### ISSUE TITLE
Mech radios give a blank message with goon chat

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10002]
![image](https://cloud.githubusercontent.com/assets/8550416/15153288/a8ea7e94-16a6-11e6-8cff-a37cdb758d8c.png)

This issue came up before.  @PJB3005

**Comment by PJB3005** [comment]
I have no fucking idea what kind of shit code mechas have to be to break this.

**Comment by Probe1** [comment]
It happened before with just regular ol headsets when gooncode was first added.
