### ISSUE TITLE
Give cockroaches a 1/50 chance of carrying a virus

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10000]
It'd flesh them out a bit more but still be pretty rare.

**Comment by Probe1** [comment]
![american-psycho-w1280](https://cloud.githubusercontent.com/assets/8550416/15145158/ff8fa2da-1681-11e6-8f1c-a211011c4aba.jpg)

**Comment by Shadowmech88** [comment]
1/50 per cockroach is not nearly rare enough considering how easy it is for cockroaches to multiply into the hundreds.
![spessman visits turkey](https://cloud.githubusercontent.com/assets/3991927/15145599/2b526516-167c-11e6-93e0-5866e59be1eb.png)

Also this issue isn't nearly dank enough to be worthy of the 10000 slot.

**Comment by ghost** [comment]
Why cockroaches? Why not mice/rats?

Saw Skowron had a cool rat sprite a bit ago that could be useful, maybe they spawn from a passive infestation event?

**Comment by PJB3005** [comment]
I think he means 1 out of 50 cockroach events.

**Comment by Probe1** [comment]
Yea I didn't realize it was gonna be 10k till it was too late.  I shoulda memed harder.

Anyway 1:100 or 1:200 whatever the number is it doesn't matter as long as its rare.  

Why I didnt' say "Why not mice?"

Players can control mice so they have something going for them.  Bugs are just kinda there.  No real interest.  I hate them because cockroaches disgust me in real life (if you've ever been to Florida you'll know we have HUGE fucking cockroaches).  But in game they're very simple and don't do very much.

**Comment by Shadowmech88** [comment]
Has anyone made it yet so that cockroaches aren't killed when a nuke goes off?

**Comment by unid15** [comment]
Isn't it already that way?

also crappy get 2/10

**Comment by Killette2** [comment]
What is the point of this?

**Comment by xpcybic** [comment]
Make it 1/10000 :balloon: :birthday: :balloon:

**Comment by Exxion** [comment]
How have there been any comments on this so far NOT mentioning this being #10000?

**Comment by Probe1** [comment]
our meme magic reserves are low

**Comment by PJB3005** [comment]
> Also this issue isn't nearly dank enough to be worthy of the 10000 slot

There has been Exxion

**Comment by Exxion** [comment]
I asked how any had failed to do so

**Comment by Intigracy** [comment]
> Also this issue isn't nearly dank enough to be worthy of the 10000 slot

There has been Exxion

**Comment by ComicIronic** [comment]
Stop wasting gets

**Comment by Probe1** [comment]
@ComicIronic is an expert on this #5000

**Comment by PJB3005** [comment]
At least he admitted he'd have let clusterfack take that if he knew what clusterfack was up to with #5001
