### ISSUE TITLE
Cryokinesis is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10008]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
That's literally it, Cryokinesis does not work.

**Comment by PJB3005** [comment]
#5633

gaaah

**Comment by Probe1** [comment]
is it?  I used it this morning on a wizard.  
1.  You have to have a target in range (1 tile works)
2.  They can't have any kinda hardsuit to protect em.

**Comment by Shadowmech88** [comment]
I think the issue might be more that there are no messages to tell you _why_ it doesn't do anything, so people just think the power is broken.

**Comment by Lorkhatosh** [comment]
It works but there are several problems with it, I suggest that cryokinesis is completely revamped.
Instead of being this strange half-broken thing it is now why not turn it into something like a fireball?
As in you actually shoot a projectile and when it "explodes" it decreases temperature in a small radius. 

I think that would make it both more useful and stop the confusion.

**Comment by Lorkhatosh** [comment]
And even if it's too hard to do the whole area freeze thing, generally turning it into a projectile and decreasing timeout between shots will be better than whatever it is now.

**Comment by MercuryDoll** [comment]
Turning it into a spell-like projectile sounds completely reasonable. Not sure if it can be reasonably made to lower room temperature (ZAS fuckery) or used to lower temperature of things other than mobs, like gas canisters etc. But if it gets implemented, please let Basilisks use the same system, for consistency and the ability to yakety these fuckers.

**Comment by Lorkhatosh** [comment]
Beam and projectile is best for Cryokinesis and for Basilisk.
Why the hell was it every anything else is byond me.

**Comment by Shadowmech88** [comment]
Tested locally. Not only does it work, but it has since been changed so that it is a ranged spell where you click on your target. It's not terribly useful, but buffs to it would be for a feature request.
