### ISSUE TITLE
Catbeast Word Filter Doesn't Work

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#10014]
#### Description of issue

Catbeasts are capable of speaking (almost entirely) without cat puns
#### Difference between expected and actual behavior

Previously catbeasts were not capable of saying 'me'. They would say Meow instead. They were also incapable of saying 'fuck', it would be filtered to yiff. Not sure if their are any other filters but at the very least these two aren't working. 'OH GOD END MY SUFFERING' and the like are still working however.
#### Steps to reproduce
1. be a catbeast
2. Attempt to say me
3. Succeed where previously you wouldn't
   -->
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
Not a clue how to fix this. Something something regex? Blame Riri.
