### ISSUE TITLE
Telepathy should work by writing people's names

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10012]
Instead of a manifest, they should be able to use telepathy by writing someone's name. This works for both the name someone appears as, and their true name. If someone is impersonating someone, the message goes for both people.

Or we could remove Greys altogether. What a huge meme.

**Comment by 9600bauds** [comment]
Should probably comment this in #10005

**Comment by Angelite191** [comment]
Oh fuck, wrong issue.

**Comment by PJB3005** [comment]
Should also make it so you get the feedback of talking through telepathy even when there's no target.

**Comment by Imagebard** [comment]
Pomf123 removed it after it was added
Fucking...
