### ISSUE TITLE
Buff vines - requested again

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10018]
I made some 74 potency vines last round, 6 maturation, 3 production, 12 yield. Nice stats, nothing astounding but still better than the normal plant. The vines did not stretch outside of botany ever, due to the way vine growth stunting works. I believe vine growth stunting is a stupid mechanic, especially since everyone knows how to deal with them. Buff vines and remove that stupid casual enabler.

**Comment by ghost** [comment]
Agreed, botany1 vines were the shit. As was being able to plant from seed packets. All anyone had to do to wreck it was vend toxin and make plant-b-gone spray in medbay or get scythes to one-man obliterate. And if it's lowpop you can stop by eng, quick chill some plasma tanks and one-tank firebomb or flamer the vines out then foam extenguisher it back ezpz.

**Comment by Kurfursten** [comment]
@Exxion no longer an issue as of #18733
