### ISSUE TITLE
makeshift magboots feature request

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10026]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
made by applying 20 metal to jackboots
they slow you down and they are considered  a bulky item (for balance and shit) and give you higher resistance to zas knockdown and from being trown away by air

**Comment by 9600bauds** [comment]
No I don't think this is a good idea

**Comment by Shadowmech88** [comment]
The current form of "ghetto magboots" is building a chair and buckling yourself into it before opening the airlock/firelock.
I really don't think there's any need for fully-functional ghetto magboots.

**Comment by unid15** [comment]
Makeshift emags when

**Comment by Ephx1** [comment]
makeshift malf ais when

**Comment by Exxion** [comment]
Aren't feature requests over the in-game bug reporter highly fucking illegal anyway?

**Comment by ihadtoregisterforthis** [comment]
Only after makeshift plasmaflood

**Comment by 9600bauds** [comment]
To actually elaborate on this: having the boots slow you down wouldn't be any different from what the real magboots already are, in that you could simply swap the boots for shoes when needed. And you can't give something a time to equip/unequip with our current inventory code.

Also the crafting recipe has same problem as the ghetto space suits: it's not hard for one bored assistant to make in preparation, but not doable by anybody in an actual emergency.

**Comment by 9600bauds** [comment]
Ghetto plasmafludd already exists, just pipe the incinerator into distro lol

**Comment by MercuryDoll** [comment]
> 20 metal

Haha, what. Good luck finding that much in an emergency, if you do it's probably because the room you are in has been blasted to shreds. Would be more feasable with 2 metal, some cable and a powercell, then they'll become basically regular magboots but they only lasts for a short time and can't be turned off, giving burn damage when the battery runs dry and you continue wearing them.

**Comment by 9600bauds** [comment]
In an emergency you'd probably be more strapped to find jackboots unless you were an officer

**Comment by FudgePucker** [comment]
Maybe two capuators, some wire and a powercell with 2 sheets of metal. They are always on and slow you down more than normal mag boots, also needs to be recharged after a few mins.

Loot machines next to you for the parts for an emergency.

**Comment by mikecari** [comment]
Just give me a makeshift pulse rifle and deathsquad armor next.

**Comment by Exxion** [comment]
In all seriousness, we already have makeshift magboots.
Office chair (which is five metal) and a fire extinguisher or telekinesis.
Or just a wheelchair.

**Comment by Shadowmech88** [comment]
Do office chairs not get moved by ZAS? I figured they would since they're not anchored.

**Comment by Exxion** [comment]
Not sure
Movecode relating to atoms with other atoms locked to them is weird
But either way, you don't get knocked down, which is the important part

**Comment by FudgePucker** [comment]
A better way to balance it would be to force slow down even when on hyperzine, meaning you can't just power game to the extreme unless you get a real pair

**Comment by MercuryDoll** [comment]
The only thing that should remove the speed penalty of magboots should be creatine :^)
well and hulking out, probably.

**Comment by Probe1** [comment]
ghetto items as a whole are fairly fukked
