### ISSUE TITLE
Can't examine GPS from inside a pod anymore / GPS should autorefresh

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10027]
I think this is part of the reason why people say finding shit in space is too hard.

**Comment by icantthinkofanameritenow** [comment]
Well, technically you can, but only if the GPS is already in your hand at the time you enter the pod. Even then, it doesn't say if you're in a vault area unless you're already right on top of it.

**Comment by 9600bauds** [comment]
To elaborate: You can't shiftclick examine a GPS in your pocket but can use it via pagedown if it's in your hand when you get on the pod

**Comment by Exxion** [comment]
Can't speak for spacepods, but I'm 95% sure you can't even refresh GPSes in your hand from within mechas

**Comment by Probe1** [comment]
just add a pod gps i'm sure pod code isn't horrible oldcode that works by magic and prayer :eggplant:

**Comment by Exxion** [comment]
Podcode is horrifying and I'm pretty confident it was written by someone who was drunk and/or asleep

**Comment by FudgePucker** [comment]
Port goon pods.
Why deal with an imitation when the real thing is now open source

**Comment by Imagebard** [comment]
What is the point of current pod code. Current pods can't even fire a fucking taser.

**Comment by Exxion** [comment]
Pods actually can fire a taser, unless that got broken AGAIN since I fixed it

**Comment by FudgePucker** [comment]
No really, port goonpods
Mining drill attachments, lasers phasers and all sorts of coolshit
Key pad locks, mason scanners, and suicide bombs.
Engineering pods, security pods, and even golden pods.
Cargo space, warp drives, and even life detectors.

**Comment by Shadowmech88** [comment]
Easier said than done.

**Comment by Exxion** [comment]
I looked into it, but the code isn't even similar
Probably easier to rewrite spacepod code from scratch
Which I might do at some point if I get the chance
Not like anyone else ever touches spacepod code anymore

**Comment by DamianX** [comment]
GPS can now auto-update and works fine from inside a spacepod.
