### ISSUE TITLE
Slimecore grenades no longer function

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10028]
#### Description of issue

A fair while ago, I was informed that you could potentially create grenades that activate slimecores, this was either not the case or is not the case now at least.
#### Difference between expected and actual behavior

Expected - EX grenades composed of double silver slime extracts and 50u of plasma in a beaker would detonate into food, it did not.

What happened -  EX Grenade bursts open. cloud of water sprays the immediate area, and nothing interesting happens.

Even following ![Deity's guide to slimefun](http://i.4cdn.org/vg/1463091151305.png) yielded no results
#### Steps to reproduce

Acquire a large or above grenade casing, an igniter, something to trigger the igniter (Signaller, timer, prox sensor, etc.),  a screwdriver, 1 or more slime cores, and a beaker that contains the reagents required to activate said slime cores.

Put them all together, the order in which the beakers and slime cores does not necessarily matter unless you want them to activate in a certain order, screwdriver the igniter and the trigger together, stick them all in the grenade, prime the grenade in some way, throw.

Notice that the grenade detonation doesn't really do anything.
#### Specific information for locating

EX grenade casings, slime extracts
#### Server revision

25348d70a08339b63f9b496a821ac1532223da39
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MercuryDoll** [comment]
> You are now in a random place, surrounded by hostile monsters and in the midst of napalm fire

Ayo, hol up. If the reaction order matters, shouldn't you and anyone nearby be teleported away **before** the monsters and napalm spawns?

**Comment by Shadowmech88** [comment]
> shouldn't you and anyone nearby be teleported away before the monsters and napalm spawns?

The grenade teleports everything in the room, including itself, to the same location.

**Comment by MercuryDoll** [comment]
Oh, that makes sense.
