### ISSUE TITLE
feature request: a new idea for a 'derelict'

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#10021]
Also sorry if I fuck up gramer or spelling, I am making a feature request at 1 at night, also somewhat sleep deprived and high

Okay, what about a pre assembled space station, but needs its "interior" done. So all the exterior walls firelocks and some windows, some interior walls, and maybe a holomap of wire and pipe positions.

Attached to that is a derelict mommi nest, with fully functioning atmospherics and partly assembled engineering, and a research and mechanics lab.

So for some map like mini that needs a special place for autisim, you got the mother of all autisim safe spaces. Maybe even include a do it your self radio system and jukebox.

You can learn how to do teg with out worrying about carbons. You can learn basics of engineering with out fucking over the round.

It would add something unique and different from wrecked space station number 32416.

Now I go to sleep, maybe I will edit this tomorrow, maybe

**Comment by icantthinkofanameritenow** [comment]
So you basically want a pussified derelict because you don't want to do real autism? That's just sad. It completely misses the point of it being a derelict in the first place.

**Comment by FudgePucker** [comment]
Not really, it has almost no piping or wiring, all that's really done for you is some walls. So unless you like spending ten hours making rwalls, it is just a minor convenience.

Also it is a unique flavor, it is a space station in the middle of construction, not just another crashed space station. Imagine floating in space and coming by a partly done space station. Bonus points if those adorible autistic crab robots are in the middle of piping and wiring.

**Comment by Shadowmech88** [comment]
What's the functional difference between a station that's been halfway built and a station that's been halfway destroyed?
What could MoMMIs do on this station that they can not already do on the Derelict?

**Comment by PJB3005** [comment]
Extra station / vault? sure.

Replacement for derelict? no.

**Comment by FudgePucker** [comment]
Spend more time constructing and less time fixing.

For example, let's say you want to pray for a shard and spent up a SME. All the emitters and collectors are neatly stacked in engineering portion instead of the other side of the station.

More time spending piping less time space proofing.

More time doing autism less busy work. Time is important because by the time you are done fixing holes an antag has put uneven flooring in the bridge and the captain calls the shuttle because he stubbed his toe.

**Comment by FudgePucker** [comment]
I mean maybe a vault would work, but then having a mommi spawner might not work, also if you did have one it would have to NEVER spawn on the same zlevel as the main station, because the zlevel locked mommis would just float over to the main station.

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker 

What you call busywork is in fact that very same autism you want more of. It sounds more like building just isn't your thing. 

Jeez, if you just want to shit around with wiring and pipes or experiment with the engines, just make a test server.

**Comment by Skullyton** [comment]
Maybe a vault with a MoMMI spawner, with the same ruling as derelict MoMMIs?

**Comment by ComicIronic** [comment]
Autism spiders do not need more reason to play apart from the rest of the game.
Being a derelict spider is something to do after you die.
