### ISSUE TITLE
Centcomm beach/bar booze vendor

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10032]
Allow it to start hacked, when we get to centcomm we still need a bartender to dispense from it. That's gay, the round's over, let me enjoy booze on the beach.

**Comment by FudgePucker** [comment]
Implying you will have enough time to pour a drink during post round death match

**Comment by Killette2** [comment]
Who said I'm going to be drinking it and not pulling a sawbones?

**Comment by Exxion** [comment]
If memory serves,  it's empty anyway
