### ISSUE TITLE
Cannot use resist to uncuff while in an active fire due to stop, drop, role having priority.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10037]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision eb21d725b53c5901bd27600ee074d028b57983cf 
> 
> General description of the issue
> Got cuffed while testing a fire. Couldn't uncuff myself due to stop dropping and rolling every time I used resist. My captor died in the flames leaving me trapped.
> 
> What you expected to happen
> Hit resist and start the uncuff process
> 
> What actually happened
> Stop drop and roll all like 30 times I tried it
> 
> Steps to reproduce if possible
> set the room on fire with a ton of plasoxy so the fire keeps going then cuff yourself/get cuffed

**Comment by PJB3005** [comment]
The issue is that this is completely contextual.

In this example stop drop and roll first is dumb, but in others it can make a ton more sense.

**Comment by clusterfack** [comment]
I don't really have a problem with it the way it is.

**Comment by Killette2** [comment]
> Hold on, let me fucking UNCUFF MYSELF FOR 30-180 SECONDS, then put out what fire I'm on.

The only exception would be if you had a borer, hardsuit, method of rapid healing (IE changeling fast rejuv for 8 genomes), or genetic power to protect you from that fire.

**Comment by Imagebard** [comment]
Sarah how the fuck did you even get in this predicament?

**Comment by ComicIronic** [comment]
VERBS
ARE
DUMB

**Comment by Shadowmech88** [comment]
If you're not wearing an atmos suit, the fire would kill you before you could uncuff yourself anyway.

I think the easiest solution is simply to make it so that people wearing atmos suits are incapable of catching fire.

**Comment by Killette2** [comment]
That idea sounds kinda stupid and strong.

**Comment by gbasood** [comment]
~~Didn't we have an issue where resisting in a fire did roll because remove cuffs took priority before this was changed?~~

Nevermind, duplicate issue of #4681

**Comment by Shadowmech88** [comment]
@Killette2
In what way? You don't take damage from being on fire if you're wearing an atmos hardsuit anyway.

**Comment by Killette2** [comment]
There's a reason firemen don't actually go directly in the fire. It's heat resistant, not a fucking space suit.

**Comment by Shadowmech88** [comment]
There may be some confusion here.
When I said "atmos suits" I was referring to atmospheric hardsuits, not firesuits.

**Comment by clusterfack** [comment]
We can have it refuse the first 'are we on fire, fix that' check and put it at the end in the case where you are wearing something that blocks you from being burned.

**Comment by PJB3005** [comment]
> VERBS
> ARE
> DUMB

Somebody agrees with me about verbs!

**Comment by ghost** [comment]
Probably should have said I was in an atmos suit, sorry. Though it does apply to shit fires and a firesuit, eng rig, sec hardsuit, maybe the warmsuit? and who knows what else.

To imagebard, lingerdinger was being a butt so he got the burn bag when he tased me. Then we yakkety'd until he roasted.

**Comment by ghost** [comment]
Got the bug where you put yourself out with an extinguisher when on fire but you're still "on fire". Went and bonked beepsky and yup, can't resist out of cuffs.

**Comment by gbasood** [comment]
Maybe make cuffs have their own button????

Actually, the fact that resist is a multi-purpose UI button only used in like 3 situations, 2 of which can overlap, is in itself dumb

**Comment by Killette2** [comment]
resist has 4 functions I can think of. Uncuffing, breaking out of lockers, rolling out fire, resisting grabs (if it feels like working before getting slammed anyways, but I think this was fixed).

**Comment by PJB3005** [comment]
Resist being buckled to things. Including vines.

**Comment by Killette2** [comment]
Not anymore PJB, I think you have to click on the vine sprite itself like you're in a chair, but it may work too.
