### ISSUE TITLE
Thrown Trash stays on station z-level

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10036]
![00000](https://cloud.githubusercontent.com/assets/7571238/15257749/332e6c2c-191e-11e6-9db6-00be1d791d76.png)

Henk

**Comment by Probe1** [comment]
lel

**Comment by Imagebard** [comment]
Realized this is a allegory for defficiency itself
Closing

**Comment by Killette2** [comment]
Waste not want not
