### ISSUE TITLE
Sleeper consoles spawning at the wrong time

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10033]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
#### Revision (Should be above if you're viewing this from ingame!)

eb21d725b53c5901bd27600ee074d028b57983cf 
#### General description of the issue

When making a flatpack sleeper, the sleeper console spawns on the side of the flatpack fabricator.
#### What you expected to happen

sleeper console spawns when the flatpack is crowbarred open
#### What actually happened

sleeper console spawns as soon as the flatpack is created
#### Steps to reproduce if possible

make a sleeper in the flatpack fabricator

**Comment by PJB3005** [comment]
Dupe.
