### ISSUE TITLE
The REAL reason of the TEG fuckery.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10034]
#### Description of issue

The TEG's main piece which does all the processing ticks faster than the pipenet, causing it to effectively run at double the speed for the pipenet every few ticks. When this happens it jams because the gas hasn't been moved before last tick.
#### Difference between expected and actual behavior

TEG to tick at the same rate as pipenets, but it actually ticks faster.
#### Steps to reproduce

Make a TEG.
#### Specific information for locating

[`generator.dm`](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/power/generator.dm)
[`Processes/pipenet.dm`](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/controllers/Processes/pipenet.dm)
[`Processes/power.dm`](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/controllers/Processes/power.dm)
#### Length of time in which bug has been known to occur

a6b0c9a818aaabb14abfac4cf5ac50cb19a97c8b
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round (has the TEG been set up in the last 7 days?)
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
Told ya

Also, wouldn't this mean that the TEG would never be able to be set up under your changes?

You did test it yourself, right?

**Comment by Killette2** [comment]
Why test it?

Also I believe, the best solution, is to push byond to run at 60fps.

**Comment by gbasood** [comment]
@Killette2 doesn't solve hte problem we're having
the process intervals are still the same

**Comment by Shadowmech88** [comment]
Couldn't this be fixed by just adding it to the list of things that tick on pipenet processes instead of the list of things that tick on power processes?

**Comment by PJB3005** [comment]
Nope, the pipe net process filters out non pipe machinery.

**Comment by Shadowmech88** [comment]
And there's no way to have it process at the same time as the pipes otherwise, right?

So what then? We make the TEG into a super special snowflake "pipe"?

**Comment by PJB3005** [comment]
I've got an idea that should work, ideally.

**Comment by Intigracy** [comment]
Make it pipe machinery?

**Comment by PJB3005** [comment]
Wait what when did I close this?

**Comment by PJB3005** [comment]
Holy shit it's way worse than I thought.

![](http://i.imgur.com/udV49S4.png)

This is debug output from a local fix branch.

pipenet is a pipenet tick

TEG is a TEG tick post-fix

TEG, power is how fast it USED to tick.
