### ISSUE TITLE
Air alarm computer on deff is fukd

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#10039]
Oh man, leave for a few weeks and I already find a bug in the first round.
The map is deff
The computer is the air alarm master computer
The image shall speak for itself.
![oh wow](https://cloud.githubusercontent.com/assets/12202731/15263875/c379973a-193b-11e6-8a25-da4329743e5f.png)

**Comment by clusterfack** [comment]
Did you search the issues before posting this?

**Comment by FudgePucker** [comment]
...
No.
Going to close it then, boy am I silly.
