### ISSUE TITLE
Go back to NanoUI CMC/adv. sec cameras.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10035]
BYOND 510 has built in JSON.

**Comment by ComicIronic** [comment]
What do you mean, go back? What happened to them?

**Comment by clusterfack** [comment]
There's literally no reason to do that since they would have the bug caused by 500x500. Unless you want to fix that? Are you going to fix that?

**Comment by Exxion** [comment]
Well, the HTML interface seems to have some arcane caching issue that may well be a BYOND issue while NanoUI doesn't
The question is whether it would be easier to make NanoUI suck less and change those back or to fix the HTML interface caching shit

**Comment by 9600bauds** [comment]
what did he mean by this?
