### ISSUE TITLE
MoMMIs using stun batons use their cell instead of the baton's for charge.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10049]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision f9465119e7934453a214623faa34a0f8a6bdcfd0 
> 
> General description of the issue
> Issue title
> 
> What you expected to happen
> Baton to be drained on a slap
> 
> What actually happened
> MoMMI cell was drained instead
> 
> Steps to reproduce if possible
> Become a MoMMI, grab a stun baton, slap someone with it.

**Comment by AutismSpider** [comment]
So what happens if you put plasma in the baton cell then slap some one with it as a mommi?

Does the baton blow up or the mommi?

**Comment by PJB3005** [comment]
The baton is shit code and sees the user is a silicon so it assumes it's a sec borg, thus taking from the MoMMI's cell.

**Comment by Shadowmech88** [comment]
Wow, that sounds _really_ shitty.
It'd be best to just make the borg stun baton its own subtype of regular stun batons, wouldn't it?

**Comment by AutismSpider** [comment]
@Shadowmech88 sounds like old shit code.

**Comment by AutismSpider** [comment]
Now that i think about it when using E sword as a mommi it drain lot of power for god knows what

**Comment by Shadowmech88** [comment]
Eswords don't even have internal cells.
Maybe it's got the same problem that stun batons do, hacked standard borgs do get energy swords.

**Comment by AutismSpider** [comment]
Yeah i think its doing a call for Emag borg Energy sword when mommi hits some one with it

**Comment by ComicIronic** [comment]
I love shitcode.

**Comment by PJB3005** [comment]
Same issue for shovels by the way.

**Comment by Shadowmech88** [comment]
> shovels require power to use

Because of mining borgs, or what?

**Comment by PJB3005** [comment]
Yep.

**Comment by 9600bauds** [comment]
Well, to be fair, these checks are all from before MoMMIs
Can you blame oldcoders for assuming nobody would be enough of a madman to make a robot WITH HANDS?

**Comment by PJB3005** [comment]
No, that's not the issue.

The issue is that oldcoders should've made a borg specific subtype.

**Comment by 9600bauds** [comment]
They did that with droppers and trays.
The results were much more catastrophic than this.
Oldcoders just couldn't into OOP

**Comment by AutismSpider** [comment]
@9600bauds It took a mad man to build this robot and all the awfulness to come with it
![pharaoh2](https://cloud.githubusercontent.com/assets/10268342/15276868/ba7c6ffc-1ab9-11e6-9b89-b21ce13875c9.jpg)

**Comment by PJB3005** [comment]
@9600bauds **sub**type.

Those examples were their own snowflake types.

**Comment by 9600bauds** [comment]
fair point
