### ISSUE TITLE
Lots of modes do not display the scoreboard when the round ends

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#10041]
Rev with revolutionary victory
Nuclear with nukeops victory
Malf I think?
Heist definitely

**Comment by Allspice** [comment]
Cult and blob too.

**Comment by PJB3005** [comment]
Nuke ops don't because the nuke has its own hard-coded round end stuff.

**Comment by gbasood** [comment]
I mean
It can still open the scoreboard
If scoreboard needs to be changed so that it doesn't do its own round-end logic from within scoreboard code then good it should be

**Comment by DeityLink** [comment]
Critically Outdated.
