### ISSUE TITLE
Examining liquid fuel on the ground freezes your client for a few seconds and outputs a weirdly-colored and distorted icon

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10053]
Taking bets these are related.

**Comment by ComicIronic** [comment]
This is the same thing as the invisible wall for mimes - the missing icon messes up with chat or something else.

**Comment by Exxion** [comment]
It's the same sprite, too
I wonder what about it fucks up

**Comment by PJB3005** [comment]
I need to investigate this.

**Comment by clusterfack** [comment]
Is this still happening?

**Comment by Exxion** [comment]
Yes, as of a few seconds before this comment.

**Comment by Exxion** [comment]
Fixed by #20289
