### ISSUE TITLE
how 2 escape derelict as derelict MoMMI

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10054]
1) go to derelict teleporter
2) put yourself in a locker
3) have another MoMMI push the locker in the teleporter, or build a conveyor belt to do it all by yourself

**Comment by clusterfack** [comment]
![wx1wp](https://cloud.githubusercontent.com/assets/8516830/15271722/29adce54-1a1d-11e6-843c-582ef5c47b3d.jpg)

**Comment by kol1th** [comment]
I did it once on metaclub, without locker fuckery. Just straight through the teleporter. That was a while ago, however.

**Comment by AutismSpider** [comment]
if its not locker push its mass driver or have a station mommi jet pack you off it

**Comment by Hoshi-chan** [comment]
You know, if we had a MoMMI fabricator on the station that players on-station had to supply with materials in order for it to function, we wouldn't have the problem of players trying to become derelict MoMMIs and reach the station.

Just saying. Just have the fabricator restrict a ckey from fabricating a MoMMI more than once, and ensure that they don't drop brains or posibrains on death. That would prevent the most notorious of shitters from spawning loads of MoMMIs or doing it and killing themselves to get back into the round.

**Comment by ComicIronic** [comment]
Main station MoMMI fab would be stealing jobs from Research, Robotics, and most of all Engineering. People would also avoid readying to bypass the autism spawn cap for the main station. 
It massively cheapens death along with everything else. SaMIs were the exact same issue, except they could talk for some reason. 

You want to be an afterdeath MoMMI on main station?  Wait for research to make posibrains, ask the roboticist to make you one.

**Comment by jknpj** [comment]
Wasn't this fixed?

**Comment by PJB3005** [comment]
It was.
