### ISSUE TITLE
Constant BYOND crash or client 'sticking', only on /vg/station

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#10052]
#### Description of issue

When I connect to /vg/station, my client either crashes within ~15 seconds (white screen of death) or I get the 'stuck' client bug where I can still hover over things and see their names, but can't see myself moving, interacting with anything, etc. normally followed by client crash - I'm assuming this is a well known bug as I've seen people talk about it before and have experienced it a couple of times in the couple of years I've been with /vg/station.

I have downloaded the server files and successfully hosted and played on a private server running /vg/'s code with no issue.

I have fully uninstalled and reinstalled BYOND, cleared the cache, rebooted my computer and sacrificed a puppy, with no success.

When I first connected to the server, I was able to set up my character and join the round with no problems. Within a few minutes, this issue developed and has only been getting worse, to a point where I can get as far as the lobby before a freeze/crash.
#### Difference between expected and actual behavior

Expected: no crashes
Actual: crashes
#### Steps to reproduce

Join /vg/station 
Crash
#### Length of time in which bug has been known to occur

I haven't played since ~January and came back to the game today. I updated BYOND to the latest (510 beta) version after uninstalling the old version. Within seconds of connecting to the server, the game crashes. This has never happened to me before in this manner.
#### Server revision

Unable to reliably enter the game, but its the one that's running right at this minute. I know this isn't helpful, but the game's reached a point where I connect and it freezes up before I can type anything.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [  ] Issue could be reproduced by different players (someone mentioned they had the same problem in the thread, not sure if it's identical)
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Literally fuck all we can do about this.

**Comment by PJB3005** [comment]
http://www.byond.com/forum/?forum=4

**Comment by Inorien** [comment]
fug man i was just told to post it here

Oh well, I'll try again tomorrow when this Purge shittery is over, and post updates if I make any progress.

**Comment by AutismSpider** [comment]
Well some thing up with byond game game plays fine for a bit and just freezes and crash's non stop.

**Comment by SysadminJeroen** [comment]
Maybe this can fix the issue.

```
[20:02:47] <Jeroentje> I'm still having a problem where my game freezes up after I'm spawned. I can play on a local server and on CM.
[20:05:01] <-> NikNak|Away is now known as NikNak
[20:05:15] <Clusterfack_> what byond version
[20:08:20] <Jeroentje> @Clusterfack_: Version 5.0 Beta 510.1342
[20:08:45] <Clusterfack_> yeah I'm going to initially suggest downgrading to 1341
[20:08:50] <Jeroentje> @Clusterfack_: I have about half a second when I open the game to interact with the world, and then it freezes up.
[20:08:53] <Clusterfack_> I think 1342 has issues
[20:09:18] <Jeroentje> Clusterfack_:  I have no clue on how to downgrade, I'll look if I can find a download.;
[20:09:50] <Jeroentje> I got a DL.
[20:09:56] <Jeroentje> http://www.byond.com/download/build/510/510.1341_byond.exe
[20:09:57] --> c0nker (~c0nker@Rizon-500ECC4.dynamic.reverse-mundo-r.com) has joined #vgstation
[20:10:31] <-- Jalleo (~Jalleo@Rizon-F980B321.cable.virginm.net) has quit (Quit: see ya tomorrow)
[20:12:50] <Jeroentje> @Clusterfack_, downgrading to http://www.byond.com/download/build/510/510.1341_byond.exe resolved my issue.
```

**Comment by Inorien** [comment]
I disabled ActiveX filtering through Internet Options and haven't had any issues so far. If it comes back I'll try downgrading

**Comment by clusterfack** [comment]
If you find any work arounds or what have you give details here http://www.byond.com/forum/?post=2084664

**Comment by AutismSpider** [comment]
Downgrading fix it for me

**Comment by Probe1** [comment]
@clusterfack link doesnt work

**Comment by SysadminJeroen** [comment]
@Probe1 "Downgrading fix it for me" -@AutismSpider

**Comment by Probe1** [comment]
Fuck everything.

**Comment by SysadminJeroen** [comment]
@Probe1 Did you fix it?

**Comment by Probe1** [comment]
Haven't tried dwngrade yet.

**Comment by Inorien** [comment]
Downgraded to 510.1320 and it seems to have fixed everything.

**Comment by AutismSpider** [comment]
New beta is buggy as shit so just downgraded to older one

**Comment by Probe1** [comment]
Same.

**Comment by clusterfack** [comment]
510.1343 fixed this and should be readily available now
