### ISSUE TITLE
Captain's Armor can't hold big gas tanks

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10057]
Why?

Not sure if oversight or balance, won't tag

**Comment by clusterfack** [comment]
So captains dont wear it everywhere

**Comment by 9600bauds** [comment]
Doesn't stop them unless there's a breach
At which point, they SHOULD be using the armor, it's a goddamn spacesuit

**Comment by Kurfursten** [comment]
I believe what clusterfack means is that engineering and mining suits tend to be "throw on and forget" style suits because large tanks last an entire shift

Hell, a filled extended tank can last an entire shift

**Comment by 9600bauds** [comment]
Don't even need to fill it or adjust the KPA lol

**Comment by Killette2** [comment]
What's wrong with little gas tanks, why do you need a big one? Compensating for something capt'n?

**Comment by Blithering** [comment]
I think this makes sense, it's more of an incidentally space-proof combat armour than a space suit. Captains get an oxygen jetpack as well, so that's something to breathe out of.

**Comment by 9600bauds** [comment]
muh slots
