### ISSUE TITLE
Lost teeth showing IDs the player was wearing at the time they lost the teeth

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10065]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
http://puu.sh/oSILr/b88b199430.png

**Comment by ComicIronic** [comment]
Use of real_name needed instead.

**Comment by Imagebard** [comment]
Why not just show "teeth"
Why should someone knocking my teeth out reveal I'm a undercover agent
How do people know what teeth came form where
Is this some kind of trickery

**Comment by ghost** [comment]
Everybody on station is a trained dentist

**Comment by ComicIronic** [comment]
Dental records are a hell of a thing

**Comment by Shadowmech88** [comment]
The detective scanner should be able to get DNA off of teeth so he can match it to medical records.
But yeah, otherwise they should always just show up as "teeth."

**Comment by Exxion** [comment]
Not to mention that changing the name of a stackable item is Bad

**Comment by Killette2** [comment]
I can tell this is really Honker's tooth and he was in disguise, but by these lines it was obvious he was wearing Captain Crunch's ID and has all access!
