### ISSUE TITLE
Pocket Happiest Mask

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#10066]
![strange](https://cloud.githubusercontent.com/assets/17928298/15275891/333e194c-1aae-11e6-8a39-8d6559d7ca85.jpg)
#### Description of issue

Happiest Masks activating while inside your pocket
#### Difference between expected and actual behavior

Expected: Nothing
Actual Behavior: EVERYONE SHOULD SMILE!
#### Steps to reproduce

Put a happiest mask in your pocket
#### Length of time in which bug has been known to occur

It happened to me a few weeks ago when i found 5 masks in a single digsite too, but i forgot to report because sleepy
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
Good news is that it doesn't actually trigger !!FUN!! unless you're wearing the mask
