### ISSUE TITLE
Make oxygen tanks last way less long.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10063]
Just a regular big oxygen tank at the default pressure and outlet pressure lasts the entire shift.

**Comment by 9600bauds** [comment]
Issue with this is that there are three options:
- Give big tanks a smaller volume (breaks everything)
- Increase human oxygen consumption (small tanks last 15 seconds)
- s n o w f l a k e

**Comment by ComicIronic** [comment]
But why

**Comment by Shadowmech88** [comment]
> Give big tanks a smaller volume (breaks everything)

Why would it break anything?

**Comment by Probe1** [comment]
@ComicIronic Because one big blue from the dispenser without filling it up will last at _least_ 3 hours.  I've never had one run out ever.

@Shadowmech88 bombs.

**Comment by 9600bauds** [comment]
Bombs, flamethrowers, pneumatic cannons etc

**Comment by clusterfack** [comment]
I have a solution, we add oxygen poisoning so you have to use AIR tanks, bwahahaha

**Comment by ComicIronic** [comment]
No, I understand that you think the air tank is too big.
I'm asking you WHY it's too big. What's wrong with the tank lasting as long as it does?

**Comment by Probe1** [comment]
1.  They're commonplace and can fit in hardsuits storage slot
2.  They have effectively unlimited capacity

One or the other makes for interesting gameplay.  Both makes it thoughtless.  Just get the blue one unless you're security/antag/whatever and need that slot for a gun.

**Comment by ComicIronic** [comment]
Is it interesting to have to refill the tank as menial work every so often?

**Comment by Probe1** [comment]
Menial?  Maybe if you're on the station and everythings fine.  But if you're in deep space or the stations massively destroyed its a fight for life.  Plan ahead.  Think about shit.
