### ISSUE TITLE
Round end report no longer shows.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10061]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 8f20ff31d56feb5e4cf157a43b9b124eda3e4d50 
> 
> General description of the issue
> Title. It's no longer shown in logs either, no list of traitors etc.
> 
> What you expected to happen
> Round ends and the list of antags, silicons, etc. show.
> 
> What actually happened
> It doesn't.
> 
> Steps to reproduce if possible
> Shuttle dock at CentComm.

**Comment by Probe1** [comment]
Been broken since yesterday.

**Comment by SysadminJeroen** [comment]
Do we know which commit broke it? If not I could bisect it.

**Comment by Shadowmech88** [comment]
Seems to be something to do with Wages.

**Comment by Probe1** [comment]
Looks like pomf may have fixed it in https://github.com/d3athrow/vgstation13/commit/9499aeaa627b29d73d750f86c9ac3c1956f2b5ee

**Comment by gbasood** [comment]
s-sorry

**Comment by Probe1** [comment]
:eggplant:

**Comment by PJB3005** [comment]
That's it I'm making a 100% tested tag.
