### ISSUE TITLE
Central atmos computer icons not lined up with the map.

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#10073]
![39d2fc1bec304224ae2e96700bfa6f88](https://cloud.githubusercontent.com/assets/5650556/15277638/4676bf76-1ad8-11e6-8207-ccf9bae52852.png)
 REAL PROBLEM THIS TIME GUIES, I SWEAR!

**Comment by Probe1** [comment]
NEW ISSUE EVERY DAY UNTIL SOMEONE FIXES IT

**Comment by AlphaBuffalo** [comment]
Wait, I didnt see an issue...

**Comment by clusterfack** [comment]
Someone literally made a duplicate about this like days ago, come on

**Comment by Probe1** [comment]
FIX OR RIOT
FIX OR RIOT
FIX OR RIOT
FIX OR RIOT
FIX OR RIOT

**Comment by AlphaBuffalo** [comment]
I meant I didnt see any issues mentioning this. I havent been playing in a few months and that was the first time I used the dang thing.
