### ISSUE TITLE
airlocks get closed instantly before the animation ends

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10079]
(WEB REPORT BY: cumoverme REMOTE: 172.93.109.202:7777)
Revision: 9499aeaa627b29d73d750f86c9ac3c1956f2b5ee 

General description of the issue

Doors get closed instantly before the closing animation ends, it makes you sometimes get ZAS'd when doubleclicking it

**Comment by nervere** [comment]
Feature.
