### ISSUE TITLE
Game crashes on latest beta in this area on Box

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10082]
![image](https://cloud.githubusercontent.com/assets/8550416/15294800/b3ef491e-1b5b-11e6-98a0-1435d22e15f6.png)

Whenever I enter here, the game crashes and repeatedly crashes.  I don't know what the cause is.  I updated to the latest beta this morning.  It has occurred across multiple rounds.  After the initial crash the game repeatedly crashes whenever I rejoin after about 5~ seconds.

Being teleported to a new area does not resolve the issue.

Clearing my cache did not resolve the issue.

**Comment by PJB3005** [comment]
Get a stack trace of the error to the BYOND forums.

**Comment by Probe1** [comment]
Where?

**Comment by SysadminJeroen** [comment]
#10052
