### ISSUE TITLE
Mice understand human speech?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10087]
(WEB REPORT BY: angeliteentyshak REMOTE: 172.93.109.202:7777)

> Revision 07570c05999a84a475d2c122ebac14459b4c83fd 
> General description of the issue
> Mice understand humans perfectly.
> 
> What you expected to happen
> Not to understand human speech
> 
> What actually happened
> I understood human speech
> 
> Steps to reproduce if possible
> 1. become mouse
> 2. find speaking human
> 3. understand them

**Comment by ihadtoregisterforthis** [comment]
Feature

**Comment by Intigracy** [comment]
They understand it but can't speak it iirc.

**Comment by Probe1** [comment]
wut

no, thats definitely a bug and a recent one.  as of 2 weeks ago mice couldn't understand human speech.

**Comment by Shadowmech88** [comment]
> as of 2 weeks ago mice couldn't understand human speech

The first day that Goonchat was merged I remember playing mouse and being able to understand humans, that was more than two weeks ago.

Why _shouldn't_ mice be able to understand humans anyway?

**Comment by Probe1** [comment]
I mean they're mice.  That's definitely weird though, I swear I couldn't understand them and they got a pAI to translate.

**Comment by Shadowmech88** [comment]
> I mean they're mice

Yes, but they're also inhabited by observers and can only be spawned by observers.
Why would an observer _ever_ want to become a mouse if they lose their omniscience AND become incapable of understanding anyone?

**Comment by gbasood** [comment]
They actually weren't meant to understand humans (in code terms at least) when I added a mouse language.

But if someone changed it since then, cool. Playing as a mouse and not being able to understand shit means you are literally just a thing running around waiting to get squished. Understanding SOMETHING means you can at least dick around a bit before getting squished.

**Comment by Exxion** [comment]
Mice have, to my knowledge, _always_ understood humans
I have talked with them many times over a period of months
You just need special equipment to understand the mice

**Comment by Intigracy** [comment]
Understanding and speaking a language are handled seperatel fyi.

**Comment by clusterfack** [comment]
Mice are supposed to understand human speech, hell even I can remember using universal recorders to translate for our pet mice.
