### ISSUE TITLE
Simple Xenos unencumbered by space

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10080]
They swim through space like they're carp which is super dumb. While you're free floating they dance all around you as if moving on ground, and you can't disengage by throwing something. Unlike a true player-filled xeno which is equally helpless as a player in space,

Please get rid of this dumb inconsistency.

**Comment by Brolaire** [comment]
Same goes for spiders and asteroid critters

**Comment by Imagebard** [comment]
>Spiders
I'm pretty sure they slip around and need web to move at all

>Asteroid Critters

What you want them to just fly off

**Comment by Brolaire** [comment]
I thought he was talking about simplemob Xenos?

**Comment by Imagebard** [comment]
The inconsistency there is important because xenos are used as both simple mobs and player mobs. The others I mentioned are nearly unplayable.

**Comment by Brolaire** [comment]
Right, I see what you mean. My point was though that I think all simplemobs ignore space movement and I assume NPC xenos are children of simplemobs

**Comment by Killette2** [comment]
what are gold slime core mobs?

**Comment by Imagebard** [comment]
Whatever do you mean

**Comment by Killette2** [comment]
Wouldn't gold slime cores be able to spawn the new AI xenos?

**Comment by Imagebard** [comment]
Yeah.

**Comment by Killette2** [comment]
And didn't you just call those adminbus only?

**Comment by Imagebard** [comment]
I think you've made a small reading mistake on your side.

**Comment by Killette2** [comment]
Well I just woke up so that's a possibility, but what are you calling adminbus only? Player xenos are still not adminbus only either.

**Comment by Imagebard** [comment]
I'm saying player controlled spiders and asteroid mobs are adminbus only.

**Comment by Killette2** [comment]
> He doesn't know how to become one

**Comment by ihadtoregisterforthis** [comment]
I don't think the issue is AI xenos being different than player controlled ones, but AI xenos not drifting in space.

**Comment by Imagebard** [comment]
Yeah, that kinda makes them different than player controlled ones.

**Comment by Shadowmech88** [comment]
This kind of movement thing applies to ALL simple_mobs.
Even Russians are able to swim through space for a short time before it kills them.

**Comment by Exxion** [comment]
Simple mobs have weird space movement, in that both their natural movement and space drifting apply to them
Watch them drift through space while trying to avoid them. They can't exactly walk through space as if it's a floor, but they can significantly alter their drifting path. They can heavily curve their paths, but not totally reverse them. If they try to attack something in the exact opposite direction as they are drifting, they sort of jig back and forth and very slowly drift away.

**Comment by Shadowmech88** [comment]
Personally I think only space carp should be capable of affecting their path to that degree in space. Other simple_mobs should be as helpless as carbons are.

**Comment by clusterfack** [comment]
If we do that then have one of two scenarios, simple mobs will jump off plating to their obvious demise of looping through space a billion times. Or they don't and anyone with a gun can kill any simple mob without ever being in any danger whatsoever from 2 space tiles away.

**Comment by Imagebard** [comment]
As Clusterfack said.

**Comment by Shadowmech88** [comment]
I see your point, but it still doesn't sit right with me.
I wish I could think of a better solution.

**Comment by ComicIronic** [comment]
If only AI wasn't tied to simple_animals

**Comment by MercuryDoll** [comment]
I'm for making simple_mobs unable to swim in space. Just make them avoid goin on space tiles. Hell, spiders could probably produce web to walk on it like lattice. Only spacecarps and similar mobs should be able to steer in freespace.

**Comment by Shadowmech88** [comment]
But like Clusterfack said, then you run into the issue of anyone with a jetpack being able to kill simple_mobs without risk from the safety of space, since the mobs won't chase them into space.

**Comment by PJB3005** [comment]
Simple mobs in space are already piss easy to lose with a jetpack.

**Comment by Shadowmech88** [comment]
But if you don't have a jetpack, they can catch up to you easily and you can't get away from them by throwing things.

**Comment by Kurfursten** [comment]
Jetpacks are expensive and make you give up your backpack. If that makes killing simple mobs a lot easier that sounds like good design.

I for one am not concerned if the new meta to countering gold slime cores will be "get a jetpack and lure every enemy to a window"

**Comment by SonixApache** [comment]
Make simple mobs not charge into space? Some self-preservation at the very least, like that recent update that made it so mobs don't shoot through friendlies.

**Comment by Imagebard** [comment]
Okay, so they just STAND THERE while you shoot them to oblivion
Makes sense for ranged mobs(Ala hivebots) but otherwise its dumb.

**Comment by Exxion** [comment]
We need to overhaul pathfinding
We're just using stock BYOND pathfinding (`walk_to()`), and we're not even using it well

**Comment by Brolaire** [comment]
This is some top-tier coding challenge probably, but would it be possible for the simple mobs to consoder the position of the person who's harming them?
My idea was: If a simple mob is harmed by ranged attacks, call the type of tile the harming person is standing on. If it's a space tile, make it run away or hide out of sight if that's possible.  I hope this isn't too unrealistic of an idea

**Comment by MadmanMartian** [comment]
From what I can tell, this is no longer a bug that occurs @Shadowmech88
