### ISSUE TITLE
The recycler is fucked up again

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10088]
If you put metal or glass in the recycler smelter, it gives abysmal values such as 0.0031 for 50 metal or glass sheets. Other ores like plasma worked fine. Fix this shit.

**Comment by 9600bauds** [comment]
Has it ever been in a state of not-fucked?

**Comment by PJB3005** [comment]
Yes.

**Comment by Killette2** [comment]
The fuck is it a balance issue for? You put in 50 sheets and you can't even reprint 1.

**Comment by clusterfack** [comment]
@bauds you changed it here when you removed the recycle procs
https://github.com/d3athrow/vgstation13/pull/7620/files

Before I dig further can I ask why?

**Comment by 9600bauds** [comment]
Basically IIRC that function was oldcode which comic didn't clean up when he implemented material datums, so I moved the few remaining items that had that oldcode to the new method (just give them proper material datums)

**Comment by clusterfack** [comment]
Yeah but stacks have an amount var which modifies how much of the material you actually have, which is why they had a special recycle proc?

**Comment by 9600bauds** [comment]
They now use the same recycle function as everything else, meaning they actually have their material amounts updated when the amount of sheets in the stack is changed
Get a stack of a few sheets and VV their materials, should be 3750*amount

**Comment by clusterfack** [comment]
I cant reproduce this even so

**Comment by Killette2** [comment]
> Unable to reproduce
> Feature Loss

/v/ is really getting to me

**Comment by 9600bauds** [comment]
hhhehehhehehehhehhe

**Comment by ComicIronic** [comment]
Is this a bug or isn't it

**Comment by clusterfack** [comment]
As far as I can tell it isnt
