### ISSUE TITLE
Plasma contamination bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10086]
What I did
1. Everything was on fire
2. I wanted out of my office, I disposaled myself
3. While in the pipes I passed through a flaming medbay
4. Noticed after this happened, even before I got through disposals, noticed my clothes were contaminated

So I conclude, since my office wasn't touched by plasma prior, that you can get contamination by going through pipes under a plasma filled area.

**Comment by PJB3005** [comment]
Contamination removed when?

**Comment by Killette2** [comment]
Hopefully soon, the only fun thing about it is when you defibrillate a contaminated person

**Comment by Shadowmech88** [comment]
I wouldn't mind contamination so much if plasma couldn't contaminate _through_ airtight hardsuits.

**Comment by 9600bauds** [comment]
Contamination removed when?

**Comment by Killette2** [comment]
When you uncode it

**Comment by Probe1** [comment]
just fix hardsuits contamination

**Comment by PJB3005** [comment]
When pomf disables it in the server config because he actually can.

**Comment by Killette2** [comment]
Who's pomf?

**Comment by ComicIronic** [comment]
Doesn't matter if Hardsuits are airtight.  PLASMAGUARD exists for a reason.

**Comment by Shadowmech88** [comment]
> PLASMAGUARD exists for a reason.

Right, but I'm saying that hardsuits without PLASMAGUARD should get contaminated without also contaminating your jumpsuit, gloves, et cetera, since the plasma isn't actually touching your jumpsuit and gloves and such because you're wearing an airtight suit.

How's the plasma going to contaminate something that it can't even touch?

**Comment by ComicIronic** [comment]
Because hieng particles don't care about what's airtight.
I mean, who says the suits are airtight in the first place? Last I checked, you don't put a mask on in space and you still suffocate, suit or no suit.

**Comment by Shadowmech88** [comment]
If the suits were not airtight, you'd take low pressure damage in space while wearing them.

**Comment by 9600bauds** [comment]
Are we seriously arguing realism again

**Comment by Killette2** [comment]
Gloves go over hardsuits

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce. Passing underneath an active plasmafire while in disposals did not contaminate any of my clothes.
