### ISSUE TITLE
Bites can be heard through walls (and shouldn't be)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#10089]
Vampire drags a monkey into maint to feed on it, and if someone's standing in the next room they can hear it
WHY

**Comment by Shadowmech88** [comment]
This applies to literally all sounds.

People can hear changelings succing through walls as well.

**Comment by AutismSpider** [comment]
with all the sounds form gun fire to ling giving some one the suck

**Comment by gbasood** [comment]
Realistically you wouldn't hear a vamp biting into someone's neck through walls though

**Comment by carshalash** [comment]
I'm more impressed with the fact you could suck a monkey instead of a monkeyman.

**Comment by Killette2** [comment]
You all aren't able to hear through walls? I can hear my dad downstairs eating his scrambled eggs, every bite on the soft texture right now. It really sucked growing up as a kid when your parents banged too.

**Comment by 9600bauds** [comment]
I keep forgetting you people up there have houses made of wood and foam

**Comment by Killette2** [comment]
Actually my house is about 3 fridge boxes, but a storm really damaged one recently.

**Comment by Zth--** [comment]
Yeah but don't forget that nanotrasen is a cheap motherfucker

**Comment by gbasood** [comment]
@carshalash Possible that you can't, but you can still hear the bite noise regardless of whether you suck or not.

**Comment by Killette2** [comment]
> bite random people in maint, sound goes through walls
> security hears, barges in, and you bite with sec in sight
> get lasered to death
> ahelp and get your ban valids
