### ISSUE TITLE
Spacesuits make no sense.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10098]
You don't breath out of your spacesuit, but from internals on your face. The spacesuit itself has no breathable air (but it is still airtight and filled with _something_).

Why do you need an internals mask? Shouldn't the spacesuit have internal atmosphere?

**Comment by ComicIronic** [comment]
L M A O
And yes, internals need a massive rework.
Clothing and equipment generally need a rework.
Inventory datums where

**Comment by 9600bauds** [comment]
Where you code them

**Comment by Kurfursten** [comment]
Space suits are not not airtight, just pressure tight. Air is allowed to move freely in and out of the suit while maintaining a stable temperature and pressure. That's why you can get plasma'd inside a non-atmos suit.

The lengths we go to in order to explain game mechanics

**Comment by ComicIronic** [comment]
Then where does it go in spess?????

**Comment by Kurfursten** [comment]
To the gas miner

**Comment by ComicIronic** [comment]
Makes sense

**Comment by PJB3005** [comment]
It's still a feature request for more logical space suits.
