### ISSUE TITLE
Feature request: Abductor event.

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#10093]
You guys knew it was fucking coming, so essentially once the antag datum shit happens I think this would be one of the best things to do. I've also heard suggestions of making vox raiders into an event like this instead of a game mode so, I'm just throwing it out there while i'm at it.

For people who have no clue what the fuck abductor is, https://tgstation13.org/wiki/Abductor go nuts. Hope this gets seriously looked at, Hensha out.

**Comment by kol1th** [comment]
when you code it

EDIT: :eggplant: :ok_hand:

**Comment by Ephx1** [comment]
> A mode that lets antags make other super powered antags
> 
> On /vg/

aaaaaaahahahaha

**Comment by Zth--** [comment]
I. Love. This.

**Comment by 9600bauds** [comment]
_upboated_

**Comment by Hoshi-chan** [comment]
Sounds cool, but it also sounds like a shitload of work to add.

If you're not coding it yourself, good luck convincing someone else to do it.

**Comment by NigglyWiggly** [comment]
I still have tons of sprites for Grey clothing and technology, if anyone decides to actually work on this.

**Comment by Shadowmech88** [comment]
Why not just post the sprites here anyway?

**Comment by NigglyWiggly** [comment]
Because they're not that great and I sort of want an excuse to re-do them all

**Comment by icantthinkofanameritenow** [comment]
I still insist Swarmers would be better, since they allow people to get back in the game faster without being enough to force a shuttle call on their own. Not without a lot of incompetence, at least.
