### ISSUE TITLE
Matter eater doesn't work on blob

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10097]
:disappointed:

**Comment by Shadowmech88** [comment]
Matter eater doesn't work on _anything_ that's not an item or a mob, does it?
Same reason you can't eat through a metal wall.

**Comment by Blithering** [comment]
![matter-eater-lad](https://cloud.githubusercontent.com/assets/15067109/15342818/2c813d80-1c90-11e6-98de-28825b3313a9.jpg)
This requires immediate fixing.

**Comment by ihadtoregisterforthis** [comment]
How do you even bite a wall head-on?

**Comment by Shadowmech88** [comment]
> he can't open his jaw 180 degrees

**Comment by Probe1** [comment]
Stand with me America.  Together we will punch the blob.  We will kick the blob.  We will bite the blob.  And yes, WE WILL EAT THE BLOB!

:us: :gun: :fireworks: :eggplant:
