### ISSUE TITLE
Disposal units are layered beneath cult gateways

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#10091]
Meaning you can shove yourself into a disposal unit and hide there until round end
Especially if you do it before nar-sie rises

**Comment by Shadowmech88** [comment]
Disposal chutes are truly the most robust hiding places.

**Comment by ghost** [comment]
what the frick is a cult gateway and is this fixed by planes

**Comment by Shadowmech88** [comment]
I'm pretty sure he's referring to those structures that look like a hole in the floor, spawned by Nar-Sie rising.

**Comment by gbasood** [comment]
yep
