### ISSUE TITLE
Decimal drowsiness causes you to be drowsy... forever.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10102]
Because oldcoders are just using a `--` to decrease it AND they check `if(drowsyness)`, so if it goes into negatives IT KEEPS GOING DOWN.

And the fun thing is a xenoarch artifact can cause this.

**Comment by PJB3005** [comment]
![](http://i.imgur.com/ul4RGzo.png)

**Comment by Probe1** [comment]
[cant wake up]
