### ISSUE TITLE
 Plasmaman cult armour sprites

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#10107]
Because getting culted and having them laugh behind your back when you can't say Nar-Sie without hissing is bad enough. Now you can rock around in this armour\* when everyone else is stuck with robes!
![owtheedge](https://cloud.githubusercontent.com/assets/15067109/15345029/7efd487a-1ca3-11e6-9bd6-478db04b5c6a.png)
download link for icons: http://s000.tinyupload.com/index.php?file_id=80225514181703090988
*icons subject to change, no constructs were harmed in the making of this gear

**Comment by TheFriggenSawbones** [comment]
holy shit this is cool

**Comment by kol1th** [comment]
:+1:

**Comment by Brolaire** [comment]
Jesus Christ that's badass.

**Comment by jknpj** [comment]
We should make their runes plasma-colored or something, because they also have no blood. Someone please summon Deity.

**Comment by Shadowmech88** [comment]
Didn't Deity already make their runes plasma-colored with his "each race now draws runes in the color of its own blood" PR? I saw that he made adamantine golems draw cyan runes even though they have no blood.

**Comment by jknpj** [comment]
I am pretty sure i was drawing red-blooded(Human Runes?) runes last time i got converted as plasmamen.

**Comment by Shadowmech88** [comment]
How long ago was that? #9555 was merged just under two weeks ago.

**Comment by jknpj** [comment]
It was last week, monday, in isaac's savage shuttle cult round.

**Comment by Brolaire** [comment]
Are the flames animated or static?

**Comment by Blithering** [comment]
@Brolaire They're animated.

**Comment by ihadtoregisterforthis** [comment]
Flames appear only when the helmet "lights" are on from what the sprites suggest.
