### ISSUE TITLE
"You are too small to pull anything." message as mouse if you are moved by a person.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10100]
(WEB REPORT BY: bobda REMOTE: 172.93.109.202:7777)

> Revision 3ddc5b88ad0e786c072d5c142186b5d789279246 
> 
> General description of the issue
> If you are a mouse and get moved around or pulled by a person it displays "You are too small to pull anything." for every tile you move.
> 
> What you expected to happen
> No such message to display.
> 
> What actually happened
> "You are too small to pull anything." is displayed.
> 
> Steps to reproduce if possible
> 1. Be a mouse.
> 2. Have a person drag you around.
> 3. ???
> 4. You have your bug.

**Comment by PJB3005** [comment]
Dupe
