### ISSUE TITLE
Spawning new blob squares is quite confusing

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10116]
![0000](https://cloud.githubusercontent.com/assets/7571238/15374546/3d100942-1d21-11e6-827b-aee0d6d73ad7.png)

If I wanted to spread north here with normal blobs, I'd have to ctrl click.
Not a very evident fact. Make the blob able to move the consciousness within 1 tile of an blob square again.

**Comment by clusterfack** [comment]
Yeah we should lynch whoever changed that. It's also 120% retarded it starts moving you sideways if you move towards a wall.

**Comment by ComicIronic** [comment]
Who would remove such a thing

**Comment by Killette2** [comment]
Honestly, I really hate this and feel it makes blob less robust, since it cannot rush (which may be a balance feature) but the movement is way too slow, even compared to someone using magboots. Ctrl click to expand fucking sucks.

**Comment by Imagebard** [comment]
Fixed

**Comment by TheFriggenSawbones** [comment]
@Imagebard WHAT

**Comment by Imagebard** [comment]
You can move one block away form default blob squares. That's "WHAT".
There have been other bug fixes and feature loss fixes so far too but I can't be assed to find them right now.

**Comment by TheFriggenSawbones** [comment]
@Imagebard weren't you fuckin perma'd
