### ISSUE TITLE
Repair module animation is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10112]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
Self explanatory

**Comment by 9600bauds** [comment]
Uhhhh
which repair module

**Comment by Shadowmech88** [comment]
Probably the repair droid module for mechs. When it's turned on, the droid is supposed to sway back and forth across the mech.

**Comment by ComicIronic** [comment]
Does it repair?

**Comment by clusterfack** [comment]
Works fine
