### ISSUE TITLE
Blob cores close to each other override other blob "styles"

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10114]
This is a pretty unimportant bug that only happens when admins are bussing around, but still.

If a new blob core is too close to another one, their new "style" will override the older one.

**Comment by ComicIronic** [comment]
I don't know what to tag this: what do you expect to happen?

**Comment by Imagebard** [comment]
I expected the different blobs to stay at their own styles, so, huhh, Bug / Fix?

**Comment by PJB3005** [comment]
@DeityLink

**Comment by ComicIronic** [comment]
Don't different blobs share blob tiles, though?

**Comment by Intigracy** [comment]
Except for the one that gains them increased blob points iirc.

**Comment by DeityLink** [comment]
Working as intended.

**Comment by Imagebard** [comment]
@DeityLink 
Can you explain this a bit further before I close this

**Comment by DeityLink** [comment]
When an overmind chooses his style, all blobs in a 5-tiles radius around his core turn into that style. It's a design choice.

**Comment by Imagebard** [comment]
>When an overmind chooses his style, all blobs in a 5-tiles radius around his core turn into that style. 
It's a design choice.

Okay but why is this design choice here in first place
You know what, whatever

**Comment by DeityLink** [comment]
The blob starts expanding as soon as the core spawns. This way the overmind has some time to make his choice.
