### ISSUE TITLE
We should make health an /obj var and add general procs for objects receiving damage

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#10113]
Currently to make something destroyable you have to add a lot of snowflaking. If all objects had a health variable as well as procs like /receive_damage(amount) etc., it would be much better

**Comment by ComicIronic** [comment]
I'm working on health datums.

As a rule, adding logic directly to a class that won't be used by all its descendants is poor patterning. A health component is better.

**Comment by west3436** [comment]
Implemented via #32007, #32184, and #32255.
