### ISSUE TITLE
Permanent Upside down/switched hotkeys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10111]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> fbd3015fda4e65f37b5a63b77d1e5f075680290f
> 
> General description of the issue
> so there's tis effect when you stand by the supermatter, it flips the screen, you see upside down, and your hotkeys are moved around. while under that I effect, I happen to die, and it persists as a ghost, even after I'm cloned, for the rest of the round. I re-entered as a wizard after death and it still persisted.
> 
> What you expected to happen
> I expect it to go away at least once I die
> 
> What actually happened
> It persisted until the end of the round. I use hotkeys quite a bit, so I ended up dropping shit when trying to activate it using the normal hotkey(pgdwn)
> 
> Steps to reproduce if possible
> stand near supermatter, start seeing upside down or sideways, die, get cloned or re-enter game as whizard

**Comment by clusterfack** [comment]
Wow #5001 when

**Comment by ComicIronic** [comment]
WHEN YOU... oh
