### ISSUE TITLE
Can't walk over mines

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10110]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> fbd3015fda4e65f37b5a63b77d1e5f075680290f 
> 
> General description of the issue
> You can't walk over the N2/Plasma mines that are on the, uhh, sand cult vault away mission.
> 
> What you expected to happen
> To be able to walk over a mine, maybe have my legs blow up.
> 
> What actually happened
> I could not walk over the mine, it blocked off an area.
> 
> Steps to reproduce if possible
> try to walk over a mine.

**Comment by Kurfursten** [comment]
The future of area-denial weaponry

**Comment by NigglyWiggly** [comment]
Well why would you walk over a mine anyway, they'll explode you dummy!
