### ISSUE TITLE
AI Cores are VERY, VERY BROKEN

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10126]
Compiling the following issue tickets : 
- #9742 : AI Cores should be deconstructible
- #8543 : Inactive AI Core can't be interacted with
- #7899 : can't unwrench an inactive AI
- #5107 : Allow the AI core to be pushed

Not only have none of these issues been fixed, but it only seems to get worse and worse every day, to the point where an admin has to step in when someone needs to physically replace an AI

Right now, the following problems plague AI Cores : 
- They can't be deconstructed at all. The wiki has steps for it, but I don't know if they're broken or don't exist. If they don't exist, then they should be added as listed on the wiki
- Unbolting and bolting AIs is VERY finicky, notably you can't anchor or deanchor AIs while they are being built
- All tools end up whacking AIs (even dead ones) or doing nothing on inactive AIs, maybe with the sole, very specific exception of wrenches
- AI Cores can't be pushed when deanchored, which is EXTREMELY painful. Seeing how literally anyone can drag them, there's really zero gameplay reason for it, and it prevents players from setting the AI into their respective cubicles in the AI Core without deconning walls

Please close the older issues in favor of that one, and for the love of everything please fix AI Cores

**Comment by ComicIronic** [comment]
I'm pretty sure you can click to move an AI into the wall slot.

**Comment by ghost** [comment]
Even then, you should be able to physically push unanchored AIs, and click moving has its own issues, which is why people still get stuck in tiny alcoves behind a fuel tank or what have you

**Comment by CptWad** [comment]
theres also an AI core called "ALICE" in centcom thats broken to all shit, its more of a simple mob then an AI, since taking direct control makes you unable to anything but speak

**Comment by ScrambledSteak** [comment]
ALICE always confused me. I had no idea why it existed every time I saw it. What purpose does an AI in CentComm serve?

**Comment by ghost** [comment]
It's not an AI IIRC, but a special subtype of AI Core that explodes when you slap it with an Intellicard, something I discovered by accident

No idea, maybe an inside joke

**Comment by Imagebard** [comment]
its also automatically makes announcements when the ERT shuttle is launched/preparing to launch.

**Comment by ghost** [comment]
It's a bit of a throwback, there's ALICE for ERT/deathsquad shuttle announcements, and GLADOS for Syndi deathsquad announcements.

**Comment by Imagebard** [comment]
Oh yes, the Syndicate Strike Team which doesn't even work
Y'know, GLADOS might just be copypasted code form ALICE. Did anyone ever check?

**Comment by Shadowmech88** [comment]
3/4 of the issues mentioned have been fixed, and the last one is its own feature request anyway.
Also, unanchored AIs can now be pushed.
