### ISSUE TITLE
remove the dumb transit pipes thing from xenoarch

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10127]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> its never used and you cant drag mobs while going trough it
> 
> What you expected to happen
> not exist
> 
> What actually happened
> it exist
> 
> Steps to reproduce if possible
> go in xenoarch and find a useless pipe thing

**Comment by Imagebard** [comment]
The github reporter was a _good idea_
