### ISSUE TITLE
stun shells are bottles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10128]
(WEB REPORT BY: manfreed REMOTE: 172.93.109.202:7777)
When rightclicking used stun shells for shotguns apear as bottles. Haven't checked fresh shells

**Comment by 9600bauds** [comment]
What

**Comment by Intigracy** [comment]
I assume he means if you right click the spent stun shell the icon is a bottle.

**Comment by AutismSpider** [comment]
spent  shell has the wrong icon

**Comment by 9600bauds** [comment]
![dreamseeker_2016-12-18_19-37-26](https://cloud.githubusercontent.com/assets/6526157/21297161/70725d7c-c559-11e6-9b8f-ebc1c34f055a.png)

**Comment by Exxion** [comment]
It was almost certainly that weird BYOND client bug
