### ISSUE TITLE
add the awesome transit pipes to everything

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10129]
(WEB REPORT BY: nigglywiggly REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> its cool and you can zoom around everyewhere
> 
> What you expected to happen
> it exist
> 
> What actually happened
> not exist
> 
> Steps to reproduce if possible
> go in station and dont find awesome pipe thing

**Comment by NigglyWiggly** [comment]
#10127

**Comment by NigglyWiggly** [comment]
rude
