### ISSUE TITLE
Flashers work without power

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10130]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/8550416/15411107/a96d8b12-1deb-11e6-8ddb-43de3677246b.png)

Even with an APC shut OFF (set equipment et al to Off) a wrenched down flasher still flashes.  The icon is off but the flasher still works.
#### Difference between expected and actual behavior

It flashed some dude despite being off
It shouldn't have.
#### Steps to reproduce

Wrench a flasher down in the brig.  Turn off the equipment et al power.  I don't know about the main breaker.  Note that the flasher still flashes you when you walk up to it!
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Did they used to require power?
This might be intended behavior.

**Comment by Exxion** [comment]
Last I checked, they do use power, but maybe they don't first check if they actually have it

**Comment by ComicIronic** [comment]
No, it checks.

```
/obj/machinery/flasher/proc/flash()
    if (!(powered()))
        return
```

**Comment by ghost** [comment]
Can't reproduce.

**Comment by Probe1** [comment]
beats me
