### ISSUE TITLE
cuban pete maracas

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10133]
(WEB REPORT BY: edwarus REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> they dont explode when thrown
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Allspice** [comment]
Got to emag them.

**Comment by TheFriggenSawbones** [comment]
good job dunsel
