### ISSUE TITLE
RETURN RUNTIME TO THE CMO'S OFFICE

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10139]
OR RIOT

**Comment by ComicIronic** [comment]
No really why is there a worm in there now

**Comment by 9600bauds** [comment]
So borgs can play dumb and pretend it's an alien larva

**Comment by gbasood** [comment]
Runtime for CMO when QM gets a pet

**Comment by ComicIronic** [comment]
QM gets shit snek

**Comment by Kurfursten** [comment]
The QM really wants a pet emitter. "It's totally a pet, security. Don't look into the matter further."

**Comment by Hoshi-chan** [comment]
Yes please.

Also, put Corpus in security where he's supposed to be, and get rid of that stupid fucking dog.

**Comment by ComicIronic** [comment]
If they added the Rottie to Sec, we should keep it.

**Comment by Hoshi-chan** [comment]
Corpus is the ssssecurity ssssnek. He belongs in the brig.

**Comment by ihadtoregisterforthis** [comment]
Corpus is the caduceus/asclepius serpent

**Comment by Hoshi-chan** [comment]
His name is corpus, as in a writ of habeas corpus, and he's a milksnake, so he's sec-colored.

The fucking dog doesn't even animate or have any personality. GIVE CORPUS TO SEC REEEEEEEEEEEEEEEEEEEEE.

**Comment by NigglyWiggly** [comment]
> His name is corpus, as in a writ of habeas corpus,

https://en.wikipedia.org/wiki/Hippocratic_Corpus

**Comment by NigglyWiggly** [comment]
besides a sec snek would be a coral snake
because they're venomous as heck but look like the friendlier ones

**Comment by Hoshi-chan** [comment]
Niggly and I are currently in negotiations for a sec pet that isn't that terrible dog. That being said, RETURN RUNTIME TO THE CMO'S OFFICE.

My reasoning is also that Corpus was in the meatclub brig before he was ever on Box, then one day he just usurped Runtime on Box, and that dumbass dog appeared in the HoS's office. I just think there should be consistency between maps, if you're gonna shove all these new pets down our throats.

Medbay doesn't need two pets, Runtime has always been the CMO's pet, and the brig shouldn't have different pets between maps. That's all.

**Comment by NigglyWiggly** [comment]
<sub> I don't think most of the pets should even be on the map to begin with

**Comment by Blithering** [comment]
Anyone know where the tiny robot icons are kept? I feel the need to sprite a retired beepsky that shoots donuts.
Edit: I call him Ol' Beepy
![old beepy](https://cloud.githubusercontent.com/assets/15067109/15490556/fbc8b95e-2160-11e6-9c55-e637aabd6903.png)

**Comment by Shadowmech88** [comment]
Just VV a Beepsky on a local server and check its `icon` var, that'll have the path to the .dmi that its `icon_state` is in.
