### ISSUE TITLE
Borer Enchanced metabolism just doesn't appear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10136]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
I had updates necessary for it to be a thing and 300 chems, just didn't appear at all.

**Comment by Shadowmech88** [comment]
Borer prerequisites are broken somehow, I discovered/fixed it in my borer PR.
When I can get to my computer, I'll just make a separate PR to fix it.

Fun fact, borers are also supposed to be able to give their host X-ray vision after giving them farsight.

**Comment by AutismSpider** [comment]
Far-sight bugs out half the time it turns on for the host or it does not same thing with iron liver mut
