### ISSUE TITLE
Telephoto Vision of Borer is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10135]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
I activated telephoto vision for my host but he had no change in his vision.

**Comment by Kurfursten** [comment]
@ComicIronic Needs further testing, worked for my host

**Comment by Probe1** [comment]
Maybe its doing a genetics roll and might not proc every time?

**Comment by Shadowmech88** [comment]
Was this ever reproduced?

**Comment by clusterfack** [comment]
Nope
