### ISSUE TITLE
We need Hippie's nooses

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#10134]
i want to HANG MYSELF

**Comment by cowboybuttsdrivemenuts** [comment]
thank god

**Comment by kol1th** [comment]
:100: :ok_hand:

**Comment by SysadminJeroen** [comment]
hang urself lelelel xDDDDDDDDD

**Comment by ghost** [comment]
Connected to what? We don't have a roof

**Comment by 9600bauds** [comment]
No but we have a ceiling

**Comment by ghost** [comment]
> cables that you can break out of in thirty seconds
> somehow strong enough to support a spaceman dangling on it

no thanks

**Comment by SysadminJeroen** [comment]
Maybe yu can make a noose out of cable coil. To use it you need to have it
on the same tile as a bar stool. To finally execute someone, either kick or
drag the stool from under their feet.
Op 20 mei 2016 21:26 schreef "DrCelt" notifications@github.com:

**Comment by 9600bauds** [comment]
Celt you big silly, the cablecuffs don't even break 
You're slipping out of them

**Comment by unid15** [comment]
skellingtons and other races with no blood and no breathing shouldn't die after hanging themselves

just let them hang there forever until somebody cuts the rope

**Comment by TheFriggenSawbones** [comment]
@DrCelt You use 15 pieces of cable for cuffs, nooses use 30. They're extra strong you see.

**Comment by Killette2** [comment]
What bauds said, you don't break out of cable cuffs, you struggle to free yourself from them and they're reusable.

Cables are pretty strong, I consider you hanging yourself with them @DrCelt

**Comment by SkowronX** [comment]
Assuming the cables used in the station are 2 AWG. It could certainly work. Then again, if fat people tried this, they would just break the cable.

**Comment by PJB3005** [comment]
@SkowronX actually examine says they're superconducting and NT would probably cheap out as much as possible.

**Comment by Blithering** [comment]
Don't you get flavour text saying you make a noose and hang yourself when you suicide holding cable coil already?

**Comment by Orangerush** [comment]
Tie the noose to an electric wheelchair or a cart then around a person and drag them around until their head rips off.

**Comment by PJB3005** [comment]
Fuck you mobile.
