### ISSUE TITLE
Summon guns should be disabled in Ragin Mages

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10140]
For the sole reason that its a training gamemode for newcomer Wizards. Summon guns makes it a bigger mess because it quickly arms the crew with weapons which could instantly destroy the wizard unless he has a skilled surgeon to help him after a gyrojet pistol breaks both his legs.

Therefore, please disable Summon Guns during Ragin Mages.

**Comment by clusterfack** [comment]
It already is though?

**Comment by ComicIronic** [comment]
It is in the code. You can't even href it in.

**Comment by clusterfack** [comment]
Like I don't know what made you single out this as something we have to do when I'm fairy sure this is the ONLY spell that is already doing this.

**Comment by Imagebard** [comment]
Wait what

**Comment by Imagebard** [comment]
Wait yes I was sure, I'm pretty sure I've heard of a wizard fucking in Summon Guns during Ragin Wizards yesterday.

**Comment by clusterfack** [comment]
What made you think of this specifically? Have you in the past heard of other spells being disabled during raging mages? Spells like SUMMON GUNS?

**Comment by Imagebard** [comment]
Erm, what? Are you complaining about disabling random spells in raging mages, is that it?

**Comment by ComicIronic** [comment]
Logs or no issue

**Comment by Imagebard** [comment]
You win

**Comment by clusterfack** [comment]
No we're saying its already been blocked out, its the only spell to have ever been blocked out, and the only reason you even thought of blocking it out was because you HEARD OF IT ALREADY BEING BLOCKED OUT.

**Comment by Imagebard** [comment]
>and the only reason you even thought of blocking it out was because you HEARD OF IT ALREADY BEING BLOCKED OUT.

I'm not even mad, I'm impressed. How did you come to this conclusion.
