### ISSUE TITLE
Papercode formatting not working, stamps messed up.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10142]
(WEB REPORT BY: kekkles REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 26d2bf239ddcd632b691f56d586dab91aa1e9416
> 
> General description of the issue
> Papercode formatting just prints as text instead of actuall formatting. Stamping paper wipes the text on it.
> 
> What you expected to happen
> Formatting to work. Stamps not to wipe text.
> 
> What actually happened
> The opposite.
> 
> Steps to reproduce if possible
> Write down any kind of papercode. Try to format text. Use a stamp on a written-on paper.

**Comment by ghost** [comment]
Can confirm, happenned to me too:
![bugs](https://cloud.githubusercontent.com/assets/19200220/15452548/2b091836-1ff3-11e6-96c3-5b2984d1c613.PNG)

Also, I was librarian; already formated text (books and the like) didn't seem to be affected. 
Should have taken pics of that too.

[EDIT]: Before anyone goes "still using XP", if that were related I would have encountered this already

**Comment by Shadowmech88** [comment]
I can't think of any recent PRs that have touched paper formatting, this is weird.

Maybe caused by the move to 510?

**Comment by ihadtoregisterforthis** [comment]
> still using XP

**Comment by PJB3005** [comment]
> still using XP

**Comment by ghost** [comment]
XP is comfy

**Comment by clusterfack** [comment]
I fixed this
