### ISSUE TITLE
Vox traders can be blobs

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#10143]
This will usually result 99% of the time in the vox popping off station and causing an instant round end.

**Comment by Killette2** [comment]
What if vox traders were blobs 95% of the time during blob mode, so they had to get to the station in time and this would entice the crew to hate traders even more?

**Comment by ComicIronic** [comment]
REMOVE
TRADER

**Comment by ihadtoregisterforthis** [comment]
Improve trader

**Comment by Ephx1** [comment]
transform trader

**Comment by Kurfursten** [comment]
Pretend to be trader
Steal singularity engine
