### ISSUE TITLE
Security Records Console can't make new records no mo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10146]
(WEB REPORT BY: probe1 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 26d2bf239ddcd632b691f56d586dab91aa1e9416 
> 
> General description of the issue
> Security records has a button that says New Record.  Clicking it does nothing.
> 
> What you expected to happen

A new record to be added.  This used to work.

> What actually happened
> 
> Steps to reproduce if possible

**Comment by Kurfursten** [comment]
@Exxion Cannot reproduce, button works fine

**Comment by Exxion** [comment]
Additionally, old
