### ISSUE TITLE
Remove xenoarch suit speed slowdown.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10147]
Actually fuck that I'm gonna do it myself.

**Comment by Imagebard** [comment]
Before you even do something, what speed slowdown?

**Comment by PJB3005** [comment]
That one, derp.

**Comment by Imagebard** [comment]
Well, it IS supposed to be a hardsuit.

**Comment by Kurfursten** [comment]
No more need for hyperzine, another reason to remove the chem dispenser from the outpost which is mostly used for chloral anyway.

**Comment by Imagebard** [comment]
Well
Good point

**Comment by PJB3005** [comment]
@Kurfursten chem dispenser is still needed for determining what an artifact does.

**Comment by Kurfursten** [comment]
@PJB3005 So give them 2 large beakers full of analysis fluid, like the Janitor starts with a limited amount of Space Cleaner. They can walk over to R&D when they run out. There's a chem dispenser every round (and if there isn't one, it'll force them to do the research which is good for gameplay)

**Comment by ComicIronic** [comment]
Did you guys give R&D a starting chem dispenser?

Also I don't agree with making a fast space suit, they're meant to be slow.

**Comment by Kurfursten** [comment]
@ComicIronic Everyone follows the wiki research path which involves building a dispenser

**Comment by Shadowmech88** [comment]
> Also I don't agree with making a fast space suit, they're meant to be slow.

I'm pretty sure even hardsuits no longer have slowdown.

**Comment by AutismSpider** [comment]
@Imagebard you move faster in miner suit then xenoarch suit not only that xenoarch suit has zero armor to it miner suit does

**Comment by kol1th** [comment]
xenobotany needs the dispenser for mutagen yeah?

**Comment by Kurfursten** [comment]
Xenobotany was a mistake.

t. The guy that added the job title.

**Comment by 9600bauds** [comment]
Xenobotany can be done 100% with a somatoray

**Comment by 9600bauds** [comment]
And I guess diethylamine but that's optional and people asking chemistry for things is good
Let's not kid ourselves though, R&D almost certainly already built a chemdispenser

**Comment by Kurfursten** [comment]
@9600bauds Speaking of fertilizers, I am 100% sure the fertilizer descriptions on http://ss13.moe/wiki/index.php/Botanist are out of date

Could you update them?

**Comment by 9600bauds** [comment]
k dun

**Comment by Killette2** [comment]
DID I HEAR YOU NERDS TALKING SHIT ABOUT MY XENOBOTANY?

**Comment by DeityLink** [comment]
xenoarch got actual rigsuits now.
