### ISSUE TITLE
mech painter and different mech sprites

### ISSUE THREAD

**Issue by pvak** [d3athrow/vgstation13#10152]
add them for fun

**Comment by 9600bauds** [comment]
When you sprite it

**Comment by Shadowmech88** [comment]
Changing the color of a mech's icon on-the-fly using a color wheel seems a lot more doable than making a ton of different sprites for all the mechs.

**Comment by Killette2** [comment]
When you mech it

**Comment by ComicIronic** [comment]
If someone splits the mech sprites into their coloured parts and background parts, and then makes the coloured part white, this would be much easier.

**Comment by ihadtoregisterforthis** [comment]
What about decals?
