### ISSUE TITLE
Hydroponic tray not showing the green light indicator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10159]
(WEB REPORT BY: jellyveggie REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4ad7c6f6398718ccdcfae5d79380eec3f2bdf63c 
> 
> General description of the issue
> Hydroponic trays don't show the green light 
> 
> What you expected to happen
> As soon as the plant can be harvested, the tray they're planted on shows a green light
> 
> What actually happened
> No green light appeared, even as the plant was avalaible for harvest
> 
> Steps to reproduce if possible
> Plant tomatoes, or any other "visibly ripe" vegetable or fruit plant. Wait until harvestable (the tomato plant will show it's tomatoes on it's sprite), and compare against the tray's lights

**Comment by Kurfursten** [comment]
Not only this, but also no weed lights, no pest lights, no water lights, no fertilizer lights

I also noticed I wasn't getting hacking overlays on vending. Maybe overlay issue general to machinery

**Comment by PJB3005** [comment]
Update BYOND.

**Comment by DamianX** [comment]
not a thing anymore
