### ISSUE TITLE
Mech Parts Not Showing Up When Attached To Their Chassis

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10156]
(WEB REPORT BY: kinggrimlock REMOTE: 172.93.109.202:7777)

> Revision fb3cc4cb6bb1e7b7e73b8243c97c58312aa84647 
> General description of the issue
> Mech parts don't show up when you attach them to the appropriate chassis.
> 
> What you expected to happen
> I expected that when I attached a mech part to its appropriate chassis (say, a Ripley arm to a Ripley chassis) that part would show up on the chassis' sprite.
> 
> What actually happened
> The mech part that I attached did not, in fact, show up on the chassis' sprite.
> 
> Steps to reproduce if possible
> 1. Produce a mech chassis of your choice
> 2. Attach any other part from that same mech (legs, arms, torso, head) and attach it to the mech chassis.

**Comment by ComicIronic** [comment]
Oh fugg

**Comment by PJB3005** [comment]
What the fuck is going on with BYOND.

Overlays are glitching out left and right.

**Comment by ComicIronic** [comment]
Byond issue, then?

**Comment by PJB3005** [comment]
I assume so? All of a sudden it started happening to me yesterday and I've seen multiple reports from multiple people about overlay related things breaking.

**Comment by Shadowmech88** [comment]
Were the parts actually getting attached, though? Could you finish building the mech?

**Comment by ghost** [comment]
Had a repeat of this earlier, upgrading to the latest version seemed to fix it for some reason.

The parts were going on, when I came back I was able to finish the mech off.

**Comment by ComicIronic** [comment]
Byond has been having issues with overlays, god knows why.

**Comment by PJB3005** [comment]
Latest changelog mentions an overlays related bug fix so I can only assume this causes version difference issues.

**Comment by clusterfack** [comment]
There's been problems with images/overlays recently that Lummox has been fixing up, but its not a problem resulting from our code.
