### ISSUE TITLE
Everything about throwing items towards windows is broken

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10162]
Issue 1: #8136
Side windows get hit by thrown items when they shouldn't
![2016-05-22_18-42-37](https://cloud.githubusercontent.com/assets/6526157/15456648/1214f782-204d-11e6-84c7-74bb9c8b074c.gif)

Issue 2:
When you throw something at a window formation like this, nothing happens.
![2016-05-22_18-32-59](https://cloud.githubusercontent.com/assets/6526157/15456651/30602054-204d-11e6-95fd-75a18c6e50eb.gif)
Why?
Only recently did I find out that it's because the thrown item is actually hitting the grille before it hits the window. And grilles don't do anything when hit by a thrown item, so nothing happens.
EDIT: I actually just found out it only works like this when thrown horizontally, if you throw vertically up, it will let you break the border windows via throwing. But you still can't break the fulltile window like this, it becomes invulnerable due to grille

Issue 3: So what if we remove the grilles?
![2016-05-22_18-45-34](https://cloud.githubusercontent.com/assets/6526157/15456657/6c428580-204d-11e6-8233-50638f34b3b2.gif)
Border windows get hit by thrown items before the fulltile window does. Hmm, that seems like it makes a little sense. But wait a second...
![2016-05-22_18-47-57](https://cloud.githubusercontent.com/assets/6526157/15456671/b92d4d6c-204d-11e6-95b3-25fae06e62c2.gif)
This happens REGARDLESS OF THE ORIENTATION OF THE BORDER WINDOW
![2016-05-22_18-48-33](https://cloud.githubusercontent.com/assets/6526157/15456678/cc1d4418-204d-11e6-88b7-1a3aff21ae37.gif)
AND IT SEEMS THE WINDOWS BREAK IN THE SAME ORDER EVERY TIME, NO MATTER WHAT DIRECTION YOU THROW SHIT FROM
Hmm, I wonder...
![2016-05-22_18-51-42](https://cloud.githubusercontent.com/assets/6526157/15456695/4021ddd8-204e-11e6-8cf9-ccddda7944d7.gif)

**Comment by ComicIronic** [comment]
Holy kek.

I don't want to say for certain that this is to do with Cluster's changes, but border items need a serious once over, because there's a strong chance this is happening with everything else. Did you try with firedoors and windoors?

**Comment by 9600bauds** [comment]
Windoors work correctly as far as I can see

**Comment by Probe1** [comment]
Nay.  When there are two windoors on a tile you open the one thats further away from you first.

**Comment by 9600bauds** [comment]
excellent
They do play nice with THROWN items though

**Comment by clusterfack** [comment]
A LOT of that is related to this http://www.byond.com/forum/?post=2079322

That lummox is intentionally dragging his feet on for reasons I cant explain

**Comment by 9600bauds** [comment]
Can we fix it?

**Comment by ComicIronic** [comment]
We could move back to custom border checking systems while Lummox doesn't do anything for the next 3 years.

**Comment by 9600bauds** [comment]
So wait, do windoors work differently or

**Comment by clusterfack** [comment]
I'm not sure why a side window would block movement though, that sounds to me like shitcode in the way throw movement works

**Comment by 9600bauds** [comment]
Can we just do the same thing windoors do?

**Comment by 9600bauds** [comment]
I hate this

**Comment by Exxion** [comment]
It would appear that all of this except #8136 is fixed
