### ISSUE TITLE
Dance Dance Revolution fails on GET DOWN stages

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#10167]
#### Description of issue

The Dance Dance Revolution vault works fine up until it tells you to GET DOWN, at which point you fail even if you rest. I assume it's because it still checks for your direction when you GET DOWN, but you don't keep your direction when resting.
#### Difference between expected and actual behavior

The minigame fails and resets instead of continues.
#### Steps to reproduce

Play Dance Dance Revolution while having a greater reaction time than the average sloth.
#### Specific information for locating

Message upon failure:
`A red screen briefly flashes on Dance Dance Revolution.`
#### Length of time in which bug has been known to occur

As long as the vault's been in, probably?
#### Server revision

70a2d4db414918eb15b27b6d404a630d391bd56a
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
@unid15

**Comment by clusterfack** [comment]
#10281
