### ISSUE TITLE
Singularity Engine - Rework discussion

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#10164]
because I posted it in the wrong repo, again
#### Brief

In its current form, the singularity engine is "babby's first engine", and the average Engineer clocks in with little engine knowledge more than that of the singularity engine. As a result, singuloose poses a risk, the output doesn't match demand half the time and it ruins everyone's day when the station runs out of power halfway through the round. There is a disappointing number of Engineers who don't know how to atmos (at all), taking SME off the table, and most TEG setups, so the go-to engine a lot of the time is singularity, supported by AME. Here, I'd like to discuss potential changes to the singularity engine to make it a more useful engine, as well as adding potential to teach Engineers core skills.
#### Criticism of current form

A number of changes would be made to keep balance and not scare away newbie Engineers. The wiki contains a great guide on setting up the singularity, but the whole process involves pointless wiring of the particle accelerator (skill not really applied anywhere else), establishing the containment field (sort of useful, teaches you not to stand in front of the emitters or to touch the containment field), and filling plasma tanks from the canisters, teaching you not to leave the cap off the plasma canister lest you fuck Engineering forever, the last two being probably the only remotely useful transferable skills from the whole task. Upkeep of the singularity engine is minimal - there is no fuel to refill beyond the plasma tanks, which apparently run out after a while (never seen this) and perhaps checking up on the singularity every so often to make sure it's not ready to escape.

The reality of these cases are:
-Rounds tend not to go on long enough to ever warrant refilling of the plasma tanks, if the round does carry on this long then some other engine must be carrying the load because of singularity's poop output.
-If the singularity reaches dangerous size, there really isn't much that can be done except shutting down the PA quickly, and the chances of this being spotted and rectified in time are incredibly low.

Expanding on the first point:
The AME requires constant refilling of antimatter cans, and monitoring extends as far as making sure the fuel is topped up. Setup is limited to not being retarded with the multitool, and setting the input level right. This engine suffers a similar lack of transferable skills.
The TEG, depending on setup, requires occasional venting and refilling of plasma/oxygen, with setup requiring an understanding of piping enough to appreciate the mechanics at work. More advanced setups need a proportional understanding of atmos, and so forces the Engineer to learn how to atmos in order to get it running.
The SME, depending on setup, needs the most atmos knowledge of all commonly used engines, and a properly executed setup should require no refills beyond plasma tanks, if these can actually run out. The setup itself requires understanding of the cooling loop and handling of byproducts, again, transferable atmos skills.
Solars: shitty engine no one uses any more, teaches basic wiring and that's about it.
R-UST: not used commonly enough, goes beyond the scope of this issue.
#### Aim

The aim is to add more transferable skills to singularity setup and bring it more in line with the other engines, as opposed to being the shitty beginner engine that kills the station half the time. This could take the form of having to lay wire to the containment field, have plasma tanks run out quicker, or introducing some fail-safe to make it not eat the station every time it escapes confinement, to address the second point. The tradeoff would be removing useless parts of setup, like the PA wrench-wire-screwdriver deal. There would also be some room for expansion - like wings on Engineering to place additional radiation-collectors, some tile that 'repels' the singularity in order to direct it away from the station should it get loose, or some capacity to reinforce the containment field to a point that it could contain a stage 5 for some time, or some alert system if the singularity is reaching a dangerous size.

I probably could have laid this out a little better, but this is really intended as a discussion thread. Yea or Nay to singulo rework?

**Comment by ihadtoregisterforthis** [comment]
Nay
There's nothing wrong with it being babby's first engine. It's fast to arm, it's reliable, and it's safe within limitations like everything else. It also has room for improvement in the form of colder plasma and more collectors. It can easily power any station for hours.
Using it over other engines is a personal choice and not a concern.

**Comment by Inorien** [comment]
What about transferable skills during setup?

**Comment by FudgePucker** [comment]
Plasma cooling is a skill that is involved with setting up the singlo.
But if you are cooling plasma and know why and how to, then you probably can set up the SME

**Comment by ComicIronic** [comment]
You never need to cool plasma for the singulo, unless Dylan's balance changes completely changed the engine. I will say that the engines are meant to feel distinct and that engineers should learn by setting up engines themselves instead of just setting up the singulo and then learning from that.

**Comment by AutismSpider** [comment]
What is this engineer you talk about?

Last time i saw one it was some jack ass doing it for the free suit and gloves

**Comment by MercuryDoll** [comment]
The AME is literally a retard engine. Not only does it only need a multitool to magically turn small boxes into big engine parts, said parts also automagically transform into the needed machine part... _unless the spaghetti code fails again_.
Then you pop in a _jar_, turn it on and completely forget about it because when it runs dry it doesn't decrease in stability like it was intended to. Even if someone was overdriving it to the point it reaches 0% integrity, the explosion is laughable, the standart size Box Enginerring starts out with barely produces an explosion bigger than an assistant smacking a fueltank with a lit welder.

Any engine we have are, with the knowledge needed to set them up, "turn on and forget" until an antag fucks with them. None actually need constant or periodic maintenance. They all produce more than enough power to get a round going for at least an hour, which is longer than the average round when it's not deadpop. And even if the engines fail, the 3 SMES should have stored enough to power the station for the rest of the round.

If you want engines to require more maintenance, there's either adding arbitrary steps or nerfing them across the board, SMES included.
