### ISSUE TITLE
Boomerang sprite not appearing in hand when caught

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10161]
(WEB REPORT BY: orangerush REMOTE: 172.93.109.202:7777)
4ad7c6f6398718ccdcfae5d79380eec3f2bdf63c 
Boomerang sprite appears on ground next to character sometimes even when it's in your hand after you throw it and catch it

**Comment by clusterfack** [comment]
I think @unid15 ?

**Comment by PJB3005** [comment]
Wasn't it @DeityLink?

**Comment by DeityLink** [comment]
@PJB3005  how dare you think that I coded that buggy unreliable mess of a weapon?

**Comment by PJB3005** [comment]
Sorry!

**Comment by ghost** [comment]
Could not reproduce

**Comment by 9600bauds** [comment]
couldn't reproduce either

**Comment by ihadtoregisterforthis** [comment]
Were you trying to reproduce together?
