### ISSUE TITLE
Atmospheric analyzer's no longer read pressure tanks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10171]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision 70a2d4db414918eb15b27b6d404a630d391bd56a 
> 
> General description of the issue
> Atmospheric analyzer's no longer read pressure tanks. They spit out, "You use the atmospheric analyzer on" instead of something like 

You use the atmospheric analyzer on  the canister

 Results of the canister scan:
 Pressure: 2856.6 kPa
 Oxygen: 655 mol, 52%
 Plasma: 602.8 mol, 47%
 Temperature: 0°C

It worked back in the day.

> What you expected to happen
> Get a reading like above
> 
> What actually happened
> Stopped short
> 
> Steps to reproduce if possible
> Grab an analyzer from a toolbox and head to the incinerator. 
> Scan one of the pressure tanks.

**Comment by 9600bauds** [comment]
Seems to be a fault of bicon()

**Comment by clusterfack** [comment]
How so?

**Comment by clusterfack** [comment]
I also cannot reproduce this

**Comment by 9600bauds** [comment]
Seems like the message cuts off right when the bicon() should show up
Also did you do it on the big pressure tanks such as the incinerator's?

**Comment by clusterfack** [comment]
No I did it on pipes as well as multiple canisters such as described in the original report

**Comment by 9600bauds** [comment]
> Steps to reproduce if possible
> Grab an analyzer from a toolbox and head to the incinerator.
> Scan one of the pressure tanks.

**Comment by clusterfack** [comment]
Hey if you want to try it on a pressure tank go right ahead

**Comment by 9600bauds** [comment]
I did
It gives this message
![dreamseeker_2016-05-23_17-38-53](https://cloud.githubusercontent.com/assets/6526157/15483828/3f2b7ee2-210d-11e6-9f76-fb5e465ec696.png)

**Comment by ComicIronic** [comment]
Clusterfack confirmed for best tester.

**Comment by clusterfack** [comment]
They use identical code so ¯\_(ツ)_/¯

**Comment by 9600bauds** [comment]
Bicon being weird

**Comment by clusterfack** [comment]
Why do you think that would actually affect this? Even if it runtimed the rest should still proceed

**Comment by 9600bauds** [comment]
It cuts off at the bicon(), which I find weird
If it were a problem with something else it'd probably show nothing at all

**Comment by PJB3005** [comment]
Somebody use debug-chat to see if the HTML is being malformed or something.

**Comment by clusterfack** [comment]
someone set the icon to something different and see if it still occurs

**Comment by 9600bauds** [comment]
how the heck do I debug chat

**Comment by 9600bauds** [comment]
![mspaint_2016-05-23_20-46-45](https://cloud.githubusercontent.com/assets/6526157/15487912/7972adb8-2127-11e6-91c2-a1d3d50f5050.png)
Changing icon did not work

**Comment by PJB3005** [comment]
debug-chat verb

**Comment by 9600bauds** [comment]
I looked for that in every tab and nada, even try to type debug- and have BYOND autocomplete and nada, but I type it down and it works what the fuck

![dreamseeker_2016-05-23_20-52-51](https://cloud.githubusercontent.com/assets/6526157/15488023/5579cbca-2128-11e6-9604-e34dc530f0f4.png)
pressure tank

![dreamseeker_2016-05-23_20-53-39](https://cloud.githubusercontent.com/assets/6526157/15488038/71ebce5c-2128-11e6-89ce-81e9422af297.png)
O2 canister

**Comment by PJB3005** [comment]
What the fuck there's nothing wrong with that HTML as far as I can see.

Also it's a hidden verb.

**Comment by 9600bauds** [comment]
how far down does this rabbit hole gooo
