### ISSUE TITLE
Large boxes, despite being too big to fit in bags of holding, can only hold small items themselves

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10170]
seriously what's the point

**Comment by clusterfack** [comment]
"Large boxes" ?

**Comment by Imagebard** [comment]
The box you can make when you assembles together 4 cardboard.
Or was it 5?
Anyways I'm sure you can find it.

**Comment by Exxion** [comment]
They hold way more items than normal boxes
But the size limit on the item is no different
Which is very dumb
