### ISSUE TITLE
crayon grafitti not appearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10173]
(WEB REPORT BY: cadaverouscoyote REMOTE: 172.93.109.202:7777)

> 70a2d4db414918eb15b27b6d404a630d391bd56a
> 
> when a crayon is used to write a letter on a floor or wall, the letter isn't visible. alt+clicking reveals that the letter does exist, but it can't be seen otherwise.
> 
> SEX IN THE BUTT to be legible in bright red crayon on the floor of the security lobby
> 
> SEX IN THE BUTT was invisible on the floor of security lobby
> 1. take crayon 2. click on floor/wall 3. select any one of the options presented

:((

**Comment by ComicIronic** [comment]
More Byond overlay issues or is this an actual problem?

**Comment by AI-Is-Rogue** [comment]
I was unable to view crayon writing, open door panels and strange rocks until I updated to the latest Byond beta. Try that.

**Comment by clusterfack** [comment]
There's a very good chance this is a problem with one of the byond beta builds where images wouldn't display correctly. But we'll never be able to verify it because this is a web report.
