### ISSUE TITLE
Disposals mailing broken on Bus Station

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10184]
#### Description of issue

Mailing on Bus Station works by launching the parcels on mass drivers into a sorting junction on space. This would be great, and awesome, if not because of the belts and mass drivers outside in space, and on said junction, don't seem to respond or work at all (maybe they recieve no power?)
On that note, neither do the junction's doors work, although lighting does
#### Difference between expected and actual behavior

Belts and mass drivers out in space should be working
#### Specific information for locating

Search for the recycling room (or send yourself down disposals)
Search for the junction, as described by the in-map pod bay instructions
#### Server revision

d285a4411d86d707427ddbe1835ff4ae9ad5c086

**Comment by Kurfursten** [comment]
Yes, as you saw elsewhere, this is fixed in the latest revision, this issue is safe to close.
