### ISSUE TITLE
"Useless" book on Bus Station's hydroponics

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10182]
#### Description of issue

The book "The human harvest" is blank upon reading, making it an useless addition to Bus Station's hydroponics.

Should either remove it or give it some actual content to the book.
#### Server revision

d285a4411d86d707427ddbe1835ff4ae9ad5c086

**Comment by Kurfursten** [comment]
I looked into this, and apparently The Human Harvest had its entire text commented out. The book wasn't removed from the game, someone just decided to remove all the text without removing the manual.

Maybe we should have a discussion if we should just remove the book entirely from the code, or fill it in with the new Diona information. Previously it discussed pod-cloning which is not something we do anymore on /vg/.

**Comment by Imagebard** [comment]
Bauds why didn't you close this one
Bauds what are you doing

**Comment by Imagebard** [comment]
Information on most books were just and simply removed.

**Comment by ComicIronic** [comment]
I believe the text was commented out because the intention was to load it from the library code instead.
