### ISSUE TITLE
Goat Treats

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10180]
The amount of times I've had to slaughter a goat because he can dangerously wound a crewman before his 10%-chance-per-tick-to-calm-down fires is saddeningly high. It might promote good chef play if someone picks a favorite food for goats that will calm them down if fed. Save Pete. #goatlivesmatter

Cursory research on the web suggests that goats particularly like salty things, so maybe any food containing salt?

**Comment by AutismSpider** [comment]
So nuts then

**Comment by Kurfursten** [comment]
As far as I know, the sole nut in the game is the peanut, which is not accessible in-game because the plant seeds are not found anywhere

**Comment by Shadowmech88** [comment]
What if you just smack him with the salt shaker?

**Comment by 9600bauds** [comment]
pet gote 4 calm

**Comment by FudgePucker** [comment]
I want some more nuts in game.
Maybe a pecan tree.
Putting some nuts in the microwave with sugar and cinnamon can give you candied nuts.

**Comment by AutismSpider** [comment]
@Kurfursten Peanuts lack icons for it some times get them form rare seeds crate though

**Comment by Exxion** [comment]
Nettles

Or really anything except grass. They'll eat grass, but they like pretty much everything else more.
They find both honeysuckle and poison ivy pretty delicious but we don't have either of those

**Comment by Kurfursten** [comment]
@AutismSpider One of these days someone will need to fix that, and revive JNC's Gorillionares at the same time.

**Comment by FudgePucker** [comment]
Oh I do like honey suckle, it has a very far reaching fragrence that smells great, compared to those shitty trees with the white blooms I see around down here in Georgia
