### ISSUE TITLE
Update Ptech Vendor

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10186]
Only Meta has one of these, so imagine my annoyance the first time I ever want to use it and find out that it doesn't have the cartridge I want. It has only a bare selection. It should stock every PDA cartridge - after all, it comes with captain cartridges.

**Comment by Probe1** [comment]
sure

**Comment by Shadowmech88** [comment]
Do cartridges check access at all?
I've never used the Security PDA cartridge, but I believe it allows you to modify Sec records. Obviously non-Sec getting these would pose a security risk.

**Comment by Kurfursten** [comment]
Two things. First:
1. the ROBUST cartridge is already in the Ptech vendor so that's not even part of that issue
2. it's the HOP's fault anyway if that happens, it's a secure office and he has an egun. Frankly if greytiders are getting into the HOP office they could just as easily tide all access or acquire sechud glasses from the brig or R&D

That being said, I wouldn't mind if someone added an access requirement to the Ptech vendor, since many other vendors have an access requirement and it even has a deny animation.

**Comment by Shadowmech88** [comment]
I actually wasn't aware that the machine was inside the HoP's office.
Truthfully, I didn't even know that it existed at all until I saw this issue.

**Comment by Probe1** [comment]
The machine can be made to require HoP access if its a concern.

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/15494566/2c556a16-2159-11e6-87b3-fdb7a9e98089.png)

I never even knew janitors had these neat PDA functions.

**Comment by Imagebard** [comment]
>Located mops
>Located mop buckets

WHY and HOW do those things have GPSes

**Comment by FudgePucker** [comment]
When the clown steals your bucket

**Comment by Imagebard** [comment]
Grind a monkey and get another one

**Comment by ComicIronic** [comment]
> grind a monkey

Not on this server furfriend.

**Comment by FudgePucker** [comment]
Mop bucket is the large cart you drag around

**Comment by Imagebard** [comment]
>furfriend

If the only server you know is Citadel I'm afraid that I might not be the "furfriend" here.
