### ISSUE TITLE
Make Clown Curse wiz spell turn your PDA into a clown PDA

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10185]
Maximum fun for everyone involved ;^)

**Comment by Kurfursten** [comment]
Only if statue turns your PDA into a crystal PDA

**Comment by Probe1** [comment]
honk virus intensifies

**Comment by Exxion** [comment]
Only if it changes the cartridge, too

**Comment by Probe1** [comment]
WYCI

**Comment by 9600bauds** [comment]
Ok remind me to code this

**Comment by Probe1** [comment]
I will remind you every single day.

**Comment by DeityLink** [comment]
_>5 years later_
