### ISSUE TITLE
Make virus carriers a thing

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#10193]
As in, being immune to a virus personally, but continuing to carry it and be infectious to others. Maybe it could be a genetics power, provided to traitor virologists via TCs?

I dunno, I've always wanted to be the plaguebringer as an antag, but you're either infected with 20 diseases and their progress is stunted by spaceacillin, or you're immune and awkwardly trying to infect people indirectly, through monkeys, tainted chem pills, and broken dishes.

**Comment by Kurfursten** [comment]
Related to #10175 if implemented as a traitor item

**Comment by DeityLink** [comment]
Supported by Nuviro.
