### ISSUE TITLE
explosions on ore crates delete the contents

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10195]
It should drop the contents instead.

**Comment by Shadowmech88** [comment]
Likely what's happening is that it _does_ drop the contents, and then the contents are hit by the explosion, destroying them.

**Comment by Exxion** [comment]
I don't think ores are damaged by explosions

**Comment by PJB3005** [comment]
@probe1 I don't think you want them to drop the contents though.

Byond can't handle that.

**Comment by Probe1** [comment]
It can handle it just fine when you press the verb to dump all contents on an ore box :confused:

**Comment by PJB3005** [comment]
Not for me.
