### ISSUE TITLE
Broken firelock in Defficiency Toxins Lab

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10197]
(WEB REPORT BY: dylanstrategie REMOTE: 172.93.109.202:7777)
On the Toxins Lab in Defficiency, in the southern entrance, there's a broken firelock on the left window facing the wrong way

There shouldn't even be firelocks on the window, so you should likely just remove them. Put rplasmaglass on it while you're here

**Comment by Konater** [comment]
Probe done this, can be closed
