### ISSUE TITLE
Virologist lacks a spawn

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10199]
This is likely an issue on all maps

Virologist needs to get his old spawn back in the Virology Lab, preferably directly at the workstation on a chair or something

If possible, add an extra spawn in case Virology gets captivating enough you have enough reason to get an assistant, not that it will be used right now

**Comment by Probe1** [comment]
...

damnit dylan.

**Comment by clusterfack** [comment]
This is why we don't merge things when people ask for them to be merged

**Comment by Probe1** [comment]
I'm on it.

**Comment by ghost** [comment]
Just so we're clear, they spawn in the Medical Doctors spawn, so it's not that bad, but it's something that needs fixing

**Comment by Exxion** [comment]
> 100% Tested

**Comment by Probe1** [comment]
I've tested it.  All maps have a virologist spawn and on Boxstation they spawn in viro.

Dylan spaghetti'd out over nothing.  When virologists were removed their spawns were left in.  Laziness wins again.

**Comment by Imagebard** [comment]
>This bug exists
Actually no it does not

What

**Comment by Exxion** [comment]
So hold on
You neither tested your changes nor tested things out before saying they were broken?

**Comment by Probe1** [comment]
we've all had spaghetti before.

**Comment by ComicIronic** [comment]
dylan needs serious testing
