### ISSUE TITLE
Remove sinister force/dark forcefield from blocking ghost movement

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#10198]
Why is this a thing?

I clicked observe to observe, not to be only capable of observing until someone goes somewhere interesting. You can even bypass it by clicking "jump to mob", you just can't move on your own or auto-follow, so it's nothing but a huge inconvenience that seemingly exists for no reason.

**Comment by Exxion** [comment]
Auto-following inside those areas doesn't work anymore? Man...

**Comment by Killette2** [comment]
Muh secret areas.

Which might be good, if we actually had decent secrets that ghost couldn't reach and carbons had to get there manually.

**Comment by unid15** [comment]
You can see what's inside them anyways, just zoom out

**Comment by Imagebard** [comment]
>you just can't move on your own or auto-follow
or auto-follow

Wait what
WHY
FOLLOWING SOMEONE IS THE ONLY REASON YOU'D PLAY GHOST

**Comment by clusterfack** [comment]
I'm pretty sure could make them invisible to ghosts too if we tried
