### ISSUE TITLE
cereal boxes don't show item

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10192]
(WEB REPORT BY: manfreed REMOTE: 172.93.109.202:7777)

> General description of the issue
> Cereal boxes no longer show the item they are made from
> 
> What you expected to happen
> see carrots on my carrot cereal boxes
> 
> What actually happened
> They where blank
> 
> Steps to reproduce if possible
> take food item
> make cereal from it

**Comment by Killette2** [comment]
You're too old to see why kids like the taste of carrot toast crunch.

**Comment by ComicIronic** [comment]
Byond overlay issue most likely, the server's going to need an announcement about it.

**Comment by Manfreedo** [comment]
Is fixed now.
