### ISSUE TITLE
Biofoam

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10201]
[Discussion]

I intend to code this at some point, this is mainly a note to self.

Biofoam injectors that, when used, can stem internal bleeding for five minutes by filling the body cavity with biodegradable foam.
Should make internal bleeding less of a guaranteed death sentence by giving the victim time to make it to surgery to have it repaired.

**Comment by 9600bauds** [comment]
Inaprov is supposed to slow down internal bleeding 
Make that matter more

**Comment by Exxion** [comment]
You sure about that?

![image](https://cloud.githubusercontent.com/assets/9827785/15554045/26a2b5dc-2290-11e6-9976-67982073320a.png)

Because this is its entire `on_mob_life()`

**Comment by clusterfack** [comment]
Look in organ code

**Comment by Exxion** [comment]
Alright, inaprov and bicard both make internal bleeding stop getting worse and temporarily slow it down, but neither actually makes it better.
Inaprov used to slow down _external_ bleeding but that's commented out.

**Comment by Shadowmech88** [comment]
Does "stop internal bleeding from getting worse" mean it halts the blood loss?

**Comment by Exxion** [comment]
No, just makes the wound not open further over time
They do slow the blood loss, though

Also, I read further and bicard (but not inaprov) WILL actually slowly heal internal bleeding, but only in huge doses.

**Comment by Exxion** [comment]
Also, I'm stupid and dumb
Wound growth is only completely stopped by having both bicard AND inaprov in your system
I'm not 100% certain that's intentional though

**Comment by Exxion** [comment]
Nope, not intentional.
Some dumb person in another codebase simply copied the bicard code and replaced it with inaprov, thus nearly DOUBLING the rate of bleedout and exactly doubling the rate of wound growth for internal injuries while neither chem is in your system
Then this managed to get ported along with some onclick code changes
This was all over two years ago

**Comment by Kurfursten** [comment]
> nearly DOUBLING the rate of bleedout

Gee I wonder why bleeds became so deadly a little over 2 years ago

**Comment by clusterfack** [comment]
Whose fault was it?

**Comment by Imagebard** [comment]
>Some dumb person in another codebase simply copied the bicard code and replaced it with inaprov, thus nearly DOUBLING the rate of bleedout and exactly doubling the rate of wound growth for internal injuries while neither chem is in your system

So basically bleeding out being so deadly is basically some huge bug?
Christ

**Comment by ghost** [comment]
It's better than the old result of fucking nothing imagebard.

**Comment by Imagebard** [comment]
People being guaranteed to die in a few seconds due to a bug is better than nothing happening due to a bug?

**Comment by 9600bauds** [comment]
I wish unfucking blood loss was that easy, I'm pretty sure this bug is just for internal bleeding

**Comment by Exxion** [comment]
Yes, what I mentioned is just internal bleeding
And the thing was ported by N3X15 but I have no idea who actually made the error

**Comment by clusterfack** [comment]
I bet it was riri
