### ISSUE TITLE
Biogenerator not producing ez nutrient or any form of nutriment

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10209]
(WEB REPORT BY: corncolonel REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Biogenerators do not produce any nutriment like ez nutrient despite there being points in the machine.
> 
> What you expected to happen
> Biogenerator produces nutriment
> 
> What actually happened
> Nothing is produced
> 
> Steps to reproduce if possible
> Process plants for bio points, attempt to make ez nutrient.  Machine activates but nothing is produced.

**Comment by Killette2** [comment]
This is a prime example of why AHELPS should be used before BUGREPORTS

You did not make any specifications in this bug report. The way biogenerator works is changed, and it no longer prints bottles. Did you detach the beaker in this scenario, it was not specified? Now you have to detach the biogenerator beaker where the fluid is now generated.

**Comment by ghost** [comment]
Can confirm that it works fine. I was generating eznutrient, robust harvest, and left4zed from the ghetto botany and research outpost biogens all day yesterday. It's in the beaker now that it's an actual chem instead of magic fairy glitter.

**Comment by 9600bauds** [comment]
Working as intended

**Comment by Kammerjunk** [comment]
I remember making robust harvest and ez nutriment through the biogen ages ago, way before botany3, and it was still in a beaker back then

**Comment by Killette2** [comment]
That's correct Krammer, change got added late botany2

t. Rowan

Fuck why am I the ONLY idiot who spends 90% of his rounds in botany
