### ISSUE TITLE
Wet footprints invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10214]
(WEB REPORT BY: manfreed REMOTE: 172.93.109.202:7777)

> General description of the issue
> Wet footprints seem to be currently invisible
> 
> What you expected to happen
> To be able to see wet footprints
> 
> What actually happened
> They are ther, but I don't see them
> 
> Steps to reproduce if possible
> Make someone bleed on the floor
> Walk trough it

**Comment by ComicIronic** [comment]
THANKS BYOND
Is this an issue or just overlays AGAIN

**Comment by clusterfack** [comment]
Overlays
