### ISSUE TITLE
Breaking your space beer as a borg fucks your modules up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10212]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b257edc23a88bcfbd6ce9902f59eedc797794edf 
> 
> General description of the issue
> If you break your space beer on someone/something that module slot becomes unusable. You can't drop it or deselect it from the menu.
> 
> What you expected to happen
> TO not have a ghost bottle
> 
> What actually happened
> Phantom Limb Syndrome
> 
> Steps to reproduce if possible
> Become a borg and pick Service.
> Break your space beer bottle over someones head and TRY to drop that shit slot 1/whatever is fucked

**Comment by 9600bauds** [comment]
H A R M

**Comment by Killette2** [comment]
It's ok if it's not human harm. Also funny enough, it's sawbones bug. The infamous glass him lover.

**Comment by TheFriggenSawbones** [comment]
i was purged at the time ok and it was still an accident i wanted to feed them vomit

**Comment by Exxion** [comment]
Stacks used to do this if they were emptied, but that got fixed
I think
I wonder if a more general fix is possible

**Comment by ghost** [comment]
Same goes for medborg syringes if you accidentally harm-intent stab somebody

Could be fixed by refreshing the modules of a borg when they're in a borg recharger? Maybe specifically ones that can be broken?
