### ISSUE TITLE
there is no chemical fridge circuit in the circuit printer 

### ISSUE THREAD

**Issue by pvak** [d3athrow/vgstation13#10213]
#### Description of issue

no chem fridge circuit
#### Difference between expected and actual behavior

to be a chem fridge circuit
#### Steps to reproduce

find there is no chem fridge circuit
#### Specific information for locating

circuit printer
#### Length of time in which bug has been known to occur

a lot of time
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
Are we sure there isn't a more general smartfridge circuit?

Also: mode (botanical / chemical / any) should be toggleable with a multitool or something

**Comment by pvak** [comment]
tried a multitool, a screwdriver and a crowbar on smart fridge circuit and it did nothing

**Comment by Kurfursten** [comment]
That wasn't a fact, it was a suggestion. It _should_ be toggleable, but it isn't.

**Comment by ComicIronic** [comment]
The path does exist. A design for it doesn't seem to.

`/obj/item/weapon/circuitboard/smartfridge/chemistry`

None of the specialist Smartfridges have their own designs.
This wouldn't be a problem but the default Smartfridge is the botany one and that only accepts food and grown stuff.

**Comment by Probe1** [comment]
This reminds me I need to make a mining smartfridge for sheets.

**Comment by Exxion** [comment]
Friendly Reminder that the chemfridge outmodes all other smartfridges because it can hold anything any other smartfridge can except seeds

**Comment by Kurfursten** [comment]
Sometimes you WANT restrictions though.

For instance, a really annoying clown might make it hard to pick out pills in an emergency if your smartfridge reads:

Apple
Banana
Berry
Bicaridine
Chantrelle
Cherry
Clonexadone
Cryoxadone
...
...

**Comment by Exxion** [comment]
And you can do that with the chemfridge
All foods can already go in it
Try it

**Comment by Kurfursten** [comment]
I agree with you, I'm saying we might want to tighten the restriction and have a toggle for mode.

**Comment by Exxion** [comment]
(#7785)
