### ISSUE TITLE
Noir should have an exception for women wearing dresses

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10211]
Noir already makes an exception for blood.  What other than blood does the detective chase?  The dame.

**Comment by ghost** [comment]
That's genius.

**Comment by kol1th** [comment]
you, are a genius

**Comment by ghost** [comment]
Should we make it anyone wearing a skirt for @NigglyWiggly 's benefit?

**Comment by kol1th** [comment]
@DrCelt of course

**Comment by Imagebard** [comment]
>Inserting traps into my Film Noir

![1416823576665](https://cloud.githubusercontent.com/assets/7571238/15584373/c64adf5e-2350-11e6-93ef-864087417588.png)

**Comment by MusgardTiger** [comment]
When u see thicc gray dame in green wedding dress:100:
