### ISSUE TITLE
Doors to Interrogation Room/Processing are called "Security Office"

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10218]
![mspaint_2016-05-27_00-42-09](https://cloud.githubusercontent.com/assets/6526157/15597136/dcb67462-23a3-11e6-957d-9b3b2488605d.png)

While we're at it: People often don't know what to call this room, partly because of this error and partly because there's already another room called Interrogation. If it's even possible, I'd love for it to be called "Processing" instead, to be clearer

**Comment by ghost** [comment]
It can be anything you want to be really, which is why the doors are called "Security Office". That's not an accident

**Comment by Shadowmech88** [comment]
Yeah, but isn't the large room to the West also called Security Office? The room just outside the HoS office?

**Comment by Kurfursten** [comment]
Shadowmech is right. This is just a case of lazy mapping, someone didn't want to rename airlocks.

**Comment by Probe1** [comment]
If ive learned anything, its not laziness its either an artifact of the older brig or just plain whoops because of how irritating dm is.  Anyway ez fix i'll go over the box issues and get something out tonight
