### ISSUE TITLE
Blob storm spawns too many overmind blobs

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#10217]
Ultimately results in LOTS OF BLOB OVERMINDS HOLY FUCK.
Needless to say this usually ruins the current round.

**Comment by Probe1** [comment]
Needs to be a middle step between the two with 1 or 2 max.

**Comment by Kurfursten** [comment]
Limit to one overmind. If you want to give them a boost, send more nodes, but no more overminds. Or if you absolutely insist, the second player needs to be a cerebrate, not an overmind.

And the number of players active may need tuning... I recall a deadpop long around on metaclub a week or two ago where we had six active players. Blob storm happens, everyone immediately heads out with lasers and hardsuits. By the time we start taking shots at it, it's already too strong to beat by just six people.

**Comment by AutismSpider** [comment]
Help if the nodes crash close by the over-mind and not into ass end of no were

**Comment by Imagebard** [comment]
@AutismSpider 
Its still an useful distraction

**Comment by AutismSpider** [comment]
If it hits some times they don't hit any thing and poof into next Z level

**Comment by Imagebard** [comment]
Eh, blobs usually start with just themselves. Sure, meteor blobs ditch stealth and don't get the short period where they're human to grief, but they join later on, so the chances are that the station is in flames.

**Comment by Kurfursten** [comment]
Outdated
