### ISSUE TITLE
Slimes not splitting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10227]
(WEB REPORT BY: smokey5454 REMOTE: 172.93.109.202:7777)

> Slimes wont split at all
> 
> When I feed my slimes a shit ton, I expect them to split after a while.
> 
> Slimes never split

 1, Just feed the slimes a few tiems and watch

**Comment by 9600bauds** [comment]
#10226

**Comment by ComicIronic** [comment]
This is the slime version of this non-atomic issue.

**Comment by Kurfursten** [comment]
Worked for me this morning, needs more testing

**Comment by nervere** [comment]
Whatever this was, it's definitely not an issue anymore.
