### ISSUE TITLE
Cabin 1 on Metaclub is not linked to the door button

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10222]
Door can't be bolted, if you press the bolt button nothing happens

Just another case of bad id_tag instancing

**Comment by CptWad** [comment]
I had a dream where you could drag and drop id connections between machines when mapping

**Comment by Probe1** [comment]
Good dream.

Also where the fucks cabin 1?  The research outpost?  The dorms?

**Comment by Kurfursten** [comment]
The dorms
