### ISSUE TITLE
Stone Mask is not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10221]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
I stained Stone Mask with blood on test server and it doesn't seem to turn me into a vampire.

**Comment by Shadowmech88** [comment]
You wore it and then splashed it with blood?

**Comment by ComicIronic** [comment]
People need to be slapped with the bugreporting guide instead of letting them delete it from the webtool window.

**Comment by ihadtoregisterforthis** [comment]
Then we would only have 

> Description of the problem:
> _the thing didn't happen_
> What you expected to happen
> _the thing_
> What happened
> _not the thing_
> Steps to reproduce
> _try to do thing_

---

Tried splashing the mask while wearing it on the test server and it worked.

**Comment by ComicIronic** [comment]
Please confirm again on live with an admin and then I'll close this.

**Comment by DamianX** [comment]
it does work
CLOSE IT
