### ISSUE TITLE
Log plasma gas ignition

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#10223]
I've had problems with this before, plasma release is logged but ignition of said plasma is not. Some guy can quickly whip outa welder and put it back in his toolbelt and we wouldn't know about it. 

If it is possible please log this thing thank you yhwh bless :100: :100: :100:

**Comment by Imagebard** [comment]
>Some guy can quickly whip outa welder and put it back in his toolbelt and we wouldn't know about it. 

Would this be worth _[OH GOD ITS LOOSE]?_

**Comment by ComicIronic** [comment]
God no, that's for gamebreaking shit.

**Comment by jknpj** [comment]
Does this include plasmamen spontaneous combustion? Or just in-the-air plasma?

**Comment by west3436** [comment]
No interest in implementing this since issue creation. There are many potential sources of plasma ignition so this could quickly spam the logs.
