### ISSUE TITLE
Bug with grinders

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10225]
(WEB REPORT BY: smokey5454 REMOTE: 172.93.109.202:7777)

> Grinding plasma in a grinder doesn't work
> 
> When I grind plasma, I expect it to grind into a beaker. 
> 
> Plasma dissappear 
1. Put plasma in grinder
2. Grind
3. Watch as nothing comes out

**Comment by ComicIronic** [comment]
This is the grinder version of this non-atomic issue.
