### ISSUE TITLE
All-In-One Grinder and mortar are FUCKED

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#10224]
#### Description of issue

I don't know if the two issues are related, but I would imagine so.
The grinder and mortar seem to have some serious issues. They cannot grind some items necessary to job progression (like grinding solid plasma to liquid plasma).
This cripples medbay regarding cloned patients (clonex heals 3 clone damage per tick opposed to cryox healing 1 clone damage per tick) and xenobio regarding plasma reactions.
#### Difference between expected and actual behavior

**Grinder**
When attempting to grind stuff like meat or pills, it gives the reagents of the object. When attempting to grind plasma or metal sheets, however, the sheet is eaten up but the beaker does not contain 20u plasma/iron.
**Mortar**
When attempting to grind anything in the mortar (tried: flare, plasma sheet, cable piece, monkey meat), you get the message that you've ground the contents, but the mortar does not remove the object and does not contain 1u of whatever you ground up.
#### Steps to reproduce

**Grinder**
Place beaker into grinder
Place plasma sheet into grinder
Grind
**Mortar**
Place compatible item (see above section for tested items) into mortar
Attempt to grind
Inspect mortar
#### Specific information for locating

Grinder: `/obj/machinery/reagentgrinder`
Mortar: `/obj/item/weapon/reagent_containers/glass/mortar`
Message upon grinding in mortar: `You grind the contents into dust!`
#### Length of time in which bug has been known to occur

A few days at the most, my guess is a day or so.
#### Server revision

0893e93e4d94b511a5af2b38b6a774828194844f
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
It looks like they are using is type in list incorrectly and that's causing their list to get fucked up
