### ISSUE TITLE
Bug with grinders and slimes not splitting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10226]
(WEB REPORT BY: smokey5454 REMOTE: 172.93.109.202:7777)

> Grinding plasma in a grinder doesn't work, and slimes wont split at all
> 
> When I grind plasma, I expect it to grind into a beaker. When I feed my slimes a shit ton, I expect them to split after a while.
> 
> Plasma dissappear and Slimes never split
> 
> Plasma stuff
> 1. Put plasma in grinder
> 2. Grind
> 3. Watch as nothing comes out

 Slime stuff
 1, Just feed the slimes a few tiems and watch

**Comment by 9600bauds** [comment]
#10225
