### ISSUE TITLE
No oxygen when the bus moves on bus station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10236]
(WEB REPORT BY: orangerush REMOTE: 172.93.109.202:7777)
716fc8ea79819a0a4aa32de1e59b5d63fc8537b1

No oxygen and you get knocked down by air

**Comment by Probe1** [comment]
sure enough busses steadily lose o2

**Comment by Probe1** [comment]
I spent some time testing this and my best guess is the propulsion doodads are to blame and need windows.  But I'm really not sure at all.

**Comment by Kammerjunk** [comment]
As far as I can tell, yes, the propulsion things aren't airtight and definitely need windows. Possibly also a floor underneath them.
If people break these windows, I don't think it'll be possible to fix them without fucking about since you probably can't walk on the propulsion things.

**Comment by gbasood** [comment]
I think the propulsion things DO have windows on other shuttles
