### ISSUE TITLE
TEG burning chamber computer can't detect injector

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10248]
(WEB REPORT BY: jellyveggie REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> baaa4e48682da18c80d2481b5ce7bfdfbe742951
> 
> General description of the issue
> Burn chamber tank computer does not detect any in/out ports
> 
> What you expected to happen
> Computer, injector and sensor frequencies for the burn chamber should match
> 
> What actually happened
> Computer and sensor had 144.9 as frequency, injector had 143.9, forcing you to enter the chamber and change it with a multitool. Access to the chamber is done through space instead of the TEG room, further complicating the issue

**Comment by Probe1** [comment]
This issue is for Bus Station.  I checked.

**Comment by Probe1** [comment]
whoops didn't quote it right, this is good to close
