### ISSUE TITLE
Bus station brig

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10242]
(WEB REPORT BY: mrslippy REMOTE: 172.93.109.202:7777)

> General description of the issue

Lock down doors at the entrence of the brig mess with the entrence doors, means you can't shut them by hand.

> What you expected to happen

Beable to close doors by hand to enhance security as there are 2 paths leading from the entrence.

> What actually happened

You have to wait for the doors to close automaticly, trigering autisem.

> Steps to reproduce if possible

Lockdown blastdoors could be moved up or down a tile, or the doors.

**Comment by Probe1** [comment]
I'm at a loss as to what he's reporting here.  The lockdown button drops blast doors and seems to be working as intended.

**Comment by Kurfursten** [comment]
I figured out what he meant. He's saying that if you close the main blast doors, you can't click-close the brig airlocks because they're under the blast doors - you have to wait for them to autoclose instead.
This is standard though, I think.

**Comment by Probe1** [comment]
I didn't notice because I alt clicked to do that, and could do that.

**Comment by Kurfursten** [comment]
Oh. Should be safe to close then @PJB3005

**Comment by Kurfursten** [comment]
I thought we decided this wasn't a bug
@gbasood @clusterfack @ririchiyo @ComicIronic
