### ISSUE TITLE
No air tanks for miners?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10245]
(WEB REPORT BY: disko REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Is there an air tank dispenser for miners? I had a look around the mining outpost and I dont think there is one.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Probe1** [comment]
Good t close
