### ISSUE TITLE
Bus Station - Medbay Complaints

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#10247]
ok medbay pros lets unite here.

The placement of things is kinda fucked up. Cryo being so close to the entrance is bad, possibly switch it with where the sleepers are? I feel like it'd be better as sleepers can be used to solve problems quickly while cryo is usually a longer commitment. Also it'd be so easy to fuck up cryo as a traitor with it being right there.

No lobby area kinda sucks but I guess you can't really have it since it's a compact station.

Speaking of cryo, the tubes should be under the tiles probably.

Chemistry and Storage should switch - It sucks to have the chem freezer far away and behind a door. 

The morgue feels way too big, especially when you look at cloning and it's a small piece of shit.

Possibly reroute the way into the telepad room? Medbay having its own is cool (how the fuck does teleporting aliens work is that going to kill everyone) but being behind two doors kinda sucks and overall the room feels kinda overly big.

In the end I think medbay needs a ton of reshuffling as it's clunky as hell. A lot of bigger rooms need to be smaller, and smaller rooms bigger.

**Comment by invoid9** [comment]
Here's a proposed how to reshuffle chem and storeroom with hallway thingy. This took 2 hours in MS paint, so please don't laugh at me. I hope it makes sense. Issues I see are that chem is too small in this pic, storeroom may be too large and telesci walls get fucked. This is just some intense idea guyying to get the gist of what sawbones already said. 

![proposed medbay bus](https://cloud.githubusercontent.com/assets/10618215/15626279/abd55158-2504-11e6-9911-e58b590da1be.png)

Again, please don't laugh. Ignore the pink.

**Comment by MercuryDoll** [comment]
The medbay storage room can definitely be smaller, with the chemistry taking its place, there should be enough room for a corridor to directly connect the telepad room with the medbay central hallway, remember what that telepad is used for: medical emergencies. You want the dying (probably already way into crit) patient towards surgery and cryo as fast as possible. The glass windows/windoor at the cloner is also stupidly inconvenient, there should be enough room to expand it that section.

**Comment by Probe1** [comment]
I have hidden the cryo pipes.  I have not addressed any of the other issues here.

**Comment by Kurfursten** [comment]
I'm open to completely changing medbay from the ground up, but you should know that you can click a windoor with your open hand to leave a windoor permanently open.

**Comment by invoid9** [comment]
There's missing lights in topright corner of storage room and in the entrance near cryo. Maybe even chem needs more light. I'm sick of dark medbay. (I checked, it wasn't busted lights, there were no fixtures. Also minor issue is there's no breakroom/pizza and no patient rooms, so there's really no place to go braindead and be out of the way, unless you leave yourself in maint which is lame.

**Comment by Kurfursten** [comment]
I have been thinking about this a great deal. How do you like the look of this? This drawing is to-scale.
![untitled](https://cloud.githubusercontent.com/assets/9782036/15629892/c16ea2e4-24eb-11e6-828a-2d4942d9838c.png)

If you don't like spacemorgue I could maybe swing it down to the maint and shift maint down (there's space). But I disagree that morgue doesn't need to be so big. I just experienced the wild ride on Bus and you need some corpse space.

Another option with this big open space is of course to pull down the sleepers into the lower area and make a small lobby in the front there. It would be very small but there would be a desk. Think Deff lobby.

**Comment by invoid9** [comment]
I think 1 of the surgeries can be halved and a patient room/break room can be placed as well. If there's room for another advanced body scanner that would be awesome to. Are you planning on having the cloning pods in genetics proper or out in the hall like it is now? I don't see why the cloning pod can't be in the hall without any sort of window obstructing it at all. Right now, that 3x1 window room is kinda unwieldy to manage. 

Also, that's a massive area between chem and paratelesci. Could do with expanded chem. Or maybe even making a proper lobby where the sleepers are and moving the sleepers down between chem and paratelesci. There seems to be plenty of space for cryo/sleepers as well as a proper lobby. Just a thought.

Is it possible to make morgue accessible without having to go through maint? 

That's all I got, hoping someone else gives feedback too. I prefer this to what we have now anyway. Thanks for all the work, by the way.

**Comment by Kurfursten** [comment]
This is more or less what the room sizes would look like in the proposed designs.

Obviously the rooms haven't been fixed for their new positions so those would change internally. But how do you feel about this from a flow perspective?

![untitled](https://cloud.githubusercontent.com/assets/9782036/15630959/f9c1ffb2-2516-11e6-9db3-4169369e89de.png)

**Comment by invoid9** [comment]
Swap cloning pod with genetics. Cryo should never be that far away from the pod. 2 advanced body scanners would be nice, and like I said before, patient/break room would also be nice. I think this plan is much better in general.

**Comment by Kurfursten** [comment]
There's just no way to swap the cloning pod with genetics. Genetics is so much larger and there's no more maint to use after putting the morgue down there.

**Comment by MercuryDoll** [comment]
Can you swap storage and cloning then?

**Comment by Kurfursten** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9782036/15658602/108d7e24-2684-11e6-88a4-4feb487dc418.png)

Another revision attempt. This medbay feels a lot bigger and more open. Not happy with paramedic room. Feels a little weird to have cryo and cloning down there below chemist. Maybe swap locations? There's an alternate medbay entrance down there too for fast entry.

**Comment by Kurfursten** [comment]
How about this? I'm finally feeling good about one. This has the telepad, the cloner, and cryo all close together. It has a patient room. Cryo is not easily accessed by antags but still in the central treatment area. The treatment area is close to the chem fridge. There is a lobby.

![untitled](https://cloud.githubusercontent.com/assets/9782036/15691414/303392fc-274e-11e6-9818-04b091328245.png)

**Comment by PJB3005** [comment]
1. That cloning is too small and it's not linked to genetics in any way so geneticists get to fuck off even more.
2. 1 tile wide main door is too small.

**Comment by Kurfursten** [comment]
Nothing we can do will ever make geneticists do cloning. Two-wide door is doable, though, I'll just move the button down.

I might be able to swap the geneticist and CMO offices though. Then they'd be adjacent at least.

**Comment by Kurfursten** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9782036/15692275/1bfe0470-2753-11e6-9af5-c1d4ca627fcf.png)
Long genetics?

**Comment by Kurfursten** [comment]
I could really use some feedback from you medbay pros. Do you not like the long genetics? Instead, I could shift the monkey pen to the right and have the maintenance door enter through the back of it.

I feel really good about where medbay is right now though, so I went ahead and did tile coloration and most of the piping, but feedback has started to go silent. I'm willing to put in the work if you guys are willing to talk about it.

**Comment by Kurfursten** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9782036/15700416/5c2aea7c-2799-11e6-8725-243690bb0137.png)

Added some pipes and color, pretty satisfied with this build assuming no one has last minute complaints. Still needs wires and areas redefined. I was holding off in case someone had last minute input that might make me shuffle rooms around again.

**Comment by invoid9** [comment]
Personally, I don't like the cramped window pen for the cloning pod. I would remove the glass completely and just use tile paint or something to mark the cloning area. That's just me, I don't know if anyone else feels the same or if it's a good idea. 

Everything else is awesome to me. Just a few little things.

-Chemistry and cryotubes need space cleaner in/near them
-Needs to be a sink in general medbay area somewhere
-I remember old medbay needed more lights, just a reminder
-Also, old taxi medbay had fuckery with light switches in patient room turning off general medbay lights. I can't spot any light switches in the main are.
-Chem could possibly do with maint access
-Could also do with chemistry wardrobe.
-Box medbay also has 2 of each medkit type in the store room, and extra general medkits lying around

I wish really experienced medbay players would comment in this thread more, but oh well. That's my amateur opinion.

**Comment by MercuryDoll** [comment]
I'm not a certified MD, but i agree. The cloning "pen" looks really weird. Either open it up completely or give it a proper room, by moving the monkey pen to the east as you suggested that may give enough room to do so.
The placement of the telescience pen is also odd but workable i guess.

**Comment by Kurfursten** [comment]
Chem is a high security area that gets broken into a lot, so I don't think adding maint access is wise there. As for other detail stuff (light switches, requests consoles, APCs, wires) - that will all be sorted out before it gets pushed, I am aware of that stuff. I just wanted to see if people liked the shape before I committed to that.

This next update will also fix 
#10325 
#10328 
#10272 
#10335 
#10317 
#10338 
#10250
Also unstacks all vents in medbay as per #10265

**Comment by nuklearcellphoneg** [comment]
I don't think this was mentioned throughout and is a little bit from memory but

Chemistry was missing(this is from when Chem was at the bottom with the storage room right above):

Space cleaner

2x Inaprovaline pill bottles with 7x 30u Inaprovaline pills

2x 30u antitoxin glass bottles

2x 30u inaprovaline glass bottles

Also, and I believe this is still the case, it has a whopping 5 large beakers. I LIKE this, but it's not the case with other medbays(keep in mind there is a large beaker in the grinder). I don't think it's too game breaking but this is more about consistency and very slightly about preventing OP antag chemists from round start(two max cap water potass nades right there among other possibilities).

Cryo:

This is more of a suggestion but

-Make table to the right of Cryo tubes, place the 2x beakers(should have 30u cryoxodone in them) and wrench and iirc crowbar)

-Remove beakers/wrench from the table south of Cryo tubes, place two general medkits(good area, general treatment will probably occur here)

ALTERNATIVELY

-Place a table by the sleepers with the two General Medkits. Either way you need the general medkits for when there are no medbay staff, etc

Storage:

-Needs 2x of each type of medkit, not just one type

-Can't tell via pic if some of these are already there, but needs Box of: Syringes, small beakers

-1 bottle each of: Toxin, Anti-Toxin, Sleep-Toxin, Inaprovaline

-Filled blood bags??

-Med HUDs???

**Comment by invoid9** [comment]
While we're talking about consistency between all medbays. Last time I played, the plasma roundstart in chemistry was 100u.

Not sure if really an issue, just thought I'd point it out

**Comment by Kurfursten** [comment]
@nuklearcellphoneg Most of the stuff you list is there now

**Comment by nuklearcellphoneg** [comment]
@Kurfursten 

https://cloud.githubusercontent.com/assets/9782036/15700416/5c2aea7c-2799-11e6-8725-243690bb0137.png

Like so?

**Comment by Kurfursten** [comment]
Yes, although that's not the most updated image. The one from the PR (see above) has wires and some other stuff (like space cleaner added).
