### ISSUE TITLE
Bus Station's Safe is shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10241]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!) baaa4e48682da18c80d2481b5ce7bfdfbe742951 

Bus' Vault Safe is really bad, a shitty bear pelt hat and a painting is a lot less than whats on box (painting, jumpsuit, key, replica katana)

**Comment by Kurfursten** [comment]
Next revision will have two worthwhile rewards
