### ISSUE TITLE
[Bus] Map issues with toxins and one research outpost.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10250]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision baaa4e48682da18c80d2481b5ce7bfdfbe742951 
> Toxins only has 3 valves instead of 6 which is shit for adjusting mixes after a test

No portascrub at all to clear plasma tanks

No portapump at all when it needs 4 for clearing tanks and handling small quantities of gas/cold gas since canisters only fill to current pressure unlike portapumps

No heater

No regular pipe dispenser or a filter on the burn chamber outlet, a gas mixer hookup to minimize waste, a heat exchanger hookup to the pre-gas pump outlet so you can still heat plasma when you fucked up and got a ton of co2 you can't get rid of.

No toxins test site?

Research outpost has no portascrubs for helping clear gas gen large artifacts

**Comment by Probe1** [comment]
I have added portascrubbers and portapumps in both the research outpost and toxins storage.  I have not addressed the other issues raised in this issue.

**Comment by Probe1** [comment]
@SarahJohnson489 where would you put the bomb test range cause I sure don't see any easy answer here.

**Comment by ghost** [comment]
You can put a dock south of toxins and just pooch it out to the east. you'll have to extend a little down and it'll go. A couple tests with vv to get the timer right.

Alternately, you can put in a shuttle/extra shuttle destination ala deff that goes to a copy/paste tox test out on the mining roid and add an smes so it stays up.
