### ISSUE TITLE
Bus Station cams and lighting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10258]
(WEB REPORT BY: ghlor REMOTE: 172.93.109.202:7777)

> Some parts of the station doesn't have proper illumination at roundstart due to lights being too far away in some locations. Read: Nearby the chapel, among other places.

There is also no cameras in the hallway outside of Toxins Lab, inside the break room, xenoarch wing room, toxins storage, some parts of xenobio, xenobio containment, Research Devision Access, RD/Coldroom, among many other places too.

> What you expected to happen
> That the AI, and crew would have proper
> optimal vision of departments, et cetera.
> 
> What actually happened
> Made mesons very important.
> 
> Steps to reproduce if possible

**Comment by Kurfursten** [comment]
@PJB3005 This was actually fixed in the last hotfix

Forgot to link it
