### ISSUE TITLE
[Bus] Science

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10256]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision baaa4e48682da18c80d2481b5ce7bfdfbe742951

RnD - No gadget bags, No hand labler and box of refills, Needs fire alarm, light switch. Duplicate newscaster

Toxins - wire and pipe break one tile above its entry airlock. 

Toxins storage - Needs an air alarm

RD - Air alarm, fire alarm, keycard auth, light switch, newscaster, intercomm, planning frame. firelock on the door

RD division - both areas, air alarm, fire alarm, light switch. Access needs a firelock. Move the sound system out from under the RD glass so we can use it.

Break room - firelock, fire alarm, air alarm, intercomm, light switch

Shuttle dock - Fire alarm, air alarm, intercomm, light switch

**Comment by ghost** [comment]
Camera coverage in general seems to be spotty.

**Comment by Probe1** [comment]
I'm done for the day.  These are all easy fixes and it shouldn't take whoever more than 30 minutes to clear the issues that are up now.

**Comment by Kurfursten** [comment]
Thanks, all these are in the next one.
