### ISSUE TITLE
Adding coordinates and damage to attack logs. 

### ISSUE THREAD

**Issue by SplergeBucket** [d3athrow/vgstation13#10253]
okay so we get logs like this
![](http://i.imgur.com/s519wxs.png)
rather than logs like this
![](http://i.imgur.com/72pvmTn.png)

iunno if hippie got em from tg or whatever but im sure you can just steal them from somewhere and it's all of a sudden better than the colour burgundy

anyway its useful im telling you its gunna be great it'll look good it's a swap for the betterment of mankined also probhe told me to make this an issue iunno how this istuff works and buttons hurt my eyes

**Comment by ComicIronic** [comment]
What are you asking for?

If the first image is the logs you currently have, what do you want to be added? Coords and hp are already there.

**Comment by SplergeBucket** [comment]
the first image is from hippie's code
the second is from /vg/'s

hp appears for punching by saying how much damage was done by the punch, but attacks don't list the mobs health afterwards for example
coordinates don't pop up in the attacklogs presented in vv, but they do in the attacklog itself like so: [01:08:30]ATTACK: Dr. Slippy Joe M.D (garethgobblecoque) fired the energy gun (proj:laser) at Shichika Matsushita (smokyprogg) (233,252,1), so it's okay-ish i suppose

what im asking for is coords and hp added to the view variable attacklog for possible increase to ease of life

**Comment by west3436** [comment]
No interest in implementing this since issue creation
