### ISSUE TITLE
wraith black screen and shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10251]
(WEB REPORT BY: crnibombarder REMOTE: 172.93.109.202:7777)

> Revision fuck heil hitler, wtf do I put here?
> 
> General description of the issue
> it was an average murderbone wizard round, the wizard blasted my ass and sucked my soul up, he then turned me into a wraith but it was just a black screen and I couldn't do anything  (say, use the wraith ability, etc) relogging didn't help me.
> 
> What you expected to happen
> for me to murder bone as a wraith
> 
> What actually happened
> bullshit black screen ruining muh fun and immersions.
> 
> Steps to reproduce if possible
> 1. get soul sucked off
> 2. turn into wraith
> 3. black screen

**Comment by ComicIronic** [comment]
Probably got null spaced somehow.
