### ISSUE TITLE
Stacked vents and scrubbers on different layers are fucking ugly.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10265]
![](http://i.imgur.com/EIXBciM.png)

**Comment by ComicIronic** [comment]
Scope this hothead with his opinions.

**Comment by Kurfursten** [comment]
I'll change it someday - but I will get to it

Cosmetic, low priority

**Comment by ghost** [comment]
Scrubbers and vents should likely not be stacked at all

With stacked pipes, you have tons of rooms to have scrubbers and vents branch off

**Comment by DamianX** [comment]
I think we can close this
