### ISSUE TITLE
Bus is boring.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10264]
I don't know what it is, but it just feels empty and boring.

Probably lack of details and other fun things.

**Comment by Kurfursten** [comment]
Here's a list of stuff for you to explore for next time
- Ghetto botany
- Abandoned teleporter room
- Abandoned holodeck room
- Animal testing / zoo
- Secret abandoned pod bay
- Maint rage cage
- Ghetto brig
- Destroyed room, open to space
- Ghetto bar
- Maint arcade
- Maint trade room
- Ghetto surgery
- Asteroid mini satellite
- Ruined solars
- Space sorter station

**Comment by PJB3005** [comment]
I'm talking about general areas, look at this room:
![](http://i.imgur.com/oJKtpYR.png)

You can't not call this boring.

**Comment by Kurfursten** [comment]
So what you want is a table with some metal and a signaller? Should've said that instead

Boring is vague. You should have named this: "Bus needs tables with random items on them"

**Comment by ComicIronic** [comment]
What room is that, EVA?

**Comment by Kurfursten** [comment]
Yes

**Comment by Probe1** [comment]
The first thing I heard other than the juke being busted about the bar is it was empty.  Boring empty dull et cetera.
