### ISSUE TITLE
Raise Dead rune brings people back as noncultists.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10262]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision c697cd94938cbb5314cdf83fe6b34201b643f6d5 
> 
> General description of the issue
> People revived with Raise Dead come back nonculted.
> 
> What you expected to happen
> They come back as cultists.
> 
> What actually happened
> Nope.
> 
> Steps to reproduce if possible
> Use Raise Dead rune (ha ha)

**Comment by ComicIronic** [comment]
Is this definitely the case or is it an overlay issue with the cultist symbol?
