### ISSUE TITLE
Hacking the Jukebox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10266]
(WEB REPORT BY: sacredatom REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Putting all the jukes offsets to 0 and cutting the Configuration wire doesn't put it in syndie mode
> 
> What you expected to happen
> The juke to turn into syndie mode 
> 
> What actually happened
> Nothing
> 
> Steps to reproduce if possible
> Set all offsets to 0 cut the Configuration wire

**Comment by Kurfursten** [comment]
You need absolute offset at zero, not relative offset. Not a bug.
