### ISSUE TITLE
Bus station brig

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10261]
(WEB REPORT BY: mrslippy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

the pAI in the brig starting area, the with with the 2 chargers, stormtrooper hardsuit mod and SPS stack can not be picked up.

> General description of the issue

pAI module can't be picked up, it can be draged and pointed to.

> What you expected to happen

Be able to pick up and activate the pAI become i need a buddy ;_;

> What actually happened

Can't do shit but drag it off the table.

> Steps to reproduce if possible

Go to the brig and look for the pAI that world spawned at round start.

**Comment by Probe1** [comment]
http://boards.4chan.org/vg/thread/143610307#p143646450

I knew it

**Comment by Kurfursten** [comment]
Yeah, the thing on the table is a mob instead of a paicard. Good catch.
