### ISSUE TITLE
Plasma windows on Bus station TEG aren't connected properly.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10260]
(WEB REPORT BY: jeroen52 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c697cd94938cbb5314cdf83fe6b34201b643f6d5 
> 
> General description of the issue
> The windows are supposed to be connected properly.
> 
> What you expected to happen
> The windows are supposed to be connected properly.
> 
> What actually happened
> Not connected.
> 
> Steps to reproduce if possible
> Go to TEG.

**Comment by Kurfursten** [comment]
What you're actually seeing is an extra directional window under the full window, but I'll remove it anyway for prettiness.
