### ISSUE TITLE
No map render for Bus Station, bug Pomf about it!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10267]
(WEB REPORT BY: zoffyx REMOTE: 172.93.109.202:7777)
No map render for Bus Station, bug Pomf about it!

**Comment by Probe1** [comment]
The map renderer is broken.  Beg n3x15 about it.

**Comment by AlphaBuffalo** [comment]
Why does shit keep breaking?

**Comment by PJB3005** [comment]
Uh, it's been broken for more than half a year.

**Comment by AlphaBuffalo** [comment]
Well, N3x fix yo shit

**Comment by ComicIronic** [comment]
rip Eggman

**Comment by 9600bauds** [comment]
dead
