### ISSUE TITLE
A sophisticated discussion about the presence of zoos in space station maintenance zones

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10270]
I would like to discuss with you all my good friends the strange presence of animal holding cells in the midst of station maintenance. As we all know, chaps, it is illogical to keep a large amount of animals fed for no reason, specially in the midst of a science-oriented space station with no particular leanings towards biological experimentation involving animals. Knowing this to be true for the "Bus station" format, it certainly does generate a level of wonder to the ma, as the presence of a unexplained zoo within the station maintenance tunnels begs us a complex question which most of our Nanotrasen or Central Command officials probably can't or will be unable to reply, but we shall ask it regardless for the purposes of sating our curiosity.

**WHY THE FUCK IS THERE A ZOO IN BUS MAINT?**
-t, Dr. Mad

**Comment by TheFriggenSawbones** [comment]
because it's cool and fun

**Comment by Kurfursten** [comment]
The airlocks say "animal testing"

Maybe it was abandoned because no one wanted that science job, as you said.

Deepest lore

**Comment by Jeroen52** [comment]
I should visit the zoo, I have seen it through a wall I think.

**Comment by AutismSpider** [comment]
Zoo has three crabs cow monkey and snake.

Crabs are the best part about it

**Comment by Kurfursten** [comment]
also a lizard

**Comment by Kurfursten** [comment]
So is there further need for discussion on this?

To help clarify the status as animal testing further I have added a cage to the zoo. I am sure this will be used by responsible scientists for research and not assistants to show off their favorite pet.

**Comment by Imagebard** [comment]
>A cage

With the new addition of a device to grief people, the room now has true meaning and purpose.
