### ISSUE TITLE
Discussion: Unsim the Taxis on Bus

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10273]
There's no way the Taxis will EVER retain their air. It's an impossibility. But we CAN have a taxi experience that doesn't suck.

A compromise is to unsim them so they don't automatically pop lungs. Let's talk about it.

**Comment by kol1th** [comment]
how did taxi station do it? Because that shit's annoying. Opened a door and nearly bled out.

**Comment by ComicIronic** [comment]
> There's no way the Taxis will EVER retain their air

Why?
People just need to open and close the doors properly.
Better yet, if you insist on handholding, give both the Taxi and the docking point double airlocks with faster timing.

**Comment by ihadtoregisterforthis** [comment]
Another issue suggests that the shuttle heaters or thrusters aren't airtight.
#10236

**Comment by 9600bauds** [comment]
Look at how the salvage shuttle does it

**Comment by Kurfursten** [comment]
@ComicIronic The docking point already IS a double airlock with faster timing. Adding the extra airlock layer to the Taxi would be as below

@9600bauds But the salvage shuttle is much bigger than a taxi. Replicating that would mean doubling the size of the taxis and forcing people to walk through 4 airlocks every time

**Comment by 9600bauds** [comment]
I mean how it has windows on the back

**Comment by ComicIronic** [comment]
Are you having the Taxis go through hyperspace? When are their doors even exposed to space?

**Comment by invoid9** [comment]
The taxis lose pressure constantly, though. I don't know if it's significant, but the propulsion tiles all have pretty much 0 pressure as opposed to normal pressure on all the wall tiles. Is it possible that the air is just leaking out of the propulsion shit? The middle propulsion tile also is different to the other 2 in that it's at -270 C.

**Comment by Probe1** [comment]
just put plating under the propulsion theres probably no need to unsimulate them.

**Comment by AlphaBuffalo** [comment]
Are the windows unanchored? And what about unsim the plating under the propulsion, would that stop air from leaking?

**Comment by ghost** [comment]
Just put some rwindows between the door and the engines.

Problem solved.
