### ISSUE TITLE
Make Hotkeys-Help link you to http://ss13.moe/wiki/index.php/Shortcuts

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10271]
At the end or something at least

**Comment by Probe1** [comment]
fuck son it would have taken you as much time to do this as it would have to open github and post hte issue

**Comment by 9600bauds** [comment]
demonstrably false

**Comment by Probe1** [comment]
It took me slightly longer because I was searching for it in vgstation/code instead of vgstation/interface
