### ISSUE TITLE
Vampires lose X-ray after cloning.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10279]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision cc1cc5611e1f64ffd0cae32f2738f2dc3f187896 
> 
> General description of the issue
> Title
> 
> What you expected to happen
> Come out of cloning pod with X-ray vision
> 
> What actually happened
> Normal boring vision, don't think I even had thermals.
> 
> Steps to reproduce if possible
> Become a vamp, suck until you get X-ray, die and get cloned.

**Comment by Probe1** [comment]
@Allspice did you keep your usable blood?

**Comment by Killette2** [comment]
I don't think you need usable blood to have passive abilities.

Also there's a lot of fucked things with vampires when they get powers through genetics.

**Comment by ComicIronic** [comment]
Are vamps even meant to be clone able?

**Comment by Shadowmech88** [comment]
Why shouldn't they be?

**Comment by Probe1** [comment]
They are undead.

Anyway I asked about the usable blood because I'm really on the fence about it.  It seems like an intended working as

**Comment by Shadowmech88** [comment]
When an undead dies, is it dead again? Dead things can be cloned.

**Comment by Allspice** [comment]
I was at like 250/1300 without X-ray after I was cloned, and before I was at 250/1300 with X-ray.

**Comment by ShiftyRail** [comment]
I was told this wasn't reproducable
