### ISSUE TITLE
Bus Station incomplete power grid

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10289]
#### Description of issue

MedSil has an incomplete power grid, with a wire missing at this location. Managed to confirm it in 3 rounds now.

![Missing Wire](http://i.imgur.com/9akfJqN.png)

As has been mentioned previously, the taxis aren't airtight. I managed to fix that by adding glass where the doors meet the propulsion. Strangely enough, the top Bus only needs the outer engines covered, whereas the bottom bus requires the inner one covered too.

![fixing the buses](http://i.imgur.com/F2yd6fT.png)

The piping on SecSci is incomplete, with no actual pipe to arrivals/escape

![No pipe](http://i.imgur.com/Fx9JMUO.png)

I'll post more as I find em
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
fixed in next hotfix, thanks for reports
