### ISSUE TITLE
Windoors being weird

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10283]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> cc1cc5611e1f64ffd0cae32f2738f2dc3f187896
> 
> General description of the issue
> Windoors can't be bumped into anymore to open.
> Delivery chutes now grab stuff through windoors.
> 
> What you expected to happen
> To bump into a windoor and open it.
> To have my crates stack up against the windoor in box cargo.
> 
> What actually happened
> Bumped into a windoor and nothing happened.
> Crates went down the conveyor and got sucked into the delivery chute straight through the windoor
> 
> Steps to reproduce if possible
> Bump into a windoor.
> Stack up some crates at the conveyor belts in box's cargo loading dock and watch them get sucked in.

**Comment by Ephx1** [comment]
This is still present as of June 27.
Cargo packages go straight through that cargo chute that's usually closed off with a windoor.
However the packages are still picked up even with the door closed.

**Comment by 9600bauds** [comment]
I can bump into windoors just fine

**Comment by Ephx1** [comment]
Here's something to try then:
As a MoMMI, move through the research front counter on Box. You can go bump into the windoors going into the room, but not when trying to leave.

**Comment by PJB3005** [comment]
Yep fucking BYOND.

**Comment by clusterfack** [comment]
Duplicate
