### ISSUE TITLE
Cult harvesters can queue up rune scribing

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#10286]
#### Description of issue

When a cult harvester presses Scribe a Rune, the menu appears and the spell starts recharging. The spell can finish recharging and a second scribe menu can be queued up.
#### Difference between expected and actual behavior

Harvesters can circumvent the spell cooldown as long as they have some time without fighting.
#### Steps to reproduce

Be a harvester
Click Scribe a Rune
Wait until cooldown has finished
Click Scribe a Rune
Scribe a rune
#### Specific information for locating

Scribe a Rune spell: `/spell/rune_write`
#### Length of time in which bug has been known to occur

No clue, fucking ages
#### Server revision

cc1cc5611e1f64ffd0cae32f2738f2dc3f187896
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DeityLink** [comment]
Harvesters were removed and will probably not write runes again if/when they get re-added. This ability was to make up for cultists being force-turned into harvesters.

**Comment by Kammerjunk** [comment]
fall 2016, sood
you promised
