### ISSUE TITLE
Bus Station doesn't have a PDA map app map

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10287]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> cc1cc5611e1f64ffd0cae32f2738f2dc3f187896
> 
> General description of the issue
> There's no map for the PDA map app you can buy from the PDA terminals.
> 
> What you expected to happen
> Buy PDA app -> Figure out where the fuck I am
> 
> What actually happened
> No map.
> http://puu.sh/p9c2T/7b7390e051.png
> 
> Steps to reproduce if possible
> Go on Bus, buy a map app.

**Comment by DamianX** [comment]
I think we can close this

**Comment by SonixApache** [comment]
m-muh bus
