### ISSUE TITLE
I feel like MoMMI should have a light replacer with infinite lights 

### ISSUE THREAD

**Issue by timmothy-lit** [d3athrow/vgstation13#10299]
I feel like MoMMI should have a light replacer with infinite lights so the station is better kept. Thats all

**Comment by Exxion** [comment]
Its glass storage is recharged by the borg chargers, and it can make lights out of glass
And it stores twice as much glass as the handheld light replacer, and uses half as much glass to fabricate lights, and can make high-efficiency lights
Infinite lights... isn't really possible without making the MoMMI light replacer work entirely differently from regular ones, but it could be made to be even more efficient and it could be given buttons to fabricate multiple lights at once
Actually, the latter should be done anyway
Or is it already that way? I forget.

**Comment by kol1th** [comment]
Don't you make light tubes and light bulbs at an autolathe?

**Comment by Exxion** [comment]
Yes. Or with a light replacer. Haven't you ever tried clicking it in your hand?

**Comment by ComicIronic** [comment]
Do not want to give more convenience to the autism spiders.

**Comment by clusterfack** [comment]
Light replacers became really fucking annoying to use after the whole box shit was added to it

**Comment by AutismSpider** [comment]
To much of pain you have to stick like three boxs in it so its not shit.

Jain borg has light replacer any way

**Comment by Exxion** [comment]
@clusterfack But they can still be used almost exactly as they were before
You don't have to take the boxes out or anything

**Comment by clusterfack** [comment]
I remember having significant trouble using them.

If I recall correctly I think the problem I was facing was that the glass I was putting in to create light tubes was being crowded out by storage of light bulbs. But it has been awhile. it was annoying as fuck at the time.

**Comment by Exxion** [comment]
That has at no point been a possible problem to run into

**Comment by clusterfack** [comment]
Like I said it's been a long time so my memory of why it was so shit isn't perfect

**Comment by Exxion** [comment]
My only thought would be that all the light bulbs took up space you wanted for light tubes, but that's what the dump to waste button is for.

**Comment by Kurfursten** [comment]
The boxes are a little annoying to use, but it's much nicer to not have to pick up 50 bulbs off the ground anymore

**Comment by ghost** [comment]
All I wish for is that each department had access to basic janitorial supplies like spare lights, cleaner sprays and soap

Right now you have to fight over the cleaner sprays in Medbay and the one spare lights box in the Escape Hallway Storage

**Comment by jknpj** [comment]
I actually didn't give them one

**Comment by west3436** [comment]
No interest in implementing this - MoMMI's can recharge capacity in a cyborg recharger.
