### ISSUE TITLE
Holopad communication really unintuitive

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10297]
You're apparently supposed to use :h to talk through your holopad avatar, but there's nothing in-game to inform you of this.
This resulted in an AI thinking they were talking out of their holopad avatar, but it was actually just the AI core talking into it's core. It also was an AI triumvirate round, so the intercom wasn't activated and nobody was hearing the AI, unbeknownst to it.
This is, put shortly, pretty awful. Since AIs rarely use a holopad, the intuitive solution would be to have normal talk redirected to holopad talk while you're using one. You can still talk over the radio via ; or :[deptkey]
Other issues: Holograms don't have a speech bubble when talking
Ctrl+arrow key doesn't rotate your hologram sprite, neither does clicking, makes facing people kind of awkward

**Comment by clusterfack** [comment]
In holo-avatar form they should definitely speak out of the holopad they are attached to. I'm not sure why they wouldn't.

**Comment by 9600bauds** [comment]
Also, would it be possible to attach a hearer to it or something so it can see attack text and such?

**Comment by clusterfack** [comment]
I already made it so holopads can do this, check the code in visible message for this

**Comment by 9600bauds** [comment]
Seemed to be broken sadly

**Comment by clusterfack** [comment]
The visible message code should definitely be working
```
		else if(istype(hearer.attached, /obj/machinery/hologram/holopad))
			var/obj/machinery/hologram/holopad/holo = hearer.attached
			if(holo.master)
				holo.master.show_message( message, 1, blind_message, 2)
```

But I can't guarantee you that the code actually uses visible message, that's where you should look. Lots of old code still loops through hearers manually and then does show_message.

**Comment by clusterfack** [comment]
If someone wanted to refer that out that would be really great

**Comment by clusterfack** [comment]
*regex

**Comment by 9600bauds** [comment]
What if you attached a mob/hearer to the hologram to have a more generalized solution? Or is that not doable?

**Comment by clusterfack** [comment]
I mean I hadn't thought of it before but if you modify both show_message and visible_message for the virtualhearer to do attached.show_message(args), attached.visible_message(args), that -may- do the trick. But that's just an off the cuff idea.

**Comment by kol1th** [comment]
I think it's fine as is, but it needs to be the lucidia font instead of regular font. Muh immulsion.

**Comment by Ephx1** [comment]
I'm pretty sure upon AI start up it flat out says "use :h to talk out of holopads", otherwise I don't know how the hell I learned that
