### ISSUE TITLE
IAA doesn't really need maint access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10291]
(WEB REPORT BY: durgen REMOTE: 172.93.109.202:7777)
now that IAA has bridge access, I think maint access could be taken away without causing too much of a headache.

It's pretty hard to blacktide without maint access, so it might lead to people playing IAA more seriously.

Maybe losing maint could be compensated by throwing IAA another bone, kind of like how it already has basic medbay access.
Basic science maybe? It would be useful for inspections

**Comment by Imagebard** [comment]
>Inspector in a science station
Can't enter science

Ayy lmao

**Comment by kol1th** [comment]
Basic science access would be pretty gr8 in exchange for maint.
