### ISSUE TITLE
Heist round end score screen / score screen in general is so fucked up at this point it doesn't even say the mode was heist

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10295]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/8550416/15638812/28003ac0-25f2-11e6-9b8a-f0b59bb4d6eb.png)
#### Difference between expected and actual behavior

This but with some vox and objectives

**Comment by kol1th** [comment]
The game mode should be a random event, and not a full game mode. TO BE HONEST.

**Comment by PJB3005** [comment]
Yep, remove heist.

**Comment by MusgardTiger** [comment]
+1 remove heist

**Comment by Probe1** [comment]
>score screen is fucked up for almost every game mode
 >lets remove heist that will fix it

:eggplant:

**Comment by ComicIronic** [comment]
> remove heist
> go from only antag vox to no antag vox

REMOVE BIRD BRAINS
