### ISSUE TITLE
RPG is worthless now

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#10294]
I don't know when this happened, but someone nerfed the RPG into the fucking ground. It now creates a one-tile-sized hole and very slight damage to the tile it hits. It can't even be used to breach a reinforced window, as it will break one window and the grille, and only crack the interior glass.

Two RPG shots didn't even destroy a machine in R&D. Who the fuck did this, and why? The RPG used to be one of the most fun tools available to nuke ops, and now it's just another worthless piece of shit that nobody's ever going to use.

**Comment by kol1th** [comment]
Sounds like fireball.

**Comment by Hoshi-chan** [comment]
Do fireballs also hit tables instead of going over them? Because I killed myself shooting over a table, expecting it to behave like a bullet.

**Comment by kol1th** [comment]
Yeah pretty sure they do. What if it's the same exact code?

**Comment by Exxion** [comment]
It isn't. Fireballs are dumbfire-only, I believe.

**Comment by Imagebard** [comment]
I have mixed feelings about this.
On one side, a RPG should be stronger and there is only a limited supply.
On the other side, they're fucking rocket launchers available round start in a crate without even paying TC for them AND I hate nuclear operatives that rush to the shuttle to get the RPG before the mission briefing even finishes because they're always the dumbest ones.

**Comment by Hoshi-chan** [comment]
Everyone shouldn't be punished for the stupidity of a few. If the dumb guy wastes the RPG, at least he'll cause damage with it.

**Comment by ghost** [comment]
The damage is a result of how Ex_act interacts with everything. Same reason the marauder rocket launchers are shit and you can shoot 30 fireballs to get through a girder

**Comment by ghost** [comment]
RPG was balanced for old explosions. Now it's going to need a lot more punch

I don't have the exact values on hand, but seeing how it has good changes of severely damaging a modern tank and cause serious AoE damage, it likely has a bigger medium and low blast radius
