### ISSUE TITLE
Mechanics room

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10292]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
Needs to spawn with gadget bags

**Comment by kol1th** [comment]
Once again, specify map. But I'll assume bus station. tag pls

**Comment by Kurfursten** [comment]
This can't be right, it does spawn with 2

Untag Bus or close

**Comment by DamianX** [comment]
I think we can close this
