### ISSUE TITLE
Spider punch bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10298]
(WEB REPORT BY: anacondawarriorsupercommando REMOTE: 172.93.109.202:7777)

> 324e6c8f86b420cc53eae364edfd2af6c85097f9 
> 
> Spiders are unable to be punched even while hulked
> 
> Spiders can be punched and damaged appropriately wether hulked or not
> 
> Spiders are completely unable to be punched
> 
> Steps to reproduce if possible

**Comment by Shadowmech88** [comment]
A lot of non-carbon mobs have no punch interaction. Borgs can't be punched either, despite the fact that hulks are able to punch _mechs_ into scrap.

**Comment by Shadowmech88** [comment]
Tested locally, I was able to punch a spider while both hulked and non-hulked.
