### ISSUE TITLE
Soap is overpowered.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10309]
Okay, think about it for a second.

Both with a space cleaner spray and the lynch-attracting mop & bucket require refills to work.

But soap exists.

Soap cleans everything, yet it's 100% infinite.

**Comment by Shadowmech88** [comment]
Yes, it's objectively the best.
I don't think that's a problem.

In spite of soap's effectiveness, I still see people using space cleaner and/or the mop for RP reasons.

**Comment by SysadminJeroen** [comment]
You could easily steal soap, space cleaner isn't that easy to steal, and especially in a spraybottle form.
Besides that, lube hurts, slides you further and stuns you longer.

**Comment by Kurfursten** [comment]
We talked about this before, and the github issue is probably still around

Last time people suggested:

> Soap has limited uses
> Soap is given a cleaning time like on other servers
> Who cares about balance for janitor

**Comment by PJB3005** [comment]
> I still see people using space cleaner and/or the mop for RP reasons.

I think it's more they don't realize where to powergame soap.

**Comment by ghost** [comment]
Soap spawns in the janitors closet on most maps.

**Comment by PJB3005** [comment]
Doesn't on box.

**Comment by ghost** [comment]
![soaponbox](https://cloud.githubusercontent.com/assets/9110500/15655949/2643f048-269a-11e6-92d5-ca770c49fa4f.png)

![soaponmeta](https://cloud.githubusercontent.com/assets/9110500/15655976/6cf21a7e-269a-11e6-8508-36def6e86c24.PNG)

![soapondeff](https://cloud.githubusercontent.com/assets/9110500/15656001/9aa46d32-269a-11e6-9ea9-4292fd158ec4.PNG)

![soaponbus](https://cloud.githubusercontent.com/assets/9110500/15656068/4b809ee6-269b-11e6-8c26-52012afebd7a.PNG)

**Comment by SonixApache** [comment]
soap is fine

**Comment by SacredAtom** [comment]
I agree soap is fine as is

**Comment by 9600bauds** [comment]
> who cares about balance for janitor

Who cares about uncleaned messes?
Janitor is a whole job that is in itself made mostly irrelevant due to soap, and most of the content of the job itself is 100% pointless compared to soap.
The mop being useless is a CRIME AGAINST HUMANITY
If the soap's cleaning power is nerfed, what would we lose? There'd be a few more uncleaned messes and both the Janitor and Chemistry would become more useful to the common people, and for fluff/non-powergame purposes at that. I see two pros and no cons there.

**Comment by PJB3005** [comment]
@Skullyton I could've sworn there was no soap in the janitor's closet on box.

**Comment by ihadtoregisterforthis** [comment]
Soap is okay

**Comment by icantthinkofanameritenow** [comment]
Wait, soap is used for cleaning? I thought its main use was to slip people when you put it on the ground.

**Comment by Imagebard** [comment]
Soap is basically cleaning for babies, christ. Just remove it or something.

**Comment by Zth--** [comment]
Make it need water, with a chance of slipping from your hands. It gets dry after a while and it's useless

**Comment by Megamaw** [comment]
Maybe you need water and a bit of time to lather it up? And then you get like ten seconds of using it.

Soap is useful for getting messes off of walls where the mop/janicart won't reach. Which is nice.

Ultimately, as a janitor main, I think the mop needs a straight up buff of some sort.

**Comment by 9600bauds** [comment]
Make the mop instant with a 0.8 sec cooldown
Does not become too fast for cleaning because you can no longer clean every tile around you at the same time
Lets you ninjaslip people

**Comment by Probe1** [comment]
@PJB3005  I GUESS
@Shadowmech88 "RP reasons" :laughing: 

Half the reason you play janitor is to slip people and point at the wet floor signs.

**Comment by Shadowmech88** [comment]
Slipping people and pointing at the signs is still _technically_ roleplaying as a janitor.

**Comment by ghost** [comment]
Here's a thing we could do : 
- Soap has limited uses, most likely a few dozen so you can't keep your magic beacon of cleaning around forever
- Soap has a short delay so you actually have to scrub the stuff you clean, just like the mop
- You can make soap via Chemistry. A recipe I'd suggest since it's about correct is Olive Oil (needs to be added, but we should really have it at this point) + Lye (NaOH, that's Sodium + Oxygen + Hydrogen) + Glycerine (Corn)

**Comment by Probe1** [comment]
do we even have olives

any fat will do

:+1: :+1: :+1: to adding lye, a highly caustic substance.

**Comment by ghost** [comment]
Eh, seemed fine. Soap you had to click for every splotch of blood whereas the mop was whole tile and spray was max range.

**Comment by Probe1** [comment]
yeah thats pmuch how i feel about it but if you add a recipe to make soap and it has a healthy amount of uses 

and if you really want to tickle my bones add multiple icon states showing usage..  then its whatever sure

**Comment by FudgePucker** [comment]
@SarahJohnson489 
This.

**Comment by Arthurdentist** [comment]
not everything needs to be balanced.

Soap is fine and its existence has never stopped people from using other cleaning methods.

**Comment by 9600bauds** [comment]
It has definitely killed use of the mop besides griffjanitor

**Comment by Imagebard** [comment]
Wait up. 
This issue is a elaborate joke, right?

**Comment by Kurfursten** [comment]
@dylanstrategie That list is funnier if you see post number 4 in this issue

**Comment by PJB3005** [comment]
@Imagebard nope I'm serious.

**Comment by Imagebard** [comment]
Okay in which case, I would like to comment that my request to remove soap was just a joke.

**Comment by FudgePucker** [comment]
Yea soap is what killed the mop, not the upgraded janicart

**Comment by 9600bauds** [comment]
![reginald](https://cloud.githubusercontent.com/assets/6526157/15685214/246e5518-2741-11e6-9c7a-a5f83b31fc11.png)

**Comment by Imagebard** [comment]
The website in the computer on that image is edited right.
Its edited right.
I mean there's no way after all.

**Comment by Intigracy** [comment]
Can you currently acquire more soap outside of being an antagonist?

**Comment by Shadowmech88** [comment]
Doesn't the mining vendor contain bars of soap?

**Comment by 9600bauds** [comment]
Biogenerator too

**Comment by Megamaw** [comment]
okay, i just remembered how many clicks it takes to scrub blood out with soap

It definitely does not need a nerf.

The space cleaner, however, is used in any situation the mop could be useful, and you have an incredible amount of it.

Again, I say the mop just needs to be buffed enough to have it's own niche.

**Comment by Intigracy** [comment]
Mops could wet in a 3x3 area from where you click.

**Comment by ihadtoregisterforthis** [comment]
Mops are fast to use, can be used on many tiles at a time, and if I remember correctly when whipping someone they apply whatever chemical they have.

**Comment by Megamaw** [comment]
Fast to use? What kind of magic pixie land are you living in?

**Comment by Imagebard** [comment]
>and if I remember correctly when whipping someone they apply whatever chemical they have.

Aaaaand suddenly everyone is suspicious of the janitor using a mop because 1 its useless compared to other options and 2 it can be used for antag shit

**Comment by SonixApache** [comment]
If you want to nerf soap so badly just add a tiny delay before you can scrub another object.
