### ISSUE TITLE
Add this as a vault

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10303]
Note to self.  Will need to think of a way to make docking ports usable by multiple ships in the future.

![1464605829478](https://cloud.githubusercontent.com/assets/8550416/15650237/18c7da74-2645-11e6-8784-d51be31f1154.png)
![1464606557933](https://cloud.githubusercontent.com/assets/8550416/15650238/199aabca-2645-11e6-948f-2ce6afec39a0.png)

**Comment by Shadowmech88** [comment]
What loot do you plan on it having?

**Comment by Probe1** [comment]
Someone wanted it for a vox tradeship (which its too nice for).  Ultimately I'd like to see it as an alternative salvage ship but that'd take some significant work with docking ports.

**Comment by Shadowmech88** [comment]
It looks like you've left off the ship's fore port corner in the design planning, why? Could have a little medical room there.

**Comment by Probe1** [comment]
Just took what the thread asked for.  I was nearly done with it but dm decided to crash and didn't save.

Easy little ship.  3x3 compartments wouldn't work so well in byond.  With machines and dense tiles it'd have to be 5x5.

![dreammaker_2016-05-30_08-21-50](https://cloud.githubusercontent.com/assets/8550416/15650723/ad796fea-2648-11e6-9425-3879a4c4fc46.png)

**Comment by unid15** [comment]
@Probe1 docking ports can already be shared by multiple shuttles, as long as they don't have transit. If they have transit areas, they may get stuck in then

**Comment by Probe1** [comment]
@unid15 They definitely get stuck and get stuck bad.  That's what I'm referring to.

The best would be having a shuttle check an adjacent area x tiles away and move there if its space was occupied.  But an acceptable one would just be giving players a message that their port is occupied and the ability to change the destination after entering transit

**Comment by icantthinkofanameritenow** [comment]
Why not just replace the current salvage shuttle with this for some of the maps? It would probably be much easier to do than try to fix all the oldcode in shuttles.

**Comment by ihadtoregisterforthis** [comment]
Shuttles have newcode. But different shuttles for each map would be great anyways.

**Comment by Shadowmech88** [comment]
Could give docking ports a var that references the docked ship's console and set it as soon as the ship enters hyperspace.
That way, a second ship would be able to see that the docking port is occupied even if the first isn't there yet, so it won't enter hyperspace at all.

**Comment by unid15** [comment]
That's a great idea

**Comment by MercuryDoll** [comment]
![imy shitty attempt](https://a.pomf.cat/kvkidk.png)

**Comment by Shadowmech88** [comment]
Doesn't it make more sense for the ship console to be towards the front of the cockpit instead of the back?
Looks nice otherwise.

**Comment by MercuryDoll** [comment]
It was a very quick mockup that was so low on effort that i mindlessly closed DM without saving. I was mostly just tooling about to prove that the design is roughly possible without reaching "Vault" mass.

**Comment by ghost** [comment]
Think I got a rough frame done, following the layout of the ship very literally

![rockshipframework](https://cloud.githubusercontent.com/assets/9110500/15710163/9fd98d98-2800-11e6-846e-9aececb09c14.PNG)

**Comment by Probe1** [comment]
needs a bluespace artillery cannon

**Comment by ghost** [comment]
Will be adding that, shame it just makes explosion in an area, rather than actually fires a shot forwards from itself

**Comment by Shadowmech88** [comment]
You could always code a new piece of machinery and a matching projectile, so that it _does_ fire a shot forward.

**Comment by MercuryDoll** [comment]
Considering how fucked up the sprites for the bluespace artillery is (3x12 or so sprites), that's probably the best idea. If you want, i can "assemble" the current sprites and give you one bigger, updated sprite. Or at least fewer ones that are easier to handle.
