### ISSUE TITLE
Blob MMI consumption leads to nullspace

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10307]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7c99cfa3718f8013866e33d749edaded585b1b
> 
> General description of the issue
> Died as a borg to a blob. Ghosted when I took critical damage. Tried to re-enter corpse after it expanded over my MMI, was sent to nullspace.
> 
> What you expected to happen
> Get killed, ghost, get destroyed, hit re-enter, see "You have no body to return to!"
> 
> What actually happened
> Get killed, ghost, get destroyed, hit re-enter,black screen.
> 
> Steps to reproduce if possible
> Spawn a blob node, sit next to it as a borg, let it overcome you, ghost before it destroys you, re-enter corpse after it destroys your MMI.

**Comment by Shadowmech88** [comment]
Sounds like the `Destroy()` of borg bodies and/or MMIs needs to null out the `current` var of the mind associated with them.
Or it needs to null out its own mind var, I can't remember how the re-enter corpse verb works at the moment.

**Comment by clusterfack** [comment]
It already should
