### ISSUE TITLE
Custom dishes revert their name upon (partial) consumption

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10304]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7c99cfa3718f8013866e33d749edaded585b1b
> 
> General description of the issue
> A dish named with a pen reverts to it's original name when consumed.
> 
> What you expected to happen
> X bites some of Super Pizza.
> 
> What actually happened
> X bites some of the grilled bear meat, deep fried monkey meat, cheese wedge, grilled xenomeat and Burned mess pan pizza.
> 
> Steps to reproduce if possible
> Name a dish, then have a bite.

**Comment by Eneocho** [comment]
they keep the new name now
