### ISSUE TITLE
magivend missing things

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10313]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> the magivend is missing the necromancer hat
> 
> What you expected to happen
> to have the hat
> 
> What actually happened
> no hat
> 
> Steps to reproduce if possible
> get a magivend
> find out it doesnt have the necromancer hat

**Comment by Imagebard** [comment]
Looking at this post in the issue tracker, there was 1 reply. Enter it, no replies. Go back to issue tracker, the reply is gone.

I'm watching you, sneaky poster.

**Comment by Konater** [comment]
oops
