### ISSUE TITLE
Changeling's Regenerative Stasis doesn't always regenerate.

### ISSUE THREAD

**Issue by The-Albinobigfoot** [d3athrow/vgstation13#10316]
#### Description of issue

After collapsing and nearing crit to (what I assume was) radiation from a monkey-human that I was succing, I used my stasis at maximum chems and waited. Like the unrobust idiot I am, I had done it directly in front of a camera, so as a result, the AI sicked the sec team on my corpse. While they were investigating the scene my stasis became ready to use, obviously I put it off for a while; after some time, sec decapitated my victim's corpse and left. I then used the return to life verb after waiting a bit only to be greeted with: "We require at least 20 units of chemicals to do that!", when I had my chems maxed out.
I had taken the form of Isaac Baker when the bug occurred.
#### Difference between expected and actual behavior

Regenerating and getting greentext vs. Not regenerating, and getting redtext.
#### Steps to reproduce
- Get sent to 10~ health or so (enough to collapse).
- Use regenerative stasis.
- Wait a minute or two after it comes online
- Use 'Return to Life'.
- Hopefully you recreate the bug.
#### Specific information for locating

We require at least 20 units of chemicals to do that!
#### Length of time in which bug has been known to occur

Just started playing on /vg/, though it is worth mentioning that I successfully used the ability earlier in the round. 
#### Server revision

db7c99cfa3718f8013866e33d749edaded585b1b
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Should have asked an admin to inspect your vars and see how many chems you actually had. Could be a HUD problem.

**Comment by The-Albinobigfoot** [comment]
I did ahelp it, but received no response.
