### ISSUE TITLE
For some reason, Vox dartguns don't fire when clicking on a turf, only on an object or mob, which really messes with your ability to shoot people

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10315]
Usually you click BEHIND people, and I can see how it would be very jarring that you do this in a combat situation and nothing happens
Also, as an unrelated request, they should start with their chemicals already mixing by default

**Comment by SkowronX** [comment]
Same fire code as syringe guns.

**Comment by 9600bauds** [comment]
No, I tested syringe guns and they don't do this

**Comment by Shadowmech88** [comment]
Are the dart guns a child of an existing gun, or their own gun?

Make sure that the dart gun's afterattack() calls Fire(), and that it doesn't have some stupid ismob() exception.

**Comment by SkowronX** [comment]
@9600bauds old syringe gun firing code which didn't fire unless you clicked a mob's sprite
