### ISSUE TITLE
Emagging shit doesn't leave prints and I can think of nothing worse for Detectives

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10318]
Emags are one of the most versatile and stealthy items a traitor can get.

Can't we give them regular fingerprint stuff when a user emags something?

**Comment by Imagebard** [comment]
Get this the Balance tag because the Christ is in need of coming down.

**Comment by AutismSpider** [comment]
Why can't we up the cost of the emag or put egg mans emag code back in?

**Comment by Imagebard** [comment]
I tried convincing everyone the emag was OP before and nothing came out of it because people are so attached to it.

Besides this is about a fingerprint bug. 
_Saying that, I imagine I might be retarded. Is the balance label really applicable?_

**Comment by Kurfursten** [comment]
It's not really a bug that when you use something else on an object (like a rod on a door) only the rod gets your prints

That being said I have no preference regarding this issue

**Comment by 9600bauds** [comment]
Fun fact, welding something doesn't leave fingerprints either, not even hiddenprints
Even the admins can't tell who did it

**Comment by Imagebard** [comment]
Why the fuck are you sharing those fun facts when you know they will be only used for evil

**Comment by 9600bauds** [comment]
Because they're fun

**Comment by ihadtoregisterforthis** [comment]
_You can't really dust for vomit_

![spinal tap](https://cloud.githubusercontent.com/assets/13305885/15686283/f454918a-2745-11e6-9b47-07242e53dc79.jpg)

**Comment by clusterfack** [comment]
Maybe soap should only clean up certain kinds of things?

I don't know how its going to clean up a puddle of blood.

**Comment by 9600bauds** [comment]
What fresh hell happened here, did the streams cross?

**Comment by Probe1** [comment]
Zuul says we make emags leave prints

**Comment by Imagebard** [comment]
They emagged the issue, panic.

**Comment by Probe1** [comment]
guys what if we make fingerprints emaggable

**Comment by Probe1** [comment]
(they explode when emagged)

**Comment by Kurfursten** [comment]
![explosive runes](https://cloud.githubusercontent.com/assets/9782036/15688470/df0b621e-273f-11e6-81fa-1cf1fc98d7b6.jpg)

**Comment by Imagebard** [comment]
Question
Does swiping a normal ID on a airlock give it your fingerprints?

**Comment by Probe1** [comment]
Prob not

**Comment by Intigracy** [comment]
Tools should ALWAYS leave hidden prints when used on something, and should at the least leave fibers.
