### ISSUE TITLE
Design a palette for sprites to use.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10311]
SS13 has horribly inconsistent art. IMO it would look much much better if sprites were restricted to a strict palette. Even if not all sprites were refactored immediately it'd be a step in the right direction.

**Comment by 9600bauds** [comment]
I think inconsistencies are in perspective or in sprite quality, the palette is probably the least clashing element

**Comment by Shadowmech88** [comment]
What do you suggest for the pallette? "Everything is dark and gloomy" and "everything is bright and happy" are both unappealing options to me.

Real life has a variety of colors. I don't think that removing variety would make it look _better_, even if it does look more cohesive.

**Comment by PJB3005** [comment]
@Shadowmech88 I don't mean it like that, I mean it like this:

![](https://web.archive.org/web/20151003151957im_/http://spacestation13.com/wp-content/uploads/2013/12/ZXLo112.png)

Left: consistent palette, right: inconsistent palette.

https://web.archive.org/web/20151022234656/http://spacestation13.com/2013/12/december-26-development-update/

**Comment by ComicIronic** [comment]
> someone downboated this

It's a good idea, though.
We need to think about having some sort of consistent art direction for the future <s>as well as a resprite of walls and airlocks a la goon</s>

**Comment by Shadowmech88** [comment]
I actually like our ambiguous-perspective walls more than Goon's.

**Comment by Imagebard** [comment]
Excuse me, I thought I understood what this was about but then PJB's image confused me.
Basically, we're going to grab a set of colors and only use those when spiriting, right?

**Comment by ihadtoregisterforthis** [comment]
Theoretically, yes

**Comment by Imagebard** [comment]
>Iamgoofball :-1: 'd this

That's worth a :+1:
No you can't change your vote, too late now.

**Comment by Lorkhatosh** [comment]
Lifeweb does something similar, and say what you want but visually lifeweb delivers atmosphere that it wants to deliver.

If we want the same we should go for certain default lighting to be maybe colored, like slightly tinted blueish or greenish and of course a color palette.

**Comment by NigglyWiggly** [comment]
I always set up a palette whenever I'm doin' sprites, and I'm sure the rest of spess would look better if everything was restricted to a palette as well, but there's the issue of deciding what that palette would be.
We don't actually have much of a 'style' at all, and as much as I'd like for us to, I'm sort of glad we don't have the restrictions of that, even if that means we miss out on the aesthetics.
So I dunno, I'm pretty neutral on this, it's a nice idea, but I don't really know if it'll work out.

**Comment by Lorkhatosh** [comment]
How about this, we get better lighting (goon lighting) and tint it a bit towards a certain color.
That will give at least some aesthetics unity to the station.

**Comment by Imagebard** [comment]
>Tinted lights

I have bad feelings about this.

**Comment by Lorkhatosh** [comment]
I feel that tint/saturation/some form of visual effect can enchance the style a bit so that all sprites don't look so bland.
Of course it needs experimentation but generally lighting needs to be improved anyway.

**Comment by ghost** [comment]
Directions for all those spriters we have that don't exist ? Sure

Here's a few bulletpoints we should bash down into their skull : 
- Black outlines are a huge no-no. If you're going to outline, at least take ten seconds to mix a darker shade of whatever color it is surrounding
- Minimal to no shading on the items, it just ends up looking terrible
- I will slap the next person who makes different colors with a variation of 1 RGB (so for example (21, 21, 21), then (22, 22, 22)). Our sprites are nowhere close to big enough to justify this shit, it doesn't make the sprite look any better and makes maintenance dreadful. 5 RGB steps are likely the absolute minimum

Also, one of these days we should move to 64p sprites and use Transform to compress them. It would make our art assets heavier, but the art quality would go up substantially (compare old Cult mobs and new Cult mobs for an example)

**Comment by MercuryDoll** [comment]
I kinda agree with Niggly on this. Yes, it would be great to have a uniform artstyle with unified color pallette, perspective, shading and all. But for that we'd need **dedicated spriters** that are willing to remake **all** the sprites we currently have **and** the sprites we're eventually going to add. Which we don't have, sprites are basically either tried to be made by whoever wants to implement a new object or whoever is willing to do that for them.
And dylan, i agree with two of those points. But [no shading](https://a.pomf.cat/xaovdh.png) is almost if not just as bad as pillowshading. People just need to learn how lighting works and do decent shading.

**Comment by Lorkhatosh** [comment]
Am I the only one who wishes that everything was double the size? I am working on aug limbs right now and there is such a small workplace to make something that actually looks neat, even other servers that have better looking augs like Paradise still look like shit because there is such a small workplace.

**Comment by ghost** [comment]
64x64 is certainly easier to work on, but supporting it fully is no small task

Even if we use basic tools like paint.net's Nearest Neighbour resize which allows to very quickly and cleanly turn 32p sprites into 64p and higher, we still need basic code infrastructure so that the 64p sprites show up properly in 32p tiles

**Comment by Lorkhatosh** [comment]
Why did 32x32 become a standard? It's so tiny.

**Comment by PJB3005** [comment]
Nah 32x32 is okay. BYOND defaults to it.

Its a good balance between "everybody can do it" and space.

**Comment by Lorkhatosh** [comment]
I slightly disagree. I think that 64x64 is still everyone can do it but it also has 

> if you want to do detailed shit on characters and limbs you can

added to that

**Comment by MercuryDoll** [comment]
Anecdotally i believe 32p sprites are just as hard if not harder to make as 64p ones, since you need to condense detail, trying to make the sprite depict what it needs with minimal pixels. Making 32p sprites look good is just a different kind of art. Sure, it's somewhat faster to whip up something _remotely resembling_ the item you want it to depict (aka placeholder sprites), but 64p gives a lot more freedom in regards to scale and detail, making it slightly easier to work with in my opinion.

![metroid sprite comparison](https://a.pomf.cat/jfwlaj.png)

**Comment by NigglyWiggly** [comment]
I sorta like 32x32 sprites
It makes it a bit more challenging to make them recognizable and that's part of the fun, at least for me.
64x64 would probably be better for detail and stuff though, I guess

**Comment by clusterfack** [comment]
Everyone uses 2x mode or stretch to fit anyway.

It would be rather trivial accounting for atoms that haven't been updated yet. We could put a transform() matrix in atom/New(). 

Though definitely all the base turf icons would need to be redone before this supposed 64x64 update.

**Comment by PJB3005** [comment]
![](http://i.imgur.com/6h9tt5u.png)

**Comment by Lorkhatosh** [comment]
wat? we moving to goon walls?

**Comment by PJB3005** [comment]
No I'm just showing a poll result.

**Comment by Lorkhatosh** [comment]
Well, goon walls are pretty great anyway, and fix up the strange perspective.

**Comment by Imagebard** [comment]
Goon walls look too thin and weird, I hate it.

**Comment by Imagebard** [comment]
>Yeah 12 votes

Shit

**Comment by ghost** [comment]
Goon walls are fine, will just take some getting used to and respriting our wall mounted items

We even have Goon windows and Goon airlocks to go with them already

**Comment by NigglyWiggly** [comment]
We're not doing goon walls.

**Comment by ComicIronic** [comment]
If we do perspective walls, we're spriting our own. Goon slanty walls look like hot shit.

**Comment by MercuryDoll** [comment]
Yeah, the concept is good but the sprites themselves could be done better.

> Goon slanty walls look like hot shit.

You mean the vertical walls being slanted? I assume this was done to account for wallmounted objects like fire alarms.
To be honest, the biggest issue with perspective walls will probably be wallmounted objects, especially ones on south walls.

**Comment by Shadowmech88** [comment]
From my vague memory of the one time I played on Gooncode just after it was leaked, I believe their solution to that is "don't have any wall-mounted objects on a room's south wall."

**Comment by ComicIronic** [comment]
Genius

**Comment by MercuryDoll** [comment]
That is pretty much what i thought they did when i had a look at their map. Kinda dumb and limiting on the mapping side of the game, but probably the best solution apart from doing [the oldschool topdown view](http://www.zeldadungeon.net/Zelda01/Walkthrough/02/017.png), which doesn't move us forward much.

**Comment by NigglyWiggly** [comment]
Reminder that our mineral walls all have perspective like that

**Comment by ghost** [comment]
Goon walls are 👌 and anyone who says otherwise is just too used to our old shitty ones.

**Comment by NigglyWiggly** [comment]
Maybe there's a reason you play a blind character

**Comment by MercuryDoll** [comment]
If the playerbase is willing to try perspective walls, i'm willing to try spriting them. But i need directions on how they would mostlikely be accepted. As i said, my biggest concern would be south-wall mounted objects which would look odd unless we go for oldschool zelda-style top-down walls.

**Comment by NigglyWiggly** [comment]
Go for zelda style if you're going to try em. Personally I say just don't bother, perspective is all kinds of fucked up and half our icons are from a pseudo top-down perspective while the other are from a straight-forward one

**Comment by PJB3005** [comment]
To revive this. The 64x initiative has sprouted TG to begin working on a consistent palette:

![](https://i.imgur.com/N7Gagv9.png)

I think we should follow their example.

**Comment by ComicIronic** [comment]
Put it in the Github wiki and let's make an issue tracking the sprites that have been converted.

**Comment by NigglyWiggly** [comment]
I can't wait to go over every single fucking sprite in the entire codebase and re-do them all in a palette and a bigger size. All this work will surely be worth it

**Comment by ComicIronic** [comment]
Nobody said that _you_ had to do it, you human crybaby.

**Comment by NigglyWiggly** [comment]
Well then let's just turn to our dedicated team of talented spriters that have all the time in the world to put in all the effort for changes that no one asked for

_we don't have a dedicated team of spriters_

That said I should probably stop complaining about how fucking stupid 64x is on this issue, I already made a statement about this shit months ago

**Comment by PJB3005** [comment]
@ComicIronic they're not finished yet though. I'll look around for it on TG and when they hit go on consistent palette we can follow.

**Comment by ComicIronic** [comment]
We might be able to get an inter-codebase colour standard.

**Comment by Shadowmech88** [comment]
The amount of work that would be involved to remake the existing sprites in a single palette is so huge, and the number of people who _care_ is so small, that I really don't think this has any chance of ever being completed.

**Comment by NigglyWiggly** [comment]
Yeah.
Like I said before, it's great idea and I'd love to see it, but the sheer workload of that would be insane.
If we were to rebuild SS13 from the ground up, somehow, then I'd most definitely get behind this, but as we are right now, it'd be too much effort.
There's of course, the issue of deciding what that palette would be.

**Comment by PJB3005** [comment]
> There's of course, the issue of deciding what that palette would be.

We can work with TG on that.

@WJohn

**Comment by ComicIronic** [comment]
Why are you talking as if making this decision wouldn't be another one of the non-retroactive quality improvement rules that we've established for this codebase on account of sitting on a 15 year old pile of shit?

What would possibly convince you that this, as an exception to all previous examples of such rules, would for whatever reason be applied to every single old sprite we have, instead of the new sprites being added to the repo in the same way the code rules are?

**Comment by Shadowmech88** [comment]
Because players don't have to look at the old code.

There's no point in making sprites adhere to a palette, with the goal of making them look cohesive, if we don't update the old sprites to use said palette.

The palette isn't going to lead to a cohesive style if 99% of the sprites don't use the palette. And the number of sprites that we have now is so huge that even multiple _years_ from now the number of new sprites which use the palette wouldn't even approach 50% of the total sprites.

What, then, is the point of enforcing the palette at all?

**Comment by ComicIronic** [comment]
1. Sprites are normally replaced over time.
2. It helps keep new sprites inside a visual guideline

**Comment by Shadowmech88** [comment]
1. Not often enough to make a difference.
2. What's the point of keeping new sprites inside a visual guideline if 99% of all other sprites don't share it?

**Comment by NigglyWiggly** [comment]
> Sprites are normally replaced over time.

We've had some sprites that haven't changed in _YEARS_

**Comment by PJB3005** [comment]
In fact I believe the engine sprite for the shuttles are still the same art from when SS13 was first leaked.

**Comment by ComicIronic** [comment]
You're right, the game has never undergone enough slow sprite changes to be noticeable.
![oldstation](https://cloud.githubusercontent.com/assets/7339857/17463081/b93ce89e-5cb6-11e6-85ca-75859294d7ac.png)
Never.

**Comment by NigglyWiggly** [comment]
You realize we still use sprites from those days.
That ID sprite is almost identical to the one we use right now.
Also that gift wrap sprite

**Comment by 9600bauds** [comment]
That's because there is no reason to re-do the ID sprites, while there is reason to re-do those windows

The thing is, there is no reason to resprite windows NOW
Nobody will resprite most sprites that look decent in the current year

**Comment by ComicIronic** [comment]
We still have some sprites, but the general game has changed completely. There's no reason to suggest that just because we might carry over some old sprites, we won't ever see the benefits of a consistent palette.

**Comment by DeityLink** [comment]
This discussion has been dead for 2 and a half years. Just close it and open a new one if the topic becomes relevant again. Overall the opinion of our spriters on Discord seems to lean massively toward 👎
