### ISSUE TITLE
Text markup for IC paperwork is broken

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#10310]
plz fix
![paperwork](https://cloud.githubusercontent.com/assets/19157295/15656654/318ecb88-266f-11e6-9ef7-01a043cba9d0.png)

**Comment by ihadtoregisterforthis** [comment]
#10142 
#9752

**Comment by ihadtoregisterforthis** [comment]
That was fast

**Comment by PJB3005** [comment]
I was actually about to link that other issue too, as I was on the page I saw the reference being added.

**Comment by Durgen** [comment]
wowee
