### ISSUE TITLE
No pepper spray refiller in the warden's office on bus station

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#10317]
im smh tbh fam bams. How can I enter my inner shitcurity if I cant refill my pepper spray? Fix this POST HASTE.

**Comment by Imagebard** [comment]
>smh tbh fam bams

Ironic shitposting is still shitposting.

**Comment by mrpain666** [comment]
The shit posting goes away when I get my shitcurity tools. Fam.

**Comment by 9600bauds** [comment]
By pepperspray refiller you mean sink, right?

**Comment by kol1th** [comment]
> By pepperspray refiller you fuel tank, right?

fixed for ya :eggplant:

**Comment by Kurfursten** [comment]
No problem. This is an easy fix. I'll even throw in one in the storage room or the officer lounge while I'm at it.

But while I'm at it, do you have any other complaints about the Bus brig, or is it mostly working out for you? Have you been getting any mileage out of the perma gym or perma cafe?

**Comment by mrpain666** [comment]
No I havent seen much of it yet, sorry.

**Comment by Kurfursten** [comment]
I'm working on a big medbay cleanup, but in the interim, you can find a pepper spray refiller in the officer lounge about ten squares to the right of the warden office.
