### ISSUE TITLE
Vox Raider hardsuits don't have welding protection, but more importantly, Vox trader hardsuits have flash protection

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10314]
I guess this is shitty because Vox Raiders don't even have any welding goggles on their ship, and I can't think of any other hardsuits that have flash protection but not welding protection
More importantly ~COUGH COUGH #4616 VOX TRADER AND VOX RAIDERS STILL HAVE THE SAME HARDSUITS WHICH HAVE FLASH PROTECTION AND HEINOUS PROTECTION VALUES~

**Comment by Imagebard** [comment]
>energy = 15

What does this do again

**Comment by 9600bauds** [comment]
I actually have no idea

**Comment by Imagebard** [comment]
I'm actually pretty sure its supposed to be stun reduction but I have been informed that stun reduction is impossible
So, huhhh, might want to test that out, because either you've got a unrelated proc that should stay here or a stun reducing proc that might just be removed altogether.

**Comment by Shadowmech88** [comment]
There are projectiles that are children of `/obj/item/projectile/energy` that don't stun.

**Comment by ComicIronic** [comment]
It's energy damage, like lasers.

**Comment by Shadowmech88** [comment]
But lasers are children of `/obj/item/projectile/beam`, not `/obj/item/projectile/energy`.

**Comment by ComicIronic** [comment]
I don't think it's decided by the type, just by a var on the projectile itself.

**Comment by ghost** [comment]
Energy = 15 means that there is a 15 % chance that incoming energy damage will be ignored, usually silently (aka no "The armor blocks the laser" message)

That's literally how the defense values work

**Comment by NigglyWiggly** [comment]
Energy can block stuns, IIRC.

One of the armors I made had energy set to something like 20 because I didn't really know what it was, and I used it ingame one time and took 3 taser shots before I actually got stunned.

**Comment by Imagebard** [comment]
In which case, christ why does the trader outfit have this?

**Comment by 9600bauds** [comment]
Because it was never designed with the possibility of non-antag Vox in mind, and especially not Vox traders
These are the same stats as the syndie suit

**Comment by ComicIronic** [comment]
REMOVE TRADER

**Comment by ghost** [comment]
Just give the trader a civilian suit with really shitty stats

We should have really just made it so Voxes don't spawn with a suit, but just internals, but it's a bit too late now, is it ?

**Comment by Imagebard** [comment]
>These are the same stats as the syndie suit

We REALLY should separate them.
