### ISSUE TITLE
Librarian cannot open his own shutter in his Den on Bus Station

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#10328]
What happened: I was the Librarian and I tried to open the shutter in my library backroom on bus

What you expected to happen: The door to open

What actually happened: Sod all

**Comment by Kurfursten** [comment]
How did it take so long for someone to report this?

**Comment by Imagebard** [comment]
Who the fuck plays librarian?

**Comment by Kurfursten** [comment]
Anyway, next update will probably be tomorrow and will fix this. Until then, ask for Cargo access at HOP.

**Comment by NigglyWiggly** [comment]
Maybe I should play more often so I can catch things like this

**Comment by ScrambledSteak** [comment]
I play librarian @Imagebard you fuck
