### ISSUE TITLE
Cards against nanotrasen. 

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10324]
Cards against humanity: SS13 edition.

**Comment by ComicIronic** [comment]
CARD IDEAS GO:

"___________!
No, we build!"

"AI, State Laws!
Law 0: __________"

**Comment by PJB3005** [comment]
Somebody get a piratepad up for it (on mobile atm)

**Comment by FudgePucker** [comment]
"Captians spare ID"
"Black Assistant"
"Waifu"
"Valids"

**Comment by clusterfack** [comment]
Put it on the thread you'll have a thousand ideas in no time

**Comment by TheFriggenSawbones** [comment]
ideas: make a real game out of wizard cards instead

**Comment by PJB3005** [comment]
http://piratepad.net/PukPEMPnyA
