### ISSUE TITLE
Cloned Mimes Should Not Lose Their Muteness

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10321]
When a human gets cloned, the cloner should check their mind's job and, if it's mime, re-apply the muteness, invisible wall power, and vow break verb.

**Comment by clusterfack** [comment]
I know right, I've said that a few times before. It's not 100% as easy as it appears but it should be possibly to put it in transfer mind or something

**Comment by Arthurdentist** [comment]
would mean that cursed wizard mimes would remain cursed on cloning which is pretty op

**Comment by Shadowmech88** [comment]
No it wouldn't. The mime curse doesn't change their mind's job.
Your mind has a var that's set to whatever job you started the round as. To my knowledge, nothing changes it.

**Comment by ComicIronic** [comment]
Wouldn't this mean you could oathbreak and then be re-mimed?

**Comment by Imagebard** [comment]
That would depend on how the feature is coded.

**Comment by Orangerush** [comment]
Don't clone mimes 8)

**Comment by DamianX** [comment]
fixed by #19013
