### ISSUE TITLE
Xenobio

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10325]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
I don't think the connecter port is connected to the plasma room.

**Comment by Shadowmech88** [comment]
What map?

**Comment by kol1th** [comment]
Most likely bus.

**Comment by Kurfursten** [comment]
Will be fixed in next edition

I swear I tested this exact pipe. I don't know how it could have vanished. The mind boggles.
