### ISSUE TITLE
Crit never darkened my vision.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10326]
This shit happened
I really can't 
![critovision](https://cloud.githubusercontent.com/assets/5169310/15695454/5326780c-2775-11e6-9436-6432fa3dfdfd.png)

**Comment by 9600bauds** [comment]
There's something poetic about this image

**Comment by ComicIronic** [comment]
You need to be more descriptive.
Are you on the latest Byond version?
How did this happen?

**Comment by PJB3005** [comment]
HUD code, that's how.

**Comment by clusterfack** [comment]
There's some problem or another with the full screen overlays that we ported from TG when we took their work to make our code 510 compatible

@gbasood Might know more about it

**Comment by gbasood** [comment]
I actually have no idea what would cause this offhand
All the code that handles actually ADDING hud overlays is still over in lifecode

**Comment by ddolll** [comment]
I'm still getting this occasionally, maybe one out of every five crits.
This is occurring on 512.1426
I'm still getting the UI freezing issue on this version though so something dumb might be happening locally

**Comment by Killette2** [comment]
I had it a few days ago too actually. I forget the circumstances

**Comment by ddolll** [comment]
![nooverlaycrit](https://user-images.githubusercontent.com/44032911/47242289-43bce280-d429-11e8-9214-277ef1b7b632.png)
This on .1453 yesterday

**Comment by DeityLink** [comment]
Should be fixed by now, especially with the latest improvements to damage overlay code in #29730
