### ISSUE TITLE
Player spawned ERT's have no ferry access- who cares give them teleporter access instead!

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#10331]
If Im not mistaken players have the ability to "self spawn" an ERT under code red.

If so, it's entirely possible for one to show up when no admins are on or able to help them, and thus stranding themselves on Centcom as they seem to lack the access to interact with the shuttle console themselves.

This occurred on Box, if it matters. The problem is also probably universal though.

**Comment by Shadowmech88** [comment]
Until this is fixed, the ERT can still get to the station via the teleporter northeast of their spawn room.

**Comment by Probe1** [comment]
It wouldn't take but a second to change.  I'm not sure if it should be changed though.

**Comment by Shadowmech88** [comment]
If players can create an ERT without admin intervention, why should that ERT be unable to work their own ferry without admin intervention?

**Comment by SonixApache** [comment]
I thought you could only spawn in as ERT if an admin initiated the event?

**Comment by Probe1** [comment]
As it turns out on code red cpt access can request an ERT automatically.  I didn't know that but it's always been there.

**Comment by ghost** [comment]
The reason behind them not getting ferry access is so that they can't just be looted of their card, and people run through centcomm to get the mechs.

They should just use a teleporter by default, really.

**Comment by Probe1** [comment]
I did not think of that.  That is horrifying.

**Comment by Shadowmech88** [comment]
What about breaking the ERT shuttle console after one use?

Would they ever need to return to Centcomm and _not_ be on the Escape shuttle or a pod?

**Comment by kol1th** [comment]
They don't have access to the teleporter room, so they gotta break in anyway

Just give em access to that room and it's gucci TBH

**Comment by mrpain666** [comment]
Yeah I understand the argument for not giving them ferry access now. If they honestly dont have access to their own teleporter room, that should ideally be fixed IMO. I edited the issue. If you want to discuss the original topic make a new one, I guess.

**Comment by Probe1** [comment]
It still has the fundamental problem of Johnny Shitdick clicking the button first, running to the teleporter and flinging himself to the station instead of waiting for other players to join in and a briefing from an admin.  

Which you _know_ is how most players think.  Teamwork has to be enforced via the game or else it falls apart 9/10 times.

Still its a minor change and I'm willing and okay with it. 

 I'd like to add a little something to the ERTs join text that says "Don't metagame or run off by yourself".

**Comment by PJB3005** [comment]
Could also make it so launching the ERT shuttle blocks off the equipment room.

**Comment by Probe1** [comment]
players WILL find a way past it.
