### ISSUE TITLE
add gps on the eva/pod hangar places on bus station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10335]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the feature

add gps for spess exploring

> What you expect to happen

more spess exploring

**Comment by Kurfursten** [comment]
You know technically those pods are supposed to be for emergency transport between stations not abandoning the crew at roundstart

**Comment by PJB3005** [comment]
Make it impossible for the pods to leave the station's z level.

**Comment by Kurfursten** [comment]
I thought about doing that with a new pod subtype
