### ISSUE TITLE
Cable cuffs take 2 minutes to resist out of instead of 30 seconds

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10334]
(WEB REPORT BY: probe1 REMOTE: 172.93.109.202:7777)
what it says on the tin

**Comment by Probe1** [comment]
@ComicIronic Can close I was mistaken.

**Comment by Probe1** [comment]
fwiw now that the round has ended..

I was mistaken in what happened.  I was buckle cuffed which takes 2 minutes regardless.  I thought I had resisted prior.

**Comment by ghost** [comment]
Eejit
