### ISSUE TITLE
Nuke OP Access

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#10332]
Crew members can still Nuke OP/Raider shuttles by simply touching the computer.

Probe1 - Today at 1:57 AM
i've never understood that rule and think its a code issue more than an admin issue
if a player finds it a player finds it
if they shouldn't be allowed to ship jack then the console should have 

req_access =list(sydicate_access)

and if a playyer kills a nuke op (or heister), FINDS the ship, and steals it then good on him.

nuklearcellphoneg - Today at 2:06 AM
^
hey let's make an issue I'm sure it will get fixed

Probe1 - Today at 2:27 AM
it would take like
30 seconds to fix
legit make an issue and i will

**Comment by ComicIronic** [comment]
What exactly is the issue

**Comment by clusterfack** [comment]
Yeah not sure either, you know you cant just post excerpts from chatrooms and expect us to understand you

**Comment by nuklearcellphoneg** [comment]
Probe1 - Today at 2:27 AM
it would take like
30 seconds to fix
legit make an issue and i will

Supposedly Probe will do it.

@Probe @Probe

Anyway, the issue is when Nuke OPs land their ship, and, say, the clown finds and rides it back which fucks the OPs. Their shuttle should have some form of ID protection.

**Comment by ComicIronic** [comment]
HONK

Can't they just close the shutters from their PDAs?

**Comment by nuklearcellphoneg** [comment]
On the one hand, yes.

They only get one PDA, though, and it's kind of a lame dick move- like, sure, you kill an OP, get their ID, go find their ship, sabotage them, okay...

But, you hear 'NUKE OPS' then immediately look for the shuttle and send it back, thus essentially winning.

**Comment by Shadowmech88** [comment]
I thought at least the raider shuttle required a raider ID.

I remember being able to remote-control a raider shuttle one round via abuse of project mind, but it only worked if I was wearing the ID we confiscated from a raider we caught.

**Comment by Probe1** [comment]
I told him to make an issue and I'd address it so I didn't forget.  Tag it as mapping please.

**Comment by Allspice** [comment]
There's two sets of agent IDs for ops, the ones they start with and the ones in their lockers. If the nuke ops don't secure all of the cards and don't drop the shutters all it takes is a crew member hacking in, taking a locker card, and sending off.

**Comment by icantthinkofanameritenow** [comment]
@Allspice 
I never saw the point of those spare agent IDs in the first place. They're better off removed.

**Comment by mrpain666** [comment]
git gud and lock it behind you

**Comment by Probe1** [comment]
There's something to be said about adding syndicate lockers so they CAN lock it.

**Comment by ComicIronic** [comment]
I think he means the shuttle, which they can already lock behind them.

**Comment by icantthinkofanameritenow** [comment]
@ComicIronic

But very few nuke ops even use the PDA that lets them do that.

**Comment by ComicIronic** [comment]
Then that's arguably more of a player problem than a design problem. We can put in a roundstart message, but it is a nukeops job to secure the shuttle.

**Comment by Allspice** [comment]
I've wondered for a bit: If the ops shutter the shuttle and the person with the PDA goes kaput, how do they get back on?

**Comment by nuklearcellphoneg** [comment]
@allspice same thing if they lose all pinpointers really

**Comment by ghost** [comment]
It used to be that Nuclear Operatives had to use their military PDA to shutter their shuttle. And frankly, they should since any bumfuck can try and raid it for free military supplies

**Comment by FudgePucker** [comment]
Only one PDA, if who is carrying it deathgasps or dies its gg because they can't get back into the ship

**Comment by icantthinkofanameritenow** [comment]
@FudgePucker

Also, keep in mind that if they use the Detomatix cartridge built into it,  they might end up making it blow up due to a PDA bomb backfiring. So they'd be unable to shutter it at all.

**Comment by Probe1** [comment]
lol you fool you tagged @probe not @Probe1

That's why I never heard of this
