### ISSUE TITLE
Move windowbreaking and firelock logging to atmos logging

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10342]
please
why the fuck would it go elsewhere
Maxwell Green/(blueleaf) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=222;Y=224;Z=1'>Central Primary Hallway - 222,224,1</a>
Maxwell Green/(blueleaf) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=220;Y=224;Z=1'>Central Primary Hallway - 220,224,1</a>
Davis Fulton/(fruktlimpa) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=220;Y=226;Z=1'>Central Primary Hallway - 220,226,1</a>
Davis Fulton/(fruktlimpa) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=222;Y=226;Z=1'>Central Primary Hallway - 222,226,1</a>
Ms. Scrub/(mcscrub2) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=233;Y=253;Z=1'>Central Primary Hallway - 233,253,1</a>
Dr. Slippy Joe M.D/(garethgobblecoque) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=210;Y=245;Z=1'>Central Primary Hallway - 210,245,1</a>
The extreme treeman/(ziekr) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=223;Y=189;Z=1'>Engineering - 223,189,1</a>
Kiley Ivanov/(driskal) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=235;Y=196;Z=1'>Engineering Foyer - 235,196,1</a>
Samuel Keeper/(smallboss) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=221;Y=253;Z=1'>Central Primary Hallway - 221,253,1</a>
Dr. Slippy Joe M.D/(garethgobblecoque) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=211;Y=235;Z=1'>Central Primary Hallway - 211,235,1</a>
Davis Fulton/(fruktlimpa) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=230;Y=226;Z=1'>Central Primary Hallway - 230,226,1</a>
Davis Fulton/(fruktlimpa) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=232;Y=226;Z=1'>Central Primary Hallway - 232,226,1</a>
Ms. Scrub/(mcscrub2) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=217;Y=256;Z=1'>EVA Storage - 217,256,1</a>
Dr. Slippy Joe M.D/(garethgobblecoque) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=219;Y=227;Z=1'>Head of Personnel's Office - 219,227,1</a>
Ms. Scrub/(mcscrub2) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=221;Y=261;Z=1'>EVA Storage - 221,261,1</a>
Samuel Keeper/(smallboss) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=210;Y=245;Z=1'>Central Primary Hallway - 210,245,1</a>
Davis Fulton/(fruktlimpa) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=241;Y=232;Z=1'>Central Primary Hallway - 241,232,1</a>
Beep_Boop_Bot/(lamberts) opened the closed and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=230;Y=190;Z=1'>Engineering Foyer - 230,190,1</a>
Samuel Keeper/(smallboss) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=211;Y=235;Z=1'>Central Primary Hallway - 211,235,1</a>
Maxwell Green/(blueleaf) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=197;Y=234;Z=1'>Cargo Bay - 197,234,1</a>
The extreme treeman/(ziekr) closed the open  firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=230;Y=205;Z=1'>Atmospherics Monitoring - 230,205,1</a>
[10:36:00]ADMIN: parsunmaisti/(Parsunmaisti) is a relatively new player, may consider watching them. AGE = 0 First seen = Requires database
Lenny Webb/(blithering) closed the open and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=211;Y=245;Z=1'>Central Primary Hallway - 211,245,1</a>
Richard Clarke/(magnnarot) closed the open  firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=174;Y=254;Z=1'>Arrival Shuttle Hallway - 174,254,1</a>
The harm baton/(pvak) opened the closed and alarming firelock at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=229;Y=202;Z=1'>Engineering Foyer - 229,202,1</a>

**Comment by kol1th** [comment]
:ok_hand:
