### ISSUE TITLE
Revamp client interface 

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#10346]
Basically do what we do with the verb option window and tab chat. So IC chat is separate from OC chat and logs can have its own tab as well so admins don't get spammed with shit and cant read chat. Another idea is to have 2 (or 3 for logs) chat windows that the user can move or close out of entirely and reopen later.

**Comment by ComicIronic** [comment]
Don't quote me on this, but the chat splitting would seem possible with goonchat since we can create our own windows, and it could be useful, but some people would request the mixed chat so we'll have to consider the implementation.

**Comment by AlphaBuffalo** [comment]
What about setting it up so you can set what gets sent to each window?

**Comment by AlphaBuffalo** [comment]
![new interface](https://cloud.githubusercontent.com/assets/5650556/15800766/7a215c28-2a50-11e6-990e-20dbabe1f790.png)

Would something like this work, where you have 2 chat boxes one for the OOC and one for the ICC? Possibly have a cogwheel button to change what each window displays like one can show combat text or the logs for the admins?

**Comment by clusterfack** [comment]
We could probably make a tab for the different chat windows with relative ease
