### ISSUE TITLE
Corpse Decay

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#10348]
Please make this happen. Also realism can suck my smooth co-

Anyway this would be pretty nice.

**Comment by Probe1** [comment]
Gibbers and sticking corpses with monkey SEs then meat spiking them are natures way.

**Comment by unid15** [comment]
Cockroaches and flies spawning out of dead corpses when

**Comment by Probe1** [comment]
>mosquitoes on a space station
Horrifying.

**Comment by AlphaBuffalo** [comment]
If we add mosquitos we should have a the zika virus be a thing. Or just allow them to transfer diseases better

**Comment by Probe1** [comment]
We should really have ebola as a virus tee bee henest

**Comment by iwillkillmyself** [comment]
:thumbsdown:, what'd happen to ERPing with your waifus dead body in no rules day?

**Comment by jknpj** [comment]
Space is a natural freezer that can keep bodies preserved for years. Dead bodies, that is.

**Comment by AlphaBuffalo** [comment]
Would the bodies expand from being in space? I dont think its a great preserver.

**Comment by ComicIronic** [comment]
The gas in your body is quite mininal: the main thing it would do is escape through your holes.

The great part about space is all your liquids boiling off under a lack of pressure, which desiccates your corpse (which is why space bodies huskify).

**Comment by 9600bauds** [comment]
What's the point

**Comment by AlphaBuffalo** [comment]
Autism, thats the point

**Comment by Shadowmech88** [comment]
A corpse wouldn't show any signs of decay in the few hours it takes to complete a round.

Are you asking for unnaturally super fast decay?

**Comment by ComicIronic** [comment]
You also wouldn't feel hunger at the rate you do.
Spessmen runs on advanced time due to being in the well of the gas giant.

**Comment by AlphaBuffalo** [comment]
I guess that means working for NT really does bring you closer to death.

**Comment by MusgardTiger** [comment]
You are basically some guys clone anyeay.

Like five minutes after death body starts to decay and by fifteen minutes you are a bloated nasty cunt.

Also people die inside the station more than they die in space, I dont think corpses not decaying in space is relevamt to this feature request. This req is about decay on station.
