### ISSUE TITLE
Syndicate Mothership (nuke op shuttle) still has infra red emitters 

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10347]
![image](https://cloud.githubusercontent.com/assets/8550416/15741019/a1b9a3a2-2885-11e6-8829-a67167c0650e.png)

The code is defunct and they do not appear in game.  This applies to all maps.

**Comment by Kurfursten** [comment]
Well, that went 2 years without being noticed

**Comment by icantthinkofanameritenow** [comment]
Fixing this now, PR will be done soon.
