### ISSUE TITLE
Malf hi-res cameras doesn't let you examine papers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10349]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 1a09ef9bbdc5bb455e0be5e081abc23ceed928f0
> 
> General description of the issue
> Can't shift-click or right-click->examine papers as a malfunct AI that bought hires cameras to see what's on them. Not sure that the lipreading works either but I didn't pay much attention to that.
> 
> What you expected to happen
> Buy hires cams to examine the RD monitor key
> 
> What actually happened
> Couldn't read the key.
> 
> Steps to reproduce if possible
> Become malf and spend 10 CPU on hires cams.

**Comment by Allspice** [comment]
Alrighty, so you need to double-click papers to examine them instead of shift-click and all that. Not what I expected. But I had some help doing more tests and it seems that the lip-reading functionality is legitimately not there. Or at least I don't know how to get it working.

**Comment by clusterfack** [comment]
Yes it seems it's not overwritten on examine yet. Not sure about the lip reading thing
