### ISSUE TITLE
Malfunctioning AIs freeze for no raisin.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10343]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 7eb4d7c97a0140b6dd70b9f5dcd9fdc109e15285
> 
> General description of the issue
> After ~15-30 minutes a malfunctioning AI's game starts freezing for no apparent cause before code delta. And HOPEFULLY it stops freezing after ~10-15 more minutes.
> 
> What you expected to happen
> Not to freeze before crushing those fuggin carbons
> 
> What actually happened
> Ice-cold game freezing.
> 
> Steps to reproduce if possible
> Become a malfunctioning cunt and wait.

**Comment by Imagebard** [comment]
What the fuck do you mean by "freezing"?

**Comment by Shadowmech88** [comment]
Maybe it's another hypothermia bug.

**Comment by MercuryDoll** [comment]
> game starts freezing

So probably dreamseeker locked up. Oddly enough, the client does this now and then for me for no apparent reason, sometimes it unfreezes seconds later, sometimes it's completely stuck.

**Comment by clusterfack** [comment]
Literally not enough information to do anything, if its the game freezing we would need to profile it to see why. 

If it's your dreamseeker freezing we can't do anything. 

This is of no use to us and we can't really help you either.
