### ISSUE TITLE
Lipozine not working for borers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10344]
(WEB REPORT BY: orangerush REMOTE: 172.93.109.202:7777)
7eb4d7c97a0140b6dd70b9f5dcd9fdc109e15285 
Lipozine doesn't cause weightloss for faties when you use it as a borer. Doesn't even show up as a chemical with taste blood

**Comment by Shadowmech88** [comment]
I don't believe this is related to borers specifically, and may be or have been a problem with lipozine itself.

**Comment by ghost** [comment]
Could not reproduce
