### ISSUE TITLE
Toolbelts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10350]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
Robotics and research should spawn with a toolbelt or two

**Comment by ComicIronic** [comment]
This is not how you write an issue.

Someone go chase this arsehole down on the server.

Does he mean:
- Every scientist and roboticist should spawn with a belt (I oppose this)
- Some maps don't have a starting belt for these jobs

**Comment by 9600bauds** [comment]
Bus doesn't have any toolbelts mapped in in Science I'm pretty sure

**Comment by ComicIronic** [comment]
That's why I was thinking of tagging it Bus, but the issue is too non-specific

**Comment by Kurfursten** [comment]
Can't be Bus. Robotics and R&D both have toolbelts. Now, you might have to compete for them, like on other stations.

Or get one biogenerated at botany. They'd be thrilled.
![bus science](https://cloud.githubusercontent.com/assets/9782036/15762974/6ff7a2f4-28e6-11e6-882b-fb9afbd80530.png)

**Comment by ComicIronic** [comment]
Closing for non-specific, then
