### ISSUE TITLE
Add Kilns To Make Bricks So We Can Make Bricks And Brick Accessories

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#10353]
![a038cc46ae97a7cb812efd6bcefa5f74](https://cloud.githubusercontent.com/assets/5650556/15764932/53cb9c90-28fd-11e6-8f69-267c502f4bbc.png)

I added bricks and brick walls, but I dont know how to into machinery code enough to make a machine that produces bricks from sand. I'm making an issue for my incompetence and Im asking for your help to make my dream of maxi cozi rooms like this to be a reality.

Also if anyone can sprite better than me go ahead and resprite those walls if you want to, I just rehashed mineral walls.

**Comment by Kurfursten** [comment]
You could just have bricks be produced from sandstone blocks

**Comment by AutismSpider** [comment]
Sandstone Blocks+Welding tool for bricks

**Comment by MercuryDoll** [comment]
How do you even make sandstone?

**Comment by AutismSpider** [comment]
Sand into sand stone by using it (aka magic and shit)

Sandstone can be use for walls/airlocks and other fun stuff

**Comment by PJB3005** [comment]
Could make a smelter recipe for it.
