### ISSUE TITLE
Spritey/Idea: Mastercraft sword, possible use for mythril and leather.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#10355]
There's not been much use for mythril sheets or leather, and I thought it might be nice to add further steps if people want to make their swords a bit more professional instead of leaving them with a wire wrapped hilt. 

![forging](https://cloud.githubusercontent.com/assets/15067109/15767884/eae5a422-2943-11e6-8323-e483e2bbe28e.png)

Idea would be to make the hilt using 5 mythril sheets, add two leather sheets for the grip, then add to a regular sword and weld to secure it. Maybe have a step for chaplains to bless it with a biblesmack to get the shiny runes.

The upgraded sword could have a change in sharpness or swing speed, or it might just be nice to have them able to be named, either detective's revolver style, or having a pool or random names to be chosen when it's completed.

**Comment by Shadowmech88** [comment]
Mythril is currently unobtainable.

**Comment by MercuryDoll** [comment]
^ This. I'm not even sure if we even have sprites for mythril ore, let alone the code for it. The only thing i found referencing mythril were coins, which _can_ be obtained _only_ via xenoarcheology. And while this sounds neat and we could certainly add mythril in easily, it thematically isn't very relevant (the few medieval gear we have is more of a tongue in cheek joke) and there's not enough stuff to make out of it that would make implementing a new ore reasonable. I'd rather we had more stuff to do with the ores we currently have, like phazon.

**Comment by Exxion** [comment]
I was going to say you could recycle mythril coins to get sheets but turns out you actually can't because they don't actually contain mythril

**Comment by MercuryDoll** [comment]
One line of code to fix but even finding a mythril coin is a one in a thousand chance considering we have thematic burial sites with higher dropchances for other stuff. That, combined with them being a small artifact which is easily destroyed if you aren't going for the slow and tedious xenoarch way makes them completely irrelevant as a method of obtaining. You have better luck praying for them.

**Comment by Blithering** [comment]
From personal experience, xenoarchaeology digsites drop sheets drop stacks of mythril sheets quite frequently.
Both the materials are really awkward to obtain, but have no purpose once you have them.

**Comment by icantthinkofanameritenow** [comment]
And there's no guarantee the sheets themselves will even show up at all. This does sound neat, but you'd still have to add in mythril ore first- possibly as another rare mineral along the lines of Phazon or bananium.

**Comment by PJB3005** [comment]
Adding an ore for 1 gimmick is shit.

IMO the mythril only coming from digsite RNG is fine since it's a gimmick anyways.

**Comment by NigglyWiggly** [comment]
> Mythril is currently unobtainable.

But it's not

I routinely find like 3-5 of the sheets whenever i play Miner

EDIT: look like this was already mentioned.

I agree with PJB, Mythril is already rare on its own, and that would make it a perfect fit for what is supposed to be a pretty rare item

**Comment by ScrambledSteak** [comment]
Mythril scimmy and full helm/platebody when
I need to go kill some hill giants

**Comment by NigglyWiggly** [comment]
That said, just using the myrthril, and THAT MUCH of it for the hilt and not the blade seems like a waste

**Comment by ScrambledSteak** [comment]
Using Mythril, Leather, an ancient ritual involving the chaplain, crayon runes, candles and a hammer, we have created the HOLY LONGSWORD, the only weapon capable of killing Nar-Sie.

Make it happen.
