### ISSUE TITLE
Cultists can soulstone the sacrifice target and render the mode unwinnable for the cult.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10354]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 29bca8f6d19fd6995a766ca83dfd205bbbb897a1 
> 
> General description of the issue
> Title
> 
> What you expected to happen
> Not to be able to soulstone the sac target, just like you can not convert them.
> 
> What actually happened
> Into the stone they go.
> 
> Steps to reproduce if possible
> Have some scrub cultist stone the target.

**Comment by PJB3005** [comment]
Is this an issue? 

If people gib him or something it's the same issue and their problem and fault.

**Comment by Shadowmech88** [comment]
If you gib them, you can still sacrifice the head.
If you soulstone them, you're shit out of luck.

**Comment by ComicIronic** [comment]
Can't you just clone someone from their gibs and then sac them?
And this would be an issue because soul-stoning is pretty standard cult practice, so if it's a bad thing to do to the target, cultists shouldn't really be allowed to do it.

**Comment by Kammerjunk** [comment]
You can indeed not clone someone from their gibs, no. If you don't have a head, you can't clone or sac them. I assume this occured after Deity's soul stone rework, but I don't really know

**Comment by JMWTurner** [comment]
Unable to reproduce. Failsafe working as intended during tests.

![workingasintended](https://cloud.githubusercontent.com/assets/21122521/19832897/703cf1dc-9e30-11e6-862a-900c6d8302bb.png)
