### ISSUE TITLE
Some fool left their debug code in the game for right clicking objects

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10368]
![image](https://cloud.githubusercontent.com/assets/8550416/15778081/f919e512-2961-11e6-8ee2-9ef3a3b8c0e5.png)

hey :)

**Comment by PJB3005** [comment]
Hey

**Comment by Probe1** [comment]
There's also a Commands tab that has the same verb.

**Comment by Kurfursten** [comment]
Whoever removes this should also remove the debug text about spawning sleeper consoles

**Comment by ihadtoregisterforthis** [comment]
It shows the object or mob icon as it appears on examine. It's still a faulty icon but
hey

**Comment by clusterfack** [comment]
Whoops? It just calls getflaticon

**Comment by NigglyWiggly** [comment]
<sub> hey

**Comment by clusterfack** [comment]
And now its gone
