### ISSUE TITLE
Telcomms overheat isn't damaging then shutting down telcomms.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10361]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision 29bca8f6d19fd6995a766ca83dfd205bbbb897a1 
> 
> General description of the issue
> Lit a plasmafire in telcomms and none of the machinery failed
> 
> What you expected to happen
> Machines to slowly fail then cut out until someone cooled the chamber and replaced the circuit.

It worked like a year and a half or whatever ago. You could start a big fuel fire after dumping some oxygen and it'd heat up then cut out.

> What actually happened
> Nothing.

Pressure:8202.7275 kPa
Oxygen:6%Nitrogen:32%
Carbon Dioxide:62%Toxins:0%
Temperature:5809.85K (5536.7°C)

> Steps to reproduce if possible
> Set telcomms on fire.
> Wait for them to not give out.

**Comment by SGuivenne** [comment]
Fairly certain this bug is no longer a bug.  I've seen multiple rounds of telecoms overheating and crapping out.

**Comment by DamianX** [comment]
This was indeed fixed.
