### ISSUE TITLE
Firing guns at darkness fires at the wrong place if your view is not the default size

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10360]
This is extremely problematic for the sniper rifle

**Comment by clusterfack** [comment]
If this is true its absolutely bizzare, here is the relevant code

![](http://puu.sh/pf1Dy/d95288fa3e.png)

**Comment by ComicIronic** [comment]
It'll be the world.view instead of user.client.view, I think.

Also why do guns not use afterattack anymore?

**Comment by clusterfack** [comment]
Oh fuck you're right, how did I not notice that

**Comment by clusterfack** [comment]
Yes that would definitely fix it
