### ISSUE TITLE
Can't properly 'complete' fullwindow plus four directionals.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10367]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision  d925bcd785bf5406a2096a55dbf750393c7eb0d1
> 
> General description of the issue
> Can't screwdrive-crow-screwdrive the final directional once you move off the fullwindow-directional tile. Likely due to whatever change made it so you can't interact with other tiles while on a fullwindow.
> 
> What you expected to happen
> To be able to secure the final window.
> 
> What actually happened
> Nope.
> 
> Steps to reproduce if possible
> Attempt to create a fullwindow-directional dealie.

**Comment by SysadminJeroen** [comment]
How long has this been a problem?

**Comment by Allspice** [comment]
I'm guessing that it was included with that movement change a month or so ago.

**Comment by 9600bauds** [comment]
Full Windows a SHIT

**Comment by clusterfack** [comment]
To be honest I thought it was related to the full window change done to fix grille hitting?

**Comment by Exxion** [comment]
Oh right. Fulltile windows are, for some unknowable reason, border objects. So they are blocking you from interacting with actual border windows which are on a lower layer.
I wouldn't be surprised if this was always a problem when applying a window from a certain direction.

**Comment by SysadminJeroen** [comment]
I checked and now I somehow can't alt-click on a fullwindow either.

**Comment by ghost** [comment]
I tried to fix full windows as a MoMMI recently and realized ALT+clicking full windows to get the turf under it is strictly verboten

At this point we might as well add a method that allows you to add a full window on a finished window square. Although being able to properly decon and bolt them down again is going to be a problem

**Comment by Exxion** [comment]
If I'm not mistaken, Alt+clicking fulltile windows has never worked
Though if you're building it, you should be able to Alt+click it while you're on the tile then keep the panel open after you move off the tile
Opening the panel checks `Adjacent()` but keeping it open only checks distance

**Comment by SysadminJeroen** [comment]
@Exxion I could alt-click fulltile windows a few weeks or a few months ago.

**Comment by Exxion** [comment]
Really? Oh.
Well anyway making fulltile windows not be border objects would almost certainly fix this
Let me check if it would break anything else

**Comment by SysadminJeroen** [comment]
@Exxion You could checkout a commit from 2 months ago, I'm sure it worked back them.

**Comment by Exxion** [comment]
It's probably a combination of fulltile windows being treated as border objects and the movecode change that broke it
But I just realized that making fulltile windows not border objects may maybe possibly make it impossible to break them down if they are also surrounded by border windows

**Comment by clusterfack** [comment]
Full tile windows are border objects to make it so you cant collide with a grille beneath them

**Comment by Shadowmech88** [comment]
Can confirm this still exists. The presence of a full-tile window prevents you from interacting with any of the border windows on a tile if you're not also on that tile, which means you can't finish a full window+border window combo unless you trap yourself inside it.

**Comment by beesil** [comment]
Fixed by #21754

**Comment by ghost** [comment]
Is there actually a way to repair a four pane plus full window tile though ? I tried a few days ago, could not manage

**Comment by Exxion** [comment]
Did you use Alt+click?

**Comment by ghost** [comment]
Yeah. Maybe I fucked it up, but I was repairing a Brig window. Put two panes, added a full window on top, shifted a pane to face me. Couldn't secure the pane facing me... or the full window, one of either
