### ISSUE TITLE
Feature request: Ratboy Genius costume

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#10365]
Title is pretty self explanatory, I think that Ratboy Genius threads added to the autodrobe would help improve the game greatly.

**Comment by Probe1** [comment]
>asking for people to upvote your feature request

**Comment by carshalash** [comment]
I'm calling you little king john from now on.

**Comment by nuklearcellphoneg** [comment]
D I S G U S T I N G

**Comment by ComicIronic** [comment]
No.

**Comment by carshalash** [comment]
R.I.P

You were too beautiful for this world rat boy genius. Seeing all of the negative votes as compared to the positive I will close this,  I understand how the vote system works.
