### ISSUE TITLE
robotics office doesnt have a toolbelt on bus station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10363]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

no toolbelts

> What you expected to happen
> 
> What actually happened
> have a toolbelt
> 
> Steps to reproduce if possible

join bus

**Comment by ihadtoregisterforthis** [comment]
[Debunked](https://github.com/d3athrow/vgstation13/issues/10350#issuecomment-223438704)

It just spawns under the toolboxes
