### ISSUE TITLE
Holding up a paper to cameras can maliciously spam the AI with popups.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10374]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision fd413e7e7a5b3bf20e1ffc3f566f2c08a3c9c91f 
> 
> General description of the issue
> Slap a camera with a piece of paper 50 times
> 
> What you expected to happen
> Nothing or one popup per minute max
> 
> What actually happened
> Too many popups to cope with
> 
> Steps to reproduce if possible
> Smack a camera with a paper while an AI exists.

Or I suppose the feature could be outright removed, even though admins warn people for abusing it it's mostly used to griff instead of 'legitimate' communication.

**Comment by Shadowmech88** [comment]
And/or could give AIs a toggle that determines whether they get the popup at all, so they can turn it off entirely if someone's being an ass.

**Comment by ihadtoregisterforthis** [comment]
There's another issue on this.
And it can be bypassed by resizing the window for now.

**Comment by Kurfursten** [comment]
We actually did limit this years ago but the limit is very short to avoid complaints

**Comment by ghost** [comment]
Limit should be higher and AI should be able to manually ignore the paper via a href link so that it doesn't have to get spammed by the same shit over and over again

**Comment by Zth--** [comment]
#4582

**Comment by JustSumBody** [comment]
Pretty sure this was fixed by #12184
