### ISSUE TITLE
exosuit control cant unlock the mech after its locked down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10371]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

cant unlock the mech from the console after locking it down

> What you expected to happen
> be able to unlock it
> 
> What actually happened
> cant unlock
> Steps to reproduce if possible

lockdown a mech

**Comment by 9600bauds** [comment]
You need to end maintenance protocols from the maintenance menu of the mech

**Comment by Eneocho** [comment]
tested by locking and unlocking a ripley mk2, it works fine
