### ISSUE TITLE
It Isn't Possible to Move Bodies Up and Down Ladders

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10376]
Do people want this changed? It means that anyone that dies inside the pyramid needs Telesci to get them out.

Instead of using the ladder on click, what about making ladders dense objects that transport anything that bumps into them?

**Comment by clusterfack** [comment]
You can make it so dragged things are transported as well

**Comment by MercuryDoll** [comment]
Dragging people up/down ladders should definitely be a thing, if only because you can drag critted people to safety to apply medical care in the field.

**Comment by PJB3005** [comment]
If telescience works to get them out that's a bug in and of itself.

**Comment by ghost** [comment]
Obviously, ever since multi-Z stations were removed, things like stairs and ladders have stopped working properly

Gonna need some sanitization and what have you. Where did we even shove ladders ?

**Comment by unid15** [comment]
Ladders are just fancy teleporters actually, only used for away missions

I'm working on fixing this issue

**Comment by unid15** [comment]
fixed
