### ISSUE TITLE
Crossroads Demons

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10382]
I've been kicking around this idea for an hour or so.
Currently asking stuff from the gods amounts to "I offer you this thing on the floor, please delete it and spawn a different thing in its place." There isn't even any confirmation as to whether an admin heard your prayer.

This would give offerings a more personal element, where a player could perform a ritual to summon an admin as a crossroads demon, and then make the bargain with them in person.
This has the benefit of providing a clear indication of whether the admin hears you/wants to answer your prayer (obviously you can't make a bargain if no demon shows up) as well as giving you opportunity for better back-and-forth conversation rather than just speaking into the air.

But seeing as this would be mostly a change for admins rather than players, I'd like to get some feedback from admins on the idea.

**Comment by Kurfursten** [comment]
I seriously hope some advantage is conferred upon bringing binoculars to the crossroads demon. Makes sense ~~to me~~ to us, right?

**Comment by Shadowmech88** [comment]
I'll be honest, what I know of crossroads demons is mostly gleaned from a wiki walk I took through the Supernatural wiki for a few hours the other day.
That is to say, practically nothing beyond "you summon it and make a bargain."

What's the relevance of binoculars?

**Comment by Kurfursten** [comment]
Just a dumb 7-year-old joke

https://youtu.be/_WCiBPjckTg?t=2m29s

**Comment by ghost** [comment]
This is more dependent on how fancy the admin wants to go with hamming up the 'trade'

For instance, any time anyone wants to trade the goonecode, I toss smoke everywhere and spawn in as a digital-like shade to talk to the person offering.

Could be cool to have a devil-like carbon mob to spawn in and control for the 'crossroad demons' thing, like stereotypical red skin, horns, and maybe a tail, with it being a carbon mob so you can potentially go fancy business man clothing to boot.

**Comment by Shadowmech88** [comment]
> devil-like carbon mob

I didn't want to make a whole new mob just for this.
I was thinking more along the lines of a regular-looking human test dummy in a business suit with the horns genetic mutation.

Actually I just realized you meant add the mob and let admins make their own adminbus with it.
In which case, I'm not sure carbons can even wear jumpsuits and the like by default.

**Comment by ghost** [comment]
We have a whole new carbon mob just to remove shitters during the christmas break, that's so damn snowflake and fucky that when it's gibbed its limbs are just different sprites of itself.

**Comment by Shadowmech88** [comment]
Can Krampus wear clothes?

Also, I'm not sure what I could sprite that wouldn't essentially be "human with red skin and horns," if I want it to be able to wear clothes without looking terrible.

**Comment by Blithering** [comment]
Only if there's the option to challenge them to a fiddle contest with the space violin.

**Comment by ghost** [comment]
![goldfiddle](https://cloud.githubusercontent.com/assets/9110500/15802197/9035eeaa-2aa2-11e6-9ef3-9d1dc0802c35.png)
