### ISSUE TITLE
Add ping sound to posibrains

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#10388]
So ghosts can finally piss off roboticists audibly.

**Comment by Ephx1** [comment]
The only thing this will do is further the fucking hatred roboticists have of it.
You'll just get a bunch more shoving them in backpacks, trash cans, or lockers and forgetting about them completely.

**Comment by AlphaBuffalo** [comment]
Ban the roboticist who do that then? 

Also I remember making an issue for this but no one doing anything about it

**Comment by 9600bauds** [comment]
Only and ONLY IF they get a 2 second cooldown on ping

**Comment by AutismSpider** [comment]
five second cooldown per ping.

last thing i want is pos brain+borg or mommi ping spaming

**Comment by ScrambledSteak** [comment]
Remember when SAMMIs got ping, buzz and vocalize? It fucking sucked and nobody was happy

**Comment by ComicIronic** [comment]
> remember Sammis
> nobody was happy

You got that right.

**Comment by Shadowmech88** [comment]
Speaking of which, did Cloroxygen just drop off the face of the Earth again?

**Comment by Ephx1** [comment]
> Ban the roboticist who do that then?

But why? It's like the chef/botanist who has to deal with asshole ghosts spamming lights to be nymphs, I can't blame them for not wanting to deal with that annoying garbage.

**Comment by AutismSpider** [comment]
holy water or screwdriver the lights switch.

**Comment by NigglyWiggly** [comment]
Fucking please no, jesus.

One of my favorite things to do is to sit on top of the posibrain and just rapid fire ping

**Comment by AlphaBuffalo** [comment]
@Ephx1 it was a sarcastic comment. But if roboticist dont want to just walk over and hit the posi brain which takes 2 seconds they shouldn't be a robticist. If anything how about makw the posi brain come alive by itself when a ghost pings it. Just give it a CD to let people add their name to the list

**Comment by Ephx1** [comment]
Sarcasm is pretty poor with a playerbase that would probably very much like to ban someone who doesn't want to deal with dicks spamming things.

No, you're right, roboticists should have two seconds to spare, but when you see a ghost rapidly spamming the thing they're just doing it to be terrible at that point.

**Comment by AlphaBuffalo** [comment]
Isnt there already a delay on "posibrain pings" thing?

**Comment by Probe1** [comment]
nah its just attack delay.

I ping posibrains mercilessly when I want to play

**Comment by SonixApache** [comment]
terrible idea
