### ISSUE TITLE
Aluminium metal foam grenades create floors and only floors

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10381]
#### Description of issue

As in the title. In a round the RD supplied engineering with a pod that could fabricate metal foam grenades. We promptly started building a few just moments before immovable rods pierced the station causing breaches. I ran and threw grenades at the openings and to my surprise the foam only created floors in space tiles and nothing else.

Later I asked an admin (Aurx) to test it with premade metal foam grenades and got a confirmation that no walls were created, so I started testing using iron instead in the formula as the spawned grenades use aluminium and they created walls and floors just fine.
#### Difference between expected and actual behavior

I'd expect the grenades to create foam walls instead of just floors to plug breaches, much like how creating a metal foam grenade out of iron works.
#### Steps to reproduce

As stated in the description.
#### Specific information for locating

/obj/item/weapon/grenade/chem_grenade/metalfoam
#### Length of time in which bug has been known to occur

No idea, I have not used these grenades in ages.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
This isn't a bug, this is @shadowmech88 never updating the wiki

#9753

**Comment by Shadowmech88** [comment]
My bad.

**Comment by Shadowmech88** [comment]
The wiki's properly updated now.

**Comment by 9600bauds** [comment]
I think I can close this now

**Comment by Gringonius** [comment]
Guess I should make another issue if I want to suggest /obj/item/weapon/grenade/chem_grenade/metalfoam containing iron instead of aluminium?

**Comment by Kurfursten** [comment]
it might be nice if the box had some of both
