### ISSUE TITLE
sombreros

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10385]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> why arent there sombreros
> 
> What you expected to happen

to be some in the autodrobe

> What actually happened

they dont exist

> Steps to reproduce if possible
> be in station
> sobreros dont exist

**Comment by Imagebard** [comment]
Slablands: Still tales of cloaks and sombreros.

**Comment by AutismSpider** [comment]
i think some one made sombreros.

They were massive though

**Comment by Zth--** [comment]
There are maracas but not sombreros. This is some serious shit

**Comment by Megamaw** [comment]
What good is being cool if you can't wear a sombrero?
