### ISSUE TITLE
seeing sprites behind walls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10398]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> lately I've been seeing dead bodies from behind walls during game. it's not xray vision or anything of the like. Its not very consistent, but if I'm directly underneath where their body is, and lets say there is a wall between us, I can sometimes see their sprite clear as day hovering over the darkness. I've only noticed this very recently, but before the new lighting update. I just saw it again recently and so I wrote out this bug report
> 
> What you expected to happen
> see above
> 
> What actually happened
> see above
> 
> Steps to reproduce if possible
> it's kinda inconsistent, but stand in, say the chemist office, and have another player fall and die above the wall area at the top. I can use it to metaknowledge people being murdered in maint, and actually helped me robust antags before

**Comment by PJB3005** [comment]
I couldn't have caused anything like this.

**Comment by Shadowmech88** [comment]
By the way, on-wall objects are still visible through walls since the move to 510.

Most noticeably the captain's fireplace, which you can see from the hallway.

**Comment by clusterfack** [comment]
Actually you know I went to fix this exact issue but I guess I didn't
