### ISSUE TITLE
Tomb away mission breaches into space when an explosive is detonated.

### ISSUE THREAD

**Issue by golfer45** [d3athrow/vgstation13#10399]
#### Description of issue

Floor can be breached.
#### Difference between expected and actual behavior

A desert shouldn't breach into space when an explosion occurs.
#### Steps to reproduce

Detonate a bomb on the ground.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Are away missions on their own Z-level?
As far as I know base_turf applies to the entire Z-level, so it might be tricky to fix if the tomb shares a Z-level with other things.

**Comment by clusterfack** [comment]
We can put a var on areas for areas to have specific base turfs that override the zlevels base turf

**Comment by clusterfack** [comment]
Which would be useful for things like the asteroid

**Comment by Probe1** [comment]
that's a good idea.

**Comment by clusterfack** [comment]
@unid15

**Comment by FudgePucker** [comment]
Wait isn't that how it is now? If I put a floor plate on the asteroid and destroy it does it become asteroid turf or space?

Also we can copy what polaris did because their station is on an asteroid and bombs in the middle of the station doesn't depressue the station.

**Comment by FudgePucker** [comment]
Also a new turf that can have floortiles on them? First round it was played the clown crowbared up all the gold floor tiles leaving the metal plating underneath.

**Comment by clusterfack** [comment]
If you plate an asteroid turf and destroy it it will become space. Like magic!

I don't know about the metal plating thing though, that requires a bit more of a refactor
