### ISSUE TITLE
Bus - CMO office's APC is not on a wall tile.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10392]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 4cee6922d52fb0f439fd92ab3c9574ec4ca4a836
> 
> General description of the issue
> Title
> 
> What you expected to happen
> APC to be on a wall
> 
> What actually happened
> It was one tile lower on a floor tile.
> 
> Steps to reproduce if possible
> Go to Bus

**Comment by Kurfursten** [comment]
Thanks for reporting. The CMO office needs a little work in general.
