### ISSUE TITLE
Bus - No defibrillator rechargers anywhere

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10393]
#### Description of issue

Self-descriptive, Bus Station medbay doesn't seem to have a single recharger for defibrillators despite having two of them.
#### Server revision

5efc3dfb9f6a3d497d4485150db0160a2e6063bd

**Comment by Kurfursten** [comment]
Good catch, thanks for reporting

**Comment by Gringonius** [comment]
This has been a common complaint for weeks but nobody actually posts it on github and at most keep the whining to ghostchat. This is why I think that a mapper should be observing rounds more often instead of hoping to rely on issue reports.

**Comment by ComicIronic** [comment]
The web report button is RIGHT THERE. We can't burden people to catch bugs by maybe listening to someone complain. l2report

**Comment by clusterfack** [comment]
>This is why I think that a mapper should be observing rounds more often instead of hoping to rely on issue reports.

This is what makes me think players have brain damage

**Comment by Kurfursten** [comment]
If it makes you feel better, I do try to observe when I have time. On the week that Bus launched I made myself much  more available to hear complaints personally both in the thread and in-game, but I can't maintain that level of personal engagement forever, especially as I code other things.

**Comment by Gringonius** [comment]
Fairly sure most players would rather keep the map rough by not reporting issues to build more support to remove it later on. But maybe I'm over thinking it.
