### ISSUE TITLE
After attempting to drain blood from a braindead, blood draining stops working.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#10407]
As a vampire, if you attempt to drain blood from a braindead human mob, you get the message "This blood is lifeless and has no power."
After this, harm intent biting at the head no longer works, and said vampire has to be remade into an antag in order for draining blood to work again.

**Comment by 9600bauds** [comment]
IIRC there was a very similar bug where vampire succ stopped working after trying to succ an invalid target but I can't remember what exactly it was about
