### ISSUE TITLE
Martians megathread

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#10403]
With #10045 merged, multi-handed mobs are now possible to code. The most popular idea currently is martians

![](http://puu.sh/phr7v/df600c817f.png)

There are already sprites provided by @NigglyWiggly, as well as some very basic code in the files, but there is still much to discuss
- Should they be a new type of carbon mob (/mob/living/carbon/martian), a subtype of monkey (/mob/living/carbon/monkey/martian) or a subtype of human (/mob/living/carbon/human/martian)? Each of these options has its own advantages and disadvantages
- Should they be available roundstart as a species, like diona or plasmamen?

**Comment by Brolaire** [comment]
whats the pros and cons of the different subtypes

**Comment by Shadowmech88** [comment]
Of the subtypes listed, the main difference is bodily functions.
Carbons, and by extension monkeys, are pretty simplistic.
They don't have blood, internal organs, or individual limbs, and I'm pretty sure they can't wear clothing of any type by default.

I think the best option would be to make it a new SPECIES of human.
This distinction is important because the code that makes them unique would go into a new /datum/species/martian, which could then be applied to a regular human to make it into a martian.
This is how all our humanoid races currently work.

**Comment by clusterfack** [comment]
New name when

**Comment by Shadowmech88** [comment]
When it bothers more than one person.

**Comment by clusterfack** [comment]
Stolen name, almost copypasted sprite. New name when.

**Comment by invoid9** [comment]
Call them Scootaloos for the memes.

**Comment by ComicIronic** [comment]
New name when.

**Comment by Killette2** [comment]
4 arms = 4 armpits

lewdest race in the game byfar

**Comment by Blithering** [comment]
If calling them martians is a problem, someone suggested Rootmars as the canon name for them. Martians can be still used as a slang term, and noones immershuns are harmed.

**Comment by clusterfack** [comment]
@Blithering you are going in the opposite direction, we don't want them to be identically named and sprited to the source material that inspired it

**Comment by Blithering** [comment]
Why bother obfuscating it? SS13 is already a grab bag of scifi clichés. Arbitrarily renaming everything to distance it from the source material just smacks of the plasma/phoron debate to me.

**Comment by clusterfack** [comment]
Plasma/phoron? How is that related? The original name for plasma is hieng particles.

**Comment by Blithering** [comment]
Its another time when a perfectly serviceable name was re-branded arbitrarily.

**Comment by ComicIronic** [comment]
But this isn't arbitrary: we don't want to copy from the source material. Plasma wasn't copied from anywhere.

**Comment by Shadowmech88** [comment]
Why don't we want to copy from the source material?

**Comment by Blithering** [comment]
> Why don't we want to copy from the source material?

This.
Also martians is a very generic term.

**Comment by ComicIronic** [comment]
> martians is a very generic term.

And yet combined with the sprites it's a reference, so what's your point

> Why don't we want to copy from the source material?

Because we are making our own game.

**Comment by AutismSpider** [comment]
was going say name them ocotillo but that's a type of plant.How about Sepiida or Octopodiformes??

**Comment by Shadowmech88** [comment]
> Because we are making our own game.

Why take a stand on martians instead of all the other referential items and mobs in the game, even not counting the stuff added before we forked?

**Comment by Blithering** [comment]
The game is already built on references. As long as they fit the spirit of the game I don't see the problem.

**Comment by ScrambledSteak** [comment]
> Because we are making our own game

Oh boy that's a good laff let me tell ya

**Comment by The-Albinobigfoot** [comment]
We should be cutting back on overt 'references', not adding more and more.

> Why take a stand on martians instead of all the other referential items and mobs in the game, even not counting the stuff added before we forked?

Their time is coming.

**Comment by Blithering** [comment]
Again, I don't see the reason for removing things just because they're a reference.

**Comment by NigglyWiggly** [comment]
> almost copypasted sprite.

I made the sprites by hand using the same palette as the sprites their based on.
The one on the far left though, that's just the basic sprite from metal slug shrunken down, I just did that as a little test thing and it's in no way the 'final design' 

Also there's plenty of good possible names for them if 'Martian' is too basic.
Stuff like: Bolitaenides, Cephalopods, Belemnites, Astrocanthoteuthis, etc, and that's just going off of cephalopod style names, you could easily base the name off of something to do with Wells and War of the Worlds, which the designs originate from

<sub> also I just found out the common octopus is called 'Octopus Vulgaris'

**Comment by Blithering** [comment]
> Octopus Vulgaris

Martian sec officer name right there.

**Comment by Gringonius** [comment]
More memes?
Also they should be some sort of bussed antag, there's absolutely no need for more non-antag races.

**Comment by ComicIronic** [comment]
I support every non-human being antags

**Comment by NigglyWiggly** [comment]
Memes?

**Comment by Iamgoofball** [comment]
those are the martian sprites from goon tho?

**Comment by NigglyWiggly** [comment]
But they are not

**Comment by Kurfursten** [comment]
Clearly they should be called Octodads.

**Comment by clusterfack** [comment]
Octopussy

**Comment by Arthurdentist** [comment]
Octopus Antags or Octotags

Nobody suspects a thing

**Comment by 9600bauds** [comment]
Word of warning, I'm currently unfucking all of stripcode and a lot of inventorycode, so don't touch that yet unless you like conflicts

**Comment by The-Albinobigfoot** [comment]
@9600bauds please god, I already lost one PR to conflicts, don't do this to me.

**Comment by clusterfack** [comment]
We're going to build a wall of conflicts and make Mexico rebase for it

**Comment by AutismSpider** [comment]
So the suggested names have been
>Scootaloos
>Rootmars
>Sepiida
>Octopodiformes
>Bolitaenides
>Cephalopods
>Belemnites
>Astrocanthoteuthis
>Octodads
>Octopussies
>Octotags
>Ocotillo

**Comment by Gringonius** [comment]
> Scootaloos

Yes, that's perfect. Throw all other suggestions in the bin.

**Comment by NigglyWiggly** [comment]
I feel like we should be talking about things other than their name; for now, I'm just gonna call em martians.

When they die, should it be in spectacular fashion, a la Metal Slug: ![](http://a.deviantart.net/avatars/m/e/methylky06.gif) <sub> ignore that dumb 'epic fail' thing, it's the only version of the gif I could find </sub>
Should Martians be clonable?
Should they be able to wear uniforms at all? Suits? Hats?
Should they be space-proof, or able to become space-proof?

**Comment by Blithering** [comment]
Personal opinions: 
Ability to wear hats is a must, for identification and fun times if nothing else. Traditional jumpsuits and the rest wouldn't work too well, but possibly a back slot or some kind of equippable lanyard for ID.
Spaceproofing should be limited to genetic powers and pods. Maybe make a martian minipod along the lines of the metal slug UFOs for space trips. 
Definitely the spectacular death scene, but have their DNA able to be extracted from remains somehow, or just put the focus on backups.

**Comment by ihadtoregisterforthis** [comment]
No need for pocket slots when they have enough arms for it.

**Comment by NigglyWiggly** [comment]
Martians die and puke up all their blood and their skin melts off leaving a skull.
Place skull, skin, and blood in microwave, press 'popcorn' button, and wait two minutes.
When the microwave dings, you can now retrieve your fresh martian, allow it to cool for at least 3 minutes.

**Comment by ihadtoregisterforthis** [comment]
Make it a Mancrowave
B^y

**Comment by Kurfursten** [comment]
The hand situation is a little weird because pockets make it so that humans functionally have four hands already. The difference is that

> Martians can hold bigger things in other hands
> ...but those things can be dropped if knocked over
> ...but those things are shown in-hand by sprite and not concealed from examination

So already the four arm advantage is basically balanced out already.

But let's say they just get hat slot, ID slot, earpiece slot, backpack slot, and four arms. That means...

> Can't wear gloves, so completely useless for engineering, virology, xenoarcheology; not useless but really bad for janitor, botany, and detective (can't replace lightbulbs, can't touch thorny stuff, will leave prints on everything)
> Can't wear a suit, double useless for engineering and xenoarch, but also mining, paramedic and poor for security (can't wear armor/store weapons in suit slot for quick access)
> Can't wear shoes, triple useless for engineering but also paramedic and janitor (glass shards!)
> Can't wear glasses, so quadruple useless for engineering and double for mining (meson scanner)
> No Asimov protection, so poorly suited for security, command, or robotics
> No jumpsuit and mask, so very poorly suited for mime and clown (also no clown shoes!)

That's not to say they couldn't function in some capacity. Four arms would help in the kitchen, bar, surgery, or chemistry. You wouldn't suffer any innate penalty for being a cargo tech/QM, librarian, geneticist, plasma researcher, or xenobiologist. So there is some niche there. But you need to think about which jobs you're locking a race out of when you restrict the items it uses.

**Comment by Arthurdentist** [comment]
I don't think all races have to be 100% balanced. I think if you are gonna play as a 'martian' then you should expect to face a lot of difficulty working on a station designed for humans by <s>humans</s> autistic crab robots.

The fact that they would be shit at specific jobs and perhaps even incapable of doing them doesn't strike me as a necessarily bad thing. This is ostensibly a role playing game after all. If people joining jobs they couldn't possibly hope to do became an issue you could species restrict them from those roles.

**Comment by AutismSpider** [comment]
Eh being shit at  space base jobs is fine to me.

They make good medbay/sci works/chefs etc though.

Be funny to see how fast they can do surgery

**Comment by Shadowmech88** [comment]
I'd like to see a side-by-side comparison of jobs they can do vs jobs they can't.

It's fine for some jobs to be inaccessible, but I don't think it's a good idea to have a race that can't do a _majority_ of jobs.

**Comment by Blithering** [comment]
Jobs that I can't see being an issue:
Service jobs
Cargo
Scientist (except xenoarch)
Medical (except paramed)
RD
HoP
IA/lawyer
Janitor
Mechanic

Jobs that might be a bad idea, but could work as a gimmick:
Security
Theatre staff

Jobs that would most likely be out:
Mining
Engineering
Atmos
HoS
Captain
Paramed

**Comment by NigglyWiggly** [comment]
We could make a space-proof helmet for martians that is essentiall a big glass dome over their head.
That'd be cute.

Also, what kind of benefits should martians have, if any?
4 arms is a given, possibly 6?
Maybe immunity to toxins or something, though I would want them to take a ton of toxins damage just because of War of the Worlds 
Should they still fall over and hurt themselves by walking on glass shards? If they can never put on shoes, I imagine this would get rather annoying really quickly.

**Comment by Blithering** [comment]
We already have a toxins immune race, so a race extremely vulnerable to them would be fun. Immunity to stepping on glass seems a good idea. Maybe more stable as a whole due to the number of 'legs'?

**Comment by NigglyWiggly** [comment]
I think it'd be neat if they were really hard to knock over in general, but that'd negate the whole 'if you fall you drop all your stuff' thing

**Comment by Blithering** [comment]
I'd like to see them have some ZAS resistance, but still able to be slipped or shoved.

**Comment by AutismSpider** [comment]
Weak to toxins can safely walk on glass shards much harder to knock over by ZAS/be shoved over?

**Comment by Brolaire** [comment]
How's this?
- 6 Arms
- 2 Legs
- Can wear shoes
- Can wear masks/hats
- Can't wear anything else

This would mean they could also walk over glass shards and such. Six hands means they could permanently hold a PDA/ID in one hand, a walkie talkie in another and a plastic bag in another while still having three free hands, however they have no "safe" slots for high-value items. For example if SecOff Octopus Vulgaris gets slipped he drops all of his security gear. On the other hand if he's a magboots-wearing squid he can batoncuff five greyshits at once.

**Comment by AutismSpider** [comment]
Why not spawn them in with custom hat that holds the ID/PDA?

hat that only fits them (and mommis) they have huge ass heads

**Comment by ihadtoregisterforthis** [comment]
They should be able to wear hats, and maybe glasses.

If the slipped/rest sprite isn't just the octopus 90° to the left, that would be great.

**Comment by NigglyWiggly** [comment]
I'd love to make a sprite of them with the tentacles all splayed out but I imagine it'd be more than 32 pixels wide

**Comment by ComicIronic** [comment]
I think a belt might be the best thing, it's not too strong but it'll be required for some jobs and it can fit over their hump.

**Comment by clusterfack** [comment]
Masks, hat, ears, shoes and 4 arms and nothing else

**Comment by 9600bauds** [comment]
ID slot PLEASE

**Comment by AutismSpider** [comment]
Eh not give them belt slot for holding the pda/id

**Comment by clusterfack** [comment]
Yeah ID slot too, maybe some kind of racial power to not drop things when tipped over to balance it out.

I think people underestimate the power of having many HANDS. That's a lot of backpacks.

**Comment by AutismSpider** [comment]
so give them strong grip makes it harder to disarm things off them/they don't drop off when knock down.

drop all the stuff when hit by stun bolt?

**Comment by clusterfack** [comment]
After all octopuses have those suction cups don't they

**Comment by ComicIronic** [comment]
What's this thing I heard about superglue?

**Comment by AutismSpider** [comment]
@clusterfack they use to grab and taste stuff some have teeth

**Comment by ihadtoregisterforthis** [comment]
They are like jellies more than octopii

**Comment by NigglyWiggly** [comment]
Martians have teeth on the bottom of their skull, and as such, some sort of jaw

**Comment by Shadowmech88** [comment]
> and as such, some sort of jaw

The teeth could be vestigial. Just because their skull has a top row of teeth doesn't mean they have a bottom row anywhere.

**Comment by AutismSpider** [comment]
![the mars people](https://cloud.githubusercontent.com/assets/10268342/15910956/21e0b5ae-2d93-11e6-8f6a-4dcb0d4ad7d4.jpg)

**Comment by Blithering** [comment]
![1465237054526](https://cloud.githubusercontent.com/assets/15067109/15912877/df3e1e44-2dce-11e6-9ea5-c66129458130.jpg)
Martians' favourite food!

**Comment by Blithering** [comment]
I'd say let them drop things when they fall just like everyone else, or it'll take all the fun out of martian tipping.

**Comment by carshalash** [comment]
Have a vote on the serb for names. EZ PZ

**Comment by AutismSpider** [comment]
@carshalash well i save you lot of time Scootaloos win the vote and some one will have shit fit over it

**Comment by carshalash** [comment]
Fuck, you found out my plan.

Get the head chicken to decide.

**Comment by Densane** [comment]
I wish for martians mob, as a whole, to be a slip source, like clown pda length time.

Like if you run over a prone martian you slip on all the speghett slime tenticlas.

A little bit of balance to the fact that one disarm can make them drop everything. If you knock them over and walk over them when trying to loot their stuff that's your fault, and by the time you recover, the martian has as well. 

but that would be kind of abuseable on the martian's side if there wasn't a timer for rest/stand up recovery time to balance the "free slip"

**Comment by Blithering** [comment]
Give martians five grab levels. Passive, aggressive hands, aggressive neck, aggressive everything, and christmas tree lights.

**Comment by NigglyWiggly** [comment]
> Aggressive everything

I know enough about Japanese pornography to say this is a bad idea.

**Comment by Blithering** [comment]
WHEN?

**Comment by AutismSpider** [comment]
never we cant have nice things

**Comment by DamianX** [comment]
Scootaloos exist since #15726
