### ISSUE TITLE
feature request: no free space suits

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#10406]
Vox and plasma men get free space proofing.
This means that in most cases space is an inconvenience instead of danger surrounding the station.

Vox should get air tank holsters that fit into the exosuit slot that can hold an airtank. This means the can be without a suit yet have a fulltank and back pack. The only jobs that get hardsuits round start as vox are engineers, atmos techs, miners, (they need it to do their jobs), and security (needs body armor, normal armor can't hold fulltanks also nonhuman security has it rough because law 2 and law 1). All other jobs don't need and don't get a round start suit.

This doesn't mean that they can't get new suits, let vox traders be able to order vox suits, the brown ones on the outpost, and blank incomplete suits. The blanks can be refitted at the HoP desk to change the job style they are. This would give more use to the vox traders because the only way their brothers from the station can get suits is from them.

Plasmamen should just get a fancy space helmet and a jumpsuit that isn't space proof but prevents them from combusting. Let them wear human suits. Also vox traders can order plasma men blanks as well.

This would mean vox traders have more of a role, HoP gets some (N)HR work besides 'GIB ACCESS', and there are still the fancy job based hardsuits for non humans, only they don't start with them.

**Comment by The-Albinobigfoot** [comment]
It's times like these that I wish I knew how to sprite.

**Comment by 9600bauds** [comment]
But then you would see green Vox skin walking around the station
Ew

**Comment by FudgePucker** [comment]
So they would look alien instead of oddly shaped hardsuits? What's the issue?

**Comment by FudgePucker** [comment]
@The-Albinobigfoot
Only sprites needed is the plasmamen jumpsuits and the airtank harness.

Airtank harness would also benifit humans, have internals that last all round without losing your backpack or needing a hardsuit.

**Comment by Exxion** [comment]
Fun Fact: Duny once removed vox space suits then Pomf himself reverted it
But times change. Maybe if someone does it again it'll stick.

**Comment by Ephx1** [comment]
You need to come up with some upsides then. As of now aside from languages which barely counts, there's no reason to pick them.

Don't say role play because I'll bust a gut laughing.

**Comment by NigglyWiggly** [comment]
Role play.

There do not need to be any advantages.
If you want to play as a bird thing, you can, but it will not be the same as playing as a human.

**Comment by Ephx1** [comment]
Pffffftahahahahaha

No one roleplays

**Comment by NigglyWiggly** [comment]
Then why do people play Vox

**Comment by Shadowmech88** [comment]
For the free space suit, obviously.

**Comment by Exxion** [comment]
<sub>If I'm honest roleplay is why I play a vox</sub>
Honestly, without suits, vox are pretty balanced

Cons:
- Need nitrogen internals
- No Asimov protection
- Inaprovaline is toxic to them and its main function doesn't work (but its lesser-known and arguably better secondary functions do)

Pros:
- CAN obtain slowdown-free magboots and near-ERT-tier hardsuits that only they can wear
- The nitrogen reagent acts as a combination dexalin and weaker antitox that lasts 20x longer per unit
- More kick and bite damage
- Can butcher things with their beak, albeit slower than with a tool (which is pretty useless but cool)
- The language

I think they also have different temperature and pressure resistances than humans, but I can't remember whether they're better or worse

**Comment by Ephx1** [comment]
Oh sorry, they role play as the exact same 
"I am no speeki common gud, yes?"

Stellar roleplay

**Comment by Exxion** [comment]
Many of the newer vox players who started playing vox after traders were added do, yes
Many of the older ones (few of which still play, admittedly) are better about it

**Comment by Ephx1** [comment]
Also I didn't know they had those other things, so I rescind my statement for vox.
I don't know about plasmamen, but they're just a greyshit race so I don't care.

**Comment by Exxion** [comment]
Currently, plasmamen are by far the most OP race

Also, I think if vox don't get free suits, maybe they should get a slight base speed boost over humans
They are stated to be quite velociraptor-like, after all

Actually I'd say do that anyway but make their bones easier to break or something

**Comment by Megamaw** [comment]
@Ephx1 
No one? Speak for yourself.

furthermore, why are vox pressure suits an issue? plasmamen and greys are already far more powerful, so why target vox in particular?

also, this is the perfect time to further my skeleton narrative

If you have a problem with a race that's underpowered, why not just push to have it removed? It's been done before.

**Comment by Ephx1** [comment]
Skeletons were removed for being meme machines, not being underpowered.

Also maybe I was being too harsh when I said no one roleplays, more like 99% of the playerbase doesn't roleplay

**Comment by clusterfack** [comment]
Skeletons were removed for being overpowered, at least primarily

**Comment by Shadowmech88** [comment]
Were they still overpowered even after they were changed to take more brute damage, be unable to eat anything but raw meat, and be unable to use medicine?

**Comment by clusterfack** [comment]
Were those the changes that were made simultaneously with them being removed? If so then I could not say.

They were primarily overpowered for not bleeding and not taking pressure damage in space.

**Comment by ihadtoregisterforthis** [comment]
They were removed at the same time they became unable to eat and have medicines.

**Comment by Megamaw** [comment]
and internally, since then they've been nerfed to shit and back

it was bad enough a skeleton could catch a virus and it would be almost impossible to cure, but now they take way more brute damage (which is fair) and can't eat or drink.

their only advantage over humans was not needing to breathe(no pressure resistance/cold resist, by the way), while a human has ASIMOV on their side, arguably one of the most useful racial bonuses, allowing you to basically open any door you want, and be granted assistance whenever you so much as had a mild inconvenience

saying they could go buck naked in space is a vast overestimation of what they did.

**Comment by Megamaw** [comment]
@ihadtoregisterforthis i remember pretty clearly a few months there where I couldn't process vaccines because >no blood

**Comment by ihadtoregisterforthis** [comment]
Skeletons did and do take pressure damage.

**Comment by Blithering** [comment]
If anything moving to plasmaman jumpsuits will increase the powergaming potential, as they'll then be capable of wearing atmos suits and the CE suit, as well as armours such as ablatives.

**Comment by Ephx1** [comment]
Why not just make the current soft suits they have not work in space?

**Comment by ComicIronic** [comment]
Because plasmen can't wear other suits, so the job-specific ones still need their job specific protections.

**Comment by Ephx1** [comment]
I don't see why the job-specific suits can't start out with protection.

**Comment by ghost** [comment]
Remove the plasmamans suit from having space protection, make the orderable plasmaman crate have a space-proof version of the suit, or an adaptation upgrade.

General tank holsters would be pretty useful for all races, not just vox.

**Comment by FudgePucker** [comment]
I think the alien space suits should be order able from vox traders, that would give them more of a use.
