### ISSUE TITLE
firebirds can walk through bolted doors

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#10417]
#### Description of issue

Firebirds can waltz through bolted doors
#### Difference between expected and actual behavior

Expected: Slam in the door
Actual behavior: IT'S MAGIC AINT GONNA EXPLAIN SHIT
#### Steps to reproduce

Find a bolted door and ride through it.
#### Specific information for locating

![bird](https://cloud.githubusercontent.com/assets/17928298/15818183/3d6f6cbc-2bb2-11e6-9875-0b5ec9a36ab6.jpg)
#### Length of time in which bug has been known to occur

Just discovered this after accidentaly phazing through the research outpost cycling airlock
#### Server revision

bc7fa76ef20b5a399a2d4e5dbcceb27def3b34fa Current Infomational Settings: 
Protect Authority Roles From Tratior: 1
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ x ] Issue happened in a recent (less than 7 days ago) round
- [ x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Intigracy** [comment]
This is intended, they can move through airlocks. It used to include walls but now it's just doors.

**Comment by Shadowmech88** [comment]
Isn't it supposed to be limited to airlocks the player has ID access to, though?

**Comment by clusterfack** [comment]
No because its for wizards

**Comment by jknpj** [comment]
But as @Shadowmech88 said, it can move only though BOLTED airlocks and unbolted airlocks that you have access to. I could not use it to get inside the gooncode satellite with it because i had no access and it was not bolted but i could enter the syndie vault because the airlock was bolted down.

. Access and bolted = move through
. No access and bolted = move through
. Access and unbolted = move through
. No access and unbolted = can't move through

Next time i get my hands in a firebird i'll it inside the station vault.
