### ISSUE TITLE
OFF-HAND as an actual item

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10418]
(WEB REPORT BY: jellyveggie REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> bc7fa76ef20b5a399a2d4e5dbcceb27def3b34fa
> 
> General description of the issue
> Picking up a large animal you previously grabbed results in both markers, grab and pick-up appearing (shouldn't let you pick it up). To add further insult to injury, the off-hand marker for the pick-up can be dropped and treated as an item of sorts
> 
> Steps to reproduce if possible
> With your hands free, and with a dead, large pet (Chickens, Ian) that require both hands to hold:

Grab the animal (grab intent, click on it), an "UPGRADE" appears. 

With the same hand that holds the "UPGRADE", drag the animal towards you (this would usually make you pick up the animal), an "OFF-HAND" appears on your other hand.

Change hands, drop the "OFF-HAND". Play around with it.

**Comment by PJB3005** [comment]
This appears to be the same issue as https://github.com/d3athrow/vgstation13/issues/10404#issuecomment-224567359

@unid15
