### ISSUE TITLE
New character "seeds" have priority antag status

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10412]
Apparently, resetting your character seed such as by changing your hair or name gives you priority antag status. Somehow.
I don't fucking know HOW, and it might just be my luck, but this has happened to me when I was changing my look: I picked Wizard after completing the changes and instantly got Wizard the next shift.

I unlocked Blob a few days later, guess what happened.
Wizard and Blob.
What are the chances?

**Comment by Imagebard** [comment]
Note: People already posted this fact a few times in the thread, so I don't think I'm revealing anything new here.

**Comment by Shadowmech88** [comment]
You sure you're not just getting lucky? One time I managed to get traitor RD four or five times in a row in a single day, without changing my character at all.

**Comment by Imagebard** [comment]
>Traitor

Common as fuck antag.
Try changing seed and rolling for a rarer one.

**Comment by Imagebard** [comment]
I also should mention I rolled nuke ops more often after changing a few things about my character but there are multiple ops so there you go.

**Comment by clusterfack** [comment]
*When people literally bug report rng*

Can you just not

**Comment by clusterfack** [comment]
Then again game modes do have shit code so I admit I wouldn't be surprised

**Comment by clusterfack** [comment]
Nah I checked these are all using pick, literally random chance.

**Comment by Imagebard** [comment]
Well, back to abusing this bug clusterfack insists doesn't exist.

**Comment by ComicIronic** [comment]
Have you demonstrated statistically that this is a bug

**Comment by clusterfack** [comment]
I bet you hold b and down when you try to catch pokemon too you superstitious fuck

**Comment by Imagebard** [comment]
If this is placebo then its a pretty strong placebo.

**Comment by Imagebard** [comment]
What the fuck do you mean you didn't hold down B
Did you really squander your chances

**Comment by ComicIronic** [comment]
If it is a bug, it's most likely to do with how Byond handles RNG.
