### ISSUE TITLE
Plasmaman prisoner suit.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#10410]
Once again the issue of plasmaman balancing has been raised. A lot has been said about it, and I'd rather keep it contained on the other issue, but a good idea was made. 
![plasmaprisoner](https://cloud.githubusercontent.com/assets/15067109/15807306/a52ef5a8-2b52-11e6-9a53-6999d6320506.png)
Plasmaman prisoner suits, non spaceworthy suits to stop plasmamen from breaking out of perma, while also stopping them combusting.

Download link for icons: http://s000.tinyupload.com/index.php?file_id=05143583065231648299

Update: alternate helmet with transparent faceplate added.

**Comment by The-Albinobigfoot** [comment]
Are you planning on making a full set of sprites?

**Comment by ComicIronic** [comment]
In what way are they non-spaceworthy

**Comment by Blithering** [comment]
I would assume they'd have zero pressure or cold resistance. I can only provide icons though so that's not for me to say.

**Comment by 9600bauds** [comment]
They have really crappy seals that only work when the pressure inside the suit matches the atmosphere outside.
There, happy?

**Comment by 9600bauds** [comment]
Or alternatively they have zero insulation so if the prisoner goes out into space he freezes immediately

**Comment by Blithering** [comment]
Hell, give them negative insulation, bullshit in that they cheaped out and went for air cooling.

**Comment by The-Albinobigfoot** [comment]
> air cooling suits on race that combusts when exposed to oxygen.

Hello?

**Comment by FudgePucker** [comment]
They would need to replace the suits themselves, they can have a belt hidden.

**Comment by Blithering** [comment]
@FudgePucker Not sure what you're trying to say there, but belts show up over all exosuits.

**Comment by FudgePucker** [comment]
Oh right.
But still, you can't take off the suit without causing them to catch on fire while you put on the suit, put on the plasma tank, and then turn on their internals.
Letting them put on their own suits means the opportunity for a disarm shove.

**Comment by jknpj** [comment]
They take a while to die due high burn resistence. you can switch suits and put their internals safely.

**Comment by AutismSpider** [comment]
Take ages to die form any type of heat or burn damage.

Taking the suit off for a bit not going kill them or hurt them badly

**Comment by 9600bauds** [comment]
It's perfectly safe to rip their suit off, dick around for a little and then put it back on

**Comment by Gringonius** [comment]
Vox could use a similar suit since they also always need a tank if held in perma.
But then, gas meme.
Actually I misread and realized the suit is simply not space-worthy. Why not make the suit lock a gas tank in suit storage so the prisoner can't use it as a weapon? But then perma has plenty of things to hit glass windows with.
Can vox still break windows with nothing but their talons?

**Comment by 9600bauds** [comment]
You can break windows with literally any object in the game including your prisoner jumpsuit

**Comment by Shadowmech88** [comment]
> You can break windows with literally any object in the game including your prisoner jumpsuit

Maybe regular windows, but not reinforced windows.
I see prisoners constantly attempt to break out of the brig by hitting the windows with their shoes, to no avail.

**Comment by 9600bauds** [comment]
They gotta throw them, not whack with 'em

**Comment by Megamaw** [comment]
> plasmamen 3rd most powerful race in the game
> give them more content
> ???

**Comment by 9600bauds** [comment]
It's content to make them less powerful.
Just curious, what are 1st and 2nd?

**Comment by Megamaw** [comment]
I'm still trying to figure out how to rank them, but humans, greys, and plasmamen are all roughly the same in strength, in my humble opinion.

**Comment by Shadowmech88** [comment]
Overall, or in combat?

**Comment by Megamaw** [comment]
Overall. The three of them have very pronounced, distinct advantages over anything else. Humans have a very powerful racial advantage(most powerful?), but no disadvantage, so I generally put them as the most powerful.

**Comment by AutismSpider** [comment]
find it funny i can take full cap laser to face as plasma man and walk it off like nothing.

**Comment by Blithering** [comment]
Please don't let this devolve into more of the same thing we saw in the goodbye sawbones PR. Yes plasmamen are resistant to burn damage, but this issue isn't about that.

**Comment by The-Albinobigfoot** [comment]
> devolve

What are you trying to say? We had an excellent debate in the PR.

**Comment by Blithering** [comment]
Yes, a wonderful time was had by all, but I'd rather find someone willing to code fashion station 13 in this particular one.

**Comment by AutismSpider** [comment]
not just lasers i can take 100mw shock to the dick and walk it off.

any thing less would kill the other races easy

**Comment by Blithering** [comment]
Yes okay, burn damage as a whole affects them to a lesser degree than races not made of extra-crispy bacon.

**Comment by The-Albinobigfoot** [comment]
You do know I added these suits right before I closed the PR, right? I could get the code and sprites for them and make a PR just for this.

**Comment by Blithering** [comment]
@The-Albinobigfoot  That would be nice.

**Comment by jknpj** [comment]
@AutismSpider, Dionaes can safely take an unholy amount of cult sword slashs in the head( even unarmored), go braindead while goliaths smash them and even summon (and keep) an almost unlimited number of manifested ghosts. Their bleed is also purely cosmetic and they take 50u pills of Hyperzine to keep going fast the whole shift. 

I understand being upset because they take almost no burn damage, but that's their racial trait. They do have several drawbacks but that simply don't balance things, yet. Removing their space-worth suits(at least when they are being kept inside perma) is a good step to solving their problem.

**Comment by Blithering** [comment]
Closing as https://github.com/d3athrow/vgstation13/pull/10415 was merged.
