### ISSUE TITLE
pAI icons seem to be fucked up.

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#10411]
Using the pAI screen display doesn't actually change the icon.
When you right click the pAI, you can see the proper icon, but you can't see it on the item itself normally.

Dunno what could have caused this, but I didn't see any other people reporting it

**Comment by ComicIronic** [comment]
Did you update Byond

**Comment by clusterfack** [comment]
What is your byond version niggly

**Comment by NigglyWiggly** [comment]
I just updated.
I'll see if it's better now and close this issue if it is

**Comment by clusterfack** [comment]
>What is your byond version niggly

GODDAMNIT NIGGLY YOU HAD ONE JOB

**Comment by NigglyWiggly** [comment]
> implying I would actually check

It's good now
