### ISSUE TITLE
bar stools have no in hand sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10413]
(WEB REPORT BY: cumoverme REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e8432f9aadc20196a267dcf3c0058da3c50cdd0e
> 
> General description of the issue
> Unlike normal stools, the fashionable ones in bar have no in hand sprite.

**Comment by Killette2** [comment]
IC in OOC, round's still going and I now know the best way to murder my target, and know he's carrying an invisible barstool.

**Comment by ghost** [comment]
Oh dear, aren't bar stools children of regular stools ? They should inherit the in-hand sprite

I'll take a look at it
