### ISSUE TITLE
Goonlights are rainbow colored

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10419]
(WEB REPORT BY: jellyveggie REMOTE: 172.93.109.202:7777)

> Revision
> bc7fa76ef20b5a399a2d4e5dbcceb27def3b34fa
> 
> General description of the issue
> Lighting tiles show as "rainbow" squares, where corners are (clockwise from upper right) black, green, red and blue regardless of enviroment (lit, dark, computer lights).
> 
> What you expected to happen
> For there to be "normal", goon-like lighting (smooth shadows, light tint, etc), just the way it worked like yesterday (for me, at least)

**Comment by ComicIronic** [comment]
Update your drivers.

**Comment by PJB3005** [comment]
If that doesn't work go to the BYOND forums saying that colour matrices are failing to render.

**Comment by ghost** [comment]
Didn't need to start a thread:
http://www.byond.com/forum/?post=2085297&hl=color%20matrix

Issue seems to be with DirectX, andd, as suggested in the thread, installing DirectX's SDK seemingly fixed it, miraculously.

 (Sorry Clusterfack, I didn't even know the SDK was a thing)

**Comment by PJB3005** [comment]
Gonna close it then.
