### ISSUE TITLE
Everything about MEGAMADCRAB is hilariously broken

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10427]
For those who don't know, using wirecutters on a crab has a 50% chance to instantly kill it, and a 50% chance to turn it into a MEGAMADCRAB, a very strong and angry crab. It is broken in just about every way you can imagine.
1. The living and dead sprites for MEGAMADCRAB are exactly the same, and neither is a crab. In fact, they are both naked white human males.
2. MEGAMADCRABs are not actually hostile.
3. You still have a 50% chance of killing them instantly with wirecutters, making them a negligible threat even if they did actually attack you.
4. If you examine them, your client freezes for a moment and the examine icon is horribly distorted, just like #10053 (@PJB3005)
5. Despite there being several different crab appearances, all of them turn into the same sprite. Which would be bad even if that sprite were a crab.

As an added bonus, if this DID work properly, wirecuttering Norris repeatedly would turn him into an unstoppable murder machine, because he revives to full health a few seconds after dying.

**Comment by ComicIronic** [comment]
What
why

**Comment by Exxion** [comment]
Oh look you can even wirecutter dead crabs to turn them into MEGAMADCRABs, and it revives them
And wirecuttering an already dead MEGAMADCRAB can revive it
I think whoever coded this was drunk

**Comment by ComicIronic** [comment]
This has been in the code for FOUR YEARS

**Comment by Exxion** [comment]
Also, as if the game knew what I was going to test, the randomly-generated station name I got when I went to experiment with MEGAMADCRABs was Crab Station Whiskey

**Comment by Imagebard** [comment]
What the fuck is this feature
WHAT THE _FUCK_ IS THIS FEATURE
WHAT THE _HELL_ ARE YOU TRYING TO TELL ME WITH THIS?
**WHAT THE FUCK _IS_ A MEGAMADCRAB?**

**Comment by AutismSpider** [comment]
meme base off this kills the crab.

**Comment by AutismSpider** [comment]
Just fix the icons/AI or use old clockwork cult mommi for the mega crab mode

**Comment by ghost** [comment]
This was Niggly's first attempt at coding IIRC

**Comment by clusterfack** [comment]
![killcrab](https://cloud.githubusercontent.com/assets/8516830/15840271/6e154ed4-2c0e-11e6-9284-e341206f52d9.jpg)

**Comment by AutismSpider** [comment]
Well its AI does not work and its missing the mad crab icons

**Comment by Praecordia** [comment]
we should leave it in and act like it's intentional

**Comment by AutismSpider** [comment]
oh its just wrong icon names etc.

Icon for mega mad crab is call evil and but it calls for mad crab

**Comment by ghost** [comment]
Wrong .dmi as well, it goes to /mob/mob rather than /mob/animal

Which would be the same icon file as it was, what the hell Niggly?

**Comment by Exxion** [comment]
It wasn't Niggly, this code predates our fork from Baystation but it was commented out at the time we forked

**Comment by AutismSpider** [comment]
Should be easy fix the icon was found in game (black crab with red eyes etc)

**Comment by Probe1** [comment]
> WHAT THE FUCK IS A MEGAMADCRAB?

**Comment by Praecordia** [comment]
@Probe1 at least it's not a _megamagmacrab_

**Comment by Exxion** [comment]
Hold on it even predates Bay's split from /tg/
Who uncommented it and also what the fuck

**Comment by Imagebard** [comment]
>Hold on it even predates Bay's split from /tg/

![1444540827465-1](https://cloud.githubusercontent.com/assets/7571238/15840608/580d480e-2c21-11e6-8e14-367dfbb4a87c.png)

**Comment by AutismSpider** [comment]
Welp we gone ♂Deep♂ we fix it or take it out for good.


Icons work fine its just red eyes black crab

**Comment by Praecordia** [comment]
> Hold on it even predates Bay's split from /tg/

![1460077810181](https://cloud.githubusercontent.com/assets/8294408/15840640/2449b15e-2c19-11e6-8c0f-e2b36e5acfdd.gif)

what the fuck is this thing
how has it been lying undiscovered for this long

**Comment by Exxion** [comment]
It was commented out for _years_ and I still haven't quite found when exactly it was uncommented, or by whom

**Comment by Exxion** [comment]
IT WAS POMF
6ad9e743d0b279a4ac488cb84ddf04e467e52f33

**Comment by Shadowmech88** [comment]
We need to fix it and buff it.
Turn it into the eldritch forgotten code beast it was always meant to be.

**Comment by NigglyWiggly** [comment]
We aren't supposed to talk about MEGAMADCRAB.

Just forget it ever existed.

**Comment by ghost** [comment]
We can't, it got so mad it crashed the server.

**Comment by AutismSpider** [comment]
only does 5 damage has 100 hp.

make it do 10 to 15 and have 300 hp+add crab sounds

https://www.youtube.com/watch?v=qWgDGHUvPQ0

@NigglyWiggly its to late we found it and now we have to fix it it crash the damn serb

**Comment by TheEliminator16** [comment]
What the absolute fuck
![1459830918175](https://cloud.githubusercontent.com/assets/8118771/15840859/13dadc3a-2c0a-11e6-8cad-e24fc27b60e3.gif)

**Comment by ghost** [comment]
Hang on, I'll get it fixed.

Are we going with the red eyes black crab icon, or should we go with something a little crazier?

**Comment by AutismSpider** [comment]
Red eyes black crab is fine unless some one wants make new icon for.

Buff its hp and damage up a bit

**Comment by Exxion** [comment]
How in fuck did it crash the server?
I'd check the logs but even they're down

**Comment by AutismSpider** [comment]
like five of them were made as we ask admins to test this.

i think the serb shit the bed with how buggy they were

**Comment by ghost** [comment]
I need angry crab sounds, fast

**Comment by Exxion** [comment]
https://www.youtube.com/watch?v=dTKhOvBNakM

**Comment by AutismSpider** [comment]
https://www.youtube.com/watch?v=t4enrU2BMpI

**Comment by ghost** [comment]
It's 20 to 1, and I'm lining up crabs to kill with wirecutters, in hopes that one becomes an evil eldritch abomination from code long lost.

This is the life.

**Comment by FudgePucker** [comment]
> this PR

The crab is my favorite pet.
I knew about the MEGAMADCRAB from reading the code.
Never could bring myself to kill the crab.

**Comment by Exxion** [comment]
@Skullyton Just snip the same one over and over
Snipping a dead one can still MEGAMADCRAB it and revive it

**Comment by ghost** [comment]
I kinda fixed that.

Can still bully norris with it though, because he just sorta regenerates

**Comment by Exxion** [comment]
Oh OK you already fixed it
And yeah, perhaps Norris shouldn't become a MEGAMADCRAB because he'd become UNSTOPPABLE

**Comment by ghost** [comment]
Mega Mad crab no longer inherits regeneration, it's a completely new mob so it can actually turn hostile.

Speaking of which, let's move this party over to https://github.com/d3athrow/vgstation13/pull/10428

**Comment by FudgePucker** [comment]
Wait isn't Norris the one on the beach?
Wouldn't that mean it would be end round anyways or something of the sort?
Keep it in, the first creature they meet in the alternative universe after fleeing from the super matter cascade, and they kill it with wirecutters? They should have to deal with the final boss of the universe.

**Comment by ghost** [comment]
Worse, Norris is a crab based off the head form of 'The thing', and it's located in xenobiology, and it regenerates.

Coffee is the crab at the end of the universe.

**Comment by NigglyWiggly** [comment]
> Norris regenerates

Wait what?
I didn't do that, did someone else code that?

**Comment by Exxion** [comment]
Yes
It was added along with the ability to make mobs regenerate, I think

**Comment by TheEliminator16** [comment]
> the ability to make mobs regenerate

Wait was that not something they could do before?
I made cyber horrors do that

**Comment by Exxion** [comment]
As in from death

**Comment by TheEliminator16** [comment]
Ah gotcha

**Comment by NigglyWiggly** [comment]
Oh, #9619.

That explains why the fucking zombie on Deffic keeps coming back to life and murdering everyone
