### ISSUE TITLE
Make xenos and manifested ghosts immune to chloral hydrate.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10426]
As it stands a single human with multiple syringes, injectors or the dreaded hypospray can single handedly kill entire armies of these two creatures, this is even more guaranteed when they are under the effects of creatine and a little armor so even if they don't get the first hit they cannot go down.

I find it specially silly against manifested ghosts who aren't even really meant to be living organisms so there shouldn't be metabolization of the sedative to begin with.

There's certainly some balancing needed here.

**Comment by AutismSpider** [comment]
keep it for manifested ghost they happen to be walking hulks who cant be stun and cant go into crit.

**Comment by Allspice** [comment]
Only if you take away facehuggers going through helmets first.

**Comment by ghost** [comment]
They bounce off of hardsuit helmets

**Comment by Allspice** [comment]
Except when they rip the things off and rehug.

**Comment by AutismSpider** [comment]
walking into nest of facehugger will get you killed helm or not.

**Comment by kernikov** [comment]
Yea to ghosts
Nay to xenos

**Comment by Megamaw** [comment]
make xenos immune. last i checked they need the buff.

**Comment by 9600bauds** [comment]
Manifested ghosts need a serious rebalance last I checked

**Comment by AutismSpider** [comment]
Xenos should be only one immune to chems manifested ghost no.

you can endless shit out ghost the damage the rune does is a joke.

picks random limb and does dilly dick for damage to it by the time next tick comes by you heal it any way

**Comment by Kurfursten** [comment]
While I agree manifested ghosts are strong, I also think chemicals affecting ghosts is dumb. Especially sleep chemicals. For ghosts. Come on guys.

How about instead someone adds a more immershuns way of killing them, like they take massive damage from holy water instead? There's a more reasonable chemical for the job and even promotes fun fire extinguisher spam guaranteed to kill at least one grey somewhere down the line.

**Comment by AutismSpider** [comment]
the cult robes and shit will block the holy water unless you force feed it to the ghost.

you be dead in three hits trying that any way

**Comment by Kurfursten** [comment]
Or unless you deliver it in the same way you deliver chloral to ghosts now (hypo, syringe gun, etc.)

**Comment by AutismSpider** [comment]
five units better do massive damage vs 30+ cult blade damage on top of the bleed and bone busting it does

**Comment by Kurfursten** [comment]
No reason holy water couldn't just dispel the ghost entirely on contact. After all, chloral effectively does the same thing, right?

**Comment by AutismSpider** [comment]
got do 200+ damage to kill the ghost they don't go into crit like other human mobs.

**Comment by Gringonius** [comment]
Manifested ghosts could get a big nerf to their health. After all it's very easy for a dead ghost to just jump back to the summoner and come back. Getting an armor rune is usually the real bottleneck for ghost armies and even naked disarm spamming while running in groups would be a valid strategy.

Players playing xenos, on the other hand, once dead often compete with the other ghosts for the handful of infected players/monkeys and need to wait to mature on top.
But this is getting a bit off-topic, unless we make this issue also about general manifested ghost re-balancing.
