### ISSUE TITLE
Rework blob random events to have 2 overminds max jesus christ

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10421]
1 Join game
2 See people get annihilated by even 1 blob
3 Realize its fucked to have 4+ blob overminds simultaneously when 1 can end the round.

**Comment by Megamaw** [comment]
Try playing better.

**Comment by NigglyWiggly** [comment]
> He doesn't like having 4+ blobs simultaneously impacting the station and killing everything

**Comment by Megamaw** [comment]
okay but to be more serious, the idea is that you have to start dealing with the blob before it gets out of control, i think

if you start attacking it and it already has 4 fucking overminds, you have probably fucked up

**Comment by NigglyWiggly** [comment]
I think you might be misinterpreting the issue.

It's not that one blob got very large

it's that multiple blobs can spawn at the same time with the blob-meteor things

**Comment by Megamaw** [comment]
oh, i haven't seen that random event
4 to start with? jesus. that's intense.

**Comment by ghost** [comment]
What worries me is that a single overmind can make another in about under 4 minutes (From what I've seen?)

That's a serious buff from what it has been

**Comment by Kurfursten** [comment]
It's weird that you made a new issue because I remembered you commenting on the previous one

Identical to #10217

**Comment by Gringonius** [comment]
More than two overminds? Jeez.
I was about to comment on how blobs from clusters have their cores always next to space making them easy pickings for people with lasers and hardsuits but you do have a point that as long as one blob plays decently and the crew is busy with the other new overminds are likely to be made.

Yesterday I was assigned to a blob that landed right on cargo, no one could reach the 22 energy guns that had been ordered, that's the only case I can predict event blobs getting easy wins with a limit of one or two overminds per event.

**Comment by Probe1** [comment]
Issues will continue to be made until someone that knows what they are doing spends 30 seconds to fix it.  

If an admin spawned 4 blobs simultaneously they'd be yelled at.  If they did it every week they'd be deadminned.

This code is fucked.  Fix it.  It's an automatic round ender.

**Comment by clusterfack** [comment]
Do it and I'll ban you you double bigger.

**Comment by clusterfack** [comment]
Nigger

**Comment by ghost** [comment]
Headmin versus Head Collab

Who wins? Nobody

**Comment by Probe1** [comment]
He does have a reasonable point that it is a duplicate issue.

I hope this gets fixed soon.

**Comment by clusterfack** [comment]
If I was on my computer and you reminded me in IRC I would have done it already.
