### ISSUE TITLE
Head swapping language phenomena

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10424]
#### Description of issue

If you swap somebodies head who knows one language (Say, only grey) to the body of somebody who knows other languages (Tradeband, gutter, common, etc.) you'll lose grey, and gain the languages of the body you just acquired.

You'll also 'assume the identity' of whomever you got the body of, as your spoken name will now be theirs.
#### Difference between expected and actual behavior

Expected - Be able to speak my native tongue after a headswap

Actual - I am now a different person
#### Steps to reproduce

A seriously weird round
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Identity is, for some reason, tied to the torso of a mob instead of its head/brain.
I imagine languages are as well.

**Comment by ComicIronic** [comment]
Yes, this is an extension of a known bug which I believe there is already an issue for.

**Comment by clusterfack** [comment]
Yeah identity is pretty warped, reminder to all the fixer of this bug that separating spells/powers between mind and body identities should be a related fox

**Comment by DrCelt** [comment]
@clusterfack

A related fox?

**Comment by ghost** [comment]
yay
