### ISSUE TITLE
Surgical switchtool funny goings on

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10422]
#### Description of issue

When you attempt to put a deployed surgical switchtool onto a table, it puts the deployed tool (for instance, if you were in cautery mode, it'd put a cautery on the table), the switchtool would remain in your hands, and undeploy itself.

The lost tool that had then been put onto the table was lost from the list of possible tools usable by the switchtool.
#### Difference between expected and actual behavior

Expected - For it to remain deployed and put on the table

Actual - I lost a tool from my compact tool-carrier
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by NigglyWiggly** [comment]
I think you can put tools back into the switchtools, but it might require a screwdriver or something

**Comment by ComicIronic** [comment]
You can put tools back into the switchtools, and it should only require slotting them in, from memory. A screwdriver is used to remove the tool. Switchtools are meant to avoid exactly this dropping behaviour, though, so something has changed since last year.

**Comment by ComicIronic** [comment]
Also where did you get a switchtool

**Comment by ghost** [comment]
It was spawned in for a bus, but you can get them from protolathes if you have the relevant research if that helps anything.

**Comment by Kurfursten** [comment]
Skully is right, Bus has a single switchtool in the storage room as a 'bonus' for not being on Box.

**Comment by ghost** [comment]
Not bus as in the map, bus as in badmin shenanigans

**Comment by Kurfursten** [comment]
You know I named it Bus for that very reason

I should have known I would regret this pun

**Comment by ghost** [comment]
Honestly thought it was called that so people would accidentally vote for it thinking it was box station

**Comment by Kurfursten** [comment]
If I wanted to that I'd have named it Buxstation and left money everywhere on the floors. Have a little more faith in our players.

Anyway, I was able to reproduce the bug on the test server with a sandbox-spawned switchtool, but I was also able to simply re-insert the lost item, so that's behaving normally.

**Comment by FudgePucker** [comment]
> Have a little more faith in our players.

top
kek

**Comment by Shadowfgt** [comment]
I know that not just the switchtool does this. If you activate your pda's atmos scanner then click on a table the scanner will appear on the table. You can even teleport it around by click on other tables with your pda.
