### ISSUE TITLE
Can't Wrench Down An Unsecured Grinder

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10436]
When I use the wrench on it, it says "Cannot refine into a reagent."
I was able to unwrench it just fine.

**Comment by ComicIronic** [comment]
What

**Comment by Shadowmech88** [comment]
It had no power at the time I unwrenched it, if that matters.
It also had a beaker loaded as well as some meat.

**Comment by Imagebard** [comment]
_???_

**Comment by clusterfack** [comment]
Check if the reagent check is before 

If(..()) return 1

**Comment by 9600bauds** [comment]
Could not reproduce after trying every combination possible of power, beaker, and items loaded
