### ISSUE TITLE
Engineering borgs can't disassemble disposal bins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10433]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 27c61d88e475f3aa8303524f34e520027ae49562 
> 
> General description of the issue
> Engineering cyborgs can't take apart disposal bins
> 
> What you expected to happen
> To turn off the pump, screwdriver the electronics, welder wrench to disassemble
> 
> What actually happened
> No reaction to screwdriver
> 
> Steps to reproduce if possible
> Be an engineering cyborg, try to take apart disposal bin

the problem is at
/code/modules/recycling/disposal.dm
line 84

**Comment by AlphaBuffalo** [comment]
I thought you need and RPD to destroy the bins, and to make the bins. Dont you have to just wrench, unweld, and RPD to destroy

**Comment by AutismSpider** [comment]
got use rpd to destroy the bins after you unbolt them form the floor

**Comment by ComicIronic** [comment]
So, not a bug?

**Comment by Exxion** [comment]
No, they're just wrong
Look in the code where the OP says and you'll  see the problem

**Comment by Intigracy** [comment]
Destroy =/= disassemble jesus christ.

For disposal bins you have to wrench then weld it to put it down, but to remove it you have to turn the pump off, screwdriver it, then weld wrench.

The issue is it's not letting borgs screwdriver.

**Comment by Exxion** [comment]
Even if it did, it wouldn't let them do the other steps, because `attackby()` just returns before doing anything if the user is a robot and not a MoMMI
This was presumably done to keep them from dropping their modules in disposal bins, but that check is _probably_ not necessary anymore after the superglue update/dropping refactor

Even if it is still necessary, it should have always gone at the end _after_ all the specific item checks

**Comment by AlphaBuffalo** [comment]
Thats counter intuitive, use the screwdriver to remove when you never screwdrived to place. But if you cant use the screwdriver then it is a bug

**Comment by MercuryDoll** [comment]
Screwdriver's to open maintenance hatches for disassembly. Pretty much any machine does it this way.

**Comment by AlphaBuffalo** [comment]
I see what you mean, but if you build one then destroy it, your most likely to use the welder first since that was the last step to place it, just like a screwdriver is last step to build a machine  and first to decon
