### ISSUE TITLE
BB code when Writing on Paper

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10435]
(WEB REPORT BY: ro5490 REMOTE: 172.93.109.202:7777)

> Revision 27c61d88e475f3aa8303524f34e520027ae49562
> 
> General description of the issue
> Paper BB code wont load.
> 
> What you expected to happen
> Text to work properly
> 
> What actually happened
> you get the [center] things instead
> 
> Steps to reproduce if possible
> paste into textbox when writing on paper

[center][large]General Request Form[/large][/center]
[br]
[br]
[list]
[_]Full Name: [small][field][/small][br]
[_]Request: [small][field][/small][br]
[*]Reason for request: [small][field][/small][br]
[/list]
[br][br]
[u]Sign Below[/u][br]

**Comment by PJB3005** [comment]
Dupe
