### ISSUE TITLE
grief with cups of water, skeletons are back baby

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10438]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8829b602feaf92867f4a3da5246b940f312e6f69 
> General description of the issue
> As a skeleton, you can drink cups of water and make the tile you're on slippery, without any of the water being removed from the cup.
> 
> What you expected to happen
> To drink the water, have it fall through me, and go from 50u in the cup to 40u
> 
> What actually happened
> I stay at 50u in the cup and can make EVERYTHING slippery
> 
> Steps to reproduce if possible
> Roll skeleton
> get a glass of water
> drink
> make the entire station slippery with only 10u of water

**Comment by Megamaw** [comment]
Skeletons are back?

**Comment by Megamaw** [comment]
also gosh i never thought not being able to eat would break several things

(i am not good at internet sarcasm but that is one)

**Comment by Imagebard** [comment]
Genetic Power 『Dissolve』 can make you a skeleton

**Comment by Megamaw** [comment]
ok yes i know this, but usually i don't have 20 minutes to dick around with the 『Bow and Arrow』

the title was misleading is what i'm getting at but yeah this is a pretty big issue

**Comment by Gringonius** [comment]
> but usually i don't have 20 minutes to dick around

So dick with it in one or two like anyone with mutagen smoke.

**Comment by SangriaMonkey** [comment]
> he didn't try this with a glass of lube

wasted potential
