### ISSUE TITLE
Cannot place glasses or shakers into booze dispensers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10431]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I want to dispense a nice glass of (your favourite drink) but I cannot place a glass into the damned machine! Have to use a bucket or beaker like a clumssy fool.
> 
> What you expected to happen
> Glass or shaker go into booze dispenser
> 
> What actually happened
> It doesn't
> 
> Steps to reproduce if possible
> 
> Obtain dispenser
> Try to shove glass or shaker inside
> Cry when it doesn't
> Whinge on github
> Repeat

**Comment by Exxion** [comment]
#9192

**Comment by Exxion** [comment]
Oh look now I'm a collab so I can close this for being a duplicate
