### ISSUE TITLE
We need a way of opening containers that doesn't activate mousetrap assemblies

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10437]
I fixed these things and I regret it.
If someone puts an important item (i.e. the nuke disk) in a backpack and jams in a mousetrap-activated grenade/bomb, there's now NO WAY to get the item without activating the mousetrap too. Even if you know for sure there's a mousetrap in there.
Needless to say this is pretty damn cheap and can get pretty powergamey, especially with the nukedisk as mentioned.
Take the proximity sensor for example, if there's a prox sensor bomb you can disarm it safely by toggling walk. This is fine because you need to know the bomb is there in order to know to walk.

I don't think anyone would disagree when I say there needs to be a way to open the container safely, the real question is, how to add a way to do so without even more retarded verb bloat?
One simple solution would be: mousetrap assemblies don't trigger on found if your intent is set to disarm. There's the obvious issue that there's no downside to being in disarm intent when opening a container, but mousetrap assemblies are so rare and intents are used for so many things that I don't really think it's very important.

Another thing to consider: You're supposed to be able to put a mousetrap grenade in your pocket and have it activate when stripped. Currently this is broken and doesn't work when stripping the pocket item directly, only activates when it's dropped via removing the jumpsuit. I'm fixing this in my stripping rewrite coming soon, but the cheapness worries me.

**Comment by Shadowmech88** [comment]
> mousetrap assemblies don't trigger on found if your intent is set to disarm

Disarm intent is pretty common. I'd opt for grab intent instead.

**Comment by 9600bauds** [comment]
but you're DISARMING the bomb hur hur

**Comment by Shadowmech88** [comment]
Well maybe you have to GRAB the mousetrap to prevent it from closing and triggering the bomb.

**Comment by Megamaw** [comment]
maybe some sort of makeshift booby trap thingamajig on a stick that you can use/make? + a sec item that makes handling sensitive content such as mousetrap assemblies easier?

**Comment by 9600bauds** [comment]
I don't think we should get TOO complex for one single item that's used maybe once a week

**Comment by Megamaw** [comment]
i'm trying to think of things other than this a mouse on a string and stick would be useful for, but idk

**Comment by 9600bauds** [comment]
Lure the Vox vermin out of their outpost

**Comment by Killette2** [comment]
Give the mousetrap bomb to an assistant, problem solved

**Comment by ComicIronic** [comment]
I'd like this to be an action that would be dangerous/bad to do if there isn't a mousetrap assembly,  just to stop people powergaming it in a way that makes the assemblies useless.

**Comment by MercuryDoll** [comment]
Do mousetrap assemblies trigger if you empty the backpack on a table?

**Comment by invoid9** [comment]
Maybe make it so trying to open the container in safety mode (whether it's disarm or grab whatever) takes some set amount of time? If you're accidentally in the wrong intent and just wanna quick open in just walk to cancel or something and redo. This way, people aren't gonna sit in safe trap disarm mode because it would eat into their powergaming time too much.

**Comment by 9600bauds** [comment]
I can't think of any way that would cause either bloat or step on some toes. I know everyone would hate it if opening a box suddenly took 2 seconds just for being in disarm intent.

**Comment by Killette2** [comment]
Disarming device when? Disarms all possible bombs in containers when used on containers, parts appear under your feet if a bomb is disarmed

**Comment by 9600bauds** [comment]
The thing is that you can already just do that with your human person hands
EXCEPT for mousetraps which are very very rarely used

**Comment by Killette2** [comment]
Watchu talking about? Mousetrap nades under locker and in containers easy blow the fuck out of people. Even laying them on the floor, a 50/50 water potas nade is better than an IED bear trap by far, unless you're not trying to cause a hull breach.

**Comment by 9600bauds** [comment]
That doesn't make them not rarely used
Mousetraps on the floor are fine since you can see them and you can pick them up to disarm them, what's not okay is specifically there being no way to disarm them when inside a container

**Comment by Killette2** [comment]
> he doesn't know dragging an open locker or dropping a backpack on them will make it completely invisible

**Comment by 9600bauds** [comment]
Oldest trick in the book man, that's why you don't step on backpacks

**Comment by Killette2** [comment]
The open locker got me once since it covers the whole tile

**Comment by SonixApache** [comment]
Dragging a backpack to a table doesn't trigger mousetrap grenades.

**Comment by west3436** [comment]
Lack of interest in solving this + see @SonixApache's comment for a method of doing this.
