### ISSUE TITLE
Mesons no longer work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10447]
(WEB REPORT BY: jellyveggie REMOTE: 172.93.109.202:7777)

> Revision
> 969e94650bd52a832dfe7544dc27ca0ef0bb4f5c
> 
> General description of the issue
> Mesons no longer work, whith areas that should be visible under mesons still being obscured
> 
> What you expected to happen
> Turfs (is that the right word?), among other things, being visible while wearing activated mesons, as per usual behavior
> 
> What actually happened
> No turfs that aren't properly lit are visible while under mesons, but at least mesons override the goonlighting shade on them.

**Comment by ghost** [comment]
![mesonry](https://cloud.githubusercontent.com/assets/19200220/15904855/dd992866-2db2-11e6-881c-8944ccb43522.PNG)

Picture related.
Also, notice the goon shadows vanishing

**Comment by Exxion** [comment]
Now that's very odd, as they worked just fine for me yesterday
But there's no denying they aren't working there
Furthermore, mesons work based on a stock BYOND mechanic, so I have no idea what could break them

**Comment by clusterfack** [comment]
We moved to using SEE_PIXELS flag, I guess this is a kink we have to work out to use it.

**Comment by Exxion** [comment]
> Two stock BYOND features don't work correctly together

I'm not sure what I expected

**Comment by clusterfack** [comment]
I admit I didn't see this coming. 

At the most basic level I know it is immediately fixable by making the see_turfs flag also give see_in_dark equal to your view range.

But I'd like to know more about why this is occurring before jumping to that admittedly hacky approach.

**Comment by Exxion** [comment]
If it really is JUST the interaction of `SEE_TURFS` and `SEE_PIXELS`, it sounds like a BYOND bug to me
`SEE_TURFS` is listed in the documentation as letting you see turfs _no matter what_
I'm about to test if simply giving myself `SEE_PIXELS` on a pre-parallax build breaks mesons, and if it does, I think that should probably be reported as a BYOND bug

**Comment by PJB3005** [comment]
> At the most basic level I know it is immediately fixable by making the see_turfs flag also give see_in_dark equal to your view range.

That would result in mesons giving you night vision.

**Comment by clusterfack** [comment]
@PJB3005 Mesons give you night vision, and disable lighting. 

Currently they still disable lighting.

**Comment by Exxion** [comment]
Almost all goggles that give you special vision of some kind disable lighting anyway
But also that wouldn't work anyway, according to my testing
You still can't see obstructed turfs, even if you do give the mesons `darkness_view`

**Comment by PJB3005** [comment]
@clusterfack they do disable lighting overlays BUT you can't see tiles that are unlit and outside your `see_in_dark`, if you extend the `see_in_dark` then you get NVGs.

**Comment by clusterfack** [comment]
Oh damn, that is troublesome

**Comment by Exxion** [comment]
Um.
I may have found another, arguably bigger issue with `SEE_PIXELS`
You can right click tiles obstructed from your view to see their contents

**Comment by clusterfack** [comment]
All turfs?

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/15907996/76065f22-2d8d-11e6-9624-95ca524d65f7.png)

**Comment by clusterfack** [comment]
Yeah that's kind of an issue. It also explains why the click catcher worked despite being plane -99.

**Comment by clusterfack** [comment]
At this point we definitely need to bag it up and report it to lummox, though I get the ominous feeling he'll say it's all intentional.

**Comment by clusterfack** [comment]
Without SEE_PIXELS parallax becomes much more performance intensive because you blend away parallax over darkness or some shit. I never bothered looking into it because I knew it would work only very poorly.

**Comment by Exxion** [comment]
So... who's going to report it?

**Comment by ghost** [comment]
Well, this is a convenient hook to starting work on refactoring sight flags, isn't it ?

**Comment by clusterfack** [comment]
I'll report it if no one else feels like it

**Comment by Exxion** [comment]
Sight flags are a stock BYOND feature
Not that we _can't_ replace it with our own system, but it wouldn't exactly be easy

**Comment by Exxion** [comment]
So it turns out that, for some ungodly fucking reason, if you have `SEE_PIXELS`, `SEE_OBJS` eats `SEE_TURFS`, so the former has the effects of both, but the latter does absolutely fucking nothing.

**Comment by clusterfack** [comment]
If that is true @Exxion then this fix could be incredibly easy, and it could simply be that the routine for see_objs is accidentally doing both.

**Comment by Exxion** [comment]
It's still a stock BYOND feature, so, unless I'm mistaken, there's not much we can do about it
But Lummox can probably fix it easily

There's still the problem of being able to right click on and see the contents of obscured turfs, though

I wonder why everything is only awful if you have `SEE_PIXELS`

**Comment by clusterfack** [comment]
How are ghosts able to see everything if they have SEE_TURFS and SEE_PIXELS as well?

**Comment by clusterfack** [comment]
This is my current draft
http://piratepad.net/rKQKCLq1jI

**Comment by Exxion** [comment]
Hold on, I spoke too soon
It's not that `SEE_OBJS` eats `SEE_TURFS`
But `SEE_TURFS` only works if you also have `SEE_OBJS`
However `SEE_OBJS` on its own doesn't have both effects

**Comment by clusterfack** [comment]
It turns out the right click thing doesn't matter that much, only certain admin verbs actually have that bug, though I have asked lummox to fix it.

The turfs thing should definitely be fixable from the test case I've given lummox. He seems to think it would be impossible to hide just one thing or the other but byond is ALREADY doing that if you have see_mobs (hides objs) or see_objs (hides mobs) with the see_pixels and see_turfs.
