### ISSUE TITLE
Space vaults spawning incorrectly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10443]
(WEB REPORT BY: boptser REMOTE: 172.93.109.202:7777)
Every second vault I've encountered in space has been cut off at one of its edges, often breaking its content as the mobs die and loot is easy to access 

the vaults aren't spawned at the edge of a z level so that's not the reason they are broken

**Comment by PJB3005** [comment]
@unid15

**Comment by ihadtoregisterforthis** [comment]
![boult](https://cloud.githubusercontent.com/assets/13305885/15900562/4956c64a-2d76-11e6-81fb-1a4dee5f1e86.png)

**Comment by unid15** [comment]
fuck me

(and map loader too)
