### ISSUE TITLE
Plasmamen Should Exhale Anything But Oxygen

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10440]
Exhaling oxygen doesn't make sense for plasmamen.
<strike>It's bad gameplay-wise because even in a full plasma atmosphere, once they turn their internals off they're going to exhale oxygen into it, which will cause them to burst into flames, which will set the room on fire.</strike>
Actually I just tested it and it doesn't seem to cause you to actually catch fire while in a pure plasma atmosphere.
However it _does_ cause endless spam of the "Your body reacts with the atmosphere and bursts into flames!" message.

It also doesn't make sense lore-wise that the mixture of plasma and oxygen which would form in their lungs does not internally combust, despite the slightest presence of atmospheric oxygen causing them to burst into flames.

**Comment by Kurfursten** [comment]
Maybe this is just a bug that needs fixing. Perhaps plasmamen should immediately start taking burn and lung damage at shift start until they die.

**Comment by AutismSpider** [comment]
Same thing with vox.

You can feed a vox and plasma man dex pills nothing bad happens it floods all the cells in the body with O2

**Comment by Shadowmech88** [comment]
I thought dexalin _did_ deal toxin damage to vox.

**Comment by Exxion** [comment]
No, but inaprovaline does.

**Comment by ghost** [comment]
Think it happened when nexis did the deus ex update, and it just sorta slipped through the cracks.

What should they exhale then? Nitrogen?

**Comment by SysadminJeroen** [comment]
@Skullyton, maybe N2?

**Comment by ghost** [comment]
Perhaps, but what would be the justification for that?

Right now the only thing we've got that converts one gas into an unrelated gas is supermatter

**Comment by Gringonius** [comment]
@Jeroen52, N2O for maximum fun.

**Comment by Exxion** [comment]
We have no idea what the hell plasma is made of, so who knows if nitrogen is actually unrelated?

**Comment by ComicIronic** [comment]
H I E N G

They could always just breathe out CO2 the old fashioned way.

**Comment by Exxion** [comment]
Have them exhale nothing and just gradually become heavier until they turn into stars

**Comment by AutismSpider** [comment]
They get so heavy they turn into walking talk gem or stone of plasma

**Comment by Gringonius** [comment]
@Exxion Atmos filters can be set to filter plasma by the "carbon molecules" option.
So it'd be carbon-based.

**Comment by PJB3005** [comment]
@Gringonius that was changed ages ago.

**Comment by ihadtoregisterforthis** [comment]
A plasmaman went AFK at roundstart on a 1x1 room. An hour later he was surrounded by plasma, far from any canister or vent. I would be inclined to think that plasmamen also breathe plasma, but I have no proof.

**Comment by Gringonius** [comment]
@PJB3005 Oh man. By ages you must mean a couple of months, right? I swear that I saw carbon molecules not long ago.

**Comment by Exxion** [comment]
Well you are right that plasma at least _contains_ carbon, as burning it generates CO<sub>2</sub>
But plasma has gone through like eight different names at this point so going by what it's called won't work too well

**Comment by PJB3005** [comment]
#3727

More than a year ago.

**Comment by Megamaw** [comment]
what if we just removed every race from the game and then we wouldn't have issues like this

i mean

we've done it before

**Comment by AutismSpider** [comment]
@Megamaw  Crabs and Spiders only

**Comment by Megamaw** [comment]
@AutismSpider yes exactly

**Comment by Kurfursten** [comment]
MoMMIs replaced by actual crabs wearing a toolbelt when?
