### ISSUE TITLE
Everything about the gooncode sat is hilariously dysfunctional

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10454]
Problem 1)
You can cheese every single Russian by just breaching any room and then just letting them all suffocate as you go. Speaking of, even if you bolt open both starting airlocks, the air doesn't drain for some reason.
Problem 2)
The russians will actually cheese themselves for you.
![dreamseeker_2016-06-08_17-13-01](https://cloud.githubusercontent.com/assets/6526157/15909462/df8408dc-2d9c-11e6-8f24-549fe991f185.png)
They'll break every single fucking window for some reason.
Problem 3)
The turrets can still be deactivated with a head of staff ID.
Problem 4)
For some fucked up reason, the inner windows SOMEHOW protect you from the turrets
https://a.uguu.se/EU7NrVGpWH8h_Desktop06.08.2016-17.32.10.02.webm

**Comment by Exxion** [comment]
That last point apparently applies to lasers in general.

**Comment by 9600bauds** [comment]
I mean yes, but you don't often have inner windows available everywhere

**Comment by Exxion** [comment]
That's true, but it also really shouldn't be happening

**Comment by Shadowmech88** [comment]
The Russians break the windows because, for some reason, the inner windows prevent them from moving onto the tile, so they have to break them to get to you.

Does the laser problem happen with all lasers, or all laser _turrets_?

**Comment by Exxion** [comment]
All lasers.
I'm looking into it now.

And the windows don't physically stop the Russians from entering the tile, but they DO break their pathfinding because they use stock BYOND pathfinding which only takes density into account

**Comment by Exxion** [comment]
Oh that's right.
Tilebased movecode is utter bullshit.

**Comment by Megamaw** [comment]
well you know what they say

if it's broke

rip the content out of the code haphazardly

**Comment by Probe1** [comment]
just redo it then.  it should change up frequently.  its the challenge arena for players so it has to stay pine fresh or else its not a challenge and we stop giving out dinky rewards for completing it.

**Comment by Shadowmech88** [comment]
Maybe make a few different ones and have it randomly select which one to use at the start of every round.

**Comment by Imagebard** [comment]
So they collectively become old instead of becoming old 1 by 1?

**Comment by Probe1** [comment]
Imagebards got it figured out.  The tcomm sat is closer to an away mission than a vault.  Whereas vaults can be around indefinitely because they're also rare, away missions need changing up or else they get stale.

The telecomm sat is like that.  Every half year or so it needs freshening up.

**Comment by ghost** [comment]
водка балалайка

**Comment by Iamgoofball** [comment]
we have the gooncode now

this needs changed to the goofcode containment, the sprites are there

**Comment by 9600bauds** [comment]
1 BTC
