### ISSUE TITLE
Viewing outpost cameras on the station makes the black squares turn into space squares

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10450]
(WEB REPORT BY: icytruth REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

http://puu.sh/plxnZ/5ba2640fc5.jpg

> What you expected to happen
> To watch the outpost without space paralax in every nonvisible square
> 
> What actually happened
> I watched the outpost with space parallax in every nonvisible square
> 
> Steps to reproduce if possible

**Comment by clusterfack** [comment]
I assume it is changing your vision flags when you use cameras, it needs to add the vision flag SEE_PIXELS additionally

**Comment by 9600bauds** [comment]
Hahahah that's fantastic

**Comment by Exxion** [comment]
It's a very easy fix but also holy fuck I was an idiot when I fixed x-ray cameras so let me just do that in a less-stupid way too

**Comment by Exxion** [comment]
By the way, fixing it will break x-ray cameras again, but that's probably less important

**Comment by Exxion** [comment]
Uh... what
Well, I fixed it, but somehow didn't also break x-ray cameras
I legitimately have no idea why this works but mesons don't

**Comment by Exxion** [comment]
GOD
FUCK
WHAT
`SEE_OBJS` LETS YOU SEE TURFS BUT NOT `SEE_TURFS`

**Comment by kol1th** [comment]
http://puu.sh/pnEUe/f94c721a4a.png
Happens to xenos too apparently

**Comment by clusterfack** [comment]
Probably since aliens have thermals its overriding it in the code somewhere
