### ISSUE TITLE
AI holograms display crew members naked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10457]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision abc835ecad37c4a941857475c712e9f29b487f7a 
> 
> General description of the issue
> When the AI chooses a crew member display for its holograms, the crew member displays with zero clothing except for the exosuit (if they started the shift with an exo like the HOS.)
> 
> What you expected to happen
> Crew holograms not to be lewd
> 
> What actually happened
> lewd as fug
> 
> Steps to reproduce if possible
> Become an AI, set the hologram to mimick a crew member.

**Comment by Exxion** [comment]
In addition, the exosuit the hologram is wearing may be facing a different direction than the body
Or something like that
I forget exactly what it is, but it's weird

**Comment by Ephx1** [comment]
Crewmember holograms are terrible.
You just copy the person's appearance, not their clothing, their clothing is usually what the game thinks is standard at roundstart for the crewmember. Which I'm guessing the game fucked up with.

On top of this there's no actual direction sprites for them, they always face towards south (at the player's POV).

**Comment by clusterfack** [comment]
If it used the person's actual appearance var it would copy their appearance fully. Then you could use something like an AI overlay blended over them to make it look AI-ish.

**Comment by Allspice** [comment]
For whatever it's worth I haven't seen this in effect in months, probably fixed with other plane bugs.

**Comment by clusterfack** [comment]
If it works now it was a result of the byond bug involving overlays, someone needs to check to see if its actually working right now and we'll close it

**Comment by ghost** [comment]
Could not reproduce

**Comment by 9600bauds** [comment]
Could not reproduce, though the resulting hologram sprite can only face south, which could probably be improved
