### ISSUE TITLE
Briefcase attacks not logging

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10459]
(WEB REPORT BY: golfer45 REMOTE: 172.93.109.202:7777)

> Revision abc835ecad37c4a941857475c712e9f29b487f7
> 
> General description of the issue
> attempts to knock someone out with breifcase do not log
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by kol1th** [comment]
That's a very in-depth bug report.

**Comment by 9600bauds** [comment]
I don't even need to look at the code to know this is caused by the briefcase having a copypasted attack() proc, like how the Lawgiver fires.
This is an excellent example of crimes against OOP.

**Comment by Gringonius** [comment]
I'm guessing it follows the code from the rolling pin and the messages of trying to knock someone out only show up to the attacker and victim.

**Comment by Shadowmech88** [comment]
I'll have you know I fixed up the Lawgiver's code recently.
