### ISSUE TITLE
Two more virus ideas I'll never code but say I will

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10464]
Tooth decay - Makes your teeth fall out.  Interesting exemption for mobs without teeth.  Hallways littered with TEEF.
~~Giggingtons - Makes you harmlessly giggle.  Tricks atmospheric technicians into thinking there is a N2O leak.  Weird out everyone else.~~ Added!

**Comment by NigglyWiggly** [comment]
> Tooth Decay

Literally nightmarish

**Comment by unid15** [comment]
Flesh Rot - your flesh rots off, spawning meat slices and turning your limbs into skeletal limbs

(or is it already in the game?)

**Comment by Imagebard** [comment]
>Tooth decay

Please no

**Comment by Kurfursten** [comment]
> Tooth Decay

Only if it eventually kidnaps the Princess of Canada

**Comment by Megamaw** [comment]
@unid15 Final stage is the infected person turning into a skeleton.

Reminder to make an exception for the meatslices for infected who are already skeletons, because skeletons making meat for no reason would be weird.

**Comment by Killette2** [comment]
@unid15 

Already exist. Necrosis does a lot of funny things, from making all your limbs pop off at once, to meat slabs falling off of you, to even shedding your skin and givng you a second chance as a skellington (it will still kill you later anyways via delimbing if you don't get it cured)

@Kurfursten 

I get that reference, memes.

@Probe1 

Gigglingtons already exist

Uncontrolled Laughter Effect - Causes the infected to randomly and uncontrollably giggle, potentially impairing communication.
Ripped straight from the wiki when I noticed it looked familiar.

Why don't we have any fun syndromes like one that induces vomiting, something that gives you cramps and weakens you every now and then, or something of that nature that relate to actual sickness and doesn't require a lot of thought to make.

**Comment by invoid9** [comment]
Bluespace fuckery syndrome (better name required)

Every time you show an external symptom (by coughing, sneezing, laughing, vomiting etc), you get randomly teleported a few feet about the distance the handteleporter does (without any portals made). Obviously a final stage symptom because of the massive fuckery it can cause.

Good idea y/n?

**Comment by Kurfursten** [comment]
Too similar to wizarditis which causes random teleporting imo

**Comment by Killette2** [comment]
:eggplant:  virus when?

**Comment by Blithering** [comment]
Piratitis: causes the infectee to yell yarr, and duplicate items at random.

**Comment by Killette2** [comment]
Too beneficial. If their limbs started becoming wooden pegs, then we're talking

**Comment by Imagebard** [comment]
>and duplicate items at random

![1457563364075](https://cloud.githubusercontent.com/assets/7571238/15988067/43b2fbe6-3019-11e6-86ce-f52059d2d02f.jpg)

**Comment by DeityLink** [comment]
**Uncontrolled Laughter Effect** is a thing right now.

But I like the idea of a Piratitis syndrome that affects your speech and makes you lose your teeth so let's keep this open for now.

**Comment by Shadowmech88** [comment]
One could add Scurvy as one of those odd Virus1 viruses that have single reagent cures.
Make the cure be lemon juice/lime juice/orange juice.

**Comment by Killette2** [comment]
Puking effect when? All we have is the black not-puke.

**Comment by DeityLink** [comment]
both effects that build up toxin damage eventually make you puke, which is more systemic imo

**Comment by DeityLink** [comment]
Now's the time
