### ISSUE TITLE
Admin attacks you in the chest with the advanced reagent scanner!

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10467]
what

**Comment by ghost** [comment]
this is due to spawning a "/obj/item/device/reagent_scanner/adv" - why does this exist?

**Comment by Kurfursten** [comment]
Gonna need some context

**Comment by ghost** [comment]
You don't need it. Spawn one of those and attempt to take a reagent sample of your own blood

**Comment by Sprok0** [comment]
You're looking for a mass spectrometer to scan your blood, the reagent_scanner can only scan objects.

**Comment by ghost** [comment]
@Sprok0 still a grammatical error

**Comment by Sprok0** [comment]
I don't seen any error though? That message is the normal attack message from any sort of item.

**Comment by ghost** [comment]
@Sprok0 Your brain is tricking you: read slowly.

**Comment by Sprok0** [comment]
"Admin attacks you in the chest with the advanced reagent scanner"
Are you sure there's a problem with this, because I can't sure see any.

**Comment by ghost** [comment]
I'm literally retarded

**Comment by Intigracy** [comment]
Unless you mean the Admin part, but that's the mob's name.
