### ISSUE TITLE
Ghosts make shocked vending machines spark

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10470]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5e515d87df38f5c8a7ef1f6269b28ee975d02535 
> 
> General description of the issue
> Clicking on electrified vending machine on the vox outpost makes sparks
> 
> What you expected to happen
> Open the menu to see what was in the machine
> 
> What actually happened
> That, and also sparks
> 
> Steps to reproduce if possible
> Electrify an outpost vending machine, click it as a ghost

**Comment by Zth--** [comment]
It's a feature!

**Comment by Kurfursten** [comment]
It's actually spooky, I like it

**Comment by Killette2** [comment]
Oh so here's a fun trick.
1. Shock a vending machine by cutting a wire
2. You're now stunned, keep attempting to cut the wire in the menu
3. Watch as you can repeatedly shock yourself while stunned until you get husked
4. Notice you can also shock yourself even after death. Fry yourself until extra crispy and byond

**Comment by MusgardTiger** [comment]
It is not really open for abuse so all good methinks

**Comment by ghost** [comment]
@MusgardTiger one word: plasma

**Comment by PJB3005** [comment]
@DrCelt: 1 word: meh
