### ISSUE TITLE
Duplicate, please delete

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#10476]
#### Description of issue

Mesons don't work
#### Difference between expected and actual behavior

Can't see through rocks, should see through rocks
#### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/5549060/15948741/2b955b4c-2e68-11e6-8436-8145b1fd8b4b.png)
![image](https://cloud.githubusercontent.com/assets/5549060/15948743/30ab1004-2e68-11e6-8058-313580194f0c.png)
#### Specific information for locating

Mesons
#### Server revision

Revision: 5e515d87df38f5c8a7ef1f6269b28ee975d02535 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
> [X]  Couldn't find an existing issue about this 

liar #10447

**Comment by kernikov** [comment]
Duplicate issue, my bad.

**Comment by Imagebard** [comment]
Just close it
There's no way to delete

**Comment by Exxion** [comment]
@kernikov Right beside the comment button
The author can close issues
