### ISSUE TITLE
Paralax causes darkness to be space

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10479]
![vampvis](https://cloud.githubusercontent.com/assets/5169310/15951160/f73d09be-2e83-11e6-832c-071ecf1ab220.png)

In this round the second I got heat vision, all dark areas became space until I disabled paralax. If I was outside of the cap's office, the caps office appeared as space. Anywhere dark/shadowed on the map was space pretty much. Paralax

**Comment by Exxion** [comment]
This is legitimately not fixable until Lummox fixes `SEE_PIXELS`
Or we revert parallax or make it not use `SEE_PIXELS`

**Comment by monster860** [comment]
Actually, this can be fixed.
- Make the parallax `PLANE_MASTER` itself use `BLEND_MULTIPLY`
- Make another `PLANE_MASTER` on the same plane as space turfs, and give it the following color: `list(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0)`. This will cause the color be set to white wherever the alpha is set to 1.

**Comment by clusterfack** [comment]
Or perhaps just change the plane of the underlay?

**Comment by monster860** [comment]
What would that do?

**Comment by ihadtoregisterforthis** [comment]
This also happens with a sight radius under 7 tiles
