### ISSUE TITLE
Lings brought back to game as borers can hear ling chat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10477]
(WEB REPORT BY: gutlesscoward REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by clusterfack** [comment]
How

**Comment by Exxion** [comment]
The other copy of this issue actually has info

**Comment by Gutlesscoward** [comment]
Yeah sorry, accidentally hit enter while typing this one.  Oops!
