### ISSUE TITLE
box vox outpost defib closet is empty

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10471]
(WEB REPORT BY: durgen REMOTE: 172.93.109.202:7777)
i expected a defib to be inside
instead it was empty

**Comment by Kurfursten** [comment]
That's actually not a defib closet, that's a first aid locker, which is a now-defunct kind of wall locker that used an identical icon. Shows how dated the outpost is.

It's still empty though. Which I guess is weird.
