### ISSUE TITLE
Combat nanobot OD

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10473]
(WEB REPORT BY: golfer45 REMOTE: 172.93.109.202:7777)

> Revision 5e515d87df38f5c8a7ef1f6269b28ee975d02535 
> 
> General description of the issue
> Od for combat nanobots is 30, wiki states 10
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Intigracy** [comment]
tbh it should be 10 instead of 30, nanobots are intended to be small number overdose.

**Comment by Imagebard** [comment]
>Syringe gun someone I don't like with 15 combat nanobots
>???

**Comment by Intigracy** [comment]
They are very time consuming to make.

**Comment by Killette2** [comment]
> syringe gun someone I don't like with any highly toxic poison/nanobots/creatine/1 unit of slime or advance slime mutatoxin
> ???

That argument is bullshit, since so many things can be instakill in 10 or less units also.

**Comment by Shadowmech88** [comment]
Yes, but the combat nanobots also _gib_ the victim.
The only things that have such an immediate, unavoidable and deadly effect are cyanide and advanced mutation toxin, which are both very difficult to acquire.

**Comment by Killette2** [comment]
> Cyanide
> Difficult

Botany aside, creatine really isn't that complex and only requires a short scavenger hunt of grab food and break into chemistry, and it gibs people.

**Comment by Shadowmech88** [comment]
> and it gibs people

Only if administered in doses over 26u, meaning you can't do it with a single syringe.
At doses under 26u, it just causes mild toxin damage.

**Comment by CptWad** [comment]
outdated, kill this issue
