### ISSUE TITLE
Slow/Drunk walk from Sleep Tox and Chloral do not wear off on Plasmamen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10485]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b961b9acd7c40d62aa888f15f4beb60de22b2fd1 
> 
> General description of the issue
> Plasmamen never lose the slow walk and drunk walk from Sleep tox and Chloral, unless treated with Ethyl.

This becomes a bigger issue with Vamp and Changeling where Clear System or Regenerative Stasis don't actually fix those issues, it's dumb as hell.

> What you expected to happen
> To be able to clear system/regen stasis and not have slow and drunk walk persist
> 
> What actually happened
> THEY STAY
> 
> Steps to reproduce if possible
> 1. be plasma guy
> 2. get sleep tox'd/chloral'd
> 3. live with fucked up legs until someone makes you ethyl.

**Comment by ihadtoregisterforthis** [comment]
Reported in #8234 but this one adds information on how to cure.

**Comment by 9600bauds** [comment]
i fixed this
