### ISSUE TITLE
Cameras break black space.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10489]
(WEB REPORT BY: knife28 REMOTE: 172.93.109.202:7777)

> Revision  b961b9acd7c40d62aa888f15f4beb60de22b2fd1 
> 
> General description of the issue
> Whenever you use the security cameras, it turns the empty 'black' unseen tiles into space tiles.

**Comment by Exxion** [comment]
Duplicate of #10450
