### ISSUE TITLE
Maybe revert parallax until SEE_PIXELS doesn't break things or we can come up with a way to get it to work without SEE_PIXELS

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10486]
Parallax is a purely visual thing. It isn't necessary for gameplay. It's beautiful and I love it, but there are several things that simply cannot be fixed while using the `SEE_PIXELS` sight flag that ARE gameplay-significant.
1. Mesons don't work.
2. Darkness can be right-clicked to gain information you shouldn't be able to have.
3. Thermals work, but are very confusing and show space everywhere.

While parallax is great to have, these things (especially the first two) are just too major to deal with for an indeterminate time until Lummox decides to fix `SEE_PIXELS`.

**Comment by Shadowmech88** [comment]
Do the issues affect everyone, or just people that have parallax turned on?

**Comment by clusterfack** [comment]
I delivered Lummox a fully working test case recently so hopefully it should be fixed soon.

Also I think it would be simpler to have turning parallax off/on add/remove SEE_PIXELS? Though that doesn't fix all the current issues with cameras and such.

**Comment by Exxion** [comment]
Well, merging #10453 will fix the camera bug

**Comment by Exxion** [comment]
Well the first two (and most major) things in the OP will be fixed in the next release, so woo!

Thermals will still be buggy as fuck though
