### ISSUE TITLE
YOU CAN'T UNSTACK STACKS ANYMORE

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10488]
@unid15 probably

**Comment by Exxion** [comment]
Actually it probably wasn't Unid, but I have no idea what broke it because stack.dm hasn't changed recently and other things that use `get_inactive_hand()` still work

**Comment by ghost** [comment]
Seconding this. Can't split stacks and trying to do so duplicated minerals up to 50 sheets.

**Comment by Exxion** [comment]
Really? When I tried to split a stack, it just put the entire stack into my other hand, like when you click most items while they're in your inactive hand

**Comment by unid15** [comment]
I think what happens is the new stack's New() proc calls forceMove( [MOB] ), which calls Crossed() with the old stack and the two stacks merge

**Comment by unid15** [comment]
Don't have time to code today but if another coder is reading this, try adding some checks into either _/atom/movable/proc/forceMove()_ or _/obj/item/stack/Crossed()_ to only merge if the location is a turf. I think it would fix the issue

**Comment by clusterfack** [comment]
I believe I've fixed this by fixing forcemove
