### ISSUE TITLE
GOD DAMN MOTHER FUCKING shipambience.ogg

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10498]
IT'S JUST AN ANNOYING LOW RUMBLE THAT OCCASIONALLY PLAYS AT RANDOM
EVEN IF YOU AREN'T ON THE SHIP, I MIGHT ADD

This is the only ambience sound I feel strongly about at all, by the way
The other ones are all fine
But this one is garbage

**Comment by Exxion** [comment]
Hold on I had a lapse in judgement in typing out that title and it's really bothering me

**Comment by Imagebard** [comment]
What's with the small ambience sound that plays when entering the AI upload
I think its something about Charles Barkley

Why is it there

Memebience

**Comment by TheFriggenSawbones** [comment]
make the .ogg a .flac and we'd be good

**Comment by ghost** [comment]
.flac is a silly file format

**Comment by ComicIronic** [comment]
I love it.

**Comment by DeityLink** [comment]
I love it, that's like pure ASMR.

**Comment by Exxion** [comment]
It's also been removed now
