### ISSUE TITLE
Shuttle Corners And Parallax

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#10494]
![c2d94362be3e143aa66156efa5351f03](https://cloud.githubusercontent.com/assets/5650556/15976865/59e4a3b6-2f23-11e6-9f5a-e57c41017eaf.gif)

I did a quick check to see if someone made an issue on this, I didnt see anything.

Also I dont really consider this of real importance, but if its too much of a hassle to fix can we make static space black so it blends better till a real fix comes.

**Comment by AlphaBuffalo** [comment]
Upon further inspection, I noticed other shuttles have parallax corners, so Im guessing its something unique to the escape shuttle. I didnt check every other shuttle though so if someone has another example please share :)

**Comment by Shadowmech88** [comment]
It looks like the shuttle corner icons have a space turf as _part_ of their icon, which makes NO sense to me.

Why not just cut the space turf out and have that half of the icon be blank, so you could see the _actual_ space underneath it?

**Comment by ComicIronic** [comment]
Shuttle corners strike again.

**Comment by SkowronX** [comment]
Just remove underlays from shuttle corners, easy day.

**Comment by PJB3005** [comment]
Yep, as skowron said. The shuttle code is adding an underlay of the old sprite which ruins parallax.

**Comment by ghost** [comment]
technically
technically
this is meme-code as hell
but you could make the shuttle corner an overlay on the parallax

**Comment by PJB3005** [comment]
No, just make the shuttle not take up the tile in the corner.

**Comment by unid15** [comment]
But then shuttle corners would look bad without parallax

**Comment by PJB3005** [comment]
Uh...

Shit.

**Comment by AlphaBuffalo** [comment]
![](http://i.imgur.com/GkuvLtq.png)

REEEEEEEEEE MUH ILLMUSION

Is anyone fixing this?

**Comment by Shadowmech88** [comment]
This is no longer the case.
