### ISSUE TITLE
Rcd construction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10493]
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Rcds show only an empty backpack space
> 
> General description of the issue
> Rcds show only an empty backpack space

and you cant select a construction type

> What you expected to happen
> having them work as intented :^)
> 
> What actually happened

As state in the description it only is an empty back back 

> Steps to reproduce if possible
> Just try out a rcd after this ebin backpack upgrade.

**Comment by ghost** [comment]
Hey, I couldn't replicate this with the RCD in-game. 

`/obj/item/device/rcd/matter/engineering`

 I was only able to see something similar with one that was not intended to be in the game.  

`/obj/item/device/rcd/matter/`

How did you come across the RCD in this particular case?
