### ISSUE TITLE
Wall-mounted frames are visible from any side of the wall

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10495]
#### Description of issue

As described, you can see intercoms, air alarms, fire alarms, newcasters and just about anything on a wall from the opposite side you should be seeing them. No mesons or x-ray usage.
For example: just look at the southern wall of the toilet area showing machines that should be visible from the main hallway or the dorms APC to the northwest:
![squeek](https://cloud.githubusercontent.com/assets/6732634/15976887/db5a70e4-2f2b-11e6-9b15-32a87cecfe75.png)

Maybe I'm blind and I can't see another issue of this same issue.
#### Difference between expected and actual behavior

The player should not seeing them.
#### Steps to reproduce

Go into maint and look at the walls behind workplaces.
#### Length of time in which bug has been known to occur

I'm not sure if this has been happening since parallax or goonlights, but it looks like that it started happening after one of these features were added.
#### Server revision

26481af1e3855deba14bccb0c4f23a7165eec8d5 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
It was happening for a while after 510, but then that was fixed
But this is completely and utterly unfixable after parallax because this is exactly what `SEE_PIXELS` is _for_

**Comment by PJB3005** [comment]
Yes but shouldn't `TILE_BOUND` then do the opposite again?

**Comment by Exxion** [comment]
Apparently not, as we have `TILE_BOUND`

**Comment by clusterfack** [comment]
Byond bug number two perhaps
