### ISSUE TITLE
Slimes screw up limbs irrepairably

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10496]
(WEB REPORT BY: bigmeatyclaws REMOTE: 172.93.109.202:7777)
Revision: dcbbb2915a2db409af2bfad32078a52a91eb349a 

I got bit by a slime, my leg got screwed up and I promptly fell over, I got a cryo ride and I couldn't walk ever since.

I thought the cryo ride would fix me.

It didn't.

> 1. Get bit by a slime until it fucks your leg up
> 2. Get a cryo ride
> 3. ????
> 4. shit's fucked

**Comment by Ephx1** [comment]
Were there any clone damage healing chems in cryo you dope?

**Comment by Allspice** [comment]
Punch yourself if you're still lying down.

**Comment by 9600bauds** [comment]
Just to clarify: Were you able to move around, just in a state of always lying down, or were you actually unable to move?
Probably #9959
