### ISSUE TITLE
Remove mesons from mining, make mining have goggles which show ores.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10491]
IMO mesons detract from the mining experience. You have no sense of darkness, being alone on an asteroid or anything like that.

If mining got their mesons taken and given goggles which highlight ores, so ores aren't harder to find, I believe this would make mining way more fun.

**Comment by Probe1** [comment]
seems alright

**Comment by Konater** [comment]
sure

**Comment by pvak** [comment]
how about the mining scanner highlights ores like the holomap does with pipes

**Comment by jknpj** [comment]
THINK ABOUT XENOARCH

edit: Miners will most likely break all digsites if they can't see them

**Comment by Konater** [comment]
the artifact overlay or whatever would be included along with the ores

**Comment by ihadtoregisterforthis** [comment]
Think about the caves filled with monsters, and the rooms full of loot.
Also all the unmarked ore walls.

I hope I don't need to remind you that not everyone plays for the inmersions.

**Comment by jknpj** [comment]
> Think about the caves filled with monsters

It's part of the fun, @ihadtoregisterforthis.  I'm pretty sure miners and xenoarchs sign for the job knowing the risk of being tantacle-raped  and slam'ed by goliaths in a dark cave. You can always toss a flare or a lamp before going yourself.

**Comment by ghost** [comment]
Wait, isn't this just the 'upgraded mining scanner' goggles you see on other servers, where ya need the mining scanner to show any ores besides iron, not just show what's gibtonite?

**Comment by Shadowmech88** [comment]
What about goggles that send out a wave in all directions every second, which highlights any ore/non-asteroid turf it hits as it spreads outwards? Like a radar.

Would that be too difficult to implement?

**Comment by Konater** [comment]
isn't that the way they do it in tg/goon?

**Comment by SkowronX** [comment]
tg has it that way. On bay/polaris, you use an optical material scanner which sees machines and objects through walls.
