### ISSUE TITLE
Why is vending machine food so shit anyways

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10503]
The only good one to buy is "4no raisins". All the others have extremely low nutriment levels.

**Comment by TheFriggenSawbones** [comment]
some food tastes better

**Comment by 9600bauds** [comment]
They all have around the same nutriment to cost ratio

**Comment by Imagebard** [comment]
yet I'm having this placebo feeling that 4no raisins is better than, say(I forgot the actual prices), 2 jerky bags.

Can you boost the nutriment in this nutriment to cost ratio?
Maybe its the Salt on some of them.

**Comment by Probe1** [comment]
I don't know why because I didn't code them but I do know they are and should be kept moderately shitty to act as an incentive players to interact with the Chef or riot until a chef is appointed.

**Comment by 9600bauds** [comment]
https://github.com/d3athrow/vgstation13/pull/6981
Literally placebo

**Comment by Imagebard** [comment]
Still booty bothered because I heard once that you needed around 10 salt units to get 1 nutriment
but whatever damn rumors
