### ISSUE TITLE
Plasmaman Prisoner Suit is missing some side sprites

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#10501]
#### Description of issue

http://puu.sh/pomu0/78b69afefd.png
http://puu.sh/pomD8/6c4b0ab497.png

Prisoner Helmet doesn't have side sprites for when the helmet light is on.
#### Difference between expected and actual behavior

it should look different
#### Steps to reproduce

be a prisoner and turn your helmet light on
#### Specific information for locating

**_PRISONER JUMPSUIT HELMET_**
#### Length of time in which bug has been known to occur

since the dawn of time
#### Server revision

idk lol
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

@blithering
I told him about it and said he'd comment or something

**Comment by Blithering** [comment]
More recent helmet sprite is at https://github.com/d3athrow/vgstation13/issues/10410

**Comment by The-Albinobigfoot** [comment]
bleh

**Comment by ihadtoregisterforthis** [comment]
That is not how you autoclose an issue

**Comment by Exxion** [comment]
"Addresses" is supposed to be a valid word for autoclosing
But it isn't
Blame GitHub
