### ISSUE TITLE
unfoldable ball of paper [bus

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10506]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> there is a ball of paper in the bus zoo
> 
> What you expected to happen
> unfold it
> 
> What actually happened

it turns into another ball of paper

> Steps to reproduce if possible

unfold ball of paper

nothing happens

**Comment by 9600bauds** [comment]
amazing!

**Comment by Exxion** [comment]
Oh yeah, that happens with all roundstart balls of paper

**Comment by Kurfursten** [comment]
@ComicIronic This is actually a code issue, not a map issue
