### ISSUE TITLE
Which Colourblind the vox?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10508]
![](http://9f1780.medialib.glogster.com/media/16681ce8da95e77b963984db1a4f6a97a908bae7f206517c1f77475aadf72797/color-blindness-types.jpg)

So we had a vote held here which said overwhelmingy vox should be colourblind. see: http://ss13.moe/index.php/poll/37

The question is, what kind of colourblind? I've made a quick webm of each one, with a "normal" for comparison.

Normal: http://puu.sh/poOsj/133c109ca7.webm
No colours changed.

Red Green: http://puu.sh/poWw2/a13644d277.webm
Red and green appear the same, blue is distinguished. (This is what dogs have.)

Red Blue: http://puu.sh/poOun/24d93b683f.webm
Red and blue appear the same, green is distinguished

Green Blue http://puu.sh/poOnb/1d0eb15be1.webm
Green and blue appear the same, red is distinguished.

**Comment by clusterfack** [comment]
I think this kind of colorblind would be best

![](http://24.media.tumblr.com/tumblr_lxmf8iALv71r9nopqo1_400.jpg)

**Comment by kol1th** [comment]
I quite like the tritanopic option

**Comment by MercuryDoll** [comment]
That would be the Green-Blue option? Looks fancy. We should implement all three versions of colorblindness as genetic defect.

> red-green actually makes the station green and purple

Dope.

**Comment by derpycobra** [comment]
I'd go with Tritanopic too.

**Comment by PJB3005** [comment]
@clusterfack I'm not sure whether that image is supposed to not have any numbers or that's the kind of colour blindness I have.

**Comment by ghost** [comment]
While I'm here, what do you think of this as a colour matrix for plasmamen?
![](http://puu.sh/poPIw/783ab155a9.jpg)
A very light pinkish tinge.

**Comment by MercuryDoll** [comment]
Reduce the overall saturation a bit before adding a pink hue and it'll be 👍
Can colorfilters like that be attached to objects like helmets, mesons and glasses?

**Comment by ghost** [comment]
@MercuryDoll I am intending to do a big update that adds different colour filters to loads of different items, yeah.

**Comment by ghost** [comment]
"Green and blue appear the same, red is distinguished." = best imo

**Comment by ComicIronic** [comment]
Redgreen link is broken, it shows the red-blue webm.

**Comment by ghost** [comment]
@ComicIronic you're right, sorry.

**Comment by ghost** [comment]
http://puu.sh/poWw2/a13644d277.webm is red-green.

**Comment by ComicIronic** [comment]
I support red-blue.

**Comment by Intigracy** [comment]
How about just drastically lowering all saturation so you barely see any color.

Anything is better than the neon eyesores in your webms.

**Comment by MercuryDoll** [comment]
> http://puu.sh/poWw2/a13644d277.webm

https://www.youtube.com/watch?v=NzEemp1SLOM

**Comment by Shadowmech88** [comment]
I'm a little surprised that 160 people voted on that poll.

**Comment by ghost** [comment]
@Shadowmech88 COLOURBLIND THE VOX

**Comment by Blithering** [comment]
They are all hideous, I love it. My vote would be red-blue so vox can't tell who's blood is who's.

**Comment by MercuryDoll** [comment]
Probably proxy-rigged but who cares. Also plasmamen only seeing pink is actually a nice idea in retrospect. Trading in the powergaming aspect of their suit with a headache inducing visual filter.

**Comment by Shadowmech88** [comment]
> Probably proxy-rigged but who cares

It's a server poll, though. You can only vote by actually logging on to the server with a unique account.

**Comment by doobiedoo23** [comment]
tritanopic definitely

crowscum deserve no colour

**Comment by Blithering** [comment]
Trade unknown colour stool for nuke yes?

**Comment by clusterfack** [comment]
I don't think you should go for 'realistic' color blindedness. It looks kinda like shit in all of those except maybe the bottom right in my opinion. You should just make it so some colors get converted closer to others.

Also if we add stands we should force them to have JOJO vision.
