### ISSUE TITLE
Holy flying fuckfish, Batman! That is a fucking absurd number of lighting runtimes!

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10505]
Scroll through the runtime log for a while. Try to find a _single_ runtime that isn't a `list index out of bounds` lighting runtime without using any kind of tool to search for one.
Good luck. You'll need it.

In all seriousness, this renders the runtime log essentially useless because it is too clogged up to find anything or, for that matter, even consistently _load_.

@PJB3005

**Comment by TheFriggenSawbones** [comment]
please stop saying fuck its not like you

**Comment by Exxion** [comment]
It is like me. It's not like my character.

**Comment by TheFriggenSawbones** [comment]
it scares me

**Comment by PJB3005** [comment]
![](http://i.imgur.com/q4W52GF.png)

Literally can't find a single runtime in the latest log file.

**Comment by Exxion** [comment]
Try the day I opened this
The runtime only happens under certain circumstances, but happens every tick or something when it does

**Comment by Exxion** [comment]
I think this has since been fixed

**Comment by PJB3005** [comment]
Only took me 7 months!
