### ISSUE TITLE
BUS GO DARK

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10504]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7c0eabb0e20a92e717f20a186bc5b0fc51f2529b 
> 
> General description of the issue
> bus spawns without lighting sometimes,
> like no lights at all,
> like LIGHTS in GENERAL don't work
> 
> What you expected to happen
> to see
> 
> What actually happened
> i'm blind as fuck, kill bus
> 
> Steps to reproduce if possible
> REMOVE BUS

**Comment by Exxion** [comment]
Lighting failed to initialize or something, just like the test server
I doubt it had much, if anything, to do with being on Bus
To the runtime logs!

**Comment by Exxion** [comment]
Well never mind.
Happened twice in a row on Bus, so it probably IS related. No idea how.

**Comment by ghost** [comment]
It happens every so often with different Z levels, have seen it happen to box's roid z level twice

**Comment by Gringonius** [comment]
Happened two rounds in a row on Bus until the server went back to box.

**Comment by 9600bauds** [comment]
bus is dead and this was caused by an esoteric vault problem that has since been fixed
