### ISSUE TITLE
An AI can right click static to see what's underneath it.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10507]
An AI can right click static to see what's underneath it.

**Comment by kol1th** [comment]
I thought AIs couldn't right click things?

**Comment by Allspice** [comment]
AI can right-click shit that is within ~7 tiles radius of its core, examine what boards a person is holding if they're high enough up in the upload.

**Comment by ShiftyRail** [comment]
Dupe of #20772
