### ISSUE TITLE
Mind transfer (Mind swap) spell doesn't fully transfer over stuff

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#10512]
Not everything is transferred over correctly when you use this spell and it's broken enough that it should be removed until it does. It will work as intended the first cast but after that any spell that checks for range will do so from the point of your original body.
If you're X, mindswap to Y and separate afterwards. You're now in Y's body and you come across Z, if you attempt to mindswap next to Z you will instead mind swap with X again.
It's not just mind swap that has issues after you use it, reportedly any spell that has a range check of some sort uses your original body as the starting point.
Mind swapping also appears to give your spells to whoever you swapped with, letting them also mind swap into their original body.

**Comment by ghost** [comment]
Shouldn't it be a lossy transfer, with each level put into the mind transfer spell meaning less is lost?

**Comment by Konater** [comment]
I recall that being a supposed feature of the spell at one point but this is pretty different
