### ISSUE TITLE
Flesh to stone, subjugate and buttbot's revenge spells still bring up a menu of available targets

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#10513]
Unlike horsehead and other fun curses these are supposed to be point blank offensive spells and make it very hard if not impossible to use on moving targets.
Please make them just pick someone close to you when used like the other spells (or use that fancy new channeling system)

**Comment by AutismSpider** [comment]
Buttbot should be on touch, (it does 60 damage when it pops some one butt off+bleeding)

Flesh to stone pick the closest thing to you.

**Comment by Konater** [comment]
Found out subjugate is the same after getting it in a bundle, perfect spell for channeling

**Comment by Eneocho** [comment]
They're all on-click adjacency spells now
