### ISSUE TITLE
Crystal race, golems just aren't geometric enough

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#10516]
![crystal](https://cloud.githubusercontent.com/assets/15067109/15987608/980ab6d2-3025-11e6-906e-e959edc4b113.png)

Just thought we could brainstorm some ideas for how one would work.

My thoughts for interesting racial traits:
No hands, but tk as standard (not actually possible due to how tk works)
Access to ancient communications
Golem resistances and weaknesses
Acts like a prism when standing in front of an emitter

Download link if anyone wants the floaty spinny crystal mob icon: http://s000.tinyupload.com/index.php?file_id=00555797550829374543

**Comment by Ephx1** [comment]
![moo2_silicoids](https://cloud.githubusercontent.com/assets/6224074/15987674/0ba49d0a-2fff-11e6-87d3-b2c5aa23d2b5.gif)

**Comment by Shadowmech88** [comment]
> Golem resistances and weaknesses

All of the current golem weaknesses rely on having limbs. That is, their loss of limbs when bones break, inability to wear gloves, shoes, masks, or exosuits, and inability to fire guns.

They don't translate very well onto a race that's just a floating telekinetic crystal.

**Comment by Blithering** [comment]
Good point, but the crumbling on death would still work. They would be a bit esoteric for a round start race as well. Someone suggested having them as a large artifact that can be inhabited by ghosts.

**Comment by Imagebard** [comment]
My idea:
One hand with the "TK" power stuck on it forever.

**Comment by Imagebard** [comment]
By the way, the sprite is too fucking bright or however you say it.
Can you use darker colors?

**Comment by Killette2** [comment]
I don't mind the sprite. What about lasers going through them however, being unable to be stunned, and being damaged heavily by brute would shatter them completely. So shotguns would fuck them hard.

Also no hands and such really limits them being lings/vampires/and why would the syndicate ever hire a rock?

**Comment by Ephx1** [comment]
@Killette2 
He didn't say they'd be a standard on station race.

also why is the sprite a Super S?

**Comment by Blithering** [comment]
I didn't intend it to end up as an S, just not very good at geodes I guess. I was hoping to end up with a range of sprites based off different minerals.

**Comment by invoid9** [comment]
> Shooting lasers at the crystal thingy cause the lasers to be redirected in random directions

Expanding on the prism idea, what if it had some focus ability? It floats still and tries to reflect light much more efficiently, causing it to act like a light bulb in dark, increase size of emitter beam going through it, and increasing the damage and size of a laser as it passes through it (also causing the laser and beams to continue in their same directions). Maybe this ability could also split white light into all those colours and create a light show?

Most of those functions seem highly useless, but  it would be funny seeing a sec officer carrying around one of those crystal dudes to help in combat just in case (even if it's a double edged sword)

**Comment by Killette2** [comment]
@Ephx1 
Fuck you for making me see that

@invoid9 
I don't think a single mineral on earth does that

**Comment by Imagebard** [comment]
>On earth

Moot point

**Comment by Killette2** [comment]
Well it's still fucking stupid. Minerals which absorb then emit light? While we're at it let's let the crystals fly over any object and phase through walls, all the while running off of farts.

**Comment by MercuryDoll** [comment]
Having tried myself at spriting something reminiscent of a crystal shard, i commend OP. It definitely is not easy to make.
![crystal](https://a.pomf.cat/kklzfg.png)

**Comment by Killette2** [comment]
It looks nice, but I don't see the face.

**Comment by MercuryDoll** [comment]
I didn't intent on giving it a "face", it was an attempt at making a crystaline structure. Though i've now been considering making some that look like Cephalons, i'd only need to give them some more _depth_.
![Cephalon Simaris](https://a.pomf.cat/nnpqbt.gif)
