### ISSUE TITLE
ATMs in other maps cargos

### ISSUE THREAD

**Issue by MisterGuyIncognito** [d3athrow/vgstation13#10517]
Saw Bus stations cargo for the first time last night.
It's got something that's been sorely needed in the other maps cargos for a very long time.

An ATM inside cargo itself and the QMs room.

Too often the situation is, transferring money to and from accounts only to be robusted, robbed, or honked in the hallways.

Think it'd be worth adding in?

**Comment by Probe1** [comment]
Having one directly in the lobby will help smooth things.  I don't know about putting it in cargo itself and think the lobby adds a little necessary risk but it's a good idea inside or outside of the dpt to have one adjacent.  Even closer than the one on Box which is just outside the HoP door.
