### ISSUE TITLE
Advanced pinpointer doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10519]
(WEB REPORT BY: mikecari REMOTE: 172.93.109.202:7777)
I was an ERT member and I tried using an advanced pinpointer to locate the nuke disk and it didn't show an arrow of any type.

**Comment by Imagebard** [comment]
Do you ever look at the issue reporter and wonder "why the fuck is this here again?"
I mean really. Its basically a incentive to not get a github account, making players unable to comment on coderbus issues. 
Also it generates tons of clone issues every single fucking repot.

**Comment by Intigracy** [comment]
That's because people spam the create button before the next page loads.

**Comment by ComicIronic** [comment]
> Do you ever look at the issue reporter and wonder "why the fuck is this here again?"

Fuck no, being able to report bugs without a Github account is a massive boon for bug reporting.
