### ISSUE TITLE
Add prompt to Borer host exit

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#10527]
Jesus Christ why is this even a thing? The second you click "abandon host" you immediately start popping off and there's nothing you can do, even worse because of how slow the thing is and eventually you plop on the floor having to crawl back to your host.

Just add a big yes or no prompt because this is terrible and incredibly easy to click accidentally.

**Comment by jknpj** [comment]
You'll never know true despair until you accidentally click abandon host in a plasma fire while your host waltz around in atmos suit dragging the plasma miner with him/her

**Comment by Ephx1** [comment]
This is a thing now.
