### ISSUE TITLE
Gas mixers node 1/node 2

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#10524]
#### Description of issue

Gas mixers have two inputs and a single output
Gas filters have two outputs and a single input
#### Difference between expected and actual behavior

http://puu.sh/pqoYB/c50390e4c1.png
I EXPECTED Pipe opposite the output being node 1.
I GOT Pipe opposite the output is _sometimes_ node 1.
Input 1 is actually input 2, and vice versa.
#### Steps to reproduce

Create a gas mixer, guess which input is one and which is two.
Test with canister
Observe
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ComicIronic** [comment]
What relevance do filters have to this issue?

Have you checked if this is to do with mirrored mixers switching nodes?

**Comment by gbasood** [comment]
> can't tell which pipe is which in a filter/mixer

This isn't a bug this is a feature request so you can see what teh fuck you're doing

**Comment by Shadowmech88** [comment]
Add the [sprites] tag, it sounds like what is needed is some arrows on the mixer sprite, like the filter has.

**Comment by ghost** [comment]
@gbasood 

> I GOT Pipe opposite the output is _sometimes_ node 1.

This is about fixing unpredictable behaviour, not about improving bad usability. It _is_ a bug
Did you even read the whole report? Not even that long.

**Comment by gbasood** [comment]
@JellyVeggie 

> sometimes

Literally never used in OP
It isn't unpredictable behavior. A mixer/filter in the same dir will always have the same numbers associated with the same pipe I/O every time
The problem is, if I AM understanding it at all, that it the I/O between dirs is inconsistent.

**Comment by ghost** [comment]
> Literally never used in OP

But I just quoted the OP. 
Third line in the "Difference between expected and actual behavior" section.

Anyway, inconsistence between dirs still adds a layer of unpredictability, at least until the user tries and memorizes the result of all posible cases. 
This calls for fixing, not for adding features to work around it
