### ISSUE TITLE
Chat blind.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10526]
(WEB REPORT BY: teakettle REMOTE: 172.93.109.202:7777)
e3ee7b2767cea8959e923300c853d54046c7e758

> Chat Blind, I only see something along the lines of "maximum of 5 times. use the bug report, ght of the window."
> 
> Clearly There is supposed to be an ingame chat and log of events along with OOC chat.
> 
> Instead it isnt and Im recieving just that message.
> 
> I've cleared cache several times and even turned of hardware rendering and nothing works

**Comment by clusterfack** [comment]
You should have made a github account, did you not realize we can't contact you if you can't even load chat?

**Comment by PJB3005** [comment]
If you're on Windows XP: install IE8

**Comment by Intigracy** [comment]
Not getting the specific message or a screenshot sure is great.

**Comment by PaulRitter** [comment]
can be closed?
