### ISSUE TITLE
hi where is my molten slag and why is melt temperature completely fucked

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10523]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/8550416/15993419/c4bdaad4-30b3-11e6-8952-bcc8094efb9c.png)

Things should be destroyed by fire but they are not.  Also a fuck ton of objects are missing a melt temperature because ???
#### Difference between expected and actual behavior

There used to be slag and there is not slag now
#### Steps to reproduce

Make fire
Set obj melt temperature below fire temperature
Get confused about why we haven't had a feature freeze in six months and we have over 500 bugs
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
Slag was removed intentionally

**Comment by PJB3005** [comment]
It was shit. I remember dying due to it. It's just a retarded and dumb mechanic.

**Comment by kernikov** [comment]
More handholding?
Bring slag back.
If it melts tools then maybe you should be able to make tools with minerals from the 'roid that have a higher melting point.
Boom, fund it.

**Comment by AutismSpider** [comment]
He was trying make ghetto way to turn slag make into minerals he gave up on so it was removed like pipe bursting.

**Comment by Probe1** [comment]
Bring
Back
Slag

Melt_Temperature doesn't even work.

**Comment by Imagebard** [comment]
>Slags

Adolf Hitler did this.
