### ISSUE TITLE
Mineral duplication

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10522]
(WEB REPORT BY: mcgstyle REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7a71dbfb15eac6cb290e8b5fa12d6bc44d60b420 
> 
> General description of the issue
> Minerals can be duplicated easily
> 
> What you expected to happen
> Take one sheet off the stack
> 
> What actually happened
> Stack changes hands and adds one sheet
> 
> Steps to reproduce if possible
> pick up any stack of sheets, click with empty hand.

**Comment by clusterfack** [comment]
@unid15

**Comment by PJB3005** [comment]
Dupe
