### ISSUE TITLE
error in the description

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10536]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> the description of the mint is :
> "it is only wafer thin. "
> What you expected to happen
> to be:
> "It is only wafer thin. "
> 
> What actually happened
> its missing an upper case letter
> 
> Steps to reproduce if possible
> open the game

**Comment by ihadtoregisterforthis** [comment]
This is what passes as bug these days

**Comment by invoid9** [comment]
How can /vg/code be made the greatest, most lagless code ever if proper grammar gets neglected like this?!

You have to think of the BIG picture! One farmer farting in Siberia can lead to a world wide communist revolution if you're not careful. It is the same principle here.

**Comment by SkowronX** [comment]
1500+ issues.

**Comment by kernikov** [comment]
Feature freeze when

**Comment by PJB3005** [comment]
To be honest we really need a freeze.

**Comment by ComicIronic** [comment]
WYFI

**Comment by clusterfack** [comment]
That would imply 1. anyone respects freezes 2. normal people would fix bugs

Neither of those things ever happen, freezes are pointless

**Comment by ghost** [comment]
We need a different approach to feature freezes.

On that note, anyone wanna match my bugfix count on #10465 ?

**Comment by Imagebard** [comment]
Freezes makes coders stop submitting features, which in turn decreases the growing amount of bugs going around.
Its not what its meant to be but at least freezes here are not TGstation-tier.

I already suggested punishing coders that simply leave during the feature freeze but someone was like _OW THE EDGE_ so huh.

**Comment by 9600bauds** [comment]
> Freezes makes coders stop submitting features

Freezes make coders not PR their features
The day the freeze ends there's a whole load of fresh PRs and oh lookie their commit dates are from a couple weeks ago
I am guilty as charged of this, by the way

**Comment by TheFriggenSawbones** [comment]
is it time for me to fix yet another bug?

**Comment by PJB3005** [comment]
It always is.
