### ISSUE TITLE
bandoliers and shotguns

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10541]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> the bandolier exosuit slot cant fit any weapon
> What you expected to happen
> to be able to carry any shotgun on the bandolier
> 
> What actually happened
> the bandolier is useless
> 
> Steps to reproduce if possible
> meta wins with 5% votes
> emag into armory
> wear a bandolier
> try put a shotgun on the exosuit slot
> see you cant wear it
> suicide
> make issue report

**Comment by Exxion** [comment]
The bandolier's purpose is to hold shells, not the gun itself
Armor can hold the gun
But yes, it is still useless

**Comment by Shadowmech88** [comment]
> Armor can hold the gun

But you can't wear both the bandolier and armor at the same time, the bandolier takes up the armor slot.
So you get no armor AND no shotgun slot in exchange for a few more shells that you could carry more easily inside a box in your backpack anyway.

**Comment by Exxion** [comment]
Yes, the bandolier is worthless
#7704

**Comment by AutismSpider** [comment]
can hold all the shotgun shells you want with  plastic bag bandolier is useless and needs to be rework

**Comment by Probe1** [comment]
bandoliers should be attaching to suits like holsters

shotguns shouldn't be attaching to bandoliers because that's retarded and not how they work.

ez.

**Comment by ComicIronic** [comment]
Tagging FR based on this thread.

**Comment by Exxion** [comment]
That's two people suggesting the bandolier be turned into an accessory rather than an exosuit
I guess I'll do that when I get home

**Comment by Killette2** [comment]
I support this, the bandolier sacrifices armor for more shells, but they both should have shotgun storage.

**Comment by Intigracy** [comment]
Yeah you could make it work like holsters, except you can add more than one shell at a time to it.

**Comment by Exxion** [comment]
Turns out we already have storage accessories anyway, so turning the bandolier into an accessory is quite simple
And I can just recycle its current sprites for the world appearance
But I need a sprite for its inventory overlay

Also it looks like you can't remove storage accessories from their jumpsuits, or, for that matter, remove the jumpsuit itself without help
so I'll fix that too

**Comment by Exxion** [comment]
Oh never mind
You can do it with the remove accessory verb
But I still need a sprite
