### ISSUE TITLE
With a sickening crunch, (src) reforms their arm blade into an arm!

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10546]
#### Description of issue

Changeling armblades when retractred state

> With a sickening crunch, (src) reforms their arm blade into an arm!
#### Difference between expected and actual behavior

Testing
No testing
#### Steps to reproduce

Be changeling and extend then retract your armblade
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
@icantthinkofanameritenow

**Comment by icantthinkofanameritenow** [comment]
That's odd. When I tested it, it gave me the "We assimilate the weapon back into our body." message. Any idea what might be causing it?
