### ISSUE TITLE
Mesons ain't working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10543]
(WEB REPORT BY: talux00 REMOTE: 172.93.109.202:7777)
Revision: 6fbc289efcfac0d28fa426054bdbf9f28bc9c84d 

> General description of the issue
> Mesons just display the map area like it's fully lighted but won't penetrate/display/show the rocks in the inner layers of rock
> 
> What you expected to happen
> The mesons working and displaying minerals in all the layers of rock.
> 
> What actually happened
> Mesons just work like a super lantern
> 
> Steps to reproduce if possible
> Put on some meson scanner

**Comment by ComicIronic** [comment]
Known issue
