### ISSUE TITLE
equip shorcut should put tools inside toolbelts

### ISSUE THREAD

**Issue by pvak** [d3athrow/vgstation13#10556]
because reasons

**Comment by ComicIronic** [comment]
Expand this - should it happen for just tools, should  it happen for just toolbelts, what should happen if the toolbelt is full, should it prioritise equip slots i.e. pockets first. 

Also don't self tag.

**Comment by pvak** [comment]
once you prees e with an item it ll check if it can fit in the belt or its full then if it cant fit it ll try equip in pockets and then try to fit in the exosuit slot
