### ISSUE TITLE
Box Vox Tradepost unary vents near shuttle are off at roundstart

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10557]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/8550416/16048433/0f078f1e-3222-11e6-8f02-952222a2886b.png)

This is my fault.  I will fix it when map priority opens up if no one fixes it before that point
#### Difference between expected and actual behavior

The var/on should be 1
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Intigracy** [comment]
learn
to
use
the
map
merge
tool

**Comment by Probe1** [comment]
i
have
never
used
it
once
in
80
PRs
and
someone
said
it
didn't
work
yesterday
nerd

**Comment by Intigracy** [comment]
That's because they're a fucking retard who can't read install.txt.

**Comment by PJB3005** [comment]
And THIS is why map instances are bad.

**Comment by Kurfursten** [comment]
@PJB3005 Separate floors into subtypes based on icon_state instead of having more than 100 instances of simulated/floor when?

Also: probably(?) fixed by #10502

**Comment by Konater** [comment]
honk

**Comment by ghost** [comment]
A fix has been bundled into my update to the area

We will need to dump all vent instances overboard and change it into proper subtypes sooner and later

Default vents should also be ON, and special vents that start with anything different than their frequency should have a subtype

Finally, fix that fucking mapping icon jesus christ

**Comment by Konater** [comment]
sometimes I wonder if all the instances I copy from other parts of the map are messed up and I've been adding apcs with non standard power amounts all this time

**Comment by ghost** [comment]
This is not impossible for some items who create a ton of instances, like atmospheric machinery

APCs specifically, not really. I have personally cleaned a bunch of completely obsolete APCs from our instance list a while ago, and now there should only be the four directionals and a bunch of very specific APCs with missing batteries and what not

**Comment by ComicIronic** [comment]
Mapping instances should never exist as subtypes unless there is a code reason, and that  should be a rare occurance

**Comment by PJB3005** [comment]
@ComicIronic so you're saying we should stop using subtypes and use instances? You've basically gone insane.

**Comment by ComicIronic** [comment]
No, I'm being sensible. The first machinery attackby overhaul hit probably a dozen map conflicts because I had to end up tearing out mapping subtypes which were just var edits of real types. Mapping subtypes have NO reason to exist. Instances are infinitely better.

**Comment by PJB3005** [comment]
@ComicIronic that example is absolutely awful because then you'd have to fuck with map instances, AND cause conflicts for every map PR.

Instances are absolutely awful to handle.

**Comment by Probe1** [comment]
The entire reason there is an issue today is because of instances and bad checking by me.  I could have done better but I was also put in a situation where there was a good chance to fail.

Now instead of me, a guy thats made dozens of map PRs, imagine it's some new guy just starting out.

Instances are useful and so are subtypes.  In this case, they should be subtyped under path/unary/on.  But I'd rather sit on a cactus than do that.

**Comment by Konater** [comment]
you mean path/unary/on/vox

**Comment by Probe1** [comment]
Unarys should be the same.  Scrubbers on the other hand aren't and case in point - Vox scrubbers are just instanced and varedited to remove o2.  What if some guy just grabbed it from the list and didn't check all the variables then put it somewhere on the station?

Awkward.

I've fixed unary vents set to purge myself because someone accidentally grabbed the unlabeled SME unary vent from the list.
