### ISSUE TITLE
Camera Missing Clothing

### ISSUE THREAD

**Issue by Rhydens** [d3athrow/vgstation13#10561]
When you take a picture it puts the mob as the top layer and the clothes beneath them. 
![ok](http://puu.sh/pt8fr/cb6614e051.png)

**Comment by xpcybic** [comment]
The Lewdcam™
"It's a feature!"

**Comment by Exxion** [comment]
That is a lot funnier than it should be.
Also totally mystifying, as I have no idea what recent change could have caused it.

**Comment by Kurfursten** [comment]
Someone should figure out if TG's photocreate is better than our system

**Comment by Shadowmech88** [comment]
> a camera with the ability to take naked pictures of people

Truly an object too powerful to exist.

**Comment by Zth--** [comment]
The nigga one is pure gold

**Comment by clusterfack** [comment]
May have messed this up with my map rendering changes, it's fully possible though I cant immediately tell you why

**Comment by clusterfack** [comment]
Also: fixed your image for you

**Comment by ihadtoregisterforthis** [comment]
Just a small rearrangement
 ![featureloss](https://cloud.githubusercontent.com/assets/13305885/16067089/64931f3a-328f-11e6-8182-384e419340d7.png)

**Comment by ghost** [comment]
@ihadtoregisterforthis I hate you.

**Comment by Exxion** [comment]
You got something against memes, friend?

**Comment by AlphaBuffalo** [comment]
This should be a real thing. You can make xray sec cameras why not add an xray camera?

**Comment by Exxion** [comment]
X-ray camera: Adminspawn only. Takes pictures of people excluding their clothes.
Discount X-ray camera: Made by attaching a carrot to a camera or some shit. Everyone it takes a picture of is a skeleton, fully-clothed.

**Comment by AlphaBuffalo** [comment]
What about emagging the discount camera to make it an x-ray camera

**Comment by Kurfursten** [comment]
Why emag? It's not dangerous

Make it a contraband crate at cargo

**Comment by AlphaBuffalo** [comment]
What about, attaching a carrot to a camera makes it a discount x-ray then using a screwdriver and a multitool you can switch the x-ray mode?

So its kind of like modifying then hacking it

**Comment by 9600bauds** [comment]
caused by https://github.com/d3athrow/vgstation13/pull/10045/commits/91587caef134edbb8c4f44323002396460fbec00?diff=split and I just can't fucking figure out why aaaaaaaaaaaaaaaaaaaaa

**Comment by clusterfack** [comment]
Someone make a fix of something else difficult or make a good port from another codebase for me and I'll bash my head against it until it's 100% fixed.

**Comment by 9600bauds** [comment]
I'm bashing my head against it right now

**Comment by clusterfack** [comment]
Good luck then :^)

**Comment by ComicIronic** [comment]
What if we set total_layers back to 25?

**Comment by 9600bauds** [comment]
After excruciating debugging (fucking fix bicon aaaaaa) I THINK what's happening here is as follows
- Before, two overlays were generated for inhand overlays, one for left and one for right
- Now it's just one overlay that contains the inhands for all hands
- This multi-meta-overlay of sorts has no default icon_state
- getFlatIcon cannot into multi-meta-overlay and doesn't like that it does not have an icon_state so it just uses the human's icon

And now I'm just poking around this bomb with a screwdriver trying to find out what will make it NOT explode

**Comment by 9600bauds** [comment]
at least that's what I'd LIKE to think, otherwise, the only other explanation here is that for some god-forsaken retarded reason unid made inhand overlays null and added the actual inhand overlays AS OVERLAYS TO THE INHAND OVERLAY but I hope it's not that

**Comment by 9600bauds** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/overlays/mobs.dm#L68
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/carbon/human/update_icons.dm#L1044
this seems to be the problem
An obj_overlay inside an obj_overlay
GetFlatIcon does not care about that shit and just tries to draw the obj_overlay directly which FUCKS it UP
now how do you make GetFlatIcon parse this onion-overlay correctly?
fuck me I don't know
