### ISSUE TITLE
Slime Grinder Monkey Blood Buckets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10563]
(WEB REPORT BY: harsetheef REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> When grinding a monkey in the Slime Extractor in Xenobiology.  The resulting blood bucket never runs out of blood.
> 
> What you expected to happen
> For the bucket to run out of blood when transferred to another container.
> 
> What actually happened
> It is a fucking bottomless waterfall of blood.
> 
> Steps to reproduce if possible
> Grind a monkey, grab the bucket, pour it into as many containers as you have.

**Comment by Intigracy** [comment]
#8059
