### ISSUE TITLE
Papercode still broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10572]
(WEB REPORT BY: kekkles REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> HTML tags etc do not work when writing on paper
> 
> What you expected to happen
> Images, text styling
> 
> What actually happened
> Just the papercode written on the paper
> 
> Steps to reproduce if possible
> Try to use the [img] tags or any other kind of papercode tags

**Comment by PJB3005** [comment]
D
U
P
E
