### ISSUE TITLE
Borers permantently deafened by flashbangs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10574]
(WEB REPORT BY: themegagoat REMOTE: 172.93.109.202:7777)

> Revision
> a83bf81c9466e8f5d82ff0eb2de9d7945fa9dfc3
> 
> General description of the issue
> flashbangs can cause borers to become deaf and never regain their hearing

cortical link chat still works though

> What you expected to happen
> Hearing, after a while
> 
> What actually happened
> Not being able to see what people are saying for over twenty minutes and counting
> 
> Steps to reproduce if possible
> Get flashbanged as a borer

**Comment by clusterfack** [comment]
@9600bauds

**Comment by 9600bauds** [comment]
Was the borer in a host, or

**Comment by clusterfack** [comment]
Nobody knows! That's part of the fun!

**Comment by 9600bauds** [comment]
yayyy

**Comment by 9600bauds** [comment]
Probably caused by simple_animal life() not reducing ear_deaf, will take a look after stripcode

**Comment by ghost** [comment]
He was in a sec officer who used the 'run in with flashbang' trick for busting a group of people.

Checked vars on the borer, his ear_deaf was stuck at 10, reducing that to 0 fixed it.

**Comment by 9600bauds** [comment]
Worryingly enough this would have been the case for anything that deafened ~~borers~~ ANY simple animals, just that explosions wouldn't deafen them when inside a host probably
