### ISSUE TITLE
Bus Engineering complaints

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10570]
Mostly just notes to myself
- Singulo generator in storage seems to be anchored for some reason
- Construction area needs to be at least one tile bigger east-west
- It's a lowpop station so mechanic should have more access to the engineering equipment room and engine room, as well as the space access
- Personally I'd like an airlock out from the TEG room for space maintenance, preferably exiting next to the singulo setup.

**Comment by DamianX** [comment]
I think we can close this
