### ISSUE TITLE
Add Drop Shadow to crayon writing?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10576]
@unid15
I was reading this nonsense and realised it is seemingly possible to add a drop shadow to the crayon writing. Something to consider?
http://www.byond.com/forum/?post=2091927

**Comment by Intigracy** [comment]
nty

**Comment by Exxion** [comment]
But like
Why?
Last I checked, when you write something with a crayon, you write _on_ the surface, not slightly _above_ the surface

**Comment by Intigracy** [comment]
Celt likes bloat.

**Comment by Exxion** [comment]
https://youtu.be/lpuS7_NPv6U?t=52s

**Comment by Probe1** [comment]
we're talking about an outline right

a very small white outline would help with definition and making crayon pop instead of blend into the tile and look kinda eh.

**Comment by Exxion** [comment]
An outline or something would be fine
But not drop shadow
That would be silly

**Comment by Probe1** [comment]
I was thinking of something else

![image](https://cloud.githubusercontent.com/assets/8550416/16128489/ea6064ca-33ce-11e6-979b-3d639ba5f4a2.png)

**Comment by Probe1** [comment]
I wouldn't mind a stroke to add some separation between objects and writing.  Drop shadow not so much.

![image](https://cloud.githubusercontent.com/assets/8550416/16128526/07aa725a-33cf-11e6-9443-b15a8b78841c.png)

**Comment by ghost** [comment]
*shrug I don't know the difference, a stroke is what I meant.

**Comment by Exxion** [comment]
Oh, OK then, that makes more sense
