### ISSUE TITLE
Tomb of Rafid ladders fukt

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10577]
(WEB REPORT BY: aurx REMOTE: 172.93.109.202:7777)

> Revision a83bf81c9466e8f5d82ff0eb2de9d7945fa9dfc3
> 
> General description of the issue
> Ladders in the Tomb of Rafid away mission that should link to another ladder via their Down var do not.  All ladders have a Down var of NULL when the map is loaded.  This means that downwards ladders don't work.  TEST YOUR SHIT.  
> 
> What you expected to happen
> SHIT TO BE TESTED
> 
> What actually happened
> IT WAS BROKE AND YOU SHOULD HAVE CAUGHT IT I CAME BACK FROM THE DED FOR THIS?
> 
> Steps to reproduce if possible
> TEST
> YOUR
> SHIT

This can be dealt with by an admin by going through all ladders in the world and finding the ones with a non-null Up var, marking that ladder, following the reference in the Up var, and setting THAT ladder's Down var to the up-ladder that links to it.

**Comment by Aurx** [comment]
Looks like there's at least one with a broken Up as well, but the ladder linking to it has a working Down.

**Comment by Gringonius** [comment]
Aurx manually fixed the ladders during an expedition round and was an overall cool guy.

**Comment by ghost** [comment]
Yeah sure, but we want it actually working without admin intervention for the next time

**Comment by Gringonius** [comment]
Praising Aurx gave me a free rejuv but _don't tell anyone_ please.

**Comment by Aurx** [comment]
I was more thinking you'd come here and bitch about TESTING YOUR SHIT but my ego didn't want me to complain.

**Comment by ghost** [comment]
@unid15

**Comment by unid15** [comment]
Fixed

**Comment by ghost** [comment]
If it's on your latest version, no it's not, we tried to play one or two days ago

**Comment by icantthinkofanameritenow** [comment]
I can verify this, I was there for said away mission.

**Comment by ghost** [comment]
Nevermind, it's fixed now, a hotfix was pushed last night
