### ISSUE TITLE
metaclub safe is bad

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10582]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> its content is useless old code trash and items you can easly get
> 
> What you expected to happen
> have cool muderboning stuff
> 
> What actually happened
> garbage and a paint
> 
> Steps to reproduce if possible
> open metaclub safe
> get trash items

**Comment by 9600bauds** [comment]
Is there ANY safe that's not bad except Deff's?

**Comment by Imagebard** [comment]
>ENERGY AXE on a safe
Good idea

Are you a Khorne worshiper or something

**Comment by Konater** [comment]
lets put a hf blade in it

**Comment by Shadowmech88** [comment]
I vote a shard of glass with 100 sharpness.
No one will suspect its deadliness.

**Comment by Kurfursten** [comment]
@9600bauds After someone specifically requested it, Bus safe now has fun items.

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten 
And those are...what, exactly?

**Comment by Kurfursten** [comment]
Hm, I can't get spoiler/summary spoiler markup to work. So just look it up yourself if you want to spoil the surprise for yourself.
