### ISSUE TITLE
smoke make shuttle dark a little

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10583]
i don't know
![dreamseeker_2016-06-16_11-59-12](https://cloud.githubusercontent.com/assets/6526157/16121642/69bdb1c4-33ba-11e6-869e-ad82987c5b4d.png)
![dreamseeker_2016-06-16_11-59-32](https://cloud.githubusercontent.com/assets/6526157/16121646/6c180780-33ba-11e6-9829-798d33df05df.png)

**Comment by Exxion** [comment]
Yes. Smoke is opaque.

**Comment by 9600bauds** [comment]
yes but it dark forevr

**Comment by Exxion** [comment]
Oh
You know I don't know how I managed not to figure that out

**Comment by clusterfack** [comment]
@PJB3005 Your fix was meant to fix this?

**Comment by 9600bauds** [comment]
Oh wait, this may have been in an outdated branch, give me a second to recompile and try this again

**Comment by 9600bauds** [comment]
Nevermind, this is fixed and I was just living in the past mannn

**Comment by clusterfack** [comment]
Wooow
