### ISSUE TITLE
Choppy space floating movement

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#10590]
#### Description of issue

When floating aimlessly through space, especially while dragging something behind you, you slide around but also jenkily teleport, and it looks really bad with the parallax on. The thing you're dragging also fiddles back and forth jerkily.
#### Difference between expected and actual behavior

Smooth floating, through outerspace.
#### Steps to reproduce

Grab a locker with parallax on, or just do it without, and run off into space.
#### Server revision

8bdde5306ab2c41cc6c9fddaa92f46e0fd061d91
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
#9415

**Comment by Midaychi** [comment]
I guess I didn't dig three months into the issues box to find that.
