### ISSUE TITLE
Artificers slip on space tiles.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10591]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 452210ada90edf96f77ae8c0ccbd50c1870ff25
> 
> General description of the issue
> If an artificer (and presumably other constructs) is on a space tile adjacent to floor it has a chance to slip like a normal person without magboots.
> 
> What you expected to happen
> Not to slip because it hovers.
> 
> What actually happened
> You slipped!
> 
> Steps to reproduce if possible
> Become a construct and try walking in space adjacent to floor.

**Comment by Allspice** [comment]
All constructs were given flying so might as well close the issue.
