### ISSUE TITLE
Lipozine and blood not working for chest borers

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#10599]
This is a very upsetting issue, because of this I can't really force women i'm in to become obese and then fix them before they kill me. Instead I just make women obese and get extracted then stomped.

Also blood doesnt seem to work.

**Comment by Shadowmech88** [comment]
Testing locally, lipozine in general doesn't seem to work, nor does becoming fat from consuming nutriment. I reported a bug with fatness a couple months ago, it seems to still exist. I'll look into the blood, though.
