### ISSUE TITLE
Vox Kitchen Cabinet lacks access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10598]
(WEB REPORT BY: justsumguy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 185d1852b6cd6c6201cd64f28e3cb7c99cc28f64
> 
> General description of the issue
> The kitchen cabinet in the Vox's botany area is locked and cannot be accessed even with a traveler ID
> 
> What you expected to happen
> To be able to open the kitchen supplies cabinet
> 
> What actually happened
> "Access Denied", probably still needs kitchen access
> 
> Steps to reproduce if possible
> Go Vox Trader
> Go to botany
> Attempt to open kitchen cabinet

**Comment by Kurfursten** [comment]
@dylanstrategie

**Comment by ghost** [comment]
Indeed, looks like I missed that one

I'll take a pass at it
