### ISSUE TITLE
Vox Seeds doesn't have the normal seed selection

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10593]
Space is very limited in the Vox Botanical Gardens right now, so I can't afford to put two machines in there. I trusted you to not fuck up @Kurfursten

**Comment by ihadtoregisterforthis** [comment]
Intended.
Also 1600 open issues

**Comment by Exxion** [comment]
Yes, that was intended, as Kurfurst made very clear
The point was to encourage trade between the station and the outpost, but the vox seeds include everything necessary for a pretty good food selection anyway

**Comment by 9600bauds** [comment]
Maybe a few innocuous seeds?

**Comment by Kurfursten** [comment]
It's intended. Vox Plants provide wood, sugar, nutriment, and flour -- plus eggs and no-fruit if you hack the machine. Vox can even "research" new seeds by playing the no-fruit lotto and converting those plants into new seeds. You can even do mutations with the glowshrooms!

Giving them a bunch of human seeds  for plants that just provide nutriment in a different-looking package (apples, oranges, eggplants, etc etc etc) takes away what makes them alien and foreign - especially when it's such a cosmetic/flavor thing.

Now, there is room to grow for the future. It is well-known from the last discussion issue that I'm working on Vox livestock, but that's not all. I have some more alien plants in the pipe to fill the niches that Vox don't have plants for (a slippery plant - banana equiv, a plant that can be used as a weapon - nettle equiv, a plant used for healing injuries - poppy equiv). So don't worry - it won't be four forever. That's just as many sprites as I thought I could reasonably beg off our spriters.

**Comment by ghost** [comment]
Well then, I'll keep this open if Trader players want to give some extra input

**Comment by Kurfursten** [comment]
Since you've all been such good sports, how about a sneak peak?

![untitled](https://cloud.githubusercontent.com/assets/9782036/16142073/048108ba-3428-11e6-93a9-32206a35e657.png)

**Comment by Intigracy** [comment]
I like the way you're doing this.

**Comment by Kurfursten** [comment]
For those who haven't seen it, relevant expansion is going on in #10601

**Comment by 9600bauds** [comment]
It's sneak peek btw

**Comment by Kurfursten** [comment]
In my defense I was very tired

**Comment by ghost** [comment]
Has been addressed in multiple fashions, closing
