### ISSUE TITLE
Scrap monkeys

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#10602]
#### Description of suggestion

Ever had a bunch of random parts laying about robotics with nothing to do with them?
Make a scrap monkey!

What you need:
1x PDA. Any kind. You probably get a lot of these.
4x cyborg parts of any kind. Head, legs, can even be repair parts for them.
1x station bounced radio or comm headset
5x units of wire
1x battery
1x Personal ai device with no personality loaded
1. Start by unscrewing the pda, and attaching all these objects beginning with the cyborg parts. This creates a scrap monkey assembly.
2. (Optional) Use a multitool to configure the laws. Default: none
3. (Optional) Use a pen to configure the name. Default: None, Ask.
4. (Optional) Swipe an ID on it. This 'locks' the scrap monkey's electronics to your highest access level
5. (Optional) Swipe an emag to change the laws to syndicate default and download RobustDrivers.
6. Add a positron or MMI+Brain, and either wrench to disassemble everything or screwdriver to finish.

The result is a monstrosity sticking out from a pda that is about the size of a monkey, is small and has tablepass + hide.

The scrap monkey's hud consists of a radio button, two hand slots, and a PDA on an ID slot that cannot be removed, but a dongle can be extended to accomplish things that using a pda in your hands would normally accomplish. An ID card can be put into and ejected from the PDA, as can carts.

They also contain a PAI, with all the functions being a PAI would give.

Due to driver issues and lack of third party support, scrap monkeys cannot use most traitor gear, law modules, or actual weapons.

 Attempting to use the former two categories will simply cause them to fumble and drop the objects, whereas attempting to use the weapons will instead cause the scrap monkey to make amusing mockeries of the sound the gun/weapon would have normally made instead of actually hitting/shooting with them. Harmless weapons like laser tag or foam darts are usable, however.

Emagged scrap monkeys have the prototype Robustdrivers, which get around these incompatibilities.

Bopping a scrap monkey in the head with an open hand causes them to fold up and drop all held items, turning them into an object that looks like a pda with junk sticking out. This object can be picked up and used/worn any way a normal PDA could be, except that a PAI cannot be inserted and you cannot access or eject the PAI inside, as it is in a semi-active and modified state.

Screwdrivering the scrap monkey object (And if locked, swiping an id card of appropriate access level), will expose the electronics. This allows you to use a multitool to see/change laws, a pen to rename, and a wrench to dis-assemble everything.

Extra suggestion:
Scrap monkeys can also use the BYOND appearances system to take the appearance of one of the PAI animals from paradise station or polaris. https://github.com/ParadiseSS13/Paradise/blob/master/icons/mob/pai.dmi

**Comment by ScrambledSteak** [comment]
The brain part is dumb. You shouldn't waste a brain on what is effectively a downgraded MoMMi that looks like a monkey. Have it be powered and controlled by the pAI on assembly instead.

**Comment by Probe1** [comment]
1600 issues

**Comment by clusterfack** [comment]
Why do you care

**Comment by ihadtoregisterforthis** [comment]
Those sprites are terrible for the most part

**Comment by Midaychi** [comment]
If leaving out the brain isn't an issue then I guess that works too.

**Comment by Zth--** [comment]
I thought this was a a PR and I was full of excitement. Fuck. 
I like the idea of using scrap, though

**Comment by Probe1** [comment]
@clusterfack it's a mess

**Comment by Ephx1** [comment]
@Zth-- 
If the creator is @Midaychi it's always a request.
He's the ideasguy of the server, the one that always spouts ideas but never actually really tries to work on them.

**Comment by Shadowmech88** [comment]
I thought Killette was our resident ideaguy?

**Comment by Ephx1** [comment]
He's the resident babysdayoutguy

**Comment by Ephx1** [comment]
Wait what the fuck, you just took that Bay feature that pAIs had where they can become mobile and added a big chunk of garbage to it.
Why would you do that? I'm all for Mobile pAIs.
