### ISSUE TITLE
Snekpeople

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#10607]
#### Description of suggestion

Sneks!
More seriously though, a suggestion for a new playable species:
1. Breathes oxygen
2. Consists of 1 mob, with two trailing non-dense "tail" entities following behind mimicing their last two tile movements. Ie: Move north and then west, trailers would move north twice and be at a right angle.
3. Other mobs can buckle themselves to the tail to 'grab on', and you can shake them by resisting. Greytide into battle with up to two other jerks welding weapons riding behind you.
4. Damaging the tail damages the "legs" of the mob, but shooting at the tail directly only has a 25% chance of hitting whereas shooting at the mob directly is normal. Melee is unchanged
5. Doors tend to close on the tail mobs causing damage
6. Coil verb/hud button, that causes the two trailers to converge, so you can take 1 chair instead of 3 at the bar
7. Slightly faster grab upgrading when coiled.
8. Remove 'legs' in surgery to remove the tail, replace with robot legs to make them simply just another reptilian scum.

**Comment by kol1th** [comment]
Sneks or snek people? Very important.

**Comment by Midaychi** [comment]
Why not both? They need a "monkey form", after all.

**Comment by ComicIronic** [comment]
Dangerously furry

**Comment by Ephx1** [comment]
jesus christ no
this is almost skeleton tier

**Comment by ScrambledSteak** [comment]
have you been watching monster musume
fuck you furry

**Comment by Konater** [comment]
Miia is the best girl

**Comment by kol1th** [comment]
@Konater Time to code sneks.

**Comment by SkowronX** [comment]
no

**Comment by Orangerush** [comment]
Don't listen to these queers +1

**Comment by 9600bauds** [comment]
that's it I'm making a new tag

**Comment by ComicIronic** [comment]
> WYCI

RIP all issues.

**Comment by kol1th** [comment]
@ComicIronic wonder if we'll get below 1000 issues if WYCI issues are tagged/removed

**Comment by Exxion** [comment]
On the one hand, interesting mechanic ideas
On the other, good fucking luck getting someone to code all that
Bonus third hand: Oh god imagine all the shitposting

**Comment by PJB3005** [comment]
Okay @9600bauds fuck off.

[WYCI] is a retarded tag because it's LITERALLY [Feature Request]: the meme tag.

You're literally making meme tags for the sake of meme tags now, it doesn't add any comical value. [Honk] and [100% Tested] are fine because they have a specific function in meme-ing, [WYCI] serves all the purposes of [Feature Request].

**Comment by Orangerush** [comment]
Why not make sneks random replacement for xenos? I mean the first two forms are already sneks just evolve into bigger sneks 

@PJB3005 THIS family computer

**Comment by 9600bauds** [comment]
I am at fault for not elaborating, but I tagged WYCI as "content requests" that would require significant effort and expand on something that isn't already in the game. Whereas a feature request could be "make this menu less shit" or "please change this balance thing".
I didn't make a new tag for memes and haha lols, I do think the Feature Request tag was getting terribly bloated and needed to have the more far-fetched ideas separated.

**Comment by PJB3005** [comment]
In that case don't fucking replace feature request, use both.

**Comment by 9600bauds** [comment]
Why? That's a bit bloatey
If you want to search for both feature requests and killette's brilliant ideas, you can click on both tags

**Comment by NigglyWiggly** [comment]
God no

**Comment by icantthinkofanameritenow** [comment]
Go back to XCOM general.

**Comment by Blithering** [comment]
Only if the snake's tail grows longer every time it eats, and any snake instagibs the moment it touches it's own or any other tail.
