### ISSUE TITLE
Food trays will not pick up any food and are currently useless.

### ISSUE THREAD

**Issue by Spacedong** [d3athrow/vgstation13#10603]
#### Description of issue
Trays do not do anything when used on food and vice versa. They refuse to pick up any food items and are currently useless.

#### Difference between expected and actual behavior
I think that the trays should be picking up any food on a tile much like a plant bag but they do nothing at all.

#### Steps to reproduce 
Get a tray from the chef's vendor and try to pick up any food item.

#### Length of time in which bug has been known to occur

Not sure.

#### Server revision

00753e149f6c1993efc3a0d1bbb069cd7daae037 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by 9600bauds** [comment]
You put the tray down, place the food in the same tile, then pick it up
Try doing that and see if it works

**Comment by Kurfursten** [comment]
For the record, I've always thought the way trays work is super unintuitive too.

I think they should have table-like code for pixel placement.

**Comment by Spacedong** [comment]
@9600bauds this did not work.

**Comment by 9600bauds** [comment]
fuck trays

**Comment by unid15** [comment]
Tested on local server and trays work just fine (there are some layering issues though)

**Comment by Spacedong** [comment]
it still doesn't work on the main server, and they make an annoying ear rape sound when dropped so they're currently broken and even if they weren't every time you use them you'll get earraped
