### ISSUE TITLE
Plasmamen seem to have 75% innate burn resist rather than the intended 50%

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10609]
Plasmamen have 75% base laser damage resistance, this is applied at all times, even when naked. For reference this amount of resistance makes a naked plasmaman take less burn damage from lasers than humans wearing death squad, nuke ops or ERT armor.
A naked human takes 4 lasers to go into crit, a naked plasmaman (or wearing an assistant suit) takes 14.
Plasmamen security personnel, HoPs and captains get a further 35 value on laser armor value of their respective suits, making them able to tank over 20 lasers before going down. For reference, this makes them more resilient to lasers than nuke ops, death squaddies and security ERT members (which they still outlast naked).
If I am to bring a more extreme case, a HoS plasmaman wearing one riot shield outlasts a Durand in defense mode and using a ranged weaponry armor booster module.

Now, this is where I ask: is this balanced?
To me it feels that it is not, even taking in account how most firefights are based around tases and how there's plenty of non-laser damage to go around this resistance to lasers is extreme and unjustified. Players who grab lasers are often taking advantage of the projectile speed and how they go through windows and glass airlocks and doors, making countering with tasers impossible in common situations involving and bullets easy to dodge because of the distance. To top this off there's pain damage from burns to be considered, a human hit by just two lasers beings to moves slowly due to it, becoming an easy target, a plasmaman needs to take 7 shots to begin suffering from slowdown so they have a ridiculous breather to run away.

Does having to live with the suit in most situations make up for this? Does having to breathe plasma and plasma tanks not being common to replace make up for this? Is not being human enough of a disadvantage?
With my personal experiences I don't think any of those are big enough cons to make up for that but that's where I want people here ponder about it.

If I were to give a suggestion I'd say that removing this reduction completely from them and adding a 10-20 laser defense value on their base suit would be enough to give them some edge against lasers without being near broken as it is. After all they already got an edge against brute by virtue of not bleeding.

Some webms showing their resistance:
Comparison between a naked plasmamen (on lepo and dex+ to negate damage from fire and a lack of plasma), a human and a diona:
http://i.4cdn.org/vg/1466192764617.webm
Naked plasmaman compared to armored (but shieldless) death squad, nuke op and security ERT (commander ERT suits are weaker what the hell).
http://i.4cdn.org/vg/1466196234044.webm
A HoS plasmaman with a riot shield compared to a Durand which I mentioned before:
http://i.4cdn.org/vg/1466198381055.webm
I still need to upload these somewhere else.

**Comment by Shadowmech88** [comment]
First,

> Plasmamen have 75% base laser damage resistance

According to https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/carbon/human/plasmaman/species.dm#L20 plasmamen have 50% resistance to burn damage, not 75%.

Second, I don't think having a lot of burn resistance is necessarily a bad thing. They should just have some other downsides to balance it out. No one complains about the insane brute tanking of dionae because you can husk them with a few hits of a welding tool, so it balances out.

**Comment by Gringonius** [comment]
That's how it seems but in practice it's 75%.
Naked plasmamen take 7.5 burn damage from each laser while humans take 30.
With a pulse rifle it's the same: plasmamen take 12.5, humans 50.

**Comment by Gringonius** [comment]
@Shadowmech88 This is where it's up to the coders. I'd rather if races had minor benefits and minor handicaps instead of a lot of each like how diona are.
Heck, I'd give a lung to have all non-humans removed from roundstart to avoid this issue with balancing and drama from special snowflakes.

**Comment by Shadowmech88** [comment]
> That's how it seems but in practice it's 75%.

Seems this is a bug report then.

**Comment by clusterfack** [comment]
If it was being applied twice in the code it would be 75%

**Comment by Shadowmech88** [comment]
The only places in the code where `species.burn_mod` is used are organ_external.dm and human_damage.dm. I don't see it getting applied twice within the same proc anywhere in there.

**Comment by ghost** [comment]
Remove roundstart diona, make grey antag-only gods of genetic manipulation and all that fun sci-fi stuff, make plasmamen spawn on the derelict as derelict survivors, make vox trade outpost only, Skellingtons are genetics only. Space station side is humans only from roundstart.

At least, if set by admins through a funbutton.

**Comment by Gringonius** [comment]
50% still sound like too much for me but I feel like I'm overstepping now.

**Comment by ghost** [comment]
Found the issue.
