### ISSUE TITLE
X-ray doesn't allow you to see in the dark

### ISSUE THREAD

**Issue by mikecari** [d3athrow/vgstation13#10619]
![bug](https://cloud.githubusercontent.com/assets/10235107/16168770/ee242866-34e2-11e6-9563-32f40e441e0e.png)

Fucking goon lighting. How do we fix this?

**Comment by Shadowmech88** [comment]
X-ray has never let you see in the dark, as far as I know.

**Comment by Allspice** [comment]
Need mesons for that or get vamp X-ray.

**Comment by mikecari** [comment]
Eh maybe it's just confusion because I know wizard Scrying Orb lets you see the in dark. Maybe it's just the genetic power that doesn't to make it less OP.

**Comment by Allspice** [comment]
You need mesons for scrying dark vision as well. Teleport to engineering maintenance storage if you want to be sneaky.
