### ISSUE TITLE
ass pie contains spirit brekaer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10610]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you cook and grind an ass pie you get spirit breaker
> 
> What you expected to happen
> not happen
> 
> What actually happened
> it happened
> 
> Steps to reproduce if possible
> cook ass pie
> eat it
> sprit breaker happens

**Comment by Allspice** [comment]
FEATURE

**Comment by Shadowmech88** [comment]
It was decided some time ago that this was a feature.

Though I'm not sure what the rules are on dosing people with it as a non-antag.

**Comment by Probe1** [comment]
its a pretty shitty feature tbh.  "Hey that exclusive traitor chem?  Yeah we put it in a joke item that can be commonly made.  Haha."

**Comment by pvak** [comment]
it was reverted for ass burger but whoever did it forgot to change the ass pie reagents
