### ISSUE TITLE
FEATURE REQUEST: DRINKING FROM BOTTLES

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#10614]
Someone should code drinking from bottles. Also, having bottles break when thrown/over people's head like booze bottles. My potions are too strong for you, traveler. :100:

**Comment by sonime** [comment]
Potion seller, I am going into battle against the greytide, and I need your strongest potions!
I love this idea.

**Comment by Rhydens** [comment]
You should do it, Kol1th! I believe in you!

**Comment by ScrambledSteak** [comment]
MY POTIONS ARE TO STRONG FOR YOU, SECURITY. MY POTIONS COULD KILL A SPACE BEAR, LET ALONE A MAN.

**Comment by kol1th** [comment]
@Rhydens I'm too stupid to code

**Comment by Rhydens** [comment]
I'm sorry to hear that. I hope you get well soon.

**Comment by ihadtoregisterforthis** [comment]
> Someone should code

We have a new tag for that actually

**Comment by kol1th** [comment]
It is merely a suggestion unless someone wants to hold my hand

**Comment by ghost** [comment]
Doesn't really solve it but keep in mind we have the rapid service fabricator which can print drinking glasses at a rate of 1 per charge of a matter cartridge. bum the rsf off the bartender and buy some metal/glass at cargo and you're set until this feature request is completed.

Use, which caps bottles/beakers, is the same or at least same enough as attack self so it's not a quick and easy right?

**Comment by Killette2** [comment]
Breaking tiny bottles over people's heads like glass bottles? How big or thick do you think these are?

This would also create glass shards, more EZ stuns, and the ability to print said EZ stuns for free.
