### ISSUE TITLE
Arm boreres and clumsypeople

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10628]
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Death to the clowns borer war now
> 
> General description of the issue
> As a clown a borer infested my arm as I was clumsy the fleshhook kept EXPLODING when the borer used it killing me in less then a minute . The borer was unaware of this.
> 
> What you expected to happen
> Not dying because a fleshhook blows up in my face even though I dont use it.
> 
> What actually happened

I died because the clumsy disability kept exploding the hookshot whenfired.

> Steps to reproduce if possible

Try it out with a clumsy disability. 

Hint Quality control plz

**Comment by Killette2** [comment]
You must be really clumsy

**Comment by mikecari** [comment]
It's a feature, not a bug :^)

Clown dying in comically hilarious ways is kind of supposed to be a thing too.

**Comment by ihadtoregisterforthis** [comment]
Clown getting suicided with his own arm exploding doesn't sound like a feature

**Comment by AutismSpider** [comment]
@ihadtoregisterforthis Clown died of exploding bone cancer RIP

**Comment by NigglyWiggly** [comment]
Sounds like Boneitis

**Comment by Shadowmech88** [comment]
I could remove the clumsy check from it.
It's a child of hookshot. Should I remove the clumsy check from the hookshot as well?

**Comment by AutismSpider** [comment]
why the fuck is the hook shot a gun?
