### ISSUE TITLE
Graphics not displaying properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10625]
(WEB REPORT BY: riftninja REMOTE: 172.93.109.202:7777)

> Revision
> 778f64fcb19aa9845fa123de92002a95acaf7ba6 
> General description of the issue
> Since last patch, clothes not displaying, bottles and beakers not displaying contents.

Tried rebuilding cache, no change.

**Comment by ComicIronic** [comment]
Possibly the Byond overlay issue?

**Comment by PJB3005** [comment]
Make 100% sure you're on the latest byond version.

**Comment by clusterfack** [comment]
Update byond
