### ISSUE TITLE
PAI Wirejack caused screen freeze and Improper Arguement

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10620]
(WEB REPORT BY: kekkles REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Using the PAI for a wirejack causes the screen to freeze
> 
> What you expected to happen
> No freezing
> 
> What actually happened
>  http://mugi.moe/uzptv
> 
> Steps to reproduce if possible
> Use PAI to wirejack any door

**Comment by PJB3005** [comment]
Sounds like a BYOND bug.

**Comment by nervere** [comment]
Can't reproduce this and the video evidence is long gone.
