### ISSUE TITLE
Graphics not updating clothing at all

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10627]
(WEB REPORT BY: boptser REMOTE: 172.93.109.202:7777)
Despite everyone wearing something, all sprites in the game appear as if they were naked

hand sprites still work but stuff like cryo, tank containers, large beakers, all don't update beyond the initial state 

screencap
https://gyazo.com/8cf2c5a08a6ba1c2318e190a3f2c333d

**Comment by Intigracy** [comment]
I have no idea what the problem is, not everyone is having this issue.

**Comment by clusterfack** [comment]
Update your fucking byond version
