### ISSUE TITLE
rightclick is slow

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10621]
can we fix it??
see: http://www.byond.com/forum/?post=1326139&page=2

**Comment by ComicIronic** [comment]
We can 
REMOVE
VERBS

**Comment by PJB3005** [comment]
> We can
> REMOVE
> VERBS

No other fix.

**Comment by 9600bauds** [comment]
From my understanding this would only require the removal of client verbs that not all clients have
Specifically, adminverbs seem to make up the great great great majority of the perceived slowdown
