### ISSUE TITLE
hookshot borer and dead host

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10634]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> the hookshot borer can still use his powers even if the host is kill
> 
> What you expected to happen

not happen

> What actually happened
> happened
> 
> Steps to reproduce if possible
> be hookshot borer, host dies, you can still move around with the hookshot

**Comment by NigglyWiggly** [comment]
That sounds like a great feature

**Comment by JustSumBody** [comment]
![image](https://cloud.githubusercontent.com/assets/19365096/16173902/b12d9e7e-357d-11e6-98c9-5c62e34e1ec6.png)

**Comment by Shadowmech88** [comment]
Is intended to be a feature.
