### ISSUE TITLE
Add framework for special roles to receive sign ups for antag/diona/whatever while alive

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10639]
Observers pmuch have a choice.  Be a bomberman or whatever, or wait for that antag role.  

It'd be nice to have something for them to do instead of be idle and wait but the way the game currently handles it would prohibit them being in a living mob of any sort (bomberman etc).

Adding this, and the requisite sanity to keep it from fukkin up, would be very nice.  I guess that would mean moving notifications to a flag.  If this was done we could let observers play bomberman, or fight in the thunderdome, or maybe add antag practice stuff?  Plenty of things to do instead of nothing.  Which is ideal.  

We want death to be consequential.  But we also want players back in the round.  Waiting until you get a chance to get back in with nothing to do but observe deters this.

**Comment by Shadowmech88** [comment]
So, you're asking for a framework that allows ghosts to enter other mobs without necessarily severing their connection to their original body?

**Comment by Probe1** [comment]
yeah pretty much spot on.

**Comment by Shadowmech88** [comment]
You may want to change the title, then. I don't feel it accurately conveys what you're asking for.

**Comment by Probe1** [comment]
I don't really know what I want.  I know the result but I don't know what I'm asking for, so it's difficult to word the title.

Look at an observer.  They're not doing anything.  If we could give them something to do, nothing major just existing stuff we have, they'll be more entertained and likely to stick around and hit that sign up button when a chance comes to re-join. 

But that doesn't really work currently.  If they are already a bomberman or even a derelict mommi they won't receive notification a wiz or blob or something is available.

**Comment by Shadowmech88** [comment]
Oh THAT'S what you meant.

I thought you meant you wanted dead players to be able to go into a bomberman or derelict MoMMI, then go back to being a ghost and still be eligible for their original body being cloned and such.

So what you're actually asking for is for ghosts in certain mobs, while living, to be able to be pulled directly into spawned wizards/blobs/dionae if they're opted-in, as though they were simply waiting for such a role as a ghost?
