### ISSUE TITLE
flashbangs make borers deaf forever

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10632]
(WEB REPORT BY: januszpavulon REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> df0258454d3cabecc8ebfca9d7095cc5c1a4995f 
> General description of the issue
> flashbangs make borers deaf forever instead of just for a while
> 
> What you expected to happen
> being deaf just for 1 minute or so
> 
> What actually happened
> i was deaf until admin removed it, it was like 5-10 minutes
> 
> Steps to reproduce if possible
> be a borer with a host, make him throw a flashbang and be near it

**Comment by ihadtoregisterforthis** [comment]
Heh
Fixed
