### ISSUE TITLE
Borer hookshots need limits

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#10638]
Just this past round, I've had the humiliating experience as a security officer of being unable to arrest a stunned prisoner because his borer kept hookshot-ing him away. At the same time, I don't want to have to cut a guy's arms off just to be sure he can't escape. So how about just making the hookshot only usable if the host is not stunned or dead?

**Comment by Kurfursten** [comment]
REMOVE MULTIBORER remove multiborer

**Comment by Shadowmech88** [comment]
Working on a PR right now to make stuns inhibit the hook as well as making some chem act as a constant inhibitor while in the host's system.

**Comment by AutismSpider** [comment]
make it cost chems to use.

>having the bone hammer sword or shield on drains chems fast
>hook shot does not

**Comment by Shadowmech88** [comment]
Fair enough.

**Comment by Gunosaguki** [comment]
definately don't hope the cost is too much, part of the fun is just dragging your host around and its just a grappling hook at the end of the day, it should only cost chems if theres somethign in the hand since you can actually ranged attack with that.

stunning disabling it though is pretty apt, though shouldn't disable the grapple if they're simply laying on the ground from a slip or something

**Comment by Shadowmech88** [comment]
> it should only cost chems if theres somethign in the hand since you can actually ranged attack with that

That didn't even occur to me.
That makes a lot more sense.

> though shouldn't disable the grapple if they're simply laying on the ground from a slip or something

Not sure if it's possible due to the way our stun system works. I believe electrodes and slips use the same var to stun people.

**Comment by Orangerush** [comment]
@AutismSpider This is good, not constant chem use though. Per use, it is just a hookshot afterall

**Comment by NigglyWiggly** [comment]
Multiborer removed when, though

**Comment by icantthinkofanameritenow** [comment]
@NigglyWiggly 
You go and revert it then, I'm engaged in enough debates about removing shit already.
