### ISSUE TITLE
getting cloned after becoming a borer after death

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10646]
(WEB REPORT BY: januszpavulon REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> bc366e02ff0c97be0ee24c272ba3766c702f47bf 
> 
> General description of the issue
> i died, then became a borer after signing up as a ghost, and in middle of playing as it i got cloned as a crewmember i played from the beginning and lost my new borer life
> 
> What you expected to happen
> nothing, mental interface error
> 
> What actually happened
> it happened
> 
> Steps to reproduce if possible
> die
> become borer
> get your first body cloned

**Comment by Shadowmech88** [comment]
[Needs Moar Testing] also.
Could be a bug with borers specifically, or all simple_animals, or all opt-in ghost sign-ups like diona, posibrains, etc.

**Comment by clusterfack** [comment]
Here we go again

**Comment by clusterfack** [comment]
FUVKING NEXBORERS

**Comment by PJB3005** [comment]
Borev would've been a better idea.
