### ISSUE TITLE
Mouse click commands don't work on dark tiles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10641]
(WEB REPORT BY: justsumguy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> bc366e02ff0c97be0ee24c272ba3766c702f47bf 
> 
> General description of the issue

Click commands don't work when clicking on a dark tile

> What you expected to happen

Middle clicking switches hands, clicking anywhere ingame faces your character in that direction, throwing items even outside your view will throw the item in that direction anyway

> What actually happened

Doing either of these when the mouse cursor is on a dark tile causes the command to not go through

> Steps to reproduce if possible

Find a wall between yourself and a tile so that the tile is out of view(black square)
Attempt to middleclick, throw an item, or face that direction with your cursor on that tile.

**Comment by Intigracy** [comment]
This is a result of the byond fix that was in the last update.

Literally unfixable.

**Comment by Shadowmech88** [comment]
Woah, wait. Does that mean we're once again unable to fire guns into darkness?

**Comment by JustSumBody** [comment]
It would appear so.

**Comment by Exxion** [comment]
Now I'm not sure, but that sounds more like a planes thing than a BYOND thing
@DrCelt

**Comment by Intigracy** [comment]
The byond bug that got fixed is that you used to be able to right click on
black tiles to see their contents.

This fix is what caused the click issues people had until lummox fixed it.

It seems it's not registering left click though.

**Comment by Exxion** [comment]
Left clicking on darkness tiles is our code, not BYONDcode, though
The ability to right click on dark tiles was `SEE_PIXELS` weirdness
Though maybe the `SEE_PIXELS` black boxes would break things now
I don't know

**Comment by clusterfack** [comment]
Move the click catcher above plane 0 to fix this

**Comment by 9600bauds** [comment]
fix it fix it fix it

**Comment by clusterfack** [comment]
Tonight

**Comment by PJB3005** [comment]
> Tonight.
