### ISSUE TITLE
Eye surgery/Advanced prostheses refuse to work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10657]
(WEB REPORT BY: bigmeatyclaws REMOTE: 172.93.109.202:7777)
dcf6bbe372ff1d51aa6c8e23db64061431da009f 

> Upon inserting prosthetic eyes into a guy, he just couldn't see shit, nothing worked, not even admin intervention. I tried applying imadozaline, cornea surgery, different eyes, re-inserting the eyes and even clean SE, none worked.
> 
> functional cyborg eyes
> 
> Blind patient stumbling around
> 
> adv eye prosthesis surgery

**Comment by pvak** [comment]
did you reattach the eyes after inserting them?

**Comment by Kurfursten** [comment]
For the record, I was able to get them to work for myself

**Comment by ghost** [comment]
Did you give him ryetalin? I found out once that if a patient goes completely blind, even reducing eye damage to 0 he will remain blind as it counts as a genetic defect, so only ryetalin will fix it. I never tried giving him a clean SE as that should fix it too but, this game works in stupid and mysterious ways.

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce. Vision came back as soon as the prosthetic eyes were attached with the Fix-O-Vein.
