### ISSUE TITLE
hair layer is below the backpack layer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10652]
(WEB REPORT BY: cumoverme REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> dcf6bbe372ff1d51aa6c8e23db64061431da009f
> 
> General description of the issue
> Have a long hairstyle, see it disappear below your backpack.
> 
> What you expected to happen
> Not to have my immersion ruined.

**Comment by ghost** [comment]
Is this even a bug?

**Comment by 9600bauds** [comment]
Sounds noticeable from the back

**Comment by NigglyWiggly** [comment]
> Putting your hair over your backpack

For what purpose

**Comment by 9600bauds** [comment]
So you can turn your head maybe

**Comment by Shadowmech88** [comment]
Is your backpack vacuum-sealed to your back or something? Backpacks pressing against your back don't have a tight enough hold on your hair to prevent your head from turning.

**Comment by 9600bauds** [comment]
> Is your backpack vacuum-sealed to your back or something? 

The straps are on somewhat tight, I don't know who'd put something like ponytails under them
I don't have long hair myself but tucking it under your backpack seems silly, and a hasty Google search confirms it

**Comment by Shadowmech88** [comment]
Personally I've only had problems when my hair is under the straps, since they support the backpack's weight, making their grip a lot tighter.

From a gameplay perspective, having the hair layer above the backpack layer might be troublesome for large back-layer items like the trophy rack.

**Comment by Intigracy** [comment]
It's always been this way as an fyi.

**Comment by MercuryDoll** [comment]
> From a gameplay perspective, having the hair layer above the backpack layer might be troublesome for large back-layer items like the trophy rack.

Not only that, it was probably also game-balance affecting, as you could easily tell if someone had a backpack on or not. Not sure what purpose hiding the backpack on your back would serve but i'm sure powergamers would find an advantage.

**Comment by 9600bauds** [comment]
Powergamers figured out long ago to use satchels

Which is coincidentally what you should do if this layering hurts your snowflakes I guess

**Comment by NigglyWiggly** [comment]
Satchels are <sub> cuter </sub> than backpacks anyway though

**Comment by Probe1** [comment]
Dead issue.
