### ISSUE TITLE
People in photos appear nude when they are clothed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10665]
(WEB REPORT BY: daxalog REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Using the camera and looking at a photo with a player in it causes them to be naked (Their nudity dependant on thier underwear option)
> 
> What you expected to happen
> To see a nomrla photo with people in it
> 
> What actually happened
> NUDITY (dependant on underwear option of the specific player you take a picture of)
> 
> Steps to reproduce if possible
> I was a vox latejoin as a journalist. I took a picture of human players. And then viewed the image in my hand.

**Comment by ComicIronic** [comment]
Known issue.
