### ISSUE TITLE
No progress bar for AI planning module

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#10664]
The planning module takes 5-10 seconds to upload into an AI or cyborg upload. However, it gives a starting message making you THINK it worked, but it won't work until you stay longer and another message pops up. This has lead to people thinking they have uploaded their laws but really they just purged an AI.

Simple addition, kinda a bug report since everything else has progress bars, and this is something that should have it since it involves you standing still to do something.

**Comment by JustSumBody** [comment]
Works on my Machine™ on version 1347
![image](https://cloud.githubusercontent.com/assets/19365096/16180484/dafe7b5c-3653-11e6-93da-9c5c3faf69b2.png)
Maybe it's the same issue that made mesons bug out, I remember progress bars for mining being weird during 45 as well so you might have to upgrade?
EDIT: ACTUALLY, progress bars in general aren't showing up if the bar is on a darkness tile, this includes mining
![image](https://cloud.githubusercontent.com/assets/19365096/16180531/ae2cf5e8-3655-11e6-9431-7a37baa30b5f.png)
Might be more planes stuff? @DrCelt

**Comment by ghost** [comment]
alright, it's planes nonsense. will fix.
