### ISSUE TITLE
Heart Removal Surgery is Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10673]
(WEB REPORT BY: colegrippah REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 7c2ffa048f9aca419fe386134be496f462dd5abe 
> 
> General description of the issue
> I tried to perform heart transplant surgery on a patient, but could not successfully remove the heart.
> 
> What you expected to happen
> The heart would come out, and I could put a new one in.
> 
> What actually happened
> The patient kept having a heart in his chest after one was removed, causing me to remove close to a dozen before giving up.
> 
> Steps to reproduce if possible
> Perform a standard heart transplant.

**Comment by ComicIronic** [comment]
KALI
MA

**Comment by ghost** [comment]
Could not reproduce
