### ISSUE TITLE
Vox Engineer suit helmets dont grant welder blindness protection

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10682]
(WEB REPORT BY: galaxygryphon REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f732dcfcca25f80c613b90bfd6d267b2a02c9f3d 
> 
> General description of the issue

Vox CE suit, Atmos suit (havent tested the regular Vox engineer suit) do not grant immunity to welder blindness

> What you expected to happen

same function as the human versions of the engineering suits, not having to use welding goggles which means you cant use mesons, or a welding mask which prevents you from welding in space.

> What actually happened

welder blindness through the suits helmet

> Steps to reproduce if possible
> 
> wear vox engineer helmet
> weld
> go blind
> complain on github

**Comment by ComicIronic** [comment]
Known issue and fixed.
