### ISSUE TITLE
Strip code is kinda bugged??

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10685]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c815d7f6a05d1e8de14e7162bf0ea5d3305ae3f4
> 
> General description of the issue
> http://puu.sh/pzhcO/d5ca7ee4b1.png
> http://puu.sh/pzhmB/7901c5904b.png
> You can DUAL WIELD clothing.

Although the properties of the first item don’t remain. With the exception of Helmet Lights still persisting. 

> What you expected to happen
> I’m not sure honestly
> 
> What actually happened
> i can wear TWO HATS at once
> 
> Steps to reproduce if possible
> You’re going to need a friend and two hats for this one boys.

Put hat 1 in your hand, and give hat 2 to your friend.

Have your friend open the strip menu and try to put a hat 2 on you.

After the attempt message shows up, put on hat 1.

WATCH as magical bullshit happens.

It also works for exosuits, so I’d assume most other things aswell.

**Comment by Kurfursten** [comment]
We should have a tag just for sanity

**Comment by TheFriggenSawbones** [comment]
are you calling me insane

**Comment by Kurfursten** [comment]
I assume you're just joking with me but in case that is a serious question, I mean that this bug is caused by a missing sanity check.

e.g.: "check again to make sure they're not wearing anything at the time to apply the clothes item"

**Comment by 9600bauds** [comment]
Alas, the only scenario I didn't account for was having friends

**Comment by Exxion** [comment]
Also I want to file a different formal complaint
Putting clothes on monkeys now takes time

**Comment by 9600bauds** [comment]
You can still slap the monkey with the monkeyclothes to instaswap them I think, or did you mean something else

**Comment by 9600bauds** [comment]
I'd like to point out that the report says you can DUAL WIELD clothing but this is false, the powers it gives you are far greater, for you can DUAL WEAR
