### ISSUE TITLE
Simplify camera assembly down to 1-2 steps

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#10689]
No one ever hooks up new cameras.

**Comment by SysadminJeroen** [comment]
I have done multiple attempts to hook up cameras.

It was just too frustrating so I quit trying.

**Comment by Intigracy** [comment]
I do it regularly.

Currently it's wrench while it's on the ground / weld / wire / screwdriver
Upgrades in between wiring and screwdriver.

**Comment by Probe1** [comment]
@Intigracy I originally complained to have the upgrade process but we stopped there after it was improved (before you had to completely disassemble the fucking thing then apply the upgrade and rebuild it).

It's been probably a year now and I still never see cameras built.

**Comment by 9600bauds** [comment]
Removing steps from construction also means removing steps from deconstruction 
Not sure how big of a deal that is with cameras being heinously easy to disable without deconstructing them anyways, the only one that matters is welding since it requires eye prot

**Comment by 9600bauds** [comment]
For starters we could get rid of the wiring step, just say the camera assemblies are already wired

**Comment by Konater** [comment]
I'd rather not since it's rare enough cameras are disabled in the first place
