### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10693]
(WEB REPORT BY: justsumguy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1fe6a823d2f983f71a81a0c2d80d1ebac15107fe 
> 
> General description of the issue
> messages are showing up twice for the user(the world message and the user message)
> 
> What you expected to happen
> "You robust Greytide McGee with the toolbox!" is the only message that shows up on my screen
> 
> What actually happened
> "You robust Greytide McGee with the toolbox!"
> "User robusts Greytide McGee with the toolbox!"
> both show up
> 
> Steps to reproduce if possible
> Attack something
> Use a thing on someone
> Do anything that has separate messages for the user and world

**Comment by 9600bauds** [comment]
:100:

**Comment by 9600bauds** [comment]
First we had DUAL WEARING, now we have DUAL HEARING
What will happen next?

**Comment by clusterfack** [comment]
That's what we get for trying to avoid copypasta, our grevious error is revealed
