### ISSUE TITLE
Pointing at things makes the pointer arrow show up under the object

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10694]
(WEB REPORT BY: justsumguy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

1fe6a823d2f983f71a81a0c2d80d1ebac15107fe 

> General description of the issue

Point at something bigger than the pointer icon and it 

> What you expected to happen

To see what is being pointed at

> What actually happened

Pointer is hidden behind the object 

> Steps to reproduce if possible

Point at stuff(large machines especially)

**Comment by clusterfack** [comment]
@drcelt PLANES

**Comment by ghost** [comment]
https://youtu.be/sXANrP1738A

**Comment by JustSumBody** [comment]
https://www.youtube.com/watch?v=G_VtQPYq8kI

**Comment by Intigracy** [comment]
So are you going to disappear for 6 months leaving this unfixed
