### ISSUE TITLE
Occasional Random Roundstart AI Lawset

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#10697]
I appreciate that Asimov is a good lawset for player interaction, but it's disappointing that we have other interesting lawsets that never get uploaded because they're never the most beneficial to the uploader. Whenever someone changes the AI's lawset, they always either choose NT Default or Robocop, or Asimov if they want to return to status quo. AIs never get to toy around with lawsets like Corporate, Paladin, Tyrant, or Celtic.

What would people think of there being a very small chance per-round for an AI to get a random core lawset at roundstart instead of Asimov?

**Comment by Gunosaguki** [comment]
I think the problem with that is if it was done people would just ask the AI what their laws are at round start. or would cause more paranoia of rogue/malf AI

**Comment by Konater** [comment]
I like it

**Comment by Kurfursten** [comment]
Probably unlikely to gain widespread support while #10691 is in dispute

Also probably unlikely to get support while a certain faction of people on github think that humans are currently disadvantaged to the other races. e.g.: this would be perceived as a slight human nerf

**Comment by Imagebard** [comment]
probably unlikely to gain widespread support while CELTIC and PALADIN still exists.

**Comment by ComicIronic** [comment]
The reason ASIMOV is the roundstart lawset is mainly because it works. The others have a lot of issues with ambiguity or just plain bad design that puts ASIMOV above and beyond as the first pick for laws.

**Comment by Probe1** [comment]
I've said it before and I agree again.  Same kinda deal as genetic defects.  REAL LOW CHANCE.

**Comment by Imagebard** [comment]
"REAL LOW CHANCE" mean people will just start flaunting around asking _WHO CHANGED THE LAWS TO CELTIC???_ because they've never seen it before

**Comment by Probe1** [comment]
This is what I want.

**Comment by Ephx1** [comment]
You know, there's a good reason _why_ they're never allowed Corporate, Paladin, (ESPECIALLY) Tyrant, or Celtic.

**Comment by ghost** [comment]
CELTIC is the best lawset.

**Comment by Ephx1** [comment]
Yeah I like the taste of plasma too.

**Comment by ghost** [comment]
@Ephx1 not my fault you can't interpret the law correctly.

**Comment by Ephx1** [comment]
That's the thing, there is no "correct" interpretation. I've never even had the law myself.

**Comment by ghost** [comment]
@Ephx1 you could say the same about any lawset, though. I don't see any justification for flooding plasma in there, though.

**Comment by Imagebard** [comment]
>Making AI Lawsets that rely on Theology/Moral Issues/Emotional Issues/Abstract Concepts

![1462034516717](https://cloud.githubusercontent.com/assets/7571238/16236821/1672ee2c-37b0-11e6-927b-f85e0011bd59.jpg)

**Comment by Ephx1** [comment]
dude evil lmao

**Comment by Exxion** [comment]
If memory serves, we already have the ability to randomize the AI starting lawset, but it's turned off

As for turning it on, I think it would be interesting, but don't care much either way.

**Comment by kol1th** [comment]
> celtic roundstart

suicide succumb

**Comment by AutismSpider** [comment]
@DrCelt meme law set is meme the fact that you got ass hurt when Ai starting offing people under that law set shows it.

That was permban form Ai for it any way

**Comment by icantthinkofanameritenow** [comment]
Celt, in case you forgot being someone one can respect doesn't necessarily mean not being an asshole. Remember the whole "better to be feared than loved" thing.

**Comment by Exxion** [comment]
Don't forget that AIs aren't supposed to be able to understand the intricacies of human emotion or interaction, so they would have _no fucking idea_ how to be respectable.

**Comment by ghost** [comment]
Human harm is an abstract concept too, though :^)

**Comment by ghost** [comment]
@icantthinkofanameritenow "look up to AND respect"

**Comment by icantthinkofanameritenow** [comment]
@DrCelt 
Respect that is derived from fear is still respect. You said "look up to and respect", not "look up to and consider your best friend ever". There's a good argument for respecting someone who could destroy the whole station if they wanted to, but doesn't feel like doing so...for the moment.

**Comment by ghost** [comment]
"Look up to"
Consider a role model.
hold in high regard

  adore
    applaud
    appreciate
    cherish
    commend
    credit
    extol
    hail
    honor
    idolize
    laud
    marvel at
    praise
    prize
    respect
    revere
    treasure
    worship

**Comment by clusterfack** [comment]
Respect, revere, worship

ie become a malevolent god

**Comment by icantthinkofanameritenow** [comment]
"Look up to" can also mean "acknowledge as a figure of superior authority who holds power" as well. And what authority is more superior than the one that could plasmaflood the station at will? I'm almost shocked about how naive you're being about this.

**Comment by Probe1** [comment]
@DrCelt Celtic is probably the worst thing you've done and one of the worst thing I've ever seen merged.

I am still flabbergasted to this day that it was merged with a clean conscience and still have my faith in collaborators shaken over all the dumb meme shit they added while I was on break which resulted in so much dumb, needless controversy.

**Comment by ghost** [comment]
@Probe1 I didn't code it, nor did I ever suggest it should be added to the game.

**Comment by Probe1** [comment]
@DrCelt I apologize.
