### ISSUE TITLE
Dead borer eggs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10696]
(WEB REPORT BY: tifora REMOTE: 172.93.109.202:7777)
If nobody signs up to a borer egg, the egg basically dies and there's no way to fix it or reboot the egg.

Come up with a solution.

**Comment by Gunosaguki** [comment]
I'm pretty sure its been this way for a good while, too. like since borer egg was added

**Comment by Shadowmech88** [comment]
It has. N3X15 coded it all, I think.

**Comment by icantthinkofanameritenow** [comment]
I can verify this as well. I suggest having the egg ping ghosts every 5-10 minutes as an alternative.
