### ISSUE TITLE
Burn husk zeroes a body's blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10707]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 0cde9ec9df2d0376d8f32423bf2f532a774e0a20 
> 
> General description of the issue
> Getting 200+ burn on a body to make it turn gray makes it lose all its blood
> 
> What you expected to happen
> That not to happen, make it easy to get walking husks if you burn kit and defib
> 
> What actually happened
> NO BLOOD, MIGHT AS WELL CLONE
> 
> Steps to reproduce if possible
> Weld a body to >200 burn, scan it and behold its lack of blood.

**Comment by Exxion** [comment]
Uh... yes, considering it becomes a husk due to being dried out, I would expect this to be the case.

**Comment by ComicIronic** [comment]
What about the part where you defib them?

**Comment by clusterfack** [comment]
Yeah the thing is though, how you are defibbing someone with more than 200 burn?

**Comment by Allspice** [comment]
Burn them to 215, then apply burn kit to 190 and defib.

**Comment by Exxion** [comment]
Nothing about this seems out of place other than the fact that it is possible at all to defib husks

**Comment by clusterfack** [comment]
You shouldnt be able to burn kit dead bodies tbh familia

**Comment by Gringonius** [comment]
They don't even accept blood, you can't inject blood into them with IVs or syringes. Looks like a feature to prevent reviving husked people.
