### ISSUE TITLE
Unable to secure emitters.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10701]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 14396402a3a2351d619c9f6af173950b9edf3101 
> 
> General description of the issue
> Emitters now can't be secured anywhere. After wrenching, attempting to weld them gives the unwelding text, and says that they are not secured properly when the 'welding' is finished
> 
> What you expected to happen
> To be able to wrench, then secure an emitter to a place.
> 
> What actually happened
> Unable to secure an emitter down, so can't make SMEs in strange places
> 
> Steps to reproduce if possible
> See above

**Comment by PJB3005** [comment]
Descriptive issue names thanks.

**Comment by JustSumBody** [comment]
My bad, fixing it now

**Comment by ghost** [comment]
@PJB3005 Thing is, if I put all the details in the name, then what's the point of the content of the post?

**Comment by 9600bauds** [comment]
Was not autoclosed
