### ISSUE TITLE
MoMMis cannot properly use RCL

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10704]
(WEB REPORT BY: amidaychi REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 75094c3859db477f2cbe86638a27b582585e2cbc 
> 
> General description of the issue
> Mommi's can't properly use RCL
> 
> What you expected to happen
> Use, move, lay cable, *ping
> 
> What actually happened
> Use, move, no cable gets laid besides the first single one, *buzz *aflap
> 
> Steps to reproduce if possible
> 1. Be MoMMi
> 2. Get loaded Rapid Cable Layer
> 3. Attempt to rapidly lay cable
> 4. nope.

**Comment by 9600bauds** [comment]
More layering issues

**Comment by 9600bauds** [comment]
More layer issues

**Comment by PJB3005** [comment]
Not a layer issue.

RCL never worked for MoMMIs.

**Comment by Kurfursten** [comment]
PJB is right, it gets called from carbon move or something

**Comment by PJB3005** [comment]
> called from carbon move or something

Tbh you deserve it for hardcoding like that.

**Comment by clusterfack** [comment]
It needs to be changed to an on_moved event

**Comment by ComicIronic** [comment]
QUALITY

**Comment by Kurfursten** [comment]
@PJB3005 I think I may have explicitly been feeling vengeful toward MoMMIs at the time

It was back ages ago when people were fussy about MoMMIs replacing engineers too well, around the time they tried to push out mommi static
