### ISSUE TITLE
Box trade outpost too big for skipjack to dock

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#10713]
#### Description of issue

The docking on the Box trade outpost intended for the vox skipjack (and salvage shuttle?) goes one tile too far down. The issue in that round was settled when the skipjack's destroy_everything was set to 1
![skipjack 2fat](https://cloud.githubusercontent.com/assets/5942183/16281268/da06304c-38c3-11e6-9b5b-784d81a2a590.png)
#### Difference between expected and actual behavior

The shuttle is unable to dock without destroy_everything = 1. Instead, it remains in the "hyperspace" area until sent to an area it can dock at.
#### Steps to reproduce

Get to the Vox Skipjack
Attempt to send it to the "Vox trading outpost" destination
#### Server revision

c680e4fb1d6856c014105f3afddc38064125e916
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) (Searched for all issues, open or close, with the word "skipjack" and "trader outpost")

**Comment by Exxion** [comment]
Since when is the docking port shaped like that? The airlock on it used to be exposed on all sides except the back specifically so this wouldn't happen.

**Comment by ComicIronic** [comment]
Probably since Dylan made his arrivals changes.

**Comment by Kurfursten** [comment]
I checked. Yep. It's @dylanstrategie 's recent courtroom / Vox outpost change

**Comment by ghost** [comment]
Indeed, there's a problem here

I feel like it would be better if the Vox Skipjack was reshaped so that the extra tile on the docking port was removed. It already has a double airlock, doesn't need a third external airlock for whatever reasons

**Comment by Exxion** [comment]
That third airlock is part of the station, not the Skipjack

**Comment by ghost** [comment]
Right, maybe just push up the docking zone one tile up by extending the shuttle hallway

Should work fine, but I can't do it myself currently
