### ISSUE TITLE
green pomf no like nitrogen

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10719]
![dreamseeker_2016-06-22_21-41-39](https://cloud.githubusercontent.com/assets/6526157/16288464/71481b0c-38c2-11e6-88a4-3b85e85ea802.png)

**Comment by Shadowmech88** [comment]
Why don't we just make the primitive races into human species so they can enjoy the benefits of organs and limbs and breathing different gases?

**Comment by 9600bauds** [comment]
Because that would make too much sense

**Comment by SkowronX** [comment]
But think! MONKEY limbs. Monkey HEADS!

**Comment by Intigracy** [comment]
aren't monkeys a subtype of humans already, or am I wrong

**Comment by 9600bauds** [comment]
No and that caused a monumental amount of shitcode in inventorycode

**Comment by ghost** [comment]
I asked about how to approach this, and it turns out making carbon monkey mobs prefer a certain atmosphere is 'bullshit and should be made into datums'.

That's all I got. Sorry this wasn't fixed before merge.

**Comment by ghost** [comment]
Well, I'll likely make a map hotfix to address arising issues, but that's a pretty major code issue that needs monkey mobs to have the new organ system integrated into them

AKA WYCI, and it's not going to be me. For now, press F to pay respects to Colonel Gravy

**Comment by Shadowmech88** [comment]
Is it possible to make monkeys not breathe at all, for now? Could just make the green chickens not need to breathe so they don't suffocate.

**Comment by Kurfursten** [comment]
@Shadowmech88 Sure. Or you can make them breathe but not require any gas or tolerate any gas. It's trivially easy to change.

We're discussing it in #10762
