### ISSUE TITLE
Bauds what the ungodly fuck is this shit

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10716]
@9600bauds 
If you hit a monkey with monkey clothes, it does put them on the monkey, but it ALSO puts them in your suit storage, regardless of whether or not they actually fit there or there is already something there.
In addition, everything that happens when something manages to be in two inventories at once happens, too, of course.

**Comment by 9600bauds** [comment]
From 1 to 10 how much would you care if I just remove the "slap monkey to instaswap" thing that I made the grave mistake of assuming it worked like I found it

**Comment by clusterfack** [comment]
Just remove it then

**Comment by Exxion** [comment]
I legitimately didn't know about it before you told me, so like 3 because now it takes time to use the stripping menu with monkeys

**Comment by 9600bauds** [comment]
It used to not take any time?

**Comment by Exxion** [comment]
It was instant at least to put things on monkeys. I never really took things off them so I don't know about that.
