### ISSUE TITLE
Disappearing sprites during gun mode

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10725]
(WEB REPORT BY: acedick REMOTE: 172.93.109.202:7777)

> Revision df30c3f4b7edc6f0dba4792a2fde05b5e2d80e42
> 
> General description of the issue
> Any object that changes sprites (eg. cigarette pack when one is taken out, opened lighters) during the gun mode where most sprites become traitor revolvers disappear.
> 
> What you expected to happen
> For a cigarette packet to not turn invisible.
> 
> What actually happened
> Removing a cigarette from it's pack and turning on a lighter to light it made both objects vanish.
> 
> Steps to reproduce if possible
> obtain muh freedoms
> have admins push buttons
> try any sort object that changes sprites
> pull a disappearing trick

**Comment by clusterfack** [comment]
That's not really surprising

**Comment by clusterfack** [comment]
While this problem would initially seem intractable, it actually has quite a simple solution. Make a distinct dmi that holds only the revolver icon as the null ("") icon state. This means that even if any icon state undergoes modification by update_icon, they will still be shown.
