### ISSUE TITLE
Captain's spare ID dislikes closets

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#10727]
Is this a feature or a bug?
![hm](https://cloud.githubusercontent.com/assets/5549060/16291696/4cc4697c-38cf-11e6-9587-575994c02f71.gif)

**Comment by ghost** [comment]
in before someone blames planes

this isn't planes

**Comment by Exxion** [comment]
I cannot think of any logic one could use to think that this has anything to do with planes

Anyway, I can't reproduce this. Had anything happened to that locker in that round?

**Comment by kernikov** [comment]
No, I know that it may have interacted with the supermatter crystal and it's storage box.
I also know that this same behavior had happened with the warden's lockable closet as well.

**Comment by Exxion** [comment]
All in the same round?

**Comment by kernikov** [comment]
Yes

**Comment by 9600bauds** [comment]
Maybe it's tied to the disk?

**Comment by Exxion** [comment]
Tried that.
Had something maybe happened to the ID?

**Comment by Exxion** [comment]
Oh, did you happen to try walking into the ID?
Had there been ZAS shenanigans that round?

**Comment by kernikov** [comment]
I know that the original idea was that the disk and ID were hidden under neither the supermatter crystal and that they (Felicity Rivera and an unknown MoMMI) were attempting to start it.
From what I could tell, they were repeatedly taking it out and putting it back into it's storage box.

**Comment by Exxion** [comment]
Well, basically, the ID must have either become dense or anchored
I don't know of any way for an item to become anchored, but ZAS can, on rare occasions, fuck up and cause an item to remain dense eternally.
If you were able to step over the card if you dropped it, though, then it must have somehow become anchored.
If you're not sure, then it  was PROBABLY ZAS shit, but possibly not

**Comment by Exxion** [comment]
In the not particularly likely event you encounter this again, with this or any other item, try throwing said item against a wall and trying again. And then tell someone whether or not it worked.

**Comment by Exxion** [comment]
Actually don't bother because it won't work.

**Comment by TheFriggenSawbones** [comment]
is it something to do with the new ultra mega unkillable unmovable lockers

**Comment by Imagebard** [comment]
Oh yeah, that's a infinite health armoury locker.
Not sure why he would code something to stop people form punching it, though.

**Comment by Exxion** [comment]
No
I said what caused it
And he said it happened with another locker, too
