### ISSUE TITLE
No Minihoe on Box Outpost (Additional Dylan Regrets)

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#10729]
In addition to #10719 and #10713 there is no longer a mini hoe on the outpost making it impossible to remove weeds.

Thanks @dylanstrategie

**Comment by Kurfursten** [comment]
Also you took the crates out of the vendor room. I used those to move stuff from the vendors to the trade ship.

A plant analyzer and hatchet would be a plus while you're at it.

**Comment by ghost** [comment]
Jesus christ, do we have a single thing in the code that actually gives you all the tools you need and doesn't need you to add a dozen extra tools in post

I'll try and cobble together a full kit, but that really needs checking

**Comment by Kurfursten** [comment]
There was an old botany crate on the previous Box outpost, like the one on Deff Vox outpost, which contains everything you need. I suggest checking that to see what it has.

**Comment by ghost** [comment]
I've opted out for a locker with modified access vars for now, copied straight from Box Botany
