### ISSUE TITLE
Prosthetics being included in overall health doesn't make sense

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#10728]
Right now wooden and robotic limbs are grouped in with your overall health. Due to this, silly things can happen such as going into crit solely from inorganic limb damage. Your body can also start going into shock just from having a damaged prosthetic. Why the hell should my body care that my peg leg is broken?

Related to #9454 #8114 #7627 #6500

<sub>Also there should be a less frustrating way to fix ~~robotic~~wooden limbs like fuck we got walking trees  on the station why can't they use tree magic to heal them aaaaaa</sub>

**Comment by Ephx1** [comment]
What's frustrating about Welder/Cable Coil? I don't even know how to fix wooden limbs though.

**Comment by chatsonf** [comment]
@Ephx1 OOPS I MEANT TO PUT WOODEN LIMBS AAAAA fixed

And there also isn't a way to fix wooden limbs right now, once they take damage they are fucked for the rest of their existence.
