### ISSUE TITLE
Stupid feature request: Wizard Wars

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10734]
Yes my choice of timing to post this is memeing but I've actually had this idea for a long time, even under this name.

Basically works like this:
1. Everyone is a wizard.
2. With exactly one objective.
3. Which is to escape alone.

Obviously it would have to be a bus-only gamemode.

Still not sure how to prevent the wizards from just murdering each other as soon as they spawn, before they have a chance to choose spells, though. Maybe make everyone invincible for the first minute or something?

**Comment by icantthinkofanameritenow** [comment]
Where are the meme tags where you need them?

**Comment by Exxion** [comment]
If you're hoping for WYCI then OK  because I totally would code it myself if it weren't for the fact that I know approximately fuckall about gamemode code and can't be assed to learn something that people keep being about to overhaul

**Comment by clusterfack** [comment]
Obviously just copypaste highlander but with wizards

**Comment by Exxion** [comment]
Fair enough
I forgot about Highlander

**Comment by Exxion** [comment]
Actually I think I'll do something a bit better than just copypasting it
I'm a lazy fuck so gimme a day or two

**Comment by icantthinkofanameritenow** [comment]
I was also thinking of the "HONK" tag too.

**Comment by Shadowmech88** [comment]
I recommend assigning each spell a "strength" and giving everyone random spells up to a maximum cumulative strength. So you can for example have one or two really good spells, or a bunch of not-so-good spells.
Requiring players to choose their spells would slow the mode down quite a bit, I think.

**Comment by Exxion** [comment]
> a day or two

How naive I was
Oh well, I still did it
