### ISSUE TITLE
stupid feature request: laser wars

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#10733]
To spice up mixed rounds.

Two teams of semi antags (minimize civilian casualties enforced by rules) with special space proof laser tag helmets and hardsuits that are unable to be removed and gib the wearer when shot by the other teams laser twice over the span of one min.

Two opposing companies that do trade with NT are in a shadow war with each other and decided on your space station to do battle. They spawn in a random room in mantanance oppisate from the other team and have maintenance IDs.

For a team to win all of the opponents must be killed or have a team member excape on the excape shuttle with no enemy team members on it.

Its still traitor/ling/vamp but now there is a harmless war going on around it.

**Comment by Imagebard** [comment]
Maybe instead of all of this, I have a better idea.

Add extra equipment to the laser tag locker. Everything needed to build around 4 laser tag turret, 2 laser tag ED-209's and 10 spare laser tag armors and guns.
Now we can REALLY up the laser tag without having to forcing mechanics and roboticists to do something unrelated to their actual job.

**Comment by TheFriggenSawbones** [comment]
ok let me give you my idea

you start off on the station when centcomm tells you it's time to angle, basically you're given ten minutes to prepare your rods and boats and after that you have to go around space and catch the biggest fish. 30 minutes later the crew is judged based on a few factors, rarity of fish, size, sheen, eyes. The victor is crowned the Fisher King and the round proceeds like normal.

**Comment by Konater** [comment]
Better better idea.
Add a red and blue flag for the teams to defend with a big in hand sprite.
Add a laser tag arena away mission.

**Comment by icantthinkofanameritenow** [comment]
WYCI

**Comment by Imagebard** [comment]
Really.

**Comment by Imagebard** [comment]
What the fuck is the point of the WYCI tag if everything gets it

**Comment by ComicIronic** [comment]
WYCI isn't invalidated by the number of issues which are tagged with it.

**Comment by Imagebard** [comment]
But its tagged on EVERY issue.
Shit ones. Good ones. Killette2 ones. Average/Normal-ones. What is it supposed to MEAN?

**Comment by ComicIronic** [comment]
"This will happen when you code it".

**Comment by Shadowmech88** [comment]
The WYCI tag is for feature requests that are so large in scope that the only way they will ever happen is if the requester himself codes them.

Regular feature requests at least have a _chance_ of being fulfilled by someone else.

**Comment by Imagebard** [comment]
Oh. I thought it was something about quality.
