### ISSUE TITLE
blunderbluss

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10732]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

you cant load it with glasses, beakers, bottles and stuff

**Comment by ghost** [comment]
To add detail to this report

Blunderbusses can't accept anything that could contain straight reagents, like glasses, cups, beakers, etc.

Guess it's so you don't load your fuel mug into your gun

**Comment by Shadowmech88** [comment]
I recently changed it so that it ONLY rejects open containers.
Have you tried loading a beaker with a lid into it?
