### ISSUE TITLE
Box Station Toxins Storage floods all of science

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10749]
(WEB REPORT BY: kolith REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b6b92761b82a936fb5737781ccab28448438a7ae
> 
> General description of the issue
> Toxins storage floods all of science with plasma
> 
> What you expected to happen
> Plasma to remain in toxins storage
> 
> What actually happened
> science flooded with plasma.
> 
> Steps to reproduce if possible
> Open a plasma canister on Box Station's toxins storage

It's probably mapped all fuckily. God please fix it.

**Comment by kol1th** [comment]
very important

**Comment by kol1th** [comment]
forgot to say it's all as AI and it KEEPS HAPPENING

**Comment by 9600bauds** [comment]
This one?
![dreamseeker_2016-07-19_04-21-06](https://cloud.githubusercontent.com/assets/6526157/16941717/3be4dd50-4d68-11e6-8d40-a4f00078b17c.png)
Seems to work fine

**Comment by Probe1** [comment]
Can't reproduce.
