### ISSUE TITLE
Vox heist shuttle trying to destroy an area on boxstation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10741]
(WEB REPORT BY: pseudonym REMOTE: 172.93.109.202:7777)
ADMIN LOG: WARNING: vox skipjack (/datum/shuttle/vox) attempted to destroy the Vox Trade Docks (/area/vox_trading_post/docking). If you want vox skipjack to be able to move freely and destroy areas, change its "destroy_everything" variable to 1.

**Comment by Exxion** [comment]
#10713
