### ISSUE TITLE
Xenomorph "pockets" are broken

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10753]
If a xenomorph tries putting a facehugger in their pocket, the hugger simply falls to the ground. Later, due to reasons I can't pinpoint the game just begins to refuse letting you try placing the facehuggers there, like if the pockets were full.
Been happening this past week or two every time I become a xeno. Unfortunately I can't tell which day it stopped working since xenos aren't too common.

**Comment by 9600bauds** [comment]
Ran into this when working on stripcode, was not sure how any of this was supposed to work. Xenos also have chest and head slots that totally do not even work at all and haven't worked for a long, long time.
ARE you supposed to be able to store facehuggers in your pockets as xeno?

**Comment by Shadowmech88** [comment]
Yes, you're supposed to be able to store facehuggers in your pockets as a xeno.

The head and chest slots may be a relic from another codebase. I know I've seen screenshots of xenos wearing labcoats and such, but I've tried using the strip menu before to put clothes on a xeno and it didn't work.

**Comment by Killette2** [comment]
Man I really wish I had that medbay is xenos picture right now where they're all dressed up as doctors...

**Comment by 9600bauds** [comment]
I've got to wonder how old that picture is, I couldn't find any evidence of those slots ever working in the code

**Comment by 9600bauds** [comment]
Also, the issue with uniforms on xenos is that they have a completely different lying down icon where it looks like they're sleeping. Since nobody will ever make a "xeno lying down" sprite for every suit in the game, the only other alternative is having the equipped items disappear when a xeno lies down

**Comment by Shadowmech88** [comment]
Their dead sprite is different from their resting sprite and their living sprite, as well.

I think it's fine for the clothes to just disappear.

**Comment by 9600bauds** [comment]
I COULD make it work
But it would require unfucking updateiconcode
Which is awful
