### ISSUE TITLE
Can't construct an ED-209 with tasers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10752]
(WEB REPORT BY: justsumguy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c4cd8f15fa9750fe4f974a75e61e8383a0b8d681
> 
> General description of the issue
> Attempting to construct an ED-209 with a security vest and taser is impossible past the wiring step
> 
> What you expected to happen
> "You attach the taser to the wired ED-209 frame!"
> 
> What actually happened
> Taser wouldn't attach, no tool would do anything to the wired assembly
> 
> Steps to reproduce if possible
> Spawn in parts to construct an ED, attempt to construct it

In one case, attempting to use any items on the frame caused me to just drop the item 

No idea if this also holds true for laser tag EDs

**Comment by clusterfack** [comment]
@intigracy did you touch this?

**Comment by Shadowmech88** [comment]
#10549

**Comment by Intigracy** [comment]
That doesn't touch the build steps though.

W/e I'll fix it.

**Comment by JustSumBody** [comment]
It could have been broken long before your change
I honestly can't remember the last time I've seen someone build an ED

**Comment by Pwirby** [comment]
Isn't it because ED can be set to fire laser ?
