### ISSUE TITLE
Air pipes layered below disposal pipes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10756]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c4cd8f15fa9750fe4f974a75e61e8383a0b8d681 
> 
> General description of the issue
> Atmos pipes are layered below disposal pipes
> 
> What you expected to happen
> Air pipes to be layered above disposal pipes
> 
> What actually happened
> Need to alt-click to access the air pipes
> 
> Steps to reproduce if possible
> Pull up floor tiles somewhere that there are air pipes and disposal pipes on the same tile

**Comment by kol1th** [comment]
planes indeed

**Comment by Intigracy** [comment]
@DrCelt
