### ISSUE TITLE
Preliminary TestStation feedback/requests

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10751]
Where we raise our hands in an orderly fashion to demand shit to be put in the test station.
Basically the idea is to minimize the shit you'd have to spawn every time you were to restart the serb to test something. When you're testing something like, say, a new gun you're coding, it's simple to just spawn it in since it's just one thing, but quality of life is not having to spawn a toolbox and spare ID and atmos suit etc etc.

QoL for testing:
- Starting area should immediately have a loaded toolbelt and admin ID within hand's reach
- Prepared metal and glass and rglass sheets
- Atmos suit with prepared oxygen tank and jetpack

Stuff that would be a bitch to spawn in if you had to test something with them:
- Gateway
- Surgery table with tools, incl. the advanced tools. A pre-spawned human would be cool too
- Chemmaster and chemdispenser
- Cryo, which is hell to make from scratch. Freezer should start on if possible
- I've needed to test things with the cloner a couple times, would be nice to have one with infinite biomass. Also an energy axe to "ease" the cloning process.
- Full R&D set, with starting materials. No need to have stuff to scan since you get the MAXIMUM SCIENCE debug option right in the menu.
- Hydroponics, though probably doesn't need many trays
- Telepad
- Maybe a compact row of gas miners, like you see in Deff
- Cargo shuttle?

Other stuff:
Maybe we could use light tiles for lighting the place without having walls or floodlights around?

**Comment by clusterfack** [comment]
If were talking about a coder who has all the extra configs disavled, starting a server with few to no simulated turfs or dynamic kighting will always be nearly instant for him

So add all the systems that are pre set up, RnD tcomms some prebuilt engines, all of it.

**Comment by 9600bauds** [comment]
Hypothetically speaking how much slower would be to just have Box z-level 1 without the extra space and the rest of the z-levels
Because if it's anything less than 0.5 seconds I say do that

**Comment by Iamgoofball** [comment]
guys lets just put all the departments on the map!!!

_5 weeks later_

test map startup is too slow, how can we fix

**Comment by 9600bauds** [comment]
As far as I understand most of the startup is from the other z-levels and all that empty space, especially the Asteroid

**Comment by clusterfack** [comment]
Yeah goofball, thats how it would be, if we didn't know exactly what lagged on startup. Except that we do.
