### ISSUE TITLE
18 days since Deffciency renders should've been updated.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#10750]
18 and counting, any way.

**Comment by Konater** [comment]
I forgot to do one for the last prison change I did make one before
https://drive.google.com/open?id=0B_Bv_tVbIjxddUlMdTJwS1NoTjg

**Comment by kernikov** [comment]
This doesn't help if it's not the one linked to in-game.

**Comment by Intigracy** [comment]
2 2

**Comment by kernikov** [comment]
2 5

**Comment by clusterfack** [comment]
Update em fags :^)

**Comment by kernikov** [comment]
3 3

**Comment by clusterfack** [comment]
I have yet to receive an updated map render rar of the images, nor has anyone asked pomf for access toe the map render dropbox to put them in.

**Comment by Intigracy** [comment]
What are the steps to update the render?

I'll update the renders regularly if I get access.

**Comment by clusterfack** [comment]
1. Open map in DD
2. Debug verbs
3. Generate map render, takes 2 minutes

**Comment by Intigracy** [comment]
I'll ask pomf for access then.

**Comment by Intigracy** [comment]
he said you do it so I'll just send you renders every saturday w/e

**Comment by 9600bauds** [comment]
was this fixed

**Comment by 9600bauds** [comment]
no idea what to tag it

**Comment by PJB3005** [comment]
How the hell did I manage to click that.

**Comment by Intigracy** [comment]
today is saturday

will do soonTM

**Comment by kernikov** [comment]
On the 41st day, another hero makes an attempt.

**Comment by PJB3005** [comment]
I just updated the renders in the Dropbox a couple hours ago but it didn't seem to have taken effect.

@d3athrow @clusterfack

**Comment by Intigracy** [comment]
yeah it's still not updated, what's up

**Comment by PJB3005** [comment]
Ask @d3athrow

**Comment by Kurfursten** [comment]
@Probe1 This actually was fixed

...But it's an issue again because it's mega out of date and doesn't have the modern black medbay

**Comment by Probe1** [comment]
We need documentation on how to do it somewhere in the wiki.

**Comment by ihadtoregisterforthis** [comment]
Fixed, right?

**Comment by Probe1** [comment]
ya
