### ISSUE TITLE
Move paper formatting from bbcode to Markdown.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10768]
Seriously bbcode is shit, Markdown is way better.

@ririchiyo tried this but people got mad because they couldn't be bothered to learn a proper markup format.

**Comment by ComicIronic** [comment]
I think the reason people got pissed was that nobody updated the wiki or older books.

**Comment by kol1th** [comment]
yes please

**Comment by 9600bauds** [comment]
Why is markdown supposed to be better again
It's like bbcode except it uses commonly used characters for tags so it's annoying and easy to accidentally strikethrough your text and such, and you couldn't even fix the formatting in-game since you can't edit
I really don't see the advantage

**Comment by clusterfack** [comment]
Yeah wait until AFTER I fix papercode to suggest this, fags

**Comment by Shadowmech88** [comment]
Won't doing this break literally every book that's already in our library?

**Comment by kol1th** [comment]
@Shadowmech88 i would assume so

**Comment by Intigracy** [comment]
well, breaking regex didn't.
