### ISSUE TITLE
Box's chemistry suggestion

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#10767]
on boxstation, inside chemistry, there are a total of 3 large beakers; usually 2 of them are used for cryomix and one is used to mix chems.
this is good if there is just one person doing chemistry, but if there are 2 people doing it, the second person doesn't have another large beaker to mix, so he should use a small beaker or go searching for another large beaker at cargo or science.
coordinate 2 chemists is pretty hard already, having another large beaker could help.

can't remember how many large beakers are on Meta's chemistry, maybe you could add another beaker there too.

Bus station's chemistry should have 4 or 5 large beakers so it's fine.

**Comment by SysadminJeroen** [comment]
Something like this?: https://github.com/Jeroen52/vgstation13/compare/Bleeding-Edge...Jeroen52:map/add-one-beaker-to-box-chemistry

**Comment by uazuaz** [comment]
if that means that you added a large beaker inside Box's chemistry, yes, many thanks.
please check Meta and Deff too, there should be at least 4 large beakers total inside chemistry there too.

**Comment by 9600bauds** [comment]
Not sure about this, you're invalidating cargo even more and making Medbay even more monotonous

**Comment by uazuaz** [comment]
well, if that's the reason it's ok  for me to leave it as it is now then.
if you want to discuss about it, any decision is good for me.

**Comment by FudgePucker** [comment]
Oh boy I can't wait to deal with science or cargo in order to do my job!
Because they are always filled with helpful people who aren't FUCKING INCCOMPETENT 

Just add another large beaker.

**Comment by SysadminJeroen** [comment]
@FudgePucker I will make a pull request.

**Comment by SysadminJeroen** [comment]
#10787

**Comment by ihadtoregisterforthis** [comment]
If the PR is not happening, should this stay open?

**Comment by ComicIronic** [comment]
Well if people want to have further discussion about it, but otherwise we can just close.

**Comment by ConkerDev** [comment]
Two chemists can finish their job in 10 minutes and just go get drunk on the bar with Beepskies. Asking them to go beg for beakers is not too much, I think
