### ISSUE TITLE
Werewolf antag WHEN

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#10770]
We've got:
Vampires
Blob
Frankenstein style creatures
And more.

All we need now is Werewolfs and Space-Mummies.
GET TO IT CODERS COME ON

**Comment by NigglyWiggly** [comment]
Rude

**Comment by kol1th** [comment]
when you port it from goon

**Comment by ghost** [comment]
We have space mummies tho

**Comment by AutismSpider** [comment]
if we got goon werewolf see some one with bag/box full of organs for cheap healing/disarm spam only being disarm spam by werewolf can kill you.
