### ISSUE TITLE
norris sometimes doesnt resurrect

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10776]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if  you kill him too fast after he resurrects there is a change of not resurrectign anymore
> 
> What you expected to happen

to resurrect

> What actually happened

ded

> Steps to reproduce if possible
> kill norris
> wait form him to resurrect
> kill it again
> he doesnt resurrect anymore

**Comment by Spacedong** [comment]
poor norris

**Comment by ghost** [comment]
Is this a bug or intended?

**Comment by JustSumBody** [comment]
I feel like it would make sense for him to not regenerate from burn damage. 
But nothing I'm seeing suggests that's supposed to happen, it's probably a bug.

**Comment by Shadowmech88** [comment]
Tested, this still happens.
Also, it's not just burn damage. I was able to stop him from regenerating with an energy axe.
