### ISSUE TITLE
Buggy gift wrap

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#10784]
can gift wrap people  at long ranges

**Comment by kol1th** [comment]
...with telekinesis?

**Comment by Exxion** [comment]
Please be a bit more specific @AutismSpider

**Comment by kernikov** [comment]
You click someone as you run past and they get wrapped if they don't move.

**Comment by kol1th** [comment]
IT'S
*LOOSE*

**Comment by kol1th** [comment]
I couldn't recreate it two rounds ago by the way.

**Comment by Furbeh** [comment]
Can confirm, Spare Ribs / A bumbling idiot was a clown and long-ranged wrapped me around 7:00 Station time

**Comment by AutismSpider** [comment]
Were you the hop?

I know i wrap up the Hop the Det Mime and Vox Medical Doctor.

**Comment by Furbeh** [comment]
Detective, you wrapped me and the mime up when we were at the bar.
