### ISSUE TITLE
Click-upgrading power cells in cyborg recharger as a cyborg ejects desired cell.

### ISSUE THREAD

**Issue by SysadminJeroen** [d3athrow/vgstation13#10781]
#### Description of issue

Click-upgrading power cells in cyborg recharger as a cyborg ejects selected cell.
#### Difference between expected and actual behavior

It should just upgrade your power cell.
#### Steps to reproduce
1. Put better power cell in Cyborg Recharger.
2. Enter it as a cyborg.
3. Click on the recharger, for the upgrade.
4. Select better cell.
5. Cell will be ejected from the Cyborg Recharger. **In previous versions it would normally upgrade your selected power cell.**
#### Length of time in which bug has been known to occur

This bug seems to occur since before 5d2312445b6e8f902574ad104679dc1db47b2231
I have made an attempt to bisect further, but if I try to compile code before that I'm getting multiple errors.
#### Server revision

ca982e238965f717d7bf95ecf4dffc56d822246a
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Ephx1** [comment]
Probably not a bug, you're supposed to use a verb now I believe

**Comment by SysadminJeroen** [comment]
@Ephx1 It still shows which cells you can upgrade when you click it, and allows you to 'upgrade' to them.

**Comment by Ephx1** [comment]
Ahhh, I misread that in-game then, my mistake

**Comment by kol1th** [comment]
@Jeroen52 I thought I was crazy too. Read it more carefully. It asks which one you want to eject. This isn't how it used to work though.

**Comment by PJB3005** [comment]
Can confirm this and it sucks.

**Comment by 9600bauds** [comment]
This might have been me, I'll look at this tomorrow, it's late here. Someone recently removed the restriction on calling attackself on your location, right?
To confirm: Does using the verb work?

**Comment by PJB3005** [comment]
Yes, it does.

**Comment by 9600bauds** [comment]
Well it seems that silicons can now somehow attack_hand their own location once again and I have absolutely no fucking clue how is this even possible
