### ISSUE TITLE
add a "bag" type system for getting ammo into a magazine

### ISSUE THREAD

**Issue by Spacedong** [d3athrow/vgstation13#10793]
What I mean by the title is, instead of having perfect pixel precision, and taking bullets from a pile on the ground and painfully slowly inserting them into a magazine, have magazines function as "bags" where if you click a pile of bullets on the ground and the magazine can use them, they are transferred into the magazine, kind of like how a plant bag functions. 

EDIT: could work with speedloaders too I guess

**Comment by Shadowmech88** [comment]
>pile of bullets on the ground

When do you encounter piles of loose bullets on the ground? All bullets that aren't shotgun shells come in ammo boxes, that can be directly loaded into magazines.

**Comment by Spacedong** [comment]
i did not know this
