### ISSUE TITLE
There are no space-worthy suits for dionas in science/research outpost

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#10799]
#### Difference between expected and actual behavior

Expected: Can't wait to wear my excavation/space suit and be a useless piece of shit autist all shift!
Actual: Have to rush to the mining outpost using anomalist suit and grab a mining hardsuit if i want to avoid taking pressure damage all shift
#### Steps to reproduce

Join as scientist diona and search for a space-worthy suit that fits your xboxhueg body
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Ephx1** [comment]
Not only should Dionae not be able to wear hardsuits/softsuits in the first place, but they already have the pressure resistance to make a space trip a harmless task. Especially now that space doesn't actually burn you instantly, just makes you fall asleep.

So really all you need to do is keep warm.

Although you might as well give them access to all suits considering that original nerf to them is completely pointless with how ineffective space is to them now.

**Comment by ghost** [comment]
Just grab a space blanket and a cup of coffee, man

**Comment by Intigracy** [comment]
Did space is not cold get merged?
