### ISSUE TITLE
Players appear under hyperspace

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10791]
Because @DrCelt is a fucking nerd and asked me to make a separate report for this in #10779

**Comment by ZeWaka** [comment]
On Goonstation, this is an issue with your BYOND not being up to date. That could possibly solve it for you.

**Comment by Exxion** [comment]
I have the newest version
No, this is Celt's fault, more than likely

**Comment by clusterfack** [comment]
Nah we just changed planes

**Comment by Intigracy** [comment]
not more than likely, this is celt's fault

he said he'd fix it today, let's see if he lied
