### ISSUE TITLE
Wizard Apprentices don't get wiz hud elements

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10801]
(WEB REPORT BY: gutlesscoward REMOTE: 172.93.109.202:7777)

> Revision 9709e5d58d69e0e097496e3af7870ca97eb44066
> 
> General description of the issue
> Apprentices made using the apprentice scroll can't see the little wizard hat icon that denotes someone as a wizard. this leads to problems when one is trying to stealth and the other is murdering everything on sight.
> 
> What you expected to happen
> I expected my apprentice to know that I was a wizard despite the disguise
> 
> What actually happened
> I got murdered to death by my apprentice, who didn't know I was a wizard.
> 
> Steps to reproduce if possible
> 1. Be a wizard
> 2. Buy apprentice scrolls. I picked muscle wizard.
> 3. remove your robes and wear a disguise.
> 4. meet up with your apprentice

**Comment by Konater** [comment]
If we made them wizards instead of traitors they would get the hud
more importantly they would be able to fly on broomsticks

**Comment by AI-Is-Rogue** [comment]
> more importantly they would be able to fly on broomsticks

THIS
