### ISSUE TITLE
Camera is broken

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#10808]
#### Description of issue

Camera photos are messed up, crayon drawings aren't properly shown, people are always naked
![BROKED](http://i.imgur.com/Q0MjhXr.png)
#### Server revision

1ebca9ab941d1fe93da156f2189b64d07c2752d2
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

OTHER ISSUES ABOUT IT: #10807 #10561

**Comment by clusterfack** [comment]
>Couldn't find an existing issue about this

You didn't even try

**Comment by kernikov** [comment]
Don't the previous issues say something along the lines of "No one knows how the code for those black magic devices works, let alone why it doesn't"?

**Comment by SysadminJeroen** [comment]
Since when is it broken, and when did it still work?

**Comment by clusterfack** [comment]
The fact those previous issues exist is why this one should not

**Comment by SysadminJeroen** [comment]
Bisect log.

```
git bisect start
# bad: [61dec3201a1590c3f02d5ec80b4e6ac8fd3f3485] Automatic changelog update.
git bisect bad 61dec3201a1590c3f02d5ec80b4e6ac8fd3f3485
# good: [5d2312445b6e8f902574ad104679dc1db47b2231] Tomb of Rafid: The Away Mission (#10206)
git bisect good 5d2312445b6e8f902574ad104679dc1db47b2231
# skip: [b80490283a7206c45d2c0667c5bc2e01dd676ef6] Perma friendly Plasma Man suits. (#10415)
git bisect skip b80490283a7206c45d2c0667c5bc2e01dd676ef6
# skip: [cddbd7958f37f1f3ef3ef84d45f02e10eebbbd8d] Adds gavel block and hammer (#10384)
git bisect skip cddbd7958f37f1f3ef3ef84d45f02e10eebbbd8d
# bad: [d08cb4ac81de5317838d888a5171048e68717fe9] Revert "One-Way Windows" (#10535)
git bisect bad d08cb4ac81de5317838d888a5171048e68717fe9
# bad: [bc7fa76ef20b5a399a2d4e5dbcceb27def3b34fa] Tilebound (#10402)
git bisect bad bc7fa76ef20b5a399a2d4e5dbcceb27def3b34fa
# good: [27b582cb4186e4981099647aad1546e497258e56] Merge pull request #10333 from clusterfack/htmlinterface
git bisect good 27b582cb4186e4981099647aad1546e497258e56
# good: [4cee6922d52fb0f439fd92ab3c9574ec4ca4a836] Automatic changelog update.
git bisect good 4cee6922d52fb0f439fd92ab3c9574ec4ca4a836
# bad: [aa00474a590993f01251a866c9af78d0615f7a44] Deff tradeship (#10319)
git bisect bad aa00474a590993f01251a866c9af78d0615f7a44
# good: [e5bbbcf7876591595781f0e06064376194c356cf] Automatic changelog update.
git bisect good e5bbbcf7876591595781f0e06064376194c356cf
# bad: [75d79b3c23b19f4f4d6ee0cde9839b42f668184d] Hand refactor (#10045)
git bisect bad 75d79b3c23b19f4f4d6ee0cde9839b42f668184d
# first bad commit: [75d79b3c23b19f4f4d6ee0cde9839b42f668184d] Hand refactor (#10045)
```

Looks like 75d79b3c23b19f4f4d6ee0cde9839b42f668184d is where the bug started.

**Comment by SysadminJeroen** [comment]
Worst part is, the code is not **A T O M I C**

**Comment by SysadminJeroen** [comment]
Re-open please.

**Comment by SysadminJeroen** [comment]
Please note that I have only bisected the nakedness, and not the crayons.

**Comment by PJB3005** [comment]
This is why squash merge is bad.

**Comment by clusterfack** [comment]
Why pjb

**Comment by ComicIronic** [comment]
Bisecting is 100% better if we just rebase squash ourselves.
