### ISSUE TITLE
item layering is borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10804]
(WEB REPORT BY: cumoverme REMOTE: 172.93.109.202:7777)

> Revision
> 9709e5d58d69e0e097496e3af7870ca97eb44066
> 
> General description of the issue
> https://u.pomf.is/oovirc.png
> Items you hold are being shown behind everything else, very perceptible with eswords and corgis.

**Comment by clusterfack** [comment]
@drcelt PLANES

**Comment by Intigracy** [comment]
@drcelt YOU SAID YOU'D FIX THIS TWO DAYS AGO

**Comment by Intigracy** [comment]
actually revert planes when

**Comment by ghost** [comment]
I noticed that the battering ram did really silly things and showed behind my character and I thought I had fucked up its in_hand icons

I guess not
