### ISSUE TITLE
The sleeper on the DJ sat has no console

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#10806]
not sure if this is intentional
![dj](https://cloud.githubusercontent.com/assets/19157295/16403394/4f2a58a4-3cba-11e6-9b99-12891a59b5fd.png)

**Comment by TheManNamedTom** [comment]
It's been like this for a long time, but I can't see any reason why there wouldn't be a console here.

**Comment by AutismSpider** [comment]
rebuild it and it have a cnsole

**Comment by sonime** [comment]
At first it had no console. Then it automatically had a console that was in the window. Now it has no console.

That sleeper isn't meant for healing.

**Comment by aceedex** [comment]
It's not a sleeper for two, so I fail to see the point. I don't think sleepers made from a flatpack have a console either

**Comment by 9600bauds** [comment]
It's for muh flavors I guess
Then again it could just be moved one tile to the left and given a console and I don't think anyone would care

**Comment by ihadtoregisterforthis** [comment]
This was intended at some point, because it's there just for flavor

**Comment by Durgen** [comment]
it's pretty weak flavor tbh

**Comment by 9600bauds** [comment]
I don't disagree

**Comment by 9600bauds** [comment]
Why did you black yourself out?

**Comment by Durgen** [comment]
[spoiler]I posted this issue during a round[/spoiler]

**Comment by 9600bauds** [comment]
nice try I see the blue blood on the DJ sat now I know where my target is >:)

**Comment by ghost** [comment]
Frankly we should just dump the sleeper, we don't use sleepers for this anymore

A bed is good enough, use the space to make a really comfy bedroom
