### ISSUE TITLE
Borers STILL able to easily kill their hosts

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#10814]
People use it as a tool to get valids. I think we should remove any drug that can OD (SPACE DRUGS) or make them incapable of overdosing.

**Comment by Ephx1** [comment]
This wouldn't be as bad if we didn't have like 3 other borers in the body being absolutely retarded and having to clean up the shittons of chemicals they produce.

**Comment by ComicIronic** [comment]
What's the issue?  Non antag borers who kill their hosts are an admin problem, and borers killing antags seems fine to me.

**Comment by kol1th** [comment]
@ComicIronic It's a common problem that shouldn't be a problem. Why can they even overdose?

> borers killing antags seems fine to me.

Even if they're your host?

**Comment by TheFriggenSawbones** [comment]
Borers are supposed to be in a symbiotic relationship with their host, it's not really a neat symbiotic relationship when you OD your host on hyperzine plus it opens up issues like, well I saw him doing something sketchy so I OD'd my host srry he wasn't antag lol

**Comment by TheFriggenSawbones** [comment]
prob just limit how much of a dangerous chemical they can produce/make it in relation to how much is in the host's body

dont really remove anything

**Comment by PJB3005** [comment]
IMO space drugs should just be removed from borers.

Hyperzine is fine but the ability to OD is not.

**Comment by PJB3005** [comment]
Goddamnit GitHub when I hit comment and I begin scrolling up don't fucking reset my scroll to the bottom so I click just as my mouse is over "assign self".

**Comment by kol1th** [comment]
@ComicIronic Also killing ANY host as a borer is highly fucking illegal. Have you played at all in the last 2-3 months?

**Comment by Shadowmech88** [comment]
I've had borers intentionally kill me with overdosing twice in the past, and both times the player just got a slap on the wrist.
I don't think admin punishment is a big deterrent for borer players like these.

**Comment by AutismSpider** [comment]
@Shadowmech88  Admin need step there shit up not going happen any way half them are massive jerk offs and the only who gave out real punishment is dead and gone.

**Comment by kol1th** [comment]
@Shadowmech88 Ghlor was on at the time so they got a ding dong bannu. God bless.

**Comment by kol1th** [comment]
This has been somewhat fixed by adding an overdose warning on stuff, good enough for me I guess.
