### ISSUE TITLE
Health HUD scanner

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10829]
(WEB REPORT BY: edwarus REMOTE: 172.93.109.202:7777)

> Revision 85c275257b9e840407c9d3258de0168140f4fd34
> 
> General description of the issue
> Health HUD scanner does not work if you are a monkey
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible
> turn yourself into a monkey

**Comment by PJB3005** [comment]
I believe this is because it's handled entirely in `Life()`

**Comment by Exxion** [comment]
It's in `handle_regular_hud_updates()`, which is kind of a clusterfuck as it stands

Please forget the comment that used to be after this stating that I was wrong,  because I was in fact wrong about being wrong

**Comment by Exxion** [comment]
Or not? Could have sworn it was in there

**Comment by Intigracy** [comment]
I tried to get this to work but gave up, good luck.

**Comment by Kurfursten** [comment]
Partial duplicate of #7025

**Comment by PJB3005** [comment]
Could use a plane for this...
