### ISSUE TITLE
Golden Apple Tart Recipe

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10831]
(WEB REPORT BY: consedfu REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Golden Apple Tart Recipe is messed up.
> 
> General description of the issue
> I put in 5 Milk 5 Flour 5 Sugar 1 Egg 1 Golden Apple, and I get Rubbish. That is the formula that is on the wiki.
> 
> What you expected to happen
> The recipe would make a Golden Apple Tart in the microwave.
> 
> What actually happened
> I got Rubbish.
> 
> Steps to reproduce if possible
> Put 5 Flour 5 Sugar 5 Milk 1 Golden Apple 1 Egg in the Microwave, then cook.

**Comment by Kurfursten** [comment]
The correct recipe is 5 Sugar, 5 Milk, **15 Flour**, 1 Egg, 1 Gold Apple

Fixed the wiki, this is safe to close
