### ISSUE TITLE
There are two messages that can appear to mice while nibbling on things, but they're not really different

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10832]
![image](https://cloud.githubusercontent.com/assets/9827785/16436795/e5694046-3d6e-11e6-8e6e-4c9f6282abcd.png)

**Comment by 9600bauds** [comment]
I looked into this once
For SOME reason, the blue messages are visible only to you, and the black ones are visible to everyone
It's random which color it will be
I know, it's dumb

**Comment by clusterfack** [comment]
Is it still showing visible messages to you and showing you the ones everyone else sees, in all cases?

**Comment by 9600bauds** [comment]
No, this is old as fuck and I think it still loops through viewers

**Comment by Intigracy** [comment]
```
        if(prob(25)) //We are noticed
            N.visible_message("[N] nibbles away at \the [src].", "You nibble away at \the [src]")
        else
            to_chat(N, ("<span class='notice'>You nibble away at \the [src].</span>"))
```
