### ISSUE TITLE
vox trader bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10849]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> -if they are near windows they start breaking them for no raisins
> -the medium pig gives the same quantity of meat as a small one when butchered (2 pieces)
> - fix the vox chicken dying at round start
> - the vox outpost in box station needs universal enzyme bottle and a mini hoe

**Comment by Exxion** [comment]
What are "they" in the first one?
And the third part is a duplicate, and soon to be fixed.

**Comment by pvak** [comment]
the vox pigs

**Comment by Kurfursten** [comment]
Mobs breaking windows for no reason is a problem frequently, related to the movement AI. This is the same reason that Russians on the satellite suffocate themselves. My advice is to store pigs away from external windows.

I'll investigate into the meat issue, @unid15 might have some ideas, I think he did butchering

for mini hoe see #10762
for suffocating chicken see #10848

**Comment by unid15** [comment]
For the meat, modify the mob's size var
The sizes are as follows
SIZE_TINY (1), SIZE_SMALL (2), SIZE_NORMAL (3), SIZE_BIG (4), SIZE_HUGE (5)

The size corresponds to the amount of meat dropped (tiny mobs drop 1 slab, small ones 2, ...)

**Comment by Kurfursten** [comment]
Vox pigs come in three sizes (which actually changes their size var) - they start small, grow to normal, then big. It's somewhat strange that size 2 and 4 are (apparently?) working fine but not 3. Needs more testing. Also I've heard reports that they continue growing after dead, so that will be an easy fix.

@pvak Could you see if size 4 is still dropping 2 meat?

**Comment by 9600bauds** [comment]
Reopen this for the Box bugs, the Box bugs were already fixed
