### ISSUE TITLE
morgue tray + cage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10851]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you put someone caged inside a morgue tray the dude gets stuck outside and cant move and cant be dragged
> 
> What you expected to happen
> something different
> 
> What actually happened
> this
> 
> Steps to reproduce if possible
> be inside a cage
> be put in a morgue tray

**Comment by Kurfursten** [comment]
@pvak Check to see if this happens with other fixed atom stuff like office chairs and roller beds.

**Comment by PJB3005** [comment]
@Kurfursten Atom locked*

Indeed though, morgue trays aren't respecting atom locking.

**Comment by Shadowmech88** [comment]
Tested locally, I was unable to place a caged person inside a morgue tray through any means.
