### ISSUE TITLE
Fireball explodes A LOT if picked up while timestopped and thrown

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10856]
Well, sometimes it fails to explode at all, sometimes it explodes once, and sometimes it explodes multiple times. I thought I had the circumstances worked out, but apparently not. I THINK it has to do with how many objects are either where it hits or near where it hits or something, but I can't seem to reproduce it reliably. Bauds can confirm it happened several times on the testing server, but I failed to narrow down exactly what made it explode multiple times.

Projectiles can still only be picked up while timestopped, but it's quite buggy, in this way as well as others. Perhaps the ability to pick up projectiles at all should be removed until it's made less buggy.

**Comment by Shadowmech88** [comment]
I was under the impression that all projectiles were anchored, and so could not be picked up at all.

**Comment by AutismSpider** [comment]
not all projectiles.

darts fire form vox guns can be grab mid air and toss back and other stuff

**Comment by 9600bauds** [comment]
caused because throw_impact is called once for every single thing on the tile

**Comment by Exxion** [comment]
@Shadowmech88 You can pick up anchored things just fine, as long as they're items. Only reason you can't pick up projectiles when not timestopped is because they don't call the parent in that case.

@AutismSpider Dart gun darts aren't technically projectiles. They really, really should be, but they aren't.

**Comment by AutismSpider** [comment]
not just dart guns crap fire out of the junk cannon at max force can be grab mid air and toss later at some one for like 200+ damage.

**Comment by Exxion** [comment]
I am pretty sure that's wrong
I mean the 200 damage part, not the catching part
Because that damage comes from the speed the cannon flings it at

**Comment by Exxion** [comment]
Oh yeah, it explodes once per item on the tile on which it explodes, not the tile it hits.
My record is nearly 900 brute with one fireball on the test server by the way

**Comment by Exxion** [comment]
This probably still happens in theory, but it's no longer possible to pick up projectiles without admin intervention, so it's moot
