### ISSUE TITLE
Goonchat doesn't escape HTML properly

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10854]
Say `<A HREF='BAD HREF STUFF= YES MASTER'>click me!!!</A>` out loud in-game
it werks

**Comment by Exxion** [comment]
Only for admins. This was fixed for everyone else like a day after Goonchat was merged.

**Comment by Shadowmech88** [comment]
The presence of this issue means most likely that the fix no longer works for normal players.

Is this the return of Rogan?

**Comment by 9600bauds** [comment]
It works for non-admins too

**Comment by Exxion** [comment]
Oh god how did it break again

**Comment by 9600bauds** [comment]
It probably was only fixed for embed images and sounds, never for other HTML stuff :^)

**Comment by Exxion** [comment]
It was definitely fixed for everything, at least for a while

**Comment by 9600bauds** [comment]
Apparently this can't be reproduced in the live serb, more to come

**Comment by Exxion** [comment]
Well, I just reproduced it in the live serb

**Comment by Exxion** [comment]
The link doesn't seem to actually WORK, but it still appears to be a link

**Comment by Shadowmech88** [comment]
What did you type/where? I tried `<a href="http://www.github.com">test</a>` in say as a mouse and it didn't embed the link.

Just to clarify, web addresses are supposed to show up as links in chat, right? Like just typing http://www.github.com would function as a link?

**Comment by Exxion** [comment]
I believe you were there. I said `<a href='google.com'>Test?</a>` in deadchat and it appeared as a link
Spans work too

**Comment by Shadowmech88** [comment]
Oh, that was you. Yeah it appeared as a link, but I could still see all the href stuff. It appeared to me as `<a href='google.com'>Test?</a>`, not as <a href='google.com'>Test?</a>.

We _are_ supposed to be able to put regular old links in chat, right? Just not embed them in text?

**Comment by Exxion** [comment]
It appeared to me as the link.
What the fuck?

**Comment by Shadowmech88** [comment]
When you say "as the link" do you mean it appeared to you as <a href='google.com'>Test?</a> ?

**Comment by Exxion** [comment]
Yes.

**Comment by Shadowmech88** [comment]
Huh, I'll try it in deadchat. It didn't seem to work for me as a mouse.

**Comment by Exxion** [comment]
Even images work again, at least for me.
I'm not going to try audio but I bet it would work

**Comment by Shadowmech88** [comment]
Somehow, the same HTML that's showing up for you as an actual link/image, shows up for me as just plain HTML code.

**Comment by Exxion** [comment]
For those not in the IRC, it appears to PROBABLY be dependent on IE version

**Comment by 9600bauds** [comment]
PJB says he won't be around his desktop PC to take a look into this, so picnic

**Comment by PJB3005** [comment]
I believe I have had this happen too a bit before this report was made, i pinged @gbasood on IRC but he was unable to reproduce it. IE, Edge (both win 10) and BYOND versions were all the same.

When it happened I used firebug and determined that the HTML was coming in sanitized but something, and I BELIEVE it was jQuery, was using even the sanitized HTML.

The specific jQuery function it has to be is parseHTML().

**Comment by tigercat2000** [comment]
I found a similar problem.
Saying `http://google.com` will produce a fully functional a link, as well `www.google.com`
![https://i.imgur.com/SHqrKnN.png](https://i.imgur.com/SHqrKnN.png)

**Comment by Shadowmech88** [comment]
I believe regular links are intended to be functional.
The problem in this issue is that players shouldn't be able to use HTML tags in chat and have them function.

**Comment by Iamgoofball** [comment]
regular links work in standard BYOND chat too

**Comment by PJB3005** [comment]
@Tigercat2000 there's a function in goonchat to convert http links, else they wouldn't be click able.

**Comment by tigercat2000** [comment]
`linkify` i guess
that's quite awful

**Comment by PJB3005** [comment]
I don't see how it's awful. It doesn't allow people to just craft hrefs that when clicked do bad things, so?

**Comment by 9600bauds** [comment]
I don't know if you're referring to a specific function in goonchat or the current state of affairs because right now you absolutely can post forged hrefs in OOC that do bad things

**Comment by Shadowmech88** [comment]
*You absolutely can post forged hrefs in OOC that do bad things _for certain people._

Most players, myself included, just see `<a href=""></a>` when someone posts <a href=""></a> in chat.

**Comment by 9600bauds** [comment]
Did we ever test how many people could see them? When we tried it in the IRC it was just you that couldn't

**Comment by Shadowmech88** [comment]
I thought there was at least one other in the IRC that couldn't. I _know_ that there were others in the server that couldn't.

**Comment by Exxion** [comment]
60% of people polled _could_ see the stuff, but only 5 people actually answered when asked so the margin of error on that is pretty astronomical

**Comment by tigercat2000** [comment]
> Most players, myself included, just see <a href=""></a> when someone posts <a href=""></a> in chat.

Same issue on Paradise, this happened: 
https://i.imgur.com/UlplGyA.png
https://cdn.discordapp.com/attachments/144578296552751104/202852269077561344/unknown.png

https://i.imgur.com/NRTH5O2.png

¯\_(ツ)_/¯

**Comment by PJB3005** [comment]
Inclined to believe it's a jQuery bug at this point.

**Comment by PJB3005** [comment]
And I did some digging.

This is completely a bug in IE / Edge and there is nothing we can do other than circumvent it in some way. Fuck.

**Comment by Exxion** [comment]
On the plus side, it seems like not many people have discovered that it's back
No ROGANing has happened
Or at least only on the test server

**Comment by clusterfack** [comment]
I don't really get how the byond html proc isn't removing all that shit, isn't that what its for

**Comment by PJB3005** [comment]
@clusterfack that isn't the issue.

I inserted debug logging to the firebug console and the HTML IS ESCAPED when it gets inserted into the page via [`Element.innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML). Yet for some reason on SOME PEOPLE'S COMPUTERS, it parses the `&lt;` and such as HTML.

**Comment by Krausus** [comment]
The issue is only occurring to people with strings set to be highlighted. Something about the way `highlightTerms` does its job is turning escaped characters into ones that aren't. I'm not actually sure what's going wrong in it, though - I ain't so good with the Javascripts.

**Comment by Exxion** [comment]
Wait hold on
Is that it?
If it is then we can fix it

**Comment by PJB3005** [comment]
Okay panic averted let's fix this mess.

**Comment by Exxion** [comment]
Yep that's definitely it
Great catch, whoever figured that out
