### ISSUE TITLE
Borer Drag Spam

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10859]
(WEB REPORT BY: rhimrifer REMOTE: 172.93.109.202:7777)
Revision: 3b41948840cd36f803bf3d6ead4415df8b1189cd

> General description of the issue
> When being dragged as borer "You are too small to pull anything." spam occured.
> 
> What you expected to happen
> No spam
> 
> What actually happened
> Spam
> 
> Steps to reproduce if possible
> -Be borer
> -Be dragged

**Comment by Shadowmech88** [comment]
I believe there's already an issue about this.

**Comment by uazuaz** [comment]
if i remember right, it happens the same when dragged as a mouse.
