### ISSUE TITLE
Playing cards not visible when stacked into a playing hand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10855]
(WEB REPORT BY: orzorn REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

3b41948840cd36f803bf3d6ead4415df8b1189cd 

> General description of the issue
> A "hand" of cards, that is, multiple cards in a stack that you're supposed to be able to flip over and see while in your hand, do not show up as cards, and instead a strange red icon with faded out cards barely visible.
> 
> What you expected to happen
> To be able to see the hand of cards.
> 
> What actually happened
> They were nearly invisible and a strange red icon was present.
> 
> Steps to reproduce if possible
> Get a deck, draw more than one card and put them on each other to make a hand. Witness the strange icon and inability to see the cards.

**Comment by ghost** [comment]
This, and the fact cards sometimes just disappear in your hand or when placed on a table, leaves me sour. Sometimes I just want to host a comfy game of blackjack and get a gimmick going, but the buggyness of cards makes it frustrating.
