### ISSUE TITLE
Vampires & X-Ray

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10861]
(WEB REPORT BY: rhimrifer REMOTE: 172.93.109.202:7777)
Revision: 3b41948840cd36f803bf3d6ead4415df8b1189cd

> General description of the issue
> Apparently getting x-ray(at least through borers) as vampire does not update a vampire's vision.
> (Follow) DEAD: borer (140) drones, "Also I gave you x-ray"
> (Follow) DEAD: borer (140) drones, "How were you not seeing everything?"
> (Follow) DEAD: Felicity Rivera cries, "the xray didnt change vamp vision"
> 
> What you expected to happen
> To give vamp x-ray as borer
> 
> What actually happened
> No x-ray vision occured
> 
> Steps to reproduce if possible
> -Let vampire get vampiric vision
> -Give vampire x-ray vision
> -Possibly other way around to see if one overrides the other

**Comment by Allspice** [comment]
Vampires get some goofy shit with vision, mesons work badly for them too.
