### ISSUE TITLE
Rev can happen with one head of staff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10866]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision b712eab71639ee8bb3bf1d0571782e8db88ddec5 
> 
> General description of the issue
> Title.
> 
> What you expected to happen
> That rev is removed from rotation but barring that, ceemo only head roundstart means no revolution.
> 
> What actually happened
> VIVA
> 
> Steps to reproduce if possible
> Join as CMO with 25+ pop.

**Comment by Kurfursten** [comment]
No longer the case
