### ISSUE TITLE
ai tracking issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10867]
(WEB REPORT BY: donalddawkins REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

clicking on a players name in text chat causes massive freezes and crashes if teleporting a long distance to said characters

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Ephx1** [comment]
I'm curious if this persists with the track button in the HUD. Some time ago clicking links in chat crashed the game for me, which I got around with the tracking button.
