### ISSUE TITLE
We need to have a discussion on nuke ops.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#10872]
Nuke ops as it stands sucks.
At least one member of the team is going to fuck everything up.

Last ops team I was on we were going to do locker ops with projectors, but that plan went out the window when some dumb ass used up all the rest of the TCs by picking random item three times. We winged it and fucked up and got spotted before even getting in the station.

Time before that I made a plan that involved me stealthing in and grabbing a telebeacon so that we could trojan horse in on me. Some asshole pushed pushed someone else into the teleporter causing a bloodred hardsut equipped op to be in the middle of the hallway.

Point is that one person can cause the entirety of the mission to be a total failure.

Options are...

Remove nuke ops from rotation. Every time we get back to back op rounds another engineer goes assistant. They almost always end in failure or they telebomb and win.

The more controversial option is to whitelist it. This is a forbidden word to use on our server, but the point stands is that one person can ruin everything. Have a sign up fourm on the forms that has a simple questionare that let's the admins know that you aren't totally retarded and are able to be a team player.

What are your thoughts?

**Comment by ComicIronic** [comment]
It sounds to me like those are both cases of deliberate bad behaviour, and should be an admin problem.

**Comment by SysadminJeroen** [comment]
Newcops isn't even that large of a problem if you get caught, bust in as a team and kill everyone you see.

Raiders is a problem when you get caught, because then the crew gets hardsuits and the darts rarely penetrate the hardsuits.

**Comment by clusterfack** [comment]
Nukeops is legitimately one of the best gamemodes

**Comment by 9600bauds** [comment]
Nothing about this issue seems specific to newcops
You WILL have to interact with retarded people in every aspect of the game, team-based gamemodes just let you really appreciate them

**Comment by ghost** [comment]
There's nothing wrong with the nuke ops gamemode, it's a playerbase problem. I've had no problems during my rounds as an Op, we had trouble deciding our plan becausr some people don't know how to communicate but in the end we reached something and did it. Sometimes it doesn't pan out, but shit happens. Every mode is a learnin experience and some people would rather you learn by observation but it's better to learn by experience. Just look at any group antag gamemode, they're all make or break on teamwork, most of the time, and one sour player can ruin the round. But they have to learn the importance of teamwork somehow, and if it seems more like an attitude problem to the gamemode/other players then it's up to the admins to come to a conclusion to if they should be roll banned from these group-antag gamemodes.

**Comment by kol1th** [comment]
I've never had a retarded nuke ops team in my ~5 or so times getting the roll for it. Sounds more like a playerbase issue than anything else.

**Comment by Durgen** [comment]
The problem with Nuke Ops is that noobs don't  pipe up and say they have no idea what's going on and veterans don't bother explaining anything.

Maybe there could be an enforced planning     stage, and some way to distinguish the more experienced Ckeys to encourage teaching.

**Comment by ComicIronic** [comment]
We could do an in game system, where being a part of x successful nukeops rounds gives you a cosmetic difference so other players know you're a relative expert. Something like a different title.

**Comment by DamianX** [comment]
This discussion seems over.
