### ISSUE TITLE
Pneumatic Cannons can be fired while clumsy/hulked out

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10874]
I'm sure you can see the issue with this

**Comment by Exxion** [comment]
Well, they are technically storage items rather than guns, so that's not very surprising

Oh fucking hell an instakill ranged hulk sounds _delightful_

**Comment by Killette2** [comment]
There are FEW items that are instakill with pneumatic cannons, but that's a different issue entirely. I also believe there should be a difference between clumsy and clown clumsy, where one would make you misfire the gun or accidentally drop it, and the clown exclusively makes it explode.

**Comment by Exxion** [comment]
Yes, there are only like two items that are instakill with the cannon
But one of them is glass shards
Which are not exactly difficult to acquire
