### ISSUE TITLE
Secret admin_log shows up as secret spawn_objects

### ISSUE THREAD

**Issue by doobiedoo23** [d3athrow/vgstation13#10875]
#### Description of issue

Using the admin log in secrets shows up in the logs as using secret spawn_objects.
#### Difference between expected and actual behavior

It should be outputting secret admin_log rather than secret spawn_objects.
#### Steps to reproduce

Go to the secrets menu, then click on Admin Log near the bottom. X out of it, and then click on it again. It will show up as this;
http://i.imgur.com/FGuvMOe.png
#### Specific information for locating

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/admin/admin.dm
Code can be found here
#### Length of time in which bug has been known to occur

probably forever

**Comment by clusterfack** [comment]
Copypasting? Or maybe the same admin code being used twice that would be exciting. Who wants to dig through datum admins topic?
