### ISSUE TITLE
Mesons broken?

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#10870]
![gentleman relay sierra 2016-07-02 075840](https://cloud.githubusercontent.com/assets/9064611/16540708/1f6a4590-403c-11e6-91ec-4bdab8c2933c.png)

I put on mesons in a round earlier today, and this is all I got.
have they been changed for some reason?
They no longer show the layout of rooms and stuff, they just turn off the shadow effects

**Comment by kol1th** [comment]
Update byond?

**Comment by Exxion** [comment]
Yeah, update BYOND
Man, Niggly, when's the last time you played? This was fixed long ago

**Comment by Intigracy** [comment]
way to search the issue tracker
