### ISSUE TITLE
Vox trade shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10879]
(WEB REPORT BY: nanocop REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Vox trading shuttle is unable to go to the station.
> 
> What you expected to happen
> Expected it to move
> 
> What actually happened
> It didnt move
> 
> Steps to reproduce if possible
> I just opened the shuttle console and it said This shuttle has no docking port specified.

**Comment by 9600bauds** [comment]
WHAT MAP

**Comment by Kurfursten** [comment]
I'm guessing the docking object was destroyed somehow, maybe by a singuloose? I don't think it has an ex_act

**Comment by carshalash** [comment]
No, I can verify this happened at the start of a map of box.

**Comment by carshalash** [comment]
http://i.imgur.com/4bzeWn3.png

**Comment by Intigracy** [comment]
Thanks @dylanstrategie.

#10762
