### ISSUE TITLE
Ling regeneration breaks cuffs.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10887]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 4469910f539fe5570a563339582e45f612e7170f 
> 
> General description of the issue
> A cuffed changeling becomes uncuffed after it comes out of regenerative stasis.
> 
> What you expected to happen
> Ling stays cuffed after regenerating.
> 
> What actually happened
> Nope.
> 
> Steps to reproduce if possible
> Cuff a ling, watch it regenerate, marvel at the cuffs falling off.

**Comment by gbasood** [comment]
dont see anything about this in code
