### ISSUE TITLE
Suit sensors can be toggled through a hardsuit.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10880]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 37bba96de73be3a926ac73422edc2186cb359141 
> 
> General description of the issue
> Other people can toggle your sensors through a hardsuit.
> 
> What you expected to happen
> To need to strip the suit first.
> 
> What actually happened
> Not needed.
> 
> Steps to reproduce if possible
> Bring up the strip menu on someone.

**Comment by Killette2** [comment]
You can probably count someone's pulse through hardsuits, you can even medical scan (handheld item) through hardsuits. How the hell do hardsuits work?

**Comment by AlphaBuffalo** [comment]
Heart rate monitor on the suit, or maybe a soft spot to measure the pulse and medical scanner penetrate hardsuit... idk that makes sense to me, what does make sense is being able to eat without taking the helmet off IIRC

**Comment by Imagebard** [comment]
Hardsuits so have injection ports to administer injections, mind you.

**Comment by AlphaBuffalo** [comment]
This is an issue though that people can turn sensors off through the hard suit
