### ISSUE TITLE
Turn Special tab off by Default

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10883]
Having new players completely ignore adminhelps because they don't show up in their chat but instead in a tab they can't check is starting to get old very fast

Also rename that preference so that it is EXTREMELY clear that this forwards all adminhelps to a Special tab

**Comment by JustSumBody** [comment]
I'm confused, how exactly is the special tab supposed to work?

**Comment by clusterfack** [comment]
It autonatically switches to the special tav if yoy have it enabled. I already solved this issue. If they wont respond ban them.

**Comment by ghost** [comment]
Aight
