### ISSUE TITLE
Vox are immune to  low-pressure damage

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10882]
Bay made them that way because they were antag-only and also in their lore they are basically an artificial race designed to be as effective as is biologically possible
But here they aren't antag-only

Note that they can still get popped lungs and they still die in space due to cold
It's just low pressure damage that they are immune to

**Comment by AI-Is-Rogue** [comment]
They're not antag-only on bay either. They are white listed though.

**Comment by 9600bauds** [comment]
Honestly sounds like a bug more than anything

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/16546931/94c25c46-4128-11e6-9e1b-77f3f54c55d6.png)

Not exactly a hard fix

**Comment by ghost** [comment]
Let's just turn them into proper organics in our "lore"

Same pressure damage and cold/heat damage resistance as humans, done

**Comment by Exxion** [comment]
They already are regular organics in our "lore"

**Comment by AI-Is-Rogue** [comment]
Our """"lore""""

**Comment by charmstruck** [comment]
I just experienced this myself. I was at the derelict while wearing a welding helmet as headgear in a low-pressure environment while taking no damage at all. This should definitely not be a thing

**Comment by gbasood** [comment]
well it seems like this is still a thing

**Comment by PJB3005** [comment]
But it's not a bug?

**Comment by gbasood** [comment]
true

**Comment by Exxion** [comment]
This was fixed for vox at some point but apparently is still the case for skelevox
