### ISSUE TITLE
When a monkey picks up an item on their left hand, it's displayed on their mob icon as being on the right hand. This phantom held item never goes away anymore even if you drop the item afterwards

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10889]
I gave up trying to figure out why this happens
![dreamseeker_2016-07-03_21-15-58](https://cloud.githubusercontent.com/assets/6526157/16548381/543de01a-4163-11e6-9cec-a54b4a70070a.png)
this is the result of picking up a helmet with your left hand and putting it on

**Comment by ihadtoregisterforthis** [comment]
Diona Nymphs too.
It goes away sometimes if you fetch something else.

**Comment by NigglyWiggly** [comment]
This used to happen to xenos.
It would go away if I picked the item up again and put it in my pocket.
It seems to not happen to xenos anymore, so maybe someone did something there that could be replicated here?
