### ISSUE TITLE
Blue Space Tomatoes ; Handcuffs; And Buckled Chairs

### ISSUE THREAD

**Issue by Anglosphere** [d3athrow/vgstation13#10884]
#### Description of issue

Throwing a blue-space tomato at some one who is handcuffed and buckled in a chair, causes them to become stuck. Things like tazers, and other stuns, and pulling also don't effect the player in handcuffs. 
#### Difference between expected and actual behavior

After being hit by a bluespace tomatoe, and teleported while handcuffed in a chair you should be able to move. 
#### Steps to reproduce
1. Handcuff a player
2. Buckle them in a chair
3. Throw a bluespace tomatoe at them
4. Ensure they are teleported by the tomatoe
5. Check if they can move
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
More precisely, it doesn't reset their locked_to, but they simply shouldn't teleport

Now to make it actually work
