### ISSUE TITLE
Ions have a chance to explode E implants.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10899]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 83bbaa3734688ba073d8098a0ba5ae2c4e64339a
> 
> General description of the issue
> Title.
> 
> What you expected to happen
> Not to be fuckered over by such a silly thing as a nuclear operative.
> 
> What actually happened
> Ops keep fucking blowing themselves up with their ion rifles, maybe moreso than the bloody RPG.
> 
> Steps to reproduce if possible
> Ion someone with an E implant.

**Comment by Shadowmech88** [comment]
Should probably just have a special EMP-proof explosive implant and give it to nuke ops only.

**Comment by Exxion** [comment]
I'm pretty sure nuke ops already get a special implant, as their explosions are way bigger
Just make it EMP-proof

**Comment by JustSumBody** [comment]
Just checked it, the implants are the same if I'm reading this right.
