### ISSUE TITLE
Box Hydroponics Storage camera leads to vox outpost hydroponics.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10891]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 4469910f539fe5570a563339582e45f612e7170f 
> 
> General description of the issue
> Check 'Hydroponics Storage' on sec cam console and it makes you jump to vox outpost hydro.
> 
> What you expected to happen
> Jump to botany backroom on main station.
> 
> What actually happened
> Title.
> 
> Steps to reproduce if possible
> Use a sec cam console

**Comment by kernikov** [comment]
This has happened to me as the warden, occasionally my advanced sec camera console locks me down to only one camera. Normally something stupid like vox outpost hydroponics, the test range, or a borg.
