### ISSUE TITLE
Ghosts don't see attack text etc through walls anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10890]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4469910f539fe5570a563339582e45f612e7170f 
> 
> General description of the issue
> At some point ghosts stopped being able to see attack text if they don't have normal line of sight to the source
> 
> What you expected to happen
> See attack messages anywhere on the visible screen
> 
> What actually happened
> Don't see that
> 
> Steps to reproduce if possible
> Observe, watch a fight through a wall

**Comment by clusterfack** [comment]
Possibly a byond bug with viewers()

**Comment by clusterfack** [comment]
In retrospect its an issue with virtualhearers not respecting the sight var of their attached mob

**Comment by gbasood** [comment]
old
issue

**Comment by Shadowmech88** [comment]
Tested, no longer happens.
