### ISSUE TITLE
Crashing the game!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10892]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4469910f539fe5570a563339582e45f612e7170f
> 
> General description of the issue
> Game crashing when using PDA
> 
> What you expected to happen
> Opening my PDA
> 
> What actually happened
> Game went poof and threw an improper argument
> 
> Steps to reproduce if possible
> Using a PDA? First time this has ever happened

**Comment by PJB3005** [comment]
BYOND issue.

**Comment by Intigracy** [comment]
Change your applocale back to english after you finish playing your nipponese porn games.

**Comment by clusterfack** [comment]
But yeah it actually is a byond issue
