### ISSUE TITLE
Asteroid next turf overlays show under the space parallax

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10901]
The rock outcroppings around asteroid tiles don't show properly over space

It seems pretty obvious that the overlay's layer must not be high enough compared to the parallax, or something of that order

Since asteroid code is some real spaghetti code, it's hard to tell what in the new parallax and layering system broke it partially

@clusterfack

**Comment by PJB3005** [comment]
@DrCelt PLANES

**Comment by Intigracy** [comment]
I don't see how it's hard to tell what broke it at all.

@DrCelt shitcode broke it.

**Comment by 9600bauds** [comment]
Plenty of technical hiccups but I think it's the least proper code of his to call shitcode

**Comment by ghost** [comment]
this will not be fixed by #11183 - there's a better way to do this entire thing pointed out to me by cluster and it'd be unatomic for me to put it in there.

**Comment by gbasood** [comment]
@DrCelt time to atomic shit up

**Comment by ghost** [comment]
;_; the dream is dead, the most efficient way to do this that requires no procs and super smooth is ruined because of lummox
I'll just do a PR making this use update_icon()

**Comment by Intigracy** [comment]
So when is this getting fixed

**Comment by clusterfack** [comment]
Literally never because @drcelt caused it
