### ISSUE TITLE
Issue NameMice can unbuckle people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10904]
(WEB REPORT BY: 9600bauds REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Issue NameMice can unbuckle people
> 
> General description of the issue
> Issue NameMice can unbuckle people
> 
> What you expected to happen
> Issue NameMice can unbuckle people
> 
> What actually happened
> Issue NameMice can unbuckle people
> 
> Steps to reproduce if possible
> Issue NameMice can unbuckle peopleIssue NameMice can unbuckle peopleIssue NameMice can unbuckle people

**Comment by PJB3005** [comment]
Why would you do this.
