### ISSUE TITLE
feature request: bandolier holding different types of ammo

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#10909]
I am making this to get an reaction before I code it, it would be a very simple addition to add.

Right now all it holds are shotgun shells, what if we allowed it to hold all shell types of other guns? So you can walk around like a cowboy with a big iron on your belt and wrapped around with .357 shells.

Much more balance breaking but would be more useful is allowing it to hold magazines, that way you can hold speed loaders, or go tacticool and have assault rifle magazines on you.

Or for a more funny (also balance changing) use, allow matter carts to be put on it. For when you really need to build things.

What are your thoughts? Too over powered?

**Comment by icantthinkofanameritenow** [comment]
Matter cartridges already fit on toolbelts, and ammo boxes/magazines do a perfectly good job of holding ammo without also forcing you to fiddle around with five different inventory screens.

**Comment by FudgePucker** [comment]
All I heard from that was that it wouldn't destroy the balance and a giant green light.

**Comment by icantthinkofanameritenow** [comment]
I was actually questioning it's usefulness; shotguns are the only gun that truly needs it since they have no options for magazines or speed loaders of any kind. Most other guns simply wouldn't get as much benefit from such a bandolier, and if you need to store that much ammo.on you in the first place then that's probably a sign that you should work on your aim.

**Comment by FudgePucker** [comment]
What if the bandolier could hold magazines?

**Comment by icantthinkofanameritenow** [comment]
I'm pretty sure even RL bandoliers don't do that.

**Comment by clusterfack** [comment]
![Wow get ye good](http://cdn3.volusion.com/cnvbm.vnrnu/v/vspfiles/photos/1025-2.jpg?1412604479)

**Comment by icantthinkofanameritenow** [comment]
Huh, didn't know those existed. 

Maybe they could be given to nuke ops? They start with two extra mags for their C20rs, and if they spawned in the bandolier it would let them carry some.more stuff in their inventory.

**Comment by ComicIronic** [comment]
Don't newcops start with webbing?

**Comment by icantthinkofanameritenow** [comment]
If they do, I've never noticed it before.

**Comment by kernikov** [comment]
![op8](https://cloud.githubusercontent.com/assets/5549060/16712851/78b4b98c-4659-11e6-91f2-ccd4b80ce39c.png)
![op81](https://cloud.githubusercontent.com/assets/5549060/16712852/7adc7dda-4659-11e6-900a-eaf579c18152.jpg)
