### ISSUE TITLE
Vampires can hypnotize and thrall while buckled and cuffed.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10908]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 3bbaa3734688ba073d8098a0ba5ae2c4e64339a 
> 
> General description of the issue
> Title.
> 
> What you expected to happen
> Not title.
> 
> What actually happened
> Just
> 
> Steps to reproduce if possible
> Get handcuffed, attempt to hypnotize and thrall someone, it just fuckin werks.

**Comment by ComicIronic** [comment]
Is this a bug

**Comment by Allspice** [comment]
Thralling at the very least mentions that you 'bite them and transfer your power' or something along those lines. And on that note: You can thrall through a full hardsuit and gas mask, too.

**Comment by JustSumBody** [comment]
Hypnotize should be fine to use while cuffed though, no?

**Comment by AutismSpider** [comment]
hypnotize  is eye powers same with the flash.

thralling forces you bite them to transfer some of your power to them can thrall people when stun on the floor to etc
