### ISSUE TITLE
Monkeys cannot bump people away or switch places with them, no matter the intent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10906]
(WEB REPORT BY: 9600bauds REMOTE: 172.93.109.202:7777)
you can't push them away or swap places with them, they completely stop you

**Comment by ComicIronic** [comment]
This is intentional.

**Comment by Killette2** [comment]
Pretty sure monkeys and humans have a bit of a strength difference when it comes to displacing each other, like how you can't push a harm intent borg.

**Comment by 9600bauds** [comment]
I can imagine that you couldn't push them away but I can't imagine any reason why a monkey or Diona or chicken couldn't just run under your legs to get past you in a 1 wide corridor

**Comment by ComicIronic** [comment]
Because you stop them, that's what the intent means. If you want that behaviour, open a feature request - it's not what the web reporter is meant for.

**Comment by 9600bauds** [comment]
Actually, this happens for people even in help intent
