### ISSUE TITLE
Mule cannot find security or janitor dropoff destination on box station.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10910]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision 0d91b25673f35182d69c6e36175ad143f2e1db89 
> 
> General description of the issue
> Set janitor or sec as mule destinations and it wont path. Kind of a downer when you want to send sec shit.
> 
> What you expected to happen
> Slowly meanders to sec/janitor and drops off.
> 
> What actually happened
> Mode: Unable to locate destination
> 
> Steps to reproduce if possible
> Get on or put stuff on a mule, set target to security/janitor then hit proceed

**Comment by ComicIronic** [comment]
What map
Also we need to add the map to the web reporter

**Comment by 9600bauds** [comment]
> Mule cannot find security or janitor dropoff destination on box station.

**Comment by Kurfursten** [comment]
I believe the reason it can't get to Security is because the maint door near security atmos needs sec access, and mules only have cargo + maint

Same issue with janitor closet, which is behind janitor-locked doors
