### ISSUE TITLE
Borer into borg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10913]
(WEB REPORT BY: tifora REMOTE: 172.93.109.202:7777)
Apparently if you ghost out of a posibrain then become a borer and someone else enters the posibrain you ghosted out of, if that posibrain is put into a borg, you get transferred out of the borer and into the borg and the posibrain that got put into the borg remains a posibrain that can talk inside the borg body but not move.

**Comment by PJB3005** [comment]
What the hell is it with borders that makes them so glitchy with minds.

Serioudly why haven't I ever heard of issued like this with Dionas?

**Comment by ComicIronic** [comment]
Presumably because borer code handles mind incorrectly and diona code doesn't.

**Comment by clusterfack** [comment]
Nexis why did you make borer code so shit
