### ISSUE TITLE
Shard delamination warnings are heard from the derelict

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10919]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> ccdc05ccde38d2dca4afa36526e85fe7c018df0f 
> 
> General description of the issue
> When some mommi testing things out on the derelict starts to overheat their shard, the entire station freaks out, searching for a shard on their station
> 
> What you expected to happen
> Derelict shard doesn't broadcast onto the station
> 
> What actually happened
> It does
> 
> Steps to reproduce if possible
> Delaminate a shard on the derelict, make the actual station panic

**Comment by PJB3005** [comment]
I told @cptwad to get my fix for this but he never did. 

If anybody wants an easy peasy fix there is a closed age old PR that added a shard to every derelict and it made the shard only affect the z level.

**Comment by ComicIronic** [comment]
> steal the shard from the derelict
> put it on the main station
> silent bomb

How about no

**Comment by ConkerDev** [comment]
Its not really silent, you get a delamination warning. And it requires a lot of work, really

**Comment by clusterfack** [comment]
Silent?

**Comment by PJB3005** [comment]
@ComicIronic it works on a z level basis, shard blowing up or throwing warnings on the derelict doesn't affect the station or vise versa.

**Comment by Intigracy** [comment]
It SHOULDN'T but it does

**Comment by clusterfack** [comment]
Wasnt this fixed?

**Comment by PJB3005** [comment]
I think it was?

**Comment by PJB3005** [comment]
e60517d2093fc875fb9c8fa84ed10d570e4bafd0

Yep.
