### ISSUE TITLE
Science biohazard shutters layer above open airlocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10915]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0d91b25673f35182d69c6e36175ad143f2e1db89
> 
> General description of the issue
> When airlocks in science are open, they are entirely covered by the biohazard shutters, making it impossible to interact without alt-click
> This is on boxstation
> 
> What you expected to happen
> Open doors to appear above open blast doors
> 
> What actually happened
> They don't
> 
> Steps to reproduce if possible
> Open a science airlock with a blast door on the same tile

**Comment by ghost** [comment]
Can we know which airlocks, specifically ? Because it's certainly not all of them

**Comment by kernikov** [comment]
Mech Recharge Hanger to Hall is definitely like this.

**Comment by SysadminJeroen** [comment]
Fixing it, sorry.

**Comment by SysadminJeroen** [comment]
This should fix it: https://github.com/d3athrow/vgstation13/compare/Bleeding-Edge...Jeroen52:fix/science-biohazard-shutters-layering
I haven't tested it and I will do it once I get home.

**Comment by Gringonius** [comment]
I thought that we had Celt to blame for this?

**Comment by kol1th** [comment]
Nope. It was like this since before Celt's new 9/11.

**Comment by SysadminJeroen** [comment]
My branch did not work, fixing it right now.

**Comment by SysadminJeroen** [comment]
I have checked any I have no clue why the shutters are over the door while the airlock is opened.
The layers have been checked.
I have taken a look at how Security's shutters are done and I don't know what is different.

**Comment by ghost** [comment]
You need to make the airlock an active object, delete the airlock and re-add it over it

The shutter thing happens if the shutter was placed after the airlock

**Comment by SysadminJeroen** [comment]
@dylanstrategie I got it working, thanks for the tip.

**Comment by SysadminJeroen** [comment]
#10981

**Comment by kernikov** [comment]
STILL BROKEN
![telescience bio airlock](https://cloud.githubusercontent.com/assets/5549060/16891136/2ae87c64-4abb-11e6-8e6e-4e9490025444.png)
![sci airlock near shuttle](https://cloud.githubusercontent.com/assets/5549060/16891137/2b0f4196-4abb-11e6-9caa-71bfde4dc33d.png)
![sci airlock inner entrance airlock](https://cloud.githubusercontent.com/assets/5549060/16891138/2b354422-4abb-11e6-8ddf-e212df0b9429.png)
![xenobio bio airlock](https://cloud.githubusercontent.com/assets/5549060/16891139/2b3670cc-4abb-11e6-9719-7010585ec7d0.png)
![sci inner bomb testing airlock](https://cloud.githubusercontent.com/assets/5549060/16891141/2b3cc0c6-4abb-11e6-937d-de15f062e27a.png)
![sci - genetics airlock](https://cloud.githubusercontent.com/assets/5549060/16891140/2b397b6e-4abb-11e6-98bf-251b7cba5524.png)

**Comment by SysadminJeroen** [comment]
@kernikov the fuck, are you sure you checked out the correct branch and commit? I walked past each and every door and it was fine.

**Comment by kernikov** [comment]
If the fix wasn't merged, then consider this just documentation.

**Comment by 9600bauds** [comment]
Fixed or not?

**Comment by SysadminJeroen** [comment]
@9600bauds When I was testing it was, @kernikov thought that it was merged already. I will test it again right now.

**Comment by SysadminJeroen** [comment]
@9600bauds Yes, it has been fixed.

**Comment by SysadminJeroen** [comment]
@9200bauds The pull request still needs to be merged though.
