### ISSUE TITLE
Tier 3 energy gun? sprites/feature request

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#10918]
I thought it might be nice to have a second upgrade to the energy gun family tree that brings back the classy black finish of the original.
![egun](https://cloud.githubusercontent.com/assets/15067109/16633403/20b52fc2-43c1-11e6-9906-d2889caa36b5.png)
Stats-wise It could retain the self-charging feature of the advanced energy gun but also be able to fit in rechargers for a faster reload, like the captains laser can. 
Download link for sprites: http://s000.tinyupload.com/index.php?file_id=99793973365618316319

**Comment by kol1th** [comment]
Why not just replace the AEG with this? I think it looks better anyways.

**Comment by 9600bauds** [comment]
I like the christmas tree lightbulb at the back

**Comment by icantthinkofanameritenow** [comment]
I agree with kol1th. The AEG's current sprite looks nothing like the normal egun anyway.

**Comment by clusterfack** [comment]
Well that's because the current 'advanced energy gun' was previously just the 'nuclear gun'

**Comment by icantthinkofanameritenow** [comment]
I noticed that in the code. What was up with that name anyway?

**Comment by Blithering** [comment]
The examine text says the battery was replaced by a teeny tiny nuclear reactor, so that's probably the reason.

**Comment by icantthinkofanameritenow** [comment]
@Blithering
Makes sense. On an unrelated note, does it still irradiate people or was that commented out?

**Comment by Imagebard** [comment]
I believe it shits out rads if EMPed
Seriously though I like this sprite a little more. What is the christmas lightbulb in the back though?

**Comment by Blithering** [comment]
I wanted to use elements from the AEG, the lightbulby part is the mini oxygen tank that hangs off the side.

![lightbulb](https://cloud.githubusercontent.com/assets/15067109/16641858/82b40cb2-43fc-11e6-9599-ed5d7a36e35f.png)

**Comment by Imagebard** [comment]
What.
Wait a minute, what the fuck is that?

**Comment by 9600bauds** [comment]
The christmas tree lightbulb duh

**Comment by Blithering** [comment]
@Imagebard  What the fuck is what now?

**Comment by kernikov** [comment]
Hitscan stun when?
Fug electrodes.
Call it a phaser.

**Comment by clusterfack** [comment]
When stuns don't instadrop you

**Comment by ComicIronic** [comment]
Stun refactor never

**Comment by Shadowmech88** [comment]
Stun refactor [When You Code It].

**Comment by 9600bauds** [comment]
People will bitch about any changes to stuns even if they're good

**Comment by icantthinkofanameritenow** [comment]
@9600bauds

More like they'll throw a shitfit if you even consider changing stuns.

**Comment by Intigracy** [comment]
stuns are good

**Comment by PJB3005** [comment]
Indeed. Stuns are good. They encourage not getting into fights because of how high risk high reward everything is.

**Comment by Imagebard** [comment]
But the only way security can arrest people is by stun fights.
...

What if security had some way to engage in indirect warfare?

**Comment by Blithering** [comment]
Rude PDA messages?
Also a hitscan stun would need a massive downside, current stuns are powerful, but balanced by their slow projectile, making yakkety saxing a valuable skill. That said, some servers have multiple stun modes, with a short range instant stun. I could sprite up a third mode for the gun, or some form of secondary barrel that uses ammunition?
