### ISSUE TITLE
Custom Clothes

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#10924]
The idea here is that players can use a machine to print an outfit of their choice that is completely customizable. It would would by having different templates like Shirt and Pants, Shirt and Shorts, Shirt and Skirt, Jacket and Short, etc. The player chooses a template and can pick what colors it would be, then the clothes get printed. Should also work for hats, and shoes imo but there is a decent selection to choose from already.

I asked this question in OOC and got mixed responses. (Badly worded anwser choices so Yes means it improves immersion and no means it hinders immersion)
http://www.strawpoll.me/10689235

This strawpoll is to see whether or not the machine should use materials to make clothes like most other machines.
http://www.strawpoll.me/10689284

**Comment by NigglyWiggly** [comment]
When
You
Code
It

**Comment by AlphaBuffalo** [comment]
teach me then :^)

**Comment by Ephx1** [comment]
Should require money, another thing to let you use your worthless space credits for.

**Comment by JustSumBody** [comment]
> Would the ability to customize clothes improve immulsion or hinder it?
> Yes or no

You can learn Byond
http://ss13.moe/wiki/index.php/Understanding_SS13_Code
http://ss13.moe/forum/viewtopic.php?f=10&t=2476
http://www.byond.com/docs/guide/

**Comment by ComicIronic** [comment]
> teach me

What are you, a casual? Learn like the rest of us and get in the IRC.

**Comment by AlphaBuffalo** [comment]
Well... is something like this even possible in DM code?

**Comment by Intigracy** [comment]
Anything is, it just depends on the amount of work involved to make it
happen.

**Comment by 9600bauds** [comment]
If we're refactoring updateiconcode it should happen before this

**Comment by Imagebard** [comment]
This isn't going to happen in first place.

**Comment by NigglyWiggly** [comment]
Obviously

**Comment by AlphaBuffalo** [comment]
Th-thanks for the support guies.

**Comment by 9600bauds** [comment]
I mean it CAN be done
uh
yeah that's all I've got here
