### ISSUE TITLE
Issue NamePuking while inside Cryo puts your vomit inside the mix

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10926]
(WEB REPORT BY: 9600bauds REMOTE: 172.93.109.202:7777)
Why

**Comment by Ephx1** [comment]
it's a feature

**Comment by 9600bauds** [comment]
It fucks up the ratio of the ingredients

**Comment by SkowronX** [comment]
kek

**Comment by Kurfursten** [comment]
IIRC vomiting just picks a beaker on the same tile as you to place vomit into. This can be annoying if you're trying to vomit into one specific beaker but you forget that you're standing on a different one and now you have to visit the chemmaster.

Send vomit to chef to make nutrition cubes.

**Comment by Intigracy** [comment]
this makes 100% sense though, you're putting your vomit into the chamber with the chemicals

**Comment by 9600bauds** [comment]
No, the beaker with the mix gets gradually released into the cryotube. It doesn't all get dissolved into the tube.
Otherwise how could you retrieve the mix back into the beaker on demand?

**Comment by Kurfursten** [comment]
I think everyone can agree that we could use better vomit acquisition mechanics. You should be able to vomit into buckets or any other open container, for example. And I get the feeling people in cryo shouldn't be vomiting at all since they can't bleed in there either. Also I would like it to prefer to vomit into the thing in your hand before just anything on your tile.

**Comment by 9600bauds** [comment]
I don't know if you can vomit while unconscious/frozen, however the guy today managed to vomit right after I put him in the tube but right before I turned it on

**Comment by FudgePucker** [comment]
Wait can you get nutrient from vomit?
Wouldn't it be possible to evolve a failed dionia nymph using a monkey man injector, rev him using defib, then inducing vomiting?

LIMITLESS NUTRIENT.
(Unless plantpeople can't vomit due to being practically immune to toxins)

**Comment by Kurfursten** [comment]
You can't get nutriment from vomit unless you cook it

Limitless nutriment is as easy as using the ice cream machine though...

**Comment by 9600bauds** [comment]
Hydroponics trays are infinite nutriment and they're also faster than some vomit business

**Comment by Probe1** [comment]
That's revolting and that's the way it should be.
