### ISSUE TITLE
Mind Transfer works while dead.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10929]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 2f046514159531952bc5856c5ab12ff4a694dcd9 
> 
> General description of the issue
> Mind Swap victim gets Mind Swap, it works across the station to swap back into the previous body, it works while dead so the wizard and the victim play fucking tug-o-war with the body.
> 
> What you expected to happen
> None of that shit.
> 
> What actually happened
> All of that shit.
> 
> Steps to reproduce if possible
> Mind Swap into some fuck, then lase them 4 times, then have them mindswap before they pass out from crit.

**Comment by clusterfack** [comment]
@intigracy you said you fixed this?

**Comment by Intigracy** [comment]
No I didn't

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/pulls?utf8=✓&q=is%3Apr%20author%3AIntigracy%20is%3Aclosed%20mindswap

https://github.com/d3athrow/vgstation13/pulls?utf8=✓&q=is%3Apr%20author%3AIntigracy%20is%3Aclosed%20swap

https://github.com/d3athrow/vgstation13/pulls?utf8=✓&q=is%3Apr%20author%3AIntigracy%20is%3Aclosed%20mind

**Comment by clusterfack** [comment]
@drcelt I thought you said you fixed thus #10647
