### ISSUE TITLE
 Priority Announcement  Payroll has been processed. All accounts eligible have have recieved their paycheck as a direct deposit, including department accounts.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#10921]
Priority Announcement

Payroll has been processed. All accounts eligible have have recieved their paycheck as a direct deposit, including department accounts.

this is shitcode because it doesn't use the central command announcement proc, who coded this

**Comment by PJB3005** [comment]
Also if you copy pasted that right it says recieved instead of received.

@gbasood

**Comment by Intigracy** [comment]
`<vg-status> It's spelled received dumbass not recieved but i cleared your messages anyways`

**Comment by gbasood** [comment]
¯_(ツ)_/¯ 
I tried to figure out a way to make it fit flavor without being annoying, apparently not too well
If you have a better idea, by all means
