### ISSUE TITLE
has thrown a cursed dice and rolled a 8

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10920]
(WEB REPORT BY: drcelt REMOTE: 172.93.109.202:7777)
has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8has thrown a cursed dice and rolled a 8

**Comment by kol1th** [comment]
???????????

**Comment by AlphaBuffalo** [comment]
I think Celt is just noting this for later so he can fix it, thats the only thing that makes sense to me

**Comment by 9600bauds** [comment]
Even while shitposting my web reports are not the worst

**Comment by ghost** [comment]
HAS ROLLED A 8
A EIGHT
A EIGHT

**Comment by 9600bauds** [comment]
https://www.youtube.com/watch?v=87H6m2v4zNs

**Comment by ConkerDev** [comment]
https://www.youtube.com/watch?v=uMOmSjHvl8s

**Comment by Intigracy** [comment]
this is why celt will never be cool
