### ISSUE TITLE
[Bus Station] Xenoarch/Mining outpost issues

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10930]
1. The first room, "Outpost Research Dock" has no APC or wiring whatsoever and because of that it starts with no lights.
2. The vent in "Outpost Study Area" starts turned off.
3. "Auxiliary Storage" contains a whopping 1 sheet of metal and 1 sheet of glass.
4. The entire outpost does not have scrubbers or a waste gas line.

**Comment by Kurfursten** [comment]
Thanks for reporting these. I'm kind of surprised the first one hasn't been reported before now... Most of this stuff is the result of it being basically just Taxi's outpost with a modified front end. Some point down the line, it should probably be rebuilt from scratch.
