### ISSUE TITLE
Traitors being assigned twice.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#10948]
![end](https://cloud.githubusercontent.com/assets/5549060/16711257/aa94b1ce-4617-11e6-9466-5aaeadb44a41.png)

```
**_Here we see someone who completed their objectives.
You'll notice that it says 10/20.
I got two different PDA codes and the first one stopped working once the second was assigned._**
```

![dubyah](https://cloud.githubusercontent.com/assets/5549060/16711258/c9e65b0e-4617-11e6-844a-be21bcbce7cc.png)
End game screen and we see all the traitors assigned twice.
Bls fix

**Comment by Gringonius** [comment]
![34 crystals](https://cloud.githubusercontent.com/assets/6732634/16711303/edf20f62-462a-11e6-89b0-e9e946a2c310.png)
Double/triple assignment like you've described has been happening for a while but I haven't noticed the TC count at the round end screen until now.

**Comment by Killette2** [comment]
You think that is bad? Check this

![6objectives](https://cloud.githubusercontent.com/assets/5169310/16711362/00a79fce-4625-11e6-9654-07b6c3cf3244.png)

**Comment by Intigracy** [comment]
Will fix tomorrow.

**Comment by 9600bauds** [comment]
I see that autoclicker

**Comment by Exxion** [comment]
I was going to link one of the other issues about this, but turns out they're both closed because someone apparently incorrectly claimed they fixed it

**Comment by Killette2** [comment]
What ya gonna do about my autoclicker? It wasn't even used for spess and I don't see how autoclickers can be used for space.

Except that day or two punches had no cooldown. Now THAT was fun/horrifying.

**Comment by Exxion** [comment]
Autoclickers can be used for two things in SS13:
1. Stupid bullshit such as lightspeed chair rotation
2. Combat without getting carpal tunnel but otherwise roughly equally effective

**Comment by Killette2** [comment]
> autoclickers
> for combat

I don't think so, if anything autoclicker makes you worse at combat. For example if you use an energy sword and hit the floor instead of your target, there's still a swing cooldown before you can swing again even if you didn't hit anything.

Chair action shall not be infringed however.

**Comment by Shadowmech88** [comment]
Weapons can't be swung at turfs.

**Comment by Killette2** [comment]
Are you sure? try clicking really fast, then click accurately with an executioners sword. I feel a difference.

**Comment by PJB3005** [comment]
He may be right here.

**Comment by clusterfack** [comment]
What am I going to do about your autoclicker?

Easy, we'll randomize the order of items from vending machines.

**Comment by Killette2** [comment]
@clusterfack 

Don't you dare

Also I'm not some pleb who dispenses 3 of each seed, which causes famine if your plants end up dying.

**Comment by gbasood** [comment]
> order more seeds

**Comment by Killette2** [comment]
IIRC, you can't order every seed out of the vending machine through cargo, OR through weed mutation (see towercaps).

Even if you buy produce and seeds (exotic seeds used to have real plant seeds, but now have xenobotany seeds) you still won't get the fruits and veges you need. Also I believe the only way to get bananas from cargo is if you order the food supply crate, which comes with the ingredients to make banana bread.

**Comment by Shadowmech88** [comment]
You can always order no-fruit seeds and use those to produce other plants and extract their seeds.

**Comment by Killette2** [comment]
You have a better chance winning to jackpot from the one armed bandit.
