### ISSUE TITLE
Trying to turn on your internals if you don't have a tank causes a runtime, which is easy to fix but the runtime itself is bizarre and mysterious

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#10946]
The runtime occurs just because someone forgot to make `toggle_internals()` return if there is no valid tank. Easy to fix.

But for some reason, where it should say the file the runtime occurred in, instead it says... something else. On my local server, it's always "**Fully charged.**" (yes, including the bolding and the period), but in the runtime log it seems to vary between rounds
It still says the correct line number (56), just not the filename

?????

**Comment by 9600bauds** [comment]
The magic
and
the mystery

**Comment by Killette2** [comment]
Of potato knishes

**Comment by Exxion** [comment]
Apparently, there are several runtimes that have this strange behavior
In today's runtime log, I found 95 instances total of about 5 distinct runtimes that reported some random string as the name of the file the runtime occurred in
Note that my regex was shit and it's possible there were more that I missed, though probably not many

**Comment by PJB3005** [comment]
Confirmed byond bug but lummox hasn't been able to track it down.

Ive reported it already.

**Comment by 9600bauds** [comment]
no longer runtimes
