### ISSUE TITLE
Seeing Parallax where you shouldn't see anything

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#10944]
I know someone made an issue for this but I think it was fixed and it seems to be bork again
.

![](http://i.imgur.com/7SpcwYT.png)

**Comment by ComicIronic** [comment]
What Byond version are you on?

**Comment by AlphaBuffalo** [comment]
Byond version 510.1437

**Comment by Intigracy** [comment]
Yeah, this is the first time I've ever been experiencing this and I'm up to date on byond.

**Comment by Exxion** [comment]
It specifically happens whenever you can't see any space tiles

@clusterfack

**Comment by clusterfack** [comment]
Haha it happens if you don't see any space tiles? What the fuck

**Comment by clusterfack** [comment]
Probably something to do with plane masters not drawing when they have no elements on the screen

**Comment by clusterfack** [comment]
But why it would let parallax blend multiply into darkness is byond me

**Comment by kernikov** [comment]
PLANES?

**Comment by PJB3005** [comment]
@clusterfack you need to always have a plane master be controlling SOMETHING (an invisible dummy us enough) else it goes haywire. Ask @DrCelt about it on Discord.

**Comment by clusterfack** [comment]
I already fixed this, shush
