### ISSUE TITLE
Electrical terminals are layered below wires.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10959]
@DrCelt PLANES

![](http://i.imgur.com/SD4N54N.png)

**Comment by Imagebard** [comment]
Why are we making individual issues about this
Does each issue have to be fixed individually

**Comment by ihadtoregisterforthis** [comment]
Duplicate

**Comment by ComicIronic** [comment]
Because a single issue can be opened or closed.
If you have a massive mono-issue, you can't ever say it's closed. Are there more planes bugs? Who knows, but we can't say there definitely aren't, so we've got a useless tracking issue for nothing in particular.
