### ISSUE TITLE
Muh waifu socks don't layer properly

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#10952]
![000](https://cloud.githubusercontent.com/assets/7571238/16713173/51be7cca-4675-11e6-8d15-6421a4e9daf1.png)
Why

![0000](https://cloud.githubusercontent.com/assets/7571238/16713174/58e846d4-4675-11e6-8b0b-a9e6fb46ecb1.png)

WHYYY are the socks above the skirt?

**Comment by Shadowmech88** [comment]
Because the shoe layer is above the jumpsuit layer on a mob's overlays.

The question is, would there be any downside to moving the shoe overlay below the jumpsuit overlay?

**Comment by clusterfack** [comment]
Yeah probably

**Comment by Imagebard** [comment]
_Fuck_

**Comment by Shadowmech88** [comment]
Only if you don't want anyone to investigate to actually make sure such a thing would cause problems.

**Comment by Imagebard** [comment]
Eh, lets try to make this easier...
Is it possible to make a exception just for kneesocks?

**Comment by Shadowmech88** [comment]
>Is it possible to make a exception just for kneesocks

That would probably be more difficult than just moving the shoe overlay below the jumpsuit overlay for all clothes.

**Comment by clusterfack** [comment]
Yeah, probably

**Comment by Imagebard** [comment]
Oh.
Well, uh, I'll let a collaborator decide when to close this then

**Comment by NigglyWiggly** [comment]
this is intentional, I think.
If you wear the socks with a suit or jumpsuit, it creates a pseudo-skirt looking thing.

**Comment by ultraplen** [comment]
@Shadowmech88 
Moving the shoe overlay under the jumpsuit overlay would ruin the appearance of all non low shoes since the upper part of the shoe would be covered by the jumpsuit

**Comment by Blithering** [comment]
Magboots and jackboots would be the worst affected by moving the shoe layer down. An alternative would be to just alter the kneesock sprite to end lower down on the leg.

**Comment by Imagebard** [comment]
Well, I guess it works fine on normal jumpsuits.
I'm so sorry I'm leaving you to die, sweet Issue...
