### ISSUE TITLE
Virologists start with their regular PDA + another blank PDA inside their satchel

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#10954]
#### Description of issue

title
#### Difference between expected and actual behavior

having just my regular PDA
got 2 PDAs
#### Steps to reproduce

start as virologist
#### Specific information for locating

see inside satchel.
haven't tried with backpack.
#### Length of time in which bug has been known to occur

happened today and also past days
#### Server revision

31b991597cf8289c6d463ebe427b2677cf101db2 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by JustSumBody** [comment]
Might be related, but their ID is the default green instead of medbay blue

**Comment by Blithering** [comment]
Can confirm it happens to multiple players, I've spawned with a blank PDA in my bag as viro too.

**Comment by uazuaz** [comment]
@Blithering 
OP updated, thanks.

**Comment by Hikato** [comment]
Fixed in #11068 :*
