### ISSUE TITLE
Windows do not protect people with TK from shocked grilles.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#10955]
#### Description of issue

As stated.
#### Difference between expected and actual behavior

People should not get shocked by said windows.
#### Steps to reproduce

Get TK, move on a live grille, it can be under 4 directionals and 1 tile windows, the person will still get shocked.
#### Server revision

31b991597cf8289c6d463ebe427b2677cf101db2
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
If the grille was made before any of the windows, this probably applies regardless of whether or not you have TK

**Comment by Gringonius** [comment]
In the round this happened I kept shocking myself in bridge and brig windows after having rolled a 20 with a cursed die, my coworker couldn't get shocked on the same windows and an admin tested and confirmed this.
I've actually tested this in a local server and I can confirm it, walking into those windows with TK shock you, without it they are safe.

**Comment by Exxion** [comment]
Wow. That's strange.
Why would it even check that?

**Comment by clusterfack** [comment]
Probably due to the TK interaction with the in range proc
