### ISSUE TITLE
xenobio borers metaclub

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10956]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> there is no way for a borer to get out of xenobio if not from doors
> 
> What you expected to happen
> pipe system to the station
> What actually happened
> DOOR
> 
> Steps to reproduce if possible
> be a borer in metaclub

**Comment by ComicIronic** [comment]
Not a bug.
