### ISSUE TITLE
Deaf while dead after explosion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10961]
(WEB REPORT BY: mchotnspicy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

018843b05edb1184f843e226710d7082fc291315

> General description of the issue

Died from a gibonite explosion and now i cant hear (You can almost hear someone talking.) the living.

> What you expected to happen

To be able to hear the living

> What actually happened

You can almost hear someone talking.
You can almost hear someone talking.
You can almost hear someone talking.
You can almost hear someone talking.
You can almost hear someone talking.
You can almost hear someone talking.

> Steps to reproduce if possible

Die from gibonite, or possibly any explosion

**Comment by ghost** [comment]
Could not reproduce
