### ISSUE TITLE
you float after being stunned on a vehicle

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#10973]
update_mob() doesn't get reset if you get stunned on it, only when you are unbuckled

**Comment by Allspice** [comment]
If you buckle and get stunned again do you float higher?

**Comment by kol1th** [comment]
Nope. Resets your pixel shit when you buckle back. The only way to fix it is buckle in/ unbuckle.

**Comment by Shadowmech88** [comment]
Fixed by #19962.
