### ISSUE TITLE
Strange pinpointer behaviour on examine

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10975]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 018843b05edb1184f843e226710d7082fc291315 
> 
> General description of the issue
> When examined, the pinpointer states approximately that there are "no active nuclear devices detected." Even if the operative nuke is armed and ticking.
> 
> What you expected to happen
> Either the pinpointer does not have that text ever or it changes to "active nuke detected" when it is armed.
> 
> What actually happened
> nope
> 
> Steps to reproduce if possible
> Insert disk, insert code, toggle the safety and timer.

**Comment by kernikov** [comment]
Is the captain's pinpointer the same object as the nukeop one? 
I know for a fact that the nuke op one works as intended.

**Comment by Aurx** [comment]
It is not.  The cap's is of type /obj/item/weapon/pinpointer while the nuke op's are of type /obj/item/weapon/pinpointer/nukeop

**Comment by nervere** [comment]
This is fixed. Testing done by @Inorien - thanks!
