### ISSUE TITLE
Runtime in gameticker.dm,185: pick() from empty list

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10980]
Pomf decided that the random spacepod spawning code should be placed in the gameticker of all places. Sadly this results in a runtime if there's no spots for spacepods. This actually causes part of the gameticker code to not get called. It only affects the test map though.

``` DM
[16:10:16] Runtime in gameticker.dm,185: pick() from empty list
  proc name: setup (/datum/controller/gameticker/proc/setup)
  src: /datum/controller/gameticker (/datum/controller/gameticker)
  call stack:
  /datum/controller/gameticker (/datum/controller/gameticker): setup()
```

**Comment by ghost** [comment]
This has since been fixed - Line 185 is now the sanity to prevent this
