### ISSUE TITLE
Being able to dump pills from a pill bottle

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#10989]
Should be about as simple as copying the functionality from the pill bag to the pill bottle, so if you'd like to dump them on a table for some reason, you could.

**Comment by 9600bauds** [comment]
Clickdrag pillbottle into table, but yeah you should be able to use it in your hand to do it too

**Comment by nuklearcellphoneg** [comment]
I'd tried to dump them by Use, but assumed click+drag didn't work

But yeah, being able to stand alone dump would be 'nice' but if they click + drag works then this isn't so important imo.

**Comment by clusterfack** [comment]
Click drag storage onto tables was the best qol feature I ever made

**Comment by ComicIronic** [comment]
Fulfilled in a general way, I don't see the need to add specific ways of doing this to all storage items.
