### ISSUE TITLE
Hideo Kojima's Metal Gear Solid V: The Phantom Pain

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#10984]
Missing limbs cause pain. Even if the limb was cleanly removed via surgery.
Having a couple missing limbs means permanent stacking pain stun unless you are forever hopped up on painkillers.
There's been a lot of confused players wondering why having no legs turned them into a fucking vegetable that can't even use their perfectly good hands. In part this also makes wheelchairs kind of pointless too.

**Comment by ghost** [comment]
Can we have more detail. Does getting your limb blast off give you permanent ghost damage ? Or does your amputated limb somehow accumulate ghost damage ?

**Comment by 9600bauds** [comment]
There is specific code to make any missing limb instantly be a 60 in the pain rating or something like that
This is intended and it's dumb as hell

**Comment by ghost** [comment]
Right, if not properly amputated

Should be toned down, or it should be fixed by going through the organ graft procedure

**Comment by 9600bauds** [comment]
There is NO proper way to amputate it it seems
Or no known way to make it stop hurting
It acts very silently and unintuitively too, in TG they have a tag for this and it's "Bad Feature"

**Comment by Gringonius** [comment]
Doesn't doing the limb replacement surgery short of actually attaching a new limb remove the pain? That said it is silly since at that point the patient can easily get a new limb.

**Comment by Killette2** [comment]
Uhhh you guys know if you cauterize the missing limb, it leads to NO pain.

Is this why it's called the wild ride? All you have to do is burn the wound shut and they shouldn't feel pain at all, pretty sure that's how it is.

**Comment by 9600bauds** [comment]
Well that's pretty shit, especially since you don't actually have any damage and nothing tells you what's giving you the pain

**Comment by Killette2** [comment]
Well you're not wrong.

I'm pretty sure if you get put in a medical scanner it will say nothing, even if any bleeding stopped.

It just makes a bit of sense that if your arm gets cut off you kinda want to close the wound. Even if blood isn't flowing to it, it probably still hurts like hell and should be sealed off.
