### ISSUE TITLE
The 'horns' genetic power cannot be removed.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10983]
(WEB REPORT BY: kernikov REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f01cfbadfc946f6440c379dffcf7bf1f2b296901 
> 
> General description of the issue
> If you're cloned and end up with horns you're stuck with them.
> 
> What you expected to happen
> A clean SE or Ryetalyn to remove them.
> 
> What actually happened
> I still look like I belong in a Homestuck comic.
> 
> Steps to reproduce if possible
> Be cloned / acquire horns.
> Try to lose them without being recloned.

**They don't appear when I'm examined, which I think they're supposed to be.

**Comment by Imagebard** [comment]
You can't fix Homestuck fans because they have mental disease.

**Comment by Shadowmech88** [comment]
I can't exactly test randomly obtaining horns as the result of cloning, but activating and deactivating the block itself seems to cause the horns to appear and disappear as one would expect.
