### ISSUE TITLE
Access datums: How?

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10986]
A recent round as vox raiders left me really salty, and as a result I'm gonna code access datums.

So first of all vox, syndicate and Nanotrasen access levels will be completely separated. The question is how I should do it though gameplay wise.

I'm talking how could you set things like tool dispensers to use vox access.
My current plan is that things like circuits have access chips which default to NT access chips, but the chips can be replaced with Vox access chips and such.

Of course taking an access chip off something would need access to the chip.

Discuss how access chips should work.

**Comment by 9600bauds** [comment]
I don't see why any of this needs to be done with this chip business
Just like set different access levels on stuff
Centcomm and Syndie stuff has worked like this for a while

**Comment by ComicIronic** [comment]
An extendable chip system is a pretty cool idea, but I'm worried about the possibility of overcomplication of the construction process, especially for roundstart machines.

It would be more sensible to just set access on boards directly a la airlock controls.

**Comment by FudgePucker** [comment]
Its simple really.
We remove the vox traders.

**Comment by clusterfack** [comment]
We make vox traders into vox traitors
