### ISSUE TITLE
Surgeon's Switchtools Tools Not Coming Out for Replacement

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10997]
(WEB REPORT BY: kinggrimlock REMOTE: 172.93.109.202:7777)

> Revision f01cfbadfc946f6440c379dffcf7bf1f2b296901 
> 
> General description of the issue
> The tools for the surgeon's switchtool aren't coming out when they're activated and you click on a table with them.
> 
> What you expected to happen
> I expected the tool that was ccurrently activated (in my case, the retractor) to come out of the switchtool when you click on the table with the tool in question out.
> 
> What actually happened
> The rettractor stayed in the switchtool, even when I had it activated and clicked on a table with it.
> 
> Steps to reproduce if possible
> 1. Obtain a surgeon's switchtool.
> 2. Activate any of the tools (for the purpose of comparing to mine, let's say the retractor henceforth)
> 3. Click on a table or desk with the retractor/tool.
> 4. The tool will not leave the surgeon's switchtool, making the retractor/tool impossible to replace.

**Comment by ihadtoregisterforthis** [comment]
#10662
Was it a feature all along?

**Comment by Gringonius** [comment]
Literally a feature now.

**Comment by ComicIronic** [comment]
You take them out with a screwdriver, this is not an issue
