### ISSUE TITLE
Scanning vox raiders results in the scanned in name being the player's selected character slot.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10991]
![](http://i.imgur.com/Lw1RHfx.png)

**Comment by clusterfack** [comment]
That's weird, problems with real_name not being used potentially?

**Comment by PJB3005** [comment]
Also if cloned that's the name they actually get.

**Comment by SkowronX** [comment]
remove raider

**Comment by Exxion** [comment]
#8328

**Comment by PJB3005** [comment]
Welp, guess I didn't search thoroughly enough.
