### ISSUE TITLE
Being able to scoop pills into a beaker

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#10990]
This would have the same functionality as say, picking up pills with a pill bottle or pill collector, except that you're using a small/large/bluespace/stasis beaker. So for example you have a beaker with x,y, and z reagents and you make the pills the wrong size or mixture, instead of placing them one by one back into the beaker, you could just scoop them into the beaker.

**Comment by 9600bauds** [comment]
Pick up into pill collector, click on grinder, grind
This is already in the game
If you let any beaker do this instantly I foresee grifftastic instantaneous fridge emptying

**Comment by 9600bauds** [comment]
If you want to get more convenient I would also support being able to slap a chemmaster with a fridge collector to melt pills into buffer
I really don't like the idea of adding this to all beakers

**Comment by nuklearcellphoneg** [comment]
If you're afraid for this having a propensity to grief, if someone were to use a couple of pill collectors to take all the pills out of the fridge, would this be any different? You can get pill bags a couple of different ways, same with beakers or large beakers or so on, and pill bags can hold much more than a beaker, ala, beakers max out at 300 I believe, whereas the amount in a single pill has no bearing as to how many pills a pill bag may hold.

**Comment by nuklearcellphoneg** [comment]
And if we're talking about upgrading the dispenser and chemmaster, how about making it so that upgrading the chemmaster giving you an internal beaker which isn't dumped when you remove beakers. :^)

**Comment by 9600bauds** [comment]
Because it's exceedingly rare to see more than 2 pill collectors in the station at any given time and they're usually both inside chemistry and they can still hold less than 50 or so pills which you can't immediately get rid of even with a locker even if you get ahold of one (compare to a beakersplash on floor)
It really is a world of difference

**Comment by nuklearcellphoneg** [comment]
You can make pill collectors in the autolathe if I remember right, as well as ordering them from cargo- same as beakers.

**Comment by ComicIronic** [comment]
Bauds already pointed out a way to do this - I don't think the convenience is worth the wat factor of auto crushing a bunch of pills somehow.

**Comment by 9600bauds** [comment]
Needs a Cargo supply crate
Half a year ago there was only ONE pill collector in chemistry, too

**Comment by nuklearcellphoneg** [comment]
Personally, I thought being able to crush pills into beakers was already odd, but fair enough.

**Comment by 9600bauds** [comment]
It's still a good idea, just not with letting beakers do it

**Comment by 9600bauds** [comment]
In particular it would be nice if the grinder could hold more than 10 pills when you do this, ideally you could fit up to 20 since that's the most you can make by accident

**Comment by nuklearcellphoneg** [comment]
Would there be a way to change it to where it depends on the amount of reagents in the grinder and not objects?

**Comment by 9600bauds** [comment]
It's possible, but probably not very intuitive or immediately appreciable
The grinder is mostly used for Chef stuff to begin with

**Comment by 9600bauds** [comment]
Realistically how bad would it be if Chemistry started off with a slightly, slightly upgraded grinder that only had tier 2 matter bins for that 20 capacity?
In at least 90% of rounds it's only ever used to grind exactly 1 item anyways

**Comment by nuklearcellphoneg** [comment]
I'll be honest, most of my personal interaction with grinders involves putting a few pizzas in, grinding them, removing nonnutriment, then readding the beaker to continue grinding.

I don't think it would be a noticeable change compared to, say, more large beakers at round start: In fact, I would say even when it came to powergaming the grinder, by buying various things which contain rare ingredients, at the end of the day it's likely you're going to be changing out beakers more than adding in new reagents.
