### ISSUE TITLE
Warden's office does not start with a standard security camera console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10998]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision f01cfbadfc946f6440c379dffcf7bf1f2b296901
> 
> General description of the issue
> Title
> 
> What you expected to happen
> Starting with a normal security cam console, because 1. the advanced sec cams have been shitty for so long; and 2. to make it easier to track silicons.
> 
> What actually happened
> NOPE.
> 
> Steps to reproduce if possible
> Join as a warden and despair.

**Comment by ihadtoregisterforthis** [comment]
Map?

**Comment by ScrambledSteak** [comment]
I thought adv. sec cams work now

**Comment by Allspice** [comment]
Definitely box, but I don't remember any map having a standard console in warden, just the fucked advanced one.

**Comment by AutismSpider** [comment]
they bug the fuck out form time to time some open issue about it.

Adv one is god awful due to this it randomly bug out making it useless

**Comment by kernikov** [comment]
Minus the issue, advanced camera console is fine.

**Comment by Allspice** [comment]
Just like how the CMC is fine am I right

**Comment by Gringonius** [comment]
What's not fine is the atmos central computer.
Still not updated for 512x512 z-levels.

**Comment by Imagebard** [comment]
Nothing has been updated so far.
And, Advanced Security Camera consoles are wonky, always have been. sometimes they work, sometimes they don't.

**Comment by Exxion** [comment]
They're still broken?
Report it again and ping Cluster. He said he fixed it.
I'm starting to think it's a BYOND bug

**Comment by PJB3005** [comment]
I've got an idea.

It's an AMAZING idea too.

Want to know it?

# NANO

# UI

**Comment by Exxion** [comment]
NanoUI sucks, but at least the NanoUI maps actually worked
Which is more than can be said for the HTML ones

**Comment by Durgen** [comment]
The current buggy advanced console is still more useful than the standard. If a Warden hates it so much, they can just use the standard in the lobby.

**Comment by Exxion** [comment]
The current one isn't more useful than the standard for the many people for whom it doesn't work at all

**Comment by clusterfack** [comment]
And why wouldn't it work for them at all

**Comment by Exxion** [comment]
Because it's still broken, as has been said above
Unless they were wrong about that
I have no idea because it works for me, but it also did during part of the time when it was confirmed broken so that doesn't mean anything

EDIT: Yep, it's still broken
Though less so than it used to be, in that relogging and trying again fixes it now sometimes and it happens less often after clearing the cache

**Comment by gbasood** [comment]
not sure if still issue

**Comment by CptWad** [comment]
it isnt
this can be closed
