### ISSUE TITLE
Food processor doesn't retain chemicals in the ingredient used.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10996]
So if I try to turn my potato with cyanide into fries the cyanide magically dissappears.

**Comment by ghost** [comment]
Goof food strikes again?

**Comment by 9600bauds** [comment]
This is how Rasputin didn't die

**Comment by Gringonius** [comment]
The food processor predates goof for sure.

**Comment by AutismSpider** [comment]
food processor predates goof ball.

if it was goof code it come out as cyanide fries or some shit

**Comment by nervere** [comment]
No longer an issue. Testing done by @Inorien - thanks!
