### ISSUE TITLE
Vox raider shuttle doesn't perfectly connect to the vox outpost.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#10992]
![](http://i.imgur.com/l9b9oCa.png)

**Comment by kol1th** [comment]
STILL? DYLAN

**Comment by Intigracy** [comment]
Thanks @dylanstrategie

**Comment by ghost** [comment]
This time it's the shuttle design that is plain retarded

I'll work on it once all the current Boxstation map PRs are merged

**Comment by Intigracy** [comment]
the shuttle design wasn't changed

you should have tested the map when you changed it last time

**Comment by ghost** [comment]
Nah

**Comment by PJB3005** [comment]
So now you're admitting to not testing. It's like you don't _want_ merges yet you still beg for them.

**Comment by Probe1** [comment]
how the shit do I even make this work

![image](https://cloud.githubusercontent.com/assets/8550416/20716336/dcf5b35c-b61f-11e6-95a7-f828799b9146.png)
