### ISSUE TITLE
medbay intercomms issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#10993]
#### Description of issue

i can assume that near medbay's entrance ideally there would be an intercom set on 148.5 with the microphone enabled and speaker disabled, and all around medbay there would be other intercoms set also on 148.5 with microphone disabled and speaker enabled, so if someone is at medbay's entrance they can talk and be heard by anyone in medbay;
if this is the case, is not working as intended.
#### Difference between expected and actual behavior

_META_
all intercoms inside meta's medbay are set on 148.5 as intended, but all of them are set with mic enabled and speaker disabled, therefore they don't serve their purpose.

_BOX_
- only the entrance near chemistry and the one on the medbay's entrance desk, near the windoor, have such intercoms; the one near paramedic station doesn't;
- there are only 2 intercoms inside medbay set on 148.5: one near chemistry and the other one inside the medical storage, all other intercoms are set on the default 145.9 common channel
- the intercom on the medbay's entrance desk, near the windoor, is set on 145.9 with mic disabled and speaker enabled

(side note: on all maps, there is an intercom set on medical channel 135.5 near the cloning pod, but on meta the intercom is called "Station Intercom (General)" and on box is called simply "station intercom"; i know that the medical channel is intended to be used, the issue is just the intercom's names)

NOTE: i only checked meta and box, the other maps should also be checked.
#### Server revision

f01cfbadfc946f6440c379dffcf7bf1f2b296901
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by eplgr** [comment]
@uazuaz If you are alive you might wanna check out my PR.
