### ISSUE TITLE
orderable conveyor circuits crate (feature request)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#10994]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
make cargo able to order conveyor circuits crates

**Comment by kol1th** [comment]
Why? Use a soldering iron

**Comment by pvak** [comment]
it consumes too much time and acid

**Comment by kol1th** [comment]
Takes much less time than a cargo shuttle, and it doesn't use much acid either.

**Comment by pvak** [comment]
why would I have to bother chemists for 200u of acid when I could order 10 crates of conveyors circuits (with like 8 circuits inside each)

**Comment by PJB3005** [comment]
Because that's still nothing compared to hauling 10 crates.

**Comment by kol1th** [comment]
> why would I have to bother interacting with others on a multiplayer game? 

Well meme'd. Let's just remove everything and add it to cargo.

**Comment by ComicIronic** [comment]
Have you tried genfabbing them?

**Comment by 9600bauds** [comment]
Yes and it was awful

**Comment by kol1th** [comment]
Gen fab is even slower

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Conveyors no longer even need circuits
