### ISSUE TITLE
Can't make a table fort corner

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#11008]
Making a table on top of a flipped table deletes the flipped table.

**Comment by FudgePucker** [comment]
Main problem with this is that it would let you make infinate tables on a single turf.
Flip table build table flip table build table...

**Comment by Exxion** [comment]
Well it shouldn't delete the flipped table
It should just not let you build the other one
Or something else
Like you can't flip a table in the direction another flipped table already is on the tile

**Comment by nervere** [comment]
Seems to have been fixed now. Testing done by @Inorien - thanks!
