### ISSUE TITLE
Make bees farmable

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11007]
You cannot currently gain more than one queen from a bee hive. When you can farm and increase everything else in botany from plants to livestock like chickens, why are bees limited?

The best you can currently do is use a hatchet on a stage 3 bee hive and you will get your queen back along with some honey. That's grand and all, but why isn't there a way to get 2 queens from a hive? Won't hives want to produce more queens for when the queen dies? I suggest there be implemented a way we can farm bee queens.

**Comment by clusterfack** [comment]
I'm no beekeeper but I think the hive kills all new queens until they need a new one

**Comment by PJB3005** [comment]
No I think the queen produces pheromones or something which prevent the growth of workers into queens entirely.

**Comment by clusterfack** [comment]
See, bees are magic

**Comment by FudgePucker** [comment]
Actually, they produce more than one queen, when this happens you need to take the new queen out and relocate her or half of the hive will fly off with her to spread. This is how you buy queen bees in the first place.

The more you know.gif

**Comment by Killette2** [comment]
Your gif didn't work

**Comment by Blithering** [comment]
![mpcfkjyt4f-2](https://cloud.githubusercontent.com/assets/15067109/16896022/193aaa9a-4b7f-11e6-86c9-9d20ab3a9d87.png)
Would it be possible to make level 3 hives spread to nearby empty ones?

**Comment by Killette2** [comment]
I like your idea Blithering. The new queen moves its bees to a nearby empty apiary and both hives start out at level 0 or 1 with a queen inside.

**Comment by ConkerDev** [comment]
that would be really OP. A single queen filling all of hydroponics in minutes. I think the vending machine as a limiting factor is fine

**Comment by Killette2** [comment]
1. Bees don't come from vending machines
2. A level 3 hive takes a decent amount of time to become, hardly in minutes like you claim
3. We suggested the hives reset due to the bees "splitting up"

Maybe if this was implemented, hydro would be full in an hour at best.

**Comment by ConkerDev** [comment]
Okay then
