### ISSUE TITLE
Reactive chemicals mix in the chemmaster but don't the expected effects

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11005]
(WEB REPORT BY: sailol REMOTE: 172.93.109.202:7777)

> Revision Don't know
> 
> General description of the issue
> Self explanatory
> 
> What you expected to happen
> I expected to get pills that wouldn't react till on a beaker or inside the body
> 
> What actually happened
> The chemicals mixed in the ChemMaster3000 and blew up, yet neither me nore the machines took any damage, I was just knocked back and I got the usual flavour text for mixing chemicals.
> 
> Steps to reproduce if possible
> 1.- Fill a stasis beaker with water and potassium
> 2.- Put the beaker in a ChemMaster3000
> 3.- Move potassium and water into the machine
> 4.- Watch it explode but not really

**Comment by FudgePucker** [comment]
Not a bug.
No you can't make gib pills

**Comment by Exxion** [comment]
The not really exploding part is a bug
And yes you can make gib pills, but you need a time release pill and a syringe

**Comment by ghost** [comment]
Not a bug, use a no react beaker for your epic explody pills

**Comment by Intigracy** [comment]
this is a bug

the not exploding part is a bug

**Comment by Exxion** [comment]
Can people maybe try reading the whole report before commenting not a bug?

**Comment by Shadowmech88** [comment]
Does 25u water 25u potassium cause a sizeable explosion?

**Comment by PJB3005** [comment]
Whoops.

Yeah @Shadowmech88 enough to break a bone or two if you're standing next to it if I had to guess.

**Comment by charmstruck** [comment]
> Yeah @Shadowmech88 enough to break a bone or two if you're standing next to it if I had to guess.

30/30 explosions are strong enough to pop open lockboxes but not strong enough to damage adjacent tiles

**Comment by 9600bauds** [comment]
No bug here
![dreamseeker_2016-07-18_12-34-32](https://cloud.githubusercontent.com/assets/6526157/16920445/ffd1b7c2-4ce3-11e6-828b-306db4524c17.png)
50water50pot did this
You just used too little waterpot for the machine to blow up
As for noreact pills, that's what the time release pills are for, the chemmaster does not include this functionality
