### ISSUE TITLE
Supermatter crates are probably too easy to amass.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#11001]
Specially since the wage update, any antag with cargo access and an emag or just cargo and engineering access can as little as two supermatter shard crates and slam one to the other manually or with conveyor belts.

Now, an antag has all the right to blow the station up if they feel like it but a single supermatter explosion tends to cause shuttle calls faster than a couple of toxin bombs because of the EMP wave. As we currently have it 200 credits and 2 minutes waiting for the cargo shuttle is all it takes to cause this when TTV bombs from science have some sort of effort behind them and take a bit to arrange.

This is currently easier than pete bombs were.

I'm not even sure what to suggest here, make them more expensive? Have it so ordering one alerts the heads of staff somehow?

**Comment by jknpj** [comment]
Make it costs at least 500, but then again, isn't like silicons/miners/QM/ANYONE WITH ACCESS TO ORE AND SMELTER will have monetary issues.

**Comment by Intigracy** [comment]
But at least the ore smelter takes time to get the money.

Silicons already have a league of things they can abuse easier anyway, like the singularity.
