### ISSUE TITLE
Diona nymphs can't read papers even after being able to understand spoken language

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11017]
Everything shows up with asterisks obscuring most of the characters

**Comment by SkowronX** [comment]
Pretty sure this is because monkeys can't read. Try reading something after taking methylin.

**Comment by 9600bauds** [comment]
Methylin doesn't work on diona nymphs

**Comment by 9600bauds** [comment]
Dupe & fixed soon
