### ISSUE TITLE
Diona nymphs don't take extra burn damage

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11015]
Did not take extra burn damage
Healed naturally from burns (do grown diona do this?)
~~Would never ever heal from the 7 brute damage I had~~ actually caused by #11014
~~Light would not heal me~~
~~Darkness would not hurt me~~ it works, it's just incredibly stupid and basically does not work

**Comment by Exxion** [comment]
I've definitely experienced most of these, but are you sure darkness doesn't hurt?
I once carried some nymphs around in my bag for a long time and they were dead when I took them out
I guess it could have been something else,  but I can't imagine what

**Comment by clusterfack** [comment]
Darkness doesn't hurt, it starves, starving hurts them a lot.

**Comment by 9600bauds** [comment]
I stood in pitch dark maint for a long-ass time where I was literaly stuck inside of and I didn't suffer any ill effects, not even yellow hunger bar

**Comment by clusterfack** [comment]
If we're talking about nymphs though I make no guarantees that there is even any code that does the plant deficiencies though.

**Comment by 9600bauds** [comment]
I found out why they don't heal from light. I had a creeping suspicion it was this but never checked

**Comment by jknpj** [comment]
Already fixed.
