### ISSUE TITLE
AI tracking agent card duder oddity

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11010]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision c6609a726a394fddd0f2ec974c28fd1c77810b02 
> 
> General description of the issue
> If someone is wearing an agent card off-cameras, and the AI attempts to track them by coms follow, the AI will get 'follow mode terminated'
> 
> What you expected to happen
> Target is off-cameras, cannot track
> 
> What actually happened
> Follow mode terminated, agent card tell.
> 
> Steps to reproduce if possible
> As AI, try to track someone with an agent card that's hiding out in maint or something

**Comment by Shadowmech88** [comment]
This is no longer the case, now it just says the target is not near any active camera.
