### ISSUE TITLE
Still possible to get insta-fuckin-sleeped by ventcrawling as carbon (alt. title: space is not cold but almost-space is)

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11013]
Ventcrawled into a pipe with the following readings as Diona:

Pressure: 0 kPa 
 CO2: 0.5 mol, 100% 
 Temperature: -262°C 

Within 5 seconds I became completely unable to move and instantly froze to death
now I'm not quite sure here but if more mol = more heat transfer then wouldn't less mol = more less heat transfer??

**Comment by PJB3005** [comment]
@DrCelt :snowflake:

**Comment by FudgePucker** [comment]
Hypothermia was a mistake.

Also never risk going into scrubbers as a dionia because if the waste loop is optimised then it will have 100000 thermal plates on it.

**Comment by 9600bauds** [comment]
Also see: #10888

**Comment by ghost** [comment]
This has been fixed

**Comment by 9600bauds** [comment]
https://www.youtube.com/watch?v=i8DRen60X10&feature=youtu.be&t=1m12s
