### ISSUE TITLE
ghosts can use the rust

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11016]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

ghosts can click on the fuel assembly port removing the fuel and stuff

> What you expected to happen
> not happen
> 
> What actually happened

halp ghosts griffing me

> Steps to reproduce if possible

click on the fuel assembly thing of the rust while a ghost

**Comment by PJB3005** [comment]
THANKS CAEL
