### ISSUE TITLE
Blob issue and balance?

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#11026]
Played a recent round on Defficiency. The Blob storm event happened. Not only did this break lighting (AGAIN) but the blob was able to grow from parts isolated from a core. 
On top of that there where roughly 8-9 cores I could see as a ghost and they were able to freely spawn more in a very very quick succession. It makes for a great automated way to exit a long round, but the isolated pieces being able to keep spawning new pieces hurt things.
Not sure if this intentional or not, but I'd like to bring it up.

**Comment by Blithering** [comment]
Blobs being only able to expand from a blob tile if it is connected to their core would be a good thing in my opinion.

**Comment by Killette2** [comment]
Cores themselves naturally grow, it's the stations duty to patrol the outside in the case of this event to purge the biohazard.

You also have to consider that the blob is an overmind, and has always been able to work with other blobs by jumping to a friend's core in need. The fact that there may be a bit too many cores or nodes, might be an oversight.

**Comment by Blithering** [comment]
The trouble is they can expand from any single tile of blob currently. You could theoretically have a blob on the edge of the z level that can still grow on the station.

**Comment by Dizor** [comment]
Yeah thats the main problem. Kinda makes it hard to clear when the seperated blob can still spread while the Prime blob auto spreads.

**Comment by clusterfack** [comment]
Much more difficult to do than you woukd think

**Comment by DeityLink** [comment]
Honestly that's kind of a feature
