### ISSUE TITLE
Borer in slime

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11020]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision c6609a726a394fddd0f2ec974c28fd1c77810b02 
> 
> General description of the issue
> borer is kill when slime becomes adult
> 
> What you expected to happen
> get transferred to new mob
> 
> What actually happened
> i dead pls restart
> 
> Steps to reproduce if possible
> be in slime as borer while others feed it monkeys

**Comment by Ephx1** [comment]
I'm more curious as to what the fuck a borer is doing in a slime.

**Comment by AI-Is-Rogue** [comment]
Chems for eggs.

**Comment by SkowronX** [comment]
no sanity check for borers entering certain mobs?

**Comment by ihadtoregisterforthis** [comment]
There is nothing wrong with borers entering slimes, the thing here is how mob changing was handled by #7237

**Comment by Killette2** [comment]
![slime borer](https://cloud.githubusercontent.com/assets/5169310/16892650/327d547c-4ae8-11e6-9271-d0db3d30267e.png)

I've done it before, this is nothing new.

**Comment by AI-Is-Rogue** [comment]
It's not about problems entering the mob. It's about being destroyed when the slime evolves to an adult form.

**Comment by AutismSpider** [comment]
no problems going in the mob borers can go into slimes xenos and monkeys etc 

only the head any way so you can't be smart ass and give the xeno queen a hook shot and bone shield and stuff like far sight does nothing for xenos

**Comment by Intigracy** [comment]
All borers except head borers are destroyed.

When Shadowmech added multiborers he didn't change the has_brain_worms proc correctly so everything that's checking if someone has borers is currently only checking for head borers.
