### ISSUE TITLE
Cult constructs cannot use cult runes.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#11022]
#### Description of issue

As titled, in a recent round the cult was exposed very early and the entire station was being implanted and fed holy water. As one of the few remaining cultists I decided to use constructs to get numbers in the cult.
Just as I had two constructs near my teleportation rune that landed in our hideout, I found out the hard way that they were unable to use it entirely, despite counting as people when using a tear reality one. We were found and stopped soon after.
#### Difference between expected and actual behavior

I expected cultist constructs to be able to use the runes.
#### Server revision

c6609a726a394fddd0f2ec974c28fd1c77810b02 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
This is apparently intentional, but I'm not sure why
Harvesters specifically are allowed to use them, but no other constructs

**Comment by Gringonius** [comment]
Huh, that's a real shame. Really limits construct utility.
I'll still keep this issue open asking to give them that ability anyway.

**Comment by ComicIronic** [comment]
I believe it's a balance issue, especially in the way that Artificiers can heal other constructs, so you could have a Jugg sit on a Blood Boil or another type of strong rune and decimate any attackers.

**Comment by DeityLink** [comment]
They can now in Cult 3.0
@MadmanMartian
