### ISSUE TITLE
On the matter of timestop and projectiles

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#11021]
Basically, I want to know what people think should be the behavior of projectiles picked up during timestop after timestop ends.
Projectiles will definitely be able to be picked up, moved, and redirected during timestop (well, they already can be, but it's buggy)
But what should happen if the projectile leaves the timestop area/timestop wears off while someone is holding it?
Options I have thought of (but more suggestions are welcome):
1. The projectile behaves as it does now except not buggy. That would mean that it can only be picked up while it's timestopped, but can then be thrown at any time at full force.
2. The projectile becomes inert if held once no longer timestopped. It's just a useless item. Nice trophy, though.
3. The projectile escapes from your grip (or bag, etc.) and flies off once no longer timestopped.

**Comment by PJB3005** [comment]
The third, personally.

**Comment by AI-Is-Rogue** [comment]
Option three sound pretty good.

**Comment by Exxion** [comment]
In the direction it was originally traveling, or in some random direction?

**Comment by Killette2** [comment]
What if this was like Sakuya logic? The knives/bullets will freeze in place until time resumes, but cannot be picked up? so if bullets get shot at the wizard, the border of the time stop would be a barrier and the wizard still has to get out of the way before time resumes, or they can put someone else in the bullet's path then dodge them for style points.

**Comment by Shadowmech88** [comment]
I vote for option 3, and having them move in their original direction if not already thrown in another direction.

**Comment by PJB3005** [comment]
> In the direction it was originally traveling, or in some random direction?

Same direction.

**Comment by Exxion** [comment]
Well
Everyone has agreed so far except Killette
That's probably the second-easiest option to code anyway, so I can't complain

**Comment by Killette2** [comment]
If my suggestion don't count, then 2>3>1

**Comment by Exxion** [comment]
Maybe we should have a server vote or two
I don't want to write bad evil snowflake code to deal with problems holding projectiles causes, so I'm going to refactor some stuff, which will be good for reasons other than just projectiles
But it'll probably take a day or two because inventorycode was a mistake

**Comment by ConkerDev** [comment]
Picking it up, Star Platinum The World style sounds great. Then you can throw it, or something.
https://www.youtube.com/watch?v=VIyuY5muDFE
https://www.youtube.com/watch?v=8ebM1HEOt-I

Dio did the same, too
https://www.youtube.com/watch?v=kIaqZh_gGz4

**Comment by Exxion** [comment]
That was already the plan
In fact, you can do it right now if you want by using Alt+click, but it's buggy and not recommended
The question was what to do when the individual holding it exits timestop/timestop wears off

**Comment by ConkerDev** [comment]
If you have picked it up and put it on your pocket, its silly that it would continue. Maybe dragging and placing it somewhere else be allowed? Throwing?

**Comment by Shadowmech88** [comment]
> If you have picked it up and put it on your pocket, its silly that it would continue.

Why, do spacemen have bulletproof pockets now?
If it keeps the same inertia it had before being timestopped, it makes sense that it would shoot out of your pocket in the direction it was originally travelling.

**Comment by ConkerDev** [comment]
That's the thing. It feels more natural for stuff not to keep their inertia if they are picked, and will lead to more interesting situations like picking up a bullet someone fired and throwing it back, killing the shooter

**Comment by Exxion** [comment]
So you want option 1, then?

**Comment by Shadowmech88** [comment]
> and will lead to more interesting situations like picking up a bullet someone fired and throwing it back

This is possible with option 3, @ConkerDev. You just need to throw it before stopped time ends. You don't get to accumulate a backpack full of bullets and throw them whenever you want.
