### ISSUE TITLE
Biosuits do not protect from plasma

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11023]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)

> Revision c6609a726a394fddd0f2ec974c28fd1c77810b02
> 
> General description of the issue
> Tried entering a plasma environment wearing a biosuit, clothing immediately became contaminated, also recieved 'your skin burns!' messages. The biosuit seemed to do nothing to protect against it.
> 
> What you expected to happen
> Biosuit would protect against plasma.
> 
> What actually happened
> I couldn't sit on the couch in the plasmaman only bar.
> 
> Steps to reproduce if possible
> Put on a R&D biosuit (Haven't tested with other types) 
> Stand in purple.

**Comment by kol1th** [comment]
not a bug _(probably)_

**Comment by ComicIronic** [comment]
I believe biosuits are meant to protect against sliming and viruses. Are they even pressure sealed?

**Comment by SonixApache** [comment]
Supposedly they protect against plasma on other codebases.

**Comment by ConkerDev** [comment]
Plasma isn't a biotoxin on our lore, more like just pink death gas. You are supposed to use pressure suits to avoid contamination, but I'll agree that biosuits could potentially be plasmaproof. That would be too OP in my opinion, but whatever
