### ISSUE TITLE
You can take the nuclear disk on the mining shuttle after hitting "send"

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11029]
#### Description of issue

You can take the nuclear authentication disk off station to the asteroid with the mining shuttle.
#### Difference between expected and actual behavior

The shuttle doesn't move when the disk is on it.
#### Steps to reproduce this bug

Drop the nuclear authentication disk just outside the mining or research shuttle
Hit "send"
During the brief taking off sequence, grab the disk and bring it with you/throw it onto the shuttle
Watch as the disk is sent off z-level 
Completely break nuke ops
For extra "fun", leaving the disk on the shuttle will prevent being able to call it from the other side. So if you leave the desk on the mining shuttle at the asteroid side, you can't call it to the station unless you get on the asteroid through other means. 
#### Specific information for locating

shuttle.dm line 268-ish 
There's some shit about "spawn" in there which I'm afraid of touching and breaking 
#### Length of time in which bug has been known to occur

probably forever
#### Server revision

c6609a726a394fddd0f2ec974c28fd1c77810b02 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
@unid15

**Comment by ScrambledSteak** [comment]
how to meme a nuke ops round

**Comment by unid15** [comment]
My PC is somewhat fucked right now so I can't do anything, unfortunately
idk how long it will take to fix it
