### ISSUE TITLE
Surgery's freezer sprite

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11031]
I don't like that the freezer inside surgery uses the same sprite of the pizza freezer, so i made a sprite based on a organ transport cooler.
I'm not good with lights and shadows, so if you like it feel free to modify it as you prefer.

![freezer_box](https://cloud.githubusercontent.com/assets/6170726/16896863/880d8458-4ba0-11e6-9d9d-d68cc8324d0f.png)

![freezer_box_big](https://cloud.githubusercontent.com/assets/6170726/16896864/8da5047c-4ba0-11e6-9e3b-eae57aea393a.png)

another version

![freezer_box4](https://cloud.githubusercontent.com/assets/6170726/16915892/65c0b4dc-4cfa-11e6-8577-533cb4f4661a.png)

![freezer_box_big4](https://cloud.githubusercontent.com/assets/6170726/16915896/6ad5da7e-4cfa-11e6-999b-e11b7f958b3b.png)

fixed version

![fix](https://cloud.githubusercontent.com/assets/6170726/16997807/45b366e4-4eb7-11e6-9e94-25bd842123b7.png)

![fix_big](https://cloud.githubusercontent.com/assets/6170726/16997811/4a035772-4eb7-11e6-8f41-f8203df0a218.png)

source:

![stock-photo-56721416-cooler-for-human-organ](https://cloud.githubusercontent.com/assets/6170726/16895271/678536b0-4b71-11e6-8cab-746987fee4fa.jpg)
![stock-photo-60571732-cooler-for-human-organ](https://cloud.githubusercontent.com/assets/6170726/16895273/715a46ee-4b71-11e6-8cdc-f0f8b44595eb.jpg)

**Comment by PJB3005** [comment]
Definitely gonna need some better shading.

**Comment by Kurfursten** [comment]
Not only does it use the same sprite as a pizza freezer, a pizza freezer can be used to safely store organs if the clown welds your freezer apart.

**Comment by uazuaz** [comment]
tried some shading.

![freezer_box2](https://cloud.githubusercontent.com/assets/6170726/16897079/031c0d8a-4ba7-11e6-8612-07f42e9f3cf7.png)

![freezer_box_big2](https://cloud.githubusercontent.com/assets/6170726/16897081/07b44592-4ba7-11e6-8644-fc590dcfb86a.png)

**Comment by kernikov** [comment]
> has a handle
> can't pick it up

**Comment by uazuaz** [comment]
made another version, more similar to the original freezer; added also on the OP

![freezer_box4](https://cloud.githubusercontent.com/assets/6170726/16915892/65c0b4dc-4cfa-11e6-8577-533cb4f4661a.png)

![freezer_box_big4](https://cloud.githubusercontent.com/assets/6170726/16915896/6ad5da7e-4cfa-11e6-999b-e11b7f958b3b.png)

**Comment by Kurfursten** [comment]
I actually think I liked it with the handle. Looked unique.

**Comment by ConkerDev** [comment]
Its still a crate. If there is no change to make it a bag, I think the alternative version is better. It's very weird that medbay practically doesnt use the color red on its scheme. Its all blue and white.

**Comment by PJB3005** [comment]
Is it just me or is there something off with the right side of the lid on the closed sprite for the last one? It sort of looks like the lid is too big and sticking out over the right side.

**Comment by Shadowmech88** [comment]
It's not just you. It has to do with the grey outline on the mouth of the tub's right side being a pixel too low.

**Comment by uazuaz** [comment]
@PJB3005 
@Shadowmech88 
it's true, but that's just in the original freezer sprite (this, cut from the original storage.dmi file)
to obtain the alternate version i just colored the regular freezer sprite's sides.

![storage](https://cloud.githubusercontent.com/assets/6170726/16993495/fb9ce5b6-4ea3-11e6-838d-da0c4a067178.png)

i'll fix it later.

**Comment by uazuaz** [comment]
tried a fix

![fix](https://cloud.githubusercontent.com/assets/6170726/16997807/45b366e4-4eb7-11e6-9e94-25bd842123b7.png)

![fix_big](https://cloud.githubusercontent.com/assets/6170726/16997811/4a035772-4eb7-11e6-8f41-f8203df0a218.png)

**Comment by PJB3005** [comment]
Much better.
