### ISSUE TITLE
Cyborg inventory stays after module change

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11039]
(WEB REPORT BY: nmsct699 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c6609a726a394fddd0f2ec974c28fd1c77810b02

If a module reset is used on a cyborg while the module inventory is still open, and a new module is selected, the item icons from the old module still appear on screen, but the items themselves cannot be selected, only the new inventory items from the new module that appear on top of the old ones.

Highly annoying.

It should go away with reset I assume.

**Comment by kol1th** [comment]
Goes away if you relog actually.
