### ISSUE TITLE
The clickboxes for stun revolvers and assault rifles are ridiculous

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11035]
(WEB REPORT BY: miningpig REMOTE: 172.93.109.202:7777)

> Revision c6609a726a394fddd0f2ec974c28fd1c77810b02 

The click boxes for stun revolvers and assault rifles seem to take up the entire tile, forcing you to throw them into a crate and then right click>toggle open the crate if you want to close it. Why does this happen.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
$50 says it has nothing to do with the guns themselves and instead has to do with them being improperly dropped from the inventory in this case and never losing the `mouse_opacity` 2 used to make them take up the whole inventory slot

**Comment by Exxion** [comment]
There we go.
If you ever pick up a lockbox then blow it open, the items inside will have `mouse_opacity` 2 until they are placed in another storage item and removed because blowing up a lockbox just sets the `loc`s of the things in it rather than properly removing them from storage

**Comment by 9600bauds** [comment]
I wonder which guns are the most commonly made

**Comment by ScrambledSteak** [comment]
Assault rifles, stun revolvers, chem sprayers, ebows, laser cannons(?) and pneumatic cannons (???)

**Comment by Exxion** [comment]
Pneumatic cannons don't even come in lockboxes

**Comment by ScrambledSteak** [comment]
he asked for the most commonly made guns
i'd assume pneumatic cannons would be on that list either way

**Comment by 9600bauds** [comment]
I was being sarcastic that this problem would happen with all lockbox items but the report specifically mentions ARs and stun revolvers :^)
