### ISSUE TITLE
Mindswap causes split spell list and problems for the wizard

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#11046]
Having mindswapped with an officer I found my spells constantly going on cooldown, allegedly, due to the officer now in my body constantly casting them. Moreover, he could cast the spells while dead, using this he kept me subjugated throughout the round, with the effect transferring to not just me, but to all who I mindtransferred into, resulting in a drunken station and a thorough mess of a round.

**Comment by 9600bauds** [comment]
Should be fixed now
