### ISSUE TITLE
Firebirds can fly right through welded airlocks

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11049]
Doesn't even open the firelock in the process, it just noclips through. Provided you have access to open the airlock, that is.

**Comment by Exxion** [comment]
What about unpowered ones?

**Comment by Intigracy** [comment]
Firebirds are supposed to fly through airlocks reeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by 9600bauds** [comment]
Well then in that case, the bug is that they can't fly through airlocks you don't have access to

**Comment by Exxion** [comment]
They are just supposed to fly through airlocks you can open
It's so you don't have to wait for them to finish opening
If memory serves, it actually says that in comments in the operative code
But apparently someone didn't think of welding

Also, they can't fly through airlocks that are actively opening
Only ones that are closed that they can open

**Comment by 9600bauds** [comment]
I have no fucking idea what they are SUPPOSED to do but I'm pretty sure not this

**Comment by Exxion** [comment]
You can look in the Firebird code
It explains it in the comments
But you're right, they shouldn't fly through  welded doors

**Comment by 9600bauds** [comment]
What if wizard firebirds could noclip through any airlocks?
That'd be fun

**Comment by Intigracy** [comment]
They used to noclip through everything, but it was seen as really OP and got nerfed.

It was SUPPOSED to be that you can move through airlocks and other shit, just not walls, with the original nerf. That didn't happen.

Deity later added the ability to go through airlocks before they open,, but only if you have access (which is pants on head retarded).

**Comment by jknpj** [comment]
@Intigracy you can go through bolted airlocks that you don't have access to. #10417 You can get inside the station's vault, AI upload, cheese the syndie vault, ignore cycling airlocks and the list goes on.

**Comment by ConkerDev** [comment]
What's the point of the Firebird if you can only noclip through airlocks you can open?

**Comment by Exxion** [comment]
The point of noclipping through the firelocks is so you don't have to wait for them to open, so you can go faster down long hallways than anything else

**Comment by Intigracy** [comment]
yeah but it's supposed to be a magical ride

**Comment by Exxion** [comment]
I'm just saying what it's currently intended to do
What it SHOULD do is a different matter, and one I care substantially less about
