### ISSUE TITLE
lisa the female corgi cant wear stuff on his back

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11043]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> cant put a radio on her back slot
> 
> What you expected to happen
> being able to put stuff
> 
> What actually happened
> Lisa already has a cute bow! message
> 
> Steps to reproduce if possible

try put a radio on her back slot

**Comment by kol1th** [comment]
> Lisa already has a cute bow! 

not 
a 
bug

**Comment by pvak** [comment]
it gives the same message for head and back

**Comment by ihadtoregisterforthis** [comment]
> the female corgi
> his back
