### ISSUE TITLE
Plastic Crates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11041]
(WEB REPORT BY: charmstruck REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c6609a726a394fddd0f2ec974c28fd1c77810b02 
> 
> General description of the issue
> Disassembling a crate made with 10 plastic sheets yields 2 metal sheets
> 
> What you expected to happen
> I expected to get plastic sheets
> 
> What actually happened
> I got metal sheets
> 
> Steps to reproduce if possible
> Obtain 10 plastic sheets
> Construct plastic crate
> disassemble the open crate with a welding tool
> Obtain metal?

**Comment by ihadtoregisterforthis** [comment]
What? Again?

https://github.com/d3athrow/vgstation13/commit/39c7ce3c6aee7d186cb702981a9bbe14d978f461

**Comment by PJB3005** [comment]
I don't actually think that ever fixed that. It might have fixed recycling them but not disassembling them with a welder.

**Comment by Hikato** [comment]
Should be fixed in #11067
