### ISSUE TITLE
Pork Tenderloin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11050]
(WEB REPORT BY: charmstruck REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 20e8385cf18921c12e1b48770f334422bc9ddc20 
> 
> General description of the issue
> Pork tenderloin has the Zhu Lóng Cao Fàn sprite
> 
> What you expected to happen
> I expected it to look like the sprite on the wiki, or at least not look like a pitcher plant, as it is not used in the recipe
> 
> What actually happened
> Looks like Zhu Lóng Cao Fàn
> 
> Steps to reproduce if possible
> 10 units Gravy and 1 Box Meat in microwave

**Comment by Kurfursten** [comment]
Thanks for the report
