### ISSUE TITLE
Goon Lighting On Shrooms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11059]
(WEB REPORT BY: blarghargin123 REMOTE: 172.93.109.202:7777)

> Revision a9dda576764b5dabf32c3e3fa1a1d91cbb30cf90
> 
> General description of the issue
> http://i.imgur.com/0IQPIDy.png
> 
> What you expected to happen
> not http://i.imgur.com/0IQPIDy.png
> 
> What actually happened
> Got http://i.imgur.com/0IQPIDy.png
> 
> Steps to reproduce if possible
> Dont know, but this is my BYOND Version
> http://i.imgur.com/bLKmWYW.png

**Comment by PJB3005** [comment]
Check your GPU drivers or something. This is not something we can fix. BYOND isnt rendering colour matrices. http://www.byond.com/forum/?forum=4
