### ISSUE TITLE
(Girlname) tips his fedora.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11077]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7767f1234b8ea9736b7edeebe4178cf28599aec4
> 
> General description of the issue
> When tipping their fedoras, female characters show the emote for male fedoratippers.
> 
> What you expected to happen
> Assista McGreyshirt tips her fedora.
> 
> What actually happened
> Assista McGreyshirt tips his fedora.
> 
> Steps to reproduce if possible
> Be girl, tip fedora.

**Comment by AutismSpider** [comment]
happens when mommis tip it.

call his not it

**Comment by Exxion** [comment]
A one-keystroke fix
Six if someone did something silly
