### ISSUE TITLE
Air Tanks at 0ºC

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11085]
(WEB REPORT BY: zalo1302 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2e470598b259fb4d1576c1b9f99068ace1139f54 
> 
> General description of the issue
> Air Tanks that are around station in maint. spawn at 0ºC instead of 20ºC.
> 
> What you expected to happen
> Air Tanks at 20ºC
> 
> What actually happened
> Air Tanks at 0ºC
> 
> Steps to reproduce if possible
> Just find one in maint.

**Comment by 9600bauds** [comment]
It's so that there's more air in there

**Comment by nervere** [comment]
Probably not an issue anymore unless this was on a specific map, but not enough info to tell. In any case, everything on Box is fine. Testing done by @Inorien - thanks!
