### ISSUE TITLE
ChemMaster 3000 Pill types

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#11088]
#### Description of issue

I believe color coding pills, at least for bicaridine, kelo/derma, antitoxin, and dex/dplus to be effective, but when I talked to others about it, they won't, literally because it takes two extra clicks.
#### Difference between expected and actual behavior

They seemed lazy but I expected logic to win through since it makes sense but
#### Steps to reproduce

Understand that color-coding pills is fairly simple when you think like, a bicaridine pill heals brute, brute is red colored text when you scan someone, so if someone puts all the different types in one bottle for their pocket, it's easy to differentiate between the pills. Once you understand this, explain it to a powergamer. They will freak out and call it retarded and slow because it takes two extra clicks per pill-type.
#### Specific information for locating

Reeeeeeeeeeeeee agents- wait, no, chemmasters.
#### Length of time in which bug has been known to occur

Time immemorial
#### Server revision

N-now.

---

Instead of a separate menu for pill types, can we just have all the different sprites listed across the interface like:

---

THIS IS UR BEAKER

THIS IS THE CHEMS IN THE MACHINE

[PILL] [PILL] [PILL] [PILL] [PILL] [PILL] [PILL]

**Comment by 9600bauds** [comment]
I was going to do this but got lazy.

**Comment by nuklearcellphoneg** [comment]
Your being lazy has led to many chemists also being lazy.

**Comment by 9600bauds** [comment]
They would have been lazy without my help anyways.

**Comment by nuklearcellphoneg** [comment]
Yes but with your help it would be one click instead of two

And that's half the clicks

A 50% decrease

**Comment by nuklearcellphoneg** [comment]
It wouldn't even be clicks then, it would be click, one letter less. Over time that really builds up in terms of explaining.

**Comment by SonixApache** [comment]
Can we just autocolor pills like what happens with the liquids

**Comment by nuklearcellphoneg** [comment]
I'm not sure what happened but A) most liquids are just... pinkish now and so B) you wouldn't be able to make fake pills for antagging. You would have healing reagents, then you'd have like carbon, mindbreaker, chloral and iirc polyacid for pill colors. Oh and unstable mutagen.

**Comment by Hikato** [comment]
Or you could hax the console to allow selection of colors, otherwise it auto colors based on the liquid.

Can you put two liquids in one pill though?

**Comment by Kurfursten** [comment]
@hikato Or even just autocolor but leave the option even without hacking

And yes

**Comment by 9600bauds** [comment]
I feel like we're stripping something out of the game by handholding hard enough to autocolor

**Comment by charmstruck** [comment]
I see nothing wrong with autocoloring with the option to manually color pills

**Comment by nuklearcellphoneg** [comment]
I-I really think autocoloring is a bad idea which will lead to more issues down the road, I just want the pill sprites listed out instead of in a separate menu.

**Comment by kol1th** [comment]
> automating something that is already brain dead easy

Stop this

**Comment by 9600bauds** [comment]
I sure would miss the heated autismal arguments about pill colors

**Comment by nuklearcellphoneg** [comment]
Chemist needs to be able to sabotage medicine without hacking- I just want the separate menu to be a part of one whole menu. Arguably easier I'd assume and not controversial and it wouldn't dumb down an already fairly straight forward job.
