### ISSUE TITLE
The baster can dupe chems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11086]
(WEB REPORT BY: gutlesscoward REMOTE: 172.93.109.202:7777)

> Revision 2e470598b259fb4d1576c1b9f99068ace1139f54 
> General description of the issue
> you can remove/add chemicals to people via the baster; if you keep removing and adding a chemical from a person fast enough with the baster, you can end up with more chemicals than you initially put in.
> 
> What you expected to happen
> I expected to end up with the same amount (or less, due to metabolism) amount of chemicals
> What actually happened
> I was able to  take out more of a chemical from myself than I had put in
> 
> Steps to reproduce if possible
> 1. Get Baster
> 2. Fill it with some chemical
> 3. click rapidly on a human to transfer the chemical, take it out of them, and squit it back in them. make sure the human isn't wearing eye protection. there will be no message for removing the chemical from the human
> 4. if done correctly, you will be putting more into the human than you are taking out. it's easily noticable if you only put in 1 unit of something into a human, because the transfer message will show that, as you're clicking on the human, you're putting in more and more chemical. you could also check via an advanced mass-spectrometer.

additionally, you can remove the reagents from the human with the baster and put them into beakers for later use.

**Comment by Exxion** [comment]
Hold on
You can just
Remove chems from people
With a baster?

**Comment by Gutlesscoward** [comment]
yeah, just click on the person with it. it won't return a message or anything, but the baster will take the chem. I'm not sure how consistent it is though; I remember having to click like 4 times to have the baster take the chems from someone.

**Comment by Gutlesscoward** [comment]
ADDENDUM: it seems you can remove chems from yourself with any dropper, not just a baster. the glitch may work there as well, though it may be more difficult since the maximum amount you can transfer with a dropper is 5 as opposed to 15 with a baster.

**Comment by nuklearcellphoneg** [comment]
Humans are actually very large beakers full of blood

**Comment by FudgePucker** [comment]
Holy shit this is amazing and the removing chems shouldnt be removed.

YOU CAN FARM NUTRIENT FROM DIONIAS

**Comment by ghost** [comment]
I'm not sure why this hasn't been fixed yet, or really reported. I've seen it used and abused many, many times.
