### ISSUE TITLE
Replace Ling with Ling+Autotator

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11097]
This would immediately improve the gamemode
Prove me wrong

**Comment by AutismSpider** [comment]
only way to improve it is to take it out like ninja same with vamp

**Comment by jknpj** [comment]
But why? We already have ling+tator. Might as well remove it as @AutismSpider said.

**Comment by kernikov** [comment]
REMOVE HEIST
REMOVE VOX
NOTHING IS WORSE THAN RAIDERS

**Comment by 9600bauds** [comment]
We do already have Ling+Tator and from my own experience it is strictly superior to pure Ling
I think Ling+Autotator would be even better

**Comment by kol1th** [comment]
Just remove every antag and have every round be sandbox.

**Comment by Intigracy** [comment]
my only complaint about traitorchan is that it ONLY spawns one changeling, regardless of pop.

**Comment by icantthinkofanameritenow** [comment]
@Intigracy

Agreed. It should at least spawn two, possibly more depending on population.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is dead 3 ways from sunday
