### ISSUE TITLE
Simple-animal mob logging

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#11093]
Simple-animal mobs are not logged, which can lead to abuse. 

An example is if I spawn this:

spawned /mob/living/simple_animal/hostile/giant_spider

Then do this

[21:11:27]ADMIN: nuklear/(fly) stuffed nuklear into giant spider.

Then put my ckey in it, I can kill whoever and it won't be logged.

**Comment by nuklearcellphoneg** [comment]
So...

**Comment by ComicIronic** [comment]
Simple animal attacks look logged everywhere in the code to me.

**Comment by nuklearcellphoneg** [comment]
Okay, I'm going to look something up. Is it just logged under attack logs like everything else?

**Comment by kol1th** [comment]
Apparently it's logged in the mob's attack log in VV, but not the attack logs themselves. @ComicIronic
