### ISSUE TITLE
Particle Accelerator's display doesn't change numbers when adjusted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11098]
(WEB REPORT BY: justsumguy REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> feac920487ed604e23e413c289f04239d1a5fe2b 
> 
> General description of the issue
> The sprite for the particle accelerator is stuck on 1 even when the strength is adjusted
> 
> What you expected to happen
> 0, 1 , 2 , 3
> 
> What actually happened
> 1,1,1,?(probably 1)
> 
> Steps to reproduce if possible
> Change the PA's strength
> Notice the display never changes off 1
> Yes this is a thing
> see particle_control.dm Line 73 I think

**Comment by clusterfack** [comment]
Theres a number on it ?!

**Comment by Intigracy** [comment]
Yeah the computer sprite has a number on the top right corner.

**Comment by clusterfack** [comment]
The secret powergaming tips are real

**Comment by Intigracy** [comment]
It may actually just be a 0 when off and a 1 when on, now that I think about it.
