### ISSUE TITLE
the pirate shit in metaclub has no light fixtures

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11101]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

no lights

> What you expected to happen
> lights
> 
> What actually happened
> no lights
> 
> Steps to reproduce if possible

go in the pirate ship and find no lights

**Comment by SkowronX** [comment]
Pirate "shit". Unsure if intended or Freudian slip.

**Comment by PJB3005** [comment]
T is halfway across a QWERTY keyboard from P, doubt it.

**Comment by SkowronX** [comment]
Coulda been muscle memory, but wuteva!
