### ISSUE TITLE
How to entirely fix bomberman

### ISSUE THREAD

**Issue by Sprok0** [d3athrow/vgstation13#11106]
Make the bomb dispenser superglued to one hand
Delete the other hand
Give bombermen noslowdown magboots

**Comment by Exxion** [comment]
Stealing other players' BBDs was apparently decided to be a feature
The magboots aren't a bad idea though

**Comment by Sprok0** [comment]
The problem was more during a full station bomberman round, with people using guns and stun batons

**Comment by ihadtoregisterforthis** [comment]
Bomberman mode is not supposed to be fair to everyone. It's not terrorist highlander, it's kill the others and survive by any means, with bombs. Slipping and disarming for the bomb dispenser is expected, making toxin bombs is encouraged, and ZAS is set to hellish most of the time on purpose.
Bomberman is not "broken", there is nothing to "fix".

Changes to stuns during this mode would be good but being able to keep the dispenser is even in the results at the end of the round.

**Comment by SonixApache** [comment]
Weird, I've been gibbed by admins for pushing people down to take their BBD.

**Comment by Exxion** [comment]
DEADMIN
You are allowed to do that

I personally think it's kind of silly that you can do it, but I got shut down when I said that when Bomberman was introduced
