### ISSUE TITLE
IV drip suggestion

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11104]
IV drips have a couple of issues; they are hard to click because their sprite is thin, and they don't show if they're injecting or taking blood.

the sprite could be improved, for example like this

![iv_drip](https://cloud.githubusercontent.com/assets/6170726/17068474/730cb2ee-5051-11e6-9ece-05b3e8235825.png)

![iv_drip_big](https://cloud.githubusercontent.com/assets/6170726/17068509/a2dbeb0c-5051-11e6-86c3-6e37a815e3fe.png)
- bigger sprite, easier to click
- they show if injecting (green +) or taking blood (red -)

note: the transparent "triangle" on the higher part of the sprite could be also considered as part of the sprite if possible, so it's even easier to click it.

**Comment by charmstruck** [comment]
This seems like it would be a good change

**Comment by 9600bauds** [comment]
I think Goon has nice sprites for these

**Comment by DamianX** [comment]
Fixed by #15075
