### ISSUE TITLE
withoit oxigen laser dont illuminate??

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11108]
![2016-07-22_21-12-28](https://cloud.githubusercontent.com/assets/6526157/17074345/00739978-5051-11e6-8d0b-dbc9ff32c9c6.gif)

**Comment by SysadminJeroen** [comment]
How long has this been happening?

**Comment by Exxion** [comment]
Probably since Parallax was either added or fixed to not use `SEE_PIXELS`

It's neat that a bug would cause realism like that

**Comment by clusterfack** [comment]
I'm not really sure what I'm seeing

**Comment by SysadminJeroen** [comment]
@clusterfack That is the point, you don't see it.
You can't see lasers on space tiles which you previously could.

**Comment by SysadminJeroen** [comment]
Since I hate myself, I'll start bisecting this issue.

**Comment by clusterfack** [comment]
Either #10858 or #10499 most likely

**Comment by SysadminJeroen** [comment]
778f64fcb19aa9845fa123de92002a95acaf7ba6 is the first bad commit.

**Comment by ghost** [comment]
this has since been fixed @9600bauds

**Comment by Exxion** [comment]
In your PR, right?
lrn2autoclose

**Comment by ghost** [comment]
@Exxion I didn't know there was a report about it
