### ISSUE TITLE
there is only one spade in hydroponics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11103]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> feac920487ed604e23e413c289f04239d1a5fe2b 
> 
> General description of the issue
> there is only a single spade in hydroponics, and tough luck if it gets lost or stolen.
> 
> What you expected to happen
> I expected there to be a spare spade in each botanist locker
> 
> What actually happened
> the only spade in all of hydroponics in the crate, which isn't ID locked, so any butthead can just steal such a high risk item easily.
> 
> Steps to reproduce if possible
> be botanist, look for spades.

**Comment by ScrambledSteak** [comment]
fun fact
you can make them in an autolathe

**Comment by PJB3005** [comment]
WHAT MAP

**Comment by ghost** [comment]
Judging by the logs and asking the player, it's regarding the botany on defficiency

**Comment by Exxion** [comment]
If they're not in the lockers, it's probably every map

**Comment by Kurfursten** [comment]
@Aurantiaco When will we add mini hoes to the autolathe?

They've needed to be an autolathe item for all time.

**Comment by PJB3005** [comment]
Definitely isn't an issue on Box.
