### ISSUE TITLE
Bomberman Rounds are Fukt: Pt1

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11105]
(WEB REPORT BY: aurx REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c0c03a45f16b91f45580fdec4051575fa1911156
> 
> General description of the issue
> The "Make everyone a bomberman" button does not provide magboots.  Bustatime is rolling in his grave with laughter.  
> 
> What you expected to happen
> ZAS not to be the main cause of bomberdeaths.  
> 
> What actually happened
> Air op pls nerf.  
> 
> Steps to reproduce if possible
> Make people bombermen, cause airflow, profit.

**Comment by DeityLink** [comment]
I think that's hilarious and that everyone will agree. I often talk about balance and such but bomberman rounds are meant to be wacky and interfere with spess mechanics.
