### ISSUE TITLE
Windows in Wild West away mission can be walked through

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11102]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> feac920487ed604e23e413c289f04239d1a5fe2b
> 
> General description of the issue
> The various fulltile reinforced windows in the first section of the wild west away mission don't block people from walking through them, but they do block the syndicate mobs
> 
> What you expected to happen
> Windows to need to be smashed through by the crew
> 
> What actually happened
> They just walk through
> 
> Steps to reproduce if possible
> Load up wild west away mission, walk through a window

**Comment by ghost** [comment]
That's a feature

What isn't, however, is that the previously invisible blockers that were supposed to stop you from mining the starting area out, are now visible. Same problem with the thunderdome currently

@DrCelt PLANES
![west fat camp echo 2016-07-22 150441](https://cloud.githubusercontent.com/assets/9110500/17059553/b1008960-501d-11e6-99cc-b58a7f43cb6b.png)

**Comment by clusterfack** [comment]
Just set them to a blank icon state if theyre supposed to be invisible?

**Comment by Intigracy** [comment]
Planes are still fucked though.

Before they were just layered below turfs since oldcode.

**Comment by Exxion** [comment]
But if they're never supposed to be visible, why give them an `icon_state`?

**Comment by PJB3005** [comment]
Mapping.

Obligatory http://www.byond.com/forum/?post=2106042&first_unread=1

**Comment by Exxion** [comment]
That's a good point

Can't we just set their invisibility to 101 or something?

**Comment by PJB3005** [comment]
Oldcoders are dumb.

**Comment by ghost** [comment]
The blocker thing is already resolved by #10885 and just needs merging now

**Comment by ghost** [comment]
this is fixed
