### ISSUE TITLE
Bomberman Rounds are Fukt: Pt2

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11107]
(WEB REPORT BY: aurx REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c0c03a45f16b91f45580fdec4051575fa1911156
> 
> General description of the issue
> Firelocks ignore bombermanbombs.  
> 
> What you expected to happen
> Firelocks to blow the fuck up.  
> 
> What actually happened
> Firelocks did not in fact blow the fuck up.  
> 
> Steps to reproduce if possible
> Make a bomberman, hit the "Make Bomberman Bombs actually destroy stuff" button, drop the locks and a bomb.  Watch as nothing happens.

**Comment by DeityLink** [comment]
They're called "firelocks" , makes sense to me. Have admins mass delete firelocks if that's an issue.
