### ISSUE TITLE
Circuit Imprinter refuses Silver, despite having Silver-requiring recipes.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11112]
(WEB REPORT BY: morena REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c0c03a45f16b91f45580fdec4051575fa1911156 
> 
> General description of the issue
> The circuit imprinter cannot store silver, despite having a reciepe which requires silver to craft.
> 
> What you expected to happen
> The circuit imprinter took the silver I was offering to feed it, allowing me to print the experiment shield capacitor.
> 
> What actually happened
> The damn thing shot a message at me saying it can't take the silver.
> 
> Steps to reproduce if possible
> hold silver in your hand
> click the circuit imprinter
> tada.

**Comment by AutismSpider** [comment]
its a recipe that needs to be move or taken out.

When you make shield gen it does not make a board it shits out a full gen like magic!

not only that gen bolted to the damn floor

**Comment by ghost** [comment]
it's still a bug, and yeah the stuff comes out bolted to the floor. But there's no other way to get the item except when they are round-start on box only. It's a cool thing, we should be able to make it somehow.
