### ISSUE TITLE
Game crashing while trying to set access on airlocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11113]
(WEB REPORT BY: gef21 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c0c03a45f16b91f45580fdec4051575fa1911156
> 
> General description of the issue
> I tried to set access on an airlock using the RCD and my game crashed, tried it again and the same thing happened
> 
> What you expected to happen
> I would set access
> 
> What actually happened
> My game crashed
> 
> Steps to reproduce if possible
> Use an RCD to set access

**Comment by ComicIronic** [comment]
What's the Byond version?

**Comment by PJB3005** [comment]
Great it's that network error.

Nothing we can do about this, go to the BYOND forums.

**Comment by clusterfack** [comment]
Are we sure whether or not he meant 'client crashed' or 'GAME crashed' as he says? The distinction is **rather** important.

**Comment by PJB3005** [comment]
I assume if it was an actual server side crash we'd know and it'd be more obvious.
