### ISSUE TITLE
Vampire rejuvenate doesnt flush out chloral

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11111]
(WEB REPORT BY: vikenz REMOTE: 172.93.109.202:7777)
Revision: c0c03a45f16b91f45580fdec4051575fa1911156

Rejuvenate didnt work on a bunch of shit the cmo injected me with

> What you expected to happen
> To assblast the CMO
> 
> What actually happened
> A billion units of chloral and some other shit stayed in my body

Trialmin JustSumGuy replicated it and rejuvenate didnt work for him either

**Comment by 9600bauds** [comment]
and good riddance

**Comment by JustSumBody** [comment]
To add to this, the tooltip for it states that it does "cleanse the system"(which seems to imply removing chems) while the wiki makes no mention of it.
I have no idea what the intended behavior is

**Comment by Killette2** [comment]
Witnessed your quads
