### ISSUE TITLE
Highlight string function is displaying the span tags in text

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11115]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/19365096/17079919/872b46f0-50ec-11e6-94b7-97aba495f692.png)
#### Difference between expected and actual behavior

I should be seeing those things with tags as highlighted
#### Steps to reproduce

Set your chat to highlight the words "AI," "door," "borg," "law," and "open," to make up for your horrible attention span
Play silicon
Go insane
#### Specific information for locating

I dunno, seems to happen for any word I've tried
#### Length of time in which bug has been known to occur

Didn't happen at all this morning(4AM-ish), started happening now. Supposedly for other people this has always happened? ("Yeah that's still broken")
#### Server revision

1be8cec8a3bca7e1c9a02f952e4af8f1b80e127a 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ComicIronic** [comment]
May have been caused by #11006

**Comment by PJB3005** [comment]
Oh for fucks sake.

So the issue is, and I have no fucking idea how to fix this anymore, that the API to get the text in a node returns < and such where there's a `&lt;`.
