### ISSUE TITLE
Camera Bugs tell people that they were hit with them when planted

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11127]
#### Description of issue

I used the camera bugs after messing around with buying random stuff and wanted to plant it on random people. Turns out they arent silently placed anymore and show others that they were hit with the camera bug when planted, making one of its main uses almost useless.
#### Difference between expected and actual behavior

Expected: It would silently slap the camera on the person, like it did before and like it does on normal objects
Actual Behavior: Made me drop spaghetti by showing an attack log in the chat, and that I have 'silently' planted it on the person. A cargo tech saw me and called me out.
![screenshot_76](https://cloud.githubusercontent.com/assets/17911005/17084428/79435e02-51bd-11e6-9bf8-27d5d57f36ca.png)
#### Steps to reproduce

Use the camera bug after setting the camera ID and put it on yourself/someone
#### Server revision

6b1d689a970962b2dd5e5e8f6e63cb4cdacfff45 Current Infomational Settings: 
Protect Authority Roles From Tratior: 1
#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
Nah man you're in the clean. It clearly says you did it stealthily.

**Comment by 9600bauds** [comment]
Either a missing return, or needs NOBLUDGEON

**Comment by Wizardcrying** [comment]
![return](https://cloud.githubusercontent.com/assets/6970188/17114927/e63f7de4-5265-11e6-803d-0ddfe28d9537.png)
@9600bauds The latter?
_edit_: **BUT WAIT**
![dreammaker_2016-07-25_19-49-22](https://cloud.githubusercontent.com/assets/6970188/17115000/4787f388-5266-11e6-934c-2925900d705d.png)

**Comment by 9600bauds** [comment]
Uhhhhhh
try making that return 0?

**Comment by Wizardcrying** [comment]
nope, return 0 does nothing @9600bauds

**Comment by Venseer** [comment]
I think I know how to fix this. I managed to do it on another item I was working on that was based on camera bugs. I can open a pull request later today or tomorrow after testing it properly but all I did was this:

```
/obj/item/device/camera_bug/attack(mob/M as mob, mob/user as mob, def_zone)
  return
```

It should work, but I'd rather test first before opening the PR.

**Comment by ComicIronic** [comment]
That would be a bad solution, we should really be looking at why NOBLUDGEON isn't working for suppressing messages.

**Comment by unid15** [comment]
NOBLUDGEON only suppresses messages that happen when you hit structures with the item - not mobs or anything else

**Comment by ComicIronic** [comment]
Then it should be extended to mobs, probably.
