### ISSUE TITLE
Message for silicon bolt/unbolt is inverted.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11129]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision 6b1d689a970962b2dd5e5e8f6e63cb4cdacfff45 
> 
> General description of the issue
> Title
> 
> What you expected to happen
> Bolt and get 'airlock is bolted', unbolt and get 'airlock is unbolted'.
> 
> What actually happened
> Opposite. Might also be flipped for shocking but I didn't check.
> 
> Steps to reproduce if possible
> Bolt or unbolt an airlock as a silicon.

**Comment by 9600bauds** [comment]
This was fixed by  #11126 I think, does it still happen?

**Comment by Allspice** [comment]
It's fixed now actually, thanks.
