### ISSUE TITLE
Feature Request: Health Triggers and Suicide Vests

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11128]
Ok here's an idea. 
Screwdriver to a health analyser, multitool on it. Now it works as a trigger for bombs. The multitool is to set a health % for it to trigger, between 0% and 100%. Now you can attach an igniter, secure the assembly and chuck it into a grenade, TTV, whatever. Now, if you die, you blow up! or polyacid smoke, whatever you wanna do.

And. And. Any sort of armor vest. Some sort of way to attach grenades or c4 to it and, depending on your trigger mechanism (Maybe secured to the vest, so the grenade assembly isn't needed so C4 will work too, unsure. Help me out here.) So you can run in looking like a real terrorist and blow people up. Would make muslim gimmicks a little more, fun, maybe.

**Comment by 9600bauds** [comment]
I believe this was a thing at some point long ago, but it was removed because it was shit and a nightmare to investigate whodunnit (e.g. oh but I totally didn't know he had that health sensor! HONK)
The functionality of the vest practically already exists with 55bombs

**Comment by MusgardTiger** [comment]
yes god wills it and it must be done.

**Comment by Exxion** [comment]
Bad and shitty memes aside, this would kind of be a cool feature

**Comment by ComicIronic** [comment]
> make muslim gimmicks more fun

Get out

**Comment by Killette2** [comment]
Wasn't this a thing and declared a horrible idea?

**Comment by BestName** [comment]
Used to be a thing but was "temporarily" removed a couple of years ago.

Edit: Found it e98a7893fa5567b23d28da114533c92bb598f456
