### ISSUE TITLE
MoMMI's can't take Vtech or Jetpack upgrade

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#11122]
Why was this taken out?

They could use the board to get speed boost and for a jetpack

**Comment by kol1th** [comment]
The jetpack module is only supposed to work on mining cyborgs. And the VTEC is only meant to work on cyborgs.

However I don't remember anything taking this out recently.

**Comment by AutismSpider** [comment]
some one touch it.

before it would work on the mommi and say its only for NT Cyborgs only,

Now it out right tells you this.

The mining robot jetpack will not fit into the mobile mmi robot module!

**Comment by kol1th** [comment]
It was a bug that it worked in the first place.

**Comment by AutismSpider** [comment]
Bug that should of never been fix i say.

**Comment by clusterfack** [comment]
@DrCelt You told me you tested this shit, I asked you very clearly whether you made the vtech and jetpack upgrade continue to work for mommis and you told me it did.

**Comment by Faptastic** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/silicon/mommi/mommi_movement.dm#L5
Could imply it's a feature to use jetpacks or simply foresight, either way someone bothered to write this out.
1-2 days ago i noticed I couldn't use the jetpack anymore but the vtech did go in. This was on the test server.
There is the issue of the actual board itself sticking inside your hand/module slot but it's merely a cosmetic annoyance, you could delete it with admin flags for example no problem. Can't recall if the vtech also did that but I assume so.

**Comment by AutismSpider** [comment]
The over land is just pointless cosmetic to show that you have the upgrade.

happens with both cyborgs and mommis see the board in the module slot etc.
