### ISSUE TITLE
Turrets do not target mechs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11136]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4fb6a0e943eef40b29944088c8c8e88346dd4616 
> 
> General description of the issue
> Turrets, even when set to lethal, will not target mechs
> 
> What you expected to happen
> Ripley with nothing but a drill to be lasered apart
> 
> What actually happened
> Turrets ignore it, ded AI
> 
> Steps to reproduce if possible
> Have someone in a mech go into the upload or core, set turrets to kill

**Comment by Killette2** [comment]
This ancient bug still exist?

**Comment by Intigracy** [comment]
maybe I'll fix this soon who knows what will happen

**Comment by clusterfack** [comment]
Isnt this fixed with the forcemove change? Surely

**Comment by ghost** [comment]
It is not. Can reproduce.
