### ISSUE TITLE
wooder barricade description is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11130]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> it says :
> A barricade made out of wood planks, it is very likely going to be a tough nut to crack

It's in perfect shape, not even a scratch.

It's in perfect shape, not even a scratch.

> What you expected to happen
> to say :
> A barricade made out of wood planks, it is very likely going to be a tough nut to crack

It's in perfect shape, not even a scratch.

> What actually happened

it says "It's in perfect shape, not even a scratch." 2 times

> Steps to reproduce if possible
> examinate a wooden barricade

**Comment by PJB3005** [comment]
@dylanstrategie
