### ISSUE TITLE
Filled MMIs are immune to supermatter

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11133]
(WEB REPORT BY: aurx REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4fb6a0e943eef40b29944088c8c8e88346dd4616
> 
> General description of the issue
> A MMI with a brain in it that hits supermatter will flash into ash but not vanish.
> 
> What you expected to happen
> Them to go the way of all mortal matter.  
> 
> What actually happened
> It stayed around.  
> 
> Steps to reproduce if possible
> Saw this when the derelict MoMMIs had rigged a mass driver pointing into supermatter to autofire and committed suicide by supermatter.  

Runtime logs look clean of anything related to this.

**Comment by jknpj** [comment]
The autism juice inside a mommi's brain makes the MMI denser than supermatter. It's a feature!

**Comment by AutismSpider** [comment]
mommi brains are denser supermatter
