### ISSUE TITLE
VTEC's method of speed increase is outdated

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#11138]
The VTEC initially is supposed to set a cyborg's speed to a lower value.

For example, if a cyborg has speed = 0, then a vtec would set speed = -1.
The issue here is that most borgs have speed set equal to 0 and setting speed lower than 0 doesn't make the cyborg move faster. 

What DOES increase the cyborg's speed is "movement_speed_modifier". I've found that adding +0.5 to this value provides a solid speed increase to the cyborg. That being said, VTEC's method of increasing speed should adjust "movement_speed_modifier" and not "speed".

As a side note, resetting a borg should reset the "movement_speed_modifier" back to its original value.

**Comment by charmstruck** [comment]
> As a side note, resetting a borg should reset the "movement_speed_modifier" back to its original value.

If that's the case, would it be impossible to re-install the VTEC module?

**Comment by SkowronX** [comment]
No. Reset modules remove the upgrade added by vtec in the first place.

**Comment by AutismSpider** [comment]
reset modules takes off the upgrades on the borg.
