### ISSUE TITLE
Agent IDs don't have the "Traveler" appearance available

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11134]
(WEB REPORT BY: wizardcrying REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision 4fb6a0e943eef40b29944088c8c8e88346dd4616 
> 
> General description of the issue
> The agent ID from the Syndicate Uplink doesn't allow you to change its appearance to that of a "Traveler" ID card.
> 
> What you expected to happen
> To have my Agent ID appear to be a Traveler's ID.
> 
> What actually happened
> There was no option to.
> 
> Steps to reproduce if possible
> 1. Buy Agent ID
> 2. Opt to "Edit" it.
> 3. Select "Appearance".
> 4. Try to find the option and fail.

**Comment by Durgen** [comment]
i always assumed this was intentional to reduce lynchings of legitimate traders
