### ISSUE TITLE
Defficiency's Medbay firelocks make it impossible to use the mancrowave from cryo

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11135]
![image](https://cloud.githubusercontent.com/assets/19365096/17088455/2086cb24-51e9-11e6-9d7e-4b7a0d5455f7.png)
Pop someone out of cryo
Attempt to put them in the mancrowave from the cryo side of the firelocks
Realize you can't without going around and opening the firelocks that seal off cryo from the rest of medbay
Get mad

**Comment by Exxion** [comment]
That's more of an issue with the placement of the freezer or mancrowave itself

**Comment by Kurfursten** [comment]
We shouldn't forget about this

It didn't even get labeled, what do we even have collaborators for?
@gbasood 
@9600bauds 
@ComicIronic 
@clusterfack 
@PJB3005 
@Exxion
