### ISSUE TITLE
bug with stacking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11148]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you put a stackable item in your bag while there is some of the item on the floor it all goes in your bag
> What you expected to happen
> to put only 2 sheets of metal in the bag and have 48 on the floor
> 
> What actually happened
> 50 metal in  the bag
> 
> Steps to reproduce if possible
> drop metal and put metal in the bag

**Comment by 9600bauds** [comment]
christ why does everything explicitly drop the item to the ground rather than just removing it from inventory

**Comment by ComicIronic** [comment]
Because the inventory removal procs have been horse shit up to now and drop_item is, at the least, consistent.

**Comment by clusterfack** [comment]
I hate inventory code bugs

**Comment by clusterfack** [comment]
@unid15 ?

**Comment by pedr69** [comment]
this is fixed
