### ISSUE TITLE
Safe on Box vox outpost is not worth opening

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#11158]
Opening the safe on the vox outpost safe is a 30 minute affair.
First you need to trade for [spoiler]steal[/spoiler] a stethoscope from medbay.
Then you have to crack the safe, a very time intensive process.

Your reward is 10 diamonds, uranium, plasma, gold, etc.
This could easily be achieved by mining in half that time.
The vox safe needs a better reward in it. Perhaps some syndicate item like an emag, an agent ID, or a chameleon jumpsuit.

**Comment by kol1th** [comment]
> giving vox an emag they can get in 15 minutes or so that lets them break into anywhere for free

wew, lad

**Comment by charmstruck** [comment]
> The vox safe needs a better reward in it. Perhaps some syndicate item like an emag, an agent ID, or a chameleon jumpsuit.

The vox safe needs to have a live bomb that promptly explodes, destroying the entire outpost

**Comment by Exxion** [comment]
Just fill it with cash money
Still not actually useful, but at least fitting

**Comment by Durgen** [comment]
cash money wouldn't make it worth the time to open it either. 
The reward should be something that is useful, but impossible/difficult to obtain otherwise.

Maybe a chameleon jumpsuit and an agent ID?
Then after some time investment, you could arrive at the station as a vox diplomat, or some other costume centered gimmick.

**Comment by ghost** [comment]
Should have some spare trader IDs so people can use the vox tradeship if there is an absence of traders

**Comment by TheFriggenSawbones** [comment]
cracking a safe takes like two minutes

**Comment by ComicIronic** [comment]
No traitor items outside of being a traitor, especially not for shitposting birds.
<s>except for the suspicious toolbox</c>

**Comment by Probe1** [comment]
idk how I didn't see this.  I completely redid that and made it a very simple system to expand if people are unsatisfied or want to modify safes.
https://github.com/d3athrow/vgstation13/pull/12743
