### ISSUE TITLE
Cannot remove mounted flashlight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11155]
(WEB REPORT BY: fatbaldbastard REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4fb6a0e943eef40b29944088c8c8e88346dd4616
> 
> General description of the issue
> Cannot remove mounted flashlight once it's attached to headgear.
> 
> What you expected to happen
> You're supposed to be able to do that.
> 
> What actually happened
> Nothing good
> 
> Steps to reproduce if possible
> 1) Attach mounted flashlight to headgear
> 2) Try to remove it
> 3)???
> 4) Critical failure

**Comment by 9600bauds** [comment]
Apply screwdriver to helmet to remove light
Unless you want a verb but then Comic would have an aneurysm

**Comment by ComicIronic** [comment]
Verbs can fuck off
