### ISSUE TITLE
Metaclub - Missing engi cam console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11162]
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)

> Revision 5a2fc473dce7735b867c6638ae5653029adc2e3f
> 
> General description of the issue
> There is no engineering cameras console in the atmos monitoring room on metaclub like there is on boxstation.
> 
> What you expected to happen
> An engineering camera monitor in atmos monitoring to check breach status.
> 
> What actually happened
> No engineering camera monitor.
> 
> Steps to reproduce if possible
> Play on metaclub

**Comment by Duny-** [comment]
This was fixed and should be closed.
