### ISSUE TITLE
Force feeding balance

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11160]
(WEB REPORT BY: zalo1302 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5a2fc473dce7735b867c6638ae5653029adc2e3f 
> 
> General description of the issue
> Force feeding is too easy and fast. Sometimes one is writing and already ate something that could have killed you. And forks are even worst.
> 
> What you expected to happen
> Some balance. More slow or something resistable. Give ideas.
> 
> What actually happened
> Got forcefeed amauri fruit and couldn't do anything about it. Like 2 seconds at most.
> Steps to reproduce if possible
> ....

**Comment by 9600bauds** [comment]
It's more than 2 seconds. You get big red text when it happens. If someone has the means to put bad stuff in food they probably have the means to put that bad stuff in you much faster. I'm not concerned

**Comment by Killette2** [comment]
Whileforcefeeding may be able to transfer more units at the speed of, or faster than syringes, some coworker trying to shove a free sample down your throat faster than a near-homeless woman with her do or die food invention at the mall is usually a time you should step back, evaluate what the fuck they are doing, then munch or pass.

If they stunned you first, guess you have to... suck it up.

**Comment by Shadowmech88** [comment]
Besides, pills are even more effective. You can deliver 50u of chems in a pill in the same time it would take you to force-feed a person a bite of food.

**Comment by Allspice** [comment]
I think he's more complaining about the fork. Forking food into someone else is instant, isn't it?

**Comment by Killette2** [comment]
fork serving IS instant, but the amount of chems you can get into a fork bike are abysmal. You cannot chloral someone with a fork.

**Comment by Kurfursten** [comment]
You can chloral someone with a bite of food easily if you fill the bite

I remember Yred used to dropper people with chloral and that's just 5u, back before eye protection stopped it.

**Comment by Killette2** [comment]
Last I checked you COULDN'T fill the fork with chloral

but then again, last time I checked was when the only fork-able food was an omelette and it was funny watching people try to eat it, not know how, and end up stabbing themselves with it while being less food than a mouse nibble.

**Comment by unid15** [comment]
you put the chloral in food and then use a fork on the food

**Comment by Killette2** [comment]
It still would transfer such a microscopic amount of chloral, you probably wouldn't even be knocked out.

**Comment by Kurfursten** [comment]
There's a way around it, get a food with a big bite size but not much nutriment. All foods hold up to 50u chemicals.

So corndogs, eclairs, eucharist wafers, sweets - these are all things that contain 5u chemicals (usually nutriment) but have bitesize 5. You could add 45 chloral to your corndog and when you forcefeed it, the person would receive 4.5u chloral. Almost as much as a dropper of 5u.

**Comment by Killette2** [comment]
How do I look at bitesize? If I'm correct, banana lets you consume a buttload of chems.

**Comment by Kurfursten** [comment]
View Variables if you have admin flags, or you can dig through game/modules/reagents/reagent_containers/food/snacks.dm - or in the case of grown items, grown.dm

However, all grown items have the same bitesize, the default of 1. In any case, it's not really a major concern for me other than forks and that has been handled by unid. :+1:
