### ISSUE TITLE
Telekinesis ceases to work when the hands are tied

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#11168]
Cuffs somehow prevent you from using telekinesis, which shouldn't be the case, since it's your head that's doing the telekinesising, not your mitts

**Comment by ScrambledSteak** [comment]
you need hands to use the force

**Comment by clusterfack** [comment]
Pretty sure we already had an issue on this and you have to wave your hands to use the force

**Comment by DrLeprikon** [comment]
Oh, sorry then, I figured that having only your head glow when you got the power meant you had to wave just the head
