### ISSUE TITLE
weird jukebox bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11164]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you enter a mech and leave the room that had a jukebox playing music you ll keep hearing the music until the song ends
> 
> What you expected to happen
> to enter the mech and not hear the music while outside the room
> What actually happened
> it happened
> 
> Steps to reproduce if possible
> enter a mech and leave a room with a working jukebox

**Comment by PJB3005** [comment]
I assume this is because mech code doesn't use `forceMove()`

**Comment by Exxion** [comment]
I've experienced this bug a lot and it's a bit weirder than this
ENTERING a room playing music in a mech starts the music, but EXITING does not stop it.
The same applies to ventcrawling.

**Comment by clusterfack** [comment]
Is this a new bug or an old one

**Comment by Exxion** [comment]
Few months, at least

**Comment by Exxion** [comment]
Also, this applies to all music players, but does not apply to turrets
Though I haven't looked at turret code in a long time so that may not be relevant

**Comment by Intigracy** [comment]
It's happening to turrets now too.

It's not properly calling entered() on the area is my guess.

**Comment by Exxion** [comment]
That would be a separate bug, because, again, the juke does properly START playing when you enter the area
It just doesn't stop when you leave
