### ISSUE TITLE
Superior Welding goggles allow vision while sleeping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11178]
(WEB REPORT BY: higgsbonbon REMOTE: 172.93.109.202:7777)

> 868b010626d9f9738f0b203d8b64c1b16d59bf60 
> 
> When wearing Superior Welding Goggles, one is able to see everything around them while sleeping as the dark/closed eyes/blind overlay does not activate.

**Comment by Killette2** [comment]
I think that's why they're superior.

**Comment by BarneyGumball** [comment]
Could not reproduce.

I'm 99% sure that this was caused by a different bug related to bruised eyes removing blindness.  Will be fixed by #12038.

![image](http://i.imgur.com/656zTbK.png)

**Comment by ghost** [comment]
Couldn't reproduce
