### ISSUE TITLE
Vox Miners do not spawn with a Miner hardsuit

### ISSUE THREAD

**Issue by Cervante** [d3athrow/vgstation13#11173]
#### Description of issue

Vox Miners do not spawn with a mining suit, instead have an assistant suit

Vox Mechanics have this issue as well
#### Difference between expected and actual behavior

Miner job on vox does not spawn with a job specific suit
#### Steps to reproduce

Spawn as Vox Miner

I've taken the time to nigger rig a set of clothes for players spawning as a Vox Miner in an attempt to solve this issue

[](url)

http://puu.sh/qh45B.dmi
http://puu.sh/qh46P.dmi

![suit](https://cloud.githubusercontent.com/assets/20673509/17200470/32a0cb02-544b-11e6-99a3-2494ab5446e1.png)
![head](https://cloud.githubusercontent.com/assets/20673509/17200472/3a8c3f40-544b-11e6-881f-c0906349d2d1.png)

**Comment by Exxion** [comment]
Oh holy fuck you attached the entire .dmi
Which... somehow actually worked
But please just post a link to the actual .dmis and just post the new sprites

**Comment by Exxion** [comment]
Actually hold on
This is an issue
Open a PR with the new sprites and only post the new sprites in the text of the OP

**Comment by Cervante** [comment]
Which version am I comparing to? Bleeding edge to 64x64?

**Comment by Exxion** [comment]
It doesn't look like you even have a fork at the moment
You may want to read through the Wiki guide on contributing to the game

If that's too much work for right now, you can post a .png of just your sprites here and someone else can do it. I highly recommend getting Git set up properly if you want to contribute more content in the future, though.

**Comment by Cervante** [comment]
I have no idea what I'm doing.

**Comment by Exxion** [comment]
That's fine, everyone has to learn
First of all, go over to the code tab and click the fork button in the upper right.
Have you downloaded Git and a Git client yet?
(Technically speaking, the client isn't necessary, but it makes it a lot easier)
(Most people here recommend SmartGit. I use regular old Github Desktop, but it sucks ass and I only still use it because I'm too lazy to upgrade. It does work, though.)

**Comment by Wizardcrying** [comment]
fuck smartgit
if you're doing simple shit tortoisegit uses the context menu and is better in my opinion

**Comment by Exxion** [comment]
It really doesn't matter which one you use, because you can always just change your mind later and all of them work for the basic stuff
(Except Github Desktop can't actually do some things properly, but they're easy to do on the command line)
