### ISSUE TITLE
bicon() is fukt when called on icons, not objs

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11179]
We have here two procs:

```
/obj/machinery/chem_master/proc/test_w_bicon()
    for(var/i = 1 to MAX_PILL_SPRITE)
        var/icon/I = icon('icons/obj/chemical.dmi', "pill" + num2text(i))
        to_chat(world, "Pill number [i] / Ref: \ref[I] / Bicon says: [bicon(I)]")

/obj/machinery/chem_master/proc/test_w_icon2base64()
    for(var/i = 1 to MAX_PILL_SPRITE)
        var/icon/I = icon('icons/obj/chemical.dmi', "pill" + num2text(i))
        var/fuckmasterflex = icon2base64(I)
        to_chat(world, "Pill number [i] / Ref: \ref[I] / icon2base64 says: <img src='data:image/png;base64,[fuckmasterflex]'>")
```

If bicon() worked correctly, both of these would give the exact same results.

The second proc seems to work fine:
![dreamseeker_2016-07-28_18-14-05](https://cloud.githubusercontent.com/assets/6526157/17229669/178bc5e8-54ef-11e6-951e-4295551c939f.png)

but bicon() only gives the first 2 pills over and over (ignore the fact that the icons look smaller):
![mspaint_2016-07-28_18-13-34](https://cloud.githubusercontent.com/assets/6526157/17229679/27807ce6-54ef-11e6-8aef-0bf9976a8f39.png)

So what's the problem here? Well, if you look at bicon(), it stores icons in a global cache to prevent doing the same icon twice. The problem here is that it indexes the icons by reference, under the assumption that an icon's reference will never change, I think
However that is not the case as seen with these procs: After an icon gets generated, it gets deleted, and a new icon takes up the reference. Pill icons 3+ onwards ARE being created correctly, bicon() just sees them, looks at the reference, and says "oh hey it's pill1 I saw just now".
I hope I'm explaining the issue correctly here. See browseroutput.dm, line 199

**Comment by PJB3005** [comment]
Yes `bicon` with icon datums is awful and in need of a rewrite.

**Comment by 9600bauds** [comment]
Do you have any ideas on how to fix it? I really don't know how you would handle the cache given that you can't get a unique \ref out of icons.
