### ISSUE TITLE
Passive vents issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11177]
In the wiki's [Guide to Atmospherics](http://ss13.moe/wiki/index.php/Guide_to_Atmospherics) passive vents are described as

> Passive vent - These vents will allow the environment they are in and the pipeline they are connected with to interact and come into equilibrium. If placed in space these will vent gases instead.

but actually, they work just like injectors:
- they are one-way only, from the pipe to the environment;
- they keep injecting all the gases from pipe to environment until there is no more gas inside the pipe;
- it seems that they don't have a pressure limit for the environment.

![passive_vent](https://cloud.githubusercontent.com/assets/6170726/17215953/079b337c-54df-11e6-8b98-11b4851e83e9.jpg)

so the only difference from injectors is that you can't use a multitool on passive vents, therefore you don't have any control on them.

is this the intended behaviour? is the wiki outdated? or am i missing something?

note that if they will actually spare pressure between pipe and environment instantly, people could use them to replace scrubbers/vents inside gas chambers.

**Comment by PJB3005** [comment]
How they currently work: unpowered vent pump with constant mole rate.

How they should work: as the wiki describes.

**Comment by pedr69** [comment]
this is fixed
