### ISSUE TITLE
64x64: the issue

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#11176]
So, I made a branch for 64x64 sprites, it can be seen here: https://github.com/d3athrow/vgstation13/tree/64x64

Most of the sprites are already upscaled with nearest neighbor interpolation by a script I made, but we need to do more than that. This issue servers as a way to keep track of what needs to be done:
#### Pixel offsets

Because we have double the icon size we need to double the pixel offsets of everything. Sadly this is very complicated.
#### Higher resolution lighting overlay

~~While not critical, we have double the resolution to work with for a lighting overlay so we should probably take advantage of it. Issue is that I'm too crap to figure out the formula used for it.~~
Scratch that it results in a complete fucking mess anyways. Really gonna need some help to reverse engineer it and fix it.

The lighting overlay has 4 corners, each corner has an associated channel in the PNG:
- **Bottom left:** Red
- **Bottom right:** Green
- **Top left:** Blue
- **Top right:** Alpha

The lighting overlay is interpolated between these 4 colours. The issue is the way it's interpolated.
- On the edges of the sprite, the interpolation is linear. (bottom center is ~128 red).
- On the diagonals, it's a square root function. This is (luckily) just a `sqrt(x)` so it's relatively simple.

Between diagonals and edges... Some mixture of the 2 probably. Help with this would be appreciated. I did try to use bilinear or bicubic resampling on the lighting overlay to upscale it but both resulted in an unusable mess.
#### Title screens.

They're gifs and PNGs, shouldn't be too hard to upscale.
#### Bingo.
- [x] Pixel offsets.
- [x] Lighting overlay. 
- [ ] Title screen.

**Comment by Cisrox** [comment]
we /hd/station now?

**Comment by ComicIronic** [comment]
By doubling the pixel offsets, do you mean the pixel_x and pixel_y changes, because we could probably Regex them.

**Comment by PJB3005** [comment]
@ComicIronic: @clusterfack already did this just now in 2f55eeb888ae951b7b250d7f2b71b3f8434f9c1b

**Comment by clusterfack** [comment]
I've taken it upon myself to fix pixel shifting for this project because I'm interested in it.

I'm open to suggestions on how to fix pixel shifts in screen locs though, I'm not sure how to keep them a constant value.

**Comment by 9600bauds** [comment]
issues with 64x64
icons are twice as big in altclick
icons are twice as big in VV and presumably in very single UI
adminbus UI wouldn't show up for me, showed up twice for kolith
![dreamseeker_2016-07-28_19-37-54](https://cloud.githubusercontent.com/assets/6526157/17232295/63c41074-54fd-11e6-8669-20927b2e4eef.png)
vamp blood counter is fucked up

**Comment by Intigracy** [comment]
anyone who doesn't have at least a 960 pixel tall screen resolution is fucked if we switch to 64x64, as an fyi.

**Comment by clusterfack** [comment]
Stretch to fit still exists

**Comment by ghost** [comment]
And stretch to fit looks better down-scaling over up-scaling.

**Comment by clusterfack** [comment]
Because really if they have a 900p screen resolution, they're using stretch to fit, because its pretty close to 960 and really really far from 480.

**Comment by Intigracy** [comment]
I used to play on 32x32 on my 1366x768 f a m i l y

when I play on 64x64 on my 1920x1080 the top few pixels are cut off of the game window (not the byond window, the box the game is in inside of the byond window)

when I play on stretch to fit with the game window (not the byond window) resized right it doesn't look like shit

**Comment by clusterfack** [comment]
Used to, because thats ancient

**Comment by Shadowmech88** [comment]
> Most of the sprites are already upscaled with nearest neighbor interpolation by a script I made

That's going to lead to mixels, since new sprites will be made with 64x64 in mind while the old sprites will simply be rescaled 32x32.
In order for it to not look like ass in the long run, we'd have to actually _resprite_ everything in the game to make use of the increased resolution.

Good luck with that.

**Comment by clusterfack** [comment]
>In order for it to not look like ass in the long run

We're several years into the long run and that has already occurred tbh

**Comment by clusterfack** [comment]
Besides have you even seen what it looks like yet? I've hosted several servers.

**Comment by Shadowmech88** [comment]
I really don't mind the way the game looks now. The sprites might not be high-quality, but at least they're mostly consistent.

Having sprites of two different resolutions in the same game generally always looks terrible.

**Comment by clusterfack** [comment]
Yeah I don't really think it'll be a problem

**Comment by NigglyWiggly** [comment]
Please no.

**Comment by PJB3005** [comment]
https://github.com/tgstation/tgstation/pull/19566

**Comment by ghost** [comment]
I've just had an awful idea that might help with incompatibility with others.

You know how there's an 'icons' section at the top of the game screen (Probably something we can't access)

How about we use something similar to that to switch between 32x32 and 64x64 icons, so people who can go HD can go HD, while we don't alienate people playing on hamster powered potato computers

**Comment by PJB3005** [comment]
Nope not feasible.

**Comment by NigglyWiggly** [comment]
because not everything is going to have 64x64 sprites, and not everything will have a 32x32 equivalent.

**HOPE YOU LIKE MIXELS**

Also you can see my opinions on this in the PR PJB linked

**Comment by mph55** [comment]
Just go with 128x128 before TG cucks us

**Comment by Blithering** [comment]
Mixels are going to be a problem as Niggly said. I'm not that smart on this whole thing, but does this mean large mobs like the alien queen will have to be done in 128x128?

**Comment by clusterfack** [comment]
Yeh
