### ISSUE TITLE
Court Windoors open in an odd way

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11171]
(WEB REPORT BY: senaat1 REMOTE: 172.93.109.202:7777)
Revision: 868b010626d9f9738f0b203d8b64c1b16d59bf60 

> General description of the issue
> When you open court doors from INSIDE the court area, the outer door opens before the inner door. See:
> http://i.imgur.com/FAj6knP.png
> http://i.imgur.com/qC48mGA.png
> http://i.imgur.com/CbDZoK4.png

**Comment by 9600bauds** [comment]
Not specific to any windoor, this is just byond Bump() code being ass and Lummox refusing to fix it

**Comment by Shadowmech88** [comment]
Our windoors used to not have this problem because we used to use our own code for bumping things.

Is the performance gained by using the built-in Bump() code worth all this hassle?

**Comment by PJB3005** [comment]
It was never about performance. It was about making pixel movement feasible in the future.

**Comment by Shadowmech88** [comment]
How about we go back to the old way for now, and wait until someone _actually_ starts working on pixel movement before we use Byond's terrible Bump() code?

**Comment by 9600bauds** [comment]
Why do we even want pixel movement

**Comment by clusterfack** [comment]
Because gliding movement is literally deprecated, which is why lummox refuses to fix this bug.

**Comment by PJB3005** [comment]
Fixing it shouldn't be then end of the world though.

Just make a `BUMP_CHECK` macro and make that manually do the `Bump()` calling as a check in `Bump()`

**Comment by 9600bauds** [comment]
Please we need that

**Comment by clusterfack** [comment]
I wont stop anyone from doing what they please, but being the person I am the only ideal solution I see requires the fix lummox has delayed giving us and I have been waiting for it VERY PATIENTLY for how many months now.

**Comment by Shadowmech88** [comment]
This is _still_ happening.

It makes moving around in the armory a pain in the ass.

**Comment by Shadowmech88** [comment]
Tested, no longer exists.
