### ISSUE TITLE
Unable to vend medicine from a smartfridge with a "+" plus sign in the name

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11189]
#### Description of issue

Pills(and probably bottles) with a "+" in the name don't vend from a smartfridge
#### Difference between expected and actual behavior

All pills vend
#### Steps to reproduce

Name a pill "something+"
place it in a smartfridge
attempt to vend it
nothing happens
#### Specific information for locating

/obj/machinery/smartfridge/chemistry
#### Length of time in which bug has been known to occur

Likely a result of #10950 
#### Server revision

ccb55b121a3fd5338fc56a602424016009566488 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by 9600bauds** [comment]
I can't believe I only tested loading but not actually vending it.

**Comment by ghost** [comment]
RIP Dex+ pills
