### ISSUE TITLE
Super singulo fails to eat supermatter crystal on teststation.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#11184]
But it still sort of starts the supermatter cascade.

Singulo code has `try`/`catch` statements on its `Eat()` for some reason so stack traces and such are impossible.

![](http://i.imgur.com/WSbekfq.png)

**Comment by clusterfack** [comment]
Im sure its due to the fact all that shit is missing endgame landmarks.

**Comment by Shadowmech88** [comment]
This is both very old and not really an issue if it only happens on the test station and never impacts gameplay.
