### ISSUE TITLE
Right clicking things makes the borer tab disappear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11194]
(WEB REPORT BY: themegagoat REMOTE: 172.93.109.202:7777)

> Revision 19fdd8c4b429cd4d468953ed7ff4be47cf9383f8
> 
> General description of the issue
> Right clicking things makes the borer's 'alien' tab with all their powers go away

**Comment by Kammerjunk** [comment]
Definitely a thing. What I'm told works as a temporary fix is reconnecting.

**Comment by JMWTurner** [comment]
Still a thing, and I have no idea what causes it.

**Comment by clusterfack** [comment]
It's a byond bug with the current beta build
