### ISSUE TITLE
Fuck you, whoever did the change to Vampires

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11191]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)

> Set up a trap for a guy 
> He is half dead
> Decide to drink his blood
> Your fangs fail to pierce his cold flesh
> What the fuck?

**Comment by ihadtoregisterforthis** [comment]
The reporter hints that he was mistaken by deleting his post on the thread.
The victim was another vampire, not related to ckeyless body change

**Comment by Killette2** [comment]
> ahelping prior to making issues is bad
> issues like this pop up

wew lad, it's almost as if admins could answer these questions if asked, and the github wouldn't be filled with non-bugs.

**Comment by Exxion** [comment]
> filled with non-bugs

This happens like twice a month, if that
Whereas ahelping to report issues actually results in an issue being opened basically never

**Comment by clusterfack** [comment]
Ahelping to inform the admins of a bug is useless, it's not the same as an ahelp to get clarification about the bug or to ask whether something is a bug.

**Comment by Exxion** [comment]
Ah damn. I misread  Killette's post. Sorry.
Though I'm not sure who ever said that ahelping before opening an issue was bad

**Comment by Intigracy** [comment]
close when

**Comment by Intigracy** [comment]
close and stay close when

**Comment by AutismSpider** [comment]
close and mark him as dip shit.

he try suck off the other vamp that shit gay man like touching dicks.

when you try suck off a monkey human it calls it mindless body.
