### ISSUE TITLE
Welding tool doesn't update its icon when fuel runs out

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11199]
#### Description of issue

When a welding tool runs out of fuel, it still shows up as lit
#### Difference between expected and actual behavior

shouldn't be lit without fuel
#### Steps to reproduce

weld stuff with a welding tool
the flame is still lit even when the fuel runs out
#### Specific information for locating

/obj/item/weapon/weldingtool/process() or wherever it updates its icon
#### Length of time in which bug has been known to occur

For a while now probably
#### Server revision

5da18a6115e7a93926843c15c5111ed2f417d840 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
This has been an issue for months.

**Comment by PJB3005** [comment]
> months

Years.

**Comment by Shadowmech88** [comment]
This is no longer an issue.
