### ISSUE TITLE
Slipping in the syndie wheelchair in space can cause you to run yourself over.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11201]
#### Description of issue

Based on some variable criteria when you slip the syndie wheelchair will potentially run yourself over if you slip in space. 

![untitled](https://cloud.githubusercontent.com/assets/5564796/17271429/9ddef140-5627-11e6-902b-a81cbb2dae54.png)

It seems that you're mostly okay when you go in one direction but if you slip while changing direction or doubling back you can run yourself over. So it seems like your body is getting there ahead of the chair then when the game updates your destination tile with the chair it checks for bodies, sees yours, and runs you over.
#### Difference between expected and actual behavior

To simply slip and not murder me
#### Steps to reproduce

Drive around lattice in space and on the edge of the station
#### Length of time in which bug has been known to occur

Just found out.
#### Server revision

d285a4411d86d707427ddbe1835ff4ae9ad5c086 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
I almost want to say it would have made sense to turn your magboots on. That way you wouldn't slip out of your chair, and the boots would keep you magnetically attached to the chair foot rest.

Also magboots prevent slipping when near objects such as outer station, lattices, and asteroids for those who didn't understand.

**Comment by AutismSpider** [comment]
some thing some thing turn ur mag boots on when in space dummy

**Comment by Shadowmech88** [comment]
Tested locally, I was unable to slip at all while spacewalking in the syndicate wheelchair.
