### ISSUE TITLE
Evolving as a diona nymph deletes your in-hand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11200]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)

> Revision 5da18a6115e7a93926843c15c5111ed2f417d840 
> 
> General description of the issue
> Evolved while holding my plastic bag of tools
> 
> What you expected to happen
> It to be on the ground or transferred to my new hands
> 
> What actually happened
> Plastic bag disappeared
> 
> Steps to reproduce if possible
> Be a nymph, hold a plastic bag, evolve.

**Comment by Kurfursten** [comment]
This happens with basically all transformation, including monkification and also robot transformation virus. I assume it also happens with player panel transformations too.

I feel like we should have a generalized proc for transformation that all others should inherit.

**Comment by Intigracy** [comment]
all of them inherit drop everything, but drop everything up until this point apparently didn't include hands.

**Comment by Exxion** [comment]
WOO INVENTORY CODE
