### ISSUE TITLE
feature request: ion jetpacks

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#11208]
The main problem I have with depending on a jetpack is how fast the fuel runs out when going full blast in one direction. Added to this problem is how much larger space is.

My idea to help solve this issue is a large capacity jetpack that requires little to no fuel.

Idea one is a atomic battery that never runs out. But it moves slower.
Idea two is much more complex. A toxins powered jetpack that takes two tanks. You set the percentage from each tank taken, and the rate gas is let into a chamber that propels the jetpack. Percentage let's you make hotter plasma tanks and colder O2 tanks and waste less fuel. Rate let's you adjust speed. So if you have a hot plasma tank and cold O2 tank you can keep a spare plasma tank on you and swap them out if needed. You can set a really high rate with a super mixture and zoom across space at warp speed.

**Comment by FudgePucker** [comment]
So pretty much bomb powered jetpack

**Comment by Kurfursten** [comment]
> when going full blast in one direction

Space movement should respect Newtonian physics so that if you increase your velocity with a jetpack you will continue moving at that speed if you turn the jetpack off.

Maybe @unid15 is interested in that

**Comment by Exxion** [comment]
Newtonian physics won't work well with only 8 possible movement directions

**Comment by Shadowmech88** [comment]
Maybe the blast cannon should propel you backwards at maximum speed when you fire it in space.

**Comment by Exxion** [comment]
I'm not even sure if there is a hard cap on speed

**Comment by FudgePucker** [comment]
> I'm not even sure if there is a hardcap on speed

Oh boy all I heard was zooming around space backing the light barrier. Fuckin fantastic

**Comment by Exxion** [comment]
Touch the singularity containment field on the side facing deep space. You will get somewhere FAST.

**Comment by clusterfack** [comment]
The highest cap for true movement is at the rate of ticking, which is 30 times per second. 

You can get a feel for this by using the highest ghost speed setting.
