### ISSUE TITLE
Clicking on the Message Monitoring Console in RD Server Room faces me with an "improper argument"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11218]
(WEB REPORT BY: megatonthrustman REMOTE: 172.93.109.202:7777)

> Revision: b4b585337b24b60e49dff0d2433f9e621ba7b590 
> 
> Upon trying to access the Message Monitoring Console, I got hit with a message saying "faced with an improper argument", thus preventing me from even moving my character. I then died from freezing upon quitting and rejoining the game because of the RD Server Room's cooler.
> 
> Literally try clicking the Message Monitor console and you get hit with that shit

**Comment by ComicIronic** [comment]
Is this us?

**Comment by gbasood** [comment]
Maybe someone fucked with telecomms and produced this?
Or something brand new popped up from all the regex changes that we didn't notice yet

**Comment by clusterfack** [comment]
It's a byond thing
