### ISSUE TITLE
Blob expansion does not care whether or not the connected tiles actually have a link to the blob core or a resource node

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11217]
#### Description of issue

Previously, you could cut the head off of a blob expansion if it decided to go in a straight line, severing the ties and resource application to two zones

This is no longer the case. The area at the bottom right of the chapel had no resource nodes, not even the factory node at the time, yet it still pulsed as if it was still receiving resources, and the blob was able to expand from it despite the clear severance from the core

![derp frontier 53 2016-07-31 123332](https://cloud.githubusercontent.com/assets/9110500/17276259/90d864f0-571b-11e6-8a37-6a7b28333f0e.png)

Hell, a player-controlled blob can expand from a single base blob that is not connected to ANYTHING, whereas an NPC blob chunk just stays inert.

This, coupled with the increased resource intake, makes blob nigh unwinnable even after 3 hours prep time for the crew
#### Steps to reproduce

Blob is expanding in a straight line attempting to take something important

Cut the neck of if

It still continues growing regardless

RIP Tactics
#### Specific information for locating

Deity blob
#### Server revision

b4b585337b24b60e49dff0d2433f9e621ba7b590
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
Pulsing can occur from the blob's cursor even if it's disconnected from core, which is exactly what Deity intended it to do

**Comment by clusterfack** [comment]
Actually its a change I made over a year and a half ago I believe, the AI's eye itself causes the blob to grow in a specific area.

**Comment by gbasood** [comment]
When you say AI I hope you don't mean the actual sillycon AI and you actually mean the overmind

**Comment by clusterfack** [comment]
Lel yes I meant the overmind, I'm so used to saying the phrase 'AI eye'

**Comment by ghost** [comment]
So, this means that the usual tactic is

> Make some overminds to stack against the crew
> Get everyone to team up
> Force your way through with impunity as multiple blob overminds on the same tile all make blobs at once

We've had entire stations become blob before the crew could even call it because of blob storms. Blobs aren't affected by explosives, and can just brute force their way across space if needs be.

**Comment by gbasood** [comment]
They'd do that even if it wasn't an issue related to overmind eye pulse-based growth.
They'd just spam blob growth, because the 'pulse' only procs like once every 5 secs. and multiple eyes on the same tile won't grow more than one tile's worth of blob per pulse afaik

**Comment by DeityLink** [comment]
> 
> 
> So, this means that the usual tactic is
> 
> > Make some overminds to stack against the crew
> > Get everyone to team up
> > Force your way through with impunity as multiple blob overminds on the same tile all make blobs at once
> 
> We've had entire stations become blob before the crew could even call it because of blob storms. Blobs aren't affected by explosives, and can just brute force their way across space if needs be.

If the blob can grow large enough to have multiple overminds (which is usually their end-game) then that's kind of their goal. Blobs spawned by blobstorms also tend to be at a disadvantage and lose by far most of the time.
