### ISSUE TITLE
Freshly converted cult will not get cthulhu icon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11210]
(WEB REPORT BY: ch0c0latem00se REMOTE: 172.93.109.202:7777)

> Revision 971a4a07a726ec051dd162015c9ed9045b03f56a
> 
> General description of the issue
> Cult that is converted through rune does not get cthulhu icon above head that others can see.
> 
> What you expected to happen
> To be able to see who is my ally and who isn't by looking above their head
> 
> What actually happened
> REEEEEEEEEEEEEEEEEEE
> 
> Steps to reproduce if possible
> Convert someone, look above head.

**Comment by ihadtoregisterforthis** [comment]
Time to "temporarily remove" cult then

**Comment by Allspice** [comment]
Haven't seen this for a while, maybe it was some plane shit that automagically went away?

**Comment by ghost** [comment]
Could not reproduce
