### ISSUE TITLE
Talk about the Syndicate Wheelchair.

### ISSUE THREAD

**Issue by ss13Tanker** [d3athrow/vgstation13#11216]
I understand that there was a vote to nerf the wheelchair, and that the problem is that there is no idea of HOW to make the nerf, well, I have a couple of ideas.

I don't think that the increase in cost would help the case, because it could cost 10 telecrystals and still it would be used, the chair is all you need; I think the key to ner if is augmenting the cooldown in between hits and however we can increase it would be a good idea.

I think the way to approach it is one of the following ways:
After running over someone, the chair advances 3 tiles in the direction it ran over someone.
Dave it have a 1.5 or 2 second cooldown before it rolls over a specific person, if it's tried, the wheelchair will push.
It's also a problem for knockdown, because on the second hit you're on the ground and maybe with a limb off, I'm not aware of the Sharpness it works on, but I don't think it's the main issue here.
Damage is fine as is, and if any of these nerfs is implemented, then I don't think any nerf to knockdown would be necessary; however, knockdown should be reduced if cooldown is not increased, and if it's not increased then damage should be reduced too, maybe to 15.

And that is my suggestion. Hope it's not terrible.

**Comment by ghost** [comment]
Personally, I think it should cost 8tc, and only affect those knocked down already. And with that, require a certain distance travelled to knock people over; deal damage. In light of that, I feel like it should do a bit more damage, as it becomes harder to use, and it's stun shouldn't effect those already laying down. Would mean people need to put a bit more effort into murderboning with it by grabbing themsevles a ranged stun to just face roll, adds a tonne of counters in light of communication and time.

**Comment by Blithering** [comment]
Leave the damage, stun and cost as is. Paint it red. make it blast out https://www.youtube.com/watch?v=atKUCxXanXA to everyone in view.

**Comment by 9600bauds** [comment]
Give it a TURBO button where it moves 5 tiles forward, have it only damage while TURBO

**Comment by ss13Tanker** [comment]
Well, seeing what's done here, apparently we mostly agree that the way to do it is to have it travel a specific distance for it to deal damage.

**Comment by AutismSpider** [comment]
FOR FUCKING ONE don't make it fucking look like normal wheelchair paint it red/black 

Da red wunz go fasta!

Make it go X distance to deal damage/knock down/turbo button to run down people up close.

**Comment by 9600bauds** [comment]
Make it leave siiiick skidmarks

**Comment by jknpj** [comment]
- Make it red. 
- Make it leaves a red afterimages, just like a comet tail. 
- Spawn a White helmet with it.
- Give a "You feel a strange pressure in the air..." message to everyone that get near one.

For something so retardly strong, being stealth is completly unbalanced.

**Comment by Killette2** [comment]
Why do you all want to make it yred? Then it will have the power of chloral at it's disposal too!

**Comment by AutismSpider** [comment]
red for speed son.

Red makes you go faster man

**Comment by 9600bauds** [comment]
Yred is creatine queen, not chloral

**Comment by SonixApache** [comment]
Same thing as the lance; only do damage if it's going fast?
