### ISSUE TITLE
Wooden Plants Harvestable By Hand

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#11225]
No longer need a sharp object @9600bauds

**Comment by Killette2** [comment]
I noticed this when using a plant bag I think. Can you do it with bare hands too?

**Comment by Kurfursten** [comment]
Yes

**Comment by Killette2** [comment]
How does this affect vines with the ligenous trait?

**Comment by Kurfursten** [comment]
Haven't tested it, but since that's not part of the harvest proc it's probably fine

**Comment by Killette2** [comment]
This is still an issue
