### ISSUE TITLE
Plans for /vg/UI: An actually GOOD UI system.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#11221]
So here's the deal, there is literally _no good_ UI framework in use on any SS13 codebase, except maybe Goon but we can't steal that anyways.

NanoUI has the issues of >it's nano. Paradise NanoUI has the issue of >it's slightly better nano but still nano and anything cool is impossible. TGUI is [slow as hell and unusable](https://github.com/tgstation/tgstation/issues/16702), _and_ it still has the same issue as ParaUI. HIM (HTML Interface Module) still has the issue of being a complete ass pain to work with. Browser datum / direct browse call is just bad because it renders the HTML server side. The list goes on.

**So can we do better?**

So here's what I'm planning for an _actually good_ UI framework:

First, we steal the server backend of TGUI, it's actually good, modular and robust. Including the data caching thing done for larger UIs I'm confident it'll work.

Secondly we rewrite the HIM from scratch and make it support data & auto updating like TGUI, **but we don't make it have templating by default**. We'll write a simple module system so that can be loaded separately for the UIs that want it. More complex UIs will obviously still use the manual UI building system.

Templating will be done with ParaUI's system, although I might enhance it to support `<input>`.

Then finally to finish it all off we take @neersighted's amazing TGUI stylesheet.

Who's with me to make SS13 interfaces finally great (I'd say great again but they were never great).

**Comment by kol1th** [comment]
:+1:

**Comment by 9600bauds** [comment]
I'm not really well-versed on this stuff but sounds good to me. I could help converting old UIs I guess, not so much with building the backend

**Comment by ghost** [comment]
How can I help?

**Comment by PJB3005** [comment]
Learn Javascript, HTML and CSS I suppose.

**Comment by ghost** [comment]
@PJB3005 why did you have to list the three languages I don't like damn it

**Comment by PJB3005** [comment]
https://gist.github.com/PJB3005/36e4de1080aac2ba0f66246224ccefd6

First draft of the public server side API is done. Gonna need a lot of work and more things (information about styles, states, UI objects)

**Criticism is extremely welcome.**

**Comment by PJB3005** [comment]
Added UI objects to the API draft.

https://gist.github.com/PJB3005/36e4de1080aac2ba0f66246224ccefd6

**Criticism is extremely welcome. Also look around for "TODO" spots and give feedback on things I was unsure about.**

**Comment by PJB3005** [comment]
Updated again https://gist.github.com/PJB3005/36e4de1080aac2ba0f66246224ccefd6

**Comment by optimumtact** [comment]
I always thought nanoui's templating frontend was alright, and we certainly did not have any performance concerns that I recall back when it was introduced.

**Comment by optimumtact** [comment]
Also if I have a bit of criticism rename the states datum to interaction_states or somethign more descriptive.

It confused me when I first read through tgui's backend code.

**Comment by ghost** [comment]
@PJB3005 why are you bothering to typecast bools and strings and such? Like, why?

**Comment by ComicIronic** [comment]
Because it is way more readable.

**Comment by ghost** [comment]
That's just nonsense

**Comment by ComicIronic** [comment]
Potato Nocode strikes again.

**Comment by Exxion** [comment]
He's right
It's utter nonsense unless the person reading the code is braindead, assuming you use the TRUE/FALSE defines

**Comment by PJB3005** [comment]
Nah.

By the way I want to remind you that you NEED these kinds of explicit primitives if you ever want a code parser to be worth shit.

**Comment by ComicIronic** [comment]
> It's nonsense

So you think it DETRACTS from the code's readability to have them declared explicitly?
Why is it a negative change to be able to see the type of a variable passed into a proc from the signature without looking at the code?

**Comment by Exxion** [comment]
Nah
I don't care whether or not you do that
But saying it is "way more readable" is nonsense

**Comment by ComicIronic** [comment]
```
/proc/add(var/item1, var/item2)
    item1 = cut(item1)
    item2 = item2 == null ? default() : item2
    return item1 + item2
```

In this example, are the two vars numbers, or strings, or lists?

```
/proc/add(var/string/item1, var/string/item2)
    item1 = cut(item1)
    item2 = item2 == null ? default() : item2
    return item1 + item2
```

Wow, now I know!

**Comment by Exxion** [comment]
You'd need more information than just the signature to know what the proc actually _does_, though, and using a proc without knowing what it does is asking for trouble.

**Comment by ComicIronic** [comment]
Unless, shock horror, the proc is well documented, and you can tell what it does from reading what has been written about it.

**Comment by Exxion** [comment]
Yes, if it's well-documented, you shouldn't NEED to read the signature to see what variable type it accepts.

**Comment by ComicIronic** [comment]
Having variable types in the signature is part of that documentation.

**Comment by PJB3005** [comment]
Alright I want to fucking revive this but I'm only doing it under the condition that the Javascript code can be written in TypeScript.

**Comment by PromethTK11** [comment]
Reviving this one, again

**Comment by PJB3005** [comment]
Nah I can't be bothered to code BYOND anymore. F
