### ISSUE TITLE
Trader ID prompt is stupid

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#11222]
At shift start vox traders have an ID prompt where they have X number of seconds to hit 'Yes' to get their Vox Trader id.

The Trader ID is important because it allows you to use the Trader shuttle console and easily get to and from the station.

Needing a prompt to recieve it, however, is stupid. There really isn't a reason why someone would reject the ID, so it only serves as an AFK check.
If you are unfortunate enough to miss the shift start by a minute, (perhaps because you have the lobby music muted) you will be without an ID for that round unless a goodmin spawns you one.

Someone please remove this shitty feature.

**Comment by Kurfursten** [comment]
@gbasood This isn't a Bug / Fix, this is more like a Feature Request or Discussion.

I've been thinking this for a while. It's snowflakey and doesn't really serve a purpose. What's worse is that it makes it so you have to have considerations for ID-less Vox in mapping (e.g.: you can't put Vox access on the outpost doors, so scientists and miners can waltz right in and poison the place with oxygen). If that wasn't bad enough, it actually prevents you from using alternate titles.

Scrap it and make the outpost fully Vox access

**Comment by gbasood** [comment]
yeah no its more of a feature request you're right

**Comment by 9600bauds** [comment]
In TG's github they have a tag for this and it's called [Bad Feature]

**Comment by gbasood** [comment]
Feel like there's a better tag name than that
Bad Feature sounds like something people would ask for on hypothermia

**Comment by Exxion** [comment]
[Why]
[T-Thanks, coders]
Etc.

**Comment by Wizardcrying** [comment]
I'd be okay with doing the ID part.
I'm not sure about the mapping part, mostly because I have no idea of how hard it would be to get the change merged after it's made.

**Comment by unid15** [comment]
I added that because I thought that vox raiders don't spawn with an ID (they actually do), and I wanted to have the possibility of ID-less traders so that raiders could impersonate them
