### ISSUE TITLE
Goldgrub doesn't drop gold

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#11228]
Goldgrubs currently drop nothing on death and can only be butchered for goldgrub meat. How could we possibly reward a miner who manages to kill one of these things?
Perhaps, to start, small amounts of bananium and phazon?

**Comment by ihadtoregisterforthis** [comment]
They were supposed to drop minerals on death.
Bug or "temporary removal to accommodate economy”?

**Comment by 9600bauds** [comment]
Memes are dandy and all but now you're just memeing in places that don't even make any sense

**Comment by AutismSpider** [comment]
make the tame ones not run away for starters.

Feeding a tame one raw ore will process raw ore it for but you get double back.  

so lets say you feed it two phazon ore you get four  sheets back etc etc

**Comment by clusterfack** [comment]
Just an oversight that it doesn't drop anything, add some ores to it

**Comment by jknpj** [comment]
They won't drop anything if they don't eat anything.
