### ISSUE TITLE
Ways to use planes?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11223]
Things I've got in mind so far are:
- Cult HUD
- Asteroid Turfs optimisation
- Wizard HUD
- Holomaps
- That one tool that engineering has that everyone has seen before but nobody knows the name of.

Need some more ideas about how to make planes actually useful now we have them set up properly.

**Comment by clusterfack** [comment]
Put all pipes and wires on a specific plane when hidden. Make a new type of goggles that gives you a plane master so you can see the pipes/wires underneath tiles.

**Comment by ghost** [comment]
@clusterfack that's uh, that's similar to the one tool that everyone has seen but nobody knows the name of, but yeah that's totally feasible.

**Comment by clusterfack** [comment]
Never heard of it

**Comment by clusterfack** [comment]
I mean basically ANYTHING that you want selective invisibility for - planes

**Comment by PJB3005** [comment]
Make holomaps use planes.

**Comment by ghost** [comment]
@clusterfack yeah you have, it's the one that makes them appear slightly visible, flashing, and everyone can see it and it is occasionally left out in the hallways

**Comment by ghost** [comment]
@PJB3005 totally feasible, that was already in the OP though.

**Comment by 9600bauds** [comment]
tray scanner

**Comment by clusterfack** [comment]
It's NOTHING like the tray scanner

**Comment by clusterfack** [comment]
You sir are a charlatan

**Comment by PJB3005** [comment]
Oh, make mining scanners to replace the mesons miners get.

Immersion.

**Comment by clusterfack** [comment]
This becomes not only feasible
https://github.com/d3athrow/vgstation13/pull/6785

It becomes a legitimately good idea

**Comment by 9600bauds** [comment]
Oh, oh, make hallucinations into their own plane so you can make it ~wobbly and shit~

**Comment by 9600bauds** [comment]
That's what planes do right?

**Comment by clusterfack** [comment]
You can do that kind of thing with them yes, mass transformations of things on the plane

**Comment by 9600bauds** [comment]
Blood exception for noir maybe, and add red dresses to it
P.S. I don't know what I'm talking about

**Comment by clusterfack** [comment]
Yep, that would be something too bauds

**Comment by ghost** [comment]
@9600bauds that one was already done, though red dresses were not included. Might do that.

**Comment by 9600bauds** [comment]
Holodeck plane for mad sickkk holodeck malfunctionzzzzz

**Comment by ghost** [comment]
@clusterfack So, instead of a luminol spray, some kind of UV glasses?

**Comment by ghost** [comment]
@PJB3005 sure why not

**Comment by clusterfack** [comment]
We might be able to do some REAL thermals that show up as red blobs when they are out of your vision, but normal when they are in your vision, that require no updates.

Oh fuck we could probably do the same to make updates really efficient for all the specific hud types.

@DrCelt Yes some kind of UV glasses or something

**Comment by ghost** [comment]
@clusterfack Yeah, HUDs were what I thought too.

**Comment by 9600bauds** [comment]
Clothing plane to make people nude on-demand

**Comment by clusterfack** [comment]
Yes, would be easy

**Comment by clusterfack** [comment]
Nude vision glasses, science's newest innovation

**Comment by 9600bauds** [comment]
Hair plane to make people GAL-O on demand

**Comment by 9600bauds** [comment]
Is it possible to apply planes over HTML interfaces and such? We could make colorblindness or noirvision affect wire hacking by  naming all the wires "wire" and leaving the color only on the font color, then apply colorblindness/greyscale over the whole window
Plus assistants arguing over the name for each color tone ("wtf is navy blue that's dark blue")

**Comment by 9600bauds** [comment]
Parallax plane?

**Comment by clusterfack** [comment]
Parallax is already heavily using planes, it's the primary reason I know what planes can do and not do

**Comment by Durgen** [comment]
> That one tool that engineering has that everyone has seen before but nobody knows the name of.

T-ray scanner?

**Comment by clusterfack** [comment]
OH FUCK YEAH AI CAMERANETS

**How to**
Just like the way europa lights works, give a darkness overlay image to everything. Attach a lighting object/image on the same plane to every camera on that plane and then the camera vision cone will light up the surrounding area just like europa lights.

It'd be fucking awesome.

**Comment by PJB3005** [comment]
> Is it possible to apply planes over HTML interfaces and such?

Not directly no.

**Comment by Blithering** [comment]
Some kind of airport x-ray scanner for sec? Predator vision? Predators themselves?

**Comment by PJB3005** [comment]
Spessclifs maybe? https://github.com/tgstation/tgstation/pull/19660

**Comment by Blithering** [comment]
Proper stairs?
