### ISSUE TITLE
You can't hear Jukes inside the salvage shuttle

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#11236]
#### Description of issue

You can't hear the juke's music playing inside the pirate/salvage shuttle
#### Difference between expected and actual behavior

expected: being able to hear, since i am not deaf and i can hear people talking just fine
actual: no music, only the silence of deep space
#### Steps to reproduce

bolt a juke in the salvage shittle, turn it on
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
> Issue name

Absolutely savage

**Comment by jknpj** [comment]
_¯\_(ツ)_/¯_

**Comment by FudgePucker** [comment]
I don't know how much has changed sense shuttle datums.
Possible problem one: the jukebox and media system works off of areas  you can't hear a juke box two turfs away if its in a different area, but you can hear it all the way down the hallway if its the same area. The salvage shuttle might have some area fuckery.
Posible problem two: you took the DJ station jukebox. It is preset up with the radio transmitter in the back. You listen to the sound system on the station, not the jukebox.

**Comment by jknpj** [comment]
I tried both scenarios. In the first, if you use the station jukebox you'll be able to hear if it is docked in the asteroid, not in space or others locations like the goonecode sat.

If you take not only the DJ sat jukebox, but also the radio transmitter and and setup your own DJ Shuttle, people will be able to hear it from the station but since you can't install sound systems inside the salvage shuttle, you hear nothing.

**Comment by Kurfursten** [comment]
There's a simple explanation for this.

You may or may not realize that when a jukebox is linked to a transmitter, it doesn't play locally, only through the transmitter. So for example if you link the bar juke to the station transmitter, it will no longer play in the bar (which does not have a sound system unless you build one).

Unlink it

**Comment by ComicIronic** [comment]
So not a bug?

**Comment by jknpj** [comment]
Nope, you still can't hear a regular jukebox if you're not docked in the asteroid

**Comment by Kurfursten** [comment]
The asteroid? Now that's truly mysterious. Which juke did you use in testing? One of the ones from the station?

One might imagine that it would play on the zlevel the juke originated from or where the ship originated but on a totally unrelated Z level? That's odd.

**Comment by jknpj** [comment]
Station's juke. Unwrenched and wrenched while docked in the roid and it worked
