### ISSUE TITLE
Remove Booing and ghost chair spinning

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#11239]
#### Description of issue

Booing is very vague and I don't think it's logged? In all instances where booing is necessary for something(hey I'm in my body etc) we can add a function where a ghost can activate it to notify someone nearby. Booing really doesn't do anything useful for this game.
#### Difference between expected and actual behavior

Booing I expected  to be spooky.

Instead it can be used to signal antags, lead living players to dead bodies, etc.
#### Steps to reproduce
1. Be alive
2. Get killed by gibtonite
3. Boo paramed to get his attention
4. Lead him to your dead body
#### Specific information for locating

It's booing and spinning chairs. We're familiar
#### Length of time in which bug has been known to occur

 Time immemorial
#### Server revision

Time Immemorial
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ x] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Wizardcrying** [comment]
YES PLEASE.
This puts ghosts back to where they should have been: pure spectators.
Being a ghost was originally to allow you to freely move around in the world and spectate whoever and wherever you want.
Ghosts have been using their powers in ways that actually affect the round and it's been leading to a lot of bullshit.

**Comment by clusterfack** [comment]
No way, you monster

**Comment by nuklearcellphoneg** [comment]
Discussion, Gameplay/Balance, Controversial

**Comment by nuklearcellphoneg** [comment]
:^)

**Comment by 9600bauds** [comment]
The rules are perfectly fine in this aspect: You can flicker lights in Medbay to nag people into checking the CMC. You can't flicker lights to play 20 questions with the living.

Removing poltergeist abilities because people COULD rarely use them for stuff against the rules is like removing emotes because someone COULD abuse them while mute. It's stupid and I cannot support the idea.

**Comment by nuklearcellphoneg** [comment]
At the least they must be logged, otherwise it's unfair to enforce the rule. It wouldn't bother me if spin chair had a cooldown.

Not to mention the murderboner vamp HoS followed by twenty spinning chairs who gets valided, but because whoever killed the HoS didn't ask anything aloud, nobody knows any better. The guy who kills the HoS didn't know they were a traitor, they come up with a BS reason for knowing, then they avoid the ban: No boo logs to back it up either.

**Comment by Wizardcrying** [comment]
> COULD rarely use them for stuff against the rules

more like frequently.

**Comment by 9600bauds** [comment]
When's the last time a guy dragged an office chair around playing Pokemon GHOST?

**Comment by Wizardcrying** [comment]
That's the more extreme side of it; the frequent offences are the things such as antag signalling.

**Comment by kernikov** [comment]
@9600bauds is that a joke, because that's exactly what happened

**Comment by 9600bauds** [comment]
Everyone caught up to it immediately, I mean the time before that
Basically, "how often does this happen?"

**Comment by Killette2** [comment]
>not pokemon GHOST

Pun missed...

**Comment by Wizardcrying** [comment]
there's been a lot of bullshit recently regarding it

**Comment by nuklearcellphoneg** [comment]
1) See person
2) Chairs are spinning around them
3) Search their office
4) Find dead body
5) Revive dead body
6) Hey that person killed me
7) Kill person

?????

**Comment by kernikov** [comment]
I understand why the chair spinning needs to go.
I don't understand why the lightflashing needs to go.
I don't understand why there's a PR already when it's been less than 8 hours and there's a discussion.

**Comment by Wizardcrying** [comment]
The PR's not intended to be merged ASAP.
edit: It also doesn't remove chair-spinning, either.

**Comment by SacredAtom** [comment]
No Boo is the best to meme people, shouldn't have to remove it because a few recent incidents

**Comment by kol1th** [comment]
What's the difference between using LOOC to say where your body is, and using ghosts?

**Comment by 9600bauds** [comment]
I could easily log poltergeist abilities but if chairspin is logged it would result in a pretty bloated log file.

**Comment by Wizardcrying** [comment]
> No Boo is the best to meme people

@SacredAtom What did you mean by this?

**Comment by chatsonf** [comment]
You mean "What did you meme by this?"

**Comment by Intigracy** [comment]
One or two people being shitters with something isn't cause to remove it for everyone.

This is exactly what TG did in this situation rather than banning the offending parties when they were caught.

**Comment by nuklearcellphoneg** [comment]
It happens a good bit and there are no logs to prove it.

Ghosts booing lights around an antag and spinning any chairs they get near isn't enough to make them valid, but it is a big red flag to other players; I should probably avoid that person. I should maybe check their office. Even if players don't act in direct and obvious ways, they can do so subtly.

Ghosts could also lead someone to their dead body by booing and spinning chairs without the living character ever asking questions, and simply standing between chairs and waiting for the chair closer to the dead body's location to spin. There's no way to prove this happens without, say, video proof.

And I don't feel comfortable banning folks on eye witness testimony.

**Comment by Wizardcrying** [comment]
The problem is people can use people getting haunted as a secret reason to avoid/investigate them without getting caught.
You can say nothing and do nothing loggable to have your meta pretty hard to detect.
You can't get hard proof that this guy used these ghosts to metagame, because it's insanely deniable.
Chairs can still be rotated w/ my PR because it's pretty unambiguous that there's meta going on.

@nuklearcellphoneg beat me to it.

**Comment by nuklearcellphoneg** [comment]
A comparable example is if two people are metacommunicating using a voice chat or something; Players A and B.

A gets killed by a ling. A tells B. B does not save A's body or kill the ling, instead, they avoid the ling like the dickens. You can't prove anything, but B has a very definite advantage with no IC or loggable indications.

**Comment by 9600bauds** [comment]
This is getting blown way, way, way out of proportion to be quite honest

**Comment by Killette2** [comment]
I think we need to remove ghost, once you die you stare at a blank screen until you get revived. Deadchat, ghost eyes, and ghost ears, all have to go too.

**Comment by 9600bauds** [comment]
By the way, in ANY case, chairspin is a lot more meta than Boo

**Comment by nuklearcellphoneg** [comment]
And more abusable since there's no cooldown. Seems like a correlation to me. :^)

**Comment by Intigracy** [comment]
I see the correlation between someone abusing it and suddenly it being an issue after years of use, yeah.

**Comment by AI-Is-Rogue** [comment]
@Killette2 Realistic  :+1:

**Comment by chatsonf** [comment]
this topic reminds me a lot about gun control
"guys look (insert incident here) happened we need to (insert feature/amendment removal here)"
"It's an isolated incident, (insert incident here) doesn't happen often enough that we need to go and (insert feature/amendment removal here)"

**Comment by Wizardcrying** [comment]
The reason why it's become an issue is because it's somewhat similar to, say, metagaming relationships.
There's probably people who don't play it stupid and get away with it for years, possibly indefinitely.
But no one ever notices that until the metagamers in question fuck up.

You start to notice many simple, odd occurrences. Those small, infrequent occurrences start to become correlations, and you see that the relationship always existed right under your nose but you never bothered to look down.
Ghost metagaming, likewise, has been quite silent. The rule hasn't been enforced (because it's nigh-unenforceable) and ghost metagaming has been accepted as fact. However, due to the recent issues regarding ghost powers, it's become more obvious that they are a problem waiting to become even worse.

**Comment by nuklearcellphoneg** [comment]
> suddenly it being an issue after years of use, yeah.

Oh it's been an issue for ages. I know I've used it myself years ago when faced with an antag to say, 'Okay I need to back off and get prepared, this guy's probably going to try to kill me because there are a lot of angry ghosts around him'.

The reason I brought this issue up is because the same thing got brought up to me by three people and my initial response was, 'whatevs, go get the logs and if they were using ghost to meta they'll be banned'

And there was of course this recent ban request with Xevonix: http://ss13.moe/forum/viewtopic.php?f=22&t=2704

In the request, these are the only logs actually relating to xevonix's ckey:

> "[11:18:42]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@227,265,1) Deadsay: drones, "goddamnit robert""

v v v By far the most damning one

> "[11:23:24]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@227,272,1) Deadsay: spooks, "really blows that ive been trying to signal people all round but none of them are smart enough""

^^^ By far the most damning one

> "[11:23:43]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@227,268,1) Deadsay: mutters, "robert was so close though""
> 
> "[11:56:44]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@260,295,1) Deadsay: drones, "if how they acted towards me in the past hasnt solidified a reasoning to not draw their character in the past then this for sure has""
> 
> "[11:56:48]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@260,295,1) Deadsay: complains, "lol""
> 
> "[11:42:46]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@258,297,1) Deadsay: spooks, "ROBERT PLEASE""
> 
> "[11:44:47]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@261,298,1) Deadsay: cries, "ROBERT PLEASE""
> 
> "[11:44:50]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@261,298,1) Deadsay: drones, "YOU STOOD ON TOP OF IT""
> 
> "[11:46:59]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@260,299,1) Deadsay: drones, "LOOK UNDER THE SHIT""
> 
> "[11:48:31]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@239,265,1) Deadsay: drones, "robert please...""

There is zero indication here that Xevonix is in any way indicating the location of their corpse aside from the signalling line. However:

> "[11:39:18]SAY: Robert Mann/Pvak (@250,247,1) As Galactic Common : Ok ghost"
> "[11:39:26]SAY: Robert Mann/Pvak (@250,247,1) As Galactic Common : Guide me to your body"
> "[11:39:51]SAY: Robert Mann/Pvak (@251,246,1) As Galactic Common : Rotate the chair"
> "[11:39:54]SAY: Robert Mann/Pvak (@251,246,1) As Galactic Common : To the direction"
> "[11:40:11]SAY: Robert Mann/Pvak (@251,246,1) As Galactic Common : North="
> "[11:40:26]SAY: Robert Mann/Pvak (@266,261,1) As Galactic Common : Still north?"
> "[11:41:17]SAY: Robert Mann/Pvak (@256,293,1) As Galactic Common : Uh where?"

Now, because of this, and only this, can we correlate the two.  However, you are making some assumptions. For example, if two dead players are in the same location, and one utilizes booing and chairs to lead someone to their body, do you punish both dead players? How can you indicate which to ban and which not to ban?

**Comment by nuklearcellphoneg** [comment]
Aside from the IC chat where pvak asks questions, wherein his timestamp directly precedes Xevonix's comments on how close he was, there's no real evidence that Xevonix that they had done something.

Now, here's the thing. Xevonix has a level or notoriety and they are very experienced with the game, so the assumption is that they are aware that what they were doing was wrong. If this were the case, why would Xevonix be so stupid as to say...

> "[11:23:24]SAY: Yahir Kepplinger/Xevonix/(Yahir Kepplinger) (@227,272,1) Deadsay: spooks, "really blows that ive been trying to signal people all round but none of them are smart enough""

...unless they legitimately believed there was nothing wrong with it. For example, if myself and Pomf were metagaming, and Pomf died, and he told me in an outside chat that he was hidden in the locker in dorms, he would not say, 'thank god i told bob dylan where my body was', as there is no inherent value in this- this is conversation.

The implication I get from this is that it does happen quite often, and the only way to really be aware that it's happening is by staring directly at it while it's in progress.

**Comment by Kurfursten** [comment]
The kind of people who see flashing lights and automatically assume antag are the same people who make chloral autoinjectors 5 minutes into the shift.

Next up, PR to remove See Ghosts rune, Manifest Ghost rune, Astral Journey rune, Orb of Scrying, and posibrain pinging.

**Comment by chatsonf** [comment]
The main problem with this is removing rotating chairs and boos from ghosts will only remove a few fun features (spinning people wildly in chairs in the escape shuttle, annoying certain people by getting a bunch of ghosts to boo the same person) and will not stop people from metagaming, if people desire to metagame they will do it one way or another, whether it is in-game or out of game.

If you claim that it was an accident and yahir didn't believe he was actually metagaming, then this isn't due to the ghost's abilities and more due to the lack of clarity of the rules.

And to add onto what kurfurst just said, acting on rotating chairs and flashing lights is less a metagaming issue and more of a powergaming one.

**Comment by nuklearcellphoneg** [comment]
> Next up, PR to remove See Ghosts rune, Manifest Ghost rune, Astral Journey rune, Orb of Scrying, and posibrain pinging.

How silly; Those are antagonist abilities.

> posibrain pinging.

Except this: No meta information can be conferred through this. All it does is create a completely brand new character with no knowledge of any events, and if they chose to use information acquired while dead/observing, it could be very easily traced back to them.

And tbh I'm not recommending you actually remove the abilities, because that's silly and no one would ever agree to that, but rather than recommend what I think someone else should code, I think it's better to present an awful option and for someone else to come up with a viable solution, and since it's their solution, they'll be much more willing to code it. Like #2375 and #4899, this exists to provoke people into aggressively listing out pros and cons to this segment of gameplay.

:^) 

> If you claim that it was an accident and yahir didn't believe he was actually metagaming, then this isn't due to the ghost's abilities and more due to the lack of clarity of the rules.

The rules are clear- however, people get away with this more often than not because, again, there's no evidence. Paramedic wordlessly follows chairs and blinking lights to a body, no one knows, and there's no trace. Guy gets killed, they're pissed at the antag, they haunt him; living player approaches, sees this: Hmm I wonder why that ghost is pestering this guy so hard. U-TURN, no evidence of anything.

**Comment by Kurfursten** [comment]
For the last two years I've thought the blinking lights and terrible hauntings that followed dangerous mass murderers were part of the ambiance that made the game interesting and added a sense of dread to greentext stories like

> Working in virology
> Lights begin blinking
> Hear a knocking on the glass outside
> APC blinks blue for a moment
> Your hair stands on end
> The cycling airlock begins to shift...

That's the kind of atmosphere you can't code.

Although when you think about it, if the station is quiet and no one is talking on radio all of a sudden, and you ask over radio where everyone is, then you avoid someone you see in the halls because no one's talking - isn't that kind of unlogged metagaming because you have reason to believe there's a murderboner based on the atmosphere alone? It's the same paranoia logic as running from someone who has one ghost blinking their lights, or running from someone because they keep moving within one tile of you.

**Comment by ghost** [comment]
I think removing it is bad, sometimes you're dead and the paramedic is too busy playing the arcade machine to check the monitor. So you boo him once, flash a few lights and he checks the monitor.

Just find a way to make flashing lights, booing and chair rotations loggable to find people if they abuse them in the future.

**Comment by jknpj** [comment]
How else am i supposed to annoy the botanists until they call the chaplain and trash all diona seeds?

**Comment by Killette2** [comment]
I grow dionas like a good boy, but if I'm busy fuck off and wait or I'll unscrew the light switch.

**Comment by chatsonf** [comment]
> people get away with this more often than not because, again, there's no evidence. Paramedic wordlessly follows chairs and blinking lights to a body, no one knows, and there's no trace. Guy gets killed, they're pissed at the antag, they haunt him; living player approaches, sees this: Hmm I wonder why that ghost is pestering this guy so hard. U-TURN, no evidence of anything.

I would bet that as many people boo and rotate chairs around the antagonist that killed them, there are as many who just do it to random people to simply mess around. Ghosts haunting players during the round is unreliable to tell who the antag is because of this.

**Comment by 9600bauds** [comment]
this has more or less been addressed and the drama died down
