### ISSUE TITLE
Shield generators stay on, and can't be turned off when they run out of power

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#11231]
![o](https://cloud.githubusercontent.com/assets/19157295/17312934/c1ec3e52-581c-11e6-842f-427f5190ed7b.png)

Cutting the wires underneath the shield gens also did not help. Once they ran out of power, they seemed to be permanently stuck in the on position.

**Comment by AlphaBuffalo** [comment]
This is a really old bug that no one has addressed, and probably will never address

**Comment by Durgen** [comment]
can we outsource bug fixing to india?

**Comment by PJB3005** [comment]
Didn't I fix something like this?

**Comment by kol1th** [comment]
I'm fairly sure they use an internal battery level. I've had them run out while the area was still powered, as well.
