### ISSUE TITLE
Have to Double-Click for a click to count.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11246]
(WEB REPORT BY: slashbolt REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> If I want to interact with anything in the field, I have to click twice for it to register.
> 
> What you expected to happen
> For one click to be detected.
> 
> What actually happened
> I have to click twice for it to be detected.
> 
> Steps to reproduce if possible
> Be me
> Click on Ciggies in game
> Realize you have to double-click on ciggies.

**Comment by Exxion** [comment]
#11206

**Comment by kol1th** [comment]
![image](https://cloud.githubusercontent.com/assets/16979948/17355598/7def9678-5906-11e6-9374-06d7c59beb33.png)
