### ISSUE TITLE
Targeting mode does not count vehicles as "moving"

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11241]
![2016-08-02_21-16-54](https://cloud.githubusercontent.com/assets/6526157/17349716/7bf4379e-58f6-11e6-9d39-14d242d5170e.gif)

**Comment by Exxion** [comment]
Oldcode is a joke

Please use events

Except the move event is actually slightly fucked right now but it's better than however the fuck this works

**Comment by SECBATON-GRIFFON** [comment]
relaymoving bypasses the event too
and to add to that, check_fire() fails on the test projectile to_bump() stuff if the mob has something dense on its tile (like, a vehicle) and was the thing causing the bug
