### ISSUE TITLE
No cooldown on rune activation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11242]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 304498dcce2a50f8ad9e218e020636c55c8d42c6 
> 
> General description of the issue
> Jerkoffs can and do spam tear-reality/manifest runes 10 times per second and make goonchat lag like hell
> 
> What you expected to happen
> One activation max per second or two
> 
> What actually happened
> TOXIMSROSHAMELONS ad nauseum.
> 
> Steps to reproduce if possible
> Double-click a rune and behold it activating twice in a brief period.

**Comment by DeityLink** [comment]
fixed thanks namely to duplicate messages appearing with a multiplier
