### ISSUE TITLE
Miscellaneous photograph bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11257]
(WEB REPORT BY: somhuan REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c246201cd4fa9c35fa42145a33488f45b49e72e6 
> 
> General description of the issue
> Tables and doors do not show up when I take pictures.
> 
> What you expected to happen
> I expect doors and tables to show up when I take pictures.
> 
> What actually happened
> The doors and tables did not show up on the picture I took.
> 
> Steps to reproduce if possible
> Be an AI, take pictures of said objects.

**Comment by kol1th** [comment]
That is definitely not the only problem with cameras.

**Comment by Exxion** [comment]
It is much more mystifying than the clothes bug, though

**Comment by clusterfack** [comment]
I would expect the reason to be that the typepaths are put in the 'directional' list when they are not directional. When you make an icon that has an invalid direction it shows up blank (fucking THANKS byond), which would cause this. I can already see tables are in this list.

**Comment by kol1th** [comment]
Oh, when you take a picture of say, a human in a hardsuit, they're a naked human with the SOUTH dir. Seems the same way for all mobs.

**Comment by Exxion** [comment]
Them always facing south is intentional
I think
At least it's always worked that way
But the clothes appearing under them is definitely not, and nobody's quite sure what caused it

**Comment by 9600bauds** [comment]
The "naked people in pictures" bug was caused by hands, unless there were two different ones

**Comment by Exxion** [comment]
Yeah, we know that NOW, but not when I said that

Anyway, is this fixed?

**Comment by Shadowmech88** [comment]
This is fixed.
