### ISSUE TITLE
Deff feature request: Two janitors??

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11258]
There's two custodial closets on Deff, both full of supplies.

Is it unreasonable to think, that JUST ON DEFF, since there's enough to go around, that there can be two janitors?

Perhaps some sort of way to show off which closet is for which janitor? I'd certainly like someone to help me janitor things up. Lots of shit to clean up in maintenance on that map.

**Comment by Megamaw** [comment]
@Duny- do you have any feedback? you did make two jani closets, which i do appreciate. but r/n the second janitor has to be made by an HoP.

**Comment by Duny-** [comment]
There are two closets and two spawn points, afaik adding another janitor slot isn't done with mapping; so I don't know how it's done.

**Comment by PJB3005** [comment]
Should be doable by just overriding the job slots of the janitor job.

**Comment by Probe1** [comment]
They're both for janitors tho.
