### ISSUE TITLE
LITERALLY UNPLAYABLE

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#11255]
![](http://i.imgur.com/uAfIxx1.png)

**Comment by 9600bauds** [comment]
uh
what am I looking at

**Comment by PJB3005** [comment]
The new player menu isn't symmetrical.

**Comment by 9600bauds** [comment]
![ruler](https://cloud.githubusercontent.com/assets/6526157/17381294/8d2a4732-59a1-11e6-9e43-a1e9e2caef8a.jpg)

**Comment by ScrambledSteak** [comment]
![03649_1](https://cloud.githubusercontent.com/assets/19224578/17389457/0a486176-59df-11e6-94f8-50c837bed137.gif)

This is absolutely disgusting. It must be rectified immediately.

**Comment by uazuaz** [comment]
what about THIS then

![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/17396930/f1731a7c-5a35-11e6-84a1-8a8fc5fe019c.png)

we need 2 different logos, one done by an even and one done by an odd number of tiles, so they can be adapted for any type of hallway.
