### ISSUE TITLE
Side windows issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11253]
#### Description of issue

under certain circumstances the side window can't let people or items pass trough their tile.
for example, if you want to push this canister against the wall from right to left you can't, because the canister doesn't go further than this. 

![01](https://cloud.githubusercontent.com/assets/6170726/17376260/1e536e38-59b5-11e6-86b6-395dddb15812.png)

but if you push on the same tile from above to below, you can

![02](https://cloud.githubusercontent.com/assets/6170726/17376265/247d2f74-59b5-11e6-95d3-0f24d115d25d.png)

note that this happens only when the item is pushed, not when pulled.
if there are 2 people walking one  against the other on a tile that have a side window, for example like this corridor,  they "bump"  even if them both have helpful intent, and they can't pass through each other as intended. this was a big issue during the dorf fort round that was done today, because people were bumping each other every time they walked in that corridor..

![3](https://cloud.githubusercontent.com/assets/6170726/17375713/7b989db4-59b2-11e6-9223-c391cc69b1b8.png)

update:
this is what happens when you do it against an unfastened window:
nothing when pulled, pushes also the window if pushed.

![ezgif-3230651700](https://cloud.githubusercontent.com/assets/6170726/17377557/8292991e-59ba-11e6-808e-de5145388269.gif)
#### Steps to reproduce

push something on a tile with a side window
walk against another person, both on help intent, on tiles with side windows
#### Length of time in which bug has been known to occur

noticed with canisters days ago, today was a mess during dorf fort round
#### Server revision

c246201cd4fa9c35fa42145a33488f45b49e72e6 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by uazuaz** [comment]
update:
this is what happens when you do it against an unfastened window:
nothing when pulled, pushes also the window if pushed.

![ezgif-3230651700](https://cloud.githubusercontent.com/assets/6170726/17377557/8292991e-59ba-11e6-808e-de5145388269.gif)

**Comment by PJB3005** [comment]
Would be fixed by #11234

**Comment by Shadowmech88** [comment]
None of the described issues happen any longer.
