### ISSUE TITLE
Ghosts don't see attack messages

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11254]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c246201cd4fa9c35fa42145a33488f45b49e72e6 
> 
> General description of the issue
> Ghosts can't see attack messages where someone attacks someone else, or a simple mob attacks a person, but attack sounds still play
> 
> What you expected to happen
> Be able to see attack messages
> 
> What actually happened
> Can't
> 
> Steps to reproduce if possible
> Observe, try to watch a fight

**Comment by clusterfack** [comment]
I think this is because virtualhearers aren't inheriting the sight var from the mobs they are attached to

**Comment by clusterfack** [comment]
I think this is because virtualhearers aren't inheriting the sight var from the mobs they are attached to

**Comment by Sprok0** [comment]
To add to this, ghosts don't seem to get any messages if they come from something that's in darkness

**Comment by Sprok0** [comment]
After a bit more testing, ghosts don't seem to see any attack message type things if they have darkness toggled off

**Comment by clusterfack** [comment]
This should be fixed
