### ISSUE TITLE
Need someone who knows regex.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11260]
Defficiency, and I suspect other stations, have manually edited "layer =" to certain values; which messes with #11183 and causes bugs which I cannot fix properly by hand.
If anyone knows how to remove all instances of layer = x in the maps (which I believe can be done by regex), please help me.
Thanks.

EG: 
![unfixable](https://cloud.githubusercontent.com/assets/7193289/17386227/6c854bc0-599d-11e6-9c44-7e4ce8bdd83e.png)

This is present on defficiency, and I could have sworn I tested this specifically. I did, as cryo is now set to "layer = ABOVE_WINDOW_LAYER", however defficiency has it manually edited to layer = 4 in the map file.

**Comment by gbasood** [comment]
Or you could just steal the regex that's part of the Travis CI check for pixel_x/y and modify it like the scrubs we are

**Comment by clusterfack** [comment]
Just learn regex

**Comment by ghost** [comment]
gotem boys
