### ISSUE TITLE
Ghosts can turn on Floodlights, and it shows their name

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11268]
(WEB REPORT BY: ch0c0latem00se REMOTE: 172.93.109.202:7777)

> Revision  d8404d73dfc054faa56e365e1d2c35c37251c0b2 
> 
> General description of the issue
> Ghosts can interact with floodlights in atmos and on the science stations, when they turn it on or off it shows their name.
> 
> What you expected to happen
> Silly ghost antics
> 
> What actually happened
> META
> 
> Steps to reproduce if possible
> http://i.imgur.com/jOHUGrP.png

**Comment by Exxion** [comment]
Whoever fixes this should also fix #10876

**Comment by Intigracy** [comment]
they should still be able to interact with them, it should just have the same cooldown as using a light switch.

**Comment by NigglyWiggly** [comment]
I assumed this was just an adminghost bug
I had no idea regular ghosts could use it

**Comment by Exxion** [comment]
It's intended that ghosts can use it
But it displaying their name is definitely not intended

**Comment by Intigracy** [comment]
I'm going to wait until #11247 is merged so there's no conflicts.
