### ISSUE TITLE
Balance: Skeleton Speed

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11279]
So, during the time Skeletons were unavailable, there were a few nerfs applied to them. Let's discuss those, now that they matter. Until I get to the one I'd like to discuss, I'll list them for your convenience.
- They cannot eat, drink, or process chemicals.
- They take increased brute damage.

Despite ALL the drawbacks of skeletons, and despite THROWING EVEN MORE onto the pile, someone decided they should move way slower than humans.

Why, may I ask? Without flesh weighing them down, shouldn't they be faster, if anything?

I guess what I'm proposing is that we make skeletons move the same speed as humans, here.

**Comment by Kurfursten** [comment]
Why does a chihuahua move slower than a German shepherd? They don't have muscle mass to move them forward quickly.

**Comment by Megamaw** [comment]
okay, so if we were going that route, without muscle mass how do the skeletons move at all?

it's clearly some form of magic, right?

**Comment by Exxion** [comment]
Let's not pretend skeletons make sense at all

Personally, I'd say give players some time to form opinions about skeletons then decide whether they need fixing/what kind of fixing they need

**Comment by Megamaw** [comment]
that's fair enough. i have several changes i'd like to propose, but you have a fair point.

**Comment by TheFriggenSawbones** [comment]
please let us eat and take chemicals again thats all I want I WANT TO DRINK AT THE BAR

**Comment by Megamaw** [comment]
Drinking at the bar would be nice, just for flavor reasons and shit.

Also we can still get hungry

**Comment by ComicIronic** [comment]
Every time you open an issue about skeletons, we code another skeleton downside.

**Comment by NigglyWiggly** [comment]
Skeletons just being a race of aliens that look like skeletons when

**Comment by Ephx1** [comment]
Skeletons just being a race of reanimated skeletal structures with unknown alien technology when

**Comment by Megamaw** [comment]
aliens that look like skeletons? nah.

any form of justification for reanimation? you have my vote.

**Comment by 9600bauds** [comment]
Them being aliens would be a justification

**Comment by NigglyWiggly** [comment]
I wrote up a big dumb thing in the library about what a Skellington is and it was like, an alien with an exoskeleton and a thin layer of transparent fleshy stuff between the bones, with the organs and veins and shit inside of the bones themselves

**Comment by Megamaw** [comment]
i also wrote some proposed lore a while back in the 'bring skeletons back' issue, but we don't really have any established lorekeepers or anything, so i don't think either of those are going to be official. @NigglyWiggly also made some rad new sprites for skeletons in that issue.

'course, that's probably a little off topic for this issue.

**Comment by ComicIronic** [comment]
I wasn't kidding about the skeleton downside thing, as it turns out.

**Comment by SonixApache** [comment]
crack the ack

**Comment by Intigracy** [comment]
seeing as you made this exact same issue again in #12418
