### ISSUE TITLE
Valves appearing under everything

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#11278]
#### Description of issue

![pllaaaaannneeessss](https://cloud.githubusercontent.com/assets/17928298/17420040/e4fcf164-5a76-11e6-8f87-5c23e0248133.png)
![plaaaaanes](https://cloud.githubusercontent.com/assets/17928298/17420039/e4fbe4b8-5a76-11e6-8c08-97c4d4b23c94.png)

**Comment by Kurfursten** [comment]
✈?

**Comment by Iamgoofball** [comment]
✈ :tokyo_tower: :tokyo_tower:
