### ISSUE TITLE
Default values for code changed when?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11270]
Come on, does anyone really need to load jukeboxes, make minimaps, have guests disallowed, not be an admin, go on a map other than box-tiny, et cetera et cetera who doesn't know specifically how to do this?
I propose we have the defaults be the speedy-compile, and anyone who needs to not have a speedy compile are the people who would know how to make it unspeedy anyway.

**Comment by kol1th** [comment]
What did he mean by this?

**Comment by Exxion** [comment]
He means exactly what he said

**Comment by ComicIronic** [comment]
Sounds good
