### ISSUE TITLE
this whole thing

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11288]
![](http://puu.sh/qqgEA/d02baa0abf.jpg)

**Comment by clusterfack** [comment]
Did you strip out the pipe layers you nerd?

**Comment by Exxion** [comment]
No, those pipes are offset, but not by enough
In fact, they're offset exactly half as far as they should be
I wonder what could possibly have caused that

**Comment by clusterfack** [comment]
It's not 64x64 you nerd

**Comment by ghost** [comment]
I'm pretty sure this is to do with 64x64.

**Comment by Exxion** [comment]
It totally is
The layer visual offsets are half as far as they should be

**Comment by clusterfack** [comment]
The offsets should be handled by pipe code, not by manual editing of offset values

**Comment by ghost** [comment]
_**Should**_ is a funny word.

**Comment by Exxion** [comment]
They are, at least normally

**Comment by clusterfack** [comment]
Well I'll put it on the list
