### ISSUE TITLE
Mechanic's uniform fits fat characters but does not use correct sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11289]
(WEB REPORT BY: higgsbonbon REMOTE: 172.93.109.202:7777)

> 6edf0208ac8e4bea5b596de53e674e0f84eaef6e 
> 
> Put a mechanic's jumpsuit on a fat character. The incorrect sprite will display.
> 
> The normal fat version of the mechanic overalls.

**Comment by kol1th** [comment]
What? Pictures? Is it the pink and black checkered sprite?

**Comment by beesil** [comment]
Fixed by #7519
