### ISSUE TITLE
Skeleton Discussion: Remove 'ACK ACK' speech impediment?

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11287]
It is my personal impression that messages randomly being appended with 'ACK ACK!' is part of what contributes to skeletons being considered a 'meme race'.

Is there any reason that this still needs to be a thing? At least the plasmamen have a speech impediment that makes sense.

**Comment by kol1th** [comment]
nah, skeletons don't make sense anyways.

**Comment by ghost** [comment]
Skeletons shouldn't be in the game anyway

**Comment by Exxion** [comment]
It's part of their charm

But if it's obnoxious, maybe the frequency should be reduced

**Comment by Megamaw** [comment]
i don't think there's anything charming about randomly screaming ACK!, is there?

like, why is it there? if you're going to give them a speech impediment, at least have it make sense, right?

**Comment by ihadtoregisterforthis** [comment]
Appears 25% of the time. It's not even a real impediment, it's a flavor clacking at the end.
I go for keeping it.

**Comment by Intigracy** [comment]
Maybe if you don't like playing as a skeleton you can play as something else.

**Comment by TheFriggenSawbones** [comment]
ack ack should stay

**Comment by Intigracy** [comment]
hey did you know linking the PR in here will show the name of the issue as reference on the PR

#15312
