### ISSUE TITLE
64x64 gives us tiny-ass title screens.

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11286]
I don't know what to say other than uh, wow, did you even test this @PJB3005 ? The title screen takes up like a fourth of the screen.

**Comment by Exxion** [comment]
The lobby screen? Looks fine to me. Could you post a screenshot?

**Comment by kol1th** [comment]
@Megamaw only one or two lobby screens were left unconverted.

**Comment by Exxion** [comment]
Ah

**Comment by PJB3005** [comment]
Which? I was pretty sure I got all of them.

**Comment by kol1th** [comment]
@PJB3005 I was wrong. It seems a majority of them aren't fixed. I don't remember which ones, though.

**Comment by PJB3005** [comment]
I just checked all the DMI files all the icons are the correct size, but `title2` and `title11` aren't opening correctly in DM.

EDIT: `title11` is fine when viewed through a proper image program.

EDIT: `title2` is opening correctly in GIMP, as is `title11` so ???

EDIT: `title2` is opening in TweakPNG and the `zTXt` is intact and contains the DMI data:
![](http://i.imgur.com/vckvfHZ.png)
