### ISSUE TITLE
bug report: Skeletons can still get hungry.

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11280]
#### Description of issue

Hunger meter still shows up for skeletons. Seems to affect skeletons like it would a human.
#### Difference between expected and actual behavior

I kind of expected, y'know, a race not able to eat, to not get hungry.
#### Steps to reproduce

-Be Skeleton
-Wait
#### Length of time in which bug has been known to occur

As long as skeletons have had NO_EAT
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by AI-Is-Rogue** [comment]
They can eat raw meat, and only raw meat. It's a [feature](http://ss13.moe/wiki/index.php/Races#Cons).

**Comment by Probe1** [comment]
Eat your meat buddy.
