### ISSUE TITLE
Meson scanner issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11299]
#### Description of issue

if you are near a supermatter shard wearing a DISABLED meson scanner, you are immune to the hallucinating effect, just like it was enabled.
#### Difference between expected and actual behavior

if disabled, they shouldn't protect you from hallucinations;
they do.
#### Steps to reproduce

wear meson scanner, disable it, go near a supermatter shard
#### Length of time in which bug has been known to occur

noticed it in the last few days
#### Server revision

beec9afaf4c1927d95f7aaf2a230488dccc3e018 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Pretty sure this is intended actually.

**Comment by uazuaz** [comment]
i ahelped when i saw it, dragonbro said me that in his opinion it shouldn't protect you from hallucinations when disabled;
by the way if it's intended you can close this issue, thanks.

**Comment by Exxion** [comment]
There was an argument over whether or not this should be the way it works back when disabling them was first being added, but I don't remember who won

**Comment by uazuaz** [comment]
well, sometimes you need to use a welder near the SME to add emitters for example, but having meson scanner enabled when welding will damage your eyes, so it's convenient to have it protect you even if it's disabled, so i can understand why people want it this way.
if it's intended to work this way it's fine for me if you close this issue.

**Comment by PJB3005** [comment]
For me it's more because mesons scanners make everything look ugly (no lighting anywhere) so mesons protecting but not actually being on is the best of both worlds for me.

**Comment by FudgePucker** [comment]
I am in support of disabled mesons protecting you.

I want to enjoy the glow of a SME with out dealing with hallucinations.

**Comment by ghost** [comment]
> so mesons protecting but not actually being on is the best of both worlds for me.

Should we have other items that are disabled still work, too?

> Shield disabled, so it's not cumbersome but still reflecting projectiles is the best of both worlds for me.
> Eswords disabled so they're not visible but still dealing a lot of damage is the best of both worlds for me

**Comment by FudgePucker** [comment]
Great comparison there Celt.
Exact same thing.

> implying we should listen to the dude who made hypothermia

:^)

**Comment by Probe1** [comment]
Oversight.  get it?

**Comment by Shadowmech88** [comment]
Not only is this probably not unintended, but it makes sense to me that it would be this way. Whatever shielding that is on the lens of the meson scanners to protect you from shard radiation hitting your eyes would be independent from whatever energy the scanners project in order to allow you to see through walls.
