### ISSUE TITLE
RPD issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11298]
#### Description of issue

the RPD's "layers" buttons are now invisible

![layers](https://cloud.githubusercontent.com/assets/6170726/17440826/9903214e-5b2e-11e6-9d05-98c27c3e4f3a.png)
#### Steps to reproduce

use a RPD.
#### Length of time in which bug has been known to occur

noticed just today.
#### Server revision

beec9afaf4c1927d95f7aaf2a230488dccc3e018 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by AlphaBuffalo** [comment]
SIXTY FOUR BY SIXTY FOUR

**Comment by ComicIronic** [comment]
Who gave the RPD a layering picker?

**Comment by AlphaBuffalo** [comment]
It's been like that since a few months after layered pipes were a thing

**Comment by 9600bauds** [comment]
It's been like that since I have memory

**Comment by PJB3005** [comment]
I made it a couple days after layered pipes was merged on GitLab.

**Comment by ComicIronic** [comment]
Pig disgusting power creep.
The pipe layer finally had something unique, and you stole it for the casual crowd.

**Comment by PJB3005** [comment]
If the unique thing is being a complete pain in the ass to use sure.

**Comment by PJB3005** [comment]
Also I just came up with an idea that could make combining pipe planner plus RPD be better than just RPD: if we make the RPD clicking on a pipe planner place at that layer instead of having to select the layer in the clunky RPD menu that'll be amazing.

**Comment by AutismSpider** [comment]
@ComicIronic  it was pain in the ass to use for both cyborgs humans and mommis

@PJB3005 keep it the way it is.

**Comment by uazuaz** [comment]
what if a frame like this appears when you have a RPD in you active hand and you put your cursor on an adjacent tile? so you don't need an option to change layers

![layers](https://cloud.githubusercontent.com/assets/6170726/17456145/818bff64-5bcd-11e6-8252-552d5f265cf0.png)
- the frame horizontal/vertical direction depends on the direction you set for the pipe
- there could be an option to set the layers function as "normal" (how it's now) and "advanced" (with this 1-click frame) for people who prefer the old way

## OR

you could create an unique "Advanced RPD" with this function that's Chief Engineer exclusive, and use that as the antagonist objective instead of the regular RPD.

**Comment by SysadminJeroen** [comment]
That frame would save me a lot of time if I had the option for that.

**Comment by PJB3005** [comment]
How about IF you have both a pipe planner and an RPD you can do it like that @uazuaz, sounds fair no?

**Comment by uazuaz** [comment]
@PJB3005 
that could also work, at least when you're near atmospherics, because the pipe planner doesn't fit in backpacks. it could also be slightly changed to be put on the floor just clicking an adjacent tile, instead of dropping them only.
anyway, i still think that an Advanced RPD for the CE, replacing the RPD objective for antagonists, is a good idea.

**Comment by PJB3005** [comment]
I'm not sure about adding another objective for traitors to steal from the CE.

**Comment by uazuaz** [comment]
ah right, there are blueprints and advanced magboots as objectives already.

**Comment by AutismSpider** [comment]
blueprints mag boots his/her jump suit and the belt pops up some times

**Comment by DamianX** [comment]
CLEARLY no longer the case
CLOSE IT
