### ISSUE TITLE
Language + Cloning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11293]
(WEB REPORT BY: megamaw REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 04de793875b318309ece858e729616a868837682 
> 
> General description of the issue
> Cloning removes any racial languages.
> 
> What you expected to happen
> To keep languages after cloning.
> 
> What actually happened
> CLACK CLACK LACKA CLACKA
> 
> Steps to reproduce if possible
> be skeleton
> die
> get cloned

**Comment by Exxion** [comment]
I'm pretty confident this doesn't happen with vox, at least (raiders excepted)
Is it unique to skeletons?

**Comment by kol1th** [comment]
Yeah, skeleton bug.

**Comment by Intigracy** [comment]
skeletons clearly have too many bugs, let's remove them again.

**Comment by ghost** [comment]
Could not reproduce
