### ISSUE TITLE
CAPS are not FLIPPED on the player's sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11300]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 307543b7b5b206028421a2ed3336f6ebed270e6a 
> 
> General description of the issue
> Ok you know those shitty caps you get from the vendor? You're supposed to be able to flip them backwards. You get the message, but the on character sprite remains the same. Its been like this for quite some time.
> 
> What you expected to happen
> to have a sick backwards cap
> 
> What actually happened
> it did not flip
> 
> Steps to reproduce if possible
> get a cap and try to flip it

**Comment by kol1th** [comment]
64x64 probably

**Comment by Exxion** [comment]
He just said right there that it had been that way for quite some time

**Comment by kol1th** [comment]
It worked fine when I was an assistant yesterday.

**Comment by TheFriggenSawbones** [comment]
it didn't work before 64x64

it worked at some point

**Comment by nervere** [comment]
They flip fine now. Testing done by @Inorien - thanks!
