### ISSUE TITLE
RPD Layering Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11305]
(WEB REPORT BY: hoborobo REMOTE: 172.93.109.202:7777)

> Revision
> 1686bb32ec200739880084d750cc464b91ba6359
> 
> General description of the issue
> The RPD no longer displays layering options for pipes.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ComicIronic** [comment]
Duplicate.
