### ISSUE TITLE
Heaters/Coolers store gas within themselves, causing inaccuracies with connected pipe systems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11307]
(WEB REPORT BY: bobda REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1686bb32ec200739880084d750cc464b91ba6359 
> 
> General description of the issue
> Heaters/Freezers appear to store air within themselves as they do their job, this leads to canisters they are connected to not updating with the correct temperature.
> 
> What you expected to happen
> If the freezer indicates a gas is say 80K, the canister it is cooling is 80K
> 
> What actually happened
> The canister desyncs with the freezer and has to be unwrenched/wrenched to update, it ends up being 82K~
> 
> Steps to reproduce if possible
> 1. Have a single freezer, connector and canister of whatever and set it up.
> 2. Set the freezer to cool to whatever.
> 3. Once it gets there, unwrench and wrench the canister and behold the freezer status display as the gases update.

**Comment by ghost** [comment]
this is a really annoying 'feature'. If you actually want to cool to a specific heat, you have to keep wrenching/unwrenching and slightly decreasing the temp of the freezer.

**Comment by BobdaBiscuit** [comment]
I've done some tests and forcing the pipe net or whatever to update via looping volume pumps makes the freezer/heater actually be accurate.

That however needs the gear and space to setup.
Toxins being moved to atmospherics when?

**Comment by PJB3005** [comment]
The internal buffer of a feature, the problem is that the temperature differential to trigger a network update is set at 1 Kelvin which is too damn high.

**Comment by BobdaBiscuit** [comment]
Fucking rip, can anything be done about it since I'm not a codefag?
.10 kelvin or something would be fine I'd think, even lower if possible.

**Comment by PJB3005** [comment]
Yes it's a piss easy change of a couple magic numbers.

**Comment by BobdaBiscuit** [comment]
Also, elder autism knowledge here that I've discovered if you need precise temps with the current system.

Disconnect the filled freezer/heater from the pipenet and it will be accurate, then pump the contents into a portapump when done.
