### ISSUE TITLE
Screen froze for a minute while my character kept moving, and then turned black with no UI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11304]
(WEB REPORT BY: spurdospardefug REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1686bb32ec200739880084d750cc464b91ba6359 
> 
> General description of the issue
> Entered bar to begin work, the screen then froze for around a minute while chat and sounds functioned normally. Then the game screen turned completely black and I was unable to do or see anything, even my UI.
> 
> What you expected to happen
> Nothing out of the ordinary.
> 
> What actually happened
> Unable to play the game.
> 
> Steps to reproduce if possible
> Unsure, might be a problem with my laptop and the new sprites.

**Comment by ComicIronic** [comment]
Sounds like Byond to me.

**Comment by DamianX** [comment]
doesn't happen anymore
