### ISSUE TITLE
Lazarus Injector + Capsule on simple animals

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11309]
Okay, so the pet lizard for the janitor, Wags His Tail died this round. I revived him with a lazarus injector. After this, I was unable to use a lazarus capsule on him.

Does it only work on hostile mobs?

Carrying my lizard buddy around is a pain in the ass, especially since I can't drag while on the janicart, nor can I pick him up like I can pick up a Diona.

**Comment by ScrambledSteak** [comment]
Use any intent other than help, drag his sprite onto yours, put him in your pocket

lizard friend

**Comment by Kurfursten** [comment]
This is WAD, not a bug. The mobcapsule code explicitly checks to see if the mob is a child of mob/living/simple_animal/hostile - in other words, they could have designed it to accept any simple_animal but chose not to.

You can still feature request it though.

**Comment by Megamaw** [comment]
yeah, feature request then. no reason not to be able to be able to capsule pets, I think.
