### ISSUE TITLE
Apiculture book has error graphics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11303]
(WEB REPORT BY: higgsbonbon REMOTE: 172.93.109.202:7777)

> 1686bb32ec200739880084d750cc464b91ba6359 

http://puu.sh/qr6AB/372c8e0091.jpg

**Comment by NigglyWiggly** [comment]
The fuck?
Since when do we have an error icon in the book dmi?

**Comment by NigglyWiggly** [comment]
Wait who the fuck added that?
We already have an icon in the library dmi with no name so that unnamed shit gets it and it was used for botany stuff.

**Comment by NigglyWiggly** [comment]
Okay so apparently Arthur added an OOPS state for some reason and now the switch to 64x deleted the old book icon because they both had no state name. 
Okay.

**Comment by DeityLink** [comment]
Image is gone, was this about the book's sprite, or the images inside? either way it should be fixed by now, I saw the book just fine recently.
