### ISSUE TITLE
Inhands were overriden again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11311]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1686bb32ec200739880084d750cc464b91ba6359 

@Justsumbody broke inhand.dmi's with the tg instrument pr and they need to be repaired

**Comment by Exxion** [comment]
I can't reproduce with blood-stained items
I can reproduce with an esword, though
Eswords appear to no longer ever have an inhand

**Comment by ComicIronic** [comment]
Love bug reporters giving you a proper report and not just their assumptions about what happened.

**Comment by clusterfack** [comment]
Fixed with facts

**Comment by JustSumBody** [comment]
Whoops
I double checked in the IRC when I was doing this since it was my first time touching .dmi's, but apparently there was something about "Byond tools" I never knew about.

**Comment by Exxion** [comment]
Fixed by #11353
