### ISSUE TITLE
Cyborg Waitress Sprite has inconsistent colors

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#11318]
From the West/East sprite, what I assume is a tie is a brighter red than what it is for the south sprite, which is a duller red.
![untitled](https://cloud.githubusercontent.com/assets/6224074/17458640/994ec65e-5be6-11e6-8347-62eac3246ce5.png)

**Comment by kol1th** [comment]
Wew.

**Comment by Ephx1** [comment]
This is a VERY important issue you pleb.

**Comment by SkowronX** [comment]
If we had priority tags I wonder how many "Low"'s there would be.

**Comment by Exxion** [comment]
I'd add [OH GOD IT'S LOOSE] but I don't want to  lose collab status after only like two days
