### ISSUE TITLE
New codebase standard: No more mapping variables.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11328]
Mapping variables other than:
- Dir

and, debateablely:
- Pixel_x
- Pixel_y 

Should not be accepted in new PRs. I'll work on removing every single other one later. Discuss.

**Comment by Megamaw** [comment]
how though

**Comment by ghost** [comment]
@Megamaw how not?

**Comment by Exxion** [comment]
`pixel_x/y` have their places as map variables, but they're currently not just used in those places

@Megamaw He just means varedited instances on the map

**Comment by ghost** [comment]
@unid15 why did you thumb this down?

**Comment by unid15** [comment]
Forbidding mappers from changing pixel_x/y is not "debatable" at all. It's a big fat huge absolute NO.

I think variables like "name", "desc", "pixel_x/y", "dir" and some others (basically those that don't affect gameplay) should be fine to varedit, as long as it's within common sense. Other stuff like varedited airlocks should be changed, with that I agree. But either way, just cutting all varedits out and installing a travis patch to fuck you up if you rename a pizza into "cold pizza" is dumb

Also some invisible issues will arise with golden slimes / master belts. For example, let's pretend russians have a 1/100 chance of spawning from one. Now let's turn the 4 varedited russian dancers in the DDR vault into subtypes. Suddenly the chance increased to 5/104 - that's nearly 5x as much. Not really noticeable at first, but the issue will be there, and it will grow as more useless subtypes are added

**Comment by DrCelt** [comment]
>Forbidding mappers from changing pixel_x/y is not "debatable" at all. It's a big fat huge absolute NO.

blame @clusterfack he said that

**Comment by PJB3005** [comment]
I have been telling people and semi enforcing this for a while now.

Imo it's dir and pixel offsets that are fine, nothing else.

**Comment by clusterfack** [comment]
@unid15 
>Also some invisible issues will arise with golden slimes / master belts. For example, let's pretend russians have a 1/100 chance of spawning from one. Now let's turn the 4 varedited russian dancers in the DDR vault into subtypes. Suddenly the chance increased to 5/104 - that's nearly 5x as much. Not really noticeable at first, but the issue will be there, and it will grow as more useless subtypes are added

That's just literally poor coding and a pretty poor reason to justify anything, when there is no reason we couldn't code it better for simple example add a variable to modify the chance, there is absolutely no reason to bring them up

**Comment by ComicIronic** [comment]
What would be the value of doing this? How would that value outweigh significantly bloating the type tree?

**Comment by PJB3005** [comment]
For one thing when we get a better mapper, I feel this isn't needed.

With the piece of shit that's DM: it so is.

**Comment by gbasood** [comment]
I don't see how a better mapper will change map formats in such a way that dir and pixel_x/y won't still show up in map files

**Comment by ComicIronic** [comment]
Why would you want them to not show up in map files?

**Comment by gbasood** [comment]
Don't know why Celt wants it other than he had to regex find/replace a bunch of variables for 64x64

**Comment by ComicIronic** [comment]
You can use preprocessor defines in dmm, though.

**Comment by gbasood** [comment]
Sure but not in Dream Maker afaik
things like NORTH throw errors
