### ISSUE TITLE
Vision is fucked, and internals bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11323]
I was clown. I died a lot. Here are some results.
![cloning](https://cloud.githubusercontent.com/assets/5169310/17459911/d61cde0a-5c1c-11e6-8466-132dd6cd1a44.png)

![critvision](https://cloud.githubusercontent.com/assets/5169310/17459913/da2eaeec-5c1c-11e6-9051-ba03336d4eb7.png)

Oh also slapping 2 bugs in one stone. You can toggle internals always. Even in crit. Even while dead. Earlier this round while I was knocked out via N20 during surgery, I toggled the internals off to wake myself up.

**Comment by 9600bauds** [comment]
You already reported the internals bug

**Comment by Killette2** [comment]
So I saw 45 minutes ago or something along that lines, but what's done is done. You get an upboat and we ignore the internals bug until it gets fixed.

**Comment by Shadowmech88** [comment]
Your vision was probably blurry due to eye damage incurred through cloning.
Also, I just tested it and I could not toggle my internals while unconscious or dead.
