### ISSUE TITLE
Frozen viewport

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11334]
(WEB REPORT BY: slashbolt REMOTE: 172.93.109.202:7777)

> Revision c158bf2c6c94a187bf695239f71959d3d5ebac6
> 
> General description of the issue
> My screen freezes whenever I get stunned and a UI effect appears.
> 
> What you expected to happen
> To not have my screen freeze.
> 
> What actually happened
> My screen freezes and the only fix is closing BYOND and relaunching.
> 
> Steps to reproduce if possible

**Comment by gbasood** [comment]
Maybe 64x64 related? Could imagine this happening with 64x64 and poopcomputer

**Comment by DamianX** [comment]
doesn't happen anymore
