### ISSUE TITLE
Parallax makes transit turfs invisible

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#11331]
![](http://puu.sh/qsOgo/8c2308b066.png)

:airplane: :office: :office:

**Comment by Exxion** [comment]
It's weirder than that
It only happens if you are below the bottom of the big windows in the emergency shuttle
Not sure about where you have to be on other shuttles

**Comment by gbasood** [comment]
Why is parallax happening at all on transit turfs
Ever
It should literally never affect transit turfs

**Comment by ghost** [comment]
oh yeah this was that planes bug that wasn't reported. Will fix
