### ISSUE TITLE
Using EMP while riding the firebird kills it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11337]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> ce8f107d458c94bf3fc272aa6471f34b7663a20d 
> 
> General description of the issue
> Using the EMP spell while riding the firebird kills the car
> 
> What you expected to happen
> My literal magic car to work while using EMPs
> What actually happened
> Mordenkainen Dark (as Unknown)  says, "NEC`CANTIO" 
> The Firebird's motor short circuits! 
> The Firebird is unresponsive. 
> 
> Steps to reproduce if possible
> Get both the car and EMP, try to use them

**Comment by Killette2** [comment]
> firebird can get EMPed instead of running on magic

Literally retarded.

**Comment by clusterfack** [comment]
That's because EMPs are also magic

**Comment by jknpj** [comment]
![resized_uncle-meme-generator-magic-must-defeat-magic-931311](https://cloud.githubusercontent.com/assets/17928298/17466376/5a460846-5ce5-11e6-8b4e-3be49ce27337.jpg)

**Comment by SonixApache** [comment]
Don't EMP while on firebirds?

**Comment by DeityLink** [comment]
Given the reception of #11363 I think people accept this as normal. Also makes ion rifle a viable counter to the Firebird.
