### ISSUE TITLE
Can't interact with Cocoons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11342]
(WEB REPORT BY: morena REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> ce8f107d458c94bf3fc272aa6471f34b7663a20d
> 
> General description of the issue
> Can't interact with Spider Queen made cocoons on mobs. You can't even move the cocoons to get them somewhere safe to unwrap them, if you could unwrap them.
> 
> What you expected to happen
> I expected to be able to tear at a cocoon containing a wrapped player and destroy it, allowing to free their body
> 
> What actually happened
> Whatever item I clicked the cocoon with I got no messages or anything, trying on various intents with sharp and blunt objects.
> 
> Steps to reproduce if possible
> Get a player to get wrapped up by a spider queen and then attempt to free them.

**Comment by ghost** [comment]
It isn't movable at all, use burn weapons like welders and cauteries to get them open.

**Comment by Exxion** [comment]
It should give text when you hit it with anything, and you can break a cocoon with any weapon, it just takes a long time with most
