### ISSUE TITLE
'Add TC' button creates another uplink.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11346]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 510f000d81cadf672e897cec921eb15df5a3f4ed 
> 
> General description of the issue
> Second uplink that overwrites the old uplink
> 
> What you expected to happen
> ADDING MORE TC to the traitor's existing uplink
> 
> What actually happened
> Nope.
> 
> Steps to reproduce if possible
> Choose to 'add tc' to a traitor.

**Comment by Megamaw** [comment]
yeah, kavlax tried giving me some TC, but it didn't work At All

**Comment by AutismSpider** [comment]
May have to use Vars to add more TC's

**Comment by ghost** [comment]
Click the number of TCs in their antag section, that'll let you edit the number

Add/remove is to do with uplinks
