### ISSUE TITLE
photo images have fucked up overlays in 64x

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11345]
![dreamseeker_2016-08-08_18-38-08](https://cloud.githubusercontent.com/assets/6526157/17497251/4d8eda12-5d97-11e6-8124-cfe955e258b5.png)

**Comment by Exxion** [comment]
Wait hold on
I thought it was just missing when I saw it in-game but in that image I see it's actually there, just tiny and in the corner
I love it

**Comment by Shadowmech88** [comment]
This was apparently fixed, and 64x64 is dead anyway.
