### ISSUE TITLE
Cargo shuttle is ALWAYS late

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#11344]
ALWAYS, not sometimes, not most of the time, IT'S ALWAYS FUCKING LATE.
The time between being late and arriving seems to vary, but why in the world would it always be late?
I know NT is shit and all but come on, it's quite literally never on time.

**Comment by Ephx1** [comment]
It's not even entirely mulshions thing, it used to not be like this, something changed.

**Comment by AutismSpider** [comment]
it was random if it came late or not in the past some thing was touch.

**Comment by PJB3005** [comment]
Might be related to the fact that the supply shuttle process only ticks every once every 30 seconds.

**Comment by Probe1** [comment]
They're right and i've noticed this too. 

But supply codes pretty crazy and it scares me.
