### ISSUE TITLE
some UI elements are fucked now, zone selection is off screen

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11352]
SEND HELP

![image](https://cloud.githubusercontent.com/assets/19365096/17504464/080334b8-5dc7-11e6-9529-5e88b7235c97.png)

![image](https://cloud.githubusercontent.com/assets/19365096/17504470/1389d5bc-5dc7-11e6-84f2-dd25669e700c.png)

**Comment by TheFriggenSawbones** [comment]
fuck the CODERS

**Comment by icantthinkofanameritenow** [comment]
#11351
Well fuck, we reported it at the same time. 

In other news, this will make surgery a very, _very_ interesting challenge.

**Comment by clusterfack** [comment]
Called it

**Comment by Exxion** [comment]
That sort of applies
