### ISSUE TITLE
Some icons are still Xbox huge

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11355]
Revision number 20e4aed1ac9a95de2c1a43b69302f2bad746d2ed 

![image](https://cloud.githubusercontent.com/assets/19365096/17507801/ba29cfae-5ddf-11e6-83e6-a9dd5459cea0.png)

Mostly stuff in the "work in progress" folder from what I'm seeing(RUST parts,

**Comment by PJB3005** [comment]
Oh fuck I see where this went wrong. All of those have a separate file outside of `icons`

**Comment by jknpj** [comment]
You're a big engine.

**Comment by Killette2** [comment]
Keep the giant SPC

**Comment by unid15** [comment]
fixed
