### ISSUE TITLE
Move liver function boost

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11364]
#### Description of issue

This is stupid
#### Difference between expected and actual behavior

Expected liver boost to be in the chest, but it involves the head. What does the head have to do with the liver?
#### Steps to reproduce

Be borer, go in chest not head.
#### Length of time in which bug has been known to occur

Since the dawn of multi-borer man
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

**Comment by jknpj** [comment]
> What does the head have to do with the liver?

http://diabetes.diabetesjournals.org/content/62/5/1367

> Length of time in which bug has been known to occur
> Since the dawn of multi-borer man

You know, that's how old borers worked, too. But i agree it needs to be moved.

**Comment by Probe1** [comment]
@Shadowmech88

**Comment by Shadowmech88** [comment]
What genetic mutation should head borers get to replace it?

**Comment by Probe1** [comment]
not anything retarded like x-ray that's for sure.

borers are already deep in meme magic territory.

**Comment by Killette2** [comment]
Was this changed?

**Comment by Shadowmech88** [comment]
Yes, liver function boost is now an ability of chest borers.
