### ISSUE TITLE
Make racks like tables

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11366]
#### Description of issue

You can place things wherever you want on a table, this behavior does not carry over to racks. The placement is randomized

**Comment by Exxion** [comment]
Doesn't placement on a rack cycle through three positions?

**Comment by kol1th** [comment]
yes, it does Exxion

**Comment by Exxion** [comment]
Personally, I like that racks have three specific positions for things to go in
But we could make it so that items are placed into the one nearest where you click
