### ISSUE TITLE
Borer host switching bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11365]
#### Description of issue

Got evolution options I should not have
#### Difference between expected and actual behavior

Not have evolution options
#### Steps to reproduce

Do a gene evolution in one host, then you will have the prerequisite in another
1. Go in head
2. Give a host telephoto vision
3. Have host die from being a retard before you can give x-ray
4. Go in new host
5. Able to give both x-ray and telephoto, despite not having telephoto prior for this host
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
You, as borer, evolved enough to get xray in your evolution tree and since genetic modifications are applied once per host, it's not strange being able to give both of them to a new one since your evolution tree isn't reset when you switch hosts.

**Comment by Shadowmech88** [comment]
I don't think this should be considered a bug.

When you evolve telephoto vision you are, ostensibly, also learning _how_ to give your host telephoto vision.

As such I don't see why you should lose the option for X-ray vision just because your host no longer has telephoto vision.

**Comment by Killette2** [comment]
I see your points, but I expected it more to be a linear upgrade for every host, like you're building upon what you already did. Either way I don't have a problem with it working this way, I just noticed it existed.
