### ISSUE TITLE
Can no longer see pipes in the dark while ventcrawling

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#11372]
Only tested on borer, but I assume it applies to all ventcrawling things. Some time ago you could see pipes surrounding you in the darkness, but now it's all up to luck trying to navigate maintenance. The pipe overlay you get while moving through the vents is still visible, just not in the darkness.

**Comment by ghost** [comment]
uhhhh, this is to do w/planes but it'd be better to turn the pipe-crawling visibility system into one that uses planes anyway so I'll do a rework of this soon :tm:

**Comment by Ephx1** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6224074/17568366/701e92ae-5f11-11e6-94b3-83976db1385a.png)
This picture perfectly displays the issue for anyone wondering.

**Comment by clusterfack** [comment]
The only reason this ever worked was due to SEE_PIXELS, which we are no longer using

**Comment by ghost** [comment]
oh, yeah never mind this is not a planes issue it is a byond issue, I misread the initial report.

**Comment by gbasood** [comment]
There's got to be some way for us to display things through walls for only some users though
I mean, mesons do it still despite see pixels being gone, right?

**Comment by clusterfack** [comment]
No, mesons use a special flag to make one of the four base byond types visible, it is not similar to making a specific typepath visible

**Comment by ghost** [comment]
untag bugfix and planes, add "thanks byond"

**Comment by Ephx1** [comment]
I almost want to beg for better darkness sight for borers because this is such a pain.

**Comment by beesil** [comment]
Fixed in #20500
