### ISSUE TITLE
CMC Showing Destroyed Player Corpse

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11370]
(WEB REPORT BY: freakinabonk REMOTE: 172.93.109.202:7777)

> Revision b13a229bd68403d9e4e4965122c8a39ea5658e28
> 
> General description of the issue
> The singularity ate a person's corpse; Crew Monitoring Console continued to show the corpse's coords even though the body and everything on it was destroyed.
> 
> What you expected to happen
> CMC to stop showing the existence of a non existent corpse.
> 
> What actually happened
> CMC showed the existence of a non existent corpse and led to around an hour of trying to save the unsaveable, and then save the doctor who was responsible for saving the dead guy.
> 
> Steps to reproduce if possible
> take corpse w/ full suit sensors on, throw into singularity, check on CMC for them

**Comment by gbasood** [comment]
Sounds like someone wasn't GC'd properly
Do simple mob's list of friendlies (people who fed them) still keep a ref to that mob forever and always?

**Comment by DeityLink** [comment]
CMC got completely reworked since so that shouldn't still be happening.
