### ISSUE TITLE
Central Atmospherics Computer map is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11386]
(WEB REPORT BY: ekkosangen REMOTE: 172.93.109.202:7777)

> Revision: 486f9b1d5f29afe33bf647e74fe113b9e0b44da8
> 
> General description of the issue
> Map of the station does not appear on the central atmospherics computer, some of the air sensors aren't visible.
> 
> What you expected to happen
> Map should appear with air sensors overlaid on top
> 
> What actually happened
> No map, some air sensors are not appearing
> 
> Steps to reproduce if possible
> Open central atmospherics computer.

**Comment by AlphaBuffalo** [comment]
Does anyone know what happened to it?

**Comment by 9600bauds** [comment]
It broke

**Comment by AlphaBuffalo** [comment]
Like why or how it broke and why no one has bothered fixing it since it's been broke for the better part of half a year
