### ISSUE TITLE
Even in death I flesh hook

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11385]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)486f9b1d5f29afe33bf647e74fe113b9e0b44da8 
> 
> General description of the issue
> hook work in death
> 
> What you expected to happen
> hook stop work
> 
> What actually happened
> HOOK ONTO EVERYTHING ONLY CHOPPING THE ARM OFF CAN STOP ME
> 
> Steps to reproduce if possible
> die as extend arm borer, still hook

**Comment by 9600bauds** [comment]
it keeps happening

**Comment by gbasood** [comment]
the hook is loose

**Comment by FudgePucker** [comment]
Its a feature, the border is still alive

**Comment by AI-Is-Rogue** [comment]
No. The borer is not alive. lightly salt the borer. This kills the borer.

**Comment by Gringonius** [comment]
Wasn't this an issue since the memeborers were merged?
I still remember a borer that would keep hooking his crit host away from medical attention and latter claimed he had no idea his host was alive.
remove borers

**Comment by Shadowmech88** [comment]
@Gringonius 
You're thinking of using the hook when the host is dead, which is intended.

This is about a borer using its hook while it itself is dead, which is an oversight.

**Comment by Iamgoofball** [comment]
icefrog please nerf pudge
