### ISSUE TITLE
(Box) Make Outpost Great Again

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#11380]
This has been brought up by a few other people. Each of the Vox outposts kind of has a gimmick - Meta has all that research equipment, good gear, chemistry, genetics, surgery, virology. Deff has mining, a single chemistry dispenser, and other nice perks (wizard cards, crossbow, drink dispensers). The big plus that Box used to have before @dylanstrategie updated it was that it had a staggering 22 trays, which is more than the main station even has. Now it has a much smaller number.

Since Botany is kind of the outpost's gimmick, it might be nice if the Box outpost started with more trays, some farmbots, maybe bees, and even xenobotany machines. Big bonus if whoever maps it adds trader access to the whole outpost so that minertide and scientisttide don't immediately raid it for jetpacks at roundstart. Especially since we've finally done away with traders having the option for no ID.

**Comment by ghost** [comment]
The only reason I cut down on the trays so much is that there's so little space to put trays while leaving navigation room and spots for all the machinery

To expand the Outpost Botany, it would have to get physically bigger. Which means moving the Trading ship and most likely redesigning the two docks

**Comment by Kurfursten** [comment]
I agree with you that it would need a dock redesign. I don't  think anyone will be sad to see the current dock go: the awkward lanky hallway is poor form and has been around since ancient times.

**Comment by ihadtoregisterforthis** [comment]
It's part of the charm of an ugly alien outpost

**Comment by Kurfursten** [comment]
Here are some better ways to make the outpost ugly than making the rooms bad:
- Missing or damaged tiles
- Damaged windows
- Random items such as trash, debris, and remains on the ground
- Decals such as blood, vomit, and dirt
- Replace some non-essential wall tiles with girders
- Add pests such as mice or cockroaches (might suffocate? might not matter, dead pests are ugly too)

**Comment by ihadtoregisterforthis** [comment]
That's abandonment, trash, a derelict station.
The vox outpost is clean and empty, with the dock being like an afterthought.

**Comment by Kurfursten** [comment]
Look, if you push the outpost back a little bit you would hit the edge and have PLENTY of room for ships. Here's just a mockup of what it could look like, anyone could map it.

There are 22 trays. 14 in the primary botany room oriented around the 2 beehive trays, with 6 more in the research room.

The trade floor basically doesn't even move, you just rotate the outpost around it.

![mockup](https://cloud.githubusercontent.com/assets/9782036/17641414/85871c18-60e4-11e6-8e89-bd8088ff9bb1.png)

**Comment by ihadtoregisterforthis** [comment]
You can make it better and beautiful, but you can also make it better and ugly looking. Not by making it dirty but by making it subpar. Otherwise it's the same as a human station but with nitrogen.
