### ISSUE TITLE
breaking windoors should leave a broke windoor assembly on the floor you can pry the controller out of

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11382]
breaking windoors should leave a broke windoor assembly on the floor you can pry the controller out of

**Comment by Intigracy** [comment]
breaking windoors should leave a broke windoor assembly on the floor you can pry the controller out of

**Comment by Exxion** [comment]
It's supposed to drop the controller, but doesn't always

**Comment by Intigracy** [comment]
you mean always doesn't

**Comment by Exxion** [comment]
I do not, because it sometimes does

**Comment by Intigracy** [comment]
Is there any pattern to it?

all access
access required
ROUNDSTART versions of the above
BUILT MIDROUND versions of the above

**Comment by Exxion** [comment]
I assume so, but I don't know exactly
I'll test it a bit

Also, this reminded me of a separate bug: Constructed windoors entirely ignore the access settings on the controller

**Comment by Exxion** [comment]
This is odd.
I've definitely seen windoors drop electronics and there was at least one PR to make them do so, but I can't get it to actually happen

**Comment by Intigracy** [comment]
#7960 was supposed to fix it but @clusterfack is a big phony

dupe of #9965 btw (which appeared after the above PR)

**Comment by Megamaw** [comment]
this is unreasonably hard for me to clean up and reconstruct as it is, as a janitor, for something so easily broken by shitcurity/antags/etc.

fix it ASAP.

**Comment by clusterfack** [comment]
Dupe
