### ISSUE TITLE
Monkeys can wear buckets on their head without spilling their contents

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#11387]
magix

**Comment by SkowronX** [comment]
Because monkey code is snowflakey as fuuuuckkkkk just make monkeys a subtype of human aaaaaaahhhhhhhhhhh

**Comment by unid15** [comment]
What we need is a full slot refactor like #10045

**Comment by Killette2** [comment]
Maybe since they're silly monkeys, they wear the bucket the other way, so it doesn't spill.

**Comment by DeityLink** [comment]
Must have been improved since then, the contents spill just fine now.
