### ISSUE TITLE
Clown goblins are wizards

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11393]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)92406bdbaaca77eae82f21018078a8799a078865 
> 
> General description of the issue
> Clown goblins that attack a broken grille turn it into a full grille, causing as many rods as you want to be created
> 
> What you expected to happen
> clown goblin not to attack the broken grille
> 
> What actually happened
> Infinite rods, infinite metal
> 
> Steps to reproduce if possible
> create clown goblin and put it near grilles

**Comment by 9600bauds** [comment]
haha what

**Comment by AI-Is-Rogue** [comment]
Decided to make a clown goblin out of the spare costumes I had. Eventually went to ghetto botany and had the brilliant idea to make the clown goblin angry and put in my pocket. The clown goblin did not stay angry in my pocket, and it attacked one of the broken grilles (that show up when you kick/beat with item)  a few times and turned them into a full grilles. It might even smash them and then repeat the process.

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce.
