### ISSUE TITLE
New Job For Snow Map

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#11392]
Since the snow map WE BUILD has stagnated. What if we add a job where you have a teleporter to an Ice Planet and you explore it and build stuff there. To make it some what appealing we can add artifacts in there for crew to find and special materials that arent found on the asteroid. I'm more so spit balling ideas here.

**Comment by Kurfursten** [comment]
A job where you leave the station to look for artifacts and special materials... like miners and xenoarcheologists?

**Comment by AlphaBuffalo** [comment]
and build? Xenoarch and miners dont build :^)

**Comment by AlphaBuffalo** [comment]
IDK what about a shuttle to a snow world z-level?

**Comment by ghost** [comment]
I've been dabbling with having a simple away mission that's just snow turfs, and it completely crashes when loading.

Something's fucked with snow turfs now, they just won't load at all, whereas previously they were only just dicey

**Comment by ghost** [comment]
@Skullyton I'll work on it soon :tm:

**Comment by AlphaBuffalo** [comment]
So no snow map till next year

**Comment by Intigracy** [comment]
try next decade

**Comment by ghost** [comment]
snow map will be fully released by december 25th 2016

**Comment by unid15** [comment]
What size did you make it @Skullyton ? If it crashes, it may be too big (the map loader has trouble with 500x500 maps)

**Comment by ghost** [comment]
@DrCelt You said you'd help me back in march, then may, then august

@unid15 Yeah, 500x500. Weird thing is, I used to be able to load a map where all space tiles on taxi (Across all Z Levels) were made into snow tiles (albeit after about 5 minutes wait), now it just straight up crashes

**Comment by Intigracy** [comment]
Five bucks it was #10200

**Comment by ghost** [comment]
To go along with this 'new job' thing, I had an odd idea about phasing out the gateway entirely, in favour of using telescience instead.

It'd involve acquiring co-ordinates (More than just XYZ (local space), we're talking relative drift including blue or red shift, frequency to accommodate for interference(getting that wrong, you'd likely turn the teleporting target into a pile of sludge or worse), etc.) via an observatory job, or potentially decoding picked up syndicate transmissions that would use a randomly generated (on round start) cypher, let's say a 5-character phrase.

Once that's done, it's then down to the roboticist to create a functional observation drone to send to the co-ordinates, to not only see if they work, but to also ascertain what sort of equipment would be required should people be sent there. Better parts for this drone would be acquirable through R&D, or found earlier than R&D can acquire them through xenoarchaeology, with some being unique to both fields.

Might be too much work/autism for this server though

**Comment by unid15** [comment]
Loading a map with the map loader isn't the same as including a map in Dream Maker - the first one is done at runtime, and will nearly always crash when given a 500x500 map, even if it's just turfs with no objects. Including a big map in DM will work just fine though

**Comment by ghost** [comment]
I was including the map in dream maker, it just completely froze up, regardless of if I put the overlay nonsense it has to do on New or Initialize, whereas before it used to load up quite nicely on Initialize until dylan did #10200 , which killed #9809 dead and is still killing it no matter which way I approach it.

It'd help if there was some form of instruction manual with these generators he made, but some do what they're advertised as not doing (Being turf-specific in what they change, but then end up changing everything regardless)

**Comment by AlphaBuffalo** [comment]
@skullyton kind of gave me an idea about GPS devices. If someone has a GPS and ask telescience to teleport them they can press a button or something and the telescience guy can lock into his GPS unit and teleport without the need of drift calculations. But it only works if the guy with the GPS unit hits a button on the unit itself
