### ISSUE TITLE
Freezer/Heater can't have its maintenance panel opened AT ALL

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#11400]
Heya bud, heard you wanted to upgrade or deconstruct me, the Freezer.
Now, now, you can't just screwdriver me open, you gotta turn me off and unwrench me first.
But hold on, now! You need to wrench me down if you're just going to open my panel like that.
What do you mean this is retarded?

**Comment by Kurfursten** [comment]
Needs more testing, I saw a freezer deconstructed this week so it must be possible.

**Comment by Wizardcrying** [comment]
AAAAAA
this was done late at night when I had a fuzzy memory of what the issue was
I retested it and it was an issue with the RPED

**Comment by Wizardcrying** [comment]
https://github.com/d3athrow/vgstation13/issues/9368
it's this issue
