### ISSUE TITLE
job choosing issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11408]
#### Description of issue

on my saved slot, on the job list, i have atmos as high and other jobs as medium and low; on a round i choose assistant with "return to lobby if preference is not available", i noticed that my portrait was still atmos tech, and when the round started i was actually an atmos tech.
on the following round i tried again to choose assistant and i've seen that my portrait was still atmos, so i reset the jobs, choose assistant and this way it worked.
i haven't saved my slot in both rounds.
#### Difference between expected and actual behavior

to choose assistant and be assistant.
i choose assistant and was an atmos until i reset the job list.
#### Steps to reproduce

save your slot with any job on high, then try to change it to assistant.
#### Length of time in which bug has been known to occur

happened today.
#### Server revision

9debda602789f89c86f5106da2808e629554f274 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Yeah, turning assistant on doesn't really work unless you also turn your other job prefs off
Man there are a lot of bugs I noticed and forgot to report

**Comment by Kurfursten** [comment]
I think this is related to the hard limit on assistants which changes to base off sec

**Comment by Kurfursten** [comment]
Fixed by me
