### ISSUE TITLE
Medical chat channel color is very similar to general chat color

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11405]
(WEB REPORT BY: rei1226 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

9debda602789f89c86f5106da2808e629554f274 

> General description of the issue

Medical chat color is exactly the same as the general chat color. You can't even distingiush between the two.

> What you expected to happen

Readable medical text

> What actually happened

Medical chat channel blended in seamlessly with general chat channel

**Comment by Exxion** [comment]
Definitely wasn't the case last time I saw the medical channel
How long has this been happening?

**Comment by ComicIronic** [comment]
Need a confirmation that this is actually happening live.

**Comment by Exxion** [comment]
It isn't happening on the test server, at least.

**Comment by Exxion** [comment]
Confirmed in deadchat that the color isn't broken, just Rei can't see the difference
Either a problem with his eyes or his screen

I'll leave it open in case people want the color changed to be a more obvious difference, though

**Comment by SysadminJeroen** [comment]
@Rei1226 check if you have colour blindness and come back. The colour is really close to the common channel but a slightly different hue.

**Comment by ghost** [comment]
I think that's a case of actual color blindless. Medical is Cyan, Common is Green

Either that or he's using a shitty discount screen with a temperature that would make a tungsten bulb look like a spotlight

**Comment by Exxion** [comment]
He said he could see the difference on a different screen, but just barely

I see where he's coming from. The colors are quite similar. Maybe a different color would be a good idea.

**Comment by Megamaw** [comment]
for those of us that don't play medbay, can we have a screenshot that showcases this?

**Comment by Exxion** [comment]
The screenshot provided by Rei:
![](http://puu.sh/qza6t/335f3aefe2.png)

**Comment by Killette2** [comment]
Still not as bad as command blue vs OOC blue

**Comment by ghost** [comment]
Command blue and OOC blue are nothing alike

**Comment by Killette2** [comment]
Things look more alike when they're flying at 100mph during highpop

**Comment by ghost** [comment]
@Killette2 you're probably too high to tell

**Comment by ihadtoregisterforthis** [comment]
![med and comms](https://cloud.githubusercontent.com/assets/13305885/17644630/1c674752-6162-11e6-9527-2970ff5ce31a.png)

Same Saturation and Lightness
They are very similar on a rush
![planes were a mistake](https://cloud.githubusercontent.com/assets/13305885/17644779/5fb97a76-6166-11e6-8a32-5fadebe31abf.png)

**Comment by Killette2** [comment]
TAKE THAT BACK! Whenever an OOC shitpost storm emerges, command becomes hell to read. Medbay to common is bad, but not that bad. At least they're different colors, OOC and command are both a darker blue.

**Comment by ComicIronic** [comment]
We can't make medical much lighter or less saturated without it becoming difficult to read. There are only so many distinct colours to react to at a glance.

We could make command a darker green.

**Comment by ghost** [comment]
Medical channel needs to be made lighter and a bit closer to Cyan

I don't remember it being that dark before, did someone change it ?

**Comment by Killette2** [comment]
I honestly can't say what we can do without testing and comparing different color variations.

On another note, space drugs don't exist celt. As neat as it'd be, I don't think anyone here has taken anything that makes them see rainbow colors that may distort color viewings. _tips fedora_

**Comment by charmstruck** [comment]
Something needs to be done about this. I'd like to be able to distinguish between important orders over medical comms and dumbass assistants jerking off on general comms out of the corner of my eye. This is simply impossible with the current colors, unlike every other department

**Comment by Rei1226** [comment]
Would an orange work for medical perhaps? It might be a bit close to the security color, but then again you wouldn't really be listening to both medical and security channels at the same time, would you?

**Comment by Killette2** [comment]
orange for medbay feels wrong on many levels, and would clash very ugly if also listening to the mining and security channels.

**Comment by ihadtoregisterforthis** [comment]
![med and comms blue](https://cloud.githubusercontent.com/assets/13305885/17698352/21b95e44-6391-11e6-81b9-a78eba7669c8.png)

Same saturation and brightness, another hue
Hex 008282

**Comment by ComicIronic** [comment]
CSS does let us do all sorts of tricks to allow for more chat variety.

One idea could be a colour reversal:
![](http://puu.sh/qDvyG/fee871dcd5.png)

**Comment by PJB3005** [comment]
I really dislike how hard that contrasts honestly.

**Comment by charmstruck** [comment]
I think it's much better than it is now though

**Comment by Rei1226** [comment]
It is better than it is now, but I agree with PJB3005. I think it would really contrast.

**Comment by 9600bauds** [comment]
I really really want to fix this but I need ideas for a better color

**Comment by ghost** [comment]
Just deeper cyan is fine

For some reason the old color was changed into this weird washed out cyan a while ago during the chat rework

**Comment by 9600bauds** [comment]
Isn't deeper cyan similar to command?

**Comment by Probe1** [comment]
Commands more of a dark blue.

**Comment by 9600bauds** [comment]
![photoshop_2016-12-29_21-56-56](https://cloud.githubusercontent.com/assets/6526157/21557933/ba5f4f24-ce11-11e6-97d3-203b4acd366a.png)
Sadly after doing this thing I am still no closer to finding the solution

**Comment by ghost** [comment]
Oh, I see the problem. Service radio stole Medbay's color

Give these disgusting plebs a shittier color like Nuclear Waste OC Green or Librarian's Underpants Pink and give Medical its rightful Cyan back

**Comment by Intigracy** [comment]
You forgot the nuke op channel pal.

**Comment by Intigracy** [comment]
also just do this

![ba5f4f24-ce11-11e6-97d3-203b4acd366a](https://cloud.githubusercontent.com/assets/4043940/21558303/825f24ca-cdec-11e6-9824-74c965ad1abc.png)

**Comment by Probe1** [comment]
eyesore.  its way too bright.

**Comment by 9600bauds** [comment]
don't worry I'm working on a great solution that will leave everyone thoroughly dissatisfied

**Comment by 9600bauds** [comment]
ok how's about this
before
![photoshop_2016-12-29_23-08-58](https://cloud.githubusercontent.com/assets/6526157/21558621/cf3a9e9e-ce1b-11e6-91bc-bd6436427c8f.png)
![dreamseeker_2016-12-29_22-55-01](https://cloud.githubusercontent.com/assets/6526157/21558623/d54d76ee-ce1b-11e6-8442-f7b06848908f.png)

after
![photoshop_2016-12-29_23-09-03](https://cloud.githubusercontent.com/assets/6526157/21558624/d802e2a2-ce1b-11e6-8178-15da89f0f29e.png)
![dreamseeker_2016-12-29_23-03-20](https://cloud.githubusercontent.com/assets/6526157/21558625/d9a3881e-ce1b-11e6-9704-fbdd7904520c.png)

**Comment by Probe1** [comment]
I'm okay with it but prepare your butts for people saying "WHY DID YOU CHANGE THIS"

**Comment by Intigracy** [comment]
works for me

or you can do this

![cf3a9e9e-ce1b-11e6-91bc-bd6436427c8f](https://cloud.githubusercontent.com/assets/4043940/21558911/d2cb7364-cdf6-11e6-9a9f-f562f63d1b7a.png)

**Comment by 9600bauds** [comment]
eww that puke color

**Comment by Intigracy** [comment]
perfect for the poopy service department
