### ISSUE TITLE
Objects sent to space in telesci move upon teleportation

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#11404]
#### Description of issue

When attempting to send a GPS to a space turf like (100, 100, 1), it starts moving diagonally down and to the left. This also happens when a human carrying the GPS is sent (and, of course, presumably if a human is sent without a GPS). This does not happen when sending a GPS to a non-space turf (for example, sending a GPS to the a floor in telesci does not produce this.
#### Difference between expected and actual behavior

GPSs start moving upon teleportation to space turfs instead of remaining stationary, making calibration difficult if sending to easy co-ordinates like (100, 100, 1) instead of sending to, for instance, the co-ordinates for the GPSs that spawn in telesci.
#### Steps to reproduce

Send a GPS to a space turf
Update a second GPS repeatedly to follow its path.
#### Length of time in which bug has been known to occur

Not sure. A couple of days at least, I would guess.
#### Server revision

29dd064a22294b4161eb924798990589fec4bc9f
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched for telesci, tele, calibrate, calibration, receive.

**Comment by Exxion** [comment]
Yeah, this has happened for a long time. Probably always.
Is it really always specifically down and to the left?

**Comment by clusterfack** [comment]
Sure it wasn't caused by @unid15 ?

**Comment by Exxion** [comment]
OK well GPSes drifting on their own was caused by that, but this has happened to mobs for at least several months

**Comment by kol1th** [comment]
@unid15 pls fix

**Comment by Exxion** [comment]
It's not Unid's fault
He made spacemove apply to everything rather than just mobs, but this was the behavior spacemove always had

**Comment by ComicIronic** [comment]
Could it be that you teleport the object, it hits then Entered(), calls a get_dir from the old turf to the new one, and for (100, 100, 1) this is down and to the left? What happens if you teleport them to 400, 400, 1?

**Comment by Kammerjunk** [comment]
When I sent one to (300, 300, 1), it started going up and to the right. I'm currently on test_box locally, but I'll tell you what happens at 400 in a couple of minutes

**Comment by Kammerjunk** [comment]
Sending it to (400, 400, 1) also made it fly up and to the right. Seemed to be going evenly so as I was able to catch and receive it on (430, 430, 1)

**Comment by unid15** [comment]
fix is underway
