### ISSUE TITLE
Recycling inconsistency

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11407]
Okay, so I like disposals recycling. It's part of my job as a janitor.

But when I see so many plastic bags thrown away, I get disappointed. Why can't they be scrapped down into plastic? It has plastic in the name!

And why can't used pizza boxes be scrapped into cardboard?

I'm sure there's more, but I'm drawing a blank. Anyone else?

**Comment by Kurfursten** [comment]
It's just low level work, even you could do it

All you have to do is add materials to those items, so add starting mat of 3 sheet of plastic to the bag, etc.
