### ISSUE TITLE
Borer UI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11417]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
Borer is supposed to have no UI but he has UI of a wraith/sharded soul instead for some reason.

**Comment by ghost** [comment]
Borers were given a simple UI that lets them target individual limbs as of multiborer

**Comment by ComicIronic** [comment]
Was this not in the changelog?

**Comment by Shadowmech88** [comment]
Probably not.
