### ISSUE TITLE
Janitorial Tweak suggestions

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#11420]
According to the wiki, Janitors usually clean up messes, and do the dull maintenance work usually neglected by the engineering team. This generally includes replacing lights, and other small things that aren't immediate dangers to the crew, like broken windows, and occasionally fixing AI cameras.

I want to give Janitor a few minor tweaks to help promote this playstyle, while also ensuring the janitor's niche isn't just 'a worse Engineer'.

So the janitor has their own little office, and generally that's one of the only places janitors have exclusive access. From map design on Box, right from your office, you are able to access Cargo's disposals line-- primarily used by them for the mailing system.

To the west is Recycling, where all the junk goes. I propose making this a janitor-access area-- again, cleaning up and dealing with trash. It makes sense that the janitor, the person designated to keep the station clean, would be in charge of this.

Furthermore, something I notice a lot is that when someone is gibbed, they leave behind a bunch of arms, legs, and what have you. There's not really an easy way to clean these up. For the purposes of letting them fit in the trash bag, I also propose these are made small items instead of normal items.

As a third change, possibly start the janitor off with some metal and glass to make repairs? Probably not full stacks, but enough to get them started before people start throwing recyclables away.

**Comment by Kurfursten** [comment]
I don't like the idea of restricting the recycling room to janitors, and I can't imagine most people would either.

It's where most people end up after riding chutes - which isn't always illicit. Sometimes you're escaping a fire. That room is also really useful for smelting plasmaglass or plasteel without leaving the station if you're an engineer, and I really, really doubt I'll ever get an engineer willing to do that duty for me.

No objections to the rest though.

**Comment by Megamaw** [comment]
I had not thought about it like that. Thank you for the constructive criticism.

I don't have a lot more to say, but yeah, people would get trapped in there, wouldn't they? You have a good point.
