### ISSUE TITLE
new sprites for tajaran footprints, magboots and clown shoes

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#11421]
First time upload, this is just a few more variations for fluidtracks.dmi
(they are white on transparent, so you may have to download them to see them)

1.png features clown shoes and magboots
2.png features catbeast/tajaran and an alternate magboots
![1](https://cloud.githubusercontent.com/assets/21017309/17647463/c63948d6-6223-11e6-80f1-b762a21f965e.png)
![2](https://cloud.githubusercontent.com/assets/21017309/17647465/caab88b6-6223-11e6-94c0-7343c02f2b3a.png)

**Comment by Exxion** [comment]
I'll handle sticking these in the dmi and coding them in tomorrow.
