### ISSUE TITLE
Trader access can be overwritten/removed

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#11430]
Simple as that, the access isn't something hardcoded to a trader ID like syndicate access is to an agent ID.

I spotted a vox trader in my ship as the captain and promptly borrowed their ID to give them a fully-detailed security and medical record, some access and branding them as a NT-sponsored Trader. He lost access to his ship and it could not be returned to them as such access is unlisted on the ID console.

**Comment by Megamaw** [comment]
not quite 'oh god it's loose' but still pretty bad

i can't imagine this would be hard to fix though

**Comment by Exxion** [comment]
Taking bets this also applies to the salvage shuttle ID
