### ISSUE TITLE
FEATURE REQUEST: Mech force eject

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11438]
Now, we all know the problems with mechs right now is that they can effectively forbid somebody from forcing the driver out bar destroying it, this covers MMIs, posibrains, and carbon drivers.

So, with being able to lock down mechs being a thing (which forces them into maintenance mode), here's an idea on how to help out people dealing with mechs severely

> If the mech is locked down (Stuck in maintenance mode), you can then access it, and hit an 'emergency eject' button to force the occupant out

This would mean that MMIs and Posibrain mechs wouldn't be a veritable coffin for said brains, and if somebody's being a donk and sitting in your ripley in a recharging station and refusing to get out, you don't have to damage your cool ride, but just get science to sort them out and force eject them.

**Comment by Exxion** [comment]
Cue everyone who knows that you can lock down a mech with any ID stealing any mech that doesn't have maintenance protocols forbidden

But yeah we do need a force eject function so that's a necessary evil
Unless it can only be done from the console

**Comment by pvak** [comment]
isnt installing an electropack supposed to do this

**Comment by SonixApache** [comment]
installing an electropack does this

**Comment by Exxion** [comment]
An electropack?
Why?

Honestly this really should be a built-in feature

**Comment by SonixApache** [comment]
Eletropack triggers the auto-eject function. Don't ask me why, it just does. 
You can print electropacks (and signallers) at autolathes, which roboticists have access to.

Seems fine. Rarely used function anyway.

**Comment by ComicIronic** [comment]
So fulfilled?
