### ISSUE TITLE
Spiders have -1 speed

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11433]
#### Description of issue

OH GOD THE SPIDERS
#### Difference between expected and actual behavior

Expected - Spiders to have 5 to 6 speed, their old speed, a steady crawl so people can escape, but not so slow that they weren't creepy

Actual - VVing a hunter showed it had -1 speed, so sanic'd an entire emergency shuttle of people to death

Nurses had 2.5 speed, so slightly sanic'd the emergency shuttle to death
#### Specific information for locating

Spider hunters, spider nurses
#### Length of time in which bug has been known to occur

#11166

Was probably missed by #11398
#### Server revision

f076b50c626336cab07427c86637336b4a5bab4c
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
@unid15
