### ISSUE TITLE
Apprentices can't revive their boss wizard during ragin mages

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11431]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision b2b5c816331fcc741d7254e1a8c0a231b7270517 
> 
> General description of the issue
> Whenever you defib your boss wiz during ragin and they have 101+ damage they die again immediately. If you clone them they die in the pod because they had >100 clone damage.
> 
> What you expected to happen
> To be a useful little slave and save my boss after he kicks the bucket.
> 
> What actually happened
> Shit feature prevented that.
> 
> Steps to reproduce if possible
> Get apprenticed, watch your boss wiz die, try to save them.

**Comment by Killette2** [comment]
Well you could have always put him in a mech to become ROBO-BOSS

**Comment by AutismSpider** [comment]
got monkey human them but doing that and they loose all there wizmang powers

**Comment by clusterfack** [comment]
Pretty sure this is due to the fact that if you go into crit in raging mages you get instakilled for your failure? So it becomes pretty much impossible to revive someone.

**Comment by AlphaBuffalo** [comment]
What if the apprentice can sacrifice himself and get the wizard healed. Also it should be limited to 1 revival so wizards can't use apprentices as back up lives.

**Comment by Kurfursten** [comment]
Pre-datums
