### ISSUE TITLE
FEATURE REQUEST: Inferno Curry

### ISSUE THREAD

**Issue by Rei1226** [d3athrow/vgstation13#11435]
Basically, a curry that's so hot, that's so spicy, that eating it will cause your character to spontaneously combust into flames. Even the greatest and most renown of dotheads won't be able to resist this spicy flavor.

**Comment by Killette2** [comment]
WYCI

**Comment by Exxion** [comment]
WYCI is reserved for things that would actually be difficult to code
This would take effort, but not really that much

**Comment by Kurfursten** [comment]
Why don't you just inject hell ramen into an existing curry and rename it with the pen?

**Comment by AutismSpider** [comment]
We have hells ramen for this so hot it even kill plasma men if they eat it

**Comment by Killette2** [comment]
Hell ramen isn't even that hot compared to peppers. It's pretty underwhelming, but great in combination with peppers.

**Comment by Rei1226** [comment]
Does hell ramen physically make your character combust though?

**Comment by AutismSpider** [comment]
Combust no not even hottest peppers do that yet any way
