### ISSUE TITLE
Re-buff creepers

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11448]
In the old days when botany 2 came around, creeper was a variation of kudzu. A much nicer version.

What is better about creepers you ask? Well one thing really, and the only thing that matters
-kudzu tiles, when full grown, obstruct vision
-creeper tiles, when full grown, do not obstruct vision

This makes creeper infinitely more pleasant to deal with than kudzu, but creeper vines cannot be used beneficially anymore to a more recent nerf that came around the time botany3 was updated. What did botany3 do? Well read this.

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/spreading/spreading.dm

Second line shows the creeper can only grow at a 4 tile radius from the center, very much destroying the creepers potential by limiting it's growth area, despite the plants stats, when it used to be the same growth as kudzu.

**Comment by Kurfursten** [comment]
Isn't that kind of the point? That creeper vines won't grow out of control unattended?

**Comment by Killette2** [comment]
I like them because they don't fuck vision, it's more of a nice thing if the growth was related to another stat.

If we want to keep creepers tame, we could add a 2nd form of vines between kudzu and creeper which has unlimited expansion but isn't as dense as kudzu is.
