### ISSUE TITLE
[feature request] increase the cost of all wizard spells, as well as wizard's starting spell points

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#11443]
Right now wizards have 5 spell points that they can spend on spells, and every spell from knock (badjaunt/badmutate) to mutate (extremely powerful and versatile) costs 1 spell point

Say, if all prices and starting points were doubled, we could decrease the price of the crappy spells, like making knock cost 1 point compared to other spells' 2. Would also help implement cantrip spells

**Comment by ghost** [comment]
It would be nice to set different costs to 'stronger' spells, but their upgrades would still have to cost 1 I'd say. Having higher starting points means wizards can actually make builds with more than just level 1 spells, people only ever seem to upgrade the same few if they take them at all. I'd personally suggest a 3 point, 2 point and 1 point tier, with tier 3 being things like Mutate, Lightning, Ass Blast, the REALLY strong offensive spells, down to clown and mime curse, subjugate, knock at tier 1, the slightly more solely utility spells.

**Comment by ghost** [comment]
It would give us more room to adjust 'power rankings' and cost

**Comment by kol1th** [comment]
So, "make wizard be able to take 50% less spells because most of them are gimmick/useless"?

I don't like the idea.
:-1:

**Comment by ghost** [comment]
prices and starting points would be doubled, so that some costs on some spells can be halved.

That's a net gain in potential magic, man

**Comment by ComicIronic** [comment]
We also have the option to give the Wizard items which can only empower spells in some way - this was one of my goals back when the empowerment system was added, so that we could have upgrades be easier without necessarily adding loads more spell points.

**Comment by Killette2** [comment]
Make wizard like DCSS

**Comment by Exxion** [comment]
@kol1th Please read the OP more carefully

**Comment by clusterfack** [comment]
Yeah I'm already in support of this

**Comment by Killette2** [comment]
There is a bad part of this, where it could potentially make unintended spells power creep over the natural combat ones. How can you truly measure the balance and power of spells without seeing them live? What about combination spells, where alone they are fine, but together they are very problematic?

Doing this leads into smogon territory.

**Comment by Exxion** [comment]
It's not like we can never ever change something again once it's been changed once

**Comment by Killette2** [comment]
Well that comes with the constant reworking. It's very hard to balance such a large selection of spells. Some get no love right now as is, but it's hard to determine the true worth of a spell and give it a fair price.

**Comment by AutismSpider** [comment]
Make it so you cant cast lighting+fire ball when hulk out etc that shit is dumb

**Comment by TheFriggenSawbones** [comment]
a pretty good idea imo.
