### ISSUE TITLE
stupid feature request: pro skub

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#11442]
Make having Skub on you when shuttle docks list you on round end report as pro-skub.

This is important.

**Comment by gbasood** [comment]
aka ship my meme pls fam :^)

**Comment by ComicIronic** [comment]
I agree, skubshitters should be labelled for a post round lynching

**Comment by Killette2** [comment]
What if there was a better way to produce, or multiply skub? We have strict skub limitations and not many can support their skub usage.

**Comment by icantthinkofanameritenow** [comment]
First work on a way to make skub, it exists only as a gashapon toy.

**Comment by Exxion** [comment]
We don't want to clog up the round end thing every round
Make it so that it's really rare to get the first skub, but it can be used to make more

**Comment by Iamgoofball** [comment]
skub rules
