### ISSUE TITLE
Can't insert Assemblies inside the Atmos Automations Console

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#11459]
#### Description of issue

![thanks ssembly update](https://cloud.githubusercontent.com/assets/17928298/17756215/ec142e5c-64b4-11e6-8e6f-ab68fe13cd61.png)
#### Difference between expected and actual behavior

Expected: Assembly goes in
Actual: Atmos Automations Console ask your to hold the assembly and try again
#### Steps to reproduce

Hold the assembly in your hands and press the button
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
@unid15

**Comment by ghost** [comment]
This isn't a bug - he has in his hand an assembly frame, not an assembly.
