### ISSUE TITLE
vampire glares and screeches piercing earmuffs and sunglasses

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11451]
(WEB REPORT BY: anacondawarriorsupercommando REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> 
> Earmuffs and Sunglasses block vampire screeches and glares
> 
> they both pierce the protections
> 
> Be vampire
> glare and screech at sunglassed and earmuffed person

**Comment by Anacondawarriorsupercommando** [comment]
revision 8e7ff7726ed3d6aebd950dd983409587fffb66b5

**Comment by Kurfursten** [comment]
I know glare goes through eye prot, but are we sure screech goes through earmuffs? If so that's definitely broken

Glare has always gone through protection though. I disagree with it, but it's not a bug.

**Comment by Eneocho** [comment]
Glare is supposed to pierce eye protection, and screech does not stun if the guy is wearing earmuffs.
