### ISSUE TITLE
[Feature request]: Sources of plastic / Assembly frames on the derelict 

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11454]
Assembly frames are something to experiment on, which could entertain bored MoMMIs on the derelict. But as far as I know, the only source of such assemblies is the protolathe, requiring plastic. Since there's no source of plastic on the derelict, a solution to both this and the need of any other future component requiring plastic would be, simply, the presence of a plastellium seed packet and the required tools somewhere on the derelict

**Comment by gbasood** [comment]
As far as I know the only REAL reason not to have plastic on derelict is because MoMMIs would set up teleport things.
Not even sure that's a good reason

**Comment by PJB3005** [comment]
> MoMMIs would set up teleport things.

They shouldn't be able to leave the derelict even if they had a teleporter.

Not to mention it's AGAINST YOUR LAWS AND A BANNABLE OFFENSE.

**Comment by Intigracy** [comment]
There's.... already a teleporter.... on the derelict.....

**Comment by AutismSpider** [comment]
god damn teleporter south of the derelict massive driver.so that bad reason for no plastic

**Comment by gbasood** [comment]
yep
