### ISSUE TITLE
Stun batons miss.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11461]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 18a523593b0ce625e7b1f9e2bf8d7bb54c650ce8 
> 
> General description of the issue
> Target an adjacent person with a stun stick, it misses ~20% of the time without Clumsy. Several people I've asked about it mentioned not remembering batons outright missing in the past so I guess it'll be resolved on github.
> 
> What you expected to happen
> Batons dun mis
> 
> What actually happened
> Mis
> 
> Steps to reproduce if possible
> Keep trying to smack a monkeyman with a baton, you'll miss a smack soon enough.

**Comment by JustSumBody** [comment]
`// you can only miss if your target is standing and not restrained`
Is this not the case?

**Comment by Eneocho** [comment]
intended I guess?
