### ISSUE TITLE
Broken bottles broken again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11462]
(WEB REPORT BY: sordine REMOTE: 172.93.109.202:7777)
Broken bottles do no damage again

**Comment by Exxion** [comment]
Have any more specific information?

**Comment by Sordine** [comment]
Like what? Get any bottle, break it, and then try to attack someone with it and it deals no damage.

**Comment by Exxion** [comment]
Break it how? There are multiple ways.

**Comment by Exxion** [comment]
Alright never mind it only applies to bottles broken by throwing, just like last time
How did this break again?

**Comment by Sordine** [comment]
Ah, sorry about that. I didn't think that how it broke would matter.

**Comment by Exxion** [comment]
You know
I don't think this was ever actually fixed
I _thought_ I fixed it
What I did _should_ have fixed it
But it didn't because shitcode

I could have sworn I tested that fix, but apparently not

Anyway, I know how to fix it 4real this time, so give me a moment
