### ISSUE TITLE
Dumping water down the sink actually pours it on the floor under the sink

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#11465]
Utterly gamebreaking
(It actually is a somewhat significant problem on occasion)

**Comment by kol1th** [comment]
literally unplayable

**Comment by clusterfack** [comment]
Clearly you forgot to add the plumbing to the sink :^)

**Comment by Kurfursten** [comment]
How can you dump into the sink? In my understanding if you use a container on a sink it will always try to fill it.

**Comment by Exxion** [comment]
#9464
Alt+click on the sink or use a verb

**Comment by Kurfursten** [comment]
Our hotkeys are becoming too powerful. We should start a wiki page.

Wait a minute, we have one. And it's undocumented there.

http://ss13.moe/wiki/index.php/Shortcuts

**Comment by Kurfursten** [comment]
Update wiki!
