### ISSUE TITLE
Telecomms scripting memory not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11463]
(WEB REPORT BY: mercuriman REMOTE: 172.93.109.202:7777)
18a523593b0ce625e7b1f9e2bf8d7bb54c650ce8 

The memory for scripts on the Telecommunications Traffic Control is not working, by that I mean that when you try mem(key,value) nothing is stored on memory

I expected the server to store data based on the way people talk

what actually happened was that the variable to which I was assigning the mem() value to always ended up empty

> Steps to reproduce if possible
> mem("val",0);
> $abc = mem("val");
> $source = $abc;

**Comment by clusterfack** [comment]
@PJB3005 you know anything about this?

**Comment by PJB3005** [comment]
I'll check it out considering I'm probably the only person here that's knows a damn about NTSL.

**Comment by PJB3005** [comment]
Unable to reproduce, following code snippet works as expected:

``` c
list = mem("honk");

if (!list)
{
    list = vector($content);
}
else
{
    list += $content;
}

$content = vector2text(list);

mem("honk", list);
```
