### ISSUE TITLE
Why the nuke is always minimal effect

### ISSUE THREAD

**Issue by Sprok0** [d3athrow/vgstation13#11464]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/gamemodes/nuclear/nuclearbomb.dm at line 298, it checks if the nuke was close enough to the center of the z-level to count as on-board, but it wasn't updated when maps were made 500x500. If you detonate the nuke at the south-west syndie shuttle dock, it counts as on-station.

**Comment by nuklearcellphoneg** [comment]
wew

**Comment by clusterfack** [comment]
Wow shitcode

**Comment by icantthinkofanameritenow** [comment]
I blame Dylan.

But seriously, it should be a simple fix, right? I figure you just have to increase the bomb range values and/or modify the check to accept larger distances (so change all instances of "128" to "256" or something). Would that do it?

**Comment by PJB3005** [comment]
Yeah should be a very easy fix.
