### ISSUE TITLE
Disarm nuke?

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#11460]
Basically after Ops arm the nuke and take the disk out you have no way to disable to nuke.
Why not allow someone to hack it same way with doors but instead of wires that dont do much of anything, all the wires blow the nuke up and only 1 disarms it. And just for shits and giggles we could allow 1 wire to open the code input so you guess the code.

**Comment by PJB3005** [comment]
You already CAN "disarm" the nuke.

You can cut it loose then launch it off the Z level.

**Comment by AlphaBuffalo** [comment]
Isnt it wrenched to the floor?

**Comment by Allspice** [comment]
Weld crow weld wrench crow to lift an anchored nuke.

**Comment by AlphaBuffalo** [comment]
how about, instead of doing that isnt very realistic
we do it my way???
:^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^)
