### ISSUE TITLE
Hueg burn damage in one go does not husk properly.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11472]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 4d935af35fa01c86e8925136514deebb4f59b34d 
> 
> General description of the issue
> If someone gets >200 burn damage in one go like from touching wires with stun gloves, they die without husking. But when you burnkit them later they husk on the spot.
> 
> What you expected to happen
> Husking when getting >200 burn in one go.
> 
> What actually happened
> Nope.
> 
> Steps to reproduce if possible
> Inflict 240 burn damage on a human to kill, this will not husk. Then apply a burn kit and the human will magically husk.

**Comment by Allspice** [comment]
Fixed by 43d616e3b4e

**Comment by Exxion** [comment]
Pretty sure it actually wasn't
Especially considering this was reported about a month _after_ that commit

**Comment by ComicIronic** [comment]
That commit didn't even touch the relevant code.
