### ISSUE TITLE
advanced camera console only showing cut cams

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#11474]
Someone cut a camera
Then I went to an an advanced camera console I had constructed earlier
The only camera I could access was the one that was cut.
Restarting the game did not fix.
Reassembling the console did not fix.
![advanced cam bug](https://cloud.githubusercontent.com/assets/19157295/17798349/1e1e19ee-6596-11e6-926a-617a4c4ad1ff.png)

Someone should probably just redo the advanced sec console from scratch, it's super shitty

**Comment by Exxion** [comment]
The HTML interface maps are ultrafucked by some caching bug that may or may not be a BYOND bug, which is so unpredictable it's sometimes hard to tell whether or not a particular bug is just an extension of it

Before the camera was cut, could you access all the cameras?

**Comment by Durgen** [comment]
yeah

**Comment by Durgen** [comment]
I saw this bug again earlier today

**Comment by Shadowmech88** [comment]
Tested, could not reproduce. I deactivated a security camera, and I could still see all the others on the advanced cams console.
