### ISSUE TITLE
SUMMON GUNS DOES NOTHING DURING WIZARD WARS

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11473]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 4d935af35fa01c86e8925136514deebb4f59b34d 
> It doesn't make guns for wizards.

**Comment by Intigracy** [comment]
summon guns ignores antagonists when summoning things
who knows why it was intended this way

**Comment by Killette2** [comment]
> see guy only get 1 gun when 2 guns are summoned
> know he's an antag and shoot him on the spot

valids secured

**Comment by clusterfack** [comment]
Probably so someone doesn't become a quintuple survivor with 5 gyrojet pistols

**Comment by Shadowmech88** [comment]
What about making it exclude survivor antags specifically?

**Comment by SonixApache** [comment]
remove exclusion, ak-47s FOR EVERYONE

**Comment by ihadtoregisterforthis** [comment]
Probably so the wizard doesn't get five experimental guns straight from the start

**Comment by ComicIronic** [comment]
I think it's to prevent an easy wiz with guns. Imagine your average wizard with a C20.

**Comment by Exxion** [comment]
But then the whole crew also has guns

**Comment by Killette2** [comment]
Wizards who use guns are the worst, unless they're purely using guns and no combat magic like mage rambo.
