### ISSUE TITLE
Can't electrolyze Doctor's Delight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11476]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4d935af35fa01c86e8925136514deebb4f59b34d
> 
> General description of the issue
> I tried Electrolyzing DD from syndiecakes with a full high capacity charge, but it failed, reading "the system didn't react..."
> 
> What you expected to happen
> the wiki states that DD is a the only source of silicon outside medical. it even lists the chemical make up of DD
> "Syndie Cakes: Doctor's Delight (lime juice, orange juice, tomato juice, and tricordrazine (Carbon, Oxygen, Sugar, Nitrogen, Potassium, Silicon))"
> I expected to get a mixture of the 4 ingredients, then furhter electrolyze tricord for silicon
> What actually happened
> The system didn't react...
> 
> Steps to reproduce if possible
> -hack candy vendor
> -get syndiecakes
> -grind using mortar
> -seperate using ghetto centrifuge
> -place the beaker containing DD in electrolyzer
> -place empty beaker of same volume
> -apply fully charged high capacity cell
> -The system didn't react...

**Comment by Kurfursten** [comment]
Electrolyze silicon from silicate tanks

Further testing

> Beepsky Smash and Doctor's Delight cannot be electrolyzed - both reactions are listed directly adjacent in Chemistry-Recipes.dm
> Many other things can, including other deadrum children like brave bull
> Nothing fucky with the defines
> Was able to electrolyze chemicals listed before (toxins special) and after (irish cream) Doctor's Delight and Beepsky Smash in list order
> The recipes for DD and Beepsky Smash still work even though the electrolyzer isn't detecting them

This is a real head-scratcher.

**Comment by Killette2** [comment]
Electrolyzing being more useful when?

Imagine if we could electrolyze some chemicals that are found as is, like liquid plasma into simpler compounds for new recipies.

**Comment by Kurfursten** [comment]
At the end of the day what you're really asking for is "more chemicals".

Electrolyzing can pretty easily get you anything a chem dispenser can -  lube, thermite, smoke, etc. The thing is, there aren't just a whole lot of desirable chemicals that aren't medicine that medbay would probably give you for free anyway. I pretty much listed the big three right there.

Anything else is usually 'safe' enough that chemistry would just give it to you - metal foam, leporazine, space cleaner, diethalymine, ethylredoxadone, etc.

**Comment by Killette2** [comment]
Technically yes you can, but what I'd like is to see more than just chem dispenser chemistry. I'd like to see a wide variety of chemistry options where you could break down components to find things more easily accessible when you can't find it in the dispenser.

This is a whole other issue, but we could use a nice and massive chem overhaul, or expansion at least. Preferably the former.
