### ISSUE TITLE
Create Custom Virus Outbreak does not have a cancel option

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11477]
The title kinda says it all.

Create Custom Virus outbreak is located in the secrets panel in the admin tab, under Security level elevated.

Could do with a full rework to be a bit nicer, maybe have it be 1 window where you have the 6 options (Person to be infected, how it will spread, and the 4 virus symptoms all from dropdowns) then a submit button

**Comment by Aurx** [comment]
Closing the client "works".  Still needs a dedicated button though.
