### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11489]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)
Not a bug, just a suggestion. You might put it somewhere on web or so.
I've had ping at around 300 for very long on a good PC.
Got a fix for it.
Playing on Win 10 with compatibility set to XP makes my ping go crazy. Removing the compatibility makes it go ~ 60 again.
Have a nice day!

**Comment by Exxion** [comment]
Why did you even have it set to compatibility mode in the first place?

**Comment by ComicIronic** [comment]
y-you too

**Comment by ghost** [comment]
Windows XP compatibility mode on Win 10's necessary to use a whole heap of programmes

**Comment by Exxion** [comment]
But don't you set it per program?

**Comment by gbasood** [comment]
^

**Comment by GenericGoose** [comment]
> Why did you even have it set to compatibility mode in the first place?

more like why do people use win10 kek
