### ISSUE TITLE
HydroHUD Glasses

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#11496]
Engineering has optical material scanners
Sec has SecHUD
Medbay has MedHUD

It's time for the botanical option. This HUD would display
- All normal health indicators of a tray over normal soil plots (water, pests, toxicity, lighting, weeds, fertilizer, ready to harvest, dying)
- Progress bar displaying how much milk goats and cows have left (udder.total_volume / 50)
- Progress bar showing chicken feeding status (min(eggs_left,8) / 8)
- Progress bar displaying progress of a chick toward growing (amount_grown / 100)
- Progress bar until next harvest over all trays and soil plots. (age - lastproduce / seed.production)

Optional:
- Allow you to examine tray contents from more than 1 tile away
- Examining a seed packet or fruit automatically brings up the plant analyzer info

Please skip the "don't tell me you're wearing glasses on a botany mission" / "my farming is augmented" jokes

**Comment by CptWad** [comment]
![crop](https://cloud.githubusercontent.com/assets/3959840/17829063/59538934-6656-11e6-86b2-422afab3848c.png)
wow spriting is fun

**Comment by Killette2** [comment]
I think an upgraded hydroponics scanner that could tell more stats that are hidden would be amazing.

**Comment by FudgePucker** [comment]
@CptWad I like it. Got that hippy 70's feeling to it.

**Comment by Kurfursten** [comment]
@CptWad Can you give me the original dmi version, or a 32x32 PNG?

**Comment by CptWad** [comment]
oh wow, I am pretty sure I have NO copies of that

**Comment by Kurfursten** [comment]
It's okay, the overlays gave me trouble anyway and I decided to shelve it again

I may pick it up again in another few months or year
