### ISSUE TITLE
Biodome vault SMES improperly set up

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#11497]
It's not wired (has no terminal) so it can't be used

**Comment by ghost** [comment]
welp

**Comment by ghost** [comment]
Testing it, the biodome wiring entirely doesn't seem to have a powergrid at all. The wires don't seem to interact with one another

**Comment by Kurfursten** [comment]
Viewed in the editor it _appears_ to have a terminal and be all connected, so it's very odd that it has the behavior you describe. It certainly explains the bug though.

I wonder if vaults can't handle wiring? I can't think of any others that use it.

**Comment by PJB3005** [comment]
Uh.

I ran across the same issue when I made my Syndicate Listening Post vault, and I fixed it by moving powernet generation AFTER vault generation (like it should be).

I have no idea why it's broken again now.

**Comment by Kurfursten** [comment]
This was fixed
