### ISSUE TITLE
PACMAN rebuilds EVERY POWERNET when you (un)wrench it.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#11506]
``` DM
   else if(!active)
        if(istype(O, /obj/item/weapon/wrench))
            anchored = !anchored
            playsound(src.loc, 'sound/items/Deconstruct.ogg', 50, 1)
            if(anchored)
                to_chat(user, "<span class='notice'>You secure the generator to the floor.</span>")
            else
                to_chat(user, "<span class='notice'>You unsecure the generator from the floor.</span>")
            makepowernets()
```

**Comment by ghost** [comment]
All hail the PACMAN

**Comment by ghost** [comment]
What does this mean?

**Comment by PJB3005** [comment]
Somebody spamming a wrench on a pacman can bring the entire server to its knees.

**Comment by ghost** [comment]
Oh boy

**Comment by kol1th** [comment]
TIME TO GRIFF

**Comment by clusterfack** [comment]
Well it has a cooldown between wrenching and unwrenching, so its not as bad as all that

**Comment by ihadtoregisterforthis** [comment]
You can have many

**Comment by PJB3005** [comment]
Nope.

What makes this worse is that due to the PACMAN being snowflake in how it does wrenching, it doesn't even have a cooldown.

**Comment by Jalleo** [comment]
Port the TG pacman it does not have this issue.

**Comment by ghost** [comment]
Huh, so is this the difference that makes it so that the pacmans will output no problem but an smes you have to cut and mend or lay the cable after you build a new smes?

**Comment by PJB3005** [comment]
So it turns out this can be neverminded.

The file this code is in is unused and dead and I didn't realize.

**Comment by Exxion** [comment]
I love those files
Just delete it to avoid further confusion
