### ISSUE TITLE
Ghosts only hear AI holopad messages if they're in view

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11515]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a82ab687e6d58ff5c706634e5e4f0c80fa66a350 
> 
> General description of the issue
> Regardless of ghostears/ghostsight preferences, ghosts can only see AI holopad messages if the holopad is actually in view
> 
> What you expected to happen
> To see the messages no matter where I was
> 
> What actually happened
> Need to be at the holopad to see secret AI conversations
> 
> Steps to reproduce if possible
> Get an AI to talk through the holopad, don't be near it

**Comment by ComicIronic** [comment]
Known issue with virtual hearers not inheriting sight flags, @Clusterfack is going to fix it.

**Comment by clusterfack** [comment]
I think this is actually not related to that, but more related to the fact its simply only sending holopad messages through visible_message, which doesn't take into account ghostears?

**Comment by gbasood** [comment]
sounds a lot like #10890
