### ISSUE TITLE
Attention all Codermins

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#11524]
If you have admin rank, I need you to send me a forum PM (or post in the contact information thread in the admin subforum if you have access, either works) containing some form of contact method.  Steam profile link, email address, etc.  This will not be made public (unless you post it publically) and will be headmin and subheadmin access only.  
Anyone who hasn't provided such within two weeks will be removed from admin status.  

Maintaners: Please leave this open for two weeks, then do whatever with it.  Or trash it and pass the message on some other way if there's sekrit coder communications networks I'm unaware of.

**Comment by clusterfack** [comment]
I don't know what you think contact information is, I'm more easily contacted through any of the methods that already exist like discord or IRC.

**Comment by Aurx** [comment]
It needs to be some form of thing that permits just dumping a message and sitting on it with no need to play "I sure hope this guy and I log in at the same time". IE, some way you can be sent a message whenever and get it when you check that sevice.  
If discord supports this, then yeah that works fine.

**Comment by Exxion** [comment]
Yeah, Discord does. Just @ the person you want to contact.
Or send them a personal message actually
Why didn't I say that first?

**Comment by ghost** [comment]
IRC supports that, too. Just not privately.

**Comment by ghost** [comment]
But re: "I sure hope this guy and I log in at the same time". Don't worry our coders don't sleep, eat, breath or do human things such as feel emotion.

**Comment by Aurx** [comment]
Great.  Then just PM me your IRC/discord nick and you'll be good.

**Comment by PJB3005** [comment]
IRC doesn't do that if you're not on the server when you get pinged.

**Comment by ghost** [comment]
You can leave a message with "nt, tell"

**Comment by Aurx** [comment]
And time's up.  This can be closed now.
