### ISSUE TITLE
So this just happened. I think its parallax.

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#11522]
Title. BYOND version 511.1549

![](http://i.imgur.com/iLkjHSx.png)

**Comment by Exxion** [comment]
Turn parallax off and see if it's fixed

But yes, it probably is parallax

**Comment by AlphaBuffalo** [comment]
Reloading did fix it

**Comment by Exxion** [comment]
Reloading as in exiting and rejoining, or reloading as in just turning parallax off and back on?

**Comment by AlphaBuffalo** [comment]
exiting and rejoining

**Comment by Exxion** [comment]
It's PROBABLY a BYOND bug, but let's ask @clusterfack just to be sure

**Comment by clusterfack** [comment]
You turned off graphics hardware rendering

**Comment by AlphaBuffalo** [comment]
I didn't though, I never even touched it

**Comment by clusterfack** [comment]
Then your computer did
