### ISSUE TITLE
Sprites: ghost spells

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11527]
i think it would be convenient to have the most used ghost verbs as spells, so i made some sprites.
i don't have experience at spriting so, of course,  feel free to propose better sprites.

from left to right: 
- for both "ghost" and "re-enter corpse" v1, v2
- haunt v1, v2
- teleport
- toggle darkness
- toggle medichud v1, v2, v3, v4

![ghost_spells_demo](https://cloud.githubusercontent.com/assets/6170726/17852705/e0b51da2-6868-11e6-92d9-c747b22d965f.png)

transparent icons 32x32
![ghost_icons](https://cloud.githubusercontent.com/assets/6170726/17852709/e674c6ca-6868-11e6-8fa0-5a0dcc40145b.png) **<===(wrong clown sprites, fix below)===**

as a side note, tooltips to show the spell name could be also useful.

UPDATE
added "hide sprite"
![hide_demo](https://cloud.githubusercontent.com/assets/6170726/17856507/3382757e-687e-11e6-8184-169a3c132b7e.png)

transparent icon 32x32
![icon_hide](https://cloud.githubusercontent.com/assets/6170726/17856517/4060f036-687e-11e6-86fe-0f80489c9f1f.png)
^^^
it's here

UPDATE 2
better sprites for "toggle medichud" v3 and v4 (yes, i have too much time to waste) 
![mh_v3_v4_big](https://cloud.githubusercontent.com/assets/6170726/17866665/aefa8f6a-68a7-11e6-9930-e44b432d9805.png)

transparent icons 32x32
![mh_v3_v4_icons](https://cloud.githubusercontent.com/assets/6170726/17866686/c25753c2-68a7-11e6-9c3a-3e437f2d612a.png) **<===(wrong clown sprite, fix below)===**

haunt v3 v4 
![haunt_v3_v4_icons_big](https://cloud.githubusercontent.com/assets/6170726/17867866/859379e8-68ac-11e6-96d1-40f219cff5f0.png)

transparent icons 32x32
![haunt_v3_v4_icons](https://cloud.githubusercontent.com/assets/6170726/17867871/8ed827ec-68ac-11e6-9df5-7298ed8f4257.png) **<===(wrong clown sprite, fix below)===**

UPDATE 3
fixed the transparent icons for the clown hands and backpack:

various icons, toggle medichud v3 and v4 deleted
![icons](https://cloud.githubusercontent.com/assets/6170726/17885715/bba6a09c-691e-11e6-94df-1e58a29cd055.png)

toggle medichud v3 v4 fixed
![mh_v3_v4](https://cloud.githubusercontent.com/assets/6170726/17885723/c40940be-691e-11e6-9384-8e7375251caf.png)

haunt v3 v4
![haunt_v3_v4](https://cloud.githubusercontent.com/assets/6170726/17885727/c7a76926-691e-11e6-83ad-a63b8ea9377b.png)

UPDATE 4
toggle darkness, lights on
![lighton_icon_big](https://cloud.githubusercontent.com/assets/6170726/17932152/fa9959d4-6a0e-11e6-9c4e-8b0b155582a5.png)

transparent icon 32x32
![lighton_icon](https://cloud.githubusercontent.com/assets/6170726/17932177/0dc7e7d2-6a0f-11e6-89fe-fb063b7ab78c.png)

UPDATE 5
i dont know if you're going to add a "toggle show/hide other ghosts" option, so i made a couple of sprites just in case.
![hide_ghosts_big](https://cloud.githubusercontent.com/assets/6170726/18231467/a2acbe8c-72ba-11e6-9b82-50447914229b.png)
hide, show and, if you prefere, a single icon for both.

transparent icons 32x32
![hide_ghosts](https://cloud.githubusercontent.com/assets/6170726/18231470/ad862bc2-72ba-11e6-84ac-72f03f6d084b.png)
^^^^^^^^^
here.

**Comment by JustSumBody** [comment]
A general "Change HUD" button may be nice for other HUD types (Muh antagHUD)
But I like it

**Comment by ComicIronic** [comment]
This is a good idea for HUDs, but it would be more appropriate in something like TGs action datum system, rather than proper spells.

**Comment by uazuaz** [comment]
added "hide sprite"
![hide_demo](https://cloud.githubusercontent.com/assets/6170726/17856507/3382757e-687e-11e6-8184-169a3c132b7e.png)

transparent icon 32x32
![icon_hide](https://cloud.githubusercontent.com/assets/6170726/17856517/4060f036-687e-11e6-86fe-0f80489c9f1f.png)
^^^
it's here

**Comment by clusterfack** [comment]
Need all of these without the background

**Comment by uazuaz** [comment]
@clusterfack 
they're already there, under "transparent icons 32x32".

**Comment by clusterfack** [comment]
Ah yeah

**Comment by uazuaz** [comment]
better sprites for "toggle medichud" v3 and v4 (yes, i have too much time to waste)
![mh_v3_v4_big](https://cloud.githubusercontent.com/assets/6170726/17866665/aefa8f6a-68a7-11e6-9930-e44b432d9805.png)

transparent icons 32x32
![mh_v3_v4_icons](https://cloud.githubusercontent.com/assets/6170726/17866686/c25753c2-68a7-11e6-9c3a-3e437f2d612a.png)

haunt v3 v4
![haunt_v3_v4_icons_big](https://cloud.githubusercontent.com/assets/6170726/17867866/859379e8-68ac-11e6-96d1-40f219cff5f0.png)

transparent icons 32x32
![haunt_v3_v4_icons](https://cloud.githubusercontent.com/assets/6170726/17867871/8ed827ec-68ac-11e6-9df5-7298ed8f4257.png)

**Comment by Ephx1** [comment]
CLOWNS DON'T HAVE GLOVES YOU FUCK

**Comment by uazuaz** [comment]
@Ephx1 
i used the sprite on the clown page on the wiki, it's their fault!
by the way i could fix it for real if you want.

**Comment by uazuaz** [comment]
ok, i actually fixed the transparent icons for the clown hands and backpack:

various icons, toggle medichud v3 and v4 deleted
![icons](https://cloud.githubusercontent.com/assets/6170726/17885715/bba6a09c-691e-11e6-94df-1e58a29cd055.png)

toggle medichud v3 v4 fixed
![mh_v3_v4](https://cloud.githubusercontent.com/assets/6170726/17885723/c40940be-691e-11e6-9384-8e7375251caf.png)

haunt v3 v4
![haunt_v3_v4](https://cloud.githubusercontent.com/assets/6170726/17885727/c7a76926-691e-11e6-83ad-a63b8ea9377b.png)

updated also the OP.

**Comment by Ephx1** [comment]
Nah I was mostly just messing around, your normal sprites are fine, for the longest time I thought clowns should actually have gloves.

**Comment by uazuaz** [comment]
i knew it, but my compulsion couldn't stand that.

**Comment by clusterfack** [comment]
Can you make a 'lit up' version of toggle darkness, that gets toggled on when I toggle darkness

**Comment by uazuaz** [comment]
@clusterfack 
i've tried something simple, i don't know if i could do something better.
![lighton_icon_big](https://cloud.githubusercontent.com/assets/6170726/17932152/fa9959d4-6a0e-11e6-9c4e-8b0b155582a5.png)

transparent icon 32x32
![lighton_icon](https://cloud.githubusercontent.com/assets/6170726/17932177/0dc7e7d2-6a0f-11e6-89fe-fb063b7ab78c.png)

**Comment by clusterfack** [comment]
Thanks

**Comment by uazuaz** [comment]
i dont know if you're going to add a "toggle show/hide other ghosts" option, so i made a couple of sprites just in case.
![hide_ghosts_big](https://cloud.githubusercontent.com/assets/6170726/18231467/a2acbe8c-72ba-11e6-9b82-50447914229b.png)
hide, show and, if you prefere, a single icon for both.

transparent icons 32x32
![hide_ghosts](https://cloud.githubusercontent.com/assets/6170726/18231470/ad862bc2-72ba-11e6-84ac-72f03f6d084b.png)
^^^^^^^^^
here.
