### ISSUE TITLE
Make the Nuke Ops shuttle be further away from the station or something

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#11525]
Some of the docking areas are way too close to the station and it brings up that whole "metagaming" thing. Like currently you can see the shuttle from solars and shit like that. With our maps being 500x500 or whatever can't we have it deeper in space or something, to make it more clear when people are being meta dicks

**Comment by ghost** [comment]
This is a good idea, especially now the map is huge. It'll cause a couple 'where the hell are we' kinda thing for a while, but as long as the docking stations have ONE straight path to the station so people don't have to try and wiggle diagonally down from it, it should be fine.

**Comment by ghost** [comment]
With #11517 you wouldn't even have to worry about that, @whorena

**Comment by Exxion** [comment]
That's for deathsquaddies
A nuke ops version is being considered but not part of that PR

**Comment by FudgePucker** [comment]
Most of the time I have that where the hell am I problem as is as new cop.
First time I just ended up on another z level.

**Comment by Intigracy** [comment]
Why don't we just - here it's a doozy so I'll go slow - let's put a button on the inside and outside of the airlock that toggles the shutters and, and you're really gonna go crazy when I say this, how about we make it require syndicate access to push the button, which just so happens to permanently be on every agent ID?

**Comment by Exxion** [comment]
The problem is people easily seeing the ship from the station, not necessarily stealing it

**Comment by JMWTurner** [comment]
Once the Deathsquad PR gets through, I'll make one for the nuke ops. Their suits will also track the position of their ship.
