### ISSUE TITLE
Necromancy Rod body swap

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11526]
(WEB REPORT BY: codenameb REMOTE: 172.93.109.202:7777)

> Revision: fb655fea69f0c06fd0556c5c90cd5fb26d8f0fb6 
> General description of the issue
> If you die during a round, and you are turned into a wizard, using the wand of necromancy on your former corpse swaps your body into that of the zombie, which you can then control. There is no way to get back in the wizard body.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by gbasood** [comment]
pretty much the same as #13805
