### ISSUE TITLE
Ghost fire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11531]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> After some time of burning I couldnt get extinguished  (maybe ghost fire), rolling on the floor didnt even initiate.
> 
> What you expected to happen
> To cease the fire, however, on my sprite im still on fire.
> 
> What actually happened
> Nothing as if I wasnt at fire
> 
> Steps to reproduce if possible
> Phew, dunno, get on fire? Was just plasma

**Comment by nervere** [comment]
Definitely not an issue anymore.
