### ISSUE TITLE
Mindswap targetting is completely broken

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#11537]
Never given a list of targets
Also you can mindswap ACROSS THE STATION because the target it picks is seemingly at random
Although it might not be random, it might be selecting targets  from the original wizard body's location.
@clusterfack

**Comment by ghost** [comment]
"I fixed it" t. cluster

**Comment by gbasood** [comment]
I'm actually pretty sure in retrospect it's picking targets based on original body's loc

**Comment by ghost** [comment]
💯

**Comment by clusterfack** [comment]
"I fixed it" -Celt after it was totally broken as bad as it ever was

**Comment by clusterfack** [comment]
Besides if this does occur it would have only been noticeable with 3 or more people, I tested it with 2. More than Celt's testing it with NO TESTING.

**Comment by ghost** [comment]
I did test it, and it worked for the case I was fixing.
It just so happens there were a thousand other problems with the spell, as this issue demonstrates.

**Comment by clusterfack** [comment]
Kek absolute bullshit. It did not work at all when I went to test it.

**Comment by SonixApache** [comment]
I noticed this as wizman the other day; blink, forcewall and other spells are still linked to your original body when mindswapped.
