### ISSUE TITLE
On shiftclick im vox, but not human

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11533]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> So I am a human but shift clicking myself I see a mini Vox figure.
> 
> What you expected to happen
> Its pretty clear - to see a human figure.
> 
> What actually happened
> A vox figure appeared.
> 
> Steps to reproduce if possible
> Maybe play Vox for some time and then switch?

**Comment by Exxion** [comment]
It's a known issue, dating back to... the introduction of Goonchat, I believe? I think this is a duplicate but I'll leave it open for now, at least

Also @PJB3005 
Can you fix this already? It's been MONTHS

**Comment by ghost** [comment]
Thanks PJB

**Comment by Kurfursten** [comment]
If we want to prioritize a long due sprite fix, I'd rather get shield generators and RUST parts back to normal. Since those actually affect the round.

**Comment by PJB3005** [comment]
@Kurfursten I already fixed that.

Did forget to close the issues though.

**Comment by Exxion** [comment]
It's not really a sprite fix anyway

**Comment by clusterfack** [comment]
Just have it not output a sprite in the first place

**Comment by Kurfursten** [comment]
This is no longer a thing as it does not put an icon at all

**Comment by DamianX** [comment]
Fixed by #15049 before the icon was removed for mobs
