### ISSUE TITLE
Actually, everyone is Vox on minipicture

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11534]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> According to my previous report (should be just below) - it is not only me, but everyone on station has that Vox minifigure there.
> 
> What you expected to happen
> To have the actual race there.
> 
> What actually happened
> Everyone is Vox. Fuck.
> 
> Steps to reproduce if possible
> No idea

**Comment by Exxion** [comment]
Damn it it varies
And this one's DEFINITELY a duplicate
