### ISSUE TITLE
Posibrain ping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11532]
(WEB REPORT BY: mal23 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Posibrain pings even when claimed
> 
> What you expected to happen
> It should't ping when claimed
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
Wasn't this allegedly fixed just a few days ago?

**Comment by ghost** [comment]
I added a check and everything, how the hell?

**Comment by SonixApache** [comment]
this is fixed

**Comment by Exxion** [comment]
*shrug
