### ISSUE TITLE
Being catbeasted removes wizard spells

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#11538]

**Comment by PJB3005** [comment]
I fail to see the problem here.

**Comment by gbasood** [comment]
Being cloned keeps your spells
Being mindswapped keeps your spells
Why would being transformed NOT

**Comment by ComicIronic** [comment]
Because you can be transformed to and from things with spells, and if you kept them, that would be bad. I'm sure there's a historical issue for this.

**Comment by ComicIronic** [comment]
#9955

**Comment by gbasood** [comment]
Since the other issue is apparently not important enough:
Should being transformed to another type of human really de-wiz you?

**Comment by TheFriggenSawbones** [comment]
its kinda fucky yeah and probably shouldn't work like that

**Comment by gbasood** [comment]
Reopened for discussion

**Comment by Allspice** [comment]
I think getting cloned removes wizard spells.

**Comment by gbasood** [comment]
It didn't for me in that same round

**Comment by SonixApache** [comment]
humanoids yes, jaunting xenoborgs pls no

**Comment by Shadowmech88** [comment]
Changing bodies through any means now removes spells, so this is no longer an inconsistency.
