### ISSUE TITLE
Should blobs and xenomorphs prevent the shuttle being called if they're on the main station z-level?

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#11541]
Could be done pretty easily in code

```
for player in playerlist
  if istype blob or if istype xeno
     if player.z == map.zMainStation
         return noshuttlecontainyourspacedemons
```

I think it's a pretty hardcore restriction so it might not be right but I want to see other people's opinions

**Comment by Ephx1** [comment]
Blob no because they always come late and it's just an excuse to call the shuttle at that point.
Xenomorphs only after a certain amount of xenos should it be denied.

**Comment by Killette2** [comment]
Again, the problem with xenos is the time it takes facehuggers to chestburst.
It was made long so humans have time to receive surgery, however every xeno nest starts off with monkeys.
What if we made monkeys burst faster instead of trying all these other ideas, so aliens can grow at a decent rate when first starting off.

**Comment by gbasood** [comment]
@Killette2 I mean those two issues are separate in my mind but I like that suggestion
This is more to remedy the fact that centcomm wouldn't want to risk xeno infestation at centcomm and would probably not rescue you

**Comment by CptWad** [comment]
only if theres a queen
meaning if they call the shuttle right after the xenos spawn or after killing the queen then I'd think its kosher
as for blobs, nah

**Comment by gbasood** [comment]
I like the queen thing

**Comment by ihadtoregisterforthis** [comment]
Wouldn't help at all if the queen evolves after the shuttle it's called but alright.

**Comment by Allspice** [comment]
Deadpoop extended with the only admin watching chink cartoons when aleiums hit, shuttle literally never.

In general I dislike things that prevent a shuttle call; at least with blob mode that ends when the blob dominates, but you can't say the same for xenos.

**Comment by gbasood** [comment]
@ihadtoregisterforthis I feel like, from an IC perspective, it still makes sense.
@Allspice That's the only thing I'm not sure how to solve. We could:
- Prevent calls while admins are on ONLY
- Require a minimum pop count
- ????

**Comment by clusterfack** [comment]
Lifeforms have been detected on the station.

>SHUTTLE CALLED reason: TEST CALL

**Comment by CptWad** [comment]
eheheheh

**Comment by ghost** [comment]
From a balance perspective, this would only be ok if there were round ending victory conditions for both xenomorphs and blobs.  These conditions would be available upon the inability to call the shuttle being triggered.

**Comment by ghost** [comment]
If you're gonna have blobs and xenos prevent a shuttle call, there needs to be some form of over-ride that can be done.

I'd say by either ERT or deathsquad, so if they're called to capture some xeno specimens for central command, or to call in and say 'station's fucked completely, call in the demolition squad'

**Comment by gbasood** [comment]
@clusterfack 

> Newcap2016 has been banned. Reason: metagaymin

**Comment by Shadowmech88** [comment]
> SHUTTLE CALLED reason: I'M BORED, NO OTHER REASON, AND YOU CAN'T PROVE OTHERWISE

**Comment by gbasood** [comment]
So okay, in that case, let's think about how Centcomm would respond to a shuttle call on a station they knew had ayys.
They could go full Weyland-Yutani and say they're sending EVAC but in reality do something like
- Send a deathsquad
- Say they're sending a shuttle but when the timer ends it doesn't show up

**Comment by Allspice** [comment]
The station isn't based on SENSIBLE THINGS, sood. Otherwise the AI wouldn't be one well-worded order away from subversion, the armoury wouldn't be facing space when there's 300 space suits to break in with, and the singu would not exist at all.

Anyway, I'll phrase my objections slightly differently. This seems like an excuse to draw out rounds an hour past the point where everyone wanted to fuck off, and I do not find that fun.

**Comment by AlphaBuffalo** [comment]
What if aliens on the shuttles prevent the shuttle from launching? Most aliens bum rush the shuttle anyways and if they can prevent it from launching long enough or after the entire crew is dead or after there are x aliens the round ends?

**Comment by gbasood** [comment]
I don't know, I think that if we were to make this, we'd need ayys as antags. Which they aren't currently.

**Comment by PJB3005** [comment]
ANTAG

DATUMS.
