### ISSUE TITLE
What if hardcore mode was enabled by default

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#11545]
It takes ages to actually starve to death, and way before you actually die you're spammed with messages telling you to eat something

What do you guys think

**Comment by kol1th** [comment]
what if people played chef

**Comment by jknpj** [comment]
We would see way more plasmamen, since they don't need to eat at all.

**Comment by Killette2** [comment]
What if people played X job?
What if X job was worth playing

**Comment by AutismSpider** [comment]
Man what? Food not that big of a deal when i can suck down ice cream cost nothing to make

**Comment by ghost** [comment]
hardcore mode is ruined by the goof cooking free nutriment from nowhere.

**Comment by Killette2** [comment]
> RP is ruined by people who chose to powergame

Really makes you think huh?
