### ISSUE TITLE
MoMMIs can put their tools into supermatter shards infinitely

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11550]
(WEB REPORT BY: miningpig REMOTE: 172.93.109.202:7777)
921cc9faf4704e0ebe519f8e45841603c65e53a4 

> General description of the issue
> A MoMMI can run around with the supermatter shard and infinitely put it's crowbar/anything else into it, killing everybody with radiation
> 
> What you expected to happen
> For the tools to be destroyed/for the MoMMI to be destroyed since the tools are a part of the MoMMI
> 
> What actually happened
> MoMMI touches a crowbar to Supermatter Shard as a silence fills the room...

As Supermatter Shard slowly stops resonating, you find your skin covered in new radiation burns.

MoMMI touches a crowbar to Supermatter Shard as a silence fills the room...

As Supermatter Shard slowly stops resonating, you find your skin covered in new radiation burns.

> Steps to reproduce if possible
> Be MoMMI

get shard

Hit shard with crowbar forever

**Comment by JustSumBody** [comment]
same issue as #11467 for the record
