### ISSUE TITLE
Buildmode is broken

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#11553]
Mass filling in advanced build mode spawns closets. Always. No matter what.

**Comment by JustSumBody** [comment]
Wew, I thought I was just using it wrong this whole time.

**Comment by PJB3005** [comment]
Should just use SDQL tbh.

**Comment by Exxion** [comment]
This must have broken pretty recently, because just a couple months ago (if that) I was using advanced buildmode fill and it was working perfectly

**Comment by Exxion** [comment]
Wait never mind
This actually works fine right now
You just have to select the type by right-clicking the buildmode button rather than copying an atom with middle click

**Comment by Exxion** [comment]
Tagging this feature request because it would be nice if atom cloning worked with filling
