### ISSUE TITLE
"You're on fire."

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11576]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8b80edba9d7c2adce0bd948ccd5d8ef840172871
> 
> General description of the issue
> as a diona, getting lit on fire by a pie tin will give you flames that don't go out, causing you to glow and look awesome.
> 
> What you expected to happen
> IT BURNS OH GOD IT BURNS
> 
> What actually happened
> you look pretty cool instead.
> 
> Steps to reproduce if possible
> be diona. Make pie tin fire. Step into fire. Flame does not go out.

**Comment by SkowronX** [comment]
Probably just calling ignite() without any arguments.
