### ISSUE TITLE
Airgroups are busted or something

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11585]
#### Description of issue

Air doesn't work properly, some tiles in a region just straight up don't change when the rest of it is
![airgroups](https://cloud.githubusercontent.com/assets/19365096/17991889/96d94276-6b10-11e6-9a93-5f58d12997fd.png)
![airgroups2](https://cloud.githubusercontent.com/assets/19365096/17991890/98a76a88-6b10-11e6-8133-ee9e7b53b057.png)
In this case, the shard wasn't cooling
This also causes telecomms to break constantly(supposedly it's happened the past few rounds as well?) , there were something like 10 odd different temperatures on different tiles throughout the chamber.

![airgroups3](https://cloud.githubusercontent.com/assets/19365096/17991892/9b50b938-6b10-11e6-888c-6089859bf6d7.png)
There's also some shit going on with pressure difference warnings when windows are broken or false walls are constructed

Bit more info I've gathered: A "fix" I've heard is to RCD the floors and reconstruct them, supposedly it fixes things?
Also shit like gas injectors apparently keeps all the gas on its tile or something I'm not seeing plasma or N2O right in the big air tanks
#### Length of time in which bug has been known to occur

A day or two ago? I want to say this has to do with the ZAS pulling fix because of its recency but I got no idea
#### Server revision

d1cf51919ed9e3c6dae9eb86b76c2742dfc496b1

**Comment by kol1th** [comment]
oh NO

**Comment by Exxion** [comment]
I really can't imagine how the ZAS pulling thing could have caused this, but ZAS is kind of an unintelligible eldritch monstrosity so who fucking knows?

**Comment by ghost** [comment]
And here's one of telcomms from that round. Both this round and the previous round some of the machinerythat produce heat and the hub got fried.

The two that fried in the pic were the hub and the second server up from the bottom left before I started turning shit off and bypassing. Ignore the blue x's, they were supposed to be the telcomms general -193C when I remembered receivers and shit don't put out major heat if at all.

![busted telcomms](https://cloud.githubusercontent.com/assets/5564796/17992445/d112db22-6af3-11e6-89bc-461852b6ff95.png)

**Comment by ghost** [comment]
This was a problem from before ZAS pulling was fixed

**Comment by PJB3005** [comment]
Yeah but it was never this extreme.

**Comment by PJB3005** [comment]
How often does this happen because I'm gonna begin bisecting with Git.

**Comment by clusterfack** [comment]
Yeah VV the tile for blocks_air, the mappers most likely fucked up

**Comment by Exxion** [comment]
Also VV for `zone` because I think something is fucking up there

**Comment by jknpj** [comment]
1X1 SMEs are the new meta. Also, how does this affect the gas miners and the station's atmos?

**Comment by Exxion** [comment]
Probably badly

**Comment by clusterfack** [comment]
Yeah it probably doesn't affect jack shit because this is just a tile based thing with blocks_air

**Comment by Exxion** [comment]
It is not, or else it would happen every round

**Comment by clusterfack** [comment]
That is 100% the issue I can guarantee you

**Comment by Exxion** [comment]
Exactly 21 instances of `blocks_air = 1` are in the entirety of tgstation.dmm and exactly zero of them are in the telecomms area.

**Comment by AlphaBuffalo** [comment]
Maybe this could be a good thing? Zas needed some patches anyways

**Comment by jknpj** [comment]
Recently i found an cool on touch atifact. Engineering was building the chamber while i was showing it to the captain, in the SME room. After touching it a few times the whole room was at wooping 1kpa -274 degrres and now comes the good part: after the engineers removed a wall to use the AME room's space the air inside the AME room stayed at 101.35 kpa 20 degrees. dragging the artifact to inside the AME room colled EVERY TILE IT PASSED BY but the rest of the room was still at 101/20. Did i mention we didn't experience any ZAS in the AME room? I need to test more things but i'm pretty sure the SME had at least 4 different temperatures, too.

**Comment by Exxion** [comment]
We decided in the Discord that what is PROBABLY happening is that, for some reason, zones are getting invalidated and deleted and aren't reforming
No idea why, though

**Comment by ihadtoregisterforthis** [comment]
Just to be sure check what the AME room is made of
![system hub x-ray 2015-10-04 212510](https://cloud.githubusercontent.com/assets/13305885/18072703/99379e22-6e36-11e6-9068-9b1cddc7c5e6.png)

**Comment by Exxion** [comment]
That specific one actually is a mapping error

**Comment by uazuaz** [comment]
maybe it's related, so i'm posting it here.
in the last round, a couple of engineers plasmaflooded by mistake the SME room and the near corridor.
the plasma in the room was scrubbed in few minutes, then a guy hacked open the external airlocks on the corridor to vent the plasma in space; the issue is that, after about 10-15 minutes, the situation was just the same as before he opened the airlocks; as an observer i checked the air multiple times and the air pressure and composition on these 2 tiles never changed (you can see my ghost on the checked tiles), disregarding the opened airlocks.
![zas](https://cloud.githubusercontent.com/assets/6170726/18133908/ad128364-6f9c-11e6-8077-45f211f961d9.png)

**Comment by Exxion** [comment]
That one is probably also a mapping problem
Oldcoders varedited a bunch of external airlock tiles to block air. We got rid of most of them, but not all.

**Comment by Exxion** [comment]
It has been positively confirmed that this was caused by the same completely incomprehensible "Out of resources!" runtime(s) that happened while the repo was DMCAed.
Probably a BYOND bug, but fuck if I know for sure.
Both times it happened, there were no code changes when it started happening and it resolved itself several rounds later ALSO with no code changes.

If it happens again, have an admin with +DEBUG run the following SDQL query, which will fix air for the remainder of the round:
`CALL update_air_properties() ON /turf/simulated`

**Comment by Exxion** [comment]
This was fixed when we removed the `turfs` list
For anyone curious, BYOND doesn't like copying (which it has to do to loop through) a list 1.5 million entries long and would sometimes run out of memory, crashing EVERYTHING with no survivors in world startup
