### ISSUE TITLE
Firebird

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11587]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d1cf51919ed9e3c6dae9eb86b76c2742dfc496b1 
> 
> General description of the issue
> Firebird is unable to be used to fly through space anymore
> 
> What you expected to happen
> Fly through space
> 
> What actually happened
> not flying through space
> 
> Steps to reproduce if possible
> Get firebird, try to fly in space, fail and end up in deep space

**Comment by Exxion** [comment]
This is intentional
And has been the case for like
Months

**Comment by AI-Is-Rogue** [comment]
I swore I saw it used in space less than a month ago.

**Comment by Exxion** [comment]
Wait
I might be remembering incorrectly, actually
It was nerfed a lot but I'm suddenly not sure that was part of it
I'll just let someone else tag it

**Comment by AI-Is-Rogue** [comment]
I imagine it was caused by the space physics PR.

**Comment by Exxion** [comment]
That's definitely not impossible
