### ISSUE TITLE
Hand teleporter duplicates items or something when you equip/store them

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11588]
#### Description of issue

Behold, advanced teleportation
![image](http://i.imgur.com/GjMWSf1.gif)
#### Difference between expected and actual behavior

No double trouble
#### Steps to reproduce

Use the hand teleporter 
shuffle around with your inventory(put the hand tele in your pocket/bag/belt, move around your ID, etc) on the same tile as the portal
hear it all get "teleported" away
There is now a duplicate of that item at the exit portal
In the case of duplicating a hand teleporter: you can then later teleport to this second one.
#### Specific information for locating

Not sure exactly, but I suspect it has something to do with equipping/shuffling inventory spots calling drop first and then putting the thing in the right place
#### Length of time in which bug has been known to occur

I feel like I've started getting ahelps about this way more recently, but I'm pretty sure it's been around for quite a while longer
#### Server revision

d1cf51919ed9e3c6dae9eb86b76c2742dfc496b1 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SkowronX** [comment]
The instance of the item somehow leaves the contents of the mob?

**Comment by clusterfack** [comment]
There isn't such a thing as duplication, but it is being taken from your mob while remaining in your hud.

**Comment by PJB3005** [comment]
Yeah I've experienced this it's super weird.

**Comment by Kurfursten** [comment]
Reminds me of stuff we saw in a lot of places lacking forcemove

**Comment by Exxion** [comment]
forceMove() wouldn't fix this
