### ISSUE TITLE
Cannot load bullets into 12mm magazine

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11599]
(WEB REPORT BY: iroquoispliskin REMOTE: 172.93.109.202:7777)

> make it work again 
> 
> bullets will not load into the magazine
> 
> bullets to go into the magazine
> 
> bullets did not go into magazine
> 
> > grab 12mm magazine >grab 12mm bullet > try to load magazine >???? >profit

**Comment by SonixApache** [comment]
Confirmed.
Specifically, 12mm (R&D assault rifle) magazines have completely ceased function.
