### ISSUE TITLE
Possess/Release Obj needs to be burned down and rebuilt from scratch

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#11592]
1. Release Obj is a verb that is always available on any object, regardless of whether or not you'e posessing it, or anything else for that matter.
2. Possessing something as a ghost and then moving makes your ghost exit the possessed object by one tile.
3. If the object you're possessing is destroyed, your eye follows it to nullspace and you're just shit out of luck unless you can find the object to release in the Release Obj list of all objects in the entire world.
4. Possessing a canister with godmode off kills you due to pressure, etc.
5. Probably more things

**Comment by Intigracy** [comment]
Actually, with the nullspace thing, I'm fairly sure you can just type release-obj and then teleport to someone to fix it.

**Comment by Exxion** [comment]
Fuck you Comic
At least half the things I said there are bugs

**Comment by Shadowmech88** [comment]
What is the purpose of possess/release object? Is it just moving things? Why have a verb for that at all?
I feel like a mob with spells to become intangible and invisible that can lock things to itself would be a more fluid solution. Just spawn one, possess it, lock something to yourself, and it looks as though it's just the thing moving.

**Comment by Exxion** [comment]
Possess predates atom locking by years
But yes, now that atom locking exists, that would be a better solution

Also why the fuck is there an admin flag *just* for this one single verb?
