### ISSUE TITLE
SMG not shooting/hitting at point-blank range

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11602]
(WEB REPORT BY: flaoer REMOTE: 172.93.109.202:7777)

> Revision: 
> a3b913a10c7417186ea06f6266ad984f5e44f96a
> 
> General description of the issue
> You can't really do anything other than smack someone with the SMG if you try to fight at point-blank range with it.
> 
> What you expected to happen
> Being able to shoot someone at melee range with the SMG.
> 
> What actually happened
> Clicking on the mob just made me hit them with the SMG. Clicking on tiles behind the mob created a bullet, but behind the mob. The shot went right past them.
> 
> Steps to reproduce if possible
> 1. Spawn SMG
> 2. Spawn mob
> 3. Go up to their face
> 4. Try to shoot them with the SMG

**Comment by ComicIronic** [comment]
Was clicking the mob directly at range tried at all?

**Comment by FudgePucker** [comment]
Were you on harm intent? You need to be on harm intent to shoot them point blank instead of pistol whipping them.

**Comment by AutismSpider** [comment]
Need to be on harm intent for point blank shooting.

**Comment by kol1th** [comment]
[Not a bug]

**Comment by Exxion** [comment]
Some guns can't be fired point blank even on harm intent. Not sure whether or not the SMG is one of them.
But the bullet shouldn't just go right through the person anyway

**Comment by nervere** [comment]
Tested, no longer an issue.
