### ISSUE TITLE
You can place wooden barricades on wooden barricades

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#11612]
![](http://i.imgur.com/dmZHbM6.png)

**Comment by Intigracy** [comment]
thanks dylan

**Comment by jknpj** [comment]
good luck, i am behind seven barricades!

**Comment by ghost** [comment]
Probably missing a busy check

**Comment by clusterfack** [comment]
No, this isn't from doing them all at once

**Comment by ghost** [comment]
Shrug, then it's missing the default stacking check, how inconvenient
