### ISSUE TITLE
Destruction of cult sacrifice target's head renders the mode unwinnable.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11616]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 652ffb4fe2fedd4bbb89f4fd8d39a14ec433e5aa
> 
> General description of the issue
> Title
> 
> What you expected to happen
> For the game to re-pick objectives if the head is destroyed I guess?
> 
> What actually happened
> Admins have to manually unbrick the cult.
> 
> Steps to reproduce if possible
> I've bitched about SOULSTONES working on the sac target before, but it can also happen by the chaplain/other-people biblefarting, the target suiciding and either turning into burgers or braincake, et cetera.

**Comment by AlphaBuffalo** [comment]
Instead if switching objectives it should say objective failed and shows the next one. Only question left is, should cult be punished for it or not?

**Comment by Allspice** [comment]
With how many people are inexperienced with cult on the server, I would not like it if the cult was punished from one of them fucking up. Setting aside that the sac objective could be rendered not-doable through zero fault of the cult.

**Comment by ihadtoregisterforthis** [comment]
Why not make it pick another target?

**Comment by AlphaBuffalo** [comment]
Eh kind of makes it easy mode if it just switches. I rather it be considered failed and a new objective of the same nature. So cult would have to sacrifice another person

**Comment by clusterfack** [comment]
Lots of other team antag modes have a fail condition.

**Comment by Allspice** [comment]
And yet the nuke disk respawns when it is deleted.

**Comment by clusterfack** [comment]
That's because people would destroy the nuke disk themselves out of spite immediately if they could. Sacrifice targets are unknown.

**Comment by Allspice** [comment]
That's well and good until the target goes and biblefarts, which is exactly what prompted this bug report; I don't like the idea that game modes can be fucked and necessitate admin intervention as a matter of course.

And since the cult MO tends to be CONVERTING PEOPLE AGAINST THEIR WILL instead of someone setting an antag to yes in their prefs and getting drafted. There tends to be a lot of inexperienced converts. I also don't like it that they can fuck over a strong cult beyond repair and get shouted at after the round; I suspect that sort of thing would only drive people away from learning the game mode.

**Comment by AlphaBuffalo** [comment]
Do people really get that butt hurt over 1 failed objective? I mean if the target dies and can't be sacrificed just mark it as failed and move on there are other objectives to try and complete

**Comment by Allspice** [comment]
If it doesn't prevent NarNar summoning then whatever.

**Comment by AlphaBuffalo** [comment]
My idea is not to prevent NarNar but to have them repeat the object with someone else being scarified. So at round end it list cult objectives as sacrifice (failed) sacrifice 2 (complete) summon narsie (complete)

**Comment by DeityLink** [comment]
Legacy Cult issue.
