### ISSUE TITLE
player controlled cockroaches are killed by nukes

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#11620]
LITERALLY UNPLAYABLE

**Comment by Ephx1** [comment]
I don't care how immune you are to radiation, being anywhere near a nuclear blast is death.

**Comment by kol1th** [comment]
The non-player cockroaches don't die

**Comment by Ephx1** [comment]
well then hush my mouth

**Comment by AutismSpider** [comment]
Roaches should turn into rad roaches on a nuke blast or when touch by nuka cola
