### ISSUE TITLE
Autotator can make borers antags

### ISSUE THREAD

**Issue by ScrambledSteak** [d3athrow/vgstation13#11624]
#### Description of issue

AUTOTATOR CAN MAKE BORERS INTO ANTAGS EVEN THOUGH THEY HAVE NO CONNECTIONS TO THE SYNDICATE BECAUSE THEY'RE **SLUGS**
#### Difference between expected and actual behavior

For autotator to only make humans antags
#### Steps to reproduce

> be borer
> have autotraitor antag you
> OD everybody even though you need them to live

![da3](https://cloud.githubusercontent.com/assets/19224578/18031523/03e92bce-6cbf-11e6-9662-17306c78f1cc.png)

**Comment by TheFriggenSawbones** [comment]
autotrator borers are neat as hell

**Comment by TheFriggenSawbones** [comment]
but will there be a dead where ppl murderbone the station and say it's because their borer is an antag what does it mean

**Comment by AutismSpider** [comment]
Eh what is this like 4th time he fail to fix this?

**Comment by ComicIronic** [comment]
Spy Slug takes the toughest contracts in the sugariest conditions for the best pay.

**Comment by clusterfack** [comment]
Fixed recently by a borer mind change
