### ISSUE TITLE
Empty slot in borg inventory

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11638]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> A standard borg with hacked board has an empty slot in his inventory. When you store something (esword) back into inventory, it is not on the first empty slot but on the second.
> 
> What you expected to happen
> To be on the first.
> 
> What actually happened
> Is on the second.
> 
> Steps to reproduce if possible
> Get a standard borg with hacked board and try taking out and returning items into inventory.

**Comment by ghost** [comment]
could not reproduce
