### ISSUE TITLE
The happy mask, in general

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11636]
#### Description of issue

This object causes too much problems considering how common it is

There's usually 3 groups of people who find it

> People who know what it does, so they leave it or trash it
> People who don't know what it does, so they put it on, do something dumb, get taken to medical, and end up shading a dozen crew
> People who know what it does, put it on, time to giggle and griff regardless of antag status

And what does it do?

> It forces people out of their current bodies, and makes them 'slaves' to the wearer of the mask, regardless of if either party wanted it or not

Now, here's the biggest problem

> to_chat(S, "<span class='sinister'>You have been given form by the power of the happiest mask! Go forth and cause joyful chaos for [H.real_name]!</span>")

So, either you get a salty shade that didn't want to get shaded who now can not re-enter their body, who is now trapped in a very weak body, a shade who obeys their masters will (which may be nothing if the master doesn't know what the fuck is going on), or a shade that treats it as a free antag roll and proceeds to fuck up the station, ignorant of their master, or a shade who gets killed in seconds because valids.

It is a poorly thought out reference item from Risk of Rain, that is all-too easy to find, that causes grief and misfortune to all who look upon it (So it at least gets that bit right).

So, how do we fix this?

> Make it more like the one from Risk of Rain, it only shades people you actually kill
> Have some way for the shade to re-enter its body, or at least be put back into a body or a soul stone
> Remove it from xenoarch finds, make it an artifact-tier item only found in vaults, or make it a wizard item wizards can buy
> ...?

**Comment by PJB3005** [comment]
#10581
