### ISSUE TITLE
Medibot can be heard when you deaf

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11631]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I am deaf tho I can hear beeping medibots "Wait! I want to help!"
> 
> What you expected to happen
> not to hear
> 
> What actually happened
> to hear
> 
> Steps to reproduce if possible
>  • get deaf
>  • get to medibot
>  • hear

**Comment by PJB3005** [comment]
reeeeeeee OLDCODE
