### ISSUE TITLE
Mechs can't drill throug blobs apparently

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11647]
(WEB REPORT BY: tornader REMOTE: 172.93.109.202:7777)
Revision: da71ac1067b385e791746186ee75d9c1165848a3 

> General description of the issue
> mechs can drill blobs, not sure if a feature or not
> 
> What you expected to happen
> I expected to drill that blob while it battered me with hits and shit
> 
> What actually happened
> couldn't do shit to it
> 
> Steps to reproduce if possible
> get mech, spawn any blob part, try to drill

**Comment by Exxion** [comment]
I have definitely drilled through a blob in the past, though it was a month or two ago, so maybe it broke in that time
