### ISSUE TITLE
AI eye fuckery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11649]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision da71ac1067b385e791746186ee75d9c1165848a3 
> 
> General description of the issue
> If the main breaker of an AI's APC is toggled off, the blind overlay will never go away even if the breaker is later toggled on.
> 
> What you expected to happen
> Wake me up
> 
> What actually happened
> Can't wake up
> 
> Steps to reproduce if possible
> Toggle breaker on your APC and weep.

**Comment by gbasood** [comment]
Probably my fault

**Comment by ghost** [comment]
Seconding the issue. Happened twice today

Kavlax found a workaround. If you re-toggle your power off and let your power reconnect thing play out you get your vision back. Then you can force your apc back on.

**Comment by gbasood** [comment]
Wait what
I could have sworn I had a fix for this that involved restructing ALL of AI's life code

**Comment by gbasood** [comment]
Yeah I did actually
#11600
Maybe the problem I was trying to solve wasn't actually caused by fullscreens? I don't know, someone else will have to take a look at it, I've done all I can see to fix it
