### ISSUE TITLE
Can see ghostchat when Duranded

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11640]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I died as a borg, got my brain extracted and then put into a Durand.
> I can still hear ghostchat, but I cant communicate in it anymore.
> 
> What you expected to happen
> To not to hear ghostchat
> 
> What actually happened
> To hear ghostchat
> 
> Steps to reproduce if possible
> Get borged, then killed. (Didnt leave borg body) then get extracted the brain and duranded.

**Comment by ghost** [comment]
Are we getting a fix for this soon? Posibrains are a mess

**Comment by SkowronX** [comment]
already an issue #11259

**Comment by Exxion** [comment]
Duplicate, as Skowron pointed out
