### ISSUE TITLE
Sprite with the noir power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11641]
(WEB REPORT BY: punishedchiot REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Black tile around the character http://puu.sh/qRVLr/205c058687.jpg
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by clusterfack** [comment]
@DrCelt

**Comment by ghost** [comment]
I figured out the cause of this and fixed it in #11340 / #11639

**Comment by PJB3005** [comment]
Atomic.

**Comment by clusterfack** [comment]
I don't care fix it in a separate PR

**Comment by ghost** [comment]
It's atomic because the same bug occurred in the PR which led me to figure out the cause :^)
