### ISSUE TITLE
You can see actions through walls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11642]
(WEB REPORT BY: miningpig REMOTE: 172.93.109.202:7777)

> 87b9d44f1d11fe969bbebee7438bbff115f92c10 
> 
> General description of the issue

I was in the maint behind surgery and my mesons (I'm assuming it was my mesons) were letting me see stuff about bone gel and cauterizing wounds

> What you expected to happen

For that to not happen

> What actually happened

It happened

> Steps to reproduce if possible

Get mesons

Have somebody do things behind a wall

(??? I think so. It seems like the most logical conclusion that the mesons were doing it.)

**Comment by Exxion** [comment]
Mesons definitely did this with posibrains, at least
Comes from sending messages to `viewers` of the turf rather than just using `visible_message()`

**Comment by clusterfack** [comment]
No it's rather that visible_message sends it to viewers(get_turf(src)), we need to rethink the system somewhat.

Either it can get viewers(src), which I'm not 100% sure if it works when objects are within objects.
Or it could get viewers([get_holder_before_turf()]) or whatever its called (for non-turfs).

**Comment by ScrambledSteak** [comment]
I also saw syringe injections through walls too, so that's definitely a problem.

**Comment by Exxion** [comment]
Wait, `visible_message()` itself does that?
Yeah replace `get_turf()` with `get_holder()` or whatever it's called
