### ISSUE TITLE
Irelands prejudice agaisnt gray aliens strikes again, the stealth removal of telepathy

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#11658]
It has come to my attention that while playing on our fair space station 13 that we are no longer able to use our mind powers at all. Old Patty O' Celt tried to hide this from me pretty well by making it so i'd actually have to try and use his neutered version of our once great and perfectly fine power to see. You see, the potato goblin made it so that the menu would show up and that we would assume that everything would be fine, big mistake Celt. You should have known that my autism and curiosity would one day cause me to try and use our neutered ability, that was when I found your deceitful coding right in our fair space station 13.

You don't know what powerful enemies you have made by doing this celt, us grays relied heavily on our ability to communicate telepathically. We are a weak bunch that consist of bug eaters and autistic chefs, when you remove our ability to mumble to people with our brains, you remove our ability to live. This is a greater tragedy than the great potato famine of '45, if this change you have made is not reverted soon celt, you will find yourself up against a powerful force that could only be defeated by a light drizzle.

**Comment by clusterfack** [comment]
It's a bug, to be fixed by https://github.com/d3athrow/vgstation13/pull/11605

**Comment by carshalash** [comment]
Cheers

**Comment by clusterfack** [comment]
Whenever that gets finished anyway

**Comment by ghost** [comment]
I can't believe you spent all that time writing those two paragraphs for a bug that I didn't cause

**Comment by carshalash** [comment]
I've wasted 22 years, what's another 10 minutes.
