### ISSUE TITLE
Xenos have no attack delay on mechs.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11650]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision da71ac1067b385e791746186ee75d9c1165848a3 
> 
> General description of the issue
> title

**Comment by gbasood** [comment]
Oh wow was this not already reported
I could've sworn it was

**Comment by AutismSpider** [comment]
it was good luck finding it
