### ISSUE TITLE
motorized wheelchair planes are fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11661]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> fix planes
> 
> What you expected to happen
> planes fixd
> 
> What actually happened
> it goes under conveyor belts and stuff
> 
> Steps to reproduce if possible
> go around with a wheelchair and see fucked planes

**Comment by PJB3005** [comment]
@DrCelt PLANES

**Comment by ghost** [comment]
Is it just the motorised one that's broken or all vehicles?

**Comment by Kurfursten** [comment]
For real though meme reports are a pretty serious problem

Adding a template did not improve report quality at all
