### ISSUE TITLE
What...?

### ISSUE THREAD

**Issue by JMWTurner** [d3athrow/vgstation13#11669]
just a flat "what"

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/datums/diseases/rhumba_beat.dm#L16

**Comment by kol1th** [comment]
I'M THE KING OF THE RHUMBA BEAT

**Comment by gbasood** [comment]
might be Cuban Pete memes

**Comment by clusterfack** [comment]
Yeah you'll find there are more little 'secrets' like this in the code

**Comment by gbasood** [comment]
https://www.reddit.com/r/SS13/comments/2qkpjo/i_am_cuban_pete/cnm6pa3
yep

**Comment by JMWTurner** [comment]
It's not so much that the virus ignores a certain ckey that bothers me.

It's that this particular ckey is hardcoded into our code. who the fuck is rosham?

**Comment by Exxion** [comment]
There are many, though most of them are related to the custom item system we have but don't use

**Comment by Kurfursten** [comment]
@JMWTurner Cuban Pete

**Comment by JMWTurner** [comment]
You mean it's not just an homage to The Mask and cuban pete in SS13 is in fact a reference to a certain player?

**Comment by Exxion** [comment]
Yes
He was legendary for blowing up the entire station

**Comment by gbasood** [comment]
A lot, actually

**Comment by Exxion** [comment]
Wow
I decided to look into it and there are fucking custom alt ID titles for THREE different ckeys
And one of them has two custom titles

Also one specific ckey gets two custom AI emotions
And there's the infamous hidden self-autoinjector (which happens to belong to the ckey with two custom ID titles)

**Comment by kol1th** [comment]
@Exxion sounds like bay leftovers

**Comment by Exxion** [comment]
Definitely

**Comment by Intigracy** [comment]
Rosham aka Cuban Pete is a leftover from TG, he would bomb the station to smithereens on a pretty consistent basis.

He's why bombcaps were introduced.

**Comment by ConkerDev** [comment]
CHICK CHICKY BOOM CHICK CHICKY BOOM
This particular piece of snowflake memery seems harmless. He's gone for long, I think.

**Comment by gbasood** [comment]
also this is old disease code and is no longer used
