### ISSUE TITLE
You cant follow station arrivals announcements

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#11660]
The href doesn't do anything

What gives @DrCelt ?

**Comment by DrCelt** [comment]
That's really odd because I tested it.
Maybe the test I did was using an outdated compile before I did the thing you said I should do. Hmph.

**Comment by Intigracy** [comment]
Secret repo conflict, I'll fix it when it's not down.

**Comment by clusterfack** [comment]
oooooooooooooooooooooooooh. That explains so much.

**Comment by DrCelt** [comment]
Thanks Secret Repo™!

**Comment by Intigracy** [comment]
Fixed.
