### ISSUE TITLE
AIs can see cult conversion through AI static

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11672]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 50066d75e0457ba030dd24d17455d100ba42cdef 
> 
> General description of the issue
> An AI reported that it could see a conversion in progress, in an area that was in static. Upon examining the area, there were /atom/movable/overlay in the right click field, called 'cultification'
> 
> What you expected to happen
> To not see conversion process through static
> 
> What actually happened
> 'IT'S CULT'
> 
> Steps to reproduce if possible
> Unknown

**Comment by kol1th** [comment]
@DrCelt

**Comment by ghost** [comment]
That's odd because the static is on plane = 1 which nothing physical except hud items should be on.

**Comment by ghost** [comment]
What's odder still is that it left 2 instances of /atom/movable/overlay well AFTER the conversion
