### ISSUE TITLE
Metaclub vox genetics outpost needs plasma

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#11671]
the gimmick of the metaclub vox outpost is genetics
It has modification consoles, vox chickens, chem dispensers, chemmasters, cryo, cloning, mancrowave, but no plasma
seems like an oversight

**Comment by Killette2** [comment]
Trade for it

**Comment by Durgen** [comment]
if the whole gimmick of the outpost is genetics, shouldn't those materials be things that don't need to be traded for?

**Comment by Probe1** [comment]
Why do you need plasma for genetics?

**Comment by Probe1** [comment]
Whatever

**Comment by Killette2** [comment]
You need more plasma for cloning once your cryo tube starts to run dry @Probe1

**Comment by Probe1** [comment]
Thats a good point.
