### ISSUE TITLE
Xenos can pop from corpses that were infected while alive.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11676]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 5e634c39623458bda9b4b8e3cb1b352a85b749a7

It might be A FEATURE or something but if I'm not mistaken it's best practice to immediately kill people that you facefuck and infect as a xeno, which seems extremely bizarre.

**Comment by ScrambledSteak** [comment]
Isn't that what happened in the actual movie

**Comment by CptWad** [comment]
yes it was
I mean the best way to do it is have like an incubation period where the larva has to stay safe
issue is that morons keep depressurizing shit and facehuggers dont give air so they outright kill people mostly on accident

**Comment by clusterfack** [comment]
There's like 4 stages if you get past the first one or two before the person dies the infection will work whether they die or not. Unless I'm missing some other nuance here.
