### ISSUE TITLE
Wrapped packages are broken again

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11674]
#### Description of issue

Using a package wrapped item in your hand makes the wrapped item disappear
Attempting to unwrap a wrapped crate makes the entire thing disappear
The contents seem to be getting null spaced
#### Difference between expected and actual behavior

packages should unwrap properly when you attack_hand or attack_self them
#### Steps to reproduce

Wrap a crate/object
Watch as unwrapping it makes the contents disappear
#### Specific information for locating

packagewrap.dm , obj/item/delivery
#### Length of time in which bug has been known to occur

Only recently noticed it in the previous round
I wanted to say it was the result of either #11505 or #11565, but when I reverted the changes to packagewrap.dm from both of these package wrapped crates were still disappearing.
#### Server revision

5e634c39623458bda9b4b8e3cb1b352a85b749a7 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
I warned you bro

**Comment by JustSumBody** [comment]
W-what

**Comment by Intigracy** [comment]
I blame forcemove.

**Comment by gbasood** [comment]
Something related to package wrapping has been runtiming, but I thought it was the disposals delivery system

``` DM
[04:22:41] Runtime in packagewrap.dm,38: undefined variable /turf/simulated/shuttle/floor/var/anchored
  proc name: afterattack (/obj/item/stack/package_wrap/afterattack)
  usr: Cash Hardie (pvak) (/mob/living/carbon/human)
  usr.loc: The floor (178, 231, 1) (/turf/simulated/shuttle/floor)
  src: the package wrap (/obj/item/stack/package_wrap)
  src.loc: Cash Hardie (/mob/living/carbon/human)
  call stack:
  the package wrap (/obj/item/stack/package_wrap): afterattack(the floor (177,230,1) (/turf/simulated/shuttle/floor), Cash Hardie (/mob/living/carbon/human), 1, "icon-x=26;icon-y=19;left=1;scr...")
  Cash Hardie (/mob/living/carbon/human): ClickOn(the floor (177,230,1) (/turf/simulated/shuttle/floor), "icon-x=26;icon-y=19;left=1;scr...")
  the floor (177,230,1) (/turf/simulated/shuttle/floor): Click(the floor (177,230,1) (/turf/simulated/shuttle/floor), "mapwindow.map", "icon-x=26;icon-y=19;left=1;scr...")
  the floor (177,230,1) (/turf/simulated/shuttle/floor): Click(the floor (177,230,1) (/turf/simulated/shuttle/floor), "mapwindow.map", "icon-x=26;icon-y=19;left=1;scr...")
```

WEW LAD

**Comment by JustSumBody** [comment]
After checking out the commits before and after, I found it was definitely caused by #11490 . Not sure how, but something with the change to force move seems to have broken getting stuff out of package wrap.
