### ISSUE TITLE
Revsquad appears in mixed mode

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#11677]
So I set up mixed to pick 3 modes at random
it picked revsquad
revs did not show up in tator menu
shuttle could not be called
r i p

**Comment by DrCelt** [comment]
@unid15 and @DeityLink

**Comment by Exxion** [comment]
Why Unid? It's @gbasood's mode

**Comment by unid15** [comment]
yeah https://www.youtube.com/watch?v=2Beda3kFNjo

**Comment by DrCelt** [comment]
You guys are the same to me

**Comment by gbasood** [comment]
Yeah this doesnt really support revsquad at all

**Comment by CptWad** [comment]
I just selected mixed at start
