### ISSUE TITLE
Marauder mech parts can't be constructed properly

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11678]
The designs don't show up even if you are at max research, from what I'm seeing they're supposed to show up under the Durand category.
In addition, the build_path for the chassis still points to the durand's chassis. Even if they could be printed, attempting to print off the marauder chassis would have probably printed a durand instead.
Their id is also still set as "durand_chassis" and "durand_larm" etc, not sure if that will cause other problems.
@JMWTurner

**Comment by ComicIronic** [comment]
Did you have NT tech levels?

**Comment by JMWTurner** [comment]
He's right, that's an oversight. I'm fixing the issue right now.
