### ISSUE TITLE
Ventcrawling into a cryopod gets you stuck

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#11689]
NO ESCAPE

**Comment by ghost** [comment]
you should be able to ventcrawl into cryo and start getting cryo'd like normally being put in it tbh, and if you have ventcrawl and take leporazine you should be able to jump in and ventcrawl out into the pipes.

**Comment by Exxion** [comment]
Mice can't enter cryo normally
I should probably mention that I found this out as a mouse

**Comment by AI-Is-Rogue** [comment]
I believe doing that while there is a person in cryo fucks it all up, breaking the entire thing. At least in my experience.

**Comment by Exxion** [comment]
If you knew about it
Why didn't you report it?

Or maybe you did and I just didn't know

**Comment by AI-Is-Rogue** [comment]
I thought I did. That is until I saw this issue. I must have forgotten to.

**Comment by Kurfursten** [comment]
Mice die pretty easily to temperature changes. Are you sure you weren't instantly killed?

It can be hard to tell with lack of UI.

**Comment by Exxion** [comment]
Mice aren't affected by atmos inside vents.
And I checked anyway.

**Comment by PJB3005** [comment]
This is because the cryo pod has a `relaymove()` override which blocks the native ventcrawling code.

Easy fix, just make it call `..()` if the mob is ventcrawling.
