### ISSUE TITLE
The minimum amount of players for revs needs to be raised

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#11688]
> rev round
> only head is the HoP
> at round start revs immediately just head to the HoP line and kill him
> IF YA SMELELELELELELELELEL

Rounds should last longer than the time needed for the lobby to load. This is getting out of hand.

**Comment by gbasood** [comment]
this was a bussed round, non-issue
Normally the minimum limit would have been fine with this
Also it was revsquad

**Comment by mrpain666** [comment]
Oh. Henk.
