### ISSUE TITLE
Kicking while stunned

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#11697]
Hi.

Can someone add the ability to kick while stunned, for a chance to do damage or a disarm-style stun if aiming at feet, legs, or groin via flailing?

Thanks!

**Comment by nuklearcellphoneg** [comment]
To me a viable way of adding this as an rng balance would be:

Each present stun has a set amount of time of paralyze; Taser puts you into stun, which is the laying down bit where you can't act nor unrest. 

Add a set amount of time wherein you cannot kick due to paralyze, so for example, if you get tased there are a few moments where you cannot kick but are then able to, but if a ling uses parasting, the paralyze lasts the duration of the stun.

**Comment by Exxion** [comment]
Might make stuns less absurdly overpowered

**Comment by nuklearcellphoneg** [comment]
That's the thought.

One police officer can cuff someone- it typically takes several to do so safely, and a wee bit better than stun-spam harm intent-dead or dying

**Comment by Allspice** [comment]
This is interesting: This would make it safest in all circumstances as only-sec to tase and lethal four times.
