### ISSUE TITLE
Rev & Counter-rev: A terrible idea by Celt that's worth a shot.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11692]
REV AND COUNTER REV.

Summary: Instead of knowing for sure whether it's rev or not, there will be two "factions", one of them syndicate backed, who vie for power of the station in order to nuke it. - The heads could be the antags planning to blow the syndies up one round, and then the people trying to save it the next. There is no conversion as such - no crew member / neutral party is ever told EVER which one is which, and must choose which side they are on. Crew members must also not harm eachother, but both heads and revs are valid no matter if rev or counter-rev.

There is exactly the same chance of counter rev and rev appearing!
once it has been revealed it's rev or counter-rev, both heads are valid, and revs are valid. NOBODY else is valid.
the heads and revs may kill whomever they want if they are the bad guys or only in self defence if they're the good guys. (The bonus is to this is that by virtue of acting in self defence, nobody can ahelp saying "X killed me was that valid" because they put themselves in that position anyway)

revolution
- the heads are cunts!
- they are syndicate sleeper agents.
- by completing tasks, they convert random members on the station to revolutionaries. - one to be the RD, one to be the CMO, one to be the CE, one to be the HoP, one to be the RD and one to be the captain - effectively, one rev = one head.
- if new heads arrive on station, a new rev is recruited as well.
- their goal is to blow up the station by hacking APCs in order to obtain the nuke code
- they should frame the revolutionaries for it
- once a certain timer has reached after having the prerequisite APCs, the nuke code will be given to all heads.
- if the heads are all killed, the crew wins. the round does NOT end, but it merely becomes pseudo-extended.

counter revolution
- the heads are cool!
- certain members of the station are syndicate agents. - one to be the RD, one to be the CMO, one to be the CE, one to be the HoP, one to be the RD and one to be the captain - effectively, one rev = one head.
- if new heads arrive on station, a new rev is recruited as well.
- their goal is to blow up the station by hacking APCs in order to obtain the nuke code
- they should frame the heads for it
- they must kill the heads.
- once a certain timer has reached after killing the heads and having the prerequisite APCs, the nuke code will be given to all revs (who will have assumed the position as new-heads).
- if the revs are all killed, the crew wins. the round does NOT end, but it merely becomes pseudo-extended.

why this is an improvement:
- Turns a shitty game mode into a pseudo WIFOM, battle of subterfuge (which one is going to blow up the station?) as well as stops it being a team death match. Takes inspiration from rev-squad.
- The revs will have an advantage as the heads are more prominent.
- Bayrev is not suited for /vg/.
- There will be rounds where the heads are killed and the new-heads are actually the antags, stealth blowing up the station. https://www.youtube.com/watch?v=4JuK1Yr35Io

How the game will progress:
- People will not kill the heads or revs initially, as this means they are more likely to lose.
- Heads and revs will be holed up; not wanting to put themselves in a position where they can lose.
- Nobody knows who's right or wrong.
- the bad guys will start subtly attempting to hack the APCs while blaming the other
- As people start to become more aware of who's the bad guy, they shall !!hopefully!! take the bad guys out.

I will be running test versions of this game live, using adminbus to simulate how this would be coded. If it succeeds, I may make this a gamemode proper.

If it fails, then it fails. Don't vote on this using github emojis, either positively or badly, until you've seen it in action, and I will be the first to say I have my doubts as to how it will work out, but it's worth a shot, right?

**Comment by gbasood** [comment]
So wait
What makes the revs act differently in this scenario?
They still just want to kill all heads, so they'll still act the same.

**Comment by ghost** [comment]
@gbasood If it's an even one-to-one fight, antag-revs versus heads, then they won't be able to win - heads are better equipped at the start, and if they're too obvious then the crew will turn on them as well. They have to convince the crew that they're the good guys.

**Comment by TheEliminator16** [comment]
Fosters paranoia and distrust, would probably lead to wacky hijinks.
I like it, it's what ling should be more like.
That being said, I do think that it'll be a mode that admins groan when it gets picked, because it'll probably mean lots of people ahelping because they got unjustly killed.

**Comment by Killette2** [comment]
WYCI

**Comment by Killette2** [comment]
@TheEliminator16 Why do you bring MrFoster into this?

**Comment by chatsonf** [comment]
I am not allowed to vote with emojis so I will just post here saying it is very promising

**Comment by gbasood** [comment]
How is WYCI different from Feature Request @PJB3005

**Comment by Kurfursten** [comment]
This guy isn't here 3 years later so I don't believe he will code it
