### ISSUE TITLE
Some spells that were changed to use wait for click no longer give the invocation

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11696]
The equip spells(clown/mime/horse curse) shoesnatch, and targeted fireball in particular I noticed don't have their invocations anymore. Can't seem to recall or find any others at the moment.

**Comment by clusterfack** [comment]
Whoops, looks like I forgot to include invocations themselves into my spell channeling system

**Comment by Intigracy** [comment]
Seems pretty simple to make it work with wait for click, just make it so clicking anywhere activates the spell on yourself still.
