### ISSUE TITLE
turret bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11699]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you build a turret with a PKA it turns into a taser turret
> 
> What you expected to happen

pka turret

> What actually happened
> taser turret
> 
> Steps to reproduce if possible
> build a turret with a PKA
> get a taser turret

**Comment by ghost** [comment]
I think it defaults to a taser turret if there's no alternative turret found for that gun.

There's a massive list of different turrets depending on the gun used on them.

**Comment by ghost** [comment]
Also what the hell is a PKA?

EDIT: Talked to him, it's the Proto-Kinetic Accelerator, the miner gun

**Comment by ihadtoregisterforthis** [comment]
Who even calls the protokinetic accelerator "PKA"?

**Comment by ghost** [comment]
People who main cargo, which pvak does

**Comment by Intigracy** [comment]
Turrets are shit and should just use the projectile of the gun used.

**Comment by Exxion** [comment]
They should fire the gun itself
