### ISSUE TITLE
Service borgs lose their shakers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11701]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4aa3a13432595c936432ea8f1a1b30f9522c6997
> 
> General description of the issue
> When a service borg puts their shaker in a booze dispenser, then eject it, it doesn't return to the service borg like expected, but instead disappears.
> 
> What you expected to happen
> To get the shaker back
> 
> What actually happened
> Well shit there goes muh job
> 
> Steps to reproduce if possible
> Be service borg
> Stick shaker in booze dispenser
> Do some nonsense with it, fill it with beer and whatnot
> Eject
> Find that you are now without shaker

**Comment by Shadowmech88** [comment]
Likely an oversight stemming from whatever PR added the ability to add shakers to dispensers.
