### ISSUE TITLE
Morgue tray greenlight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11708]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> If you clone a corpse from morgue tray that became greenlighted, placing the original back into the tray gives a green light despite there being no ckey in that body (since it was cloned).
> After leaving the body in the open for a while and placing it back in the morgue, the light was red as it should be.
> 
> What you expected to happen
> Red light on a cloned body.
> 
> What actually happened
> Green light for a while despite no ckey in body.
> 
> Steps to reproduce if possible
> Have dead body with no ckey in morgue tray.
> Player re-enters corpse in the tray.
> Clone that corpse.
> Place the original back in tray
> Observe the green light that should be red.

Like I said, I think it goes away with time, so this may be a non-issue.

**Comment by Shadowmech88** [comment]
Tested locally, unable to reproduce.
