### ISSUE TITLE
Electrical storm event refills SMES's

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11704]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 44491382b2416afb61430af5d0f6834d8206637d 
> 
> General description of the issue
> For some strange reason, when the electrical storm fires and does its thing, previously near-empty SMES's come out of it completely refilled, despite not having any power sources
> 
> What you expected to happen
> The turned off power to not produce more power
> 
> What actually happened
> FREE POWER
> 
> Steps to reproduce if possible
> Have a shit engineering team
> Watch as they die in stupid ways, not getting power set up
> An electrical storm rolls in and out, turning station power on and off as it goes
> Marvel that SMES's are now at full, enjoy another 40 minutes to get the station's power problems sorted

**Comment by mrpain666** [comment]
ITS A FEEEAAAAAAAATURRRREEEEEEE

**Comment by ghost** [comment]
Why was this closed when it wasn't explained/fixed?

**Comment by PJB3005** [comment]
Here's the reason this happens.

The problem is, oldcoders are fucking braindead, and their method of implementing this was to, instead of disabling output on the SMES, forcefully turning OFF APCs and stuff, they decided that it should wipe everything to 0% charge, AND turn off the output and input on the SMES while they were at it.

Guess what, they didn't actually bother to code a method to _store_ what they ruined, result being, they just blindly force everything to 100% charge, including setting input and output values on SMES cells on the maximum.

**Comment by ghost** [comment]
If that's the case, why was this issue closed?

**Comment by Exxion** [comment]
Fantastic question

**Comment by ComicIronic** [comment]
Because it's a bad use of the web reporting tool. This isn't a bug, it's just how the code works, and the web reporter shouldn't be used to make change requests because we have no followup from the user who submitted it originally.

**Comment by ghost** [comment]
So, you're saying power from nowhere isn't a bug? It refilled SMES's that had no power source

Also, I'm the guy who reported it

**Comment by PJB3005** [comment]
Is it a bug? Technically no.

Is it goddamn retarded? Certainly yes.

**Comment by Exxion** [comment]
I would argue that it is a bug
Batshit stupid behavior coming from something being poorly-coded

**Comment by ComicIronic** [comment]
That's not a bug. Bugs are when something is intended to have a specific behaviour, and doesn't. It's not when a general idea is implemented in a way you don't like.

**Comment by Exxion** [comment]
Good thing we definitely know that this is exactly what the coders who made it work this way intended, not anything that would actually make sense

**Comment by 9600bauds** [comment]
Who gives a shit about the semantics, this is certainly not misuse of the webreporter and certainly shouldn't be closed
