### ISSUE TITLE
Feature Request: Remove the ability to name yourself and have names chosen from a drop down list of sensible names

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11714]

**Comment by clusterfack** [comment]
>Celt if this is all you have to contribute I'm going to ban you

This is not a place to stir up shit about admin rulings you dislike

**Comment by ComicIronic** [comment]
Well, I mean, we do have the ability to roll random names already. The only question is if we want the admin power to enable that, which I thought they could do already.
