### ISSUE TITLE
Syndicate c20r doesn't knock down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11713]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a11b14623ac8bfb6d9e930c9c74cb61044d4edd2 
> 
> General description of the issue
> Being shot by the nuke ops gun doesn't knock people down anymore
> 
> What you expected to happen
> Shoot someone and they fall over
> 
> What actually happened
> They keep coming
> 
> Steps to reproduce if possible
> Shoot someone with the ops gun

Probably because of the recent assault rifle nerf

**Comment by ghost** [comment]
feature loss

**Comment by Exxion** [comment]
It was actually intentional

**Comment by FudgePucker** [comment]
Nukeops have it somewhat hard, if they get stunned once they are fucking done, a stray taser blast hitting them is gee gee.

Their signature weapon has become worthless.

**Comment by clusterfack** [comment]
Was it intentional? I don't recall it getting removed

**Comment by Allspice** [comment]
ARs lost their stun to nerf science, it dinged ops as well.

**Comment by FudgePucker** [comment]
#10480 is the last PR that touched anything that I can see that may cause it.

**Comment by Killette2** [comment]
I thought this was an intentional change done to that type of gun because bullet stun for them was considered "overpowered", although I do not agree with this.

**Comment by Shadowmech88** [comment]
Even if it is intentional, I think it should be changed back.
Stuns are the cornerstone of ranged combat and while the station's officers will have a fuckload of tasers, the ops will get _maybe_ 5 eguns and then they're shit out of luck up against stun weapons.

**Comment by TheFriggenSawbones** [comment]
icantthinkofanameirghtnow was a mistake lets be honest

**Comment by clusterfack** [comment]
Nowhere in that PR did it say it was making the c20r not having any knockdown

**Comment by Sprok0** [comment]
The problem looks like both guns use the same magazines, and they're all spawning filled with the ammo_casing/a12mm/assault instead of the ops getting the regular bullets

**Comment by clusterfack** [comment]
Sounds like this PR
https://github.com/d3athrow/vgstation13/pull/11625

**Comment by charmstruck** [comment]
Nuke ops was difficult as it was, and now it's even harder?
Great

**Comment by jknpj** [comment]
> Nuke ops was difficult as it was, and now it's even harder?

It goes from easy peasy to super hard based on the crew manifest and op experience, to be honest. Having silicons/AI in the manifest will make things harder, unless they get subverted. If the HoS is holding the disk, expect a big gunfight for it, but if the HoP is holding it while sitting in his desk one op can safely walk to the hop line and gun him in the face. 

I still think ops need to get their c20r stun back because right now regular crewmembers can easily fend them off rather easily using cheap tricks(ZAS,lube,makeshift weapons, etc) while saxing their eguns and hoping they shot each other, making the whole threat of being raided by elite nuclear operatives look weak as fuck

**Comment by icantthinkofanameritenow** [comment]
Calm your tits sawbones, I'll fix it. Only the AR was supposed to be affected by the stun loss, it was a mistake on my part for the C20r to be affected too.

**Comment by Exxion** [comment]
Guess I read your comments on that other PR incorrectly
