### ISSUE TITLE
Genetic noire when shuttle is called

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11710]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> When you have the Noire genetic deffect and the shuttle is called, as the halls are blinking red, you cant see anything on the halls; nor people nor floor nor anything. Compleetely blind there.
> 
> What you expected to happen
> To see black&white halls.
> 
> What actually happened
> You see absolutely nothing.
> 
> Steps to reproduce if possible
> Get noire, call shuttel, get to hallways.

**Comment by ghost** [comment]
Screenshot of the effect

![](https://ctrlv.cz/shots/2016/09/01/54zC.png)
![](https://ctrlv.cz/shots/2016/09/01/mgA8.png)

**Comment by Kurfursten** [comment]
@DrCelt 

Can't believe this went unreported for so long

**Comment by ghost** [comment]
what the hell

**Comment by ghost** [comment]
seems like a byond problem, probably. I'll see if I can reproduce it

**Comment by clusterfack** [comment]
Preferences -> enable hardware rendering you cheating fag
