### ISSUE TITLE
That RIGHT FUCKING HAND

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#11712]
oh god somebody please fix the layering on the right hand. It's been driving me crazy for years.
![please](https://cloud.githubusercontent.com/assets/7810719/18176978/08d28678-7046-11e6-81f1-072b2a2f0904.PNG)
![fix it](https://cloud.githubusercontent.com/assets/7810719/18176982/0aad4a5a-7046-11e6-89cd-50f6da644563.PNG)

**Comment by FudgePucker** [comment]
Oh I always thought it was a bracelet, not your bleeding out stumb

**Comment by NigglyWiggly** [comment]
"Oh the tourist outfit has a red wristwatch or something, neat"

**Comment by ghost** [comment]
za hando?

**Comment by DeityLink** [comment]
Not sure when exactly but this was apparently fixed a while ago.

**Comment by Dacendeth** [comment]
#28527 fixed it.
