### ISSUE TITLE
Feature request: turn ventcrawling into a spell

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#11727]
it's kind of annoying to have it buried in the the IC tab or wherever it is

I have no idea how feasible it would be to do this.

**Comment by clusterfack** [comment]
Alt click

**Comment by jknpj** [comment]
> not macroing Crawl-Through-Vent

*buzz

**Comment by SkowronX** [comment]
Gee you want an HUD action button for a verb? How interesting

**Comment by Exxion** [comment]
DUDE ALT+CLICK LMAO

**Comment by SkowronX** [comment]
Not to mention ^ works just fine

**Comment by Durgen** [comment]
> alt-click to vent crawl

Well then, did not know about this.
