### ISSUE TITLE
Change Ambrosia to Marijuana

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#11722]
Make it make you hungry instead of seeing stupid colors as well.

**Comment by Kurfursten** [comment]
If you want to be hungry we already have a chemical for that, lipozine does it.

**Comment by clusterfack** [comment]
Dude weed lmao

**Comment by FudgePucker** [comment]
DUDE WEED LMAO.

Maybe have it reduce your metabolism so chemicals last longer in your system, make it saturate the colors and have an outline on everything.

**Comment by ComicIronic** [comment]
Dude 3 minute food orgy scene lmao

**Comment by Killette2** [comment]
Lipozine doesn't work the way it used to, it used to be much more effective in making someone starve but now it's more of an instant unfat pill.

**Comment by Iamgoofball** [comment]
just add weed alongside ambrosia

**Comment by Kurfursten** [comment]
@Killette2 It still has -10 nutriment factor, give it to thin man and he will get mad hungry

**Comment by Killette2** [comment]
@Kurfursten check how fast it metabolizes. I'm not entirely sure how it works but despite it's rate, it leaves the body instantly after consumption

**Comment by Shadowmech88** [comment]
You can roll a blunt out of literally any grown food. You can make watermelon blunts if you want to.

If you want marijuana blunts, then just add the marijuana plant.

**Comment by Kurfursten** [comment]
@Shadowmech88 Godblunts do get a snowflake case

**Comment by nuklearcellphoneg** [comment]
> you can roll a blunt out of literally any grown food

smh what a disaster game

**Comment by Kurfursten** [comment]
Don't be talking smack about my poppy blunts

**Comment by Killette2** [comment]
> wanting bicardine overdose

**Comment by Kurfursten** [comment]
It does nothing but send you messages.

Someone should really do something about our """"overdose"""" effects, since people just load up on antitoxin for even things like synap

**Comment by nuklearcellphoneg** [comment]
It heals internal bleeding.

Bicard OD causes toxin damage too I'm pretty sure

**Comment by Exxion** [comment]
Yes to both, if I'm not mistaken
Also I'm kind of amazed anyone knows the healing internal bleeding part

**Comment by nuklearcellphoneg** [comment]
I've always refused to look at the code, because the first thing I bothered to look at was chemistry, so I hand tested all the different chems to see what they did, what the OD was like, and so on. It's how I noticed Kelo and Derma stack and most things don't have a meaningful OD.

**Comment by nuklearcellphoneg** [comment]
FYI, deciphering the chem code was not worth the time or effort.

**Comment by Iamgoofball** [comment]
yeah bay's OD was stupid, they couldn't be bothered to make it actually matter so you can ignore it completely with anti-tox

**Comment by Probe1** [comment]
Really you want cannabis.   If you care for that to be added then make a feature request for it please.

**Comment by nuklearcellphoneg** [comment]
NOPE I STILL WANT THIS AND I WANT MINDBREAKER TO BE LSD

**Comment by Exxion** [comment]
Mindbreaker *is* LSD, according to the "lore." The name was changed for propaganda reasons.
Also, you were serious about this?

**Comment by Killette2** [comment]
I'd rather have better fleshed out drugs than generic blanket names tbh. Goon has so many drugs, why do all of ours suck?

**Comment by Kurfursten** [comment]
why have I not unsubscribed from this issue yet?

**Comment by nuklearcellphoneg** [comment]
Yes, I am. The names were change from what they were, uhhhhhhh iirc the swap from /v/ to /vg/? Maybe when we swapped to Bay code?

The names they are now really epitomize the kind of server we aren't- knowingly avoiding words like marijuana and LSD, acid, whatevs, in order to be more family friendly.

Be proud of your free speech!!

**Comment by nuklearcellphoneg** [comment]
Actually in line with what Killette said, we could use some tweaks to our drugs- Psilocybin, our most honestly named drug, iirc is just a copy of space drugs- not at all what psilocybin is like irl, which would be like Mindbreaker/LSD(which would give perma prisoners access to try to weaponize among other fun bits).

**Comment by Killette2** [comment]
@nuklearcellphoneg untrue. Psilocybin also makes your screen shake in high doses, making the clown virus in high strength fucking brutal. Otherwise yeah it's a clone. I think it also cannot overdose and doesn't make you drool and twitch, but these observations were a long time ago.

**Comment by Intigracy** [comment]
LSD makes it sound so much more friendly than it actually is though.

**Comment by Killette2** [comment]
Also buff/fix spiritbreaker

**Comment by Exxion** [comment]
I'm glad this already has [Honk] because I'd have to use every ounce of restraint I have not to add it
