### ISSUE TITLE
Can't push objects standing on a border-window

### ISSUE THREAD

**Issue by JMWTurner** [d3athrow/vgstation13#11723]
I tried really hard but I can't make heads and tails of that one.

![ahhhhhhdfg](https://cloud.githubusercontent.com/assets/21122521/18202450/4462b8f0-7110-11e6-8a2c-2f841f5bfc62.png)

See this canister? You should be able to push it east or west, but you cant. The game tries to make you push the window instead. You can still pull the canister though.

**Comment by nuklearcellphoneg** [comment]
https://github.com/d3athrow/vgstation13/issues/8787

**Comment by JMWTurner** [comment]
That's a similar issue but the causes are pretty different. Also here it's about pushing, not pulling.

**Comment by nuklearcellphoneg** [comment]
https://github.com/d3athrow/vgstation13/issues/4042

**Comment by nuklearcellphoneg** [comment]
Your east and west bit confuses me.

**Comment by ihadtoregisterforthis** [comment]
#11253

**Comment by JMWTurner** [comment]
Despite your efforts @nuklearcellphoneg it was @ihadtoregisterforthis that found another open issue that relates to that one.
