### ISSUE TITLE
Mechs that move become invisible

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11730]
#### Description of issue

It seems that https://github.com/d3athrow/vgstation13/pull/11700 may have caused a slight issue with icons for mechs, as currently when a mech moves, its icon state is set to null. It's alright before somebody jumps in, after somebody jumps in, but screws up as soon as that person moves. Once you eject the mech is back to normal
#### Difference between expected and actual behavior

Expected - Stomping around in my mech

Actual - Stealth mech
#### Steps to reproduce

Make a mech

Get in mech

Move about
#### Specific information for locating

/obj/mecha/combat
#### Length of time in which bug has been known to occur

Recently
#### Server revision

b700a20d1f2dcacff14e9259888c9c8432f5d15a
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
@JMWTurner

**Comment by JMWTurner** [comment]
Fixed by #11731
