### ISSUE TITLE
clown curse and possibly other spells do not appear work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11736]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1a4ed406d13b3b416d8fb4d70e1fe7969a5f15c0 
> 
> General description of the issue
> Unable to use clown curse on others
> 
> What you expected to happen
> HONK HONK LASER GUNS EXPLODE
> 
> What actually happened
> Hugs!
> 
> Steps to reproduce if possible
> attempt to use clown curse on others and watch it fail

**Comment by ghost** [comment]
@clusterfack

**Comment by Shadowmech88** [comment]
Tested locally, clown curse works.
