### ISSUE TITLE
Buttbot's Revenge Spell Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11737]
(WEB REPORT BY: badasswafflez REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1a4ed406d13b3b416d8fb4d70e1fe7969a5f15c0
> 
> General description of the issue
> Buttbot's revenge doesn't work
> 
> What you expected to happen
> Asses to be blasted
> 
> What actually happened
> Spell was readied, doesn't actually do anything.
> 
> Steps to reproduce if possible

**Comment by uazuaz** [comment]
just for clarification:
after you ready the spell, you need to click your target, and the target must be in an adjacent tile near you.
did you do it this way?

i just tried it on a monkeyman on the test server and it works just fine to me.

**Comment by ComicIronic** [comment]
This is why I hate web reports.
