### ISSUE TITLE
MoMMI nest starts with air and an air alarm.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11733]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 92b1e8a9020617483eb80518906782c1636721a0 
> 
> General description of the issue
> Title
> 
> What you expected to happen
> That an area with an airlock leading directly to space, inhabited by autists that are immune to space, to not care about vacuum.
> 
> What actually happened
> firelocks drop and the welder tank gets sucked out of the mommi nest whenever a crab leaves via airlock.
> 
> Steps to reproduce if possible
> Look at the crab nest as a ghost.

**Comment by uazuaz** [comment]
i assume you're talking about boxstation.
in my opinion the mommi nest regular airlock should be replaced by 1 external airlock or 2 reinforced windoors, to limit the air loss.

**Comment by ghost** [comment]
Why's there even need to be air there?

**Comment by uazuaz** [comment]
the air alarm could be removed then.
the issue is that there are often air alarms about the mommi nest being depressurized, if a mommi opens that door.

on a side note, when there is an air alarm in the mommi nest, a firelock closes also the recycling room external airlock.

**Comment by AutismSpider** [comment]
just wall it off some thing they move by pipe 90% of the time

**Comment by Kurfursten** [comment]
Do the opposite, remove all walls and floor tiles, make the room consist of lattices and one plating for the APC.

**Comment by Killette2** [comment]
What if we replaced the MoMMI airlock with plastic flaps? MoMMI's could still go under it and air won't be loss unless the MoMMIs undo them.

**Comment by jknpj** [comment]
There's usually only ONE thing i like about that alarm: It's a sign some greyshit is stealing the crabs protolathe. But i still wish the mommi nest was moved to that room with chargers in chapel maint or under the AI upload, left to the borg's spawn. Having it so exposed to space only leads to be raided or destroyed by meteors.
