### ISSUE TITLE
Feature Request: Add playing cards to box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11746]
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)
There are nifty playing cards that spawn on the metaclub locker room and bar, it would be nice to see them spawn on box. Maybe in the bar, library, and fitness room. Assuming this would be a very simple addition.

**Comment by SonixApache** [comment]
doesn't the rapid service dispenser make those?

**Comment by Rattlederp** [comment]
Yeah I think it does but when there isn't a bartender its nice to not have to break into the bar backroom and steal the thing just to get yourself some playing cards

**Comment by Kurfursten** [comment]
It should be added to a cargo crate

**Comment by TheFriggenSawbones** [comment]
you can get them from the RSD and as a prize from Arcade machines.

but ye make it one of those cargo booby prizes
