### ISSUE TITLE
BODA machines list 'drinking glass' instead of 'glass of x'

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11740]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1a4ed406d13b3b416d8fb4d70e1fe7969a5f15c0 
> 
> General description of the issue
> see title
> 
> What you expected to happen
> 'Glass of Space Cola'
> 
> What actually happened
> 'Drinking Glass'

**Comment by SonixApache** [comment]
Used to work just fine. Does it count as oversight?

**Comment by ComicIronic** [comment]
Unless someone can prove it's a logic error in the BODA code, I'm willing to guess this was caused by changes to the way reagents name their containers, so it's oversight to me - systems interaction goes wrong.

**Comment by SonixApache** [comment]
Thing is, when it comes out, it has the right name. It's a recent change, and not sure if it's specifically that machine or just a general issue. 

I know the hydroponics vending machines are having issues as well as of late.

**Comment by Exxion** [comment]
I believe it's because vending machines are shit and spawn a new item of the given type when it's dispensed, rather than generating them on creation and dispensing them from its `contents`
And it uses the compile-time name in the list of things

**Comment by clusterfack** [comment]
Well yes that is how it should work for things that aren't put into it, because making a ton of objects that will not necessarily be used is stupid. But is it actually using that same behavior for objects put into it? That would be silly.

**Comment by Exxion** [comment]
Only one kind of vending machine can have things put into it and it really shouldn't have that ability because it's buggy as fuck and not even useful

**Comment by Kurfursten** [comment]
Doesn't apply anymore as they were replaced with bottles
