### ISSUE TITLE
Can hear deadchat as posibrain in Mech

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11755]
(WEB REPORT BY: askaris REMOTE: 172.93.109.202:7777)

> Revision 472abf148f4cdc49392f378ccbc23a9e1d34c62b 
> 
> Can hear deadchat as posibrain when installed into a mech
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ihadtoregisterforthis** [comment]
dupe
