### ISSUE TITLE
Light issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11751]
#### Description of issue

this happened on boxstation.
i was observing last round, a guy welderbombed the hallway near the bar and another guy closed the breach;
then the power gone out because "abnormal activity in the powernet";
the replaced tiles were lighted anyway, as you can see in the picture.

![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/18230385/5b8824ae-7299-11e6-811b-c129199dc628.png)

i tried to do a test on the test server exploding a fuel tank and replacing the missing tiles, and i obtained the opposite issue; for the replaced tiles, only the ones adjacent to me were visible, all the others were full black.

![222](https://cloud.githubusercontent.com/assets/6170726/18230392/b19683b8-7299-11e6-8906-fdfa818233e0.png)
![333](https://cloud.githubusercontent.com/assets/6170726/18230393/b6013902-7299-11e6-9dc6-754bf4da9561.png)

i killed myself, and the replaced tiles were enlightened in the dark

![444](https://cloud.githubusercontent.com/assets/6170726/18230408/79a768e0-729a-11e6-87de-d381bbb90dd8.png)

**_NOTE:**_ friday a mommi was building a bar outside escape, all the new area had this issue, with all the tiles but the ones adjacent to you being black. other people confirmed it.
#### Difference between expected and actual behavior

a darkened tile being dark, and an enlightened tile being visible;

if you're a ghost, replaced/new tiles being enlightened without any light source;
if you're alive, replaced/new tiles being full black when they aren't adjacent to you.
#### Steps to reproduce

remove floor and replace it in a dark area;
build a new zone outside the station.
#### Length of time in which bug has been known to occur

i noticed it for the first time a couple of days ago.
#### Server revision

b83c425d106241928e706f4bf5d58d109db84be5 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Sounds like the lighting overlay isn't being transferred correctly, and then the luminosity of the turf doesn't get updated either.

Not impossible this is a result of the `forceMove()` PR.

**Comment by CptWad** [comment]
this happened before goonlight

**Comment by PJB3005** [comment]
Then why wasn't it reported?

**Comment by CptWad** [comment]
I always thought it was just lag

**Comment by ihadtoregisterforthis** [comment]
It could be related to areas, at least the mommi room part.
walls and flooring on space will be lit until an area is set.

**Comment by PJB3005** [comment]
@ihadtoregisterforthis yes, that is indeed intentional, because lighting is disabled in the space area. What isn't though is the fact that the turfs weren't luminous so you needed to be adjacent to them.
