### ISSUE TITLE
remove o hotkey

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11750]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
remove 'o'oc hotkey

**Comment by Killette2** [comment]
o

**Comment by Exxion** [comment]
1. Why?
2. Fuck no

**Comment by SkowronX** [comment]
no

**Comment by NigglyWiggly** [comment]
For what purpose

**Comment by Allspice** [comment]
Because it's the biggest source of accidental ick ock by far. Depending on how shitty the window focus acts for you, you can bring up ooc by mousing a bit too far and hitting 'o' off of the say window.

**Comment by ComicIronic** [comment]
Can't you just disable it yourself?

**Comment by Killette2** [comment]
You literally can disable it yourself by editing your skin
