### ISSUE TITLE
Give silicons the ability to *scream 

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11761]
With a sound and all
Imagine

**Comment by kol1th** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Shadowmech88** [comment]
![image](https://cloud.githubusercontent.com/assets/3991927/18247164/77c11b88-7336-11e6-854c-c69398ead795.png)

**Comment by NigglyWiggly** [comment]
First the screaming.
Then, the _moaning_

**Comment by jknpj** [comment]
> MoMMI speakers emit a loud noise! Looks like it is trying to scream!

**Comment by Intigracy** [comment]
Static sound.

**Comment by clusterfack** [comment]
https://youtu.be/G9FGgwCQ22w?t=2m12s

**Comment by NigglyWiggly** [comment]
_The MoMMI seems to be attempting to scream, but it has no mouth!_

**Comment by AutismSpider** [comment]
sure they have a mouth if they can drink stuff and eat pills

**Comment by Hoshi-chan** [comment]
Cyborg farts when?

**Comment by SonixApache** [comment]
@Hoshi-chan when you make the audio for it

**Comment by NigglyWiggly** [comment]
I could throw together a sound for that, but the question is: _w_ _h_ _y_

**Comment by Intigracy** [comment]
static sound

**Comment by jknpj** [comment]
*roar when?

https://www.youtube.com/watch?v=VVtx3xE8uGQ

**Comment by Shadowmech88** [comment]
This should be re-opened given that the fulfilling PR was reverted.
