### ISSUE TITLE
Chat's Fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11773]
(WEB REPORT BY: serwind REMOTE: 172.93.109.202:7777)
Chat won't load. Says:

If this takes longer than 30 seconds, it will automatically reload a maximum of 5 times. If it still doesn't work, use the bug report button at the top right of the window.

Announcements seem to work but nothing else shows, including ahelps.

**Comment by clusterfack** [comment]
Is it though, also I don't know why we have this message

**Comment by ghost** [comment]
I talked to serwind, told him to update his IE and it worked. Close this.
