### ISSUE TITLE
New coding standard suggestions

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#11778]
It's time to make our code much more modular, readable and adjustable

Here are my suggestions 
- fully remove src because it increases the file size. ~~src.~~drop_item(T, force_drop=1)
- add a space between if, while, for and other functions, and tthearguments like this: drop_item (T, force_drop=1)
- use defines for ALL icons and icon states
- only use 4 spaces for indentation now. Replace all tabs with 4 spaces
- no more named arguments. They're prone to runtiming and you can make a typo in the argument name. Do this instead drop_item (T,,,,,,,,1)
- when calling functions with multiple arguments, each argument should be on a different line. Less conflicts this way
  drop_item (\
  T,\
  ,\
  ,\
  ,\
  ,\
  1)

**Comment by PJB3005** [comment]
https://github.com/d3athrow/vgstation13/wiki/Draft:-New-Coding-Standards

**Comment by Shadowmech88** [comment]
> only use 4 spaces for indentation now. Replace all tabs with 4 spaces

Why?

**Comment by PJB3005** [comment]
(this is a meme issue)

**Comment by clusterfack** [comment]
Hilarious guys, I sure love bike shedding lets make an issue dedicated to it :okhand:
