### ISSUE TITLE
Feature suggestion: Xenoarch roid

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11794]
Considering there seems to be a small war going on between xenoarchs and miners, here's my suggestion so both parties aren't screwing with one another.

Have a subtype of /turf/unsimulated/mineral/random that has a lower ore density, but an increased density of potential dig sites, like /turf/unsimulated/mineral/random/arch

That way, you can then map in another roid to some maps, be it on the asteroid z Level, an off-station z level, or even have it as a vault

**Comment by clusterfack** [comment]
Yeah I really dislike this idea, making xenoarchs even more separated from human contact.

**Comment by AI-Is-Rogue** [comment]
I like the idea. Stop smashing my large artifacts and other assorted digsites. reeee

**Comment by gbasood** [comment]
I agree with @clusterfack 
Off-station roles are already dumb enough by making a group of players NOT interact with everyone else ever

**Comment by jknpj** [comment]
What would prevent artifacts from being spawned in other z-levels?

**Comment by ConkerDev** [comment]
Xenoarch is already cult station. Stop embracing the hikikkomori ways. Xenoarch is already boring as it is.

**Comment by DeityLink** [comment]
Conflict between miners and xenoarchaeologists is part of the salt of their job.
