### ISSUE TITLE
Feature Demand: breathalyzer

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11803]
Purpose - For telling how drunk you are (as opposed to how much alcohol is currently to be metabolized in the future)
Actual purpose - For showing off how much alcohol you drank in the bar. Getting the highest score.

**Comment by Killette2** [comment]
Sec can also use one of these if you're in the hall running drunk.

**Comment by Probe1** [comment]
Closed in the breathalyzer pr
