### ISSUE TITLE
Feature Suggestions and Issues: Xenoarcheology Update

### ISSUE THREAD

**Issue by AceDick** [d3athrow/vgstation13#11808]
Alright, with the xenoarcheology update adding a new R&D tree and modifying the way scanning large artifacts works, I've tested it across two rounds and done so along with an assistant, and run into a handful of issues with it, as well as a few ideas to toss out there, with the hope of inspiring future updates.

Issues currently:
- As the result of the artifact scan reports being research objects, they've been made able to be scanned by mechanic analyzers for the reverse engine, presumably to be able to be reproduced using the general fabricator. I can't imagine this was intended, I was not able to get a chance to going through the full process of reverse engineering to see if it even works, or scanning smaller artifacts to do the same, so more testing may be needed. It could be repurposed into a way of reproducing artifact finds.
- I'm aware the new anomaly scanner was commented out pending the discussion had in #11630 to allow the new features in sooner, but the new changes making the ability to read the full artifact report require the scanner were not removed, making it impossible to get large artifact secondary triggers and descriptions, or in the case of those containing a full description in the first paragraph and effects in the second, impossible to get the artifact's triggers at all. Until the merge is changed in either direction, either removing the changes in how artifact scan reports require the new scanner to fully read or adding the scanner needed to decrypt the report, it makes researching larges more a crapshoot.

Suggestions:
- Anomaly tech tree is kinda barebones, some ideas for more stuff like:
  - ability to create more of the anomaly power utilizers and cells
  - upgraded versions of the power utilizers to allow more precise means of releasing the stored energies, one of my biggest gripes with trying to make artifacts useful somehow, at the moment all harmful artifacts were you to try and harness them, run the risk of affecting yourself and everyone else in around you. I propose having better utilizers that can release on touch like a stun baton (giving doctors a healing touch comes to mind) and through projectiles like a gun (making them less unwieldy to use when giving them to security) unlocked through anomaly research, as well as having ones that can release a bigger AOE at the cost of depleting charge much faster or something to that effect
  - similar to above, better cells that can store more charge than the initial ones
- One of the biggest calls for this update is deterrents for miners just plowing through artifact sites. While reducing chances of getting smalls from drilling are reduced, there is little to no penalty for destroying larges. Since these are large pieces of alien tech whose effects can wreck those without protection, and we already have it in the code for there to be a flash and some very limited damage to those around to experience it, why not increase the damage and/or have effects based on the type of artifact destroyed (like summon monsters for the destruction of the cryo pod, drawing from one of the effects for a generic artifact, etc.) so there's risk to carelessly pushing through the centers of anomaly sites?
#### Server revision

0f9616e623dcab5af936d4b15bc7f108fc8c9749
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by icantthinkofanameritenow** [comment]
> One of the biggest calls for this update is deterrents for miners just plowing through artifact sites. While reducing chances of getting smalls from drilling are reduced, there is little to no penalty for destroying larges. Since these are large pieces of alien tech whose effects can wreck those without protection, and we already have it in the code for there to be a flash and some very limited damage to those around to experience it, why not increase the damage and/or have effects based on the type of artifact destroyed (like summon monsters for the destruction of the cryo pod, drawing from one of the effects for a generic artifact, etc.) so there's risk to carelessly pushing through the centers of anomaly sites?

I like this idea, though the monsters would need to be appropriately buffed given how well-equipped miners are to handle monsters. Perhaps it would be simpler to just have them explode like a bomb or gibtonite, but that might just be overkill. 

Adding the anomaly scanner back in would be for the best. As long as it doesn't openly reveal the triggers and effects, it wouldn't just break xenoarch.  Power utilizers are never used at all to my knowledge- there just aren't enough people who know how to use them, let alone effects strong enough to justify it.
