### ISSUE TITLE
The letter "Ñ" does not display in either IC and OOC chats

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11800]
(WEB REPORT BY: dawhatthefox REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> The letter "Ñ", in either capital or lowercase, makes whatever you have just typed and sent not display to anyone but you.
> 
> What you expected to happen
> For it to work properly.
> 
> What actually happened
> I can see what I sent, but the receiver cannot.
> 
> Steps to reproduce if possible
> Just use the letter when talking with someone.

**Comment by PJB3005** [comment]
Same problem as #11682
