### ISSUE TITLE
Ragin' Mages master wizard

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11802]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!) b8e7229165f155603273a67c73d484715bc12a3d 
> 
> General description of the issue
> You can refund other wizards' spellbooks in raging mages causing yourself to become a MASTER WIZARD
> 
> What you expected to happen
> Not able to refund other wizard spellbook
> 
> What actually happened
> TREMBLE BEFORE MY LARGE AMOUNT OF SPELLS, MORTALS
> 
> Steps to reproduce if possible
> Be angry magician and refund the spellbooks of the wizards before you

**Comment by clusterfack** [comment]
@unid15 I mentioned this earlier

**Comment by Killette2** [comment]
Keep this, if they killed the last wizard we need a more robust wizard to take their place.

**Comment by gbasood** [comment]
nah that's dumb

**Comment by ConkerDev** [comment]
We need this
https://i.ytimg.com/vi/c9-KRo8IQ1I/hqdefault.jpg

**Comment by Killette2** [comment]
That looks like it was from that real Scooby Doo movie, where Scrappy Doo was the villian hiding in a robot collecting souls. That movie sucked.
