### ISSUE TITLE
Waffleceltpipes are a SHAM, a SHAM I tell you

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11806]
![](http://puu.sh/r3MEa/ab35e81ef5.jpg)

**Comment by Killette2** [comment]
Those have always been like that

**Comment by PJB3005** [comment]
I know why this is. The injector is placed "under" the floor, but the pipes aren't.

**Comment by xpcybic** [comment]
more like a shamROCK get it because you're a leprechaun ha haha

**Comment by PJB3005** [comment]
What map is this, this is a mapping issue. Not Wafflepipes fault.

**Comment by Probe1** [comment]
Feck off and come back with a real issue report

**Comment by PJB3005** [comment]
Pretty sure this is deff actually.
