### ISSUE TITLE
Slimes are largely invincible(?) or extinguishers are busted

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#11819]
Just had a round where no matter how much you sprayed slimes with an extinguisher, they'd never die. They died when shot with a temperature gun or dragged into space, but extinguishers had no effect on them whatsoever.

Not sure that there was any relevant context to the bug, they just weren't taking damage from extinguishers.

**Comment by Shadowmech88** [comment]
Are you sure that the extinguisher you were using was filled with water?

**Comment by Hoshi-chan** [comment]
100% positive. I _had_ filled it with space cleaner before, though.

Is it possible that filling an extinguisher with something other than water, then filling it with water later on somehow fucks it?

A xenobiologist in the same round was ALSO spraying the slimes with an extinguisher with no effect.

**Comment by Shadowmech88** [comment]
Extinguishers are old.
It's possible that could fuck with it due to shitcode buried somewhere in the extinguisher code.

**Comment by nervere** [comment]
Tested fire extinguishers, fiddling with reagents inside them, etc. Can't reproduce it. Definitely not an issue anymore.
