### ISSUE TITLE
Derelict MoMMIs on Metaclub don't have their "don't leave the station" law

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11813]
(WEB REPORT BY: mayneez REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Basically derelict MoMMI doesn't have the law that forbids them from leaving the station
> 
> What you expected to happen
> I expected the MoMMI to have that law
> 
> What actually happened
> It didn't
> 
> Steps to reproduce if possible
> Spawn as MoMMI on metaclub, check laws

**Comment by gbasood** [comment]
sounds like the spawner is wrong?

**Comment by AutismSpider** [comment]
Isit using the Dwarf Fortress mommi spawn pad?

**Comment by clusterfack** [comment]
This requires a map edit to changed the locked_to_z variable to the zlevel it is placed on.
