### ISSUE TITLE
map error in box station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11816]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> there is a table under the mechanics  research console for no reason
> 
> What you expected to happen
> no tables under the consoles
> 
> What actually happened
> there is a table there
> 
> Steps to reproduce if possible
> go on vg station
> see a table under the mechanics console thing

also the mechanics office in box should be bigger

**Comment by gbasood** [comment]
confirmed
![](http://i.imgur.com/yh2O2SU.png)

**Comment by uazuaz** [comment]
on boxstation there is also an air alarm on the floor under the AAC above the TEG.

![aa](https://cloud.githubusercontent.com/assets/6170726/18359999/9add80a2-75fc-11e6-8cd5-b8a6a10d09c9.jpg)

should i open another issue?

**Comment by gbasood** [comment]
yes

**Comment by PJB3005** [comment]
I literally knew about this computer being weird like that for as long as the mechanics workshop was here.
