### ISSUE TITLE
Cyborgs need a hat slot

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#11835]
PLEASE
its the saddest thing on earth that they can't.

**Comment by NigglyWiggly** [comment]
no

This would also be hard to do what with all the different shapes and sizes of our cyborgs

**Comment by PJB3005** [comment]
See, this is a problem we dug ourselves into with borgs.

On goon, borgs are human shaped _and_ can wear clothing, it's really cool.

We literally cannot do that with the hole we dug ourselves into. Due to our like, what, 50 borg icons, we can't really do that, because it wouldn't fit on most of them.

**Comment by TheFriggenSawbones** [comment]
FUCK

**Comment by Exxion** [comment]
Obviously we need to make a sprite for every hat for every borg sprite

**Comment by TheFriggenSawbones** [comment]
YES

**Comment by unid15** [comment]
MoMMIs do it somehow so why not borgs

**Comment by Exxion** [comment]
Because MoMMI sprites are all the same basic shape

**Comment by clusterfack** [comment]
Look at where the engiborg head is, you know the only good engiborg sprite that everyone uses. It's at a different pixel x/y for every direction which is something we just cant do softcoded for each hat.

**Comment by NigglyWiggly** [comment]
You know what we could do though

_Cyborg paintjobs_

**Comment by Shadowmech88** [comment]
We can't dynamically change the pixel offset of the cyborg's hat layer overlay based on which direction it's currently facing?

**Comment by clusterfack** [comment]
I suppose its technically possible but rather annoying. 

Basically you need to specify the pixel x/y value of the head for every direction of the borg icon. Then you icon procs to dissect every hat into four icon states which are pixel shifted to that 'correct' pixel x/y location then insert them back into a single multidirectional icon state and then add that generated icon state into the overlay of the borg.

**Comment by Shadowmech88** [comment]
So we just need to write the icon procs for borgs in general, and then have a function that assigns a value to a hat x/y offset var for each direction based on which sprite the borg is using?

Doesn't seem like it'd be that difficult to do. Finding the hat offsets for every single sprite would certainly be tedious, but not technically difficult.

I'm sure we can find _someone_ willing to compile a list of every borg sprite and its associated hat x/y offset for each direction.

**Comment by ihadtoregisterforthis** [comment]
A tedious job for a feature that will be largely unused. Remember borgs would need someone else to fit them as they can't grab the hats. Like dressing monkeys or Ian.

**Comment by clusterfack** [comment]
Well also I can't speak to how bad the performance of that would be, I generally avoid using icon procs whenever I can do so. But yeah I just wanted to confirm that it is -theroretically- possible.

**Comment by SonixApache** [comment]
WANT TO WEAR A HAT?
PLAY AS A CARBON OR A MOMMI

FUCK BORGS
