### ISSUE TITLE
Air alarm or vents

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11838]
(WEB REPORT BY: sandysand REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> scrubbers/vents don't appear off or on when switched
> 
> What you expected to happen
> animation to appear off/on when switched to that setting
> 
> What actually happened
> nothing changed but it seems like i can still unwrench them
> 
> Steps to reproduce if possible
> toggle vents/scrubbers using air alarms

**Comment by PJB3005** [comment]
Welp I broke this with wafflepipes.
