### ISSUE TITLE
Paper cups

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11833]
(WEB REPORT BY: pinkacolada REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
>  Well I didn't want to get a beaker so I grabbed a paper cup and tried to jiggle that into the Pathogenic incubator and it won't fit. Also I can't pour out this cup of virus food.
> 
> What you expected to happen
>  The cup go into the thing, just like  a beaker
> 
> What actually happened
>  It didn't
> 
> Steps to reproduce if possible
>  Fill a paper cup with something and put it into the incubator

**Comment by Kurfursten** [comment]
Paper is organic matter, I don't think it would be very sterile to grow viruses on that surface.

**Comment by PJB3005** [comment]
Sorry but do you really except to be able to put a paper cup into a pathogenic incubator?

**Comment by NigglyWiggly** [comment]
How is this an error?

**Comment by TheFriggenSawbones** [comment]
buddy you need to not cheap out on your virology supplies

**Comment by Exxion** [comment]
Why do we even call them viruses? Everything about how they behave is more like bacteria

That's a separate issue though

**Comment by Shadowmech88** [comment]
What would we call the department, then? Bacteriology?

**Comment by Exxion** [comment]
Pathogenics
Epidemiology
Probably some other possibilities too

**Comment by despotate** [comment]
Someone please close this idiotic issue

**Comment by Probe1** [comment]
Because epidemiologist doesn't sound rad as fuck.

Also no people are allowed to make feature requests and they are allowed to sit for a while until I close them because its not been filled in 4 years.

**Comment by despotate** [comment]
It's asking for the ability to have **paper cups** be inserted into industrial-grade space machinery because this person tried to do so in-game out of pure laziness and failed. It's practically a troll issue.

**Comment by Exxion** [comment]
Yeah no it's pretty dumb

**Comment by Probe1** [comment]
We have far more stupid shit with beakers and I cannot fathom why this featreq generated such a response but I'm moving on with my life.

**Comment by Exxion** [comment]
Probably because all the stupid shit we have with beakers is side effects of how things are coded
Nobody requested to allow rags to go in chem dispensers
They just do
But here someone (who happens to also be a thread meme) requested to add to the stupid shit

No, I don't think the hostility was necessary, but on a codebase for a 4chan server it's to be expected
