### ISSUE TITLE
Can't swipe ID card in Airlock electronics

### ISSUE THREAD

**Issue by Manfreedo** [d3athrow/vgstation13#11834]
Clicking on "Swipe ID" in the menue that pops up when I use the Airlock electronics PCB does nothing for me. Apparently for other people this brings up a menue to select the acess requirtements for the airlock. For me the text just turns purple. No text about anything working or not working.

Length of time in which bug has been known to occur:
Forever for me, for others it seems to be working right now.
- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

Edit: Works with engineering acess but there is no feedback if tried without propper access. A "Access Denied" message would do I guess.

**Comment by Kurfursten** [comment]
This isn't broken, it's just unintuitive.

You're supposed to click the unlock link with your ID in your ID slot (or PDA). If it's in your hand, it won't detect the ID.

**Comment by Manfreedo** [comment]
@Kurfursten 
I was Instructed to do so when I ahelped about it.
Didn't help.

**Comment by Manfreedo** [comment]
![its blobsquad](https://cloud.githubusercontent.com/assets/20943168/18412848/4ede2e92-7799-11e6-929f-8330249517c8.PNG)
Here is an image for clarification. The PDA has my ID in it. I also tried it with the plain ID in the ID-slot.

**Comment by uazuaz** [comment]
in the picture you're an assistant; did you try it as assistant only? you need engineering access to do that.

maybe a "access denied" message when using an incompatible id would help to avoid confusion.

**Comment by Shadowmech88** [comment]
Really it should ALSO be changed so that it detects your ID in your hand.

As it is now it's really unintuitive.

**Comment by Manfreedo** [comment]
@uazuaz Works. But yea this realy needs some sort of feedback if you don't have acess.
