### ISSUE TITLE
Subspace tunneler can be used through cameras and across z-levels

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11836]
#### Description of issue

You can use the subspace tunneler at any distance as long as you're able to see the turf/object through cameras or some other means. If you're clever enough you can use it to get on Centcomm.
#### Difference between expected and actual behavior

Probably lock it by Z-level at least.
#### Steps to reproduce

Create a subspace tunneler
Look through a security camera
Teleport stuff back and forth through the camera

You can also use this to get onto Centcomm from the station, and I'm sure derelict MoMMIs can find a way if they're clever enough.
#### Specific information for locating

/obj/item/weapon/subspacetunneler
#### Length of time in which bug has been known to occur

As long as the SST has existed probably
#### Server revision

7ca0599ebd13816fbe618fa5cb320b42eaa5a6b6 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ComicIronic** [comment]
What's a subspace tunneler?

**Comment by TheFriggenSawbones** [comment]
item added in Shadowmech's ghetto weapon update.

It's like a gun that can store item within itself and teleport the stored item elsewhere - so as I understand it doesn't check if you're looking at somewhere with a camera. So you can technically pick up most things, while looking through sec cameras, and teleport it anywhere.

**Comment by Exxion** [comment]
@Shadowmech88

**Comment by PJB3005** [comment]
Okay how do we want to fix this, prevent cross Z level, to centcomm or make it NEED to be in view?

**Comment by clusterfack** [comment]
Just do range 7 around the subspace tunneler

**Comment by Shadowmech88** [comment]
Given that the device is supposed to teleport things, is it really an issue if it can be used through cameras?

Obviously fix the ability to get to Centcomm with it, but otherwise, what's the harm? How often is it even made, anyway?

**Comment by clusterfack** [comment]
I mean people have already found several things that can be harmful about it from the lack of sanity it initially had.

**Comment by Shadowmech88** [comment]
This is the only bug report for this item that I can find.

What other things need to be fixed about it?

**Comment by clusterfack** [comment]
Well I haven't seen other issue reports about it because people are intentionally not reporting them so they can abuse it more.

**Comment by PJB3005** [comment]
Then why haven't you reported it @clusterfuck?

**Comment by clusterfack** [comment]
I've never had a chance to play around with it, so I couldn't accurately describe to you with much precision exactly can or cannot be done with it.
