### ISSUE TITLE
Optical Material Scanner Interference

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11830]
(WEB REPORT BY: hoborobo REMOTE: 172.93.109.202:7777)
Revision: 7ca0599ebd13816fbe618fa5cb320b42eaa5a6b6 

> General description of the issue
> Pipes cannot be unwrenched and valves cannot be interacted with if you are wearing an optical material scanner that is turned on.
> 
> What you expected to happen
> To be able to interact with secured pipes and valves and such with my optical materials scanner turned on.
> 
> What actually happened
> Unable to unwrench pipes or interact with valves if wearing an optical material scanner that is turned on.
> 
> Steps to reproduce if possible
> Wear an optical material scanner, make sure it's on, try to unwrench a pipe or interact with a valve.

**Comment by clusterfack** [comment]
Where in the fuck are you getting an optical material scanner. Theyre not available at all

**Comment by PJB3005** [comment]
> not available at all.

#9311

**Comment by PJB3005** [comment]
Anyways I'll probably end up fixing this by making the holomaps be literally on the `FLOAT_PLANE`.

**Comment by clusterfack** [comment]
Oh you stole the name for something else?

**Comment by PJB3005** [comment]
Yes.

Also, this is what I ran into when trying to get this to work:

https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/09/2016-09-10_15-08-07.webm

For some reason the existance of the underlays is causing the rest of the manifold to not render...
