### ISSUE TITLE
Xeno queen can use the ventcrawl verb.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11848]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision c2dd2915cf7e64e8a4fa1e9af209fb93a71cf607 
> 
> General description of the issue
> Title
> 
> What you expected to happen
> Queen to not be able to ventcrawl
> 
> What actually happened
> 'crawl-through-vent' lets you hop into vents (but alt-clicking does not)
> 
> Steps to reproduce if possible
> Above

**Comment by FantasticFwoosh** [comment]
I was present the round this was in, can confirm but i didn't see it firsthand.

**Comment by AutismSpider** [comment]
old bug is back lets the fat ass queen vent crawl

**Comment by 9600bauds** [comment]
thicc xenos strike back
