### ISSUE TITLE
WAFFLEPIPE SHAM

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11840]
![](http://puu.sh/r78fL/e6e3979b3e.jpg)

**Comment by PJB3005** [comment]
It this on the map or not.

This is important info nerd.

**Comment by jknpj** [comment]
Is this the metaclub's vox outpost cycling airlock?

**Comment by Shadowmech88** [comment]
I'm not even sure what this is supposed to be.

**Comment by Exxion** [comment]
This is why you don't use puu.sh
