### ISSUE TITLE
Vox doors lack trader access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11847]
(WEB REPORT BY: fantasticfwoosh REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

c2dd2915cf7e64e8a4fa1e9af209fb93a71cf607 

> General description of the issue
> Nearly all vox trading station doors on boxstation are open access to use by anybody and summarily require manual input to seal to stop intruders (via welding or bolt triggers)
> 
> What you expected to happen
> Doors to be secured with trader access as to maintain boundaries and secure the compound.
> 
> What actually happened
> Scientists and miners entering the compound and summarily helping themselves to the supplies there intended for local vox population because the doors are all access.

Resulting oxgen coming through unintentionally on the doors opening also triggers the localised fire locks in small quantities

> Steps to reproduce if possible
> Play as vox trader and take off your id to walk through the doors, additionally invite miners outside from the opposing doors in the oxygen filled foyer.

**Comment by FantasticFwoosh** [comment]
Hello apologies on the poor formatting, i filled this in from the in-client bug reporter (for uniformity i share my ckey name and my github name). I am on hand if people require any first hand elaboration on the issue or for me to re-format my issue report. (as i notice the revision code seems to have gotten lost)

Thanks.

**Comment by Kurfursten** [comment]
Yeah, this is fixed in #11441

**Comment by FantasticFwoosh** [comment]
Thank you, people were abusing Vox's hard

The Vox independence league liason intermediary & auxillary negotiators (VILLIAN) thank you

---

Additionally i can recently confirm that ID modifications are needed on lockers too, namely the hydroponics locker which also opens without relevant trader ID

**Comment by Probe1** [comment]
Custom vote started by Kavlax.
#11847 Should the Vox Outpost airlocks require Vox Trader access?
Type vote to place your votes.
You have 60 seconds to vote.

Vote Result: Yes with 7 votes
No had 3 votes

**Comment by Probe1** [comment]
Custom vote started by Kavlax.
#11847 **Should the Vox Outpost airlocks require Vox Trader access?**
Type vote to place your votes.
You have 60 seconds to vote.

**Vote Result: Yes with 7 votes**
No had 3 votes

**Comment by Probe1** [comment]
Custom vote started by Diethyl.
**Should the Vox Outpost airlocks require Vox Trader access?**
Type vote to place your votes.
You have 60 seconds to vote.

**Vote Result: No with 8 votes**
	Yes had 6 votes

**Comment by Kurfursten** [comment]
Maybe we should have some control tests. Example: ask if the research division should require science access or cargo bay require cargo access.

**Comment by Probe1** [comment]
I'm going to try limiting it to the high risk doors that people _want_ to break into based on feedback.  That way players can freely move throughout the Tradepost but it isn't lolfreejetpacks.

**Comment by Kurfursten** [comment]
You should remove the front lobby entirely, it's an artifact of a pre-shuttle era and is only used to leak oxygen into the base due to lack of access on doors.
