### ISSUE TITLE
Broken Welder

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11856]
(WEB REPORT BY: hoborobo REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 824f1382b72e9ad7fa56881e016ac8b6b2ca0a75 
> 
> General description of the issue
> Welder shuts off and does not turn on when fueled
> 
> What you expected to happen
> The welder to turn on
> 
> What actually happened
> The welder did not turn on.
> 
> Steps to reproduce if possible
> No idea, it just happenes some times. I'm looking at it right now and it says 20/20 units of fuel but it won't turn on.

**Comment by PJB3005** [comment]
I can confirm this.

**Comment by clusterfack** [comment]
How do bugs like this even happen

**Comment by Blithering** [comment]
Have you checked it was secured? they can be unscrewed for the flamethrower recipe and that prevents them working.

**Comment by Shadowmech88** [comment]
Were we able to reproduce this? It still has no tags.

**Comment by unid15** [comment]
happened to me once

**Comment by Probe1** [comment]
Happened to me while I was doing that welder PR.  It's real but it seems to happen just because shit fucks up in the MC or something who goddamn knows.

**Comment by ghost** [comment]
Might very well have been fixed by #12937 which fixed a welder runtime?

**Comment by Exxion** [comment]
I don't think so, but who knows?

I can't see in the code any way in which this could happen other than how Blithering described.

**Comment by Zth--** [comment]
Any signs of life?

**Comment by Shadowmech88** [comment]
Given the lack of testing/reproduction steps and the age of this report, I think it can be closed.
In fact I think I remember a problem like this being fixed specifically.
