### ISSUE TITLE
blunderbuss doesnt fit on suit armor slot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11857]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> cant fit
> 
> What you expected to happen

fit

> What actually happened

cant fit

> Steps to reproduce if possible
> try equip the blunderbusss on armor slot

**Comment by Exxion** [comment]
If you're going to do this, just delete the template

Also, different exosuits have different things that can be put in their suit storage. You mean you want it to fit on regular old sec armor, right?
