### ISSUE TITLE
glitching when using pAI to open doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11853]
(WEB REPORT BY: punishedchiot REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> http://puu.sh/r8irn/d74bf9abe2.png
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
Holy shit an error message while not on local?

**Comment by ghost** [comment]
I'm sure this is a duplicate.

**Comment by clusterfack** [comment]
It's a byond issue that pops up when you have your (I believe language?) settings fucked up.
