### ISSUE TITLE
Improper Layer Stacking on Chair Construction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11854]
(WEB REPORT BY: fozzington REMOTE: 172.93.109.202:7777)

> General description of the issue

When constructing a chair (comfy/regular only, office seems to work correctly) facing North (and North only), buckling into the chair results in character sprite remaining above the chair. This effect persists when unbuckling, rebuckling, and moving on and off the chair, ending only when chair is rotated, after which all directions work as they should

> What you expected to happen
> 
> Build chair
> Sit in chair
> Be comfy
> 
> What actually happened
> 
> Build chair
> Sit in chair
> Straddle chair awkwardly
> 
> Steps to reproduce if possible
> 
> Build a comfy/regular chair while facing North (Up in 2D-Land)
> Buckle onto built chair

**Comment by ghost** [comment]
I guess update layer isn't called on new
