### ISSUE TITLE
Arm blades shouldn't work through hardsuits

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11852]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by AutismSpider** [comment]
make sure does same thing for borer shield sword and hammer etc

**Comment by Killette2** [comment]
Do we really need this level of realism?
You can eat through hardsuits, your bones can break in hardsuits while your suit is just fine. Hardsuits never made sense.

**Comment by AutismSpider** [comment]
well i bet people would cry if hard suits took damage and you need kits to fix them up etc.

**Comment by TheFriggenSawbones** [comment]
or make it so the armblade layers above the hardsuit so people can see it

**Comment by ghost** [comment]
The issue isn't that people can't see it, it's that a hardsuit is used to keep air in, and therefore to use an armblade through it would not really work
@Killette2 yes

**Comment by AutismSpider** [comment]
@Killette2 its sharp ass blade coming out of a air tight suit they take the suit off to use this power or the suit becomes useless on use.

**Comment by Killette2** [comment]
@AutismSpider you mean that suit you can have while wearing a hive hand, you can use stun gloves through, and wear even with items glued to your hands which would logically prevent it?

**Comment by clusterfack** [comment]
Clearly they should both check body coverage before use

**Comment by AutismSpider** [comment]
@Killette2 never get why you can stun glove people with a hard suit on that shit is dumb same with hive hand on.

**Comment by Shadowmech88** [comment]
Is there _anything_ that is outright prevented by hardsuits aside from pressure damage?

I think you can even use autoinjectors on people wearing hardsuits.

**Comment by Exxion** [comment]
Syringe guns and, as far as I'm aware, exactly nothing else

**Comment by PJB3005** [comment]
Syringes have a longer `do_after` with hardsuits.

**Comment by icantthinkofanameritenow** [comment]
I'm not sure this change would leave eswords unaffected. Code-wise, the only difference between them is that the armblade can't be dropped.

**Comment by Allspice** [comment]
Can't trauma-kit internal organs with hardsuits on, but you can slice and dice and do about every other surgery through the suit.

**Comment by Killette2** [comment]
what if we removed hardsuits? they're just for powergaming anyways, when have you ever needed a hardsuit?

**Comment by AutismSpider** [comment]
only like three or four  jobs that really need hard suit

miners Sec for when they need to deal with ops or jew birds in space we should just combine engi and atmos hard suits as one.

All the suits in eva should be cheap grey ones.

**Comment by icantthinkofanameritenow** [comment]
@AutismSpider
I'd second that if it weren't for the fact that the grey suits don't allow full-size oxygen tanks to be kept in suit storage. That alone cripples their usefulness since it forces you to either give up your backpack or suffer with an oxygen tank that drains fast even when filled to maximum.
