### ISSUE TITLE
Box (livestock Vox Animal) unpolished, no death state messages

### ISSUE THREAD

**Issue by FantasticFwoosh** [d3athrow/vgstation13#11858]
#### Description of issue

The actual 'Box' animal is not consistent, when it dies for whatever reason the states after are not consistent with other mobs in lacking a death message and emitting a individual noise upon butchery post death, in general it could do with a rework or a touch up
#### Difference between expected and actual behavior

Some kind of message to indicate that the box that i have been cloning has died, I IC was busy managing station hydroponics in the presumption that the box i cloned would survive, however it soon died. I thought that it would die with a message (there was none in the chat) and just give off the usual gibbing noise when it is butchered.

What did result is that the box triggers its death sprite without warning, and upon butchering emits a deathscream, which is nonsensical as it is already dead without fabricating up a reasonable conclusion.
#### Steps to reproduce

Obtain box cloning kit, set up on either the station or the nitrogen laden (more specifically the regular station would be a good place to test due to the dangerous oxygenated atmosphere) vox base and feed box meat into the cloner, a box baby should emerge and shortly die of a lack of No2 air after. No death messages should occur as in line with the issue and the box sprite should be overturned hooves up.

Then proceed to butcher the box with a kitchen knife/butchering implement and upon the final gibbing carve it will issue a deathscream despite it already being dead.

**Comment by Exxion** [comment]
Also can we _please_ change its name?
It's really confusing

**Comment by SonixApache** [comment]
how about Vig? Vox pig.

**Comment by Exxion** [comment]
I don't really like how that sounds, but at the very least it's less confusing

**Comment by FantasticFwoosh** [comment]
Making it more boarish would help i think rather than a run of the mill green piggie, some aggressive tendencies for additional flavour. Lots wrong with their code right now, not least having the same amount of meat whatever size (in relative time = growth) it gets to. Usually 1 slab of meat for the cloner ready and a spare for cooking/eating each time.

None of the fruit and veg are called vox fruit or voxtables, vig seems a little silly but its a good try.

**Comment by ghost** [comment]
I like the name box

**Comment by ComicIronic** [comment]
Voar?

**Comment by Exxion** [comment]
See there's a slight problem with that one

**Comment by ComicIronic** [comment]
We're already pandering to that crowd.

**Comment by FantasticFwoosh** [comment]
@DrCelt its unflattering when 'you pet the box'

Like really, box, boxes, boxen where do inanimate objects and green space pigs begin or end?

**Comment by Exxion** [comment]
Also it gets confusing because we refer to tgstation as Boxstation, often just shortened to Box

**Comment by ComicIronic** [comment]
My pig's a box, damn you! A box!

**Comment by JustSumBody** [comment]
You also can't give them a mask and nitrogen internals to bring them on station alive, they just suffocate before you get them on the shuttle
I had a gimmick I wanted to do

**Comment by FantasticFwoosh** [comment]
@JustSumBody Why not try to make cages internalized so that you could localise the air in there so you can drag the piggies onto the station safely until you get a correct environmental holding place to let them loose. Vox's dragging round cages full of wild exotic beasts sounds very traderish.

"You attach the nitrogen air canister to the cage's localised air supply" (though i am aware of the huge ass bars provided for air which again might be a issue but wave it off as bluespace or modify the cage design/use a alternative holding box)

Ranching needs more emphasis on actual game mechanics as keeping a box is usually only relevant to harvesting minimal amounts of bacon food items (when box meat is processed in a microwave) giant battle steed emus/ angry box boars some actually interesting fauna for vox to sell with co-dependent diets on certain vox plants (box prefer and grow better on breadfruit etc) are up on the table of possibility to enhance this system.

**Comment by ghost** [comment]
Box should be like sheep, their full name should be Boxen and the plural is Boxen, because English is a shit language we can do whatever we want.
