### ISSUE TITLE
Vox traders spawn in addtional space suits with internals on INSIDE the safe Vox base

### ISSUE THREAD

**Issue by FantasticFwoosh** [d3athrow/vgstation13#11861]
#### Description of issue

Vox traders spawn fully suited in movement impeding space suits and hooked onto internals with a mask already active regardless of the map settings whether appropriate or not, it appears to have been a oversight and requires some quality control.

One such benefit is selling on the spare suits generated by round-start joining up as a Vox trader but often these desirable objects are thrown out of balance when your base is fully stocked with them and summarily quantity of stock depletes demand. Having the suits be rare and non-generated upon roundstart would make them commercially and convenience wise rare and valuable.

Vox already start with appropriate uniform clothing ('alien clothing') and internal starter boxes (with pocket sized personal canister of No2 and spare mask) so moving suits/No2 canister distributors (of the large suit fitted kind) to a seperate area and unifying the vox map design to accomodate fully suited/casual unsuited vox traders in a safe breathable enviroment on round-start need to be considered. 
#### Difference between expected and actual behavior

On non-box maps such as the metastation map where the vox are seperated and must find the new intermediary vox base/trader shuttle it works as intended. You would think the same experience for providing the suit that they give you each and every time would be the same result of 'finding through deep space' your new hideout putting your suit, mag-boots and high supply of No2 to use.

The metastation map's premise is unique and this loadout normally fits quite well for that scenario but for everywhere else it is inappopriate not to mention duplication of (as mentioned in this issue report #11860 , VERY strong space suits already fitted and entirely space worthy.) EVA equipment out-scaling station supplies which aren't needed and are a hindrance to function and movement inside the safe vox base, discouraging traders from working on localized base departments (engineering & botany) and instead to instantly rush off to the ship slowly with suit slowdown.
#### Steps to reproduce

Select your racial preferences to Vox, and set trader to high, you will spawn in the local vox dorms OR the alternative meta station salvage startpoint, only on box is the suit & air tank equipped (additional testing for other map starts needed to clarify)

**Comment by ihadtoregisterforthis** [comment]
It's just N<sub>2</sub>
There's no o involved
And if there were, it would be capital, as well as after the 2

**Comment by Exxion** [comment]
Man don't you go stealing my posts

**Comment by FantasticFwoosh** [comment]
Sorry tg force of habit, on topic about the discussion please though.
