### ISSUE TITLE
Air and external airlocks

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#11863]
#### Description of issue

i saw this on boxstation, i don't know about other maps.
some of the external airlock tiles around the station block gases even if the airlock is hacked open or destroyed; if you check the air on these tiles with an air analyzer or as a ghost, you see that they are at 101.3 kpa no matter what.
in this comment https://github.com/d3athrow/vgstation13/issues/11585#issuecomment-243796522 @Exxion said that old coders did it on purpose; i think that it could be changed so gases could pass through open external airlocks as they should.

i saw people hacking open these airlocks trying to vent the station during a plasma flood multiple times, but it's totally useless of course.
![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/18467669/34e22174-79a1-11e6-8ea2-c02a0c98bbc1.png)
#### Difference between expected and actual behavior

opening an airlock should let all the gases pass through;
spess magic prevents this.
#### Steps to reproduce

open those specific airlocks, enjoy your air anyway.
#### Specific information for locating

i checked on the test server and the affected airlocks are
- both airlocks leading to the singularity generator
- airlock between the AME room and the engineering escape pod
- all solars
- supply shuttle dock's **_internal**_ airlocks
- dock N of arrivals, between ghetto bar and escape pods
#### Length of time in which bug has been known to occur

maybe forever
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
This used to be the norm
Then the oldcoders/mappers left and ones who aren't idiots replaced them, so it's not anymore
But we haven't removed all  of them yet

**Comment by Exxion** [comment]
And... apparently you pointed to me saying that before but I was too tired to notice
Carry on then
