### ISSUE TITLE
Buttbot's only seem to hear through intercoms and radios

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11865]
Revision: 6db9bf47a602d82e47355c0af6eea24446cd1ab2 

Talking to a buttbot doesn't make it repeat what you're saying
UNLESS it hears what you're saying through the radio/intercom.

**Comment by clusterfack** [comment]
Not actually sure why this would happen

**Comment by jknpj** [comment]
I blame their hear()

>Hear(message, atom/movable/speaker, message_langs, raw_message, radio_freq)
		This proc handles hearing. What it does varies. For mobs, it treats the message with hearer-specific things
		like language and deafness, then outputs it to the hearer.
>IMPORTANT NOTE: If radio_freq is not null, the code will assume that the speaker is virtual!
>
>VIRTUAL SPEAKERS:
Virtual speakers are simply atom/movables with a few extra variables.
If radio_freq is not null, the code will rely on the fact that the speaker is virtual. This means that several procs will return something:
	(all of these procs are defined at the atom/movable level and return "" at that level.)
	GetJob()
		Returns the job string variable of the virtual speaker.
	GetTrack()
		Returns wether the tracking href should be fake or not.
	GetSource()
		Returns the source of the virtual speaker.
	GetRadio()
		Returns the radio that was spoken through by the source. Needed for AI tracking.

**Comment by gbasood** [comment]
haha guess what this is STILL A bug
