### ISSUE TITLE
Vox Trader Suits are way too good

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#11860]
Alien Pressure Suit:
melee = 60 
bullet = 50 
laser = 30 
energy = 15 
bomb = 30 
bio = 30 
rad = 30

Nuke Ops Suit:
melee = 60 
bullet = 50 
laser = 30 
energy = 15 
bomb = 35 
bio = 100 
rad = 60

Alien Pressure Helmet:
melee = 60 
bullet = 50 
laser = 30 
energy = 15 
bomb = 30 
bio = 30 
rad = 30

Nuke Ops Helmet:
melee = 60 
bullet = 50 
laser = 30 
energy = 15 
bomb = 35 
bio = 100 
rad = 60

**Comment by TheFriggenSawbones** [comment]
It's the same armor Vox Raiders use for some reason??

So the solution would be to make a new suit for Vox Traders that doesn't have a fuck ton of armor

**Comment by FantasticFwoosh** [comment]
Or just have vox spawn without suits and a limited amount of suits/heavy kit in EVA, the vox base is already No2 filled and pressurised correctly so why are fresh spawns walking around/putting efforts into spare suits?

More ways to obtain suits (maybe some sort of vox trading post network console that takes raw credits for vox items) and vox equipment would be helpful.

**Comment by Exxion** [comment]
It's just N<sub>2</sub>
There's no o involved
And if there were, it would be capital as well as after the 2

But yeah might as well make them spawn suitless, considering there's a limit of three traders and vox EVA contains four suits

**Comment by icantthinkofanameritenow** [comment]
Maybe change the ones in the Vox Outposts and the ones the traders start with into a child of the original, with stats equivalent to a basic space suit. It would look the same, but it wouldn't have the protective value- and it would make sure the Vox Raider suits are unaffected.

**Comment by Allspice** [comment]
Minor tangent, but this all seems to stem from the bird outpost being both a trader den and a raider gearup area, although I'm not sure raiders ever truly 'geared up' there due to the skip's tools and toys. The suits are obviously excessive, but I'm also thinking about the f r e e jetpacks, the secvend, perhaps other things I'm missing. The bird nest should have some more thought given to what it should and should not have now that traders exist.

**Comment by icantthinkofanameritenow** [comment]
@Allspice
And I know I and a few other people have taken advantage of the fact that anyone can enter the outpost and take a jetpack for themselves, even if they aren't Vox.

**Comment by jknpj** [comment]
Birb Miner/Xenoarch/Scientist also enjoy the free alien suit

**Comment by ghost** [comment]
remove

**Comment by Durgen** [comment]
> suits too good

I always assumed this was compensation for the fact that traders are frequently bullied/arrested for no raisin.

Also, if they try to enforce castle law the same way say, the QM does, they will get lynched by silicons/security, so it helps to be able to take a bit of a beating instead.

**Comment by icantthinkofanameritenow** [comment]
They're not part of the crew and raiders constantly try to pass themselves off as traders. The bullying is totally justified.

**Comment by Durgen** [comment]
When traders get griffed they get no help from security, no help from silicons, and little sympathy for admins. 

Some stronk armor goes a long way to mitigate that.

**Comment by icantthinkofanameritenow** [comment]
Yeah, armor which can be nicked by any other Vox too. At least make it spawn on them to start with instead of being in the outpost for anyone to take. 

And honestly, they should have known that they'd be free game to griff by virtue of the job. Don't pick trader if you don't want to be griffed.

**Comment by Durgen** [comment]
How often do station vox head to the outpost to nab armor?
I don't think I've ever seen that.
What's much more common is xenoarchs/miners grabbing the free jet packs.

**Comment by Allspice** [comment]
Traders are 'glorified' grayshirts. Don't see assistants getting bloodsuits and jets in primary tool storage.

**Comment by icantthinkofanameritenow** [comment]
Seems to me that the simplest solution would be to make the suits available in the outpost a child of the original with their stats reduced compared to the original. The traders get to keep their appearance, but lose the nuke op-tier defenses. That sound reasonable enough?

**Comment by Exxion** [comment]
Yes, but preferably the sprite should be changed slightly and the description should definitely be changed

**Comment by icantthinkofanameritenow** [comment]
Reasonable enough. Any suggestions beyond calling it "trader's pressure suit"? Sprite-wise, I mean.

**Comment by Intigracy** [comment]
#12165
