### ISSUE TITLE
Make fly amantias less retarded please

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11877]
#### Description of issue

Fly amantias can evolve to the plastic shroom, the one you can already dispense from your vendor
#### Difference between expected and actual behavior

I expected to get destroying angels and not a shit plant that I already have
#### Steps to reproduce

``` dm
/datum/seed/mushroom/poison
    name = "amanita"
    seed_name = "fly amanita"
    display_name = "fly amanita mushrooms"
    products = list(/obj/item/weapon/reagent_containers/food/snacks/grown/mushroom/amanita)
    mutants = list("destroyingangel","plastic") ---------THESE ARE THE STEPS TO REPRODUCE
    packet_icon = "mycelium-amanita"
    plant_icon = "amanita"
    chems = list(NUTRIMENT = list(1), AMATOXIN = list(3,3), PSILOCYBIN = list(1,25))
```

**Comment by NigglyWiggly** [comment]
Fly Amanita turning into a poisonous hostile walking mushroom when

**Comment by Killette2** [comment]
when you code it
