### ISSUE TITLE
Human Trader

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11882]
(WEB REPORT BY: chaostamed REMOTE: 172.93.109.202:7777)
54e1aae89a56057a1644d6a5c80255983980d8b9 
I become a Trader as a human, when I intend to be an assistant.

I do not know what causes it, so it may not be able to be reproduced.

**Comment by Durgen** [comment]
I've seen this happen 2 times before
both times the human had the static name 'Victoria Ratthers' or something like that
I assumed at the time it was an admin screwing around

**Comment by clusterfack** [comment]
Yeah the fact you were trying to be an assistant is probably important, I think it put you into that rule due to the security vs assistants limit.

**Comment by ghost** [comment]
Victoria Rathens seems to be able to become a human trader time after time, seen them play it a lot

**Comment by Durgen** [comment]
![victoria](https://cloud.githubusercontent.com/assets/19157295/18605539/ff961c4e-7c59-11e6-8755-f96892324264.png)

edit: I just spoke to chaostamed. It seems to only effect them. So bizzare.

**Comment by Shadowmech88** [comment]
Apparently only ever affected one person, for some reason.
