### ISSUE TITLE
Removing your hardsuit helmet while on a stretcher makes the helmet disappear

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#11885]
What it says on the tin. It just vanishes from existence. I assume it might carry over to other items removed from your person while on the stretcher.

It also leaves the little "toggle light" icon on your HUD for your helmet, and permanently breaks it. Wearing a new helmet will not fix the HUD icon or allow you to toggle your lights with it.

**Comment by Exxion** [comment]
@unid15 

I'm about 90% sure it's removing the helmet from your head slot and trying to put it in your hand slot but failing because you're lying down, so instead the helmet just ends up in the endless void of your character without actually occupying a slot

**Comment by Killette2** [comment]
I've also encountered this bug, I was stunned and trying to take a tool out of my toobelt and it appeared ghostly where it once was in my inventory, and couldn't be used or removed. Item never appeared.

**Comment by unid15** [comment]
My bad, I'll fix it when I get home
