### ISSUE TITLE
Shrink space

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11880]
#### Description of issue

Space is too fucking huge and empty. There's hardly any vaults, and nobody is going to build in some random Z level.
#### Difference between expected and actual behavior

You float through space forever
I expected to actually land within 20 minutes
#### Steps to reproduce

Get spaced
#### Specific information for locating

Space
#### Length of time in which bug has been known to occur

since meme vaults

**Comment by unid15** [comment]
welcome to space, it's huge and empty

did you know that all the planets of the solar system can fit between Earth and Moon

**Comment by NigglyWiggly** [comment]
Do you understand what space is?

**Comment by jknpj** [comment]
expand space

**Comment by Killette2** [comment]
Yes space is big, but it's not fun. I'm not saying shrink it smaller, I'm saying **_revert_** space to what it was. It was manageable before, but now it's size is ridiculous. Are you saying space should be buffed, because that's what happened.

**Comment by ghost** [comment]
> space has too much space

🤔

**Comment by ihadtoregisterforthis** [comment]
But reverting space to what it was is precisely shrinking it smaller

**Comment by Killette2** [comment]
Yes it is, there was nothing wrong with old space. Then people suggested we make a ton of vaults, and barely a handful got made. We did overkill in expanding space, if anything it should be more z-levels rather than bigger z-levels.

And yes the classic space is space meme. There's nothing wrong with creating a time lapse and making you get to other points in space quicker. We can do a lot of things in space much quicker than how they happen in life. There's no need for space to be this much time filler while floating through it, it's not fun.

**Comment by Exxion** [comment]
Actually there was something wrong with old space.
We were out of it.
The station went nearly edge-to-edge horizontally.

Also yeah, you shouldn't expect to reach something quickly if you're just drifting, and if you have a jetpack it doesn't take very long.

**Comment by ghost** [comment]
The year is 2525. Scientists are working on new ways to get rid of all the buildings cluttering it. Space has been renamed "Full". The syndicate now get place to place by just hopping, and space ships have been rendered useless, and impossible to pilot.

**Comment by Killette2** [comment]
@Exxion that's the only valid point. Z-levels that are used, like asteroid and the station deserve to be big. Other z-levels, especially ones with less than the mass of the derelict, do not have a justifiable reason to be so big.

And yes I'm aware the other things the derelict z-level shares, that should be the minimum threshold for taking up all that space.

**Comment by TheFriggenSawbones** [comment]
i hope some day we can make more stuff to put in space

like vaults

**Comment by ComicIronic** [comment]
We're not shrinking space. It was made bigger so we could put more stuff there. Allow me to describe what's going to happen if we shrink it:
1. Everything becomes easier to get to
2. People try and add new stuff to the map
3. The map becomes too full of new stuff and you can't drift anymore
4. Someone makes the map bigger again for space
5. "Space is too big!"

**Comment by Killette2** [comment]
Just make things not line up! :eggplant: 

Also space has never been "too full" in the history of this game, ever

**Comment by SonixApache** [comment]
we could just ditch one of the Z-levels, there really isn't much out there that's worth shit apart from vaults

**Comment by Exxion** [comment]
What, Z-level 6?
That's where the salvage shuttle spawns

**Comment by SonixApache** [comment]
So move it to the other big space Z-level, or the derelict. Or replace the medical ship with it since nobody cares about the medical ship anyway.

**Comment by AlphaBuffalo** [comment]
Well we have some options.
1) Add stuff
2) Shrink space
3) Remove a z-level and move the stuff in others
4) Have different sized z-levels, so the station and roid have the biggest, and all the others are smaller

**Comment by gbasood** [comment]
5) use fucking space pods to travel the distance because jetpack flight through space is dumb and you're dumb

**Comment by Exxion** [comment]
It doesn't even take that long with jetpacks. It's only drifting with no tools that takes forever to get anywhere.

**Comment by clusterfack** [comment]
You cant have different sized zlevels

**Comment by Killette2** [comment]
Well ain't that a kick in the dick? I guess the only solution is to put more stuff in the same z-level and take away ones that aren't being used to store much.

I will say I do like the main station having a large z-level for construction

**Comment by Exxion** [comment]
"Solution" implies there's a problem in the first place

**Comment by Killette2** [comment]
Well there is a problem considering you also only go super slow or super fast in space now.

Think throwing an item or spraying an extinguisher will make you go double the default speed like it used to? Think again

**Comment by SonixApache** [comment]
The problem is that if you get spaced and you don't have a spacepod with a super or hyper cell you're very likely to just be fucked.

**Comment by Killette2** [comment]
If we can't agree to shrink space, surely we can at least go as fast as we used to be able to. It was always good to throw an item to change direction and get a speed boost if you were going the slowest speed.

**Comment by FudgePucker** [comment]
Replacing the white ship with the salvage shuttle would be a bad idea. A very bad idea.

Salvage shuttle is one of the best rewards in space, also one of the rarest.

There are no land marks in the zlevel, if you hit the derelict you know where clownroid and DJ station is. You go to telecom sat you know where the white ship is.

So it would go from, 'search for an empty z level and scour its entirety for the ship' to 'loot for hardsuit gun and hop in teleporter'

It would go from 'best reward in space rairly found in a round and a real fun surprise leading to fun space adventures' to 'SS power game ruse cruse'

Every cultround will have one starting cultist rushing for the ship to have as a base.

**Comment by Killette2** [comment]
What if we put the salvage ship in a completely random non-station z-level, in at least 4-8 potential spots? It could be somewhere around the roid, somewhere in the derelict level, t-comms level, but there will be a very good amount of spots to where checking the spots even would be a very slow way to find it.

Not to mention it's already in a static spot where you can telescience.

**Comment by SonixApache** [comment]
Fudge has a point.

**Comment by FudgePucker** [comment]
@Killette2 Still having a way to find it by using landmarks would be bad, 4-8 potential spots sounds like a lot, but you would know exactly where they are, and the salvage shuttle is worth it, all you gotta do is find a landmark then search the spots, not on that zlevel? Go to the next one and look for a landmark. Also with telescience it is still harder and longer to do, because you have to figure out what zlevel (Telescience zlevels are randomized right?), the drift and shit, and then use a spread sheet. That would take longer than just nabbing a hardsuit and laser gun.

**Comment by Sprok0** [comment]
Would it be possible to convert the salvage shuttle into a vault? I don't actually know anything about mapping

**Comment by gbasood** [comment]
So the complaint here is that getting spaced without an actual tool to travel through space with will just slowly kill you because you probably won't ever hit anything?

Sounds like realistic gameplay

**Comment by SonixApache** [comment]
In various cases it won't kill you, it'll just waste a lot more time.

**Comment by Killette2** [comment]
The telescience drift isn't that big iirc. If you try to teleport yourself in the middle of the shuttle you should always be in eyesight of it.

**Comment by Shadowmech88** [comment]
Last I heard, the drift was within +/-50 tiles on both axes.

**Comment by icantthinkofanameritenow** [comment]
Perhaps a compromise would be a good idea, how about cutting the size down to 350x350 or so until we can put in more stuff in the empty space? It would be smaller, but it would still be larger than it was before the initial transition to 500x500 and leave a fair amount of room for vaults and other stuff.

@ComicIronic
The problem with your hypothetical scenario is that the original influx of new vaults and other contents that was expected after the original expansion is now a fraction of its original self. There simply isn't enough new stuff to justify the current size, and even if every possible vault spawned at once (which seems to be extremely likely thus far), there would still be an unacceptably large amount of extra space left over. 

Hell, you could add an entire second derelict somewhere and have plenty of space to spare.

**Comment by coldcola** [comment]
I agree with fudgepucker on the rarity and importance of keeping the salvage shuttle in a mostly empty z-level to emphasize it, however there is actually one landmark that you could potentially use to find the shuttle(unless it's been removed) and it is typically in the same general area.

that said keep spess big.  if you get spaced and are lucky enough to have internals/harsdsuit, you should have enough time to get your suit sensors on and PDA spam someone into checking the CMC for you.

**Comment by Exxion** [comment]
Two landmarks to find the shuttle, in fact, though one is a spacepod so it's tiny and not always there

**Comment by Killette2** [comment]
3 years and space still has no new vaults 😔 
So much for expanding space to add more things huh?

**Comment by coldcola** [comment]
>probe closing an issue

I mean I knew the serb was dead when ssethtiders got admin but damn, RIP /vg/

**Comment by FudgePucker** [comment]
Three year old issue

**Comment by coldcola** [comment]
so close all issues that are 3+ years old then, there's sure a bunch :)

**Comment by FudgePucker** [comment]
Have you even seen how many pages of open issues there are? 98
