### ISSUE TITLE
ERT doesn't get magboots

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#11884]
How can they respond to emergencies if they can't even respond to zas

**Comment by SysadminJeroen** [comment]
Could also give them a lifetime supply of hardcores.

**Comment by clusterfack** [comment]
Fun fact, hardcores do the OPPOSITE of what they're supposed to because nexis is a moron and reversed their behavior

**Comment by Shadowmech88** [comment]
> hardcores do the OPPOSITE of what they're supposed to

They make you _more_ susceptible to ZAS?

**Comment by ghost** [comment]
uh, they're meant to make you more susceptible.

**Comment by Shadowmech88** [comment]
I thought they were meant to make you less susceptible, but as a trade-off going into crit kills you instantly.

**Comment by Allspice** [comment]
Hardcores do not speed up your death in crit at all.

**Comment by Shadowmech88** [comment]
So it's just the unique death message whenever you do die?

**Comment by NigglyWiggly** [comment]
I thought they used to, didn't they?

**Comment by clusterfack** [comment]
1. They are supposed to give you a unique death message
2. They are supposed to make you get blown by airflow even when airflow pushing is disabled

That's why they're free and available to all engineers.

**Comment by SysadminJeroen** [comment]
@clusterfack I tested Bustanuts a couple weeks ago on a local server and I didn't get ZAS'd when exposing a room to space, however maybe I should try harder.

**Comment by clusterfack** [comment]
I cant facepalm hard enough, yeah because like I fucking said earlier right now they make you NOT get pushed by airflow. Their behavior got flipped by nexis.

**Comment by Exxion** [comment]
Default ZAS settings are wimpy as shit
The live server defaults to Hellish, but local servers don't
They default to basically nothing. You can't really get airflow pushed on a local server by default at all. At least not by just opening a hole to space.

**Comment by SysadminJeroen** [comment]
@clusterfack I have read that about 20 hours ago, however I did not put effort into remembering that YOU said it.

**Comment by Shadowmech88** [comment]
I like Bustanuts as they are right now.
