### ISSUE TITLE
Infinite broken hand dropping

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11895]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/5169310/18537008/38883964-7ad0-11e6-9b30-0d38c87ce07d.png)
#### Difference between expected and actual behavior

Not to get spammed
#### Steps to reproduce
1. picked up a curse/glued item (I spawned a cursed/glued banana peel)
2. break that hand
3. receive tasty spam

**Comment by clusterfack** [comment]
@unid15 more money mo problems
