### ISSUE TITLE
Dizor combat borg can turn invisible

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#11894]
I think it might have something to do with its shielding or mobility module being active.

**Comment by AutismSpider** [comment]
missing icons for having the module active or some thing.

**Comment by Hoshi-chan** [comment]
Yeah, that's what I figured when I saw it happen. The borg used it to turn invisible and effortlessly kill a bunch of cult ghosts, can't imagine how a non-throwaway antag would feel about it.

**Comment by clusterfack** [comment]
Oh the combat borg shield sprite slash mobility sprite? This is a pretty common problem actually, someone ping him about it.

**Comment by Shadowmech88** [comment]
I'm the one who added it, and I SWEAR I fixed both those modules before I merged it, and it was visible then. The entire reason I tested it was because I saw this very same thing happening.
