### ISSUE TITLE
2x attack bug abuse

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11897]
#### Description of issue

You can attack with the same weapon, or a different weapon, TWICE REALLY FAST. Unsure about the later, but do know the same weapon gets 2 uses.
#### Difference between expected and actual behavior

Expected: normal attacking
Happening: you and your borer attack
#### Steps to reproduce
1. get an arm borer
2. get it to be hook shot module
3. give it a weapon of your choice
4. attack with your weapon while your borer is attacking with it
5. you will notice you and your borer sharing your arm have two separate cooldowns for attacking, so you can attack 2x as fast

**Comment by Shadowmech88** [comment]
How close do you and the borer have to sync to do this? The borer code is _supposed_ to check whether the host is in the middle of an attack cooldown before attacking.

**Comment by Killette2** [comment]
I was the shield borer watching the event, but I have no idea. It was pretty close but nowhere near exact. All the other borers inside noticed it too and commented about it in her body, so it wasn't just me seeing this.

**Comment by jknpj** [comment]
I'm pretty sure you also don't consume chems if you are hooking-attacking at melee range

**Comment by Shadowmech88** [comment]
> I'm pretty sure you also don't consume chems if you are hooking-attacking at melee range

That's intentional.

**Comment by jknpj** [comment]
> How close do you and the borer have to sync to do this? 

Just spam

> That's intentional.

Even if it i, that means you can shank a nigga twice as fast without using any chems

**Comment by Shadowmech88** [comment]
> that means you can shank a nigga twice as fast without using any chems

Only due to the aforementioned bug that lets the host and the borer attack at the same time, right? Which _is_ a bug.

**Comment by AutismSpider** [comment]
So fix the bug and be done with it.

make it drain chems for close up hook attacks any way

**Comment by Killette2** [comment]
why? It drains chems because you're extending your flesh. The borer can still control the arm but if the arm is where it needs to be there needs no more exertion

**Comment by Shadowmech88** [comment]
I'm fixing this right now.
Obviously the host and borer shouldn't be able to attack with the same arm at the same time, but what about different arms?

Should I tie the host's and borer's attack delays together completely, or let them attack at the same time if the host uses their other hand to attack?

**Comment by AI-Is-Rogue** [comment]
Let them attack at the same time if using different arms in my opinion.
