### ISSUE TITLE
VV/View variables on objects sometimes causes the client to disconnect and reconnect

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11907]
#### Description of issue

Every round or two, I'll end up with an object that I absolutely cannot VV without it disconnecting me. As in, I'll hit "view variables", get met with a frozen screen, and then I'll have ended up disconnecting/reconnecting to the server without ever seeing the variables.
Other objects of the same type aren't affected, and typically other admins can VV the one I'm having trouble with.
Off the top of my head I recall a RUST Gyrotron control computer, door bolt control button(one of the ones in metaclub dorms), and a taser turret giving me trouble while none of the others of the same type did.
#### Steps to reproduce

I can not find any consistency between what objects cause this to happen, as it just seems to be a different object every round.
I can't recall it happening with turfs or mobs, but I probably haven't VV'd them enough to run into it.
#### Specific information for locating

/client/proc/debug_variables(datum/D in world)
I think that's the one
#### Length of time in which bug has been known to occur

At least since I've been adminned
Possibly since VV's been in existence
#### Server revision

236418dbcbcf06b4d77d4bef3612a7d99f200f01
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
I know exactly what this is.

It's the sending of the icon of the object being VV'd to the client, because it predates base64 icons from goon.

Paradise fixed this, I'll dig the PR up in a sec.

**Comment by clusterfack** [comment]
It's been around forever, we've never figured out why it might occur.

**Comment by clusterfack** [comment]
Or pjb knows and is going to snipe me

**Comment by PJB3005** [comment]
https://github.com/ParadiseSS13/Paradise/pull/5250

**Comment by PJB3005** [comment]
Or no wait wrong one, this is the one: https://github.com/ParadiseSS13/Paradise/pull/5178

**Comment by Intigracy** [comment]
It happens to me sometimes too, I've got no idea why.

**Comment by PsiOmegaDelta** [comment]
Happens occasionally on Bay as well, even for things without icons (datums).
Is very consistent when it happens, and tends to appear, disappear, and move around with compilations.

**Comment by clusterfack** [comment]
Icons can be pretty spooky. Did you know that occasionally when you add overlays as strings it puts the entire dmi into the icon? It was causing a bugbwith bicon before.
