### ISSUE TITLE
Unable to leave unlocked booze storage locker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11905]
(WEB REPORT BY: askaris REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

d5e11d4f8fb61ecf01b55e2103ba73471e7a22c1 

> General description of the issue

Walked into open booze storage locker as assistant, closed door, could not open from inside.

> What you expected to happen

Be able to open the unlocked locker from the inside.

> What actually happened

Locker gave "it won't budge" message when attempting to move out. Directly clicking on the locker would not open it. Had to resist to leave.

> Steps to reproduce if possible

Place self in unlocked booze storage locker without bar access, close door.

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce.
