### ISSUE TITLE
Wizards start with an empty survival box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11902]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d5e11d4f8fb61ecf01b55e2103ba73471e7a22c1
> 
> General description of the issue
> Wizards don't have anything in their survival box, which kinda defeats the purpose of the box.
> 
> What you expected to happen
> Survive getting slammed in the head because I had a bandage
> 
> What actually happened
> Died because lmao nobandage
> 
> Steps to reproduce if possible
> spawn as wizard, note lack of stuffs

**Comment by Killette2** [comment]
This bug is so old I thought it didn't exist anymore
