### ISSUE TITLE
Special (green, blue, red) medical bots revet to standard (white) medkits when destroyed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11901]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d5e11d4f8fb61ecf01b55e2103ba73471e7a22c1
> 
> General description of the issue
> Roboticist turned a green medkit into a green medbot.
> Green medbot was then destroyed.
> Out of the destroyed remains came a white medkit.

**Comment by clusterfack** [comment]
LITERALLY UNPLAYABLE

**Comment by SonixApache** [comment]
Specific medibots inject specific shit, y'know. It's a waste to lose one, really is.

**Comment by Probe1** [comment]
I think I'd rather kill myself than touch anything to do with robo code.

**Comment by ghost** [comment]
brb, killing myself by touching robocode
