### ISSUE TITLE
autolathe shells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11904]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> the autolathe prints spent white shells
> 
> What you expected to happen
> working white shells
> 
> What actually happened

they are already spent

> Steps to reproduce if possible
> print white shell
> look how its already spent

**Comment by Killette2** [comment]
I'm pretty sure one of it's features is the ability to make empty shells. I'm not sure how you were intended to fill them but they've existed a while.

**Comment by SonixApache** [comment]
Yeah, the standard legal 'shotgun shell' is empty. Can't fill it, no idea what it's point is.

**Comment by Kurfursten** [comment]
It's WAD, since you can hack the autolathe for "real" shells, but maybe we should remove the empty shells so people stop being confused.

**Comment by ScrambledSteak** [comment]
white shells still make sound, they're blanks

**Comment by Killette2** [comment]
Did you know in real life if you shoot yourself point blank with a blank, it can kill you? There is no bullet, but the pressure can do lots of damage if it has no escape other than through your body.

**Comment by charmstruck** [comment]
If they actually do function as blanks as Aurantiaco says, they should probably be renamed to reflect that

**Comment by Durgen** [comment]
https://en.wikipedia.org/wiki/Brandon_Lee#Death

**Comment by ComicIronic** [comment]
Brandon Lee died because there was a bullet lodged in the barrel. There are cases of people dying directly from the force of the blank because they put the gun to their temple, not because the blank fired anything.

**Comment by Probe1** [comment]
``` /obj/item/ammo_casing/shotgun/blank ```
