### ISSUE TITLE
Suit sensors are dumb

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#11915]
I mean the execution, not the concept

The name displayed on the CMC for someone with suit sensors on is their actual mob's `name`. This means that, if you aren't wearing an ID and you are wearing a mask or your face is disfigured or something, you'll show up as unknown. This is extremely stupid. Why would your suit sensors get your identity from your face?
Less importantly, suits with sensors enabled but not on mobs vanish from the CMC, which seems dumb.

My proposals:
1. A suit with sensors enabled stores the name of its owner and always reports that name (until it's updated somehow). So burning someone's face off doesn't confuse the CMC and, conversely, you can steal someone's suit and put it on to make it look to the CMC that they're fine. Not sure mechanically how the name should be updated or whether it should use ID or DNA though.
2. A suit taken off its wearer still reports to the CMC for a while before shutting off, saying either no vitals detected or just reporting no damage. (The former would be better for immulsions but the latter may be better for gameplay, which takes priority.)

For added fun, make it so that you can emag a jumpsuit to allow you to set the name it reports.

**Comment by Gef21** [comment]
Also your suit has four different settings and only two of them are ever used ever

**Comment by Killette2** [comment]
The settings are fine, I've used all 4 of them for different scenarios.

**Comment by rweeblington** [comment]
Having a DNA scan similar to pAIs would be good, and if it could automatically trigger on being put on.

**Comment by gbasood** [comment]
Downside of this is that it makes ling play really fucking difficult, because it forces them to change suits when they change faces.
At least the way lings currently plays. And probably will continue to play for eternity

**Comment by Exxion** [comment]
I said you could update it

**Comment by Hoshi-chan** [comment]
@rweeblington Emagging jumpsuits to scramble their DNA scan, causing it to stop automatically updating, while a second emag causes it to start randomly changing identities between people on the crew manifest.

EDIT: Oh wait, Exxion already said that. Shit.

**Comment by ghost** [comment]
The suit sensor should get the name from the ID; you place it on your suit anyway.

**Comment by rweeblington** [comment]
Real good idea constructive feed back on Exxion's idea though @Hoshi-chan 
@DrCelt Sure, but "unknown" when wearing a mask to hide your face makes no sense if it was formerly reporting your name.
