### ISSUE TITLE
Cryo cells are over pressurized, causing 2 brute damage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11914]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> While in the cryo tube, you get the orange too much pressure indicator. This causes you to always have at least 2 brute damage while inside. 
> 
> What you expected to happen
> Heal brute damage and have a nice atmosphere inside tube
> 
> What actually happened
> Never heal to full because lol 2 brute damage
> 
> Steps to reproduce if possible
> Go inside cryo tube
> Observe overpressure
> Or, while outside, observe occupant never healing to full

**Comment by Aurx** [comment]
Cause of issue (on box): Cryo tubes are directly hooked into O2 canister with no pressure control (IE, a pump)
This causes the entire canister to dump into the pipes and thus hyperpressurize the system.

**Comment by Aurx** [comment]
Solution is damn simple: Remap so there's a gas pump between the O2 can and the rest of the pipe system.  E: And make sure the pump is off or not set above 101.3kpa.  
EE: There's a vertically oriented pipe two tiles above the O2 can, replacing that with a north-facing gas pump would solve this with one change.

**Comment by Shadowmech88** [comment]
Didn't used to cause pressure damage.
What changed?

**Comment by PJB3005** [comment]
I made crap make sense and made am occupant of a crap cell be inside the cell's atmosphere, not the turf's.

**Comment by invoid9** [comment]
I came across this issue while on deff, if that matters.

**Comment by Exxion** [comment]
Having fun on mobile, PJB?

**Comment by jknpj** [comment]
if cell is cooled, why is the pressure so high?

**Comment by BestName** [comment]
Because there's still a full tank of oxygen in there.

**Comment by SonixApache** [comment]
Cryo cells now occasionally just continue generating brute that can outright kill a man.
Observed on Defficiency; saw the brute go from 16 to 72 while other damage types dissipated. Not sure if there was bicardine or something that causes brute damage in the mix at the time.

May just be Deff related.

**Comment by Shadowmech88** [comment]
So does this mean that plasmamen combust inside cryo tubes, since they're filled with O2?

**Comment by PJB3005** [comment]
If they do, I don't see how they wouldn't have before.

Before being in a cryo cell used the surrounding atmosphere, so the plasmamen would still catch fire if he's out of his suit in a cryo cell.

**Comment by Exxion** [comment]
No. They have to be breathing to catch fire.

**Comment by Shadowmech88** [comment]
> they have to be breathing to catch fire

So a plasmaman wearing a plastic bag on his head and taking dex+ supplements can go without his hardsuit completely?

**Comment by Exxion** [comment]
Uh
Probably?

**Comment by PJB3005** [comment]
:clap:

**Comment by gbasood** [comment]
Caused by @PJB3005 with https://github.com/d3athrow/vgstation13/pull/11829

**Comment by Intigracy** [comment]
I band-aided this but I'd rather an actual fix be applied.

**Comment by Exxion** [comment]
> Implying that wasn't already the best solution

It makes sense that if cryo is overpressurized, it would hurt you

**Comment by ghost** [comment]
@PJB3005 fix your damn bugs :smirk:

**Comment by PJB3005** [comment]
Working as intended.

**Comment by gbasood** [comment]
Do cryo cells at least provide any notice that they are overpressurized in the interface or examine or anywhere at all?

**Comment by ghost** [comment]
@gbasood No, because it's a bug that PJB said is a feature now

**Comment by PJB3005** [comment]
There is no way to fix it without reworking the 300+ occurrences where `return_air` is handled.

Warning on the cell sounds like a plan though.

**Comment by Exxion** [comment]
>Pressure in cryo cells making sense is a bug

I'll grant it was an oversight, but that's how it always should have worked

**Comment by 9600bauds** [comment]
Was fixed via ugly floor pump
