### ISSUE TITLE
Vox pig(box) still grows in size even while it's dead

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#11916]
#### Description of issue

If a Vox pig dies, it continues to grow in size until it reaches prize porker size.
Every stage of growth updates the icon to be the living state as well, so they look like they're living even
#### Difference between expected and actual behavior

Dead pigs shouldn't grow, much less seemingly spring back to life when they do
#### Steps to reproduce

Grow pigs in O2 rich environment so they suffocate
Watch them still grow as you butcher them
#### Length of time in which bug has been known to occur

Since the pigs existed I guess
#### Server revision

713564a7711ee3d83f7a869ebd7ee786c64abf3a 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by FantasticFwoosh** [comment]
Ive witnessed this firsthand too.

**Comment by Killette2** [comment]
Maybe this is their special trait, they don't stay dead.
