### ISSUE TITLE
Mednanos can't cure virus2

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11911]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
for(var/datum/disease/D in M.viruses)
                        D.spread = "Remissive"
                        D.stage--
                        if(D.stage < 1)
                            D.cure()

'viruses' only contains shit like robotic transformation and magnitis I guess, and I doubt that it was intended for mednanos to ONLY cure those considering how rare they are. But a catbeast infected from a shattered virus tray then given 5u mednanos when their eyes started watering progressed unimpeded through gaben, giggles, and arachno.

**Comment by coldcola** [comment]
is it the `if(D.stage < 1)` that is causing the most basic virus' to be cured? should more evolved virus' be cured by nanos?
