### ISSUE TITLE
FEATURE REQUEST have a way for a signaler to open a door

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11925]
(WEB REPORT BY: blarghargin123 REMOTE: 172.93.109.202:7777)
I was thinking of making a bell that when rang would open a door that has a signaler set to the same frequency. But because you can only lock, and unlock airlocks with a signaler it is impossible. But since it would make hacking 3x easier because you would only need to pulse 1 wire to open the door instead of pulsing 1 wire then crowbar I recommend doing something like swiping your ID on the signaller and if its on the wire to open the door it will use that access requirement to open said door. If someone has a better idea please share

**Comment by ComicIronic** [comment]
Can you really not pulse an open wire on a door?

**Comment by Exxion** [comment]
There is no open wire on regular airlocks. Only the two-tile ones.
Or if there is one I've never gotten it to work at least

**Comment by unid15** [comment]
there is a wire that opens/closes the door when pulsed - it works if the airlock has no access requirements, or if its ID wire is cut

**Comment by ComicIronic** [comment]
Then can someone try and rig up a bell assembly to signal the open wire and see if this actually needs new code?

**Comment by Exxion** [comment]
Right
I probably should have figured that out

So you can do this. You just need to pulse the access wire too.

**Comment by AlphaBuffalo** [comment]
there should be a light that tells you when you pulse the access wire I guess, or just pulse every wire and try to open the door

**Comment by ghost** [comment]
There are some people who know assembly wizardry very well, I've seen someone make voice activated un-bolting and opening airlocks, that lock and bolt themselves after.

**Comment by AlphaBuffalo** [comment]
There is a wire that opens doors, but only when the door has no access requirements. I tried opening a maintenance airlock by pulsing wires and none of them opened the door. What I did was attached a signaler to the wire that opens an airlock with no access requirements, then pulse every wire to see if signalling the signaler would open the door which it did not.

**Comment by Exxion** [comment]
Oh, so it doesn't even work if the access requirements are disabled, as long as the door usually has them?

**Comment by AlphaBuffalo** [comment]
No will open a door without access requirements

**Comment by Killette2** [comment]
Voice activators are far from wizardy unless you use some supreme autism with 40+ signaller parts

**Comment by Manfreedo** [comment]
Well there is this:
![access button](https://cloud.githubusercontent.com/assets/20943168/18606606/f436a962-7cb4-11e6-9a9e-e6b75e6d992a.PNG)
But the only commands for doors I figured out where open and close. I'm still searching for one that changes the doors state.

**Comment by unid15** [comment]
> There is a wire that opens doors, but only when the door has no access requirement

or the ID control wire is cut

**Comment by AlphaBuffalo** [comment]
Next time I play I'll try to find and cut the ID control wire. The only thing I hate about it is that it's harder to find than the test light because there is no ID control light

**Comment by unid15** [comment]
[spoiler]the lights flash when you pulse that wire[/spoiler]

**Comment by AlphaBuffalo** [comment]
Which light?

**Comment by unid15** [comment]
the airlock light duh
the same one that lights up when the door is bolted

**Comment by AlphaBuffalo** [comment]
Oh its the same as the ID control, this is news

**Comment by AlphaBuffalo** [comment]
okay you need to cut the ID wire, then pulse down the list again to find the wire to open the door. I managed to make a signaler open a maintenance door by doing it this way.  But my plan of having a bell open a door wont work because the signaler in the bell wont trigger the one in the door ;_;

**Comment by unid15** [comment]
That's weird, I remember making a bell-triggered door and it worked fairly well

**Comment by AlphaBuffalo** [comment]
idk maybe I did something wrong. but I didnt change the frequency or code on both of the signalers

**Comment by ComicIronic** [comment]
If it can be done, this isn't an issue.
