### ISSUE TITLE
Facehuggers can hug through mechs

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#11920]
#### Description of issue

While mining with a ripley, an unfortunate roboticist uncovered a xeno nest in the asteroid. Upon entering proximity to the nest, an egg opened

'Knochen Heinrich  says, "Dont tell me these things can go through the exo...."'

Said facehugger that left the egg pathed its way towards Knochen's mech, and took his mask off and facehugged him through an airtight mech suit.
#### Difference between expected and actual behavior

> Expected
> Get away from her you bitch
> Actual
> Get away from her you _facehugged_
#### Steps to reproduce

Be mining on asteroid with a RIPLEY
Find xeno nest
Get too close, so one of the eggs opens
Marvel that a hand with a penis inside of it is able to jump through a mech built for travelling through space
#### Server revision

713564a7711ee3d83f7a869ebd7ee786c64abf3a
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Well, facehuggers _can_ easily melt through space suit helmets in the Alien universe...

**Comment by ComicIronic** [comment]
Was the mech set to be airtight or was he breathing through internals?

**Comment by gbasood** [comment]
Shouldn't matter,  I don't even know why they're facegrabbing through ANY container

**Comment by ghost** [comment]
I have honestly never had this happen to me as a miner on the asteroid, hell, the eggs didn't even open when I got near them. It's gotta be something to do with the mechs internals.

**Comment by NigglyWiggly** [comment]
Probably something to do with mechs, like how monsters in lazarus capsules were attacking people from inside the balls if the guy who had them was inside a mech

**Comment by Shadowmech88** [comment]
Mech code is still terrible overall, right?

**Comment by AutismSpider** [comment]
mech code was never good to begin with

**Comment by Killette2** [comment]
The facehuggers crawl through the cracks bro

## working as intended

**Comment by gbasood** [comment]
Might be that `Crossed()` isn't checking if a mob is actually NOT inside a thing and somehow it's still finding the mob

**Comment by Exxion** [comment]
No, because `Crossed()` is a BYOND proc

**Comment by gbasood** [comment]
:V
Facehuggers use Crossed to check for faces to jump on. It might be getting mobs inside mechs from that.
Thanks for the lecture on the code I implemented for facehuggers though

**Comment by gbasood** [comment]
So `followtarget` the proc that has facehuggers walk to targets checks if they're located on a turf before continuing, so pathing isn't the problem
Only other way for them to attach is Crossed()

**Comment by gbasood** [comment]
Jumped in a ripley, burst an egg, walked around the facehugger, and nothing.
Also tried walking around a grown egg, nothing.
Perhaps bussed

**Comment by Exxion** [comment]
> One sentence
> A lecture

`Crossed()` just doesn't work that way unless you specifically made it work that way, which I doubt because you would know if you did

**Comment by gbasood** [comment]
Yes, you were right
Anyways I can't reproduce it so I'll close this for now until it can be reproduced by someone else ¯_(ツ)_/¯

**Comment by ghost** [comment]
Did anyone ask Knochen how it happened to him?

I think his ckey is Herrytheafroheadcrab or something along those lines

**Comment by ihadtoregisterforthis** [comment]
It happened to me before.
Ripley with claw and drill, as plasmaman miner.

**Comment by gbasood** [comment]
@ihadtoregisterforthis okay cool now make it reproducable

**Comment by ihadtoregisterforthis** [comment]
![lmao 2 hug](https://cloud.githubusercontent.com/assets/13305885/19017726/d35fafc4-881a-11e6-9781-77ff84832b2e.png)
![random name](https://cloud.githubusercontent.com/assets/13305885/19017727/d5e146b8-881a-11e6-908c-61bc05a8211b.png)

**Comment by gbasood** [comment]
Steps to reproduce?
I tried the ones in the OP and got no results.

**Comment by ihadtoregisterforthis** [comment]
Open egg by walking near, escape the angered masks, enter mech, go back to boast that they can't hurt you now.
Except they can after some attempts.

**Comment by gbasood** [comment]
I walked circles around one in a mech and couldn't get it to occur
I'll have to test it again I guess?

**Comment by Pathid** [comment]
Seems if the facehugger locks onto you while you're outside the mech, then going inside it won't break the lock.
