### ISSUE TITLE
toxins test site feature request

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11923]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the FEATURE
> toxins test site needs a piece of undestructable wall at the end of it ( on the same y level of the mass driver) 
> because if a bomb blows everything the next bomb mass drived will fly into space

**Comment by ghost** [comment]
Nah, just grab the space suit and head out, put a grill up. Having riveted walls on Z1 is just a bad idea, it's a free meteor shield and stuff. Just know how many bombs you've thrown out and stuff, and use the damn cameras until you blow them up.

**Comment by Shadowmech88** [comment]
> Having riveted walls on Z1 is just a bad idea, it's a free meteor shield and stuff.

It would literally be a single tile. The odds of a meteor even hitting that tile on its way to the station are incredibly slim.

**Comment by icantthinkofanameritenow** [comment]
I think I can change this easily enough. Think about it, as improbable as this sounds there is a stupidly small chance of the bomb looping around  the Z-levels and causing the next bomb test to turn Arrivals into a smoldering hole. 

I mean, it COULD happen in theory.
