### ISSUE TITLE
Automatic payment on item pickup via a display

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#11935]
Basic idea goes like this:
- Items for sale go into a display sort of thing. Vendor sets price per display. Can contain multiple items in one display. Display shows flat icon of item that is next in queue for purchase from that (basically the first item in contents)
- Player who wants to purchase something walks up and clicks on display with empty hand. Item is dispensed to their hand. They are automatically charged the cost of the item to their PDA wallet.
- Player with insufficient funds is notified that they're fucking broke son
- Player with no PDA simply picks it up and sets off an alarm.
- Looking at the display shows the cost of purchase
- Display settings can be modified by whacking it with a PDA, provided you're the owner of the display.

Why this is better than the POS systems we have:
- No individual item tagging hassle. Throw all those waffles in one display and charge 5 space bucks per stack of waffle.
- Extreme ease of purchase means people will be more likely to go through the process of buying your novelty blood-smeared paper. Biggest pro.

**Comment by Kurfursten** [comment]
We should get a tag for "needs spritework"
