### ISSUE TITLE
Pathogenic Incubator Interface Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11934]
(WEB REPORT BY: lavoss REMOTE: 172.93.109.202:7777)
if you do not have a virus dish in the Pathogenic Incubator you cannot use ANY controls, including ejecting chems, turning it on/off, flushing it, etc. which all fuck with the proccess as not being able to flush before inputing a dish could mutate it. Also I believe the code for virologies equipment needs a general cleanup as its all broken to shit in general and the admins always used to say when i'd complain "yeah virology is buggy as shit and needs to be fixed" but no one did.

**Comment by clusterfack** [comment]
Glad someone finally reported it then, stupid fucking admins

**Comment by clusterfack** [comment]
@PJB3005 most likely related to your bugfix

**Comment by PJB3005** [comment]
No, I doubt that. My fix only touched the `process()` code.
