### ISSUE TITLE
Cluwne bans do not work

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#11938]
After testing this on a willing test subject (applied via the ban page before a server reset, he connected in a fresh round after server reset at round start), my test subject remained human and unaffected.

**Comment by AutismSpider** [comment]
Has not work for years its not fully done or half assed

**Comment by 9600bauds** [comment]
I was made codermin JUST to look at this issue and here is what seems to be the problem

Cluwnebans only exist in the ban page
there is no implementation for them anywhere in the code
honk

**Comment by Exxion** [comment]
I don't think codermin status was necessary to find that out

**Comment by 9600bauds** [comment]
Me neither I was actually told I was being cluwnebanned to test it out

In time, this will prove a mistake

**Comment by Shadowmech88** [comment]
How would one even check for whether someone is cluwnebanned in the code?

**Comment by Exxion** [comment]
Depends on how it's set up, but most likely requires involvement on Pomf's end

**Comment by ghost** [comment]
fixed by #27771
