### ISSUE TITLE
Phazon floors don't make you go fast

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11940]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> edc7031057929aca2beb276a08cb404fa78d3641
> 
> General description of the issue
> Phazon floors are supposed to make you go faster, but they do not.
> 
> What you expected to happen
> go fast while walking over them
> 
> What actually happened
> go same speed as always while walking over them

**Comment by PJB3005** [comment]
@unid15

**Comment by icantthinkofanameritenow** [comment]
Are they even supposed to make you move faster?

**Comment by PJB3005** [comment]
Yes

**Comment by CargoTechnician** [comment]
Right now if you have something slowing you down like a space suit or magboots you will move the normal run speed on phazon tiles, so it does something at least

**Comment by icantthinkofanameritenow** [comment]
Must be using oldcode to change speed then. Well, there goes any hope of fixing this.

**Comment by Exxion** [comment]
Not really
The move delayer simply doesn't support negative slowdown
