### ISSUE TITLE
All doors on the vox skipjack are all-access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11948]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a0276aab47fd96958917ffcb01190cfbcf33ca6c 
> 
> General description of the issue
> Anyone can open all doors on the vox skipjacks
> 
> What you expected to happen
> The doors to require syndicate access, the vox already start with agent IDs to provide it
> 
> What actually happened
> Anyone can walk through the skipjack freely
> 
> Steps to reproduce if possible
> TP to skipjack, touch door

**Comment by icantthinkofanameritenow** [comment]
Working on this now. Should I make the shuttle console require the access too in order to deter hijackers?

**Comment by Durgen** [comment]
make them vox access instead of syndicate access

that way traders can embroil themselves in raider schemes
