### ISSUE TITLE
Shield Generators refuse to function when the coverage radius is >70m

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11949]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a0276aab47fd96958917ffcb01190cfbcf33ca6c
> 
> General description of the issue
> Shield generators are cool and all, but they cease function if you set the range to a number over 70.
> 
> What you expected to happen
> Cover the entire station in a shield that drains more energy than a syndicate power sink
> 
> What actually happened
> fucking nothing

**Comment by Shadowmech88** [comment]
Are you sure the generator was getting the power necessary to create such a shield?

I'm not sure how shield generator code works, but maybe they don't create the shield at all if there isn't enough power.

**Comment by jknpj** [comment]
Maybe it's a capacitor Issue? Since it does not drain power from the powernet/apc directly.

**Comment by SonixApache** [comment]
The shield generator draws power exclusevly from shield capacitors, which in turn seem to draw power from being in a powered room. I set up two capacitors next to it at max power; it didn't work. 

When you hit the generate field button when over 70m, it starts up, but nothing happens; power drain doesn't change, field doesn't come up, renwicks don't charge, nothing.

Both capacitors (even though it only connects to one) had 1e.06 or whatever power, the absolute maximum.

**Comment by AutismSpider** [comment]
radius has a cap you can set it higher but you get nothing for doing so.

Shield generators are out dated and need work done to them badly

**Comment by AlphaBuffalo** [comment]
I think it breaks itself somehow
