### ISSUE TITLE
95% sure killer tomatoes have been broken since botany3

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11953]
In botany2, killer tomatoes were a random chance from tomato mutations, it went as follows
33% blue tomato
33% blood tomato
33% killer tomato

Now in botany3, killer tomato is a mutation of blood tomato. However ever since it's release I have yet to get a killer tomato outside of xenobotany means (random seed happens to have killer tomato sprite) and I've never seen them grown by other botanist either. I'm pretty sure that they're broken, as I have no problem with any other mutation except this very specific one.

**Comment by Exxion** [comment]
I'm like 95% sure I _have_ seen them since botany3, but you would be more of an authority on this than I am

**Comment by Killette2** [comment]
Feel free to test server it, I'd love to see it work but I just can't say it does. If you've seen it, it's likely a product of xenobotany using random sprites (however, xenobotany "killer tomatoes" are still able to be turned into the mobs, it's just an unreliable roundabout way to get them rather than the intended way)

**Comment by SonixApache** [comment]
I've seen them multiple times since botany3. Not sure how they were created.

**Comment by Probe1** [comment]
(this was fixed)
