### ISSUE TITLE
Hookshot Visual Bug

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#11957]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/3991927/18686261/ecf7d14c-7f40-11e6-9ddc-b32906a7b758.png)

Only half of the hookshot's chain links are visible.
#### Server revision

87682b58153ff63c7d7727010aa96218c8c960cb
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
@DeityLink fix this your code is UNREADABLE

**Comment by Shadowmech88** [comment]
Might have to ping him on his new username.

**Comment by Intigracy** [comment]
@JMWTurner

**Comment by DeityLink** [comment]
> Implying both accounts aren't tied to the same address

**Comment by JMWTurner** [comment]
@clusterfack I take offense to that, I put a metric fucktons of comments in both hookshot.dm files.

**Comment by JMWTurner** [comment]
@DrCelt CELLLLLTTTTTT https://github.com/d3athrow/vgstation13/commit/778f64fcb19aa9845fa123de92002a95acaf7ba6#diff-6dd350ccd31e0a22d901ebff45961f7cR328

FOR WHAT PURPOSE

**Comment by clusterfack** [comment]
You put 30 comments in a ~500 line file, most of which just said 'this proc does this'

**Comment by JMWTurner** [comment]
Then how is it unreadable?

**Comment by clusterfack** [comment]
Because the comments don't explain shit
