### ISSUE TITLE
Deconstructing/Recyling plasteel crates bug

### ISSUE THREAD

**Issue by CargoTechnician** [d3athrow/vgstation13#11958]
#### Description of issue

Plasteel crates turn into 2 metal sheets when deconstructed or recycled , probably because they are a subtype of closet. 
#### Difference between expected and actual behavior

Crates cost 10 plasteel to make so you expect to get 10 plasteel sheets back, or 10 iron and 10 plasma in the furnace. Also crates don't go into the recycling furnace if they are closed.

**Comment by SonixApache** [comment]
Why in god's name are crates made out of plasteel anyway?

**Comment by AutismSpider** [comment]
old cargo shit crates gave points etc

**Comment by charmstruck** [comment]
I made this report for plastic crates, I guess plasteel crates weren't fixed alongside them

https://github.com/d3athrow/vgstation13/issues/11041

**Comment by pedr69** [comment]
plasteel crates dont seem to exist anymore

**Comment by Securitymain** [comment]
Fixed in https://github.com/vgstation-coders/vgstation13/pull/13619
@Kurfursten this can be closed
