### ISSUE TITLE
Can't emag exofabs (to gain access)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11967]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 777a7453ab5486dfce43b02b3f9b3dd25b881973
> 
> General description of the issue
> Nothing happens when you emag an exofab.
> 
> What you expected to happen
> Emag exofab, get access
> 
> What actually happened
> slap emag onto exofab, no effect, UNAUTHORISED ACCESS DETECTED

**Comment by ComicIronic** [comment]
Huh, weird.

**Comment by Manfreedo** [comment]
Duplicate of https://github.com/d3athrow/vgstation13/issues/9054
