### ISSUE TITLE
You can do a lot of broken stuff with the subspace tunneler

### ISSUE THREAD

**Issue by Gutlesscoward** [d3athrow/vgstation13#11961]
Item in question:
 vgstation13/code/modules/projectiles/guns/projectile/constructable/subspacetunneler.dm

The subspace tunneler, for the uninitiated, is a makeshift gun that, when loaded with bluespace crystals and a super matter bin, can grab and store any item that can be held in the hand, as well as almost any machine if given a natural bluespace crystal. It can also teleport these stored items to any space in that the user can see. The ability to take nearly anything from the station, stuff it in an item that can be held in your hand, and teleport it anywhere you can see naturally leads to a lot of opportunities to break parts of the game. Here are a few examples of the stuff you can do with the tunneler:

1.you can take any item you see/teleport items to any space you see, even through walls or surveillance cameras. 
This bug was talked about briefly in https://github.com/d3athrow/vgstation13/issues/11836, but ultimately the decision was made to just not allow the tunneler to warp people to centcomm, which was one way to abuse this. However, with this item, people can still: 
-teleport bombs anywhere on the station, including restricted areas! (admittedly, telesci can do this too via shoving a bluespace crystal in their teleporter, but they have to figure out the co-ordinates. with the gun, all you gotta do is click)
-steal anything from anywhere without leaving a trace!
-with clever use a teleporter beacon and hand tele, be able to warp anywhere in camera vision!
-circumvent dangerous z-levels that have valuable rewards by making a camera with x-ray vision that can see the loot room/looking at the loot room yourself with x-ray vision, teleporting a beacon into the room, and hand tele-ing yourself to the loot room via the beacon!
1. Outside of a small banned item list, you can really teleport ANYTHING, including some items that aren't meant to move.
   a good example of this is the SMES. the SMES is not suppposed to move once it's made, it's supposed to be deconstructed and reconstructed to where it needs to be. this means that moving a smes from one powergrid to another one and trying to hook it up does nothing, as there wasn't anything programmed for that possibility. Other examples are parts of multi-tile machines, like the gateway, or the teg, or parts of the AME. I haven't tested it on space pods, but it probably does the same to them too. Another example would be the nuke disk; while it's a banned item, you can circumvent that by putting it in a container, like a locker, cheese wheel, or cake. backpacks don't seem to work, though.Lastly, you can store/teleport lockers, which can hold people in them. this last one is mostly notable because of...
2. The Subspace Tunneler can be destroyed via the destructive analyzer, destroying any items inside of it.
   To its credit, it seems that the tunneler is supposed to eject any items inside of it upon destruction, as it gives a message about how the items inside it are forcibly ejected as they're destroyed, but unfortunately no actual ejection takes place. While I have yet to be on the receiving end of this, I assume that for living things it's like being cremated; your body doesn't exist anymore in the game world, you're done, round over for you. With this you can also destroy the gateway (no away missions for you, station!) and the nuke disk(I'm not sure if it comes back).

Honestly, it may be better to just scrap the item than to fix all the bugs it causes and could, in the future, cause. it's a very obscure item, not many people use it, and there's not much use for it, other than to griff, steal items, and abuse bugs. 

PS: Some of the more broken parts (stealing lockers with people in them, stealing machines) require the use of a rare natural bluespace crystal, which can only be found through abandoned mining crates or bluespace slimes.  This makes the broken situations rarer, but whether or not they're rare enough to justify the tunneler's continued existance or broken effects is up to you.

PPS: Sorry if this issue submission is informal or doesn't follow the guidelines for submitting an issue; I've been meaning to type this up for a while, but school's been getting in the way, and I wanted to get this done sooner rather than never.

**Comment by Gutlesscoward** [comment]
I don't know why, but my list of reasons is being shown as '1. 1. 2.' and not '1. 2. 3.' like I typed. Weird.

**Comment by clusterfack** [comment]
Markdown is fucking shit at numbered lists primarily

**Comment by Kurfursten** [comment]
Easiest way to deal with machinery would be to disallow it to pick up anything without WRENCHMOVE, which I think is reasonable

**Comment by PJB3005** [comment]
Wew. I fixed the cent comm bug and kept camera teleports because it's !!FUN!!  if it occurred to me that it's basically a better version of telescience I would've fixed that too.

**Comment by Gutlesscoward** [comment]
I'm not criticizing you over your decision, PJB; I thought camera teleports were fun too. I just wanted to mention that the glitch had already been acknowledged in a different issue.

**Comment by Shadowmech88** [comment]
The first issue was deemed a feature, the objects mentioned in the second issue are in the exclusion list, and I have tested and verified that storing the nuke disk inside an item does not allow you to capture it.
The third issue is a bug and will be fixed momentarily.
