### ISSUE TITLE
Biogenerator gift wrap bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#11963]
Gift wrap is one of the things you can buy in a biogenerator, it cost 300 points
I bought one thinking it was a whole roll, but it was only one paper, which is not enough to even wrap a person. This is dumb.

**Comment by Kurfursten** [comment]
You can wrap a small item with 1 sheet right?

Anyway balance not bug, although I don't think anyone would object to a price tweak and a button to produce multiple, like with paper

**Comment by CargoTechnician** [comment]
So something like 20 points for a sheet of gift wrap and 25 for a sheet of package wrap, which also has the same problem?
