### ISSUE TITLE
Borer powers and roundstart job powers can activate defect blocks

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#11969]
So your borer activates x-ray, or telescopic vision, and suddenly you're retarded. Or you spawn as a detective and you don't just have the sober gene, you also irradiate everyone around you.

It's p. fucked up, and clearly not functioning as intended.

**Comment by SonixApache** [comment]
The former is, the latter is a FEATURE as far as I know.

**Comment by ghost** [comment]
Former is weird genetics code, where it assumes that modifying a block is cue to start activating any deactivated blocks. It's why you shouldn't depend on ryetalyn so much, and instead get a cleaned SE from genetics, assuming they know how to do their job.

Latter is just how the random generoll works. If your job/species has a releated genetic ability/disability, you're more likely to get hit with an additional genetic ability/disability

I've seen chameleon detectives and hulk greys roundstart, it's pretty fun and terrifying

**Comment by aceedex** [comment]
This also applies to getting project mind from viruses

**Comment by Intigracy** [comment]
It's because it's changing your SE to activate the block, so if you already have some "repressed" blocks (like if you take rytealin as clown to remove clumsy it's now repressed, or spawn in with a repressed one) it unrepresses them.

**Comment by Probe1** [comment]
Borers and Genetics Farsight playing nasty with each other is sort of a bug / oversight but what you're referring to is how genetics works.
