### ISSUE TITLE
Cant eat cuffs with hungry

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11962]
(WEB REPORT BY: anacondawarriorsupercommando REMOTE: 172.93.109.202:7777)

> Revision d050837ad869e98ff46c4ac4b4cb1a4dc75db936
> 
> General description of the issue
> I am unable to eat my handcuffs with the hungry genetics power
> 
> What you expected to happen
> You have always been able to eat your handcuffs with this power
> 
> What actually happened
> Clicking on the handcuffs with hungry does nothing
> 
> Steps to reproduce if possible
> Handcuff yourself
> Try to eat the cuffs with the hungry power

**Comment by clusterfack** [comment]
Maybe a result of the range change?
