### ISSUE TITLE
restocking vendors premium items

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11968]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you try restock a vendor with no more premium items and a coin inside it wont refill the premium items

**Comment by Shadowmech88** [comment]
I'm not actually sure if restocking is _supposed_ to refill the premium items.

**Comment by ComicIronic** [comment]
Check if it does it without the coin there.
