### ISSUE TITLE
ZAS Through Portals

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#11971]
How laggy/difficult to implement would this be?

For example, if you made a portal to space, things would get sucked into the portal and the air would drain out of the room.

**Comment by clusterfack** [comment]
I want to say not as hard as you'd think, but making it not buggy and fucked up would be the difficult part.

AFAIK you'd just make a connection edge (the datum structure that connects two zas zones) between the zone of portal A and the zone of portal B.

**Comment by Shadowmech88** [comment]
What determines the direction of airflow in ZAS, as far as pushing objects goes?

**Comment by Intigracy** [comment]
high to low

**Comment by CptWad** [comment]
good lord. just put a telebeacon in space and suck people out of rooms

**Comment by clusterfack** [comment]
I'm fairly sure the location of the connection edge determines the direction of the airflow. Which is why when you make a space tile in the middle of the room everyone is pushed towards it.

**Comment by SkowronX** [comment]
Imagine all the salt from the hand tele opening a portal into space.

**Comment by Exxion** [comment]
This would be possibly the only way to make the holodeck burn sim actually worthwhile

**Comment by Intigracy** [comment]
`>saying the holodeck burn sim isn't worthwhile`

it's really really strong if you set up with it beforehand via welding firelocks open

**Comment by Exxion** [comment]
Even after the bug that caused its ZAS zone's volume to expand without bound was fixed?

**Comment by Intigracy** [comment]
Haven't used it in a while to know for absolute sure.

**Comment by coldcola** [comment]
this idea both scares and excites me.  would be interesting to actually have head roles securing the hand tele due to it's potential devastating effects.
