### ISSUE TITLE
Ragin Mages doesn't draft dead wizards or apprentices.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11986]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 903de6d9a6a3311150c7a606ec3459fd0afd9177 

During a round of ragin there were about 5 dead wizbongers+apprentices in deadchat. The wiz drafter failed due to no candidates 5 times then the round ended.

**Comment by ComicIronic** [comment]
Isn't this deliberate?  You'd be able to loop forever and not care about dying otherwise.

**Comment by Allspice** [comment]
Ragin drafter has a hard limit of about 2-6 wizards before the crew wins.

**Comment by Hoshi-chan** [comment]
Yes, but it's not drafting people who were previously wizards or apprentices, and sometimes those are the only people with their prefs on.

It's worsened by the bug that prevents you from saving your special role preferences mid-round that shows up sometimes.

**Comment by Megamaw** [comment]
i think this is because we tried to fix the whole 'getting selected to be a new wizard while scrying' bug.

just my two bits, though.

**Comment by Kurfursten** [comment]
Datums make this irrelevant
