### ISSUE TITLE
Lobby music continues to play after exiting lobby

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11981]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 193878aed19bce1a22c40af32d99efc883ecef39 
> 
> General description of the issue
> See the name of the issue.
> 
> What you expected to happen
> Lobby music stops after selecting "Observe" or picking a job
> 
> What actually happened
> It keeps going
> 
> Steps to reproduce if possible
> Leave the lobby.

**Comment by clusterfack** [comment]
Ah yeah, that was me. I standardized the lobby channel from its magic number form to prevent this kind of thing happening, but didn't catch all the places it was used.
