### ISSUE TITLE
Can't toggle parallax in-game anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11983]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 193878aed19bce1a22c40af32d99efc883ecef39 
> 
> General description of the issue
> Can't toggle parallax in-game anymore
> 
> What you expected to happen
> Be able to switch parallax on and off while playing
> 
> What actually happened
> Changing it in the new menu and saving doesn't update like the old verb did
> 
> Steps to reproduce if possible
> Go to the new settings menu, set parallax off or on, save setting, no change to current game

**Comment by Sprok0** [comment]
Reconnecting after saving the new setting works to change parallax, but it'd be nice if it updated immediately like the verb did
