### ISSUE TITLE
Borer extendo arm still works when dead or in crit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11984]
(WEB REPORT BY: gigiekk REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 903de6d9a6a3311150c7a606ec3459fd0afd9177 
> 
> General description of the issue
> Borer extendo arm spam still works while host is dead or in crit
> 
> What you expected to happen
> Someone with nn arm borer to not be able to pogo around the station while dead
> 
> What actually happened
> They pogo'd around the station while dead
> 
> Steps to reproduce if possible
> Get arm borer
> It evolves extendo arm
> Die
> Pogo around the station while dead with your amazing new arm borer

**Comment by Shadowmech88** [comment]
Feature.

If someone wants to catch your corpse, they can tase your dead body or inject it with silicate/salt.

**Comment by coldcola** [comment]
I also have seen a method of blocking in the corpse with security/engineering tape etc.

**Comment by Probe1** [comment]
You are in crit, not your borer.  I don't like arm hookshots but that is how it is.
