### ISSUE TITLE
Box noises

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11991]
(WEB REPORT BY: pinkacolada REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I have this cute pig thing and it's not making cute pig snort noises
> 
> What you expected to happen
> Pig noises
> 
> What actually happened
> just cute pig box things
> 
> Steps to reproduce if possible
> Get a box, and hoist. Maybe pet it a bit

**Comment by ghost** [comment]
> Mob ambient noises

Could be fun
