### ISSUE TITLE
Metaclub derelict MoMMI spawner

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#11997]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> It spawns MoMMIs that aren't Z-level locked. Had a few instances of MoMMIs coming in via the derelict teleporter to the station
> 
> What you expected to happen
> MoMMIs to be blocked from entering the teleporter
> 
> What actually happened
> This shit

**Comment by ihadtoregisterforthis** [comment]
#11813
