### ISSUE TITLE
Botanist can't open Hydroponics doors on Box

### ISSUE THREAD

**Issue by BarneyGumball** [d3athrow/vgstation13#11998]
I only tested this on my local copy, but when I started the round as a Botanist I couldn't open the front Hydroponics doors on Box.

When I edited my ID to include every access type the doors accept, they would open.

**Comment by gbasood** [comment]
that has
literally never happened at any other time

**Comment by PJB3005** [comment]
Something related to private servers defaulting to minimal access maybe?
