### ISSUE TITLE
Manifested ghosts can be debrained, then placed into an MMI or a permanent human body

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#11992]
I couldn't believe it when I started getting the, "SOMEONE IS TRYING TO CLONE YOU OR PUT YOU INTO AN MMI" message as a ghost.

**Comment by ghost** [comment]
Manifested ghosts are supposed to ash on death, not sure what got changed

**Comment by Hoshi-chan** [comment]
I put on a security officer's uniform so I'd have pockets and space for an ID, if that matters.

**Comment by ghost** [comment]
Well, I was in regular cult armour, and got decapitated twice and morgued once. Something was up

**Comment by Allspice** [comment]
I've only ever known ghosts to ash when the manifestor moves off the rune.

**Comment by clusterfack** [comment]
How did you get decapitated as a manifested ghost ???

**Comment by Hoshi-chan** [comment]
I didn't. They took my body and performed surgery on it.

**Comment by ghost** [comment]
You can decapitate any carbon human mob if you chop at the head long enough
