### ISSUE TITLE
Turrets can shoot you while you are in a vent.

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#11995]
I was an alien, crawled into the AI core to say hi, got hit with some lasers, crawled back into the vent to leave, and got lasered to death while inside it.

**Comment by Shadowmech88** [comment]
It should be noted that this is specifically while inside an atmos device like a vent or scrubber, the turrets do not attempt to target you if you're inside a pipe.

**Comment by DamianX** [comment]
Is it because vents and scrubbers are visible? Would it shoot if you were inside a pipe and the floor tile was crowbar'd?

**Comment by Shadowmech88** [comment]
You are correct, removing the floor tile with a crowbar and exposing the pipe causes the turrets to shoot at you while inside that section of pipe.

**Comment by nervere** [comment]
Tried reproducing this, doesn't seem to be an issue anymore.
