### ISSUE TITLE
Give Vampire Vision a Toggle

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12000]
Mainly the vampire night vision. Since you can't turn it off, you have no way to see where the darkness is, so you can't make sure other people can't see you.

**Comment by uazuaz** [comment]
what if the dark area was shown as black and white when using night vision?
this could be applied on all tools that let you see in the dark, like meson scanners: colored for lighted zones, black and white for dark zones.

**Comment by PJB3005** [comment]
@uazuaz not sure if that's even doable in BYOND.

**Comment by ComicIronic** [comment]
Not until we implement custom darkness, really, no. It could be done with some nasty processing, but you wouldn't want to.

**Comment by clusterfack** [comment]
I was thinking a plane master on the lighting plane could do it.

**Comment by robintime** [comment]
#13561
