### ISSUE TITLE
Can't examine person holding a hecate

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12005]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 6141d3384cb484a04884512410d9c1b82b1dad83 
> 
> General description of the issue
> Trying to examine someone holding a hecate rifle doesn't work
> 
> What you expected to happen
> Examining to work
> 
> What actually happened
> Nothing happens
> 
> Steps to reproduce if possible
> Put a hecate in someone's hands, try to examine them

**Comment by Exxion** [comment]
It's the accented e in the name (or desc, either way) breaking Goonchat again
@PJB3005

**Comment by Intigracy** [comment]
but it used to work

;_;

**Comment by clusterfack** [comment]
@PJB3005

**Comment by Exxion** [comment]
I'm almost certain this was fixed
Reopen if not

**Comment by DamianX** [comment]
I think it shows up as garbage now

**Comment by Exxion** [comment]
Shows up as garbage in right click and the name bar at the bottom, but should be correct in the chat output
Which is what this was about

**Comment by PJB3005** [comment]
Reminder to blame BYOND forever.
