### ISSUE TITLE
Medical nanobots fully heal a point-blank shotgun blast in one tick, internal and all.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12003]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision 6141d3384cb484a04884512410d9c1b82b1dad83

Ninety brute. It also lets you stand in front of an emitter beam without falling over. Bit much.

**Comment by SGuivenne** [comment]
I'm about 80% sure medical nanites have since been nerfed.

**Comment by Eneocho** [comment]
they got nerfed since, it takes a good while to heal a point blank slug or buckshot
