### ISSUE TITLE
The evidence bag is too big for the evidence bag box.

### ISSUE THREAD

**Issue by CyberTropic** [d3athrow/vgstation13#12001]
Can't put evidence bag taken from the evidence bag box back into the evidence bag box because the evidence bag is too big for the evidence bag box, even though that's where the evidence bag originally came from.

**Comment by JustSumBody** [comment]
I'm pretty sure it takes on the size of whatever you have in it, so if you put a normal sized item the bag itself becomes normal sized and no longer fits.
It changes back if you take the item out.
