### ISSUE TITLE
Always random body doesn't seem to work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12014]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Setting always random body option to yes in character settings doesn't seem to do anything anymore. Entering the round, it gives you the body that shows up in character prefs, and in the following round, the option is always set to no again.
> 
> What you expected to happen
> To enter a round with a completely random body different to the one showing in the menu, and for the option to stay set to yes between rounds unles toggled again 
> 
> What actually happened
> No random body, option resets to 'no' between rounds
> 
> Steps to reproduce if possible
> Set Always Random Body to YES and watch your character not be random as hell

(I might be doing something comepletely wrong here)

**Comment by PJB3005** [comment]
@Clusterfack?

**Comment by invoid9** [comment]
Didn't work before his changes, I think. Someone else in OOC also mentioned it had been broken for months

**Comment by clusterfack** [comment]
As far as I can see, it's never worked. Ririchiyo added a variable and a toggle for it, and no behavior was ever implemented for it. You couldn't even toggle it until I added that functionality, though at the time I wasn't aware that there was no behavior in create body to handle it anyway.
