### ISSUE TITLE
WATER FLOWERS REPLACE WHATEVER CHEMICAL THEY SPRAY WITH "WATER" IN THE LOGS

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#12019]
ITS LOOSE
in the logs, if you say spray lube with the clownflower it says said clown was spraying water and not lube, which is horrible

**Comment by Intigracy** [comment]
are you sure it even logs?

**Comment by CptWad** [comment]
It logs when certain chemicals are sprayed (acids and lube

**Comment by BarneyGumball** [comment]
Are you sure you weren't reading the message it sends to chat when you spray someone?  Water flowers don't have any logging code.

In fact, the only thing that checks `logged_sprayed_reagents` is the spray bottle, so stuff like fire extinguishers aren't logged either.
