### ISSUE TITLE
Upgraded Janicart balance?

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#12017]
The janicart can be upgraded by using an easily obtained Janicart Upgrade Module. The upgrade allows you to clean anything just by running over it.

This is incredible. But is it too incredible? It makes the mop useless, and invalidates most uses for the space cleaner.

I don't think that upgrading a janicart shouldn't be a decision of weighing pros against cons, so I'm not going to ask 'oh, just nerf the upgraded cart's speed'.

Instead, I propose a solution that solves another problem. The mopping mechanism of the upgraded janicart will require maintenance, and stop working after some time, requiring you to tune it up-- since fixing things is in the janitor's job description.

Now, when you, the chemist, are asked for lube, you already know there's currently only one use for lube, and that's for being a shithead. On our wiki, it says, however, "Space Lube is a high performance lubricant intended for maintenance of extremely complex mechanical equipment."

Requiring tune-ups on the upgraded janicart with space lube gives lube a niche other than being a dick, and it gives the upgraded janicart a niche other than 'better than everything'.

Thoughts?

**Comment by Exxion** [comment]
The mop is useless even without the upgrade
Because of soap

Maybe make the upgraded janicart require space cleaner to clean. It already has reagent storage anyway.

**Comment by Shadowmech88** [comment]
People who clean using the mop do so because they enjoy it for what it is, not because it's the most efficient option.

I don't see why we have to nerf the janicart.

**Comment by Exxion** [comment]
It _does_ kind of fuck with the cult's spread blood objective

**Comment by Megamaw** [comment]
I like my proposed idea because it also establishes a secondary niche for Space Lube, giving chemists another decision to make. A use that falls in line with what space lube is intended for, in lore.

Soap isn't better than the mop. You can't clean people with soap. Furthermore, you can't add reagents to soap. There's more, but my memory's a little foggy. It's better in some regards, yes, but the mop still has uses.

Making the upgrade require space cleaner is missing the whole point of the suggestion. It's not a brainless nerf. It's something I think would create more interesting interactions. As a janitor, you were already asking for space cleaner. That's fucking boring.

@Shadowmech88 I'm not doing this simply to 'nerf the janicart'. As someone who almost exclusively plays janitor, I think this would be an exciting change that adds more depth to the job.

**Comment by Shadowmech88** [comment]
I don't exactly see how "splash some lube on the janicart every once in a while" would be exciting.

**Comment by Megamaw** [comment]
i feel like you're missing the point. the point is you'd have to ASK for lube.

but more importantly, lube would have a use other than just straight up griffing, which means people can actually ask for it.

but it requires thought from the chemist, who has to decide whether or not you seem like the type to lube hallways.

furthermore, it's one more maintenance thing to keep yourself occupied as janitor.

**Comment by Shadowmech88** [comment]
Is asking the chemist for lube exciting?

**Comment by Megamaw** [comment]
it doesn't have to be 'exciting' and grandiose like vaults and shit to be interesting and add onto the experience.

does it get the blood pumping? no, but it's interesting.

**Comment by Shadowmech88** [comment]
I'm only asking because you yourself said that it would be an exciting change.

**Comment by rweeblington** [comment]
On this note, I think more uses for space lube would be good.
The janicart (often) and clowncart (relatively often) needing would be good.
Robots (rarely) and mechs (relatively often) needing it would be good.
All-In One Grinders and anything that makes that noise (relatively often) too.

Greyshits stealing the botanist's lube would be more interesting than them just getting it from medbay or science.

**Comment by Shadowmech88** [comment]
Someone in the past has suggested using it to lube machinery like the protolathe, to cut down on manufacturing times.

**Comment by SonixApache** [comment]
Janicart upgrade is fine when you compare it to janiborgs.
Alternatively we could just cut the entire thing and port the janicart from other codebases (literally just a cart thatn holds a mop, bucket and garbage bag)

**Comment by Hoshi-chan** [comment]
No. We don't need balance changes to shit that's been fine forever and that nobody complains about.

Fix one of the thousand open issues or add new content instead.

**Comment by Megamaw** [comment]
see, i tried suggesting 'maybe the lube makes the cart faster' a few months back, but literally no one responded to that issue. the fact we're having any sort of dialogue about this is nice, in my eyes.

i'm making the nerf as light as possible, but trying to nudge people into asking for lube.

also, i VERY RARELY see other janitors upgrading their cart. this isn't an "oh the cart just stops moving" deal, this is a "oh, better go tune up my janicart because I can't just clean everything i run over until I do".

Do I think the current way of doing things is broken? While I feel a little guilty rushing RnD roundstart and asking for an upgrade, no, I don't think it's overpowered as it is.

**Comment by Megamaw** [comment]
i guess what i'm saying is this'd lead to more interesting crew interactions? yeah, i would prefer it giving the cart a speed boost like i initially suggested, but no one seemed super interested in anything like that, so I went in the other direction, and whaddya know, people are talking about it.

people that don't even play janitor.

**Comment by Shadowmech88** [comment]
Frankly, I don't think anyone else cares enough to bother changing how the janicart works.
You might have to code it yourself.

**Comment by Exxion** [comment]
Jokes aside, I don't really like that sentiment

But that doesn't make it untrue
