### ISSUE TITLE
Janicart speed issue?

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#12016]
Ever since skeletons came back, I've switched back to one.

Since then, I've noticed that plenty of humans are running WAY faster than my cart, at normal speed.

I believe species speed is affecting the speed of the janicart, which shouldn't be happening-- a vehicle should be able to go the same speed it usually does, regardless of the driver.

I believe this is a bug. I don't know how the speed on the Janicart works, but it seems like it's a modifier rather than a flat speed. Which is kind of weird.

**Comment by SonixApache** [comment]
Could not reproduce.

**Comment by SkowronX** [comment]
Could not reproduce he says. Were you not around when janicart went sanic fast?

**Comment by SonixApache** [comment]
Tested on local server, cart goes same speed regardless of what species is operating it. Seems to go faster than running as a human.

**Comment by Megamaw** [comment]
That's fuckin' weird. I find myself incredibly outsped and outchased by running humans. I play as a skeleton. I usually wear a biosuit, which is another movement modifier. As a skeleton, it's hard to find raw meat, so I also am usually famished.

None of these things affect movement on the janicart? That sucks, must be clientside wonkiness.

**Comment by Aurx** [comment]
Movement speeds are guidelines at best.  A great way to see the fuckery that occurs is to watch the roundstart borgs heading to robotics on box: It's common that both will hit the escape hallway at roughly the same time, and also common that one will move noticeably faster down that straightaway despite neither borg doing anything but holding right.

**Comment by clusterfack** [comment]
I think it's because byond has such a shit default movement system. The way it works is your computer tries to ping every tick to resend the move command. If your computer fucks up due to a slowdown or lag or the command is lost somehow, your movement gets fucked a little bit.

That's why I want to implement a moveloop which primarily just recognizes key up/down to start/stop movement. I had already done the work for that and it works in pixel movement, but it was bugged in tile based movement so I dropped it for the time being.

**Comment by SonixApache** [comment]
420 closeit

**Comment by NigglyWiggly** [comment]
> As a skeleton, it's hard to find raw meat, so I also am usually famished.

Wait what
Do skeletons still need to eat but can only eat raw meat or something?

Is this a joke?

**Comment by Exxion** [comment]
Yes

Not any more so than skeletons as a whole

**Comment by NigglyWiggly** [comment]
For what reason

**Comment by Exxion** [comment]
Memes
Just like basically every other property of the skelememes
