### ISSUE TITLE
Research shuttle on box refuses to go home.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12023]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0e07cd0217834583181458ec75010de45fe43077
> 
> General description of the issue
> Once the shuttle hits the research outpost it won't come back.
> 
> What you expected to happen
> Hit button, go back to main station.
> 
> What actually happened
> Hit button, 'Shuttle has arrived', still on outpost.

**Comment by CptWad** [comment]
further information: It appears that when moving FROM that port makes you unable to return to said port, you can move to never before seen ports without worry.

**Comment by Kammerjunk** [comment]
When trying to return, the message you get is this:
`ADMINWARN: ADMIN LOG: WARNING: mining shuttle (/datum/shuttle/mining) attempted to destroy the start area (/area/start). If you want mining shuttle to be able to move freely and destroy areas, change its "destroy_everything" variable to 1.`
Names and types replaced with the appropriate shuttles, of course.

It can be fixed for the time being by setting the shuttles to destroy_everything = 1

**Comment by unid15** [comment]
Oh lord almighty I know who and what caused this
fixing now
