### ISSUE TITLE
Bluespace Rift Not Working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12022]
(WEB REPORT BY: chucklemonger REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0e07cd0217834583181458ec75010de45fe4307
> 
> General description of the issue
> The Bluespace Rift is present and can be examined, but there is no way to pass through it.
> 
> What you expected to happen
> To be taken through the rift upon arriving at or interacting with it.
> 
> What actually happened
> Nothing
> 
> Steps to reproduce if possible
> Trigger the Supermatter Crystal event and attempt to enter the Rift.

**Comment by PJB3005** [comment]
Which map.

**Comment by Durgen** [comment]
I saw this bug a week or two ago
not sure which map

**Comment by ghost** [comment]
Box station, Defficiency
