### ISSUE TITLE
Blind Wizard spell doesn't work on borgs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12028]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0e07cd0217834583181458ec75010de45fe43077
> 
> General description of the issue
> 'Blind' wizard spell doesn't do shit to borgs.
> 
> What you expected to happen
> Blind that faggot borg trying to tase me.
> 
> What actually happened
> Fucking nothing.

**Comment by AutismSpider** [comment]
it did before did some one touch it?

**Comment by Shadowmech88** [comment]
Tested locally, I was able to blind a cyborg just fine.
