### ISSUE TITLE
Cyber horrors on gooncode satellite don't shut up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12024]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0e07cd0217834583181458ec75010de45fe43077 
> 
> General description of the issue
> (Follow)  cyber horror  emits, "GHAA!@@#" 

(Follow)  cyber horror  groans, "H@!#$$P M@!$#" 

(Follow)  grey cyber horror  groans, "H@!#$$P M@!$#" 

(Follow)  vox cyber horror  groans, "KR@!!N" 

(Follow)  cyber horror  emits, "GHAA!@@#" 

(Follow)  cyber horror  emits, "GHAA!@@#" 

(Follow)  grey cyber horror  groans, "KR@!!N" 

(Follow)  grey cyber horror  groans, "K!@@##L!@@ %!@#E" 

(Follow)  cyber horror  emits, "K!@@##L!@@ %!@#E" 

> What you expected to happen
> NOT THAT
> 
> What actually happened
> THAT
> 
> Steps to reproduce if possible
> Observe on box

**Comment by CptWad** [comment]
already have a fix
