### ISSUE TITLE
Dwarfism Prevents Hulking Out

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12036]
Intended, but I think it should be changed.

The hulk mutation doesn't make you larger, it just makes you stronger. There's no reason you can't be tiny _and_ muscular.

What does everyone else think?

**Comment by clusterfack** [comment]
Midget hulks? Lame! Better as it is.

**Comment by SonixApache** [comment]
I'm not sure how I feel about green super dorfs.

**Comment by icantthinkofanameritenow** [comment]
In practical terms, the mutation has no visible effect on size and I don't see why it should be mutually exclusive with hulk; their effects are entirely unrelated.

**Comment by Gringonius** [comment]
Since when is this intended?
Dwarfism makes going through tables even faster but hulks can break them all the same, I don't see how making each mutually exclusive balances anything.

**Comment by Exxion** [comment]
It has always been intended. Someone put code in specifically to make it the case.

Note: Not saying whether or not it should be the case, because I don't care. But it is intended.

**Comment by Intigracy** [comment]
https://www.youtube.com/watch?v=M-re0HMkldY

**Comment by Intigracy** [comment]
@JustSumBody since you have POLLING, make me a poll on this.
