### ISSUE TITLE
diona and spikes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12033]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if someone signs up for a diona and the diona gets spiked before the ghost gets inside the ghost ll get null spaced istead of entering the diona
> 
> What you expected to happen
> nothing?
> 
> What actually happened
> everything is black and i can hear the deads
> 
> Steps to reproduce if possible
> sign up for a diona spike the diona get null spaced

**Comment by Exxion** [comment]
Actually this one's better

**Comment by robintime** [comment]
#20537 is a more descriptive duplicate
