### ISSUE TITLE
Goonecode Sat Russian Removal

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12047]
[Discussion]
#11974 seems to have removed the Russians from the Goonecode satellite, and replaced them with cyber horrors.

However, I can't seem to find any mention whatsoever in the PR that it was going to do that. @CptWad listed #10454 as being "fixed" but didn't seem to actually tell people anywhere what changes were made to the Goonecode satellite, so people never had the opportunity to voice their opinion on the removal of the Russian mobs.

Do you guys like or dislike the removal of Russians from the Goonecode satellite? Should they be re-added?

**Comment by Durgen** [comment]
good change imo

**Comment by SacredAtom** [comment]
Dumb as hell bring back Russians

**Comment by coldcola** [comment]
pretty rife for abuse, last night some sneaky business with extracting mednanos from cyberhorror injections for mass production.

**Comment by TheFriggenSawbones** [comment]
i liked the russians more but they were insanely easy to cheese

maybe like reduce the number of cyber horrors

**Comment by charmstruck** [comment]
The only reason to go there was to grab a Mateba and now there's one fewer decent place for space exploration

**Comment by CptWad** [comment]
There truely will be no change to the sat that will please everyone
I made more changes than that, adding more challenge to it (moving the SMES and so on) my goal was just to make it more difficult in general. 
Russians were too easily cheesed, but hell if you like russians what I could do is just make new spaceproof russian mobs with laser AK47s and the cool hardsuits
but then people would have laser ak47s and hardsuits

**Comment by Shadowmech88** [comment]
You probably should've described the changes to it in the PR so people could weigh in on them before it got merged.

**Comment by Exxion** [comment]
Yeah always do that

**Comment by CptWad** [comment]
Yeah sorry about that I was quick to jump the gun. 
I can make a NEW pr with EVERYTHING IN IT about the satellite
though I gotta make the mobs and stuff too which I have never done before but I will make it up to the lot of you

**Comment by Shadowmech88** [comment]
Also even if the Russians _don't_ get re-added, it might be nice to just put a mateba or two somewhere on the satellite. They were hands-down the best loot there.

**Comment by CptWad** [comment]
thats another topic entirely that I did want to do later: LOOT
I have NO IDEA what to put there. It cant be too good but not worthless either. 
the first time I did it I considered adding and infinite powercell but decided against it, but now all that excess ammo seems pretty shit

**Comment by charmstruck** [comment]
An infinite powercell? That doesn't seem like something that should be spawned by default

**Comment by CptWad** [comment]
hell dont we have nazi uniforms too? Couldn't we make nazi mobs instead of ruskies? really thats up to preference.

Theres only a few things that use the infinite powercell, the worst being for borg use, but you would need a lot to turn off the engines. (the second worse thing that could happen) 
Its also used in stunprods and stunglubbs 
but maybe a special random cool item out of a loot list like the maint spawns but cooler

**Comment by charmstruck** [comment]
Infinite cell in a Phazon mech would be pretty difficult to take down, especially considering you wouldn't have to take up one of your slots with a power siphon or whatnot

**Comment by SonixApache** [comment]
I'd rather it be filled with viscerators than giving everyone easy access to medical nanites.
