### ISSUE TITLE
NT Mk58 .45 sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12042]
(WEB REPORT BY: bittervanilla REMOTE: 172.93.109.202:7777)

> Revision:
> cc57b785bc42b258ea6432885e6427272121151b 
> 
> General description of the issue:
> When the magazine is removed from this pistol, the sprite changes to 'empty' with the slide drawn back, but there's still a live round that can be fired from the pistol.
> 
> What you expected to happen
> The sprite would only change once the bullet in the barrel was shot/removed
> 
> What actually happened
> Sprite changed too early and didn't reflect the ammo count in the gun.
> 
> Steps to reproduce if possible
> 1. Load NT Mk58 .45 pistol with a magazine (any)
> 2. Click the sprite in hand to eject magazine.
> 3. Look down the barrel to check if a round is still inside and watch your life flash before your eyes alongside the gunfire because the slide you locked back too early slipped and there was still a round in the gun.

I'm not sure if this also happens with the traitor/nuke op sketchin pistol. Might be worth looking into?

**Comment by SonixApache** [comment]
Probably because the change sprite code in the .45 is different from the other guns. I'll have a look soon.
