### ISSUE TITLE
AME on box starts with an odd number of parts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12043]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> cc57b785bc42b258ea6432885e6427272121151b 
> 
> General description of the issue
> Self-explanatory; 11 parts available means only a 1-core engine is possible without Cargo help.
> 
> What you expected to happen
> 12 parts, for a 2-core AME
> 
> What actually happened
> Only 11
> 
> Steps to reproduce if possible
> Play Box.

**Comment by Intigracy** [comment]
uh you can get a two core engine @icantthinkofanameritenow

x x x x 
o x x x
x x x x

o being controller, x being part

**Comment by Intigracy** [comment]
@icantthinkofanameritenow 
![2016-09-28_18-21-23](https://cloud.githubusercontent.com/assets/4043940/18937795/6621a242-85a8-11e6-8f24-c7869b9ab293.png)

**Comment by Intigracy** [comment]
also

x x x x 
o x x x 
x x x x

**Comment by icantthinkofanameritenow** [comment]
Well, I feel like an idiot now. Consider this issue closed.
