### ISSUE TITLE
Centrifuge Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12044]
(WEB REPORT BY: deussex REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> After I upgraded the Virology centrifuge with pico-manipulators, the centrifuge won't stop spinning; ergo never finishing its action
> 
> What you expected to happen
> After the upgrade, the centrifuge would isolate viruses faster
> 
> What actually happened
> The centrifuge is stuck spinning with no way to turn it off w/o losing my blood sample
> 
> Steps to reproduce if possible
> 1.)unscrew/pry out virology centrifuge
> 2.) put it back together, this time using pico-manipulators instead of micro-manipulators
> 3.)attempt to isolate blood sample

P.S.
I don't know whether its the fact I disassembled/reassembled the centrifuge or the fact that I replaced its internal components that caused this problem. I don't even know if replacing with nano-manipulators will affect results.

**Comment by ammy55** [comment]
Just accidentally tested this. Can confirm
Further testing. Tried with the nano manipulators and it works now.

**Comment by clusterfack** [comment]
I remember someone very recently saying they fixed this

**Comment by PJB3005** [comment]
...

It was dylan.

**Comment by clusterfack** [comment]
Of course it was, and people wonder why we removed him

**Comment by despotate** [comment]
Tested in-game.

- Disassembled and reassembled isolator. Still worked.
- Reassembled with 1 micro, 1 pico manipulator. Still worked.
- Reassembled with 2 nano manipulators. Still worked and correctly cut down time to isolate.

Please close this issue.

**Comment by Exxion** [comment]
Reopen if someone can reproduce
