### ISSUE TITLE
Gibbing old body sucks up a borer's soul.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12046]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b9753d8782af69552d8d9626372906bed074a086 
> Die as a human or similar, click a soulless borer to enter it, get sucked into your old body when it gets gibbed. Likely other closely-related methods but I'll test that later maybe.

Likely related to #10646

**Comment by Allspice** [comment]
Clickdragging into a borer then gibbing the human doesn't cause me to get sucked in, even though the old body loses its ckey and retains its old mind (with the related ckey) just like with normally clicking an empty borer.

**Comment by Allspice** [comment]
Set a monkeyman's mind to the mind of the occupied borer, the slug gets sucked up when the monkeyman is gibbed. So there's the problem I guess.

**Comment by clusterfack** [comment]
I'm going to assume this was fixed
