### ISSUE TITLE
Wizard Time Stop affects the Wizard if the wizard moves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12057]
(WEB REPORT BY: orzorn REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5b091dca77d7749488e5bda8a9c7baccf93b5be2 
> 
> General description of the issue
> In testing this spell in the wizard den, an admin noticed that I was being frozen by it. I further tested it and saw that I was frozen if I attempted to move inside of it.
> 
> What you expected to happen
> Not to be frozen inside of my own time stop.
> 
> What actually happened
> I was frozen if I moved. If I stayed in place, I could take actions.
> 
> Steps to reproduce if possible
> Pick time stop spell
> Cast time stop spell
> Attempt to move inside of time stop field
> Realize you are frozen and can't move

**Comment by Exxion** [comment]
You know
Many people, including myself, noticed this
But nobody reported it
I kept meaning to but I forgot

It's been happening for at least a few months

**Comment by ScrambledSteak** [comment]
Wizard isn't fully attuned with his TIME STOP yet. He can only move for a few seconds in the frozen time.
