### ISSUE TITLE
Roburger seems to be broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12055]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
I got infested with a xeno and decided to eat a roburger to turn myself into a cyborg, but not symptoms started in any shape or form and I just hatched later.

**Comment by gbasood** [comment]
When you say hatched I assume you mean borg'd

**Comment by SonixApache** [comment]
Nanites are slow as fuck nowadays. Virus seems to take forever to actually do something, if they even work at all.

**Comment by gbasood** [comment]
Viruses are part lifecode and part RNG, both in notifications and in stage transitions, so sometimes they're slow and sometimes they're VERY fast.

Not a fan of that viruses for this system in part due to that

**Comment by Exxion** [comment]
Ah yes, disease1.
You _know_ something must have sucked if someone went through the trouble of completely remaking it from scratch rather than just fixing it.

**Comment by clusterfack** [comment]
I mean, they use completely different ideologies, one is completely random and one is completely certain. Other than that theyre very similar.
