### ISSUE TITLE
Can't cut holes in books with tactical knives

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12054]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2235342c45d9728519132065375a0909071ecd14
> 
> General description of the issue
> Tactical knives (and other small knives) can't do half the shit you can do with a full-size kitchen knife.
> 
> What you expected to happen
> pull knife from boot holster, apply knife to book, hide stuff in book
> 
> What actually happened
> pull knife from boot holster, apply knife to book, nothing happens

**Comment by Shadowmech88** [comment]
Tactical knives don't work on a lot of things. Like cutting up bedsheets, for example.

The best fix would be to have those check for sharpness rather than istype().

**Comment by SonixApache** [comment]
Yeah, actually. Is that how butchering works as well?

**Comment by Exxion** [comment]
I'm almost certain butchering is a sharpness check
I've seen someone butcher something with a syringe before

**Comment by clusterfack** [comment]
We need sharpness bitflags clearly

**Comment by SonixApache** [comment]
@Shadowmech88 did your sharpness magic fix this?

**Comment by ComicIronic** [comment]
It's likely the tactical knife just hasn't been set to be sharp.

**Comment by Probe1** [comment]
Syringes cutting things was fixed by a recent pr

**Comment by jknpj** [comment]
> else if(istype(W, /obj/item/weapon/kitchen/utensil/knife/large) || iswirecutter(W))
		if(carved)
			return
		to_chat(user, "<span class='notice'>You begin to carve out [title].</span>")
		if(do_after(user, src, 30))
			to_chat(user, "<span class='notice'>You carve out the pages from [title]! You didn't want to read it anyway.</span>")
			carved = 1
			return

books can only be carved by wirecutters and kitchen knifes

**Comment by Probe1** [comment]
Alright lets fix that.

**Comment by SonixApache** [comment]
Lets.
