### ISSUE TITLE
Killing the only wizard should have a chance at making other antagonists

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#12058]
Wizextended is boring and just seems so badly executed now. I think no longer ending the round upon the death of the wizard partially brings to light how bad the game mode potentially was to begin with.

I propose that on the death of the wizard, or say, after about an hour of the round has elapsed, the game mode has a random chance of randomly selecting traitors or something like that.

The bland dish known as a wizard round needs a bit of seasoning now.

**Comment by aceedex** [comment]
Make wizard death force summon guns

**Comment by Exxion** [comment]
Tensioner when

(You're basically describing a wizard-specific version of the tensioner)

**Comment by mrpain666** [comment]
I pretty much figured such. That's fine. Something's gotta change though, this mode is honestly shit right now
.>right now
You know what I mean

**Comment by AutismSpider** [comment]
if the solo wiz dies part of his powers moves on to random player or some shit.

**Comment by rweeblington** [comment]
What if on wizard death the wizard nominates a crew member to get a sliver of their power?
Can kinda be a "Oh you actually were nice to me / No John you are the demons." situation.

**Comment by gbasood** [comment]
This is the sort of reason we need antag datums and probably wont happen until then
Or at least shouldn't

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Fulfilled via d*namic
