### ISSUE TITLE
Cultist  Constructs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12069]
(WEB REPORT BY: arcadionsword REMOTE: 172.93.109.202:7777)

> Revision (Revision: 27b874368ed33ed0572b14c43aa3767206b9c2e6 
> 
> General description of the issue
> Cult constructs now have free movement in space, AND they can't make walls or floors.
> 
> What you expected to happen
> I expected to drift through space and throw down floors and throw up walls to assist my cult brothers.
> 
> What actually happened
> I could only CORRUPT tiles, like Nar Sie, and could also corrupt at range. I also had perfect mobility in space.
> 
> Steps to reproduce if possible
> No clue! Sorry. Kavlax said he'd look into it.

**Comment by PJB3005** [comment]
What type of construct were you even? There's 3 types and only one can actually build walls IIRC.

**Comment by Allspice** [comment]
He was an arti. I took it over for a moment and I couldn't lesser construct walls or build floors on space either.

**Comment by Allspice** [comment]
Yep, another test and I can't make floors or walls in space.

**Comment by ArcadionSword** [comment]
Yep, artificer. All I could do was corrupt existing walls, not even deconstruct normal walls or doors or anything, just turn them into Cult walls and floors. One wall turned INTO a floor, for some reason when I used my powers on it, but otherwise, yeah. Just turning floors into engraved floors and walls into Cult Walls.

**Comment by Allspice** [comment]
Artis touching an adjacent cultwall turns it into a floor, that's a feature.

**Comment by Allspice** [comment]
After doing some looking, it seems that the issue originated with commit 4505af93746, the arcane golem bit.

**Comment by ArcadionSword** [comment]
Thanks for finding that so quickly. It's appreciated by all cultists and constructs alike.

**Comment by gbasood** [comment]
Assuming this is resolved?
