### ISSUE TITLE
Deff(and I'm pretty sure Meta's) Supply shuttles are still fucked

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#12060]
revision 5b091dca77d7749488e5bda8a9c7baccf93b5be2 
![image](https://cloud.githubusercontent.com/assets/19365096/19012997/a5e7e4fe-8792-11e6-9758-d9f244f392ef.png)

From what I'm told, Wad copypasted the Box cargo shuttle and they're supposed to be differently sized or something. They still need to be set to destroy everything(causing a breach) and deff's(pictured) doesn't line up with the conveyor belts.
I mentioned this in the other issue, but it seems it was a completely separate issue entirely from the docking port thing.

**Comment by SonixApache** [comment]
paging doctor @CptWad

**Comment by Kammerjunk** [comment]
Meta's shuttle got fixed in #12025 but it seems Deff got overlooked
Second verse, same as the first

**Comment by CptWad** [comment]
reeeeeeeeee I thought this was fixed goddamn it
im fixing it atm
