### ISSUE TITLE
roundstart Mr. V.A.L.I.D. Portable Threat Detector are broken.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12062]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5b091dca77d7749488e5bda8a9c7baccf93b5be2
> 
> General description of the issue
> They don't do shit.
> 
> What you expected to happen
> subject clear
> 
> What actually happened
> ...

**Comment by SonixApache** [comment]
also #7821

More specifically;
Box station - took a roundstart threat detector to the front of the security wing - wrenched it down - hit the buttons (that do nothing) a few times - it does nothing

Cargo ones worked, I think.

**Comment by Exxion** [comment]
> Cargo ones worked

Anyway post that on the issue you linked, as this is a dupe but less specific
