### ISSUE TITLE
Pouring out a glass of vox blood makes two (2) colors of blood

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#12070]
It also shows up red in the glass and it's still called a glass of tomato juice

**Comment by Gringonius** [comment]
But if you put it in an IV drip it shows up as blue, even if the bloodbag will be red when removed. Go figure.

**Comment by Exxion** [comment]
Yeah but it's not the right shade of blue

It probably shows up the right color in a beaker, but who actually knows?

**Comment by ComicIronic** [comment]
I think it's not the right shade of blue because of the plastic.

**Comment by Shadowmech88** [comment]
I wasn't able to pour it out, but I threw the glass and it only produced a blue puddle when it broke.
As far as the other issues, what would be the best solution? We don't have any blue juices. Should we just forego the joke entirely for non-red blood and call it a glass of blood?
