### ISSUE TITLE
(Internal) Bleeding persists on limbs after removal.

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#12071]
#### Description of issue

Limbs will continue bleeding even if they no longer exist.
Health Analyzer will report that the patient has internal bleeding but the advanced scanner will not find anything since the affected limb no longer exists.
~~Because the limb no longer exists and can not be operated on, there is no way to actually fix the bleeding.~~
If you replace the limb with a prosthesis the advanced medical scanner will correctly report internal bleeding in the limb but as a prosthesis can not be operated on you're permanently fucked.
#### Difference between expected and actual behavior

I expected a non-existent right arm to not have internal bleeding but it did.
#### Steps to reproduce

Make someones limb bleed and then hack that shit off.
#### Length of time in which bug has been known to occur

I don't freaking know I just noticed it.
#### Server revision

27b874368ed33ed0572b14c43aa3767206b9c2e6
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Also applies to damage, and really everything else.
We really need to fix tons of shit about limbs.

**Comment by Allspice** [comment]
The vein is presumably fucked and dangling out or something. You only need to apply the fixo to repair internal on severed limbs.

**Comment by BestName** [comment]
> The vein is presumably fucked and dangling out or something. You only need to apply the fixo to repair internal on severed limbs.

Well that's nice to know. Too bad it isn't explained anywhere and since the internal bleeding won't show up in the scanner you're fucked unless you're in the know.

And what if you replace the missing limb with a robolimb (like I did)?

**Comment by Exxion** [comment]
Then you're fucked until you remove it
Again, we pretty much have to rewrite limbcode

Which I think @Skullyton is already working on

**Comment by gbasood** [comment]
this isnt evne just muh immulsions
If someone is bleeding to death when they're a quad amputee there's no way to fix their bleeding limbs because THEY HAVE NONE

**Comment by Exxion** [comment]
That's why it's also tagged bug

**Comment by BestName** [comment]
Fixed in #12803 probably
