### ISSUE TITLE
Noir effect remains after clean SE and ryetalyn

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12080]
(WEB REPORT BY: hudenagyon REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Roundstart noir effects are not affected by clean SE and ryetalyn even of the player gets the power deactivation message. Blood doesn't show up as red or blue or whatever color it has.
> 
> What you expected to happen
> Blood shouldn't be affected by monochrome affect. Deactivation of noir should remove the black and white.
> 
> What actually happened
> Read above. Additionally, restarting byond didn't help. Noir music started up and everything went gradually monochrome, including blood.
> 
> Steps to reproduce if possible
> roundstart gumshoe
> get clean se and ryetalin
> spread some blood around
> try to restart

**Comment by clusterfack** [comment]
@drcelt

**Comment by ghost** [comment]
Hmm

**Comment by clusterfack** [comment]
Check for runtimes

**Comment by JustSumBody** [comment]
It's runtiming on `activate` and `deactivate`
`Runtime in vg_powers.dm, line 158: Cannot read null.screen`

**Comment by gbasood** [comment]
I have no clue how this happened
Didn't noirblock require the fullscreens.dm stuff i ported in 510 or something
Because that'd mean I had nothing to do with this

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Holy shit I thought I broke this but it turns out it's 2 years old
