### ISSUE TITLE
The big red pressure tanks in maintence are storing gas at 0 degrees C

### ISSUE THREAD

**Issue by jakmak** [d3athrow/vgstation13#12081]
#### Description of issue

Those big red map object only pressure tanks located in main on the stations are storing gas at 0 degrees Celsius. I have spawned a few in the map maker when testing a map and they were also at 0 degrees Celsius .
#### Difference between expected and actual behavior

The gas in these tanks is at 0 degrees celcius when normal 02/air/general gas canisters store it at 20 degrees round start and also i feel that with hypothermia  these could be a minor hazard because cold
#### Steps to reproduce

find pressure tank in maint on all modern maps. Hit with gas analyzer. Read temperature, ???. Profit

![](https://puu.sh/rwNpe/2be3d2d9a0.png)

tried on all mediums the gas is 0 degrees Celsius. Sometimes being 1 degree higher or lower. I connected the canister to them to verify it wasnt the gas reader derping and released the gas in the room it did turn it reduce the room temp when opened
#### Specific information for locating

spend 5 minutes patrolling maint and you will see a set of 1 or 2 

![](https://puu.sh/rwNiH/293a49a0cc.png)
these puppies right here
#### Server revision

3488779386043e20c8bf699523441f1119dbfd3b Current Infomational Settings: 
Protect Authority Roles From Tratior: 1
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)
  )

**Comment by gbasood** [comment]
What MAP

**Comment by Exxion** [comment]
I'm pretty sure it's not a map issue, and thus it's all maps

**Comment by ghost** [comment]
It's so the canisters store more.
It makes no difference with hypothermia or anything, I've used them fine for a long time.

**Comment by Probe1** [comment]
That's an oversight.

**Comment by Probe1** [comment]
If you're wondering this will fuck up atmos and confuse the SHIT out of atmos techs as to why it's being fucked up.

**Comment by gbasood** [comment]
No what how is that an oversight
Cold gas has less volume and is more ideal for storage than warm gas
Whether or not this is actually USEFUL is more of an issue of whether or not it was intended
Or maybe it just needs to be described as cold as fuck gas somewhere in the obj desc

**Comment by Sprok0** [comment]
Mixing one of those tanks into the entire distro loop won't drop the temp very much anyway if it has anything in it already. The amount of gas in them is really not much compared to the volume of the whole pipe network

**Comment by Shadowmech88** [comment]
I suppose this is a feature after all, then.
