### ISSUE TITLE
emergency oxygen tanks sometimes break when refilled

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12089]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> sometimes while you refill an emergency oxygen tank to full it wont work and give no oxygen with internals on
> 
> What you expected to happen
> breathe with a full oxygen tank
> 
> What actually happened
> no air
> 
> Steps to reproduce if possible
> refill an oxygen tank
> 20% chance of it not working or something

**Comment by SonixApache** [comment]
Sometimes when it's 100% empty it sets the release pressure to 0kPa.
Did you check that and/or set it back to 16?

**Comment by Kammerjunk** [comment]
"someone tell this idiot that he's refilling from air canisters instead of oxygen canisters
i'm too lazy to make an account"
t. anon

**Comment by Exxion** [comment]
@pvak Can you confirm either of these things?

**Comment by SysadminJeroen** [comment]
Most likely this: https://github.com/d3athrow/vgstation13/issues/6945#issuecomment-180946908

**Comment by Exxion** [comment]
Unless pvak can confirm he checked the release pressure and didn't fill it with air, it's not a bug

**Comment by SysadminJeroen** [comment]
@pvak pls confirm

**Comment by Intigracy** [comment]
haha pvak refilled his oxygen with air hahahahahaha

but seriously to breathe air it's like way higher kpa than 16

**Comment by SysadminJeroen** [comment]
You only need 16 kPa for oxygen.

**Comment by Intigracy** [comment]
I said air.

**Comment by pvak** [comment]
admin said that when an oxygen tank is completly empty the valve closes itself and you have to manually turn it one so its a "feature"

**Comment by Exxion** [comment]
That's definitely weird behavior, but not really a bug
Open a new issue if you want it changed
I'd tell you to just change the title and OP of this one, but it's a web report, so you can't
