### ISSUE TITLE
hypomemia ruining lives

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12086]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 3488779386043e20c8bf699523441f1119dbfd3b 
> 
> General description of the issue
> I was a ling on deff. I monkey formed to remove my cuffs, and nearly instantly fell asleep permanently with no hope of ever waking up. I had to regenerate after about 20 minutes as a monkey (forever trapping me in my form, unable to transform back into a human), and then I continued being plagued with falling asleep every other second. it kept giving me messages like, your exhausted, you could use a nap, you really need to get warmed up, etc.
> it was so bad, I have to regenerate so I can walk another 2 feet before I collapsed to sleep again for all of eternity.
> What you expected to happen
> monkey shouldn't fall asleep to hypothermia so often, they should have a greater trheshold since they have fur, and they walk around naked all the time.
> 
> What actually happened
> I got memed on by Celt and Duny
> 
> Steps to reproduce if possible
> be ling on deff (I never had this happen on bax as far as I remember)
> lesser form yourself in the hallways
> CAN'T WAKE UP!

**Comment by TheFriggenSawbones** [comment]
#11937

**Comment by Intigracy** [comment]
hypothermia was a mistake

**Comment by clusterfack** [comment]
@drcelt

**Comment by ghost** [comment]
They do have a greater threshold due to fur.

**Comment by ghost** [comment]
As to why this happens, who knows.

**Comment by ghost** [comment]
I mean, if it never happened on box? That doesn't make it sound like a problem with hypothermia, honestly. I'll look into it anyway, but uh my gut feeling is that there was something in round which cooled the hallways.

**Comment by rweeblington** [comment]
Can confirm it was round-contextual.
I lesser form'd myself as ling on deff last night 1 minute into the round and felt no effects of hypothermia.

**Comment by Shadowmech88** [comment]
I think [Unable to Reproduce] or [Needs Moar Testing] might be more appropriate labels.

This certainly is a bug.

**Comment by gbasood** [comment]
I mean, can you reproduce it in a setting where it shouldn't happen?
Because as I'm reading it, it was cold so he got hypothermia.

**Comment by Shadowmech88** [comment]
I don't know if it was confirmed that the hallways were cold during that round.
