### ISSUE TITLE
Some stuff about vampires

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12084]
(WEB REPORT BY: strawberrytan REMOTE: 172.93.109.202:7777)

> Revision Revision: 3488779386043e20c8bf699523441f1119dbfd3b
> 
> General description of the issue
> Vampire interaction with corpses. I had a dead player's husk and wanted to give it the succ. So I transplanted the brain into a monkeyman and did so. This worked perfectly, but after I did I had a thought and monkeyed them, then turned them back into a human. Bam, they had 100% blood again and I was able to succ them a second time. Repeated a third time to confirm, monkeying a succed body and turning it back into a human restores all of it's blood for vampires to cycle endlessly.
> 
> What you expected to happen
> Player brain in monkeyman allowing the suck.
> Bloodless monkeyman being monkeyed and back not to restore all of it's blood.
> 
> What actually happened
> Player brain in monkeyman allowing the suck.
> Bloodless monkeyman being monkeyed and back DID restore all of it's blood
> 
> Steps to reproduce if possible
> stick fully drained human corpse into genetics machine
> turn into monkey
> turn back
> full human cadaver for sucking

**Comment by gbasood** [comment]
Already documented
