### ISSUE TITLE
Deff Supply Shuttle 3: With a Vengeance

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#12085]
#### Description of issue

@CptWad 
Deff shuttle's still broken. It now tries to teleport to the correct location when returning to CentComm, but is unable to because it's flipped around:
`ADMIN LOG: WARNING: supply shuttle (/datum/shuttle/supply) attempted to destroy the Centcom Supply Shuttle (/area/centcom/suppy). If you want supply shuttle to be able to move freely and destroy areas, change its "destroy_everything" variable to 1.`

If you set destroy_everything to 1, this happens when it docks at CentComm:
![how did it get here](https://cloud.githubusercontent.com/assets/5942183/19074058/8e6156a4-8a3e-11e6-9119-ba716ef6f852.PNG)

At roundstart, the shuttle is docked normally:
![this is good](https://cloud.githubusercontent.com/assets/5942183/19074416/600a4002-8a40-11e6-9df1-045caee32f6d.PNG)

Sending the shuttle back to the station has no adverse effects (like killing everyone or tearing a shuttle-sized hole in the station).

I'm guessing it's caused by the docking port being where it is instead of at the fore airlock.
#### Difference between expected and actual behavior

Deff supply shuttle still needs admin intervention to run and docks inversed at CentComm.
The only current result of this if it doesn't get admin intervention is that the crew has no wait time on their crates arriving, so I guess you can just call it a feature.
#### Steps to reproduce

Load up Deff
Send supply shuttle
#### Length of time in which bug has been known to occur

Since #12067 was merged, I imagine.
#### Server revision

3488779386043e20c8bf699523441f1119dbfd3b
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched for "deff" and shuttle"

**Comment by CptWad** [comment]
f u c k

**Comment by Manfreedo** [comment]
Same issue
https://github.com/d3athrow/vgstation13/issues/12073
Uncheck point 5

**Comment by Exxion** [comment]
It really isn't.

**Comment by Kammerjunk** [comment]
#12073 is about the conveyor belts being borked.
This is about the docking port on CentComm being flipped the wrong way round and in the wrong spot or whatever, I dunno.
