### ISSUE TITLE
Vivi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12094]
(WEB REPORT BY: scottkip REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> ebc132e98c018adfb749af43668d9a7b6111cf35
> 
> General description of the issue
> An admin spawned me in as Vivi, the little bird in a cage. When I was being carried by someone as an object, I slowly suffocated until I died.
> 
> What you expected to happen
> Not to suffocate.
> 
> What actually happened
> I suffocated.
> 
> Steps to reproduce if possible
> Spawn someone in as Vivi, and have someone else hold Vivi.

**Comment by JustSumBody** [comment]
I think you're a bit confused.
Technically you were a human mob named Vivi stuffed inside a renamed canary item, there's some issues with it where stuffing people into objects causes them to suffocate/get hypothermia'd.

**Comment by TheFriggenSawbones** [comment]
the admin needs 2 toggle the genetic blocks for no breathe and cold/heat res to be honest
