### ISSUE TITLE
kneesocks description is missing a period

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12095]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> literally unplayable
> 
> What you expected to happen
> That's some kneesocks. They are a normal-sized item.

A pair of girly knee-high socks.

> What actually happened

That's some kneesocks. They are a normal-sized item.

A pair of girly knee-high socks

> Steps to reproduce if possible
> examinate kneesocks
> find out its missing a .

**Comment by gbasood** [comment]
don't label a grammar problem a consistency issue that's just excessive

**Comment by Exxion** [comment]
But it is a consistency issue
Most things have periods and it doesn't
