### ISSUE TITLE
space carpet tiles [feature request[

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12090]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
tiles that have the icon of space 
because reasons
maybe made by applying a bear fur to a carpet tile?

**Comment by SonixApache** [comment]
Black version of the arcade carpet?

**Comment by clusterfack** [comment]
Web reporter isn't for feature request you numbnuts
