### ISSUE TITLE
Raider gamemode has no end-of-round information

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#12106]
#### Description of issue

The end of round screen does not show any information about the vox raiders. Not who they were, what their objectives were, if they succeeded or anything.
#### Length of time in which bug has been known to occur

Months, if not longer.
#### Server revision

d8cd9c5014e09152c2697b3df07444501334c917
#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SkowronX** [comment]
Raider a shit. Remove

**Comment by gbasood** [comment]
This probably has a duplicate somewhere

**Comment by Allspice** [comment]
Probably closed by https://github.com/d3athrow/vgstation13/pull/12153
