### ISSUE TITLE
Maracas jangle while in your pockets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12104]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Maracas in your pocket act as if they are in your hand (whenever you change direction they make that noise)
> 
> What you expected to happen
> At least a sort of muffled jangle, I dunno
> 
> What actually happened
> CHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKYCHICKY
> 
> Steps to reproduce if possible
> put maracas in pocket and jiggle

**Comment by Probe1** [comment]
https://www.youtube.com/watch?v=5nMrIjBBov8
