### ISSUE TITLE
Request to change Defficiency External Airlock for the Reasearch Outpost

### ISSUE THREAD

**Issue by IAGFPRMF1** [d3athrow/vgstation13#12102]
http://puu.sh/rzioy/d1008db574.png
Room is too large, venting usually results in painful ZAS without magboots. 
A busy xenoarchaeologist will have to crowbar the firelock that closes at the northern airlock (blowing everything around if you do not feel like waiting for the room to repressurize) and navigate around with magboots on. 

Hilariously lethal if you forget to turn your magboots on re-entry 

Here's the airlock for the Box Research Station for comparison.
http://puu.sh/rziLy/668e8d00ab.png

**Comment by Exxion** [comment]
It needs cycling airlocks.
Also the Deff main mining airlock blocks air which is bad and dumb

**Comment by AlphaBuffalo** [comment]
FUCK YOU DUNY

**Comment by Exxion** [comment]
In his defense, external airlocks blocking air when open used to be common practice, but we rightly decided it was fucking stupid

**Comment by AlphaBuffalo** [comment]
whats stupid is that the vent cant siphon air and opening that airlock will always depressurize it
