### ISSUE TITLE
Give HoP/Captain ability to invalidate IDs of dead crewmembers

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#12100]
Would probably want an additional step in here like they have to be confirmed dead by medical first?
I don't know
Should be reversible since cloning

**Comment by Shadowmech88** [comment]
This power might make more sense in the hands of the IAA.

Also this would really screw over traitors who might need that access to get to their target.
It also doesn't really make sense with the game's current internal logic. IDs have never been remotely-accessible in any form, and door access has never been remotely alterable.

**Comment by SonixApache** [comment]
HoP / captain can already invalidate the ID of a dead crewmember by slapping it into their machine and setting it to assistant.

There's absolutely 0 logic for remote ID control in our codebase right now.

Alternative idea; 'Secure' IDs that CAN be remotely modified. R&D items?

**Comment by Kurfursten** [comment]
If it was implemented you would have to be very careful because either you just created...

> A 100% foolproof way to detect if someone is alive or dead remotely

OR

> A mostly-foolproof way to remotely strip a suspect of any access, especially so if they're not really a traitor, because then they probably won't have stolen backup IDs, emags, etc.

I don't really want to see cops with the ability to lock you down in your office remotely, make you wait 8 for them to show up, get tasecuffed and dragged to the brig for 2 minutes, interrogated and strip searched for 5 minutes, and then put in a cell for 3 minutes for lifting someone's muffin.

**Comment by PJB3005** [comment]
Exact same opinion as @Kurfursten, this would drastically unbalance the game.

**Comment by gbasood** [comment]
Okay thanks for opinions, I think you guys are right.
On the remote ID control: I really doubt the IDs themselves are controlling anything. Airlocks/etc read the IDs, and in a system that isn't insane that'd mean reading a database of IDs to see what access your ID has.
But it's spess so that's fine.
