### ISSUE TITLE
Defficiency's random detritus cannot be cleaned by any mortal means.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12118]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)

> Revision 
> 6cc88f327d8296b8c80ca3539b1a654c8106eda5
> 
> General description of the issue
> The piles of robot remains that encrust deff maints are impossible to clean, move or pick up. 
> 
> What you expected to happen
> They can be cleaned like robot gibs spawned when a borg explodes.
> 
> What actually happened
> The janitor cries.
> 
> Steps to reproduce if possible
> 1: lose all common sense.
> 2: vote deff.
> 3: Pick janitor.
> 4: ???

**Comment by Sprok0** [comment]
those aren't actually gibs, they're "remains", like the bone piles humans turn into when ashed

**Comment by Shadowmech88** [comment]
Why aren't remains cleanable anyway?

**Comment by SonixApache** [comment]
A lot of random shit in Deff is actually just decals, like the damaged hull in the ghetto diner. It's awful.

**Comment by FudgePucker** [comment]
Out in the far distances of space, a thousand voices scream out load, but can only be heard as faint as a whisper.
FUCK YOU DUNY

**Comment by Gringonius** [comment]
I propose we take care of this issue by removing Deff.

**Comment by PJB3005** [comment]
Deff is literally the best map.

**DUNY DID NOTHING WRONG**

**Comment by Megamaw** [comment]
i like deff, but gosh dang is it frustrating to try and clean it up as a janitor

**Comment by gbasood** [comment]
We could add an obj that just spawns in the desired gibby-parts as cleanable messes.

**Comment by Probe1** [comment]
It's a coding issue not a map issue

**Comment by SonixApache** [comment]
pretty sure it's a mapping issue

**Comment by Probe1** [comment]
It's a mapping issue that these exist on a map.  It's a coding issue that these cannot be cleaned.  

The issue wants them to be cleanable, not removed.

**Comment by SonixApache** [comment]
The detritus is decals, so it's definitely a mapping issues for starters. Shit's gotta be mapped out to even allow it to be cleaned.

**Comment by Probe1** [comment]
Turns out it was a map issue.  Duny used the wrong subtype.

@SonixApache :)
