### ISSUE TITLE
Farm bots don't do fucking shit yo.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12111]
(WEB REPORT BY: ammy55 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d8cd9c5014e09152c2697b3df07444501334c917 
> 
> General description of the issue
> Farm bots do all of fucking nothing. no Matter what the behaveoural controls are set to. 
> 
> What you expected to happen
> Farm bots to be usefull
> 
> What actually happened
> Litterally nothing.
> 
> Steps to reproduce if possible
> 1.Make a farm bot
> 2. Be amazed as nothing fucking happens

**Comment by ammy55** [comment]
Alright i'd like to offer a correction, the farm bot doesn't do fuckall, but what it does do it doesn't do well.
So let's dive in to what i now know.
1. the UI doesn't update when you click on anything so you have to re-click on the bot to update the UI
2. The "Ignore empty trays" option does the exact opposite of what it's setting is at
3. When it does weed or water a tray it takes a while for the sprite on the tray to update and clear the water/weed light.
4. it's just fairly slow to move between tasks.

**Comment by Exxion** [comment]
I'm pretty sure all the bots except sec ones suck major ass right now.
Actually the cleanbots might work
But floorbots and farmbots are definitely fucky

**Comment by SonixApache** [comment]
Cleanbots had super weird pathfinding last time I checked.
Medbots are the only good ones, and even they have some bugs.

**Comment by Shadowmech88** [comment]
According to Jknpjr, this is no longer the case.
