### ISSUE TITLE
putting a monkey cube on a fork makes you eat the monkey cube

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12115]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> that
> 
> What you expected to happen
> monkey cube on a fork
> 
> What actually happened

has a malformed monkey (937) sticking out of his flesh!

> Steps to reproduce if possible
> hit a monkey cube wit ha fork

**Comment by gbasood** [comment]
``` dm
/obj/item/weapon/reagent_containers/food/snacks/attackby(obj/item/weapon/W, mob/user)
    if(istype(W,/obj/item/weapon/pen)) //Renaming food
        var/n_name = copytext(sanitize(input(user, "What would you like to name this dish?", "Food Renaming", null) as text|null), 1, MAX_NAME_LEN*3)
        if(n_name && Adjacent(user) && !user.stat)
            name = "[n_name]"
        return
    if(istype(W, /obj/item/weapon/kitchen/utensil/fork))
        var/obj/item/weapon/kitchen/utensil/fork/fork = W
        if(slices_num || slice_path)
            to_chat(user, "<span class='notice'>You can't take the whole [src] at once!.</span>")
            return
        else
            return fork.load_food(src, user)
```

can't see what'd cause this

**Comment by PJB3005** [comment]
... How is this a bug? 

You can eat monkey cubes.

**Comment by Shadowmech88** [comment]
If I'm reading the issue right, I think he's saying that the act of putting it on the fork caused him to immediately eat it.

I know we had a change to forks recently, can you no longer have food on a fork? Does using a fork cause you to instantly take a bite now?

**Comment by Eneocho** [comment]
can't put monkeycubes on forks now
