### ISSUE TITLE
fire flies away

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#12122]
https://dl.dropboxusercontent.com/s/fbrbn83okough9l/2016-10-08_01-24-13.webm?dl=0

**Comment by FudgePucker** [comment]
Its a feature

**Comment by Exxion** [comment]
Memes aside, hyperspace code a fuck

**Comment by Probe1** [comment]
Gas moves from a high volume state to a low volume state.  Or in this case, shit is flying out of the goddamn shuttle and I don't know what else to expect it to do.

**Comment by Probe1** [comment]
@PJB3005 would like to see hyperspace not fuck with atom locking.

**Comment by Exxion** [comment]
To be fair, that's really more of a problem with hyperspace than atom locking

**Comment by PJB3005** [comment]
Yep.

**Comment by Shadowmech88** [comment]
RIP the original file that showed what exactly the report was about.

**Comment by Exxion** [comment]
Fire is an object, and it was getting dragged away by hyperspace
I think it was Ring of Fire, since I'm pretty sure that's the only case in which fire can hit the throwers
Maybe flamethrowers too, but that wouldn't really be a problem

**Comment by Shadowmech88** [comment]
Is it a problem for ring of fire? The ship is moving at hyperspeed, after all.
Hyperspace throwers are pretty bad, but should I reopen this report specifically?

**Comment by Exxion** [comment]
Probably not a big enough deal to bother with other than just removing hyperspace throwers
