### ISSUE TITLE
Mousetraps can be triggered when dead

### ISSUE THREAD

**Issue by Sordine** [d3athrow/vgstation13#12137]
Armed mousetraps in containers can be triggered when dead if you stay in your body and try opening the container. You still have to be close enough to the container to open it. This can be used to trigger bombs after you have died.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
There are already other ways to trigger bombs while dead, but yeah that shouldn't happen
