### ISSUE TITLE
General Fabricator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12139]
(WEB REPORT BY: deussex REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> The General Fabricator doesn't work
> 
> What you expected to happen
> I would insert a blueprint (paper or nanopaper), and the Gen Fab will accept the design so I can print a machine out
> 
> What actually happened
> Gen Fab will not accept any design. To be specific, the error message reads: "This isn't the right machine for that kind of blueprint!"
> 
> Steps to reproduce if possible
> Scan anything with device analyzer
> Let Reverse Engine research and print out a blueprint
> Attempt to put it in the Gen Fab

I don't know if that's how you're supposed to work it, but what else can you do to operate the Gen Fab? It accepts metal,glass, and plastic, but not the designs it was meant for?

**Comment by jakmak** [comment]
You see mechanics blueprints are used in 2 machines. Flat pack fabricator and general fabricator. Flat pack fab is for MACHINES (cloners, protholathe, autolathes, consoles, ect) and gen fab is for hand held objects (rcd's, most tools, stun batons, hand teles, ect) AND If you are traitor mechanics you can buy a special scanner that lets you scan guns and traitor items and make them in the general fabricator ( emag, c4, c20r, eguns, shotguns, Esword, E bow, ect)
