### ISSUE TITLE
Opening an R&D lockbox while in your hand makes the contents disappear.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#12148]
#### Description of issue

Opening an R&D lockbox while in your hand makes the contents disappear. @Sprok0 
Tested this on my local server, not on the main server.
#### Difference between expected and actual behavior

Expected:
Hold lockbox in hand -> apply ID with other hand -> lockbox disappears -> contents appear under your feet
Actual:
Hold lockbox in hand -> apply ID with other hand  -> lockbox disappears
#### Length of time in which bug has been known to occur

Since #11753 was merged.
#### Server revision

763239efe8644c09c5f7d3859852df5207adfa21 
#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kammerjunk** [comment]
Confirmed on main server
