### ISSUE TITLE
Lockboxes check both the ID in the ID slot and the ID in hand.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#12149]
#### Description of issue

When opening lockboxes, the lockbox doesn't just check the ID you're using to open it (ie the one in your hand), but also your currenty active ID. @Sprok0 
Only tested on my local server, not on the main server.
#### Difference between expected and actual behavior

Expected:
Be Captain -> Slap engineer ID on lockbox -> Access denied!
Actual:
Be Captain -> Slap engineer ID on lockbox -> You unlock the lockbox!
#### Steps to reproduce
- Have an ID with sufficient access equipped.
- Have a spare ID with insufficient access in-hand.
- Acquire a lockbox that requires access.
- Apply spare ID to lockbox.
#### Length of time in which bug has been known to occur

Since #11753 was merged.
#### Server revision

763239efe8644c09c5f7d3859852df5207adfa21 
#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Sprok0** [comment]
They actually only check the ID that you hit them with, how would they be able to check what you're wearing? Wait nevermind I misread
