### ISSUE TITLE
Almost every door is accessable with public acces.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12158]
(WEB REPORT BY: ch0c0latem00se REMOTE: 172.93.109.202:7777)

> Revision 7057b53501244f865475081b3aecf64f01542769 
> 
> General description of the issue
> Almost every door (excluding the Captain's office, the HoP's office, Security checkpoint, server room, probably more) has public access, so any chucklefuck can run in there.

**Comment by Exxion** [comment]
God damn it
$50 says that the code checks for the _existence_ of `req_access` or `req_one_access` (whichever one overrides the other) and since they are now empty lists by default rather than `null`, everything is fucked

**Comment by ghost** [comment]
😂👌🏻
