### ISSUE TITLE
Building Pressure Tanks [Feature Request]

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12154]
Is there any reason why the big red tanks south of ghetto bar in box can't be built? I feel like it'd be a pretty neat thing to have as an atmos tech, and way cleaner than a window enclosed tile

**Comment by AutismSpider** [comment]
build them out of what though plastic? plasteel?

**Comment by Shadowmech88** [comment]
I remember reading in the code once that the gas contained in the red pressure tanks is supposedly some kind of snowflake gas with unique burn properties.

**Comment by PJB3005** [comment]
Nah, there's a tank in the code that has the oxygen agent b gas, nut otherwise it'd the normal gases.

**Comment by Shadowmech88** [comment]
Are the oxygen agent B tanks on the map anywhere, or are they unused?

**Comment by AutismSpider** [comment]
i think some in box near cargo and the ghetto bar

**Comment by PJB3005** [comment]
@AutismSpider uh no they're unused what are you on about.

**Comment by ghost** [comment]
@AutismSpider Plastic doesn't seem like too safe a material and it'd have sort of a snowflake status in engineering use when mechanics and science need it way more.
Metal, with cost ramped up to be way higher than canisters' could make sense, and plasteel at canister cost would let you have more tanks in a single stack, but the currently available plasteel at engineering might end up being too little. Might.

Edit: Just looked at canister code and it's volume is half a tank's so (I thought it was a third or a fourth). I'd guess that just double the metal would do the trick, given you lose mobility to gain condensed space. Hell, maybe even lower than that, not sure

**Comment by ihadtoregisterforthis** [comment]
What about multiple steps to build?

**Comment by AutismSpider** [comment]
@ihadtoregisterforthis 
Make pressure tank shell form plasteel or iron put some rods on it weld the rods then slap some iron on it?

**Comment by beesil** [comment]
Added in #22883
