### ISSUE TITLE
Add more virus effects

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#12169]
Virology has only 1 real use, and that is making extremely deadly viruses. Other than that, the are has a few uses for blobs, xenos, and hiding bodies since its a mostly unused space.

There are some beneficial viruses but they arent worth the trouble and are greatly out numbered with the extremely harmful ones. There is also the extreme RNG thing that can make it next to impossible to find virus effects that wont kill people. 

Instead of getting a virus sample and hoping for good traits, I'm thinking of going the genetics route, or using another system where you can pick the trait from a pool of pre determined traits and then combine them. The other system is just an idea, feel free to express your opinion.

I'm also thinking of adding things like gimmicky things like vamp skin (which makes you burn in the sun light (space in our case)), rock skin (increases brute resistance while also making you a little slower, or use more energy and get more hunger), night eyes (see better in the dark), toxin filtration (your body can scrub toxins from the air and you produce anti-toxin in your body), and much more.

**Comment by gbasood** [comment]
Oh boy look at this fucking broad feature request with no specifics

**Comment by AlphaBuffalo** [comment]
Isn't that the norm here?

**Comment by AlphaBuffalo** [comment]
closing from lack of interest
