### ISSUE TITLE
Mice can place stuff in disposals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12178]
(WEB REPORT BY: jeroen52 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 02a01197183ab1b5eb1b5655d68eb7944e7f6d63
> 
> General description of the issue
> A mouse can put items in disposals.
> 
> What you expected to happen
> The mouse not putting something in disposals
> 
> What actually happened
> mouse (794) places the red suit into the the disposal unit. 
> 
> Steps to reproduce if possible
> No clue, I assume you become a mouse.

**Comment by coldcola** [comment]
apparently Diona can too, just as a note.

**Comment by Exxion** [comment]
Dionae should be able to
They have hands that can pick things up
