### ISSUE TITLE
there is only one destination tagger in box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12177]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> 1 destiantion tagger
> 
> What you expected to happen
> at least 3
> 
> What actually happened
> lose it no crates 
> 
> Steps to reproduce if possible
> be in box station

**Comment by Shadowmech88** [comment]
Alternatively, a way to make or even _order_ more would be nice.

**Comment by charmstruck** [comment]
Would be nice if it was scannable by the device analyzer

**Comment by uazuaz** [comment]
reminder that using screwdriver + multitool on destination taggers let you add custom tags or remove tags, and that they can be used on sorting junctions to select their destination, so they could be used by people with a RPD to repair or even expand the disposal/mailing system.
said that, having more destination taggers would be nice.

**Comment by PJB3005** [comment]
I'm genuinely surprised there's someone except me that knows that (I coded it)

**Comment by uazuaz** [comment]
i just had too much spare time when doing experiments.
by the way there is a little bug when you add a tag, the new tag will be always all caps.

**Comment by Shadowmech88** [comment]
Put that bug in its own report.

**Comment by uazuaz** [comment]
i just made a test and i saw that tags are not case sensitive, so you can use either normal or all caps tags, also nobody uses this feature, so it doesn't really matter.

**Comment by ammy55** [comment]
why not just add it to cargo techs roundstart equipment or the cargotech lockers?

**Comment by Probe1** [comment]
The destination tagger can be created in the autolathe.  Please use that.

```
C:\Coding Projects\SS13\vgstation13\code\game\machinery\autolathe.dm

"Misc_Tools"=list(
		new /obj/item/device/flashlight(), \
		new /obj/item/weapon/extinguisher(), \
		new /obj/item/device/radio/headset(), \
		new /obj/item/device/radio/off(), \
		new /obj/item/weapon/kitchen/utensil/knife/large(), \
		new /obj/item/clothing/head/welding(), \
		new /obj/item/device/taperecorder(), \
		new /obj/item/weapon/chisel(), \
		new /obj/item/device/rcd/tile_painter(), \
		new /obj/item/device/rcd/matter/rsf(), \
		new /obj/item/device/destTagger, \

```

**Comment by ComicIronic** [comment]
That should be good enough, unless somebody moved the autolathe out of Cargo.
