### ISSUE TITLE
c20r's bug out if you use their magazine completely

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12176]
#### Description of issue

If you fire a c20 until it has completely expended the rounds in its magazine, it will eject said magazine, then you can't actually reload it with another magazine after.
#### Difference between expected and actual behavior

Expected: Being able to hit the now-empty c20 with a magazine to reload it

Actual: Absolutely nothing
#### Steps to reproduce

> Shoot gun
> Shoot it till it goes _beep_
> Marvel that the magazine just entered your other hand
> Worry when you can't reload it with a spare magazine in your pocket
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
C-20rs cannot load R&D 12mm magazines, they can only load their special /ops subtype.
Where'd you get the spare magazine?

**Comment by ghost** [comment]
From another C-20r, it was on the wild west mission

**Comment by SonixApache** [comment]
Ah, probably means the NPC syndies come with the wrong magazines loaded. I'll check.

**Comment by SonixApache** [comment]
Checked -- the Wild West map has a bunch of regular 12mm magazines laying around. I'll see if I can mass edit those out.
