### ISSUE TITLE
incorrectly scoped locate allows players to qdel anything

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12189]
#### Description of issue

The `/obj/machinery/computer/diseasesplicer` feeds the input of it's `Topic` straight into `qdel` as seen  [here](https://github.com/d3athrow/vgstation13/blob/a559bcf4e9f3004ad5969e1344680db1f37575a2/code/modules/virus2/diseasesplicer.dm#L131)

```
    if (href_list["grab"])
        memorybank = locate(href_list["grab"])
        analysed = dish.analysed
        qdel(dish)
        dish = null
        scanning = 10
```

**Comment by monster860** [comment]
Are you sure? This will probably runtime error first on `analysed = dish.analysed`

**Comment by 9600bauds** [comment]
This just causes harmless runtimes, no qdeletion happens

**Comment by Exxion** [comment]
It should still be fixed, but yeah it's not as big a deal as this says
It can still qdel any dish though

**Comment by BarneyGumball** [comment]
It feeds the input into `memorybank`, not `dish`.

Searching the entire world for something that is inside the machine is pretty ridiculous though.

**Comment by Exxion** [comment]
Yet again it is shown that I cannot read
But also the PR author can't so I don't feel quite as bad about it

**Comment by ghost** [comment]
`s/PR/Issue` but yes. I'm a dumb.

**Comment by Exxion** [comment]
Turns out I also can't write

**Comment by MadmanMartian** [comment]
Looks like this issue is redundant
