### ISSUE TITLE
Pizza boxes accept arbitrary html

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12194]
#### Description of issue

Pizza boxes can be (ab)used to inject HTML straight into the game by writing on it using a pen and writing your desired HTML into the `input()`

**Comment by Kammerjunk** [comment]
Sure does. Here's a flamboyantly gay pizza featuring sidescrolling text.
![fag](https://cloud.githubusercontent.com/assets/5942183/19368953/df4fbf9a-91a2-11e6-9c5a-5df480fd937f.PNG)
I sure hope you can't put any HTML in here.
That would be bad.

**Comment by SysadminJeroen** [comment]
@Kammerjunk I have made an attempt at injecting [this song](https://www.youtube.com/watch?v=hi9oNYiYmrI), but there seems to be a character limit that I hit.

I could try harder though.

**Comment by Shadowmech88** [comment]
Quick, before someone fixes it.

**Comment by Kammerjunk** [comment]
Still better than injecting LOUD NIGRA RAINBOW RIDE MAGIC MISSILE BEES like we had the couple of days after April's Fools

**Comment by Exxion** [comment]
Rogan?

**Comment by ScrambledSteak** [comment]
All I thought of was writing fake ban messages but that's a funny idea

**Comment by Exxion** [comment]
I'm going to register the shortest domain name currently available and upload various sound files to it with one-character-long (plus the extension) filenames in an attempt to get audio elements that fit within character limits
