### ISSUE TITLE
incorrectly scoped locate allows players to trigger any implant in the game

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12191]
#### Description of issue

Players are able to trigger any `/obj/item/weapon/implant` trough the `/obj/machinery/computer/prisoner` because it's `topic` does not correctly check if the `/obj/item/weapon/implant` is a valid implant.

**Comment by Blithering** [comment]
So the warden can set off nuke ops implants?

**Comment by ghost** [comment]
Yes, any implant in the game can be triggered.
