### ISSUE TITLE
Runtime in striketeam.dm holomap

### ISSUE THREAD

**Issue by j-mie** [d3athrow/vgstation13#12207]
#### Description of issue

When enabling the holomap on a deathsqaud a runtime is caused.
#### Difference between expected and actual behavior

A runtime should not happen and the map should appear
#### Steps to reproduce

Become deathsqaud, enable holomap
#### Specific information for locating

```
Runtime in striketeam.dm,111: Cannot read null.z
  proc name: update holomap (/obj/item/clothing/under/deathsquad/update_holomap)
```

Seems to be this code here

```
for(var/obj/item/clothing/under/deathsquad/D in deathsquad_uniforms)
    var/mob_indicator = HOLOMAP_ERROR
    var/turf/TD = get_turf(D)
    if(D == src)
        mob_indicator = HOLOMAP_YOU
    else if((TD.z == T.z) && ishuman(D.loc))
```
#### Server revision

Latest
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
@JMWTurner

**Comment by PJB3005** [comment]
Pretty sure the static station map holomaps are 100% fucked too.

**Comment by j-mie** [comment]
The static station map seems to work fine on Atlas. I did have to edit the code though because the bar icon and deathsqaud map don't seem to use the offset at all. https://github.com/AtlasStation/AtlasStation2/commit/58eff7788376431e547374a9f8cf606c9e466bd1

**Comment by JMWTurner** [comment]
@PJB3005 The station maps still work perfectly fine.

The deathsquad suit runtime gets fixed by #11903 which has been open for an entire month now.

@JamieH oh, so my feature made it to other coderbases as well?

**Comment by Exxion** [comment]
Atlas is a branch of /vg/ code, so yes

**Comment by PJB3005** [comment]
@JMWTurner when I tried to use them they runtimed trying to read undefined variables.

**Comment by JMWTurner** [comment]
@PJB3005 Are you talking about the suits or the station maps? I tested the station maps today and didn't see any runtime. Do you have logs by any chance?

**Comment by PJB3005** [comment]
Station holomaps.

**Comment by JMWTurner** [comment]
I'll need logs then, it might happen because of something external to the maps themselves.

**Comment by PJB3005** [comment]
Nah, just try to open one. They runtime trying to access an undefined variable on the station holomap object (the one you click on).

**Comment by JMWTurner** [comment]
I compiled on the current Bleeding-Edge to test it again just now and clicked on the one east of arrivals on box but nothing out of the ordinary, and no runtime either.

**Comment by PJB3005** [comment]
Weird.

**Comment by Exxion** [comment]
You know, the runtime logs are just as public as the other logs

**Comment by JMWTurner** [comment]
@PJB3005 I checked the runtime. It seems they come from the portable ones, the ones that silicons use. Furthermore it seems to happen every time a silicon gets destroyed. I understand what's going on now, I'll fix it.

**Comment by JMWTurner** [comment]
@PJB3005 there you go #12238

**Comment by PJB3005** [comment]
I haven't used the silicon ones but the stationary ones have never worked.

**Comment by Exxion** [comment]
> Stationary ones have never worked

You mean they've never displayed the map for you? Because they've always worked for me.
