### ISSUE TITLE
Kneesocks sprite goes over the black skirt sprite (and possibly others)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12201]
(WEB REPORT BY: miningpig REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
>  8df11430ca12583edf49460efe0676c2e02264ec 
> 
> General description of the issue
> I was attempting to become the ultimate waifu, but the kneesocks were clipping over the skirt and it looked bad.
> 
> What you expected to happen
> for the socks to go under the skirt
> 
> What actually happened
> sock over skirt(?)
> 
> Steps to reproduce if possible
> get black skirt and kneesocks from autodrobe
> wear both
> ???

**Comment by Shadowmech88** [comment]
This has been reported before, in #10952.

The only way to fix it without fucking up something else is to shorten the kneesocks sprite.
