### ISSUE TITLE
Screen freezes when Goonchat loads

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12213]
(WEB REPORT BY: morphi REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> cbdc4667dd7cd1be0dab7f53ba92cb79cf953c52 
> 
> General description of the issue
> Game screen freezes when Gooonchat loads if you close the game after joining the round and come back later.

Everything else works fine, I can hear in game sounds, read the chat and use verbs.

> Steps to reproduce if possible
> Join game, close game, relog, play for two seconds before Goonchat loads up and watch the screen freeze.

Happens to me every time I have to quit and come back later, couldn't reproduce in a local server however.

**Comment by Exxion** [comment]
Screenfreeze was seemingly fixed by 512.1425
Also this never had anything to do with Goonchat, probably
