### ISSUE TITLE
Idea for Protolathe Revamp: Splitting it up

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#12217]
We all know the protolathe is a bloated abomination of a machine, so I was thinking this:

The protolathe is divided into several machines, each with access to branches of the current tech tree corresponding to the department it is located in: one for Medbay for medical stuff, one in Engineering for devices like P-ray scanners and other engineering equipment, one in Science for bluespace and robotics equipment in addition to stock parts (which could be shared with Engineering as well), and so forth. 

Weapons other than simple magazines would be available for Security's lathe at code blue and at all of them for code red. If the other departments need to be armed badly enough, it'll be available to them.all; incidentally this would also make lockboxes unnecessary since otherwise the weapons never show up on the menu in the first place. Like how NT experimental tech doesn't show without the disk for it. Circuit imprinters could probably stay as they are for now, they don't suffer from the bloat to anywhere close to the protolathe's degree. 

Now you may be thinking - how will they all be supplied with materials? The answer is simple.  We make another machine in cargo to act as a central resources deposit- all of the lathe subtypes will draw from its stores remotely, thus allowing them to work without miners having to shuttle their materials across the station at any given time and also eliminating competition over materials. 

Each machine will access a fraction of the materials that increases with the quality of its matter bin, though none should be able to use the whole store at once. (I would suggest allowing all other fabricators save for maybe autolathes to draw from this central supply as well, for obvious reasons.) I will note that this does give it a flaw in that if this central deposit is compromised (e.g. bombs) the whole station would be affected; all the more reason to keep it guarded, I'd say. 

I don't have the experience to implement this myself, but to my knowledge it seems to address all the current issues with the protolathe and science being OP perfectly. Your thoughts?

**Comment by Shadowmech88** [comment]
I think it'd be better, for at least _some_ of the protolathe items, for them to be constructed in a more organic way than "push button, receive item."

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88

How would you do that? Do you mean like assembling them like the makeshift weapons from basic parts?

**Comment by FudgePucker** [comment]
Also, maybe add a way to enable code red when there are no heads.
A way for a crew member to request centcom to scan the station for life, if half of the crew is dead, if there are alium weeds everywhere, or the blob gets big enough it will call code red.

**Comment by icantthinkofanameritenow** [comment]
That's a sensible idea, though calculating it might be an issue depending on whether it calculates the trigger number by using the initial number of crew or the number present when the scan begins.

**Comment by Shadowmech88** [comment]
> Do you mean like assembling them like the makeshift weapons from basic parts?

Yes, but not out of pieces of junk.

**Comment by icantthinkofanameritenow** [comment]
So what would you make them out of, pray tell? Details, please.

**Comment by Shadowmech88** [comment]
Stock parts would probably make up some of it. Stuff like console screens and manipulators.

We could also make new items that serve as basic building blocks, with various combinations producing different useful items.

**Comment by icantthinkofanameritenow** [comment]
Could have potential, but better to describe it in a separate issue for the moment.

**Comment by FudgePucker** [comment]
This is somewhat how goon stations fabricators work as well.
They have fabricators for every department, and even some common general access fabricators in tool storage areas.
