### ISSUE TITLE
alien resin membrane + light tile planes are fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12224]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> they combine
> 
> What you expected to happen
> light tile plane effect under the alien membrane
> 
> What actually happened
> they are mixed
> 
> Steps to reproduce if possible
> put a alien membrane over a light tile

**Comment by clusterfack** [comment]
@DrCelt

**Comment by ghost** [comment]
I'm pretty sure this isn't a bug

**Comment by ghost** [comment]
Oh wait yeah it is
