### ISSUE TITLE
Upgrading Sleepers Makes Them Unusable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12241]
(WEB REPORT BY: jalis REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Upgrading the sleepers manually without RPD causes the console screen to access them disappear.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by gbasood** [comment]
It's amazing how fucked up parts upgrades are.

**Comment by BarneyGumball** [comment]
The way they build the console is pretty dumb.  You need to have a free tile on the right side of the sleeper when you build it, or it won't get a console.

**Comment by gbasood** [comment]
yes
that's something I added to fix a separate problem a long time ago
someone can certainly redesign it

**Comment by DamianX** [comment]
fixed by removing the sleeper console
