### ISSUE TITLE
Engineering Borgs cannot change access for Airlocks built with RCD

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12240]
#### Description of issue

When a Engineering Borg tries to change access on a airlock which he wants to build with the RCD, the menu for title and access change opens, but options to change access are nowhere to be found. Only the airlock name can be changed.
#### Difference between expected and actual behavior

Expected: Being able to change a high security airlock's access which needs to be built so that no greyshit could jump through easily
Actual Behavior: No access needed to open the door as access could not be changed with the menu, greyshits jump in
#### Steps to reproduce
1. Pick engineering borg
2. Use the RCD and set it to airlocks
3. Click on the ID icon
4. See that the window only shows the option to change the airlock name
5. Scream as someone steals the cap's shit because he can just enter
#### Length of time in which bug has been known to occur

Not sure how long it actually was in, but I encountered it about six hours from the time I post it, a round in which I was a engineering borg. A admin told me to open a issue at that time. There also was a server update some time where i got this but I tested it out after the update, and the bug still happens.
#### Server revision

8455e57862aebead00ae1c4ec09a06c7eb2c3a65
[Protect Authority Roles From Tratior: 1]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by charmstruck** [comment]
I'm pretty sure I've seen this issue discussed before, but not being able to change airlock access as an engieborg sure makes things annoying

**Comment by PJB3005** [comment]
This is intentional because I didn't want to get shat on for "silicon powercreep". Fixing it is incredibly easy.

**Comment by ghost** [comment]
> This is intentional because I didn't want to get shat on for "silicon powercreep". Fixing it is incredibly  easy. 

Ah, I just thought it was a bug because of admins telling me to report it. But it kind of fucks you over when you need to fix doors.

**Comment by charmstruck** [comment]
> But it kind of fucks you over when you need to fix doors.

The people it really hurts is the crew, barring greytiders
