### ISSUE TITLE
Randomize Headset Channels Every Round

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12242]
It is incredibly hindering to Security when every antag can tune a station-bounced radio to the Sec channel and listen to everything Security is saying regarding their investigation.

I think it'd be better if department frequencies were randomly chosen every round.

**Comment by clusterfack** [comment]
Aw I thought it was a PR

**Comment by kol1th** [comment]
![image](https://cloud.githubusercontent.com/assets/16979948/19426273/005072f8-93f0-11e6-9913-e839f41bb313.png)

**Comment by Sprok0** [comment]
Weren't sec/command frequencies "encrypted" or something at some point, so you actually needed a headset encryption key to listen to them

**Comment by Shadowmech88** [comment]
All channels require an encryption key item for that headset to access that channel via the shortcut.

No channels are inaccessible via station-bounced radio, not even syndicate channels. Assistants can listen into the fucking nukeop channel with a station-bounced radio.

**Comment by BarneyGumball** [comment]
Being able to listen to Nuke Ops is definitely fucking dumb.

Not sure about random channels though.  Rounds with an AI would make it pretty much pointless.

**Comment by Shadowmech88** [comment]
> Rounds with an AI would make it pretty much pointless.

How so?

**Comment by BarneyGumball** [comment]
> Greyson McTide: AI state the sec channel frequency

Sec could arrest the guy, but at that point everyone would know what it is anyway.

**Comment by clusterfack** [comment]
We should hide channels that are encrypted, so that they only get decrypted when their common server gets deconstructed. Then make it so mechanics can make custom encryptipn channels :+1:

**Comment by Shadowmech88** [comment]
The AI can just use department keys via its built-in radio now, right?

Does it even need to be told the actual frequencies anymore?

**Comment by BarneyGumball** [comment]
@Shadowmech88 The AI can just read the frequency straight off the server: http://i.imgur.com/H4GUMVn.png

I agree that you shouldn't be able to access secure channels like Security or Command with station-bounced radios without at least  doing something else first.  Like breaking into telecomms to steal encryption keys or something.

**Comment by icantthinkofanameritenow** [comment]
@BarneyGumball 
Agreed. It makes even less sense that a random station bounced radio should be able to overhear radio chatter from the channesl that are supposed to be restricted to nuke ops, ERT, and so on. Ideally, you could tune into the channel without the key, but unless you have it all you'll hear will be gibberish.

**Comment by SonixApache** [comment]
[WYCI]

**Comment by Probe1** [comment]
Rather than fuck over people that know telecomms lets just be sane and make security & command a protected channel.
