### ISSUE TITLE
Boxstation- Warden Cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12254]
(WEB REPORT BY: luzzgawr REMOTE: 172.93.109.202:7777)

> Revision eae80326599334ffea6687e9a4001fc43d0b537e 
> General description of the issue
> It looks like on the sec cameras for wardens camera console, when using minimap view, that the little green camera icons are shifted way out of place, resulting in AI chamber upload camera to be placed in tcomms, and engineer cameras flat out in space
> 
> What you expected to happen
> Me finding a nice greyshit raiding telecoms for "muh glubs" round start, filling my fat officer quota for the day 
> 
> What actually happened
> Every camera is too far south in minimap view
> 
> Steps to reproduce if possible
> hop on a warden camera console. It could just be my computer. I am not sure.

**Comment by Shadowmech88** [comment]
I haven't seen this in my recent testing of other advanced camera console issues.
