### ISSUE TITLE
Vampire: bat form doesn't remove cuffs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12253]
(WEB REPORT BY: curver REMOTE: 172.93.109.202:7777)
As the title suggests.

**Comment by Allspice** [comment]
also does not remove your clothes

**Comment by Sprok0** [comment]
Also allows passage through walls, which is not a standard bat ability.

**Comment by Mayneez** [comment]
Well guess time to fix all 3, amirite?

**Comment by Exxion** [comment]
What the fuck, Intigracy

**Comment by Intigracy** [comment]
Oops

**Comment by beesil** [comment]
Fixed by #22564

**Comment by Exxion** [comment]
Wow, what the fuck was I smoking?
