### ISSUE TITLE
Make conveyor belts less of a pain to build

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#12250]
Any time you want make a line of converyor belts you need 20+ fucking boards.To much to ask to have master board you hook to a frame then link the belts to this by id etc?

**Comment by AutismSpider** [comment]
Or take the board part out and have them build this way.

Converyor belt frame 3 rods screwier diver the rods and then add 4 cables slap more metal on it or welding tool it to make a belt.

**Comment by jakmak** [comment]
you can use a solder iron/genfab to mass produce the boards but i agree construction of these things is a bitch. I feel that a bigger problem is the fact that it costs 5 metal for a single conveyor so a belt 10 tiles long costs a full stack of metal

**Comment by AutismSpider** [comment]
need acid and glass for that man to much  stuff over all to make a fucking converyor belt

**Comment by gbasood** [comment]
There should be some kind of limiting factor for sure, but it should be having the right tools not having a shitton of resources.
At least if we want people to actually do cargo related things that's how it should work.

**Comment by gbasood** [comment]
WRONG BUTTON NO ONE PANIC

**Comment by ihadtoregisterforthis** [comment]
I think they are less of a pain now

**Comment by Exxion** [comment]
The construction method was completely changed. If anyone still has a problem, open a new issue.
