### ISSUE TITLE
Hivebots multiplying in nullspace

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#12261]
#### Description of issue

Hivebots are replicating at a rapid rate in nullspace, someone said "30 per second" and it seems pretty accurate. I don't know why it's happening. There was no new space vault loaded that round:
![help](https://cloud.githubusercontent.com/assets/5942183/19475457/93082da8-9534-11e6-8d9f-8d7243c6da7d.PNG)
Trying to select a hivebot beacon through SDQL yielded no results.
Here's two pictures of 11000 Strong Hivebots in nullspace. They become so many that they freeze you when you open the Haunt list.
![11143](https://cloud.githubusercontent.com/assets/5942183/19475155/ee5018e4-9532-11e6-9168-f1958afb4c22.png)
When they reached a few thousand, the CPU counter in the Status tab said 120
#### Difference between expected and actual behavior

I'm on hivebot deletion duty because the forces from the Byond are amassing an army worthy of Mordor and it gets taxing if they're allowed to build.
#### Steps to reproduce

Not sure what the requirements are or if it happens every round. If the latter, just wait a minute and then do Haunt and go to the bottom.
Alternatively, select them in SDQL, but it'll take a while for it to load.
#### Specific information for locating

Strong Hivebot: `/mob/living/simple_animal/hostile/hivebot/strong`
#### Length of time in which bug has been known to occur

Don't know for sure. I've only noticed the Haunt lag recently (today and yesterday).
#### Server revision

e0bbe9de1491897aa63e4de6c58d0e43d1250d17
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
I didn't know hivebots even _could_ replicate.

What creates them, normally? The beacon?

**Comment by Kammerjunk** [comment]
Normally a beacon, yeah, which is just `/mob/living/simple_animal/hostile/hivebot/tele`. I don't think anything else can, but I dunno.

**Comment by Shadowmech88** [comment]
I'm looking at the code for the hivebot beacon, and it seems completely incapable of creating strong hivebots. So they must've been coming from something else.

If I remember correctly, the strong hivebots were a recent addition specifically for a certain vault.

**Comment by Shadowmech88** [comment]
The only place in the code where strong hivebots are mentioned, aside from their own .dm, is `maps/randomvaults/hivebot_factory.dmm`.

Maybe try loading that vault specifically during a round and see if the problem happens again, or if it was a fluke?

**Comment by Kammerjunk** [comment]
If so, it's creating them without the vault being loaded, since all the vaults in the round are from longer ago.

**Comment by Kammerjunk** [comment]
Oh, well, actually, that one IS loaded. It's one of the original vaults, I think, but yeah, can try it with and without the vault to see the difference.

**Comment by Shadowmech88** [comment]
My guess would be that the problem is in the general vault spawning/building code, because there's nothing in the hivebots' code that looks like it could cause this.

**Comment by Kammerjunk** [comment]
Looking at it, I don't think it even has a beacon. It's supposed to be like a destroyed hivebot facility.

**Comment by PJB3005** [comment]
> The only place in the code where strong hivebots are mentioned, aside from their own .dm, is `maps/randomvaults/hivebot_factory.dmm`.

I made a vault that involves hivebots too...

**Comment by Iamgoofball** [comment]
@MrStonedOne

CLEANBOT LIVES

**Comment by Iamgoofball** [comment]
For reference we had this happening but with CLEANBOT, for some reason a random proc got replaced with the new() for cleanbots. The main one that got replaced was sound()

**Comment by BarneyGumball** [comment]
Bisecting shows that #12088 is the culprit.  It's also the cause of everyone losing sound at round start.  Keep in mind it only runtimes if the `hivebot_factory.dmm` vault gets loaded.  `ejectedengine.dmm` seems to have nothing to do with it.

```
[02:23:11] Runtime in ,: bad arg name 'wait'
  usr: Strong Hivebot () (/mob/living/simple_animal/hostile/hivebot/strong)
  usr.loc: (nullspace)
Undefined variable /mob/living/simple_animal/hostile/hivebot/strong/var/status
[02:23:11] Runtime in say.dm,254: 
  proc name: play vox sound (/proc/play_vox_sound)
[02:23:11] Runtime in ,: bad arg name 'wait'
  usr: Strong Hivebot () (/mob/living/simple_animal/hostile/hivebot/strong)
  usr.loc: (nullspace)
Undefined variable /mob/living/simple_animal/hostile/hivebot/strong/var/status
[02:23:11] Runtime in say.dm,254: 
  proc name: play vox sound (/proc/play_vox_sound)
```

**Comment by Iamgoofball** [comment]
"runtime in ,"

Goddamn

**Comment by Exxion** [comment]
I love that BYOND bug

**Comment by BarneyGumball** [comment]
This is the cause: http://www.byond.com/forum/?post=2024361&page=2

**Comment by Exxion** [comment]
Wait, but that thread says it was fixed over a month ago
Maybe the server needs to be updated to the newest version of BYOND?

**Comment by MrsTonedOne** [comment]
Either create a /sound/ at world start (and icon because it can happen to those) or update byond

**Comment by gbasood** [comment]
# REVERT #12265 AFTER 511 PLEASE OKAY THAAANKS

**Comment by Shadowmech88** [comment]
I doubt we'll remember.

**Comment by Kammerjunk** [comment]
In either case, I'm told we've updated to 511 so I'll just close this
