### ISSUE TITLE
Mindswapping with silicons may be causing some really weird shit/STOP EDITING CKEYS

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#12268]
Via bobdabiscuit on discord

> Aight
> so what happened at first was some dude was a wizard
> he didnt want to be wiz so kammer swapped me for em
> the previous wizard then became a mommi I think
> which fucked up my borg laws
> and crashed byond
> the wizard I stood in for was swapped out so was most likely a ghost
> not actually playing until he became a mommi
> I was put into their body

So basically his client got deleted on the original wizard's becoming a MoMMI? Maybe?

**Comment by clusterfack** [comment]
\>secondhand bug reports

Please

**Comment by gbasood** [comment]
best we got
anyways it should be easy to test, just check if mind vars arent being changed correctly on admin swapping a person into a body while its occupied

**Comment by clusterfack** [comment]
Also
>almost surely caused by admin intervention

Strike two

**Comment by BobdaBiscuit** [comment]
So I went log diving and this is basically what happened from what I can see.

Yelier becomes a roundstart wiz.
Doesn't want to be wiz.

> [15:17:15]ADMIN: HELP: Yelier/(Nihilus the All Knowing): I don't really want to be wiz, it just selected it at roundstart even when I had my preferences off - heard by 2 non-AFK admins.

Kammer swaps him with me (I was observing)

> [15:37:48]ADMIN: PM: Kammerjunk/(Ginger Beach)->Yelier/(Nihilus the All Knowing): If you really wanna leave, just ghost. Someone will take over
> [15:37:59]ADMIN: HELP: Yelier/(Nihilus the All Knowing): Alrighty then, thanks. - heard by 1 non-AFK admins.
> [15:38:18]ADMIN: Kammerjunk/(Ginger Beach) modified Unknown's ckey to bobda

I become Nihilus the All Knowing and die, I then get borged.
Suddenly after a few hours or so my byond freezes/crashes with [http://i.imgur.com/WEi2mUH.png](http://i.imgur.com/WEi2mUH.png).

As you can see the derelict mommi creation message is shown.
This is when the spaghetti happens.

I can't find the logs of mommi creation but Yelier and I login at the same moment , suggesting we both actually crashed at the same moment (they possibly tried to spawn in as a mommi there).
We are also assigned to the same Mommi, with my borg having no attached ckey anymore.
I am then returned to the game lobby able to join/observe etc.

> [16:57:20]ACCESS: Logout: _no key_/(GRAND WIZARD NIHILUS) (Locker Room - 242,262,1)
> [16:57:20]ACCESS: Login: bobda/(Mobile MMI 64) from [NOPE] || BYOND v510
> [16:57:20]ACCESS: Logout: _no key_/(Nihilus the All Knowing) (Atmospherics - 290,230,1)
> [16:57:20]ACCESS: Login: Yelier/(Mobile MMI 64) from [NOPE] || BYOND v510

And the final bit of fuckery is in the round end screen, it displays Yelier's mommi as having no ckey, my first borg as having no ckey and him as still being the wizard.

[http://imgur.com/a/ZWcKd](http://imgur.com/a/ZWcKd)

Logs are [http://game.ss13.moe/logs/2016/10-October/18-Tuesday.log](http://game.ss13.moe/logs/2016/10-October/18-Tuesday.log), [http://game.ss13.moe/logs/2016/10-October/18-Tuesday%20admin%20only.log](http://game.ss13.moe/logs/2016/10-October/18-Tuesday%20admin%20only.log)

**Comment by gbasood** [comment]
>modified ckey
fucking
no wonder the mind vars didnt swap
