### ISSUE TITLE
Cannot add more than one ingame photo to a piece of paper

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12263]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
If you attempt to add more than one photograph taken ingame with the camera only the first image will appear on the paper and the rest will just disapear.
No message shows up telling you that you cannot add more pictures and no more than one picture is shown.
To reproduce this just use the camera and take a few pictures and place the picture on a paper.

**Comment by Megamaw** [comment]
LOOK AT THIS PHOTOGRAPH
