### ISSUE TITLE
Decal runtimes

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12273]
Point arrows don't disappear, Gibs are acting strangely

![uoi transport tomb v 2016-10-19 142213](https://cloud.githubusercontent.com/assets/9110500/19520262/85aeb590-9607-11e6-85c5-c88f85d2de1a.png)

[06:17:07] Runtime in misc.dm, line 9: type mismatch: 0 += the arrow (/obj/effect/decal/point)

[05:53:49] Runtime in misc.dm, line 9: type mismatch: 0 += the gibs (/obj/effect/decal/cleanable/blood/gibs)

**Comment by Kammerjunk** [comment]
The only thing that seems to be capable of cleaning gibs is soap, except you can still clean the gibs (and footprints) after they're **seemingly** gone. Gibs leave behind a white gib-thing
I'll update this in a few minutes to show what it looks like and whether I can find anything in that turf's contents
Edit: Never mind, it seems that it's not broken every round. I'm not sure what the conditions are.
I'm pretty sure it's a hiccup from 511, though
