### ISSUE TITLE
cant_drop = 1 Does Not Prevent You From Moving an Item From One Hand to Another

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12275]
I've tried to fix it by putting a check in `put_in_hand_check()` but for _some_ reason, I can only get `is_holding_item()` to return a `held_items` index when the item in question is a child of `/storage`, like a box or a backpack.

Using this code:

```
if(W.cant_drop)
    var/I = is_holding_item(W)
    if(I)
        to_chat(src, "You can't pry \the [W] out of your [get_index_limb_name(I)]!")
        return 0
```

Somehow prevents me from switching a `cant_drop = 1` _storage_ item from one hand to the other just fine, yet every other type of item can be moved freely between hands.

I can't figure it out, maybe someone else can.

Also this is what's causing #8492.

**Comment by Intigracy** [comment]
canremove = 0

**Comment by Shadowmech88** [comment]
I'm not sure what you mean by that.

Are you saying I should replace all instances of `cant_drop = 1` with `canremove = 0`?

**Comment by Intigracy** [comment]
probably, come to think of it

**Comment by Intigracy** [comment]
Though I'm not 100% certain it works with dropping things from your hands, was just a suggestion.

**Comment by BarneyGumball** [comment]
Where are you putting this code?  Storage containers don't have normal `attack_hand` procs.

**Comment by Shadowmech88** [comment]
I put it into `mob/proc/put_in_hand_check()` in `inventory.dm line 206`.

@Intigracy 
`canremove = 0` works to prevent the item from switching hands, but does not prevent you from dropping it.
Should I combine the functionality of `cant_drop` into `canremove` and then remove the `cant_drop` variable altogether?

That might be a problem with clothing set to `canremove = 0` in that you will no longer be able to drop it in addition to not being able to take it off once wearing it.

**Comment by Shadowmech88** [comment]
Adding the OP's code to `/obj/item/attack_hand()` causes it to function as intended for normal items, but now it doesn't prevent storage items from switching from hand to hand.

I guess I'll just put the code in both places.

**Comment by Intigracy** [comment]
Mousedrop is different from attack_hand is why it's not working

**Comment by Shadowmech88** [comment]
Where would that proc be located?

**Comment by BarneyGumball** [comment]
@Shadowmech88 It'd probably be better if you added a `put_in_hand_check()` to `/obj/item/attack_hand()`, assuming it won't break anything.

**Comment by Shadowmech88** [comment]
> assuming it won't break anything

I am completely unsure.

The weird thing is, picking an item up _already_ calls `put_in_hand_check()`, as does switching an item from one hand to the other. It's just that `is_holding_item()`, for SOME reason, can't see that you're holding the item if it gets called inside `put_in_hand_check()`, unless said item is a storage item.

**Comment by BarneyGumball** [comment]
Oh no wonder, `obj/item/attack_hand` calls `u_equip` before the `put_in_hand_check()`.

**Comment by Shadowmech88** [comment]
So what's the best solution? Should I have `/item/attack_hand()` call `put_in_hand_check()` _before_ the `u_equip` call?

Currently I've got `cant_drop` checks in both `put_in_hand_check()` and `attack_hand()`, and it works, but I don't know if it's the best method.

**Comment by BarneyGumball** [comment]
That should work.  Just put the check inside the `if(src == user.get_inactive_hand())` block.
