### ISSUE TITLE
spess pets-- missing images

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12289]
(WEB REPORT BY: megamaw REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1c3095d7c457b8db83b9967c698dbf26551ac1f8
> 
> General description of the issue
> Some images are missing or broken in Spess Pets. Including the back-forward buttons.
> 
> What you expected to happen

I kind of didn't expect little 'x'es.

> What actually happened
> 
> Steps to reproduce if possible

Buy Spess Pets at a PDA terminal, boot it up.

**Comment by beesil** [comment]
Fixed by #23251
