### ISSUE TITLE
Really slow speed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12286]
(WEB REPORT BY: enderandutu REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

I start playing as a plasmaman with the mechanic job.
I do the stupid thing of filling my tank with heated plasma and start breathing it, then a whole medical shenanigans happens (check steps) aaand... I suddenly have the speed of a snail.

> General description of the issue

I had the spped equivalent to that of a treeman(while running), while not necessarily one.
Not food nor hyperzine could fix the problem (hyperzine made me a little faster, but it was more like a walking speed).

> What you expected to happen

To get well and return to whatever I was doing.

> What actually happened

Started to move like a snail... while running.

> Steps to reproduce:

-Play as plasma with mechanic job.
-Fill your plasma tank with heated plasma.(dumb thing to do)
-After a while, when effects start to show, take it off.
-Faint.
-Have someone administer dexalin until you wake up (maybe have a medibot help?).
-Wait until you take some damage, enter a sleeper, exit the sleeper.
-Enter a cryo, wait until fully healed, get out, have someone put you in a hemostat regulator.
-Now start breathing plasma again, from the plasma tank which looks like a rectangle.
*Certain steps are unncessary, this how it all happened.

**Comment by Shadowmech88** [comment]
Given the age and mysterious nature of this bug, I think this report can be closed.
