### ISSUE TITLE
Annoying visual bug with metal rods?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12285]
(WEB REPORT BY: foxop REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
>  f7a2e1bae68bc67efbe87f5ff27d592e7e418ea0 
> General description of the issue

Metal rods show up randomly (visual only) in the hand slot presumably if they have been clicked on once. Will also show up above the HUD.

> What you expected to happen

metal rods pls go

> What actually happened

they did not go

> Steps to reproduce if possible

click on a metal rod

**Comment by clusterfack** [comment]
It's part of click drag construction. It even gives you a message in chat. Please.
