### ISSUE TITLE
blindness bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12298]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> if you eat imidizaline while blind it has no effect
> 
> What you expected to happen
> be able to see
> 
> What actually happened
> still blind 
> 
> Steps to reproduce if possible
> be blind
> eat imidazoline pill
> keep being blind

this shit happened 2 times not sure what causes it

**Comment by Exxion** [comment]
@pvak What caused your blindness?

**Comment by charmstruck** [comment]
Eye surgery exists for a reason

**Comment by Intigracy** [comment]
If it was genetic, pills wouldn't fix it.

IIRC if you get to high enough eye damage imi won't work anymore and you need surgery.

**Comment by DeityLink** [comment]
Pretty sure it was genetic blindness.
