### ISSUE TITLE
Parallax doesn't loop (properly, at least)

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#12309]
1. Be a ghost
2. Set speed to max
3. Fly in some direction for half a minute or so. Watch as the upper parallax layer slides off your screen. Continue flying a while longer. Watch as the lower parallax layer also slides off your screen.
4. Fly in the opposite direction to get them back.

Note that this occurs gradually over multiple times the width of a Z-level. Obviously, crossing a Z-level boundary doesn't fix it, though it does affect it somehow in a way I'm not entirely sure of.

@clusterfack

**Comment by DeityLink** [comment]
Should have assigned it to me since I wrote the wraparound part of the code.
