### ISSUE TITLE
Compressed matter implant bug

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12302]
#### Description of issue

Summoning wrapped lockers/crates with a compressed matter implant makes them dissapear
i did this on the test server so i don't know if it works properly on the real server
#### Difference between expected and actual behavior

expected to have a usable locker i can unwrap but it makes it disappear upon clicking
#### Steps to reproduce

> wrap locker/crate
> use implant on it
> activate implant
> clicking object makes it disappear 
#### Specific information for locating

C implant and storage spaces
#### Length of time in which bug has been known to occur

 i have no idea i just decided to test it out
#### Server revision

d285a4411d86d707427ddbe1835ff4ae9ad5c086 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x? ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
I wasn't even aware you could use it on things that aren't items.

**Comment by Exxion** [comment]
Wrapped lockers _are_ items

**Comment by Shadowmech88** [comment]
> Wrapped lockers are items

Why?

**Comment by Exxion** [comment]
Because wrapped packages are items and they're a kind of wrapped package

**Comment by Shadowmech88** [comment]
How are players prevented from picking up wrapped lockers?

**Comment by Exxion** [comment]
`attack_hand()` override, just like projectiles

**Comment by Exxion** [comment]
Wait holy fuck could you use a compressed matter implant on a projectile?
I'm going to grab a fucking immovable rod

**Comment by Shadowmech88** [comment]
You'd have to catch it in mid-flight.
Or during stopped time.

**Comment by Exxion** [comment]
You can just pick up timestopped projectiles anyway
But catching it mid-flight isn't impossible
Just difficult

**Comment by PJB3005** [comment]
1. Have to take a gamble buy for immovable rod in the first place, since having an immovable rod happen is unlikely.
2. Need to have the rod fly JUST by you, on such a large station.
3. Have to be able to click it with JUST the perfect timing.

**Comment by Exxion** [comment]
Obviously it's impractical
But that's not even the issue this report is about

I'm guessing when you say you clicked the wrapped locker, you mean clicked it in your hand
In which case it makes perfect sense it disappeared because it went into you
The compressed matter implant just really shouldn't work on wrapped lockers to begin with

**Comment by Shadowmech88** [comment]
> Nuke Ops
> buy compressed matter implant
> four ops climb into a locker
> wrap it
> last op implants the locker into himself
> becomes a tactical operative bomb

I like it.

**Comment by Exxion** [comment]
PLEASE someone do that before this gets fixed

**Comment by ghost** [comment]
The package is null spaced if interacted with even if you drop it

**Comment by Shadowmech88** [comment]
Tested, the package seemed to drop fine both when unwrapped in-hand or on the ground.
