### ISSUE TITLE
Some mobs still have hands when they probably shouldn't

### ISSUE THREAD

**Issue by BarneyGumball** [d3athrow/vgstation13#12308]
Mobs like mice that shouldn't have hands still do and can use them (kinda).  It means anything that uses `put_in_hands()` (and probably anything that only works on hand checks) works on mice/etc.

So you can, for example, steal a magazine out of a gun.  You can't drop it though, you have to put it into something like a box or back into the gun.

**Comment by JustSumBody** [comment]
I remember giving mice shoe snatch and the shoes taking up space, preventing you from casting it again. Pretty sure resting drops the held item

**Comment by gbasood** [comment]
I thought mouse code prevented you from interacting with just about everything though

**Comment by BarneyGumball** [comment]
Just about everything, but not everything.  There's no protection for verbs, spells and some other miscellaneous interactions that rely on hand checks, not mob type checks.
