### ISSUE TITLE
Stacks of rods/tiles deleting during click+drag building

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12303]
(WEB REPORT BY: archsunder REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> When click and drag building, there seems to be a chance to have your entire stack of materials vanish. As far as i can tell it occurs when you click on a space that already has rods or tiles built on them, and then drag them onto an empty space, but i'm struggling to replicate it.
> 
> What you expected to happen
> Expected to build scaffolding with metal rods click+drag feature.
> 
> What actually happened
> Metal rods vanished.
> 
> Steps to reproduce if possible
> Drag rods in click+drag build mode from scaffold onto empty space (probably)

**Comment by Intigracy** [comment]
#12304
