### ISSUE TITLE
Vox raider objectives don't check properly

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#12301]
Revision 55fdb5475d859309a3931fbda3f2f3d195a20568 
They had the full PA and 20 diamonds on the shuttle
I'm also almost positive they didn't kill or even interact with anyone, but the inviolate objective still failed. Not sure how that one works
![image](https://cloud.githubusercontent.com/assets/19365096/19616079/8b9da830-97d8-11e6-9bae-3422847def12.png)

**Comment by Shadowmech88** [comment]
If memory serves, the PA has to be fully assembled in order to count.

Which is stupid, it should just check to make sure all the pieces are on the shuttle.

**Comment by charmstruck** [comment]
Vox Raider is a mess to begin with. It should be removed until it is fixed or it should be removed completely if nobody is willing to make it a decent mode

**Comment by BobdaBiscuit** [comment]
Can confirm that the checks for stacks of refined mats doesn't work, the round before that had raiders fail with 20 diamonds on board, then some time later failed with 200 glass on board. The 4 emitters check doesn't work either.

What does work though, is the nuke check, so good job.

**Comment by ihadtoregisterforthis** [comment]
I remember hearing that the way the inviolate rule works is by checking any deaths on the station, up to a certain number.

**Comment by ShiftyRail** [comment]
No longer applicable.
