### ISSUE TITLE
Space piano typo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12314]
(WEB REPORT BY: jellyveggie REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5f0d30f647f98a5c066ca3a1a6494bb4c41dbab5 
> 
> General description of the issue
> When a piano is broken, the message that appears when trying to use it contains a typo
> 
> What actually happened
> The message is "That the space piano is broken for good.", Should be either that piano or the piano

**Comment by Exxion** [comment]
I just love how BYOND inserts `\the` before objects referenced in text whether you ask it to or not

**Comment by Exxion** [comment]
(Can be fixed by either removing the "That" or changing `[src]` to `[name]` in the string that says that)

**Comment by Intigracy** [comment]
Yeah, any time you reference something as [src] or [H] or whatever, it automatically adds \the to it.

[src.name] fixes it.

**Comment by clusterfack** [comment]
Unless you use \improper which is what its for iirc

**Comment by DrCelt** [comment]
Space Piano isn't really an improper noun

**Comment by Intigracy** [comment]
No.

You can't use \improper in the middle of something, it has to be at the beginning of a var definition.

```
John shoots [D].
```

If [D] is named `Duck`:
John shoots Duck.

If [D] is named `\improper Duck`:
John shoots the Duck.

If [D] is named `duck`:
John shoots the duck.

```
John shoots \improper [D].
```

Errors.

**Comment by clusterfack** [comment]
@Intigracy Are you straight up retarded?

@DrCelt Then it should be "The space piano is broken for good" and using [src] was right

**Comment by Exxion** [comment]
Uh
No, Intigracy is exactly right
That's how it works

Plus even if it did work, it would be `\proper` that got rid of the the

**Comment by clusterfack** [comment]
Yeah I'm saying the name should have been \improper if we wanted to remove "the" from it anywhere it was used.

**Comment by coldcola** [comment]
I remember this was happening a decade ago with uncapitalized words in DM, would always add 'the' as a prefix, looks like I know why now.

**Comment by Intigracy** [comment]
You mean \proper.

**Comment by Exxion** [comment]
Yeah, `\proper` is the one that removes the the
