### ISSUE TITLE
Surgeries missing from wiki

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12320]
(WEB REPORT BY: megamaw REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)

0b78218edab42bddd7c47b77395c0a364557a74d 

> General description of the issue
> Skeleton surgeries missing from wiki
> 
> What you expected to happen
> Surgeons to know how to reconstruct faces for skeletons
> 
> What actually happened
> Look at wiki
> ????
> 
> Steps to reproduce if possible

Look at wiki

**Comment by Kurfursten** [comment]
Does normal facial reconstruction not work?

http://ss13.moe/wiki/index.php/Surgery#Facial_Reconstruction_Surgery

**Comment by Gef21** [comment]
Is it not just the same steps for regular facial reconstruction but without the incision?

**Comment by gbasood** [comment]
You can edit the wiki if you know the steps yourself
????

**Comment by JustSumBody** [comment]
![image](https://cloud.githubusercontent.com/assets/19365096/19633139/42957032-997c-11e6-8957-0ea24c82b60f.png)

**Comment by Kurfursten** [comment]
@Intigracy pls Needs More Testing we don't even know if you can't use the normal surgery steps yet, it could be human error

**Comment by SonixApache** [comment]
Skeletons don't have faces, can you even do facial reconstruction on one without a face?
Call it a feature and close it.

**Comment by CptWad** [comment]
after some testing
- Skeletons can have their face fucked up
- There is no way of fixing it
- Only surgerys that work are brain removal and bone repair
