### ISSUE TITLE
Can't use a welder to deconstruct "wardrobe" closets

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#12325]
Closets of the type /obj/structure/closet/wardrobe (the metal clothing closets that typically have department clothing in them) can't be deconstructed with a welder
It throws a runtime in closets.dm line 289, null.makeSheets
~~The materials var for the wardrobes appeared to be null, but I can't seem to figure out where it is being set at the closet level or why it's not being set for wardrobes.~~
Actually I see what it is 
`/obj/structure/closet/wardrobe/New()` calls the parent but also adds all its clothes to it. Since the specialized wardrobes are children of it, they can't call the parent without also adding the parent's clothes. So they just add their own clothes and never call the super's New.
Guess the solution is to make the parent wardrobe type an empty version of it and change all the specialized ones to be children of that, but then you'd have to move the default wardrobe clothes to one of those and replace the path in maps.

**Comment by Exxion** [comment]
Or like have a list of starting contents and have it spawn them and null the list in `New()`

**Comment by Intigracy** [comment]
`>overriding New() to not call parent`
Never do this.

Exxion's fix is probably the best option.

**Comment by Exxion** [comment]
Yeah, `New()` is one of a small number of procs that should always, no matter what, call the parent

**Comment by clusterfack** [comment]
Well it doesn't really -HAVE- to
