### ISSUE TITLE
Some doors look closed for a split second before opening fully

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12324]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Wooden, shuttle, confession and other non airlocks appear closed for a second while being opened. It's been around for ages, dunno if there's already an issue about this
> 
> What you expected to happen
> opening a door to look like a door opening
> 
> What actually happened
> I get tricked twice about it's opening twice
> 
> Steps to reproduce if possible
> open door

**Comment by Intigracy** [comment]
If I were to guess, I'd say the Spawn() before switching icon_state is longer than the animation, so the animation is probably looping.

**Comment by clusterfack** [comment]
I remember fixing this at one point?

**Comment by Zth--** [comment]
Yeah I'm 100% sure clusterfack fixed this months ago
