### ISSUE TITLE
MoMMI Fabricator bug

### ISSUE THREAD

**Issue by Sordine** [d3athrow/vgstation13#12321]
Re-entering your body after clicking become MoMMI will not make you a MoMMI, and it makes the MoMMI Fabricator busy building one forever.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
``` DM
    spawn(50)
        if(!user || !istype(user))
            building=0
            update_icon()
            return
        makeMoMMI(user)
```

SHITCODE
