### ISSUE TITLE
HoP headgear in char setup

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12323]
(WEB REPORT BY: 1pirateguy REMOTE: 172.93.109.202:7777)

> Revision 0b78218edab42bddd7c47b77395c0a364557a74d 
> 
> instead of having his regular hat in the char preivew, characters set to HoP wear a EOD hood http://puu.sh/rTC1F.png
> 
> What you expected to happen
> a cap
> 
> What actually happened
> this http://puu.sh/rTC1F.png
> 
> Steps to reproduce if possible
> set your prio to high on HoP dumbus

**Comment by Shadowmech88** [comment]
![image](https://user-images.githubusercontent.com/3991927/47132432-6e603d00-d269-11e8-8408-7f14e9bd0d04.png)
Tested on the test server, seems to work.
