### ISSUE TITLE
Items layered below hand icon if taken out of an inventory

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#12326]
#### Description of issue

If you pick something up off of a table, it's fine:
![from table](https://cloud.githubusercontent.com/assets/5942183/19648590/d5cd9da8-9a02-11e6-9671-77bb89a6c7f9.png)
If you pick something up from an inventory (like backpack or belt), it gets layered below the hand sprite:
![from belt](https://cloud.githubusercontent.com/assets/5942183/19648630/07780bcc-9a03-11e6-9547-53a915b29450.png)
It does _not_ happen when taking an item out of a labcoat
#### Difference between expected and actual behavior

Items in hand become _useable_ (assuming you're on hotkey mode or using ctrl+Y) and still exist, but are functionally invisible due to presumably being layered below the hand icon.
#### Steps to reproduce

Have item in bag or belt, take item into hand.
#### Specific information for locating

Bags:
`/obj/item/weapon/storage/bag`
Belts:
`/obj/item/weapon/storage/belt`
Labcoats:
`/obj/item/clothing/suit/storage/labcoat`
#### Length of time in which bug has been known to occur

Recent. First heard complaints about it last round (round started 04:20:07 server time or about 2 hours and 40 minutes ago, round before that started 02:53:03 server time or about 4 hours and 10 minutes ago).
#### Server revision

76edc74b43cccf8046a4b759d52ce3a8a313c52c
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched for "invisible" and "hand"

**Comment by Exxion** [comment]
Someone seems to have fucked up storage items. (The labcoat isn't a storage item. It uses copypasted storage item code.) They also don't always update properly when you put something in them.
