### ISSUE TITLE
Cloning two players at once results in shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12327]
(WEB REPORT BY: nukas REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 76edc74b43cccf8046a4b759d52ce3a8a313c52c
> 
> General description of the issue
> Put someone in the cloner, scan, clone. If you then put another body in and scan and clone, the first clone will be stuck in the cloning pod and cannot be retrieved.
> 
> What you expected to happen
> Either the cloner should reject a new cloning process while there's already an ongoing one or it should eject the first body when a new cloning process is initiated.
> 
> What actually happened
> The new clone proceeded to work as intended, but the first one sort of disappeared. The player became conscious but couldn't be seen (his voice came out of the cloning pod). He couldn't be ejected and the pod seemed to be empty. Deconstructing the pod didn't eject his body either.
> 
> Steps to reproduce if possible
> Put a player in the cloner and clone it, then put another player in the cloner and clone it while the first clone is still being made.

**Comment by Exxion** [comment]
Oh hey, I'm pretty sure someone reported "becoming the cloning pod" before but wasn't specific enough for us to know how to reproduce it. So that's one mystery solved.

**Comment by DarkDibblez** [comment]
Should be an easy fix, I'll look into it
