### ISSUE TITLE
Spacepod window collision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12335]
(WEB REPORT BY: deussex REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> fly spacepod into a window on research outpost. 
> It gets stuck in the window, can't move, but still draining power as i try to fly it out
> 
> What you expected to happen
> Not collide in the first place
> 
> What actually happened
> Flied into window, spacepod gets stuck
> 
> Steps to reproduce if possible
> fly a constructed spacepod into the northwest window of the xenoarch spectrometer room

**Comment by Exxion** [comment]
#7111
