### ISSUE TITLE
Crippling emitter/blob issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12336]
(WEB REPORT BY: sprok REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b798ff8691b1c79c88d6b633cee3f113736d3967
> 
> General description of the issue
> Emitter beams, after destroying a tile of blob, stop in place and don't move forward to the next. If a blob expands into the now empty tile, it does not get damaged by the beam next to it.
> Normal blobs that are being damaged by an emitter, when turned into strong blobs, stop taking damage.
> 
> What you expected to happen
> Emitters to bore holes through blobs
> 
> What actually happened
> They don't
> 
> Steps to reproduce if possible
> Spawn a blob core, point emitters at it

**Comment by gbasood** [comment]
prob beam runtimes tbh
beams were a mistake
