### ISSUE TITLE
Metaclub Z1 Holomaps don't seem to be showing up 

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#12339]
Revision dbfc25a042ca245bac2d417cb0e4e1b33fc3b455 

Trying to view holomaps as silicons/the wall mounted maps gives the "map not found" screen and the "The holomap failed to initialize. This area of space cannot be mapped." error in chat. 
Interestingly enough, spawning in the stock holomap_chip seems to show it.
So far I'm only seeing this happen with Z1 on metaclub, other z-levels seem unaffected. Would need to double check the other maps when I get a chance.

Likely caused by #11903

**Comment by clusterfack** [comment]
@JMWTurner
