### ISSUE TITLE
Give pAIs the abilities of a chem dispenser (with some drawbacks)

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#12349]
Currently, pAIs can only make coffee, tricord, and smoke, at a very slow rate, which severely pales in comparison with borers.

Borers can instantly put any specific amount of chemicals into their host instantly, but their drawback is that they can only do it with a limited amount of chemicals.

In comparison, I suggest that pAIs should be able to make any chemical that can regularly be made by a Chem Dispenser, however they keep the already existing charging time for each chemical, as well as only able to add them in small amounts each time. This would also have an indirect drawback as bodies aren't meant to act as long-term mixing bowls, slowly metabolizing chemicals already placed in them, whether or not the pAI is finished creating the specific chemical they have in mind.
Also chemicals that use reagents that are dangerous to people would probably not be viable, since it would kill your host before you are able to finish making it.

This would also fit in a gameplay perspective, where biological beings like borers are able to extremely and efficiently make a limited amount of chemicals, while mechanical technology would be able to make any chemical, although very inefficiently.

<sup>Also this would make more people want to play pAIs, as well as make people want pAIs more</sup>

**Comment by sonime** [comment]
Anything special aside from just being able to make base reagents like a chem dispenser? What about things like coffee or paismoke?

**Comment by chatsonf** [comment]
Is paismoke different from regular smoke? If not then you can just manually make regular smoke like before

wait oh god that would be blood smoke wouldn't it

**Comment by chatsonf** [comment]
Should be fine for pAIs to keep the previous chemicals that they could make before along with all the chem dispenser ones.

**Comment by gbasood** [comment]
_if_ we wanted to do this you could allow the pAI to dispense to two separate containers and combine them together at will.

I mean, this would allow players to carry living bombs with them, but on the other hand, **BORERS LITERALLY DO NOT STOP WHEN THEIR HOST DIES**

**Comment by Shadowmech88** [comment]
> wait oh god that would be blood smoke wouldn't it

The blood container is separate from a player's normal internal reagent container.

**Comment by sonime** [comment]
Paismoke is it's own chemical, I think it's even the first one in the .dm file too.

**Comment by AutismSpider** [comment]
paismoke is its own thing needs a host to set it off any way

**Comment by Exxion** [comment]
The paismoke chem just turns into the ingredients for regular smoke when in a mob

**Comment by Blithering** [comment]
Personally, I reckon pAIs should be buffed in other ways, let borers keep the title of best chemical dispensers.
