### ISSUE TITLE
Uplinks exist as objs on both box and deff when they should be using a landmark

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#12347]
```
world: Error(Cannot read null.mode (/exception))
Hidden Uplink. (/obj/item/device/uplink/hidden): New(the uplink (/obj/item/weapon/implant/uplink))
the uplink (/obj/item/weapon/implant/uplink): New(the implanter (/obj/item/weapon/implanter))
Uplink Implant (with injector) (/obj/item/weapon/storage/box/syndie_kit/imp_uplink): New(the floor (96,124,2) (/turf/unsimulated/floor))
```

Did some fixing of that error output and basically what's happening is `ticker` is null before the uplink's `New()` happens i.e. the obj is instantiated before ticker is

``` DM
/obj/item/device/uplink/New()
    ..()
    welcome = ticker.mode.uplink_welcome
    uses = ticker.mode.uplink_uses
```

![](http://i.imgur.com/pktZ41O.png)
![](http://i.imgur.com/6yLzBgD.png)
![](http://i.imgur.com/XWVn1ua.png)
WHOOOOOOO

**Comment by gbasood** [comment]
This is also happening with an emag on meta club

``` dm

[13:56:47] Runtime in cards_ids.dm, line 99: Cannot read null.emag_energy
proc name: New (/obj/item/weapon/card/emag/New)
src: the cryptographic sequencer (/obj/item/weapon/card/emag)
src.loc: the floor (101,122,2) (/turf/unsimulated/floor)
call stack:
the cryptographic sequencer (/obj/item/weapon/card/emag): New(the floor (101,122,2) (/turf/unsimulated/floor), 0)
```

**Comment by gbasood** [comment]
OH AND IT HAPPENS WITH SPC 294 AS WELL
WHO FUCKED WITH CENTCOMM

**Comment by Probe1** [comment]
This seems really nasty.  Creating spawners for 3 objects and mappers should just know to use those spawners instead of the regular objects.  I foresee no one knowing that they should have done that in the first place and the issue coming up again in the future even if fixed with landmarks today.

**Comment by Exxion** [comment]
OK first of all I'm talking out my ass but second of all isn't this what `initialize()` is for?

**Comment by Probe1** [comment]
After taking a crack at it and failing I'm gonna go ahead and let a coder write this landmark and pass it on.  I don't have the interest in fixing it all.  I'll do the mapping bit sure.

Do the needful.

**Comment by Intigracy** [comment]
This is pretty easy to do.
Take everything in the New() proc and instead put it in initialize()

**Comment by Probe1** [comment]
Do it then monkey

**Comment by Intigracy** [comment]
What a rude dude.

**Comment by Probe1** [comment]
codemonkey gets banana
