### ISSUE TITLE
Improve trader

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#12348]
Trader is currently a flawed job in quite a few ways.
- Traders often use the job pretty obviously incorrectly, instead travelling to the station to perform as an assistant/shitter early on or be part of the crew. This is in direct contrast to the idea of the job and worsens the experience for everyone, especially traders who are attempting to actually trade. The worst offenders are ones who simply act like Vox Raider antags and steal everything that isn't nailed down. It's just sad to watch and gets good traders arrested/killed by misled Security.
- There just aren't very many trade goods on the Vox Outpost. Yes, there are many items, but at some point they become bland; autolathe products, food and plants (from a decently limited selection unless you no-fruit it up), and some medical items, as well as the obvious flash/flashbang/handcuff trio that any Assistant wants to get his hands on. Overall, after playing the job a few times, it just gets hard to trade new and interesting things. This is exempted moderately on Meta and Defficiency, but those outposts have problems of their own in finding good trade goods. Overall it's the worst on Box, despite having the best layout for botany and cooking.
- Getting more of the 'rare' and fun incentives in a round, like items from random space z-levels or mining rewards, is extremely tedious and unrewarding with the starting equipment. Your only space exploration gear is a shit hardsuit and a few jetpacks, and unlike normal space explorers, you're expected to be able to get back to the outpost with your loot in a timely fashion. Since it's all based on RNG, most rounds you will end up spending 40 minutes getting a few cool objects, and either the round has ended or some other terrible thing has happened to the outpost/the shuttle/your fellow traders/the crew. If you even manage to get back.

I have heard a few solutions to these problems that might help:
- Spawning random items and presents on all outposts, like the crates on Defficiency or the presents on Meta Club. If this is too inexact or the items not varied enough, make a new item group for traders that spawns in a few boxes with enough stock to last, OR make a sort of vending machine with a random stock that can only be used a set number of times. Here's the idea on the thread, not mine:

> Trader balance idea
> new vending machine on the outpost
> has randomized contents each shift
> each trader starts with a special coin, allowing them to get one item from the vending machine
> the vending machine items would be things the crew would want, not always things that traders would want themselves
> 
> marauder boards
> vial of Peridaxon
> vial of Mednanobots
> RPD full of high tier parts
> box of artificial blue space crystals
> banarium juice
> paper with the location of a genetics power block
> reinforced plasma glass
> etc etc
- A spacepod, possibly low quality, would allow for space exploration. I'd ask for some sort of GPS system and telescience to go with it so that explorers aren't relying on luck to get back, but I know that's probably too much.
- Jobban people who play Trader badly. There should be slightly more defined rules for the job-- a Trader should realize a space station isn't their home, at least unless circumstances change somehow. A Trader should also realize that they aren't a Raider and stealing things is decidedly shitty and contrary to the actual fun parts of the job, which is providing money/valuables for yourself in exchange for goods the crew currently can't/don't have.

That's all I got thanks

**Comment by Durgen** [comment]
Some of what you outlined is more of an admining issue, and should probably go in the forums.

I think a new spawner that selects from a list of nifty items would be the easiest way to fix the lack of trade goods. This would be the easiest way to approach the issue.

The advantage of a vending machine, is the amount of trade goods would scale to the number of traders.

Also it would be nice if someone revived https://github.com/d3athrow/vgstation13/pull/11441

**Comment by Zth--** [comment]
Oh man the vending machine idea is soooo nice. I'll see if I get a working version tomorrow

**Comment by kilozombie** [comment]
@Zth-- 
Any luck so far? Thanks for taking an interest

**Comment by Zth--** [comment]
Not yet, I've been working with robots components. This is the next thing in my todo list

**Comment by kilozombie** [comment]
Cool, I saw that PR. Good luck with it

**Comment by Kurfursten** [comment]
Basically all of this has been implemented now, reopen if you still have FRs
