### ISSUE TITLE
Any-Mode for WASD doesn't work

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#12358]
#### Description of issue

Any-Mode for Hotkeys seems to be broken for WASD
#### Difference between expected and actual behavior

```
    Ctrl+a = left
Ctrl+s = down
Ctrl+d = right
Ctrl+w = up
```

These should all work; none of them work now, you have to actually toggle hotkey mode on and off.
#### Steps to reproduce

Try any of the above shortcuts
#### Length of time in which bug has been known to occur

Today
#### Server revision

d9c649295cda19adfdd311b6adf02c36361dec94 Current Infomational Settings: 
Protect Authority Roles From Tratior: 1
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by nuklearcellphoneg** [comment]
I-I don't know how to play without wasd please send help.

**Comment by Exxion** [comment]
Wait
You actually play by holding Ctrl and using WASD?

**Comment by Iamgoofball** [comment]
Jesus Christ who holds ctrl to move

**Comment by nuklearcellphoneg** [comment]
Yes, so I don't have to toggle hotkeys on and off. :(

**Comment by Shadowmech88** [comment]
> so I don't have to toggle hotkeys on and off

Why not leave hotkeys toggled on?

**Comment by nuklearcellphoneg** [comment]
Then I can't type.

**Comment by Shadowmech88** [comment]
You know the T key brings up a chat box where you can type messages, right?

**Comment by Intigracy** [comment]
This is completely unrelated to the bug report.

**Comment by Exxion** [comment]
No fun allowed
