### ISSUE TITLE
Give SPS/Siren Helmet to Beepsky and optional SPS/SirenHelmet step when making Securitrons

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#12366]
Upgrading grandpa beepsky with security new toys to make security aware of it's death and a cool new helmet to meme harder when rolling after perps <s>WOOP WOOP! PREPARE FOR JUSTICE!

**Comment by SonixApache** [comment]
Riot beepsky and russian beepsky for the different helmets we have while we're at it
