### ISSUE TITLE
Greyling to grey does not work at all.

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#12367]
I want you to go onto a test server, spawn in a grey, revert them to a greyling and then try putting them back to normal. 

I gotta say it is cute to run around as a tiny grey in red shorts.

**Comment by ghost** [comment]
Well fuck

**Comment by ghost** [comment]
The greyling to grey turns them into a human (Which is an oversight I can fix in like 1 line and already have the changes ready to go) but I just can't get my head around why it force ghosts the monkey rather than transferring the mind

**Comment by gbasood** [comment]
@Skullyton this happens with MoMMis too, there's flag on minds that prevents them from transferring when transfer_to is called
IF it is related to that and not just something else bad happening

**Comment by clusterfack** [comment]
Look up some of the old mommi fabricator bugs that were this exact same cause

**Comment by gbasood** [comment]
``` DM
    if(active)
        new_character.key = key     //now transfer the key to link the client to our new body
```

this
https://github.com/d3athrow/vgstation13/issues/10795
it's not a bug, but that variable doesnt usually do what it's intended to do except in the case of aghosts I think

**Comment by MadmanMartian** [comment]
Unable to reproduce. Grey > Greyling and Greyling > Grey all worked flawlessly

**Comment by carshalash** [comment]
Nigga its been nearly a year of course its fixed by now.

**Comment by MadmanMartian** [comment]
Somebody's gotta check the open issues to see which are closeable
