### ISSUE TITLE
Spider queens will get stuck on things they can't break or move around when trying to break bulbs, and ignore everything else to do so

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#12364]
![](http://i.imgur.com/D0PHLSc.png)

**Comment by Shadowmech88** [comment]
Tested, still exists. Putting a spider queen in front of a light surrounded by consoles rendered it completely docile.
Though, is this just a problem with spider queens, or with all mobs who attempt to attack things they can't get to?

**Comment by Pathid** [comment]
Mobs in general probably. Most don't have a frustration mechanic in their AI, but there's a couple that do. In fact spider queens themselves do, but it specifically applies to stuff that's targeted for cocooning.
