### ISSUE TITLE
feature request: add a tokamak core and fuel injector to deff.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#12374]
They get the circuit boards for them, the gyrotrons, and the rust partially done. Give them the last two major road blocks.

The circuit boards are just two giant middle fingers. You need to get tier three stockparts , so you are cockblocked by research. "Here's the circuit boards, so now you don't need to plead science to get them, all you need is a long list of specific tier three stock parts that you need from science."

"B-b-but muh interaction"
I tried making a R-UST two times on deff. I had problems with science BOTH TIMES, BACK TO BACK ROUNDS OF SHITTERS IN SCIENCE.
First time I had waited for some one to come, miners didn't get matierals. Second time same round I was waiting in front of research after ringing their bell for a long time, some guy came in, ignored me, printed out shit for himself and left. So I had to break in myself to print out the parts.

Why the fuck is half of the difficulty of setting up the R-UST hoping that you aren't fucked over by the retards in science? (Another third being hoping you have enough time to get it turned on before shuttle call)

Xenobio doesn't have to suck cargos dick to get gold slime cores. Why the fuck do engineers get shafted and have to deal with the feature dump shitter department to do something fun?

Seriously, does anyone have any objections to this, besides the shitty forced interaction?

**Comment by Shadowmech88** [comment]
What the hell is a tomohawk core?

**Comment by Sprok0** [comment]
I assume he means the tokamak

**Comment by FudgePucker** [comment]
Shit my bad.
I edited the title so at first glace I don't look like a total fucking idiot.

**Comment by AutismSpider** [comment]
better off grabbing the build core form cargo for 100$+the other missing parts

**Comment by ComicIronic** [comment]
I N T E R A C T I O N

**Comment by FudgePucker** [comment]
Fuck science.
Why should anyone have to deal with a department that is filled with shitters 110% of the time?
Every fucking round I play where I have had to deal with research and robotics has been a god awful experience.

**Comment by Probe1** [comment]
I call it a tomahawk core too because I think that is more fun.

Also I'm not doing it.   I already built the framework for the R-UST and gave you all the boards.  That is an incredible head start that has lowered the entry bar.  Lowering the requirement to build the R-UST doesn't mean I'm going to just set it up for you entirely.  You can

1.  Order it from cargo

2.  Ask for parts from science.

3.  Convince someone else to map you an ezcheeze setup so you don't have to do any of the work.

**Comment by FudgePucker** [comment]
Okay that seems fair enough.
I should have gone to cargo instead of science in hindsight.
