### ISSUE TITLE
Separate Attack Delays For Each Hand

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#12370]
Currently all hands share an attack delay, which means if you attack with a sword in your right hand, you're prevented from attacking with the knife in your left hand until the first attack's cooldown finishes.

What do people think of the prospect of each hand having a separate attack delay, making dual-wielding weapons a viable strategy?

**Comment by AutismSpider** [comment]
end up with people making binds/macros to go fist of the north-star on people.

**Comment by JustSumBody** [comment]
Add dolphin diving to go full John Woo

**Comment by Intigracy** [comment]
ORA ORA ORA ORA ORA ORA ORA ORA

**Comment by sonime** [comment]
Greyshit with TWO toolboxes, Horror of the Maint Monster, coming soon to an Entertainment Channel near you!

**Comment by ghost** [comment]
harmbatonat60rpm.jpg

**Comment by DarkDibblez** [comment]
I would vote against completely separate cooldowns, but having your opposite hand have a slightly lower cooldown (which is extended to your original hand's cooldown if an item switch happens) might be okay? That way there's still a benefit and it stops people from doing 2 attacks at once.

**Comment by jknpj** [comment]
H I G H L A N D E R

**Comment by gbasood** [comment]
double gun
when 2 taser shots per second isnt fast enough

**Comment by Shadowmech88** [comment]
@DarkDibblez

Like a cooldown gets applied to both hands when you attack, but the cooldown on your off-hand is slightly shorter?

**Comment by DarkDibblez** [comment]
@Shadowmech88 Exactly.

**Comment by clusterfack** [comment]
I dont like this. Seems like just adding more effort to maximum powergame. Also seems like it would be abused by macros or such.

**Comment by DeityLink** [comment]
rip
