### ISSUE TITLE
Gasses vanish

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12387]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> After a gas reaches -263C in a pipe it vanishes.
> 
> What you expected to happen
> I expect gasses reaching 1 Kelvin and not vanish from the pipes
> 
> What actually happened
> 
> Steps to reproduce if possible
> Just cool plasma in a closed loop

**Comment by FudgePucker** [comment]
Whoh, can some one test this? I thought 4 kelvin was the lowest limit.

**Comment by ReindH** [comment]
![what the fuck](https://cloud.githubusercontent.com/assets/23237185/19965025/51df1376-a1c5-11e6-958c-3b0bd2c326fc.png)

Should have uploaded this earlier but im a lazy turd.

**Comment by Shadowmech88** [comment]
Was gas being pumped into those pipes? I notice the mol count jumps back up right at the end there.

**Comment by ReindH** [comment]
No, the 2 pumps coming from the miner were turned off, the one up there is on so the gas can move to cool even more, despite the sudden jump in mol count soon after that it plummeted to almost zero mol.

**Comment by ReindH** [comment]
I could remake the situation if needed later this day just tell me what specifics you need.

**Comment by gbasood** [comment]
@ReindH we need specific steps to reproduce it so we can find out what's going wrong and WHEN it's going wrong

literally step-by-step tutorial on how to fuck it up, leave no step out

**Comment by ComicIronic** [comment]
Could be !FLOATS!

**Comment by ReindH** [comment]
I can't seem to recreate the issue anymore, sorry for wasting your times.

**Comment by DamianX** [comment]
I remember something similar to this was fixed in one of the ZAS refactors, @Exxion ?

**Comment by Exxion** [comment]
I think I see the issue there, but I'm not sure. HE pipes used to leak gas into the void at an alarming rate if they were in a room that had very low but nonzero pressure. Three of the HE pipes there are over non-space tiles.

Also -263 is ~10K, not 1K, so the temp checks out
