### ISSUE TITLE
Self Surgery

### ISSUE THREAD

**Issue by Sordine** [d3athrow/vgstation13#12397]
If you stand on the same tile a table is on you can do surgery on yourself.
Here's a webm: http://puu.sh/rZjmV.webm

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Does the table have to be flipped? Does it work if you just build a table underneath yourself?

**Comment by Sordine** [comment]
Either flipped or building one under you, just need to be on the same tile.

**Comment by Allspice** [comment]
FEEEAAAAATUUUUREEEE

**Comment by BarneyGumball** [comment]
Did you just chop your own head off and reattach it?

**Comment by Shadowmech88** [comment]
He did chop his own head off, but he revived using the rejuvenate admin verb.

**Comment by jknpj** [comment]
Robust, i like it.

**Comment by ghost** [comment]
Oh my god it's perfect.

**Comment by jakmak3** [comment]
DELETE THIS
