### ISSUE TITLE
IRA-Approved IED IED-a (haha kill me)

### ISSUE THREAD

**Issue by ScrambledSteak** [d3athrow/vgstation13#12398]
We should be able to jam metal bits and pieces into our IEDs so we can turn them into nail bombs. I guess they'd spit projectiles everywhere and deal damage to people (embedded items when). Perfect for becoming space's newest IRA member.

**Comment by Shadowmech88** [comment]
> jam metal bits and pieces into our IEDs

What about a potato?

**Comment by troots** [comment]
since i can put ian and runtime onto bolas, i suspect it's going to be the same with this concept ok???

**Comment by jknpj** [comment]
Cultist bombs jammed with soul shard pieces when?

**Comment by SonixApache** [comment]
isn't embedded items a thing with bullets?

**Comment by DamianX** [comment]
it's a thing
