### ISSUE TITLE
Skeletons can no longer drink milk

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#12390]
#### Description of issue

Skeletons are no longer able to drink milk.
#### Difference between expected and actual behavior

As per any food, anything a skeleton ingests goes right through them. This includes milk, which used to have a special interaction with skeletons.
#### Steps to reproduce

Acquire a glass of milk as a skeleton, and attempt to drink it. It splashes on the floor.
#### Specific information for locating

Glass of milk
The contents in the glass of milk fall through and splash onto the ground, what a mess!
#### Server revision

f5f8644ab9e46e09b019da24d83b963e18306d37
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
If it did have a special interaction with them in the past, it's been quite a while since it worked

**Comment by AutismSpider** [comment]
have redo the interaction now.

**Comment by SonixApache** [comment]
the obvious answer is to remove skeletons
