### ISSUE TITLE
Ketchup thing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12393]
(WEB REPORT BY: gef21 REMOTE: 172.93.109.202:7777)

> Revision f5f8644ab9e46e09b019da24d83b963e18306d37 
> 
> General description of the issue
> someone make a bug report for me
> gravy, cinnamon, soy sauce and ketchup don't add to your hunger bar anymore ever since dylan fucked them
> ketchup is effectively just water and this is a SIN
> 
> What you expected to happen
> gravy, cinnamon, soy sauce and ketchup add to your hunger bar
> 
> What actually happened
> gravy, cinnamon, soy sauce and ketchup don't add to your hunger bar
> 
> Steps to reproduce if possible
> gravy, cinnamon, soy sauce and ketchup

**Comment by Probe1** [comment]
Can confirm, issue still present.  Why did you let dylan touch things?

**Comment by ComicIronic** [comment]
Because we were desperate

**Comment by Eneocho** [comment]
seems to be fixed
