### ISSUE TITLE
Time to fix the pneumatic cannon

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#12400]
Fact that you can fire glass shard and do 300+ damage is dumb.

Fix how the damage works or put it in a lock box

**Comment by Skullyton** [comment]
180 is the cap, still dumb however

That's moreso just from a small oxygen tank than you can get from a 1GW railgun

**Comment by AutismSpider** [comment]
can do 200+ easy on unarmored spots (need test the glass to see if its good one or not like you do with spears) 50 to 100 to people in sec hard suits/miner suits.

Even point this out in the gun PR people will move on form using guns to next brain dead thing happens to be this all you need is a cold tank of gas  and glass shards.

**Comment by TheFriggenSawbones** [comment]
#11621 has more info on it

but yeah it needs to be nerfed.

Instant killing wizards/any antag is really really lame considering how you don't need to put much work into it.

**Comment by Exxion** [comment]
More like pneuMAGIC cannon am I right my dudes

**Comment by whorena** [comment]
I did a lot of playing around with the Pneumatic Cannon a while back, a lot of what I discovered is outlined in #11621 but I'll just throw it out for people who don't want to sit and scroll through all that junk.
Any w_class_tiny item jammed in the barrel will do insane damage when fitted with a full large blue oxygen tank at 50% output pressure. 
Glass or Plasma-Glass shards can hit up to 290 damage. (However, it's semi-random I believe, they have like a strange 'hit-rate' where sometimes they just fail to connect and do no damage what so ever.)
You can also load skulls and null-rods to do over 200 damage each. Screwdrivers can also do >100 damage.
A lot of very, very common items can be jammed in and used to just murder people without even having to try, and it fits a lot of them at once. 
Using glass shards, you can get 3-4 instant-kills from the Pneumatic cannon, and you only have to wait a short while on the cooldown. It only takes 250kpa to actually deliver a shot which is completely fatal, doing about 150 damage. So a 1013kpa tank can be fiddled around with to get that easily.
Oh, and you will kill people through sec hardsuits too. Not sure about riot armor, but I even used AME fuel tanks once and gave people such bad internal bleeding they died in 10 seconds through anything.

**Comment by Exxion** [comment]
Armor protection against thrown items/the pneumatic cannon is based on a diceroll. Two, actually. Each uses the armor's melee protection as the probability for the check to pass. If both checks pass, the wearer takes zero damage from the thrown/fired item. Otherwise (yes, even if one of the checks passes), they take the full force.
So you have a 1/[melee protection]<sup>2</sup> chance of taking no damage, and 1-[that] chance of taking full damage
That means you have ~1/3 chance of one-hitting someone IN DEATHSQUAD ARMOR with the cannon

**Comment by Sprok0** [comment]
I've found what is probably the maximally damaging item to be used in the pneumatic cannon, it's the "unstable goo" items that get spawned in your hands from some virus symptom. They're w_class tiny, and have _30 throwforce_, a full tank at 50% did 440 damage to an unarmored human.
![goo](https://cloud.githubusercontent.com/assets/19806447/20035625/dd47d82c-a3c2-11e6-8b29-8a8ef110cfc1.png)
