### ISSUE TITLE
Bank security as a character preference

### ISSUE THREAD

**Issue by ammy55** [d3athrow/vgstation13#12401]
Please make bank security settings a character preference saved between rounds. It's super annoying have to go to the ATM every round to change it to just use my ID.

**Comment by SonixApache** [comment]
this

**Comment by charmstruck** [comment]
Yes, this would be much appreciated

**Comment by gbasood** [comment]
I think the only reason to not have this is because if someone figures out your PIN one round and has a metagrudge they could empty out your account every round.
But you deserve it if someone figures out your PIN tbh and metagrudging itself can be handled by admins
so 👍

**Comment by SonixApache** [comment]
PINs can still be randomized, I just want to be able to have my security level on 0 from roundstart.

**Comment by beesil** [comment]
Closed by #19547
