### ISSUE TITLE
WHO FUCKED WITH THE LIGHTS

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#12414]
WHO DID THIS, WHY DO THIS, FUCK YOU WHO EVER DID THIS!!!! 

We use fluorescent lights, THEY SHINE WHITTTTTTEEEEEEEE NOT FUCKING BLUE LIKE CRAPPY LED LIGHTS

NOW
![image](https://cloud.githubusercontent.com/assets/5650556/19839981/b2d9544e-9ec2-11e6-95e1-9af0cc66b32f.png)
BEFORE
![dreamseeker_2016-09-23_18-30-49](https://cloud.githubusercontent.com/assets/5650556/19840034/c8e442d4-9ec3-11e6-9564-501e638c388b.png)

Can not play till fixed

**Comment by PJB3005** [comment]
Pretty sure this is working as intended ™️

**Comment by kol1th** [comment]
@PJB3005 wasn't like this until very recently

**Comment by Exxion** [comment]
Yeah no the tubes are supposed to always be white, standard bulbs are supposed to be slightly yellowish, and HE bulbs are supposed to be white

**Comment by Intigracy** [comment]
blue tint was removed

**Comment by The-Albinobigfoot** [comment]
> WHO DID THIS, WHY DO THIS, FUCK YOU WHOM EVER DID THIS!!!!

ftfy

**Comment by Intigracy** [comment]
Lighting will be as normal on the new round.
