### ISSUE TITLE
antag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12416]
(WEB REPORT BY: bullybeatdown REMOTE: 172.93.109.202:7777)
My antag preferencess wont reset or submit pls help?

**Comment by uazuaz** [comment]
some days ago i had the same issue; no matter what button i was pressing to save (submit/save slot/save setup), the new settings for antag roles didn't save.

today i cleared the cache, joined the server and it works with the "submit" button.

**Comment by gbasood** [comment]
Maybe there's old cached JavaScript or something, then, in this  case?
