### ISSUE TITLE
Become MoMMI does nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12410]
(WEB REPORT BY: socket REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b595d03886ee99d103c2645236687dee6b984e6 
> 
> General description of the issue
> Clicking on the spawner or using the "Become MoMMI provides the confirmation that dialogue, "Do you wish to be turned into a MoMMI at this position?"
> But nothing happens if you say yes.
> 
> What you expected to happen
> Become a MoMMI
> 
> What actually happened
> Stayed a ghost
> 
> Steps to reproduce if possible
> Observe
> try to become mommi on derelict
> continue observing

**Comment by Intigracy** [comment]
#12386

@gbasood, can confirm.

**Comment by clusterfack** [comment]
test ur shit man

**Comment by gbasood** [comment]
Sorry it's taken me so long to get to this.
I'm working on finding a fix now.
