### ISSUE TITLE
Issue with ventcrawling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12425]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
The past two rounds I have played and came in contact or was a ventcrawlable creature it seems that the scrubbers are constantly dangerously overpressured and the scrubber pipeline is always underpressured to the point it damages you. This makes it dangerous to ventcrawl at all.

To reproduce, chose a lesser creature such as a monkey and attempt ventcrawling.

**Comment by Kurfursten** [comment]
Not a bug? Even if the scrubber line started out with room pressure atmos, it would empty out quickly via the final vent.

**Comment by Sprok0** [comment]
The scrubber line should always be either empty and freezing if atmos did their jobs, just empty if they didn't, or literally full of fire. Don't ventcrawl through scrubbers if you aren't immune to atmos.

**Comment by clusterfack** [comment]
Pressure doesn't affect you in pipes though

**Comment by Exxion** [comment]
Yes it does, unless you're a mouse

**Comment by ihadtoregisterforthis** [comment]
Or a borer

**Comment by AutismSpider** [comment]
any thing thats sub type of monkey will take pressure heat and cold damage form pipes.
