### ISSUE TITLE
Changelings can attempt to revive while beheaded

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12434]
(WEB REPORT BY: streptomutans REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
I beheaded a changeling and was carrying her head around when I got the text "Lizelle Siellander appears to wake from the dead, having healed all wounds.".
The head remained lifeless but I doubt I should be getting that message

>What you expected to happen
I expected the text to not appear

>What actually happened
The text appeared

>Steps to reproduce if possible

1. Behead changeling
2. No idea what exactly she's done
3. Get the text

**Comment by gbasood** [comment]
Report fails to describe what the actual problem was
The changeling can attempt to revive WHILE THEIR HEAD IS BEING CARRIED BY ANOTHER PERSON
Resulting in NOTHING

**Comment by gbasood** [comment]
I'll remake with a better description
