### ISSUE TITLE
GreyBay Embassy: Feature suggestion

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#12446]
Well, being the jelly faggot I am from seeing all of the vox get cool toys and shit i'd like to make a little suggestion.

I think it would be neat to add a section to the science outpost for greys to start out with for a unique job. I think it would be neat for it to be a place for genetic experiments, It would be a good way to implement things like augments which I know has been thought of for quite a bit as well as having a nice way to implement the abductor glands and tweak them to make them a bit less antagy.

**Comment by kilozombie** [comment]
Ayy, I told you to suggest and you did it
How can you make this different from Genetics? The abductor glands, sure, but how do you interest people to head to the science outpost to get strange things inserted in them?
How much variety should there be in the glands? What work should the Greys have to do?

**Comment by carshalash** [comment]
Well, the gland system is kind of on /tg/.

https://tgstation13.org/wiki/Abductor#Abductee_or_Insanity_101

If we take that and then modify it to have our own versions of them it would be pretty nice to have it be personalized to the server instead of a straight up port.

And honestly, when it comes to personalizing everything instead of just making it a different version of genetics. I think that the big thing about greys as a concept have always been seen as these scientific fucks that love testing things, I think it would be great if they started out with cubes for monkeymaning different races,  or just having freezers of dead bodies for testing. The concept of making genetic seems like it has been getting more and more popular recently on the server, i've seen medbay staff and admin get raging hardones from the ideas of making frankensteins just to meme or to try and bring the strongest aspects of different races together.

**Comment by ghost** [comment]
IF we wanted to make frankensteins fun, we'd need to unslave shit like claws from being mutations assigned to the torso

**Comment by ghost** [comment]
Considering vox traders get a unique set of seeds, and are seemingly hydroponics oriented, wouldn't be too hard to argue that the same could be done for greys and implants/genetics.

I know there's sprites and such for an implant production facility in the code. Maybe give them a semi-constructed telesci, basic genetic facilities, and an implant autism facility?

**Comment by kilozombie** [comment]
An implant autism facility, similar in scope and potential to Xenobotany, would make me cream pretty hard.
Implant that injects you with 2 hyperzine periodically but also making you leap at random? Teleportation whenever hit by a laser as well as healing all left arm damage?
??!?!??

**Comment by NigglyWiggly** [comment]
> Special starting locations for another race

No thank you. It's already dumb that the birds have one but making the greys suddenly a super special race with their own special base would be dumb.
That said, I still want to see Grey technology stuff.

**Comment by SonixApache** [comment]
SAUCERS
COW PROBES
RAYGUNS

At the very least there should be special interactions between greys and cows. And butts.

**Comment by Kitfox88** [comment]
> greys raid station
> goal is to steal x amount of asses from people

**Comment by icantthinkofanameritenow** [comment]
One nonhuman race being treated like special snowflakes is enough. Let the rest deal with the fact they're second-to-last class citizens in SS13 already.
