### ISSUE TITLE
Textlog failed to load

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12445]
(WEB REPORT BY: noobxshowx78 REMOTE: 172.93.109.202:7777)
>Revision: a5edb6775a89b8443c93142b551061e069d72ddf 

>General description of the issue
Textlog says "Loading..." 
and tells me to bug report it

>What you expected to happen
n/a

>What actually happened
n/a

>Steps to reproduce if possible
n/a

**Comment by Intigracy** [comment]
As-is this issue report is entirely unusable.
