### ISSUE TITLE
Revsquad antaghud icons are fucked

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#12451]
Show up as black question marks.

**Comment by ghost** [comment]
Hmm if only someone made a PR that streamlined this using I datums and planes
🤔

**Comment by gbasood** [comment]
snowmap first

**Comment by ihadtoregisterforthis** [comment]
100 bugs first

**Comment by clusterfack** [comment]
"Streamlined" 


The method you used was dogshit

**Comment by ghost** [comment]
Literally the best way to do it in byond, feck off.

**Comment by clusterfack** [comment]
No it was really bad

**Comment by ghost** [comment]
You're literally wrong tbh

**Comment by DamianX** [comment]
Fixed by removing revsquad
