### ISSUE TITLE
How to make Ling more like 'The Thing'

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12467]
As of right now there is a bug where you can use the 'rejuvenate' spell while as a head. This is seen as something of an oversight currently, so I have a proposition

Should a ling use the 'rejuvenate' spell while just as a head, they get a popup asking them if they want to become a more mobile form.

If they do so, the head is transferred into a headcrab-like thing like Norris, which can then scamper away. This special ling-norris can bite people to give them sleep toxins, and should it come across a dead or sleeping body, after a certain amount of time depending on the headgear of the person, forcefully remove their head and replace it with that of the lings.

Additionally, could have an 'infectious parasite sting' that can infect a persons limb if afflicted, and steadily take them over. Chopping the limb off would make a norris-like creature of the limb, which would attack anyone (and fake attack those who are a ling) and self-regenerate unless ashed or burned in some way. Should the parasite-sting completely overwhelm the person, they are then outed from their body, and a semi-brainless ling form (Also self regenerating unless ashed or burned) of their former self takes its place. Completely AI controlled, and can be directed by the ling that gave the parasite sting.

If you want full pandamonium, could have it so that an upgrade to the 'infections parasite sting' would make the AI controlled ling-limbs and ling-lifeforms potentially infect people if they attack them.

**Comment by kilozombie** [comment]
> people no longer behead lings
> they just stick them in the incinerator
> uh oh, the incinerator has been destroyed, i guess changeling is invincible

...

**Comment by AlphaBuffalo** [comment]
Even if the incinerator is broken you could just debrain them

**Comment by ghost** [comment]
I know how to make ling more like the thing

snow map

**Comment by Shadowmech88** [comment]
I think this is complex enough for the [WYCI] tag.

Also ling is never going to truly be like Thing because everyone has a radio headset.
The Thing would be much less suspenseful if every victim had the ability to broadcast "WOAH THE MONSTER IS IN X BUILDING AND IS EATING ME AND HE'LL PROBABLY TAKE MY APPEARANCE, WATCH OUT."

**Comment by AlphaBuffalo** [comment]
If anything make a beheaded ling able to talk and communicate with regen just for shits and giggles

**Comment by ghost** [comment]
@kilozombie Flamethrowers? Plasma fires? Tossing the sod into a R-UST or supermatter?

**Comment by ihadtoregisterforthis** [comment]
Leaving the head in space one tile away from any wall or window.

**Comment by jknpj** [comment]
Thing-like things:

Being able to use Matter Eater with their torso.
Being able to become any kind of simple mob.
Being weak to fire.
