### ISSUE TITLE
Ghost hands on cryocell (minor)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12475]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
>Revision :96d93214ce674e36fe453b922dd4e7da285e479f 

>General description of the issue

When you're inside a cryocell and push the "realease sequence" button, it shows the text :

Release sequence activated. This will take thirty seconds.

>What you expected to happen

No text - you're in not conscious

>What actually happened

Got a text

>Steps to reproduce if possible

Get incouscious, get stuffed into a cryo cell, select the option on the menu

**Comment by ghost** [comment]
This is how it's meant to be

**Comment by Exxion** [comment]
Yes, that's very intentional
Takes 30 seconds to release yourself from it and is near instant when released from outside

**Comment by Ephx1** [comment]
So, instead of closing this, you just put the label "Not a bug" on it.

**Comment by Exxion** [comment]
Yes, because something being intended does not automatically make it good.
In this case it is, but it's a matter of fairness

**Comment by Ephx1** [comment]
Then you should start an issue with that as the topic, the creator here just thinks it's a bug.
