### ISSUE TITLE
. attacks you with the crowbar.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12478]
(WEB REPORT BY: kolith REMOTE: 172.93.109.202:7777)
>Revision 96d93214ce674e36fe453b922dd4e7da285e479f 
>General description of the issue
Attacking a posibrain with anything gives them the message 
`. bashes you with the crowbar.`
http://i.imgur.com/NrpiLx8.png

>What you expected to happen
<name> bashes you with the crowbar!

>What actually happened
. bashes you with the crowbar.

>Steps to reproduce if possible
Be hit with any item as a posibrain.

**Comment by gbasood** [comment]
too late i already reported this nerd #12477

**Comment by kol1th** [comment]
FUCC
