### ISSUE TITLE
Borg movement when broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12476]
(WEB REPORT BY: bexus REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Borgs with broken actuators (or whatever the fuck it's called) being able to move (and control the enviroment) after running out of power.

>What you expected to happen
Still being unable to move or interact with machines

>What actually happened
When running out of power I was suddenly able to move and interact with machines, only modules didn't work.

>Steps to reproduce if possible
Damage yourself as a borg to about 20% then allow yourself to run out of power

**Comment by NigglyWiggly** [comment]
Not a bug.

**Comment by Shadowmech88** [comment]
Why isn't it a bug?

From the sound of the report, a broken actuator normally prevents a borg from moving, but then that borg with the broken actuator suddenly can move when it runs out of power.
At the very least it's a consistency issue.

**Comment by NigglyWiggly** [comment]
Oh, hmm.

**Comment by jknpj** [comment]
Unable to reproduce.
