### ISSUE TITLE
unknown obj

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12480]
(WEB REPORT BY: ooben REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
96d93214ce674e36fe453b922dd4e7da285e479f 

>General description of the issue
I spawned in the Paramedic Station. There is an "obj" in the Paramedic EVA gear locker.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by JustSumBody** [comment]
Result of #12113 
Also curious that they added it to the map rather than the locker object itself

**Comment by gbasood** [comment]
@aceedex fix ur bug fam
also change it to the locker instead of the map like @JustSumBody said, seriously don't manually edit lockers if you want to change ALL of them

**Comment by aceedex** [comment]
Going to fix it soon(tm)
It wasn't meant to change all of them though, just the one in box

**Comment by 9600bauds** [comment]
is fix
