### ISSUE TITLE
Slime people dismember into human bits

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12489]
(WEB REPORT BY: ammy55 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
a34c1c4cf788938ae8fb8b2183de2f507946fcf5 
>General description of the issue
Got beheded as a slimeman
head was a human

>What you expected to happen
i expected my disembodied head to be slime

>What actually happened
was human

>Steps to reproduce if possible
become slime man
remove head

**Comment by ghost** [comment]
This is because a slime person isn't a separate species, it's just a sprite overlay like hulk

**Comment by Intigracy** [comment]
Mutantraces are gay, why aren't they all just species?

**Comment by Exxion** [comment]
I'm guessing the mutantrace system was made before the species system

**Comment by Intigracy** [comment]
But when the species system was created it sounds have incorporated the mutantrace one

**Comment by Intigracy** [comment]
Should

**Comment by Exxion** [comment]
Yes, but that would have required work

**Comment by Eneocho** [comment]
they no longer get dismemebered into human bits
