### ISSUE TITLE
Flatpack Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12492]
(WEB REPORT BY: falcon343 REMOTE: 172.93.109.202:7777)
>Revision:  a34c1c4cf788938ae8fb8b2183de2f507946fcf5 
>General description of the issue: Fabricating sleepers, body scanners, or thermo homeostasis generators in the flatpack fabricator causes them to auto-spawn the other half to the right of the machine even before it's unpacked. When the flatpack is unpacked, only the left side comes out.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Exxion** [comment]
#5311
Dear fuck this is an old issue
