### ISSUE TITLE
Metal foam grenades are now just foam grenades

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12500]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

Revision: 32357c5286f6dc37159361a50ac20afeaed1bb4f 
>General description of the issue
Metal foam grenades no longer create foam walls.

>What you expected to happen
WALLS

>What actually happened
NO WALLS

>Steps to reproduce if possible

throw metal foam grenades, wait for the bubbles to stop, admire your walls being less tangible than a mime's

**Comment by AI-Is-Rogue** [comment]
They create foam floors when activated on space tiles.
