### ISSUE TITLE
Paramedic EVA locker bug.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12509]
(WEB REPORT BY: dil9 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

Revision: 6f35f0ab5242609a7a68b72ca6e8c6a159d206e4 

>General description of the issue

There's an item called "obj" in the paramedic EVA locker in boxstation. I don't think you can pick it up or do anything with it.

>What you expected to happen
The paramedic EVA locker not having an item called "obj" in it.

>What actually happened
The paramedic EVA locker had an item called "obj" in it.

>Steps to reproduce if possible
Open the paramedic EVA locker and right click to see the items in it.

**Comment by Probe1** [comment]
Shoulda tagged it as Boxstation you bum
