### ISSUE TITLE
RED BLINDING LIGHTS FAR TOO BLINDING

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#12504]
When the station is undergoing evacuation procedures, a recent addition added red blaring lights to all the hallways.

Whenever this happens, I don't know if it'd because of my bad vision, because I'm colorblind, or some mix of the two, but I can't see shit.

Can we maybe either remove it, or just tone down how red it is?

**Comment by Megamaw** [comment]
@gbasood what information do i need other than 'when you call the shuttle, the red lights in the halls are too bright for me to see anything'

**Comment by Shadowmech88** [comment]
Post a picture of the lights?

**Comment by AlphaBuffalo** [comment]
This brought up a decent idea though, should we make a colorblind setting?

**Comment by Megamaw** [comment]
ok shit where does byond save screenshots

**Comment by PJB3005** [comment]
`Documents\BYOND\screenshots`

Though yeah how do you guys screenshots to figure out what we're talking about?

**Comment by Intigracy** [comment]
It's like the firelock flashing overlay on the area except in every major
hallway and a worse color.

**Comment by FudgePucker** [comment]
> coders play the game so little they never seen the red eye rape lights from the excape shuttle

Codrs pls

**Comment by clusterfack** [comment]
Pretty sure he's talking about a bug you get when you turn off hardware rendering like an absolute shitter so you don't see lighting. Thus confirming my belief that all skeleton players are shitters.

It also causes the emergency escape shuttle red overlay to cover up everything beneath it.

**Comment by FudgePucker** [comment]
I have hardware rendering on, I think the blaring red lights are fucking agitating.
If I was red color blind I would gouge out my eyes every round.

**Comment by clusterfack** [comment]
I don't know of any 'recent addition' that has changed this in any way at all.

**Comment by PJB3005** [comment]
The lights don't use hardware rendering.

But yes they should really be replaced with coloured alarm lights in the hallways.

**Comment by clusterfack** [comment]
The area lights use blend mode multiply, which means they need hardware rendering to not be opaque

**Comment by PJB3005** [comment]
No they use add unless it was changed very recently.

**Comment by clusterfack** [comment]
You can test this yourself

**Comment by clusterfack** [comment]
Actually wait I remember what the issue was it was with noir planemasters

**Comment by Megamaw** [comment]
@clusterfack nope, they're not opaque. it's not a bug. i just cant see shit because im colorblind and it's really fucking bright.

by 'recent addition' i mean 'probably within the last two years'

**Comment by Megamaw** [comment]
that is to say, it's working as intended, but the way it was intended makes the game literally unplayable for me

**Comment by gbasood** [comment]
Couldn't we add a colorblind mode to spess with `client.color` and a matrix? I mean it probably wouldn't help flashing red lights from my understanding but hey

**Comment by Megamaw** [comment]
i think i have an idea of what'd be better b/c i dont think its just colorblind folks who have trouble seeing in it 

maybe instead of turning the whole floor/action area red in the halls there's like an alarm on the walls in each room that tells you the current security level-- blue, green, red, etc, and red + blinking for evac

**Comment by Shadowmech88** [comment]
Such wall-mounted alarms already exist.

**Comment by Megamaw** [comment]
im getting my thoughts mixed up with reality again, except the other way around from the usual

i should probably get that checked out!

wait why dont we just use those instead?

**Comment by Shadowmech88** [comment]
Because there's only one alarm per zone, and for very large areas like the central primary hallway, not everyone can see the alarm while inside the hallway. The lights serve to notify everyone in the area of the alert status at the same time.

**Comment by AlphaBuffalo** [comment]
What about a setting to disable the evacuation light and use a status icon above the health bar to indicate when the shuttle is called

**Comment by Megamaw** [comment]
@Shadowmech88 maybe add more alarms to large areas? idk, just make it so the game isnt unplayable for 10 minutes at the end of the round. just because it's 'intended' doesn't mean it's not stupid. i think you said that once.

@AlphaBuffalo see that might work but there's already something in the status tab that also tells you, and having blaring red fucking lights as an optional setting would be confusing af
