### ISSUE TITLE
Paramedic Webbing/Hardsuit Shortage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12501]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision 
32357c5286f6dc37159361a50ac20afeaed1bb4f 
>General description of the issue
The paramedic EVA gear closet in every map other than Box contains no Webbing
There's also a lack of hardsuits, with only one for a possible two paramedics on boxstation

>What you expected to happen
Webbing and hardsuits for all paramedics to be available

>What actually happened
it's fucking nothing

>Steps to reproduce if possible
load up box and look at the paramedic closet
then load up any other map and look at the paramedic closet

**Comment by aceedex** [comment]
When I made the PR, it was intended for it to be only in box to make it a little less dull. If it's in that  much demand I'll add them to other stations later on

**Comment by Probe1** [comment]
idk what I can do for you here.  its how it was designed and i don't see a problem with the design.

**Comment by DamianX** [comment]
I'm on another mapping spree, do we want this to be added?
