### ISSUE TITLE
mortar and strange plants pug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12512]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
using the mortar on a strange plant with potato icon gave me potato juice

>What you expected to happen
chemicals

>What actually happened
potato juice?

>Steps to reproduce if possible

grind a strange plant with potato icon
get potato juice

**Comment by Exxion** [comment]
> pug

**Comment by gbasood** [comment]
🤔

**Comment by Shadowmech88** [comment]
It seems this isn't a bug. The mortar has unique messages for grinding grown items as opposed to grinding something like a can, indicating that it is supposed to produce juice whenever it grinds a grown item. I believe that, in all circumstances when juice is produced from a grown item, the actual reagents inside such as the nutriment (and any more exotic reagents) are ignored.
Maybe a toggle for grinding/juicing could be added to mortars.
