### ISSUE TITLE
Cannot evolve as alien larva

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12527]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)
>Revision 
e329cd8659ccdd5ef795628ef67fc9aee2fe1e6d 

>General description of the issue
Self-explanatory. Click an option to evolve from, nothing happens. 

>What you expected to happen
I evolve.

>What actually happened
See above.

>Steps to reproduce if possible
Be an alien larva ready to evolve. 
Try to evolve, fail.

**Comment by Sprok0** [comment]
You need to hold still after selecting your caste, for like five or ten seconds

**Comment by Intigracy** [comment]
Needs some sort of message explaining that, honestly.

**Comment by clusterfack** [comment]
Spell do after should use do after so they show a progress bar

**Comment by icantthinkofanameritenow** [comment]
@Sprok0 
Really? Why isn't there anything specifying that?

**Comment by Sprok0** [comment]
https://github.com/d3athrow/vgstation13/pull/11469 When xeno abilities were changed to spells, evolving was given a cast_delay of five seconds for some reason.

**Comment by Intigracy** [comment]
Just do what clusterfack said, easy fix.
