### ISSUE TITLE
Posibrain seeing deadchat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12526]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
posibrain in a durand seeing deadchat

>General description of the issue
im a posibrain in a durand and i can see deadchat while alive

>What you expected to happen
not to see dead chat while alive

>What actually happened
i saw deadchat while alive

>Steps to reproduce if possible
put a posibrain in a durand and see dead chat

**Comment by SkowronX** [comment]
already an issue about this

**Comment by SonixApache** [comment]
\>>>/#11259/
