### ISSUE TITLE
Windows and Zombies

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#12524]
I've got two problems that might need adressing

First being Full pane windows preventing you from alt clicking or interacting with items on the space they occupy. While this isn't game breaking, it does prevent reinforcing or rebuilding certain areas to a pristine condition.

Second is from a recent round, when Zombies revive, at least the crimson head, they are unable to move. They can still speak and trigger movement sensors, but will be stuck in place.

**Comment by Exxion** [comment]
Full windows are considered border objects so that it's actually possible to break them while border windows would otherwise be in the way.
Not sure why we don't just layer border windows on top instead so that you could just break them before the full windows, but whatever

No idea about the zombies

**Comment by gbasood** [comment]
> Not sure why we don't just layer border windows on top instead so that you could just break them before the full windows, but whatever

probably the only reason is that they look ugly that way

@Dizor in the future since these issues are completely unrelated, please make separate issues for them

**Comment by JustSumBody** [comment]
First issue is tied into #10367
It's been around for quite a while now and it is annoying having to make sure you alt click your tile and do the whole autistic rotate thing just to properly finish full windows
I'm not sure a great way to address that either really

**Comment by Intigracy** [comment]
Easy solution is to add alt click to windows, making it call alt click on get_turf(src)

**Comment by Exxion** [comment]
@Intigracy That's already how it works
Problem is that Alt+clicking doesn't work on tiles that aren't `Adjacent()` to you
Plus you still can't interact with things under full windows even if you Alt+click on the tile before you place the window
(Only checks distance for leaving Alt+click up, not adjacency)
(Actually why IS adjacency required for Alt+click listing?)

**Comment by Shadowmech88** [comment]
Tested locally, a revived crimson skull was able to chase me around.
