### ISSUE TITLE
Pathogenic Incubator Bug (AGAIN)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12530]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision 2c696f47b22a07086021996cb450f73e4cd8a20b 
>General description of the issue
Unupgraded pathogenic incubators will not produce mutations, at all

>What you expected to happen
delicious BEEP

>What actually happened
foul PING

>Steps to reproduce if possible
crank up the radiation and let an incubator work

**Comment by Kurfursten** [comment]
Needs more testing

The unupgraded incubator can go for a pretty long time without mutations. That's just how RNG with low chance works.

**Comment by ghost** [comment]
Nope, I fucked up.

A new pathogenic incubator has the mutate chance of 0 because it's multiplying by 0 (Base stock parts)

I'm dumb

**Comment by ghost** [comment]
Couuuld be a feature that the machine needs to be upgraded before you can do any advanced mutation shit, considering it got buffed?

**Comment by Intigracy** [comment]
So you can't use virology until you upgrade?

**Comment by ghost** [comment]
Can't use virology for research, if it were the case

I'll sort it, hang on
