### ISSUE TITLE
Grey Shuttle Vault Mapping Problems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12532]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision b59cd864ffacc94b2c77a4c13b88b8229f29df3b

>General description of the issue
The middlemost "propulsion" unit is oriented 180 degrees to the other two, such that the exhaust is facing towards the ship
The greys in the ship can open the doors, whicn can and will cause them to vent the whole ship and then float off into space

>What you expected to happen
the sprites to not be borked and the greys to be in the ship

>What actually happened
the sprites were borked and the greys fucked off

>Steps to reproduce if possible
load up the vault and watch the greys wander around until they space themselves

**Comment by Kitfox88** [comment]
ayylmao
