### ISSUE TITLE
Stacking teeth on a surface

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12533]
(WEB REPORT BY: curver REMOTE: 172.93.109.202:7777)
If you stack human teeth on a surface, the total of teeth on that surface will always be one, regardless of how many you placed on there (unless you remove the one, of course). The rest vanish into bluespace.

**Comment by Exxion** [comment]
Teeth are a stack, so when you place a tooth on the same tile one already is, the stacks merge.

**Comment by MasterofNothing** [comment]
I didn't examine it, so I guess that'd explain it. Nevertheless, you can't place them without merging the stacks like many other objects (e.g. on different spots on a surface), which is the behaviour I was expecting.

**Comment by Exxion** [comment]
Yeah, there should probably be a way to place multiple stacks of the same type on the same tile without them merging
