### ISSUE TITLE
Sound clip being played when your laws are changed/updated

### ISSUE THREAD

**Issue by Fruktlimpa** [d3athrow/vgstation13#12546]
This is a feature request. I was unsure how to format this considering that the template was for bug reporting.

In any case. I fucked up as sillycon and ended up harming a human when my laws had already been changed. I do not deny that I missed the update because of my lust for murderboning to fulfill my one humans last wish, but it made me realize how easy it could be to miss it should the text be spamming fast.

So is it possible to add in a sound clip to whenever your laws get updated or changed to more easily alert the sillycons when their laws are changed as to further prevent stupid mistakes like mine?

**Comment by Kurfursten** [comment]
How about this?

http://vocaroo.com/i/s0H7gXg1oqrE

**Comment by Allspice** [comment]
perfect

**Comment by Fruktlimpa** [comment]
The most optimal sound would be the syndicate clip that says "Your new directives have been uploaded" but using the Nanotrasen AI voice instead, mainly for IMMULSION purposes.
But this works just as well, just anything to grab the attention of the player really.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=7nQ2oiVqKHw this is what the upload sound should be

**Comment by AlphaBuffalo** [comment]
I like the Mac startup sound

**Comment by jknpj** [comment]
How about this one? https://youtu.be/pG6g0ZMK1ws?t=18m12s

**Comment by Fruktlimpa** [comment]
I dug through the vox sound map and there were already words for something as simple as "Laws have been updated".
I spent 500 hours in audacity making this abomination of a sound file. Might be too confusing considering that it sounds like the AI but it's something. pls no hate.

http://puu.sh/skhQG/af8548d086.ogg

**Comment by ihadtoregisterforthis** [comment]
https://www.youtube.com/watch?v=MfSfpZooiu0

**Comment by ghost** [comment]
https://youtu.be/DGOgSPVBmIE

**Comment by ihadtoregisterforthis** [comment]
https://www.youtube.com/watch?v=scFR4sYnVDc

**Comment by Fruktlimpa** [comment]
We have some good sounds already posted so I thought I would ask how difficult you think it would be to add this into the game, code-wise that is.
I can't code for shit so I am hoping a kind soul will take it upon him to do it.

**Comment by Exxion** [comment]
An addition of exactly one line, plus the sound file.

**Comment by Fruktlimpa** [comment]
The AOL "You got mail" is great. It is short while still standing out enough and it has that meme-spice that the playerbase™ loves.

**Comment by ihadtoregisterforthis** [comment]
I think it should be something short and unique, to avoid confusion. Like the "personalities available" cue that pAIs have.

**Comment by jknpj** [comment]
http://vocaroo.com/i/s1GuY2iuAfDA

**Comment by ComicIronic** [comment]
Just beeping is a bit too generic, given how often the AI will hear it in all the ambience rooms with cyborg background noise.

**Comment by Zth--** [comment]
I'll add this to my todo list, I'm gonna work on a sounds update next weekend

**Comment by Fruktlimpa** [comment]
Thank you for taking it upon you. Have you selected a sound you like? Even if Jknpj's sound is just bleep bloops it sounds unique enough and if you raise the volume a bit it will stand out.
