### ISSUE TITLE
MULEbot hacking menu etc.

### ISSUE THREAD

**Issue by Chronakai** [d3athrow/vgstation13#12549]
#### Description of issue
MULEbots do not have a decent wire ui, and only radio crackling is present on multitooling them
also no nanoUI

Also it's kind of a bitch to get them to start working properly even without hacking, but maybe I'm doing it wrong.

#### Difference between expected and actual behavior
Motor whirring, cargo loader thunking, an actual working menu like most other wire-hackable things

#### Steps to reproduce 
Go cargo
obtain screwdriver and multitool
unlock the control menu on the MULEbots
pop open the cover with a screwdriver
use multitool on the bot
pulse all the wires
scream

#### Specific information for locating

MULEbot
multitool
The radio crackles.

#### Length of time in which bug has been known to occur

At least a few revisions.

#### Server revision

Most recent as of 11/14/16

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Zth--** [comment]
Old unmaintened code

**Comment by Kurfursten** [comment]
Not a bug, read the wiki for information on to hack mulebots. You have to cut wires for mules, multitool isn't very useful.

The stuff you're looking for like a "thunk" is from other codebases, not ours. You can look at the indicators at the bottom after cutting wires though. For instance, the platform rides low.

**Comment by Chronakai** [comment]
Alright, I'll look things over a bit closer and give it another shot soon.
