### ISSUE TITLE
Spells Lost on Cloning (Bug?) - Causes Ghost Spell to remain when alive

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12545]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Unsure how this works because this wasnt for a wizard, but a miner who found a spellbook of binding. Upon being cloned instead of having no spells or my bound object spell, i instead had the "boo" ghost spell. Unsure how ANY of this is supposed to behave but im sure something fucked up somewhere.

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce.
