### ISSUE TITLE
Shuttle flames can enter the shuttle if you smash the rear reinforced window

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#12542]
Image taken from deff's emergency shuttle during transit
![image](https://cloud.githubusercontent.com/assets/19365096/20255038/75cc4ca0-aa07-11e6-8bf5-428f06751d52.png)
That bottom most reinforced window at the back of the shuttle which separates the heaters/propulsion from the rest of the shuttle was smashed, this was the result the whole shuttle ride
Not sure if this is specific to Deff because of sideways transit turfs or what
Also not entirely sure if this happens on things like the mining shuttle which move instantly, I feel like it will but just not to the same extent.

**Comment by Sprok0** [comment]
I'm 99% sure it can't happen on normal shuttles, but this seems to be working as intended here. The diagonal flames from the transit zone is something I'll try to fix though

**Comment by AutismSpider** [comment]
Why fix it?

**Comment by AI-Is-Rogue** [comment]
I think it should be considered a feature, and that all shuttles should be able to do this if they can't because it can only bring FUN.

**Comment by Shadowmech88** [comment]
If we keep it as a feature, then I think the windows at the back should be made into reinforced plasma glass windows, to make it at least a little tougher to fuck up everyone inside the shuttle with fire.

**Comment by Exxion** [comment]
Agreed. We should also make it possible to install windows on the heaters as can be done with grilles, so replacing those windows is actually possible.

It's just occurred to me that this would be a major problem on the salvage shuttle, whose roundstart spiders often break the windows when someone tries to board the ship.

**Comment by jknpj** [comment]
How does it work with savage, trader, skipjack and syndicate shuttles?

**Comment by Sprok0** [comment]
It doesn't, only the escape shuttle is vulnerable to this.

**Comment by Intigracy** [comment]
I think it'll be anything that uses hyperspace, no?

**Comment by Sprok0** [comment]
The escape shuttle doesn't fully use the normal shuttle launch system, but is moved directly by the emergency shuttle process. Normal shuttles have the exhaust timed so that the backwash doesn't hit them, but the escape shuttle doesn't, and also keeps firing while in transit. This was honestly unintended, but I'm calling it a feature.

**Comment by Exxion** [comment]
It already had it so I had to remove it to get the extra emphasis

**Comment by 9600bauds** [comment]
https://a.uguu.se/Wmujp2qOGGCq_Desktop11.30.2016-13.36.27.03.DVR.webm
memes and dreams

**Comment by Intigracy** [comment]
Wonderful.
