### ISSUE TITLE
Secure Vial Storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12554]
(WEB REPORT BY: pinkacolada REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
A virologist does not have the access to open the Secure Vial Storage box in Viro

>What you expected to happen
It to open

>What actually happened
It didn't open

>Steps to reproduce if possible
Get a Secure Vial Storage box and swipe a Virologist ID on it

**Comment by Probe1** [comment]
```	req_access = list(access_virology) ```

**Comment by Probe1** [comment]
Its inheriting the lockbox access requirement.
