### ISSUE TITLE
Having both your body and your face obscured is apparently SUPPOSED to make it so that your gender can't be seen on examine, but actually doesn't because for some reason the in operator has a lower priority than &&

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#12558]
(Note that only hardsuits obscure your body)
Fixing JUST this would require only a pair of parentheses, though changing other messages to maintain consistency with it would require more work.

Alternatively, we could just leave it as-is.

I don't really have a preference either way, but if we do decide not to fix it, the code that's supposed to handle this should be removed.
So uh... decide, I guess.

**Comment by Intigracy** [comment]
I think it should obscure.

**Comment by Exxion** [comment]
It's occurred to me that the code that handles this should be removed either way, because making other messages keep consistency with this would involve changing the mob's `gender` under these circumstances, and examine should then always report the mob's `gender`

**Comment by Exxion** [comment]
I believe this has since been fixed
