### ISSUE TITLE
Leaving the wizard's den

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12555]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)fc28df4e5bf6eeb6ec2ae93ca2aff8adacf12241

>General description of the issue
you can blink into a wall in the wizard's den and exit into space. And you could probably use the small tank in your backpack and gem hardsuit together to reach centcomm, then steal their seraph and destroy the station

>What you expected to happen
blink anywhere but into the wall

>What actually happened
teleported into the wall

>Steps to reproduce if possible
be wizard and blink while inside of the den

**Comment by Sprok0** [comment]
Which map was this, I checked when I made blink work on z2 that all the wizard dens were surrounded by the shuttle teleport zones that dump you in a random zlevel, so you couldn't actually reach centcomm.

**Comment by AI-Is-Rogue** [comment]
It was box. I blinked into the wall and accidentally moved into the void but I quickly teleported back inside. I was just guessing you could find your way to Centcomm, and I really don't think you should be able to teleport onto those walls at all, could have died there.

**Comment by Sprok0** [comment]
It's the same as how you can blink into the window/grilles on the station, blink only checks if the turf itself is dense, not if there is anything else dense on it.

**Comment by AI-Is-Rogue** [comment]
Really? I thought it wasn't like that for the station walls, I can't remember ever blinking into them.

**Comment by Sprok0** [comment]
Did you actually blink into one of the walls, or one of the grilles?

**Comment by AI-Is-Rogue** [comment]
It was one of the wizard den walls next to the knives and statues.

**Comment by clusterfack** [comment]
@sprok0 I WARNED YOU BRO, I WARNED YOU ABOUT BLINK BRO.

**Comment by Intigracy** [comment]
Isn't there a var on turfs that let you prevent blinking and jaunting on
them?

**Comment by Konater** [comment]
I thought there was a block on the z level that prevented this

**Comment by Intigracy** [comment]
It got removed, hence clusterfack's above post.

**Comment by Shadowmech88** [comment]
There used to be.
