### ISSUE TITLE
Ion Rifles short other Ion rifles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12551]
(WEB REPORT BY: acedick REMOTE: 172.93.109.202:7777)
>Revision 17b57e93c63540e1ecd6b513747953d9

>General description of the issue
Ion rifles' localized ion effect usually doesn't short the ion rifle itself that fired it even if you're caught in it, however with another one on my person the ion shorted that one. This is running off the assumption that ion rifles themselves should be resistant to being ion blasted.

>What you expected to happen
Ion rifle would not short and lose all charge, like the rifle that was fired.

>What actually happened
Ion rifle that was fired remains charged, other ion rifle does not.

>Steps to reproduce if possible
>have two rifles
>fire ion blast close enough to get caught
>other ion rifle will lose charge, fired one will not

**Comment by Shadowmech88** [comment]
Not just that, but ion rifles can drain their OWN charge.

**Comment by AutismSpider** [comment]
Yeah its odd that Ion rifles/guns are not EMP harden in some way

**Comment by Sprok0** [comment]
```
/obj/item/weapon/gun/energy/ionrifle/emp_act(severity)
    if(severity <= 2)
        power_supply.use(round(power_supply.maxcharge / severity))
        update_icon()
    else
        return
```

It should already be immune to non-direct EMPs

**Comment by clusterfack** [comment]
>severity <= 2

H u e

**Comment by Intigracy** [comment]
I feel it'd make more sense if it were just EMP immune completely.

**Comment by clusterfack** [comment]
Its not emp immune at all

**Comment by Shadowmech88** [comment]
Can EMPs not have greater than 2 severity?

**Comment by Intigracy** [comment]
1 2 3 severity.

1 is the closest iirc.

**Comment by Intigracy** [comment]
Yeah, emp_act(1) is the strongest effecting, emp_act(3) is the weakest.

It's very possible to emp your ion rifle, just from glancing at that code block. It's only immune to the weakest emp.

**Comment by ComicIronic** [comment]
It should be noted that the code is totally correct - the EMP rifle only drains for stronger EMPs. It's just not immune. Could change the whole thing to a return or an empty block.

**Comment by clusterfack** [comment]
Last I checked there is no severity 3 for ion, nada

**Comment by Intigracy** [comment]
Maybe I'm thinking of ex_act.

**Comment by Exxion** [comment]
They work the same way, except there are no actual circumstances in-game where a `severity = 3` EMP happens

**Comment by ghost** [comment]
@ComicIronic It's not an oversight if they were coded specifically with this intention

**Comment by ComicIronic** [comment]
The arguable oversight is that an ion rifle can EMP itself.

**Comment by ghost** [comment]
@ComicIronic but the bug report here says that doesn't happen

**Comment by ComicIronic** [comment]
But the first comment does.
