### ISSUE TITLE
makeshift bee grenades[feature request

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12552]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
what if you could put bees into a bottle and trow it at people

**Comment by Ephx1** [comment]
WYCI

**Comment by FudgePucker** [comment]
If you aren't willing to log into github to make a feature request, then the feature request isn't worth coding.

**Comment by Probe1** [comment]
what fudgepacker said.

Pvak has about 50 feature requests through the BUG REPORTER.
