### ISSUE TITLE
revert the shuttle fire pr

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#12568]
please god only bad shit has came from this

**Comment by TheFriggenSawbones** [comment]
it keeps getting breached by non-antags. The fire kills everyone in the shuttle.

Whats the fucking point and why does it work like that

**Comment by SysadminJeroen** [comment]
There is already a discussion to turn the escape shuttle glass into _reinforced_ plasma glass.
And if a pane is broken get Engineering to repair it.

**Comment by Sprok0** [comment]
The pane is already reinforced plasmaglass

**Comment by SysadminJeroen** [comment]
If that is the case, the person destroying it is destroying it on purpose.

Because those things are difficult to destroy by hitting them and they usually withstand explosions.

**Comment by TheFriggenSawbones** [comment]
the guy screwdrivered and crowbar'd the glass

it does nothing man

just fuckin make it impossible for it to ever go back into the shuttle

**Comment by SysadminJeroen** [comment]
If he did that and he isn't an antag isn't that an offense he can get a bannu for?

**Comment by TheFriggenSawbones** [comment]
and he was but what's the point of having a way of killing the entire shuttle that easily

**Comment by Sprok0** [comment]
You mean like breaking the windows to space and zassing half the crew out?

**Comment by SysadminJeroen** [comment]
There always is another 2 panes or a door between you and the rest of the shuttle, they need to destroy that too or emag the door open.

And I was also thinking about what @Sprok0 said, it is easier to ZAS half of the crew than to light everyone on fire.

**Comment by jknpj** [comment]
you can buckle yourself to not fly away now
you can't protect yourself from magic blue fire with chairs

**Comment by ihadtoregisterforthis** [comment]
Make the heater piece block the flames.
Also does the fire appear on escape pods?

**Comment by Sprok0** [comment]
Escape pods aren't actually shuttles, and don't do this.

**Comment by kol1th** [comment]
Why does it even backfire into the shuttle again? Doesn't really make much sense.

**Comment by Kurfursten** [comment]
Exotic particles

**Comment by ghost** [comment]
It probably shouldn't backfire into the shuttle, despite how much I love it when it does, just for the reason that it doesn't make any sense, it's a vacuum, it sucks air out, not fire in. If the heater was not exposed to space though, sure, keep it.

**Comment by Probe1** [comment]
Get out you fuckin communist

**Comment by Probe1** [comment]
(For real though people want it and its not a significant issue)

**Comment by PJB3005** [comment]
Let's never forget.

https://gfycat.com/PaleWeirdHammerheadshark

**Comment by Probe1** [comment]
I wouldn't in a million rounds.
