### ISSUE TITLE
Tide Recipe broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12577]
(WEB REPORT BY: amikawaii REMOTE: 172.93.109.202:7777)
Tide Recipe is broken, mixing water and welding fuel in equal amounts removes both reagents and yeilds nothing.

**Comment by Kurfursten** [comment]
Error at line 2693 Chemistry-Recipes.dm missing value
`result_amount = 10`

@ComicIronic tag easy fix
