### ISSUE TITLE
Mixing water and fuel makes both reagents disappear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12578]
(WEB REPORT BY: miningpig REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
 a720bcf0e692dde803a3c66a21765bce0b68a317 

>General description of the issue
The wiki said that mixing water and fuel would make a cool drink called "Tide" with a toolbox mug sprite. The two ingredients are water and fuel. Yet when you combine the two ingame, you get a bubbling noise, and both reagents disappear

>What you expected to happen
Cool drink for the ghetto coffee boy.

>What actually happened
Disappointment

>Steps to reproduce if possible
Mix water and fuel.
Get disappointed

**Comment by ComicIronic** [comment]
Known issue.
