### ISSUE TITLE
Lighting and Graphics are messed up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12586]
(WEB REPORT BY: unusualcone REMOTE: 172.93.109.202:7777)
I seem to have an issue with the graphics not only on /vg/station, but in the entire game as well.

The graphics seem to look a bit off, with some items having terrible resolution, lighting not having fade, the game running like shit, etc.

I have already updated DirectX, my graphics drivers, BYOND is on the BETA version,I checked and unchecked the Graphics box in the BYOND Preferences, but no matter what I do the game never get fixed.

I have yet recieved some advice for an absolute solution, since this seems uncommon.

**Comment by TheFriggenSawbones** [comment]
http://imgur.com/a/hEivg is his issue.

No dimming/fade in the deep dark maint

**Comment by Zth--** [comment]
Have you checked hardware rendering? When I turn it off my game looks exactly like yours

**Comment by PJB3005** [comment]
Hardware rendering is disabled.

Make sure your drivers are up to date and then try to install the June 2010 DirectX SDK and see if that fixes anything.

**Comment by DamianX** [comment]
CLOSE IT
