### ISSUE TITLE
Can't see chat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12583]
(WEB REPORT BY: eyeofheimdall REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>The chat window doesn't align properly, and doesn't show any text at all.

>What you expected
To see chat

>What actually happened
No alignment, looks like the window couldn't load the Jscript element or whatever it's using.

>Steps to reproduce if possible
I'm on Win XP, Using up-to-date Byond (as of 11/19/16). Connected directly to sever. There is some sort of text but all i see is this:
play field||e maximum of 5 times.
play field||t, use the bug report
play field||ght of the window.

Thanks!

**Comment by Exxion** [comment]
>XP

Why

At least it's not a bad bug report
Have you tried relogging?

**Comment by ghost** [comment]
@PJB3005

**Comment by kol1th** [comment]
Didn't someone say at one point it just doesn't work on XP?

**Comment by PJB3005** [comment]
It does work on XP but they need to install IE 8.

**Comment by Exxion** [comment]
Usually the more recent one (#12654) would be closed, but it has more information than this one
