### ISSUE TITLE
bioluminescence color doesn't get transferred properly while doing xenobotany

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#12597]
#### Description of issue

I had a plant with red bioluminescence. Wanted to get another plant with red bioluminescence too so I did splice the gene. The new plant got bioluminescence but without color, just plain normal light. It should've been red.

#### Steps to reproduce

Get each gene and try to splice the bioluminescence one. You get the trait without color. I didn't try with purge (it should work with splice).

There are a few other bugs with xenobotany, I'll report them as soon as I can reproduce them

**Comment by Ratvar** [comment]
Use colour "Pigment" gene to change colours, dude. No bugs here.

**Comment by Zth--** [comment]
What? Did you even read? There's no such a thing as a pigment gene. Quote from the wiki 

> **Bioluminiscence**: The plant's bioluminiscence and _bioluminiscence color._

Everything works nice with the exception of the color.

**Comment by Ratvar** [comment]
Wekk. I mixed it with other gene systems, sorry.

**Comment by 9600bauds** [comment]
Splice just averages out the colors, are you sure you didn't end up with a very faint green or something? Seems to be working on my end

Biolum is the kind of gene you'd always purge anyways
