### ISSUE TITLE
Magically Regenerating Ingredients

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12591]
(WEB REPORT BY: snoopdoggofmars REMOTE: 172.93.109.202:7777)
>Revision 2d08ce9f9b740365e21ece3ea0aa2d6201a0acc3 

>General description of the issue
When grilling a sandwich, as in the kind made by just combining a food item with a slice of bread, the original reagent(s) will reappear on the grill but you'll still get the whole sandwich.

>What you expected to happen
Just a sandwich.

>What actually happened
I got a sandwich and an orange.

>Steps to reproduce if possible
Add food item to slice of bread, put onto grill.

**Comment by Intigracy** [comment]
Goofcode is great innit

**Comment by Exxion** [comment]
Oh yeah I was going to report this but I forgot
Made like five sandwiches with the same cheese wedge
The ingredient disappears if someone eats one of the things it's "in" though

**Comment by ghost** [comment]
IT'S A FEATURE

At least, that's what everyone who I reported this to before said. I wouldn't be against a fix for it but it's kind of handy...
