### ISSUE TITLE
Multiple Horror Form Issues/Bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12599]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Some of these may be intentional, so I'll just list everything that happened.

1. ~Unable to equip, no magboots or helmet means no light, darkness becomes an enemy to a maint monster. zas becomes hell despite horror form being "unstunnable"~

2. ~Force Airlock Doesn't work at all, tried various things.~

3. ~No way to tell your health, regenerating doesnt remove vision loss from damage, eventually decays till I can't see again and have to regen so I can at least see a bit again.~

4. Hardboil is a positive power that makes it hard to see in the dark. BECAUSE its a positive power, you can't regenerate it away, though I'm not sure if regenerate removes bad powers either.

5. Why Can Horror form pick up items anyways? shouldnt it just be a monster? If you pick up an item in combat, it drasticly reduces the damage you're doing to people if you don't notice right away.
6. Horror forming while in stun will just leave you in stun, Probably not a bug, but maybe should force a stand?

**Comment by Gunosaguki** [comment]
~Oh and forgot one. The evolution menu mentions you can "devour" targets whole as the horror form. They have no such ability as far as i can tell~

**Comment by Gunosaguki** [comment]
Someone clarified i mean the noir power, not hardoiled

**Comment by Blithering** [comment]
For the devour ability I think you need to get an aggressive grab on them, then click your own sprite. At least that's how it works with aliens and fatties.

**Comment by Shadowmech88** [comment]
I believe that, now that horror form changelings are an actual human race instead of whatever snowflake I'm sure they were at this time, issues 1 and 3 no longer exist. The rest is feature request. OP updated to reflect this.
