### ISSUE TITLE
Refunding spells removes Spells you already have

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12590]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
If you already have a spell when you obtain a spellbook and refund spells, it'll just nuke the spells you had and give no refund points for it.

Very situational of course. but an issue none the less

**Comment by unid15** [comment]
I thought this was already fixed by #11824

What spells did you lose?

**Comment by Gunosaguki** [comment]
thiefknock from the goonesat on def. this may be because its distinct from the actual knock spell?

**Comment by Shadowmech88** [comment]
It seems refunds can no longer be taken outside the Wizard's den, so I don't see how this situation could happen anymore.
