### ISSUE TITLE
R&D access doesn't exist, it's based on toxins access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12607]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
>Revision 7e99076dd9449b

>General description of the issue
Roboticist lost R&D so they can't do research in nopop, but they (and everyone else) can still print from the proto. Parameds can do chemistry genetics etc. in lowpop. And if a science nerd wants to restrict access to the science machines they can lock the console.

**Comment by Intigracy** [comment]
They didn't lose R&D reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by Kammerjunk** [comment]
![they did](https://cloud.githubusercontent.com/assets/5942183/20649378/0b3ebbd0-b4bf-11e6-8260-d92fddadf801.png)
🤔 
That's with the "R&D Lab" access set on the airlock, which is the same one used by the R&D lab.

**Comment by Intigracy** [comment]
Then that's an issue with the airlock's access.

Which map is that?

**Comment by Kammerjunk** [comment]
Box.
Why would the R&D lab not have the access called "R&D Lab"?

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/pull/12103/files#diff-2612c60a374882c32be674b2092ebe58L100

The only access change in that PR was removing toxins and toxins storage from roboticist.

**Comment by Intigracy** [comment]
![2016-11-27_07-39-30](https://cloud.githubusercontent.com/assets/4043940/20649422/a926509c-b474-11e6-833d-2008ae943df8.png)

access_tox = 7



access_research = 47

**Comment by Intigracy** [comment]
I'll push a hotfix in a few minutes.

**Comment by Kammerjunk** [comment]
https://github.com/d3athrow/vgstation13/blob/a559bcf4e9f3004ad5969e1344680db1f37575a2/config/access%20levels.txt
access_research is general science access. Even geneticist has that.
It's not R&D.

**Comment by Intigracy** [comment]
Then there is no R&D specific access, which is pretty stupid.

**Comment by Kammerjunk** [comment]
It seems R&D access is currently the same as toxins access. Giving an airlock board R&D Lab access gives it an entry in conf_access with a value of 7, which is listed as access_tox
That is pretty stupid, yeah

**Comment by Intigracy** [comment]
access_tox is access to R&D, access_tox_storage is for toxins

**Comment by Intigracy** [comment]
@Allspice Sorry I hijacked your feature request, if you still want the analyzer to lose the R&D access could you make another issue?

**Comment by Probe1** [comment]
sometimes i think "Why did I just spend 30 minutes to do it right when it took me 5 minutes to fix it"

i think oldcoders thought "Why did I just spend 5 minutes when I could have not done anything at all"
