### ISSUE TITLE
Fix the Defficiency trade shuttle

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#12606]
It's awful.
It's the worst kind of awful.
This shuttle is not attached to the outpost proper. Instead, you have to spacewalk 5-6 tiles to get to it. In addition, both airlocks leading out to it are one tile wide, which makes it difficult to bring anything with you, such as canisters to repressurize it.
Opening the door to get in will inevitably ZAS some shit up. No, not the first go, not if you're lucky and very quick. But if you ever, EVER need to make two trips, or have more than one trader in your squad, air will rush out of the main room, and cause shit to fly towards you and out the door. This can include trade goods, potted plants, stools, you name it. God forbid you forgot to turn your magboots on, you're automatically dead just like on Meta Club.
Just extend the airlock so you can get to the shuttle, or move the airlock to the top side of the outpost. There's no reason some asswipe would have parked it so inconveniently that the jews would need to spacewalk every time they wanted to put more things in their ship. Only Bill Hudson or possibly Satan would have parked it in such a way

**Comment by Kurfursten** [comment]
see #10319

tagging @Probe1 for visibility

Honestly I don't really care one way or the other, but Deff by far as the best outpost so having the worst trade shuttle seems like a fair tradeoff.

**Comment by PJB3005** [comment]
I'm fine with the going through space, as long as the size of the airlock (vox station side) is increased so stuff can be hauled through it.

Decompression doesn't really matter as long as you allow the shuttle to refill air by opening the airlock after docking at the station.

**Comment by Intigracy** [comment]
Decompression does matter though because half of your shit flies towards the door.

**Comment by Kurfursten** [comment]
I don't remember that ever happening, but that may be because I play correctly and don't leave the windows open to the stock room when entering and exiting. Has anyone who plays the role badly (leaving the trade windows wide open while decompressing) noticed this?

**Comment by kilozombie** [comment]
The entrance room will get depressurized. Then, when you enter the main room by opening the windoor, the pressure differential will cause ZAS.
Not really fair to imply I play the role badly and that you play 'correctly'. Whether or not you are special does not matter, air will drain out of the shuttle and make trips back and forth arduous and sometimes dangerous.

**Comment by PJB3005** [comment]
Okay true I didn't think of that.

🤔

What if we made it so you can have "blast pressurization" of an area in the same sort of way it looks like in Dead Space?

Then also add ZAS not touching objects that are being pulled and you're golden.

**Comment by Kurfursten** [comment]
I'm not able to reproduce the effects on live. Notice the paper remains still no matter what is dragged through the door.

http://imgur.com/a/q3pOM

**Comment by Probe1** [comment]
I was asked to keep the theme of Defficiency when making it.  If you have suggestions for creative drawbacks or think that it should be nixed altogether then please post them.

As well ZAS settings have been altered since it was mapped so in the current balance it may be untenable.

**Comment by Kurfursten** [comment]
That's a good point, the actual live server may not run on the same ZAS settings as default testing settings.

**Comment by Exxion** [comment]
It doesn't.
Live server is always set to Hellish, while the codebase default is... I don't know, but piss wimpy.

**Comment by Kurfursten** [comment]
Somebody take a video of the effects on paper on live then

**Comment by Probe1** [comment]
I should probably change it.  It was not designed for Hellish.

**Comment by kilozombie** [comment]
From personal experience, the potted plant can be flung toward the door the first time you even open the door.
ZAS is just really really harsh on the server and this shuttle is an example of that.

**Comment by Probe1** [comment]
I'm glad to hear that.  It must always be BUSTATIME. Please evaluate this change @kilozombie 

![image](https://cloud.githubusercontent.com/assets/8550416/20675974/2661c73e-b55c-11e6-9165-f0fd12b0a511.png)

**Comment by Kurfursten** [comment]
No scrubbers? Oxygen poisoning, caw.

**Comment by Probe1** [comment]
Alright I'll add some something dirty.

**Comment by Sprok0** [comment]
That new airlock will take ages to cycle, the one-tile one has a pretty good speed on it.

**Comment by Probe1** [comment]
It took around 8 seconds.

**Comment by Exxion** [comment]
(We don't even have a system for cycling between two atmospheres. Only cycling between an atmosphere and vacuum.)

**Comment by Probe1** [comment]
Gross, I can't get an airlock sensor to work on a shuttle and I'll have to change this.
