### ISSUE TITLE
Asteroid Monsters no longer drop loot.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12612]
(WEB REPORT BY: morena REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: a41aab6d776a040a7a30b0562751ed2210b61c6f 

>General description of the issue
Asteroid monsters don't drop their loot any more

>What you expected to happen
Kill a Basalisk, get some diamond
Kill a hivelord, get a hivelord brain
Not sure if anything else is supposed to, Goldgrubs maybe. 
>What actually happened
Neither drop anything

>Steps to reproduce if possible
Kill a monster on the asteroid

**Comment by Sprok0** [comment]
Those are butchering drops now, use your pickaxe/drill to cut it off them

**Comment by ComicIronic** [comment]
Has the wiki been updated?

**Comment by PJB3005** [comment]
It says it for goliaths but it's not explained for the others.

**Comment by Icychocobo** [comment]
I added a small blurb to the Basilisk and Hivelord entires on both the Shaft Miner and Creatures pages on the wiki. It now states (in a sorta clunky manner) that they need to be butchered before you get their spoils.

**Comment by ComicIronic** [comment]
Fixed.
