### ISSUE TITLE
lights of pod failure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12620]
(WEB REPORT BY: molenga REMOTE: 172.93.109.202:7777)
Ever since the last update the lights of the pods go dark even though there are lightsources present.
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by nervere** [comment]
No longer an issue.
