### ISSUE TITLE
New lighting elements fail to illuminate

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12621]
(WEB REPORT BY: jfrit REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
406f2e444c2091e992c11009cbcb73393c09876b

>General description of the issue
I turned on a emergency floodlight, and other lights (hard hat lamp), and the environment's lighting didn't change.

>What you expected to happen
The new light source should have appeared.

>What actually happened
The sprite changed, but the light did not appear.

>Steps to reproduce if possible
Unknown.

Appears related to #12620

**Comment by FudgePucker** [comment]
Recent changes that could have caused this?

**Comment by PJB3005** [comment]
Lazy lighting init was a month ago couldn't have been that.

Weird.

**Comment by nervere** [comment]
No longer an issue.
