### ISSUE TITLE
pharmacist jumpsuit sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12622]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
the sprites for when you have it in hand are inverted (when you hold it in the right hand its on the left hand )

>What you expected to happen
spirtes not inverted

>What actually happened
sprites r inverted

>Steps to reproduce if possible

hold pharmacist jumpsuit in hand

**Comment by Shadowmech88** [comment]
Shouldn't this be reopened since the PR that fixed it was reverted?

**Comment by ComicIronic** [comment]
Yes.
