### ISSUE TITLE
PA no longer pulses supermatter shard.

### ISSUE THREAD

**Issue by ReindH** [d3athrow/vgstation13#12627]
#### Description of issue

Shooting the shard with the Particle Accelerator is not making any reaction with the supermatter shard anymore (crystal not tested).

#### Difference between expected and actual behavior

Expected reaction with shard, tested with power level 2, no energy and heat buildup from the shard. No light level increase either.

#### Steps to reproduce 

Aim PA at shard, set PA to any level, activate PA.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
It never worked that way.

**Comment by ReindH** [comment]
I remember the shard generating heat/power with the help of the PA before.
That was at least a year ago though.

**Comment by ComicIronic** [comment]
The PA effect might have collided with the supermatter the ways sparks used to and caused a reaction, but that shouldn't have happened.

**Comment by SysadminJeroen** [comment]
[![High Effect Engineering](https://img.youtube.com/vi/pIiBB1dA-3o/0.jpg)](https://www.youtube.com/watch?v=pIiBB1dA-3o)

**Comment by PJB3005** [comment]
> taking HIGH EFFECT ENGINEERING as source for anything
😂

**Comment by SysadminJeroen** [comment]
@PJB3005 They have actually once done it right, the mad man.

**Comment by jknpj** [comment]
I remember that. Still, the "done right" memengine was just 3 shards in conveyors, no PA nor actual singulo

**Comment by ReindH** [comment]
Too bad I never made screenshots because I never expected that this was a bug and it's gonna be eventually fixed.

**Comment by Probe1** [comment]
>quoting instead of greentextan
for shame @PJB3005

**Comment by Exxion** [comment]
>Caring

**Comment by kol1th** [comment]
:joy:

**Comment by liltiptop** [comment]
Did you try turning it off and on again?

**Comment by Intigracy** [comment]
`>sucking at greentextan`
smh

Also I'm pretty sure this actually did work at some point, whether or not it should come back can be discussed here.

**Comment by ReindH** [comment]
I would bet my left arm it worked some time ago and not the way ComicIronic described.
When the PA effect hit multiple shards there was no prompt in chat and no sound effect either but it still did pulse the shards.

It's nothing really powerful either, just a fun and awesome way of powering the shard, should definitely be re added in my opinion.

**Comment by jknpj** [comment]
> multiple shards there was no prompt in chat and no sound effect either but it still did pulse the shards.
Shard produce o2, plasma, heat and rad
o2 pulse Shard
more Shard = more o2, plasma, heat and rad

Multi shard engines can literally live just with one shard stimulating the other. Trust me, i've tried so many kinds of high octane memengines in the past and the PA NEVER did anything, everyrything was always o2 mindgames.

![high-octane meme engine](https://cloud.githubusercontent.com/assets/17928298/20841237/d3414d7a-b891-11e6-8ffd-d7f4f8664498.png)

**Comment by ReindH** [comment]
Well fuck me then, take this as a feature request.
And no, my left arm stays.

**Comment by PJB3005** [comment]
🔪 sorry I'm claiming that arm.
