### ISSUE TITLE
[Deff] Cargo has no desk bell

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#12628]
Description of issue
[Deff] Cargo has no desk bell

Difference between expected and actual behavior
[Deff] Cargo has no desk bell

Steps to reproduce
Desk bell

Specific information for locatinge.g. an object name, paste specific message outputs
Desk bell

Length of time in which bug has been known to occur
Desk bell

#### Server revision
Ding

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of desk bell.

- [x] Desk bell

**Comment by Probe1** [comment]
![output_sodcpz](https://cloud.githubusercontent.com/assets/8550416/20735429/04922d8e-b66e-11e6-9f42-e6148eadea6a.gif)

**Comment by 9600bauds** [comment]
Another minor nitpick:
The large beakers in Chemistry should be layered above all the other junk on the table
they are the most important thing

**Comment by Probe1** [comment]
I know someone who just loves to fix maps.  Shame there's already a deff PR up that's approved and waiting to be merged.

**Comment by Intigracy** [comment]
You can have infinite PR's open if you used the map merge tool and aren't touching the same tile in any of them.
