### ISSUE TITLE
Lawmaker in HoS Locker and Energy Axe in Safe for ALL MAPS

### ISSUE THREAD

**Issue by lawmaker666** [d3athrow/vgstation13#12637]
#### Description of issue

HoS gets a Lawmaker on defficiency map. And not one on Box or Metaclub! Very sad!
Add a lawmaker to the HoS locker in Box station and metaclub station.
On the defficiency map the vault holds an energy axe inside the safe.
On the box station and metaclub map the vault holds NOTHING OF VALUE! Many such cases!

You're a really smart and talented codebus.
In the vault safes you should add something that randomly spawns something of BEAUTIFUL, GREAT OR HUGE VALUE from a BEAUTIFUL list of things of value.
You should then not tell us what's on that list because we deserve a little bit of magic in our space lives. 
Like really the magic is gone. Put a little magic back in the game. Make the vault safe worth something.  
You're doing a great job. 
I love you.
Please and thank you and may god bless you.

**Comment by ghost** [comment]
Are you a dirty vox? 
You type like one.
Gas the vox, race war now!

But anyway the Energy Axe on Deff is stupid, and the fact it can be mass produced by mechanics is even stupider.
Lawmaker on every map would be nice, give the HoS a good little toy everywhere.

**Comment by lawmaker666** [comment]
I'm literally pomf.

**Comment by Probe1** [comment]
I'd rather just edit the energy axe in Defficiencies safe to have half its normal damage (bringing it in line with an esword - still a treat but not retarded one shotting people).  

And I'm not going to do something on all maps because Duny did something stupid on Defficiency.

**Comment by JMWTurner** [comment]
The axe can be turned on and off, and it's damage is reset to the default values everytime, so it's not something you can change through mapping alone @Probe1

**Comment by Probe1** [comment]
Really?  That sucks.  

That's why god gave us subtypes though.

**Comment by lawmaker666** [comment]
you just completely ignored my idea to make the safe something worth breaking into!
I don't even want you to add the stupid axe!
I want you to use your imagination and surprise me! 
If you're wondering why ss13 stopped being fun for you to play it's because there was no mystery left! Now when you add a new feature you let everyone know what you're doing so there's no discovery for the players. There's no fun there's no risk there's no failure. 
ADD SOME MYSTERY TO THE VAULT SAFE! 
BE MORE LIKE GOON!

**Comment by Probe1** [comment]
There is a difference between mystery and admin only items that beat everything else in the game.

The only times an energy axe have been spawned that I'm aware of, deadmin requests revved up.  No one likes getting one shotted.

**Comment by jknpj** [comment]
Lawmaker request makes sense but the axe needs to be AXED from every map

**Comment by lawmaker666** [comment]
instead of axe make an item from a random list of cool things appear in the safe, then make something dangerous like the energy axe a 1% change to spawn in the safe!
and then don't tell us what's on that list, actually don't tell us if you added it or not either
let it become a spess myth or a greytide legend told by clowns in hushed tones in maintenance

**Comment by Probe1** [comment]
Why not just an energy axe that is equivalent to an esword?  It will still be the most powerful melee item on the map.  Everyone wins.

I agree with @jknpj these are two separate issues.  I'm not going to get bent out of shape over the lawmaker I'm just not going to add it myself.  I will personally help you become a mapper if you would like to add it.

**Comment by ghost** [comment]
I'm very much against map homogenisation - if all maps are the same then there's no reason to vote deff over box

**Comment by ghost** [comment]
Adding a lawmaker to every map doesn't suddenly remove the reason to vote Deff. 
There are probably very few regular HoS players who even use it or want it. 
People vote Deff as a troll, or because they like the large map size, the sprawling maintenance, the chance of some neat goodies when exploring. Maybe they like a certain department more on it. Personally, I like the bar and robotics on Deff more than the other maps. 
On every map the CMO gets a hypospray, on every map the CE gets his belt.
What does a HoS get on anything outside of Deff? A poopy telescopic baton which is only good for beating people to death because its stun is so short. 
All the heads deserve a unique goodie across all maps, if you want some spice between each map then we should look into add more things.

**Comment by Shadowmech88** [comment]
The name of the gun is *Lawgiver*, not "lawmaker."

**Comment by ghost** [comment]
Oh, well ... 
My points still stand!

**Comment by Exxion** [comment]
Homogenization for no good reason: Bad
E-axe in the safe: Worse

**Comment by Probe1** [comment]
I'll put a PR up later this evening and we can see what people think of replacing it with an esword tier energy axe.

Maybe @Shadowmech88 would like to put the lawgiver in HoS lockers.

**Comment by FudgePucker** [comment]
I had an idea for an HoS prized weapon like the Captain gets his recharging laser cannon.

A semi auto shorty shotgun that can fit in your backpack or holster. You can load it with lethal or stun shells. It would be a good weapon for the HoS to have so he can have more power on hand when shit hits the fan.
EDIT: holds 3+1 shells, call it something like ol' fateful. Add a rack for it to his wall.

**Comment by Shadowmech88** [comment]
I would rather not be the one to do it, lest I give the appearance of favoritism towards the weapon since I was the one who made it.
At least, I'm not going to unless this issue gets enough positive support.

**Comment by Probe1** [comment]
you know what i'll do it

fuck it.
