### ISSUE TITLE
Two Ian clothes issues

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#12631]
1. Since the security helmet got renamed to the tactical helmet Ian cannot wear it. No more Sgt. Ian.

2. The ghost Ian costume (bedsheet) is missing it's sprite now. Name changes to ghost, and his barks become spooky but it still looks like regular Ian.

**Comment by 9600bauds** [comment]
>Since the security helmet got renamed to the tactical helmet Ian cannot wear it. No more Sgt. Ian.

It checks type directly instead of doing istype() :clap:
