### ISSUE TITLE
Metaclub has several toolbelts that are incorrectly pathed

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12636]
is
/obj/item/weapon/storage/belt
should be
/obj/item/weapon/storage/belt/utility

Will fix.

**Comment by FudgePucker** [comment]
Not a bug, belts can hold any pocket able item instead of only tools. There is also one in mechanics lab in box.

**Comment by Intigracy** [comment]
They should be given a different sprite.

**Comment by Probe1** [comment]
I'll re-add them as a new item with a new sprite when the sprite is made.

**Comment by Probe1** [comment]
I will re add them later today.
