### ISSUE TITLE
10,000 bees in a suit (but not really)

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#12639]
Sprites for plasmaman suits specific to beekeepers and lawyers. 
![plasmalaw](https://cloud.githubusercontent.com/assets/15067109/20762489/6c2cbbb6-b71e-11e6-8dac-463b3b097f99.png)
![buzzman](https://cloud.githubusercontent.com/assets/15067109/20762501/74dddf38-b71e-11e6-92fa-dffe0006d89a.png)
I would also like to request that the plasmaman suit orderable from cargo is changed from the assistant suit to the generic, non job specific one (that lawyers currently use).
Download link for sprites: http://s000.tinyupload.com/index.php?file_id=04078784234571162324

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/20762930/1c4a2098-b6f6-11e6-9deb-38115b362b08.png)

http://fallout.wikia.com/wiki/AntAgonizer

**Comment by ghost** [comment]
bzzz

**Comment by AI-Is-Rogue** [comment]
just bee yourself

**Comment by Ephx1** [comment]
Neat despite how incredibly stupid the beekeeping one is.

**Comment by Gringonius** [comment]
I like both sprites but the bee suit seems a bit too silly for something not out of the theater vendor.

**Comment by ComicIronic** [comment]
Are you not going to add them in?

**Comment by Probe1** [comment]
He's scared of coding.  

I'll add it to the autodrobe but I'm hesitant to make it a job default without people telling me to do that.

**Comment by Shadowmech88** [comment]
Wasn't he the one that coded the bananium sword?

**Comment by ComicIronic** [comment]
Make the lawyer one a job default, but put the bee one in the autodrobe.

**Comment by Ephx1** [comment]
Making the bee suit standard is like we made a vox xenobiologist suit that looked like a xeno.
Perfectly fine as an autodrobe thing, though kind of weird race specific clothing is in there.

**Comment by Shadowmech88** [comment]
Vox xenobiologist suit that looks like a xeno when?

**Comment by Blithering** [comment]
Making the bee suit autodrobe or cargo crate only seems like a fair compromise to me, Although I agree it's a little strange to have race specific stuff in the autodrobe.

**Comment by Probe1** [comment]
It has human specific stuff that vox can't wear doesn't it?

**Comment by ComicIronic** [comment]
Humanonormative society strikes again.

**Comment by Ephx1** [comment]
The only things that cannot be worn by vox are plasma man suits, and human hardsuits.
Damn, they could even wear human oxygen masks last I checked.
