### ISSUE TITLE
cant reach the d20 in the wizard hideout (metaclub)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12641]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

the d20 cant be reached without breaking the tables
>What you expected to happen
d20

>What actually happened
cant get it

>Steps to reproduce if possible
be in the wizard hideout in the metaclub station and see how you cant reach the d20

**Comment by Shadowmech88** [comment]
Not saying the mapping couldn't also be changed, but could you get the d20 by buying Bound Object, using it to retrieve the d20, and then refunding the spell?

**Comment by Probe1** [comment]
That's a pretty ingenious idea @Shadowmech88

**Comment by Sprok0** [comment]
You could also buy blink and use it until you end up next to it, or mutate and break the table.

**Comment by Allspice** [comment]
Unless that was changed recently can't mutate on Z2

**Comment by Shadowmech88** [comment]
This might be worthy of a separate issue, but the NOZ2CAST flag tends to occasionally fuck over wizards who try and use their spells on the escape shuttle, since it's placed on Z2 while in transit.

**Comment by Sprok0** [comment]
I took Z2NOCAST off blink and mutate recently, specifically because of that

**Comment by Shadowmech88** [comment]
Jaunt also has it, doesn't it?
