### ISSUE TITLE
Posters commemorating that time the engineering team flew too close to the sun

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#12647]
A couple of posters celebrating the meme machine (https://www.youtube.com/watch?v=pIiBB1dA-3o).
![noshardforu](https://cloud.githubusercontent.com/assets/15067109/20782324/aad81edc-b782-11e6-91eb-38a61db0eea7.png)
Nick's shard ban
![engineering](https://cloud.githubusercontent.com/assets/15067109/20782353/f3f6304a-b782-11e6-986b-92716ff33238.png)
Engineering at it's finest
Download link for icons: http://s000.tinyupload.com/index.php?file_id=01811044685279698653

**Comment by liltiptop** [comment]
>When you meme so hard in a pipe simulator that you're remembered as a legend.

Thanks for making the posters m8, they look great!

**Comment by Shadowmech88** [comment]
>BAHHU

**Comment by Kurfursten** [comment]
I think the 3-shard poster is fine, although making a poster of someone's static seems to tread very closely to circlejerking. It reminds me of Niggly wanting to add gashapon toys of well known static players - something that was rejected at the time.

I don't think we're on a slippery slope to waifu body pillows or anything, but for content, let's try to keep it about the game and not about the players.

**Comment by Gringonius** [comment]
>It reminds me of Niggly wanting to add gashapon toys of well known static players - something that was rejected at the time.

His OC librarian and Furbeh's character are on the current code, though. If there's a slope, we already slipped down it long ago with these two exceptions.

**Comment by Kurfursten** [comment]
Nevill was commented out and Niggly's was renamed to "Toy Snowflake", description "What a faggot"

But yeah you're right they did slip through, once.

**Comment by Ephx1** [comment]
No, they aren't because pomf told niggly to cut that shit out

**Comment by Zth--** [comment]
**Yes** to the shard one, **no** to the other one
