### ISSUE TITLE
Urist McCook tried to knock you unconscious!

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#12643]
...is a weird message to see when you were already unconscious.

This is a message from the shitty rolling pin/briefcase custom attack, which is really, really bad

**Comment by ComicIronic** [comment]
Blech.

> There's a `for(var/mob/O in viewers(M, null))` in briefcase code

BLECH

Who wrote this

**Comment by Intigracy** [comment]
It's extremely old oldcode.
