### ISSUE TITLE
Shutters on the HoP office windows on box. Good idea? Bad idea?

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#12646]
The box station HoP office windows have no shutters to close in emergencies, unlike the other parts of the bridge. It might be handy to add some, as I have found the ones on meta really useful for hiding behind.
Then again, it might be a bit too secure if they were put in place. Who knows?

**Comment by Probe1** [comment]
We really need a way to destroy shutters (without explosions)

Don't get me wrong I like the HoP idea.  But think of it this way.  Shutters are stronger than rwalls.

**Comment by Intigracy** [comment]
You can open them with a crowbar if they're unpowered.

**Comment by FudgePucker** [comment]
Can we make it so they are unpowered for a few seconds when emp'd then?

**Comment by Huuuuuuuuuuugo** [comment]
Have lever toggleable shutters surrounding the tile facing the HoP's table

Slam them down and trap the miscreant in so the Nice Men in Red can take them away

**Comment by SysadminJeroen** [comment]
Is anyone doing this right now? Because if not I can map it.

**Comment by Probe1** [comment]
Go for it.

**Comment by Blithering** [comment]
@Huuuuuuuuuuugo Meta HoP office has exactly that, and also wall mounted flashers. You never need leave your desk again!

**Comment by SysadminJeroen** [comment]
I'll be going to map this right now, I'll update my status here and refer the PR that I'll make to this issue.

**Comment by SysadminJeroen** [comment]
Opened #12699.

**Comment by SysadminJeroen** [comment]
Re-open?

**Comment by Blithering** [comment]
If you're going to be reopening the PR then this issue isn't really needed anymore. The discussion is probably best kept to that.
