### ISSUE TITLE
Chat not displaying

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12645]
(WEB REPORT BY: pepsipuppy69 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Chat didnt show up

>What you expected to happen
Chat to show up

>What actually happened
Chat was shifted to the left and had an error message, I could read 
"maximum of 5 times.
,use the bug report
ght of the window"

>Steps to reproduce if possible
Just opening the game

**Comment by Exxion** [comment]
#12583
