### ISSUE TITLE
Bugged Chat on Windows XP

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12654]
(WEB REPORT BY: skippers REMOTE: 172.93.109.202:7777)
Chat doesn't load at all on Windows XP.
Assuming it's because internet explorer is outdated.
Chat works fine on all other servers.

**Comment by ComicIronic** [comment]
I
E
8

**Comment by gooza3** [comment]
Alright I'm going to type out exactly how to fix this--
If you're running Windows XP from a virtual machine/ fresh install it DOES NOT COME WITH INTERNET EXPLORER 8
I'm not sure what version it has but it's older than IE8.
Microsoft doesn't offer IE8 on their website anymore so you need to go to a different website to download it- http://www.majorgeeks.com/files/details/microsoft_internet_explorer_8_for_xp.html
That website wouldn't even load at all on the version of Internet Explorer I had so I needed to download it from a public library, put it on a USB and then put it onto my computer.
If you're running it from a Virtual Machine you could subvert this by using a Shared Folder
Anyway, just run that executable, restart your PC, and then it should be fixed : )

**Comment by Zth--** [comment]
Make a wiki entry? Something called "Troubleshooting" would be cool

**Comment by CptWad** [comment]
http://ss13.moe/wiki/index.php/Troubleshooting

remove tag
