### ISSUE TITLE
Wheelchairs don't bump open windoors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12657]
(WEB REPORT BY: ammy55 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 4ea5540e64a350ed083a937f31c7fb94f962cb02 

>General description of the issue
Wheelchairs don't open windoors when you bump into them

>What you expected to happen
The windoor to open when i bump into it

>What actually happened
The windoor didn't open

>Steps to reproduce if possible
Get in wheelchair
Bump windoor

**Comment by ComicIronic** [comment]
Does this happen with other vehicles as well?

**Comment by Exxion** [comment]
If memory serves, yes
