### ISSUE TITLE
Wizard revamp - mana

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#12659]
Wizards will keep spell cooldowns, slight changes
Wizards will still have points to buy spells with
Wizards also have a mana supply, similar to many other antag modes like lings, vamps, alien, blob, ect
Use spell, need mana
I will code all of this myself
I will even add new unique staves and their interactions with mana
Current staves are fine, won't need mana
New staves won't be any upgrades of existing staves
The cavendish banana you eat today was not always the bananas we always loved! The previous banana that most of the world ate was called the gros michel! The gros michel was larger, easier to store due to less of a curve, took longer to spoil, and generally is agreed to taste better than todays cavendish banana. Due to a fungus outbreak that was a danger to all gros michel bananas due to the plants being too similar and the fungus unaffected by fungicides, we had to make a switch to the cavendish we use today.
I will add gros michel bananas. They will be a vox plant
New spells with the introduction of mana!

**Comment by Kurfursten** [comment]
I thought the whole point of Wizards is that their spells don't use any resources. It makes them different from vamp ling alien blob etc.

Because you know, unlike those things, there's no progression with wizard. You don't set up an alien base and evolve and add troops or more resource blobs or get more powers from extra blood or genomes.

**Comment by Killette2** [comment]
That's what magical artifacts are for, non mana use.
I wouldn't compare changeling genomes to mana, genomes would be spells. Mana would be the chemicals changelings use when they use their abilities. Mana doesn't necessarily imply or even need progression and it can further enable more possibilities with wizard.

**Comment by Kurfursten** [comment]
You're missing my point entirely. Lings only get stronger as the round goes on so it makes sense to limit their skills by chemical use. Similarly, vampires get stronger as the round goes on with blood, etc.

Wizards don't get stronger unlike all of those antags. Adding another limit to how often they can cast spells outside of the natural cooldowns doesn't "enable more possibilities", it just slows burst spell use by capping the maximum number of spells that can be cast in rapid succession. Unless you're planning to remove cooldowns, or give wizard new spells or something to compensate for the new artificial limit you're adding, but you haven't announced anything like that.

**Comment by Gunosaguki** [comment]
I'd be fine with it For spells like Blink, which are too easily abused to be gods

**Comment by Ephx1** [comment]
So a cooldown on top of another cooldown

**Comment by Intigracy** [comment]
Pretty much yeah.

He said in the OP he intends to keep cooldowns in as well.

**Comment by ghost** [comment]
Could you explain why a permabanned player would code something for a server they cannot play on. Or why this would occur months after being banned?

Not to mention it's a shitty idea that only weakens wizards for no real reason, wizards already die easily, making their spells even more useless won't improve the round type.

**Comment by Ephx1** [comment]
I don't see how this expands wizard abilities then. Unless he's also allowing more spell points, two cooldowns for more spells?

**Comment by Killette2** [comment]
I said I'd add new spells and slight changes to cooldowns. What is the problem if I code this? I expected you to read this better @Kurfursten

**Comment by Kurfursten** [comment]
>What is the problem if I code this?

I've told you twice already. Wizards are not a progression antag and don't need another spell limiter tacked on. I hate to just parrot back what you've said but "I expected you to read this better". This isn't new information, it's what both previous posts said.

**Comment by Killette2** [comment]
I could show examples of what I made but if you want to just reject code without seeing my work I'll just close this and go back on my other acc

**Comment by ghost** [comment]
Maybe if your idea wasn't completely shit people would like it more. And throwing a hissy and closing the pr because you got some negative feedback doesn't help your case either.

Why don't you start by fixing some bugs to show people you can code well, then start introducing ideas.

**Comment by mrpain666** [comment]
Why are you making issues for a codebase/server you're banned from?

**Comment by Shadowmech88** [comment]
If you already have the code, why bother making an issue at all? Why not just make a PR and let people comment on that?

**Comment by Gef21** [comment]
Remove cooldowns, add mana

**Comment by Shadowmech88** [comment]
All that would do is allow wizards to hoard all their mana into casting one or two most-effective spells.

Instead of casting lightning once and then moving on to blink/subjugate/et cetera while lightning recharges, you can now just funnel all your mana into lightning and become a killing machine.

**Comment by Gef21** [comment]
Funny, tho

**Comment by ghost** [comment]
has this man just admitted to ban evading?

**Comment by ihadtoregisterforthis** [comment]
Be on the lookout for Killette3
