### ISSUE TITLE
Medibots do not check for overdose directly before injecting.

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#12653]
#### Description of issue
Raised in #12262.
Medibots will check if the patient has meds to begin with, but will not check just before injecting, leading to overdoses.

#### Difference between expected and actual behavior

Medibot stops itself from taking a life.
Medibot takes a life.

#### Steps to reproduce 

Stand near a medibot with brute damage, have it start injecting you, eat 29 units of bicard in a pill, get OD'd on by the bot when it finishes injecting.

**Comment by Iamgoofball** [comment]
another good way to reproduce it(and more common) is having 3-4 medibots doing stuff at once

**Comment by JustSumBody** [comment]
Hey here's an image
![image](https://cloud.githubusercontent.com/assets/19365096/20820387/eb6bc030-b808-11e6-9574-29b64967d66e.png)
Someone stacked something like 10 medbots of each kind in one spot then punched themself, this happened

**Comment by ghost** [comment]
Okay, for most of these it'd be a doddle, you'd just have a max(reagent.overdose, (mob.reagents.get_reagents_by_name[reagent_name].amount + to_inject)), except those fucking weird ones that OD based on time in the body.

**Comment by Iamgoofball** [comment]
hi im a dumb stupid dumb idiot who cant read

**Comment by ghost** [comment]
There is just no talking with you, foogall, is there?

**Comment by Intigracy** [comment]
Ignore goofball.
