### ISSUE TITLE
IPCs when...

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12655]
...we narrow down what the heck an IPC will be.

So far what's been discussed is
- Humans but robotic
- Have a screen for a face that the emoticon on it can be adjusted, similar to a pAI

So, discussion time, what the fuck should an IPC be?

**Comment by Intigracy** [comment]
What does IPC stand for?

**Comment by kol1th** [comment]
Selectable models as "skin color"
Brain in chest, can survive but not see without a head 
Would not feel pain
Would not breathe 
Instead of eating, they can succ a battery to replenish some charge, or do it the ghetto way and hook themselves up to a powered cable (take damage if it's too much charge?) 
Overheat in low pressures due to lack of airflow
Regular chems and such wouldn't work, they would have to use nanopaste and some new reagents as meds
Would probably see science more than medbay
Positronic brain instead of human brain 
Can ghetto repair themselves with tools instead of nano paste, think of it like bandages vs. trauma kits

**Comment by kol1th** [comment]
@intigracy Integrated Positronic Chassis

**Comment by ghost** [comment]
![faggotwithoutgithubno1](https://cloud.githubusercontent.com/assets/9110500/20820344/861826d6-b832-11e6-8c03-9ca3ddc14ce4.PNG)

**Comment by Exxion** [comment]
Pros: Sounds like a cool, legitimately-different race
Cons: Holy shit that would require, at the very minimum, a complete rewrite of organ code
(Which we need to do anyway but nobody's actually going to do it)

**Comment by JustSumBody** [comment]
How hard could it be :tm:

**Comment by kilozombie** [comment]
Just port it from wherever
I don't care that none of it not matches up to our codebase just copy and paste the code in and launch it
LAUNCH IT

**Comment by AutismSpider** [comment]
well if you do port it is with or with out hot milf add on they have and emag stuff you can do to them?

**Comment by ghost** [comment]
@AutismSpider what

**Comment by kilozombie** [comment]
Anyway, from what I remember from Paradise, IPCs are primarily people who are machines, rather than machines who were previously people (borg). So... they have no lawset, and some special racial traits, I don't know.

**Comment by kol1th** [comment]
@skullyton What he means is, there's a malf module that essentially lets them slave an IPC to themselves

**Comment by PJB3005** [comment]
Just an FYI but it took bay multiple years worth of mob code rewriting to get them into a non-buggy state.

Also, didn't pomf veto them at some point?

**Comment by ghost** [comment]
Your meme anime tv robots are SHIT.

Scootaloos need to be added.

**Comment by Exxion** [comment]
Stop saying we need to "add" Scootaloos.
We already have them. They're just very unfinished.

**Comment by gbasood** [comment]
@PJB3005 pretty sure this idea has been veto'd more than once already yeah

probably because what this idea amounts to is "borgs, but stronger"

**Comment by Ephx1** [comment]
> Borgs but stronger

The race that can't go into space at all?
The race that's as strong as a human with two modes of healing?
The race that can instantly be emagged?
The race that can't be revived in any form?
The race that can't improve their batteries?

Stronger than borgs you say? Sure, they have hands but that's about it.

**Comment by AI-Is-Rogue** [comment]
I thought they could be revived, just not through defibrillators or cloning.

**Comment by Ephx1** [comment]
Last I checked on Bay, if you die as a robot that's it, game over.
They could have changed it, but that would severely fuck up their lore so I doubt it.
(But they also change their lore a lot so whatever.)

**Comment by AI-Is-Rogue** [comment]
IPCs seem to be on several different servers, each with their own mechanics and I'm not entirely sure which wiki to use as reference here.

**Comment by gbasood** [comment]
@Ephx1 
\>humans but robotic
so lawless borgs with hands and no modules isn't borgs but stronger?
And unless I'm mistaken borgs posibrains/mmis can be popped into a new body at any time, so there's a revival for you

Actually you kind of just listed a bunch of ways they'd literally be borgs but stronger

**Comment by AI-Is-Rogue** [comment]
I think we need to stop comparing them to cyborgs or thinking of them as cyborgs but with hands.

**Comment by Ephx1** [comment]
Being unable to go into space ISN'T a benefit.
Borgs are STRONGER than humans, yet IPCs share the same amount of health as humans AND have limited healing options like borgs.
IPCs can't be revived (at least on bay) because they're supposed to be expensive as shit.
Being unable to improve their batteries is NOT a benefit.

What the fuck are you smoking, sood?

**Comment by Ephx1** [comment]
Being instantly emagged is debatable, but it's no different from a greyshit patch, vampire stare, or rev flash.

**Comment by Intigracy** [comment]
Just to be sure, they can't interact with things like borgs can, right. They're just humans with laws and fewer ways of healing.

**Comment by Ephx1** [comment]
Nah, from what I've seen the only special action they have with machinery is setting intent to disarm then sapping energy from APCs.

**Comment by AI-Is-Rogue** [comment]
They don't have laws, Intigracy.

**Comment by Shadowmech88** [comment]
Would they be rendered immobile by stun weaponry? A great deal of the "strength" that borgs hold over humans is their immunity to stuns.

**Comment by Ephx1** [comment]
I imagine that's entirely up to whoever ports them, as most servers that have them use that weird multiple stuns system.

**Comment by kol1th** [comment]
Jesus christ they're not "cyborgs with hands", they're "humans but metal"

**Comment by ghost** [comment]
All our aliens are just "Humans but something"

**Comment by JustSumBody** [comment]
>whine that race ideas are "humans but something" when they're too similar

>whine about snowflake when races are too different

Do we just not want new races then or what so nobody wastes time coding it

**Comment by ghost** [comment]
Probably best to just not get more races, non of the non-human races are currently any good so I doubt IPCs would be either.

**Comment by PJB3005** [comment]
How about no new races and actually try to fix the fucking code?

**Comment by kol1th** [comment]
@pjb3005 when you code it

**Comment by Imagebard** [comment]
>When a good contributor tells you to fix code instead of being a smalldick but you remember he's wrong because he can go do it himself

**Comment by SonixApache** [comment]
Hey I came here to revive this after playing as IPCs on some othercode tests.

IPCs on Tau Ceti can't fix themselves. They also insta-explode when hit by an EMP. Not sure if you can revive them in any way. Emagging their bits (full-body prosthetics) just sets them to explode, much like our robo-limbs.
