### ISSUE TITLE
ATM issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#12656]
#### Description of issue
i was a miner last round, i gone to the ATM near cargo to put some money in the virtual wallet, used my ID on the ATM, put my account number and pin and clicked submit; nothing happened and there were also no way to take my ID back.

EDIT: during the new round seems to work just fine by the way.

#### Difference between expected and actual behavior
a working ATM;
didn't work.

#### Length of time in which bug has been known to occur

just happened, but i haven't played in weeks, so i don't know.

#### Server revision

4ea5540e64a350ed083a937f31c7fb94f962cb02 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by uazuaz** [comment]
during the new round seems to work just fine by the way.

**Comment by PJB3005** [comment]
Sounds like a runtime?

**Comment by uazuaz** [comment]
now i remember that during that same round, also my lantern and helmet light weren't working; in the following round they were fine again.
maybe the two issues were related?

**Comment by uazuaz** [comment]
didn't happen anymore in these 2 days, this issue could be closed maybe.
