### ISSUE TITLE
ATM in Cargo office spawning withdrawn cash wrong

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12668]
(WEB REPORT BY: qbone REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 19128f20e69e267d413ddaf91722b1146516a4c9 

>General description of the issue
ATM in Cargo spawns withdrawn cash in grille between Warehouse and Cargo office instead of at the ATM, or in front of it. 

>What you expected to happen
I expected the Withdrawn Cash to appear where the ATM is.

>What actually happened
It spawned in the grille to the left and behind the ATM, I had to break through the glass and grille to get it.

>Steps to reproduce if possible
Withdraw cash from the ATM in Cargo Office

**Comment by PJB3005** [comment]
WHAT.

MAP.

**Comment by Kurfursten** [comment]
Looks like it has to be Box. When did someone sneak in that new ATM in the back of the office? They did a poor job with it.

**Comment by Probe1** [comment]
(wasn't me)

Noted.
