### ISSUE TITLE
Grays can use project mind while playing Mime

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#12665]
Clearly grays should be job restricted from mime, or neutered of their racial bonus when playing mime.

Requesting 'OH GOD ITS LOOSE', and 'Honk' labels

**Comment by Probe1** [comment]
![853746ec2ee800efe241767a5c6b719e](https://cloud.githubusercontent.com/assets/8550416/20864063/0894a904-b9af-11e6-8a42-68c6362ecede.png)

I guess we can disable it if its a problem but they are ayys first, mimes second.

**Comment by robintime** [comment]
changed in #23180
