### ISSUE TITLE
Vox are still able to be captain in roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12666]
(WEB REPORT BY: morphi REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
19128f20e69e267d413ddaf91722b1146516a4c9 

>General description of the issue
Vox are still able to become captain in roundstart when they're supposed not to, and the job even shows as "Unavailable" on the job preferences.

**Comment by JustSumBody** [comment]
If you had a slot with captainl/hop/whatever saved on high with a nonhuman before the change, it's still there unless you reset the job prefs. It's how I still play diona cap/Skelly Hos

**Comment by ComicIronic** [comment]
That's disgusting.
