### ISSUE TITLE
Mortar is missing it's icon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12674]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Blithering** [comment]
Pressed enter too early, 77ced68b81a56c793a5ea87adab8d5f5e8b8a66d was the revision. 
The mortar made from a bowl and a sheet of metal now spawns without an icon, kinda difficult to use like that. It had one up until recently.
