### ISSUE TITLE
Cult is too uncommon

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#12672]
I went to http://stats.ss13.moe/matchlist and checked how many times was cult played in the last 10 pages. That throws 6 cults... in 240 games. Which is 2.5% of chance.

I did the same for extended: 8.3% in the last 240 games.

Is this on purpose? In my experience cult is far more fun than extended

**Comment by Probe1** [comment]
I came to the same conclusion when checking the stats page a few days ago.  But it's important to note that extended can happen at any pop and cult can only happen at certain ones.

**Comment by Allspice** [comment]
Cult is available at 15+. I believe we usually have 15 or more round-start so that still leaves extended being about twice as common as cult even when cult is possible.

**Comment by Probe1** [comment]
I agree.

**Comment by Intigracy** [comment]
**PROBABILITY EXTENDED 1**
PROBABILITY MALFUNCTION 3
PROBABILITY BLOB 4
PROBABILITY NUCLEAR 5
PROBABILITY WIZARD 3
PROBABILITY REVOLUTION 2
PROBABILITY REVSQUAD 2
PROBABILITY DOUBLEAGENTS 1
PROBABILITY CHANGELING 5
**PROBABILITY CULT 2**
PROBABILITY TRAITORCHAN 3
PROBABILITY AUTOTRAITOR 5
PROBABILITY HEIST 2
PROBABILITY RAGINMAGES 2
PROBABILITY VAMPIRE 3

**Comment by Probe1** [comment]
>changeling 5

this is why we cant have nice things.

**Comment by Zth--** [comment]
I did the same with wizards: 12.5% (only wizards, not counting ragin' ones, which is 6,6%). Changelings 12.5%.

So, IMO numbers should be tweaked

**Comment by jknpj** [comment]
PROBABILITY EXTENDED 1
PROBABILITY MALFUNCTION 1
PROBABILITY BLOB 1
PROBABILITY NUCLEAR 1
PROBABILITY WIZARD 1
PROBABILITY REVOLUTION 1
PROBABILITY REVSQUAD 1
PROBABILITY DOUBLEAGENTS 1
PROBABILITY CHANGELING 1
PROBABILITY CULT 1
PROBABILITY TRAITORCHAN 1
PROBABILITY AUTOTRAITOR 1
PROBABILITY HEIST 1
PROBABILITY RAGINMAGES 1
PROBABILITY VAMPIRE 1

FIX'd

**Comment by Megamaw** [comment]
PROBABILITY EXTENDED 1
PROBABILITY MALFUNCTION 1
PROBABILITY BLOB 1
PROBABILITY NUCLEAR 1
PROBABILITY METEORS 1
PROBABILITY WIZARD 1
PROBABILITY REVOLUTION 1
PROBABILITY MONKEY 1
PROBABILITY REVSQUAD 1
PROBABILITY DOUBLEAGENTS 1
PROBABILITY CHANGELING 1
PROBABILITY CULT 1
PROBABILITY TRAITORCHAN 1
PROBABILITY AUTOTRAITOR 1
PROBABILITY HEIST 1
PROBABILITY MEME 1
PROBABILITY RAGINMAGES 1
PROBABILITY VAMPIRE 1
PROBABILITY ZOMBIE 1


fixed further

**Comment by PJB3005** [comment]
Where's DINOWARS?

**Comment by Probe1** [comment]
Below Berlin Mode

**Comment by gbasood** [comment]
>cult is the same as rev and revsquad

awful tbh
up cult
also nerf changeling holy fuck

**Comment by DeityLink** [comment]
I think it's no longer an issue, there at least 4 cult rounds per week, that's nice. @MadmanMartian
