### ISSUE TITLE
Disease Analyzer doesn't update its icon on power_change

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12679]
#### Description of issue

Disease analyzer keeps running after it begins analyzing a virus.

#### Difference between expected and actual behavior

It to shut off
It kept running

#### Steps to reproduce 

Start it up, turn off power

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Wizardcrying** [comment]
`code/modules/virus2/analyzer.dm`, line 76-79
```
/obj/machinery/disease2/diseaseanalyser/process()
	if(stat & (NOPOWER|BROKEN))
		return
	use_power(500)
```

**Comment by DamianX** [comment]
It doesn't keep analyzing but it doesn't update its icon, either.
