### ISSUE TITLE
Disposals Access

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#12671]
At some point, on Box, someone decided to restrict just the right-hand door to final disposals. I'm not sure who has access to it now (Janitor?) - but the QM and Cargo Techs can't get in anymore from that side, but they can waltz in the other entrance.

Please give cargo back access, sometimes a crate gets sent to disposals by mistake.

**Comment by Probe1** [comment]
I'll have a box PR out this evening.  There's 3~ of these I can knock out in a few minutes.
