### ISSUE TITLE
Disease Splicer is a console and better fits as a machine

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12670]
#### Description of issue

The Disease Splicer cannot be upgraded and performs an integral task in manufacturing viruses.  No matter how good the rest of virology equipments upgrades are, it still acts as a wall that prevents you from working in a quick and effective way.

#### Difference between expected and actual behavior

All machines to be machines rather than a hodge podge of consoles and machines.

#### Specific information for locating

[code\modules\virus2\diseasesplicer.dm]

**Comment by ComicIronic** [comment]
Does the splicer have a delay in working?

**Comment by Probe1** [comment]
Yes.  But I cannot for the life of me find out how from its file.

**Comment by ComicIronic** [comment]
If any of the variables `scanning`, `splicing`, or `burning` are above 0, the machine lowers them every `process()`. While the variables are above 0, it stops the user doing anything. So if you set it to 100, after 100 `process()`s, you can use the machine again.

**Comment by ComicIronic** [comment]
This is a bad way to do fixed-delay code.

**Comment by Probe1** [comment]
I'd have to agree since it took a code rocket scientist to explain it to me.
