### ISSUE TITLE
Viral Samples don't properly update their description after being spliced.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12686]
#### Description of issue

When you insert a viral dish into the splicer you can change what symptoms and diseases it has.  You can examine these viral dishes by shift clicking or using the verb examine.  The description is not updated when a new disease is written over an old one on the Virus Sample.  
#### Difference between expected and actual behavior

It should rewrite the description with the current symptoms

The old symptoms are still listed

#### Steps to reproduce 

Grow a virus sample in the pathogenic incubator, analyze it in the disease analyzer, then splice it in the disease splicer.  The new spliced disease will not be present.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
Think you have to rescan it after that point, as it's the scanner that does the 'printing'

**Comment by Probe1** [comment]
It won't let you.  When placed inside a scanner it will have already scanned it and not change the items description.  You _could_ breed the virus into blood, isolate the virus in a centrifuge, then analyze the virus again which takes anywhere from 45 seconds to 3 minutes.

**Comment by ghost** [comment]
Oh, well that does seem odd then

**Comment by Wizardcrying** [comment]
If a virus dish's `info` var is defined, then it shows the extra examine text and outputs `info`'s contents at the end.
However, `code/modules/virus2/diseasesplicer.dm` doesn't seem to have any mention of `info` in it.
