### ISSUE TITLE
All viruses progress through stages at identical speeds

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12684]
#### Description of issue
Feature Request

```	var/stageprob = 10 ``` is set at the top of \code\modules\virus2\disease2.dm but never modified anywhere else.

#### Difference between expected and actual behavior

Viruses to have a varied and colorful set of speeds.

They all act the same.

**Comment by Kammerjunk** [comment]
I wouldn't mind a range of 1-10 which works the same way as the other variables in virology (which I know nothing about tbh)
Bring on the superviruses

**Comment by ghost** [comment]
Okay, here's how we could change this;

Currently, there's a feature where adding a minute amount of toxins (from nanomed) to the pathogenic incubator decreases infection chance, what if other chems could change the different things about it?

Adding hyperzine could increase the stageprob, but also the cure rate. Adding anti-toxin could reduce the cure rate, but decrease the stage prob. Hyronalyn could reduce the major mutation chance, that sorta thing

**Comment by ghost** [comment]
Having a degree of random variance would make things less predictable, which

**Comment by Probe1** [comment]
which what?
