### ISSUE TITLE
Players can use cheat engine to see through static

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12682]
https://www.youtube.com/watch?v=APZz4sn1xLY
I believe that we merged a fix for this from TG but it didn't actually fix this specific video, allegedly.

**Comment by jknpj** [comment]
What in the actual fuck

**Comment by PJB3005** [comment]
@Intigracy uuuuuuuh.

**Comment by ComicIronic** [comment]
This was pretty much always going to be possible, because the images are just sent to the client over the actual game - a memory editor like CE can take them off with enough effort.

**Comment by BestName** [comment]
😂👌

**Comment by jknpj** [comment]
Is it possible to know when the AI is using something in a cameraless place?

**Comment by ComicIronic** [comment]
Yep, AI interactions are probably rare enough to let us check camera coverage of something whenever the AI interacts with it.

**Comment by Intigracy** [comment]
The way it works is they search for the icon_state name to delete it.

The icon state doesn't exist so there's nothing to search for.

If you can reproduce it, please explain how.

**Comment by ghost** [comment]
@Intigracy if you look in that video, as I said in the OP, no, that's not how he's doing it

**Comment by Intigracy** [comment]
If you have a solution you're welcome to code it.

**Comment by jknpj** [comment]
Isn't it a BYOND problem? I mean, the fact that can use CE in BYOND at all

**Comment by PJB3005** [comment]
@MrStonedOne panic.

**Comment by ComicIronic** [comment]
Being able to use CE in any game is hardly a problem - CE works on the fact that any game will have values in memory, and coding defensively against CE is incredibly difficult, since you need to essentially tie a lot of values together in a non-performant way. Our best bet is to track when people are doing things which would only be possible without static.

**Comment by PsiOmegaDelta** [comment]
@PJB3005 MrStonedOne has already done something about it over at tg: https://github.com/tgstation/tgstation/pull/21884

**Comment by MrsTonedOne** [comment]
thats the old solution. but in there bay talks about their solution.

What you can also do is bind to mouseenter of turfs and just detect mouses going over turfs that they aren't suppose to be able to see, then add in a system that doesn't process clicks if it didn't get a mouse enter recently so prevent using CE to disable the mouse enter events.

**Comment by PJB3005** [comment]
Oh the mouse enter sounds brilliant.

"Ai McShitter has hit way too much mouseenters on invisible turfs, might be hacking."

**Comment by Earthykiller127** [comment]
get off my dick cheating isnt against the rules

**Comment by jknpj** [comment]
>cheating isnt against the rules

Hmmm

**Comment by Earthykiller127** [comment]
http://ss13.moe/wiki/index.php/Rules

**Comment by jknpj** [comment]
>0. Admins may disregard any and all of these rules if they deem it to be in the best interest of the current round, the server, and/or the community at large. They will, of course, be fully accountable for their actions if they exercise this privilege. 

┐(ツ)┌

**Comment by ComicIronic** [comment]
>Don't be a dick. We're all here to have fun, and if you're deliberately ruining other people's fun that's a problem.

**Comment by ihadtoregisterforthis** [comment]
Metagaming is against the rules. Cheating to see what you shouldn't be able to see is metagaming.
It's a deductive argument from there.

**Comment by Earthykiller127** [comment]
All of you kids cited completely unrelated rules. Good job

Bane evasion isn't against the rules either now that I think about it

**Comment by PJB3005** [comment]
![](http://s2.quickmeme.com/img/62/62f538b129e13afc6c7d9b9278b63f63f4c91e1f8fd1077c36e088039bf538f8.jpg)

**Comment by ComicIronic** [comment]
>bane evasion

**Comment by Earthykiller127** [comment]
CIA

**Comment by Wizardcrying** [comment]
The asteroi rises.

**Comment by nervere** [comment]
There's logging for this now, it's very obvious to admins if and when someone tries this.
