### ISSUE TITLE
Defficiency doesn't have a radio intercom in cloning

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#12698]
So if you get cloned and no one is around, you can't yell like a madman

**Comment by Exxion** [comment]
Doesn't it have a button to open the door from the inside like the other maps do, though?

**Comment by Zth--** [comment]
Yeah but when you get out of the cloner you can't even walk

**Comment by Exxion** [comment]
Sounds like you need to get good

In all seriousness though, I'm pretty sure you can walk if you're ejected after a full cloning cycle
Or maybe that's only sometimes

**Comment by Ephx1** [comment]
_only_ sometimes
Sometimes you can jitter over to the door, other times you're stuck on the floor yelling for help or a swift death.

**Comment by Kurfursten** [comment]
If you actually finish the cycle you're stable and out of crit. The big deciding factor in whether you can walk is if the genetic damage is distributed across your arms or legs.

If even one of your legs has too much genetic damage, you are fucked. Crawling when?

**Comment by Probe1** [comment]
On one hand I guess that means I did good by adding those (map feedback is hard to get)

On the other hand I guess I forgot about Deff
