### ISSUE TITLE
Head reconnection ""bug""

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12692]
(WEB REPORT BY: dil9 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
5e4c870d82b76875fe6d887e76f8d0aa4fec7e19 

>General description of the issue
I saw a monkey-man's head off. I saw a dead human's head off. I put the human's head on the monkey-man. His face and name magically change into the monkey-man's face and name.

>What you expected to happen
For the voice and face of the monkey-man to change to the ones of the person's head I just put on.

>What actually happened
The head transformed into the monkey-man's head.

>Steps to reproduce if possible
Saw off somebodie's head. Put another head on their body.

Not really a REAL bug, but it's still pretty silly

**Comment by Kammerjunk** [comment]
Oh no don't let them fix the transplant UI/UE restoration :x
Unless the fix will allow it to be restored just by swapping heads. Then I don't really care

**Comment by Shadowmech88** [comment]
[Feature Request]

Currently the identity of a human mob is tied to its torso, rather than its head/brain. This is dumb and should be changed.
But a lot of organ code is still pretty old, I think, so it might be a hassle.

**Comment by Kammerjunk** [comment]
>Currently the identity of a human mob is tied to its torso, rather than its head/brain.

Yeah that's definitely all c;
You can restore an identity using the head but that's not something that should ever never ever be removed because it's the *only* way to restore identity

**Comment by Probe1** [comment]
christ I think I asked identity to be stored in the brain in 2014
