### ISSUE TITLE
Biofoam injectors are unobtainable (absolute feature request)

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#12703]
![image](https://cloud.githubusercontent.com/assets/16979948/20963396/07663ee2-bc22-11e6-8772-efa771d76567.png)
These things
@Probe1

**Comment by Shadowmech88** [comment]
I had fully intended to add a box of them to paramedics' lockers.
I still do.
At some point.

But if someone else happens to get to it before I do, that's fine with me.

**Comment by viniciuspetch** [comment]
I have to ask: whay they do?

**Comment by Probe1** [comment]
Stops internal bleeding https://github.com/d3athrow/vgstation13/pull/12396

**Comment by ghost** [comment]
Why is there no recipe for biofoam?

Foaming agent, clonex, ice pepper extract to freeze the wound, job's a good un

**Comment by Shadowmech88** [comment]
>Why is there no recipe for biofoam?

Because I didn't want Medbay handing out 50u pills of the stuff. I think it's a nice treat for paramedics to keep their patients from dying on the way to Medbay, but I don't think the reagent should just be the first response of Medbay as a whole toward internal bleeding.

**Comment by kilozombie** [comment]
I have never understood the "chemistry shouldn't be able to make certain useful things" meme. With trail mix they can make rezadone. With xenobotany they can dispense peridaxon. A recipe that requires clonex, foaming agent and ice pepper extract is already a hurdle of needing botany AND needing quite a bit of effort.
Good chemists should have more goals to shoot for. Effort-intensive, requiring cooperation with other departments, sure. But right now once you make the base meds, the rest (even rezadone) is superficial  at best and can be made easily by any guy with the Guide to Chemistry. Lipozine, imidazoline, etc.
Just my opinion though.

**Comment by ComicIronic** [comment]
It makes sense not to give Chemistry a chem solution to what is otherwise a very difficult Medbay problem. You could put cloning in a pill, and no matter how difficult it would be to get, people would still churn them out every round because it would be better than what there was before.

**Comment by Probe1** [comment]
Rezadone kinda does that.  

Anyway I was thinking instead of putting it in the paramedics locker just have it spawn on paramedics, and give it a super high research req with diamonds or something.  Medbay doesn't really have any research above 5.

**Comment by kilozombie** [comment]
And recall how rarely even a competent Medbay actually gets some rezadone going.
Does biofoam completely cure internal bleeding or stop it temporarily?

**Comment by Exxion** [comment]
Stops it temporarily

**Comment by kilozombie** [comment]
That's not even great then. We can already do that with bicard OD I thought.
I see no reason why a competent chemist corresponding with botany shouldn't be able to make more biofoam, honestly.

**Comment by Exxion** [comment]
Bicard stops the bleeding from getting worse and an OD gradually heals it, but it doesn't stop the bleeding.

**Comment by kilozombie** [comment]
Gotcha.

**Comment by Shadowmech88** [comment]
If someone wants to open a PR adding a recipe for biofoam, feel free. But I don't want to do it.

**Comment by FudgePucker** [comment]
I would support a recipe requiring frost oil.

This is one of the few examples of interacting working. Putting it into the protolathe is a GOD FUCKING AWFUL IDEA AND YOU SHOULD FEEL BAD FOR COMING UP WITH IT AS A SOLUTION.

Chemistry wants frost oil. Botany is the only source of it. Now the botanist can offer to make ice peppers in extange for mutagen. Thus adding a use for botany for chemists outside of exotic seeds. Giving it to the feature bloated protolathe would mean medbay never sees biofoam, also the assholes on hyperzine wearing EoD suits with an armory worth of weapons in their bag of holding now gets immunity to internal bleeding.

Giving two different people two parts of a puzzle and telling them to interact works better than giving one person several completed puzzles and asking everyone else to interact with them.

**Comment by Exxion** [comment]
(Xenobio can also make frost oil, but close enough)

**Comment by FudgePucker** [comment]
Xenobio has no use for chemistry because science can just make chemical dispensers.

**Comment by viniciuspetch** [comment]
Well, this idea has my thumbs up emoticon of approval (tm), and I like the biofoam recipe, but there's something lacking: and the injector itself? If the paramedics lose the injectors for some unknown reason (honk), how they'll get another one? I see two options: 1) Protolathe; and 2) Cargonia. One way or the other, we need to find a way to get new injectors.

Unless you'll let us/them use normal syringes, but that's boring

**Comment by Shadowmech88** [comment]
>how they'll get another one?

My original intent was for them to be a limited commodity.

**Comment by viniciuspetch** [comment]
> My original intent was for them to be a limited commodity.

I don't like the idea of being limited because limited roundstart items are all really useful and powerful (like the hypospray and hand tele, for example).

But on the other side, if the biofoam becomes game-changing, then limited injectors might be the better option.

This brings another thing: how biofoam works when being ingested/injected?

**Comment by 9600bauds** [comment]
>It makes sense not to give Chemistry a chem solution to what is otherwise a very difficult Medbay problem. You could put cloning in a pill, and no matter how difficult it would be to get, people would still churn them out every round because it would be better than what there was before.

You can churn out Rezadone every round.

I am the only person I have ever seen to churn out Rezadone every round.

And it's not even good.

**Comment by Shadowmech88** [comment]
>how biofoam works when being ingested/injected?

Are you asking if there's a difference? Or just asking how it works in general?
It doesn't matter how it gets into your body, but while inside it it halts all internal bleeding.

**Comment by viniciuspetch** [comment]
> Are you asking if there's a difference? Or just asking how it works in general?

Sorry, I meant when injected via normal ways (syringe, IV).

If the biofoam injector works like any other injection and just puts the chemicals inside one's body, then disregard everything I said about the injector itself. I thought the bleeding stop would work **only** with the proper injector.

**Comment by Exxion** [comment]
Haha like reagent code could support that (without awful hacks)

**Comment by viniciuspetch** [comment]
> Haha like reagent code could support that (without awful hacks)

hehe make it so adding biofoam to a biofoam injector actually transforms it into a special reagent that actually works. And never touch the code again

**Comment by Exxion** [comment]
>Put into biofoam injector
>Inject into dead monkeyman
>Throw monkeyman in gibber and grind meat
>Drink resulting working biofoam whenever needed

**Comment by kol1th** [comment]
Should have been closed with #12926
