### ISSUE TITLE
Medical Borg issue

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#12707]
Medical module has an odd interaction when using an IV.
Placing the borg's beaker into the IV stand and then removing it will break it, disallowing it being stored or used by the borg until it is placed into a machine such as a chem master and removed and restored in the borg, or the borg is reset.

**Comment by Shadowmech88** [comment]
Putting multiple bug reports into the same issue is bad practice.

**Comment by Dizor** [comment]
Ah sorry, I'm still use to condensing stuff. I'll remember for the future.

**Comment by ComicIronic** [comment]
Just make a new one now and move the second half into it. As is, we can't use this for tracking either bug.

**Comment by Dizor** [comment]
updated to be used solely for the medical borg issue

**Comment by Probe1** [comment]
Grand.  Look at it as I see it.  I fix issue 1 but not issue 2.  I can't automatically close your issue in good faith because I didn't resolve pt2.  Now the next guy has to investigate my pr.  Overtaxed Collabs have extra work.  

Issues are free help yourself to as many as needed.
