### ISSUE TITLE
Every weapon with AUTOMAGDROP plays smg_empty_alarm.ogg even if it's nonsensical for it to play a loud fucking buzzer

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12702]
#### Description of issue

```

/obj/item/weapon/gun/projectile/afterattack(atom/target as mob|obj|turf|area, mob/living/user as mob|obj, flag, struggle = 0)
    ..()
    if(!chambered && stored_magazine && !stored_magazine.ammo_count() && gun_flags &AUTOMAGDROP) //auto_mag_drop decides whether or not the mag is dropped once it empties
        RemoveMag(user)
        playsound(user, 'sound/weapons/smg_empty_alarm.ogg', 40, 1)
    return

```

this is not the place to do ``` playsound(user, 'sound/weapons/smg_empty_alarm.ogg', 40, 1 ```

#### Difference between expected and actual behavior

my deagle brand deagle not to sound like an alarm clock when it rounds outta dakka

it indeed did sound like an alarm clock

#### Steps to reproduce 

get gun with automagdrop shoot gun it yaps at you 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

yell at me i don't give a fuck i'm gonna freewheel it on outta this issue

**Comment by Shadowmech88** [comment]
I believe the best solution would be the addition of a `mag_drop_sound` var to `/obj/item/weapon/gun/projectile`, then replacing the 'sound/weapons/smg_empty_alarm.ogg' in the `playsound()` with `mag_drop_sound`.
