### ISSUE TITLE
Replace Gooncode with a Pomfcoin

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#12700]
The Gooncode has been an obsolete meme ever since the leak several months ago. It's time to get with the times and replace it with a new Pomfcoin item.

Alternatively, Shadowmech88 suggested in https://github.com/d3athrow/vgstation13/pull/12623 the Gooncode could be replaced with 2 bitcoins, which was the ransom paid (and ignored) for the Gooncode not to be released.

**Comment by Probe1** [comment]
Tempted to just put a corpse somewhere on the sat with two bitcoins and the goonecode on them.

**Comment by ihadtoregisterforthis** [comment]
There was a discussion here #8589

**Comment by Probe1** [comment]
neat

**Comment by SkowronX** [comment]
bawk

**Comment by Iamgoofball** [comment]
replace it with the goofcode

someone made a sprite for it in one of the threads post-gooncode release

**Comment by Shadowmech88** [comment]
And we can make it so that touching it deals constant brain damage.

**Comment by Iamgoofball** [comment]
that, and remove the deep fried recursion cap on the fryer

**Comment by Exxion** [comment]
There already isn't one
You just need to rename the item each time

**Comment by Iamgoofball** [comment]
nice, top quality code-by-that-guy-who-redid-my-fryers
