### ISSUE TITLE
Increase cost of Virus Sample Crate from cargo from 25 to 35 or 40

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12709]
Its too cheap you can afford enough for the whole shift at roundstart most of the time.

Increasing the cost isn't great because mutating viruses is **HORRIBLE SHITCODE** but its still worth saying and I'd like to know if anyone agrees.  I doubt it since I think there's all of 10 people across the whole server that play viro.

**Comment by SysadminJeroen** [comment]
I'll only agree with this if more neutral and positive symptoms will be added.

**Comment by viniciuspetch** [comment]
We need to improve virology before balancing it.

About the symptoms, I'm planning to open a issue _soom(tm)_ to discuss some ideas that came up while chatting at Discord.

**Comment by Probe1** [comment]
We don't really need ideas we need coders who have ideas.  We have a lot of ideas.  Not as many coders.

**Comment by viniciuspetch** [comment]
We need ideas before we code them. I only found one issue about virology balance (#12684).

And most of the ideas are quite simple to code, or maybe just copy-pasting (I hope).

**Comment by SysadminJeroen** [comment]
It is easy to get 4 negative symptoms, you can spend hours to finish a virus with only neutral and positive symptoms because of RNG.

**Comment by Probe1** [comment]
that.. isn't even remotely truthful.

lets keep it real please.  virology IS shit but we don't need to exaggerate it.

**Comment by SysadminJeroen** [comment]
@Probe1 I have sometimes spent one and a half hours doing speedy virology to try neutral or positive symptoms by getting 5+ virus crates sent to me.
