### ISSUE TITLE
Mint Toxin doesn't gib fatties

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12712]
(WEB REPORT BY: agentofzog REMOTE: 172.93.109.202:7777)
>Revision: ref: refs/heads/Bleeding-Edge

>General description of the issue
Eating mint toxin doesn't gib you if you're fat.

>What you expected to happen
explosion

>What actually happened
kept being alive

>Steps to reproduce if possible

get fat, 
eat dat mint. 
enjoy not being splattered all over the floor

**Comment by Kurfursten** [comment]
Cannot reproduce on live
