### ISSUE TITLE
Pizza inside pizza boxes is invisible

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#12716]
![image](https://cloud.githubusercontent.com/assets/19365096/21065770/08745cb4-be30-11e6-93ba-f0bfd039145d.png)

That's a pizza box. It is a normal-sized item.
A box suited for pizzas. It appears to have a Vegetable pizza inside.

pretty sure it's snacks.dm line 2904 where it adds the pizza overlay
```var/image/pizzaimg = image("food.dmi", icon_state = pizza.icon_state)```
still trying to find the pizza in food.dmi when it's probably not in there anymore.
@Kurfursten

**Comment by Kurfursten** [comment]
Pizza is still in food.dmi so that's strange

I'll still try to figure this out tonight though. Successfully reproduced on live.
