### ISSUE TITLE
Arts and Crafts crate is missing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12718]
(WEB REPORT BY: agentofzog REMOTE: 172.93.109.202:7777)
Looks like the arts and crafts crate can't be ordered from cargo anymore. Sucks having a limited amount of camera film (unless there's a service borg).

**Comment by Intigracy** [comment]
I highly doubt the removal was intentional.

**Comment by Kurfursten** [comment]
Error at line 293 of supplypacks.dm

Marble crate does not have unique pathing

Label easy fix
