### ISSUE TITLE
Assault rifle icon is small, here's a bigger one.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#12738]
![rifle](https://cloud.githubusercontent.com/assets/15067109/21068955/893071d4-be6d-11e6-8bfc-3753af6af21c.png)
Because if you can't have enough dakka, it might as well look big.

Download link for sprites: http://s000.tinyupload.com/index.php?file_id=55780107458244358060

**Comment by Wizardcrying** [comment]
>Because if

**Comment by Probe1** [comment]
Needs in hand sprites.

**Comment by Shadowmech88** [comment]
Will the current in-hand sprites not suffice? Those look fine, don't they?

**Comment by Blithering** [comment]
I'm happy with the current in-hand sprites, it's just the floor version that's a bit tiny.

**Comment by SkowronX** [comment]
What's stopping you from making a pr?

**Comment by Shadowmech88** [comment]
Actually I just realized that this icon might look a little awkward if it takes up literally the whole tile.
The scale of our item sprites is really messed up.

**Comment by Blithering** [comment]
@Shadowmech88 There's no set scale for gun icons, next to a deagle or the caps laser it looks dinky, but put it next to a laser AK and it's huge. I tried to match it with the CR-20 size wise.

@SkowronX Mostly ignorance.

**Comment by Probe1** [comment]
![maxresdefault](https://cloud.githubusercontent.com/assets/8550416/21078091/7a1acdd4-bf30-11e6-9d35-74fa167ccd92.jpg)


Don't try to make sense of sprite sizes.

**Comment by ghost** [comment]
The small size of the assault rifle is my fault. I never got gun sprites right, they're always to big or to small. (Assuming the assault rifle is referring to the xcom one) But you're replacement is 👍 x 💯
