### ISSUE TITLE
Advance security cameras are not working for me

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12746]
(WEB REPORT BY: recounted REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Advance security cameras are not working for me

>General description of the issue
Whenever I click on the advance security cams it does not show the map of the station. Im not sure what is causing this issue. 

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Probe1** [comment]
Update to IE9 or later.
