### ISSUE TITLE
Blind when shuttle is called

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12741]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
I reported this like three months ago, but
seems its not fixed.
https://ctrlv.cz/HuWz

>What you expected to happen
See

>What actually happened
Not see

>Steps to reproduce if possible
Get goggles, call shuttel, watch floor.

**Comment by viniciuspetch** [comment]
Couldn't reproduce using the code from 06/12 (4 days ago)
![Imgur](http://i.imgur.com/OdRR2ZW.png)

**Comment by Shadowmech88** [comment]
Could it have something to do with the red emergency lights in the hallway?

**Comment by Exxion** [comment]
It's less that it *could* and more that it *does*
