### ISSUE TITLE
Issue with internal bleeding/blood transfusions

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#12756]
Okay this is the same issue, I'm just not sure the cause. I hope at least.

Had an issue last night where I was healing a player who had internal bleeding and a fracture in their head.
When performing surgery I could not use the fix-o-vein to heal the bleeding as it kept saying there was no way to use it. After the surgery was over the internal bleeding no longer showed on the patient.
When given a blood transfusion however, their blood level did NOT increase, staying at 30% while the blood pack drained out.

Now I'm not sure which would be the cause of the issue involved. 
My hunch is that the internal bleeding didnt actually cure, so the blood level didnt increase, but it could be a problem with the blood bags.

I do apologize if this was suppose to be two issues but honestly I'm not sure how to divide it up since the exact cause is somewhat unsure to me.

**Comment by Probe1** [comment]
It's the same issue you're good..  Internal bleeding was incorrectly set to null.  Possibly when applying blood.  Internal bleeding was not correctly reset and the behavior went tits up.

Needs some hardcore testing unfortunately.

I'm worried it may have just been the mob controller taking a dump.

**Comment by Dizor** [comment]
I did scalpel > Hemostat (clamp bleeders) > [ineffective fixovien] > fix bone > saw bones > open head > [ineffectiv fixovien] > hemostat (check bonechips) > [fixovien, no luck] > **Attached IV** >close and seal skull > [fixovien, no dice] > cautery.

**Comment by SGuivenne** [comment]
This bug still a thing?

**Comment by Shadowmech88** [comment]
Tested, I gave a monkeyman internal bleeding in the head, and was able to use the fix-O-vein on him after using the scalpel, hemostat, and retractor. The original steps did not mention the retractor, but I figure it must have just been omitted, since I was unable to proceed to the bone setter or circular saw without doing so.
Seemed to work fine.
