### ISSUE TITLE
MoMMI spaghetti does not function correctly

### ISSUE THREAD

**Issue by abernd** [d3athrow/vgstation13#12755]
#### Description of issue
When mommi spaghetti is eaten, the user does not transform into a mommi as intended.

#### Steps to reproduce 
Eat mommi spaghetti.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) see https://github.com/d3athrow/vgstation13/issues/12579

**Comment by PJB3005** [comment]
> intentionally posting a dupe

**Comment by Iamgoofball** [comment]
Mom(mi)'s spaghetti
