### ISSUE TITLE
Injecting blood into a plasma man results in a successful message but no blood injected

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12760]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/8550416/21083768/b14a2c42-bfc5-11e6-98da-07551ec84e83.png)

#### Difference between expected and actual behavior

Blood to be removed from the syringe.  Blood to be inserted into the mob.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Sprok0** [comment]
Is that just plasmamen or any race with no blood?

**Comment by AI-Is-Rogue** [comment]
I believe it works with Dionaea.

**Comment by jknpj** [comment]
Don't dionae have greenish blood?

**Comment by AI-Is-Rogue** [comment]
They don't appear really have blood other than what the health analyzer says, you cannot remove the blood as far a I have tested, and they also have the NO_BLOOD flag. But they do make blood splatters.

**Comment by Eneocho** [comment]
injected blood into a plasmaman, it got injected properly and was metabolized like a normal chemical
