### ISSUE TITLE
Flaming skull (plasmaman monkey) issues

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#12774]
#### Description of issue

They have no hands but still have swap, drop, throw HUDs
Light bulbs grabed by them get null'd
They can't attack other simple mobs (tested with spiderling and mouse)

https://webmshare.com/play/Dm40G

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by uazuaz** [comment]
saw it yesterday.
they also have a "back" and can wear backpacks, i don't know if it's intended.

**Comment by Wizardcrying** [comment]
how did this get through
shouldn't they be similar to corgis in what they can do, minus the tailspinning?

**Comment by Exxion** [comment]
We learned the hard way from vox that having primitive forms that aren't monkey subtypes fucks everything up
So now we're dealing with having to remove monkey features from a monkey

**Comment by Wizardcrying** [comment]
wonderful

**Comment by jknpj** [comment]
>they also have a "back" and can wear backpacks, i don't know if it's intended.

Forgot about this. The backpack floats in the air for some reason, too.

**Comment by Exxion** [comment]
Floating backpacks apply to diona nymphs, too
Or really any monkey whose sprite is shorter than the monkey sprite

**Comment by Intigracy** [comment]
nulling lightbulbs

nice

**Comment by ghost** [comment]
Looking at this now. The HUD stuff I think I can handle easily, but the lightbulb stuff might be a tad more interesting.

Also, as a flaming skull I could attack monkeys and humans, but not mice. Odd

**Comment by uazuaz** [comment]
just made a test on the test server, as a monkey you can't attack mice too, so it seems that all lesser forms can't attack them.

also:
![tail](https://cloud.githubusercontent.com/assets/6170726/23582445/8e50f210-012a-11e7-9758-0a7a1ff18fb2.jpg)

**Comment by ghost** [comment]
Fucking monkey emotes.

HUD's fixed, lights nullspacing has been fixed, gonna look at attack code and see why the monkey can't bite chickens

**Comment by ghost** [comment]
Monkey emotes are fixed, moved to their own proc so you can override it if you have another monkey type that you want to have its own emotes
