### ISSUE TITLE
Having high ping makes precise movement impossible

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#12779]
Just a note this is most likely bad latency handling on byond's part and not /vg/station, but I'll make this incase there's some autism that can be done.

#### Description of issue
With high (130+) ping it becomes impossible to move a single tile at a time, instead a single keypress moves you 2+ tiles.

#### Difference between expected and actual behavior
**Expected:**
* tap key
* move 1 tile

**Actual:**
* tap key
* move 2 tiles, get launched into space during spacewalks etc etc

#### Steps to reproduce 
* Have shit internet, play videogame.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

N/A

#### Server revision

2b12a40f77325be2d79d2fd3cb4fc60c07347cc1 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by BobdaBiscuit** [comment]
Also something slightly interesting, if I try to move then change direction, the new direction acts as expected.

ie: Tap up then right, I move up 2 tiles then 1 tile right.

**Comment by jknpj** [comment]
I play with 90~100ms all time and only get those issues above 130ms

**Comment by BobdaBiscuit** [comment]
Perhaps the goonchat ping is incorrect then, .ping does nothing.
Pinging ss13.moe manually gets 130 - 200ms, so RIP me.

**Comment by Zth--** [comment]
Can confirm. It's awful when you're a ghost

**Comment by BobdaBiscuit** [comment]
Since we know it's not just literally me, might a hacky fix be some setting to toggle that trims keypress time for moving or something?

Literally everything else on the server is fine to use with shit ping.

**Comment by BobdaBiscuit** [comment]
I'm gonna try it myself but I'm shit at coding in byond.
My proposed fix for this is a setting that shit ping players can use that makes their character pause for a split second after moving 1 tile, then continues on normally.

This (would hopefully) fix the issue as it gives the server time to receive the keyrelease signal and stop the second step being made, and it should be short enough that if you are actually running somewhere it doesn't interfere at all.

https://github.com/d3athrow/vgstation13/pull/12846

**Comment by BobdaBiscuit** [comment]
@Zth-- @jknpj My PR got merged with an option in the game settings to pause after your first step, can you guys give feedback on if it helped with the issue?
