### ISSUE TITLE
fuel cans and welder tools

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#12773]
#### Description of issue
fuel cans can't be used to refill welder tools anymore; if you use a welder tool on a fuel can nothing happens, if you use a fuel can on a welding tool you will splash the fuel on the welding tool and on the floor.

#### Length of time in which bug has been known to occur

noticed today but i haven't used it in a while so i don't really know

#### Server revision

a5aa9e00802d5a10c916f8cb89606ec6c8e8d621 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by 9600bauds** [comment]
This is weird

**Comment by Kurfursten** [comment]
Reproduced on live. Not sure what caused this, I assume someone changed the attack behavior of glass, looked through recent commits and couldn't find anything obvious.

**Comment by Kurfursten** [comment]
This one took some digging, but I figured out what caused it.

@JMWTurner @BarneyGumball In #12050 you made it so that you could only transfer to open containers. However, sometimes you need to transfer to things that aren't open containers (like for instance, a welding tool). Instead of just opening a PR to fix this, I thought I'd ping you to discuss the implications of changing it back, or if the better way is to hack in an exception for the welder, etc.

Also @clusterfack I guess since he reviewed it and @Probe1 because he likes engineering things

**Comment by BarneyGumball** [comment]
Anything you can directly pour into should get the OPENCONTAINER flag.  It's not a hack to give the welder the flag.

**Comment by Kurfursten** [comment]
@BarneyGumball What do we want to do about the extinguisher situation? They get the OPENCONTAINER flag when you remove the fill cap, but you used to be able to just pour in directly from a fuel can without wrenching off the top of the extinguisher. I understand having to turn the safety off but it kind of sucks to fuck around so much just to refill your welder, compared to clicking a water tank.

**Comment by BarneyGumball** [comment]
Eh, all I did was make it so code that was already there actually did something.  I'm sure most players wouldn't mind if the fire extinguisher was just given the flag permanently.

**Comment by Kurfursten** [comment]
The functionality we're talking about was already there but removed when you added the flag check. In any case, we should try to think of if there's anything else we're forgetting before making a PR. Don't worry, soldering irons are still okay.

As of right now we need to add flags for
* Welding tools
* Fire extinguishers
* Silicate sprayers

Should also check the other usual suspects just to be safe

**Comment by Probe1** [comment]
Motherfucker I dumped welding fluid all over the chapel and then in a moment of infinite spaghetti lit it on fire with my welder by mistake.

THIS IS WHY.

**Comment by Kurfursten** [comment]
@Probe1 Besides the three I mentioned, can you think of anything else? It would presumably be something that needs chemicals inserted to work but is not, itself, a reagent container. The circuit printer springs to mind but I'm pretty confident that someone would've noticed by now if it were that.

**Comment by Probe1** [comment]
Nope, I only ever noticed bad behavior from the fuel can.

AND I BLAMED IT ON MYSELF

**Comment by Kurfursten** [comment]
It's not the fuel can, it's general to all reagent containers. In other words, if you had tried to fill your welder from a whiskey bottle or beaker, the same thing would happen.
