### ISSUE TITLE
Wizard's Lightning Spell cannot be used while Cuffed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12785]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
To Clarify, you cannot USE the lightning once cuffed, but can still cast the spell. My guess is the code has it throwing an invisible UI object, so being cuffed messes it up.

I'd highly expect lightning to still work while cuffed considering it comes out of your hands though

**Comment by Sprok0** [comment]
This is how all the targeted spells work, if you need to click on something to activate it then cuffs disable it

**Comment by Gunosaguki** [comment]
Eh, just feels weird. the whole thing with wizards is that their weakness is being de-robed or muzzled. handcuffs stopping lightning bolt just seems akward. Maybe change it to fire the lightning bolt in front of them if they're cuffed?

**Comment by Sprok0** [comment]
They should really just work through cuffs, I always got the impression that ss13 spells were mostly verbal rather than somatic.
I don't know how possible that is though, I'm pretty sure being cuffed just blocks all clicks in some way.
