### ISSUE TITLE
corrosive acid (xeno power ) doesnt consume plasma

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12781]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
as a xeno sentinel i corrosive acid a thing at i still had 200 plasma

**Comment by Kurfursten** [comment]
Needs more testing. Corrosive acid as a sentinel was working days ago when I was an alium.

**Comment by jknpj** [comment]
I'm pretty sure i fixed this.
