### ISSUE TITLE
10 u fertilizer bottles suck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12780]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
why arent the nutrimax stock fertilizers bottles 30u like other chemical bottles istead it makes using them for multiple plants a pain and makes shitton of empty bottles on the floor literally unplayable

>What you expected to happen
have 30 u bottles 

>What actually happened
10u meme bottles

>Steps to reproduce if possible
be a botanist find out 10 u bottles are shit

**Comment by Probe1** [comment]
see a chemist then or go to bee town

**Comment by Intigracy** [comment]
It's enough for one tray per bottle.

**Comment by pvak** [comment]
yeah but an average botanist/xenobotanist has to feed at least 10 plants at the same time which means 10 bottles

**Comment by Probe1** [comment]
then get bees

idk what to tell you here.  you aren't meant to have everything at round start or get everything all on your own.
