### ISSUE TITLE
SME Chamber Door should be a glass door

### ISSUE THREAD

**Issue by Anton-Kr** [d3athrow/vgstation13#12812]
The door is solid, which does not allow for emitter placement, which is lame as the room is crowded as is when you're trying to modify the SME. Making it a glass door would allow for emitters to be placed a bit more conveniently.

**Comment by uazuaz** [comment]
an alternative solution could be to move the door on a corner, like on defficiency.

**Comment by jknpj** [comment]
@uazuaz you end losing a rad collector by doing it but it at least it's safer than using a windoor

**Comment by Exxion** [comment]
Glass door =/= windoor

**Comment by jknpj** [comment]
I'm confused, are glass doors just the common see-through airlock?

**Comment by Exxion** [comment]
Yes

**Comment by uazuaz** [comment]
oh right. i thought OP was talking about a windoor.

**Comment by ReindH** [comment]
It take just a minute to rebuild into glass door though, and be mindful that glass doors doesn't shut as fast unless you hack them or a robo sets them on fast closing.

**Comment by Ephx1** [comment]
Do we have emergency glass airlocks? If not we should.

**Comment by uazuaz** [comment]
could be useful a new sprite for an airlock that closes fast as an external airlock, with a glass hole in the center for the laser, specifically done for the SME chamber.
maybe modifying a bit the old unused firelock sprite? done a couple of attempts.

![doorhazard2](https://cloud.githubusercontent.com/assets/6170726/21259988/4b758f98-c384-11e6-9194-47b42c825f18.png)

![111](https://cloud.githubusercontent.com/assets/6170726/21260889/6be0df2c-c388-11e6-8ae0-a0c1d210fbf1.png)

**Comment by PJB3005** [comment]
I disagree with making this a transparent airlock.

If you want to spam emitters at the SME you have to work for it, and even then you can just make a window inside the airlock and bolt it open.

**Comment by ComicIronic** [comment]
Yeah, do it yourself.
