### ISSUE TITLE
Heaters and Freezers are garbage.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#12813]
Heaters and freezers are weird.
They seem to have an internal gas storage, which is what they heat/cool, and then it's transferred to the whole system. 
But sometimes this breaks, and it stops heating your entire input and only whats directly in the machine instead, meaning you need to refresh the system to get the entire thing to update correctly, usually by un-wrenching and re-wrenching whatever you've connected. But even then, you can never seem to reach the desired temperature you input onto the interface.

Is there some sort of way to change them? Make them so they don't have an internal gas chamber or something, but affect only the system that's connected.  I just want them to stop being so  garbage.

**Comment by Exxion** [comment]
#11307 has more detail.
Discuss over there whether the internal storage should be totally removed, or whether the network update threshold should just be lowered to something less absurdly high.
