### ISSUE TITLE
Medical Borg Truama kit not giving a message when used on an organ.

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#12811]
As the title implies, when used on a valid organ (fresh lungs this time), it gives a progress bar but no text indicating use or success.

**Comment by Allspice** [comment]
Pretty sure it's a FEEAAAATUUUUUREEE that trauma kits in general (not just borg kits) do not work on robo organs, that's what nanopaste is for. The "bug" is that it doesn't let people know that it's bugging up because the organ is mechanical.

**Comment by 9600bauds** [comment]
dëup of #7924
