### ISSUE TITLE
attempting to move while cuffed and dragged causes runtime that crashes the game

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12842]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 64ca162eec555d2c47bba5adf50bee59e70217db 

>General description of the issue
whenever I get cuffed, and try to move, the game spams my box with "you are restrained and unable to move" and dreamseeker crashes for several minutes.
I have to either manually restart, which sometimes is impossible to do because it's crashed so bad.
>What you expected to happen
not crash the game and fill my text box to the absolut maximum. like it's so bad that it maxes out the log to where all old messages were lost.

>What actually happened

see above
>Steps to reproduce if possible
get cuffed, get dragged, try to move

**Comment by Kurfursten** [comment]
I've never seen this cause a crash but it sure is annoying, wouldn't hurt to add a cooldown on the message.

**Comment by Shadowmech88** [comment]
I think I remember hearing something like this related to mice being dragged, where they'd constantly get messages saying "You're too small to pull anything!" if they were being pulled by someone else.

**Comment by AI-Is-Rogue** [comment]
The same thing happened to me when I held down a directional key and walked into gibtonite with a ripley, I got so many messages about the safety features not letting me do that, that I crashed. The mech's walking is slow but it seems to be able to interact with gibtonite extremely fast.

**Comment by Exxion** [comment]
Yeah mechs have always spammed the fuck out of messages on failed movements
Try walking into a door you don't have access to in a mech sometime

As for happening when just walking, that's odd

**Comment by 9600bauds** [comment]
None of this sounds like runtimes tho

**Comment by ComicIronic** [comment]
Could add a single mob var for storing last received message for use in `to_chat`, without too much memory tanking. It might be better to look at solutions which do some sort of in-place delay, maybe based on a string hash.

**Comment by Shadowmech88** [comment]
Tested, I only received the message 2 or 3 times per second. I suspect the message stacking feature that has since been added would cut down on the impact of multiple identical chat messages as well.
