### ISSUE TITLE
Something screwy with grilles. (disappearing rods)

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#12847]
#### Description of issue
When you deconstruct the little broken remains of a grille that has been battered down, it only spawns a rod if there isn't a rod on the tile already.

#### Difference between expected and actual behavior
Expected the rods to either autostack or both be on the tile after deconstruction.

Got some weird deletion.
#### Steps to reproduce 
Smack a grille down with anything, leave a rod on the tile, then smack or snip the broken grille remains.
Repeat with the rod removed from the tile after breaking the grille.

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ReindH** [comment]
Same thing happens when you deconstruct a wall when there is a stack of 46 metal sheets on the same tile of said wall. Instead of stacking to 47 then 49 One is left with 3 metals.
Might want to test this with other materials too.

**Comment by Exxion** [comment]
So you checked that the stack only contained one rod, right?

**Comment by Blithering** [comment]
Yes, only one rod.

**Comment by Blithering** [comment]
Should have been fixed by https://github.com/vgstation-coders/vgstation13/pull/15243 , closing.
