### ISSUE TITLE
Remove mining/asteroid secret rooms and replace them with asteroid specific vaults

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12856]
It's how tg does it and honestly it's a much better system.  It's more modular, it's easier to add new content, and the mining secret rooms are ancient and outdated.

I don't even know how they work.

@unid15 are you game on copying and pasting a bunch of stuff for us to get a template and the ball rolling?

**Comment by Ephx1** [comment]
So what, how the rooms can randomly spawn now, just with pre-made vaults?
Or are we going back to the even older version where there were 3-4 spots you could rush to every round for a guaranteed room?

**Comment by Probe1** [comment]
The former.  Make most of the asteroid a potential location for a secret area as it is now.  Unlike how it is now, use the excellent architecture of vaults so people can add in new rooms easily.

**Comment by Intigracy** [comment]
Removing asteroid room generation will improve startup times as well.

You'd need to make vaults able to spawn more than one vault in the same defined area though, so people can't just meta the vault locations and know there's a guaranteed one here here and here.
