### ISSUE TITLE
Gameplay design promotes homosexuality

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#12855]
High level problem here
Most users in-game are homosexual. How do we fix this?

**Comment by Probe1** [comment]
![habeeb_it](https://cloud.githubusercontent.com/assets/8550416/21287260/7c1401fa-c435-11e6-8f56-af16d46b6156.jpg)

**Comment by DrCelt** [comment]
![1481484644529](https://cloud.githubusercontent.com/assets/7193289/21288536/dd4d17ea-c43a-11e6-9215-ed8395e32749.jpg)
