### ISSUE TITLE
Should space adaptation be re-added to the potential virus symptoms?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12867]
It's currently set not to ever appear.  It's powerful but not any more so than genetics can do every round.

**Comment by Blithering** [comment]
More positive virus symptoms please.

**Comment by SkowronX** [comment]
It needs a balance change compared to what genetics is able to do.

**Comment by SkowronX** [comment]
Which is do what space adapt can but in a shorter time with lesser odds of losing said ability

**Comment by AI-Is-Rogue** [comment]
There is the problem where it stops cryo from working.

**Comment by Intigracy** [comment]
Sounds like a feature.

**Comment by despotate** [comment]
I think there needs to be a deeper rework of viral symptoms. The concept of "good symptoms" as they stand just doesn't quite sit right with me. Of all the "good" symptoms that exist,

- There are four good symptoms that are just "synthesize x if host has less than y of x in system".
- There's Telepathy, which is stolen from genetics. Also, you keep it forever even if the virus gets cured.
- There's lantern, which is genuinely creative but I think you keep it forever as well.

And that's it. If we add space adaptation back, it doesn't really add anything to virology. It follows the copy-paste model of drug synthesis, has its job kind of done by genetics already, and is too _good_. It should stay in the special effects. I know I keep saying this, but there is space for _creative, serious, or bizarre_ viruses and symptoms, and I'm sure we can come up with better stuff than what we have now or has been added recently. I'm working on these ideas myself.

And another note is that even the best viruses give you a fever, cure themselves over time, and have a 5% chance of conferring immunity before they even start.
