### ISSUE TITLE
Remove Hanging Man's syndrome from the list of disease effects

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#12861]
#### Description of issue

Hanging Man's syndrome essentially replaces all th_ v_w_ls _n ___r sp__ch w_th _nd_rsc_r_s. It's a bad symptom in many ways.

Comms are meant to be auditory. All the other comms-affecting diseases are auditory. Almost all the stage four syndromes make you sniffle or wheeze or some shit in a way that everyone around you _hears it_. Some of them capitalize your words because you're screaming loudly. Broken radio traffic scrambles letter casing and order to simulate static. But underscores don't _mean_ anything, they're just underscores. They break the fourth wall by forcing the player to acknowledge that they're reading underscores, and oh, how funny, hanging man's syndrome, get it, haha, instead of being immulsioned in the game.

They also encourage stupid workarounds after the initial five seconds of panic. In my experience when a virus with this syndrome ravaged the station, people just started "going with the flow" with the virus by using leetspeak to prevent writing things that won't transmit, which is even more cancerous. Another problem is that this symptom doesn't really show any mercy; most symptoms in stage 2 have a percent chance of activating per processing tick and add up their effects fairly incrementally. Hanging man's just kills your comms without any randomness or luck involved, until you get cured.

Essentially, the symptom is a gag, too blunt, pulls you out of the fourth wall, and drags down the standards for the rest of the viral symptoms. There's certainly space for joke symptoms, but most of what's gotten added recently is gags like being turned into an anime girl with a katana, or a roundhouse kick disease, etc., which makes people approach virology with the mindset of "what's the funniest, most pop-culture-referencing symptom I can make", instead of "what would be an interesting, terrifying, or _space-worthy_ symptom"?  This is srs bizness, after all. 

And finally, if you scream, you end up saying "____________________!" This alone is enough of a reason to can this shit effect.

To fix, just comment the virus out here: https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/virus2/effect.dm#L943

**Comment by ghost** [comment]
The roundhouse kick disease just adds an already existing coffee to the player, and it heals your legs so it's beneficial

**Comment by despotate** [comment]
Gyroscopic syndrome was literally created with Ctrl-C, Ctrl-V, erase, write "GYRO". It's not an example of creativity in virology. I could add ten more gyro-like symptoms in ten seconds by replacing "GYRO" with some other bar drink.

**Comment by ghost** [comment]
Certainly could, I was just completing requests from the thread.

**Comment by ghost** [comment]
Same could be said of Creosote Syndrome, Delightful effect, Space Adaption effect, Adrenaline Extra, Glasgow Syndrome, and Full Glass syndrome which all use the same code, but I appreciate your honesty and your forwardness.

**Comment by DeityLink** [comment]
Both hanging man and babel syndrome are Danger:3, meaning they're meant to be hindrances. In Nuviro you cannot get infected by those when spawning, so I think this issue isn't relevant anymore.

**Comment by Kurfursten** [comment]
It's been 3 years so he can open a new one if he wants it
