### ISSUE TITLE
Borer gets sent to the void if their host is eaten by lord Singuloth

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#12869]
#### Description of issue
As a head borer I got sent to the black void when my host got eaten by the singularity.

#### Difference between expected and actual behavior
**Expected**
* Get eaten.
* Die.

**Actual**
* Get eaten
* Sent to the darkness of the void, able to eject from your host and use all verbs as normal.

#### Steps to reproduce 
* Be borer in a host.
* Have your host eaten by singularity.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

N/A

#### Server revision

fd7ba9d41190ff9225f4d502d8ad23a5ed3e75e6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
I'd be surprised if this was related to borers specifically and the guy didn't just get his entire contents list nullspaced somehow.

**Comment by Kammerjunk** [comment]
Yup yup just happened last round when a host exploded from an e-implant. Borer was nullspaced when he ahelped that "the whole screen is black, I can only examine my host, myself, a verb holder, and a fleshshot, also unable to move or really do anything," host was nullspaced when I tried jumping to him.
