### ISSUE TITLE
OOC bans are fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12865]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
fd7ba9d41190ff9225f4d502d8ad23a5ed3e75e6 

I'm constantly ooc banned, even after Kammer lifted it.

I think it was caused by celt ooc banning me months ago. that expired but the thing persists.

**Comment by Ephx1** [comment]
Don't fix, thx

**Comment by SkowronX** [comment]
never fix this

**Comment by mrpain666** [comment]
Honk

**Comment by nuklearcellphoneg** [comment]
Works as intended

**Comment by ghost** [comment]
awwwwww
