### ISSUE TITLE
horror form hair

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#12872]
![dreamseeker_2016-12-18_01-58-29](https://cloud.githubusercontent.com/assets/6526157/21291618/7e391dae-c4c5-11e6-8d6f-b6ddfce93917.png)

![dreamseeker_2016-12-18_01-56-04](https://cloud.githubusercontent.com/assets/6526157/21291615/5b7565ac-c4c5-11e6-94f4-6fc99d1882b8.png)

**Comment by Shadowmech88** [comment]
Going horror form used to make you bald, right?
