### ISSUE TITLE
Phantom Pain (Won't go away.)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12871]
(WEB REPORT BY: consedfu REMOTE: 172.93.109.202:7777)
>Revision a3fa295bada07af89fbf42932fcad66ea0d23ffb

>General description of the issue
For whatever reason the loss of a limb results in the inability to do anything at all due to immense pain.

>What you expected to happen
The pain to go away after the surgery ends.

>What actually happened
The pain didn't go away.

>Steps to reproduce if possible
Use circular saw to amputate any limb at all that won't result in immediate death.

**Comment by 9600bauds** [comment]
gotta use scalpelretractorcautery after bonesaw to make the pain stop

otherwise you're just walking around with a mangled stump

yes, I agree, it's shit
