### ISSUE TITLE
Should the CMO be able to select their blood type as a head role privilege?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12907]
Float other ideas to improve the rate people take heads if have them.

**Comment by kilozombie** [comment]
Would this be something you choose at roundstart?
Seems like a fun innate ability like chaplain religion choice.

**Comment by Ephx1** [comment]
Yeah, how would that work?
If CMO is set to "high" would that allow you to alter your blood type?
Or would it be a roundstart thing like kilo suggested?

**Comment by pvak** [comment]
for what purpose

**Comment by Probe1** [comment]
To motivate players to pick head roles.

**Comment by Probe1** [comment]
@Ephx1 a prompt once the round actually starts like @kilozombie mentioned.  We _could_ just be realistic about it and make every CMOs blood type O-.

**Comment by 9600bauds** [comment]
Give the CMO an implant that gives him permanent healthHUD, no matter what he has in his eyes slot

**Comment by Probe1** [comment]
That's really cool but it reminds me of the hypospray.  It's cool, but its not really "special".

**Comment by Blithering** [comment]
Tangentially related, back in the days of yore CE started with the round's wire layouts in his notes. That would be cool to re-add.
