### ISSUE TITLE
eclair sprites are fucking massive

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#12915]
#### Description of issue

They are larger than mobs

#### Difference between expected and actual behavior

To be regular sized

Its bigger than the nuclear bomb

#### Steps to reproduce 

spawn an eclair

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Just boost the nutrition value and call it a feature.

**Comment by Probe1** [comment]
that'd be okay for a secret super item.

**Comment by 9600bauds** [comment]
IIRC there was a PR to make them smaller and it was considered a feachur

**Comment by PJB3005** [comment]
#9280

**Comment by SkowronX** [comment]
""""""Controversial""""""

**Comment by 9600bauds** [comment]
This was already brought up before, too, but the baguette sprite is LITERALLY a google images result resized in MS paint.

**Comment by Probe1** [comment]
honestly the baguette has gone on too long

**Comment by PJB3005** [comment]
It's a feature now.

**Comment by SkowronX** [comment]
Look at the palette, wowee.

![palette](https://cloud.githubusercontent.com/assets/7810719/21295833/7e451080-c52b-11e6-95cf-10d4d7ebff47.png)

**Comment by PJB3005** [comment]
This is the source I believe:
 ![](http://images-mediawiki-sites.thefullwiki.org/10/4/1/5/84919861599037634.jpg)
