### ISSUE TITLE
previous_list_item() is broken!

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#12918]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/__HELPERS/lists.dm#L178

I found this while doing #12809. Apparently, hair selection arrows are the only ones that use previous_list_item() and next_list_item() at all.

The end result here is that you can't use the "previous hairstyle" arrow, but you can use the "next hairstyle" one.

I tried to fix it for a while but I hate this proc.

**Comment by 9600bauds** [comment]
Oh wait, it might just not like associated lists. Hmm.

**Comment by unid15** [comment]
>  if(i < L.len || i > L.len)

screw the oldcoders, why not just write **if(i != L.len)**

p.s. yeah that's where the error is

**Comment by 9600bauds** [comment]
don't question oldcoders

they worked in mysterious ways

**Comment by 9600bauds** [comment]
Come think of it, .len doesn't even work for associated lists, does it?

**Comment by unid15** [comment]
replace that statement with if(i < 1 || i > L.len) and it'll work

**Comment by 9600bauds** [comment]
👌
