### ISSUE TITLE
Firelocks no longer require access or crowbars to open

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#12922]
#### Description of issue

Not sure if this was an intentional change, but firelocks blocking off breaches or fires (noted by the flashing lights) used to require crowbarring or engineering access to open, but recently just give the message 'you force the firelock open' when clicked on.

#### Difference between expected and actual behavior

Previously the safety feature at least slowed down peoples' attempts to open the zas nightmare
Now we can all enjoy slamming into paper sheets and dying.
#### Steps to reproduce 
make a breach so the station's firelocks close and theoretically lock. 
open one with the flashing alarm lights,
Marvel as evolution has rendered the average greyshirt's hands equivalent to a crowbar.

#### Length of time in which bug has been known to occur

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [yes] Issue could be reproduced by different players
- [checkbox] Issue could be reproduced in multiple rounds
- [:^)] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
I'd bet money that it's related to #12894.

**Comment by Blithering** [comment]
That was very fast.
