### ISSUE TITLE
Vox trader armor shouldn't be near-useless

### ISSUE THREAD

**Issue by Dusk-a** [d3athrow/vgstation13#12928]
Vox trader armor used to have very good protection (which was bit too much) but now it is complete garbage with no defense, no flash block, and they can't hold a jetpack like they used to. Traders shouldn't be walking around with essentially no protection considering their outpost is on the asteroid where there are plenty of things ready to fuck your day up and a trade gone wrong can end up in death. What should be changed is that they revert to how they used to work and their armor values lowered to what mining hardsuits have.

**Comment by Probe1** [comment]
I asked @Skullyton to get new sprites and we'll give them a unique variant that matches the mining hardsuit in terms of protection as you suggested.

**Comment by jknpj** [comment]
Might as well let them upgrade their suits with goliath hides or maybe with basilisks to make them literally snowflakey

**Comment by Kurfursten** [comment]
@jknpj Literally snowflakey armor would be made on snow map

**Comment by Shadowmech88** [comment]
Crafting ice armor from snowballs when?

**Comment by Probe1** [comment]
>craft ice armor
 >instantly go into a hypothermia induced coma then die of exposure 30 seconds later.

**Comment by Shadowmech88** [comment]
I'm tempted to add it now, just for that.

**Comment by Kurfursten** [comment]
Vault where you can kill Celt for an Amulet of Temperature Immunity when?

Also include CELTIC board on the loot table

**Comment by Shadowmech88** [comment]
Are potato men still in the code?
It could be one of those, with attacks that lower your body temperature.

**Comment by NigglyWiggly** [comment]
>Vox trader armor shouldn't be near-useless 

Yes it should.

**Comment by Probe1** [comment]
I think after the actual discussion the plan is to not change their sprites and just let them augment their shit with goliath armor a la miners.  Does that sound good @devlkiller0 ?

**Comment by kilozombie** [comment]
The thing is, don't Raiders start with the same armor? And I'm pretty sure there aren't enough of the alternative hardsuits for everyone.

**Comment by Probe1** [comment]
Yes, that is why people did not want the sprite changed.  So raiders can be mistaken for traders and vice versa.

**Comment by kilozombie** [comment]
Right, but shouldn't there be two versions with the same sprite, or is that already the plan?

**Comment by Probe1** [comment]
Correct.  That is how it already works.  Raiders armor (which looks identical) is extremely robust while traders armor has little protection.

**Comment by Exxion** [comment]
To deal with the lack of protection, simply stop sucking.
But who the fuck removed the ability for them to carry jetpacks?

**Comment by kilozombie** [comment]
Yeah protection really shouldn't be on there, there are few circumstances where the armor factor isn't used just to attack crewmembers and miners with shitty escalation. Most traders really don't need the encouragement in the form of a tough hardsuit. But jetpacks, yeah that should probably be changed, it's a bit of a bitch to space explore having to hold your backpack all the time.

**Comment by Sprok0** [comment]
What? You can't use the jetpack from suit storage even if it fits there, you need to hold your backpack to fly around no matter what.

**Comment by kilozombie** [comment]
...well, I'm just a big moron in this thread, then.

**Comment by Exxion** [comment]
It's still EXTREMELY useful to just hold the jetpack, considering you can still use it as internals from suit storage.

**Comment by Probe1** [comment]
its ok kilozombie i make that mistake still and re-learn this all the time

**Comment by Dusk-a** [comment]
@Probe1 So what you are saying is to use goliath plates to give them any armor at all or basically make them mining hardsuits just reskinned for vox?

@Exxion The way they got switched from the raider suits is they just got added under the civilian suit list which cannot hold jetpacks in the suit storage slot

**Comment by Probe1** [comment]
Yes.  Have them start out as is, have adding goliath plates increase their armor.  Keep the sprite the same.

Everyone is a little happy.

**Comment by AI-Is-Rogue** [comment]
That would be nice for the miner Vox who can't upgrade their hardsuits.

**Comment by Dusk-a** [comment]
Sounds like the best that will happen, if it gives decent protection but you need to work for it I have no problems with that. What about the jetpack in suit storage or flash/welding protection?

**Comment by Exxion** [comment]
My vote goes to yes jetpack, no welding/flash protection.
