### ISSUE TITLE
Lobby bell bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12929]
(WEB REPORT BY: cacogen REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
edf8fbbc6100ed7f0d7fd863b9cbed8e97f0e462

>General description of the issue
1. Bells spawn bolted, which means when you fabricate them as a Mechanic using the General Fabricator you have to unwrench them to pick them up
2. Bells can't be taken out of backpacks once put inside

>What you expected to happen
Bells to not to spawn bolted and to be removeable from bags

>What actually happened
The opposite

>Steps to reproduce if possible
1. Spawn Mechanic
2. Use device analyser on desk bell (e.g. medbay's)
3. Use analyser on reverse engine
4. Add nanopaper to blueprint printer
5. Research desk bell on reverse engine
6. Nanoprint desk bell
7. Use blueprint on general fabricator
8. Add material to general fabricator
9. Fabricate a bell
10. Try to pick it up
11. Unwrench it
12. Drag it to your hand to pick it up
13. Place it in your backpack
14. Try to take it out again

**Comment by JustSumBody** [comment]
You can get the bells out of your bag by click dragging it to your character for what that's worth. Rest of it checks out though

**Comment by Probe1** [comment]
thats hilarious

i hate mechanics code

**Comment by Intigracy** [comment]
Almost everything that can spawn anchored for mechanics does.

**Comment by ComicIronic** [comment]
You know, when you describe it like that, Mechanic sounds like a very convoluted job.

**Comment by Shadowmech88** [comment]
Is there anything mechanics can produce that should never be unanchored?
Flatpacks can just be assembled where you want them, but as far as the general fabricator, should we just make it unanchor everything it produces?

**Comment by Exxion** [comment]
Pretty sure bells are the only anchored item the genfab can produce

**Comment by Pathid** [comment]
Consider: Bells are easy to construct out of metal and a signaller. Nothing of significance would be lost if they were made unscannable.
