### ISSUE TITLE
Visible tiles get fucked in escape pods (possibly other shuttles?)

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#12925]
#### Description of issue
When an escape pod jumps to hyperspace the inside of the pod is displayed as absolute darkness, can't see shit even when lights are active.

#### Difference between expected and actual behavior
**Expected**
* Jump to hyperspace
* Can see the inside of the pod

**Actual**
* Jump to hyperspace
* CAN'T SEE SHIT CAP'N

#### Steps to reproduce 
This has happened as both borer and diona nymph, I haven't played human recently.
As diona (the video below) we were all resting to fit in.

* Go in pod
* Go to hyperspace

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Last month/few weeks I think.

#### Server revision

edf8fbbc6100ed7f0d7fd863b9cbed8e97f0e462 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by BobdaBiscuit** [comment]
https://www.youtube.com/watch?v=MosFnKnAEig is the issue in action along with some in pod hilarity.

Also talked to the 2 other diona players and they said they had the exact same issue.

**Comment by Shadowmech88** [comment]
It looks like you couldn't see inside the pod even before it launched, nor after it docked until you opened the airlock leading into the bigger ship.

Could it be that there was just no light inside the escape pod with which to see?

**Comment by Probe1** [comment]
In a related bug, the lights seem to fuck up when the shuttle reaches centcomm

**Comment by BobdaBiscuit** [comment]
It was still visible before launch, just not pitch black. (we were hiding from the xeno menace)

I also had my lantern on the entire time, and the other diona were fucking with their own lights.

**Comment by Shadowmech88** [comment]
Works on my machine.
![image](https://user-images.githubusercontent.com/3991927/47407181-97784600-d71f-11e8-888c-9622e46a6bfc.png)
