### ISSUE TITLE
Sleeping and Then Resting Seems to Cause Permanent Sleep Until Resting Again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12927]
(WEB REPORT BY: cacogen REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
edf8fbbc6100ed7f0d7fd863b9cbed8e97f0e462 

>General description of the issue
a guy left me in the body scanner after surgery. i couldn't eject using the verb in the right-click menu or the object tab.

>What you expected to happen
to eject from the body scanner

>What actually happened
nuttin

>Steps to reproduce if possible
1. burst a lung
2. go to medbay
3. guy takes you to surgery
4. tells you to sleep
5. go do a thing in another window
6. come back
7. you are in body scanner
8. your vision is clear, yet you're unconscious
9. try to eject
10. cannot

maybe i needed to wake up or something, i don't know. but the screen wasn't black so it was like i was awake.

**Comment by 9600bauds** [comment]
Sounds like the "used the rest verb while asleep" bug

**Comment by Shadowmech88** [comment]
Tested, and yes, the bug here seems to be that if you sleep, then use the rest verb, it seems like you will remain unconscious with clear vision until you use the rest verb again, at which point you will once again be able to speak/eject yourself/etc.

**Comment by Intigracy** [comment]
https://github.com/vgstation-coders/vgstation13/pull/20736
