### ISSUE TITLE
ghosts can use food processor what the fuck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12962]
(WEB REPORT BY: kranenberg REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
612b12d48d418a15f45fd9d2df5403a92f66bb48 

>General description of the issue
as a ghost, you can drag things in a radius of 3 tiles around the food processor into the food processor, and you can grind whatever is inside by clicking it - can't  grind humans since the processor will pop them out after the grinding, but it will take time while they're stuck in the processor

>What you expected to happen
TO NOT BE ABLE TO DO THS

>What actually happened
I WAS ABLE TO DO THIS

>Steps to reproduce if possible
be a ghost
drag something process-able to the food processor
click processor
enjoy funsies

**Comment by Probe1** [comment]
already on it

**Comment by Exxion** [comment]
I assume you mean three-tile diameter/one-tile radius, but either way

**Comment by Probe1** [comment]
honestly why aren't we doing this at a high level for basically all machines then writing an exception for lightswitches

```

	if(!ishuman(user) && !isrobot(user)) //No ghosts or mice putting people into the sleeper
		return

```

**Comment by troots** [comment]
@Exxion 5 tile diameter, if ghosts  got reflex or dragged your sprite beforehand you're in for fun times

**Comment by Exxion** [comment]
Oh right. I'm dumb.
Extra loose.

**Comment by Blithering** [comment]
So thats what was happening that round
