### ISSUE TITLE
Sugar Cookie Recipe doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12969]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
765724ffbf0a8485e17dc089b7a032b5279b189e 

>General description of the issue
try to bake sugar cookies

>What you expected to happen
get sugar cookies

>What actually happened
BURNED. MESS.

>Steps to reproduce if possible
5 sugar
5 flour
1 egg

**Comment by Probe1** [comment]
I'm probably responsible for this somehow since i touched a line next to it.
