### ISSUE TITLE
Tiny hermit crabs hidding themselves in their helmet shells

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#12968]
#### Description of issue

![undercover](https://cloud.githubusercontent.com/assets/17928298/21372460/f0942286-c6f5-11e6-9a4a-f9c021c684d6.png)
https://webmshare.com/QYn0J

smol mommi sprites are able to hide their red rogue eyes under big hats/hemets

#### Difference between expected and actual behavior

Expected: A RED-EYED MOMMI AI CALL IT
Actual: AHELP WTF MOMMI JUST KILLED ME FOR NO RAISINS

#### Steps to reproduce 

As any "tiny" type of crab, grab any big hat/helmet and use the verb "Hide"

#### Length of time in which bug has been known to occur

God know, at least a few months

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
Yes, and there are _MANY_ other helmets that murderous mommis chose for that purpose.  Whether it's a good idea to allow this is worth talking.  

It's not truly a bug, and it's only kind of an oversight if you fudge the meaning of oversight.  It's more like no one cared.

**Comment by jknpj** [comment]
Since this got a Discussion tag, what about keeping this as a feature but only if not-emaged?

**Comment by Probe1** [comment]
I mean ideally you'd just make their eyes glow through anything in the hat slot if the eyes are red.

**Comment by 9600bauds** [comment]
Borg eyes already work like that for no fucking reason, we just have to figure out how they work

**Comment by Probe1** [comment]
hahaha holy shit we're doomed

**Comment by ghost** [comment]
Alright so I know why borg eyes and MoMMI eyes work like that and I too know why MoMMI eyes don't show up as red in that screenshot

**Comment by kol1th** [comment]
The borg eyes show up above every single thing, even lighting, which is retarded. This sounds like a feature to me

**Comment by ghost** [comment]
```Celt: I can fix that like super easily
Celt: If you hide, your red eyes are on the floar plane
Celt: if you don't
Celt: your red eyes poke out of a hat
Celt: because they're on the lighting layer
Probe1: um
Probe1: how even
Celt: Hm?
Probe1: how would you handle this
Probe1: i guess
Probe1: if emagged
Celt: Super easily
Celt: if(emagged)
Celt: shit I could tell you how to make that PR
Celt: one moment
Celt: the issue is
Celt: uh
Celt: if the MoMMI was under a table hiding
Celt: their red eyes would show through it
Probe1: yes
Probe1: exactly.
Probe1: that's why I wrote how would you handle this
Probe1: it basically ruins them hiding
Celt: Hm
Celt: got it
Celt: Have it layer above the hat if they're hiding but not above anything else
Probe1: post it in the issue so everyone knows
```` 

@kol1th The reason it layers above darkness is obvious - it's illuminated

**Comment by Allspice** [comment]
I think borg lights become invisible in the dark when the borg rests.

**Comment by Ephx1** [comment]
Borg lights shut off if resting or their actuators are shot

**Comment by kol1th** [comment]
@DrCelt they also appear above chairs

**Comment by Kitfox88** [comment]
hacked mommis are so evil their piercing gaze cannot be hidden from

**Comment by jknpj** [comment]
Evil is in the eye of the beholder

**Comment by ihadtoregisterforthis** [comment]
Some MoMMI sprites have an emagged variant that changes the color of the chassis. These small ones could have one but that would mean having to sprite.

**Comment by Reviire** [comment]
What if you added more red lights to them? Like, the bits that aren't covered by the helmet start glowing too. Their entire body isn't covered by a helmet.
