### ISSUE TITLE
Chaplain Religion "Roman" not working.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12985]
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
9807acba44ad6e88b0e2e28342b711f791e19032

>General description of the issue
One of the Chaplain religions isn't properly appearing in-game. It's listed on the github, however.

>What you expected to happen
Set religion to "Latin" (same should also apply to "Rome", "Roma", and "Roman") and get Legionary armor, etc.

>What actually happened
Default Religion (Space Jesus, Holy Book of etc.)

>Steps to reproduce if possible
Set Chaplain religion to "Latin", "Rome", etc.

**Comment by Kurfursten** [comment]
@Probe1 This isn't feature loss, it's an oversight

Issue at line 151 of civilian_chaplain.dm - the author wrote all of the names in capital letters "Rome", "Roma", "Latin", etc. but that switch statement first converts all strings to lowercase, therefore it can never match. Tag easy fix, only have to convert the religion to lowercase in the if statement.

**Comment by Probe1** [comment]
I thought @Kammerjunk would have already opened a PR to close this issue tbh.

**Comment by Kammerjunk** [comment]
Yeah, I was looking for more bugfixes and then in-game stuff got my attention and then I forgot. One minute.
