### ISSUE TITLE
Range stun removal 

### ISSUE THREAD

**Issue by jakmak3** [d3athrow/vgstation13#12988]
As we have all seen the games combat revolves around the concept of stun n done. The first ranged stun that you get is your finishing blow. This is a problem that has existed a on all codebases which several have tried to deal with (TG disablers, Bay weak tazers) But i propose a radical solution. Remove all ranged stuns all together.

Of course this would keep stuns from batons, stun prods, zas, flashes, flashbangs, cult runes, and disarms but it removes all ranged stuns from the game.

What this would include is

Removing tazers and replacing the ones sec spawn with/ their lockers with sec glocks

Remove rubber bullets from sec glocks

remove sec borg tazer and buff it by giving it increased speed

remove stun from detective .38 and buff its damage

remove c20r/other ballistic weapons stun by removing their stun and increasing their damage to balance it out

remove stun revolver

egun/AEG stun is removed and replaced with a low damage lethal one which instead of doing stun damage does a third of a normal egun energy bolts worth of damage OR remove the non lethal/low lethality mode and give them a larger battery

Ofcourse i am probably forgetting some weapons but this is the general gist of it. All stun weapons would need to be melee range and all ranged options would be lethal only.

This would also prompt a need to change how security would handle people now without their easy 1 hit golden bolt.

 I know many people would have their own version of this but this is mine.
out their easy 1 hit golden bolt. I know many people would have their own version of this but this is mine.

If someone is to be put under arrest if the security officer can get a stun off on them via any method (baton, flashbang, lucky zas) then the officer can go ahead with the arrest without needing to order them to stand down first provided there is good reason for the arrest in the first place.

If the suspect may run then the officer in order to use lethal force MUST order them to stand down in some format they can understand (hailer, yelling at them, yelling over radio, pda ,ect). if they do not comply and resist arrest/run after being told to surrender the officer may use lethal force and alert other officers that the suspect has refused to stand down. Simply any form of a message to halt would suffice for this.

If the suspect is armed, dangerous, armed and dangerous, has attacked someone with lethal force or has murdered someone an officer does not need to order them to stand down and can resort directly to lethals provided the criteria is met.

If implemented in my vision i could see several different things happening when sec is dealing with suspects.
1. Sec would be more willing to try to use melee 
2. Sec might be more inclined to talk things out before unzipping baton/glocking someone
3. Dindus/assistants would either be more jittery or much more afraid to greytide around
4. Sec would be more inclined just to shoot people

1 wouldn't be that bad and could be fun, 2 and 3 would be pretty good. Assistants more afraid to kill all the stations pets or break all of engineerings windows and 4 i could see being a problem with this strategy

But some issues with this is sec would use lethal force on innocents much much more due to them being to afraid to talk things out or just plain old shitcurity so i dont know if it should be handled more hands off or if admins should play a big role in it. Doing it hands off could potentially invite shitcurity and possibly cause us to devolve into hippie but with admin intervention it would mean admins would have much more responsibility in handling things that currently can be handled IC. So i do not know how this should be enforced.

I know this entire idea sounds retarted and lets be honest it probably is but i feel that this is a potential alternative to dealing with the infamous stun n done of combat. Methods like TG disablers and weak ass bay tazers dont work to improve combat and the fact that easy wins exist like this could be a problem. I invite input and criticism from everyone regarding this idea.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/8247
https://github.com/d3athrow/vgstation13/issues/8220
Two previous issues.

There's another that I can't find that led to this gem image.  _Normally_ I'd refrain from posting any meme-rific images until at least the issue had served its purpose.  In this issue I think we all need a reminder of every time we discuss this.  No one can agree and it goes nowhere.  

If people want to discuss their ideas please try to find ways to work together instead of just saying "no thats stupid".

![stuns](https://cloud.githubusercontent.com/assets/8550416/21408972/d765aa36-c7a5-11e6-82ea-5dfda2ed9408.png)

**Comment by Blithering** [comment]
I really don't like the idea of nerfing sec's only safe nonlethal option and replacing it with forced RP and valids.
Having to ask a greytide thats barreling down the corridor at you with stungloves to please stop and come quietly is just going to result in salt on both ends, either from sec who get bumrushed and feel powerless and restricted, or by non-sec who now see security as shitcurity incarnate, 
The 'easy one hit golden bolt' is a ridiculous concept in my opinion too, the projectile speed is laughable, and any decent amount of yakkety sax can dodge all five shots in a standard taser.

**Comment by JustSumBody** [comment]
>If the suspect may run then the officer in order to use lethal force MUST order them to stand down in some format they can understand (hailer, yelling at them, yelling over radio, pda ,ect). if they do not comply and resist arrest/run after being told to surrender the officer may use lethal force and alert other officers that the suspect has refused to stand down. Simply any form of a message to halt would suffice for this


Oh boy I can't wait to lase people to crit, cuff, then keloderm because "THEY WERE RESISTING"

In all seriousness this would require a rework of space law or administrative changes to what sec is allowed to do(which should be more to make up for the fact that their safest method of dealing with shitters is now lethal)

**Comment by despotate** [comment]
This would honestly just encourage more shitcurity from me as I'd throw flashbangs instead. I always want to do so because they get rid of annoying bystanders. I usually don't because the taser results in less protests from people.

**Comment by jakmak3** [comment]
Again i was basically throwing ideas to the wall and seeing what sticked. I feel like lots of both would happen. More shitcurity and also more sec being willing to actually talk things out but i dont see any other reliable alternative to dealing with stun n done.

**Comment by despotate** [comment]
I just love flashbangs.

**Comment by Probe1** [comment]
The riot crate is the best crate.  Cargo can keep the armor.

**Comment by Shadowmech88** [comment]
First-off, this sounds like a [WYCI].
Second, even if you *did* code it, I can almost guarantee the opposition to such a major change to such a major facet of the game would be so strong that it'd never get merged.

I think the only way progress is going to be made reworking our combat system is by small, gradual changes, not tearing the whole thing out and replacing it with something different all at once.

**Comment by jakmak3** [comment]
Shadow i could code this but i know it would get shot down. Hell im not even sure about the system that i proposed. I made this discussion to try to collect ideas on this to see if they can be improved.

**Comment by 9600bauds** [comment]
Absolutely prequisite to any move towards lethals being the norm would be completely rewriting targeting mode from scratch.

So,  #12449 #11241 #11240

**Comment by mrpain666** [comment]
> In all seriousness this would require a rework of space law or administrative changes to what sec is allowed to do(which should be more to make up for the fact that their safest method of dealing with shitters is now lethal)

This proposed change would worsen the situation for security and the server as a whole for this very reason. The only viable option for dealing with petty crimes will eventually escalate to a full on killing as stun weaponry was not available or a viable option.

**Comment by jakmak3** [comment]
again it brings up the question of if lethal force was the norm would it devolve into hippie or would greyshitting become rare and much less noticable. It could go either way and i do not know exactly how the community would take this change. Either go further into becoming DEATH MATCH 13 or greyshits being to scarred to dindu around. If i knew for fact how this change would handle i would either have the PR up right now or scrap this entire idea

**Comment by Exxion** [comment]
Well, we could remove all the tasers from one map and see how things go there.
I know that wouldn't be a COMPLETE removal, but it would be an approximation

**Comment by Shadowmech88** [comment]
That seems like a good way to trial the idea.
Though I think it'd have to be a new map with no tasers. Removing them from an existing map would probably cause outrage.

Maybe Snowmap could be the no-taser map?

**Comment by Allspice** [comment]
admin: help: faget: oh SHIT the copper just lased my ass is he valid ?

**Comment by Blithering** [comment]
Asimov silicons would also be an issue.

**Comment by TheFriggenSawbones** [comment]
yeah i'm not too sure about this. wouldn't it just devolve into cops shooting people and people shooting back, and isaac wouldn't this change get you killed since you're constantly having security called on you since you break into literally everywhere

**Comment by jakmak** [comment]
Shadow I kinda agree with that idea. All I really want to see is a 1 week trial of the system I proposed or at least attempt part of the original system. After the trial I would either go forward if it if there are less dindus or cancel it if sec becomes shitcurity 24/7

And sawbones sec seldom get called to deal with my shit. It's usually chloral happy doctors/zenny is captain/Hitler HOS

**Comment by Ephx1** [comment]
![robot11](https://cloud.githubusercontent.com/assets/6224074/21471904/8d0d1922-ca90-11e6-96d5-f923ccd36566.png)

LOCKDOWN SECURITY
*BUZZ
*BUZZ
*BUZZ

But seriously you have to take into account the synthetic force that is bound to halt harm. Either you want security being fucked over every round (strengthening the hate people have for silicons) or you pull the "Shitty Non-human Captain" trick and upload NT Default at round start.

**Comment by DeityLink** [comment]
Well that seems pretty universally disliked. Closing?

**Comment by Exxion** [comment]
Also old
