### ISSUE TITLE
Weird Cameras on Deff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#12995]
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

c699d6721d53a20a5e1b33c8d99480c7547270a9 
>General description of the issue
The Engineering South and AME South Cameras are both listed on the Supply Outpost Cameras

>What you expected to happen
That those cameras, which are on the main station, would be on a security camera console for the main station and not for the mining outpost.

>What actually happened
They're in the wrong fucking spot DUNY

>Steps to reproduce if possible
Click on Supply Outpost Cameras

**Comment by Probe1** [comment]
>Duny
Though it would be sweet to say it is not Dunys fault.

It was mine.
