### ISSUE TITLE
Should Hulks Be Able to Fire the Pneumatic Cannon?

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#13002]
[Discussion]

**Comment by jknpj** [comment]
>gunhulk

GAAAAAY

>inb4 pneumemes aren't guns

**Comment by Kurfursten** [comment]
I don't even think hulks should fit in wheelchairs. I think cripplehulks should flop out hilariously onto the floor.

**Comment by kol1th** [comment]
(No)

**Comment by 9600bauds** [comment]
they no longer can

**Comment by Shadowmech88** [comment]
I know, this issue was opened in response to them being made unable to fire them, to see if people wanted it kept that way.
But the discussion is dead, so no point in leaving it open.
