### ISSUE TITLE
Loading a map element places an object's contents outside of the object

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#13004]
Example: Loading the oldvault.dmm vault, and the things inside of all of the closets as well as the safe are just on the floor on the same tile, rather than being inside. Happens with all externally loaded .dmm files.

**Comment by Probe1** [comment]
It's because its supposed to be run at server start and shit doesn't initialize properly.  

It's probably way, way more trouble to fix than it is worth

**Comment by kol1th** [comment]
probably but it makes me ANGERY

**Comment by Exxion** [comment]
It's not that the objects get moved outside of the closets
But that they never get moved in

**Comment by Exxion** [comment]
(You can "fix" this by only using pre-filled closets and safes in map elements)
