### ISSUE TITLE
thermal homeostasis regulators only build half when flatpacked and cause sick runtimes when people try to use them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13017]
(WEB REPORT BY: probe1 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

d0d5d4e94f26fcaa1dd6de35f5bac7648fd4c6c2 
>General description of the issue

Mechanics were never meant to scan multi tile machines and never given the proper coding to support it but by god we decided to let them do it and this is the half built sleeper bed we lie in.

>What you expected to happen

The manncrowave to be fully built
>What actually happened

it was only half built and shit went to hell.  It can't even be deconstructed.

>Steps to reproduce if possible

scan a manncrowave and try and build it, try to get in it and look at all those sick runtimes.

**Comment by 9600bauds** [comment]
Could be fixed by removing the microwave

**Comment by Kurfursten** [comment]
IIRC sleepers and FBS autogenerate a console if one is missing, so mancrowaves should do that too

**Comment by Exxion** [comment]
The Mancrowave is a sleeper
And that autogeneration also fucks up flatpacks

**Comment by Fruktlimpa** [comment]
It CAN be deconstructed it is just that sometimes it deletes itself when you screwdriver it and sometimes it doesn't, allowing you to pry out the circuit board and reconstruct it which results in a fully fledged mancrowave.

When I used to do telebay this was one of my main gripes and I ran into the self-deleting mancrowave several times but some other times it played nice and allowed itself to be deconstructed.

**Comment by DamianX** [comment]
Fixed by making it a single-piece machine
