### ISSUE TITLE
Rev victory condition only counts roundstart heads of staff.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13016]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
It should count latejoin heads as well.

**Comment by Ephx1** [comment]
_Rev shouldn't exist in the first place_

**Comment by Allspice** [comment]
Baby steps.

**Comment by Ephx1** [comment]
But no, really, outright removal aside, this is always how it's been.
I can't be too sure of the reasoning, but maybe someone else knows?
It seems a bit silly if this wasn't on purpose.

**Comment by Wizardcrying** [comment]
I suppose it's something for rev heads, being that having to kill more heads that just latejoined would be a pain in the flash. However, something that goes for this issue is that the revolution would have already spiraled out of control by then, and one more thing for the revolution to fight could act as a balancing force.

**Comment by Sprok0** [comment]
It would also encourage hanging around the arrivals shuttle and ganking any latejoin heads, which isn't fun for anyone involved.

**Comment by Allspice** [comment]
Revs are already 'encouraged' to gank heads/implants as they walk off the shuttle, head revs encouraged to flash the rest.

**Comment by AutismSpider** [comment]
Game mode more awful then lings and vamp. 

Who ever OK touching it up and not taking it out like ninja code needs to be shot in the head and toss into pit of spiders.

**Comment by Probe1** [comment]
It's a group failure @AutismSpider 

Anyway look we get antag datums squared away and then we fix this kind of dumb shit because the code doesn't give us aneurysms.

**Comment by Kurfursten** [comment]
No longer the case
