### ISSUE TITLE
Separate Grinder Shortcuts

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#13021]
Months ago back in #10958 @9600bauds added an additional alt shortcut to the grinder where it grinds if it has something in it. At the time I said we should use separate shortcuts but he never really got back to me, and we still need to do it. This is something someone who plays a lot Service notices frequently:

If you fill the grinder with an item that produces more than 10u (tomatoes, for example) you will end up generating more than 100u. The grinder will fill up with ketchup and have leftover tomatoes - but then you can't alt click the beaker to remove it (alt tries to grind it if there are items inside) or alt click to grind (can't grind if the reagents are full). In essence, shortcuts stop working in this relatively common case.

If you separate the shortcuts between alt and ctrl, this gridlock will never happen.

**Comment by kilozombie** [comment]
Oh my god, I can grind woodapples even faster now. Yes yes yes, this would be incredible.

**Comment by Probe1** [comment]
oh man I thought this was a PR for some reason and was wondering why I couldn't hit merge.
