### ISSUE TITLE
photos + mannequins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13027]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

dressed mannequins show naked on photos
>What you expected to happen
photos of dressed mannequins

>What actually happened

naked mannequins
>Steps to reproduce if possible
take a photo of a dressed mannequin

**Comment by ShiftyRail** [comment]
Dupe of #12626
