### ISSUE TITLE
Snowmen cause hypothermia when firing at people

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#13028]
#### Description of issue
Snowmen, when aggressed, cause hypothermia due to the chilling effect they produce with their shots. This could potentially kill someone or otherwise render them immobile. Wearing a blanket didn't really help.

#### Difference between expected and actual behavior
I expected not to get hypothermia from getting into a snowman snowball fight
I did, and got stunned hard at one point ("`You can't feel your hands!`")

#### Steps to reproduce 
Aggress a snowman with a snowball.

#### Length of time in which bug has been known to occur

Probably since snowmen were reintroduced

#### Server revision

6ea048906508dc15d7f42e956b10b3b84795a942 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Uh, there shouldn't be any snowmen that attack in easily reachable places.

Sounds like a mapping issue.

**Comment by jknpj** [comment]
They are bolted down inside ghetto surgey in box, it's not so easily reachable

**Comment by Probe1** [comment]
Yes I put that one there intentionally in the spirit of ``` OH GOD ITS LOOSE ```

Can you kill it with a welder before you become hypothermic and die?

Also they're retaliate so it should not harm you until it is harmed (by any source)

**Comment by jknpj** [comment]
you can kill it with a few punches and it will literally just say "whatever" and stop agroing you after a while if you stop attacking it

**Comment by Probe1** [comment]
Sorry but this was sort of the point
