### ISSUE TITLE
Crate viruses are IMMENSELY overpowered compared to isolated viruses and I need YOUR ideas for how to fix this.

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13032]
Skip to the bolded text at the bottom to get the rundown if you don't want to read everything.

I was planning on opening a PR to decrease the amount of virus food that the virus food dispenser contains but I realized after some speculation that it would only result in making virus crates even MORE unbalanced compared to homegrown viruses. Let me explain by first stating the facts.

- Crate viruses start with 5-50 growth (~30).
- Crate viruses ALWAYS have random symptoms and antigens, so there's no point growing them past 60 (analysis + splicing) or 50 (analysis, then pop them back in for 10 more if you want to splice) growth. You never need to radiate them since they'll be just as random regardless.
- Apart from getting the crates, virus crate viruses are only time limited by how fast you can click a dish and stuff it into the incubator.

Meanwhile

- Isolated viruses start with 0 growth and need to be taken to 100 (actually 120) since you have to wait for the isolator as well as try to maximize new symptoms per unit of time by cooking them longer.
- Isolated viruses usually get 1-2 major mutations per 100 growth. Each major mutation results in a "new" symptom, however, there's is an increasing chance with each new mutation that you overwrite a previous mutation. You also have a lower chance of getting a "good symptom" because isolated viruses can mutate towards badness=2 effects while crate viruses don't. Per new symptom, crate viruses have a 5% chance of changing antigens. 
- Isolated viruses are time limited by how fast it takes the isolator to spit one out (roughly 120 growth worth of time), and makes you waste your time constantly having to make the isolator keep running.

So this means that, on average

- **Isolated viruses spend 5x more time being cooked, wasting 5x the virus food, to get 1/2 the new symptoms and 1/10th the chance of new antigens, while making the player have to deal with 30% more machinery, constantly click the isolate and radiate button, and leave a mess in the incubator and isolator that will JUST fuck your shit up if a virus is on the loose and you need to flush the incubator and clear the isolator and deal with the vials that are left behind.**

# It literally takes FIFTY FUCKING TIMES LONGER to get all the antigens with isolated viruses instead of crate viruses. This makes it ALWAYS worth it to spend up to half an hour grabbing virus crates and begging for access to unlock them instead of having to deal with isolated viruses.

We need a rebalance. Share ideas here.

**Comment by Probe1** [comment]
who even cares about antigens when you can cure a virus in under five minutes?

**Comment by despotate** [comment]
To pre-emptively cure viruses before they even begin spreading.

"THERE'S A VIRUS ON TH-"
"Antibodies are available at chemistry"

The numbers don't look good for symptoms either, though. 10x the time per symptom.

**Comment by Probe1** [comment]
Way way too much work.  Just cure it as it comes in my experience.

I have seen people do it that way but I see it more of making lemonade out of lemons because the jobs so shit than an actual valuable contribution.

**Comment by despotate** [comment]
The entire job of virology has to be rebalanced. I agree. Step one would probably involve getting isolated viruses to be worth anything when compared to crate viruses. Any ideas?

**Comment by Kurfursten** [comment]
It's nice that SOMEONE wants crates from Cargo. But maybe let the Virologist just have virus crate access.

**Comment by Probe1** [comment]
Every time I've asked that I've gotten a "no" from everyone.  

Alternatively borgs, the CMO, the HoP, the Captain, and mob/goats can open your crates.

**Comment by jakmak3** [comment]
Again the balance behind this is 2 fold since it has to rely on 2 people not having severe autism. The first being the cargo techs who 90% of the time either wont order the crate OR wont mail it to the right place and the second is the CMO who has to be the one to open the crate since its CMO locked meaning you need to go through the mess of cracking the crate OR being a traitor and choosing to buy a emag.

**Comment by Probe1** [comment]
@jakmak3 this isn't the thread and we are having a real discussion between people who _play the game_.  There's no need to exaggerate to the point of absurdity unless you don't want anyone to listen to you.

If cargo is ignoring you 90% of the time there is something going on for you that isn't going on for the rest of the players.

**Comment by despotate** [comment]
Usually if cargo / the CMO don't open their crates I just escalate my requests by asking borgs, AI, the HoP/Captain for access, engineering, etc. until I get what I want. This game has other players in them. Learn to interact with them without shoving console-printed sheets of paper at them.

These are terrible "barriers" to virus crates regardless because virus crates are just so much more efficient that I'd rather waste an hour finangling myself around the system to get them delivered than endure the monotony of incubating isolated viruses.

**Comment by DeityLink** [comment]
Kinda no longer relevant. The amount of virus food needed doesn't matter either since you'll click once with the dish on the dispenser and slap it in the incubator, and growth dish no longer let you get all antigen by themselves.
