### ISSUE TITLE
ornaments don't work on plants potted by botany

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13035]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 55b5f3f1ca3678f579a7358ce133e90a38cef0e3 

>General description of the issue
the new ornaments were added, and they're all fun and all, but they don't work on potted plants like the one you can make with sand, it only works on round start potted plants which is kind of a let down

>What you expected to happen
being able to add ornaments to my own custom potted plants

>What actually happened
didn't work on my potted plants

>Steps to reproduce if possible
grow a plant in hydroponics
make a pot
pot the plant
attempt to add ornament

**Comment by Shadowmech88** [comment]
My guess would be because such plants aren't children of `/obj/structure/flora` like potted plants are, for some reason.
I'll look into it.
