### ISSUE TITLE
Rev+Revsquad both autorecall the shuttle

### ISSUE THREAD

**Issue by Allspice** [d3athrow/vgstation13#13042]
Jesus fuck please remove it.

**Comment by Exxion** [comment]
In Revsquad, it's a bug. (#12534)
Normal rev is up for discussion.

**Comment by JustSumBody** [comment]
Remove

**Comment by Probe1** [comment]
I do admit after observing plenty of that round last night @JStheguy that this isn't working well.

An auto recall has its place but it should probably be time gated for the first hour.

**Comment by Kitfox88** [comment]
just remove rev, shit mode
