### ISSUE TITLE
snowmap crashed serb

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13057]
It wasn't in the rotation, which is good, but it still got loaded, which is bad
About twenty minutes in it crashed
This is more a reminder to myself to look into the runtime logs than anything else, also a general reminder to not play snowmap
in terms of bugs, aye there were a few but I think it was a fairly successful round really

Also re: the crash, I'm deeply sorry that happened. I guess it gives you all time to spend christmas with your family or something - Personally, I had the server left on for a day by accident and I didn't get any issues but I can't put into words how apologetic I am this happened even if it was unpreventable, because in the end this wouldn't have happened without snowmap and as soon as the runtime logs are available I'll be working as hard as I can to figure out why

they say a picture means a thousand words so here take this as an apology
![](http://cl.jroo.me/z3/c/D/c/e/a.baa-Awesome-Apology-Cake.jpg)

**Comment by Ephx1** [comment]
Good cake, would eat

**Comment by ghost** [comment]
The cause: we ran out of lists. Not a snow map specific issue, but as snowmap has more objects than box and *someone* added three lists to atom movables , well. It's the same issue that caused that big crash a couple weeks ago, and again, is not a snowmap issue.

**Comment by PJB3005** [comment]
Nice meme.
