### ISSUE TITLE
Wheelchair Riding

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13067]
(WEB REPORT BY: consedfu REMOTE: 172.93.109.202:7777)
>Revision  db4fae77cf325c86de183f6a6414c8355c8bde46

>General description of the issue
When you climb into a wheelchair the character sprite overlays it instead of going behind the armrest / onto the seat (ect.)

>What you expected to happen
I would look like I'm actually in a wheelchair after getting into it

>What actually happened
Looks like I'm clinging onto the side of the wheelchair

>Steps to reproduce if possible
Climb into a wheelchair

**Comment by Shadowmech88** [comment]
Maybe a planes issue?

**Comment by Kurfursten** [comment]
The way to fix this would be kind of a pain, because you would need to do one of two things

>Make the wheelchair so flat 2D that you can't see the seat if it's turned sideways and empty.
>Break the turned wheelchair sprite into 2 parts - the side and the rest. Layer the side above humans inside the chair and the rest below.

**Comment by troots** [comment]
that or have two sets of wheelchairs, one for empty and another that is always on top of the player, but has specific pixels removed so that the player is visible in specific areas

**Comment by Exxion** [comment]
I mean
We've already done this for comfy chairs and couches

**Comment by Kurfursten** [comment]
IIRC comfy chairs have a flat side sprite

**Comment by Exxion** [comment]
Yes
The same could be done for wheelchairs.
