### ISSUE TITLE
Stage 2 singulo thinks it's bigger than it really is

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13062]
Take a look at this code.

![atom_2016-12-25_16-43-06](https://cloud.githubusercontent.com/assets/6526157/21472604/3f9f9224-cac1-11e6-8d47-829a9bcfe1be.png)

When the stage 2 singulo checks for shield generators to bounce off of, it checks 3 tiles away rather than 2. Essentially, singulo movement treats 3x3 singulos as if they were 5x5.

This results in two things:
One, like a really infuriating DVD screensaver, the stage 2 singulo will never bounce off the shield generators, always stop 1 tile before.
![dreamseeker_2016-12-25_16-44-33](https://cloud.githubusercontent.com/assets/6526157/21472612/90a4e2dc-cac1-11e6-9d91-6b8c2f475679.png)

Two:
![mpc-hc64_2016-12-25_16-46-35](https://cloud.githubusercontent.com/assets/6526157/21472623/cd19c4e4-cac1-11e6-9319-872a0ba76f38.png)
![mpc-hc64_2016-12-25_16-46-58](https://cloud.githubusercontent.com/assets/6526157/21472628/ea76026e-cac1-11e6-99ce-a9b361e56782.png)
![mpc-hc64_2016-12-25_16-47-14](https://cloud.githubusercontent.com/assets/6526157/21472629/eb9995d4-cac1-11e6-92b1-04abfd3adefb.png)
If a singulo is created too close to the border, when it grows to stage 2, it will think it's 5x5, not 3x3 like it really is. So its movement checks the tiles on the OTHER SIDE of the containment field, and thus thinks it's OK to move that way.

Theoretically, fixing this would be as simple as changing this 3 to 2.
![atom_2016-12-25_16-43-06](https://cloud.githubusercontent.com/assets/6526157/21472642/2bec63aa-cac2-11e6-9077-090771c6c9a8.png)

But it says "yes this is right", plus it's SINGULARITY CODE, maan, someone else do it

**Comment by 9600bauds** [comment]
https://github.com/d3athrow/vgstation13/commit/337be2c3bcc7a739ffc927ccce9d6aa2b43c114c
mport2004@gmail.com, why

**Comment by Probe1** [comment]
```  committed on Feb 9, 2011 via svn ```

oh boy

**Comment by Exxion** [comment]
This is going to sound crazy, but why don't we rewrite the singulo to actually use movecode?

**Comment by Probe1** [comment]
You have no idea how many times in the scant week I've been a collaborator I've tried to attach a label to a comment and most of them like now, have been [WYCI].

I would love that.

**Comment by Sprok0** [comment]
A bit of thoughts about this, the singularity will not expand from stage two to three if it's right next to a shield gen. If it could hug the walls consistently it'd be hard to tell when it was at a good size. Setting it to the right size also doesn't keep it from growing into the shield wall if the generator/1x1 sing was next to the wall in the first place, but that's more an issue with setup.

**Comment by 9600bauds** [comment]
It would only hug the walls for a little while then move away and properly expand

The "1x1 sing eats shields" is apparently intended, stage 3 and 4 have checks against it

**Comment by Sprok0** [comment]
It's becase the 1x1 doesn't move, so if it checked for shields it would just sit next to the shield and build up energy forever
