### ISSUE TITLE
Grues are fairly lackluster

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#13069]
After having a bit of experience playing as one(grue), I feel like they could use some touching up. As-is, it's very difficult to distinguish between slightly lit and dark areas, which leads to you either being seen or just die to light.

- Flashlights kind of just kill them. Perhaps a system where light sources would push them away, or something like a vampire's jaunt that teleports them to a dark area would be better.

- They're very weak and have very little health overall. The perma-hulk kind of helps this, but the fact is they will just die to a few laser shots anyways. I'm not sure if they're weaker than regular humans, but they sure do feel like it. 

- Since their whole gimmick is about being in darkness, maybe give them a way to open/move around/force open maintenance doors. You just kinda get trapped in one area.

- Cyborgs make them pointless.

Out of all of these issues, the light sources that can be thrown (Lanterns, flashlights) just feel really bad to be against. There's no real defense for it other than just running away.

Overall, it's a neat idea, but I feel like it needs some fleshing out if you want it to become something more than just a couple of powers on a hulk.

**Comment by Shadowmech88** [comment]
>Flashlights kind of just kill them.
>the light sources that can be thrown (Lanterns, flashlights) just feel really bad to be against. There's no real defense for it other than just running away.

Did you try using your swallow light ability to negate the crewmembers' portable light sources?
>I'm not sure if they're weaker than regular humans, but they sure do feel like it.

They take double brute and burn damage.
>maybe give them a way to open/move around/force open maintenance doors

Grues have hulk, you can just bust down a wall into maintenance instead of using the airlock.
>Cyborgs make them pointless.

It's true that grues have no offensive strategy against them, but unless combat borgs are deployed they still can't see in the dark or fire projectile weapons, so evading them shouldn't be too difficult.

What changes would you suggest?

**Comment by kol1th** [comment]
I don't believe the swallow light ability works on flashlights or cyborg flashlights. Maybe it did, but like I said, it's very difficult to distinguish between poorly lit and unlit areas.

Maybe a way to force open airlocks with a timer like Skullyton's zombies can. Something that won't leave lasting damage like breaking down every wall in your path. 

Also, they go from VERY fast to very slow after taking damage, so once you do basically any amount of damage to them they become trivial to kill. 

What I mean by cyborgs being pointless is, without them taking normal measures against cyborgs (ions, flashes) they have no way to fight back. Can't even punch them as a hulk.

**Comment by Shadowmech88** [comment]
>I don't believe the swallow light ability works on flashlights or cyborg flashlights

It generates a very strong negative light source, so it should work on all positive light sources.

**Comment by kol1th** [comment]
I had the power active before, and a cyborg standing next to me with its flashlight module on was enough to kill me.

**Comment by kol1th** [comment]
I'm mistaken, it was just circumstance that made me think the light had killed me, when in reality it was just the modifiers paired with low pressure.

**Comment by Iamgoofball** [comment]
you are not likely to be eaten by a grue

**Comment by ghost** [comment]
Cyborgs make everything pointless

**Comment by Kurfursten** [comment]
Cyborgs have very poor balance and are not a good metric to measure the strength of anything by.
