### ISSUE TITLE
Null Space Blob Core Spawn

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13068]
(WEB REPORT BY: jalis REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

db4fae77cf325c86de183f6a6414c8355c8bde46

>General description of the issue
Spawned in as blob overmind, and core is located in nullspace (?) / pitch black screen. Had 0 health and could not do anything.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Shadowmech88** [comment]
Given the lack of steps to reproduce and the age of this report, I think it can be closed.
