### ISSUE TITLE
medbay pipe devices

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13073]
on all maps, the cryocell pipe devices are pretty ugly because they are placed above the floor tiles, i think that they look a lot better if they're placed under them:

![box](https://cloud.githubusercontent.com/assets/6170726/21482129/4992a442-cb70-11e6-86f3-f6b14beda6e1.png)

it could be also done for paramedics cryocell.

**Comment by Probe1** [comment]
Things I'm gonna fuck with:  
pipe layouts
adding/removing pipes
bowls of ice cream

Things I'm not gonna fuck with:
wasps
layers
planes

**Comment by uazuaz** [comment]
well, to put them under the floor tiles you just need to wrench the device on a floor with no floor tiles, then add the floor tiles; what could go wrong when mapping it?
if you want to see it, i just modified them on the test server right now.

**Comment by PJB3005** [comment]
All you have to do is to make a subtype of the pumps and such that has `level = 1` and they'll be below the floor.
