### ISSUE TITLE
smart gun thread

### ISSUE THREAD

**Issue by jakmak3** [d3athrow/vgstation13#13081]
If you eject a empty PAI from a smartgun it causes the PAI to despawn

**Comment by Probe1** [comment]
guess whos about to get yelled at

(its @Shadowmech88 )

**Comment by JustSumBody** [comment]
Some clarification: The pAI doesn't despawn, if you're holding the gun it's moved into your mob's contents. If you eject it while it's on the floor it pops out on the floor where the gun is.
In addition: PAI guns can only fire from the forbidden locations(Disposals)
