### ISSUE TITLE
Emancipation Grill Plox

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#13089]
I would try and code it myself but I dont know how. 

Basically a field that will only allow someone carry certain items through, just like in portal. But I think it would add an extra level of difficulty for vaults that will make some loot worth it. 

If anyone wants and idea of how it should work I thought that the grill should have a list of whitelisted objs and be able to be turned on and off from a switch or from the APC. It doesnt need to be buildable since this can be a little OP for station use

**Comment by Shadowmech88** [comment]
Should be easy enough. Just make it a non-dense anchored structure with a var holding a list of allowed items, and then on `Cross()` loop through the contents of the atom crossing it and `qdel()` anything not in the list.

**Comment by SkowronX** [comment]
Apply this to the gateway and allow certain items to be disallowed by admins. (disallowing parent objs and their children perhaps.)

**Comment by AlphaBuffalo** [comment]
I wouldnt have it qdel them, but instead, it would act as a wall, so people dont lose stuff like diamond sheets

**Comment by Kurfursten** [comment]
If you want them to drop before entering you should use Bump instead of Crossed

Although I foresee the same amount of cheesery as getting onto Centcomm or leaving Derelict Z-level as a MoMMI

**Comment by Probe1** [comment]
Somebodies working on this but I forget who

**Comment by AlphaBuffalo** [comment]
Its me, blarghargin123

**Comment by Exxion** [comment]
For the love of god don't recursively loop through all `contents`
There's a proc specifically for this kind of thing. It's what the game uses to check for steal objective completion. It only checks things that are accessible under normal circumstances.

**Comment by ComicIronic** [comment]
What if I throw something at it? What if I drop an item next to the field, stand on it, and pick the item up?

**Comment by AlphaBuffalo** [comment]
ideally it would emancipate those as well

**Comment by ghost** [comment]
If you throw something at it that's not allowed, it'd bounce back off

And surely you can have something like where you can't pick up things on the other sides of one-directional windows in regards to picking up objects next to the field

**Comment by Kurfursten** [comment]
I really think the best way to do this is a dense object with a Bump behavior that forcemoves "in" after removing their non-whitelisted stuff. That way thrown objects would naturally bounce off (or be allowed in if on the whitelist)

Seems cleaner this way because in the case someone breaks it, it's still effectively a wall.

**Comment by Shadowmech88** [comment]
@Exxion 
You're thinking of `search_contents_for()`.
But that takes a specific typepath and returns a list of object references with that typepath. The grill will use a whitelist, not a blacklist, so `search_contents_for()` would only be useful for getting a list of the stuff that doesn't need to be emancipated, which isn't very useful at all since what is needed is a reference to the stuff that *does* need to be emancipated so it can be `qdel()`'d.

**Comment by ghost** [comment]
Why not a whitelist version and a blacklist version?

**Comment by ComicIronic** [comment]
We can always use the inclusion-exclusion system used by stuff like storage items, which does both whitelisting and blacklisting.

**Comment by ultraplen** [comment]
@AlphaBuffalo are you still working on this ? Because if not, I am stealing the idea.

**Comment by AlphaBuffalo** [comment]
@ultraplen go for it I broke it after trying to fix it and I have no idea what to do

**Comment by AlphaBuffalo** [comment]
Also I don't even have a computer right now so I can't even do shit

**Comment by SkowronX** [comment]
ahahahahaha

**Comment by AlphaBuffalo** [comment]
![](https://cdn.discordapp.com/attachments/239836068491296788/263394195023200258/Untitled-1.gif)

When I was making the code originally unusual cow made this sprite for me

I also lost all the code for it because I'm stupid and delete things a lot :^)

**Comment by AlphaBuffalo** [comment]
![](http://i.imgur.com/DLghYdX.png)

thanks to the power of discord archiving I found a screenshot of the code I made originally for the grille that then got abandoned because I couldnt figure out how to make it qdel items thrown through it, dropped on it, picked up on it, or any other way to getting an item through without already holding it and walking through it :^)

**Comment by MadmanMartian** [comment]
Most useful, thank you.

**Comment by AlphaBuffalo** [comment]
Not a problem, I wish I could code better or had a better understanding for this shit
