### ISSUE TITLE
Let Security PDAs dispense police tape.  Let security pAIs dispense police tape.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13088]
Nigh worthless roleplaying object -> easier to use -> might get used.

Ditto on engi tape to engi PDAs.

**Comment by SysadminJeroen** [comment]
Atmos tape for atmos PDAs

**Comment by Ephx1** [comment]
So what, let Security pAIs who are in sec PDAs do it, or just those with the sec HUD?

**Comment by Riekland** [comment]
Both, I'd say
sec tape is always useful when you don't take it and never useful enough to give up another pair of cuffs
I want to feel like a proper polis
