### ISSUE TITLE
The Janicart can "clean" the AI's hologram

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#13087]
And by clean I mean run over and obliterate from existence. You still control it, just that its icon disappears.

**Comment by 9600bauds** [comment]
This is wonderful

**Comment by kol1th** [comment]
astonishing

**Comment by Exxion** [comment]
I don't even WANT to know what the fuck is going on in the code that could cause this

**Comment by Ephx1** [comment]
My only guess is that it somehow counts as one of those overlay sprites similar to blood.

**Comment by Probe1** [comment]
Though it inarguably needs fixing I refuse.

**Comment by SonixApache** [comment]
Still an issue.

**Comment by jknpj** [comment]
All right, janicarts clean: `(istype(A, /obj/effect/rune) || istype(A, /obj/effect/decal/cleanable) || istype(A, /obj/effect/overlay)`

The holograms are `var/obj/effect/overlay/hologram/`

The question is, shitcode or feature?

**Comment by Exxion** [comment]
>Janicarts clean any /obj/effect/overlay

Wow, that's fucking disgusting. It's a good thing we barely ever use them.

**Comment by Probe1** [comment]
I still say its a hilarious feature.

**Comment by SonixApache** [comment]
janiborgs do the same thing, for that matter
