### ISSUE TITLE
flatpacks.

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13093]
#### Description of issue
- flatpacks can be stacked by ghosts.
- even if you're alive, you don't need to be adjacent to them to stack them; they just need to be in sight.

unstacking seems to work fine.

#### Difference between expected and actual behavior
as a ghost, expected to being unable to stack them, i was able;
when alive, expected to actually touch them to stack them, i can do it from few tiles away.

#### Steps to reproduce 
be ghost, stack them.
be alive, stack them without touching them.

#### Length of time in which bug has been known to occur

noticed just now, i don't really know.

#### Server revision

9ee2efc1e2e3209f114b0a319b710c11a81e15eb 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
@ComicIronic

**Comment by Probe1** [comment]
prob just a clickdrag check
