### ISSUE TITLE
Making vox raiders not trash

### ISSUE THREAD

**Issue by jakmak3** [d3athrow/vgstation13#13090]
As we all know raiders is one of the WORST game modes in rotation. What this devolves into 90% of the time is idiots running around trying as hard as they can to collect valids on a bunch of under equipped birds who cant fight back or stealth raiders which turns into SMELELELELE.

This of course is a awful gamemode that does have potential. Essentially post ideas to not make raiders garbage.

My ideas as follows

Remove the raiders flying home = round end

have auto traitor running in the background with of course the raiders exempt from being tatored. The main issue with the valids is the entire crew knows they can trust eachother. They have no fear around eachother so you see everyone getting all access and a shotgun as soon as someone yells BIRD OPS. If they crew knows that they cannot trust eachother then they will be less inclined to take up arms to fight the group of bird niggers stealing engineering equipment

allow the raiders to speak common. Not being able to speak common makes a peaceful resolution much much harder to come to. Yes sure you can use a translator but it always turns into a complete mess trying to do so. If not all of them speaking common have atleast 1-2 of them speak common

Downsize the raider team size from 6 to 4. 6 birds is way to hard to control

Allow the raiders to pick their own names. Having a preset list of names makes it easier for powermemers to figure out there are raiders.

Give the raiders normal gray backpacks. That yellow engineering backpack sticks out like a sore thumb

Borgs. Borgs ofcourse always are a problem for raiders since a single non sec borg can and will fuck up the entire raider party's day. The thing is that the raiders do have anti borg weapons (emp rifles and ion grenades) BUT as we all not these weapons are not at all suited for fighting borgs. The solution? Make the anti borg weapons actually effective

Remove the feature of their radios being able to hear all station side frequencies. If they cant speak common its useless and if they CAN speak common it would be unbalanced. Maybe instead give them normal encrypted freq radios capable of only hearing its own freq and some station bounced radios so they can blend in as traders more easily and still be able to hear common

Deep space. As we all know when the raiders go to deep space round ends and everyone gets a antag re  roll. Instead have deep space be a location similar to the nuke op base in which they can go there with no risk of having an assistant stumble upon them in deep space so they can respite and store all their stolen goodies. Along with this add the area this base would be in to count as the raiders WIN space where objects on those tiles count towards the victory conditions. Ofcourse like the nuke op base have it be 200% resistant to keeping the crew/raiders from being able to get out of the base into z level 2

Skipjack. The skipjack design does have some issues. This is what changes i feel the skipjack need some changes to be able to suit the raiders

http://imgur.com/j6gh7C5

Circled in blue in the bird prison. The bird prison is not fit to hold people for several reasons.

1. there is no air tanks or masks for the prisoners who would suffocate on the vox air unless they had a large 02 tank with them when they were kidnapped. Give them a few airtanks and masks

2. If a prisoner has a air tank then that prisoner could just use that tank to break the window/windoor and escape meaning the vox cannot reliably hold prisoners hostage in that room since they would just escape. Instead replace it with a ultra reinforced wall and a airlock that can be bolted via button outside of the cell.

Add some N2 tanks in the green X and in the ships airlocks so the raiders can always have some spares.

And replace the circled in purple stations alert with a camrea console so the birds can scout ahead.

Also a key flaw in the skipjack is that it can go to 4 places (5 if you count the round ender)

http://imgur.com/umKzeOl

3 places around station and the vox trade post. All of which are very predictable places.

As oppose to the nuke op ship which can go to 8 locations around the station and several locations on other Z levels.

The raiders who are intended to be a agile and very mobile attack force can only go to 3 places around where the target station is and 1 place away from the station. This is completely ridiculous and locks the raiders into a select few places they can go to hide making easier for the crew to valid them. Bottom line is raiders need to be able to fly more places

Last broken bones for a raider usually mean that individual is useless to the team since the raiders have no way to mend broken bones. Adding a surgical setup would be to much so instead add in some of those advanced medikits that have the medical splints in them that allow for temporary mending of bones. 

I know most of these ideas suck but i mean they cant be any worse than what we have now

**Comment by Ephx1** [comment]
> WORST game mode in rotation

It's not rev.
I'm fine with most of these ideas, but it's funny you mention borgs when they only give a shit you're there if you harm someone (something you don't do)

**Comment by ultraplen** [comment]
> WORST game mode in rotation

Its not vamp.
Its one of the better gamemodes, atleast in concept. It could need some rebalancing though.

**Comment by jakmak3** [comment]
> when they only give a shit you're there if you harm someone

yeaahhhh about that

According to all non meme lawsets vox are valid
Asimov = not human = valid
NT default = not crew = valid
robocop = enemy of the corp = valid
paladin = ???? = valid or not paladin is a total shitshow


Any what i intend with this is during raider rounds for the vox themselves to almost be a sideshow in the regular action. If they are the main attraction and with their lack of a ability to take on large groups of attackers they would get raped but if they were something on the side it would be more interesting to deal with.

**Comment by Ephx1** [comment]
They may be "valid" but most of the time I don't see these valids collected unless you break your inviolate.

**Comment by Probe1** [comment]
It'd be fine as a random event in my opinion.  Just have it check off objectives cultstyle when the previous objective reaches Z2 and let them go back and steal some more.

It's pretty weak no matter what you do as a main game mode type.  It's either poor mans nuke ops or some weird semi RP not very antagonistic thing.

**Comment by jakmak3** [comment]
yeah i agree with probe on that. Its better for them not to be the main deal but something interesting none the less. Essentially imagine traders BUT with a lot less restraints and more inclined to fuck shit up. And ephx1 most silicon players actively go out to find valids whenever presented if its in the form of a vox

**Comment by jakmak3** [comment]
God dammit the image isnt working

**Comment by Probe1** [comment]
you can upload images directly to github by dragging it into the text field.

the real problem here isn't anything any of us have said.  it's that none of us have the motivation to code it.  also hopefully bauds is refactoring antag datums so coding it isn't a pain in the ass.

**Comment by jakmak3** [comment]
Most of my changes would be easy. Just a few map changes and some changes in what they spawn with. The real issue is doing autotraitor in the backround. I only made this to collect ideas and get feedback before i commit to doing these changes

**Comment by Probe1** [comment]
That is the substantial part of it unfortunately.  It does not work well by design.  Increasing their infiltration abilities will not correct that.

**Comment by jakmak3** [comment]
Yes. it all goes back to the crew needing something to distract their valid boner long enough for raiders to get away when found out

**Comment by Probe1** [comment]
I mean the nicer way of putting it is raiders just aren't entertaining enough and eventually no matter what they do someones gonna be bored enough to start a fight

**Comment by jakmak3** [comment]
![this entire pr](https://cloud.githubusercontent.com/assets/22970318/21487164/28e75424-cb91-11e6-8b79-300e10002b5d.jpg)

**Comment by jakmak3** [comment]
I realized i posted the wrong image by accident. THIS was the actual image
![1474926399593](https://cloud.githubusercontent.com/assets/22970318/21488259/64abde02-cbab-11e6-8187-feb5c7ad40c5.jpg)

**Comment by kol1th** [comment]
>Asimov = not human = valid

What did he mean by this?

**Comment by icantthinkofanameritenow** [comment]
@kol1th 
Self-explanatory. They're not human, so borgs can kill them without fear of BWOINKing.
