### ISSUE TITLE
Butchering as a grue

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13094]
What the PR implies is that you can butcher bear handed a human corpse to be able to heal yourself.

What seems to actually happen is that it insists that you're trying to do CPR, or punching the dead dude.

Some better stipulation on how to butcher would be great.

**Comment by Kurfursten** [comment]
Which intent did you use, in case it matters?**

** I have no idea if it matters for grues, but it does for humans.

**Comment by ghost** [comment]
Help: Attempts CPR

Harm: Punches the dead guy

Grab: Grabs the dead guy

Disarm: Disarms a corpse

**Comment by ghost** [comment]
Also, for their whole triple speed, they suffer serious pain slowdown

Maybe take away the bonus speed and make them pain immune?

**Comment by Shadowmech88** [comment]
Butcher is a verb.
Right click -> Butcher

**Comment by Exxion** [comment]
Same as vox without masks
