### ISSUE TITLE
Box cargo ATM deposits money onto window tile

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13099]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)
When you press the withdraw button on the cargo ATM in box, the money plops out onto the window tile just northwest of the ATM.

**Comment by Probe1** [comment]
I fixed this and tested it to make sure it didn't happen..

**Comment by Probe1** [comment]
Great, someone added ANOTHER atm to cargo.  I'm gonna remove it.

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/21499539/cbac9840-cc04-11e6-8f0b-7e550175608a.png)
