### ISSUE TITLE
Feature Request: Brain Revival

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#13098]
So today I was neurons got firing and something came to me, why do we not have a way to start the old grey matter again for dead brains? Most of the time you see brains die it is because of incompetent doctors or robotocists, its kind of shitty for players to be taken out of the round due to the wild ride or just pure incompetance. I think there should be some kind of machine you can pop brains into to get them back or even a chemical that can be injected to revive them so that someone who isn't shit can come in and save the day.

**Comment by Probe1** [comment]
what you're describing is if a player ghosts.

**Comment by AutismSpider** [comment]
the brain dies over time probe if its not put in an mmi or a freezer same thing happens organs.

**Comment by ghost** [comment]
I thiiiiiiiink this might be one of those urban rumours as to why there's a freezer in medbay

**Comment by JustSumBody** [comment]
Alright, some testing and looks at organ code. Here's how it works:

Brains decay over time like other organs unless they're in a cryobag, freezer, or MMI. When their health reaches 0, the brain becomes a "dead brain" and can't be used in brain transplants. 
HOWEVER, this same brain CAN be placed into an MMI as normal. When this is done, the brain can then be taken out and is at full health. In this sense, MMIs are kind of the solution to your problem.
You can also inject dead organs with peridaxon(whatever that organ chem is called) to restore them I believe.

Also how fucking bad does someone have to be to let this happen it took like 5 full minutes for it to turn dead.

**Comment by PJB3005** [comment]
I can't find any code that would cause the brain to die off over time when not in a freezer, looking at the code at a glance.

**Comment by JustSumBody** [comment]
@PJB3005 it's inherited from "organs"
see: https://github.com/d3athrow/vgstation13/blob/eae088713cf49b4bbc8ff0830b8c30f50dc3910c/code/modules/organs/organ_objects.dm#L38

**Comment by PJB3005** [comment]
Welp.

**Comment by PJB3005** [comment]
Also the reason I didn't see your message was because mobile doesn't auto update the page (presumably for battery preservation reasons)

**Comment by Probe1** [comment]
we should prob just add a return there for brains since brains are spechul

**Comment by ComicIronic** [comment]
Maybe you should just be able to transplant dead organs. It's not like a brain "stays good" in a corpse just because it's inside the body, it's just as dead as the rest. The downside from organs going off should stay. Then you would be unable to defib a dead brain, but you could still clone them.

**Comment by ghost** [comment]
Organs going off should just accumulate damage to those organs over time.

You put in a brain that's been dead for 10 minutes, the guy's gonna be retarded

**Comment by Kitfox88** [comment]
strokes when

**Comment by Shadowmech88** [comment]
Blood clots when?

**Comment by ghost** [comment]
More organs when?

Switching it from both eyes, to left eyeball and right eyeball, so eyepatches would make sense when?

Butts as an organ so you can re-attach them, or make a cybernetic equivalent when?

Tongues/vocal chords as an organ when, so if you take a species's vocal chords, you can speak their language but not necessarily understand it?

**Comment by Ephx1** [comment]
> so if you take a species's vocal chords, you can speak their language

That makes no sense. I can mimic what Chinese sounds like but that doesn't mean I'm able to speak it in the first place.

**Comment by ghost** [comment]
So you object to alien vocal chords, but not to cybernetic assholes?

**Comment by Ephx1** [comment]
_prosthetic asses already exist_

I don't object to alien vocal chords, but you would still need to know how to speak a language and not just sputter gibberish.

**Comment by Chronakai** [comment]
I support reattachable butts. Not necessarily your own butt.
