### ISSUE TITLE
smart pai loses the ability to fire after hit by a flashbang

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13091]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
get hit by a flashbang cant shoot anymore

>What you expected to happen
temporarly disable the pai power to shoot the laser

>What actually happened
cant shoot anymore removing and putting the pai back doesnt do anything

>Steps to reproduce if possible
put pai into smart gun
get hit by a flashbang
pai cant shoot anymore

**Comment by Probe1** [comment]
@Shadowmech88

**Comment by Shadowmech88** [comment]
I don't see any specific code that has to do with integrated pAIs that I think could cause this.
Could it be a general bug where pAIs aren't able to click because flashbangs stun them forever?

**Comment by ComicIronic** [comment]
I think it would be something like that. Their life() doesn't reduce their stun amount.

**Comment by Probe1** [comment]
I retract the bum label and apologize.

**Comment by Intigracy** [comment]
Andy Senpai! I'm alive and I want to be INSIDE OF YOU.
