### ISSUE TITLE
Synthetics with no power cells can still pull things

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#13107]
I'm not sure if this is intended or not, but I can already see someone getting incredibly butthurt about it.

**Comment by Probe1** [comment]
Its been like this since forever so idk man

The butthurt should be coming any day now.

**Comment by Ephx1** [comment]
Due to how fucky the synthetic damage system is it requires a really weird set of conditions.
Unless it's been changed, you lose your power cell and you can't die, so if someone were to perhaps do that to a synthetic they could still pull things. Heck, people were butthurt they can still move with no powercells - soooooo.

**Comment by Probe1** [comment]
This could be your time to get that contributor tag next to your name.

**Comment by Ephx1** [comment]
I have no real idea what a contributor does other than allow pulls to get merged and issues tagged/closed. I have no coding experience aside from one thing, and I don't play as often as I used to.

Don't think it'd be good for me at all.

**Comment by Probe1** [comment]
thats collaborator.  contributors just a label that github affixes to your name once you've had a pull request merged.

**Comment by Ephx1** [comment]
That's even worse because I wouldn't know where to begin in fixing this and honestly don't care enough to do so. Only reason I reported it is the future visions of "REEEEEE BORGS SO OVERPOWERED THEY CAN PULL STUFF WITH NO BATTERY" just like every other headache that splits open when a robot does something.

**Comment by Probe1** [comment]
That makes two of us!  You could always pop in discord and ask.

**Comment by Fruktlimpa** [comment]
Speaking as someone with no coding experience, isn't this a fairly easy fix? Isn't it just a binary 1/0 if a mob can pull things?
