### ISSUE TITLE
Evidence Bag Thing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13102]
(WEB REPORT BY: nodle66 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Tried to put an incomplete improvised explosive into an evidence bag, but the bag got into the explosive as shrapnel. Upon removal of the bag, the bag seemed to have an ide in it.

>What you expected to happen
I expected the explosive to get into the bag

>What actually happened
The bag got into the explosive

>Steps to reproduce if possible
Make an improvised explosive, and before you add any shrapnel in, try putting it into an evidence bag.

**Comment by Kurfursten** [comment]
Yet another bug caused because evidence bag is a snowflake weapon instead of a container

**Comment by Probe1** [comment]
🤣

**Comment by Exxion** [comment]
Did you just say that when you removed the bag it appeared to have an IED in it?
Congratulations. You've invented physical recursion.

**Comment by Shadowmech88** [comment]
It sound like putting an IED into an evidence bag should spawn a singularity.

**Comment by Kurfursten** [comment]
This kind of ghost item thing isn't a very uncommon bug. Basically, due to lack of sanity the bag ends up with a reference to the IED. I'm guessing that if he tried to take the IED out of the bag it would move it to his hand no matter where the IED actually was, even across the station.

**Comment by Exxion** [comment]
I know, and it is ALWAYS great.
