### ISSUE TITLE
PAI and istruments (bug + feature request

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13113]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
some hand held isturments like the trombone and the honky horn have a remove pai verb because of bugs

>What you expected to happen
what if we turned it into a real feature like 

>What actually happened

>Steps to reproduce if possible

**Comment by Probe1** [comment]
That's it.

I'm telling him not to open dozens of feature requests through the bug reporter.

**Comment by Shadowmech88** [comment]
This is caused because currently all objects have the verb when spawned, and then it gets removed in `/obj/New()`. `/obj/item/device/instrument/New()` doesn't call its parent, so the verb is never removed.

Is there a way to get a verb to not be show up by default?

**Comment by Exxion** [comment]
>`/obj/item/device/instrument/New()` doesn't call its parent

`New()` is one of like two procs that should pretty much ALWAYS call the parent

**Comment by Shadowmech88** [comment]
So should I change `/obj/item/device/instrument/New()` to call its parent?

**Comment by Exxion** [comment]
Yeah, unless there's a REALLY good reason not to
And I doubt there is, in this case
