### ISSUE TITLE
Vox Engineers/Miners spawn with o2 in their survival box instead of n2

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13116]
[species.dm]
[boxes.dm]

**Comment by Probe1** [comment]
also despite a sprite existing plasma men dont have small internals at all

**Comment by ComicIronic** [comment]
They deserve it.

**Comment by Intigracy** [comment]
I think this should stay, or give them an EMPTY tank that's the right color.

They already start with internals.
