### ISSUE TITLE
ADD FUCKIN MUSTARD GAS TO THE GAME

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13112]
#### Description of issue

THERES NO WAY TO SCAR THE LUNGS OF MY FELLOW CREW AS AN ANTAGONIST

#### Difference between expected and actual behavior

I EXPECTED CHEMICAL WARFARE

I DID NOT GET CHEMICAL WARFARE

#### Steps to reproduce 

Bent double, like old beggars under sacks, 
Knock-kneed, coughing like hags, we cursed through sludge, 
Till on the haunting flares we turned our backs 
And towards our distant rest began to trudge. 
Men marched asleep. Many had lost their boots 
But limped on, blood-shod. All went lame; all blind; 
Drunk with fatigue; deaf even to the hoots 
Of tired, outstripped Five-Nines that dropped behind.
Gas! Gas! Quick, boys! – An ecstasy of fumbling, 
Fitting the clumsy helmets just in time; 
But someone still was yelling out and stumbling, 
And flound'ring like a man in fire or lime . . . 
Dim, through the misty panes and thick green light, 
As under a green sea, I saw him drowning. 
In all my dreams, before my helpless sight, 
He plunges at me, guttering, choking, drowning. 
If in some smothering dreams you too could pace 
Behind the wagon that we flung him in, 
And watch the white eyes writhing in his face, 
His hanging face, like a devil's sick of sin; 
If you could hear, at every jolt, the blood 
Come gargling from the froth-corrupted lungs, 
Obscene as cancer, bitter as the cud
Of vile, incurable sores on innocent tongues, 
My friend, you would not tell with such high zest
To children ardent for some desperate glory, 
The old Lie; Dulce et Decorum est 
Pro patria mori.

#### Specific information for locating

PROBABLY WANNA LOOK AT WELDER FUEL VOLATILES TO GET THE GIST OF HOW THE GAME HANDLES IT, AND OBVIOUSLY CHEM GRENADES AND UPLINK.DM.  

#### Length of time in which bug has been known to occur

WE'VE NEVER HAD MUSTARD GAS!

#### Server revision

WE MAY NEVER KNOW

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Orangerush** [comment]
Holy shit you stole my idea. REPORTED

**Comment by Probe1** [comment]
I GUESS ITS A RACE TO SEE WHO CODES IT FIRST NOW

**Comment by kol1th** [comment]
Did you know if you bite a borg, it makes mustard gas?

**Comment by Shadowmech88** [comment]
Would there be a way to make mustard gas spawn every time someone does something that causes a runtime error?

**Comment by Probe1** [comment]
Last round Aurx gibbed himself and it caused a runtime that was inexplicable to read and I want this.

**Comment by Aurx** [comment]
Then there's an issue with gibself as a borg or gibself as a MMI'd brain.

**Comment by ghost** [comment]
Please don't code this, it makes mustard gas.

**Comment by ComicIronic** [comment]
Polyacid smoke grenade you chump.

**Comment by Probe1** [comment]
XGM port.. which is woefully far from completion and needs a lot of work.

**Comment by ComicIronic** [comment]
Remember that we tried gas datums and the server tanked.

**Comment by Exxion** [comment]
Because you didn't do it properly

**Comment by IratePirate** [comment]
First time i've seen Wilfred Owen in a github thread tbh.

**Comment by Probe1** [comment]
WYCI actually exists but we don't have the gas datums to handle it.

**Comment by Shadowmech88** [comment]
>exists but we don't have the gas datums to handle it

How? Why would someone add it without adding the modifications needed to make use of it?

**Comment by PJB3005** [comment]
Just saying but with gas datums the entire room would flood instantly with the gas which is almost certainly not what you want either.

**Comment by Probe1** [comment]
I SEE THAT SNEAKY EDIT PJB
