### ISSUE TITLE
Bound object can be used to pick up items through cameras and off z-level

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13127]
So for example if you take empowered bound object, then look at the thunderdome through the entertainment monitor cameras, then port out the blastwalls, you can see into the weapons storage and snag yourself a 150 force 25 throwforce weapon or snazzy double eblade.

Can also grab anything going on in the thunderdome if a min is testing things

**Comment by Shadowmech88** [comment]
Stealing objects through cameras is cool.
I think the spell should just specifically exclude items on Z-level 2, like what was done for the subspace tunneler.
