### ISSUE TITLE
the KEEPER module is an actual module on box centcomm

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#13128]
I just fixed two bugs related to it in my PR but it doesn't even let you use it on an upload in the first place.
So why is it even at central? What is the purpose of it existing at all?

related snippet
```DM
/obj/item/weapon/aiModule/keeper/validate(var/datum/ai_laws/laws, var/atom/target, var/mob/sender)
	..()
	to_chat(sender, "<span class='warning'>How the fuck did you get this?</span>")
	return 0
```

**Comment by Ephx1** [comment]
Fairly certain there's a spawn-only MoMMI law uploader console.

**Comment by Shadowmech88** [comment]
I wasn't able to find a MoMMI console in the machinery spawn menu, but does it matter regardless? That area of Centcomm is intended to be admin-only, after all.
