### ISSUE TITLE
Xenoarch Artefacts can crash admin's VV

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#13132]
#### Description of issue
Kavlax and Kuranon reported their VV crashing when looking at one of my artefacts.

#### Difference between expected and actual behavior
**Expected**
* Xenoarch metaclub badmins let me know what it does.

**Actual**
* Admins get rekt and I don't know what my meme artefact does on a 15 minute round.

#### Steps to reproduce 
* Find artefact.
* VV it.
* Hope it was one of the bugged artefacts.

#### Specific information for locating

* Could be due to https://github.com/d3athrow/vgstation13/pull/12715

#### Length of time in which bug has been known to occur

Since 4741e677dc364f9d5d9825a371f3a7d96856fc58 .

#### Server revision

4741e677dc364f9d5d9825a371f3a7d96856fc58 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
This is a BYOND bug and I believe it's to do with the sending of the icon preview. Making that preview use `bicon` would solve this issue.

For reference I believe Paradise fixed this.

**Comment by Kurfursten** [comment]
@Exxion haven't sen this ever and I VV artifacts a lot

**Comment by Exxion** [comment]
Reopen if it happens again
Or just open a new one
