### ISSUE TITLE
virus samples and machines

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13135]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
every time the analyzed sample is mutaded the machines adds a "OUTDATED:" to the description if you mutate it multiple times it turns to OUTDATED : OUTDATED : OUTDATED : OUTDATED : GNAv2 based virus lifeform - stamm #5437, #5437

>What you expected to happen
only 1 OUTDATED: added to the desciption

>What actually happened
 OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED:  OUTDATED: 

>Steps to reproduce if possible
mutate a virus with the machine multiple times

**Comment by Probe1** [comment]
@despotate
