### ISSUE TITLE
Bound Object can steal stuff from centcomms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13130]
(WEB REPORT BY: harsetheef REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
As a wizard with bound object with an extra point in strength, you can steal centcomm equipment (specifically the high force eaxe and eswords) thru the cameras to centcomm on station.

>What you expected to happen
To not be able to steal centcomm stuff.

>What actually happened
Murdered the station with eaxes and eswords.

>Steps to reproduce if possible
be a wizard, bind objects through the arena cameras, specifically the team waiting area airlocks and the weapons.

**Comment by kol1th** [comment]
#13127
