### ISSUE TITLE
Xenoarch specific antag options

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#13139]
YMMV but from a few antag xenoarch games it seems almost impossible to get something decent to work with due RNGesus only wanting to give you the station wide death face melting artefacts when you're non antag, xenoarch has huge potential to be a **FUN** antag gimmick yet most of the time all 8~ artefacts on the roid are shit.

I'll program it myself but I'm looking for some discussion/potential ideas on the change, I can see why xenoarch is neat in that sometimes you get real neat shit but you have to sift through the trash etc.

I feel xenoarch needs this as it's completely rng and that large artefacts are a finite resource, they are hard enough to get and it's even harder to get a good combo while you have antag.

Here's a few of the ideas I have so far:
* Emagging/Traitor item that let you see the effects and triggers straight up, to speed up the process
* Emagging/Traitor item that lets you modify an artefact's effect/triggers
* Ano scanner being a job specific item for scientist traitors

**Comment by Probe1** [comment]
Fuck no to the last one.

Don't get me wrong I think the Ano should be in the game somehow but that's just all wrong to make it an antagonist item.

**Comment by Kurfursten** [comment]
I think in general people have shied away from offering science any job specific tools because they get

>Combat mechs
>Weapons from protolathe
>Bombs
>Slime army
>Gold core spawning
>Golem slaves
>As many borers as there are willing ghosts
>Robotics Console + ability to build any computer/machine (incl. security cameras)
>Artifacts
>Teleporting into room of plasma / into the singularity

**Comment by BobdaBiscuit** [comment]
I feel every department has a ton choice really.

And is there something wrong with giving antags options that stray away from the old murderbone/singuloose/bombings that we've come to know and love.

**Comment by ComicIronic** [comment]
Encouraging Xenoarch antags also encourages antags that spend most of the round doing nothing and defending it because they were looking on the roid.

**Comment by BobdaBiscuit** [comment]
The reason I made this was to see if exactly that can be prevented for people who actually want to antagonise with xenoarch shit who can't.

The issue is that people who want to do a xenoarch gimmick will be going on the roid anyway, and might end up being forced to spend the whole round there in the hopes of getting some decent material to work with, the idea here is to speed up that process so they can get back on station and start removing kebab.
