### ISSUE TITLE
2 viruses with the same name but 2 different verosity + disease analyzer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13137]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
if 2 viruses have the same name but different small stats when you put them in the disease analyzer and print the paper it ll print 2 papers of the 2 viruses

>What you expected to happen
1 paper

>What actually happened
2 papers

>Steps to reproduce if possible

have 2 viruses with slight different stats but same synthoms and name 
but in the analyzer
print
2 papers istead of 1

**Comment by despotate** [comment]
I'm tempted to just remove paper printouts entirely to fix this

FUCK paper

**Comment by Probe1** [comment]
nein.  they are useful.

**Comment by despotate** [comment]
By the way this bug can't be fixed unless we rework virus """"""""unique"""""""IDs (which are just random numbers from 1-9999 that don't even check if other viruses already exist of those numbers) and make them change for minor mutations.

This bug also extends to ejecting a virus dish when there are multiple of the same name; you end up ejecting all of them.

```
	if(href_list["eject"])
		for(var/obj/item/weapon/virusdish/O in src.contents)
			if("[O.virus2.uniqueID]" == href_list["name"])
				O.forceMove(src.loc)
				if(toscan["O"])
					toscan -= O
		src.updateUsrDialog()
	else if(href_list["print"])
		for(var/obj/item/weapon/virusdish/O in src.contents)
			if("[O.virus2.uniqueID]" == href_list["name"])
				PrintPaper(O)
```
