### ISSUE TITLE
New Player Options New Player Options

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13144]
![dreamseeker_2016-12-28_16-13-18](https://cloud.githubusercontent.com/assets/6526157/21529489/970a35b0-cd18-11e6-8312-40bc5ae2031d.png)

**Comment by Probe1** [comment]
Yes that annoys me as well.  Just not enough to do anything.

**Comment by despotate** [comment]
You have decLared ready.
