### ISSUE TITLE
The PDA messaging server should be upgradeable, and block spam when upgraded.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13147]

**Comment by BobdaBiscuit** [comment]
If no one else is working on this already I'll shit something together tomorrow.

**Comment by Ephx1** [comment]
I like how this request exists, it shows how little people use the PDA store.

**Comment by Probe1** [comment]
we already have it as @Ephx1 said.

**Comment by PJB3005** [comment]
I feel stupid now.

**Comment by Ephx1** [comment]
I wouldn't mind it as a sort of upgrade, but it's surprising how unused the PDA store goes when it has a few good things.
Actually it's probably unused because of the scarce few things.

**Comment by PJB3005** [comment]
Good thing those PDA are worth playing.

**Comment by Probe1** [comment]
integrate the pda machine into something else.

I use those PDA games though.  That neopets one is fuckin siiiiick

**Comment by Ephx1** [comment]
Ehmm, maybe into holomaps? They're pretty scattered throughout the station.
