### ISSUE TITLE
Supermatter can't be eaten by a singulo if it has been modified by a multitool menu.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13142]
The issue is because if `fingerprintshidden` isn't `null` it'll try to add a list to a string, resulting in a runtime:

![](http://i.imgur.com/sIdr24A.png)

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/supermatter/supermatter.dm#L136

**Comment by Probe1** [comment]
[IT'S NOT LOOSE]

**Comment by Zth--** [comment]
Still a thing?

**Comment by gbasood** [comment]
i'd assume yes

**Comment by ghost** [comment]
I can't seem to be able to reproduce this

**Comment by PJB3005** [comment]
Nah definitely still happens.

Only happens when you use a singulo though, and the touching needs to be multitool menu.
