### ISSUE TITLE
stange anti-british bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13158]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
writing a message with the pound sign (£) breaks it and makes it unable to be sent (for chat + ooc) when used on ahelp it makes the bwoink sound but its invisible for the receiver http://puu.sh/t4Tug/b79ebe81a3.png

>What you expected to happen
be able to use £

>What actually happened
racism against british people

>Steps to reproduce if possible
write £ on chat 
try send message
 get nothing

i blame ira for this

**Comment by Exxion** [comment]
All special characters break it
Blame BYOND

**Comment by mph55** [comment]
You could remove the double url_encode in browserOutput.dm so issues like those and the Hécate are fixed, it's not like UTF-8 is used outside of the screaming russians

**Comment by Exxion** [comment]
Goonchat ALWAYS uses UTF-8
The problem is that BYOND doesn't.

**Comment by PJB3005** [comment]
@mph55 is correct here.

That'd fix it, but only for the Windows-1252 range.

**Comment by mph55** [comment]
Goonchat is IE and BYOND is Windows 1252 so it should be able to render £ at all times. It fucks up when £ is double encoded. 

%a3 is £ encoded, %25a3 is £ double encoded, if you try and paste %25a3 into OOC it'll break while %a3 will show £ properly.

**Comment by PJB3005** [comment]
No the issue is that anything above 127 is different between UTF-8 and Windows-1252, so the Javascript client side throws a Unicode Decode Error.

I would've already fixed this if Javascript weren't a shit language and actually allowed you to specify the encoding to use when decoding.

**Comment by PJB3005** [comment]
Like, my best idea would be to catch the `UnicodeDecodeError` and then use a regex to turn the encoded Windows-1252 bytes that aren't valid UTF-8 into UTF-8.

**Comment by ghost** [comment]
Why fix this, the Brits deserve it

**Comment by Wizardcrying** [comment]
@DrCelt stop shitposting.

**Comment by IratePirate** [comment]
You people make me sick.

**Comment by ReindH** [comment]
Of course there are no british, it's the future!

**Comment by Shadowmech88** [comment]
This no longer seems to be the case.
![image](https://user-images.githubusercontent.com/3991927/47408970-df4e9b80-d726-11e8-9c61-344e5430e39d.png)

**Comment by DamianX** [comment]
But did you try it with 2 clients? Sounds like the issue is when they use two different encodings.

**Comment by PJB3005** [comment]
Nah. This is fixed.

**Comment by Exxion** [comment]
This was the exact issue libvg was originally created to fix
