### ISSUE TITLE
Telecomms Machinery Stops Taking Damage From Heat After 90°C.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13157]
This is the code that causes a telecomms machine to get damaged:
```dm
/obj/machinery/telecomms/proc/checkheat()
	// Checks heat from the environment and applies any integrity damage
	var/datum/gas_mixture/environment = loc.return_air()
	switch(environment.temperature)
		if(T0C to (T20C + 20))
			integrity = Clamp(integrity, 0, 100)
		if((T20C + 20) to (T0C + 70))
			integrity = max(0, integrity - 1)
	if(delay)
		delay--
	else
		// If the machine is on, ready to produce heat, and has positive traffic, genn some heat
		if(on && traffic > 0)
			produce_heat(heatgen)
			delay = initial(delay)
```

It seems to be quite weird about how integrity is lost under heat.

The machine will only take damage from heat between 40°C and 90°C, above that and it won't take any damage at all.

**Comment by Intigracy** [comment]
I think they intended to do an else if to make it take more damage above that but forgot.

**Comment by Exxion** [comment]
Looks to me like it stops at 70

**Comment by Shadowmech88** [comment]
So you could run telecomms in a burn chamber instead of a cooling chamber?

**Comment by PJB3005** [comment]
@Shadowmech88 yes.
