### ISSUE TITLE
Double agents have objectives to kill and protect the same person

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#13151]
I fixed the issue before I could take a screenshot, but someone today rolled double agent and had an objective to protect someone AND an objective to kill the SAME person.

**Comment by Probe1** [comment]
for fucks sake

**Comment by Intigracy** [comment]
Ez fix

**Comment by Kurfursten** [comment]
>In order to protect him, he must be killed

Have we considered that the syndicate objective generation proc may be just an average silicon player?

**Comment by ghost** [comment]
Objectivizer is rogue, blow the nuke ops

**Comment by jknpj** [comment]
>		//Make sure that the target exists, and that we don't already have an objective to protect the target
Protect target checks if you're already protecting it but not if you already have to kill it

**Comment by DamianX** [comment]
Double agents no longer exists as a gamemode.
