### ISSUE TITLE
Get rid of the ugly multitool menu CSS

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13168]
Seriously jesus fuck it's such a chore.

Of course the styling would still be unique to the multitool menus once changed, but jesus.

**Comment by Wizardcrying** [comment]
>Seriously jesus fuck it's such a chore.

Do you mean working with the multitool menu?

**Comment by PJB3005** [comment]
Working with it is fine.

**Comment by 9600bauds** [comment]
provide examples

**Comment by PJB3005** [comment]
Of?

**Comment by 9600bauds** [comment]
The multitool CSS

I can't remember what it looks like and have no idea what it could be changed to if I can't remember it in the first place

**Comment by PJB3005** [comment]
![](http://ss13.moe/wiki/images/thumb/f/f9/MultiTool.PNG/300px-MultiTool.PNG)
