### ISSUE TITLE
We need a "mental interface" analogue for severed heads

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13164]
**Somebody drops a locker with thee husked corpses at Medbay's front door.** Two of the three husked players have became diona, only one of them is still revivable.

You take one of the corpses, put it in the cloner and scan it. The ghost of the player gets a loud BWOINK and gets told to rejoin their corpse if they want to show that they're still active.
You get one of three very clear messages: "The ghost is there and in his body", "The ghost is missing, cannot revive", or "The ghost is there but is a faggot and doesn't want to rejoin his body".
Using this information, you can quickly discard the two unrecoverable husks and take the third one to give them a head transplant. Everyone is happy.

But:

**Somebody drops a locker with thee severed heads at Medbay's front door.** Two of the three decapitated players have became diona, only one of them is still revivable.

You take one of the heads. You cut off a monkeyman's head. Retractor. Fixovein. Hemostat. Cautery. Reattach head. Go clone/defib them. _Oh look there was no ghost in this head._
You take another head. You cut off the same monkeyman's head. Retractor. Fixovein. Hemostat. Cautery. Reattach head. Go clone/defib them. _Oh look there was no ghost in this head either._
You take the last head. You cut off the same monkeyman's head. Retractor. Fixovein. Hemostat. Cautery. Reattach head. Go clone/defib them. _Oh look, in the time it took you to perform THREE head transplants, the last player became a diona, and probably didn't even realize his head had been rescued._

Medbay could really use some device to perform the "mental interface query" with severed heads/brains. They don't even need to be able to talk, just a YES/NO to the "are you still there?" question. Otherwise it just leads to a lot of wasted time.

**Comment by Probe1** [comment]
_The luster in their eyes is gone_

**Comment by 9600bauds** [comment]
Problem is that if you do it by just examination it's not quite the same thing as the mental interface dance, in the latter the ghost actually gets a prompt to rejoin their body. Nobody actually stays in their head after they get decapitated.

**Comment by NigglyWiggly** [comment]
Part of the reason nobody stays in their head after being decapitated is because you cannot interact with deadchat while in a severed head.
I agree that we could use something like this.

**Comment by kol1th** [comment]
>You take one of the corpses, put it in the cloner and scan it. The ghost of the player gets a loud BWOINK and gets told to rejoin their corpse if they want to show that they're still active.

Husked as in THE S U C C from a changeling right?

**Comment by 9600bauds** [comment]
Husking from lasers doesn't even exist anyways

They just go pale but it doesn't make them uncloneable

**Comment by Sprok0** [comment]
They're still husked, which is separate from being given the NOCLONE mutation, which ling absorbing does.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is fixed

**Comment by nuklearcellphoneg** [comment]
So it is..... him.......!

**Comment by Exxion** [comment]
???
