### ISSUE TITLE
Doing What Changeling Tried to Do but Better

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#13175]
Changeling was inspired by The Thing, but it does a very poor job of capturing The Thing's atmosphere. Reasons being:
* It is mildly difficult to absorb people without them shouting for help via radio, you being seen, or their husk being discovered.
* There is very little incentive to bother impersonating those you absorb.
What this leads to is, instead of a constant feeling of suspense and distrusting your allies, it becomes a monster hunt similar to how vampires are dealt with.

I think we should brainstorm a gametype meant to be what changeling initially tried to be. My ideas are:
* Single antagonist, similar to wizard.
* Can absorb people very quickly, within one or two seconds.
* Can activate horror form at any time.
* Horror form makes them extremely vunerable to burn damage as well as increasing their speed and damage.
* Must be in horror form to absorb victims.
* Upon absorbing a victim, their body disappears, and you take their identity until you trigger horror form again.
* No genome count or upgrade path, absorptions are incentivized by the player dying if they go too long without feeding.

Thoughts?

**Comment by kol1th** [comment]
That's kind of similar to Goon's ling, from my very small amount of experience with it. They can go horror form temporarily, and absorb people from there as well as overpower them with sheer strength.

>extremely vunerable to burn damage

Maybe not. I'd wager burn damage is the most common form of damage on the station. Maybe fires and flamethrowers, rather than something like a lit welder or an energy gun.

>increasing their speed and damage. 

Definitely.

>Must be in horror form to absorb victims.

Maybe not, but have it be the faster (one to two second) absorb in the alternate form.

>Upon absorbing a victim, their body disappears, and you take their identity until you trigger horror form again.

This is fantastic. Of course, with the option to change to anyone they absorb. But automatically changing is an idea I quite like.

>No genome count or upgrade path, absorptions are incentivized by the player dying if they go too long without feeding.

I like this. Maybe a system like having everything unlocked at roundstart, but requiring DNA or some other point system to use certain abilities/transform to horror, with horror draining every few seconds you have it active. 


On another note, something you didn't mention that TG has, is a "last resort" option for when you run out of options. From what I recall, it gibs your old body, and you turn into a meat slug kind of thing, and you can crawl through vents, and take over a corpse if you find one. I quite like that idea and I'd be all for porting it.

**Comment by Shaska-** [comment]
>absorptions are incentivized by the player dying if they go too long without feeding.
Not sure that's a good idea. People may start locking up changeling suspects for extended periods, and see if any of them starts collapsing, which wouldn't really be particularly fun for anyone involved.

**Comment by Shadowmech88** [comment]
>People may start locking up changeling suspects for extended periods, and see if any of them starts collapsing

The player would know that they need to feed well before the hunger kills them, and could trigger their horror form to hopefully escape and regroup.

**Comment by Blithering** [comment]
I've been thinking about a changeling rework for a while as well, and I reckon lings could do with having a resource, named genetic stability or something, which is decreased when using ling abilities, and makes your disguise less effective. For example if you chose to have something minor like hallucination sting, you'd have a minor hit to stability and on autopsy there'd be a note saying about unusual bone structure, whereas a more powerful ability like rapid regeneration would cause a bigger dip and cause body scanners to freak out. Stability would be regained by absorbing and assuming a new identity, which would also refund all evolution points, setting you back at square one, but with more points to work with.
Players could then choose to either play it stealthy and safe with relatively few upgrades, go for a the thing style method of revealing themselves only to assume a new identity and slip back into the crowd or go balls to the wall and rely on their abilities to cover for their obvious inhumanity.
Horror form from start would also be a cool idea, have the world announcement removed so it becomes more of an asset for overpowering isolated people, and have it destroy the identity they were using before they transformed, so they either need to have a spare identity in the gene bank or kill someone to revert. There also could be a second tier of horror form, (partially sprited already actually) which has the world announcement and enhanced abilities so there's still the 'fuck you all look how many genomes I have' factor.
![horror](https://cloud.githubusercontent.com/assets/15067109/21565549/62ac346a-ce91-11e6-8d6d-05edd47f75a5.png)
Picture to make the wall of text more interesting.

**Comment by AI-Is-Rogue** [comment]
@Blithering, sprite reminds me of a Necromorph, I like it, I also think your suggestion sounds better than dying if you don't kill people, allows the changeling more flexibility.

**Comment by Ephx1** [comment]
> There is very little incentive to bother impersonating those you absorb.

Will never change in our playerbase due to people seeing others as mere vending machines that do jobs and occasionally get pissy at you. Doubly so when most characters don't even have a personality.

**Comment by Shadowmech88** [comment]
>Will never change in our playerbase

Part of the goal of my suggestions is to get that to change by *forcing* the player to take on the appearance of whoever they last absorbed.

**Comment by Ephx1** [comment]
Ah I thought you mean "impersonate" as in act like, not just take the appearance of. I've seen lings transform, and even normal people with UIs transform, but they never bother to even vaguely act like the original and indeed no one notices when their coworker suddenly stops talking and starts being suspicious as shit.

**Comment by Intigracy** [comment]
We could also give them the ability to make a new  thing.

The one from the movie was clearly in two places at once.

**Comment by Ephx1** [comment]
How would that work exactly? Two players or a backup infection left in someone? The suggestions here also imply no unlocking abilities via absorption.

**Comment by ComicIronic** [comment]
I think two players wouldn't be a bad idea for what is essentially an assassination gamemode, but it raises the issue of wanting to be succ'd for the antag status and powers. Splitting would certainly be closer to the Thing idea and bringing more antags into the fold might make lings actually do something for once with the rampup.

**Comment by Blithering** [comment]
Maybe make some sort of cocoon out of the husk of the victim that can be jumped to in the event the original body gets destroyed?

**Comment by Intigracy** [comment]
I was thinking splitting, yeah.

I can throw together a neat little flow chart when I get home on how I think it'd work.

**Comment by ghost** [comment]
I remember the thread discussing this awhile ago, and there was one idea I liked a lot, the ability to switch between horror form and normal form should just use our current horror sprite, but through evolution points they should be able to unlock some type of "true" horror form (using the sprite blithering posted) which would function similar to our current horror form.

**Comment by Riekland** [comment]
We already have norris, don't we?
We could make the splitting apart depend on what limbs you have, so if nothing's cut off you can drop one or both arms, one or both legs, the head, or a mix
then you can have them all act the same, but make the ones the player doesn't enter just skitter around real fast and try and latch on people
probably make them do it relatively slowly, and give the player controlled bit a sting or something so it can get back onto someone
