### ISSUE TITLE
Attacking as a mob with no attack damage produces a "miss" sound

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13174]
@unid15 's combat dealio probably

So if you take a mouse or a cat for example and try to attack someone you get
```The mouse (67) has missed the unknown!```

since their damage lower and upper are both zero. Regular simple animals are unaffected

**Comment by ghost** [comment]
The fix is to give mice 0.1 damage each bite :^)

**Comment by jknpj** [comment]
mouses were a mistake

**Comment by Probe1** [comment]
Thanks for reminding me to code a mommi fabricator subtype that has adjustable outputs so I can fill the round with simple mobs _without_ all the effort.
