### ISSUE TITLE
How to make the hypospray more useful

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13172]
Sadly the hypospray doesn't see a lot of use for actually treating people with, and this is because it isn't flexible enough. Flexibility is something that people have suggested before, I've heard silly suggestions like advanced CMO gloves that makes pillfeeding instaneous and such, I think I've came up with something better:

1 - Allow you to crush pills directly into the hypospray's container.
2 - Clicking a pill with the hypospray in hand instantly reverse-crushes it into the hypospray.
And so, if the CMO needs to shove 3 different pills down some guy's throat, he can click-click-click them with the hypospray and then just prick the guy a lot, if needed. Or prick a lot of different people for things like a radstorm.
And finally:
3 - Steal the idea from the engineer's fuel can and give the hypospray 2 different reagent containers, which can be switched by using it in hand.
The idea is that no matter what you do, some shmuck will put chloral in his hypo. This will, at the very least, make it so that he can't have JUST chloral in there. He still has the flexibility to shove a bicaridine pill in there and prick away.

**Comment by Intigracy** [comment]
You mean doesn't have to, not can't.

There's still gonna be shitters that doublechloral.

**Comment by Allspice** [comment]
You can already crush pills into hypos. Got changed 3-6 months ago I think, or that's about when I noticed it.

**Comment by Shadowmech88** [comment]
Unfortunately there are, at the moment, just not a lot of uses for autoinjector functionality in general besides administering chemicals to people against their will.

**Comment by Blithering** [comment]
Multiple reservoirs would be cool, the cyborg hypospray already can switch between three healing chems too so why let the robots have all the fun?

**Comment by jakmak3** [comment]
As it stands now its not a issue with the hypo but instead an issue with chems itself. The hypo has a chem storage of 30u and up to 50u of any chem can be administered by pill with only a little more work. 5u chem inject unless if its medical nanobots is strait up not worth it for healing purposes. Still with that it is the perfect close range chemical weapon applicator with a refillable reservoir.
