### ISSUE TITLE
Derelict MoMMis can teleport to the station when inside a cage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13187]
(WEB REPORT BY: archsunder REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
fcaa64cba57915006c8c3fcdf22ea1e28c73bbbd 

>General description of the issue
BROKE THE CONDITIONING and managed to teleport to the carbon station whilst inside a plasteel cage

>What you expected to happen
"You can't use this teleporter"

>What actually happened
Appeared on carbon station, beeped and pinged at some carbons, then teleported home

>Steps to reproduce if possible

**Comment by Probe1** [comment]
why don't we just delete them if they leave the derelict z level instead of this hodge podge of protection
