### ISSUE TITLE
Telecomms and the Laws of Thermodynamics.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13184]
So I'm working of a touch up of telecomms, and while working on the code for heating, I found quite an interesting issue.

Telecomms code heats the environment by adding 40 KJ of energy every 5 ticks.
However, the machinery doesn't make up for this and actually uses a fraction of the energy outputted by the heating.
The problem is, when I went and made tcomms use the realistic buttloads of power it probably should be using...

![](http://i.imgur.com/aUcFkIn.png)

Telecomms becomes the biggest power user on the station and would cut the setup time engineering has down to unreasonable numbers and might even make the singularity flat out too weak.

So I'm honestly not quite sure what to do here. I want to make them use the correct amount of energy, but at the same time it's flat out unreasonable without rebalancing everything related to energy and power.

**EDIT:** Actually I miscalculated. The energy draw is only half that. Still ridiculous.

**EDIT 2:** Actually it's even less bad than that because it only generates heat if there's traffic going through, but this code seems bugged either way?

**Comment by Probe1** [comment]
Oh boy.

Well the only thing I can think is don't be realistic.  Lower it to 50kW

**Comment by PJB3005** [comment]
@Probe1 it already isn't realistic.

Also I fucked up my math badly because this code's such a mess, but the power usage would still be relatively high compared to what we have now.

**Comment by PJB3005** [comment]
Actually after running a bunch of tests involving assembly frames I think I came to the conclusion that it'll be fine.

If it isn't we can always revert the change I suppose.

**Comment by Exxion** [comment]
The singularity engine already violates conservation of energy
I wouldn't worry about physical realism

**Comment by ComicIronic** [comment]
The singulo is not a closed system - it draws energy from somewhere else.

**Comment by Exxion** [comment]
Yeah
The PA
Which is powered by... the singulo.

**Comment by ComicIronic** [comment]
No, another part of space.

**Comment by Shadowmech88** [comment]
What if use of telecomms was a goal of Engineering instead of a guarantee?

**Comment by PJB3005** [comment]
The energy source is plasma.

Plasma gets consumed by the collectors.

**Comment by Exxion** [comment]
Alright, fair enough. Forgot about that.
But I don't think anyone would claim the singulo is scientifically accurate in general.

**Comment by kol1th** [comment]
@Shadowmech88 Then if nobody knows how to set it up, you don't get comms. And if they don't set that up, chances are power isn't set up. Which means comms won't work anyways.

**Comment by Shadowmech88** [comment]
>Then if nobody knows how to set it up, you don't get comms. And if they don't set that up, chances are power isn't set up

My implication was that we change Telecomms to use the large amounts of power that PJB calculated they'd logically have to based on their heat output, so that Engineering has to produce a large power output in order for Telecomms to get enough power to function.

They wouldn't have to set up Telecomms itself.
