### ISSUE TITLE
new "combat code" bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13185]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
clicking on people as a mouse gives a message + a disarm sound

>What you expected to happen
no sounds no messages

>What actually happened
The mouse (618) has missed Landantyme the Toad (as Slate Slabrock)!The mouse (618) has missed Landantyme the Toad (as Slate Slabrock)!The mouse (618) has missed Landantyme the Toad (as Slate Slabrock)!

>Steps to reproduce if possible
be a mouse click on people

**Comment by Exxion** [comment]
#13174
