### ISSUE TITLE
Suggestion: Add rechargers to away missions

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#13197]
I don't see how this could hurt, since away missions tend to be difficult enough as it is. At the very least, it would simplify things a little bit by not making it necessary to set up a protolathe for bullet printing purposes.

**Comment by Probe1** [comment]
List out the ones you think need them.  Some like Tomb are really sizeable and walking back to recharge in security is a long trip.  Others are pretty small.

**Comment by icantthinkofanameritenow** [comment]
Tomb of Rafid and Wild West come to mind; possibly that one where the mindflayer shows up though it might have one already.
