### ISSUE TITLE
the massive eclair is missing the spirte

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13199]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
the massive eclair has no sprite

>What you expected to happen
big sprite

>What actually happened
no sprite

>Steps to reproduce if possible
make a massive eclair
its invisible

**Comment by Probe1** [comment]
Closed by https://github.com/d3athrow/vgstation13/pull/13193
