### ISSUE TITLE
Please revert the PDA alt and ctlr click shortcuts

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#13194]
Or at least allow the player to choose between the shortcut set-ups.

It bothers me a lot and I don't see the point of it being swapped over some fabled "standardization" that's not explained.
I've been told to express my opinions by PJB.

**Comment by PJB3005** [comment]
> that's not explained.

m8

Most actions that have shortcuts are under alt. It's extremely unintuitive that the PDA is the exception to this rule.

**Comment by Probe1** [comment]
I think peoples problem is the one that they are consciously familiar with is the PDA.

**Comment by 9600bauds** [comment]
Speedclone 15 people in one shift and you'll get used to the new shortcuts real fast

**Comment by 9600bauds** [comment]
In seriousness though, switching the shortcuts, giving it a week for people to get used or half-used to them and THEN switching them again would get more people mad than just switching them once

**Comment by kol1th** [comment]
Documentation where

**Comment by 9600bauds** [comment]
In the starters guide that is in the front page of the wiki and the general OP
http://ss13.moe/wiki/index.php/Shortcuts

**Comment by Iamgoofball** [comment]
😭

**Comment by Gringonius** [comment]
> Most actions that have shortcuts are under alt. It's extremely unintuitive that the PDA is the exception to this rule.

I'm not sure if I follow the logic, alt removed the pen instead before the change, the shortcut was always in use and I believe that ctlr is more comfortable to use.

> In seriousness though, switching the shortcuts, giving it a week for people to get used or half-used to them and THEN switching them again would get more people mad than just switching them once

A week ago I was told to make an issue or even PR to revert it because it was apparently unpopular, then told soon after that wanting the change reverted was "knee-jerk shitposting", now just a week after when I actually open this issue I'm being told it's been that way too long and shouldn't be undone because of that. I'm puzzled by this.

**Comment by DamianX** [comment]
Are we done discussing?

**Comment by Exxion** [comment]
>last comment not far from two years ago

I'm going to say yes
