### ISSUE TITLE
Suggestion: make rechargers scannable by the device analyzer

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#13196]
It would help drastically in blob rounds, not to mention in larger away missions where you might not have time to waste running back and forth to the recharger in the gateway. Plus, allowing the mechanic to make a machine the protolathe can't create should give more people a reason to play them.

**Comment by Probe1** [comment]
Why not just add rechargers to away missions instead of opening a huge balance quandary?

**Comment by icantthinkofanameritenow** [comment]
That works too.

**Comment by Probe1** [comment]
It was Tomb right?

**Comment by icantthinkofanameritenow** [comment]
Yes, though I could imagine it being a factor on other long away missions like Wild West as well. Set up another issue, use that instead. #13197
