### ISSUE TITLE
EVA suits don't have the plasmaguard flag except for CE and Atmos suits.

### ISSUE THREAD

**Issue by liltiptop** [d3athrow/vgstation13#13206]
Wear an atmos suit or a CE suit and plasma does nothing to you.
Wear any other suit and plasma somehow magically enters your space proof suit and fucks with you.
This may have been talked about a while ago, but it still exists.

**Comment by Shadowmech88** [comment]
This was talked about a while ago.
One of the ideas floated to change this was that spaceproof suits without plasmaguard would still become contaminated themselves, but would prevent all your other clothing like your jumpsuit and boots and gloves from becoming contaminated.

**Comment by icantthinkofanameritenow** [comment]
That's been intentional for ages, it's because otherwise atmos hardsuits would have no reason to exist.

**Comment by Shadowmech88** [comment]
What about their heat immunity?

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88 That usually only comes into play during plasma fires, and arguably that just finishes off the people the plasma didn't kill outright. 

On an unrelated note, in the Tomb of Rafid i was set on fire despite wearing the gold atmos hardsuit, so it's clearly not actually fireproof.

**Comment by Sprok0** [comment]
Flamethrowers just ignore fire protection from suits, and the jackels/fire traps use the same type of projectile.

**Comment by icantthinkofanameritenow** [comment]
Do they? That would explain it, even though that doesn't make much sense.

**Comment by Exxion** [comment]
Flamethrowers use the same projectile, in fact
