### ISSUE TITLE
attack text is past tense now

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13201]
In the past few days, something's happened that has made all attack text phrase itself as past tense

Problem is, a large amount of the mob attack text is present tense, as was standardized by @Intigracy a bit back.

Now, rather than

'The clown goblin honks at greyshit mcshirt'

It now comes out as

'The clown goblin has honks at greyshit mcshirt'

**Comment by Exxion** [comment]
What the fuck?

**Comment by Probe1** [comment]
@unid15

**Comment by Intigracy** [comment]
Je crie.
