### ISSUE TITLE
Smart laser guns should not be able to shoot in every direction while on someone.

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#13208]
>The pAI has full control, the master isn't a factor. **The pAI can even fire the gun while it's on the ground.**

And when in your master's belt or wherever else.
They should not be instant, always-usable personal defense turrets.
It's bullshit.
Get rid of it.
Thanks, @Shadowmech88.

**Comment by despotate** [comment]
Just played a round as a pAI in a gun. I'm assuming you're the detective I killed? I agree with limiting their ability to fire.

Also can't tell when you're in a gun or just in someone's pocket. This leads to many accidental misfires.

**Comment by Wizardcrying** [comment]
@despotate Yes.
"Okay." was the only response I had to getting destroyed by a changeling alarm in a gun.

**Comment by Shadowmech88** [comment]
Why did you vote positively on the PR if you didn't like what it entailed?

**Comment by jknpj** [comment]
@Shadowmech88 
because "I died pls nerf", but no seriously, bag gun is a bit too much but it's not THAT BAD as their ammo is a issue. Why not make they destroy damage/destroy the container they're firing from?

inb4 people start stuffing smartguns inside their bodies

**Comment by JustSumBody** [comment]
Quick someone draw a smart gun firing from inside someone's chest

**Comment by Probe1** [comment]
![wolfenstein-3d-](https://cloud.githubusercontent.com/assets/8550416/21581956/8d9f59f2-d014-11e6-8ba6-d2a84ea1d9e7.jpg)



MEIN LEBEN

**Comment by PJB3005** [comment]
It's a feature, the gun is based on the Smart Pistol MK5 from Titanfall:

![](http://vignette1.wikia.nocookie.net/titanfall/images/1/17/SmartPistolMK5.png/revision/latest/scale-to-width-down/270?cb=20140313010804)

**Comment by Ephx1** [comment]
> titanfall smart pistol

triggered

**Comment by Kitfox88** [comment]
![stroheimcyborg](https://cloud.githubusercontent.com/assets/16981475/21582620/be8037c6-d02d-11e6-901d-cee3f3da57f4.png)

**Comment by AutismSpider** [comment]
![smart guns](https://cloud.githubusercontent.com/assets/10268342/21599113/3be7e308-d12d-11e6-9ca7-af2e7b1639ef.jpg)

**Comment by icantthinkofanameritenow** [comment]
At the very least, I suggest making it so that the gun can only fire when on the ground or when held by someone. If they aren't visible in the game, they shouldn't be able to fire at anything. 

Additionally, a sight radius for the pAI would be advisable- they should be able to see no further than a normal human, so darkness would be able to significantly interfere with their effectiveness in the absence of a light source.

**Comment by Exxion** [comment]
Can pAIs see better than humans right now?

**Comment by icantthinkofanameritenow** [comment]
It's been some time since I last played a pAI, but if memory serves their sight is equivalent to a human's at the least. The important thing is that the basic concept needs limits so it doesn't let the pAI fire out potshots from a backpack hidden in a locker.

**Comment by MasterofNothing** [comment]
pAI + smartgun = complete bullshit. You're basically done for if you run into someone with that shit on him and you can't duck behind a wall or something. I have no idea why this was even added.

Thankfully, it doesn't get used too often, but when it does it's extremely overpowered.
