### ISSUE TITLE
Created grilles are showing as invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13204]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
1530fdfa12eb2348b02e451db2026392b199c7e2 

Seems that when a grille is created, its visibility is 0

And if somebody were to right click the turf it's on, select it from the turfs contents, and press delete, it does not delete.

**Comment by Exxion** [comment]
Oh god not this again

Sounds like it's getting `qdel`ed then moved back to the turf for some reason
(`qdel` sets  `invisibility` to 100 and you can't delete something that's already been deleted)

**Comment by Exxion** [comment]
I blame pooling

**Comment by Probe1** [comment]
>Oh god not this again
