### ISSUE TITLE
Zombies - Where to next?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13222]
Discussion issue for ideas for zombies

- [ ] Infection vector - ways for the zombies to be introduced into the round through normal, non admin abuse means
- [x] Clothing - rather than fighting naked corpses, have them inherit clothing during zombification that's dropped on gibbing
- [ ] Different variants
- [ ] Changes to how they work currently

**Comment by ghost** [comment]
OOC:  Dattinderbox:  exploding zombies 

Can easily be done. Maybe have them as a point at the end of the consumption branch, retexture the fat sprite, and on death they do a -1,2,4 with lubegibs

**Comment by DoctorMonkey** [comment]
Zombification as a virus symptom?

It'd be neat if someone who got zombiefied with armor on kept the resistances, making a tough zombie.

**Comment by ghost** [comment]
That sounds feasible, @despotate you're our resident virus man. How would you do a zombie virus?

**Comment by Shadowmech88** [comment]
Zombies with special abilities like in L4D.

**Comment by aceedex** [comment]
Id say allow crimson heads to bust down walls like the goliaths can

**Comment by ghost** [comment]
Crimson heads are the only zombie type that can bust through bolted doors, and are guaranteed to break doors open compared to the regular zombies 33% chance.

Perhaps have another zombie geared towards structure destruction and tanking damage?

**Comment by Kurfursten** [comment]
Zambies may have a """33%""" chance but you can spamclick the door as much as you like to guarantee it opens after ten seconds

**Comment by kol1th** [comment]
Maybe have player-controlled zombies that aren't just simple mobs, so you can dismember them and such, as well as crawling zombies or something of the likes if you cut their legs off. Maybe with an increased chance to dismember them with sharp objects, more chance the sharper the object.

**Comment by despotate** [comment]
To respond to Skullyton, I'm not really that familiar with BYOND or even SS13 itself (I've only been playing for around a third of a year) or quality coding in general but I guess if I wanted to just slap together a zombie virus real quick, I'd create an instance of a `disease` with only a stage 1 `zombification` effect that uses cumulative `count` comparisons to escalate:

- `count > 0`, some coughing
- `count > 5`, you start sloughing off flesh (probably just copy paste the necrosis code)
- `count > 15`, you lose ability to talk, walk slower, start getting massive internal organ damage, use a `spawn(60 SECONDS)` to turn the dude into a zombie if they haven't died by then, guess? in a regular programming language I'd just add a hook to whatever function gets called when a human mob dies to zombify them if they didn't die from anything weird, not sure if that's available in BYOND.

Though this approach brings some problems (cough, virus fooding your way into getting cured, spaceacillin), mostly a result of `disease` really not being general at all and acting only one very oddly specific, magic numbered way.

So really the proper way to do this would be to generalize `disease` (which is actually `virus` (which is actually much closer to bacteria)) into the absolute barest bone disease possible that has in it only what `effect` needs (just a log variable, I think) plus the global disease list (?) and then use `effect` however it wants. Probably stitch together a bunch of the stage 1s, necrosis, whatever, check if the mob's dead and reanimate them as a corpse.

Don't rely on me for anything but I'll try and spend some time sorting out the disease code.

**Comment by Shadowmech88** [comment]
What about a zombie virus that is completely asymptomatic, except your corpse turns into a zombie when you die?

**Comment by jknpj** [comment]
Might as well show the the infected as dead in medhud
