### ISSUE TITLE
Add a ghost option to hide other ghosts without toggling darkness

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13229]
I think someone said this would be possible with planes

**Comment by Probe1** [comment]
👌

**Comment by 9600bauds** [comment]
[When Celt Codes It]

**Comment by Exxion** [comment]
It would be possible with planes, but the ghosts would still be mouse opaque. Just invisible.

**Comment by 9600bauds** [comment]
Well, if you just slapped planes magic on top of the currently existing system, they would only be mouseopaque to other ghosts, right?

**Comment by Exxion** [comment]
Yes
