### ISSUE TITLE
Box still has a wreath rack in the theater backroom

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13226]
Honk

**Comment by Kurfursten** [comment]
I thought this was one of the easter eggs you were talking about when I saw it in the diff

**Comment by Probe1** [comment]
Oh no those are much more minor.  A single box of wreaths in a closet in maint, a santa hat in a locker.  Little stuff not an extra rack of shit.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/pull/13232
