### ISSUE TITLE
Admin IDs don't have Vox Outpost access

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13238]
https://www.youtube.com/watch?v=HHgxOXEQaFU

**Comment by ScrambledSteak** [comment]
No gods, no admins, only birds.

**Comment by Intigracy** [comment]
Instead of manually adding every access every time we add a new one we should just make an admin access for the card that has an exception in checking for access.

**Comment by jknpj** [comment]
How the fuck is admin bully real just qdel the airlocks and walk in

**Comment by Shadowmech88** [comment]
Or use right-click -> jump to turf.
