### ISSUE TITLE
Some Attack Text is Still Past Tense

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#13243]
![image](https://cloud.githubusercontent.com/assets/3991927/21603660/8f16bf2c-d164-11e6-817b-1b3794b9a94d.png)

**Comment by PJB3005** [comment]
> has punches

**Comment by Kitfox88** [comment]
cyka blyat jug

**Comment by ghost** [comment]
Best of it is, the russians have knives, they do slice damage, but they're punching you

**Comment by Intigracy** [comment]
Does this still happen? I can't find the code for it anywhere.

**Comment by CptWad** [comment]
I bet the knives are just in the wrong hand(s)
