### ISSUE TITLE
Should we de-list the RPD/RCD from the antag steal items?  I mean holy shit.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13248]
Under the definition of Grand Theft.

>The following items fall under this : All Mechs, Command-level IDs, the Captain's Antique Laser and Secure Armory weaponry, Hand Teleporters, the **RCD**, the **RPD**, the Stations Blueprints or a photo thereof, the Hypospray, Ablative Vests, the Pinpointer and Nuclear Authentication Disk and all Heads Jumpsuits.

Things that can be printed from autolathes, that aren't kept in secure lockers (or even especially secure areas), and generally cause mild to moderate concern shouldn't really be antag steal objectives.  Yes, RPDs are _incredibly dangerous._  But so are gygaxes and laser cannons which will only net you ten minutes in the brig.

There's a lot of good alternatives that have come up like the lawgiver and other new, rare items.

**Comment by ghost** [comment]
Powercreep from the autolathe. Autolathe nuked when?

**Comment by Kurfursten** [comment]
I think we should choose one of these two options, to maintain balance:

* Remove RCD/RPD from antag objectives
* Add all Head jumpsuits to Autolathe

**Comment by Probe1** [comment]
>antag objective discussion turns into autolathe buff in just two posts

I wouldn't have it any other way.

Also I'm thinking:

CEs belt:  Unique, awesome, will be missed
Lawgiver:  Unique-ish, awesome, will be missed, very dangerous

???

**Comment by Shadowmech88** [comment]
I think it'd be good to have the other head-unique items as objectives, like the hypospray is.

Although the Lawgiver may not work for an objective, considering it's unique and it can be destroyed simply from the wrong person trying to fire it.

Also what could be the item to steal from the RD?

**Comment by Sprok0** [comment]
Lamarr, clearly

**Comment by Probe1** [comment]
not even the RD cares about lamarr, and he can destroy it to make a hive hand can't he?

**Comment by 9600bauds** [comment]
The CE's belt is already an objective
Let's nuke jetpacks while we're at it

**Comment by 9600bauds** [comment]
Someone pointed out that the Lawgiver wouldn't really work because it gets deleted if anyone unauthorized tries to fire it

**Comment by Kurfursten** [comment]
Maybe allow jetpacks to stay, but make it specifically the Captain's Jetpack (it's an O2 jetpack, unlike the CO2 ones found in EVA or the N2 ones on the outpost)

**Comment by icantthinkofanameritenow** [comment]
@Kurfursten 
Good idea. The others are too easily acquired.

**Comment by jakmak3** [comment]
for the love of god remove jetpacks, RPD, and RCD. The RCD/RPD can be made with almost no work and in comparison to anything else is not at all dangerous and jetpacks can litterally be bought in a vending machine and fit inside a jetpack. These objects are disgustingly easy and should be outright removed

**Comment by 9600bauds** [comment]
You can still get oxygen jetpacks from Mining vending machines and I think in Meta, Sec EVA has them.

I considered the captain's flask since it's unique, but it's even lamer than a jumpsuit. Also considered the Chain of Command but we're getting into 2many captain's objectives and it's kinda lame too.

**Comment by Kurfursten** [comment]
Clearly the answer is to make more cool head of staff toys.

**Comment by jakmak3** [comment]
OK what if we steal TG's idea and in some head lockers/caps office/vault/somewhere important have fluff objects like top secret files and NT military starmaps or reasearch doccuments regarding plasma/supermatter/memes. Serve little to no purpose other than immhulsion and traitor steal objectives. Would make sense from a IC perspective.

**Comment by 9600bauds** [comment]
That's like

Jumpsuits that you can't wear

**Comment by 9600bauds** [comment]
Also, one of these days I'm coding the implant in the CMO's locker that gives them perma MedHUD

If you get it as an objective and the CMO already implanted it you have to forcibly remove it via surgery

**Comment by jakmak3** [comment]
from a balance and easiness of objective standpoint it is BUT from a RP perspective it is pretty interesting.
