### ISSUE TITLE
Special role preferences reset every time character main job preferences are changed.

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13247]
Title. Specifically on saving changes. Searched for previous issues but they were much more generic.

This _feels_ like an easy one line fix but I've gone through a bit of https://github.com/d3athrow/vgstation13/blob/f9b8c780eecfedc41459eb46adb6363fd091ed9a/code/modules/client/preferences.dm and haven't found exactly what it is that would solve this.

**Comment by 9600bauds** [comment]
Should be fixed, make a new issue if not
