### ISSUE TITLE
Recent issues, performance, lag, weird acting objects

### ISSUE THREAD

**Issue by eplgr** [d3athrow/vgstation13#13252]
#### Description of issue

Recently, an update caused everything to start acting very weird. Watch the webm, it explains better than what I can say with words. 

https://puu.sh/tanps/3f521ad032.webm (first half shows objects acting weird, second half shows...lag)

A few days ago, the whole server started having _very_ high ping, resulting in several rounds crashing and/or force-ended. Apparently, it was a bug with viruses, and the update got rollback'd. This did fix the server-wide problem, but some players, including me, still experience issues.

I am opening this thread mainly to be a reminder, especially because it looks like it doesn't affect everyone, but I am guessing that the players that have these issues, almost can't play anymore.

Sidenote: no, it's not a personal internet connection problem, many players have this issue and, in my case, I have no problems in any other online game + **the test server works perfectly**.

#### Difference between expected and actual behavior
Everything was working fine 1 week ago.

#### Server revision
43feddfd3591b6719e0d6e1586160a93e62c40cf 

#### Issue bingo
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

#### Versions
Byond: 510.1345
IE: 11.576.14393.0 (Update 11.0.38 KB3203621)
Windows 10 Pro, Version 1607, Build 14393.576, x64.

**Comment by Exxion** [comment]
The lag issues, if they don't happen to everyone, wouldn't be a code issue. Perhaps a hosting or server issue, but not directly related to the code.

That layer bullshit with the crates would be a code issue. Can't imagine what could cause it, though.

**Comment by eplgr** [comment]
I am not really sure how to explain it. What I actually tried to say is that at some point, the server was crashing and NO ONE could play because of the lag. This stopped happening, but to a less extent, the lag is still there. Perhaps some players experience the same issue worse than others? I don't know. 
My sentence stating that "probably not everyone has this problem" is...probably wrong. 

And like I said before, **the test server works perfectly**. So if both of them are hosted in the same place, that is not it.

**Comment by IAGFPRMF1** [comment]
Been happening to me, too. Updating Byond stable and switching to beta did not fix it. 
Horrendous frame lag around large accumulations of blood or items.

Also on Windows 7, so not sure if OS is the issue.

**Comment by CyberTropic** [comment]
I've also been having issues with items flickering around and lag when zooming out in observer mode or looking at large amounts of items lying around. Not an OS issue since mine is on Windows 10. This also only started happening maybe like several days ago.

**Comment by mtpowell** [comment]
It appears to be an issue with your host, from my end. Here's a tracert.

http://i.imgur.com/nLtwCLS.png

It hits the internal network of your host(choopa) and times out. This started roughly 3 days ago, and I can no longer play on this server.

**Comment by 9600bauds** [comment]
I'm definitely getting framerate lag all of a sudden. Not laggy movement, but clear choppish framerates with no obvious correlation to what's going on in the screen. I don't know if this could be related to connectivity?

**Comment by Anglosphere** [comment]
I'm getting the same issue. Lots of frame stuttering, and input lag. To the point where running down a hallway, and getting into a door is quite difficult. 

I'm also seeing the same thing as in the .webm in Shomeks post. Items in large stacks move to the top, and then another one moves to the top, and sometimes they disapear. 

Byond: 510.1347
Windows 7

**Comment by despotate** [comment]
Windows 10 craptop, have never experienced any of these issues (especially no flickering), but I have had a bit of stuttering occasionally and blood does cause a lot of lag.

**Comment by mtpowell** [comment]
If the other people experiencing these issues could post a tracert(windows key+R > tracert game.ss13.moe) we could determine if it's the host or not.

**Comment by Exxion** [comment]
Zooming in and out has always been laggy, but low framerates with no clear reason is strange.

Also, blood lag is nothing new
That one's thanks to BYOND's icon operations being preposterously slow

**Comment by JustSumBody** [comment]
Another potentially related issue: Some people are reporting that things with movement states are constantly moving.
See
http://is.4chan.org/vg/1483526087922.webm
For the record, I'm getting literally none of these issues
Current version 511.1365

**Comment by jknpj** [comment]
I'm also having this issue with movement state

**Comment by Banon13** [comment]
I started noticing this issue last night when doing some mining. Pile of various ore sheets, the sprites would flicker and shuffle. I'm getting no more lag than usual though.  It also seems like movement states are accelerated or stuck in a loop. Firelock lights blink faster than normal. Corpus the medbay pet rapidly headbobbing. Basically anything animated.

**Comment by eplgr** [comment]
Posting my tracert in case it helps, it times out in the same place as well I believe:
https://puu.sh/tb2Vn/8c161a5eec.png

**Comment by Exxion** [comment]
@Banon13 They would flicker and shuffle while you were standing still, or while you were moving?

**Comment by Banon13** [comment]
@Exxion While moving. Though the shuffling effect can be a bit inconsistent in when it occurs. Some piles of objects won't shuffle and some will.

**Comment by Exxion** [comment]
Then that's normal. BYOND just has no idea how to deal with things on the same layer.

**Comment by Probe1** [comment]
@ShoMek @Banon13 @TNepr @mtpowell  please update us on whether the issues, aside from high ping, are still present.

**Comment by mtpowell** [comment]
@Probe1 It appears to be fixed, don't know what you did but good job 💯

**Comment by Probe1** [comment]
Pomfs our hero @mtpowell

**Comment by 9600bauds** [comment]
:heart:

**Comment by Exxion** [comment]
The fix was downgrading from the latest BYOND beta

If ping is still a widespread issue, pester Pomf. Not much we can do about it codewise.
I guess we could make an attempt at better lag compensation, but considering BYOND's limitations, it would be a marginal improvement at best, and a lot of work.

**Comment by eplgr** [comment]
Yeah, it feels much much better. Sorry for taking 2 days to reply.
