### ISSUE TITLE
Celtic crown doesn't actually protect you from the cold

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13251]
![image](https://cloud.githubusercontent.com/assets/19365096/21628364/d66176c8-d1ec-11e6-81f0-2e441aefd76a.png)

Also tested with a foam extinguisher, began taking a nap after a few sprays.

**Comment by PJB3005** [comment]
This may have been my fault while fixing the compile failiure caused by the merge of the PR (which **wasn't** @Shadowmech88's fault mind you)

**Comment by Shadowmech88** [comment]
So how do we fix it?

**Comment by AutismSpider** [comment]
Fix it by starting a potato famine

**Comment by PJB3005** [comment]
@Shadowmech88 no idea, try debugging it I guess?

**Comment by jknpj** [comment]
Armor is the problem, not the crown. I'll see if i can just add a istype in the armor to see if you got the celtic crown equiped

**Comment by Shadowmech88** [comment]
The armor is NOT the problem, I specifically tested it when I coded the crown, and the crown protected me.
The problem is the crown, and I'll get around to fixing it soon.
