### ISSUE TITLE
Massive amount of calls and self CPU on barricades/destroy()

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13254]
calls a.pomf.cat/ukrlrz.txt
self cpu a.pomf.cat/nxpejp.txt
total cpu a.pomf.cat/dpijtf.txt

Proc Name                                                                                      Self CPU    Total CPU    Real Time        Calls
------------------------------------------------------------------------------------------    ---------    ---------    ---------    ---------
/obj/structure/window/barricade/Destroy                                                       48545.344        0.009        0.009           35

CPU was  over 100 for an extended period of time.

http://game.ss13.moe/logs/Dev/runtime/2017-01-03-runtime.log

I dumped profiling info but it doesn't seem to be uploaded I"ll check with Pomf

**Comment by 9600bauds** [comment]
:clap:

**Comment by Exxion** [comment]
>Self CPU: 48545.344
>Total CPU: 0.009

What in the name of fuck

My grip on the Self/Total CPU distinction is tenuous at best, but I wasn't aware Self COULD be higher than Total

**Comment by Kitfox88** [comment]
the power of belief

**Comment by Exxion** [comment]
Anyway, it was PROBABLY that runtime that there are a bunch of
```
[16:46:41] Runtime in ,: bad arg name 'brokenup'
  proc name: Destroy (/obj/structure/window/barricade/Destroy)
  usr: Jose Gaspar (seldomseenman) (/mob/living/carbon/human)
  usr.loc: The plating (311, 206, 1) (/turf/simulated/floor/plating)
  src: the wood barricade (/obj/structure/window/barricade/full)
  src.loc: the plating (310,206,1) (/turf/simulated/floor/plating)
  call stack:
  the wood barricade (/obj/structure/window/barricade/full): Destroy(null)
  the fire axe (/obj/item/weapon/fireaxe): afterattack(the wood barricade (/obj/structure/window/barricade/full), Jose Gaspar (/mob/living/carbon/human), 1, "icon-x=22;icon-y=4;left=1;scre...")
  Jose Gaspar (/mob/living/carbon/human): ClickOn(the wood barricade (/obj/structure/window/barricade/full), "icon-x=22;icon-y=4;left=1;scre...")
  the wood barricade (/obj/structure/window/barricade/full): Click(the plating (310,206,1) (/turf/simulated/floor/plating), "mapwindow.map", "icon-x=22;icon-y=4;left=1;scre...")
```

**Comment by Exxion** [comment]
Wait
Fuck
Goddamn it
>`Runtime in ,:`

AGAIN

**Comment by Probe1** [comment]
What's it mean @exxion

**Comment by Exxion** [comment]
Fuck if I know

Also, I have determined that we can blame Dylan for the runtime here
Though I have no idea what could POSSIBLY cause that completely absurd Self CPU

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/21652132/6de285a0-d279-11e6-80f9-d6ee7e4a111c.png)

**Comment by 9600bauds** [comment]
I think the barricade thing is just an artifact of profiling rather than the cause for the meltdown probably. Maybe it's that shuttle lighting thing?

**Comment by Exxion** [comment]
Honestly that's the only remotely sensible explanation

**Comment by 9600bauds** [comment]
First round I observe is lag hell, second one has no lag at all.
In the first one someone had the salvage shuttle, clown was using the mining shuttle, and I think someone was using the trader shuttle.
Second, none of those things that I know of.

Koinsidents???
