### ISSUE TITLE
[Proposal/Feature Request] Make Antimatter Great Again

### ISSUE THREAD

**Issue by Efruit** [d3athrow/vgstation13#13264]
**The actual proposals are in the comments. Go there.**

The Antimatter Engine is somewhat behind the other engines in its potential.
 * The TEG can be hooked up to a R-UST
 * The SME can be built in any number of configurations
 * The solars can have their panels replaced for up to 200% extra power
 * The singulo has the opportunity for unusual configurations and immediate danger to the station
 * The AME has... moar coars.

This proposal seeks to make the AME more configurable, and to give it the potential to be touched more than once per round.

This is a 5-part proposal.
Each part has its own comment, describing the particular component. This is done to refrain from spamming the issues section, while permitting emojicratic voting on individual parts.
All 5 parts are independent (although part 4 isn't particularly helpful without part 3), and should be voted on as such.

**Comment by Efruit** [comment]
**Make Antimatter Great Again: Part 1 (Different AM jars)**
 * Two larger variants of AM Containment Jar, one with 5,000 units (yellow), one with 10,000 (red)

**Comment by Efruit** [comment]
**Make Antimatter Great Again: Part 2 (Controller upgrade - Tank eater)**
 * A circuit board (applied like the jannicart upgrade) that allows the controller to automatically eject empty tanks, and pick up full(er) tanks from surrounding tiles.

**Comment by Efruit** [comment]
**Make Antimatter Great Again: Part 3 (Plasma reaction)**
 * Makes the AME more efficient (= more power) with plasma in the atmosphere.
 * Adds an airlock to the Box AME room because it's fucking PLASMA.
 * Could possibly add a pipe cap to allow SME plasma to be routed inside the AME room.
 * _It will never be made less efficient than it already is_

**Comment by Efruit** [comment]
**Make Antimatter Great Again: Part 4 (Controller upgrade - Auto-tune)**
 * Currently, the highest safe antimatter injection rate is 2 times the reported "Current Efficiency", which is directly related to the number of cores.
   With MAGA Part 3, that is no longer the case, as plasma would change the effeciency
 * Add Another circuit board added post-construction to the AM controller to allow it to automatically apply the highest safe injection rate.

**Comment by Efruit** [comment]
**Make Antimatter Great Again: Part 5 (Antimatter Collectors)**
 * A way to refill AM Jars.
 * Either placed outside the station, or tied to the SME somehow.

**Comment by Probe1** [comment]
Having swappable upgrades delivered via circuit boards is a neat idea.  Give it a cap like a max of 2 upgrades.  Let players choose how to customize their engine.  Have it auto eject and auto load, but the AME will never be more efficient.  etc.

Oh god i'm imagining full on mech attachments.  Loader arms and ejection racks.

**Comment by PJB3005** [comment]
Factorio when

**Comment by Probe1** [comment]
@PJB3005 remember SAMMIs

**Comment by Shadowmech88** [comment]
Someday I think I might like to bring SAMMIs back, I liked the concept.

**Comment by Exxion** [comment]
Make them actually programmable rather than player-controlled
Or let them be either
I really want programmable arms though

**Comment by Probe1** [comment]
I can't wait for Leroylightyear to come back next gear and give us the next gift of hilarious broken coding.

**Comment by Exxion** [comment]
Leroylightyear?

**Comment by Probe1** [comment]
The guy that coded cancer and SAMMIs

**Comment by Exxion** [comment]
Is that Cloroxygen's ckey or something?
