### ISSUE TITLE
Wizard Blink OP AF

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13263]
(WEB REPORT BY: ro5490 REMOTE: 172.93.109.202:7777)
>Revision 91551003f85eb38502983816267c0f6bd9981464

>General description of the issue
Wizards blinking so damn rapidly around the place makes it almost impossible to hit them with anything, needs nerfing a little.

>What you expected to happen
Hit OP wizard with anything

>What actually happened
Wiz Blinked 8+ times, dodged everything from 4 crewmembers and escaped

>Steps to reproduce if possible
Play as wizard, chose blink as a spell.

**Comment by Blithering** [comment]
Fun fact: If you click to shoot a wizard just as they blink, you will fire at their new location instead of where you clicked.

**Comment by 9600bauds** [comment]
How much of this is the short cooldown and how much of this is the smoke?

**Comment by AutismSpider** [comment]
most of it is the smoke it makes like 4 to 6 smoke clouds making it hard to see fucking any thing.

**Comment by Probe1** [comment]
It makes me want to add a salt tag but that's very inappropriate and unhelpful.  But it makes me wanna.

**Comment by kilozombie** [comment]
Just Use Lasers (tm)

**Comment by kol1th** [comment]
And every wizard somehow still dies even though blink is so overpowered. Just remember, wizard is a solo antag (unless it's ragin mages), and when they die it's just regular extended unless an antag intervenes. They SHOULD be stronger and harder to kill.

**Comment by icantthinkofanameritenow** [comment]
Half the time I use it, I just blink into a wall or into space.

**Comment by Shadowmech88** [comment]
If you're blinking into a wall or space, bug report it. Blink has both `IGNOREDENSE` and `IGNORESPACE` flags, meaning neither walls nor space should be chosen as a valid target.

**Comment by jknpj** [comment]
Can't we have a IGNOREGASMINER flag? because it happens a lot

**Comment by Probe1** [comment]
You would want ```turf/simulated/floor/engine``` .   That'd also preclude the supermatter shard chamber and TEG burn chamber.

**Comment by Shadowmech88** [comment]
Is that flooring different than reinforced flooring? Because if not it would allow the crew to counter a blink wizard by placing reinforced flooring all over the station.

**Comment by Probe1** [comment]
It is not.  If you'd like you could specifically path all the gas miners varedited floors that contain their particular gas, as well as the SME and TEG floors, to have their own paths then have blink check against that.

**Comment by ComicIronic** [comment]
I don't think it would be a good idea at all. We could have blink check the gas pressure of every turf you might move to (because what happens if I make a big pressure room that isn't a starting miner) but I'd rather wizards just stopped teleporting near miners. If you're in danger of jumping into a death zone randomly, maybe don't do that.

**Comment by Exxion** [comment]
Agreed
Don't make blinking be COMPLETELY without risk
