### ISSUE TITLE
You can surgically remove a limb, and reattach it, and the limb will have no associated damage

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13265]
#### Description of issue

Because of https://github.com/d3athrow/vgstation13/pull/12803 you can now chop off a limb, say a broken hand with internal bleeding and max damage, and reattach the exact same hand, and it will have none of the associated damage

#### Difference between expected and actual behavior
Expected - The limb object transplanted to have the associated damage it had, such as bad veins, broken bones, burn and brute damage, etc.

Actual - It has no damage whatsoever

#### Steps to reproduce 
Have a guy come in with bad damage to a limb you can remove

Chop it off in some way

Reattach it through surgery

Marvel at the fact it has no damage

#### Specific information for locating

Surgery, limbs, https://github.com/d3athrow/vgstation13/pull/12803

#### Length of time in which bug has been known to occur

18 days as of this bug report

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by 9600bauds** [comment]
Can you believe this is a thing for internal organs, but not external ones?

**Comment by ghost** [comment]
Internal organs are a bit more sensible when it comes to organs.

>A species has a list of organs
>on spawn, it generates these organs
>On removal of these organs, the datum is actually placed into the organ object

Whereas external organs are a more evil business

>All species have a left arm, a right arm, a left hand, a right hand, a left leg, a right leg, a left foot, a right foot, one chest, one groin, one head
>on 'removal' of one of these external organs, it drops a weird object, and sets a variable in the datum to 1
>This leads to weird shit
