### ISSUE TITLE
Deff has a missing disposal pipe above the courtroom

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13279]
![dreammaker_2017-01-06_00-11-29](https://cloud.githubusercontent.com/assets/8550416/21708271/d5e2c4ae-d3a4-11e6-9c74-95f72781156d.png)

**Comment by Probe1** [comment]
Like you're ever gonna map you cock wrangler

**Comment by Intigracy** [comment]
Don't be rude you pole smoker
