### ISSUE TITLE
research botanists have no access to botany

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13278]
(WEB REPORT BY: januszpavulon REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
95b4ef1eec015ac10a29f78189f3a8d6555c34b9 
>General description of the issue
cant open botany crates and shit because of this, it makes no sense

>What you expected to happen
to have botany access

>What actually happened
didn't had botany access

>Steps to reproduce if possible
play as research botanist, order botany crates and try to open them

**Comment by JustSumBody** [comment]
Can always just smash them open with your emitter

**Comment by DeityLink** [comment]
Fixed by #16694
