### ISSUE TITLE
Welder-Induced Blindness Is Genetic and Requires Ryetalyn Even After a Transplant

### ISSUE THREAD

**Issue by Fruktlimpa** [d3athrow/vgstation13#13272]
#### Description of issue

Someone who welds their eyes to destruction is unfixable by imidazoline or transplant. If you transplant then you STILL have to do eye repair surgery to fix it even tho that makes no sense.

#### Difference between expected and actual behavior

I expected the eyes to work after transplant

#### Steps to reproduce 

Welder your eyes to mush. Ask for transplant. Watch it not work.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
It was a genetic defect.

**Comment by ComicIronic** [comment]
And the reproduction steps?

**Comment by AI-Is-Rogue** [comment]
@Probe1 It was not a genetic defect, I was the one who had their eyes fucked beyond belief
@ComicIronic I welded reinforced tables a few times after I went blind, I then went to medbay and found out my eyes were destroyed.

**Comment by Probe1** [comment]
```
var/b_eyes 
var/g_eyes

```

aren't being reset to 0.  Implanting new eyes needs to run a eyecheck() or however that shit works.

**Comment by Fruktlimpa** [comment]
The lad came in with around 60+ eye damage. First I gave him Imidazoline until it was down to 0 but it didn't work.
Then I transplanted his eyes for new ones and I made sure they were healthy new eyes.
It didn't work. Afterwards I did the regular eye repair surgery
Target eyes, scalpel, retractor, hemostat(?), cautery. And that fixed the issue.

The eye repair surgery was done on the transplanted eyes and not on the original broken eyes.

**Comment by ghost** [comment]
I've got it.

Welders, when they're applying damage to your eyes if you're welding without protection, apply disabilities to you if your eyes go above a certain damage threshold. These disabilities are not tied to the eyes, but the user.

			if (E.damage >= E.min_broken_damage)
				user.simple_message("<span class='warning'>You go blind!</span>","<span class='warning'>Somebody turns the lights off.</span>")
				user.sdisabilities |= BLIND
			else if (E.damage >= E.min_bruised_damage)
				user.simple_message("<span class='warning'>You go blind!</span>","<span class='warning'>Somebody turns the lights off.</span>")
				user.eye_blind = 5
				user.eye_blurry = 5
				user.disabilities |= NEARSIGHTED
				spawn(100)
					user.disabilities &= ~NEARSIGHTED

Imidazoline doesn't fix this, eyeswapping doesn't fix this. Only the surgery where you lift the lenses fixes this.

**Comment by Probe1** [comment]
The solution is to add a message about going permanently blind to the user.

**Comment by Shadowmech88** [comment]
It doesn't exactly make sense though, for welding-related damage to not be fixed by an eye transplant. Even if that damage is a genetic defect.

Maybe genetic defects that deal with eyes in general should be fixed when receiving new eyes.

**Comment by ghost** [comment]
I'll see if I can move it to eyeballs
