### ISSUE TITLE
Waterflower breaks clowncart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13275]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
95b4ef1eec015ac10a29f78189f3a8d6555c34b9 

>General description of the issue
Using a water flower on a clowncart after getting the upgrade breaks the clowncart completely making you unable to use anything but the flower on it and it also empties the water flowew

>What you expected to happen
to be able to ride the cart

>What actually happened
unable to ride the cart

>Steps to reproduce if possible
upgrade the clowncart with bananium until it says you can fill your flower
and then use the flower on it and try
to ride the cart or use anything compatible on it

**Comment by Shadowmech88** [comment]
Tested, I was able to fill a flower and then ride the clown cart just fine.
