### ISSUE TITLE
Game frozen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13277]
(WEB REPORT BY: uszy REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
95b4ef1eec015ac10a29f78189f3a8d6555c34b9 

>General description of the issue
Suddenly disconnected, after reconnecting a few (graphical) frames play and then the screen's frozen on the last thing I saw. Can still hear game sounds, see chat. This happens fairly frequently if I don't re-start the game fresh and a few rounds go by.

>What you expected to happen
This was only the second game I played today, didn't expect it to catch me on the second time reconnecting.

>What actually happened
Thing.

>Steps to reproduce if possible
I found this doesn't happen if I do a fresh start every round, but this time I was disconnected mid-game.

Never had this happen back in 2015.

**Comment by BobdaBiscuit** [comment]
I can confirm this happens for me with the byond beta, stable is fine.

**Comment by Exxion** [comment]
The newest beta is turbofucked.

**Comment by DeityLink** [comment]
Well at the very least we're no longer suffering from that beta in particular
