### ISSUE TITLE
Deff still has a christmas fire near arrivals

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13281]
https://a.pomf.cat/kwipsh.png

small surprise no one noticed and reported it.

**Comment by CyberTropic** [comment]
Where's the issue? Do you just hate comfy???

**Comment by Kurfursten** [comment]
I think Box still has some lights in northwest maint

**Comment by Probe1** [comment]
holy shit i'm going to put maptext down that says it is an easter egg if one more person says it

**Comment by PJB3005** [comment]
(Box never actually had christmas lights)

**Comment by Exxion** [comment]
Instead of maptext, just put a Gashapon pod resprited into an actual Easter egg beside it

**Comment by Probe1** [comment]
I know that's what makes me exasperated.  I'm joking with all this I'll just hide it somewhere else so people don't file some reports

**Comment by Intigracy** [comment]
We have actual Easter eggs in the code.
