### ISSUE TITLE
Smoking a cigarette as a Grey protects you from being splashed with water

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13280]
Someone was on fire next to me a couple days ago and an overzealous volunteer fireman ended up spraying an extinguisher at me, but I took no damage because of the ciggy I'd been smoking.

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm#L382

**Comment by Shadowmech88** [comment]
Permeability code is garbage.

**Comment by 9600bauds** [comment]
#7786

**Comment by Sprok0** [comment]
This has nothing to do with permeability anything, greys are just entirely immune to splashed water if they have anything at all in either their mask or hat slot.

**Comment by Shadowmech88** [comment]
I'm pretty sure the reason is that having something in their mask or head slot prevents the splashed water from actually hitting them because of *permability code.*

**Comment by Sprok0** [comment]
I mean, he linked the relevant code in the report, it's pretty clear.
```
if(H.wear_mask)
	to_chat(H, "<span class='warning'>Your mask protects you from the water!</span>")
	return
if(H.head)
	to_chat(H, "<span class='warning'>Your helmet protects you from the water!</span>")
	return
```
