### ISSUE TITLE
Should pAIs Inside MULEbots be Able to Open Firelocks Via Bumping

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#13285]
Currently the dropping of firelocks renders the pAI completely confined.

Just curious what people think.

**Comment by Ephx1** [comment]
I don't see why not, Mechs operate in the same fashion. I wouldn't want it for the extreme alarm firelocks that require crowbars though.

**Comment by Exxion** [comment]
Mechs can't bump-open locked firelocks anyway
You need the clamp for that

**Comment by jknpj** [comment]
Dunno, i really have mixed feelings about it. Using the fire alarm is a great way for crew and AI to deal with a rogue smartMULE but at the same time being stuck in between two firelocks because of sighly overpressure must suck a lot

**Comment by Ephx1** [comment]
I thought pAI mules functioned on the same basis as normal mules, power switch and all? Can't an AI just y'know, turn it off?

**Comment by JustSumBody** [comment]
Most projectiles including tasers seem to "short them out", and cut/mend random wires. So if you spam it enough it'll stop moving from having one of its charge wires cut, or stop being able to run people over. 

That said, mules do a FUCKTON of damage running people over. Two hits to crit, think it has higher damage potential than the prenerf syndicate wheelchair.
I don't think they should be entirely self-sufficient with being able to open firelocks as well, but eh. Nothing that requires a crowbar sounds fine

**Comment by Kurfursten** [comment]
@JustSumBody Even before the nerf, the wheelchair didn't deal anywhere near as much as a MULE. The danger with the wheelchair was "get knocked down once, get run over 10 times at 15 damage each".

On topic: I have no preference. MULEs can get through maint to almost all their destinations just fine, but it also doesn't seem catastrophic to give them firelock clearance. Give Smart framework to electric wheelchairs.

**Comment by gbasood** [comment]
long as mulebot players are held responsible for their actions like all other players, sure why not

**Comment by Probe1** [comment]
We hold people responsible for opening firelocks?

**Comment by Exxion** [comment]
Unlocked ones aren't dangerous to open, so that's not really an issue

**Comment by Ephx1** [comment]
Honestly we _should_ hold people responsible for opening burning doors that have big blaring lights on them that scream "DO NOT OPEN" but then a majority of the server would be banned.

**Comment by Kurfursten** [comment]
I think it's a matter of reporting. If I recall correctly, someone WAS banned once for killing a science department full of people by opening a door to a plasma fire, but someone made a request (not sure if that was the only bad thing they did though). So you see, the great barrier there is that people don't feel like making ban requests over firelocks.

**Comment by PJB3005** [comment]
The solution is to remove firelocks.

**Comment by Shadowmech88** [comment]
>MULEs can get through maint to almost all their destinations just fine

pAI-controlled MULEs actually don't have any access, and can only navigate through the no-access doors in the main hallways.
I'm not sure whether that's a good thing or a bad thing.

**Comment by jknpj** [comment]
They do have maint and cargo access

**Comment by Shadowmech88** [comment]
Oh, really?
I guess I never tested those specifically. That's nice.
