### ISSUE TITLE
Parapens contain impedrezine.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13284]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
As things stand, the only not-awful use of the tricky dicky pen is to enable gimmicks and such where you need one or two captives. But this is nonviable when the pen gives the victim 200 brain damage. The brain damage used to be fun when you could buy them from cargo and poke everybody, but that has been removed so the imped should be removed too.

**Comment by Kurfursten** [comment]
I believe you can still get pens from the spec ops crate which requires an emag.

**Comment by Allspice** [comment]
#11851

Spec ops lost the pen and gained a gun.

**Comment by BobdaBiscuit** [comment]
From testing it seems impedrezine makes the knockout absolutely instant, without it there's a bit of a delay the attacked can shout for help/move about before being knocked out. It also lasts way after the other chemicals leaving the target with a whopping 200 brain damage.

A possibly fix would be to just 1u or so so they only get medium retarded, while retaining the instant effect of it.
