### ISSUE TITLE
library's visitor computer issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13297]
#### Description of issue
when you use the library's visitor computer, if you choose the "any" category it won't show any book, because the game thinks that "any" is a category itself; this means that if you choose a category you can't see the full list anymore; i think a similar issue was already fixed for the Check-In/Out Computer here: https://github.com/d3athrow/vgstation13/pull/9567
i saw this on box, i can assume it's the same on all maps.

#### Difference between expected and actual behavior
expected the "any" category filter showing all the books;
got the "any" category filter showing nothing.

#### Server revision

ebc8bd6f8b63289357eae99b91a8e79b576e0d5e 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Ephx1** [comment]
We could just remove the visitor's computer and no one would notice

**Comment by west3436** [comment]
The visitor's computer has been removed and this issue is fixed in the Check In/Check Out computer as stated in the OP.
