### ISSUE TITLE
Beepsky (and all secbots) can be loaded onto a MULEbot, and beepsky will walk off the MULEbot and still remain the MULEbot's load

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#13290]
basically lets you teleport beepsky without carrying him I guesssssss

**Comment by Shadowmech88** [comment]
Seems the fix would just be to make Beepsky not move if its loc isn't a turf.

**Comment by Kurfursten** [comment]
does this affect all bots in general? e.g.: medbot

**Comment by ComicIronic** [comment]
Loading doesn't change loc. I think stuff just need to unload from a mulebot on Uncrossed().

**Comment by Shadowmech88** [comment]
Doesn't the `C.forceMove(src)` at https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/machinery/bots/mulebot.dm#L442 make `C`'s `loc` the MULEbot?

**Comment by gbasood** [comment]
Don't ask Comic it's not like he made that line change or anything
![](http://i.imgur.com/cTF7jtT.png)

**Comment by Exxion** [comment]
MULEbots predate atom locking, but they should probably be changed to use it

**Comment by ComicIronic** [comment]
A robot made that PR!
