### ISSUE TITLE
We should add a poster printer that lets players turn jpg/png images into posters!

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13306]
Think of the 32x32 anuses!

**Comment by gbasood** [comment]
w y c i
just remember that anything like this has to be uploaded to serb, processed, and then sent out to all clients

**Comment by Probe1** [comment]
I know 😞

**Comment by Rattlederp** [comment]
well cant you just use whatever is used for putting images on pieces of paper?

**Comment by Shadowmech88** [comment]
Images on pieces of paper are possible because the images are opened in a client-side browser window.
They're not a physical object in the game that everyone can see at the same time.

**Comment by Probe1** [comment]
Yeah that's where I got the idea @Rattlederp

**Comment by Rattlederp** [comment]
Oooh, well in that case a ghetto and easier to implement version of what you're is asking for is just make paper placeable on walls? Perhaps a different generic sprite for when the paper only has an image and is placed on a wall
edit: only downside there is that it wont be viewable unless you right click it or something like shadowmech said

**Comment by jakmak4** [comment]
rattle some other servers have duct tape that can be used to tape paper to walls if you want to try to port that

**Comment by Probe1** [comment]
holy shit stop making new github accounts you can delete your repository if you have really fucked it up

**Comment by jakmak4** [comment]
nigger how was i suppose to fix my other account. I couldn't download the repo through any mortal means (except outright downloading the zip which i wouldnt have been able to submit changes without begging another to upload them for me). Even pjb gave up and didnt know how i fucked up my shit so hard

**Comment by mrpain666** [comment]
A compromise would be examining the poster and having the image pop up in a window

**Comment by PJB3005** [comment]
@jakmak4 is this actually the fourth account you've made?

Literally if making a new account genuinely fixes anything you've got an email to send to GitHub support.

**Comment by SonixApache** [comment]
Ah, yes, so librarians can actually make porn museums.
Fund it.

**Comment by Shadowmech88** [comment]
We could make the poster a larger version of the sprite nanopaper uses, to let people know it's got a custom image on it.

**Comment by kol1th** [comment]
fund it immediately

**Comment by PJB3005** [comment]
Or we could tell people to upload the perfect size of icon.

**Comment by Exxion** [comment]
This actually wouldn't be that hard to code, if anyone still cares about it
That is, it wouldn't be that hard to code if players had to directly upload the image. Making it retrieve an image from a URL would be difficult, but not impossible
