### ISSUE TITLE
Random name didn't give me a first name, only a last name

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13302]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 78a1d0e641a1f88b84a61da1a304693f43ae9e42 

>General description of the issue
Random name gave me the name " Agg"
I wasn't given a first name, only a surname
>What you expected to happen
random name should give me a first and last name

>What actually happened
no first name, only surname

>Steps to reproduce if possible
just play enough random name that you get lucky and land a no first name combo.

**Comment by Aurx** [comment]
What race?

**Comment by mrpain666** [comment]
OH NO THINK OF THE WAIFUS! THE STATIC META FRIENDS!!11!!1

**Comment by 9600bauds** [comment]
i doubt anyone will bother testing this until the reporter says what race they were

**Comment by Exxion** [comment]
Vox don't generate separate first and last names, and even if they did, "Agg" wouldn't be one of them
No idea about diona or plasmaman name generation
I think greys and humans draw from the same pool, which "Agg" is a part of, if I'm not mistaken

**Comment by DamianX** [comment]
Is it possible this would happen if the names.txt file contains a blank line? Perhaps at the end of the file?

**Comment by Exxion** [comment]
Yes
