### ISSUE TITLE
Players Missing One Arm Cannot Wear Gloves

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#13312]
This feels like an oversight. I mean, there's no reason that you can't put a glove on your remaining hand.

**Comment by Probe1** [comment]
Cuffs, yeah sure what are you gonna cuff them to.  But gloves that's just stupid.  Head canon it any way you like.

Oh god what if someone gets really autistic and adds left and right handed gloves and we have to keep track of which hand has the boxing glove and which has the insulated glove

That actually sounds kinda sweet now that I think about it.

**Comment by Aurx** [comment]
We're adding new inventory slots?  
BRING BACK HAT STORAGE

**Comment by kilozombie** [comment]
Give me an inventory slot for every finger so I can wear my Elite Celtic Ring of Hydrocumulation +6 as well as my Excavator Mystery H.O.N.K. Gauntlet of Many Fists at the same time

**Comment by Shadowmech88** [comment]
As was mentioned in the issue I opened about this, there are a couple ways to solve this.
Either split *every* glove sprite into right and left gloves, and apply the sprites based on which hands the wearer has.
Or edit the existing glove sprites on the fly based on which hand the wearer is missing, which I have no idea how to do and according to Comic, risks breaking a lot harder.

**Comment by Ephx1** [comment]
> Cuffs, yeah sure what are you gonna cuff them to

The arm itself

**Comment by gbasood** [comment]
@Aurx no
