### ISSUE TITLE
You can interrupt a surgery step without being punished for it by dropping the tool you're using

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13317]
This is my go-to for when I realize I've accidentally started surgery on the wrong body part / used the bone setter without the bone actually being broken.

There needs to be proper way to safely cancel surgeries, dropping your tools on the floor just to stop sawing someone's head off is breaking my immulsions.

**Comment by Exxion** [comment]
You can do anything that would cancel a `do_after()`, right? Like moving or switching hands.

**Comment by despotate** [comment]
Moving or switching hands or putting the tool away makes the surgery fail (eg. if you're using a scalpel, you cut them open, if you're using glue, you smear it on their organs)

**Comment by Exxion** [comment]
That's dumb
