### ISSUE TITLE
Chest borers should have the ability to defibrillate their host

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13322]
Seems like something that'll help them get a leg up compared to headborers.

**Comment by gbasood** [comment]
too stronk

**Comment by despotate** [comment]
Defibrillating someone doesn't really do anything to help them other than let them walk for fifteen more seconds and lie in crit for thirty more seconds, though. Borers usually leave their host on death anyway, and we can always make borerfibrillation cost a lot of chems.

**Comment by Ephx1** [comment]
Oh fuck off, borers are already OP enough

**Comment by BobdaBiscuit** [comment]
Defib removes the only weakness borers have and that is if their host dies that's it, game over, everybody out.
With a headborer/chest borer combo you could in theory have an un-dieing man who just gets right back up after death with the head borer shitting chems in and chest borer getting the old ticker going again.

**Comment by Probe1** [comment]
https://www.youtube.com/watch?v=dfKQUEPcgi8

**Comment by despotate** [comment]
Then the correct answer is to severely nerf headborers. The problem that this feature request is trying to solve is that being a chestborer by yourself is really unappealing, you can only inject blood, get an advanced scan, and kinda resist two basic types of damage by expending a ton of chems. Even legs are more fun to be in.

**Comment by Probe1** [comment]
I'm 💯 % ok with nerfing headborers and think that's stupid power creep that they get x-ray.

**Comment by Ephx1** [comment]
The whole "you can slap a borer in every limb!" is fucking stupid, the fact that head borers got buffed ON TOP OF THAT is even worse.

**Comment by Probe1** [comment]
I'm actually ok with the "pick a part of the body and it has specific stuff" and think that's neat.

That's no reason to give it super good stuff so everything else gets fuckin thrown out of whack and pAIs now want buffs and now antags need buffs because captains are rolling around with turbo pocket valid-protectors.

**Comment by Shadowmech88** [comment]
For the record, head borers were *supposed* to have X-ray even before I touched them.
The prerequisite check just didn't work correctly, so they couldn't access it.
