### ISSUE TITLE
Captain's helmet needs a light on it because that's cool

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#13325]
#### Description of issue
The captain's armour helmet doesn't have a light.

#### Difference between expected and actual behavior
Expected a cool light like deathsquad helmets, but actually have to use hands to activate the free enhanced light in the PDA.

#### Steps to reproduce 
1. Be captain
2. Try to emit light from your helmet (not the SWAT helmet, that one can hold lights, the cool one)
3. Panic as your head remains dark
#### Specific information for locating

I did a sprite for captain helmet lights if that helps.
http://s000.tinyupload.com/index.php?file_id=80690206631959742456
![caplight](https://cloud.githubusercontent.com/assets/15067109/21755548/9878e51a-d60d-11e6-909b-deb5f792f22c.png)

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
I think it makes sense. The Captain shouldn't be running around in maint in his armor hunting valids like deathsquad/swat, that armor is his personal EVA in case of a singuloose or massive bombing.

And like you said, he already gets a free PDA enhanced light.

**Comment by Blithering** [comment]
True, between the PDA light and the SWAT helmet being able to mount flashlights he's not desperate for it, but it's cool. Also the captain's armour being an older model of deathsquad armour is a nice lore/continuity thing that makes me want to give it the cool glowing faceplate they have.

**Comment by Exxion** [comment]
You don't need to use hands to activate the PDA light though
