### ISSUE TITLE
Why not make every alcoholic beverage a "joe"?

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13331]
It'd make people a little more willing to punish their in-game bodies if a drink-appropriate soundtrack followed it, and possibly even some thematic screen changes.

**Comment by Probe1** [comment]
because thats a lot of work and since you're in the bar, a lot of sound on top of the juke.

plus Joe is special.  if everything was special then it wouldn't be special.

if you feel keen to it, add the code for a few other things.

**Comment by despotate** [comment]
I can't even find the music code for it.

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm#L5224
https://github.com/d3athrow/vgstation13/blob/58def87fedc25b491eb63abd0a369a82b2c90558/code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm#L696

**Comment by Probe1** [comment]
The ogg is here https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/sound/misc/noirdarkcoffee.ogg

Try looking for it being called instead of the code calling it.

**Comment by Exxion** [comment]
I'm with Probe here. Having every drink do that would be dumb.
