### ISSUE TITLE
A big list of boxes that need unique sprites and are easy to do.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13330]
![image](https://cloud.githubusercontent.com/assets/8550416/21757999/c647f82c-d604-11e6-921c-ea2004e342b0.png)

The simple box.  Same outline, identifying drawing inside so people can tell at a glance what they are.  But many just default to their plain unadorned box sprite and don't reveal their contents.  If you'd like to cut your teeth on spriting it can't get much easier than this.  People have no expectations but it really needs done.  Here is the big ol list of boxes that need sprites.

obj/item/weapon/storage/box/samplebags
Contains sample bags for Xenoarcheology.
![sample bags](https://cloud.githubusercontent.com/assets/8550416/21758144/cc3dccbe-d606-11e6-88ba-4d50d50dc953.png)

~~/obj/item/weapon/storage/box/botanydisk~~
~~Contains data disks for botanists.~~
![hydrodisk](https://cloud.githubusercontent.com/assets/8550416/21758154/d630de46-d606-11e6-9600-a390840ea5c1.png)

~~/obj/item/weapon/storage/box/holobadge~~
~~Contains holobadges.~~
![holobadge](https://cloud.githubusercontent.com/assets/8550416/21758156/da7bd69a-d606-11e6-9613-28bc40dea0b2.png)

~~/obj/item/weapon/storage/box/mugs~~
~~Contains mugs.~~
![mug](https://cloud.githubusercontent.com/assets/8550416/21758157/de2b785e-d606-11e6-87e5-e0d29e1975b7.png)

/obj/item/weapon/storage/box/pillbottles
Contains.. pill bottles. 
![pillbottle](https://cloud.githubusercontent.com/assets/8550416/21758175/01bb34e4-d607-11e6-83f0-94b19107cf09.png)

/obj/item/weapon/storage/box/cups
Contains paper cups.
![watercup](https://cloud.githubusercontent.com/assets/8550416/21758162/e408b0c0-d606-11e6-9baa-02c5eb80bfeb.png)

/obj/item/weapon/storage/box/condimentbottles
Contains condiment bottles
![condiment](https://cloud.githubusercontent.com/assets/8550416/21758164/e6e3d608-d606-11e6-82d3-b93bb3fee709.png)

/obj/item/weapon/storage/box/drinkingglasses
![emptyglass](https://cloud.githubusercontent.com/assets/8550416/21758166/eb833d0c-d606-11e6-89d4-c23248ee74b3.png)

/obj/item/weapon/storage/box/blanks
These are shotgun shells.
![blank shell](https://cloud.githubusercontent.com/assets/8550416/21758168/ee97c558-d606-11e6-8bf5-a2ec307b6612.png)

~~/obj/item/weapon/storage/box/injectors~~
![injector](https://cloud.githubusercontent.com/assets/8550416/21758170/f16ccae4-d606-11e6-8499-45547c180193.png)

~~/obj/item/weapon/storage/box/spellbook~~
~~This one actually contains a bunch of spellbooks so creativity counts.~~
![image](https://cloud.githubusercontent.com/assets/8550416/21758101/13d9bd9a-d606-11e6-9ea7-552673d6ec8b.png)

**Comment by Exxion** [comment]
...Why is there a condiment bottle box? The CondiMaster just makes them for free, and very few people except the chef would need them.

**Comment by Kurfursten** [comment]
It probably predates the condimaster

**Comment by Blithering** [comment]
Pill bottle, evidence bag, and shotgun shells all already have icons for their respective boxes in the game files, probably just not used.

**Comment by west3436** [comment]
These have been implemented
