### ISSUE TITLE
Advanced EOD suit did not prevent gibbing from a bomb.

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#13344]
#### Description of issue
While wearing an Advanced EOD Suit/Helm a bomb blast went off and gibbed me. I'm not sure what the intended behaviour is but I heard the regular suit is meant to kill you but prevent gibbing, and advanced EOD is meant to let you tank a devastation range bomb, with no chances to gib.

#### Difference between expected and actual behavior
**Expected:**
* Boom
* Haha nice firecracker

**Actual**
* Station has some new red paint on the walls

#### Steps to reproduce 
* Wear advanced EOD suit
* Be in the devastation range of a bomb

#### Specific information for locating

-

#### Length of time in which bug has been known to occur

-

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
It's not guaranteed protection, else it'd all be at 100% bomb protection.

**Comment by SkowronX** [comment]
armor = list(melee = 80, bullet = 80, laser = 40,energy = 20, bomb = **_100_**, bio = 0, rad = 0)

**Comment by ghost** [comment]
Well shit, what's its coverage flags?

Engineering hardsuit and helmet may have 80% rad resistance on both, but they don't cover hands and feet, so with the usual magboots and insulated gloves it drops to about 65% rad resistance

**Comment by Eneocho** [comment]
Tested it, it let me tank a point blank shard and a point blank nitro, though you get injured enough to be pretty close to dying either way.
