### ISSUE TITLE
EMP rune has the same range as EMP talisman.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13346]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
That is, radius heavy 1 light 3. Something like heavy 4 light 7 might be better.

**Comment by Allspice** [comment]
On second thought, I probably got the numbers wrong; if radius 1 is your tile and 2 is the tiles next to you, EMP talisman and rune are heavy 2 light 4, so upgrade to heavy 5 light 8 or some such.

**Comment by Kurfursten** [comment]
I thought the advantage of the rune was that it doesn't go away. So you can keep EMPing a borg who wanders too close over and over. That seems strong enough without a range bonus.

Also, consider this situation: if you make the rune radius 6 or higher, you can simply create a rune in the meeting room and click it repeatedly until the AI dies.

**Comment by Allspice** [comment]
EMP rune vanishes when used, just like the talisman.
