### ISSUE TITLE
Mineral doors can only be deconstructed with a pickaxe

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13356]
#### Description of issue

Mineral doors are doors.  Doors are deconstructed with wrenches and welders.  But not mineral doors.  They require a pickaxe.

#### Difference between expected and actual behavior

Oldcode to be not bad
Oldcode was bad.

**Comment by Exxion** [comment]
>Expecting oldcode not to be bad

**Comment by ComicIronic** [comment]
When you say "doors", what do you mean specifically, airlocks?

**Comment by Probe1** [comment]
No, specifically ``` /obj/machinery/door/mineral ``` opposed to ``` /obj/machinery/door/airlock ```
