### ISSUE TITLE
Mass drivering a gorrillion or so glass shards or whatever probably slowly kills the server beyond watchdog's ability to fix

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#13350]
http://imgur.com/tqPMqYT
http://imgur.com/2pC6xVq

It was that awful "death lag" where the server doesnt work but watchdog thinks it's still on and doesnt bother trying restarting it.

**Comment by Shadowmech88** [comment]
It probably has to do with the number of drivers rather than the number of shards.
I'm pretty sure mass drivers have a limit on how many items they can fire simultaneously specifically to prevent shit like this.

Or maybe the issue is multiple mass drivers trying to throw the same shard?

**Comment by mrpain666** [comment]
It was that awful "death lag" where the server doesnt work but watchdog thinks it's still on and doesnt bother trying restarting it.

**Comment by mrpain666** [comment]
> Or maybe the issue is multiple mass drivers trying to throw the same shard?

Could have been. I'm not well versed in this sort of code and what lag it produces. Someone with that knowledge needs to assess this issue and see what ramifications stacking a billion glass shards and 30 mass drivers would have on the server

**Comment by Exxion** [comment]
I have
NO
Idea

But I'll look into it

**Comment by Kurfursten** [comment]
I can't think of any reason that mass drivers should be stackable.

**Comment by Intigracy** [comment]
The issue is the stackable mass drivers, not the shards.

**Comment by SonixApache** [comment]
Do the mass drivers try to drive eachother?
