### ISSUE TITLE
you can perform CPR on yourself with creatine

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13355]
https://youtu.be/b6XMRh65JeE?t=1m21s

**Comment by Probe1** [comment]
![1416762590023](https://cloud.githubusercontent.com/assets/8550416/21786692/3e7e57d0-d693-11e6-8363-c46e72baa100.gif)

**Comment by Zth--** [comment]
proc/perform_cpr doesn't check if you're trying to CPR yourself. Someone should test it with hulk mutation to see if it's a mutation thing

**Comment by 9600bauds** [comment]
Hulk just lets you not be unconscious during crit, I think that and the lack of sanity is the full extent of it
