### ISSUE TITLE
The Head of Security hat sprite doesn't appear on Greys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13363]
(WEB REPORT BY: digitalis REMOTE: 172.93.109.202:7777)
>Revision ec9c007416dd01bc8f7ddead3278586572afdd03 

>General description of the issue

Title
>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by kol1th** [comment]
To fix this add the sprite to the grey hats.dmi, either one that fits or just the original. Also add `species_fit = GREY SHAPED` to it or whatever it is. 

[EASY FIX THAT I'M TOO LAZY TO DO] tag when?

**Comment by Intigracy** [comment]
Or if you're going to just copy the old sprite instead of adding a grey specific one, instead add `species_fit = list()` to fix it, it's inheriting from the helmet sprite.
