### ISSUE TITLE
the red alarm lights that happen when calling a shuttle fuck up with night vision goggles making all the tiles with the red light dark green 

### ISSUE THREAD

**Issue by pvak** [d3athrow/vgstation13#13368]
#### Description of issue
cant see shit 
i cant see tiles with dirt on them, they turn into a dark green square (maybe related)
also goon lights dont work for me maybe it doesnt happen if someone has goon lights working?

#### Difference between expected and actual behavior

be able to see 

#### Steps to reproduce 
have night goggles on while the shuttle is called in a main hallway

#### Specific information for locating

main hallways

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players (not sure)
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by nervere** [comment]
Still an issue.
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/e10309d5-2478-4336-ae59-9121fb28cc28)

**Comment by west3436** [comment]
Not a bug - night vision works fine with the shuttle enroute if you are actually in a dark area. The picture posted previously had all lights turned on which already blocks NVG vision.
![image](https://github.com/vgstation-coders/vgstation13/assets/66280799/05827d37-74cd-4ce2-b429-5e58f910b181)
