### ISSUE TITLE
Positronic doesn't ping you for signup if prefferences for it are set to No

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13360]
(WEB REPORT BY: shaska REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
2cc0be67bdd4af02d70434bad8c01233c60f70d7

>General description of the issue
Having posibrain prefferences set to no doesn't offer you to sign up for it when it's activated when your special role prefference for it is set to no.

>What you expected to happen
To recive a link that lets me sign up for the brain, but without it automatically signing me up for it.

>What actually happened
Nothing

>Steps to reproduce if possible
>Observe
>Wait for roboticist to activate the posibrain
>Recieve no sign-up link

**Comment by uazuaz** [comment]
i too have posibrain option set to "no", i just tried to enter a posibrain on the sever and it worked as usual; clicking the inactive posibrain made it ping, clicking the posibrain when active did let me join as a functioning posibrain.

are you sure you haven't set it to "never"?

**Comment by Shadowmech88** [comment]
>clicking the inactive posibrain made it ping, clicking the posibrain when active did let me join as a functioning posibrain

I believe he's requesting that setting the option to "no" would still cause the *prompt* for the posibrain to appear in chat, but that it would be opt-in as opposed to opt-out, so that you could ignore it or go AFK without getting sucked into a posibrain.

**Comment by uazuaz** [comment]
ah i see now. well that would be nice, yes.
EDIT: i just remembered that i opened a similar issue https://github.com/d3athrow/vgstation13/issues/7774

**Comment by Shaska-** [comment]
>he's requesting that setting the option to "no" would still cause the prompt for the posibrain to appear in chat, but that it would be opt-in as opposed to opt-out

That's exactly it.
It's how it used to work before the special role overhaul, and also the way the special role menu says it's supposed to work.

**Comment by SonixApache** [comment]
pls fix
