### ISSUE TITLE
nets

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13379]
work like bolas
 \- can only be thrown up to 2 tiles away
 \- do not fit in backpacks and have a very visible in-hand sprite
 \+ work as both handcuffs and legcuffs in one
 \- harder to get than bolas, maybe for raiders and other shitty antags

**Comment by Probe1** [comment]
From the ultra exclusive probe1/issues issue: Things players asked for in game:

>SHOCKY NET GUN
http://cdn.instructables.com/F22/LUDT/IJUAHFHF/F22LUDTIJUAHFHF.ANIMATED.MEDIUM.gif?width=614

**Comment by kilozombie** [comment]
https://github.com/d3athrow/vgstation13/pull/13366 
nat

**Comment by optimumtact** [comment]
LOOK AT THIS NET, THAT I JUST FOUND

**Comment by gbasood** [comment]
WHEN I SAY GO
TYPELESS LOOPS
🍆

**Comment by Probe1** [comment]
Go!
Go back to TG, not /vg/!

**Comment by Exxion** [comment]
Alright, that was a hell of a stretch

**Comment by west3436** [comment]
Not implemented
