### ISSUE TITLE
Deaf talisman and deaf sting are both SUPER FUCKING OBVIOUS to the victims

### ISSUE THREAD

**Issue by Allspice** [d3athrow/vgstation13#13376]
Both alert the victim with bold red text, which about fucks up any subtle applications of either. Would be better if it produced no message like mute sting.

**Comment by jakmak4** [comment]
do people even use deaf tailsmens? All it does is annoy your target while he still can yell HELP RAPE COLLECT VALIDS HERE NOW!

**Comment by SonixApache** [comment]
if you're masked you'll still yell out the magic words of a stun talisman, if your target somehow escapes they'll know your identity. not so much if deaf.
