### ISSUE TITLE
xeno eggs have too much health

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13370]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
they take like 15 toolbox hits to die

>What you expected to happen
4 toolbox hits

>What actually happened
a lot of hits

>Steps to reproduce if possible
hit a xeno egg with something

**Comment by jknpj** [comment]
is your toolbox heated?

`if(!W.is_hot())
		damage = damage / 4.0`

They have 100 health and take 1/4 damage of anything that's not hot because IT'S A FEEEEEEEEATURE

**Comment by clusterfack** [comment]
It sounds like you're saying we should buff the toolbox

**Comment by Exxion** [comment]
They do take a RIDICULOUS amount of damage to kill

**Comment by Probe1** [comment]
"I used the wrong tool for the job and it didn't work well please nerf"

**Comment by Aurx** [comment]
100 health is pretty silly considering how many a standard nest will contain.  And you have to get rid of them all or some dumbshit will accidentally or "accidentally" walk in and restart the xeno plague.

**Comment by Probe1** [comment]
It doesn't really create a balance issue in game and it helps slow down players and gives the queen time to relocate and create the next nest.  I don't see anything broken here to fix.  Except a user used the wrong thing to remove one.

**Comment by jknpj** [comment]
flamethrowers

**Comment by Exxion** [comment]
The right tool for the job is not something common enough for this to be reasonable.
A welder would still take 9 hits, if memory serves, and that would damage your eyes.
Anything that isn't a welder, plasma cutter, or esword of some variety takes way more.
Requiring a laser or esword to clear a nest in less than an hour isn't reasonable

**Comment by Probe1** [comment]
I really disagree about welders being uncommon, or xenomorphs being an everymans task to remove that should have even more common solutions.

**Comment by Aurx** [comment]
The issue is not that there's no solution.  
The issue is that cleanup after winning is something that shouldn't be a problem in the first place.

**Comment by Exxion** [comment]
I didn't say welders were uncommon
But that even welders, the "right" tool for the job, take nearly 2/3 as long as one of the strongest wrong tools for the job, which is still too long to be practical

**Comment by Gef21** [comment]
I once tried to fight off a small infestation as an engie borg and I used up an entire tank of welder fuel and had to go get more, how much health do people think would be good and should the damage resistance against non-burning be lowered? first reply wins

**Comment by Probe1** [comment]
how about increasing the fire damage multiplier then?

**Comment by Aurx** [comment]
I'd say to half the health and make them take extra damage from hot stuff instead of less damage from not-hot stuff.

**Comment by Probe1** [comment]
How about we quadruple their health but make toolboxes do 15x as much damage.
![1429494050709](https://cloud.githubusercontent.com/assets/8550416/21867183/0964fe12-d81b-11e6-8ce1-2313d943caf2.jpg)



(We've reached the point where the discussion has born fruit but the question is Will You Code It?)

**Comment by Gef21** [comment]
welders do 15 damage iirc so it would take 9 hits to destroy an egg with a 1.0 modifier, 4 hits to destroy with a 1.5 modifier and 4 hits to destroy with a 2.0 modifier but things like laser cutters and eswords would fucking destroy them

if we're halving the health then it would take 4 hits with a 1.0, 3 hits with 1.5 and 2 with a 2.0, toolboxes deal 15 force which right now is on a 0.25 which means they are hitting for a woeful 3.75 damage and will take 13 hits to destroy one, with a 0.5 modifier it would take 7 hits which I think is pretty good

Right now I'm voting for 1.5 hot damage and 0.5 not hot damage, with the eggs health reduced to 50, does everyone agree with that?

**Comment by Aurx** [comment]
It's literally three lines, I've already got them marked and know what to change them to.  The question isn't Will You Code It because the code is done, the question is Will Git Fucking Work Without Taking An Hour Of UI Bullshit.

**Comment by Aurx** [comment]
Or maybe the question is Will This Trash Campus Wifi Stay Connected Long Enough To Download Anything.

**Comment by Probe1** [comment]
BIG QUESTIONS.

**Comment by Aurx** [comment]
I've yet to see speeds higher than 120kb/s, and it's floating closer to 100.  It's been at 11% for six minutes.  I don't think this is happening on my end until I get home tonight.  

Fuck, now it's at 60 kb/s

**Comment by Aurx** [comment]
35

It's at fucking 35

RIP chances of getting a PR done on campus.

**Comment by Shadowmech88** [comment]
How well do flamethrowers perform at clearing out eggs?

**Comment by Zth--** [comment]
@Aurx do yourself a favour and learn the command line git
