### ISSUE TITLE
EVERYTHING IS FUCKED

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13371]
(WEB REPORT BY: gef21 REMOTE: 172.93.109.202:7777)
>Revision 1d79b779cd55d23fbb69aab09c80b7ae6ea1e51

>General description of the issue
Everything was fucked so I updated and now it is worse

>What you expected to happen
The chat and menues to come back

>What actually happened
The game screen went black but I got chat back, not sure about menues

>Steps to reproduce if possible
not a clue

**Comment by jknpj** [comment]
what the fuck gef

**Comment by Gef21** [comment]
Okay the round ended so I can post shit now

When the round started this was happening http://i.imgur.com/5RJfFxc.png so I closed it and updated it

now it looks like this http://i.imgur.com/Na7lywi.png

**Comment by Intigracy** [comment]
Revert to Build 511.1366

**Comment by Intigracy** [comment]
http://www.byond.com/download/build/511/511.1366_byond_setup.zip
