### ISSUE TITLE
pAI mulebots need a revert or nerf

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#13387]
It's a 0TC Syndie wheelchair, that is now making an appearance every round

**Comment by Intigracy** [comment]
Everything new and shiny always makes an appearance every round for a while.

**Comment by N3X15** [comment]
See #13386.

**Comment by N3X15** [comment]
cc #13389

**Comment by SonixApache** [comment]
Doesn't the HoP's PDA cartridge let you shut down mules remotely like the cargo PDA cartridge does?

**Comment by AutismSpider** [comment]
@SonixApache Yes and you can emp the mule to drain the cell or out right kill the pAI if it does not buy emp  shielding

**Comment by JustSumBody** [comment]
Hi
http://puu.sh/tiiaJ/01e35f67df.webm

**Comment by AutismSpider** [comment]
Crush delay got in Spike strips would be nice to have to deal with other like the clown cart etc and mule bots if one gets to out of hand

**Comment by Intigracy** [comment]
Who the fuck ACTUALLY uses the say verb instead of just typing it in the chat box

**Comment by SysadminJeroen** [comment]
ooc I do.

**Comment by Zth--** [comment]
I was that pAI. Sad to see I'll be the only one to experiment such fun with mulebots

**Comment by Shadowmech88** [comment]
Admins can still varedit MULEbots to remove the implemented crush delay.

**Comment by jknpj** [comment]
Already nerfed.
