### ISSUE TITLE
computer frame constrction problems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13398]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
if you fuck up one of the steps to build a computer like moving away while wrenching the computer frame becomes unusable, you cant wrench it again or anything, same for other steps that require you to stand still

>What you expected to happen
being able to construct a computer
>What actually happened
computer frames that cant be interacted with

>Steps to reproduce if possible
make a frame, start wrenching , move away, try wrench (same problem for other steps)

**Comment by jknpj** [comment]
Strange.

**Comment by Exxion** [comment]
Sounds like a runtime
Porting things to construction datums when?

(When construction datums get some required functionality they don't have, like optional steps and branching paths)

**Comment by ComicIronic** [comment]
Branching paths can be done by multiple consecutive datums. I still have to revisit optional steps, but it was a pain to try and implement the first time around.

**Comment by DamianX** [comment]
Fixed by #16138
