### ISSUE TITLE
I'm on fire.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13393]
(WEB REPORT BY: zubron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
15faae975d693a7f42ec4f629c3dde1cfaf20587

>General description of the issue
My toon's sprite is on fire. It doesn't do any damage, and nothing (fire extingushers, a sec officer with a fire extingusher, water, etc) can make it go away.

>What you expected to happen
To only be on fire for a bit.

>What actually happened
I'm on fire forever.

>Steps to reproduce if possible
I accidentally lit the bar on fire on the metaclub map while trying to burn Pun Pun to death. 
I put on a fire suit, dropped a lighter on the ground and sprayed Pun Pun with a fire extingusher filled with welding fuel.
The entire place quickly went on fire because it's wooden, I caught on fire, and slowly started dying, then a borg opened a door to the maint tunnels and I got pressure blasted out. After that, I was on fire forever.

**Comment by ghost** [comment]
Yaay overlays

Also holy crap that's a specific way to reproduce the problem

**Comment by Exxion** [comment]
I've had that happen in the past, though the circumstances around it were totally different. I just ignited myself with a pie tin and resisted. Which usually works just fine, but one time it didn't, and I visually remained burning until I later did it again and fixed it.

**Comment by JustSumBody** [comment]
>toon

**Comment by Intigracy** [comment]
Toontown woooooo

**Comment by Kurfursten** [comment]
@Exxion Did you fix this?

**Comment by Exxion** [comment]
Not as far as I know

**Comment by SonixApache** [comment]
This is still a thing as far as I know. It's funny, because if you hand these burning people a cigarette and light it their false flames become true flames.
