### ISSUE TITLE
Dummy AI cores like ALICE at CentComm pollute check-ai-laws

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13397]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
SOMETHING SILICON *no key*/(A.L.I.C.E.)'s laws:

*no key*/(A.L.I.C.E.)'s laws are null?? Contact a coder.

**Comment by jknpj** [comment]
muh immulsions

**Comment by gbasood** [comment]
mindless silicons should probably not show up
Mindless mobs are mobs that have never had a client so it's our best tool here I think

**Comment by Kurfursten** [comment]
Is there any reason that ALICE at centcomm shouldn't just be a riveted wall with the AI core sprite?

If admins want to do stuff at centcomm they can do all AI functions with aghost

**Comment by Probe1** [comment]
I suppose the answer to that would be to maintain the illusion.  We're all old and nothing is magical to us but to new players, there is an illusion that people are actually at Centcomm doing stuff.  Even for old players we still maintain a roleplaying element for ERT/Deathsquad instead of just dropping them in an austere room and teleporting them to the station via admin tools.

**Comment by Kurfursten** [comment]
Sure but does ALICE actually need to be an AI object? If it looks and is described right, you wouldn't know the difference, unless someone wants to put a mind in it

**Comment by Exxion** [comment]
Wasn't ALICE just a dummy object some time in the past?

**Comment by jknpj** [comment]
simple AI for GlaDOS and A.L.I.C.E. when?

**Comment by Aurx** [comment]
ALICE used to be a dummy object.  No clue why the hell it was made an actual AI, but it's a mapping issue unless the dummy object was coded out.  

What map was this?

**Comment by Probe1** [comment]
Probably all of them.

**Comment by Intigracy** [comment]
It's been an AI for as long as I can remember.

**Comment by Sprok0** [comment]
It's actually a decoy AI, /mob/living/silicon/decoy
One of these used to be in the AI core during malf, where the actual AI was moved to the malf satellite

**Comment by Probe1** [comment]
Needs a

```
 if 
 /mob/living/silicon/decoy
return
```
