### ISSUE TITLE
The entire powernet failing random event doesnt have a badmin button

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#13391]
Not the one that blows lights out. The one that makes a black out for a few minutes.

Can't badmin it.

**Comment by Probe1** [comment]
It did and it was removed and I don't know why.

**Comment by mrpain666** [comment]
It was broken and no one fixed it

**Comment by JustSumBody** [comment]
Might have been removed when wad diddled with the secrets panel, he pruned some obsolete buttons
in #12135
I could swear though that was the "make all areas unpowered" button which is still there, no?

**Comment by mrpain666** [comment]
My bad it's the "make all areas unpowered" button

**Comment by Aurx** [comment]
You can do everything it does with SDQL anyways.

**Comment by Probe1** [comment]
god don't encourage people to SDQL query we accidentally the serb often enough

**Comment by mrpain666** [comment]
Celt's gone no one does that often anymore

**Comment by Aurx** [comment]
That sounds like a challenge to me!
