### ISSUE TITLE
StonedMC issues

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13405]
- [ ] Lighting on station turns on before round start.

**Comment by Iamgoofball** [comment]
is the lighting really an issue?

better it turns on before the round starts than it turn on while it's also processing spawning everyone and making roundstart take longer

**Comment by PJB3005** [comment]
Seems to eat a bit of battery from the SMES so yes.

**Comment by Iamgoofball** [comment]
Hm

**Comment by JustSumBody** [comment]
Does this mean deff runs out of power before round start now

**Comment by PJB3005** [comment]
.... No

**Comment by gbasood** [comment]
I don't see the lighting as a real problem

**Comment by 9600bauds** [comment]
Would it be possible to set station time to 12:00 when the round starts [feachur request]

I seriously can't believe it wasn't like that before

**Comment by Probe1** [comment]
It's not really an issue since the APCs and machines aren't initializing so power isn't drained.

But its good to note.

**Comment by gbasood** [comment]
@9600bauds pretty sure we could have done that since forever ago

**Comment by Probe1** [comment]
You've been notified already but might as well write it down - map votings super fucked.  It produces several results with different amounts of votes.

**Comment by Iamgoofball** [comment]
oh yeah we re-did map votes to be based on a pref in the user for favorite map and it's weighted around that

**Comment by Zth--** [comment]
Favorite map? If box is your favorite map it doesn't mean you want to play it 24/7. You don't eat sushi everyday because it's your favorite plate. Or whatever, I don't like sushi.

**Comment by MrsTonedOne** [comment]
its random weighted by vote percentage.

so a map with twice as many votes as other maps gets randomly picked for the next map twice as often.

**Comment by Exxion** [comment]
Yeah, that's how ours works too. But we actually vote each time rather than just once

**Comment by Probe1** [comment]
For the record the voting has been fixed.  @PJB3005 did an excellent job porting it and @MrStonedOne did an excellent job coding it and the nameless tg contributors did an excellent job fixing the bugs MSO probably made :^)

**Comment by Shadowmech88** [comment]
I believe this can be closed.
