### ISSUE TITLE
Humant mutantraces don't react well to being turned into slimepeople

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13401]
Slimepeople are shit because they don't have their own species datum, just hackish code. A Diona ate mutationtoxin, the result was: a Diona still looking like a Diona, being slow as a Diona, having Diona regeneration, but having SOME slimepeople traits such as being slow when fed hyperzine (which was particularly devilish)

**Comment by Shadowmech88** [comment]
The best fix for this is giving slimepeople the golem treatment and making them a proper race.

**Comment by Intigracy** [comment]
This is because slimes are a mutantrace, not a species.

Mutantraces are just dumb.

**Comment by Ephx1** [comment]
> being slow when fed hyperzine

Someone, please, I beg you, make this a normal diona feature.

**Comment by 9600bauds** [comment]
The funny thing is that this Diona got himself killed and cloned to try to fix it but his DNA was forever modified 🎉

**Comment by MadmanMartian** [comment]
Slimepeople are their own race now. This is fixed
