### ISSUE TITLE
Sometimes Chat freezes randomly

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#13415]
So after Nexis new update, it would seem chat can randomly freeze and stay frozen until a client restart.

Pressing pause and unpause didn't fix the issue, I wish I knew more about what caused it but it happened mid round when I was alt tabbed.

**Comment by TheFriggenSawbones** [comment]
oops the revert pr went up right after

**Comment by N3X15** [comment]
Reverted
