### ISSUE TITLE
Let's modernize this fucking codebase. ECS and interfaces how?

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#13429]
Ok. How has nobody coded an ECS and interfaces yet?

# Interfaces

Pretty simple stuff, you define a contract for what a type does but leave the implementation up to the type. If you don't implement the contract correctly it won't even compile.
BYOND doesn't support this natively because of course, but we can at least replicate a bare bones system. Issue is I'm not entirely sure whether it's feasible to do performantly and neatly at the same time.

Current idea I've got so far is the following:

```dm
// How this works is that implementing an interface defines a proc on the type equal to the interface name.
// Then we can do a really damn cheap lookup.
#define hasinterface(object, interface) hascall(object, "[#interface]")

// Need a generic name for reasons of being clean.
#define IINTERACTABLE IInteractable

// This, when correctly used, defines the proc checked by hasinterface.
// The proc tries calling the interface methods and will fail compile if any are undefined.
// Should be extendable to vars too *whoop*
// No non clumsy way to automate this sadly.
// This proc should NEVER be called directly!
#define IMPLEMENTS_IINTERACTABLE proc/IINTERACTABLE { \
	attackby(); \
	attack_hand(); \
}

// Define a generic interface type for casting and documentation purposes.
// Actually irrelevant to the correct functioning of the above macros and defines.
/IINTERACTABLE/proc/attack_hand(var/mob/user)
/IINTERACTABLE/proc/attackby(var/obj/item/W, var/mob/user)


// Example
/obj/thing
	name = "thing"
	...

	// Define that we implement the interface.
	IMPLEMENTS_IINTERACTABLE

// Implement the procs.
/obj/thing/proc/attackby(var/obj/item/W, var/mob/user)
	world << "Ouch!"

/obj/thing/proc/attack_hand(var/mob/user)
	world << "Honk!"


// Example usage.
/client/Click(var/atom/object)
	if (hasinterface(object, IINTERACTABLE))
		var/interface/IINTERACTABLE/I = object
		I.attack_hand(mob)
```

This method has a lot of boilerplate to defining interfaces but should hopefully be very boiler plate free for implementing them.
Other solution I've seen can't be checked at compile time and aren't as fast to check whether the object implements an interface.

# ECS

TODO: need brainstorming can't decide on a syntax yet.

**Comment by PJB3005** [comment]
Assigning N3X and Comic because they're probably gonna be able to provide some insight and brainstorming on the best way to pull this off in BYOND.

**Comment by ghost** [comment]
Okay, let's lay the groundworks

What the fuck is an ECS?

**Comment by PJB3005** [comment]
Entity Component System.

AKA what engines like Unity and UE4 have.

**Comment by Exxion** [comment]
The interfaces thing seems doable, but I really don't think composition is possible in BYOND without awful performance

MAYBE something hackish with macros?

**Comment by PJB3005** [comment]
No performance critical systems.

That simple

**Comment by Exxion** [comment]
Disgusting

**Comment by Exxion** [comment]
OK actually
Why do we even need both ECS and interfaces? I'm talking out my ass as usual, but aren't they basically slightly different solutions to the same problem?

**Comment by PJB3005** [comment]
@Exxion interfaces is "I can do this thing, let me handle it.", ECS is "I want a good standardized way of doing a common task"

You might have a button. It implements an interface to allow it to receive interaction events, but you also need a radio connection component to send radio messages when the button is pressed.

**Comment by Exxion** [comment]
You know, maybe composition with macros and thus without too big a performance hit is possible
Or at least limited composition

**Comment by Shadowmech88** [comment]
If I'm understanding this correctly, would this allow for two different objects without a common parent to share a behavior without copying+pasting that behavior into both of them, by putting it into a component and giving both objects that component?

**Comment by Exxion** [comment]
That's the idea

**Comment by Shadowmech88** [comment]
That's really neat.

**Comment by Exxion** [comment]
At an absolute minimum, we could just throw the vars and procs necessary for certain common behaviors into a macro, then just stick that macro in the type definition of anything that needs that functionality
Inelegant, but effective and minimal effect on performance

**Comment by Exxion** [comment]
Example for macro-based composition I wrote up in the Discord:

It's based heavily on the interface example in the OP.
The scenario is the cell-draining artifact. The loop at the end signifies this.
This is probably not fully syntactically correct, but it gets the idea across.
```
#define has_component(object, C) hascall(object, C)

#define COMP_CELL_HOLDER proc/COMP_CELL_HOLDER(){return};\
    var/obj/item/weapon/cell/cell;\
    var/other_relevant_vars;\
    proc/relevant_procs()

/cell_holder //A dummy type with ONLY the vars/procs of the component. If you want to access a var/proc on something only knowing that it has this component, typecast it as this.
    COMP_CELL_HOLDER

for var/atom/movable/AM in view()
    if has_component(AM, "COMP_CELL_HOLDER")
        var/cell_holder/CH = AM
        CH.cell.use(50)
```

Compared to datum-based composition:

Pros:
* Negligible performance cost (Biggest pro)
* Referencing the variables/procs is simpler
* A bit easier to include a component in an object definition
* No cleanup of datums is required on object deletion

Cons:
* Components can't be added/removed at runtime (Biggest con)
* Due to reliance on multi-line macros, syntax is a bit awkward
* Conflicting var/proc names are a bit harder to catch
* Disgusting typecasting for accessing the components' procs/vars
* muh absolute pathing

**Comment by PJB3005** [comment]
Sounds like a plan.

**Comment by PJB3005** [comment]
Problem is that defining procs for those components will absolutely suck because it's all in a single macro.

**Comment by Exxion** [comment]
Eh. Pretty much like JS except with mandatory semicolons, with added backslashes

**Comment by Exxion** [comment]
Could even write a script to convert a normally-written proc to that format

**Comment by PJB3005** [comment]
@Exxion a lot of this logic can get really complex. I'd rather not.

Having to write the entirety of reagent holders like that would be pure terror.

Also an issue being namespacing.

**Comment by Exxion** [comment]
All a script would have to do is put semicolons and backslashes in and add braces where the tabbing changes

**Comment by PJB3005** [comment]
That's too painful.

**Comment by N3X15** [comment]
Now a work in progress, assigned to Components project.
