### ISSUE TITLE
Defficiency disposals pipe missing outside courtroom

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#13422]
#### Description of issue
@Probe1 there's a disposals pipe missing outside the courtroom.
![location of missing pipe](https://puu.sh/tjCNY/37ab04e9f2.png)

#### Server revision
1eb193efef8916e122e77a281d286a7562ededd7

**Comment by Probe1** [comment]
Oh yeah I know about that one https://github.com/d3athrow/vgstation13/issues/13279

But thank you for being diligent and reporting both.  It's my fault for not saying so.
