### ISSUE TITLE
Warden hat is invisible on greyliens.

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13424]
de factor repeat of @13363 for the other security head role

inb4 I'm going to have to add an individual report for every job type's hat

**Comment by kol1th** [comment]
most of them should work tbh

**Comment by Kitfox88** [comment]
a ton of hats look like shit on vox too but that's probably not an easy fix since their head shape is so wierd and it's not as easy as offsetting the sprite, i'm guessing

**Comment by Gef21** [comment]
I tested it a bit and it looks like it's all tactical helmets that don't work on grayys

**Comment by kol1th** [comment]
@Kitfox88 It's as easy as just editing as sprite that fixes it, adding species_fit = VOX_SHAPED or whatever it is, and adding the sprite to the vox/hats.dmi

**Comment by Kitfox88** [comment]
oh, maybe i should get off my ass and try spriting some fixes
