### ISSUE TITLE
Proposed Rework for Revolution

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13423]
As discussed idly in OOC with N3X15 : 

New Conversion/Deconversion Mechanic : 

- Remove the ability of flashes to convert people from the game (and clean up the code in the process, I guess)
- Change the conversion item to an "earpiece hacking tool". Could be concealed or blatant. It is re-usable, so one per rev head at the start
- The earpiece hacking tool works instantly on earpieces and encryption keys that are not worn (Just plug it in and fuck with the encryption key) and takes a silent but long (3-5 seconds) interaction when next to a target with an earpiece and without a headgear that covers it (aka hardsuit helmet or combat helmet)
- Hacking a headset adds a special rev channel (technically Syndie channel) to the earpiece and toggles a special brainwashing function to it, instantly turning the target into a Revolutionary. The headset still looks perfectly functional to the casual eye. The decryption key is attached to that Rev, and will stay so for as long as the key is in one piece
- Loyalty implant makes one immune to the effects of brainwashing, although their headsets can still be hacked (which is obviously a bad idea since they'll start hearing the rev channel)
- To deconvert a target, just stripping or removing the headset isn't enough. You have to destroy either the headset or the earpiece. Loyalty implant would still deconvert, so getting rid of your earpiece to "be invincible" will lead to you losing track of your team (and the station in general if you're stupid enough to not pick up a new one) and easily getting deconverted
- Potentially, removing your brainwashing headset could seriously fuck with you (something like withdrawal or slowly going insane). Just need to be careful about potential meta checking options created this way

Anti Greytide Measures : 

- Perhaps limiting the amount of hacked earpieces attached to a single hacking tool to somewhere around 1 to 3. Maybe even add basic widgets like being able to self-destroy the earpiece if the operative got caught (could do anything from just totaling the headset, to a small explosion capable of lethally wounding the operative and wounding anyone right next to him to prevent him from ratting out) and detecting who is wearing them and being able to subtle message them and track their rough location (X, Y, area), just like a tracking implant
- If you put on a headset already attached to a Rev, it should probably do nothing. If that Rev gets deconverted, it might instantly recheck and convert you, so this is a VERY unsafe idea

This, coupled with the recent changes allowing the shuttle to be called during Revolution to end the round, should make the gamemode fun and prevent endless stalemates between the Greytide Commune and the Fuhrerbunker

**Comment by Ephx1** [comment]
This just makes it seem tons easier for revs to win if their conversion process is even stealthier

**Comment by yclatious** [comment]
Maybe its just me, but preventing the tide, one of the core aspects of how a revolution works, seems backwards. Other than that, sounds good on paper, hope it works on pratice.

**Comment by Exxion** [comment]
>Can't convert through helmets

Congratulations on making vox and plasmamen nigh impossible to convert again

**Comment by ghost** [comment]
So, rather than clicking on people, you just follow em?

**Comment by Kurfursten** [comment]
Make a new issue relevant to datums if you still believe in this idea and plan to code it
