### ISSUE TITLE
clown shoes, crayons and washing machines

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13425]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
if you paint clown shoes (by putting them in a washing machine + colored crayon) it will turn the shoes of the crayon color but they ll still make the clown shoes sound

>What you expected to happen
not really sure maybe no clown noises
>What actually happened
yellow shoes that make clown noises
>Steps to reproduce if possible
put clown shoes with a crayon in the washing machine, wear the shoes and go around making clown shoes sounds

**Comment by Kitfox88** [comment]
stealth clowning

**Comment by Intigracy** [comment]
Honestly I hope this is never fixed.
