### ISSUE TITLE
ok lets figure out why antag preferences aren't saving

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#13433]
Lets  FIGURE THIS OUT BOYS

http://i.imgur.com/XhCF8r7.png

I hit submit

after 30 seconds I hit save

I did this from the settings dropdown menu.

Will report back with what happens when the serb restarts

**Comment by TheFriggenSawbones** [comment]
also clearing the byond cache did not fix this

**Comment by Gef21** [comment]
same, I also can't be a posibrain because of this

**Comment by TheFriggenSawbones** [comment]
OK so my preferences saved, could it be the submit button is fucky? Was I the biggest mistake of 2016/2017?

**Comment by kilozombie** [comment]
The submit button hasn't worked for me since November.
Even when it did work, it resets whenever you save other preferences for most people, and was reported in a different issue.

**Comment by despotate** [comment]
The submit button works for me.

Usually the process is:

1. Change job preferences
2. Save preferences
3. Go to the special roles page, notice how all the roles are filled
4. Restart the client
5. Oh, look the special roles weren't actually filled and they just reset
6. Se the special roles by clicking submit

Just looking at the messages you get in the chatbox the proximate cause appears obvious; saving job preferences gives you the standard four black lines, saving special preferences gives you the standard four black lines + a ton of blue lines, one for each special preference. So saving normal preferences probably simply doesn't save special preferences, which resets it.

**Comment by SonixApache** [comment]
@clusterfack PLEASE

**Comment by Intigracy** [comment]
They ARE saving, they just don't show your preferences correctly when you re-open it.

All of them show as no, right?
