### ISSUE TITLE
cyborg's radio

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13448]
#### Description of issue
i noticed that borg's radios are like bounced radios; for example, when a secborg receives a radio message on the sec channel all nearby people can hear it.
in my opinion their radio should be like earpieces and let radio messages be heard by the borg only.

#### Steps to reproduce 
stand near a borg, wait for him to receive a message on a channel that isn't on your earpiece

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Intigracy** [comment]
Borg radios ARE bounced radios.

**Comment by uazuaz** [comment]
are they supposed to work this way? is there a reason for people around being able to hear everything said to borgs?

**Comment by Kitfox88** [comment]
fuck silicons is my guess but probably also shitty oldcoding?

**Comment by Intigracy** [comment]
The reason you can hear it is because it's a bounced radio.

Whether or not you should be able to is this discussion, not why you can.

**Comment by Aurx** [comment]
It's a FEAAAATUUUUUUUUUURRRE
Or at least a lingering remainder of one
