### ISSUE TITLE
Can't Zoom in as a ghost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13441]
(WEB REPORT BY: agentofzog REMOTE: 172.93.109.202:7777)
>Revision  ff09c947fb82a7446fb5aa1c15ca532273acb57b 

>General description of the issue

Attempting to zoom in as a ghost doesn't work, you just get black borders. Zooming out works fine.

>What you expected to happen
See all those pixels up close

>What actually happened
Just get some black borders

>Steps to reproduce if possible

be ghost
touch the mousewheel

**Comment by Probe1** [comment]
It's some setting I forget what that does that.  Might be stretch to fit.

**Comment by Probe1** [comment]
People are insisting its a bug but fuck if I know how that could have changed suddenly.

**Comment by Ephx1** [comment]
64x64 and the others will create only borders
Stretch to fit should zoom in properly

If it doesn't work like this, then it's probably a bug or something

**Comment by Exxion** [comment]
Set it to stretch to fit

**Comment by Exxion** [comment]
There was some relatively recent change that made it so that trying to zoom in while your view range is already 1 resets it to default, but I don't think that's what he meant

**Comment by Probe1** [comment]
I can reproduce it on live but not locally.

**Comment by uazuaz** [comment]
on the test server (not updated) it works  zooming like intended; on live server the picture just shrinks adding black borders.
set on "stretch to fit" both cases.

**Comment by Exxion** [comment]
Haha what

**Comment by ComicIronic** [comment]
Sounds like an effect of the Byond version.

**Comment by Probe1** [comment]
I'm using the same version of byond as the server..

**Comment by uazuaz** [comment]
i haven't changed byond version between the 2 tests.
i'm on the latest stand-alone stable by the way.

**Comment by ComicIronic** [comment]
I meant "it sounds like the test server and live server are on different Byond versions".

**Comment by Exxion** [comment]
@PJB3005 Could this be caused by your recent secret repo stuff?

**Comment by PJB3005** [comment]
@Exxion not at all.

**Comment by Exxion** [comment]
Well, do you have another explanation?

**Comment by PJB3005** [comment]
Nope.

Unless BYOND absolutely shits the bed with screen objects which I highly doubt.

**Comment by Shadowmech88** [comment]
Tested on live, zooming in while on stretch-to-fit works as expected. The black borders that appear while on other display modes are a BYOND thing.

**Comment by Exxion** [comment]
I'm pretty sure it actually *was* PJB's secret repo stuff, which has been broken for months
