### ISSUE TITLE
Having your carrier gibbed as an intellicard nullspaces you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13444]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
f97aef46c79ca78b3d6aa6ef813c85a68313340a 

>General description of the issue
I was in some guy's backpack as an intellicard. Guy got gibbed. I got nullspaced.

**Comment by SGuivenne** [comment]
Didn't this bug get resolved or reported semi recently?

**Comment by DamianX** [comment]
Closing in favor of #16710
