### ISSUE TITLE
Printing Talismans in Photocopiers make said Talismans invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13453]
(WEB REPORT BY: smallboss REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
fa28f61f0d5e8ea58b19f4893e607120ab8466b5

>General description of the issue
Cult papers can be made invisible by copying them in a photocopier

>What you expected to happen
The cult paper I have put in the printer would normally get copied

>What actually happened
The paper got copied, but it is completely invisible and still has it's functions

>Steps to reproduce if possible
Put cult talisman in printer
Print
Rightclick or Altclick to see that a invisible paper has been printed

**Comment by jknpj** [comment]
How are you able to multiply a talisman's power with a photocopier when they need bloody runes to make them have power in the first place?

**Comment by Allspice** [comment]
MAGIC

**Comment by JustSumBody** [comment]
Librarian op please nerf

**Comment by Blithering** [comment]
Nanotrasen brand toner is 50% blood.

**Comment by Kitfox88** [comment]
toner is actually the blood of an unknown alien species

**Comment by 9600bauds** [comment]
Explains why it's so expensive

**Comment by Probe1** [comment]
The oversight here fwiw is you can photocopy talismans.  Not that photocopiers have an innate ability to perform eldritch blood magic.

**Comment by SonixApache** [comment]
toner is the blood of space squid
which explains why we only get space carp and not space squid

**Comment by Probe1** [comment]
I have this odd dream of coding space jellyfish.  All they do is float around the exterior of the station harmlessly.  Idk it seems nice to me.
