### ISSUE TITLE
There need to be some tweaks to lighting to make flares and bioluminescent plants less of an eyesore when a room is already lit

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13451]
See pics related. Basically,
- Having lots of bioluminescent growns / flares together in one spot makes a room that's already lit with white lights _darker_ and makes your eyes strain much more, because they're not really adding luminosity so much as stealing it from the room's lights
- Even when they don't make it darker, the hue gradient looks just goddamned awful, it really makes you not want to plant any bioluminescent growns when it means that you'll have to play the rest of the shift with a terrible, unaesthetic, eyesore green/blue/orange tint on your screen
- Fuck man, you gotta play the role to understand it, having a fridge glow in that genuinely disgusting color just makes you want to blow up the whole place

![botany1](https://cloud.githubusercontent.com/assets/22053715/21928700/4d7c88b4-d95a-11e6-8827-45aea3dcb3d7.PNG)
![botany2](https://cloud.githubusercontent.com/assets/22053715/21928702/4d7d079e-d95a-11e6-8c8b-69f5944894c0.PNG)
![botany3](https://cloud.githubusercontent.com/assets/22053715/21928701/4d7cbabe-d95a-11e6-92aa-707fddbdef2c.PNG)
![botany4](https://cloud.githubusercontent.com/assets/22053715/21928699/4d7c624e-d95a-11e6-848d-e42ef6f56b5e.PNG)
![botany5](https://cloud.githubusercontent.com/assets/22053715/21928703/4d7d650e-d95a-11e6-807c-55e3c92ef6e7.PNG)
![botany6](https://cloud.githubusercontent.com/assets/22053715/21928704/4d7d9646-d95a-11e6-9266-bd3a3c090484.PNG)
![botany7](https://cloud.githubusercontent.com/assets/22053715/21928708/4d892c5e-d95a-11e6-95a9-7769ac11fb28.PNG)
![botany8](https://cloud.githubusercontent.com/assets/22053715/21928707/4d890918-d95a-11e6-9ad7-7410d141bcc1.PNG)
![botany9](https://cloud.githubusercontent.com/assets/22053715/21928706/4d8740e2-d95a-11e6-8bec-f615b6156455.PNG)
![botany10](https://cloud.githubusercontent.com/assets/22053715/21928705/4d87111c-d95a-11e6-8a05-c7b7b05a4b4d.PNG)
![botany11](https://cloud.githubusercontent.com/assets/22053715/21928709/4d896520-d95a-11e6-9cb5-56ad287124c4.PNG)

Possible solutions:

- Vastly decrease the strength and radius of the light a plant emits if it's bioluminescent
- Somewhat decrease, if at all, the strength of light that bioluminescent growns emit
- Vastly decrease the strength and radius of bioluminescent growns' light when inside a fridge (especially considering how many you'd stuff in a fridge over the course of a shift)
- Maybe decrease the strength of a flare too

**Comment by Blithering** [comment]
The fridge change would be good, but the other ideas kinda majorly affect what the luminescence is meant for, lighting up dark areas.

**Comment by despotate** [comment]
Whether or not luminescence is meant to add light to dark areas doesn't affect the fact that they effectively remove it from lit areas with the worst hue and gradient you could possibly think of.

The most important change I'd be asking for is to make bioluminescent plants have a strength and radius of light emission equal to what their harvested growns have, as you can see in the above image, their growns have much more reasonable lighting than the plants.

**Comment by Kurfursten** [comment]
Splicing off bio-luminescence is completely trivial if it bothers you.

I agree with the fridge change though, but otherwise I'm with Blithering.

**Comment by 9600bauds** [comment]
The ACTUAL problem here is that stacked light sources only increase the luminosity amount but never the luminosity radius. This is why 30 stacked shrooms look like a tiny concentrated ball of green, and I suspect MAYBE wrong color averaging: https://youtu.be/LKnqECcg6Gw

And also apparently you don't like that flares are flare-colored which is a completely different thing

**Comment by ComicIronic** [comment]
I'm pretty sure we corrected color averaging to use the root average for that reason.
