### ISSUE TITLE
the cargo layout is meta is inefficent

### ISSUE THREAD

**Issue by pvak** [d3athrow/vgstation13#13450]
#### Description of issue
moving many crates to disposals require too much time

http://imgur.com/a/qAyZu

red arrows is the current path you have to unload a crate
green arrows is a suggestion for a better path (maybe make the coveryors go more south to unload right into the disposals belt 

#### Difference between expected and actual behavior
optimized set up

#### Steps to reproduce 
be in meta
have a not optimized cargo unloading set up

#### Specific information for locating

cargo in metaclub

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
The meta setup is actually really similar to the original Box layout (walk through two doorways, travel about the same distance), but when I fixed mail a long time ago I added the easy-chute to Box

**Comment by Probe1** [comment]
time for drunken mappeng
