### ISSUE TITLE
there is no sanity check when installing pAIs to see if there was already a pAI loaded, which results in the new pAI overwriting the old one

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13469]
Henketh

Seen with a pAI being loaded into a medibot that already had a pAI

**Comment by Zth--** [comment]
There are also runtimes if you insert an empty pAI in a bot

**Comment by PJB3005** [comment]
@Shadowmech88 ruh oh.

**Comment by Shadowmech88** [comment]
>There are also runtimes if you insert an empty pAI in a bot

Medbots specifically?

**Comment by Zth--** [comment]
No, mulebots too. It's an easy fix though, the pAI framework needs some sanity
