### ISSUE TITLE
Need sprites for pAI medbots and mulebots

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#13468]
I can add them if needed, but sprites would be nice

**Comment by ComicIronic** [comment]
Please be more descriptive : what needs spriting?

**Comment by AutismSpider** [comment]
When a medbot and mule bot have  pAI in them.

**Comment by Zth--** [comment]
There's already a sprite for medbots.
I'm requesting a sprite for medbots when there's a pAI inside. And mulebots too.

**Comment by Probe1** [comment]
Make sure to ping the spriters in discord.

**Comment by SonixApache** [comment]
And loaded smartguns.

**Comment by Shadowmech88** [comment]
If we wanted a sprite change that would be obvious, yet not ruin *immulsions*, we could just overlay a holographic-looking image of the pAI's face over the object's sprite, like it's projecting it out of the integration slot.

**Comment by AutismSpider** [comment]
it be funny as mule bot with cat face overlay runs people down

**Comment by Blithering** [comment]
Giving this a go, having trouble getting the different scales looking any good
![paibots](https://cloud.githubusercontent.com/assets/15067109/22084623/ba8acef8-ddc8-11e6-91c3-f996e0e90d61.png)

**Comment by PJB3005** [comment]
Problem with that MULE is that the pAI thing is obscured when a crate is on it. 

The smart gun and medibot look great though!

**Comment by Blithering** [comment]
Sorry for the massive delay, completely forgot about this
http://s000.tinyupload.com/index.php?file_id=00897317410207433584 Download link for sprites, pAI mules and medibots also change the bot's light colours to blue to make it more obvious there's something in there. I can't code for toffee so I'm gonna have to hand this off to whoever feels like it
