### ISSUE TITLE
Easy Spritework: N2 Closet

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#13462]
For years, the Vox outpost has had alternate O2 lockers that instead contain only N2 tanks and Vox breath masks. If you're a new contributor looking to cut your teeth on something easy, this is about as simple as it gets -- recolor an existing locker and change O2 to N2.

You can find O2 lockers under utility_closets.dm, look for /obj/structure/closet/emcloset/vox and simply set the icon states for open and closed to the names you've given the new sprites in closets.dmi (this is the same icon file where the O2 locker sprite is used).

**Comment by Shadowmech88** [comment]
We should probably get an [Easy Feature Request] tag to mirror our [Easy Fix] tag.

**Comment by ghost** [comment]
Is this good enough? 

Version with the closed locker being normal, but opened looking broken:
![emergencyvox](https://cloud.githubusercontent.com/assets/17911005/21956319/a75bb006-da7e-11e6-819d-7cde4bb8b781.png)
![emergencyvoxopen](https://cloud.githubusercontent.com/assets/17911005/21956336/d7411b4e-da7e-11e6-871c-3fbed88fa3eb.png)
Version with both sprites seeming broken:
![emergencyvox2](https://cloud.githubusercontent.com/assets/17911005/21956359/543404a4-da7f-11e6-8f15-998ec40e901d.png)
![emergencyvoxopen](https://cloud.githubusercontent.com/assets/17911005/21956362/588958d8-da7f-11e6-9f44-22a86c7f8bb0.png)
Version with both sprites looking like normal lockers:
![emergencyvox2](https://cloud.githubusercontent.com/assets/17911005/21956415/8029b670-da80-11e6-8ccb-e893d739304c.png)
![emergencyvox2open](https://cloud.githubusercontent.com/assets/17911005/21956417/8920f612-da80-11e6-9661-cf28555fb5d5.png)

**Comment by Kurfursten** [comment]
Looks nice, and I'm glad to see someone new getting in on this.

**Comment by ghost** [comment]
Alright, I will probably just use the broken version since vox and all.

**Comment by ghost** [comment]
Here is a better one I worked on (and it fits in more ways than one because it's just a reskin of the firelock closet)
![emergencyvox3](https://cloud.githubusercontent.com/assets/17911005/21956805/fa8ad3ec-da88-11e6-8a22-ad5e46e91cc3.png)

**Comment by ghost** [comment]
https://github.com/d3athrow/vgstation13/pull/13466
