### ISSUE TITLE
inscrutable space ZAS

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13471]
![2017-01-15_00-01-22](https://cloud.githubusercontent.com/assets/6526157/21961330/d71cb594-dae5-11e6-9a8f-415318dfe717.gif)
it stopped after the middle section between the two windows was floored and walled off

**Comment by Probe1** [comment]
Amazing

**Comment by 9600bauds** [comment]
Honestly out of the 2.5 people on this Earth that know how ZAS works, none of them can probably figure this out just from the gif so close this in 23hrs

**Comment by clusterfack** [comment]
Its a conflict between inertial flow in space and airflow which targets a particular tile to move to, though I was pretty sure I fixed it unless someone redid either inertia in space or airflow.

**Comment by ComicIronic** [comment]
Isn't the issue that airflow isn't modifying space inertia, then?

**Comment by Exxion** [comment]
Uh
How is ZAS pushing even working on space tiles?

**Comment by PJB3005** [comment]
Proper newtonian velocity when.

**Comment by Shadowmech88** [comment]
What is the status of this?

**Comment by Exxion** [comment]
Not sure it was ever observed other than this time
It was most likely fixed long ago
I'm sure someone else will report it if it shows up again
