### ISSUE TITLE
pAI Smartguns cannot target specific limbs / have no gun safety switch

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#13470]
#### Description of issue
pAIs that are slotted in smartguns don't get a UI of any kind. It's not a big deal, but it means they'll always aim for the chest, and they'll fire the gun any time they click anywhere on the screen. This has in my own experience led to a bunch of accidental lasering, which is kind of a bummer.

#### Server revision
2ceb30407801557eb00116340b41e3910fb63ee2

**Comment by Zth--** [comment]
The switch could be easily made like medbots. A hotkey should be made to switch between firing or not. Then make a state_controls_pai with instructions detailing this
