### ISSUE TITLE
you can 1hand play guitars

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13479]
(WEB REPORT BY: mchotnspicy REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
f16785da76b3e4f2f26524ad81de6886c284d2b5 

>General description of the issue

You can play guitars with one hands
>What you expected to happen
One hand for strumming, one for pressing n the strings

>What actually happened
One hand for both

>Steps to reproduce if possible
Start playing a song, then unwield the guitar

**Comment by ComicIronic** [comment]
While this would be true with no arm, you can still play a guitar with no hand - strumming doesn't require fingers for just making noise.

**Comment by Exxion** [comment]
I think he means you can play the guitar with one hand while using the other for something else

**Comment by ComicIronic** [comment]
Ah right.

**Comment by jknpj** [comment]
Already fixed.
