### ISSUE TITLE
Firing a gun at someone on the same tile as you causes you to shoot yourself

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#13486]
#### Description of issue
If you try to point blank shoot a person while standing on the same tile as them, you will shoot yourself, despite the combat text stating you shot at the other person.

#### Difference between expected and actual behavior
Expected to be able to shoot people while standing over them execution style.
Actually manage to shoot yourself in the face.

#### Steps to reproduce 
Stand on the same tile as someone, shoot at them.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [haventchecked] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
T-thanks lummox

**Comment by Exxion** [comment]
Odd that it still *says* you hit them
Let's just go with both for now

**Comment by Blithering** [comment]
It's possible that you actually hit yourself _and_ the person you aim at, I've never been wearing a medHUD to test
Edit: Just tested, you only shoot yourself.
![gunicide](https://cloud.githubusercontent.com/assets/15067109/21967391/8b938ede-db7d-11e6-9625-da1888138b42.png)

**Comment by Aurx** [comment]
What mystifies me is that there's explicit handling for point-blank shots but it's actually shooting the projectile like any other shot instead of just directly telling it what it hit.

**Comment by Exxion** [comment]
Making it work that way would solve this specific problem, but not shooting a lying person on a tile where a person is also standing and hitting the standing one, shooting anyone on any tile that also contains any dense non-mob object and hitting the object, etc.

Someday maybe I'll get around to fixing `Bump()` "properly"

**Comment by Sprok0** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/projectiles/gun.dm#L184

```
if(targloc == curloc)
	user.bullet_act(in_chamber)
	qdel(in_chamber)
	in_chamber = null
	update_icon()
	return
```
You can also point-blank yourself with the RPG without exploding because of this.

**Comment by Exxion** [comment]
>`user.bullet_act(in_chamber)`

>`user`

:thinking:

**Comment by Aurx** [comment]
Some sort of poorly considered suicide code, I'd guess.  
Or a crippling logic error that was .100% tested.  Could be either.

**Comment by PJB3005** [comment]
This isn't BYOND's fault then.

amazing.

**Comment by SGuivenne** [comment]
Still a bug lol.
