### ISSUE TITLE
Small piping issue in Box Vox outpost atmospherics

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#13485]
These two scrubbers are not hooked up to the waste line.
![scrubbers](https://cloud.githubusercontent.com/assets/19157295/21966439/b7ba1806-db38-11e6-88cf-ebd1d854e8dd.png)

**Comment by Kurfursten** [comment]
won't matter anymore as of #13449

**Comment by Probe1** [comment]
Yeah that's what I thought when I was gonna tag it.

**Comment by Kurfursten** [comment]
Don't forget to close it, though
