### ISSUE TITLE
The Nanobots bottle in the Tradervend is actually a Nanites bottle

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#13483]
Small oversight it seems.
The majority of the work to create Mednanos or Combatnanos is in the Nanite -> Nanobot step

**Comment by 9600bauds** [comment]
💯

**Comment by Zth--** [comment]
Oops

**Comment by Kurfursten** [comment]
I should've realized that wasn't a bird Jew joke, I noticed this before the merge

It gets very hard to tell sometimes what's bad on purpose
