### ISSUE TITLE
Vox Have No Captain's Helmet Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13493]
(WEB REPORT BY: zammyman215 REMOTE: 172.93.109.202:7777)
Revision
4c2662fbbc188ec8363cc32bc4eb8ff6107c46f0

Vox currently have a sprite for the Captain's Armor, but not one for the Helmet. It just makes them bald and is invisible.

**Comment by jknpj** [comment]
Might as well make cap armor human-only

**Comment by Probe1** [comment]
Might as well.  Not like it'd fit on a vox head.

**Comment by uazuaz** [comment]
aren't captain, HOS and HOP roles unavailable to vox?

**Comment by jknpj** [comment]
Yes but people still abuse slots saved with old prefs to play cap/hos/hop as non-human, also, promotions i guess.

**Comment by Kitfox88** [comment]
>they don't sling their tank around their back and wear the greaser outfit

yall don't even vox right

**Comment by kol1th** [comment]
Sounds like a bug, I'm pretty sure there's a sprite for it.

**Comment by Blithering** [comment]
Might have been lost when the captain's helmet had the lit sprite was added, there was a similar issue recently where greys lost helmet sprite when tactical lights were added

**Comment by gbasood** [comment]
Just needs something like #13407 i think

**Comment by jknpj** [comment]
Holy shit there's a snowflake vox armor sprite with different color and shape
