### ISSUE TITLE
Weak bullets, standard beams should cause welder tanks to dump fuel on the first shot and blow on the second.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13506]
Heavy beams et al should retain the original behavior.

How often do you see welder fuel fires that isn't deliberate shittery?  Never.

**Comment by jakmak5** [comment]
>Heavy beams et al should retain the original behavior.

wait laser bolts when shot at a welder fuel tank use to cause it to leak welder fuel? If that is the case why was this changed?

**Comment by Shadowmech88** [comment]
By "original behavior" he means the current behavior.
He's requesting that basic lasers be changed to cause the tanks to leak on the first shot, and heavy lasers be left unchanged.

**Comment by ghost** [comment]
So, reagent containers have health?

Damage it to a point, it starts leaking its contents (Can basically make a trail of welder fuel by dragging the tank around) but too much and it explodes?

Or have it where its based on instantaneous damage, where a slight graze may ca

**Comment by ghost** [comment]
*may cause it to leak, but a large amount of damage at once causes it to explode?

**Comment by Probe1** [comment]
The first sounds best @Skullyton

**Comment by ghost** [comment]
But why would it explode if there was a hole in it to potentially let out any pressure?

**Comment by Probe1** [comment]
Ignition.  A laser is super fucking hot.   Bullets generating sparks on contact with metal.

**Comment by Shadowmech88** [comment]
Yeah, but explosion requires the buildup of pressure.
If there's a hole in the tank releasing the pressure, than wouldn't it be more likely to just eject a stream of flame than actually explode?

**Comment by ghost** [comment]
So, shoot a welder tank with a bullet, then shoot it with a laser to make a large-tank liquid flamethrowet?

**Comment by SonixApache** [comment]
Welding tank flamethrowers jetting through the station sounds a lot more fun and chaotic than stupid explosions
