### ISSUE TITLE
Pressing a direction while buckled in a chair should rotate it that direction.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13509]

**Comment by 9600bauds** [comment]
Rollerchairs only

**Comment by Probe1** [comment]
Yeah that's where the idea came from.  I can't decide what direction a chemists chair should face.  Towards the desk, or the chem dispenser!

**Comment by 9600bauds** [comment]
I mean honestly most of the time the chemists use the machinery from the other side or standing diagonally to it

**Comment by Blithering** [comment]
You should also be able to scoot roller chairs with your feet to slowly move without an extinguisher.
