### ISSUE TITLE
Being in a sleeper means you fled the station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13505]
(WEB REPORT BY: rattletrap REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
61aee611bf36644523de3b14b7f09930faa24a3e

>General description of the issue
Putting someone in a sleeper counts them as "fled the station" for the purpose of rev

>What you expected to happen
Putting someone in a sleeper to keep them alive doesn't make them magically disappear

>What actually happened
Rev round ended because the last head was in a sleeper

>Steps to reproduce if possible
Put a head in a sleeper on rev

**Comment by Kitfox88** [comment]
remove

rev

**Comment by BestName** [comment]
I thought this was intentional to prevent heads/head revs from hiding in closets/sleepers/cryo/disposals etc. and dragging on the round.

**Comment by Probe1** [comment]
If it is then how the shit are you gonna let people know about that caveat?  Especially without spoiling the roundtype or tacking it onto every bit of wiki info about heads.

That seems more like an admin issue.    I've been there before.  I've PM'd heads hiding in a 1x1 tile surrounded by walls that if they don't cut the crap I'll reveal where they are.  

It's good in theory but I've never heard of sleepers causing it before and if I can connect for 4000+ rounds over 3 years then how the hell can I expect anyone else to know every bit about how not to lose rev in silly ways accidentally.

Shit, just imagine saying "No no don't put me in the sleeper it's rev we'll lose".

**Comment by Sprok0** [comment]
Are you sure they didn't die in the sleeper? I can't see how this would happen otherwise, all the checks for rev/head victory use get_turf and check that turf for being on the station zlevel.

**Comment by ghost** [comment]
I've known this since forever - if you hide in a locker, sleeper, etc etc etc you've fled the station

**Comment by Shadowmech88** [comment]
>drag locker behind you
>see head
>put locker under them and close it
>win

This is dumb.

**Comment by 9600bauds** [comment]
Strangely I couldn't reproduce this in local testing

**Comment by Probe1** [comment]
Musta died.

**Comment by 9600bauds** [comment]
As in I couldn't reproduce the locker thing either

**Comment by Rattlederp** [comment]
Well here's some more details, when this happened, the HoS was talking to me and alive just seconds before, I had him in the box sec sleeper before the round ended for a good amount of time. When the round ended, the end of round screen said the rest of the heads were dead except for the HoS, who it said fled the station despite being in the sleeper. IIRC he had about 20 units soporific in him by that time which I guess must have been injected by the rogue AI. I dont know if any of that helps but its all I remember

EDIT: Rev is a shitty gamemode anyway so that round was missed by no one and we might all be better off if this doesnt get fixed because why would you want longer rev rounds

**Comment by Sprok0** [comment]
```
/datum/objective/mutiny/check_completion()
	if(target && target.current && !blocked)
		if(target.current.stat == DEAD || !ishuman(target.current) || !target.current.ckey)
			return 1
		var/turf/T = get_turf(target.current)
		if(T && (T.z != map.zMainStation))			//If they leave the station they count as dead for this
			return 2
		return 0
	return 1
```
This is what rev checks to see if the heads are dead, putting them in a sleeper or locker shouldn't count as having actually fled.
```
else if(head.current.z != 1)
	text += "fled the station"
```
The round end screen checks it the dumb way that would show sleepered heads as having fled, though.

Either the HoS died in the sleeper, somehow lost their ckey (logged out?), or wasn't a roundstart head and didn't actually matter.

**Comment by Killette2** [comment]
Does this affect disposal chutes also? You can easily hide in one with the pump off (disposal chutes give a light if something's in them: protip).
However sometimes heads of staff may need one to escape in an emergency. Also what about situations where a head may be thrown in an infinite disposal loop?

**Comment by Exxion** [comment]
It doesn't really matter
It's just a round end display bug, not an actual round end condition check bug
Should still be fixed, but I wouldn't worry about figuring out exactly in which cases it could happen

**Comment by Kurfursten** [comment]
No longer the case
