### ISSUE TITLE
Skin and hair colors wrong when spawned in?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13500]
(WEB REPORT BY: kitfox88 REMOTE: 172.93.109.202:7777)
>Revision ef48eb50d774f5d5fcb29eb50369f86694e7894e

>General description of the issue
Colored to be a black dude on my character screen, spawned as a white dude

>What you expected to happen
be a black dude with brownish hair

>What actually happened
white dude with blond hair

>Steps to reproduce if possible
be oppressed by trump's america

**Comment by Shaska-** [comment]
![randomidentities](https://cloud.githubusercontent.com/assets/4910818/21998977/0911a278-dc38-11e6-8632-9123a57eaf53.png)

**Comment by Kitfox88** [comment]
Oh, I don't ever recall seeing that, w h o o p s. 🥇

**Comment by Aurx** [comment]
GOD BLESS
THAT MAN
AND
THAT BUTTON
