### ISSUE TITLE
no animation after nuke explosion

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13502]
#### Description of issue
after the nuke exploded and shown the timer, the animation was stuck on this frame instead of showing the station explosion animation

![scrnshot1](https://cloud.githubusercontent.com/assets/6170726/21999277/7f393d8e-dc39-11e6-8317-bb1a3d732915.png)

#### Difference between expected and actual behavior
expected animation of station blowing up
got nothing

#### Steps to reproduce 
let the station blow up with a nuke

#### Length of time in which bug has been known to occur

it happened multiple times in the past weeks

#### Server revision

ef48eb50d774f5d5fcb29eb50369f86694e7894e 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Uh, the nuke ops successfully blew the station, right?

If they put the nuke too far off the station the animation intentionally doesn't play IIRC.

**Comment by uazuaz** [comment]
it happened just now, it wasn't ops, it was blob + AIs with the objective to blow the nuke.
so, it could happen that just freezes this way?

**Comment by PJB3005** [comment]
Oh, no idea then.

**Comment by uazuaz** [comment]
update: i found this file
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/icons/effects/station_explosion.dmi
there are 2 animations about the nuke, one with the station exploding and the other with the station intact but on both animations there is a fading to red;

i just tried to blow up the station on the test server, i put the nuke on the center of the station, inside the AI upload; i got the timer animation, then that still frame, no other animation, no fade to red; i also got the message
>The station was destroyed by the nuclear blast!

**Comment by ghost** [comment]
The code for checking if the nuke is close enough checks from the center of the z level, but rather than being map.maxX/2 or something along those lines its checking for a hard number, which was not corrected when the size of the maps were scaled up

**Comment by PJB3005** [comment]
No that's been fixed ages ago, no?

**Comment by SonixApache** [comment]
This happened a few days ago. First frame played, that's it.

And semi-related; every map plays the animation for deff, which is disgusting.

**Comment by Shadowmech88** [comment]
The animation played fine for me on the test server.
