### ISSUE TITLE
Permanent invisibility

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13517]
(WEB REPORT BY: papamagpie REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>First time writing a bug report so bear with me.

With the invisibility mutation you can maintain invisibility permanently provided you're dragging a corpse. The corpse can be any corpse. With a chick corpse I was able to sneak into the wardens office with little to no issue. 

>What actually happened

First discovered with a giant spider corpse, I was able to replicte it with any corpse. 

>Steps to reproduce if possible

Grab a corpse with the grab intent whilst having the invisibility mutation (the one that has you fade over time).

**Comment by jknpj** [comment]
if you buckle to a chair you don't get invisible, too.

**Comment by Eneocho** [comment]
Couldn't reproduce. I became visible as soon as I moved.
