### ISSUE TITLE
aliens and cuffs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13518]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

handcuffing aliens gives a really ocky icky debug message and it also doesnt work
>What you expected to happen
arresting aliens for vandalism 
>What actually happened
cant cuff and i get a debug message someone left behind

>Steps to reproduce if possible
cable cuff alien

**Comment by Aurx** [comment]
Really helps to actually include a copy of the message.

**Comment by JustSumBody** [comment]
```You are trying to equip this item to an unsupported inventory slot. How the heck did you manage that? Stop it...```

**Comment by jknpj** [comment]
Fixed.
