### ISSUE TITLE
Air and external airlocks on mining station

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13514]
#### Description of issue
just like https://github.com/d3athrow/vgstation13/issues/11863
on box's mining station, the tiles at the 2 exits are sealed to not let air pass through.
the secondary western mining station is not affected.

![0](https://cloud.githubusercontent.com/assets/6170726/22020080/a8f43214-dcb6-11e6-8adc-4ed4082fc5c0.jpg)

#### Difference between expected and actual behavior
expected air going out when opening an airlock;
it didn't happen.

#### Steps to reproduce 
open these 2 specific airlocks, wait, use an atmospheric analyzer.

#### Specific information for locating

saw this on box, i don't know about the other stations.

#### Length of time in which bug has been known to occur

months

#### Server revision

26e7b2fefc22bb29447d647add5e4f9de86bf125 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
Blame casuals annoyed that the airflow would keep stealing their boxes

**Comment by uazuaz** [comment]
that is not going to happen anymore because of this https://github.com/d3athrow/vgstation13/pull/13039
if necessary, closets near external airlocks could be replaced by wall-mounted emergency lockers like the ones near the research outpost exit and the exits from engineering to singularity field.

**Comment by Probe1** [comment]
Airlocks are set to block air.  Easy fix.

**Comment by Probe1** [comment]
Tested as of 15-2-2018 and air is flowing out properly.  Can close.
