### ISSUE TITLE
You can fill balloons from empty tanks.

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#13528]
#### Description of issue
You can fill up a balloon with an empty tank, adding nothing.

#### Difference between expected and actual behavior
Expected: Can't fill it up capn.

Actual: Vacuum Balloons

#### Steps to reproduce 
Have an empty tank and fill up a balloon with it.

#### Length of time in which bug has been known to occur

Since balloons were merged.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
This doesn't make sense, the code for filling checks the `air_contents.return_pressure()` of the tank to make sure it's got gas in it.

**Comment by BobdaBiscuit** [comment]
Are you rounding/clamping at all, cause this was a tank with 0.0001kpa or so in it.

**Comment by Shadowmech88** [comment]
I should probably require that the `air_contents.return_pressure()` be greater than atmospheric pressure, then.

**Comment by BobdaBiscuit** [comment]
"(E) (C) (M) pressure = 0.0012815" is the tank I used, drained from the previous bug I submitted.
