### ISSUE TITLE
Paramedic Cloner Ejection Acccess

### ISSUE THREAD

**Issue by Kitfox88** [d3athrow/vgstation13#13520]
It's super annoying to need to have an actual doctor come over to manually eject the cloner when it's someone like a bird brain, since IIRC they'll just keep dying of toxins while it tries to finish the job. Is it possible that access to eject could be added to paramedic IDs or would that require full bore medbay access like surgical as well?

**Comment by Probe1** [comment]
😆 🔫

**Comment by Kitfox88** [comment]
WHY YOU GOTTA HATE PROBE

**Comment by Probe1** [comment]
Medbay has already been shitfucked by doctors getting total access and making jobs even less meaningful is exactly the kind of bullshit I stand against.

There is absolutely nothing standing in your way of doing what I do and asking for access when there are less than an ideal amount of Medbay staff.  

A job has to be special.  It has to have pros, cons, unique content, and unique tasks.  It isn't the Paramedics job to perform surgery.  That is the surgeons job.  Why do I want to encourage "Surgeon" to be a meaningless title that has no speciality to it?  Why do I want to degrade Paramedics speciality into "It's Doctor but with maint access".

https://a.pomf.cat/fenuth.ogg

Edit:  It's not that I hate nice things, or paramedics, or fun.  It's that this is a video game and not a sandbox.  In order for it to function we need to balance between giving players what they need, and letting players interact with each other to accomplish what they want.  You have all the tools to accomplish what you want.  You're asking coders to fuck up the balance to remove your challenge and uniqueness.  Of course the answer is emphatically no.  You have to show that there is something seriously wrong with how the game functions.  Quality of life does not trump balance.

**Comment by Kitfox88** [comment]
Okay then, no cloner eject access for paramedics. Maybe remove cloner room access from them entirely then though?

**Comment by Probe1** [comment]
Ah now that is where the trickiness starts.

The discussion was about the value of paramedics being able to speedclone people.  A strategy some people think is currently abusive and should be nerfed, and not one required to revive a person.

Cloner access is basic revival.  Some people will be beyond the threshold for defibs and require it.  At that point I say "Okay, we need to make concessions.  Cloning is a part of basic care and not something the intended specialist (Geneticist) has any interest in doing, and the job isn't so popular that there's any guarantee to have a Geneticist.  

So having general access to a cloner is OK.

This is the same kind of argument as "Why can only the CMO delete cloning backups?  If the cloner should be restricted why can anyone use it at all?"

**Comment by Kitfox88** [comment]
Oh, do you not need to speedclone vox anymore? I could swear they'd take fucking ages to clone because of some reason or another regarding O2 being toxic to them. If that's not the case then yeah, who needs ejection access. vOv
