### ISSUE TITLE
Newspapers have no in-hand sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13525]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
404c3feb2895eec6da651d3edce26ce8

>General description of the issue
Newspapers (like the ones that can be printed from newscasters) have no in-hand sprite.

**Comment by Lokiamis** [comment]
It has a sprite, but it's almost impossible to see against the gray tiling and is definitely different from the greenish one we had just a few days ago.

**Comment by SonixApache** [comment]
Oh shit you're right, it does have a sprite. Needs work.

**Comment by DeityLink** [comment]
It's gotten a proper sprite since #26732. This can be closed.
