### ISSUE TITLE
Mommi can't pick up the rapid crate sender from the recharger

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13535]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Mommi can't pick up the rapid crate sender from the recharger

>What you expected to happen
To be able to pick up the RCS as a mommi from the recharger

>What actually happened
Nothing.

>Steps to reproduce if possible
Make a recharger, put the RCS in it and try to take it.

**Comment by DeityLink** [comment]
Fixed by #26639
