### ISSUE TITLE
Nikita missiles can be added as shrapnel to IEDs and don't stop exploding

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13538]
Added 5 nikita missiles to an iedcasing and blew it, generated NONSTOP EXPLOSIONS in a box of catbeasts
![image](https://cloud.githubusercontent.com/assets/19365096/22087157/5ba787c8-ddaa-11e6-904d-32bc44bf8886.png)

![image](https://cloud.githubusercontent.com/assets/19365096/22087026/b865fc02-dda9-11e6-972f-86d44170e8eb.png)

Worth noting that these can be obtained by any player via the kestrel vault

Not sure of any other shrapnel items that should probably not be items but there we go

**Comment by N3X15** [comment]
I propose locking out the kestrel vault until we can figure out a decent way to prevent this.

**Comment by pvak** [comment]
make missles normal sized

**Comment by JustSumBody** [comment]
Missiles are already normal sized

**Comment by ComicIronic** [comment]
What's causing the loop, is there a runtime?

**Comment by AutismSpider** [comment]
why the fuck is the ied taking normal size items?

**Comment by Kitfox88** [comment]
bluespace soda cans

**Comment by Probe1** [comment]
@N3X15 https://github.com/d3athrow/vgstation13/pull/13546

Though this definitely isn't fixing the issue and there's underlying problems with IEDs that need addressed right away.

**Comment by pvak** [comment]
does it mean you can put a box of ieds inside an ied for infinite space?

**Comment by SonixApache** [comment]
Boxes aren't bullets.

**Comment by ultraplen** [comment]
@AutismSpider  because the missiles are bullets casings apparently, the IEDs allows those (+ a few non tiny items such as glass shards)

copy pasted over from the PR doing the workaround fix #13546: 
>not allowing missiles in IEDs

its like you nerds HATE fun

For real though, if missiles are larger than w_class_tiny this is a one line easy fix. I´ll be able to open a PR in a few hours but if you dudes want to hot fix it before that, go to the get_projectile proc on the bullets (can't remember exactly what i called it) and add in a size check.

**Comment by ultraplen** [comment]
This would actually better be fixed by setting shrapnel_amount = 0 on all the missiles, that way you can't add em to the ied.

**Comment by Blithering** [comment]
Can grenades be added as shrapnel? they can be fired from grenade launchers so they're sorta ammo.

**Comment by ultraplen** [comment]
No, only .../ammo_casing/... can be fired as shrapnel.

**Comment by Blithering** [comment]
Pity. Cluster bomb casing when?

**Comment by ultraplen** [comment]
cluster bomb ammo_casing ?

**Comment by Blithering** [comment]
I meant more of a new type of grenade case that works like the clusterbang, insert other grenades and when triggered it scatters them around with the pins pulled.

**Comment by Shadowmech88** [comment]
This was fixed by #13549.
