### ISSUE TITLE
Parrying

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#13533]
[Discussion]

I think it'd be neat to make it so that if two people melee attack each other at close to the same time, the weapons will clash and neither person will receive damage.

I'm not quite sure what the best way to code that would be, though. There'd need to be a window of at least a partial second during which the attacker's attack listens for the victim's attack, which would cause there to be a slight delay between clicking the target and the target actually taking damage/displaying the combat message, which sounds less than optimal to me.

**Comment by yclatious** [comment]
Are you sure that with latency and such, you aren't going to add something that will end up just not being used a lot?

Im thinking it will end like frame perfect parrying in a online fighting game, you aren't going to see a lot of em being done, least not frequently, and at most itl be a minor annoyance instead of a actual mechanic to most people, if it even triggers.

If you however were to add parrying as a natural chance when using a shield against a opponent, that would be neat, would give a extra incentive to make wooden bucklers to greyshirts and make riot shields even better for sec, even if they don't need it very much with all the tools they have.

**Comment by Shadowmech88** [comment]
I don't really expect it to be *intentionally* done all that much, but I thought it might make for some nice flavor if two people in a fight happen to sync their attack cooldowns.

**Comment by yclatious** [comment]
While it would be neat, and Im not saying it shouldn't be a thing, maybe you should think about incorporating it with other elements other than just synchronized toolbox swings, like double swords and shields having them. Sound effects and such would be great, and Im not doubting that a duo of assistants clashing toolboxes for a minute wouldn't make the race cage that much more entertaining, but other elements should be though out a bit more, so it isn't restricted to just frame perfect shows of robustness.

**Comment by Aurx** [comment]
A: Neither person receiving damage just sounds like it'd be an infuriating waste of time.  
B: Neither person taking damage sounds like it'd let some asshole parrytank damn near anything if they kept their adjacency brief.

**Comment by Exxion** [comment]
Autoclickers would become godly, rather than just marginally useful

**Comment by Blithering** [comment]
Sounds like it would need a more in depth mechanic than that, to prevent logical black holes like blocking an energy axe with a plastic knife. Maybe a quick hacky version could be a parrying dagger that's essentially a reskinned buckler?

**Comment by Shadowmech88** [comment]
>Autoclickers would become godly, rather than just marginally useful

How so? The person using the autoclicker would still have an attack delay.

**Comment by Exxion** [comment]
Yeah. And so would the person attacking them. In general, the same attack delay.
It would be possible to counter an autoclicker, but it would involve a different strategy than most fights. (Let them parry a few times, pause attacking until they hit you once, and start wailing on them for a couple hits until they realize what's happened)

**Comment by kol1th** [comment]
Just make it an "intent" or something like that, and when toggled on has  a % chance based on whatever to parry the attack.

**Comment by Lokiamis** [comment]
50% chance to lose a hand when you try to disarm somebody wielding an energy sword when?
