### ISSUE TITLE
Janitors should be restricted to nonhuman races.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13559]
I find it obscene and offensive that we let the most prestigious race meddle in such a lowly position.  Letting this continue offends me on a personal level.  Human janitors are ruining this station and this is where we need to draw the line.

**Comment by Probe1** [comment]
muh teegee lizards

**Comment by Kurfursten** [comment]
Restrict AI to human only, since only human brains are worthy of becoming an AI. These are the serious, important issues.

**Comment by Lokiamis** [comment]
Janitors should receive no wages, but give them a microwave and box of donk pockets to compensate them.

**Comment by Iamgoofball** [comment]
roger wilco isn't an alien though

**Comment by Megamaw** [comment]
what the fuck are you high on the janitor is the most prestigious position on the station

**Comment by SonixApache** [comment]
unlock lizards, make them janitor only

roundstart silicons as posibrains WHEN

**Comment by Kurfursten** [comment]
Restrict posibrain silicons from playing secborg and combat borg. We should reserve that for human brains.

**Comment by Ephx1** [comment]
> roundstart silicons as posibrains WHEN

this

_though I'd just prefer the option to choose that_
