### ISSUE TITLE
Leather drying could use a bit of tweaking

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13554]
Currently the way it works is that wet leather has a wetness variable of 30.
When fire_act is called on wet leather, if the air is also more than 500 Kelvin then the wetness variable goes down one. Once wetness hits 0, the wet leather turns into a sheet of dry leather. 
This essentially means you need a burn chamber to dry leather, as small campfires and pietin fires will do nothing. Even if they call fire_act(which I'm not sure campfires do), you still need that whole "temperature above 500K" thing to be going.

On top of that, drying leather in a stack is extremely inefficient. A stack of 10 leather shares the same wetness variable, and when a stack dries it only takes out/dries one sheet from the ten. So for a stack of 10 leather, you'd need wetness to tick down 300 times to dry all ten sheets.
This can be easily bypassed by splitting the stacks into single sheets, as they would all dry simultaneously. Not sure what would be the ideal intended behavior, but that seems a bit off to me.

**Comment by Shadowmech88** [comment]
Would it be better to require fire but not heat, or heat but not fire?

**Comment by AutismSpider** [comment]
hot room to dry it off?

**Comment by Zth--** [comment]
A hot room with 40ºC or more will do the trick. You can achieve it with heaters for example, or even the thermostat
