### ISSUE TITLE
Janitor QoL tweak: Make 'right arm', 'left foot', etc. Small

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#13558]
oh god, these are a pain in the ass to clean up because they're so common, because gibbing is common, but i can't pick them up with a trash bag. the only way to do this is by hoping there's disposals nearby, and walking them over one by one.

this is the worst, and i don't think useless hacked off limbs will become broken somehow by being made small instead of normal.

**Comment by Kurfursten** [comment]
This kind of thing is what the trash cart is for. Still, wouldn't be wonderful if you could hook the trash cart up to be pulled by the janicart?

Also Box doesn't have a trash cart, but it's just a resprited normal crate of course.

**Comment by Kitfox88** [comment]
Bonus if you make them small you could fit them into IEDs right.

**Comment by Megamaw** [comment]
this is the first i'm hearing of a trash cart.

**Comment by Exxion** [comment]
It's only on Meta, as far as I know
Found in the disposals room

**Comment by Sprok0** [comment]
It's just a resprited crate

**Comment by Megamaw** [comment]
since you can't drag anything with you as the janitor, it is absolutely useless from what it sounds like

**Comment by Kurfursten** [comment]
>can't drag anything as the janitor

**Comment by Megamaw** [comment]
semantics. you know what i mean.
