### ISSUE TITLE
"write in blood" verb issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13564]
#### Description of issue
during cult, after cultists complete some of the objectives, you as a ghost can use the "write in blood" verb;
doing so you have a prompt to write your own message, but the result is just an unreadable scribble; doesn't matter what you write, it seems to me that a standard sprite it's used for all messages.
on the left, i wrote just "boo".
![2](https://cloud.githubusercontent.com/assets/6170726/22164619/5205adc6-df58-11e6-9fcc-0c1d47380423.png)

#### Difference between expected and actual behavior
expected a readable word; if it's meant to be unreadable there is no point on asking you to write your message.

#### Steps to reproduce 
during a cult round be ghost, wait for some cult objectives to be complete, use the "write in blood" verb near a blood stain, watch how writing a message was pointless

#### Server revision

7ece5c7182b52d51807094a62774cddb32eb2ff1 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
You have to examine it to read it
That long predates crayon writing

**Comment by uazuaz** [comment]
ok, ill close this then.
