### ISSUE TITLE
Port this travis optimization

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13562]
https://github.com/tgstation/tgstation/pull/23163

@PJB3005 
@clusterfack 

shouldn't be hard and will definitely improve our travis build times by compiling everything at once instead of compiling 4 maps then 2 maps then finishing.

**Comment by MrsTonedOne** [comment]
bump

**Comment by PJB3005** [comment]
I would port it.

IF I KNEW BASH.

And I don't really want to know bash anyways. It's cancer.

**Comment by MrsTonedOne** [comment]
0-0

**Comment by PJB3005** [comment]
@MrStonedOne I did this in #14316 but forgot about this issue so I didn't close it. @jknpj saw it while sifting through some old issues so I closed it.
