### ISSUE TITLE
Ultra clean station statistic is just plain mean.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#13569]
![clean](https://cloud.githubusercontent.com/assets/15067109/22170443/4f712064-df75-11e6-8d87-bd7dbcd1bac1.png)
The end of round tally relating to janitors only states whether the station is perfectly, possibly unattainabley, clean, and deducts a point from the end of round score for every mess or piece of trash left over. 25 mister cleans (including one being pushed around by the adminbus) couldn't get the ultra clean award so I have no clue how many points it awards, but unless its in the hundreds of thousands the effort required is just plain not worth it.

I'd really like it to be changed to also record messes cleaned, probably at 1 point per tile cleaned, or trash disposaled, similar to how mining smelts, food cooked and plants grown are recorded. That way the janitor has something to feel good about, the station's score reflects the effort put into it, rather than how many people succumbed to the cockroachvomitinggibbingtons five minutes before the shuttle arrived.
This morale increase may stop janitors from becoming sociopathic monsters who only live to see the other crew slip on their faces as they stand there mopping the same spot for hours on end, pausing only to sarcastically point at the wet floor sign (but don't get your hopes up)

**Comment by Megamaw** [comment]
as a janitor who is not one of the aforementoned monsters, yeah, chasing this high is why i often disappear in maint for a while, and it compels me to delve deep into deffmaint and endanger myself just to clean messes

having a more reasonable goal that'd keep me focused on messes that matter? nice idea, actually, buddy

**Comment by Zth--** [comment]
**_Related_**
```
if(!messpoints && !litter) //Not a single mess or litter on station
  score["crewscore"] += 10000 //Congrats, not even a dirt patch or chips bag anywhere
```

```
var/litter = score["litter"] //Every item listed under /obj/item/trash will
cost one point if it exists
```

**Comment by Blithering** [comment]
25 Mister Cleans failed to achieve that from just the round start clutter on box. I am glad that it is a large number though.

**Comment by yclatious** [comment]
Yknow, I think that if a coder simply removed the virology maint cobweb, that it could be possible for janitors to do it normaly, since there actually is a random cobweb there that is stopping most of the attempts.

**Comment by Shadowmech88** [comment]
What if janitors could obtain a mess detector, that would work like a pinpointer for the closest mess within range?

**Comment by PJB3005** [comment]
SS13 is becoming more similar to viscera cleanup detail by the minute....

**Comment by SysadminJeroen** [comment]
@PJB3005 @Shadowmech88 Perhaps we need to import the detector noise from viscera cleanup detail in this new tool.
