### ISSUE TITLE
After relogging, your internals icon will always show as off, even when your internals are actually on

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13579]
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Relogged on the test server, internals still showed as being on.
