### ISSUE TITLE
Being doorcrushed creates a honest-to-God invisible forcefield around you 

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13576]
https://github.com/d3athrow/vgstation13/blob/465fb8b5b5a00f8697e2e47ce3b02f4ce0bc85bb/code/defines/obj.dm#L339
https://github.com/d3athrow/vgstation13/blob/0dc86433b7dbee2307b6c0113d7e91ff3a90f556/code/game/machinery/doors/airlock.dm#L1291
When getting doorcrushed, a mob spawns a magical "stop" forcefield to hold it in place. For some context, the only other things that use this "stop" forcefield are timestop, and an admin player panel punishment.

For as long as the forcefield is around you, NOTHING MAY MOVE YOU OFF THAT TILE (edit: except with very good timing).

This means nobody may drag you off the door to stop the doorcrush (edit: except with very good timing). The pull will inexplicably break while you remain in place with no indication of why (edit: except with very good timing).
~~This also means that if you are immune to the stun of the doorcrush itself, such as by being a horrorform ling, you will be perfectly standing up yet unable to move. You can turn around, attack anything close enough to you, throw items etc etc. you just may not ever move out of the tile.~~ whoops it turns out that airlocks are FUCKING MAGIC and one of the two things I could find in the game that manage to stun horrorform lings isn't that wonderful

The forcefield lasts for 2 seconds, though obviously it's trivial for anyone doorcrushing you to just keep doorcrushing you which extends the forcefield indefinitely. Hell if someone made an assembly to continuously doorcrush they couldn't even get your corpse off of the tile (edit: except with very good timing).

Why the fuck does this exist?

**Comment by kol1th** [comment]
🤔

**Comment by Ephx1** [comment]
This is new, anyone who I doorcrushed was easily saved by someone else despite instant smashing.

**Comment by 9600bauds** [comment]
I vividly being unable to pull someone out of a doorcrush about a year+ ago

**Comment by aceedex** [comment]
I've been pulled out of door crushes tons of times. This has to be relatively new. But why

**Comment by Sprok0** [comment]
This is five years old, and was added in https://github.com/d3athrow/vgstation13/commit/8730d375cfeada87950d13a44d0b3bfb0b822f39

**Comment by 9600bauds** [comment]
Seems like I was wrong and horrorform lings still manage to get stunned by the airlock somehow
I looked a little more into this: There is a VERY SMALL time window for you to successfully drag the guy out. It has to be when the airlock is just about to close again, otherwise you move out, the guy doesn't move, and the pull gets broken.

**Comment by 9600bauds** [comment]
I think I figured out why this exists
Five years ago, when getting stunned from doorcrushes, you didn't immediately drop to the floor until the next Life() tick
So people would get doorcrushed, run past the door, and then go down
Rather than fix the doorcrush stun not being instant, they did THIS

**Comment by Sprok0** [comment]
I mean, if a powered door is closing on you as hard as it can you probably couldn't just be pulled out of it

**Comment by 9600bauds** [comment]
When you're getting doorcrushed the door is in the process of reopening most of the time if you want to flip the logic card here

**Comment by Probe1** [comment]
l o l

**Comment by SonixApache** [comment]
it sorta makes sense that you get stuck when having a giant airlock slam in on you
doorcrushing without the position lock is completely unviable

**Comment by pvak** [comment]
the only way to save someone from a doorcrush is grabbing

**Comment by Exxion** [comment]
Anything that uses `forceMove()` rather than `Move()` could move you out of the door
Like a locker, or vehicle, or probably many other things
But then if you entered the door again before the thing vanished, you'd get stuck again

**Comment by 9600bauds** [comment]
You still get stunned and can't move out yourself

I don't think that other people having the POSSIBILITY of fishing you out of the stunlock makes it "completely unviable"

**Comment by SonixApache** [comment]
Doorcrushing is the most hands-on way of killing anyone you're gonna get as an AI. Crushing someone in a hardsuit to death takes forever. If they have any friends, they'l lbe able to get out of it without too much trouble.
The stun is the only thing that makes it remotely viable.

**Comment by Blithering** [comment]
The stun isn't the problem, it's the invisible stay in place forcefield.

**Comment by AutismSpider** [comment]
make sure it stuns then and take the force-field out
