### ISSUE TITLE
X-ray gun doesn't shoot through walls.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13577]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
I've heard that it does from a number of sources; it doesn't. It's just a 30 burn laser that's green.

**Comment by Aurx** [comment]
That's a TGstation feature.

**Comment by Shadowmech88** [comment]
Giving the projectile infinite penetration would be trivial. Would make a good first PR for someone.

**Comment by Exxion** [comment]
Infinite penetration would be horrifying

Actual x-rays can't really pass through metal anyway
But it is called science *fiction* for a reason

**Comment by Shadowmech88** [comment]
Could give it infinite penetration, but decrease its damage every time its `Bump()` is called, so it diminishes with every obstacle it passes through.

**Comment by ComicIronic** [comment]
And have it stop when it hits 0 damage.
