### ISSUE TITLE
Infinite Jump

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13581]
(WEB REPORT BY: chucklemonger REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
 9c6c0356db96beecb2dc4507668c7e955a5000f2 

>General description of the issue
The Jump genetic power can be repeated endlessly for a very short time.

>What you expected to happen
A single long distance jump.

>What actually happened
Upon being clicked while still in use, it activates again. This can be repeated until the original jump would have hit the ground. When tested with an autoclicker on a 3 millisecond delay, this effectively allows teleportation. Also, it packs the chatbox.

>Steps to reproduce if possible
Acquire genetic Jump power.
Click the icon multiple times in quick succession.

**Comment by PJB3005** [comment]
Something tells me the sleeping if the movement loop inside the jump ability is delaying the cool down counter to be set.

Waitfor'd fix this.

**Comment by Probe1** [comment]
I mean it doesn't need testing everyone uses it all the time.  You spam the button.

**Comment by PJB3005** [comment]
This seems not the end of the world tier until you realize it causes clients to hang *badly* when you combine it with an auto clicker.
