### ISSUE TITLE
medibots are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13587]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
they have been broken for a while maybe the pai medibot pr did it.
medibots now spam injections and when i used a mass spectometer on the dude injected he had nothing in the blood 

>Steps to reproduce if possible
be hurt near a medibot
get 9999 injection messages
no meds in the blood

**Comment by Zth--** [comment]
Works fine in the test server which is outdated. I'll check the main server

**Comment by Blithering** [comment]
This may have something to do with medibots who have had a pAI inside, and then removed. Noticed this was when it started wigging out and spamming empty injections the last time it happened to me.

**Comment by Probe1** [comment]
I'm pretty sure it started when someone made a fix to stop them from overdosing people
