### ISSUE TITLE
Browser datums are stubborn to unset_machine(), but only for the first time

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13580]
I've been able to reproduce this with the chemfridge, chemmaster, icecream vat, and seed extractor. Probably happens with more browserdatum things.

1) Be ghost, touch the machine to open interface, close it
2) Another player updates the machine such as by loading beaker/pill/seed
3) The interface opens up again for you, close it again
4) Another player updates the machine such as by loading beaker/pill/seed
5) No interface

And from that point onwards it works perfectly as expected. You can open the interface again and close it, next time someone loads something in the machine the interface doesn't appear again. It WILL happen again if you touch a different machine, even one of the same type (try it with both chemmasters).
No idea.

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce.
