### ISSUE TITLE
the single evilest thing in the game

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13586]
![firefox_2017-01-22_19-53-02](https://cloud.githubusercontent.com/assets/6526157/22186922/6b5f0468-e0dc-11e6-8b28-9d2c57dabcdf.png)
Why that looks like a mighty packed choke there, don't it Johnny?
Ya got the main entrance and the fridge and Chemistry all right and pinned all close to eachother! There's always a writhing squirming mass of people tryin' to make their way through!
Y'no what it needs?
![dllhost_2017-01-22_19-54-45](https://cloud.githubusercontent.com/assets/6526157/22186938/ae5e03ae-e0dc-11e6-8714-b5098bffafe7.png)
LET'S ADD A FUCKING SHOWER STICKING OUT THE SIDE OF THE FRIDGE SO THAT PEOPLE CONSTANTLY FUCKING TURN IT ON AND SLIP EVERYONE FOREVER
YEAH A NICE AND USELESS SHOWER RIGHT IN THE MIDDLE OF THE BIGGEST CHOKEPOINT OF MEDBAY, CONSPICUOUSLY PLACED IN SUCH A WAY THAT IT COULD OFTEN GET MISCLICKED ON
WHOEVER DID THIS IS THE SINGLE MOST BRILLIANT EVIL DEVIL TO EVER TOUCH DREAMMAKER

**Comment by Kurfursten** [comment]
INCONSPICUOUS POST

**Comment by 9600bauds** [comment]
shush I did and I already fixed it

**Comment by Kurfursten** [comment]
I gotchu, I'll just edit that post and no one will ever know

**Comment by kilozombie** [comment]
Sidenote, if you swap the desk and door, there's a lot more wiggle room to get in and out of Chemistry.

**Comment by Probe1** [comment]
I would have removed it ages ago but it makes me laugh every time.

I suppose I must if emojiocracy says I must.

**Comment by 9600bauds** [comment]
Leave it in but please do something about THE CHOKE

**Comment by 9600bauds** [comment]
Also how2deconstruct shower

**Comment by Probe1** [comment]
>Please do something about fundamental design flaw that would require a significant rework of the entrance

Oh well since you put it that way.

**Comment by 9600bauds** [comment]
thanks probbu I knew I could count on you

**Comment by Kurfursten** [comment]
Relocate the owl gear elsewhere and put the shower in its place, add a civilian airlock above it, and wa-la, you have private showers!

**Comment by SonixApache** [comment]
Place the showers in the doorways instead.
People coming in and out get disinfected / cleaned of blood, greys get melted, doctors get incentive to never leave. It's a win-win situation.

**Comment by Probe1** [comment]
Add a remote signaller to the shower so doctors can send people on the wet and wild ride.

**Comment by Duny-** [comment]
This was fixed and should be closed.

**Comment by nuklearcellphoneg** [comment]
Remove Duny
