### ISSUE TITLE
UI Hide/Show Breaks Toggles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13597]
(WEB REPORT BY: hikato REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
0c2a5d0fe3a7c5ade0fe24c3176a684933a369dc

>General description of the issue
If you show/hide the UI, when it is enabled again, the toggles don't reshow.

>What you expected to happen
See muh magbootz to toggle.

>What actually happened
No toggle for muh magbootz.

>Steps to reproduce if possible
Hide/show UI.

**Comment by Hikato** [comment]
@gbasood Wear magboots and press F12 twice.  You won't see the button to toggle in top left.

Can't show pics of what ain't dere.

**Comment by Shadowmech88** [comment]
Hiding the UI no longer even hides the magboot button, much less permanently.
My guess is it has something to do with the changes to action buttons since this report.
