### ISSUE TITLE
Most of disposals somehow goes to medbay in Meta

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13592]
reproduced by climbing into disposals from mechanics'

**Comment by Probe1** [comment]
Please be more descriptive.  

The disposal line travels directly through medbay.  Is it spitting out or something?

**Comment by Kurfursten** [comment]
While trying to find out what he meant by this, I noticed that these rooms have **comically** inoptimal disposal chutes, often times going 10 or 15 tiles out of the way when there's a maintenance door to the main disposal line one or two tiles away.

* Botany
* Telescience
* Medbay Foyer
* Medbay Breakroom

The medbay breakroom doesn't have a sort junction. You put the sort junction at a major hall so anyone can loot the medical crates.

**Possible cause of issue** the merge junction above the current medbay sort junction is facing the wrong way.

**Comment by 9600bauds** [comment]
Most of the garbage on the station literally pops out of the medbay backroom bin, yes
Can be reproduced by climbing into disposals from inside Mechanics'

**Comment by DamianX** [comment]
I climbed into Mechanics' disposals and ended up at cargo, did someone fix this already?

**Comment by Probe1** [comment]
yeah i forgot to tag it https://github.com/d3athrow/vgstation13/pull/13734
