### ISSUE TITLE
machines unbolted from the floor, also no effect when using a wrench

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13605]
#### Description of issue
- account database and isolation centrifuge are unbolted from the floor, therefore you can pull them around; additionally, there is no way to bolt them, wrench has no effect.
- disease analyzer and pathogenic incubator are bolted, but there is no way to unbolt them, wrench has no effect.

#### Difference between expected and actual behavior
expected all machinery starting bolted and that you can bolt/unbolt them at will using a wrench;
some of them aren't.

#### Steps to reproduce 
try to pull machinery, use wrench on them.

#### Length of time in which bug has been known to occur

a couple of weeks, i don't really know.

#### Server revision

0c2a5d0fe3a7c5ade0fe24c3176a684933a369dc 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by despotate** [comment]
- Hydroponics trays are completely functional when unbolted, and even when stacked, leading to the current meta of just unwrenching all the trays and stacking them near the vendors and using alt-click to plant/harvest/etc them
