### ISSUE TITLE
Not being able to walk when cuffed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13607]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
8f037bac773f3340b82e59706ea4c4445bc39df8 

>General description of the issue
When you are cuffed you aren't able to walk on lattices. You can turn around by clicking but movement itself is impossible

>What you expected to happen
Being able to walk

>What actually happened
Couldn't move at all

>Steps to reproduce if possible
Cuff yourself, stand in space on lattices

**Comment by Aurx** [comment]
This is because space movement only lets you "push off" objects when not restrained, and latices let you move by being objects you can "push off" of instead of normal floors.

**Comment by Shadowmech88** [comment]
Can you not push off of things with your feet?

**Comment by Aurx** [comment]
Apparently not.

**Comment by DeityLink** [comment]
Let's pretend that the player uses their arms to grab the lattice and move in space using those.
