### ISSUE TITLE
Lit flares not acting like heat sources

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13618]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
16e34f8e9f8fd4d9bb9fe9b4d00fc0b6bcb60e38 

>General description of the issue
Can't put shit on fire or light cigarettes with a flare

>What you expected to happen
hot hot hot

>What actually happened
not not not

>Steps to reproduce if possible

**Comment by Kurfursten** [comment]
What are you trying 'put on fire' other than cigarettes?

I am pretty sure flares DO set plasma on fire.

**Comment by Aurx** [comment]
They ignite plasma.  Making them light cigs would be trivial.  

If you want them really acting as heat sources, they'd need to dump heat into their tile's air.  
Being able to murder somebody slowly by locking them in a tiny room with two boxes of lit flares does sound fun though.
