### ISSUE TITLE
The bunker isnt on

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13610]
(WEB REPORT BY: amikawaii REMOTE: 172.93.109.202:7777)
>Revision (16e34f8e9f8fd4d9bb9fe9b4d00fc0b6bcb60e38

>General description of the issue
the server is full of refugees, idiots who refuse to learn how to play, people who run around like its Hippie.

>What you expected to happen
A method in place that when we get swarmed with new people that directs them not here unless they have a good reason

>What actually happened
See above

>Steps to reproduce if possible
join any game during American High Pop.

**Comment by Exxion** [comment]
If you're going to post a meme issue, at least use an actual account

**Comment by PJB3005** [comment]
Honestly this is a new low for issues Jesus christ.
