### ISSUE TITLE
Emagging buttbots should output to chat copypasta

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13614]
>Wot the fok did ye just say 2 me m8? i dropped out of newcastle primary skool im the sickest bloke ull ever meet & ive nicked ova 300 chocolate globbernaughts frum tha corner shop. im trained in street fitin’ & im the strongest foker in tha entire newcastle gym. yer nothin to me but a cheeky lil bellend w/ a fit mum & fakebling 

From bumblingidiot

**Comment by Shadowmech88** [comment]
But what does this have to do with butts?

**Comment by Exxion** [comment]
???

**Comment by Kurfursten** [comment]
Wow, I knew Bumbling's English wasn't strong but this really needs an editor.

**Comment by Exxion** [comment]
It's like 2/3 of a shitty edit of the gorilla warfare copypasta
But... why?

**Comment by ghost** [comment]
Emagging buttbots should give them chat memory like poly, complete with saying said memorized text at random, albeit buttified

**Comment by Probe1** [comment]
Because it's funny of course.

**Comment by PJB3005** [comment]
Make them say ass blast USA instead.

**Comment by Kurfursten** [comment]
RIP all old Probe issues

**Comment by Probe1** [comment]
Celt told me to fix issues.  50 feature requests that won't be fulfilled.
