### ISSUE TITLE
The random stack of 50 materials on the vox trader shuttle ought to always be cardboard

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13621]
Cardboard thematically and mechanically makes sense since you would make boxes out of it to put your goods in when selling items.

**Comment by jakmak5** [comment]
This actually does make sense since there really isnt anything better you can put there without it being unbalanced or having it be completely useless since this would serve a functional purpose while not giving the traders an powergamey edge.

**Comment by Probe1** [comment]
It was for selling not for boxes.  Hence it being random.

**Comment by despotate** [comment]
Is the crate with table and rack parts on the other side of the shuttle also for selling and not for trader use?

We can keep the RNG of having an extra materials stack but I don't know why we would withhold packaging from the role that needs it most. They can't order empty box crates or feasibly grow cardboard in the biogenerator with their plants' shit stats, lack of xenobotany, and lack of time, so this seems to be a QOL upgrade with no real downside to me.
