### ISSUE TITLE
What's Wrong with Meta's Medbay and How to Fix It

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13620]
![meta0](https://cloud.githubusercontent.com/assets/6526157/22252014/904c29cc-e22b-11e6-8239-4dbbd17a27f8.png)
This is meta's medbay. You may not readily appreciate what's wrong. To show you that, first I'm going to represent it as the simple placement of the rooms.
![meta1](https://cloud.githubusercontent.com/assets/6526157/22252039/a3b36f84-e22b-11e6-908d-ab45d3eda96b.png)
I want you to imagine where people usually move to and from in Medbay. Where does a doctor go when dragging a patient around? Where do the patients run to when trying to find a doctor? Where do the patients go to self-medicate?
The majority of pedestrian flow gravitates around the fridge, no question about it. Then, to and from the fridge, people go to Cryo, the body scanners, sometimes Surgery, sometimes the cloner, etc.
Let me make a few crude lines here to represent the flow of people.
![meta2](https://cloud.githubusercontent.com/assets/6526157/22252238/3fcbf828-e22c-11e6-9fb4-9ffa5a9e2a21.png)
You can probably see the issue now. People crowd the FUCK out of the bottleneck 3wide hallway. They go back and forth on it to get to the fridge, to go to the fridge, when entering medbay, when leaving medbay, etc.
Notice how people almost never go to Storage, yet it's near the center of it all. What a waste of space.
As an added bonus, look at how hilariously impractical the Paramed's placement is.

I'm going to do a very simple swap here.
Rotate Paramed's, Storage and Chemistry all counter-clockwise.
![meta3](https://cloud.githubusercontent.com/assets/6526157/22252501/32067cf8-e22d-11e6-9628-9d08d700fbee.png)
See how much more evenly distributed that is?
The main solution here is to MOVE THE FRIDGE. Once you move the fridge, people only go through the 3-wide hallway to get in and out of medbay. As an added bonus, there's a real nice and open space to put the fridge on, which is currently being wasted.

**Comment by Kurfursten** [comment]
In addition, with chemistry gone, we could move the shower up one tile so that it would be closer to the medbay exit airlock.
