### ISSUE TITLE
how 2 get 2 cent episode 19

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13630]
![2017-01-24_21-30-04](https://cloud.githubusercontent.com/assets/6526157/22272959/52f2b72a-e27c-11e6-9eba-00eb0c680fe0.gif)

**Comment by jknpj** [comment]
amazing

**Comment by clusterfack** [comment]
Life, uh, finds a way.

**Comment by Shadowmech88** [comment]
What if we just put invisible immovable objects all over the cargo shuttle area at Centcomm that just gib any human on their tile?

**Comment by jknpj** [comment]
Make <s>humans</s> anything gib if they arrive to centcomm using this method, mommis will end finding a way

**Comment by Exxion** [comment]
Let's put an actual sorting room at CentComm so that if anyone manages to get there, their immulsions aren't wrecked and they get to explore a little crate deployment center
For about five seconds before getting murdered by indestructible 300-damage security bots

**Comment by 9600bauds** [comment]
All jokes aside, I think admins would really appreciate some little machine in Centcomm that lets you place items on a tile and it generates a supply manifest and puts them in a crate as if it were a legit custom cargo order. For when the IAA makes a really formal fax asking for something and it'd be tacky to just spawn it in or send it in an unmarked crate.

I briefly tried to do it and immediately gave up when I saw cargo shuttle code.

**Comment by Probe1** [comment]
Ok why did this never get discovered before

God that's so obvious.

Alternatively and sanely, we just add a short delay when sending the shuttle and have a check to see if anything is on it after that delay.

**Comment by Intigracy** [comment]
Or just kill people since they keep finding a way.

Like derelict mommis.

**Comment by PJB3005** [comment]
@Intigracy I disagree.

Getting to centcomm should be rewarded by admin hilarity, not by instant gibs. If you find a way we patch it and now you need to get more creative.

**Comment by Probe1** [comment]
yeah getting to centcom is not expressly forbidden.  Mommis are expressly forbidden from leaving Z4.

It's similar but it's not the same thing

**Comment by MadmanMartian** [comment]
Gonna take this one up, learning some mapping for it

**Comment by MadmanMartian** [comment]
would this technically be closable now? Getting to centcomm via the cargo shuttle isn't as big an issue with the new cargo station.

**Comment by Kurfursten** [comment]
Yeah it's closeable
