### ISSUE TITLE
Intercept report only gives extra TC to players who don't have skeptical/opposed Nanotrasen relation set

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#13634]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/gamemodes/game_mode.dm#L193

So basically people with this set to anything but loyal deprive themselves of TC

**Comment by Probe1** [comment]
idk if thats an oversight.  its intended.

**Comment by 9600bauds** [comment]
I believe the tradeoff for this is that if you set skeptical/opposed you show up in the roundstart command report more often

**Comment by Shadowmech88** [comment]
It's kind of dumb to base whether a player receives extra actual in-game benefits on an otherwise completely cosmetic character customization option.

Why not just change it so that it gives people on the intercept report extra TC regardless of their NT relation?

**Comment by Exxion** [comment]
Because setting your NT relation changes the likelihood you'll appear on that report

**Comment by Intigracy** [comment]
Let's just remove NT relation and give TC if they're on the report.

**Comment by Intigracy** [comment]
Also it's not "only".

		else if(special_role == "traitor" && prob(40) || \

They just have a higher chance.

**Comment by Intigracy** [comment]
Wait I see what you're saying now, holy shit. It adds you to the suspects if you pass the first check for NT relations, but you GET NO TC.

**Comment by gbasood** [comment]
Yep
You can remove yourself from getting TC on accident by setting your relation to anything but default

**Comment by PJB3005** [comment]
Solution is to remove relationship.

It's a bay \~RP~ feature nobody gives a shit about.

**Comment by Exxion** [comment]
Yeah, there's really no reason to keep it
It only affects one thing in-game, and no matter how we change it, everyone would set it the same way for powergaming purposes
