### ISSUE TITLE
Marauders, even with circuits from a trader, aren't possible to build

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13638]
Alright so traders can buy maruader circuits from their vending machine and that's all well and good, you can even deconstruct them for some combat and programming tech. You can scan them with a device analyzer and gen fab each circuit for 3000 glass and 300 plastic if you don't have the research but have the circuits.

HOWEVER, the marauder mech parts themselves can't be made unless you have NT Tech at level 5
Getting NT Tech to level 5 is not possible(or at least SHOULDN'T be according to the argument @JMWTurner made for having marauders buildable to begin with), only things in that tree are the gravity well gun, hookshot, and ricochet rifle.

Proposed fix: Give the circuits some NT Tech on deconstruction.

Alternatively I'm wrong and it is somehow possible to get NT 5 without bus with those three items, in which case the issue is marauders ARE researchable without circuits which is also bad.

**Comment by ihadtoregisterforthis** [comment]
This is all intended

**Comment by Intigracy** [comment]
Pretty sure the item being 100% unusable isn't intended, no.

**Comment by ihadtoregisterforthis** [comment]
From a marauder board bugfix
>They now require Nanotrasen tech 5. Along with Marauder parts. Admins can spawn nanotrasen tech disks and varedit their value to 5 if they wish to grant players the tech to build them IC, or during an event.

From the list on the Jewvend PR
>Box of marauder circuits (one is missing, because vox are jews)


It wasn't an accident

**Comment by Probe1** [comment]
It was absolutely intended.

**Comment by Intigracy** [comment]
So then the box is just a useless item that takes up space that could otherwise be something they could sell.

**Comment by Exxion** [comment]
@Probe1 That's absolutely stupid.

**Comment by kilozombie** [comment]
The _intended_ behavior was that you would need some supplement to build the marauder, or that you would need two traders to spend coins on the boxes. Not that it would be utterly useless, just that it wouldn't be a starter kit to a marauder in of itself.

**Comment by 9600bauds** [comment]
The circuit box was literally added in as jew scheme bait

**Comment by Exxion** [comment]
Adding something specifically as gimmick bait is stupid because everyone would eventually KNOW it's gimmick bait, and it would be worthless

**Comment by ComicIronic** [comment]
And yet someone clearly didn't know, because this issue exists.

**Comment by Intigracy** [comment]
@zth-- since everyone is just assuming, what was your original intent with the box?

**Comment by Zth--** [comment]
@Intigracy the code speaks for itself https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/objects/items/trader.dm

Should we add the missing circuit or is it too OP? To be honest this one was kind of a placeholder to see what happened. Now I learnt that it has an expiration date and nobody will pick it anymore

**Comment by PJB3005** [comment]
Give them the levels so you can clone the board with mechanics and scan it to get the tech levels for the other board.

**Comment by Intigracy** [comment]
Yeah, having one missing is fine, but you could give them the levels so actual effort can be taken to get the last piece.

**Comment by kilozombie** [comment]
Yeah it'd be cool in my mind if you still needed 2-3 boxes to actually get what you wanted.

**Comment by Aurx** [comment]
Hell no, we should not be putting admin-spawn supermecha into the round.

**Comment by kilozombie** [comment]
The alternative is you give them almost what they need, and the last part/parts have to be bussed in, so admins can control the actual flow of marauders.

**Comment by Shadowmech88** [comment]
If you're going to make it require bus anyway, why give them the partial circuits at all? Why not just ask the admins to bus in a complete marauder?

**Comment by Intigracy** [comment]
Leaving it incomplete is just wasting one of the 5 slots on the vending machine.

**Comment by Aurx** [comment]
>If you're going to make it require bus anyway, why give them the partial circuits at all? Why not just ask the admins to bus in a complete marauder?

Or for that matter, just bus in the parts and let them assemble it.

**Comment by kilozombie** [comment]
Admins will never bus a marauder in, they might bus a single circuit in (since you've already gone through some effort)

I'm pretty sure the original idea came from somebody in the thread, according to what I said in https://github.com/d3athrow/vgstation13/issues/12348

**Comment by Shadowmech88** [comment]
>effort

You used a coin on a machine.

**Comment by kilozombie** [comment]
...well, I mean, a trader did, and then you went and bought the box. But yeah, even I'm having trouble figuring out what exactly the point is of this thing.

**Comment by Probe1** [comment]
we're getting ahead of ourselves real quick.  I said okay to adding it because you couldn't actually get the mech

Your choices are removing it or accepting it as is.  There is no admin spawn supermech choice.  I'm sorry if you thought that it was intended to be obtained.

**Comment by JustSumBody** [comment]
Just remove them in my opinion. Waste of trader coin and guaranteed to do nothing but generate ahelps/bug reports about it being useless

**Comment by Shadowmech88** [comment]
Remove it then. What's the point of having a useless item in the vendor?

**Comment by kilozombie** [comment]
No point.

**Comment by Probe1** [comment]
The point was so Traders can Swindle roboticist that don't know better.

This was discussed and the pr and issue.

**Comment by Shadowmech88** [comment]
But eventually all the roboticists *will* know better and then the item will just be useless clutter.

**Comment by Probe1** [comment]
New players start playing everyday.  I'm not married to the idea but I am struggling with repeating the same discussion we had not a week ago when we added this.

**Comment by JMWTurner** [comment]
Admins can spawn a /obj/item/weapon/disk/tech_disk/nanotrasen and varedit the /datum/tech/nanotrasen in its "stored" var 's level to 5, and hand it to players, if they wish to provide an IC way of allowing players to craft marauder parts.

Alternatively, replace the marauder circuit that traders can buy with a level 5 nanotrasen tech disk, but I wouldn't advise it.

IMO the marauder circuit should just be removed from the traders. **Players shouldn't be able to craft the fucking Deathsquad's mech every round.**

**Comment by despotate** [comment]
Don't worry, Probe, I solved your dilemma.

25 January 2017

    (diff | hist) . . Roboticist‎; 22:36 . . (+25)‎ . . ‎Despotate (Talk | contribs)‎
    (diff | hist) . . Roboticist‎; 22:34 . . (+193)‎ . . ‎Despotate (Talk | contribs)‎ (giving a heads-up to newfriends on buying Marauder circuit boxes)

We wouldn't want to hide information from the players like Goon does, after all :^)

**Comment by Exxion** [comment]
@ComicIronic That's why I said eventually

**Comment by Aurx** [comment]
Get a loada this guy who thinks newfags read the wiki.

**Comment by ihadtoregisterforthis** [comment]
Goon hides information from being closed source and changing everything everytime the sekrits become public. It's a long way from there to omitting details for a jape.

Anyone that tries once, looks at the PR on github, or asks on the thread can know

**Comment by JustSumBody** [comment]
WERE NOT GOON!!!!

Also does this mean I can get out of updating the wiki with my hot new features now since it can be found out through thread/github

**Comment by Aurx** [comment]
No

**Comment by Aurx** [comment]
Work harder codeslave

**Comment by Kitfox88** [comment]
having them there as a fuck you cocktease that serves zero purpose is bullshit crap for morons

**Comment by 9600bauds** [comment]
I mean it will result in traders getting lynched at some point, which is A purpose
no comment on if it's a good one or a bad one :^)

**Comment by despotate** [comment]
I understand what you people are aiming for (information asymmetry) and I don't know why it's not implemented in a much more sane way than something that'll essentially only ever maybe work once on unsuspecting idiots and is otherwise a waste of a trader coin slot. In a general sense, I'd aim for giving the trader the option to buy multiple exclusive items at the cost of them being broken / damaged with no one but the Trader knowing this for certain, as an example. 

Really considering the current culture of Tradertide I'd want to do the opposite of encouraging lynchings against them, they have little enough to legitimately do and trade as it is.

**Comment by Kurfursten** [comment]
No longer relevant as it was replaced with Mecha Graveyard disk
