### ISSUE TITLE
Bullwhip having no attack delay until you hit a mob with it is hilariously overpowered

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#13637]
![muppet trade post 64 2017-01-24 230805](https://cloud.githubusercontent.com/assets/9827785/22277850/cd2d63ea-e28c-11e6-8ba3-5b4ed212f246.png)

**Comment by Shadowmech88** [comment]
The idea it to bring it in line with other melee weapons, whose attack delays do not apply unless you actually hit something.

In the erratic click-spam fest that is combat, applying the attack delay to the bullwhip even if you miss would make it nearly useless.

**Comment by Exxion** [comment]
It's more akin to a ranged weapon, though
If you miss with the bullwhip, you get infinite retries until you hit, even though it's a 15-force weapon with infinite ammo and triple the range of most melee weapons

I can understand giving it a shorter attack delay when you miss, but none at all is a bit much
You can have four whips visible at once, though I only managed to get three in the screenshot

**Comment by Shadowmech88** [comment]
I would've decreased the time the whip is visible when used, but I couldn't figure out how.

Anyway, what attack delay would be best? Half second? Quarter second?

**Comment by Intigracy** [comment]
Try quarter, if it's still OP we can change it to half later.

**Comment by Shadowmech88** [comment]
Can `DelayNextAttack()` take decimal values? A quarter normal attack delay is 2.5 deciseconds.

**Comment by Intigracy** [comment]
It uses either sleep or spawn to do the correct behavior, so the question is really whether those do.

Just round down.
