### ISSUE TITLE
Floorbots are only creatable with blue toolboxes

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#13635]
However you can make a medbot with any color medkit

**Comment by clusterfack** [comment]
Botcreep

**Comment by Zth--** [comment]
At this point floorbots are so hilariously broken they shouldn't be in the game until completely reworked

**Comment by Killette2** [comment]
I hope you mean broken as in non-functioning, because it's true and why they need attention

**Comment by pvak** [comment]
can you give floorbots the ability to change floor tiles like loading it with wooden floor tiles, pressing a botton and it ll turn metal floor into wooden floor

**Comment by AutismSpider** [comment]
Red tool box =  fire fighting bot 
yellow tool box = ????
Blue tool box = floor bot but this thing needs better ai

@Killette2 medkit you use matters though if you use a blue one it put dex in people etc

**Comment by Killette2** [comment]
It didn't matter until about half a year ago

**Comment by Ephx1** [comment]
yellow toolbox = wire laying bot that bases its wiring positions on the holomap

**Comment by PJB3005** [comment]
Holomap can't be used for determining the station layout. It stores appearance data only.

**Comment by Ephx1** [comment]
Well you get the idea anyways, it'd be a good compliment to the blue one.

**Comment by DamianX** [comment]
Yellow = light replacer bot
you heard it here first

**Comment by Killette2** [comment]
I just wanted pretty toolboxes...
