### ISSUE TITLE
Sleeping, being buckled to a bed, and then waking up makes you deaf until you get back up again

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13633]
Just logdived to see what happened of a bwoink and it turns out that both I and a pink haired static, who were asleep, buckled to beds, and woke up, thought we were still asleep because we kept getting "You can almost hear someone talking." messages. Vision did turn to normal when we woke up. The way out of this was to hit rest.

**Comment by gbasood** [comment]
sounds like you were asleep even after vision returned?

**Comment by despotate** [comment]
No, I think we fully woke up and vision returned but were still deaf for some reason. I had to hit the rest verb to get back up, which also cleared the deafness.

**Comment by Shadowmech88** [comment]
This definitely sounds like the "remained asleep with clear vision forever after resting while asleep" bug. We already have one report for that.
