### ISSUE TITLE
You can't bootstrap research with just an autolathe on Boxstation because the circuit imprinter board is missing from Tech Storage

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13648]
There's a protolathe and a research console in tech storage but no circuit imprinter.

In fact, I think the ONLY current way to make a circuit imprinter is with another circuit imprinter.

**Comment by jakmak5** [comment]
This was probably put in to stop people from building their own sci lab so they dont have to be cucks to science.

**Comment by Aurx** [comment]
Just use the MoMMI nest one you nerd.  What are they gonna do about it, buzz at you?

**Comment by 9600bauds** [comment]
It's kind of backwards that the room whose only intended purpose is to let you rebuild from scratch doesn't let you rebuild from scratch

**Comment by Zth--** [comment]
@jakmak5 there's no need now because the console requires science access

**Comment by Allspice** [comment]
You only need science access for server stuff and deconstructing, any random greyshirt can still print their guns and bags.

**Comment by AutismSpider** [comment]
only need sci access undo the lock or decon stuff

**Comment by PJB3005** [comment]
You need sci access to link to machines if you've just set it up too IIRC.

And you need it to use the deconstructive analyzer, and without syncing you then have no way to get the levels to print shit.

**Comment by Zth--** [comment]
Yeah I'm pretty sure you can't do shit without science access

**Comment by Allspice** [comment]
I believe screwdrive twice on the R&D console detects the nearby machines automagically.

**Comment by Sprok0** [comment]
It also unlocks the console if someone locked it, rendering that feature pointless

**Comment by PJB3005** [comment]
And it causes all research levels to be forgotten so you need to sync to be able to use it again, which you can't without access.

**Comment by Sprok0** [comment]
It keeps the research levels, I just tested that.
It also reconnects to the research network, if you disconnected it before locking it

**Comment by PJB3005** [comment]
Wait really?

Well then.

**Comment by despotate** [comment]
Yeah, https://github.com/d3athrow/vgstation13/issues/13688 is related and the reason I even asked for this; it'd have opened another path towards Tradertiding an AI upload. Probably not a good idea to add the imprinter there until access restrictions work properly.
