### ISSUE TITLE
Some stuff don't recycle properly

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#13641]
Boxes should recycle to cardboard.
Space cola should recycle to iron.
Eaten chips in general should recycle to something.

I'm sure there are a few more but I don't play cargo/janitor enough

**Comment by Exxion** [comment]
>Iron cans

**Comment by Kurfursten** [comment]
Cans are aluminum, and even grind into aluminum

**Comment by Zth--** [comment]
Yeah but we don't have aluminum... but now that I think of... they'd be nice to have

**Comment by Kurfursten** [comment]
It would make a cool upgrade for the recycler

>Adds the ability to produce 30u bottles of reagents like a chemmaster
>Organic trash like banana peels get converted into Biomass that can be used at the cloner or biogenerator
>Cans into aluminum reagent, etc.
>Containers that get recycled but had liquid in them (e.g.: beakers) don't just lose their reagents, it gets output in bottles as well

**Comment by uazuaz** [comment]
boxes are already recycled to cardboard like other items made of paper and cardboard (if i remember right, even pizza containers and paper sheets), but you need to interact with the sorting machine and enable the "miscellaneous" filter to send boxes and other stuff to the recycling furnace.

note that the sorting machine is not reachable on deff, a windoor could be added there.

**Comment by Exxion** [comment]
Disposals was a mistake
1. The sorting machine fails to put recyclables on the recycling belt fairly often, at least on default settings
2. If it does put a recyclable container on the recycling belt but not everything in the container is recyclable, the unrecyclable trash will just pass straight through the furnace and stacking machine and plop out in the place stacks from the stacking machine are supposed to go, which is very annoying to correct

Either there should be a second sorting machine, or the furnace/stacking machine should work differently

**Comment by SkowronX** [comment]
Isn't there a var you can define for objects to be recycled into?

**Comment by PJB3005** [comment]
The way it works is that objects have a category for recycling. The sorter round start has some of these categories enabled.

This category is completely separate from whether the object can be recycled in practice.
