### ISSUE TITLE
Ian can't drive adminbuses

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#13654]
Critical issue please fix immediately

**Comment by Killette2** [comment]
Did you try putting the captain hat on him first?

**Comment by Probe1** [comment]
this is why we have 1500 issues.

**Comment by Exxion** [comment]
Ian SPECIFICALLY is SUPPOSED to be able to drive the adminbus though

I'm not joking
If memory serves, it specifically checks if the person attempting to drive it is a test dummy or Ian (by a typecheck, of course, so there's no way to override it in-game)
You can't make this stuff up

**Comment by Exxion** [comment]
I mean
Nobody in their right mind would ever use the adminbus on the live server
But it's still a bug

**Comment by mrpain666** [comment]
Y-yeah! It's not l-like I gave every admin keys and started teaching them how to use it. N-nope!

**Comment by Exxion** [comment]
How much teaching does one need? Just try it on the test server. The buttons are mostly self-explanatory anyway.

Also, *why*?

**Comment by PJB3005** [comment]
> he doesn't just proc call his way into the adminbus seat.

pffff

**Comment by Zth--** [comment]
```
/obj/structure/bed/chair/vehicle/adminbus/buckle_mob(mob/M, mob/user) 
        if(M != user|| !ismob(M)|| get_dist(src, user) > 1|| user.restrained()|| user.lying|| user.stat|| M.locked_to|| istype(user, /mob/living/silicon)|| destroyed) 
                return 
 
        if(!(istype(user,/mob/living/carbon/human/dummy) || istype(user,/mob/living/simple_animal/corgi/Ian))) 
                if(!occupant)  
                        to_chat(user, "<span class='warning'>Only the gods have the power to drive this monstrosity.</span>")//Yes, Ian is a god. He doesn't have his own religion for nothing. 
 
                        return 

```

**code/game/objects/structures/vehicles/adminbus.dm**

**Comment by Shadowmech88** [comment]
While I wasn't actually able to drive the bus due to apparently not having `R_ADMINBUS` on my local server, as Ian I was able to get the "you are a god, but you don't have your license" message, which based on the code suggests that I would have been able to drive as Ian with sufficient admin permissions.
As such, it seems this bug no longer exists.
