### ISSUE TITLE
Natural bluespace crystals can be mass-produced in the general fabricator

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13656]
SKREEEEEEEEEEEEEEEEEEEEEEEEE trader shit is useless

**Comment by Exxion** [comment]
Natural* bluespace crystals

Memes aside I have no idea what to tag this

**Comment by despotate** [comment]
Balance, oversight at the very least

This lets traders keep the entire box for their own shenanigans and only hand out one natural crystal for the mechanic to infinitely dupe

**Comment by Shadowmech88** [comment]
Logically, scanning a natural bluespace crystal and printing the design in the general fabricator should create an artificial bluespace crystal.
