### ISSUE TITLE
Supermatter Cascade Bugs

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#13652]
This shit was working when I left but it falls to me to fix it apparently.

Meta-Issue for all the SMC bugs.

* [ ] Whoever coded the lighting shit did it wrong and it takes place AFTER the galaxy-wide alert thing
* [x] Lights are green. (?!)
* [x] Slow damage to the station not occurring
* [x] Supermatter sea has some graphical issues
* [x] Supermatter sea looks like shit
* [x] Bluespace rift hitbox is 3x3 when it should fit the size of the sprite.
* [x] Does not fuck with parallax colors (Would be neat to get brand new parallax textures but probably won't happen)
* [ ] People have shovelled awful music into the apocalypse playlist, needs a review.

**Comment by ihadtoregisterforthis** [comment]
http://ss13.moe/media/?playlist=endgame&type=html for the last point
