### ISSUE TITLE
plagiarize these potions and win 5 crummy funbucks from my steam wallet

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13661]
I want to see potions in the game
I need someone to sprite them
I have carefully prepared this spritesheet with plenty of reference so that you may plagiarize them and make them spess-grade
![potiens](https://cloud.githubusercontent.com/assets/6526157/22358337/0adaf342-e41d-11e6-8fe4-f2ec34c8c3c6.png)

ABOUT THE POTIONS:
I'll implement them in some way after sprites are provided, I was thinking that the empty potion flasks could be available via cargo/premium item and they could be filled by players with whatever mememix they fancy (plasma-resist potion with leporazine+whatever, 5u of every healing chemical in the game, etc etc) so that the players can run their own lame potion seller gimmicks
After that, I guess pre-filled potions could be added as a potion bundle for wizards, to finally give them a way to heal themselves, BUT a limited use and rather cumbersome one (wizards with infinite heals would be hell)
There's large bottles and small bottles, here's my fun thought: The small ones can only be consumed via "Quaff", which drinks the entire potion in one go, so kind of like a pill that you can examine to see contents. The big ones are basically just reskinned alcohol bottles as available from the bar.

ABOUT THE SPRITES:
The reference ones aren't spess-grade, they are literally stolen from various game wikis and have clashing palettes and O U T L I N E S. They are obviously references to guide yourself from aka trace.
Since this is a personal request that is like 80% sprites I will be offering 5$ from my steam wallet if the sprites are real nice
Ideally the best way to go about these would be to sprite the empty bottle and, in a different photoshop layer, have the colored content overlay, so that it can be re-colored and we can have like 4 different colors of each shape of flask and have a super fancy overlay for the wiz ones. Maybe even use the empty flask sprite after the potion is fully emptied.
At least one Diablo II potion must be included THIS IS NOT NEGOTIABLE

**Comment by CptWad** [comment]
cool maybe I might try
no promises

**Comment by N3X15** [comment]
Please god don't steal them verbatim, we don't need any more bullshit for goon to fake-DMCA us with.

**Comment by CptWad** [comment]
![45675](https://cloud.githubusercontent.com/assets/3959840/22362039/7f95fff0-e414-11e6-886a-1c9d20ed4b2a.png)
hows this look

**Comment by Shadowmech88** [comment]
What's the yellow thing hanging off the cap?

**Comment by CptWad** [comment]
[fug.zip](https://github.com/d3athrow/vgstation13/files/734579/fug.zip)
here
![image](https://cloud.githubusercontent.com/assets/3959840/22363028/2ac6f030-e41c-11e6-9587-ff89a47085a5.png)
The "orb" ones are animated
I tried to do themes in respective order: "Swirling mass, Space, Heartbeat, SPEED and The Sun"

**Comment by CptWad** [comment]
@Shadowmech88 WOOPS
forgot that
![image](https://cloud.githubusercontent.com/assets/3959840/22363083/9a45d6c4-e41c-11e6-81e7-a4ded09ce7d2.png)

**Comment by kol1th** [comment]
those are gonna be HUGE on tables and such, remember that

**Comment by Exxion** [comment]
@N3X15 Goon can't DMCA over a sprite that doesn't belong to them
And just redrawing them isn't any worse than our xenos or stunbatons

**Comment by CptWad** [comment]
should I make them smaller then? I understand how sprites get blown up in game, I guess the small potions should be taken down to size

**Comment by 9600bauds** [comment]
Honestly, I would like if someone just redrew some of the ones I posted. I especially like the ones in row three, they're a very nice size. Only problem is making them consistent with SS13 style/pallette
Also should be 7 or so so we can fill a box of them

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/22379832/e4751518-e46f-11e6-8c22-d0fa1bedf4a4.png)
I did some more
So the consensus is smaller? but I had such FUN doing the animated ones
[fug.zip](https://github.com/d3athrow/vgstation13/files/735819/fug.zip)
heres the progress I got so far, when I get back to this ill try smaller,

**Comment by Shadowmech88** [comment]
We can have big ones, just look at the alcohol bottles, after all. They're as big as a person.
I think there should also be small ones, though, about the size of our chemistry bottles.

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/22384889/3be598bc-e485-11e6-9f76-ab5e37d0be0f.png)
okay is this smaller/better
![image](https://cloud.githubusercontent.com/assets/3959840/22384905/4eedb674-e485-11e6-8f62-b31a8f01d500.png)
![image](https://cloud.githubusercontent.com/assets/3959840/22384913/5a067316-e485-11e6-9c49-a97a7b9baf5f.png)
![image](https://cloud.githubusercontent.com/assets/3959840/22384925/6847d690-e485-11e6-9b4a-e1ec2f0cb851.png)

**Comment by Shadowmech88** [comment]
The cap is hanging off the mouth of the bottle only on one side and it bothers me.
They look really good, though.

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/22385249/c8a6e55c-e486-11e6-9405-44d4a024d22a.png)
?

**Comment by Shadowmech88** [comment]
Those look perfect.

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/22386073/497ae842-e48a-11e6-8ec0-16595e810576.png)

now with animated vials and empty containers
[fug.zip](https://github.com/d3athrow/vgstation13/files/736172/fug.zip)

**Comment by Zth--** [comment]
I really like them, but why don't you make them uncolored so you reutilize the beaker code?

**Comment by CptWad** [comment]
b/c I didnt see that part of the request
also where are the sprites for such things, I am looking at chemicals.dmi and have no idea where to start doing that

**Comment by Shadowmech88** [comment]
reagentfillings.dmi

**Comment by Riekland** [comment]
What's the point of adding vials? We already have the cunts in the code.
Also, there needs to be more shades on those brown bands, there only being three makes it look cartoony

**Comment by CptWad** [comment]
diablos theme is grimdark, ss13's is cartoony 
but ive updated a lot so far based on shitposts on the thread
heres some samples
![image](https://cloud.githubusercontent.com/assets/3959840/22391536/b4dc891c-e4a6-11e6-98db-820ac2f3a752.png)
![image](https://cloud.githubusercontent.com/assets/3959840/22391548/be774980-e4a6-11e6-9c0c-997def5aa152.png)
![image](https://cloud.githubusercontent.com/assets/3959840/22391556/c8cfb840-e4a6-11e6-902a-976c0811da00.png)
![image](https://cloud.githubusercontent.com/assets/3959840/22391564/d111ed3e-e4a6-11e6-847b-50045dd6ead4.png)
![heart](https://cloud.githubusercontent.com/assets/3959840/22391599/02197eba-e4a7-11e6-9605-ee1e400843f0.gif)
![space](https://cloud.githubusercontent.com/assets/3959840/22391600/021a51e6-e4a7-11e6-815d-a73c17f1d32d.gif)
![sun](https://cloud.githubusercontent.com/assets/3959840/22391601/021ace14-e4a7-11e6-94ce-f667c94d9a20.gif)
![matrix](https://cloud.githubusercontent.com/assets/3959840/22391602/021c05fe-e4a7-11e6-808c-e8591fecd8be.gif)
![mass](https://cloud.githubusercontent.com/assets/3959840/22391603/021cbc38-e4a7-11e6-994b-c97159c5565d.gif)

**Comment by CptWad** [comment]
other questions/answers
>why vials

Felt like I could? Also I wanted little fizzy effects

>reagentfillings.dmi

alright, should I make similar things inside potions.dmI or add them into reagentfillings.dmi?

**Comment by Zth--** [comment]
Add them into reagentfillings (please)

**Comment by CptWad** [comment]
Added reagentfillings.dmi updates
functionality for custom color reagents ready for all but the erlenmeyer flask since ill probably replace it later
removed all the shit flasks/erlenmeyer flasks and replaced most
snazzier animations
![image](https://cloud.githubusercontent.com/assets/3959840/22392849/c7d53c74-e4b2-11e6-9807-07cbbfbbd7a8.png)
[fug.zip](https://github.com/d3athrow/vgstation13/files/736596/fug.zip)

**Comment by CptWad** [comment]
woops, I fucked something up in the last zip file
well heres my "done" zip. suggestions and all are still welcome
[fug.zip](https://github.com/d3athrow/vgstation13/files/736614/fug.zip)

**Comment by Blithering** [comment]
Made a quick attempt at turning some of row 3 into a more uniform palette. Definitely a lot more plagiarism-y than CptWad's flasks, but I liked the designs and thought they would make good premade wizard ones.
![wizflask](https://cloud.githubusercontent.com/assets/15067109/22408396/0cc59afe-e670-11e6-8af1-279dc9bac716.png)

**Comment by 9600bauds** [comment]
I'm on a little spessvacation for the time being so I'll come back to this in a week or so, tyty very much for all your entries

**Comment by pvak** [comment]
can you add a box of empty potion flask in the wizard crate?
