### ISSUE TITLE
RD access is shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13665]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
rd doesnt have access to things like the tech storage, eva and ai modules windoor

>What you expected to happen
have access to shit that rd is supposed to have

>What actually happened
no access

>Steps to reproduce if possible
be rd

**Comment by Probe1** [comment]
>RD doesn't have access to things like (Engineering area)

I know where to find you Pvak.

**Comment by PJB3005** [comment]
@Probe1 roboticists do.

**Comment by Probe1** [comment]
That's because roboticists used to be in engineering ages ago.

**Comment by pvak** [comment]
why would tech storage be considered ""engineering"" ?

**Comment by Probe1** [comment]
It is next to engineering, is filled with engineerings things, requires engineering access, and meets the needs of engineers.  

We didn't accidentally forget to give the RD insulated gloves.  He's not supposed to get them, or have access there.

And for other things

>Lawboards

Only the Cap has access to these.  You could ask why the CE, HoP, HoS, or CMO don't have access and get no closer to the answer of "It's captain restricted"

>EVA

Giving doctors access to EVA was a shitty idea but that isn't rectified by giving every last department on the station access.

**Comment by 9600bauds** [comment]
But he does have access to telecomms storage :^)

**Comment by Probe1** [comment]
Yeah telecomms has fallen under the dual purview of the RD/CE ever since the abandonment of the telecomms satellite.  You can draw a clear line between the RD (who has the telecomms mainframe password in his office) to telecomms.

**Comment by pvak** [comment]
>It is next to engineering, is filled with >engineerings things
how are the circuits boards "engineering things"

**Comment by Exxion** [comment]
They're for building machines

**Comment by CptWad** [comment]
Its spare boards for when engineers rebuild destroyed parts of the station
research can literally print the boards so they have no need for getting in there, if anything roboticsts should probably stop having access to tech storage.
