### ISSUE TITLE
Dumping ore boxes with 1000+ ores results in the server lagging out hard

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13668]
1.  Get an ore box
2.  Fill it with a fuckton (1k+, 3k for maximum effect) ores
3.  Press dump all ores
4. Server lags the fuck out.

Needs to only dump x many at a time no matter what.

**Comment by 9600bauds** [comment]
Does it lag from the act of dumping the 1000 ores, or from the 1000 ores on the ground?

**Comment by Exxion** [comment]
Probably the act of dumping 1000 ores
I don't think a measly 1000 items just sitting around would lag the server
Or at least I hope not

**Comment by Zth--** [comment]
**>** **oh hey I just wanted to pick up the diamond**
**>** **right click the tile**

![BOOM](http://i.dailymail.co.uk/i/pix/2009/01/18/article-0-0319BA1D000005DC-327_468x286.jpg)

**Comment by Exxion** [comment]
Alt+click

**Comment by PJB3005** [comment]
I don't think alt click can save you from this.

**Comment by Exxion** [comment]
Not from the server lag, but from what @Zth-- said

**Comment by Zth--** [comment]
I personally use altclick, but newbies don't know it exists. That literally happened to me when I was learning the game

**Comment by beesil** [comment]
Fixed by #22392 (hopefully)
