### ISSUE TITLE
Infinite spell points

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13666]
If you take the no robes spell and no other spells, you get a spell master for your new "spell" on the top right. Clicking on this removes it from your screen. 

After this happens, hitting "refund spells" will give you your ten points back and tell your that you've forgotten no robes. However, you can keep refunding these 10 points over and over and wind up with as many spell points as you want.

**Comment by Killette2** [comment]
Pretty sure this is intentional. It is used for roleplay where you happen to be a better than average wizard.

**Comment by Kitfox88** [comment]
finally i can secure greentext when i roll wiz

**Comment by Exxion** [comment]
Fixed by #13858, but was not autoclosed correctly
