### ISSUE TITLE
Heat exchange pipes are hard to click, make them mouse opacity 2

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#13679]
Easy fix.

**Comment by Exxion** [comment]
That makes it impossible to click ones on lower layers without Alt+click
Personally, I think they're fine, but if more people agree they're too hard to click, let me suggest we use a mask rather than `mouse_opacity`

**Comment by Zth--** [comment]
A mask could work too. But something needs to change, they're really hard to click. Also I think it's already impossible to layer them without altclicking

**Comment by Aurx** [comment]
Best solution would be to make the pixels inbetween the tiny pipes part of the clickzone.

**Comment by PJB3005** [comment]
@Zth-- the RPD defaults to using get turf for whatever thing you click on, and the pipe item you need to wrench down is always layered above the pipes anyways.

Not sure what the problem is here.

**Comment by jknpj** [comment]
alt+click

**Comment by Zth--** [comment]
this was addressed some time ago
