### ISSUE TITLE
Mr. Clean is now Narsie.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13678]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
389af6a6902692c9a95ef04fbc98258cf3d90c35 

>General description of the issue
/obj/machinery/singularity
/narsie/large/clean

Now uses Narsies sprite, rather than Mr. Clean

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

I blame the new narsie animation. While sick nasty - I hope you can bring clean back.

**Comment by jknpj** [comment]
Oversight. I'll fix it
<s>but maid nar-sie sounds fun too</s>
