### ISSUE TITLE
Medical Research Vault: Doors in Space

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#13673]
Revision: 8bbd1ed5ba4e9afa00a8080a3ea49eb078a6c31b 

![2017-01-27_12-35-59](https://cloud.githubusercontent.com/assets/110073/22386829/b50abaa8-e48d-11e6-9340-0b8fc1a4fd7d.png)

/cc @Shadowmech88

**Comment by Shadowmech88** [comment]
Oh, meaning there's space tiles under the doors?
