### ISSUE TITLE
Using the food processor to gib destroys items

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13680]
(WEB REPORT BY: agentofzog REMOTE: 172.93.109.202:7777)
Revision: 389af6a6902692c9a95ef04fbc98258cf3d90c35 

>General description of the issue

If you put a chicken suit on someone and turn them into nuggets via the food processor, some items (usually the clothing and some other stuff) will get destroyed. 

According to Zealotron it's a bug that has something to do with a ckey being inside the corpse or something like that.

>What you expected to happen
being able to reuse the chicken suit and get people's shit

>What actually happened
suit is one use only and phat loots are lost

>Steps to reproduce if possible

put the chicken suit on someone still active, 
stuff em in the food processor
watch stuff pop out then instantly dissapear

(also I think this way might  make more nuggets than normal  but I'm not sure)

**Comment by TheFriggenSawbones** [comment]
To explain it better,

If you're inside the body while its being processed - the chicken suits fly out but it ends up disappearing.

However if you ghost/put a braindead body in the chicken suit will come out.

**Comment by west3436** [comment]
Has been the case for long enough now that this no longer seems to be a bug
