### ISSUE TITLE
We probably want to nerf Vox Traders/Xenoscientists' ability to upload laws at will

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13688]
I'll admit it, I've been tradertiding the last few days to see how far I could go without being detected by the main station. If you trade for the research console and circuit imprinter boards and a packet of berry seeds, you can construct the basic research consoles and screwdriver/unscrewdriver to unlock, sync techs, and sync with nearby machines, and mutate berry seeds into glowberries to EMP the AI upload that you shit out using the materials you start with in the den and its easily hacked vault. This level of powergaming doesn't actually take that much time, complexity, or cooperation, and is nearly undetectable by those on the station. At the end of it you get an AI upload with any module you want to print and EMP, so it's definitely a strategy that needs to be removed from Traders. You could probably do a very similar thing as research botanist and not even have to interact with anyone doing it, though there's less of an RP reason to do it.

A possible fix would be to just disable AI uploading from the asteroid but it's trivial to just unwrench, move the shuttle, wrench, upload, unwrench, move the shuttle without being detected.

The necessary fix here is likely to remove the ability to screwdrive/unscrewdrive the research console to gain access and sync.

**Comment by Probe1** [comment]
Crap did I not tell bauds to do this?

I meant to.  Yeah nothing except the silicon uploads work like that.

**Comment by Kurfursten** [comment]
It would be nice if the AI core had an intelligence upload bus that needed to be linked to the AI and upload console. In other words, simply building an upload console wouldn't be useful unless you can visit the core too.

**Comment by PJB3005** [comment]
@Kurfursten then the issue is that the AI can nuke the main upload and now you need to get into its core to make it not malf.

**Comment by Kitfox88** [comment]
UNSECURED

WIFI

why not just make law uploads require a passcode that's randomly generated at the start of each round? have a paper with it start in obvious places like rd's office, cap's office, etc?

**Comment by Sprok0** [comment]
I like that, make sure the AI can't know it and it'd cut down on "AI law two open the upload and turn off the turrets, say nothing" effortless subversions

**Comment by Kurfursten** [comment]
@PJB3005 Who doesn't just kill the AI when it's malf?

**Comment by PJB3005** [comment]
I meant rogue and subverted with laws, derp.

**Comment by Ephx1** [comment]
@Sprok0 
You're right, now it's "AI get a borg to tell me the password on the paper in the RD Office/Captain Office, then shut off your turrets, let me into your upload, and don't say anything about it"

**Comment by Rattlederp** [comment]
Asimov sure is a good lawset

**Comment by Exxion** [comment]
Just put it in the notes of the RD and roboticists and fuck the paper

**Comment by Ephx1** [comment]
@Rattlederp
Asimov is the sharpest double-edged sword ever, as it gives most antags and normal players an equal standing. Others are fairly vague to the point of anger from players if not followed in their eyes or will instantly wreck antagonists.

@Exxion 
That doesn't sound good, roboticists and research directors are among the first to die if the AI goes wrong. So if you have a rogue set of silicons, there goes any chance you had of resolving it peacefully. Plus if you do have to kill the AI, there would be literally no way to fix it (in terms of laws), I don't think it's good to remove a player from the round due to someone else's doing.

**Comment by Exxion** [comment]
Blowing borgs for being subverted is common practice if they're dangerous, but I see what you mean

**Comment by Ephx1** [comment]
There would need to be a dismantling process for AI cores before I would support that. As you know, they're only moveable between a card and another core. Perhaps if different cores held different lawsets that would patchwork the issue of that.

**Comment by Sprok0** [comment]
I would assume that reset and asimov core modules wouldn't need the password, to allow for un-subverting to be done reasonably

**Comment by Ephx1** [comment]
That works too I suppose

**Comment by Killette2** [comment]
A password will nerf traitors making laws with a hacked AI upload freeform board hidden somewhere, I do not like that

**Comment by AlphaBuffalo** [comment]
Make the hack board not need a password

**Comment by ghost** [comment]
With regular AI uploads restricted to z-level and long-range available through high tech or the upload seems done.
