### ISSUE TITLE
The syndicate radio channel can be recorded with telecomms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13681]
(WEB REPORT BY: gutlesscoward REMOTE: 172.93.109.202:7777)
>Revision
389af6a6902692c9a95ef04fbc98258cf3d90c35

>General description of the issue
if you link the syndicate radio channel to a subspace broadcaster, a tcomms bus, and a server, you can listen in on anything said on the syndicate channel. this can be used to find out if there are nuke ops/vox squads.

>What you expected to happen
I expected the syndicate channel to be blocked from telecomms equipment
>What actually happened
the syndicate channel was able to be recorded with telecomms equipment. scripts could even be run, though I don't recall being able to pass any messages to the syndie channel. I could tell when someone spoke on syndie radio though!

>Steps to reproduce if possible
1.use multitool on subspace broadcaster, add a filter frequency of 1213.
2.use multitool on a bus, add a filter frequency of 1213.
3.use multitool on a server, add a filter frequency of 1213.
4.use the telecomms computer (not the script computer) to open the logs of the syndicate channel. do keep in mind that any other frequencies linked with it will also be logged.

**Comment by DamianX** [comment]
@Probe1 I think this was fixed

**Comment by Exxion** [comment]
Appears so.
