### ISSUE TITLE
[Boxstation] Mechanics workshop doesn't have an AI holopad

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13683]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
389af6a6902692c9a95ef04fbc98258cf3d90c35 

>General description of the issue
The Mechanics Workshop on box doesn't come with an AI holopad. This is a shame. Likely an issue with the other maps as well.

**Comment by Aurx** [comment]
Why WOULD it have a holopad?

**Comment by SonixApache** [comment]
Every science division has a holopad, why not mechanics?
