### ISSUE TITLE
Cyber horrors on the medical research vault don't shut up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13695]
(WEB REPORT BY: agentofzog REMOTE: 172.93.109.202:7777)
Revision: 5b94be417e0a00aff0575b7e048f43dea50c50f6 

it's the goonsat horrors all over again, just let me oberve in peace

>What you expected to happen
peace and quiet and shittalking the vampire

>What actually happened
(follow) cyber horror groans, "H@!#$$P M@!$#"

(Follow) cyber horror groans, "GHAA!@@#"

(Follow) tajaran cyber horror emits, "K!@@##L!@@ %!@#E"

(Follow) cyber horror emits, "GHAA!@@#"

(Follow) tajaran cyber horror emits, "K!@@##L!@@ %!@#E"

>Steps to reproduce if possible

observe

**Comment by Exxion** [comment]
All in favor of making ghostears ignore playerless simple mobs, vote this comment up
All opposed, vote down

**Comment by N3X15** [comment]
/cc #13692

I plan to do an overhaul of them after I'm done with component mobs so they only start mouthing off when there's a client'd mob nearby.
