### ISSUE TITLE
ghost hands + old shitcode + large artifacts = ???

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13690]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
the giga drill and the replicator thing can be activated by ghosts

>What you expected to happen
ghosts being friends

>What actually happened
ghosts griffing people

>Steps to reproduce if possible

touch machines while a ghost

**Comment by Exxion** [comment]
Giga drill: Who gives a shit? It's currently being completely rewritten and the worst you can do is turn it off while someone is using it, which would be difficult because nobody in their right mind would use it

Replicator: Oh *boy*

**Comment by AutismSpider** [comment]
Replicator can make  mobs like mimics if the ghost finds the right button

**Comment by Sprok0** [comment]
See #13186, the replicator being usable by ghosts is intended

**Comment by Exxion** [comment]
That's dumb, but whatever
Looks like I'm outvoted

The giga drill one is technically still an issue, but a really minor one, which there's no point in fixing before the rewrite
Still, I'll leave this open for now

**Comment by Riekland** [comment]
IT'S
A
FEATURE
literally every time a xenoarch has his thing used by ghosts they make an issue here
there's been what, four in the past week
read the goddamn git before making an issue

**Comment by Zth--** [comment]
Not a bug.

**Comment by jknpj** [comment]
It's a feature.
