### ISSUE TITLE
Attack logging runtiming

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#13696]
These events were neither present in Linda Blanch's VV attack logs nor the server attack logs.

Runtime stack traces in order:

[23:22:02] Runtime in , line : bad arg name 'adminwarn'
proc name: add attacklogs (/proc/add_attacklogs)
usr: Linda Blanch (sergewind) (/mob/living/carbon/human)
usr.loc: The floor (248, 230, 1) (/turf/simulated/floor)
src: null
call stack:
add attacklogs(Linda Blanch (/mob/living/carbon/human), Gerald Forlo (/mob/living/carbon/human), "force-fed", the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), "amount:5, container containing...", null)
the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large): attack(Gerald Forlo (/mob/living/carbon/human), Linda Blanch (/mob/living/carbon/human), null)
Gerald Forlo (/mob/living/carbon/human): attackby(the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), Linda Blanch (/mob/living/carbon/human), "icon-x=18;icon-y=16;left=1;scr...", null)
Linda Blanch (/mob/living/carbon/human): ClickOn(Gerald Forlo (/mob/living/carbon/human), "icon-x=18;icon-y=16;left=1;scr...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=16;left=1;scr...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=16;left=1;scr...")

[23:22:04] Runtime in , line : bad arg name 'adminwarn'
proc name: add attacklogs (/proc/add_attacklogs)
usr: Linda Blanch (sergewind) (/mob/living/carbon/human)
usr.loc: The floor (248, 230, 1) (/turf/simulated/floor)
src: null
call stack:
add attacklogs(Linda Blanch (/mob/living/carbon/human), Gerald Forlo (/mob/living/carbon/human), "force-fed", the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), "amount:5, container containing...", null)
the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large): attack(Gerald Forlo (/mob/living/carbon/human), Linda Blanch (/mob/living/carbon/human), null)
Gerald Forlo (/mob/living/carbon/human): attackby(the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), Linda Blanch (/mob/living/carbon/human), "icon-x=18;icon-y=-16;left=1;sc...", null)
Linda Blanch (/mob/living/carbon/human): ClickOn(Gerald Forlo (/mob/living/carbon/human), "icon-x=18;icon-y=-16;left=1;sc...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=-16;left=1;sc...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=-16;left=1;sc...")

[23:22:08] Runtime in , line : bad arg name 'adminwarn'
proc name: add attacklogs (/proc/add_attacklogs)
usr: Linda Blanch (sergewind) (/mob/living/carbon/human)
usr.loc: The floor (248, 230, 1) (/turf/simulated/floor)
src: null
call stack:
add attacklogs(Linda Blanch (/mob/living/carbon/human), Gerald Forlo (/mob/living/carbon/human), "force-fed", the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), "amount:5, container containing...", null)
the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large): attack(Gerald Forlo (/mob/living/carbon/human), Linda Blanch (/mob/living/carbon/human), null)
Gerald Forlo (/mob/living/carbon/human): attackby(the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), Linda Blanch (/mob/living/carbon/human), "icon-x=18;icon-y=16;left=1;scr...", null)
Linda Blanch (/mob/living/carbon/human): ClickOn(Gerald Forlo (/mob/living/carbon/human), "icon-x=18;icon-y=16;left=1;scr...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=16;left=1;scr...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=16;left=1;scr...")

[23:22:09] Runtime in , line : bad arg name 'adminwarn'
proc name: add attacklogs (/proc/add_attacklogs)
usr: Linda Blanch (sergewind) (/mob/living/carbon/human)
usr.loc: The floor (248, 230, 1) (/turf/simulated/floor)
src: null
call stack:
add attacklogs(Linda Blanch (/mob/living/carbon/human), Gerald Forlo (/mob/living/carbon/human), "force-fed", the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), "amount:5, container containing...", null)
the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large): attack(Gerald Forlo (/mob/living/carbon/human), Linda Blanch (/mob/living/carbon/human), null)
Gerald Forlo (/mob/living/carbon/human): attackby(the large beaker (/obj/item/weapon/reagent_containers/glass/beaker/large), Linda Blanch (/mob/living/carbon/human), "icon-x=18;icon-y=-16;left=1;sc...", null)
Linda Blanch (/mob/living/carbon/human): ClickOn(Gerald Forlo (/mob/living/carbon/human), "icon-x=18;icon-y=-16;left=1;sc...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=-16;left=1;sc...")
Gerald Forlo (/mob/living/carbon/human): Click(the floor (249,231,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=18;icon-y=-16;left=1;sc...")

**Comment by ghost** [comment]
I'll look into it

**Comment by ghost** [comment]
Found the problem, fixing now
