### ISSUE TITLE
toggle botton for hiding mobs messages

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13692]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
some mobs fill the chat with messages

>What you expected to happen
being able to toggle off mob messages 

>What actually happened
 cyber horror groans, "KR@!!N"

(Follow) cyber horror groans, "G@#!$ H@!#%, H!@%%@ @!E"

(Follow) tajaran cyber horror groans, "GHAA!@@#"

(Follow) cyber horror groans, "G@#!$ H@!#%, H!@%%@ @!E"

(Follow) cyber horror emits, "H@!#$$P M@!$#"

>Steps to reproduce if possible
be a ghost and get your chat flooded with this shit

**Comment by Exxion** [comment]
Man, what have we said about using the web reporter for feature requests?
