### ISSUE TITLE
leather stack drying isnt working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13703]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
istead of 10 leather i got a stack of 0 leather

>What you expected to happen
10 leather

>What actually happened
There are 0 leather pieces in the stack.

>Steps to reproduce if possible
dry 1 stack of leather
get nothing

**Comment by Kammerjunk** [comment]
Last update 9 days ago
@Shadowmech88 Something about
```
if(src.use(amount))
	drop_stack(/obj/item/stack/sheet/leather, src.loc, amount)
```
this?

**Comment by Shadowmech88** [comment]
I *did* test it. Not sure what's happening.

**Comment by Exxion** [comment]
It uses the amount
*Then* reads it as the number to drop

**Comment by gbasood** [comment]
rip amount

**Comment by Killette2** [comment]
I thought I reported this over a year ago when I tried tanning with a burn chamber

**Comment by Exxion** [comment]
That would have been an entirely different bug.

**Comment by Killette2** [comment]
So it is
