### ISSUE TITLE
Cult runes are white

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#13707]
Apparently this has been the case for quite a while, but nobody reported it

I'm almost certain I've tracked the cause down to somewhere in [Uristrunes.dm](https://github.com/d3athrow/vgstation13/blob/58def87fedc25b491eb63abd0a369a82b2c90558/code/game/magic/Uristrunes.dm) (specifically, `get_uristrune()`), but it's... not exactly well-documented or very inherently readable, so I'm not sure exactly what's fucked up

**Comment by Shadowmech88** [comment]
There was a PR some time ago to dynamically color runes based on the blood color of the person who drew them, which I'm guessing necessitated making the base rune sprites white.
The error is likely somewhere in the code that's actually supposed to color the runes.

**Comment by Exxion** [comment]
Yeah
That code is where I said in the OP

**Comment by Exxion** [comment]
Oh dear
I read farther in the code I linked
I see multiple errors, but they're all minor and  wouldn't cause this

I also see an absolute shitshow below that with readability values reaching new lows

**Comment by Exxion** [comment]
Oh good, it's not in the inscrutable parts
I'll fix this in a jiffy
