### ISSUE TITLE
Repeatedly using a screwdriver on the detective's computer makes infinite manuals

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#13719]
Related links: #6760, #6769
#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Zth--** [comment]
~~IIRC it's a blank book~~. Simply map the book and remove the snowflake from the machine

**Comment by Probe1** [comment]
top kek
