### ISSUE TITLE
The four "new" vox colors don't have tails

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#13714]
It looks really silly

**Comment by ihadtoregisterforthis** [comment]
Always? Because I remember the tails being part of the torso gib sprite. Do they have chests?

**Comment by Exxion** [comment]
I don't know if it's always
They don't in the character preview, and at least at the one time I checked, light green didn't have one in-game

**Comment by Exxion** [comment]
So this apparently broke sometime *after* the colors were added
Somehow

I *think* that vox had the tails attached as an overlay like other species do, but this somehow got removed
The green/brown/gray vox sprites also have the tails drawn directly onto the torso sprite, so the absence of the overlay was invisible
The other four do not

But as far as I can tell, yes, the tails are always absent now

**Comment by Intigracy** [comment]
We didn't have tails as an overlay when I added the brown/green/gray

Polaris probably uses overlays for the tails though since they have furry customization, since the "new" (the light green one is the old one) ones are just rips from Polaris that'd explain the lack of them on the torsos.

**Comment by Exxion** [comment]
Goddamn it
I was just about to say "wait, but I can't find where the tail sprites would have been, and also vox never had `HAS_TAIL`"

But fuck
Now we have to go rip those tails

**Comment by Exxion** [comment]
That also means that the screenshot in the PR adding them wasn't actually taken in-game
Because the tails are clearly visible there
Which is why I thought it broke afterward

**Comment by Aurx** [comment]
.100% tested, as usual.

**Comment by ghost** [comment]
sorry bros, the picture in the PR is actually from Para
