### ISSUE TITLE
You can bypass being unable to wrench machinery down on shuttle tiles by simply deconstructing and reconsructing the machinery

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13722]
This seems to work on the vox shuttle last I checked, likely works on all shuttles. 
If you try to use a wrench on unwrenched machinery, it'll tell you that you can't wrench it down there. 
If you use a screwdriver and crowbar to disassemble the machinery, it'll spawn a wrenched-down machine frame and its components. Adding the components back to the machine frame and using a screwdriver finishes construction and grants you a wrenched-down machinery. 
Does not work on computer frames because those spawn an unwrenched frame when disassembled.

**Comment by jknpj** [comment]
IT'S A FEEEEATURE. May also work with flatpacks

**Comment by Exxion** [comment]
Machines being bolted on construction was a mistake

**Comment by despotate** [comment]
Also, this does lead to hilarity as a vox trader when I construct an autolathe using this method and hack it without gloves, shocking it and making sparks fly but being completely unharmed because there's no actual power in the grid.

**Comment by kilozombie** [comment]
Why not just make machinery wrenchable down on shuttles?
Is it broken in ways I don't know? For instance: no power when shocked by it

**Comment by Exxion** [comment]
Shuttles aren't powered in the same way station areas are

**Comment by kilozombie** [comment]
Meh, yeah. That's not really solvable.

**Comment by pvak** [comment]
you can also build and deconstruct a wall to turn shuttle floor into normal floor

**Comment by Exxion** [comment]
I love our turf code

**Comment by Shadowmech88** [comment]
Would there be any consequences to just making all machines with `WRENCHMOVE` unwrenched when built?
Or would it be better to just prevent machines from being completed while on shuttle turfs?

**Comment by Pathid** [comment]
Consequence one is you'll always need a wrench to get a ``FIXED2WORK`` machine construction to a working state.
Consequence two is you'll be able to get a wrenched, completed machine to an unwrenched state with a screwdriver, a crowbar and no wrench.
