### ISSUE TITLE
Crew Monitoring Computer display problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13721]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
>Revision 340603ff0d0971f2a57aa49f875219c1b00e0127

>General description of the issue
There is no minimap when you open the CMC, simply the positions of the players, without the background.

>What you expected to happen
Having the background like in previous versions.

>What actually happened
No background.

>Steps to reproduce if possible
Go the CMC, see if there's a background minimap or not.

**Comment by PJB3005** [comment]
15 millionth dupe.

@clusterfack fix when.

**Comment by gbasood** [comment]
literally never

**Comment by Exxion** [comment]
I still think it's a BYOND issue
Unless this is a different bug, because all the HTMLUI maps have shit tons of them
