### ISSUE TITLE
Asthma and Inhalers when?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13727]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
Asthma and Inhalers when?

**Comment by Kurfursten** [comment]
All feature requests through the web reporter get tagged @Exxion

**Comment by Shadowmech88** [comment]
Maybe we should just add a separate bot for feature requests, complete with a "Feature Request" button in-game.

**Comment by Kitfox88** [comment]
feature request: feature request button in game

**Comment by Ephx1** [comment]
How about we just start banning people who use it to feature request?

**Comment by clusterfack** [comment]
Web reporter is not for feature requests
