### ISSUE TITLE
Virologist Spawns without Jumpsuit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13729]
(WEB REPORT BY: mrcantknow REMOTE: 172.93.109.202:7777)
>Revision 340603ff0d0971f2a57aa49f875219c1b00e0127 

>Virologist doesn't spawn with a juumpsuit 
>He should spawn with a god damn jumpsuit
>he didn't

>Spawn in as a virologist at roundstart or during the round

**Comment by Kurfursten** [comment]
more info; race?

**Comment by JustSumBody** [comment]
I know I had this happen on a plasmaman slot, but also that slot was still running a preferences set from when virologist was an alt medical doctor title.

**Comment by TheFriggenSawbones** [comment]
he was a human

**Comment by eplgr** [comment]
Happens to me always. Human. You spawn naked and with your ID and that kind of things in your backpack. 
Also, I was using one of those custom job titles.

**Comment by Kurfursten** [comment]
I just wonder how this took so long to be reported. Roughly 8 months ago we got the virologist back in #10175 and it was already buggy (missing a spawn for example). It also had fucked up two PDAs which wasn't fixed for two months in #10954 . Even as recently as two months ago Probe fixed the virologist not having access to the secure vial container in #12652

My question is: were virologists naked all this time, or is it more recent?

**Comment by AI-Is-Rogue** [comment]
I think this happens when your medical doctor custom job is set to virologist even though that was removed, I have been able to do this before as well.

**Comment by eplgr** [comment]
@Kurfursten I think it only happens with custom job names. But yes, all this time.
It really shows how little virologists are seen.

**Comment by jknpj** [comment]
`H.equip_or_collect(new /obj/item/clothing/under/rank/virologist(H), slot_w_uniform)`
`H.equip_or_collect(new /obj/item/clothing/mask/surgical(H), slot_wear_mask)`
`H.equip_or_collect(new /obj/item/clothing/shoes/white(H), slot_shoes)`
`H.equip_or_collect(new /obj/item/clothing/suit/storage/labcoat/virologist(H), slot_wear_suit)`
`H.equip_or_collect(new /obj/item/device/flashlight/pen(H), slot_s_store)`

Virologist job seems fine but there's no MD Virologist alt title so there you go

**Comment by Probe1** [comment]
Can anyone reproduce this

Has it gone away for the user
