### ISSUE TITLE
50+ stacks bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13737]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
if you fill a machine with 50+ more of a material and then deconstruct it all the material is in 1 stack like if i put 84 metal i ll get a 84 metal stack

**Comment by jknpj** [comment]
I- I'll just all it a feature. Are materials getting lost?

**Comment by Probe1** [comment]
nicetrylazycoder

though i doubt anyones gonna rush to fix this

**Comment by Aurx** [comment]
Why not just lift the stack cap and add a "split stack" button?

**Comment by Probe1** [comment]
So players can't carry too much of x too easily for nebulous balance reasons.

**Comment by Aurx** [comment]
Well yeah, but I can't honestly think of anything that'd be broken that can't be trivially broken by dragging a crate of sheets (1500 sheets) or even just grabbing a spare backpack and shoving it full of 350 sheets.  
I mean, really, when are you going to need 351 sheets for anything that anybody will care about balance-wise?
