### ISSUE TITLE
Can of Invisibility's infinite ersion is not actually infinite use

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13732]
(WEB REPORT BY: smallboss REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
4160a0228d058e83f083b3cafb1c3eecef42f467 

>General description of the issue
The infinite version of the invisiblility spray is not actually infinite.

>What you expected to happen
Give the clown a can of invisibility with infinite uses and get a deadmin request

>What actually happened
The can is only one use on a object/mob

>Steps to reproduce if possible
Spawn the infinite version of the invisibility spray
Notice how you can only use it once

**Comment by jknpj** [comment]
HONK

**Comment by ghost** [comment]
Just realized that the can just does not wear off, which is why it is counted as "infinite". Would be great if there would be another version for actual infinite uses and no wear off too. Honk.

**Comment by Intigracy** [comment]
@shadowmech88 Rename it to permanent or something.

**Comment by Exxion** [comment]
Yeah, permanent would be a better name

**Comment by Shadowmech88** [comment]
A version with infinite uses could be added as well, but in the meantime, admins can varedit the `sprays_left` var to a ludicrously high number in order to make that can functionally infinite.
