### ISSUE TITLE
Invisiblespray/infinite is not actually infinite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13735]
(WEB REPORT BY: cptwad REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
4160a0228d058e83f083b3cafb1c3eecef42f467 

>General description of the issue
When using the infinite invisible spray, it runs out after a single use

>What you expected to happen
easy adminbus

>What actually happened
gigantic mess of empty cans of used up "Infinite" cans.

>Steps to reproduce if possible
>Spawn invisiblespray/infinite
>Use spray
>Attempt to use again
>fail

**Comment by Exxion** [comment]
Dupe, and it means infinite duration, not infinite use.

**Comment by Exxion** [comment]
(#13732)
