### ISSUE TITLE
nutrition level is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13749]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
not sure what but i died of starvation with 150 nutriment

>What you expected to happen

not dying while i had nutrition
>What actually happened
rip

>Steps to reproduce if possible
eat a lot die of starvation

**Comment by ghost** [comment]
Not bugged, mousestarve is set at 200 and below. I'll set it to o
