### ISSUE TITLE
Lighting runtimes, super bed shitting action with lights powered on but giving off no light

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13743]
http://pastebin.com/V0tpCrCT

This is really bad half the station has lights on but no illumination.  Both lines indicated by the runtimes have not been changed in 8 months.

**Comment by Probe1** [comment]
```

[20:00:44] Runtime in lighting_source.dm, line 212: Cannot modify null.loc.

proc name: apply lum (/datum/light_source/proc/apply_lum)
src: /datum/light_source (/datum/light_source)
call stack:
/datum/light_source (/datum/light_source): apply lum()
Lighting (/datum/subsystem/lighting): fire(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing()

```

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/lighting/lighting_source.dm#L212

```

[20:00:44] Runtime in lighting_source.dm, line 264: Cannot modify null.loc.
proc name: smart vis update (/datum/light_source/proc/smart_vis_update)
src: /datum/light_source (/datum/light_source)
call stack:
/datum/light_source (/datum/light_source): smart vis update()
Lighting (/datum/subsystem/lighting): fire(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing()

```

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/lighting/lighting_source.dm#L264

**Comment by PJB3005** [comment]
Something is deleting dview.

WHO THE FUCK IS DELETING DVIEW?

**Comment by Probe1** [comment]
An admin was using build mode before the round started.

@N3X15 reported that this has happened to him during local testing once.

![image](https://cloud.githubusercontent.com/assets/8550416/22497227/0ffa2a78-e81e-11e6-892a-558a1ebd94cf.png)

**Comment by CptWad** [comment]
https://www.youtube.com/watch?v=YQpLNCRIxWA

**Comment by Exxion** [comment]
That is 100% the dview mob getting deleted, or at least dereferenced
How? No idea

**Comment by gbasood** [comment]
probably thanks BYOND
specifically might be us running out of memory

**Comment by SonixApache** [comment]
dunno about runtimes but i get lights that are on but don't produce light all the time when spooking stuff

**Comment by Exxion** [comment]
I think that happens when you spook the light at exactly the right time and it fails to update
