### ISSUE TITLE
Replace some hardsuits in box eva with softsuits

### ISSUE THREAD

**Issue by ThePlapatin** [d3athrow/vgstation13#13750]
Atmos tech is a max 3 slot job, it has 3 hardsuits in atmos. The 2 in eva are going to be used by non-atmos techs (powergaming assistants).

There's four engineering hardsuits in engineering, the two in eva are going to be used by non-engineers (powergaming assistants)

I think these hardsuits should be removed and replaced with softsuits, and the access doors removed so these softsuits are a more general for anyone in an emergency rather than specifically for job, it also means assistants greytiding for the atmos suit cannot powergame as easily as soft suits don't have the tank storage option. So people won't sit in hardsuits all round as carrying your bag in your spare hand is annoying, hopefully this will prevent some powergaming and make a more balanced game.

**Comment by ghost** [comment]
I would have to disagree. There are many times I have latejoined as an atmos tech and have had to get an EVA atmos suit due to all of the ones in atmos being taken either by engineers or greytiding assistants.

**Comment by uazuaz** [comment]
maybe not the engineering ones, but the atmos one could be replaced.
or maybe, replace 1 atmos and 1 engineering.

**Comment by ghost** [comment]
Anyone in engineering with sense will take an atmos suit when possible.  You also get plenty of time with 2-3 emergency tanks to the point that only silly people fuss with the large tanks

It'll be nice to see some of the power creep rolled back with more soft suits via eva.

**Comment by 9600bauds** [comment]
when the plasmafludd kicks in and all you got is a white cloth suit because one guy once saw an assistant in an atmos suit and decided to remove EVA rather than call security
![springfield-volunteer-fire-department-5](https://cloud.githubusercontent.com/assets/6526157/22511150/720e2d5e-e873-11e6-8547-04ca13bf9cd1.png)

**Comment by ThePlapatin** [comment]
When the plasmaflood kicks in you are already dead unless you are the powergaming assistant that greytided an atmos suit.

**Comment by ghost** [comment]
![eva_test1](https://cloud.githubusercontent.com/assets/9110500/22512966/9f5d6490-e892-11e6-9b84-9b0e9b161fb1.PNG)

Switched out the engineering and atmos hardsuits for 6 regular softsuits. With the extra room, I moved some of the tables into a sort of supply zone, and was able to fit some additional canisters in.

Y/N?

**Comment by jakmak** [comment]
It's probably fine the way it is currently since this is literally the only complaint about box EVA I have heard and not to mention as harse said when eng and atmos runs out of suits there is no way to get more. Not to mention the ghetto rigged suit made out of a fire suit, gasmask, and blanket is better than the grey shit suit in literally every way. Essentially if it ain't broke don't fix it.

**Comment by Shaska-** [comment]
Medical doesn't strictly need hardsuits either. You could replace it with some spare vox/plasmaman/grey suits.

**Comment by ghost** [comment]
With the medical hardsuits, it's more so you can identify somebody who can heal you in a crowd than anything

**Comment by Shaska-** [comment]
That's a good point.
I still think there should be some spare suits for greys in there at least though.
Perhaps cut 2 of the softsuits and replace them with grey suits.

**Comment by ghost** [comment]
Now that's pushing it. It's a human station, the alien hardsuits and softsuits are order-only for a reason

**Comment by ghost** [comment]
Jakmak, there was a bunch about it way back when the change happened.

**Comment by jakmak** [comment]
Why not instead do what metaclub did and keep the eng and atmos hardsuits behind eng/Atmos doors and some generic soft suits only needing EVA access to get to while relocating the medical hard suits to medbay(behind medical access doors of course). It wouldn't turn box EVA into the same mess that is deff EVA while also dealing with needing eng access to get any hard suits. Also no spare equipment barring spare air tanks for filthy unwashed non humans.

**Comment by ghost** [comment]
Eh, med having their suits moved into their dept is overdue. We don't need the additional rigsuits over soft suits though. It's just power creep. The only reason we have the eva we have now is because of the powergamers throwing a shitfit until it was reverted. Doors stop nobody

**Comment by Probe1** [comment]
Does this mean I can remove the ridiculous medical hardsuits from eva

**Comment by jakmak5** [comment]
what if we added a micro eva to medbay to free up more space in EVA. see this shitty drawing for what i had in mind
![ss 2017-02-01 at 04 38 47](https://cloud.githubusercontent.com/assets/25081182/22527455/49bdc682-e89d-11e6-9021-c3873a321213.jpg)

**Comment by uazuaz** [comment]
about people stealing hardsuits:
hardsuits are sensible equipment and they are inside a closed area; if a security officer sees someone using a hardsuit without having the connected job, they could automatically arrest them for theft+trespassing (13 minutes total) if they don't have a proper explanation.

having so many normal space suits means that now greytiders can ask (or steal) them instead of atmos suits; nobody needs specifically atmos suits, with the exception of people that are going to plasmaflood.

**Comment by ghost** [comment]
Could arrest. Don't.

**Comment by kol1th** [comment]
Do not remove the atmos suits and engineering suits, as those are all gone from engineering within 30 minutes from powergaming shitters

**Comment by ThePlapatin** [comment]
;security x has broken into y and stolen z

x = powergaming shitter
y = where they took z from
z = the hardsuit they stole

@jakmak5 That would be good, you could also maybe edit the security bathroom to be smaller and have a mini eva in security that regular officers can access without needing armory access for the suits there.

**Comment by Fruktlimpa** [comment]
If the shortage of atmos suits are a problem then add more to secure storage or something. Why does EVA need to have job department suits when the departments themselves can host them?

**Comment by Lokiamis** [comment]
Since we're discussing EVA, there's no reason for medical hardsuits to exist tbh

**Comment by uazuaz** [comment]
as Skullyton said
>With the medical hardsuits, it's more so you can identify somebody who can heal you in a crowd than anything

**Comment by Lokiamis** [comment]
That's a weak, silly justification. People can identify medical outfits just fine, and doctors have their HUDs.

**Comment by uazuaz** [comment]
you can't identify medical outfits through a hardsuit.

**Comment by Lokiamis** [comment]
Medical doctors, chemists, and surgeons do not require armored extravehicular activity space suits. If the medbay is depressurized or exposed to space, easy identification of the aforementioned is the least of your concerns.

**Comment by Kurfursten** [comment]
Reducing atmostech hardsuits is a significantly large buff to malf AI. That's all I have to say on this subject.

**Comment by Blithering** [comment]
While I do like the humble grey softsuit, there's still the mechanics to think about, being able to leave the engineering storage suits to the engineers and take one of the EVA suits to go podracing in was always nice. Plus the atmos hardsuit being literally the only thing besides the CE suit or being more chemicals than man that can survive a plasmafire is a problem in of itself, making it even more limited is just going to make things more horrible. I'm not in favour of these changes.
