### ISSUE TITLE
mouse eating doesnt leave rubbish after eating food that leaves trash when finished eating

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13752]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
eat a candy and no candy wrapper when done eating

>What you expected to happen
trash

>What actually happened
rat ate the wrapping

>Steps to reproduce if possible
eat stuff that leaves trash as a mouse
no trash

**Comment by ghost** [comment]
Looking at the code, it only drops trash if after_consume is called, which isn't the case for attack_animal consumption.

Corgis also eat the wrapping

**Comment by Kitfox88** [comment]
this is realistic and immersion assisting if my dumbass dog is anything to go by
