### ISSUE TITLE
CMC (and other nanoUI shit) doesn't show station map

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#13779]
#### Description of issue

The crew monitoring computer doesn't actually show a map. Ever. Neither does the bhangometer and whatever else uses nano and shows a map.

#### Length of time in which bug has been known to occur

Since 2017 at the very least. Probably a few months more. I'm honestly surprised nobody made an issue about it yet.

#### Server revision

6235e411665e05d610547dfba2d5d7d7c83b8079

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

Yeah, it's another dupe. Couldn't find an open issue.

**Comment by Fruktlimpa** [comment]
From what I have heard it has to do with your internet explorer version. It is most likely out of date because who the fuck uses that browser, so if you update it the UI should return.
This is hearsay and I haven't tested it myself because I haven't pulled my fingers out of my ass and done it.

**Comment by Exxion** [comment]
It's actually HTMLUI, not Nano

**Comment by SonixApache** [comment]
I'm on win10, ain't no updates available for IE.

**Comment by PJB3005** [comment]
Real issue is that the entire code behind the HIM interfaces is cancer, and the nano code has been left to rot after the HIM interfaces came in.

**Comment by SonixApache** [comment]
Well this was fixed, so that's good.
