### ISSUE TITLE
Make the world start at 11:55

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#13773]
So that we begin the shift at 12 noon

**Comment by gbasood** [comment]
or just
make station time not start until round starts
doesnt it just take a timestamp and do timestamp math for station time

**Comment by Killette2** [comment]
Last time I checked blobcode, the resource frequency depends on station time. 12:05 is technically a nerf to blobs

**Comment by gbasood** [comment]
so fix that part of blob too
it's not hard

**Comment by SECBATON-GRIFFON** [comment]
did this one ages ago
