### ISSUE TITLE
average empress

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13781]
(WEB REPORT BY: mchotnspicy REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

6235e411665e05d610547dfba2d5d7d7c83b8079 
>General description of the issue
the alien empress is "average" in size

>What you expected to happen

empress is a big gurl
>What actually happened
average

>Steps to reproduce if possible

4 u

**Comment by jknpj** [comment]
Literally unplayable
