### ISSUE TITLE
Plasmamen Clown/Mime name change

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13794]
(WEB REPORT BY: waismuth REMOTE: 172.93.109.202:7777)
>Revision 6235e411665e05d610547dfba2d5d7d7c83b8079

>Inputting custom name for my plasmaman clown/mime job doesn't register. I keep my assigned random name for the clown, and my original name for the mime

>I want the name prompt for clown/mime jobs to work properly

>What actually happened
I'm left with a random name as the clown

>Steps to reproduce if possible
1 Be a plasmaman clown/mime
2Try to input name
3 Fail

**Comment by AI-Is-Rogue** [comment]
This happens if you wait too long to enter the name. There is a time limit to how long you can keep the name prompt up before it just decides to give you a random clown name because you spent ten or so seconds from roundstart with it open.

**Comment by Shadowmech88** [comment]
This should be fixed by #19591.
