### ISSUE TITLE
shoveling two plants at once doesnt work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13796]
(WEB REPORT BY: bobby177 REMOTE: 172.93.109.202:7777)
Revision: d213d4b1d6cae57923c9f0c7a8d72e1f805a7501 
When using a spade to transfer moonflowers to pots, the game allows you to click both flowers at once to uproot both at the same time. Even with 2 pots next to my character, one plant went into the pot and one plant disappeared. It seems like this should either work correctly or not be allowed.

**Comment by gbasood** [comment]
the bug is either that:
 - you can shovel two things at once
 - you can shovel two things at once but one of them gets nullspaced
