### ISSUE TITLE
Fusion of Name and Cords in crew monitor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13799]
(WEB REPORT BY: fluffyfris REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When you select, Text Based in the crew monitor the cordinates of people and the location of people get fused thoghetter.

>What you expected to happen
Both details to be seperate.

>What actually happened
They are fused thoghetter

>Steps to reproduce if possible

**Comment by 9600bauds** [comment]
![dreamseeker_2017-02-03_19-52-16](https://cloud.githubusercontent.com/assets/6526157/22611611/4da8c630-ea4a-11e6-86e7-333063acbc53.png)
http://pastebin.com/ZG0GQW2d
how is this hapen??

**Comment by kilozombie** [comment]
The grammar in that web report, though.

**Comment by Zth--** [comment]
Line 56
`                  <td>
                     <h3> </h3>
                  </td>`
the fuck is this code

**Comment by gbasood** [comment]
@Zth-- 
\>table with headers in them
what's the probem

**Comment by 9600bauds** [comment]
`if (area && pos_x && pos_y)	{ tdElem.append($("<div></div>").text(area).addClass("tt").append($("<div></div>").append($("<span></span>").text("(" + see_pos_x + ", " + see_pos_y + ")")))); }`
t-thanks javascript monstrosity
