### ISSUE TITLE
Another request to nerf a popular thing

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#13808]
The ghetto space suit is crazy OP.
Take a look at the standard grey space suit:
-Move slowly while wearing it
-Can only fit smaller tanks in storage
-No helmet light

Whereas a firesuit with a blanket and some wires has:
-No noticeable slowdown
-Can fit large tanks
-Helmet light

While the helmet light is congruent with the construction materials, the firesuit can't hold large tanks either, and the space blanket slows you down to crippled diona in legcuffs speed. 

I use this suit a lot, but its still better than it really has any right to be.

**Comment by Kurfursten** [comment]
If anyone ever does nerf this, they should in the same PR add a comfy crate to cargo that includes a bunch of blankets so that as a balance, people need no longer raid medbay or order a medical crate in order to become amateur space men.

**Comment by ghost** [comment]
What if like...we reversed the features of those two.

**Comment by Kammerjunk** [comment]
@Kurfursten I believe this is the one you want
![image](https://cloud.githubusercontent.com/assets/5942183/22615935/9bca47a6-eaa1-11e6-8750-4923b34356ea.png)

**Comment by nuklearcellphoneg** [comment]
Yes I agree with this 100%, honestly the firesuit is sufficient to survive short forays into space.

**Comment by 9600bauds** [comment]
Is it really still? I thought hypothermia fucked that up royally

**Comment by Kurfursten** [comment]
@Kammerjunk Yeah, that's the one I'm talking about. You end up ordering a whole crate of medical stuff just for one item _inside_ one of those items.

It would be nice if there was a comfy themed crate, maybe with some wood for a campfire. I bet we could think of some other stuff too.

**Comment by Kammerjunk** [comment]
@9600bauds Not having any issues locally on test_tiny, not sure if it's the same on the main serb
![image](https://cloud.githubusercontent.com/assets/5942183/22616186/8fdee760-eaa8-11e6-8bfc-878f1c8da16c.png)

**Comment by Kammerjunk** [comment]
Okay now I'm feeling cold. I should probably warp up some more.
Still, it's not bad.

**Comment by Kammerjunk** [comment]
And even after entering the heated station, I was cold for long enough to enter crit.
Maybe it isn't so great either.

**Comment by nuklearcellphoneg** [comment]
Should I make an issue

Asking to nerf hypothermia

**Comment by Kurfursten** [comment]
I was amused to learn that if you eat Chinese Cold Salad too quickly, you'll pass out.

**Comment by jakmak** [comment]
Christ just remove the sleep memes from hypothermia. It was intended for the snow map which was ran once and during that single run it crashed the server. All it does is make zas abuse stronger since 5 second stun, Drag to space, and wait 5 seconds for endless sleep and death

**Comment by gbasood** [comment]
welcome to space

**Comment by Blithering** [comment]
This was fixed, closing
