### ISSUE TITLE
Roid structures can be generated inside the new (box) vox outpost.

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#13802]
There was a xeno nest inside the vox outpost last round. It was the first time I've ever witnessed this.
Sorry, no screenshot.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Pretty sure this has been reported before.

**Comment by Riekland** [comment]
Are you telling me that there shouldn't be aliens to ruin the perfidious v*x's day at roundstart?

**Comment by Blithering** [comment]
Vox construction at its finest

**Comment by gbasood** [comment]
dupe issue
