### ISSUE TITLE
Floor Tile Issue

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#13806]
![image](https://cloud.githubusercontent.com/assets/6540760/22614863/ca41a1e2-ea56-11e6-871a-a3499851c335.png)

![ejwnxmsnwyamanbdgacdyy_zbhfeoiyyyuc5vn29fyf3ufc81ap2kcerwhzwoblpfpq5vd2i2lnzofgxuicl5ljftqsdop98sb4xbunsxaqyi_pl-f9yydlgdnz93enpevsmvj8ikcli](https://cloud.githubusercontent.com/assets/6540760/22614870/d57079b2-ea56-11e6-889c-030c0ea47233.png)

![ejwlymenwyamambdgaatu3djnohyjfisi-y-quzer-95x_ezp1vdbjz0bdgobti3ryazdvzdpj9cx6g-yqxvrlb94tsukahtlm8sjb_semp4f2umkzyuqwaabzpzj7u75wfcjchp](https://cloud.githubusercontent.com/assets/6540760/22614873/db8c8cbe-ea56-11e6-8d7f-385300bac1f5.png)

Map is deff

**Comment by nuklearcellphoneg** [comment]
The tiles changed periodically throughout the round, and I have no idea why.

**Comment by jknpj** [comment]
COMIC SAAAAANS

**Comment by nuklearcellphoneg** [comment]
Thanks for noticing

**Comment by kilozombie** [comment]
IT'S
A
FFEEAATTUURREE
Cargo techs use these magic floor tiles for crate item bluespace manipulation with a picomanipulator on a table. Removing this will literally ruin the game.

**Comment by Kurfursten** [comment]
But what did you post in OOC that you discussed in that ahelp? These are the hard hitting questions

**Comment by nuklearcellphoneg** [comment]
Feel free to investigate logs

**Comment by nuklearcellphoneg** [comment]
:^)

**Comment by PJB3005** [comment]
BYOND shat itself again, move along.
