### ISSUE TITLE
Remove Bustanut Reagent

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#13803]
This is a game breaking chem that serves no purpose.

**Comment by nuklearcellphoneg** [comment]
(It makes ZAS not affect you if you didn't know)

**Comment by kilozombie** [comment]
>Nuke's on a feature-removal spree

>99% of his arguments are shit (lol it serves no purpose BUT it's overpowered)

![t3_3rted7](https://cloud.githubusercontent.com/assets/6062247/22614696/ac69447a-ea3a-11e6-883f-4a84ba0685ed.jpg)

At this point we should just remove Space Station 13.

**Comment by jknpj** [comment]
Isn't it useless thanks to our default ZAS setings?

**Comment by nuklearcellphoneg** [comment]
It literally makes ZAS not do anything to you. It's like wearing magboots.

**Comment by nuklearcellphoneg** [comment]
If you are in a plasma fire, and open the door to escape, normally you get sucked out and slammed into the wall.

If you eat bustanuts, it doesn't do anything at all.

**Comment by kilozombie** [comment]
I daresay that may be possibly Intentional, my dear friend

**Comment by nuklearcellphoneg** [comment]
It should make ZAS more hardcore, not make it not affect you at all.

**Comment by kilozombie** [comment]
WYCI

**Comment by nuklearcellphoneg** [comment]
Why not just disable ZAS?

**Comment by AutismSpider** [comment]
>post this after that talk about ZAS and how it works

how far did you stick that knife up m8?

**Comment by nuklearcellphoneg** [comment]
I don't follow.

**Comment by nuklearcellphoneg** [comment]
It poked through into my nasal cavity, though, if you must know.

**Comment by kilozombie** [comment]
It's like contributors are slowly discovering quirks of the game that other people have known for ages and are suddenly in uproar and making feature removal requests because they weren't informed before

**Comment by nuklearcellphoneg** [comment]
I'm not a contributor.

**Comment by kilozombie** [comment]
It's like people who browse github on a semi-regular basis to shitpost are discovering quirks of the game that other people have known for ages and are suddenly in uproar and making feature removal requests because they weren't informed before

**Comment by nuklearcellphoneg** [comment]
Also, making this issue will help ensure that, even if it's not changed, everyone will know about. :^)

**Comment by kilozombie** [comment]
Next thing you know, he's going to spill the beans that you can fill tanks beyond the usual limit! The madman

**Comment by AutismSpider** [comment]
@kilozombie show lot of mommi players and  engine techs/atmos how to do this most of them move on to making bombs etc

**Comment by nuklearcellphoneg** [comment]
Make better ways to combat ZAS if you want- this is a magic chem.

**Comment by kilozombie** [comment]
If we're talking legitimately, I like the idea that there's a chem that combats ZAS for the common man, and IMO bustanut is fine as-is. An interesting change might be requiring you to mix bustanut with another common chem (maybe silicon or oxygen or something, from ghettochem?)

**Comment by ghost** [comment]
Bustanuts were made to make ZAS be super duper powerful against you and only you. This is a bug, not an OP chemical

**Comment by nuklearcellphoneg** [comment]
It's a game breaking chem... and yes, a bug.

**Comment by Allspice** [comment]
By consuming hardcores, your brain's neuronic pathway dealies are opened to the genetic knowledge of "bracing yourself against shit so air doesn't send you slamming into a wall 50 times."

**Comment by nuklearcellphoneg** [comment]
That sucks, because that's not how it works. :( Sorry.

**Comment by 9600bauds** [comment]
I've looked at the code and it's most definitely not a bug, it's pretty explicitly intended
You can argue about the balance all you want and say it's dumb all you want, it's not a fukken bug though

**Comment by clusterfack** [comment]
We should fix the bug that made bustanuts make you immune to zas, and have it make you vulnerable to zas like it used to.

**Comment by clusterfack** [comment]
@9600bauds you're 100% wrong, Nexis flipped the behavior for it by accident when he did a rewrite of it once, its at the end of airflow.dm

**Comment by nuklearcellphoneg** [comment]
Yes. it would be fine with me if instead of making it make you invincible to ZAS, it made ZAS affect you in the most extreme way, personally.

**Comment by 9600bauds** [comment]
```
/mob/AirflowCanPush()
	if (M_HARDCORE in mutations)
		return 0
	return 1
```
Flip this around and now it means everyone is ZAS immune UNLESS they have bustanuts
I have no idea what it was before I only know what it is right now, and that is, not a bug

**Comment by nuklearcellphoneg** [comment]
I'm sorry bauds, but it is not the intention of Bustanuts at all.

Busta wanted ZAS to be hardcore, and that's what Bustanuts were intended to do- to make it as a harsh as it could be.

**Comment by 9600bauds** [comment]
cool but lemme point back to what I said

> You can argue about the balance all you want and say it's dumb all you want, it's not a fukken bug though

**Comment by clusterfack** [comment]
![](http://puu.sh/tNpfr/5ef9d1cd16.png)

**Comment by clusterfack** [comment]
Airflowcanpush was an override that used to allow you to be pushed when the ZAS setting to be pushed was disabled.

However this dumb motherfucker left airflowcanpush in the way it was to fix a "bug" but flipped the hardcores behavior.

**Comment by Blithering** [comment]
Legend had it back in the day the downside to bustanuts was it made you even more haemophilic when you had it in your system. Or at least that was what I was told. Would be fun to have that come true.

**Comment by Kammerjunk** [comment]
https://github.com/d3athrow/vgstation13/commit/229b4c1323fc79dc21523d99610c1f4b5a0ac686 This is when bustanut and its functionality was created.
This is the important part: `if(zas_settings.Get(/datum/ZAS_Setting/airflow_push) || reagents.has_reagent("bustanut"))`

https://github.com/d3athrow/vgstation13/commit/09683bc2ba704ce8580d8265942e53074ba69333 This is the next change to Airflow.dm.
This is the important part: `if(zas_settings.Get(/datum/ZAS_Setting/airflow_push) || AirflowCanPush())` plus what Cluster posted just above (although in a different state then).

I'm not hugely invested either way and I'm worried I'm too dumb to understand it properly, but there it is.

**Comment by nuklearcellphoneg** [comment]
It's a thing that's not working as it was ever intended to. It is in fact working in the exact opposite way. It's just something no one ever pointed out as a not working as intended.

**Comment by Kammerjunk** [comment]
Goddamn Argentinians
Edit: https://github.com/d3athrow/vgstation13/pull/843

**Comment by Killette2** [comment]
I thought this was the point of bustanuts the entire time actually
I thought it was supposed to make you the master of ZAS

**Comment by Lokiamis** [comment]
Bustanuts should make ZAS more hardcore. That's the joke and entire point of the item. I should know because I'm the shitposter who made the muh hardcores image and sprite for it.

**Comment by Killette2** [comment]
If you're going to make them make ZAS more hardcore, then make them both free and not a contraband item again. They were put into contraband because they were OP due to the ZAS negating effect and being free food, but if it punishes you for eating then I see no reason to make it less of a task to get

**Comment by Lokiamis** [comment]
@Killette2 that's not a very hardcore thing to say. Besides, they can be used offensively and annoyingly.

**Comment by nuklearcellphoneg** [comment]
I'm glad Busta isn't around any more, he would cry on how casual the playerbase has become.

**Comment by ScrambledSteak** [comment]
I just want to ask why you linked this in my admin app

**Comment by nuklearcellphoneg** [comment]
Your name reminded me of this. https://github.com/d3athrow/vgstation13/pull/843

**Comment by ScrambledSteak** [comment]
I see. that's dumb and also that guy is dumb for making le push meme the only option

**Comment by Lokiamis** [comment]
Bahahshdkg

**Comment by Probe1** [comment]
memes

also no

**Comment by Exxion** [comment]
They were supposed to make ZAS more hardcore, but someone fucked up and they do the opposite
But I'm not convinced ZAS really *can* get more hardcore than Hellish

**Comment by Shadowmech88** [comment]
Whenever someone opens a door within range of you, you get slammed against a wall even if there's no pressure difference.

**Comment by AI-Is-Rogue** [comment]
That would be amazing.

**Comment by SonixApache** [comment]
You can still increase the ZAS settings.

**Comment by Exxion** [comment]
Technically speaking, yes, you can increase the ZAS settings past Hellish.
Doing so, however, is morally wrong.
