### ISSUE TITLE
Shoe Bloodying

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13813]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
8def58646688d950f30b882892336789ee6dfbb0

>General description of the issue
When wearing shoes with an accessory on(and maybe without fuck knows), should you walk over vomit or oil or blood and get it on your shoes, the sprite often will not update on your character nor the clothesdoll thing
This also happens when washing them, where only some bits will become clean looking and the rest look like shite
>What you expected to happen
spick and span clean shoes

>What actually happened
oh god drill sergeant is going to kill me

>Steps to reproduce if possible
wear shoes, try to wash

**Comment by gbasood** [comment]
i thought we fixed shoes not updating when washed
like 2 years ago

**Comment by Zth--** [comment]
It's runtiming. We had an issue with bloody footprints not showing back then. It was badly fixed and icons never worked again.
`[04:42:37] Runtime in update_icons.dm,750: Cannot read null.name
  proc name: update inv shoes (/mob/living/carbon/human/update_inv_shoes)
  usr: Matt Hunt (mater0706) (/mob/living/carbon/human)
  usr.loc: The plating (207, 217, 1) (/turf/simulated/floor/plating)
  src: Matt Hunt (/mob/living/carbon/human)
  src.loc: the plating (207,217,1) (/turf/simulated/floor/plating)`

**Comment by Probe1** [comment]
Its something like if its stacked, only the top layer of filth gets cleaned.

**Comment by gbasood** [comment]
@Zth-- that's unrelated actually
That runtime happens when their species is null i.e. qdeling
I made a PR to fix that literally a few hours before you made that comment

**Comment by Shadowmech88** [comment]
Could not reproduce. Walked between a puddle of blood and vomit multiple times, was able to clean the shoes just fine with both soap and a sink. No runtimes either.
