### ISSUE TITLE
Hyperzine + Magboots

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#13810]
If magboots are activated and you have hyperzine it does not slow you down.

That's retarded, please fix this.

**Comment by AutismSpider** [comment]
same thing happens with strong leg mut want take that out to?

**Comment by ghost** [comment]
Riddle me this,

You don't click your mags, someone off in the distance opens something, and you eat shit
A perp is yakkety saxing to check if you're on mags then uses a swap choice rcd/grenade to breach/opens a door after clicking mags and you eat shit
You keep your mags on to not eat shit and basically anyone who can hit the broad side of a hallway bends you over your cover and husks you senseless 10/10 times
You try to keep your mags off and try to click them on in time when your gut feels it coming but you still eat shit to one of the two regardless
Rampant grief as people fight like autists over the carts causing murder bans, shitcurity jobbans, and general rampant asshurt
ZAS is reduced to the point it doesn't exist which has the same end result while low-friction tobogganing down the luge to nothing matters shitsville

Let it go.

**Comment by 9600bauds** [comment]
I see what Nuke is doing here!
He's opening issues on all his favorite powergaming tricks so they get a lot of thumbs down and guarantee they never get removed :^)

**Comment by nuklearcellphoneg** [comment]
You wear magboots to beat ZAS and the Singo, right?

So, why do you need them to be enabled 24/7?

**Comment by kilozombie** [comment]
Because spacewind is sudden and unexpected, and sometimes you know there's going to be a breach but have no idea where or when.

**Comment by nuklearcellphoneg** [comment]
Isn't that the point?

**Comment by kilozombie** [comment]
Getting unexpectedly killed by being slammed 5 times into a wall per second by magic spacewind that appears because some asswipe opens a door accidentally is not the point.

**Comment by jakmak** [comment]
Suck a dick nuke hyperzine mags are one of the best features of this codebases chem system.

**Comment by kol1th** [comment]
Hyperzine nullifying every slowdown we have is absolutely retarded. It should be reworked.

**Comment by JustSumBody** [comment]
The best feature of our chem system is creatine and lube.

**Comment by nuklearcellphoneg** [comment]
If magboots complete negate the Singo and ZAS(correct me if I'm missing anything) then they need a trade off for using them. You can't say, oh an antag will kill me with magboots on- if you're the one wearing magboots, they ought to be sucked away by one or the other- if not, turn your magboots off, dumbo. Then turn them on again when you need them.

**Comment by Shadowmech88** [comment]
The trade-off is that you have to either be slow or constantly dosing yourself with hyperzine.

**Comment by nuklearcellphoneg** [comment]
That's not a trade off at all.

**Comment by nuklearcellphoneg** [comment]
14u is going to last awhile, and it's cheap and readily available and commonly requested. You're never going to have an issue having Hyperzine. And, finally, it still doesn't make any sense. The strong legs mutation DOES make sense, and if you had them in conjunction with magboots and hyperzine, would make plenty of sense.

**Comment by nuklearcellphoneg** [comment]
You're not supposed to just be able to leave your magboots on for eternity without ever having to think to turn them off.

**Comment by AI-Is-Rogue** [comment]
Magboots stick to the floor and strong legs makes sense because you can lift your feet easier, but what about hyperzine? Why does it allow you to lift your feet easier?

**Comment by Shadowmech88** [comment]
Hyperzine makes your legs stronger.

**Comment by Kitfox88** [comment]
remove zas obv

**Comment by kilozombie** [comment]
Remove Code
**REASONING:**
- Things have come out of coding such as waifus, ERP and literal autism. The only reason lag exists is because of the code. Furry ERP games use code just like we do. Even NASA uses code. Code is overused and makes too much slop.
- It has to be maintained by hundreds of people.
- People are using it to make changes to the code. It's a self-fulfilling shit prophecy.

**SOLUTION:**
Revert all of code. Return to nothingness.

**Comment by AI-Is-Rogue** [comment]
@kilozombie 🤔
