### ISSUE TITLE
discussion about disposal mailing system

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#13812]
i observe rounds often and almost every time i see people at cargo using the disposal mailing system wrong; this happens because the mailing system is very unintuitive ‎ and maybe also illogic (that's why i wrote this guide https://github.com/d3athrow/vgstation13/issues/6800)

sorting junctions and wrapped sorting junctions could be modified to pick items individually, so all unwrapped/untagged items will go to the recycling room, all wrapped/tagged parcels will reach their destination and all wrapped/untagged parcels will reach the mail outlet inside the cargo delivery office.

could there be some technical issue when sorting a big number of items?

**Comment by PJB3005** [comment]
The problem is that disposals, for efficiency reasons, contains all items in a meta structure for transport. Now this can only have on sort tag... 

Could probably optimize the bin to be smarter about it though.

**Comment by uazuaz** [comment]
couldn't multiple "meta structures" be used?
example:
you send 20 items at once; there are 1 parcel tagged medbay, 2 parcels tagged engineering, 17 unwrapped/untagged items (trash);
1 meta structure for the medbay parcel
1 meta structure for the 2 engineering parcels
1 meta structure for the 17 pieces of trash
all sent at the same time.

**Comment by PJB3005** [comment]
Of course, that's what I meant.

**Comment by SonixApache** [comment]
I was thinking about writing a 'DISPOSALS MAILING FOR DUMMIES' book and placing it in cargo. People just need to git gud.

**Comment by uazuaz** [comment]
@SonixApache 
i already wrote a guide, is linked in the OP; by the way, i think that changing the system is a better solution, it's more intuitive if changed this way and trying to send parcels when trash comes on the conveyor belt can be annoying as it is now.

**Comment by SonixApache** [comment]
@uazuaz tell me where that's supposed to go and I'll make a PR for it.

**Comment by uazuaz** [comment]
@SonixApache 
that's why i'm discussing the matter, at the moment i think that it would be better to change the system to be more logic and intuitive; if the mailing system is changed, there will be no need for the manual.

if people think that the current system is better, the manual could be added inside the delivery office.

**Comment by PJB3005** [comment]
Manual is needed either way. This oddity should definitely be fixed though.

**Comment by uazuaz** [comment]
well, all new people on cargo do the same error: they wrap and tag all the crates and send them all together with trash, even if there are multiple destinations; if the system is changed to work this way there will be no need for a manual, it can be easily taught in-game by other people.
