### ISSUE TITLE
Another Crew Monitor bug, God help us

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#13823]
This shit, this shit right here.
I decided to not add it to the big festering mess of the other bug report.
![untitled](https://cloud.githubusercontent.com/assets/6224074/22621383/6bca3de6-eaf0-11e6-8a29-07aab48ba173.png)
Resizing didn't help. BYOND version 5.0.510.1347. Maybe I need to update?

**Comment by gbasood** [comment]
Is this not just #13799

**Comment by Ephx1** [comment]
How the fuck did I not see that? My bad.
