### ISSUE TITLE
EMPs shouldn't cause robotic limbs to fall off

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#13824]
Just disable them for a bit, like every other piece of machinery.

**Comment by AI-Is-Rogue** [comment]
EMPs destroy mechs and the computer screens.

**Comment by Lokiamis** [comment]
Ok well whatever. I haven't seen anybody use a robotic limb in a long time, and maybe a buff would get them some love.

**Comment by AutismSpider** [comment]
emps do damage to mech (most of it to the cell any way) computer screens are easy to fix.

**Comment by AI-Is-Rogue** [comment]
But it still damages the mechs and computers, that was my point.

**Comment by Allspice** [comment]
The most damageful thing EMP does to mechs is a damage- and celldrain-over-time until you hop out and maint wrench cablecoil.

**Comment by AI-Is-Rogue** [comment]
It can also fuck up the navigational systems I believe. And it still damages the mech, so I believe it could affect the robolimbs too.

**Comment by Lokiamis** [comment]
Damaging them is fine, as long as they don't just fall off.

**Comment by Kurfursten** [comment]
Actually robotic limbs just got a substantial buff. Damage to the limbs no longer subtracts from your total health. Meaning for example if a doorshock only burns your robotic arm, you remain at 100% health.

Also things that damage multiple zones like MULE crushing and ZAS therefore deal less damage overall to people with prosthetics.

And the justification for all this was "but emps! Even though they're uncommon, they really fuck you up!"

**Comment by Ephx1** [comment]
> Meaning for example if a doorshock only burns your robotic arm, you remain at 100% health

I'm gonna miss laughing at patients with prosthetic limbs walking into medbay.

**Comment by gbasood** [comment]
next
\>"You feel a tiny prick" only happens if they weren't targeting a prosthetic limb

**Comment by ghost** [comment]
Need a way of EMP proofing them

Now if only somebody was working on cybernetics

**Comment by Kurfursten** [comment]
Instead, just add limbs to the organ printer. That's the best way of EMP-proofing.

**Comment by Intigracy** [comment]
Non-organic (or completely missing) limbs should subtract from your max health by some with the benefit that they don't affect your health when targeted and damaged.

**Comment by jakmak** [comment]
Problem with limbs and EMP is that it 1 hits the limb and usually forces the victim into pain crit (which basically is a 1 hit) while borgs made out of solid metal and electronics shake it off like nothing meaning EMPs are better suited for fighting carbons then they are at handling sillicons. Either reduce damage on robolimbs or buff its effects on borgs massively

**Comment by AutismSpider** [comment]
They stun borgs for longer now on cyborgs they suck massive dong vs mechs and rip any one with robo limbs or a heart two emps blast and its over for you.

**Comment by Ephx1** [comment]
Oh fuck off, EMPs stun borgs for 20 seconds now. That's not even seconds, that's server ticks, so it's even longer. If you can't kill an immobile target that already takes like ten hits from a toolbox (or even _less_ if RNG favors you) in 20 seconds you are shit and I ask you to get the fuck out.

**Comment by Aurx** [comment]
Retards STILL think emps are for killing silicons, when they've always been stun with a side of damage.  
You can't patch stupid.

**Comment by Kurfursten** [comment]
Hm, you could improve the examine text for cyborgs a bit, though, in terms of damage.

For humans it's pretty clear when the fight is over - bleeding on the ground, they're toast. But a "heavily dented cyborg" can still mash your face in.

**Comment by Ephx1** [comment]
As much as I would agree to better examine text, I don't know anyone who doesn't continually beat a borg even after death. Stun and constantly destroy.

**Comment by Shadowmech88** [comment]
I don't see any reason why we can't just make borgs go horizontal when they've taken enough damage to be inoperable.

**Comment by Ephx1** [comment]
It's just a case of the "just looks weird", I kinda want a specific light on the borg to signify death. We _do_ have the regular lights, but borgs can shut those off by turning off their actuator, and they turn off when stunned.

**Comment by Shadowmech88** [comment]
What about a "smoking" overlay that can be applied to them to make them look broken down?

**Comment by Ephx1** [comment]
Now that would be rad.

**Comment by Kurfursten** [comment]
@Ephx1 That's kind of my point, people don't know when to stop beating.

We really need a deathgasp equiv for them too

>[Name] slackens, internal rotors quieting.

**Comment by Ephx1** [comment]
But we do have a deathgasp equiv.
...How long have you been playing?
We also have a specific text (purple I think) for them being dead.

**Comment by Kurfursten** [comment]
2 years and I've smashed many cyborgs. Maybe it's just not obvious enough, or maybe it doesn't play if they ghost or something.

**Comment by Probe1** [comment]
Never ever ever ever ever trust a deathgasp from a cyborg.

**Comment by Aurx** [comment]
It's just as obvious as a deathgasp from a human.  
People just don't murder 'borgs as often.

**Comment by Ephx1** [comment]
I've rarely seen people trust a deathgasp from humans, probe. Especially if they have a sharp tool, regardless of whether or not their target is a ling/vamp they _WILL_ behead their target.

**Comment by Shadowmech88** [comment]
You can just shift+click a human to check whether they've got a pulse or not if you're uncertain about their deathgasp.

Is there any way to verify that a borg is dead?

**Comment by Probe1** [comment]
Yes when it starts harmbatoning you that indicates it was a ruse.

**Comment by Ephx1** [comment]
Like I said there's a very specific "it's unsalvageable" death message on examining. Also I don't think you can see if someone has a pulse merely by shift clicking them anymore, you have to manually pick the "check pulse" verb.

**Comment by Shadowmech88** [comment]
>I don't think you can see if someone has a pulse merely by shift clicking them anymore

![image](https://cloud.githubusercontent.com/assets/3991927/22665362/20248186-ec7a-11e6-8099-398427ce8109.png)

**Comment by Ephx1** [comment]
Odd, hasn't worked for me but honestly I mostly play silicon, could you try as one?

**Comment by Kurfursten** [comment]
I believe the pulse check is proximity based

**Comment by Aurx** [comment]
It indeed is.  You automatically check for a pulse when you examine somebody adjacent to you, but you then both have to not spazz out and sanic off before the pulse check completes.

**Comment by gbasood** [comment]
Okay well this is old and also way off topic

**Comment by Shadowmech88** [comment]
Needs the [Unfulfilled Feature Requests] tag.
