### ISSUE TITLE
Revert peacekeeper/security borg color scheme

### ISSUE THREAD

**Issue by Shaska-** [d3athrow/vgstation13#13830]
It looks like ass.

**Comment by TheFriggenSawbones** [comment]
kodiak borgs are invisible

**Comment by gbasood** [comment]
separate issue @TheFriggenSawbones

**Comment by PJB3005** [comment]
What the hell how did I fuck up the sprite for Kodiaks, I'm 100% sure I pasted dizor's new version in.

**Comment by Probe1** [comment]
They should be red still.  Its iconic.

**Comment by Killette2** [comment]
My favorite secborg sprite is the one I make when I reach the RD's office

**Comment by Ephx1** [comment]
So your burning corpse then?

**Comment by mrpain666** [comment]
#rekt

**Comment by Killette2** [comment]
Help borgs are lings! They stole my UI!

**Comment by Yelier** [comment]
The new color is nice, but it's just out of place for what they do. I get that it was changed so people don't think they're immediately part of the security team regardless of laws, but if they don't know how laws work, they shouldn't be playing silicon in the first place. I would be in favor of going back to red.

**Comment by Killette2** [comment]
It's not out of place, secborgs blue ball me all the time.
