### ISSUE TITLE
Peacemaker Borg skin bug

### ISSUE THREAD

**Issue by billbillson** [d3athrow/vgstation13#13833]
#### Description of issue
The last skin you can choose in the peacekeeper tab has no sprite other than some random gold bits that makes you pretty much invisible.

#### Difference between expected and actual behavior
I expected to see a blue borg skin

#### Steps to reproduce 
1.be borg
2. choose peacemaker module
3. decide to use the bottom last skin
4.become invis

#### Length of time in which bug has been known to occur
 forever as long as you are using the skin
	

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by mrpain666** [comment]
Why did we have to go and fix something that wasnt broken?

**Comment by gbasood** [comment]
@PJB3005 you fuck

**Comment by mrpain666** [comment]
I asked a question.

Why did we try to fix something that wasnt broken?

**Comment by mrpain666** [comment]
Yeah just keep deleting why I keep asking this change occurred in the first place.

**Comment by PJB3005** [comment]
Aaaaaah

**Comment by Probe1** [comment]
why even change the color

**Comment by mrpain666** [comment]
WOW MUH SLIPPERY SLOPE ATTACK ANIMATIONS AND PAPRIKA STUNS WHEN

**Comment by mrpain666** [comment]
but seriously, WHY?

**Comment by mrpain666** [comment]
OH SHIT PROBE YOU'RE POSTING IN THE BUG REPORT ISSUE NOT THE CLOSED PR NO ONE'S GOING TO LOOK AT YOUR COMMENTS ARE GOING TO GET DELETED AND YOULL BE BANNED FROM THE GITHUB PLS BE CAREFUL

**Comment by PJB3005** [comment]
![image](https://cloud.githubusercontent.com/assets/8107459/22625387/3863675c-eb95-11e6-9ac5-455f79bda1dd.png)

**Comment by mrpain666** [comment]
HE'S ACTUALLY DOING IT WHAT A MAD MAN
