### ISSUE TITLE
Strange dungeon spawning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13848]
(WEB REPORT BY: mal23 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Rolled vox trader and found some out of place walls. Decided to investigate

>General description of the issue
For some reason map generation decided to spawn 3 mining astroid dungeons on the vox trader outpost, resulting in a part of the main hallway being replaced

>What you expected to happen
N/A

>What actually happened
N/A

>Steps to reproduce if possible
Since this is done during world generation, I don't know how to reproduce it

**Comment by PJB3005** [comment]
Duplicate.
