### ISSUE TITLE
Invisbility spray can be used on the supermatter shard and singularity

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13841]
A bit much perhaps
![image](https://cloud.githubusercontent.com/assets/19365096/22625394/07bafdcc-eb63-11e6-89c2-5302811507c2.png)

**Comment by eplgr** [comment]
Does that mean that wizards should also not be able to bound object the shard?
I know they are supposed to be stronger because they are solo antags, but...

I think that getting the shard for a clown is actually risky so yeah, if he gets it, he should be able to pull this off.
On the other hand, wizards' can easily get it.
And I name them to put in perspective the situation.

**Comment by ScrambledSteak** [comment]
The ultimate honk.

**Comment by Exxion** [comment]
How do you even get next to the singularity to use the spray on it?

**Comment by Ephx1** [comment]
By chugging anti-toxins in a CE suit, and some crafty jetpacking.

**Comment by Intigracy** [comment]
By doing it when it's still 1x1.

When it changes icon it doesn't reset alpha.

**Comment by AutismSpider** [comment]
don't you die spraying the thing you are touching it?

**Comment by AI-Is-Rogue** [comment]
I n t e n d e d

**Comment by jknpj** [comment]
@AutismSpider that's not how supermatter works, if you slap something against it whatever you hold get consumed and you ger radiation all over you

**Comment by Shadowmech88** [comment]
What if you varedit a supermatter shard into your hand and hit another supermatter shard with it?

**Comment by AutismSpider** [comment]
@jknpj the spray form the can is hitting it that should set off the rads and not turn you into dust

**Comment by mrpain666** [comment]
Keep it as is please

**Comment by Killette2** [comment]
This is a good thing but watch as it easily gets abused to the point of it being unfun. Happens every time

**Comment by Probe1** [comment]
As HILARIOUS as it is to read on github, it's awful in game.  Fix it tactfully or I'll fix it with a hacksaw @Shadowmech88
