### ISSUE TITLE
Borer previous host death bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13853]
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
>Revision
1b93bf9f986816dce9141879dc2c6fa8858edd43

>General description
I was a borer in the brain of a vampire. The vampire was beaten to death, and I abandoned his corpse, and entered the head of an assistant. While chatting with the assistant, I turned into a ghost with no messages as to why. In ghost chat, I learned that the corpse of the vampire had been cremated at that moment.

>What you expected to happen
Not dying as a borer in the head of another person due to my previous host being cremated.

>What actually happened
This is a bit redundant with the 'general description' section, isn't it?

>Steps to reproduce if possible
See 'general description' section.

Hope this helps.

**Comment by Shadowmech88** [comment]
Tested locally, could not reproduce.
