### ISSUE TITLE
The chat feature is actually a bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13852]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
chat be buggy

>What you expected to happen
chat not be buggy

>What actually happened
> be me
> join serva
> hear new welcome song
> see new chat, be like OOoooOoO
> see no colors in chat, be like OOOooo.
> fix everything by clicking "Highlight string"
> break everything
> https://ctrlv.cz/DWmh
> then can't see where to get them weapons

>Steps to reproduce if possible
See the \"What actually happened\" paragraph.

**Comment by Exxion** [comment]
It's not new at all
Also, Jesus fuck

We're going to need more info to know what the fuck is going on

**Comment by Exxion** [comment]
So we eventually established that
1. Neither clearing the skin files nor the cache fixed it
2. The Goonchat window is present for him, just fucked up
3. Reloading his `chatOutput` datum made the links that would be in the dropdown menu appear in chat, but only until he clicked in the window (?????)
4. He's on Windows 10 and IE 11, so those aren't outdated

**Comment by Exxion** [comment]
And now @TheFriggenSawbones has this bug too

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/22631993/5653f08a-ebe3-11e6-85c5-baf0e66340e6.png)

Holy fuck Lummox
Get your shit together
When was the last beta build that didn't break something?

**Comment by Probe1** [comment]
511.1365

Which is why I put it on the server and MOTD so people didn't update to other versions.  But hey, some people will do that.
