### ISSUE TITLE
"but it's just a balloon"

### ISSUE THREAD

**Issue by Yelier** [d3athrow/vgstation13#13859]
The Syndicate balloon exists to take away all your TC, reveal that you're a traitor, and also to show that you're robust enough to deal with both of those **WITH ONE HAND.** However, whenever someone sees one, they think "is this guy really a Syndicate agent?" and ignore it, because they know that if they act on it, the guy holding it can just ahelp "IT'S JUST A BALLOON WTF", which I agree with. It _IS_ just a balloon. Nobody would kill someone over holding a balloon with a letter on it.

All of this just completely removes the point of the item, so here's my proposed solution (which you may have seen in the thread a week or so ago):
-Balloon is replaced with "Syndicate Advertisement Bundle" on the TC exchange PDA screen
-Box contains both a Syndicate balloon, and also a new item; a Syndicate t-shirt, which would basically just be a red t-shirt with an S on it that occupies the armor slot
-Having just one item on your person does **NOT** make you valid (it's JUST a balloon/it's JUST a t-shirt, etc), but having both **DOES** (you can be considered a Syndicate advertising object, marking you as an enemy of NT)

What it accomplishes:
It removes your TC, completely reveals you without a question if you're wearing both, and even gimps you further by taking up a slot that could be armor or a hardsuit, but there's nothing stopping you from just trashing the shirt and using the balloon like how it was before the addition of the shirt.

Also, perhaps a deluxe version that costs all your TC+ the NT opposed bonus that contains Syndicate sneakers/ballcap?

**Comment by Probe1** [comment]
How about we just remove the item from the list since players/admins can't seem to handle a player declaring themselves valid?

The balloon is fine.  Nuke made a stupid decision and changed it to not making you valid.  That was not fine.  We don't need to code better policy.

**Comment by Megamaw** [comment]
we probably shouldnt have to do such mental gymnastics (ie ONLY BOTH) in such a short time to react for this sort of thing

S t shirt would be cool tho

**Comment by Yelier** [comment]
Probe, I think that while it may be more work (not that I can really speak for any of this since I don't know how to code), it'd be better just to add something else to confirm that "YES, THIS PERSON IS INDEED VALID, NO QUESTIONS ASKED." You can still do balloon shenanigans where you may/may not be a traitor if you hold it, but if you really just wanted hardmode without a catch, you could have both on you.

And as for your input, Megamaw, would it really be mental gymnastics? No one thinks twice about shooting the shit out of a wizard with a staff, a cultist with robes and a blade, or nuke ops with a gun, however people are pretty good about not instantly slaying a guy with just wizard robes and a hat, a guy with a cult blade ("object"), or a guy wearing an ops hardsuit when it doesn't seem like it's nuclear emergency.

**Comment by Probe1** [comment]
Yes, it is.  Either you spent all your telecrystals on an item that says I'm Valid or you didn't.  Or you're an idiot and picked up the item.

The item is a mess but it isn't a mess from a code perspective. The only coding solution is to remove it.  The other solution is to tell admins to stop being silly.

**Comment by Exxion** [comment]
Just make the balloon explode comically but harmlessly when dropped, so that it's guaranteed the person holding it is, in fact, a syndie

**Comment by Kammerjunk** [comment]
Nobody would kill someone over holding a balloon with a letter on it.
Nobody would kill a mime for talking.
Nobody would kill someone for reciting bad porn.
Nobody would kill someone for being a cat fetishist.

With the "it's just a balloon" policy, it becomes a 10 TC banbaiting tool instead of a "look how robust I am I'm such a big strong man that I could kill you all with one hand tied behind my back" tool.

**Comment by N3X15** [comment]
Maybe allow it to be dropped, but anyone other than the owner trying to pick it up gets a "you're not a smooth enough operator to hold this" denial.

Other than that, we need a [Policy] tag

**Comment by Yelier** [comment]
But the entire point of the issue that I made is to show that you're valid in a way which both admins and players can say "yes, he's valid" without having to think twice. Just add a warning message on the PDA screen and mention Syndie advertisers in the "enemy of the corporation" part of the Space Law handbook. I could probably even find someone who wouldn't mind spriting/coding it at all.

**Comment by Yelier** [comment]
That was intended for Probe's comment, I'd edit it to say so but I've moved to mobile and can't.

**Comment by mrpain666** [comment]
It was obviously made so that the user would declare themselves valid.

Should we make it a valid kill now?

**Comment by Probe1** [comment]
Sure that'd resolve a whole lot of pain and confusion.

Anyway on point @N3X15 has a sick idea.  Make it pop if dropped so no one knows what a badass you are if you ever let go.

**Comment by Yelier** [comment]
Go for it, just make sure to tell the other admins that it's now valid salad.

**Comment by mrpain666** [comment]
I'll raise the issue with the other admins. I'll make sure to show this to them. There may be a policy change in a week.

**Comment by Yelier** [comment]
What if ZAS or something knocks you over, Probe? That'd encourage people to powergame with magboots and hyperzine, which is the opposite of robust. I'd just go with the inability to pick it up and a flavor message if you're not a tator.

**Comment by Probe1** [comment]
Then you're not the boss and your telecrystals are still gone.

**Comment by mrpain666** [comment]
You buy the thing at your own risk. It is a "joke" item. I think that was the basic, underlying principle in its concept.

**Comment by Exxion** [comment]
@Probe1 Hey that was my idea

**Comment by N3X15** [comment]
Yeah, it was Exxion's, all I did was make it so you can pick it up again if you get ZAS'd or slipped.

**Comment by mrpain666** [comment]
The vote with admins is currently in a huge majority towards letting it be a valid kill. If that majority holds through tomorrow night I will declare it to be policy then.

**Comment by Megamaw** [comment]
robes, blood red space suits, these things stand out.

a tiny little tee shirt doesnt

it's not 'at a glance' it's 'oh i better shift click to check-- oh fuck im dead'

**Comment by Intigracy** [comment]
Feel free to remove the it's just a balloon part of the description, I added it after the last ruling that happened on the matter.

**Comment by Exxion** [comment]
You know
On second thought
I don't even think any code changes at all are necessary
If the rule is the balloon makes you valid, don't pick up the balloon if you don't want to get killed
Maybe make it give a warning when you try to pick it up and let you cancel, but it shouldn't be impossible for non-syndies to have it. It should just be your own responsibility if you do have it.

Plus, if the balloon can be held by other people, that allows a clown who rolls the extra 8 TC to eliminate their target in one of the clowniest ways possible: By gluing the balloon to the target's hand then letting the station do its thing.

**Comment by Zth--** [comment]
It should make you valid, that's the /fun/ of the balloon. And if we do, we should state it in the wiki and make a changelog entry for it or something so people don't cry when they get rekt (they will do anyways)

**Comment by Shadowmech88** [comment]
It should make you valid, because the alternative is everyone *knowing* it should make you valid, while still not being able to act on it because of admin policy, which becomes frustrating for players and admins alike.

**Comment by PJB3005** [comment]
I like the concept that the balloon doesn't make you valid, but let's be honest there's no way to get everybody to brain wash themselves to forget the balloon is a traitor item, so it's better that it DOES make you valid.

**Comment by SonixApache** [comment]
it should make you valid

**Comment by mrpain666** [comment]
You'd pick it up at your own risk, just like any other traitor item.

Since it offers you absolutely no advantage, as it does nothing, there's no reason to pick it up if you find it.

If you use it to kill bait and get your valids as a non antag, we enter different territory that admins will deal with accordingly.
