### ISSUE TITLE
Leather satchel option doesn't work on skeleton

### ISSUE THREAD

**Issue by Yelier** [d3athrow/vgstation13#13857]
It spawns you in with a normal backpack. Not sure how it acts with jobs that aren't assistant, I haven't had time to test it on the main server, the test server is down, and I'm too lazy to host a local game.

Not that it really matters all that much, I think we have a total of like 4 or 5 regular skeleton players.

**Comment by Megamaw** [comment]
as a skeleton player, i think there are even less satchel players.

**Comment by mrpain666** [comment]
Satchel master race.

Backpack players tend to be shitters.

**Comment by 9600bauds** [comment]
But satchels are a straight upgrade from backpacks

**Comment by Megamaw** [comment]
they are???

**Comment by Yelier** [comment]
Smaller sprite, harder to hit.

It also generally looks better.

**Comment by SonixApache** [comment]
the only logical solution is to remove skeletons

**Comment by Kitfox88** [comment]
satchels look better for everything but miners and sec

**Comment by jknpj** [comment]
Some jobs have no satchel option, ate you sure isn't just a job problem?

**Comment by Exxion** [comment]
The leather satchel isn't job-specific
