### ISSUE TITLE
Washed glove sprites with crayons no longer change after the Scrubglove changes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13860]
(WEB REPORT BY: harsetheef REMOTE: 172.93.109.202:7777)
>General description of the issue
When you wash insulated gloves with the mime's crayon, your interface sprites change to the white gloves, but your on-character sprite appears as if they are wearing yellow insulated gloves.  This is a MASSIVE and UNACCEPTABLE nerf to both mimes and clowns.  Literally unplayable.

>What you expected to happen
To have white gloves.

>What actually happened
It looks like mime's with washed gloves now have insulated gloves on.

>Steps to reproduce if possible
Wash insulated gloves with a crayon and wear them.

**Comment by Probe1** [comment]
@Sprok0 

Fix it quickly or the revert fairys coming.

**Comment by JustSumBody** [comment]
~~I thought that was the point of his PR?~~
~~```Recoloring stungloves with a washing machine doesn't revert the worn sprite.```~~

~~So you can't just hide stungloves by washing the gloves~~

Oh nevermind, that's for ALL gloves I'm retarded

**Comment by Sprok0** [comment]
looking into it
