### ISSUE TITLE
Set-pose verb is flavor text but stronger

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13871]
Use the set-pose verb
Enter LITERALLY ANYTHING unlogged, have said text show up on examine through any disguise or identity dealio
![image](https://cloud.githubusercontent.com/assets/19365096/22672975/491ae2f8-eca5-11e6-8a83-8c368d396139.png)

(said player was actually Jackie Chan disguised as someone else, but the text still showed)

**Comment by Ephx1** [comment]
I never understood the purpose of a "pose", surely that can be covered in flavortext?
I'd be fine with just removing it.

**Comment by kol1th** [comment]
It's used in RP servers as something like a "per-round flavortext", showing things that change more compared to the static flavor text. Kindof useless here.

**Comment by Zth--** [comment]
Instead of removing it, we should make it togglable

**Comment by Probe1** [comment]
wait what we have this?

**Comment by kol1th** [comment]
@Probe1 It's always been there. Nobody uses it.

**Comment by ThePlapatin** [comment]
remove this instantly please, we can't trust our current playerbase not to metagame

**Comment by Shadowmech88** [comment]
I wonder how much sanity this has.
Could you use it to convey information via your corpse?

**Comment by Exxion** [comment]
I have nothing against RP features in theory
But in practice they always seem to be really badly implemented

**Comment by Ephx1** [comment]
I'm all for RP but when something is this broken and probably nobody even knows about, I see no reason why it shouldn't be removed.

**Comment by Blithering** [comment]
![pose](https://cloud.githubusercontent.com/assets/15067109/22707271/2cc530d4-ed6a-11e6-9b29-b7c8ec036671.png)
How to cause mild panic with set pose.

**Comment by gbasood** [comment]
@Zth-- the point is that it's possible to use this to communicate without logs to do things such as:
 - ERP
 - Ockick
 - identify a person via their pose no matter what they're wearing or if they're a ling or not
 - other bad things I might be overlooking

Toggleability is not a solution

**Comment by Zth--** [comment]
I mean server togglable, so forks can have it if they want to

**Comment by gbasood** [comment]
Ehhhh
Given the shitcode that it is, which I saw because making a PR to remove it right now, they'd want to rewrite it themselves anyways.
It literally does text parsing on EVERY EXAMINE to add punctuation
