### ISSUE TITLE
Nuclear explosions are shit

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#13882]
#### Description of issue

Nuclear explosions do jack squat. They just lock everyone on every Z-level in place. Not even a small explosion, not even a single death, just placelocking. 

#### Server revision

b31abeda2acbee4f619e5b3506439214eb7a7d32

**Comment by gbasood** [comment]
yeah the only problem with making them do shit is that it'd be one huge costly explosion and possibly kill serb

**Comment by Zth--** [comment]
we can deal with big explosions :wink:

**Comment by SonixApache** [comment]
A bombcap explosion and death to anyone on the Z-level would be a big step up from just 'lol no moving for you'

**Comment by gbasood** [comment]
true

**Comment by BobdaBiscuit** [comment]
The server can survive me unzipping 4 bombcap disabled 22 devs on the main station perfectly fine, a bigass explosion centered on the nuke would be fine.

**Comment by uazuaz** [comment]
what about just killing everyone and turning them to skeletons with no explosion?

**Comment by SonixApache** [comment]
I dropped a dev 70 on my listen server and it sorta worked, not sure if it's a good idea but it's an option.

**Comment by Blithering** [comment]
The AI destruct explosion properly kills everyone, why not copy that?

**Comment by kernikov** [comment]
![ss 2013-09-23 at 07 30 19](https://cloud.githubusercontent.com/assets/5549060/22716126/fad9a83a-ed59-11e6-8bbd-c49efbbf71be.jpg)
Server can handle it.

**Comment by Aurx** [comment]
But people might use the lagspike from the giant explosion to meta that a nuke just went off.  
Do we really want these metasmart individuals to know that the round is over a fraction of a second sooner?  
Do we really want to give them such a massive advantage in the most important part of SS13, the post-round OOC shitposting?  

I say NO.

**Comment by gbasood** [comment]
delaying round end for explosion that has no impact other than "it's pretty" is dumb
if it results in more than 5 seconds of features then I'm personally against it
killing everyone on z-level is fine though

**Comment by mtpowell** [comment]
Everyone should fall over/gib as the screen fades to white or black as the nuke logo appears

Personally I'd like to hear OMG JC A BOMB! as this happens

**Comment by gbasood** [comment]
you already have a big nuclear cutscene that's supposed to play for non-ghosts, we don't need more sound effects for that
actually gibbing people might mess with the cutscene because it'd change  their `eye`

**Comment by Exxion** [comment]
Does anyone happen to know why everyone gets stuck lying down when the nuke goes off, even if it doesn't blow up the station and kill them?
It's because, when the cinematic plays, everyone gets buckled to a bed, which (at least according to Railfist) lies in the game ticker somehow
Yes, really
The purpose is so that nobody moves around while the cinematic is occurring, but then people never get unbuckled, unless they change forms (as a diona nymph or something)
(I haven't actually tried resisting out, so I don't know if that works)

(I've personally verified that there is a bed, but I've never bothered looking actually where it physically is, so the "in the game ticker" part might be bullshit)

**Comment by kol1th** [comment]
Solution: Just make the animation that's supposed to play actually work, and leave a static image on the screen when it's done.

**Comment by Zth--** [comment]
What if we teleported all the players to the beach? Like 'welcome to heaven'

**Comment by kernikov** [comment]
Wow, I'm scientologist and you've triggered me with your Christian imagery.
What is this, Evangelion?

**Comment by PJB3005** [comment]
Just.

Kill everybody. Play the cutscene. While the cutscene is playing drop a big bada bomb so you don't notice the lag.

**Comment by Exxion** [comment]
But sometimes (most of the time) the nuke fails to blow up the station anyway

**Comment by SonixApache** [comment]
gamma radiation

**Comment by Aurx** [comment]
Actually, do nukes still create a bed and buckle everybody in the world to it?  
Because I remember that used to be the case and HOLY SHIT OLDCODE WHY.

**Comment by Kitfox88** [comment]
>gamma radiation

Then everyone should just become hulks for post-round shittery.

**Comment by gbasood** [comment]
@Aurx see what @Exxion said a few messages above

**Comment by uazuaz** [comment]
@Exxion 
are you sure? because most of the time it's not the explosion, but the animation failing, at least for me.
i opened an issue about it https://github.com/d3athrow/vgstation13/issues/13502

**Comment by Exxion** [comment]
I'm not sure, no. I seem to remember that it kills everyone if the nuke is successful, but since there's no visual feedback anymore if it is, I don't know for sure.

**Comment by ghost** [comment]
nukes make boom now

**Comment by SonixApache** [comment]
oh wow i forgot to close my own issue after making a PR specifically for this

**Comment by ghost** [comment]
it happens, I'm still finding old feature requests that have been fulfilled
