### ISSUE TITLE
Peacekeeper borg cuffs don't disappear after being removed

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#13909]
The problem with #13880 is that ``handcuff/cyborg`` when applied still just applies the regular handcuffs to the mob. So the onremoved is only ever going to be on the default cuffs.

**Comment by Zth--** [comment]
Please stop merging non-tested shit

**Comment by 9600bauds** [comment]
Sometimes we make the terrible, terrible mistake of assuming the creator of the PR tested it while coding it.

**Comment by Aurx** [comment]
We really need to start demanding screenshots and videos that prove shit works.  

Or start throwing around punishments for untested code.

**Comment by yclatious** [comment]
You guys could also not merge shit prs like peacekeepers to begin with :^)

**Comment by kol1th** [comment]
@9600bauds And that should stop

**Comment by TheFriggenSawbones** [comment]
great job

**Comment by gbasood** [comment]
@yclatious nice meme

**Comment by Probe1** [comment]
@Zth-- you have a relationship based on trust with me.

every PR, you sell a little trust.  if the PR works you get it back.  now imagine the speed his PRs will be merged.

@Aurx the real talk answer is we just don't merge peoples code who repeatedly fuck up, and they take a back seat if we have to personally test their shit.  See: Dylan.

**Comment by icantthinkofanameritenow** [comment]
Weird, it worked when I tried it.

**Comment by Exxion** [comment]
I don't believe that you actually tried it
At least not properly

**Comment by 9600bauds** [comment]
I think he spawned cyborg cuffs for himself as a test dummy instead of actually testing it as cyborg

**Comment by Exxion** [comment]
Exactly
Not properly
