### ISSUE TITLE
Food processor gives off datum names

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13907]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
It seems that, should something go awry, it references the datum involved

>What you expected to happen
Not for my immersions to be so heavily broken

>What actually happened
Noodles suddenly jumps out of /datum/food_processor_process/mob/monkey!

>Steps to reproduce if possible
Well, here's how it went

Sentient monkey (In this case, a diona) jumped into food processor

They couldn't get out, so activated the food processor while within

It made the processing noise, then at the end Noodles suddenly jumps out of /datum/food_processor_process/mob/monkey!

**Comment by jknpj** [comment]
Diona nymphs can't be processed, even if they don't jump out of it. It's straight fucked up

**Comment by kilozombie** [comment]
Well, living ones. You can process dead nymphs into water buckets IIRC.

**Comment by Kurfursten** [comment]
As a subtype of monkey, they should turn into a bucket with blood

**Comment by kilozombie** [comment]
Oh shit, I didn't realize the bucket was filled with _blood._ For some reason I assumed it was some kind of magic botany shit to get more buckets by growing dionas
