### ISSUE TITLE
Always Random Body isn't saving

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13901]
(WEB REPORT BY: n3x15 REMOTE: 172.93.109.202:7777)
# Revision 
1852b5feb94cc2611f614b9950be30731466120c 
# Reproduction steps
1. Join server
2. Open character settings
3. Enable "Always Random Body"
4. Save Slot
5. Wait 30 seconds
6. Save Setup (Probably not necessary, but eliminating any weirdness)
7. Wait until server restart
8. Open character settings again

# Expected Behaviour
Always Random Body: Yes

# Observed Behaviour
Always Random Body: No

**Comment by Probe1** [comment]
I'm pretty sure it hasn't since riri re-did it 2 years ago.

**Comment by clusterfack** [comment]
@probe1 that was working not saving, I made it work
