### ISSUE TITLE
Defficiency atmos cameras are terrible

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#13914]
#### Description of issue

The cameras for the AI in deff's atmos are terrible. You can't see the toxins computer, the N2O computer, you can't see inside any of the tanks except for the gas mixing tank. It's some gay shit, and definitely done on purpose.

#### Server revision
6a35b36127bcb4aaad3beb78e4c6969d71bc9d0f

**Comment by 9600bauds** [comment]
>can't prasmafrud without a borg to help you

emergent gameplay

**Comment by SonixApache** [comment]
>can't stop plasmafloods without having to task your borg who's already busy trying to save 40 people from dying in plasma hell (if you're even lucky enough to have one)

shitty map design

**Comment by 9600bauds** [comment]
Well, can't you see the mix tank?

**Comment by SonixApache** [comment]
I can, but if they're not using the mix tank (who does?) that doesn't work.
The issue is that nobody even has to cut cameras or APC wires to prevent AI fuckery; the map is already designed to fuck over AI control of the area.

**Comment by Aurx** [comment]
I'm sorry, but I'm not sure this is on the correct site.  
Did you mean to post this here: http://ss13.moe/forum/viewforum.php?f=20 ?

**Comment by SonixApache** [comment]
@Aurx I can file a ban request for Deff?

**Comment by Aurx** [comment]
Please do, the players would love you.  

Jokes aside, banning an entire map is outside my authority unless there's an administrative issue with it that can't be quickly fixed.  
But if you go PR digging and find out who made those cameras be like that, then things could happen.  
First, I'd boot up a local serb and see if I could plasmaflood and stop plasmafloods as AI with that camera config. If I can, then problem exists with player not with map.  Git gud.  
If it's impossible and the cameras were always like that, then the mapper needs to get yelled at.  
If the cameras used to permit AI distribution of hot fun and were changed to not, then it becomes unpleasant conversation time.

**Comment by 9600bauds** [comment]
Why are we overthinking this so much

**Comment by Aurx** [comment]
Hot Fun is mandatory, citizen.  Please assist in identifying the commie mutant traitors who have sabotaged Friend Computer's ability to dispense Hot Fun.

**Comment by SonixApache** [comment]
I went all the way back to Sep 22, 2015 and the cameras were always trash, so I guess I can just chalk this one up to DUUUUNNYYYYYYYYYYY and fix it myself.
