### ISSUE TITLE
Mime backpack is all kinds of wrong

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13929]
(WEB REPORT BY: diavil REMOTE: 172.93.109.202:7777)
Revision: 1c87cd4b41d49edc6ae5fa2682429fe1fb6a5ac9 

Mime starts with a goddamn industrial backpack.

#13926

Possibly the reason.

**Comment by AI-Is-Rogue** [comment]
Doesn't it have to be merged for it to affect anything?

**Comment by Lokiamis** [comment]
I was doing some offline testing earlier and noticed librarians get them too.
