### ISSUE TITLE
The circuit imprinter lacks the chem fridge board

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13925]
#### Description of issue

You can't print more chem fridges ever.

#### Difference between expected and actual behavior

My chem fridge to be repaired.

The clown attached C4 to my chem fridge board and laughed at me.

#### Steps to reproduce 

Purchase C4
Screwdriver crowbar a chemfridge
Attach C4
Watch the light in Medbay players eyes go out

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by kilozombie** [comment]
It would also be incredible if you could wrench up fridges to move them around. It's rare, but there are occasionally instances where you need to bring an assload of medicine or plants to a certain place.

Right now it treats it like you're trying to put the wrench into the fridge.

**Comment by Kurfursten** [comment]
Yes, I too would like to be able to break into chemistry in a few seconds with just a wrench and without leaving any evidence of the break in.

**Comment by kilozombie** [comment]
This is already how you break into a number of places, to be fair. And you could just PDA the AI to open the door for you. But that's a fair point

**Comment by 9600bauds** [comment]
IIRC last time we had this talk #10213 #8055 #7785 there is a circuit but it's only for the kitchen fridge with the chemistry fridge being a super snowflake

I'm of the opinion that we should 

just

you know

let the kitchen fridge hold pills if it fucking wants to and unify both fridges into one

**Comment by ghost** [comment]
Give me a minute, I've got an idea

**Comment by kol1th** [comment]
🤡

**Comment by TheFriggenSawbones** [comment]
🍆

**Comment by ghost** [comment]
Have you ever been antagonized so hard that you made an issue report to never be antagonized the same way?

In all seriousness, instead of being added to the circuit printer, I would like to see the smart fridges currently in the circuit printer to be able to be swaps from botany goods mode to chemistry pills mode via multitool.  Someone mentioned this method a while back and it stuck out.

**Comment by ghost** [comment]
Pretty much what I'm doing now, except using a soldering iron instead

>There's 6 different types of smartfridge, of which 3 aren't used anywhere

Time for funtimes with smartfridges

**Comment by Exxion** [comment]
Friendly Reminder that the chem smartfridge outmodes all other smartfridges except the kitchen and slime ones
The kitchen one can hold seeds and the slime one can hold slime extracts, but the chem one can hold everything else that any fridge can hold

**Comment by despotate** [comment]
I agree with bauds, the kitchen fridge definitely should be allowed to hold pills and shit considering that botanists can grow chemicals and isolate them with a chem master, and the chef might have non-nefarious reasons to place those into his food. _Might_.

**Comment by kilozombie** [comment]
I would love if there were a way to rename exotic plant seeds so you could mark one variety as "peridax+hyronalin fruit" or whatever.

But that's kinda asking a bit much, I guess.

**Comment by despotate** [comment]
does using your pen / label roller not work? you can even rename trays with a verb

**Comment by kilozombie** [comment]
I have no idea why I didn't think of that.
