### ISSUE TITLE
Give AIs a medical hud

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#13921]
#### Description of issue

Silicons default to Asimov and not having a medical hud makes it extremely difficult to know if someones being harmed or not.

#### Difference between expected and actual behavior

AIs be equipped with the tools they need to follow their laws

AIs sorely lacking in a basic no nonsense feature

**Comment by kol1th** [comment]
yeah, uh 
https://github.com/d3athrow/vgstation13/pull/11312
I suggest we just port the AI things other servers have. Like the robot control that lets you control beepskies and floorbots and such.

**Comment by SonixApache** [comment]
Upgrade cameras with medHUDs.

**Comment by Ephx1** [comment]
Big Brother soon fellow ~~fleshlings~~ humans.

**Comment by Intigracy** [comment]
Only if it's based on suit sensors.

**Comment by Ephx1** [comment]
Really though, I'd have to go with some sort of implementation that @Intigracy said, and even then I'm not sure people would be OK with it. A main weakness of an AI is the really vague details they get about people based solely on movements and what they have in-hand. 

Similar to the PR about an AI seeing actions, this opens the way for slightly more hardcore validhunting. "Oh, that clothed guy underneath that other guy _instantaneously_ died? Hmm" and of course "That cuffed guy is slowly dying but not bleeding? _While in dark maintenance in front of that other guy staring at him?_" 

You can pretty much guarantee that you'll know what antags those are without a second thought. You might be able to guess these based on some hardcore observations without the MedHUD, but it puts a big glowing red arrow on them to more easily and readily confirm their non-human status for quick anal-harmbaton action.

I know you can have the Crew Monitor open to do this, but seriously that thing is so fucking broken I wouldn't even consider it. Plus, unless you want to deal with that buggy mess constantly there's a good chance you won't always have it open, and there's no way you're going to snap your attention away from someone in danger.

**Comment by Probe1** [comment]
That's a pretty rough argument.  It's a problem for them to have medihuds even though they can use the (now totally working) CMC for the same information.  And it's only ok if we add some big check based on suit sensors that no ones going to code.

**Comment by Ephx1** [comment]
Well, I'm always up for more ways to stop harm. Just don't say I didn't warn ya when the playerbase inevitably turns up their shit dial to 11 because a silicon gets something to do its job slightly better. 
woop woop harm alarm

> now totally working

just, just get out

**Comment by Probe1** [comment]
It works I swear.  (On my machine)

**Comment by eplgr** [comment]
*>buffing silicons, ever
*>giving them even more tools to validhunt
Stop. Please.

Mainly because I don't think AIs should be all-powerful. 
Maybe we should have a camera upgrade that allows the AI to have medhuds **in that area**. And then, we could talk about changing some of the roundstart cameras to have that upgrade. Like in medbay and some other places.

**Comment by Allspice** [comment]
I'm not fond of dealing with ass pain when the AI makes a call that someone is being harmed by X based on their view of it. AI medhuds please.

**Comment by JustSumBody** [comment]
Serious question: How often do you see camera upgrades applied?
In my experience, I've never seen it.

**Comment by SonixApache** [comment]
I often get carrot camera upgrades when I want to keep tabs on certain areas, like cargo's warehouse.
Camera proxy alarms are useless because they don't alert the AI.
EMP-Proofing is nice, but EMPs are too rare to really worry about it.

Having to stick HUDs in them would be good.

**Comment by Ephx1** [comment]
Upgrades would probably happen if the AI asks. Like with pretty much anything else they ask for, people are pretty pliable if they have nothing to do.

**Comment by eplgr** [comment]
I believe only a few people are aware you can upgrade cameras.
After playing for years, I only realized you could a few months ago while playing as a vampire in deff: apparently, dorms cameras start with carrot upgrades, which meant the AI could see me everywhere in maint around that area.

Anyway, if someone actually adds medhud cameras, the changelog will take care of spreading the word.

**Comment by kol1th** [comment]
Don't make a camera upgrade jesus christ
