### ISSUE TITLE
Mopping with blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13931]
(WEB REPORT BY: edwarus REMOTE: 172.93.109.202:7777)
>Revision d00c2630c3a91e416e5dd79dcb7da69b164ce4e9

>General description of the issue: moping with blood does not work

>What you expected to happen
To be able to spread blood everywhere

>What actually happened
nothing

>Steps to reproduce if possible
fill mop bucket with blood and try and mop

**Comment by ghost** [comment]
Wow, the way the mop works is completely flawed.

Thwapping somebody with the mop doesn't do a touch_reaction, just a generic reaction, so you can't just go and thwap a guys face off with polyacid.

Also with turfs or cleanable decals, it just cleans them regardless of what chemical is within the mop

EDIT: My bad, it's just not using the defines for some reason

**Comment by ghost** [comment]
Oh, I see the problem.

It places the blood, then cleans it

/obj/item/weapon/mop/proc/clean(turf/simulated/A as turf)
	reagents.reaction(A,1,10) //Mops magically make chems ten times more efficient than usual, aka equivalent of 50 units of whatever you're using
	A.clean_blood()

**Comment by gbasood** [comment]
mop code is absolute shit

**Comment by Eneocho** [comment]
Works now. I vaguely recall a PR had changed it but can't remember which.
