### ISSUE TITLE
Cannot remove or resist out of peacekeeper handcuffs

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13940]
#### Description of issue
Peacekeeper Android-552 is trying to handcuff Eliana Quinn!
Peacekeeper Android-552 has put the handcuffs on Eliana Quinn!

The borgs could not uncuff me. They said the timer finished but I was still cuffed
The mime tried but I remained cuffed
I resisted and when the timer finished the message played but I remained handcuffed
My arms were cut off and I remained cuffed

3 of us had to be killed and cloned to get free

#### Difference between expected and actual behavior
Cuffs to be stripped off/resisted off

#### Steps to reproduce 
Get cuffed by a peacekeeper borg

#### Server revision

Saturday, Feb 11th, 2017 
0bed6bce8085eeecf24c46f9b4fc089ca2b847c2 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by kernikov** [comment]
The cuffs also can't be removed via hand removal, you stay cuffed with only one hand.
Oh right, and it's apparently impossible to cut off the second hand/arm.

**Comment by yclatious** [comment]
Peacekeeper borgs are a good addition guys, we promise we 100% tested them.

**Comment by PJB3005** [comment]
@yclatious it was icantthinkofanamerightnow who coded the peacekeepers not leaving cuffs and then managed to test it absolutely 0%, completely unrelated to peacekeepers.

**Comment by yclatious** [comment]
Exactly, why did you folks ever merge peacekeepers, merge peacekeeper bandaid fixes  and why did you folks paint sec borgs baby blue instead of royal blue or red?

**Comment by kilozombie** [comment]
I didn't even realize that by asking the borg to cuff you I fucked your round so badly
I'm so sorry

**Comment by Probe1** [comment]
Guess who the revert fairy is visiting

**Comment by Shadowmech88** [comment]
I don't even understand how this could have happened, cyborg handcuffs have literally no unique properties.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88

I know. I did exactly what you told me to do when I made the fix, and it worked when I tested it on my own. If you have e the slightest hint on what went wrong, I want to know.

**Comment by Exxion** [comment]
(It was #13937)

**Comment by Shadowmech88** [comment]
Yeah but I don't know how #13937 could have caused this, cyborg handcuffs don't override anything from parent handcuffs so they *should* function exactly the same.

**Comment by Exxion** [comment]
Probably has to do with the cuffs being `qdel()`ed *before* being dropped
Though I have no idea why that would cause this
