### ISSUE TITLE
No way to cancel the Block Injector menu for the DNA Modifer Access Consoles

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#13956]
#### Description of issue
This is something that has plagued me for a good while, but I always forget to report it.  The Block Injector menu, in the DNA Modifer Access Consoles for genetics, has no way of being cancelled.  If you select it on accident, it forced you to make an injector and triggers the cooldown associated with it.  This will happen even if you step as far away from the console as possible (the wonders of using DNA consoles within medbay while across the station at arrivals.)

#### Difference between expected and actual behavior
For there being a way to close the awful menu.  Yet there is not.

#### Steps to reproduce 
![22pf0je](https://cloud.githubusercontent.com/assets/20872793/22859035/d0cd524c-f094-11e6-9033-30edbd5f8c9f.png)

Select this option in the DNA Modifer Console menu.

**Comment by 9600bauds** [comment]
Super easy fix will do this later
