### ISSUE TITLE
skeletons can eat from forks

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13951]
they're not supposed to be able to eat

**Comment by Ephx1** [comment]
Simple, just make the fork break their hand when they pick it up.

**Comment by Shadowmech88** [comment]
Make them break a tooth if they attempt to eat off a fork.

**Comment by Megamaw** [comment]
just make them able to eat b/c otherwise they just fucking starve and are slower than diona without the benefits after 30 minutes into the round

**Comment by Shadowmech88** [comment]
Skeletons can eat meat, can't they?

**Comment by SonixApache** [comment]
the obvious solution is to remove skeletons

**Comment by Intigracy** [comment]
Remove skeleshitter.

**Comment by Megamaw** [comment]
@Shadowmech88 they can eat meat, but very few people know this, including most chefs. 

why is it even meat? that makes no sense to me. if it was milk i'd have a sensible chuckle but Why Meat?

**Comment by Kitfox88** [comment]
Something about eating man meat goes here.

Milk would be funny at least though, yeah. But really, they're already dead, why do they need to eat.
