### ISSUE TITLE
you can remove electropacks from your back with clickdrag

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#13952]
as in click drag the icon from your back slot into your hand

you're not supposed to be able to take them off by yourself

**Comment by SkowronX** [comment]
SANITY

**Comment by ghost** [comment]
While I am unable to replicate it as you described, you can take it off by just using the equip hotkey with any backpack type item in your hand.  Which is also a bug along these lines.

**Comment by Exxion** [comment]
*sigh

I just love inventorycode

**Comment by Zth--** [comment]
I'm sure I reported this like 2 years ago

EDIT: I remember making a webm for it, I think it was on gitlab

**Comment by beesil** [comment]
Fixed by #19592
