### ISSUE TITLE
Should Vox Traders start with / be able to easily acquire PDAs?

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#13967]
As we all know, Vox Traders start with only a shitty, torn intergalactic passport ID and a station-bounced radio as their connection to NanoTrasen. It might seem obvious at first glance that no, we shouldn't give Traders even more fancy toys via a PDA. Hear me out as to why I think it is kind of necessary for them to have a PDA or something similar to it:

- Trading relies on communication. Screeching over commons about your box of Marauder circuits when realistically only the roboticist is gonna be fooled by those is unnecessarily painful compared to just PDAing him directly. Yes, if you're particularly robust, you'll rush the miner's and botanist's headsets roundstart and pop their keys together to have access to service, supply, and science, but that's likely an oversight and just department-wide communications aren't specific enough. It'd be great to be able to individually message people to tailor your trade towards their specific needs and I'd be more than happy to have the roundstart radios removed for this. Speaking of which,
- Trading relies on knowing who the fuck you're even Trading to. Missing a PDA means you're missing the crew manifest. It takes a very long time to prepare goods to sell and it's really important to know beforehand who your customers are. The size of the science department determines whether you should get the bluespace beaker or the borer egg, for example. The worst offender is buying clown shoes when there's no clown. Now, it's possible that this is a fair challenge and traders should just spam common for the first fifteen minutes of the shift begging everyone to tell them if there's a clown or a roboticist etc., but the problem is that the arrivals computer can be heard from everywhere so Traders do already start with a limited set of information, ie, who arrived on the station, just not who started on the station to begin with. And I'm sure adding a PDA to the Traders is easier than fixing hearing the arrivals computer everywhere :^) (plus you'd still hear it if you were docked)
- No PDA means no station time. No way of finding that out on the vox outpost or vox shuttle. I'll freely admit that I only care about this because I've been running a contractual Trader gimmick where I'm hired to do a service for x minutes, but seriously, it's stupid that I have to set up a timer for x + byond_lag minutes on my phone instead of just negotiating using the station time. And it's just good to have awareness of what time it is in general so you know what you should hawk and to who. 
- There's probably more general utility functions on a PDA that are necessary for Trader QOL, I dunno.

But why open an issue instead of getting one from:
- The PDA vendor: you can't, it's one of the few vending machines that won't take cold hard cash. The other problem is that 37% of the time you won't start with enough cash to buy one anyway.
- The HoP: fuck this guy. Remember, you're basically relying on an assistant with all-access for mercy. So many problems. Sometimes they don't exist. Sometimes they don't come to their desk. Sometimes they don't know that they can print a PDA. Sometimes they refuse to print one and just tell you to get one from the vendor. Sometimes they just start arguments with you. Sometimes the line is super long. Sometimes he wants money that you don't have for the PDA. Sometimes you get bullied in line. Blah blah basically everything that can go wrong will go wrong. I'm not exaggerating here, I've been in every one of these situations and it's definitely not worth it for the 20% chance that you might get a PDA in less than five minutes and be able to return to your now-looted shuttle.

The other problem with the two above approaches is:

- You need to get onto the station to get them and getting on the station means you're gonna get deported for looking at someone the wrong way. We shouldn't encourage Vox Traders hanging around on the station by crippling their ability to trade unless they get x item from it roundstart. Also, time spent on the station is time assistants spend law 2ing silicons into opening your shutters and looting your shuttle.
- These approaches take too long and are too inconvenient in general, you need the information and messaging capabilities before you leave for the station, not after you go through the five minute bureaucratic slog for it. Time is money for a Trader, and your wares are most valuable early on in the round, forcing them to go through this shit roundstart is just hell.

Of course, I'm aware of the following point against the idea of giving Traders PDAs:

- We're giving Traders PDAs

Maybe we could split up the functions of the PDA into a portable crew manifest with station time and a messaging handheld device. But I'm not spriting that.

**Comment by jknpj** [comment]
Even better, give the vox outpost a pAI. pAI can deal with messaging for their owner just fine.

**Comment by gbasood** [comment]
Only problem I'd see is that their PDAs would basically just be Nanotrasen PDAs
Snowflake trader PDAs when

**Comment by SonixApache** [comment]
PDAs aren't that overpowered, don't see why they shouldn't get one if literally everyone else gets one.
Question is, what cartridge should they get for it, if any? And what color PDA? Maybe a raggedy-ass skin for it, like their IDs?

**Comment by 9600bauds** [comment]
The PDA vendor not taking cash seems like a massive oversight to me, regardless of the whole vox thing

**Comment by despotate** [comment]
If they're getting a cartridge please for the love of god make it have this function:

- Call trader shuttle

This would solve so many problems, holy shit

**Comment by Exxion** [comment]
My favorite thing about the PDA vendor is that you need a PDA to get another PDA

**Comment by SonixApache** [comment]
@Exxion you don't -- you need an ID with an existing account to get a PDA.

**Comment by Exxion** [comment]
Huh. Didn't know you could just jam the ID in there on its own.
Still, it should be able to take cash

**Comment by 9600bauds** [comment]
I think we all can sort of agree 100 bucks for a PDA is overpriced while we're at it

**Comment by Exxion** [comment]
Like anything in the economy system makes any sense
Plus, that's $100 for a chance at a RARE LIMITED EDITION TRANSPARENT PDA

**Comment by Riekland** [comment]
or you could go to the HoP and TRADE for one
you know
just a thought

**Comment by 9600bauds** [comment]
or you could read the OP

just a thought!

**Comment by Riekland** [comment]
wait what the fuck I read it and I swear that paragraph wasn't there
this is a conspiracy against retards like me

**Comment by 9600bauds** [comment]
![time passed](https://cloud.githubusercontent.com/assets/6526157/22865709/8d9bfd98-f148-11e6-953a-8dec9252f714.png)

**Comment by kilozombie** [comment]
I'd be in favor of this, THOUGH it would really make wallets have even less use than they normally do.

>If they're getting a cartridge please for the love of god make it have this function:

>Call trader shuttle

Fucking wonderful. I can't count the number of times some asshole has taken the shuttle to the station, gotten deported out an airlock or begged for a crew ID from the HoP, and then left me on the outpost for 20+ minutes waiting for some borg to be ridiculously kind and help me out.

**Comment by yclatious** [comment]
I don't see a reason for the birds not to have their own version of a pda, as much as I hate snowflakey shit, most vox do have issues with shuttles, make a couple shit vox ones spawn in outposts and the cartridges to spawn next to them, bypasses the rng of available money at start and allows them to check the manifest. That, or just allow the pda machine to receive cash instead of needing a ID with a account if giving them free pdas is too much.

**Comment by Kurfursten** [comment]
The thing I like about the idea of Trader PDAs, as a crew member, is that I can see if there are traders right away. I don't have to bug the AI to check for a ship on camera or waddle down to arrivals myself. And I know they're around right away so I can message them to bring seeds and shit.

What I don't like is that someone can say
>Oh look, Vox traders!
>Oh shit, there are no traders registered on my digital messenger...

But I guess that works with nook ops names too, and heist is still in shambles as a game mode so no sense in balancing around it

**Comment by Blithering** [comment]
Maybe have a single beat up looking PDA that they all have to share?

**Comment by 9600bauds** [comment]
It's a PDA newscaster!

**Comment by Probe1** [comment]
look

you're playing a poverty race in a poverty job.  you're not getting super nice things.  that's not the point of it.

**Comment by kilozombie** [comment]
Regardless
>Fucking wonderful. I can't count the number of times some asshole has taken the shuttle to the station, gotten deported out an airlock or begged for a crew ID from the HoP, and then left me on the outpost for 20+ minutes waiting for some borg to be ridiculously kind and help me out.

is obviously a problem.

**Comment by despotate** [comment]
They still, at the very least, need a way of viewing the crew manifest even if the only way of doing so would be a shitty broken console mounted to their shuttle wall or something.

If I have to type in 'who' to gain an idea of how many crew members there are and watch the arrivals announcements computer to see what types of roles arrive and in what numbers to determine whether I should get the bluespace beaker or the borer egg, there is a fundamental problem with the tools we're giving Traders. Without a crew manifest, barring Trader gimmicks, the first ten minutes of a Trader will always be somewhat the same because I am given the exact same information every shift before coming onto the station, so I always have to buy the "safe" bets and tools for trade.

I'm more than happy for Traders to have a shitty version of the PDA. As I suggested, maybe they should start with portable view-only manifests and a shitty button that calls the shuttle. As Kilozombie has described, sometimes you can spawn with three Traders where one of them is a collossal dickhead and strands the other two by acting like a douchebag, and there's nothing you can do about it that won't get you lynched.

**Comment by Blithering** [comment]
![voxpda](https://cloud.githubusercontent.com/assets/15067109/22997927/6a08275e-f3cc-11e6-8bf9-51ba57af2f7e.png)
It's not stupid, it's advanced!

**Comment by kilozombie** [comment]
Lovely
