### ISSUE TITLE
Box station xenoarch space suits do not have containing pods

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#13964]
So you know that pods that all space suits spawn in, that can be used to clean off plasma from the suit (since they can't be put in the washing machine)?

Box research station doesn't have them so it's a huge pain in the ass when your large artifact/plant spews hot plasma in your face, and you can't clean your suit off anywhere.

**Comment by SonixApache** [comment]
Oh, THAT'S what the UV cauterization is for?

**Comment by SkowronX** [comment]
Those suits should have plasmaguard.

**Comment by PJB3005** [comment]
@SonixApache also cleans blood.

**Comment by Exxion** [comment]
How the fuck does UV sterilization remove anything, anyway?

**Comment by SkowronX** [comment]
Rad magic

**Comment by kol1th** [comment]
Bluespace magic

**Comment by Shadowmech88** [comment]
Fixed by #15441.
