### ISSUE TITLE
Invisible APCs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13974]
(WEB REPORT BY: themegagoat REMOTE: 172.93.109.202:7777)
>Revision f3f8c8766fe65a0b08a75db90be31ca769f723ad

>General description of the issue
After taking an APC off of the wall in a maintenance tunnel, I attempted to place it in a slightly different spot to get it out of the way while building things. Upon placing the APC frame it simply disappeared from existence. I was able to do this three times in the area before I started getting messages saying there was an APC for the area and I couldn't attempt to place it at all. 
Someone placed the APC in the same spot it was originally in while I was writing this and it apparently works just fine there though.

**Comment by Exxion** [comment]
What the fuck

**Comment by Zth--** [comment]
Can confirm. It happened to me on saturday's dorf event. I was like what the fuck? We were creating a new room so I thought it was related, seems like not.

**Comment by uazuaz** [comment]
maybe related:
in the derelict's atmos room there is no APC but all the stuff in the room are powered from round start; in the moment you add an APC frame all the devices will turn unpowered, then when you add a power cell all devices are powered again.

**Comment by Exxion** [comment]
That's not really related
The area is just varedited to be powered or something
I think

**Comment by Exxion** [comment]
Oh hey I guess this mystery's solved

What presumably happened: Where you tried to move it to was in a different area, which already had an APC, and each of the first three times you tried to replace it, you picked up the frame in the first (now APC-less) area.
