### ISSUE TITLE
Internals don't work anymore.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#13980]
#### Difference between expected and actual behavior
I clicked the on button, but they did not turn on.

#### Steps to reproduce 
Put on any kind of internals, prep for space walk.
Observe how your UI light turns off when you touch your inventory even though they were never on.

#### Length of time in which bug has been known to occur
Started 2017.02.13 at 7:45 PM CST, round after TATOR-LING ended.

#### Server revision
09d782445a1434ea6f2b5cf450a43994f094bec4 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by N3X15** [comment]
Fix issued.
