### ISSUE TITLE
Skeletons can't drink milk

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#13987]
What's even the point of a meme race if they don't follow the memes?

**Comment by SonixApache** [comment]
the obvious answer is to remove skeletons

**Comment by ScrambledSteak** [comment]
skeletons should become hulks if they drink milk

**Comment by 9600bauds** [comment]
![calcium strength](https://cloud.githubusercontent.com/assets/6526157/22897426/5003b2ea-f202-11e6-89a6-6a14f7d5fc01.jpg)

**Comment by gbasood** [comment]
#12390

**Comment by SonixApache** [comment]
@gbasood thank you
