### ISSUE TITLE
toxin bombs wont fire in shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#13982]
(WEB REPORT BY: pibeman REMOTE: 172.93.109.202:7777)
It's pretty simple
I made a bomb with a timer, to fire 10 secs after the shuttle launched
The bomb not only did not explode when the shuttle launched, but it exploded inmediately after arriving and ending the round.

**Comment by BobdaBiscuit** [comment]
Assembly timers work in !!!BYOND TIME!!!, which IIRC is half realtime.
So say you set it to be 2 minutes, it will explode in 4 minutes.

So I assume you set the bomb to be like 1-3 minutes, which then doubled so it went off after the shuttle arrived at centcomm.

**Comment by Exxion** [comment]
This is a rare instance of something that's actually our fault despite being blamed on BYOND
Game ticks are 2 seconds, but that's our code, not base BYOND

**Comment by Shadowmech88** [comment]
Still, it deserves at least one test with a manual detonator, just to be sure.

**Comment by Intigracy** [comment]
Are you sure you didn't set it for a minute and not 10 seconds?

It wouldn't explode two minutes later if there wasn't a massive lagspike unless you set it to somewhere around that.
