### ISSUE TITLE
Obliterate siliconbanned / antagbanned autoborger carbons

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#13988]
#### Description of issue

There's nothing more annoying than having to babysit a bunch of turboshitters near your autoborger because they just harmlessly sift through it. There's no indication that they're banned either, they just roll on through.

Would be very helpful if they just disappeared, or if the autoborger at least notified you that they're unborgable.

**Comment by Kurfursten** [comment]
Perhaps it could produce a cyborg with no mind and the game poll for a ghost who is not banned?

That would help more people get back in the round (more fun overall), and mean that the AI isn't shorted a slave

**Comment by Killette2** [comment]
While it's fun to do what I do, request a cyborg ban then play as a clown pretending the autoborger is a slide and confusing the AI when they don't know why you're being borged, this can be a problem.

I like Kurfursten's idea, but what about rev and cult? I remember trying to rev someone a few days ago and the process to murder him while he was ratting me out when flash told me he was revbanned was a huge hassle when I was already on the run.

**Comment by Kurfursten** [comment]
I think we already implemented a special behavior for cult but I can't recall it at the moment

**Comment by Killette2** [comment]
I forget what it was also, I think they get knocked out and it informs you they are cult banned? Still a very big problem for revs too because you can't stand around killing a guy after he already calls you out because back up is coming

**Comment by SonixApache** [comment]
ideas from the thread:
1: Create blank borg, poll ghosts
Issue with this is that the new borg occupies space, and that it consumes an autoborg charge. Might be a critical moment, which would be bad.
2: Just gib the carbon
Issue is no pay-off at all -- you've got the autoborger, you fed someone into it but there's nothing to show for it except some nice red decorations
3: Add processing time (for more malf stuff)
This'd be really nice -- whenever a carbon fucks you over, you get more toys to help unfuck the situation. 5 per kill wouldn't be too bad. Issue with this one is that there's no other way to get processing time.

4: Make it remove the cooldown from the next borging so that after the next person goes in the factory is immediately ready again.
5. Force pull a ghost that has malf set to "yes" or "always"
6. Give them survivor
7. Turn them into a MoMMI
8. Hack/control a random MoMMI and gib the carbon
9: Reduce the win timer
10: give the next borg a better cell
11: permanently upgrade the recharge speed of the autoborger

**Comment by Killette2** [comment]
Turning a salty carbon into a MoMMI during malf is asking for silicon bans (you don't think the MoMMI will try to hurt the malf in the case of some players?)

**Comment by DeityLink** [comment]
So apparently that's a thing now.
