### ISSUE TITLE
Regular eswords may ignore electrified grilles, but not dualswords

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#13997]
#### Description of issue

Dual eswords don't protect grills

#### Difference between expected and actual behavior

Ignore like reg swords

**Comment by 9600bauds** [comment]
dualswords have absolutely no sharpness at all
w e w

**Comment by Exxion** [comment]
Is the dualsword not a child of the esword, or does it override `sharpness`, etc.?
I'm not sure which would be worse

**Comment by Aurx** [comment]
It's a completely distinct item, since it has to inherit two-handed item stuff.

**Comment by 9600bauds** [comment]
`/obj/item/weapon/dualsaber/`

nope

it doesn't have to inherit anything

**Comment by Aurx** [comment]
Huh.  Could have sworn.  
Did the twohand stuff get moved to a proc then?

**Comment by Exxion** [comment]
Not even
It's just a bitflag

**Comment by strawberrytan** [comment]
To add to this, double bladed energy swords seem to not have an on hit sound effect whereas the energy sword does

the distinct energy thunk is missing
