### ISSUE TITLE
Monkeys wearing sunglasses does not protect them from flashes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14005]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 8a749be3999be77a66ae9ab4768d6a7f52813d55 

>General description of the issue
sunglasses and mesons don't work on monkeys, and I can't think of a good reason why they shouldn't

>What you expected to happen
I expected the sunglasses to protect from flashes

>What actually happened
they did not protect from flashes

>Steps to reproduce if possible
be monkey, wear sunglasses, apply flash

**Comment by Killette2** [comment]
I thought monkey armor did nothing in general, like wearing sec helmets as a monkey being just cosmetic

**Comment by SonixApache** [comment]
is that because armor is defined only for humans in life.dm?

**Comment by Killette2** [comment]
I have no clue, I'm only parroting something I've heard in this instance and I've never noticed a difference wearing armor as a monkey

**Comment by Exxion** [comment]
That is very possibly true
