### ISSUE TITLE
Move the bee virus to stage 3

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14008]
After playtesting it a bit I've come to the conclusion that stage 1 has too much and stage 3 doesn't have enough in terms of "The crew won't kill you" symptoms.

**Comment by ghost** [comment]
Fair point

**Comment by Killette2** [comment]
I'm not sure on this one. A lot of stage 1 things feel bland even though it's supposed to be a relatively tame stage that doesn't mean we can't have a bit of fun there. On the other hand, 3 is lacking in fun and variety that won't fuck you over.
