### ISSUE TITLE
Cultify Artifact Effect fucks up terrain

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#14006]
#### Description of issue
Cultify artifact effect does the following:

* Delete all windows
* Converts grilles to cult grilles, which doubled with the above can shock unsuspecting fucks
* Deletes asteroid walls completely, only space left behind (this could be assumed for any other non station wall)
* Converts R-walls to non reinforced cult walls

What this means is you unintentionally fuck the station if you waddle around cult converting it, which I don't think is intended.

#### Difference between expected and actual behavior
**Expected:**
* Basically cosmetic changes to make the environment more culty

**Actual**
* Fucks up the environment and makes it more dangerous

#### Steps to reproduce 
* Use cultify

#### Specific information for locating

code/modules/research/xenoarch has the files

#### Length of time in which bug has been known to occur

Since it was added.

#### Server revision

8a749be3999be77a66ae9ab4768d6a7f52813d55 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
Does it make riveted walls and shuttle walls breakable? Time to raid centcomm

**Comment by BobdaBiscuit** [comment]
It might actually straight up delete them.

**Comment by SonixApache** [comment]
why don't we just get cult windows that are red or something

**Comment by Sprok0** [comment]
Cult grilles are airtight, cultify shouldn't depressurize anything. I'll make it only cultify simulated turfs though, I only tested it on the station when I made it.

**Comment by BobdaBiscuit** [comment]
@Sprok0 
The issue with cult grilles is that they can shock people due to the windows being deleted, and also the fact that single directional windows are deleted which could fuck up departments or certain areas.

**Comment by Intigracy** [comment]
Which is why the grilles are airtight.

**Comment by Sprok0** [comment]
Exposed electro-grilles and normal walls seem fine to me, cultzone isn't supposed to be entirely safe. I can't think of any areas where removal of directional windows would do serious damage to an area, can you give some examples? Everywhere that I can think of uses windowgrilles for anything important.

**Comment by BobdaBiscuit** [comment]
It's just annoying since it makes cultify an artifact effect you can't go around using decently as non antag for hilarity, since it actively makes the station worse and could result in people getting hurt from being shocked from what appears to be an undamaged window.

In regards to window deletion mostly small containment pens (ie artifact containment on the outpost) will get fucked, but importantly things like atmos projects and mixing chambers that atmos techs/engineers make will be breached causing huge gas leaks, this could be done completely unintentionally if the cultify range is large enough to hit atmospherics from the central hallway.

Window deletion is also shit for if the station is damaged in any way, if a regular grille from a space window is destroyed ZAS gets invited in and the user a nice bwoink.

**Comment by AI-Is-Rogue** [comment]
@BobdaBiscuit It was stated in this issue that cult grilles are airtight.

**Comment by BobdaBiscuit** [comment]
>if a regular grille from a space window is destroyed ZAS gets invited in and the user a nice bwoink
