### ISSUE TITLE
You can only really use two out of five of the Trader shuttle tables to display your wares

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#14003]
Not just the table in directly behind the windoor, but also the two to the side of it, can have their shit stolen if you open the windoor. You only really have the two tables at the top to place your stuff for display, but they're kind of out of the way and one of them already stores paper and a pen. There's also the one at the corner which is also quite out of the way.

**Comment by Kurfursten** [comment]
Easily fixed with some directional windows.

You should be able to do this yourself but it wouldn't hurt for a mapper to touch this up

**Comment by kilozombie** [comment]
FWIW, I always put the paper/pen bin in the nearby backpack, as well as the rack parts in the crate. Then I put the table parts on the bottom side of the shuttle, next to the other table. Now I've got 4 safe table spots as well as a crate.
Then I put low-value goods by the windoor and curse out or report or flash+disposal anyone who tries to steal them.
