### ISSUE TITLE
Constructs don't have intents

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14013]
#### Description of issue

Without intents, you can't destroy tape.  This makes police tape as impermeable as a riveted wall.  As hilarious as that is it's also s h i t coding.

**Comment by AutismSpider** [comment]
Should be for all mobs  intents and pick limbs to hit etc

**Comment by Shadowmech88** [comment]
Unless this was fixed or changed, I think it's still an issue worth being open.

**Comment by Probe1** [comment]
True fact:  My only ban was because I murdered a guy as a construct cause it was my first week playing and thought they had intents and would be on help like everything else.  5 years later they still don't.

**Comment by Exxion** [comment]
The tape part was fixed by #18228
That's not the *whole* issue, but it's the important part
I'd honestly recommend just making a new issue if you want further discussion on the topic, since nobody is ever going to look at this one again
