### ISSUE TITLE
Ventcrawling via alt click allows dionas to enter pipes when they are buckled.  At that point they are both anchored and out of the chair which fucks them up forever.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14015]

**Comment by Exxion** [comment]
Maybe we wouldn't have problems like these if everyone weren't so afraid of `Move()` for some reason

**Comment by Intigracy** [comment]
or
OR
we could just stop copypasting all the checks and put them all in the ventcrawl verb, and then have alt clicking call ventcrawl() since you can call verbs as procs.

**Comment by Exxion** [comment]
I mean
That too
But we really overuse `forceMove()`

**Comment by Shadowmech88** [comment]
Was this fixed by #15723?

**Comment by Exxion** [comment]
Presumably, considering it fixed it for MoMMIs
