### ISSUE TITLE
A recent PR killed a fuckload of overlays.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14025]
![dreamseeker_2017-02-14_10-55-19](https://cloud.githubusercontent.com/assets/8550416/22977606/51736376-f35d-11e6-9e35-a09d122b1d5d.png)

Asteroid tiles aren't getting their overlays until one of the turfs are destroyed.

Genetic powers overlays are missing.

Probably a lot others.

**Comment by Intigracy** [comment]
Saying something right when it started happening would have been nice.

**Comment by Probe1** [comment]
Yeah I'm looking through commits to find it now.  Best guess is anywhere from 2 to 4 days ago.

**Comment by Probe1** [comment]
Tested commit from 3 days ago.  Issue was still there.

Tested server on stable version of BYOND.  Issue was still there.

**Comment by Probe1** [comment]
Tested commit from 7 days ago and issue didn't exist.  https://github.com/d3athrow/vgstation13/tree/48f3bb616798eef39541d45ff81e0e8b11cab444

Its somewhere between 3 and 7 days ago.

**Comment by Probe1** [comment]
Tested commit https://github.com/d3athrow/vgstation13/commit/3745682b3498593fa83ad55e7443966d38271554 from 6 days ago and the issue didn't exist.

**Comment by Zth--** [comment]
Test #13930

**Comment by Probe1** [comment]
Tested #13930, issue exists.  So the frame is between #13930 and 3745682

**Comment by Probe1** [comment]
It was https://github.com/d3athrow/vgstation13/pull/13930

**Comment by gbasood** [comment]
couldn't tell you why though
it's possible there's a proc referencing `turfs` that's finding another `turfs` var in its scope that somehow *wasnt* the global turfs list but that'd make zero sense

**Comment by Shadowmech88** [comment]
The existence of a `turfs` var in *any* scope would trigger a duplicate definition compilation error if a global `turfs` var already existed, wouldn't it?

**Comment by gbasood** [comment]
Nope that's not how scoping works
```dm
var/turfs = "honk"
proc/honk()
    var/turfs = "don't honk"
    world << turfs

honk()
```
you'd see "don't honk"

**Comment by Exxion** [comment]
It works fine
But please don't do it
It causes only confusion and pain

**Comment by gbasood** [comment]
such as right now
when there's no good reason this should happen but it is anyway

**Comment by Shadowmech88** [comment]
If locally scoped vars override global vars, then why would the removal of the global var have changed anything?
The code in question would've been using the local `turfs` var even before the global var was removed, right?

**Comment by Exxion** [comment]
That is the mystery

**Comment by gbasood** [comment]
My only other theory is that `in world` is too hueg for BYOND and it fucks up or something
Which seems dumb because I figure we'd get a runtime or warning
Unless it was considering it an infinite loop in which case fuck

**Comment by Exxion** [comment]
`in world` is common practice in the DM Ref
And it's not really that many more things than `turfs` was

**Comment by gbasood** [comment]
Well actually `in world` is technically all atoms ever
But it shouldn't be causing this
The shit that causes overlays for mining turfs specifically is `initialize()` which is called by the master controller
I have no idea why that'd be breaking but I'm fixing some long standing bugs that are runtiming on initialize()

**Comment by N3X15** [comment]
Fixed by 14029

**Comment by Exxion** [comment]
Yeah
And most atoms are turfs
At least I think

**Comment by N3X15** [comment]
May be fixed by #14029

**Comment by Probe1** [comment]
It wasn't.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/14077
https://github.com/d3athrow/vgstation13/issues/14065
