### ISSUE TITLE
You can use a Morph Mask to hide the Disk forever

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#14033]
A simple guide to fucking over the nuke cops
1. Inexplicably get hold of a morph mask whilst the nuke cops are busy masturbating and discussing strategy
2. Hold nuke disk in your hand
3. Wear mask

Disk gets sent to nullspace with your body and there is no way the cops can get a hold of it again. Even if they murder you they cannot force you back from being transmorgged. Its worse if the mask is cursed because now you can't even get the disk back. 

The disk should ideally prevent the mask from working or get spawned on the station somewhere and not sent to nullspace.

**Comment by Shadowmech88** [comment]
The disk's respawn check should probably check if the disk's top-level container is in nullspace, as well as checking if the disk itself is in nullspace.

**Comment by Exxion** [comment]
`if(!get_turf(src))`

**Comment by N3X15** [comment]
Transmog should probably dump all items it can't transfer to the ground.
