### ISSUE TITLE
jukebox bugs when its maintenance panel is open when unwreched

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14040]
(WEB REPORT BY: januszpavulon REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
e1a943d8818a63d4a2f3267f9ed002983467c21e

>General description of the issue
if you open the maintenance panel of a juke when its unanchored you cant do shit with it other than cut wires, cant anchor it, cant close the panel, nothing

>What you expected to happen
juke not bugging and becoming useless metal box

>What actually happened
juke became a useless metal box

>Steps to reproduce if possible
unanchor a juke and then use a screwdriver on it, it becomes broken and unrepairable

**Comment by jknpj** [comment]
>when its maintenance panel is open when unwreched

thanks oldcoders

**Comment by jknpj** [comment]
duplicated issue of #5859 and #9747
