### ISSUE TITLE
Homeostasis machine gets flatpacked incorrectly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14043]
(WEB REPORT BY: streptomutans REMOTE: 172.93.109.202:7777)
When you make a thermal homeostasis regulator flatpack, the right half outright spawns next to the flatpack fabricator when the flatpack is made, breaking it, and when you open the flatpack only the left half comes out. There is no way to move the right half away from where it spawned besides Admin help.
Really ruins custom medbays and the immersion

**Comment by PJB3005** [comment]
This fixed so I can stop closing dupes when.
