### ISSUE TITLE
Mr Clean doesn't work again 

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#14059]
If you spawn him, he has no sprite.

Guessing its from @ihadtoregisterforthis' animation pr

**Comment by gbasood** [comment]
how dare mr clean not have a sprite

**Comment by jknpj** [comment]
can't be @ihadtoregisterforthis fault, the narsie animation file is standalone

**Comment by gbasood** [comment]
is this reproducable actually? with our memory problems it could be BYOND messing up once

**Comment by Exxion** [comment]
I don't think that one's due to memory problems, as it's clientside
Or rather it's due to clientside memory problems, which aren't the same

**Comment by gbasood** [comment]
server fuck ups can translate to display fuckups
BYOND game servers are very authoritative

**Comment by Exxion** [comment]
They're completely authoritative, except for rendering
And this is a rendering thing

I think it probably comes from having too many appearances or something

**Comment by gbasood** [comment]
byond did it
thanks RAM
