### ISSUE TITLE
Oversight? Cuffs + caged = stuck

### ISSUE THREAD

**Issue by MasterofNothing** [d3athrow/vgstation13#14054]
Issue/oversight(/feature?):

1) Get cuffed.
2) Get put in a cage.
3) Resist.
4) Despair as you can't shrug off the cuffs, nor open the cage.

Expected:

Shrug off cuffs, open cage. Or something else, I don't know.

Why it's an issue:

Security has been abusing this. Cages are way too easy to get to make this a valid gameplay element. If you would have some stasis chamber instead that needed a lot of research, sure. Then I could live with it (a little). You can just remove someone from the round entirely now.

**Comment by jknpj** [comment]
you need hands to struggle, no wait nevermind i see your point

**Comment by Shadowmech88** [comment]
You can unbuckle yourself from chairs while cuffed, cages should behave the same way.

**Comment by SonixApache** [comment]
Cages prevent you from doing anything. If you're on the floor you can't get up either.
They're made outta plasteel, which is magic anyway.

**Comment by beesil** [comment]
Closed by #18955

**Comment by ShiftyRail** [comment]
It was also a dupe of a previous issue
