### ISSUE TITLE
CMC: it. just. works.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14062]
#### Description of issue

As silicon you can bring up the CMC and it will function forever. It'll work when out of vision range, it'll work when it's not powered, it'll just work forever. 
I think carbons can keep it up forever as well, but it doesn't update unless it's in your vision range or you manually switch modes.

#### Server revision

7b8e568919d708387e4bdaa7df41bb39100bb1db

**Comment by kol1th** [comment]
AI should have a built in CMC :^)

**Comment by Aurx** [comment]
Well maybe the carbons should have gotten a better data plan then, not the AI's fault they don't get reception at their workplace.

**Comment by SonixApache** [comment]
don't think this is a thing anymore
