### ISSUE TITLE
Genetic powers and bottles are not showing their overlays.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14065]
#### Description of issue

![image](https://cloud.githubusercontent.com/assets/8550416/23077011/c547461e-f510-11e6-8356-397a76a9a9b1.png)

These bottles should be white.  Likewise, bottles filled with mutagen appeared empty despite having 30u in them.

#### Length of time in which bug has been known to occur

1-14 days

**Comment by Probe1** [comment]
Its older than this commit https://github.com/d3athrow/vgstation13/pull/13930

**Comment by Probe1** [comment]
its older than this commit https://github.com/d3athrow/vgstation13/commit/3590eeaedb0e47569e0a43b065f0806461d0b658

**Comment by SonixApache** [comment]
did you figure this out yet because bottles are still fucked

**Comment by Probe1** [comment]
nope
