### ISSUE TITLE
Lawgiver bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14060]
(WEB REPORT BY: eopaxe REMOTE: 172.93.109.202:7777)
Revision 00b92913d29614a31815e48eff11b3230bf6cf10

If you're not the HoS, the lawgiver explodes - but not if you fire it point blank. Not sure it does damage point blank, either. 

Step one to reproduce:
Fire lawgiver point blank at entity next to character.
Step two: Fire it non-point blank.

**Comment by Probe1** [comment]
Okay what i'm seeing here is it was DNA locked and he doesn't know about that.

What I'm also seeing is the gun fires AND melees, and the check must be detecting the melee attack and passing but the gun still fires @Shadowmech88

**Comment by Shadowmech88** [comment]
I made the Lawgiver a long time ago, its firing code might be shit. I'll take a look at it.

**Comment by Exxion** [comment]
I think he knows about the DNA lock
The bug report is the second part
