### ISSUE TITLE
pAI-controlled medibots open blastdoors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14071]
(WEB REPORT BY: acedick REMOTE: 172.93.109.202:7777)
>Revision bfac15d3267ece041c6651ea8c1a17746543941a 

>General description of the issue
Found that as a pAI in a medibot you are capable of bumping into blast doors to open them automatically, bypassing and trivializing lockdowns in this way.

>What you expected to happen
Blast door to remain closed

>What actually happened
Blast door was opened when accidentally moved into.

>Steps to reproduce if possible
>be pAI in a medibot
>walk into blast door
>it opens

**Comment by Zth--** [comment]
pAI medbot movement is actually medbot movement, so yeah, normal medbots can open blastdoors too.

**Comment by AutismSpider** [comment]
just medbots or all bots?

**Comment by Shadowmech88** [comment]
Not all bots, I'm pretty sure MULEbots only have Cargo and Maintenance access.

**Comment by AutismSpider** [comment]
both bot types can't open  or close fire locks.
