### ISSUE TITLE
Can't play at all - no Byond version works (without utterly crippling issues) & I might as well ask here

### ISSUE THREAD

**Issue by MasterofNothing** [d3athrow/vgstation13#14087]
Which Byond version should I use? I'm having terrible, game breaking, crippling issues and I've tried a whole bunch of things already. Other suggestions also very welcome.

Some info:

511.1374 = can't move without BLEEP BLEEP BLEEP sounds
511.1373 = frozen viewport for 10 sec upon joining and bleep when moving
511.1372 = goonchat fucked, bleeping when moving
511.1371 = goonchat fucked, extremely slow joining, bleeping when moving, dreamseeker won't shut off, unless forced
511.1370 = bleeping when moving, viewport freezes first 30 seconds
511.1369 = viewport freezes first 15 seconds, bleeping when moving, higher ms
511.1368 = bleeping when moving
511.1367 = least terrible so far, but still fucking terrible, but viewport sometimes freezes + takes 30 seconds to work at all, subtlepm format is fucked up, crew monitor takes time to work
511.1365 = frozen viewport, no chat messages/radio arriving
511.1364 = messy tiles = lag
511.1363 = messy tiles = lag
511.1362 = viewport doesn't even work. At all. Dream seeker process gets stuck
511.1361 = messy tiles = holy fuck, is this a slideshow?
...
511.1348 = messy tiles = SEND HELP & consoles don't work properly / at all
510.1347 = 4000+ ms

My system is fine - i7 5820k, 980ti, no issues with anything other than Byond. I've updated my DirectX with whatever version I could find and I've tried several Nvidia drivers (and I'm now on 378.49). I do run W10, fully updated.

Obviously, I can counter the bleeping on some versions (replace Windows settings with an empty sound file), but this doesn't help at all. Moving then causes lag, and the mouse cursor blinks / shows something's going terribly wrong.

---

511.1365 stopped freezing for whatever, mysterious reason, when I re-installed it. Not sure if it'll stay that way. It still lags a bit, but at least I can sort of play.

**Comment by N3X15** [comment]
Clear your cache. 

1. Byond Main Window
2. CTRL+P.  
3. Games Tab
4. Clear cache

**Comment by MasterofNothing** [comment]
@N3X15 

Doesn't fix most of the issues (e.g. bleeping when moving), but with 511.1365 it has reduced lag significantly. Can't tell you yet what it means for 510.1347 (stable), because resources are downloading super slowly.

Will update once I get the resources downloaded. Thanks.

---

Stable (510.1347) now works fine! I wouldn't say it's silky smooth (as it's been in the past for me), but it's certainly playable. 511.1365, 511.1367 are also fine, with 1365 probably as the best one for now.

Thanks! I'll close this.
