### ISSUE TITLE
The station (hasn't) cleared the meteor storm.

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#14083]
Meteor storm clearing used to be based on when meteors stopped spawning, but since we made zlevels bigger, it says the station has cleared the wave before the last set of meteors hits.

**Comment by Riekland** [comment]
I kind of like it tbh
It adds flavour to the r o l e p l a y when new players expect the explosions to be over when the announcement comes, then they get scared when things blow up after the announcement while everyone else just sort of accepts it
It fits the shitty stations we have that something as important as a meteor warning would be fucked too

**Comment by SonixApache** [comment]
rod warnings, carp warnings and xeno warnings always late, meteor wave warnings always ends early
***nanotrasen***

**Comment by ghost** [comment]
I don't exactly remember how it times it, but it's probably too tight, just drop some extra delay

**Comment by DamianX** [comment]
Had an idea on how do this but then I looked at the code
