### ISSUE TITLE
Wooden Plankss

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14086]
(WEB REPORT BY: cisrox REMOTE: 172.93.109.202:7777)
>Revision 18d2b569ce5a205b232a834b71575c70fb50423e

>General description of the issue
Wooden planks when examined say, There are 50 wooden plankss in the stack.

>What you expected to happen
There are 50 wooden planks in the stack.

>What actually happened
There are 50 wooden plankss in the stack.

>Steps to reproduce if possible
Examine wooden plank stack with more than 1 plank.

**Comment by jknpj** [comment]
>What you expected to happen
There are 50 wooden planks in the stack.
What actually happened
There are 50 wooden plankss in the stack.

>singular_name = "wood plank"
irregular_plural = "wooden planks"

Easy fix :tada:
