### ISSUE TITLE
dead diona nymph sprite issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#14096]
#### Description of issue
when a diona nymph is not taken by any ghost and dies, the dead nymph uses the same sprite of an alive nymph; also, if you drag the dead nymph around it uses its walking animation.
i don't know if this also happens on nymphs that are killed.

#### Difference between expected and actual behavior
expected the dead nymph using the dead nymph sprite

#### Steps to reproduce 
plant diona seeds
wait until it dies

#### Length of time in which bug has been known to occur

i don't know, but this doesn't happen on the outdated test server.

#### Server revision

7645b476792b73d2a1a42f25564522e95f084c16 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
This wasn't the case before
hrm

**Comment by jknpj** [comment]
update_icon isn't working for the lying/dead sprite for some reason
