### ISSUE TITLE
Can't create Bleach in chemistry

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14101]
(WEB REPORT BY: zhanbao REMOTE: 172.93.109.202:7777)
>Revision d5a905648f26e44ab5ea72d76c8ccde857641f82

>General description of the issue
Cannot create bleach from scratch, the sodium and chlorine in the recipe mix to form table salt no matter what order you mix them in.

>What you expected to happen
Mixing (SODIUM = 2, CHLORINE = 2, OXYGEN = 2, CLEANER = 4) to make bleach.

>What actually happened
Makes slightly salty space cleaner.

>Steps to reproduce if possible
1. Mix Space Cleaner
2. Add Sodium.
3. Add Oxygen.
4. Add Chlorine

**Comment by Probe1** [comment]
@unusualcrow "I tested it"

**Comment by ghost** [comment]
fuck i forgot to test that
i'm absolutely retarded

literally the ONLY thing I forgot to test
