### ISSUE TITLE
Calling the vox trader shuttle should automatically attempt to close and temporarily bolt the shuttle's pair of airlocks and the corresponding arrivals airlocks

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#14106]
I've spaced at least three customers completely on accident because I called the shuttle back to the outpost before noticing that someone was trying to enter the shuttle. Can't really prevent this as a trader and it's a shitty situation for the spacee as they're now at telescience's mercy to get back into the round.

**Comment by Riekland** [comment]
This will make it difficult if not impossible to get away from people who are trying to murder the vox.
May I suggest not going near the vox shuttle for fear of spacing/catching a disease/theft/murder/the smell?

**Comment by Intigracy** [comment]
Or give it a few seconds of delay before it leaves, with an intercom that yells at people to stay clear.

**Comment by Durgen** [comment]
it already has a delay, an intercom would help though

**Comment by Shadowmech88** [comment]
We should have non-dense warning light structures that can be layered over airlocks and flash when a ship is preparing to move, so that people can tell whether they might end up walking into space if they try entering that ship.

**Comment by Zth--** [comment]
Hmm. Maybe add a remote signaler to the computer which sends a signal every time you launch your shuttle.

Edit: and then you connect them to Shadow's idea
