### ISSUE TITLE
Shotguns are really awkward to use now.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#14117]
Recently, shotguns were made to require two hands to fire, pump and break. This combined with the shotguns low ammo count (particularly in the barman's shotgun) have made it really annoying to use. 
Try spawning a double barrel and armour on the test server, take the gun off your armour, fire it, reload and put it back. 
This should be simple, its the basics and could be called on to do any number of times in a round, but unintuitive things like having to swap to the offhand and drop to unwield, not being able to put a wielded weapon on your armour and pump/break being the same action as wielding will cause fuckups. Accidentally unloading your ammo when you wanted to fire or getting disarmed because putting your gun away takes four steps is gonna be a pain in the arse.

**Comment by kol1th** [comment]
That's why I wanted it alt click

**Comment by kol1th** [comment]
Also 70 brute damage weapons shouldn't be easy.

**Comment by Blithering** [comment]
I'd argue that the slow rate of fire, low ammo count, ammo needing to be stored and loaded individually and inability to fit into backpacks were downside enough, particularly seeing as revolvers deal similar damage. Either way making them this clunky to use isn't the right solution if they were unbalanced.

**Comment by Shadowmech88** [comment]
Aren't revolvers also exclusive to traitors, though?

**Comment by Allspice** [comment]
Well, it was 40 brute (60 for combat) before the change so that's an odd argument.

**Comment by SonixApache** [comment]
We should port CM's shotgun shell stacking feature. That'd make this rework viable.

**Comment by Blithering** [comment]
@Shadowmech88 Traitors, detectives with a screwdriver or anyone who visits the goone sat

@SonixApache Shell stacking isn't the problem, the clunky as fuck handling is.

**Comment by aratherangryduck** [comment]
We should port it anyways, probably one of the few things CM ever did right was the ammo management

**Comment by Exxion** [comment]
Making it cumbersome is not the same thing as making it hard.
As a general rule, if a macro can circumvent your "difficulty", it's not actually difficult

**Comment by Killette2** [comment]
Just port ammo stacking and then decide on this change

**Comment by Blithering** [comment]
Change was reverted, closing the issue.
