### ISSUE TITLE
Folders/clipboards should work like bags and scoop up papers/photos

### ISSUE THREAD

**Issue by Apelsinsaft** [d3athrow/vgstation13#14110]
**The problem:**

If you put a paper in a folder, you have to remember which order you put all your papers into the folder if you ever want to fish it out without inspecting your entire folder, and having to put every paper in the folder manually is a pain for paper-intensive jobs like cargo, journalist, IAA or --god forbid-- paperwork gimmick HoP.

**The solution:**

Folders/clipboards are now a type of bag, and like for example plastic bags will scoop up every item on a tile you click, while being restricted to papers and photos. Additionally, like other bags, when you interact with a folder/clipboard the items inside are visible and you can interact with them directly. Even if the folders/clipboards could only hold 10 papers or photos, this would be a massive improvement since you can now identify which photo is which with a glance, tell stamped from unstamped papers apart with a glance etc.

**Comment by JustSumBody** [comment]
Rename your papers, shows the full titles

Also god fuck this was something I started to do and then dropped because "surely nobody else really cares about this"

**Comment by Probe1** [comment]
its one of those things you don't notice isn't there until you have it and you wonder how you lived without it
