### ISSUE TITLE
Poppy pretzels can only be made with roundstart seeds

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#14114]
I'm guessing due to xenobotany reworks somewhere down the line, seeds which are clipped off of poppy flowers or through the seed extractor don't work.

**Comment by ghost** [comment]
It checks for the subtype object /obj/item/seeds/poppyseed. Any seed clipped after is just /obj/item/seeds with the poppy plant in reference.

**Comment by ShiftyRail** [comment]
Dupe of #12582
