### ISSUE TITLE
sometimes airtight flaps aren't really airtight

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#14121]
Description of the Issue:
![scrnshot1](https://cloud.githubusercontent.com/assets/20007336/23128212/d1e77666-f75c-11e6-9111-89c94aa4dde1.png)

>try to use airtight flaps to separate rooms with different gases/pressure/temperatures
>doesn't really works and the gases will just ignore the flaps.

**What was expected**
a tiny hot room to dry leather.
**What actually happened**
me getting cooked.

the issue keeps happening if you have a hot chamber bigger than 1 tile, i can create single tiles hot chambers without problems, but when the hot chamber is bigger than that the issue happens.

**Comment by jknpj** [comment]
you have to crowbar it to make it airtight IIRC

**Comment by Jubisloviu** [comment]
but i did that, yet the gases ignored the flaps and fucked my shit up

**Comment by uazuaz** [comment]
i think that high temperature is transferred trough walls.
are you sure that the gas composition was the same for both sections? or just the temperature?

**Comment by Zth--** [comment]
needs more testing?

**Comment by Zth--** [comment]
Can confirm, they're not working. We ran some tests and yeah, they're fucked. At least not the buildable ones

**Comment by dunsel-hordon** [comment]
They have been fucked like this for at least a year. I remember making a bug report about it. At least pretty sure i did.

**Comment by Exxion** [comment]
Dunsel, this bug report is almost four years old. Yes, it has been broken for over a year.

**Comment by Eneocho** [comment]
Last I tested I couldn't replicate at all (there was another issue just like this), so I'll close it. Reminder to reopen if the issue reappears.
