### ISSUE TITLE
Newlighting is disorienting and glum

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#14132]
When did we switch to this new lighting system? I think we called it goonlighting?

Either way, everything is dark, glum, and gross, no matter how many high-efficiency lights I put in.

If there are no conflicts, can we just revert it? The only reason it'd look 'great' is if you like everything dark and muted.

When combined with the good ol' ten minute flashing red lights during evac,  I can't see jack shit.

**Comment by kol1th** [comment]
i'll get the revert PR up pronto.

**Comment by ghost** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHHHA

**Comment by eplgr** [comment]
we need more honk buttons

**Comment by Zth--** [comment]
I don't have enough downvotes

**Comment by TheFriggenSawbones** [comment]
:(

**Comment by Megamaw** [comment]
that was fast.

**Comment by ghost** [comment]
signs of ss13-related autism:
- prefers blocky, unrealistic lighting
- thinks goon-style lighting makes things darker
- wants to revert hours upon hours upon hours of reverse engineering, coding, and optimizing for his (unpopular) personal opinion
- while not even having contributed the slightest thing
- quite obviously needs to see an eye doctor

**Comment by Exxion** [comment]
>If there are no conflicts

I can't even begin to describe how far there are from no conflicts

**Comment by TheFriggenSawbones** [comment]
megamaw, your eyes are not ok

**Comment by Megamaw** [comment]
yeah.

i know.

**Comment by Exxion** [comment]
I want to at least pretend to be neutral, so I didn't add [Honk]
But the chances of it getting reverted are essentially zero

**Comment by ghost** [comment]
no, the chances of it getting reverted are *literally* zero
![honk](https://cloud.githubusercontent.com/assets/10257081/23147573/e483f226-f7ad-11e6-8adb-13b697071664.jpg)

**Comment by Probe1** [comment]
>If there are no conflicts, can we just revert it?

![1487571289207](https://cloud.githubusercontent.com/assets/8550416/23147723/1f358690-f7af-11e6-89cd-cd1c8660f29f.jpg)


Also no.  I mean have your discussion but no is the decision.  We're not ripping out a major module of the game that we have spent untold hours getting to work because you don't like an aspect of it that can be modified.

**Comment by Shadowmech88** [comment]
>new version of incredibly crucial system added months ago
>repeatedly optimized, fixed, or otherwise edited in the time since
>I wonder if reverting that initial PR would cause conflicts

It frightens me that I can't tell whether this issue was made ironically or not.

**Comment by Intigracy** [comment]
the obvious answer is to remove skeletons
