### ISSUE TITLE
Blood Donation Bot accepts blood from no blood races

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14139]
Because for some reason someone thought it would be fine to let no blood races have vessels full of blood. No really.

I'll fix this later if someone doesn't beat me to it. OLD CODE!

**Comment by Kitfox88** [comment]
do they not bleed like you or i
are they no less human
despite being skeletons i guess

**Comment by MadmanMartian** [comment]
This was fixed by #14244 apparently

**Comment by Kurfursten** [comment]
You are correct this is safe to close
