### ISSUE TITLE
ZAS issue on boxstation

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#14141]
#### Description of issue
few rounds ago, a rod destroyed a door and some walls between HOP office and AI upload opening a breach on space; about 30 minutes passed and the pressure didn't change at all.
(___NOTE:___ i made a test destroying that same wall with thermite on the test server and the pressure dropped as intended)
![1](https://cloud.githubusercontent.com/assets/6170726/23172564/71840c9e-f856-11e6-8a72-3c296c428048.jpg)

#### Difference between expected and actual behavior
expected the air to be sucked in space; 
didn't happen

#### Server revision

70406da520eea6d365ed3740322ff484df9ec7c2 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
it isn't limited to box or that particular tile.  It's an issue with Zas updating.  It happens infrequently all over the place.

**Comment by uazuaz** [comment]
is it an already known issue then?
feel free to close this issue if so.

**Comment by Zth--** [comment]
I would say it happens every two shifts

**Comment by Killette2** [comment]
Tune down ZAS off the default of extreme and this should fix it

**Comment by Probe1** [comment]
It's a known issue but I don't know where or if there's a duplicate.

@Killette2 happens on all ZAS settings nice try.
