### ISSUE TITLE
Some Z2 dungeon fuckery and holodecks

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#14144]
So there's that wine cellar vault that makes a dungeon on Z2 right

![image](https://cloud.githubusercontent.com/assets/19365096/23195278/6c26d842-f880-11e6-810e-fdf18f91fbaf.png)

What happened here is that the holodeck and dungeons spawned in the same place, so we have this really weird overlap.

Now, these smaller holodeck simulations I don't think pop up anywhere anymore so I didn't see it fuck up the station's holodeck. But that's something to keep in mind.

**Comment by unid15** [comment]
What map was it?

**Comment by JustSumBody** [comment]
This was on box station

**Comment by Aurx** [comment]
Why in the world are we spawning vaults on z2?

**Comment by Exxion** [comment]
#11282 @Aurx

**Comment by unid15** [comment]
Couldn't reproduce. Is it still happening?

**Comment by Kammerjunk** [comment]
Sure is.

**Comment by unid15** [comment]
Fixed I believe

**Comment by Exxion** [comment]
Ask to reopen if not, I guess
