### ISSUE TITLE
Suicide syndrome glitch

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#14149]
1. Get suicide syndrome
2. suicide, and maybe die
3. suicide... again? I have noticed people suiciding even after death
4. holy shit the corpse suicided 4 times why won't you stay down

Noticed this during my ling round. People I diseased were commiting suicide AGAIN even when already dead or in crit from a previous suicide. Sometimes, the repeated suicides were actually healing the victim, albeit not to a safe level, because of the health it was setting them at.

**Comment by stewartspicer** [comment]
Just opened a pull request for something that should fix this, probably. I couldn't reproduce it even before trying to fix it, but this should prevent it from happening 
https://github.com/d3athrow/vgstation13/pull/14152

**Comment by eplgr** [comment]
It's a syndrome, yes, it's what supposed to happen.

**Comment by Exxion** [comment]
...You're SUPPOSED to commit suicide while already dead?
Somehow I don't believe that

**Comment by eplgr** [comment]
Yeah I may have understood it incorrectly. I thought people were referring to suicide after being healed or something, not while already dead.
