### ISSUE TITLE
Major Spessmart Design Flaw

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14159]
Due to the proximity of the WelcomeBot(? may have been a rulebot) to the front door, it will be sucked out by the airflow when entering or exiting. If you try to return to spacemart with the provided disk, this causes the bot to gib and lock down the store.

@Shadowmech88

**Comment by Exxion** [comment]
Make an object that looks like one of those things that tells a Roomba where a room ends and make it impassable to storebots

**Comment by Kitfox88** [comment]
Wasn't this already a problem once before with the Spessmart? It'd probably be best to just add a force airlock sort of thing like Virology has or whatever.

**Comment by Shadowmech88** [comment]
You're talking about the bots just inside either door?
They're completely enclosed by reinforced windows on all sides, aren't they? How are they getting sucked out into space?

**Comment by Kurfursten** [comment]
It was the RulesBot after all, I looked it up
![untitled](https://cloud.githubusercontent.com/assets/9782036/23270584/de10ae26-f9b9-11e6-994f-e63ba9d483d9.png)

Yes, that's the thing about Hellish ZAS. Now I know what you're thinking
>How did he get through both doors?

He got sucked into the antechamber when I entered, and sucked into space as I left

**Comment by Kitfox88** [comment]
hellish zas is fucking stupid as hell

**Comment by Exxion** [comment]
Yeah, it's too weak
