### ISSUE TITLE
Can't examine blood on a tile anymore

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#14165]
#### Description of issue
Blood on tiles used to be able to be examined, It didn't have much use beyond flavour on its own, but in cult rounds ghosts can write in blood to spook the living. Not being able to examine means that you can't read what's written.

#### Difference between expected and actual behavior
Expected to be able to select blood or blood writing on a tile when right clicking, can't

#### Steps to reproduce 
try to read the blood writing outside the zombie room in deff maints, or right click on any tile with blood.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Sprok0** [comment]
Now you need to alt-click the tile with blood on it and examine from that menu
