### ISSUE TITLE
Mech sprites wont update properly

### ISSUE THREAD

**Issue by BitterVanilla** [d3athrow/vgstation13#14163]
#### Description of issue

After finishing the final step of constructing any exosuit (the final weld of the exterior plating) the exosuit shows up in it's closed 'piloted' form. Entering the mech and ejecting again seems to fix this. Otherwise, mechs seem to be fine changing sprites from piloted/empty/broken, as well as adding modules with visual additions such as the repair droid.

#### Difference between expected and actual behavior

**Expected**

  -    Newly constructed mechs appear in their unpiloted, empty state.

**Actual**

- Exosuits appear to have pilots in them before anyone's had a chance to get in.

#### Steps to reproduce 
- Follow http://ss13.moe/wiki/index.php/Guide_to_Robotics#Mechs up to step 18/24
- Constuction finishes and the mech doesn't look quite right
- Climb into mech and eject/destroy mech/attach repair droid to test/"fix"

#### Length of time in which bug has been known to occur
When I stopped playing around October, mech construction worked fine. I only started playing two days ago and it happened immediately.
I think this isn't client side, since I've tried BYOND stable and two other beta releases and the problem has stuck with them. If it's just on my end or as intended, then derp.

#### Server revision
cd181e5f9e9d1c84f4d5a37e27079a68f44c0d23

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
Oh yeah, this issue's existed since the invisible mech fix. Around that time the moving HONK sprites were added.

**Comment by Exxion** [comment]
Just put `update_icon()` in `New()`
Unless something weird is going on

**Comment by Exxion** [comment]
Oh look, they don't even fucking use `update_icon()`
Never mind, then

**Comment by Exxion** [comment]
OK, the ACTUAL way to fix it is to move line 90 in `mecha.dm` to after line 106
I don't have Git set up on this computer yet so someone else can do it
