### ISSUE TITLE
Xray gun causes turf sprite corruption for entire z-levels when fired

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#14160]
#### Description of issue
When an xray gun is shot it leaves a burn mark through every turf the laser hits, over time these burn marks (or more commonly, every turf that DOESN'T have a burn mark) has it's sprite fucked.

Sprites occasionally change what they are, so it can go from black, to a potion, to a wraith, and rather entertainingly a plasma hotspot.

#### Difference between expected and actual behavior
**Expected**
* Warning shot valids secure with bullet holes throughout the station

**Actual**
* Entire z-level is visibly fucked

#### Steps to reproduce 
The issue itself takes time to manifest but the following worked for quickly getting it to happen.

* Get 2 xray guns and shoot up the main station
* Move to the asteroid and shoot up there
* Return to station
* Station turfs are missing sprites

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

Since the X-ray gun got added.

#### Server revision

-

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by BobdaBiscuit** [comment]
![IT BEGINS](http://i.imgur.com/3IDhB0c.png)

**Comment by Ephx1** [comment]
Fucking _AMAZING_

**Comment by kilozombie** [comment]
I've noticed space tiles do this on occasion, like all the pieces of space dust will become ethereal goliaths or waffles or emags or something. I don't know if it's related at all but BYOND is simply wonderful

**Comment by Exxion** [comment]
It's a known BYOND bug
It's clientside; relogging will temporarily fix it

However, the x-ray laser causing it to happen more frequently is interesting. Maybe we can finally track down the cause!
