### ISSUE TITLE
Sticky White Stuff

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#14166]
#### Description of issue
When you extend a telescopic baton, it gets an irremovable white blood overlay on it for the rest of the round. 

#### Difference between expected and actual behavior
Expected the baton to be clean until the chain of command needs a link removed.
Actually have to put up with the horror of an unclean baton.

#### Steps to reproduce 
Extend a telebaton.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by TheFriggenSawbones** [comment]
Theres no problem with the baton doing added magic damage.

**Comment by ghost** [comment]
I always thought those were scratches, but there should be a better sprite for it than what there is right now.

**Comment by ghost** [comment]
I found the bit in code that fucks it up.

```/obj/item/weapon/melee/telebaton/generate_blood_overlay()
	if(blood_overlays["[type][icon_state]"]) //Unless someone makes a wicked typepath this will never cause a problem
		return
	var/icon/I = new /icon(icon, icon_state)
	I.Blend(new /icon('icons/effects/blood.dmi', rgb(255,255,255)),ICON_ADD) //fills the icon_state with white (except where it's transparent)
	I.Blend(new /icon('icons/effects/blood.dmi', "itemblood"),ICON_MULTIPLY) //adds blood and the remaining white areas become transparant
	blood_overlays["[type][icon_state]"] = image(I)
```

**Comment by DamonFriedberg** [comment]
```/obj/item/weapon/melee/telebaton/generate_blood_overlay()
	if(blood_overlays["[type][icon_state]"]) //Unless someone makes a wicked typepath this will never cause a problem
		return
	var/icon/I = new /icon(icon, icon_state)
	I.Blend(new /icon('icons/effects/blood.dmi', rgb(255,255,255)),ICON_ADD) //fills the icon_state with white (except where it's transparent)
	I.Blend(new /icon('icons/effects/blood.dmi', "itemblood"),ICON_MULTIPLY) //adds blood and the remaining white areas become transparant
	blood_overlays["[type][icon_state]"] = image(I)a```

**Comment by Exxion** [comment]
That's not exactly the relevant part, but the relevant part is like two lines above, so kudos

**Comment by robintime** [comment]
this has been fixed

**Comment by robintime** [comment]
this was not fixed i was deceived

![help](https://user-images.githubusercontent.com/81062934/114282137-1f498c00-9a10-11eb-813b-93e04d5bb42b.png)
