### ISSUE TITLE
Humans are showing as dionas on examine

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#14173]
![](https://puu.sh/uhCQd/e796916fcf.png)

Why is this important? I just had a case where a borg killed a wizard because he acted upon that information. This also creates confusion and it makes adminning harder.

**Comment by Ephx1** [comment]
Examine icons for humanoid mobs has been fucked for a long while now, not just humans.

**Comment by Probe1** [comment]
Been this way since goonchat was merged.

**Comment by kol1th** [comment]
something something getflaticon

**Comment by Exxion** [comment]
This is also a duplicate of several other issues
Literally every human mob shows up as the first one to be examined in a given round because the bicon cache is fucking stupid

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/issues/9384

**Comment by Intigracy** [comment]
be nice if this would be fixed
