### ISSUE TITLE
Ghetto Space Helmet does not have a icon

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14179]
#### Description of issue
The Ghetto Space Helmet has no icon, as it is set to hardhat0_ghetto while there is no hardhat0_ghetto in the head.dmi file. There is only the old icon there, rig0-ghetto and rig1-ghetto. This could probably be fixed easily by setting the icons of the ghetto helmet in /clothing/spacesuits/miscellaneous.dm to rig0-ghetto, and to rig1-ghetto for the version with it's lights on.

**Comment by Probe1** [comment]
@SonixApache

**Comment by ghost** [comment]
I told him on discord, he will probably fix it tommorow because something went wrong with github


I really wonder who would merge things like this without making sure everything is right

**Comment by SonixApache** [comment]
IT WORKED ON THE LAST COMMIT, I DON'T REMEMBER ANYTHING
fix'll be up tomorrow
