### ISSUE TITLE
Vox Trader Ship Admin Issue (Admin Destinations)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14172]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
If you happen to move the trader ship with admin commands you can't actualy send it to its proper auxilary dock on the station, only to the dock that the pirate shuttle uses.

**Comment by MasterofNothing** [comment]
Works for me, or am I missing something?
![1](https://cloud.githubusercontent.com/assets/6288730/23335232/106bd33e-fbb1-11e6-874d-bb7c4621f751.png)
![2](https://cloud.githubusercontent.com/assets/6288730/23335233/1233b420-fbb1-11e6-8b7d-31f115b49a2a.png)

**Comment by Shadowmech88** [comment]
@MasterofNothing I believe that docking port is the salvage shuttle docking port, not the vox trader shuttle's usual port.

**Comment by MasterofNothing** [comment]
@Shadowmech88 

The one I sent it to is called 'station auxillary docking'. If you select NanoTrasen Station, you end up at the port a few tiles to the east.

Where do you want the shuttle to go then, @Probe1?

**Comment by Exxion** [comment]
The correct one is the eastern one, but if you can send it there, it works
Confusing name in the admin window, but oh well, it makes sense to the traders
