### ISSUE TITLE
Vampire's hypnotize menu

### ISSUE THREAD

**Issue by eplgr** [d3athrow/vgstation13#14176]
It should work like https://github.com/d3athrow/vgstation13/pull/13855
I read the code and it does not work like changeling powers, so I am not sure how to do it myself.

Reasons: vampires already struggle a lot. That extra step gives you away quite easily, this should help. Also, it's annoying and it doesn't make sense.
It's a start.

**Comment by gbasood** [comment]
From what I remember of playing vamp a long time ago, their disables felt all over the place, too.
But I can't remember a whole lot from that round aside from picking up seizures from someone I succ'd.

I just realized that was off topic but I'm gonna leave my complaint here.

**Comment by eplgr** [comment]
Also this should probably be applied to all spells/powers (such as disease touch).

It's really a QoL change, to try to turn down their power level (vampires or any other antag) with a fukken window popping out so it takes you longer to do it sounds... bad.
