### ISSUE TITLE
Hardhat worn sprites don't show light

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14183]
#### Description of issue

Light on or off, when worn on your head it'll always appear off to other people.

#### Server revision

e4bbc110ca4a11370b529c4e30d8bccd1b4bdfff

**Comment by SonixApache** [comment]
![](https://puu.sh/uiPww/4a44ab92c0.png)
MAYBE. MAYBE NOT? I DON'T KNOW. CLOSING THIS.

**Comment by Riekland** [comment]
I _think_ that the on mob and item sprite only updates when you turn the light on or off via clicking it inhand, as opposed to using the icon at the top left of the screen which is utter wank and never works right

**Comment by SonixApache** [comment]
SEEMS TO STILL BE AN ISSUE

**Comment by PJB3005** [comment]
@Riekland is correct here.

**Comment by Eneocho** [comment]
can't reproduce on testing
