### ISSUE TITLE
Blunderbuss force calculation is needlessly complex

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14192]
`var/fire_force = fuel_level + (fuel_level * (1/(fuel_level/10)))`

>y = x + (x * (1/(x/10)))
>y = x + x * (10 / x)
>y = x + 10

I read @Shadowmech88 's original description and I couldn't determine if he intended something else here, but unless I'm going crazy, there's no reason to have a complex formula that always simplifies to fuel_level + 10.

**Comment by Shadowmech88** [comment]
I feel like I must have had a reason at the time, but I can't for the life of me remember what it was.
