### ISSUE TITLE
Metaclub's detectives start with thermals

### ISSUE THREAD

**Issue by eplgr** [d3athrow/vgstation13#14198]
Other maps that are not box starting with cool stuff does not mean they should start with broken and completely OP stuff.

Detective's office (I guess?) starts with thermals. I just played a round as a mechanic where I was asked to masscopy them and give them to all officers.
And it was not the first time this happened. I didn't understand before how they got them, but now I do.

They are supposed to be an antag item, they are extremely good and expensive. Meanwhile, the detectives get it for FREE. Even though it spawns at their office, the HOS and many officers will rush to get (and probably masscopy) them.

I don't think they should have this. It's too much. It's too good.

**Comment by kernikov** [comment]
Make them uncopy-able with a non-traitor device scanner.
Wow, fixed.

**Comment by Lokiamis** [comment]
Nah, thermals are way too good in the first place.

**Comment by beesil** [comment]
Closed by #14416

**Comment by ShiftyRail** [comment]
Very interesting to read in light of the buddy bag change
