### ISSUE TITLE
Revolvers eject casings automatically

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14204]
that's not how revolvers work

fe929e5849c62fba901269b160850d65a0da151f

**Comment by mrpain666** [comment]
How is this a feature request?

**Comment by Shadowmech88** [comment]
Because the person who made the issue is implicitly requesting that revolvers be made to *not* eject casings automatically.

**Comment by Exxion** [comment]
God I hate how the projectile weapon types are structured
