### ISSUE TITLE
Action button issues

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#14201]
I'm going out of town the next few days so I won't be able to get to this anytime soon

null runtime on Login()

null.moved runtime for seemingly unknown reasons(I can't reproduce it locally)

Cyborg jetpacks don't work due to silicon lack of action buttons and the verbs are gone now(Guess a fix would be to give the verbs back just to the borg version for now?)

**Comment by ghost** [comment]
_Give me back my jetpack._

**Comment by PJB3005** [comment]
Material scanners don't have action buttons anymore.
