### ISSUE TITLE
Genetic abilities spell button resulting in script error

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14206]
#### Description of issue
when i hover over genetic abilities,or any icon like this(spells,for example) i get an error:
script error
line 182
symbol 5
error: no $
code:0
URL: http://127.0.0.1:62028/7ace4622.htm

#### Difference between expected and actual behavior
I cant activate some abilities.

#### Steps to reproduce 
have IE 8,have cryokenesis,hover over it,get an error.

#### Length of time in which bug has been known to occur
20:02 26.02.17

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

Os win7
Byond 511

**Comment by PJB3005** [comment]
@JustSumBody aaaaaah 

Probably tooltips though?

**Comment by JustSumBody** [comment]
Most likely, though I'm not sure what could be causing trouble for him specifically
Especially since I don't think anyone's changed it since then

**Comment by DamianX** [comment]
This is a cache issue and there's nothing we can do about it
