### ISSUE TITLE
Summon Cultist requirement

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#14202]
the Free Cultist rune requirement got recently lowered from 3 to 2 invokers to work, but most of times there is no point on freeing a cultist without also summoning them, so in my opinion the Summon Cultist rune requirement should be lowered to 2 invokers as well.

**Comment by AI-Is-Rogue** [comment]
Didn't #14150 already do that?

**Comment by Blithering** [comment]
Wasn't there a PR that made summon and free cultist into the same rune?

**Comment by uazuaz** [comment]
my bad, i just read the 2017.02.25 changelog and thought that only free cultist and teleport other were affected.
closing this.
