### ISSUE TITLE
Sci Outpost Xenobotany sink

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#14205]
Xenobotany could do with a sink on the outpost, 
emptying the water tank and having to use the chem dispenser is pretty lame.

**Comment by Kurfursten** [comment]
It's in the bathroom, use a wrench

>Emptying the tank with 8 trays

but how

**Comment by kernikov** [comment]
> but how

The thirst is real.

**Comment by Kurfursten** [comment]
I always knew that outpost was full of thirsty bitches

**Comment by Killette2** [comment]
what about the chem dispenser?
also tbh I almost never touch water, real botanist don't need it
