### ISSUE TITLE
Antag Codewords are commented out (I think)

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#14209]
I haven't ever seen antag code phrases on this server, while fucking around with code I found names.dm, which has the only reference of codeword generation on the codebase, and it's commented out.

**Comment by Exxion** [comment]
I've definitely seen them, but I've had antag roles disabled for months, so maybe they broke in that time

**Comment by ghost** [comment]
i've rolled tator twice recently and had no code words

**Comment by SonixApache** [comment]
Haven't had codewords on local test serb or live serb antag rolls in a while.

**Comment by ghost** [comment]
I have not seen them recently either.  I know because I have been waiting to scream them roundstart over the radio for a few weeks now.

**Comment by Chucklemonger** [comment]
Haven't seen codewords in my last 3 tator rolls.
