### ISSUE TITLE
You can hear blob overminds telepathy from the lobby

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14200]
#### Description of issue
![dreamseeker_2017-02-25_23-06-41](https://cloud.githubusercontent.com/assets/8550416/23337068/44b5328a-fbb0-11e6-900f-54e7697608ea.png)

#### Difference between expected and actual behavior

Sanity

No sanity

**Comment by Exxion** [comment]
You can also hear CentComm announcements, as shown in that very screenshot
