### ISSUE TITLE
X-ray lasers have absolutely no problem penetrating the entire station, even R-walls, even though their damage is properly reduced

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#14216]
Yes, that does mean that they deal 0 damage after passing through a few walls. They still continue to pass through everything, though.

I have a feeling `bullet_die()` isn't doing its job.

**Comment by Kitfox88** [comment]
at zero damage i don't think anything's gonna die, yeah

dohohohohoho

**Comment by kilozombie** [comment]
You went 4 whole hours without a laugh emoji so I think your joke must not have been funny

haha
