### ISSUE TITLE
Giving somebody a peg leg gives them a real foot

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#14210]
1. remove leg
2. add peg leg
3. be disturbed

Peg leg appears normally when you choose it at character setup
![untitled](https://cloud.githubusercontent.com/assets/25004372/23344187/4f58f6c4-fc4e-11e6-9991-680704c35a94.png)

968524fd4d7a1b47da35da2c942ca83c549805c6

**Comment by Killette2** [comment]
What happens if you try to cut it off? I'm sure this was always the case as a work around since having no feet is awful

**Comment by Shadowmech88** [comment]
>since having no feet is awful

Usually applying a prosthetic limb applies a prosthetic version of that limb's children as well, meaning giving someone a peg leg should also give them a peg foot, like how giving someone a robot arm also gives them a robot hand on that arm.
