### ISSUE TITLE
Projectiles can escape the CentComm Z-Level

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#14215]
Yeah almost shooting people in the round with x-ray lasers while testing them on CentComm was fun

**Comment by Zth--** [comment]
![](http://i.imgur.com/Y5GlP3E.png)

**Comment by Aurx** [comment]
But if you change this behavior then I can't set up an automated centcomm meteor cannon that sprays all of spess with death.

**Comment by Shadowmech88** [comment]
The X-ray beams likely won't make it out of Centcomm once #14216 is fixed, anyway.
