### ISSUE TITLE
Admin ghost hands

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#14223]
You're supposed to be able to screw with any computer, but that's not the case for every machine. I'll separate this in three categories:

## Interfaces that pop out but buttons don't work
- [ ] Intercoms
- [ ] APCs
- [ ] SMES

## Interfaces that don't even pop out
- [ ] Vending machines (smartfridges work just fine)
- [ ] Telepad
- [ ] Autolathe
- [ ] Exosuit fabricators
- [ ] Accounts database
- [ ] Microwaves
- [ ] Faxes displays a message: "Nope."
- [ ] Merch computer
- [ ] Geneticist computer
- [ ] Crew monitoring computer
- [ ] Communications console

## Buttons that don't work
- [ ] Medbay exit button

### This list will keep growing. Please comment your discoveries so I can add them to this list.

**Comment by Intigracy** [comment]
air alarm
apc
atmos shit (pumps/volume pumps)
bar sign
beepsky/bots
crew monitoring computer
fire alarm
firelocks
foam dispensers
holopads (can't fuck with the AI by requesting it HONK)
intercomms
light switches have the cooldown players do
shuttle computer
shuttle doors
smes
tcomms machines
telesci console
turret control

**Comment by mrpain666** [comment]
The accounts database would be nice to be able to use as an admin. You can send faxes with the send fax verb or whatever it is.

But yeah ideally we would be able to use everything.
