### ISSUE TITLE
Chapel confession doors can be interacted with by ghosts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14224]
(WEB REPORT BY: invoid9 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Ghosts can touch the chapel confession doors, meaning they can open/close the all-access booth and can EH EH the chaplain's booth

>What you expected to happen
To not be able to spook the curtains

>What actually happened
Ghosts interacting with doors

>Steps to reproduce if possible
Just be ghost and click on the chapel confession booths.

**Comment by Probe1** [comment]
Working as intended.

**Comment by Killette2** [comment]
I reported this years ago
To players and admins in deadchat

Ghost could also mess with washing machines but I'm sure that is fixed. They can also try to open the librarian shutter door which is the same as the chapel, but they can't due to no access.

**Comment by Exxion** [comment]
Telling deadchat does not, never has, and never will count as reporting

**Comment by Killette2** [comment]
Whooosh
