### ISSUE TITLE
account database on defficiency

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#14231]
#### Description of issue
the account database on deff is inside the science server room, therefore inaccessible.

#### Difference between expected and actual behavior
as HOP, expected being able to create new bank accounts and reactivate links between ATMs and centcomm when needed when i'm on deff:
got NOPE.

#### Steps to reproduce 
be on deff, search for the account database.

#### Server revision

server is down at the moment.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
There is really no reason for the database to be in a coldroom

**Comment by Killette2** [comment]
How else will you get cold hard cash or be able to freeze someone's account?

Someone was probably just retarded and put it in there because the RnD machines look similar and they are in a coldroom.
