### ISSUE TITLE
Unable to late join as trader

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#14249]
I am not sure if barring traders from late joining was an intentional feature, or one of the limitations of adding playable non crew-members that spawn off of the z level.

Either way, I thought I would start a discussion about it because it would be nice to be able to late join as trader.

**Comment by Probe1** [comment]
Yes, that is the design.  You can only join as a trader or silicon at roundstart.

**Comment by Durgen** [comment]
I just found another discussion about this so i'll close this issue

https://github.com/d3athrow/vgstation13/issues/10605
