### ISSUE TITLE
Wizard's Staff of Necromancy is broken, and funny.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14254]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
0faf08b455f97e63e22af1c9e359bcbaa8ab3c7c 

>General description of the issue
It's very broken
Sometimes you don't get put in your zombie
othertimes you get drafted as a wizard and try to zombify your own body, putting your mind in that zombie and leaving the wizard catatonic.

>What you expected to happen
bug free

>What actually happened
bugs

>Steps to reproduce if possible
Die
Come back as a wizard
Use the Staff of Necromancy on your dead body
ahelp as fast as you can

**Comment by Killette2** [comment]
I mean it makes sense in a weird roundabout way spiritually

**Comment by SonixApache** [comment]
special.dm#L181
It creates a zombie with the mind that's assigned to the target mob. Why multiple mobs can share a mind is beyond me.
