### ISSUE TITLE
Vox Raiders needs to roll more objectives

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14252]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
http://i.imgur.com/APhsTje.png

14
minute
rounds

also they always fail number 3 its weird, it checks for any deaths right

this gamemode fucking SUCKS

**Comment by TheFriggenSawbones** [comment]
ITS TERRIBLE

and just a heads up, it always does that. They either break into the armory to get some guys or go mining for 10 minutes.

No kidnapping objectives, no cool objectives, nothing fun, just a terrible hellscape filled with squawks and wasted antag rolls.

**Comment by Lokiamis** [comment]
Yeah that was pretty stupid

**Comment by Anglosphere** [comment]
This is a good round type. There is nothing wrong with it. If you humans were not so incredibly stupid, the rounds would last much longer. Our superior bird brains dominant when given the task of antagonizing the station. Go whine in the thread about it.

**Comment by ghost** [comment]
IT SUCKS SO MUCH

**Comment by kilozombie** [comment]
BAAAAAAAAAAAAAAAAAAAAAWK
BAWK BAWK BAWK BAWK BAWK
WE EARNED MUCH COIN
CLOSE ISSUE ING IMMEDIATELY

**Comment by SonixApache** [comment]
the obvious answer is to remove vox

the more obvious answer is to remove heist as a gamemode, and add it backi n later as a random or bus event

**Comment by Aurx** [comment]
>also they always fail number 3 its weird, it checks for any deaths right

Yeah, anytime a /mob/living/carbon/human's death() is called it increments the "vox murdered somebody" counter.  If it's over 5 at round end, inviolate broken redtext for everybody.

**Comment by Probe1** [comment]
I vaguely remember someone having a solution to this @Exxion 

😐

**Comment by Exxion** [comment]
Removing the only good part of a mode is in no way a solution

**Comment by jakmak** [comment]
Remove round end on birbs going home and run auto traitor in the backround

**Comment by Durgen** [comment]
raiders should be removed as a game mode and turned into a button
would be a good way to shut dead chat up when it's whining for an ERT/squid

**Comment by gbasood** [comment]
duplicate of #12112
