### ISSUE TITLE
Discord > Server connection issues

### ISSUE THREAD

**Issue by StarSmasher44** [d3athrow/vgstation13#14256]
Not really an issue just more of a question, I've been trying to set up the discord to communicate with the server since it seemed to be implemented. But I've stumbled upon some issues;
1. It is asking for a url, what url is this precisely? I figured I'd have to make use of the webhook function. But that doesn't seem to work. Which brings me to point 2;
2. What would I have to enter on DISCORD_PASSWORD? Since the webhook only supplies a link and not a password requirement of a way to fill it in at all.

Thanks guys, hope I'm not being too much of a bother by using the issues system like this.

**Comment by PJB3005** [comment]
The URL points to a flask thing I'm running on the box of MoMMI.

https://gist.github.com/PJB3005/3b028aa81e65adc3cf562d5146e69e82
