### ISSUE TITLE
Items disappearing when put in bags but having their sprites stay on screen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14269]
(WEB REPORT BY: aerlx87 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
c2d1b3eae8e1ff73f774f3d9ccf37bfb38c3ba1f 

>General description of the issue
Sometimes when you put an item in a bag, you will no longer be able to interact with the item. Its sprite will still be on the screen in the location it would have been inside the bag, but you won't be able to take it out, and you can still put other things in that spot. I've had this happen with both hand teles and id's across multiple rounds.

>What you expected to happen
They would be put in my bag.

>What actually happened
They disappeared from existence and left their sprite imposed on the screen.

>Steps to reproduce if possible
It's only happened randomly.

**Comment by Killette2** [comment]
This issue is ass, especially when handcuffs are involved. Sometimes you can even consistently see the item, like if it's a gun how many shots left it has.

**Comment by despotate** [comment]
Seen it happen multiple times with thrown bolas that were picked up, but never anytime else.

**Comment by jknpj** [comment]
update_icon is still fucked and i have no clue why.

**Comment by Probe1** [comment]
The hand teleporter is notoriously fucky with this.

**Comment by Exxion** [comment]
I've never personally seen this issue, but I have seen a related one VERY often (nearly every round, if not every round) (especially with boxes). An item inside a backpack shows up on your screen despite the backpack not being open. You can interact with it just fine, remove it from the bag, whatever. It just shows up when it shouldn't.

As for this bug, I have absolutely no idea how it happens, but please ahelp if you see it again and ask the admin to VV the bag's `contents` list
