### ISSUE TITLE
Paramedics don't spawn with a backpack if you have the messenger bag preference.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14260]
(WEB REPORT BY: kernikov REMOTE: 172.93.109.202:7777)
>Revision 0faf08b455f97e63e22af1c9e359bcbaa8ab3c7c

>What you expected to happen
A messenger bag.

>What actually happened
No backpack.

>Steps to reproduce if possible
Spawn as a paramedic on Box with a messenger bag as preference.

**Comment by jknpj** [comment]
<s>how in the fuck</s> FUCK
