### ISSUE TITLE
None of the animals in the Holodeck Zoo are holograms

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14265]
I could look past the milking holocows
I could look past the farming eggs from holochickens
But corgi meat is literally an antag objective

**Comment by kol1th** [comment]
>objectives

**Comment by Kitfox88** [comment]
what's wrong with a good hard hololife on the holofarm with your hololivestock

**Comment by ghost** [comment]
Idea - Make a subtype of simple animal that is just /holo

Then have subtypes that are the cow, corgi, chicken, etc.

**Comment by Shadowmech88** [comment]
Then make subtypes of cow meat, corgi meat, and chicken eggs that are /holo, with 50% alpha and no nutriment.
Then make holorecipes.

**Comment by Kurfursten** [comment]
Since holoitems disappear when they leave the holodeck, holorecipes seem unnecessary

**Comment by Blithering** [comment]
Could have them blue and fuzzy like the holocarp are.
![holocorgi](https://cloud.githubusercontent.com/assets/15067109/23584705/42a820cc-0161-11e7-87de-a05b05712f35.png)

**Comment by Killette2** [comment]
What if eating enough holofood makes you a hologram?

**Comment by Probe1** [comment]
Holomeats
Holorecipes

Just flag them as no butcher jhchrist

**Comment by ghost** [comment]
Microchips, Blue eggs and spammail

**Comment by Megamaw** [comment]
maybe they should have some sort of value outside the holodeck

simply because we need holographic meatloaf

**Comment by Yelier** [comment]
I like the holomeat idea. When you eat it, it would give zero nutriment or anything and then give you a snarky message about how tasty and filling it was.

**Comment by Killette2** [comment]
When you use a fork on holographic food, it gives you text about how the fork just goes through the food picking up nothing.
