### ISSUE TITLE
gold atmos suit malfunctioning light

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14273]
(WEB REPORT BY: nziswat REMOTE: 172.93.109.202:7777)
>Revision c2d1b3eae8e1ff73f774f3d9ccf37bfb38c3ba1f 
>General description of the issue
upon converting an atmos suit to the golden version, the helmet's light no longer seems to work.

>What you expected to happen
the helmet to light up

>What actually happened
nothing

>Steps to reproduce if possible
atmos suit
use golden conversion kit on atmos suit
put on gear
nothing happens upon activation

**Comment by ghost** [comment]
It's a feature

**Comment by jknpj** [comment]
Not a bug
