### ISSUE TITLE
deff's and meta's mechanic workshops

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#14270]
#### Description of issue
on defficiency and metaclub, inside the mechanic workshop, the windoors that are on the desk and general fabricator tiles don't require any access; this means that anyone can open them, unwrench the general fabricator (or use a hookshot, or disassemble the desk), enter the workshop, steal/do whatever they want, exit, wrench back the fabricator (or re-assemble the desk) without leaving any trace.
on boxstation these windoors have workshop access requirement, the same should be applied on deff and meta.

#### Difference between expected and actual behavior
expected that anyone breaking inside the workshop leaved some trace, like a broken windoor;
got free access for all.

#### Steps to reproduce 
try to open the workshop's windoors without using any ID

#### Length of time in which bug has been known to occur

maybe forever

#### Server revision

c2d1b3eae8e1ff73f774f3d9ccf37bfb38c3ba1f 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by mtpowell** [comment]
This is the last time I post my secrets in the thread

**Comment by Probe1** [comment]
I mean it's not exactly a secret.  I was just too lazy to fix it or make an issue

**Comment by ComicIronic** [comment]
Closed by #14337
