### ISSUE TITLE
Captain's armor cannot be decontaminated

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14274]
(WEB REPORT BY: kernikov REMOTE: 172.93.109.202:7777)
>Revision c2d1b3eae8e1ff73f774f3d9ccf37bfb38c3ba1f 
Captain's armor does not have plasmaguard apparently.
When 'blasma-ed' you cannot clean it in a washing machine because it does not fit.
It also does not fit in a suit storage unit.

>Steps to reproduce if possible
Try to clean blasmad captain's armor.

**Comment by Probe1** [comment]
Verified.

**Comment by Shadowmech88** [comment]
Most likely due to the captain's armor being some kind of snowflake armor plating with space protection, rather than a hardsuit with high armor values.

Is there any reason the captain's armor shouldn't just be a child of space suits?

**Comment by Probe1** [comment]
Not that I'm aware of.

**Comment by AutismSpider** [comment]
caps armor is snowflake riot armor(with better stats) with space protection same with the helm

**Comment by Blithering** [comment]
Does bleach decontaminate it?

**Comment by kernikov** [comment]
I didn't think of that and wasn't in a position to test bleach.

**Comment by ShiftyRail** [comment]
Dupe (#22294)
