### ISSUE TITLE
EVA and Tcomms access, deff

### ISSUE THREAD

**Issue by eplgr** [d3athrow/vgstation13#14289]
- Ask HoP to give you EVA access:
  - go to EVA
  - see the door does not open

- Be Mechanic:
  - go to tcomms
  - computer is behind *another* door
  - see the door does not open

**Comment by Kurfursten** [comment]
EVA access is borked on all maps IIRC, why don't you go ahead and test this on Meta and Box for us too?

**Comment by PJB3005** [comment]
It works fine on box AFAIK.
