### ISSUE TITLE
Butchering as a Grue rework

### ISSUE THREAD

**Issue by eplgr** [d3athrow/vgstation13#14282]
I think the mechanic is too counter-intuitive. I had the same problem #13094 had, but even after reading that issue, I couldn't figure out how to make the verb appear.
I am not sure I tested it on help intent, but I am sure it didn't appear on harm intent.

Either way, there is no way to figure out you can actually butcher people unless you come to the github and search for grues. And even then, you wouldn't know how it works, because it's only stated in an issue.

**Comment by Shadowmech88** [comment]
It works exactly the same way that it works for other species who possess claws, such as tajarans.
Also in a broad sense, the same way that it works for vox, though I imagine the necessary conditions would be different.

In any case, if there is an issue, it's not specific to grues.

**Comment by Exxion** [comment]
1. Right click dead thing
2. Oh look, a butcher verb

I'm pretty sure that verb is always there, even when you can't use it (which, to be fair, is confusing)

**Comment by eplgr** [comment]
@Exxion It's not there, at least not *always*.

**Comment by Shadowmech88** [comment]
Were you wearing gloves/something that covered your hands?
Beak butchering doesn't work while wearing a mask, so maybe claw butchering doesn't work when your hands are covered.

**Comment by eplgr** [comment]
I was naked.
