### ISSUE TITLE
HE Pipes infinitely layerable

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#14298]
![dreamseeker_2017-03-08_19-21-38](https://cloud.githubusercontent.com/assets/110073/23773356/b9e12538-04d3-11e7-8b8c-b39ee105bfdb.png)

I can't pinpoint where this is happening, but the `/obj/item/pipe/onattack()` shit seems to be one likely culprit.  

/cc @ComicIronic since he's the layering guru

**Comment by Probe1** [comment]
I've been meaning to point this out on github but passive cooling through H/E pipes is also absurdly effective.  Like what would take dozens of direct cooling pipes only takes 5 indirect.

I'm not sure the code is working right it's so effective.

**Comment by N3X15** [comment]
Yeah, that needs fixed, too.

#14299
