### ISSUE TITLE
getting cloned changes your underwear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14290]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

c718968c60c97fa4950105f94be42e4cab4eb53a

**Comment by Probe1** [comment]
When are we going to stop this disgusting power creep.  How does a cloner make underwear?  Biomass? Unlikely.  I will get right on adding a cloth requirement for cloning.

**Comment by Shadowmech88** [comment]
Given what happens to your underwear when you die, I think it's nice for the cloner to give you a fresh pair.

**Comment by Kitfox88** [comment]
someone add rainbow undies as a 1/100 chance each clone

**Comment by Riekland** [comment]
I'd like to add that it also changes your hair colour sometimes, I think it's only if you have a hair colour that's not from the normal grid and is instead a custom value
I think
Also I don't think that the hair should be changed just adding that it might be part of the same problem

**Comment by SkowronX** [comment]
Someone better make a "Choose undies" option for the clone pod. I would set that thing to Mankini every time.

**Comment by Chucklemonger** [comment]
@Riekland I believe that's the case; my static's hair changes to a much paler color (but always the same color) about every one in three times I get cloned.

**Comment by Exxion** [comment]
The hair color one is known
It was reported fucking eons ago and nobody's fixed it yet

**Comment by DamianX** [comment]
Sonix eventually fixed this
