### ISSUE TITLE
HE Pipes are OP as fuck

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#14299]
The two little HE pipe stubs sticking out of the default box SME into space are apparently more than enough to cool an oxygen-medium SME with three active emitters.

**Comment by Probe1** [comment]
If anyone looks at this make sure you carefully test telecomms after making any changes.

**Comment by jknpj** [comment]
It's easy, just make map a burning chamber inside tcomms piped directly to both o2 and plasma miner and the machines will never break.

**Comment by Probe1** [comment]
Or we just set the tiles temperature to OVER the overheat value so the check to see if they're overheating never runs!  Thanks oldcoders!

(@pjb3005 might have fixed this but  I'm still amazed at how awful that check was.)

**Comment by Kurfursten** [comment]
Yeah, passive cooling has definitely become the norm among engineers now

**Comment by Exxion** [comment]
From a realism standpoint, HE pipes should barely work in space. They're designed to *conduct* heat really well, not radiate it. That's what the radiators are for.

But also who gives a shit

**Comment by Probe1** [comment]
I don't want to be argumentative but engineering autists do love realism.

It'd return the vestigial radiator pipes to infrequent use instead of being something you never ever make ever.

**Comment by PJB3005** [comment]
There's an issue about the cause of this. They exchange heat with gas on the entire pipeline instead of in their pipe specifically.

@Probe1 I handed the code to Damian so he still has to make a PR.

**Comment by ghost** [comment]
Kurfurst, it's also a good idea to at least install redundant passive cooling unless you're intentionally making a fuckhuge amount of cold gas inside anyway. Woe is the shitgineering that explodes during a long blackout event because the vents and scrubbers aren't running and the specific heat of the chamber isn't big enough to ride it out.

**Comment by ihadtoregisterforthis** [comment]
Fix'd

**Comment by Probe1** [comment]
They're still pretty OP the PR was for outright bugs with them that made them even MORE OP.
