### ISSUE TITLE
Compilation issues.

### ISSUE THREAD

**Issue by flawd95** [d3athrow/vgstation13#14296]
#### Description of issue
Source won't compile.

#### Steps to reproduce 
Attempt to compile source

#### Specific information for locating

This is the error:
code\__HELPERS\_macros.dm:224:error: missing ')' in macro definition

This is the line it points too:  
#define LIBVG(function, arguments...) call("./libvg.[world.system_type == "UNIX" ? "so" : "dll"]", function)(arguments)

Perhaps it has something to do with all the quotes, but I don't know enough about byond coding to figure it out.

#### Length of time in which bug has been known to occur

Don't know.

#### Server revision

Can't load so..

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
Variadic macros require byond>511. You can't compile anymore on 510.

**Comment by flawd95** [comment]
OMG I'm so sorry..  Please forgive buggin you guys about something so stupid. :(

**Comment by Probe1** [comment]
You're cool dude this is why we have a github.
