### ISSUE TITLE
Mesons make you immune to shard radiation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14297]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When a human has meson scanners equipped he doesn't get radiation damage from an active shard. No radiation suit required.

>What you expected to happen
Radiation buildup and quick death with occasional stuns.

>What actually happened
Watched a shard for 2 hours in just a jumpsuit and mesons.

>Steps to reproduce if possible
- Equip meson
- Activate shard with whatever amount of emitters
- Die of boredom

**Comment by jknpj** [comment]
Get near it without a radsuit, i dare you, i double dare you. Watching from outside the chamber does nothing because the radiation range is tiny.

**Comment by DamianX** [comment]
Radiation range is determined by the shard's power, with a typical setup (and probably advanced ones too) the range doesn't expand to outside the chamber.

**Comment by Exxion** [comment]
[Discussion] because he may want to change the radiation range, then

**Comment by Killette2** [comment]
Make the SME deadly again!

**Comment by ReindH** [comment]
Wait, so by that logic I shouldn't get rad damage even without mesons?
But I checked and I DO get toxic buildup without them.
One round I was doing the saucy shard pulling and every time I threw stuff into the shard people from 4-5 tiles dropped like bricks.

**Comment by Exxion** [comment]
Throwing objects into the shard specifically creates a fuckton of radiation

**Comment by ReindH** [comment]
I learn something every day I suppose.

**Comment by jknpj** [comment]
![comfygineering](https://cloud.githubusercontent.com/assets/17928298/23772307/40b1ad38-04f9-11e7-8e4c-810b79059810.png)

>There re people in this issue RIGHT NOW trying to kill comfy SME autismforts

**Comment by Probe1** [comment]
>He calls that comfy

![50 megawatt lounge 2015-03-25 at 11 17 16](https://cloud.githubusercontent.com/assets/8550416/23773369/eb923554-04ec-11e7-995b-f2daf2ef0912.png)

**Comment by Killette2** [comment]
DUDE SAFER SINGULO, LMAO

**Comment by DamianX** [comment]
close it
