### ISSUE TITLE
AI intercepted PDA messages show the reciever rather than the sender

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14307]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

b9a5ad2831c0df90e280fc12c751d3683bb899c8

**Comment by Shadowmech88** [comment]
Should it show both the sender and receiver?

**Comment by SonixApache** [comment]
Dunno, it says "Intercepted message from x" but x is the reciever, not the sender.
Oddly enough it works properly for spam mails.

**Comment by Ephx1** [comment]
I'm pretty sure it does it both ways, intercepting sometimes from sender or receiver.

**Comment by SonixApache** [comment]
Well that's fucked then, if it states 'from' rather than 'to'.

**Comment by Ephx1** [comment]
I think it's to somewhat confuse the AI, intercepting random messages can be really damaging to some players. A sort of curb to Big Brother.

_I mean you could always just get the key with minimal effort, but still._

**Comment by Allspice** [comment]
Sounds like it's just for asspain and ahelp generation.
