### ISSUE TITLE
Viruses cure themselves after extended periods of time

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#14300]
This is dumb, especially if you make a beneficial virus that nobody wants cured.
It's even worse since you have to wait a long time until stage 4. We could introduce some better QoL changes to virology before we're forced to do an overhaul or ignore it forever.

**Comment by ghost** [comment]
>what is the immune system

**Comment by Killette2** [comment]
nonhuman symbotic bacteria exist inside all of us right now though

**Comment by ghost** [comment]
>bacteria in the gut
>compared to viruses in-system

**Comment by Probe1** [comment]
How?

**Comment by Intigracy** [comment]
Autocuring is a coded in feature btw.

If it progresses to whatever the max stage is and then gets stage * 100 ticks in it'll autocure when it would normally progress to next stage.

**Comment by CptWad** [comment]
[not a bug][wyci][do not merge]

**Comment by Exxion** [comment]
Sure, there are fuckloads of symbiotic bacteria in you
But, at least as far as I'm aware, there is not one single symbiotic virus

To be fair, viruses in SS13 act more like bacteria than viruses, though

**Comment by Killette2** [comment]
Viruses are extensive work. It autocuring at stage 5 like you say really leaves a bad taste in my mouth. This is only reasonable for antag viruses where they're expected to be the end of the world so good on you if you survive, but with beneficial or "beneficial" viruses you might want them to last a little bit longer.

**Comment by Ephx1** [comment]
This seems good for some sort of hard to get chemical to pair with your virus to stop curing, beneficial or harmful.

**Comment by eplgr** [comment]
Does this actually happen, though?
I mean, have you ever released a beneficial virus and had it being self-cured after a long time?

I ask because it takes a lot of time to reach stage4, so I wonder about stage5.

**Comment by Shadowmech88** [comment]
I've seen it happen before.
It's not frequent though, simply because seeing a completely beneficial virus is already uncommon and seeing one early enough that it has time to cure itself is even less so.

**Comment by despotate** [comment]
Viruses curing themselves happens pretty often on extended with an active virologist. There's also the added problem that viruses increase your body temperature by 5*stage when you're infected, so even the most beneficial virus occasionally can warm someone up to the point where they take burn damage, though this doesn't happen too often.

Not too hard to just take a different dish with different antigens and splice all the same effects into it every fifteen to twenty minutes for re-releases though.

**Comment by PJB3005** [comment]
I see automatic cure messages way more often than you'd think in Admin debug logs.

**Comment by SonixApache** [comment]
once you make and release a beneficial virus, get a job change to chemist and make it your sole purpose to inject everyone with spaceacillin forever

**Comment by Killette2** [comment]
The spaceacillin stalls the virus not curing it, keeping it at stage 4 forever right?

**Comment by SonixApache** [comment]
Think so.

**Comment by eplgr** [comment]
At the start of `/datum/disease2/disease/proc/activate(var/mob/living/carbon/mob)` you can find:
```	
	//Space antibiotics stop disease completely (temporary)
if(mob.reagents.has_reagent(SPACEACILLIN))
		return
```
I am not sure it stops the symptoms completely (although it seems like it?) but for sure it prevents the disease to further evolve.

**Comment by eplgr** [comment]
Well, yes, I confirm, if you give someone spacecillin, good bye good symptoms.

**Comment by Killette2** [comment]
So how do we fix this before the rework

**Comment by Lokiamis** [comment]
There's no need for this when beneficial viruses are as rare as they are. Virology doesn't need to be an antag-only job like toxins.

**Comment by Kammerjunk** [comment]
Another reason to the list of why nobody plays virologist. It's a shame that the job is useless (partially because almost all symptoms are useless or straight-up bad, but partially because of stuff like this) and that should be changed.

**Comment by ghost** [comment]
There should be more ways of introducing symptoms to the body

Bacteria is quick to infect, quick to proceed, but can't hold as many symptoms and cures itself quickly

Viruses are the usual

Parasites are harder to cure, slow to proceed, can't hold as many symptoms, and feeds off something about the host

**Comment by ComicIronic** [comment]
You could add a gene for symbiosis and have it only be active if there are only beneficial symptoms (though that would be quite hard to check).

**Comment by Killette2** [comment]
Viruses also have too many hardcounters, including just simple radium being an instant cure. It's bullshit and undermines all a virologist's work.

I liked when /tg/ invented a new virology a long time ago and the cures were abstract things like gold and silver, or simple orange juice depending on how you customized the virus.

**Comment by ComicIronic** [comment]
That just sounds like old-virus. We could integrate more interesting research for "cures" than just antibodies, but I don't agree with binning the current system.

**Comment by Killette2** [comment]
Maybe we should see what the current problems with virology are. Maybe bus some people to be traitor if they have a virologist job and see what they can do with it. Nobody touches it and it just took a huge balance blow, meaning it's even less desirable now than it was before. Why should we want a job like this to be so useless? You don't even need a single machine in the lab to mass cure viruses for the whole crew.

**Comment by PJB3005** [comment]
Here's the problem with virology.

If you make it too advanced and hard to cure, virus events will become lethal.

**Comment by ComicIronic** [comment]
There's the possibility to split curing into two methods, one brute-force and one specialised: a specific reagent cure and the current antibody system. Either a large part of the crew works together to try and figure out what needs to go into space-chicken-soup to cure Gibbingtons, or a doctor does it in a skill-based way.
