### ISSUE TITLE
Snow should be obtainable from simulated snow turfs

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#14317]
Like on Deff or wherever else it's located. It's shitty that you can't get snowballs and the poutine citadel. I think Snowmap fixed this but, well, you know what happened with Snowmap.
JACK CLARK 2017

**Comment by kernikov** [comment]
I hope that's not my Easter egg, smh.

**Comment by ghost** [comment]
Find the ice cream vault. Its got snowballs

**Comment by kilozombie** [comment]
Yeah, but finding a vault, shovelling up snow, and mat synthing it or bringing it back without it melting somehow is a massive stop-gap to making the citadel.

**Comment by Blithering** [comment]
You could also hope to get lucky with gold extract snowmen

**Comment by Yelier** [comment]
I shared the same frustration, I was eager to make a citadel as well. However, it later struck me that perhaps it's better this way.  Wouldn't it be too easy to just go to the Deff easter egg or the holodeck? I feel like the citadel is supposed to be more special than the ocean by a good amount, but it'd lose that if the only extra steps you had to do were to head over to the holodeck or to weld a few walls on Deff.

Overall, the citadel is a good, funny easter egg. I think it's even funnier that it requires you to find a VERY specific vault somewhere in the extreme vastness of space.

Plus, like what Blithering said, the vault isn't exactly the only way. Xenobio is also an option.

**Comment by kilozombie** [comment]
Fair enough, yeah.

**Comment by west3436** [comment]
Implemented
