### ISSUE TITLE
Golden Atmos Hardsuit helmet light doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14315]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

a5970fe4a38eef27ebf2d206f28f04a8dd93871d

>General description of the issue
An atmospherics hardsuit that's been modded with the gold suit modkit loses it's helmet functionality.
The toggle does nothing.

**Comment by Probe1** [comment]
funny this came up twice in a month

**Comment by SonixApache** [comment]
if it's a feature and not a bug, why is there a goddamn button?

**Comment by jknpj** [comment]
Because @JustSumBody
