### ISSUE TITLE
Wizard Pain Mirror Spell keeps making people think they are thralled

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14323]
#### Description of issue
This isn't anything big but the Pain Mirror Spell plays a sound when summoned that is connected with the Vampire Gamemode and also gives the player a text that tells them they are "bound" to the wizard. I saw players getting confused about it in ahelps and ingame too, so maybe it should be changed. Even thought it is funny to see someone confused about it ingame, it could end up in a nonantag murdering people because he thought he was thralled somehow

**Comment by Killette2** [comment]
The thralls are supposed to cause the pain, that's why it's called pain mirror
