### ISSUE TITLE
pills in mouth

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14322]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
Shouldn't pills (cyanide for example) be able to be held inside mouth to bite into them when the time comes, just like people actually did in real life? (they used capsules though)

**Comment by Anton-Kr** [comment]
Wyci

**Comment by Killette2** [comment]
Make it a dental implant involving surgery then we can talk

**Comment by SkowronX** [comment]
Seems useful when stuck in crazy spirit dimensions.

**Comment by SonixApache** [comment]
You can knock teeth out of people, don't see why you shouldn't be able to knock teeth back into people.

**Comment by Kitfox88** [comment]
DENTAL PLAN

**Comment by SkowronX** [comment]
Time for a dentist title.

**Comment by Killette2** [comment]
LISA NEEDS BRACES

**Comment by Shadowmech88** [comment]
We could add tooth decay that fucks up your teeth if you don't brush them after eating something.

**Comment by FudgePucker** [comment]
Main problem with this idea is that the best pill to use wouldn't be cyanide.
Keep a bottle of hulk sauce in your pocket and put a pill in your teeth, stunned and handcuffed? Just pop that pill and you can just break those cuffs and become unstunnable.

**Comment by Killette2** [comment]
Why don't we have a can of spinach to give temp hulk?
