### ISSUE TITLE
Traitor mechanic scan explosive implants

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14334]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
You can't scan explosive implants as traitor mechanic. Is that intended?

**Comment by Killette2** [comment]
There's several traitor items that despite seemingly mechanical, like detomax carts, aren't scanable.

**Comment by AutismSpider** [comment]
only scan able if it has tech level to it

>no slip shoes have tech level to it but most of the implants and detomax carts don't

shit needs white list for what it can and can't scan

**Comment by SonixApache** [comment]
Can mechanics scan other PDA cartridges?

**Comment by ComicIronic** [comment]
You can scan it if it has materials or tech levels and is not unscannable.

**Comment by robintime** [comment]
duplicate of #11053
