### ISSUE TITLE
Bluespace Beaker looks like bloodbag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14342]
(WEB REPORT BY: rageblood REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
cb31b788a9d38504fd4882662d1325fd2f5e58d8 

>General description of the issue
Bluespace beaker has the same sprite as a bloodbag

>What you expected to happen
Standard bluespacebeaker sprite

>What actually happened
Bloodbag sprite is overlayed into a bluespace sprite

>Steps to reproduce if possible
N/A

**Comment by eplgr** [comment]
Did I do this? How?
This is hilarious. It's bedtime for me, gonna find what's wrong tomorrow.

**Comment by Probe1** [comment]
10:1 thanks  byond incoming

**Comment by Probe1** [comment]
I don't believe it. Its actually a bug.

**Comment by Probe1** [comment]
Can reproduce in 

beaker/bluespace
beaker/bluespace/large
beaker/noreact
beaker/noreact/large

Cannot reproduce in other beakers.  

Steps to reproduce:  Get beaker, fill it with any chem.

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/23884806/59795614-0845-11e7-9673-1fb45c0ea0b7.png)

Maybe because bluespace and stasis beakers have no partially filled state they shit the bed here.

**Comment by Probe1** [comment]
Best guess is somewhere here fucked up bad https://github.com/d3athrow/vgstation13/pull/14227/files#diff-9994537fa22ac1f1758b9d734aae9549R59

**Comment by eplgr** [comment]
![](https://puu.sh/uHUfj/cd968a2f6c.png)

But WHY

**Comment by eplgr** [comment]
I thought the issue had to do with using the same icon file in different places and applying different blend procs in each one.
But no, I moved bloodpack's filling sprites inside bloodpack.dmi and changed their var name, and SOMEHOW bluespace beakers still show bloodpacks overlays, even thought they are completely unrelated. Geez.
Gonna keep trying later.
