### ISSUE TITLE
(Player?) Gremlin interaction is a global admin message

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14346]
(WEB REPORT BY: mrfoster REMOTE: 172.93.109.202:7777)
>Revision
72dec266e83dde3ce137de4f25cf2b21f96570c9 

>General description of the issue
As admin you see all interactions relating to Gremlins as if you were right there. "X has interacted with Y", "X looks at the entertainment moniter but gets bored", "X begins to butcher [GREMLIN]:

>What you expected to happen
Not this

>What actually happened
This

>Steps to reproduce if possible
1) spawn gremlin
2) put player in gremlin
3) jump anywhere else and wait

**Comment by Kurfursten** [comment]
Ick ock, I didn't know I was a gremlinn

**Comment by clusterfack** [comment]
Watafak

**Comment by ghost** [comment]
oh god

**Comment by unid15** [comment]
Haven't encountered this, is it still an issue? Also sounds like a bug with virtual hearers

**Comment by Exxion** [comment]
I'm going to guess "no"
Reopen if reproduced
