### ISSUE TITLE
Comment out or remove the far sight mutation

### ISSUE THREAD

**Issue by despotate** [d3athrow/vgstation13#14349]
It makes you laggy as shit, fucks with sleeping/pain/blind overlays, and fucks with your UI buttons by shrinking and moving them around. Mostly laggy as shit though. I don't see a redeeming reason for it to stay in the game when it's strewn with so many bugs that fuck with your interface or ability to interact with the game itself.

**Comment by Ephx1** [comment]
> It's broken, so let's just get rid of it entirely

no

**Comment by DamianX** [comment]
Ehh, maybe we should fix the overlays and UI instead.

**Comment by despotate** [comment]
Can I just re-emphasize that **it lags**?

Most bugs can be hand-waved away, sure, a fucked overlay is bad but it won't actually make you stop playing the game. But FPS drop is an unforgivable bug and you can't even fix it until you get to medbay and take rye if there even is any. Almost all of the time when a geneticist passes around power injectors I end up regretting it because of the massive FPS drop I get from it. God forbid starting with it as a random mutation.

We should not be keeping things in the game that such a significant amount of frame drop.

**Comment by SonixApache** [comment]
works on my machine

**Comment by DamianX** [comment]
The issue I have with it is that byond 511 forces me to play on Icons->64x64, fucking with the UI and the overlays when I have far sight, as you said. On 510 this doesn't happen. 
I also don't recall ever getting lag from this, but I'll test it.

**Comment by Probe1** [comment]
Doesn't lag me at all.

**Comment by SonixApache** [comment]
Why can't you play on Stretch to Fit?

**Comment by Kitfox88** [comment]
Because stretch to fit makes everything look like absolute trash, sharp edges 4 life

**Comment by SonixApache** [comment]
Maybe if you're running at a retarded resolution.

**Comment by PJB3005** [comment]
> Running a retarded resolution

Not it actually makes everything worse even if you're on 1080p.

**Comment by Exxion** [comment]
You need to size the screen properly, and on 1080p that's easy
On any other screen resolution, though, it's hellish

**Comment by Intigracy** [comment]
You set the icons to 64x64
You resize the window to exactly the dimensions of the 64x64 icons
You switch to stretch to fit

**Comment by Intigracy** [comment]
Then when you get the mutation you expand your window by one tile worth.

**Comment by Exxion** [comment]
The problem is that on any screen resolution other than 1080p, the size you have to set the screen to to get an integer scale is really tiny

**Comment by DamianX** [comment]
Having to do that shit in [current_year] is BYOND unacceptable, anyway. Is there nothing we can do to fix it?

**Comment by Exxion** [comment]
Sort of
We can change the scaling style so that it uses bilinear or something as opposed to just duplicating pixels
But that probably wouldn't look any better
