### ISSUE TITLE
Xenoarch testing machines won't work

### ISSUE THREAD

**Issue by AceDick** [d3athrow/vgstation13#14348]
#### Description of issue
For those who aren't xenoarch nerds, a quick rundown of two machines that are important to the labwork of finding large artifacts are the Hyperspectral Imager and Fourier Transform spectroscope. They are used to identify the signal of an artifact and distance it is from where a rock sample was pulled. 

Found that no matter what, the machines would always produce a report that stated "The scan was inconclusive. Check sample integrity and carrier consistency."  and would do so for both machines that contained the same sample. Checked the changelog to see that several xenoarch changes were made but none involving that in particular so inclined to believe something fucked up somewhere. Tested with numerous circumstances (different carrier fluids which didn't work despite the nature of the report message, rock sample pulled from various rock tiles and strange rocks themselves, used analysis fluid only) and could not get it to work.

Will get more testing on it done as I'm able.

#### Difference between expected and actual behavior
Expected to be able to prepare a rock sample with a silicon carrier fluid and for the two machines to be able to scan and produce a large artifact signal and distance to large artifact. Got reports that only said the scan was inconclusive.

#### Steps to reproduce 
>go through usual xenoarch steps of finding artifact site, digging, and taking a sample from the wall using core sampler
>produce lithium sodium tungstate, grind sample, combine the two and add silicon
>put mixture over bunsen burner, separate silicon and analysis fluid from the rest
>put a beaker of fluid into Hyperspectral Imager and Fourier Transform spectroscope, begin scanning
>get report stating it was inconclusive

#### Specific information for locating

"The scan was inconclusive. Check sample integrity and carrier consistency."

#### Length of time in which bug has been known to occur

Not sure, have only gotten back to playing again for the first time this month, wasn't an issue last month where I tried xenoarch there again.

#### Server revision

Game: 72dec266e83dde3ce137de4f25cf2b21f96570c9 
Patches: c59333d8d4afdada839834747f67f85c9c964805 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
This is strange, it worked fine last time i tried. I'm pretty sure @PJB3005 and @BobdaBiscuit were testing it not too long ago, too.

Try using other carrier fluid.

**Comment by BobdaBiscuit** [comment]
I haven't played in the last couple of weeks, so it was working then.
IIRC that message in particular only appears if a machine tries to process an invalid mixture.
