### ISSUE TITLE
fix bomb logging 

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#14350]
It sucks.

ADMIN LOG: Bomb valve opened in Thunderdome with the remote signaling device attacher: Unknown Last touched by: zealotron(?)

Syndie-spawned bomb displays this.

It was triggered by Arch Sunder.

It's like that for every bomb, it only tells us who put the signaler on and who touched it last, not who actually made it blow up

**Comment by Aurx** [comment]
But we do log signalers.  

Or is this another damn case of "Logged ingame, never gets to the .txt"?

**Comment by Killette2** [comment]
So you can frame someone else for blowing a bomb with a proxy signaller?

**Comment by gbasood** [comment]
No, signallers are logged.
But yes, this could be improved somehow.
