### ISSUE TITLE
Runes appear on security cameras

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#1436]
Not sure if this is a bug, but it seems like one, since they don't show up for the AI, and they're using the exact same cameras.

Security really doesn't need the ability to remotely reveal the cult like this, anyhow, as if stealth culting wasn't hard enough.

**Comment by d3athrow** [comment]
Cameras have always been able to see runes, TG made AI not see runes a long time ago as well and the underlying code hasn't been changed outside of me making the blood image be stored rather than generated everytime an AI is made or reconnects.
