### ISSUE TITLE
Bleach Recipe Is Bad

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14367]
Instead of 4 parts + 4 parts + 2 parts = 2 parts, it should be 2 parts + 2 parts + 1 part = 1 part.

This matters because if you have 2 space cleaner, 1 oxygen, 2 salt in your beaker, it won't mix. You simply can't do odd numbers. And the chem dispenser only works in increments of 5.

Basically, you can't make bleach with no leftovers with a large beaker without taking the beaker out of the dispenser, your closest option results in 14 bleach and the aforementioned 2-1-2.

**Comment by Aurx** [comment]
40+40+20=20
Large beakers hold 100

**Comment by Kurfursten** [comment]
You can't do 20 because Ammonia only results in multiples of 3, come on step it up my man

**Comment by Aurx** [comment]
Then do 60-20-10 and repeat the 20-10 twice more.  It's a 6->2 reaction.

**Comment by Kurfursten** [comment]
Hmm, that could do it, actually.

Still, I can't think of a good reason to require a minimum of 4u Space Cleaner for the reaction, so this is a good change

**Comment by Aurx** [comment]
>could do it

It'd work perfectly.  

But yeah, there's no reason to have to mix in doubles.
