### ISSUE TITLE
Holodeck: Chess QoL Feature Request

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#14366]
1) Save state, or having to specifically click reset in order to reset the chess board- play chess for half an hour, power blinks off and on, RIP

2) Some lighting for the tiles would be nice, at the very least: picking up a chess piece lights up that tile, and the tile you set it on lights up. When the next piece is picked up, the first tile turns off, etc etc- helps speed up the game.

:^)

**Comment by kilozombie** [comment]
Nuke with the really good ideas
It's raining cats and dogs

**Comment by Kurfursten** [comment]
You might be looking for an idiom like "pigs are flying". Raining cats or dogs is, strangely enough, not meant to convey a sense of impossibility, but rather just means heavy rain.

**Comment by kilozombie** [comment]
Thanks, that's a good tip
Everyone's on top of things today.

**Comment by Killette2** [comment]
give chess pieces immunity to ZAS

**Comment by Kurfursten** [comment]
The king and queen are in the wrong starting positions, they're reversed!

What a blunder! Do you even play chess guys?

**Comment by JustSumBody** [comment]
While we're at it make the emagged version do this
https://www.youtube.com/watch?v=Vl9dvoUY5pc

**Comment by nuklearcellphoneg** [comment]
:*(

**Comment by Exxion** [comment]
I'm not really sure how possible saving the state is with current holodeck code

**Comment by Killette2** [comment]
Fuck it, the holodeck runs on holopower now. No more outages because the holodeck keeps it's own holopower projected.
