### ISSUE TITLE
Add logging to slime attacks

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#14368]
I've seen quite a few times of players making themselves slimes and then trying to get valids from it.

I mean shit, how long has player controlled slimes been a feature without logging for attacks? If lube is logged how isn't this?

**Comment by Killette2** [comment]
Because we code cool stuff and piece them together without touching each others code much. It's not a bad thing as much as it is an expected oversight.

**Comment by AutismSpider** [comment]
wait do smart gun pais have attack logs? some with hook shot borer slapping people?

**Comment by Exxion** [comment]
The former: Probably
The latter: I don't know

**Comment by Shadowmech88** [comment]
The former calls `Fire()` with the pAI as the user, so it should.
The latter makes use of standard attack procs with the borer as the user, so it also should.

Might be worth confirming, though.
