### ISSUE TITLE
Metaclub ghetto robo charge room below the library has some bad plating tiles

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14389]
![image](https://cloud.githubusercontent.com/assets/8550416/24080333/280eff70-0c73-11e7-8ec0-32537d777f7b.png)

When floor tiles are applied the icon doesn't update.

**Comment by PJB3005** [comment]
This also happens on the edges of the hole in the engine room on the derelict.

**Comment by SonixApache** [comment]
The whole maint is full of stupid shit like this.
It's actually already got a floor tile, it's just painted to look like it doesn't.

**Comment by Riekland** [comment]
This is an issue in literally all of deff maint, I think all of the areas that aren't just corridors have tiles painted to look like plating because duny is an idiot

**Comment by DamianX** [comment]
Is this the same thing as #13327?

**Comment by Exxion** [comment]
Yes
