### ISSUE TITLE
TALKING IN SPACE

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14385]
#### Description of issue

YOU CAN SPEAK IN SPACE. YOU CAN HEAR IN SPACE.
ANYONE IN HEARING (READ: SIGHT) RANGE OF YOU CAN HEAR YOU WHEN YOU SPEAK.
WE'RE PROBABLY THE ONLY SERVER THAT 'FEATURES' THIS NONSENSE.

#### Difference between expected and actual behavior

SPEAK IN SPACE -> NOBODY CAN HEAR YOU BECAUSE THERE'S NO WAY FOR THE SOUND TO TRAVEL TO ANOTHER PERSON EXCEPT FOR MAYBE THE SPACEMAN NEXT TO YOU IF YOU HOLD HIS HAND OR BUMP HELMETS OR SOMETHING
VS
SPEAK IN SPACE -> THE SPACEMAN NEXT TO YOU, CLOWN FLYING AWAY 7 TILES AWAY FROM YOU, AND PERSON INSIDE THE STATION OPPOSITE OF YOU CAN ALL HEAR YOU

#### Steps to reproduce 

SPEAK
IN SPACE

#### Length of time in which bug has been known to occur

I actually remember this not being the case at some point in the last two years.
Since goonchat, maybe?

#### Server revision

Game: a357ed3737a63af94f833447b62ef44266882e34 
Patches: c59333d8d4afdada839834747f67f85c9c964805

**Comment by ghost** [comment]
>IT'S A FEAAAATUUUUREEEEEEEEE

**no**

**Comment by ghost** [comment]
In space, no one can hear you cha cha cha

**Comment by Ephx1** [comment]
I'm pretty sure this wasn't actually the case at one point, yeah. I remember specifically there being an update to remove sound and speech from space all together, only allowing non-radio speech if you were in an adjacent tile.

> In space, no one can hear you cha cha cha

_What do you mean you killed him, cha cha cha?!_

**Comment by BestName** [comment]
It's fine, all the spacemen can read lips.

**Comment by ComicIronic** [comment]
Sounds don't play in space, although that doesn't respect any kind of pathfinding, so you can hear sounds across a space gap.

**Comment by Killette2** [comment]
You can hear literally every other sound in space including lasers, jetpacks, and airlocks of ships that are not connected to yours by anything but space.

**Comment by PJB3005** [comment]
If you can that's a bug that needs patching then.

And the sound pathfinding is night impossible to do performantly afaik so.

**Comment by kernikov** [comment]
tfw no global / local music can be heard either

**Comment by ComicIronic** [comment]
Global muting in space is an oversight, since I made the naive assumption that all sounds were local.

**Comment by Riekland** [comment]
Doesn't goon make you just gasp if you try and speak when you can't breathe, like if you're on empty internals or in space? Would it be possible for us to have that too?

**Comment by ComicIronic** [comment]
That should be pretty easy, using `say()` or whatever the proc is called.

**Comment by uazuaz** [comment]
don't know if related but...
if you build a floor in space and wrench a jukebox there, you can hear its music from anywhere in space, even on another z-level.

**Comment by Ephx1** [comment]
That is a _fantastic_ feature, please don't fix.

**Comment by IAGFPRMF** [comment]
Back in the day you couldn't hear fucks talking to you in space.
Bring back this feature tbh

**Comment by Shadowmech88** [comment]
How do you get a jukebox to turn on in space without an APC to draw power from?

**Comment by PJB3005** [comment]
Power in space is weird.

I haven't looked into it much but my understanding is that they don't check for power on construction and there's no APC to turn them off.

**Comment by SonixApache** [comment]
@Shadowmech88 kick it
