### ISSUE TITLE
High-frequency machete isn't flagged as dangerous for device scanners

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#14384]
I expected to have to splurge on the syndie scanner, I was wrong.

Here's me trying to scan an energy sword, and then a machete with all three types of device scanners.
![image](https://cloud.githubusercontent.com/assets/5549060/24072031/7522b2c8-0bad-11e7-9c75-60d33bc128e6.png)

**Comment by kernikov** [comment]
@jknpj

**Comment by jknpj** [comment]
It just want you to give war a chance.

**Comment by Shadowmech88** [comment]
It should at least have a decently high production cost if we want to keep it scannable.

**Comment by jknpj** [comment]
It's an oversight, i'll fix it.

**Comment by jknpj** [comment]
I forgot to add a Closes #14384. @Probe1, can you close this for me?
