### ISSUE TITLE
Metaclub QM office doesn't have a filing cabinet or anything similar

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14388]
#### Description of issue

i can't store my request forms anywhere
literally unplayable

#### Server revision

Game: fb3a2b42986c14cb969101635c6280a14a14f2f0 
Patches: c59333d8d4afdada839834747f67f85c9c964805

**Comment by SonixApache** [comment]
i mean yeah there's a folder but FUCK folders

**Comment by Probe1** [comment]
Store them in the trash.

**Comment by Kurfursten** [comment]
Store all request forms on one clipboard

Send all shipping manifests back for that sweet sweet 2 credit bounty
