### ISSUE TITLE
Changing Changelings with the Staff of Change drops their verb holder and allows for it to be picked up

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14399]
#### Description of issue
When you shoot a changeling with a Staff of Change the mob will drop the Changeling verb holder, which gives the player who holds it ling powers, but they do not seem to work.
![ahhh](https://cloud.githubusercontent.com/assets/17911005/24102602/d5795886-0d7c-11e7-9337-fed568e0fa1e.png)

#### Steps to reproduce 
Get a body with changeling verbs
Shoot it with the Staff of Change
Alt + click the tile of the changeling

#### Server revision

4e178bc82d16b127975121ceffcb9c28fae42721

**Comment by clusterfack** [comment]
Make /dropped() for verb holders cause them to self delete should be the solution here I think

**Comment by eplgr** [comment]
Does this happen with all verbs? I mean, if you are a wizard and someone uses the staff on you, you lose the verbs too. Do they appear to be on the floor too?

**Comment by Exxion** [comment]
No. Only certain mobs.
But Cluster's proposed fix would fix them all anyway.

**Comment by ComicIronic** [comment]
What the hell is a verb holder

**Comment by Aurx** [comment]
>What the hell is a verb holder
>Collaborator

ww

**Comment by ComicIronic** [comment]
excuse me fam I can't hold an encyclopaedic knowledge of 800,000 noodles in my mouth can I

**Comment by ghost** [comment]
I am not sure myself but my best guess is that it is in the contents of a antag's body and is responsible for giving a antag the variables needed to do antag stuff. Doesn't work if you just have the verb holder so it probably needs something else from whoever has it on his body.

**Comment by Aurx** [comment]
I mean, fuck, you take one look at the name and you can't guess what it does?  
It's called a verb holder.  
I'm willing to bet it holds verbs.  
Maybe even has fancy procs for adding and removing those verbs from the person it's in when its instantiated and destroyed.

**Comment by Exxion** [comment]
If memory serves, it holds mob-specific verbs for mobs whose verbs have to be changed sometimes (like changelings, borers, etc.) because mob verbs don't update when your `loc` isn't a turf or something along those lines

**Comment by clusterfack** [comment]
@ComicIronic its some stupid shitty way of getting around the byond bug where verbs can only get added to you while on a turf, by putting verbs onto objects and putting them inside people so they can access them

Personally I greatly prefer spells
