### ISSUE TITLE
Fourier Transform spectroscope Failure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14396]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Not sure if the scanner for large artifact triangulating is busted or not. Tried all carrier fluids in combination with the analysis liquids, all came up bad.

**Comment by Gunosaguki** [comment]
Just necroing this because Its still bugged. For all the large artifact changes we've been getting, its hard to actually get them because of this
