### ISSUE TITLE
When a body which has ghosts haunting it gets put in a Cryotube you can see the ghosts inside

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14398]
#### Description of issue
You can see dead people and observers which haunt a body in cyro by examining.
![panic](https://cloud.githubusercontent.com/assets/17911005/24102257/a16dc668-0d7b-11e7-8e24-d2ff19e021f1.png)

#### Steps to reproduce 
Put body with ghosts haunting it in cyro
Examine Cryo
Know that Shitter McGlubbs is dead

#### Length of time in which bug has been known to occur

I think I saw this even before the cryo sprite change, really not sure. Decided to test it out today and see that it really does happen

#### Server revision

4e178bc82d16b127975121ceffcb9c28fae42721

**Comment by jknpj** [comment]
FEATURE

**Comment by SonixApache** [comment]
2SPOOKY

**Comment by PJB3005** [comment]
Pretty fun bug but it should definitely be patched because it allows you to see who is dead.

**Comment by Riekland** [comment]
Might be neat to have them still show up but just have it say "you can see x tortured souls aside [playername]"
I dunno it seems too neat to just kill

**Comment by PJB3005** [comment]
Yeah I was thinking the same, though I couldn't think of a nice flavor text for it.

**Comment by Probe1** [comment]
X shapes float behind him

If list = < 1 /His shadow plays against the lights
If list > 1 /His shadow flies around the tube
