### ISSUE TITLE
Getting deconverted as a cultist seems to completely wipe your IC notes

### ISSUE THREAD

**Issue by invoid9** [d3athrow/vgstation13#14414]
#### Description of issue
If you get deconverted as a cultist, and then check your notes, they will be completely blank, meaning you can no longer check your bank details, blood type or whatever else. Not sure if this is the cause, but I did add a note of all the words since I didn't have a tome when I saw a comm with the words, so it kinda makes sense that was wiped.

#### Difference between expected and actual behavior
Being able to remember bank details and such after deconversion, instead of having complete amnesia about everything.

#### Steps to reproduce 
Get culted and then deconverted (this might also work with revs but I don't know)

#### Server revision

Game: 26565f98f4ebbae6551ecb651f1ca058f0724828 
Patches: c59333d8d4afdada839834747f67f85c9c964805 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
The issue is in cult.dm#L447.
`cult_mind.memory = ""`

The thing is: do we want to touch this at all before eggman gives us antag datums?

**Comment by Probe1** [comment]
yeah its fine we can fix conflicts.

**Comment by ShiftyRail** [comment]
Cult 2 issue
