### ISSUE TITLE
Spawned cyborg, died, human name in deadchat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14438]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When you choose cyborg as your occpation, spawn, set name, and then get spac- i mean, when you die, in deadchat and as a posibrain you have that human name you have as default in character creation.

>What you expected to happen
Have my cyborg name.

>What actually happened
Got my human name.

>Steps to reproduce if possible
Mentioned above.

**Comment by Exxion** [comment]
Even as a posibrain? Not just an MMI?

**Comment by jknpj** [comment]
Not a bug, it's your MMI's name.

**Comment by Intigracy** [comment]
If you're spawning as a borg then you have an MMI, not a posi.

Posibrains work fine.

**Comment by Exxion** [comment]
That's what I thought
Then 100% rock solid feature

**Comment by Ephx1** [comment]
spawn as posibrain option when
