### ISSUE TITLE
Penlight: bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14439]
(WEB REPORT BY: curver REMOTE: 172.93.109.202:7777)
Sometimes, the penlight doesn't work. Sometimes, it does.

Friendly intent (and not kicking or biting); aim for eyes; hold penlight in active hand; target.

Half the time, you attack someone and the other half you aim for their pupils. Their face gear doesn't matter, as you should get a warning anyway if they have any (i.e., it just won't work, but you won't be attacking them).

**Comment by MadmanMartian** [comment]
Can not seem to reproduce. Maybe the penlight was off?

**Comment by SGuivenne** [comment]
Either should be closed or given an unable to reproduce tag
