### ISSUE TITLE
box: double firelock outside the bridge

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14443]
#### Description of issue

@Skullyton 
![image](https://cloud.githubusercontent.com/assets/8468269/24374419/14132f28-1335-11e7-82e0-0c39fd2ded50.png)

#### Server revision

Game: 7d530bba3f41be24c08975ccc3774fb088e2c0c5 
Patches: c59333d8d4afdada839834747f67f85c9c964805

**Comment by ghost** [comment]
These will show up more as previously shitmapping two of them into the same place was handled by one getting deleted.

**Comment by Exxion** [comment]
Alright
Why does it drop the assembly on deletion?

**Comment by ghost** [comment]
It only drops it when the firelock detects another firelock on the same tile. Previously it only deleted

It's to stop people from just going lolbuild and deleting all the firelocks

**Comment by Exxion** [comment]
Ah

**Comment by SonixApache** [comment]
@Probe1 what the fuck, this happens every round on live. This is a [mapping: Box] issue.
