### ISSUE TITLE
Slimes still aren't logged properly

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#14442]
#### Description of issue
Slime attacks were logged in #14382 
Doesn't cover slime feeding (which is the one where they stick themselves to your mob and do clone damage until you die and it's the one you probably want logged because that's how they feed and reproduce and guarantee a hit on you as often as possible. This feeding currently *is* logged, but it's only logged in the VV attack log which isn't great for figuring out stuff post-round.
It'd probably be best to check if the slime has a client or if the victim has a client or something like that to avoid a bunch of regular xenobio work

#### Difference between expected and actual behavior
Slime feeding is invisible in the logs as long as the slime itself doesn't mention it

#### Steps to reproduce 
- Become slime
- Go near human
- Click 'Feed'

#### Specific information for locating

Playable slimes are at `/mob/living/carbon/slime` and subtypes (the simple animals are pet slimes and the hosile simple animals are rabid slimes)
The slime Feed verb (`/mob/living/carbon/slime/verb/Feed()`) is at `/code/modules/mob/living/carbon/slime/powers.dm`

#### Length of time in which bug has been known to occur

Probably always. I've seen two cases in recent times where this was an issue but I don't know of any changes to their logging other than #14382 

#### Server revision

7d530bba3f41be24c08975ccc3774fb088e2c0c5  

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues) Searched "slime"

**Comment by Probe1** [comment]
Honestly lugging them in general would be useful since being able to tell a player has been damaged is always helpful
