### ISSUE TITLE
Mommi namepick

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14444]
(WEB REPORT BY: riolenn REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Can't pick a mommi name when you are crated from a pbrain in middle of the round

>What you expected to happen

to be able to pick a name 
>What actually happened
You cannot choose your name any more.

>Steps to reproduce if possible

**Comment by gbasood** [comment]
Don't the roboticists pick the name of MoMMIs they create or
I could have sworn you can change your name/get your name changed when you're created this way
