### ISSUE TITLE
Burning Forever without taking damadge

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14440]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
i am able to burn forever as a human without taking damadge, it also seems i cannot be put out.

>What you expected to happen
i was gonna burn myself to death out of boredom

>What actually happened
instead im forever aflame, which is kind of cool

>Steps to reproduce if possible
in the backroom of the library one metaclub i emptied the room, put a stove next to a bed, poured welder fuel on the wooden floor, lit a match, and laid down naked in the bed. a small fire spread and quickly went away, i took a small amount of damadge, and then it healed and im just on fire.

**Comment by Exxion** [comment]
#13393

**Comment by kilozombie** [comment]
>damadge

hilarious
