### ISSUE TITLE
Viruses are not spreading like they used too

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#14454]
It seems to me that viruses are nowhere near as infectious as they were in the past. Specifically it seems like viruses rarely, if ever spread. This is true even when they are airbourne. I've seen people stand in the same room as other infected people for half an hour without getting infected at all.

To test:
1. random mob infection lesser / greater
2. leave uninfected mob in room with infected mob
3. watch as nobody new gets infected.

**Comment by jknpj** [comment]
@despotate nerfed viruloose, maybe related to this?

**Comment by Exxion** [comment]
No, as that only had to do with mixing viruses or something

**Comment by mtpowell** [comment]
![](https://i.gyazo.com/e533840410386bbbdb7e1d1807fbd246.png)


Maybe I'm a little too drunk but apparently wearing a paper hat makes you immune to viruses

**Comment by ghost** [comment]
One time I made a good virus that was airborne, went out without any virus protection except the virologist jumpsuit and not a single person got the virus even at the last stage with spreading symptoms

**Comment by Blithering** [comment]
Is it something to do with requiring a symptom like coughing for airborne?
