### ISSUE TITLE
centcom is accessible from a few vaults that lead to z level 2

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#14452]
the prison shuttle vault and the vampire den vault, both allow access to z level 2

this allows cheeky madmen to get to centcom by bagulothing the superhard rock walls

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by AutismSpider** [comment]
Bagulothing kills you though

**Comment by Shadowmech88** [comment]
Two people could go and one could sacrifice themselves to allow the other to get to Centcomm.

**Comment by Shadowmech88** [comment]
Should bagulothing in general just fail on Z2?

**Comment by JustSumBody** [comment]
muh round end griff
also could you do the same with say, someone constructing a particle accelerator manually and singuloosing from there

**Comment by Shadowmech88** [comment]
Sounds like the best solution is to just make singulo-proof walls and surround the vaults with them.

**Comment by Durgen** [comment]
perhaps an easier solution would be to surround z2 vaults with hyperspace turfs so you can't jetpack to centcom once you bust out

@AutismSpider greatness requires sacrifice

**Comment by jknpj** [comment]
>Baguloth

Watch as i pipe my way into centcomm as mommi fucking casual carbons

**Comment by Probe1** [comment]
All of these are bandaids.  The solution is to just put throwers around the area to force the player out.

**Comment by Exxion** [comment]
In all seriousness, it should just teleport you to the edge of random Z-level like a Z-level border does

**Comment by ghost** [comment]
Does super matter sea delete singulos? Is it possible to surround vaults with it and make it not spread?

**Comment by Probe1** [comment]
Yeah that's what I meant by throwers @Exxion sorry I should have been clear.
