### ISSUE TITLE
Drag damage feedback / discussion

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14469]
discussion of #14447 and #14468 and #14477 and #14535 and #14670 and #14746 and  #15271
a rundown of current drag damage mechanics and notes:
- Dragging someone who is knocked down AND has an unsplinted fracture AND is under the effect of gravity will, with a medium chance, cause brute damage
- Dragging someone who is: knocked down AND bleeding AND is under the effect of gravity will, with a chance based on their % of remaining blood, cause bloodloss
- Chances and damage are generally doubled when the person being dragged is in crit
- Correct procedure is to either splint or bandage someone before transport, or to transport them by roller bed / locker / office chair / bodybag / yellow intent grab

one good note from invoid:

> I like the drag change. It just needs blood trails that dont cause footprints when walked over

**Comment by ghost** [comment]
it shouldn't drag apart wounds that you've sealed up with bandages.

Open wounds yes, but if you've taken the time to treat them on-site, it shouldn't fuck them up royally to take them back to medical.

Phantom blood is bad, too.

**Comment by despotate** [comment]
Dragging gives me reverse ASMR
Seeing that "you worsen their wounds!" text is one of the few things in this game that actually makes me cringe in sympathy pain

**Comment by carshalash** [comment]
Making the game lag to shit from the blood footprints everywhere as well as just giving more reason for medbay to say fuck it and toolbox/clone is kinda shit.

Med arent really gonna bother trying to fix someone with an assload of broken bones and 30% blood from the dragging meme.

**Comment by SonixApache** [comment]
@Skullyton Checking for bleeding limbs instead of just general damage is probably a good idea.
Phantom blood?

@carshalash Going to try to make the trails not generate footprints. Speedclone nerf soon, though.

**Comment by ghost** [comment]
Problem with the blood is that it's an active process IIRC, because it can hold viruses.

So, once there's a shit ton on screen, it's lag city space-style

**Comment by SonixApache** [comment]
I could just remove virus transference from the trails, but that'd be kinda lame. footprints hold viruses, though, so maybe that's an addition to the mass lag that I can get rid of.

**Comment by Exxion** [comment]
The viruses, etc. in blood have nothing to do with the clientside lag, because all calculation is serverside.

**Comment by FudgePucker** [comment]
How do you pick up viruses from blood laying on the floor? Everybody has fucking shoes on, and even when you don't have shoes, unless the blood is fresh and you have open wounds on your feet, the chances of getting a virus from skin contact is low.

**Comment by FudgePucker** [comment]
Also making blood loss an EVEN BIGGER PROBLEM seems like a bad idea, considering how every single asshole on the server has O- blood and nobody donates.

**Comment by ghost** [comment]
Viruses that spread through blood ignore all resistances if you walk in the same tile as it, this happened once so I'm not 100% sure

**Comment by Kurfursten** [comment]
I see a lot more donation now that Dr. Acula is available, but happens when I play - usually the dead of night at deadpop when people run the bloodbot as sort of a gimmick when medbay is slow. Paradoxically this is when blood donations are least needed due to less patients in the first place.

**Comment by kernikov** [comment]
>every single asshole on the server has O- blood

Blood type is random, you can no longer select it.

**Comment by Kurfursten** [comment]
He was being facetious for effect, like how you might say "no one on the station knows how to do a surgery", which is possible but very unlucky if true

**Comment by SonixApache** [comment]
>Dragging in space still tears people apart

**Comment by Blithering** [comment]
Stealth cult buff!

**Comment by nuklearcellphoneg** [comment]
Walking instead of running while your legs or feet having brute damage alleviating some of the effects of pain when.

**Comment by nuklearcellphoneg** [comment]
That aside, I love this being added back in to be honest- unfortunate for the uneducated I suppose, but it overall has the tendency of buffing troublemakers while hurting the heroes, in general.

**Comment by jknpj** [comment]
We need roller beds in emergency lockers

**Comment by SonixApache** [comment]
but you can just use the emergency locker

**Comment by Kammerjunk** [comment]
More mechanics include
- Being unable to follow your Asimov laws no matter what action or inaction you take to the point where standing there and watching a human die is not an incorrect course of action
- Dragging someone who's been punched on a few times and decided to rest 🙁 

Checking for bleeding instead of brute sounds good

**Comment by ghost** [comment]
I've had to bind STOP DRAGGING HIM YOU IDIOT to a key because people don't read the chatbox to see it's causing damage

On second thoughts, that seems a bit counter intuitive considering the reason for the bind

**Comment by SonixApache** [comment]
Yeah, I'll get on the bleeding thing ASAP.

**Comment by SonixApache** [comment]
#14535 so that's done, now it checks for bleeding or fractures. If the boxing champion wants to lay down for a bit and get dragged, he won't fall apart anymore.
Thinking about adding a cardboard 'emergency medkit' with a splint, bandage and one-time-use ointment.

**Comment by SonixApache** [comment]
A mention from the discord; having the damage not activate when the person dragging is walking would be a good change.

**Comment by Huuuuuuuuuuugo** [comment]
...Would it cause too much a spriting nightmare to code in fireman's carry?

**Comment by PJB3005** [comment]
Yes it'd be a complete nightmare because you'd have to create sprites for every damn clothing item.

**Comment by SonixApache** [comment]
Could just use that thing that the gun charger / display case uses where it uses the sprite but smaller.
Except that probably wouldn't work due to the amount of overlays a human has?

**Comment by Exxion** [comment]
It would work just fine. Scaling applies to overlays.
It would look like absolute shit though.

**Comment by ghost** [comment]
Could just do a locking atom, where the person getting fireman'd is locked to the persons back, then y upped a bit.

but then you'd have to do the whole direction stuff as well, which I guess you can nab from chairs by using and abusing layers

**Comment by Blithering** [comment]
Make a giant baby harness item that can be equipped in the suit slot and buckled into like a wheelchair.

**Comment by SonixApache** [comment]
Well there's still some stuff I want(ed) to do, like no-footprint blood trails and cloning changes, but I've been busy with other things so this is as good as it gets.
