### ISSUE TITLE
Deff: Cargo shuttle loading doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14461]
(WEB REPORT BY: micano REMOTE: 172.93.109.202:7777)
50edc72ab72aa9598edb43897d5690ec185fbb65

If you press the loading door buttons they open the wrong internal door. So if you hit the loading door button for the out of shuttle lane, The first two doors open but then the top lane in bound door opens on the shuttles internal side.

Just push the button and the wrong doors open.

**Comment by Duny-** [comment]
Should probably be closed.
