### ISSUE TITLE
Gyrotrons are unresponsive if they are in space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14465]
(WEB REPORT BY: koltarius REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
As the title says, gyrotrons can not be linked or be used if they are in space, aka if they are in a room not marked on the CE/MoMMI blueprints.

>What you expected to happen
To be able to link gyrotrons while in space, as long as they are powered, secured and welded to the ground.

>What actually happened
Well, nothing.

>Steps to reproduce if possible
Place gyrotron somewhere on plating in space
Power, secure and weld gyrotron
Try to link gyrotron to see nothing happening

**Comment by mtpowell** [comment]
>To be able to link gyrotrons while in space, as long as they are powered, secured and welded to the ground.

But they aren't powered if they're not linked to an APC with blueprints. Unless you want them to function like emitters?

**Comment by FudgePucker** [comment]
Why not just make them like emitters? It would also let them be linked to the AAC, instead of some snowflake computer.

**Comment by Exxion** [comment]
High-power machinery should always require direct wires

**Comment by ReindH** [comment]
I'd really like if I didn't have to link every gyro separately if it can be helped, tedious as hell.

**Comment by FudgePucker** [comment]
Making it into an emitter child with a different projectile and icon would solve that problem as well ReindH, just gotta turn it on manually, or use the multitool to set a tag and frenquancy to the same as the AAC.
