### ISSUE TITLE
Staff of Change either needs to do a check for silicon jobbans before forceborging or just pump out purged borgs.

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#14462]
As the title says, the SOA is capable of force borging jobbaned silicon players.

It's difficult for me to force admins to take fuck ups from these silicons seriously when it's pumping out borgs that shouldnt be there in the first place.

So we either

1.Server ban these banned silicons when they are forced into silicons and they fuck up
2. "Pretend" they're purged or whatever
3. Remove borgs from the SOA entirely
4. Make the SOA check the ban database first.

I would prefer 4. 3. Would work. 1+2 are terrible. For right now we're having to go with 2 until this is addressed.

**Comment by Arthurdentist** [comment]
4 is the best option.

You could have it check banned status and if banned turn the victim into something nasty like a frankenstein or catbeast. Incentive not to get sillycon banned that way.

**Comment by mrpain666** [comment]
Actually I could be wrong about this. Sillycone banned players might not be able to get it. Someone double check.

**Comment by ghost** [comment]
Should vary up what it turns them into

Like make it so that you get turned into a MoMMI or an AI

**Comment by Arthurdentist** [comment]
@Skullyton Sillycon bans cover AI and MoMMI

**Comment by Shadowmech88** [comment]
Make it turn them into a spiderbot if they're silicon banned.

**Comment by FudgePucker** [comment]
>purged borgs

So you think having all access murderbots are a good idea?
Most of the really bad things SoC can create can't use computers or machines, first thing a purged borg is going to do is plasma flood.

I like the spiderbot idea

**Comment by Kitfox88** [comment]
>So you think having all access murderbots are a good idea?

I thought that's what sillycons already were even before they're purged

**Comment by Blithering** [comment]
A purged borgo will immediately go sec module and shoot the wizard, I'd say turn silicon banned people into MMIs when hit.

**Comment by ghost** [comment]
they turn into a robot, critical failure, instantly detonate

**Comment by ghost** [comment]
wait, shit, that's basically ei nath

**Comment by Exxion** [comment]
Yeah but only for people who are silicon banned

**Comment by Arthurdentist** [comment]
I like the idea of turning them into spiderbots but I have a feeling full sillycon bans actually ban you from spiderbot as well. Could be wrong however.
