### ISSUE TITLE
Fork overlays aren't working for seemingly any food

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#14472]
I'm guessing this is related to the bug that's preventing liquid from rendering in bottles

**Comment by Kurfursten** [comment]
Can you reproduce this in more than one round? If true it is relatively recent, fork overlays were definitely working on March 21

**Comment by kilozombie** [comment]
Yep I'll give it a go on the test server, just a sec
edit: Wait if it's a recent change that won't tell me anything. I'll do it on the real server and report back when it's not icky

**Comment by kilozombie** [comment]
Seems like this was an isolated incident, I'll reopen this if it happens consistently
