### ISSUE TITLE
Morph Masks don't transform and kill you on death.

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#14480]
#### Description of issue
I was killed as a grey cyber horror, robogibs appeared and the horror fell over and ghosted me, I did not transform back to normal and die in my regular body.

#### Difference between expected and actual behavior
**EXPECTED**
Run into electrified door, die and revert back to normal.

**ACTUAL**
Ran into electrified door and become a unsavable cyber horror corpse.

#### Steps to reproduce 
I was a fully grown diona while using the grey cyber horror mask, I ran into an electrified door and got oneshot.

#### Length of time in which bug has been known to occur

Since masks were ingame.

#### Server revision

90dd884865df7f67469b9d209545849d8c843319 

Patch c59333d8d4afdada839834747f67f85c9c964805  

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
cyber horrors call qdel on death, probably deleted your reference and couldn't put you back in

**Comment by PJB3005** [comment]
Isn't even exclusive to cyber horrors, this is broken for ALL simple animals.

**Comment by PJB3005** [comment]
Oh dear god this goes deep into simple animal code.

Simple animals use `Die()` for everything `death()` does on regular mobs. Yay.

**Comment by PJB3005** [comment]
And to make matters worse, a lot of this shit doesn't call `..()` in `Die()` either, which means the entire death stack is fucked.

**Comment by PJB3005** [comment]
https://www.youtube.com/watch?v=8JaJzzNfygo

~~I give up.~~
