### ISSUE TITLE
Slime people bugs and stuff

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14497]
#### Description of issue
since they're mutant race instead of an actual race this causes some shit to happen,
cameras show them as regular humans
![image](https://cloud.githubusercontent.com/assets/22992659/24574852/c73695f0-165e-11e7-8970-d9db073b8313.png)
they appear as human in cameras (left) but hulked people still appear hulked in cameras (right)
there were other issues concerning other races have weird shit happen when consuming the mutation toxin
I doubt anyone will fix it and even make it into a real race but it's worth a shot at making an issue instead of shitposting
they are also buggy with being absorbed by a changeling, it causes the ling to look bald for a period of time until it randomly updates to look like a slime person. The ling still has the powers from it just not the appearance
![image](https://cloud.githubusercontent.com/assets/22992659/24575006/1a205f7e-1661-11e7-86a2-c7c0ccc5511f.png)
pic is transforming to the slime person then biting the wire without taking damage
#### Difference between expected and actual behavior
>act like a normal race or atleast be like hulked out people

#### Specific information for locating

probably has to do with being a mutantrace instead of a race

#### Length of time in which bug has been known to occur

a long time i guess

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Commandersand** [comment]
god damn what it automatically published

**Comment by MadmanMartian** [comment]
This is fixed. Slimepeople were converted to a proper race

**Comment by Exxion** [comment]
I really have no idea why the fuck they looked normal in photos
But *shrug
