### ISSUE TITLE
Runtime in striketeam_datums.dm

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#14492]
Upon pressing ``` Send in an Emergency Response Team! ``` I was greeted with this runtime.  No ERT were selected.  Now maybe people just forgot to set their preferences.

```

[17:53:46] Runtime in striketeam_datums.dm, line 67: Cannot execute null.is afk().
proc name: trigger strike (/datum/striketeam/proc/trigger_strike)
usr: Default Cyborg-211 (probe1) (/mob/living/silicon/robot)
usr.loc: The floor (125, 65, 2) (/turf/simulated/floor)
src: /datum/striketeam/ert (/datum/striketeam/ert)
call stack:
/datum/striketeam/ert (/datum/striketeam/ert): trigger strike(Default Cyborg-211 (/mob/living/silicon/robot))
/datum/admins (/datum/admins): Topic("src=\[0x2104d254];secretsfun=s...", /list (/list))
Probe1 (/client): Topic("src=\[0x2104d254];secretsfun=s...", /list (/list), /datum/admins (/datum/admins))
Probe1 (/client): Topic("src=\[0x2104d254];secretsfun=s...", /list (/list), /datum/admins (/datum/admins))

```

@JMWTurner

**Comment by mtpowell** [comment]
![](https://i.gyazo.com/2a0d628a8f9803d0465242aaddb241f5.png)

This should return, not continue

**Comment by Intigracy** [comment]
no it shouldn't

if you return instead of continue then the first person looped through that's jobbanned ends the recruitment for everyone else

the problem is a null client trying to do O.client.is_afk()

put !O.client before the first check

**Comment by mtpowell** [comment]
ah I was under the impression that was for every client, my bad. One of the caveats when you come from PHP.
