### ISSUE TITLE
Tableclimbing is slightly bugged, still a great feature though really 10/10!!! !!

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#14508]
when somebody else climbs on a table you see "You bang your head on the table!" and when you climb on a table it says "<your name> bangs his head on the table!" instead of the other way around

**Comment by Shadowmech88** [comment]
A fix has been merged but the server's not recompiling for some reason so the live version still has the bug.

**Comment by Intigracy** [comment]
#14502 fixed it, but the server isn't getting updates for some reason
