### ISSUE TITLE
Augment wish list

### ISSUE THREAD

**Issue by DunkelzahnsWill** [d3athrow/vgstation13#14505]
Sup fam, I'd like to officially request some neato borg/mech augment additions that reach into the silly.
From the modules borgs already have, like built in chem/booze dispensers, to the ability to lift things in big crushing exosuit arms!

6 million credit spess man when?

**Comment by ghost** [comment]
Where's the list?

**Comment by DunkelzahnsWill** [comment]
- [ ] Machinegun leg
- [ ] Exosuit arm
- [ ] Implanted limited-function micro-chem master
- [ ] subdermal armor
- [ ] implanted SMG in an arm
- [ ] implanted sec hud
- [ ] implanted co2 jetpack
- [ ] emergency air implant
- [ ] cranial bomb implant
- [ ] foot spikes similar to trader boots, perhaps weaponizable?
- [ ] wired reflexes, low percent chance to parry/dodge boolets or punches
- [ ] eye mounted laser-pointer

**Comment by ghost** [comment]
Groin pulse cannon when

**Comment by ghost** [comment]
Now this I can work with.

Add more civvie level shit, that stuff's all military tier

**Comment by yclatious** [comment]
How about cyborg stuff? Built-in flash for a eye/ eye camera, replacing bones with titanium rods and such, air purification module for lungs so stuff like co2 doesnt fuck you up.

Small things though, lets not go crazy and set a bad example.

**Comment by Ephx1** [comment]
> Rev head tries to flash someone
> They flash back with their eyes and deck them 

Fund it

**Comment by Kurfursten** [comment]
>Rev game mode
>Still going by the time a roboticist can print out advanced eyes and do an eye surgery

**Comment by yclatious** [comment]
Happens sometimes, rev is a interesting gamemode when its stealthy.

**Comment by Yelier** [comment]
How has nobody suggested a skull gun yet?

**Comment by ghost** [comment]
TBH all this stuff should require a special item or table you can get from max possible research like maybe needing phazon?

**Comment by SonixApache** [comment]
need eye implants that put a yellow outline around everything

**Comment by AutismSpider** [comment]
make the foot spikes work like mag boots/borers foot claws power. toggle them on and off etc

**Comment by Jubisloviu** [comment]
it would be nice to have a tool-kit arm, with all basic tools similar to a swiss army knife.
also being able to insert steel plates in your body to increase DR and slowing you down in exchange for the extra protection.

**Comment by SonixApache** [comment]
THAC0 system when
