### ISSUE TITLE
Trains haven't been reverted or voted on yet

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#14526]
Yes, yes, we might like trains, sure. Choo choo! But it was an April Fool's PR and should either be reverted, or given another vote/discussion (since last time it was decided that they shouldn't be added, IIRC).

by trains I mean attack animations

**Comment by Intigracy** [comment]
AA have a preference that's off by default, which is what the detractors last time said they'd be okay with.

**Comment by kilozombie** [comment]
That'd be a nice solution too.
Objectively, it makes reading a combat situation WAY easier. I don't mind having them on but let's have it actually discussed rather than stealth-merged in a meme PR

**Comment by Exxion** [comment]
Actually, last time it was decided that they not only SHOULD be added, but WOULD

A poll in a while might be opened to see how people like them when they're actually in the game. After all the initial uproar has died down, of course

**Comment by kilozombie** [comment]
OK, sure. No harm in giving it a week to stew, especially if they're made off by default.
Currently they're on by default.
It was a meme PR and they were stealth-merged in, that's real shitty and mean to the playerbase.

**Comment by Exxion** [comment]
Yeah I can't really disagree with you there

**Comment by clusterfack** [comment]
I wouldn't be worried even with a poll being made, attack animations have never been outvoted in a poll ever even Intigracy's pr which 2/3rds of the people supported (without a preference). Not sure why it would default to anything but 0 because the migration clearly states ``"ALTER TABLE `client` ADD COLUMN attack_animation INTEGER DEFAULT 0"``

**Comment by kilozombie** [comment]
I recall opening it up to item animations being default and I've also heard people in the thread say it was item animations by default.

**Comment by N3X15** [comment]
It's a preference toggle, calm your tits

**Comment by Exxion** [comment]
It is item animations by default.

**Comment by kilozombie** [comment]
Sorry-- I just think that when things are added, they might as well be added in a way that's transparent, rather than in this way, which feels like cloak-and-dagger.

...where does it seem like my tits aren't calm? I wouldn't have even made this issue if not for the torrential shitposting in the thread about it

**Comment by Exxion** [comment]
Yeah
While I do think attack animations are a good change and should be added, this was kind of a sketchy way to do it

**Comment by clusterfack** [comment]
That's really a case of focusing more on *procedure* than the actual content. There is no way that a completely optional feature should be controversial in the slightest.

**Comment by kilozombie** [comment]
Yeah, this issue is about procedure. Nobody's even saying otherwise.

**Comment by kilozombie** [comment]
So since they're on by default but intended to be off, obviously that's a bug that needs fixing (and will make people happy). Everyone wins!

**Comment by AutismSpider** [comment]
if its a toggle whats the big deal if they dont like it just it off.

**Comment by kilozombie** [comment]
I guess the primary argument against attack animations is that they make combat too easy. Not sure I side with that belief, but it is the one that was tossed around way back when.

**Comment by N3X15** [comment]
How the fuck does an effect make combat "too easy"?

**Comment by kilozombie** [comment]
You can see who's attacking who at a glance, rather than needing to check the event log.

**Comment by clusterfack** [comment]
It makes it more understandable and user friendly, which has always been one of the design goals of the server.

**Comment by kilozombie** [comment]
All completely irrelevant to the discussion and issue at hand, which is the method with which this was merged.

**Comment by clusterfack** [comment]
The method of which something is merged is the vein of attack of people who do not have any rational arguments to oppose the change. Issues are not meant for discussion of managerial matters, and I have closed them in the past for becoming such and I will apply the same here.

**Comment by kilozombie** [comment]
Make sure you fix the bug where they default to on, since it was (as you demonstrated) unintentional behavior.
Unless we don't actually have any standards.

**Comment by PJB3005** [comment]
Having them be opt out is a ton better than opt in.

**Comment by Probe1** [comment]
Calling something you dislike a bug is not a good way to get people to listen to you.

**Comment by Shadowmech88** [comment]
>Issues are not meant for discussion of managerial matters

For future reference, where is the best place to discuss Github policy? The forum?

**Comment by gbasood** [comment]
Clearly it means you should go to his safe space Discord server to complain to him directly.
Honestly cluster you're just showing that you don't want to listen to the users by closing an issue with that statement

**Comment by kilozombie** [comment]
>Not sure why it would default to anything but 0 because the migration clearly states "ALTER TABLE `client` ADD COLUMN attack_animation INTEGER DEFAULT 0"

Unintended behavior is a bug, @Probe1 . Clusterfack didn't intend for it to default on, therefore it's unintended behavior.
I'm not trying to make a mountain out of a molehill, the fact is that the thread and server population _has already done that._ It would help if there was some better communication here.

**Comment by gbasood** [comment]
Since I can't edit my comment
Cluster is right about the user friendly part.
Kilo is right in that this shouldn't have been merged as a joke PR on April fool's day with a joke description and title if it was intended to be kept in game, since it just ends up looking dishonest
But nothing's changing about the code itself until we get the poll results

**Comment by gbasood** [comment]
Except maybe the default option part

**Comment by Riekland** [comment]
I have no real reasons past the aesthetics of it and the fact that I hate change but this is still a retarded way to get your PR through
We have rules about sneaking shit through in unrelated PR's already, I don't see how this doesn't apply
Fucking remake it with less autism and have it merged the normal way you shitlord

**Comment by kilozombie** [comment]
I think this is actually not a big deal even if it might seem like a big deal in the moment. We'll all move past it.
The coders and playerbase need to hug it out ASAP.

**Comment by PJB3005** [comment]
If it makes you feel any better, it's not like it wouldn't have been merged anyways.

**Comment by kilozombie** [comment]
Oh no, absolutely. I don't doubt it would get merged and I'm happy with it.
The fact that the only problem people have is that the coders were rude to them makes me think things are really probably okay, let's just be nicer to each other next time, thread and github and discord included.

**Comment by Exxion** [comment]
Everything about this ordeal was awful, other than the fact we now have attack animations
Maybe we shouldn't push a serious feature as a joke then expect people to not get upset
