### ISSUE TITLE
Hulks punching walls can be seen through walls with attack animations.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#14533]
Specifically those on a wall itself, makes cool aid man roleplay very difficult when everyone sees the fist icon  flashing for a few seconds before the hulked out geneticist comes flying into the cap's office.

**Comment by Kurfursten** [comment]
At long last I know what that icon is supposed to be

Also simple mobs (like carp) send a fist icon into glass windows which is... weird looking. Could we maybe send an icon of the mob itself into the window? That might look less weird.

**Comment by DamianX** [comment]
it's a feature, because the spessman can tell the wall is being punched to pieces. in fact, why don't we have sounds for wall smashing too?

**Comment by PJB3005** [comment]
Sounds like a feature to me.

**Comment by Riekland** [comment]
Amazing
Is there not a sprite for biting? Would using bite intent make fists appear on the person I'm biting? Do people not check their pulls?

**Comment by Shadowmech88** [comment]
If I remember correctly, when a hulk hits a wall there is flavor text about the wall creaking and bending under the hulk's punches.
I think there should be audio as well.

**Comment by JustSumBody** [comment]
>Do people not check their pulls?

Didn't see you point it out in the PR :v)

**Comment by clusterfack** [comment]
1. Can't be seen through walls, you can see the attack animation because you can see the wall that is being destroyed by the hulk.
2. @Riekland that's a sprite issue, if you made sprites for kicking/biting for me I would add them
3. @Kurfursten same with carp and such, its just a matter of getting sprites, the fist was meant to be a generic unarmed attack until spriters made some animations for it

**Comment by FudgePucker** [comment]
Better idea, totally remove the tumor instead of keeping it on a toggle.

It was a good April fools joke because it is so cancerous.

**Comment by yclatious** [comment]
You already know they wont revert it once its in fudge. Sucks, but fuckilydo, a revert pr wont happen or pass so just get used to it.

**Comment by FudgePucker** [comment]
Riot

**Comment by PJB3005** [comment]
@FudgePucker riot against the community who voted yes for it, then.
100% thread shitposter tier.

**Comment by Blithering** [comment]
@Shadowmech88 you might be thinking of when an alien or horror ling forces a door open, wall punching as hulk only gives a 'you hit the wall' message.
The main reason I made this issue is because having attack animations visible when the attacker isn't makes  surprising people that much harder.

**Comment by PJB3005** [comment]
Let's be honest in no real circumstance would you not notice when a hulk is punching your wall in.

**Comment by ComicIronic** [comment]
The question is if it's fair to see WHAT is doing the wall-buckling. Until there's something which keeps that anonymity for good reason, I'm fine with the animation being visible.

**Comment by FudgePucker** [comment]
If you don't get a notice with them off then fix that or fix this.
Its not optional if you get an unfair advantage.

**Comment by PJB3005** [comment]
@FudgePucker GEE just like how you can't see who is attacking who as AI without attack animations.

If the "unfair advantage" is an argument then your own stupidity is the only issue.

**Comment by Kurfursten** [comment]
Let's steal the metal groaning sound TG uses for opening unpowered doors with a crowbar, then use it for this

**Comment by aceedex** [comment]
The obvious answer is to remove attack animations, since they're beyond stupid

**Comment by Exxion** [comment]
There's nothing unfair about missing out on information due to your own choice to turn a feature off

That said, why CAN you see the animation through the wall? Isn't the animation on the attacker, not the thing being attacked?

**Comment by clusterfack** [comment]
If it is an animation on the attacker then clicking on the animation by accident will cause you to click on yourself. This occurs because the click behavior for images inherently tied to the things they are attached to, and you cannot reset mouse opacity for them.

Thus
1. Put the image on the target (like we do and TG does) - click behavior works fine
2. Put the image on the attacker - causes you to click yourself (and hit yourself) if you click the animation

**Comment by Exxion** [comment]
>you cannot reset mouse opacity for them

You can with a `PLANE_MASTER`, but I guess that's probably more trouble than it's worth
