### ISSUE TITLE
Mimes and Hardcores reagent being able to whisper.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#14530]
#### Description of issue
Mimes shouldn't be able to talk, but if you have hardcores in your system and do the deathgasp emote you whisper a line of text instead.

#### Difference between expected and actual behavior
You whisper "i told u i was hardcore" instead of the regular emote.

#### Steps to reproduce 

Just eat bustanuts and *deathgasp as a mime

#### Length of time in which bug has been known to occur

Beats me, always?

#### Server revision
Revision: 7710d243e9515f233531d36ee55d6cb647cc5e66

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
truly a hardcore mime
