### ISSUE TITLE
Krampus still avaliable from the staff of change

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#14546]
Not the first time I've made this issue but each time it apparently gets fixed when it never actually does. This time im making it again to illustrate just why this fucking awful thing needs to be removed.

In fact I think we'd do better to remove the Krampus Mob entirely until its not a mess but asides from that take a look at this screenshot. 

![krampus nightmare](https://cloud.githubusercontent.com/assets/6353372/24678458/87d3e620-1982-11e7-9a82-bd810e56733a.png)

See all those dead krampuses on the floor? Those are actually his limbs. His limbs share the same sprite as his entire body. I hate the sack sprite too, how its part of the mob and not a separate item. Please do something about this before I have an anyeurism. 

To replicate:
1. Take staff of change
2. Turn crew into a disgusting joke mob that should have been removed after christmas
3. Create clones of the disgusting joke mob by removing its limbs.

**Comment by Kurfursten** [comment]
Nice to see someone getting use out of the RCL though.

**Comment by Exxion** [comment]
I'm about 98% sure that Krampus *was* removed from the SoC a while ago
Who fucked it up?
