### ISSUE TITLE
Poor lighting in Deff Library.

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#14550]
Even with all HE lights, the library in Deff is really badly lit, especially the part where it meets the maintenance leading to the janitorial closet.

Deff has a lot of problems like this because it was designed at a time before Goonlighting. And, uh, a lot of other maps also have their spacing with this in mind. We should probably go over some of this at some point..

**Comment by Probe1** [comment]
Weird I did a pass when goonlights were implemented for Box, Meta, and Deff but I guess I did a poor job on Deff or maybe skipped Deff and am misremembering it.

**Comment by Megamaw** [comment]
there are still points on box where i have issues but i'll point 'em out later

**Comment by Megamaw** [comment]
of note, another spot i've noticed: where medbay meets morgue

**Comment by Probe1** [comment]
Every tile does not need to be 100% lit.
![image](https://cloud.githubusercontent.com/assets/8550416/24692268/30de8de2-19a6-11e7-8950-2489f9aa8f1e.png)
  

This is fine.
