### ISSUE TITLE
Smothering somebody with a rag also wipes them down

### ISSUE THREAD

**Issue by d3athrow** [d3athrow/vgstation13#14556]
#### Description of issue
If you target the mouth and click somebody you begin to wipe them down with the rag as well as smother them

#### Difference between expected and actual behavior
Smothering only

#### Steps to reproduce 
Equip rag, apply chemicals, target mouth, click somebody adjacent

#### Length of time in which bug has been known to occur

Unknown

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Rags are truly magical
They have next to no sanity on anything at all

**Comment by Lokiamis** [comment]
Wetting them at a sink also starts wiping down the sink

**Comment by Probe1** [comment]
I had no idea you could do that with rags.
