### ISSUE TITLE
Attack animation settings don't seem to save

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14555]
#### Description of issue

Attack animation settings don't seem to save. Setting them to anything but none will have them revert to none next time I connect.

#### Difference between expected and actual behavior

Set setting -> hit save setup or save slot -> setting remains
VS
Set setting -> hit save setup or save slot -> setting goes back to none

#### Steps to reproduce 

change setting, hit save slot and/or save setup, then wait out a round and check on the next

#### Server revision

Game: 4ea9c1b476a5f4775867d7767ecfe518c0f23f86 
Patches: a761ebd6e1fd1fcdb30863a1e9a283b69875d588

**Comment by PJB3005** [comment]
@clusterfack reeeeee

**Comment by Riekland** [comment]
B R A V O
R
A
V
O

**Comment by PJB3005** [comment]
Candidate number 1: ![](https://cdn.discordapp.com/attachments/239823463802470400/299201860001333248/unknown.png)

**Comment by ComicIronic** [comment]
B R A V O

**Comment by clusterfack** [comment]
Sqlite queries, how do THEY work

**Comment by Yelier** [comment]
Default character doesn't work either. It just goes back to an old one despite having a more recently saved character.

**Comment by PJB3005** [comment]
Fixed by e26c076d14fe66d2f06db759bfe7ae4ce995bfc6 supposedly.
