### ISSUE TITLE
Spawning as vox drops regular job clothing on the ground

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#14563]
...in addition to having the suit equipped.
![image](https://cloud.githubusercontent.com/assets/6307265/24738600/f76c4e04-1a96-11e7-8864-509baefe62b7.png)

I don't think this is intended.

**Comment by Probe1** [comment]
Its probably specific to that job.

**Comment by DamianX** [comment]
I think I remember this happening with MD, surgeon and CMO. May happen with the rest of medbay too.

**Comment by Kurfursten** [comment]
I'm guessing what's happening here is the Vox equip (from alien.dm) is running first, then the job equip under medical.dm is running, and the suit slot is already occupied.

Could be prevented by checking if already wearing a suit in medical.dm before trying to add a labcoat

**Comment by kilozombie** [comment]
This happens with Chef also.
It's not a big deal and if those items weren't dropped you'd never have a way of getting them on some jobs/stations. It'd be good if they were plopped in your backpack or something.

**Comment by Ephx1** [comment]
Sometimes these objects are deposited on that one tile lobby screen area before everyone is sorted out too. So occasionally this won't happen.

**Comment by jknpj** [comment]
Old oversight, happens with plasmaman too. As kurf said species code equip the suit before job code and since job code uses equip_to_slot_or_drop the labcoats end in the ground.

**Comment by Exxion** [comment]
Happens with roundstart bartender, but not latejoin
