### ISSUE TITLE
Arenas

### ISSUE THREAD

**Issue by Yelier** [d3athrow/vgstation13#14568]
There were some neat ideas in the thread about non-bomberman arenas today, so perhaps the conversation can be continued in this issue. 

Here are some of the ideas that people posted:
-Constant arenas going on z2 throughout the round that ghosts can sign up for, not just from admins making arenas at round end
-Silicon/mime/clown-like naming upon spawning into an arena
-More TV cameras in the arenas so the people in the station can watch
-Different jump-to arena verbs for each arena

As for the actual arena ideas:
-Random loadout thunderdome (I assume each person has the same loadout?)
-Instagib rifle arena (someone suggested HFblades in their back slot as well)
-Vanilla thunderdome (like the holodeck)
-Tank minigames
-Mech duels
-Fists only rage cage that gibs people that try to disarm/grab
-Big highlander box

If you have any other ideas or input, please feel free to share. I'm not actually coding any of it, I just thought that there were some cool ideas in the thread and decided to document them.

**Comment by SonixApache** [comment]
fuck yeah, fuck yo-
wait, this isn't a PR
@Skullyton get on it

**Comment by ghost** [comment]
*aflap

**Comment by Yelier** [comment]
Another idea - maybe the time suit could be in the pool for the random loadout thunderdome? (if it ever gets merged, that is)

**Comment by SonixApache** [comment]
oh yeah, timesuit-on-timesuit warfare
just like in that warehouse level

**Comment by ghost** [comment]
>Rather than having an arena datum, deity made it a hardcoded BOMBERMAN datum
>All the turf placing is hardcoded
>All the equipment is hardcoded
>Everything is hardcoded

AAAAAAAAAAA

**Comment by yclatious** [comment]
We believe in you dragon. Grant us sweet THUNDERDOME when lings meme half the station or when its another WE BUILD.

**Comment by Shadowmech88** [comment]
A lightcycle arena would be nice, as well.

**Comment by Probe1** [comment]
Look at TGs capture the flag code, its very advanced.

**Comment by Durgen** [comment]
while this idea sounds cool, I think having a parallel deathmatch running for ghosts and observers might detract from population of the station

**Comment by Probe1** [comment]
It's more about keeping the dead busy and not quitting the game.  Which is what they do when they have nothing to do.

I hear where you're coming from but its bog standard not the case.  Without ways to pass the time or get back in the round people just leave and play different games.

**Comment by JMWTurner** [comment]
Ghosts who play Bomberman can never re-enter their corpses. This should be somehow fixed until Arenas become an actual thing.

**Comment by Yelier** [comment]
@Durgen Probe summed it up perfectly, I was just about to say something similar. People come to the server to play SS13, not thunderdome or chess. The holodeck has both of those with no risk of dying (assuming you use holoweapons and not real ones in the thunderdome) yet it remains empty most of the time. If anything, it'll keep more people on the station. 

Take this situation as an example:
Guy dies
His current options are to play as a mouse, mommi, observe, or wait to possibly come back, be it cloned or another method, or just disconnect
If he just wants to be cloned and it's clear he won't be, disconnecting is the likeliest option
If he does disconnect to do something else, there's a good chance he won't be back the next round, due to missing it or just losing interest for the time being.

Now, if there's a more fun alternative, he'll probably stick around and do one of those fun alternatives. And before you know it, SMELELELE will have happened and he's back in the lobby for the next round. I'd be worried about more roundstart observers sapping players from the station if the holodeck WAS constantly in use, but that's not the case at all.

**Comment by SonixApache** [comment]
for me alternative arenas would be nice when the round end gets delayed by 30 minutes because some shitler is lying to the mins about doing something stupid in a videogame

**Comment by Hoshi-chan** [comment]
Instagib CTF on Facing Worlds WHEN??

**Comment by NigglyWiggly** [comment]
>Constant arenas that ghosts can sign up for
>Constant stream of attack logs and minds getting put into different bodies and shit

**Comment by JMWTurner** [comment]
I might take care of that when I'm done with the Strike team revamp. Some of the machines I've made for it might find some use in the Thunderdome. Case in point http://i.4cdn.org/vg/1492555351268.webm
