### ISSUE TITLE
Useless R-UST boards on Defficiency

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14567]
#### Description of issue

Defficiency comes with boards for the R-UST tokamak core and R-UST fuel injector but I'm pretty sure both of those are 'special' machinery like emitters.
I added descriptions to all the circuit boards recently and those two boards have the description for the base class board, so.

#### Server revision

Game: 8ba69c86d0640d3ba52c6f1cf9273507675fd936 
Patches: a761ebd6e1fd1fcdb30863a1e9a283b69875d588

**Comment by FudgePucker** [comment]
I don't think they are worthless, I remember using those boards last time I tried to set up the RUST, they just require t3 stock parts, meaning they are worthless, SCIENCE NEEDS THOSE MATS FOR GUNS FUCK YOU (I hate research and everyone that goes scientist just for R&D)

**Comment by SonixApache** [comment]
R-UST has it's own circuits defined in Cael_Aislinn/Rust/circuits.dm
I'll add descriptions to those, I guess.
