### ISSUE TITLE
Tooth Replacement Surgery

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14575]
As far as I know, we don't have this. Which is a shame because people with less than two teeth can't bite. Also missing teeth don't show up on full body scan.

I'm imagining a pretty easy surgery
>Target mouth
>Insert tooth, bone gel, cautery

**Comment by ComicIronic** [comment]
>can't bite with ol' chomper

![Ol' Chomper in the can](https://frinkiac.com/img/S04E17/443659.jpg)

What is this

**Comment by ghost** [comment]
wouldn't it be better as scalpel first?

**Comment by Shadowmech88** [comment]
We should also have a dentures item that can be worn in the mask slot and allows people with no teeth to eat while worn.

**Comment by ghost** [comment]
does losing teeth affect anything right now?

Last I checked there is no cooldown or time taken on food consumption

**Comment by Kurfursten** [comment]
According to @unid15 in the original PR, you can't bite if you have less than 2 teeth

The odds of losing that many teeth are pretty low though since few people aim for the mouth, you'd have to rage cage all shift

**Comment by Blithering** [comment]
Now all we need is for tooth type to affect bite damage, and you can have goliath toothed miners chewing through rocks faster than drilling.

**Comment by Kurfursten** [comment]
Need to be able to butcher fangs off spiders so that you can get literal poison fangs implanted

**Comment by ghost** [comment]
supermatter shard teeth for implant-induced matter eater

**Comment by Durgen** [comment]
cyanide capsule teeth when

**Comment by Blithering** [comment]
5% chance per bite of food taken to accidentally trigger the implant, 50% if clumsy

**Comment by Bpage5** [comment]
If tooth replacement is added, why not add more consequences to having missing teeth, like having food take more bites to eat, or adding a slurred/lisping filter to your speech?

**Comment by Kurfursten** [comment]
It would be kind of weird because there are 32 teeth but most foods have 4-5 bitesize, so let's say you did proportional speed. You'd have to lose 8 teeth before you notice any change in food eating at all. It's rare for someone to lose more than 1 or 2.

You are, in fact, more likely to lose a limb than a tooth.

**Comment by Shadowmech88** [comment]
What about various tooth loss-related maladies like dry sockets and such?

**Comment by Kurfursten** [comment]
Oh definitely. We have a pain mechanic after all.

**Comment by Blithering** [comment]
Could we also have a tooth extraction surgery? de-fanging vampires would be fun

**Comment by Shadowmech88** [comment]
>tooth extraction surgery

It's called a toolbox to the mouth.

**Comment by Blithering** [comment]
No, that's the spiritbreaker cure.

**Comment by Riekland** [comment]
Speaking of mouth related shit, do we have the ability to pull out teeth with wirecutters? Also, the tongue being an organ would be fantastic. We could have recipes for it, and you could silence your targets with a well placed slice. Mouths are the future of robustness, I tell you.

**Comment by Kurfursten** [comment]
Why stop with a tongue organ, we need a uvula organ to force vomiting and tonsils for airborne virus defenses.

**Comment by Shadowmech88** [comment]
Wirecutters wouldn't be great for tooth removal. You're thinking of pliers.

**Comment by Shadowmech88** [comment]
Also tongue removal wouldn't silence a victim, just give them a major speech impediment.

**Comment by Praecordia** [comment]
add gold teeth and silver teeth

**Comment by Kammerjunk** [comment]
Remember to brush your teeth once a shift!

**Comment by SonixApache** [comment]
ass replacement surgery first

**Comment by SonixApache** [comment]
#14945
ass replacement second, actually. #14972
