### ISSUE TITLE
LAssailant is garbage

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#14592]
It causes mobs to hard del because it keeps a ref to a mob forever unless the mob that was attacked is destroyed. That isn't conjecture, I checked.

We don't really use it, as far as I know, for anything but stat logs, and before that I don't know why it ever existed.
It isn't useful.
I'll probably remove it from the stats site at some point anyways.

We need to remove the LAssailant var. Why am I making this issue? Because I don't want to deal with it tonight and I don't want to forget how garbage it is. *And maybe someone else will do it for me*

**Comment by Shadowmech88** [comment]
In what way is it used for stats?

Could it be replaced with, for stat purposes, a var that holds information about the last assailant but not an actual reference to anything?

**Comment by gbasood** [comment]
That's the problem, to get the last assailant it's using the LAssailant var stored on the mob which is updated whenever (hypothetically) that mob is attacked.
The LAssailant var on the mob itself is the bigger problem because **ANY MOB THAT IS ATTACKED WILL KEEP A REFERENCE TO ITS ATTACKER EVEN IF IT IS QDEL'D** causing hard deletions
The stat collection thing I'm fixing myself.
