### ISSUE TITLE
how should ion pistols be obtainable

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14601]
we have ion pistols in the code and i think they would be good to add finally. should they be cargo, r&d, or hell, even both

**Comment by jknpj** [comment]
spessmat

**Comment by Lokiamis** [comment]
Deffo not cargo or RnD. Maybe xenoarch or an expensive ops item (cluster was right)

**Comment by Blithering** [comment]
I'd say make it a traitor item, possibly roboticist specific or something.

**Comment by ghost** [comment]
while im still partial to cargo/rnd, how would making it something in the RD closet be?

**Comment by SonixApache** [comment]
powercreep

**Comment by ghost** [comment]
should be R&D and require plasma

**Comment by Lokiamis** [comment]
No mass producible ion weaponry ever

**Comment by DamianX** [comment]
what are the arguments against not having them easily available?

**Comment by ghost** [comment]
perhaps making them require high tech and an NT disk, and having a decent mat cost, would prevent them from becoming mass produced every single round

**Comment by ghost** [comment]
and if your fear is this ruining malf rounds, ai can delete literally all research or just flat out blow up the lathe. and if they required high mat, research, and a data disk, the odds of a round going on to the point where the station would have these stockpiled 4noraisin before the ai goes delta seems unlikely. and an ion PISTOL wont do much good when all your air is replaced with plasma

**Comment by Blithering** [comment]
Concealable weapon that can disable comms, SPS, weapons, borgs, open lockboxes and all the other fun ion things really shouldn't be printable at a lathe

**Comment by ghost** [comment]
to be fair, you can make emp grenades with minimal effort in science, but i do see what you mean. a grenade is a lot less reliable than a gun.

**Comment by yclatious** [comment]
Adu, understand that the harder something is, the less people do it. Greyshit antags don't all hook up 12 welderbombs despite them very well being able to with relative ease because its harder work, most just act like retards, snip wires and robust people since its easier than station wide sabotage, Ions are potent as fuck and giving science even more shit is just a bad idea.

**Comment by Yelier** [comment]
ONE in the armory, maybe HoS locker instead. Perhaps a tator item that recharges like an ebow. I like the xenoarch and ops weapon ideas too.

**Comment by Lokiamis** [comment]
I made a mistake

**Comment by Gunosaguki** [comment]
Make it require large artifact research since that tech is basically not used at all

**Comment by yclatious** [comment]
Honestly, they just shouldn't be available for normal traitors and at most, itd be deathsquad gear/ert

**Comment by SonixApache** [comment]
give the nuke ops one (1)

**Comment by Blithering** [comment]
I can see them being useful for deathsquads, but ERT, security and nuke ops already have access to the rifles.

**Comment by IzayaChan** [comment]
give it to nukeops
FUCK BORGS

**Comment by PJB3005** [comment]
Issue with the rifles is that they're huge and unwieldy @Blithering

**Comment by Probe1** [comment]
Whatever is done has to be done with caution.

**Comment by Blithering** [comment]
Whatever is done has to be done with reckless abandon.

**Comment by Probe1** [comment]
I'll find you.

**Comment by Blithering** [comment]
![auex3xs](https://cloud.githubusercontent.com/assets/15067109/24833508/c2f3578e-1cc2-11e7-8fa0-1c9ec3961758.jpg)

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/24833518/4375cce0-1c99-11e7-95aa-66547683db64.png)

 >Affirmative Action Waldo

also bottom center with your github icon now GET BACK ON TOPIC

**Comment by Blithering** [comment]
Fair enough, I feel the bulkiness of the rifles was an intended tradeoff, we shouldn't be giving pistols out to anyone who already has direct access to the rifles as it would bypass said trade. (i.e. sec, ops and ERT)

**Comment by yclatious** [comment]
I feel like the ion rifles "encumberance" just makes it too unwieldy to properly utilize, yeah, you can store it in your suit slot but as sec or as nuke ops, you usualy put anything but a ion there because other shit is much more crucial to carry than a ion, even if ions are great. If you folks want to give them to nukeops/deathsquads/ert, which I believe are the only ones who should get them at all, id say its justified to allow them to use them in limited numbers because honestly, Ions are just too annoying to carry normaly for most players to consider them, atleast thats why I have seen in my  playtime, both from myself and observong others, unless its imperative, ions are not touched due to that.

**Comment by Hoshi-chan** [comment]
TC item available to nuke ops or traitors, high-level NT experimental research requiring rare materials (like plastic AND diamonds, or phazon if you wanted it to be _that_ rare), and maybe stick them in some kind of vault.

When I say "high-level research", I don't mean the typical stopping point for research, I mean weapons 7, materials 7, "beyond what people usually bother to do" research.

Also, if you make them a traitor item, maybe consider spicing them up a bit beyond just being handheld ion rifles. Aesthetically, I mean, not functionally.

**Comment by ComicIronic** [comment]
We can start out by testing them on nukeops default loadout to see what the powerlevel is actually like. I think this is a load of speculation otherwise.

**Comment by Exxion** [comment]
How many shots do the pistols get?
They should be able to fire like twice from a full charge, as the tradeoff for size, unless they're REALLY hard to get

**Comment by FudgePucker** [comment]
Maybe as a vault loot in a run down research station that is booby trapped with ion prox grenades and over run with cyber horrors and space spiders.
The ion pistol could be found on a corpse with a suicide note and a knife.
Other traps could be a toxins lab malfunction, with a plasma and O2 miner burning for an eternity, just for you to open a firelock and burn to death. The corpse that holds it could be surrounded by the ever burning fire in a safe room, they started the fire to protect themselves from cyber horrors and spiders, but ran out of rations and couldn't get out.

**Comment by ghost** [comment]
Nuke ops already get two rifles that fit in their suit storage and EMP based
There should be one in warden' locker and one in science. 
It should require power cells, basic gives it one shot super gives it two etc
Or you know, make flashes stun borgs in an AOE when used

**Comment by ghost** [comment]
Another idea is sticking one in the vault

**Comment by FudgePucker** [comment]
Problem with giving it to science is ~~fuck that entire shitty power gaming department~~ that the protolathe is a bloated feature sink.
