### ISSUE TITLE
Nightvision broke my game

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14608]
(WEB REPORT BY: dusty715 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
I put on nightvision to test it out, it broke the ui, then the map after taking 1-2 steps, and crashed the game 304 times until the nightivison effect stopped working and I took it off.

>What you expected to happen
Nightvision

>What actually happened
Borke game

>Steps to reproduce if possible
Put on nightvision while in syndacite shuttle thing

**Comment by PJB3005** [comment]
W-what.

**Comment by gbasood** [comment]
>Syndacite

So it's possible he doesn't know what he's talking about and exaggerates what "crash" means. Especially dubious of "304 times"
On the off chance he's not:
 - Toaster comp
 - Hardware accel not enabled

**Comment by ComicIronic** [comment]
Did you update your graphical drivers?

**Comment by nervere** [comment]
This has been reworked a lot since this issue, and there isn't nearly enough info to reproduce anyway.
