### ISSUE TITLE
AIs can still use Annouce verb while powered down

### ISSUE THREAD

**Issue by Banon13** [d3athrow/vgstation13#14618]
#### Description of issue

A powered down AI can still use the AI Announcement system.

#### Difference between expected and actual behavior

A powered down AI is dead so it shouldn't be able to do anything.

#### Steps to reproduce 

Beat the fuck out of an AI till it's dead
Use Announcement system

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by FudgePucker** [comment]
WOOP WOOP AI IS IS DEAD ASS BLAST USA MILLION BUTT MINEFIELD WOOP WOOP

**Comment by DamianX** [comment]
> controversial

???

**Comment by ghost** [comment]
Working as intended :^)

**Comment by SonixApache** [comment]
>couldn't find an existing issue about this

#14294

**Comment by ComicIronic** [comment]
Duplicate.
