### ISSUE TITLE
Why would I take a pintpointer?

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#14617]
Icons for a new drink, the pintpointer.
![pintpointer](https://cloud.githubusercontent.com/assets/15067109/24839746/42a94818-1d58-11e7-9dbd-55fd5e79acfa.png)
Suggested in the thread, has different icons indicating proximity to the bar.
download link for icons: http://s000.tinyupload.com/index.php?file_id=09947391294335289252

@Shadowmech88 volunteered to code it, how nice of him.

**Comment by ComicIronic** [comment]
Make this map wide and put them in the arrivals shuttle and it's golden.

**Comment by Shadowmech88** [comment]
I'd prefer that pintpointers pointed to the closest alcoholic drink. Pointing to the bar was going to be my fallback depending on how many pintpointers could exist before the former approach began using too many resources. There's definitely a theoretical limit, but I'm not sure what the practical limit would be.

Like, if the bartender would have to mix 1000 of them before the simple math operations started to tax the server, I think that'd be fine.

**Comment by kilozombie** [comment]
I think a good medium would be to point at the bartender, so you know who to MUG when you need more alcohol.
Only in niche circumstances would this have any real gameplay effects, but I think brewing a special drink to locate your cult/antag target is pretty fuckin' funny, and in line with the rest of spess.
(Also, the description should be "Why would you take this?")

**Comment by Kurfursten** [comment]
Cultists only target loyalty implanted crewmen for the sacrifice objective iirc

**Comment by kilozombie** [comment]
I've gotten made the sacrifice objective as a _trader_. So I dunno what exactly is going on.
To be fair, EVERYONE ELSE WAS DEAD at that point. It was a fucking insane round.
