### ISSUE TITLE
You can't butcher cockroaches

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14627]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
>General description of the issue
yeah title

>What you expected to happen
butcher roaches and start my homemade vodka company

>What actually happened
roaches dying in a single hit with remains impossible to butcher

>Steps to reproduce if possible
>kill roach
>try to butcher
>can't
i even tried to use the knife, all the fucking kitchen machines like gibber, meat spike, all-in-one grinder, processor

**Comment by TheFriggenSawbones** [comment]
NEEEVERMIND
you use toxin

**Comment by Exxion** [comment]
#14626
