### ISSUE TITLE
Surprise Pizza crate is OP

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#14623]
75 credits for 5 pizzas is overpowered
Cargo can out chef the chef with very little effort

ideas: 

- up the cost of the crate a bunch
- put it in a kitchen access locked crate, so cargo needs emitters for infinite pizza

**Comment by BobdaBiscuit** [comment]
Pretty sure it's entire purpose is to feed the station in the case of no chef.

**Comment by ComicIronic** [comment]
That shouldn't make it a chef replacement outside of desperate times, though. What is the standard pizza price?

**Comment by Kurfursten** [comment]
16 months ago vending machine prices were standardized (Getmore price = 66% * nutrition value; Dan price = 16.5% * nutrition value; Ramen at each is much more efficient pricewise at 10% and 2% respectively). At that time, the pizza crate was nerfed by raising its price from 15 credits to 75 credits.

@ComicIronic You get five random pizzas, which vary from 30-50 nutritiment = 450 to 750 nutrition each (for reference, a beef jerky packet is 6 nutriment = 90 nutrition); Starving begins at 150, you need to get your nutrition value above 150 to not take the speed penalty (hungry starts at 250).

Even if the pizza crate ($75) provided only one pizza and you got the worst one (30 nutriment), that would be dramatically better than buying from the Getmore vendor, where a similar amount of money ($60) gets you 6 nutriment.

I'm not taking a side in this, I'm just providing information. Perhaps an alternative but overlooked solution is to nerf the amount of nutriment in a pizza, which is crazy proportional to the work that goes into a pizza.

**Comment by yclatious** [comment]
People who order pizza were not going to eat at the chefs anyways, most chefs just pump out mediocre food, do no gimmick and expect people to gobble down on ambrosia jawbreakers and so on. If a chef does menus and other stuff, people will naturally come and eat but most chefs are neither skilled enough to pump out good food, charismatic enough to appeal to people with some sort of gimmick or give enough of a shit to broadcast said gimmick on comms and such, the second they do they get more customers, but they dont because they chose not to.

Fuck off with making a pizza crate 500 credits just because the chefs that play suck ass and then complain that people eat pizza when the food is shit, and why the fuck would you id lock a freezer crate, alongside with making the access requirement of chef since he should be doing anything but ordering fucking pizza, he should be making it himself.

Get a grip.

**Comment by Kurfursten** [comment]
Oops, some of my numbers were off. It has been a long time since I looked at pizzacode, if you refresh the numbers should be right now.

**Comment by JustSumBody** [comment]
Reminder that the ice cream machine is LITERALLY infinite nutriment for FREEE

If there's no chef, wrench that out into the main hall and wa la

**Comment by kilozombie** [comment]
Yeah food is already easy to obtain, no need to gimp the cargo pizza game. Plus, cargo pizza sucks compared to actual pizza created in the kitchen, because you don't get the bonus nutriment from all the individual ingredients that makes it extremely filling. Reward chefs with cooler food perhaps, don't hurt other people who are just trying to get a bite to eat (when 90% of rounds have almost no food in the kitchen)

**Comment by Riekland** [comment]
hint
if you don't want to be outdone by cargo, do what they do
cargo drags crates of high nutriment food to departments so they don't have to leave during red alert BY THE WAY DONT FUCKIGN ELAVE YOUR WORKPLACE ON RED ALERT YOU CUNTS
if the chef would just fucking deliver food without having to be told then this wouldn't be an issue

**Comment by kilozombie** [comment]
I need to get back to playing spess to teach all these chefs a lesson
Delivering food is near the top in terms of 'good things you should do to make people like you'.
You have food delivery bags for a reason, they pick up 14 food items like a plant bag does.

**Comment by Blithering** [comment]
How about putting in an order for pizza pings a signup list to ghosts, who get put into a pizza delivery guy and have to make and deliver the pizza manually?

**Comment by Riekland** [comment]
I guess
I would make it delivery drones with mommi non interactions laws, though, because you know what would happen

**Comment by yclatious** [comment]
That is the worst kind of stupid, the not even funny nonsensical stupid.

**Comment by kernikov** [comment]
![what is my purpose](https://cloud.githubusercontent.com/assets/5549060/24884858/0e8ef046-1e11-11e7-9c0e-88a062a8bba1.png)
>What is my purpose.

"You pass the pizza."

**Comment by yclatious** [comment]
Love of god, nobody tell the jew waifu he posted this, I don't want a 300 comment war about how rick and morty is a shit show.

**Comment by Riekland** [comment]
>>>/reddit/

**Comment by kernikov** [comment]
![xd](https://cloud.githubusercontent.com/assets/5549060/24885117/60ec48d8-1e12-11e7-9ac8-bf35057e71dd.png)

**Comment by ghost** [comment]
I don't really see how pizzas are an issue.  Botany or ghetto botany can throw robust harvest in a single tray with cabbages and feed the entire station easily in just a few harvests, and that is free.  anyone who is wasting 75 credits on pizzas is a fucking retard.  Hell, even if you make it 1000 credits... "AI law 2 order me a pizza crate!"  On a related note, who cares?  You won't die even if starved and there are a million and one ways around the slowdown/no regen starvation effects.  "b-but Harse, that takes effort!"  Well, just grab the box of crayons near primary and eat those.  It will keep you fed for the entire round.  Why are you trying to casualize the game and remove the retard traps like cargo pizza?

**Comment by RFultra** [comment]
Please don't ruin my meals on wheels gimmick metaclub

**Comment by ihadtoregisterforthis** [comment]
Make the pizzas more expensive by reducing the amount of pizzas per crate. Make a single order feed one or two people instead of one or two departments. 

What the hell does the drama tag mean?

**Comment by Durgen** [comment]
drama tag means the issue got posted to the thread and a bunch of people with pitchforks showed up

**Comment by PJB3005** [comment]
@Durgen no it doesn't.

**Comment by carshalash** [comment]
![image](https://cloud.githubusercontent.com/assets/16896032/24907445/a2746dce-1eff-11e7-92f1-89a093e6bdb6.png)

**Comment by SonixApache** [comment]
this is why food delivery bags exist

hire an assistant
dress them up in something nice
make them food bag your food to various departments

**Comment by ghost** [comment]
h-ha good thing xenobio can supply science with infinite food no need for pizza or leaving the department

**Comment by gbasood** [comment]
this has been something I've complained about since forever
Also not to mention
GUNS ARE LESS VALUABLE THAN ONE PIZZA

**Comment by FudgePucker** [comment]
Make the pizzas have a chance of being Dan pizzas. Oh boy 1 and 10 pizzas are poison, they are cheap for a reason.

**Comment by Blithering** [comment]
Discount Dan's Pizza style food disks, menthol cool flavour!

**Comment by Accipitermaris** [comment]
@yclatious 
I don't have an opinion on pizza crates, but to address the issue with chefs you mentioned:
I read the statement "skilled enough to pump out good food" as implying that there is more to producing good food than efficiently putting the correct portion of ingredients in the microwave, when I don't believe there is. If the chef can read the cookbook, the only real bottleneck in making some nice dish such as Turkey is supply, and if his skill is in growing the ingredients himself, then he's a capable Botanist, not a skilled Chef. The only meals a Chef can produce that require any creativity in this sense strictly fall under goofcooking, which probably wasn't what you had in mind. (Water Snack Bar Burgers, Lemon Cake Cakes, Sandwich Sandwiches, Pizza "Pies", and Birthday Cake Slice Cereal)

**Comment by kilozombie** [comment]
Skilled cooking is at least 50-60% prepwork. The better you are at prepping and getting your ingredients, and organizing them, the better you'll do as a chef in every single way.

The other half is serving your food, actually juggling your ingredients, and making sure you make your kitchen interesting, as well as things like delivering food or making your food hyper-nutritious or healing.

**Comment by yclatious** [comment]
Todays chefs lack efficiency, variety, prep work, botanist coordination and appeal. No appeal and people wont bother to stay or give half a rats ass, no variety without a specific gimmick and the same as before, no efficiency and people will just order pizza since there barely is any food by 12:10, efficiency without botanist coordination, the rarest of all of these, means you will be hampered because they are just weed smoking catatonics who can barely make 100 potency melons and as such, your food kinda sucks eitherway. Kilo already explained it in a good way.

**Comment by ReindH** [comment]
It doesn't really help that 9 out of 10 botanists go ambrosia "dude weed lmao" and ignore what you ask of them. Maybe if the HoP cared enough to shape them up.
But don't go and nerf cargo pizza for that reason unless you want angry engineers at your doorstep.

**Comment by mcgstyle** [comment]
Pizzas cost money, chef food doesn't.
Most of the station can be made redundant by cargo so I do not see the problem.

**Comment by gbasood** [comment]
I mean, that is the problem.
Pizza is a small part of it and it's much easier to change than the entirety of cargo.

**Comment by SonixApache** [comment]
why don't we just make shotguns edible
problem solved

**Comment by Killette2** [comment]
I leave for less than a month and this is what someone sends me? I wouldn't mind if someone borrowed my menu that's stored in the library, it's very realistic for the chef to compete with both vending machines and cargo.
