### ISSUE TITLE
Using a DNA injector in spessmart Triggers Alarm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14625]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Title says all. Using the DNA injectors you buy at spessmart IN spessmart will trigger an alarm

**Comment by Exxion** [comment]
No destroying merchandise
Even if you've already bought it

At least that's what I assume the thing is complaining about

**Comment by unid15** [comment]
Turns out my spessmart code is pretty spaghetti. In theory this shouldn't happen but it does :thinking:
