### ISSUE TITLE
Couches have shitty sprites

### ISSUE THREAD

**Issue by ultraplen** [d3athrow/vgstation13#14622]
![chrome_2017-04-10_21-21-58](https://cloud.githubusercontent.com/assets/20318196/24878793/dc937bf6-1e34-11e7-8626-5332817a5899.png)
![chrome_2017-04-10_21-31-39](https://cloud.githubusercontent.com/assets/20318196/24878883/27df748e-1e35-11e7-938a-26dca7041d00.png)

It would be great if someone could touch up the couch sprites. I could give it a shot but I'm worse than garbage at spriting, and the current couch sprites are evidence of that.

(The original sprites by Neinhaus are great, but my edits ruined them)

**Comment by praisenarsie** [comment]
your mouse cursor has a shitty sprite

**Comment by ultraplen** [comment]
its designer i dont expect plebs to understand it
