### ISSUE TITLE
Can't get Cockroach meat.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14626]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
48e58fc7f96aa9bb429844129da9ae189172b387 

>General description of the issue
You can't butcher cockroaches for their meat, it leaves a splat on the floor that you can't butcher

>What you expected to happen
to be able to butcher a roach

>What actually happened
cant

>Steps to reproduce if possible
spawn cockroach
try your hardest to butcher it

**Comment by ghost** [comment]
wooooow thanks unid

**Comment by ghost** [comment]
okay, turns out you have to spray them with toxin so they don't gib.

`/mob/living/simple_animal/cockroach/reagent_act(id, method, volume)
	if(isDead())
		return

	.=..()

	switch(id)
		if(TOXIN)
			Die(gore = 0)`

**Comment by Kurfursten** [comment]
>The ghetto solution for radiation is literally orders of difficulty harder to make than the normal solution for radiation and not documented at all on the wiki

What did @unid15 mean by this?

**Comment by jknpj** [comment]
this is just like monster hunter and i love it

**Comment by ghost** [comment]
It ain't so bad

>Find cockroach
>Feed it some food so it makes eggs
>Grind up the eggs for roach shells
>plant some potatoes in ghetto botany
>grind them up with a mortar and pestle
>Combine the roach shells, potato juice, and water to make greyshirt vodka

If you want roach meat, it's semi self sustaining

>Roach nibbles on food
>It introduces toxins to the food and lays eggs
>Grind up the nibbled food for toxins
>Spray it or pour it on the cockroach
>Dead roach for dinner

**Comment by Shadowmech88** [comment]
>kill roach with chemical that the roach itself deposited into the food it was eating

:thinking:

**Comment by ComicIronic** [comment]
It's not good at staying alive.

**Comment by Kurfursten** [comment]
Can you at least splash it with poison or does it need to be spray?

>Break into chemistry to steal the spray bottle but ignore the dispenser

**Comment by kilozombie** [comment]
Haha are you guys joking
Just pick up the cockroach and literally put it into a grinder

**Comment by unid15** [comment]
The logic was that if you hit a roach with a big item like a fire extinguisher there's not going to be much of it left intact, so instead of a small manageable corpse you get roach guts splattered all over the floor

I guess I'll make them gib only when excessive force is used

**Comment by ghost** [comment]
Nah nah nah, this works. Spraying them with pesticide should leave a body, whereas squishing with a newspaper won't leave you much.

Plus, we can do radroaches now

**Comment by kilozombie** [comment]
Yeah but literally just pick up the cockroach and put it in a grinder hahahaha what the fuck
Go in grab intent and drag it on yourself and it goes in your hand, it can be deep fried or made into cakes or grinded

**Comment by Exxion** [comment]
>grab intent

Fun Fact: It works on any intent except Help

**Comment by kilozombie** [comment]
Yeah but grab intent is objectively the best for this sort of thing because it won't punch simple animals accidentally

**Comment by Exxion** [comment]
But you also won't punch them if you don't suck at clicking

**Comment by kilozombie** [comment]
Sometimes BYOND bugs out and counts your click+drag as just a click

**Comment by kilozombie** [comment]
Wait wait, what the fuck?
You actually have to *butcher* the cockroach into *meat* to get cockroach shells? Why's there shells in the meat? unid what are you DOING
Just put the cockroach shells and nutriment into the cockroach's actual reagent container.

**Comment by Exxion** [comment]
Since the cockroach is a mob, that would almost certainly not work without additional code

**Comment by kilozombie** [comment]
Shit alright.
Well, I guess if this is the only option, the pest spray change will help.

**Comment by Shadowmech88** [comment]
Also simple_mobs don't have internal reagent containers like humans do.
