### ISSUE TITLE
Bunch of inhands dissapeared recently.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#14639]
Toolboxes and wrenches are one example.

**Comment by JustSumBody** [comment]
#14540 if I had to guess

**Comment by ComicIronic** [comment]
This might be the issue with the dmi being too big to save in DM.

**Comment by ghost** [comment]
Objects in belts or backpack slots also do not show up anymore, example the katana or the taser

**Comment by SkowronX** [comment]
Altering those specific dmis in any way shape or form should be an autoban from making prs.

**Comment by PJB3005** [comment]
Honestly we need to set Travis to check those files for md5 sum.

**Comment by jknpj** [comment]
I'm scared of opening that file in DM

**Comment by Exxion** [comment]
Don't.
Or at least don't save if you do.

**Comment by Lokiamis** [comment]
>#14540 if I had to guess

items_lefthand.dmi and items_righthand.dmi did not contain any of the missing sprites at least as far back as august

**Comment by Intigracy** [comment]
Yes, they did.

Opening it in DM deletes the ones that are over the DMI limit, saving it makes it save that way.

**Comment by Intigracy** [comment]
https://github.com/Lokiamis/vgstation13/blob/0ec450342b8ee11f1f07304fab12bf5bfff0dcce/icons/mob/in-hand/left/items_lefthand.dmi
before your PR it was 217 KB big

https://github.com/Lokiamis/vgstation13/blob/35e1d7448059018246b42b860648a8f14341e65a/icons/mob/in-hand/left/items_lefthand.dmi
after your PR it was 146 KB big

**Comment by SonixApache** [comment]
lookiiiaaamiiiiisssss

**Comment by SkowronX** [comment]
ban

**Comment by Blithering** [comment]
So the taser inhands are missing, I thought I just needed to update.

**Comment by ComicIronic** [comment]
Should be fixed, reopen if not.
