### ISSUE TITLE
Cult can't sac dead brains or something like that

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#14635]
#### Description of issue
Sac target suicided, got debrained by friendly malpractice doctor, tossed into space. Cult (much) later found brain, tried to sac, didn't work.
Chaplain had since gone into a different mob (posibrain), but the dead brain still contained his old brain mob.

#### Difference between expected and actual behavior
Gamemode becomes impossible to advance instead of just deleting the brain and spawning gibs or something like that and then completing the objective.

#### Steps to reproduce 
- Have Sacrifice objective
- Kill sac target, debrain
- (Toss away until it's a dead brain?)
- Try to sac the sac target

#### Specific information for locating

Cult gamemode (looks like it includes objectives):
`code/game/gamemodes/cult/cult.dm`

#### Server revision

Game: 45f48d6a26394c896845f3b62c1ac8ea9fc4ed3a 
Patches: a761ebd6e1fd1fcdb30863a1e9a283b69875d588 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DeityLink** [comment]
Legacy Cult issue, no longer a problem with Cult 3.0

**Comment by Kammerjunk** [comment]
didn't test anyway
