### ISSUE TITLE
DNA modifiers / Injectors leaking radiation?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14637]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Doing genetics is pretty much guaranteed to give you radiation sickness now within the time span of 3-5 DNA injectors. unsure if intentional or something is giving radiation that shouldnt be

**Comment by ghost** [comment]
if(istype(M,/mob/living))
			M.radiation += rand(5,20)

Injectors give you between 5 to 20 rads
