### ISSUE TITLE
Light tile remote doesnt change colors of the light tiles

### ISSUE THREAD

**Issue by str4t0s** [d3athrow/vgstation13#14646]
#### Description of issue

I tried to use light tile remote to change colors, but it doesnt do anything.

#### Difference between expected and actual behavior

I expected to be able to change colors of selected tiles with the remote.

#### Steps to reproduce 
1. grab light tile remote
2. select existing light tile emotes strapped to floor with the remote
3. try to change colors

#### Specific information for locating
light tile remote

#### Length of time in which bug has been known to occur
i just found it out

#### Server revision

Game: 4ac0ecb8147ffd4b4f5823ad1fb29df3f21a2ce1 
Patches: a761ebd6e1fd1fcdb30863a1e9a283b69875d588 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

**Comment by Exxion** [comment]
Did you click the activate button? Because it seems to work just fine.
