### ISSUE TITLE
Include Definition Law Information at Roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14648]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
I've noticed people have been getting confused at definition laws, most likely because its easy to assume that law order would override them at a glance. I suggest that we give this information at round/creation start for all sillicon types

**Comment by Ephx1** [comment]
Just put it in the rules.
That's it.

**Comment by SonixApache** [comment]
the obvious answer is to remove laws

**Comment by Ephx1** [comment]
Just remove silicons in general. Would stop a lot of headaches, _desu_.

**Comment by ComicIronic** [comment]
Law 4 one-human a SHIT

**Comment by Exxion** [comment]
First we'd have to agree on whether or not definition laws actually apply at low priorities.
I mean obviously they do, but some people don't seem to think so

**Comment by Allspice** [comment]
That would be better served, I think, by an agreement on what silicon laws actually are.
