### ISSUE TITLE
There is no sprite for the new capsule sold in the tradervend

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#14642]
It is invisible in game, and I have only been able to pick it up via alt-clicking a tile.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
The new what? gachapon?

**Comment by Durgen** [comment]
yeah

**Comment by Kurfursten** [comment]
I noticed that but I'm on a branch refactoring messy  APC code right now, if nobody fixes it before the end of the week I'll get to it

It's really easy though, just add a default icon_state, a new coder could do it

**Comment by Kurfursten** [comment]
Or better yet

See gashapon.dm at line 21? 
`b.icon_state = "capsule[rand(1,12)]"`

MOVE THAT CODE TO LINE 52

**Comment by SonixApache** [comment]
i had a dream about finding a gatchapon capsule in space after reading this
