### ISSUE TITLE
Feature request: Two seater pod

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#14657]
Pretty self explanatory from the title. Why go fuck off into space by yourself when you can go with a friend!

**Comment by PJB3005** [comment]
![](http://i.imgur.com/VIc764Z.png)

**Comment by SonixApache** [comment]
Pretty sure most other codebases have passenger seat modules for pods and mechs.

**Comment by Exxion** [comment]
You forget that our pods were coded from scratch in ten minutes by the chicken
