### ISSUE TITLE
Law implant

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#14651]
The greytide implant is pretty cool, but I think you could make it even better if it were some sort of implant that forced a lawset on a living being. You'd be able to configure it in any way you want, and the resulting person would be slaved to that lawset, same as a silicon. However, in terms of rules, a purged human would just go back to being a nonantag.

Could cost 7-8 TCs?

**Comment by ghost** [comment]
>human on keeper lawwset

**Comment by ComicIronic** [comment]
A cool idea, but I see a lot of problems with it. Without all the sillycon expectations, admining that kind of implant might be pretty difficult.

**Comment by Shadowmech88** [comment]
Would the implant have humans adhere to server rules regarding silicons IE "You can do anything as long as your laws do not prohibit it"?

**Comment by kilozombie** [comment]
Yeah it would be annoying to admin, requiring some robust logs and even then... there could be problems.

Same rules as sillycones, I suppose. Which are NOT "you can do anything as long as your laws do not prohibit it" when it comes to murdering random nonhumans on Asimov, for example.

**Comment by DamianX** [comment]
Or just make the objective for the implantee "Protect and serve" instead of just protect and you can law two him like sillycons

**Comment by JustSumBody** [comment]
One of the big benefits of greytide implant and thralling and such is that the person slaved is still a person and not a silicon. As such they're allowed to be a bit more "proactive" and less restricted by laws and stricter silicon rulings.

For instance, let's say you have a borg emagged to a tator. The borg CANNOT let the tator die as doing so would break their laws. So if there's a case where the HoS is stunning and gunning your one human, you HAVE to intervene and give away the game or you're breaking your laws.
Whereas a greytide implanted duder can wait until the dust settles and the body is forgotten about before dragging them to cloning under a new name and identity. 

It's a neat idea that might maybe fit a new gamemode though, where the expectations are a bit clearer.

**Comment by kilozombie** [comment]
Oh, imagine that. A few (maybe a higher percentage than other antag type) crewmembers at roundstart have weird and wacky lawsets randomly generated that might make them do horrible or strange things.
