### ISSUE TITLE
Socket Wrenches can unwrench overpressurized pipes without venting

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#14655]
#### Description of issue
When unwrenching an overpressurized pipe with a Socket Wrench, you can bypass having to vent the pipe completely by canceling your initial attempt, making it skip the venting and go straight to the pipe removal step.

#### Difference between expected and actual behavior
Presumably, interrupting the venting should interrupt the entire pipe removal attempt. Instead, it just interrupts the venting step. The removal step can still be canceled by a second interruption.

#### Steps to reproduce 
1. Attempt to remove an overpressurized pipe with a socket wrench.
2. Cancel your unwrenching attempt. (Either by switching your active hand, taking a step away from the pipe, dropping your wrench, etc.)
3. Watch as you cleanly remove the pipe without flooding the room with several hundred kilopascals of gas.

#### Length of time in which bug has been known to occur
I'm pretty sure this has been the case for at least a year now, if not even more. I keep telling myself to report it after round-end but I keep forgetting. Blame my goldfish memory I guess.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Pretty sure I've known about this for more than a year but never bothered to fix it.
