### ISSUE TITLE
Show-server-logs and related verbs occasionally cease to function

### ISSUE THREAD

**Issue by BobdaBiscuit** [d3athrow/vgstation13#14658]
#### Description of issue
The verbs badmins use to open the round logs in notepad can occasionally stop working at all, preventing banvalids from being claimed and metaclubs destroyed.

Also on Linux the verbs do absolutely nothing at all due to wine not liking how byond tries to open notepad. Apparently there's more admins other than me that wanted to use linux so this is almost an issue on it's own.

I did some code diving and there's a legacy system in place for if some madman is using byond 508 etc in which instead of opening notepad the server just uploads the log to the admins computer to a location they specify, this fixes the linux issue and will most likely remedy the occasional notepad issue on windows.

So a patchwork fix would be implementing an option box when using the verbs to pick what functionality to use, until we can get the actual issue sorted.

#### Difference between expected and actual behavior
**EXPECTED**
Verbs open the logs and ban valids can be claimed.

**ACTUAL**
The do diddly squid and we get deadmin requested for being shit at our job.

#### Server revision

b253a43204d1fdc66bb9871cd3bc81708fd12c3c 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
Can confirm. Using get-server-log does crash the absolute heck outta me. Same with the save chat log function on goonchat

**Comment by BobdaBiscuit** [comment]
From what I can tell from pestering some admins, I THINK windows 10 might be the issue.

**Comment by ghost** [comment]
I'm on windows 7 on both laptop and main computer, neither work. Don't think it's that

**Comment by BobdaBiscuit** [comment]
Oh I wonder if they are COMPLETELY fucked then, cause I haven't had an admin say they were using it fine.

**Comment by nervere** [comment]
theres an option to save file to computer now, no longer an issue
