### ISSUE TITLE
Pants for monkeys

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#14653]
I think that the athletic shorts should be wearable for monkeys, I believe that the monkeys do not like how inhumanely they are being treated having to wear monkey diapers when this server does not have poop.  I am sure that the monkeys will be much happier if they can simply have a lad run up to the athletic room and grab them some nice red shorts.

**Comment by carshalash** [comment]
Let the monkeys wear pants comic.

**Comment by ComicIronic** [comment]
🤡
