### ISSUE TITLE
We have have buffed radiation, no geiger counters.

### ISSUE THREAD

**Issue by DorfGuy1** [d3athrow/vgstation13#14661]
#### Description of issue
so we dont have any geiger counter items, this is not a good thing, cause now radiation will fuck you up

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Look as much as I want Geiger counters, they'll be a complete bitch to do due to how radiation works. You basically will have to rewrite it all (except for mobs) and hope you don't get a performance disasters (*cough* bay)

**Comment by Rattlederp** [comment]
doesn't tg have geiger counters?

**Comment by Shadowmech88** [comment]
We have two different systems for radiation, right? One based on distance and another based on whether you can see the thing giving off the radiation?

**Comment by PJB3005** [comment]
There's no systems for radiation. Period.

Everything that applies rads just loops over mobs in view (or range in some bizarre cases) and does an apply effect for radiation. Nothing more.

Singulo and SM are smart enough to also loop over all rad collectors and if they're without 15 tiles power them.

Oh yes by the way rad collectors working is binary based on distance, they either get perfect energy or they get nothing. Beautiful.

**Comment by ghost** [comment]
Okay, the current system for applying radiation means we can't piggyback off anything to get a reading of 'Oh fuck you're getting irradiated'

But, there is a halogen counter so you can see how much radiation a person has. it's an engineering PDA cartridge.

**Comment by Shadowmech88** [comment]
For the range-based irradiation, at least, we could make it loop through a slightly larger range in which to trigger geiger counters, but not actually irradiate mobs.

**Comment by ghost** [comment]
nonono, best way would be that if a mob is irradiated, or at least if an irradiation is attempted, the irradiation check checks to see if the mob has anything on it that could be used as a geiger counter, and tell it the information

**Comment by Exxion** [comment]
The problem is that doing that requires recursively checking the `contents` of everything in the mob.
Or checking the holders of all Geiger counters, which is... probably actually less bad

**Comment by Shadowmech88** [comment]
Yeah but then the geiger counter will only be capable of telling you that radiation is *currently* fucking your shit up.

I'd like geiger counters to be warning systems capable of helping you avoid actual radiation exposure by warning you when you get close.

**Comment by carshalash** [comment]
![image](https://cloud.githubusercontent.com/assets/16896032/25060189/fae59d88-21da-11e7-9225-e8e0f0ae0b75.png)

You're one sick fuck.

**Comment by ghost** [comment]
???

**Comment by PJB3005** [comment]
@Exxion virtual hearers for rads.

**Comment by ghost** [comment]
@Shadowmech88 So you're saying you want the geiger counter to detect radiation before you're in a radioactive area?

**Comment by Shadowmech88** [comment]
Yes.

**Comment by SonixApache** [comment]
https://github.com/Baystation12/Baystation12/blob/fc7fe166dad5a829e499b922d946718e2e90c824/code/game/objects/items/devices/geiger.dm

i want geiger counters

**Comment by FudgePucker** [comment]
There are only a few radiation emitters most of them in engineering.

If you are that worried about radiation remove the genetic power that makes you emit it. Fuck genetic powers, fuck this one in particular. Giving WMDs to shitters. This is the happiest mask only worse. Fucking ruin everything by just standing there, plausible denyability in admin helps.

**Comment by ghost** [comment]
Fudge is there something you want to talk about?

**Comment by FudgePucker** [comment]
I have never had a good encounter with a genetisist.
Abusing telekinesis xray and invisibility to be an immortal killing machine.
Fake injector to monkey me, didn't finish me off on the meat spike, blew the cover of cult round start without even using a charge of his starting talisman.
Invisibility xray remote interaction to blow up both of the chemical dispensers, one of them in my face, non antag, doesn't leave finger prints, ONLY GOT A DAY BAN FOR THAT FUCKING BULLSHIT.
And finally people abusing radiation to stand next to you and kill you by liver failure "hahaha what's wrong? What do you mean stay away?" Main use of the power is to be a giant shit.

Also fuck xray vision, most broken shit in the game, thermals were removed from meta's detective office for a reason.
Remove radiating and xray from genetics.

**Comment by PJB3005** [comment]
https://en.wikipedia.org/wiki/Salt

**Comment by Shadowmech88** [comment]
>thing killed me pls nerf
