### ISSUE TITLE
Drag damage and borgs is fucked

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14669]
![image](https://cloud.githubusercontent.com/assets/8468269/25071394/0e0448d4-22b6-11e7-868f-496754424ded.png)

I turbofucked something in #14535.
dragging someone who should suffer from drag damage damages the borg rather than the downed one

dragging ANYONE that has dragged someone that should suffer from drag damage spams the user with [you should probably not drag that someone] messages
That's an issue with pulling not being terminated properly, not an issue with me.

#### Server revision

Game: 9aa263f87b6ce3b683e8ab961fcb18df62f62ed2 
Patches: a761ebd6e1fd1fcdb30863a1e9a283b69875d588

**Comment by ghost** [comment]
serves you right, shitborgs
