### ISSUE TITLE
Dragging damages borgs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14674]
(WEB REPORT BY: mcgstyle REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
9aa263f87b6ce3b683e8ab961fcb18df62f62ed2 

>General description of the issue
Getting damaged as borg "4noraisin"

>What you expected to happen
Nothing

>What actually happened
You will take brute damage when dragging a downed/injured person as a borg

>Steps to reproduce if possible
Not sure yet, happens sometimes but not always

**Comment by SonixApache** [comment]
SHOULD ALREADY BE FIXED SINCE  #14670 GOT MERGED
