### ISSUE TITLE
Mass drivers don't really work anymore for small objects

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#14675]
When you mass drive something, ZAS interfers

Expected behavior
1. you put something in the mass driver
2. you hit the button
3. mass driver shutter opens
4. object gets launched into space

actual behavior
1. you put something on the mass driver
2. you hit the button
3. mass driver shutter opens
4. the object gets zassed towards the open shutter and slowly drifts out into space
5. the mass driver fires, but the object is no longer in position, and is drifting out slowly into space

coffins still work fine, but if you are trying to mass drive smaller items like GPS units, it is a major headache.

related issue https://github.com/vgstation-coders/vgstation13/issues/14354

**Comment by ghost** [comment]
Would putting airtight plastic flaps work?

**Comment by PJB3005** [comment]
One solution I can think of is to make blast doors be non dense as soon as they begin opening, then make the driver launch at the same time as the driver opens.

**Comment by Durgen** [comment]
the mass driver would have to start launching before the doors even opened
it takes a second for the animation to complete and the launch to happen

**Comment by Kurfursten** [comment]
This isn't really clear. What you mean is "the chapel mass driver doesn't work anymore", but since disposals mass driver is already in an airless environment, it isn't affected by ZAS

Can coffins use pipes so we could just set up the chapel like disposals?

**Comment by PJB3005** [comment]
@Kurfursten there's more than 2 mass drivers on the station and it's not like the only one affected is the chapel. 

Personally I think the issue name is fine.

**Comment by Kurfursten** [comment]
That's true now that I think of the bomb driver. Though, since it also has a bin it's less effected. +1 for bin viability

**Comment by SonixApache** [comment]
airtight plastic flaps in the blast door would solve a lot

**Comment by PJB3005** [comment]
Then I can launch people with the driver anymore.

**Comment by Kurfursten** [comment]
You can but they'd have to lay down/get slipped.

**Comment by Ephx1** [comment]
Maybe if people are going at a certain speed, they can get pushed through flaps?
Of course, dealing some brute damage in the process.

**Comment by Shadowmech88** [comment]
You could just make the blast doors block all airflow like the exterior mining doors do.

**Comment by ReindH** [comment]
Or the airlocks near the singularity, but do you really want to make an invisible air wall?
My immulsions are already ruined form those airlocks.

**Comment by Shadowmech88** [comment]
IC-ly, the air in the chapel's mass driver is kept from escaping by the will of God himself.

**Comment by Exxion** [comment]
Please don't ever suggest that ever again

**Comment by PJB3005** [comment]
IC-ly, the air in the chapel's mass driver is kept from escaping by the will of God himself.

**Comment by Exxion** [comment]
That's not the one I meant but OK
