### ISSUE TITLE
Weird terrible game-breaking mysterious bug HERE

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#14682]
So from what I can gather the X-ray gun can cause terrible round ruining bugs in the form of crashing everyones client. Happened last round and apparently a few days ago or something.

Also during the round someone got a Hecate with a weird name (from the syndie base vault) and shot it a few times.

It sounds like they both caused the crashes. They both leave those streaks in walls if you fire through them and in the past, with the x-ray gun at least, it's caused major sprite corrupting for walls.

**Comment by Exxion** [comment]
The sprite corrupting was fixed. At least mostly.
Not sure what could be going on with the crashes. Going to need more information.
When you say "everyone," do you actually mean everyone?

**Comment by TheFriggenSawbones** [comment]
This was on deff.
As far as we know, it happened around arrivals and on the asteroid. If you went there you'd crash.

One person claims they fired the x-ray gun on zlevel 6, which shouldn't matter I guess?

The other guy who had the Hecate fired it around arrivals, which is where the crashing took place. 
If anyone went to arrivals it'd crash their client until they were manually warped away.

**Comment by Exxion** [comment]
Only fired it once?

**Comment by TheFriggenSawbones** [comment]
twice, second time was near science however none of us checked to see if crashes happened there.

**Comment by Exxion** [comment]
Very strange.
Honestly I have no idea what's going on, but if it happens again and I'm available, please get me to take a look.

Has this ONLY happened on Deff, or just most recently?

**Comment by Exxion** [comment]
Also, what part of the asteroid?

**Comment by TheFriggenSawbones** [comment]
According to SpurdoSpardeFug the same thing took place on box after someone fired an x-ray gun towards arrivals. 

Also it's hard for me to say. Started with a section near the mining outpost and I think it expanded?

**Comment by gbasood** [comment]
Is there maybe a specific thing that the gun is hitting that's causing this?

**Comment by SonixApache** [comment]
X-ray beam going past the Z-level boundaries, maybe?

**Comment by Exxion** [comment]
Something to do with shuttles, if I had to hazard a guess.
Arrivals and the mining outpost.

**Comment by FudgePucker** [comment]
Can you get xray guns from xenoarch guns?

**Comment by Shadowmech88** [comment]
I believe Xenoarchaeology is the only source of X-ray guns.

**Comment by FudgePucker** [comment]
Well now that would be a problem then.
Its almost as big of a round ender as the super matter crystal

**Comment by nervere** [comment]
Doesn't seem to be an issue anymore + no reports of it since. The Hecate rifle also seems to be without issue.

**Comment by Exxion** [comment]
I was able to sort of reproduce this at the time IIRC, but it probably got fixed by some BYOND update at some point
