### ISSUE TITLE
Holodeck catbeasts can erase objects from existance

### ISSUE THREAD

**Issue by ThHuberResearch** [d3athrow/vgstation13#14688]
#### Description of issue
Anything you put on the holodeck catbeasts will be erased once you move them out of the holodeck.

#### Difference between expected and actual behavior
Stuff should not be erased, the catbeasts should keep the stuff you make them wear.

#### Steps to reproduce 
Load the holodeck zoo
Equip the catbeasts with stuff you want to erase. For example, put stuff in a backpack, put the backpack on them.
Drag the catbeasts out of the holodeck to make them despawn.
Reload the zoo, the catbeasts respawn but the stuff they were wearing is gone.
Reloading the zoo multiple times does not affect this, the stuff stays gone.

#### Length of time in which bug has been known to occur
First noticed yesterday

#### Server revision

Revision: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
Someone should replace them with a simple animal cat beast

**Comment by ComicIronic** [comment]
That wouldn't fix the general issue, it would just be a band-aid. Holodeck items should not walk off with anything inside of them.

**Comment by jknpj** [comment]
Yeah you can nullspace the disk using this, curious thing is: only the first catbeats can hold things.

**Comment by ThHuberResearch** [comment]
@jknpj 
Yes, they become weird zombie-like creatures after they reset. Their bodies exist but you can't do anything with them.

**Comment by Shadowmech88** [comment]
Holo-atoms should probably drop anything in their contents that isn't also holographic when deleted.
