### ISSUE TITLE
Holodeck animals can be transformed into "animal holder" by putting them in bolas or a cannon

### ISSUE THREAD

**Issue by ThHuberResearch** [d3athrow/vgstation13#14689]
#### Description of issue
The holodeck puppies and chickens transform into "animal holder" if you bring them outside inside another object. The one I noticed it with were the wheelchair cannon (load a puppy into it, fire it outside the holodeck) and the cable bolas (you can put the chickens in those).
Related: https://github.com/vgstation-coders/vgstation13/issues/14688

#### Difference between expected and actual behavior
The contents of the bolas / wheelchair cannon should be empty instead of "animal holder".

#### Steps to reproduce 
Make a wheelchair cannon
Load a corgi puppy from the holodeck into it
Fire the wheelchair cannon outside the holodeck
The cannon fires an "animal holder"

Make bolas
Insert chickens into bolas
Move bolas outside the holodeck
Examine will show the contents as: "A poorly made bolas, made out of a chicken and Pomf chicken, tied together with cable."
Cut the bolas with wirecutters: "You cut off the animal holder and the animal holder."
This results in "animal holder" objects on the floor that you can pick up

#### Specific information for locating

You cut off the animal holder and the animal holder.

#### Length of time in which bug has been known to occur

Noticed yesterday on the live server, tested today on test server

#### Server revision

Test server: Revision: d285a4411d86d707427ddbe1835ff4ae9ad5c086 
Live server: unknown, should be Revision: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
WE MEET AGAIN, ANIMAL HOLDER, MY OLD NEMESIS

**Comment by SonixApache** [comment]
What happens if you bring a box of puppies out of the holodeck?

**Comment by Exxion** [comment]
So wait.
The animal holder changes its name when the animal inside is deleted, so that means it knows it was deleted.
But it doesn't just delete itself?

**Comment by ThHuberResearch** [comment]
@SonixApache 

I tried the following:
I had a puppy in:
- a briefcase, held 
- a box in a backpack
- inside the backpack
- in a pocket

All four puppies vanished and no "animal holder" could be found. I emptied the briefcase, box and backpack on a table and couldn't find an animal holder

@Exxion 
I guess that is the case? 
HOWEVER, for cheese wheels this problem does not happen.

Put a puppy in a cheese wheel
Take the wheel outside the holodeck
Cut the cheese wheel
No animal holders anywhere

So far the cannon fires an "animal holder" and the bolas produce "animal holder" objects you can pick up, but cheese works.

**Comment by unid15** [comment]
I bet it's because cannons and bolas keep object references that don't get cleaned up, causing this behaviour

**Comment by Exxion** [comment]
Oh yeah
This would probably still be a problem even if the thing *did* delete itself
I mean... less of one, as the thing would have `invisibility` 101 and thus be impossible to see or interact with, but it would still get dragged back from `qdel()`etion
