### ISSUE TITLE
Vox Cryo Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14680]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
Upon being placed in the cryo pod as a vox The baldy human sprite displayed instead.  Now, I'm not a doctor, but I do not think that cryo is supposed to spontaniously turn voxes into humans and back upon removal from the cryo tube.

**Comment by ghost** [comment]
Cryo is trying to cure vox from being  birds

**Comment by PJB3005** [comment]
This is now my all time second favorite bug reporter issue.

**Comment by jknpj** [comment]
Need moar pics

**Comment by BarneyGumball** [comment]
![](http://i.imgur.com/PW3rm54.png)

Can't reproduce.
