### ISSUE TITLE
you have still have a sechud icon when you are invisible through invisibility spray

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#14691]

**Comment by Probe1** [comment]
Ditto on medical hud.

**Comment by jknpj** [comment]
Most likely ditto on AI tracking too.

**Comment by Durgen** [comment]
I encountered it when I was invisible, and I was wearing an invisible hard-suit, helmet, and backpack

**Comment by ihadtoregisterforthis** [comment]
I once spotted a stealth test dummy with an admin ID, because of the HUD indicator

**Comment by Shadowmech88** [comment]
This is not unexpected, since invisible spray makes you practically invisible rather than actually invisible, so that people can still click on you and such.

I'm unfamiliar with HUD code but maybe a check could be added so that HUD icons are not displayed on mobs whose alpha is `<= 1`?
