### ISSUE TITLE
Posessing Mob Masks Transports Ghost to Nullspace

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14699]
(WEB REPORT BY: knightkiller REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b

>General description of the issue
Posessing someone wearing a mob mask when they take it off drops you off in what I can only assume to be nullspace, that being a black void. Can't talk in nullspace either

>What you expected to happen
You either swap to posessing the one taking off the mask, or just stop posessing the dissapearing mob

>What actually happened
Screen turned to black void, no interaction possible with view screen, cannot talk either.

>Steps to reproduce if possible
1) Be ghost
2) Have someone put on mob mask
3) Posess the player controlled mob
4) Have player take off mask
5) Be sent to the void/nullspace

**Comment by Exxion** [comment]
Oh, you mean haunt, not possess
I was really confused
But also not at all because possess is awful

**Comment by Shadowmech88** [comment]
I plan to alter transmogrification at some point, which will prevent this from happening.

In the meantime it's not a huge concern because ghosts can just teleport to any person or area to get out of nullspace.
