### ISSUE TITLE
Antagonist roles resetting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14693]
(WEB REPORT BY: purplenum REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 

>General description of the issue
I set my antagonist roles to Always and hit submit. It stays that way for a few rounds, and then for no apparent reason it'll go back to being "No" for all of them after a few rounds.

>What you expected to happen
I expect it to always stay on Always unless I change it.

>What actually happened
It will occasionally reset to "No"

>Steps to reproduce if possible
Set antagonist roles to always and press submit. Check its status every round, find that after a few rounds its returned to "No"

**Comment by PJB3005** [comment]
dupe.
