### ISSUE TITLE
Clicking on the game screen defocuses the text bar at the bottom of the window

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14698]
(WEB REPORT BY: deadpoolj REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 

>General description of the issue
When I click on something in the game screen, I can't type in the text bar without having to click on it first

>What you expected to happen
I can esword someone while calling them a faggot

>What actually happened
I try to type but nothing shows up down there

>Steps to reproduce if possible
1. Click on anything in the game screen
2. Try to type say youre a fag
3. ???
4. FUCKALL

**Comment by SonixApache** [comment]
use hotkey mode faggot

**Comment by Riekland** [comment]
h*lla fucking epic """""""""""""""""""""""""""bug""""""""""""""""""""""""""" report my dude
