### ISSUE TITLE
blind MMi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14690]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
>having your brain removed and staying inside the brain during transfer to the MMi causes you to become blind

>not be blind

>i was blind, most likely caused because i didn't have my blindness updated as i transfered to the MMi since the brain is blind if you're inside of it

>try getting borged by a roboticist

**Comment by Shadowmech88** [comment]
#15275 and #15689 have additional information on this.
