### ISSUE TITLE
job name in occupation preferences

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14695]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
>can't change the name of your job

>to change my job name

>clicking the job name sent me to the new player options

>be me and click on a job name

**Comment by DamianX** [comment]
is the in-game report thingy suddenly shitty for some reason or is this issue alone shitty?

**Comment by ghost** [comment]
Probably report thingie

**Comment by Exxion** [comment]
No, people just replace the words rather than write under them
This isn't a new thing, though it has been happening especially often in the past few days for some reason

**Comment by PJB3005** [comment]
The template used is also God damn awful, why would you use quotes for headers.

**Comment by jknpj** [comment]
it happens to me randomly, i think it's a byond issue.

**Comment by nervere** [comment]
Doesn't appear to be an issue anymore.
