### ISSUE TITLE
Dosing someone with Chloral Hydrate a second time wakes them up briefly

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14694]
#### Description of issue
Injecting or feeding someone Chloral Hydrate knocks them out after a brief moment, but if you inject or feed them a second time they'll wake up again for a moment before collapsing, as if they'd gone back to the pre-sleep confusion+drowsiness phase.
This doesn't seem to repeat if you inject or feed them after the second time, though, but I might've just missed it.
It also doesn't apply using addreagent, so there's that.

#### Difference between expected and actual behavior
It should keep them knocked out regardless of if you inject or feed them it a second time.

#### Steps to reproduce 
1. Acquire test dummy.
2. Acquire Chloral Hydrate in a hypospray or container.
3. Inject or feed it to the test dummy.
4. Wait for them to collapse.
5. Inject or feed them it again.

#### Length of time in which bug has been known to occur
The last day.

#### Server revision
Game: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 
Patches: a761ebd6e1fd1fcdb30863a1e9a283b69875d588 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by despotate** [comment]
This is a result of all chloralings having a chance for you to be woken up for several seconds after you've been asleep for around a dozen seconds and has nothing to do with injecting or feeding chloral a second time

**Comment by DamianX** [comment]
That comment has always been wrong.
