### ISSUE TITLE
null name

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14692]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
>you have no name

>to have a unicode digit

>no name

>ctrl+backspace whilst in a popup menu such as a wizard name or a borg name. works with adminhelp too

**Comment by Exxion** [comment]
>Ctrl+Backspace

Is... is this a universal cancel button?
If so, how did I not know about it?

**Comment by PJB3005** [comment]
Shouldn't this kind of stuff have a check against empty strings? Is it writing a byte that isn't filtered as control chat?

**Comment by Riekland** [comment]
ctrl+almost anything results in meme letters all over the shop
I don't think you can even ctrl+a but don't quote me on it

**Comment by PJB3005** [comment]
Well yes but control characters should be filtered.

**Comment by clusterfack** [comment]
Makes you wish we used a custom input for every input in the game, would make sanitizing dumb shit like this much easier

**Comment by jknpj** [comment]
Fixed for borgs, not sure about wizards.

**Comment by nervere** [comment]
no longer an issue
