### ISSUE TITLE
Sec Escape Pod on Meta is going backwards

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14702]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
its trippy

**Comment by TheFriggenSawbones** [comment]
http://i.imgur.com/zsTbJc9.gifv
![](http://i.imgur.com/KAOGVg7.png)

**Comment by SonixApache** [comment]
There's also no fucking door, so if you're trying to treat someone with that sleeper and the pod launches, you're screwed.

**Comment by Duny-** [comment]
This was fixed and should be closed.

**Comment by Exxion** [comment]
Including the door part?
Actually that can be a separate issue if not
