### ISSUE TITLE
Hallucination needs a hard cap

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#14703]
#### Description of issue

People wanna be ghouls, they get as many rads as possible.

#### Difference between expected and actual behavior

This can achieve like I dunno a 23-28k hallucination value

#### Steps to reproduce 

Set a couple of people to like 23k hallucination, I dunno, maybe just one would work, and I think the server should come to a relative crawl.

#### Specific information for locating

Hallucination

#### Length of time in which bug has been known to occur

People didn't used to intentionally irradiate themselves to such an incredible degree.

#### Server revision

Game: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b 
Patches: a761ebd6e1fd1fcdb30863a1e9a283b69875d588 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
working on it now

**Comment by Shadowmech88** [comment]
Why would having a large hallucination value cause lag?

**Comment by nuklearcellphoneg** [comment]
It spawns a number of mobs for the hallucinations.

**Comment by nuklearcellphoneg** [comment]
All the lag was gone after hallucination was mass edited to 0.

**Comment by Shadowmech88** [comment]
Does the number of mobs spawned for a player increase as the player's hallucination value increases?

**Comment by ghost** [comment]
It's just a prob(3) if they are hallucinating, no other checks besides that

**Comment by Shadowmech88** [comment]
In that case, I don't see why a high hallucination value, in and of itself, would cause lag.
The problem may lie with hallucinating in general.

**Comment by ghost** [comment]
I've added a limit of 3 spooks to the list.

Now just gotta find a point as to where to lock the sleep divider at.

In other news, your brain on 40,000 hallucination https://webmshare.com/play/QY4Xa

**Comment by Intigracy** [comment]
It's clearly the sound effects causing the lag.

**Comment by Blithering** [comment]
Is it possible to have the limit in effect for all sources of hallucinations apart from spirirtbreaker?

**Comment by ghost** [comment]
Yeah, I can do that

**Comment by FudgePucker** [comment]
Why does radiation cause hallucinations anyways? Is that a real side effect of radiation poisoning?

**Comment by ghost** [comment]
fixed by #14705
