### ISSUE TITLE
bloodpacks appear in syringes

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14704]
#### Description of issue
Having syringes contain very little liquid makes a blood pack sprite appear
This might only work with certain liquids? It works with the slime mutation toxin

#### Difference between expected and actual behavior
>No bloodpack
>Uses correct overlay(?)

>Blood pack sprite appears

#### Steps to reproduce 
>Get syringe
>Draw from green core or maybe 1u of anything?
>See fucked up syringe

#### Length of time in which bug has been known to occur

A month I think

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by eplgr** [comment]
Oh, these mysteries.

**Comment by ComicIronic** [comment]
No doubt the bloodpack is the sprite with no name in that DMI, and it's defaulting to it.
