### ISSUE TITLE
Ore Processor Console UI Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14709]
(WEB REPORT BY: rhimrifer REMOTE: 172.93.109.202:7777)
Revision: 595c120ced5722ff3e9ebcf0df7fd1bc2fe5045b

>General description of the issue
Twice I've had the Ore Processor Console's main control(Point reclaim, disable/enable) section disappear when using it

>What you expected to happen
UI to function normally

>What actually happened
Part of the UI disappeared

>Steps to reproduce if possible
Its only happened twice, but I think circumstances were about the same:
-Have machine hold large amount of ore
-Insert ID
-Maybe push a few buttons
-???

**Comment by DamianX** [comment]
Completely my fault, but it's not actually disappearing, it's just moving to the bottom of the window. I think.
PR coming up.
