### ISSUE TITLE
AI restorer bug

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#14715]
I unloaded ion rifle shots into an AI in order to teach it a lesson and scare it straight by just restoring it afterwards like usual. When I popped the did ai into the intellicard and restored and tried to bring it back into the round though, nothing really worked or gave them any prompts to re enter.

**Comment by SonixApache** [comment]
Need to be more specific.
AI was dead, got moved into the card, then you stuck it in the restorer?

AIs don't get a prompt for being revived, they just return to their body and It Works™ when they're functional.
