### ISSUE TITLE
Feature Request: Nametag for animals

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#14712]
What happens if you grow a strong bond with a monkey or a chicken that you stole from botany or genetics? Do you just keep it named chicken (187) or monkey(83) for the rest of the shift? What about the poor xenobilogists who grow slimes and don't get to name their dank pets after giving their docility potions? We should have the ability to have our pets have names on this server, make spess pet friendly again

**Comment by Shadowmech88** [comment]
You can use hand labelers on animals.

**Comment by carshalash** [comment]
Sweet
