### ISSUE TITLE
Ion rifling an ai core gives you the ability to call the shuttle through the ai

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#14720]
I forgot my most favourite bug from last night, every time I shot it the pop up to call the shuttle came up, I asked dragonbro what the fuck was going on and apparently the logs said the ai did it.

**Comment by Exxion** [comment]
What in the endless fuck?

**Comment by carshalash** [comment]
It was the best one of them all.

**Comment by ghost** [comment]
What the fuck

**Comment by Intigracy** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/silicon/ai/ai.dm#L437

**Comment by Intigracy** [comment]
Though you getting a popup is obviously not intentional.

**Comment by carshalash** [comment]
I was the person ioning and got the popup.

**Comment by Exxion** [comment]
Oh god damn it I just figured it out
I bet the shuttle call proc uses `usr` where it shouldn't

**Comment by PJB3005** [comment]
> I just figured it out

What it took you this long to realize?

**Comment by Exxion** [comment]
Yes
That is what I said

**Comment by PJB3005** [comment]
Pffff.

**Comment by Exxion** [comment]
Didn't see you saying anything about it

**Comment by gbasood** [comment]
Why the 
FUCK
does that proc use `usr` ever
