### ISSUE TITLE
Shunted malf AI can't blow the nuke.

### ISSUE THREAD

**Issue by ReindH** [d3athrow/vgstation13#14729]
#### Description of issue
Malf AI can't nuke if they shunt.

#### Difference between expected and actual behavior
Expected the station to explode by pushing the button.

The button was unresponsive so I shunted back to core, the button disappeared.

#### Steps to reproduce 
Shunt before the timer counts to zero, push button for nothing.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Fruktlimpa** [comment]
Is this really a bug tho? Isn't it simply the trade-off from shunting? I mean you still win, just a minor one.

**Comment by ReindH** [comment]
Then don't let the nuke icon pop up to taunt you.

**Comment by pedr69** [comment]
i believe this is fixed and can be closed @Kurfursten
