### ISSUE TITLE
Vox trader TG action figure has no sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14724]
(WEB REPORT BY: yclat REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The trader action figure you get in the box via arcade has no icon

>What you expected to happen
To see trader pox

>What actually happened
Invisible trader pox

>Steps to reproduce if possible
Play arcade until luck blesses you with the box, hope it has a trader with no icon, see it has no icon

**Comment by Exxion** [comment]
Usually the newer would be closed when there's a dupe, but #18178 has (marginally) more information
