### ISSUE TITLE
Hulk Screams go through Disabled headsets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14731]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
I've noticed you can disable the speaker on your headset and you will still scream into it when punching stuff as hulk

**Comment by Intigracy** [comment]
speaker =/= mic

you can't disable the mics for headsets iirc

**Comment by Killette2** [comment]
Screwdriver disables headset mic

**Comment by SonixApache** [comment]
screwdriver removes the encryption keys, does it turn it off afterwards?

can just change the frequency to stop yelling over common

**Comment by Gunosaguki** [comment]
Really? when you disable the speaker though you still recieve sounds and cant use ; anymore

**Comment by gbasood** [comment]
Speaker is just the earpiece that you hear comms over
Mic can't actually be disabled afaik

**Comment by Gunosaguki** [comment]
Point remains i couldnt ; while it was disabled. perhaps thats a different bug entirely?

**Comment by Shadowmech88** [comment]
Are you sure that you weren't actually sending radio messages and just couldn't *tell* because your headset speaker was off?

You won't get the green message in the chat bar if your speaker is disabled, since that message comes through your radio.

**Comment by Gunosaguki** [comment]
I was still hearing other people through radio

**Comment by Shadowmech88** [comment]
You were hearing other people through your headset while its speaker was disabled?

**Comment by Exxion** [comment]
Probably an intercom or something

**Comment by Shadowmech88** [comment]
Shouldn't he have been able to hear what he was saying over the radio via the intercom as well, in that case?

**Comment by Gunosaguki** [comment]
Yeah i wasnt carrying a radio of any sort. And i was frequently out in space so I wasnt near any intercoms

**Comment by gbasood** [comment]
It's entirely possible that the hulk scream does snowflake things that doesn't check if the speaker is actually on before showing the player who is screaming the scream message or something.

What we REALLY NEED are proven steps to reproduce.

**Comment by Killette2** [comment]
On a similar note, a good tip for hulks is to steal a muzzle from medbay/perma and wear it when you want to hulk smash around so you don't scream, but you can keep your headset on.

**Comment by gbasood** [comment]
`sood has created a PR: Makes hulking out break muzzles`

**Comment by Killette2** [comment]
DON'T YOU DARE, IT'S LEGITIMATE STRATEGY!

**Comment by gbasood** [comment]
`sood has created a PR: makes hulking out break all clothing and drop in hands`

**Comment by Killette2** [comment]
Will it spawn you purple shorts?

**Comment by ComicIronic** [comment]
`sood has created a PR: makes hulking out give you a 30-day ban for powergaining`
