### ISSUE TITLE
Gyro beverage does not display sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14739]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
Similarly, the gyro beverage does not sprite properly upon being created.  I will try to come up with a list of non-sprite changing beverages but it appears to primarily be the cafe ones.

**Comment by Rattlederp** [comment]
are you putting them in a mug or a drinking glass? A lot of the cafe ones only work with a mug
EDIT: ...as Blithering pointed out on your last issue
