### ISSUE TITLE
upgraded Service Borg Large Beaker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14744]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
>large beaker can't be put into machines like a chem dispenser

>be able to put it into machines like a chem dispenser

>can't put it in

>try to put it in

**Comment by Exxion** [comment]
I... think that's intentional? I don't know, really

**Comment by jknpj** [comment]
intentional, i know, it sucks.

**Comment by Shadowmech88** [comment]
It's intentional because I didn't want upgraded service borgs to be able to become pseudo-medborgs.
The beaker can still be placed into children of the chem dispenser like the drink dispenser, though.
