### ISSUE TITLE
Space Mountain Wind tag on soda machine bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14753]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
>The space mountain wind option on the soda fountain is bugged and moved down from where it should be, leaving a seemingly blank option.

**Comment by gbasood** [comment]
is this NanoUI and having overflow non-hidden like in #14436

**Comment by Exxion** [comment]
Probably

**Comment by Eneocho** [comment]
doesn't seem to be a thing anymore
