### ISSUE TITLE
Motorized Wheelchair cell usage is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14754]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
cc5cd8c387ca0fae9f66061196d8627ac9bbca33 

>General description of the issue
The way the motorized wheelchair draws power from the cell is flawed, leading it to run endlessly

>What you expected to happen
Should the wheelchair's cell charge be below the consumption rate, it would stop working

>What actually happened
It can run along nicely and infinitely on 1 charge (Movement consumption is 2), thus leading to unlimited speedy wheelchair usage

>Steps to reproduce if possible
Literally just ride around in the wheelchair, watching the cell charge usage

**Comment by ghost** [comment]
This stemmed from an idea where the medical malpractice could potentially use cell charge each time it would run somebody over (Moreso if the rider is fat, and if the person being ran over is fat) and testing it
