### ISSUE TITLE
Light replacers dont fit in toolbelts as advertised.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#14768]
#### Description of issue
In a toolbelt's item text upon inspection it states that a light replacer fit inside of it but upon trying to place one inside you find out they don't fit.

#### Difference between expected and actual behavior
Light replacer gets a too big messege instead of being placed inside.

#### Steps to reproduce 
Try to put a light replacer in a toolbelt

#### Server revision
Revision: 7b496ed8fdeb170c69a5033cb6012634fd5f4ad4

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
It's probably in the allowed list, but has a `w_class` too big to fit
Solution: Remove it from the allowed list

**Comment by Kurfursten** [comment]
rather, remove it from the description instead

since the CE belt gets the same list plus more, its larger size limit allows it to hold the light replacer
