### ISSUE TITLE
Moving out of welded locker message spam

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14767]
#### Description of issue
if you try to move out of a welded locker it spams the message and crashes your game

#### Difference between expected and actual behavior
>move in locker
>message shows once

>move in locker
>BYOND HAS STOPPED WORKING

#### Steps to reproduce 
>get stun welderlocker spaced
>try to move

#### Specific information for locating

locker

#### Length of time in which bug has been known to occur

probably a while

#### Server revision

![image](https://cloud.githubusercontent.com/assets/22992659/25567573/71a95eaa-2db6-11e7-83f1-8c559ecc9b06.png)

first time this has happened i think with locker
it's a common issue with trying to move while restrained

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
cooldown on it won't budge to fix
