### ISSUE TITLE
Blindness doesn't work correctly with far sight.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14779]
(WEB REPORT BY: sirskeleto REMOTE: 172.93.109.202:7777)
>General description of the issue
When having farsight and blindness, the outer edges are visible

>What you expected to happen
I'd be blind.

>What actually happened
I was only able to see in a circle around my avatar and also the rim on the edge of the screen.

>Steps to reproduce if possible
Get blindness and farsight.

**Comment by Exxion** [comment]
I'm pretty sure this has been reported a trillion times before but I'm too tired to go find an example right now

**Comment by Shadowmech88** [comment]
Are vision overlays placed relative to where the camera is focused, or at the corner of the viewbox?
If the former, could we just make the vision overlays incredibly large so that they still fill the screen when view size is increased?

**Comment by Exxion** [comment]
I believe it's the latter, but I don't think it would be hard to change
But a better solution would just be to use BYOND's built-in tiling of screen objects to make the overlay infinite
(Have just the visible circle part be in the center of the screen and infinitely tile just black squares elsewhere)
(I'm almost certain you can do that)

**Comment by PJB3005** [comment]
Or just make a hook for when view size changes and use transforms.

**Comment by Exxion** [comment]
I mean... that's both harder and worse for performance, but I guess you COULD

**Comment by PJB3005** [comment]
Nah I don't think it would be.

**Comment by Exxion** [comment]
I mean it just is.
What I suggested: Have two objects (one of which already exists). Assign a string to a variable for each object. Let the client handle the rest.
What you suggested: Set up events and make the server edit transforms whenever someone's vision changes.

**Comment by PJB3005** [comment]
Editing transforms is cheap as hell and vision changes are rare.

I had to do the same thing when porting /vg/lighting to TG before I realized why I needed the crap workaround. It's fine.

**Comment by Exxion** [comment]
I didn't say it was awful. But why bother with all that when you can get exactly zero serverside performance cost for less work?

**Comment by PJB3005** [comment]
Actually BYOND does chug at large icons so.

**Comment by Exxion** [comment]
The icons would be *smaller* than the current ones.

**Comment by ComicIronic** [comment]
Stop theorycompiling and someone create a performance test.

**Comment by Exxion** [comment]
Honestly the performance impact would be negligible either way. I'm just arguing on principle.

What actually *is* important is that the two solutions aren't equivalent. Mine would keep the visible area the same regardless of sight distance while PJB's would scale it.
Personally I think since you're *blind* mine is correct, but what do others think?

**Comment by Shadowmech88** [comment]
Personally I don't think blindness should *have* a visible area. It should be like wearing a blindfold, except you can mouse over objects adjacent to you to see what they are.

Are there any other view overlays besides blindness that impact gameplay rather than just aesthetics?

**Comment by Exxion** [comment]
Bad eyes and pain

**Comment by Shadowmech88** [comment]
The bad eyes overlay is blocky, right? It's not a halo like the blindness overlay is?
In that case, wouldn't transforming it screw with how the edges of the overlay perfectly overlap the tile grid?

**Comment by Exxion** [comment]
Yes
