### ISSUE TITLE
Advanced Security Camera Computers Irreparably Break When Camera(s) are Deactivated

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#14784]
#### Description of issue
When a security camera is disabled, the Advanced Security Camera Computers break such that only 0-2 random camera(s) may be selected and remotely viewed through via the interactive interface, when in reality, far more cameras are operational. This can be verified by using the regular Security Camera Computer to compare it to the Advanced Security Camera Computer interface when this bug is in effect.
This bug is shared across all players in the game and is shared between all Advanced Security Camera Computers. As of the writing of this report, the text only mode of the Advanced Security Camera Computer is bugged so that nothing is displayed when this button is selected, so this mode cannot be used as an alternative to the interactive mini map.

#### Steps to reproduce 
1. Disable a security camera with wirecutters.
2. If the computer isn't broken, try repeatedly cutting and mending the Power Link Light multiple times.
3. If the computer still isn't broken, try disabling around 5 or 6 security cameras. 
4. Go to the brig and use an Advanced Security Camera Computer. It should only display somewhere between 0-2 random cameras on the interface, despite there being far more operational cameras.

#### Length of time in which bug has been known to occur

Approximately 1 Year and 2 Months.
The first Open Issue I see reporting this bug was submitted in March 25, 2016, by gbasood: https://github.com/vgstation-coders/vgstation13/issues/9035

#### Server revision

Revision: 13a551835d2e8c7968703a5d242b26da2bf571e3 

#### Issue bingo

- [x] Issue could be reproduced at least once
I reproduced this issue twice on the test server.
- [x] Issue could be reproduced by different players
To my understanding, other players are aware of and have reproduced this bug.
- [x] Issue could be reproduced in multiple rounds
I have experienced this issue 3+ times in regular rounds, and I have reproduced it twice on the test server.
- [x] Issue happened in a recent (less than 7 days ago) round
I experienced this issue today.
- [ ] [Couldn't find an existing issue about this]
When I Ahelped about this issue, the responding Admin said that it was acceptable to file a new one.

Thanks for reading!

**Comment by PJB3005** [comment]
Hey look it's a dupe.

😂🔫

**Comment by Accipitermaris** [comment]
Sorry! I thought it was fine to open another issue.

[23:07:24]ADMIN: HELP: Accipitermaris/(Osbert Sealis): no I mean the advanced security camera interface. it bugs out so that when a single camera gets cut on the station, the interface breaks for the rest of the round - heard by 1 non-AFK admins.
[23:07:46]ADMIN: PM: Zealotron/(Sawbones)->Accipitermaris/(Osbert Sealis): oh uhh yeah that's metagaming. Bug report that too if you could
[23:07:55]ADMIN: HELP: Accipitermaris/(Osbert Sealis): aight - heard by 1 non-AFK admins.
[23:11:51]ADMIN: HELP: Accipitermaris/(Osbert Sealis): Uh... sorry for being a bother again but, would it be appropriate to make another bug report if there's already one on the github? But the report in question is kinda old https://github.com/vgstation-coders/vgstation13/issues/9035 - heard by 1 non-AFK admins.
[23:12:14]ADMIN: PM: Zealotron/(Sawbones)->Accipitermaris/(Osbert Sealis): it's fine

**Comment by PJB3005** [comment]
Don't worry it's fine.

The reason I used 😂 🔫 is because this is one of the most awful and "nobody wants to fix it because it'd require writing a new UI framework" tier bugs, but it's been reported dozens of times.
