### ISSUE TITLE
Pods clipping thru walls via Tubes

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#14787]
![1](https://cloud.githubusercontent.com/assets/6540760/25747862/0149787e-3177-11e7-8bb3-0b62b32495de.png)
![2](https://cloud.githubusercontent.com/assets/6540760/25747864/02a30514-3177-11e7-8874-8f170fdae102.png)

**Comment by nuklearcellphoneg** [comment]
I've had to tele a lot of people out of corners with diagonal tubes on them before, I guess because the tube can push them into that corner.

In this case, since pods cover two turfs, I guess the pipe pulls it 'behind' the tube, which is the rwall, and it clips through.

**Comment by PJB3005** [comment]
@nuklearcellphoneg spot on.

**Comment by Kurfursten** [comment]
Yeah, I've seen this happen a lot. Tubes are a nightmare.

**Comment by PJB3005** [comment]
Literally to fix tubes all you need to do is make them use `Cross` instead of `Bumped`

**Comment by SonixApache** [comment]
the obvious solution is to remove tubes

**Comment by nuklearcellphoneg** [comment]
^

**Comment by nuklearcellphoneg** [comment]
Here is the extent of my interactions with tubes over the years:

2013: Those look cool, I wonder what all you can do with them??
2014: What are these tubes even f-- oh someone got stuck behind them and I don't have the flag to delete them.
2015: Someone is stuck there again, better teleport them.
2016: Someone is stuck there again, better teleport them.
2017: Oh you can cheese through walls using a pod and tubes, how horrifying
