### ISSUE TITLE
Special Roles Reset

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14796]
(WEB REPORT BY: serwind REMOTE: 172.93.109.202:7777)
Revision: c9581ebb295c1f7abbaf7c1ee7400b831671253c 
>General description of the issue
It appears that upon inspecting the special roles of a character I had been playing for several rounds that the selected options of (always) have somehow reset to (no). I am not quite sure as to the reason for this but it is most assuredly a bum tickler.

>What you expected to happen

For the special roles to function correctly, to be quite honest with you my friendly so close I might call him family.

>What actually happened

The opposite of the thing that was suppose to happen unfortunately. What's suppose to happen is that the setting you select is suppose to remain the same unless you change it. Perhaps it is an intentional feature but the current iteration of this feature has it doing the complete opposite of that. 
>Steps to reproduce if possible

Playing the game from time to time, especially when you want to be an antag and have a root tootin good old time with your fellow lads from the space station 13 video game.

**Comment by clusterfack** [comment]
Dupe 
https://github.com/vgstation-coders/vgstation13/issues/7686
