### ISSUE TITLE
Should Forcewall Reflect Projectiles

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#14799]
I saw a post in the thread that suggested a projectile-reflecting spell, and figured that since we already have a barrier spell of sorts, they might be good together.

Would it make forcewall too strong, or just right?

**Comment by ghost** [comment]
maybe an upgrade could give it

**Comment by ghost** [comment]
Now that you can't spam force wall it should reflect projectiles, people would only use it for memes so giving it a use will be nice

**Comment by carshalash** [comment]
A good question would be whether it should have an identifier or not for when it has the projectile reflection upgrade or whether it should just be a base upgrade to the spell.

**Comment by Blithering** [comment]
Upgrade would be a good idea, and you can make the wall spawned a different colour to indicate it's reflecty. Would you be able to take a crack at fixing laser reflecting if you're working on this?
