### ISSUE TITLE
FUCKING CODERS CAN'T CODE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14795]
(WEB REPORT BY: serwind REMOTE: 172.93.109.202:7777)
STEPS TO REPRODUCE ARE TO PLAY THE GAME BECAUSE THE FUCKING SPECIAL ROLES KEEP RESETTING I AM FUCKING TRIGGERED PLEASE FIX IT IMMEDIATELY ALSO I DEMAND AN APOLOGY.

**Comment by PJB3005** [comment]
Fuck off.
