### ISSUE TITLE
Defibrillator Functions on Races Without Hearts

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#14807]
Skeletons, for example.
It just doesn't make sense.

**Comment by ghost** [comment]
we have plenty of things that don't adhere to a species physical attributes.

Diona, skeletons, and plasmamen can write blood runes, all with their own special species blood colour

**Comment by ghost** [comment]
Does CPR check for lungs?

**Comment by ComicIronic** [comment]
What color are skelly runes, white?

**Comment by Megamaw** [comment]
as someone actively advocating for skeletons to be less underpowered, i still think making them unable to be defib'd and making them unable to make runes makes perfect sense as a balance change.
