### ISSUE TITLE
Special Roles Resetting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14800]
(WEB REPORT BY: serwind REMOTE: 172.93.109.202:7777)
Just wanted to update on this because there was some debate as to the cause. Some seemed to think it was from changing job roles, but I just changed job role priority, and my special roles did not change.

FIX IT CODERS.

**Comment by Killette2** [comment]
Yeah I was gonna report this. It happened to me when I was readying up :(

It even happened right after I fixed it! Where I put my antag roles back on, saved them, declared ready, double checked my antag roles and they were all unchecked again! I feel left out from this bug :'(

**Comment by clusterfack** [comment]
Still a dupe
#7686
