### ISSUE TITLE
Corncob pipe non funtional

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14802]
(WEB REPORT BY: stiphs REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by PJB3005** [comment]
We should be able to ban people in game for submitting shit bug reports holy shit.

**Comment by Exxion** [comment]
Dude he just clicked the button too soon. Look, there's a fine one submitted by the same guy with the same title right above it.

**Comment by PJB3005** [comment]
@Exxion when I made that comment there wasn't.

**Comment by Exxion** [comment]
Oh
Still seems rather harsh
