### ISSUE TITLE
Tactical Light Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14812]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

eb1807fff6855c82e8da5238bd58e0809da19dc2 

>General description of the issue

Tactical Light doesn't stick to most hats

>What you expected to happen

Ultra tacticool head lighting action with fashion

>What actually happened

no lights u u u u unless you like gay hats or helmets :^)

>Steps to reproduce if possible

get hat, get light, try to put together

**Comment by Anton-Kr** [comment]
wysi

**Comment by Riekland** [comment]
from what I can tell it's just a little tan square that goes on the same part of all the hats it fits on
but I dont fucking know

**Comment by Exxion** [comment]
It almost certainly is, knowing how accessories work

**Comment by Megamaw** [comment]
@IsdatAfamas wysi? what's the s stand for?

edit: nevermind i'm dumb

**Comment by Exxion** [comment]
Oh also the tactical light toggle plays a sound and has no cooldown, so you can wreck people's ears with an autoclicker

**Comment by Megamaw** [comment]
would that cause issues on the server's performance or just on everyone's hearing

**Comment by Exxion** [comment]
Just the hearing

**Comment by SonixApache** [comment]
only tactical helmets come with the tactical mount required to attach a tactical light

**Comment by ComicIronic** [comment]
Tactical design to avoid spam

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Fixed
