### ISSUE TITLE
Computer Minimap issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14824]
(WEB REPORT BY: theophrastus REMOTE: 172.93.109.202:7777)
>Revision 263f304ec7b03e2efee42349d0966312139d0ff4 
>General description of the issue
Adv. Security Cameras minimap and Crew monitoring computer minimaps do not appear, but atmospherics computer minimap does. This has happened to me on two different computers.

>What you expected to happen
To be able to see all the minimaps and interact with them

>What actually happened
I couldn't see the minimaps on 2/3 computers

>Steps to reproduce if possible
Open aforementioned computers

**Comment by Exxion** [comment]
Try clearing your BYOND cache
That SHOULD fix it
If it doesn't, I can give steps to manually fix it
But this is clientside and already reported several times

**Comment by Theophrastus1** [comment]
I'm going to need steps on how to manually fix it, clearing the cache did nothing.
