### ISSUE TITLE
Remove hyperlinks from non-OOC in-game channels.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#14827]
Simply said, any URL creates hyperlinks everywhere currently.
Name a clown/mine/non-human after a real or fake URL? Your name in chat becomes an hyperlink. 
Say an URL in-game? Hyperlink. 

I have no clue how goonchat works but I think that said hyperlinks should be gone from all channels but OOC and related ones such as admin PMs, msay, looc and even ghost chat since it's a grey area. Really just for the sake of people not accidentally clicking on those.

**Comment by Shadowmech88** [comment]
People shouldn't be posting links in non-OOC/LOOC anyway, so I don't see the harm in making hyperlinks OOC/LOOC-only.

**Comment by Theophrastus1** [comment]
There was a borg named www.hotsexystuds.com for a short period, and it created a hyperlink. Comedy aside, it was something that you probably won't want being abused.

**Comment by SonixApache** [comment]
Names don't support HTTML / CSS / BBcode tags, right?

**Comment by Theophrastus1** [comment]
I would assume they don't, but i haven't actually tried. Just hyperlinks really.

**Comment by Exxion** [comment]
Why would they support BBCode?
And CSS tags aren't even a thing

As for HTML, that's sanitized. Or at least supposed to be

**Comment by robintime** [comment]
duplicate of #9353
