### ISSUE TITLE
ATM Eats IDs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14820]
(WEB REPORT BY: nemod6989 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
263f304ec7b03e2efee42349d0966312139d0ff4

>General description of the issue
Deconstructing an ATM while an ID is in it, deletes the ID

>What you expected to happen
My ID to be spit out

>What actually happened
It spit out 1 piece of metal

>Steps to reproduce if possible
>Insert ID
>Deconstruct
>Here's your metal

**Comment by yclatious** [comment]
Just kick the ATM till it spits it out

**Comment by Exxion** [comment]
Read more than the title

**Comment by yclatious** [comment]
I did, you start using a welder on a atm to make it back into metal and expect your plastic card to be a thing after recieving welder fire and you are a idiot.

**Comment by mtpowell** [comment]
You use a wrench

**Comment by yclatious** [comment]
Whoops

**Comment by SonixApache** [comment]
ATM (de)construction definitely needs work. It's a broken relic.
