### ISSUE TITLE
It keeps happening

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#14826]
![2017-05-11_21-26-22](https://cloud.githubusercontent.com/assets/17213510/25979889/c1acf1d6-3690-11e7-9b94-df71e147ed2c.png)

**Comment by ghost** [comment]
8 minute rounds and no interactions with the crew.  Epic.

**Comment by gbasood** [comment]
@TheFriggenSawbones stop memeing

**Comment by TheFriggenSawbones** [comment]
@gbasood please fix make them roll two more objectives

**Comment by gbasood** [comment]
you can literally do that yourself
side note, gamemode rotation is an admin issue
