### ISSUE TITLE
Virus spreading is borked

### ISSUE THREAD

**Issue by jakmak6** [d3athrow/vgstation13#14825]
For the last couple of months i havent seen a virus outbreak. I had made a virus in viro with these stats

GNAv2 based virus lifeform - stamm #1452, #1452
Infection rate : 50
Spread form : Contact
Progress Speed : 10
Effect:Melisso-Emeto Syndrome. Strength : 1. Verosity : 3. Type : 1.
Effect:Adrenaline Extra. Strength : 1. Verosity : 3. Type : 2.
Effect:Groaning Syndrome. Strength : 1. Verosity : 5. Type : 3.
Effect:Creosote Syndrome. Strength : 1. Verosity : 1. Type : 4.
Antigen pattern: QP

and attempted to spread. I hugged several people and none of them go the virus but when i injected blood the virus did spread to the injected person.  I know nothing at all about how viro works so i request an actual viro player to help test and see if virus spreading is actually broken.

**Comment by DamianX** [comment]
Reading through the code it seems clothing in the targeted area would prevent spread. Have you tried using naked hands on someone with naked hands, for instance?

**Comment by Exxion** [comment]
Arthur told me a while ago that viruses are fucked
They don't seem to spread at all, ever

**Comment by Arthurdentist** [comment]
I already made an issue for this I believe but it didn't gain much traction. Not sure where it got too.

**Comment by Killette2** [comment]
Wasn't like this before the virus nerf after I made my suicide virus that one round, triggering coders to make virology further useless.
🤔
