### ISSUE TITLE
station can be cooked up with a heater

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14828]
![screenshot_4](https://cloud.githubusercontent.com/assets/17911005/25994645/f7750b68-370e-11e7-97e2-d2b05c9b441d.png)

I don't know how this fully happened, but this runtime seems to cause all of the atmos on station to get fucked, resulting in this: 
![4828404123](https://cloud.githubusercontent.com/assets/17911005/25994671/103e2d3c-370f-11e7-9720-528c42b13e61.png)
The heater was in toxins

**Comment by Exxion** [comment]
Dear fuck

**Comment by ghost** [comment]
we should leave it like this

**Comment by FudgePucker** [comment]
Is this reproducible?
Sometimes atmospherics just shits itself.

**Comment by SECBATON-GRIFFON** [comment]
imagine the TEG output
...if i could even reproduce this. i've had no luck either
