### ISSUE TITLE
Bug with cult sacrifice objective?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14839]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
40d9b8600f2609d10a940314fd984c79e6e206e9 

>General description of the issue
Cult got an objective to sacrifice one of their own, a cargo tech.
When they tried they got a "There is nothing fit for sacrifice on the rune" message

>What you expected to happen
a sacrifice

>What actually happened
There is nothing fit for sacrifice on the rune.

>Steps to reproduce if possible
try to sacrifice a culted guy, I guess?

**Comment by DeityLink** [comment]
Outdated. Open another issue it this happens again.
