### ISSUE TITLE
Two Time Suit issues related to using the past mode

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14833]
(WEB REPORT BY: smallboss REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 263f304ec7b03e2efee42349d0966312139d0ff4 

>General description of the issue
1.When you get beheaded while you are jumping into the past with the timesuit your body will be regenerated after the effect, but your soul will still be in your head, making the regenerated body catatonic

2. When you get hit by a staff of change projectile while jumping into the past you will still stay in the body of the staff of change projectile after the past mode stops rather than putting you back in your original body.

**Comment by PJB3005** [comment]
@Shadowmech88

**Comment by ghost** [comment]
Aren't they admin spawn only

**Comment by PJB3005** [comment]
@Commandersand so? It's still bugs.

**Comment by ghost** [comment]
also this happens when you use the jump to past spell after blowing yourself up
![screenshot_5](https://cloud.githubusercontent.com/assets/17911005/26019923/aa218d4e-3779-11e7-8d83-70f5d44d59f5.png)
the body is alive without any limbs, but catatonic

**Comment by FudgePucker** [comment]
Jesus that is disturbing. Fucking thing is an abomination of nature, nuke the station christ.

**Comment by Dacendeth** [comment]
Timesuit has many more bugs than that. Past mode doesn't reset your blood%, future mode causes active timed explosives (at least IEDs) to never explode if they were to explode while you were frozen. If you hit future mode and then hit past mode right away (or the other way around i forget) you end up nullspaced. If you hit past mode and put on a morphing mask during the effect you essentially have two bodies until you take the mask off causing your old body to appear at your current masked location and you get shoved back inside of it.

**Comment by Shadowmech88** [comment]
The timed explosive thing is because they're exploding in nullspace because timed explosives use `spawn()` to handle their countdown and `spawn()` is an internal BYOND thing, so I'm not sure how it could possibly be delayed. Timed explosives explode in stopped time as well.

**Comment by Intigracy** [comment]
timed explosives use timers which have a var you can use to disable timing, then once time continues you can put the var back to enabled

**Comment by Shadowmech88** [comment]
I meant "timed" in the general sense.
IEDs don't use timers, do they?

**Comment by Intigracy** [comment]
Ah.

The solution I'd offer is refactoring them to use Process() and giving them a timeleft var, that way you can stop them from processing when they get timestopped.

**Comment by Intigracy** [comment]
Though that'd be seperate from the above PR unless you want to just shove it in that one.

**Comment by Exxion** [comment]
If you make them use `Process()`, they can only time in multiples of 2 seconds.
