### ISSUE TITLE
ERT is to hard to call

### ISSUE THREAD

**Issue by jakmak6** [d3athrow/vgstation13#14837]
Currently ERT is far far to hard to call. Without admin intervention to call a ERT you need to

- raise to red which requires 2 heads (reasonable)

- a captain level ID on the communications console (not head of staff level it has to have captain access)

- the shuttle to NOT be already called

On paper this sounds resonable and just but in practice it is not possible to call a ERT without a admin helping due to

- If it actually got so bad that a ERT would be called there would be a low chance of 2 heads being alive (yes you can promote an assistant to help but that is also a mess to explain how to raise to red)

- If you needed a ERT and had a comms console already then you would have called the shuttle. While it makes sense to not allow ert while shuttle is coming in practice nearly every time i have seen a ERT attempted to be called without admins helping the shuttle would already be on its way. It may not seem big but those 10 minutes can mean life or death for the entire crew

- Captains level access. Not many people play captain and the ones who do are usually to dumb to know players can call ert without praying to admins and since to have all access and not be captain/lone head of staff you need to be antag/powernigger who rushed the spare roundstart.

Maybe reduce the access to requirement to call ERT down to bridge level  (head of staff access), allow the ID swiper (same one used for raising to red) to allow for a swipe for ERT, and allow ERT to be called when the shuttle is called because 99% of the time when a ERT is needed the shuttle is already en route.

Also think when was the last time you remember seeing a ERT get called WITHOUT admins helping call it. Deathsquads dont count

**Comment by ghost** [comment]
TFW two smart too call ERT

**Comment by ReindH** [comment]
WE BUILD

**Comment by ghost** [comment]
I'd like calling the ERT to just be head access. You're too busy cleaning up messes to be able to play the game as captain but then you're fucked by not having access as a dept head down the road.

**Comment by jakmak6** [comment]
Also these are 90% of the situations where you would call a ERT (barring adminbus stuff)

- Nukies. If you were at a comms console then first thing you would do is call the shuttle. ERT needing code red means getting heads to sit still and raise to red which never happens due to the panic of nuke ops. Besides the amount of time it takes to raise to red the nukies would probably be able to kill the only person with the access to call the ERT

- Xenos. By the time the crew feels they need help they either A call the shuttle or B the only people with access to call ert are dead.

- Revs. A ert can tip the scales in revs BUT to raise to red it needs the heads to seperate in order to raise and the captain to actually call the ERT. By the time you do all these pre requisites the revs usually kill off the heads

These are most of the situations where ERT gets called. For reasons listed it is far far to much effort to call a ERT. Maybe if captain level ID can raise to red on the comms console or again the ID swipers used to raise to red can call a ERT and to also remove the requirement that the shuttle has to be NOT called in order for a ERT to be spawned.

**Comment by Blithering** [comment]
I thought you could also call an ERT with two heads of staff using the keycode thing once its in code red?

**Comment by jakmak6** [comment]
not on this codebase blithering. On other codebases (paradise?) you can but not here

**Comment by Blithering** [comment]
Found it, https://github.com/vgstation-coders/vgstation13/pull/12615 made it possible for heads to call ERT using keycard device.

**Comment by jakmak6** [comment]
wait ive never seen that option on the keycards

**Comment by PJB3005** [comment]
Lol

**Comment by Intigracy** [comment]
`+		if((get_security_level() in list("red", "delta")))`
because you haven't been in red alert when you've tried
