### ISSUE TITLE
REMOVE SOLO WIZ

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14844]
![image](https://cloud.githubusercontent.com/assets/22992659/26085734/db85f670-39ab-11e7-8b28-6f8eae428300.png)
recent wizard round statistics
it's HORRIBLE and should either be removed or just made into wiz+(random antag)
admins will either put in another wizard or just press the autotraitor/ling button
it's worse than extended because people KNOW the round has no more antags if there's one wizard that dies so the game no longer has a paranoia  feel which leads to admins pressing buttons or a round where you now feel very safe because the only antag has died

**Comment by Shadowmech88** [comment]
Ragin' Mages is just a better version of wizard mode, isn't it?
We could roll more of that to compensate for removing wizard mode.

**Comment by mtpowell** [comment]
What should really happen is for every, let's say, 7-10 players, a random antag should pop
Basically merge wizard/vamp/traitor/doubleagent/ling into one game mode

**Comment by AI-Is-Rogue** [comment]
**antag datums**

**Comment by Intigracy** [comment]
This is purely a config thing, no code changes needed.

Get an admin to make a server poll about this and I'll have no issue changing it.

**Comment by SonixApache** [comment]
been saying wiz + autotator for months now

**Comment by ihadtoregisterforthis** [comment]
#14473

**Comment by AutismSpider** [comment]
Round use to end on the wiz is death. 

yell at dip shit who took that off and put that back in.

**Comment by Exxion** [comment]
That was voted for

**Comment by Arthurdentist** [comment]
round ending on wizard death was shit for a thousand reasons that have been explored over and over already.

Antag datums is the proper solution but its still not here.

**Comment by Exxion** [comment]
Antag datums wouldn't solve anything on their own
Just make it easier/possible to solve things properly

**Comment by Megamaw** [comment]
as someone whose favorite antag to play as is the wizard, both ragin mages and wizzyman rounds have problems

wizzyman is fun to play as, but it can end very quickly/be a little boring if you cant spice it up somehow

ragin mages punishes stealth wizzymen if any of the wizards go loud, inciting a validhunt for the last wizards so the round can end

honestly, as oversaid as it is, i think the best solution is legitimately working on antag datums, so that wizards can be in rounds alongside traitors/etc automatically

**Comment by Blithering** [comment]
Hey, I'm in that picture! Also I agree spicing it up with some hidden other antagonists either after the wizard dies or as a mini-mixed would make it better. Until then admins adding a few new traitors or a new wizard to keep the round becoming extended helps a lot.

**Comment by Anton-Kr** [comment]
```
D A T U M S
  N
  T
  A
  G
```

**Comment by gbasood** [comment]
reminder that stats could use some love in many ways
become a python nerd today

**Comment by mtpowell** [comment]
Goon has amazing stats, we should have something like them, some sort of log Scraper

**Comment by gbasood** [comment]
no
goon doesn't use a log scraper
goon uses basically what we have
if you want to improve things about:
 - the way we show stats: you can contribute to https://github.com/gbasood/vgstation-statistics-viewer
 - the way we gather stats: you can contribute to the game code *RIGHT NOW*

**Comment by Intigracy** [comment]
bauds decided to work on antag datums and then he disappeared

the position is truly cursed

**Comment by icantthinkofanameritenow** [comment]
@Intigracy 
That's because he's a lazy bum.

**Comment by Kammerjunk** [comment]
Round ending after wiz death wasn't great. It was certainly better than wizstended.
Extended is okay I guess (although I get pretty bored in medbay), but extended with the entire crew on high alert because a space-trotting magic asshole decided to swing by is different

**Comment by Intigracy** [comment]
http://ss13.moe/index.php/poll/111
