### ISSUE TITLE
How to genocide the vox in one easy map gen

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#14843]
![2017-05-13_21-01-33](https://cloud.githubusercontent.com/assets/17213510/26073638/0ec71abe-3975-11e7-8f55-c98549b115e4.png)
![2017-05-15_12-58-43](https://cloud.githubusercontent.com/assets/17213510/26073642/107fdb48-3975-11e7-84f4-7de992b01a4c.png)

**Comment by TheFriggenSawbones** [comment]
top is box bottom is meta

**Comment by Gunosaguki** [comment]
Man Spessmart sure has gotten competitive with the traders recently

**Comment by Durgen** [comment]
https://github.com/vgstation-coders/vgstation13/issues/13802

**Comment by Durgen** [comment]
![scrnshot1a](https://cloud.githubusercontent.com/assets/19157295/26074493/9e1c6064-3977-11e7-8c2c-0b16cd7b9348.png)

**Comment by ghost** [comment]
How come it's only vox outposts and not science or mining ones?

**Comment by Durgen** [comment]
well the metaclub vox outpost is on z6, and the box vox outpost is new, so maybe something broke when it was merged

**Comment by ihadtoregisterforthis** [comment]
It's been like this for years. 
The spacemart issue is probably fixed by mapping

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/26076334/4a749f3a-396d-11e7-9b30-a6450d90a35f.png)
this is why
it needs to be changed to
![image](https://cloud.githubusercontent.com/assets/3959840/26076358/59ccc43a-396d-11e7-8ba5-4029dd6e3421.png)

**Comment by Riekland** [comment]
I don't see any issue whatsoever here

**Comment by Kurfursten** [comment]
I am 100% sure that I originally mapped a large area around the voxpost as explored AND reconfirmed with probe that when he PR'd it, he left those explored. How this could've happened is very confusing to me, I wish maps had git blame.

**Comment by CptWad** [comment]
no not the AREA its the TURF
you want `/unsimulated/mineral` N O T `/unsimulated/mineral/random`
TURFS decide random structures for whatever reason

**Comment by Kurfursten** [comment]
Amazing

**Comment by Exxion** [comment]
And it checks SPECIFICALLY for that type to end generation, rather than any type other than the random one?
What the fuck

**Comment by ihadtoregisterforthis** [comment]
The meta vault spawn keeps removing part of the outpost

![alium center yankee 2017-06-29 002934](https://user-images.githubusercontent.com/13305885/27753957-43a9421c-5dbe-11e7-825f-61eba55fbb0f.png)

**Comment by Riekland** [comment]
"good"
