### ISSUE TITLE
Decoy Balloon not Scannable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14850]
(WEB REPORT BY: starnightx REMOTE: 172.93.109.202:7777)
The special scanner from Mechanic doesn't allow to scan the Decoy Balloon for mass produce.
>Unplayable

**Comment by Shadowmech88** [comment]
I don't see why it wouldn't be scannable, neither it nor anything it inherits from has the `MECH_SCAN_ILLEGAL` or `MECH_SCAN_FAIL` flags.

**Comment by jknpj** [comment]
does it have tech?

**Comment by Shadowmech88** [comment]
Is tech necessary for the mechanic's scanner? I thought it was just for the tech levels R&D gets from putting it into the destructive analyzer.

**Comment by jknpj** [comment]
`if(O.origin_tech || istype(O, /obj/machinery)) //two requirements: items have origin_tech, machines are checked in...`

Yes you need origin_tech to be able to scan
