### ISSUE TITLE
NO SLIMES IN XENOBIO

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14869]
(WEB REPORT BY: sandysand REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
NO SLIMES IN XENOBIO

>What you expected to happen
SLIMES IN XENOBIO

>What actually happened

NO SLIMES
>Steps to reproduce if possible
MERGE BAGEL STATION
PUT IN ROTATION
LOVE IT
NOTICE YOU CAN'T DO XENOBIO

**Comment by ghost** [comment]
also no normal extinguishers either
