### ISSUE TITLE
Bagel Station Sec Shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14868]
(WEB REPORT BY: wushroom REMOTE: 172.93.109.202:7777)
>Change the name from Research Shuttle to Prison Shuttle or something

>The name in the shuttle console is research shuttle
>It being called Prison Shuttle

>It wasn't

>Look at the console in the brig

**Comment by Durgen** [comment]
it also says 'moving to the genetics research outpost'  when moving
