### ISSUE TITLE
Detective Access in Brig

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14860]
(WEB REPORT BY: slashbolt REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Detective has no access to the Prison Wing door in the brig

>What you expected to happen
Having access to the prison wing door in brig

>What actually happened
I didn't have access

>Steps to reproduce if possible
>be det
>try to get through brig access
>cannot

**Comment by Theophrastus1** [comment]
Why would a detective need to get to solitary or the permabrig?

**Comment by Intigracy** [comment]
same on the other maps
