### ISSUE TITLE
Bagel starts with a ton of empty vending machines

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#14875]
![2017-05-17_21-16-25](https://cloud.githubusercontent.com/assets/17213510/26185552/57ac6e40-3b51-11e7-88fb-8b5bd9cf35b9.png)
![2017-05-17_21-15-44](https://cloud.githubusercontent.com/assets/17213510/26185554/591ea388-3b51-11e7-9cdb-4665fed1283b.png)
![2017-05-17_21-14-22](https://cloud.githubusercontent.com/assets/17213510/26185556/5af766cc-3b51-11e7-95d3-8d0920da8739.png)

**Comment by AI-Is-Rogue** [comment]
They're meant to get filled by all of the vending packs in cargo and that other room.

**Comment by Intigracy** [comment]
I believe this is intended, you'll have to take it up with @CptWad

**Comment by CptWad** [comment]
intended
