### ISSUE TITLE
Free the Goliaths! (Bagelstation)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14877]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
![](http://i.imgur.com/l8lmqMb.png)
Save these special boys

**Comment by Gunosaguki** [comment]
FUCKED UP THE LINK FIX IT FOR ME

**Comment by Blithering** [comment]
http://imgur.com/a/faeeA
