### ISSUE TITLE
Bagel: Solars initial setup problems.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14878]
(WEB REPORT BY: uristmcstouthorn REMOTE: 172.93.109.202:7777)
>Revision 
f2cea69adc0cb5e92550f5a17de3d16ddd6bb84c

>General description of the issue
Setting up solars (as I've done on boxstation a bajillion times) and they refuse to actually turn once set up.  Auto-tracking, manual tracking, even manual manually clicking the -/+ and the cosole says it's turned, the picture on the monitor says turned, but the solars don't actually turn.

>What you expected to happen
Solars, tracking the light as they should, and turning toward it, to produce power.

>What actually happened
The solars don't turn toward the light, nor anything else for that matter.

>Steps to reproduce if possible
Head out of maint, to the southwest (I'm assuming UP from player orientation is North) solar array and try to set them up.

**Comment by Intigracy** [comment]
I'm betting you didn't connect the tracker

**Comment by CptWad** [comment]
same, I was careful when setting those up but I can double check them for good measure
