### ISSUE TITLE
Bagel gulag issues/requests

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#14874]
The Bagel perma gulag is neat, but I think it needs a second warden slot so there's one to watch over it and one to watch over the station prisoners.
I also personally reckon the mining area should have air, but be cold so there's an excuse to have the sec and prisoner coats there instead of hardsuits.
In actual issue news however, the air injector near the north basketball hoop kills you if you stand on it too long, 10 seconds was enough to pass out and break a foot.
And the escape pod's two north corners bug out in transit, see the screenshot for details.
![bagshuttle](https://cloud.githubusercontent.com/assets/15067109/26185455/fdcfe7c6-3b82-11e7-81cc-592c50d0937c.png)

**Comment by CptWad** [comment]
yeah definitely, sadly the way asteroids are set up they wont HAVE air to breath. My idea was to set up some soft suit spacegear that are obviously orange-ish for prisoners, which is why they are anomaly suits since they fit the theme

**Comment by Blithering** [comment]
I could sprite up some prisoner softsuits if you want
