### ISSUE TITLE
Bagel, No access to auxiliary tool storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14871]
(WEB REPORT BY: knightkiller REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

c0223685d75c08d615d8731c75d79ce7b326ad33 
>General description of the issue
Aux Tool Storage seems to be inaccessible to me (A scientist)

>What you expected to happen
It to open

>What actually happened
It did not

>Steps to reproduce if possible
Try to open aux tool storage as a scientist

**Comment by Kurfursten** [comment]
Aux Tool Storage isn't accessible to scientists on any map (it always requires maint access). On Box, the aux tool storage is the room above the custodial closet.

**Comment by ghost** [comment]
scienctists also have art storage access though i don't remember if that's normal

**Comment by Kurfursten** [comment]
Yes, that's normal, art storage is public
