### ISSUE TITLE
Singularty Beacon not working?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14882]
(WEB REPORT BY: codenameb REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
194a6f92635fe0b68e590fe8fbb622e0b5dc61b2

>General description of the issue
Playing on Bagelstation. A singularity beacon was placed in virology, wired up, connected to the floor, and turned on. A bag of holding was placed in a bag of holding on the other side of the station. I was instantly gibbed, and the singularty spun in place and did not move or change in size until it was destroyed by someone else.

>What you expected to happen
The singularity beacon to attract the singularity

>What actually happened
The beacon had seemingly no effect at all.

>Steps to reproduce if possible
See above.

**Comment by JustSumBody** [comment]
```
/obj/machinery/singularity/process()
	dissipate()
	check_energy()

	if(current_size >= 3)
		move()
		pulse()
		if(prob(event_chance)) //Chance for it to run a special event TODO: Come up with one or two more that fit.
			event()
	eat()
```
From what I'm seeing, it won't actually move unless its "size" is above 3
Fresh bagulo doesn't move regardless of beacons
