### ISSUE TITLE
Bagelstation map render doesn't exist

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14894]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
194a6f92635fe0b68e590fe8fbb622e0b5dc61b2 
>General description of the issue
Self-explanatory

>What you expected to happen
Clicking on the "Bagelstation" panel brings up the map

>What actually happened
The following:

"The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.
Error 404"

>Steps to reproduce if possible
Play on bagel, click on the tab that would normally bring up the map.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Close this
