### ISSUE TITLE
Bagelstation missing a Scrubber

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#14899]
Despite having a manifold here (I forget where this is on the map), it has no accompanying scrubber.
![scrnshot1](https://cloud.githubusercontent.com/assets/6224074/26219491/36802a0e-3bdd-11e7-91e9-59f88036c338.png)

There's also a vent laid over a scrubber line somewhere in engineering, which is going to trigger someone fierce when they find it.

**Comment by Kurfursten** [comment]
Confirming this again, just in case anyone thought it might have been from a specific round, I saw this 8 hours ago
