### ISSUE TITLE
Bagelstation primary tool storage APC placed incorrectly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14895]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
194a6f92635fe0b68e590fe8fbb622e0b5dc61b2

>General description of the issue
APC is floating directly in front of top-left maintainence door

>What you expected to happen
For it to be on the wall.

>What actually happened
See above.

>Steps to reproduce if possible
Play on Bagelstation. There may be other APCs also placed incorrectly as well.

**Comment by icantthinkofanameritenow** [comment]
My mistake, meant "Bagelstation primary tool storage APC placed incorrectly".

I can also confirm that among others, the Ghetto Morgue, Port Maintainance, Aft Primary Hallway, Port Primary Hallway, and...you know what, I'll just make a new issue, there's a ton of them.
