### ISSUE TITLE
The prison shuttle on bagel is not tied to any console, mining shuttle can go to security roid

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#14892]
So there's the security shuttle on bagel that goes to the security asteroid section, except the console station side lacks any destinations to pick from and the console roid side says something about scanning for docking ports.
Not sure what the security shuttle console itself has on it, but might be worth looking into.

MEANWHILE, the mining/cargo shuttle can be used to go to the prison station instead.

**Comment by CptWad** [comment]
aaaaaa fuckin shuttles
