### ISSUE TITLE
Giant Syringe Drains Blood Without Drawing It

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#14903]
#### Description of issue

Giant syringe can't draw blood, and gives a message stating such, but still drains a person's blood level when you use it on them.

#### Difference between expected and actual behavior

Giant syringes should not make blood vanish into thin air.

#### Steps to reproduce 

Use giant syringe on a person.

#### Server revision

194a6f92635fe0b68e590fe8fbb622e0b5dc61b2 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
Couldn't reproduce.
Used a `/obj/item/weapon/reagent_containers/syringe/giant` on a `/mob/living/carbon/human` and got 

> This needle isn't designed for drawing fluids from living things.

No blood was drained.

**Comment by Shadowmech88** [comment]
Did you check your blood level using a health analyzer? Because I stuck myself with it a few times and my blood level was reduced to 80%.

**Comment by DamianX** [comment]
I used a full body scanner, actually.

**Comment by Shadowmech88** [comment]
Huh, I just tested it again and it didn't happen.
Strange.
