### ISSUE TITLE
Ramsay bot able to be clicked to spam and in non adjacent tiles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14901]
(WEB REPORT BY: theophrastus REMOTE: 172.93.109.202:7777)
>Revision 194a6f92635fe0b68e590fe8fbb622e0b5dc61b2 

>General description of the issue
Able to click ramsay bot from over tables and windoors to spam the chat with the turn off message

>What you expected to happen
it wouldn't just fill the chat or be able to be abused

>What actually happened
it was promptly abused

>Steps to reproduce if possible
put ramsaybot near a table or windoor, stand on the otherside and try to click it repeatedly.

**Comment by jknpj** [comment]
RIP sanity

**Comment by ReindH** [comment]
Ghosts can spam too.
