### ISSUE TITLE
Being slimed by Cursed Dice should remind you you aren't an antag

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#14916]
So this is the commonly accepted server policy p sure that if you self curse yourself into a slime, you aren't an antag. As it's supposed to be a punishment not a mode for players to get sick kills.

Any chance we can get a big flavor text reminder when you get slimed by the die?

**Comment by TheFriggenSawbones** [comment]
or remove sliming from the dice, that could also work

**Comment by Shadowmech88** [comment]
We could make the dice turn them into a docile slime instead.

**Comment by TheFriggenSawbones** [comment]
Frankensteining the roller seems to be a popular choice on the server

**Comment by Intigracy** [comment]
I could give them the reminder, or I could just change the slime punishment to a catbeast monkey.

**Comment by Arthurdentist** [comment]
got a PR going up that should resolve the issues I hope.
