### ISSUE TITLE
Large Artifacts Sometimes never having Visual or Audio Activation effects

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14918]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
I think this is caused when an artifact has two effects triggered by touch. The effects will still happen, but there will be absolutely no text to show it. Maybe its because the effect length is "burst on touch" But regardless some flavor text would be nice for the less obvious effects.

**Comment by jknpj** [comment]
Because secondary effect activation has no visual changes, that's how we get newbie xenoarchs banned.

**Comment by DeityLink** [comment]
Some sounds were added for large artifacts activations.
