### ISSUE TITLE
[BAGEL] Hydrophonics puddle describes itself as sink

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14912]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

71a6e4dc152a7c5825cdb0f9a5a5cab175e524c6 

>General description of the issue

https://puu.sh/vUqGR/7cec949b29.png

**Comment by BobdaBiscuit** [comment]
I IDENTIFY AS A SINK-KIN.

**Comment by Intigracy** [comment]
It's a subtype, just needs a desc change.

**Comment by CptWad** [comment]
not a map-related issue but ill fix it anyways
UNATOMIC
