### ISSUE TITLE
No Autopsy Scanner on Bagel

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#14924]
#### Description of issue
Bagelstation does not have autopsy equipment in the morgue or in medbay anywhere, autopsy equipment cannot be created

#### Difference between expected and actual behavior
Autopsy scanner at the very least available in morgue

#### Steps to reproduce 
Play Bagelstation

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
no pen in the morgue either
