### ISSUE TITLE
Ghosts can attempt to turn of Chef RAMsay which displays a message to living and dead, revealing the name of the one clicking.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14930]
(WEB REPORT BY: fruktlimpa REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Ghosts can click on Chef RAMsay to try and turn him off which will display this message to living and dead.
"Darin White tries to turn Chef RAMsay off, but there's no switch!"

>What you expected to happen
Not being able to click him

>What actually happened
Can click him 

>Steps to reproduce if possible
Spawn RAMsay
Ghost
Click RAMsay

**Comment by Fruktlimpa** [comment]
An image from the chat feed. ICK OCK-proofed
![ss 2017-05-19 at 06 11 59](https://cloud.githubusercontent.com/assets/19466872/26256970/0c9b61bc-3cbf-11e7-87b7-aa6b7a4a337d.png)

**Comment by jknpj** [comment]
Cooking a fix for it
