### ISSUE TITLE
SLIME RACE problems

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14944]
#### Description of issue
upon cloning it reverts your gender to your previous  one before sliming
for some reason our limbs didn't want to come off after a shitload of cutting, it worked for a while but our limbs stopped coming off easily
They're not immune to cloning as advertised, not sure if it needs fixing or removal
apparently ALL races or atleast vox can become a slime person instead of only humans, not sure if intended
their custom speech either doesn't work or isn't colored since i couldn't tell which

#### Difference between expected and actual behavior
>be "it"
>limbs still fall off
>took clone damage from decloners and cloner
>custom speech looked regular
>only humans can slime person

#### Steps to reproduce 
have a nice productive round in xenobio

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ x] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
>apparently ALL races or atleast vox can become a slime person instead of only humans, not sure if intended

Intended.

**Comment by Shadowmech88** [comment]
As far as the limb severing thing, I'm not sure what to do about that.
I think I'm going to need more information than "it worked for a while and then it didn't."

Put it in its own issue after this one's closed.

**Comment by ghost** [comment]
aight
