### ISSUE TITLE
Silicon Extended Wait Time

### ISSUE THREAD

**Issue by SerWind** [d3athrow/vgstation13#14947]
Fuck me I didn't know what to call this. I still have no idea how to tag shit. Anyway did a bit of a poll in /vg/ today for what it's worth about how to approach new players getting their hands on silicons. I think the current wait time for them is like seven days? Which is honestly nothing. Personally I was a bigger fan of white listing them but I think I agree with Sawbones in that nothing should be white listed, doesn't really fit with our server culture. Anyway here's the poll http://www.strawpoll.me/13000642/r

I think extending the time significantly that new players to our server have to wait to get their hands on silicon roles is a perfectly reasonable idea, especially considering how we approach asimov. There's too many house rules for someone who has been playing for seven days to really get. Would love to hear other people's thoughts on this unless it's Solarious cause he's SHIT.

Nah just a meme.

**Comment by Shadowmech88** [comment]
What are the other job slot wait times like?
Is a month comparable, or much longer than the next longest?

**Comment by SonixApache** [comment]
Some more time for most of the locked roles might be good.

An option for meanwhile, though; Toggle pAI on by default. 
pAI is a great way to learn basic silicon (well, not-carbon) gameplay and still contribute to a round.

**Comment by ReindH** [comment]
I heavily support something like this, I sound like talking out of my ass since I got no proof, but the amount of borgs who have no idea what they doing has been an issue lately.
Some of them don't know how actually laws work or don't even know what binary chat is even.
Don't know how well an extended wait time would work, but it's a start.

**Comment by ghost** [comment]
Yeah it'd be fine for it to be at least matched with the head roles wait times. Getting more time under your belt before getting in the hotseat can only help.

**Comment by SerWind** [comment]
I believe the longest wait time is 30 days? I think even that's too low really, which is why I was more in favor of white listing.

**Comment by ReindH** [comment]
Wouldn't that be extremely subjective?

**Comment by SerWind** [comment]
Hence why I am more for white listing them, but at least a longer time might stop some people who just aren't ready. Silicons have more potential to ruin rounds than I think anything else on the station.

**Comment by Shadowmech88** [comment]
I believe he meant "Wouldn't white listing be extremely subjective?"

**Comment by ReindH** [comment]
Yes, I should have worded it better I guess.

**Comment by SerWind** [comment]
Oh, well I interpreted as "isn't an increased timer subjective" in the sense that some people learn quicker and some people learn slower, and it's better to gauge that one on one instead of just setting a timer that might or might not fit the needs. Anyway I'm all for an increase in the timer as a compromise anyway, and I think most people agree it's at least a good idea?

**Comment by Theophrastus1** [comment]
I'd say that longer wait times is definitely needed, it's a pain in the ass when you have people who do not understand how silicon laws work and do things like disregard orders on asimov

**Comment by FudgePucker** [comment]
What about time played instead?
Someone who plays several rounds everyday for a week will know more than someone who plays one round a week for a month.

**Comment by gbasood** [comment]
Time played would be neat, but honestly, good luck coding it.

**Comment by Exxion** [comment]
Time played would be obnoxious to code, but not really that hard. (Record the times of connection and disconnection, subtract, and add.) Worth the effort? Don't know.
Number of rounds played would be easy, though.
