### ISSUE TITLE
Bagel default-wires the SME to the main grid

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#14955]
It will take some doing, but you can definitely set it up in a way that it runs into the engineering grid

**Comment by SonixApache** [comment]
Doesn't bagel default-wire the SME into it's mobile SMES charging grid?

**Comment by Kurfursten** [comment]
The portable SMES are part of the main grid, so "yes", but the main grid is not "behind" those ports. Whether or not you even plug in the mobile SMES, the main grid will get the full wattage of the SME.

**Comment by jknpj** [comment]
feature

**Comment by SonixApache** [comment]
Last time I played bagel (before the last batch of fixes) there was a single cross wire seperating the SME from the main grid. Are you 100% sure?

**Comment by Kurfursten** [comment]
It is possible that someone altered the power setup before I got there, I've only done Bagel engineering once so far on live

**Comment by CptWad** [comment]
entirely sure I made sure this wasnt possible. 
if its true then f u g

**Comment by CptWad** [comment]
![image](https://cloud.githubusercontent.com/assets/3959840/26281361/5c25eb4a-3da9-11e7-88c3-aa8e85fc554b.png)
we good

**Comment by Kurfursten** [comment]
Alright, cool. In that case, it must have been someone who changed it manually.

**Comment by SonixApache** [comment]
For the record, this is a feature of Bagel I really like. Just wish the SMES ports were easier to find for engineering.
