### ISSUE TITLE
Possible HoP traitor issue?

### ISSUE THREAD

**Issue by chaotichawk** [d3athrow/vgstation13#14957]
http://i.imgur.com/CCQzM56.png
I escaped on pod as HoP traitor (very low roll rate by the way) and didn't get my greentext even though I survived.

**Comment by Blithering** [comment]
Which map was this on? And which pod did you take? Its possible one of the pods is marked as a prison area like the shuttle brig.

**Comment by ghost** [comment]
You probably left the pod before the smellelelel, that area you are in is not considered an escape.

**Comment by chaotichawk** [comment]
@Blithering Box station used brig pod yeah,it doesn't count towards greentext? Well you're HoP after all, you have access to it wanting or not

**Comment by mattmatterson111** [comment]
The not in custody part checks to see if you're in the brig area of the shuttle, of the brig escape pod. So if you're in either of those it won't count as not in custody.

**Comment by Intigracy** [comment]
I think it has some stupid check like checking for the red turf.

**Comment by CptWad** [comment]
this does not seem like a mapping issue at all given that the sec pod has blue flooring

**Comment by ghost** [comment]
It checks the area, not the floor, surely
