### ISSUE TITLE
CMO has no access to bridge's glass doors in metaclub or defficiency

### ISSUE THREAD

**Issue by smedbux** [d3athrow/vgstation13#14967]
#### Description of issue
CMO has to break rwindows to get to the central bridge consoles

#### Difference between expected and actual behavior
CMO has bridge access normally

#### Length of time in which bug has been known to occur

I've known about it for a month or so

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Duny-** [comment]
This behavior is intended on defficiency. The central area is meant for the captain, only contains an extra comms console, and only has captain access. All the other consoles (including another comms console) are fully accessible by all the heads.
