### ISSUE TITLE
bagelstation airlock placed over wall

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14961]
(WEB REPORT BY: ttorpedo REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
f45682708f6a19a77cf2b6473858a5501f49dc95 
>General description of the issue
south of the security shuttle is an airlock in the maintenance tunnels. It is unusable as there is a wall underneath the door.

>What you expected to happen
there to not be a wall under the door

>What actually happened
there was a wall under the door

>Steps to reproduce if possible
walk through maint tunnels under the security shuttle and try to go through the door where a wall will be in the way under the door.

(hopefully this isn't just some kind of elaborate prank)

**Comment by Intigracy** [comment]
Sound like a great elaborate prank
