### ISSUE TITLE
[BAGEL] Medbay keeps throwing atmosphere alarms

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#14963]
#### Description of issue

--- Atmosphere alarm detected in Medbay! (Medbay Lobby South | Medbay Hallway South | Medbay Lobby North | Medbay Hallway West | Medbay Hallway | Medbay Hallway Center | Medbay Hallway North | Medbay Hallway Northeast)

Reason for this is unknown.

#### Server revision

f45682708f6a19a77cf2b6473858a5501f49dc95

**Comment by Kurfursten** [comment]
Probably one tile of space is mapped as part of medbay

**Comment by Exxion** [comment]
That or an incorrect vent instance

**Comment by CptWad** [comment]
Nah I fucked up and put a scrubber under an alarm which pisses it off for some reason
