### ISSUE TITLE
Bagel Feature Requests For Perma

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14962]
-roid should have sec cameras
-perma shouldn't have real knives, should have plastic ones like box

**Comment by Jubisloviu** [comment]
but box perma has no plastic knives, it has small knives.

**Comment by ghost** [comment]
that should be fixed by someone who cares more than me, along with bagel

**Comment by CptWad** [comment]
but the roid does have sec cameras? They are even on a new network
as for the knives, if you die to prisoners with knives then its your own damn fault
