### ISSUE TITLE
Bagel bar sign

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14969]
(WEB REPORT BY: szuflox REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

f45682708f6a19a77cf2b6473858a5501f49dc95

>General description of the issue

When you change the name displayed on the bar sign for the first time it moves one tile down from wall to the floor, later it just stays there.

>What you expected to happen

Bar sign not moving.

>What actually happened

Bar sign moves.

>Steps to reproduce if possible

Try to use bar sign.

**Comment by SonixApache** [comment]
I've had this happen to me on other maps (Deff?) as well.

**Comment by Intigracy** [comment]
Since the latest barsign PR which resets the position of the barsign to 0
