### ISSUE TITLE
Adminhelps with characters like "ñ" or "áèíóù" aren't displayed and cause a Runtime

### ISSUE THREAD

**Issue by PromethTK11** [d3athrow/vgstation13#14970]
#### Description of issue: 
If you put some characters like the title ones in an adminhelp it's gonna cause a runtime, it gonna reproduce the bwoink sound but it would never display the message on the chatbox

#### Steps to reproduce:
- Press F1
- Type: "ñ"
- Enter

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Can't be fixed until we move the msay panel to goonchat.

**Comment by Riekland** [comment]
john madden

**Comment by Shadowmech88** [comment]
Could we at least scan through incoming ahelps and just remove such characters before passing them to the msay panel's code?

**Comment by PJB3005** [comment]
@Shadowmech88 I mean I guess you could yeah but that's still hideous.

**Comment by PJB3005** [comment]
If anybody's interested in doing that, just wrap the text sent to the msay panel in `strict_ascii(text)` to remove non 7-bit ASCII values.

**Comment by nuklearcellphoneg** [comment]
Good I don't wanna talk to foreigners
