### ISSUE TITLE
Bagel has a lot of area that isn't covered by sound systems

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#14976]
I've only heard music on the shuttle, arrivals, and security. Halls don't seem to have coverage, for example, and medbay's bare as well.

**Comment by SonixApache** [comment]
I had a medbay sound system rape my ears with that whale/screams track a few rounds ago, so it's definitely covered.
Probably just doesn't have it's own sound system.

**Comment by Kurfursten** [comment]
Yes, medbay is just about the only place that DOES have coverage, the system is on the table by the entrance

**Comment by CptWad** [comment]
after some investigation looks like I forgot to put sound systems everywhere but the hallways
theres a few in other spots (RnD, Robotics, the bridge escape/arrivals, etc)
I got a fix in the works atm
