### ISSUE TITLE
bagelstation crematorium

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#14980]
(WEB REPORT BY: burntdevil REMOTE: 172.93.109.202:7777)
8e7cae21735a8f84968ac795e92d4ff425406b6e 
No button to turn on the cooker.

**Comment by PJB3005** [comment]
I'm just gonna assume this is bagel but dear god the IQ of the average issue rep-

**Comment by Kurfursten** [comment]
Confirmed bagel

**Comment by SonixApache** [comment]
@PJB3005 at least they're reporting things, better than nothing
