### ISSUE TITLE
There's no Radical Steve in Meta and in Deff.

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#14984]
Title says all, how come there's no Radical Steve on those stations?
it's inexcuseable his lack of existance on Deff since it's the perfect breeding ground for cockroaches
also i feel like Meta overral quality would increase to be on par with the other stations if it had a Radical Steve or a Cockroach Egg on maintenance.

**Comment by SonixApache** [comment]
he's box's mascot

since box is trash

**Comment by Jubisloviu** [comment]
@SonixApache but if he's box's mascot why he's also on bagel?

**Comment by SonixApache** [comment]
because bagel is just box but re-arranged

**Comment by CptWad** [comment]
because I put him on both of those maps

**Comment by jknpj** [comment]
but you can spawn roaches using trash

**Comment by CptWad** [comment]
this is an homage to my pet cockroach when I was seven and when It was immediately crushed by my mother when she found it

**Comment by Intigracy** [comment]
Get a real pet

Like a spider

**Comment by AI-Is-Rogue** [comment]
Cockroaches should be on every map, so you can create the anti-rad stuff.

**Comment by ghost** [comment]
better yet, add a way for cockroaches to be introduced mid-round

**Comment by Exxion** [comment]
There is one
It's a truly awful idea to actually do it though
