### ISSUE TITLE
[Bagel] station salvage shuttle can't dock at station

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#14996]
I tried sending it from Station North to Auxiliary Docking and the ship Wouldn't move.
Other docking destinations are probably broken as well
- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by CptWad** [comment]
ah hell I know why
