### ISSUE TITLE
Fix or remove vox raiders

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#14995]
Vox raider rounds last for 8 minutes. Add more objectives or just remove it.

**Comment by TheFriggenSawbones** [comment]
just saying, since no one wants to step up to the plate remove it.

nexis' rework doesn't work very well. Its in an even worse state after it, actually.

**Comment by Durgen** [comment]
inb4 something something datums

just remove it for the meantime

**Comment by strawberrytan** [comment]
What if we encouraged vox Raiders to understand that objectives are a suggestion and gave them an overarching goal to steal shit and be fun

**Comment by SonixApache** [comment]
That happened, they got fucked by suit sensors and it still wasn't fun.
Or maybe it was, I don't know what constitutes as 'fun' for vox.

**Comment by ghost** [comment]
Just replace it with plasma ops, a syndicate plasmaman group who have to steal the plasma miner and other plasma accessories

**Comment by gbasood** [comment]
Christ
How many times do I have to say this
This is, in reality, an admin issue. We can set the occurrence rate to 0 in the secret repo if you get admin consensus

**Comment by Durgen** [comment]
colab coup d'état,  when

**Comment by Exxion** [comment]
I still think we should revert N3X15's changes and just remove the mode from rotation until antag datums are finished, at which point we can re-add it as a tensioner-only thing

**Comment by gbasood** [comment]
No need to remove n3x's changes, though

**Comment by Exxion** [comment]
Other than that they're dumb
Or at least the organ harvesting one is
I don't remember what the others were

**Comment by gbasood** [comment]
~There's a server poll up now for this.~
whoops nevermind

**Comment by Exxion** [comment]
You sure about that?

**Comment by gbasood** [comment]
whoops

**Comment by ShiftyRail** [comment]
No longer applicable as of dynamic mode :tm:
