### ISSUE TITLE
Bagel vox outpost

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#15001]
There's a dead APC in the hallway near engineering

There are no lights in the antechamber to the tarjan genetics room.

There was also an air alarm with no power somewhere.

**Comment by CptWad** [comment]
cant find this air alarm

**Comment by AI-Is-Rogue** [comment]
I believe it was in front of the medical area and dormitories area.

**Comment by CptWad** [comment]
I see no reason why it should be off, its in the same area as an APC, APC is on, its on. so its not me doing it.
