### ISSUE TITLE
Bagel: engineering oversights

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#15009]
These meters could/should be assigned a name and frequency
![dreamseeker_2017-05-24_11-42-56](https://cloud.githubusercontent.com/assets/6307265/26403132/65300824-408d-11e7-80de-5b6f8bb2ebc5.png) ![dreamseeker_2017-05-24_11-42-30](https://cloud.githubusercontent.com/assets/6307265/26403143/720ddecc-408d-11e7-873b-e7f0e8e50524.png)

The SME computer is not linked to the injectors in the chamber, I feel like it should be?
![dreamseeker_2017-05-24_11-43-42](https://cloud.githubusercontent.com/assets/6307265/26403155/80d993ec-408d-11e7-9f9d-f33b5d149aea.png)

**Comment by CptWad** [comment]
fuck

**Comment by SonixApache** [comment]
NAME ALL THE PUMPS TOO

**Comment by CptWad** [comment]
no to the SME stuff. Just set it up u-r-self 
did it all else. Next pr.
