### ISSUE TITLE
Changeling Vial doesn't Display Objectives

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15005]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
When using the changeling vial, the objectives only show up in the notes section.

Also I feel the opening text when using the vial properly states if you're the same person or a changeling who took over the host

**Comment by Gunosaguki** [comment]
Doesn't properly state*

**Comment by Shadowmech88** [comment]
>contents of vial leap at you
>you pass out
>"You feel your consciousness slipping away..."
>"Finally, we once again have a suitable body."

I don't know how it could be any clearer that there was a changeling inside the vial and it took over your body.

**Comment by Gunosaguki** [comment]
Because it could simply imply you used to be a changeling and reemerged. Im nitpicking but it honestly didnt come to mind when i first read it. I read to many villain monologes.

regardless, my first comment still is an issue.

**Comment by Blithering** [comment]
The same is true of the stone mask, one round a while back I was turned into a vampire with it, and didn't know I had any objectives until the results screen.
