### ISSUE TITLE
Traitor Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15006]
(WEB REPORT BY: kingcorg REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

Traitor objective to get the Captains Antique gun, Case was opened fine, shows laser gun sprite on my screen and I cannot grab it

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Exxion** [comment]
This was confirmed to actually not be the case. Someone else just grabbed it first. Let's all laugh

**Comment by Exxion** [comment]
Wait
It showed the sprite?

**Comment by mtpowell** [comment]
Someone swapped it out with a regular egun and it wouldn't let them remove it(even with captains ID)

![](https://i.gyazo.com/e70ac8af0681f64e67bafbcebac27f5a.png)

**Comment by Blithering** [comment]
Not a bug, first time you open a display case with ID and remove the contents it registers your fingerprint as an access requirement. Smashing the case would have also allowed you to smash the fingerprint scanner to get that regular egun floating there.
