### ISSUE TITLE
Summon Arcane Golem as a wizard is hilariously unusable

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15019]
The magic missile that arcane golems will launch will target other golems and the wizard itself.  The Lightning they launch kill the wizard and the other golems.  The fireball the golems launch will generally just explode directly on top of the golem itself, potentially harming the wizard due to their proximity to the wizard on summoning.  It also outright kills the golem.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds (if it was ever used)
- [ ] Issue happened in a recent (less than 7 days ago) round (see above comment)
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
What if summon arcane golem just spawned an adamantine golem apprentice with your spells?

**Comment by ghost** [comment]
I forgot to mention that upon summoning multiple golems, you will outright kill yourself upon using any of those three mentioned spells (lightning, fireball, and magic missile) upon cast.

**Comment by Blithering** [comment]
Maybe have it cast spells independently at targets not in the wizard faction rather than mirroring your casts, possibly with altered golem-specific versions for spells like magic missile so the missiles only track the target it was aimed at
