### ISSUE TITLE
jury rigged space helmet sprite isnt good anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15015]
(WEB REPORT BY: zubron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 90828731c272fd1cdc2f0bb08d01d4d8c7d2ff8b 

>General description of the issue
Not sure how to explain this very well, but the jury rigged space suit helmet's sprite is shit now. It used to have an actual, handcrafted sprite in the past. Now, when you finish adding the firefighter helmet to the assembly, the sprite turns shit.

>What you expected to happen
The good sprite.

>What actually happened
A shit sprite.

>Steps to reproduce if possible
Space blanket on a gas mask. Cable coils on that. Then a firefighter helmet. Once you add the firefighter helmet, the sprite turns shit. It wasn't like that before. What the frick?

**Comment by Exxion** [comment]
What the fuck? Somehow its item icon got replaced with its worn icon.
Like with directions and everything.
![](http://i.imgur.com/XXkF83o.gif)

**Comment by SonixApache** [comment]
This is probably my fault, I'll look into it.
