### ISSUE TITLE
Centcomm items can create antags after the round has ended, making admin investigation more frustrating than it really needs to be

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#15011]
Even better THEY DON'T ADD LOGS THAT ADMINS CAN SEE
Seriously whoever did this has no foresight
Or ability to check for runtimes since they did that too before I fixed (some) of them

**Comment by Intigracy** [comment]
Which items?

**Comment by CptWad** [comment]
The changeling vial and vampire mask

**Comment by Shadowmech88** [comment]
Why do we even have those items on Centcomm?

**Comment by CptWad** [comment]
Thought it was a good idea at the time. I could change it ez

**Comment by Blithering** [comment]
Or just move them somewhere inaccessable without adminporting

**Comment by CptWad** [comment]
They should be. Think the way inis via rcd. Ill just properly wall it off or delete the offenders

**Comment by gbasood** [comment]
They've gotten in with:
captain's spare
ripley
baguloth

**Comment by MadmanMartian** [comment]
@Shadowmech88 @PJB3005 Fairly certain the items were removed from all maps. This is now void
