### ISSUE TITLE
Infinite Energy as a Cyborg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15014]
(WEB REPORT BY: showmethelogs2 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
90828731c272fd1cdc2f0bb08d01d4d8c7d2ff8b 
>General description of the issue
Cyborg's energy continually increases and exceeds maximum value.

>What you expected to happen
For the charge to decrease 
>What actually happened
Charge increases

>Steps to reproduce if possible
Roll cyborg, do not choose a name for a few minutes, stand still, then choose a name.

**Comment by Exxion** [comment]
I assume there was some kind of runtime in setup, but my connection was way too bad to really learn much from VV or the runtime log at the time.
I did see one borg-related runtime that I haven't seen before, but I have no idea at the moment if it was related to the bug.

**Comment by Uqualm** [comment]
See 
![its me sarca u dumbfucks](https://cloud.githubusercontent.com/assets/11592349/26430892/b560ef30-40be-11e7-84cb-28e8aba58406.png)

**Comment by Exxion** [comment]
With Z-level range?

**Comment by SonixApache** [comment]
@Exxion Yes.

**Comment by Exxion** [comment]
Wow.
It still shouldn't go above the cell's max capacity but I kind of don't want to leave this open
