### ISSUE TITLE
Revsquad issue listing/adoption thread

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#15010]
Since it looks like revsquad will be voted out of rotation, and I'm not putting additional effort into it, I'd like to put this up as a general discussion thread, as well as give other people the opportunity to let other people know if they're going to work on the mode.

For discussion I'd like to hear:
 - How rounds typically play out, form both antag and non-antag perspectives.
 - Issues with specific mechanics (random item spawning, communication/coordination capabilities, the team's objective)
 - IF you can think of some good, specific changes, describe them.

**Comment by ghost** [comment]
Revsquad and revs should end in minor head victory if atleast one head evacuates so exempt z level 2 and whatever the shuttle z level is from being off station
This'll force revs to force a recall and continue the hunt and they don't get a free win if the shuttle is called

**Comment by ghost** [comment]
Wait is this for just ideas

**Comment by Blithering** [comment]
From what I've seen, it usually starts with one of the squad (probably the most armed) making an attempt on a head of staff's life, successful or not, from there all the crew go on high alert expecting revs. This pretty much forces the rest of the squad to lie low and usually continues with no further attempts until the shuttle is called, or the security staff's random implantation finds the rest. With little to no possibility to recruit and little equipment, there's not much a revsquad can do against heads once they lose the element of surprise.

If  I were to suggest improvements, I'd probably either up the number of starting squaddies or guarantee the limited flash is given to one, and increase the number of items each squaddie spawns with. Something to encourage more activity on the part of the antagonists, and involve more crew in the round.

**Comment by gbasood** [comment]
@Commandersand kind of yeah
unless someone wants to work on the ideas it's just a discussion
it's mostly me saying "i'm not gonna work on this so someone else can, here's what people don't like about it"
