### ISSUE TITLE
The m1911-P and children of the Pulse Rifle will have their sprite and icon disappear upon firing.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15027]
The m1911-P and all children of the pulse rifle (/obj/item/weapon/gun/energy/pulse_rifle/) will disappear upon firing and their icon state will switch from "m1911-p" to "m1911-p-1.#IND". This occurrence causes the gun's sprites and in-hands to go invisible.

**Comment by PaulRitter** [comment]
outdated, please close
