### ISSUE TITLE
Slime Language is really hard to read in chat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15028]
(WEB REPORT BY: knightkiller REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
90828731c272fd1cdc2f0bb08d01d4d8c7d2ff8b 

>General description of the issue
The slime race's language is very light blue. On a white background this makes it nigh on impossible to read on some monitors (Like mine)

>What you expected to happen
For the text to be appropriately readable (Maybe change the font and make it pink?)

>What actually happened
Light blue on white background

>Steps to reproduce if possible
Become Slime Person, Speak in slime, fail to read it without selecting it or squinting

**Comment by Shadowmech88** [comment]
I made it the same color as slime blood.
I'll change it if someone suggests a good alternative color.

**Comment by ghost** [comment]
Dark blue or green
