### ISSUE TITLE
Crashing from newscaster interaction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15026]
(WEB REPORT BY: zimmu REMOTE: 172.93.109.202:7777)
Every time I interacted with the newscaster after submitting an article on the feed, it would crash if I interacted with it. May have been due to the tildes in the story?

**Comment by Sooose** [comment]
I've had this issue for awhile and never reported it. I get an invalid argument popup and then the game freezes. For me I don't use tildes, it just happens most of the time I try and submit a story to the newscaster.

**Comment by Eneocho** [comment]
tested a while, can't reproduce, seems to be fixed.
