### ISSUE TITLE
The Xenobiology Atmospheric Computer on Box Station becomes a Central Atmospheric Computer with this one, simple trick.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15023]
The Xenobiology Atmospheric Computer becomes a Central Atmospheric Computer if you simply screwdriver the screen out and screwdriver it back in.  This is capable of controlling all air alarms on the station.

**Comment by FudgePucker** [comment]
Funny thing is that they can just print the board in research
