### ISSUE TITLE
Soviet hardsuit sprite is invisible on greys

### ISSUE THREAD

**Issue by JustSumBody** [d3athrow/vgstation13#15031]
It does that thing where it overrides all your other layers(glubs and shoes) like a hardsuit does but it looks like you're wearing nothing at all
Helmet is fine however.

**Comment by Intigracy** [comment]
it's probably named wrong in the dmi

**Comment by Intigracy** [comment]
that or it's got species_fit set with no actual sprite to back it up

**Comment by DamianX** [comment]
close it
