### ISSUE TITLE
we is of winnings, yes?

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15033]
#### Description of issue

Random Weighted Vote Result: Defficiency/ with 3 votes and a 12% chance of winning 
	Box Station/ had 3 vote and a 12% chance of winnings 
	Bagel Station/ had 18 vote and a 72% chance of winnings 
	Metaclub/ had 1 vote and a 4% chance of winnings

>18 vote

>winnings

#### Server revision

5b80bd4bafec023fc7dd385ab09704f52a7cf02f

**Comment by ghost** [comment]
what is the issue here?

**Comment by ghost** [comment]
Box is still in rotation

**Comment by PJB3005** [comment]
I think he means the the fact that it should be winning instead of winning**s**.

**Comment by SonixApache** [comment]
and votes instead of vote
