### ISSUE TITLE
radiation event is busted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15043]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

3b727e7bfb1e89d66fcc4faa450118ffc43f6684 

>General description of the issue

The initial message fires, but there's no radiation.
`High levels of radiation detected near the station, ETA in 30 seconds. Please evacuate into one of the shielded maintenance tunnels. `

**Comment by ghost** [comment]
It runtimed for some strange reason

[14:55:43]DEBUG: Runtime in <b>radiation_storm.dm</b>, line <b>34</b>: <b>Cannot execute null.radiation alert().</b> <a href='?_src_=holder;viewruntime=[0x210283a8]'>[view]</a>
