### ISSUE TITLE
[BAGEL] another reversed intercomm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15041]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

3b727e7bfb1e89d66fcc4faa450118ffc43f6684 

>General description of the issue

https://puu.sh/w1Xiu/c5f80eb126.png

**Comment by SonixApache** [comment]
This is at security somewhere, obviously. Very helpful bugreport.
Might also be one in the meeting room, on the table in the center.
