### ISSUE TITLE
Salvage shuttle interior glass airlocks sometimes bolt randomly.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15059]
(WEB REPORT BY: turbogay REMOTE: 172.93.109.202:7777)
Revision: 32b39d13bf6bc22284abcec26abe4e35c7e30181 
Issue: Sometimes the salvage shuttle internal glass airlocks in back are either bolted when I arrive to them or when I get within one tile of them.

The internal glass airlocks normally are not bolted and I did not see anything about it in the changelog.

Doors bolted as soon as I was within one tile of them, only happens with the interior ones.

To reproduce I would try to wait a short amount of time before going to the salvage shuttle then opening the first airlock and walking next to the internal one and seeing if it bolts.

**Comment by ghost** [comment]
Which map this occurs on would have been nice

**Comment by Durgen** [comment]
I cheese the salvage shuttle all the time and I've never seen this

**Comment by Kurfursten** [comment]
It's possible that someone was using remote signallers, that's is my favorite thing to do with the salvage shuttle doors. I even get a pAI to be doormaster if I can.

**Comment by Exxion** [comment]
Apparently it happened to him in at least two separate rounds
*shrug

**Comment by TurboGay** [comment]
@Skullyton Happened to me on Deff and Metaclub, I can take screenshots if that would help.

Would they not need to physically be there to attach signalers though? I'm usually there pretty quickly and never seen signs of other people being there.

**Comment by FudgePucker** [comment]
Maybe the ship is being haunted by the previous crew.
