### ISSUE TITLE
Free Cultist Rune Nullspacing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15054]
(WEB REPORT BY: goodguy1448 REMOTE: 172.93.109.202:7777)
25056c3b92dc234dd02c13f5418e8d4cf6ec6214

Two guys tried to get me out of TeleSci with a Free Cultist Rune and i ended up nullspaced (I saw the 2 guys who casted the rune for 1 sec and then the screen went back). Zealtron unbuged me anyways. I ended up in the science outpost at the roid. This was on Metaclub

**Comment by PJB3005** [comment]
> using his name as issue title.

nice.

**Comment by Exxion** [comment]
I'm legitimately going to bwoink him for that next time I see he's online

Not like actually punish him, just meme at him

**Comment by Exxion** [comment]
Anyway I think this was already reported, but I couldn't find it
