### ISSUE TITLE
Bagel: Minerals are SPARSE

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#15062]
There is such a low density of minerals on the main asteroid. Why is this?
You need a drill to get anything of worth.

**Comment by PJB3005** [comment]
Sounds good to me.

**Comment by PJB3005** [comment]
Sounds good to me.

**Comment by Wizardcrying** [comment]
@PJB3005 What do you mean?

**Comment by Kurfursten** [comment]
There are some people who believe that minerals should be a bit rarer. You know, you really only need to mine out one of each and R&D will be set for the shift, unless they really want a lot of diamond heavy gear like bags.

I kind of think of it from the opposite direction, though: maybe R&D costs are too low and mineral scarcity is just fine.

**Comment by Wizardcrying** [comment]
I think they're just TOO scarce.

**Comment by Kurfursten** [comment]
Go straight down from the mining outpost to get this high spawn field
![untitled](https://cloud.githubusercontent.com/assets/9782036/26532060/2e86c2d0-43bd-11e7-92c8-99a2d9e19594.png)


There's another bigger one to the right of the gulag asteroid, but it's farther away and you have to fly around the research outpost

**Comment by CptWad** [comment]
Not a bug, its just that the asteroids a different layout and you just have to get used to it.
Also good excuse to get a jetpack
