### ISSUE TITLE
Glowing Orbs Drift in Space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15061]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
For magical orbs that follow you by hovor, I noticed once I entered space they just drifted instead of continuing to follow, which kind of makes them worthless for their purpose, doesnt it?

Just reporting incase this wasnt intended

**Comment by Gunosaguki** [comment]
Hover. Fuckin typos

**Comment by ghost** [comment]
good spot
