### ISSUE TITLE
Internal bleeding is a joke for vox specifically

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#15068]
One of the more minor racial upsides for vox is that they have a couple extra extra chems for healing toxin damage. (Gravy, which heals toxin damage at double the rate of antitox but is metabolized significantly faster, and nitrogen, which heals toxin at the rate of antitox and suffocation at the rate of dexalin, but is metabolized 20 times more slowly.) (Neither has the reagent clearing property of antitox though.)
In nearly all scenarios, this is barely useful. Nitrogen is mostly just useful because it lasts a really long time. It can keep you alive and awake at a slightly lower blood level and it can extend how long you can survive without a mask and tank for quite a while, but not indefinitely.
There is, however, one case in which nitrogen is really, really good, though: Taking along with absurd amounts of bicard to heal internal bleeding. Antitox works for that too, but you need to take only 5% as much nitrogen for the same amount of bicard. Plus, it heals some oxygen damage from your low blood, as well.

Proposal: Make the bicard OD deal more damage to vox.
Or nerf nitrogen, but please don't

**Comment by ghost** [comment]
I don't really see the issue.
If you're healing internal bleeding with bicard, you're guaranteed to have antitoxin at hand. If anything, antitoxin is more common than nitrogen probably.

**Comment by Exxion** [comment]
You need something like 1u antitox for every unit of bicard above 30
Or .05u nitrogen for every unit of bicard above 30
And chem dispensers just dispense nitrogen

**Comment by ghost** [comment]
Seems more like an issue of nitrogen metabolism in general rather than some interaction with internal bleeding I guess

**Comment by Exxion** [comment]
Yes, but it's only really powerful when combined with a bicard overdose
Or I guess other overdoses, but bicard is the only one worth anything

**Comment by Gringonius** [comment]
Just remove nitrogen being a super anti-toxin for vox, really. It doesn't have any actual reason to act that way.
The chems cloning gives to new vox bodies would have to be replaced with regular anti-toxin, though.

**Comment by Exxion** [comment]
Man nitrogen is so nice though

Although it would honestly require some impressive mental gymnastics to not classify its preposterously slow metabolism rate as an oversight
