### ISSUE TITLE
MaMIs turn into real brains when implanted

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15072]
#### Description of issue
A Machine-Man Interface, when filled with a live posibrain and implanted into a debrained corpse, turns into a completely organic brain. Not sure if this is a feature.

#### Difference between expected and actual behavior
>Implant MAMMI, attach brain, de-attach brain, remove MAMMI, recieve MAMMI with posibrain
vs
>Implant MAMMI, attach brain, de-attach brain, remove MAMMI, recieve completely organic brain

#### Steps to reproduce 
- Acquire a MAMMI
- Place a live posibrain in it
- Debrain a monkeyman
- Implant and attach MAMMI
- De-attach and remove MAMMI

#### Specific information for locating
![image](https://cloud.githubusercontent.com/assets/8468269/26554870/b9ad3daa-4492-11e7-8536-4ce81d0122ad.png)

#### Server revision
6d320b561b3440df7434d3d8513e674cea9868eb

**Comment by Shadowmech88** [comment]
I don't believe it's intentional.

**Comment by toomykins** [comment]
They shouldn't even be able to be put into MaMMI's. it's just a byproduct because posibrains and brains are both classed as "brains"

**Comment by Shadowmech88** [comment]
It sounds like you're confusing MaMI with MMI.
