### ISSUE TITLE
Arm Borer Server Crash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15092]
(WEB REPORT BY: rhimrifer REMOTE: 172.93.109.202:7777)
>Revision
34d4d0255dc8f22a7e7cac60ec87927231cd4e5b

>General description of the issue
Arm borers can cause the server to crash when using the utility hook

>What you expected to happen
Not crash

>What actually happened
Crash

>Steps to reproduce if possible
I have only seen it happen twice now. The most recent time the person with the borers said he had 2 utility borers. Screenshot from the thread from most recent crash:
https://dl.dropboxusercontent.com/s/nyxub6agl257usb/borercrash.jpg

**Comment by ghost** [comment]
same can also happen with the hookshot. Gonna take a look now

**Comment by AutismSpider** [comment]
not 1st time its happen with borer hook/hookshot gun.

**Comment by Shadowmech88** [comment]
I believe this was fixed by #15818.

**Comment by N3X15** [comment]
Issue occurred again on October 2nd 2017. 
![1506992474549](https://user-images.githubusercontent.com/110073/31105994-eb645c26-a79c-11e7-9433-bf1a55ab0b98.jpg)

**Comment by Shadowmech88** [comment]
This was fixed by #16220.
