### ISSUE TITLE
Santa's Corgi Helper Spawns on Defficiency Instead of Ian

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#15099]
I'm guessing it's a Christmas thing that someone forgot to remove.

**Comment by ghost** [comment]
probe left a few easter eggs around on maps, deffs case it's Ian having a santa hat

**Comment by Shadowmech88** [comment]
Oh, I thought the only Easter eggs he left were hidden in maint and such.

**Comment by SonixApache** [comment]
i for one don't think it belongs

**Comment by Blithering** [comment]
It would be neat if the christmas stuff was moved to a timed thing like the valentine's chocolate was

**Comment by Shadowmech88** [comment]
The Christmas stuff is still in the code, it's just not placed on the map.
The problem with trying to automate the placing of things on the map, based on the date, is that it'd have to be done in a proc, and the positions in the proc would not keep up with the positions on the actual map.

Like, if someone reworked a department, come Christmas time all the garland and wreaths and such would be in the wrong places, unless we mandated that everyone who edits a map also edits all the holiday object placement code which I don't want to do.

**Comment by Blithering** [comment]
Ah, fair enough. Maybe just keep a copy of the christmas version of the map from last year in the files so they can be more easily compared when the time of the year comes around and remove them from the standard then?

**Comment by Shadowmech88** [comment]
Technically, we already have that. You can view/download any file in its entirety at any point in history on Github.

**Comment by SonixApache** [comment]
Why not just auto-equip Ian with a santa hat on christmas?

**Comment by Shadowmech88** [comment]
That'd work.
Just Christmas, though, or all of December 1st through 25th?

**Comment by Blithering** [comment]
I'd say all December

**Comment by Exxion** [comment]
>The problem with trying to automate the placing of things on the map, based on the date, is that it'd have to be done in a proc, and the positions in the proc would not keep up with the positions on the actual map.

Just use mapped landmark objects that only spawn the decorations during the proper time of year

**Comment by Shadowmech88** [comment]
Like, wall garlands that always show up in the map editor but only show up in-game during Christmas?

**Comment by Exxion** [comment]
Yeah
