### ISSUE TITLE
BagelStation, no way to activate shower without using Alt-click

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15107]
(WEB REPORT BY: wulfel REMOTE: 172.93.109.202:7777)
Because the shower curtain is on top of the shower itself, you can't actually click the shower to turn it on unless you Alt-click to show everything in the tile in your tab window.

**Comment by CptWad** [comment]
refering to multiple showers.
this is a problem with the shower curtains themselves, I want to use them but they cover the sprite
I can adjust it in a few places but theres others that would have to be forced to have this problem.
One way would be to have two more "open" curtain sprites that are all bunched up on one side of the square
