### ISSUE TITLE
Tajaran has human meat and teeth

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15108]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The tajaran in bagel maint drops human teeth, when butchered gives human meat.

>What you expected to happen
Cat meat and teeth

>What actually happened
Human meat and teeth

>Steps to reproduce if possible
Kill the tajaran in bagel maint, apply toolbox to mouth, then butcher.

**Comment by Intigracy** [comment]
After species is applied, people need to have their teeth and butcher drops regenerated.

As is all species have human stuff.

**Comment by Eneocho** [comment]
they make tajaran teeth (snowflake human teeth), cat hide and tajaran meat (generic mob meat) now, seems to be fixed.
