### ISSUE TITLE
Weapon Rechargers

### ISSUE THREAD

**Issue by jakmak3** [d3athrow/vgstation13#15104]
Lets talk about gun chargers. As it stands now the energy weapon chargers are map objects and admin spawn only meaning they cannot be acquired by any other means. On every other codebase however they can be built. The reason we havent done it here is it would be a powercreep balance hell because there are about 4 possibilities for how chargers could be made by players

1. Cargo order

2. Protolathe/circuit imprinter

3. mechanics flatpacker/genfab

4. Solder iron

The first one would be having them under cargo order. However this would only help gun cargo and due to how difficult it is to order stuff from cargo without access and actually get it delivered it would be locked under cargo only. It should be noted the cargo RCS needs to be charged via gun charger and once depleted unless you steal a charger from sec/mining it cant be recharged

The second would have the recharger made via protolathe or having the board for the recharger in the circuit imprinter and having it be built like a normal machine with stockparts. Both of which would be good for gun sci (which is less common now) but it would still lock it down to sci only and with how clunky and annoying it is to build new machines Manually since the RPED costs far far to much to make it would never be seen

The third having them be scannable and producable via mechanics flatpacker/genfab would actually probably be the best and give mechanics more of a purpose since all the usefull things the genfab can make are either Unscannable or need a traitor scanner since the protolathe here cant produce that much in the way of usefull here

The last is the most retarded of all. Adding a recharger board to the solder iron. This would allow any assistant to make one and would be a horrible horrible idea since weapon rechargers would go from being an esoteric device only createable by the gods to being a common piece of machinery that can be made from nothing

In my opinion we should try options 1,2 and 3, Locking the recharger to a single department would be powercreeping a single group while leaving others in the dust since they are unlikley to share. Cargo order, buildable by protolathe and scanable by mechanics would probably be the best way to go with these

**Comment by SonixApache** [comment]
*sec-only ammolathe*

Mod the constructable hand-crank chargers to allow them to recharge guns.

**Comment by ghost** [comment]
your issue with adding it to the iron is allowing any assistant to make one, but you want to add it to cargo, science, AND mechanics?

edit: sec only ammolath is unironically a good idea

**Comment by jakmak3** [comment]
adu6oo what do you suggest we do to add this to being made by players WITHOUT it being retarted powercreep or accessible to any assistant

**Comment by ghost** [comment]
sec only ammolath

**Comment by jakmak3** [comment]
didnt think of giving sec a way to get them since they dont get any machinery or tools. So giving sec a new machine roundstart that can make ammo/rechargers if it was a autolathe but for bullets?

**Comment by SonixApache** [comment]
***Ammolathe***
Multi-function lathe that can shit out rechargers, ammo, guns, gun mods, etcetera. Given to sec at roundstart, with a tiny amount of materials. Syncs to research to unlock more shit.
See also: #9909

**Comment by Blithering** [comment]
> Mod the constructable hand-crank chargers to allow them to recharge guns.

VOLT DRIVERS WHEN
![volt_driver_m2033_hud2](https://cloud.githubusercontent.com/assets/15067109/26707898/f053ca54-473f-11e7-9c5f-e6af95579ce7.png)

**Comment by Rattlederp** [comment]
@Blithering watch how uncle Bourbon works. Great idea tbh
