### ISSUE TITLE
[Bagel] cargo has no shuttle timer display

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#15119]
WAAAAD

**Comment by DamianX** [comment]
The conveyor belt is fucked as well in some way but I don't remember exactly how and I'm not going to test it, instead I will leave this barely helpful comment right here and not open a separate issue.

**Comment by Durgen** [comment]
https://github.com/vgstation-coders/vgstation13/issues/14884

there is a closed issue about the bagel cargo belts, but they could use more work

**Comment by yclatious** [comment]
Its the belt that transports cargo from the shutle to the station, the first belt is backwards and instead of transporting stuff down it tries to transport it up, I was just too lazy to report it.
