### ISSUE TITLE
You can send money through PDA even in z-levels with no signal to messaging server/radio/nothin'

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15110]
so people can dial 911 while lost in space WEEWOOWEEWOO

**Comment by SonixApache** [comment]
oh no, someone did it

**Comment by DamianX** [comment]
Okay, how should it be fixed? Require a connection to the PDA messaging server?

**Comment by SonixApache** [comment]
Do ATMs work when the accounts database isn't on the same Z-level? If not, you could use that.
Else yeah, make it check if the PDA messaging server is on the same Z-level and if the accounts database is online.
