### ISSUE TITLE
Cyborg Specializations

### ISSUE THREAD

**Issue by Rattlederp** [d3athrow/vgstation13#15118]
Feature request. I had an idea the other day that I thought would be neat and I'd like some input. What if cyborgs could choose their type for different bonuses when they spawn? I was thinking we could give the bay cyborg variants (Android, Cyborg, Robot) some practical purpose. Here's my idea. I would assume something like this wouldn't be particularly hard to code? But I have no coding experience so I'm probably wrong

You spawn as cyborg, choose name, module, and then ~~chassis~~ type. 
3 different ~~chassis~~ types
**Android ~~chassis~~**
- Less overall health (Because the chassis is more human-like, more fragile joints)
- More damage from EMP/Longer EMP stun? (Because more sensitive electronics)
- Moves faster than humans (No idea how much faster. V-TEC speed? Makes sense, again, cause androids would be more human-like and therefore more agile)
- Most advanced programming/complex personality roleplay wise if you're into that kind of thing

**Cyborg ~~chassis~~**
- Regular cyborg that we have now

**Robot ~~chassis~~**
- Moves at skeleton/diona speed
- Takes considerably less damage from EMP (less complicated electronics) 
- Is not stunned by EMP? Or some other bonus? Much shorter EMP stun?
- Simple/Obviously programmed personality roleplay wise if you're into that kind of thing

**Comment by jknpj** [comment]
Human brain = Cyborg (Roundstart cyborgs)
Posibrain = Android (Posibrain cyborgs)
No brain = Robots (Brainless cyborgs like hugborgs)

This has nothing to do with their chassis at all

**Comment by ghost** [comment]
Only being able to make AIs out of posis when?
It's not artificial if it's a human brain

**Comment by Rattlederp** [comment]
@jknpj alright well ignore the shitty lore part then. Call it whatever you like.
Taking that into account though, maybe the robot one wouldn't drop any brain on death/deconstruction as one of its negative side effects instead? Maybe give it almost human speed to make up for that?
And then Androids drop only posis when killed/deconstructed?

**Comment by toomykins** [comment]
i don't really understand why cyborgs are as fast as they are now.

**Comment by FudgePucker** [comment]
Being faster is the best choice

**Comment by Rattlederp** [comment]
@FudgePucker I figured that'd be the mentality, because combat is about speed, which is why I was thinking they wouldn't get too much of a speed boost. Then, offset the speed by making them easily disabled even with a half-assed EMP shot. The lower health should be low enough to make them almost as easy to robust with an extinguisher as a human
As for the robot, I think it'd be an interesting take on playing cyborg. You're much less affected by the most reliable way to kill you, EMP, but at the cost of speed. Maybe give them a health boost too. 
~~I just want to be a cyborg snowflake~~

**Comment by FudgePucker** [comment]
Cyborgs as it stands isn't always about combat.
EMPs are only encountered in situations with antags or if your covers blown when malf.

Why go cyborg over android when playing as medical engineering or service? Hell having the speed boost as ~~security~~ peacekeeper is more important, people can just out run you.

A better idea would be having specifications, engineering could choose between having a plasma tank pickuper inserter or a device to carry canisters (oh man even I have to call feature creep on that first one, number one benifit MoMMI has over engineering borg is being able to set up radiation collectors), medical choosing between a inflatable sleeper that can be deployed or a pez dispenser for pills, mining choosing between excavation drill or the cargo pad device, service choosing between a card dealing device (picks up drop decks, shuffle, and deals) or a food service arm (picks up and places food and drinks, letting you arrange food on tables neatly).

**Comment by Ephx1** [comment]
Not sure about that other stuff, but I _would_ like a choice to have a human brain/posibrain and maybe being straight up robot like you said.

**Comment by Rattlederp** [comment]
Well definitely some good ideas from everyone in here now, much better than what I hoped this would be initially.  Maybe someone will be inspired to code it at some point, what Ephx said it probably the most realistic implementation
