### ISSUE TITLE
Vending machine pack movement onto pylons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15125]
(WEB REPORT BY: smedley8 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

775c9e72c3a7b19cab2d4a63bdf521f5a7599d6f 
>General description of the issue

As an Artificer, on bagel, I moved into a vending machine recharge pack while a pylon was opposite to it.

The game proceded to crash, there was no error messages or any sort of client response other than the standard "Dreamweaver.exe" has stopped responding.

>What you expected to happen

Nothing at all.

>What actually happened

The game crashed.

>Steps to reproduce if possible

As an artificer move into a vending recharge pack while it is opposite to a pylon.

**Comment by Exxion** [comment]
Dreamseeker.exe, you mean?

**Comment by DamianX** [comment]
Predictably doesn't happen 
![image](https://user-images.githubusercontent.com/6307265/47085153-059ba500-d216-11e8-82d0-a32f90d74624.png)
