### ISSUE TITLE
Swiss Army Knife Wirecutters Can't Hack Doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15122]
(WEB REPORT BY: wutnold124 REMOTE: 172.93.109.202:7777)
>Revision 775c9e72c3a7b19cab2d4a63bdf521f5a7599d6f

>General description of the issue
Swiss Army Knife wirecutters don't work when cutting door wires.

>What you expected to happen
The wirecutters in a swiss army knife to cut a wire.
>What actually happened
The game said "You need wirecutters!"

>Steps to reproduce if possible
Get a swiss army knife. Screwdriver a door's panel open. Try and cut a wire in the door.

**Comment by Shadowmech88** [comment]
@DrSnips did you ever fix this? I know you intended to.

**Comment by DrSnips** [comment]
I did, #15830
