### ISSUE TITLE
Atmos/Engineer Vox start with extended capacity oxygen tanks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15120]
(WEB REPORT BY: knightkiller REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
82637aa5c1d23846bc636a3806bd1855bbb4bfaf 
>General description of the issue
Rather than the vox default nitrogen tank in the survival equipment box, its an extended oxygen tank

>What you expected to happen
Have an emergency nitrogen tank (Or perhaps an extended variant)

>What actually happened
Had an extended emergency O2 tank

>Steps to reproduce if possible
Join as engineering vox

**Comment by DamianX** [comment]
Why do we not have extended nitrogen tanks?

**Comment by Knightkiller11** [comment]
I mean, at least since I was an engi I could just use a pump to empty then re-fill the oxygen tank with nitrogen, but I guess its the principal of the matter? Extended nitrogen tanks would also be useful for vox who don't wear suits, reduces the times you need to go and refill

**Comment by Durgen** [comment]
could traders get extended capacity nitrogen tanks also? 
I empty an extended capacity oxygen  tank and fill it with nitrogen every round I buy the coat

**Comment by Kurfursten** [comment]
While I've pushed for Trader QoL in the past, I think traders should still have to fill their own air tank if they want to use a pocket size one. That's just part of living ghetto.

**Comment by Blithering** [comment]
On a similar note, will plasmamen ever get small plasma tanks?

**Comment by DamianX** [comment]
When You Sprite It

**Comment by Blithering** [comment]
They're already sprited though.
