### ISSUE TITLE
Vox Atmos Techs start with wrong emergency tank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15121]
(WEB REPORT BY: commondragon REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
775c9e72c3a7b19cab2d4a63bdf521f5a7599d6f 

>General description of the issue
Vox Atmos techs (and perhaps other engineering positions) start with an extended oxygen tank rather than a nitrogen tank.  It's a very minor issue it's not only easy to fix yourself, but most of the time a vox will never part from their large tank.  Still, it can catch one off guard.

And yes I scanned it first to make sure it wasn't just filled with nitrogen.

>What you expected to happen
Have an emergency nitrogen tank in your survival equipment box

>What actually happened
Have extended emergency oxygen tank in survival equipment box

>Steps to reproduce if possible
1: Set up character as one of the pox
2: Join as atmos tech
3: Check survival equipment box in your backpack

**Comment by Exxion** [comment]
#15120
