### ISSUE TITLE
Disposals pipes allow theft of everything in Space-Mart without consequences

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#15123]
Crate it up and throw it out

**Comment by Shadowmech88** [comment]
Does it at least detect that the items have left the store and lock it down?

**Comment by Exxion** [comment]
Nope.
If you use/destroy one of the items, though, it will lock it down

**Comment by Shadowmech88** [comment]
Would locking down even be a solution? The person could send themselves out via disposal pipe as well.
Should we just destroy anything that attempts to cross over the tiles that make up Spessmart's impenetrable walls?

**Comment by mtpowell** [comment]
Make the walls two tiles thick

**Comment by Shadowmech88** [comment]
They could still place pipes on the outside wall by spacewalking.
Even if the wall was three tiles thick, couldn't they place pipes up to the inner wall, then climb into a bin and ride them until it spits them out on the inner wall's tile, then place a pipe on the center wall and step off of the wall back into the interior?
I feel like it'd need to be at least 4 tiles thick to completely thwart connecting the inside to space via pipes.

**Comment by mtpowell** [comment]
I believe Disposals can't be welded down if there's a wall on the tile

**Comment by Shadowmech88** [comment]
Then how are people placing the disposal pipes to carry the items out?
Are they piping through the foyer and out the entrance instead of through the walls?

**Comment by Exxion** [comment]
@Sooose
Explain please

**Comment by mtpowell** [comment]
@Shadowmech88 
You can place a chute and trunk on the outside of a wall and it'll shoot you on top of the first set of walls and then you can walk off it, similar to building a wall under you.

If there are two walls you can't walk off

**Comment by Shadowmech88** [comment]
That seems more like an issue with disposal pipes being capable of depositing you onto dense turfs at all.
It's probably best that it be made to either drop you on the pipe's own turf, or just have you get stuck in the pipe.

**Comment by Exxion** [comment]
That's not what I saw
They just piped through the doors into the lobby

**Comment by Shadowmech88** [comment]
We could install a small dead-end pipe loop that goes through the door connecting the store and the lobby.
Players would have to remove the anchored pipes in order to install their own pipes leading out, which should trigger a lockdown.

**Comment by Sooose** [comment]
Just noticed I got pinged. You can remove all the tiles on the ground from the lobby area where the tree is up to the cashiers and pipe a diposals system directly through the front entrance. From there you just crate everything up, throw it down the chute where the cashiers are and it arrives in the lobby without triggering any alarms.
