### ISSUE TITLE
There's apparently a guaranteed vault with construct stones and shells on bagel.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15124]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
This seems bad.

**Comment by Gunosaguki** [comment]
it would be fine if it was made harder. As of now I know you can telescience the parts, make that a no go.

Changelings also can slowly fight their way towards it, but thats kind of antag privilege

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Bagel is dead.
