### ISSUE TITLE
Borgs are OP

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15135]
(WEB REPORT BY: izayachan REMOTE: 172.93.109.202:7777)
Delete borgs

**Comment by ghost** [comment]
MUH 300 HP

**Comment by Exxion** [comment]
I've said the word "meme" far too many times today, so sadly I'm not going to try to analyze why this only got one comment.
Because by all rights it should be quite a spicy meme.

Wait fuck
