### ISSUE TITLE
Add basic shit to the Bagel Xenobio

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15136]
(WEB REPORT BY: goodguy1448 REMOTE: 172.93.109.202:7777)
775c9e72c3a7b19cab2d4a63bdf521f5a7599d6f

The Xenobio at the bagel roid is missing basic shit like a regular fire ext. and a wall medkit (Or just add a white medkit to the sleeper room).

I got my chest ripped by an adult slime and ended up bleeding to death because i could't find a fucking gauze.

**Comment by ghost** [comment]
Git gud :^)
But seriously a gauze on the table and a wall extinguisher is good enough
A wall mounted fire fighter closet can be good too.
