### ISSUE TITLE
borgs cant open morgue trays

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15132]
(WEB REPORT BY: molenga REMOTE: 172.93.109.202:7777)
So, I noticed that medical cyborgs cant open or close morgue trays, I understand the no hands as a way to limit medical cyborgs powers in relation to doctors, but not being able to deposit bodies on morgue is retarded as it takes a medic away from his duties just to open and close the daamed things.
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
It really makes no sense that medical cyborgs cant be used for such a menial task as hauling bodies to morgue since they cant open and close the trays.

>What you expected to happen
I expected the borgs to be able to open the tray, if not by hand then in the same way we open doors using shift+click

>What actually happened
Nothing since I have no hands and the code is shit.

>Steps to reproduce if possible
Get a borg and try to open morgue trays, you will fail and will be forced to call a medic to perform such a menial task, taking him away from his much more important duties.

**Comment by ghost** [comment]
Wew boy silicons once again prove the most reasonable and pleasant players by calling a simple nohands oversight "the code being shit".

**Comment by DamianX** [comment]
I mean, the code IS shit.

**Comment by TheFriggenSawbones** [comment]
@Unknown-as-Captain that was quote from me 😄

**Comment by SonixApache** [comment]
Wew boy carbons once again prove the most reasonable and pleasant players by calling a shitcode reporter "unreasonable and unpleasant"

**Comment by ghost** [comment]
I technically​ didn't say that :^]

**Comment by Rattlederp** [comment]
Technically speaking having this would increase your chances of being cloned when you inevitably die. Being in a morgue with the green light instead of on the floor under 3 other bodies is always better, why not let medborgs do that for you?

**Comment by beesil** [comment]
Fixed by #19120
