### ISSUE TITLE
OVER POWERED MIE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15142]
(WEB REPORT BY: bunny232 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
I AM REMOMVING TEETH FROM DEAD BODYS AS A MOUSE. OH GOD I JUST BUTCHERED A BODY FIX THIS AAAAAAAAAAAAAAAAAAAAAAAAA.

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Exxion** [comment]
#15143
