### ISSUE TITLE
[BAGEL] External airlocks near brig are inaccessible to sec

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15146]
#### Description of issue
The ones in maint around the brig. Should give them external access *or* sec access requirements, so officers don't have to walk around to arrivals to leave.

#### Server revision
74db1fa3b9682139521d69a1159523ea63c491a8

**Comment by CptWad** [comment]
You mean like other maps? I think only deff has such features
not that I cant add them

**Comment by SonixApache** [comment]
I added such features to box. Or I tried, at least.
