### ISSUE TITLE
holoswitch multitool doesn't work on doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15140]
(WEB REPORT BY: izayachan REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When using a holo multi-tool, I get the message "You need a multitool!"

>What you expected to happen
The holoswitch functioning as a multi-tool

>What actually happened
The message "You need a multitool!" appears on my screen

>Steps to reproduce if possible
Use a holoswitch multitool on a door

**Comment by Shadowmech88** [comment]
I believe this was fixed by #15830.
