### ISSUE TITLE
Bandolier grammar

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15154]
(WEB REPORT BY: cisrox REMOTE: 172.93.109.202:7777)
>Revision 9ddd9f17bb8c6f211b188a5fd3fd0007bf851091

>General description of the issue
A bandolier designed with eight pouches for [diffrent] ammunition types.

>What you expected to happen
A bandolier designed with eight pouches for [different] ammunition types.

>What actually happened
A bandolier designed with eight pouches for [diffrent] ammunition types.

>Steps to reproduce if possible
examine the bandolier in sec lockers

**Comment by FudgePucker** [comment]
Oh man I must look really fucking stupid right now.
