### ISSUE TITLE
You can become jesus with those simple steps.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15151]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
1.Cut Avocado in half
2.Cut the Half Avocado again
3.keep cutting your half avocados for infinite avocados

also on a side note, the seed you get from removing the avocado seed will not be a modified seed, so if you have a bajillion potency avocadoes with polacyd, zombiepowder and tonio you'll only get a normie seed.

**Comment by CptWad** [comment]
💯 % tested

**Comment by strawberrytan** [comment]
To add to this, half avocado is in the table of possible no fruit results

T. Trader who got jipped by rolling half avocado and having it disappear when I put it in the seed extractor

**Comment by Shadowmech88** [comment]
I could have sworn I specifically prevented this. I definitely intended to.
The seed extractor producing nothing when given half an avocado *is* intended, you need to feed it whole avocados.

As for the avocado seed being normal, I'm not sure how to copy the genetic data of the fruit it came from into it.
