### ISSUE TITLE
Pipe Networks Stop Updating

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15150]
(WEB REPORT BY: reviire REMOTE: 172.93.109.202:7777)
Revision: 74db1fa3b9682139521d69a1159523ea63c491a8 

>Pipe networks stop updating temperature when, from what I can tell, you have a canister attached to a port and pump gas into a tank. Pressure will increase when siphons are in use, but temperature won't change at all. Adding a new pipe to the network fixed the issue.

>I expected temperature to keep increasing due to the H/E pipes.

>Temperature remained constant even without new gas being inserted. 

>Steps to reproduce if possible
Setup H/E pipes, some sort of gas input, a port with a canister on top. Take gas out of canister, network should stop updating.

**Comment by Reviire** [comment]
Okay so I might've been a bit fast on the report, I'm not able to reproduce it with the steps I gave. I only know that it's a problem i've had several times. i.e, in one scenario I had plasma stuck at -235C and was completely unchanging.

**Comment by Exxion** [comment]
It's probably one of those weird internal bugs that's hard to reliably reproduce.
