### ISSUE TITLE
Slime people can't use hyperzine

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15168]
So it's not a bug but there's no way for slime people to GO FAST without dying
It doesn't make sense having hyperzine not work properly on only them, this would have made more sense for DIONA but they did a different thing with them.
Maybe just delete that line of code or revert it back to intense heat super charging them?

also the reason for them having less temp resistance is something like water evaporates,i think that's what shadowmech said? doesn't make sense for them to be water based slime if they get hurt by water

**Comment by Shadowmech88** [comment]
I said *liquid* evaporates. I never said slime people were made of water.

Also I didn't specifically add the hyperzine thing, that existed even when slime people were a mutantrace.

**Comment by ghost** [comment]
ah
yeah the hyperzine thing didn't matter since they could just eat a shit load of chilis for the same effect
but now that you can no longer do that there should be an alternative to hyperzine

**Comment by DamianX** [comment]
you could always like
play a non-snowflake race
if you want to go fast

**Comment by SonixApache** [comment]
hyperzine speeds up the muscles
slimes don't have muscles

**Comment by ghost** [comment]
Since when have slimes ever been fast in a videogame?

**Comment by Fruktlimpa** [comment]
Hyperzine was a mistake
