### ISSUE TITLE
Bagelstation PDA map missing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15166]
(WEB REPORT BY: mikeytwolf REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

Revision: 4003b6a38719fea504088fba5fc6bc1d63115879

>General description of the issue
PDA station map is missing

>What you expected to happen
VALUE FOR MONEY

>What actually happened
Just a grid, with co-ordinates and the ability to place markers

>Steps to reproduce if possible
Just buy a station minimap from a PDA app vendor.

**Comment by jakmak** [comment]
The pda maps were superceded by the holomaps. Actually what if we replaced the slow shitty pda map with a holomap?
