### ISSUE TITLE
Any real reason that Dionae can't wear ghetto space suits?

### ISSUE THREAD

**Issue by toomykins** [d3athrow/vgstation13#15180]
#### Description of issue
Dionae can't wear ghetto space suits

#### Difference between expected and actual behavior
I don't see why they can't. same head, dionae and humans can both wear nasa suits, voidsuits, hardsuits, but not this?

#### Steps to reproduce 
try to wear a ghetto space suit as a diona

**Comment by PromethTK11** [comment]
Why a Dionae should wear a space suit at all?

**Comment by toomykins** [comment]
Why should any race wear any space suit ever?
I really don't know what you're trying to say here @PromethTK11

**Comment by SonixApache** [comment]
Aren't dionae space-proof anyway?
To answer your question; probably forgot a species flag. Should be an easy fix.

**Comment by AI-Is-Rogue** [comment]
Hypothermia's a bitch.

**Comment by SonixApache** [comment]
the two components of the ghetto spacesuit are just as effective in space-proofing you as the suit itself.

**Comment by toomykins** [comment]
@SonixApache yeah no it's pretty cold in space in ss13 so they need the layering space-proof suits give, also pressure still hurts.

**Comment by SonixApache** [comment]
Pressure doesn't hurt dionae.
Firesuits are 100% pressure proof, and isolate heat enough to keep you warm for extended spacewalks.
Pretty sure space blankets keep you warm for long enough as well, but I'm not 100% on that.

**Comment by toomykins** [comment]
Still not really a reason why they shouldn't be able to equip the equipment.

**Comment by SonixApache** [comment]
Again, your actual answer is that someone probably forgot to add a species flag.

**Comment by ghost** [comment]
Because they already have a natural ghetto space suit 😂👌
