### ISSUE TITLE
Ideaguy idea: mech crew monitor module for oddyseus

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#15181]
imagine being able to use a crew monitor inside of an ody

would make odys bretty great paramedic gear instead of not really worth building

also it would be good to have a third medical module for odys could equip so no spaceman would have to double up with 2 syringe guns ever again.

**Comment by Killette2** [comment]
I will slap any roboticist's face if they ever deliver me an oddy with 2 syringe guns instead of 2 sleepers or random 3rd utility

Or send them a PDA message

**Comment by Exxion** [comment]
>Not going triple sleeper

**Comment by Durgen** [comment]
top syringe gun producing healing cocktail
bottom syringe gun producing chloral/mutagen

plebians

**Comment by ghost** [comment]
>not having a syringe gun with oxycodone DD and honey

**Comment by SonixApache** [comment]
>not just upping the hardpoint count for every mech by one

**Comment by Exxion** [comment]
>Not doing that then going quadruple sleeper

**Comment by SonixApache** [comment]
>not just coding a hardpoint system with visible sprite overlays so you we can up the amount of total modules without going full retard
