### ISSUE TITLE
Captain's Cap is not visible on greys.

### ISSUE THREAD

**Issue by SysadminJeroen** [d3athrow/vgstation13#15195]
#### Description of issue
The title.
Captain's Cap is not visible on greys.

#### Difference between expected and actual behavior
Someone wanted to see a Captain's Cap on a grey, couldn't see it.

#### Steps to reproduce 
Put a Captain's Cap on a grey.

#### Specific information for locating

Captain's Cap.
`/obj/item/clothing/head/helmet/cap`

#### Length of time in which bug has been known to occur

Right now.

#### Server revision

91adeed8a916b660dbf081340607d6e91fa0131f 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Waismuth** [comment]
same with cult space-proof helmet and crusader helmet

**Comment by beesil** [comment]
Fixed by #22049
