### ISSUE TITLE
Chemaster 3000 Duplication bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15193]
(WEB REPORT BY: wushroom REMOTE: 172.93.109.202:7777)
>Revision: 91adeed8a916b660dbf081340607d6e91fa0131f

>Using input lag, I was able to open more than one window (the ones that ask you how many pills, etc.) in the chemaster. By doing this, I was able to follow through with them all creating a seperate instance of my order with each one.

>To get the amount of chemical I made back

>I got two sets, since I opened two windows

>I get somewhere between 15ms and 30ms ping, but still get input lag in-game. All I do is spam click more than once at a time to get the thing I want to happen. Do that while on the Chemaster 300 gui (blue buttons) and you get this bug.

**Comment by SysadminJeroen** [comment]
Close this, nothing was in the bottles.

**Comment by ghost** [comment]
it dupes the pills, but the second lot of pills have no chems in them
