### ISSUE TITLE
Tank Transfer Valves have no in-hand sprite

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15198]
This is kind of an issue. Would be good if we could transform the sprite the TTV is using at the time, since there's a lotta custom sprites for them.
![Me holding two TTVs surrounded by more TTVs](https://user-images.githubusercontent.com/8468269/27010762-b144e810-4eac-11e7-9245-7fa3c2856e53.png)

#### Server revision
91adeed8a916b660dbf081340607d6e91fa0131f

**Comment by SkowronX** [comment]
I'm pretty sure there used to be an inhand sprite years ago.

**Comment by Arthurdentist** [comment]
does the toxin commemorative clock have an inhand?

**Comment by SonixApache** [comment]
It does not.
