### ISSUE TITLE
Captain's cap not appearing on grays

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15194]
(WEB REPORT BY: wushroom REMOTE: 172.93.109.202:7777)
>Revision: 91adeed8a916b660dbf081340607d6e91fa0131f 

>I put it on. It didn't appear on my head. I remained bald. Nuff said.

**Comment by Exxion** [comment]
#15195 is more descriptive and also actual issues are preferable to web reporter ones because the author is subscribed
