### ISSUE TITLE
Golden atmos hardsuit helmet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15202]
(WEB REPORT BY: salmonistasty REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>The upgraded atmos hardsuit helmet won't illuminate. There is toggle light option, but it doesn't work

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by SysadminJeroen** [comment]
#15203 describes the issue better.

**Comment by SonixApache** [comment]
The issue isn't that there's no light, it's that there's a non-functional light switch button.
Yet ANOTHER action button issue that'll never get fixed.
