### ISSUE TITLE
[Boxstation] SpacePods keep getting stuck inside of this window

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15209]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
http://i.imgur.com/FGOktlv.png

I have witnessed two different people flying space pods fly into this window and tube combination and become unable to leave due to some unknown force.
The window in question is on the science outpost on Boxstation in the Spectrometry Lab, which is the first room north of where the shuttle docks.

**Comment by SonixApache** [comment]
TUUUUUUUUUUUUUUUUUUUBES

why haven't we just fucking removed tubes already

**Comment by DamianX** [comment]
Didn't PJB say the only thing that needed to happen was move tubes from Cross to Bumped or something like that?

**Comment by ElectroBlueGuy** [comment]
I can confirm, one time i had to call an admin to unstuck myself, and then got stuck again

**Comment by Exxion** [comment]
@DamianX The other way around

**Comment by DamianX** [comment]
How hard can that be?

**Comment by Exxion** [comment]
Like three lines

**Comment by nuklearcellphoneg** [comment]
[14787]

**Comment by nuklearcellphoneg** [comment]
#14787
