### ISSUE TITLE
Golden atmos hardsuit helmet issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15203]
(WEB REPORT BY: salmonistasty REMOTE: 172.93.109.202:7777)
>The light from atmos upgraded hardsuit helmet should work, I think, because there is toggle light option. Sadly it does not.

>Light from upgraded atmos hardsuit isn't working

>I expected the hardsuit helmet  to produce light, just like any other hardsuit helmet

>Nothing actually happend

>Upgrade atmos hardsuit helmet with the upgrade kit located at start of the game in atmos/engineering rooms. Toggle light.

**Comment by SonixApache** [comment]
>The issue isn't that there's no light, it's that there's a non-functional light switch button.
Yet ANOTHER action button issue that'll never get fixed.
