### ISSUE TITLE
Power point counter being displayed inapproprately

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15206]
(WEB REPORT BY: codenameb REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
e7a6ca3ca220e3bae6d0c069d972e6bfb0a54b66

>General description of the issue
Joined a round near the end, it seems xenos were out and about. I spawned in with the power point counter, as if I were a xeno. It was displayed in the wrong location.

http://imgur.com/a/OfQ73

>What you expected to happen
Nothing.

>What actually happened
Odd HUD display.

>Steps to reproduce if possible

**Comment by ghost** [comment]
BYOND is shit when it comes to HUDs

**Comment by Intigracy** [comment]
Death by powerpoint

**Comment by nervere** [comment]
No longer an issue.
