### ISSUE TITLE
Step Speed Transfers To Ghosts, Doesn't Reset

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15205]
(WEB REPORT BY: n3x15 REMOTE: 172.93.109.202:7777)
>Revision
e7a6ca3ca220e3bae6d0c069d972e6bfb0a54b66

>General description of the issue
When haunting someone, step speed (movement speed between tiles, AKA glide speed) transfers from hauntee to haunter.  When the haunter stops haunting or the hauntee dies, the step speed is not reset. This results in movement being jerky, similar (but not exact) to when someone fucks with step_x/y.

>Steps to reproduce if possible
(Who the fuck put this below expectation/observation)
1. Haunt player
2. Have player's movement speed lowered 
3. Kill player
4. de-haunt
5. Move.

>What you expected to happen
Normal ghost movement speed and step transition.

>What actually happened
Jerky movement because the slower step movement speed is still set.

**Comment by Shadowmech88** [comment]
Ghosts should always have the same step speed, right?
Couldn't this be fixed by making un-haunting someone manually set the ghost's step speed to what it's supposed to be?

**Comment by N3X15** [comment]
It's dependent on movement speed, and since you nerds added some new "Change Speed" verb, that's variable.

**Comment by Shadowmech88** [comment]
So, make un-haunting someone manually set the ghost's step speed to whatever's appropriate for its movement speed?

**Comment by N3X15** [comment]
Sounds good.
