### ISSUE TITLE
Det can't open one doors in brig, but can open all the other doors leading to the same place

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15212]
(WEB REPORT BY: moltevolte REMOTE: 172.93.109.202:7777)
http://prntscr.com/fiz3v2 take this screenshot as a description, it's more descriptive than how I can describe it myself

**Comment by Durgen** [comment]
you mean the bolted door?

**Comment by SonixApache** [comment]
Maybe he was just touching it at the time.
That door is probably one of the doors that lead to perma, hence.

**Comment by Kurfursten** [comment]
This is bagelstation, the hallway that leads to the gulagship

Map issue not code issue
