### ISSUE TITLE
feature request: short range radio jammer

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#15211]
One of the biggest problems you can run into as a traitor is people getting out a quick radio call after you ambush them. I believe this has caused shitter juice and sleepy pens to see high usage. I feel like this is the most boring way to antagonize, and the worst way to be killed. Woops you let someone come within a single turf next to you, now you are dead.

I feel this can be fixed by a radio jammer, a device disguised as a tape recorder (no new sprites would need to be made this way) that prevents radios and headsets from working within an adjustable range. It uses a power cell that can be removed and replaced, the longer the range the more power it uses.

If this would be too powerful a few nerfing ideas could be, printing to chat a flavor text that you hear a breif moment of static whenever your radio gets shut off by the jammer (letting your target know that he is about to get anally raped and to run or fight instead of calling for help), making the AI hear a flavor text about a static sound and when it is left on enough the location of the noise (alerting the station that someone has a jammer and to be careful around strangers, also forces you to remember to toggle it on and off before you get busted), or harder but neater, cause all turfs within jamming range show up as static to the AI (a half buff and full nerf, AI can not identify you or what the hell you are doing, but knows your location to alert security if they spot the clearly out of place static, which would be a neat concept because you can set up a trap using it with a proximity grenade, that valid the AI told you about is really a polyacid smoke bomb).

I am pretty sure goon also has something like this.

**Comment by PJB3005** [comment]
We should call it.... THE EMP GRENADE!

Anyways, remove common radio and headsets for all but sec and command *when*.

**Comment by Exxion** [comment]
When someone with any sense makes a remake
But sadly that's never gonna happen until then

**Comment by SonixApache** [comment]
alternative option; port bay/tg/whatevercode yellow intent that lets you cover someone's mouth so they can't talk

**Comment by Rattlederp** [comment]
I love this idea, there's nothing I hate more than getting wordlessly killed and spaced even though I'm always willing to play along with the antag's gimmick. But the antag has no way of knowing that I'm not one of those cunts that instantly screams into the radio. This would solve that issue nicely for both parties. The EMP grenade isn't subtle enough imo, pretty sure that's why no one uses them.
