### ISSUE TITLE
Cult shouldn't need to summon narnar every time.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15219]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
I'd like it if the final objective could be to just hijack the emergency shuttle with at least X cultists, which I believe was an option before certain changes were made. Demonic twister gets old.

**Comment by Riekland** [comment]
>WEB REPORT BY: kavlax 

ah yes

**Comment by SonixApache** [comment]
Grey McShirt [Common]: "IT'S TDM"

**Comment by Fruktlimpa** [comment]
No thank you, it feels like it will undermine the purpose of cult and water it down to edgyrev

**Comment by Uso15** [comment]
Got to shuffle more minor objectives in there, like 'sacrifice the chaplain' or 'shard x people' or 'convert x% of Station tiles to cult tiles'.  You know, get the whole cult involved.

**Comment by clusterfack** [comment]
In game bug reporter is for bug reports
