### ISSUE TITLE
Defillibrators have no inhand sprite

### ISSUE THREAD

**Issue by ElectroBlueGuy** [d3athrow/vgstation13#15213]
We really need a sprite for the defillibrator, so people won't do the DUDE SURPRISE STUN because of no in-hand sprite

**Comment by Exxion** [comment]
![image](https://user-images.githubusercontent.com/9827785/27060412-b90d1320-4faa-11e7-8d0e-843bb40a4bed.png)

**Comment by DamianX** [comment]
rename emagged defibrillator to defillibrator when?

**Comment by ElectroBlueGuy** [comment]
I shouldn't write issues at 2:00 in the morning

**Comment by Exxion** [comment]
Nah, this is far from the worst misspelling of defibrillator on the GitHub
I just felt like being an ass

**Comment by Bilgecrank** [comment]
I was going to sprite some paddles, but the Defib is fully sprited in the Weapons.dmi, with hand sprites for both carrying the defib and the paddles separately. There's even an emagg sprite.

![fully sprited](http://i.imgur.com/A43Y3Gh.png)

**Comment by ElectroBlueGuy** [comment]
@Kokuten thats something isn't it

**Comment by Exxion** [comment]
I guess originally the defib was going to be two-handed or something, judging by those `icon_state`s

**Comment by ElectroBlueGuy** [comment]
I wonder, if the sprites are in the code, why aren't they in the game?

**Comment by Exxion** [comment]
They're in the spritesheet, not the code.
Also the inhands aren't really in the *right* spritesheet, but I don't think that really matters, and isn't hard to fix anyway

**Comment by Bilgecrank** [comment]
It makes sense that they'd be two-handed, I thought they were. Anywho, let me know if they need to be adjusted or something, I was actually looking forward to giving this a whirl.

**Comment by gbasood** [comment]
>They're in the spritesheet, not the code.

welp

**Comment by beesil** [comment]
Fixed by #18586
