### ISSUE TITLE
Custom Strike Team Members get nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15225]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Issue: Created a custom strike team, upon spawning the members had no identity or items, making them a blank human.

**Comment by Intigracy** [comment]
https://github.com/vgstation-coders/vgstation13/blob/8d561d8fb8b126c93d204b1ca22c48826592d820/code/game/striketeams/striketeam_datums.dm

literally no code for equipping them, lmao

**Comment by SonixApache** [comment]
close this
