### ISSUE TITLE
Maint door by Chapel Mass Driver not accessible by Chaplain.

### ISSUE THREAD

**Issue by Cutelilduck** [d3athrow/vgstation13#1522]
Chaplain ID is not able to open the maintenance door by the mass driver. Crematorium maint door works as intended.

![chapel_access](https://cloud.githubusercontent.com/assets/6144694/4323407/14f36a54-3f50-11e4-9751-333aedd8657e.png)

**Comment by d3athrow** [comment]
This is intentional.
