### ISSUE TITLE
Borer speed boost bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15224]
(WEB REPORT BY: yertbogan REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
c146d12f77b4de6e93852edee897acf44c73a746 

>General description of the issue
borer chemical related speed boost does not toggle off even when you run out of chemicals

>What you expected to happen
I would stop speed boosting when my chemicals ran out

>What actually happened
my host had massive speed indefinately

>Steps to reproduce if possible
be borer>evolve chemical speed boost>activate>deactivate/run out of chemicals

**Comment by Killette2** [comment]
It's a feeture

**Comment by Shadowmech88** [comment]
I was unable to reproduce this on the live server.
