### ISSUE TITLE
Vanishing metal sheets upon object desconstruction

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#15237]
#### Description of issue
Deconstructing most objects with a wrench while a stack of metal is on the same tile will cause the stack of metal to transform into one or two sheets based on what the object was.

#### Difference between expected and actual behavior
Sheets making their own stack instead of magically eating the previous stack

#### Steps to reproduce 
Build a stool, drop a stack of metal on the same tile and wrench the stool, only 1 metal sheet will remain.

Tested objects it happens with are chairs, beds, every couch piece(didnt test all the different colors), and racks.

#### Other
Tables and girders only turn into 1 sheet when wrenched apart despite costing 2, what's up with that?

#### Length of time in which bug has been known to occur

At least a few months, this is not the first time it's happened to me.

#### Server revision
Revision: 26a9ad0be9fe5f08560406d9ca0fcda0657a19cf

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Sorry dude, but this is all intended
Not to say it's not up for discussion though

**Comment by DamianX** [comment]
@Exxion ???

**Comment by Exxion** [comment]
Stacks combining is a fully intentional feature, and most things return less material when deconstructed than they took to construct, which is also intentional
Personally though, I think that should only be the case when a welder is involved in construction

**Comment by DamianX** [comment]
Nope, I've encountered and fixed this bug before with computer frames.
Place 50 sheets on a tile, deconstruct a chair on the same tile, magically you only get a total of 1 metal instead of 51.

**Comment by Exxion** [comment]
Oh what

**Comment by Dacendeth** [comment]
Maybe i didn't word it correctly, having 20 stacks of metal on a tile with a stool you deconstruct will cause 20 of those metal sheets to vanish, and a single stack of 1 sits on the tile instead

**Comment by DamianX** [comment]
I blame pooling #14852

**Comment by Exxion** [comment]
Yeah sorry I misunderstood
Why the fuck would this only happen for certain items?

**Comment by Dacendeth** [comment]
It works as intended when you have a stack of metal and you weld a locker/crate apart, seems to be only linked to wrenching things apart?

**Comment by Exxion** [comment]
It's probably pooling, as Damian said
But I have no idea why that would break it

**Comment by kilozombie** [comment]
I've also had this happen often when cutting up logs/woodapples for wood.

**Comment by SonixApache** [comment]
this is a pretty big issue
