### ISSUE TITLE
metal tomahawk cannot cut wood, but the glass one can

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15233]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: c3f57ba6874f57166c983391dfd12283a5759ff0 

>General description of the issue
title pretty much says it all. I made 2 tomahawks one glass, the other metal, the glass one cut wood into planks, the metal one didn't

**Comment by Shadowmech88** [comment]
I was unable to reproduce this. It is likely that the metal tomahawk was at an incomplete stage of construction, for example having the blade wired to the handle but not yet welded to it.
