### ISSUE TITLE
Package Wrap Price Nerf

### ISSUE THREAD

**Issue by Smedley8** [d3athrow/vgstation13#15240]
Package Wrap is pretty expensive, at a high cost from biogenerator or $10 for a sheet in the Arts and crafts pack. It should be changed to have either its own cargo pack or someway for cargo to make more of them.

**Comment by Kurfursten** [comment]
Does the biogenerator at least make a full stack, or just one piece?

**Comment by Smedley8** [comment]
One piece, if I can recall.

**Comment by Kurfursten** [comment]
Seems fair to up it to a full stack from the biogenerator, I don't think anyone would object

**Comment by SonixApache** [comment]
seems fair

**Comment by Killette2** [comment]
My issue about the biogenerator doing this got ignored :(

**Comment by DamianX** [comment]
link?

**Comment by Killette2** [comment]
https://github.com/vgstation-coders/vgstation13/issues/11963
