### ISSUE TITLE
Chain lightning doublecast

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15245]
(WEB REPORT BY: saronsen REMOTE: 172.93.109.202:7777)
>Revision
 a02b254c6f68cd92bda8f110fa9425abc4f76588 

>General description of the issue
wizard can doublefist chainlightning in a single cast 

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by saronsen** [comment]
When you accidentally press submit fucking shit.
