### ISSUE TITLE
Amorphous Mask Exploding Necromorph Issue

### ISSUE THREAD

**Issue by Knightkiller11** [d3athrow/vgstation13#15241]
#### Description of issue
Done on Testing Server
Wearing an amorphous mask that transforms you into a explody type necromorph, then attacking yourself results in an infinite gory chain of explosions

#### Difference between expected and actual behavior
Expected Behaviour:
Explode once, kill self

#### Steps to reproduce 
1) Be a Necromorph Exploder (Or be transmogged as one via amorphous mask)
2) Attack self
3) Infinite explosions, also you die
4) Heres a picture of the result:
![image](https://user-images.githubusercontent.com/25286638/27258491-aae55850-53f3-11e7-9acb-ce39f0909b83.png)

#### Length of time in which bug has been known to occur
Uncertain? Perhaps as long as explosive necromorphs have existed

#### Server revision
d285a4411d86d707427ddbe1835ff4ae9ad5c086 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [?] Issue happened in a recent (less than 7 days ago) round (Do test server rounds count?)
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
If it doesn't cause lag it could be kind of neat just as a feature. Like a bad large artifact. An actual "gotta wall it off and forget about it" situation.

**Comment by Knightkiller11** [comment]
It causes lag, quite a bit of it if it's anywhere near you. about 2 screen distances away.
Could suck if someone decided to do it within the vicinity of medbay

**Comment by Shadowmech88** [comment]
This is more an issue with the mob than the mask.

**Comment by Kurfursten** [comment]
I figured since it's an explosion. What a pity!

**Comment by Knightkiller11** [comment]
Thinking about it, assuming the round on the test server hasn't restarted, it may still be exploding right now. Feel free to drop by to admire the view I guess.

**Comment by ghost** [comment]
At this rate we might as well have an allowed list of mask morphs, rather than a not allowed list

**Comment by SonixApache** [comment]
that or we unfuck everything at the base

**Comment by Shadowmech88** [comment]
I think it'd be better to just fix the mobs that become problems, unless it affects a whole bunch like the humanoid business.

It's not a good idea to have mobs in the code that can fuck up rounds via bugs/oversights if they happen to be controlled by a player, regardless of how the player is placed in control.
