### ISSUE TITLE
Posibrains talk with a normal speech bubble rather than a robotic one

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15248]
#### Description of issue
![image](https://user-images.githubusercontent.com/8468269/27276493-b8591ad8-54db-11e7-91c6-8d5dd0c4ecaa.png) vs ![image](https://user-images.githubusercontent.com/8468269/27276615-09aed922-54dc-11e7-83ba-17e70d01379e.png)

#### Server revision
d7ee1bd8b71e2e6e398a247174465d87acf91879

**Comment by DamianX** [comment]
Should MMIs get the robotic bubbles as well?

**Comment by Ephx1** [comment]
Logically they are part machine, but I always imagined that the MMI emulates their original voice to a certain degree.
