### ISSUE TITLE
RC consoles messages aren't logged

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15242]
#### Description of issue
Messages sent with RC consoles, the green things on the wall that people use to bug cargo, aren't logged as far as I know.

#### Difference between expected and actual behavior
use RC console to ERP with cargo, find message in logs
vs
use RC console to ERP with cargo, nothing in logs

#### Steps to reproduce 
Send a message with an RC console, check logs

#### Specific information for locating
`/obj/machinery/requests_console`
`/code/game/machinery/requests_console.dm`

#### Server revision
dbf39a1e0c2d781bd9b87ad4491bf02019ca0261

**Comment by Killette2** [comment]
I don't think this has happened in the history of ever

**Comment by Exxion** [comment]
I also don't think cargo has ever checked them at all

**Comment by SonixApache** [comment]
you'd be surprised

**Comment by Killette2** [comment]
I meant nobody has used them to ERP, not that they've never been checked.
I'm also not surprised, because according to the logs it hasn't happened 😃
