### ISSUE TITLE
Chain lightning doublecast

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15246]
(WEB REPORT BY: saronsen REMOTE: 172.93.109.202:7777)
>Revision
 a02b254c6f68cd92bda8f110fa9425abc4f76588 

>General description of the issue
wizard can doublefist chainlightning in a single cast 

>What you expected to happen
one hand to be filled with lightning, not both

>What actually happened
ZZZAP MUTHAFUCKA
ZZZAP MUTHAFUCKA

>Steps to reproduce if possible
Probably just mashing chain lightning as fast as possible while swapping hands

**Comment by mtpowell** [comment]
Not a bug

```var/temp = "You have improved [name]"
	if(spell_levels[Sp_SPEED] >= level_max[Sp_SPEED])
		multicast = 2
		temp += " and gain the ability to multicast, each incantation allows you to fire off two bolts of lightning before having to re-cast."
```
