### ISSUE TITLE
Experimental weldingtool doesn't gen fuel correctly.

### ISSUE THREAD

**Issue by DrSnips** [d3athrow/vgstation13#15254]
The experimental weldingtool's fuel generation currently doesn't work, the tool itself isn't used anywhere else other than the holo switchtool's welder module.
It's was intended to gen a small amount of fuel per second. When it was added to the holo switchtool, it should have fixed it but upon testing later it doesnt seem to work when in the switchtool.
Possible reasons it doesn't work
A. It's inside the switchtool and lots of items don't work correctly when in a switchtool.
B. The fuel gen code v2 doesn't work period.
C. The tools vars are played with when it's deployed from the switchtool. (When you deploy it from the holoswitchtool, it come out pre lit due to it being in the switchtool and having no way to be turned on normally)

**Comment by Shadowmech88** [comment]
The experimental welding tool generates new fuel on each call to its `process()`.
However, it is never added to `processing_objects`, so its `process()` is never called.

**Comment by ghost** [comment]
It is added to processing_objects when it is on. If it runs out of fuel it turns off however, it also regenerates fuel faster than it uses it if left on

So, never let it run out.

**Comment by DrSnips** [comment]
Well, that doesnt seem to be true because every time you deploy it, it relights itself. Drain a holotool utill it shuts off, then redeploy it, then smack a welder tank. I found out the hard way one round.

**Comment by Shadowmech88** [comment]
My bad, I was only looking for a `New()` proc, I didn't guess it could be added elsewhere.
