### ISSUE TITLE
ERT ghost draft not working properly

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#15257]
#### Description of issue
A few minutes ago we have a round with a serious case of spider infestation in arrivals. That prompted command to call in an ERT which at least two ghosts signed up for, a few minutes later the ERT signing phase closed and not a single ERT member got spawned.

#### Difference between expected and actual behavior
For ghosts to become ERT members.

#### Steps to reproduce 
I'm not sure if this is happening every time but something clearly went wrong here.

#### Server revision

Game: eaa3f967bf2515a79203398c35578d9d58df91d2 
Patches: 2d49ec593b55394cff3802053088086f84d76f3e 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by nervere** [comment]
doesn't seem to be an issue anymore
