### ISSUE TITLE
Welder would not turn on

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15259]
(WEB REPORT BY: tellossee REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
eaa3f967bf2515a79203398c35578d9d58df91d2 

>General description of the issue

Had a welder from being a round start mechanic. It had fuel. it would not turn on. I tried refilling it and dropping it. It still would not. Others couldn't either
>What you expected to happen
for it to work

>What actually happened
it didn't 

>Steps to reproduce if possible

I don't know

**Comment by Exxion** [comment]
To be clear, it was the one in your belt at roundstart, and you never clicked it with a screwdriver or anything?

**Comment by SonixApache** [comment]
Maybe there was water in it somehow.
Probably pointless without VVing that particular welder, unless it was throwing runtimes.

**Comment by ghost** [comment]
It's an ancient bug nobody can ever reproduce or bother to ahelp it to be vv'd when it happens. One of space's great mysteries that the librarian should form a cult around solving. Just think of it like being bit by the neighborhood dog.

**Comment by Exxion** [comment]
The only way I can see it could POSSIBLY happen based on the code is if someone screwdrivered the welder earlier

**Comment by nervere** [comment]
This doesn't happen anymore, if it ever even did. Exxion's explanation is the most likely.
