### ISSUE TITLE
Jump major buff-genetics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15278]
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
>Revision 
d2b45f9c028a58ad5879a8939ba61ed2a8cc4229 
>Jump does not go on CD until around 2 seconds after you press it. Allowing you to jump almost 6 times before the CD is turned on
>What you expected to happen
Jump once

>What actually happened
Jump lots if you spam the shit out of it, covering ground quickly, fucking up your character sprite since you almost go off screen

>Steps to reproduce if possible
get jump genetic buff
Spam jump alot
Jump alot

**Comment by kilozombie** [comment]
Unintentional but fucking awesome
Would never want this removed even if it were actually being used for nefarious business. It's too funny, and feels like a classic spess-esque quirk.

**Comment by Killette2** [comment]
Oops wrong account earlier
