### ISSUE TITLE
Unlimited hulk

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15273]
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
>Revision d2b45f9c028a58ad5879a8939ba61ed2a8cc4229 

get hulk superpower
activate hulk
get clean SE before hulk power goes away
get unlimited hulk

>What you expected to happen
Hulk go away

>What actually happened
Hulk 4ever

**Comment by Killette2** [comment]
Lmao I remember there was a similar bug I found where you could use creatine to get hulk then charcoal to get it out of your system so you're hulked forever while off creatine
