### ISSUE TITLE
Plasmamen "lose blood" when being dragged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15270]
(WEB REPORT BY: aerlx87 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
d2b45f9c028a58ad5879a8939ba61ed2a8cc4229 

>General description of the issue
When you drag a plasmaman while they're in crit or dead, the message "(Name) loses a lot of blood from being dragged!" despite plasmamen having no blood to lose.

>What you expected to happen
Either no message, or one that doesn't reference blood.

>What actually happened
Bloodloss was referenced despite being none to lose.

>Steps to reproduce if possible
Beat plasmaman to death then drag him around.

**Comment by SonixApache** [comment]
i'll look into it
probably yet another 'plasmamen have fake blood lmao' meme

**Comment by SonixApache** [comment]
Rejuvenating a plasmaman gives them blood for some reason. And after that, they don't lose blood from drag damage, even though they throw blood splatters.

However, bloodloss shouldn't happen from being in crit and having broken bones, so I can work on that.
