### ISSUE TITLE
Very annoying layer selection on RPD

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#15283]
#### Description of issue
The buttons to select layer on the RPD are very small - you have to click the thin pipe icon to select it. This is a problem for users with very high definition screens, as the icons are so small you have to get the mouse pointer into a space that's literally a pixel or two wide.
Propose replacement with either larger square buttons, radio buttons, a drop down menu, plus/minus buttons, etc. Whatever works better than the current annoying one.

#### Difference between expected and actual behavior
As an autismtech, we need to place pipes on multiple layers frequently, for example when setting up cooling systems or increasing efficiency-space ratio for things like air-to-distro. Making this easier than having to waste time attempting to click a tiny icon would enhance the users ability to spew autism across the station.

#### Steps to reproduce 
>Have high-resolution, small-size screen
>Attempt to switch layers on RPD

#### Specific information for locating
Rapid Piping Device menu

#### Length of time in which bug has been known to occur
More than a couple of years at least

#### Server revision
All

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Shift+scrollwheel

**Comment by DamianX** [comment]
Agreed, but as a workaround you can use the shift-scrollwheel shortcut.

**Comment by Inorien** [comment]
Thanks, I didn't know about that. Will try it in-game.
Improving the window itself would still be a help

**Comment by SonixApache** [comment]
use the keybinds
