### ISSUE TITLE
More Transforms to add to No Transform

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15296]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
Since transmogrify artifact still has issues, heres another two to add

Giant spider - Dies instantly on Transform
Hive Broodling - Dies after a few seconds, vanishing since it has no corpse, with you along with it

**Comment by ghost** [comment]
Giant Spider - there's a subtype added by probe for a vault that spawns in dead, it caused a bit of trouble in the past as spiderlings would evolve into it.

Broodling - Have an extremely short half-life if there's no brood to link to it

**Comment by Exxion** [comment]
Hivelord broods just *always* die after a few seconds
No matter what
There's like a `spawn(something) qdel(src)` or something in their `New()`
