### ISSUE TITLE
Diona nymphs suffocate when held.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#15293]
#### Description of issue
If a nymph is picked up and held in a players hand they begin suffocating after a few seconds. 

#### Difference between expected and actual behavior
Being able to be a scarf without dying instead of dying.

#### Steps to reproduce 
Be nymph, get held and wait a few seconds.

#### Length of time in which bug has been known to occur
Sawbones told me this was a known bug but i haven't experience it at all until today and i've been nymphing on and off for a few months now, so my guess is something recently brought it back?

#### Server revision

Revision: b853412661b3cd0fc1297218119a4e28746bab5e 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
I think it might only happen sometimes
But I have no idea when or why

**Comment by Riekland** [comment]
>not holding your nymph by the neck in a vice grip

it's like you want it to run away
