### ISSUE TITLE
Bagelstation HoS has a holodeck button instead of keycard authenticator

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#15294]
You can't go code red with the holodeck please
@CptWad

**Comment by ghost** [comment]
Working as intending, go to the holodeck and use the keycard auth in there.

**Comment by Killette2** [comment]
holo-keycard authenticator

**Comment by CptWad** [comment]
Go ahead with this I got plenty to fix once you do

**Comment by CptWad** [comment]
I thought this was a pr and deleted my branch fuck

**Comment by gbasood** [comment]
don't delete branches like that then nerd
alternatively just push your local branch back to your remote

**Comment by CptWad** [comment]
deleted from local
anywho I already fixed all the bugs from last time and I am now sweeping up any from between then and now
fucking barber shit took like a whole day and nothing came of it
