### ISSUE TITLE
Metaclub using virtually no power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15291]
(WEB REPORT BY: mikeytwolf REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
1188d7447060024dddba0c0fd2b9d24af7ec37a9 

>General description of the issue
SME isn't even on, and is literally the only source of power. Yet a bajillion power is being made from nowhere, and usage is far too low. SMES are completely ignored.

>What you expected to happen
Actual power that requires thinking

>What actually happened
Retard CE fucking with SME for no reason not getting lynched.

>Steps to reproduce if possible
Go to Metaclub.

**Comment by DamianX** [comment]
Another great report.

**Comment by Exxion** [comment]
Solars?

**Comment by Blithering** [comment]
Possibly just a MoMMI upgrading the glass in the solars to plasmaglass

**Comment by Kurfursten** [comment]
Cannot reproduce on local, safe to close
