### ISSUE TITLE
MoMMI's constructed by the roboticist cannot pick their name

### ISSUE THREAD

**Issue by Knightkiller11** [d3athrow/vgstation13#15290]
I always found it wierd how cyborgs are able to choose their name upon creation (and later alter it once more via reclassification module), while MoMMIs are incapable of doing so unless created automatically at roundstart. 

I can understand having MoMMIs on the derelict be incapable, so as to differentiate from station MoMMIs, however MoMMI's created by the roboticist are also not given the option, despite also being station MoMMIs, heck even cyborgs created by a Malf AI's borging machine can choose their own name (At the AI's discretion).

Does anyone else seem to think this is an issue?

**Comment by Exxion** [comment]
I swear it used to let you

Actually I *know* it used to let Derelict ones pick a name, at least

**Comment by Blithering** [comment]
If the roboticist manually sets a name with a pen, you don't get to pick. Are you sure that didn't happen this time?

**Comment by Knightkiller11** [comment]
I'm like 90% sure he didn't, also its unlikely that he'd pick the name "Default MoMMI-525".

**Comment by Exxion** [comment]
I think MoMMI namepicking broke a while ago, but I have no idea exactly when. Sometime between the last two times I played Derelict MoMMI.

**Comment by ihadtoregisterforthis** [comment]
Does the "pick name" verb do anything?

**Comment by Knightkiller11** [comment]
It says "You can no longer pick your name" or something along those lines, don't think it works in any situation at the minute, at least when used by a player

**Comment by Ephx1** [comment]
@Blithering
How would the roboticist pick a name if MoMMIs don't have a chassis to make?
You put the objects on the MMI to make a MoMMI, not make a chassis beforehand.

**Comment by yclatious** [comment]
I think it was Nexis borg name thing pr that fucked it up, the issue started happening since then Im sure.

**Comment by Blithering** [comment]
Spaghetti-made MoMMIs still get to pick their names, just tested it
