### ISSUE TITLE
Rev not ending if heads remain on station.

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#15300]
So last round, the CMO and RD stayed on the station as the emergency shuttle left for centcomm. Shuttle arrived and the round didn't end.

I bwoinked the last two heads, killed them both, and it ended.

**Comment by gbasood** [comment]
When someone investigates this and finds the cause they should check if the same thing can happen with revsquad
Non-ending rounds when the shuttle docks is real bad

**Comment by Killette2** [comment]
This is pretty funny. Perhaps have the shuttle crash and explode(itself only) when it arrives at the station if it is rev or malf

**Comment by Kurfursten** [comment]
Fixed
