### ISSUE TITLE
Botany snowflake chems removed garlic having holy water

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#15303]
Literally unplayable.
Also this was like the entire point of garlic so it's objectively a bad feature

**Comment by SonixApache** [comment]
says in `seeds.dm#L1693` that garlic should still contain holy water.

**Comment by kilozombie** [comment]
Grinded 10 garlics, got 60 allicin and 20 nutriment

**Comment by SonixApache** [comment]
`## WARNING: The large beaker attempted to add a reagent called 'HOLYWATER' which doesn't exist. (Sonix Apache)`
🤔

**Comment by kilozombie** [comment]
![imagine this but every minute](https://user-images.githubusercontent.com/6062247/27623934-a15dd2ec-5b93-11e7-8ef7-40b349f7a2eb.png)

**Comment by SonixApache** [comment]
oh wait all-caps shit never works

I'm not sure why it's not working, I'll dig deeper.

**Comment by kilozombie** [comment]
It's possible this is because of garlic being such low potency.
But I'm not sure why it gives me the anti-toxin equivalent instead of holy water in the first place

**Comment by SonixApache** [comment]
I did some fuckery and it seems to be potency related. What's weird is that garlic bread also doesn't contain holy water.

**Comment by SonixApache** [comment]
Yeah I don't know what the fuck is going on.
Potency 100: 5 holy water
Potency 50: 3 holy water
Potency 30, 25, 15, 10: 0 holy water
Should be one unit of holy water to start with, + 0.4 more per potency point (so 1u more per 25 potency)
Holy water is being fucky in general.

I'll test some more later if nobody figures it out.

**Comment by kilozombie** [comment]
Even then, that's a HORRIBLE ratio. Garlic shouldn't even have allicin, it should be holy water and nutriment in decent amount.

**Comment by RealestEstate** [comment]
I remember bug reporting this myself earlier, before the snowflake plant chems were added, it's always been like this. holy water is present at super high potency levels, and even then it's only a minute amount. I guess it's just a feature. the addition of the antitox only makes it slightly more tedious, as you now have to seperate that and the nutriment to get pure holy water.

**Comment by Kurfursten** [comment]
@SonixApache It inherits it from the component ingredients

I don't think anyone would complain about upping the holywater rate in garlic though. And for that matter making it hurt vampires a bit more.

**Comment by SonixApache** [comment]
@Kurfursten 
```
/obj/item/weapon/reagent_containers/food/snacks/garlicbread/New()
	..()
	reagents.add_reagent(NUTRIMENT, 4)
	reagents.add_reagent(HOLYWATER, 2)
```
Newly spawned ones don't contain holy water.
Something's weird.

**Comment by Killette2** [comment]
What did you guys do to botany!

**Comment by Eneocho** [comment]
it does have holy water (also allicin)
