### ISSUE TITLE
Diona can't breathe if they are on someone's shoulder

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15301]
(WEB REPORT BY: mater0706 REMOTE: 172.93.109.202:7777)
>Revision:a0ee006142357300ca24eaeadc4083d3828b9b85

As a diona you can be put on someone's shoulder, when that happens you can't breathe anymore and you start to get really cold. Then you can faint, you won't die if you are in light but you will get put into crit.

I expected to just stand on their shoulders.

**Comment by jknpj** [comment]
MOB HOLDERS

**Comment by Exxion** [comment]
#15293
