### ISSUE TITLE
Virus is broken completely now

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15307]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
When you contract a virus your body develops the antigens instantly which makes it useless. You don't even need radium or a doctor. It just autocures itself at stage one.

pls fix

**Comment by SysadminJeroen** [comment]
Can confirm, virus was cured at tick 0.

**Comment by Exxion** [comment]
Wow we're doing really well with viruscode recently aren't we

**Comment by SonixApache** [comment]
wasn't this an issue a while ago?

**Comment by Fruktlimpa** [comment]
But I saw a functional virus yesterday, it was spawning unstable goo and all. 🤔

**Comment by ihadtoregisterforthis** [comment]
I saw someone with a virus indicator blinking off every two seconds. But also saw Judge Dredd drop all sorts of organs on another round.

**Comment by SonixApache** [comment]
yeah the medhud indicator for virusess is fugged
