### ISSUE TITLE
Cult should fail to start if there isn't a chaplain, like rev fails without heads or malf fails without an AI

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#15309]

**Comment by DamianX** [comment]
It would fail a lot.

**Comment by Diavill** [comment]
just put a bullet between their eyes

**Comment by ghost** [comment]
Literally just kill them. You don't have to deal with the cult realizing they can remotely change laws, setting 11 angry cult borgs on you. The null rod isn't wasted on someone who's going to fuck off and get meme'd on and you don't have to deal with deconverts who were dumb enough to be converted in the first place to go oh gee oh my oh no I'm loitering by the cult base again looking at all this exotic scenery oh nooo I've been spotted I better walk away at a reasonable speed. Ah! I've been talismanned and my implant is being removed! Gosh darnit isn't that like so cuhrazeee!? I neeeever could have imagine'd this'd happen.

If you're butt bungled about holy water, order groans recharge packs while you're on the implant order train. Between all of you, head dept accounts, the silicons and the vault cash that was already stolen you can rustle up the money to buy out all the filk for holy scripture filk, recharge packs so you have all you need. Even if they got to and dumped the chapel, you can buy a second flask with a coin and some eucharist wafers should get an additional deconvert with the ~35 holy water between all of them. You can also IV or cryo the holy water to stretch it.

Edit: I guess if you really hate someone, you can reset a borg to service and have them synth a bajillion. Sucks if the borg wanted to do anything with its life though.

**Comment by jknpj** [comment]
Traitor should fail if there's no security

**Comment by AutismSpider** [comment]
people been telling you this for ages do not decull just cut there head off and poly acid/S acid the head same goes for rev just fucking kill them.

**Comment by SonixApache** [comment]
until the chaplain can delete nar-sie himself form the station this is pointless

**Comment by Shadowmech88** [comment]
Chaplain being able to summon God to fight Nar-Sie when?

**Comment by Aurx** [comment]
When you sprite every single possible god a chaplain can worship.

**Comment by Theophrastus1** [comment]
Hey, I usually worship Doomguy when I play Chaplain, but never became an avatar of my god destined to fight nar nar. Admins a shit

**Comment by DeityLink** [comment]
Legacy Cult Issue.
