### ISSUE TITLE
Butt removal surgery does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15302]
(WEB REPORT BY: libertino REMOTE: 172.93.109.202:7777)
Tried removing the butt of 3 different corpses following the steps on wiki, it does not work.
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The butt removal surgery gets stuck on the cautery step, you can keep trying and it gives the same message that you cauterized the wounds on the butt, but the butt wont fall off.

>What you expected to happen
According to wiki the butt should be ready to be used for a buttboy.

>What actually happened
It did not drop the butt and the step of cautery gets repeated ad infinitum.

>Steps to reproduce if possible
Just try to perform butt removal surgery following the steps on wiki.

**Comment by SonixApache** [comment]
![image](https://user-images.githubusercontent.com/8468269/27623486-fec65f1e-5bdc-11e7-8a02-5b9ae6d8e903.png)
cool, i get to blame @CodenameB

**Comment by CodenameB** [comment]
*shrug*

I never touched butt removal. Feel free to check my PR. 

And, it was working perfectly fine when I wrote my code, that's how I got butts for testing purposes.

Obviously someone changed something else in the mean time.

**Comment by SonixApache** [comment]
Last touch to butt surgery was yours, but if it was working back then something else changed I guess.
I think it's prioritizing butt attachment over butt removal for some reason.
