### ISSUE TITLE
Ventcrawling Error

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15315]
(WEB REPORT BY: kharkov72 REMOTE: 172.93.109.202:7777)
>Revision de065b9b413fe60457134bfdb151535a3d1e128c

If you enter a vent while buckled to a chair, you lose all ability to anything. Done while a MoMMI.

>What you expected to happen
Expected it to auto unbuckle and allow me passage through the vent

>What actually happened
Buckle still set, but since I am in a vent I cannot unbuckle, and cannot leave the vent as I am stuck

>Steps to reproduce if possible
Buckle self, enter vent

**Comment by jknpj** [comment]
why can you even enter vents while buckled

**Comment by gbasood** [comment]
i'm sure this is duplicate but
#15164

**Comment by gbasood** [comment]
I thought that we fixed this like two years ago
https://github.com/vgstation-coders/vgstation13/issues/14015

WHY DOES ALTCLICK CRAWLING HAVE SNOWFLAKE CODE
WHY ARENT THEY THE SAME PROC
EVERY FUCKING TIME, GUYS
