### ISSUE TITLE
Player Setup doesn't save

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15319]
(WEB REPORT BY: ashemmes REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When saving a character's changes, name, age, nanotrasen relation and handicaps do not save, and upon reload, return to the previous form.
Limbs, hair, underwear etc seem to save though.

>What you expected to happen
For character data to save.

>What actually happened
Only some of it does.

>Steps to reproduce if possible
Make changes, save, reload?

**Comment by SonixApache** [comment]
Stuff doesn't save when you're ready.

**Comment by Exxion** [comment]
I'll check the href logs tomorrow to confirm that was the problem

**Comment by Exxion** [comment]
Well I guess now I don't have to
