### ISSUE TITLE
Missing distro pipe on Bagel 

### ISSUE THREAD

**Issue by Rattlederp** [d3athrow/vgstation13#15310]
![Missing pipe](https://i.imgur.com/m9rxV4X.png)
#### Description of issue
Missing pipe in between the monitoring room and entrance

#### Steps to reproduce 
Be on bagel, watch as the atmos monitoring room never repressurizes because of this missing pipe

#### Specific information for locating
Atmospheric monitoring room on bagel, see picture for reference. This is the view while using a Holomap

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Durgen** [comment]
https://github.com/vgstation-coders/vgstation13/issues/15058

**Comment by Rattlederp** [comment]
fugg I did a quick search before I posted this and now it turns out I'm blind, please close cause duplicate
