### ISSUE TITLE
You can only give a shocking handshake if your target wears non-insulated gloves himself.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#15311]
#### Description of issue
As described, trying to give someone who's wearing no gloves (with a hardsuit covering their hands or not) simply gives no result whatsoever. In the test server I would even stun someone while aiming for the hand and with help intent like a regular stunglove punch but I couldn't reproduce that in either my private testing server and the public server where simply nothing would happen.

#### Difference between expected and actual behavior
To be able to shock people who wore no gloves.

#### Steps to reproduce 
Try shaking the hands of someone with no gloves while wearing a charged stunglove yourself.

#### Server revision

de065b9b413fe60457134bfdb151535a3d1e128c

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Aurx** [comment]
Unless it's been updated since the original PR, handshake code never actually verifies that the shakee's gloves exist, so it runtimes when it checks how insulated they are.  Or maybe it runtimes on the istype() call, dunno if that handles nulls gracefully.

**Comment by Exxion** [comment]
It does. It's the glove part.
