### ISSUE TITLE
Cyborg and potentially human RCD's can deconstruct super reinforced walls.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15318]
(WEB REPORT BY: turbogay REMOTE: 172.93.109.202:7777)
Revision: d1cda375b7d1055ec8f7b7f5e487a42ccf64f824 

General description of the issue
Cyborgs and potentially humans can deconstruct super reinforced walls with the RCD which can be used to cheese certain vaults surrounded by them meant to block this kind of abuse.

>What you expected to happen

Expected to not be able to deconstruct them.

>What actually happened

Clicked a super reinforced wall on accident and it was deconstructed.

>Steps to reproduce if possible

As engineering cyborg, use the rcd to decontruct the super reinforced wall.

**Comment by ghost** [comment]
imagine that

**Comment by Dacendeth** [comment]
Spessmart, here I come...

**Comment by FudgePucker** [comment]
I am pretty sure you can bypass spessmart using disposal pipes still.
