### ISSUE TITLE
Captain's Headset

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15324]
(WEB REPORT BY: leapthatwall REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
883b3138acbd17828943ad39b133c467b987929d 

>General description of the issue
When using the captain's headset, :m will not accurately allow you to speak through the medical frequency, and likewise you won't hear anything from it. Likewise, :n and :u won't work, but :s and :c will.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by strawberrytan** [comment]
All channels but security and command start OFF and need to be turned on by using the headset to communicate on them

Not a bug
