### ISSUE TITLE
chemical smoke needs some more testing, it's really fucky

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15321]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 82ce2c8b7110fdc7450857a57ee82a7afb6d38c2 

>General description of the issue
I was standing outside of chemistry, asking for bleach and a chemist mixed bleach and ammonia causing a smoke cloud. the thing was though, that all the windows and windoors were sealed, so by that logic, none of the smoke should have escaped to me, but it did, bursting my lungs. the smoke sprite didn't go past the windoor either, so the sprite itself never even reached my character, but it still blew out my lungs.

**Comment by ghost** [comment]
Might need better collision checks (does smoke have ANY collision checks?) so that it isn't going through windows like that

**Comment by Eneocho** [comment]
Smoke is known to pierce through windows at times. Not really a feature but kinda something to be expected at this point. Reopen if people complain again or want that specific interaction fixed.
