### ISSUE TITLE
You can take electropack off yourself by switching it with another backpack

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15326]
(WEB REPORT BY: moltevolte REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
:^)

>General description of the issue
You can't take the electropack off yourself, but you can just switch it with another backpack.

>What you expected to happen
To be unable to switch electropack with another backpack.

>What actually happened
I was able to do it just fine.

>Steps to reproduce if possible
Put an electropack on yourself, take another backpack into your hand and click on the backpack slot in your eq.

**Comment by Killette2** [comment]
https://www.youtube.com/watch?v=0gU35Tgtlmg
