### ISSUE TITLE
Nettles Won't Grind

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15330]
(WEB REPORT BY: buttswana REMOTE: 172.93.109.202:7777)
Nettles don't turn into sulferic or formic acid when you grind them, the beaker remains empty and the Nettles are consumed.

I expected them to turn into sulferic acid.

They were consumed and the beaker was left empty.

Grow Nettles, dump them in grinder, grind them.

**Comment by SonixApache** [comment]
#15179
