### ISSUE TITLE
Borg Rename module doesn't let borgs pick their name.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15332]
#### Description of issue

Borg rename modules don't seem to work right; won't let you namepick after being used.

#### Difference between expected and actual behavior

Shit name -> apply rename module -> get force-named by roboticist or get a charge for the namepick verb
***vs***
Shit name -> apply rename module -> get renamed to default -> stuck with default name 5ever

#### Steps to reproduce 

Take borg with picked name and module and sprite, apply rename module.

#### Specific information for locating
*You cannot choose your name any more.*

#### Server revision
411473a4a2a74b0eff17e0bea958a66e4eba9abe

**Comment by SonixApache** [comment]
wow it's supposed to let a human set a borg's name, or let the borg choose their own name
but it does neither, it just resets their name to standard and leaves it at that
fucking quality

**Comment by Knightkiller11** [comment]
Reckon that this issue could be linked to the naming issues MoMMI's have?

**Comment by SonixApache** [comment]
Doubt it, but I can look into it.

**Comment by Exxion** [comment]
Why would you doubt it?

**Comment by SonixApache** [comment]
Because this board is years old and the mommi thing is a recent issue.

**Comment by Exxion** [comment]
Yeah, and so is the board not working
[Honk]

**Comment by SonixApache** [comment]
The board hasn't done anything for the past (1,2,4) years as far as I can tell.

**Comment by Exxion** [comment]
Really? Well never mind then
