### ISSUE TITLE
Holodeck catbeasts lose all their data (vars become null) when switching fields

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15334]
#### Description of issue
![catbeast with no organs](https://user-images.githubusercontent.com/8468269/27800302-145d7778-6019-11e7-971f-861a5c2e3991.png)
Boatload of other vars are null as well, which causes various runtimes.
Not 100% same as #13963 but definitely related.

#### Length of time in which bug has been known to occur
probably since fbdec0ea3fc67277786248e64d56ed918edc9baa, maybe before

#### Server revision
16f8ef9cb7d0f29a892c933964d9828a98e8027d

**Comment by Shadowmech88** [comment]
Holodeck mobs were changed into mimics that just look like the mobs, right? This may not exist anymore.

**Comment by MadmanMartian** [comment]
@N3X15 this bug no longer occurs, as the mobs aren't the same (Changed from carbon mobs to simple mobs that mimic any mob)
