### ISSUE TITLE
Telecomms vs Device analyzer

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15349]
Machines like Telecommunications Relay or Hub should be perfectly scannable by mechanic given that you can scan and recreate teleporter which is arguably the same or higher tech level.
Even more so that telecomms actually fall within Mechanic's spehere of responsibility.

I tried to print telecomm relay and put it in spacemart but my device analyzer gave me an error :rage:

**Comment by jknpj** [comment]
>Even more so that telecomms actually fall within Mechanic's spehere of responsibility.

Just build them from scratch using the damn spare boards

**Comment by ghost** [comment]
That just let's you make one relay.
Box has spare relays in telecom's but you can't say the same about Duny station for example.
Also, gathering all the component is a fucking pain too. I'd rather just shove the metals inside and print a flatpack.

**Comment by SonixApache** [comment]
this is probably a one-line fix, better do it before someone yells "BUT" and it gets the dreaded balance tag
