### ISSUE TITLE
Borgs are supposed to be flammable but aren't for some reason

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15346]
#### Description of issue

Borgs have code for catching/being on fire, but it doesn't seem to work.

#### Difference between expected and actual behavior

*Borg steps in burning inferno, comes out ablaze*
vs
*Borg steps in burning inferno, comes out just fine*

#### Specific information for locating
`code/modules/mob/living/silicon/robot/life.dm#L325`

#### Server revision
c8ab2aa22449e87b6463b560370143c893e0cf80

**Comment by ghost** [comment]
If it gets fixed the, service, and maybe mining borg need an extinguisher added unless they can stop drop and roll.

**Comment by DamianX** [comment]
notice how the silicon metaclub sneakily buffs borgs by giving them a ghetto jetpack

**Comment by SonixApache** [comment]
@SarahJohnson489 they can just walk into space or find a shower.

**Comment by Shadowmech88** [comment]
Was this fixed by #15730?

**Comment by SonixApache** [comment]
Nah, I just fixed the fire indicator in that one. It *should* work, as long as a borg actually catches on fire.
Which I think is impossible.
