### ISSUE TITLE
Gliding as Ghost by Default

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#15341]
#### Description of issue
That gliding thing after haunting a player that gets hurt happens all the time now.
The Fix-Movement verb is a roulette. Sometimes the movement becomes smooth, sometimes the glide goes to maximum slug, sometimes moving by a tile is instant.

#### Length of time in which bug has been known to occur
This didn't happen 3 days ago

#### Server revision
Game: c8ab2aa22449e87b6463b560370143c893e0cf80 
Patches: d5d234fb3c0492546117f441b4dfd59a88acef10 

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this

**Comment by kilozombie** [comment]
It's superbly annoying, but it's only been happening for certain people, it seems like.
