### ISSUE TITLE
Robotic limb related bugs.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#15356]
#### Description of issue
Chemicals are supposed to ignore robotic limbs but I found a few issues.
<ol>
<li>Arithrazine will damage robotic limbs slowly over time.</li>
<li>Medical nanobots will work a fraction of the time and rapidly consume themselves until gone if you have damaged robotic limbs. The chance they heal flesh at all is based on the current ratio of damaged flesh:robotic per tick</li>
<li>Not really a chemical thing but i thought i'd at it, Nano paste doesn't work on robotic limbs.</li>

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
~~wait
Arithazine?
that's not our code~~
oh it's Arithrazine

**Comment by Dacendeth** [comment]
DamianQ told me the medical nanobots dont seem to have a check to see if a limb is robotic or not and they cannot heal robotic parts but they constantly try to until empty. https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/carbon/human/human_damage.dm#L182,
