### ISSUE TITLE
Advanced Silicate sprayers are fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15362]
(WEB REPORT BY: yclat REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The advanced silicate sprayer doesnt work as it cannot be filled up with silicate

>What you expected to happen
To fill the advanced silicate sprayer and to reinforce windows like a good MoMMI

>What actually happened
The Advanced Silicate Sprayer is out of silicate!

The Advanced Silicate Sprayer is out of silicate!

The Advanced Silicate Sprayer is out of silicate!

The Advanced Silicate Sprayer is out of silicate!

The Advanced Silicate Sprayer is out of silicate!

The Advanced Silicate Sprayer is out of silicate!

The Advanced Silicate Sprayer is out of silicate!

>Steps to reproduce if possible
Make advanced silicate sprayer and attempt to refill it

**Comment by Dacendeth** [comment]
Can confirm this is still happening, minor work around is to put silicate in it with a beaker as it refills normally as long as it isn't completely empty.

**Comment by SGuivenne** [comment]
Is this bug still a thing?

**Comment by BarneyGumball** [comment]
Doesn't appear to be an issue any more.  I can fill spawned and protolathed advanced silicate sprayers whether they're empty or not.
