### ISSUE TITLE
Char Slot not Loading

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15360]
(WEB REPORT BY: bigjim12 REMOTE: 172.93.109.202:7777)
>Revision:9adde2dfb27c2e550a87664bcef702de39ca77f0

Server never remembers my slot, although other servers can.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Dacendeth** [comment]
Whatever slot you last saved on is the one it loads upon connecting again at new rounds.

**Comment by SonixApache** [comment]
- Join game
- Load slot you want to work on
- Set up character
- Save Slot
- Save setup
- Ready up

**Comment by ghost** [comment]
Actually that's because of BYOND
Use the older versions

**Comment by Exxion** [comment]
I CAN say with complete confidence that THAT'S not true.
Character slots are completely serverside
