### ISSUE TITLE
Unable to make Firefighter Ripley

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15368]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

519da7868c257db5b3e6d77a908be13ccf66b3ec 
>General description of the issue
You can't finish constructing the Firefighter Ripley.
You get to final steps of Attaching the five plasteel, you can't wrench it. You can however weld the Plasteel off. It has some weird dialogue involving the internal and external armor.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by SonixApache** [comment]
RTFM or RTFC. It uses 10 plasteel.
![image](https://user-images.githubusercontent.com/8468269/27993702-1b0c9848-64af-11e7-8111-35e43d588abe.png)
