### ISSUE TITLE
Knife duplication bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15366]
(WEB REPORT BY: gregovich REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

519da7868c257db5b3e6d77a908be13ccf66b3ec 

>General description of the issue

Taking out the knife from a holster while resting temporarily duplicates the knife

>What you expected to happen

The knife should not be removable while resting

>What actually happened

Trying to remove the knife spawns a knife on the floor, while the knife is still in the holster. The spawned knife disappears when succesfullly grabbing the holster knife.

>Steps to reproduce if possible

Put knife holster on boots
rest verb
Click on boots

**Comment by jknpj** [comment]
just verbs being shit and upate_icon not being called

**Comment by Dacendeth** [comment]
I just tested this and it doesn't seem duplicate, it does however result in teleporting knives still. Lay down and pull out your knife then get up and throw it. Then click on your boots again and your knife will be teleported to your hand. Same thing for gun holsters.

**Comment by Exxion** [comment]
I don't even want to know how the checks fucked up that badly
