### ISSUE TITLE
When your hand is malfunctioning and you drop an item inside a space pod it gets disintegrated

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15369]
Title

**Comment by ghost** [comment]
I mean the item of course

**Comment by ghost** [comment]
Just looked into this; they dropped the thing in the spacepod itself. Not quite disintegrated, but not accessible in any easy way.

**Comment by SonixApache** [comment]
does dragging the spacepod to an empty tile remove the items?

**Comment by ghost** [comment]
Same issue when you get flashbanged or whatever while in a mech. You drop it and poof.

**Comment by yackemflam** [comment]
You drop the items into the cracks of your seat. It's like finding how much coins you dropped in your car

**Comment by Exxion** [comment]
Storage atoms, etc.

**Comment by ghost** [comment]
Now we know where to hide that disc huh

**Comment by Dacendeth** [comment]
Just tested it, it makes you drop the disk "in the pod". The pinpointer points to the pod wherever you move it and the only way to get it out seems to be to explode the pod forcing the disk to respawn somewhere else.

**Comment by MadmanMartian** [comment]
Will fix when I get back

**Comment by ghost** [comment]
@MadmanMartian
