### ISSUE TITLE
Escape Shuttle Hallway Cent Pump 1 isnt conected to the grid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15364]
(WEB REPORT BY: yclat REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The vent isnt connected to the atmos grid at all and as such doesnt work or is able to be used for MoMMI travel

>What you expected to happen
To be able to have more than one vent working and to travel from it

>What actually happened
Disconected vent, no travel. *buzz

>Steps to reproduce if possible
Go to escape, pry floors, see its disconected

**Comment by DamianX** [comment]
#14475

**Comment by yclatious** [comment]
Sorry, was ingame and didn't know.

**Comment by DamianX** [comment]
and this is why the in-game report is shit
