### ISSUE TITLE
Glass floors + layer manifold = invisible manifold

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15374]
#### Description of issue

![image](https://user-images.githubusercontent.com/8468269/28002687-a681d284-6537-11e7-99b8-9968f4d88edf.png)

(The manifolds are beside the Ripley)
#### Server revision
519da7868c257db5b3e6d77a908be13ccf66b3ec

**Comment by SonixApache** [comment]
Also a bug that [needs moar testing]; constructing the floor may result in them being named 'airless glass floor', even when you re-pressurize the room afterwards. I'll report it separately after testing.

**Comment by ihadtoregisterforthis** [comment]
Even after #15354?

**Comment by Exxion** [comment]
That
Had absolutely nothing to do with this
