### ISSUE TITLE
ghost movement choppy bullshit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15370]
(WEB REPORT BY: saronsen REMOTE: 172.93.109.202:7777)
>Revision 519da7868c257db5b3e6d77a908be13ccf66b3ec 

>General description of the issue
ghost movement is choppy and comes to a weird, extremely slow gliding halt

>What you expected to happen
to move around like normal without gliding, like how it has been for years

>What actually happened
camera is choppy as hell when moving, and when releasing movement key you spend nearly two seconds gliding to the center of the last tile you were moving to

>Steps to reproduce if possible
be ghost
move around

**Comment by Exxion** [comment]
I guess this is the worst that could happen

**Comment by gbasood** [comment]
Related to #15341 ?

**Comment by Exxion** [comment]
Yeah and presumably caused by #15214

**Comment by SysadminJeroen** [comment]
Currently bisecting the issue.

```sh
git bisect start
# bad: [519da7868c257db5b3e6d77a908be13ccf66b3ec] [ci skip] Automatic changelog update.
git bisect bad 519da7868c257db5b3e6d77a908be13ccf66b3ec
# good: [d8c0455cbb6be789b92833c8b4aae09b67459283] Adds logging for spraying items. (#12034)
git bisect good d8c0455cbb6be789b92833c8b4aae09b67459283
# good: [4160a0228d058e83f083b3cafb1c3eecef42f467] Automatic changelog update.
git bisect good 4160a0228d058e83f083b3cafb1c3eecef42f467
# good: [e44004882f22cce960eab1d157f89abd88e9b20e] [ci skip] Automatic changelog update.
git bisect good e44004882f22cce960eab1d157f89abd88e9b20e
# good: [abf4629c3e5c44d00851b2e4733c4aff9a7a6ddb] Cursed dice changes (#14925)
git bisect good abf4629c3e5c44d00851b2e4733c4aff9a7a6ddb
# good: [1c2f4e7ae08d403e0f6e8b90febe515eef113196] forgot to remove defunct apply effect line.
git bisect good 1c2f4e7ae08d403e0f6e8b90febe515eef113196
# good: [b853412661b3cd0fc1297218119a4e28746bab5e] [ci skip] Automatic changelog update.
git bisect good b853412661b3cd0fc1297218119a4e28746bab5e
# bad: [89bccdd55743915235f81e9ac22a8eed59b31c2a] Fixes MoMMI namepick (#15335)
git bisect bad 89bccdd55743915235f81e9ac22a8eed59b31c2a
# good: [c7854208d7ec615b36da1026ac9f8e2974c2527e] In hand sprites for valves (#15264)
git bisect good c7854208d7ec615b36da1026ac9f8e2974c2527e
# bad: [3f2876c8c4ac1fab684b3d3c56a4afc8f42cf9dc] re-adds magbite slowdown (#15336)
git bisect bad 3f2876c8c4ac1fab684b3d3c56a4afc8f42cf9dc
# bad: [6102fc7da1d21a062abbf9a330054e9871764db7] fixes dylans meme-fuck (#15287)
git bisect bad 6102fc7da1d21a062abbf9a330054e9871764db7
# bad: [63a39a7218af768b87b176b9d9272730457a91b9] [ci skip] Automatic changelog update.
git bisect bad 63a39a7218af768b87b176b9d9272730457a91b9
# bad: [a8c3bd7c1e619c9d9f06c82067f15fdaed70ef44] Hopefully fixes some stupid glide size shit. (#15214)
git bisect bad a8c3bd7c1e619c9d9f06c82067f15fdaed70ef44
# first bad commit: [a8c3bd7c1e619c9d9f06c82067f15fdaed70ef44] Hopefully fixes some stupid glide size shit. (#15214)

```

**Comment by Fruktlimpa** [comment]
Correct me if I am wrong but this happens on the more recent Byond versions. I had this shit when I upgraded to the latest version which I cannot remember which it was, I also got the same issue while being the AI so I downgraded down to 511.1378 and haven't noticed the same kind of choppiness.

**Comment by Exxion** [comment]
Client version SHOULDN'T matter for this, but I can't say with 100% confidence that it actually doesn't

**Comment by Fruktlimpa** [comment]
Yeah, I cannot be certain it is because of the client, I only remember that I have definitely felt choppiness as a ghost and AI and that it went away when I downgraded.

**Comment by SysadminJeroen** [comment]
So I thought that I had a good idea how to preproduce this issue, but bisecting it hasn't been too kind.

**Comment by Exxion** [comment]
You need two people to do it

**Comment by SysadminJeroen** [comment]
@Exxion I was able to reproduce the bug using `spawn carbon/human.`, following it, and then varediting a ton of damage so they die.

**Comment by SysadminJeroen** [comment]
The bisecting has finished, the commit that introduces the bug has been found. It is this commit: a8c3bd7c1e619c9d9f06c82067f15fdaed70ef44
The `git bisect log` is detailed here: https://github.com/vgstation-coders/vgstation13/issues/15370#issuecomment-313977594

**Comment by Exxion** [comment]
Honestly you didn't really have to do that in this particular case
But thanks for doing it anyway

**Comment by SysadminJeroen** [comment]
The choppyness was really grinding my gear, I really can't stand it and I hope that a codermin will fix it ASAP.

**Comment by gbasood** [comment]
it's nice to have affirmation but uh
someone already pointed out that commit as the problem like a week ago

**Comment by SysadminJeroen** [comment]
@gbasood It was pointed out yesterday in this issue. And now there is more affirmation.

**Comment by Exxion** [comment]
Well, until this gets fixed, I've discovered the problem with the fix movement verb is that it sets the glide size based on how long it's been since you last moved
So it works perfectly if you use it while moving
So that's a workaround, at least

**Comment by jknpj** [comment]
WE SMOOTH NOW
