### ISSUE TITLE
Strange floor overlay behaviour in custom rooms

### ISSUE THREAD

**Issue by Knightkiller11** [d3athrow/vgstation13#15386]
So as an Autism MoMMI I was building a observation room for the bridge, and decided to place down some garish ass light tiles, however upon removing them for repositioning I noticed that the coloured light bit of the tiles remained. So I tested what happens with a foam extinguisher, and this is the result:
![image](https://user-images.githubusercontent.com/25286638/28048733-ae9cbb56-65ea-11e7-826b-93b1cbe38aca.png)

No idea why it happens, but I assume it has something to do with floor overlays

Also apparently fire suppression foam can hold a pAI, considering that it has a "Remove pAI" verb if you select it on the alt menu

**Comment by BarneyGumball** [comment]
Seems to have been fixed by #15895.
