### ISSUE TITLE
Issues with the custom vending machine already

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15384]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
custom vending machine stopped working at one point, and adding more things to the machine simply deleted the stuff. I don't know what exactly triggered it to become unusable. I don't think it was something external since I was baby sitting the machine, but yeah, I had like 40 stuff for sale, next thing I know it tells me no product loaded. adding more product removes the product and tells me no product loaded. needs a bit more testing.

**Comment by RealestEstate** [comment]
also, tried deconstructing it and reconstructing it. when I deconned it, I saw inventory drop, so I moved some of it and rebuilt the vending machine. I noticed I was missing inventory when I loaded it back up, so there's definitely some items being removed, but I don't know how or why.

**Comment by SonixApache** [comment]
@d3athrow

**Comment by d3athrow** [comment]
I'll figure this out when I have the opportunity

**Comment by d3athrow** [comment]
So far I can't reproduce locally

**Comment by RealestEstate** [comment]
I pried out the circuit board, to be more precise, that's when the inventory was ejected. I just glanced through the inventory, took some stuff off the tile of the deconned vending machine, left the rest of the inventory on the tile, then reconstructed the vending machine on the exact same tile. I wonder if reconstructing the machine over the stuff had an effect. I alt-clicked, so I don't think it was being blocked by the vendo

**Comment by d3athrow** [comment]
Tried that and no change in behavior.

**Comment by ihadtoregisterforthis** [comment]
Runtime?

**Comment by Sooose** [comment]
Had a similar problem, set up the vending machine to my account and walked away for 30 seconds maximum to load up a recharge kit. I placed 5 bullwhips in the recharge kit and double checked that the recharge kit showed them. Upon loading the vending machine it did not contain any bullwhips and the recharge kit was consumed back into cardboard.

**Comment by d3athrow** [comment]
The version you can spawn from sandbox or admin menu is buggy and you can't add items to it (why zth), screwdriver and pop the circuit board out and remake it and it will work fine for testing.

**Comment by Kurfursten** [comment]
Apparently Zth fixed this
