### ISSUE TITLE
Random loss of gender

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#1539]
No clue what's causing this, but more times than not, I and many others end the round with "It" pronouns and male chests on a female sprite.

It's fucking weird.

**Comment by clusterfack** [comment]
Doesn't seem reproduceable. Might as well close this unless someone actually knows how to reproduce it.

**Comment by Angelite191** [comment]
It might have something to do with the update proc. Something screws up when updating the human icon.

**Comment by clusterfack** [comment]
Alright, I've seen this IN a round for the first time and view variable'd it  The player had a PLURAL gender (die cis scum) so I asked the player how he managed to do it. This is how he said he did it.

>Humanized a monkey, injected it with my UI+UE, beheaded it,  made a UI+UE of its headless body, injected myself with that.
