### ISSUE TITLE
Mask of the Phantom allows access to CentComm

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#15397]
Dear god

**Comment by Allspice** [comment]
FEEAAATUUUUUUREE

**Comment by ghost** [comment]
How? How does it allow access to centcomm?

I can't work with a dear god, a deer god maybe, but a dear god I can't do fuck all with

**Comment by ihadtoregisterforthis** [comment]
If you can use the teleport or follow verbs, jump to the thunderdome or the dead Judge Dredd. Maybe even a test dummy.
Or maybe you can step on the cargo shuttle and tell someone to send it out.

**Comment by ghost** [comment]
>it just straight up turns you into a ghost

SHUT

DOWN

EVERYTHING

**Comment by RealestEstate** [comment]
maybe we could make a subtype of ghost called the phantom and restrict it from going to restricted Z-levels like Z-2 and whatnot

**Comment by ghost** [comment]
that sounds actually quite reasonable.

**Comment by Exxion** [comment]
There already is a subtype, and I was going to do that today

**Comment by ghost** [comment]
This shouldn't be a surprise to anyone.

https://github.com/vgstation-coders/vgstation13/pull/14069

The PR stayed open for a month, citing its functionality in the comments, and it was still merged with such.

**Comment by CptWad** [comment]
Why DID this get merged?

**Comment by Exxion** [comment]
It shouldn't be, but it was.
Somehow nobody (who spoke up at least) saw that coming, despite it being absolutely obvious in hindsight

**Comment by Dacendeth** [comment]
Just like to tack on that it allows you to hear admin deadsays

**Comment by Exxion** [comment]
I honestly can't blame Shadowmech for that one
Sounds like `dsay`code is just garbage
