### ISSUE TITLE
Choice of assistant in job preferences is misleading

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#15408]
#### Description of issue
If you select assistant in your job preferences, it appears to override all of your other job preferences.
![](http://i.imgur.com/E5D1ITJ.png)
This is not the case however. If you have anything else selected in your job preferences, they take priority over assistant.

#### Difference between expected and actual behavior
Assistant should override any other job preferences, as it currently appears

#### Steps to reproduce 
Select medium/high on every other job, and then toggle 'assistant' to yes. You will be guaranteed to not get assistant.

#### Server revision

5b3905640311d4700c0a95c5e72afb7b3d9be06e 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Lokiamis** [comment]
Assistant shouldn't be a toggle on the first place. It's dumb. Let me out it in the lottery with everything else.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is fixed @Exxion
