### ISSUE TITLE
Maintenance protocols enabled when they were forbid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15414]
(WEB REPORT BY: pshy3214 REMOTE: 172.93.109.202:7777)
Borgs went rogue and started attacking, luckily i was in my mech to avoid the plasma however they enabled maintenance protocols on me, luckily the borg i was fighting was killed so i hopped out, terminated maintenance and then hopped back in to lock it. This did not help.

>What you expected to happen

For the borgs to not disable the mech once the protocol was forbidden

>What actually happened

The maintenance protocol was enabled however since i disabled it, i couldnt terminate the maintenance

>Steps to reproduce if possible

forbid maintenance, then have a borg enable it. Possibly damage the mech first?

**Comment by Allspice** [comment]
Did you not remove the beacon from your mech

**Comment by SonixApache** [comment]
remote beacon can remote lockdown you
