### ISSUE TITLE
Stealing from behind a wall via telekinesis

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15418]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
By using telekinesis, if you stuff something into a comfy chair's cushions, you can later take it out  of the chair from behind a wall or window and have it in your hand.

**Comment by ghost** [comment]
TK calling attack_hand by default was a mistake

**Comment by Killette2** [comment]
I reported this already >:(
