### ISSUE TITLE
Pills put in vendor are displayed only as "Pill"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15416]
(WEB REPORT BY: valkyrieskies REMOTE: 172.93.109.202:7777)
Put a bunch of labeled Opium pills in the custom vendor, when I look at them in the vendor buy screen they were all just listed as "Pill". Kinda shit if you wanna sell medicine or drugs.

**Comment by Kurfursten** [comment]
Additional consideration if someone decides to fix this: it DOES need to specify that it is a pill (or food item, or whatever). Because otherwise you might just name your pill "ablative armor" and put it in the vendor.

**Comment by d3athrow** [comment]
@Kurfursten Would be pretty snowflakey to do that

**Comment by ghost** [comment]
Pills already get "pill" forcibly added at the end of their "input" name at the chemmaster, but you could still rename food with a pen to do the swindle described above

**Comment by RealestEstate** [comment]
@Unknown-as-Captain the ultimate jew tactic.

**Comment by d3athrow** [comment]
That's an idea, I just made it show the original name for the time being.

**Comment by Kurfursten** [comment]
@d3athrow We could avoid snowflaking behavior by using the vending machine's categories. Make item classes food and pill.

e.g.: When you look at the boozeomat you have categories for spirits, fermented drinks, etc; seed vend separates by fruits, vegetables, etc.

**Comment by d3athrow** [comment]
Are the mini icons not adequate @Kurfursten

**Comment by Kurfursten** [comment]
Nah they work great
