### ISSUE TITLE
Activating flares

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15415]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
5b3905640311d4700c0a95c5e72afb7b3d9be06e 

>General description of the issue
When you pick up a flare you get an icon in top left corner to light it. When I put it in a toolbox from oxygen lockers I was able to light the flare no matter how far I moved

>What you expected to happen
Icon disappearing when moving away from toolbox

>What actually happened
Icon stayed forever

>Steps to reproduce if possible
Put a flare in a toolbox/container

**Comment by SonixApache** [comment]
action buttons strike again

**Comment by jknpj** [comment]
sanity pls
