### ISSUE TITLE
Monkeymen vomit into rejuvenator bottles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15413]
(WEB REPORT BY: vuoristo REMOTE: 172.93.109.202:7777)
>Revision 5b3905640311d4700c0a95c5e72afb7b3d9be06e 

>General description of the issue
Monkeymen in DNA pods will vomit into rejunevator beakers

>What you expected to happen
The vomit shouldn't go in the beaker

>What actually happened
The monkeyman vomits into the beaker

>Steps to reproduce if possible
Put a rejunevator into the DNA pod and have the monkeyman vomit

**Comment by jknpj** [comment]
this is my favorite bug now

**Comment by Killette2** [comment]
rejuvination pods?
You mean when people actually put medicine in the genetics computers?

**Comment by Kurfursten** [comment]
All of these "vomit into" bugs could be simultaneously fixed by a check to see that the  open container you want to vomit into isn't inside machinery.

**Comment by Exxion** [comment]
Yeah but they could also be fixed by just closing your beakers
[Honk]

**Comment by Killette2** [comment]
@Kurfursten fuck you you cunt, that's fun
Vomit powered infinite cryogenics

**Comment by west3436** [comment]
Close the beaker before inserting it into the machine
