### ISSUE TITLE
Box Station medbay lacks Plasmaman and Vox suits

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15422]
(WEB REPORT BY: valkyrieskies REMOTE: 172.93.109.202:7777)
897b81d32834d508ae3631cbe487f0be59a3406b 
Kinda important if you want to treat either of these species if their orginal suits are lost.

**Comment by ghost** [comment]
I added the xeno space suits to cargo for this very reason.
