### ISSUE TITLE
Soldering a Starscreen circuit board makes it disappear

### ISSUE THREAD

**Issue by Rattlederp** [d3athrow/vgstation13#15426]
#### Description of issue
Upon being soldered, the message about converting the starscreen circuit board into the EX appears but the circuit board disappears, happens when converting a Starscreen EX to normal as well

#### Difference between expected and actual behavior
Expected to get Starscreen gen EX, got nothing

#### Steps to reproduce 
Solder a starscreen gen board

#### Server revision
Game: a49a1f110a65badc048704f90c9bcfbb943f57f5 
Patches: d5d234fb3c0492546117f441b4dfd59a88acef10 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Rattlederp** [comment]
@SonixApache

**Comment by SonixApache** [comment]
goddamnit
