### ISSUE TITLE
Box Interrogation room intercom

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15438]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Can't access or use the intercom of box station's interrogation room, it's behind a glass full window

>What you expected to happen
The ability to use the intercom

>What actually happened
Nothing, cant access it.

>Steps to reproduce if possible

**Comment by Shadowmech88** [comment]
Fixed by #15441.
