### ISSUE TITLE
Immortal cyborgs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15437]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
57d5d74388084385bb7ee6ba37655c76b50d32b7 

>General description of the issue
Borgs are unkillable if they have no cell and reach anything between 250-280dmg

>What you expected to happen
Damage going over 250-280 and dying

>What actually happened
When the cell is removed and you use a weapon that deals less than 25 damage per hit, damage will stay at something between 250 and 280. It will not go up after that unless its an explosion. Even pulse rifles are useless against a borg in that state. So a cyborg without a cell can ONLY BE KILLED by a weapon with 25 damage per hit. Problem is, no matter how damaged the borg is, it can still move unless you actually kill it. So players stay in limbo - suicide or ghost means they lose any chances of actually coming back to the round without losing memories.

>Steps to reproduce if possible
Remove a cell, bash with a toolbox/fireextinguisher/anything that has less than 25damage. THAT INCLUDES ION RIFLES

**Comment by SonixApache** [comment]
what

**Comment by Allspice** [comment]
Sounds like the damage to each other part was at the cap of 30 or 60 depending, so the parts (and the cyborg as a whole) could not be damaged further. Should be doable by removing any other part like the actuator or cameras.

**Comment by tayachiya** [comment]
Only tried it with a cell because that's the only part people remove mid-fight
But then you need at least a laser gun to kill the poor bastard, or it'll get stuck in an undying state
Unless you blow it up

**Comment by Chazach** [comment]
![screenshot_2017-07-16-23-37-28](https://user-images.githubusercontent.com/25990485/28252092-62b21b3e-6a84-11e7-9398-38e25aa88ee1.png)
tfw

**Comment by Blithering** [comment]
There's also the issue that while they can still move, they can push people into hazards such as a room with active turrets or shocked doors, and generally be a hindrance

**Comment by jknpj** [comment]
i doubt they can be a hindrance because without battery move 3 times slower than a diona but the bug is still a thing and needs to be solved.

**Comment by tayachiya** [comment]
They can still open doors by bumping into them
