### ISSUE TITLE
Can't save to new character slot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15434]
(WEB REPORT BY: tellossee REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
563077630105e413ef8a06baa21459ea96983046

>General description of the issue
Can not save to a new character slot

>What you expected to happen
Edit character, click "save slot" and it save to an open character slot. It doesn't, just overwrites the current character.

>What actually happened
It overwrote the current character slot

>Steps to reproduce if possible
Load a slot, change it, click "save slot"

Also, I don't have this issue on the test server, just the main one. I also tried "save setup" to the same effect. I have 4 open character slots.

**Comment by west3436** [comment]
Unable to reproduce/more information needed. Will reopen if information is provided.
