### ISSUE TITLE
All inventory disappeared from custom vendor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15431]
(WEB REPORT BY: valkyrieskies REMOTE: 172.93.109.202:7777)
563077630105e413ef8a06baa21459ea96983046

After loading a few more refills into my vendor, the stock suddenly all disappeared and it displayed as "No products loaded!" to everyone who looked at it. According to admins, all items were still inside, but they couldn't see them when using it either.

**Comment by west3436** [comment]
Unable to reproduce/more info needed. Will reopen if additional info is provided by @ValkyrieSkies.

**Comment by ValkyrieSkies** [comment]
>7 years ago

Sorry mate but I don't even remember this happening at this stage.
