### ISSUE TITLE
Each component from ECS should have a good complete description 

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15442]
#### Description of issue
Most of the components meant to be reused so it's obvious people should clearly know HOW to use it, WHAT it does, and WHERE is examples of component's use.
Imagine that you creating generic components and then some dumbass creates special snowflake component meant to be used only in his animal farm PR. What enrages you is that component is just a copypasta from 3 of your components. You found that out 7 month after that dumb PR got merged by maintainer who gives zero fuck to ECS...

It's so important that we even need to force descriptions being required in Component PRs, maybe make a script which will translate descriptions into wiki page...

**Comment by Exxion** [comment]
@ihadtoregisterforthis 😕

**Comment by jakmak6** [comment]
ECS?

**Comment by gbasood** [comment]
Entity Component System
It's a design pattern, you can look it up on normal people wiki

**Comment by ghost** [comment]
Yeah i need to clarify what is ECS here:
https://en.wikipedia.org/wiki/Entity%E2%80%93component%E2%80%93system
Read this wiki article to understand what ECS is.

ECS was requested by #13429 and got implemented and merged into codebase
This is @N3X15 implementation based on Unity entities:
https://github.com/vgstation-coders/vgstation13/pull/13866
This is API reference:
http://ss13.moe/wiki/index.php/User:N3X15/Components

More components:
https://github.com/vgstation-coders/vgstation13/pull/15172

**Comment by gbasood** [comment]
>This is @N3X15 implementation based on Unity entities:
Unity

u wot

**Comment by ghost** [comment]
@gbasood Unity MonoBehaviour is a strong and flexible ECS implementation which suits well in linear inheritance language like DM
