### ISSUE TITLE
Plasma Supply Control bugged on bagel.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15443]
(WEB REPORT BY: smedley8 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
a57ba61461feffbb4326678e3d50b08f2b6279b9 

>General description of the issue
Plasma supply control computer in Bagel Atmos is not working as expected. After puting the Output to on hold and turning on mix to waste, the mix still repressurised.

>What you expected to happen
The mix would have emptied.

>What actually happened
The mix repressurised.

>Steps to reproduce if possible
Try to depressurise Plasma to mix.

**Comment by Shadowmech88** [comment]
Fixed by #15441.
