### ISSUE TITLE
Following a head that gets poly acid sends you the nullzone

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15454]
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: e1767916b8e3dd21569dca0caa8c350dc734c500 

>General description of the issue
Following a head that gets polyacid sprayed sends you to the nullzone

>What actually happened

Was following a person who was recently killed and beheaded, I suppose they were in their head at the time, when it was poly acid, I was sent to the nullzone area thing

>Steps to reproduce if possible
Follow a ghost that is in their head
get the head polyacid
Sent to ghost hell

**Comment by Shadowmech88** [comment]
This isn't technically a bug, since aciding an item deletes it and deleted items are sent to nullspace, to which you followed it.
Given that ghosts are capable of teleporting out of nullspace, I'm not sure anything needs to be done about this.

**Comment by Exxion** [comment]
All locked atoms should be unlocked in `/atom/movable/Destroy()` or whatever the highest appropriate type is

**Comment by Exxion** [comment]
Oh wait
They probably are
But you're following the brainmob inside the head, not the head itself

**Comment by Shadowmech88** [comment]
So is the solution to have the `Destroy()` of head objects unlock everything from the brainmob inside the head, if there is one?

**Comment by Exxion** [comment]
Presumably they're unlocked in the brainmob's `Destroy()`
They're just still inside the head, I guess

Give me a moment to look into locking categories.

**Comment by Exxion** [comment]
I'd say do one of these:

1\.
Add a flag (either a lockflag or a locking_category flag) that moves the previously-locked object to the turf when unlocked, and give it to ghosts (if a lockflag) or the observer locking category (if a category flag)

2\. 
```
/datum/locking_category/observer/unlock(atom/movable AM)
    . = ..()
    AM.forceMove(get_turf(AM))
```

Strictly speaking, the former is probably more proper, but I can't imagine any use for the system other than ghosts, so it seems like unnecessary complexity.
