### ISSUE TITLE
Infinite Cells Break APC UI

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#15455]
Causes the UI to be blank and the game to send an infinite number of error messages in a popup box instead. Obviously this is only something that affects admins/coders/testers. Tested on test server.

Probably caused by #14638

@PJB3005

**Comment by N3X15** [comment]
JSON implementation in BYOND has issues with infinite numbers.

**Comment by clusterfack** [comment]
Told people it was a dumb idea, shame pjb went behind my back to cause this bug.

**Comment by Killette2** [comment]
Why not use math.huge
