### ISSUE TITLE
Cargo Shuttle Decompressed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15459]
(WEB REPORT BY: kommandre REMOTE: 172.93.109.202:7777)
>Revision bae4f47eb8166af0fb11da2c83aa260ad8c42009

>The cargo shuttle is always decompressed now, probably due to no windows by the boosters

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by DamianX** [comment]
This is in bagel, of course. Thank you, in-game reporters.
