### ISSUE TITLE
[Bagel] No beach? Supermatter cascade event is borked

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#15462]
#### Description of issue

We had a supermatter cascade happen on Bagel the other day (thanks mustard you fuck) but everyone got stuck under the rift bubble rather than being ported out.
More specifically, the big beach bubble was there, and being near it allowed you to phase through walls, but it didn't do anything.

#### Difference between expected and actual behavior

brilliant flash of energy -> touch beachcrab bubble -> get to metaclub private beach
vs
brilliant flash of energy -> touch beachcrab bubble -> run around under the bubble like an idiot

#### Steps to reproduce 

Cause a supermatter cascade on Bagel.

#### Specific information for locating

If the beach isn't there, or isn't set up right, that is probably the reason.

#### Length of time in which bug has been known to occur

One day.

#### Server revision

ce907c04f4222d87df11da0888e8beda5d9afe62

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [ ] Couldn't find an existing issue about this

**Comment by jknpj** [comment]
ditto of #12818

**Comment by SonixApache** [comment]
whoops
