### ISSUE TITLE
Can hear blob whispering in lobby.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15481]
(WEB REPORT BY: wutnold124 REMOTE: 172.93.109.202:7777)
>Revision:ff27632dffc62ec6c111af8fac95ae9064af8e05 

>General description of the issue
Joined, instantly saw "Your vision becomes cloudy ..." text and saw a blob speaking.

>What you expected to happen
Not being able to hear a blob speak in the lobby.

>What actually happened
I joined the server and saw a blob whispering.

>Steps to reproduce if possible
Join ongoing round with an active blob.

**Comment by gbasood** [comment]
maybe not even loose actually but still bad
