### ISSUE TITLE
Wrenching table parts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15485]
(WEB REPORT BY: yackemflam REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Table parts disappear when you wrench them in hand

>What you expected to happen
Table parts to turn into a sheet of their material

>What actually happened
They disappeared into somewhere

>Steps to reproduce if possible
Wrench a table part that is in your hand

**Comment by DamianX** [comment]
Must have been me.
