### ISSUE TITLE
pAI and borer dont mix

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15493]
(WEB REPORT BY: libertino REMOTE: 172.93.109.202:7777)
I cant inject chems into my master as a pAI, i suspect it is because of the borers he had.
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When i try secreting chems it says i need a carrier to inject chems into.

>What you expected to happen
It should have injected coffee.

>What actually happened
It said i needed a carrier to inject chems into, despite being in his pocket and having his dna.

>Steps to reproduce if possible
Place a couple borers into someone and try to inject chems as a pAI

**Comment by jknpj** [comment]
Because you need to be either on his hands or pocket/id slot. Inside the PDA/Bag won't do.

**Comment by Blithering** [comment]
It bugs me you can't dispense chems from the PDA pAI slot. Makes it a lot less useful.
