### ISSUE TITLE
dimensional pushing a humanoid cube kills pomf

### ISSUE THREAD

**Issue by small-boss** [d3athrow/vgstation13#15498]
#### Description of issue
If you dimensional push a humanoid cube it will make the server slow down and make it unplayable.

#### Difference between expected and actual behavior
Expected: It teleports the cube in a random spot
Actual: It fucks everything up

#### Steps to reproduce 
1. Turn someone into a cube
2. Dimensional push the cube
3. Get deadminned

#### Specific information for locating

https://pastebin.com/84BiFwKT this is what happens when the spell is used.

#### Length of time in which bug has been known to occur

Since the compactor was merged probably

#### Server revision

b583efc991248630a64d2b8c2eefc02eb05c1a6b 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
Your pastebin was deleted, what was it?

**Comment by SonixApache** [comment]
runtimes?

**Comment by Fruktlimpa** [comment]
Ah fuck me. It was my pastebin and I set it to expire by mistake. It was a dreamdeamon log. I can get to testing it again and saving some logs later.
There were only 3 runtimes at the time from "Updating action buttons" or whatever it was called.

Is there any other logs I should try grab? The server stalls like crazy and getting something out of it after doing the push isn't easy.

**Comment by DamianX** [comment]
maybe run the profiler and screenshot that?

**Comment by Kurfursten** [comment]
If you plan on doing more testing, please spawn in a "humancube" manually, it should be empty. Try pushing that first to see if it causes problems. Then test it on a monkeycube.

I suspect the empty cube will not cause problems but the monkeycube will. If so this will validate my suspicions about how to fix this.

**Comment by Fruktlimpa** [comment]
@Kurfursten I ran the profiler this time and this was the result. This screenshot was taken pretty much 45 seconds after pushing myself.
Also to reiterate, this only happens if you push YOURSELF when you are a cube yourself. 

Pushing a cube with a human in it and a cube without one didn't matter. 
![dreamseeker_2017-07-26_18-15-00](https://user-images.githubusercontent.com/19466872/28631829-de6114ea-722e-11e7-8359-7d0c1d0302a2.png)

**Comment by Kurfursten** [comment]
Can you dimensional push a locker while inside it (with the locker closed)?

**Comment by Fruktlimpa** [comment]
I'm not sure, I'd have to test that. But Damian said something about the push code searching for a turf on the z-level that the caster currently is on.
And correct me if I am wrong but doesn't the cubes store the mob in nullspace? So the push spell tries search for a turf in nullspace which I'd assume doesn't really work like it should.

**Comment by Kurfursten** [comment]
They only store roundstart mobs in nullspace, because you can't put something inside another object during the definition of an object. So any mobcube created with the compactor just stores the mob inside the cube.

**Comment by Exxion** [comment]
Oh dear fuck
Why does dimensional push `get_area_turfs()` EVERY TIME it picks a turf whose `z` isn't the caster's `z`?
I mean even if it didn't do that, it would still cause an infinite loop if the caster doesn't have a valid `z`
But that's also not good

**Comment by Shadowmech88** [comment]
@Exxion 
The reason it has to re-pick the turf using `get_area_turfs()` if it doesn't match the caster's `z` is because `area`s do not have coordinates. So the only way to know whether the randomly-chosen area is on the same Z-level as the caster is to check the `z` of a turf in the area, which necessitates using `get_area_turfs()`.

**Comment by Exxion** [comment]
No, I mean it should fetch the list of turfs once, and just `pick()` from it every time

**Comment by Exxion** [comment]
The list of area turfs should only be fetched once per area, not once per turf

**Comment by Shadowmech88** [comment]
It *is* only fetched once per area.
If the chosen turf's `z` isn't the caster's `z`, a new area is randomly chosen, and then a new turf is picked from that new area, and so on.
Only one turf is picked per area.

**Comment by Exxion** [comment]
You're right. I misread something.
