### ISSUE TITLE
[Feature request] Detective equipment upgrade for Secborgs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15503]
(WEB REPORT BY: lisandrabrave REMOTE: 172.93.109.202:7777)
Powergayman sillycon just wants to be more useful to the station. Also, humans can't law 2 to tell you to not investigate if they're not there.

**Comment by DamianX** [comment]
what did he mean by this

**Comment by jknpj** [comment]
secborgs are literally overgrow beepskys

**Comment by SonixApache** [comment]
compromise: make it remove the taser

**Comment by Blithering** [comment]
I could see the use in a board that swaps the taser, baton and cuff modules for a scanner, camera and evidence bag.

**Comment by Riekland** [comment]
This is an absolutely fucking awful idea
You can already get a secborg to remove evidence for you letting them be in charge of analyzing evidence is such a bad idea
law 2 tell them that urist mcfuckface's prints are on it not mine

**Comment by ShiftyRail** [comment]
Fixed by vox trader modules
