### ISSUE TITLE
Fat people can eat the nuke disk

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#15504]
#### Description of issue
If a fat person puts a nuke disk on a monkey and eats the monkey, the disk is stored in the fat person's container.

#### Steps to reproduce 
Be a fat person
Get the nuke disk
Get a monkey
Put the disk in the monkey's hand
Eat the monkey
You now have the disk in your body, which can only be removed through gibbing

#### Specific information for locating

I know @Intigracy was the one who worked on the revamp of eating people

#### Server revision

1ba76cf440e5295c2bc55da463f77cc4e424a01f 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
The correct answer is to remove vore

**Comment by Kurfursten** [comment]
The correct answer is to add a stomach organ

**Comment by drawsstuff** [comment]
Tested ingame, can confirm it works.
