### ISSUE TITLE
Detective's Camera Bugs on Bagel Station doesn't have a mobile viewer, rendering them useless.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15501]
(WEB REPORT BY: zyrodil REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
There is a cigarette pack in the Detective's office with Camera bugs inside of them. To use them fully, you need a Monitoring device of some sort. But there is no such device to be found in the Detective's office, which means that you have useless Camera Bugs you can put everywhere but you can't use them.

>What you expected to happen
I would expect either no Camera Bugs in the Detective's office or (more preferably) a Video Monitor-device of which would view the video feed of these Camera Bugs.

>What actually happened
I had a package of Camera Bugs for no reason.

>Steps to reproduce if possible
1. Go to the DromedareCo Cigarette pack and pick it up.
2. Ask if one of your security friends wants a cigarette.
3. Pull out Camera Bugs.
4. Search through your office for a Video Device.
5. Fail to find a Video Device.

Thanks for your time, admins. It's not a game breaking thing, it's just wierd that there's Camera Bugs and no way to use them.

**Comment by SonixApache** [comment]
Can't you use that stationary TV to view them?

**Comment by Zyrodil** [comment]
I can view all cameras from the stationary TV. Which again would render the Camera Bugs useless.
I guess I can use the Camera Bugs "on the go" with a mobile video-device, which might be useful (if not a bit redundant).

**Comment by Exxion** [comment]
The mobile one is what the camera bugs are for.

What you need to do is go into maint and cut into that little room that has a chance to spawn a portable TV every round and hope it has one

**Comment by Ephx1** [comment]
Why would there be an object that spawns 100% of the time that relies on a random chance spawning object elsewhere?

**Comment by Exxion** [comment]
That was a joke
