### ISSUE TITLE
Packedstation- TEG Burn room scrubbers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15514]
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
Revision: 27515e0b8e6cacd87358a3345ac018f79270d1b2 
>General description of the issue
The pipes are not connected together and won't connect together since the h/e pipes is blocking the replacement of the pipe
Also it is not connected to the outside vent at all round start

**Comment by redbluefreak** [comment]
Forgot push links 
https://puu.sh/wT2Fe/732704f6ee.png -round start
https://puu.sh/wT2Fe/732704f6ee.png -after getting the pipe into place
