### ISSUE TITLE
Janicart Timestop

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15530]
(WEB REPORT BY: ozymandias37 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
Janicart still in use when not on player

>General description of the issue
A wizard used the timestop spell while I was on the janicart. After it ended, I still am high off the ground as if I'm on the janicart even though it has remained stationary from the timestop.

>What you expected to happen
The janicart and my character to stay "attached"

>What actually happened
They became disjointed

>Steps to reproduce if possible
Timestop an area that has a janitor on janicart

**Comment by strawberrytan** [comment]
I think this is an issue with all janicart style vehicles such as wheelchairs and secways

The only fix in game right now is to climb back on then get off manually

**Comment by Exxion** [comment]
It's also not exactly an issue with timestop
I believe it happens whenever anything knocks you off it at all
Though I'm not sure why timestop knocks you off it

**Comment by DamianX** [comment]
Yes, being stunned by something like a taser has the same effect.

**Comment by BarneyGumball** [comment]
Not sure what changed but timestop doesn't knock you off the janicart any more and being tased off the cart resets your pixel offset properly.

**Comment by DamianX** [comment]
It was never timestop knocking you off, but specifically the vehicle's `relaymove` in the event you couldn't move, if I understand vehicles correctly. Either way it was fixed by #19962
