### ISSUE TITLE
Bagel: Cargonia Issues

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#15549]
* The monitors in cargo bay do not display time until the cargo shuttle arrives.
* Some of the MULE locations are broken, I only tested Medbay but I am sure there are others. I did in fact check the medbay beacon to make sure it was called Medbay, and it is.
* The barren hallway near the warehouse and final disposals seems like it could use the addition of something. If nothing else, I notice there are no fire closets in that area of the station.

**Comment by CptWad** [comment]
fixed
I need examples otherwise digging through them will only lead to me missing some
Alright I threw a fire room in there. Sadly the use of mass drivers means I cant ring around maint past disposals and chapel

**Comment by Kurfursten** [comment]
I'll conduct some additional testing on local.

**Comment by Kurfursten** [comment]
On local, the beacons seem to be working. Perhaps it was just a really crafty greyshit who tampered with navbeacons that one shift?

Either way, good work with the rest.
