### ISSUE TITLE
Bees stinging bees

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15555]
(WEB REPORT BY: oliverklohsoff REMOTE: 172.93.109.202:7777)
Only noticed it with more than three hives, since Bees 3.0
Angered bees can now target other bees, which forces those bees to attack back, creating a cascade of bee in-fighting which floods chat and could possibly cause slowdown if it was done with large enough hives.
Here's an example 
https://image.ibb.co/gpDipk/Bee_contents.png

**Comment by DamianX** [comment]
#15554

**Comment by DeityLink** [comment]
Not a bug, intended behaviour. Just calm them with some water. If bees come out of the hive angry, that's because the bees' diets are too toxic, isolate the beehives from toxic plants and add beezeez
