### ISSUE TITLE
Stasis Bags

### ISSUE THREAD

**Issue by jakmak6** [d3athrow/vgstation13#15561]
On bay medbay has special body bags called stasis bags which are single use body bags that can keep a body in stasis making it safe to drag around while stopping all bleeding/oxyloss/suffocation (incase a room has no oxygen) but however it doesnt protect from extreme temperatures (room being on fire or 5 degrees kelvin) and doesnt protect from low pressure/high pressure. In exchange for all this the body bag deals a slow and steady uptick of clone and brain damage to the occupant and also being single use.

I thought about porting these UNTIL i realized we have them in our code

Yes the are in vg code and function exactly as mentioned above (with some minor issues ofcourse).

These stasis bags could be given to the paramedic in his locker to make his job more releveant and make body recovery less bloody & could be given to ops/raiders. Ops so they could drag fallen team mates to safety instead of always leaving them for dead and for raiders so they can do the aforementioned and also be able to safety drag hostages through space without said hostage needing a spacesuit+internals.

Currently the cryo bags do function correctly but the clone damage means that a mere 5% clone damge from being in it for a minute would result in several deformed limbs and would also prevent you from being able to move (because clone damage no matter how little is hardcore). I was thinking of removing the clone damage and doubling the brain damage rate.

**Comment by Exxion** [comment]
I don't really see why they need to deal clone OR brain damage, if they're single-use and rare.

**Comment by jakmak6** [comment]
Wells I think the clone/brain damage was added in so you couldn't keep people in permanent stasis since on serbs where they are used nearly every doctor has one on them. I was going to axe the clone damage but I don't know what to do about brain damage. 3 options.

1. Remove brain damage and allow for infinite stable stasis.
2. Keep brain damage as is or buff it
3. Add in 2 separate stasis bags. A normal one which does slow and steady brain damage for normal doctors (maybe?), low material and sci cost in plathe and low price plus no access for cargo order and a adv one that does no brain damage, paramedic/CMO only has access to, mineral (plasma?) And relatively high sci level and high cargo price (if even allowing the adv cryobag to be ordered via cargo).
4. axe brain damage and instead the stasis bag stops working in ~1 minute after shoving someone in it. Advanced versions that can last longer.

Emojiocracy vote: Upvote for option 1, downvote for option 2, laugh for option 3, hooray for option 4. Please reply with any critique

**Comment by Riekland** [comment]
I don't actually see why you'd need to remove any of the damage it does
Clone and brain damage is easy as shit to fix, anyway

**Comment by jakmak6** [comment]
Brain damage is ez and so is clone damage but the way these things apply clone damage incapacitates you massively and removes your ability to walk without treatment with only being in the bag for a short time. It be easier for everyone involved just to remove it and maybe increase brain damage

**Comment by Riekland** [comment]
If the bags don't fucking gimp people then there's no point to not using them
Why would I ever do anything but stick someone in a statis bag when retrieving them instead of using a roller bed?

**Comment by jakmak6** [comment]
Because these I intend to be a paramedic/CMO/powergamer item just like biofoam and to help discourage clonebayallday. That and roller beds are akward as hell to use since they don't fit in bags undeployed and if someone is buckled to one it makes it more of a mess to work around them since you can't occupy the same time as them

**Comment by Riekland** [comment]
So you want them to have basically no downsides?

**Comment by jakmak6** [comment]
I don't want to have them be downside less but clone damage is far too debilitating to keep and I couldn't decide if them being rare + single use would have been plenty or if I should have added brain damage so I left it up for a vote

**Comment by Exxion** [comment]
Rare items can be good

Personally, I'd say axe the damage over time and just make them only work for a limited time
I'd have indicated that on the emoji vote comment but nobody else seems to be using it

**Comment by ValkyrieSkies** [comment]
I'd say just remove all damage seeing as they're one-use items. Just givethe Paramedic a bare minimum of 1 or 2 roundstart and require RnD to print more.

**Comment by jakmak6** [comment]
so this is how i plan to do them currently. vote option 3. 2 seperate bag types. Both single use and both keep the occupant in indefinite stasis unless if they are removed from the bag. The first type aka cheapy bags cause a slow but steady uptick of brain damage and can be made from the protolathe for iron plastic and plasma with low tech levels and can be cargo bought with a paramedic access crate. Paramedic gets a box of 4-5 of low quality ones in his locker. The advanced type can be made only from protolathe and needs iron glass plastic plasma silver and gold (but not much silver and gold). The advanced bags can hold someone in indefinite stable stasis without the brain damage. If you are cuffed/restrained inside a cryobag you need remain still for 30 seconds to break out of the bag (just like resisting out of a welded locker but shorter).
