### ISSUE TITLE
Advanced Security Cameras Download Maps Every Round

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15564]
(WEB REPORT BY: kotmroku REMOTE: 172.93.109.202:7777)
Revision: 949c674551ba85719a6e1019203ad9dbf6c68d04 
Description: Every time I use Advanced Security Cameras, it forces me to re-download the maps of all Z-Levels, which causes lag, and in general makes it tedious to use. It might be caused by constant updates, but it's still bad. Maybe add an refresh button to the console, so I can download the map manually?

I expected smoothless watching over the station.

I got laggy piece of shit.

Use the Advanced Security Cameras console after round reset, I suppose.

**Comment by Exxion** [comment]
Someday maybe the HTMLUI maps won't suck

**Comment by gbasood** [comment]
I'm pretty sure that if the URL of the map(s) were to be static it would cache the image(s), but that'd require hosting external to the Dream Daemon server probably

**Comment by gbasood** [comment]
it is now 2019
we already host a bunch of stuff on the web server insteda of the game server including the rsc file
we can do it for this too, if it still applies

**Comment by west3436** [comment]
Advanced Security Cameras Console was removed in #30607.
