### ISSUE TITLE
AI losing ability to interface with nanoui consoles and core foam dispensers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15576]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)
>Revision 13be40ca3a10ef921cd1dbacea11dba9d5b89d9b

Byond version: 510.1347 

>General description of the issue
AI losing ability to interface with nanoui consoles and core foam dispensers

Relogging and resend resources does not fix it

>What you expected to happen
Be able to turn on the foam dispensers and using the crew monitor, tsci, and others

>What actually happened
Clicking them does nothing

>Steps to reproduce if possible
Get the monitor decryption code. Put it in to the message monitor console then leave it logged in. 

At some point later you'll lose the ability to access nanoui and foams.

**Comment by SonixApache** [comment]
What I've noticed is that you can open them *once* and then it fucks up.
Tends to fuck up if you try to play on your second screen as well, things don't ever pop up at all.

**Comment by nervere** [comment]
No longer an issue, likely fixed in #19879 and possibly #33012.
