### ISSUE TITLE
AI laws not showing up when examined as a ghost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15584]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)
>Revision 4da258c1635a0e2fea9b8628ae4c6ce4fbc53e05

>General description of the issue
Exactly as the name says.

>What you expected to happen
Laws show up when examining or shift-clicking. 

>What actually happened
They don't show up. 

>Steps to reproduce if possible
Examine the AI as a ghost.

**Comment by SonixApache** [comment]
Isn't that a TG feature? Do we even have code for that?

**Comment by ihadtoregisterforthis** [comment]
#15572

**Comment by SonixApache** [comment]
oh wow
Was this fixed by #15585?

**Comment by gbasood** [comment]
jk says yes
