### ISSUE TITLE
You can wrench desk bells into your bag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15606]
(WEB REPORT BY: aerlx87 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
563013ec06c8ede9903256594fc985439178b020 

>General description of the issue
If you take a desk bell and then store it in your bag, you can use a wrench on it and secure or unsecure its bolts. You'll also not be able to remove it.

>What you expected to happen
A desk bell to not somehow have securing bolts that can attach to the inside of a backpack and then be rung

>What actually happened
It can be secured down, and rung as if it was on a desk

>Steps to reproduce if possible
Get bell, put in backpack, use wrench

**Comment by gbasood** [comment]
bellspam 2.0

**Comment by ReindH** [comment]
Advanced clowning.

**Comment by DeityLink** [comment]
on it

**Comment by DeityLink** [comment]
I don't understand, attackby uses	`if(iswrench(W) && isturf(src.loc))` so it shouldn't be wrenchable when not on a turf...

**Comment by Exxion** [comment]
Remember when you could pick them up with a bag when they were already wrenched, and then could never remove them without emptying the bag? Good times

**Comment by Exxion** [comment]
And I can't reproduce this. It doesn't bolt down in the bag. It can, however, still be rung, by clicking it with anything other than an empty hand or screwdriver.

**Comment by Exxion** [comment]
Wait
Oh my FUCKING GOD
The signaler bell's `attackby()` is just a fucking copypaste of the parent
But is missing the `isturf()` check
So this ONLY works for signaler bells
Did whoever made bells not understand inheritance?

**Comment by DeityLink** [comment]
I must have been damn tired at the time I coded that. I'm sure there was a reason at the time.

**Comment by Exxion** [comment]
There's one operative difference I can see, but that was not the best way to do it
