### ISSUE TITLE
Supermatter gives radiation irrespective of the distance

### ISSUE THREAD

**Issue by ReindH** [d3athrow/vgstation13#15608]
#### Description of issue
Throwing anything into the shard gives the person throwing it rad damage NO MATTER THE DISTANCE!
Even hundreds of tiles away, even if you used a mass driver! It seems to behave like cursed dice.

#### Difference between expected and actual behavior

Expected protection from radiation at extreme distances, and the rad from mass driver is simply ridiculous.
Get rads no matter what.

#### Steps to reproduce 

Just throw or mass driver anything into a shard from any distance. Different Z-level not tested but probably the same.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
>even if you used a mass driver

**Comment by jknpj** [comment]
>even if you use a mass driver

what

**Comment by ReindH** [comment]
Tried it on the test server.
Parked the shard about 100 tiles away and shot cable coils at it with the mass driver.
It gave me rads and procced the fluff text. That's why I believe it works like cursed dice.

**Comment by jknpj** [comment]
fucking mass drivers

**Comment by Exxion** [comment]
Thanks, `usr`
