### ISSUE TITLE
New centcomm deathsquad shuttle entrance is in the hallway of medical for some reason and when it was placed on my map it wasnt shift clicked resulting in all of medical lacking power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15605]
(WEB REPORT BY: cptwad REMOTE: 172.93.109.202:7777)
Mostly up so I dont forget to fix it tomorrow

**Comment by DeityLink** [comment]
hold on what? can't make heads or tails of this issue title. What map? Who are you?

When you say entrance you mean the dock right?
