### ISSUE TITLE
Silicon *fart when

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#15616]
#### Description of issue
Sillycons can't *fart and this is a travesty

#### Difference between expected and actual behavior
>shitter waifu sec got captured
>go to fart on >her
>can't fart

#### Steps to reproduce 
Find a downed carbon
say *fart
(Can't fart)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Seven months ago.
It was ill-received.
#13437

**Comment by sonime** [comment]
maybe itll be more well-recieved this time, especially without *scream

**Comment by ihadtoregisterforthis** [comment]
Robots don't have butt cheeks.

**Comment by jknpj** [comment]
don't do it, it creates mustard gas
