### ISSUE TITLE
Mining vaults spawning in Vox Outpost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15617]
(WEB REPORT BY: ch0c0latem00se REMOTE: 172.93.109.202:7777)
>Revision 75297aa617253bc8544a957e680c233c5004602a

>General description of the issue
http://i.imgur.com/o4bK1aw.png
Wizard vault spawned inside the vox outpost, replacing some walls with plasma walls.

>What you expected to happen
vaults to spawn decent distances away from outposts

>What actually happened
see picture

>Steps to reproduce if possible

**Comment by Durgen** [comment]
reported several times
https://github.com/vgstation-coders/vgstation13/issues/14843
https://github.com/vgstation-coders/vgstation13/issues/4776
