### ISSUE TITLE
Meta Club Supply Shuttle's borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15628]
(WEB REPORT BY: tigerbothesh REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

09d9ebc3a92eedcab5b4251b2c4d9bec03af30f4

>General description of the issue

Cargo's Supply Shuttle won't arrive after being called, still shows as docked

>What you expected to happen

Supply Shuttle to dock with station after being called

>What actually happened

Countdown, then nothing showed up. ahelped to fix it

>Steps to reproduce if possible

Place orders on Meta Club and call the Supply Shuttle

**Comment by SysadminJeroen** [comment]
It does this because there is excessive propulsion on the shuttle, which pokes into the maint below. Which causes the shuttle not to depart at all.

**Comment by TheFriggenSawbones** [comment]
#15623
