### ISSUE TITLE
Still floating as if i had fairy wings on even though i took them off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15625]
(WEB REPORT BY: avadanatinde REMOTE: 172.93.109.202:7777)
>Revision d16c0d4b23258dd66ecf358bcce91882f2b77919

>General description of the issue
I put fairy wings from DDR on with equip hotkey, take them off by equiping trader coat, and then place the wings in by backpack and i still float and can navigate in space as if i have the wings on. This only stops when i take the wings out of my backpack again.

>What you expected to happen
for me to stop floating when i stop wearing the wings.

>What actually happened
i can navigate in space without a jetpack now

>Steps to reproduce if possible
1 win DDR
2 equip fairy wings
3 equip trader coat
4 put wings in your bag
5 explore space for forever for free without a jetpack now

**Comment by jknpj** [comment]
IF QUICKSWITCH ISN'T CALLING DROPPED() I'M GOING TO RIOT

edit: IT ISN'T
edit edit: It's my fault.
