### ISSUE TITLE
Wizards don't summon magic for themselves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15639]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)ef8d0b5c9f957d2e7a7596677d590a9ce07a0414 

>General description of the issue
Summon magic doesn't summon for the wizards like summon guns does

>What you expected to happen
Magic hour

>What actually happened
Wasted spellpoints

>Steps to reproduce if possible
Summon magic as wizard

**Comment by N3X15** [comment]
Well no shit

**Comment by SonixApache** [comment]
working as intended

**Comment by Exxion** [comment]
1. [Discussion] in case anyone who hasn't shown up yet wants to change it also. (Let's just give it a couple days or so)
2. Petition to change [Not A Bug] to [Working As Intended]

**Comment by AI-Is-Rogue** [comment]
At first I figured it was unintended and caused by #12120 and #12117 having some sort of mix-up.
But it seems I missed this [commit.](https://github.com/vgstation-coders/vgstation13/pull/12117/commits/7c794db04b91bcda168dde04bae41449236d692d ) Whoops.

**Comment by Exxion** [comment]
Wow, that is extra intentional.
That code also slightly disgusts me.
