### ISSUE TITLE
applying thermite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15630]
(WEB REPORT BY: avadanatinde REMOTE: 172.93.109.202:7777)
>Revision ef8d0b5c9f957d2e7a7596677d590a9ce07a0414 

>General description of the issue
cannot apply thermite to a wall from a drink bottle or thermos

>What you expected to happen
the thermite to be applied to the wall

>What actually happened
all that happened is i pushed the wall and no thermite was applied
>Steps to reproduce if possible
1 get thermos or alcohol bottle
2 put thermite inside
3 try applying to wall
4 die because you can't thermite the wall and the AI is a bad man

**Comment by nervere** [comment]
This is because these reagent containers are a child type of `food/drinks/...`.
Not a bug as this has always been the intended behavior, but it would be a cool feature.
