### ISSUE TITLE
Sasha InHand sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15634]
(WEB REPORT BY: electroblueguy REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
ef8d0b5c9f957d2e7a7596677d590a9ce07a0414 

>General description of the issue
when held in hand, sasha takes the sprite of Ian

>What you expected to happen
There should be the inHand sasha sprite

>What actually happened
it seems like i'm holding Ian

>Steps to reproduce if possible
grab sasha

**Comment by jknpj** [comment]
And all cats are runtime when you hold them. Not really a bug but a WYSI

**Comment by robintime** [comment]
duplicate of #28727
