### ISSUE TITLE
Buying from vendors break IE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15631]
(WEB REPORT BY: dopaper REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
 ef8d0b5c9f957d2e7a7596677d590a9ce07a0414 

>General description of the issue

>What you expected to happen
I wanted a coffee/anything else from vending machine

>What actually happened
when you purchase it it displays a this page could not be displayed error.

>Steps to reproduce if possible
buy from a vending machine

**Comment by DamianX** [comment]
Still happens sometimes but I have no idea why. Why would it happen specifically with vending machines?

**Comment by DamianX** [comment]
Still not a clue, by the way.
