### ISSUE TITLE
Janibelt says it's full but it's not

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15632]
(WEB REPORT BY: chugmonkey REMOTE: 172.93.109.202:7777)
ef8d0b5c9f957d2e7a7596677d590a9ce07a0414 

>Janibelt says its full, yet its not full and has 1 slot open

>I expected to put a wet floor sign into my janibelt for safe keeping

>It says the janibelt is full but has 1 slot still open

>Fill up the janibelt, then take 1 item out and attempt to put another item in.

**Comment by Kurfursten** [comment]
List the exact items inside, it might be reaching its max total w_class
