### ISSUE TITLE
Canisters rupturing while hooked to connectors can break the connector

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15642]
(WEB REPORT BY: panthid REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
ef8d0b5c9f957d2e7a7596677d590a9ce07a0414

>General description of the issue
Canisters rupturing while hooked to connectors can break the connector. This makes the connector unusable even if unwrenched and wrenched again.

>What you expected to happen
Connector to reset to unconnected state when the canister ruptures.

>What actually happened
Connector gets stuck and thinks there is a canister still connected and so can't accept a new canister.

>Steps to reproduce if possible
Rupture a canister while it is hooked to a connector. In this case it was an oxygen canister which had been connected to the cryo in box which had the vacuum pump left on for a while. The canister was ruptured with a cyborg circular saw.

**Comment by FudgePucker** [comment]
Could be worse, wasn't there a bug where if a canister connected to a connector when ruptured it would constantly dump all the gas in the pipe network out, acting as a super unpowered injector? Or did it just crash the server? I can't remember.
