### ISSUE TITLE
Medical Cyborg Flash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15640]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
>medical cyborg flash burns out if used too much, instead of just running out

>flash runs out instead of breaking

>flash burnt out

>spam the medical cyborg flash

**Comment by jknpj** [comment]
just recharge my man

**Comment by SonixApache** [comment]
[not a bug]

**Comment by Shadowmech88** [comment]
If this isn't a bug, can someone clarify why?
Does using a cyborg charger repair a burnt-out flash? Is the flash not actually burning out?

**Comment by MadmanMartian** [comment]
It's to stop overuse and abuse of the flash. Can't just sit there as a medborg flashing the retina out of the clown, so your flash will burn out and require you to go away from said bullied clown to fix the flash via recharge

**Comment by Pathid** [comment]
> Does using a cyborg charger repair a burnt-out flash?

Yes it does indeed.
> Is the flash not actually burning out?

This also happens. It has to recharge itself if you use it over 5 times within a minute. Tricky part is the recharger station recharges the flash instantly, but _only_ if it's broken first, which has only a 10% chance to happen during that.
