### ISSUE TITLE
Cyborg Default Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15647]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
so this is how it goes: if you become a module and then get reset, you can become another module again and press cancel on the sprite to become, and it'll glitch you into becoming the default/standard borg sprite, meaning whenever used with the combat borg and its sprite changing modules like the shield and mobility module, it causes them to go invisible because it does not have a sprite for the default borg.
if this cannot be fixed by perventing it all together, it could be fixed by adding dummy sprites to the default borg sprite to pervent the invisbility.

**Comment by jknpj** [comment]
Amazing oversight.
