### ISSUE TITLE
Putting a dead facehugger on your mask slot makes you immune to facehugging

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15649]
(WEB REPORT BY: sailol REMOTE: 172.93.109.202:7777)
de3bc7604a921b924c9e2297541ab4c9772d7c11

>General description of the issue
A dead facehugger on your face makes you literally immune to facehugging, the facehugger won't "bounce off" it simply won't connect.

>What you expected to happen
For the facehugger to connect with the face.

>What actually happened
The facehugger didn't connect

>Steps to reproduce if possible
.-Put a deadfacehugger in your mask slot
.-stay near a facehugger.

**Comment by Intigracy** [comment]
New meta

**Comment by gbasood** [comment]
Yeah actually I'm pretty sure this was always the case
I'm sure you can even find an issue about this pre-existing
