### ISSUE TITLE
Cyborg Default Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15648]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
>you go cyborg, turn into any module, have a reset module used on you, become another module and use cancel instead of becoming a sprite, it will force you into becoming the default cyborg sprite

>not to become a default cyborg sprite

>became the default cyborg sprite

>become cyborg >become module >reset to default module >become module >press cancel

**Comment by Exxion** [comment]
Why'd you report it again, except worse?
#15647
