### ISSUE TITLE
Lazarus Capsuled Monsters attacking things from inside capsule

### ISSUE THREAD

**Issue by CornColonel** [d3athrow/vgstation13#1566]
When you revive a monster on the asteroid and put it in a lazarus capsule they will attack exosuits and sometimes people with their ranged attacks, ie goliaths knocking over shit and breaking windows with tentacles, basilisks freezing people.

**Comment by d3athrow** [comment]
this should be fixed.

**Comment by clusterfack** [comment]
It is fixed, you can close this
