### ISSUE TITLE
Can't Save Characters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15679]
(WEB REPORT BY: monkeymolester69 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
7c88ed2c638fc6c2ccbbb483143bd31b06de7707

>General description of the issue
The game "allows" me to save a character for that round, but after the round restarts my character is lost and I have to recreate it again.

>What you expected to happen
My character(s) to save between rounds.

>What actually happened
Can only modify one character, character is then wiped as the round restarts.  Saving the slot, saving the setup, and updating special role preferences does not seem to fix the problem.

>Steps to reproduce if possible
Join and try to create a character.

**Comment by SonixApache** [comment]
#15669 ?

**Comment by SGuivenne** [comment]
is identical to #15684

**Comment by DamianX** [comment]
Duplicate.
