### ISSUE TITLE
Character Slot wont save

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15684]
(WEB REPORT BY: theframptonator REMOTE: 172.93.109.202:7777)
>General description of the issue

Cannot save my character, when I close the game and reopen I have to remake my character again. The game says that my Char slot is saved but I cannot load it.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by SonixApache** [comment]
#15669 ?

**Comment by SGuivenne** [comment]
Looks like this was patched out and the patch referencing it didn't properly close these bugs

**Comment by west3436** [comment]
Not sure why this was reopened.
