### ISSUE TITLE
MMi Blindness

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15689]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
so whenever you get debrained, you're blind while debrained, and this appears to not update whenever transfered into an MMi, possible fixes as far as i know would be to either update the MMi to not be blind, or make it so that being debrained does not make you blind in the first place

**Comment by Shadowmech88** [comment]
Duplicate of #14690.
