### ISSUE TITLE
Table Build Glitch

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15687]
(WEB REPORT BY: hoborobo REMOTE: 172.93.109.202:7777)
>Revision
dea69d34b455da695e91a2059a68e8c7340efb9f

>General description of the issue
Building a table on top of another table merges the two carryable tables.

>What you expected to happen
Two different tables to pop out when deconstructed

>What actually happened
One table popped out when deconstructed

>Steps to reproduce if possible
Build a table atop another table

**Comment by Exxion** [comment]
Yeah, rather than not letting you try to build a second table, it just deletes the first one (if I remember correctly) when you do.
