### ISSUE TITLE
You can't actually build a taxi spacepod

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15682]
(WEB REPORT BY: gutlesscoward REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
eccd8396b3232b1871b5acef4d92ad83371ce94e 

>General description of the issue
if you try to build a taxi spacepod (doing the entire spacepod building process, but using taxi spacepod armor instead of civvie) a civilian spacepod comes out instead.

>What you expected to happen
get a taxi spacepod

>What actually happened
get a civilian spacepod

>Steps to reproduce if possible
1.build a spacepod. when at  the step where you put in civvie pod armor, put in taxi pod armor.

**Comment by MadmanMartian** [comment]
Yaay construction datums looking for istype
