### ISSUE TITLE
Box Station AME Room Atmos Barrier

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15691]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
http://i.imgur.com/ROZmgjB.png
hmm, not sure about this one, might be an area inside of an area causing ZAS to freak out and treat that area as a different seperated area

**Comment by Exxion** [comment]
Yeah, that rectangle of turfs is varedited to `blocks_air = 1` for presumably some reason

**Comment by Kurfursten** [comment]
@Exxion not an issue as of #19268
