### ISSUE TITLE
Singularity causes MoMMi to become semi-dead.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15706]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
so as a mommi with the repair bot sprite, fell into the singularity whilst fire extinguishing away from it, ended up being WEIRDLY DELETED, where the non-glowing eyes sprite was removed and the eyes were left glowing, still able to speak and use items until emped, dissappeared from the singularity's gravitational pull, it was not capable of moving at any point after destruction, i cannot even imagine how this happened, and i don't even know if it's possible to replicate.

**Comment by jknpj** [comment]
NEVERMIND THIS MUST BE THE SAME ISSUE THAT BORGS HAD

**Comment by Exxion** [comment]
What issue?

**Comment by MadmanMartian** [comment]
He got deleted, but his overlays did not. The EMP got him to be completely deleted

**Comment by Exxion** [comment]
Ah

**Comment by Exxion** [comment]
Wait what

**Comment by jknpj** [comment]
@Exxion #15614 borgs had the same issue with updateicon runtiming, making the singulo stop processing them halfway

Just have to check the runtime log to make sure what's runtiming for them

**Comment by Intigracy** [comment]
Fixed in #15614
