### ISSUE TITLE
can't examine my sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15708]
(WEB REPORT BY: tornader REMOTE: 172.93.109.202:7777)
>Revision
a133fd47f06e39703d8edb2ebfa5cc7bbe9c76ce 

>General description of the issue
You can't examine my diona sprite for some reason, I think it might be because of the peg legs I added to make myself slower

>What you expected to happen
to be able to examine it, I think no one else can examine it either

>What actually happened
..

>Steps to reproduce if possible
add peg legs to you diona, hair and sight problems. not sure if it will work but it used to be fine before that

**Comment by SonixApache** [comment]
I had this issue randomly as well for a short while. Disappeared over the course of a round. Wasn't a diona or anyone with peg legs, far as I can remember. Just some random guy I couldn't examine.

I figure it's related to flavor text.

**Comment by SonixApache** [comment]
Happened again a bit ago. Asked zak1946 to do a VV dump at the time.

**Comment by DamianX** [comment]
Tested as a diona with 4 peg limbs and could examine myself just fine.
