### ISSUE TITLE
Supermatter Irradiating the entire Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15707]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
so if you throw a object a supermatter shard and when it hits the supermatter shard, if it's off screen the entire station gets irradiated, so throw a object a supermatter shard a couple tiles away from it being visible like if you were in space, and you'd be irradiating the entire station, which could be used to quickly eradicate everyone

**Comment by MiniMeatwad** [comment]
so if you throw a object at a supermatter shard, when it hits the supermatter shard from an object thrown from further than view range 7, everyone on the same z-level gets irradiated.*
whoops i fucked up bad on that

**Comment by MadmanMartian** [comment]
Whoo, a twofer!
