### ISSUE TITLE
You can't make pod armor in the spacepod fabricator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15718]
(WEB REPORT BY: gutlesscoward REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
c841e9ee5826d97996b9d8535343a5e48c2b468c

>General description of the issue
You can't make pod armor in the spacepod fabricator; going to the 'pod armor' section just shows "no  parts in memory".

>What you expected to happen
when on the 'pod armor' section in the spacepod fabricator, it should show types of pod armor to create; the civilian pod armor is a default that's always on there. taxi pod armor shows up after plasma gets researched to 3 by RnD.

>What actually happened
the list was empty, despite research being maxed by RnD.

>Steps to reproduce if possible
1. go to spacepod fab
2. select 'pod armor'  on the menu
3. look at the "no parts in memory" message
4. get sad thinking about all the taxi pods you will be unable to build

**Comment by MadmanMartian** [comment]
you're kidding.

How the fuck was I able to make them then?

**Comment by MadmanMartian** [comment]
Oh, they require plasmatech 3, which is largely ignored in most of the speedrun strats of RnD

**Comment by MadmanMartian** [comment]
Disregard that, I consume dong. Fix up momentarily
