### ISSUE TITLE
Misplaces/nonfunctional vent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15715]
(WEB REPORT BY: higgsbonbon REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
d2d7c11e40553dea372122a56c9c6fff4c7f011c 

>General description of the issue
An air vent in the Xenobiology Specimen Cage 1 is not connected to the appropriate console, rendering the system inoperable.

**Comment by MadmanMartian** [comment]
Map is metaclub apparently

**Comment by Probe1** [comment]
Cursed code.  Also copy paste mapping.  Highly cursed.
