### ISSUE TITLE
You can't make pod armor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15717]
(WEB REPORT BY: gutlesscoward REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
c841e9ee5826d97996b9d8535343a5e48c2b468c

>General description of the issue
Y

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Gutlesscoward** [comment]
Accidentally hit enter while typing, submitted early, pls delet this

**Comment by DamianX** [comment]
>in-game reports
