### ISSUE TITLE
The chess board on the holodeck is wrong.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15711]
The chessboard on the holodeck has the king and queen in the wrong positions.  The station queen being on a black space at the bottom holds the implication that the station pieces are the black pieces at the bottom and the cult pieces are the white pieces at the top.  While it could technically pass for correct, it is aesthetically displeasing to have reversed positioning with the colors and an inverted color scheme.

![y64dy5r](https://user-images.githubusercontent.com/20872793/29263965-c6408032-80a0-11e7-988f-8f65d9641741.png)

**Comment by Dacendeth** [comment]
I cant believe i never noticed this, Queen on her own color!

**Comment by ghost** [comment]
Nerd

**Comment by Kurfursten** [comment]
We've known for five months!

https://github.com/vgstation-coders/vgstation13/issues/14366#issuecomment-286967791

**Comment by Lokiamis** [comment]
I fixed this months ago and never bothered to PR it. Honk. Also added the superior strategy game, checkers.

![untitled](https://user-images.githubusercontent.com/25004372/29296631-ed504dec-8131-11e7-9651-c94322f4842c.png)
![2](https://user-images.githubusercontent.com/25004372/29296667-1a5856fe-8132-11e7-8f59-5b09498d8288.png)

**Comment by ghost** [comment]
gibs me that.

**Comment by Lokiamis** [comment]
I'll do it tomorrow if I can remember how
