### ISSUE TITLE
Verbs disappearing from changling tab

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15710]
(WEB REPORT BY: headless1 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

195309606b8fc3da98ffeccc95209317ec1f3dd8
>General description of the issue
All of my changling verbs disappeared, save EvolutionMenu.

>What you expected to happen
To be able to access the changling abilities I purchased
>What actually happened
After using them for a bit they suddenly vanished without warning, making playing the antag role much more difficult if not impossible.

>Steps to reproduce if possible
I wouldn't really know. Suck somebody and then try to purchase a power, and see if the verbs stay, I guess?

**Comment by nervere** [comment]
Changeling reworked a lot since this was made, doesn't seem to happen anymore.
