### ISSUE TITLE
New Engineering Room for Box

### ISSUE THREAD

**Issue by Reviire** [d3athrow/vgstation13#15720]
Cptwad told me to make this an issue on Git to get a discussion about it, it's just a suggestion. Don't hate, he told me to do it.

So, here's the idea. Add a new room to engineering, just an empty 10x10 or so room with nothing but an APC and an Air Alarm, so autistic projects are easier to start, without needing to pull apart rooms or build a new one entirely. They're fun to do, but spending a heap of time preparing to even start is really annoying.

**Comment by ghost** [comment]
Honestly, the entire dept needs an overhaul. Ideally around a TEG core with straight valved H/E pipes for adjustability and a duplicate so at least 3 engineers can do shit. This way you can plug in an SME shard, R-UST donut generator, or just use it as a plain burn chamber. Glass the size where you want it and secure gyros/emitters. Have the AME/Sing bays off to the side. Crunch the core atmospherics room functions into a teensy mini-mos that's largely skeleton'd around layered taps, mixers, and the other bits often added and maybe add an inter-departmental chute system for moving large amounts of crates around with having to put up with shitcurity and the hand tele. Then there can just be an RnD room with pen taps , some space turf real estate, and a space chiller rack. I think it's like 15x15. A R-UST core at 9x9 is about as big as you're gonna get and you can just layer H/E if you want a tough TEG burn chamber anyway. at 11x11 gives you a tile of walking room, 15x15 lets you put various engine parts, pumps, and canisters along the walls

The chute system and more destination tagged bins would help cope with the dongmos expanding.
