### ISSUE TITLE
"Propulsion" object is not rotatable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15731]
(WEB REPORT BY: headless1 REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Propulsion devices can't be rotated to be constructed properly, meaning that should one need to do construction with them it's much more difficult than it needs to be.

>What you expected to happen
"Rotate Object" functionality.

>What actually happened
It has none.

>Steps to reproduce if possible
Unwrench a propulsion from the floor and watch in amazment as it can't be rotated.

**Comment by unid15** [comment]
The propulsion engines from that round were actually resprited AI cores, as that allowed wrenching/unwrenching them. Although this issue does raise a valid point - there are no constructable shuttle engines in the code, and the already existing ones can't be moved around or rotated.

**Comment by Exxion** [comment]
I think there are the beginnings of constructable ships buried deep within some folder labeled "unused"
But they probably don't use the same engines anyway

**Comment by Shadowmech88** [comment]
Closing this due to the issue creator being mistaken.
If constructable shuttle engines are desired, a separate feature request can be made.
