### ISSUE TITLE
Lack of ATM's on Packed Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15733]
(WEB REPORT BY: turbogay REMOTE: 172.93.109.202:7777)
Revision: eacb22abdf1de3b8533f6554a53d319308692cb6 

General description of the issue:

General lack of ATM's across the station, couldn't find in the majority of places I looked.

What you expected to happen:
Expected there to be some more ATM's on the station.

**Comment by Kurfursten** [comment]
There are only three ATMs on packed station, two are on the Vox trade shuttle and one is at the bar front door.

I recommend adding one to the cargo line and one to the dorms. Maybe the top left corner of the bridge where there's an open spot, too.

**Comment by SonixApache** [comment]
THE OBVIOUS SOLUTION WOULD BE TO MAKE ATMS CONSTRUCTABLE AGAIN
