### ISSUE TITLE
Chair + Sleeping = Wierd Things

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15737]
(WEB REPORT BY: kharkov72 REMOTE: 172.93.109.202:7777)
>Revision eacb22abdf1de3b8533f6554a53d319308692cb6 

>General description of the issue
I slept (SLEEP COMMAND) for foot surgery, and was dumped in a medbay lobby chair while I was in the process of waking up. Not only did I never actually wake up, the sleeping black border eventually went away.

>What you expected to happen
Well, I expected to eventually wake up. I also expected the sleeping border to remain while I was, well, asleep.

>What actually happened
Completely unable to wake up, border eventually went away. Also, able to fully examine nearby people, and to see text box sprites, but cannot hear.

>Steps to reproduce if possible
Sleep self, have someone else buckle you into a chair, observe. Possibly, induce foot bone repair surgery (Possibly specifically the left).

**Comment by strawberrytan** [comment]
Sleep command lasts basically forever without any influence from the outside, you can faint instead for a shorter duration of sleeping or hope the doctor wakes you up

**Comment by ghost** [comment]
This lasts until someone unbuckles you from the chair and shakes you up, you instantly wake up properly. Probably related to resting.

**Comment by Intigracy** [comment]
Going to assume this was fixed by https://github.com/vgstation-coders/vgstation13/pull/20736, feel free to re-open if it wasn't.
