### ISSUE TITLE
Some Guns Work Through Cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15740]
(WEB REPORT BY: n3x15 REMOTE: 172.93.109.202:7777)
```
OOC: WentAFK: Reminder that gravity well can be sent through cameras and can cause a singularity when fired at a singulo gen
OOC: SangriaMonkey2: >sent through cameras
OOC: SangriaMonkey2: that's some 7d backgamon right there
OOC: Vahalian: i never woulda guessed thats how that worked
OOC: MaloKingi: Is it a Bug or Unintended Feature?
OOC: Vahalian: i mean can other guns be shot through cameras?
OOC: WentAFK: Bluespace tunneler works through cameras
OOC: WentAFK: And presumably x-ray lasers
OOC: Vahalian: thats really cool actually
OOC: N3X15: Did you make a bug report
[Never responded]
```

**Comment by Shadowmech88** [comment]
The subspace tunneler working through cameras has been deemed a feature.

The other stuff is bugs, though.

**Comment by SonixApache** [comment]
Something I asked Yred to test recently;
Chemsprayers fire all the way to where you click. Can chemsprayers have infinite range if used through cameras?

**Comment by ghost** [comment]
@SonixApache Tested locally, you only get ~1-2 extra tiles past the edge of LoS but it's RNG. Held true when using change-view-range as well

**Comment by Kurfursten** [comment]
Tested xray and gravity well and like SJ says, you can't really shoot it anywhere you wouldn't be able to see anyway. At most it's a binoculars effect, not through walls.

Seems not a bug/safe to close @Exxion
