### ISSUE TITLE
Item teleportation/duplication via custom vending machine

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15776]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
# Revision
76455c7b9ef3c5accb3ab026a38682238247b480

# Description
Loading an item into an empty recharge pack, removing it, then loading the vending machine with the pack loads a duplicate item into the vending machine, which can be bought, creating a duplicate until it is picked up, at which point the original will teleport to the person who picked it up
# Steps to Reproduce
see above
# What you Expected
nothing loaded
# What Actually Happened
phatnom produce

**Comment by MadmanMartian** [comment]
removing it doesn't remove the reference, nice
