### ISSUE TITLE
Spiderbots can pick up anchored desk bells

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#15778]
#### Difference between expected and actual behavior

Expected: Sanity
Got: Anchored bell can keeps anchored after you drop it

#### Steps to reproduce 

Be spiderbot, go to any desk with a bell, use your pick up verb

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
>bell desks

**Comment by jknpj** [comment]
desk bells, whatever
