### ISSUE TITLE
IEDs and Evidence Bags.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15780]
(WEB REPORT BY: thewhargoul REMOTE: 172.93.109.202:7777)
# Revision
a4af1639dfb15df33ccbe090616b464f4863be42

# Description
Whenever you try to put an IED into an evidence bag, the evidence bag is put into the IED as shrapnel and you get the text for putting the IED in the bag as well. Whenever you remove the shranel the Evidence will have a sprite as if it has the IED Inside of it, as well as have the description as if it did.
# Steps to Reproduce
Put an IED into an evidence bag
# What you Expected
To put the IED in the bag
# What Actually Happened
The Bag was placed in the IED and the IED was placed into the bag simutaneously.

**Comment by DamianX** [comment]
Could we have evidence bags use `preattack` as a fix?

**Comment by The-Whargoul** [comment]
Update:
was able to place IED in Evidence bag after emptying the shrapnel from the IED.

**Comment by Riekland** [comment]
I distinctly remember this being an issue before and people saying it was fixed
