### ISSUE TITLE
Custom vending machines not vending

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15789]
(WEB REPORT BY: lisandrabrave REMOTE: 172.93.109.202:7777)
# Revision
9a84a48686aa944be9bc0c565b27c94f980cb97d

# Description
Items in custom vending machines are unable to be purchased.
# Steps to Reproduce
1. Make custom vending machine
1.5. (possibly related) unwrench it from the plating and move it around.
2. Load your stuff in
2.5 (possibly related) unwrench it and put it in its final resting place
3. Attempt to vend
# What you Expected
People to be able to buy my dodgy goods from the machine.
# What Actually Happened
Nothing is able to be purchased, and capitalism fails on the station.

**Comment by Kurfursten** [comment]
Report again if you can reproduce
