### ISSUE TITLE
AI cant track exosuits with camera

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15792]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
# Revision
9a84a48686aa944be9bc0c565b27c94f980cb97d

# Description
AI can't track mechs and exosuits on camera, nor the people in them. Probably a feature, but it would be a great QoL upgrade.
# Steps to Reproduce
Double click on mech or search in the tracking window.
# What you Expected
Hoped to be able to track mechs
# What Actually Happened
Impossible to automatically track them, finding them a pain in the arse.

**Comment by SonixApache** [comment]
AI OPEN THIS DOOR

**Comment by ReindH** [comment]
AI WHERE IS THE PHAZON KILLING THE CREW?!

**Comment by ghost** [comment]
\>name my mech "unknown"

\>;AI TRACK THE UNKNOWN
