### ISSUE TITLE
Treadmill generators

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15808]
(WEB REPORT BY: falcon343 REMOTE: 172.93.109.202:7777)
# Revision
a562f556644694e3e03636bb1483e37fb1141d3f

# Description
Treadmill generators don't work when you try to use them.

# Steps to Reproduce
Make a treadmill generator, put it down, try to run on it. It won' do the thing. Wow!

# What you Expected
I expected to have it do the thing and make power!

# What Actually Happened
Can't run on it, no power. Sad!

**Comment by MadmanMartian** [comment]
Needs a wire under it

**Comment by jknpj** [comment]
Actually i'm glad someone reported it i forgot to do it myself. They are indeed broken, even with a knot under they just don't work

**Comment by DamianX** [comment]
git bisect points to 51df013603bef38819234063a90f4a944215c65b

**Comment by Kurfursten** [comment]
@DamianX That only changed comments, no effect on operations

As best I can tell, it was caused by a change in how Uncross is used. It's been so long since I've looked at these move handling procs and they've changed a bit since then, but I have a solution that should work.
