### ISSUE TITLE
Circuit imprinter printing a full confectionator

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#15807]
#### Description of issue

The circuit imprinter prints a full confectionator instead of a board

#### Difference between expected and actual behavior

Expected a board, got a real confectionator filled with 300u sugar

#### Steps to reproduce 

1. Make a confectionator board with the circuit imprinter
2. Get a full working confectionator filled with sugar

#### Server revision

Game: a562f556644694e3e03636bb1483e37fb1141d3f 
Patches: cce7d45130404579663c09010c5d0aebe829e6d6

**Comment by SonixApache** [comment]
Technology is amazing.
