### ISSUE TITLE
AI can find out what someone's actual identity is when they are using a voice changer

### ISSUE THREAD

**Issue by small-boss** [d3athrow/vgstation13#15812]
#### Description of issue
A AI can figure out the real name of someone using a voice changer by following their speech after they take off their mask. So if Greytide McAntag pretends to be Greytide McShitter and then takes off his voice changer, the AI can click on the radio message supposedly said by Greytide McShitter, just to see that the camera is trying to track Greytide McAntag.

#### Steps to reproduce 
1. Have one player use a voice changer and hide from a camera. Make him say something on the radio with a fake identity. Take off the mask/Put on your normal ID
2. Have another player follow the fake identity by clicking on the name next to the radio message.
See how the camera now tracks the real identity, and not the fake one which talked on the radio.

#### Server revision

ee943827ee690c07bed6d2fdb6abe6acf17d44dc

**Comment by Allspice** [comment]
#11010 related
