### ISSUE TITLE
Can't deconstruct Starscreen shield generator or capacitor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15813]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)
# Revision
ee943827ee690c07bed6d2fdb6abe6acf17d44dc

# Description
Can't deconstruct Starscreen shield generator or capacitor

# Steps to Reproduce
Screwdriver doesn't open the maint panel
Gives "Starscreen shield generator must be anchored first!" when unsecured
# What you Expected
Screwdriver opening the maint panel so you could crowbar the circ out

# What Actually Happened
No message at all

**Comment by SonixApache** [comment]
Starscreens are oldcode as fuck with regards to deconstruction and power. Think the work they need is outta my league, sadly.
