### ISSUE TITLE
Pacid/Phenol Vines No Longer Eat Flooring / Wall Exteriors 

### ISSUE THREAD

**Issue by Anglosphere** [d3athrow/vgstation13#15827]
#### Description of issue
Kudzu (or any vined plant for that matter) is no longer able to eat floors/walls.  This is likely due to the reagent change in Death Nettles from Pacid to Phenol.  I think Phenol is a child of pacid, so Idk why it doesnt work. 

#### Difference between expected and actual behavior
Phenol Vines destroying floor tiles, and exteriors of walls. 

#### Steps to reproduce 
Splice 100+ potency grass onto Death Nettles, Splice vines onto death nettles.
Plant Nettles
Wait for vines. 

#### Specific information for locating

	if(seed.chems && !isnull(seed.chems[PACID]))
			seed.chems[PACID] = null // Eating through the hull will make these plants completely inviable, albeit very dangerous.
			seed.chems -= null // Setting to null does not actually remove the entry, which is weird.

https://github.com/vgstation-coders/vgstation13/blob/246b9261f5df95639af1ec5c029a8e2fd9ed8136/code/modules/hydroponics/seed_controller.dm

#### Length of time in which bug has been known to occur
Probably since Phenol was added as the reagent for Death Nettles. 

#### Issue bingo
![itaintworknomo](https://user-images.githubusercontent.com/20270723/29747485-62dc0b68-8ab1-11e7-8303-bc48d3ba3309.png)

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
@Shadowmech88
