### ISSUE TITLE
Gravity guns working with cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15834]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
24c1659563d97eacb39a69301d1b3b63307addb9

# Description
You can use cameras to shoot gravity guns to any part of the station.

# Steps to Reproduce
Get a camera console, gravity gun and shoot.

# What you Expected
probably a projectile hitting a wall or something

# What Actually Happened
The projectile will slowly move to wherever you clicked ignoring any walls in its wall then create the gravity well precisely where you clicked

**Comment by Shadowmech88** [comment]
Duplicate of #15740
