### ISSUE TITLE
Happy mask shade's "revert form" ability really should have a tooltip describing what it really does.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#15836]
If you get shaded and you click this icon that shows up into your hud with no explanation you quickly return to your body and become unshadeable.
While this ends up being a one-time issue if the user actually wants to be a shade it can be a huge bummer.

**Comment by DeityLink** [comment]
Happiest Mask shades are a form of transmogrification, the exact same that other roid masks are using, and it's using the same spell for all. This probably won't be fixed.
