### ISSUE TITLE
Allow traders to be targeted by antags

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#15835]
People have been requesting this for more than a year, but as far as I can tell no one has opened an issue about it. Traders being unable to be targeted by antags is a relic from a time before the trade shuttle existed and should be reverted.

https://github.com/vgstation-coders/vgstation13/pull/9514

Now almost all traders eventually make their way to station, besides those who die doing something stupid in space. Restricting them from being targets no longer make sense.

**Comment by Dusk-a** [comment]
I will defend many things for traders but I agree that never being an antag target is kind of dumb. No reason they can be antag yet can't be a target themselves ever.

**Comment by Kammerjunk** [comment]
Good for discussion if people keep bringing this up
Remember than they were made immune because of complaints from antags, not complaints from traders. They were angery because there wasn't really a good chance for, say, the chef to get his greentext if they're on an entirely different station

**Comment by Orangerush** [comment]
@Kammerjunk any way for only certain jobs that could reasonably go out and get them get them as a target or is that impossible currently?

**Comment by Kammerjunk** [comment]
Ahahaha

**Comment by Kammerjunk** [comment]
Well, I mean, maybe? I wouldn't mess with it because I didn't like what I was looking at the last time I was looking at antag stuff, but maybe?
It sounds like it'd be really snowflakey code though

**Comment by Orangerush** [comment]
![i anger](https://user-images.githubusercontent.com/19225676/29801422-82fd2462-8c3d-11e7-9e4a-03a37c76a7db.jpg)

So what you're saying is ANTAG DATUMS?

**Comment by Durgen** [comment]
@Orangerush Traders don't need a restriction, they are far easier to kill than for example Miners or Xenoarchs.
just do this
'hey secborg go kill that bird in arrivals he stole 1 credit from me'

**Comment by Kammerjunk** [comment]
If they go to the station at the same time you look for them, certainly

**Comment by Dusk-a** [comment]
Its not too difficult for a borg to get on their outposts either provided they know where it is. They can even use the trade ship's console to move it

**Comment by Kurfursten** [comment]
This restriction was made at a time when Traders could not access PDAs. Today most Traders will save up the 100 credits for a PDA, meaning you can pinpoint them. Time for trader targets again. 👍 

Besides, this change will make some of the most obnoxious voices be quiet for a while.

**Comment by Kammerjunk** [comment]
Yeah, until the traitors start complaining and asking for the thing they don't have yet again ¯\\_(ツ)_/¯

**Comment by SonixApache** [comment]
>needing objectives to kill shitbirds

**Comment by ghost** [comment]
An antag is more than their greentext. If you want to antagonize the shit out of traders, go fuck them up. You don't need to send newfags off to accomplish nothing in regards to the action in the round because they're too dumb to look beyond their obj's when the guys who want to fuck up traders can just use their antag tickie to go KFC the place already.

**Comment by Kammerjunk** [comment]
I had thought that'd be brought up at some point, but it works both ways.
* Objectives don't matter, so you don't need an assassinate objective to kill traders.
* Objectives don't matter, so there's no reason to prevent traders from being the target of assassinate.

**Comment by ghost** [comment]
For the people who have a hardon for greentext instead of not giving a shit it marginally reduces the chance of at least something happening on the station before they sit in a locker for the shuttle. Yes, xenoarch/miners exist and no, adding more to that off-station list isn't helping.

**Comment by Kurfursten** [comment]
antagonistes no longer target
