### ISSUE TITLE
Tomahawks don't work on biomass

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15859]
(WEB REPORT BY: panthid REMOTE: 172.93.109.202:7777)
# Revision
089fa1318a411f50e6db33a58c0eb620d7e4eea7

# Description
Tomahawks don't work on biomass (space barf) despite being a child of hatchets. There's probably more sharp weapons that it doesn't check for too.
# Steps to Reproduce
Try to clear biomass with a tomahawk.
# What you Expected
Tomahawks to clear biomass.
# What Actually Happened
My tomahawk didn't clear biomass.

**Comment by Shadowmech88** [comment]
It's because biomass `attackby()` code uses discrete type checking rather than `istype()`, meaning the child types of the things that work on it, don't work on it.

**Comment by Kurfursten** [comment]
Should use is_type_in_list and define a constant list

**Comment by Exxion** [comment]
Or just
Sharpness

**Comment by Kurfursten** [comment]
Maybe some combo of sharpness and force, otherwise you're cutting biomass with a pen.

**Comment by Exxion** [comment]
Sharpness flags

**Comment by Shadowmech88** [comment]
Yeah, we differentiate sharpness now between points, blades, saw teeth, et cetera.

**Comment by ghost** [comment]
Is_hot or whatever the plasma cutter and a couple others too?
