### ISSUE TITLE
Slime floor tiles slow actual slimes.

### ISSUE THREAD

**Issue by DrSnips** [d3athrow/vgstation13#15858]
The green slime floor tiles may affect slime people, but they don't effect actual slimes, large and small.
They slowed me down as a real slime (both sizes) while walking on them when it should speed me up on them.

**Comment by ghost** [comment]
Shhhh my code is perfect 🔫

**Comment by DamianX** [comment]
>buffing slimes

**Comment by DrSnips** [comment]
Its not a buff if it should be intended

**Comment by ReindH** [comment]
Cryofloors when?

**Comment by CptWad** [comment]
additionally, they are not unique turfs so they cannot be bussed in without a lot of effort, or mapped in

**Comment by DamianX** [comment]
Fixed by #18257
