### ISSUE TITLE
Borer's can't view flavor text

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15860]
(WEB REPORT BY: panthid REMOTE: 172.93.109.202:7777)
# Revision
089fa1318a411f50e6db33a58c0eb620d7e4eea7

# Description
Borers attempting to view flavor text get a "Hell no." debug message instead.
# Steps to Reproduce
Try to expand flavor text as a borer.
# What you Expected
To be able to view flavor text as a borer.
# What Actually Happened
"Hell no."

**Comment by Exxion** [comment]
Yeah for some reason, that's all borers' `Topic()` does
