### ISSUE TITLE
Bagelstation Browser Map 404

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15871]
(WEB REPORT BY: arjunz REMOTE: 172.93.109.202:7777)
# Revision
af25d80b871d85f1da391adf266a1812c5c85722

# Description
The Bagelstation browser map doesn't work. It 404s

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by CptWad** [comment]
who the hell else has dropbox access
I uploaded bagel AND packed
literally waiting on whoever the fuck updates the website

**Comment by Shadowmech88** [comment]
Is this still an issue?

**Comment by ShiftyRail** [comment]
@Exxion Bagel has a render now, no longer an issue.
