### ISSUE TITLE
condiment bottles don't transfer chemicals to food

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15872]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
af25d80b871d85f1da391adf266a1812c5c85722

# Description
basically what the title says, I used a condiment bottle and it didn't transfer the chems to the food like it should have. I don't think this was always the case, and it might need a bit of testing to confirm what the problem is.

**Comment by Eneocho** [comment]
Fixed
