### ISSUE TITLE
Packed: Chemistry Dispensers start uncharged.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#15884]
#### Description of issue
The chemistry dispensers in packed station start without any charge, this is very troublesome for the chemist at round start when they're ready to crank out some pills.

#### Difference between expected and actual behavior
On every other map, the mapped chemistry dispensers start out at full charge.

**Comment by CptWad** [comment]
its because dispenser/chem is whats made by NEW players while dispenser/chem/mapping is whats used in the map maker

**Comment by Exxion** [comment]
EXCELLENT IDEA: Remove the mapping subtype and make them fill their charge in `New()` if `ticker` does not exist
