### ISSUE TITLE
Touching the singularity with TK gibs you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15883]
(WEB REPORT BY: aparist REMOTE: 172.93.109.202:7777)
# Revision
4b92c53739e82525ac2443f7158ae1834bcdb225

# Description
Touching the signularity with TK gibs you

# Steps to Reproduce
Get TK
Get a singularity (only tested with a stage 3 one)
# What you Expected
No reaction, since I used my mind to touch it telephatically

# What Actually Happened
I gibbed on the spot

**Comment by DamianX** [comment]
feature

**Comment by SonixApache** [comment]
[honk]

**Comment by Knightkiller11** [comment]
I think it would be interesting if TK'ing a shard/singularity did the soulstone capture effect, but perhaps for gameplay a message like "this is a bad idea" would be better

**Comment by jknpj** [comment]
Maybe "this was a bad idea" after gibbing would be better,

**Comment by Intigracy** [comment]
Suggested fix: Don't touch the singularity.

**Comment by Killette2** [comment]
It blew your mind

**Comment by ghost** [comment]
what if you could fling the singularity around with TK

**Comment by nuklearcellphoneg** [comment]
What if it turned you inside out instead
