### ISSUE TITLE
You can apparently genfab more revsquad flashes.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15899]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
The new flashes still convert.

**Comment by jknpj** [comment]
thanks mechanics.

**Comment by gbasood** [comment]
i thought i explicitly made that impossible

**Comment by ghost** [comment]
>rev flash is based on the flash and not the person using it

coders?????????????

**Comment by gbasood** [comment]
@Commandersand 
If it were based on the person using it:
 - Give flash to rev buddy after convert
 - Get more uses out of it for free
 - Wow ez

The problem is that they can be genfabbed at all.
