### ISSUE TITLE
Ghosts can Empty Deep Friers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15894]
(WEB REPORT BY: n3x15 REMOTE: 172.93.109.202:7777)
# Revision
f525395eddeefbf26cf0950a9d2e65096e27ef0d

# Description
Ghosts can empty deepfryers

# Steps to Reproduce
1. Right-click on frier as ghoast
2. Remove ingredients

# What you Expected
Denial message or something.

# What Actually Happened
Complied.

**Comment by FudgePucker** [comment]
Is it logged or can some asshole just empty it and get away with it?

**Comment by Anglosphere** [comment]
I'll also add Mice can also do this. 

On top of this mice can also toggle hydro tray lids, and label them.

**Comment by Cyadox** [comment]
Ghosts can also use washing machines, spoopy

I think we need to add some sanity to the machine/console class.
