### ISSUE TITLE
Box station Vox botany

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15898]
(WEB REPORT BY: spoonylove REMOTE: 172.93.109.202:7777)
# Revision
cc51b31f7cd71bc097aa9b733b0e8ef32f2d33f8

# Description
Vox station botany has no data disks to use the xenobotany machines. 

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
according to @Probe1 that's WAD

Trade for them

**Comment by SonixApache** [comment]
working as intended

**Comment by Riekland** [comment]
shouldn't have xenobot machines in the first place
boards maybe
full machines fuck no
