### ISSUE TITLE
Slimes do not grow when line of sight is lost after feeding

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15909]
(WEB REPORT BY: soudesuka REMOTE: 172.93.109.202:7777)
# Revision
a83b039a29feb39b2aa81d6dfd6ab936de2ef376

# Description
Feed slime a monkey, walk out of view of slimes. Slimes do not grow when not being watched. Once bugged, limes will not grow after any amount of waiting, and feeding them again will not cause them to grow.

# Steps to Reproduce
Feed a slime, leave its line of sight.

# What you Expected
Slimes to grow while the mob that fed them is not in view.

# What Actually Happened
Slimes do not grow and never are able to again.

**Comment by DrSnips** [comment]
Pretty sure the only sight code slimes have is for thier friends list. Nothing to do with growing.

**Comment by AI-Is-Rogue** [comment]
A long time without feeding will make slimes need to eat a lot more monkeys than usual to become an adult.

**Comment by nervere** [comment]
> A long time without feeding will make slimes need to eat a lot more monkeys than usual to become an adult.

This is the explanation. Line of sight has nothing to do with growth.
