### ISSUE TITLE
Lightning spell does no damage.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15914]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
Zilch.

**Comment by Cyadox** [comment]
If it helps, I think I was the guy (or at least one of) the guys he was zapping. I was wearing insulated gloves at the time so I'm not sure if that protects you or not, but basically after numerous zaps all it did was give me that hazy cloudy effect you get when you get eye damage, but no physical damage at all.

Edit: Also had a Vox softsuit on. I recall a message saying it absorbed the blow, but I'm not sure if that was related.
