### ISSUE TITLE
Feature Request: crawling

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15919]
I kinda like being able to go places at a slow speed in my russian cave simulators while having broken legs
Not being able to move at all is pretty lame if you lose a leg or just in pain crit
It would probably require having at least one fully functional arm/hand
If that's too complicated a little life alert necklace for people with robotic legs or cripples would be nice

**Comment by ghost** [comment]
Ask the thread for the PR where it was broken intentionally, promised to be fixed then was never fixed. That one guy has it on speed dial

**Comment by Aurx** [comment]
> If that's too complicated a little life alert necklace for people with robotic legs or cripples would be nice

That's called "Turning on your fucking suit sensors" and calling for help.

**Comment by nuklearcellphoneg** [comment]
Do me a favor. Lay on your stomach on a linoleum floor and attempt to crawl without using your legs.

That being said, I'd be in favor of being able to crawl using tables, chairs, corners, etc that would normally be 'grabbable' and I think it'd be a nice touch(I also think it'd be neat to be able to use those bolted down things to brace yourself against the dreaded ZAS to some effect, not invulnerability).

**Comment by Shadowmech88** [comment]
I think you could crawl on tile without using your legs by holding yourself up with your arms and then falling forward.
It'd be slow going, but you'd move.

Also, just because your legs are too broken to walk on doesn't mean they can't aid in crawling.

**Comment by nuklearcellphoneg** [comment]
Incredibly slow. Also remember you're doing this because your legs are shattered.

Able to use your hands at all while laying down when?

**Comment by ghost** [comment]
Just ask Hippie how all this shit went.

**Comment by ghost** [comment]
Being able to use things while lying down works well in my Ukrainian stronghold exploration game
it doesn't let you attack above the groin 
Being able to use items while down would lead to some more spicy combat but the metaclub would not allow that so I only made a request to crawling

**Comment by Riekland** [comment]
hahahahahahahah
HAHAHAHAHAHAHAHAHA

**Comment by SonixApache** [comment]
Being able to move with one or zero legs would be really nice.

**Comment by ghost** [comment]
> Do me a favor. Lay on your stomach on a linoleum floor and attempt to crawl without using your legs.

Not everyone is as out of shape as you @nuklearcellphoneg

**Comment by ghost** [comment]
Savage

**Comment by nuklearcellphoneg** [comment]
Grudges teach you how to crawl I suppose.

https://www.youtube.com/watch?v=uBAXDVB5Q6E

**Comment by MadmanMartian** [comment]
@Shadowmech88 this has been fulfilled for the most point. Please close.
