### ISSUE TITLE
custom vending machines delete their contents instead of firing it

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15949]
When the red light is off on vending machines via pulsing, their contents will fire out at mobs.  For custom vending machines, it appears to not be firing and to just be deleting its contents.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Anglosphere** [comment]
I was able to replicate this bug.

**Comment by Knightkiller11** [comment]
Guess that ruins my "Fill it full of single stacks of sharp things/floor tiles" idea, and my "fill it with glass containers of PolyAcid" turret idea.

**Comment by Zth--** [comment]
/obj/machinery/vending/proc/throw_item()

**Comment by DamianX** [comment]
Closing in favor of #17567
