### ISSUE TITLE
Advanced Security Cameras

### ISSUE THREAD

**Issue by BurntDevil** [d3athrow/vgstation13#15944]
#### Description of issue

The camera's for the Z-level will fail to show after certain actions, mainly moving away while the camera is active.

#### Steps to reproduce 

Make Advanced Cameras
Use camera, any camera. 
Close the security camera panel. You will be stuck on camera screen until you move away from console.
Move away.
Return, the cameras will not function for that Z-Level.
This works every time.

**Comment by MadmanMartian** [comment]
I honestly can't reproduce this using the steps to reproduce you've given. Maybe it's something that can't be reproduced locally as it apparently has you download resources each access time according to #15564

**Comment by Theophrastus1** [comment]
welcome to adv. sec cameras which have been fucked for over 3 years or something like that
