### ISSUE TITLE
Habitat vendor metal and glass are not real

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#15940]
#### Description of issue
Metal and glass from the vendor can be used as sheets for their specific sub menu, but cannot be inserted into protolathes, circuit printers et al, and are "recycled" by autolathes

They also cannot be merged with real metal or glass sheets

It seems they are a clone that has not inherited all functions

#### Difference between expected and actual behavior
Metal and metal(vendor) should be able to stack and be used in machinery

#### Steps to reproduce 
Buy metal or glass from the engineering habitat vendor and use it for anything that isn't in the metal construction menu

#### Length of time in which bug has been known to occur

At least since yesterday (15 hours from issue being written)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
The vendor uses a /bigstack subtype for those, and I believe it was discussed that it might cause problems, but the alternative didn't work or something similar?

@Kurfursten probably knows.

**Comment by Kurfursten** [comment]
Mysterious. I thought I picked this up in testing but I guess I didn't test *enough*.

I have an alternate easy patch that should make it work though, I'll put it up in the next half hour or so, thanks for reporting.
