### ISSUE TITLE
[Bagel] getting to cent, birds in the coop edition

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#15942]
The bagel Tradership is improperly aligned in hyperspace. This allows crafty bug abusing traders to get to centcom without admin intervention. 

It seems like someone noticed this, but didn't quite fix it. The bottom windows of the north side of the cockpit are indestructible, but if you go in from the north, and trigger the ship with a PDA, you can exit 
 to the non-hyperspace turfs while the ship is in motion. 

![birds in the coop](https://user-images.githubusercontent.com/19157295/30247182-b521153a-95d3-11e7-8282-87038459df86.png)

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Durgen** [comment]
suggested fix: align the ship properly during hyperspace warp on z2
suggested lazy fix: make the north windows also indestructible

**Comment by EenKogNeeto** [comment]
I reported this ages ago, Likely prompting the window thing. Can confirm the birbs in question weren't even robust and failed to steal the 5000 stack of glass, the pocket blackholes, or any of the other cool stuff.

**Comment by Durgen** [comment]
we had to make a quick escape while dodging bluespace artillery

**Comment by MadmanMartian** [comment]
How does this happen? Surely it's as simple as a mapping issue

**Comment by Durgen** [comment]
fixed by https://github.com/vgstation-coders/vgstation13/issues/16074
