### ISSUE TITLE
Elite Syndicate Shuttle oon BAGEL

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15943]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
9ebadaf67d1e29f07c3f1a42b57ab427a6a61313

# Description
the elite syndicate shuttle does not work properly, attempted to use shuttle magic when it did not move and it refused to teleport to created docking ports. VV destroy everything was 1 maybe it needed a transit area. Eitherway it was borked
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by CptWad** [comment]
@DeityLink

**Comment by DeityLink** [comment]
I'm on it.
