### ISSUE TITLE
Deff Genetics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15954]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
There's only one genetics console when there are two geneticist slots.

**Comment by ghost** [comment]
I was under the impression there was only one geneticist spawn in Deff from what Duny said.

**Comment by Kurfursten** [comment]
There are two geneticist slots on Deff, but if you wanted to make it limit one...

https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/maps/defficiency/jobs.dm
