### ISSUE TITLE
Holywater anything anywhere

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15953]
(WEB REPORT BY: eenkogneeto REMOTE: 172.93.109.202:7777)
# Revision
9c42b535c01b55a41766c11dfa99a32837d3405b

# Description
The chaplain can turn any water tank in sight into holywater.
# Steps to Reproduce
take bible, click water tank from a mile away
# What you Expected
Can't reach
# What Actually Happened
Can reach

**Comment by Exxion** [comment]
I wonder how old this bug is

**Comment by Kurfursten** [comment]
Isn't Space Jesus omnipresent?

I bet it works through cameras too.

**Comment by Fruktlimpa** [comment]
Space Jesus exists within all of us, objects and beings alike. The chaplain simply calls him forth from the depths of man or object.

**Comment by nuklearcellphoneg** [comment]
>see cultists meeting in bar
>see one with a glass of water


The possibilities of hilarity will be missed
