### ISSUE TITLE
Disposals Bug on Tree-cockatriceship

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15956]
(WEB REPORT BY: eenkogneeto REMOTE: 172.93.109.202:7777)
# Revision
8c64da39880d56bea8d976ee68d4596a8c913146

# Description
Cockatrice/Treeman ship has a weird thing that leads to stacked vines and probably shouldn't be possible in general.
https://i.gyazo.com/1fa45052165a38838d714092b2a031e7.png
# Steps to Reproduce
Observe the tree-cockatrice ship, Near the pens at the disposal part.
Watch as it constantly stacks more vines onto a tile by consuming the vines that spread into the disposal and spitting them out somehow.
# What you Expected
Vines not to stack infinitely
# What Actually Happened
Dozens of vines end up on the same tile due to the disposal eating and then shooting them out.

**Comment by Exxion** [comment]
That's fantastic.

**Comment by ghost** [comment]
That's terrific!
