### ISSUE TITLE
Traitor PDA not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15961]
(WEB REPORT BY: headshotter REMOTE: 172.93.109.202:7777)
# Revision
ebc939bf1769a0182199c110f7ab6f58406e532b

# Description
Inputting my traitor code into my PDA's ringtone does not show the Syndicate uplink screen. It merely closes the PDA window.
# Steps to Reproduce
Take traitorous PDA in hand. Open PDA. Go to messenger, click Set Ringtone, manually type my traitorous code (in this case, 844 Alpha). 
# What you Expected
The red background screen, showing the traitor items you can spawn.
# What Actually Happened
Tried closing the game window and re-connecting. Same results. Had to ask an admin to spawn me an emag. Xevonix helped me.a

**Comment by west3436** [comment]
Unable to reproduce/more information needed

**Comment by Eneocho** [comment]
> Unable to reproduce/more information needed

I've had the same issue happen once, it just blinked and selfclosed. My bet is it was some sort of nanoUI-like issue (in that it gets fixed by restarting the game).
