### ISSUE TITLE
Mechs not getting destroyed by a crystal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15968]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
c49d1851271db3264cee2c04307e7f151b09e5bd

# Description
Noticed a durand just pushing a supermatter crystal like it was nothing

# Steps to Reproduce

Get in a durand, possibly other mech, and walk into a shard/crystal

# What you Expected
durand to explode
# What Actually Happened
crystal was pushed, acted like a locker/other big movable object

**Comment by SonixApache** [comment]
Can clamps load shards?

**Comment by Exxion** [comment]
Yes
I think

**Comment by jknpj** [comment]
yeah the clamp can pick up shards

**Comment by SonixApache** [comment]
So I could load my mech up with ten shards to nuke the immediate vicinity and EMP the station to death upon destruction.

That's fucking amazing. I love this game so much.

**Comment by WhiteHusky** [comment]
Careful, you'll give people ideas.

And you're giving me ones right now and the idea of discretely loading a mech with shards to wander around with, watching people's faces melt off their skulls and various electronics explode violently sounds like a grand time.

However I'm not sure if shards will 'burst' radiation when inside a container like the mech.

**Comment by Exxion** [comment]
If something prompts them to, they probably will, but I can't imagine how anything would do so while they're in a mech.

**Comment by SonixApache** [comment]
set a gygax to sanic mode, sprint into sec, drop 5 shards, sprint away, laser the shards

**Comment by FudgePucker** [comment]
Clamps being able to handle shards makes sense. The shard has a containment stand that let's you pull it around and pick it up with a mecha. You bump into the shard itself, then it removes you from existence.

Maybe when you bump into a shard in a mecha it destroys the mecha and makes you fall to the ground like something from looney toons

**Comment by ghost** [comment]
just make it drain the mech's powercell TBH if you bump into it
also
punching crystals making 9 shards when?

**Comment by Exxion** [comment]
Why would bumping into it drain the mech's powercell?

**Comment by Eneocho** [comment]
tested, cannot push, seems to be fixed
