### ISSUE TITLE
Buckled on rollerbed = bullets can't touch you

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15964]
Probably should make a formal bug report for this.

When buckled to a rollerbed the rollerbed essentially acts as a wall for projectiles. End result, they cannot touch you. Thankfully you can't shoot back or anything

Steps to reprojews:
1) Buckle catbeast to rollerbed
2) Attempt to valid it

**Comment by nuklearcellphoneg** [comment]
Harm intent point blank range too?

**Comment by ghost** [comment]
Didn't try, I would assume no

**Comment by ghost** [comment]
Yep, blocks harm intent point blank range, too
It also blocks thrown items

**Comment by ghost** [comment]
Add chemical sprays, items being ZAS'd, and kudzu

(Technically all the above except bullets also apply to vehicles)

**Comment by strawberrytan** [comment]
I remember people using this to be invulnerable to lasers, the bed can tank infinite shots

**Comment by Exxion** [comment]
Anyone remember photocopier surfing?
Because I'm like 95% sure that is still 100% a thing

**Comment by nuklearcellphoneg** [comment]
Should have been fixed- I remember when someone used it specifically to fuck over a malf so everyone flipped out about it.
