### ISSUE TITLE
Food icons of plants stay when they're loaded into a fridge

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15972]
(WEB REPORT BY: hundreddirtyjacks REMOTE: 172.93.109.202:7777)
# Revision
535535b12243268dd46612b745b07f961f0a56fb

# Description
Plant icons on screen when you load them into the fridge when they're suppose to disappear. 

# Steps to Reproduce
Simply load plants into botany fridge.

# What you Expected
I expected the plant icons to dissappear instead of staying.

# What Actually Happened
Plant icons stayed.

**Comment by Kurfursten** [comment]
This only happens if you have the bag view open when you load contents

I think probably related to not passing user in the recent smartfridge patch instead of just having a quiet arg like I originally intended, will have a look

**Comment by DamianX** [comment]
Yep, I didn't think about it.
`drop_item` takes care of it through `remove_from_mob`. The quiet argument was the sane choice.
