### ISSUE TITLE
Deficiency: Science outpost diposal system is a deathtrap.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#15970]
#### Description of issue
The science outpost disposal system currently ejects you into the oxygen miner, causing you to get crushed.

#### Difference between expected and actual behavior
Expected the disposal system to take you outside like it used to.

#### Steps to reproduce 
Climb in disposal system and wait for bone breaking sound effects.

**Comment by Exxion** [comment]
When did you last see it work correctly?

**Comment by Sooose** [comment]
About a few months ago, I haven't used it in quite some time.

**Comment by Kurfursten** [comment]
Map render of deff still shows the disposals going into space and no O2 miner at all

Someone force a render update

**Comment by Duny-** [comment]
![image](https://user-images.githubusercontent.com/5224390/30426813-b734ef36-994d-11e7-8818-b54aa2c5e3e3.png)
Well that's certainly something.
I'm going to go ahead and fix that.
