### ISSUE TITLE
Plasma-men nearly immune to laser cannons?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15980]
(WEB REPORT BY: eenkogneeto REMOTE: 172.93.109.202:7777)
# Revision
de857b5321bff2d75ce0064a0f974e1515d732ef

# Description
I can't be certain that this is actually a bug, or intended. But I landed 6 shots on a plasma-man with a laser cannon (Admin confirmed that 6 connected) and he remained standing and concious, not even visibly pained. Laser cannons are a fairly high tier weapon, and as far as I am aware still do 40 damage a hit. Even a racial 50% resistance wouldn't lead to this result, hence my considering it a bug.
*Potentially important note: I was a combat borg at the time, Perhaps the issue is there? 
# Steps to Reproduce
Take a laser cannon, Shoot it at a plasma-man
# What you Expected
Slightly more resistant than the average human
# What Actually Happened
Doesn't even flinch despite being hit with potentially 240 burn damage.

**Comment by EenKogNeeto** [comment]
Added note: 
He said he softened three of the hits, Which I figured took it to 180, and then if they just half burn damage or something would put him at 90, Aka 'one hit from death' So this is now obviously intended and can be removed or whatever. Was just a freak luck streak.
[Doing the math and figuring out this wasn't a bug](https://i.imgur.com/Kp6RN00.png)
PS: Kill me
