### ISSUE TITLE
Advanced EOD Suit Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15986]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
Advanced EOD Suit's legs don't cover two pixels of foot, resulting in ugly toeless bomb-resistance

**Comment by Shadowmech88** [comment]
I believe the root cause of this is that the full human sprite in `human.dmi` is missing pixels on the feet, causing clothing to not cover those areas when people use that human sprite as a guide in spriting clothing.
