### ISSUE TITLE
Vox jobs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#15985]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
55f0b796201e5ec16c844ae729f3b196f36e30d5

# Description
vox can be sec
# Steps to Reproduce
pick vox, join sec
# What you Expected
no dirty thieving nonhuman shits in my police force
# What Actually Happened
CAW WE MAKE MANY ARREST

**Comment by ShiftyRail** [comment]
Clearly the solution to this is to remove sec

**Comment by SonixApache** [comment]
http://ss13.moe/wiki/index.php/Guide_to_Food_and_Drinks#Chicken_Recipes
vox do need more jobs, 5 isn't enough

**Comment by Mothblocks** [comment]
*aflap

**Comment by Exxion** [comment]
Restricting jobs by species is already a feature, so that's a more appropriate tag
Also, discussion dead, reopen to continue

:sneaky_coders:
