### ISSUE TITLE
POS machines literally print infinite money.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#15991]
#### Description of issue
Hilariously enough, I encountered this issue while fixing the other issue that was reported with the POS grammar stuff.  When you make a product with the machine for say $100, and you finalize a sale and only enter the $100, it does not consume the money and just spits even more cash, equal or greater than the total (up to $10,000), back out in a change box.  You can sit there and double it to obtain insane amounts of cash.

#### Difference between expected and actual behavior
I expected a normal transaction.  I got a magical money doubling machine.

#### Steps to reproduce 
1. Set a product for any amount of money as the price.
2. Make a purchase for that produce and finalize it.
3. Try to insert the cash for the value of the produce only (not including taxes)
4. Holla holla get dollah

#### Specific information for locating
A POS machine can be found in the front of nearly all department.  They are the machines that no one uses.

#### Length of time in which bug has been known to occur
There is absolutely no telling given that nobody uses them.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by TheFriggenSawbones** [comment]
d o u b l o o n s
o
u
b
l
o
o
n
s

**Comment by Kitfox88** [comment]
something something fiat currency something buttcoin

**Comment by Zth--** [comment]
I started investigating this and found out that if you add a product with a negative value and then purchase it, you can add as much money as you want to your account

**Comment by Exxion** [comment]
Not really surprising nobody found these bugs before
I've never seen one actually used
