### ISSUE TITLE
[Bagel] Artifact harvesting room isn't connected to the outpost's grid

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#15995]
#### Description of issue
![fucking wad](https://user-images.githubusercontent.com/17928298/30497827-b7911256-9a2a-11e7-9804-c1119273d724.png)

#### Length of time in which bug has been known to occur

Since we got a new outpost, i guess.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Durgen** [comment]
I'm also pretty sure there is no wire under the emitter

**Comment by CptWad** [comment]
christ
