### ISSUE TITLE
Opening the flavor text window as pAI also opens the pAI menu

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16002]
Self-explanatory, have someone with a >32 chars flavor text, examine it as a pAI, your software interface opens as well.

Version 61e7b03a5fcf5b307561f48fd4df28c5a5a269e9

**Comment by Exxion** [comment]
Holy fuck.
pAI `Topic()` is set up to always open the interface unless the link you clicked was *specifically* an admin PM.
Absolutely stunning.
```
if(href_list["priv_msg"])	// Admin-PMs were triggering the interface popup. Hopefully this will stop it.
	return
```

**Comment by DamianX** [comment]
It is impressive.
