### ISSUE TITLE
Pinpointer Sprite has Different Details when in use

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16007]
(WEB REPORT BY: carlenwhite REMOTE: 172.93.109.202:7777)
# Revision
61e7b03a5fcf5b307561f48fd4df28c5a5a269e9

# Description

When the pinpointer is in use, the sprite changes and adds two buttons as if the screen shrunk
https://puu.sh/xBy4y.gif

# Steps to Reproduce

Use pinpointer.

# What you Expected

The sprite to not change much.

# What Actually Happened

Sprite grows two new buttons.

**Comment by WhiteHusky** [comment]
Claiming.
Also the sprite without having to browse to it.
![](https://puu.sh/xBy4y.gif)
