### ISSUE TITLE
stray bible pixel

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16008]
(WEB REPORT BY: orangerush REMOTE: 172.93.109.202:7777)
# Revision
61e7b03a5fcf5b307561f48fd4df28c5a5a269e9

stray ian bible pixel at the top right of the icon. can be seen when in your bag and when dropped http://puu.sh/xBAXN/9e7b7dd405.jpg

**Comment by Orangerush** [comment]
Going to add onto this report, not sure if it's for all sprite or just the Ian flavored bible

**Comment by Exxion** [comment]
It's presumably just the Ian bible because the different sprites have nothing to do with each other
I mean it could be present on others, but it would be present separately, if that makes sense

**Comment by Kurfursten** [comment]
It is just the Ian Bible

You can find the sprite in storage.dmi - you can delete the pixel yourself by setting the alpha all the way to transparent on any color, or just substitute this fixed sprite

![ianism](https://user-images.githubusercontent.com/9782036/30735514-ed648f06-9f44-11e7-8f2c-aca1145dbd2d.png)
