### ISSUE TITLE
Guac recipie is broken.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16013]
(WEB REPORT BY: faceplantkun REMOTE: 172.93.109.202:7777)
# Revision
61e7b03a5fcf5b307561f48fd4df28c5a5a269e9

# Description
Guacamole burns when you try to make it. Put in exact amounts of everything needed, still got burnt mess.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Shadowmech88** [comment]
My bad, I forgot to change the guacamole recipe on the wiki when it was changed in #15082.

**Comment by Shadowmech88** [comment]
The wiki's up to date now, so this should be fixed.
