### ISSUE TITLE
Request: Aloe Vera and Cotton plants.

### ISSUE THREAD

**Issue by Ragnasal** [d3athrow/vgstation13#1602]
Could be used to make salve and bandages. Yes/No?

**Comment by nuklearcellphoneg** [comment]
Yeah

Botany would drool over this

Pls hurry

**Comment by gbasood** [comment]
We should actually implement this

**Comment by nuklearcellphoneg** [comment]
Hi, let me reiterate how much I like this, as I believe in coding new quality things over porting quality things from other servers. :^)
