### ISSUE TITLE
Pushing a gas mask out of the way shaves you temporarily

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16025]
(WEB REPORT BY: aparist REMOTE: 172.93.109.202:7777)
# Revision
706eb74a39085a5fd1f91c435ae9aff57cbce3ab

# Description
see title
# Steps to Reproduce
Have beard
Wear gas mask
Push it out of the way
Take it off
Put it back on
Push it back into place
Take it off
# What you Expected
Nothing
# What Actually Happened
I got phantom shaved

**Comment by jknpj** [comment]
body covering flags still apply when the mask is up, should be an easy fix for newbies

**Comment by Riekland** [comment]
not being able to wear a gas mask if you're not shaved or using the hitler mustache when
