### ISSUE TITLE
Disabling MoMMI's to "tip them over" doesn't work propelly

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#1603]
Okay, abefore we start with this issue, here's a little thing i'd like to share:
You can press disable and aim at normal Borgs to "tip them over".IT stuns them but has no sprite/animation as far as i know.

With that being said.
Disabling MoMMI's generate text as normal, but doesn't seem to immobilize the MoMMI.

**Comment by ComicIronic** [comment]
Can anyone actually tip a borg?
It seems to me that the functionality isn't in the code currently.

**Comment by clusterfack** [comment]
I fixed this with my most recent pull

**Comment by ComicIronic** [comment]
Name it and I'll close it.

**Comment by clusterfack** [comment]
https://github.com/clusterfack/bugfixstation13/commit/9b17e1ff803c40ed438fea9917b59198a1bba84c
