### ISSUE TITLE
Sprite request: active subspace receiver

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16033]
The subspace broadcaster (![image](https://user-images.githubusercontent.com/6307265/30623894-abb06a8e-9dba-11e7-9d90-21c206208d61.png)) currently has a simple animation for when a message is sent.

It looks like this: https://imgur.com/YiSVcOi
Its counterpart, the receiver, lacks a receiving animation.

All these icons are in `icons/obj/stationobj.dmi`.

**Comment by Kurfursten** [comment]
Isn't that because the receiver is always animated, unlike its counterpart?

**Comment by DamianX** [comment]
Maybe, but a guy made a sprite anyway.

**Comment by Shadowmech88** [comment]
Can this be closed, then?

**Comment by DamianX** [comment]
#16035 will close it
