### ISSUE TITLE
Sprite request: Some consoles use a generic computer sprite

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16034]
- ~~Telecommunications Traffic Control~~ done
- ~~stacking machine console~~ done
- ore processing console

**Comment by Kurfursten** [comment]
![traffic](https://user-images.githubusercontent.com/9782036/30673584-bd3c1c38-9e39-11e7-9bb7-addf3951111e.gif)

A traffic computer sprite I threw together

**Comment by Kurfursten** [comment]
![stacking](https://user-images.githubusercontent.com/9782036/30685941-3fc99878-9e7c-11e7-8d35-fed62eba4ee9.gif)

Stacking machine

**Comment by MintyEtude** [comment]
![oreprocessingcomputer](https://user-images.githubusercontent.com/77856878/105538755-e2e47a80-5cc1-11eb-9752-81726bb44248.gif)
Ore Processing machine
