### ISSUE TITLE
Kudzu vines can be enter disposals

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#16041]
#### Difference between expected and actual behavior

**Expected:** 

Kudzu vines not separating themselves and entering disposals

**Actual:** 

![disposals kudzu](https://user-images.githubusercontent.com/17928298/30704750-054c3bbc-9eca-11e7-9415-4bc63bc44153.png) 

Kudzu enters disposals then gets tossed back inside, cogratulations, now you have stacking kuzdu.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
#15956

**Comment by ghost** [comment]
Oh, for some reason I thought this was something that only happened in specific conditions of that vault.

This makes more sense.

**Comment by ghost** [comment]
Tentatively fixing this by making disposal inlets not able to take anchored objects, I found that you can ride janicarts down disposals.
Feature?
