### ISSUE TITLE
Defficiency Virology has a docking port inside it

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16043]
Exactly what it says on the tin, you can see it when you're a ghost. It's over by the containment rooms.

Just a little oversight, an easy fix.

**Comment by CptWad** [comment]
apparently its intentional, ask @DeityLink

**Comment by DeityLink** [comment]
@Kurfursten not an oversight. That's the deathsquad's "crash into the station" docking port.

deathsquad and elite syndie both have a near station/inside station docking port.

**Comment by SonixApache** [comment]
👌 

We should get drop pods.

**Comment by Kurfursten** [comment]
wew

**Comment by DeityLink** [comment]
@SonixApache That's basically what the Elite Syndie/Deathsquad shuttles are. Except they can drive them away for now. (previously the elite syndie shuttle was a one way trip)
