### ISSUE TITLE
Cant disarm any monkeys or nymphs

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#16048]
#### Description of issue
Tried to shove down Pun Pun and no response, no text feedback or anything. I tried different targeting regions and still nothing.
Tested it in two different instances, also tested it on a soulless diona nymph and got the same results.

#### Server revision

Revision: 2fe5585b7455a2d288eb2e26f45ceb680ee340ae 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Limitless power

**Comment by Exxion** [comment]
Yeah, looks like the disarm intent just... doesn't do anything to monkeys
Could you disarm them before? Honestly I'm not sure I've ever tried

**Comment by Dacendeth** [comment]
Yeah you could disarm them before, I talked to harse theef, they think it might be related to their shushing addition.
