### ISSUE TITLE
If possible, seperate movement and throwing icons for items

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#1605]
Bolas currently spin around as if you threw them when you pull them.

**Comment by Probe1** [comment]
![2](https://cloud.githubusercontent.com/assets/8550416/10092282/966d7ebc-6312-11e5-900f-0e5217343ec5.gif)


this is the funniest bug i've ever seen

**Comment by ConkerDev** [comment]
Didnt you know about this? It was even worse with the old sprites. At least now it looks cool.

**Comment by gbasood** [comment]
Could change it so bolas spin until they're done being thrown to resolve this but honestly not even a real problem

**Comment by Intigracy** [comment]
too neat to fix
