### ISSUE TITLE
Missing in-hand sprites

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16050]
The toy sword and the taser gun in-hand sprite don't appear at all, both left and right.
There's probably more.

#15992 was the last to touch the in-hand files.

**Comment by Kurfursten** [comment]
One of these days I swear I am going to make a README for new coders that has all the basic information like

**Do not edit "read only" sprite files. If you need to add new inhands, pick a different inhand file or make a new one.**

@DrSnips

**Comment by Shadowmech88** [comment]
We should honestly just have Travis fail any PRs that edit over-capacity .dmi files.

**Comment by DrSnips** [comment]
Yeah, Im guilty here likely. There's surgery inhand dmis but the file isn't used actually. I think I added the new tools to it so feel free to delete the sprites in the large inhand dmis and just throw a few lines in the surgery tool code to path them to the surgery tool inhand dmi.

**Comment by SonixApache** [comment]
>touching one of the 13 cursed read-only .dmis
