### ISSUE TITLE
Can't Surgically Remove Wooden Lumbs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16058]
(WEB REPORT BY: cyadox REMOTE: 172.93.109.202:7777)
# Revision
4f0316c857c335cc03dfecfa274f5a5b0947b24b

# Description
Title says all. Tried to remove a wooden lumb from someone and couldn't.
# Steps to Reproduce
Replace someone's arm with a wooden limb
Attempt to remove wooden limb using surgical saw or harm intent
Chat messages says you've removed the limb, but it's still attached
Additionally, wooden limb causes crit effects even though the person is still at 100% health (can't stand, etc)

**Comment by Cyadox** [comment]
As a note, this bug is apparently at least a couple years old according to some kind folks in deadchat. Apparently it was deemed too difficult to fix at the time.

**Comment by Cyadox** [comment]
~~Has to do with the droplimb proc in /modules/organs/organs_external.dm. For whatever reason it's called but fails. I'll have a chance to debug it sometime next week, so anyone else can feel free to see what's going on until I get around to it.~~

Never mind that, found the bug. destspawn (which determines if a limb has been removed already) is set to true when it really shouldn't be.
