### ISSUE TITLE
Floor with custom step effects (uranium, bananium) still trigger when trying to enter a blocked floor

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#16055]
Example: Build uranium floor, build a table over it, walk into the table. You are irradiated despite not stepping on the uranium.

This is because the step effects are handled on Enter(), which is actually a proc used to see if you can enter the tile, not after you enter it.

**Comment by SonixApache** [comment]
same happens for putting uranium floors under windows - walk into window, get irradiated

**Comment by Exxion** [comment]
Yes, that is one of the objects that can stop you from moving into a tile

**Comment by SonixApache** [comment]
i didn't realize how useless my comment was till i read the OP again
