### ISSUE TITLE
Bluespace Tomatos Not Teleporting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16059]
(WEB REPORT BY: seymourbutts REMOTE: 172.93.109.202:7777)
# Revision
4f0316c857c335cc03dfecfa274f5a5b0947b24b

# Description
Bluespace tomatos seem to no longer teleport
# Steps to Reproduce
Grow tomato
Throw tomato
# What you Expected
Bluespace tomato blinking
# What Actually Happened
Tomato splats and nothing happens

**Comment by Kurfursten** [comment]
They don't teleport until you increase potency

**Comment by Zth--** [comment]
I just tested them, they're working. You need at least 15 potency for them to work
