### ISSUE TITLE
There are only two roundstart mechanic positions, but up to three can be supported via latejoin.

### ISSUE THREAD

**Issue by TurboGay** [d3athrow/vgstation13#16065]
#### Description of issue

There are only two roundstart mechanic slots, but you can latejoin after the round has started to make three mechanics total. Unsure if it can go up to more mechanics than three.

#### Difference between expected and actual behavior

Expected the game to be able to support three mechanics readying up in the lobby, which was not the case and resulted in having to join late.

#### Steps to reproduce 

Have three people ready up with mechanic set on high in the lobby.

#### Length of time in which bug has been known to occur

I'd say this issue has been happening for a month or two now, if not more time. Just wasn't sure if it was intended behavior or not but I figure I'd make the issue now that it's come up again.

#### Server revision

ffcf7e7b7b8ef8004827d7e95cdf7dad1fd50ded

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
There's three starting positions on box as well.

**Comment by Killette2** [comment]
I think this is intentional to allow latejoining of a job. It's also like this for botanist (2/3 slots) and I believe many other jobs

**Comment by Shadowmech88** [comment]
Still, it might make more sense if the extra slots weren't available right at roundstart.
