### ISSUE TITLE
Silver slime cores can spawn "Deep Fried Foods Holder Obj"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16068]
(WEB REPORT BY: ch0c0latem00se REMOTE: 172.93.109.202:7777)
# Revision
ffcf7e7b7b8ef8004827d7e95cdf7dad1fd50ded

# Description
Silver slime has a chance to spawn some weird coder bullshit food
# Steps to Reproduce

# What you Expected

# What Actually Happened
https://media.discordapp.net/attachments/184815377329422336/361379242375643141/unknown.png

**Comment by Exxion** [comment]
Should use `existing_typesof()`
If it does, then this obj should be changed to have a null `icon` or whatever
