### ISSUE TITLE
Mineral stacks deleting previous stack on tile is back

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16083]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)
# Revision
30fb5f429fc18d435fd3adbe989ce423facb3d29

# Description
Whenever printing minerals with the borg/mommi matter synths or hatcheting logs at the least, once you pass one stack it deletes the old one

# Steps to Reproduce
Be a borg/mommi and start synthing multiple stacks on the same tile or,
Have an ass ton of logs near you and hatchet more than 100 planks worth

# What you Expected
To not delete the previous

# What Actually Happened
My 101 planks became 49+2 after harvest

**Comment by Kurfursten** [comment]
Something like this appeared to have occurred with stacks of sandstone this morning

**Comment by DrSnips** [comment]
Similar issues with stacking, ejecting a sheet of something and then another before you move the first sheet causes it to delete the old sheet from on top of the proto/auto lathe. Likely that similar machines have this issue too like the exosuit fab. Stack code is at it again.

**Comment by DamianX** [comment]
Great. I'll look into it.
