### ISSUE TITLE
Spears are invisible.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16094]
(WEB REPORT BY: delightedmerchant REMOTE: 172.93.109.202:7777)
# Revision
a433a426c0fcecd413a7d9b2d5f07aec95a56347

# Description
Spears are invisible when held.
# Steps to Reproduce
Hold a spear.
# What you Expected
A visible spear.
# What Actually Happened
The clown did not see my spear. I did not see it either.

**Comment by Exxion** [comment]
Yep. Inhands are still fucked.
@DrSnips

**Comment by DrSnips** [comment]
Yeah, I did it wrong I guess with my last try at fixing it. I will try yet again. If that doesnt work, its likely someone better tries to fix it.
