### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16137]
(WEB REPORT BY: pump1234 REMOTE: 172.93.109.202:7777)
# Revision
65b1f7c0f3a5040956e06a2e61153806dc6072c8

# Description
Typo for Sec suit storage as "Segurity Suit Storage Unit"
# Steps to Reproduce
1.Look at the suit storage unit
2.???
3.Profit
# What you Expected
"Security Suit Storage Unit"
# What Actually Happened
"Segurity Suit Storage Unit"

**Comment by DamianX** [comment]
Fug :DD

**Comment by DrSnips** [comment]
Fug

**Comment by SysadminJeroen** [comment]
![blasma](https://user-images.githubusercontent.com/2915526/31046878-1b57e490-a601-11e7-842e-a6c1e09a6704.png)

**Comment by SonixApache** [comment]
seguridy :DDD

**Comment by DamianX** [comment]
~~@CptWad AAAAAAA WHY DID YOU MAKE IT A SPECIAL SNOWFLAKE MAPPED VAR~~
Nevermind, it was @PromethTK11 

This seems to be the case only for packed station.

**Comment by CptWad** [comment]
![disstressed dolphin](https://user-images.githubusercontent.com/3959840/31054068-739bec24-a65f-11e7-8dfc-39133a734c13.gif)
ya didnt check ya proofs

**Comment by PromethTK11** [comment]
Fugg

@DamianX I wanted them to be different cuz they're in the same room as the standard suits
