### ISSUE TITLE
Dwarven Vendors Broken by Ads

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16141]
#16122 refactored vending machine ads, but failed to account for the vendor that isn't in vending.dm, the mining vendor in mine_vending.dm

Because the mining vendor has a string of ads instead of a list of strings for ads, it causes runtimes rendering the entire machine unusable, meaning you cannot get any pokemon toys, KPAs, jetpacks, etc.

@DamianX

**Comment by SonixApache** [comment]
fucking snowflake code

**Comment by Kurfursten** [comment]
It's not so much snowflake code as a snowflake file

I suppose the idea is to keep all the mining stuff in one place.
