### ISSUE TITLE
Chefs cleaver no long gibbing people

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#16159]
Pretty self explanatory.

**Comment by ghost** [comment]
I saw it successfully gib several people less than a week ago, so if it actually is broken, that implies it was fairly recent.
That being said, kitchen.dm hasn't been touched in 80 days.  Is there any more information about what happened when it failed to gib?  Race, intent, etc.

**Comment by Exxion** [comment]
Apparently the code for the cleaver gibbing people isn't *in* `kitchen.dm`.
It's in `human_defense.dm` because someone didn't understand how to code properly.

But that file hasn't been touched in six months

**Comment by ghost** [comment]
Because _of course_ it is.
Regardless, I asked him on Discord and he said he didn't realise he needed to be on harm intent, so I guess that's that mystery solved.  Issue closed?
