### ISSUE TITLE
the pictures for blue-white in the tile painter are completely broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16166]
(WEB REPORT BY: delightedmerchant REMOTE: 172.93.109.202:7777)
# Revision
bc93863334adff0021c256f52d0da1b3b405e0aa

# Description
see title
# Steps to Reproduce
set tile painter to blue-white
# What you Expected
pictures
# What Actually Happened
where are the pictures

**Comment by Eneocho** [comment]
works now
