### ISSUE TITLE
Captain EVA cant be cleaned

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16168]
(WEB REPORT BY: alandemarest REMOTE: 172.93.109.202:7777)
# Revision
bc93863334adff0021c256f52d0da1b3b405e0aa

# Description

Captain's space suit armor can't be rid of toxins/radiation after plasma contamination

Can't be inserted into washing machine or suit storage for disinfection

# Steps to Reproduce

Contaminate the suit, try to clean

# What you Expected

to be able to clean

# What Actually Happened

Couldnt clean

**Comment by Kurfursten** [comment]
Use bleach, cap has access to chemistry!

However if someone wants to make an EVA tube for it, I'll sprite a blue SSU

**Comment by DamianX** [comment]
Duplicate #14274
