### ISSUE TITLE
Atmospheric Meters readout glitch

### ISSUE THREAD

**Issue by AnonymouxRex** [d3athrow/vgstation13#1616]
I observed over two rounds that two different meters in Atmospherics have demonstrated erratic reading behavior.  Here is a sample of readings taken during a round from the atmospherics distribution loop meter:

The pressure gauge reads 1200.47 kPa; 293.12°K (19.97°C)
The pressure gauge reads 1205.65 kPa; 293.12°K (19.97°C)
The pressure gauge reads 955475 kPa; 293.12°K (19.97°C)
The pressure gauge reads 955475 kPa; 293.12°K (19.97°C)
The pressure gauge reads 955475 kPa; 293.12°K (19.97°C)
The pressure gauge reads 955475 kPa; 293.12°K (19.97°C)
The pressure gauge reads 955475 kPa; 293.12°K (19.97°C)
The pressure gauge reads 1210.79 kPa; 293.12°K (19.97°C)
The pressure gauge reads 1210.79 kPa; 293.12°K (19.97°C)
The pressure gauge reads 1210.79 kPa; 293.12°K (19.97°C)

From what I can tell, it is not causing any harmful behavior in the atmospherics systems but that might be due to its transient behavior.  I also observed it occurring on the waste line meter during a meteor round earlier in the evening.

**Comment by d3athrow** [comment]
Really no good way to fix this.

**Comment by clusterfack** [comment]
I think I fixed this anyway when I changed pipecode by using update_values
