### ISSUE TITLE
Surgery sometimes requires multiple clicks

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#16169]
#### Description of issue
Sometimes organs don't go in
sometimes using a tool requires multiple clicks

#### Difference between expected and actual behavior
working on the first click

#### Steps to reproduce 
do various organ transplants or basic surgery

#### Length of time in which bug has been known to occur

![image](https://user-images.githubusercontent.com/22992659/31206975-e7f47256-a940-11e7-9e4a-9dbfaafb62e4.png)

pic related
i forgot to press the bug report button but i remembered i had a screencap saved
the tools not working might have been my bad but this definitely doesn't work properly
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
maybe it was because of server lag?

**Comment by Exxion** [comment]
What kind of table was he on?

**Comment by Kurfursten** [comment]
Did you move? What intent were you on?

**Comment by ghost** [comment]
Use a surgery table you heathen

**Comment by Cyadox** [comment]
I'll take a look since I touched surgery code recently. I doubt its anything more than the random failure chance you get when using a regular table though.

**Comment by Shadowmech88** [comment]
Isn't that a chance to fail at performing the surgery step though, not a chance to just not attempt the step at all?

**Comment by Cyadox** [comment]
@Shadowmech88 Yes, and you are supposed to get an appropriate chat response, such as 'You slip and mangle the organs', ~~but I can't see it being anything else except being on the wrong intent.~~

EDIT: Intent was HELP it seems:
[17:09:38]ATTACK: <font color='red'>Nigata Komaeda(sandysand) attacked Desmond Maxans(greatimperator) with advanced lungs. (INTENT: HELP) (DAMTYE: BRUTE)</font>
[17:09:39]ATTACK: <font color='red'>Nigata Komaeda(sandysand) attacked Desmond Maxans(greatimperator) with advanced lungs. (INTENT: HELP) (DAMTYE: BRUTE)</font>
[17:09:46]ATTACK: <font color='red'>Nigata Komaeda(sandysand) attacked Desmond Maxans(greatimperator) with advanced lungs. (INTENT: HELP) (DAMTYE: BRUTE)</font>
[17:09:47]ATTACK: <font color='red'>Nigata Komaeda (sandysand) used the advanced lungs to perform surgery type /datum/surgery_step/internal/replace_organ on Desmond Maxans (greatimperator)</font>
[17:09:53]ATTACK: <font color='red'>Nigata Komaeda (sandysand) used the advanced lungs to successfully complete surgery type /datum/surgery_step/internal/replace_organ on Desmond Maxans (greatimperator)</font>

**Comment by Exxion** [comment]
There are like four different things that can cause surgery steps to fail. You get a message if it fails due to an inadequate tool, but if the table is inadequate, you just attack the person with the tool
That's why I asked what kind of table it was on
Because unless it was a surgery table, this is not a bug
Poor design, maybe, but not a bug

**Comment by Hugh-G-Rection** [comment]
ADMIN: HELP: Is virologist antag? Cause he just beat me into crit with my own liver

**Comment by ghost** [comment]
It was on a roller bed.

**Comment by Cyadox** [comment]
> It was on a roller bed

I'm *pretty sure* there's a fail chance with surgery on a roller bed. It's bad that there's no feedback to tell you, but you really should have thought of that one.
Also explains why your tools weren't working 100% of the time.

**Comment by Exxion** [comment]
Leaving it open because, while not a bug, still probably worth at least adding a failure message

**Comment by Cyadox** [comment]
Should it be the same failure and consequences (damage, etc) as if you're using an unsuitable tool, or just a total failure?

**Comment by ghost** [comment]
maybe give a message that the rollerbed slides while you try to perform surgery

**Comment by WhiteHusky** [comment]
Generally the fail chance should increase instead of doing an attack. I've killed someone while doing non-Nanotrasen sanctioned surgeries in one of the dorms over the fact that the RNG would repeatedly and almost without fail apply the hatchet violently at the chest of the person and not their ribs.
