### ISSUE TITLE
Item: Colt Single Action Army Revolver

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16173]
(WEB REPORT BY: dekarflamon REMOTE: 172.93.109.202:7777)
# Revision
096ba9ea51d1afa19420f41eec2e0ad892f3df2a

# Description

Colt Single Action Army Revolver wasnt working correctly. Attempted to fire and would not even when loaded with bullets. captain eventually managed to get it to work.

# Steps to Reproduce
Get ocelot syndicate bundle. Attempt to shoot Colt Single Action Army Revolver.

# What you Expected
It to fire when you tried to shoot it.

# What Actually Happened
It didnt.

**Comment by Exxion** [comment]
*This* one is not a bad report.

**Comment by Intigracy** [comment]
The problem is that clicking it while it's inhand takes a bullet out, as opposed to cocking it like the hotkeys for attack_self do.

You HAVE to use hotkeys (pagedown or z) to cock it.

**Comment by Exxion** [comment]
What the fuck

**Comment by Shadowmech88** [comment]
I've got no idea why that would be, clicking it while it's in-hand should call the same proc as the hotkey.
Who doesn't use hotkeys for `attack_self()`, anyway?

**Comment by Blithering** [comment]
I don't use hotkeys, so I'd probably have the same problem, I also found using pAI medibot functions a pain for similar reasons. Could action buttons be implemented for these things?

**Comment by Shadowmech88** [comment]
Even if you don't use hotkey *mode*, why wouldn't you use the standard hotkeys like pageup, pagedown, et cetera?

**Comment by Blithering** [comment]
Due to lack of indication as to their purpose in each instance I suppose.

**Comment by Allspice** [comment]
It's probably that clicking the pistol with the offhand that removes a bullet, and click with active hand that cocks it, like how offhand click plastic-bag opens the storage and active hand click dumps it.

**Comment by Blithering** [comment]
If that's the case then its consistent with other weapons that require cocking between shots like the shotgun.

**Comment by Exxion** [comment]
Yeah, Intigracy is right
Somehow, you unload a bullet if you click it in your hand (yes, with it in your active hand), but cock/spin it if you use either key

**Comment by Exxion** [comment]
There we go.
The SAA has a second arg to its `attack_self()` that calls the parent if truthy. The parent unloads a bullet casing. Alt+clicking on the SAA calls `attack_self()` with the second arg set to true, which is how you're supposed to unload bullets from it.
Problem is, `attack_self()` already *has* a second arg. It's `params`, and deals with where on the item you clicked, or something. `params` always has a value when you *click* on the item in your hand, but does not if you use a hotkey. (You didn't click on it, so there's no location information for it to hold.)

As far as I know there's only the one `params` var, so adding `var/params` between the other args [here](https://github.com/vgstation-coders/vgstation13/blob/ae6fd08cc7f364e74ee22f0349f84a6e4c2a26cd/code/modules/projectiles/guns/projectile/revolver.dm#L252) and specifically naming the second arg [here](https://github.com/vgstation-coders/vgstation13/blob/ae6fd08cc7f364e74ee22f0349f84a6e4c2a26cd/code/modules/projectiles/guns/projectile/revolver.dm#L269) should fix it
