### ISSUE TITLE
The R glass in AI construction is still acts like it's in your hand after application.

### ISSUE THREAD

**Issue by DrSnips** [d3athrow/vgstation13#16172]
When you apply the R glass to a new AI core you act like you still have the glass in hand. The sprite vanishes but say you try and pick up something else like your tools and it's like you still have the glass in hand. You can drop whatever is in hand to rid the invisible thing. I had only 2 sheets of R glass in hand before using it on the AI core.
This has happened several times in the past and I assumed it was just due to stacks being bugged but it's still an issue so it's likely a bug in the core construction.

**Comment by Cyadox** [comment]
I can confirm this as well, I was experiencing it while attempting to fix #16097. As far as I could tell, it's an improper call that causes the item to... semi-delete?

From what I could figure from VVing the stack, it gets sent to garbage collection but never fully gets there, so you get weird stuff like the sprite disappearing but still occupying a hand slot, being able to throw or drop it (and have the item actually be there while still 'invisible').

**Comment by Exxion** [comment]
Presumably, it is deleted, but not dropped, so your hand still holds a reference to it

**Comment by Shadowmech88** [comment]
This same problem happened with wood plank stacks in peg surgery.
It's possible that stacks in general are broken somehow.
