### ISSUE TITLE
Pintpointer doesn't track the person who made the drink

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#16189]
#### Description of issue
Pintpointer doesn't track the maker of the drink as intended. Simply shows the beer mug icon. Drink was also dropped on the ground I believe, so it may have been because my hands were full.

#### Steps to reproduce 
Create Pintpointer in hands as normal. In this case, a borg handed me a Syndie bomb and Atom bomb they had made themselves, and I mixed them together normally.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
The fullness of the beer icon on the Pintpointer's screen indicates how close it is to the person it's tracking.

**Comment by Cyadox** [comment]
@Shadowmech88 
My mistake then, I assumed it would work like the pinpointer's arrow.
