### ISSUE TITLE
Bagel: Tcomm Computers are not configured to tcommsat network

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16188]
It's trivial to fix for anyone who understands tcomms, but it would throw off people who just uses the computers.

It's also possible it was sabotaged that shift but Bagel is only one in like ten rounds so it's hard to verify

**Comment by Hugh-G-Rection** [comment]
It's not sabotage, it definitely starts without the tcommsat buffer, and I only know this after at least three rounds of thinking someone had sabotaged it.
I never minded it, because it keeps your average greyshirt or AI from uploading ~Nyah to common, but it is technically a bug.

**Comment by Kurfursten** [comment]
You don't actually have to configure the traffic control computer, which is the one that has scripts.

The two that need to be configured are the server monitor (which leads you read radio records) and the telecoms monitor (which lets you remotely view all tcoms connections in the net)
