### ISSUE TITLE
Unsecured Welders Need Proper Failtext and Better Examine Text

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16191]
**Updated**

If you accidentally unscrew your welder, there is no examine text showing it's unsecured, it can't be turned on, and its fail text says it's out of fuel instead of unsecured. Also the sprite doesn't change, of course, so there's little way to tell.

**Comment by ghost** [comment]
I had the same issue and confirmed it was utterly fucked by asking another player to try using it - they couldn't turn it on either.  I also use fuel cans almost exclusively, but I've only seen it happen very recently.

**Comment by Kurfursten** [comment]
Things that definitely do **not** cause it, from my testing
* Using up all the fuel and then refilling at a welding tank
* Using up all the fuel and then refilling from a fuel can
* Attempting to weld something you do not have enough fuel for
* Running out of fuel welding apart a window, welding shut a locker
* Attempting to refill a welder from an empty fuel can
* Queuing up welding jobs that would take more fuel than you have available and completing those jobs successfully (in cases like welding windows, the check only looks for 0 fuel but then subtracts one at the end using the remove_fuel proc, which is safe and can't go negative)
* Queuing up welding jobs that would take more fuel than you have available and failing due to lack of fuel (some jobs like welding down the RUST fuel injector require 3 fuel and check that you have it before finishing the weld job)
* Allowing the welding tool to run out of fuel via its process()
* Running out of fuel via hitting things that are not weldable, such as uncrowbarred floortiles, metal chairs, mobs, etc.
* Putting a welding tool in your toolbelt / refilling the welding tool while it is in your toolbelt with a fuel can

**Comment by Blithering** [comment]
Did you try securing it with a screwdriver?

**Comment by Kurfursten** [comment]
Amazing. You're right.

So to recap, if you accidentally unscrew your welder when sticking your screwdriver back into your toolbelt...

* The welder won't work anymore
* There is no examine text suggesting the problem is that it's unsecured
* It gives you failtext about being out of fuel instead of being unsecured

Great call Blithering

**Comment by ghost** [comment]
it was unsecured?!
OH WHAT THE FUCK
_AAAAAAAAAAAAAAAA_
