### ISSUE TITLE
Mice can remove corn oil from the deep fryer.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16207]
(WEB REPORT BY: meetmeindorms REMOTE: 172.93.109.202:7777)
# Revision
d8f0d2a4432b0bc60c0b2fb627177be8be7e525f

# Description
Mice can remove corn oil from the deep fryer.

# Steps to Reproduce
Be a mouse
Right click the fryer
Remove ingredients
Wait

# What you Expected
I didn't expect a thing.

# What Actually Happened
Empty fryer.

**Comment by SonixApache** [comment]
sanity/mousehands

**Comment by Exxion** [comment]
I don't feel like doing the label trick
