### ISSUE TITLE
Jukebox begins to play "9D5D37E30E4F6766BE6D1A3BE7F5C076", by r nparacepRoyppMs, from ' Deudn mu4S lVMok aYc0roNTt-'. 

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#16206]
#### Description of issue
Jukeboxes don't properly announce their songs or playlists or whatever.
Not sure if this is intended behavior, and not sure if this is only the case for certain types of jukes -- have yet to reproduce it properly.
`Jukebox begins to play "9D5D37E30E4F6766BE6D1A3BE7F5C076", by r nparacepRoyppMs, from ' Deudn mu4S lVMok aYc0roNTt-'. `

#### Difference between expected and actual behavior
`Jukebox begins to play "9D5D37E30E4F6766BE6D1A3BE7F5C076", by r nparacepRoyppMs, from ' Deudn mu4S lVMok aYc0roNTt-'. `
vs
`Jukebox begins to play "Some Song", by Some Guy, from 'Some Place'. `

#### Steps to reproduce 
Play a song on the juke on the live serb

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/77eeef2eeb17262fd315959ecf39ac05e5d18cfe/code/modules/media/jukebox.dm#L102
maybe?

#### Length of time in which bug has been known to occur
Goonchat? I vaguely recall this being fixed at some point.

#### Server revision
01cf594e56f2e598c0a89c678b93cf54491687f1

**Comment by MadmanMartian** [comment]
Hacked juke?

**Comment by SonixApache** [comment]
I noticed it on a round of extended on packed with the goonsat untouched, so I doubt it'd been emagged. Does hacking it produce that kind of effect?

**Comment by MadmanMartian** [comment]
yes, could also have been one of the vidya playlists

**Comment by clusterfack** [comment]
```

I'm A Gangsta | Rappy Mcrapperson | YTMND Soundtrack - Volume 04 | 9D5D37E30E4F6766BE6D1A3BE7F5C076
-- | -- | -- | --


```
from the emagged jukebox

**Comment by clusterfack** [comment]
Pretty obvious it takes the md5 hash as the songname and scrambles the author and soundtrack

**Comment by ghost** [comment]
Yeah, it was hacked, and hacked jukes always do that.

**Comment by SonixApache** [comment]
Seems to be a feature.
