### ISSUE TITLE
flavotext dont works

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16208]
(WEB REPORT BY: cadaverouscoyote REMOTE: 172.93.109.202:7777)
# Revision
d8f0d2a4432b0bc60c0b2fb627177be8be7e525f

# Description

flavor text can't do semicolons or ampersands. probably other shit, too. it completely cuts off anything past the point they're used.

# Steps to Reproduce

set your flavor text with an ampersand or semicolon somewhere in the middle of it.

# What you Expected

Raised by condors from a babe in the Andean mountain range; he stands 5'7 & 1/2" due to malnutrition as a child from a meager diet of carrion and cavy. Being a 1/2 dalo-faelid, 1/4 spanish, 1/8 chinese, 1/8 quechua mix, his purported whiteness is in question. As an Aries, he's enthusiastic, energetic, impulsive, and the first to push boundaries. Doesn't like being called Deangelo but doesn't really hate it either. Enjoys long walks away from the beach, keeping his third eye wide, being obtuse, his bodily functions, and other peoples' bodily functions. You know all of this because it's tattooed on his paunch.

# What Actually Happened

Raised by condors from a babe in the Andean mountain range

**Comment by Intigracy** [comment]
flavor text was a mistake

**Comment by cadaverouscoyote** [comment]
"fixing" flavor text was the mistake

**Comment by Kurfursten** [comment]
You put that much work into writing your character's backstory but couldn't be bothered much with the report title. 🤷‍♂️

**Comment by TheFriggenSawbones** [comment]
his flavor text matters more please fix it collabs
