### ISSUE TITLE
Grab dragging is broken

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16214]
#### Description of issue
It used to be (few months ago at most) you could drag mobs you had in a grab as a way to avoid causing drag damage at the cost of slower speed. (A method Sonix intended to work when drag damage was re-implemented.) Nowdays moving away while maintaining a grab does this awkward thing where you take a slow step away. The slow move rate is still being applied so whether this was an intentional change or not, it feels like a bug.

#### Length of time in which bug has been known to occur
Past few months at most.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
Grabbing picked up a lot of weird issues a while ago, not sure what caused it.
Definitely wasn't an issue when I implemented initial drag damage, though.
