### ISSUE TITLE
Flavour Text

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16213]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
5de1c9061fde2ed461b00b58c949f2cca3843ced

# Description
putting an apostrophe breaks the flavour text
# Steps to Reproduce
put an apostrophe in your flavour
# What you Expected
isn't
# What Actually Happened
isn&#39;t

**Comment by DamianX** [comment]
really now?

**Comment by DamianX** [comment]
![image](https://user-images.githubusercontent.com/6307265/31474464-467da706-aefb-11e7-8191-470f73c362be.png)

**Comment by Riekland** [comment]
oh my fucking christ
okay epic
it's supposed to be complaining about how I get the html thingie that's &# 39 instead of a '

**Comment by DamianX** [comment]
Okay, I'm half-asleep right now but can you try just re-submitting the flavor text in the preferences? The way flavor text is sanitized changed and that might be what's happening here. I'll do some more testing tomorrow.

**Comment by Riekland** [comment]
Looks like resubmitting it fixed it
I should have probably tried that before I complained
arigato

**Comment by DamianX** [comment]
It's actually something other people will run into and I'm not sure what the best course of action is.

**Comment by Hugh-G-Rection** [comment]
So long as we'rd griping about &#;39, is there any chance we can visit the issue about it appearing in comms any time text runs through a script?
I used to use a content replace ("&#;39", "'") at the end of every script to fix it, but that broke recently, so it's easy for people to tell when a script is running and it's mildly immersion breaking.

**Comment by DamianX** [comment]
Make a separate issue, please.

**Comment by Shadowmech88** [comment]
So is this not a bug, or is it technically a bug but with an easy way to fix it in-game?

**Comment by DamianX** [comment]
Players that set their flavor text before the latest fix PR will have a mildly fucked up flavor text until they re-submit it through the preferences.
