### ISSUE TITLE
Suggestion: Hitting people with clothing should extinguish them

### ISSUE THREAD

**Issue by WhiteHusky** [d3athrow/vgstation13#16224]
Hitting people with jackets or jumpsuits or anything similar should have a chance of putting them out on a 'HELP' intent so you can help your fellow, downed spessmen who is burning in a bright blaze.

**Comment by ShiftyRail** [comment]
I can try that, but can you tell me how to, reliably, set people on fire ? In order to test it I need to set a monkeyman, for exemple, on fire on a test server.
Most ways end up causing too much collateral damages.

**Comment by ghost** [comment]
Just throw some welding fuel on the floor and light it, won't kill them.

**Comment by Exxion** [comment]
Pie tin fires aren't hot enough to even directly deal damage unless you include another flammable thing
Though the very state of being on fire will start to deal damage after several seconds

Or you could just use a local server where you're an admin and use a test dummy, since they're "invincible"

**Comment by Sooose** [comment]
Could always just walk through a lite campfire.
