### ISSUE TITLE
Thrown items being caught still hit the person

### ISSUE THREAD

**Issue by WhiteHusky** [d3athrow/vgstation13#16225]
#### Description of issue

Catching a thrown item causes the item still register getting hit by the item.

#### Difference between expected and actual behavior

Catch the item without getting damaged, instead the item still caused harm.

#### Steps to reproduce 

Get your fellow spessman and ask them to begin throwing with a empty hand. Throw your fellow spessman a toolbox and watch them catch the toolbox while at the same time getting clocked by it.

#### Length of time in which bug has been known to occur

Noticed it recently, could've been happening for a while since catching items is not usually known by anyone else, even though it shows itself useful for the occasional odd situation.

#### Server revision

Game: 0fbc931a5b873a9ec1fdf5f2168ed850286a4653 
Patches: d906516f81933e3d174db4567c16a7fbf960ebe6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
Possibly #16124?
