### ISSUE TITLE
Null rod runtime on attack

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#16236]
[03:47:18] Runtime in null_rod.dm, line 47: Cannot read null.vampire
proc name: attack (/obj/item/weapon/nullrod/attack)
usr: Prospero Wang (kamen132) (/mob/living/carbon/human)
usr.loc: The floor (296, 254, 1) (/turf/simulated/floor)
src: the saint katana (/obj/item/weapon/nullrod/sword/katana)
src.loc: Prospero Wang (/mob/living/carbon/human)
call stack:
the saint katana (/obj/item/weapon/nullrod/sword/katana): attack(Unknown (/mob/living/carbon/human), Prospero Wang (/mob/living/carbon/human))
Unknown (/mob/living/carbon/human): attackby(the saint katana (/obj/item/weapon/nullrod/sword/katana), Prospero Wang (/mob/living/carbon/human), "left=1;screen-loc=7:15,7:11", null)
Prospero Wang (/mob/living/carbon/human): ClickOn(Unknown (/mob/living/carbon/human), "left=1;screen-loc=7:15,7:11")
Unknown (/mob/living/carbon/human): Click(the floor (295,253,1) (/turf/simulated/floor), "mapwindow.map", "left=1;screen-loc=7:15,7:11")
Unknown (/mob/living/carbon/human): Click(the floor (295,253,1) (/turf/simulated/floor), "mapwindow.map", "left=1;screen-loc=7:15,7:11")

**Comment by DamianX** [comment]
Doesn't happen for most other `isantag()` macros because they just do `H.mind in list`, as opposed to `isvampire()` that also also checks for `H.mind.vampire` but doesn't take into account that `mind` might be null.
