### ISSUE TITLE
Treading a Cigarette causes the '[...]You push it back into place.' message along with putting it out.

### ISSUE THREAD

**Issue by WhiteHusky** [d3athrow/vgstation13#16239]
![](https://i.imgur.com/1RTWMrL.png)
#### Description of issue

Treading a Cigarette causes the message you get when you try to move your headgear into a position that is not supported.

#### Difference between expected and actual behavior

Tread on the cigarette and nothing more, but the character attempts to move it into a different place and fails doing so while treading on the cigarette.

#### Steps to reproduce 

Get a cigarette and attempt to put it out by using it in your hand.

#### Server revision

Game: 49b1a27315ef488b816e9051f827bdf106758031
Patch: d906516f81933e3d174db4567c16a7fbf960ebe6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
*Should* be as simple as removing the `..()` in cigarettes' `attack_self()`
