### ISSUE TITLE
New gamemode idea

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16235]
Since we already have wizards coded, we should make a special game mode involving wizards where only one of them is spawned for the entire round. This can seem like a groundbreaking new concept, but if we code this new gamemode we have the opportunity to more easily do stealth wizards or "mastermind" type wizards where one antagonist controls the flow of the round rather than it be a chaotic mess every time. Although wizard isn't supposed to be the most serious mode to begin with, I think a new mode like this would be a good addition to the rotation instead of multiple wizards clashing together in the same round unwantedly.

**Comment by SonixApache** [comment]
wiztended sux

**Comment by Hugh-G-Rection** [comment]
And perhaps when this wizard dies, thus ending potential interest in the round, it could end the way MALF does on AI defeat? That would be crazy.
In all seriousness I miss 5 minute rounds where the wizard fireballed himself while still in the treehouse, or because Vox wizards didn't spawn with breathmasks.

**Comment by Exxion** [comment]
>vox wizard round
>5 minutes

More like 5 seconds

**Comment by Killette2** [comment]
Honestly I'd rather have a 1/3rd chance of wiztended rather than wizard be a shitfest teamdeathmatch every single time

**Comment by SonixApache** [comment]
i'd rather just have extended than extended + (magically-induced) non-antag shitlery

leave that last one up to the gods

**Comment by Shadowmech88** [comment]
After antag datums are completed, we could explore possibly bringing back one-wizard rounds and then simply spawning another wizard or a different antag type altogether once the wizard is dead, rather than letting it turn into wiztended.

**Comment by Killette2** [comment]
Would it be like the fabled tensioner so you get a little bit of piece and quiet after the wizard dies before xenobloblings?

I also remember there being a gamemode on LLA before it shut down called wizard+traitor. That could also be an easy fix, after adjustments are done to prevent meta such as wizard+vamp/trait/ling

**Comment by Exxion** [comment]
It wouldn't be *like* the tensioner, because that implies that it wouldn't *be* the tensioner

**Comment by Killette2** [comment]
Then what's wrong with mixed if it went lighter on the amount of the 2nd antag when a serious one like wizard is involved?

**Comment by Aurx** [comment]
I'm of the opinion that there should be traitors in all roundtypes except extended.

**Comment by Killette2** [comment]
Except team gamemodes

**Comment by SonixApache** [comment]
wiztended sux
having the entire chaos covered in blood and chaos with everyone armed hunting for things that don't actually exist also sux

**Comment by Killette2** [comment]
wiztended sucks indeed but the issue I'm raising here is that any gimmick/themed/roleplay wizardry is currently impossible when you have this many other people with magical powers wanting to do their own thing.

**Comment by Aurx** [comment]
If your gimmick isn't hot shit, you should be able to use the magic of communication to get the other wizzymen involved.  
Or just murder their dumb asses on the station, declare yourself the wizlander, and get chloraled while roleplaying as a lesbian 14yo nipponese schoolgirl.

**Comment by Killette2** [comment]
Then why did ops need an admin enforced commander role due to so many shitters ruining everything?
🤔

**Comment by Aurx** [comment]
Big difference between four people, none of which you can kill if they're retards, and one maybe two people who you can valid at the drop of a hat.

**Comment by Killette2** [comment]
Then not only do you need spells that go with your gimmick and are effective against other wizards, but if I hurt other wizards I'd feel bad and like a douche :(
wizard on wizard violence is worse than changeling on changeling

**Comment by Killette2** [comment]
Any different opinions after 69 wizard rounds today?

**Comment by aceedex** [comment]
I miss single wiz
Whats the point of ragin' mages if wiz is as it currently is

**Comment by Killette2** [comment]
For even more wizards
