### ISSUE TITLE
Vent/Scrubber in Toxins Storage facing wrong way (Deff)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16248]
(WEB REPORT BY: cyadox REMOTE: 172.93.109.202:7777)
# Revision
9581b7d21e6a406b19679d154d87da250cfe2187

# Description
Both the Scrubber and Vent in Toxins Storage spawn on the map facing east instead of west, and therefore aren't connected to their respective pipe networks.

**Comment by Cyadox** [comment]
Also there's a pipe section missing in the cloning room, the straight piece that goes under the window.
*Assuming* it wasn't damaged, anyways.
