### ISSUE TITLE
Idea : random tips in lobby splashscreen

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#16252]
Everyone knowns that spessman is relatively complex and that a lot of mechanics have been coded but are hard to find or straight-up undocumented on the wiki.
This can cause people to be quite incompetent and must be really frustrating for any newcomers and seasoned players alike. (Like how many people just don't know about the 'resist' verb)

In most modern games nowadays there are some random tips being offered when the game is loading. I suggest we do this in the lobby, while people are either waiting for the round to start or are busy setting up their characters.

Of course, it should be toggeable so that hardcore spessmen aren't distracted from pre-round OOC shitposting by silly tips.
It should also be quite straight-forwards and basic tips, so that people can still discover the game by themselves.

I was thinking of making it a little window with a little "Next Tip" button but that would make 3 little windows at roundstart and maybe it would be annoying. Idk.

Ideas of the kind of tips
>Command : if you are the only head of staff at roundstart, you are considered acting Captain. It is your duty to prevent people from stealing the important items.
>Medical : a "mental interface failure" message when cloning indicates that the player has disconnected. A "subject might be braindead" message indicates that the player is still online, but not on his body at the current moment.
>Security : remember that your job here is to arrest people, not murdering them. Read the wiki about Space Law for more information.
>General : you can force open firelocks with a crowbar. But be careful, a flashing firelock indicates that the room is probably not safe to walk into.
>General : if you are venturing in a room with a significant difference of pressure, be sure to wear magboots and a hardsuit.

**Comment by Aurx** [comment]
But that security tip is outright wrong.

**Comment by ShiftyRail** [comment]
It would of course need better formulating but you get the idea

**Comment by DamianX** [comment]
![1402251071820](https://user-images.githubusercontent.com/6307265/31597586-7ec5b1d4-b249-11e7-8b32-6d1cb81e3e97.png)

But yes.

I like the idea, I'd make it something like a highlighted text near the MOTD or similar.

**Comment by ghost** [comment]
this is a feature on TG and TG derivatives so it should be simple enough

**Comment by ShiftyRail** [comment]
https://github.com/tgstation/tgstation/blob/master/code/modules/tooltip/tooltip.html

This is how tg does it. Which is smart because JS is entirely client side.

**Comment by Riekland** [comment]
fucking casual

**Comment by Hugh-G-Rection** [comment]
General: It's important to stay fed in space. Remember to eat any food you find on the ground as fast as possible.
General: When someone is teaching you a new job, take detailed notes. Be sure keep a pen in your hand while standing directly next to them.
Janitor: Always remember the ABC of janitorial duties, Always Be Cleaning! When there's nothing else to do, be sure to mop in high-traffic areas to show everyone your dedication to station cleanliness.
Chemist: Remember that Medical Cyborgs don't have hands to pick up pills. To make things easier on them, make everything into bottles instead of pills.
Silicon: It's your job to help and assist any and all human crew-members, regardless of job or rank. Until they take you off Asimov, then its your job to make them pay for their foolishness!

**Comment by ShiftyRail** [comment]
@Riekland thanks for the wonderful feedback as usual. You truly are a jewel on this repository

**Comment by ghost** [comment]
PROTIP: To defeat the Syndicate Agent, shoot it until it dies.

**Comment by Blithering** [comment]
Just as long as there's one that tells people that comments like 'wtf how did I just die and what's a proboscis' go in ahelp not OOC

**Comment by ShiftyRail** [comment]
Could be, but people who come in and don't even read the rules don't really deserve to play tb'h

**Comment by FudgePucker** [comment]
General: Space is dangerous, please don't smash external windows.
General: Space Lube is a useful tool to bring joy and laughter to the station. Just splash it on the floors and watch hallways become slip and slides! Everybody will enjoy the fun new way to get around the station and will want to find you and ~~murder you and toss your corpse into space~~ give you praise for bringing joy to the station. Honk
Engineering: Don't open firelocks unless you know what you are doing. You will only get yourself killed and make the situation worse in an emergency.
Engineering: turn on the shielding before turning on the partial acceloratior when setting up the singularity.

**Comment by SonixApache** [comment]
>resist verb

there's a resist UI button
