### ISSUE TITLE
Bugs are bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16268]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
# Revision
8984ad596abd59f4e21c488640f4fd58d4feba9d

# Description
Camera bugs are horrendously broken, can be placed on anything within sight range, except for certain items that seem to have been specifically coded not to work. They can also be placed on things like scrubber pipes that are only visible through Tray scanners, and OTHER CAMERA BUGS. Testing revealed they cannot be placed using cameras to extend your vision, so that's something I guess.
# Steps to Reproduce
grab camera bugs, click anything on the screen
# What you Expected
bugs to be sane
# What Actually Happened
bugs be buggin', will post a screenshot to show just how bad

**Comment by Blithering** [comment]
![camera bug](https://user-images.githubusercontent.com/15067109/31695556-4ce8371c-b3a3-11e7-898d-37fdf402ecc0.png)
Also note that all this was done while staring through a closed window into robotics.

**Comment by ShiftyRail** [comment]
Is it going to conflict with the PR that improves bugs if I try to sanitise it a bit
Might be talking utter bollocks but wires T-Ray should have its own plane and you would just need to check you're not targetting said plane
Also add a range check
