### ISSUE TITLE
If you put bonemen in the gibber you get meat.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16273]
(WEB REPORT BY: meetmeindorms REMOTE: 172.93.109.202:7777)
# Revision
8984ad596abd59f4e21c488640f4fd58d4feba9d

# Description
Put skellingtons in the gibber and you get meat.
# Steps to Reproduce
1. Crack the ack.
2. Put cracked ack in the gibber.
3. Meat

# What you Expected
I have no clue what I expected.

# What Actually Happened
Meat

**Comment by Shadowmech88** [comment]
I believe this should be as simple as just changing the meat type of skeletons in their species datum.

**Comment by MadmanMartian** [comment]
meal bones for stew when?

Grind them up for bone meal for a better fertiliser when?

**Comment by Killette2** [comment]
Bone marrow
