### ISSUE TITLE
The health analyser sometimes scan souls improperly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16272]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
8984ad596abd59f4e21c488640f4fd58d4feba9d

# Description
Had a head to fix.
Health analyser indicates someone is there.
Did a head transplant.
Clone : MIF.
Beahead the clone : health analyser indicates a soul again.

**Comment by MadmanMartian** [comment]
Thank you for the feedback. Was difficult to test it by myself so a bug or few slipped through. I'll get onto it ASAP

**Comment by SonixApache** [comment]
@MadmanMartian did you do the multi-client join-as-yourself + join-as-guest thing

**Comment by MadmanMartian** [comment]
???

**Comment by SonixApache** [comment]
make sure `GUEST_BAN` is #commented out in the config
Launch / Log in on BYOND, start your daemon, click this button
![image](https://user-images.githubusercontent.com/8468269/31735049-e7ec573c-b440-11e7-9571-e11cb0b9dd08.png)
log out on BYOND, click button again

now you have two working clients to test with
