### ISSUE TITLE
Creating traitors via Create-Antagonists always will try to make three traitors

### ISSUE THREAD

**Issue by small-boss** [d3athrow/vgstation13#16286]
#### Description of issue
Creating traitors with Create-Antagonists ends up turning 3 players into traitors. So if you have only ten people on station and press the button in hopes of turning someone into a antag it ends up creating three traitors, which is pretty overkill for a small station.

#### Difference between expected and actual behavior
Expected: The button only creates one traitor
Actual: The button creates three traitors

#### Steps to reproduce 
Press the button on a local server as admin

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
In vgstation13/code/modules/admin/verbs/one_click_antag.dm
```
for(var/mob/living/carbon/human/applicant in player_list)
		if(applicant.client.desires_role(ROLE_TRAITOR))
			if(!applicant.stat)
				if(applicant.mind)
					if (!applicant.mind.special_role)
						if(!jobban_isbanned(applicant, "traitor") && !jobban_isbanned(applicant, "Syndicate"))
							if(!(applicant.job in temp.restricted_jobs))
								candidates += applicant

	if (candidates.len)
		candidates = shuffle(candidates)

		var/mob/living/carbon/human/candidate

		for (var/i = 1 to min(candidates.len, 3))
			candidate = pick_n_take(candidates)

			if (candidate)
				var/datum/mind/candidate_mind = candidate.mind

				if (candidate_mind)
					if (candidate_mind.make_traitor())
						log_admin("[key_name(owner)] has traitor'ed [key_name(candidate)] via create antagonist verb.")

		return 1

	return 0

``` 
Apparently not only does it always make 3 traitors, it's also coded relatively badly on top of that
