### ISSUE TITLE
More DEFFiciencies

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#16281]
![more fresh hell](https://user-images.githubusercontent.com/13457856/31803152-26db394c-b520-11e7-8c7f-1d55a5e3e8e6.png)

If the image isn't clear enough, that scrubber connects to literally nothing (and there's already one in the room anyways), and obviously a pipe where it should never exist.

**Comment by Kurfursten** [comment]
This kind of thing happens when you copy/paste windows. No judgment though, copy/paste windows saves a ton of time on stacking grilles and panes.

Thanks for the very clear report.

**Comment by Pathid** [comment]
Genetics has another disconnected vent or two, as does the bar back room. Don't know if I should make a separate issue or not.

**Comment by Cyadox** [comment]
@Pathid You should probably open a new issue. As much as I'd like to say 'hey guys just post in this issue to get the map fixed', we'll still get the automated issues coming from the bug reporter opening new issues.

**Comment by Shadowmech88** [comment]
Splitting each problem into its own issue is generally good practice, because it avoids issues becoming "half-fixed" if someone fixes one of the problems described in it, but not all of them.
