### ISSUE TITLE
Clarke Inflatable Launcher Cannot Target Adjacent or Present Tile

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16289]
If a king could move there, Clarke can't shoot it. Same with tiles it's standing on, which can be inconvenient.

**Comment by ghost** [comment]
It seems to be a thing with most of the missile rack launchers, probably to stop people blowing themselves up.  I can't exactly tell what lets the ones that CAN target adjacent tiles do it, though.
