### ISSUE TITLE
R&D servers are invisible

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16288]
Could be all stations, too. Just a sprite state error I assume.

**Comment by ghost** [comment]
It's on all maps, and it's because the server sprite is in telecomms.dmi instead of research.dmi.  Looks like it got moved there when _SOOOOMEONE_ redid telecomms machinery.

**Comment by SonixApache** [comment]
Oh, so that's what it is. I figured they were accidentally mapped out.
