### ISSUE TITLE
Clarke salvaging breaking my immersions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16290]
(WEB REPORT BY: bittervanilla REMOTE: 172.93.109.202:7777)
# Revision
eab1acb0e4e0cd724f69672896549c8bd54b5911

# Description

After destroying a Clarke mech and using a crowbar/welding tool to salvage parts from the wreckage, a Ripley Left Leg popped out.

# Steps to Reproduce

It's RNG (I think?) but:
Smash Clarke
weld/crowbar
see what comes out

# What you Expected
Clarke parts to be salvaged

# What Actually Happened
Ripley parts were being found instead

**Comment by ghost** [comment]
That's weird, because the Clarke wreckage seems to be all in order codewise.  Maybe it's leaving behind the wrong wreckage when it explodes?
EDIT: It's using the wrong wreckage.
