### ISSUE TITLE
Hologram Issues

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#16308]
<del>Holograms can't hear speech, because they lack the `HEAR_ALWAYS` flag which confers virtualhearers.
Holograms' inventory slots don't show up.
Holograms can't hear sound because their `Login()` doesn't call `..()` which means they're not added to the player list.</del>
Holograms can move diagonally. Not sure what the best fix for that would be.

**Comment by unid15** [comment]
Some feedback - holograms can deal lethal damage to players, and they can break windows. IMO those two things should only be possible when the holodeck's safety protocols are disabled. If they're not, all damage originating from the holograms should be HALLOSS. That might be fairly hard to implement, though.

**Comment by unid15** [comment]
You can become holograms even if the holodeck console is powered off
Also adminghosts (and ordinary ghosts for that matter) can no longer access the holodeck console interface. I think becoming a holodude should be done by clicking a button in the console interface, rather than clicking on the console itself

**Comment by Shadowmech88** [comment]
I'd prefer to leave the ability to deal damage so that holograms can participate in rage cages and boxing matches and the like.
Holograms who murder people should just get banned.

**Comment by Blithering** [comment]
Could you have holograms deal holodamage when attacking?
Also a couple of things I noted:
Picking things up by clicking works fine, but using right click > pick up tells you you cant pick things up
And holopeople could use a bit of transparency on their icons to match other holo things

**Comment by Exxion** [comment]
We have `HALLOSS` for a reason. Holograms on the safety-enabled holodeck should *always* use it.

**Comment by Durgen** [comment]
holoshitters should not be able to damage the holodeck
also there should perhaps be a cooldown for becoming a hologram

![holoshitters](https://user-images.githubusercontent.com/19157295/31867531-1808a010-b757-11e7-927b-3f79a43d31dc.png)

**Comment by Durgen** [comment]
Also there should be a maximum amount of holomen at one time. Maybe 3-4. Otherwise they become totally disinhibited shitters.

**Comment by Chazach** [comment]
They cant even use lasertag guns

**Comment by Shadowmech88** [comment]
It seems holopeople can no longer move diagonally. Everything else would be better served being made into a feature request.
