### ISSUE TITLE
Holster sanity is still kinda broken

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#16329]
#### Description of issue

Attempting to draw an item from a holster of any type (knife or handgun) via macro/verb while both hands are full will tell you you need an empty hand to draw it.  Despite this, the item drops onto the floor under you, and will keep 'teleporting' after you if you continue attempting to draw it with both hands full.

If someone picks the item up and you attempt to draw it again, it'll duplicate the item - whoever's holding it keeps theirs, but another spawns under you.  These duplicates are still the SAME item, though, and if dropped or taken will remove the others.

If you pick it up yourself and then attempt to holster it by clicking on your jumpsuit/boots, you'll be given an error message for the holster being occupied.  Attempting to empty the holster with your other hand will work, but the weapon you were already holding will still be visible on your sprite and still be usable, despite not being in your hand slot.

There's a lot of other confusing behaviour that you'll notice if you test this out and trying to make it consistently work is giving me a headache.

#### Difference between expected and actual behavior

Expected to either be unable to draw the item with both hands full, or for the item dropped on the floor to not bug out horrendously.

#### Steps to reproduce 

1. Place item in holster.
2. Have hands full.
3. Attempt to draw item from holster with the Holster-(Handgun) or Holster-(Knife) verb, via the object tab or macro.

#### Specific information for locating

Shoulder holsters, knife holsters, and the like.  First noticed with the Head of Security's Lawgiver and Tactical Knife, but seems to be the case for everything.

#### Length of time in which bug has been known to occur

It seems to be the same issue with iconstates from #15366, which was supposed to have been fixed in #15600.

#### Server revision

bafcd50bbda22c552032a84673f973280f6bff46

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
Easy fix: remove verbs.

**Comment by ghost** [comment]
m-muh macros

Still, verbs are a real pain in the ass, aren't they?

**Comment by jknpj** [comment]
non-meme answer: put_in_hands forcemoves the item to your turf if both your hands are busy THEN returns false. Holsters use if(put_in_hands) in the unholsting proc so there you go.

**Comment by ShiftyRail** [comment]
>put_in_hands forcemoves the item to your turf if both your hands are busy THEN returns false

We could either do a new proc just for holstering or tweak put_in_hands.
