### ISSUE TITLE
Inserting an ID into a PDA with an ID says you're inserting when its not

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#16325]
What it says on the tin. Was doing local testing as a Captain, put the Spare in my PDA then just for funsies wanted to see if I could put in both. Turns out you can't thankfully, but the to_chat message says you are inserting the ID anyways

**Comment by SonixApache** [comment]
Isn't that because you swap the IDs?

**Comment by Cyadox** [comment]
I didn't think to check to be honest, since the ID's look identical. I'll check right now

**Comment by Cyadox** [comment]
Apparently I'm retarded because you're correct. However, maybe making the ID's name, rank, or some other identifier should be part of the message so you know what ID is inserted? 

I can't believe it doesn't do that now and instead t feels the need to tell you who's PDA you're putting into to like you wouldn't know.

**Comment by strawberrytan** [comment]
The current ID inside a PDA is also stated in the main menu of the PDA
