### ISSUE TITLE
Box station toxin mixing room fuckery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16333]
(WEB REPORT BY: dopaper REMOTE: 172.93.109.202:7777)
# Revision
c82dce1e6c0c87b10c0b24893ccec568de34d4b6

# Description
if you put your mix in the mixing chamber and leave it there too long without lighting it or draining it, it will turn invisible and not burn or allow any other gasses in. It's been this way for a long ass while.
# Steps to Reproduce
Put a 33/66 mix in the mixing room and wait, or burn it in the mixing room and wait.
# What you Expected
Big bomb sauce
# What Actually Happened
Bomb sauce dissapeared

**Comment by Cyadox** [comment]
I only used a small amount of gas, but i can't seem to replicate this. By default, the mixing vent pulls gas out of the mix chamber into a pipe *whether the gas pump is on or off*, so maybe that's all this is?
Can't say what's not letting gasses in though. As far as I know turfs can have an infinite amount of gas in them, so unless the injector is off or the pipe is empty that shouldn't be an issue.

There's no invisible gas eating monster, for sure.

**Comment by CptWad** [comment]
theres a vent in there that passively succs all the air out into the pump
turn off vent
"bug" fixed

**Comment by CptWad** [comment]
![image](https://user-images.githubusercontent.com/3959840/32036463-d1c3afd4-b9d4-11e7-9e24-515a716653b6.png)
this

**Comment by Cyadox** [comment]
@CptWad yeah pretty much what I was trying to say. I guess its unintuitive because people assume vents have no gas storage of their own

**Comment by PJB3005** [comment]
I fail to see how it's unintuitive when you can literally see the pressure meter on the output pipe rising.

**Comment by Shadowmech88** [comment]
If the exit pump is turned off, I don't think the removed gas will reach the pipe meter.
Or are you referring to a meter other than the pipe meter?

**Comment by PJB3005** [comment]
Ok true that.

**Comment by FudgePucker** [comment]
What about adding a tank computer like the ones in atmospherics so you can change the settings and toggle on/off the vent and injector?
