### ISSUE TITLE
Welding Shards as Clarke Creates No Glass Sheets

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16347]
Also, if you try to deflate inflatables from its launcher, you don't get them refunded, but that may be intended

Additionally, the Clarke switchtool welder deals very very low damage, taking quite a few hits to deal with a carp. One carp can deal almost half of the Clarke's integrity before dying, carps should die in 2 welder hits.

**Comment by jknpj** [comment]
i though it was supposed to be unable to do any sort of combat

**Comment by Shadowmech88** [comment]
The inflatables not refunding is intended.
The low damage from the welder is not explicitly intended, but the Clarke is generally not intended to do any sort of combat, so I don't see a reason to fix that.

The shard welding is the only issue.

**Comment by Kurfursten** [comment]
To be clear here, if you ever encounter two carp, which is almost guaranteed on maps with high numbers of spawns like metaclub but extremely likely even on box, your Clarke is as good as scrap metal.

I am pretty sure the total lack of any armor is enough disincentive against using it to fight, but you can't run away from Carp. They move faster than the Clarke.

**Comment by PJB3005** [comment]
This issue is *really* non atomic.

**Comment by Shadowmech88** [comment]
Maybe a module that specifically disables space carp could be added, for Clarkes that need to do work in space.
That should really be put into its own feature request, though.

**Comment by Kurfursten** [comment]
Clarke already has extremely high competitiveness for modules. I would go on at this at length but let's not get even further distracted.

**Comment by Kurfursten** [comment]
Pretty sure Shadowmech fixed this one
