### ISSUE TITLE
Posibrain getting ejected from mechs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16349]
(WEB REPORT BY: libertino REMOTE: 172.93.109.202:7777)
Some times when using a clarke I got ejected from the mech while using a multitool.
# Revision
f36295aecd8ee8d77cb9f5aa13ab7822126614a9

# Description
For whatever reason I got ejected from my mech as a posibrain, it happened twice in this round. I was using an exosuit mounted engineering multitool to try and re-wire the goonsat to turn on the teleporter. I got bussed into my mech by admin goldstein the first time but gave up on the second time it happened.
# Steps to Reproduce
Try using a clarke equiped with an engineering multitool to hack doors, place wires and other such things, that is what I was attempting when the bug ocurred.
# What you Expected
I expected the mech to be able to do everything an engineering borg is capable of, AT LEAST.
# What Actually Happened
 Not only was it not able to do the stuff it is intended to do it ejected my posibrain in the process, leaving me effectively stuck at a vault.

**Comment by MadmanMartian** [comment]
Reproduced on private server. When you clickdrag the mech you can eject yourself as MMI
