### ISSUE TITLE
Cryo tubes without power are completely unresponsive

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16342]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
87d87808e32a8bc7dbe6452f6c7238153fa0e07a

# Description
Cryotube without power are unresponsive. Can't remove patient, nor beaker.

# Steps to Reproduce
Operate a cryotube during a blackout.

# What you Expected
Being able to retrieve the patient or the beaker.
# What Actually Happened
None of it happened.

**Comment by SonixApache** [comment]
isn't that intended?

**Comment by ShiftyRail** [comment]
I do not think so. The patient can extract themselves, and you can remove them with right-click as well, it's just the NanoUI that's completely unresponsive, which can be quite frustrating if you have a perfectly fine cryomix you can't retrieve.
