### ISSUE TITLE
Subspace Tunnelers Can Pick Up Objects With People Inside

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16350]
This includes if someone is inside a mech, for example. Seems a little wrong, the rampaging mech can be clicked out of existence without even a projectile and stored in a perfect prison.

Also, I believe the new meta for prisons should be to lock a prisoner in a locker, then store it with the subspace tunneler. I haven't tested it, but I assume there's no escape? @Shadowmech88 would know if it has a relaymove.

**Comment by Shadowmech88** [comment]
Being able to trap people inside them is explicitly a feature of subspace tunnelers. If you are inside one in any way, you can use the resist verb to escape.

I suppose maybe an exception could be made for mechs due to how dangerous they're supposed to be, but that'd still be a feature request.

**Comment by Kurfursten** [comment]
It's good that you thought to add a resist out.

Can you grab people who aren't inside objects? e.g. are these your best choice against deathsquid?

**Comment by Shadowmech88** [comment]
It doesn't work on mobs themselves, you have to at least trap them inside an object first.
