### ISSUE TITLE
Biomass can be attacked with unlit/empty welders

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16355]
#### Steps to reproduce 
Attack biomass with unlit welder with 0 fuel
Expect it to fail
It works flawlessly

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/commit/b91b877d0a332bc3673f31d3e27c4a5cf7598071#diff-977791ecb40b3ed7dce566a2767506e5
Maybe?

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MadmanMartian** [comment]
What feedback did it give?

\The [user] sears through \the [src] with \the [W]

or

\The [user] burns away \the [src] with \the [W]

Either which way that means the welder's not sorting itself correctly when it's out of fuel

**Comment by DamianX** [comment]
>  That's a gatling welder. It is a bulky item. 
Engineering Dakka. 
It contains: 
Nothing. 
It contains 0/160 units of fuel! 
You use the gatling welder's hot edge to burn through the biomass.

**Comment by MadmanMartian** [comment]
Alright, so its sharpness flags aren't being set properly when it runs out of fuel. I'll get onto it ASAP

**Comment by ghost** [comment]
It works even when it has full fuel, the issue is that it doesn't check for it being activated to burn away.

**Comment by MadmanMartian** [comment]
looking at it, neither do energy melee weapons.

Why have something toggleable when you have elements of it not depend on being toggled on?

**Comment by SonixApache** [comment]
welding tool nozzles are kept at 1000°K at all times

**Comment by MadmanMartian** [comment]
*screaming*
