### ISSUE TITLE
Unspawned statistifcs_cycle() call in gameticker.dm

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#16356]
https://github.com/vgstation-coders/vgstation13/blob/aa03523a510f3b2c5e43e635b28f502bae1e946d/code/game/gamemodes/gameticker.dm#L229-L330

Probably not intended.

**Comment by gbasood** [comment]
huh, I thought I ripped out all of the SQL db stats code

**Comment by Kurfursten** [comment]
@Exxion It would seem this call no longer exists at all, sood may have removed it
