### ISSUE TITLE
Bomb flash causes grilles, canisters, and tanks to explode(?)

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#1636]
Early this morning, nuklear dropped a 100-tile bomb with no actual explosion (or some shit like that, ask him). There was a huge flash, and every grille, toxin canister, and fuel tank on the station exploded, causing the station to be irreparably damaged, and the round to end in under a minute.

I have no idea if this has to do with the new bomb flash that was just added/fixed/whatever, but shit, man.

**Comment by ririchiyo** [comment]
Reopen/new issue if you decide to do ex_act(4).
