### ISSUE TITLE
Runtimes associated with advanced cameras

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#16361]
#### Description of issue
When testing out some new mobs that explode into an EMP, I found that there's a few runtimes that crop up when cameras get EMPed

[00:10:38] Runtime in adv_camera.dm, line 180: Cannot execute null.isUsed().
proc name: update (/datum/interactive_map/camera/update)
usr: Unknown (Guest-1176300837) (/mob/living/carbon/human)
usr.loc: The floor (172, 255, 1) (/turf/simulated/floor)
src: /datum/interactive_map/camera (/datum/interactive_map/camera)
call stack:
/datum/interactive_map/camera (/datum/interactive_map/camera): update(1, 1, /list (/list), 0)
the security camera (/obj/machinery/camera): emp act(1)
empulse(the floor (171,256,1) (/turf/simulated/floor), 6, 12, 1)

Got over 100 instances of this one

[00:36:36] Runtime in adv_camera.dm,202: Cannot execute null.isUsed()
proc name: update (/datum/interactive_map/camera/update)
usr: Unknown (Guest-1176300837) (/mob/living/carbon/human)
usr.loc: The floor (172, 255, 1) (/turf/simulated/floor)
src: /datum/interactive_map/camera (/datum/interactive_map/camera)
call stack:
/datum/interactive_map/camera (/datum/interactive_map/camera): update(1, 1, /list (/list), 0)
the security camera (/obj/machinery/camera): emp act(2)
empulse(the floor (171,256,1) (/turf/simulated/floor), 6, 12, 1)

80~ instances of this one.

#### Steps to reproduce 
EMPs in proximity to cameras, with the power already being off at the APC

**Comment by ghost** [comment]
Might happen if nobody has used the cameras on the round yet, will investigate later
