### ISSUE TITLE
Reduce material costs of Conveyor circuit boards by 50%-90%

### ISSUE THREAD

**Issue by Ragnasal** [d3athrow/vgstation13#1637]
A conveyor belt circuit board costs as much as a regular board in resources.
Sucks when you're trying to mass produce them. They should have reduced material costs for specific reasons that may or may not include Conveyor Station.

**Comment by CptWad** [comment]
How has this not been been updated? :+1:

**Comment by 9600bauds** [comment]
They're pretty cheap if you scan the board and produce them at the General Fabricator.

**Comment by d3athrow** [comment]
issue with being able to make flaps is they're indestructable, unless we made them deconstructable you'd end up with ground zero IV drip and meatspike clogging the hallways again.
