### ISSUE TITLE
Hand tele bugs

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16373]
-If you put a hand tele in your pocket or backpack while standing over a portal it goes in the portal
-The icon appears in your pocket/container but you cannot access it
-If you quickswap in your pocket where it should be, you can pull it back out your pocket despite it have "fallen" in the portal

**Comment by PJB3005** [comment]
Oh so THIS is what causes that.

I think I did some debugging on the probable cause of this. The item temporarily gets moved onto the tile you're on while it's being moved cross inventory slots, so the portal catches it and ruins everything.

**Comment by Shadowmech88** [comment]
Would there be any issue with temporarily moving the item to nullspace instead of the turf?

**Comment by PJB3005** [comment]
I doubt it.

**Comment by PJB3005** [comment]
Realistically however, you wouldn't have to move it at *all* since the item is still contained inside the same mob. Just change the screen location and what slots it's assigned to.
