### ISSUE TITLE
Vox versions of the Tacticool turtleneck shows up as grey jumpsuit

### ISSUE THREAD

**Issue by Uso15** [d3athrow/vgstation13#1638]
I'm pretty sure skowron set up both versions of the suit, real and arcade prize, with new vox versions. not sure what could be linking back to a grey jumpsuit code-wise
![screenshot 2014-10-03 22 39 18](https://cloud.githubusercontent.com/assets/8187016/4514568/5d1dd740-4b78-11e4-89d9-9d0e3d25fd28.png)

**Comment by ComicIronic** [comment]
http://puu.sh/fnZPT/f40cbf5d66.png
Not an issue.
