### ISSUE TITLE
Chef Hat Visual Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16384]
(WEB REPORT BY: swagman55 REMOTE: 172.93.109.202:7777)
# Revision
67779cc19de42399f8f292f431b0e3294e2a244f

# Description
When holding the Chef's hat it appears as you holding a Chef's apron

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Shadowmech88** [comment]
Does an in-hand icon for the chef's hat exist?

**Comment by Blithering** [comment]
Aren't inhands a bit overstuffed right now? Not that I'm against fixing this, but inhand changes tend to break existing icons

**Comment by PJB3005** [comment]
@Blithering only if they're done incorrectly.

**Comment by Blithering** [comment]
I just thought it would be worth mentioning since this was tagged as a good first issue

**Comment by ShiftyRail** [comment]
Dupe of #20070
