### ISSUE TITLE
The system for throwing speed/damage sucks dick.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#16393]
Items have two throwing-related variables, throw_speed and throwforce.

Main problem:
throw_speed determines how many tiles a thrown item flies per tick. This is ridiculously fast for 99% of items in the game, which have throw_speed ~4 or more. **An item with throw_speed=4 moves 4 times faster than any bullet in the game.** An item with throw_speed=4 has literally no travel time when thrown up to 4 tiles away, turning it effectively hitscan like a laser.

Problem 2:
The reason why 99% of items in the game have such a high throw_speed is because throw damage is not throwforce, like you would expect, but actually ´´´throwforce*throw_speed/5´´´. So if you want an item to not fly ridiculously fast when thrown, and give it a throw_speed of 1 or something, you would have to multiply its throwforce by 5 for it to keep the same throw damage.
There's a super special way to make an item fly slower while keeping the same damage, an argument called fly_speed. However you can't set this individually per item, you need to feed it as an argument to throw_at() and only 3 things in the game do that.

I suggest that the throw damage of an item should purely depend on throwforce, and the throw speed of an item should purely depend on throw_speed. Then, make most items have a throw_speed of 1 or 2 to keep shit sane.
As a requirement to that someone would have to go through every item in the game and replace their throwforce with ´´´throwforce*throw_speed/5´´´. Is this doable with a script of some sort?

**Comment by Exxion** [comment]
Yes, but it would *ruin* the pneumatic cannon, and hulks, and plenty of other things.

Also you didn't even mention armor

**Comment by ghost** [comment]
The pneumatic cannon calculating throw damage differently is bad and why glass shards instakill people for no good reason. That'd be the opposite of ruin t b h

Hulks and everything else that previously modified throw_speed (I'm not aware of any besides hulks and pneumatic cannons) can use some other damage modifier that's not inherently tied to the fly speed of the item which is the problem to begin with

**Comment by Exxion** [comment]
But it makes *sense* that if something is flying faster, it will deal more damage. You could alter the equation such that at the normal speed, damage is equal to `throwforce`, but making it equal regardless of speed is silly.

**Comment by Lokiamis** [comment]
while we're at it, let's rebalance basketball

**Comment by yclatious** [comment]
>A pneumatic cannon loaded with almost theoreticaly impossible pressure firing a ultra sped up piece of sharp glass shouldn't instakill people

Nani the fuck, wood has pierced concrete when thrown fast enough by tornados, anything sharp enough would cut through you like butter if fired from a pneumo.

**Comment by Shadowmech88** [comment]
Of course it would.
It shouldn't instakill people because having a moderately-easy to obtain weapon which uses very-easy to obtain ammunition which instakills people is very not-fun for everyone except the shooter, not because it's unrealistic.

**Comment by ghost** [comment]
No that's not what I mean.
Glass shards have a low throw_speed and high throwforce, which are supposed to balance out. Well the pneumatic cannon ignores the former. Tada. Glass shards are now pneumatic cannon death missiles, but not coins, or knives, or anything you'd expect to work better as a projectile. Basically the best pneumatic cannon projectiles are the ones that "naturally" fly the slowest, not the ones that naturally make the best projectiles.

If only there was a way to make a glass shard visually fly slower without giving it a high throwforce to compensate...

**Comment by Exxion** [comment]
Glass shards and hatchets are tied for the best pneumatic cannon ammo, and both of them are intended to be good throwing weapons
Not that the pneumatic cannon's balance is good, but that's not the specific reason it's bad

**Comment by Hugh-G-Rection** [comment]
Actually, the best pneumatic cannon ammo is in fact monkeycubes  :clown_face:

**Comment by Exxion** [comment]
Alright, best for sheer damage

Also monkeycubes are worthless if your opponent has a mask, whereas a glass shard or hatchet still has a roughly 30% chance of one-shotting someone in deathsquad armor, if memory serves
