### ISSUE TITLE
Dead simple mobs including mice can block emitter beams

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16396]
#### Issue description
Need I say more? Dead or prone humans don't block them but dead mice do.

#### Server revision

Game: f240d18facecec4787a017a83f7b979d96caf804 
Patches: d906516f81933e3d174db4567c16a7fbf960ebe6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Very literally.

**Comment by ghost** [comment]
You need to block 3/4 emitters to singuloose IIRC so not that bad

**Comment by Pathid** [comment]
Haven't been able to reproduce it with mice, so far. I'm guessing they have to be killed in some non-standard way. However lots of other simple mobs will block the beams indefinitely with their bodies.

**Comment by ShiftyRail** [comment]
Update (trying to fix it), it works reliably on cows, necrophorms, and other large simple animals.
