### ISSUE TITLE
Blood moon feedback

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#16398]
Opening an issue with some feedback now that a blood moon button has been pressed and people have given it a try.
The main problem appeared to be that it instantly spawns mobs with no prior warning, leaving the crew flatfooted and dead within the first few moments. A global message when the button is pressed, followed by a few minutes prep time could really make it more enjoyable.
Another problem is that with the APCs all breaking, anyone without easy access to a crowbar gets stuck in their department even if they can kill off the mobs that spawn there. Perhaps a drop off of survival equipment like meteor mode has would help with that?
The other thing that might help would be clear goals, perhaps a way to defeat the event so that the crew can return to normality somewhat or at least call the shuttle to evacuate the survivors.

**Comment by Blithering** [comment]
Closing due to duplicate issue, will post comment in shadowmech's

**Comment by SonixApache** [comment]
shame a dupe is the 6666th closed issue

**Comment by Blithering** [comment]
At least it was to do with something spooky.
