### ISSUE TITLE
Over 100% Gas at air alarm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16413]
(WEB REPORT BY: streptomutans REMOTE: 172.93.109.202:7777)
# Revision
b38facc339cd63bd5902aea744065ca9bc07edd1

# Description

1. Check air alarm in a room which has been flooded
2. See N2O far above 100%
3. Have your almonds activated by that fact
4. Use atmos analyzer: It shows a realistic percentage but no moles
5. Use atmos analyzer on scrubber pipe when scrubbing it: realistic percentage but no moles

**Comment by Exxion** [comment]
Wow, I thought this was my fault
But no, it's Celt's

I mean the removal of `group_multiplier` made the number much, much larger, but this would have happened in really impressive floods anyway

I'll still fix it, of course
