### ISSUE TITLE
Some dead bodies act up very strangely when trying to bring them back to the round.

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#16417]
#### Description of issue

Behead them and slap an health analyser unto them, nothing happens.
Scan them in the cloner, not even a "MIF" or "Subject might be braindead" message happens.
Examine gives a "He has no pulse and his soul has departed..."
Stuffing them in morgue trays and clicking on them just make them disappear until you update the turf. 
Defibing just gives out the message `You shock Urist McSpessmen with the paddles.`, and no further message about failure or success.
Really bizarre.

#### Difference between expected and actual behavior

The cloner gives understandable messages, not just a blank.
Same for the health analyser.
And lastly, bodies should _not_ disappear after stuffing them in a morgue.

#### Steps to reproduce 

Actually I don't really know, since it happens with seemingly random dead bodies.
One thing for sure, Monkeymen are not included. `Error: Mental interface failure.` still shows up.
Players who are still "in there" are not affected as well, It only seems to affect people who have left the round. I still get "Subject might be braindead" and classical "MIF" messages.

#### Length of time in which bug has been known to occur

Very recently, I'd say less than two weeks.

#### Server revision

b38facc339cd63bd5902aea744065ca9bc07edd1 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players (got people next to me to confirm)
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
I've got webm recorded, will uploaded them as soon as possible.

**Comment by Hugh-G-Rection** [comment]
Just to clarify, by saying you behead them the implication is that this is all with a headless corpse, correct? So it's as simple as adding "There's no head/brain" error message to everything. 
I mean I know the ride can get wild but I've never seen someone use paddles on a headless corpse before.

**Comment by ShiftyRail** [comment]
No, I mean the functionality of #16278 which tells you if there is a soul in a head.
Get a head with this bug, run the health analyser on them, get no feedback.

**Comment by ShiftyRail** [comment]
Cloner :  https://webmshare.com/play/jq6m8
Defib : https://webmshare.com/play/dvRnr (notice how there is no "vitals signs too weak" nor "patient condition does not allow reviving")
Morgue : https://webmshare.com/play/VGeMB (by far the most spooky)

**Comment by PJB3005** [comment]
This is fixed by #16407.

**Comment by ShiftyRail** [comment]
Alright, I've seen it, he might have forgotten about the health analyser though.
