### ISSUE TITLE
Potato batteries are borked

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16419]
-potato batteries power is supposed to increase with potency
-a potency 110 potato had the default 300 charge, should have been much higher, potato contained no chemicals
-potency 64 potato with very high levels of nutriment also resulted in a 300 charge battery

I read somewhere in the code prior a long time ago that potato battery cells are supposed to scale with potency (albeit poorly), this didn't happen.

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/df127e0e35537ffdd34b72555677b471b2b97d5a/code/modules/reagents/reagent_containers/food/snacks/grown.dm#L338-L350

Well it's in there, so this is definitely a bug and not a feature request.

**Comment by Exxion** [comment]
The code to set the charge looks pretty airtight. Not sure how that's failing.

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/246b9261f5df95639af1ec5c029a8e2fd9ed8136/code/modules/power/cell.dm#L5-L13
So apparently the code that sets the description is getting called before the maxcharge is updated.

**Comment by Shadowmech88** [comment]
The description updating could be moved to an `update_desc()` proc, which could then be called by the potato battery after the charge is set.

**Comment by Exxion** [comment]
It shouldn't set the `desc` at all. It should just say that stuff in `examine()`

**Comment by Shadowmech88** [comment]
Oh, true.
