### ISSUE TITLE
Chemical temperature recipe ideas and tweaks

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#16410]
* Putting a reagent container in the fridge (1-4 C) or freezer (somewhere below 0C) should cool it down
* Heating ice should turn it to water (>3C)
* Cooling water should turn it to ice (<0C)

Other suggestions would be nice

**Comment by jknpj** [comment]
as bad it might be: ling blood testing.

**Comment by Kammerjunk** [comment]
\>Pick up solid plasma at 20 °C
\>Turn it into liquid plasma at 20 °C
\>Carry highly toxic widely unknown substance to the other side of the room and put it on table
\>Accidentally spill it, curse but carry on
\>Pick up empty glass beaker
\>Fill it full of molten iron
\>Pick up glass beaker of molten iron
\>Melting point: 1,538 °C
\>Subverted AI pumps gaseous plasma at 20 °C into the air and kills me
Reagent temperatures are a meme ¯\\_(ツ)_/¯

**Comment by Hugh-G-Rection** [comment]
I used to love the idea of ling testing, but the current community can't be trusted with it. 
The last thing we need is everyone getting cuffed and blood-drawn every time an assistant husks himself on an HoP grille. Please no more antag tests.

**Comment by DamianX** [comment]
Also please no more discussion about antag tests in this issue, yeah?

**Comment by Shadowmech88** [comment]
Cooking recipe code should be given support for reagent temperatures, and certain dishes should require reagents that are within a certain range of temperatures.
Soups requiring hot liquids, ice cream requiring cold liquids, et cetera.

**Comment by Blithering** [comment]
Crystallising stuff by heating it slowly to make solid forms of medicines without a pill generator

**Comment by Kurfursten** [comment]
In general, I would like a better way of reacting to temperature over time.

So, for instance, if you heat ice to melting point, it only melts 1u of ice and then saps away a small amount of heat from the remaining ice. Continue heating to melt down the ice water over time instead of all at once.

Besides being simulationist, this allows for some other interesting stuff with engines.
