### ISSUE TITLE
New Xenoarch Artifact Effects

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#16426]
I think having some new, interesting Xenoarch large artifact effects would be nice.
Post ideas for new effects. Remember that theoretically, anything can be done.

**Comment by Exxion** [comment]
>theoretically, anything can be done

I mean... I guess that's technically true, but there are lots of things that practically can't

**Comment by Shadowmech88** [comment]
Right, but I didn't want people to not suggest things because they weren't sure they were feasible. Better to get suggestions that can't be done than to not get suggestions that can.

**Comment by Exxion** [comment]
Oh of course. I was just
Actually I don't have a practical reason for saying it. Being obnoxious, I guess?

**Comment by mtpowell** [comment]
How bout smaller artifacts that can be put in your backpack so it's not so obvious 'giant chunk of earth' is manipulating everything?

**Comment by PJB3005** [comment]
@mtpowell Artifact batteries are supposed to do that, but they're either nigh-useless or flat out broken.

Personally we need to prune crappy effects and make application of artifacts easier via say artifact batteries. Make a gun frame at R&D that shoots artifact effects, etc...

**Comment by Kurfursten** [comment]
At artifact generation, a random value is selected.

When triggered,
>With wire knot below artifact
Puts [that value] watts into the grid

>Without wire knot
Produces a large amount of sparks. If someone is in view(3), lightning bolt them.

**Comment by Durgen** [comment]
An artifact that makes floors and walls wooden, similar to the cultify artifact

**Comment by Blithering** [comment]
Rotates the vision of everyone in the z level 90 degrees per activation
causes the first two people to activate it to become quantumly entangled, anything that happens to one, happens to the other
creates a screen sized looping field, walking too far in any direction will cause you to loop around to the opposite edge of the field
ghost inhabitable mob TGborg style, crystal entity that has no hands, but starts with telekinesis to move objects with instead
a caveman frozen in ice
a powerful sword embedded in stone, that picks a random person to be worthy to wield it. Only they can take it out of the stone.
a puzzle box with a spirit trapped inside
spews shuttle fire in all directions on activation
splits into two halves that function as containers with a shared inventory, anything put into one can be taken out of the other and vice versa
a cake that splits into two copies of itself if not eaten within a minute

**Comment by Durgen** [comment]
An artifact that lets you teleport to supermatter sea beach.

**Comment by Exxion** [comment]
@Kurfursten That effect on a speed trigger
Fantastic meme engine fuel

**Comment by Jubisloviu** [comment]
A headless live body that ghosts can control
A ancient drone that can be controlled with a remote
A huge rock that scrambles the names of everyone in the z-level

**Comment by Hugh-G-Rection** [comment]
A small robot that when given a power cell and activated will throw never-ending pies at any mob in range, giving them 10u nutrient per splat, until it is destroyed or the cell runs out.

On activation, everyone within a certain tile radius will only hear other people's voices as HONK! Basically Peirrot's ears.

Randomly makes the sprite of anything you touch it with larger by a random amount, the way admins will sometimes make giant rubber ducks

On touch, grants you a random benefit, such as positive genetics mutation or phazon power, or unique weaker affects that are all positive. When first  touching it, the pillar gives you a countdown of time with no explanation, then chooses a random mob from a list (Spiders, Hivebots, Corgis, Polar Bears etc), and assigns that mob to you silently. Every time you touch it, a counter goes up by 1, and when your time is up, you will be gibbed and however many times you touched it, that number of your mob type will burst out of you. "Guys come check it out, I can run super fast and eat extinguishers!" "OH MY GOD CLOWN JUST EXPLODED INTO THIRTY SEVEN MICE"
 
Not sure how in-depth we can get with hallucinations, but it would be great to have the illusion of being on an adventure or away-mission while really being on the station. "You are teleported to another realm!", you're standing on stone floors in a vault somewhere, where you explore and find loot, putting on armor and swinging swords at monsters, when in reality you're running down the hallway naked screaming and swinging around a broken space violin.

The Shitter Hat: A black wizards hat that reads aloud the admin notes of the person wearing it :clown_face:

**Comment by Exxion** [comment]
This issue is asking for ideas for large artifact **effects**, not unique artifacts.

**Comment by PJB3005** [comment]
> A ancient drone that can be controlled with a remote

Oh no it's #5000 all over again.
