### ISSUE TITLE
Windoor/firelock placement in Bagel Brig Entrance

### ISSUE THREAD

**Issue by EdXbtkOEwGw** [d3athrow/vgstation13#16427]
![dreamseeker_2017-11-02_18-09-00](https://user-images.githubusercontent.com/33260604/32352764-52103e46-c001-11e7-943e-1d49cad01754.png)
The windoors are layered above the firelocks which make them extremely annoying to use.

**Comment by Hugh-G-Rection** [comment]
Every botany-kitchen windoor ever.
