### ISSUE TITLE
Refilling bunsen burners is a pain in the ass

### ISSUE THREAD

**Issue by Knightkiller11** [d3athrow/vgstation13#16438]
#### Description of issue
So I tried Xenoarch again after a bit, and needed to fill a bunsen burner with fuel. Had a container with ethanol in it, but clicking on the burner with the container in hand didn't fill it.
As it turns out you can only fill a bunsen burner when something's already on it

The main issue here is that nothing about the burner signposts the way to properly fill it with fuel, perhaps give it an interaction where you can screwdriver it to show its container which you can then fill.
Also the wiki on the subject is outdated and doesn't say the burner needs fuel or what fuel is valid.

#### Difference between expected and actual behavior
Expected:
1) Have container of valid fuel
2) Use it on bunsen burner (with nothing already on it)
3) Fill bunsen burner
Actual:
3) Put container on burner, be confused

#### Steps to reproduce 
1) Have container of valid fuel
2) Use it on bunsen burner (with nothing already on it)
3) Fill bunsen burner

#### Server revision
b76d4bc87ccd9af1ce1d3196587b94a6650e5df6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Yep I've found it too. It's pretty painful.

An electric Bunsen burner would be real nice.

**Comment by Shadowmech88** [comment]
It could be changed so that Alt+click fills the burner, regardless of whether it has a beaker on it.

**Comment by PJB3005** [comment]
@Shadowmech88 I already made alt click toggle it in #16412 and alt+attackby seems like quite the unusual interaction.

**Comment by Cyadox** [comment]
Screwdriver or some other common tool to open the fuel compartment?

**Comment by MadmanMartian** [comment]
@PJB3005 this was fulfilled. Please close.
