### ISSUE TITLE
Arm sash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16443]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
1440a12fe5a71682511314726522fddf280c4608

# Description
Quick swapping the sash will give you a permanent arm
# Steps to Reproduce
quickswap sash on belt
# What you Expected
remove arm
# What Actually Happened
multiple arms

**Comment by Exxion** [comment]
Does this let you get arbitrarily many arms?
God I hope so

**Comment by AI-Is-Rogue** [comment]
It does.

**Comment by jakmak6** [comment]
delet

**Comment by Kitfox88** [comment]
unlimited power

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/28573306/32404330-78e9ce28-c16f-11e7-9cdd-cef87de472f6.png)
You can't beat Shiva

**Comment by Aurx** [comment]
Sure you can, just stand directly above or below them.

**Comment by SonixApache** [comment]
we need an alpha strike button
