### ISSUE TITLE
Your own clones attack you with magic missile

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16445]
when you use the doppleganger spell and another person comes into sight, the magic missile has a good chance of being targeted to you also

**Comment by Blithering** [comment]
This is likely more a problem with the magic missile projectile homing rather than doppelgangers

**Comment by Hugh-G-Rection** [comment]
Can't imagine there would be an easy way to fix this without removing the ability for Wizards to MM other Wizards.

**Comment by Killette2** [comment]
Surely there's a way

**Comment by Blithering** [comment]
You could try giving the clones the friendly fire avoidance of other projectile firing simple mobs, but it would make them less effective in combat, more obviously fake and the projectiles themselves will still track you. Just remember not to get between a clone and a target
