### ISSUE TITLE
One-way windows are still calculated for ghosts and mobs with x-ray vision

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#16446]
Re-opening of #15741

![](https://i.imgur.com/VWhgzv8.png)

**Comment by Shadowmech88** [comment]
Is it just the window's own tile?

**Comment by unid15** [comment]
Yes, only the window's tile is blocked

**Comment by Killette2** [comment]
It's called a one way window for a reason, otherwise it'd just be a window

**Comment by Exxion** [comment]
This is because the secret repo was never updated, by the way

**Comment by Exxion** [comment]
Now it has been, so they shouldn't be calculated for ghosts.
The comment says it also stops calculation for x-ray vision, but I see no code to suggest that's actually the case, so I'll leave this open
