### ISSUE TITLE
Vending Machine Sprites

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16448]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
1440a12fe5a71682511314726522fddf280c4608

# Description
there's like three or four white pixels on the top left corners of most of the vending machines

I think this has been the case ever since they were introduced

**Comment by Kurfursten** [comment]
I don't see it. If not fixed, open again with picture.
