### ISSUE TITLE
When Saving Setups You Recieve a Bug Warning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16456]
(WEB REPORT BY: adu6oo REMOTE: 172.93.109.202:7777)
# Revision
87e84fd8f31d54010aaa7ce36b17492abec062cb

# Description
When I saved my setup i got a large amount of text telling me roles could not be found

# Steps to Reproduce
1. Go to to char slot
2. Save roles
3. Look at chat

# What you Expected
Nothing to happen

# What Actually Happened
"BUG: Unable to find role alien.

BUG: Unable to find role blob.

BUG: Unable to find role borer.

BUG: Unable to find role changeling.

BUG: Unable to find role cultist.

BUG: Unable to find role Dionaea.

BUG: Unable to find role malf AI.

BUG: Unable to find role operative.

BUG: Unable to find role pAI.

BUG: Unable to find role posibrain.

BUG: Unable to find role revolutionary.

BUG: Unable to find role traitor.

BUG: Unable to find role vampire.

BUG: Unable to find role vox raider.

BUG: Unable to find role wizard.

BUG: Unable to find role commando.

No changes to role preferences found!"

**Comment by MadmanMartian** [comment]
I've looked at this before. It's because antag role preferences are trying to draw them from href, when the antag role preferences aren't being sent to href.
