### ISSUE TITLE
Telecoms Overheating Very Frequently

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16452]
Recently I've played CE on Box twice, Deff, and Bagel, and every shift telecoms reached 40C and overheated regardless of the setup. I believe someone changed something about temperature code and is causing the frequent overheating. Note that even now it still takes more than an hour to get to that temperature.

**Comment by PJB3005** [comment]
@Exxion 

This is probably due to the experimental ZAS reworks recently. The ancient Xenoarch analysis machines broke too (though much more hilariously).

**Comment by Exxion** [comment]
I blame people basing anything off the number of moles of gas in the environment

**Comment by Exxion** [comment]
There's something weird here. Just like with the xenoarch machines, the changes should have cancelled out in these calculations.

**Comment by Kurfursten** [comment]
Maybe the code telecoms uses to heat up its room is implemented oddly or doesn't use the proper air handling procs?

**Comment by Exxion** [comment]
Oh, it doesn't, but the calculations still should have cancelled out

**Comment by Exxion** [comment]
I'm having some weird issues with Git, so I'll fix this tomorrow. Sorry to everyone in lowpop who wants to use the radio.

**Comment by Kurfursten** [comment]
Fortunately lowpop is less affected due to lower telecom traffic

**Comment by DamianX** [comment]
It might be worth saying that as far as I can remember the code for telecomms heat generation was more or less copypasted from the space heater, so that may need to be looked into as well.

**Comment by PJB3005** [comment]
On the topic of heaters, I think I've noticed that air conditioners are ridiculously fast too. Haven't tested perfectly though.
