### ISSUE TITLE
Bigstacks of Sheets Can Merge Incorrectly on Ground

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16454]
Noticed this very rare niche case recently. Basically if you don't pick up the sheets that are generated at a habitat depot vendor and buy another stack, they merge incorrectly and the amount stays 20 instead of increasing to 40. If you pick up the sheets and merge them in your hand they act totally normally.

Probably related to getfrompool which is used by the dummy item that generates the stack of 20.

**Comment by Exxion** [comment]
Pooling was a mistake

**Comment by Killette2** [comment]
fix when?
