### ISSUE TITLE
chat window not loading

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16461]
(WEB REPORT BY: simonnn REMOTE: 172.93.109.202:7777)
# Revision
09eb641d61fd0c45cf6c5244bd706ffd24c2bbdd

# Description
chat window not loading, stuck on the loading phase.
# Steps to Reproduce
n/a no idea. just joined as usual via adress.
# What you Expected
chat window loading
# What Actually Happened
as above

**Comment by SonixApache** [comment]
useful
