### ISSUE TITLE
Flipped tables not blocking projectiles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16466]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
0abcb3cf284080b21e8256e162ea6b123462f942

# Description
Flipped tables only block projectiles when fired at the tile the flipped table is on but not when fired past
# Steps to Reproduce
Flip table and shoot at the table's tile and shoot past the table
# What you Expected
Blocking projectiles no matter where you click
# What Actually Happened
Not blocking projectiles when clicking past the table

**Comment by gbasood** [comment]
well, hm
IS this a bug?

**Comment by PJB3005** [comment]
I'd say flipping tables should block projectiles yes.

**Comment by Exxion** [comment]
It's supposed to
(Have a chance to do it, that is)

**Comment by Shadowmech88** [comment]
I don't see any reason not to make it guaranteed to block projectiles.

**Comment by Exxion** [comment]
Why would flipped tables be better at stopping bullets than reinforced windows?

**Comment by PJB3005** [comment]
Because it looks cooler?

**Comment by Shadowmech88** [comment]
Bullets could still penetrate through tables like they do through windows. I just mean the tables should always need to be penetrated rather than sometimes just allowing the projectile to pass.

**Comment by Kharkov72** [comment]
Just tested on test server, this is still the case. Shooting past the table causes the electrode to go over it, but clicking on the table has it block it. Tested with stun electrodes and lasers, on a single table and on a chain of two tables.
It only ever blocks if you click on it.
