### ISSUE TITLE
Borgs can't send PDA messages.

### ISSUE THREAD

**Issue by Shaska-** [d3athrow/vgstation13#1646]
Borgs lost the button that lets them send PDA messages, other than replies to other messages, and the button that lets them review sent and received PDA messages.
Guessing it happened when the AI UI got ported.

**Comment by clusterfack** [comment]
Is this still an issue. It seems fine?

**Comment by Shaska-** [comment]
I believe it was fixed a while ago, but I'll double-check just to be sure
