### ISSUE TITLE
Cyborg Chemistry Gripper and Bloodbags

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16474]
(WEB REPORT BY: grimreaperx15 REMOTE: 172.93.109.202:7777)
# Revision
bd483ea93c1801b5fd45f38f3d5b8c01fa4cc7ad

# Description
The Cyborg Chemistry Gripper for Medical Borgs can pick up and insert blood bags into IV stands, but cannot remove them.
# Steps to Reproduce
Put a blood bag in an IV stand, try to remove it with the chemistry gripper.
# What you Expected
The bloodbag to be removed.
# What Actually Happened
The bloodbag was not removed.

**Comment by jknpj** [comment]
Have you tried to click the IV drip without any module active? This is important.
