### ISSUE TITLE
Solanine is a chemical that we have that as far as I can tell does nothing other than what normal toxins do

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#16477]
![there is no code here to make it actually act on anything](https://i.imgur.com/qbYNgeN.png)
this also isn't the only chem that's like this
they're just flavor variations
why do they exist that's dumb

**Comment by Exxion** [comment]
They're the botany versions of the reagents
Keep up

**Comment by Shadowmech88** [comment]
They exist so Botany can obtain functional equivalents to existing chems which can also be mixed to create new chems exclusive to Botany.

**Comment by gbasood** [comment]
Okay
I still don't like it

**Comment by Pathid** [comment]
Solanine is technically a better poison than toxin since anti-tox removes the latter but not the former. Not sure if that was intended.

On second thought maybe it was just slow. I should test them against each other.

**Comment by Exxion** [comment]
No that's probably correct
