### ISSUE TITLE
Martians have a fucky bicon

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#16476]
![](https://i.imgur.com/jnAV5vo.png)

**Comment by Exxion** [comment]
I believe the same goes for certain borg sprites. But only certain ones.
I have absolutely no idea what causes it.

**Comment by Exxion** [comment]
Wait actually I figured it out

![chrome_2017-11-06_22-05-38](https://user-images.githubusercontent.com/9827785/32475267-e39aa316-c33e-11e7-8a91-62752874b270.png)

**Comment by Exxion** [comment]
I don't know why I didn't say this in the above comment, but adding a zero at the end of the args to `icon()` on [this](https://github.com/vgstation-coders/vgstation13/blob/bd483ea93c1801b5fd45f38f3d5b8c01fa4cc7ad/goon/code/datums/browserOutput.dm#L226) line *should* fix it
