### ISSUE TITLE
Taking off jumpsuit inside of suitstorage deletes your ID, belt, and everything in your pockets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16472]
(WEB REPORT BY: delightedmerchant REMOTE: 172.93.109.202:7777)
# Revision
bd483ea93c1801b5fd45f38f3d5b8c01fa4cc7ad

# Description
title
# Steps to Reproduce
Take off jumpsuit while inside suit storage
# What you Expected
I don't know what I expected.
# What Actually Happened
ID, belt, and pockets got deleted.

**Comment by Cyadox** [comment]
Removing your jumpsuit drops those items onto the floor automatically, and are probably being nullspaced since they can't be put into the suitstorage container.

Is it intended for people to be able to access their inventory while in a suit storage unit? If not, a little sanity would fix this.

**Comment by Intigracy** [comment]
Actually, it's dropping them into the suit storage unit's contents.

**Comment by gbasood** [comment]
so basically this just needs to tell the player where the items go i guess

**Comment by Exxion** [comment]
That and actually let them get them back

**Comment by gbasood** [comment]
I didn't realize you couldn't dump the storage contents

**Comment by MadmanMartian** [comment]
Can't you turn off the power and crowbar the stuff out?

**Comment by Exxion** [comment]
Maybe, but that's a pretty wacky thing to have to do to pull objects out of a unit designed for storing other objects

**Comment by Intigracy** [comment]
Just make it dump the "loose" contents when opened.

**Comment by Cyadox** [comment]
Should we even let people drop items while crammed inside what is essentially a suit locker? You can't do that in a normal locker if I recall.

**Comment by DamianX** [comment]
even if you don't *let* people do it, some things like robotic arms malfunctioning would have the same effect, might as well provide a way to eject the contents.

**Comment by Aurx** [comment]
It's safer to assume that people can drop anything anywhere they are than it is to assume nobody will ever add a way to drop things in stupid places.

**Comment by Cyadox** [comment]
>People will always find a way to do stupid things

Fair enough. Intigracy pretty much nailed it, just make it dump anything inside that shouldn't be there.

**Comment by gbasood** [comment]
Alternatively just make it drop the shit from the suit where you're standing
I don't care either way honestly, just that they can get the shit back easier than crowbaring it out without power

**Comment by Kurfursten** [comment]
It should use get_turf instead of loc. That should be a universal standard.

**Comment by MadmanMartian** [comment]
>man takes off clothes inside closet
>clothes pop out of the closet

**Comment by DamianX** [comment]
>cigar goes out inside closet
>butt pops out of the closet

**Comment by Aurx** [comment]
I can't think off-hand of any circumstances where dropping an item while inside something should intuitively place it outside the thing.  
Dropping to turf instead of loc while inside things would, quite reasonably, get bug reported.

**Comment by gbasood** [comment]
No, it drops inside a *suit storage*, like the things in EVA. You can't be in those.

**Comment by Intigracy** [comment]
You can be stuffed into them buddy, it's why you can hack the controls to
make them deal more damage.

Simply loop through the contents when it's opened and remove anything not
referenced by the three slots. It already does it for mobs.

**Comment by Exxion** [comment]
@Kurfursten That is the opposite of true.

**Comment by Kurfursten** [comment]
@Exxion You can't possibly stand by that claim. If you argue that get_turf should *never be used for anything* (the opposite), you'd prevent grenades from going off when held in hand because their loc would not be a turf.

**Comment by Exxion** [comment]
Man, you know what I meant. When one object is dropped by/spawned from/detached from/etc. another, it should always use `loc`, not `get_turf()`.
`get_turf()` should be used only very sparingly when moving or spawning objects.

**Comment by Kurfursten** [comment]
Yes I did

**Comment by Aurx** [comment]
M8, even if you did take him literally, the negation of "It should use get_turf instead of loc. That should be a universal standard." is not "Never use get_turf".

**Comment by Kurfursten** [comment]
One verbal tease is enough for me thanks, I don't have the autism necessary to argue with you about the nuances of "negation" versus "opposite".

**Comment by Aurx** [comment]
"Opposite of true" is false indicates the negation of the statement is true.  I'm sorry, I need to confiscate your autist license, you've clearly normalized.

**Comment by gbasood** [comment]
everyone shut up and fix the bug

**Comment by Exxion** [comment]
It's really more of an oversight

**Comment by SonixApache** [comment]
@gbasood you can actually just climb into suit storage units yourself, I usually do it whenever I gotta go AFK as engineer
