### ISSUE TITLE
cARGO NOT WORK

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16473]
(WEB REPORT BY: delightedmerchant REMOTE: 172.93.109.202:7777)
# Revision
bd483ea93c1801b5fd45f38f3d5b8c01fa4cc7ad

# Steps to Reproduce

USE CAROG SHUTTLE COMPUTER

**Comment by Cyadox** [comment]
So apparently this is a NanoUI issue, as described by the discord chat:

>we're having some issues with cargo consoles giving the NT logo and nothing else reported by several players, is there a fix for this? they're mostly on 510

In essence, the interface opens but there's no buttons or text, and it's happening to several people.

**Comment by Shadowmech88** [comment]
This report is brain damage text material.

**Comment by PJB3005** [comment]
The bug here is that the cargo computer accepts non-ASCII inputs for orders, but can't display them. As soon as anybody uses them the thing blows up.

Pretty sure we do have a report and even if we don't I'm not keeping this one open so...

**Comment by PJB3005** [comment]
#14240 is probably the same issue though it doesn't state why.

**Comment by gbasood** [comment]
`var/reason = copytext(sanitize(strict_ascii(input(usr, "Reason:", "Why do you require this item?", "") as null|text)), 1, REASON_LEN)`
it definitely shouldn't be a non-ascii thing again

**Comment by gbasood** [comment]
```dm
var/reason = copytext(sanitize(strict_ascii(input(usr, "Reason:", "Why do you require this item?", "") as null|text)), 1, REASON_LEN)
```
seems like it shouldnt be non-ascii anymore, unless it's getting it from people's names

possibly related:
```
[03:55:52] Runtime in supplyshuttle.dm,156: Cannot read 0.value
  proc name: sell (/datum/controller/supply_shuttle/proc/sell)
  usr: Alfred Thorlen (denthamos) (/mob/living/carbon/human)
  usr.loc: The floor (201, 232, 1) (/turf/simulated/floor)
  src: /datum/controller/supply_shutt... (/datum/controller/supply_shuttle)
  call stack:
  /datum/controller/supply_shutt... (/datum/controller/supply_shuttle): sell()
  Supply shuttle console (/obj/machinery/computer/supplycomp): Topic("src=\[0x210bcaf5];send=1", /list (/list))
  /datum/nanoui (/datum/nanoui): Topic("src=\[0x210bcaf5];send=1", /list (/list))
  Denthamos (/client): Topic("src=\[0x210bcaf5];send=1", /list (/list), /datum/nanoui (/datum/nanoui))
  Denthamos (/client): Topic("src=\[0x210bcaf5];send=1", /list (/list), /datum/nanoui (/datum/nanoui))
```
```dm
line:
cargo_acct.money += (mat.value * 2) * P.amount // Central Command pays double for plasma they receive that hasn't been redeemed already.
```

**Comment by Pathid** [comment]
![](https://i.imgur.com/Qag2E63.png)
Thread says it's quote marks doing it.

**Comment by ShiftyRail** [comment]
apology for poor english
where were you when cargo was not working
i was using carog shuttle computer
'cargo not work'
'no'

**Comment by gbasood** [comment]
so effectively what needs to happen is html_encoding the input text
@PJB3005 i'm gonna make a guess that sanitize and strict_ascii are not intended to do html_encode's job yeah?

**Comment by PJB3005** [comment]
If it's a " breaking it my guess is the actual problem is the JSON encoder
not escaping it.

**Comment by gbasood** [comment]
html_encode on the reason field should fix that I believe

**Comment by PJB3005** [comment]
Don't HTML encode the reason that's a bad solution.

In general ALL our sanitization strategies are bad because you should serialize on output, not input.

**Comment by gbasood** [comment]
\>sanitizing input is bad
🤔 

It doesn't really matter where we sanitize here if it's changed in only one location.
html_encode after input or before display works, and unless you point out a specific thing to do otherwise, that's probably what we should do.
