### ISSUE TITLE
Plasmeme vampires dont take damage from space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16485]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
bd483ea93c1801b5fd45f38f3d5b8c01fa4cc7ad

# Description
As title

# Steps to Reproduce
be plasnigger
succ someone in space
# What you Expected
not to get succd in space and have the lad burst into flames
# What Actually Happened
you guessed it, no damage

**Comment by PJB3005** [comment]
Duplicate, just got 2 other reports.
