### ISSUE TITLE
BagelStation Brig has atmos alert if you open too many doors.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16486]
(WEB REPORT BY: fatbaldbastard REMOTE: 172.93.109.202:7777)
# Revision
bd483ea93c1801b5fd45f38f3d5b8c01fa4cc7ad

# Description
Open too many doors within brig and outside, and the atmos alert will block the brig.

# Steps to Reproduce
1) Open many doors
2) Watch sec lobby
3)???
4) FUCK

# What you Expected
Something good for once.

# What Actually Happened
Just brig being locked down from opening too many doors.

**Comment by DamianX** [comment]
![latest](https://user-images.githubusercontent.com/6307265/32519229-55a381a8-c40c-11e7-837d-e635c466e0da.png)

**Comment by Sooose** [comment]
sec lobby
Might have something to do with the distribution loop to the brig being off by default. Unless you turn on the valve in the back room, air will never come out of those vents in the brig.

**Comment by Exxion** [comment]
It's almost certainly yet another issue with removing `group_multiplier` that I overlooked

**Comment by Exxion** [comment]
Wait no it isn't zones don't merge across doors
