### ISSUE TITLE
Get Shit Done

### ISSUE THREAD

**Issue by ringringllingling** [d3athrow/vgstation13#16498]
I want to be able to crumple empty plastic bags into a small or tiny item that can be put inside your backpack or other containers, then remove them and unfold them back into a normal plastic bag.  I've posted a bounty at www.coderbounty.com, will pay 10 bucks.

**Comment by ringringllingling** [comment]
fucked up. oops.

**Comment by Exxion** [comment]
You can edit issues, you know
