### ISSUE TITLE
Bagelstation showers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16491]
(WEB REPORT BY: swagman55 REMOTE: 172.93.109.202:7777)
# Revision
bd483ea93c1801b5fd45f38f3d5b8c01fa4cc7ad

# Description
The shower curtains in the bathroom block the shower itself from being activated
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Sooose** [comment]
alt-click

**Comment by SonixApache** [comment]
still bad design
