### ISSUE TITLE
Disassembling Light Tiles yield more cable than used in construction

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#16504]
#### Description of issue
Disassembling a Light (Floor) Tile yields you five pieces of cable coil, when only two are used in construction.

#### Difference between expected and actual behavior
Expected to receive the same amount of cable back, instead found a way to produce infinite cables.

#### Steps to reproduce 
1. Apply cable to glass
2. Apply wirecutter to the wired glass
3. +3 cable coil

#### Length of time in which bug has been known to occur
Just discovered this

#### Server revision
2b6aa7b06aecca4a51cfa4b800cb771f35d625e9 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Pathid** [comment]
Really simple to fix. The salvage amount wasn't adjusted when the cost was reduced. I'll do that right now.
https://github.com/vgstation-coders/vgstation13/blob/5d73070f77f123bec728c93b414a21a0d7c40f5d/code/game/objects/items/stacks/sheets/light.dm#L19
