### ISSUE TITLE
Small amount of Potassium from Bananas

### ISSUE THREAD

**Issue by ringringllingling** [d3athrow/vgstation13#16508]
#### Description of issue
Disclaimer: Paying to add code in no way guarantees a merge request will go through.  At any rate, its only a dollar, so pull that stick out your butts.

I would like to request a feature so that you get a very small amount potassium from grinding bananas.  I think this will cause chaos and generally contribute to the fun of the game.  I have posted a dollar bounty on bountify and the link is here: https://bountify.co/vg-station-add-feature-to-grind-bananas-for-very-small-amounts-of-potassium

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
I like how grinding bananas gives just "banana" as a pure essence. I'm against this change, a compromise would be if there were 2 different varieties of banana or one was a mutation of the other.

**Comment by gbasood** [comment]
\>grind banana
\>add protein mix
\>add water OH SHIT MY HANDS
this is why you use milk in protein shakes kids

but anyways the reason that banana potassium doesn't explode you when you eat a banana and drink water is because the potassium is bound up in a more complex molecule or something
you'd need to do some C H E M I S T R Y to unbind it
