### ISSUE TITLE
Hot plates/Ghetto Cooking

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#16525]
Feature Request, and mostly so I don't forget.

Basically a cheaper microwave, created with metal and finished with two microlasers and screwdrivering.

Advantages: Cooking whereever there is power and materials. Very cheap and quick to make, literally all you need is the parts vendor or an autolathe.
Disadvantages: Low to moderate risk of a burned mess, regardless of whether the recipe was valid, say 10-25%. Longer timer (with better lasers reducing that, but of course never better than the microwave equivalent).  Burnt messes will 'break' it just like the microwave.

Codewise this will be either a child of microwaves or of the hotplate that may or may not be added to xenoarch.

**Comment by Riekland** [comment]
uh sweaty you forgot to set up payment
this isn't a charity anymore xx

**Comment by Cyadox** [comment]
Yes I totally wasn't going to code it without getting paid, just waiting on those sweet pomfcoins!

**Comment by west3436** [comment]
Implemented via #33569; use a frying pan on a burning barrel for all of your ghetto cooking needs.
