### ISSUE TITLE
grinding large material stacks can waste them

### ISSUE THREAD

**Issue by RealestEstate** [d3athrow/vgstation13#16530]
#### Description of issue
if you grind several sheets of a certain material like metal, the entire stack is consumed in the grinding process, but you only get a full beaker's worth of stuff. each material stack creates about 20 units juice, so if you put a stack of 50 metal, and a stack of 5 metal in 2 grinders and grind, both grinders will give you 100 units liquid iron and consume up all the metal, meaning you essentially just deleted 45 sheets of metal

#### Difference between expected and actual behavior
grinding plants makes it so that even if the grinder is full with plants, it will only grind up enough plants to fill a beaker without deleting the excess plants. I would think the same should apply to material sheets. put in 50 sheets, press grind, it uses up 5 sheets to give you 100 units liquid iron, there are 45 sheets remaining in the grinder's storage

#### Steps to reproduce 
put different sized stacks of materials into the all-in-one-grinders.

#### Length of time in which bug has been known to occur
I've known about it for at least 2 years, but I've just learned to cope with it and separate no more than 5 sheets for grinding. it's one of those code oversights that everyone knows about but they just learn to make a small adjustment to account for it.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
not actually a bug but it sounds like you'd want it to only grind up what it could hold in the output
possibly as a toggle so you can waste whatever extra you want, in case one stack of a thing only gives you a little over half, and it would prevent you from grinding the rest up because it'd overflow for instance
