### ISSUE TITLE
I'll just leave this here...

### ISSUE THREAD

**Issue by Hugh-G-Rection** [d3athrow/vgstation13#16545]
Since this is clearly how we do things now.

https://bountify.co/antag-datums-for-ss13-vg-station

I want ninjas for Christmas, goddamnit.
SPACE NINJAS.

**Comment by Shadowmech88** [comment]
Antag datums is a project with multiple people working on it, so I'm not sure how the money would be divided up.

**Comment by ShiftyRail** [comment]
SLIPPERY
SLOPE

**Comment by Kammerjunk** [comment]
>7 days left

You've lost fifty freedom bucks this day

**Comment by ShiftyRail** [comment]
>You've lost fifty freedom bucks this day

Starving kids in Africa could have eaten those datums

**Comment by Blithering** [comment]
![datums](https://user-images.githubusercontent.com/15067109/32691792-fa6ce5bc-c704-11e7-9b0b-dfc0039da2b4.png)
Where do I collect the money?

**Comment by Killette2** [comment]
![image](https://user-images.githubusercontent.com/5169310/32693563-189d3e10-c6fb-11e7-81f6-b5109ce0c732.png)
Space Jesus, this seems like it's getting out of hand.

**Comment by Hugh-G-Rection** [comment]
So what you're saying is I need to up the bounty, yeah? Alright, I'll see what I can do sit tight

**Comment by Killette2** [comment]
inb4 pages full of feature reque-
![image](https://user-images.githubusercontent.com/5169310/32693721-87554abc-c6fd-11e7-9235-f860139759ad.png)
st for cash

**Comment by ringringllingling** [comment]
ha!  i did it!  I memed!
my first meme.. (sniff)
so proud, much wow

**Comment by ringringllingling** [comment]
oh wait, those are all dated 2016
