### ISSUE TITLE
Syndiepaper is absurdly easy to escape from, also makes you pipe Houdini

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16550]
### Description of issue
Not only is the wrapped person free to use items, they can bypass the measly resist time by simply clicking on the package with an empty hand.

#### Additional bug
It's not completely useless however. I've found that by wrapping _yourself_, and mailing yourself by click-dragging to a disposal bin, you can then resist out in order to warp out of the pipe in an arbitrary spot.

### Difference between expected and actual behavior
"This extra-strong wrapping paper is perfect for concealing bodies or trapping a victim with no escape. Simply apply directly to the victim and wrap them up into a regular-looking delivery package. Takes about three seconds to wrap."

### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
A while back people complained that there shouldn't be a way to "handcuff" someone so that they can't escape on their own (even though this is functionally no different than walling someone off or welding them into a room with no tools) and they made it possible to resist out but never changed the description.

🤷‍♂️

**Comment by Pathid** [comment]
They made it 10 seconds (which itself is ridiculous for something that costs 4 TC even if you get multiple uses), but that's not even currently relevant in the game. Like I said, you can instantly free yourself by clicking the package with an empty hand while inside.

**Comment by Killette2** [comment]
What about the straightjacket?
