### ISSUE TITLE
Two people cuffing someone simultaneously results in one pair getting lost

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16552]
#### Steps to reproduce 
Get three people, two pairs of cuffs
Two of them try to cuff to the third person

#### Expected behavior
Last person to complete the cuffing should fail and keep the handcuffs on them

#### Actual behavior
A pair of cuffs is forever lost inside the third person's `contents`
![image](https://user-images.githubusercontent.com/6307265/32691812-b52dc774-c70d-11e7-9e36-2cde4121ca89.png)

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
haven't we fixed this bug like three separate times now
