### ISSUE TITLE
Meta Club Perma needs a remapping

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#16551]
it's shit, there's jackshit to do in there besides reading smut on the computer and planting weeds wich will eventually get you killed because of the toxins
there's no seed vendors or grinders so you can't cook good shit to waste your time
no b-ball court to play against your fellow inmates
meta perma is no fun, i always enjoyed getting perma'd, but i'd rather ghost and play as a derelict mommi than to live on metaclub perma.
escaping it is a pain in the ass too while we are it since there's grilles outside cucking you from escapes.
![shite](https://user-images.githubusercontent.com/20007336/32691064-115f6a66-c6e1-11e7-840b-a5d85dede5ec.png)

every perma has it's own gimmick
Box - Chickun and Chem master enable you to be a farmer
Deff - Perma's inside of the station, also really huge and has a b-ball court
Bagel - Gulag mining
Packed - Comfy and Smol
Meta - ???????

**Comment by DrSnips** [comment]
Meta's gimmick is you go there to rot and die like all permas should be. If anything it's good for sec that you can't escape why should perma be designed around escaping? To be fair it could really use some some to not make it bland.

**Comment by SonixApache** [comment]
you could try to train the snek there to fetch an ID card for you

**Comment by Blithering** [comment]
It's not a matter of being escapable, it's just box perma flipped and with half the stuff removed leaving what's left to be utterly useless. For example the microwave was left in, but the seeds mapped to spawn don't allow for any cooking

**Comment by Riekland** [comment]
Deffs perma was a fucking mistake, it's just empty space
All this needs is botany machines to fix it

**Comment by Sooose** [comment]
If the goal of a perma was to rot and die solitary would do the job just fine. Perma is there to give people a chance to stay in the round without being borged. Giving them something to do or a chance to escape is a good idea.
