### ISSUE TITLE
Fist spell balance discussion

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16563]
Now that this spell has been around for a while and wizards have incorporated it into builds, there's been talk in deadchat and in the thread that it's led to some very one-sided and uninteresting rounds. Should it be removed? Reworked? Kept? General complaints about fist balance go in here.

If it looks like there's enough support for removal then I will make a PR to comment it out of spellbooks.

Related issue: #16503

**Comment by jknpj** [comment]
The first thing that needs to be done is to fix its targeting, then we can talk about balance.

![fist](https://user-images.githubusercontent.com/17928298/32756136-b2cb5df8-c8bf-11e7-8dab-c209ddd3a379.png)

**Comment by Shadowmech88** [comment]
Do we know yet whether the targeting issue is specific to Fist, or if it affects all long-range targeted spells?

**Comment by eplgr** [comment]
Today: 
One wizard killed **the whole station in highpop**. 
Nowhere to hide, no way to counter. He was stunlocking everyone (including cyborgs), which obviously led to super easy kills. No one even managed to get close to him, since the range is the whole screen.

This behaviour is extremely bad. Like I stated in the discord, overpowered stuff could make good stories happen, but this is way beyond that. This is worse than EI NATH and the unnerfed version of the lightning spell together.
There was absolutely 0 effort, and he solo killed the whole station.

**Comment by Praecordia** [comment]
up the cooldown, change it so it doesn't hit the whole screen/can't hit people through walls
meme spells shouldn't be able to massacre everybody on station

**Comment by Allspice** [comment]
Did they have like any damage-modifyicinating ability to boost the punch damage perhaps

**Comment by ghost** [comment]
I really don't like that it's a massive AoE. That's not what comes to mind when I think "fist", it's more like a weaker, spammable blood boil.

But besides the thematic dissonance, "huge instant cast AoE" is dumb right from the start. That's basically as low-effort, no-skill as you could make the spell, the only thing it needs is line of sight (and wiz is the most mobile antag in the game!). My opinion is that it should become targeted in some way. Maybe only punch directly in front of you, like a 3-wide fireball or something.

One thing's for sure in my mind, Fist is a bad spell at its concept as is right now, it will never be fixed without basically reworking it into something else. "Concept" being "huge instant cast AoE".

**Comment by ghost** [comment]
Also it's fucking retarded that a spell called "Fist" works while stunned and cuffed.

**Comment by Pathid** [comment]
If it's a matter of the targeting being borked, what about just removing it on that basis? Anybody mind?

**Comment by DrSnips** [comment]
Posting my suggestion here to make fist more like magic missile where it summons "fists" that go after people as well as making the cool down a lot higher. Consider it more of a damage oriented MM with only a chance to stun.

**Comment by Blithering** [comment]
Is the punch affected by armour?

**Comment by Shadowmech88** [comment]
It uses the `unarmed_attack()` proc just like regular punches do. It is affected by all the same factors that regular punches are.

**Comment by Killette2** [comment]
suggestion
-fist are magical, you get 10-20 fist ammo
-when you punch someone a fist is created at their location
-only wizards can pick up fist
-you passively generate fist
-bonus points if you can charge multiple ammos into a really big fist (without direct scaling) that only gives 1 fist return when picked back up

**Comment by Exxion** [comment]
Replace punching everyone on screen with @CptWad's suggestion from years ago
Remove cooldown on unarmed attack only
And to prevent autoclickers from being strictly better than clicking by hand, make the ability last for a certain number of attacks rather than a certain amount of time, or scale the cooldown by the number of attacks, or something

**Comment by Aurx** [comment]
I don't think there's any way to make no-cooldown, autoclicker, and balance fit together.  

If it lasts n attacks, the autoclicker gets you those n much faster, reducing the time you spend in melee.  
If it increases cooldown, then you've got Ei Nath 2: Instakill Boogaloo.  Who gives a shit about cooldown when you can kill three people in as many seconds?  
Even making it last n clicks would mean they'd just have to stun before instagibbing.

**Comment by Exxion** [comment]
I believe you'd have to punch someone well over a hundred times before you start having a solid chance of even punching a single limb off
And there's also a click delayer below the attack delayer, limited to... I don't actually know exactly. Faster than the attack delayer, but way under 100 clicks per second.

**Comment by Blithering** [comment]
Given the low damage of unarmed attacks, if the line of sight problems are fixed it shouldn't be too bad. Anyone wearing even basic armour should be   able to absorb most of the hits

**Comment by Aurx** [comment]
Wizzymen get hulk.

**Comment by Pathid** [comment]
At least some of these Fist steamrolling rounds were with the Scrying Orb, as I understand it. Even if the targeting bug were fixed, wouldn't that combination stay as effective as it is?

**Comment by Exxion** [comment]
If you keep the spell in ghost form, that is even more of a bug than the line-of-sight thing

**Comment by Shadowmech88** [comment]
I believe he's talking about the X-ray vision granted when you buy the scrying orb.

**Comment by Exxion** [comment]
Ah.
Then yes, that combination would remain equally effective, unless it used actual line-of-sight instead of just vision
`view(user.loc)` instead of `user`
Or `dview()` because ignoring darkness might make more sense

**Comment by Blithering** [comment]
A three spell combo being powerful is nothing new I suppose, blink emp lightning was pretty common til lightning broke. Could make it riskier by also making the spell kick any vending machine in sight

**Comment by Killette2** [comment]
What do you mean that it becomes broken when a wizard puts a bunch of points into a single gimmick?!
