### ISSUE TITLE
You can have 3 starter cultist

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16565]
While looking at antag code I noticed that you can start a cult round with only 3 people. I've experienced this in the past and ahelped thinking it was a bug but apparently this is intended behavior.
Why is this a thing?

https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/gamemodes/cult/cult.dm

**Comment by Kurfursten** [comment]
I don't think that's intended behavior, because the code very clearly lists required_players_secret as 15.

Although there is probably also some secret repo stuff on this as well

**Comment by Killette2** [comment]
required_players = 5
	required_players_secret = 15
	required_enemies = 3
	recommended_enemies = 4

**Comment by DeityLink** [comment]
Now an intended feature of Cult 3.0, on low populations.
