### ISSUE TITLE
Arcane Golem Casts Doppelganger

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16567]
(WEB REPORT BY: eenkogneeto REMOTE: 172.93.109.202:7777)
# Revision
03ceedfc332de77dad3e8a6d8e7e2542ae2b6c96

# Description
Regardless of what it says, Arcane golems can infact cast doppelganger!
# Steps to Reproduce
Take Doppelganger
Take Arcane Golem (Optionally upgrade count)
Summon the Arcane Golem/s
Without moving, Start spamming Doppelganger
# What you Expected
One doppelganger comes out because the golems wont cast it as per their description
# What Actually Happened
Four come out per cast, Up to 20 doppelgangers per casting of the arcane golems when using 3.

I was hesitant to report this simply because I don't want to actually see people use it ingame.
They can also use Snake Form, But it has its own built in checks and balances unlike doppelganger, so its not really an issue.

**Comment by EenKogNeeto** [comment]
Reached 1200 doppelgangers on test server in under 20 minutes with this for reference. Not as easy to do on the main server because you need more spells to get around, but you can still swarm maint and stuff pretty easily, not to mention just teleporting into medbay and swarming it with a few dozen clones.

**Comment by SonixApache** [comment]
YES

**Comment by Killette2** [comment]
What really? When I tried this on the test server it didn't seem to work

**Comment by EenKogNeeto** [comment]
Must be standing physically ontop of the golems, This seems to bypass a lot of the spell restrictions, but does not enable them to summon additional golems.

**Comment by Exxion** [comment]
That seems like a pretty significant detail.

I'm going to go out on a limb and say indentation mistake
