### ISSUE TITLE
Defficiency Bar does not have a fire alarm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16562]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
03ceedfc332de77dad3e8a6d8e7e2542ae2b6c96

# Description
The bar in Defficiency doesn't have a fire alarm. Funny, since that's the most likely place to catch fire.
# Steps to Reproduce
set deff's bar on fire
# What you Expected
fire alarm saves the day
# What Actually Happened
everyone died

**Comment by SonixApache** [comment]
inb4 feature
