### ISSUE TITLE
Mechanical Debris Artifact has no sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16575]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
# Revision
03ceedfc332de77dad3e8a6d8e7e2542ae2b6c96

that's exactly what's on the title
1. Dig Mechanical Debris small artifact
2. see that nothing popped from the rocks
3. Alt-Click the rock tile and see that the Mechanical Debris actually has no Sprite

**Comment by Kammerjunk** [comment]
Looks like wrong icon got set because of copypasta, see [finds.dm](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/research/xenoarchaeology/finds/finds.dm)
