### ISSUE TITLE
Cyborgs with offline actuators can't examine

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16570]
#### Description of issue
Cyborgs with offline actuators can't examine. ~~No error message, no "there's something there but you can't see it", they just can't.~~ Correction: "you can't see it" message appears when examining but not when using the shift-click shortcut.

#### Difference between expected and actual behavior
Expected to at least be able to use examine with a broken actuator. I think even locked down borgs can examine, but I'm not sure.

**_Edit_**: Turns out _locked down_ borgs _can_ with the verb or right-click. Broken actuator borgs still can't.

#### Server revision

Game: 03ceedfc332de77dad3e8a6d8e7e2542ae2b6c96 
Patches: d906516f81933e3d174db4567c16a7fbf960ebe6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
Seems like the camera should be the component tied to disabling examine

**Comment by Pathid** [comment]
> Seems like the camera should be the component tied to disabling examine

Apparently they both disable examine. Either one going offline disables it.

**Comment by jknpj** [comment]
This isn't a bug at all!
