### ISSUE TITLE
The chance of getting a Losetta stone is absurdly low.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#16574]
The number of things that need to happen to get a losetta stone is ridiculous. First off, lets just assume you have telekinesis on a round where the singularity is active. Now you need to get close to it and try and pull a losetta stone out. Unfortunately this only has a 5% chance of success, with a terrible penalty for failing. If you fail the check to pull the stone out, you get a 50% chance of getting lucky and being gibbed. If you lose the coin toss, you get erased with all former cloning backups also being rendered useless. All of this for merely getting the chance to pull a stone out that allows anyone who touches it to learn the same randomly chosen language.

I liked the idea and concept for getting this item so I hope this won't turn out to useless additional content. Should it be easier to get? Leave it as it is? Harder to get? Looking for opinions.

**Comment by MadmanMartian** [comment]
Wearing certain psychic amplifying tech could help.

Consuming some mind-altering spice from xenobotany?

Sitting in a psychic amplifying throne that feeds on the lifeforce of whatever is sitting in it?

**Comment by SonixApache** [comment]
step 1: don't touch black holes, not even in your mind
step 2: delete the stone if you care so much

It's not about 'useless content' or 'how can we make people get this', it's one of those little rare hidden things that can happen. One could even call it, dare I say, *fun*. Just leave it alone, man.

**Comment by Blithering** [comment]
I like the idea of people putting on psychic amplifiers and purple robes in an attempt to better their odds of success

**Comment by Sooose** [comment]
@SonixApache I mean, sure we can leave it at that. Its not something you _have_ to get. I just don't see it as something rare that might happen. With the 5% chance of success and the prerequisites already being difficult, people won't even attempt to grab it.

**Comment by MadmanMartian** [comment]
rude @SonixApache

**Comment by SonixApache** [comment]
*nuance*

**Comment by Exxion** [comment]
It's a (literal) meme item added as a meme way of "fixing" a meme bug
