### ISSUE TITLE
No actual way to create the Chemical storage fridge

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16578]
(WEB REPORT BY: valkyrieskies REMOTE: 172.93.109.202:7777)
# Revision
03ceedfc332de77dad3e8a6d8e7e2542ae2b6c96

There's no actual way to create the chem storage fridge in the game despite it being a pretty important piece of equipment.

**Comment by DamianX** [comment]
Soldering iron on the smartfridge board?

**Comment by EdXbtkOEwGw** [comment]
Aren't smartfridges a straight upgrade from chemfridges anyways?

**Comment by Exxion** [comment]
The opposite. The chemistry fridge is a direct upgrade to nearly every other variety of smartfridge.
The kitchen smartfridge can hold seeds and the xenobio smartfridge can hold slime extracts, but as far as I can remember, the chemfridge can hold every other item any other smartfridge can hold

**Comment by SonixApache** [comment]
Isn't the chemfridge the base class that you're not supposed to be able to get?

**Comment by Exxion** [comment]
By chemfridge, do you mean the Smart Chemical Storage that spawns in medbay at roundstart, or the other medical smartfridge that is unobtainable?
Because I'm referring to the former.

**Comment by MadmanMartian** [comment]
Solder the smartfridge board

**Comment by Exxion** [comment]
Alright sorry
Pointless to obtain
