### ISSUE TITLE
squid martians are immune to explosive maracas.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16585]
(WEB REPORT BY: boosterrooster REMOTE: 172.93.109.202:7777)
# Revision
dc1c0dbbcf447f7a9e40003dacc52fe27127821a

# Description
I threw three of the explosive maracas at a one and it hit them directly and it didnt die.
# Steps to Reproduce
Toss a few at a those squid leg freaks.
# What you Expected
Them to die after at least the second one.
# What Actually Happened
They kept holding their own set of maracas and throwing them back at me while I sent into crit after one of them.

**Comment by MadmanMartian** [comment]
well this is beautiful. I wonder if they're just entirely immune to explosions

**Comment by Kurfursten** [comment]
Martians do not override ex_act()
Carbon does not override ex_act()
Living does not override ex_act()
Mob does not override ex_act()
Martian, therefore, calls this ex_act() code from atom level:

`return`

Which makes them immune both to bombs and drills.

**Comment by Pathid** [comment]
Fairly sure they're also immune to pacid (touch).

**Comment by Hugh-G-Rection** [comment]
That's spess, baby! Stamp FEATURE on this and call it a day :+1:

**Comment by SonixApache** [comment]
this is not metal slug compliant
