### ISSUE TITLE
Wide wheelchair seems to let you teleport the nuke disk off-station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16586]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
dc1c0dbbcf447f7a9e40003dacc52fe27127821a

# Description
It seems that if you are riding the wide wheelchair you can pass through a teleporter off the Z-level, together with the nuke disk.
# Steps to Reproduce
Acquire nuke disk, acquire wide chair, mount chair together with others, set up teleporter, have other pilot enter teleporter while you are seated
# What you Expected
bounce off the teleporter because of the disk
# What Actually Happened
went through the teleporter with the disk

**Comment by Kurfursten** [comment]
What is the wide wheelchair?

**Comment by SonixApache** [comment]
`/obj/structure/bed/chair/vehicle/wheelchair/multi_people`

**Comment by Kurfursten** [comment]
We have exactly one nuclear disk, why haven't we just had it check its own location in process() by now? The performance cost would be very light.

**Comment by DamianX** [comment]
It does check its location in `process()` but it only replaces itself if it's in nullspace, not in another zlevel

**Comment by Kurfursten** [comment]
So let's fix that

**Comment by SonixApache** [comment]
wouldn't that cause the disk to pop back to the station when the ops leave on their shuttle

**Comment by SGuivenne** [comment]
Only if they failed to properly arm and drop the nuke on the station, with the disk in it, like they are supposed to.  Granted, that ALSO could be avoided by adding in the syndicate z level as acceptable also.

**Comment by SonixApache** [comment]
>disk in active nuke

nononononono
you take the disk out
so they can't just hit the [kill nuke] button

**Comment by Pathid** [comment]
>wouldn't that cause the disk to pop back to the station when the ops leave on their shuttle

Not to mention the crew has to be able to take the disk on the escape shuttle for crew major victory.

**Comment by Kurfursten** [comment]
It would be really easy to not teleport back to Z=1 if the disk isn't on a shuttle or pod tile.

**Comment by Exxion** [comment]
Just whitelist Z2 too

**Comment by Aurx** [comment]
Z2 would need to be whitelisted for death squad and nuke op things anyways.
