### ISSUE TITLE
Metaclub Transit Tube air transport

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#16582]
#### Description of issue

The Transit Tube between the MiniSat and Engineering Foyer keeps transporting air from the MiniSat to the Engineering Foyer

#### Steps to reproduce 

>Look at Transit Tube
>Watch it transport air from the MiniSat to Engineering Foyer
>Get an excess pressure alert in Engineering Foyer and low pressure on the MiniSat West Wing

#### Specific information for locating
Metaclub, the only map with a Transit Tube

#### Length of time in which bug has been known to occur
Since the recent atmos changes

#### Server revision
dc1c0dbbcf447f7a9e40003dacc52fe27127821a

**Comment by PJB3005** [comment]
@Exxion

**Comment by Exxion** [comment]
Absolutely magical

**Comment by PJB3005** [comment]
Also

> Metaclub, the only map with a Transit Tube

Really shows how much people play xenoarch eh

**Comment by Exxion** [comment]
Anyway this should be a simple fix
I've just been busy for a while
I'll do it today
