### ISSUE TITLE
Remove pAI from fossilized Plants?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16589]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
470847cb9802226b189ee25e956ca1f3d4776004

# Description

Fossilized plants give you the option to remove pAIs
# Steps to Reproduce

From what can be seen multiple fossilized plants can be recovered and all will display this bug.
# What you Expected

For pAIs to not be an option to eject from goddamn petrified biological material
# What Actually Happened

Option to eject pAIs, ability to infinitely eject nothing from fossils.

**Comment by Killette2** [comment]
It makes sense that when you try nothing happens, so this doesn't sound like a bug to me. 🍆 

edit: added an eggplant to show it was an attempt at humor

**Comment by Shadowmech88** [comment]
I believe objects which do not have pAIs in them are not supposed to display the verb at all, which would make this a bug.

**Comment by SGuivenne** [comment]
@Killette2 thats the thing, something happens, using this verb tells you "you eject  from the object"

as in its ejecting something unnamed and nonexistent.

**Comment by Blithering** [comment]
Lots of random objects have this verb left in, I've seen pAI lockers, sandwiches, and hats
