### ISSUE TITLE
Player controlled mice forcibly moving around when hungry is extremely annoying and unfun

### ISSUE THREAD

**Issue by EdXbtkOEwGw** [d3athrow/vgstation13#16599]
#### Description of issue
When hungry, even player-controlled mice are forced to move towards the first food item they see. This is extremely annoying because you constantly have to fight your movement, and especially so because your movement targets the first food item you see and will not switch target.

#### Difference between expected and actual behavior
Expected: Not this
Got: This

#### Steps to reproduce 
Play mouse, become hungry (which will happen ALL the time), pass in front of a vending machine with the fire wire activated, literally can't stop moving, your ventcrawl action is constantly interrupted, die in frustration

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/simple_animal/friendly/mouse.dm#L105

#### Length of time in which bug has been known to occur
Ever since whoever decided to add this garbage added this garbage.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
have you tried eating to reduce your hunger

that said your other two issues are the actual issue that causes this

**Comment by EdXbtkOEwGw** [comment]
I believe this is an issue too. This feature accomplishes nothing except being extremely annoying.

**Comment by Hugh-G-Rection** [comment]
I came here to squeak at you.

**Comment by gbasood** [comment]
literally just check if the mob is inhabited before causing movement via ai logic

**Comment by PaulRitter** [comment]
was fixed
