### ISSUE TITLE
Unable to use the search bar in View Variables

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#16596]
https://i.imgur.com/oBJRjEO.png

why is it happening

why can't I search in vv anymore

unid suggested updating java/ie and I updated java and had no updates for ie

**Comment by Exxion** [comment]
Have you tried clearing your BYOND cache?

**Comment by TheFriggenSawbones** [comment]
yeah, both ways. no dice

**Comment by TheFriggenSawbones** [comment]
I tried an older revision local server and the test serb and no LUCK. It happened after one of these two things, Firefox Quantum pushed their shit and after I installed the recent big windows update god bless

**Comment by Kurfursten** [comment]
It's not just you, I mentioned this on discord

**Comment by TheFriggenSawbones** [comment]
god bless i'm not alone

**Comment by PJB3005** [comment]
This aint botany man.

Joking aside, I've had this too.
