### ISSUE TITLE
ERT could use a ballistic option

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#16609]
ERT currently spawn with eguns and advanced eguns as weapon choices, this leaves a bit of a problem in the event something EMPs them. 
I think it would be a good idea to put a rack of the currently unused .45 pistols in the ERT prep areas, as it would give them a ballistic option that's a midpoint between sec glocks and deathsquad's matebas, and give them more flexibility.

**Comment by Killette2** [comment]
Their guns still recharge for a reason. Every time bullets and bleeding are introduced something goes terribly wrong with stun shells being the only exception.

**Comment by SonixApache** [comment]
NT USPs

**Comment by Blithering** [comment]
Those are the ones yes, forgot the name for a bit. 
EMP breaks AEGs, they no longer recharge themselves, and as far as I know there's no way to fix them. It seems to be an intended behaviour, as they get a different icon when this happens. Also something going terribly wrong is usually the reason an ERT is called in the first place

**Comment by Pathid** [comment]
Yes, AEGs have a rising chance to permanently break with each time they're EMP'd. (They also irradiate the holder each time too.)

**Comment by SonixApache** [comment]
ideaguy idea: ERT ID + something = .45 ammo
sectech vending machines maybe?

**Comment by Blithering** [comment]
This was actually fulfilled, ERT get USPs these days. Still, doesn't need reopening.

**Comment by robintime** [comment]
oh shit nice i didn't actually know that!
