### ISSUE TITLE
Allow vampires to upgrade thralls

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16608]
If you thrall someone who's already thralled (costing ??? amount of blood) we could make them a vampire while still remaining under the rules of being your thrall. Would be more fun instead of just having them a slave, would allow vampires to be more aggressive rather than a bat dude who uses guns, and would be more accurate to vampirism while allowing more people to join in on the fun.

**Comment by Killette2** [comment]
Another thing this will help with is make it so vamp isn't always vampstended since they have worse tools than lings already

**Comment by Aurx** [comment]
I don't really see how this will change much, aside from making it easier for a starter vamp to have their cover blown by an asshat thrall-vamp.

**Comment by Blithering** [comment]
The main problem with vamps is their slow startup, by the time you have 600 blood to drop on a double thralling that problem has been passed. Plus with that blood you could instead thrall two people who would help you get blood instead of taking it for themselves

**Comment by Killette2** [comment]
It's not about hoarding blood as much as sharing the fun. I also intend for this to be optional (if a thrall annoys you to give him vamp just tell him to walk into space)

**Comment by Sooose** [comment]
I think its easier to get more people in on the fun by thralling two people instead of turning one into a vampire. Maybe make turning them require something other than just double the cost of a standard thralling.

**Comment by Blithering** [comment]
I'd say rather than making late game vamp stronger, give them something for the early game to help them get rolling, like perhaps they could choose  a bonus from a list that suits different play styles. Unrelated note, phone posting and my auto-correct thinks lategame is supposed to be Kamehameha. Weeb phone wants dragon ball vamps

**Comment by Killette2** [comment]
Give vamps kamehamehas

**Comment by Jubisloviu** [comment]
vampire clans from WoD when?

**Comment by Aurx** [comment]
>(if a thrall annoys you to give him vamp just tell him to walk into space)

Just tell him to march up to the chef and volunteer for gibbing.  Or have him stand under a shuttle.  Or feed the singularity / supermatter.  Or just jump out an airlock suitless and not try to come back, off-z corpses rarely get recovered.  
If he's a shit he'll disobey any suicide order, if not you've got plenty of ways to kill him forever without spending 300 blood and risking some chucklefuck seeing it and screaming about vamps.

**Comment by Exxion** [comment]
I like the idea, in theory.
In practice, though, as Blithering said, it doesn't really fit the power curve vamps currently have.

**Comment by Blithering** [comment]
What if the vampire holy protection was reversed, so at 0 blood, before you have any unholy abilities to speak of, you can resist the chapel and holy water, but the more blood you drink and the more you unlock vampire powers, the greater effect holy things have on you? It would help stop vampires being dragged to the chapel for testing before they can get any progress that would allow them to evade capture, and fits thematically. Vampires trying to avoid drinking blood altogether and use their vamp time to just do regular traitor stuff can be killed just as easily as any human

**Comment by TheFriggenSawbones** [comment]
tbh just add vtm clans lets have dope tremere vampires casting blood strike and Auspex

**Comment by Killette2** [comment]
tbh I'd like anything to make vampires a better antagonist that aren't fearing for their lives if they do a single vampiric thing

**Comment by SonixApache** [comment]
think of something better than this shit then @Killette2

**Comment by Killette2** [comment]
Since when did vampires not turn other people into vampires in stories?

**Comment by Exxion** [comment]
It's a gameplay issue, not a thematic one.
Vampires start out weak, but at maximum power are already nigh invincible. If you want to deal with them being scared to act, you need to increase their power in the earlygame, not the lategame.

**Comment by Blithering** [comment]
How about family heirlooms, consumables using the wizard potion base that give vampires a leg up to start. 
Ideas:
Coagulated bloodstone, consume to gain a small amount of usable blood
Wing of bat, one time use bat form
Homeland soil, increases regeneration from coffins after consumption
Brand name cereal, joke item but tasty
Defiled holy water, prevents holy damage for a time
Weirder idea
Malvakian crest, gain permanent hallucinations, also hear snippets from ghost chat

**Comment by Killette2** [comment]
What if we change the vampires starting blood to give them a headstart and see how that affects the rounds compared to previous vamp rounds? Often I see vamp rounds where they get 0 blood. The starting tools are terrible and beg you to rely on things like chloral,  so this could be what we could do until we think of a better idea.

**Comment by SonixApache** [comment]
how about we don't do that till you come up with and code a better idea

**Comment by Killette2** [comment]
How about we do nothing and keep vampstended you hypocrite
![image](https://user-images.githubusercontent.com/5169310/33150742-e72a4e6c-cfa2-11e7-8c86-7699d51400f6.png)

**Comment by SonixApache** [comment]
that shitty reply somehow convinced me
maybe more vampires would be an improvement to the gamemode

**Comment by Kurfursten** [comment]
There seems to be some bizarre disagreement about what exactly the problem is with vampire. Let's be clear: don't apply a buff if you don't know what the problem is. If you **do** know what the problem is, don't apply a buff that doesn't solve that problem. If you think vampires have a weak early game, what in the world are you doing trying to buff their ultra-late game where they have thralls and extra blood to spend "upgrading" them? Similarly if you want to buff early game vampires, do it in a way that doesn't make their lategame even more powerful. I don't know if you guys even remember 2 years ago when Kilkun made half of vampire's abilities cost literally nothing (0 blood) but it was awful.

For my part I've always thought it was bizarre that holy water works exactly the opposite as you would expect for good gameplay on vampires. Holy water will burn a vampire who is yet to kill a single person, meaning it's best used to antag test people who have no reason to be suspicious. Meanwhile it takes HUNDREDS of units directly forcefed to deal any damage at all to a mature vampire running around screeching in a cape with thralls, _**that's**_ the kind who you should be fighting off with holy water spray.

**Comment by Killette2** [comment]
You have a point. Your and blithering's idea is starting to grow on me. I still like the idea of holy water used on mature vampires but I feel like they should be able to resist. For example, using holy water on a matured vampire makes them lose some of their stored blood which will help them resist the holy water but at the same time they will scream. You would brutally wear them down as if it was a real exorcism instead of them instantly ashed for example by the water.

My original idea wasn't intended for balance as much as it was for fun, where it would allow vampires to go more loud instead of being stealthy from start to maturation. My idea of giving more starting blood to vampires was since most of the complaints that vampires have too difficult of a time starting out. More starting blood would help speed up the rounds while not really changing any mechanics to keep from a sudden balance shift.

As for blood costing abilities, I think it would be nice if some (weaker) abilities were free under the condition that you have X amount of blood like a catalyst. This would allow vampires to use abilities more strategically where you either use your strong abilities or hold your blood in case you get outed and need to use a bunch of your weaker ones to escape, or if you wanted to do both it would force you to murder more and be more antagonistic. I know one of our current spells requires an amount of blood as a catalyst but cannot remember which one and the wiki is down.

**Comment by Kurfursten** [comment]
Kilkunvampire was awful. Screech and glare every cooldown because there was no cost, and batform + shadowstep is like having both blink and jaunt. You cannot make glare and screech free. They are not easily blocked, do not require aim, and have no projectile.

**Comment by Killette2** [comment]
You can't compare shadowstep to blink so freely. It requires a dark space (which you can't see when you're matured and get x-ray+nightvision. pretty counterintuitive if you ask me) and has a much longer cooldown. Also wizards who use the better versions are human while vampires are not.

**Comment by Kurfursten** [comment]
The range on shadowstep is quite long, in my experience you can always shadowstep to maint. In that way it's actually better than blink for escaping because it almost always guarantees you teleport behind a door and dense walls to slow pursuers and block lasers. (You can also make darkness anywhere you want by simply smashing a light in 2 hits from a crowbar)

Shadowstep **is** one of the tamer spells though, that I will agree, compared to the others I listed. Thank Pomf that back when Kilkun was here, bat form was just mist form and didn't summon bats as a bonus. Could you imagine?

**Comment by Blithering** [comment]
Perhaps the inverse weakness would work  if using the shadow form ability would give holy water resistance as well, so you can go loud if you get outed late game, or try and hide your identity and risk being exposed by holy water.

**Comment by Killette2** [comment]
The bats barely matter tbh. They're like worse baby space carp

**Comment by Kurfursten** [comment]
Doppelgangers hardly matter they said
It won't really be that big a deal if someone sits in maint spawning them over and over they said
You can't even control them they said
Just merge it they said

**Comment by Blithering** [comment]
Bats on their own are a distraction, combined with screech and a space adjacent window they can wipe a department. Magboots do nothing if you're already floored from the stun.

**Comment by Killette2** [comment]
bats and dopplegangers are hardly a comparison. The absurd amount of blood and cooldown time to make a weaker mob which can't stun you isn't close at all.

**Comment by Kurfursten** [comment]
Did you get lost somewhere in this conversation where we were talking about when Kilkun took blood costs off of most vampire spells, including mist form?

**Comment by Killette2** [comment]
Even without blood the cooldown is the major issue

Doppelganger's cooldown is 30 unupgraded, 10 fully upgraded

Vampire's cooldowns are

summon bats - 2 minutes (and cost a whopping 75 blood, 2 bats)
jaunt - 1 minute (30 blood, 1 bat)
blink - 20 seconds (20 blood)

Now let's take a look at how scary these bats are


/mob/living/simple_animal/hostile/scarybat
	name = "space bats"
	desc = "A swarm of cute little blood sucking bats that looks pretty pissed."
	icon = 'icons/mob/bats.dmi'
	icon_state = "bat"
	icon_living = "bat"
	icon_dead = "bat_dead"
	icon_gib = "bat_dead"
	speak_chance = 0
	turns_per_move = 3
	response_help = "pets the"
	response_disarm = "gently pushes aside the"
	response_harm = "hits the"
	speed = 5
	maxHealth = 20
	health = 20
	flying = 1
	mob_property_flags = MOB_SWARM

	harm_intent_damage = 8
	melee_damage_lower = 10
	melee_damage_upper = 10
	attacktext = "bites"
	attack_sound = 'sound/weapons/bite.ogg'

A whopping 20 health which can be taken out by one laser shot, which when hunting vampires security is likely to have on them. I could not find the health a doppelganger has. I assume it is the default, which I would also assume is 100 because they certainly do not die to one laser shot.

The idea of spawning a bunch in maint to be effective is absurd under the current conditions. You are paying a cost for a worse mob on a worse cooldown. Since they can swarm according to the code (even if I'm unsure that behavior happens) they might fill some niche but I have yet to see this happen with the cost and cooldown they currently have.

**Comment by Kurfursten** [comment]
You seem to be getting confused here. You keep talking about a cost, I'm discussing why it would be a bad idea to remove that cost. You've made me reiterate this point twice, I would appreciate it if I don't have to type it again.

**Comment by Killette2** [comment]
I mention the cost but didn't intend for it to be the focus point. It was supposed to be attached to the fact that some cooldowns feel a bit extreme if you find yourself in a dire situation (such as the AI is on your case) and how some things are underwhelming even after you pay a price for them (such as bats).

You have some nice ideas thematically involving holy water. What in your opinion is the problem with vampires?

**Comment by Killette2** [comment]
During a conversation this topic came up:
What if we lowered the cost of vampire abilities?
The only successful vamps are either stealth or gunvamps with shadow menace toggled. You can't go loud because the cost and making them free would be overpowered. What do you say we meet in the middle and have reduced cost. Maybe make it so you get the most reduced cost when you wear the vampire cloak as it fits the identity of the antag type.

Usable blood is not the easiest thing to come by as it takes a victim, time, and for them to not succumb the second they hit crit. Once you go loud getting more usable blood is usually out of the question which encourages vamps to stay quiet.
