### ISSUE TITLE
Runtime associated with chemmasters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16606]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)
# Revision
9880b09f03b5a0189d66a6929e2191c60c773161

# Description
When attempting to analyze blood in the buffer of the chemmaster, I found pressing ? didn't yield anything. After asking an admin (Zealotron) to see if there was a runtime, there indeed was.

[13:48:22] Runtime in chem_master.dm, line 182: Cannot read null.name
proc name: Topic (/obj/machinery/chem_master/Topic)
usr: Alijah Todd (dragonbro) (/mob/living/carbon/human)
usr.loc: The floor (248, 234, 1) (/turf/simulated/floor)
src: the ChemMaster 3000 (/obj/machinery/chem_master)
src.loc: the floor (249,235,1) (/turf/simulated/floor)
call stack:
the ChemMaster 3000 (/obj/machinery/chem_master): Topic("src=\[0x2006d3b];analyze=1;des...", /list (/list))
DragonBro (/client): Topic("src=\[0x2006d3b];analyze=1;des...", /list (/list), the ChemMaster 3000 (/obj/machinery/chem_master))
DragonBro (/client): Topic("src=\[0x2006d3b];analyze=1;des...", /list (/list), the ChemMaster 3000 (/obj/machinery/chem_master))
# Steps to Reproduce
Get a beaker of blood
Put it in the chem master
move the blood to the buffer
Press ?
# What you Expected
The readout of the blood (Its bloodtype, specifically)
# What Actually Happened
Nothing. It worked when I moved the blood back to the beaker, but in the buffer I got nothing.

**Comment by SonixApache** [comment]
>WEB REPORT BY: dragonbro
