### ISSUE TITLE
Feature request - Advanced health anaylzer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16607]
(WEB REPORT BY: dragonbro REMOTE: 172.93.109.202:7777)
Please, somebody, make something hand-portable that tells you if somebody is able to be revived and hasn't logged out, without having to go to cloning/decapitate the person and health analyze the decapitated head/treat the body to a defibrable point only for the defib to say 'patients condition does not allow for reviving'.

**Comment by Sooose** [comment]
Maybe change the soul portion of the examine verb to include whether they're just ghosting like it should anyway.
