### ISSUE TITLE
Feature request - "Brain damage" for sillycons

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16614]
Admins have a variety of means to punish carbons IC for bad behavior when it doesn't go into ban territory, including giving brain damage. Why should silicons miss out on that? Relatively minor law violations could be met with circuit damage. This could manifest as garbage characters being randomly inserted into the silicon's speech, and sporadically putting static overlays over objects in the viewport. The static could be re-purposed from what I believe is a currently unused feature of MoMMIs.

**Comment by Blithering** [comment]
It would be a neat addition to emp if they scrambled silicons brains for a bit

**Comment by SkowronX** [comment]
Fragmented code and bloatware.

**Comment by Durgen** [comment]
punishment module when
