### ISSUE TITLE
Bring back the stage for the theater

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16613]
![image](https://user-images.githubusercontent.com/5169310/33120925-7989a878-cf41-11e7-869d-91992d2c015e.png)

I feel the server would highly benefit from a design that's somewhere between the new bar and old bar. The bar being connected to the kitchen to distribute food is nice for bartenders who'd like to roleplay a bit more and have things to sell like an actual bar, and the theater having a stage reminds the clowns that they're not just greyshirts with costumes. We could do a bit of work to keep the link between the bar and dorms if that is an issue, but I feel like these changes would be a situation where everyone in the bar area would benefit from.

**Comment by EdXbtkOEwGw** [comment]
We already have theaters in ~~Meta, Deff AND Bagel~~ literally EVERY map except Box and I never see them used

**Comment by Kurfursten** [comment]
I've seen a performance on the Packedstation stage once.

I think most people don't even know about the Bagel theater at all.

**Comment by Killette2** [comment]
Deff theater is in an odd and ugly spot though. Bar theater is best theater
