### ISSUE TITLE
Deff SME airlock still leaks gas

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16615]
(WEB REPORT BY: reind REMOTE: 172.93.109.202:7777)
# Revision
9880b09f03b5a0189d66a6929e2191c60c773161

# Description
The SME chamber airlock sometimes leaks gas in closed state.
# Steps to Reproduce
It triggers somewhat randomly, sometimes it doesnt trigger at all.
# What you Expected
Airlock blocking gasses like any other airlock.
# What Actually Happened
Gas and heat came out, killing me and fucking up the whole room.

**Comment by FudgePucker** [comment]
>that god damn airlock is passing gas again

:joy: :ok_hand:

I adhere to quantum ZAS theory, at random the particles of gas in the area will align with the particles that make up the airlock, connecting the two zones of gas.

**Comment by Exxion** [comment]
Yeah I guess it was wishful thinking to imagine that the ZAS update could have fixed this

**Comment by Kurfursten** [comment]
@Exxion This is another one of those gas issues

**Comment by Exxion** [comment]
I think this is a separate one from the nebulous, unfixed one
Has anyone observed it recently?

**Comment by Kurfursten** [comment]
no
