### ISSUE TITLE
Runfast superpower broken since movement speed code change

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16626]
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
# Revision
9880b09f03b5a0189d66a6929e2191c60c773161

# Description
Ever since the way movement speed/slowdown works was redone, the "runfast" superpower in genetics has ceased to function. It used to prevent any slowdown, like hyperzine does. Now, it doesn't seem to even mitigate slowdown, and as far as I can tell doesn't work at all anymore.

# Steps to Reproduce
Give self runfast genetic superpower, do something that normally slows you down, like wearing magboots. Observe that you are still slowed down when you shouldn't be. Take hyperzine to see how it ought to behave.

# What you Expected
Proper slowdown prevention.

# What Actually Happened
Nothing at all. When the movement speed update went through, they must have forgotten to update the way runfast power works.

**Comment by AI-Is-Rogue** [comment]
I'm pretty sure the movement speed rework said that it made it so the power actually makes you run faster instead of negating slowdown.

**Comment by DamianX** [comment]
Yep, not a bug.

**Comment by JackMassacre** [comment]
I must have missed that while skimming the details of that particular update when it popped up. Thanks for correcting me.

Relatedly, if it's working now as intended, its effects are pretty unnoticeable. Whether that's good, bad, or unimportant, I can't say.

**Comment by AI-Is-Rogue** [comment]
Last time I saw the power it was a pretty big speed boost.  Did you have anything slowing you down?

**Comment by DamianX** [comment]
It's a good speedup, if anything it needs to be toned down.

**Comment by JackMassacre** [comment]
Does it not work at all if you have any amount of slowdown applied? I haven't looked at the code yet, I just noticed toggling it on while testing other stuff offline didn't appear to do anything, but I'm sure I had some magboots or a hardsuit on at the time.

**Comment by AI-Is-Rogue** [comment]
Seems to be working properly on the test server. The boost is a bit subtle but still very effective.

**Comment by DeityLink** [comment]
Testing seems to show that the superpower still works fine. Both on its own, when combined with hyperzine, or with phazon tiles.
