### ISSUE TITLE
C-4 Space Pod Deletion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16632]
(WEB REPORT BY: nogeeef REMOTE: 172.93.109.202:7777)
# Revision
9880b09f03b5a0189d66a6929e2191c60c773161

# Description
I used C-4 to destroy a space pod and the driver was ejected, but the passenger was nowhere to be found.

# Steps to Reproduce
1. have a driver and a passenger in the escape pod
2. apply c-4 to the escape pod from outside
3. when the c-4 detonates the pod will be destroyed, the pilot ejected, and the passenger deleted

# What you Expected
both pilot and passenger to be ejected

# What Actually Happened
only the pilot was ejected. the passenger was deleted.

**Comment by MadmanMartian** [comment]
oh dear
