### ISSUE TITLE
tele-vines

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16645]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
d493882bf8db75866a15ed195213a99d77b4fe4a

# Description
getting grabbed by vines, then teleporting out (I did it with bluespace tomatoes, but it could also work for shit like telesci) while still grabbed will make the vines remotely hold you and inject you with poison (even though you teleport to somewhere that has no vines). I think the phantom vine grab just carries over without checking if the vines are still holding you.
# Steps to Reproduce
make kudzu, get trapped, teleport out via blue space plants
# What you Expected
once you're away from the kudzu plants you shouldn't be stuck and you shouldn't get injected

**Comment by jknpj** [comment]
REFERENCES

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/42724268-6ef51da2-876f-11e8-8483-ef2e3d97575e.png)

**Comment by DeityLink** [comment]
So basically the bug is that when vines proc their strangle shit, they don't check whether you weren't move away (which could happen if you were slipping at the same time, like in this case).

They should release you if you're not in their loc.

**Comment by SysadminJeroen** [comment]
Same thing with lube vines I think.

**Comment by DeityLink** [comment]
I'll make vines immediately end your slipping if they catch you.
