### ISSUE TITLE
Boxstation Vox cant access own APC's

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16644]
(WEB REPORT BY: laserdog REMOTE: 172.93.109.202:7777)
# Revision
d493882bf8db75866a15ed195213a99d77b4fe4a

# Description
You cant unlock the apcs on vox station with vox id
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by JackMassacre** [comment]
For what it's worth, every vox trader outpost gives the traders access to insulated gloves from the start of the round, and APCs can very easily be hacked to unlock them.

**Comment by Durgen** [comment]
Also air alarms.

**Comment by DamianX** [comment]
Is this issue in any way specific to box station?

**Comment by Probe1** [comment]
No all maps should be that way.
