### ISSUE TITLE
AC Units Too Powerful

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16648]
I noticed this a while back when I accidentally briefly exposed a heat exchange pipe from a RUST to an engineering chamber and the room shot up to ungodly temperatures. It only took a couple minutes with an AC unit to cool off, didn't even need foam. I've even heard of people running tiny SMEs on nothing but an AC to cool them. Probably went haywire with the atmos changes.

In any case, this needs more testing and may have already been fixed since I haven't had a chance to test it again recently. I'm all for strong engineering tools but it really seemed to cool outrageously fast.

**Comment by DamianX** [comment]
I told you about the space heaters bro https://github.com/vgstation-coders/vgstation13/issues/16452#issuecomment-341944514

**Comment by ghost** [comment]
Aw, I kind of liked being able to actually do something to help after a plasmafludd as anything other than foamslave.

**Comment by Kurfursten** [comment]
@DamianX Funny enough that was back when I noticed this, I guess I forgot that we had already talked about it.

**Comment by FudgePucker** [comment]
With how damaging to the areas atmospherics high heat is, being able to use an air conditioner to fix it is good. You have to go find one and drag it to the problem area, it needs to be powerful enough to deal with toxins leaks.

What's the problem with a simple solution to a major problem? By the time you set up some fancy air cooling loop the emergancy shuttle would have been called. Time is everything for engineering and repairs.

You can't use the AC to make a death room right?

**Comment by Kurfursten** [comment]
No it has a minimum temperature (otherwise it would be a huge problem because of how available AC units are). The problem is that if AC units do indeed work so fast they trivialize all other atmos, there's no reason to have any engineering skills. Cool your SME with an AC, cool telecoms with an AC, no need to call an atmos tech for a fire. If you will, it's like if the PACMAN generator could run on a power cell (AC units do this) and could generate a couple megawatts of energy, and spawned in the laundry room at round start. Or if you prefer an atmos comparison, if those publicly available portable scrubbers in the laundry room instantly cleared all plasma, meaning it's better to build an engine using portable scrubbers and you could wait out a plasmaflood just by turning the scrubber on in your room.

I don't object to AC units being good at cooling off rooms (that's the point) - or even that they are much better than foam extinguishers (they should be better, since you have to pull an object around instead of carry an item), I object to the fact that they now trivialize heat problems.

**Comment by Blithering** [comment]
How about making it so that ACs are still good at cooling down rooms that are too hot, but if there's still something pumping heat out, like a SME or telecomms equipment, the AC overloads and shuts down?
Alternatively, just make them cool rooms slower, so that they can't keep up with the outputs

**Comment by Kurfursten** [comment]
Yeah, that's all I'm saying, tone it back a little bit

**Comment by JackMassacre** [comment]
How about a compromise? Rather than a change to the effectiveness of an air conditioner (or just changing it too much), make its effectiveness come at a greater cost in power output and add a necessity for constant maintenance and upkeep.

That is to say, have the power cell drain faster the higher the difference the ambient temperature is against the temperature you have set the air conditioner to.

This way, the device is still very useful for dealing with heat emergencies, but you'll have to carry spare cells and switch them out on the fly, or employ a hand crank, etc., and you can't power single-tile supermatter engines with it by popping in a 15k cell and leaving it on for two hours without having to attend to it anymore.

**Comment by Kurfursten** [comment]
That's fine too, although maybe if you want to go that route maybe it should have a configurable "intensity" setting as well so you don't blow out the battery trying to lower room 2 degrees

**Comment by JackMassacre** [comment]
While we're on the subject, if we're heading towards bringing heaters and air conditioners down to a sane level of effectiveness, it would also be very nice if we could have some way to construct new ones, or at least order new ones from cargo. Ideally both.

**Comment by Blithering** [comment]
Maybe a crate with one heater and one conditioner, climate control crate or something

**Comment by JackMassacre** [comment]
Personally I'd prefer if nothing else to be able to print circuitboards for them at some tech level. That way as well would allow derelict MoMMIs to mess around with them without having to pray and hope an admin is awake and feeling generous.
