### ISSUE TITLE
You can change your suit sensors while dead.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#16649]
#### Description of issue
You can change your suit sensors once while dead with a small setup.

#### Steps to reproduce 
Open the menu to change suit sensors and leave it open, while dead or otherwise incapacitated you can confirm your choice and your settings will update.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x]  Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
Wonder if this works with...
-PDAs
-speaker assemblies when you're entering the text
-command consoles when you're making an announcement

**Comment by Exxion** [comment]
It pretty much has to be fixed on a case-by-case basis, so there are a *lot* of things it probably works with.
The first and third of those ones are *probably* high-enough profile that they have already been fixed, though.

**Comment by Killette2** [comment]
![image](https://user-images.githubusercontent.com/5169310/33394548-a9314a84-d510-11e7-9a59-d02cb1f3789d.png)

**Comment by Killette2** [comment]
![image](https://user-images.githubusercontent.com/5169310/33394594-d3bccb8e-d510-11e7-8207-34f82f798386.png)

And now things get interesting...

**Comment by Exxion** [comment]
>People figured this out with being able to rename drinks before they figured it out with speakers

Well
Probably not
But they *reported* it first

**Comment by Killette2** [comment]
>You swallow a gulp of My Body Is On The Astroi.

**Comment by Exxion** [comment]
I wonder if it works with foods
I have a wonderful idea

EDIT: It does not
