### ISSUE TITLE
Feature request: Space Suit crate on cargo

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#16646]
i mean, come on now.
you can order a space suit for vox, also for plasmamemes and there's also one for greys only
why not for the humans too?, just make it expensive like 200 bucks each
it could really help those dark dorf times when peoples that took the suits have fucked off and you're left doing nothing because you didn't chose a race with a roundstart space suit, or you didn't got lucky to get a suit quickier, so you have to sit down in the outpost doing jackshit.
inb4 "just use a firesuit bro."

**Comment by MadmanMartian** [comment]
How much would/should it cost? Should people be able to buy one straight away using roundstart funds?

**Comment by MadmanMartian** [comment]
Should the orderable space suits have downsides/upsides over job-specific space suits? Maybe have a bottom-bucket suit that works in atmospheric pressure between 0 and 1 but is affordable, while theres also military issue combat EVA gear for a kings ransom

**Comment by coderbus13** [comment]
could just have it be a basic suit

**Comment by SonixApache** [comment]
just use a firesuit bro

**Comment by Pathid** [comment]
Probably around a dozen firesuits on-board you can use to make ghetto spacesuits. Ghetto space helmets need _red_ hardhats, which seems like an unnecessary restriction to me. Yeah, I know they usually come with the firesuits 1:1 but come on.

**Comment by Dacendeth** [comment]
I'd like a way to get the clown space suit, even if it's made a small chance to come in the shipment that be good enough.
