### ISSUE TITLE
Lockdown Implant

### ISSUE THREAD

**Issue by SerWind** [d3athrow/vgstation13#16651]
Sec implant that lets sec or silicons/AI lockdown the implanted person like a borg.

Resisting will let you move or take action for a short amount of time.

**Comment by ghost** [comment]
It's called electropack :^)

Now if only they weren't bugged to all fuck

**Comment by SerWind** [comment]
You're not wrong, though you can't resist and electropack as far as I'm aware? Could just be a change made to that.

**Comment by Dacendeth** [comment]
I think you can get an electopack off by equiping another backpack.

**Comment by SonixApache** [comment]
did you know borgs have a completely unused weapons lock function
