### ISSUE TITLE
Lagging and UI froze

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16656]
(WEB REPORT BY: lazyspirit REMOTE: 172.93.109.202:7777)
# Revision
7091a4d6c085231c93c5d9a26f5d69259dcb609f

# Description
can't move, can't click anything, can chat tho
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment]
This is most likely due to you using BYOND 511.

Download this : http://www.byond.com/download/build/510/510.1347_byond.exe
This is in the thread and as the MOTD too. smh tbh fam.
