### ISSUE TITLE
Binary chat as positronic brain

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#16653]
A round ago I was called into existence as a posibrain, then crammed into a metal coffin known as a mech. Curiously I could hear binary chatter, but not speak over it with :b. It seems there was someone else in the posibrain before me, but I guess they suicided, so I could have a go.

**Comment by Cyadox** [comment]
Had the samd thing happen, but I was the original posibrain occupant. Its nothing to do with suicide, the mechs simply have no binary radio.

**Comment by Probe1** [comment]
Not sure where the bug in this is.  Should posibrains not have :b or should they be able to use the binary radio?

**Comment by Ephx1** [comment]
Posibrains cannot use binary or hear it. They've been without binary for years now. Originally they could listen to and transmit over :b, but that was eventually removed since it was ridiculously easy to have a positronic brain rat out malfunctioning/rogue silicons.

**Comment by Probe1** [comment]
Ok I'll see about removing that.
