### ISSUE TITLE
Certain consoles not refreshing as silicon

### ISSUE THREAD

**Issue by ReindH** [d3athrow/vgstation13#16650]
#### Description of issue
Computer consoles like the cargo supply console no longer refresh automatically, making it a pain in the ass as AI,  borgs or MoMMI  to use them for accepting multiple crates.
Same issue with atmosphere tank monitoring consoles, they don't refresh unless you are right next to them, have to close the window and reopen.

#### Difference between expected and actual behavior
Expected: automatic refresh of the window every second or every interaction (like accepting a crate)
Actual:Information doesn't update, have to manually close and reopen the window

#### Steps to reproduce 
Be silicon, order 3 or more crates and try accepting them when not right next to a console.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [x ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x ] Issue happened in a recent (less than 7 days ago) round
- [x ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
*unzips #16647*

**Comment by ReindH** [comment]
Didn't notice, you are my hero.
Is there an issue about the bangometer refusing to open again once you closed it's window as AI?

**Comment by DamianX** [comment]
Apparently not.

**Comment by SonixApache** [comment]
Door control windows also don't update when you change their options.
