### ISSUE TITLE
C.A.C. broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16654]
(WEB REPORT BY: scribnibblers REMOTE: 172.93.109.202:7777)
# Revision
7091a4d6c085231c93c5d9a26f5d69259dcb609f

# Description
this computer no longer does very much.  it is sooooo useful i wish it worked.
# Steps to Reproduce
go to atmospherics and use the computer on the top left called central atmospherics computer
# What you Expected
the central atmosperics computer used to let you access air alarms around the station
# What Actually Happened
nothing happens when i click on air alarms.  also i think once i look at the computer and close the windows i can never get it to open again but other computers, nano ui, pda, etc work fine

**Comment by Sooose** [comment]
If memory serves me right, to update that computer's UI you need to click the computer again each time to get it to refresh. Its pretty annoying regardless.

**Comment by BenjaminMichael** [comment]
Its not working for me no matter what I click each time. :(
