### ISSUE TITLE
Pink/black checkered jumpsuit when fat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16652]
(WEB REPORT BY: irradiation REMOTE: 172.93.109.202:7777)
# Revision
7091a4d6c085231c93c5d9a26f5d69259dcb609f

# Description
After becoming fat through a lot of sugar in my bloodstream, my First-Responder jacket popped off and instead of having my normal Chemist Jumpsuit colors, I had a jumpsuit filled with pink-black squares, like I was playing Garry's Mod with missing/misdownloaded textures.
# Steps to Reproduce
0 - Play on Metastation
1 - Wear a Chemist Jumpsuit
2 - Wear a First-Responder Jacket
3 - Have a roller bed in your suit storage
4 - Become fat through large sugar quantities in your bloodstream.
5 - Enjoy your black-pink jumpsuit!
# What you Expected
To have my jumpsuit in the normal color.
# What Actually Happened
My jumpsuit was checkered in black & pink. Picture to follow.

**Comment by Irradiation** [comment]
![fat spess](https://user-images.githubusercontent.com/15248411/33394340-02de3552-d510-11e7-9754-cc33fd96815c.PNG)

**Comment by Blithering** [comment]
https://github.com/vgstation-coders/vgstation13/issues/9139

**Comment by Exxion** [comment]
Chemist jumpsuit, you say? That one specifically should work.
#10788

**Comment by Blithering** [comment]
I think the chemist has two or more alt title jumpsuits, it may be one of them

**Comment by SonixApache** [comment]
this is a really good bugreport

**Comment by Shadowmech88** [comment]
Based on the appearance of the sprite in his inventory, he was wearing the pharmacist jumpsuit.
I just tested it, and the pharmacist jumpsuit now has a fat sprite.
