### ISSUE TITLE
Blood in containers can have its type changed.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#16660]
#### Description of issue
Blood can be effectively transformed from one type to another almost effortlessly.

#### Steps to reproduce 
Take 5u o- and put in a empty blood bag or beaker, now put any other blood type into it and it will turn into what blood type was in there first. You could easily with a large syringe turn all the round start bloodbags into o- bags with a few minutes of work.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
#12934

**Comment by Dacendeth** [comment]
Man I swore I read every title before submitting, guessed i missed that one.
