### ISSUE TITLE
Mechs Should Eject Dead Pilots

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16667]
Ran into a little trouble previously where someone started bleeding outside of a mech, climbed in to return to medbay, and died before they could eject. The result was having to smash the mech and waste huge amounts of resources.

Or, if auto-eject is a problem, maybe it could be a maintenance panel thing.

**Comment by Pathid** [comment]
You have to stick an electropack on the mech and activate it. Not the most intuitive thing, I know.

**Comment by SonixApache** [comment]
You can insert one by just enabling maintenance mode, right?
