### ISSUE TITLE
Stats counting a human victory as an AI victory

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16668]
#### Description of issue
Human victory was counted as an AI victory. Not shunting was counted as shunting. Two detonated borgs were counted as 2 borgs at round end. This was after Delta and the AI didn't actually shunt. 

#### Specific information for locating
http://game.ss13.moe/logs/2017/12-December/01-Friday.log
`[19:56:24]GAME: <h1>Round End Information[...]Mode Result</h2><FONT size = 3><B>Human Victory</B></FONT><BR><B>The AI has been killed!</B> The staff is victorious.<FONT size = 2><B>The malfunctioning AI were:</B></FONT><br><img src="logo_4.png"> <b>Trifty</b> was <b>D.O.O.R.K.N.O.B</b> (deactivated)<BR><HR><br><br><BR><h2>Round Statistics and Score</h2><B><U>GENERAL STATS</U></B><BR>`
http://stats.ss13.moe/match/339
![815](https://user-images.githubusercontent.com/31839805/33511709-b348e818-d6d4-11e7-9d47-31eaebb0e807.PNG)

#### Server revision

Game: 9ef74e808f59b43bd5a9e97f02ba2477c6afc572 
Patches: 0b7885e898447447a811f0be191bba73b5c20932 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
fixed in the JSON thing I haven't worked on in forever thanks for reminding me
