### ISSUE TITLE
SME broken by zas "update"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16661]
(WEB REPORT BY: bobthomas REMOTE: 172.93.109.202:7777)
# Revision
9ef74e808f59b43bd5a9e97f02ba2477c6afc572

# Description
zas "update" broke all known configurations of SME
# Steps to Reproduce
try to use the SME without it blowing up
# What you Expected
self explanatory
# What Actually Happened
self explanatory

**Comment by PJB3005** [comment]
Challenge accepted.

**Comment by MadmanMartian** [comment]
how is this self explanatory?

what has broken?

**Comment by jknpj** [comment]
I swear to god these reports get worse every day

**Comment by PJB3005** [comment]
I want to say we peaked when somebody made 10 issues being aware of
spamming but you know...

**Comment by Exxion** [comment]
How in the blazing fuck did the *R-UST* being broken get reported before the SME?
And by quite a while, too

Anyway, I can probably fix this one later tonight, but I still don't know jack shit about the R-UST

**Comment by PJB3005** [comment]
![](https://i.imgur.com/0JSbam0.png)

Yeah I think we can ignore this issue it's probably full of shit. I just built this on the test server.

**Comment by PJB3005** [comment]
![](https://i.imgur.com/nJIsSFr.png)

**Comment by Exxion** [comment]
Does the test server even have the update yet? I'm not sure how far out of date out is right now.
But that would explain it not getting reported yet.

**Comment by PJB3005** [comment]
@Exxion I just checked and it has Unid's Zathura vault so it's at LEAST at 6aa5e230f3bc1255d9bda36cef6395d3e820f0bf

**Comment by PJB3005** [comment]
Yeah unless somebody credible has evidence of the SME being broken I'm just closing this.
