### ISSUE TITLE
ZAS only works when it feels like it

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16663]
There was a hull breach in arrivals. Pressure was at it's lowest 88 and then it started filling back up. I have seen this issue many times before when airflow won't happen through busted walls or open doors for some reason. What is the cause of this?
![screenshot_102](https://user-images.githubusercontent.com/5169310/33507343-3a575bae-d6c2-11e7-83f5-e52e48f126d3.png)

**Comment by mtpowell** [comment]
Possibly an optimized atmos, although there is a noticeable pressure difference

**Comment by Killette2** [comment]
I don't have the feeling this is the case or it would have blown the locker and toolbox out too

**Comment by Exxion** [comment]
Hm. ZAS has always had a tendency to fail to connect zones on occasion, but it appears to have become much more common since the update.
I'll look into it.

**Comment by Exxion** [comment]
This is probably #19258

**Comment by nervere** [comment]
Closing as duplicate of #19258
