### ISSUE TITLE
Defficiency has no air conditioners in maintenance 

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16669]
#### Description of issue
Deff has no air conditioners in maintenance, lots of space heaters but no ACs.

#### Server revision

Game: 9ef74e808f59b43bd5a9e97f02ba2477c6afc572 
Patches: 0b7885e898447447a811f0be191bba73b5c20932 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
It's because Deff maint is already too cool
