### ISSUE TITLE
Compile time is way too long

### ISSUE THREAD

**Issue by JaredFogleSS13** [d3athrow/vgstation13#16675]
#### Description of issue
Compile time is way too long. Maybe it's just my years old computer, but it takes maybe 5 minutes to compile this heap of shit. I try disabling files for objects and stuff I probably won't need, but then my compile log is flooded with errors. Perhaps there should be some guide or something on how to make compile times much shorter at the cost of having an actually playable server? (As in, when testing unless you're actually fiddling with robotics code you don't need them).

#### Difference between expected and actual behavior
It shouldn't take several minutes every single time to compile even if it's just a small change.

#### Steps to reproduce 
Compile this.

#### Specific information for locating

N/A

#### Length of time in which bug has been known to occur

I have no idea. 

#### Server revision

Latest. Too lazy to open up the game.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
literally just BYOND
we can't fix it

**Comment by Exxion** [comment]
Always has been, always will be. BYOND was never meant to run a game of this scale.
Sorry.

**Comment by JaredFogleSS13** [comment]
thought so, but there are still hundreds of scripts that don't have to be enabled every single compile time.

**Comment by Shadowmech88** [comment]
You can somewhat improve compile times by using a smaller map, such as test_tiny.
Beyond that, it's just the result of living in a castle built on top of a garbage heap.

**Comment by JaredFogleSS13** [comment]
@Shadowmech88 will try this, but like you said with the word "somewhat", i don't expect this to improve it very much

**Comment by clusterfack** [comment]
Yes ^ do the above, a lot of the FIRST compile time on opening dream seeker is getting the map set up. If you use a map like test_tiny it will be far faster.

**Comment by small-boss** [comment]
i had compile times of literally 15 minutes on a shitty pc once
thats just how byond is

**Comment by Exxion** [comment]
There are not actually... any compile-time scripts, as far as I know.
If you mean unnecessary code, then sorry, but SS13 is about as far from modular as you can get. If you can find a file of any significance that can be unticked without causing a compile failure, I'll be shocked.

**That said**, using a test map as suggested above will probably cut off 30 seconds to a minute, and you can get some additional benefit from using `dm.exe` rather than the actual Dream Maker.

**Comment by JaredFogleSS13** [comment]
@Exxion unnecessary code is what i meant, and yea i figured out the non-modular part. as for dm.exe, that i didn't know. i see that i have it, but i'm not sure what it is. is it a console program that i can just run `dm.exe vgstation13.dme` in?

**Comment by gbasood** [comment]
yeah you can use not Dream Maker to compile via dm.exe
there's project setups for things like building via Atom and the `build` apm package
more specifically:
https://www.reddit.com/r/SS13/comments/40xh7s/coder_stuff_updates_regarding_github_atom_for_dm/
https://www.reddit.com/r/SS13/comments/48stt2/yet_another_github_atom_update_atomic_dreams/

**Comment by JaredFogleSS13** [comment]
@gbasood i prefer vs code over atom, but i get how all that works and could get it working for me. i'll look into it, how much would using test_tiny and dm.exe improve compile time?

**Comment by gbasood** [comment]
oh in that case there's a syntax package for VS Code based on Atomic Dreams that I've published as well, and you can configure it to build similarly
for compile times: test_tiny.dmm helps a lot, it also more specifically helps with starting a local server after compiling by a fuckton

**Comment by Exxion** [comment]
>VS Code package based on Atom package based on Sublime package that doesn't even really work anymore

What kind of hell have we trapped ourselves in

**Comment by gbasood** [comment]
the vs code package is basically a straight port at least
they both use the same rendering engine whereas the sublime package never worked quite right anyway

**Comment by Killette2** [comment]
Lets just port ss13 to another engine, that should fix this problem. If nobody else has the time, you can tag me to work on this and close the issue.

**Comment by MadmanMartian** [comment]
DM only compiles using one core, so you've gotta have a good clockrate on your processor.

Went from a 1.6GHZ to a 3.4GHZ, compile time went from 12 minutes to 2 and a half.

**Comment by clusterfack** [comment]
@Killette2 yep, other engines have incremental compilation

**Comment by gbasood** [comment]
@Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 @Killette2 

ss14 when

**Comment by Killette2** [comment]
![image](https://user-images.githubusercontent.com/5169310/33579853-23a212d8-d919-11e7-89dc-cfacf43886b4.png)
I'm making it 3D while I'm at it

**Comment by gbasood** [comment]
roblox doesn't count

**Comment by Exxion** [comment]
Honestly even that is better than BYOND
