### ISSUE TITLE
SME issues.

### ISSUE THREAD

**Issue by DrSnips** [d3athrow/vgstation13#16673]
A recent issue has come up with the sme. A shard in an atmos of large amounts of O2 will self stimulate and flash red. This is normal until you realize that it's not cooling properly. I had a valid passive cooling set up with a mostly n2 atmos and the cooling worked as expected. Then I switched it over to the o2 atmos for the o2 stim and the shard room started to heat up dramaticly unlike in the past. Ive done this in the past without the problem about a week ago. The H.E pipes used were working properly and were slightly cooling the room but the heat rapidly shot up unlike how it was in the past where it was a manageable heat increase. This was greatly outpacing 25 H.E pipes that were space cooled and this wasnt an issue a week or so ago. I then swapped out the gas back to n2 to stop the o2 stim and the shard went back too being cooled just fine. The I filled the room with a similar amount of mols of n2 as there was o2 in the end.
Im makes me believe that the o2 stimulated state of the sme is a tad bit broken right now.

**Comment by FudgePucker** [comment]
What about scrubbers and injectors with a space cooling loop?
O2 super charged shards should be hard to maintain. N2 retarded shard with chilled plasma in the collectors wired to grid is more than enough to over power a power sink, how much more power do you need?

**Comment by DrSnips** [comment]
It produces a lot of heat yes. But for some reason it's making an abnormal amount of heat now. You used to be able to run the o2 stim just fine a week or so ago with the setup I had. This indicates that there is an issue somewhere.

**Comment by FudgePucker** [comment]
Maybe this is the intended behavior and the passive cooling set ups only worked due to a bug that got fixed.

You could always multtool the shard and set up a AAC script to turn on an injector connected to a canister filled with hyper chilled N2 when the damage gets too high.

**Comment by DrSnips** [comment]
Here's the thing. There hasn't been a bugfix pr for the sme recently as far as I can tell. And the recent atmos changes were supposed to just be code cleanup and not change anything.

**Comment by JackMassacre** [comment]
I'm not seeing any differences in any of my passive cooling SME setups, all of which I use pure O2 for in the shard's chamber.

This simple 3-HE-junction, two-tile mini SME still works just fine. Using current code, as of less than an hour before this post. Temperature is stable and low, shard is glowing.
[https://imgur.com/a/uSJ16](https://imgur.com/a/uSJ16)

What gas have you been using inside of your passive cooling pipes?

**Comment by Exxion** [comment]
Yeah, sorry, I meant to comment on this but forgot
I didn't intend to change anything about the SME, so if something was changed by the ZAS update, that's a bug. I just haven't had a chance to look into it yet because I've been busy. Should be able to tomorrow.

That said, if it's specific to a particular type of gas and said gas isn't N<sub>2</sub>O, I struggle to see a way the ZAS update could have caused it.

**Comment by PJB3005** [comment]
Above a certain oxygen threshold, the SME's power math changes, so the theory is that triggers a haywire reaction like we saw with the xenoarch machines.

Should be noted though that the SME doesn't use an internal temperature buffer like those did, so...

**Comment by Exxion** [comment]
That's not what the problem was for those machines anyway
And I saw the problem for the SME
I'll fix it in a bit
