### ISSUE TITLE
Clothes sprites don't show up on catbeasts

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#16687]
steps to reproduce:

1. Be catbeast
2. Try to cover your shame
3. Fail miserably because all clothes vanish on you
4. get valided

**Comment by yclatious** [comment]
Its a Feature™️

**Comment by Ephx1** [comment]
> coders enabling furry erp by removing the need to take off clothes

DISGUSTING

**Comment by Arthurdentist** [comment]
im just waiting for someone to hide a traitor objective or even the nuke disk by putting it in a backpack on a catbeast corpse

**Comment by Exxion** [comment]
Pinpointer renders hiding the disk like that pretty irrelevant

**Comment by PJB3005** [comment]
> expecting the average crew to be competent enough to use a pin pointer.

**Comment by Aurx** [comment]
Just hide the pinpointer, the same asshole usually has it and the disk.
