### ISSUE TITLE
1-way tube trap

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16686]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
9b4f195c7b422dd7f8deed81612820374a3b7587

# Description
on metaclub, there's a section of tubing that bends at a diagonal angle at the top left most part of the research outpost in space. there's a small gap of space between the tubing and the rock wall, so if you walk inside (the game lets you walk inside) you get permanently stuck and can't get back out through the same way you walked in because the tubes only let you slip under them going in but not out.

**Comment by Kurfursten** [comment]
REMOVE TUBE

**Comment by Exxion** [comment]
Oh yeah, I probably should have reported this when I made transit tubes use actual movecode
Or just fixed it, but >atomic
