### ISSUE TITLE
Supply Shuttle not arriving on several stations

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#16691]
Steps to reproduce:
Be on Metaclub (possibly also deff)
Order literally anything
try to receive your order
Wait forever because the shuttle never docks.

This is a pretty big issue all in all

edit: looks like its already fixed on deff but at the time of writing its broke on meta

**Comment by Intigracy** [comment]
https://github.com/vgstation-coders/vgstation13/commit/e65db39c874c0b740a0b0151e08933919b706eb9 should fix it for all future cases that may pop up, didn't know there was an issue up or I'd have autoclosed it.

dunno why it wasn't this way before
