### ISSUE TITLE
Date and time inconsistencies

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#1669]
The mech logs seem to display the date and time of your system with the year as 2555 while the PDA events menu displays station time and your system date with the year as 2525.
Also the bank account creation date seems to be random meaning that your bank account creation date will sometimes be in the future.
This is very damaging to my immersion, please fix post haste.
![mech log](https://cloud.githubusercontent.com/assets/3892856/4575796/20e97b84-4fac-11e4-9a9c-82e4a944bb76.png) ![pda](https://cloud.githubusercontent.com/assets/3892856/4575799/21d4ec36-4fac-11e4-8b52-871d51e479e5.png)

**Comment by BestName** [comment]
Help it keeps happening!
![send help](https://cloud.githubusercontent.com/assets/3892856/5618103/1af4dc70-951e-11e4-8918-11c57c6f04fa.png)

**Comment by d3athrow** [comment]
bluespace is a bitch.
