### ISSUE TITLE
Defficiency - No air on cargo shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16701]
(WEB REPORT BY: alandemarest REMOTE: 172.93.109.202:7777)
# Revision
1ddc546022e3382b5b064e3b8d8fbfc1ea19fba6

# Description
No air on cargo shuttle round start, causing you to suffocate and take low-pressure damage

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Pathid** [comment]
Not only that but
![deep neckbear object ix 2017-12-06 125930](https://user-images.githubusercontent.com/31839805/33688063-124aa6c2-da8f-11e7-83af-a3196f171c68.png)
Some of those crates are actual orders that got left behind in the shipping station.

**Comment by MadmanMartian** [comment]
So, turns out I never actually put plasma glass by the engines.
