### ISSUE TITLE
Centcom encryption key is confusing because all channels default to off.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16708]
(WEB REPORT BY: rpaul REMOTE: 172.93.109.202:7777)
the heaset key aint working

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment]
🤔

**Comment by PJB3005** [comment]
It definitely works, just tested it, but you have to go into the headset's menu and enable all channels.
