### ISSUE TITLE
Crawling is busted.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16714]
(WEB REPORT BY: donnager REMOTE: 172.93.109.202:7777)
# Revision
882bc158d357ec80cd311299d8666ff4cbc06767

# Description
You can crawl diagonally over tables and windoors. You can also crawl under flaps.
# Steps to Reproduce
Stand diagonal to a tile where the things blocking you are a table and windoor, lay down and click that tile. You crawl to it!
Similar with flaps, just click the floor under the flaps and you crawl under.
# What you Expected
Not to be able to do these things.
# What Actually Happened
Free greytiding tool for easy trespasses that everyone can do, for free and it's completely untraceable unless you actually see somebody do it. Allows people to break into security with incredible ease for example.

**Comment by StreptoMutans** [comment]
Sneaky coders did it again

**Comment by MadmanMartian** [comment]
You reproduce it by being on the same tile as the windoor

**Comment by MadmanMartian** [comment]
![robot observatory kappa 2017-12-08 211605](https://user-images.githubusercontent.com/30557196/33785457-09cd3648-dc5d-11e7-8bb2-9b8fe2423e07.png)
![robot observatory kappa 2017-12-08 211608](https://user-images.githubusercontent.com/30557196/33785458-0afebd8e-dc5d-11e7-9ecd-8c8360f4ea2f.png)
