### ISSUE TITLE
Shuttle crushing an AI in an intellicard nullspaced it

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16710]
#### Description of issue
Shuttle crushing an AI in an intellicard nullspaced it. Was the emergency shuttle on Boxstation if that's relevant.

#### Server revision

Game: 882bc158d357ec80cd311299d8666ff4cbc06767 
Patches: 1b8525b994dfb3aa4d306f77f90f73abca332031 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
Should we just make all atoms/movable qdel their contents on Destroy?

**Comment by PJB3005** [comment]
Personally, yes.

If things don't explicitly destroy their contents, it'd cause left over references in app cases, and it helps prevent bugs like these.

Thay said, I'm not sure mobs handle qdel very well.
