### ISSUE TITLE
Please add a way to toggle ghosts other than your own without having to toggle darkness.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#16720]
This was said to be easy to code using planes.

**Comment by Ephx1** [comment]
I'm curious why you would ask for this.

**Comment by ghost** [comment]
Seeing other ghosts is very annoying when they're following a character and their ghost sprite is rendered over the character's.

**Comment by Ephx1** [comment]
That's fair. I'm all for it then.

**Comment by Kurfursten** [comment]
Yes he's right, also sometimes you want to examine the antagonist to see what they've got with them but you can't because 50 ghosts are on top of them and you have to either right click or toggle darkness

**Comment by gbasood** [comment]
lots of people including me have thought this would be easy with planes
but no one actually tried to do it i think

**Comment by Killette2** [comment]
I always wanted this but felt like I'd be the only one nitpicking about it

**Comment by Exxion** [comment]
It would be easy to do with planes if you were fine with also hiding your own ghost.
It would be slightly harder to do if you want to be able to see yourself, but not that much

**Comment by SonixApache** [comment]
#6671
@Kurfursten could always just implement the TG orbit follow sprite thing

**Comment by gbasood** [comment]
@SonixApache 
I think some people were violently against it but you could always make a PR and find out after all your hard work's been wasted :^)

**Comment by SonixApache** [comment]
@gbasood  alternatively just force merge it under the guise of "we'll revert it if people really do hate it"

**Comment by Pathid** [comment]
@gbasood
Could always make it a client setting deal.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is fixed @Exxion

**Comment by Intigracy** [comment]
I wish you could toggle darkness without toggling ghosts

**Comment by Exxion** [comment]
Not impossible but would require changing how toggle darkness works
