### ISSUE TITLE
Revert Crawling

### ISSUE THREAD

**Issue by Hugh-G-Rection** [d3athrow/vgstation13#16723]
Completely negates slips and traps of any kind without any equipment, and as a Clown I cannot abide by this gross affront to both nature and Honkmother.

**Comment by gbasood** [comment]
you can always hit the revert button yourself to make the PR
https://github.com/vgstation-coders/vgstation13/pull/16610

**Comment by Shadowmech88** [comment]
Slipping is supposed to stun as well as weaken (knock over), isn't it?
If so, then being able to crawl while stunned is a problem.
If not, then making it so would fix this issue.

**Comment by Shadowmech88** [comment]
Alternatively, as suggested by Sood, crawling could be changed so that weakened mobs are unable to crawl.

**Comment by ghost** [comment]
You can use it to safely crawl over lube?
Haha that's great

**Comment by Killette2** [comment]
what if slipping while crawling makes you stand up stunned?

**Comment by mattmatterson111** [comment]
Being weakened should let you crawl. Being stunned shouldn't. That way stunning someone still works but losing both your legs no longer stops you from crawling around.

**Comment by MadmanMartian** [comment]
can't crawl over lube/water after #16705

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah you still can crawl over lube

**Comment by MadmanMartian** [comment]
what the fuck

**Comment by Pathid** [comment]
That's 90% of what it's used for currently.

**Comment by DamianX** [comment]
that's not true
i'd say it's also used to bypass dizziness 50% of the time

**Comment by Pathid** [comment]
Oh yeah. Forgot about confusion.
