### ISSUE TITLE
Monkeys cannot crawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16736]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
-Turn self into monkey
-Try to crawl
-Cry because the hairless apes can do it and you can't

**Comment by SonixApache** [comment]
using your knees to move is what seperates man from beast

**Comment by Kurfursten** [comment]
It has been a long time since I saw that movie but I am pretty sure the humans won in planet of the apes by using their superior ability to crawl under plastic flaps
