### ISSUE TITLE
Mice eating out of donut boxes don't update the donuts on the box's icon

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16746]
#### Steps to reproduce 
Be a mouse, mousedrag a nearby donut box onto you, eat some donuts, observe the phantom donuts on the box's icon.

#### Length of time in which bug has been known to occur
Not new at all, just happen to be reporting it now.

#### Likely related issue
https://github.com/vgstation-coders/vgstation13/issues/13752

#### Server revision
Game: e6a24663932a4a0fb9a573c6ea7e239ea34677d1 
Patches: 9e34bcea4d28270b966365362177f6890fc3ca45 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MadmanMartian** [comment]
it's fukken loose

**Comment by Exxion** [comment]
It's *probably* just that the procs to update the box's sprite aren't getting called, but there is a nonzero probability that the donut references are not getting deleted from the box
