### ISSUE TITLE
Chem Dispenser Always on top

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16743]
(WEB REPORT BY: gunosaguki REMOTE: 172.93.109.202:7777)
The chem dispenser at the xenoarchaeology outpost on box always overlays on top of the beaker, that or the beaker always goes to the bottom, not sure which.

**Comment by Gunosaguki** [comment]
Its the beakers, when removed from a device they're being placed at the bottom of every object on the tile

vials included
