### ISSUE TITLE
Cell charger can't recharge crap cells

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16747]
#### Steps to reproduce 
Place empty power cell in cell charger
Notice how the charge always stays at 0%

Tried the basic power cell and the `/crap` variant. Probably caused by the charger trying to give the cells more charge than they can hold.

**Comment by Pathid** [comment]
Chargers don't seem to be able to charge "standard" 1000 cap cells either.

**Comment by DamianX** [comment]
...as was said in the OP? Perhaps I should have been more clear
