### ISSUE TITLE
Mimics can make their way onto the Cargo Shuttle, on Bagel

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16744]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
# Revision
e6a24663932a4a0fb9a573c6ea7e239ea34677d1

# Description
https://i.imgur.com/ofeHKFq.png
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by TheFriggenSawbones** [comment]
see its a problem because it prevents the cargo shuttle from being sent

if you can make an exception for mimics and make them sleep on the shuttle sure maybe
