### ISSUE TITLE
power out event ended in forever darkness

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16759]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)
# Revision
5ccc46034e0b2da362b0865fb4a4d10d9df6f732

# Description
https://i.imgur.com/QHT0Bv4.png
https://i.imgur.com/2ih14d7.png
https://i.imgur.com/qP8pTvZ.png
https://i.imgur.com/4tb9q18.png
https://i.imgur.com/A5YM1tF.png
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by EenKogNeeto** [comment]
We have no clue what caused this, but It was broken /before/ the power outage event, The outage event just forced all the lights that were already on to be off and therefore plunged us into eternal darkness.
A borg early in the round reported that its flashlight had no function, That was the earliest mention I remember.

**Comment by Pathid** [comment]
There was an abductor bus round like a month ago where this happened. Best way to describe it is something breaks and light fixtures start only updating the lighting system when it's light to dark, never when it's dark to light.

**Comment by EenKogNeeto** [comment]
Happened again in a recent round, There were both botany glowing things and tinted windows going on that round, The original round reported I don't /believe/ had anything like this but I was on mining the entire round. Maybe Zealotron could confirm if it did.

**Comment by Zth--** [comment]
Closing because I'm 98% certain this no longer happens
