### ISSUE TITLE
Banana Honk Reagent Called Banana Moma

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16758]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
5ccc46034e0b2da362b0865fb4a4d10d9df6f732

# Description

Banana Honk shows up as banana moma in the reagents
# Steps to Reproduce

Make a banana honk
# What you Expected

To get a banana honk reagent
# What Actually Happened

Got a banana mama

**Comment by DamianX** [comment]
Is this a feature?
