### ISSUE TITLE
SecBot Taser not clickable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16762]
(WEB REPORT BY: mcgstyle REMOTE: 172.93.109.202:7777)
# Revision
5ccc46034e0b2da362b0865fb4a4d10d9df6f732

# Description
see above
# Steps to Reproduce
Be secborg with 15000 cell, select secritron sprite, activate taser stunprod flashlight, try to go back to taser
# What you Expected
bein able to use the taser as usual

# What Actually Happened
I could not activate the taser in module slot 1

**Comment by DamianX** [comment]
I *think* this was fixed by #16739.
