### ISSUE TITLE
You knock out your target... except you don't

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16766]
#### Description of issue

I whacked a guy on the head and he didn't get knocked out.

#### Difference between expected and actual behavior

-Expected: Him to get knocked out
Reality: He didn't get knocked out. He was standing up before and after the last knockout was given so it wasn't even a .5 second sleep.

#### Steps to reproduce 

-Wear the gay dermal patch or some other good helmet I suppose
-Get whacked on the head
![screenshot_104](https://user-images.githubusercontent.com/5169310/33925911-0d765072-dfaa-11e7-8116-b8227728794b.png)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by EenKogNeeto** [comment]
Armor absorbed it.
