### ISSUE TITLE
Chem gripper

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16764]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
muh chemistry gripper won't grip pills

**Comment by ghost** [comment]
Good

**Comment by Pathid** [comment]
The medical upgrade board lets you. Too bad having anomaly research is so rare.

**Comment by jknpj** [comment]
With or without the medical upgrade? This is important.

**Comment by Sooose** [comment]
I know who was talking about this and they said it was even with the upgrade.

**Comment by jknpj** [comment]
I found what was wrong with them and i can only blame myself.
