### ISSUE TITLE
Should be able to secure curtains.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#16778]
It would be a nice feature if you could secure curtains in place. Currently they blow around due to ZAS and move on conveyor belts, which seems a little counter intuitive. Maybe just have the curtains blow open when there is ZAS around.

**Comment by Kurfursten** [comment]
I assume this was supposed to work the opposite way, with curtains supposed to ONLY be secure, and the author erroneously assumed structures have anchored = 1
