### ISSUE TITLE
Envelopes nullspace lighters when burned with them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16774]
(WEB REPORT BY: valkyrieskies REMOTE: 172.93.109.202:7777)
# Revision
5ccc46034e0b2da362b0865fb4a4d10d9df6f732

# Description
As above.

**Comment by MadmanMartian** [comment]
'You manage to light the cheap lighter.

You hold up the envelope and set it on fire, reducing it to a heap of ashes.

You put the lit cheap lighter into the envelope.'

The lighter is being put into the envelope upon burning, yielding naught but dust

**Comment by Cyadox** [comment]
AND FOR MY NEXT TRICK

Maybe a check to see if its burning when inserting items? Or just disallow lit lighters altogether.
