### ISSUE TITLE
Corpses can leave body scanner while it's on.

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#1678]
Was dying, got taken through medbay, placed in body scanner, taken out, cloned.
Went looking around, and saw that the body scanner was still on. Ejected the occupant, and my old corpse jumped to the scanner location.

**Comment by DeityLink** [comment]
used to happen when you were dragging a corpse. You'd drag the corpse out of the scanner, then it'd jump back to the scanner once you eject it.
