### ISSUE TITLE
Pain thresholds do not scale for carbons with nonstandard max health

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16780]
So I noticed that larvae are slow as heck, contrary to what the movies would have you believe. Thought this was some kind of wonky balance thing, but apparently it isn't so. It's from pain since you can observe them assume their true speed right after they get a hug.

https://github.com/vgstation-coders/vgstation13/blob/bb83beadcbce952295d60e10cdbc2bc2f7d63d1c/code/modules/mob/living/carbon/alien/larva/larva.dm#L8
https://github.com/vgstation-coders/vgstation13/blob/bb83beadcbce952295d60e10cdbc2bc2f7d63d1c/code/modules/mob/living/carbon/carbon.dm#L639-L651

Notice that larvae have 25 hp and the 100 on line 649 is a hard-coded number.

**Comment by Pathid** [comment]
Maybe more importantly, this also contributes to alien hunters being as OP as they are. With their 250 health you have to do 190 damage to cause them any pain slowdown.

**Comment by Killette2** [comment]
wew
