### ISSUE TITLE
dry ramen doesn't turn into undry ramen when mixed with water

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16788]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
bb83beadcbce952295d60e10cdbc2bc2f7d63d1c

# Description
adding water to dry ramen from the getmore machine doesn't undry it like it used to. needs more testing

**Comment by Pathid** [comment]
The hot ramen reaction was changed to require boiling temperature in https://github.com/vgstation-coders/vgstation13/pull/16475. Unfortunately they didn't add any heating mechanism to the cup to keep it consistent with the description that states it's self-heating.

**Comment by Killette2** [comment]
heating power that metabolizes with certain other chemicals when?

**Comment by SonixApache** [comment]
jesus christ

**Comment by EenKogNeeto** [comment]
Please fix this, Its annoying as hell as a chef to not be able to obtain hot ramen.

**Comment by Killette2** [comment]
dude grab a burner as a chef lmao

**Comment by Kurfursten** [comment]
It takes 54 welder hits to warm up ramen enough to become the kind you want to eat

That's excessive
