### ISSUE TITLE
You can't bind gas miners

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16793]
-Get advanced bind wizard spell
-Try to bind gas miner
-It doesn't ever bind (despite literally everything else working)

Methods I used
-Turning it off
-Unwrenching it
-Alt-clicking the floor then trying
-Asking it politely

**Comment by MadmanMartian** [comment]
fairly sure it's excluded

**Comment by DamianX** [comment]
It's a feature
https://github.com/vgstation-coders/vgstation13/blob/bb83beadcbce952295d60e10cdbc2bc2f7d63d1c/code/modules/spells/targeted/recall.dm#L20

**Comment by PJB3005** [comment]
Now, I don't agree with having this bindable, but to play devil's advocate: that generic atmos machinery exclude is probably because any other atmos machine would blow up if forcefully moved like this. The gas miners have absolutely no reason to be atmos machines.

**Comment by DamianX** [comment]
We have stuff that moves atmos machinery already (cough cough Dimensional Push) but no one seems to complain anyway.

**Comment by Killette2** [comment]
I'm actually more annoyed that you can't bind cryo tubes than gas miners
