### ISSUE TITLE
flesh to stone spell menu

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16794]
(WEB REPORT BY: tugamix666 REMOTE: 172.93.109.202:7777)
# Revision
bb83beadcbce952295d60e10cdbc2bc2f7d63d1c

# Description
casting flesh to stone spell opens up a menu for people adjacent to you
# Steps to Reproduce
be wiz, get flesh to stone, cast it when near someone
# What you Expected
for it to be selected target by clicking not menu pop up
# What Actually Happened
a menu happenned

**Comment by Killette2** [comment]
Thank fuck this ancient shoe is being updated
