### ISSUE TITLE
Anti-toxin and allicin do not remove snowflake botany versions of the "common poisons"

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16807]
#### Description of issue
Anti-toxin and allicin (botany anti-toxin) remove toxin from living mobs but not solanine, sleep toxin but not valerenic acid, sulfuric acid but not formic acid, polyacid but not phenol.

#### Difference between expected and actual behavior
I kind of expected anti-toxin to work on those, or allicin to work at the very least since it's the botany anti-toxin variant. The second could at least be considered a feature if it did. Not that I think anti-toxin needs to be buffed, I consider it a consistency issue.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
It's a feature

**Comment by Killette2** [comment]
Also noted - botany chems (were a contentless mistake) don't react the same way in plant trays. Plant trays only check for antitoxin when lowering the plant's toxicity but not the plant version.

**Comment by MadmanMartian** [comment]
I have a feeling it's because it checks for hard ID, rather than if it's a subtype

**Comment by Exxion** [comment]
Yes, because that's how our chemistry system works
