### ISSUE TITLE
Bio suits and bio hoods still get contaminated

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16800]
Despite https://github.com/vgstation-coders/vgstation13/pull/15155 giving them PLASMAGUARD, bio hoods and biosuits still get contaminated if you wear them in plasma.

![super beard complex sigma 2017-12-16 111631](https://user-images.githubusercontent.com/31839805/34073845-49df9630-e258-11e7-97fd-f5377c7d4f01.png)
.

**Comment by DamianX** [comment]
I can't reproduce this, what steps did you take?
![image](https://user-images.githubusercontent.com/6307265/34081439-f226d246-e34c-11e7-8ffb-93013c2ff46f.png)

**Comment by Pathid** [comment]
![asteroid center yankee 2017-12-17 122214](https://user-images.githubusercontent.com/31839805/34083384-ff50790e-e324-11e7-84f1-bcc6a13a2047.png)

Do you have the ZAS Plasma setting on "Oh Shit!"?
