### ISSUE TITLE
Plasma + Battery = Cell that can't be charged and Overnerfed explosion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16825]
(WEB REPORT BY: eenkogneeto REMOTE: 172.93.109.202:7777)
# Revision
8965a723067ce3e5747438473ae94fd65c2eb50b

# Description
Inject plasma into a stun baton, Turn it on and hit someone
This was nerfed some time in the past due to it being too strong (It used to have a dev tile) and is now painfully worthless.
# Steps to Reproduce
See above

# What you Expected
Explosion based on plasma injected, up to a cap obviously.

# What Actually Happened
500u of plasma exploded in a 1 tile weak explosion centered on the person holding the stunbaton, not even stunning the target.

Related bugs: If theres plasma in the cell it wont charge at all at a cell charger, wont explode either, same for a stunbaton with a plasma cell not charging in a recharger. This means you can make a cell that never goes over 0 and shove it in a borg if you want to be a dick.

**Comment by jknpj** [comment]
What misleading title

**Comment by SonixApache** [comment]
the explosion is based on the battery type now, right?

**Comment by Cyantime** [comment]
By 'Some point in the past', do you mean 'More than seven years ago'?
https://github.com/vgstation-coders/vgstation13/blame/f2ed22a049f4492abbaaba12b6b264f466b70be6/code/modules/power/cell.dm#L84
Before it was made to scale with cell charge, it was always a flat 0,1,2 explosion.
The explosion is based on the amount of charge currently in the cell. Inject a hypercell, put that into the baton you want to use.

**Comment by Killette2** [comment]
Yeah this scales with cell size. Base APC/baton cells are worthless, you gotta bring your own cell now.
