### ISSUE TITLE
>Movie_box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16826]
(WEB REPORT BY: kurba REMOTE: 172.93.109.202:7777)
# Revision
ed258b2256db095e9e614bdbdc6bb6d762206c0f

# Video jukebox must be named "Moviebox" without any spaces.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by MadmanMartian** [comment]
please don't shitpost via issue reporter.
