### ISSUE TITLE
Mops are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16835]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
2bf9d817088ea972f55540db3315ded858803015

# Description

Mops are currently useless, even though they go through the motions they currently do not clean messes, making them just an assinine slipping machine.
# Steps to Reproduce

Get a mop, wet it, attempt to clean anything. 
# What you Expected

Mops to actually work
# What Actually Happened

The mops, zey do nothing.

**Comment by SGuivenne** [comment]
Tested with water, and with bleach in water.  The mop animation completes, wets the floor as usual, but does NOT clean messes.  Soap cleans messes suggesting its probably not the messes.  Somethings clearly screwy.  Ask meet me in dorms for more info they were the attending admin that was doing weird admin shit

**Comment by Killette2** [comment]
Slippery soap suds when?

**Comment by Fruktlimpa** [comment]
Keep soap being the catch all cleaning master but make it degrade and eventually disappear like actual soap.
Make mops better but keep the slipping.
Make soap available for ordering in cargo.

Janitors gets to keep their free griff ticket and soap gets nerfed. Everybody is happy.

**Comment by SysadminJeroen** [comment]
I can confirm, I thought it might've been the bleach so I gave mask2697 a empty mopbucket and filled it with water, I have even used a brand new unused mop. It did nothing.

**Comment by Killette2** [comment]
-soap available for ordering in cargo
Trying to keep the botany man's business down I see

**Comment by agentofzog** [comment]
You can already purchase soap at cargo (for a high price).
