### ISSUE TITLE
Wet mops fail to clean

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16830]
(WEB REPORT BY: gringonius REMOTE: 172.93.109.202:7777)
# Revision
ed258b2256db095e9e614bdbdc6bb6d762206c0f

# Description
Mops wet the floors but fail to clean anything
# Steps to Reproduce
wet a mop and dunk it in a water bucket
try to clean blood, crayons or anything else
# What you Expected
clean shit
# What Actually Happened
fuck

**Comment by jknpj** [comment]
Did you wait until the action what done?

**Comment by jknpj** [comment]
Same as #16835
