### ISSUE TITLE
Unremovable cable.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16837]
(WEB REPORT BY: mongoon REMOTE: 172.93.109.202:7777)
# Revision
2bf9d817088ea972f55540db3315ded858803015

# Description
In E.V.A. room on derelict, there is a cable that when cut, creates cable piece but does not get removed, and can be cut infinitely. Tile above the APC's terminal.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by jknpj** [comment]
What map?

**Comment by SysadminJeroen** [comment]
Bagel.

**Comment by SysadminJeroen** [comment]
![dreamseeker_2017-12-21_18-17-37](https://user-images.githubusercontent.com/2915526/34268217-31356552-e680-11e7-878b-0f4bf8ef8607.png)
The tile to the right of the Engiborg is infinite, for some reason.

**Comment by jknpj** [comment]
i don't even

**Comment by PJB3005** [comment]
Probably a runtime?

**Comment by CptWad** [comment]
![image](https://user-images.githubusercontent.com/3959840/35123260-5adb3d46-fc56-11e7-9fee-3d6e250fabae.png)
dont see anything that does this map side? Just a normal cable with directions?

**Comment by CptWad** [comment]
checked the txt file I see nothing on the map that does this? Since all derelicts are 99% the same all derelicts should then have this problem so ill test it out.

**Comment by CptWad** [comment]
![image](https://user-images.githubusercontent.com/3959840/35163394-6a562ab0-fcfb-11e7-9f4f-4af8da33cd21.png)
on bagel

**Comment by gbasood** [comment]
prob was runtiming
someone check logs for when this was reported

**Comment by CptWad** [comment]
remove mapping (bagel) pls

**Comment by Kurfursten** [comment]
Cannot reproduce @Exxion
