### ISSUE TITLE
Medbay intercoms display the frequency and title of the channels

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16834]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
cbc473a28e0da33d7128c3e6b1a3df1c2bd9c2c7

# Description
People talking near Medbay intercoms in their headset will have the name of the channel and its frequency displayed on chat.

This bug seems bright new.

Sample :
Zachary Ehret [145.7] (Scientist)  says, "[Freq: 1351/Science] Zachary Ehret(Scientist): yo" 
In the classical orange Medbay intercom text.

**Comment by Pathid** [comment]
As someone who was observing that round, this phenomenon didn't have anything to do with the medbay intercoms. This was some tcomms script fuckery that was doing that.

**Comment by ShiftyRail** [comment]
Well then disregard
