### ISSUE TITLE
Excrutiating

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#16832]
Apparently it's spelled "Excruciating" who knew?
![untitled](https://user-images.githubusercontent.com/6224074/34215236-c8033d1a-e572-11e7-82b1-c44dbb3e84a8.png)
It's amazing how long it's been this way.

**Comment by Kurfursten** [comment]
Me thog not read message past red bold "The pain...!"

Me get jist of statement and move on to murdering what make thog in pain to start with
