### ISSUE TITLE
Prison cell 4 on bagel is bugged

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16849]
If you set a timer for it, it will unlock the door and the locker almost immediately. The timer will still be ticking down during this process as normal.

**Comment by CptWad** [comment]
Needs more testing? Having trouble finding the reason for this, as its literally the same thing for all cells but with 1 number replaced after "Cell "

**Comment by CptWad** [comment]
additionally I cant see any differences from tgstations cell as both are coded exactly the same

**Comment by CptWad** [comment]
ok so it does happen, no idea why. ill look into it more

**Comment by CptWad** [comment]
wew ill need a collab to take a look as I cant seem to find out WHY its not working

**Comment by DamianX** [comment]
collab here
let me just say
HAHAHA

HAHAHAHA

HAHA
HA

there's an extra door timer stuck inside the wall of the armory
for some fucking reason

when that hidden door timer processes it opens the windoor

**Comment by CptWad** [comment]
![1353489985874](https://user-images.githubusercontent.com/3959840/35166803-f7dd468c-fd07-11e7-9f92-107e4453a3fe.jpg)
GOOD FUCKING GOD HOW DID THAT GET THERE
