### ISSUE TITLE
Acid'd Items in inventory can't be removed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16847]
(WEB REPORT BY: valkyrieskies REMOTE: 172.93.109.202:7777)
# Revision
e0cf79dc47294f83e993f21c794dbc9273e09574

# Description
Accidentally acid'd an ID in my inventory, it turned into a "gooey grey mass", and I was totally unable to interact with it or remove it, rendering the slot useless.

**Comment by Pathid** [comment]
Can't reproduce, need more info. What type slot was it?

**Comment by Cyadox** [comment]
Valkyrie locked themselves out of Github, so just passing this on:
The item was in a slot in their backpack. They used sulphuric acid in a beaker on their ID, the beaker possibly containing space cleaner as well.

**Comment by ValkyrieSkies** [comment]
Correction, it was an ID in the sixth slot of my bag belonging to a braindead geneticist. Minor detail.
