### ISSUE TITLE
examining as an extendo arm borer will always result in you slapping what you're simply trying to examine which leads to trouble

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16845]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
e0cf79dc47294f83e993f21c794dbc9273e09574

# Description
basically what the title says. shift clicking on anything while you're a borer with the extendo arm will result in extending your arm at said thing.

**Comment by jknpj** [comment]
With shift+click or with the examine verb?
