### ISSUE TITLE
t-ray scanners let you see invisible people

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16859]
This has been a known bug since the chameleon gene came out for genetics. Now that we have more things such as invisibility spray and cloaks, along with better things like the P-ray scanner and other things that should not be mentioned, should we address if this is a bug or a feature again?

**Comment by SkowronX** [comment]
Keep it as is.

**Comment by SonixApache** [comment]
T-rays and P-rays are known to penetrate light refracting surfaces

**Comment by Lokiamis** [comment]
This has been a feature for like a decade

**Comment by MadmanMartian** [comment]
This is a feature.

**Comment by Killette2** [comment]
I didn't think this discussion would be received so negatively, nor did I know it was intended for anything beyond wires or pipes.
