### ISSUE TITLE
BYOND live icon/RSC corruption on space tiles.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16851]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
193ac4ca1074ed168dd6994560716c9d0d00ba50

# Description
https://imgur.com/a/MaOnr

# Steps to Reproduce
This happened on packedStation.
BYOND version : 510.

**Comment by jknpj** [comment]
I'm pretty sure that's a byond bug.

**Comment by PJB3005** [comment]
Thanks BYOND.
