### ISSUE TITLE
You can slip on lube while being on a janicart or other vehicle

### ISSUE THREAD

**Issue by small-boss** [d3athrow/vgstation13#16862]
#### Description of issue
You can slip on tiles with lube even if you are on a vehicle. If you try to buckle yourself to a ride that is on a tile with lube you will stunned and sitting in the vehicle

#### Difference between expected and actual behavior
expected: dont slip when driving over lube
actual: slip

#### Steps to reproduce 
1. get a janicart, wheelchair etc.
2. buckle in
3. drive over lubed floor

#### Length of time in which bug has been known to occur

if i had to guess i think #16705 caused it

#### Server revision

224443bda633f1ca00b897f0f656076f25e95d92 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MadmanMartian** [comment]
Oh lawd, seems that having it be an object that's crossed, it slips you right the fuck away.

I'm concerned that a jaunt-wizard might slip now.

**Comment by MadmanMartian** [comment]
Wait, wasn't this already a thing beforehand?

Previous lube itteration didn't have a Slip() check, so it would slip you anyway

**Comment by small-boss** [comment]
> Wait, wasn't this already a thing beforehand?

I am pretty sure that a vehicle protected from lube floors. I might go and test it out with a older version of the game.

**Comment by ShiftyRail** [comment]
Riding secways, wheelchairs or the janicart was a known ~powergay~ and legitimate strategy to work around lubed floors.
