### ISSUE TITLE
Deffs disposals leads to a mass driver that is only reachable via cargo or through two layers of shutters that only open when you fire the fucking mass driver

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16861]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
224443bda633f1ca00b897f0f656076f25e95d92

# Description
THE DEFF DISPOSALS LEADS TO A MASS DRIVER THAT IS ONLY REACHABLE VIA CARGO OR THROUGH TWO LAYERS OF FUCKING SHUTTERS THAT ONLY OPEN WHEN YOU FIRE THE FUCKING MASS DRIVER
# Steps to Reproduce
GET FUCKED BY DUNY
# What you Expected
NOT THIS
# What Actually Happened
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Riekland** [comment]
![screenshot-2017-12-25 full-0 png png image 8224 x 8224 pixels](https://user-images.githubusercontent.com/9220789/34337973-e8f6d7d8-e95b-11e7-885d-214e7e7bf108.png)

here's your pick son of bitch

**Comment by DamianX** [comment]
just go through the plastic flaps lol
