### ISSUE TITLE
Something about CO2 calculations is very off for some mobs

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16860]
#### Description of issue
Mice will drop dead at very small amounts of CO2, 0.02 moles or something. Monkeys will go into a near-death state at around 0.6 moles and never come out of it.

#### What you expected to happen
Mice should follow what the max_co2 for simple animals is, 5 (moles?)
Monkeys have a safe_co2_max of 10, which appears to be partial pressure.

#### Length of time in which bug has been known to occur
I am fairly sure this started when all the recent ZAS updating was done.

#### Server revision

Game: 224443bda633f1ca00b897f0f656076f25e95d92 
Patches: 9e34bcea4d28270b966365362177f6890fc3ca45 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
So THAT'S why mice randomly died to nothing
