### ISSUE TITLE
Shuttle exhaust can pierce through the cargo shuttle and burn everything inside

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#16866]
#### Description of issue

![this is fine](https://user-images.githubusercontent.com/17928298/34340459-f368d270-e96a-11e7-9cef-605fb948adb8.png)

#### Difference between expected and actual behavior

Expected: cargo techs to be safe inside the cargo shuttle
Actual: A quick and painful death

#### Steps to reproduce 

Launch the mining shuttle while the cargo shuttle is docked.

#### Specific information for locating

Happens on metaclub due cargo layout.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by AlphaBuffalo** [comment]
I like this FEATURE. Kind of makes sense, having thrusters up against another shuttle might cause the thrusters to burn the shuttle

**Comment by PJB3005** [comment]
@AlphaBuffalo no, because there's no way the exhaust fire can get inside an airtight shuttle without melting the glass.

Not to mention the mining shuttle on deff doesn't have this, so that doesn't even make sense.

**Comment by AlphaBuffalo** [comment]
melting walls when?

**Comment by Probe1** [comment]
That is fucking hilarious.
