### ISSUE TITLE
Bagelstation causes AIs to crash randomly

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16873]
#### Description of issue
Bagelstation causes AIs to have their Dreamseeker client crash at random. Various players have agreed that it's the map doing it. Could have sworn there was a formal issue for this already but apparently not.

#### Length of time in which bug has been known to occur
This has happened for months, maybe as long as the map has been in rotation.

#### Server revision

Game: a2e83a82c01a6fdb8a92c2e2e689db8726421f14 
Patches: 9e34bcea4d28270b966365362177f6890fc3ca45 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
That runtime has nothing to do with it.

**Comment by ShiftyRail** [comment]
This runtime happens everytime someone logs off.

**Comment by Pathid** [comment]
Alright, I'll remove it from the description then.

**Comment by Ephx1** [comment]
I want to suggest something different: Bagelstation gives the AI a jukebox, therefore they're more likely to listen to it. I suggest that somehow the streaming crashes the client, seeing as how every crash I've had as an AI was with the juke/sound system on. Even on other maps.

Probably worth noting I don't use the VLC type streaming.

**Comment by Pathid** [comment]
Seems like it's happened to me with the jukebox off but I can't be sure.

**Comment by ValkyrieSkies** [comment]
I've never used the jukebox as Bagel AI before and I've been subject to horrifically common crashes in my time.

**Comment by DamianX** [comment]
Still happening, of course.

**Comment by ValkyrieSkies** [comment]
I don't think anyone actually believed the juke was responsible.

For what it's worth, this bug happens to me the most when I'm trying to jump the camera to a person or when I scroll the camera long distances.

**Comment by Exxion** [comment]
Does this still happen?

**Comment by gbasood** [comment]
This is that one specific crash that was supposed to have been resolved by 512
When I was testing 512 to see if it crashed AI players still, it seemed to do it less or not at all

**Comment by Exxion** [comment]
OK then
Reopen if encountered again
