### ISSUE TITLE
Aliens can use autoinjectors.

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#16871]
#### Description of issue

> "The alien hunter (441) injects the alien queen with the autoinjector." 

#### Difference between expected and actual behavior

They are aliens, they shouldn't be able/have the dexterity to do this.

#### Steps to reproduce 

Be alien, acquire autoinjector, be an asshole.
Update : here is how to acquire the autoinjector
https://streamable.com/0tbik
Basically Ayys can be given things. Which they shouldn't.

#### Length of time in which bug has been known to occur

Just last round.

#### Server revision

a2e83a82c01a6fdb8a92c2e2e689db8726421f14 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
https://streamable.com/plm0f

Turns out you can give items to xenos.

**Comment by Ephx1** [comment]
You've been able to give ayys items for a very long time, and I'm fairly certain their dexterity check doesn't actually apply to anything except trying to use consoles or pick up items.

**Comment by jknpj** [comment]
It's still a bug and the fact nobody reported it properly is really bad.

**Comment by Pathid** [comment]
While it's true they can hold stuff that are given to them, it's also true that xenos can pick up hyposprays and children of hyposprays off the ground. Grenades too. It's an attack_paw thing.

**Comment by Killette2** [comment]
by bug, I think you mean my favorite feature that is an intended part of the game
