### ISSUE TITLE
You can be a double cultist

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16884]
![screenshot_106](https://user-images.githubusercontent.com/5169310/34366120-a90701a6-ea65-11e7-8426-d9fe0f00760d.png)
Get 2 words, get 2 papers, hear double
![wr6ydezntxgozcqdodu7bg](https://user-images.githubusercontent.com/5169310/34366118-a6c2d3c0-ea65-11e7-806d-e0b869449098.png)

**Comment by Killette2** [comment]
That round also apparently drafted a sec and HoP into the cult, who were then not made cultist due to the implants.

**Comment by ShiftyRail** [comment]
Datums when

**Comment by DamianX** [comment]
> [13:24:56]DEBUG: Donnager had cultist enabled, so drafting them.
> [13:24:56]DEBUG: Sylphyn had cultist enabled, so drafting them.
> [13:24:56]DEBUG: Felipez8 had cultist enabled, so drafting them.
> [13:24:56]DEBUG: Killette2 had cultist enabled, so drafting them.
> [13:24:56]DEBUG: Killette2 was force-drafted as cultist, because there aren't enough candidates.
> [13:24:56]ADMIN: Starting a round of cult with 2 starting cultists.

First was the AI, second was a sec officer, third was the HoP.

**Comment by SonixApache** [comment]
![double_cultist](https://user-images.githubusercontent.com/8468269/34367978-81e9f402-eab0-11e7-96a6-34c1ca6d2f55.png)

**Comment by Killette2** [comment]
I think we should just cancel cult

**Comment by Pathid** [comment]
This happens with Double Agents too, right?

**Comment by Killette2** [comment]
I have a really really old screenshot of me getting traitor changeling traitor but I'm not sure if it counts being so old

**Comment by Hugh-G-Rection** [comment]
^ #HumbleBrag

**Comment by Killette2** [comment]
I'm an old player btw
