### ISSUE TITLE
Deff lacks upload boards, notoriously NT Default

### ISSUE THREAD

**Issue by EdXbtkOEwGw** [d3athrow/vgstation13#16882]
According to a threadposter at least.

**Comment by Aurx** [comment]
Lacking NT Default sounds like a feature to me.

**Comment by Accipitermaris** [comment]
It's missing ROBOCOP too. I just freeform'd+planning frame'd my very own ROBOCOP when I wanted to ROBOCOP but it'd be nice to have it, sure.
