### ISSUE TITLE
Supermatter Shard No Longer Glows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16881]
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
# Revision
84b8d1764a794c2f6e4b75fc657bfd688552fc43

# Description
The supermatter shard no longer glows when subjected to an oxygen rich environment and low temperatures.

# Steps to Reproduce
Isolate the supermatter shard in a majority O2 atmos, and chill it. It should glow red but doesn't anymore, as of late.

# What you Expected
The same glowing visual exhibited as it used to in the past as of a few updates ago and all before that.

# What Actually Happened
It doesn't glow anymore since a few updates ago.

**Comment by DamianX** [comment]
Witnessed this myself, one shard in a passive setup was glowing, another shard in an active setup wasn't.

**Comment by jknpj** [comment]
Pressure stats my dudes, pressure.

**Comment by JackMassacre** [comment]
If you're asking what our pressure stats were, my tests were done using the same pressure levels i've always used before. Specifically, 200-1000kpa of O2, sometimes on one tile, sometimes in a chamber with multiple tiles.

When chilled, this has always caused the shard to glow before recent updates. As I understand it, there were some tweaks to supermatter recently, and I figure that's where something changed.

**Comment by Kurfursten** [comment]
@Exxion This is not an issue and as of the supermatter monitoring computer it's easier than ever to see where glowing starts (80%). I get glowy every round I play.

**Comment by Exxion** [comment]
Reopen if someone manages to reproduce this when it demonstrably should be glowing
