### ISSUE TITLE
Mesons don't show up correctly on Vox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16895]
(WEB REPORT BY: skowron REMOTE: 172.93.109.202:7777)
# Revision
f0d737f7833e740910dd0a9533aeb9373a978071

# Description
Mesons appear as if they would on humans.

# Steps to Reproduce
Put mesons on.

# What you Expected
Mesons fitting vox eyes.

# What Actually Happened
Not that.

**Comment by Rhimrifer** [comment]
This is an issue with most eye equipment. I figured it was a product of Noone Wants to Draw These syndrome.

**Comment by SkowronX** [comment]
that's wrong. vox used to have the sprites so someone must have fucked up somewhere

**Comment by Rhimrifer** [comment]
Oh my bad. Looks like they're still there, but unused.
