### ISSUE TITLE
Box loading doors buttons inverted pixel offset

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#16905]
The blast door buttons in cargo bay are now floating in the air to the right instead of offset to appear on the glass windows to their left. Could be someone messed this up by accident by pasting buttons from Defficiency which has the pixels in the opposite direction.

**Comment by Hugh-G-Rection** [comment]
They aren't floating, they were moved to the floor so people could stomp on them like that Chuk E Cheese spider game to open doors while their arms are full of pizza.
