### ISSUE TITLE
You can't dip cigarettes in coffee cups

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16906]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
58b5dde165c7ef46ad84db3fc2920cccd63194b8

# Description
You can't dip cigarettes in coffee cups. You can dip them in beakers, though.
# Steps to Reproduce
- Acquire a cigarette, cigar, or any subtypes
- Acquire a cup of coffee from a coffee machine (or something similar)
- Click on the cup with the cigarette in your hand
# What you Expected
Coffee smokes!
# What Actually Happened
Nothing.

**Comment by jknpj** [comment]
Cups aren't glass containers, they're food containers.

**Comment by SonixApache** [comment]
They hold other liquids/reagents, though.
It's stupidly unintuitive that you have to pour your coffee from the cup into some other, more solid container (like a mug, glass or beaker) before you can dip your cigarette in it.

**Comment by SonixApache** [comment]
Can't use flasks either.
  
And upon further testing, you can't use mugs or glasses either.

**Comment by SonixApache** [comment]
I fixed this in #20602 and forgot.
