### ISSUE TITLE
Engineering cyborgs can scan and produce leather

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#16901]
#### Steps to reproduce 
Obtain leather
Scan leather
Print leather

The latest changes to the mat synth probably caused this.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
Same for SNOWBALLS

**Comment by Killette2** [comment]
what about wooden planks since they can also be stacked and built with?

**Comment by jknpj** [comment]
those too i suppose

**Comment by Hugh-G-Rection** [comment]
It's a feature(?)

**Comment by jknpj** [comment]
It isn't.

**Comment by Probe1** [comment]
I feel like we should change the name to **mineral** synthesizer if its only going to scan mineral based stuff.  All this stuff can be scanned not just leather.
![dreamseeker_2018-02-17_15-07-40](https://user-images.githubusercontent.com/8550416/36345199-567a7dba-13f4-11e8-8f17-f5023131da62.png)
