### ISSUE TITLE
Xenobio slime potions should be smaller

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16904]
There are items that are in bottles that you would think would fit in pockets but they don't and are rather annoying to manage in your inventory. These include
-slime steroid
-slime nutriment
-slime extract enhancer 
please quality of life my job

**Comment by SonixApache** [comment]
>[good first issue]

you mean [WYCI]  ?

**Comment by Killette2** [comment]
I thought WYCI was reserved for ideas
