### ISSUE TITLE
Packed - Can't reach the paper table in the mechanics office

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16909]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
58b5dde165c7ef46ad84db3fc2920cccd63194b8

# Description
On packed, you cannot reach the table with the paper dispensers without opening the locker next to it.
# Steps to Reproduce
Step into the mechanics office, attempt to grab some paper.
# What you Expected
Paper in my hand, on demand.
# What Actually Happened
Required locker wizardry.

**Comment by PromethTK11** [comment]
Intened tho
