### ISSUE TITLE
Cargo Shuttle OP

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16914]
(WEB REPORT BY: rpaul REMOTE: 172.93.109.202:7777)
# Revision
58b5dde165c7ef46ad84db3fc2920cccd63194b8

# Description
I got onto the shuttle, it departed an i got removed, only my id was left laying on it

# Steps to Reproduce
go onto shuttle

# What you Expected
not to spontaneously vanish

# What Actually Happened
i died

**Comment by jknpj** [comment]
Another quality report

**Comment by DamianX** [comment]
what could he possibly have meant by this?

**Comment by SysadminJeroen** [comment]
It was the cargo shuttle on Bagelstation.

**Comment by AutismSpider** [comment]
Just fucking happen to me cargo shuttle on Bagelstation its null spacing people some how.
![shit map and shit coders whats new](https://user-images.githubusercontent.com/10268342/34422981-aab06176-ebde-11e7-921b-0fbe0f361655.PNG)
