### ISSUE TITLE
Bunsen Burners Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16926]
(WEB REPORT BY: lunanite REMOTE: 172.93.109.202:7777)
# Revision
8962a71cda7dd136a92e43a38d7c4ed99123a2e8

# Description
Bunsen Burners don't work, have no fuel and presumably cannot be refilled. Kind of makes it hard to do Xenoarch.
# Steps to Reproduce
Try to use any bunsun burner or refill with fuel.
# What you Expected
Put beaker into burner, turn on until solutions achieves desired action.
# What Actually Happened
"The bunsen burner splutters out from lack of fuel.

You open the fuel port on the bunsen burner.

You cannot directly fill this object."

**Comment by Lunanite** [comment]
Spent a bit more time trying things, it can only be filled with specifically a Fuel Can (which I don't think you can even get on the Outpost, and the burner starts empty.) Would make a lot more sense for it to be fillable by more things, or at least for you to be able to get a can of fuel for it easily. 

EDIT: I also filled and spent the burner twice (100 units of fuel) and it did absolutely nothing to the beaker's Density Separated Sample. Does the Burner even do anything while on?

**Comment by MadmanMartian** [comment]
What fuels did you use.

It can only take ethanol, welder fuel, glycerol, and plasma, and only one of each.

If you're trying to heat 50 units of density separated sample it's going to take a long time.

**Comment by jknpj** [comment]
>Kind of makes it hard to do Xenoarch.

My sides

**Comment by Lunanite** [comment]
Madman, I was able to refuel it with Welder Fuel, but only from specifically the Fuel Can item. 

The more pressing matter I noticed was that the bunsen burner, when it did turn on, did literally nothing to the beaker with Density separated sample I put on it, despite refueling and letting it run to empty a 2nd time.

**Comment by MadmanMartian** [comment]
I have not been able to reproduce not being able to refuel it (Have been able to refuel it from a beaker of ethanol, a bluespace beaker of glycerol, and a coffee mug of plasma)

The bunsen burner needs to be empty of all different fuels before it will accept a new one.

**Comment by MadmanMartian** [comment]
There are thermometers you can use to get the temperature of the beaker, basic mercury ones available via medical vending machines, and electrical 3dp ones available via RnD. They'll give you some feedback as to what temperature it is.
