### ISSUE TITLE
Slimepeople don't heal from rezadone

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16937]
Last round a guy got nommed by slimes before becoming a slime person. They can't use cryo so I gave him rezadone, the clone damage didn't heal. Because of this slime people can't heal clone damage.

**Comment by EdXbtkOEwGw** [comment]
Not even 1 point of healing?
Are you sure he wasn't overdosing on the rezadone? It stops healing on OD.

**Comment by Killette2** [comment]
5 units but he asked for more so I gave him 5 more later. Will double check

**Comment by Killette2** [comment]
duplicated this myself using only 5 units. Can confirm

**Comment by AI-Is-Rogue** [comment]
>They can't use cryo

Are you sure? It seemed to work fine the last time I was a slime person.

**Comment by Killette2** [comment]
I'm not sure but since slimepeople take heavy toxin damage from cold I assumed it would be a bad idea. Is it safe? Either way the rezadone problem still stands.

**Comment by Pathid** [comment]
I was under the impression slime people were immune to clone damage.

**Comment by AI-Is-Rogue** [comment]
Cryo is safe for them, the temperature doesn't affect slime people at all. Even without a mix they are safe inside of the tubes.

**Comment by Killette2** [comment]
Well Path the bug report comes from taking damage prior to becoming a slime person. I haven't tested say, a decloner, on a slime person myself
