### ISSUE TITLE
Grue vision doesn't activate until relog

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16944]
Grues are supposed to have a neat negative vision filter. But if you're a ghost who gets stuffed into one by a madmin, you'll never see it unless you relog. Presumably this is an issue with the colourmatrix feature in general.

**Comment by DamianX** [comment]
I admin-ghosted and dragged my ghost into a grue, I can see the inverted vision just fine:
![image](https://user-images.githubusercontent.com/6307265/34634639-54730800-f286-11e7-8eba-dde08c4bf7e4.png)

**Comment by Shadowmech88** [comment]
I dragged both myself and a guest logon into a grue, the vision started up fine both times.
Though interestingly, in the time since this report was made, the opaque tiles for negative vision have become white instead of black.
