### ISSUE TITLE
Summon Robes needs to update clothes stuff

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#16943]
#### Description of issue
* Casting Summon Robes while wearing something in your suit storage will not drop the item even if it does not fit on your robes.
* Casting it with your face covered will result in sunglasses, masks and headsets not appearing on your sprite until you take them off and put them back on.
* Casting it while wearing things like rig helmets and magboots will leave greyed-out action buttons stuck on the top of your screen.

**Comment by jknpj** [comment]
Thanks old coders.
