### ISSUE TITLE
blood count showing up to non-vamps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16956]
(WEB REPORT BY: libertino REMOTE: 172.93.109.202:7777)
# Revision
fa1b977af993c20a64166dff4e45704f57e65c5f

# Description
vampire blood count shows up when you are not a vampire.
# Steps to Reproduce
I just started shift during evacuation as an assistant and it was there.
# What you Expected
I expected to not see a vampire blood count when im not a vampire.
# What Actually Happened
I saw the blood count, and therefore knew the round type.

**Comment by Killette2** [comment]
So was it vampire?

**Comment by ShiftyRail** [comment]
@Exxion no longer an issue as of datums
