### ISSUE TITLE
TG Surgery Tool Sprite Port

### ISSUE THREAD

**Issue by Chronakai** [d3athrow/vgstation13#16958]
They might need a bit of color tweaking to match up with the scalpel, but I think it would look better. And I've always wondered what the fuck the OG Cautery sprite even is.

![Retractor](https://tgstation13.org/wiki//images/c/c8/Retractor.png) ![Drill](https://tgstation13.org/wiki//images/8/88/Drill.png) ![Hemostat](https://tgstation13.org/wiki//images/4/48/Hemostat.png) ![Cautery](https://tgstation13.org/wiki//images/5/54/Cautery.png)

**Comment by DrSnips** [comment]
If the cautery gets changed here the other laser cautery tools would need a change as well. I'm also not a huge fan of that drill sprite's shape. It feels a bit too square

**Comment by strawberrytan** [comment]
I like the idea of the hemostat and retractor being a bit more defined as their current sprites sort of blend in to regular tables, I'm usually alt-clicking tiles to grab them. Not sure how these will look in-game though. Might be cool.

**Comment by Chronakai** [comment]
@DrSnips Yeah, drill I could see staying how it is. But I had no idea there were other cautery tools.

**Comment by Mothblocks** [comment]
@strawberrytan Maybe it's just because I'm inept, but my first time doing robotics I couldn't find the tools I needed because with their color scheme they looked like outlines. This change would probably also help inept new players as well as just making the sprites look good.
