### ISSUE TITLE
Weird slime monkey explosion bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16955]
-become slime man
-eat a bunch of monkey cubes, since you have no bones it won't break your bones and shatter your organs
-get an object thrown at you, this happened twice last round due to a PDA throw and a faggot(food)
-suddenly all the brute from the monkeys you eaten are inflicted and you die instantly
-you melt into a puddle since you're a slime man and all your little baby monkey abortions are scattered everywhere

This is one of the screenshots from the event if you need a rough estimate on what happened
![screenshot_111](https://user-images.githubusercontent.com/5169310/34464473-9552e80e-ee4e-11e7-9449-28b69520d4e0.png)

**Comment by SonixApache** [comment]
feature

**Comment by Hugh-G-Rection** [comment]
That's spess, baby.

**Comment by MadmanMartian** [comment]
Found it; It's calling createwound without updating damages.
