### ISSUE TITLE
Claws in Boxing Gloves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16959]
(WEB REPORT BY: dtscurvy REMOTE: 172.93.109.202:7777)
# Revision
fa1b977af993c20a64166dff4e45704f57e65c5f

# Description
A Diona wearing boxing gloves will slash people through the gloves.
# Steps to Reproduce
Play a diona
Put boxing gloves on
Punch a nigga
# What you Expected
That it would deal stun damage like boxing gloves usually do (i think)
# What Actually Happened
The guy I was boxing lost all his blood.

**Comment by Killette2** [comment]
So should boxing gloves take away the claws damage but keep the racial strength if there is any aside from what the claws provide?

**Comment by unid15** [comment]
Claws actually shouldn't provide additional damage when wearing any sorts of gloves, the bug should be purely visual/auditory
