### ISSUE TITLE
M_REGEN ("You feel better" genetics mutation) does literally nothing.

### ISSUE THREAD

**Issue by EdXbtkOEwGw** [d3athrow/vgstation13#16966]
As in there's not even any code for it.

Should either be made to do something or commented out

**Comment by Killette2** [comment]
did you look in carbons?

**Comment by PJB3005** [comment]
I checked the entire source. No references to it anywhere.

**Comment by jknpj** [comment]
That's just the **genki** gene

**Comment by JackMassacre** [comment]
This sounds like a great opportunity to bring in something new. How about a reduced/no hunger superpower instead? Would be nice to have powers that are less of a powerup and more of a convenience.
