### ISSUE TITLE
Lots of atmos/piping/vent mistakes and omissions in packedstation map.

### ISSUE THREAD

**Issue by JackMassacre** [d3athrow/vgstation13#16969]
Both sets of scrubbers in the captain's office and captain's quarters face south when they should face west, and thus start disconnected from their respective piping. Beneath the cigarette machine and beneath the rack.

The captain's office and quarters scrubbers also start out scrubbing plasma and oxygen, instead of plasma and CO2.

The unary vent that is supposed to serve as vent pump for the four tiles between the two sets of double-airlocks at the brig entrance begins the round turned off.

There is no air alarm in the brig proper to control the vents and scrubbers.

There is no air alarm in the detective's office.

The unary vent pump hidden beneath the equipment rack in the mining dock room in cargo is facing south when it should be facing north, and thus does not connect to air supply piping.

There is a stray "port maintenance" air alarm in the maintenance tunnel directly south of the pod bay. It does not control any vents or scrubbers. The existence of another maintenance air alarm in the central eastern part of the station that IS connected to a nearby vent and scrubber within maint tunnel probably suggests the stray one was intended to have its own vent and scrubber.

There is a redundant "Research Division Air Alarm" in the borer development room (as the airlocks name the small room), which controls the same vents and scrubber that are already controlled by the air alarm in the main research division hallway, on the outer wall of the RD's office.

The borer development room also lacks its own working scrubber connected to the waste piping, and instead has a scrubber connected to the isolated orange piping that borers are intended to crawl out of, except this scrubber is on by default and scrubbing the small room's atmos into its isolated piping, by mistake. It's also noteworthy that this little room is not properly designated as a separate area from "research division", for blueprint purposes, and lacks its own APC to power its equipment as well.

The center-most unary vent pump in the AI Upload Access room starts out facing west when it should face east, and thus isn't connected to any piping. Also there are two sets of vent pumps and two sets of scrubbers in the AI Upload Access room, for no discernable reason. It's quite a small room.

The courtroom vent pumps both start out turned off instead of on. The westernmost courtroom scrubber starts scrubbing only CO2, but not plasma, while the other correctly starts out scrubbing both.

The Quartermaster's office does not have its own vent pump or scrubber, and in fact the air and waste piping doesn't even come near the office. There is a redundant "Cargo Bay Air Alarm" inside this office which controls the same vents and scrubbers as the air alarm right outside in the main cargo bay area. The QM office does not seem to have its own blueprint area designation, nor APC or unique air alarm.

The scrubber in the Paramedic Station room near medbay begins the round scrubbing only CO2, but not plasma.

The Gateway room does not have its own air alarm.

**Comment by StreptoMutans** [comment]
The fitness room locker room part where the clothing vendors are has a vent facing south when it should face north too

**Comment by PromethTK11** [comment]
Holy shit

edit: Leaving this here, brig needs an evidence locker and one of the flash isn't working
