### ISSUE TITLE
Can't cure a virus

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16973]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
fa1b977af993c20a64166dff4e45704f57e65c5f

# Description
Something called Advance Disease can't be cured even via "Possible cure"

# Steps to Reproduce
Inject yourself with it

# What you Expected
To be able to cure the virus

# What Actually Happened
Neither orange juice nor radium cure the virus

**Comment by MadmanMartian** [comment]
virus1, lovely.

**Comment by DeityLink** [comment]
Should no longer appear in rounds unless badmins force them in.
