### ISSUE TITLE
Can fill multiple vending machines with one pack

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16975]
(WEB REPORT BY: drexplosion REMOTE: 172.93.109.202:7777)
# Revision
4149dc502de725a548be22cfcb1b44d4e9ecb262

# Description
If I drag a pack onto multiple empty vending machines, I can greate several copies of the same vendor. It can only be done if you do this before the first vendor finishes installing.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Killette2** [comment]
Sadly since the way this is coded, you cannot use it to dupe items. It just makes the item jump around when you take it from multiple vending machines. Consumables may be an exception?
