### ISSUE TITLE
Chameleon gene does not work while resting.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16977]
(WEB REPORT BY: tnepr REMOTE: 172.93.109.202:7777)
# Revision
4149dc502de725a548be22cfcb1b44d4e9ecb262

# Description
You don't go invisible if you hit rest when you have the invisibility gene.

# Steps to Reproduce
Have invisibility gene
Rest

# What you Expected
Go invisible eventually

# What Actually Happened
Lying on the ground like a chump for everyone to gawk at

**Comment by Dacendeth** [comment]
I thought it was like this so you could find dead chameleon bodies? It also doesn't work when you're buckled into a chair.

**Comment by DamianX** [comment]
Do we call this a feature?
