### ISSUE TITLE
Superfart with Borers is Superbroken

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#16988]
#### Description of issue
If you superfart with a borer inside of you, it throws the borer out of your body and it keeps its verbs as if it is inside of you, but can move independently and ventcrawl.

#### Difference between expected and actual behavior
Slugs shouldn't come out the bum, or maybe they should?  All I know is that it is best if they don't keep their internal verbs that can help you across the map.

#### Steps to reproduce 
fart with a borer inside of you while you have the superfart genetic power.

**Comment by EdXbtkOEwGw** [comment]
Has Science Gone Too Far?

**Comment by RFultra** [comment]
Braaaaaaaaaaaaaaaaaaaaaaaaaaaap

**Comment by RFultra** [comment]
Borer girl would be proud

**Comment by Killette2** [comment]
Holy shit
