### ISSUE TITLE
Up the price of staff of change

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16981]
It's not that the staff of change is the ultimate win/robust ticket, because it is not. The reason the staff of change should have a heavier price is because of it's effect on the people who get hit. Making someone a non-humanoid, say a slime, xeno, monkey, whatever usually permanently makes it so they cannot do their job after that point. They cannot repair the station or actively do much anything but obtain valids because of their human/snowflake form being stripped from them. The only thing that we have that comes close to doing this would be soul stones/necro staff but they at least demand you be in crit first. The artifact just has too large of an impeding impact for it's cost when it changes your form and should receive a price hike for the cost of that chaos.

**Comment by SonixApache** [comment]
go here
https://github.com/vgstation-coders/vgstation13/blob/9c2ebba5021eee43e4bb76c2f9e5ed92a4331769/code/game/gamemodes/wizard/artifacts.dm#L22
add a line that says
`price = Sp_BASE_PRICE * 2`
replace 2 with more if you think it should cost more

just make the fucking PR

**Comment by Pathid** [comment]
Sounds like a good case for bringing back xeno brain surgery.

**Comment by Hugh-G-Rection** [comment]
Stop trying to balance space. It can't be done and only punishes people who aren't shitters when you try. Dont make me copy my shitty rant from the dimensional push complaint issue.
I need the SoC along with spells for snake memery, frankenstein skeleton armies, bound staff-turrets and Darwin's Primordial Rage Cage. Don't take away my ability to gimmick because there are people who just shoot everyone 4noraisins. Sometimes you don't get to do your job, that's just spess.

**Comment by Killette2** [comment]
Back when you could turn people into cluwnes it was considered a problem due to some of the things I mentioned above. Getting turned into some of the other things that SoC provides basically makes you a cluwne that can attack back such as an xeno or slime. Not to mention the fact it can make you a borg and some people would rather not play than be a borg, witnessed the other day where the clown went braindead after he became one which I'm sure we all could understand.

The only other thing I could suggest is if you could make a "cure" for the staff of change where when applied it reverts you back to your original form. Being crippled by having your hands and headset taken away by a stray bolt that can be spammed really sucks and it's no argument that SoC is one of the most chaotic things. Being able to undo it's damage would be a blessing for players that otherwise feel stuck as whatever they are begging for the shuttle for sweet release.

**Comment by Hugh-G-Rection** [comment]
The game is intended to be chaotic and unpredictable. Some days you go to work and do your job and go home without anything happening. Some days you to go work and a magic man turns you into a robot, you get to come to terms with your new existence, perhaps forced to help the person who changed you, only to have your laws changed forcing you hunt them down, on the way being changed into an alien or slime and faced with the decision of helping the station or becoming it's enemy. You say it "really sucks", but these kind of wacky situations you're forced into is literally what makes this game what it is, and if you're so jaded with the experience that you'd rather kill someone or suicide than spend a little time outside your comfort zone then I honestly don't know why you're still here. 
The problem as I see it, and this may just be the nostalgic oldfag in me talking, are the people who are more concerned with "winning", gaining attention and/or their own personal projects than they are with sharing in a fun and unique experience. We've all had at least one fun gimmick shut down by someone who refused to accept any version of the round other than their own, like an atmos tech who fireaxes a "friendly" wizard so he can dick with pipes for two hours alone and uninterrupted. 

And sure, maybe some of the excitement is gone for you. Maybe after being turned into a borg or xeno for the 500th time the experience has lost it's charm. Maybe the only thing keeping you in space is the personal challenge of succeeding at a certain job or activity, or garnering the positive attention of your peers, believe me I've been here long enough to understand that feel. But it puts you in the minority, and it means you're playing this game for the wrong reasons and skews your judgement. But that's just one clowns shitty opinion.

**Comment by EdXbtkOEwGw** [comment]
Your argument here is "don't nerf anything, I'll use it good, I'm a gud boi, it's the fault of the guy playing to win!"

Until we start dealing with antags "playing to win" administratively (which will be NEVER) the only other way to deal with balance issues is through the code.
Sorry but one thing being used so fucking often lowers the overall wackiness of the game.

**Comment by Hugh-G-Rection** [comment]
My argument is stop boohooing and removing features when you don't like what happens to you. If we dislike assholes in our community, then we should do something to curb the behavior. But if we say as a server that it's okay to be assholes, then you need to fucking deal with sharing the world with them like an adult or leave. What we shouldn't do is to continue nerfing and removing features because you are personally inconvenienced or angered by them. Deal with it. 
Best case scenario, this change would make the assholes who would use SoC to be a dick to everyone instead say "Welp guess I'll just kill everyone instead." Real improvement.

**Comment by EdXbtkOEwGw** [comment]
So, it's impossible to recognize a balance flaw unless it personally made you mad, which obviously means you can't change it then.

No that's just fucking stupid.

**Comment by SonixApache** [comment]
antags are antagonizing me too hard
we must limit the means of antaggery

You say the antags are playing to win, but if you're trying to beat them, aren't *you* playing to win?

**Comment by Killette2** [comment]
Killing everyone still takes more effort than staff of change, even with mutate.

**Comment by strawberrytan** [comment]
SoC is also a big gamble though, since 9 times outta 10 that xeno will be coming for the wizard

**Comment by Killette2** [comment]
That's why I mentioned it's not the power of the staff for the wizard because it's not a big power play, it just kinda fucks everyone in the most chaotic way really cheaply.

**Comment by Killette2** [comment]
Another thing I considered is we could move it to the bundle box pool and remove it, but I'm not sure if I want to take away direct options from wizard just yet. If it was rare like that it wouldn't need any sort of nerf and it would still have it's charm when it appears.

**Comment by agentofzog** [comment]
You already have to buy bind if you don't want to lose the thing if you face down a banger. Plus if the crew isn't trash they can kill the wiz and change everyone back into humanoids.  Really, it's easier for the crew to recover from a SoC than a bunch of other wizard shenanigans.

This is just the sort of thinking that killed viro as an antag choice because nobody bothered to put on internals.

**Comment by Killette2** [comment]
>internals stopping a viro antag

LUL

I will agree bind + artifact really helps and should be taken tactically, but that should not be a factor for the artifacts price because you don't have to get it. Many artifacts even fit on your back, belt, or suit storage with wiz robes. If anything that should make bind cost 10 if it doesn't already but keep the upgrade prices for advance bind and it's cooldowns as is.
