### ISSUE TITLE
Holodeck Console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#16995]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
9034a5c4b8dcae8798d09d31e19aab3e22aed1cb

# Description
AI is able to use the console even if it was unbolted as long as it doesn't close the control window

# Steps to Reproduce
Have one player be a borg/AI and click on the console, have another player unbolt it

# What you Expected
Window to automatically close like with most machinery

# What Actually Happened
Nothing, I was able to control and unpowered console like it was still fine and visible

**Comment by DamianX** [comment]
Couldn't reproduce this, the window stays open but the commands don't work, and they shouldn't, by looking at the code.
https://github.com/vgstation-coders/vgstation13/blob/d33de5cc19ec52fb20dc9cce4b7b99d689882ef7/code/game/machinery/computer/HolodeckControl.dm#L123
https://github.com/vgstation-coders/vgstation13/blob/d33de5cc19ec52fb20dc9cce4b7b99d689882ef7/code/game/machinery/machinery.dm#L366
