### ISSUE TITLE
Dying with a borer in you as a slime person

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#16993]
This just fucks all the shit up.
First the borer is dumped out of you, which was a wonderful way to get rid of my braindead borer.
Second it dropped a flesh-shot which I was able to pick up and used. Disappeared after I threw it?
Third it dropped the borer handler verb thingy with no item sprite. I've fucked around with it on the test server before but not when this happened and it gives you a borer tab when held pretty much.
Fourth I somehow dropped a health implant, which I didn't even know were in the game. I guess it's related to the borer being in me but I'm not 100% positive how that sucker got inside.

**Comment by Pathid** [comment]
Did you clone-scan yourself?

**Comment by Killette2** [comment]
Pardon?
Someone scanned me before I died but I don't see how that's relevant.

**Comment by Pathid** [comment]
That puts a health implant in you is all.

**Comment by Killette2** [comment]
Why? What happens if you remove it and get scanned again?

**Comment by Pathid** [comment]
It doesn't really do much. When you bring up somebody's record on the cloner console it will show you their damage types, right? Well that's data from the health implant. All removing it does is make that line give an error message.

**Comment by Hugh-G-Rection** [comment]
This sounds like all kinds of fun *features waiting to happen. I'm curious if you can get a permanent bone sword or shield this way. Can you use the borer tab while holding the handler? Injecting yourself with drugs, or climbing into someone else's ear?
