### ISSUE TITLE
Bhangmeter Discription Error

### ISSUE THREAD

**Issue by Rhimrifer** [d3athrow/vgstation13#17009]
#### Description of issue
There is a "by" where there should most likely be a "with".

#### Difference between expected and actual behavior
"Has been recently outfitted by meteor monitoring software by Space Weather Inc." versus
"Has been recently outfitted WITH meteor monitoring software by Space Weather Inc."

#### Steps to reproduce 
Have a Bhangmeter in existence and examine it. Tested on Bagel & Box.

#### Specific information for locating
That's a Bhangmeter
Ancient technology used to measure explosions of all shapes and sizes. Has been recently outfitted by meteor monitoring software by Space Weather Inc.

#### Length of time in which bug has been known to occur
Just discovered it, but I can't imagine it was modified recently.

#### Server revision
989342ef93079812703aeb660cd70269f8dbc42e

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Mothblocks** [comment]
just fix it

https://github.com/vgstation-coders/vgstation13/blob/63cd55a08dc586ef77704b4c1022d3f89d6679be/code/game/machinery/doppler_array.dm#L5
