### ISSUE TITLE
man bumps into wizard snakes, enters nullspace

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17013]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
989342ef93079812703aeb660cd70269f8dbc42e

# Description
someone bumped into a wiznerd snake and got null spaced, they ahelped @ 18:58:45 on 1/5/18 seemed to happen again after. amari evans
# Steps to Reproduce
bump into wizard sneks
# What you Expected
to stay in reality
# What Actually Happened
nullspace 2x

**Comment by jknpj** [comment]
#17012
