### ISSUE TITLE
booze dispenser dispenses water instead of ice

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#17029]
#### Description of issue
The booze dispenser spits out water, not ice.
It's got an [Ice] button. The button makes water appear in your container.
#### Difference between expected and actual behavior
Click ice button, recieve ice.
vs
Click ice button, recieve water.
#### Steps to reproduce 
Acquire a booze dispenser, place a container in it, hit ice button.
#### Specific information for locating
`/obj/machinery/chem_dispenser/booze_dispenser/`
https://github.com/vgstation-coders/vgstation13/blob/80937eeddc5b6fddfcff0e9d1592ef113e9c10da/code/modules/reagents/machinery/chem_dispenser.dm#L352
#16116
@MadmanMartian 
#### Length of time in which bug has been known to occur
since #16116 probably
#### Server revision
cfea3ae501ced31e1d8ab8556856afb3918f590a

**Comment by MadmanMartian** [comment]
*aflap

**Comment by FudgePucker** [comment]
Its a feature, the ice machine is broken.

**Comment by Intigracy** [comment]
straight iced this motherfucker
