### ISSUE TITLE
Can't remove lighter from the cigarette pack/cigarettes are invisible in the hand

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#17023]
#### Description of issue

The lighter is stuck in the cigarette pack

#### Steps to reproduce 

1. buy a cigarette pack and a lighter
2. take a cigarette out, it can't be seen in your hand
3. Put it in your mouth
4. Light it
5. Put lighter in cigarette pack
6. cry as you can never remove it again, even doubleclicking the cigarette pack just empties all the cigarettes but not the lighter

#### Length of time in which bug has been known to occur

Must have become broken kind of recently, i had successfully removed lighters from packs before

#### Server revision

cfea3ae501ced31e1d8ab8556856afb3918f590a

**Comment by Pathid** [comment]
Something to do with the type check in this?
https://github.com/vgstation-coders/vgstation13/blob/cfea3ae501ced31e1d8ab8556856afb3918f590a/code/game/objects/items/weapons/storage/fancy.dm#L305-L310

But then why did it break just recently? Maybe #16885 did it somehow?
