### ISSUE TITLE
Changelings can't absorb headless bodies, even if they haven't been succed yet.

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#17021]
#### Description of issue
If you accidentally cut someone's head off, you can't absorb their body.

#### Difference between expected and actual behavior
Expected: To be able to succ someone's body if I accidentally cut their head off
Actual: Couldn't succ them because they're 'not suitable'

#### Steps to reproduce 
Cut someone's head off in combat
Try to give them the succ
Dude's body is not suitable!

#### Specific information for locating

?? Changelings and suitable bodies

#### Length of time in which bug has been known to occur
No idea

#### Server revision
989342ef93079812703aeb660cd70269f8dbc42e 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
Unironically a feature.

**Comment by Cisrox** [comment]
but why

**Comment by jknpj** [comment]
#10375 Because we can't have nice things
