### ISSUE TITLE
Vamp jaunt doesn't cost blood.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17037]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
Its verb in the vamp tab shows that it should cost 30 useable blood, but useable blood doesn't change on activation.

**Comment by AI-Is-Rogue** [comment]
"Free, but requires 30 useable blood" From the wiki.
#7633 was supposed to make it cost 30 but it currently has no checks to remove the blood.

**Comment by Killette2** [comment]
Ah finally, vamp buffs.
