### ISSUE TITLE
Green Slime Extract doesn't spawn Mutation toxin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17034]
(WEB REPORT BY: zyrodil REMOTE: 172.93.109.202:7777)
# Revision
40962d22a5040090760baae3b2e3f5f2e20f7781

# Description
I injected Plasma into the Green Slime Extract and the Mutation Toxin didn't spawn.

# Steps to Reproduce
Farm slimes and get a green slime, kill it and extract it's Green Slime Extract.
Inject it with Plasma.
# What you Expected
I expected a Mutation Toxin after injecting the Green Slime Extract.

# What Actually Happened
The Green Slime Extract expired and nothing happened.

**Comment by DrSnips** [comment]
Not a bug. The mutation toxin is inside the core.

**Comment by Zyrodil** [comment]
Sorry! I thought it was like the Nutriment.
