### ISSUE TITLE
The *custom emote command requires you to do the entire process twice to work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17042]
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
# Revision
8fcf15421cacee89707ec090a03416293d0198a6

# Description
Using '*custom' to do a custom emote makes you input what you want to emote twice, and makes you choose whether it's visible or heard twice, before it finally does display what you've input.

# Steps to Reproduce
Try it.

# What you Expected
Not this.

# What Actually Happened
This.

**Comment by jknpj** [comment]
why would you ever use the *custom emote

**Comment by DamianX** [comment]
if it's terrible why not remove it?

**Comment by jknpj** [comment]
Good fucking question

**Comment by gbasood** [comment]
mimes

**Comment by JackMassacre** [comment]
*custom lets you specify if you want the emote to be only either visible or audible. It does have a use, it just incorrectly requires you to put everything in twice. It's a small bug that amounts to some extra inconvenience.
