### ISSUE TITLE
Large Crystal Artifacts Cannot be Dragged wi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17052]
(WEB REPORT BY: anglosphere REMOTE: 172.93.109.202:7777)
# Revision
4219ed0cec997006eb2b336227040bc179d186f0

# Description
If a large crystal artifact is ctrl+left clicked, it cannot be dragged. 

https://imgur.com/a/D8hoY

Applies to both Green and Red/pink ones.  Otheir large artifacts seem not to be affected. 
# Steps to Reproduce
Find large crystal artifact
Ctrl+click
Try dragging it

# What you Expected
Find large crystal artifact 
Ctrl+click to drag it back to the outpost for research

# What Actually Happened
The artifact could not be dragged.

**Comment by Anglosphere** [comment]
https://imgur.com/a/j84uy

Replicated the issue again.

Any large random artifact cannot be pulled. 

They can be pushed.  But thats it. This has happened on every large random artifact i've found. 

This makes it super tedious and sometimes even impossible to get them back to the lab.

**Comment by Fruktlimpa** [comment]
I'll chime in and say that I tested spawning in and dragging the green crystal to no avail. Pushing works, ctrl+click and then clicking on adjacent tiles work but dragging it doesn't work.

**Comment by Anglosphere** [comment]
I'm also going to add that you can't pull the TG borgs any longer either.

**Comment by jknpj** [comment]
Those shells aren't even large artifacts, they are rare small artifacts.
