### ISSUE TITLE
Non-smooth things that don't use smooth gliding

### ISSUE THREAD

**Issue by EdXbtkOEwGw** [d3athrow/vgstation13#17053]
Just so I remember these later.

Simple mobs
Things dragged in hookshots
Ventcrawling mobs should get a fitting glidesize
Singulo
Is this even doable with projectiles?

**Comment by DamianX** [comment]
pAI medbots weren't smooth, not sure if regular bots are affected too

**Comment by EdXbtkOEwGw** [comment]
I won't be online to try these for over a week so if anyone wants to take a stab at them be my guest
