### ISSUE TITLE
Emaggable Buttbots

### ISSUE THREAD

**Issue by Mothblocks** [d3athrow/vgstation13#17054]
[This is something I'm going to make when I get the chance, I'm still not in a position where I can work on SS13 code at the moment, on Guhnoo slash Linooks and I haven't tested Dream Maker yet.]

Buttbots are unique of the NPC bots in that emagging doesn't do anything for them. This is a travesty for such a classic bot, here were my ideas.

- Indestructible. Buttbots have the natural predator of pissed off security. This will protect them, filling the intercoms with butts for all (unless they throw the Buttbot into the singularity).
- Attempting to attack a Buttbot (including with a ranged weapon) will unleash a superfart, knocking back those in its range. 
- Buttbots will now have an in built radio, listening to ALL frequencies, and repeating butts back to them. Listen in as security goes insane with butts flooding their line!

Message example when emagging a butt bot: "You stick the card deep inside the cheeks of the Buttbot. Lord knows why."

**Comment by Mothblocks** [comment]
"WYCI"? @DamianX Excuse my ignorance, what does that label mean?
  
EDIT: I'm just going to take a guess, "Will you code it"? Is that what it is? If so, yeah.

**Comment by DamianX** [comment]
It means "When You Code It"
I will now unsubscribe from this as the only thing I can contribute is "REMOVE BUTTBOTS"

**Comment by DrSnips** [comment]
Just make them instantly explode on emag and maybe make it so it consumes the emag as well. Buttbots are already awful as is with just a SBR next to them. On top of being untrackable. The user should be punished for making these awful things.

**Comment by EdXbtkOEwGw** [comment]
Buttpointer when?

**Comment by jknpj** [comment]
Why would i take a butt pointner?

**Comment by Hugh-G-Rection** [comment]
Shut up and take my telecrystals

**Comment by Blithering** [comment]
How about having emagging activate subliminal mode, creating an area of effect that directly alters speech to add the butts, rather than just copying

**Comment by Mothblocks** [comment]
@Blithering The good ideas just keep flowing in.

**Comment by ghost** [comment]
Absolutely fucking not. There's 312500 tiles to choose your stack of cancer from as long as the maker isn't a retard. They aren't logged. They aren't tracked by any ic means. You can't mute SBR/intercomms. If everyone channel hops, so can he then just hang out making a full spectrum until the server crashes. Butts aren't hard to get. Arms aren't hard to get.  Everything else isn't hard to get. Admins refuse to do fucking shit about it and enablers cry that oh you can just kill the always non-antagonist doing it you don't know did it or find out from the always useless forensic scans on the buttbots you'll never find in 5 z-levels. The only thing that should be done with buttbots is a buttbot gps, as pinpointers need an overhaul to work with multiple targets and non-roundstart buttbots, or removal of buttbots entirely.
