### ISSUE TITLE
On boxstation, trader outpost still spawns asteroid rock and minerals inside of it near botanical research, deleting items and sizeable sections of the outpost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17059]
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
# Revision
23371fbb73b6e6d1f1e95b37700bbc923b997ddf

# Description
Trade outpost on boxstation sometimes starts with asteroid rock/mineral bits spawned inside of it, leading to item and station deletion and vacuum if mined away. I've seen this once before like a year ago.

# Steps to Reproduce
Seems to happen randomly on map generation.

# What you Expected
For asteroid rock not to start spawned inside the trader outpost.

# What Actually Happened
A terrible inconvenience.

**Comment by EdXbtkOEwGw** [comment]
https://github.com/vgstation-coders/vgstation13/issues/14843#issuecomment-301584957

**Comment by DamianX** [comment]
Duplicate.
