### ISSUE TITLE
Windows and unsecured pipes cannot be pulled/thrown

### ISSUE THREAD

**Issue by The-Whargoul** [d3athrow/vgstation13#17057]
Related to #17056 and #17052 
possibly related to #17044 
#### Description of issue
One direction windows, which normally are able to be pulled when unsecured, can no longer be pulled, however can be pushed. this is the same for unsecured piping sections, like a volume pump. It cannot be pulled, however, these items also cannot be thrown out of your tile. When thrown, the item lands at your feet on the same tile, and it hits your sprite. 
#### Steps to reproduce 
>Try to pull unsecured window
>Try to pull unsecured pipe section
>try to throw said pipe section.

**Comment by jknpj** [comment]
`##WARNING: Pulling disappeared! pulling =  old pulling =  in code/modules/mob/living/living.dm at line 701 src: Jonah Greene usr: Jonah Greene.`

Ruh oh

**Comment by jknpj** [comment]
@EdXbtkOEwGw Any ideas?
