### ISSUE TITLE
Changelings become unresponsive if put inside sleeper while in regen stasis

### ISSUE THREAD

**Issue by johnjohn** [d3athrow/vgstation13#1705]
Was playing earlier. Got blasted by a bomb as a changeling and went into regen stasis. An engineer ended up finding me and putting me in a sleeper on the escape shuttle. Attempted to wake from statis at least 4 times. Depleted chemicals as well. Was not able to wake up, even after someone removed me from the sleeper.

**Comment by d3athrow** [comment]
Appears to be that with 507.1281 clients will not update their verbs list if their loc is not a turf.
>closet
cryo
sleeper
mecha
this that and everything

**Comment by Cyadox** [comment]
Did this get fixed with the newer clients?

**Comment by PJB3005** [comment]
Nope

**Comment by Cyadox** [comment]
@PJB3005 if it's a client issue, is it something we CAN fix?

**Comment by PJB3005** [comment]
@Cyadox I think we can "fix" it, by reworking how lings get powers.

**Comment by clusterfack** [comment]
You can move it to some kind of verb holder. Like borers or preferrably spells.

Otherwise as it is it is completely unfixable without a byond fix.

**Comment by chatsonf** [comment]
It's been 3 versions (5.07 to 5.10), is this able to be fixed yet?

**Comment by clusterfack** [comment]
No, never

**Comment by 9600bauds** [comment]
Well, not the bug that causes this, but you can use a verb holder to make it just werk

I BELIEVE until this is fixed, you can get around this problem by closing the game and joining again to force your verbs to refresh

**Comment by clusterfack** [comment]
I guess it will be fixed when I convert all the verbs to spells then :^)

**Comment by 9600bauds** [comment]
Not even spells, just like do the thing borers do
