### ISSUE TITLE
Holy water does not increase plant water level or do anything for plants

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17066]
~~This goes deeper though. From what I can tell there's two entirely parallel systems for handling reagents put into plant trays.~~
EDIT: As it turns out code/game/machinery/hydroponics.dm is not included so that's egg on my face. Syringing holy water is just as useless.

https://github.com/vgstation-coders/vgstation13/blob/01b9e180f16529b1f075f56489eca99b51c92017/code/modules/hydroponics/hydroponics_reagents.dm#L42-L256

**Comment by Kurfursten** [comment]
That's some nice formatting. How'd you do that?

**Comment by Pathid** [comment]
Click first line number -> shift-click last line number -> go to the [...] button left of the first line and click copy permalink -> paste into comments.

**Comment by EdXbtkOEwGw** [comment]
The first file is not included.

**Comment by Pathid** [comment]
That makes sense.

**Comment by jknpj** [comment]
Well holy water isn't water, i don't know what else you expected. You can't even use it to slip people or hurt greys

**Comment by Pathid** [comment]
It _contains_ water and it calms bees. The Chaplain can convert entire tanks of one into the other. And if you make farmbots out of said watertanks then they're useless. I'm sure you could water plants with it at one time but the only evidence I have to show that is https://github.com/vgstation-coders/vgstation13/blob/1b73c89670116d2dc88311acdaf7bcce34a15187/code/game/machinery/hydroponics.dm#L610-L613, which I didn't realize was unused when I made this.

**Comment by jknpj** [comment]
I'm not saying this isn't a bug, i'm just saying this is expected to happen to snowflake chems.
