### ISSUE TITLE
How to fire immovable monoliths without admin intervention

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17072]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
d3c409a434f26593c9dd454021313f0fd232968c

# Description
Roulette revolvers are semi-common in xenoarchaeology and have no restrictions on rods of any kind

# Steps to Reproduce
find a roulette revolver in a war site and fire until it shoots a rod
# What you Expected
The occasional meteor or pulse laser
# What Actually Happened
HOTRODS

**Comment by Pathid** [comment]
That's not necessarily a bug, but the meteors probably are. The base meteor type is in the revolver's blacklist. But we'd have to ask @Shadowmech88

**Comment by jknpj** [comment]
Should roulette revolvers be less common? I agree that they are too strong to be a common item.

**Comment by Blithering** [comment]
Perhaps add a version with a more restrictive blacklist as a common one and keep the current version as a super rare find

**Comment by DeityLink** [comment]
wait it can spawn any kind of meteor? that's huge, that means it could even spawn blobs then!
