### ISSUE TITLE
malf autoborger not spawning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17071]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
01b9e180f16529b1f075f56489eca99b51c92017

# Description
im not exactly sure but i've gotten two ahelps now about an ai NOT being able to spawn an autoborger. so heres a bug report
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment]
#16856 did this
