### ISSUE TITLE
Feature Request: Movie Projector to Library

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#17082]
After fiddling with nanopaper and uploading some movies/shows in the library database i think it would be a great idea if we could upload movies/shows into laser discs (the most advanced kind of storage media) and play them on some sort of projector in library to everyone watch it.
it would be great for movie nights and to get comfy, imagine watching The Thing while a changeling succs peoples in the cinema, very immersive.

**Comment by Anglosphere** [comment]
How will the MPAA feel about this?

**Comment by Mothblocks** [comment]
maybe in addition (or just as an easier alternative), you could put in a slideshow of the photos from the camera

**Comment by DeityLink** [comment]
Is it possible for BYOND to read the color of a pixel at a specific point of a video?

**Comment by Exxion** [comment]
Probably not, but even if it could, doing it would be mindbogglingly laggy
This could be done by opening the video in a separate window, but there's no reasonable way to show the video on a screen in the map
