### ISSUE TITLE
Being inside a disposals pipe when said pipe is destroyed nullspaces you

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17087]
#### Steps to reproduce 
- Be fat
- Get stuck inside a pipe
- Have a mech drill said pipe
- Die in the void

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/8739cedae764f48e2697a73947ba5672c9a83b03/code/modules/recycling/disposal.dm#L547

#### Length of time in which bug has been known to occur
Forever?

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by gbasood** [comment]
isnt this more of mech drilling being dumb

**Comment by DamianX** [comment]
I dunno, I suppose this also happens if you deconstruct the pipe normally but I didn't check or test it

**Comment by Dacendeth** [comment]
I've taken apart a pipe with tools to get people out before and nothing bad happened.

**Comment by gbasood** [comment]
IIRC, mech drilling destroys things in a different way than usual, which has resulted in similar bugs before
