### ISSUE TITLE
APCs bugging out as "fully charged"

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17081]
Noticed this in a couple shifts recently.

Case 1
>Got a report about an abnormal APC that was tampered by a gremlin. Investigated to find it fully charged but switches for equipment and lighting kept automatically switching to "OFF". Not just auto, but even manually clicking ON would set them to OFF. Removing cell didn't remedy, checking power and cable nothing was wrong. Had to deconstruct and rebuild APC. The buggy APC was "fully charged".

Case 2
>Reported abnormal power issues at outpost. Investigated to find EMP artifact had knocked out all power in all rooms. Power still being supplied by SMES on outpost but no room charging. APCs were "Fully charged" in spite of having 0 charge (empty bar). Removing and reinserting cell fixed problem, resumed charging.

Probably entirely two different bugs. Might need to split this issue.

**Comment by Pathid** [comment]
Case 1 sounds like a cut wire in the APC, not a bug.
