### ISSUE TITLE
Borg upgrades are locked behind ANOMALY RESEARCH??

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#17107]
Why would you do this? What the fuck do anomalies have to do with upgrading borgs? Why does anomaly research even exist?

Please replace it with something reasonable that people will actually be able to get. This is plastic all over again.

**Comment by jknpj** [comment]
Upgrades that also upgrade grippers need Anomaly 2. I shouldn't be a problem if miners bring back to R&D a single trash item(fork-shaped spoons, strange items).

**Comment by Hoshi-chan** [comment]
We had a whole argument about this in discord that should've taken place here.

**Comment by jknpj** [comment]
Discord was a mistake

**Comment by gbasood** [comment]
alternatively just recap the discussion from discord here

**Comment by Killette2** [comment]
Cyborgs with grippers sound pretty strange to me, just toss a fossil in the DA and you'll learn all about it.
