### ISSUE TITLE
Cyborg deathgasp doesn't seem to trigger on death

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17104]
#### Description of issue

Noticed this a few times, haven't thoroughly tested it but, this message here:
https://github.com/vgstation-coders/vgstation13/blob/a31beb5dce01b328c8e86420c98879df2b22923b/code/modules/mob/living/silicon/robot/emote.dm#L90-L92

doesn't seem to trigger properly on death, even though it seems like it should.

https://github.com/vgstation-coders/vgstation13/blob/23371fbb73b6e6d1f1e95b37700bbc923b997ddf/code/modules/mob/living/silicon/robot/death.dm#L36-L43

**Comment by DamianX** [comment]
is this unrelated to the fact that sometimes cyborgs don't properly die due to components/health shenanigans?

**Comment by jknpj** [comment]
Add this to the fact that on emp_act posibrains emote *ping* on nullspace.
