### ISSUE TITLE
GHOSTS CAN TAP ON WALL AQUARIUMS

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17123]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
c260ac9f653fd3cbd418d08d88a9fd99c8709513

# Description
AHHHHHHHHHHHHHHHHHHHHHHHHHH
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment]
FEATURE
