### ISSUE TITLE
Mol counts in tanks are waaaaay off. ZAS

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#17141]
#### Description of issue
Went to make some canister bombs for old times sake after not making any in ages, used the old standard mix and it was a dud despite hundreds of prior uses. Looked into it the round after and noticed the numbers were insane compared to what they used to be.

*Scanned with the Atmos tech pda cart's gas scanner*

Cause old tanks would be,   
Results of the plasma tank scan: 
Pressure: 56.3 kPa 
Oxygen: 52 mol, 76% 
Plasma: 15.5 mol, 23% 
Temperature: -267°C. 

Are now:  
Results of the oxygen tank scan: 
Pressure: 48 kPa 
Oxygen: 1734.5 mol, 77% 
Plasma: 518.1 mol, 22% 
Temperature: -267°C 
Heat capacity: 3872.77

Just trying to match the old mol counts created bizarre numbers with the new system despite the expected curve as you approach 0 kelvin.
 Results of the plasma tank scan:
 Pressure: 1 kPa
 Oxygen: 36.1 mol, 76%
 Plasma: 10.8 mol, 23%
 Temperature: -267°C
Heat capacity: 80.65

 Results of the oxygen tank scan:
 Pressure: 2 kPa
 Oxygen: 53.3 mol, 77%
 Plasma: 15.9 mol, 22%
 Temperature: -265°C
Heat capacity: 119.06

#### Steps to reproduce 

I'm not a numbers guy so all this junk flies over my head. Here's a fat block of tank values from may 2016ish and were still valid in august 2017. You can try to match these values in a current round and see how off stuff is.

==================
X

 Results of the plasma tank scan:
 Pressure: 52 kPa
 Oxygen: 35.2 mol, 67%
 Plasma: 17.3 mol, 32%
 Temperature: -265°C
===============================
X

 Results of the plasma tank scan:
 Pressure: 48.3 kPa
 Oxygen: 35.5 mol, 66%
 Plasma: 17.5 mol, 33%
 Temperature: -266°C

======================
x

 Results of the plasma tank scan:
 Pressure: 38.1 kPa
 Oxygen: 24.8 mol, 57%
 Plasma: 18.7 mol, 42%
 Temperature: -266°C

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 27 kPa
 Oxygen: 10.5 mol, 34%
 Plasma: 20.3 mol, 65%
 Temperature: -266°C

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 27 kPa
 Oxygen: 10.5 mol, 34%
 Plasma: 20.3 mol, 65%
 Temperature: -266°C

==============================
X

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 56.3 kPa
 Oxygen: 52 mol, 76%
 Plasma: 15.5 mol, 23%
 Temperature: -267°C

==========================================
X

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 54.3 kPa
 Oxygen: 54.9 mol, 84%
 Plasma: 10.2 mol, 15%
 Temperature: -267°C

=========================
You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 56.3 kPa
 Oxygen: 52 mol, 76%
 Plasma: 15.5 mol, 23%
 Temperature: -267°C

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 560.3 kPa
 Oxygen: 52 mol, 76%
 Plasma: 15.5 mol, 23%
 Temperature: -204°C

 Results of the plasma tank scan:
 Pressure: 2010.3 kPa
 Oxygen: 52 mol, 76%
 Plasma: 15.9 mol, 23%
 Temperature: -25°C

==================================================================
X

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 350.3 kPa
 Oxygen: 32.5 mol, 76%
 Plasma: 9.7 mol, 23%
 Temperature: -204°C

===========================================================
X

 Results of the plasma tank scan:
 Pressure: 49 kPa
 Oxygen: 43 mol, 72%
 Plasma: 16.7 mol, 27%
 Temperature: -267°C

=================================
X
 Results of the plasma tank scan:
 Pressure: 50 kPa
 Oxygen: 48.2 mol, 79%
 Plasma: 12 mol, 20%
 Temperature: -267°C

=-====================
X
 Results of the plasma tank scan:
 Pressure: 55 kPa
 Oxygen: 53 mol, 80%
 Plasma: 13.2 mol, 19%
 Temperature: -267°C

==========================

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 65 kPa
 Oxygen: 62.6 mol, 79%
 Plasma: 15.7 mol, 20%
 Temperature: -267°C

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 2515.8 kPa
 Oxygen: 47 mol, 79%
 Plasma: 12.4 mol, 20%
 Temperature: 83°C

================================================
X
 Results of the plasma tank scan:
 Pressure: 62 kPa
 Oxygen: 59.7 mol, 80%
 Plasma: 14.9 mol, 19%
 Temperature: -267°C

=================================
X
 Results of the plasma tank scan:
 Pressure: 82.2 kPa
 Oxygen: 84.5 mol, 87%
 Plasma: 11.9 mol, 12%
 Temperature: -266°C

============================================================
X

 Results of the plasma tank scan:
 Pressure: 25.8 kPa
 Oxygen: 12.3 mol, 42%
 Plasma: 16.9 mol, 57%
 Temperature: -266°C

====================================================
X

You use the atmospheric analyzer on  the plasma tank

 Results of the plasma tank scan:
 Pressure: 41.5 kPa
 Oxygen: 29.1 mol, 61%
 Plasma: 18.2 mol, 38%
 Temperature: -266°C

=============================================
X

 Results of the plasma tank scan:
 Pressure: 51 kPa
 Oxygen: 41.2 mol, 70%
 Plasma: 17.1 mol, 29%
 Temperature: -266°C

=====================================
X
 Results of the plasma tank scan:
 Pressure: 62.3 kPa
 Oxygen: 60.6 mol, 84%
 Plasma: 11.4 mol, 15%
 Temperature: -266°C

===========================================

#### Specific information for locating

More ZAS updating #15922 ? @Exxion , This is all ideal gas law stuff so is there a hangup in one of the fomula's in gas_mixture?
https://github.com/vgstation-coders/vgstation13/pull/15922

#### Length of time in which bug has been known to occur

Some time post-august 2017.
January 19th, 2018

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Odd. I know I forgot to fix ghosts scanning areas, but I could have *sworn* I got tanks.
Not that it's particularly hard to fix. I've just been busy for a while. I'll handle it soon:tm:

**Comment by ghost** [comment]
Thanks a million man.

**Comment by Exxion** [comment]
I finally got a chance to look at this. Very sorry for the delay.
1. It's just a display error, so don't worry about it fucking up how things work (or rather don't worry about fixing it fucking things up). Specifically, all mol counts in (standard-sized) tanks appear exactly 250/7 times higher than they should be. (All other numbers are correct.) The same problem exists with canisters as well (but with a different multiplier), since the gas analyzer is actually the problem here.
2. Turns out this was caused by fixing scanning rooms. Without making the analyzer even fuckier than it already is, fixing this will "break" that again. (It will get the correct values per liter rather than per tile.)

I'll probably not bother making the analyzer no more fucky and just fix both
I should get to it tomorrow.

**Comment by Exxion** [comment]
To update: I decided it would be better to just fix everything like this once and for all, so I've been going through every occurrence of `return_air()` in the codebase and fixing where necessary. There are a lot of them, so it's going to take a few days.
