### ISSUE TITLE
Antagonist shuttle destinations are hard-mapped

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#17152]
#### Description of issue
The locations at which antag shuttles dock (in proximity to the station) are hard-mapped, this means you can predict where they will dock, and wait/attack there.

#### Difference between expected and actual behavior
expected - Nuke op shuttle comes into rough proximity of the station to do its thing

actual - Nuke op shuttle docks at one of four locations in proximity to the station, reducing the search radius that the crew may have to look to one of four locations rather than ALL OF SPACE.

#### Recommended remedy
Have the shuttle be 'drivable' so you can move it around in-game

Or, randomize where the shuttle locations can be within a certain space, akin to the vault generation.

**Comment by small-boss** [comment]
this would be a nice thing to have, but i dont think byond can pull it off.
maybe allow the ops to make their own shuttle docking point by entering the coordinates they want to dock at?

**Comment by Aurx** [comment]
Making the shuttle 'drivable' is technically possible but impractically laggy.  

Dial-a-coord and random docking points should be easily possible though.

**Comment by CptWad** [comment]
\>dial a coord
;HELP SYNDICATE SHIP IN CAPTAINS OFFICE

**Comment by Kurfursten** [comment]
It is possible to mathematically generate a location. For example, have a 'center of station' marker, and you can move your ship to any position 100 tiles away from that marker, you choose the degrees. So, 90 would put you on the west side and 270 on the east. Shuttles already have a 'safe' checker to make sure they don't destroy anything they move to.

Downside: powergaymin engiborgs could go around the station building walls to limit the range of where the shuttle can be parked.

**Comment by gbasood** [comment]
powergaymin engiborgs could also currently just go sit somewhere in space and wait for a shuttle if they thought that'd help

**Comment by DeityLink** [comment]
Antag shuttles used to be much much closer from the station, so close that you could see them from window or while setting up solars. Now they're a full screen away, which means you won't find them accidentally.

If people can bother learning by heart where they can dock on the various map you can be sure those same people will find the shuttle just as quickly by adding a random. Even then, they'll only search if someone found nuke ops and called it over the comms.

A scrapped idea was to have the ship's console display an holominimap that you could then click to select a docking port. But that meant more screen elements fuckery and I was tired of it.

**Comment by iFlashYou** [comment]
How about adding laser turrets, around the ship, that shoot non ops?

**Comment by SGuivenne** [comment]
How about we ban metagamers who repeatedly check these spots

**Comment by AI-Is-Rogue** [comment]
It's already punishable if I remember correctly.

**Comment by DeityLink** [comment]
It is.

You cannot prevent every player wrongdoings with code alone. That's why admins are there (among other reasons).
