### ISSUE TITLE
Noir gene renders security airlocks (and maybe other things) invisible

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#17150]
Just join a round as a gumshoe. Security airlocks, including your office door, are invisible. It's incredibly disorienting.

EDIT: Actually, I don't know how the fuck to reproduce this. Trying it on the test serb right now and all the airlocks are visible this time.

**Comment by DamianX** [comment]
Could have been a BYOND bug.

**Comment by gbasood** [comment]
Sounds like BYOND bug to me
