### ISSUE TITLE
Packed Mining Dock uvent 1 faces the wrong way

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#17185]
#### Description of issue
![image](https://user-images.githubusercontent.com/5942183/35218704-e4ae37b4-ff6f-11e7-8247-d35615af6cd0.png)

#### Difference between expected and actual behavior
Expected to ventcrawl into mining office, instead got placed inside window

#### Steps to reproduce 
- Start packed
- Go to mining dock
- Crowbar up the floor on the vent
- Optionally: Turn off vent and wrench it out to see direction more clearly

#### Server revision

27f69d0d9abafd4cb286069626bda7c3206d29f5 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
https://github.com/vgstation-coders/vgstation13/pull/17712
