### ISSUE TITLE
More Reasonable Radiation

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17191]
Ever since the radiation rework, rads have really, really strong. I've felt this for a long time but I didn't want to knee-jerk, I wanted to give it plenty of time for people to experience and see how they felt about it. I finally felt encouraged to have a community dialog about this when recently people in the thread believed the CE hardsuit (on two separate occasions this week) has no radiation protection at all. Last night, I witnessed the head of security fly by the singularity for mere seconds and get completely annihilated with five internal bleeds. It's really bad. In fact, "Five internal bleeds" is kind of the norm: most doctors know if someone has to come to medbay for rad treatment, usually they're clone fodder because it would require way too many surgeries.

I'm not saying we need to make radiation trivial. In the past radiation damage was low to moderate if you were suited up but the danger was you might get hit with a random dice roll that makes you pass out and die for sure. I think we can dial back radiation damage without making it so diluted as to encourage people to fuck around next to it in atmos suits.

I'd encourage people to get out a branch and do their own testing, and possibly we could even have a server vote.

**Comment by CptWad** [comment]
It really should be a tad of both, but based more on how LONG your exposure is. small bursts of radiation should be curable but if you stand near something too radioactive for long enough you should die internally

**Comment by Cisrox** [comment]
i feel like the CE hardsuit, the highest end engineering hardsuit should have 100% rad resistance, considering that the xenoarch space suits do

**Comment by Exxion** [comment]
Discussion dead, reopen to continue, etc.
