### ISSUE TITLE
Voice Changer Stops Working After Reconnecting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17192]
(WEB REPORT BY: laserdog REMOTE: 172.93.109.202:7777)
# Revision
818d0a2f993201fc5e7e4f45ea20605bd0fbb68f

# Description
My syndicate voice changer refused to work after i reconnected to the server becuase i had 1000 ping. lost me the round

# Steps to Reproduce
Use voice changer and agent id. leave and reconnect

# What you Expected
The Voice changer was supposed to make it look like i was pickle rick

# What Actually Happened
it said my real name instead of pickle rick and i lost the round

**Comment by SonixApache** [comment]
>i lost the round

**Comment by Blithering** [comment]
Did you try turning it off and on again?

**Comment by nervere** [comment]
Can't replicate.
