### ISSUE TITLE
Emagging an airlock does not leave prints or fibers.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#17203]
#### Description of issue
Emagging an airlock does not leave prints or fibers

#### Difference between expected and actual behavior
It totally should leave fibers, it's silly that you can emag every single external airlock and get away with it unless witnessed. 
You'd be touching the emag and giving it your prints or fibers which then touches the airlock rubbing off your prints or fibers, but in reality the airlock gets nothing and detective is just sad.

#### Steps to reproduce 
Buy emag
hit door

#### Length of time in which bug has been known to occur
Probably for all time

**Comment by Kurfursten** [comment]
Nor does a locker or windoor.

A few nights ago, the trader (I assume, I never proved it) during deadpop emagged on Box...
>Both external airlocks to port fore maint
>The two more airlocks from there into sec medbay
>The windoor out of sec medbay
>The airlock to interrogation
>From there, the next airlock into evidence, and yet another from evidence into the armory
>Still another airlock into the secure armory
>Four more windoors inside the armory
>The secure locker at the back of the armory

That's 8 airlocks, 5 windoors, and a locker!

I scanned everything and got nothing.

**Comment by beesil** [comment]
Fixed by #23075
