### ISSUE TITLE
Drag damage gibs hands

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17207]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
8e77c929d97e20342060297c3b3091d85219f4c7

# Description
as title

# Steps to Reproduce
drag someone and their hands explode
# What you Expected
this might be intended i dunno

**Comment by SonixApache** [comment]
Not intended. Don't remember this happening in my testing.

**Comment by DamianX** [comment]
This means drag damage does 16+ damage at a time.

**Comment by SonixApache** [comment]
Normal drag damage does 2 brute damage, extra drag damage does 4. Max is limited to the max of the limb. Not sure what's going on.

**Comment by Allspice** [comment]
bone breaking miiiight do some damage in itself

**Comment by SonixApache** [comment]
Could not reproduce in testing.
Made a guy's hands bleed, then dragged him around. Limbs took maximum damage, then stopped taking drag damage. The next hit made the limbs pop off, but didn't cause gibbing.
Tested on 8100d4a920ce81b9b50e0620915cfc7be941f09a 

Not a lot of useful info to go on in this report, but I think this is referring to that round on packed this morning, where it actually happened to me. I think the thing was that I took explosion damage that damaged my hand, then got dragged while in crit, and *then* the broken hand kicked in causing the damage to go over the limit.

**Comment by Dacendeth** [comment]
Are you sure it wasn't someones robotic hand? They gib at max damage.

**Comment by Kurfursten** [comment]
Saw a man's legs get gibbed off by dragging today, also on Packed, also took explosion damage.

**Comment by SonixApache** [comment]
[needs moar testing] I guess. I'll mess around some time soon, try to reproduce it.

**Comment by ShiftyRail** [comment]
We dragged away drag damage
