### ISSUE TITLE
Vermin event fires but spawns no mobs

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17219]
Splitting https://github.com/vgstation-coders/vgstation13/pull/17183#issuecomment-359620278

> the kitchen is zoned as part of the bar, so there's no defined kitchen. So the vermin event for the kitchen (maybe the incinerator too, I don't see one) still fires and gives the message, but it can't find anywhere to spawn the mobs.
> https://github.com/vgstation-coders/vgstation13/blob/949c674551ba85719a6e1019203ad9dbf6c68d04/code/modules/events/infestation.dm#L14
> There's probably a way to fix it without affecting the actual map areas though.

**Comment by DeityLink** [comment]
yeah you could count the number of turfs in the target area. If it's too low, remove the area from the list and try picking again, until the list is empty and the event fails.
