### ISSUE TITLE
Issues with Buttbots

### ISSUE THREAD

**Issue by Mothblocks** [d3athrow/vgstation13#17221]
#### Description of issue
Buttbots no longer do their usual behavior of parroting and replacing the text with "butt". Instead, they only say "butt" and fart (like when they're clicked).

Buttbots also can be spam clicked on to flood the chat (not radio). As funny as this is, it's unintentional and is due to a lack of sincelastfart check on attack_hand.

#### Difference between expected and actual behavior

Expected behavior: Buttbots should parrot what the user says and repeat it with "butt" replaced. Then fart. They should also have a cooldown on clicks.

Actual behavior: Buttbots don't parrot and instead just say "butt" and fart when they hear something. They do not have a cooldown on clicks.

#### Steps to reproduce 
Talk to a Buttbot. Spam click on a Buttbot.

#### Specific information for locating

code/game/machinery/bots/buttbot.dm

/obj/machinery/bot/buttbot

#### Length of time in which bug has been known to occur

I don't know. Seems to be since #17116.

#### Server revision

Only tested on local, not an actual server.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

I need someone else to test this in a current round while I try and fix this, thanks. butt

**Comment by gbasood** [comment]
Alright, well, part of hte problem was:
```dm
/obj/machinery/bot/buttbot/proc/fart()
	if(sincelastfart + 5 < world.timeofday)
		speak("butt")
		playsound(get_turf(src), 'sound/misc/fart.ogg', 50, 1)
		sincelastfart = world.timeofday
```
This speak call is in the wrong place. Should be under attack_hand. Easy enough to fix.
As to why they aren't picking up the radio chatter, I'm still not sure

**Comment by Mothblocks** [comment]
I never said anything about them not picking up radio chatter, is that a bug I missed?

**Comment by gbasood** [comment]
Probably?
If they're not saying anything other than but, then almost certainly.
Anyways I'm testing a fix now

**Comment by gbasood** [comment]
![image](https://user-images.githubusercontent.com/2076607/35365376-1d8a204c-0129-11e8-9a82-c289b89b05c3.png)
Alright, looks good.
