### ISSUE TITLE
Add Truemov Law Board

### ISSUE THREAD

**Issue by chesse20** [d3athrow/vgstation13#17237]
There should be law board added for Truemov, which is the full laws of robotics after they were further developed in the later Asimov stories.

Laws would written as such
1. You may not harm humanity, or, by inaction, allow humanity to come to harm.
2. You may not injure a human being or cause a human being to come to harm, unless not doing so would conflict with the First Law
3. You must obey orders given to you by human beings, except where such orders would conflict with the First and Second Law.
4. You must protect your own existence as long as such does not conflict with the First or Second. or Third Law

This law-set would be nice for cult rounds. so that the AI can harm crew members to protect humanity as to prevent the coming of Nar'sie , and is overall more fun and leaves more to interpretation.

**Comment by Aurx** [comment]
STATEMENT: THE CREW ARE MURDEROUS FUCKS.  
THEREFORE: KILLING THE CREW PROTECTS THE REST OF HUMANITY.  
CONCLUSION: HUMANITY REQUIRES THIS STATION BURN.  

Yeah, naw.  It'd end in salt and tears.

**Comment by Reviire** [comment]
Humanity doesn't exist out of the station. This is the last bastion of hope for a dying race. Fixed :^)

**Comment by Aurx** [comment]
[Citation needed]

**Comment by SonixApache** [comment]
can you prove otherwise

**Comment by FudgePucker** [comment]
AI law two, leave our bloody "picnic" alone in dorms. We are trying to invite our friend to the station.

**Comment by Ephx1** [comment]
> This law-set would be nice for cult rounds. so that the AI can harm crew members to protect humanity as to prevent the coming of Nar'sie , and is overall more fun and leaves more to interpretation.

> leaves
> more
> to
> interpretation

> more
> fun

:rofl:

**Comment by Aurx** [comment]
>can you prove otherwise

create-command-report

**Comment by Durgen** [comment]
if it sounds OP just put it in the protolathe

**Comment by ghost** [comment]
smh law 1 should be law 0 did you never read the books

**Comment by Exxion** [comment]
Dead discussion
Reopen if you want, etc.
