### ISSUE TITLE
Can't squirt chems into people's eyes using droppers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17235]
(WEB REPORT BY: agentofzog REMOTE: 172.93.109.202:7777)
# Revision
5e45c8d3fe2175a90ee9bb025d65536840c92ad8

# Description
Whenever you try to squirt somene with a  dropper it says "You can't, Dropper is closed." and fails to transfer any chems, even though you used to be able to do it on anyone without eye protection. If there is a way to open the dropper I have not found it.

# Steps to Reproduce
check that your target didn't grab glasses
fill dropper with chloral alternative of choise
attempt to squirt
try to play it off as they call sec

# What you Expected
trickdrop my target with the stun juice

# What Actually Happened
only make them know I'm trying to molest them

**Comment by DamianX** [comment]
#16855 maybe

**Comment by Pathid** [comment]
In testing, the "You can't, Dropper is closed." message would display even on successful transfer of reagents. While this part is an oversight, I think maybe you got caught out by #17091.

**Comment by ShiftyRail** [comment]
Was fixed.
