### ISSUE TITLE
Machinery often appearing above ejected items

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#17239]
Not sure when this started happening, maybe about a week and a half ago? Things like the chem-master and xenobotany machines will now eject their items below the actual machines, so you have to right+click or alt+click on the tile to actually get what you wanted.

I think this problem has shown up before, can't remember quite what the reason was but it'd be cool to have fixed at some point.

**Comment by DamianX** [comment]
Are you using byond 511?

**Comment by kilozombie** [comment]
...Aw cripes no, I swapped off to play the WW2 server.
Sorry, this is my mistake.

**Comment by DamianX** [comment]
I mean, it's still a bug that we'll have to figure out.

**Comment by kilozombie** [comment]
BYOND, the whole big thing in of itself, is a bug. A big ol' glitch in the universe.
