### ISSUE TITLE
Display Case Frame Attackby Not Responsive

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17244]
Ran into this on Packed with @unid15 

A display case frame (added glass) would not accept an airlock circuitboard. After he forced it in, it wouldn't be screwdrivered finished. Something preempting its attackby maybe?

**Comment by Blithering** [comment]
I had the same problem, can't make display cases right now

**Comment by DamianX** [comment]
@ShiftyRail last touched construction frames

**Comment by Kurfursten** [comment]
I don't think this is Shifty's fault based on his diff

I did some testing on this and displaycase_frame attackby is not getting called at all. I changed the *first line* of its attackby to show a visible message and got no results, even when forcing attackby as an atom proccall. It's like something is preempting it entirely.

**Comment by ihadtoregisterforthis** [comment]
Fixed?

**Comment by Probe1** [comment]
@imw-Oculus make sure to write Fixes then paste a link to the issue so they autoclose in your PRs please.


Thanks @ihadtoregisterforthis
