### ISSUE TITLE
RPDs cannot be handed to other people

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17247]
Encountered this with @DrCelt on Packed

Probably because they use Preattack or something

**Comment by ghost** [comment]
Related: they also override alt-click on tiles and ctrl-click on dragging things

**Comment by DamianX** [comment]
It's a feature https://github.com/vgstation-coders/vgstation13/blob/27e2505dbf53b9ee3588daa99dd11829bef7725f/code/modules/RCD/RPD.dm#L91

**Comment by ghost** [comment]
ew

**Comment by Exxion** [comment]
For what reason?

**Comment by PJB3005** [comment]
https://github.com/vgstation-coders/vgstation13/blob/27e2505dbf53b9ee3588daa99dd11829bef7725f/code/modules/RCD/RPD.dm#L88-L96

Literally commented above that override WHY this is this way.

In testing of RPD scrolling, I was constantly examining and alt clicking floors. I think this is a nice tradeoff.
