### ISSUE TITLE
Vampire Verbs Went Poof

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17254]
(WEB REPORT BY: joyeuxchat96 REMOTE: 172.93.109.202:7777)
# Revision
e1e5b9c7f41f3ad72095fe752582c5d4c497367b

# Description
Was downed on the asteroid as a vampire, after glaring I was tasted. I used hypnotize, it failed and my Vampire verb tab left and never came back.

# Steps to Reproduce

# What you Expected
Verbs
# What Actually Happened
No Verbs

**Comment by RealestEstate** [comment]
similiar thing happened to me when I exhausted all my vampire verbs (glare, hypno, rejuv). the tab went away since there are no verbs to pick from, but the tab came back when the verbs reset from their cooldown. are you sure that this isn't what happened?

**Comment by ShiftyRail** [comment]
@Exxion vamps no longer have verbs.
