### ISSUE TITLE
"The Human Harvest - From seed to market" is a blank book

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#17256]
Isn't there a wiki article we could link it to? Could anyone write one? Shoulldn't it be renamed since you're no longer harvesting humans but dionae?

**Comment by Zth--** [comment]
Remove this book entirely. This haven't been a thing since... 2014?

**Comment by Probe1** [comment]
Its for pod people so yeah remove.

**Comment by DeityLink** [comment]
It's been rewritten at some point with fluff about growing diona, no longer blank.
