### ISSUE TITLE
Bees out of nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17250]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
e1e5b9c7f41f3ad72095fe752582c5d4c497367b

# Description
Placing an apiary seems to cause bees to just jump into existance if there are chillbugs nearby
# Steps to Reproduce
plant chill bugs and place apiaries nearby
# What you Expected
empty apiaries
# What Actually Happened
dead bees all over the floor

**Comment by DeityLink** [comment]
I think queen bees don't properly import their species when they migrate. Will fix that.
