### ISSUE TITLE
Liquid plasma hurts plasmaman if you drink it

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#17270]
#### Difference between expected and actual behavior
I expected to be able to drink it since i breathe it, but it hurt.

#### Steps to reproduce 
Drink that plasma, die slowly.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
Imagine drinking liquid oxygen IRL

😱

**Comment by SonixApache** [comment]
imagine being a monstrosity infused with oxygen IRL

😱

**Comment by ghost** [comment]
Oxymen when

**Comment by Exxion** [comment]
Liquid oxygen is very cold, whereas liquid plasma isn't
It probably should be but absolutely nothing about phases of matter in this game makes sense
