### ISSUE TITLE
Bagel has no chill

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17273]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
4c24df99fcb7ee75e56bf7f42239203c3225860f

# Description
Bagel doesn't have any chillbug packets
# Steps to Reproduce
Load up bagel and look around the trader outpost
# What you Expected
Chillbug packets
# What Actually Happened
No packets

**Comment by Kurfursten** [comment]
It appears #17182 did not edit Bagel

**Comment by Aurx** [comment]
Bagel confirmed for totally unchill, maaaaan.

**Comment by DeityLink** [comment]
Oh we have more maps now?
In the meantime, feel free to request admins for a packet or two.

**Comment by ghost** [comment]
@DeityLink 

Boxstation
Metastation
Defficiency
Bagelstation
Packedstation

**Comment by FudgePucker** [comment]
>coders haven't been on the server so long that they don't know the map rotation.

**Comment by FudgePucker** [comment]
Jk love you Deity, I respect and appreciate what you do for the server

**Comment by DeityLink** [comment]
Wasn't that a meme? I barely remember.
