### ISSUE TITLE
Speaking into a headset's default channel speaks out loud

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17288]
#### Description of issue
Speaking into a headset using ";" now speaks out loud rather than whispering.

#### Steps to reproduce 
- be nuke op
- say ";I see the captain"

#### Expected behavior
Only nuke ops to hear what you're saying

#### Actual behavior
Everyone in your view hears what you just said

#### Specific information for locating
I guess #17146 did this
#17198 is related

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
I'm working on a fix for this and #17198
