### ISSUE TITLE
Clipboard Icon and Object Type Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17294]
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
# Revision
20ae6f13e62ce4dcd3598c797b6c5d89b5caddef

# Description

The clipboard's icon seems to update to display the latest object you've just taken out of it. It should probably be displaying the next object on its icon, instead of the one that it now no longer contains.

Also, folded paper other than envelopes cannot be put into clipboards. This seems to be an oversight or some other kind of mistake. Folded paper is smaller than the paper it was made of, after all, and it's still paper. Presumably.

**Comment by Kurfursten** [comment]
This is also fixed in #17293 

Except for folded paper but it has never been allowed on clipboard as it is not a subtype (envelopes are allowed)

**Comment by Kurfursten** [comment]
@PJB3005 my bad, closed by #17293
