### ISSUE TITLE
Plasmamen violate the laws of physics and retain body heat forever

### ISSUE THREAD

**Issue by bathosbathtime** [d3athrow/vgstation13#17307]
#### Description of issue
Plasmamen no longer have Celt's thermal regulation

#### Difference between expected and actual behavior
Expected: Plasmamen don't stay hot forever after putting out a fire with their suit

Actual: Plasmamen stay warm forever, possibly presenting themselves as a source of fuel
#### Steps to reproduce 
1.Take off suit
2.Catch fire
3.Put suit back on
#### Specific information for locating

vgstation13/code/modules/mob/living/carbon/human/plasmaman/species.dm
Thermal regulation introduced in:
https://github.com/vgstation-coders/vgstation13/pull/7863
Thermal regulation removed in:
https://github.com/vgstation-coders/vgstation13/pull/8203
( Look for:
if(!H.on_fire) // then the plasma can regulate him.
 			if(H.bodytemperature < T0C+37)
 				H.bodytemperature = min(H.bodytemperature+0.5,T0C+37)
 			else
 				H.bodytemperature = min(H.bodytemperature-0.5,T0C+37)
)

#### Length of time in which bug has been known to occur

Feb 10, 2016

#### Server revision

Game: ce0f1a803fb0dcc8cb7afdd184d73a2fd9e89d1c 
Patches: 78ac2f909b50159df885e55ab563750b9b00c5dd 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)
Issue also stated here https://github.com/vgstation-coders/vgstation13/issues/14035 but I've found where the issue came from so I'm making a new one.

**Comment by ghost** [comment]
strictly speaking though despite this being a bug it's not violating the in game laws of physics where NO HEAT AT ALL transfers through plasmamen suits iirc
