### ISSUE TITLE
Flamethrowers do diddly squat damage against blobbos

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#17312]
Imagine being the atmos tech in that situation and having to be all like "damn, blob, you fuckin' fine, all big with your damn walls and gross spores. I would totally burn you, both my character and the real spessman me." when all it really wants to do is thinker with pipes in another atmosia room. Like seriously imagine having to be the atmos tech and not only hide in that station while blob flaunts it's burn weakness in front of you, the favorable lighting barely concealing it's unreinforced walls right to the space, and just sit there, take after take, hour after hour, while it devours the station. Not only having to tolerate it's disgusting attitude of devouring everything on it's path but also it's haughty attitude as everyone on set tells "it's FUCKING BIG" and "DAMN, BLOB HAS GOTTEN BIG LIKE THAT??" because they're not the ones who have to sit there and watch it strut around it's emitter weakness; never before have you seen something like that, no ass, no hips, you didn't even know that existed before today. You've never seen anything this fucking disgusting before, and now you swear you can taste the fucking meaty walls from the back of their unprotected overminds as it shakes it's spores to writhe it suggestively at you, smugly assured that you are enjoying the opportunity to get paid to hide there and get crushed in it's volumptuous walls, the walls it worked so hard for with the absortion of several doors, windows and spessmans. And then the badmins calls for another bus, and you know you could burn every single person in this room before the banhammers could put you down, but you sit there and endure because you're a atmos tech. You're not going to lose your chance to play another round over this. Just bear it. Hide in a pod and bear it.

**Comment by Ephx1** [comment]
Does fire even do anything to blobs anymore? I'm pretty sure it doesn't.

**Comment by Pathid** [comment]
Fire does damage blobs. You easily can see the damage graphics appear on the "new" blob skin. But it has to be either very hot or sustained to kill them off, and they don't catch fire or count as fuel themselves. That rules out everything except plasma.

Edit: Looks like strong blob is totally immune to fire though. That's probably what you noticed, @Ephx1

**Comment by Aurx** [comment]
Blobs also breach the station just by existing anywhere remotely near a space tile, so it's nearly impossible to actually keep a fire going where a blob is.  
If you can it'll wreck them, but you generally can't.

**Comment by Jubisloviu** [comment]
it's a gat dammed stream of fire lads, that thing should decimate normal blobbo walls
if i can make a meme flamethrower mix that deals 170 damage per shot, that thing should fucking obliterate non reinforced walls, blob's meme immunity to bombs and singulo is also shite, tactically deploying welderbombs on the cores/nodes should be a thing.

**Comment by Pathid** [comment]
>meme immunity to singulo

Whaaaat? Singulo spares no blob. Explain yourself.

**Comment by Jubisloviu** [comment]
I kinda remember overminds/nodes being immune to singulo, i even remember badmins bussing Mr Clean on the blob and it doing jackshit to nodes.

**Comment by Pathid** [comment]
I can confirm Mr. Clean works on blobs, not to discount the other stuff you said.

**Comment by FudgePucker** [comment]
@Jubisloviu 11/10 issue report.
This is the level all reports should aspire to. :+1:

**Comment by FudgePucker** [comment]
Also last/first time I played blob someone singloosed and it went straight for me so no, they do not have "meme immunity" as far as I know.

**Comment by SonixApache** [comment]
Flamethrowers should 100% do decent damage to blebs, especially with meme mix.
