### ISSUE TITLE
Exploding mice runtime on gibbing

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#17313]
[19:08:55] Runtime in living.dm, line 1391: Division by zero
proc name: drop meat (/mob/living/proc/drop_meat)
usr: Kameron Pycroft (pseudonym) (/mob/dead/observer)
usr.loc: The floor (230, 254, 1) (/turf/simulated/floor)
src: Tom (/mob/living/simple_animal/mouse/brown/Tom)
src.loc: the plating (229,267,1) (/turf/simulated/floor/plating)
call stack:
Tom (/mob/living/simple_animal/mouse/brown/Tom): drop meat(the plating (229,267,1) (/turf/simulated/floor/plating))
Tom (/mob/living/simple_animal/mouse/brown/Tom): gib(0, 1)
Tom (/mob/living/simple_animal/mouse/brown/Tom): ex act(1)
explosion(the floor (226,254,1) (/turf/simulated/floor), 30, 50, 90, 0, 1, 0, 1)

**Comment by MadmanMartian** [comment]
this divide by zero will haunt me forever
