### ISSUE TITLE
Telescopic baton and classic baton dont stun on harm

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#17323]
#### Description of issue
It doesn't stun on harm intent, normal stun batons had this bug for a bit too.

#### Difference between expected and actual behavior
Hitting someone harder being just as stunning as a helpful smack.

**Comment by ghost** [comment]
couldn't reproduce; this is working on live for me

**Comment by ghost** [comment]
... can reproduce on test.
