### ISSUE TITLE
Secure Briefcase

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#17327]
#### Description of issue
Secure briefcase's keypad screen doesn't seem to update consistently.

#### Difference between expected and actual behavior
When I first set the code, I saw each number pop up as I put them in. Later on when opening it, pressing the numbers works but you need to manually exit the pop up window and attempt to open the briefcase again in order to refresh the list of numbers you've already put in. This also applies to it displaying ERROR when entering a wrong code and UNLOCKED once you've unlocked it.

It could use a UI update.

#### Steps to reproduce 
Use a secure briefcase.

#### Specific information for locating
The secure briefcase.

#### Length of time in which bug has been known to occur
Probably time immemorial.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

I saw there was one related which was added to the milestone- it might not be so much that you can't open the briefcase as the UI confused them and they failed to set the code or enter it correctly. It's surprisingly annoying to do.

https://github.com/vgstation-coders/vgstation13/issues/8890

**Comment by DamianX** [comment]
This is ancient shitcode: what's happening is that you opened a briefcase and then interacted with something else (anything like a PDA would do), that changed/reset your current `machine`. That causes the window to not update for you anymore even if you click on it. You can band-aid this by doing `usr.set_machine(src)` in `/obj/item/weapon/storage/secure/Topic()`.

But /vg/ui when?

**Comment by beesil** [comment]
Fixed by #22876
