### ISSUE TITLE
Metaclub/ had -1 votes and a -15% chance of winning.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#17325]
Random Weighted Vote Result: Packed Station/ won with 3 votes and a 42% chance of winning.
	Box Station/ had 3 votes and a 42% chance of winning.
	Metaclub/ had -1 votes and a -15% chance of winning.
	Defficiency/ had 1 vote and a 14% chance of winning.
	Bagel Station/ had 1 vote and a 14% chance of winning.

vote controller 

(E) (C) (M) (S) being_sent_to_past = null 
(E) (C) (M) (S) choices = /list (5) 
Box Station/ = 2 
Metaclub/ = -1 
Defficiency/ = 2 
Packed Station/ = 3 
Bagel Station/ = 1
(E) (C) (M) (S) chosen_map = null 
(E) (C) (M) (S) current_votes = /list (8) 
banevader43 = 1 
ncorovaneer42 = 5 
streptomutans = 3 
accipitermaris = 4 
drcelt = 4 
libertino = 1 
kurba = 3 
dacendeth = 4
(E) (C) (M) (S) data = /list (5) 
1 = /list (3) 
1 = 1 
Box Station/ = null 
3 = 2
2 = /list (3) 
1 = 2 
Metaclub/ = null 
3 = -1
3 = /list (3) 
1 = 3 
Defficiency/ = null 
3 = 2
4 = /list (3) 
1 = 4 
Packed Station/ = null 
3 = 3
5 = /list (3) 
1 = 5 
Bagel Station/ = null 
3 = 1
(E) (C) (M) (S) disposed = null 
(E) (C) (M) (S) gcDestroyed = null 
(E) (C) (M) (S) initialized = 1 
(E) (C) (M) (S) initiator = "The Server" 
(E) (C) (M) (S) interface [0x2107b635] = /datum/html_interface/nanotrasen/vote 
(E) (C) (M) (S) ismapvote = /list (5) 
Bagel Station/ = "maps/voting/Bagel Station/vgstation13.dmb" 
Box Station/ = "maps/voting/Box Station/vgstation13.dmb" 
Defficiency/ = "maps/voting/Defficiency/vgstation13.dmb" 
Metaclub/ = "maps/voting/Metaclub/vgstation13.dmb" 
Packed Station/ = "maps/voting/Packed Station/vgstation13.dmb"
(E) (C) (M) (S) lastupdate = 0 
(E) (C) (M) (S) last_update = 130067 
(E) (C) (M) (S) lock = 0 
(E) (C) (M) (S) mode = "map" 
(E) (C) (M) (S) name = "datum" 
(E) (C) (M) (S) parent_type = /datum/controller 
(E) (C) (M) (S) question = "What should the next map be?" 
(E) (C) (M) (S) started_time = 129589 
(E) (C) (M) (S) statclick = null 
(E) (C) (M) (S) status_data = /list (5) 
map = null 
What should the next map be? = null 
3 = 12 
4 = 0 
5 = 0
(E) (C) (M) (S) tag = null 
(E) (C) (M) (S) time_remaining = 12 
(E) (C) (M) (S) total_votes = 0 
(E) (C) (M) (S) type = /datum/controller/vote 
(E) (C) (M) (S) vars = /list (29) 
(E) (C) (M) (S) voted = /list (13) 
banevader43 = null 
ncorovaneer42 = null 
streptomutans = null 
accipitermaris = null 
drcelt = null 
streptomutans = null 
streptomutans = null 
libertino = null 
streptomutans = null 
drcelt = null 
kurba = null 
kurba = null 
dacendeth = null
(E) (C) (M) (S) voting = /list (14) 
1 [0x5000000] = Dacendeth /client 
2 [0x5000009] = Little Astronuat /client 
3 [0x500000b] = DrCelt /client 
4 [0x5000003] = Libertino /client 
5 [0x5000001] = NCorovaneer42 /client 
6 [0x5000008] = Xevonix /client 
7 [0x5000004] = BoHaynes /client 
8 [0x500000c] = Kurba /client 
9 [0x500000d] = BanEvader43 /client 
10 [0x500000f] = StreptoMutans /client 
11 = null 
12 [0x500000e] = Accipitermaris /client 
13 [0x5000002] = JoeMother0 /client 
14 [0x5000005] = DamianQ /client
(E) (C) (M) (S) weighted = 1

**Comment by ghost** [comment]
[06:03:22] HELP: StreptoMutans/(Joe Shafer) (?) (PP) (VV) (SM) (JMP) (CA) : I voted meta and it still had 0 votes. When I changed my vote it had -1 
[06:03:26] Coder Liasion PM to-StreptoMutans/(Joe Shafer): heck
[06:03:38] Player PM from-StreptoMutans/(Joe Shafer): Maybe because I joined after the shuttle had docked? No idea
[06:03:59] Coder Liasion PM to-StreptoMutans/(Joe Shafer): thank you that should be enough to fix it

**Comment by gbasood** [comment]
#17290
likely related
