### ISSUE TITLE
blast doors openable via water tank. Prisoner 545 too powerful.

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#17349]
![prisoner 545](https://user-images.githubusercontent.com/16896032/35846407-483b28a2-0b62-11e8-8317-fbbea1a84f0b.png)

Pretty self explanitory

**Comment by carshalash** [comment]
Can I get the its loose tag please sood?

**Comment by Rhimrifer** [comment]
Farmbots open any blast door.
![farmbot](https://user-images.githubusercontent.com/30352495/35848091-c048b54e-0aea-11e8-9ba5-172408ce4968.png)

**Comment by Kurfursten** [comment]
I knew about this on Deff but I never even considered the AI core applications

Yeah as much as this is hilarious it needs to be fixed.

**Comment by Pathid** [comment]
I expect that any dense bot will do this. Does it work with an ED-209?

**Comment by Rhimrifer** [comment]
Literally any bot can. Alt-click a blast door while pulling a medibot  and move it onto the same floor.
