### ISSUE TITLE
Couldn't buy a fireball spell after buying firebreath

### ISSUE THREAD

**Issue by Chazach** [d3athrow/vgstation13#17346]
#### Description of issue
tried to make bang happen but it wouldnt

#### Difference between expected and actual behavior
left with fire halitosis as my only spell

#### Steps to reproduce 
spawn in as wizard, buy fire breath, when clicking fireball it cucc'd me and said no no

![cuccd](https://user-images.githubusercontent.com/25990485/35834565-4e3a067c-0ace-11e8-98fd-957797957176.png)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Rhimrifer** [comment]
Just tested and had the same issue.

**Comment by ShiftyRail** [comment]
Might be the "helpers for spells" PR
Will take a look at it

**Comment by MadmanMartian** [comment]
No, it's the spellbook, it uses locate(spelltype) in spell_list

locate(type) is basically calling istype on everything in that list.

Fire Breath is /spell/targeted/projectile/dumbfire/fireball/firebreath
Fireball is /spell/targeted/projectile/dumbfire/fireball
