### ISSUE TITLE
Human convective heating/cooling apparently doesn't care about air pressure

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17347]
You can be wearing a spacesuit in 0.5 kPa and 1500 Kelvin and if your suit doesn't have 1500 K heat protection you fry just as fast as if the pressure was 100 kPa. As far as I know this makes no sense thermodynamically and allows a small total heat input to easily make a huge area very dangerous. This led to particularly unfortunate consequences during a recent away mission (it was the Wild West one) which got vented and then heated by trapped air from a small fire. And then today a similar thing happened on the station while the air alarms had been disabled by the Corporate AI.

**Comment by Kurfursten** [comment]
Nothing cares about air pressure, which is why a bombing can cause telecoms to overheat

>Room depressurizes
>Low air pressure makes it easy for the machines to heat the air
>High temperature fries machines

**Comment by Pathid** [comment]
But that does make some sense since the heat comes from inside the machines, even though it could be modeled better probably.

**Comment by Exxion** [comment]
Related to #18345
This specifically is probably outdated, though, since it was made while we were still in `group_multiplier` withdrawal
I haven't verified if the code actually *works*, but hypothermia is *supposed* to depend on air pressure (or rather the var names claim it's supposed to depend on pressure, but according to the math it actually depends on number of moles)
This is why ventcrawling nymphs would instantaneously freeze to death for a while after hypothermia was added

**Comment by ghost** [comment]
Hypothermia is supposed to work like that but suits are different @exxion - either they work or they don't for fully preventing heat transfer.


UNFORTUNATELY in 0.5kpa you do not conduct less heat because people moaned and bitched at me for space "not being cold"

**Comment by west3436** [comment]
Duplicate of the ancient bug #13393

**Comment by west3436** [comment]
The "mx" var **does** factor in pressure when calculating damage to the mob.

`//minimize this for low-pressure enviroments
	var/mx = 5 * firelevel/zas_settings.Get(/datum/ZAS_Setting/fire_firelevel_multiplier) * min(pressure / ONE_ATMOSPHERE, 1)

	//Always check these damage procs first if fire damage isn't working. They're probably what's wrong.
	var/fire_tile_modifier = 4 //multiplicative modifier for damage received while on fire and standing on a fire tile
	apply_damage(fire_tile_modifier*HEAD_FIRE_DAMAGE_MULTIPLIER*mx*head_exposure, BURN, LIMB_HEAD, 0, 0, used_weapon = "Fire")
	apply_damage(fire_tile_modifier*CHEST_FIRE_DAMAGE_MULTIPLIER*mx*chest_exposure, BURN, LIMB_CHEST, 0, 0, used_weapon ="Fire")
	apply_damage(fire_tile_modifier*GROIN_FIRE_DAMAGE_MULTIPLIER*mx*groin_exposure, BURN, LIMB_GROIN, 0, 0, used_weapon ="Fire")
	apply_damage(fire_tile_modifier*LEGS_FIRE_DAMAGE_MULTIPLIER*mx*legs_exposure, BURN, LIMB_LEFT_LEG, 0, 0, used_weapon = "Fire")
	apply_damage(fire_tile_modifier*LEGS_FIRE_DAMAGE_MULTIPLIER*mx*legs_exposure, BURN, LIMB_RIGHT_LEG, 0, 0, used_weapon = "Fire")
	apply_damage(fire_tile_modifier*ARMS_FIRE_DAMAGE_MULTIPLIER*mx*arms_exposure, BURN, LIMB_LEFT_ARM, 0, 0, used_weapon = "Fire")
	apply_damage(fire_tile_modifier*ARMS_FIRE_DAMAGE_MULTIPLIER*mx*arms_exposure, BURN, LIMB_RIGHT_ARM, 0, 0, used_weapon = "Fire")`
