### ISSUE TITLE
Taking off a transformation mask mid-jaunt

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17358]
#### Description of issue
Jaunting while wearing a transformation mask (mask of the wraith in this case) lets you make mindless copies of your mask's form by taking the mask off mid-jaunt. Not exactly game-breaking since wraiths don't have AI.

#### Server revision

Game: d66cb2decdb046adeeee5d54b555ee86f8c390fd 
Patches: 78ac2f909b50159df885e55ab563750b9b00c5dd 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DeityLink** [comment]
Guess we have a way to farm ectoplasm now

note to self: allow soulstone shard grinding later
