### ISSUE TITLE
Cultify artifact turns the escape shuttle floor into space / invisible

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#17353]
Just happened on packed, when the shuttle floor was cultified by an artifact, it turned into space. Wasn't actually space, it just turned invisible.

**Comment by DeityLink** [comment]
Yeah, that's what always happenned. Never got around to fix it. Surely something forgotten in its Cultify() proc. Before parallax the floor would just be black., and I thought blood and runes looked great on it.

**Comment by jknpj** [comment]
I'll try to solve it at least on shuttle turfs.
