### ISSUE TITLE
Windoors don't drop electronics on destruction by melee weapon

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17368]
#### Description of issue
Windoors don't drop electronics on destruction, _when destroyed by a melee attack._

#### Difference between expected and actual behavior
Expected the windoor to create a circuitboard on destruction, yet it doesn't
https://github.com/vgstation-coders/vgstation13/blob/c117a35244c04c66ddd2e1b6550777aba416677c/code/game/machinery/doors/windowdoor.dm#L358-L372

#### Steps to reproduce 
Destroy a mapped-in windoor with ~~any weapon~~ scratch that, it has to be with a melee weapon.

#### Server revision
Game: f82455d2654e74f1a2877fe99384c9da40e5454a 
Patches: 78ac2f909b50159df885e55ab563750b9b00c5dd 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kammerjunk** [comment]
![image](https://user-images.githubusercontent.com/5942183/36063628-9d19a6b2-0e7f-11e8-8691-e7394973a487.png)
Every destroyed windoor here is mapped in except the one in the middle of the medbay front hallway. Tested on tgstation, not test_box or something like that. Can't see a merged PR within the last 2 days that addressed this.
Which windoor(s) did you destroy? Mapped-in windoors have electronics = null and created windoors have whatever board you made them with. It looks like the board and the accesses on it should get set right. The new circuitboard is moved to loc either way.

**Comment by Pathid** [comment]
![windoor2](https://user-images.githubusercontent.com/31839805/36077708-174fd002-0f23-11e8-93f1-d992a93831d3.PNG)
Huh. Maybe it's a Deff thing?

![windoor3](https://user-images.githubusercontent.com/31839805/36077751-7ec73130-0f23-11e8-8493-8a4a96b1e0e3.PNG)

Oh so apparently _lasering_ them makes the board drop. Updating the description.

**Comment by Pathid** [comment]
Also it's not mapped-in windoors. My bad.

**Comment by Pathid** [comment]
Also, get this, making a new windoor with the electronics that do drop doesn't transfer the access requirements to the new door.
