### ISSUE TITLE
Vox Armalis need oxygen to live

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17367]
#### Description of issue
A Vox Armalis, although being a sub-species of Vox, can't survive without oxygen.

#### Steps to reproduce 
Spawn an Armalis on the vox outpost and watch as it slowly dies.

#### Server revision
Game: f82455d2654e74f1a2877fe99384c9da40e5454a 
Patches: 78ac2f909b50159df885e55ab563750b9b00c5dd 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Ephx1** [comment]
When in the world are we going to use these disgusting things anyways?

**Comment by SonixApache** [comment]
the obvious solution is to remove vox armalis

**Comment by Kammerjunk** [comment]
They're simple animals and `/mob/living/simple_animal/vox` doesn't seem to exist for anything other than `/mob/living/simple_animal/vox/armalis` so I expect that this is an issue with simple animals in general being hardcoded to suffocate (silently) without oxygen
