### ISSUE TITLE
can't unload potted plant when picked up with the hydrolic clamp

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17385]
(WEB REPORT BY: tellossee REMOTE: 172.93.109.202:7777)
# Revision
887a6f632dd53c404fb1ff3c79df06ed1d588986

# Description
picked up a potted plant with hydrolic clamp. Couldn't unload it.
# Steps to Reproduce
pick up a plant with a hydro clamp. Try to unlaod it.
# What you Expected
it to unload
# What Actually Happened
it didn't.

**Comment by DamianX** [comment]
![image](https://user-images.githubusercontent.com/6307265/36009130-1d95fb3c-0d4b-11e8-9428-3c9ba5d69a3b.png)

**Comment by Pathid** [comment]
Try it with something stashed in the plant maybe.

**Comment by DamianX** [comment]
also works

**Comment by groosbstrd** [comment]
I swear it would no unload from my clamp storage. I'd click "unload" and nothing would happen. All the other buttons would work.

**Comment by ghost** [comment]
@groosbstrd was the issue report made on that round? Maybe there's a runtime error here
