### ISSUE TITLE
This is fine.

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#17393]
![thisisfine](https://user-images.githubusercontent.com/17928298/36031952-8b7b6cd4-0d93-11e8-8b88-8989e1ce126b.png)

The current silicon fire immunity is actually an oversight. This issue is related to #15346.

Let's check their fire_act():
https://github.com/vgstation-coders/vgstation13/blob/25b228d3ecf180434125da9047275280ea2ce535/code/modules/mob/living/silicon/robot/life.dm#L335-L337
Ok so, they don't have fire_stacks, fine. IgniteMob() is called, but since cyborgs don't have their own IgniteMob()...

https://github.com/vgstation-coders/vgstation13/blob/70302175f29fe4915f40b2df8beb2f0b3efd1f41/code/modules/mob/living/living_defense.dm#L266-L274

They don't ignite at all. The best part is, they are supposed to take damage when on fire: 
https://github.com/vgstation-coders/vgstation13/blob/25b228d3ecf180434125da9047275280ea2ce535/code/modules/mob/living/silicon/robot/life.dm#L321-L326

**Comment by Pathid** [comment]
Do they stop, drop and roll?

**Comment by jknpj** [comment]
having no fire_stacks means they don't keep burning outside a turf that is on fire

**Comment by Blithering** [comment]
If this were to be fixed, I'd say keep the fire immunity on engiborgs, as they usually do a fair bit towards firefighting

**Comment by AutismSpider** [comment]
only engi borg and mommis need the fire immunity

**Comment by aceedex** [comment]
It's a feature

**Comment by aceedex** [comment]
Jokes aside keep it for the medborg too, since they usually double down as paramedics

**Comment by ghost** [comment]
Maybe a semi-cheap upgrade makes cyborgs fireimmune?
