### ISSUE TITLE
Balloon decoys can't be examined

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17400]
#### Description of issue
They can't be examined with either shift-click or with the menu.

#### Difference between expected and actual behavior
I remember being able to examine them and they copied the original person's description.

#### Length of time in which bug has been known to occur
I first noticed this a few days ago. Remember it not happening a few months ago.

#### Information for locating
https://github.com/vgstation-coders/vgstation13/blob/35a139dc0391bbb2ef322c05e253e55e264cf301/code/game/objects/items/toys.dm#L1349-L1360

#### Server revision
Game: caee6789f84367f2ddb35dedf4e44e61bd83dffb 
Patches: 78ac2f909b50159df885e55ab563750b9b00c5dd 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
I see the issue.
