### ISSUE TITLE
All access not enough to lock ED-209

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17413]
(WEB REPORT BY: reviire REMOTE: 172.93.109.202:7777)
# Revision
caee6789f84367f2ddb35dedf4e44e61bd83dffb

# Description
All access isn't enough access to lock the controls of an ED-209.
# Steps to Reproduce
Try to lock ED-209 with all access.
# What you Expected
To lock it.
# What Actually Happened
It didn't lock.

**Comment by Kammerjunk** [comment]
Can't see the issue here.
![image](https://user-images.githubusercontent.com/5942183/36063579-059761a8-0e7f-11e8-8298-c50f5c375902.png)
Keep in mind that the access panel has to be open and the bot must not be emagged for the controls to be able to be toggled. What message did you get?

**Comment by nervere** [comment]
no longer an issue
