### ISSUE TITLE
Drinking Glass Transfer to Soldering Iron

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17427]
(WEB REPORT BY: hbyc REMOTE: 172.93.109.202:7777)
# Revision
ba8e532970cddfb7e75d397b4bab413ecbe9f095

# Description
Drinking glasses cannot be used to fill soldering irons
# Steps to Reproduce
Fill glass with sulph
click on empty soldering iron
# What you Expected
transfer sulph to iron
# What Actually Happened
nothing

**Comment by Kurfursten** [comment]
The cause of this is that only children of glass can transfer chemicals to the soldering iron, and the drinking glass is not a child of glass

Not being part of glass denies it certain privileges such as toggling the top of the container open/closed, set the label with a pen, splashing onto things, and fitting into an IV drip
