### ISSUE TITLE
Becoming thin while stuck inside a disposals pipe doesn't unstick you

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17425]
#### Description of issue
As a borer I put lipozine into my fat host hoping it would let him move along in the pipe but apparently there's nothing in pipe code that continues to check if you're fat after getting stuck initially.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MadmanMartian** [comment]
Why would it unstick you? You've lost momentum in the pipe

**Comment by DamianX** [comment]
Obviously you should be able to fart your way forward.

**Comment by Pathid** [comment]
Well you could just crawl through at that point but I don't expect anyone to impliment that just for this particular scenario.

**Comment by Pathid** [comment]
Actually, after looking at this:
https://github.com/vgstation-coders/vgstation13/blob/797e78300fc2643e44fc8ceabbfe1aca1c972bcf/code/modules/recycling/disposal.dm#L656-L668
It seems like being hit by a disposal holder from behind _does_ check if you're fat and will get you moving again. Maybe I'll call this a non-issue after all.

Except no, has_fat_guy never gets reset to zero for the holder. That is kind of an oversight.
