### ISSUE TITLE
Flashbang/Grenade balance change

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#17429]
A lot of people complain about one second long flashbangs, please discuss ideas to make them more fun.

One second long flashbangs are very effective, and if anyone ever made grenades they'd too be very effective if set to 1 second long.

I propose a two second long minimum to a timer. This would still make them very good if the thrower just holds them a second before throwing, but if thrown instantly gives alert people a chance to run away and not be directly next to it, probably will still be stunned by a flashbang but the distance would reduce the stun alot. Also gives the problem of maybe the thrower overcooks it and their grenade backfires on them, which isn't a problem with 1 second long grenades as you the way they are used now is by aiming, hitting the action key and instantly clicking to throw.

if you have an idea please post.

**Comment by ghost** [comment]
Thread poster suggested the timer minimum instead being at least 3 seconds, which I prefer to 2.

**Comment by TurboGay** [comment]
Three seconds is a good idea, but another excellent alternative is to reduce the stun radius but make it still blind you and force you to drop items at the current global range it has now, forcing you to actually aim near your target. Also, with normal grenades you can just set them to voice so the timer is less noteworthy in that regard.

**Comment by aceedex** [comment]
How to make bangers useless.txt

**Comment by Chazach** [comment]
I would prefer effective radius/effect being reduced over removing the timer changing. Currently bangers can even knock people down offscreen, which doesn't seem particularly well thought out.

**Comment by ShiftyRail** [comment]
What Chaz suggested seems better.

**Comment by Pathid** [comment]
They need an effect falloff over range applied to the flash like they do for the bang. Also an in-hand icon. (All grenades do, even if it's a few pixels.)

**Comment by Blithering** [comment]
They had an inhand icon, if they don't have one now it may be due to the overstuffed inhands again. The same thing happened with tasers a while back

**Comment by Pathid** [comment]
They do have an in-hand apparently. I'm all mixed-up unless they disappear on the main server for some reason.

**Comment by DrSnips** [comment]
I don't think flashbangs should be nerfed due to them being one of the very few items that security actually has to fight silicons.
If I was forced to pick an option the stun fall off thing seems like a reasonable change but I would never touch the timer settings.
While they are strong against carbons and the stun falloff would be ok I think ailicons should talk the full effect for the reason I said before.
I also feel like this is a "I died/got arrested pls nerf"

**Comment by Diavill** [comment]
make bangers an AOE disorient that lasts 2 minutes, but still works as a stun against siliconis

**Comment by DrSnips** [comment]
That completely removes the use of a flashbang since disorient does pretty much nothing if not makes you better at avoiding being caught. See hugborg harmalarm.

**Comment by Pathid** [comment]
>one of the very few items that security actually has to fight silicons.

Few kinds, maybe. (If three is few.) However the brig starts out with at least 20 of them for free. And borgs have really no counter-play to the long screenwide stun save plasmaflooding, which is what the robust ones will do every time due to no alternative.

**Comment by SonixApache** [comment]
and there it is

**Comment by DrSnips** [comment]
>Borgs need a counter counter.

For what reason? Plasmaflood is just a big fuck you station in general so I don't consider it a direct counter to just flashes.

**Comment by Pathid** [comment]
Because maybe they should have a way to not insta-lose that isn't the same boring thing every time? Might as well remove malf and traitor AI. It's really only fun for the AI.

**Comment by DrSnips** [comment]
Im pretty sure you're aware of how our combat system works. Stun and done. Borg tasers/stunbatons can stun carbons but carbon tasers/stunbatons cannot stun borgs. Flashbangs are the accessable option to deal with silicons.

**Comment by Pathid** [comment]
Yes, but you can dodge a taser. Just try to dodge a one second flashbang. And they stun longer than the actual ion rifles that used to exist for that purpose.

(Also I don't know if you're aware but every officer, roboticist, and ~~most~~ all heads get a flash, which is essentially a stunbaton against borgs, with an extra AoE blind mode that goes out three tiles.)

**Comment by iFlashYou** [comment]
Why should it make useless against borgs? Keep it the same against silicons but remove this 7x7 stun against carbons

**Comment by Pathid** [comment]
> 7x7

If a carbon is wearing eye protection and a helmet (any kind of helmet, even costume helmets) it's a 5x5 two second stun. With no eye protection it's a 15x15 ten second stun. This is also the value silicons get.

**Comment by Allspice** [comment]
Flashbang stun for silicons and unprotected carbons lasts ~18-20 seconds; it's like nuke device time, it ticks down about once every two seconds.

Note: Unprotected flashbang stuns for the same duration as e.g. stun batons, flashes, tasers. 20s is basically the default stun duration.

**Comment by Pathid** [comment]
Alright I knew it was longer. So it's 
- 15x15 ~20 second flash stun for carbons with no eye protection and silicons.
- 5x5 ~4 second bang stun for carbons with helmets.
- 5x5 ~20 second bang stun for carbons without helmets.
- 11x11 ~16 second bang stun for carbons without helmets.
- 15x15 ~8 second bang stun for carbons without helmets.

**Comment by ghost** [comment]
Bangers only have this shitty ui because they came from the dawn of man. If they weren't, you'd just pop the timer off and change it. What it already does. Take stimulants, use your stun clear,  or otherwise don't make yourself chump bait. It's not like you don't know they have them. Better yet, just drop a prox grenade in something and sit in a bin or locker and collect your free dead officer when he tards over wanting to bang free balids.

**Comment by SonixApache** [comment]
@SarahJohnson489 have you seen #15831?

**Comment by ghost** [comment]
Yeah, if you spend the time to get that, it's a hell of a lot easier to nut the dev than it is playing with the prox's reaction time on explosion/one-tanks.

**Comment by Exxion** [comment]
Discussion dead, reopen if you want, etc.
Pretty sure there was a change to flashbang balance since this issue, too, so it's outdated
