### ISSUE TITLE
Going over blood while in a janicart leaves foot prints

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17431]
(WEB REPORT BY: deethree REMOTE: 172.93.109.202:7777)
# Revision
8f769fd48c4c52608cf6ebce168a431fbd66ebbf

# Description
Riding a janicart and going over blood and probably other stuff leaves bloody foot prints behind.
# Steps to Reproduce
drive a cart over moist blood
# What you Expected
no prints or maybe tire tracks
# What Actually Happened
foot prints

**Comment by Pathid** [comment]
Eh, I can do no prints if that's okay.
