### ISSUE TITLE
Chemicals Transferred From a Fire Extinguisher Dissapear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17435]
(WEB REPORT BY: anglosphere REMOTE: 172.93.109.202:7777)
# Revision
f7a79805f577f465cecd6003e4766de37690023c

# Description
Chemicals transferred from a fire extinguisher to a beaker disappear. 

# Steps to Reproduce
Put a chemical in a fire extinguisher
Dump it into a beaker

# What you Expected
The chemical to transfer to the beaker
# What Actually Happened
The chemical disapeared

**Comment by Kurfursten** [comment]
My theory: you had the extinguisher wrenched open. Its afterattack causes it to splash if it's wrenched open, and maybe you didn't see the message.

**Comment by nervere** [comment]
Can't replicate, Kurf's explanation seems likely.
