### ISSUE TITLE
Can print circuits with less acid than needed.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17449]
(WEB REPORT BY: reviire REMOTE: 172.93.109.202:7777)
# Revision
1734656c6946434a0f1c11134bfe4528b7001f51

# Description
Can print circuits via circuit imprinter with 20 acid. Will go down to 0. If 30 is in, it will still use 30.
# Steps to Reproduce
Use imprinted, make circuit with 20 acid.
# What you Expected
To not work.
# What Actually Happened
Worked.

**Comment by Probe1** [comment]
shouldn't it be tagged under sight

**Comment by SonixApache** [comment]
ancient bug

**Comment by DrSnips** [comment]
I'm pretty sure it's a FEATURE because of how making stuff in a protolathe/printer is. Its due to how things are rounded I'm pretty sure.

**Comment by Pathid** [comment]
Similar is how when a fabricator loses power it finishes the current thing it's building before stopping.

**Comment by Probe1** [comment]
After looking at RnD code for 30 seconds I am dead inside.

**Comment by Zth--** [comment]
sacid is being multiplied by 1.5 for some unknown reason. 20 *1.5 = 30. I tried with 50 having as a result 75.

Maybe a coeff applying where it shouldn't?
