### ISSUE TITLE
Defibs have no in-hand sprite

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17442]
They really ought to have one.

**Comment by ghost** [comment]
Could have sworn they had one, a victim of the overstuffed in-hand sheet?

**Comment by Bilgecrank** [comment]
These are in the Weapons.dmi, but are currently unused, paddle_lefthand and paddle_righthand with a lot other defib sprites.

![image](https://user-images.githubusercontent.com/8432868/36186301-2ae3f388-110c-11e8-889e-c1018aa1c762.png)

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/35710a10e460f74858d0cc8c3baa57715c972e37/code/game/objects/items/weapons/defib.dm#L67-L72

Try to spot what's wrong with this picture.

**Comment by jknpj** [comment]
>item_state

**Comment by Probe1** [comment]
>wield code

https://i.imgur.com/f83qgpS.png

**Comment by beesil** [comment]
Fixed by #18586
