### ISSUE TITLE
Chemistry machines dispense beakers under their own spirte.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17453]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
88171d9ae136f6e4cd33f1a1e2e2a0c90dba0dcc

# Description

When ejecting the beaker on a chemistry machine, it shows up under said machine.

# Steps to Reproduce

Work on a chemistry machine, try to eject the beaker.

# What you Expected

The beaker to show up OVER the machine.

# What Actually Happened

It showed up UNDER the machine.

**Comment by Pathid** [comment]
From what I remember, this depends on your client version. Try updating to the latest beta. Apparently it doesn't freeze anymore.

**Comment by ShiftyRail** [comment]
I'm on 512 and I never had that bug on 510.

**Comment by Kurfursten** [comment]
Can you reproduce this in multiple shifts? Used to be this would happen every once in a while with the tank storages dispensing O2 and plasma tanks under the storage unit -- back before they dispensed straight to inhand. Whether or not it would go on top or below just varied by shift.

**Comment by Pathid** [comment]
It does happen on the latest version apparently.
