### ISSUE TITLE
Explosion Recipe Adjustment

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#17456]
Hi, we should make it where water + potass doesn't work when put into someone's body at all, unless it meets the threshold requirement to cause their body to explode, that way you can't magically remove all reagents from people.

**Comment by Kurfursten** [comment]
To make this less confusing, I'd like to give some numbers just for anyone who wants to argue about this. For each 1u of water and 1u of potassium, you get 2u **created volume** of explosion. This creates a reagents_explosion effect of **amount** = created volume/10 rounded to the nearest 1, with a hardcap of 15. If amount <=2, there is **no explosion effect** on the turf at all, but instead there is a chance for any mobs standing on that exact turf to get knocked down (chance is 50*amount). Turf explosions are given based on a range calculation, where **range** = amount/3 - 1. This range is also capped at 14, but 4 is the highest result (15/3-1). Range is then converted into the familiar devastation, heavy, light format. **Dev** = range/4, Heavy = range/2, Light = Range.  Dev and Heavy round, Light does not. These all have hardcaps that don't matter.

* The most popular clearing pills are 1u each, with 2u created volume, giving a 10% chance of knockdown and no other effects
* The largest possible mixture without causing a turf explosion is at 20 created volume (10u water, 10u potassium). 100% chance of knockdown.
* The smallest turf explosion with a light radius of 1 is 60 cv (30wat/30pot). This is also the point where heavy radius rounds up to 1. **This will gib a dead body if it is not wearing bomb armor**
* The smallest turf explosion where dev is high enough to round up to 1 is 90cv (45wat/45pot) **This will gib a living human if they are not wearing bomb armor**
* The largest possible explosion is at 140 created volume (70u water, 70u potassium). This is a hard cap, nothing past this matters.

**Comment by nuklearcellphoneg** [comment]
Activated charcoal exists(albeit broken) for the purpose of clearing chems.

Water potass removes the need for treating poison like this. One could argue that cloning also removes the need for treating poison, but it removes the need for kelotane, dermaline, bicaridine, blood packs, IVs, surgery, et alia.

**Comment by ghost** [comment]
Just hack code it to not clear reagents when it reacts in a mob. Free my nigga allahu broken hand syringe explosion stabs. And I guess non-Ody RSG's but honestly nobody uses alternating water-potass over chloral/mutagen

**Comment by Pathid** [comment]
>(albeit broken)

Still? Or were you not aware of the recent charcoal buff?

**Comment by SonixApache** [comment]
@SarahJohnson489 rapid syringe gun with chloral / nitro mix is pretty fun.

**Comment by jknpj** [comment]
Wait didn't we just have a shitstorm over this that resulted into N3X quitting, charcoal buffed and the fix reverted?

**Comment by Irradiation** [comment]
We did, but this is Nuke we're talking about.

**Comment by nuklearcellphoneg** [comment]
Why would you ever use Charcoal when you have the Explosion that instantly removes all reagents, doesn't make you vomit, and costs infinitely less to produce?

**Comment by nuklearcellphoneg** [comment]
On the opposite end, why would you ever attempt to poison someone as a schtick in whatever variety(hyperzine OD, lexorin, whatevs) when whatever you did can be undone with 8 clicks?

**Comment by ghost** [comment]
Because you go broad spectrum and they're dead before they get to 8 clicks.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Close this
