### ISSUE TITLE
Vox have blue blood yet their organs produce red blood splatters

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#17467]
![voxblood](https://user-images.githubusercontent.com/7573912/36289934-3c00e0a0-12c3-11e8-8811-320ea4cabbae.png)

**Comment by Probe1** [comment]
there has to be a better way to do this than tracking down every edge case.  footprints organs blood drops sprites.

**Comment by SonixApache** [comment]
Species variable for organs?

**Comment by Dacendeth** [comment]
plasmamen with no blood leave red blood splats as well.

**Comment by DeityLink** [comment]
Organs should just take the source mob's species' blood color when they're created.
