### ISSUE TITLE
Sound systems don't work on shuttle turfs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17463]
(WEB REPORT BY: reviire REMOTE: 172.93.109.202:7777)
# Revision
1768cfa5bb81ae2bbca5e72fdc190d44de2b9def

# Description
On a shuttle turf, such as the escape pod with a sound system on it, can't be heard while on the pod, but can be heard while off the pod.
# Steps to Reproduce
Play music via sound system, stand on pod, step off pod. Note difference.
# What you Expected
Music to be hearable while on the pod. 
# What Actually Happened
It could only be heard while not on the pod.

**Comment by Kurfursten** [comment]
The pod is a separate area with its own sound system tuned to the escape radio channel
