### ISSUE TITLE
Thread Map Insights

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17462]
Mostly so I don't forget them but other people can talk about them I guess, these are ideas about maps that I think are interesting or probably good that I've seen in the thread

**Packed**
* Since it lacks a disposal as a gimmick, I've seen a couple times the recommendation that Cargo get a roundstart RCS and telepads (maybe a recharger for it? Or rewrite the RCS so the battery is removable like a baton)
* HoP office closer to Bridge (probably most relevant because deadpop means someone's going for the spare usually)
* Increase the size of below-medbay maint (I've seen this one a couple times before)
* Improve EVA? Make AI core accessible without going through science?

**Deff**
* Secvend recharge pack should be moved to somewhere more secure than maint
* Evidence room needs to not border maint
* Interrogation room below court feels too out of the way to be used for processing
* Perma Atmos + Perma generally too exposed to maint
* External airlocks (sec EVA) not ID locked

Particularly in the case of Deff, I wonder if the solution is not completely overhauling the brig again but instead overhauling the ruined medbay part of maint.  I might do some rough sketches like I did before we redid Deff medbay

**Comment by Probe1** [comment]
Adding another sec maint door sounds like the best solution to both the secvend and evidence room complaints.  One door two problems solved and lord knows deff has enough maintenance.  

![dreammaker_2018-02-15_12-54-42](https://user-images.githubusercontent.com/8550416/36272430-8268bd98-124f-11e8-96c1-e02ecdadd97b.png)

**Comment by Probe1** [comment]
The sec airlocks require "63" but since they're cycling airlocks they rely on buttons instead of bump() / onclick() .  I assume that's the problem.

**Comment by Kurfursten** [comment]
Buttons can receive access iirc

**Comment by Probe1** [comment]
Do they inherit it from the doors they're attached to?  The buttons outside sec don't have it.  Regardless I haven't tested any of this in game.  It could very well be working fine.

**Comment by Kurfursten** [comment]
I do not think so
