### ISSUE TITLE
Atmos likes to push things through windows and windoors.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#1747]
Occasionally, when rooms are depressurized about and a door opens causing air to move around items start flying about right? On a few occasions I noticed that items can warp through windows. It only works when the windows have no structure (Read: Grille) is in the way. Meaning if you removed the grille in a window then allow air to push objects at it, the air pushes the object under the glass rather than against it.
One way to test:
Depressurize the maint tunnel behind botany
Put an item at the door to the backroom of botany. NOT IN THE BACK ROOM but in the main tray room.
Open the door between the main room and the back room and watch the item zoom through the little glass window/windoor thing meant for MULEs

**Comment by d3athrow** [comment]
This should be fixed.
