### ISSUE TITLE
Newest version of byon lags

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17480]
(WEB REPORT BY: tellossee REMOTE: 172.93.109.202:7777)
# Revision
3759a519c89f10f00270688d0eeb677664c38800

# Description
Newest version of byond (512 I think?) will lag very badly every 4ish minutes. Like the game runs but it stutters super bad. Reconnecting will fix it for 5ish minutes then it does it again. On 511.132 or whatevever the problem doesn't happen.

# Steps to Reproduce
play on /vg/ with the newest version. It stutters/lags pretty bad after a bit.
# What you Expected
It not to I guess
# What Actually Happened
It sutters/lags and reconnecting is the only fix for a short amount of time. Playing on older verision of byond doesn't have this issue.

**Comment by gbasood** [comment]
okay but did you try this on literally any other setup
do you know if it's BYOND for you or just BYOND for you on our server
specifically unless it's our problem there isnt shit we can do about it

**Comment by Intigracy** [comment]
Try installing byond 512.1403

you can find it here, at the bottom of the list - http://www.byond.com/download/build/512/

**Comment by Exxion** [comment]
Bad report, outdated version
