### ISSUE TITLE
No alerts for taking things from id slot.

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#17483]
Self explanatory

**Comment by Dacendeth** [comment]
like someone stealing your id? It's a chance to alert im pretty sure, thought it was a feature?

**Comment by carshalash** [comment]
In four tests it didnt alert once.

**Comment by Dacendeth** [comment]
I tested this months ago with someone and they said they only got a "id being fumbled with" message sometimes. Suppose it was a long time ago so something might have changed.

**Comment by DamianX** [comment]
Likely a feature
https://github.com/vgstation-coders/vgstation13/blob/49162f22e8d8d93b645d1fd392c6b03f9f6d0f34/code/modules/mob/living/carbon/stripping.dm#L169

all slots but ID and pockets use `visible_message` instead of `to_chat(user)`

**Comment by Ephx1** [comment]
wait, why would this be a feature?
If I'm reading this right, the victim gets no message about their shit being touched. If that's true, why do the assistant pick pocket gloves exist, which do exactly that?

**Comment by DamianX** [comment]
pickpocket gloves prevent this message from being displayed if the action fails
https://github.com/vgstation-coders/vgstation13/blob/49162f22e8d8d93b645d1fd392c6b03f9f6d0f34/code/modules/mob/living/carbon/stripping.dm#L181

they also place the stolen item directly into your hand rather than on the ground

**Comment by Ephx1** [comment]
Well then at the very least it should let someone know their ID is being taken right off the bat. How is someone going to move their hand in such a way that they'll swipe something off your chest?

**Comment by SonixApache** [comment]
@Ephx1 You'd be surprised.

This is a feature, and a fine one at that. No need to change it.

**Comment by ghost** [comment]
It gives a message only if the action fails.

Also this title is not self-explanatory you fuckwit.
