### ISSUE TITLE
Can't collect meat from monkey on spike

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17494]
(WEB REPORT BY: higgsbonbon REMOTE: 172.93.109.202:7777)
# Revision
a38ecef4c7724fd7a2446420788f85442cc13113

# Description
A monkey, when put on a meat spike, yields no meat and thus makes the spike impossible to use or deconstruct.
# Steps to Reproduce
Unknown, was working several times before the bug.

**Comment by ghost** [comment]
Tested it, Got two meat, could spike additional monkeys and deconstruct the spike after.
Dunno why we got two meat instead of three but yeah.

**Comment by Probe1** [comment]
Thank you for testing it 😄

**Comment by Pathid** [comment]
@SarahJohnson489 Seems to be because of #17019
