### ISSUE TITLE
Motorized wheelchairs and possibly other variants of wheelchairs now have laggy and jerky movement when driving them

### ISSUE THREAD

**Issue by TurboGay** [d3athrow/vgstation13#17493]
#### Description of issue

Same as the title, I can have perfect smooth movement on foot and on other vehicles such as the janicart, but getting on a motorized wheelchair and driving around makes your game look laggy or jerky. Previously motorized wheelchairs were very smooth and operated just fine.

#### Difference between expected and actual behavior

Expected movement not to be janky/laggy.

#### Steps to reproduce 

Drive motorized wheelchair around, experience a laggier looking game than on foot.

#### Length of time in which bug has been known to occur

Not sure, haven't used motorized chairs in months.

#### Server revision

a38ecef4c7724fd7a2446420788f85442cc13113

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Pathid** [comment]
Related to #17044 and #17053

**Comment by Exxion** [comment]
You know, I'm pretty sure there's an internal BYOND flag specifically for this purpose
Perhaps we should try using it
