### ISSUE TITLE
New Silicon Photo manager does not show picture contents in text

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#17506]
#### Description of issue

With the prior silicon camera system, opening "view images" and choosing a picture would show the picture and a description "You see Greyshit McCult hold the arcane tome". Now you only see the picture and no text.

#### Length of time in which bug has been known to occur
Since the silicon photos were updated
https://github.com/vgstation-coders/vgstation13/pull/17354

#### Server revision
7393162dfc74cb636eae5f9156dce5f3df545a32

**Comment by Probe1** [comment]
Does this apply to both pictures the AI took and pictures that were taken by cyborgs?

**Comment by StreptoMutans** [comment]
both, it doesn't matter who took them

**Comment by jknpj** [comment]
I'll take a look at it, should be easy to fix
