### ISSUE TITLE
Medical spawner in dmm for Box/other maps is calling an empty parent list instead of a populated one

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17505]
obj/abstract/map/spawner/medical

![image](https://user-images.githubusercontent.com/8550416/36357383-52908b54-14cb-11e8-8966-6278dfe99186.png)

**Comment by Kurfursten** [comment]
That's not on Box, that's on the satellite deployment dungeon which is a dungeon created by the spy sat vault

At 25,37 on the glass table there are 2 stacked medical spawners. These should be changed to either medical/pills or medical/drugs

https://www.dropbox.com/s/2lxm7dpm3fru4nc/Screenshot%202018-02-18%2016.53.28.png?dl=0

**Comment by Probe1** [comment]
Is it not also happening at Centcomm?

Oh I see now.
