### ISSUE TITLE
Add an audio alert for cyborg station alerts.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17510]
Atmospheric Alarm in blahblah should have sound feedback so it isn't lost in the chasm of chat.

**Comment by Kurfursten** [comment]
No way this will get annoying when the goose is loose

**Comment by Probe1** [comment]
Well it can have a cooldown no big deal.

**Comment by SonixApache** [comment]
use the drone `beep beep` from factorio
