### ISSUE TITLE
The speech bubble that indicates a player is typing isn't working

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17517]
It should be but it isn't.  It used to be.  I'll test this.

**Comment by SonixApache** [comment]
We've never had this feature as far as I'm aware.

**Comment by ghost** [comment]
@SonixApache Probe is convinced we did.
I think his memory is failing due to his age because it's not a feature we've ever had

**Comment by Aurx** [comment]
Our speech bubbles are, and have always been, displayed when they speak.

**Comment by Zth--** [comment]
yeah, we never had this feature

**Comment by Exxion** [comment]
As everyone has said, we never had this
I'm also not sure it's even possible for people who don't use hotkeys
