### ISSUE TITLE
Can't add blood to a human with 0% blood

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17512]
#### Specific information for locating
I'm guessing here:
https://github.com/vgstation-coders/vgstation13/blob/2e0b33bf5e78773df8a72a6fdf85a0d7057dd71c/code/modules/organs/blood.dm#L266-L296

#### Length of time in which bug has been known to occur
Not a recent thing. Could be very old for all I know.

#### Server revision
Game: 956843085a7a5b417857547b64a6fc7a09526cb0 
Patches: 1f151d7a38ff2301172c5585b8ec3a972ca3efe6 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Sooose** [comment]
This bug has been in for at least a year, I've seen it several times.

**Comment by Pathid** [comment]
Figured out why this happens.
https://github.com/vgstation-coders/vgstation13/blob/4a38ac91690dfcababaf1ffa0ef633458b366d9b/code/modules/reagents/Chemistry-Holder.dm#L491-L500

The vessel is deleting the blood from ``reagent_list`` when the volume gets below 0.1u, just like any chem holder does, and it's not getting reinitialized by the blood procs.

**Comment by Pathid** [comment]
I thought of a couple solutions to this, but they involved remaking the blood datum instance, and it messed up blood data stuff unless I made a bunch of conditions for transferring it.

Next solution is, just not deleting the entry. This seems kind of ugly and non-OOP though.
```
/datum/reagents/proc/update_total()
	total_volume = 0
	amount_cache.len = 0
	for(var/datum/reagent/R in reagent_list)
		if(R.volume < R.custom_metabolism/2) //Used to be 0.1, changing this to custom_metabolism/2 to alter balance as little as possible since the default metabolism is 0.2
			if(R.id == BLOOD && ishuman(my_atom)) //Don't delete human blood data.
				if(R.volume < 0.1) //Safety in case REAGENTS_METABOLISM is messed with. This is the base human blood regen amount.
					R.volume = 0
					continue
			else
				del_reagent(R.id,update_totals=0)
				continue
		total_volume += R.volume
		amount_cache += list(R.id = R.volume)
	return 0
```
