### ISSUE TITLE
Feature Request: Allow wizards to pick race/let any race be wizard

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#17513]
As title says, allow wizards to switch their race as they spawn in to one of the many humanoid races (skeleton). 

As well as let nonhuman characters be selected as wizard at roundstart.

**Comment by SonixApache** [comment]
magic is a strictly human attribute

that's why they're the dominant species

**Comment by Aurx** [comment]
Just buy a staff of change and an apprentice scroll, silly.

**Comment by Dacendeth** [comment]
I think skeleton wizards would be okay for lich based gimmicks.

**Comment by Blithering** [comment]
Nonhuman wizards start a whole load of balance issues noone wants to wade through, the current system of automagically turning everyone who spawns as wizard human is fine.
