### ISSUE TITLE
getMob does not clear locked_to var

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#17525]
#### Description of issue
Teleported some faggot who was buckled into a bed.  He remained buckled 5eva.  

#### Difference between expected and actual behavior
Expected: Them to be able to move and stand.  
Actual: Utter immobility.  
Suspected to apply to other forms of teleportation, including those available to players.  

#### Steps to reproduce 
Spawn DrCelt.  
Buckle DrCelt to a bed.  
Right-click on DrCelt.  
Use get_mob verb on DrCelt.  
Laugh at DrCelt as he is unable to move under his own power.  

#### Specific information for locating
locked_to var is not being cleared.  

#### Length of time in which bug has been known to occur
I remember this sort of shit from like, 2012, man.  Not sure if it's this exact shit, but teleportation and beds have never gotten along.  

#### Server revision
Game: 0437d5f78554553cac791d917c15f982338dfc2f 
Patches: 1f151d7a38ff2301172c5585b8ec3a972ca3efe6 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [variations on this have happened for literally forever, fix it already please] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Anglosphere** [comment]
This also occurs with chairs. 

You can fix it by wrenching the chair into metal currently though. It unstucks whoever was sitting in it.

**Comment by Pathid** [comment]
Should we just have `teleport_to()` call `unlock_from()`?

**Comment by ghost** [comment]
WHY ME I WASN'T EVEN LOGGED IN THIS IS BULLYING
