### ISSUE TITLE
Issues cited from the discord

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#17520]
KammerJuicy - Today at 7:36 PM
>You can eat through a mask
>A single glass of beer makes you wasted
>You go from being fed to starving in 30 minutes
>You start freezing in seconds from being outside in space
>You can stand in temperatures that ought to boil all the water in you
>A highly experimental method of power generation is nothing more than shooting lasers and pumping cold gas
>Research is a pre-compiled point and cick adventure
>You can hear other people talking to you while you're in space

**Comment by ghost** [comment]
> You start freezing in seconds from being outside in space

I didn't want this; but try to fix it and @NigglyWiggly will shout at you

**Comment by Kammerjunk** [comment]
I was actually just making fun of the first thing brought up

**Comment by ghost** [comment]
>You can eat through a mask

Don't get me started

#15659

**Comment by Kammerjunk** [comment]
![image](https://user-images.githubusercontent.com/5942183/36395502-c7cd20dc-15b9-11e8-9e69-b5dffedc5a4e.png)
🤔

**Comment by Zth--** [comment]
>A single glass of beer makes you wasted.

Since when? This sounds like a bug

>You go from being fed to starving in 30 minutes

Yeah, I would lower it to 20 :)

**Comment by Kammerjunk** [comment]
Since never, depending on what you consider "wasted." It should still get you drunk, though. Two glasses of beer inside of 4.1 minutes would get you "wasted" (as in you would have trouble controlling your own movements).
50u of beer at 0.4u removed per tick means 125 ticks total. Slur starts after a common_data (combined datas of all ethanol reagents in you) of 65 and confusion starts after 130.

**Comment by Probe1** [comment]
Food riots when.

**Comment by FudgePucker** [comment]
So the joke is that none of these are bugs and 90% of them we already had PRs that were shot down for being stupid?

**Comment by Aurx** [comment]
The only one that's a reasonable issue is R&D.  
R&D just fucking sucks, since you can literally write a script to do it for you.  It's blatant make-work with no change in the results based on your skill or innovation.

**Comment by ghost** [comment]
Pretty much Fudge.

There's no solution that makes rnd better Aurx unless you're going to split out round critical products from the autism rnd

**Comment by Probe1** [comment]
That was my opinion when we discussed it in Discord.  RnD is an easy nook to stuff cool ideas into.  We've stuffed so much that is "critical" to round progression for some jobs that it feels like an obligation to do it.  To fix it we'd have to disassemble RnD game design rather than the code.  That's why we can't really "code" a better solution.

**Comment by Aurx** [comment]
Yes, that's why I'm calling it make-work instead of just a tedious slog

**Comment by Kammerjunk** [comment]
>So the joke is that none of these are bugs and 90% of them we already had PRs that were shot down for being stupid?

Silly question. Like I said, I was just making fun of the first item on that list. It's shitposting, not intended to be made into an issue. When he read it, he must have taken it as legitimate complaints or whatever

**Comment by Probe1** [comment]
FOOD RIOTS WHEN

**Comment by MadmanMartian** [comment]
I took it as legitimate complaints, yes. My bad.

**Comment by ghost** [comment]
>Kenya config preset
>Vendors and cargo food is gone
>Hunger is three times faster
>Hyperzine is insane
>Starvation always on
>Custom vends mapped in on all maps by default at last
>Chef is charging for food
>People are getting grab tossed over the tables only to get soap'd, cleaved, and gibbered to make more food
>Medbay is jealously defending corpses with lube and polyacid so they can butcher meat out of them and harvest the organs to eat

FOOD RIOTS W H E N

**Comment by Exxion** [comment]
Dead
Reopen if you want

Most of those are features anyway
