### ISSUE TITLE
WHAT I LEARNED IN TG SCHOOL IS

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#17539]
Hello it's me. I'm here to write a short list of things that /tg/ has that I think are neat and then suggest some changes based on what I experiences over there. Some of them are purely personal and others I think could really help the server. I was told this is okay I'm sorry that it's so long. 

### - Diagonal Movement
Now this might be controversial but it's really useful for movement. I hear it's just a one line change to enable it here but I'm sure some people wouldn't want it. I can see issues with it here, especially with our SANIC movement speed it would make dodging tasers, lasers, heck probably bullets too, completely trivial for a skilled player. But holding Left and Down and only moving straight down (as up & down seem to override the side movements on my keyboard) is really annoying. 
Along side this I think goes moving items that you are pulling. Being able to move things round corners when you trap yourself is very useful and stops people from gay baby jailing themselves.

### - Action Button Toggle Identifiers
You know those little action buttons in the top corner for your magboots, lightswitches, gas mask, whatever. On /tg/ they change colour when they're in their "activated" state! Really useful for knowing if you've remembered to turn your magboots on at a glance, that your flashlight is on or if your airtank is on (Toggling that is an action button there too, as well as that little UI thing that we have.) Or even stuff like that your jetpack is currently stabalizing. I know most of these already have telltale signs on their sprites within the action button, but some are a little ambiguous for me and a better clarification is just nicer. If you wonder what I mean I'll grab a screenshot later.

### - Exosuit Action Buttons
Okay so the Exosuit menu is nice and all, but having to keep it open all the time to cycle equiptment, toggle your lights, toggle internal air tank usage, that kind of stuff, is annoying. It takes up space! Also a nice big EJECT button in your main focus area is nice. 

### - Eating Sanity
If /tg/ can have it, why can't we. Can't eat through things that cover the mouth. Change vox breath masks into nose masks so they don't have their mouth covered. Plasmamen don't need to eat. Muh Immersions. On that menu that pops up when you drag someone onto you, add a toggle for toggling their mask, just like internals toggle, so you don't have to strip someones mask to feed them pills.

### - One Piece Hardsuits
Not sure what the proper name for these is, but all our hardsuits come in two seperate items, the body rig and the helmet rig. Merge them, give the hardsuit body a toggle which pops the helmet up. Really just a QoL/RP thing for me. No reason to walk around the station with your hardsuit helmet up, but when you have to manually take it off and hold it somehow it's very tedious. 

### - Bag Limits
It's 2018 guys. Why do our bags have a static item limit instead of a w_class limit? Why can I only hold 7 pens in my bag, but I can also just have 7 boxes and fill those with 7 pens each. Makes you think, right? But then you might ask, what about bags of holding? Just give them a 14 item slot limit of anything in the w_class they can hold. Or just a big number. Whatever you know.

### - Item Stacking
Hey you know plant bags? Coin bags? Mining satchels? You know how when you open them they show each individual item inside and it can take up your entire screen? I do. Look at [this](https://cdn.discordapp.com/attachments/245856976217702400/415493603352117248/Space_Station_13_2016-04-26_01-54-04.png). Why don't we just stack all similar things into one pile while in these kind of containers? We can even do this better than /tg/, because they do it by type, which means if you fill a chemistry bag with patches, they all stack up ontop of each other even if they have different names. Wait a minute, maybe I should have bug reported that...

### - Buckle Button
/tg/ has a buckle button. When you're buckled to something it tells you on your UI, and you can click it to get unbuckled. You can do this while both your hands have items. I like that. Some people won't. I'm putting it here anyway. 

## Mining Stuff

Let's be real that asteroid is pretty boring for miners. There's not really a lot of cool things to discover outside of a few little neat "hoo weee" vaults. Where's the excitement? The number of mobs is limited, most maps asteroids are small and just densely packed materials. While I don't particularily want a Lavaland, it's played out and the whole asteroid mining thing is cool but. Come onn. All you have to really do is strip mine and shoot a few monsters and then you leave for space to hunt worthwhile vaults. And the things you can buy with the $100000000 you make farming all those ores aren't even worth it.
So here's some ideas. They're a bit stealy from lavaland, obviously, but yeah.
- Nests. Like Lavalands Tendrils, the nests are home for the asteroid creatures. A goliath nest, a basalisk nest, a hivelord nest. They spawn the monsters on a timer of some kind. This means that if miners want they can more easily farm goliath plates, farm diamonds, hivelord cores, you name it. But, the nests can also be destroyed to drop something from a loot table. We'd have to think of what we could add to the loot table, Could be similar to xenoarch equipment, could be unique stuff, but mostly just stuff you think might crash land on an asteroid. A cool prototype space suit, you know. We can get creative and make it our own. 
- Bigger Asteroids. Let's just fill up the entire zlevel. either with a few big main clusters and little offshoots, however you want to design them, but make them large. We should encourage exploring. 
- Less dense materials. If the asteroids are bigger, we don't need these giant giant 20-30 ore clusters of plasma and iron. We can split them up, scatter them around, change how they're generated. It'll give miners have to work a bit more instead of just "woops lemme walk out my airlock and dig for 20 minutes to get 2000 ore to last the whole shift." 
- Asteroid Vaults. BIGGER. BETTER. COOLER. You know like, there's that one that can spawn the firebird. Why not make it bigger, add some fluff, make it look like a crashed Wizard ship. Shuttle wreckages, Cult bases, really stupid fluff things that have no purpose, biodomes from ancient civilisations. 
[If anyone could teach me how to try and map I would give it a go but I'd probably get frustrated as I heard the tools for it are not that great and I'm also special.]
- Change the damn Ore Processor. Why does this thing auto process everything in some sort of priority order list? Hey man. You want some plasteel? Better click it 200 times to bring it to the top of the menu and then hope you don't lag after turning it on. Oh you did? There goes all that plasma you mined into plasteel. Please, give us a way to specifically pick what we eject from it, and remove the stacking machine.
- The PKA. A miners go-to ranged weapon on the asteroid. We should borrow things from /tg/ here. Add upgrades for it so you can make it better at killing the mobs. But I think we should remove its ability to destroy rock. Melee mining > Ranged mining. Ranged mining removed a lot of risk of going through a wall into a goliath and being taken to brown town. 
- The Mining Vend. It sucks. There's nothing worth buying from it except Lazarus Injectors and poke balls. Maybe Mining drones. Am I the only one who uses these? Maybe. But I like them, steal /tg/s upgrades for them too, you can make them sentient there and a player can be your mining drone buddy. Posibrain rules or something. Add buyable medkits, utility things, we could brainstorm that stuff later, I dunno. Also make it NOT a vending machine and something unique so it doesn't have to have limited stock, I don't know if its still cheesable with a dead mouse but that was lame.
- Ore Stacking. Hey those little nuggets that pop out when you mine something. There's a lot of those right? What if you forgot to dump your ores in the processor for an hour and then dropped them all on the floor. Wouldn't that be a little laggy? On /tg/ it was very laggy! I broke the server doing it once! Woo. So how about instead of having them as individual nuggets, why don't we make them stack like sheets stack? Might be a performance boost for when there's a lot of ore debris! Also just makes sorting your ores a little easier if you only want to process a few or something. I dunno.
- Automatic Pickup. Having to manually click every single ore nug on the ground is tedius. And then having to click the ore box to transfer it every 4 seconds? Ugh. No thanks, I'd rather space myself. How about, if you're holding your ore satchel, maybe you've pocketed it or belted it. Swoop, you scoop up your ores as you go. Pulling your ore box too? Swoop. Into the ore box they go. No more click click click click, just mining.  But you forgot your satchel and you're just dragging an ore box? Get out of here, idiot. What are you gonna pick them up with? Change how Ripleys do this too. Just make them pick up ores beside + infront of them when they walk or something. 
- Mechs. Mechs mechs mechs. The asteroid is so small and denses mechs are overpowered. Previous things will make them less overpowered. But then comes other suggestions, mainly monstery type ones. Ripleys have no ranged weapons available, aren't the fastest things in the world and although they can take some hits, what use is it if you can't reach the mob. Hivelords are pretty annoying to kill in a mech, and I wouldn't want to run into a gaggle of Goliath in one either, seeing as I have to go punch to punch with them. Let's add a PKA for the ripley. Nothing too fancy, works like a normal one, give them a little combat potential, the asteroid is dangerous!

Think that's all for now, it's mostly about mining I think. Most of /tg/ was boring and wasn't exactly engaging. Their medbay is just using roundstart medics/the sleepers and autocloning people to full health, engineering is just toggling on 5 pumps and then starting an emitter. You can't even move the super matter crystal as far as I'm aware. It sucked, wanted to suicide bomb with it once and I couldn't do shit. Xenobiology is braindead, they removed 90% of the human element in it and it's just sitting at a console. Even added a way to add potions to slimes through it. Only thing you manually do is slime extracts. Their R&D is not desirable. Arbitrary point per minute system so you have to wait to unlock things. Takes around an hour to complete everything. They alsoed added a departmental system to protolathes, so science can't print guns unless they get the security protolathe from the Brig or spare board from HoS's locker. Which is overkill anyway because they also added "firing pins" which have to be installed in guns to fire them and protolathed guns don't start with them. Can't print the boards either, if you destroy the protolathes and spare boards that's it. Science is over. There's even a Department Circuit Imprinter, but then they added a normal, non-department one to robotics so you can still just print every other board you're not technically supposed to. I don't know, it's a mess. Implants are cool. We could steal some of their different implants. Cargo has this thing that's like, the crate you orders gets shot into the station in a drop-pod and it breaks the floor and blows up walls. It's incredibly dumb, I don't know why it's a thing. I don't know /vg/ botany like I know /tg/ botany so I can't comment on that. Didn't check out atmospherics much. Apparently you can set the inside of pipes on fire and its more efficient than using a burn chamber but I never tested it. Toxins is similar to ours as far as I know but their blue pumps go to 2533 so bigger booms are easier. I am the /tg/ god, you can ask me anything. (That was sarcasm.) 
Last but not least, CRAFTING MENU SUCKS. But you can make some cool things but THE MENU IS BAD.

**Comment by Kurfursten** [comment]
That certainly was "a short list of things"

**Comment by ghost** [comment]
Yci

**Comment by ghost** [comment]
This seems like good insight and should not be undervalued or dismissed.

**Comment by Dacendeth** [comment]
Give players diagonal movement or remove it from simple mobs.

**Comment by ShiftyRail** [comment]
- _Diagonal Movement_
Won't work with our movespeed as you said so yourself.

- _Action Button Toggle Identifiers_
That is a neat idea. Actions buttons still runtime a lot and we _don't even know why_ though.

- _Exosuit Action Buttons_
 Same with the previous, neat idea.

- _Eating Sanity_
Goofball no goofing.

- _One Piece Hardsuits_
Why didn't I thought of that. Genius.

- _Bag Limits_
Will be much harder to do then what it looks like if we don't want it to be half-arsed.

- _Item Stacking_
Same with the above. Neat idea but more work than what it looks like imo.

- _Buckle Button_
Up there with a resist button flashing when needed, would be very nice.

Overall, thanks for the suggestions.

**Comment by ghost** [comment]
If you wanted one piece hardsuits, wintercoat code basically does that.
Gonna disagree with one piece hardsuits though

**Comment by ghost** [comment]
Why is that?  I really like codebases where you can use them separately, but can attach them into a functioning one piece suit.

**Comment by ghost** [comment]
It's only 2000 words if you want I can go into depth and probably write a dissertation on everything. Thank you for the tags. 
I'd like to know why you disagree with the one piece hardsuits though too Celt. It's very nice.
The mining section is really long too I know, I just feel like the asteroid has been slowly catered towards xenoarcheologists as it's our special job that I've never seen anywhere else, leaving miners to just be things that get in their way. 
I will stand by eating sanity forever because muh immulsions. But I will admit the only reason it REALLY works on /tg/ is their chem system is mostly patches and sleepers, whereas ours is cryo and pills. Also they do have some special gas mask subtypes that you can have as internals AND eat with, such as their Welding Gas Mask, while also having an implant which allows you to use internals without an internals mask. 
I'd like to add to this all as I get more acclimated to /vg/ if it's okay. Learning and sharing from other servers is important, we're all unique in our own ways but that doesn't mean we can't borrow, steal and consume others, as long as we do it in our own way. Recently /tg/ also took how our AME works and replaced their AME. Which, balance wise was a good choice because their old AME was incredibly broken and overpowered.
Also races, they have a lot of races and some of them are pretty cool. 

Edit: Let me add that only Hardsuits are one piece. All softsuits are two piece. That means the basic EVA suit, the void suit, the syndicate soft suit, a few others.

**Comment by FudgePucker** [comment]
>eating sanity

I know you been banned for a year, but we already have had this argument. NO.

Also its not a sanity issue, there is flavor text added for when you eat with a mask on. Its not an over sight, its not a sanity issue, it is working as intended.

If you want this issue to not divulge into shit flinging I recommend you just remove it, before the medbay lynch mob gets here thirsty for blood.

**Comment by ghost** [comment]
Sure that looks like a lot of cool stuff, but we're missing the most important feature that's in other codebases, being able to roll down jumpsuits and sleeves

**Comment by Mothblocks** [comment]
Moth people W H E N.

I've been playing a lot of /tg/ lately and one thing I like is that they got buttons for, like, everything. And everything just looks and feels nice. Buttons slide in, everything has a nice sound to it, etc.

**Comment by Intigracy** [comment]
Up and down overriding side movement is the dumbest thing ever and should have been fixed before that movement change was merged.

**Comment by ghost** [comment]
Gotta admit I don't care for moth people, fly people, or lizards. But it's their non-roundstart races that are cool. Androids, Synths, Dallahan, the way their Slime People work, they're cool as hell. 

Also I did mention about the medbay issue with eating sanity. However, in the couple of rounds I've been observing and playing, I've noticed that the few doctor statics focus a lot more heavily on the cryo tube meta than a pill and dump meta. Personally, as an old medbay player this offends me heavily, but I  would still root for not being able to eat through masks. But, I respect you've had this argument before and I will drop it here.

Oh yeah, also let's steal titanium so we can build shiny white walled things, and the build-your-own-esacpe-shuttle system they have is neat, along with the various different escape shuttles the captain can purchase. Little things like these are purely fluff but they make for different experiences at round-end. I wish I had screenshots of any of the shuttles I built while playing but due to the /tg/ nature I either survived and forgot to screenshot it or it all got blown up by someone just before it was finish.

**Comment by SonixApache** [comment]
🔫

**Comment by jknpj** [comment]
![unknown](https://user-images.githubusercontent.com/17928298/36536214-e34a9f4a-17aa-11e8-9999-c06cb4f5d120.png)

The buckle up HUD is part from a system called screen alarms, i ported it to a branch of mine earlier this year but i don't plant to touch it any time soon so if anyone wants to work on them it's on my screen_alarms branch

**Comment by Kurfursten** [comment]
I always thought it would be more fun to revive the fish-head people idea from years ago than to make another IPC/android race. Because the concept is the same (robot body) but it's an old /vg/ original idea and detachable head is neat.

That said my idea backlog is too big for a whole race atm.

**Comment by ghost** [comment]
the Dallahans on /tg/, i think they're called that, have a seperate head and body. You see through the head and move with the body, so you have to carry your head around to do anything. It's really weird and only like half-implimented but you can play as it still with their Prides Mirror which lets you pick almost any coded race. Only ever seen someone else be one but they documented it to me sort of. 
I like that idea though, it's a different spin on it.

**Comment by Blithering** [comment]
Screw Dallahans, I just want a constructed robot body spider bots can attach themselves to.

**Comment by Anton-Kr** [comment]
B I L L 
I 
L 
L
