### ISSUE TITLE
Discussion: Should we remove/change being able to move action buttons?

### ISSUE THREAD

**Issue by Mothblocks** [d3athrow/vgstation13#17543]
Action buttons are cool, but I find myself a lot of them time accidentally dragging them for whatever reason. Then, I can never get them to line up again and it bugs me the whole round. What's the use of this feature? Does anyone use it? Am I just autistic?

**Comment by Probe1** [comment]
No reason to remove them when you could just add a preference setting to lock them on a per user basis.

**Comment by Mothblocks** [comment]
I was thinking a preference was a good middle ground but I reiterate the question on if anyone actually uses this feature.

**Comment by Probe1** [comment]
I don't and only know it exists because of the runtimes.
