### ISSUE TITLE
All entries in the "Choose disabilities" menu are set to "No" even if they're actually enabled

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17555]
#### Steps to reproduce 
- Setup character
- Character settings
- Handicaps: [Set]
- Set all options to "Yes"
- [Done]
- Handicaps: [Set]
- Notice how all entries are set to "No"

"Save setup" doesn't affect it. The changes are actually applied, and you spawn with the chosen disabilities.

#### Length of time in which bug has been known to occur
Not a clue.

#### Server revision
Game: 18eb936bb4b5a676c3f5e58e80217caf5dcd87c2 
Patches: 1f151d7a38ff2301172c5585b8ec3a972ca3efe6 
Also happens locally.

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Dacendeth** [comment]
Not suggesting it's related but as for length of time i can say i noticed this whenever veganism was added to the list.

**Comment by Aurx** [comment]
Well that identifies the cause, then. 
Fucking vegan hacktivists trying to whitewash their degenerate subculture.

**Comment by DamianX** [comment]
Magically doesn't happen anymore
