### ISSUE TITLE
Emergency shuttle sound when it arrives at a destination is ridiculously loud

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17557]
Needs tweaked by like 25%

**Comment by ghost** [comment]
![54efgt4e5g6t45e](https://user-images.githubusercontent.com/20872793/36520945-b1cd973e-1759-11e8-8066-c9bd2f4b4540.gif)

**Comment by ghost** [comment]
Hahahahaha Nigga How Are Loud Noises Even Real Hahahahaha Nigga Just Turn Down The Volume Close Your Ears NIgga

**Comment by Probe1** [comment]
@HarseTheef 

![image](https://user-images.githubusercontent.com/8550416/36521156-427fadf4-1763-11e8-8c63-51c3a1df55b2.png)
