### ISSUE TITLE
Molotovs thrown by non-mobs aren't logged

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17569]
#### Steps to reproduce 
- Put molotov in custom vending machine
- call throw_item()

```
x4 drinks.dm,1235: Cannot read null.attack_log
  proc name: throw impact (/obj/item/weapon/reagent_containers/food/drinks/throw_impact)
  src: Uncle Git\'s Special Reserve (/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey)
  src.loc: the floor (202,260,1) (/turf/simulated/floor)
  call stack:
  Uncle Git\'s Special Reserve (/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey): throw impact(the Dwarven Mining Equipment (/obj/machinery/vending/mining), 3, null)
  Uncle Git\'s Special Reserve (/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey): hit check(3, null)
  Uncle Git\'s Special Reserve (/obj/item/weapon/reagent_containers/food/drinks/bottle/whiskey): throw at(Slick Packer (/mob/living/carbon/human), 16, 3, 1, 3)
  the Dwarven Mining Equipment (/obj/machinery/vending/mining): throw item()
```

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/209e5e38f38c0cb713ae3ca246f2914f868e0ef9/code/modules/reagents/reagent_containers/food/drinks.dm#L1235

#### Length of time in which bug has been known to occur
#17028

#### Issue bingo
- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
That's hilarious.  The vend throwing molotovs.

**Comment by DamianX** [comment]
@Exxion did you fix this?

**Comment by Exxion** [comment]
I believe so, if the server has been updated to at least 512.1428
It still won't log what threw it, though. Only what it hit.

This also applies to molotovs thrown by mobs if they hit dense non-mob atoms. Fixing that would require substantial changes to the code for throwing objects.

**Comment by DamianX** [comment]
Oh, then no. We should be running 1426

**Comment by nervere** [comment]
Tested, no longer an issue.
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/3a3bfa65-5e7f-4fc1-90bf-199705b1d7fa)
