### ISSUE TITLE
You can bypass the nuke disk check for vending machine recharge packs by placing it into a container

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17566]
#### Steps to reproduce 
- Try to put nuke disk into empty recharge pack
- You can't
####
- Put nuke disk inside a coat
- Put coat inside empty recharge pack
- You can

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/209e5e38f38c0cb713ae3ca246f2914f868e0ef9/code/game/machinery/vending_packs.dm#L29

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
There even is a `atom/search_contents_for` proc.
