### ISSUE TITLE
Custom vending machines cannot throw items

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17567]
#### Steps to reproduce 
- Place something in an empty recharge pack
- Fill a vending machine with said pack
- call throw_item() on the vending machine

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/209e5e38f38c0cb713ae3ca246f2914f868e0ef9/code/game/machinery/vending.dm#L1079
```
x5 vending.dm,1079: Cannot create objects of type /obj/item/weapon/grenade/smokebomb.
  proc name: throw item (/obj/machinery/vending/proc/throw_item)
  src: Sales (/obj/machinery/vending/sale)
  src.loc: the floor (219,264,1) (/turf/simulated/floor)
  call stack:
  Sales (/obj/machinery/vending/sale): throw item()
  Sales (/obj/machinery/vending/sale): process()
  Machinery (/datum/subsystem/machinery): fire(0)
  Machinery (/datum/subsystem/machinery): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing()
```

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Zth--** [comment]
someone should close #15949 since it's a duplicate and this one has more info
