### ISSUE TITLE
Derelict Solar Panels produce 0 power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17571]
(WEB REPORT BY: reviire REMOTE: 172.93.109.202:7777)
# Revision
d5202fd7861aecd67d48bbda32f9cef3520ae959

# Description
The solar panels on the derelict don't produce any power by default. Produces 0 power until the solar panels got their glass replaced. In this case, it was replaced with reinforced plasma glass.
# Steps to Reproduce
Go to derelict, use solar panels.
# What you Expected
Power.
# What Actually Happened
No power.

**Comment by Probe1** [comment]
You know better you rascal.  You didn't even post what map this is on.

**Comment by Reviire** [comment]
It was on Box nerd

**Comment by Kurfursten** [comment]
what was the solar rotation angle?

**Comment by Probe1** [comment]
Can't reproduce.

**Comment by Exxion** [comment]
Someone reply to this (or just open a new issue) if it happens again
