### ISSUE TITLE
MoMMI phantom action buttons

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#17579]
#### Description of issue
Playing MoMMI I noticed three action buttons on the corner. One was for toggling a voice changer, one for selecting the icon of a mask, and one for pushing that mask aside. No noticeable changes while changing these.
Then after using my inbuilt flashlight an action button for it appeared.
Then after using a flashlight from the floor another icon appeared. I noticed this allowed me to toggle that flashlight even from a few tiles away.

The items that weren't on my inventory were below the buttons, while the flashlight was above.
![buttons](https://user-images.githubusercontent.com/13305885/36574992-150ae298-1827-11e8-8719-561d0de332c4.png)

Thinking back on it, the round was traitor and I hope I wasn't messing with someone else's gear from far away.

#### Difference between expected and actual behavior
I would expect the buttons to work only with internal tools, or at least from a reasonable distance. Or make this officially a feature.

#### Steps to reproduce 
Something like taking or getting near an item with action buttons, not sure

#### Length of time in which bug has been known to occur

This didn't happen eleven days ago

#### Server revision
4732d633d0a72e4457ea8949076feaf6106739a8

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
@jknpj

**Comment by jknpj** [comment]
my bad, i'll put up a patch for it
