### ISSUE TITLE
Defficiency medbay machines don't show the open maintenance panel overlay

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17585]
#### Steps to reproduce 
- Apply screwdriver to any of the things changed by #17471
- See nothing changed

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
Pretty sure this has always been the case

It also applies to unchanged medbay machines like the chemmaster and chem dispenser, all the virology machines, all the genetics machines, plus many other machines in general! The food processor, the gibber, the egg incubator, etc

**Comment by DamianX** [comment]
Well, I noticed this happening with the vending machine. That one does display an overlay, if memory serves

**Comment by Kurfursten** [comment]
Yes, that one *would* lose its overlay since vendors do get special screwtoggle overlays.

I can look into it, but someone might want to make overlays for all the machines (vendors actually each get a custom overlay to suit their design)
