### ISSUE TITLE
Latejoin trader spawned on the arrival shuttle

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#17593]
#### Description of issue
TITLE

#### Difference between expected and actual behavior
I thought I was supposed to be a flying chicken not a normal arrival.

#### Specific information for locating

My trader alternate title was vagabond and i arrived when the emergency shuttle was 4 minutes away, there were no other traders if any of this info helps. 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
I believe I have a fix for this, in testing now
