### ISSUE TITLE
MoMMIs get stuck with flashlight spells if they move flashlights

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#17600]
#### Description of issue

When you pick up Flashlights as MoMMI, you keep the spells. You can toggle the flashlights on/off from anywhere

#### Steps to reproduce 

1. Be MoMMI
2. Move Flashlight
3. Have eternal control over it

https://ibb.co/nbkCdH

#### Server revision
2f2461e89cda8de7db0acc08542be79d5acf79a2

**Comment by DamianX** [comment]
Should be fixed by #17588

**Comment by Pathid** [comment]
@DamianX Seems it was.
