### ISSUE TITLE
Graphics Issues on Mech Graveyard

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17607]
(WEB REPORT BY: leapthatwall REMOTE: 172.93.109.202:7777)
# Revision
cdb9f184780a1b5d20a9aeb4d472c3c99af1e8fa

# Description
When you arrive at the mecha graveyard, the space around it looks like a you're on a shuttle in motion. 
# Steps to Reproduce
Go to the mecha graveyard.

# What you Expected
Space to look like space!

# What Actually Happened
Space looked like space when you're moving at incredible hihg speed.

**Comment by Kurfursten** [comment]
not a bug, it's a feature
