### ISSUE TITLE
Metaclub: Shuttle Landing Projects Flames Into Vox Outpost

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17601]
It's on an entirely different Z level, I have no idea how this could happen.

@Kammerjunk didn't see the flames but observed the box it lit on fire afterward, it sent a torrent of those blue fire effects up the main hallway of the outpost, concentrated near the 4-way intersection

**Comment by MadmanMartian** [comment]
the blue flames hit the teleport landmark, so they do what somebody falling out of the shuttle would do

End up in some other place on another Z level that's not the asteroid or the main station. Because the metaclub vox station is in 'deep space', it's in a valid zone to fall into.

**Comment by Kurfursten** [comment]
Gonna put this out there and it may be unpopular: I think we should move that trader base off deep space.

* Powergamers can simply count out how many tiles they need to go to get a roundstart salvage shuttle guaranteed
* It's the ultimate rapecave because there's no radio there ever
* An inconvenience to the traders, too, because no radio means they can't advertise
* This Issue

**Comment by Probe1** [comment]
I wanna make a self contained tradepost inside a big ship.  Can we do that for Meta?

**Comment by Kurfursten** [comment]
As long as you make sure its landing position is CLEARLY DEFINED at the dock so people wandering around the station don't get hit. Blinking airlock doesn't help from more than 7 tiles away - I nearly gibbed a miner tonight.

**Comment by ihadtoregisterforthis** [comment]
Saw this happen with the escape shuttle on Box. The fire was on the derelict z-level with no apparent pattern, just streams anywhere.
![dude paralax](https://user-images.githubusercontent.com/13305885/36641921-75fddc5e-1a16-11e8-8b13-ee2fcbdb860b.png)

**Comment by Exxion** [comment]
This was fixed by #17669
I think
