### ISSUE TITLE
Ventcrawling pipe overlay is buggy to near uselessness

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17609]
#### Description of issue
The pipe overlay disappears when you ventcrawl a screen-length away from where you entered the pipes, and only reappears sporadically.

#### Difference between expected and actual behavior
Expected the overlay not to disappear.

#### Steps to reproduce 
Try ventcrawling past a screen-length away from where you started.

#### Specific information for locating
Client version is 512.1408.

#### Length of time in which bug has been known to occur
Pretty sure this wasn't happening a couple weeks ago.

#### Server revision
Game: cdb9f184780a1b5d20a9aeb4d472c3c99af1e8fa 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Pathid** [comment]
Not even a screen-length sometimes, either. What appears to happen is the pipes bug out into 4-way manifolds for a split second and then disappear.

**Comment by Probe1** [comment]
Can't reproduce on live.  I'm using latest stable sooo I'm gonna take a wild guess as to the cause.

**Comment by Pathid** [comment]
Fixed by updating to v512.1411. Closing this.
