### ISSUE TITLE
Ruins show up on holominimaps

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#17611]
![image](https://user-images.githubusercontent.com/7573912/36641662-c6ca2fda-1a33-11e8-99d5-ed43d780dbed.png)
some asteroid ruins show up on the holominimaps, yet the tunnels don't show up. Surely we have the ruins generate a bit later so they don't show up, right?

**Comment by Pathid** [comment]
There's apparently a flag called NO_MINIMAP for making turfs invisible to minimaps.

**Comment by DeityLink** [comment]
Yeah but then they'd just leave a hole instead of a floor.
