### ISSUE TITLE
Barricade + Wooden door = near invulnerable door.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17614]
(WEB REPORT BY: reviire REMOTE: 172.93.109.202:7777)
# Revision
e902e55bf9fab14bdf9e952389fdea986a50fdb1

# Description
The wooden door prevents alt-clicking the tile to interact with the barricade, while the barricade blocks any sort of interaction with the door. Can only blow it up.

# Steps to Reproduce
Door, barricade.
# What you Expected
To break the barricade.
# What Actually Happened
The best combo sinced slicing and bread.

**Comment by Accipitermaris** [comment]
Resin Doors Part 2: THE CREW STRIKES BACK

**Comment by Pathid** [comment]
Trying to reproduce this locally. This kind of barricade and this kind of door? Except the barricade was under it?

![223](https://user-images.githubusercontent.com/31839805/36758741-21e119be-1bca-11e8-8fb5-d19953864553.PNG)
