### ISSUE TITLE
Asthmatic wizards don't get an inhaler

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17622]
#### Steps to reproduce 
- Roll wizard
- Have an asthma attack
- Die

#### Specific information for locating
#17228

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Ephx1** [comment]
> DnD nerds don't get their inhalers

good, losers
