### ISSUE TITLE
mecha graveyard destination disk failure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17626]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
0638086db473057fa2be88ecaecabc6af7445a18

# Description
player reports the mecha graveyard destination disk would no add the mecha graveyard to the destination list of the trader shuttle
# Steps to Reproduce
slap the shuttle comp with the mecha disk
# What you Expected
to add the destination
# What Actually Happened
it did not, had to bus it in for him

**Comment by Probe1** [comment]
@Kurfursten

**Comment by Kurfursten** [comment]
This isn't a bug

Trade the disk, you can't use it yourself
