### ISSUE TITLE
Research resets to 0 on network sync

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17651]
(WEB REPORT BY: fadyftj REMOTE: 172.93.109.202:7777)
# Revision
8f110a5c79824da13621c747d40ef875c63a81ef

# Description
All research levels reset to 0 when attempting to sync database with network

# Steps to Reproduce
Press "Sync database with network" on research console

# What you Expected
I expected the research to be synced up with the network

# What Actually Happened
Gee whiz I wonder what happened

**Comment by StreptoMutans** [comment]
The Servers were at a nice 100 degree because the cooling was fucked

**Comment by Probe1** [comment]
Thanks @StreptoMutans
