### ISSUE TITLE
Mined turfs on the snow gateway mission dont have air.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17672]
(WEB REPORT BY: boosterrooster REMOTE: 172.93.109.202:7777)
Likethe title says. Once you mine the walls on the snow gateway mission the turfs under them dont have air. This conflicts with the rest of the turfs having air.

**Comment by unid15** [comment]
To be clear, the mission isn't in the game yet, this was just me live-testing (:smirk:) #17647

**Comment by Probe1** [comment]
heh.  Yeah I know.  Also snow turfs aren't even cold for whatever reason.  @DrCelt told me I used the wrong turfs.
