### ISSUE TITLE
Monkeys can pick up spacepod frames pieces.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#17671]
#### Description of issue
Normally clicking this rotates the piece, but if you're a monkey you pick it up instead.

#### Length of time in which bug has been known to occur

Happened a few days ago

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
Greasemonkeys

**Comment by Dacendeth** [comment]
Fixed by something.
