### ISSUE TITLE
CAMERANET_ENGI is assigned but isn't viewable from any console

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17693]
The cameras of engineering cyborgs, and now NT MoMMIs, are on this network. You might think the Engineering Cameras console would view this, but no.
https://github.com/vgstation-coders/vgstation13/blob/744949fc80c9f611df6b740d96ccf1fed00ac23e/code/game/machinery/computer/camera.dm#L149

**Comment by DamianX** [comment]
engineering cameras now have CAMERANET_ENGI
