### ISSUE TITLE
Lighting overlay visible with Alt+click

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#17699]
#### Description of issue
The color sprite thing used for the lighting appears on the Alt+click tab. It can't be clicked and it has no options. 
![go into the light](https://user-images.githubusercontent.com/13305885/36914328-abe5690e-1e2b-11e8-9e65-0e3ffc051665.png)

#### Steps to reproduce 
I noticed it on many if not all situations of alt clicks.
Byond version 511.1384

#### Length of time in which bug has been known to occur
No idea

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
The shadow realm strikes again.

**Comment by Exxion** [comment]
This might hold the record for longest-standing bug that would be trivially easy to fix
