### ISSUE TITLE
NT MoMMIs don't appear on cameranets they're supposedly assigned to

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17694]
Related to #17693, even when CAMERANET_ENGI is varedited into a camera console, only engineering cyborgs become viewable. NT MoMMIs' assignment here doesn't do anything apparently. Probably has to do with scrambledcodes.
https://github.com/vgstation-coders/vgstation13/blob/08636f057ab8a324806102cd0b9022c76a73f7c2/code/modules/mob/living/silicon/mommi/mommi_modules.dm#L46

**Comment by ghost** [comment]
Not a bug; MoMMIs shouldn't have cameras ever assigned to them for obvious reasons.

**Comment by Pathid** [comment]
I don't disagree with that. Makes me wonder what the point of assigning it was though.

**Comment by jknpj** [comment]
I also don't disagree with that notion i just added it as compromise. Also i think i found the issue on cyborg code:

https://github.com/vgstation-coders/vgstation13/blob/08636f057ab8a324806102cd0b9022c76a73f7c2/code/modules/mob/living/silicon/robot/robot.dm#L117-L123

**Comment by SonixApache** [comment]
aren't NT mommis not the same as standard-issue mommis?

**Comment by jknpj** [comment]
pretty much

**Comment by Kurfursten** [comment]
This is still an issue
