### ISSUE TITLE
Central Atmospherics Computer Doesn't Function Correctly 

### ISSUE THREAD

**Issue by Anglosphere** [d3athrow/vgstation13#17707]
#### Description of issue
The Central Atmospherics computer does not respond when clicking on individual air alarms, when changing Z levels, or when showing a detailed list. 

#### Difference between expected and actual behavior
When clicking on an individual air alarm, it brings it up, and allows the modification of values in the alarm. 

When selecting a new Z level, a new Z level should load with its map. 

When clicking on show detail list, a detail list should appear. 

#### Steps to reproduce 
Click on the CAC
Click on an air alarm
Wait 10 minutes
Nothing happens

Click on the CAC
Click on change Z level
Select a Z level
Wait 10 minutes
Nothing Happens

Click on the CAC 
Click on Show Detailed List
Wait 10 minutes
Nothing Happens. 

#### Length of time in which bug has been known to occur
Since https://github.com/vgstation-coders/vgstation13/issues/16654 probably. 
![ahhhhhh](https://user-images.githubusercontent.com/20270723/36930182-c92e8c00-1e50-11e8-8839-0395faaa69c2.png)

#### Server revision
Current

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
closing #16654 in favor of this, as this has more information

**Comment by ghost** [comment]
Thirding it. Borked.

**Comment by Inorien** [comment]
I think the problem lies in #16395, specifically changes to code/WorkInProgress/Mini/atmos_control.dm
I'll give it a good look in a couple of days

**Comment by BenjaminMichael** [comment]
This is a game balance crippling bug why not revert back before the change was merged?  That's what we used to do when stuff broke...
