### ISSUE TITLE
Getting turned into an "angry swarm of bees" by a Large Artifact mob transformer will ghost you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17702]
(WEB REPORT BY: archsunder REMOTE: 172.93.109.202:7777)
# Revision
8bcd1a7efd6c700cd26550d72b9da55b6e5a823e

# Description
You get turned into bees, couple seconds later you're a ghost, the bees stay behind as a simplemob and the badmins can't retrieve you

# Steps to Reproduce
1) Spend your time digging for autist statues until you find a large
2) Find out it transforms you and others into monsters temporarily
3) Get transformed into angry bees
4) Get ghosted

# What you Expected
To get murdered by my own artifact in an intended manner like any xenoautist would want
# What Actually Happened
sudden bee death

**Comment by Anglosphere** [comment]
Its a feature.

**Comment by Probe1** [comment]
fixit

**Comment by Kurfursten** [comment]
@Exxion No longer an issue as of 18562
