### ISSUE TITLE
Stun Balance Issue

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#17708]
Hello all,

 You can get zombie powder several ways, the easiest ways will most likely be to hack the medivends to roll for lucky trailmix drops. If that fails, ghetto chem via Groan's can be used to create zombie powder. Of course, if you're a traitor you can just get a pen, but that's pretty normal stuff.

Neurotoxin is a bar drink. To make it, you mix: 1 part Sleep Toxin, 1 part Gargle Blaster.

How do you make a gargle blaster? 1 part Gin, 1 part Vodka, 1 part Whiskey, 1 part Cognac, 1 part Lime Juice.

**Comment by Kammerjunk** [comment]
If you don't ebow+esword/blasmaflud/subvert/6bomb, you're getting banned for improper antagging

**Comment by ghost** [comment]
How 2 fix
Step 1: Move spawners to thunderdome
Step 2: Autobottxors shutters to arena open at 12:10 
Step 3: When one living mob remains, play scottlandforever.ogg then restart server at the end.
Step 3.5: Don't let anyone claw your gooch and handle your own consumables while wearing your tin hat and shaking uncontrollably
Step 4: Uninstall sphess and go play team fortress 2

**Comment by Probe1** [comment]
removeTRAILMIX REMOVE TRAILMIX yuo are the wrost idea put rare chem outside medbay not inside easy hack

**Comment by iFlashYou** [comment]
what?

**Comment by Probe1** [comment]
Hacking vends in medbay gets you trail mix pill bottles that have random pills.  In one of the pills there will be zombie powder which can be used for carpo toxin, which can be used for rare medbay chems.  It's a bit too cheeky to have rare stuff in the department for my taste but people enjoy it.

**Comment by ghost** [comment]
Absolute madman stance, animal datums is finished in 2555, carp are slightly fleshed out, the whole carp pheramones/husbandry system is made less shitty, and a zoo type area added to hydroponics or xenobio as part of a new wave of content allowing a more legitimate source than pill scrabbling and be a head tier banned soda buyouts.

More content, chloral bay isn't aids, people can get it if they want it, everybody's happy.
Edit: except for the maps where 'bio is hard id locked away from them cause people are fucking dicks.

**Comment by nuklearcellphoneg** [comment]
@iFlashYou Chloral was nerfed but there exists two arguably superior substitutes which are fairly easy to obtain. You can manufacture zombie powder as an assistant.

**Comment by ghost** [comment]
Who could've seen this coming?

**Comment by nuklearcellphoneg** [comment]
And y'know, I'm not going to say anything necessarily needs to be changed, but I'll definitely also do my best to make sure the recipes and locations of ingredients are common knowledge so they're fairly easy to obtain for everyone.

:^)

**Comment by Probe1** [comment]
@SarahJohnson489 code eet

**Comment by ghost** [comment]
Don't you have a 1v1, fists only, 5x5 rage cage fight club to run instead nuke ?

**Comment by nuklearcellphoneg** [comment]
No, normally I would just play chemist all day, but I just don't feel safe in there any more with the chloral nerf!

**Comment by Exxion** [comment]
Discussion dead
Reopen if necessary
You know the drill

Also that title and OP is awful
