### ISSUE TITLE
Ghosts cant view bodyscanner info

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17715]
(WEB REPORT BY: dacendeth REMOTE: 172.93.109.202:7777)
# Revision
8dcfbd52e5ece16620a5e941a6b4b1085cf700f1

# Description
I wanted to see stats on occupent in it.
# What you Expected
To see damage values.
# What Actually Happened
Nothing opened.

**Comment by DamianX** [comment]
too much sanity

**Comment by Pathid** [comment]
Feature loss. Ghosts could read them when they had consoles.
