### ISSUE TITLE
Scrubbers and Vents are on Three Different Frequencies on the Vox Outpost 

### ISSUE THREAD

**Issue by Anglosphere** [d3athrow/vgstation13#17722]
#### Description of issue
The Vox outpost has its scrubbers/vents on three different frequencies. Some are even on different frequencies inside of the same zone.

#### Difference between expected and actual behavior
I suppose this could be what the mappers intended, but I would assume they would all be on the same frequencie. 

#### Steps to reproduce 
Teleport to the Vox outpost
Examine the vars for the vents, or use a multi tool on them. 

#### Length of time in which bug has been known to occur
Unknown

#### Server revision
Current

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [x
![voxcpox](https://user-images.githubusercontent.com/20270723/36940043-576b65e8-1ef0-11e8-9646-90a9017f27a0.png)
 ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
You don't have to x the boxes.  Once the PR is made they become tickboxes and you can click on em.

**Comment by Probe1** [comment]
@Kurfursten Why is this?  It looks intentional to me all the scrubbers and vents are on the same two sets of frequencies.

**Comment by Kurfursten** [comment]
I am pretty sure it's an artifact of the old outpost. Some parts e.g. the cycling chamber and trade floor are ancient and didn't get remapped.
