### ISSUE TITLE
Why can't dead bees be picked up or put into lockers? Or be dragged into the disposal bin?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17720]
(WEB REPORT BY: tellossee REMOTE: 172.93.109.202:7777)
# Revision
31e7a93e9650334299b7d06c89588b54f5d703fc

# Description
You should be able to drag dead bees into disposal or transport a large number of dead bees in a locker or somthing. But right now you can't. you just have to move all the dead bees somewhere that can't be seen. One by one. Can't even put them in disposals.

**Comment by Pathid** [comment]
That's because they're not items or mobs, they're cleanable decals that happen to be movable. Use soap, space cleaner, etc.

**Comment by DamianX** [comment]
feature?

**Comment by Pathid** [comment]
Having potentially hundreds of dead bees as items or mobs would probably be a waste of CPU cycles. Making soap dissolve dead bees _seems_ like an acceptable design compromise, provided players get a way to intuit this instead of having to be told.

**Comment by Aurx** [comment]
Changing the sprite to make them look squashed, and making them immovable should do it.  If they look like a mess, people will treat them as such.

**Comment by groosbstrd** [comment]
I had no idea you cleaned them up with space cleaner and the like.
