### ISSUE TITLE
Proposed Fix For Hyperzine

### ISSUE THREAD

**Issue by chesse20** [d3athrow/vgstation13#17727]
When you first take hyperzine a meter below where the health and nutrition bars/makers are appears. While on hyperzine the meter slowly goes up. If the meter fills to 100%, your character will say woody's got wood over the intercoms.

**Comment by Aurx** [comment]
But power gay men would just take off their headset and walk away from intercoms at 99%.  
Clearly having hyperzine in your system needs to glue your headset to your ear.

**Comment by Mothblocks** [comment]
someone give me a single reason not to code this

**Comment by Daxalog** [comment]
If you add this.  Dont tell the playerbase what happens when the bar fills.

**Comment by Probe1** [comment]
Yikes
