### ISSUE TITLE
pAI Problems

### ISSUE THREAD

**Issue by Mothblocks** [d3athrow/vgstation13#17740]
This was discussed in an OOC of a round a day or so ago. Basically, there's nobody ever on the list for pAIs. Note the wording of there's nobody ever on the list, not that nobody ever wants to be a pAI. The problem with pAIs is that you have to specifically enable it in your config, but even then you still get a prompt. What I'm trying to say is, what's the point of the config option when either way you still have to accept a prompt? Why not just alert all the dead when there's a pAI slot open?

Someone can probably explain this better than me, I don't know.

**Comment by Probe1** [comment]
Copy borer, xenomorph code for chat sign ups for pAIs.

**Comment by jknpj** [comment]
Main issue is that you need to fill a fucking form to get in the list

**Comment by Pathid** [comment]
The only required field is a name. Even that could be reworked though I guess, totally possible the form itself is putting some players off.

**Comment by Mothblocks** [comment]
So can we just get rid of the form and config option and only have players type in their name when they sign up?

**Comment by Probe1** [comment]
It'd be nice to maintain the old system while streamlining it .. but yes.  Ideally you'd have players click sign up and be prompted to enter a name then another prompt to fill out additional details allowing them to skip that stage if they aren't interested.

**Comment by Ephx1** [comment]
Can the whole role sign up config just be switched to "Never, Ask, Always"? What the hell is the point of "Never, No, Yes, Always"?

**Comment by Probe1** [comment]
I think it's "Never, no (this round), yes (this round), always"

**Comment by Mothblocks** [comment]
@Ephx1 Do you mean change antag roles to do that too? If that's what you're saying, that sounds kinda cool. Could have some message like "You contemplate in your head to renounce your loyalty to NanoTrasen and join the Syndicate...do you accept this thought?" along with a timer so you can't grief it somehow.

**Comment by SonixApache** [comment]
it's weird that you can't call up the pAI config menu outside of actually interacting with a pAI.

**Comment by Intigracy** [comment]
Best solution is to put that entire prompt in preferences so they can set it once and then forget about it
