### ISSUE TITLE
Should the xenoarch suit have its current slowdown malus?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17741]
Its a recurring point being brought up and obviously people would rather use hyperzine than deal with any slowdown whatsoever.  Should we bring its speed up to mining hardsuit speeds?  Why does it even have a slowdown more severe than normal suits?  Are we fighting over some ancient ass bay code balance?

**Comment by DrSnips** [comment]
Xenoarch suits are currently really bad. Maybe make them like mining suits but have a conversion kit to give them the rad resist in exchange for speed like it is now. What I don't get is why are there usually double the amount of mining suits than xenoarch suits. You would think there would be more of a limit on the better suits than the shit ones.

**Comment by ghost** [comment]
It has rad resist so you aren't dead on the roid cause you proc'd a rad pulse the second it was generated and ate shit.

The amount are arbitrary, it really only needs more suits, lockers and field generators but it's pretty rare to have three xenoarchs as-is so that's just feeding back into the everyone has suits problem.

**Comment by DrSnips** [comment]
A few radiation patches added to xenoarch would help.

**Comment by ghost** [comment]
Don't those only give you an alert? People who aren't mad powergaming carrying a full chem fridge up their asshole can get a fatal dose.

**Comment by DrSnips** [comment]
Im not completely sure on how effective they are currently but a small buff to them giving the wearer x seconds of rad protection upon triggering would definitely cover things. However this doesn't really do much if the artifact you dig up is one of those 100x100 tile radiation emitters that makes the station internal bleeding and vomit bacon.

**Comment by ghost** [comment]
So can we agree on how about no?

**Comment by Dacendeth** [comment]
Compared to an engineers it has an extra 20 rad resist (100 instead of 80) but doesn't have all the other defensive stats while being slower too? That seems kind of silly.

**Comment by Blithering** [comment]
Didn't we have this discussion recently? 
As far as I can remember from the previous time this was brought up, the xenoarch suit is bad when compared to RIG suits, but good when compared to other softsuits, which it inherits its slowdown from. As to whether xenoarch suit should be remade into a RIG, meh. I'm not a fan of anything that would encourage scientists to snag the suit and then wear it all shift

**Comment by DrSnips** [comment]
Iirc yes but it was to completely remove the slowdown. This is more to being it in line with modern rigs.
