### ISSUE TITLE
Meta Trader Outpost Observations

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17755]
From spectating a shift, this is what I encountered. These are mostly notes to myself for a followup PR.
* Most people don't know how to use an APC layered under glass so we may just have to put a wall there anyway even though it will block some sunlight. Also, because load from the SMES can be prioritized over the APC, because of how the wiring is set up, you can awkwardly end up not charging your APC as you charge your SMES on auto.
* May need to rethink the positioning of the solar farm, because vault spawns can interrupt its solar array (comical).
* It might be a little too much to expect modern players to understand how the old Taxi portable SMES works. Could add an instruction sheet.

Fortunately, in spite of these issues the power consumption on the shuttle is still quite low so it's not a terrifyingly bad problem, but one that should still be rectified early.

Still on the fence about whether the solar farm should have a shuttle caller but I'll put it here to remind myself.

**Comment by Dacendeth** [comment]
I think maybe if one of the portable SMES at the solar farm was sitting unattached to the base I would have instantly realized all of them were the portable kind, maybe others would too?

**Comment by Kurfursten** [comment]
Also the gas out vent is on backwards
