### ISSUE TITLE
Invisible spray can turn supermatter invisible?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17761]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
c5f16ebcb97856efffeb9cb3f256f754b7f0d071

# this should be removed, because it shouldn't be possible to turn the supermatter invisible if it deletes anything that touches it.

**Comment by Pathid** [comment]
See #13936. Invis-spraying shards was left in under the condition that it always ashes the sprayer.

**Comment by Intigracy** [comment]
If a supermatter eats anything that touches it, how doesn't it eat the spray from the can

**Comment by MiniMeatwad** [comment]
yeah, if supermatter destroys anything that touches it, it should also destroy the spray from the can

**Comment by Aurx** [comment]
Yes, and invisible spray makes anything it touches invisible, so the supermatter annihilates the spray as the spray makes the supermatter invisible.  
This is basic logic guys, come on.

**Comment by Probe1** [comment]
I got mega shit for my compromise.  Sorry my dude this is gonna go nowhere.  I'll tag it as discussion though.

**Comment by Killette2** [comment]
I think you should put more reason to why it should be changed.

**Comment by Exxion** [comment]
Discussion dead for three months, reopen if necessary, etc.
