### ISSUE TITLE
Revived Changeling Heads Also Count as "Survived"

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17773]
An extension of #12435

A changeling head was able to get survival credit because he "sprung to life" on the shuttle... it didn't do anything of course, he was still just a head, but he got survival credit

**Comment by Probe1** [comment]
I don't know if that's a bug.

**Comment by Durgen** [comment]
Norris form when

**Comment by Probe1** [comment]
Been asking for that for YEARS

**Comment by DamianX** [comment]
It's totally a bug.

**Comment by Aurx** [comment]
IT'S A FEAAAATUUUUREEEEEEEEE

**Comment by Kevak** [comment]
Feature!

**Comment by Kurfursten** [comment]
We no longer have lings or survive jecties
