### ISSUE TITLE
Security Request Consoles Are In Low Traffic Areas Or Do Not Exist

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17788]
Box and Deff: RC is tucked away where it can't be seen. I've highlighted the visible range. Not that much of this range is taken up by tables reducing effective squares and it is all in low traffic areas.

Metaclub: RC is in a visible spot... but only the warden can reach it to read it.

Bagelstation: Requests console does not exist(?)
Packedstation: Requests console does not exist(?)

![untitled](https://user-images.githubusercontent.com/9782036/37203378-116526c6-2353-11e8-954a-e2e2f145d110.png)

**Comment by Probe1** [comment]
I have a plan.  We remove them because they failed as a concept.

**Comment by Kurfursten** [comment]
Gonna have to remove all of them in that case because the bartender was complaining his RC message wasn't received by sec today. As long as they're on the walls they'll confuse people.

You gotta leave the head ones though because people still use those for announcements all the time... and strip out the functionality to make requests to other departments since those RCs won't exist anymore.

**Comment by Accipitermaris** [comment]
yeah the head of staff announcements are prolly the only thing i see those consoles used for
