### ISSUE TITLE
PDA Station Map Bagel Missing

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#17799]
#### Description of issue

Check the tin.

#### Difference between expected and actual behavior

Wanted a PDA map. There was none.

#### Steps to reproduce 

Go to Bagel station. Buy a map.

#### Specific information for locating

See above.

#### Length of time in which bug has been known to occur

Since the station was baked.

#### Server revision

Game: cd8753420c36557ab296a9a5ee5db91c1659821e 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [czech] Issue could be reproduced at least once
- [czech] Issue could be reproduced by different players
- [czech] Issue could be reproduced in multiple rounds
- [czech] Issue happened in a recent (less than 7 days ago) round
- [czech] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

![image](https://user-images.githubusercontent.com/6540760/37236579-1db72526-23d7-11e8-9b29-c82518cde721.png)

**Comment by Probe1** [comment]
@DeityLink ?  Can you help with this?

**Comment by DeityLink** [comment]
yeah, on it

**Comment by DeityLink** [comment]
Actually this app needs a full rewrite for two reasons: requires too much work to maintain, and holominimaps are better overall.

So I'm thinking of replacing it with a button that spawns one. However that leaves the matter of the personal markers.

I'll deal with it when I can.

**Comment by Probe1** [comment]
Thanks 😄
