### ISSUE TITLE
Examining dead players no longer tells you if they have a soul or not.

### ISSUE THREAD

**Issue by toomykins** [d3athrow/vgstation13#17792]
#### Description of issue

examined someone, said "(s)he has no pulse..." so i assumed his ghost was still in his body, cloning says mental interface failure

#### Difference between expected and actual behavior

When dead players have left their body, it used to say "(s)he has no pulse..." and then something about their souls having left their body.

#### Steps to reproduce 

examine a ded player without soul.
think they do have a soul

#### Length of time in which bug has been known to occur
a few weeks/months now.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
Feature #16658
Reason is precisely that whether or not a player is in the dead body is not a good indicator of whether the player is there. Most people hang around as a ghost after death.

**Comment by Pathid** [comment]
@DamianX I'm not sure checking for a mind is immensely useful either. It lets you rule out monkeymen I suppose. It's a bit counter-intuitive that you can get more ghost info with severed heads and brains than with whole corpses.

**Comment by toomykins** [comment]
I dont see a positive side in getting rid of it. oh well

**Comment by nuklearcellphoneg** [comment]
So if their player is online, it always implies that they're in a state able to be cloned, basically?

**Comment by DamianX** [comment]
If the mob has a mind still assigned to it no message regarding souls is printed. Take that as you will.
"Their soul is departed" is printed for mobs that have been cloned or have had their mind transferred by some other means.
Ghosting does not transfer the mind, so "their soul is departed" is not shown. The clear win is that people won't assume "Oh, that guy has no soul, I won't bother cloning them" unless, in fact, that guy has no soul, and shouldn't bother cloning them.

**Comment by Pathid** [comment]
@toomykins The positive side is if you get the "soul has departed" message now it's proof-positive that they're never going to be clonable, it means they've already been cloned or that they're a monkeyman. 

Negative side is now the possibility of a dead player hanging around inside their corpse to communicate that they have a logged-in client is gone (unless they're put in a morgue tray). Currently it won't say that their soul has departed if they're logged out, or even if they've reincarnated as a diona or something. Becoming a new character leaves the old mind where it is.
