### ISSUE TITLE
Robotic limb/organ EMP feature request

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#17806]
We've all been there, you get a shiny new robotic limb or organ, take one step out of science and fail to spot two greyshirts having a harmless EMP grenade fight. 
As every metal part of you violently explodes off of your body, you look around you and notice that the cameras, APCs, and borgs haven't followed your example of how to act in an EMP situation and are just temporarily shut down.
I think robotic limbs would be more viable as an option if they too were rendered temporarily non functional in an EMP instead of dismembering/destroying themselves. 
This would still have the potential for hilarious deaths as a robot heart isn't gonna beat too well before it reboots, and a chief engineer with two dead legs crawling away from  an angry singulo would be a laugh, but it would make them seen as less of an outright detriment if they stayed attached and eventually regained function. Emagging robotic limbs could reset their behaviour to their current state for surprise EMP assassinations, I have never seen the current emagging of robot limbs used, and have no idea what it currently does.

**Comment by Pathid** [comment]
It makes them blow up instead of popping off.

**Comment by Dacendeth** [comment]
Yeah after a set amount of time they explode violently gibbing you and venting to space.

**Comment by MiniMeatwad** [comment]
yeah this should be added
