### ISSUE TITLE
dorf mommi spawner doesnt work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17805]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
cd8753420c36557ab296a9a5ee5db91c1659821e

# Description
the mommi spanwer for dorf does not work, it had power and metal, spawned a different spawner and that worked but not the dorf one
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by jknpj** [comment]
what it wrenched down? this is important. Nevermind the thing is straight up broken
