### ISSUE TITLE
Metaclub Casino/Voxship mapping derps.

### ISSUE THREAD

**Issue by Kevak** [d3athrow/vgstation13#17818]
This is technically two issues.

-The voxship's 'airlock' portion (the 2x2 zone lined with boltable airlocks and scrubbers) appears to be set to all access rather than trader access. The bolt buttons are trader access but the doors themselves are not. This seems unintentional and possibly like an oversight considering the rest of the doors in the ship are trader access.

-Vox Casino lacks a Vox Botany Locker. This means Vox traders spawn without the all important (and irreplacable) Minihoe. Making theft or other forms of Acquisition for a minihoe mandatory for vox planning on growing things. They also don't get a hatchet. Which is inconvenient but manageable via crafting. This seems like an oversight.

**Comment by Kurfursten** [comment]
Those doors not having trader access was intentional ~~to encourage people to bolt them~~

I'm considering only adding a minihoe and nothing else to the outpost though since @Probe1 has already complained at me for making the casino base too nice. It's hard to strike a balance between "a place people might actually want to spend their time" and "too nice". You can see in the original screenshot it was like a 3x4 room without even chairs. Maybe remove the ore furnace since you don't get a mining locker anyway and that wasn't in the original design.

**Comment by Probe1** [comment]
Get rid of that plasma beaker RnD thing while  you're there.

**Comment by Kurfursten** [comment]
Having a plasma beaker lets them make cryox and dexalin without need to give them a grinder (the original meta outpost had a grinder+plasma). I figured it wasn't too unreasonable since they no longer have access to the free sepia camera (xenobio item) or grenade launcher (R&D item?).

**Comment by Pathid** [comment]
Secret tip: You can kill weeds with phosphorus.

**Comment by Jubisloviu** [comment]
but you can grind plasma with just a mortar made out of a wooden bowl and a metal sheet
i honestly thought the entire point of vox traders was to live on a free society with sub-optimal stuff and get good shit throught trading
might as well give traders ion pistols and c-20r on their armories too

**Comment by Kurfursten** [comment]
We may have actually reached the point of absolute peak hyperbole. Someone has literally compared a *beaker* to nook ops gear. Screencapped for retrospect.

![untitled](https://user-images.githubusercontent.com/9782036/37260289-609fad34-255f-11e8-8673-3c2c81986a7b.png)

**Comment by Aurx** [comment]
A beaker WITH plasma.  That they could just mine trivially.

**Comment by Kurfursten** [comment]
The old outpost had a beaker WITH plasma WITH a grinder. You can see why it needed to go, given that they were practically starting out with a seraph.

For the record I _can_ sympathize with what Probe has to say about aesthetics but this thing where we type stuff like "damn, traders start out with their internals turned ON? how come miners have to turn on their own internals? might as well just spawn them with a pulse rifle" doesn't really even belong outside thread shitposting. C'mon guys.

**Comment by agentofzog** [comment]
Here's my issues with it
-no shutters anywhere, making it really easy to break in
-can't send it back to asteroid with the trader PDA (haven't tested if you can use the trader PDA at all)
-no table to put goods on, vending machine only, have to leave your safe space to do barter.
-no gps for figuring out where the hell the solar farm is even supposed to be

**Comment by CptWad** [comment]
is this an issue anymore? It appears to have been fixed and I cant find any vox casinos

**Comment by Kurfursten** [comment]
no

**Comment by Kurfursten** [comment]
@Exxion this was changed months ago
