### ISSUE TITLE
Engineering Cyborg has no Magnetic Gripper?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17845]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
4b3fe90d18ae3c1e54dcf9b4da32595e028017d1

"The engineering cyborgs magnetic gripper can now interact with things it's gripping (e.g. airlock electronics, tanks). It can also hold additional items such as table/rack parts, and mountable frames (for APC, air alarms, ...)"

engineering cyborg has no magnetic gripper?

**Comment by Pathid** [comment]
Magnetic gripper is not standard-issue. It's a very resource and research-intensive upgrade.

**Comment by jknpj** [comment]
![grippers](https://user-images.githubusercontent.com/17928298/37437796-e116c7ac-27cd-11e8-8388-499932939044.png)

You need to buy your monthly pomfcoin bag and then try to get one from pomfboxes
