### ISSUE TITLE
[Discussion] Do you want a Dionaea rebalancing following #17820?

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#17846]
Simply put, #17820 is going to halve diona health regeneration in full light from what it is now, and cut it off completely in less than 80% illumination. This is going to cut directly into what they're good at now, fighting simple mobs. Reverting, or partially reverting the hyperzine regen nerf from #14721 to compensate (#17821) hasn't shown to be popular so far, so I'm looking for opinions and ideas. Of course, feedback after #17820 goes live will probably be more useful.

**Comment by Blithering** [comment]
so long as carrying a torch or lantern provides that 80% illumination they should be okay at fighting mobs still. If you wanted to give them a bonus to make up for the cut regen, you could have them benefit from the full speed bonus of hyperzine I guess. Or if you wanted to do something fun as a racial bonus, you could give them an ability to root themselves to increase regen back to the bugged level at the cost of all movement, with some kind of delay on rooting and unrooting maybe?

**Comment by Pathid** [comment]
>you could have them benefit from the full speed bonus of hyperzine I guess

The thing with that is I was mistaken before. #17822 is not going to take away hyperzine's ability to ignore racial speed penalties.
