### ISSUE TITLE
Minebot needs manual resetting all the damn time

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#17847]
#### Description of issue
Once a minebot in collect mode collects, it stops collecting until reset to collect mode.  

#### Difference between expected and actual behavior
Should, and used to, be a ore-roomba.  

#### Steps to reproduce 
Buy a minebot.  Turn it on.  Mine shit.  Watch as it grabs one bundle of ore and no more.  
Click it once to turn it from collect mode to collect mode, and it grabs ore exactly one more time.  

#### Specific information for locating
search_objects is set to 2 when entering collect mode, but the action of collecting ore sets it to 0 so it stops looking for ore.  
This is because the minebot's call to AttackingTarget, where it calls CollectOre, calls super, which sets search_objects to its initial value.  For a minebot, this is 0.  

#### Server revision
Game: 2fbfe6b70f8bc95112b02d0b37c47db508faa84c 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
@Pathid #17548

**Comment by Pathid** [comment]
I was about to say that. Whoops.
