### ISSUE TITLE
Mutate spell's cooldown can be bought 4 times but only the first is effective

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17842]
#### Steps to reproduce 
- Be wizard
- Buy mutate
- Buy cooldown twice
- Notice how the cooldown stays the same and your points go down nonetheless

#### Length of time in which bug has been known to occur
Forever?

#### ???
I should only be able to buy 1 cooldown upgrade or the cooldown should be decreased correctly (no).

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
ngl that's a good thing mutate is awful design wise.

**Comment by MadmanMartian** [comment]
the difference is 1 second overall. Each rank up is 25 deciseconds off (charge_max is 400, cooldown_min is 300)
