### ISSUE TITLE
The FPRINT atom flag is useless

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#17848]
#### Description of issue

Behold this ancient shitcode
https://github.com/vgstation-coders/vgstation13/blob/54e1bfda9afa3d483743b245d843a4d1e84855c4/code/game/atoms.dm#L652
`FPRINT` is defined as `2`
if flags is `0`, then `!0 == 1`, and `1 & 2` is `0`
if flags is `1`, then `!1 == 0`, and `0 & 2` is `0`
if flags is `2`, then `!2 == 0`, and `0 & 2` is `0`

#### Difference between expected and actual behavior

Atoms without FPRINT shouldn't receive fingerprints

#### Steps to reproduce 

They do

**Comment by Aurx** [comment]
Literally move one closeparen and it works.  
Some newcoder should come get their bug valids.
