### ISSUE TITLE
Uvents can't be switched to siphon

### ISSUE THREAD

**Issue by GelatinousGlob** [d3athrow/vgstation13#17865]
#### Description of issue
Uvents can't be set to siphon/draw. Tried with both air alarm and with a tank control computer which simply didn't recognize the uvent.

Box station

#### Difference between expected and actual behavior

Uvent should switch to siphona nd turn red when switched in an Air alarm.

Uvent should show up on the tank control computer, other devices worked but not the uvent

#### Build uvent, go to air alarm, try to change blowing to syphon, watch it do nothing.

Use multitool on uvent, try to input frequency and tag into tank control computer, doesn't work.

#### Length of time in which bug has been known to occur

Pretty sure they still worked a month or two ago (but im not 100% positive)

#### Server revision

3474f9907b23dbc944a34e55986753f9390cc793 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
This has been the case for as long as I can remember

It also appears to, in fact, be a bug, not a feature request
In `air_alarm.tmpl`, clicking on the button that displays pump direction sends a command of `set_dir` with a value of either `siphon` or `release`, when it *should* send a command of `direction` with a value of 0 or 1, respectively
It's likely that someone refactored air alarms at some point and forgot to change the `tmpl`

**Comment by Exxion** [comment]
Nope. Actually, this has been broken ever since air alarms were moved to NanoUI. It wasn't a refactor. It was just that when the NanoUI template was ported, nobody noticed that the command for that was wrong.
That was five years ago

EDIT: On second thought, I believe this was actually a case of someone forgetting to add code to the air alarms to handle the commands sent by NanoUI rather than the commands themselves being wrong
But it's an academic distinction since it still never worked

**Comment by Exxion** [comment]
Probably not a good idea to fix this until siphoning vent pumps have been "fixed"
So that's a reminder to do it later

**Comment by Eneocho** [comment]
works fine
