### ISSUE TITLE
Laser Heater and Cooler don't work

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#17868]
#### Description of issue
Laser heater and its cold counterpart don't change the temperature of a beaker inside.

#### Difference between expected and actual behavior
I expected the heater to modify the temperature of a beaker full of space lube by any amount in the seven hours I left it running in the test server, but it stayed at room temperature.
I also set the cooling machine but I forgot to turn it on. Still no visible change at all after multiple minutes.

Frostoil + water did result in cold ice, so the reagent temperature seems to be working fine.

#### Steps to reproduce 
put beaker in machine and wait nine months

#### Length of time in which bug has been known to occur
Didn't even know we had reagent heaters.

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Eneocho** [comment]
they work now
