### ISSUE TITLE
meta vox outpost suggestion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17876]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
Needs some mining equipment

**Comment by Daxalog** [comment]
Should the equipment be weird or different in some way? A Pickaxe that uses the wooden stick but they have a shitty starting metal picks that breaks after some use. And stronger/stranger axes come from different ores. Maybe they wouldnt get AS good as the diamond drill for pure efficiency but it might open up a useful vector of trade to Miners/Anybody who wants to go spelunking with odd options. Just an idea..

I wonder what a Phazon or Bannanium Pickaxe would do.

**Comment by Probe1** [comment]
Sure.  Go code that cause we don't have durability limited pickaxes.

**Comment by Daxalog** [comment]
Gotcha ill look into it. Do I have to link back to this issue in some way when im done?

**Comment by Probe1** [comment]
Yeah just write "Closes https://github.com/vgstation-coders/vgstation13/issues/17876" in your PR title.  The link being the url of the issue.
