### ISSUE TITLE
Character briefly becomes Kevin Bacon in Footloose

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#17877]
#### Description of issue
Movement flipping the fuck out for no reason at random intervals, as if someone's randomly mashing my arrow keys, or I'm being controlled by another player 

It usually happens when I'm on the janicart, and I have the keys in the cart.

I have no idea what's causing this. This isn't happening in other games, so it's not a keyboard issue.

**Comment by DrSnips** [comment]
Isn't this a virus effect?

**Comment by jknpj** [comment]
thanks, gyro

**Comment by Blithering** [comment]
Random movement is caused by a few things, but being on a vehicle usually prevents it altogether. If it's happening on a vehicle this might be something different

**Comment by Megamaw** [comment]
usually happens on roundstart, btw.

**Comment by jknpj** [comment]
ooh, i think i get this as nymph too when i use my suck blood verb while moving, it locks me into moving in that dir

**Comment by MadmanMartian** [comment]
There is a macro where you can rapidly spin a chair. This macro can be used on a janicart. Ergo, this is not a bug but a ghost being fucky with you.

This is a feature, as it's controlled by a boolean variable called 'noghostspin'. On the default vehicle it is true, so the vehicle can not be spinned. On the janicart it is false, so it can be spinned.

**Comment by Probe1** [comment]
That's beautiful.

**Comment by Blithering** [comment]
The only thing is, Megamaw specified movement not facing direction. Unless we get confirmation it may just be ghosts spinning the fuck out of the cart, but it may also be something else

**Comment by Megamaw** [comment]
late af but i know what cart spinning looks like. as a janitor, i am used to this

i am not used to, however, taking my hands off the keyboard and mouse and watching as my character flips his shit and wigs out in random directions taking me back and forth through the halls.

keep in mind i said usually. its been a while but i think it's happened while standing too

no, i'm not a doofus. i know ghosts can spin shit. but they can't make you move to other tiles, much less THAT fast.

**Comment by Megamaw** [comment]
addendum to last post, correction: okay i AM a doofus but i understand what ghosts do, i'm not new.

**Comment by Probe1** [comment]
We're all happy 👏

**Comment by Megamaw** [comment]
wait okay why is this suddenly closed if it's still an issue

**Comment by Probe1** [comment]
Wasn't it ghosts?

**Comment by jknpj** [comment]
nope

**Comment by DeityLink** [comment]
Is this still a bug/happening?

**Comment by Megamaw** [comment]
i don't play that much on /vg/ anymore, i'm not sure if this was ever reproduced, but i vaguely remember it happening 2 or three times on separate days.

**Comment by DeityLink** [comment]
Will re-open or make a new issue if it occurs again
