### ISSUE TITLE
Bagel genetics improvements

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17872]
Add a service desk so people can get curbside genetics and geneticists don't live in a cave.

Move the consoles one tile closer to each other so you can stand in between them like the autistic fuck you are and double fist the consoles.

**Comment by Irradiation** [comment]
What if the consoles were distanced in the first place to encourage raiding of Tech Storage to get more console boards?

**Comment by Probe1** [comment]
Nah you just go get yourself a wrench and move them yourself if they aren't mapped that way. Also I don't think tech storage starts with the boards.  I like the way you think though.

**Comment by ghost** [comment]
It depends on the map sadly and like you say I don't think bagel has a dna modifer which is one of our major inconsistencies.
It's fun for antag shenanigans on box though!

**Comment by Probe1** [comment]
I want to go full retard/steam ahead. Add the non-secure tech storage boards to a spawner list.  Spawner picks what board will be on what rack at random every round.  People will _love_ me.
