### ISSUE TITLE
Didnt see cult icons as a juggernaunt transformed while offline

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#17881]
#### Description of issue
I got turned into a juggernaut while I was restarting the game, but didn't have a HUD and accidentally murdered a cultist because of it.

#### Difference between expected and actual behavior
Having a hud telling me who to smash, instead of no hud.

#### Steps to reproduce 
get soul sharded while offline maybe?

#### Server revision

Revision: ae0e52a427ab5b6a19cdcb6177fe421f31f6cd04 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Pathid** [comment]
``[15:24:41]GAME: Cultists: Gaius J Caesar(NerdOctopus), Driscoll Mosser(MiniMeatwad), Horatio Robinson(Heroinehero007), Johnny Blues(KernelCornstalk), Oliver Twist(BokChoi), Juggernaut (323)(Dacendeth).``
It appears you were a proper cultist jugger, so what I said on discord about not being registered as a cultist wasn't the problem.

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/37688799-2163b564-2c78-11e8-99bf-41d9a8e7820f.png)
I didnt appear on the roundend cultist list for me

**Comment by Pathid** [comment]
:thinking:
Well then.
