### ISSUE TITLE
Packed Mapping Notes

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17886]
Tech storage has exactly a single one-way window, the bottom tech storage directional window to space facing south.

MoMMI nest top middle window inexplicably has a north facing directional firelock.

**Comment by Probe1** [comment]
I'm going to go out on a limb and say both were my fault.  The firelock was there before but I forgot to remove it when I moved the nest.  The window I probably did since one-way-windows are mixed in with reinforced windows in the instance panel
