### ISSUE TITLE
Jar and Water causes infinite slippery floors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17898]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
5ae5cb73a28241c6200128a8e7e345871a10e34c

# Description
jar printable in the autolathe constantly applies water to the ground according to the amount in the jar as long as there is a object in the jar, 5u will slip people very shortly and 250u is enough to kill somebody and fully strip a nuke operative. can be abused by walking around and having water constantly appear below you, the more jars the more of a water trail you leave.
# Steps to Reproduce

# What you Expected
a jar
# What Actually Happened
jarjar binks slips everyone and kills them through water magic

**Comment by MadmanMartian** [comment]
how in the fuck.

Why in the fuck does touch_obj water reaction decide to cover the fucking ground in water?

**Comment by MiniMeatwad** [comment]
turns out the amount of water in units doesn't matter but something else might

**Comment by Mothblocks** [comment]
sounds like a fun feature to me

**Comment by jknpj** [comment]
holy shit

**Comment by MiniMeatwad** [comment]
on the topic of jars, has anyone tried putting a superglued item stuck on their hand into a jar to get it off? the autolathe can also accept the jar even though it has a item in it, deleting the item in it, the jar can also hold a jar inside of a jar inside of a jar and so on. the jar also turns into a glass shard on breaking, which creates more glass than the jar costed

**Comment by MadmanMartian** [comment]
1. It should have a check to see if the person can actually place the object
2. Aw fuck
3. Intended
4. How in the hell. I set it so that it was specifically worth 1 shard of glass
