### ISSUE TITLE
Religion Denouncement Confirmation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17893]
(WEB REPORT BY: dtscurvy REMOTE: 172.93.109.202:7777)
# Revision
5ae5cb73a28241c6200128a8e7e345871a10e34c

# Description
There's no confirmation prompt for denouncing your faith. This is very problematic when you're a chaplain during a cult round and you try to turn your flashlight on and you tip your fedora instead and turn autistic
# Steps to Reproduce
Have a religion, hit fedora button
# What you Expected
Nothing, it was an accident
# What Actually Happened
Fucked up as chaplain and was useless during a cult round, committed seppeku

**Comment by Aurx** [comment]
Why the fuck were you wearing a fedora during a cult round as a chaplain, though?

**Comment by ihadtoregisterforthis** [comment]
Rennounce faith action button has a fedora icon. And the atheist religion gives you a fedora.

**Comment by ShiftyRail** [comment]
This is weird, as Chaplains should not be able to renounce, at all.
I'll look into that.

**Comment by ShiftyRail** [comment]
![error_message](https://user-images.githubusercontent.com/31417754/37789040-2ff9b308-2e03-11e8-8b50-c8139c00a8e9.png)

This is the message that is supposed to happen when your renounce a religion as chaplain.
Could you please tell me if you had that one ?

Thanks.
