### ISSUE TITLE
Packed issues

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#17908]
1.  Not enough ATMs/poor distribution
2.  Maps in arrivals.
3.  Mining shuttle shit can be done better.
4.  Path to the secret powergamer high yield areas requires a lot of tedious mining
5.  No crates around the mining smelter.

**Comment by Dacendeth** [comment]
The NT glock custom in the armory uses .38 ammo, but the spare magazines in the locker with it are .45.
