### ISSUE TITLE
ZAS Foam Fire Extinguisher causing -274C 0kPa gases

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17909]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
4315dc729429be213ad2e4f04eb8f4bde0a7886f

# Description
https://i.imgur.com/GkD5HBv.png
# Steps to Reproduce
first, you need to create something like this https://i.imgur.com/Xg5ZoDt.png
since you can create a full window and be inside of it, you can turn the gases inside of it to be -274C by using a foam fire extinguisher in the corner making sure the foam doesn't exit the window.

second, you need a teleporter of some sort, to create something like https://i.imgur.com/eEL7NNA.png
it will need either a GPS or the coordinates or a tracking beacon for either one of the teleporters to teleport there.

third, you need to create a canister full of a lot of moles of gas, then you take it to a teleporter that you can use to teleport the canister inside of the full window, you then teleport yourself inside with the canister and smash the canister until it breaks, then use the foam fire extinguisher as mentioned and any gases in the full window will now be -274C and 0kPa. use a scrubber to extract the gas

**Comment by Exxion** [comment]
I have confirmed that this is *not* fixed, and also that it does explicitly require the window. A one-tile room does not work.
What

EDIT: Never mind, a one-tile room *does* work. Just for some reason, it didn't once.
Also, I'm pretty sure this bug is as old as the foam extinguisher itself
