### ISSUE TITLE
Beartrap bug?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17917]
(WEB REPORT BY: angstalmighty REMOTE: 172.93.109.202:7777)
# Description
despite taking bear trap off, graphical bugs (ghost beartrap in hand, cant drop it) and permanent slow-walking

# Steps to Reproduce
>step on beartrap
>take no damage
>move 2 steps to the right
>try to take bear trap off
>????? sorry I can't really remember what else happened

# What you Expected
When I got prank-beartrapp'd that I would be able to continue to play the rest of the round walking at full speed

# What Actually Happened
A failed vamp round because "you're too slow!"

**Comment by Dacendeth** [comment]
did you forget to toggle walk back to run?
