### ISSUE TITLE
Automatically Wielded Items

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17924]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
4aec24b2edcf6f5aa7f5394ce88ea64c02949b2b

# Description
they can't be stored because they're automatically wielded and wielding a object makes it so it can't be stored, picking up a chick lets you store it in a box or something, but i can't store chickens in my backpack because they're wielded
# Steps to Reproduce
pick up a chicken with grab intent by dragging it onto you

**Comment by MadmanMartian** [comment]
Sounds like a feature

**Comment by Pathid** [comment]
Might be. Although, isn't it weird being able to put nymphs in your bag but borers are too big in some way?

**Comment by MiniMeatwad** [comment]
i figure they should use the size they're assigned instead of just completely out right preventing you from storing it

**Comment by Probe1** [comment]
chickens are fine. 
borers are strange and an oversight.

until a time when we move away from simplistic representation of objects and storage space you're going to have to accept some weird stuff.  if its really important you can start coding us a weight and mass system now.

**Comment by Exxion** [comment]
You don't have to do that
Just remove the code that prevents you from placing wielded objects into containers and fix whatever bug that was presumably added to fix
