### ISSUE TITLE
A shard of glass is worth the same as a sheet of glass

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#17920]
weapons/shard.dm, line 18
	starting_materials = list(MAT_GLASS = 3750)

mining/materials.dm, line 149
       cc_per_sheet = CC_PER_SHEET_GLASS

_defines/setup.dm
      #define CC_PER_SHEET_GLASS 3750

If you're going to have an object drop a shard, it had best be worth equal to or more than a glass sheet.

**Comment by Kurfursten** [comment]
Isn't this logical since you can weld any shard into one sheet of glass?

**Comment by MadmanMartian** [comment]
then why does it not use the define?

**Comment by Kurfursten** [comment]
Comic didn't think of it in #4584 and no one suggested he use the defines which have existed since this codebase started (#174)
