### ISSUE TITLE
Explosive Chewing Gum explodes in pocket

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17926]
(WEB REPORT BY: chugmonkey REMOTE: 172.93.109.202:7777)
# Revision
2046363a10cdcf1d13a0f54aece13a1efede3ec2

# Description
I had wrapped chewing gum, and put it in my pocket to buy another piece as the clown. When I suddenly exploded. When I looked back it had said I started to chew the gum when I obviously hadn't
# Steps to Reproduce
1. Buy chewing gum
2. Put it in your pocket
3. Buy another piece?
4. Watch as you explode when you never even unwrapped it
# What you Expected
Fun and Memories
# What Actually Happened
Eternal unwavering asdness

**Comment by Kurfursten** [comment]
This is probably checking to see if its loc is a mob rather than checking to make sure it's in the proper slot

**Comment by Kurfursten** [comment]
Was not able to reproduce, probably just hit the equip hotkey by accident without realizing. In addition, I looked at the code and could see no way it could be caused without equipping to the mask slot.

@Exxion this is fine to close
