### ISSUE TITLE
telekinesis is not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17927]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
2046363a10cdcf1d13a0f54aece13a1efede3ec2

# Description
telekinesis is not moving items, just highlighting them
# Steps to Reproduce
toggle tele block on, click an item, it glows, nothing else after 
# What you Expected
to throw it 
# What Actually Happened
it shimmered

**Comment by Irradiation** [comment]
Can confirm it happened last week on a bagel vampstended/wizard/autotraitor round.

**Comment by MiniMeatwad** [comment]
yeah it's broken

**Comment by Allspice** [comment]
Bisected commits, bug appears at #17417
