### ISSUE TITLE
Ghost roles affected by the text stacking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17925]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
4aec24b2edcf6f5aa7f5394ce88ea64c02949b2b

# Description
if someone makes a lot of dionae and harvests them all at once, people will only be able to sign up for one diona, perhaps this could be fixed by having any ghost roles prompted in the chat have something different about them
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
There *is* something different in each prompt: The hrefs of the links. If they're getting combined, something's wrong with the system.

**Comment by jknpj** [comment]
this doesn't happen to me at all

**Comment by Exxion** [comment]
I'm not sure what happened here, but I also can't see a way it would happen in the code. Reopen if confirmed.

**Comment by Pathid** [comment]
@Exxion I think the hrefs might actually get doubled somehow.  It has happened to me in the past.

**Comment by Exxion** [comment]
Oh, like the chat message got sent twice? I haven't seen that happen in the wild, but I have seen it while debugging stuff, so it's clearly possible
