### ISSUE TITLE
Box: Begone Telecoms Cycling Airlock

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17939]
I normally always force the doors but I didn't this time because I had no inflatable doors (mistake one) and then had to wait 4 (four) minutes for the doors to cycle because the thermal plate + heater combo is so bad at warming up the cycler. Why you ask?

> Results of the Insulated pipe scan:
>  Pressure: 1204.8 kPa
>  CO2: 1324.7 mol, 100%
>  Temperature: 0°C

Turns out the coldness of the room itself cools off the pipes a lot faster than the heater can warm it up. It's time Box learned a lesson from Deff and simply made it a 2-step airlock system instead of this archaic cycler that everyone bypasses anyway.

**Comment by jknpj** [comment]
flaps and conveyors when?
