### ISSUE TITLE
[Layers] Glowshroom layer is above the table layer

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#17941]
#### Description of issue
Glowshrooms pop up above the table layer and since they basically encompass the tile and you attack it if you click it, you can't do jack shit with a table in a practical manner. Need the effect's layer put below table layer.

![glowshroom layer](https://user-images.githubusercontent.com/5564796/37948877-a308218e-313e-11e8-8f2e-4836b1ca7cf5.png)
Lost the one with the glowshrooms on top of the rtables here but just imagine the normal floor effect on top of the tables
![botany diona farm 20951](https://user-images.githubusercontent.com/5564796/37948917-cbd790b8-313e-11e8-9e7c-1a7dd7551e89.png)

@DrCelt  Save us layers man, you're the only hope of the republic.

#### Difference between expected and actual behavior
Glowshrooms to be layered below table layer

#### Steps to reproduce 
Spawn a couple glowshrooms, hit pgdn to place em, use a table parts, growshroom is on top

#### Specific information for locating

effects/glowshroom.dm

/obj/effect/glowshroom
	name = "glowshroom"
	anchored = 1
	opacity = 0
	density = 0
	icon = 'icons/obj/lighting.dmi'
	icon_state = "glowshroomf"
	layer = BELOW_OBJ_LAYER
	var/endurance = 30
	var/potency = 30
	var/delay = 1200
	var/floor = 0
	var/yield = 3
	var/spreadChance = 40
	var/spreadIntoAdjacentChance = 60
	var/evolveChance = 2
	w_type=NOT_RECYCLABLE

I don't think it's relevant but here's the glowshroom itself
Food/snacks/grown.dm
/obj/item/weapon/reagent_containers/food/snacks/grown/mushroom/glowshroom/attack_self(mob/user as mob)

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
Cozy
