### ISSUE TITLE
Named chicks don't keep their name

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17942]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
d94298f7e372b866baa59b39c1d7e458f96425cc

# Description
maps include either a chicken or chick in botany, usually named Pomf, the name of which does not persist if the chick turns into a chicke

**Comment by sonime** [comment]
Any chicken that spawns, including the one in Botany, already has a chance to be a Pomf chicken.
