### ISSUE TITLE
invisable monkeys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17956]
(WEB REPORT BY: pappavol REMOTE: 172.93.109.202:7777)
# Revision
cc720307ff0cf2abe993b579b7b6784895efc1df

# Description
the monkeys just randomly went invisable
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Pathid** [comment]
BYOND issue. Closing the window and reconnecting usually fixes it. Must be some reason it only happens to monkeys though.

**Comment by Exxion** [comment]
Whenever it happens, it happens to all objects with the same sprite, if this is the issue I think it is
