### ISSUE TITLE
Grille shocks people if cable is under it wether or not the cable is powered.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17969]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
cc720307ff0cf2abe993b579b7b6784895efc1df

# Description
https://i.imgur.com/6GfnatC.png

**Comment by Probe1** [comment]
Oops

**Comment by Pathid** [comment]
Can confirm, any unpowered wired grille will shock you for a stun and zero damage.
