### ISSUE TITLE
Red ribbon belt artifact bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17975]
(WEB REPORT BY: harukasuka REMOTE: 172.93.109.202:7777)
# Revision
cc720307ff0cf2abe993b579b7b6784895efc1df

# Description
Putting it into the belt slot is supposed to give you one extra hand, but taking it off and putting it on makes them stack infinitely.
# Steps to Reproduce
Take it off and put it on again
# What you Expected

# What Actually Happened

**Comment by nuklearcellphoneg** [comment]
delete this

**Comment by Probe1** [comment]
Pretty sure its a duplicate.
https://github.com/vgstation-coders/vgstation13/issues/17897
