### ISSUE TITLE
Deff medbay juke has no nanovinyls in it.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#17979]
#### Description of issue
the medbay juke on deff has no music for you to listen to like every other jukebox on other maps.

**Comment by Kurfursten** [comment]
I bet they used the parent jukebox instead of jukebox/bar

**Comment by Probe1** [comment]
Sounds like a good excuse to add a new juke subtype for Medbay.

**Comment by ghost** [comment]
DOCTOR, DOCTOR, GIMME THE NEWS

**Comment by Probe1** [comment]
alright post songs for medbay.

**Comment by ghost** [comment]
Bad Medicine - Bon Jovi
Bad Case of Loving You - Robert Palmer (or Moon Martin if you want I guess)
Doctor Feelgood - Mötley Crüe
Sheer Heart Attack - Queen
Staying Alive - Bee Gees
Also the Theme Hospital OST please thank you

**Comment by Kurfursten** [comment]
- Teardrop by Massive Attack (the intro to House M.D.)
- I'm no Superman by Lazlo Bane (the intro to Scrubs)
- Suicide Is Painless (intro to M * A * S * H)
- Cosy In The Rocket by Psapp (intro to Grey's Anatomy)
- St. Elsewhere by Dave Grusin (intro to, obviously, St. Elsewhere)
- The Doogie Howser, M.D. Intro Song (this is instrumental and has no name but you can find good quality rips on YouTube)

**Comment by Probe1** [comment]
List so far https://www.youtube.com/watch?v=OBwS66EBUcY&list=PLFLmYeyUixxxJ1JlhhFDywvaYtgJa-otz&index=2

**Comment by Dacendeth** [comment]
Witch Doctor - Ooh Eeh Ooh Ah Aah Ting Tang Walla Walla Bing Bang
"Weird Al" Yankovic - Like A Surgeon

**Comment by toomykins** [comment]
E-Rotic - Help Me Dr. Dick https://www.youtube.com/watch?v=KEChIzlaPjI

**Comment by Probe1** [comment]
You better believe Dr Dick is going in.

**Comment by Kurfursten** [comment]
"How to Save a Life"

How'd we forget?

**Comment by Blithering** [comment]
Dr reanimator - move your dead bones
Genetics needs some representation

**Comment by CptWad** [comment]
this isnt an issue anymore

**Comment by Exxion** [comment]
It was fixed by #18755 but for some reason Duny intentionally didn't autoclose this in it
