### ISSUE TITLE
No air in bagel SME shard chamber

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17971]
(WEB REPORT BY: lunstra REMOTE: 172.93.109.202:7777)
# Revision
cc720307ff0cf2abe993b579b7b6784895efc1df

# Description
Exactly what it says on the tin, there's no air in the shard chamber on bagel
# Steps to Reproduce
Wait for a bagel round and open it up
# What you Expected
There to be air in there
# What Actually Happened
There is none and all the loose shit in the area gets sucked across the room which is a pain in the ass

**Comment by Kurfursten** [comment]
This actually is a feaaaaature, use an inflatable wall. Although it should perhaps be changed anyway just for consistency.

**Comment by Probe1** [comment]
Why is it a feature I can't remember

**Comment by Kurfursten** [comment]
No nitrogen in the shard chamber makes it easier to get to 80% oxygen when it's time to fill
