### ISSUE TITLE
Cyborg Components

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#17984]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
7c9b9de55568680112cd517621c8648ae61a89c5

# Description
they work weird and components are randomly damaged, meaning if you're unlucky you're likely to be disabled in a couple of laser shots, reinforced components added recently are more or less useless if it's easy to disable a cyborg simply because the power cell will most likely break before any of the components do

**Comment by SonixApache** [comment]
[discussion] ?

should borgos have their organs assigned to aim zones?

**Comment by AutismSpider** [comment]
most people would aim for the chest/head then
