### ISSUE TITLE
Aghost Interaction Wishlist

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#17989]
- Vending machines
- Cargo console
- Telesci console
- Firelocks
- Microwave
- ATMs
- Accounts database
- Fax
- Turret Control
- Foam dispenser
- Message Monitor Console
- Fabricators (exosuit fab)
- SMES (same)

Not updating at distance
- Intercoms
- Request console (don't clear icon_state)
- Sec + Med Records (opens but no ID)

**Comment by Pathid** [comment]
* Intercoms

You can VV them easily but it's not the same.

**Comment by Probe1** [comment]
FUCKING CARGO CONSOLE

**Comment by Probe1** [comment]
@Kurfursten If you're looking for a project, adding admin verbs into a well made HTML list would be a godsend.  80% of the verbs as you know are admin ones.  Its a hot fucking mess.

The existing menus are also dogshit.  A good example is Secrets.  It's just a super long list instead of there being several submenus divided by type (logging, bus, minor bus, major bus, random events, etc)

**Comment by Kurfursten** [comment]
The problem with an html list is that it's only a slight step up if you still have a ton of stuff. Take the secrets menu: so long you can scroll practically for days before you get to the secret coder debugging at the bottom. Plus side is that you can ctrl+f at least.

**Comment by Probe1** [comment]
Submenus.

**Comment by Kurfursten** [comment]
Also, a button to locate the spare might be nice.

**Comment by Kurfursten** [comment]
If the traitor panel would show what someone has spent their TC on like the ending screen, that would be nice

**Comment by DamianX** [comment]
#14223

**Comment by Kurfursten** [comment]
I would also like who advanced to show jobs

**Comment by Kurfursten** [comment]
Aghosts seem to get no notification whatsoever when a new player arrives on the station, which needs fixing

**Comment by nuklearcellphoneg** [comment]
Oh man, you know, I know exactly what this implies.
