### ISSUE TITLE
Fat Tradershuttles & Centcomm

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#18003]
Apparently this is true of a lot of shuttles, Bagel Deff and Meta. They're not getting placed far enough inward and people can get out of the throw area.

I think it's time to put this meme to bed once and for all by changing out the windows at centcomm for the fake windows we already have on places like the cargo shuttle's z2 spot, and walling off the whole transit area.

**Comment by strawberrytan** [comment]
Rip hyperspace jaywalking to central command on a wing and a prayer

**Comment by unid15** [comment]
Alternatively switch to procedurally generated transit areas. With the exception of the fact that they don't have throwers (so they teleport you to space right away when you step out), they're better in pretty much every way

**Comment by Probe1** [comment]
Could you do that for us though @unid15

**Comment by unid15** [comment]
I'll take a look at it sometime maybe

**Comment by Kurfursten** [comment]
For reference the transit zone is plenty big enough, the shuttle is just placed badly
