### ISSUE TITLE
Shocked airlocks appear not to check siemens_coefficient

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18007]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
Hit a spicy airlock with a glass shard: Zappy
Shard on shocked grille: No zap.
Battering Ram on airlock (think it is also nonconductive): Zappy
Ram on shocked grille: No zap.

**Comment by Allspice** [comment]
Minor revision: The airlocks skip WEAPON siemens_coefficient. Touch while wearing insulated gloves, no shock. Touch while holding but not wearing yellas, shock.

Also, touching grille and airlock with batteringram offhand produces results identical to touching with the ram itself.
