### ISSUE TITLE
Invisible captain armour on vox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18005]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
1759f357e3820a61cb4fc846e3384fd2dacc3ae5

# Description
Alternative cap's armour is wearable but invisible when worn by a bird

# Steps to Reproduce
Put on cap's armour as a vox - easy to find on Bagel iunno about other stations

# What you Expected
Not be able to wear/have visible armour

# What Actually Happened
Buttnaked bird

**Comment by beesil** [comment]
Fixed by #22049
