### ISSUE TITLE
Imidazoline Welding Pseudo-Blindness

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18028]
(WEB REPORT BY: nogeeef REMOTE: 172.93.109.202:7777)
# Revision
b9fbf780e43bbaf48295112a6728b48517f384a7

# Description
When on imidazoline, it will appear that you aren't blind (I can see the whole screen just fine) but when I try to examine something it says I can't see it.

# Steps to Reproduce
1. Weld until you go blind
2. take imidazoline. I believe I took something like 32u
3. After blindness clears, weld until the "you go blind" message appears
4. You should now be "blind" but you can see everything

# What you Expected
To have black around most of my screen, representing blindness.

# What Actually Happened
I can see the whole viewport.

**Comment by nuklearcellphoneg** [comment]
With imid eye damage not ecvoluate?

**Comment by MadmanMartian** [comment]
Welding gives you the blind defect, which isnt fixed by imidazoline

**Comment by nuklearcellphoneg** [comment]
Oh so a separate flag from eye damage? Weird, I've never had my eye damage through welding not cure via imid.

**Comment by Probe1** [comment]
R0B0s right.  It takes doing like he said.

**Comment by Probe1** [comment]
My mistake I re-read his issue and realized he's complaining about the overlay not properly being reapplied.  Which is a known bug and I'm sure in the 900 bug reports its mentioned but fuck if I'm looking for it.
