### ISSUE TITLE
Putting arms in trashbags

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18038]
(WEB REPORT BY: kommandre REMOTE: 172.93.109.202:7777)
# Revision
3245d7f3d2734fb4a5ac77ba54c9a697f0a725d2

# Description
Every limb except the right arm can fit into a trashbag
# Steps to Reproduce
Click on a right arm while holding a trash bag
# What you Expected
The arm to be picked up, like all other limbs
# What Actually Happened
It says it is too big to fit into the trashbag

**Comment by strawberrytan** [comment]
Pretty sure arms are classed as large and legs are classed as normal in size

Honestly it should be the opposite, and maybe sawing the hand or foot off will or should reduce item size (but maybe it doesnt?)

**Comment by Probe1** [comment]
They should all be abstracted as normal / small objects for quality purposes.  This is a case of code being too smart for its own good.

**Comment by ghost** [comment]
This was fixed at some point, checked on my end. Close this
