### ISSUE TITLE
Cyborg Medical Module Bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18032]
(WEB REPORT BY: kharkov72 REMOTE: 172.93.109.202:7777)
# Revision
3245d7f3d2734fb4a5ac77ba54c9a697f0a725d2

# Description
R&D has the research for a midical module (3 Engineering 3 Biological research), but it won't show up in the exosuit fab.
# Steps to Reproduce
Do R&D however you do it, then just check. I'm not sure why it isn't showing up, maybe it was just coded out?
# What you Expected
I expected to upgrade my borgo.
# What Actually Happened
My borgo left cold and defibless.

**Comment by jknpj** [comment]
A N O M A L Y

**Comment by Pathid** [comment]
See #17107

Also nobody updated the damn wiki.
