### ISSUE TITLE
Feature Request: more bots with pAI slots. 

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#18052]
#### Description of issue
medibots are the only bots with a pAI slot. why no roombas or ED209s with them?

**Comment by toomykins** [comment]
Medibots can space walk
MULEs can lift things and people up and run people over.
what more can you want?

**Comment by spoonylove** [comment]
an officer cheapsky sec companion who scolds people.

**Comment by Pathid** [comment]
pAIs can already *halt and *law if they have the security package but that sounds good too.
