### ISSUE TITLE
Flashes stun blind people

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#18057]
A flashbang causes ringing, but why would a flash stun a blind man?

**Comment by Accipitermaris** [comment]
>be blind assistant
>rev tries to flash me
>i run away and report to sec for my free <s>forced implanting and disposaling</s> McEgun

sounds gimmicky enough to be good

maybe you'd add flavor text, like if you examine someone they'll have an extra flavor text if they're blind like how people with loads of braindamage appear upon examine.

**Comment by Killette2** [comment]
I think penlight has a unique text for blind people, along with normal and people who have x-ray vision.

**Comment by strawberrytan** [comment]
For genetic blindness the penlight will either tell you the pupils dilate or do not react to light stimulus

**Comment by Pathid** [comment]
Works with any flashlight, by the way.
