### ISSUE TITLE
obese vox immune to mint toxin

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#18055]
#### Description of issue
became obese as bird ate a mint and didnt explode. 

#### Difference between expected and actual behavior
Expected to gib.

#### Steps to reproduce 
be a vox make a mint from the recipe (aloe+1 sugar) be fat or become fat. eat the mint and not die. If I remember correctly I drank some ground up mint toxin as well and got nothing.

**Comment by Pathid** [comment]
Only humans and greys can be actually fat instead of just "chubby". It's an unfortunate side-effect of how not having fat sprites for other species is handled currently.

**Comment by jknpj** [comment]
vox can't be fat

**Comment by spoonylove** [comment]
Oop my mistake
