### ISSUE TITLE
crew manifest bugging out during 24 hr freeze test

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18066]
(WEB REPORT BY: ssquids REMOTE: 172.93.109.202:7777)
# Revision
80e79f9e20c8ad6f2c9f431f8049ae810e0bfa41

# Description

Name Rank Activity 

Cockswain Adams Plasma Researcher 

Jere Stradford Cyborg  

crew manifest appears to be bugged, Jere Stratford is not the name of a cyborg

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
needs closed
