### ISSUE TITLE
cigarette capacity not adjusted to account for tobacco implementation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18074]
(WEB REPORT BY: cadaverouscoyote REMOTE: 172.93.109.202:7777)
# Revision
f78487c60f9aa45458a5041fae1175ca3122d6c0

# Description

a third of a cigarette's (and half(?) a cigar's) capacity is taken up by tobacco, as a result prank cigarettes don't work properly any more. capacity must be increased.

# Steps to Reproduce

dip a cigarette in ≥ 15u welder fuel and light.

# What you Expected

*pow*

# What Actually Happened

*pff*

**Comment by MadmanMartian** [comment]
so, the cigarette now has something in it, and this is a problem?

**Comment by ghost** [comment]
They're half full of nothing now.

**Comment by Probe1** [comment]
frickin idiots putting frickin tobacco in my cigarettes.  they were ignitable beakers!

**Comment by SonixApache** [comment]
Wait, so exploding cigarettes is no longer a thing?
That's feature loss right there.

**Comment by cadaverouscoyote** [comment]
>small, inconsequential feature no longer works as intended due to the addition of another small, inconsequential feature
>solution which would retain both suggested in description
"what so tobacco's the problem??"
