### ISSUE TITLE
Jetpacks useless without action buttons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18075]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
# Revision
f78487c60f9aa45458a5041fae1175ca3122d6c0

# Description
verbs related to jetpacks seem to be missing from the object tab, using them inhand gives the internals menu.
# Steps to Reproduce
equip jetpack, have no action buttons
# What you Expected
toggle jetpack and toggle jetpack stabilisation to be in object verbs
# What Actually Happened
not there

**Comment by Probe1** [comment]
We know, I made a note of it in the announcement, and the verbs were removed.
