### ISSUE TITLE
Admin Permissions

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#18070]
Hello, okay so let's say you have the +SOUND flag but no other flags. This flag will still make you see logs and stuff that you shouldn't during the round, you know, like admin logs and stuff!

It would be really nice if when someone had +SOUND and only +SOUND they did not see those logs. :) Kind of a general thing, probably has more to do with the general nature of PERMISSIONS overall.

**Comment by sonime** [comment]
Reminder to give me +SOUND

**Comment by Probe1** [comment]
![_](https://user-images.githubusercontent.com/8550416/38634854-bc2570fe-3d91-11e8-8b24-89ac0f9bb2d6.png)

**Comment by sonime** [comment]
+SOUND giving access to admin logs is an actual issue though, even the cluck agreed. I'd screenshot it but I'm phoneposting.

**Comment by nuklearcellphoneg** [comment]
Yes Sonic anime is correct.

**Comment by nuklearcellphoneg** [comment]
![image](https://user-images.githubusercontent.com/6540760/38636381-010374ce-3d96-11e8-8683-53a704229248.png)

**Comment by MadmanMartian** [comment]
This is a legit citable issue though. Why's it closed?

**Comment by nuklearcellphoneg** [comment]
I imagine he doesn't want to appear like he's favoring me or something; to be honest, I only bring this up because it would lead to me having +SOUND. :^)

**Comment by Probe1** [comment]
@MadmanMartian We already have multiple issues regarding admin flags and Nuke isn't getting sound without being an admin.  Also it was posted in a semi jest so it was closed in the same fashion.

**Comment by DamianX** [comment]
Probe is fucking up and declaring himself a dictator

**Comment by Probe1** [comment]
sound or riot
