### ISSUE TITLE
Screen getting stuck (still image after round join)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18083]
(WEB REPORT BY: venseer REMOTE: 172.93.109.202:7777)
# Revision
1a239993fca21055a149cf279b57a5bd3d7c2aa2

# Description
Whenever I join a round, the screen gets stuck into a still image. I am still connected to the server and can read chat, hear players talking.

Any attempt of resizing and/or moving the screen will cause it to turn black.

# Steps to Reproduce
Join Game.

# What you Expected
To join the round normally

# What Actually Happened
Screen gets stuck into a still image. Any attempts of resizing the screen will turn it black.

**Comment by DamianX** [comment]
Uninstall BYOND
Use http://www.byond.com/download/build/510/510.1347_byond.zip

**Comment by MadmanMartian** [comment]
@DrCelt
