### ISSUE TITLE
Throwing sand at people eyes doesn't inflict pain/damage eyes.

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#18080]
1. Grab a handful of sand.
2. Aim for the eyes.
3. Throw it at the clown/Click on the clown with the sand.
4. The sand ends up on the ground, not in the clowns eyes.
**5. The game doesn't make your character yell "POCKET SAND!" everytime you throw sand at people.**

**Comment by Pathid** [comment]
This is in fact a feature that exists. Although unlike say, flashes, it fails silently when they have eye protection.
