### ISSUE TITLE
No thermals/xray as vamp even with required blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18089]
(WEB REPORT BY: gazzyh REMOTE: 172.93.109.202:7777)
# Revision
9ce3123d4bcffb6217ab6a744fc7e26b1f1e6b30

# Description

Had over 500 blood, no thermals or xray.

# Steps to Reproduce

# What you Expected

1) suck a nigga
2) get thermals

# What Actually Happened

1) suck three niggas
2) no thermals or xray

**Comment by Waismuth** [comment]
It did happen to me in the past, too. I think it might be a bit random, so it's hard to re-create

**Comment by ShiftyRail** [comment]
@Exxion also fixed by datums
