### ISSUE TITLE
Manage Religions Sanity

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#18084]
Pressing the JMP button also tries to deconvert that person, topic must be written wrong

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/cc720307ff0cf2abe993b579b7b6784895efc1df/code/modules/admin/topic.dm#L4800

@ShiftyRail

**Comment by ShiftyRail** [comment]
I'll fix that this evening, thanks

**Comment by Probe1** [comment]
https://github.com/vgstation-coders/vgstation13/pull/18088
