### ISSUE TITLE
pAI DNA samples can still be accepted by dead players

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18090]
(WEB REPORT BY: probe1 REMOTE: 172.93.109.202:7777)
# Revision
9ce3123d4bcffb6217ab6a744fc7e26b1f1e6b30

# Description
Even in death you still get the dialogue to accept a pAIs request to sample your DNA.
# Steps to Reproduce
Be dead.
Have a pAI ask you for DNA
# What you Expected

# What Actually Happened

**Comment by Killette2** [comment]
What if it's asking your dead body cells if they don't mind being sampled?

**Comment by Probe1** [comment]
🤔

**Comment by Kreyfag-the-social-african-american** [comment]
code\modules\mob\living\silicon\pai\software.dm
https://pastebin.com/9bTb4W4b
This should probably fix it
