### ISSUE TITLE
Slime People bleeding problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18094]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
When you hack of a limb of a slime person in one clean swing they're perfectly fine - no bleeding. But if you do it slowly they spray blood everywhere and bleed out.
I think slime people should not have blood at all.

**Comment by Pathid** [comment]
Slime people don't have blood. They leave splatters but so do dionas.

Sounds like what you're describing is a general quirk with the limb damage system no matter what species you are: You die from a large amount of brute or burn on a single limb if it's applied slowly enough not to sever or gib it.
