### ISSUE TITLE
Bells Inside Items

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18102]
(WEB REPORT BY: redworthy REMOTE: 172.93.109.202:7777)
# Revision
98fa2e08279bfef028f3bc20960cf6f36119b95e

# Description
Placing a bell (Medbay Bell etc) inside a bag, box or even your pocket causes it to get stuck. You can't click it to remove the item.

You can also use a wrench to bolt the bell while it's inside an object to make it useable.

# Steps to Reproduce
- Unbolt bell
- Drag bell onto you to pick it up
- Place inside bag, box etc

# What you Expected
- Clicking the bell while it's inside a bag etc would cause you to pick it up

# What Actually Happened
- Clicking does nothing

**Comment by Pathid** [comment]
#17946
#15606
