### ISSUE TITLE
Zombies permanently lag the server

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#18100]
After a certain badmin spawned a lot of zombies, the server started lagging to the point where restarts didn't fix it - only merging a github PR and letting the server recompile stopped the lags. AFAIK, this only happens with zombies - this is the second time this happened on my memory.

Possible fix posted in discord - ``CALL global._list_remove(global.mob_list, src) on [zombie_type] IN global.mob_list`` - I haven't had the possibility to test it yet

**Comment by ShiftyRail** [comment]
To be noted - this SDQL query should be called in the game while zombies are ruining everything.

**Comment by nervere** [comment]
This was fixed.
