### ISSUE TITLE
Emagging doors doesn't leave fingerprints, it isn't logged for admins, doesn't leave hidden fingerprints either.

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#18104]
#### Description of issue
Emagging doors doesn't leave fingerprints or create logs for admins to view. 

#### Difference between expected and actual behavior
I expected to find logs of somebody emagging a door. 
I didn't find any logs or fingerprints.

#### Steps to reproduce 
Emag a door then think to urself "woah how did this go unfixed for so long?"

#### Length of time in which bug has been known to occur
Since forever apparently.

#### Issue bingo

- [x ] Issue could be reproduced at least once
- [ -] Issue could be reproduced by different players
- [x ] Issue could be reproduced in multiple rounds
- [- ] Issue happened in a recent (less than 7 days ago) round
- [:) ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by beesil** [comment]
Fixed by #23075
