### ISSUE TITLE
Coders fuck up stupid april fools joke of mimics on the shuttle to last longer than april fools

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#18110]
![image](https://user-images.githubusercontent.com/16896032/38869195-3785ae4e-428d-11e8-910b-9c69607f6817.png)
Quality fucking coding retards.

**Comment by jknpj** [comment]
super rude. Now, what was the map, and all that info that you cut out but we need to actually know if it was caused by april fools or not?

**Comment by ShiftyRail** [comment]
It keeps happening

There IS a random mimic crate at centcom supply zone, although I believe there's no reason for it to ever end up in the actual shuttle

**Comment by carshalash** [comment]
https://github.com/vgstation-coders/vgstation13/pull/17961 The cause of this shit

**Comment by jknpj** [comment]
@carshalash that only works on april fools.

**Comment by ShiftyRail** [comment]
It's explicitely time-gated, yeah
Are you SURE it wasn't the random "mimics have been breeding in the xyz" event ?

**Comment by carshalash** [comment]
Pretty sure the trade shuttle isnt a possibility, and no events had happened in the round.

**Comment by jknpj** [comment]
Then it was the mimic crate from the centcomm shuttle area that somehow became active and walked in the shuttle, again.

**Comment by carshalash** [comment]
Why on earth is a mimic in the shuttle area to begin with.

**Comment by jknpj** [comment]
Emergent gameplay? They aren't supposed to wake up/move unless some kind of mob manages to go near it

**Comment by ShiftyRail** [comment]
The icon and the description match the wooden chest mimic hidden in centcomm loading area.
It is possible, however unlikely, that a badmin spawned in, woke him up, and lured him into the shuttle.

Not a code issue and even less a coder issue.

**Comment by carshalash** [comment]
![image](https://user-images.githubusercontent.com/16896032/38870231-8ee0f54c-4290-11e8-8b0b-de974efc3cb7.png)
Then why is there a russian in the same area?

**Comment by ShiftyRail** [comment]
How the fuck should I know, ask admins for his attack logs and then we will be able to work up from here.

**Comment by bathosbathtime** [comment]
Deemed a feature by PR #17343

**Comment by Kurfursten** [comment]
>Apologyman spooks: "WHO THE FUCK CODED THAT"

**Comment by MadmanMartian** [comment]
>All this anger over being killed

Why must you hurt me in this way?

**Comment by SonixApache** [comment]
oh hey it's a dumb report

**Comment by gbasood** [comment]
hey someone should check logs

**Comment by ghost** [comment]
WAI

**Comment by LavosIG** [comment]
get fucked carsh lmao, features are great

**Comment by ihadtoregisterforthis** [comment]
At least on box a mimic and a russian spawn in there. As soon as the round starts they fight and the mimic wins in a few seconds, then goes back to being a crate. The shuttle doors start closed and the conveyors off. There has to be a very weird combination of events to cause the mimic to move into the shuttle.

**Comment by Irradiation** [comment]
Clearly, this is a feature because there's an extremely small chance that the russian can die on the shuttle (Good fucking luck). Regardless of where the Ruskie dies, the mimic somehow manages to slip onto the shuttle. Clearly we need mimic-control.

**Comment by jknpj** [comment]
something something announcement about mimics

**Comment by nuklearcellphoneg** [comment]
Can I get a probability read out on this specific chain of events happening

**Comment by gbasood** [comment]
<0.05%
