### ISSUE TITLE
remote signallers don't work in imported assembly frame builds.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18119]
(WEB REPORT BY: spoonylove REMOTE: 172.93.109.202:7777)
# Revision
8514bd03bbc8091aee7d6c7697b2d9abe3832a24

# Description
had saved a small assembly frame from a previous round which involved signallers. upon build the signallers connected to the randomizers refused to work unless pulsed manually. sending a singal from another singaller on the proper freq with code did nothing. 

# Steps to Reproduce
build an assembly frame with a signaller hooked up to a randomizer to do something like say pulse a random speaker. export it, rebuild it with import/export get the error. 

here is a pastebin of my assembly frame for testing. 

https://pastebin.com/n9c86Ki0 

the signallers should work fine. merely set another set of signallers to the same freq and code and see if it works. the signallers need to be removed and put back in and reconnected perhaps on a new freq and code. 

# What you Expected
it to work.

# What Actually Happened
not working.

**Comment by Exxion** [comment]
I can't reproduce this with the given Pastebin

**Comment by Exxion** [comment]
Wait hold on
It only happens if the signalers aren't new
