### ISSUE TITLE
Adamantine golems and space wind

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18117]
These guys originally had the equivalent of galoshes (which do give some ZAS resistance after all) stuck to them before they were made into a proper race. Now they've inherited the slowness and the inability to wear any shoes, but none of the upside. Not being able to shoot guns is one thing, but I feel like not having that NOSLIP _and_ not being able to wear magboots limits their usefulness quite a bit.

**Comment by Killette2** [comment]
How exactly does NOSLIP help against ZAS?

**Comment by Pathid** [comment]
You get pushed around but not knocked over as much.

**Comment by Killette2** [comment]
So ZAS tries to randomly either stun/weaken, or slip you? Why should NOSLIP provide any advantage in the first place?

**Comment by Pathid** [comment]
Better traction perhaps? Magboots give you NOSLIP when on and that's necessary for getting any protection against ZAS in the code how it currently is. There's just an additional check that gives an additional layer of protection if the NOSLIP is from magboots.

**Comment by Aurx** [comment]
ZAS is actually invisible clowns.  
Wake up sheeple.
