### ISSUE TITLE
Botany mutation alter-temperature and vines both ignore tray lids.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18118]
(WEB REPORT BY: kavlax REMOTE: 172.93.109.202:7777)
I'd expect my room not to turn into a freezer with the lid down.

**Comment by Killette2** [comment]
Hey guys, he trusted the lids!

**Comment by MadmanMartian** [comment]
vines do not from a code standpoint.

Alteration of temperature requires the botany tray to be on a connector for it to be contained.

**Comment by Exxion** [comment]
Judging by the code for the hydro tray, it looks like plants *do* always ignore the lid when altering the temperature.
It looks like @MadmanMartian is right about vines though
