### ISSUE TITLE
'Invisible' tiles causing unexpected behavior

### ISSUE THREAD

**Issue by MasterofNothing** [d3athrow/vgstation13#18114]
'Invisible' tiles are causing unexpected behavior. One example is the fucker in the tile left of my character. Without a light, or meson glasses, you'll get stuck right where my character is stuck if you move from the tile below my character to the north. If you move from west to east (one tile above the character in the image), you'll drift off in to space, because the game acts like the tile isn't there. Enable a light or mesons, and the behavior is as expected, and you can move about.

If you want to reproduce it, play boxstation and check for yourself. You can see where this happened pretty clearly - east of the security escape pod, north off the holodeck.

![thanks_byond](https://user-images.githubusercontent.com/6288730/38906417-f4536e34-42b6-11e8-9027-0d3214bd194c.png)

**Comment by gbasood** [comment]
That's an opaque tile.
It isn't receiving light so it's not 'invisible' so much as it is in complete darkness and it won't tell you what it is when you mouse over it.
If you're not adjacent to something dense, like that wall, in space, you can't move around without a jetpack or throwing something.

So where's the unexpected behavior exactly?

**Comment by gbasood** [comment]
Oh, if you're getting stuck in space on a corner, that might be a problem.

**Comment by MasterofNothing** [comment]
Yeah, the point is that you get stuck on it, and can't interact with it. So when going from south to north, it stops you, but doesn't allow you to move away from it. From west to east, you drift off into space (where the 'opaque' tile should have enabled you to move one tile further to the east before drifting off).

**Comment by Exxion** [comment]
Taking bets it checks `oview(1)` instead of `orange(1)`
Or `view(1)` I guess but there's not really any reason to check your own tile so it should still be `orange(1)`

~~EDIT: Actually I lied and it should just be `range(1)`~~
No it shouldn't I was wrong about the difference
