### ISSUE TITLE
Accidentally trashing soap as cyborg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18121]
(WEB REPORT BY: blithering REMOTE: 172.93.109.202:7777)
# Revision
8514bd03bbc8091aee7d6c7697b2d9abe3832a24

# Description
It is possible to lose your built in soap as a borg by accidentally putting it in your trash bag
# Steps to Reproduce
i have no idea
# What you Expected
soap is attached
# What Actually Happened
soap goes in bag

**Comment by jknpj** [comment]
my god.

**Comment by jknpj** [comment]
![image](https://user-images.githubusercontent.com/17928298/46403099-f1b15880-c6d7-11e8-8d23-666fe04559d0.png)
