### ISSUE TITLE
Vampire Transform Doesn't Fool AIs

### ISSUE THREAD

**Issue by Rhimrifer** [d3athrow/vgstation13#18122]
#### Description of issue
AI was able to follow an old name to track a transformed vampire's new identity. Yes I know we know now, but it's here as well.

#### Difference between expected and actual behavior
Target not on cameras instead of panning to new id

#### Steps to reproduce 
Speak as vampire and be heard by AI.
Transform.
Have AI follow old name while on camera.

#### Specific information for locating
I am unsure what else is effected by this, but was specifically found with the vampire's transform power. A related issue was with tracking agent ID cards/voice changers, but that looks resolved.

#### Server revision
8514bd03bbc8091aee7d6c7697b2d9abe3832a24 

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Intigracy** [comment]
https://github.com/tgstation/tgstation/issues/1128

https://github.com/tgstation/tgstation/pull/9602

for reference on how TG dealt with this a while back

**Comment by beesil** [comment]
Fixed by #22559 (probably)
