### ISSUE TITLE
Shadow Step Autism

### ISSUE THREAD

**Issue by SirSkeleto** [d3athrow/vgstation13#18137]
#### Description of issue

Shadow Step (the vampire spell) can step you into space and that's stupid. The spell supposedly teleports you to dark places, and space (as far as the vamp is concerned) is very bright. I'm not sure if it works on all of space but last round I used it on the shuttle and I fucked off into the speedy part which quickly dumped me into the other part.

#### Difference between expected and actual behavior

Hoped to teleport ANYWHERE ELSE or just not at all

#### Steps to reproduce 

1. Be a vampire

2. Suck enough blood to get shadow step

3. Board Emergency Shuttle

4. Wait for shuttle to depart

5. Shadow step into space and die with redtext

**Comment by Pathid** [comment]
Shadowstep skips /turf/space tiles as valid targets. And those speedy tiles are /turf/space/transit so in theory it ought to skip those too, right?

**Comment by MadmanMartian** [comment]
``
        for(var/turf/T in range(usr,outer_tele_radius))

			if(T in range(usr,inner_tele_radius))

					continue

				if(istype(T,/turf/space))

					continue

				if(T.density)

					continue

				if(T.x>world.maxx-outer_tele_radius || T.x<outer_tele_radius)

					continue	//putting them at the edge is dumb

				if(T.y>world.maxy-outer_tele_radius || T.y<outer_tele_radius)

					continue

				if((T.get_lumcount() * 10) > max_lum)

					continue

				turfs += T``

You couldn't have ended up straight into space, and couldn't have ended up on a wall. Are you sure you weren't teleported close to space and stepped off into it?

**Comment by SirSkeleto** [comment]
I used it while downed.

**Comment by Pathid** [comment]
Could you have ended up next to a breach and gotten ZASed out?

**Comment by DamianX** [comment]
which map was this on?

**Comment by SirSkeleto** [comment]
bagel

@Pathid entirely possible. I was downed after all, but it seemed pretty fast and I'm not sure if there was a breach.
