### ISSUE TITLE
Pizza slice spam on custom vendomat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18148]
(WEB REPORT BY: jellyveggie REMOTE: 172.93.109.202:7777)
# Revision
269f2e3a5c73d4c7908075fceb0cccf47121ca95

# Description
Inserting pizza slices from the same pizza into a custom vendomat creates a new entry for every slice, creating six entries per pizza that will become sold out forever after buying a single slice.

# Steps to Reproduce
Build a custom vendomat, obtain pizza, slice pizza, insert pizza slices.

# What you Expected
A single entry per pizza slice type.

# What Actually Happened
An entry per every pizza slice inserted.

**Comment by Killette2** [comment]
Pizza tax

**Comment by Eneocho** [comment]
Cannot reproduce, seems to be fixed. Every slice type I tried got properly stacked
