### ISSUE TITLE
It's another "chatbox loading issues" episode

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#18140]
#### Description of issue
Sometimes when I join a game (either in progress or to pre-game lobby) the chatbox doesn't load at all. This has happened twice in the last two days. Rejoining doesn't fix it, but only _sometimes_ (hooray Byond). 
Client version is 512.1421.

![brokenbyond2](https://user-images.githubusercontent.com/16082007/39139674-74d83852-471a-11e8-8810-d47b08e99940.png)

First case (Apr-22) - latejoined during evac. Chatbox completely blank, but everything else was working. I could see players speech bubbles in the game window, but nothing at all appeared in chat - not even the welcome messages. I was still able to communicate, I had to explain the issue in LOOC and others could read what I'd said. Round ended shortly after and no further testing was done.

![brokenbyond1](https://user-images.githubusercontent.com/16082007/39139663-6d595b42-471a-11e8-8223-1e554d464863.png)

Second case (Apr-23) - Joined to pre-game lobby. Had played previous round but auto-rejoin had failed, so I restarted the client. Chatbox did not load. Rejoining the game during the pre-game lobby did not fix the issue. Rejoining after the round had started, however (1215 station time when I tested it), the chatbox mysteriously loaded fine.

It's uncertain if the chatbox eventually loading properly in the second case was a matter of clientside delay or something different. 

![image](https://user-images.githubusercontent.com/16082007/39140725-66094f7a-471d-11e8-8a60-0065b11cb099.png)

Edit: Third case (Apr-23) - It keeps happening aaaaaaaaaaaaaaaaaaaaa
The round immediately after the one in the second case. This time, I killed byond.exe completely. Rejoining did not fix. I don't even know if its clientside at this point

#### Steps to reproduce 
It seems very random. I didn't join the game differently or notice any particular circumstances  on my system at the times it didn't load properly.

#### Length of time in which bug has been known to occur
I first had it happen yesterday, and it happened again today. I've never seen it otherwise (that I remember) but the github history suggests there have been issues relating to this for a while. They are all on older versions or don't exactly describe what I had, though.

#### Server revision
Game: 269f2e3a5c73d4c7908075fceb0cccf47121ca95 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 

#### Issue bingo

- [x] Issue could be reproduced at least once (it was random, but happened more than once)
- [ ] Issue could be reproduced by different players (uncertain)
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this] (Not exactly describing this case, but there are similar ones)

**Comment by DamianX** [comment]
Use 510
Also post your OS version + update and internet explorer version

**Comment by Inorien** [comment]
Switching to 510.1347.
OS is Windows 10 Home x64, build 1709.
Internet explorer version is 11.371.16299.0.

Edit: Joining the server on version 510.1347 had text working immediately. Given the previous behaviour, though, this may well be luck. I'll keep updating this thread when further developments

**Comment by Inorien** [comment]
Since switching to 510.1347, I've had no issues of the textbox failing to load, across several connections. 
Seems something kills it in the Byond update beyond that version and 512.1421.

**Comment by DamianX** [comment]
alright
