### ISSUE TITLE
Remove the O hotkey

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18157]
Think of all the ick ock that could be prevented.

**Comment by ShiftyRail** [comment]
To do it manually : 
![image](https://user-images.githubusercontent.com/31417754/39242978-413508fe-488c-11e8-9a6d-7e0e10f0a0d3.png)

**Comment by PJB3005** [comment]
@ShiftyRail That's a shit solution and you know it.

**Comment by ShiftyRail** [comment]
Yeah I know
I'm just spreading the word out

**Comment by Diavill** [comment]
Think of all the _hilarious_ ick ock that would be prevented

**Comment by Killette2** [comment]
😏 He uses hotkey mode...

**Comment by Inorien** [comment]
Adding to this, the manual fix for the hotkey is overwritten when Byond is updated/downdated, at least when using installers manually downloaded from the website.
