### ISSUE TITLE
Vox popped lungs breathe good

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18158]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
# Revision
269f2e3a5c73d4c7908075fceb0cccf47121ca95

# Description
I popped my lung as a vox fairly soon after joining, and i took no suffocation damage or blood loss all round. I could have really good luck, or something is wrong.

# Steps to Reproduce
Pop your lung as a vox then see if you ever suffocate?

# What you Expected
I expected to eventually die

# What Actually Happened
I did not die

**Comment by Pathid** [comment]
Well, popped vox lungs do damage in local testing. Either it's a transient bug, or maybe you got the no breathing mutation somehow.
