### ISSUE TITLE
Chemistry 101 Book issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18156]
(WEB REPORT BY: subs455 REMOTE: 172.93.109.202:7777)
# Revision
269f2e3a5c73d4c7908075fceb0cccf47121ca95

# Description
The link that the Chemistry 101 book opens has been deleted.
# Steps to Reproduce
Reading Chemistry 101
# What you Expected
To be taken to the "Guide To Chemistry" Wiki
# What Actually Happened
Got taken to the Chemistry 101 Page, which is deleted and not helpful.

**Comment by Eneocho** [comment]
works now I guess
