### ISSUE TITLE
Combining cooking ingredients with full hands destroys the product (flour+egg = dough)

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#18169]
#### Description of issue
I've had this happen with flour+egg to make dough. Holding the flour sack in one hand and an egg in the other, using the flour sack on the egg makes the egg disappear, as well as the dough you were meant to receive.
This doesn't happen if the egg is on a table. Using the flour sack on an egg on a table produces dough as expected.

#### Difference between expected and actual behavior
Dough shouldn't vanish - you should get it after you use flour on the egg.

#### Steps to reproduce 
Hold flour sack in one hand
Hold egg in the other
Use flour sack on egg
Where did the dough go 🤔 

#### Length of time in which bug has been known to occur
No idea. I just saw it today.

#### Server revision
Game: 3899bd88a590cda04ab655cdfe53d05db9af16ad 
Patches: f7b1883a4643b40f0e4c1aa07538e4260810a476 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players (untested)
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
I guess it's putting the dough inside the human
