### ISSUE TITLE
Remove mob icon from the "examine" text

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18164]
#### Description of issue
Because metagay.
I'm talking about this icon right here: 
![image](https://user-images.githubusercontent.com/6307265/39306077-66a54a9e-495f-11e8-8922-151a91dc36a3.png)
The only thing it's good for is breaking muh emulsions as I can clearly tell who is behind a disguise.

**Comment by GeneriedJenelle** [comment]
Maybe instead of completely removing it, have it actually display the clothing/items as they are in-game?

**Comment by DamianX** [comment]
May or may not be impossibly costly.

**Comment by Exxion** [comment]
`getFlatIcon()` would be required and is absurdly expensive in some cases, *especially* players
The reason why cameras are only 3x3 is that any larger runs the risk of noticeably lagging the server
It's that bad

**Comment by GeneriedJenelle** [comment]
That's horrifying.
