### ISSUE TITLE
Virus STILL not fixed?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18161]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
Some year ago I made a report about virus automatically curing itself immediately after you contract it. Someone on github said the issue was fixed yet here I am, experiencing it again. Meet me in Dorms can confirm it I guess?

**Comment by Pathid** [comment]
It's possible I messed up something in #17303. Post logs if you have them.

**Comment by DamianX** [comment]
Fixed by #20166
