### ISSUE TITLE
Suggestion : cult constructs should have a less impersonal name

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#18165]
It's relatively easy to get a soulstone and a shell as a non-cultist, and while the confusion of having both cultist constructs and non-cultist ones fighting can be fun, remembering which number is yours can be annoying and lead to "wait was it valid again" moments.

My suggestion is to allow constructs to choose a name (either from a list, or typed by themselves) to make the confusion more manageable.

**Comment by Aurx** [comment]
Idea: Key it off the soul-stoner's religion.

**Comment by DeityLink** [comment]
`[21:47:45]SAY: Marko Bomb the Juggernaut/IFlashYou (@@262,277,1) As Cult : I CANT DANCE`

...Fixed?
