### ISSUE TITLE
Can use asthma inhaler on self if mouth is protected

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18176]
#### Steps to reproduce 
- Obtain inhaler
- Click on your spessman
- You must remove your gas mask first!

\-

- Click on the inhaler itself
- It just works

**Comment by Reviire** [comment]
Clearly we need to remove accounting for the gas mask, like with pills.

**Comment by Killette2** [comment]
Eating with mask is a bad thing
