### ISSUE TITLE
Cyborgs can't lift tape

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18186]
Engineering cyborgs should be able to lift engineering/atmospherics tape.
Security cyborgs should be able to lift security tape.
To be clear, you CAN remove it but you cannot lift it/put it back down.

#### Steps to reproduce 
- Be cyborg
- Place tape
- Attempt to lift tape to allow passage
- Cry

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
tape grippers?

**Comment by DamianX** [comment]
Just the "empty hand" should work? Consistency and such

**Comment by Pathid** [comment]
It's not like we have a chair buckling gripper, etc.
