### ISSUE TITLE
AI can't emote

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18180]
#### Description of issue
AIs can't emote at all. They don't even have a `*help` thingy.
They should have at least as many emotes as pAIs have.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SirSkeleto** [comment]
I was playing MoMMI yesterday, and I was sitting outside the AI upload on box with a few carbons and the AI hologram. I pinged. The AI said "*ping". Ruined everyone's immulsions. Please fix.

**Comment by PublicEnemyMaiPai** [comment]
on this plz dont take it from me
