### ISSUE TITLE
Plasmamen lose their special flames when cloned.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#18196]
#### Description of issue
Normally plasmaman have a unique on fire sprite, but when you get cloned you lose it.

#### Difference between expected and actual behavior
Retaining my cool flames after being cloned instead of getting the normal ones

#### Steps to reproduce 
All it takes is being cloned.

#### Specific information for locating
Something that might be related i'm not sure, is health analyzers show roundstart plasmaman as 100% blood, but when you get cloned and have the normal flames they register you as proper 0% blood.

#### Length of time in which bug has been known to occur

I'm sure it's been around a while, i'm surprised I never noticed I had the normal flames while being dragged to cryo tube sooner.

#### Server revision

Revision: f5b9e6985f4586543d472af4737385dc0549c929

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SonixApache** [comment]
the obvious solution is to remove plasmemes

**Comment by Exxion** [comment]
Presumably checking mob type rather than `species`
