### ISSUE TITLE
Make lightswitches layered on top of darkness

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18195]
So that you can see them in the dark.

**Comment by MadmanMartian** [comment]
Thats not how any of this works

**Comment by DamianX** [comment]
Care to explain?

**Comment by Ephx1** [comment]
Couldn't you just make it so that they have an additional red/green sprite that works in the dark, like cyborg sprites do?

**Comment by MadmanMartian** [comment]
why would light switches be visible at all times?

Most of them is dark grey metal, and the light they have to signify they're on is only on when the light is on.

**Comment by DamianX** [comment]
Okay perhaps I should explain better
I liked how Bay did this:
![image](https://user-images.githubusercontent.com/6307265/39440291-bd16eeb6-4caa-11e8-99e6-4bc7b2e6639d.png)
![image](https://user-images.githubusercontent.com/6307265/39440302-c2730656-4caa-11e8-9cae-88467ffcc396.png)

Is this somehow worse than Hitler?

**Comment by Ephx1** [comment]
Oh, that's exactly what I was saying. :+1:

**Comment by MadmanMartian** [comment]
yeah, that's cool
