### ISSUE TITLE
Scientists can't open weed control crates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18200]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
Which makes no sense considering Xenobotanists and the fact that it isnt even dangerous stuff

**Comment by jknpj** [comment]
xenobotanist isn't a job

**Comment by DamianX** [comment]
They can open seed crates since #16694 though

**Comment by jknpj** [comment]
well, damn

**Comment by Kurfursten** [comment]
I guess when you have bombs and guns at your disposal, scythes and toxin grenades don't even class as dangerous anymore

**Comment by Killette2** [comment]
xenobotanist being a science title was a mistake. It should have stayed in botany, where it's actually relevant.

**Comment by Exxion** [comment]
Then they'd need access to the science outpost, where xenobotany *is*
Station hydroponics isn't configured as well for xenobotany, because it's mostly for growing food
