### ISSUE TITLE
Appendix surgery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18201]
(WEB REPORT BY: tobiaskunst REMOTE: 172.93.109.202:7777)
# Revision
83e1ff97d4515785807422f91be9e50e269fbc92

# Description
When I did the surgery to remove a appendix and followed all steps the appendix still showed up on the health scanner. Patient also recieved toxins damage, even though the surgery was a success.

# Steps to Reproduce
Remove appendix from a patient with appendix problems.
Afterwards check with healthscanner.
# What you Expected
Patient is cured and healthy
# What Actually Happened
Appendix still showed up and patient died

**Comment by Pathid** [comment]
Reminds me of #15167. Maybe it's similar.
More info is necessary since this isn't something that happens every time an appendectomy is done.

**Comment by nervere** [comment]
Unable to replicate this when patient has appendicitis.
