### ISSUE TITLE
Appendectomy don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18202]
(WEB REPORT BY: tobiaskunst REMOTE: 172.93.109.202:7777)
# Revision
83e1ff97d4515785807422f91be9e50e269fbc92

# Description
After a successful appendectomy the appendix still showed up on the health scanner. Patient recieved toxins in huge amounts and died.
# Steps to Reproduce
Follow the appendectomy from the wiki.
Check patient with health scanner afterwards
# What you Expected
Patient is healthy and lost his appendix.
# What Actually Happened
Patient got appendix removed,died due rising toxins level.
Health scanner still showed the appendix as a reason.

**Comment by jknpj** [comment]
#18201
