### ISSUE TITLE
Genetic speech filters don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18216]
(WEB REPORT BY: otatoh REMOTE: 172.93.109.202:7777)
# Revision
a4f9afe2fafdf112acdfa0478b20ef1cd4c6c927

# Description
Genetic disabilities that should give you speech filters (chav, lisp, whisper, shouting, etc) don't work.

# Steps to Reproduce
Give yourself genetic speech disability, then talk. 

# What you Expected
Speech filter 

# What Actually Happened
Nothing

**Comment by MadmanMartian** [comment]
unable to reproduce. Am currently a jive talking swede
![bork](https://user-images.githubusercontent.com/30557196/39837162-848a22d2-53cd-11e8-8b9f-bbed597ca206.PNG)

**Comment by DamianX** [comment]
Does activating them via mutagen or genetics work?

**Comment by MadmanMartian** [comment]
yes

**Comment by gbasood** [comment]
It's probably more likely the gene just didn't activate
