### ISSUE TITLE
Viruses reveal identity

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#18215]
Was playing last night in disguise with no ID, but then I started noticing my real name being revealed in virus emotes despite my disguise. I can't remember exactly which ones, but I believe shivering was one of them.

**Comment by MadmanMartian** [comment]
It's literally making you talk/emote. Unable to reproduce with the shivering virus.

**Comment by MadmanMartian** [comment]
![shivermetimbers](https://user-images.githubusercontent.com/30557196/39838123-5716acaa-53d0-11e8-9c5a-c351f8f20780.PNG)

**Comment by Killette2** [comment]
Maybe it wasn't shivering. Do any of them not do this?

**Comment by DeityLink** [comment]
The only symptom that COULD technically expose your identity is Necrosis, as chunks of meat falling off you are named after your real name. Other than that, no symptom uses real_name.
