### ISSUE TITLE
WRONG TABLE NERD

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18214]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
135cbe0ab1da6f4c72c5533ef86157f73ba89cb4

# Description
The wooden table in dormitories above the treadmill generator in the vox outpost on Box Station is a /obj/structure/holotable/wood and therfore cannot be wrenched. needs to not be holo lads.
# Steps to Reproduce
go to where i said and look at it
# What you Expected
it to be a normal everyday wooden table
# What Actually Happened
i was rused

**Comment by Kurfursten** [comment]
>Vox can't even afford real tables
>Put up hologram table instead
