### ISSUE TITLE
Morphin Mask Ghost Death

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18219]
(WEB REPORT BY: godzillakotm REMOTE: 172.93.109.202:7777)
# Revision
a4f9afe2fafdf112acdfa0478b20ef1cd4c6c927

# Description
Found a morphing mask that turned me into a hologram, I floated around for a bit and suddenly I'd turned into a ghost with no body to re-enter. Only thing left of me was my ID lying on the ground.
# Steps to Reproduce
Equip a morphing mask (Hologram) then float around a bit and see what happens.
# What you Expected
To float around as a hologram then take the mask off.
# What Actually Happened
Floated around as a hologram for about 5 seconds then turned into a ghost.

**Comment by Kurfursten** [comment]
@jknpj no longer an issue as of #18364
