### ISSUE TITLE
Immovable Rod and Wooden Walls issue

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#18213]
alright, here's how it goes, dunno if it's actually intended or not.
\>Rod is spawned
\>Rod goes throught wooden walls
\>While deleting the wooden walls the rod also deletes the floor tiles, turning it on space tiles and causing major breaches around places like bagel's dorms/library

**Comment by Pathid** [comment]
Thanks for reporting this, man. Meant to report it myself a while ago. It's made worse by the fact that you can't build wooden lattices or decks on space.
