### ISSUE TITLE
Pneumatic Scythe doesn't fit on a Clarke Mech

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18226]
(WEB REPORT BY: bittervanilla REMOTE: 172.93.109.202:7777)
# Revision
1faa6fe0f889eb5489d2a6ac6207317adbd91f24

# Description

The Heavy Duty Pneumatic Scythe  description says that it can be attached to maintance exosuits, but it wont fit on a Clarke.

> That's a Heavy Duty Pneumatic Scythe. It is a huge item. An extremely heavy-duty pneumatic scythe. The "giant robot" approach to weed control. (Can be attached to: Maintenance Exosuits)

# What you Expected

It'd fit in a Clarke Mech. It's a maintance mech, right? Either that or the description should be made clearer - Only attaches to Ripley and Ripley-sub types

# What Actually Happened

'You were unable to attach the Heavy Duty Pneumatic Scythe to Clarke'

**Comment by Pathid** [comment]
Updating the description sounds good. The scythe is very good at the one thing it does and there should be things the Ripley can do that the Clarke can't.

**Comment by BitterVanilla** [comment]
There are already a couple of degrees of seperation between the Ripley and the Clarke - you can't attach any drills to the Clarke and make it a speedy mining tool  and none of the engineering exosuit tools (cable layer, RED Module, Engineering Switchtool, Metal Foam Grenade Launcher, Automatic Floor Tiler, Inflatable Barrier Launcher) will fit on a Ripley.

Having a scythe be able to fit on both wouldn't be unreasonable, I think. If there're concerns about having a speedy human slasher harm mech around, it doesn't do that much damage in comparison to the clamp, and you can always lock the harm away like the harm-squeeze Hydraulic Clamp has
>WARNING: OSHA regulations prohibit use of the Hydraulic Clamp in that way.

Personally I think the Clarke is fast for no good reason but that's not really a bug to report.

**Comment by Pathid** [comment]
The scythe is already very good at trivializing an antag botanist who grew deathvines. It one-shots all vines in a 3x3 square even if they have the trait that makes them resistant to normal scythes. Doing that at mach speed is kind of gratuitous.

**Comment by jknpj** [comment]
clarke can't equip weapons, period.
