### ISSUE TITLE
Advanced Security Cameras and Buckling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18234]
(WEB REPORT BY: wyattham REMOTE: 172.93.109.202:7777)
# Revision
46d13b176ac33528c011e7b3c4d4c9cb1b737a0e

# I noticed that when you buckle to a chair you cannot use advanced security cameras...

# Grab a chair, grab a advanced security camera console, use. Also, i used a folding chair when i did it... just to say.

# Cameras!

# Jack shit.

**Comment by DamianX** [comment]
I'm still not sure what Steve has to do with this.

**Comment by west3436** [comment]
Advanced security camera console was removed in #30607
