### ISSUE TITLE
Mapping Requests: Arctic Waste

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#18230]
Every single time I open this gateway mission people die because they go in without internals or winter coats. It's also really hard to make sure they arrive at some sort of safe zone because they can spawn in a HUGE WIDE AREA.

My requests are
* Add air to all the snow tiles so that it's only a cold hell not an airless one
* Restrict where it places you to a small area (perhaps even only inside the gateway room down that ladder?)
* Make the borders actually invulnerable. Going into space in this area is obviously not intended and it's possible to get stuck on the z-level edge because it has no transitions

Some default content like wolf mob spawners or a fishing pond or something would be nice too.

**Comment by ghost** [comment]
change it to the proper snow tiles

**Comment by Aurx** [comment]
Fact: Space is cold.  
Fact: Snow is cold.  
Conclusion: Space is snow.  
Fact: Space has no air.  
Conclusion: Snow has no air.  

Everything seems to be working as intended.

**Comment by Irradiation** [comment]
Can't argue with Aurx's logic.
