### ISSUE TITLE
Advanced Security Cameras, and Radical Steve

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18233]
(WEB REPORT BY: wyattham REMOTE: 172.93.109.202:7777)
# Revision
46d13b176ac33528c011e7b3c4d4c9cb1b737a0e

# I noticed that when you are buckled to a chair you can't use advanced cameras...

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment]
leave radical steve out of this

**Comment by DamianX** [comment]
duplicate of #18234 I guess
