### ISSUE TITLE
All-In-One Grinders Should have Larger Capacity Request

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#18236]
To keep it a simple example, if a botanist decides to make snowflake meds via plants for Medbay, one of the things that makes this tedious is that a full All-In-One tends to fill up with whatever produce, grinds, must be filled again with the plant bag, then ground again.

I think that if All-In-One grinders had more capacity in that manner everyone would benefit.

**Comment by Irradiation** [comment]
I think the idea is that you're supposed to jarass R&D until they cave in and give you upgraded components for the grinder.

**Comment by ghost** [comment]
This is such a trivial QoL thing that it feels stupid to lock it behind R&D.

Also, fuck R&D.

**Comment by Pathid** [comment]
Tier 3 matter bins don't take any rare materials by the way.

**Comment by Kurfursten** [comment]
It's bizarre that no one in here seems to realize that all in one grinders have no capacity at all, it's based on the beaker you choose to insert. The limit of 100 is because you're using a large beaker.

If you want more you need a bluespace or large bluespace beaker.

**Comment by Pathid** [comment]
The input hopper has a capacity though.

**Comment by Kurfursten** [comment]
Oh yeah, that's true. Much less tedious than repeatedly changing out the beaker though, when your potency is high you're getting 50u per plant, so potentially 500u per bag dump.

**Comment by Killette2** [comment]
Processor being able to hold more than 1 thing at a time when?

**Comment by nuklearcellphoneg** [comment]
Being able to hold more plants in the processor means less swapping to the plant bag to refill the processor as you grind into presumably a box of small beakers you got off medbay or waited for cargo to make. 

This in turn can less tediously lead to opium and perhaps tannic near round start which helps to achieve opiudine or kelotanniderma

**Comment by ringringllingling** [comment]
The choke point is the beaker, not the hopper.  Just get a bigger beaker.

**Comment by Killette2** [comment]
No I mean the thing that turns potatoes into fries

**Comment by nuklearcellphoneg** [comment]
I used 14 large beakers last night for grinding poppies with opium and tannic as well as honey. On the plants it took two plant bag fills per large beaker.

For the sake of balance it should hold as much as can be ground up to fully fill a large beaker.

As an aside I imagine it would take 3-4 plant bag fills for a blue space beaker

**Comment by SonixApache** [comment]
In the time it took you to use 14 large beakers to meme you could've walked to R&D and acquired a bluespace beaker, a screwdriver, a crowbar and 2-3 super matter bins.

Non-issue.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is effectively solved

**Comment by Kurfursten** [comment]
@Exxion

**Comment by Exxion** [comment]
Solved how? I'm a bit behind on developments
