### ISSUE TITLE
Beekeeper Request

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#18235]
Beekeepers should start with one queen bee packet. :^)

**Comment by Blithering** [comment]
Can ranchers start with a backpack full of chickens?

**Comment by nuklearcellphoneg** [comment]
It's possible to be a beekeeper and not be able to grow bees as it stands, in accordance with an awful set of circumstances.

If they start with a single queen bee packet, they can at least grow wood for an apiary and start their bees.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is literally already a thing @Exxion

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
H-He's fast!

**Comment by Exxion** [comment]
I didn't even notice it had only been seconds
Lucky timing
