### ISSUE TITLE
Duplicate Wiki's

### ISSUE THREAD

**Issue by ringringllingling** [d3athrow/vgstation13#18247]
We have a wiki at both wikia and our local server

>http://ss13.moe/wiki/index.php/Main_Page
>http://vgstation.wikia.com/wiki//vg/_Station_Wiki

Maybe we should consolidate / update them.

**Comment by MadmanMartian** [comment]
I don't think the latter is official

**Comment by DamianX** [comment]
It isn't, and this is not a code issue.

**Comment by Durgen** [comment]
http://vgstation.wikia.com/wiki/Special:Log?limit=500&month=&year=
