### ISSUE TITLE
Dialogue Filters

### ISSUE THREAD

**Issue by ringringllingling** [d3athrow/vgstation13#18246]
I would like our coders to add some text filters that filter Game Description and Dialogue separately.

For example, if someone was trying to inject someone forcibly with a syringe, that would be game description, while someone screaming "Halp Security greifin me!" over the intercom would be Dialogue.  

In addition, I would also like the ability to filter radio, local, and emotes separately.

**Comment by Blithering** [comment]
I don't think that the ability to tune out things like that would make for a better experience, you don't pick and choose what you hear and see. This and the other feature request you made both seem like methods of opting out of any form of roleplay or interaction that isn't to do with valids

**Comment by SonixApache** [comment]
@Blithering what if he wants to roleplay as someone with severe autism

**Comment by ringringllingling** [comment]
ideally, you would have two separate feeds, so you can still see both the description and the chat dialogue.  I know this would require changes to the GUI, but I think it would result in massive improvement in user experience.
