### ISSUE TITLE
Shrapnel gone, pain in chest remains

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18259]
(WEB REPORT BY: mchotnspicy REMOTE: 172.93.109.202:7777)
# Revision
04cb05a7b7eecf7c2df0e2cbaf097a9d0414f48d

# Description

What the title says. The docs cant find anything wrong with me, so it may be a bug.

# Steps to Reproduce
1. get shot but buckshot whilst wearing sec armor 2. remove shrapnel in surgery 3. feel woozy
# What you Expected
to feel fine
# What Actually Happened
i feel faint

**Comment by jknpj** [comment]
STANDING

edit: isn't woosey because the blood loss?

**Comment by Pathid** [comment]
"You feel faint/dizzy/woosey" is from bloodloss. Eat something, drink iron or get a transfusion.
