### ISSUE TITLE
Megaphones are busted

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18279]
#### Description of issue
Megaphones don't let you talk in 
# BIG LETTERS 
anymore.

#### Difference between expected and actual behavior
Expected to talk in
# BIG LETTERS.
Instead I talked in NORMAL SIZE LETTERS.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Mothblocks** [comment]
you could never talk into them from reading the code

you click on them and then they're loud

**Comment by Pathid** [comment]
@Jared-Fogle Try it. Doesn't work.

**Comment by ddolll** [comment]
Megaphones worked for me in fd7aa65ce51c014a96c70d348d0b93bfd5641dcc
