### ISSUE TITLE
Bolas can't fit in sec suit storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18281]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
7fb33f7aac417f78560ea6f400f48ce4e733288b

# Description
See title
Looks like an oversight since most of other sec items do

**Comment by ShiftyRail** [comment]
It was with a sec normal armour
Doesn't imagine it fits on hardsuit/ablative/riot as well
