### ISSUE TITLE
MMI Mechs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18288]
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 172.93.109.202:7777)
# Revision
162de49296ae65f01355de54824683c01c36ccab

# Description
As mmi you are blind. When put in a mech the blindness presisted as mmi mech.
# Steps to Reproduce
Try putting and mmi player in a mech
# What you Expected
To just enjoy the tormented existance that is mmi mechs
# What Actually Happened
Double torment

**Comment by Pathid** [comment]
MMIs being blind is the bug. They are not supposed to be blind (except in the case of EMP damage that heals over time) and they are not always blind, only sometimes.
