### ISSUE TITLE
Summon cultist

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18282]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
7fb33f7aac417f78560ea6f400f48ce4e733288b

# Description
Summoned cultist ended up being nullspaced after summon rune WORKED

# Steps to Reproduce
Summon someone, probably in a room with people

# What you Expected
Cultsit appear and stay

# What Actually Happened
Cultist appeared and disappeared after half a second. Ended up in nullspace(which effectively cucked cult as they still appeared on summon cultist rune but couldn't be summoned)

**Comment by Pathid** [comment]
You know if they were locked to anything? Maybe inside a vehicle?

**Comment by DamianX** [comment]
is this reproducible?

**Comment by DeityLink** [comment]
The new Blood Magnetism rune that replaces the old Summon Cultist one works differently. This is now outdated/legacy.
