### ISSUE TITLE
How to get to cent generations ultimate

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#18283]
#### Description of issue
The bad effect of the single use book of push can teleport you to any area, even to z2.

#### Difference between expected and actual behavior
Expected: Sanity
Actual behavior: TELEPORT INTO ANY AREA, VAULTS, CENT, WIZARD DEN, OPS SHUTTLE

#### Steps to reproduce 
Use the book, give it to other people

#### Specific information for locating
![mooods](https://user-images.githubusercontent.com/17928298/39974158-301675ce-56fd-11e8-8ecb-1be104086a9d.png)
**Local chaplain looting Z2 in the middle of ragin mages**

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Reviire** [comment]
Wizard rounds did nothing wrong. They must be whacky, this is a f e a t u r e. Wizards, seraphs, assorted random antags.
