### ISSUE TITLE
Packed engineering access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18308]
(WEB REPORT BY: majesticmastodon REMOTE: 172.93.109.202:7777)
# Revision
bfdda846636eac7dba837336b393963cfdcc3940

# Description
Mechanic doesn't have engineering access on Packed

# Steps to Reproduce
Just be a mechanic on packed and go to engineering
# What you Expected
For the doors to open so I can take glubbs and singuloose
# What Actually Happened
The doors didn't open

**Comment by Kurfursten** [comment]
Engineering actually consists of a few different accesses, atmos, engine_equip and engine, the second is for the equipment room/lobby and mechanics have that, the ladder is for the actual engine rooms like SME, AME, etc. on Box. You can't get in the front door or left maint entrance?

**Comment by ghost** [comment]
Mechanic doesn't have access to the front door or maint areas, you basically have to hack/deconstruct to get it.
