### ISSUE TITLE
Drink Sprites

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18305]
(WEB REPORT BY: nomixam REMOTE: 172.93.109.202:7777)
# Revision
bfdda846636eac7dba837336b393963cfdcc3940

# Description
I went to mix the drink Wake Up Call and after doing so the unique sprite for it failed to appear. instead only being a regular Drinking Glass with brown coloring.
# Steps to Reproduce
Mix Coffee, Beepsky Smash and Sprinkles.
# What you Expected
For the unique sprite on the wiki to appear.
# What Actually Happened
An ugly boring sprite appeared.

**Comment by Exxion** [comment]
Not a bug. Wake Up Call is a cafe drink, and as such needs a mug rather than a glass to get the unique sprite.

**Comment by DamianX** [comment]
Do we explain this anywhere?

**Comment by Exxion** [comment]
Not as far as I know, so
