### ISSUE TITLE
Skeletons can die of oxyloss if they have asthma.

### ISSUE THREAD

**Issue by toomykins** [d3athrow/vgstation13#18338]
#### Description of issue

Skeletons can have asthma.
Ashtma kills the skeleton.
no identifier for why you're dying, at all.

#### Difference between expected and actual behavior

lol i dont have to breathe

#### Steps to reproduce 

be geneticist and fuck yourself up with skeletonese and asthma

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
Do skelememes even have internal organs such as heart/lungs ?

**Comment by jknpj** [comment]
hotfix: remove skeletons

**Comment by DamianX** [comment]
It checks for M_NO_BREATH but not for the species-specific thingy

**Comment by SonixApache** [comment]
The obvious solution is to remove skelememes.

**Comment by jknpj** [comment]
why do skeletons breath

**Comment by ShiftyRail** [comment]
>why do skeletons ~~breath~~ exist
