### ISSUE TITLE
Cyborg eaten by the singulo doesn't really die

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18334]
(WEB REPORT BY: thmg REMOTE: 172.93.109.202:7777)
# Revision
793555b2fd0e1d3f4d1fee34e53c3c37b0a3f662

# Description
Got near the singulo, game displayed the destroyed sprite but I was still able to fire my taser gun and use my other modules.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Pathid** [comment]
Return of #15382
Happened to me a couple days ago.
