### ISSUE TITLE
Custom vendors could be better

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#18346]
I know these have been in development for a while with gradual changes, and I recall vending machines are in general a pain in the ass to modify/get working, but some stuff that would be cool:

- Option to make sold out items disappear (or be able to remove them manually)

- Objects stacking if they have the same name (probably with some sanity if it's been renamed)

- A log in window like the ATM instead of having to unscrew the machine for real?

Only actually gave this a go one round as Trader so it's perfectly possible I did stuff wrong too.

**Comment by SonixApache** [comment]
could give the EFTPOS an actual purpose

**Comment by kilozombie** [comment]
`could give the EFTPOS an actual purpose`

That'd be neat.

Right now custom vendors are right on the cusp of being really great and helpful, but still it's a little too clunky to buy from or insert items conveniently.

**Comment by Kurfursten** [comment]
@Exxion all of this was fulfilled
