### ISSUE TITLE
Exosuit Fabricator looses Ultra-laser uprgade after synching with research

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18356]
(WEB REPORT BY: bigkuro REMOTE: 172.93.109.202:7777)
# Revision
6bdd0f18dc463ea9ad94b7f532251b42b37e08c6

# Description
The exosuit fabricator looses its ultra-high-precision micro-laser upgrade when it is synched up with research, making it fabricate at least three times slower.

# Steps to Reproduce
Unscrew an exosuit fabricator, upgrade it with a rapid-part exchanger with ultra micro lasers in it, rescrew the fabricator, unscrew & rescrew the robotics console or use the robotics console to synch up near devices, then head to the exosuit fabricator and press the synch up button. 

# What you Expected
The fabricator to fabricate faster after upgrading it and synching up with research to expand the list of available items.

# What Actually Happened
While it does synch up with research, the fabricator looses its ability to fabricate faster.

**Comment by Pathid** [comment]
Somehow I missed this when I updated RefreshParts() for fabricators:
https://github.com/vgstation-coders/vgstation13/blob/5b1ac5880f7824e5850dbdca9bf558cc1a02bcf0/code/modules/research/fabricators.dm#L400-L428

It's for making materials and data tech improve efficiency and speed respectively but it's all screwed up.
