### ISSUE TITLE
Point of sale products

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18359]
(WEB REPORT BY: awsmnamedude REMOTE: 172.93.109.202:7777)
# Revision
aaa9e8dd712a893a6d34a8e68cba284f3e604c9d

# Description
I added an item to a point of sale to sell burgers, but when I try to add additional products the window is blank

# Steps to Reproduce
put a single item into a point of sale and try to put more produts in

# What you Expected
I should be able to pu in many products

# What Actually Happened
onlyone product was able to be put in, or maybe I have to put in many at the same time?

**Comment by Dacendeth** [comment]
You might be the first person to attempt to use these in years.

**Comment by PaulRitter** [comment]
tested, works with multiple items
