### ISSUE TITLE
Grilling a slider on a plate produces a grilled slider on a plate + a normal slider

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18357]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
6bdd0f18dc463ea9ad94b7f532251b42b37e08c6

# Description
Grilling a slider on a plate produces a grilled slider on a plate + a normal slider.
# Steps to Reproduce
Produce a slider (10 flour, 2 meat for 4x sliders)
Place slider on a plate.
Place plated slider on grill.
Recieve grilled slider plate + ungrilled slider.
# What you Expected
One grilled slider on a plate.
# What Actually Happened
Slider duplication!

**Comment by SonixApache** [comment]
this got abused less than 15 minutes after this report

**Comment by DeityLink** [comment]
Fixed by #30190
