### ISSUE TITLE
Peekaboo crates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18372]
(WEB REPORT BY: orangerush REMOTE: 172.93.109.202:7777)
# Revision
daff71be25d4b4a45bb3bd3dd3cfa74b872cfe55

# Description
Crates on deff (maybe other maps) like to hide under conveyor belts apparently

**Comment by SonixApache** [comment]
I've been noticing a lot of stuff being under stuff it shouldn't be. Like, stuff under racks, stuff under machines...

**Comment by Pathid** [comment]
Yeah, it's an issue with 512. I'm fairly sure it doesn't happen with a 511 client.

**Comment by toomykins** [comment]
have never seen this happen on 510. it's a 512 bug for sure.

**Comment by Exxion** [comment]
Does anyone happen to know what version of 512 it started on?

**Comment by Pathid** [comment]
@Exxion I had the impression that #16743 was from the same cause.

**Comment by Exxion** [comment]
You appear to be correct.
It also appears not to be a bug at all. Both `plane` and `layer` are the same for conveyor belts and crates, so the order they render in is arbitrary. It's surprising it was ever consistently *not* this way.
I suspect 512 changed how the renderer decides what order to draw things in when not explicitly told.
The solution, of course, is to just explicitly tell it.
(In this case I recommend setting the default `layer` of conveyor belts to `TABLE_LAYER`, or maybe `BELOW_TABLE_LAYER`)
