### ISSUE TITLE
Visor helmets are really cool but don't support tactical flashlights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18387]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
27e37d5b3cac1cf323cf763702663557eaad9a29

# Description
Visor helmets are really cool but don't support tactical flashlights
# Steps to Reproduce
Attempt to attach a tactical flashlight to a Visor Helmet
# What you Expected
Tacticool visor helmet
# What Actually Happened
My face is protected but I can't see shit in the dark

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Close this
