### ISSUE TITLE
Gold Atmos Suit doesnt hold socket wrench

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18385]
(WEB REPORT BY: gelatinousglob REMOTE: 172.93.109.202:7777)
# Revision
27e37d5b3cac1cf323cf763702663557eaad9a29

# Description

Apply gold suit mod kit to atmos suit, suit no longer holds socket wrench in the suit slot.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Hugh-G-Rection** [comment]
Sounds like a good time to bring back  `allowed = list(/obj/item/weapon/)`
