### ISSUE TITLE
Freeze screen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18394]
(WEB REPORT BY: mrslippy REMOTE: 172.93.109.202:7777)
# Revision
6cddeb8a369faf3a0be97471608c91e6b54c63f8

# Description

I can't see shit nigga. Screen is frozen 

# Steps to Reproduce

looc said it has happend to a few fokes, I changed my IU color, reconnected and was met with a black graphics pannel. Text works fine. anytime the window is resized its black

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment]
Use 512.1425

**Comment by Exxion** [comment]
Or higher
