### ISSUE TITLE
Feature Request: "Doesn't Tip Note" Traitor item

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#18402]
-Doesn't Tip Note
\>Chef / Quartermaster Traitor Item
\>Costs 10 TC's
\>Upon Purchasing it, all cargo pizza orders for the rest of the round are sabotaged

**Comment by Tokanova** [comment]
can you make it so if the note is destroyed the pizzas go back to normal?

**Comment by Pathid** [comment]
What should happen if it's already bought by somebody else?

**Comment by Jubisloviu** [comment]
@Tokanova that's a nice idea, make it so you need to incinerate the note to turn the pizza orders back to normal
@Pathid they get double sabotaged and a syndicate pizza delivery killbot can show up on cargo shuttle from time to time

**Comment by MadmanMartian** [comment]
what forms of sabotage?

The crate is a mimic?
The pizzas are in fact razors?
The pizzas contain superacid?
There is no pizza, it is in fact 'GO TO THE KITCHEN'?

**Comment by SonixApache** [comment]
pizza bombs

**Comment by Jubisloviu** [comment]
@MadmanMartian 
margherita - poisoned
mushroom - full of acid
meat - random viruses on it
vegetable - mutagen

**Comment by Killette2** [comment]
mushroom pizza should be spiritbreaker, or at least mindbreaker
margherita could contain nothing but discount dans cheese related stuff and his sauce
