### ISSUE TITLE
Shooting ray of light at the back of your throat instantly kills you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18406]
(WEB REPORT BY: crudequip REMOTE: 172.93.109.202:7777)
# Revision
f1a681fe05c963ec847d28687170808117d366f8

# Description
i stick the laser tag gun in my mouth and pull the trigger, killing me instantly

# Steps to Reproduce
suicide with laser tag gun

# What you Expected
a funny meme where the gun fires and nothing happens

# What Actually Happened
mcfucking dead

**Comment by DamianX** [comment]
same as #15236

**Comment by strawberrytan** [comment]
This is a feature

**Comment by jknpj** [comment]
same as #15236
