### ISSUE TITLE
Can't melee spacepods

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18413]
Can't seem to hit spacepods with melee attacks of any kind, unlike mechs. Incidentally this means that something like a xeno or a construct has no hope of doing anything to them.

**Comment by Killette2** [comment]
Are you sure messages just don't pop up? Sometimes you can hit things without attack animations

**Comment by Pathid** [comment]
Yes. It's fully tested. Also I can see in the code the lack of anything that would handle melee attacks.
