### ISSUE TITLE
Xenoarch Masks cheat death

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18411]
(WEB REPORT BY: thewhargoul REMOTE: 172.93.109.202:7777)
# Revision
b8ac96dead146bcaf0fd4f1abe980c6069f16d83

# Description
>Get Mask of wendingo from wardrobe
>Put mask on, become Wendingo
>Jump into space, die as wendingo from space
>see deadchat, can talk in deadchat
>Hit revert form
>come back to life as normal sprite w/ revert to your status prior to putting on mask
# Steps to Reproduce
See above
# What you Expected
Mask fuckery
# What Actually Happened
Super mask fuckery

**Comment by Shadowmech88** [comment]
#18206 should have fixed this.

**Comment by MadmanMartian** [comment]
maybe something's death() isn't making a super call?

**Comment by MadmanMartian** [comment]
can't reproduce. Have been blowing self up as a wendigo, as a mouse, and it triggers the untransmogrify.

**Comment by Shadowmech88** [comment]
Specifically blowing yourself up? The post mentioned dying from space exposure.
It's possible the inconsistency is due to `ex_act()` being a factor.

**Comment by MadmanMartian** [comment]
blowing self up, getting tased as a mouse, and dying to space exposure
