### ISSUE TITLE
Resting and taking out a cyborgs cell causes the cell to vanish

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#18424]
#### Description of issue
If you are laying down and click a borg with it's cover open you remove it's cell and the cell vanishes and the borg becomes unpowered.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
pretty sure i know what is going on
