### ISSUE TITLE
MetaClub escapepods

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18436]
(WEB REPORT BY: mrbimbles REMOTE: 172.93.109.202:7777)
# Revision
2995e9f2058dea5c18fbbe46149d306b639a1aae

# Description
Meta Club pods don't launch with shuttle but still appear at centcom when shuttle arrives.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Pathid** [comment]
Is this repeatable? If it's a single case, it's possible it was due to an admin messing with the shuttle panel.

**Comment by Duny-** [comment]
Works on my machine

**Comment by Exxion** [comment]
CNR and old
