### ISSUE TITLE
Simple animals don't get environmental hazard warnings

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18431]
Simple animals can be vulnerable to many of the same environmental hazards that complex mobs are, but they usually have no way to tell except by seeing their health go down. No pain overlays in most cases either, meaning the corners of the screen becoming red. The kPA, O2, toxins and temperature warning HUD elements should all be standard.

**Comment by jknpj** [comment]
Simple animals were never meant to be controlled by players, they're SIMPLE for a reason. But then again, screen alarms when?
