### ISSUE TITLE
wonderful wardrobe has no sanity checks

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#18442]
#### Description of issue
that dang thing has vamp masks in it and shit

![it was traitor](https://user-images.githubusercontent.com/27335385/41069875-be953b32-69bd-11e8-9346-0d410d533b68.png)

(gamemode was autotraitor, vox became vamp via the mask)

**Comment by Allspice** [comment]
why don't we just remove the fucking birds already yo

**Comment by jknpj** [comment]
>vox gets free antag and a mask of spider queen in the same round

@Kurfursten seems like spessmart in a locker wasn't a good idea after all

**Comment by Sooose** [comment]
Traders getting a free roll at vamp round start seems a little silly, doesn't exactly require any effort.

**Comment by DamianX** [comment]
I think this was discussed in the PR that added it. Getting cool antag items was apparently okay because you could also get bad things (like a real facehugger, and ??? what else?).  The obvious solution is to make the masks not work on traders so that they have to sell them :)

**Comment by Dacendeth** [comment]
add a blacklist and double the clothes that come out, so maybe just once the birds will have a matching set of cool plasmaman suits to buy.

**Comment by SonixApache** [comment]
i like the idea of making the masks not work on traders (or even better, vox in general)

**Comment by Kurfursten** [comment]
That's not what sanity means 🤔

**Comment by DamianX** [comment]
INSANE loot inside

**Comment by Durgen** [comment]
What are the chances of a vamp mask coming up?

**Comment by Kurfursten** [comment]
(1/all clothing items)*20

**Comment by Exxion** [comment]
Apparently there already is a blacklist
It uses exactly the same list of clothing that Spacemart does
This excludes the infinite vamp mask, but (apparently intentionally) not the one-use one

**Comment by Kurfursten** [comment]
Yep, that's how it was made. To be clear I don't really have strong feelings about this one way or the other. Though maybe all antag clothing should be taken off the spessmart masterlist instead of creating a second snowflake list. I mean, they only cost $150 at the store.

**Comment by Kurfursten** [comment]
I did some quick maffs based on the length of the all clothing item list and estimate our clothing items somewhere in the ballpark of 1200, which makes the chances of rolling any one particular item about 1.6% per shift you buy the wardrobe. Someone who wants a more accurate count can open the create object menu in the game panel and by hand count all /item/clothing.

**Comment by Durgen** [comment]
that seems like low enough rarity that it isn't actually a problem

**Comment by Accipitermaris** [comment]
It also has the Nuke Ops Holochip which a Vox Trader used to loot the Nuke Ops shuttle one round.

Pretty funny, but I think if people knew that this sort of stuff was going to be in the code for good they probably wouldn't have been as supportive of it. I can't really think of any other jobs in SS13 that we would give a similar "free pass" to, code wise.

**Comment by SonixApache** [comment]
Honestly, with how dull rounds can be, we might as well leave it in. Just a shame that the birds are infinitely more likely to use the item itself than they are to just trade it.

**Comment by Allspice** [comment]
this reminds me of when bags of holding were removed from the trader vend because they didn't have an incentive to trade it
