### ISSUE TITLE
Teleporters, Ablative, Lasers

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#18444]
![image](https://user-images.githubusercontent.com/6540760/41097978-ec169fb4-6a27-11e8-8fdf-02a5036d61eb.png)

Set up two portals. Shoot a laser through while wearing ablative, get lucky, have it reflect, step out. See picture.

**Comment by Exxion** [comment]
You don't need the ablative for this. You can just shoot the laser straight into the teleporter that the hand teleporter is set to to achieve the same effect.

**Comment by Exxion** [comment]
Oh right
Duplicate of #11890
Other than the part about the sprites facing the wrong way, which is a separate issue entirely
