### ISSUE TITLE
[Feature Request] Make the chemistry gripper less painful to use

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#18457]
Chiefly, maybe make it so you can drop items without unequipping the module. 

Like make the first "drop" command drop the beaker, then the second puts the module away, or something, instead of having to constantly unequip and re-equip the gripper any time you need to grab a different beaker.

**Comment by Pathid** [comment]
@Hoshi-chan There's an action button just for that. But that double-drop control scheme seems more ergonomic, yes.

I'll add that examining the gripper doesn't examine the beaker it's holding, and it really should.

**Comment by Leapthatwall** [comment]
Additionally, right-clicking on it doesn't right-click the beaker either. 
Alt-clicking still allows you to change the transfer amount I think, but it makes it a bit of a problem if you don't want to/can't do that.
