### ISSUE TITLE
gibtonite doesn't explode

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18468]
(WEB REPORT BY: szuflox REMOTE: 172.93.109.202:7777)
# Revision
f2692862d4fa5a2689e90fae5dcfea55059ef2fd

# Description
Mined gibtonite doesn't explode after being hit with a pickaxe
# Steps to Reproduce
Find gibtonite
Disarm it with mining scanner
Mine it
Hit it with pickaxe
# What you Expected
Boom
# What Actually Happened
No boom

**Comment by Pathid** [comment]
@MadmanMartian
