### ISSUE TITLE
I think the cat ears brain damage thing has run its course.

### ISSUE THREAD

**Issue by amikawaii** [d3athrow/vgstation13#18462]
I think we have evolved where this novelty/meme pr is no longer required.  it was a nice joke 6 months ago, but this isn't really a good way to handle "people are doing things I don't like."   I move that we revert this change.

**Comment by ShiftyRail** [comment]
Especially since it's used a griff tool to give people braindamage.
Coding something to spit someone is a bit dumb.

**Comment by Coxswain-Navigator** [comment]
I think it should be left as it is, in my experience using it to grief is pretty much a non-issue that can be dealt with IC.

**Comment by Pathid** [comment]
>griff tool

That and I've come to strongly suspect for certain players the slow brain damage only added another fetishistic component to the mix. Cat ears were a mistake.

**Comment by DamianX** [comment]
I told you and you wouldn't listen

**Comment by Dacendeth** [comment]
at the very least collectable cat ears shouldn't have this, so people waste all their money on hat crates as god intended.

**Comment by ghost** [comment]
Adding brain damage to cat ears is a very low RP idea, which we tend to discourage, but allow. I don't think deliberately coding something just to spite people is a great addition, so with these two things considered please remove cat ear brain damage thank you

**Comment by vampirebat74** [comment]
Are you people insinuating that brain damage is a bad thing?

**Comment by Killette2** [comment]
While it is a crappy precedent, is there anything wrong with this specific change?

**Comment by ghost** [comment]
@killette2 if it's a crappy precedent in and of itself that's reason enough to say it's wrong

**Comment by nuklearcellphoneg** [comment]
It's not a precedent. Go look at ye old fedora.

**Comment by strawberrytan** [comment]
Cat ears are literally more powerful than mercury at giving brain damage

Revert cat ears or buff mercury

**Comment by Irradiation** [comment]
Clearly cat ears need to inflict Impedrezene-levels of brian damaeg.

**Comment by Orangerush** [comment]
The anti static league would like to thank our sleeper agent "amikawaii" for making this and outing out the waifus. You are not safe anywhere ![lotfi_morteza20110426050431340 1](https://user-images.githubusercontent.com/19225676/41205682-e5e082ae-6cc5-11e8-8ee4-dfb273de57aa.jpg)

**Comment by Killette2** [comment]
So what's wrong with meme hats giving brain damage? The only thing debatable is what classifies one as a meme hat

**Comment by Accipitermaris** [comment]
people using them to grief mostly

i dont want to have to compile a forensic analysis & publish it to the discovery packet every time some dude forces a fedora (or what have you) on me

**Comment by Killette2** [comment]
So the issue is someone puts a hat on you? What's stopping you from kicking their ass and explaining to the station that they did it. I don't see a difference between this and any other form of assault, it's the persons fault not the weapon, and this weapon doesn't seem over-burdening.

**Comment by Intigracy** [comment]
the real travesty was changing the collectible cat ears to change to hair color too instead of staying black
