### ISSUE TITLE
A depowered particle accelerator still "works"

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#1847]
Clicking on a depowered PA console will bring up the PA menu though it will not let you change any of the settings or run a part scan. PA that has been activated but depowered will also continue firing but the blasts do not seem to do anything to the singularity.
This coupled with #1846 has caused some trouble lately with latejoining engineers trying to setup the singularity and not realizing that equipment power is disabled.

**Comment by d3athrow** [comment]
Should be fixed.
