### ISSUE TITLE
Most things assume your gender can be determined regardless of obscured slots

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18474]
#### Description of issue
Related reading: #18466, #12558

The core of the issue is that we use BYOND macros such as `\his` and `\her` to format our strings, the behavior of which cannot be controlled outside of setting the `gender` var for the particular atom.

#### Solution 1
Set the `gender` var when someone's face/body slots are obscured. Discussed in #12558
This sucks, and is prone to errors. I'd avoid it.

#### Solution 2
We have a `/datum/gender` that we could use to help with this. Written by N3X15 two(?) years ago, never used for anything.

#### Solution 3
Port TG's thing. See here:
https://github.com/tgstation/tgstation/blob/ba1030f8038f07bfba17d4b2887c584d09b8c9fe/code/__HELPERS/pronouns.dm

They replaced all usages of \his with this.

**Comment by DamianX** [comment]
why was this closed?

**Comment by Probe1** [comment]
I closed the discussion issues that were over a year old if this is pressing then you can reopen it

**Comment by DamianX** [comment]
well, the discussion part was just picking one of the options. This is still very much a bug.

**Comment by ShiftyRail** [comment]
Alternative solution : let people chose their pronouns on the fly

**Comment by west3436** [comment]
This was addressed in #28219 and subsequent PRs.
