### ISSUE TITLE
MoMMIs cannot activate microwaves

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#18495]
#### Description of issue
Can load, but not turn on.  Despite having a hand.  

#### Difference between expected and actual behavior
I wanted to fill the kitchen with delicious food just out of the crew's reach and *comment at people who asked for it, then eventually have the kitchen broken into by hungry assistants.  Instead my hand stopped working.  

#### Steps to reproduce 
Be a MoMMI, click the fukken thing.  

#### Length of time in which bug has been known to occur
Since the borgsanity got implemented

**Comment by DamianX** [comment]
feature?

**Comment by Aurx** [comment]
HAAAAAAAND

**Comment by Allspice** [comment]
its a claw

**Comment by SonixApache** [comment]
f e a t u r e

**Comment by AutismSpider** [comment]
mommi needs slap his claw on it harder then

**Comment by jknpj** [comment]
This has been a feature since KEEPER for merged, my refactor changed nothing.

**Comment by jknpj** [comment]
This is completely against KEEPER by the way

**Comment by ShiftyRail** [comment]
MOMMI MAKE ME A SANDWICH

**Comment by Aurx** [comment]
>This is completely against KEEPER by the way

[citation needed]

**Comment by jknpj** [comment]
https://github.com/jknpj/qwilfish-on-head-retard/blob/4b87c943ced8d5ddae8ba0f2d0cde48280550c34/code/game/machinery/kitchen/microwave.dm#L198-L206

This is from 2 years ago, when only service cyborgs could interact with microwaves, because it is their quirk.

>[citation needed]

I got one:

> **You may not involve yourself in the matters of another being**, even if such matters conflict with Law Two or Law Three, unless the other being is another MoMMI in KEEPER mode.

**Comment by Exxion** [comment]
Last I checked a microwave isn't a being

**Comment by jknpj** [comment]
>I wanted to fill the kitchen with delicious food just out of the crew's reach and *comment at people who asked for it, then eventually have the kitchen broken into by hungry assistants.

**Comment by Aurx** [comment]
I understand this can be hard for c*ders, but you have to actually use your words.

**Comment by jknpj** [comment]
Making food/drinks with the intention to feed other non-keeper mommi beings is against the very first law of your lawset, come on.

**Comment by Exxion** [comment]
Who said anything about the kitchen?
Who said anything about feeding other beings?

EDIT: I mean other than the OP

**Comment by Aurx** [comment]
READ, nigga.  READ.

**Comment by Exxion** [comment]
Sorry I should have been more clear
You can use microwaves without them being in the kitchen, and without the intention of feeding other beings.
Using a microwave to feed other beings is a violation. Using the microwave *just in and of itself* is not

**Comment by Aurx** [comment]
That was directed at jknpj, my bad.

**Comment by Exxion** [comment]
Honestly it made more sense directed at me

Oh also, to be clear, I absolutely don't give a shit whether or not this is changed
It just wouldn't be a law 1 violation to use a microwave if you could

**Comment by Pathid** [comment]
Teasing carbons with delicious food with a stated intent to provoke a reaction isn't involvement, huh? I wonder what else this could be applied to.

**Comment by jknpj** [comment]
Using microwaves by itself isn't a violation of your laws(that's why i allowed soviet mommis to do it) but unless he was just being ironic in his report he was hoping the assistants to break in and get the food, right?

**Comment by Exxion** [comment]
Oh yeah doing what he said in the body of the report would absolutely be breaking law 1
I thought you meant using them at all would be

**Comment by Aurx** [comment]
Sarcasm is apparently dead.  Where the fuck is a geneticist when you need one?
