### ISSUE TITLE
Noir Vision (genetic defect) Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18491]
(WEB REPORT BY: deussex REMOTE: 172.93.109.202:7777)
# Revision
7da454228522c37dda9edbd8b65e48e0686562cb

# Description
I died, got cloned, got the black-and-white Noir vision as a genetic defect; complete with the sax music. But when I was put in cyro, my vision didn't revert to normal. I tried a ryetalin and that didn't work. When I got injected with a clean SE injection form genetics, that didn't work either. Now I'm stuck with black and white vision.
# Steps to Reproduce
1.)Die
2.) Get Cloned
   2A.) Hope you get the Noir vision upon being cloned
3.) Attempt to be cured via clean SE injection or Ryetalin
# What you Expected
My vision goes back to normal my means of genetic defect-curing. 
# What Actually Happened
I'm stuck with black and white vision, despite those attempts.

**Comment by Dacendeth** [comment]
I've also experienced this once.
