### ISSUE TITLE
Rune word things

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18500]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
830beff3451ab9343af5b3731ac6e585cd440e68

# Description
look it's an ock ick
# Steps to Reproduce
touch an astral journey rune from beside the rune instead of on top of it
# What you Expected
Harvester (40) chants, "Rash'tla sektath mal`zua. Zasan therium vivira. Itonis al'ra matum!"

The markings pulse with a small burst of light, then fall dark.

You remembered the words correctly, but the rune isn't reacting. Maybe you should position yourself differently.
# What Actually Happened
Harvester (40) chants, "Rash'tla sektath mal`zua. Zasan therium vivira. Itonis al'ra matum!"

\<span class='warning'>The markings pulse with a small burst of light, then fall dark.

You remembered the words correctly, but the rune isn't reacting. Maybe you should position yourself differently.

**Comment by Pathid** [comment]
[Not a bug]

**Comment by Riekland** [comment]
oh come the fuck on

right okay it gave me a bracketed message along the lines of (cannot something something distance) before the "the markings pulse" shit which doesn't want to appear on git. I also didn't save logs because I couldn't be fucked

**Comment by Exxion** [comment]
Fixed it for you

**Comment by Pathid** [comment]
My bad. Reading comprehension fail here.

**Comment by Exxion** [comment]
No, that wasn't there when you wrote your comment
I escaped the HTML tag when I wrote that last one

**Comment by Pathid** [comment]
Neat.
