### ISSUE TITLE
Animated NanoMed Plus Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18502]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
The animation for the NanoMed Plus is taken from one of the severs that has blue medbay instead of green, so the green cross on the machine turns blue for the duration of the animation and then straight back to green

**Comment by ShiftyRail** [comment]
It also increases MASSIVELY my MTTVC (Mean Time To Valid Collection)

**Comment by Kurfursten** [comment]
How long has this been happening? I haven't seen this and I know I've used that vendor a lot.

**Comment by ShiftyRail** [comment]
@Kurfursten Merged 3 days ago : #18476

**Comment by SonixApache** [comment]
And on that note Deff's medbay is black and red.

**Comment by DamianX** [comment]
if we made the the base icon blue I'd have to edit way less frames

**Comment by Riekland** [comment]
don't you dare bitch none of the other medical sprites are blue
