### ISSUE TITLE
CE blueprints UI doesn't open

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18517]
#### Steps to reproduce 
- Obtain CE blueprints or construction permit
- Use in-hand

#### Expected behavior
A window should pop up to let me define/rename rooms.

#### Actual behavior
Absolutely nothing happens.

#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by soyconsumer** [comment]
Neither do construction permits, it seems
