### ISSUE TITLE
Create-Antagonist button is missing Vampires

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18529]
(WEB REPORT BY: mustardtiger REMOTE: 172.93.109.202:7777)
# Revision
375b2a60ea7df4be9148dea463a370d9cd3b0bf9

# Description
Create-Antagonist button aka lazy mins feel good button is missing the option to create vampire antags. Please add it so I can extend the vampstended.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Irradiation** [comment]
Fuck that noise, how about we remove vampires instead?

**Comment by SonixApache** [comment]
>2 vampires doing nothing

>hit vampire button

>10 vampires doing nothing

**Comment by Killette2** [comment]
https://github.com/vgstation-coders/vgstation13/issues/18531

Or if you're less lazy spawn 1 use masks. Whether they use it or sell it is up to them, but it will result in FUN.
