### ISSUE TITLE
AI can open gas canisters

### ISSUE THREAD

**Issue by GelatinousGlob** [d3athrow/vgstation13#18525]

**Comment by Intigracy** [comment]
https://github.com/vgstation-coders/vgstation13/blob/793555b2fd0e1d3f4d1fee34e53c3c37b0a3f662/code/game/machinery/atmoalter/canister.dm#L292

This is obviously intentional but it can be changed if deemed necessary.

**Comment by Killette2** [comment]
You could meme and just claim they're all digital, but I feel like this could be something that gets removed.

**Comment by SonixApache** [comment]
their valves are tuned to the soft, soothing sounds of security cameras moving in specific patterns

**Comment by strawberrytan** [comment]
If there are no electronics in these canisters then how do you explain the pressure indicator light that glows green, yellow, or blinks red

**Comment by Killette2** [comment]
@strawberrytan it's a pressure functioning meter. The metal bar will go behind a colored plastic depending on the amount of pressure.

**Comment by pedr69** [comment]
then how come their pressure regulators get fucky when EMP-d?
obviously there's electronics in there
