### ISSUE TITLE
Vamp rounds need a little more UMPH

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#18531]
I was playing a vamp round, and again it was a lowpop round with only one vampire. Vampires are already known most for vampstended, and having only one antagonist really builds onto that. A simple solution that might be worth discussing is to raise the minimum amount of vampires to 2 or 3, or make a mode like changelings get and we get traitor+vamp. If datums are the issue, then raising minimum vamps wouldn't be too big of work around in the mean time. No round should rely on a sole person unless they can have major impact such as malf, blob, or wizard. Especially if it's a stealthy role.

**Comment by SonixApache** [comment]
In ye olde lore, doesn't a vampire bite cause vampirism?

**Comment by Killette2** [comment]
Already tried

https://github.com/vgstation-coders/vgstation13/issues/16608
