### ISSUE TITLE
MoMMI toggle station holomap verb broke

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18551]
(WEB REPORT BY: lunstra REMOTE: 172.93.109.202:7777)
# Revision
8e8f51d1739b066f9fc99540624c83aad0b4bcf5

# Description
Esactly what it says on the tin, this thing was working a few weeks ago since I was using it to raid the clown roid and now it isn't. Might be the case for all silicons but I only checked it as a crab
Possibly related to https://github.com/vgstation-coders/vgstation13/pull/18415 
# Steps to Reproduce
Click toggle station holomap as a crab
# What you Expected
The station holomap to come up
# What Actually Happened
It didn't

**Comment by jknpj** [comment]
something very fucky with component code, i'll look into it.

**Comment by Pathid** [comment]
@jknpj 
![mommis](https://user-images.githubusercontent.com/31839805/41620837-bb6b56f6-73bf-11e8-9b25-05b1f194cfc2.PNG)

**Comment by jknpj** [comment]
WORKS FOR CYBORGS
