### ISSUE TITLE
Remove random roundstart asthma disability

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#18566]
Basically a trader started with the disability and choked to death, it was horrible.

I think this is an oversight because having a lethal disability in random roundstart disability pool is pretty dumb.

**Comment by jknpj** [comment]
don't you get a dang inhaler with your nerd gene

**Comment by AutismSpider** [comment]
that if the rng picks it

**Comment by Pathid** [comment]
But you do.

**Comment by MusgardTiger** [comment]
where does it spawn, in your hand or your bag? either way if it does indeed spawn the guy would've seen it and not choke to death.

**Comment by DamianX** [comment]
No, it only spawns if you selected the asthma disability in your preferences. I, too, believe this is an oversight.

**Comment by Pathid** [comment]
Really? Could have sworn I got a random inhaler one time. The RNG is rolled right after the player-chosen disabilities are handled and they're both clearly before ``EquipRank()`` is called. Not that I really care if you remove from roundstart random mutations, but it's odd.

**Comment by DamianX** [comment]
You seem to be correct, you should be given an inhaler.
https://github.com/vgstation-coders/vgstation13/blob/d628c191bf8c2c37452c234cac4447bd2572bfb8/code/game/jobs/job_controller.dm#L495-L499
Still.
