### ISSUE TITLE
you can singe people with unlit cigarettes

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#18572]
#### Description of issue
You can singe people with unlit cigarettes. No idea if it does damage.

#### Difference between expected and actual behavior
click diona repeatedly with unlit cigarette -> nothing happens
vs
click diona repeatedly with unlit cigarette -> diona kicks your ass for attempted murder
#### Steps to reproduce 
Click someone with an unlit cigarette.

#### Server revision
b4bc4ed40e2461a576e45a8cbe69f82d878d5e1c

**Comment by veles2001** [comment]
Just confirmed this on [`3fad58f`](https://github.com/vgstation-coders/vgstation13/commit/3fad58ff2cc80d8390cccea326e0ef26dfb6e837). It seems to occur with every item that is defined in code/game/objects/items/weapons/cigs_lighters.dm. From my testing, it doesn't do any damage.
