### ISSUE TITLE
Thrown bottles do not splash their reagents

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18579]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
e47cbf0bef8d059312f4d9b665321b94573a30ba

# Description

Throwing a bottle (say, space beer filled with water, or welder fuel) at a person, or the floor for that matter, does not splash the contained reagents on the floor.

# Steps to Reproduce

Be HoS, get splashed with water, run, except to slip and get robusted.
Also reproduced via testing, with and without a mask, at a person or at the floor.

# What you Expected

I expected the reagent to be splashed on the ground, and to slip, and get laughed at.

# What Actually Happened

Nothing of the sort.

**Comment by ShiftyRail** [comment]
May or may not be Lummox-locked due to #18481.

**Comment by Irradiation** [comment]
For some reason, which I assume to be due to Exxion/Lummox, you can't inject reagents into people by throwing drinking glass filled with chems anymore. RIP throwing 50u of Crypto at the Clown.

**Comment by Exxion** [comment]
Bottles without rags in them should still work, so if this is true it's a separate bug from the one #18481 will fix in 512.1428

**Comment by Exxion** [comment]
I can't reproduce either bug mentioned here, UNLESS the bottle has a rag stuffed in it or contains welder fuel
In which case it *is* the bug that will be fixed by updating the server to 512.1428, when it comes out

EDIT: Actually I can't reproduce it when the bottle hits a mob or the floor even in the above case. Only a dense `/obj` or a wall.

**Comment by ShiftyRail** [comment]
What was your test case, Exxion ? Here's what I did to reproduce it

>spawn in two normal humans (not test dummies)
>assume control of one of them
>pick space beer, empty, fill with water
>throw it at person/the ground
>run through it, expect to slip
>didn't slip

**Comment by Exxion** [comment]
Doesn't happen locally following that exact procedure

![image](https://user-images.githubusercontent.com/9827785/41793237-767249da-7629-11e8-968c-1c058b1897e6.png)

**Comment by Exxion** [comment]
It was found that he was reproducing it on unsimulated turfs, which is not apparently a bug
@Irradiation I'd still like to hear about glasses not splashing people
