### ISSUE TITLE
Analyser or Analyzer?

### ISSUE THREAD

**Issue by praisenarsie** [d3athrow/vgstation13#18573]
https://github.com/vgstation-coders/vgstation13/blob/58def87fedc25b491eb63abd0a369a82b2c90558/code/modules/research/xenoarchaeology/machinery/artifact_analyser_old.dm#L5
https://github.com/vgstation-coders/vgstation13/blob/58def87fedc25b491eb63abd0a369a82b2c90558/code/unused/disease2/analyser.dm#L2
https://github.com/vgstation-coders/vgstation13/blob/ca58878c3a09aafa533daffdc92ae261fee1178e/code/modules/research/xenoarchaeology/machinery/artifact_analyser.dm#L3
https://github.com/vgstation-coders/vgstation13/blob/3514cc9360a07e8d144663318c3fe1976e867559/code/modules/research/designs/engineering.dm#L74
https://github.com/vgstation-coders/vgstation13/blob/246b9261f5df95639af1ec5c029a8e2fd9ed8136/code/modules/research/destructive_analyzer.dm#L11
https://github.com/vgstation-coders/vgstation13/blob/c9da8e464ccb7b1aa6d124c6858b9e071f13103f/code/modules/hydroponics/hydro_tools.dm#L16
https://github.com/vgstation-coders/vgstation13/blob/b313207001c2566e6848e2ae34539cb12ee59c79/code/modules/research/designs/stock_parts.dm#L200

vote on your voting analyzsers now

also these aren't all the cases

**Comment by ghost** [comment]
Analyser. Case closed.

**Comment by DamianX** [comment]
Analysis device.

**Comment by Killette2** [comment]
Who cares, they're both anal to me

**Comment by Ratvar** [comment]
Anal Isis
