### ISSUE TITLE
Exofab Problems

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#1857]
Alright I tried using exofabs yesterday and I experienced the bugs people have been talking about, I haven't tried replicating them specifically but I'll include all the details of what happened.

1. I did about half the research so I could produce a higher level power cell
2. I synced the robotics console and then both the exofabs. At this point I had no problems, and the super cell I was trying to build was successfully created.
3. I wanted a hypercell next so I upped the research to the levels required and synced up the new tech over to robotics.

Now here is where my problems started
4. Upon resyncing the exofabs, all the tech that had been synced up the last time was deleted and all the NEW tech was added. (i.e. super cell removed, hyper cell added). None of the original tech on the exofabs was deleted.
5. This also introduced the bug where you cannot build anything from the exofab.
6. I could sync the exofabs as many times as I wanted. Each time it would add all the tech missing and delete all the tech it has.

**Comment by clusterfack** [comment]
https://github.com/tgstation/-tg-station/commit/d56698f99101a2973dda06b374dc55c9c79faab1
https://github.com/tgstation/-tg-station/commit/ba44b325d3fc4eca64cb48e5b733e5bdc21b2722

**Comment by ComicIronic** [comment]
We are already on the design-based system for exosuit fabricators.
TG actually switched after we did.

**Comment by ririchiyo** [comment]
This should actually be fixed now, I hope.
