### ISSUE TITLE
Hundreds of options on right click

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18595]
(WEB REPORT BY: capitalistpickle REMOTE: 172.93.109.202:7777)
When I right click an option I get 100s of options, but they block the screen so I can't pick anything up, I closed byond and reopened it and I still have the problem

**Comment by strawberrytan** [comment]
You need to give more info and screenshots if possible

**Comment by Exxion** [comment]
It's a BYOND bug with 512.1428, which Lummox somehow missed before releasing it. Update to 512.1429.
