### ISSUE TITLE
Storing items in containers located at the same tile as a portal sends them through the portal.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#18613]
#### Description of issue
As described in the title: this includes worn containers such as toolboxes on hands, labcoats, belts and backpacks. Doesn't seem to happen to player slots like suit storage and belts. It also happens if the container is on the floor, under the portal. A "phantom" icon of the item shows up in the HUD but it cannot be interacted with.
Issue  #14308 is similar but it is not exactly the same as this, #17277 may also be related to this.

#### Difference between expected and actual behavior
For items to enter the container, not sneakily go through the portal.

#### Steps to reproduce 
Grab a hand teleporter
Use it
Try storing anything in your backpack, toolbox or the like

#### Server revision

750d038780d56e316f7f9d5427bebdcddaf92178

#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Man, I thought we fixed this

**Comment by jknpj** [comment]
because somefuckinghow items are dropped for a short while when they're stored

**Comment by Killette2** [comment]
https://github.com/vgstation-coders/vgstation13/issues/16373
