### ISSUE TITLE
There is no attack message when you hit a grille with whatever

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#18656]
There is no attack message when you hit a grille with literally anything. I think it is this way because we didn't have spam filter thing in the past but I think we should add attack messages to hitting grilles now. Mainly because if it is your first time doing it with a strong hitting item, you probably break the grille before you go "huh there is no message is this thing breakable?" but when you try it for the first time and what you have is a low damage item you either think that it doesn't break or there is a bug.

**Comment by Killette2** [comment]
There's no attack message when you toolbox a door either

**Comment by ghost** [comment]
Toolboxing a door does nothing, though, toolboxing a grille does
