### ISSUE TITLE
Meta Club - central atmospherics computer does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18652]
(WEB REPORT BY: curver REMOTE: 172.93.109.202:7777)
The central atmospherics computer displays the map, and little details, but you can't go into the detail list. It just keeps loading. Tested 511 and 512, and the issue remains.

**Comment by MasterofNothing** [comment]
With "and little details" I mean the icons for the air alarm status.

**Comment by MasterofNothing** [comment]
This still does not work. Tested 510, 511 and 512 (latest). It means that any atmospherics project is impossible on Meta.

You cannot go into the detail list / control individual air alarms at all remotely.

**Comment by Inorien** [comment]
#17707

**Comment by Exxion** [comment]
Duplicate of the above
Also, god damn
