### ISSUE TITLE
You can't emag windoors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18667]
(WEB REPORT BY: soyconsumer REMOTE: 172.93.109.202:7777)
# Revision
3fad58ff2cc80d8390cccea326e0ef26dfb6e837

# Description
You can emag secure ones but not normal ones
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by MadmanMartian** [comment]
I can't even emag secure ones.

**Comment by Irradiation** [comment]
I believe I've managed to emag secured windoors multiple times.
