### ISSUE TITLE
Mech bay and blast doors can be opened or closed by clicking them with empty hand.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#18668]
#### Description of issue
These secure doors that usually require a button to move up and down seem to be able to be operated by hand with no access.

#### Length of time in which bug has been known to occur

Pretty new I think.

#### Server revision

Revision: 3fad58ff2cc80d8390cccea326e0ef26dfb6e837 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
Exactly the same with Bridge doors and Brig door. Tested as HoS, with HoS access and with Captain access.
