### ISSUE TITLE
Blast Doors Can Be Opened by Hand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18671]
(WEB REPORT BY: dtscurvy REMOTE: 172.93.109.202:7777)
# Revision
3fad58ff2cc80d8390cccea326e0ef26dfb6e837

# Description
Clicking on blast doors opens and closes them.
# Steps to Reproduce
Click on a blast door.
# What you Expected
For a blast door not to open
# What Actually Happened
It opened

**Comment by DamianX** [comment]
#18668
