### ISSUE TITLE
Pathogenic Incubator Dish Release

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18687]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
Whenever you eject the virus dish from the incubator, it puts it below the incubator on the tile, meaning you need to right or alt click to get it

It's sloooow

**Comment by Killette2** [comment]
This is why I use 5.10

**Comment by Exxion** [comment]
This is the same issue as #18372
