### ISSUE TITLE
Carbons can change gas pump pressures without being next to it.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#18691]
#### Description of issue
Gas pumps can have their kpa changed while you're not next to the pump if you open the window to set the numbers, I didnt test it with any other atmos things but it might work with them too.

#### Difference between expected and actual behavior
To get an error messege about being too far away and it doesnt change it
It worked.

#### Steps to reproduce 
click on the gas pump
click the change pressure button
keep that new window open and walk away from it
change the pressure and walk back and confirm it actually got changed.

#### Server revision

Revision: fc2b142a9550cc220473093c575db4f5a9d37be3 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by veles2001** [comment]
I just confirmed this on [`fc2b142`](https://github.com/vgstation-coders/vgstation13/commit/fc2b142a9550cc220473093c575db4f5a9d37be3). This seems to affect every object that opens the little message box with the text field for entering numbers.

**Comment by ddolll** [comment]
I can confirm that this has existed since before the repo, maybe always

**Comment by Dacendeth** [comment]
something fixed this.
