### ISSUE TITLE
Exosuit mounted switchtool can lose a tool by putting them on a table or in a locker.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#18704]
#### Description of issue
Title.

#### Server revision

Revision: 91b9287409686352a808a6d038face427aa366cb 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
Could be related to #17584

**Comment by Dacendeth** [comment]
Doesnt happen anymore
