### ISSUE TITLE
Small things that need sprites

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#18716]
- ~~Chemdispenser when beaker is inserted~~#18766
- [ ] Bluespace beaker when lid is added
- [ ] Soda can after opened
- [ ] Laser scalpel when toggling modes

**Comment by SonixApache** [comment]
Laser scalpels *should* be animated on both modes

**Comment by ghost** [comment]
There's no visual distinction on which mode it's set to is what I meant

**Comment by RealestEstate** [comment]
if that PR passes it should check off the latter 3 leaving you with just the chem dispenser w/beaker
