### ISSUE TITLE
first name only

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18717]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
game forces a surname on you if you're human which should be considered a bug after the last name rules change

**Comment by Exxion** [comment]
It's a config option, not a bug

**Comment by DamianX** [comment]
config was a mistake

**Comment by SonixApache** [comment]
name rules were a mistake

**Comment by Exxion** [comment]
Make a poll or vote or something
It's in one of the files that the collabs have access to
