### ISSUE TITLE
Safe's can spawn unopenable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18719]
(WEB REPORT BY: tokanova REMOTE: 172.93.109.202:7777)
# Revision
e73421e2414a1f6a925861ec7e7ab62c47e76f63

# Description
When attempting to open safes, the numbers to open it and sweet spots can overlap, meaning they can be unopenable.
# Steps to Reproduce
Bit random
Find number where it tinks, krinks, or plinks
Go in opposite direction and look for tonk's, krunks, and plunks
Get bamboozled as first tumbler untumbles.

# What you Expected
To be able to open safes consistently!.
# What Actually Happened
I wasn't able to open it, even after doing everything right

**Comment by RealestEstate** [comment]
I've noticed this myself

**Comment by DamianX** [comment]
I've had this happen but managed to eventually open it. So it's annoying but I don't think it makes the safe unopenable.
