### ISSUE TITLE
Lattices don't automatically smooth with placed catwalks.

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#18744]
#### Description of issue
Constantly, when catwalks are placed directly north of a lattice in Dream Maker, the lattice won't smooth with the catwalk at runtime.

Additionally, lattices don't smooth with nearby catwalks if said catwalks were placed after them.

Please check the screenshots bellow

#### Difference between expected and actual behavior
Lattices should always connect to catwalks, no matter in which order they were placed down, or their position according to each other.

#### Steps to reproduce 
1. Open Dream Maker
2. Locate a place on the station where there's a catwalk directly North of a lattice. (or add one for testing)
3. Compile and Start a local server
4. Observe that the lattice isn't properly connected to the catwalk

5. Spawn a lattice in space
6. Space a catwalk next to it
7. Observe that the lattice isn't connected to the catwalk

#### Specific information for locating
![image](https://user-images.githubusercontent.com/7573912/42365495-eeaf04e4-80fe-11e8-95d8-8526beba9412.png)
Those can be found west of the Centcomm Deathsquad center.

![image](https://user-images.githubusercontent.com/7573912/42365749-a34f9724-80ff-11e8-9ca6-bcb404a187d7.png)
Above: the lattice was placed first (at runtime)
Bellow: the catwalk was placed first (at runtime)

#### Server revision

Game: 311b6cbff8869e03d6afd6ae7aa8efb9170a2b60 
Patches: 998316155b9c9210ca3d87fb7313d9cf2b30f871 

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Very strange that the first one only applies in one direction.

**Comment by DeityLink** [comment]
I think it has something to do with smoothing occuring on New() and all of the world's New() being called row after row from bottom to top. Adding a small delay in the smoothing should fix the first issue.

**Comment by DamianX** [comment]
\>a small delay
use initialize

**Comment by Exxion** [comment]
I would expect it to fail from one horizontal direction as well in that case, but this is BYOND so expectations are barely more accurate than a coin flip
