### ISSUE TITLE
Can't pick up gibtonite ore

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18757]
#### Description of issue

"You can't pick that up!"

#### Specific information for locating

Guessing it's
https://github.com/vgstation-coders/vgstation13/pull/18600/files#diff-ac3b89e91ad083b3cb3fdb669006158cR234

@MadmanMartian 

#### Length of time in which bug has been known to occur

In the past couple weeks.

#### Server revision

Game: b397411cf9c29ab651c01751021b975fc645317e 
Patches: 998316155b9c9210ca3d87fb7313d9cf2b30f871 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by RealestEstate** [comment]
were both hands empty? gibtonite ore requires 2 hands.

**Comment by RealestEstate** [comment]
nvm I tested it with 2 hands and it is indeed borken

**Comment by Kurfursten** [comment]
For reasons extremely confusing to me, gibtonite has anchored = 1, which should prevent it from being picked up at all unless it has some kind of snowflake exception? And yet there's a comment in the code that implies the opposite.

	anchored = 1 //Forces people to carry it by hand, no pulling!

**Comment by Exxion** [comment]
@Kurfursten You sure? As far as I know there's nothing intended to keep people from picking up anchored items. It just means they can't be pushed/pulled around.

**Comment by Exxion** [comment]
Oh, I guess that only used to be the case

**Comment by Kurfursten** [comment]
It sounds like you found what I'm talking about, which is this:

https://github.com/MadmanMartian/vgstation13/blob/ed24bb0975cc8c8f59a2e464ecf28e6687664e88/code/game/objects/items.dm#L804-L813
```

/obj/item/can_pickup(mob/living/user)
	if(!(user) || !isliving(user)) //BS12 EDIT
		return FALSE
	if(user.incapacitated() || !Adjacent(user))
		return FALSE
	if((!istype(user, /mob/living/carbon) && !isMoMMI(user)) || istype(user, /mob/living/carbon/brain)) //Is not a carbon being, MoMMI, or is a brain
		to_chat(user, "You can't pick things up!")
	if(anchored) //Object isn't anchored
		to_chat(user, "<span class='warning'>You can't pick that up!</span>")
		return FALSE
```
