### ISSUE TITLE
packed xenobotany underequipped

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18750]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
department starts without a hatchet(important) which I believe to be an oversight while mapping

**Comment by Killette2** [comment]
Is this for hydro or science?

**Comment by Riekland** [comment]
xenobotany has nothing to do with hydroponics

**Comment by Killette2** [comment]
That is incorrect
