### ISSUE TITLE
Magmaw Adminwarns Are A Bit Distracting

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#18760]
I don't know if there's an easy fix for this.

Magmaws are really cool and while fairly rare add a bit of excitement to the roid. However they also spam admins with attack warnings a fair bit because they send a message when shoot off a fire spout, which is repeatedly every time they eat some plasma. They love shooting at just about everything including other roid monsters.

Is there a way we can only send an admin warning if they hit or target a player?

**Comment by Exxion** [comment]
If the code I'm looking at is the correct code, then this should be easy. Give them their own subtype of the `fire_breath` projectile that changes nothing from the parent except overrides `admin_warn()` to only call the parent if the hit mob has a mind or something
