### ISSUE TITLE
Chemdispenser lacks sprite for when beaker is inserted [request]

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#18766]
Would be nice so you can tell at a glance if it's loaded

**Comment by RealestEstate** [comment]
so the reason I hesitated with the chem dispenser is because if you look closely at the sprite, it has multiple dispensing tubes on a tray, kind of like a soda fountain at a fast food place. it would look kinda silly to just plop a beaker smack dab in the center of it imo.

**Comment by DamianX** [comment]
The obvious solution is to have more beaker slots

**Comment by ghost** [comment]
Thanks for looking into it.
In my head I pictured just a small 5 pixel tall miniature of a beaker resting under the tubes. It doesn't really even need to change depending on the type of beaker inserted, just something to show you "oh, that's where the beaker is"

**Comment by RealestEstate** [comment]
I made you the overlay, but you might want to wait for #18759 to get merged first to prevent conflicts.
https://cdn.discordapp.com/attachments/463854296430018572/466777516049301504/beakeroverlay.dmi
@Unknown-as-Captain
