### ISSUE TITLE
Security Newscaster on Box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18775]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
Any reason it's hidden in HoS office? It's available to all officers on deff and it seems fine. Or at least make it available to the warden.

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/42488528-f7d3575a-83d3-11e8-8712-886ae5a2aa10.png)
there's this one, accessible from where i'm standing.

**Comment by Blithering** [comment]
What access is required to post a wanted issue? I noticed in a recent round I was unable to do so as warden using that newscaster

**Comment by SonixApache** [comment]
You need to use a security newscaster, which are only in certain areas.

**Comment by Dacendeth** [comment]
Oh that ones not a security newscaster? really should be.
