### ISSUE TITLE
Tomb of Rafid atmos simulation issues

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18773]
This part of the tomb has these unsimmed(?) water turfs next to simulated turfs that seem to always get vented, creating unending absurd space wind. Or at least that's what seems to be doing it.

![procreatory fortress uniform 2018-07-08 193520 1](https://user-images.githubusercontent.com/31839805/42430304-3ae93956-82f3-11e8-977d-2ae9b66afa9c.png)
![procreatory fortress uniform 2018-07-08 193526](https://user-images.githubusercontent.com/31839805/42430317-5054fb72-82f3-11e8-8e99-c58647be00f7.png)
![procreatory fortress uniform 2018-07-08 193528 1](https://user-images.githubusercontent.com/31839805/42430307-3e9f211e-82f3-11e8-868d-eb66c97eef00.png)

**Comment by Caboozles** [comment]
I'd rather not see this changed, actually. It's hilarious, and given how rare even getting this away mission is, it's probably the most memorable and entertaining aspect of it.

**Comment by Exxion** [comment]
Presumably fixed by #19346
