### ISSUE TITLE
Item in bag becomes unresponsive, also stuck on the screen when bag is closed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18776]
(WEB REPORT BY: xuesong REMOTE: 172.93.109.202:7777)
# Revision
ad4262a57992534eb17b4586d264fa9628165b41

# Description
pretty much what I said in the issue title. 

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
Ancient issue
Still not exactly sure of the cause

**Comment by Blithering** [comment]
Wasn't it determined to be something related to the fact putting an item in bags momentarily puts in on the floor first?

**Comment by Exxion** [comment]
I kind of doubt it, but I guess it's possible
