### ISSUE TITLE
spider machine broke

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#18788]
#### Description of issue
spiderlings didn't grow up. an rng event spawned 4~ in the vault and they didn't grow up
admin online said that the amount_grown variable didn't move past 0 and that he had to edit it himself

#### Difference between expected and actual behavior
just dont want to grow up

#### Steps to reproduce 
spawn spiderlings, wait

#### Specific information for locating
located in the spiderlings

**Comment by ShiftyRail** [comment]
https://github.com/vgstation-coders/vgstation13/blob/91f122395ef8dcfb8e8a08a9eb6323781e0e55f9/code/modules/mob/living/simple_animal/hostile/giant_spider/spiderling.dm#L121-L127

Amazing, it checks if `amount_grown > 0` instead of `>= 0`.

**Comment by Kurfursten** [comment]
That's actually intended behavior. Under /New() spiderling has a 75% chance to set amount_grown to 1.

**Comment by DamianX** [comment]
Feature, I guess. Does anyone think this should be changed?
