### ISSUE TITLE
Mobs in cages are indestructible?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18790]
(WEB REPORT BY: shadownil REMOTE: 172.93.109.202:7777)
# Description
Giant spider in a cage on cult base in space. Try to kill it with lasergun so I can explore safely, but it constantly attacks me the moment I get within one tile, and none of my attacks work on it. Cannot try opening the cage without serious damage.

# Steps to Reproduce
Get any hostile mob, put in a cage, attack it with a lasergun.

# What you Expected
To kill the fucking thing so I can spess spelunk more.

# What Actually Happened
Nope, you can't kill the spider in the cage, it's just the perfect door guardian in a cage with clear spaces between bars.

**Comment by SonixApache** [comment]
dude just close the cover lmao

**Comment by RealestEstate** [comment]
yes while testing this I can confirm that anything inside a cage, covered or not, is immune to lasers.
obrez shots pierce the cage but do not damage what is inside. the rocket launcher was the only thing that I was able to use to damage the thing inside ultimately killing.

**Comment by Exxion** [comment]
Even piercing shots don't work? That's very strange.

**Comment by RealestEstate** [comment]
could it be that the shot registers the cage as a structure and doesn't bother to check what's inside?

**Comment by Exxion** [comment]
Not if the cover is open, since the mob isn't inside it in that case

**Comment by DeityLink** [comment]
Won't the mob just wander if the cover is open?

**Comment by Exxion** [comment]
Not if the cage is closed.

**Comment by DeityLink** [comment]
@Exxion so if I get it right, it can still attack adjacent tiles if the cover is open the but the cage is closed? Is that intended? (Is it good design?)

**Comment by Exxion** [comment]
Yes, it's intended. If you don't want it to be able to interact with the outside world, close the cover.

**Comment by DeityLink** [comment]
So the only issue is projectiles not reaching them inside cages because it bumps into the cage first? Can there be several mobs inside a cage or just one?

**Comment by Exxion** [comment]
Just one as far as I know. But the cage isn't dense as far as I know, so I don't think it's normal projectile code that blocks it. Perhaps there's some code for the purposes of vehicles or something that causes bullets hitting a mob locked to something to hit the thing they're locked to instead. If that's the case, I'd probably just only make it do that if the thing is dense or something.

**Comment by DeityLink** [comment]
After testing I confirm that the cage IS dense when close, which allows bumping into it to push it out of the way when there is a mob inside. So yeah looks like the best is to have it return the occupant's bullet_act on impact.

**Comment by Exxion** [comment]
Ah, makes sense.
Fun detail: BYOND does not allow mobs to ever appear earlier in `contents` than any object, ever, so if a dense mob and dense object are on the same tile, bullets will always hit the object unless it's specifically coded to pass it on to the mob. Neat.
