### ISSUE TITLE
Magnificent mag boots going invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18793]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
cf65224c00e9010ff5990fc7aed2bb64dbe0c7f9

# Description
Mag-magboots going invisile when worn

# Steps to Reproduce
Spawn shoes, put them on

# What you Expected
Be able to see them

# What Actually Happened
Icon's gone, shoes still there

**Comment by Kurfursten** [comment]
Probably missing Vox sprite
