### ISSUE TITLE
Unmounted firelock

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18792]
(WEB REPORT BY: martyrofspandau REMOTE: 172.93.109.202:7777)
# Revision
cf65224c00e9010ff5990fc7aed2bb64dbe0c7f9

# Description

there is a single firelock on the "bridge" between vox outpost trader vox/human part - that is dismantled and not mounted from the start of each round. I suspect that that is a bug.

It is the 3rd firelock from the left (visible after right doors open)

# Steps to Reproduce
spawned at start of each round

# What you Expected
that the firelock will be placed properly

# What Actually Happened
quite the oposite

**Comment by jknpj** [comment]
Why the fuck can't people report the map in a mapping issue

**Comment by Dacendeth** [comment]
I think he's talkin about box.
![image](https://user-images.githubusercontent.com/26881007/42585386-79a25210-8503-11e8-9dbc-46552bca7596.png)
it felt thematic to me that it wasn't finish and just laying on the ground.

**Comment by ghost** [comment]
@jknpj Actually why the fuck can't the issue reporter automatically embed the map
