### ISSUE TITLE
Hailer on dismembered heads is buggy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18799]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
cf65224c00e9010ff5990fc7aed2bb64dbe0c7f9

# Description
using the hailer (I used the PDA integrated one) on a dismembered head instead told the adjacent people to halt instead of the head.
# Steps to Reproduce
decapitate a criminal.
hail his head
everyone around within 1 tile(even multiple people in a single message) are hailed to stop.
# What you Expected
the head to be hailed
# What Actually Happened
everyone adjacent was hailed

**Comment by Kurfursten** [comment]
This is working as designed, if you do not target a mob it instead hails everyone in a 3x3 square of where you clicked (helps if you miss exact clicking someone who is running)
