### ISSUE TITLE
Show held item can be spammed easily

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18804]
(WEB REPORT BY: goldsteel REMOTE: 172.93.109.202:7777)
# Revision
d4da169f6a635496ab2d023e9d258ff91d7b08e4

# Description
Repeat of the shuffling cards chat spam incident. You can run over glass or something else to break up the chat while rapidly clicking an item and showing red arrows everywhere.

# Steps to Reproduce
Shift and middle mouse an item while running around on glass shards

# What you Expected
Some sort of short delay

# What Actually Happened
Spam spam spam spam spam spam spam

**Comment by DamianX** [comment]
sounds like an ic issue xD
