### ISSUE TITLE
science weed control crates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18811]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
science cant open weed control crates while they can open exotic seed crates (consistency issue)

**Comment by DamianX** [comment]
allegedly not a bug #18200

**Comment by RealestEstate** [comment]
PSST HEY KID, THE OUTPOST HAS AN EMITTER THAT CAN OPEN ANY CRATE. YOU DIDN'T HEAR THIS FROM ME, OK?
