### ISSUE TITLE
Cloned flammkuchen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18818]
(WEB REPORT BY: mitchykins REMOTE: 172.93.109.202:7777)
# Revision
887d81a686cc567434b3a1cc6037e5e1be765b7f

# Description
Basically thanks to a plate, spit and campfire, I can copy food, I only saw this with Flamkuchen but I'm not sure if it happens with other foods as well
# Steps to Reproduce
Put flammkuchen on plate, put on spit over campfire, wait a while and another flammkuchen will appear under the flammkuchen on a plate
# What you Expected
Not to have another flammkuchen appear
# What Actually Happened
One randomly appeared under the food item

**Comment by Kurfursten** [comment]
Plates and roasting are both mistakes

**Comment by SonixApache** [comment]
related: #18357

**Comment by Jubisloviu** [comment]
goofcooking was a mistake

**Comment by DeityLink** [comment]
Fixed by #30190
