### ISSUE TITLE
Infinite wire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18829]
(WEB REPORT BY: lavoss REMOTE: 172.93.109.202:7777)
>get wire from engi derelict place on meta
>go to get small wire to throw
>gives entire coil
>put it back to see what happens
>accidently create self refilling infinite wire coil generator

oh god im loose call me

**Comment by DamianX** [comment]
What is the "engi derelict place on meta"? A vault?

**Comment by Exxion** [comment]
@Irradiation

**Comment by Dacendeth** [comment]
You sure it just wasnt a graphic bug? sometimes you take a coil piece and it's a single piece but it looks like a full coil.

**Comment by Irradiation** [comment]
@Exxion Yes hello, why am I pinged?

**Comment by Exxion** [comment]
@Irradiation because you were talking about this on Discord and I thought you could shed some light
