### ISSUE TITLE
night vision goggles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18824]
(WEB REPORT BY: jayz420maskoff REMOTE: 172.93.109.202:7777)
# Revision
aa6ebdcaa9f0313e4de958207d401828cf540c5d

# Description
if you die with night vision goggles on then your vision is perma tinted green even in ghost mode and still when you get revived or become a whatever

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment]
Nice.
related to #18533
