### ISSUE TITLE
Packed Station lacks a coin mint.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18828]
(WEB REPORT BY: smedley8 REMOTE: 172.93.109.202:7777)
# Revision
aa6ebdcaa9f0313e4de958207d401828cf540c5d

# Description

No coin mint on the packed station Asteroid.

# Steps to Reproduce

Dude just go to the asteroid on packed lmao.

# What you Expected

A coin mint.

# What Actually Happened

A compressed mining/research outpost that lacked a coin mint.

**Comment by SonixApache** [comment]
literally unplayable
