### ISSUE TITLE
No inhand icons for riot shield

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18823]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
aa6ebdcaa9f0313e4de958207d401828cf540c5d

# Description

There is no inhand icon for the riot shield

# Steps to Reproduce

Equip shield

# What you Expected

Intimidate greyshirts

# What Actually Happened

Even more powergaming

**Comment by Exxion** [comment]
Oh god did someone fuck up inhands again?

**Comment by RealestEstate** [comment]
they've worked before, this is something new.

**Comment by ShiftyRail** [comment]
#18782 looks to be the latest PR to touch in-hands

**Comment by Blithering** [comment]
At this point inhands fucking up could be its own tag, considering how often it happens

**Comment by Dacendeth** [comment]
noticed this with toy energy sword too.
