### ISSUE TITLE
Cultify artifact makes cult grilles that glitch out on deconstruction

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18833]
I'm not sure if this is all cult grilles or just the ones made by artifacts. What happens is if you cut apart one of these cult grilles, it makes the floor under it unable to be deconstructed. What's worse is if you construct a normal grille in the same spot it disappears and makes an invisible wall there that doesn't even show up on alt-click.

**Comment by Exxion** [comment]
Holy shit is this the source of the mysterious invisible grilles???
(There have been bug reports about grilles turning invisible but remaining dense for years)
(This is almost certainly either an issue with `qdel()` failing or with pooling)
