### ISSUE TITLE
Cyber Horrors no longer inject medical nanobots on hit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18830]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
# Revision
aa6ebdcaa9f0313e4de958207d401828cf540c5d

# Description
exactly what it says on the title, admins bussed cyber horrors and none of the crew members ended up becoming one, they just died whenever they got mauled instead.
# Steps to Reproduce
get hit by a cyber horrors
# What you Expected
cyber horror groans, "K!@@##L!@@ %!@#E"
# What Actually Happened
greytide mcshirt dabs!

**Comment by Killette2** [comment]
Got a screenshot or logs of their attack messages?

**Comment by MadmanMartian** [comment]
Tested both. You still get mednanobots, and mednanobots do convert you.

**Comment by MadmanMartian** [comment]
![atheist muppet hq one 2018-07-17 013630](https://user-images.githubusercontent.com/30557196/42790506-572d94ec-8963-11e8-8d3c-63b308e155af.png)
