### ISSUE TITLE
Mask of the Xenomorph not being put on normally

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18843]
(WEB REPORT BY: tokanova REMOTE: 172.93.109.202:7777)
# Revision
9870f9dfcf0b51a006f4d01052ca1710c81a9d3e

# Description
I was putting on a xenomorphifying mask and it kept looping 'attempting' to put the mask on. But when I dropped it, it finally got put on.
# Steps to Reproduce
Take Mask of the Xenomoprh
Try to put on
Watch as it loops itself attempting ot be put on
Drop
Be amazed as it goes on
# What you Expected
To be able to just put it on easily
# What Actually Happened
It kept looping being put on til dropped.

**Comment by Dacendeth** [comment]
it refuses to put itself on with the hotkey equip i've noticed, clicking your mask slot works fine though, still does that weird thing when you drop it on the ground.
