### ISSUE TITLE
Engineering APCs do not charge on Box Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18849]
(WEB REPORT BY: dtscurvy REMOTE: 172.93.109.202:7777)
# Revision
9870f9dfcf0b51a006f4d01052ca1710c81a9d3e

# Description
The Auxillary Engineering APC,the Supermatter Room APC, and the Antimatter Engine Room APC do not charge on Box Station, even if there's power in the wires leading up to them. The External Power indicator on the APC's UI will go on and off again from "Good" to "Low".
# Steps to Reproduce
Go on Box Station, set up the singulo or some other engine, and set up the SMES.
# What you Expected
For them to charge
# What Actually Happened
They didn't charge

**Comment by Pathid** [comment]
Yes, this is what happens if you have the SMES units set to draw all the available power. It's not a Box thng.

**Comment by Inorien** [comment]
you also need to set the internal engineering SMES in the TEG room i think, someone mentioned APCs only drawing from wires supplied by a SMES and not engines, though i may be wrong on that

**Comment by DamianX** [comment]
I'm sure this is just engineers setting SMESs to "Auto", as Pathid said. There should be better documentation on the wiki.
