### ISSUE TITLE
double agent with only one agent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18855]
(WEB REPORT BY: osaifh REMOTE: 172.93.109.202:7777)
# Revision
46aab02a2dcd1124eb3c87365a5eb75df1ffe5be

# Description
A round started with the double agents gamemode, however, there were only 7 players ready, so that caused it to only be one traitor (me), and I had 2 escape objectives, no kill objectives

# Steps to Reproduce
Start a round of double agents without enough people for there to be at least 2 traitors

# What you Expected
Either the gamemode to be changed (since there aren't enough people to have 2 traitors, double agents doesn't make any sense) or for there to be at least 2 traitors

# What Actually Happened
There was only one traitor (I received the traitor role twice, the result screen showed me twice and I had 2 uplink codes for the PDA) with 2 escape objectives

**Comment by Ratvar** [comment]
double agent
double escape
all checks out, not a bug

**Comment by Dacendeth** [comment]
Better than having a kill objective on yourself along with a protect yourself objective.

**Comment by Kitfox88** [comment]
That's TWICE the greentext to get, seems like a feature not a bug.

**Comment by ShiftyRail** [comment]
@Exxion fixed by datums.
