### ISSUE TITLE
Emotes are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18857]
(WEB REPORT BY: curver REMOTE: 172.93.109.202:7777)
/me does not do anything, nor do things like *smile.

Issue since today.

**Comment by Pathid** [comment]
#18738
@ShiftyRail

**Comment by Irradiation** [comment]
@ShiftyRail Please explain yourself on the forums. https://github.com/vgstation-coders/vgstation13/pull/18738

**Comment by Killette2** [comment]
Emotes were removed because we were tired of being compared to bay

**Comment by MasterofNothing** [comment]
That's a quick fix, nice.
