### ISSUE TITLE
MoMMI emotes are borked

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18867]
MoMMI emotes (except for Me ones) aren't working at all. Using *help gives you this:

![available](https://user-images.githubusercontent.com/31839805/42869550-3b4e6b30-8a2a-11e8-90ed-5eb011f5b65d.PNG)

Not entirely sure the borg ones are working either, haven't checked that yet.

**Comment by ShiftyRail** [comment]
I'll look at it
It might be an error with the `can_run_emote` proc but nothing strikes me as self-evident so you'll have to wait until this evening.
Apologies

**Comment by Pathid** [comment]
@ShiftyRail Correction to what I said: *beep works.

**Comment by ShiftyRail** [comment]
This is incidently the only one that I tested 😂 
I think it might be something with invalid playsound calls, I'll check the runtimes.

There is no reason that *dance should not work in theory, but I'm fucking retarded so nothing is impossible
