### ISSUE TITLE
custom vending machine needs some serious TLC because right now it makes me want to rip my dick off with the other end of a hammer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18862]
(WEB REPORT BY: wwwbabysdayoutmodewhengov REMOTE: 172.93.109.202:7777)
in rough order of importance

trying to add 10 of the same item, such as 10 identical pills, makes them all become separate listings taking up entire pages! it should obviously work like the kitchen fridge that groups up items of the same name

when you vend one of the 10 pills the listing for said pill shows up as SOLD OUT. forever. there's no way to clear it. not even as the owner. you now still have 2 pages of pills blocking the rest of your stock but now the entries are literally useless, too

EVERY FUCKING TIME YOU WANT TO ADD A NEW ITEM YOU HAVE TO SCREWDRIVER THE VENDING MACHINE AND INSERT YOUR FUCKING ACCOUNT NUMBER HOLY SHIT WHY. THIS ISN'T EVEN SECURE PEOPLE CAN FIND OUT YOUR ACCOUNT NUMBER IT'S NOT LIKE IT ASKS FOR YOUR PASSWORD TOO. please make the locking based on ID and let you use the controls without screwdrivering if wearing said ID

the UI does not update for any actions, such as adding items, setting price, screwdrivering, using the controls, literally nothing updates the window and you have to refresh it every time

trying to add a beaker/bottle to the vending machine results in you splashing the vending machine with it and then instantly inserting the empty beaker/bottle. sure you can put the lid on but holy shit why

you need 4 cardboard to make the empty recharge pack that does really nothing except let you build the vending machine... and then you get the cardboard refunded? I had to raid my department emptying boxes on tables just to build it, and even though yeah I can realistically manage this in a short time I really don't see the point to it, could be 2 cardboard instead and it'd change nothing

**Comment by Killette2** [comment]
Don't forget that they can be hacked as easily as any other vending machine to shoot out items

**Comment by Hugh-G-Rection** [comment]
Come down to central primary and see my collection of Knife, Hatchet and Broken Glass vending machines! What could go wrong?

**Comment by Exxion** [comment]
If anyone cares, open a new issue for the remaining 10%
