### ISSUE TITLE
Gyro doesnt make you spin anymore.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#18860]
#### Description of issue
Drinking gyro is supposed to make you spin, it didnt.
Might be related to #18857 since gyro makes you emote spinning out of control.

#### Length of time in which bug has been known to occur

Seems recent.

#### Server revision

Revision: 46aab02a2dcd1124eb3c87365a5eb75df1ffe5be 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
Fixed by #18858
