### ISSUE TITLE
A lot of in-hand sprites seem to be missing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18877]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
9d123d55b2278c5824c31a2ff562996b83aaf7c1

# Description
I feel like a bunch of in-hand sprites are missing. Maybe it's on my end, but... I can't see riot shields, or temperature guns among other things.

**Comment by SonixApache** [comment]
tasers as well...
