### ISSUE TITLE
Should the SPS/GPS be changed?

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18872]
There's some discussion in the comments of this shitpost here: #18856

If you have anything to add this is the place to do it.

Ideas from the shitpost:

> Only let security (no captain, no hop) have them

> multiple different "categories" of gps so for example cultists doing /spacebase/ shit who wanted to stay off the grid could set up their own category of gpses so they don't stick out like a sore thumb to anyone with a gps while also broadcasting to eachother. a bit like the pr that non broadcasting gpses don't show up on the list but more fleshed out.

And there's still #18734 up for debate

**Comment by boy2mantwicethefam** [comment]
delete sps lol, litrly better suit sensors bruh how bout sps be deleted also bruh whys removal of op things shitposts bruh they bouta throw me into the gulag those red sistants bruh wait till ysee oh no no no

**Comment by ShiftyRail** [comment]
The SPS promotes an interesting gameplay and rewards officers for paying attention to their fucking teammates
It discourages people from ganking a loot pinata and using the gear
It discourages people from just taking off people one by one in a boring fashion

It is, however, a tad too strong, especially against certain antagonists
- Cult can EMP rune them
- Traitor can EMP-nade them
- Changeling can silent/deathstung + strip in space (not very viable)
- Vampires are completly out of luck
- Revs and malf usually skip the "kill people stealthy" alltogether

I'm for #18734 to be merged (with the added suggestion), and maybe for some ways to disable them for vampire, a better way to deal with them as a ling (no EMP stings though) and perhaps an increased vulnerability to EMPs/explosions (the fact that they beep before exploding is ridiculous. If anything, they should not be able to give coordinates when exploding.)

**Comment by boy2mantwicethefam** [comment]
tbf who tf still buys empnades like bruh you wastin precious tc on consumables dont do that lmao

**Comment by Accipitermaris** [comment]
I'll just rewrite & post what I wrote in the PR:

>I'm not against removing SPS powercreep. I think we should change them so they don't beep upon death or stripping, but still exist on their own GPS network so we can still physically coordinate with others with them. Our movespeed is crazy high so being able to coordinate with the XYZ positions of others is vital even when you're patrolling with someone else in person. Think of reworked SPSes then, as just normal GPSes that simply exist on their own network as Security/Command's ghetto Holochips, & not entities that outclass both Tracking Implants & Cloning Backups in terms of death detection. I believe this along with the merging of the PR that allows the "broadcasting" of a GPSes coordinates to other GPSes to be toggle-able would be a good change. This is of course a ghetto fix. In an ideal world you could create your own secure networks of GPSes as anyone.

>Also, with all these changes in mind, I would ask people to seriously consider giving Security Officers some kind of non unga-bunga way of accessing the CMC while we’re on this topic. I can see why people might see a CMC in the Brig as too powercreepy (but nowhere near as powercreepy as AIs), but they might also see just giving Security access to the Bridge doors as powercreepy as well.

**Comment by Kitfox88** [comment]
They're useful for keeping sec officers or other high value targets from just being brutally murdered and vanishing for 5+ minutes before anyone bothers asking where they fuck they are, and beeping on death is very useful too. Removing the alert when they're removed is a good idea though, as is the possibility of adding different networks for other non-sec or command folk to use and muck with.

**Comment by nuklearcellphoneg** [comment]
Delete them and let sec fruitlessly pray for a pai instead.

**Comment by SonixApache** [comment]
I think the GPS is definitely a powerful crutch with the way it works -- you stow it in your survival box and forget about it. Which seems to have as side-effect that people generally don't watch the SPS list, but only act when it goes beep.
That said I'd definitely miss it. Seeing the squad drop whatever they're doing and sprint outta the brig whenever [HOP1 HAS BEEN STRIPPED IN FORE PORT MAINTENANCE]  shows up is hilarious.

Perhaps they should be made a little more subtle? A little beeping noise instead of the loud-as-fuck HL2 sounds, no chat prompt, a 'history' status after being stripped that indicates where and when it went off.

Oh and GPS tagging would be pretty good. Anything to cull the fucking ERT SPSes from the list. 
Maybe they should only show up on the list after being re-tagged.

**Comment by iFlashYou** [comment]
How about the strip and death alarm only works when the sps is on your belt or body armor storage slot?

**Comment by Irradiation** [comment]
Or the pocket slot, which is infinitely more sensible than outright removing the armor suit storage/belt slot.

**Comment by ShiftyRail** [comment]
@iFlashYou
Not a bad idea, if a bit weak.

**Comment by Dacendeth** [comment]
could make it make a little beep and flash sorta like how a PDA does, so you gotta pay attention and keep it in view.

**Comment by Blithering** [comment]
I never could see the issue, SPS only discourages the most unplanned of assassinations, assuming its not  just beeping at untouched lockers. The fucking loud half life sound effect could use toning down though.

**Comment by iFlashYou** [comment]
@Irradiation I mean to put it into your sec belt, not use the belt slot for it.

**Comment by Killette2** [comment]
Are SPS broken and overpowered? Absolutely
But so is stealth that antags get. Security is high priority targets, and this only works if the security team is working together. If all heads of staff had this it would be a different story, but I see no problem with officers having SPS.
