### ISSUE TITLE
Putting a mask of corgi in pocket takes time

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18871]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
06ad0474f1a9397a95550295320a7867d202276f

# Description
Putting a mask of corgi in pocket takes time as if you were trying to equip it

# Steps to Reproduce
Get a mask of woofer, put it in empty pocket

# What you Expected
Insta hiding

# What Actually Happened
[Character name] attempts to put on the mask of the corgi.
This is the message I got when putting it in my pocket

**Comment by Pathid** [comment]
#18205

**Comment by MadmanMartian** [comment]
closed by #18850
