### ISSUE TITLE
Unreliable Me emoting

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18882]
![broken me](https://user-images.githubusercontent.com/31839805/42931698-38292992-8af5-11e8-9ef8-deab1d4b0735.PNG)

I've been able to reproduce this but it's intermittent. It will occur and resolve itself after a minute or two. Also it may be specific to mimes.

**Comment by ShiftyRail** [comment]
I'll look into that
>It will occur and resolve itself after a minute or two.

May or may not be the static list of emotes clearing itself, although I highly doubt that.
I've personally been able to "Me" reliably enough when testing.

**Comment by ShiftyRail** [comment]
I am completely retarded (once again)
Let me clear that
