### ISSUE TITLE
Silicon airlock control panel is buggy if you're adjacent to the airlock

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#18899]
#### Description of issue
If you, the silicon, are adjacent to an airlock and hit an option on the menu here it will do an open/shut door command after whatever you do. In addition the box dialog won't update, again, only if you're adjacent to the airlock.
![airlock control](https://user-images.githubusercontent.com/31839805/42987299-98ae0a22-8bad-11e8-91cb-be73555c1bb7.PNG)

#### Specific information for locating
My guess it's due to #18542

#### Length of time in which bug has been known to occur
Pretty sure this didn't happen a month or two ago

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
Also lately the aghost door control seems a bit buggy. Like, hitting bolts seems to instantly try to open or close it. Possibly related.
