### ISSUE TITLE
Custom Vendors not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18904]
(WEB REPORT BY: robosperg REMOTE: 172.93.109.202:7777)
# Revision
f654a2bb69cadfa37ddd7379837431a06cffa014

# Description
Custom vending machines dont give out items when bought/hacked/emp'd

# Steps to Reproduce
Attempt to use one

# What you Expected
To markup prices

# What Actually Happened
No items came out

**Comment by jknpj** [comment]
Fixed
