### ISSUE TITLE
Pinpointers don't update to point to malf AIs if the security level is not delta

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18927]
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
# Revision
62cd864a38abea215454aee8b26cb87b6f85be0e

# Description
The pinpointer does not point to Shunted APCs.

# Steps to Reproduce
Try to use the pointer to find a shunted milf hiding somewhere so you can go take her out.

# What you Expected
To find that hot milf waiting for me

# What Actually Happened
The pinpointer pointed to the disk and didn't actually show us the milf.

**Comment by DamianX** [comment]
At first I thought I broke this when changing from `in world` to `in pinpointer_list` but according to this the pinpointers only get their new target if the AI shunts after delta, and I believe they might be able to shunt even before delta.
https://github.com/vgstation-coders/vgstation13/blob/62cd864a38abea215454aee8b26cb87b6f85be0e/code/modules/power/apc.dm#L972-L974

**Comment by Caboozles** [comment]
AI shunted after delta. That shouldn't be it.

**Comment by DamianX** [comment]
![image](https://user-images.githubusercontent.com/6307265/43041642-cc07b9e4-8d66-11e8-8d12-6302ee16c4e7.png)
![image](https://user-images.githubusercontent.com/6307265/43041648-e1d6c8fa-8d66-11e8-99dc-56e72c7e8e06.png)
![image](https://user-images.githubusercontent.com/6307265/43041651-f496477c-8d66-11e8-9b32-e1e051583691.png)

**Comment by soyconsumer** [comment]
The security level was set to blue after the AI went Delta, maybe that caused it?

**Comment by DamianX** [comment]
Yeah, that would do it.

**Comment by Inorien** [comment]
If this is the same round I'm thinking of, there was some fuckery with the disk itself which was suspected to be involved. IIRC there was a shunt and then the disk was destroyed/spaced after (?) such that it respawned, leading to the problem with the pinpointer

**Comment by nervere** [comment]
Fixed in #34683
