### ISSUE TITLE
Can't modify radios

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18926]
(WEB REPORT BY: mitchykins REMOTE: 172.93.109.202:7777)
# Revision
62cd864a38abea215454aee8b26cb87b6f85be0e

# Description
I can't engage or disengage a radio, or even change frequency, it keeps closing window
# Steps to Reproduce
Click on a radio, then click one one of the clickable texts, the window closes
# What you Expected
The clickable text to change and for the ragio to get engaged or disengaged
# What Actually Happened
The window just closed and the status didn't change

**Comment by DamianX** [comment]
ree #18925
