### ISSUE TITLE
Can't interface with intercoms/radios

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18925]
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
# Revision
62cd864a38abea215454aee8b26cb87b6f85be0e

# Description
Whenever clicking on the radio channels or intercomms, the dialogue box closes immediately without registering any changes.

# Steps to Reproduce
Be ~~AI~~ anyone including ghosts and humans
Try to turn on intercomms or other radios
Fail

# What you Expected
To be able to use the damn telecomms systems.

# What Actually Happened
The window closes immediately

**Comment by DamianX** [comment]
#18900 did it

**Comment by Caboozles** [comment]
Seemed to mostly affect the intercom within the core itself. Neither I nor my borg were able to turn it off, and I was unable to turn on medical/engineering/etc radios.
