### ISSUE TITLE
Mime and clown names default if you don't enter them right the first time.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18938]
(WEB REPORT BY: boosterrooster REMOTE: 172.93.109.202:7777)
# Revision
efc4fe87d6039d93f2c6b1bfc4fde80f2ab5974d

After trying to submit a clown/mime name and failing to do by either entering an invalid name or taking too long (not sure how long but after a few minutes) it doesn't change your name right and it defaults to the normal name for the player.

**Comment by DamianX** [comment]
Well, yes. That's what happens. You get 3 tries or 30 seconds.
What's the actual issue and what's a better alternative?

**Comment by jknpj** [comment]
Allow people to set a default name in their prefs too i suppose
