### ISSUE TITLE
Large Carboard Box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18935]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
efc4fe87d6039d93f2c6b1bfc4fde80f2ab5974d

The big old carboard box you make with four sheets that looks way better than the small one cannot go in any container ever, even a bag of holding, thus "The large box is too big for Bag of Holding." which isn't quite how bags of holding work

**Comment by Blithering** [comment]
I always saw things like that as being too big to fit into the bag's opening, making the pocket dimension size moot
