### ISSUE TITLE
Cutting/Pulsing a camera's focus light wire only reduces the visible radius for the AI, not for camera Computers

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#18940]
Surely there is a way to make it so vision is reduced when looking through a computer as well.

#### Steps to reproduce 
1. Open a camera's maintenance hatch
2. Pulse each wires with a multitool, until you find the one that toggles "The focus light is <b>off</b>."
3. With the focus light set to off, use a Security Camera computer to look through that camera
4. Observe that you can see up to 7 tiles away from that camera.
5. Turn yourself into an AI, and observe the area around that camera
6. Observe that you can only see up to 2 tiles away from that camera

**Comment by Exxion** [comment]
Duplicate of #3492
