### ISSUE TITLE
Phylactery cannot leave z-level while on person

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18947]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
888a7b487c560544005d71e82113e0acf6265650

# Description
Leaving the z-level with phylactery will ash you, even if you're carrying it
# Steps to Reproduce
spawn phylactery and try to leave the z-level while carrying it
# What you Expected
Not to get ashed
# What Actually Happened
ashes to ashes dust to dust

**Comment by MadmanMartian** [comment]
welp

**Comment by Arthurdentist** [comment]
https://www.youtube.com/watch?v=CMThz7eQ6K0
