### ISSUE TITLE
hitting glass floors removes gas sprites

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#18951]
#### Description of issue
made a glass plasma room to take off my suit and live in my natural element. when the gases were in the room I hit the floor which made the floor sprites change, which then removed the sprites of plasma in the air. 

#### Difference between expected and actual behavior
To see plasma in the air. 

#### Steps to reproduce 
make a part of or all of the floor glass, fill the room with a visible gas, I used plasma, but I suspect it works with other gases. 

![bug](https://user-images.githubusercontent.com/32474532/43123330-b596e5fe-8ed8-11e8-96a4-dff303fb3127.png)

**Comment by SonixApache** [comment]
placed glass floors are usually named 'airless' for the record
