### ISSUE TITLE
You cannot drool while unconscious.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18959]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
6d83492ec070ce638d7b0ad71ede87adc325aac0

# Description
>take drugs
>fall asleep
>You cannot drool while unconscious.

**Comment by Killette2** [comment]
Isn't that because you can't emote while unconscious and the way emotes work is so janky that it's just makes you /say emote*

**Comment by ShiftyRail** [comment]
@Killette2 It was like that before, expect that before that message did not show up, iirc.
