### ISSUE TITLE
borgs can't understand cats, probably dogs too? 

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#18952]
#### Description of issue
Got turned into a cat and was disappointed to see that no one could understand me. 

#### Difference between expected and actual behavior
borgs know every other language, why not this one? I suppose its because cats only meow or purr

more of a feature request than bug I guess.

**Comment by Pathid** [comment]
Due to #17339

**Comment by jknpj** [comment]
cats have no language
