### ISSUE TITLE
You can't kill yourself with a taser

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#18954]
#### Description of issue

Using a taser on your mouth with harm intent does not kill you.

#### Difference between expected and actual behavior

Expected : Suicide
Actual : Ouch but alive

#### Steps to reproduce 

See description

#### Specific information for locating

Probably the taser file

#### Server revision

888a7b487c560544005d71e82113e0acf6265650 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Dacendeth** [comment]
it crits you if you're not 100%, just do it twice in a row.

**Comment by Pathid** [comment]
It's a feature.

https://github.com/vgstation-coders/vgstation13/blob/0f34fdc907e712bae99de4915beca43306ef9670/code/modules/projectiles/gun.dm#L339-L349

**Comment by Exxion** [comment]
Actually is a feature for real
