### ISSUE TITLE
Night Vision without green tint

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18967]
(WEB REPORT BY: killroi REMOTE: 172.93.109.202:7777)
# Revision
b1d150c0ed95f6ce458236155a1499fa4eb92c32

# Description
Green tint from night vision goggles allows full night vision without green tint if you reconnect while wearing them
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by flagzzzz** [comment]
Related to #18533.
