### ISSUE TITLE
Hyperzine slows slime people

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#18972]
And I don't like it

**Comment by Pathid** [comment]
Capsaicin is the slime hyperzine. It's fiddly in that you have to take it in 2u doses or something or you start dying. It could be due to Celt's body temperature rework or maybe it's supposed to work that way, I dunno.

**Comment by Killette2** [comment]
Oh, I was hoping it wasn't a feature. That's just as awful then, seeing how fast slime people die to heat, which is faster than humans. Where did you get the 2u figure from? If that was tested I don't see why people would push it after

**Comment by Pathid** [comment]
There's a range of temperatures where they get a hyperzine-like effect without taking damage. Capsaicin is just really potent on slimepeople, which can be a good thing if your source is orange slime reactions.

**Comment by Killette2** [comment]
how do you do 2u at a time without wanting to kill yourself?

**Comment by DamianX** [comment]
IV drip?

**Comment by Pathid** [comment]
2u lasts longer than you'd think. It's the temperature that gives slimes speed, not the reagent itself.
