### ISSUE TITLE
Signing up for pAIs is broken

### ISSUE THREAD

**Issue by AceDick** [d3athrow/vgstation13#1897]
Tested on the test server, found that for whatever reason even though pAIs were being taken, never got a text notification in chat that one had been activated, over several rounds. Found that with testing all of the various pAI role settings and having another person activate a new pAI to test each, none gave a notification and no pAI personalities got submitted. Seems the same applies for posibrains although you can still click on them to sign up, you're never told when one is active.

**Comment by clusterfack** [comment]
I fixed this with my most recent pull. At roundstart someone activated a pAI and both I and others can confirm we got a text notification asking for candidates. Closeable.
