### ISSUE TITLE
Stripping/opening containers pulls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18974]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
f66146886e683798947c12209fe4cc4a877d2601

# Description
You can't stop pulling things on your tile when trying to strip/open any container

# Steps to Reproduce
Just try to strip anything or anyone

# What you Expected
Not retarded feature

# What Actually Happened
Retarded goddamn feature

**Comment by ShiftyRail** [comment]
A better report than #18973

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Sounds like a missing return

**Comment by ShiftyRail** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE I'm on it, for mobs it's a missing return, for objs it's that Mouse_Drop is defined twice (in a redundant fashion), and one of the procs call the parent, so it also calls the basic thing.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Oh actually for mobs it just always calls parent
I'll just push my fix and if yours is better just merge that one

**Comment by ShiftyRail** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE since I coded literally the same thing there's no reason to do it
