### ISSUE TITLE
Attaching an IV drip moves the IV drip

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#18978]
#### Description of issue

1. Attach IV drip to man
2. It attaches and moves
Edit: If you try to fold body bags it also pulls them towards you at first

#### Difference between expected and actual behavior

It should stand still

#### Specific information for locating

#18895

#### Length of time in which bug has been known to occur

Since memedragging was added

#### Server revision
4e0b350671bd7df4652ca3b1704ecd6b2c1fcb06

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yikes

I'll go through all the clickdrag cases tonight
