### ISSUE TITLE
Default cyborg can't open any door with bump move or other hard id checks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#18984]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)
# Revision
573906e9836229f4b591caeefaac9b6a48492b4b

# Description
Default cyborg's can't bump to open anything anymore
Can't use cargo consoles
Can't use exofabs
Can't use shuttle consoles

Safe to say anything with a hard id check which would include rnd shit, telcomms, etc is probably also broken.

Doors can be temporarily dealt with though accessing the door panel but it's still fucked

Picking a module seems to fix it but it's still discriminating against default.

# Steps to Reproduce
Pick cyborg and walk into a door

# What you Expected
Door to open
Cargo order to be accepted
Able to print shit 
Send shuttles

# What Actually Happened
Red denied light and sound
Your credentials were rejected by the current permissions protocol.
Unauthorized Access: attempted by 
Access denied.

@jknpj

**Comment by jknpj** [comment]
Cyborg access is now tied to their module, no module means no access.

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/db6048a3ed3f52e3240634e5ea979b36c455be73/code/modules/mob/living/silicon/robot/robot.dm#L1305-L1309

:thinking:
Maybe someday I should start reading those huge unatomic silicon updates you do.

**Comment by jknpj** [comment]
:man_shrugging: I guess it's my fault for forgetting to adding it to the changelog

**Comment by ghost** [comment]
Are you fucking serious? You're gonna rip out an entire way to play and just go not a bug/oversight? You were still able to doorknob, console, and drag around until it was clear which staffed positions could actually handle shit or not and where there was actually a need for a cyborg before you settled on one. It also gets you time to get someone to load metal in the fabs and someone that can actually follow You, man. Grab reset. Hit metal monster unga bunga if you're gonna take the gamble on being eng for the foreseeable future to get loaded fabs. There's no good reason to do away with it.
