### ISSUE TITLE
Scream emote doesn't play sound anymore (In space, no-one can hear you scream)

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#18987]
#### Steps to reproduce 
- Break a bone or pepperspray yourself
- Notice the "Space Man screams!" message in chat
- Notice no sound being played

#### Server revision
573906e9836229f4b591caeefaac9b6a48492b4b

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
Yikes
I'll look into it
