### ISSUE TITLE
Half-built Large Fishtank Filter construction doesn't refund 10 glass sheets on crowbarring

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19015]
(WEB REPORT BY: sarahjohnson REMOTE: 172.93.109.202:7777)
# Revision
c4d1b2ce078614e22092782e08d86b141c58ab7a

# Description
Doesn't refund the 10 glass on aborted construction

# Steps to Reproduce
Built a machine frame, cable'd it. Added a Large Fishtank Filter circuit, and 10 sheets of glass. Crowbar'd it to remove the circuit and glass and it only ejected the circuit.

# What you Expected
10 glass sheets in addition to the circuit

# What Actually Happened
Only the circuit

**Comment by ghost** [comment]
Wrenching an empty constructed one deletes it, the metal, the cable, and the circuit leaving only 4 of the 10 glass sheets.

Normal deconstruction also doesn't line up or work.
