### ISSUE TITLE
Beakers and the link fit in jars.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19062]
(WEB REPORT BY: boosterrooster REMOTE: 172.93.109.202:7777)
It seems a bit silly that when you try to pour your reagents into a jar it takes the container from your ahnd and puts it in the jar. Maybe blacklist beakers and the like.

**Comment by Dacendeth** [comment]
samething happens trying to fill a morter with a soda can, perhaps if someone could code only empty containers fitting in these?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
You can also put a jar into a jar.

**Comment by Exxion** [comment]
I hate to be the one to make this "joke" but jarjar
