### ISSUE TITLE
Making vending machines from recharge packs doesn't stock products

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19070]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
dce58643429b95eff27ae1f8c7aff967eaed4b8d

# Description
Build empty machine or deconstruct and reconstruct machine
->
drag vending pack to machine
->
vending machine changes to appropriate type
->
no product loaded

Interestingly enough, the font that the products use now also applies to the wires. Something's very fucky.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Odd, I'm sure I tested this
