### ISSUE TITLE
Inflatable Shelter ignores internals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19081]
(WEB REPORT BY: curver REMOTE: 172.93.109.202:7777)
Like the title says. The anesthetizing gasses knock you out, even if you're using internals.

This is weird.

**Comment by Irradiation** [comment]
The shelter **INJECTS** you with sleep toxin, which is why you go sleepy. Internals don't block sleep toxin sleepytime.

**Comment by MasterofNothing** [comment]
Then the description should be amended. Unless it's injecting a gas, which would probably put you to sleep forever.

**Comment by Irradiation** [comment]
@Kurfursten Hey kid, want a quikfix PR?

**Comment by MasterofNothing** [comment]
There's a more serious bug though. If the shelter is in space, you can't climb out. At least not by clicking on the sprite. It keeps injecting you forever and knocking you out.

Edit: never mind, you're just stationary on the same tile. I expected to be transported to another one. It's still technically a bug that it keeps injecting you, maybe?

**Comment by Irradiation** [comment]
I propose making a separate issue for that problem.

**Comment by Kurfursten** [comment]
You could change the text if you wanted yeah

Also incidentally it only injects you once (when you first enter), you can pass out multiple times from the dosage though. Incidentally, you need to Resist to leave, not click the shelter itself.

**Comment by MasterofNothing** [comment]
You should test it on a space tile and not adjacent to any objects. It doesn't work as intended then. Or at least I hope that isn't intended behavior.

**Comment by Kurfursten** [comment]
I can't tell what you're talking about exactly unless you are worried about the fact that you exit on into the shelter's tile?

**Comment by MasterofNothing** [comment]
That, and when you exit, it quickly injects you again as if you've just entered. And you're basically stuck, unless you throw something. But by the time you figure that out, you're likely sleep toxed again - at least once.

**Comment by Kurfursten** [comment]
Are you actually receiving the "injected" message again? Because I didn't reproduce that in testing but it's possible I missed it. You are not getting injected if you don't see the message again. You can fall asleep twice (briefly) from the one injection.
