### ISSUE TITLE
Packed does not have nearly enough holopads.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19086]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
b122addbc8ed9294c5e8c9b99b7d1e1bb2a774a8

# Description
They're missing in like, everywhere. Telescience, for one.

**Comment by strawberrytan** [comment]
lack of holopads on packed (literally) got me killed (medbayhasnoholopads) nerf (theresaholopadinthejanitorscloset) pls
