### ISSUE TITLE
RD labcoat doesn't show up on greys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19085]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
b122addbc8ed9294c5e8c9b99b7d1e1bb2a774a8

# Description
RD labcoat doesn't show up on greys. You can wear it, but it just doesn't show up. Incorrectly set sprite? Missing sprite?

**Comment by DamianX** [comment]
ree #18174
