### ISSUE TITLE
Giant Spiders Chitter in PokeBalls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19109]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
20f2412f4b9a1c1e8f63a22881d398df40136cfa

# Description

Giant spiders wont stop chittering when revived inside of their lazarus capsules
# Steps to Reproduce

revive spider.  Catch it before it destroys a window to space or all the lighting (which they continuously do.  Put in belt/backpack in lazerus capsule. 
# What you Expected

The asshole to stay quiet
# What Actually Happened

The giant spider chitters.

**Comment by jknpj** [comment]
Mobs can talk when inside objects, this isn't a bug.
