### ISSUE TITLE
Things appearing under racks, closets etc

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19107]
(WEB REPORT BY: tokmicz REMOTE: 172.93.109.202:7777)
# Revision
20f2412f4b9a1c1e8f63a22881d398df40136cfa

# Description
some things still appear under the texture of container or other structures, in this case a janibelt appearing under a rack

# Steps to Reproduce
Put thing on rack, sometimes it goes on top of it properly however

# What you Expected

# What Actually Happened

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
That last PR was only for machinery not structures
I'll see if I can reproduce this tomorrow

**Comment by Dacendeth** [comment]
things have appeared under racks for a while now, seems kind of random to me what will appear wrongly.
