### ISSUE TITLE
Inflatable Shelter Teleport Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19114]
(WEB REPORT BY: minimeatwad REMOTE: 172.93.109.202:7777)
# Revision
c8d57a27a2502992c13739bdf69a77479f72a962

# Description
the inflatable shelter will teleport to you if you can press the retrieve button, meaning a borg or possibly an AI can teleport a inflatable shelter to themselves by using the firelock's emergency shelter

**Comment by Kurfursten** [comment]
I should not have expected firealarms to have good sanity checks, they are so old
