### ISSUE TITLE
The Confectionator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19123]
(WEB REPORT BY: eremite5 REMOTE: 172.93.109.202:7777)
# Revision
c94e2f320a946e66980d06403f2fa0f4c43786aa

# Description
Each time an object is placed into the confectionator it produces a sugar version of what was placed inside but also returns the original object placed inside. I am not sure if this is the intended outcome or if this is a bug so I am reporting it just in case.

# Steps to Reproduce
1. Click on the Confectionator sprite with any handheld object in hand.
2. Allow the machine to work.
3. See that the result is a single sugar duplicate of the item inserted and the item itself.

# What you Expected
Only the sugar version of what was placed into the machine.

# What Actually Happened
The sugar version of what was placed into the machine as well as the origial item.

**Comment by SonixApache** [comment]
[working as intended]

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Item duping? Sweet

**Comment by SysadminJeroen** [comment]
It is not item duping, the "copy" made from the confectioner is a totally useless sugar copy.

Besides that, you require sugar for the confectioner to work.

**Comment by Exxion** [comment]
This is exactly how it's supposed to work
