### ISSUE TITLE
rockernauts feedback

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#19136]
cc @MadmanMartian 
there was some shitposting in the thread but we all know people rarely actually throw up issues to keep the feedback where we can see it so here

some of the key issues from that thread:
- You can't see them with the ore scanner unless you scan every single wall you dig -- should be screen-wide AoE like gibtonite at the very least
- They're too common
- They drop shit loot for how tanky they are (It's, what, one entire PKA magazine to kill one?)

I've yet to play mining since they got added, so I don't have any feedback to give personally.

**Comment by MadmanMartian** [comment]
>You can't see them with the ore scanner unless you scan every single wall you dig -- should be screen-wide AoE like gibtonite at the very least

They use the exact same process of revealing as gibtonite.

> They're too common

Easy tweak to be done

>They drop shit loot

I guess I can up the ore count? Some suggestions for loot would be helpful.

**Comment by SonixApache** [comment]
1: Cool, OP opinion discarded -- though maybe rock-o-vision optics would be nice
2: Cool, do it. Alternatively, keep everything as it is, but make them a lot weaker. Like, 60 health.
3: Rockernaut plates / gloves that make you punch harder? Guaranteed mythril/adamantite drops so you can wave around fancy useless ores? LEGO Rock raiders references?

Oh, hell, you could like, make the rockernauts drop a (material for a) glasses-slot item that lets you see rockernauts while they're still in the rock. A mesons upgrade for miners.

**Comment by jknpj** [comment]
We could make them have drop something that you can apply to yourself to make rockernauts ignore you unless they get attacked? "No john, you're the rockernaut."

**Comment by MadmanMartian** [comment]
![rogue roost kappa 2018-08-06 161738](https://user-images.githubusercontent.com/30557196/43725396-532d0396-9994-11e8-9912-0f56752210dc.png)
![rogue roost kappa 2018-08-06 161741](https://user-images.githubusercontent.com/30557196/43725401-5499fad6-9994-11e8-866e-e4716de5a871.png)

**Comment by SonixApache** [comment]
Hm, maybe they ment "like gibtonite" as in "Diamonds are rare, so you use the scanner when you see diamond, so you know it's gibtonite". But if rockernauts had unique sprites it'd kinda defeat the purpose.

**Comment by jknpj** [comment]
Someone also asked me to give some kind of exosuit-mounted mining scanner to ripleys because they can't deal with rockernauts at all

**Comment by MadmanMartian** [comment]
That doesn't sound too bad. I'll get onto that then

**Comment by SGuivenne** [comment]
I say don't nerf their toughness at all.  Let them cull the shit tier miners out. 

Gotta do more testing before I decide on commonality problems though.

**Comment by SonixApache** [comment]
I don't think it's about shit-tier miners getting rekt, it's about rockernauts being not even threat but a nuisance.

**Comment by MadmanMartian** [comment]
I've tweaked the numbers in #19139 , they're down to 25% of what they were previously (Eat shit, thanos)
