### ISSUE TITLE
Borgs can open lockers.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19138]
(WEB REPORT BY: dil9 REMOTE: 172.93.109.202:7777)
# Revision
812a908321b087c53209d8062491de51dc20202b

# Description
The c_ders changed something I liked, into something I do not like. Please get rid of them.
# Steps to Reproduce
Be in a locker.
# What you Expected
The usual.
# What Actually Happened
Powercreep.

**Comment by Pathid** [comment]
If it doesn't have a lock they can open it. If it has a lock they can only toggle the lock. As far as I know it's been like that forever.
