### ISSUE TITLE
Mapping for radstorm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19140]
(WEB REPORT BY: sgtgummibear REMOTE: 172.93.109.202:7777)
# Revision
812a908321b087c53209d8062491de51dc20202b

# Description
Was in a rad safe area under bot, right of the morgue and was killed by rad even though it was marked as a safe area.
# Steps to Reproduce
Rad is coming, walk into room right of morgue next to space heater, die, cry.
# What you Expected
To live
# What Actually Happened
gained super powers and died

**Comment by Pathid** [comment]
Which map? Also, be aware that radiation lights don't work when there's no power to the room.

**Comment by Dacendeth** [comment]
sounds like box with the landmark positions he said.

**Comment by Kurfursten** [comment]
@Exxion Can't reproduce

Also does not seem to apply to meta, deff, bagel, or roid. Could conceivably refer to packed? But I also checked out that map and it seems fine

I'd say close
