### ISSUE TITLE
Emotes are fucked episode 100

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#19142]
812a908321b087c53209d8062491de51dc20202b

\>start breathing from anesthetic tank
\>You cannot giggle while unconscious.

\>be AI
\>try to *ping or *buzz
\>nothing happens, no sound, no chat message, no error. It's not even in the *help output

\>be AI
\>*faint
\>you are now deaf

\>be AI
\>*help
\>notice how you are able to jump, spin (does nothing, obviously), stretch, wave, bow, flip(?) and other things a stationary brain-in-a-box shouldn't be able to do

**Comment by Killette2** [comment]
AI emotes could just be happening on screen, not the actual box itself
