### ISSUE TITLE
[Roid] - the windoor in front of the cargo computer is a bad idea

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19152]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
1757d7beb3bf7ae2af32f327c4934e8483821d68

# Description

It closes itself in the middle of your order, kinda annoying.

**Comment by brndd** [comment]
Windoor has been removed. Now the delivery office has privacy shutters. The intention of the windoor was to allow Cargo to control whether this desk is available or not, and the privacy shutters work better for this purpose. They're closed by default.
