### ISSUE TITLE
Roidstation Holodeck Issues

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#19163]
It still gets that problem where it stacks between modes where we got winter, chess, and thunderdome all at once. Also got zoo, beach, and metal foam walls. **Also, we have repeatedly reproduced a bug that moving at a diagonal through the border of the holodeck (e.g.: the door to the control room, or anywhere as a ghost) causes you to teleport to deep space and die.**

Also seems holocorgis and holo-weapons don't despawn when leaving the deck, but advanced holograms still do

**Comment by Irradiation** [comment]
Please add [OH GOD IT'S LOOSE].

**Comment by Kurfursten** [comment]
Might be related to the holodeck on the derelict level or the mapping of the holodeck zones on z2.

**Comment by Kurfursten** [comment]
@MadmanMartian Let's keep this open until it's tested

**Comment by brndd** [comment]
I don't know why this happens or what causes it. I took a peep at the holodeck code and there's no reason it should be happening, as there are no extra holodeck areas anywhere there shouldn't be, and the holodeck is pretty much copypasted from Box to begin with.

The PR I did earlier removes some holodeck areas from the derelict, as that was suggested as the cause. No idea if it will change anything, though, but we'll see.

**Comment by Exxion** [comment]
Holodeck is part dylancode and part ancient oldcode
I'm not really sure which part is worse

I can't imagine what could possibly cause the teleporting thing, but it's not the first time we've had an incomprehensible bug

**Comment by GeneralVeers25** [comment]
We did some testing earlier. It looked to me like the most likely culprit was the Snow Field Holodeck but this will need to be verified on other maps and rounds.

**Comment by Exxion** [comment]
The problem has been determined to be that it overlaps a shuttle area. The hyperspace throwers cause switching simulations to fuck up, and the hyperspace edges cause the teleportation issue.

**Comment by Kurfursten** [comment]
Ah, yes, @DamianX encountered the throwing issue. He was permanently flung to the right, along with some other people.
