### ISSUE TITLE
Detective coat rack can only hold one coat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19170]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
5e4172d0f2bc43e30b54388a61e34609202ae441

# Description

Coat rack only holds one coat
# Steps to Reproduce

Try decking out your wardrobe, experience dissapointment
# What you Expected

For the coat rack to actually hold multiple coats as the spriting suggests it would
# What Actually Happened

Dissapointment

**Comment by DamianX** [comment]
Actually, not a bug. It's because it holds a coat on one side and a hat on the other.
