### ISSUE TITLE
Anonymous Roidstation issue list

### ISSUE THREAD

**Issue by brndd** [d3athrow/vgstation13#19177]
Someone sent this to Osseus. Submitting here so it doesn't get lost.

Bar door doesn't require bar access
Juke spawns with no viynals in it, should be the bar subtype.
No plasma in chemistry roundstart
Medbay door control panels for civilian exit arent general access.
(opinion) the medbay floor color scheme is absolutely repulsive and clashes goddam everywhere, physically hurting my eyes, and random tiles are just the wrong color compared to their surroundings
Cargo shuttle conveyors, not all linked to levers and the unloading one also goes into the shuttle instead of out of it.
No wire under SME power monitoring computer
Wire missing in cargo lobby next to the APC. As is the Arrivals APC
Auxilliary tool storage missing vents and scrubbers
Brig cells have no cell timers/id_tag on doors
Pretty much every status display on the station is for the supply shuttle
Unsimmed roid turfs in dorms somewhere causing dorms to vent at an alarming rate, isolated to the top right palm tree and the two turfs to the left of it
Botany has an extra bioballistic delivery system it doesnt need.
Daves zoo is also hyper fucky atmos, probably unsimmed turfs again, whole station probably needs checking for those
Holodeck is busted in about 10 different ways, including being able to load in multiple holodecks at the same time and someone randomly teleporting into space when they went through the top right door.
Secure armory firelock is facing the wrong way, on the north of the door instead of east/west.
Hardly any fire alarms
Table in front of the chem fridge in chemistry so you can't actually get to it.
Centcomm ferry docks at one of the escape shuttles docks so they'll collide

**Comment by Lunstra** [comment]
Oh this is the list I wrote up from the ahelps we got in the first round and like two things i noticed myself

**Comment by brndd** [comment]
>(opinion) the medbay floor color scheme is absolutely repulsive and clashes goddam everywhere, physically hurting my eyes, and random tiles are just the wrong color compared to their surroundings

Medbay colour scheme has been redone.

>Bar door doesn't require bar access
>Juke spawns with no viynals in it, should be the bar subtype.
>No plasma in chemistry roundstart
>Medbay door control panels for civilian exit arent general access.
>Cargo shuttle conveyors, not all linked to levers and the unloading one also goes into the shuttle instead of out of it.
>No wire under SME power monitoring computer
>Wire missing in cargo lobby next to the APC. As is the Arrivals APC
>Auxilliary tool storage missing vents and scrubbers
>Brig cells have no cell timers/id_tag on doors
>Pretty much every status display on the station is for the supply shuttle
>Unsimmed roid turfs in dorms somewhere causing dorms to vent at an alarming rate, isolated to the top right palm tree and the two turfs to the left of it
>Botany has an extra bioballistic delivery system it doesnt need.
>Daves zoo is also hyper fucky atmos, probably unsimmed turfs again, whole station probably needs checking for those
>Secure armory firelock is facing the wrong way, on the north of the door instead of east/west.
>Table in front of the chem fridge in chemistry so you can't actually get to it.

Fixed all of the above.

>Holodeck is busted in about 10 different ways, including being able to load in multiple holodecks at the same time and someone randomly teleporting into space when they went through the top right door.

Might not be Roidstation-related. Pending investigation: #19163

>Centcomm ferry docks at one of the escape shuttles docks so they'll collide

Will be fixed later.

>Hardly any fire alarms

More specificity would be useful. I've tried making sure every room has one fire alarm. Hallways could benefit from having multiple. Fixing this right now is a bit of a pain, because fire alarms in the mapper look like this at the moment: 

![alarm](https://i.imgur.com/LyT59ri.png)

**Comment by SonixApache** [comment]
worth checking: medbay south exit button opened the wrong door -- the door behind the counter opened rather than the actual exit doors

**Comment by brndd** [comment]
Pretty much all of these are fixed and what aren't will be fixed when we do a restructuring patch, so this can be closed.
