### ISSUE TITLE
Roid Library window is space.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19182]
(WEB REPORT BY: meetmeindorms REMOTE: 172.93.109.202:7777)
# Revision
210957064a54932f3050325930cbea8cc3bbb45b

# Description
The Roid Library window is space. This is obvious whenever there is a power outage since it is still bright as day.

# Steps to Reproduce
>play roid
>go to library
>right-click library window
>is spess

# What you Expected
flooring

# What Actually Happened
It is space.

**Comment by kilozombie** [comment]
This is true in a few places. I'm pretty sure it's true in the windows for Escape.
