### ISSUE TITLE
Posibrain non-functional emotes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19190]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
b3ec3a8124087d625c9d65e5304bee4b28472106

# Description

Everal emotes are listed under posibrains but not actually viable, these include *flip and *spin
# Steps to Reproduce

use *help, verify emote list, attempt these two emotes.
# What you Expected

Weird shit, like angrily flapping as a robot 
# What Actually Happened

nothing at all

**Comment by Pathid** [comment]
There's also *cross, which actually works but makes little sense in the way it displays.

``PBU-555 crosses their arms.``
