### ISSUE TITLE
Power outage events could knock out all radio, snowflake style

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#19194]
Nocomms is a meme. It's a bad meme. I don't like it. Yucky!

_But_ there's something interesting about the idea of a period of time where you can't communicate to your fellow crew members efficiently. Right now, the power outage event is almost that, but you can't know if somebody you're after has a station-bounced radio or if they're just competent at using intercoms.

What if in that very short timespan, people are completely unable to radio anyone? It might make the short power outage more scary, since you've absolutely not got a lifeline in case you're ganked. Maybe only _mildly_, because it's so short, but even an extension of a couple minutes could make it a real deal.

I dunno. Might be stupid. I wanted to float it by, though.

**Comment by DrSnips** [comment]
I think we already have a tcomms outage event. As for station bounced radios Ive always thought of them like walkie talkies where they don't require you to have some type of comms system to work.

**Comment by kilozombie** [comment]
For sure, which is why it'd have to be snowflaked in. Maybe it's an errant drone jamming up radio, or some sort of bluespace anomaly.

**Comment by Pathid** [comment]
Putting some unreliability factor on SBRs makes sense. I don't know if tacking it onto the grid check event really follows from an IC perspective though.

**Comment by Blithering** [comment]
We do have a telecomms malfunction event don't we? Probably better to incorporate it into that than power outage

**Comment by Pathid** [comment]
Thing is there's a feature of the comms blackout event: It means if the comms go down, you don't immediately know whether it's foul play. If you can pick up an SBR and rule that out you lose a lot of that designed-in uncertainty.
