### ISSUE TITLE
Food in the chapel doesn't

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19199]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
a3ee0e3e79f7954bf39e607807eab2ee40dd541e

# Description

Food in the chapel doesnt foood, if you eat the poppies or the harebells it just tells you "theres nothing left" and despawns them.

# Steps to Reproduce

Eat shit in the chapel
# What you Expected

To get nourishment
# What Actually Happened

Faith is a hoax.

**Comment by SGuivenne** [comment]
This is for roidstation mind you.

**Comment by brndd** [comment]
They're funeral flowers not food, you heathen.

**Comment by kilozombie** [comment]
Titles that sound wrong until they make sense

This is probably due to some fuckery with how it's placed on the map considering harebells are supposed to contain nutriment, and poppies are definitely supposed to have plant-bicaridine.

**Comment by SirSkeleto** [comment]
this is also true of other maps
