### ISSUE TITLE
Roidstation Holodeck fucked in general

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19193]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
a3ee0e3e79f7954bf39e607807eab2ee40dd541e

# Description

Using MOST of the holodeck rooms completely break it, including but not limited to snow field and Meadow.

Get fucked celt.
# Steps to Reproduce

Muck with the holodeck
# What you Expected

A snowy field
# What Actually Happened

Global Warming.

**Comment by Kurfursten** [comment]
duplicate
