### ISSUE TITLE
roidstation has a centcom pda printer in hop's office

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19209]
(WEB REPORT BY: smallboss REMOTE: 172.93.109.202:7777)
# Revision
95dee60f24e92dd7b5394917b771d1a03053ddb9

# Description
the pda printer in the HoP's office is the one that's used on centcom, rather than the one ment to be used on station
# Steps to Reproduce
1. be hop
2. notice that you can recolor your PDA to all of the PDA schemes (nanotrasen official, military pda, etc)

**Comment by brndd** [comment]
The PDA printer looked to be the exact same one as on Box, but just to be safe I've now literally copypasted the Box one on top of the one on Roid. If this issue persists after the update, then it's a feature.
