### ISSUE TITLE
Mechanics start with welding mask down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19210]
(WEB REPORT BY: autisticmouse REMOTE: 172.93.109.202:7777)
# Revision
95dee60f24e92dd7b5394917b771d1a03053ddb9

# Description

Not a huge bug but the mechanics seem to start with their welding mask ready for hardcore welding

# Steps to Reproduce

Be a mechanic

# What you Expected

Welding mask to be in the normal non-welding position

# What Actually Happened

Blinded by the non-light

**Comment by Irradiation** [comment]
That's not just a problem with mechanics, just about EVERY welding mask on every map everywhere starts in the ready-to-weld position.

**Comment by SonixApache** [comment]
the obvious solution is to remove mechanics

**Comment by ghost** [comment]
Do we actually want that though ? The welding mask up sprite looks pretty jarring just sitting around
