### ISSUE TITLE
Chefs don't have access to Asteroid Station chef maintenance door

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#19225]
Really helpful QoL thing that's in other maps.

**Comment by Kurfursten** [comment]
If chefs don't there is the more worrying thought that maybe assistants do

**Comment by brndd** [comment]
It requires *both* Kitchen and Maintenance access, when it should only require Kitchen access. So Assistants don't have access to it, but neither does the Chef—or almost anyone else on the station barring all access, for that matter.
