### ISSUE TITLE
hemorrhoidstation kitchen has no lightswitch, botany and botany backroom use the same lightswitch

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19227]
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
and the bar has only one lightswitch and it's behind the bartender table

**Comment by Pathid** [comment]
>and the bar has only one lightswitch and it's behind the bartender table

Hey, on Box it's in the bar backroom. Do any of the bars have one in public reach?

**Comment by Kurfursten** [comment]
Box:
* Kitchen: Cooking area only
* Bar: Backroom only
* Botany: Main+Backroom share lightswitch

Packed
* Kitchen: Cooking area only
* Bar: Bartender accessible only
* Botany: No backroom, no lightswitch

Meta
* Kitchen: Cooking area only
* Bar: Public switch only
* Botany: Yes, both

Deff
* Kitchen: Cooking area only
* Bar: Bartender accessible only
* Botany: No lightswitch at all

Bagel
* Kitchen: Coldroom only
* Bar: No lightswitch at all
* Botany: Main+"Backroom"(side)+"Circle" share lightswitch

**Comment by brndd** [comment]
Lightswitches toggle lights for the entire area (that is, per APC). The one on Box toggles both the Botany trays and the Botany backroom, too.

**Comment by brndd** [comment]
Added lightswitches to kitchen in #19248 and forgot to document it. This can be closed.
