### ISSUE TITLE
can play arcades as ghost and it spawns non-ghost prizes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19226]
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
# Revision
4c339ee9c3013b16efc399fcc4692c1f5b1687d4

# Description
can play arcades as ghost and it spawns non-ghost prizes
# Steps to Reproduce
play arcades as ghost and it spawns non-ghost prizes
# What you Expected
can not play arcades as ghost and have it spawn non-ghost prizes
# What Actually Happened
can play arcades as ghost and it spawns non-ghost prizes
# Additional Information
can play arcades as ghost and it spawns non-ghost prizes

**Comment by Kurfursten** [comment]
When this gets fixed, whoever fixes it should leave in a ghost compatible arcade version for FUN purposes. Kinda like how the multiman wheelchair became a thing.

**Comment by DamianX** [comment]
https://github.com/vgstation-coders/vgstation13/blob/cbdaf449ab71363984869d1e3d4b493854b2ee72/code/game/machinery/computer/arcade/arcade_game.dm#L147

I assume this was copied from when it was an obj/machinery subtype, which would work correctly. As it is, that super-call does nothing.

The fact that it went unnoticed this long is surprising.

**Comment by Dacendeth** [comment]
It makes me wonder what would happen if a ghost played cuban pete and lost..

**Comment by SGuivenne** [comment]
@Dacendeth we need to test that for science

**Comment by Kurfursten** [comment]
gibbing a ghost does nothing, tried it before
