### ISSUE TITLE
Improvements to Roidstation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19221]
(WEB REPORT BY: filterfish REMOTE: 172.93.109.202:7777)
# Revision
4c339ee9c3013b16efc399fcc4692c1f5b1687d4

# Description
I would recommend adding a meteor fence around the exposed area of atmospherics on Roidstation.  The air tank and o2/n2 lines are particularly vulnerable to meteor strikes.  Since atmos has to work harder to keep the station pressurized on this map, this would really help.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by brndd** [comment]
Solid idea. Most other directions appear covered, but that one is both completely exposed and right next to the edge of the map, which probably makes it more likely to be struck in the first place.

**Comment by brndd** [comment]
Fixed as of #19248
