### ISSUE TITLE
Conveyors fuck ZAS up, splitting rooms

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#19239]
#### Description of issue

When using many conveyors, the room splits into different ZAS zones not interchanging air

#### Difference between expected and actual behavior

Expected the whole room to be cold, got delamination on two different maps (Box and Asteroid)

#### Steps to reproduce 

1. Order shards
2. Add cooling and conveyors to the SME room
3. Put shards in and turn it on
4. You will now observe that only a small portion of the shards gets cooled, those in their independent zones heat up and start to delaminate since appearently conveyor belts split rooms

Video: https://i.4cdn.org/wsg/1533837647546.webm

#### Server revision
407c904603b07c81f48d72d30beae49cea1001f5

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Chazach** [comment]
the air is pulled away by the conveyers
its a feature

**Comment by Exxion** [comment]
Hold on. Where in Box did this happen? You said the SME room, but are you sure it wasn't the AME room?
The room in the video is the Asteroid AME room, which apparently has the same mapping issue as the Box AME room, where a bunch of the tiles are varedited to have `blocks_air = 1`

**Comment by StreptoMutans** [comment]
I tried it in the AME room in Box and it didn't cool properly. People claimed it was an ancient bug with the map, so I tried it in the AME room in Asteroid and it happened too. Did he really add the "ancient bug" to the newest map too?

**Comment by Exxion** [comment]
I assume he copied and pasted the Box AME room, since yes, it also has the air-blocking tiles

**Comment by brndd** [comment]
The bug is caused by tiles that have been manually edited to have `blocks_air = 1`. There's no way to tell these apart at a glance in the mapper, so they were carried over to Roidstation through copypasting from Box like some sort of a filthy oldcode STD, and festered in the fertile virgin soil of Roidstation until there were **four hundred** `blocks_air = 1` tiles on the station. Holy shit ZAS must be fucked.

I'm gonna do another bugfix for this and a bunch of other issues soon.
