### ISSUE TITLE
1! bite of spicy eggplant sushi will kill you as a slime person. 

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#19243]
#### Description of issue
was a slime person, got hungry made some food from slime extracts, spawned some spicy eggplant sushi, took 1 bite died minutes later from the avalanche of pain from hot sauce, admin said I had acquired upwards of 180+ burn damage? This is probably working as intended, but I brought this here to say perhaps this is maybe a little too severe? or perhaps some kind of warning that this shit can horribly kill you as a slime person.

**Comment by RealestEstate** [comment]
were you a white slime person? you know the penalty stacks when you’re both.

**Comment by spoonylove** [comment]
If I recall I was blue. that may be it. Im not sure.

**Comment by DrSnips** [comment]
I don't recall color having an impact on your stats unless you're talking about it being a phazon mutation.

**Comment by Kurfursten** [comment]
He was rather blueish, the eggplant was not tampered with, and he had 188 burn

**Comment by Pathid** [comment]
Capsaicin is incredibly dangerous to slimepeople.
See #7869 and #7882 and how the latter doesn't touch the slimepeople part of capsaicin code. Some portion of it has to be unintended.

**Comment by spoonylove** [comment]
I'm fine with it being dangerous, but as said I took 1 bite, knowing "oh this stuff is pretty hot, lets test it out with one bite to see how bad it messes me up i'll just fix myself up." NOPE. I've never really had experience with slime people until recently and everything written just says a problem with cold, a warning definitely needs to be put somewhere.

**Comment by Pathid** [comment]
What were you wearing at the time? Heat insulation comes into play here. If you're wearing a space suit you can't cool down at all.

**Comment by spoonylove** [comment]
do lab coats insulate that hard? I was just in the basic scientist gear.
