### ISSUE TITLE
roidstation xenobiology slime extract fridge dies and never comes back, can't unwrench to move it either. 

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#19244]
#### Description of issue
power went out, fridge was unusable and unwrenchable, it just had to sit in the corner dead. 

I've noticed there are lots of APCs in the room in a weird layout, I assume this is what is fucking with the power to the fridge. each cage seems to have its own APC except the bottom right which also holds the power to the lights?

#### Difference between expected and actual behavior
I can understand it not working when there is no power but when it had come back on the machine still refused to work. The other problem is that it cant be unwrenched? As far as I know simply trying to unwrench it with a tool did nothing, it was trying to store the wrench.

#### Steps to reproduce 
roidstation xenobio, put something in the machine, with power, cut power to the room, notice how you cant put things in. restore power, still unable to use the machine, or wrench to a different part of the room that is getting power.

**Comment by brndd** [comment]
As far as I can tell the machine is identical to the one on other maps. Perhaps this is not Roidstation-related?

**Comment by Pathid** [comment]
I know that fridges can't be unwrenched to move. You have to reconstruct them in another place. Might want to double-check what area that turf it spawns on is part of though.
