### ISSUE TITLE
Roidstation security maint door requires security access

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#19245]
#### Description of issue
![image](https://user-images.githubusercontent.com/26881007/43936853-8e04f38e-9c28-11e8-83be-f574f1ce5101.png) 
That maint door on the right can't be opened with just maint access and the maint area on the other side doesn't require any access besides maint to get to so it seems weird that door is access restricted.

**Comment by brndd** [comment]
I think I put security access on this thinking all maintenance airlocks into security need it, but in retrospect this clearly leads into the security lobby area which is public access. We'll fix that and give maintenance in general some love in Roidstation \~version 1.1\~
