### ISSUE TITLE
Out of place tile in roid medbay

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19257]
(WEB REPORT BY: tolan1 REMOTE: 172.93.109.202:7777)
# Revision
149580c92d1d552f611ae13c17ee14218dfbd8f4

# Description
Whoever made the medbay dark forgot a tile under the airlock to virology exterior from medbay
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
And a tile under Chemistry
And a tile under Cloning
