### ISSUE TITLE
Greytide Implant lacks a HUD to show other implanted dudes

### ISSUE THREAD

**Issue by ProfanedBane** [d3athrow/vgstation13#19250]
#### Description of issue
Greytide implanted dudes only get a HUD to show who implanted them, any other implanted minions lack any tell, which may or may not lead to some confusion in a firefight.
Unsure if this is a balance decision or just something we never bothered to do.

#### Difference between expected and actual behavior
**EXPECTED:** Something to identify fellow greytiders.
**ACTUAL:** Local man ruins everything with friendly fire.

#### Steps to reproduce 
\>get implanted
\>find someone else who's implanted
\>behold

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MadmanMartian** [comment]
Greytided should all be in the same faction now
