### ISSUE TITLE
rollerchairs dont act like chairs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19251]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
50d6b9ca3cdd2c022838922c41e65235b4b07519

# Description
rollerchairs do not protect from slips or other shenanigans

**Comment by SonixApache** [comment]
doesn't protect from the memechair either lmao

**Comment by DamianX** [comment]
Should it?

**Comment by DeityLink** [comment]
Fixed by #30082
