### ISSUE TITLE
AI Jump To Network verb and Show Camera List buttons don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19263]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
149580c92d1d552f611ae13c17ee14218dfbd8f4

# Description
I've been getting this issue more often now. Neither of the buttons seem to do anything. I've tried restarting byond and relogging multiple times. I'm on BYOND 512.1429, and this was most prevalent on Roidstation.
# Steps to Reproduce
Join as AI on roidstation - hit Show Camera List button or Jump To Network button - cry as nothing happens
# What you Expected
List of cameras
# What Actually Happened
No lists!

**Comment by brndd** [comment]
Clicking on that button on Roidstation produces a runtime:

```
[08:32:03] Runtime in tracking.dm,18: type mismatch: "SS13" & /list (/list)
  proc name: get camera list (/mob/living/silicon/ai/proc/get_camera_list)
  usr: Siri (burneddi) (/mob/living/silicon/ai)
  usr.loc: Mainframe Base (133, 157, 1) (/turf/simulated/floor/bluegrid)
  src: Siri (/mob/living/silicon/ai)
  src.loc: Mainframe Base (133,157,1) (/turf/simulated/floor/bluegrid)
  call stack:
  Siri (/mob/living/silicon/ai): get camera list()
  Show Camera List (/obj/abstract/screen): Click(null, "mapwindow.map", "icon-x=17;icon-y=19;left=1;scr...")
```

This is triggered when a camera has an incorrectly defined network list that is not a list but a string. On RoidStation, it's a camera in hydroponics:

```"aTp" = (/obj/machinery/camera{dir = 1; name = "Hydroponics Office"; network = "SS13"},/obj/machinery/botany/editor,/turf/simulated/floor{dir = 1; icon_state = "green"},/area/hydroponics)```

I'll push a fix for this and include it in #19262. It would also be good to fix the AI code so it doesn't catastrophically fail when a malformed camera like this exists. It also seems to affect the regular cameranet code too, though:

```
[05:12:16] Runtime in camera.dm,72: Cannot read "SS13".len
  proc name: New (/obj/machinery/camera/New)
  src: Hydroponics Office (/obj/machinery/camera)
  src.loc: the floor (172,170,1) (/turf/simulated/floor)
  call stack:
  Hydroponics Office (/obj/machinery/camera): New(the floor (172,170,1) (/turf/simulated/floor))
  Hydroponics Office (/obj/machinery/camera): New(the floor (172,170,1) (/turf/simulated/floor))
```
