### ISSUE TITLE
THERE ARE NO NEWSCASTERS ON ROID STATION!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19261]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
# Revision
149580c92d1d552f611ae13c17ee14218dfbd8f4

# Description
exactly what it says on the title

**Comment by spoonylove** [comment]
Someone tag this with oh god its loose

**Comment by soyconsumer** [comment]
The library literally got zero (0) newscasters
