### ISSUE TITLE
All Newscasters spam the ghosts with their updates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19278]
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
# Revision
1dc5ffdf3f904095c4abb468396d1b7d446bf03e

# Description
Each newscaster individually announces each update to all ghosts, resulting in massive spam.
# Steps to Reproduce
Observe when someone uploads a new article
# What you Expected
Not to be spammed by everything.
# What Actually Happened
Got spammed

**Comment by Pathid** [comment]
Pretty sure you can blame #19269

**Comment by Kurfursten** [comment]
Ghosts now also hear every vending machine at all times rather than just the ones in view, annoying

**Comment by DamianX** [comment]
Looks like this behavior of `send_speech` is intended. https://github.com/vgstation-coders/vgstation13/blob/1dc5ffdf3f904095c4abb468396d1b7d446bf03e/code/modules/mob/say_readme.dm#L71-L72

Maybe newscasters and vending machines should use a different proc?

**Comment by Kurfursten** [comment]
Shuttles also get sent however they're less annoying
