### ISSUE TITLE
Roidstation: Misc Xenoarch/Mining Issues

### ISSUE THREAD

**Issue by ProfanedBane** [d3athrow/vgstation13#19275]
- Science seems to lack any latex gloves for that sweet sweet anomaly resist
- There doesn't appear to be anomaly suits anywhere for that matter
- The leftmost anomaly harvester cannot connect to it's scanpad
- There's no monkey test subjects for xenoarch (not a huge issue since you can order them ez pz from cargo)
- The Mining Outpost Escape Pod isn't actually an escape pod

**Comment by brndd** [comment]
>The Mining Outpost Escape Pod isn't actually an escape pod

Turns out we're out of available escape pods and the code for them is AWFUL, so I'm just going to have to delete that one unfortunately.
