### ISSUE TITLE
TEG chamber on roid station problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19279]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
# Revision
1dc5ffdf3f904095c4abb468396d1b7d446bf03e

# Description
yeah the magmaws are a nice idea and shit, but after testing it i feel like it needs a way to feed the burn chamber with oxygen and plasma to accelerate the burning rate

using the 2 round start magmaws i got to like 150°C after some minutes and that's pityful

**Comment by brndd** [comment]
Magmaws probably need a buff to their heat generation. It'd be neat if they shat out actual magma instead of doing the fireball shit they're doing now. I'm adding a way to use the TEG as a regular TEG.

**Comment by Jubisloviu** [comment]
Magma would be god tier
magmaws are decent if you manage to gather a fuckton of those, like 6~8 or so, but with only 2 there's not much you can actually do
