### ISSUE TITLE
Roidstation: Gulag Overpressurizes the Permanent Confinement Area

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#19288]
#### Description of issue
What it says on the tin. Seems to happen every round.

#### Difference between expected and actual behavior
---

#### Steps to reproduce 
If it doesn't happen naturally on its own, try opening one of those Blast Doors in the cells that are used to cycle in prisoners, leaving them open, and seeing what happens. They might be the source of the issue. Somehow. They're the only consistent variable I can isolate as the Gulag "Distro" looked fine & it was only the main Perma room that was overpressurizing.

#### Specific information for locating
---

#### Length of time in which bug has been known to occur
---

#### Server revision
---

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
does #19282 fix this? @brndd

**Comment by Accipitermaris** [comment]
fug I missed that pr, my bad

**Comment by brndd** [comment]
@DamianX yes it does
