### ISSUE TITLE
Borers inside hosts can't see emotes

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#19291]
#### Steps to reproduce 
- be borer inside host
- non-host does a "me dabs!"

#### Expected result
"Non-host dabs!"

#### Actual result
absolutely nothing

#### Server revision
f1f47fdc976f2e3d7218e1f1350edb40a0db521a

**Comment by ShiftyRail** [comment]
Probably the same reason why pAIs could not see them.
I am away until the 15th but I'll have it fixed at that date.
