### ISSUE TITLE
Sand and Singularities don't Mix

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19301]
(WEB REPORT BY: generalveers25 REMOTE: 172.93.109.202:7777)
# Revision
a4b4140783d045b634a30a5191c1fede34762218

# Description
Sand tiles become pitch black when messed with by the Singularity. See: https://lambda.sx/sJN.PNG
# Steps to Reproduce
Release the Singularity onto a beach.
# What you Expected
Not ugly stuff.
# What Actually Happened
Ugly stuff.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Sounds like a randomly generated headline

**Comment by PaulRitter** [comment]
tested, no longer an issue.

pls close
