### ISSUE TITLE
mime's screaming silently plays the audio scream

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#19310]
#### Description of issue
Normally when a mime "acts out a scream" no audio clip is played, but now they do.

#### Difference between expected and actual behavior
silence vs sceaming

#### Server revision

Revision: a4b4140783d045b634a30a5191c1fede34762218

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MadmanMartian** [comment]
the acting's so convincing, you trick yourself into thinking you heard it
