### ISSUE TITLE
roidstation chemistry has no syringe box and only one beaker box what the fuck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19314]
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
# Revision
49bb3148e75bd51cfc2e274a2eea3ff2806df705

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by brndd** [comment]
They're in the locker.
