### ISSUE TITLE
Custom vendors not trader-friendly, and go by ID name rather than linked account

### ISSUE THREAD

**Issue by VNLoverMay** [d3athrow/vgstation13#19322]
#### Description of issue
Two seperate issues here.
One, the custom vendor is pretty much useless to the job that it should be the most useful to, since they can't turn off edit mode on the vendor as vox IDs are NOT account linked, and even if they were, it wouldn't work because...
Two, the vending machine checks for name rather than linked account. This is obviously NEVER going to work for traders, and it makes it a fair deal easier to spoof, especially by someone with an agent ID.

#### Difference between expected and actual behavior
Traders should be able to use the custom vendor to facilitate easier trading, however the way it's set up doesn't let traders use it at all.
Traitors should not be able to steal everything from said vendor simply by purchasing an Agent ID and changing the name to "Trader Shoal", but they can totally do that.

#### Steps to reproduce 
Attempt to use a custom vendor as trader, realize your ID doesn't work, ahelp to try and find some sort of solution, be absolutely bewildered when account linking doesn't fix it until you go code diving and find, for some reason, it goes off of name.

#### Specific information for locating

Because of aforementioned code diving, I have the exact location of the offending code.
https://github.com/vgstation-coders/vgstation13/blob/61e36ee262535713912d9bafbc80661b6eb54dd3/code/game/machinery/vending.dm#L476-L489
However, just changing it to check the account on the ID will NOT make it work for traders, as their IDs are not associated with the account.

#### Length of time in which bug has been known to occur

Ever since #18921 was merged.

#### Server revision

Game: 49b9a131db5a4e9882dc337351967d95077decea 
Patches: 998316155b9c9210ca3d87fb7313d9cf2b30f871 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by WhiteHusky** [comment]
I'll have to take the code I've added in #19192 and split it to check authentication for situations like this, but as you said even checking for account number won't work because chances are trader IDs don't have the correct account information.

However that's a problem resolvable IC by asking a HoP to change the card's account number to the desired account.

Alternatively, we create an item who's purpose is holding an account number (Credit Card!) and spawn it on the trader shuttles.

**Comment by VNLoverMay** [comment]
I think a seperate item is definitely preferable to having traders needing help from the station to use vending machines, considering they're usually reluctant to help anyway. Perhaps a seperate card locked inside the safe or something would be good enough.

**Comment by WhiteHusky** [comment]
I'll try to cobble something together as a prototype to get a card in the game and later pop it on the trader shuttles.

It'll be similar to an ID but lacks any access, only to keep an account number. Maybe you can create a new credit card from any ATM for like $5 (to prevent infinite cards).
