### ISSUE TITLE
Add a *boop for the sillycons

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#19362]
We already have *beep, why not *boop?

**Comment by brndd** [comment]
I'm pretty sure they already have a *boop, it just doesn't have an accompanying sound effect.

**Comment by Pathid** [comment]
Could we just take twobeep.ogg and lower the pitch?

**Comment by sonime** [comment]
Needs its own sound effect or I will not die happy.

**Comment by brndd** [comment]
it should be something like the sad boops R2D2 makes.
