### ISSUE TITLE
Asteroid Station kitchen shutters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19377]
(WEB REPORT BY: archinist REMOTE: 172.93.109.202:7777)
# Revision
600b7156ac5ce6035eae8f4c8e61115a003f4d59

# No button/controls kitchen shutters for the kitchen on Asteroid Station

# Go to kitchen on Asteroid Station, see shutters above tables, look for shutter button and see none

# I expected there to be a button for the shutters so I can open and close them if needed

# There was no button for the shutters, so they couldn't actually function as shutters (can't be opened or closed)

**Comment by ShiftyRail** [comment]
I too shout when I talk
