### ISSUE TITLE
Cyborg eyes are invisible.

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#19378]
May be related to #19246 

Overlays are getting generated just fime, but they don't appear to the living. Ghosting makes your ghost appear with your eyes, though.

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/addf5cf7026300b55a7c14bb14bc6bc45e19c139/code/modules/mob/living/silicon/robot/robot.dm#L971

Getting rid of the third argument here makes them appear so it's definitely some kind of plane/layer thing.
