### ISSUE TITLE
Heartbreaker toxin doesn't actually combine

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19371]
(WEB REPORT BY: lavoss REMOTE: 172.93.109.202:7777)
make mindbreaker

make dexalin

go to combine

nothing happens

:clap: :clap: :clap:

**Comment by SonixApache** [comment]
[heat]

**Comment by Kurfursten** [comment]
4 minutes later he made heartbreaker using the burner

👏

**Comment by Irradiation** [comment]
Read the wiki reeeeee

**Comment by DamianX** [comment]
shame
