### ISSUE TITLE
*aflap machine broke

### ISSUE THREAD

**Issue by beesil** [d3athrow/vgstation13#19383]
#### Description of issue
*aflap emote and *flap emote are not working for carbons _and_ silicons.

#### Difference between expected and actual behavior
*aflap or *flap, no feedback or output to chat. 

#### Steps to reproduce 
Login, type *aflap or *flap.

#### Length of time in which bug has been known to occur
Since emote datums, at least.

**Comment by DamianX** [comment]
closed by #19386
