### ISSUE TITLE
Mineral walls are borked

### ISSUE THREAD

**Issue by jknpj** [d3athrow/vgstation13#19380]
Seems like you can't tap girders with mineral sheets to make mineral walls because turf code is fucking retard and used the old sheettype strings to find the wall type. #17540 oversight.

https://github.com/vgstation-coders/vgstation13/blob/4a38ac91690dfcababaf1ffa0ef633458b366d9b/code/game/objects/structures/girders.dm#L247-L292

**Comment by Kurfursten** [comment]
Old wallcode is truly horrifying, I have recently read it myself

**Comment by jknpj** [comment]
disregard that, i'm blind IRL.
