### ISSUE TITLE
Engineering and atmospherics access issues

### ISSUE THREAD

**Issue by wild-billy** [d3athrow/vgstation13#1939]
There's quite a few of these.
The biggest and most important are related to the SM and TEG, which basically can't be setup, modified, and operated properly without having both engie and atmos access. 
The rub here is that these engines naturally span both the power and gas simulation systems, so it's pretty much impossible to stick them as purely in the engineering or atmos departments.

One solution is to unify them as the same job, with multiple flavor titles. That presents balance issues though, since a robust traitor with both accesses has several dozen different ways to fuck the station right at their fingertips.

Currently it's not a huge gameplay obstacle, since anyone who wants to do advanced work with either is usually either a MoMMI or the CE, but we need to get it worked out at some point. Mere mortals should be able to dick with advanced engines too.

**Comment by clusterfack** [comment]
Department access is shared now, this issue is no longer relevant in the current build

**Comment by ComicIronic** [comment]
Reopen if still an issue.
