### ISSUE TITLE
wrong pipe asteroid station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19396]
(WEB REPORT BY: riolenn REMOTE: 172.93.109.202:7777)
# Revision
96f159591515adc68368366e0e90f95f811d40c8

# Description
wrong pipe used at 135, 218, 1 on the waste line

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by justsmith** [comment]
one more wrong pipe type/missing 

Research Wing Hallway (323, 251, 1) on the waste network
