### ISSUE TITLE
Chat settings aren't preserved

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#19402]
Stuff that you set with the little gear, like font size, don't get preserved between sessions anymore. Pretty sure it has to do with 512.

Somewhere the data either isn't being saved properly
https://github.com/vgstation-coders/vgstation13/blob/fbb51865d8ffddfe96f4e50e349178bc24928b1b/goon/browserassets/js/browserOutput.js#L789-L794

or loaded properly.
https://github.com/vgstation-coders/vgstation13/blob/fbb51865d8ffddfe96f4e50e349178bc24928b1b/goon/browserassets/js/browserOutput.js#L507-L519

**Comment by DamianX** [comment]
To be clear, each time you reconnect, even in the same round, the settings get reset?
Those are saved as cookies, did you mess with the cookie settings for IE?

**Comment by Pathid** [comment]
Yes it's each time I reconnect. I'll try that.

**Comment by Pathid** [comment]
Doing this doesn't make any difference.

![internet zone](https://user-images.githubusercontent.com/31839805/44313616-706c6380-a3c0-11e8-9563-657fc39a3c8c.PNG)

**Comment by DamianX** [comment]
something something http://www.byond.com/forum/?post=2406876

**Comment by Exxion** [comment]
Only way to fix this is to shove it into player prefs instead of storing it locally
On BYOND's end it's working as intended. Being able to write cookies was apparently always a bug.
