### ISSUE TITLE
Empty machine frame in research unusable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19403]
(WEB REPORT BY: autisticmouse REMOTE: 172.93.109.202:7777)
# Revision
113190d7c1dbefbdbaeaaff89b2a859c68ad26b5

# Description

There's an empty machine frame by default in RD, but you can't add cables to it.

# Steps to Reproduce

# What you Expected

It to work

# What Actually Happened

**Comment by Pathid** [comment]
What. Map.

If I were to guess it's Roidstation though.

Edit: Yeah, Roidstation. It's a ``/obj/machinery/constructable_frame`` when it should be ``/obj/machinery/constructable_frame/machine_frame``.

**Comment by Kurfursten** [comment]
I'm guessing it's just not wrenched down and he kept trying to smoosh cables into it
