### ISSUE TITLE
Pipe layering is broken

### ISSUE THREAD

**Issue by brndd** [d3athrow/vgstation13#19409]
Something about pipe layering is causing seemingly properly layered, separate pipelines to combine into one network. I've ran into this problem twice while mapping Roidstation, and I have no idea what exactly is causing it.

I was doing a rework of the atmospherics of Roid, and made heavy use of layered pipes to do so. Something about this setup is causing the two gray pipes at the top, and the four gray pipes at the bottom to merge together:

![1534738977829](https://user-images.githubusercontent.com/5822375/44320521-2aa8ad00-a44b-11e8-8a70-a16f2698ec8d.png)

I presume it has something to do with layer adapters, because here the two gray pipes and the blue pipe are forming a single network while having relatively few overlapping tiles, with the tile with the blue layer adapter being the most "complicated" overlap:

![1534739258089](https://user-images.githubusercontent.com/5822375/44320552-5cba0f00-a44b-11e8-92ad-cffd101ed23f.png)

Given that this setup triggers the bug, it likely has something to do with either layer adapters or manifolds. I'm leaning towards layer adapters, because the manifolds on the blue pipe on the north side of the room do not trigger the bug.

To view the setup that triggers the bug, pull this branch: https://github.com/brndd/vgstation13/tree/roidmos

**Comment by brndd** [comment]
Ok, I'm almost certain it's layer adapters, because when I remove the layer adapter in the second picture, the pipes don't get mixed together:
![1534741367598](https://user-images.githubusercontent.com/5822375/44321237-7e1cfa00-a44f-11e8-8aa4-95023e9a0c84.png)

**Comment by Inorien** [comment]
If I had to guess I'd say its layer adapters on consecutive tiles 
While you're at it can you minimize the amount of dark blue piping in the atmos floor area? It's confusing af when trying to work on distro if there's the weird connector darkblue pipe sharing the floorspace

**Comment by WhiteHusky** [comment]
I think this issue's been around for a long while, perhaps a year or so. I've had issues with multiple pipes over a layer adapter merging themselves together when they (visually) shouldn't.

**Comment by Exxion** [comment]
https://github.com/vgstation-coders/vgstation13/blob/6398dfca5664c1afa2969cc7ce2260f4984ddfee/code/ATMOSPHERICS/pipes.dm#L1282
I haven't made sure yet, but I'm pretty sure the issue here is that it only checks its *own* direction, not the direction of the pipe it's trying to connect to.
