### ISSUE TITLE
Mass pressure jump on whole station, murders everyone

### ISSUE THREAD

**Issue by golfer45** [d3athrow/vgstation13#1940]
Massive 2.8 billion kPA pressure spike everywhere on the station.
Things to note, atmos had no power. Nothing had been fucked with.
![fix pls](https://cloud.githubusercontent.com/assets/4716493/5146452/ad0acb5a-717a-11e4-8fbb-8fdd968754a1.PNG)

**Comment by clusterfack** [comment]
Someone should have seen this again by now if it hadn't been fixed.
