### ISSUE TITLE
Feature Request: Finish Stomach Code

### ISSUE THREAD

**Issue by Tokanova** [d3athrow/vgstation13#19412]
As it stands, Stomachs ( #19121 ) aren't complete. The stomach organ only is affected by thinks the player mob drinks (or is forced to drink), meaning things they eat with chemicals in them, or pills they swallow, do not go to the stomach.

To finish Stomachs, the following additions and changes will need to be made.

1. Have food and pills go into stomach. (Duh.)
2. Have only things ingested affect the stomach, so Cryo does not kill your stomach.

With these changes, Stomachs would become a more complete organ. Medbay and players themselves would have to take into consideration the health of their stomach when eating and being treated. I of course have other ideas for it, but these are the ones I think deserve focus right now.

**Comment by Irradiation** [comment]
Also make it so having the Sober gene makes you immune to stomach damage from ethanol. Honk.

**Comment by kilozombie** [comment]
Stomachs don't take damage from alcohol except on a very very long scale, so the original PR really makes no sense. It's not even alcohol poisoning-- it's "drank a bottle of beer? your stomach takes 10 damage" like who the fuck thought that was a good idea

**Comment by Irradiation** [comment]
@kilozombie #19413 happened, so that's gone for now.

**Comment by strawberrytan** [comment]
What of things like blood and creatine pills?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Close this
