### ISSUE TITLE
Vomit with welder fluid in it doesn't catch fire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19423]
(WEB REPORT BY: izayachan REMOTE: 172.93.109.202:7777)
# Revision
39338dbf6b428ea93851ca41e421fc48f146afb6

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by IzayaChan** [comment]
ignore this one, it was a accidental double post
