### ISSUE TITLE
Roidstation "Perfect Man" exhibit is weird

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#19420]
https://github.com/vgstation-coders/vgstation13/blob/39338dbf6b428ea93851ca41e421fc48f146afb6/maps/RoidStation.dmm#L9324
I know that link won't work because GitHub won't display the file, but here it is:
```
"dxp" = (/turf/simulated/floor{desc = "\"This is a plaque in honour of our comrades on the G4407 Stations. Hopefully TG4407 model can live up to your fame and fortune.\" Scratched in beneath that is a crude image of a meteor and a spaceman. The spaceman is laughing. The meteor is exploding."; dir = 4; icon_state = "plaque"; name = "Comemmorative Plaque"; nitrogen = 30; oxygen = 70; temperature = 80},/turf/simulated/floor{tag = "icon-siding6"; icon_state = "siding6"},/obj/structure/showcase{desc = "A stand with a model of the perfect Nanotrasen Employee bolted to it. Signs indicate it is robustly genetically engineered, as well as being ruthlessly loyal."; name = "'Perfect Man' employee exhibit"},/turf/simulated/floor{tag = "icon-siding9"; icon_state = "siding9"},/area/hallway/secondary/construction{name = "\improper Research and Mining Hallway"})
```

1. "Comemmorative"
2. `nitrogen = 30; oxygen = 70; temperature = 80`
3. There are somehow three separate turfs on this tile
4. All of them have their `tag` var set for some reason, though this one might be intentional
5. This one is actually about the tiles surrounding this tile, not the tile itself: They're transparent tiles that aren't children of glass floors, so they look like ass if you have parallax off, don't update parallax if you have it on, and turn into regular plating if crowbarred

**Comment by Reviire** [comment]
Glass floors look like ass regardless, if you have parallax off.

**Comment by Exxion** [comment]
OK I hadn't bothered to check that, but it shouldn't be hard to fix

**Comment by DamianX** [comment]
- This is still a thing.
- There's also another tile with that description, but not three turfs:
`(/turf/simulated/floor{desc = "\"This is a plaque in honour of our comrades on the G4407 Stations. Hopefully TG4407 model can live up to your fame and fortune.\" Scratched in beneath that is a crude image of a meteor and a spaceman. The spaceman is laughing. The meteor is exploding."; dir = 4; icon_state = "plaque"; name = "Comemmorative Plaque"; nitrogen = 30; oxygen = 70; temperature = 80},/area/bridge)`
- "Comemmorative" is not how you spell it
- When you have more than one turf on one tile, the last turf gets the images of the previous turfs added as underlays. This is a BYOND feature, I guess.
- What the fuck is going on here?

**Comment by Kharkov72** [comment]
this is a similar issue as #24018 as in it's the thing that SHOULD just be an overlay being a fucking FLOOR REEEEEEEEEEEE
