### ISSUE TITLE
Vomit with welder fluid doesn't set fire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19424]
(WEB REPORT BY: izayachan REMOTE: 172.93.109.202:7777)
# Revision
39338dbf6b428ea93851ca41e421fc48f146afb6

# Description
Vomit with welder fluid in its contents won't catch fire
# Steps to Reproduce
Drink a bunch of welder fluid and vomit. Try to light it.
# What you Expected
For the vomit to start a small fire
# What Actually Happened
The vomit did nothing
Sorry for the double-post, I pressed enter the first time by accident.

**Comment by jknpj** [comment]
That's not how vomit works.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
If only there were a simpler way to spread welding fuel on the floor

**Comment by ProfanedBane** [comment]
Is there a reason vomiting doesn't spill chems onto the floor?

**Comment by jknpj** [comment]
wait for #18729

**Comment by Killette2** [comment]
This + immolation power could make for real shenanigans
