### ISSUE TITLE
Plasmaman Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19425]
(WEB REPORT BY: morena REMOTE: 172.93.109.202:7777)
# Revision
c4447123fd263bba9f1c4d0a887dec8ca63d631b

# Description
Plasmamen who have been beheaded still have a sprite with their head attached
# Steps to Reproduce
Behead a plasmaman
# What you Expected
no head
# What Actually Happened
head flies off but head stays on body sprite

**Comment by strawberrytan** [comment]
This also applies to ghouls for probably the same reason
