### ISSUE TITLE
Examining as a borer from inside a host

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#19428]
After #19297 you cannot shift-click to examine things from inside a host, that's unless you use Cancel Camera View first, which brings back the old jerky viewport. This is on top of previously not being able to right-click examine things either, which might very well apply to any mob inside an object.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Huh. Wait a minute, this reminds me of a certain mech bug...

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah it turns out that reset_view() is what causes #4829
and mechs broke that at some point
and I just un-broke it from borers which broke THIS now
So the question is which one would be less broken
