### ISSUE TITLE
This is enough Angies

### ISSUE THREAD

**Issue by Pathid** [d3athrow/vgstation13#19435]
![ultrameens tomb sierra 2018-08-21 212524](https://user-images.githubusercontent.com/31839805/44448319-c6e3c880-a59f-11e8-9dfb-b1940505c7cd.png)

This wasn't a bus. Is this what's supposed to happen? This was on Boxstation if that's important. A miner also reported lag while fighting one, not sure if related.

**Comment by ProfanedBane** [comment]
This also happened a few days back on Boxstation. There was some kinda vault with unbreakable asteroid walls with a fuckton of these boys spacing inside.

**Comment by MadmanMartian** [comment]
what the fuck

**Comment by SonixApache** [comment]
the best part is when one slams into another while trying to get you and they all begin fighting eachother
