### ISSUE TITLE
Subjugate on borgs

### ISSUE THREAD

**Issue by LisandraBrave** [d3athrow/vgstation13#1945]
Subjugate spell works on borgs, and never wears off. The borg stumbles around for the rest of it's life.

reproduction:
1: Be wizman
2: Make a borg
3: Cast subjugate on said borg
4: Watch it stumble forever

**Comment by clusterfack** [comment]
Comic's spell code rework fixed this with 

>compatible_mobs = list(/mob/living/carbon/human, /mob/living/carbon/monkey)

**Comment by ComicIronic** [comment]
#2001, reopen if still an issue.
