### ISSUE TITLE
Bagelstation derelict pod armor doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19467]
(WEB REPORT BY: pomf123 REMOTE: 172.93.109.202:7777)
# Revision
84fb247c2fce0fce42a88150d51df6f11c9a77e6

# Description
The pod armor is the legacy version and should be updooted to use the new subtypes.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kammerjunk** [comment]
Related to #19468

**Comment by Kurfursten** [comment]
@Exxion This has nothing to do with bagel (and it's a dupe, you can close it)
