### ISSUE TITLE
(roid) Double telesci = double trouble

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19460]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
5acf835cc078834a0b54743c8713a1a3b8d33fa1

# Description

Two telesciences means two calling points but they only get sent to one, the one in Science.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Can be fixed by removing it from Science
