### ISSUE TITLE
Roidstation detective office problems

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#19461]
A couple of things I noticed about the detective office that are missing or extra

- it has two medical records computers, both the laptop and the one by the morgue tray (personally not a fan of the whole morgue tray being there but that's just me)
- it has no suitcase to hold stuff
- it has no camera or film 
- it has no intercomm

Also a bookcase would come in handy to store the forensics and space law books so you can pretend you are well read

**Comment by SonixApache** [comment]
Morgue tray is good for autopsies!

**Comment by Blithering** [comment]
Except there's no autopsy tools or an operating table, so you gotta go to the morgue anyway

**Comment by GeneralVeers25** [comment]
Given that there's an operating table, morgue tray, and autopsy tools in Brig medbay, I'm considering taking the morgue tray out and instead giving the Detective his own door into the Security Lobby. I'd reorient the Office to make it a bit more like a real 'Private Eye' where you can (theoretically)  go in and hire him.

Thoughts?

**Comment by Blithering** [comment]
Sounds good to me, as a detective I never have bodies for examination in my office anyway, they usually end up taken to medbay or kept in the brig morgue.
