### ISSUE TITLE
Martians can't equip hats on their own?

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#19473]
On my own test server at least, I can't manage to control a martian/scootaloo/whatever without being unable to equip hats and helmets, even ones designed specifically for the species. It will show itself going into the hat slot, but it won't actually be there, it remains in one of your hands, and you can fix the desync by dropping it.
On the flip-side, if somebody _else_ equips something on a martian's head, it will actually be there. But for the martian, it seems to show up inexplicably in one of their other hand slots.
I haven't done anything that would realistically break this on my test server but I'd appreciate another independent test of this, it's kind of annoying

**Comment by Pathid** [comment]
Yeah their inventory code looks like it's not unequipping it from the tentacle.
