### ISSUE TITLE
Holomen cannot interact with Inflatable Shelters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19482]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
aad64615f32b5e034a1f0cdad451c5349b7472fd

# Description

Holomen are unable to enter or insert peopel into inflatable shelters
# Steps to Reproduce

Aquire shelter, aquire person, aquire holoman, try inserting person into shelter as holoman
# What you Expected

Memes
# What Actually Happened

Dissapointment

**Comment by SGuivenne** [comment]
I was wrong, they can in fact enter shelters, they just cant put people in them.

**Comment by Kurfursten** [comment]
Are you 100% sure they can't? Because putting someone else into the shelter does not get the progress bar (the person entering is the one for which the progress bar shows). It's also twice as long as climbing in yourself, 2 seconds rather than 1

**Comment by Pathid** [comment]
Seems to work on my end. Issues I can see:
1. They don't get the "grab" icon in their HUD.
2. The grab doesn't break automatically so you're stuck in place after you put them in until you drop the invisible grab.

**Comment by Pathid** [comment]
Oh and climbing in the shelter causes a runtime:

```
[23:43:17] Runtime in inflatable.dm,381: Cannot execute null.has reagent().
  proc name: enter shelter (/obj/structure/inflatable/shelter/proc/enter_shelter)
  usr: The hologram (642) (panthid) (/mob/living/simple_animal/hologram/advanced)
  usr.loc: The e5 (104, 18, 1) (/turf/simulated/floor/holofloor)
  src: the inflatable shelter (/obj/structure/inflatable/shelter)
  src.loc: the e5 (104,18,1) (/turf/simulated/floor/holofloor)
  call stack:
  the inflatable shelter (/obj/structure/inflatable/shelter): enter shelter(the hologram (642) (/mob/living/simple_animal/hologram/advanced))
  the inflatable shelter (/obj/structure/inflatable/shelter): attack hand(the hologram (642) (/mob/living/simple_animal/hologram/advanced))
  the hologram (642) (/mob/living/simple_animal/hologram/advanced): UnarmedAttack(the inflatable shelter (/obj/structure/inflatable/shelter), 1, "icon-x=13;icon-y=11;left=1;scr...")
  the hologram (642) (/mob/living/simple_animal/hologram/advanced): ClickOn(the inflatable shelter (/obj/structure/inflatable/shelter), "icon-x=13;icon-y=11;left=1;scr...")
  the inflatable shelter (/obj/structure/inflatable/shelter): Click(the e5 (104,18,1) (/turf/simulated/floor/holofloor), "mapwindow.map", "icon-x=13;icon-y=11;left=1;scr...")
```

Clicking the shelter a second time produces ``You begin to climb into the shelter.`` and makes the runtime happen again.

**Comment by Kurfursten** [comment]
Ah, of course. Holopeople have no reagents. Could use a sanity check.

But in all honesty should holopeople even be allowed in??

**Comment by SGuivenne** [comment]
it turns out you can enter as a holoman by left clicking but you cannot put others in.
