### ISSUE TITLE
Holomen do not appear in inflatable shelters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19484]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
aad64615f32b5e034a1f0cdad451c5349b7472fd

# Description

Holomen do not appear as a sprite in shelters
# Steps to Reproduce

Be holoman, climb into shelter
# What you Expected

Stupidity
# What Actually Happened

An empty shelter

**Comment by Kurfursten** [comment]
How would the light of the projector reach inside? 🤔 

Realistically this is probably because holomen do not have an appearance to copy

**Comment by Exxion** [comment]
If you mean the `appearance` var, all atoms have it
