### ISSUE TITLE
You cannot lazarus inject slimes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19496]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
6c7a40a8e450063233787839861da23a5f7015ad

# Description

Slimes cannot be lazarus injected as "The lazarus injector is only effective on lesser beings."

It doesn't get much lesser of a being than a fucking homogenius mass of slime
# Steps to Reproduce

Acquire dead slime, attempt to inject with lazarus injector
# What you Expected

An unstoppable Slime army
# What Actually Happened

Got cuckolded

**Comment by Kurfursten** [comment]
Slimes can telepathically chirp. That makes them more advanced than humans.

**Comment by Killette2** [comment]
Slimes are somewhat a subspecies. It's just like how you can't lazarus a monkey. They're somehow magically an upgrade to simple mobs

**Comment by jknpj** [comment]
They're both carbon. Same to xenos/martians.

**Comment by DamianX** [comment]
I'm going to call this not a bug but if anyone feels differently they're welcome to change it
