### ISSUE TITLE
Dehumanize yourself and face to supermatter

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#19497]
#### Description of issue

Supermatter shard gives weird text when observing someone getting gibbed.  "Deangelo Metzer slams into Supermatter Shard inducing a resonance... its body starts to glow and catch flame before flashing into ash." as an example.  Note the Its instead of a gendering term.  

#### Difference between expected and actual behavior

Terminology is inconsistent with general actions

#### Steps to reproduce 

Observe someone getting gibbed

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
The supermatter doesn't assume genders

**Comment by Exxion** [comment]
I assume it's because the `\he` macro goes by the last embedded object in the string, which in this case is the shard, not the person
