### ISSUE TITLE
Box station bridge mapping bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19500]
(WEB REPORT BY: gringonius REMOTE: 172.93.109.202:7777)
# Revision
6c7a40a8e450063233787839861da23a5f7015ad

# Description
There's a strange glitch going on with box's bridge and it's incredibly ugly, dark and clashes with the hallways around it. It's almost as if a clown with a tilepainter broke into it at round start.

**Comment by MadmanMartian** [comment]
![pic](https://cdn.discordapp.com/attachments/245856152276041728/483824637495476226/X8g.png)

I have been informed that this is a joke issue.

**Comment by Gringonius** [comment]
Looks serious enough to me. What a horrible-looking, bloated bridge.
