### ISSUE TITLE
Objectives in notes get a little fucky (datums)

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#19514]
Got autotraitored upon arriving and then converted to an ayy later, didn't check notes before being converted to an ayy and unsure if that did anything

Notes listed my objectives twice in two different categories.

![image](https://user-images.githubusercontent.com/6062247/44817876-c1880e80-ab9b-11e8-9f04-3553e08d7bc1.png)

**Comment by MadmanMartian** [comment]
fixed by #19669
