### ISSUE TITLE
Datums: Nuke op with "summon Nar-Sie" objective

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#19513]
#### Description of issue
Was made a nuke op at the start of an autotraitor round as a test dummy and had the objective to summon Nar-Sie. A traitor also had that objective IIRC

#### Difference between expected and actual behavior
I don't know if being a nuclear operative during autotator is expected, but being expected to summon grand daddy narnar probably isn't

#### Steps to reproduce 
Idk sign up for traitor and become traitor I guess

#### Server revision
Probably f8e0ebe265743efddcd4e68738bf798052a5ddf1

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by jknpj** [comment]
I did that
