### ISSUE TITLE
pAIPS Fucking Sucks :^)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19520]
(WEB REPORT BY: jazzstringz REMOTE: 172.93.109.202:7777)
# Revision
8e764adaa22206eb2370bf68af91ee49c400c880

# Description: The pAIPS (pAI Positioning System) doesn't display any coordinate data, with all the fields being undefined.

# Steps to Reproduce
>Become pAI
>Download pAIPS
>Try to Enter a Tag (it won't work)
>Try to Turn Auto-Refresh On (it won't work)
>Look at the lack of GPS Coordinate Data.
# What you Expected
Well, presumably, I should be able to enter a name for the pAIPS and it should be able to auto-refresh, not to mention display coordinate data.
# What Actually Happened
I tried to enter a name in the tag field, and while closing and reopening the window did change the name, the field still considered itself undefined. I clicked on the Auto-Refresh button to turn it on, but it didn't turn on. I looked at the list of coordinates that appear on GPSes, but it was all undefined.

**Comment by strawberrytan** [comment]
I think this was working a while ago, maybe this is in some way linked to the change that makes GPSes spawn off by default

**Comment by RealestEstate** [comment]
yeah it was probably my PR
