### ISSUE TITLE
Combat drones nuzzle you at point blank range

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19536]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
4a8bd3e7ae934b0fab2c1454c643ae426a9f8b0d

# Description

Combat drones, instead of lasering you, nuzzle you at touch range
# Steps to Reproduce

# What you Expected

Death
# What Actually Happened

Nuzzles

**Comment by Hoshi-chan** [comment]
It's a feature.
