### ISSUE TITLE
SPS are gunked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19546]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
34e932cb105e1f5d928f680e708f5865367e2ce3

They don't ping on stripping anymore.

**Comment by ShiftyRail** [comment]
More specifically, it's when you strip someone's jumpsuit and the SPS is in, say, pocket, it won't beep.
The message on death is also no longer visible from viewers of the SPS.

**Comment by ShiftyRail** [comment]
I can confirm in game that it does not beep.
