### ISSUE TITLE
(ROLE DATUMS) More than one roundstart wizard can spawn.

### ISSUE THREAD

**Issue by ProfanedBane** [d3athrow/vgstation13#19576]
Just noting this down incase we forget.
There's no role limit for wizmen so you can end up with 2+ spawning in wizard den, in the same tile.

**Comment by DeityLink** [comment]
Doesn't that also happen with the current antag code?

**Comment by ProfanedBane** [comment]
Unless I'm reading the code wrong no it doesn't.

**Comment by Kammerjunk** [comment]
For a period, Wizard was a 20+ mode that spawned one wiz per 10 players, but this was reverted with #17218 and #17396

**Comment by DamianX** [comment]
Feature?

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/47604482-ce3dad00-d9fa-11e8-8317-b752a94ffa9e.png)
no

**Comment by DamianX** [comment]
`required_candidates` seems to be the minimum amount of antags that need to be created, not the upper limit. I'm confused by your response.

**Comment by DeityLink** [comment]
Well actually it's kind of both. But unless specified otherwise a ruleset wouldn't ever pick more antags than required_candidates.

![image](https://user-images.githubusercontent.com/7573912/47604740-0e525f00-d9fe-11e8-9669-796b95fdca76.png)

And the roundstart wizard ruleset only creates one wizard.

**Comment by DamianX** [comment]
So...are two wizard rulesets firing here?

**Comment by DeityLink** [comment]
Shouldn't possibly happen unless an admin forced them before roundstart. Why don't we have logs for the concerned round?

**Comment by DeityLink** [comment]
Most likely scenario is that two wiz rulesets were forced.
