### ISSUE TITLE
custom vending machines can't be toggled anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19577]
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
using your ID on one just gives you a gay error

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
![dreamseeker_2018-09-03_22-39-01](https://user-images.githubusercontent.com/40967382/45005497-2e4f3e80-afca-11e8-8820-cdeabbfd261f.png)
https://github.com/vgstation-coders/vgstation13/blame/Bleeding-Edge/code/game/machinery/vending.dm#L495
@WhiteHusky
