### ISSUE TITLE
Holomen Seem to Get Nullspaced on Death

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#19588]
Kept happening when I would spear myself to death testing on local (Bleeding Edge). Investigate on live. It would give a message about my body "shifting and contorting", too. May have to do with holders being used for advanced holograms??

@Shadowmech88

**Comment by Shadowmech88** [comment]
>It would give a message about my body "shifting and contorting", too.

Possibly this? https://github.com/vgstation-coders/vgstation13/blob/52230c286a37cd9a51051fd04981132756560b9d/code/modules/mob/death.dm#L55
Were you transmogrified into a holoperson?

**Comment by Kurfursten** [comment]
That does seem to be the message it would send before death.

I was just a normal holoperson from interacting with the console - no mask involved (I do not know if the console uses transmogrification). I was an adminghost but I was not using the admin holoman option.

**Comment by ShiftyRail** [comment]
@Shadowmech88 Was not able to reproduce this on local, either with normal advanced holograms, or with admin ones
I did notice this 
```
[19:12:23] Runtime in delays.dm,50: Cannot execute null.delayNext().
  proc name: delayNextAttack (/mob/proc/delayNextAttack)
  usr: Trinity () (/mob/living/simple_animal/hologram/advanced)
  usr.loc: (nullspace)
  src: Trinity (/mob/living/simple_animal/hologram/advanced)
  src.loc: null
  call stack:
  Trinity (/mob/living/simple_animal/hologram/advanced): delayNextAttack(10, 0)
  the energy axe (/obj/item/weapon/melee/energy/axe): on attack(Trinity (/mob/living/simple_animal/hologram/advanced), Trinity (/mob/living/simple_animal/hologram/advanced))
  the energy axe (/obj/item/weapon/melee/energy/axe): handle attack(the energy axe (/obj/item/weapon/melee/energy/axe), Trinity (/mob/living/simple_animal/hologram/advanced), Trinity (/mob/living/simple_animal/hologram/advanced), null, null)
```

**Comment by Kurfursten** [comment]
if you say it's not happenin we'll close it
