### ISSUE TITLE
Vampire abilities are shitcode

### ISSUE THREAD

**Issue by vampirebat74** [d3athrow/vgstation13#19605]
#### Description of issue
Vampire code is ancient. Vampire abilities with cooldowns shift the locations of the other skills, most notably hypnotize. This negatively affects the user severely and may be one of the many reasons why vampstended was so common.

#### Difference between expected and actual behavior
What it should do: have all of the abilities in consistent locations
What is does: move all of the ability names whenever you cast one with a cooldown

#### Steps to reproduce 
>Start round, be vamp
>try to quickly glare + hypnotize the HOS so you can thrall him after all the succs
>glare and shadow step, losing your cover and fucking yourself over

#### Length of time in which bug has been known to occur
Probably since it was written

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x ] Issue could be reproduced at least once
- [ x] Issue could be reproduced by different players
- [ x] Issue could be reproduced in multiple rounds
- [ x] Issue happened in a recent (less than 7 days ago) round
- [ x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by MadmanMartian** [comment]
This is fixed in datums. They're moved to spells.
