### ISSUE TITLE
Cargo Console is Environmentally Insensitive

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19626]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
406ae75049dcc4ca95dcf730513dadc4b6fbbb57

# Description

Ordering a shipment of 0 crates spawns a blank sheet of paper from the console. 
# Steps to Reproduce

Order any crate, request 0 of it when asked how many
# What you Expected

Nothing
# What Actually Happened

oh god paper everywhere

**Comment by Kurfursten** [comment]
Could not reproduce, and in fact the code clamps minimum value to 1. Probably unrelated bug.

@Exxion probably safe to close in favor of some better report in the future if it comes up again
