### ISSUE TITLE
Chef RAMSey reacting to component ingredients

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19627]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
406ae75049dcc4ca95dcf730513dadc4b6fbbb57

# Description

Chef RAMSey went after mimic meat, as far as I'm aware he isnt supposed to go after raw ingredients.
# Steps to Reproduce

Acquire mimic meat

Get cucked by the fucking chef bot
# What you Expected

Outrage from other things
# What Actually Happened

Outrage from that. ITS SUPPOSED TO BE RAW ITS A FUCKING RAW SLAB OF MEAT YOU FUCK.

**Comment by Kurfursten** [comment]
RAMsay will go after anything (including raw ingredients) with reagents on his blacklist, including things like spider legs (toxin)

**Comment by jknpj** [comment]
IT'S FUCKING RAAAAAAAAAAAAAAAW

**Comment by DamianX** [comment]
feature?
