### ISSUE TITLE
Observing someone as ghost and then Haunting them gets fuckey

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19638]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
fa3b0fdcd569387784672604e389a540cbe17c01

# Description

If you observe someone as a ghost and then haunt them afterwards, youre camera will center on them as your ghost flies around aimlessly without vision on them.
# Steps to Reproduce
ghost.  Observe someone.  Haunt them because you cant stop observing.  Fuck your camera up fam.

**Comment by Exxion** [comment]
Observe someone how?

**Comment by SGuivenne** [comment]
@Exxion Via the observe verb.

**Comment by Exxion** [comment]
I didn't know about that verb honestly
But this doesn't appear to be specific to using observe then haunting
This is just always how that verb works

**Comment by Exxion** [comment]
And to stop observing, observe yourself or use the cancel camera view verb.
Not intuitive, but it works.
