### ISSUE TITLE
Plasmamen drink 2.25 from containers they drink instead of 5u.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#19640]
#### Description of issue
~~you used to drink 5 units when you drank something, I don't recall anything about this being changed on purpose so i'm reporting it.~~

 When plasmamen drink from a container they drink 2.25 instead of 5u like humans

#### Difference between expected and actual behavior
taking mansized drinks instead of manlet sized drinks from a bottle

#### Steps to reproduce 
sip bottle, inspect bottle.

#### Specific information for locating
~~I was a plasmaman if that has anything to do with it.~~
Might be related to them not having a stomach.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
*sips reagents* yep... I remember when sips were 5u... sure don't sip like they used to

**Comment by Exxion** [comment]
It was never specifically 5u
It was 10% of the total contents, or all of the remainder if below a certain threshold
At least for glasses and bottles

**Comment by Dacendeth** [comment]
Uh in my experience whatever you sip be it a coffee cup, a liquor bottle, or a 300u beaker you always drink 5u. But regardless of that I've done some further testing and this is indeed a plasmeme related bug, humans drink 5u and plasmemes only 2.25.

**Comment by Exxion** [comment]
I mean I shouldn't have said it *never* was because I have no idea about the past like half year, but it definitely used to be the case that when drinking from a glass, the first sip would be 10u, second 8u, so on
(I said 10% above but actually I think it was 20%)

**Comment by Dacendeth** [comment]
Yeah I can believe that since it still works like that when you feed someone from a bottle/glass

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This should be fixed

**Comment by Exxion** [comment]
Was it? Is that confirmed?

**Comment by Dacendeth** [comment]
yeah, fixed by stomach removal.
