### ISSUE TITLE
Typo in the holodeck disclaimer.

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#1964]
Someone misspelled "Bruises" as "Brusies".
![738e34231d](https://cloud.githubusercontent.com/assets/3892856/5158707/fb0be6e6-734f-11e4-9e1e-a1b7f0c7ba05.png)

**Comment by clusterfack** [comment]
I'm not sure this is still relevant, cant find this in the code.

**Comment by BestName** [comment]
If it was in the code I would have fixed it myself but as far as I know the paper is part of the map and I don't want to touch the map.
