### ISSUE TITLE
Diamond Coins register as an Iron Composite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19649]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
62c2da231743709d56deff02086f1c47f79c1dec

# Description

Diamond coin artifacts register as being metallic despite the fact they should be carbon based as they are fucking diamond.

**Comment by Jellyveggie** [comment]
Don't you know? Diamond is the hardest metal known to man

**Comment by jknpj** [comment]
Diamond coins are just a drop from the 'random coin' find
