### ISSUE TITLE
Vampires don't burn in chapel

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#19644]
While testing one-click-antag, I chilled in the chapel as a vampire (role), and was unaffected by holy tiles.

**Comment by gbasood** [comment]
Were you already in the chapel when you got button'd?

**Comment by SGuivenne** [comment]
I burned to death as a vampire last night after being dragged there.

**Comment by MadmanMartian** [comment]
@gbasood I even walked in and out after realizing

@SGuivenne that'd be on bleeding edge, this is a role datums branch bug
