### ISSUE TITLE
That new glow on lightswitches is ugly with user constructed switches

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#19641]
#### Description of issue
![image](https://user-images.githubusercontent.com/26881007/45261078-dc8e2600-b3c6-11e8-9c6a-4c0e79891eb5.png)
all 4 of these I placed myself in a round, 3 of them look wrong, tested placing in different locations and same results.

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Huh, the dir doesn't work for constructed ones
