### ISSUE TITLE
Bagel is literally too big

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#19652]
you waste a fuckload of time navigating around it, it's annoying as shit and power goes out sooner than normal stations if no mommi's/enginners set engines up
also in lowpop the station feel like a absolute graveyard

here's some proposed changes
-squash it a little
-prevent it from being voted on if there's not enough peoples

**Comment by Exxion** [comment]
Squashing it isn't exactly easy, but the other suggestion is
We already have a system that excludes maps based on population
We'd just have to increase Bagel's minimum

**Comment by Kurfursten** [comment]
I said more or less the same thing elsewhere in the bagel feedback post but "squashing it" is something extremely effort intensive. It would be like starting over from scratch. Realistically, all wires and pipes would need to be remapped and likely most of the rooms. The entire top half of the station is nearly empty so spreading out rooms more evenly would mean the new rooms need to face opposite directions as they get moved south to north, etc. Cpt Wad hasn't weighed in on any of the discussions, but it would be a massive project and he hasn't even fixed the minor issues like the ones recently repaired by other people (engineering grid, telecoms network, brig atmos, etc)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
So what you're saying is just pull the plug on it

**Comment by Kurfursten** [comment]
We've got a lot more map variety with Roid now and with Deff being much improved so I'd be less sad to see it go.

If Wad wants to try to make sweeping overhauls I'd be happy to be there for him with advice on the process and ask for more time, but if he doesn't speak up...

**Comment by Reviire** [comment]
Delete bagel. It has far too many points you need to turn at, and it's just too large. It takes years to navigate to the other side. I'm fairly sure ye olde donut was far easier to get around.

**Comment by CptWad** [comment]
Honestly id be fine with it being highpop as well
like 25+ as its fairly acceptable at highpop when the departments are flushed out.
but as the guy that mapped it in the first place the issue is that the OG donut was large and bagel is larger to accommodate the 15 or so new rooms since 4407 
So squashing it isn't an option (realistically) but increased popcap is necessary.
