### ISSUE TITLE
Anomolous anomalies are Anomalizing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19650]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
62c2da231743709d56deff02086f1c47f79c1dec

# Description

Xenoarcheology appears to have a rare and possibly one time bug where I pulled a depth of 0 clearance of 0, and an unknown composition, despite the fact that I had already dug to 56 cm of the rock.
# Steps to Reproduce

Do xenoarcheology
# What you Expected

Weird shit that wasnt this
# What Actually Happened

This

**Comment by SGuivenne** [comment]
This got weirder after testing too.  I did NOT get the message that I fucked up and destroyed an artifact when I tore down the wall with a pickaxe, and the entry wouldn't let me delete it individually, making me instead clear all entries.

**Comment by jknpj** [comment]
0 depth means a large artifact, it is in the fucking wiki

![image](https://user-images.githubusercontent.com/17928298/45287426-a3d17800-b4be-11e8-8943-c67fc9b2b841.png)
