### ISSUE TITLE
Access issues using borg MMI in human.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19665]
(WEB REPORT BY: fritzlhimmlerina REMOTE: 172.93.109.202:7777)
# Revision
aaeed4a463b4865752526e95feb1dab2501d9ec4

# Description
Was a borg, got destroyed, MMI removed and put into a monkeyman to become human. After this weird issues with access and identification for certain machines. I could enter certain areas I had no access to (science, security, cargo) and security equipment did not recognize my lack of ID (beepsky, turrets etc. would treat me as a properly ID'd person despite me having no ID and them being set to shoot non-ID people.

# Steps to Reproduce
Take MMI from destroyed borg and place in a monkeyman. Not sure if there are other steps required, have not had the chance to reproduce this personally.

# What you Expected
On "becoming human" a loss of any access, as if I had become a naked human.
# What Actually Happened
Remnants of borg access and identification seemed to remain active after "humanizing".

**Comment by Kurfursten** [comment]
@jknpj @Exxion This is yet another false report due to egalitarian station mode
