### ISSUE TITLE
Can't use cult tome while buckled to a chair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19678]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
006ce38c3d023872c1c9594087ce8348b814184e

# Description
Can't use a tome when buckled

# Steps to Reproduce
BUCKLE UP, TRY DRAW RUNE

# What you Expected
Menu to show up

# What Actually Happened
Nuffin

**Comment by Exxion** [comment]
This is pretty much definitely not a bug
Not to say it can't be changed of course

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Thanks now I know my target is buckled to a chair

**Comment by SonixApache** [comment]
If you can read books while buckled, surely you can use books while buckled.

**Comment by Kurfursten** [comment]
Reading a book, sure, but drawing intricate blood runes on the floor while buckled to a chair?

**Comment by DeityLink** [comment]
Not an issue in cult 3.0 anymore. Whether that makes sense to you or not.
