### ISSUE TITLE
Emitters don't accept signals from access buttons

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#19684]
#### Description of issue
Emitters don't accept signals from access buttons. 
I need to do more testing on where it breaks, but that's what it looks like.

#### Difference between expected and actual behavior
press button set to toggle emitters, emitters toggle
vs
press button, jack shit happens
#### Steps to reproduce 
Set up an emitter.
Make sure it's welded and powered.
With a multitool, set the frequency to 143.9, set the tag to LASER.
Set up an access button in vision range of the emitter.
With a multitool, set the frequency to 143.9, set the tag to LASER.
Set the command to `on`, `off`, or `toggle`

Press button, recieve nothing.
For counter-testing, you can use an AAC to send a signal to the emitters that *does* work.

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/3828157f4158fb1ac917b64b8135bfb09631bcb7/code/modules/power/singularity/emitter.dm#L98
https://github.com/vgstation-coders/vgstation13/blob/3828157f4158fb1ac917b64b8135bfb09631bcb7/code/game/machinery/airlock_control.dm#L318

#### Length of time in which bug has been known to occur
A long time. I've tried this a few times now. Probably more than a year?

#### Server revision
80f35b7d06c1dab7bb9ff18777c95874b968addd 

#### Issue bingo
- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this

**Comment by SonixApache** [comment]
Okay, it's the filters.
Access buttons work on `RADIO_AIRLOCK`, whereas emitters and the AAC work on `RADIO_ATMOSIA`.
What's the best solution? Make a new, seperate button that's on `RADIO_ATMOSIA`? Make access buttons broadcast on both filter ranges?

**Comment by Kurfursten** [comment]
Give buttons a multitool menu that lets you select their filter

**Comment by SonixApache** [comment]
I can dig it.
