### ISSUE TITLE
Monkey Transformation animation for Plasma Men is Jank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19688]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
80f35b7d06c1dab7bb9ff18777c95874b968addd

# Description

Plasma men being monkeyed by the staff of change do the human monkeying animation, which means they go from a plasma man, to a naked human, then have there flesh fall off into a monkey, and then suddenly become a flaming skull.
# Steps to Reproduce

Be Plasmaman, be whacked by change staff
# What you Expected

Plasma memes
# What Actually Happened

Jank

**Comment by Killette2** [comment]
This happens with any race
