### ISSUE TITLE
Bluespace Anomalies are bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19690]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
80f35b7d06c1dab7bb9ff18777c95874b968addd

# Description

The actual location of a bluespace anomaly and its reported location via announcement are not consistent
# Steps to Reproduce

I dunno get a BSA 
# What you Expected

The region that was said to have been anomalized to have been anomalized
# What Actually Happened

A different department entirely got fucked.

**Comment by jknpj** [comment]
but BSA always affect the whole station

**Comment by SGuivenne** [comment]
except its saying it was centered around aft primary when it was actually engineering, or that it was in the teleporter when it was actually the AI core that got beamed up somewhere.

**Comment by jknpj** [comment]
Maybe i'm thinking about the wrong event

**Comment by Exxion** [comment]
Judging by the code, there's no way it could be wrong about the area that the effect is *centered* on
BUT it picks a random turf from that area and teleports everything within 12 tiles of it to a random beacon, so it could easily still take things that are in other areas if it picks a turf near the edge of the chosen area

Also I have never seen this event happen in-game, ever
I didn't even know about it until this issue
