### ISSUE TITLE
Cant pickup deck of une cards after putting them in a box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19698]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
d1706cc4db2f3dc555f8721032bdc9cbc3f896fe

# Description
stick em in a box, expect to be able to click-drag them out to pick up the full deck, but actually "You can't reach it from here.", forcing you to pull out all 108 cards individually

**Comment by DrSnips** [comment]
This is an issue with the recent clickdrag to sort inventory changes and applies to all card decks likely.

**Comment by SGuivenne** [comment]
Just make sure when you fix it you don't do the bug again where you can click drag from anywhere to anywhere like that one bug a while back.

**Comment by DrSnips** [comment]
I just put a deck of cards in my bag in a round and then clickdragged it to my hand slot without issue. Maybe it was due to being in a box in a bag but I dont see why that would be an issue.
