### ISSUE TITLE
[Metastation] Virology changes

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#1969]
There is no Antibody Scanner (/obj/item/device/antibody_scanner)

Replace the Pathogenic Isolator (/obj/machinery/disease2/isolator/) with a Pathogenic incubator (/obj/machinery/disease2/incubator/)

Add a Vial storage box (/obj/item/weapon/storage/fancy/vials) and a secure vial storage box (/obj/item/weapon/storage/lockbox/vials)

And lastly add a Medical laptop (/obj/machinery/computer/med_data/laptop)

There are no starting virus samples either.

**Comment by ComicIronic** [comment]
Check this again.

**Comment by clusterfack** [comment]
CHECK IT AGAIN

**Comment by DeityLink** [comment]
But I did ;_;

**Comment by clusterfack** [comment]
Okay
