### ISSUE TITLE
Botany Plant Clippers are bugged and have been for probably over a year

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19691]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
80f35b7d06c1dab7bb9ff18777c95874b968addd

# Description

Plant clippers have a minor but existing bug where, when used, they seem to obligatorily increase the growth state of the plant they are used on, which is nonsensical
# Steps to Reproduce

plant a plant, use plant clippers

**Comment by Killette2** [comment]
shhhhh

**Comment by SonixApache** [comment]
![image](https://user-images.githubusercontent.com/8468269/45638962-032b1b80-baaf-11e8-9054-ed990b713d44.png)
amazing

**Comment by Killette2** [comment]
There's a black github?

**Comment by SonixApache** [comment]
nah, I use Stylus and a black theme

**Comment by Hugh-G-Rection** [comment]
Not a bug nothing to see here Botany is working as intended
