### ISSUE TITLE
You pull back the tab of Nuka Cola Quantum with a satisfying pop.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19695]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
80f35b7d06c1dab7bb9ff18777c95874b968addd

# Description
Its a fucking bottle, BOTTLES DONT HAVE TABS
# Steps to Reproduce

Get Nuka Cola Quantum, open with satisfying pop
# What you Expected

To remove the cap with a satisfying pop
# What Actually Happened

Remove tab.

**Comment by Kurfursten** [comment]
![](https://s-media-cache-ak0.pinimg.com/564x/1a/8f/d6/1a8fd6c3a3b1e25b3fff6c8faa439e64.jpg)
