### ISSUE TITLE
Wendigo virus has no cure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19702]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
27033397535792b994d5877c9ada8bb6be3708a4

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment]
Good old virus 1

**Comment by Exxion** [comment]
Actually the other one's better
#19703
