### ISSUE TITLE
Reinforced mining hardsuit is invisible on greys

### ISSUE THREAD

**Issue by Waismuth** [d3athrow/vgstation13#19709]
#### Description of issue
Normal hardsuit from mining looks ok on greys, but when you upgrade it with hide plates it becomes transparent, showing your character like it's naked

#### Difference between expected and actual behavior
Just want the armor to look normal

#### Steps to reproduce 
Be ayllmao, go mining, skin a Goliath, upgrade suit, become the spaceproof nudist 

#### Server revision
Game: f31484d3e0aed1af131f6c98854c3157b743d0fe 
Patches: f3f59aa7134ed6ac34edde8b9aa72c76dfd35634 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Waismuth** [comment]
there's a few items that appear invis on greys, so far I know the clown space suit helmet, and medieval plate armor helmet (ordered from cargo) is also invis on them

**Comment by ShiftyRail** [comment]
This got fixed.
