### ISSUE TITLE
Wendigo virus has no cure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19703]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
27033397535792b994d5877c9ada8bb6be3708a4

# Description
Warning: Virus Detected
Name: Unknown.
Type: Unknown.
Stage: 2/5.
Possible Cure:

**Comment by Exxion** [comment]
#19702 
Not marking as a duplicate because I don't feel like finding out if that would make closing this one close that one too

**Comment by Exxion** [comment]
Actually this one has more info

**Comment by MadmanMartian** [comment]
according to the code
`/datum/disease/wendigo_transformation
	name = "Unknown"
	max_stages = 5
	spread = "Unknown"
	spread_type = SPECIAL
	curable = 0
	agent = "Unknown"
	affected_species = list("Human")`
