### ISSUE TITLE
[Metaclub] Fixes - Primarily Engineering

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#1972]
Alright any issues I find I'll put here
Remove gas pumps after each coolant tank in atmos, the vent pump already serves this purpose. For oxygen and nitrogen however the mix pumps should be kept.

An entire tile of space in atmos can be saved by moving around the air mixing setup as shown
![savingspaceinatmos](https://cloud.githubusercontent.com/assets/8516830/5179278/a247caec-7440-11e4-8e11-3294d959f743.png)

Maint distro pipes go over floor tiles
![maintdistro](https://cloud.githubusercontent.com/assets/8516830/5179273/93c52aa0-7440-11e4-8608-3130a5251707.png)

Tcomms has no cooling system installed in any form, therefore if a round goes on it will usually fail by 1.5 hour mark without any human tampering.

Antimatter room essentially blocks the normal path to the Minisat. You can still get there by crawling under the tubes, then walking all the way along antimatter chamber, then crawling under the tubes again.

Atmos has no valve that allows you to vent waste to space.

Alternate mining shuttle sends and recalls the original mining shuttle using its console, still has space bridge control, despite being on the opposite side of the station.

Crew monitoring computer doesn't display the actual metaclub map.

Transport tubes cause you to experience pressure damage while inside of them.

All these pipes going to the connectors outside of atmos can be raised above the rwalls or piped under the nearby glass instead. Also if the pump location earlier going to the portable gas pumps is changed, you can remove the two gas pumps on the left side of atmos that are currently in existence.
![pipeunderrwalls](https://cloud.githubusercontent.com/assets/8516830/5181542/15dad604-745d-11e4-8568-78df8890823a.png)

**Comment by ComicIronic** [comment]
Check again and update, please.
In particular the one about the computer not showing the right map is outdated, I wonder which other ones are.

**Comment by clusterfack** [comment]
It's true many of these issues -have- been fixed already. Thus I'll close this issue.
