### ISSUE TITLE
Move to top command doesn't do anything anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19734]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
d10f21b723966fddc3fcf5120656277909d14ad3

# Description

On the tin
# Steps to Reproduce

Try using move to top
# What you Expected

It to work
# What Actually Happened

It no work

**Comment by Exxion** [comment]
Right, since BYOND changed how it layers objects on equal plane and layer sometime in 512
To be fair we never should have relied on the old behavior

**Comment by DamianX** [comment]
duplicate of #19063

**Comment by Exxion** [comment]
You know we can actually mark things as duplicate now
We should do that instead of just closing them
Like this:

**Comment by Exxion** [comment]
Duplicate of #19603

**Comment by Exxion** [comment]
God damn it I fucked up hold on

**Comment by Exxion** [comment]
Duplicate of #19063

**Comment by Exxion** [comment]
I hate mobile

**Comment by DamianX** [comment]
it's case-sensitive for reasons that are beyond me, okay

**Comment by Exxion** [comment]
It has to be *exactly* that post
This used to not be the case but I guess people complained about accidentally using the feature or something
