### ISSUE TITLE
Martians can Put literally any item in their head slot.  Invalid items will register as being held.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19751]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
6e4563907a84563ad65f2b4e1377d1ecf08e5e45

# Description

Not sure why this is that way, it doesnt do anything either
# Steps to Reproduce

Be martian, try to wear shit
# What you Expected

Hat memes
# What Actually Happened

Jank

**Comment by kilozombie** [comment]
Related to https://github.com/vgstation-coders/vgstation13/issues/19473 because absolutely nothing can be actually equipped to the head slot anyway
