### ISSUE TITLE
Please for the love of christ connect the distro tubes on box main with the ones in xenobiology.

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#19769]
#### Description of issue

Its hell for borers if the airlock has been sealed the wrong way as they cannot leave the room.  It kinda fucks with the round in general]

**Comment by Irradiation** [comment]
Like virology, it's intentionally separated from the normal distro so naughty shit can't out without help
READ: SLIMES VENTCRAWLING

**Comment by jknpj** [comment]
>if the airlock has been sealed the wrong way as they cannot leave the room

That's the point of them.

**Comment by DeityLink** [comment]
I don't remember when this was changed exactly but borer eggs are no longer in xenobio, they now have their own small room outside, featuring a vent connected to distro.
