### ISSUE TITLE
Cyborg lockdown without being locked down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19767]
(WEB REPORT BY: gazzyh REMOTE: 172.93.109.202:7777)
# Revision
63f63add5f463df6e34fb721583e4ef53363a666

# Description
Was unable to move and functionally "locked down" without getting said lockdown message
# Steps to Reproduce
Dunno, play cyborg and get locked down even though you're not locked down?
# What you Expected
Lockdown gets lifted, I move
# What Actually Happened
Lockdown gets lifted, I don't move

**Comment by SonixApache** [comment]
broken actuator or a signaller on the lockdown wire, maybe.
