### ISSUE TITLE
Yes and No are swapped on Flora Data Disks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19777]
(WEB REPORT BY: miniaturebigfoot REMOTE: 172.93.109.202:7777)
# Revision
63f63add5f463df6e34fb721583e4ef53363a666

# Description
Selecting Yes to wipe data will not wipe it, but selecting no will.
# Steps to Reproduce
Put data on Flora disk, then try to wipe.
# What you Expected
For Yes to be Yes.
# What Actually Happened
Yes was No.

**Comment by DamianX** [comment]
https://github.com/vgstation-coders/vgstation13/blob/63f63add5f463df6e34fb721583e4ef53363a666/code/modules/hydroponics/seed_machines.dm#L16-L24
🤔 seems fine to me?

**Comment by kilozombie** [comment]
Never had an issue with this.

**Comment by Exxion** [comment]
Someone clarified in the thread that the buttons are reversed from their usual positions
The person who opened this issue probably didn't *read* the buttons
The positions should be switched if that's true
