### ISSUE TITLE
the autoborger can slave their victims to non-malf AIs if there are any available

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#19776]
#### Description of issue
so you're a malf, right
and someone hit the triumvirate button, right
so you got no borgs because who plays borg anyway
so in a last-ditch effort, you toss down an autoborger
but then only every third borg is yours, because of `select_active_ai_with_fewest_borgs()` being called when the borg gets borged
so that's kinda shitty

#### Difference between expected and actual behavior
be milf, have other AIs at roundstart, autoburger 5 carbons, recieve 5 slaved milf borgs
vs
be milf, have other AIs at roundstart, autoburger 5 carbons, recieve 2 slaved milf borgs and 3 hostile borgs
#### Steps to reproduce 

see above

#### Specific information for locating
`select_active_ai_with_fewest_borgs()` 

#### Length of time in which bug has been known to occur
god knows

#### Server revision
63f63add5f463df6e34fb721583e4ef53363a666

**Comment by ShiftyRail** [comment]
Feature

**Comment by Killette2** [comment]
Seems like a balance decision

**Comment by Kurfursten** [comment]
I hate milf as much as the next guy, but the autoborger is an antag tool that has to be purchased. We don't send sec a paralysis pen for every time the ling uses his paralysis sting.
