### ISSUE TITLE
Sillycone ban

### ISSUE THREAD

**Issue by tayachiya** [d3athrow/vgstation13#19775]
#### Description of issue

Total sillycone ban should include posibrains but should not include a pAI

pAIs are completely different in the little gameplay they get compared to borgs/AIs/mommis, that I feel like they shouldn't be included
Posibrains on the other hand lead only to those three "jobs", and I see no reason why a jobbaned person should be a posi

**Comment by ShiftyRail** [comment]
This is more of an administrative issue than a code one.

I have on my backlog a general framework for ghost roles ban, but I'm not sure if I'll ever find the time to implement it.

**Comment by Reviire** [comment]
Posibrains can lead to being put into a human body, so it'd be kind of wrong to prevent them too. You're already prevented from playing sillycone, no reason to ban the posibrain. It's just a normal brain, plus a few rules.

**Comment by tayachiya** [comment]
I've been told to write it here, so I wrote it here
Posibrains bein put in a human body is an incredibly unlikely situation, which I've seen like 5 times tops
I still think the ban should not include a pAI

**Comment by ShiftyRail** [comment]
Admins have full liberty to choose which roles they ban, the preset is something stored on Pomf's server

Litteraly not a code issue
I'll lift your pAI ban this evening

**Comment by DamianX** [comment]
It seems you can't jobban someone from posibrains, though?

**Comment by Exxion** [comment]
>get jobbanned from borg
>join as posibrain
>cannot become ANYTHING except a mech

**Comment by SGuivenne** [comment]
Isn't that asking for shitters?  Seeing as you are basically one step from antag at that point?

**Comment by Exxion** [comment]
Yeah that was kind of my point
