### ISSUE TITLE
Invisible Man Rides Mulebot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19772]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
63f63add5f463df6e34fb721583e4ef53363a666

# Description
if you get onto a chair and have a mulebot pick up said chair you ride the mulebot invisibly with only the chair visable
# Steps to Reproduce
get mule bot
get chair
get on chair
get chair on mulebot
# What you Expected
visable man riding mulebot on a chair.
# What Actually Happened
this https://imgur.com/a/2IARZGV

**Comment by Kurfursten** [comment]
Related #17785

**Comment by Exxion** [comment]
Someone just change the MULE to use atom locking already

**Comment by DamianX** [comment]
I did here https://github.com/DamianX/vgstation13/tree/MuleLockingAtoms but it was awful, if someone wants to pick it up from there go ahead.

**Comment by Zth--** [comment]
Fixed here #22111
