### ISSUE TITLE
resetVariables() is broken

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#19779]
#### Description of issue
`/datum/proc/resetVariables()` expects its args to be strings containing names of vars to NOT reset.
https://github.com/vgstation-coders/vgstation13/blob/63f63add5f463df6e34fb721583e4ef53363a666/code/__HELPERS/datumpool.dm#L108-L126

Instead, most implementations pass parameters like this:
```
/mob/living/simple_animal/resetVariables()
	..("emote_hear", "emote_see", args)
/mob/living/simple_animal/bee/resetVariables()
	..("bees", "visited_plants", args)
```

which results in resetVariable's args being (JSON representation):
`["emote_hear","emote_see",["bees","visited_plants",[]]]`

instead of the expected:
`["bees","visited_plants","emote_hear","emote_see"]`

#### Length of time in which bug has been known to occur
The beginning of time?

#### Server revision
63f63add5f463df6e34fb721583e4ef53363a666

**Comment by Exxion** [comment]
Make it take one argument, which is a list
Then the override is just
```
arg_name += list("whatever")
..()
```
(Yes I am sure that works)
(OK 99% sure)
(If it doesn't then `..(arg_name + list("whatever"))` but that's probably slower)
And the rest should be obvious

Then hope that nothing was relying on this bug, and cry when something inevitably was

**Comment by DamianX** [comment]
Last time I touched pooling I killed the server so I'm not going to do this

**Comment by SGuivenne** [comment]
Look, killing the server is basically a rite of passage for a coder and/or veteran player.
