### ISSUE TITLE
Injecting monkey blood doesn't seem to transfer antibodies

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19771]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
63f63add5f463df6e34fb721583e4ef53363a666

# Description
Can't cure a virus with simple monkey-blood transfusion, need to make a proper cure first

# Steps to Reproduce
Infect with a virus, feed radium, try to transfer antibodies

# What you Expected
Not be sick

# What Actually Happened
Stayed sick

**Comment by DamianX** [comment]
#20402 has slightly more info
