### ISSUE TITLE
I got high and meta'd the roundtype

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#19783]
1. be an engineer who ordered some crates
2. jerk off around the supermatter shard to burn a little bit of time while you wait
3. hallucinate the wizard hitting you before it ever leaves the wizard den
https://prnt.sc/ky8ku6
![image](https://user-images.githubusercontent.com/5169310/45980708-b9977f00-c020-11e8-845d-353d9679183d.png)

**Comment by Kurfursten** [comment]
Probably would be a safe fix to just exclude people on Z2 in general from being hallucinated. That would also avoid test dummies in the Thunderdome and ops inside their base.

**Comment by Dacendeth** [comment]
Another issue is it seems like who you hallucinate is only ever one person, this can also be used to meta changes about who your hallucinate target is and what they are wearing or worse.  One time the person I was hallucinating even DNA scrambled himself to hide but I hallucinated his new look and knew who he changed into.

**Comment by RealestEstate** [comment]
it's a FEATURE.
and a funny one at that.
funny == good

**Comment by SGuivenne** [comment]
Honestly, just throw in some stock hallucinations for fucks sake.  A few nuke ops, grey tide, wizard, or cultist looking assholes with random names would be a pretty solid way to neutralize this.

**Comment by Probe1** [comment]
feature
