### ISSUE TITLE
Catfish Cause Algae Instead Of Eating It

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#19781]
Thanks fishtank port

I swear, that thing was a pile of badcode

**Comment by ShiftyRail** [comment]
I have it on my mind to convert all fish to OOP
If I'm not too busy I'll attack that this week-end.

**Comment by Killette2** [comment]
It might be an issue of them doing both when you go under/over a certain number. A similar thing happened with plants getting a buttload/max amount of weeds when you added too much polyacid to them, a chemical that's supposed to kill weeds (and the plant but we're focusing on weeds here).

**Comment by Kurfursten** [comment]
I wasn't able to reproduce this on local. Absolutely bizarre, keep an eye on this.

**Comment by MadmanMartian** [comment]
>I have it on my mind to convert all fish to OOP

Are you saying they're not already?

**Comment by Kurfursten** [comment]
If only you knew how bad things really were, Madman

**Comment by Killette2** [comment]
I made this happen a round ago by having a large tank with ~5 catfish and ~5 eels. Either the catfish were causing the algie, or there being 8-10 fish caused almost instant max dirtiness which would be a problem in a different regard.

**Comment by Kurfursten** [comment]
Yeah I was there, I was the other engineer, that's why I made the report
