### ISSUE TITLE
Inconsistent access on Packed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19789]
(WEB REPORT BY: baronvs REMOTE: 172.93.109.202:7777)
# Revision
770b0577606eda75ac346e4a3147e15e27dd6dd6

# Description
Giving someone Engineering access does not actually give someone access to Engineering

# Steps to Reproduce
Get an ID card that does not have Engineering access on it, give it access, then try to walk through the door.

# What you Expected
The door labelled ENGINEERING to open for someone who has ENGINEERING access on their ID card

# What Actually Happened
No access. Further testing revealed that the door actually opened for Power Equipment instead

**Comment by Kurfursten** [comment]
This is actually due to a common misconception and applies to several maps. The first room is engine_equip, the engineers' loadout room. Power equipment. Engine access is for the engines themselves (and called Engineering).

**Comment by CptWad** [comment]
This isn't really a mapping issue or even specific to packed. The only difference is that the primary door requires ONLY engineering but not atmos like other maps. This is a ID logic issue if an issue
