### ISSUE TITLE
Plant alternate chems don't affect plants like their main counterpart

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#19784]
- Add antitoxin to plant, it helps
- Add plant-antitoxin to plant tray, it does nothing
- Plant chems were ported with almost no new reactions and lead to more mistakes than good

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
If you can make a complete list of what's missing it'd be easy to add it in

**Comment by Shadowfgt** [comment]
botany snowflake chems were a mistake

**Comment by Killette2** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/hydroponics_reagents.dm

there's antitoxin, polyacid, sulfacid, toxin, and a few more that I might have missed.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I literally just tested it and ALL the snowflake chemicals work with plants :thinking:

**Comment by Killette2** [comment]
Brb

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Killette2, Botanist, has been missing for a week.
