### ISSUE TITLE
AntagHUD no longer works.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19797]
(WEB REPORT BY: meetmeindorms REMOTE: 172.93.109.202:7777)
# Revision
40e82996617dc215eda9f82ea0df6cc13aab2512

# Description
I have AntagHUD on, but it doesn't appear to be working on antags.

# Steps to Reproduce
>be admin
>look at antags
>turn on antaghud

# What you Expected
AntagHUD to work, and show who's an antag.

# What Actually Happened
Nada.

**Comment by DeityLink** [comment]
I remember ghost antag hud working significantly differently from regular antag hud, I wonder if there's a seamless way to have both work together.
