### ISSUE TITLE
Debit card sprites are gonezo.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19790]
(WEB REPORT BY: meetmeindorms REMOTE: 172.93.109.202:7777)
# Revision
1b1e1b7aff96f3e117bb98d0fe86568bbc45f263

# Description
Literally the issue description.

# Steps to Reproduce
1. Log into the game.
2. Get a debit card.

# What you Expected
A debit card.

# What Actually Happened
No debit card sprite.

**Comment by DeityLink** [comment]
Should be fixed by #19791
