### ISSUE TITLE
ROLE DATUMS nuke op issues

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#19798]
i reported these ingame but for posterity

- [x] we had 6 ops
- [x] there didn't appear to be a leader, nobody had the special icon
- [x] we didn't spawn with the code? maybe? not sure
- [ ] the uplink didn't have ops-only items
- [ ] we rolled a greytide kit with the random item option, is that normal?

**Comment by DeityLink** [comment]
#19799 fixes 1- and 2-.
3- wasn't a bug, there was a code.
4- and 5- are getting fixed soon.

**Comment by MadmanMartian** [comment]
greytide kit for ops sounds fun

**Comment by SonixApache** [comment]
@DeityLink did 4 and 5 ever get fixed?

**Comment by jknpj** [comment]
no because 4 needs effort and 5 happens even to normal traitors(it's shitcode but people will tell you it's a feature)
