### ISSUE TITLE
Power Crepes take an oddly large amount of time in the microwave

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19800]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
40e82996617dc215eda9f82ea0df6cc13aab2512

# Description

Power crepes seem to take a minute IRL of time in the microwave or more to actually make
# Steps to Reproduce

Make a power crepe, stand around akwardly
# What you Expected

Quick Microwave
# What Actually Happened
Slow

**Comment by Kurfursten** [comment]
I warned people false reports would happen when only 1 food has a custom cook time

Not a bug
