### ISSUE TITLE
Nuke disk trash compactable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19803]
(WEB REPORT BY: fritzlhimmlerina REMOTE: 172.93.109.202:7777)
# Revision
a70d78279c79a295dd65a50bf2bc3020bf613d7c

# Description
You can trash compact the nuke disk, not sure if this is intended behaviour, but it would strike me the compactor should refuse to operate when the disk is in it.

# Steps to Reproduce
Put nuke disk in container (used the secure briefcase myself), put container is trash compactor, engage trash compactor. Not sure if this works without putting the disk in a container first.

# What you Expected
No compaction

# What Actually Happened
Compaction

**Comment by Kurfursten** [comment]
no big deal since it's undamaged inside the cube

**Comment by SonixApache** [comment]
How do you uncube the cube?

**Comment by Kurfursten** [comment]
toss in the recycler or any level of explosion
