### ISSUE TITLE
Invisible and Intangible Pylons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19811]
(WEB REPORT BY: explosiveamnesia REMOTE: 172.93.109.202:7777)
# Revision
80d64440b0dcc0c941601f86c5575a5250da3152

# Description
As an artificer created by a wizard (haven't played cult artificer yet), your Red Pylons are invisible and intangible, but still give off light and heal constructs.

# Steps to Reproduce
1. Become Artificer
2. Create a Red Pylon
3. ???
4. Profit!
# What you Expected
A visible and physical red pylon
# What Actually Happened
OP unkillable pylons pls nerf

**Comment by MadmanMartian** [comment]
another lost icon

**Comment by Exxion** [comment]
Yeah, but that doesn't explain the 0 `density`
