### ISSUE TITLE
Datum vampire bats attack the vampire that summoned them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19813]
(WEB REPORT BY: irradiation REMOTE: 172.93.109.202:7777)
Vampire spawned bats to try and break escape windows and some decided to turn on him.

The space bats bites the monkey (139)!

The space bats smashes against the grille.

The space bats smashes into the reinforced window!x4
The space bats bites Spencer Hunter (as Chip Weisgarber)! (VAMPIRE)
The space bats bites Spencer Hunter (as Chip Weisgarber)!
The space bats bites Spencer Hunter (as Chip Weisgarber)!

**Comment by ShiftyRail** [comment]
Fixed
