### ISSUE TITLE
Fully filled oxygen tanks run out in about three minutes.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19829]
(WEB REPORT BY: bigkuro REMOTE: 172.93.109.202:7777)
# Revision
bff0f66fcbbe17a3550d601b4a7959b46796d30b

# Description
An extended-capacity emergency oxygen tank now lasts like three minutes before it runs out of oxygen.

# Steps to Reproduce
Grab an extended tank from an oxygen locker. Fill it up to max kPA. Turn it on, wait four minutes and watch as your character begins to gasp for air.

# What you Expected
Being able to explore space.

# What Actually Happened
Having to switch to a big oxygen tank since the yellow one ran out. Even the big one runs out quicker now.

**Comment by Exxion** [comment]
God damn it
