### ISSUE TITLE
(CA) no longer checks antagonist in dynamic mode

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19836]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
8807e3dc60ec65f08ea3671d03a70b24bcba539c

# Description
(CA) in the special tab for admins no longer works for prayers or centcomm messages, i suspect across the board its borked
# Steps to Reproduce
get prayed at and smack (CA)
# What you Expected
antagu check
# What Actually Happened
denada

**Comment by DeityLink** [comment]
:thinking:
