### ISSUE TITLE
Plasmaman suffocate to death breathing plasma

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#19833]
#### Description of issue
Plasmaman cant play the game right now, taking constant suffocating damage upon joining.

#### Length of time in which bug has been known to occur

Didn't happen yesterday.

#### Server revision

Revision: 8807e3dc60ec65f08ea3671d03a70b24bcba539c 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
???
The math should be exactly the same as before

**Comment by Exxion** [comment]
Nice
This is specific to plasmamen. Vox are fine. So are humans, of course.
I hate lifecode
