### ISSUE TITLE
Random shuttle tile in CentComm

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#19839]
![image](https://user-images.githubusercontent.com/9827785/46180064-38442480-c28c-11e8-932d-d77205b1498e.png)

**Comment by Orangerush** [comment]
it's a feature

**Comment by Exxion** [comment]
Yes, this has been fixed
There's also an extra window visible in the bottom tile of the screenshot, which I didn't notice until just now, and it's still there
But that's a separate issue
