### ISSUE TITLE
Holo People lack dexterity to get Swole

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19841]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
c6a7e5098e3d0ad71d49a81baeec307d5d333e6d

# Description

All exercise gear and laser tag guns currently fall outside of what holo people can use.  This includes treadmills and the exercise machines.  We cannot acquire holographic gains.
# Steps to Reproduce

Be holoman, have gym, get cucked
# What you Expected

Holo Swole
# What Actually Happened

Beta A F

**Comment by west3436** [comment]
They are holograms not people
