### ISSUE TITLE
Vox Raiders Missing from One Click Antagonists

### ISSUE THREAD

**Issue by bathosbathtime** [d3athrow/vgstation13#19846]
![antago-ants](https://cdn.discordapp.com/attachments/245856152276041728/495082886198984705/temp13.PNG)
Vox raiders are not on the one click menu for create antagonists.
Please readd so I can hit it and get the "not enough candidates" message again.

**Comment by ShiftyRail** [comment]
You're meant to use the the game panel stuff, we live in a dynamic society
