### ISSUE TITLE
NPC xenos attack NPC reanimated player zombies

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19842]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
c6a7e5098e3d0ad71d49a81baeec307d5d333e6d

# Description

Reanimated zombies of dead players come back and are immediately eaten by xenomorph mobs 
# Steps to Reproduce

Get killed by a zombie, have a xeno mob out, get reanimated and murdered
# What you Expected

Indifference
# What Actually Happened

Memes

**Comment by jknpj** [comment]
They have different factions, that's normal.
