### ISSUE TITLE
You can't spin new shuttle chairs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19857]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
67b9ab2389a2e1bdeeb1fc3c4351bd500a627067

# Description

This is a tragedy

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's a feature, but a bad one

**Comment by spoonylove** [comment]
Riot

**Comment by jknpj** [comment]
What the vox-vaper said
