### ISSUE TITLE
Can't seem to scrub emergency oxygen tanks

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#19858]
#### Description of issue
Emergency oxygen tanks won't empty out when placed in a scrubber or portable pump.
I tried on, off, in, out, wrenched and unwrenched. Nothin'. Plasma tanks, on the other hand, work fine.

#### Difference between expected and actual behavior
Place tank in scrubber, turn on scrubber, empty tank
vs
Place tank in scrubber, turn on scrubber, no changes

#### Specific information for locating
Tested with blue and yellow emergency oxygen tanks, and a plasma tank.

#### Length of time in which bug has been known to occur
Less thank a week. If I'd have to point "probably related" fingers, I'd point at @Exxion's #19802.

#### Server revision
67b9ab2389a2e1bdeeb1fc3c4351bd500a627067

**Comment by Exxion** [comment]
>Plasma tanks, on the other hand, work fine.

Mother fucker I tested plasma tanks

**Comment by Exxion** [comment]
I can't reproduce this.

**Comment by DamianX** [comment]
Scrubbers aren't supposed to take oxygen out of a container anyway, right?

**Comment by Exxion** [comment]
No, but he also said portable pumps

~~While investigating this, though, I came across an unrelated but *fucking stupid* bug with pumps~~
EDIT: Scratch that, I'm a dumbass
They do something stupid but it gets caught by sanity elsewhere

**Comment by SonixApache** [comment]
turns out i'm retarded and the pump was just full (probably)
