### ISSUE TITLE
[img][/img] fucken broking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19859]
(WEB REPORT BY: cadaverouscoyote REMOTE: 172.93.109.202:7777)
# Revision
67b9ab2389a2e1bdeeb1fc3c4351bd500a627067

# Description

images can not be embedded in paper. the files appear broken, both with images uploaded recently and images uploaded long ago which once worked.

# Steps to Reproduce

pick an image from the internet and paste its link between image tags on a piece of paper. then get somebody to examine it and tell you what they see.

# What you Expected

my drawing

# What Actually Happened

[X]
 ¯

**Comment by beesil** [comment]
What image host were you using? Some don't work in my experience.

**Comment by cadaverouscoyote** [comment]
alright i'm back
>What image host 

tried a couple. and like i mentioned, hosts which once worked (namely imgur) no longer do, that's some feature loss.

**Comment by jknpj** [comment]
Not an issue with the code,they just disabled hotlinking.
