### ISSUE TITLE
Checking for injuries is malfunctioning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19862]
(WEB REPORT BY: volttekka REMOTE: 172.93.109.202:7777)
# Revision
d3114dcd75893fc6c9a05429ca0e92ba7a52b224

# Description
All it shows is leg status
# Steps to Reproduce
Help intent, click self
# What you Expected
Full list of body part status
# What Actually Happened
Ony leg status.
You check yourself for injuries.

My legs are OK.

**Comment by jknpj** [comment]
It's a meme feature
