### ISSUE TITLE
Request: Adjust Shuttle Seats

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#19865]
Requiring 5 plasteel makes them somewhat obnoxious to build if you want to make them, but it also means that arrivals is a treasure trove of usually around 125 plasteel at roundstart to anyone with a welder. Wouldn't it be better for both autism building AND less looting if it was made to 1 sheet instead? (Arrivals would still be worth like 20 plasteel) This is a really small change and easy to PR but I thought I'd put it up for discussion.

@DeityLink

**Comment by RealestEstate** [comment]
yes this is a good suggestion.

**Comment by DeityLink** [comment]
How about 2 plasteel

**Comment by Kurfursten** [comment]
That's fine too although just remember the arrivals shuttle is loaded with these things on every map

**Comment by DeityLink** [comment]
Some maps more than others arguably. I think on some stations there's not a single tile of free space, that's kinda unrealistic.

**Comment by Kurfursten** [comment]
Even Packed manages to stuff in a somewhat incredible 17 seats

**Comment by DeityLink** [comment]
And I mean, come on, it's a lowpop map, there won't ever be 17 players joining packed at once, heck there could be 4 seats.
