### ISSUE TITLE
October Bug Squashing IS LIVE

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#19879]
This is a sort of promotion idea I had to drum up support for coding bug fixes without the financial incentive of bounties or the draconian lockdown of an oldschool feature freeze. The idea is this: *anyone* is welcome to post here and commit to fixing bugs and get added to the list. Then, for any bug fix made in October (which is not itself a part of OBS) the participants will *match* that bug fix by fixing one of their own. In this way, the force of any one bug fix is multiplied by the participants. There are also two extra bonuses.
* Fixing a particularly stubborn/difficult bug (such as finally fixing our Crew Monitoring Computer, Adv Cameras, or Central Atmos computer) will be worth *five* bugs fixed (either making the committed fix five each or fulfilling the obligation of 5 bugs for one committed). A list of these will be fully decided upon and posted on October 1.
* A first time bug fixer / first time coder PR must be matched by *five* bugs fixed by all those committed to the challenge. This is to incentivize new people to get over the hurdle of learning git and making their first contribution to our server.

I will keep a running tally of how many bugs need to be fixed if you're participating right here (feel free to tag me for bug fix PR *started* in the month of October), as well as those who have committed to join the challenge.

**Participants**
* Kurfurst: 1
* Damian: 2
* Shifty: 16
* jknpjr: 4
* MartianMadman: 11

**Current Fix Target**: 77
* RealestEstate: 3
* Intigracy: 1
* Exxion: 6 (as 10)
* Shadowmech: 42
* Sonix: 1
* Deity: 4
* tralezab: 2 (as 6)
* BarneyGumball: 5
* Sood: 2
* Vape: 2

Here's my hitlist for "hard bugs"
* ~~The mysterious "examine by shift click but not examine by verb works in a mech" #4829~~
* Camera jumping has a split second of showing everything #18384
* Everyone's nude in 512 #19706
* Fixing the arcane issue with NanoUI where it just pops up blank or won't open at all (e.g.: #15576 #17724 #3264 probably others I couldn't find)
* And fixing any of the three: Crew Monitoring Computer, ~~Central Atmos Computer~~, Advanced Security Cameras #3591 #6446 #13216 #6446
* ~~Monkey DNA Trouble  #8102~~
* Ghostly esword blood #9175

**Comment by Hoshi-chan** [comment]
I haven't done anything in years, and don't remember how to use git, would a contribution from me count as a first-time bug fix?

**Comment by Kurfursten** [comment]
Sure I'll allow it

**Comment by Irradiation** [comment]
HIGH OCTANE BUG FIXIN'

**Comment by MadmanMartian** [comment]
Sign me up

**Comment by MadmanMartian** [comment]
wake me up when tomorrow starts

**Comment by Shadowmech88** [comment]
If anyone knows of or stumbles across any bugs with features I have made, please assign them to me or mention me in them.
I usually self-assign such bugs, but
![image](https://user-images.githubusercontent.com/3991927/46271684-540d2c00-c513-11e8-8905-70093a61aba3.png)

**Comment by ShiftyRail** [comment]
I will consider #19902 & #19889 as a first-time PR and code 5 bugfixes for them

**Comment by jknpj** [comment]
@ShiftyRail neither are bugfixes

**Comment by ShiftyRail** [comment]
`A first time bug fixer / first time coder PR must be matched by five bugs fixed by all those committed to the challenge. This is to incentivize new people to get over the hurdle of learning git and making their first contribution to our server.`

Counts as a first-time PR for me (since he learned SmartGit for them)

**Comment by Kurfursten** [comment]
Posted my list of "hard bugs", feel free to nominate others or Discord message me with nominations

**Comment by Blithering** [comment]
Would me fixing a non sprite-related bug count as a first time?

**Comment by Kurfursten** [comment]
The spirit of the new coder bit is anyone who has to learn git to make their contribution, do you qualify for that?

**Comment by Exxion** [comment]
lol

**Comment by Kurfursten** [comment]
I've already taken out 20% of my promised fixes and I am confident the other pledgees will do theirs in time

**Comment by MadmanMartian** [comment]
what do the numbers by the names mean?

**Comment by Kurfursten** [comment]
they were bug fix counts last time I updated (Oct 20 I think?)

**Comment by Exxion** [comment]
Well it's also December and not October, so leaving it open makes no sense
