### ISSUE TITLE
Vox vamps can't succ

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#19877]
#### Description of issue
Vox vamps just punch people when they succ even if they have head targeted, harm intent on, and bite intent on
It only happens while their masks are on

#### Difference between expected and actual behavior
Vox vamps punch when they try to succ

#### Steps to reproduce 
Be vox (optional probably), be vamp, wear mask, succ blood

#### Specific information for locating

It's probably because [UnarmedAttack() in other_mobs.dm](https://github.com/vgstation-coders/vgstation13/blob/d9e848094b6925abf2f76e05e25d483a69edf908/code/_onclick/other_mobs.dm) calling [can_bite() in human.dm line 1502](https://github.com/vgstation-coders/vgstation13/blob/c6a7e5098e3d0ad71d49a81baeec307d5d333e6d/code/modules/mob/living/carbon/human/human.dm) which returns 0 due to `check_body_part_coverage(MOUTH)` so `UnarmedAttack()` calls [set_attack_type() in human.dm line 1462](https://github.com/vgstation-coders/vgstation13/blob/c6a7e5098e3d0ad71d49a81baeec307d5d333e6d/code/modules/mob/living/carbon/human/human.dm) with default argument so it just sets attack type to normal

#### Length of time in which bug has been known to occur
idk probably since datums

#### Server revision
c656f910240c361da8a65ba15ae3bc448a5f5e33 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
As Intigracy pointed out in the chat:
https://github.com/vgstation-coders/vgstation13/commit/a3ea15b60b276a564a0eaa54e78561f4d3eda38e#diff-1ff8328c73a4a8a73ad2c1fe6d517588L1471

Adding that back in would allow vampires to bite anything under any circumstances, but fixing this *without* causing that would be such a pain in the ass I'd be willing to deem it a feature
