### ISSUE TITLE
Staff of Change Removes the Abandon Faith Option for Chaplains

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#19873]
#### Description of issue

Being transformed by the staff of change removes your ability to abandon faith

#### Steps to reproduce 

Get changed by wizard, get bugged

**Comment by Kurfursten** [comment]
Should this really be a button? I feel like there should be some kind of sacrilege act anyone can do to abandon faith if converted.

**Comment by DamianX** [comment]
Agreed, make it religion-specific, too.
Brian Damag: consume alkysine
cult: drink holy water

**Comment by SGuivenne** [comment]
I dont know or get why its a button too, especially as it interfered with my Church of Anime Gimmmick due to looking identical to the tip fedora button

**Comment by DeityLink** [comment]
More importantly, there is only one /datum/action per religion which always gets granted to the latest convert. So if you convert someone, the previous convert will lose the ability to renounce their faith. Was this the intended behaviour @ShiftyRail ? If so that issue can probably be closed.
