### ISSUE TITLE
Advanced Energy Gun getting EMPd trashes it forever

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#19885]
#### Description of issue
The Advanced Energy Gun, like many energy weapons, is prone to EMP damage, unlike with most others however, due to its normal recharging it gets weird, venting radiation onto you instead and dumping its capacity.  This is fine normally, except in rare cases it'll stop recharging entirely after a point, which renders the weapon useless.  
#### Difference between expected and actual behavior

Expected: weapon recharges slowly, recharges however 

Reality: Weapon is irrecoverably broken 
#### Steps to reproduce 

Get advanced Energy weapon, get EMP'd roughly 3 times or so

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
lewd

**Comment by ShiftyRail** [comment]
>ERPing an energy gun

Strange tastes

**Comment by SGuivenne** [comment]
I've made a terrible mistake

**Comment by kilozombie** [comment]
ERP damage when

**Comment by Caboozles** [comment]
Memes aside, my AEG that same round had a similar issue. After we got EMP'd on the shuttle, it actually recharged for a small while, then stopped after about 2 minutes. It then refused to charge, even though I didn't have the same reactor rad issue you did, so it should have kept working.

**Comment by RealestEstate** [comment]
```
/obj/item/weapon/gun/energy/gun/nuclear/proc/failcheck()
	lightfail = 0
	if (prob(src.reliability))
		return 1 //No failure
	if (prob(src.reliability))
		for (var/mob/living/M in range(0,src)) //Only a minor failure, enjoy your radiation if you're in the same tile or carrying it
			if (src in M.contents)
				to_chat(M, "<span class='warning'>Your gun feels pleasantly warm for a moment.</span>")
			else
				to_chat(M, "<span class='warning'>You feel a warm sensation.</span>")
			M.apply_radiation(rand(3,120), RAD_EXTERNAL)
		lightfail = 1
	else
		for (var/mob/living/M in range(rand(1,4),src)) //Big failure, TIME FOR RADIATION BITCHES
			if (src in M.contents)
				to_chat(M, "<span class='warning'>Your gun's reactor overloads!</span>")
			to_chat(M, "<span class='warning'>You feel a wave of heat wash over you.</span>")
			M.apply_radiation(300, RAD_EXTERNAL)
		crit_fail = 1 //break the gun so it stops recharging
		processing_objects.Remove(src)
		update_icon()
return 0
```

**Comment by RealestEstate** [comment]
looks like the rad release and losing its recharge ability is quite literally a feature as far as I can tell.
(this is in AEG's file: /code/modules/projectiles/guns/energy/nuclear.dm)

**Comment by Killette2** [comment]
This is from long ago a feature, as a counter to advance E-guns you can permanently jam them. I think they're still jammed if they take the EMP damage even if you try recharging them with a recharger after.

**Comment by Exxion** [comment]
You can't recharge them in chargers

**Comment by SGuivenne** [comment]
My problem with this is mostly that, even if its apparently not a bug, theres no way to fix it, your expensive investment of materials (Or ERT tool) is completely and irreversibly useless to the point you may as well recycle the damn thing.  A simple addition of a repair method would be incredibly nice, especially as Im not aware of many tools you can properly burn out irreparably, even mechs at least let you salvage them for parts.

**Comment by Killette2** [comment]
What if you could slap on a new kit and the old one gets discarded? It's somewhat a balance change, but this would save you from having to buy a new gun at cargo at least

**Comment by RealestEstate** [comment]
I for one like the feature. AEG are a really powerful tool (and not that expensive to upgrade considering it’s mainly uranium for the kit), so being able to be permanently shut one off gives it a good counter that the user has to be aware of. it gives it a trade-off. as for ERT, they also get a ballistic gun iirc, but a broken AEG would make it significantly harder for them to subdue without killing  so I guess they should get a snowflake fail proof AEG.
this is my opinion.
however I do think it should give the user a hint when examining that shows it’s been damaged

**Comment by SGuivenne** [comment]
It'd only be a mild balance change, especially if you required the gun be put on the floor or a table as the normal upgrade is already.  After all, EMPing guns is generally intended to be a short term solution anyway, not a permanent "remove weapon from the field" option.

**Comment by RealestEstate** [comment]
as long as fixing it prevents bypassing the emp and replenishing the charge that’s perfectly fine by me.

**Comment by DamianX** [comment]
Closing because not a bug. If anyone wants to code the suggested changes they should go right ahead.
