### ISSUE TITLE
AntagHud no longer shows faction specific icons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19909]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
2ea5b7111f67d04f2ccce0f674c531fcca8cd1ad

# Description
only shows that black square with white question mark (tested on cult2 and ragin magin)

**Comment by Kurfursten** [comment]
@Exxion This is fixed (can't verify for cult2 but works for cult3 and raging)
