### ISSUE TITLE
Mule + Construct = Fucked up viewport

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19907]
(WEB REPORT BY: kharkov72 REMOTE: 172.93.109.202:7777)
# Revision
2ea5b7111f67d04f2ccce0f674c531fcca8cd1ad

# Description
Turns out, if you become a cultist construct and hop on a hacked MULEbot, your viewport stops moving from that MULE. If the mulebot gets destroyed, then your vision nulls out and you just get a black screen.
Things that might be important in the report:
-Only happened to wraith and juggernaut, artificer didn't hop on the wild ride
-these were non-cultist constructs (the chaplain made them himself)
-the MULEbot didn't move (not sure if it follows the bot or just stays on the location you get on at)

**Comment by Exxion** [comment]
Yeah that's pretty much expected
Fuck MULE code
