### ISSUE TITLE
Changelings can sting themselves, and will default to it if no target is in proximity

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19912]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
2ea5b7111f67d04f2ccce0f674c531fcca8cd1ad

# Description

You can sting yourself and it is awful
# Steps to Reproduce

Be ling, try to fat sting a nerd in space, fat sting yourself
# What you Expected

To sting them or nothing
# What Actually Happened

Fat stung self

**Comment by ShiftyRail** [comment]
>You can sting yourself 

It's a feature, they even say that when you buy the sting.

**Comment by Exxion** [comment]
Should probably not do it by default though

**Comment by SGuivenne** [comment]
Thats a default sting you dont even buy it
