### ISSUE TITLE
RCD suicide is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19917]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
2ea5b7111f67d04f2ccce0f674c531fcca8cd1ad

# Description

RCD suicide makes you double suicide after deconstructing yourself fails to initiate properly. 
# Steps to Reproduce

Acquire RCD, Suicide with it
# What you Expected

Deconstructing self
# What Actually Happened

Double suicide

**Comment by RealestEstate** [comment]
![untitled12](https://user-images.githubusercontent.com/25192877/46328297-588d1f80-c5bb-11e8-9319-e042ce89ed96.png)
a pic of the phenomena.
