### ISSUE TITLE
Metabuddy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19925]
(WEB REPORT BY: wentafk REMOTE: 172.93.109.202:7777)
# Revision
2ea5b7111f67d04f2ccce0f674c531fcca8cd1ad

# Description
Metabuddy drink seems to have no visible effect
# Steps to Reproduce
Go through process of making metabuddy
Pour into glass
Drink
Make others drink
# What you Expected
Something to happen upon drinking(I believe a HUD icon is suppose to appear?)
# What Actually Happened
Nothing special

**Comment by kilozombie** [comment]
Role datums may have bunked this, I remember it working fine very recently

**Comment by RealestEstate** [comment]
if metabuddy is having issues, then I wonder if any of the other new drinks would too

**Comment by SonixApache** [comment]
@Kurfursten / @Allspice

**Comment by Kurfursten** [comment]
Don't ping me, it's role datum's fault

EDIT: Looked into it, it appears what happened is the icon was deleted out of logos.dmi. Probably like all the other icons that went missing in datums.
