### ISSUE TITLE
Latejoin tator merchants dont get syndie menu

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19928]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
cdeb58b55178ad0ae228087a61bf4a4780d826e7

# Description
Latejoined as Merchant, got a message syndicate didn't have access to aradio even though I have spawned with one

# Steps to Reproduce
Latejoin as burd, pray for antag

# What you Expected
Emags and other things

# What Actually Happened
Cuck'd

**Comment by Kurfursten** [comment]
Turns out this can happen to anyone due to the order of equipping/traitoring for latejoins.
