### ISSUE TITLE
Late-joins get double security (and medical?) records.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#19939]
#### Description of issue

Roundstart people get one (1) security / medical record.
Late-joins get two (2).

#### Length of time in which bug has been known to occur
Recent. Probably role datums.

#### Server revision
29ac5a5bcda7bf03aa7f6900a68a8e08fde966d1

**Comment by SonixApache** [comment]
this would be fine if it weren't for the fact that there is no way to delete records

**Comment by SonixApache** [comment]
was not resolved by  #19946

**Comment by SonixApache** [comment]
A weird thing I noticed: The 'name' field on my record (as a late-join, as seen from the security HUDS) was not my name, but that of a random assistant.

**Comment by Intigracy** [comment]
Was this fixed?

The above PR wasn't actually merged into the SR until 6 days ago.

**Comment by SonixApache** [comment]
Oh.

Yeah, it was fixed.
