### ISSUE TITLE
Can't print cult tomes in library

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19934]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
dc047cf4defee23b291035ad01053be0fa62816a

# Description
Emagged library computer to print false tomes, nothing showed up

# Steps to Reproduce
Emag library PC, try to print, receive nothing

# What you Expected
Cult tome

# What Actually Happened
Got the message it was printed, nothing appeared
"we're getting adminwarnings about them trying to be spawned when there's no cult so I guess not, you might wanna bug report it"

**Comment by RealestEstate** [comment]
a conditional prevents a tome from being spawned without an active cult in ritual.dm, line 265.
I can go ahead and comment it out but I have no idea what the ramifications will be.

**Comment by tayachiya** [comment]
Now that I think about it, it would also destroy the tome that shows up in the black gift box you can find on goonesat. Non-cultists can't use tomes anyway
