### ISSUE TITLE
Inserting Money Into PDA Moves It To Your Hand

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#19930]
It shouldn't do that, like when you slot in an ID, it doesn't try to move it into the hand the ID used to be in

**Comment by Exxion** [comment]
This definitely was not always the case
In fact, I don't think it's the case on my local copy, which is only like a week or two old
EDIT: No, this does not happen on my local copy, which is about six days old

**Comment by BarneyGumball** [comment]
How exactly were you putting the money into the PDA?  I've tried putting money in a PDA in my ID slot, a pocket, my other hand, on a table and inside my bag and the PDA stayed put for all of them.

**Comment by Kurfursten** [comment]
PDA was in the ID slot each time. Note that when the bug occurred each time, I was a player NOT adminning with a spawned PDA.

NOTE: I was not able to reproduce this in the thunderdome with a spawned PDA (NOTE THE THUNDERDOME USES THE CENTCOMM Z2 ACCOUNTS DATABASE!), but giving a real player (botanist) the cash causes the bug when they try to insert the money. Could not reproduce when station power was out due to event (tried 3 times). Bug reproduced when power came back ON. Botanist player already had his ID in PDA before testing.

Tried again with a vox miner and nothing happened for him, tried again with a vox librarian and nothing happened. These players inserted their ID into their PDA for the first time in the shift when I asked them to test.

Tested with bartender ID (trader ID inserted) -- REAL player's ID/PDA but admin test dummy. No bug.

Tested with janitor ID in janitor PDA (test dummy with real player items) - bug reproduced when power was ON but not when power was OFF.

**I strongly believe this bug is tied to the accounts database being active.**

**Comment by Kurfursten** [comment]
Could be related to #19762 ?

**Comment by Exxion** [comment]
I can't reproduce this locally at all. Tested as a naturally-spawned player, both with spawned cash and printed cash, both adminned and deadminned, with the accounts database on, on the normal station.

**Comment by Exxion** [comment]
Ah, never mind. It happens if and only if the PDA window is open.

EDIT:
https://github.com/vgstation-coders/vgstation13/blob/5ec54480ac85135eb6f46e8cd7f7ef001354f2f3/code/game/objects/objs.dm#L293
