### ISSUE TITLE
Issue with Spawn swords/magic

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19936]
(WEB REPORT BY: caboozles REMOTE: 172.93.109.202:7777)
# Revision
29ac5a5bcda7bf03aa7f6900a68a8e08fde966d1

# Description
Wizard spawned swords and magic. Some people didn't get anything.

# Steps to Reproduce
Exist in wizard round, have wizard spawn, not get any sick loot, be a very sad boy.

# What you Expected
To get something from the summoned weapons

# What Actually Happened
Not get anything, watch a vox who also got nothing get killed by someone who did.

**Comment by ShiftyRail** [comment]
It's a feature, actually, much like summon guns, you have a 35% of getting the role.
It was also like this before datums : 
https://github.com/vgstation-coders/vgstation13/blob/4902fef6d0d764dcb2e7ef206e2eba7da17d5c64/code/game/gamemodes/wizard/rightandwrong.dm#L12-L24

**Comment by Blithering** [comment]
The role is to some, but everyone is meant to get a gun/sword/spell

**Comment by tayachiya** [comment]
I am 100% sure that before everyone used to get guns/magic, so you couldn't just meta who was antag and who wasn't

**Comment by ShiftyRail** [comment]
Yeah yoy're right
I misread the file and it'll be fixed soon
