### ISSUE TITLE
Harvester Rune writing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19931]
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 172.93.109.202:7777)
# Revision
cdeb58b55178ad0ae228087a61bf4a4780d826e7

# Description
Harvester rune writing seems to be broken
# Steps to Reproduce
Try beeing a cult harvester and try to scribe runes
# What you Expected
The menu to scribe runes popping up
# What Actually Happened
Nothing really it just set iself on cooldown and that was it

**Comment by ShiftyRail** [comment]
This is fixed @Exxion
