### ISSUE TITLE
Spacepods can partially phase through windows facing away from them

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#19959]
This has always been the case, ever since spacepods were first implemented, but apparently was never reported
This actually applies to any multitile object and any border object, but spacepods and windows (and firelocks) are the only common ones

(It's because `Uncross()` isn't the correct proc to use for this behavior)
(The correct proc does not exist)

**Comment by Exxion** [comment]
I'm a dumbass and `/turf/Exit()` wouldn't work for exactly the same fucking reason as `Uncross()`
OP edited

Anyway the most strictly correct way of doing this (other than switching to pixel movement) would be to lock a dummy atom to the window offset one tile in the window's `dir`, and have its `Cross()` return false for objects moving in that direction
This is obviously idiotic and I'd love to hear any other suggestions

**Comment by Exxion** [comment]
I actually did that in #28857 but other parts of that PR didn't work so it's not in
It worked properly but, as mentioned above, is idiotic
Border objects were just a mistake

**Comment by west3436** [comment]
Implemented in #31154.
