### ISSUE TITLE
Roidstation - Firelock in the minishop near theatre is facing the wrong way.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#19957]
#### Description of issue
![image](https://user-images.githubusercontent.com/26881007/46449116-37156a80-c758-11e8-9704-df227bffe69c.png)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Do you have any idea how hard it is to get plasma out after it gets inside the wall?
