### ISSUE TITLE
Turrets at Centcom fire all game long

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#19960]
![image](https://user-images.githubusercontent.com/7573912/46477405-e00ca580-c7ea-11e8-8294-b9de68078685.png)
Because they're in the same area as that mimic for some reason.

**Comment by iFlashYou** [comment]
Remove the mimic

**Comment by DamianX** [comment]
non-area-based turrets when'st'd've?

**Comment by Exxion** [comment]
Technically a mapping issue at least until turrets are coded to be less awful

**Comment by Shadowmech88** [comment]
Alternatively, could the mimic be added to some kind of Centcomm faction that the turrets would ignore?
I don't know much about how turrets work.

**Comment by DeityLink** [comment]
They seem to no longer fire all the time.

**Comment by DamianX** [comment]
Probably because the mimic moved out of their range, otherwise you should still expect them to shoot 24/7
