### ISSUE TITLE
being turned into a vox as a slimeperson ling, then brought back, only to find no powers but chems and genome

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19964]
(WEB REPORT BY: shadownil REMOTE: 172.93.109.202:7777)
# Revision
b01534b42527c3ad3815baf98946d12a7c2e7fd6

# Description
>ling
>turn self into slimeperson
>go try to pull some shit
>get robusted
>virus turns me into vox in the middle of the chaos
>get pointblank railgun shot by a lucky fucking atmostech
>think I'm done
>somehow someone is reviving my head back at medbay
>am now a vox with a completely new name appearance and everything
>can still use :g to talk with my ally ling, and the small grey box of Chems and Genome count are still there above internals toggle, and my notes and ling objectives are all the same
>but I have no Changeling verbs tab at all

# Steps to Reproduce
>be ling
>turn self into slimeperson with slime toxin from injecting green slime extract with plasma
>get a virus that turns you into a Vox
>get absolutely gibbed to oblivion with a point-blank railgun blast
>get revived through cloning

# What you Expected
THE RUSE TO CONTINUE

# What Actually Happened
No ling powers at all!

**Comment by MadmanMartian** [comment]
so the role datum is still there, but ling powers weren't reformed.

Naicu
