### ISSUE TITLE
Fax timer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19972]
(WEB REPORT BY: jeanvoerman REMOTE: 172.93.109.202:7777)
# Revision
b01534b42527c3ad3815baf98946d12a7c2e7fd6

# Description
Transmitter arrays realigning. Please stand by for 84960.8 seconds.

# Steps to Reproduce
Try sending a fax I think?

# What you Expected
Sending a second fax

# What Actually Happened
24 hours cooldown

**Comment by tayachiya** [comment]
Could be a problem with roidstation IAA fax only, fax on the bridge itself is 90 seconds

**Comment by DamianX** [comment]
midnight rollover?
