### ISSUE TITLE
Windows won't load

### ISSUE THREAD

**Issue by crumplehat** [d3athrow/vgstation13#19974]
#### Description of issue
Opening a window, like the character setup window (specifically when trying to get to Load Profile), the window that comes up won't actually load anything, will result in a spinwheel and a blank, white window. Happens also with the jukebox window and the instrument box. The latter actually worked for a while but then stopped loading after trying to import a new song, and wouldn't load anymore afterward.

Issues seem isolated to this server (briefly ducked into another one to test on the load profile windows and didn't get any issue, but it's possible it could have happened if I'd kept trying long enough, considering the instrument window). Happened before I'd updated Byond (hadn't played in a few months) and continues to happen afterward. Can only get beta version to start, stable tells me dreamseeker is outdated but it tells me to use the download link from the byond website, which is just the usual updater, and gives me the same message while attempting to connect to the server.

#### Difference between expected and actual behavior
Usually the stuff in the windows would just load, like a web page. It's more like they're just frozen now. Doesn't always result in a spinwheel by my cursor but it gives up on empty whiteness. I've had on rare occasions windows like this not quite load and give me an actual "Could not load page" message, but I can't remember clearly enough if that was an older version of byond and if things still work that way.

#### Steps to reproduce 
Just opening any of the stated windows. Sometimes they work briefly but opening sub-windows (like trying to load a profile from the setup menu) seems to be the more consistent problem. And I guess when it happens once it just keeps happening with all the others.

#### Specific information for locating
That's about all I know? I've tried restarting and reconnecting but only ever get brief relief. Game functions fine otherwise, and knowing how finicky my connection can be sometimes it doesn't seem to have anything to do with that (I'm moving normally and also didn't seem to get the problem on another server). I don't know HOW it could be isolated to this server, but it seems to be.

#### Length of time in which bug has been known to occur
Today, since I started playing again a couple of hours ago. EDIT: about 9:30 to at least 11:15ish.

#### Server revision
Game: cce2e35f8a4ce2cfe7dafba3a00fac908764c174 
Patches: f88539d92a2ab37192c3eba0705b68ac74bd2dab 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by DamianX** [comment]
Remarkably thorough report but you forgot to mention your exact BYOND version. Can you try [512.1448](http://www.byond.com/download/build/512/)?

**Comment by crumplehat** [comment]
Version I had was 512.1450. Installed 1448, connected to the server, tried selecting setup character, didn't even get a reaction. I thought the game was freezing or the connection was dying, kept reconnecting. Tried Join Game out of frustration, still no reaction. In more frustration, tried Observe, and was about to close the window when it actually brought up the dialogue about whether I was sure. Soon as I accepted, it put me in the game like usual but all the windows that hadn't opened before came up at the same time. Tried to monkey with them a bit by opening the General Settings window from the Settings drop-down menu up top, same with the Special Roles, but got the window issue again.

If it's related, Dream Seeker crashed at one point after I clicked Join Game, but I was also trying to reconnect a few times over again so that might not be related, but I figured I'd include it since it's marginally possible it's related to that weird thing about it saying Dream Seeker was too outdated for Stable even using the official updater.

EDIT: Continued trying to bring up the windows, the special roles and settings, they're coming up now. Didn't do anything different, just working now.

> Remarkably thorough report but you forgot to mention your exact BYOND version. Can you try [512.1448](http://www.byond.com/download/build/512/)?

**Comment by DamianX** [comment]
Have you tried connecting to the test server? `byond://ss13.moe:1337`

Also if dream seeker crashed you should find the log in windows' "event viewer" and report it to the BYOND forums, not much we can do about client crashes unfortunately.

**Comment by SonixApache** [comment]
It's pretty common for buttons to not work when you've just connected to the server, I get the same issue.
If stuff still doesn't work after a minute or two it's definitely busted.

**Comment by Exxion** [comment]
@crumplehat The stuff in your comment sounds like resources aren't finished downloading. Right click the title bar. Click Options & Messages. If you see a loading bar, you're still downloading resources, and everything being fucked is expected until that's done. If it persists after loading is finished, then there are problems.

**Comment by crumplehat** [comment]
Still getting the issue. What governs what shows up in windows like the Jukebox window and the setup window and so on? The game's running perfectly normally otherwise, just that these windows freeze up and won't load.

**Comment by crumplehat** [comment]
Issue seems to have been resolved. After the last server update it seems clear now. Thanks, guys.

**Comment by Exxion** [comment]
Your cache was probably corrupted or something, and thanks to how the CDN works, any update to any resource file makes you redownload all assets
Have someone reopen this if it comes back.
