### ISSUE TITLE
False walls being very obvious, no mesons.

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#19981]
![image](https://user-images.githubusercontent.com/16896032/46531977-8a1b2900-c8e2-11e8-90b8-47d4626bfb42.png)

**Comment by MadmanMartian** [comment]
@DeityLink you did something with smoothwalling recently didn't you?

**Comment by DeityLink** [comment]
nothing that should have changed that.
![image](https://user-images.githubusercontent.com/7573912/46536287-4e666c00-c8ae-11e8-98fa-cd389697563e.png)
After testing the issue seems to only occur with fake reinforced r_walls
