### ISSUE TITLE
Please Update the Wiki to Include New Deities

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#19986]
#### Description of issue

The word of Mr. Clean, Brian Damag, Shitcurity/Beepsky, and Anime must be spread.  

In all seriousness the page is outdated as hell and can use quite a bit of work, I'm happy to do it but I'm not sure how wiki update proposals work.

**Comment by Kurfursten** [comment]
Anyone can update the wiki, there is no need to propose anything

**Comment by Irradiation** [comment]
There's no proposals. Just make an account and press Edit Page.

**Comment by SGuivenne** [comment]
Welp.  

EDIT: I thought that was the damn cancel button what the hell.

**Comment by west3436** [comment]
The wiki entry is [pretty exhaustive](https://ss13.moe/wiki/index.php?title=Chaplain#Religions) - if entries are still missing please add them yourself.
