### ISSUE TITLE
the pastry is a lie

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19987]
(WEB REPORT BY: relegated REMOTE: 172.93.109.202:7777)
# Revision
2d801c6367e0a9a0187098f6721c443ae47e0c2b

# Description
donut box on asteroid has full icon state but is empty and acts weird when you add donut
# Steps to Reproduce
go to asteroid
check donut box on kitchen counter
put junk inside
# What you Expected
donuts in full box
# What Actually Happened
literally unplayable game breaking bug

**Comment by ShiftyRail** [comment]
This is a recurring problem with most of the pre-mapped food items on roid
Including the bananas in maint, they don't real and disappear on pickup

**Comment by coldcola** [comment]
literally unplayable.

**Comment by GeneralVeers25** [comment]
Closed by one of the recent bug fixes, #20094 I believe.
