### ISSUE TITLE
can't cancel out of paper UI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#19997]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)
# Revision
2d801c6367e0a9a0187098f6721c443ae47e0c2b

# Description

# Steps to Reproduce
writing on paper, paper gets taken away midway, press cancel and it says:
"Please ensure your pen is in your active hand and that you're holding the paper." and reopens the menu
# What you Expected

# What Actually Happened

**Comment by Shadowmech88** [comment]
Could not reproduce. I got that message, but the menu did not reopen.
