### ISSUE TITLE
Having 16Kpa internals regularly flashes the O2 warning and suffocates you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20003]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
1d2d2d736ae2fb8eccf9aebf9a50806bdcb22662

# Description
Happens regardless of outside atmos, only persists for a couple of seconds or so before going back to normal

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Sounds like you fucked up your lungs

**Comment by Exxion** [comment]
🤔 
I just fixed this a few days ago
I'll go check again

**Comment by Exxion** [comment]
Wait no 16kPa is exactly the minimum allowed oxygen level
I don't care if it complains for a couple seconds then

EDIT: Yeah this is probably just floating point error or something
It does exactly nothing other than deal 1 oxy damage occasionally
(You heal 5 per tick it doesn't happen)

**Comment by DamianX** [comment]
17 is the new 16
