### ISSUE TITLE
Roundstart Skeleton and skeleton vox dont move faster until you get cloned.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#20000]
#### Description of issue
A roundstart skeleton vox is the same speed as a human and isn't fast like their human skeleton counterparts, however upon getting cloned you will gain the speed bonus.

#### Difference between expected and actual behavior
Being fast all the time instead of having to get cloned to get my speed boost.

#### Server revision

Revision: 2d801c6367e0a9a0187098f6721c443ae47e0c2b 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Dacendeth** [comment]
Actually upon playing a normal skeleton roundstart they dont seem any faster than humans either?

**Comment by Shadowmech88** [comment]
Poor use of the #20000 get.

**Comment by SonixApache** [comment]
>#20000 get is skelenigger related

gitgod is dead

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/65877243-21318a00-e359-11e9-9e11-dfa4892d966f.png)
still happening today.
