### ISSUE TITLE
Skeletal vox can't be traders

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20012]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
98ca78c6a1f8cc9f87798d1c6fd9e4ab2bbcd493

# Description
Skeletal vox cannot be traders
# Steps to Reproduce
change race to skeleton vox and be locked out of trader
# What you Expected
To be a trader skeleton
# What Actually Happened
Unable to be a trader skeleton

**Comment by Kurfursten** [comment]
Not a bug

Trader skeletons can't be a thing because
>Not wearing a suit (if they were it would hide their spooky sprite so what's the point) so they can't latejoin
>Impact of being thrown from space when latejoining would probably wreck their skeletal asses
