### ISSUE TITLE
Legacy Cult: Making ghosts visible no longer gives out a message that you did

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#20010]
#### Description of issue
On the tin. Involves using the "See Invisible" rune to see ghosts and using a tome on them to make them visible to the living. Minor feature loss since datums.

#### Difference between expected and actual behavior
For a message about you dragging the ghost to the world of the living to show up.

#### Server revision

98ca78c6a1f8cc9f87798d1c6fd9e4ab2bbcd493 
3fb5a0e5a47e3d0e13a9fdeee420c851212d002c 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
Cult 2.0 is ded
