### ISSUE TITLE
Being cloned and/or getting Staff-of-Change'd makes you lose all your spells

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20028]
#### Description of issue
title
i feel like spells are tied to the body rather than the mind for some reason

#### Difference between expected and actual behavior
be crewman with book magic
get turned into a martian | get killed and cloned
retain spells
vs
be crewman with book magic
get turned into a martian | get killed and cloned
lose all spells

#### Length of time in which bug has been known to occur
at the latest since role datums, though no specific time

#### Server revision
d9cb1d08d578e7d63f29e8d681386e438000faf0

**Comment by Shadowmech88** [comment]
I asked about this in Discord, and was told that no mobs, including wizards, are intended to keep their spells after cloning.
Not sure about staff of change, though.

**Comment by AI-Is-Rogue** [comment]
#18461 for SoC
And I distinctly remember being cloned and keeping my spells a while back after the CMO cloned me and gave me a new identity for some unholy reason.

**Comment by Exxion** [comment]
@Shadowmech88 But that's wrong, unless it was changed with role datums for some reason.
The spells belong to the mind but are used by the body, and so they have to be re-added properly, but aren't always

**Comment by DamianX** [comment]
No, you were never able to retain your spells after cloning.
Spells used to be stored in the body of the wizard. In fact, it was relatively common to headswap their corpses with crewmen to give said crewmen access to spells.
That said, I don't know if it was a bug or a feature and I don't care about it being changed either.

**Comment by Exxion** [comment]
Apparently they used to belong to the mind but that was commented out at some point

**Comment by strawberrytan** [comment]
I've never actually seen anybody but myself do the wizard magic body hijack but it is fun
