### ISSUE TITLE
Can Bind users catch a break?

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#20023]
The base cost of bind is 20 and the upgrade cost is also 20. If you want to bind any advanced things, like computers or machines you have to shell up 40 points. Bind is also limited to where you can't bind atmospheric machinery, including gas miners and cryogenic tubes, where push isn't even affected by such a limit at half the cost. The suggestion here would be to decrease the upgrade cost by 10, making it so if you want to use the bind spell for machinery it would only cost you 30 instead of 40. While this would still leave you with 3 other 20 cost spells one of the few 10 cost spells or lesser options would fill this gap making this cost reduction not a major buff to bind.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
dude shard lmao

**Comment by RealestEstate** [comment]
should upgrade for more bind slots

**Comment by Killette2** [comment]
> dude shard lmao

If you like radiating yourself and playing with fire sure. I've even brought up the idea of making the shard unbindable for this change

**Comment by Exxion** [comment]
>push isn't even affected by such a limit at half the cost

That's really more of a problem of push being OP as hell

**Comment by Caboozles** [comment]
Isn't shard affected by basic binding? Or was that changed. Because I know binding shards worked for basic  spellcost a while ago.

**Comment by RealestEstate** [comment]
I just want to say that I really love bind and this PR will make bind cheaper and that is good.
