### ISSUE TITLE
Duplicating Protolathes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20020]
(WEB REPORT BY: avadanatinde REMOTE: 172.93.109.202:7777)
# Revision
2ab6cf8530112673a7102821d22fe40a4d0893a9

# Description
I went to make a protolathe and circuit printer on the mining outpost layering the machine frames in 1 tile as i normally do. I accidentally put them in the wrong order so that the protolathe occluded the circuit printer so i went to deconstruct them. 

The boards and parts came out, but a protolathe still existed at the same spot, along with a newly spawned machine frame.

When you move the parts from the protolathe you just took apart and put them somewhere else and try to deconstruct the protolathe that is still there the parts teleport to the old spot and the protolathe still exists and a new machine frame spawns.
# Steps to Reproduce
Get RnD Kit
Go to Mining outpost, make two machine frames on a single tile
Build these machine frames into a protolathe and a circuit printer, layer them so the protolathe is on top.
Screwdriver the lathe open, crowbar the contents out.
The contents will come out, the protolathe will stay, and a new machine frame spawns.
# What you Expected
To be able to deconstruct the protolathe without an infinite duplication glitch.
# What Actually Happened
An infinite duplication glitch.

**Comment by DamianX** [comment]
Fixed, I'm sure
