### ISSUE TITLE
Light Fixture in Asteroid Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20025]
(WEB REPORT BY: avadanatinde REMOTE: 172.93.109.202:7777)
# Revision
de60b5d8ea7d075f89f23319869bcfca20dfdffd

# Description
Cannot disassemble Light fixture left of the Cargo Bay APC.
# Steps to Reproduce
Smash light
Remove Broken light tube
Try all manners of tools including Wrench, Screwdriver, Wirecutters, Crowbar, Welder, etc to remove the wires from this light fixture
Fail at removing the wires from the fixture.
# What you Expected
To disassemble this light.
# What Actually Happened
I can't disassemble this light.

**Comment by GeneralVeers25** [comment]
I've done some testing, and this appears to be the case on all maps, not just Roidstation. You can no longer just wirecutter the wires out.

**Comment by DamianX** [comment]
should be fixed by #20071
