### ISSUE TITLE
MMIs (and posibrains) inside borgs get EMPed when their shells get EMPed

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20037]
#### Description of issue

Shoot borg with ion rifle -> MMI inside starts making noises
This should not be happening.
![screamingMMIs](https://user-images.githubusercontent.com/8468269/46634989-221f4980-cb53-11e8-894d-cf1debcbd827.png)

#### Length of time in which bug has been known to occur
Less than a year. Yeah, helpful. Probably since the emote rework?

#### Server revision
1b428644bfaeeab52d01cfb69fcddaaf7ded7448

**Comment by DamianX** [comment]
@ShiftyRail

**Comment by ShiftyRail** [comment]
I am away until Sunday but I'll take care of this
