### ISSUE TITLE
Exosuit Logging: Furshit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20033]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
d9cb1d08d578e7d63f29e8d681386e438000faf0

# Description

"Attack by hand/paw. Attacker - Gabriel Lowe."

Whenever someoen does a physical attack on the mech via punching it it states hand/paw.  No Furries plz.
# Steps to Reproduce

Be in mech, get punched, actually read the logs
# What you Expected

Attack by hand. Attacker - Gabriel Lowe.
# What Actually Happened
Attack by hand/paw. Attacker - Gabriel Lowe.

This is furshit

**Comment by Exxion** [comment]
The best part is that they're separate procs. They could be logged separately

Also just say "unarmed attack"

**Comment by tralezab** [comment]
what coders type: well the monkey attack hand is the same as the human attack, so we'll just move the logging onto the attack hand proc for both

what players think: WHAT FURRY CODED THIS

THIS IS FURSHIT
