### ISSUE TITLE
Martians do not recover eyesight from being uncouncious

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#20040]
#### Description of issue
As the titles says.

#### Difference between expected and actual behavior
To regain my eyesight, instead I wake up permanently blind. May be related to #18953 which is a few months old by now, but my hearing remains just fine.

#### Steps to reproduce 
Be a Martian and go to sleep by any mean, wait to wake up and become blind. I'm aware that this issue is happening to plenty of uncommon player-controlled mobs from reading another post. I had this happen to me about a week ago when I was turned into something else but I can't quite recall what.

#### Server revision

1b428644bfaeeab52d01cfb69fcddaaf7ded7448 
3fb5a0e5a47e3d0e13a9fdeee420c851212d002c 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Kurfursten** [comment]
I suspect it is related to that other bug as you say.
