### ISSUE TITLE
Vampire dissolve into bats is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20058]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
5ec54480ac85135eb6f46e8cd7f7ef001354f2f3

# Description

One of the vampire abilities lets them dissolve into mist form and leave bats behind.  On the server it works, but then it immediately despawns the bats.  This is weird as shit.
# Steps to Reproduce

Be vampire, mist form
# What you Expected

Bats
# What Actually Happened

Bats for like half a second

**Comment by ShiftyRail** [comment]
The issue here is that the animation doesn't fit. It's not really a bug.
Mist/bat form is not supposed to be "traceable".

**Comment by SGuivenne** [comment]
bat form is supposed to drop bats, it says so in the description.  It traditionally also HAS dropped bats.  If its not doing it now its a bug.

**Comment by ShiftyRail** [comment]
Oh, I didn't understood. I'd call it a feature loss more than a bug.

**Comment by SGuivenne** [comment]
can't you tag that for it if you'd call it that? I dont actually know how that works

**Comment by SonixApache** [comment]
It's feature loss / bugfix

**Comment by DeityLink** [comment]
I think that whoever turned the verbs into spells accidentally linked the jaunt icon to the deprecated Mist Form spell instead of Bat Form. The bats that appear are part of the vampire's jaunt animation, and no bats actually spawn.

**Comment by SonixApache** [comment]
[Common misconception]
