### ISSUE TITLE
Blood Vendor not vending

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20056]
(WEB REPORT BY: avadanatinde REMOTE: 172.93.109.202:7777)
# Revision
5ec54480ac85135eb6f46e8cd7f7ef001354f2f3

# Description
The blood vendor in box at least does not let you take blood bags out of it
# Steps to Reproduce
try to vend anything from the blood vendor
# What you Expected
to get blood vended
# What Actually Happened
it won't vend blood bags

**Comment by Irradiation** [comment]
Were all blood types borked or was it only a specific blood type?

**Comment by Irradiation** [comment]
Well, I tested it. Something broke the bloodbank vend hardcore.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Dupe of #20196 which has more info
