### ISSUE TITLE
Feature Request: Heroin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20063]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
5ec54480ac85135eb6f46e8cd7f7ef001354f2f3

# Description

Weve already got Plant Opium and Plant Cocaine, its logical in progression that we should be able to make heroin out of the opium.

**Comment by Irradiation** [comment]
And what do you propose the effects should be?

**Comment by SGuivenne** [comment]
Probably some kind of brute damage reduction and completely removing pain latency at the cost of brain and liver damage that gets progressively severe scaling with the dosage.
