### ISSUE TITLE
Baster Weirdness

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20066]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
b52283d78d341c1326705bf492fd0cc8e67af041

# Description
Attempting to use a baster on yourself while empty does weird stuff
# Steps to Reproduce

Get baster, apply on self
# What you Expected

No clue
# What Actually Happened
You can't, the baster is closed.

That doesn't make much sense.

**Comment by SGuivenne** [comment]
Applying it with reagents gets even weirder 

[name] squirts something into [Name] eyes!

You can't, the baster is closed.

This seems like sloppy coding

**Comment by Eneocho** [comment]
Can't reproduce, seems to be fixed.
