### ISSUE TITLE
Putting a / in the Pill Name box in the chemmaster does weird shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20061]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
5ec54480ac85135eb6f46e8cd7f7ef001354f2f3

# Description

Putting a / in the chemmaster for pill name ( I.e. "KeloDerm 5/5") will cause the pill to not dispense and it to fail to register that chemicals have been lost, however if you take the beaker out it'll show the chems are missing.

# Steps to Reproduce

Get chemicals, put a / in the thingy, watch the fireworks
# What you Expected

it to work
# What Actually Happened

Fucks shit up

**Comment by Exxion** [comment]
Sounds suspiciously runtimey

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Sounds suspiciously Topic()al rather

**Comment by DamianX** [comment]
Sounds suspiciously like #20056
I'm calling it
BYOND bug

**Comment by SGuivenne** [comment]
Edit: Its definitely got the \ symbol and at least one other symbol I havent narrowed down (spamming all of them except knowns definitely triggered one weird shit similar but I couldnt identify it).  On the bright side, the fact its so fucked means HTML inject attempts are completely nonfunctional as are much of the arbitrary code stuff.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Also
>fail to register that chemicals have been lost, however if you take the beaker out it'll show the chems are missing.

This is just you ejecting while the reagents are in buffer you dummy

**Comment by SGuivenne** [comment]
RIP.  Also this is a feature?  How the fuck did I manage this level of autism to discover this where nobody else has.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I tried giving it a more lax filter but discovered another gamebreaking bug in the process honk
