### ISSUE TITLE
Suit Storage Emag no longer works

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20089]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
ea4c1e3ae0fae12e948da174e800410a68b1c5f4

# Description

Space suits used to be emaggable and able to high energy irradiate people inside of, it appears that no longer works
# Steps to Reproduce
Attempt ot emag space suit storage
# What you Expected

It to work
# What Actually Happened

Didnt

**Comment by AutismSpider** [comment]
its done by screwdriver now i  think

**Comment by Exxion** [comment]
I'm not seeing any evidence it was ever emaggable
At least not in the last three years
As far as I can see, it's always been done with the screwdriver

EDIT: Yeah it has always been done with the screwdriver
It was never emaggable

**Comment by SGuivenne** [comment]
Welp, in that case you can close this one
