### ISSUE TITLE
Vampire bug (it's loose)

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#20086]
#### Description of issue
Vampires can accumulate multiple cheat death charges

#### Difference between expected and actual behavior
Expected: use cheat death, cheat death once

Actual behaviour: hit cheat death three times during cheat death's effect time and receive three cheat death action button abilities that fullheal on activation

#### Steps to reproduce 
Die, hit cheat death more than once, wait for the queued cheat death's to complete

#### Length of time in which bug has been known to occur

No idea

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ShiftyRail** [comment]
Nice one

**Comment by Killette2** [comment]
It's a feature. You're cheating cheating death. Also known as the pumpkin eater effect
