### ISSUE TITLE
Animations Showing at improper times for objects

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2008]
This is for two particular objects that I have noticed have this issue, 
-Shield Generator (the type that starts in left side of engineering secure storage)
-Doors already removed by Narsie's cultification

When you move your screen into range of viewing them very quickly, they play their animations (shield powering down and door cultification). Despite already having that effect (depowered, cultified).

To reproduce ghost and use click teleporting to get into sight range, and the animation will often play unecessarily.

**Comment by ComicIronic** [comment]
Can't reproduce the door bug locally.
Is this still an issue?

**Comment by clusterfack** [comment]
Yes, it happens universally. If you move around as an observer (i.e. very quickly) after narsie has been summoned you should undoubtedly see it occurring.

**Comment by clusterfack** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8516830/6764322/d31b1892-cf79-11e4-9f78-1608e7f1c109.png)

Here is a screenshot of the issue in action. It's pretty hard to get the full effect in a screenshot because the animation time is only about a second. But you can see the doors on the right displaying it.

**Comment by Exxion** [comment]
Does this still happen? I haven't noticed it but that doesn't mean anything

**Comment by clusterfack** [comment]
Yes, it occurs because of the way animated icon states work. When you move far enough away from something with an animated icon state that doesn't repeat (i.e. occurs once and stays that way), your dream seeker client will forget that it saw it. So when you move back into range of it (quickly enough so that you don't miss it), the animation reloads from scratch in your client so it plays again.

**Comment by Exxion** [comment]
What a fuck

**Comment by clusterfack** [comment]
This still happens you fucking nerds

**Comment by gbasood** [comment]
Maybe so but what hte fuck can we do about it if it's a BYOND bug?

Should we really keep an issue open on a bug that can't be solved?

**Comment by Exxion** [comment]
All the other ones you closed also still happen by the way and are, in theory, fixable, though probably nobody ever will because they are so minor and fixing them would be difficult

**Comment by gbasood** [comment]
None of the ones labeled `T-Thanks BYOND` that I closed should have been fixable issues.

**Comment by Exxion** [comment]
The Z-wiggling? Pretty sure it happens because everyone has the same layer, so if you randomize everyone's layer between the normal layer and the normal layer + 0.1 or something, it would probably fix it.

**Comment by gbasood** [comment]
Z-wiggling occurs on ANY atom, not just carbons. So you'd have to randomize layer on EVERY layer change, not just atom creation. Would be an extensive rewrite for a small visual annoyance.

**Comment by Exxion** [comment]
Exactly why I said nobody would fix it

**Comment by DrCelt** [comment]
Blame @PJB3005
