### ISSUE TITLE
Killed by rads in maint on Deff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20084]
(WEB REPORT BY: discotau REMOTE: 172.93.109.202:7777)
# Revision
ea4c1e3ae0fae12e948da174e800410a68b1c5f4

# Description
ran into maint and died nearby chapel
# Steps to Reproduce
go into maint near chapel/library during rads 
# What you Expected
to survive
# What Actually Happened
slow death

**Comment by Gringonius** [comment]
Literally a feature. The station is meant to be shitty. #9382

**Comment by Exxion** [comment]
As the age-old saying goes, "IT'S NOT MAINT"

**Comment by strawberrytan** [comment]
to add to this I was actually hacking APCs and turning breakers off and I definitely hit up escape areas' APCs before that radstorm happened
