### ISSUE TITLE
Syndicate traitor not receiving uplink

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#20098]
#### Description of issue
Join game as botanist alt title gardener, mission specifications decrypted but not provided an uplink code, check notes and it is not there either

Talked about it later and other people reported similar occasional no-uplink problem but I have not seen an issue for it

#### Difference between expected and actual behavior
Expected: Syndicate traitor receiving uplink
Actual: Given traitor objectives on latejoin as an alt-title botanist but after the autotraitor text there was another string in red that said something along the lines of "unfortunately the syndicate could not provide an uplink this time"

#### Steps to reproduce 
I don't know, maybe it's something to do with latejoining, alt title jobs, or botanists?

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by strawberrytan** [comment]
Logs (http://game.ss13.moe/logs/2018/10-October/10-Wednesday.log)

> [07:20:56]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">DYNAMIC MODE: Chance of injection with the current player numbers and threat level is...50%.</span></span>
> [07:20:56]ADMIN: DYNAMIC MODE: Chance of injection with the current player numbers and threat level is...50%.
> [07:20:56]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">DYNAMIC MODE: Check passed! Looking for a valid ruleset to execute.</span></span>
> [07:20:56]ADMIN: DYNAMIC MODE: Check passed! Looking for a valid ruleset to execute.
> [07:20:56]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">Strawberrytan/(Strawberrytan) joined the station, and was selected by the <font size='3'>Syndicate Infiltrator</font> ruleset.</span></span>
> [07:20:56]ADMIN: Strawberrytan/(Strawberrytan) joined the station, and was selected by the Syndicate Infiltrator ruleset.
> [07:20:56]DEBUG: Runtime in <b>dynamic_stats.dm</b>, line <b>29</b>: <b>Cannot read "Syndicate Infiltrator".name</b> <a href='?_src_=holder;viewruntime=[0x2111f7f1]'>[view]</a>
> [07:20:56]DEBUG: Runtime in <b>whitelist.dm</b>, line <b>64</b>: <b>Cannot execute null.conditional whitelist().</b> <a href='?_src_=holder;viewruntime=[0x2111e879]'>[view]</a>
> [07:20:56]ACCESS: Logout: *no key*/(Strawberrytan) (start area - 8,81,2)
> [07:20:56]ACCESS: Login: Strawberrytan/(Lanaya Reed) from [NOPE] || BYOND v512
> [07:20:56]ADMIN: (strawberrytan/) started the game as a Gardener.
> [07:20:57]EMOTE: Ian/ (@289,197,1): 
> [07:21:01]EMOTE: Osman Khebula/Eerjunic (@260,251,1): giggles.
> [07:21:05]EMOTE: Osman Khebula/Eerjunic (@260,251,1): twitches violently.
> [07:21:08]SAY: Lanaya Reed/Strawberrytan (@@157,251,1) As Galactic Common : Hey buddy
> [07:21:13]SAY: Lanaya Reed/Strawberrytan (@@157,251,1) As Galactic Common : Do you want a ride?
> [07:21:13]EMOTE: Osman Khebula/Eerjunic (@259,249,1): giggles.
> [07:21:13]EMOTE: monkey (959)/ (@376,236,2): jumps!
> [07:21:13]EMOTE: monkey (115)/ (@274,196,1): jumps!
> TOPIC: "status", from:[IP CENSORED], master:, key:
> [07:21:27]EMOTE: monkey (873)/ (@270,197,1): scratches.
> [07:21:33]EMOTE: monkey (779)/ (@277,299,5): jumps!
> [07:21:35]EMOTE: monkey (860)/ (@277,298,5): waves his tail.
> [07:21:52]SAY: Lanaya Reed/Strawberrytan (@@184,250,1) As Galactic Common : Eh?
> [07:21:59]EMOTE: monkey (860)/ (@276,299,5): jumps!
> [07:22:13]EMOTE: Ian/ (@290,199,1): 
> TOPIC: "status", from:[IP CENSORED], master:, key:
> [07:22:17]WHISPER: Strawberrytan/(Lanaya Reed) (Locker Room - 185,246,1): No uplink, that's a shame
>

**Comment by DeityLink** [comment]
Alright, I'll fix that one
