### ISSUE TITLE
Multiple vampire bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20108]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
daf2a41526ee54c7a3aa23a9ba26935152244d0b

# Description
Started the round with 2 copies of glare, hypno and rejuv
could succ with mask on (not consistent across all vamp spells, cant thrall with it)
The vampire sight buffs kept flickering on and off depending on how much useable blood i had
thralls listed twice on the end round screen, counted as success despite the fact I got dunked on

**Comment by ShiftyRail** [comment]
Was this on dynamic mode or secret->vampire ?
I know for a fact that every oldstyle gamemode spawns two copies of the vampire, but dynamic shouldn't.
