### ISSUE TITLE
Defficiency - Recharging in adv robotics changes sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20113]
(WEB REPORT BY: autisticmouse REMOTE: 172.93.109.202:7777)
# Revision
daf2a41526ee54c7a3aa23a9ba26935152244d0b

# Description

Not sure why, but i went from the Landmate model of engiborg to a completely different model after emerging from the first charging station.

# Steps to Reproduce

Choose landmate engiborg and go into the recharging station near AI core

# What you Expected

To still be the landmate

# What Actually Happened

I became something else entirely

**Comment by DamianX** [comment]
Local server, roundstart cyborg, picked engineering, picked landmate sprite, entered the charging station to the entrance of the AI upload, kept my landmate sprite.

**Comment by kot-blini** [comment]
autisticmouse here, sorry it looks like i was being trolled

[16:57:47]ADMIN: Jknpjr/(Grey Stoke) modified ROUGE's icon to robots.dmi
[16:57:47]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message"><a href='?priv_msg=[0x5000004]'>Jknpjr</a>/(Grey Stoke) modified ROUGE's icon to robots.dmi</span></span>

**Comment by DamianX** [comment]
admins, not even once
