### ISSUE TITLE
Amazing bug with the high-frequency machete

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20122]
(WEB REPORT BY: jubisloviu REMOTE: 172.93.109.202:7777)
# Revision
f774a274a2aed950cacbaac4e2a522c853c5389d

# Description
-Turn on the high frequency machete
-get nullspaced as soon as a vine pulls you because you delete vines in your tile

**Comment by MadmanMartian** [comment]
which absolute [car horn] had it so that an objects forcemove also forcemoves things attached to it?

**Comment by SGuivenne** [comment]
Hey, I'm curious if this has anything to do with the spiny skin bug I had where I killed a holo carp using the skin spines and got nullspaced by it.  Could be a similar proc.

**Comment by jknpj** [comment]
This is JoJo-tier antics

**Comment by veles2001** [comment]
Confirmed in d5a1a1f

**Comment by SGuivenne** [comment]
this is probably older, Hi Freq machetes dont get used much and when they do they generally arent used with kudzu on the map

**Comment by Exxion** [comment]
@MadmanMartian But it *should* do that
