### ISSUE TITLE
Spacewalking Seems To Be Vision Based

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#20138]
I noticed this when I was testing something else locally.
If you're spacewalking around the outside of a structure, and the wall turfs on the edge are at their maximum level of darkness (due to there being no light inside the structure, for example), you won't be able to "grab" or walk alongside the turfs. It will be as though they don't exist.
This can lead to odd behavior such as turning off your helmet light mid-spacewalk causing you to suddenly begin drifting despite still being next to the wall, simply because you can no longer see the wall.

It can be avoided by carrying any kind of light source, even a PDA light, to light up the turfs around you, but if you don't have a light source you'll have to throw things to move around the outside of the asteroid and vaults and such.

**Comment by Pathid** [comment]
Same as #18114?

**Comment by Shadowmech88** [comment]
It seems so.
