### ISSUE TITLE
Projectiles No Longer Go Through Portals

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#20141]
Tested with both bullets and lasers. If you fire past the portal, the projectile ignores it. If you fire at the portal, the projectile collides with it and stops there. It never comes out of the other portal, though.

**Comment by Exxion** [comment]
#20096 
Turns out it was always a bug

**Comment by Shadowmech88** [comment]
Wew, fix one thing and break another.

**Comment by Shadowmech88** [comment]
Is there any reason to disallow anchored objects of any kind from going through portals? If they can't move, they can't enter the portal, and if they can move, they can move, so why not let them go through a portal?
