### ISSUE TITLE
Natural antibodies

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20147]
(WEB REPORT BY: kyunny REMOTE: 172.93.109.202:7777)
They're the most broken part of virus feature and it basically makes beneficial viruses pointless. This is already besides the fact that malignant viruses are weak as shit compared to the effort it takes to get rid of them even without the natural antibodies.

**Comment by CptWad** [comment]
honestly viruses in general are bad
they exist to allow a specific job to exist which rewards players for fucking off for two hours alone just to invent some "beneficial" virus that usually just gets cured by other doctors actually doing their job healing people

**Comment by Hoshi-chan** [comment]
I like virologist's coat and satchel, but hate the job. Virology and viruses have desperately needed a complete overhaul for a long, LONG time. It's always felt to me like all the virus effects could just as easily be genetic abnormalities, or vice versa. Maybe merging the two professions somehow is the answer, but I dunno.

Beneficial viruses are stupid, releasing viruses as an antag is on par with a plasma flood in terms of manageability for the average spessman (that is to say, not fun because there's no real interaction, just death), and so the only thing you can really do as a virologist is spend 15 minutes getting antibodies and curing all viruses forever, then become a regular doctor with a dope green labcoat.

EDIT: Also, in regards to the topic in the announcement, they should probably cure over time on their own. If you make that change though, you should probably at least partially revert the burst of damage caused by radium curing a virus. It was meant to counter a self-curing meta, which won't be such a big deal if there's a greater chance that they'll cure on their own.

Besides, even if there's a virologist, instead of people storming chemistry for radium, they now storm virology to try to cure the virus themselves, so I don't get why the fuck that change even stuck.

**Comment by ghost** [comment]
Not every antag virus causes death. There are some fun ones like anime hair and random languages.
Your hatred for viro is irrational.
Also, making a virus regardless if its beneficial or not doesnt take more than half an hour.
The idea of virology is good, it's the implementation of that idea that's bad.

**Comment by Durgen** [comment]
> Beneficial viruses are stupid, releasing viruses as an antag is on par with a plasma flood in terms of manageability for the average spessman (that is to say, not fun because there's no real interaction, just death)

@Hoshi-chan the chad greyshit breaks into chemistry and cures himself using punpun, so he can go back to AFKing in the bar without the sniffles. The virgin wagie spaceman quarantines himself in his department to patiently wait for a cure that never comes, eventually turning into a catbeast at 14:05 and getting murdered by the mime.

**Comment by SirSkeleto** [comment]
>implying there are antags who like fun on /vg/station, not ones who will just opt for fastest kill every time

**Comment by Killette2** [comment]
I've hated this feature forever. Fuck self curing viruses. Another buff viro needs is being able to tell when the stats of a virus, like the verocity or strength change. Currently the machine only makes noises when a virus changes its effects, but never when the stats adjust. It's incredibly annoying if you ever want to make a virus stronger, you have to play a random guessing game of checking the oven.

**Comment by Kammerjunk** [comment]
natural antibodies no
virology overhaul yes

**Comment by Killette2** [comment]
Virology needs an overhaul more than genetics. It just doesn't work and is one of the most boring RNG shitfest where you do tons of work, which may pay off if they don't take the 2 seconds to instacure it.

**Comment by vampirebat74** [comment]
What if viro was able to scan objects taken from space for viruses, and viruses would have a trait that determines whether or not they can automatically be cured, similar to being contact/blood/airborn? Maybe make it so that viruses that don't go away naturally can easily be cured with spaceacillin

**Comment by aceedex** [comment]
how bout.
Viruses can't cure themselves, unless you have spacecillin in your system, in which case the virus stops incubating (meaning wont receive any newer stages, just live with what you already have) and while spacecillin is being metabolized you have a chance to overcome it. Overcoming the virus meaning, you do NOT produce antibodies, the virus just stops affecting you but you cant cure anyone else. Then, add a way to get spacecillin outside of medbay in non-absurd quantities. 

I feel like this  reaches a happy middle ground, where viruses are still lethal and capable of crippling, but if you got sneezed at and the medbay got bombed you're not stuck in the floor for the next 30 minutes while the viro murderbones.

Also bring back radstorms mutating viruses for cryin' out loud

**Comment by Kammerjunk** [comment]
>radstorms mutating viruses

Not really helping what the OP mentioned about beneficial viruses

**Comment by Arthurdentist** [comment]
the biggest nerf to viruses was actually making it so that when a person is infected, they get infected at stage one. Previously an infected person was infected at whatever stage the person who infected them was at, this was why you could have such an effective 'virus explosion' in the past.

**Comment by DamianX** [comment]
You could also have a virus that made you instantly suicide which is what got it nerfed, iirc. Surely we don't want to bring that back

**Comment by Killette2** [comment]
@Arthurdentist I claimed that nerf would kill viro from day one. What if the virus just grew faster depending on what stage it got transfered from? For example getting a stage 4 would make you get sick 4 times faster

**Comment by Arthurdentist** [comment]
@DamianX my suggestion would be to make viruses infect one stage below the stage they are on, so a stage four would infect at stage three, stage three at two, and stages two and one at stage one

I also think removing suicide syndrome might not be a bad call as well.

**Comment by ghost** [comment]
Does Suicide syndrome stop you from being cloned like regular suicide?

**Comment by Killette2** [comment]
Yes. There's also gibbingtons, creole (mint toxin), monkism, catbeast, plasma generation.
A lot of stage 4 syndromes are catastrophic, and some to the point where you are prevented from being cloned in one way or another. That's their point, and a lot are locked behind a thing called bad=2, which means you can't just spam virus crates, you need to get lucky with radiation to even have a chance of unlocking them.

**Comment by ghost** [comment]
Creole is only a threat when paired with gaben syndrome, otherwise who cares if its culls one or 2 fat players.
Catbeast basically only because of serb culture.
