### ISSUE TITLE
Roundstart Chaplain can Spawn as a Vampire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20159]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
22f57f09e918f0894715cf90706b4b603b88fc61

# Description

This kills the Chaplain
# Steps to Reproduce

Spawn as chaplain, be roundstart vampire
# What you Expected

To not spawn as a vampire and not die
# What Actually Happened

Dies screaming and on fire and burns to ash.

**Comment by ShiftyRail** [comment]
https://github.com/vgstation-coders/vgstation13/blob/22f57f09e918f0894715cf90706b4b603b88fc61/code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm#L79-L80

I blame dynamic mode
