### ISSUE TITLE
Antag Hud is borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20151]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
1b4488e4e0d1429558c6f742d5d3c282c27dde59

# Description
The Antafg Hud dfor admins is broke and fails to show the icon for antags for admin ghosts
# Steps to Reproduce
check antags, jump to antag, turn on antag hud, see nothing
# What you Expected
little antag icon
# What Actually Happened
nada. didnt work for traitors or changelings. did not test the rest.

**Comment by Kurfursten** [comment]
this was because traitors didn't have an icon, now they do
