### ISSUE TITLE
Blue biomass vines seem to have no sanity to where they can grow.

### ISSUE THREAD

**Issue by DrSnips** [d3athrow/vgstation13#20161]
As the title says blue biomass seems to grow through windows, airlocks, firelocks, and most other tiles next to it despite being blocked in some way or another that you couldn't move though normally or would expect to block it.

**Comment by SonixApache** [comment]
[feature]

**Comment by Dacendeth** [comment]
Doesn't kudzu do this too?

**Comment by DamianX** [comment]
Calling this a bug until proved otherwise

**Comment by Lunstra** [comment]
I can confirm from observation that regular kudzu does NOT do this, and in fact, if it grows fully next to closed airlocks at least, sometimes does the exact opposite and refuses to grow anymore in that direction even if the airlock is opened, until part of the vine is destroyed forcing it to update I guess.

**Comment by Blithering** [comment]
Seems both like to grow through windows though
