### ISSUE TITLE
Bagel: If the singulo is the feature engine, then why does so much singulo-related stuff start as unbolted?

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20173]
#### Description of issue

It adds so much time to even setting up the simplest of engines that the SMES can run out of juice.

#### Difference between expected and actual behavior
set up PA, turn on field gens and emitters, fill collectors, engage PA
vs
set up PA, bolt down and weld field gens, turn on field gens and emitters, bolt down collectors, fill collectors, engage PA

#### Server revision
dcc4c15a29fe48e7d730fda0cd833d93054299f3

**Comment by CptWad** [comment]
originally because if nobody bolts it down theres nulls at the certain variables for admin investigations
shit idea now that I think about it
