### ISSUE TITLE
Chillwax does not work on simple mobs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20171]
(WEB REPORT BY: repertor REMOTE: 172.93.109.202:7777)
# Revision
dcc4c15a29fe48e7d730fda0cd833d93054299f3

# Description
When injected, simple mobs are still able to attack
# Steps to Reproduce
inject a hostile mob with chillwax
# What you Expected
pacification of the mob
# What Actually Happened
continues to attack

**Comment by MadmanMartian** [comment]
Fixed by #19948
