### ISSUE TITLE
Putting telecrystals in an ore box deletes them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20178]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
dcc4c15a29fe48e7d730fda0cd833d93054299f3

# Description

As it says on the tin
# Steps to Reproduce

Mine telecrystal

Pick up with satchel, load into  ore box
# What you Expected

To load the telecrystals
# What Actually Happened

deleted

**Comment by ShiftyRail** [comment]
Probably easy to fix.
A missing allowed type most likely.
