### ISSUE TITLE
New and weird probable byond bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20184]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
dcc4c15a29fe48e7d730fda0cd833d93054299f3

# Description

Currently my throw sprites and my right clicking object sprites are being exceptionally fuckey, not displaying anything but blanks until moused over and not displaying prepped throws at all.
# Steps to Reproduce

no fucking clue but I spawned as a diona
# What you Expected

Functional normal game
# What Actually Happened

like 2/3rds not shit?

**Comment by DamianX** [comment]
works on MY machine
