### ISSUE TITLE
Blood Banks don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20196]
(WEB REPORT BY: riekland REMOTE: 172.93.109.202:7777)
# Revision
1fe90e48ce77cb2d2e4521d5a943337e7c8f87e8

# Description

blood banks don't vent anything even when they're powered, you can still toggle the images though so that's something

**Comment by ghost** [comment]
Can confirm.

**Comment by DamianX** [comment]
I know that spaces in the name of the bloodpack break it.
I don't know why. I think it's a BYOND bug, someone should test the latest 512 versions to see which one broke it.

**Comment by SonixApache** [comment]
should probably bandaid it for now, it's pretty debilitating

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's not the spaces, it's the \improper macro in the bloodbags
Given that nothing in the code changed recently I'm 99% sure this was caused by the BYOND update

**Comment by DamianX** [comment]
Which one, though?
