### ISSUE TITLE
Create antagonist verb will only spawn 1 wizard, no matter how many are entered

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20201]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
2f82cbcbb726f048a6f9ab1d7142f8469076b490

# Description
very based
comes up with
number of wizards made.
in the chatbox after

**Comment by DeityLink** [comment]
Oh the irony
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/396d3db2-82ca-46c5-8c96-3b8d5849df98)

**Comment by DeityLink** [comment]
Maybe fixed by #34638
Needs more testing. @nervere

**Comment by DeityLink** [comment]
Actually I'll just close this until the problem arises again.
