### ISSUE TITLE
halloween wizard spellbook bundle ideas

### ISSUE THREAD

**Issue by coldcola** [d3athrow/vgstation13#20207]
skeleton curse, pumpkinhead curse etc
hurry there is not much time

**Comment by SonixApache** [comment]
Shadow's embrace , which gives you that vampire half-cloak
Morph into skelevox
Pumpkinhead curse, lit, can't be taken off, forces you to sPeEeEaAaK SpoOoOoOkilly
~~something with candycorn~~ [redacted]
trick-or-treat, which equips a random unremovable halloween costume
Curse of the Horseman, that makes your head invisible or god forbid, detachable?

~~Also gonna need black&orange robes.~~

**Comment by Shadowmech88** [comment]
A spell to spawn a jack-o-lantern mob that casts fire breath like the firebreathers from the tomb mission.
Summon robes replaced with an identical spell that summons a witch outfit instead.
Potion of spiked punch. When thrown, makes everyone in view of the impact point the maximum level of drunk except the one who threw it.
Lycanthropy spell. Gain the ability to transform into a powerful werewolf, but it's random, you can't use your spells while transformed, and you intermittently lose control and have a simple_animal AI take over.
A broom artifact. Grants spaceflight as well as standard levitation.
A mummify spell. Summons enchanted bandage clothing items onto you that heal your brute damage while you wear them, but also make you move slowly and don't function as wizard robes.
A spell that does nothing but make ghosts visible. Costs 1 spell point.
A poltergeist spell that causes you to astral-project like with the scrying orb, but you can't hear or speak with deadchat. Instead, you gain the ability to either move specific items, or throw all items in view around.
A spell that breaks or burns out half the lights on the station randomly.
A spell that lets you create spider web obstacles.
A spell that creates one random snack item poisoned with 1u spiritbreaker per use.
Alternatively, a single-use spell that causes all vending machine items to have a 10% chance to be dosed with 1u spiritbreaker.
A spell that causes NPC zombies to periodically rise out of the ground in random locations on the station.
A selection of the halloween costumes, but as artifacts which function as wizard robes and grant additional powers tailored to their appearance when worn.

**Comment by SonixApache** [comment]
> A broom artifact. Grants spaceflight as well as standard levitation.

Doesn't the broom we have already do that?

**Comment by Shadowmech88** [comment]
I wasn't certain we had a broom, but I did discover while testing something recently that levitation itself grants spaceflight by default, so it is likely it does both.

**Comment by Kurfursten** [comment]
Summoned Haunted Jams - It just spawns haunted jam all over the station. This is stronger than you might think because idiots might eat some and die. Plus ghosts can rattle them around so it's fun for all.

**Comment by Blithering** [comment]
Summon diabetes: gives all players a plastic pumpkin bucket full of random sweets. 
Monster mash: makes people hallucinate random mobs 
Graveyard smash: places a tombstone that summons skeletons until it's destroyed
2spooky4u: subjugate but it makes the target scream in terror
Witches cauldron: summons a poutine ocean style cauldron that can be interacted with any beaker or glass to get witches brew, a murky potion reskin. Drink all you dare!
9 lives: transmogrifies you into a black cat, summons eight more. That snake spell but Halloweeny
Jumpscare: Rigs a container with something that will jump out and spook you. Lockers can contain xenos or greyshirts that will toolbox you, crates may contain facehuggers, TTVs or spiders. Ideally, they would semi-realistically 'kill' the spookee for a few seconds before snapping back to reality.

**Comment by Blithering** [comment]
Flesh to bone: skeletonises the target

**Comment by Blithering** [comment]
Headless horseman's curse: target player becomes muted and a pumpkin is put on their head. They are given a head chopping axe and one minute to find a victim. Clicking someone with the head chopping axe swaps their head with yours (Frankenstein style, mix and match!) and passes on the curse. People who have already been the headless horseman have a glow  visible to the current horseman and can't be targeted by the axe. (No tag backs). If the horseman fails to claim a head before the timer expires the pumpkin vanishes, taking the wearers head with it. A Jack o lantern container spawns somewhere on the z level containing this head.

Thinking about this, it would also be a fun non-halloween spell if reskinned to a hot potato.

**Comment by Dacendeth** [comment]
A staff of change that only turns people into skeletons, ghouls, and frankenstein monsters?
