### ISSUE TITLE
Holodeck become holoperson lacks sanity.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#20237]
#### Description of issue
The become holo person button has no sanity to it, if you keep the panel open or otherwise gain access to the ability, you can teleport to the holodeck and become a holo person, and then untransmogrify as yourself whatever you are. I used this to get a derelict mommi to the holodeck once, and to teleport as a pai.

#### Steps to reproduce 
be a ghost
open the holodeck panel
become a derelict mommi
click the button to become a holoperson

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SGuivenne** [comment]
oh christ.  This is glorious.
