### ISSUE TITLE
Wizards can spawn in arrivals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20241]
(WEB REPORT BY: korthe REMOTE: 172.93.109.202:7777)
I spawned as a wizard in the arrivals shuttle with nothing at all

# Steps to Reproduce
I dunno, become a wizard
# What you Expected
to be in the wizards den
# What Actually Happened
I was in the arrivals shuttle

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
You became the virgin type of wizard not the sorcerer kind

**Comment by SonixApache** [comment]
i assume this was on roid

**Comment by Kurfursten** [comment]
should be fixed by #19946 unless things have changed dramatically with that deity fix the other day

**Comment by Exxion** [comment]
Reopen if it happens again
