### ISSUE TITLE
Simple AI REALLY likes doors now.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20243]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
# Revision
e1da95dbca70f7109751935e26976657c0f5a365

# Description
The spider thing wasn't only spiders; a lot of mobs seem to have extreme door-related OCD.

# Steps to Reproduce
place mob near all-access door
# What you Expected
mob kills me
# What Actually Happened
mob touches door for 6 hours straight

**Comment by DamianX** [comment]
allegedly fixed by #20432
