### ISSUE TITLE
Windoor malfunction (Box)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20247]
(WEB REPORT BY: bittervanilla REMOTE: 172.93.109.202:7777)
# Revision
bbb68135b675d66d2b7e8b674814018bdac46fd8

# Description
Mechanic can't open the windoor (research and development desk) to the lab from the starboard hallway on Box, making it hard to pass goodies to miners/janitors/traitors whilst being the crew facing side of Science.

The windoors around the General Fabricator work with the mechanics ID and from the crew side like they used to but it's not possible to lay a drill on it. Two reinforced windows block access to each tile anyway so crew can't reach around from the bottom side.

# Steps to Reproduce

+ Join as a mechanic
+ Attempt to open the crew side windoor in the top left corner of the lab
+ BEEP BEEP

# What you Expected

Anyone to be able to open it - it's on the public side and there's no windoor on the mechanic side.

# What Actually Happened

The roboticist, scientists and RD could open the windoor with their access, but not the public crew or the mechanic from their lab.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
:joy:
