### ISSUE TITLE
Nu--Box Mechanic & R&D disposal network is badly linked.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20254]
(WEB REPORT BY: irradiation REMOTE: 172.93.109.202:7777)
1 - Get into nu-mechanic disposals
2 - Proceed to get sent to nu-R&D disposals
3 - Enter nu-R&D disposals
4 - Nu-R&d disposals drops you there.

**Comment by SonixApache** [comment]
seems i don't understand how junctions work -- i'll look into it asap
