### ISSUE TITLE
Borer farsighted gene and ryetalyn

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#20267]
#### Description of issue
I had retard speech as a disability and took ryetalyn to cure it. Much later, a borer upgraded my vision with the head based eye upgrade. This brought back my disability which was funny but interesting.

#### Difference between expected and actual behavior
Expected: take rye, disregard disabilities, receive superior genes from borer (I actually hate farsight but that's neither here nor there)

Actual: take rye, disregard disabilities, receive eye gene from borer, disabilities trigger again

#### Steps to reproduce 
Have any power or disability suppressed by ryetalyn

Receive eye upgrades (probably any borer upgrade that applies a gene based power triggers this bug) from borer

#### Length of time in which bug has been known to occur

Unknown

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by strawberrytan** [comment]
I'm retarded and didn't see that this already has an issue that was ultimately labelled 'not a bug'

My bad

**Comment by DamianX** [comment]
FEATURE
enabling-
