### ISSUE TITLE
"My legs are OK." when targeting limbs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20266]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
# Revision
6dc31db4f90e993d484e8afe3403f3c475506173

# Description
Upon examining myself by clicking on my sprite I was greeted to a notification telling me that the status of my legs are "OK", regardless of where I was targeting on my sprite.

# Steps to Reproduce
Click your little man while playing to examine him and if your legs are okay, you should too enjoy this message.

# What you Expected
I assumed that if I was targeting my arms, for example it would inform me if they were also okay.

# What Actually Happened
Clicked my sprite, my legs are okay at least.

**Comment by DamianX** [comment]
maybe we should just remove that reference

**Comment by ShiftyRail** [comment]
Memes into mistakes

**Comment by Fruktlimpa** [comment]
I like this meme

**Comment by mattmatterson111** [comment]
I thought about commenting on how confusing that was in the original PR. It's not a very obvious reference when it's used in that context.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Memes were a mistake

**Comment by Riekland** [comment]
A "Jian"t pain
