### ISSUE TITLE
Detraitor'd traitor AIs still have their law 0.

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#20271]
#### Description of issue

Detraitor'd AI (by the removal of the role) still have their law 0.

#### Difference between expected and actual behavior

That law 0 should be dropped along with the role when you're detraitor'd by an admin.

#### Steps to reproduce 

Traitor an AI, detraitor AI, check its laws.

#### Length of time in which bug has been known to occur

Probably role_datums.

#### Server revision

Latest.

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SGuivenne** [comment]
Aha, I'm guessing the traitor thing just has the half assed "toss a law 0 in" code bit rather than have it actually connected to the role in some substantial way besides "throw in a rule 0 and make it unable to be removed".

**Comment by Intigracy** [comment]
It's a var that needs to be nulled.
