### ISSUE TITLE
Xeno Botany chem transfer/inheritance seems broken 

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#2028]
Looking at the code, I see the products gene also includes gases exuded, and chemicals, but whenever I splice the gene, I just get the fruits. Nothing else. Hoping this isn't intentional (as I don't fully understand the code) I've made a bug report. The file is seed_datums.dm in the hydroponics folder.

**Comment by ComicIronic** [comment]
Apparently fixed, reopen if not.
