### ISSUE TITLE
Prevent atmos from chainslamming mobs

### ISSUE THREAD

**Issue by ddolll** [d3athrow/vgstation13#20288]
<featurerequest>
<discussion>
Currently any time high pressure atmospheric changes occur, mobs get knocked over by airflow and slammed into windows etc. and stunned. While stunned, the mobs are then slammed into the window again, having the stun renewed. This means that any time an atmospheric event which triggers ZAS slamming occurs which isn't instant, literally everyone dies from chainslamming before they get the chance to stand up and e.g. turn on magboots, regardless of being in a hardsuit.

This reinforces the existing metagame of hardsuit-magboots-internals being mandatory at all times, as there is no counterplay or warning to a lot of possible triggers (i.e. someone fiddling with a vent).

If the slam did not occur while the mobs were stunned, it would be possible to survive atmospheric events which you yourself did not cause but were prepared for.
(and serve as a reduction of the binary nature of the lethality of atmospherics)

**Comment by Shadowmech88** [comment]
Specifically, I think preventing airflow from pushing mobs who are lying down, or at least preventing it from damaging/stunning them, would allow players to then crawl to safety after the initial shock of being pushed into the wall.

**Comment by SonixApache** [comment]
ZAS is still 5 kinds of fucked anyway

**Comment by ddolll** [comment]
The slam doesn't actually respect magboots so if you fall over while magboots are on you get chainslammed as well.
