### ISSUE TITLE
Schroomie invert eyesight cannot be cancelled

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20282]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
1d2816fd0f2cfd470ced2506c9bc7cb3c369165b

# Description

Probably something similar to the detective's noir plane. I'm stuck with a inverted colour view.

**Comment by BarneyGumball** [comment]
Very likely that #20252 will fix this.

**Comment by Exxion** [comment]
Are you on 1453? If so this is probably the BYOND bug

**Comment by Pathid** [comment]
Duplicate of #19280

**Comment by Exxion** [comment]
Well in that case, no it isn't the BYOND bug
