### ISSUE TITLE
Damaged APCs can sometimes not be deconstructed(?)

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20283]
#### Description of issue

![image](https://user-images.githubusercontent.com/8468269/47124115-7675a800-d27c-11e8-92eb-1f117e4eea1c.png)
APCs that have their covers blown off can SOMETIMES not be deconstructed.
The cell is stuck in there and there's not a single tool that works on it (though you can open the wire menu and snip the wires, but it doesn't seem to do anything)
Screwdriver gave me `Close the APC first.` and a crowbar gave me `Unexpose the wires first!`(?)
However, spawning in a mommi and using a wrench on it somehow removed the cell?
I probably caused this in #19040. I haven't been able to reproduce it locally, hence no report/fix yet.

#### Steps to reproduce
Not sure. It happens with APCs broken from either explosions or APCs. It only occurs when the cover is already off.

#### Length of time in which bug has been known to occur
Definitely since #19040, not sure if before.

#### Server revision
0732f797e3e5915fcf820e1765b84c813351a755

[bugfix]

**Comment by BarneyGumball** [comment]
Uuuuuuuh:

https://github.com/SonixApache/apachestation13/blob/095ebf524ae42870540b97025df9ba7798e26283/code/modules/power/apc.dm#L624-L631

Not sure what you intended to do but I'm sure it wasn't this.

**Comment by SonixApache** [comment]
guess there should be a `stat & (BROKEN)` in there or something?
