### ISSUE TITLE
Add quotes from The Lion to BrainDamage.txt

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#20293]
#### Description of issue

As such a notable person who has made contributions to the community it is only fair he be memorized in this manner.  After all, we'd be social pariahs not to.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Not every passing shitter needs to be immortalized, especially one from what is essentially not even SS13

**Comment by SonixApache** [comment]
*who?*
