### ISSUE TITLE
smelelel takes like a minute to kick in so we never even make it through the map vote

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20308]
something is fugged

revision cb5a4cf1f4f3b09b56627c664944c300295acb88

**Comment by SonixApache** [comment]
Roundstart sound (the automatic diagnostic and announcement bla bla bla) was also delayed. Something's really fucky.

**Comment by ShiftyRail** [comment]
Something sleeping in the subsystems responsible for smelele perhaps

**Comment by SonixApache** [comment]
I think it disappeared, I'll re-open if reproduced and provide more accurate info.
