### ISSUE TITLE
Lightswitches still glow red or green when the area power gets cut

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20303]
![EVEN_IN_DEATH_I_STILL_GLOW](https://user-images.githubusercontent.com/8468269/47188429-47bd0780-d338-11e8-86fe-ad08a9306ce4.png)

#### Server revision
c949cbab8d5bc69c29ed3485e1acacf86c31d42d

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It's intended that they self-glow (kind of like radium gunsights or something) but they probably should turn off when the area power is off since the lightswitch is useless in that case I agree

**Comment by SonixApache** [comment]
this feature got axed afaik

**Comment by DeityLink** [comment]
> this feature got axed afaik

I'm fairly sure light switches do become lightless when the APC's main breaker is off

**Comment by SonixApache** [comment]
the feature that got axed was lightswitches being a lightsource (again, afaik)

**Comment by DeityLink** [comment]
They absolutely are though, that's how you can see them from across a dark room.
![image](https://user-images.githubusercontent.com/7573912/131735192-d88688e0-f334-4fb3-a3b0-c8cfd0dbd136.png)

**Comment by DeityLink** [comment]
unless you turn off the APC ofc

**Comment by SonixApache** [comment]
chalk it up to [needs more testing] then i guess
