### ISSUE TITLE
Emotes in lobby

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20301]
(WEB REPORT BY: tolan1 REMOTE: 172.93.109.202:7777)
# Revision
c949cbab8d5bc69c29ed3485e1acacf86c31d42d

# Description
Emotes showing in lobby
# Steps to Reproduce
Connect to the server after the round starts and sit in lobby
# What you Expected
Not to see anything besides shuttle calls and command reports etc
# What Actually Happened
Seeing Poly flying around, Ian chasing his tail, the clown pulling a prank with the me verb

**Comment by DamianX** [comment]
fixed by #20295
