### ISSUE TITLE
Can see animals doing stuff in lobby

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20300]
(WEB REPORT BY: robosperg REMOTE: 172.93.109.202:7777)
# Revision
c949cbab8d5bc69c29ed3485e1acacf86c31d42d

# Description
https://cdn.discordapp.com/attachments/259083193741737985/502604353715044352/unknown.png
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment]
fixed by #20295
