### ISSUE TITLE
Trying to Health Analyzer someone clown cursed gets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20311]
(WEB REPORT BY: shadownil REMOTE: 172.93.109.202:7777)
# Revision
cb5a4cf1f4f3b09b56627c664944c300295acb88

# Description
Get clown cursed
Health scanner someone else who is also clown cursed
"You analyze the floor's vitals!
Analyzing Results for the floor:
Overall Status: Healthy
Key: Suffocation/Toxin/Burns/Brute
Damage Specifics: 0 - 0 - 0 - 0
Body Temperature: ???°C (???°F)
Localized Damage, Brute/Burn:
No limb damage detected.
Subject bloodstream oxygen level normal | Subject bloodstream toxin level normal | Subject burn injury status clear | Subject brute injury status clear
Blood Level Unknown: ???% ???cl
Subject's pulse: ??? BPM"

# What you Expected
To check the person and see their damage

# What Actually Happened
More than half the time, even if I'm moused over that person's sprite and the bar says "Unknown" and I click to check them, it checks the floor instead.

**Comment by Exxion** [comment]
#20310
