### ISSUE TITLE
wiz can't summon things

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#20314]
A night ago I was a roundstart wizard and I had none of the summon spells. Had an admin look into it too and even with the admin spellbook he couldn't summon either.

**Comment by jknpj** [comment]
#20081

**Comment by jknpj** [comment]
>I was a roundstart wizard

wait a minute

**Comment by jknpj** [comment]
Please post the logs

**Comment by DeityLink** [comment]
:thinking:
