### ISSUE TITLE
Wheelchairs get stuck in the cuckcube instead of being moved to where legless characters spawn

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#20320]
#### Description of issue
When you spawn as a legless character you spawn "buckled" in a wheelchair that got left behind in that cube you spawn in before moving to arrivals.

#### Length of time in which bug has been known to occur

I haven't played a legless character in a few months but it worked before that.

#### Server revision

Revision: f96859783c1aa4d6309d6fe41ca1f76763e668be

**Comment by DamianX** [comment]
This is even worse, you spawn buckled to the wheelchair in the cuck cube, so you can't move at all.
For the record, this only happens if you latejoin, as `AttemptLateSpawn` calls `EquipRank` before moving the guy.

**Comment by Dacendeth** [comment]
Yeah, you can get out of the wheelchair by disarming yourself at least.
