### ISSUE TITLE
When the Fist spell is used with Arcane Golem(s) you can hit each other

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#20331]
#### Description of issue
You'll punch the golems and the golems will punch you

#### Difference between expected and actual behavior
Factions

#### Steps to reproduce
Take 3 arcane golems, fist, punch your bros and be punched by your bros

![untitled](https://user-images.githubusercontent.com/5564796/47252242-b6a86800-d3ed-11e8-8837-3c0d5a26fca0.png)

#### Length of time in which bug has been known to occur

No idea, probably after golems or fist tweak whatever came last.

#### Server revision

[bugfix]
[featureloss]

**Comment by ghost** [comment]
Forgot to say, for the golems, I was the only mob in their field of view.

**Comment by ShiftyRail** [comment]
Tough love
