### ISSUE TITLE
Spawning the Firing Range, Discharging a gun to empty, and Respawning the firing range doesnt recharge the gun

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20349]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
dce2c641087abdd26e3fed18207edc4104887eef

# Description

Doing this does, however, make the gun appear recharged
# Steps to Reproduce

Summon firing range on holodeck, shoot gun to empty, put gun back, respawn the firing range on holodeck
# What you Expected

To refill the gun
# What Actually Happened

gun looks full but is empty

**Comment by SGuivenne** [comment]
Edit: throwing the guns around doesnt fix it either, and neither does swapping to an intermediate holodeck area and swapping back.  Throwing the firing range gun out of the holodeck and respawning it ALSO doesnt work.

**Comment by DamianX** [comment]
Because of the way the holodeck works, which is dumb and terrible, all hololasers share the same `power_supply`.
