### ISSUE TITLE
Repairing Computers fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20351]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
6cce3916bf4a931acca01f6b54fd1c7ae5dd167b

# Description
When a console screen breaks and is unscrewed, the glass will be stated to fall out, but no glass will, only when you actually repair the console will the broken glass come out
# Steps to Reproduce

Break a computer, unscrew it, notice lack of glass, replace glass, screw it
# What you Expected

Glass to fall out at step 2
# What Actually Happened
Glass falls out upon completion.

**Comment by ghost** [comment]
Tried it, got the shard on the unscrew.

**Comment by Kurfursten** [comment]
Also could not reproduce, most likely caused by LAYERS
