### ISSUE TITLE
Increasing virus strength is absolutely the worst

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#20374]
There are already a million issues about viruses in  general but here is another one.

Certain syndromes have multipliers (strength), when you increase it the symptoms become more potent, a potentially interesting mechanic.

The problem? It is incredibly tedious and you have no idea if you are succeeding or not.

So at least as far as I can tell from looking at the code, you need to radiate the virus with under 50 radiation, and then eventually minormutate will be called and you might increase the multiplier on a syndrome.

The issue is that you have a 5% chance of doing this as far as I can see, and then even if it hits minor mutate it is only a (I think) 1 in 6 chance that it will actually increase or decrease the multiplier. What makes this even better is the fact that the incubator doesn't actually give you any indication that a minor mutation has occurred. It will beep when you change the symptom but you get sod all when the multiplier, verosity or anything else about the virus changes.

This is just another thing about virology that ought to be changed.

**Comment by Killette2** [comment]
I've ranted about this on the other unrelated virus issue. It would be such a drastic change if there was a beep when this happened instead of you constantly needing to rescan it.

**Comment by MadmanMartian** [comment]
remedied by #21545
