### ISSUE TITLE
Left4Zed no longer works.

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#2037]
No effect is registered when using left4zed after the xenobotany update. Also floral somatorays don't seem to work either.

**Comment by ComicIronic** [comment]
Is this still an issue?

**Comment by Angelite191** [comment]
Yep. It is.

**Comment by 9600bauds** [comment]
It does work, it's just coded to be borderline useless. Basically you use a ton of left-4-zed on a plant, and it will need less mutagen to mutate. Which is pretty stupid, I was working on fixing it as part of my botany mutation overhaul, but that will come after the featurefreeze.

**Comment by clusterfack** [comment]
PR the fixes scrub, don't keep us waiting in the wings or we'll make a bunch of conflicts for you

**Comment by 9600bauds** [comment]
Too late, I already fucked up with git and basically have to redo the branch.
It's not really a fix either, more of a re-do which needs the rest of the mutation overhaul
