### ISSUE TITLE
Permanent Colorblindness

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20396]
(WEB REPORT BY: skippers REMOTE: 172.93.109.202:7777)
# Revision
e8327933336825f0f5a8b349c2d40e5e5d267027

# Description
Playing as a detective (Gumshoe) on Asteroid Station got color blindness from an unknown source. Doc couldn't fix it and admins couldn't either. Reconnecting didn't help
# Steps to Reproduce
Be Gumshoe on asteroid station, get colorblindness (I believe it was from a virus?)
# What you Expected
If a doctor couldn't fix it maybe an admin could
# What Actually Happened
Nobody could fix it and reconnecting didn't help

**Comment by Irradiation** [comment]
Gumshoe gives you the Noir mutation when you join.

**Comment by BarneyGumball** [comment]
#20252

**Comment by Exxion** [comment]
Yes, but Gumshoe is supposed to get Noir
