### ISSUE TITLE
Waifu effects can be negated by clothing hot swapping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20397]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
e8327933336825f0f5a8b349c2d40e5e5d267027

# Description

Getting turned into a magical girl is supposed to prevent you from removing the skirt, regenerating it if you do so, as of right now it doesnt
# Steps to Reproduce
Get waifued, change your clothes and move on with your life
# What you Expected

Magical Girl oWo
# What Actually Happened

Sadness

**Comment by Arthurdentist** [comment]
not a bug as far as I can tell, having the chemical in you means that you do regenerate the skirt, but it comes with some caveats. First, everytime you do regenerate the dress, you lose 4 of the chemical in your blood, and second you need to have more then I think 5 units for the effect to occur. So you need to pump yourself full of the chemical to get to a stage where the dress would constantly regenerate on you.

**Comment by SGuivenne** [comment]
in that case the text on the wiki is misleading.

**Comment by Kurfursten** [comment]
Yeah, it's the intended effect that it costs some waifu to regenerate the outfit.

If you really wanted it unremovable we do have clothing level vars for that (e.g.: cursed horse mask)
