### ISSUE TITLE
Box Station Research Shuttle freaks the fuck out when airlock is opened

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20421]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
23d284d870c417754ce95bf1e927aad92ff47d91

# Description
When the airlock to space is opened, regardless of whether or not the shuttle is docked, the emergency airlocks immediately fall as if it has vented to space, with a corresponding alert being issued.  this generally occurs when the shuttle is docked and the air is safe.
# Steps to Reproduce

Dock research shuttle on station, open the airlock
# What you Expected

to embark/disembark

# What Actually Happened

Airlocks down PANIC MODE

**Comment by CptWad** [comment]
there appears to be scrubbers and vents under air alarms
thats probably why
