### ISSUE TITLE
Bring back the Excavation Hardsuit on Box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20420]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
23d284d870c417754ce95bf1e927aad92ff47d91

# Description
As far as I was aware the survivor suit was meant explicitly for roidstation, it shouldnt be popping up on box should it?

**Comment by jknpj** [comment]
🤔

**Comment by Exxion** [comment]
What did he mean by this?

**Comment by DamianX** [comment]
Suit dispensers on the box research outpost contain survivor suits. Is this intended?

**Comment by Exxion** [comment]
Ah yeah that makes sense

**Comment by Blithering** [comment]
The survivors suit was supposed to be a middle of the road suit for both miners and scientists on asteroid station only. Instead only scientists get it, and it replaced the excavation suit on other maps as well. Smells a bit like a sneaky science buff to me.

**Comment by DamianX** [comment]
They can't keep getting away with this. Who did it? @jknpj @GeneralVeers25 @brndd
