### ISSUE TITLE
monkeys placed in a locker will endlessly gasp even after being removed from the locker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20427]
(WEB REPORT BY: cptwad REMOTE: 172.93.109.202:7777)
# Revision
23d284d870c417754ce95bf1e927aad92ff47d91

its on the tin

**Comment by CptWad** [comment]
![image](https://user-images.githubusercontent.com/3959840/47479292-7aa44700-d7e1-11e8-8724-789349b110d0.png)

**Comment by Pathid** [comment]
Very possibly a result of #19802

**Comment by Exxion** [comment]
I'd say probably
