### ISSUE TITLE
Feature Request: Artifact Borgs Made Interesting

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#20434]
#### Description of issue
Artifact borgs are kindve lame right now, always being an unbound TG service borg with one of several flavors of lawset.  What would be interesting is to make there be abnormalities with digging up and activating artifact borgs.  Perhaps they have asimov or one of the default lawsets, perhaps they get one of the quarantine or oxygen is toxic or power saver laws, perhaps they get ion laws, or perhaps they get something weird like an Asimov lawset for the wrong species (I.e. for vox or greys or for monkeys/lizards or something non sapient) or getting a corporate lawset for corporations that either are not nanotrasen or are not even located in the station.  Maybe even wartime lawsets or lawsets with missives that no longer have any significance.

On top of this it'd be interesting to roll for non standard additions to the artifact borg modules, such as items from other modules, weird questionable shit, or even concerning additions like random traitor tools.  I dont know how viable this specific bitd be but some more diversity to art borgs would be neat.

**Comment by Exxion** [comment]
You know, you can just self-tag it rather than writing "Feature Request" in the title
Read the template that comes up when you open an issue

**Comment by jknpj** [comment]
They do have their own module and exclusive crap though

**Comment by SGuivenne** [comment]
I have literally never seen that other than the detectimov lawset

**Comment by jknpj** [comment]
🤷‍♂️

**Comment by Caboozles** [comment]
Could just make it so that they all start with an ion law that can't be purged. Would create some real comedy, and make it really feel like an ancient, damaged borg.

**Comment by jknpj** [comment]
More like it would never get used. Who in their right mind would active a rogue cyborg?

**Comment by SGuivenne** [comment]
> More like it would never get used. Who in their right mind would active a rogue cyborg?

Most of the station, Ion laws make things !!FUN!!
