### ISSUE TITLE
Borers don't recover chems when their host is unconscious

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#20478]
#### Description of issue
Borers don't recover chems when their host is unconscious but they themselves are fine(can speak etc)

**Comment by Shadowmech88** [comment]
Evidently a feature: https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/simple_animal/borer.dm#L160

**Comment by Kurfursten** [comment]
@Exxion Either decide this is a bug or close it

**Comment by Exxion** [comment]
It's iffy but nobody seems to really care
