### ISSUE TITLE
Gas lost when wrenching h/e junctions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20482]
(WEB REPORT BY: ddolll REMOTE: 172.93.109.202:7777)
# Revision
0118819467c0c0352c024c3fe00a40583b684293

# Description
When wrenching h/e junctions together, I noticed that almost all of the gas in the pipenet dissappeared and it went from >200000KPA to 2KPA in a pipenet at most twice the size.
# Steps to Reproduce
Attach a h/e junction to a pipenet, possibly only while in space?
# What you Expected
Gas not to dissapear
# What Actually Happened
Gas dissapeared

**Comment by Exxion** [comment]
Thought I fixed all the bugs like this
I'll take a look when I get home

**Comment by ddolll** [comment]
![junctions](https://user-images.githubusercontent.com/44032911/47624400-b5024100-db5f-11e8-8f44-1bce92f5a124.png)
This is how I was arranging the pipes if that matters

**Comment by Exxion** [comment]
So it turns out this
1. Is not unique to H/E junctions
2. Is not unique to H/E pipes at all
3. Is not unique to space
4. Is not unique to low pressure
5. Is not unique to anything
6. Just always happens literally every time you wrench any pipe down
7. Just deletes the entire fucking pipeline
8. Has happened for years

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Okay but can I ask why were you doing that disgusting piping

**Comment by Zth--** [comment]
Does this still happen?

**Comment by Exxion** [comment]
Pretty sure it does, but I haven't tried recently
Don't remember for sure whether or not I even figured out exactly *why* it happens
