### ISSUE TITLE
Spawning Without Legs Is Bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20505]
(WEB REPORT BY: nukas REMOTE: 172.93.109.202:7777)
# Revision
8cd61b30888cec265025068a9949886adc8ba722

# Description
Spawning without legs should spawn you on a wheelchair, it currently does ANYTHING BUT. I can't even describe it, you DO get the "You climb onto the cripplin' ride!" message but there's no wheelchair around. You cannot move, only turn around. It's as if you were stuck in an invisible wheelchair. There happened to be a shuttle seat under me and I couldn't buckle/unbuckle to it. An admin spawned a wheelchair under me and I couldn't climb to it.

# Steps to Reproduce
1) Join a round in progress without legs. (not sure if map dependent)
2) ???? WHAT THE F

# What you Expected
1) Spawn in a (visible and working) wheelchair.

# What Actually Happened
Spawned unable to move or buckle up to anything, wheelchair probably spawned in an alternate dimension.

**Comment by ShiftyRail** [comment]
The wonders of the cuck cube
