### ISSUE TITLE
Spider Migration Season

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20518]
#### Description of issue

spiders now have a tendency to aggressively roam and go through airlocks
this causes the salvage shuttle spiders to space themselves at roundstart
which results in spiders raining onto the station *almost every round*

#### Difference between expected and actual behavior
expected to be able to work without orbital drop shock spiders deleting my windows

#### Steps to reproduce
watch the spiders on the salvage shuttle

#### Length of time in which bug has been known to occur
since #20432, and whatever caused the spider OCD before that

#### Server revision
b8790b0eba17ee5385b860723704d048d20aed03

**Comment by BarneyGumball** [comment]
Have to agree that it's really fucking annoying and pretty excessive.  A spider came in through the singularity airlocks on Box during low pop and proceeded to smash every window and jam open every airlock between engineering and the HoP's office.

The worst is when one of the spider queens shows up to your lovely autism build and destroys half of it with 30 seconds.  The only way to prevent major damage is to be already carrying enough weaponry to deal with it (and don't you dare be a MoMMI).

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/pull/20077/files#diff-844b559858e6eb2ed7249e36c730e82eL107

**Comment by SGuivenne** [comment]
can we get a honk tag on this one?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I said it once and I'll say it again
If the problem was that the airlock opening timer shat with Life() threading why can't we just revert all the changes to spider airlock opening and just give it set WAITFOR false

**Comment by SGuivenne** [comment]
had this happen 2 rounds in a row, spider vented the fuck out of the HoS office and in the next round a spider broke into TEG and then was baited onto a treadmill to serve as an eternal power slave for its sins.
