### ISSUE TITLE
A virus symptom's chance can become 0

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#20513]
Another bug for the shitpile that is virology.

Virus symptoms have a chance var, which determines how likely the symptom is to proc on each tick. This chance var can actually become zero, I am not entirely sure how but I think it can occur during MINORMUTATE. the consequence of this is that the symptom will literally never occur, you could have kingston syndrome with zero chance and you will never become a catbeast, and worst of all there is no way for a virologist to actually see this chance easily without being an admin, which means an antag virologist could be in the unfortunate position of releasing a virus then having it do literally nothing, and never knowing the reason why.

**Comment by SGuivenne** [comment]
Yet another reason why virology in its current iteration is shit
