### ISSUE TITLE
Surik Stalks incorrect reagents?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20566]
(WEB REPORT BY: kahnn1 REMOTE: 172.93.109.202:7777)
# Revision
18f2ead119138fd779c4a3e669b320600106be90

# Description
If you grind surik stalks in a grinder it gives you karmotrine instead of Hyoscyamine as listed on the wiki.

# Steps to Reproduce
Grind surik stalks in grinder.

# What you Expected
Hyoscyamine and Cytisine.

# What Actually Happened
Karmotrine.

**Comment by AutismSpider** [comment]
wiki was not updated when surik was given the new chem

**Comment by Kurfursten** [comment]
Wiki is now updated, this is safe to close

@Exxion
