### ISSUE TITLE
glass of scientist's serendipity has no sprite

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#20570]
Fill a glass with this chemical and it will not be visible to any method other than floor alt click

**Comment by Kurfursten** [comment]
Could not reproduce on live

**Comment by Killette2** [comment]
I did it on the test server with a drinking glass (not a beaker of any sort). When in glass form you're able to put inside the destructed analyzer

**Comment by Kurfursten** [comment]
You can *only* insert it into the DA when it's in a drinking glass, that is the intended design.

When I attempted to reproduce it I used a normal drinking glass, not a beaker.

**Comment by Killette2** [comment]
Can you post a picture of it?

**Comment by Kurfursten** [comment]
![image](https://user-images.githubusercontent.com/9782036/48024591-afc86780-e106-11e8-863c-7e1755edb2fb.png)

**Comment by Killette2** [comment]
![image](https://user-images.githubusercontent.com/5169310/48084410-9e926000-e1c5-11e8-8728-ce770bd69247.png)

**Comment by Kurfursten** [comment]
Are you sure this isn't a test server problem? Test serb can run out of date often.

**Comment by Exxion** [comment]
Test server is *always* out of date, and this was shown to work on live
