### ISSUE TITLE
Infinity chemheating bug

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#20578]
#### Description of issue
Chemicals in beakers seem to keep their temperature for a while or something and this leads to weird interactions if you mix stuff in them

I never noticed this before because usually I pour the synth into a new beaker with bicaridine ready to go

#### Difference between expected and actual behavior
Expected: add bicaridine to synthocarisol beaker for some stacked healing memes

Difference: mix bicaridine in the beaker, but the inaprovaline and bicaridine present keep instantly turning into more synthocarisol inside the beaker i used to heat up the chems in the first place

#### Steps to reproduce
Make synthocarisol in a beaker using a Bunsen, then throw in some inaprovaline and bicaridine 

You now have more synthocarisol

#### Length of time in which bug has been known to occur

<bugfix>

**Comment by bathosbathtime** [comment]
Each chemical has a heat capacity in the code, with synthocarisol having 0.57 compared to bic and inapro having 0.57 and 0.8 respectively.  While it does make sense for synthocarisol to remain hot for a short while after cooking, it would still need to be much hotter than the required amount to bring the other reagents to the temperature needed.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
the infinity bunsen burner....

**Comment by strawberrytan** [comment]
so to update this may not be a bug and it is not infinite, the beaker was hotter than synthocarisol requires to be cooked

as more chems are added the heat is diluted until it is no longer hot enough to cause the reaction
