### ISSUE TITLE
Manifest prediction doesn't show assistants

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20574]
#### Steps to reproduce
- Set assistant to Yes
- Ready up
- Check manifest prediction

#### Expected behavior
Assistant | 1

#### Actual behavior
Nothing at all

#### Specific information for locating
Probably because it's not `High` but `Yes`.

**Comment by Kurfursten** [comment]
This isn't a bug, you can't high pref an assistant role. It was brought up in the original PR that if you set something else to high and then Assistant to YES, your other role is still the high pref the system will use.

Assistants are wonky.

**Comment by DamianX** [comment]
The whole thing is a UI clusterfuck.
