### ISSUE TITLE
Vampire thralls are listed multiple times in the end game report

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20581]
![image](https://user-images.githubusercontent.com/6307265/48026855-8da30980-e147-11e8-85c1-10e61f513b19.png)

They shouldn't be

**Comment by MadmanMartian** [comment]
One lists the factions, which the vampires are under, the other is independents

**Comment by DamianX** [comment]
Why don't we list them all together a third time for good measure?
