### ISSUE TITLE
Snow (from snow planet) suggestion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20610]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
2f4fc6bdb98cc67f0a2ed60d3804be32787c19f6

# Description

Snow doesn't take shields into account.
Snow should probably be in auto-throw mode like bolas and activated grenades.

**Comment by Exxion** [comment]
But have you considered: Fuck auto-throw

**Comment by Kurfursten** [comment]
cannot reproduce

![image](https://user-images.githubusercontent.com/9782036/68746542-6da9ef80-05be-11ea-9c89-bfddd18b0d52.png)
