### ISSUE TITLE
Peg feet can't be removed

### ISSUE THREAD

**Issue by LisandraBrave** [d3athrow/vgstation13#2061]
This extends to removing legs too, leading to this kind of thing
![limbs are magic](https://cloud.githubusercontent.com/assets/8226662/5311359/1bb24bde-7c0a-11e4-970f-4f2d003d1246.PNG)

**Comment by ComicIronic** [comment]
Peg limbs in general don't seem to be removable.
Had an issue of attaching a peg leg (which generated no foot) which could not be sawed off, despite having the messages play.
