### ISSUE TITLE
Meta morgue airlock can't be opened by paramedics.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20628]
(WEB REPORT BY: tobiaskunst REMOTE: 172.93.109.202:7777)
# Revision
5ff61840789fab6167bfb15e1571b820f761834e

# Description

Paramedics can't open the airlocks left of the morgue.

# Steps to Reproduce

1# Be Paramedic
2# Try to open airlock left of the morgue.
3# Be disappointed.

# What you Expected

Airlock opens.

# What Actually Happened

Airlock stays closed.

**Comment by Irradiation** [comment]
It's easy. We remove metaclub.
