### ISSUE TITLE
Posibrain Text & Ruling

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#20637]
When you become a posibrain you are greeted by this message:

> You are a positronic brain (OSI-618), brought into existence on Production Hub Sigma.
> 
> As a synthetic intelligence, you answer to all crewmembers, as well as the AI.
> 
> Remember, the purpose of your existence is to serve the crew and the station. Above all else, do no harm.

Now, apparently the rules have changed on how this is ruled.
Said here, #11896 and what was my understanding is that these aren't inherently important and you are treated as a regular non-antag crew-member, with authority much of an assistant. 
However I have just been informed by Shifty, who apparently also asked in the admin portion of the discord, that this is false. As a posibrain mech/spiderbot you cannot harm anything. At all. No mobs, nothing.

This is insanely stupid and pretty much makes putting posibrains into mechs a complete waste of time, as they can pretty much do nothing but walk around and look at people. 

We should really do something about that text.

**Comment by strawberrytan** [comment]
I don't think a lawless posibrain should be allowed to validhunt and form it's opinions on whether a proper crew member is a 'syndie', but I also see the reasoning behind allowing them to beat up carp and stuff

**Comment by SGuivenne** [comment]
you are allowed to valid hunt, that said theres also good reason not to give posi brains control of mechs, seeing that its both less useful than a person and asking someone to paranoidly EMP it.  After all, you are literally asking for a robot uprising that way.

**Comment by SonixApache** [comment]
the posibrain law has always been a guideline, not a literal rule. treating it as such is retarded.
the law shows up once, when you spawn, and that's it - people tend to forget about it anyway
best solution would be to alter or remove the message imo

**Comment by charmstruck** [comment]
Couldn't you just change them so that they act as cyborgs? As in: slave them to an AI when activated, give them the AI's laws or Asimov, make it so that they show up on the cyborg law change computer. This would obviously revert if the posibrain were to be made into an AI or MoMMI, but stay the same if inserted into a cyborg/mech/spiderbot body
Or you could just give them a static lawset like Asimov and be done with it, I guess

**Comment by Killette2** [comment]
just add to the end of do no harm "to the crew or it's silicons."

**Comment by BBHazard** [comment]
> 
> 
> just add to the end of do no harm "to the crew or it's silicons."

This would be ideal.
Or do the other option and give them a proper lawset from the start, or when they're inserted into a mech.
Leaving it as-is makes non-borg posis worthless and ensures the bare minimum of mechs ever get used.

**Comment by robintime** [comment]
dupe of #11896
