### ISSUE TITLE
Hair selection arrows don't pick from the same list as manual input

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20632]
#### Description of issue
![image](https://user-images.githubusercontent.com/6307265/48267095-a9e9c380-e431-11e8-95e4-68fcb881acae.png)

#### Steps to reproduce
- Be /mob/new_player
- Character setup
- Select the CIA hair style
- Hit the `<` arrow to choose the previous element in the list

#### Difference between expected and actual behavior
It should give you the previous hair style in the list.
It gives you null and throws a warning instead.

#### Specific information for locating
`## WARNING: code/__HELPERS/lists.dmL207: -1 is outside of bounds for list, (67)`

**Comment by SGuivenne** [comment]
I always assumed this was a byond issue.  This is a issue on literally every server I've played on, you can even get invalid hairstyles from it sometimes, like quills on humans or an afro on vox, it wont sprite right but it'll let you pick it!

**Comment by Exxion** [comment]
Absolutely genius warning by the way
I think someone didn't understand how the `__FILE__` and `__LINE__` macros work

**Comment by Exxion** [comment]
Oh and
https://github.com/vgstation-coders/vgstation13/blob/234f33da2136260b5acfacd39bb4dbece7e4a988/code/modules/client/preferences.dm#L1195
`//gender intentionally left null so speshul snowflakes can cross-hairdress`
So yes, the title of the issue is exactly the issue
