### ISSUE TITLE
Can only see chicken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20643]
(WEB REPORT BY: jackthesmack REMOTE: 172.93.109.202:7777)
# Revision
ddcd3b026020569df4f571dd8c2d252e88b8e138

# Description
I can only see a chicken that says "RIR Pomf chicken
You were delicious"
I have tried spectating people as ghost, clicking all the ghost commands, turning into a mouse.
# Steps to Reproduce
Clicked observe.
# What you Expected
To see the game
# What Actually Happened
I see a chicken

**Comment by DamianX** [comment]
You probably had the screen freeze bug. Update to the latest beta, which is 512.1454 at this time.
