### ISSUE TITLE
Telecomms heat exchange pipes are connected to the waste pipes

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20664]
#### Description of issue
![image](https://user-images.githubusercontent.com/6307265/48320364-9ac56a00-e619-11e8-875d-bd6de2185faa.png)

This setup is impossible to recreate in-game and should probably fail to initialize instead.

**Comment by ghost** [comment]
Well THAT explains a lot

**Comment by DeityLink** [comment]
And that is the story of how a cultists managed to kill himself and two other cultist, including one on the other side of the station, by just throwing some molotovs in the library.
