### ISSUE TITLE
Unconscious humans can scream

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20678]
#### Steps to reproduce
- Give spessman 14u chloral hydrate
- Break said spessman's bones

#### Difference between expected and actual behavior
He's unconscious and shouldn't be able to scream, but he is.

**Comment by DrSnips** [comment]
I have no consciousness but I must scream.

**Comment by SonixApache** [comment]
it's a reflex

**Comment by Kurfursten** [comment]
This appears to be a feature, it's specifically defined in scream

>stat_allowed = UNCONSCIOUS

What do we want to do on this one?
