### ISSUE TITLE
Monsters revived by Lazarus injectors will not remain allied after death and being cloned

### ISSUE THREAD

**Issue by peas2j121** [d3athrow/vgstation13#20675]
#### Description of issue
Monsters revived and put into Lazarus capsules will no longer be allied to you if you die and get cloned.

#### Difference between expected and actual behavior
Much like how cult carries over in death (even if you're cloned to a point before you were converted), your creature's loyalty should act the same way (after all, it's the same dna between cloned bodies). 

#### Steps to reproduce
-Kill a monster
-Revive it with any Lazarus injector and put it in a capsule
-Die and get cloned
-Now your monsters won't listen to you

#### Length of time in which bug has been known to occur
Apparently this issue was reported about on Nov 5 2016

**Comment by MadmanMartian** [comment]
It's because the faction is lazarus \ref[mob], so once you're no longer that mob, they're no longer your lazamons

**Comment by DamianX** [comment]
feature, stop cloning people

**Comment by ghost** [comment]
If anyone's closing them later on, #12486

**Comment by Exxion** [comment]
Duplicate of #12486
