### ISSUE TITLE
Mist Form ability does not work

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#20671]
#### Description of issue
Mist form literally does not work.

#### Difference between expected and actual behavior
For it to work.

#### Steps to reproduce
Be a vampire, get enough blood to unlock and be able to use the spell listed at 20u, click on the mist form ability and have it do nothing, not even enter a cooldown or error message.
On an unrelated noted every single vamp ability is on a 3-minute cooldown now except for mist form and cloak of darkness, just remove all solo antags already instead of going down this path.
#### Server revision
e97acecbb73997c4da93fd695c643bb5c5777cd0

**Comment by ShiftyRail** [comment]
This is the cooldown they had before.

**Comment by ShiftyRail** [comment]
Works on my machine. Are you sure you weren't standing on a holy tile, in the chapel ?
Were you hit by the null rod ?

**Comment by Gringonius** [comment]
I was in the escape shuttle. I don't think there were any chaplains around. Would it give no message feedback about holy tiles blocking it?

**Comment by ShiftyRail** [comment]
Jaunt, the wiz spell, doesn't work on the escape shuttle (z = 2). Vampire's jaunt is based on that. I assume this is to avoid wiznerds looting centcom, but vampires shouldn't have that constraint.

**Comment by ShiftyRail** [comment]
@Exxion @Intigracy Was deemed a feature

**Comment by Intigracy** [comment]
If you want them to cast while on z1, just code it so jaunting into a space tile that throws you into space works.
