### ISSUE TITLE
IAA suitcase SMG is underwhelming

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#20677]
[spoiler or at least it was the last time I played, which was admittedly a while ago[/spoiler]
the TC price should be lowered, or the damage should be buffed somehow

**Comment by Killette2** [comment]
what size is the gun? I thought that was it's perk

**Comment by SonixApache** [comment]
the obvious solution is to remove IAA

**Comment by Durgen** [comment]
Did not mean to close this

**Comment by Blithering** [comment]
The gun it comes with is the standard science printable SMG, but the real bonus of the case is the ability to pop it out and store any gun in there.
