### ISSUE TITLE
Borgs made with cultist brains retain vision of the cult icon and can identify other cultists.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#20682]
#### Description of issue
On the tin, if borgs were bad enough against team antags before now a borg made from a cultist can easily just hunt down all cultists on command. Likewise, cultists can see the cult icon on the borg and it might throw them off the first time.

**Comment by SonixApache** [comment]
@DeityLink this is pretty serious
maybe turn them into constructs or something?

**Comment by DeityLink** [comment]
We've discussed about it on Discord. i think the best option is to give players a new mind when they become borgs. 99.9% of the time they don't get to become human again anyway.

**Comment by Pathid** [comment]
>give players a new mind when they become borgs. 99.9% of the time they don't get to become human again anyway.

What about after players realize that this is a way to unantag people permanently and keep them in the round?

**Comment by ShiftyRail** [comment]
This is going to be Deconvert 2.0, revenge of the Deconvert, but even more tedious.
You kill the guy, borg him, and when the coast is clear you can gift him a new body.

If the point of Cult 3.0 is /no deconverts/, then you're creating a way to get around that.

Maybe have the proc displaying faction icons checking if the subject is a borg and denying him.

**Comment by DeityLink** [comment]
For now we'll remove the role from their mind when they get borged so at least they don't keep the HUD. I'll make it so they get the role back somehow later.
