### ISSUE TITLE
Mind transfer not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20693]
(WEB REPORT BY: manfreed REMOTE: 172.93.109.202:7777)
# Revision
4d3411260f8e649396e3c11e6d7024287556d11a

# Description
Was wiz and got lasered at seconds after teleport to station.
Magic Missiled the sec officer shooting and tried to mindswap 4 times. Nothing happened.

# Steps to Reproduce
Try the mind transfer spell

# What you Expected
To mindswap into the sec guy

# What Actually Happened
I helped him up

**Comment by jknpj** [comment]
Unable to reproduce
