### ISSUE TITLE
Mice worn on your head are not visible

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20690]
#### Steps to reproduce
- Wear mouse on head
- in-world sprite is unchanged

**Comment by jknpj** [comment]
lost with datums?

**Comment by DamianX** [comment]
I think it happened before datums.

**Comment by DamianX** [comment]
I have an update on this: it's only black mice.

**Comment by Kurfursten** [comment]
Apparently we never had black mouse support, it's not even in the code.
