### ISSUE TITLE
Can't deconstruct windoors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20691]
(WEB REPORT BY: szuflox REMOTE: 172.93.109.202:7777)
# Revision
4d3411260f8e649396e3c11e6d7024287556d11a

# Description
It's impossible to deconstruct windoors because first step, using crowbar on open one, doesn't do anything.

# Steps to Reproduce
Try to use crowbar on open windoor
# What you Expected
Pulling out the electronics 
# What Actually Happened
Nothing happens

**Comment by jknpj** [comment]
question: was the windoor open?

**Comment by MadmanMartian** [comment]
can confirm, tried every tool on a windoor, both open and closed.

When open, attacking it with an item just closed it.

**Comment by ghost** [comment]
Thirding, crowbarring an open windoor with valid access doesn't let you pry the circuit out
