### ISSUE TITLE
Spider migration season is still open

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20698]
see #20518 #20533

**Comment by jknpj** [comment]
roid

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Sure this isn't Roid's 800 maint spiders & engine spiders & maint free ship spiders?

**Comment by SonixApache** [comment]
It is, but the issue is that they decide to escape and cause havoc *every round*.

**Comment by SonixApache** [comment]
It's also still spider migration season on Metaclub! Yay!

**Comment by SonixApache** [comment]
There's a spider in deff maint, east side, near the brig. He REALLY enjoys being in the brig, though.
Every round. At roundstart.
