### ISSUE TITLE
Cult 3 forge has a fucked up icon and description

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20707]
#### Description of issue
![image](https://user-images.githubusercontent.com/6307265/48470862-e848ff00-e7f2-11e8-86a8-855d358309db.png)

#### Steps to reproduce
- Be cultist
- Summon forge
- Examine it
- Pic related

**Comment by DamianX** [comment]
Spire has the same thing
![image](https://user-images.githubusercontent.com/6307265/48472306-4aefca00-e7f6-11e8-8377-3bbc9862f04e.png)

**Comment by DeityLink** [comment]
I don't know how icons-in-chat work exactly, but maybe they cannot render overlays, which would explain that. The forge and spire are 64x64 invisible sprites, all of their looks are overlays, which is the only way I found to have some parts animate their color/alpha.

**Comment by Exxion** [comment]
The issue is a null/invalid `icon_state`
If you want something to always be invisible, it should either have no `icon` or it should have a valid `icon_state` corresponding to a blank sprite (other than the default one)
