### ISSUE TITLE
The invisible posibrain

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20701]
(WEB REPORT BY: charmstruck REMOTE: 172.93.109.202:7777)
# Revision
ebe3166fbf8ae43c78a975d9e4940ed22b3e3d6b

# Description
Was destroyed as an emagged MoMMI while attempting to ventcrawl, but the posibrain that popped out was invisible? I was still able to talk, but the sprite for the brain did not show up in the right-click or alt-click menus. Interestingly enough, the invisible posibrain could be moved via locker.

# Steps to Reproduce
Not sure how reliably it can be reproduced, but I vaguely described how it happened

# What you Expected
A visible posibrain that could be picked up with and generally interacted with to pop out of my corpse

# What Actually Happened
An invisible brain popped out?

**Comment by SonixApache** [comment]
Hey, I had the same issue.
Emagged mommi, beaten into submission, exploded into an invisible untouchable posibrain.
