### ISSUE TITLE
Cult 3 tome background doesn't load sometimes

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20705]
![image](https://user-images.githubusercontent.com/6307265/48470359-83d97000-e7f1-11e8-90cd-56cd44c92649.png)

#### Steps to reproduce
- Be cultist
- Open book
- Browse the pages
- Pic related

**Comment by DeityLink** [comment]
Known bug, it's a cache error I think, don't really know what I could do to fix it, just close and re-open it.
