### ISSUE TITLE
Using a smithed hammerhead/pickaxehead to create a hammer creates something of a lower quality.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20712]
(WEB REPORT BY: archsunder REMOTE: 172.93.109.202:7777)
# Revision
4eefdcef89c9f2db5d85ee83eabb9241ba5f6b74

# Description
Unsure if this is intended, but attaching handles to forged blacksmithing parts that have a higher quality seem to just reroll the quality of the finished product.
# Steps to Reproduce
1) Make hammer/pickaxe head of normal or higher quality
2) Attach handle
3) Receive poor or worse
# What you Expected
Quality of smithed head to matter
# What Actually Happened
Quality of smithed head didnt SEEM to matter

**Comment by ghost** [comment]
Seconding, handle rerolling quality is kind of a bummer when you get a superior head and it drops to shoddy after you stick the handle on it.
