### ISSUE TITLE
putting plasma in a welding tool should do something

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#20719]
#### Description of issue
[featurerequest]
You can remove reagents from a welding tool and put other stuff in it. 
That includes plasma the extremely flammable stuff known as plasma.

Sadly, trying to light the tool with plasma doesn't do anything at all - just bitches that you're outta fuel.

#### Difference between expected and actual behavior
fill welding tool with plasma, turn on, get turbo welding
or
fill welding tool with plasma, turn on, tool explodes
vs
fill welding tool with plasma, try to turn on, tool doesn't work

#### Server revision
ce025fc8d46539458bac15fcb48a7b7b2127f4c9

**Comment by Kurfursten** [comment]
Instead of exploding it might be amusing to have it THROW you in the opposite direction that you're facing, possibly with burns/eye damage.

You could even use it as a ghetto jet booster alternative to extinguishers when on an office chair / exploring space
