### ISSUE TITLE
bolas fucking disappear when you throw them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20724]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
4591d43d0e85d6dd0675d9e7750e70432bc013b9

# Description
they just vanish on a miss

**Comment by DamianX** [comment]
just don't miss

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
As in they go invisible or they descend to the shadow realm?

**Comment by Chazach** [comment]
100% shadow realm

**Comment by Inorien** [comment]
just dont throw them that way
t. steve jobs

**Comment by Exxion** [comment]
They also vanish on a hit if the hit mob isn't a human
