### ISSUE TITLE
Attempting to put a core sample bag back into the core sampler will put the core sampler into the core sample bag.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20729]
(WEB REPORT BY: archsunder REMOTE: 172.93.109.202:7777)
# Revision
f1a832621c4f2f890b81bd4fc20c491f72b0d698

# Description
Sampler go in bag.
# Steps to Reproduce
Attempt to put core sampler bag back into core sampler.
# What you Expected
Core sampler bag to go in core sampler.
# What Actually Happened
Core sampler went into core sampler bag.

**Comment by BarneyGumball** [comment]
#20515
