### ISSUE TITLE
Astral Journey

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20735]
(WEB REPORT BY: wentafk REMOTE: 172.93.109.202:7777)
# Revision
f1a832621c4f2f890b81bd4fc20c491f72b0d698

# Description
Astral Journey rune is unlike how it used to be. May be intended due to the rework but it's a bit shit.
# Steps to Reproduce
Get on Astral Journey Rune and activate it
# What you Expected
Screaming at ghosts directly to get in the blade. 
Haunting your target/spessman to find out what is going on easily
# What Actually Happened
No lungs to talk to ghosts(apparently that matters to your ghostly form)
No Haunt available unless they talk. Only option is to return to body

**Comment by DamianX** [comment]
The actual bug is that there is a haunt option available if ghosts talk. Also they're not supposed to hear dead chat, according to what Deity told me.

**Comment by DeityLink** [comment]
>Astral Journey rune is unlike how it used to be.

Well yeah, that much and all the points they listed were intended.
Indeed I had completely forgotten you could haunt mobs from chat (despite doing it all the time as observer)

**Comment by DeityLink** [comment]
Also you don't have to scream to ghosts to get in the blade, they automatically get a prompt when you plant it on an altar.
