### ISSUE TITLE
Diona nymphs can't be non-con converted.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20734]
(WEB REPORT BY: ammy55 REMOTE: 172.93.109.202:7777)
# Revision
f1a832621c4f2f890b81bd4fc20c491f72b0d698

# Description
Diona nymphs don't get killed when refusing cult conversion.
# Steps to Reproduce
Be a diona nymph
get converted
say no
# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
So they choose to get devoured but get converted anyway?
