### ISSUE TITLE
[Balance] Unintended (?) side-effect of converting through implants 

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#20743]
[balance]

#### Description of issue

In cult 3, you can convert through implants. This also removes the implant from the person being converted, and make them resist further implants.

A side effect is that all cultists seem to resist implants now. This makes cult-checking much easier, faster, and not require a chaplain, since the stock implants in brig (3 cases) are enough to check 12 (twelve) people. If you're low on supplies, you can also ring cargo.

This seems unintended to me because it's a heavy nerf to cult (making them that much easy to uncover).
Although, now that implanted people can be converted, they shouldn't be implanted again (because I think even cult mains here would think it's silly ; remove implants completly at this point)

I'd be fine with cultists never having been implanted to accept implants.

**Comment by DeityLink** [comment]
I'll ponder about it.

**Comment by SonixApache** [comment]
It also eats an implant every time you catch a bloody boi, which is annoying.

**Comment by Caboozles** [comment]
Arguably the only defense Sec has against converted sec officers is that they can tell when an implant has been removed from someone important.
People who have never been implanted accepting implants is much more reasonable.
