### ISSUE TITLE
Ping meter bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20756]
(WEB REPORT BY: mask2697 REMOTE: 172.93.109.202:7777)
# Revision
6752a2d2f9e752c4d5ac6aa1744f2bbf6112b55a

# Description

I can confirm that the latency monitor is not consistent and is least reliable when one is actually experiencing lag, which defeats the entire purpose of the thing.
# Steps to Reproduce

get laggy on an inconsistant wifi system
# What you Expected

Lag meter to show lag
# What Actually Happened

lol ur fine until your gun doesnt shoot or you realize you cant move in a straight line.

**Comment by SonixApache** [comment]
the ping meter is only for goonchat

**Comment by Exxion** [comment]
It only updates every 30 seconds, so obviously a lagspike shorter than that won't always be recorded
The meter is there to show your normal ping, not your jitter
Just like in most games, except more so

BYOND is TCP-only with an additional verification layer on top, so trying to get a ping meter closer to real-time would essentially DDoS the server

**Comment by SGuivenne** [comment]
So what youre saying is we need to DDOS the server more until it develops an immunity?

**Comment by Inorien** [comment]
Give it small lag spike DDOSes to build up immunity to the big DDOS attacks
