### ISSUE TITLE
Create antagonist wizard someone made someone on station a wizard

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20754]
(WEB REPORT BY: chazach REMOTE: 172.93.109.202:7777)
# Revision
43d7adfc05f9d0ab08dc59371d28aef54dbfedbe

# Description
they got put into the wizard faction but got no spellbook or robes

**Comment by Killette2** [comment]
Stealth Wizard

**Comment by bathosbathtime** [comment]
I hit the create wizard button earlier today and it spawned them in arrivals naked so this is still happening.
Map was deff, during a vamp round.

**Comment by ShiftyRail** [comment]
Use the midround ruleset button ree
