### ISSUE TITLE
Inverted Vision bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20765]
(WEB REPORT BY: uhex REMOTE: 172.93.109.202:7777)
# Revision
46405f56b416a3da2232344c3a4fa4e0db625a79

# Description
Dying with inverted vision on does not revert the vision, nor does pressing the inverted vision button.
# Steps to Reproduce
Become mushroom-man, turn on inverted vision, die. Become mushroom-man again, press button, cry.
# What you Expected
My vision reverted back to normal or at least when I pressed the inverted vision power button
# What Actually Happened
The inverted vision is permanent.

**Comment by DamianX** [comment]
same as #18491
blocked on pomf updating to 1454
