### ISSUE TITLE
Breaking tape very, very, VERY rarely sends you to nullspace.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#20767]
#### Description of issue
On the tin, I had this happen over a year ago as a borg breaking engineering tape but since it couldn't be reproduced I decided not to make an issue, cannot recall when. Might as well do it now.

![null tape](https://user-images.githubusercontent.com/6732634/48750497-7e06e300-ec66-11e8-84f6-29cc28564078.png)

#### Difference between expected and actual behavior
Not to be nullspaced.

#### Steps to reproduce
No fucking clue, in both cases I was in harm intent, first as a borg, now a human officer.

#### Length of time in which bug has been known to occur

A year ago, give or take.

#### Server revision

46405f56b416a3da2232344c3a4fa4e0db625a79 
<!-- SELF LABEL YOUR ISSUE TODAY!

[bugfix]

**Comment by nuklearcellphoneg** [comment]
Feature
