### ISSUE TITLE
Constructed windows start fastened to the floor&cannot be built on grilles

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#20808]
#### Description of issue
bugfix
When you click a grille with glass, you attack the grille on any intent and cannot build a window on it.
Windows built are fastened to the floor from the beginning.

#### Difference between expected and actual behavior

I want to place windows on grilles and they shouldn't be fastened to the floor when created

#### Specific information for locating

Probably one of the recent meme-merges

#### Length of time in which bug has been known to occur
A day or two

#### Server revision
f410ab446bf2d295613bf4d99d4123834e1b7f0b

**Comment by DamianX** [comment]
#20611
