### ISSUE TITLE
Various Cult bugs as Diona Nymph, and with Soul Gems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20811]
(WEB REPORT BY: jackmassacre REMOTE: 172.93.109.202:7777)
# Revision
f410ab446bf2d295613bf4d99d4123834e1b7f0b

# Description

As Diona Nymph, cult converted me, succeeded, but did not receive cult spells, and was unable to use tome to do anything "you don't have the dexterity to do this" when clicking on a rune name. Could still activate existing runes on ground, though.

After realizing uselessness, asked to be killed and put into soul gem to create artificer. Once I was punched to crit as diona nymph, heard successful soul shard/gem sound, but did not actually get absorbed, then healed from crit and saw the cultist use the soul gem (filled with nothing) on a construct shell, creating a blank Artificer controlled by no one.

Tried a few more times with similar results, then finally succumbed while crit, and ghosting failed to prompt for turning into a shade like other cultists can. Additionally, ghosting made my corpse vanish, and re-entering corpse made it re-appear on the ground.

Admin had to force my soul into the brainless artificer, and then had to manually set me to cult faction due to the artificer having no faction.

**Comment by DeityLink** [comment]
What in the fuck.

**Comment by DeityLink** [comment]
Soul gems have received an overhaul so I'll consider this fixed until it gets reported again.
Also dionaes should be able to write runes now.
