### ISSUE TITLE
Feature Request: Buff forges 2k18

### ISSUE THREAD

**Issue by Jubisloviu** [d3athrow/vgstation13#20816]
-Buff the forge so it can heat up iron recipes with only wood
in my honest opinion it should work, but slower than plasma
-Remove being able to use a welding tool to heat up the metal
what's even the point of the forge if you can open any yellow locker and have a forge in your pocket everywhere?

**Comment by ghost** [comment]
People need to spread awareness of planting grass for grass tiles, use them on plating, then shovel or spade them for sand to make sandstone. It's reasonable enough.
