### ISSUE TITLE
[Feature] Emag Borg Master-Identifier

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2082]
Just like how Revolutionaries can see fellow revolutionaries and cultists see fellow cultists, add a flag next to a borg's master for emagged borgs. 

Why: Most masters go into hiding after ordering their borgs to go mass murder, and when trying to hide/escape are often killed in the indiscriminate massacre by their own emagged pets. So it would be useful if borgs had a flag to identify their emagger.

**Comment by ririchiyo** [comment]
Discussed in #3407.
