### ISSUE TITLE
INFINITE MONEY HACK 100% LEGIT

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20823]
#### Steps to reproduce
- Keep buying something from the vending machines.

That's it. Having no money prints an error but it still vends the item.

![image](https://user-images.githubusercontent.com/6307265/49009881-f0e5f180-f171-11e8-8cd3-9268e838f844.png)

The runtime error is unrelated.

**Comment by ShiftyRail** [comment]
We communist station now

**Comment by SGuivenne** [comment]
Its just like the Venezualan Government!

**Comment by Exxion** [comment]
One billion percent tested

**Comment by Killette2** [comment]
Not gonna lie, I abused this with the mining vends when I didn't have enough funds and just didn't tell anybody because how much easier it made antagging. Swing the hammer I've been a bad boy
