### ISSUE TITLE
Blob can still use the spooky sprites

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#20833]
#### Description of issue
#20697 didn't fix it apparently
![image](https://user-images.githubusercontent.com/6307265/49055888-a27c3580-f1f9-11e8-929f-f5b1aaa47f1d.png)

#### Steps to reproduce
- Use the "Spawn a blob conglomerate" option under "Secrets"

#### Server revision
39b1371cb904bba238b5418fe22dc6d19dce9738

**Comment by Killette2** [comment]
I didn't know this existed and I'm mad I never got to use it

**Comment by MadmanMartian** [comment]
Why couldn't deity just add this paid-for appearance to the list of selectables, rather than forcing it for halloween through a completely different method that's snaked all over the codebase?

**Comment by Kurfursten** [comment]
it is on the list of selectables in addition to being spaghetti coded

**Comment by MadmanMartian** [comment]
eaugh
