### ISSUE TITLE
Autodrobe Pirate Uniform

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20830]
(WEB REPORT BY: angryturnip REMOTE: 172.93.109.202:7777)
# Revision
39b1371cb904bba238b5418fe22dc6d19dce9738

# Description
The AutoDrobe is giving me soviet uniforms when I'm selecting pirate uniforms, and it's removing one pirate uniform from the machine's inventory every time
# Steps to Reproduce
Select Pirate Uniform
# What you Expected
Pirate Uniform
# What Actually Happened
Soviet Uniform

**Comment by Kurfursten** [comment]
Could not reproduce on live, I even tried 20 different things including all pirate and soviet gear

Notably soviet uniforms are just below pirate uniforms.
