### ISSUE TITLE
Slime tiles suck so hard

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#20849]
They make slime people go too fast to have control, even if you slow yourself such as having magboots on or are starving. When crowbarred they get destroyed instead of pried up easily making replacing the damage annoying. Nobody likes slime tiles other than putting them in a straight line in science to make you go in and out of science faster. How would we make a decent concept not go to waste like this?

**Comment by Irradiation** [comment]
>Waaaah, I'm going too fast
Get out, you're not worthy of going at 200 sanics/hour

**Comment by SGuivenne** [comment]
Ur 2 slow
