### ISSUE TITLE
cards sometimes turn invisible/disappear while using hands of cards

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20840]
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
don't know how to reproduce specifically, just use hands of cards in general

**Comment by Exxion** [comment]
https://github.com/vgstation-coders/vgstation13/blob/1d45da69591f630f53c860dab4ed501db80bdd06/code/modules/games/cards/playing_cards.dm#L256
Tab it once and replace `src` with `card`
