### ISSUE TITLE
Magmaws shoot bullets instead of fire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20852]
(WEB REPORT BY: bittervanilla REMOTE: 172.93.109.202:7777)
# Revision
eacfee5c088748f840e15c85ba343823b068a8d5

# Description

Magmaws will fire bullets at walls and miners instead of breathing fire as they used to. Miners aren't equipped to deal with this kind of firepower!

# Steps to Reproduce

1. Search local Magmaw Den.
2. Peek inside for free dug ores.
3. RATATATATATA.
4. Bleed out and die.

# What you Expected

Side stepping plumes of fire that reach out from the magmaw, no saftey behind the box and rocks torn apart.

# What Actually Happened

The magmaw eats Plasma ore!
Xiao Mei Feng is hit by the projectile in the chest!x5

Rocks aren't affected by the shots but miners have it much worse.

**Comment by spoonylove** [comment]
im curious how this happened. very amusing.

**Comment by Exxion** [comment]
The base `projectile` is a bullet
The var in a particular proc that held the projectile to fire was, of course, just typed as `projectile`
It used `new()` without specifying a type properly, so everything was bullets (when fired by that particular proc, using a typepath rather than an instance)
