### ISSUE TITLE
cant click&place reinforced glass on grilles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20850]
(WEB REPORT BY: assburgeri REMOTE: 172.93.109.202:7777)
# Revision
38b529775f93aa948cd09c7639c41da69f7140f4

# Description
cant click&place reinforced glass/window on grilles
# Steps to Reproduce
click grille with reinforced glass
# What you Expected
u know
# What Actually Happened
grille got dunked by the glass

**Comment by Kurfursten** [comment]
#20808

**Comment by Exxion** [comment]
As it happens, this corresponds exactly to the part of #20808 that isn't fixed by #20817

**Comment by SonixApache** [comment]
@MadmanMartian fix it or riot
