### ISSUE TITLE
retarded firelocks in deff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20867]
(WEB REPORT BY: whoru REMOTE: 172.93.109.202:7777)
![](https://i.imgur.com/Pn773Tv.png)
once something wakes them up they realize they're right up against space so they will stay that way forever

**Comment by Killette2** [comment]
We really need to go on a firelock purge and get rid of some of the stupider firelocks in this game. Especially some of the back to back ones some maps have
