### ISSUE TITLE
Admin Player Panel Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20868]
(WEB REPORT BY: publicenemymaipai REMOTE: 172.93.109.202:7777)
# Revision
f6bc772795c2b19d24822b37ded68d724bd64685

# Description
The Admin Player Panel does not have a dropdown menu anymore for ghosts
# Steps to Reproduce
Be an admin, press f6 hover over a ghosts name
# What you Expected
A menu extension containing PP-N-VV-TP-PM-SM-JMP
# What Actually Happened
Nothing

**Comment by ShiftyRail** [comment]
Duplicate of #20865
