### ISSUE TITLE
Player Panel : unable to hover on players who joined as ghosts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20865]
(WEB REPORT BY: shiftyrail REMOTE: 172.93.109.202:7777)
# Revision
3b7b390a22712157267e23dde9da1af351486a05

# Description

[adminstration]

As admin, using the player panel, hovering with the mouse on a player who joined as a ghost doesn't expand it to see the Notes, Player Panel, etc, etc.

It works on `new_players` and on people who ghosted from dead (or living) bodies.

**Comment by ShiftyRail** [comment]
No longer an issue
