### ISSUE TITLE
Windows Not Placing Correctly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20877]
(WEB REPORT BY: disgruntled REMOTE: 172.93.109.202:7777)
# Revision
8479ed8d8dc54b1784366561e719335b71459e22

# Description
When a window is placed via the build menu when using a sheet of glass/re-glass/plasglass/re-plasglass, the window is placed loose, but the game appears to think that it has already been fastened.  Thus, to actually fasten the window, one must undo the fastening process (screwdriver>crowbar>screwdriver), then redo it.
# Steps to Reproduce
Hold a sheet of glass, press the use key, select one/full window.
# What you Expected
It should either place loose and require normal fastening, or place fastened and require no further action.
# What Actually Happened
The window was instead created in some kind of superposition where it was both fastened and loose at the same time.  The game says it is fastened, but it is not.

**Comment by Kurfursten** [comment]
@DamianX tested, no longer a bug as of martian fixes
