### ISSUE TITLE
Glass Floors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20871]
(WEB REPORT BY: morena REMOTE: 172.93.109.202:7777)
# Revision
f6bc772795c2b19d24822b37ded68d724bd64685

# Description
Reinforced glass to make glass tiles creates Plasmaglass floors. This is inconsistent.
They also can be placed on platings, but show no signs they've been placed and the tile still shows up as "plating". 
Either they shouldn't be allowed to be placed on plating, or should still have some kind of sprite for it.
Also just don't make normal glass suddenly turn into plasma glass.

**Comment by vampirebat74** [comment]
Because of these, borgs can no longer create glass floors. Please make them an option for eng borg material synths as well.
