### ISSUE TITLE
Windows created from the glass menu have secure issues.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20879]
(WEB REPORT BY: boosterrooster REMOTE: 172.93.109.202:7777)
# Revision
acc1ff7b3c7d011fa2eb1235d800c2742da22179

# Description
Glass windows created from the new menu are "firsmly secured based on their desc but are actually unsecure AND secure. Trying to weld one down to get a sheet back just hits it and you can drag them. You have to unsecure and resecure them for them to be back to normal.

**Comment by Exxion** [comment]
Duplicate of #20877
