### ISSUE TITLE
Infinite Exosuit Air

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20878]
(WEB REPORT BY: nogeeef REMOTE: 172.93.109.202:7777)
# Revision
acc1ff7b3c7d011fa2eb1235d800c2742da22179

# Description
After gas tank breach in the Ripley Exosuit, the airtank pressure rapidly drained to 0kpa. However, without internals, my character inside experienced no oxygen loss.
# Steps to Reproduce
1. Enter Ripley
2. Turn on internal airtank
3. Damage the Ripley (in this case I tangled with a Hivelord) until a GAS TANK BREACH occurs
4. Wait for the airtank pressure to reach 0kPa
5. Breath easy. No problems, even out on the roid.
# What you Expected
To die of oxygen loss, as I had no internals and the mech was empty.
# What Actually Happened
No oxygen loss experienced, no damage taken, I was fine.

**Comment by SGuivenne** [comment]
Well yeah, but could you evolute?

**Comment by Exxion** [comment]
I could be wrong, but I don't believe this is a bug. The tank breach only drains air from the tank, not the cabin. So even if the air tank is empty, you still have the air in the cabin to breathe.

EDIT: The cabin has a volume of 200L and a breath is .5L, so each breath uses .25% of however much oxygen is in the cabin
If my math is right, it would take nearly four minutes for you to start gasping after your tank was emptied

**Comment by Exxion** [comment]
My math was clearly wrong because it takes way more than four minutes
But yes, you do eventually start suffocating once the cabin gets too low on oxygen
