### ISSUE TITLE
Stunprods don't work.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20885]
(WEB REPORT BY: subs455 REMOTE: 172.93.109.202:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
Stun Prods don't work. Assembling them and trying to activate them tells you it is out of charge, despite there being a 100% charged power cell in it.
# Steps to Reproduce
Build a stun pod and try to turn it on
# What you Expected
The stunprod to turn on and work normally.
# What Actually Happened
It stays off.

**Comment by Pathid** [comment]
Not a bug if you were using a basic cell. Stunprods spend more charge per hit than those can carry.

**Comment by DamianX** [comment]
It should give some sort of message if that's the case.

**Comment by Pathid** [comment]
Consider that it's just some wirecutters on a stick connected to a battery. Realistically it's a stretch that it has the level of feedback it currently has. You'd just prod somebody and it would fail to stun them.

**Comment by SonixApache** [comment]
"you notice a distinct lack of hum from the coils" for the prod, and "The power light stays dark" for actual batons.
