### ISSUE TITLE
Window Bugs

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#20880]
@MadmanMartian 
* Pushing a directional window facing left or right (4 or 8) rotates it so that it is directionally facing south (dir 2) regardless of your angle of approach; pushing one facing north causes it to rapidly shift back and forth between directions
* Unanchored windows cannot be deconstructed with a welder
* Fully anchored windows (all 3 steps, screwdriver crowbar screwdriver) can be deconstructed with a welder
* All construction and deconstruction messages are reversed. (e.g.: securing the window shows You unfasten the reinforced window from its frame., You pry the reinforced window from its frame., You unfasten the reinforced window's frame from the floor.)

Parts 2-4 of this bug are obviously just reversed checks but 1 is a bit  odder

**Comment by MadmanMartian** [comment]
what the fuck is windows

**Comment by ghost** [comment]
windows are not in a good spot right now

**Comment by MadmanMartian** [comment]
Working on it right now.
The direction stuff is a LEGACY bug. On movement, it resets to its ini_dir, which defaults to south.

It's always been like this, and nobody's noticed.

**Comment by Exxion** [comment]
>It's always been like this

No, they used to not turn at all when dragged
If you look, you will see that `ini_dir` is set when rotating windows
