### ISSUE TITLE
wizards are keeping the flavor text from their static once again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20903]
(WEB REPORT BY: whoru REMOTE: 206.221.180.138:7777)
not like most flavor texts aren't already ooc in ick memery

**Comment by Intigracy** [comment]
Bringing it back was a mistake

**Comment by ShiftyRail** [comment]
They're keeping everything, flavour text, appearance, and handicaps.
Pretty sure that roundstart plasmeme wizard could be a thing, should a lucky person be drafted.
The roundstart guys are just spawned in the cube and then teleported to wiz's den and equipped.
Pretty sure if you pass your mouse over them roundstart, you'll see that they even keep the name.

I think I already made an issue about this.

**Comment by SonixApache** [comment]
magic mirror in the den when
