### ISSUE TITLE
You can bus in a head rev on the asteroid.

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#20916]
#### Description of issue

[roleissue]
This is a problem, because then, it counts as having escaped the station, and counts as a rev defeat, which ends the round.
The obvious solution is to prevent admins from doing it.
More importantly,
**Should a rev defeat end the round ?** We live in a dynamic society now, after all.

**Comment by Exxion** [comment]
Keep in mind that as long as threat is still a limited resource, high-cost antags will deplete it and prevent most other antags from spawning for the rest of the round
