### ISSUE TITLE
Adding custom objective to factions results in the standard "Be yourself text" not editable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20929]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
93eec5f938bb974bfc04526cda0894643c2bc235

# Description
Faction objectives, not individuals ones. Doesnt allow it to be edited. (Only tried with wiz)

**Comment by ShiftyRail** [comment]
Works on my machine.
![work on my machine](https://user-images.githubusercontent.com/31417754/49540484-1f797000-f8c8-11e8-9da0-2131dbe3d555.png)

Make sure you select "custom objective". Not basic objective.
