### ISSUE TITLE
Gun sprites: Rearmed

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#20938]
Somebody suggested that we redo all the gun sprites, and a lot of spriters jumped on board.

This issue will be the 'repo' of gun sprites.

When posting sprites, please state what they will be replacing.

**Comment by TheBimmer231** [comment]
First round!

https://cdn.discordapp.com/attachments/239836068491296788/522503897022201856/gunpackage1.dmi
![image](https://user-images.githubusercontent.com/22187456/49895739-890df700-fe51-11e8-8813-7495c64385ca.png)

**Comment by Servalfang** [comment]
oof
