### ISSUE TITLE
Feature Request: Set DNR

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20936]
(WEB REPORT BY: mask2697 REMOTE: 206.221.180.138:7777)
# Revision
c11556c666b091fd3474a65e011c00bc404f38b5

# Description

This is one of those quality of life features that exists on several other servers, most notably goon.  The ability to set a Do Not Rez flag that prevents you from being signed up for mobs or to be cloned.  

This is good if you want to observe in the background and not reject roles repeatedly.  

It'd also help with things like people spawning in as AFK borers or xenos or whatever.

**Comment by Exxion** [comment]
This is what setting your role prefs to never does
Pressing never when polled has this effect for only the current round, though there's no way to do that before you're polled
So basically it would be pretty much as simple as adding a button

And again, you can self-tag.
