### ISSUE TITLE
Xenos can be autotraitored

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20941]
(WEB REPORT BY: lunstra REMOTE: 206.221.180.138:7777)
# Revision
a33493e35e3a09d5584c03d6be8790785e5e082c

# Description
What it says on the tin
# Steps to Reproduce
Be a xeno and have dynamic memes happen I guess
# What you Expected
For xenos to be a hive mind of killing machines that only care about the hive
# What Actually Happened
Mission specifications decrypted, welcome to the syndicate

**Comment by SonixApache** [comment]
xeno makes deal with syndies to escape containment, makes sense
real issue report is "they get an uplink but no real way to use it"
