### ISSUE TITLE
Mulebot can't run over xenos

### ISSUE THREAD

**Issue by BBHazard** [d3athrow/vgstation13#20942]
[easy]
#### Description of issue
Due to probably mob shitcode or something, mulebots can't run over xenos even if they can run over humans.
Probably applies to other human-like things as well.  Worth checking those.

#### Difference between expected and actual behavior
So mulebots, when hacked, can run over people.
Right.
So, I tried to run over a xeno.  It's people-sized, can be knocked over like people can.
Rammed into 'em.  Nothing.  Not even a message.  Just stopped dead in my tracks.
Tried multiple times, made sure I had a running start, all the usual stuff.  Nada.

#### Steps to reproduce
Be a pAI in a hacked mulebot, try to run over a xenomorph.

#### Server revision

a33493e35e3a09d5584c03d6be8790785e5e082c

**Comment by SGuivenne** [comment]
goddamn it, this is a game breaking bug, how will we fight the beno menace off our death chariots.

**Comment by Pathid** [comment]
![mulebot test](https://user-images.githubusercontent.com/31839805/49570131-adfee900-f8ea-11e8-8f3c-feaedf1fd6e7.PNG)

Works for me. And although the simple mob versions seem to be semi-immune to it, you can at least go over them. I suspect your owner didn't cut the right wire on the mule if you're stopping dead.

**Comment by Kurfursten** [comment]
@Exxion close
