### ISSUE TITLE
Vanishing cult HUD

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20951]
(WEB REPORT BY: lexuskit REMOTE: 206.221.180.138:7777)
# Revision
02d9f67b236528005c90a948bb90c72dde8e3c86

# Description

Became a slime person earlier in the round, then got culted, and died due to forge a forge's high temperature bullshit staying there forever even as I left vicinities. The cult HUD that allows you to tell friend from foe simply disappeared after I got cloned afterwards.

# Steps to Reproduce

Become slime person.
Get culted.
Die.
Get cloned.
HUD is fucking gone.

# What you Expected

The HUD to be there after being cloned.

# What Actually Happened

The HUD was gone and I couldn't tell who the fuck was a cultist or not.

**Comment by Kevak** [comment]
This also happens to moshrooms if you cult em before they grow up.

**Comment by Dacendeth** [comment]
Being cloned at all removes huds I think, at least vamp thrall gets removed when you get cloned even though you're still a thrall.
