### ISSUE TITLE
Giving a Grey a swirlie doesn't utterly fucking annihilate them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20961]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
c4145c9af771d8406cf5797ca107fbf924e7ad95

# Description
Attempting to return a grey to his/her natural environment in the shitter does not cause severe damage
# Steps to Reproduce
Apply grey to toilet for swirlie
# What you Expected
*scream
# What Actually Happened
flush

**Comment by vampirebat74** [comment]
Based and redpilled
