### ISSUE TITLE
Custom strike teams spawn with deathsquad gear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20973]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
a3f253d2185b2677bab9c86637f0c2215ad5fe37

# Description
from the thing on the admin panel to make a custom strike squad, they spawn with full squiddie stuff

**Comment by Sooose** [comment]
Happened again in the round just now, very annoying when you're trying to set something up.
