### ISSUE TITLE
Big dump of virology symptom ideas+improvement suggestions

### ISSUE THREAD

**Issue by UndeadOrb** [d3athrow/vgstation13#20979]
[<featurerequest>]
Drummed up a bunch of viro ideas that'll make it less of a lynch-on-sight role, some are pretty raw and would need balancing. Couple of people were bitching up the crude ideas in thread, so they're not as unbalanced as they were.
Notes: Make airborne strains less common. Almost every virus is airborne, mostly because fluid based or bloodborne diseases spread too slowly to be useful, but some symptoms being contained very well to a few patients would be better than absolutely everything being extremely virulent. 
Part of the reason why Viro is so bad right now is because a good disease is still a nuisance, and your odds of being gibbed by something that was just giving you Hyperzine are too high. More positive or neutral symptoms means that having a virus isn't always bad, hence why I even wrote all that shit, and turns it into less of a trust exercise, as even full random viruses could be completely positive. 
Giving warning beforehand before a symptom begins is a good way to make stuff like Gibbingtons less of an immediate round ender, as they could panic and sound the alarm before turning into red goo giving people a chance to avoid a horrible stage 4 on an otherwise good disease that the tator Viro might have handed out.
The chem synth symptoms would have to be extremely minor to avoid being overpowered, giving someone the ability to heal welding torch burns over a few minutes is a good stage 2 or 3 but any more than that makes people too robust. Resistances and stuff are better as they are just tanks with weaknesses, not self-healing gods. Stage 4's are a bit different as I sort of went with the established "everything between Delightful Syndrome to Gibbingtons is fair game" so stuff gets a bit more creative.

Stage 1:
-Infected slowly synthesize Hyronalin, giving them slightly heightened resistance to radiation.
-Infected is better at managing their body temperature, sweating or shivering more efficiently, able to handle hotter or colder climates without harm at the cost of needing more nutrition after exposure to these climates. Useless for little more than a walk through a freezer or near several fires.
-Causes the infected to synthesize Spaceacillin, slowing progression of diseases. 
-Causes the infected to randomly and uncontrollably greet everyone they meet, and bid them farewell when parting. Impairs communication.
-[FILLER]Causes the infected to feel minor soreness with no serious effect.

Stage 2:
-Causes the infected to synthesize Phalanximine, causing baldness and radiation damage over time but heightening toxin resistance.
-Causes the infected to become immune to genetic shifting, automatically curing genetic disabilities but also positive effects from the works of Genetics. Arguably beneficial. Does not cure virus symptoms.
-Causes the infected to grow much denser bones and automatically synthesize milk, granting a significantly stronger skeletal system. Does not fully counteract the effects of Fragile Bones syndrome.
-Causes the infected to develop hawk-like vision, increasing their view range.
-Causes the infected to yell everything they say, greatly increasing vocalization range, and copying many of the effects of the megaphone, but also removing the ability to whisper. Arguably beneficial.
-Causes the infected to cough up credit chips, causing significant inflation. 

Stage 3:
-Causes the infected to grow solid Uranium within their digestive system, which must be farted out. Causes radiation damage while within the body. Arguably beneficial.
-Causes the infected to grow solid gold bars within their digestive system, which must be farted out. Beneficial.
-Causes the infected to slowly synthesize Synthocarisol, granting resistance and slow healing from blunt damage.
-Causes the infected to randomly and uncontrollably cough up various plants, ranging from garlic to death nettle, of randomized stats. Arguably beneficial, until someone plants cyanide bananas with the spreading trait.
-Causes the infected's saliva to become extremely acidic, causing no harm to the host but granting a bite that causes significant toxin damage.
-Causes the infected to grow a random piece of irremovable Security headwear (uniform caps, helmets) and a wooden baton they cannot drop. Also causes the infected to automatically shout at wanted persons (aside from themselves) when they enter their line of sight. Arguably beneficial.
-Causes all of the infected's organs to work in overtime, causing hyperenergy (similar to Hyperzine's effects) due to increased oxygen content in the fast-moving bloodstream. Also causes more rapid bleeding, but more rapid clotting of wounds, as well as greater resistance to low-oxygen environments, more rapid synthesis of medicines or poisons in the blood, and a more efficient stomach. Can cause appendicitis. (would need adjustment to not make you a superpowered, more downsides from overuse or similar)

Stage 4:
-Allows the infected to synthesize a large dose of Leporazine at will, as well as greatly increasing lung strength for a short period, granting the ability to spacewalk for short durations unprotected. (20s duration for 300s cooldown or similar)
-Causes the infected to become nearly immune to fire, as well as spontaneously ignite. Extreme temperatures such as plasma fire are still enough to harm the user, albeit far less so than usual. Arguably beneficial.
-Causes the infected to turn into a slime-person. 
-Causes the infected to suddenly develop the ability to speak and understand binary, as well growing an internal wireless transceiver for the AI comms, allowing communication with the AI and cyborgs.
-Causes the infected's body temperature to plummet with no ill effects, as well as synthesize small amounts of Cryodextrone, allowing not only automatic healing of all damage over time, but resistance to the cold of space. Slower than the healing effects of Delightful Syndrome.
-Causes the infected's muscles to rapidly develop into those of an Olympic-tier athlete, granting significantly higher movement speed (without the slow-resistance effects of Hyperzine) and punch/swing significantly harder. Thrown items are also tossed like javelins, dealing significant damage depending on the item, as well as traveling at significantly higher speeds and over longer distances. Extremely beneficial. Small chance the infected's heart bursts from overuse.
-Causes the infected to synthesize Creatine as well as become immune to it's overdose effects, effectively granting the Hulk ability.
-Causes the infected's body to synthesize massive amounts of Medical Nanobots, inevitably turning them into a Cyber Horror. At least it heals them beforehand.
-Causes the infected to rapidly increase in size, increasing unarmed damage, as well as causing them to grow large, powerful tentacles, which they can cast under the ground to quickly trip opponents like a Goliath.
-Causes the infected to cough up water balloons filled with Space Lube, which when popped, lubricate a fair area around the balloon. 
-Causes the infected's feet to turn into mopheads, constantly damp with Space Cleaner. Removes the ability to wear shoes, but without the slowdown and damage from glass, as well as causing them to clean tiles they walk on. Arguably beneficial.
-Causes the infected to occasionally become possessed by an unknown force, and mindlessly scribe a random Cult rune onto the floor. Causes mass panic and minor blood loss, not beneficial.
-Causes the infected to quickly grow a irremovable red Syndicate spacesuit and helmet. Allows spacewalking, but causes massive confusion and an aggressive Security team. Arguably beneficial.
-Causes the infected to suddenly need to breathe pure nitrogen, like a Vox. Vox are unaffected. Warns the infected beforehand, but usually causes lots of suffocation fatalities.
-Causes the infected to become extremely plant-like. This grants the ability to perform photosynthesis, slowly healing damage under strong light as well as removing the need to eat, but they take damage in the dark as well as taking significantly more damage from fire. Slowly progresses into forcing the infected to breathe high concentrations of Carbon Dioxide, not available in the normal air supply, but exhaling significant amounts of Oxygen.
-Causes the infected to become extremely gassy and rapidly and uncontrollably fart pure Oxygen into the air supply. This rapidly repressurizes rooms, but can quickly overpressurize normal areas if several infected are present, and makes fire extremely hazardous.
-Causes the infected to turn slowly turn into a Cluwne. Extremely dangerous if left untreated, they are immediately transformed into a Clown, but degrade into the far lesser form if ignored. Over two minutes, the infected loses their ability to talk, which is aggressively interrupted by honking, then their ability to grasp items, before losing their humanity entirely. Simultaneously causes incredible amounts of brain damage during degradation.
-Causes the infected to uncontrollably shit out bars of soap. Annoying but otherwise harmless, a good stage 4 for a beneficial virus.
-Causes the infected to randomly cough out large billowing clouds of smoke, which contain any chemicals currently in their body. Obscures vision and can be extremely dangerous if the infected has consumed poisons.
-Grants the infected the Midas Touch, turning any items they hold in their hand into gold. Turns the infected into a gold statue after 30 seconds. Other sentient beings can only be turned into gold if the infected successfully Grabs them with the grab intent, granting the uninfected the ability to escape what could be effectively a gib otherwise. Causes mass panic.
-Causes the infected to synthesize Carp Pheromone and slowly synthesize Carpotoxin, as well as vomit up live carplings. Will kill the infected over time, but not before they create a large purple hazard if left uncontrolled.
-Causes the infected to develop massive brain damage over time as well as replacing much of their spoken words with "uhhhh," causing widespread station shutdown that is difficult to cure. Those with head access, if infected and fully progresses, will immediately be gibbed, but otherwise nonlethal.
-Causes the infected to grow an unremoveable Bomberman helmet and uncontrollably shit out bombs. Causes massive depressurization and panic.
-Causes the infected to rapidly synthesize Heartbreaker and Mindbreaker Toxin, causing respiratory damage and massive hallucinations. Also causes slow synthesis of Spiritbreaker Toxin, causing a slew of effects, and also persisting after death and cloning. Makes the dead extremely hard to fully cure.
-Objects the infected touch or stand nearby will become sentient and wander aimlessly until disrupted, in which they will attack nearby creatures until damaged, in which they will revert to a normal unliving state, or all creatures in sight are dead.
-Rapidly replaces the infected's blood supply with bleach. Causes near-instant death and eventually dissolves the infected corpse entirely.
-Turns the infected into an adult corgi. 
-Causes the infected to uncontrollably shit out armed grenades. Similar to Bomberman but harder to notice.
-Causes the infected to turn into a cockatrice. Causes mass panic as the usually less-armored crewmen are attacked and turned into stone.
-Causes the infected to strip naked and rapidly and loudly shout about picnic baskets before turning into a Space Bear.
-Causes the infected to turn into a Gremlin, retaining their humanity but stripping them of their ability to communicate. The infected also divide into non-controlled gremlins on exposure to water. Infected cannot attack gremlins. Eventually causes large damage to electronics and shuttle calls.
-Causes the infected to melt down and turn into a Blob. Only a minute, percent chance of being an Overmind-controlled blob, but otherwise causes massive panic.
-Causes the infected to shit out live facehuggers. Causes inevitable death squads.
-Causes the infected to quickly turn into a Hivelord. Grants a large yet temporary supply of extremely potent medicine at the cost of most of the crew. Can be beneficial if extremely contained.

**Comment by UndeadOrb** [comment]
Another complaint I just forgot to author in is to make curing diseases a bit more complicated than just "feed the monkeyman radium and shove them in a scanner." In it's current state since nobody ever plays Viro it makes sense, but unless you entirely have Medbay on your side ala Revs/Cult a disease is extremely easy to cure and stop entirely. Forcing a bit of use of the Viro lab to cure the disease as quickly as they do now would be a pretty good medium, as well as complicating the "just stuff em with radium" strategy a bit more than it is currently means a tator viro could actually do a number before the floorpills are distributed.
Also add more antibody letters, once someone has 5 antibodies they're almost entirely immune to diseases- either making 1 letter diseases a bit more common, or requiring something somewhat more complex than a 1 letter match- or even making diseases have a hidden stat detailing their difficulty to cure, perhaps requiring two matching antibody letters- would make stuff a bit harder to shutdown.

**Comment by SonixApache** [comment]
bring back magnetism

**Comment by Killette2** [comment]
I miss magnetism and was thinking about it the other day. I loved seeing objects like floor tiles, lockers, pens, and toolboxes floating towards people. We need it back.

**Comment by ghost** [comment]
virology is badcode and needs a complete rewrite. It's currently full of bugs and adding on spaghetti fixes will just make it more and more of a mess.

**Comment by DeityLink** [comment]
Well magnitis is back now, are there any interesting symptoms in this list you'd like to see?

**Comment by SonixApache** [comment]
the retrovirus (scrambles your DNA constantly) and dna spreading virus (spreads your DNA to nearby others) maybe

**Comment by DeityLink** [comment]
the retrovirus already exists as **Reverse Pattern Syndrome** (Danger:5), also causes heavy cloning damage.

**Comment by ShiftyRail** [comment]
i am not sure if this is still applicable. if it is, feel free to re-open.
