### ISSUE TITLE
The Safe in the vault is gunked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#20978]
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
a3f253d2185b2677bab9c86637f0c2215ad5fe37

# Description

Last round the code to the safe was 46, 25. Yet you can only move in fives, which means opening it was impossible

# Steps to Reproduce

>Go to safe
>cry

# What you Expected

Me to get loot

# What Actually Happened

No loot

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
No dummy, the code is 46*5, 25*5

**Comment by Kurfursten** [comment]
@DamianX not a bug
