### ISSUE TITLE
Martians are incompatible with cult 3

### ISSUE THREAD

**Issue by Chazach** [d3athrow/vgstation13#20980]
#### Description of issue
Cant inscribe or use runes, cant shade on death

**Comment by Chazach** [comment]
Same with xenos

**Comment by Kevak** [comment]
Can confirm.

**Comment by DeityLink** [comment]
Not a bug. So long as xenos and martians don't have proper blood vessels, they'll have to use someone else's blood.

**Comment by ShiftyRail** [comment]
Martian biology works in mysterious ways
