### ISSUE TITLE
Infinite Exosuit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21008]
(WEB REPORT BY: caboozles REMOTE: 206.221.180.138:7777)
# Revision
3e2aabda88628e177a70ec199c9521a52aa4cb6d

# Description
Somewhere after producing the 6th phazon, I realized that the machine had borked somehow and was producing things it didn't have the materials to make. It in essence was spitting out infinite parts.

# Steps to Reproduce
Maybe it was because I sync'd the R&D console after it was upgraded, but something caused it to bug out.

# What you Expected
For it to cost mats.

# What Actually Happened
FREE PARTS

**Comment by AI-Is-Rogue** [comment]
Bluespace matter bins?

**Comment by Caboozles** [comment]
Possible. They were upgraded.

**Comment by SonixApache** [comment]
Bluespace matter bins supposedly don't actually work with exofabs, so maybe not.

**Comment by ghost** [comment]
Just to say, two days ago I ran out of materials in a fully upgraded and synced exofab while producing Durands. 
The matter bins definitely do work in some way with the fabs, even if they're just a material dump. I threw like 300ish sheets of metal into each and printed barely anything and one of them came out empty as I started using an upgraded autolathe next to it a lot.

**Comment by SonixApache** [comment]
Okay so apparently bluespace matter bins *do* work on exofabs -- you could probably print "infinite" phazons because the bluespace bin network had "infinite" materials available.

**Comment by Lunstra** [comment]
Prepared to bet this was bluespace bins and a MoMMI with no sense of right or wrong that had synthed 50 sheets of phazon into his own lathe that also had bluespace bins or something similar tbh
