### ISSUE TITLE
Mute characters can use megaphones

### ISSUE THREAD

**Issue by ddolll** [d3athrow/vgstation13#21005]
#### Description of issue
Pretty much what it says on the tin: genetics muted characters can use megaphones exactly the same way as everyone else.

#### Difference between expected and actual behavior
You'd expect mute characters to get the same message as mimes
'You find yourself unable to speak at all.'
But instead they can use megaphones to avoid their disability.

#### Steps to reproduce
Turn mute on in handicaps.
Join game, find a megaphone, be able to use it and therefore talk.

#### Specific information for locating
Megaphones use issilent(user) to check if you should be able to talk, but issilent doesn't check for muteness.

Worth noting that any sort of muting effect which allows emotes will still allow you to use the megaphone to talk.
#### Length of time in which bug has been known to occur
Probably forever, I remember abusing this years ago.
Only tested and reproduced this just now though.

#### Server revision

fd7aa65ce51c014a96c70d348d0b93bfd5641dcc

**Comment by Killette2** [comment]
(almost) mute
