### ISSUE TITLE
Packed Station - Engineering camera console only shows 2 cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21001]
(WEB REPORT BY: autisticmouse REMOTE: 206.221.180.138:7777)
# Revision
4f0beada28372455bb6446bf23150441d392cee0

# Description

Using the engineering camera console only lets you see borg vision and one xenobio camera.

# Steps to Reproduce

Use the engineering camera console and cycle through cameras

# What you Expected

To have a lot more cameras viewable, surely most/all cameras on the station?

# What Actually Happened

Only xenobio and robot camers are viewable.

**Comment by jknpj** [comment]
Because It only shows mommi cameras and cameras with active alarms

**Comment by DamianX** [comment]
Should we take this opportunity to spell that out somewhere? In its description maybe?

**Comment by Kurfursten** [comment]
I think this is actually just safe to close because it already does spell it out in its description. It directly says it only displays alarms and engineering silicons
