### ISSUE TITLE
Let lings delay their stings

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#21010]
Some stings like transformation can be nichely nice, but can rapidly help the crew figure out who the changeling is. A fun tool that lings can sometimes use is the hallucination sting, which naturally has a delay before activating and can really cause confusion. If the ling could delay the effects of some of their other stings, it could call for more interesting scenarios to take place.

**Comment by ShiftyRail** [comment]
Lings don't have stings anymore
