### ISSUE TITLE
C4 should be an actual explosive, not an object deleter.

### ISSUE THREAD

**Issue by BBHazard** [d3athrow/vgstation13#21042]
#### Description of issue
C4, despite being advertised as a plastic explosive, does not actually explode.  It just deletes the object you plant it on and leaves a few decals I guess.  Either its description should be changed to reflect its actual behavior, or its behavior should be changed to reflect its description.

#### Difference between expected and actual behavior
Planted on the floor below a supermatter shard.  No explosion sound effect, and when I come back, the floor's been deleted.  And NOTHING else.
It's supposed to be an EXPLOSIVE, not a fucking Mr Clean Magic Eraser.

#### Steps to reproduce
Plant C4 on a tile, on anything other than the object you intend to destroy on that tile.

#### Server revision

05d13264e180f61d903789355ebb64d131b9777f

**Comment by Irradiation** [comment]
I mean, it's a shaped breaching charge, it's supposed to not explode elsewhere than on the target.

**Comment by BBHazard** [comment]
> 
> 
> I mean, it's a shaped breaching charge, it's supposed to not explode elsewhere than on the target. Kind of horseshit that it doesn't nuke the shard if it's planted under it, though.

Well yeah, that's why it's a one-tile explosion.  But it should destroy what's on that tile, within reason.

**Comment by Pathid** [comment]
![shard](https://user-images.githubusercontent.com/31839805/49982545-fc773d80-ff11-11e8-8e8f-01e792fa5533.PNG)

https://github.com/vgstation-coders/vgstation13/blob/92f88dd2179fc75c217c4ff56989c241526f3a82/code/game/objects/items/weapons/explosives.dm#L118-L119

https://github.com/vgstation-coders/vgstation13/blob/82d3be35527f76ff1a11e70c4f633087b0d73e89/code/modules/supermatter/supermatter.dm#L125-L130

See the "should be improved" line. Severity 3 booms don't do squat to a shard.

**Comment by ddolll** [comment]
readd syndicate bangers
