### ISSUE TITLE
Vampire glare/hypnotise don't check for blindness, also screech ignores deafness

### ISSUE THREAD

**Issue by ddolll** [d3athrow/vgstation13#21045]
#### Description of issue
This was fixed for a version of vamps which didn't exist in #19224 but was never actually changed for datums vampires.

#### Difference between expected and actual behavior
Would expect glare/hypno to respect genetic blindness (or just blindness in general really), instead you can stun people who can't see you.
Same thing goes for the screech with deafness.

#### Steps to reproduce
Start as blind&deaf character
Have vampire glare/hypnotise/screech you

#### Specific information for locating
The spells just don't check for it at all

#### Length of time in which bug has been known to occur
Probably for as long as vampires have existed, since it was around before #19224 which didn't actually fix it.

**Comment by iFlashYou** [comment]
Do blind people see the red text when something like glare happens next to them?
