### ISSUE TITLE
Fossiled Plants Can Be Genfabbed

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21043]
Honk

**Comment by AutismSpider** [comment]
not just the fossils can scan most the guns too

**Comment by Kurfursten** [comment]
That's "fine" I guess since they're at least, you know, guns.

It makes no sense that you can scan fossilized plants because they don't have predetermined contents. You find one fossilized plant, then clone it until you have every prehistoric special plant type.

**Comment by Killette2** [comment]
oy vey shut this issue report down!
