### ISSUE TITLE
Confused Lazarus Spider

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#2106]
Make a spider your own with the lazarus stuff.

It will proceed to cocoon itself(maybe not always but this occurred).

Not a big deal, I'd assume because it's friendly faction is changed from spiders to the owner?

**Comment by clusterfack** [comment]
That's weird. I don't even know how such a thing is possible under the current code for hostile mobs as list targets ignores the src to prevent things from attacking themselves for exactly this reason.
