### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#21070]
[tested]
Ignore this

**Comment by Exxion** [comment]
uh oh

**Comment by Exxion** [comment]
Oh it did work and just didn't show up

**Comment by KingofHONK** [comment]
Pompey, despairing of the defeat, fled with his advisors overseas to Mytilene and thence to Cilicia where he held a council of war;[[44]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTETempest201762-46) at the same time, Cato and supporters at Dyrrachium attempted first to hand over command to [Marcus Tullius Cicero](https://en.wikipedia.org/wiki/Cicero), who refused, deciding instead to return to Italy.[[6]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTERawson1992433-6) They then regrouped at Corcyra and went thence to Libya.[[44]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTETempest201762-46) Others, including [Marcus Junius Brutus](https://en.wikipedia.org/wiki/Marcus_Junius_Brutus) sought Caesar's pardon, travelling over marshlands to Larissa where he was then welcomed graciously by Caesar in his camp.[[45]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTETempest201762%E2%80%933-47) Pompey's council of war decided to flee to Egypt,[[46]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTETempest201763-48) which had in the previous year supplied him with military aid.[[2]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTEGoldsworthy431-2)

In the aftermath of the battle, Caesar captured Pompey's camp and burned Pompey's correspondence. He then announced that he would forgive all who asked for mercy. Pompeian naval forces in the Adriatic and Italy mostly withdrew or surrendered.[[6]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTERawson1992433-6)

Hearing of Pompey's flight to Egypt, Caesar remained in hot pursuit, first landing in Asia and reaching Alexandria on 2 October 48 BC, where he learnt of Pompey's murder and then was embroiled in a dynastic dispute between Ptolemy XIII and Cleopatra.[[47]](https://en.wikipedia.org/wiki/Battle_of_Pharsalus#cite_note-FOOTNOTERawson1992433%E2%80%934-49)

**Comment by ghost** [comment]
sneed

**Comment by KingofHONK** [comment]
kane-f@81225c8899684ceed813e4dc8e063080815d1d26
