### ISSUE TITLE
Doughnut giver helmet eats other helmets if you equip it.

### ISSUE THREAD

**Issue by DrSnips** [d3athrow/vgstation13#21076]
If you equip the doughnutgiver helmet via quick equipping it will eat any other hat you had in the helmet slot. I'm not sure this applies to any other helmets. 
Some admin feedback about the runtime logs that may be helpful:
>[19:52:28] Bathtime PM from-Bathosbathtime: One in clothing.dm line 223:bad index, one in drag_drop.dm line 16 Cannot execute null.MouseDropTo() that might be it

**Comment by Kurfursten** [comment]
@Exxion This was fixed I forgot to add the closes line in desc
