### ISSUE TITLE
Xenoarch Gun Descriptions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21073]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
0b5dd2871275e0d9792b889632c56a52f0d972ac

# Description
I don't play xenoarch enough to know if this is a bug but I thought guns had some sort of random description. Unsure if this affects other things like random pAI slots which should also be added to descriptions
# Steps to Reproduce
Find xenoarch gun
Examine
# What you Expected
A random description of some sort: All craftmanship is of the highest quality or whatever
No listing of what ammo it uses(I thought you had to randomly find out by stuffing bullets in)
# What Actually Happened
That's gun. It is a normal-sized item.
A classic revolver. Uses .357 ammo.

**Comment by Exxion** [comment]
Caused by #20762
