### ISSUE TITLE
Feature Request: Roundstart Trader Moshrums

### ISSUE THREAD

**Issue by jubisloviu1** [d3athrow/vgstation13#21082]
Honestly when was the last time a bird actually bothered to plant them?
Moshrums are pretty cool, but them being locked behind 2 layers of RNG (one being the existance of a trader and the other being the trader actually knowing how to harvest them) is kinda garbage.

**Comment by Coxswain-Navigator** [comment]
Faxing your pomfcoins as we speak.

**Comment by Kurfursten** [comment]
I've made it clear in the mushroom suit PR (and discussion before that) that I support this idea, it's just a hassle to implement because it will require making moshrums a selectable race.

**Comment by SonixApache** [comment]
fulfilled by #26548
