### ISSUE TITLE
Cant place windows on an adjacent grille if you're on a space tile.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#21087]
#### Description of issue
If the tile you're standing on isnt a valid location to create a window (space for example) you cannot put a window on a grille that has proper floor support underneath it that is next to you.

[bugfix]

#### Difference between expected and actual behavior
Window attaching itself to the grille.
Error message about floor support.

#### Steps to reproduce
Attempt to replace a broken window from space by clicking on a grille.

#### Length of time in which bug has been known to occur

since https://github.com/vgstation-coders/vgstation13/pull/20611 i'd imagine.

**Comment by SonixApache** [comment]
-> try to place glass on other tile
-> code checks tile you're currently on, rather than target tile

@MadmanMartian
