### ISSUE TITLE
Deconstructing a MoMMI with an MMI inside turns it invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21093]
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
9903eb8011c4a8cd2e5024778ed88914d3214f44

# Description

What it says on the tin, the only way to see it is for the MMI to speak

# Steps to Reproduce

build a mommi and deconstruct it

# What you Expected

for the mmi to pop out

# What Actually Happened

it disappeared

**Comment by Exxion** [comment]
qdel nonsense maybe?
