### ISSUE TITLE
Abandoned Shuttle Doors stuck in place because of web

### ISSUE THREAD

**Issue by small-boss** [d3athrow/vgstation13#21091]
#### Description of issue
Every door in the abandoned shuttle that has web stuck under it will be stuck in position the moment it gets opened, making the door uncloseable without having a admin replace it. Trying to close it only plays the door closing sound effect.
This bug is pretty old, and with the recent change to the abandoned shuttle in #20533   this makes both interior entrance doors uncloseable once opened.

**Comment by Exxion** [comment]
The bug is super ancient but IIRC you *can* hack them closed

**Comment by small-boss** [comment]
I tried crowbarring it with it's power off but same result
the web under the doors should be removed and the doors should be closed (and bolted probably) so that spiders don't put web down again

**Comment by Exxion** [comment]
I know I've gotten them closed before, but I don't remember how
But doors have been fucked with since then, so it's possible it's even more broken than it used to be

**Comment by Dacendeth** [comment]
I've also encountered this and no amount of hacking could get them closed, didn't try anything else like maybe getting a silicon to close them or anything though.

**Comment by MadmanMartian** [comment]
You have to hit them with an ID with their sort of access.

I'll look into fixing this now. This also happens to doors crowbarred during a temporary blackout.
