### ISSUE TITLE
Blind characters respect lighting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21127]
(WEB REPORT BY: ddolll REMOTE: 206.221.180.138:7777)
# Revision
8a0a8e6d75623512e0995c46b6391ff19c0a4420

# Description
When blind, characters can see how dark the tile they are on is and can therefore tell when the lighting changes, and also suffer from having a dark view-hole when in a dark area.
# Steps to Reproduce
Be blind.
Move to a dark area.
Observe the change in the brightness of your hole of vision.
# What you Expected
Blind characters to ignore ambient light levels the same way characters with mesons do.
# What Actually Happened
I could tell how bright the tile I was on was and needed lights to be able to see easily in dark areas like maintence despite being blind.
Also actually wearing mesons lit up my tile by making it ignore ambient light levels like you'd predict it would.

**Comment by beesil** [comment]
its a feature you dumb cunt

**Comment by ddolll** [comment]
It's not though you fag it unironically shatters my immersions

**Comment by Zth--** [comment]
Feature
