### ISSUE TITLE
You can crawl while under the effect of neurotoxin

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#21126]
Exactly what it says on the title. Thanks crawling

**Comment by Pathid** [comment]
Since #20994
Looks like going forward from here requires deciding on a case by case basis which knockdown effects need a stun added to them.

**Comment by Intigracy** [comment]
Should add a FAKEDEATH check to crawling

**Comment by Exxion** [comment]
Oh no, my cult conversion strat
