### ISSUE TITLE
X-Ray Interferes With NVGs/Mesons

### ISSUE THREAD

**Issue by Rhimrifer** [d3athrow/vgstation13#21125]
#### Description of issue
When you have genetics X-Ray vision, night vision goggles do nothing but make everything a little more green, mesons have no effect.

#### Server revision
8a0a8e6d75623512e0995c46b6391ff19c0a4420

**Comment by bathosbathtime** [comment]
Specifically, mesons + xray and night vision + xray no longer grant total vision.  You can't see in the dark with them combined anymore.

**Comment by tayachiya** [comment]
Pretty sure it happens with any kind of glasses
I've had issues with vamp vision + sec glasses before
