### ISSUE TITLE
can't whisper in crit or say *deathgasp in crit to succumb

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21137]
(WEB REPORT BY: whoru REMOTE: 206.221.180.138:7777)
I had clone damage at the time if it helps

**Comment by ShiftyRail** [comment]
I blame the PR that allowed most mobs to whisper
I won't be able to push for a fix until tomorrow afternoon

**Comment by MadmanMartian** [comment]
Doesn't inaprov prevent you from deathgasping?

We'd need to know more about their status

**Comment by Intigracy** [comment]
Inaprov prevents you from taking the oxy damage you take just from being in crit

**Comment by ShiftyRail** [comment]
I found out why it happens, I have a fix, but there are some runtimes and I won't be able to actually do it properly until at least the 2nd of January.
Sorry 'bout that, will push the fix when it works as soon as I can.
