### ISSUE TITLE
Spiders web open bolted doors

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21130]
Gee, I wonder how they keep escaping the salvage shuttle

**Comment by MadmanMartian** [comment]
Have already raged about this, turns out they have some MORE snowflake code in the nurse's life()

**Comment by Kurfursten** [comment]
Contextually I'm assuming #21128 is anticipated to fix this?

**Comment by MadmanMartian** [comment]
Yes, as I'm going to be moving webbing up stuff into CanAttack and such, so wanted a system for further reducing object weighting so they're not always webbing up stuff rather than biting on people walking up to them and patting them on the head.
