### ISSUE TITLE
Cult altar is borked beyond measure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21138]
(WEB REPORT BY: caboozles REMOTE: 206.221.180.138:7777)
# Revision
82f05ba7c72c4337598d86aa6d0b9e7779f7b38f

# Description
As the sacrifice, I got placed on the altar to get summoned, and due to some shenanigans I was able to escape it. I was then spaced by my would-be captors, but due to some sort of space bullshit I was eternally stunned despite not actually being stunned by anything. For nearly 2 minutes I was stunned until they inevitably found me and brought me back.

# Steps to Reproduce
Have people put you on altar then presumably space you.

# What you Expected
To be able to move once free

# What Actually Happened
Not able to move once free.

**Comment by DeityLink** [comment]
Need better steps to reproduce. I'm pretty sure that they could have gotten up by just using the "rest" verb.
