### ISSUE TITLE
Cult is Borked 2: Electric Boogaloo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21139]
(WEB REPORT BY: caboozles REMOTE: 206.221.180.138:7777)
# Revision
82f05ba7c72c4337598d86aa6d0b9e7779f7b38f

# Description
Despite 0 cultists every even laying eyes on the last stone, and every functional cultist in the round either being dead or scattered to the winds, upon the death of the last bloodstone, Narise was summoned. Except he wasn't. He didn't appear. But the blue APCs and hordes of monsters sure did.

# Steps to Reproduce
Who knows. Just kill the bloodstones and roll the dice.

# What you Expected
Narsie not to randomly get summoned

# What Actually Happened
Narsie randomly got summoned.

**Comment by DeityLink** [comment]
Fixed by #21332
@MadmanMartian
