### ISSUE TITLE
Weeb Midround Execution Doesn't Work

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21151]
Doesn't seem to execute at all even with a valid applicant. Got an adminwarn for polling 2 players and 1 player selected but the nothing happened.

Also won't poll observers, only dead players (may be intended?)

**Comment by Arthurdentist** [comment]
its worked both times I've forced it; was this a forced attempt at it or was it picked by dynamic but failed to materialise?

Both times I tried it, there were a lot of dead people.

**Comment by Kurfursten** [comment]
It was forced. Very mysterious, we'll need to investigate more.

**Comment by SonixApache** [comment]
🤔 

give me the amount of dead players, amount of ghosts and map next time you notice it please

**Comment by Kurfursten** [comment]
Couldn't reproduce in a later round, maybe it was just something weird about that one game

I'll reopen this if it happens again
