### ISSUE TITLE
snowmap holomaps are green with envy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21157]
(WEB REPORT BY: kharkov72 REMOTE: 206.221.180.138:7777)
# Revision
3ec6d4389835ec03acc98b6a14dc0168b7722560

On snowmap at least, all the holomaps on station have a green overlay on the wall they're on which I'm pretty sure ain't right

**Comment by DeityLink** [comment]
wish I had a screenshot but I'll investigate later

**Comment by DeityLink** [comment]
Fixed by #27213
