### ISSUE TITLE
Airlock Control: Topic Overlap With Bolts And Open/Close Door

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21173]
I've run into this a lot and keep forgetting to report it

Basically when you try to bolt open a door the interface forces it closed instead

Affects aghosts probably AIs too

**Comment by ghost** [comment]
This seems to be only an issue with adminghosts, the window doesn't seem to refresh properly for them. For the AI, it refreshes instantly. Maybe a ghosthands issue ?
