### ISSUE TITLE
Grinch Improvements

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21174]
Some things that could be improved
* Some form of health regen. I know he's a miniantag but 75 health and no regeneration means he gets worn out easily.
* Disable sink/water duping. It's not really OP since it lowers your max health to a pitiful 5 for a handful of AI gremlins but it's MUH IMMERSIONS
* Actual UI and bag slot instead of the hacky solutions we have now which don't work particularly well (honestly, maybe just turn it into a type of complex carbon like martians/gondolas)
* Really, just, make it not a gremlin subtype. You can't even examine the damn thing and it has so many missing interactions.
* Resistance against high air pressure: overpressurizing distro significantly hampers the Grinch as he will quickly kill himself in the pipes. Leaving a heat/cold vulnerability seems fine just as a strategy for flushing him out, but overpressurizing distro isn't at all dangerous and commonplace just as a normal practice.

**Comment by MadmanMartian** [comment]
>disable sink/water duping

Something's up there, as grinch duping should already be disabled

**Comment by Killette2** [comment]
I'd like cold resist due to his home being an icy cave, but needing oxygen still.

**Comment by Intigracy** [comment]
Is there any actual reason for it to not be a human/monkey subtype instead of a simple_animal?

**Comment by Kurfursten** [comment]
laziness with gremlin acts
