### ISSUE TITLE
Gibtonite is fucking garbage

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#21193]
Last round I got lucky with gibtonite and stopped it with 0 reactions left in the chain, the most powerful and lucky roll (gibtonite is just playing chicken with RNG).
I blew it outside of comms thinking it would do serious damage, but it barely did more than a welder bomb. I risked my life for this shit? The explosion is big on the roid, why doesn't it scale decently on the station. Gibtonite is gaytonite.

**Comment by Killette2** [comment]
Yes it's not a bug, but it's awful that risking your life playing chicken with gibtonite provides a similar explosion to a high powered potas/water or slightly more powerful welderbomb.

**Comment by ghost** [comment]
More feature request I assume

Honestly, we should keep gibonite and add mining charges for big booms. Maybe make it so you need to actually insert defused gibotine in it to increase yield ? And can only be blown on depressurized asteroid layer unless you emag it

**Comment by ghost** [comment]
Also, to answer your question more directly, gibonite explosion scales with pressure to prevent griffing

**Comment by Killette2** [comment]
So I've been using it wrong is the gist of what you're saying? I'm not sure how it prevents griefing since you can grief with anything else, but I will play around with it and close this if the results are satisfying.

**Comment by Exxion** [comment]
No, it doesn't appear to scale by pressure
It has exactly three possible explosion sizes, which depend only on how well it was mined: (-1, 1, 3), (1, 2, 5), and (2, 4, 9)
A fuel tank is (usually) (1, 2, 4), for comparison
