### ISSUE TITLE
Stop slimes from getting cucked

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#21195]
I'm tired of trying to split a dark blue slime into more and then getting 3 cerueleans and 1 light blue. There should be a minimum of one similar offspring to the parent. This is also an annoying issue when you're breeding purple slimes, and sometimes greys if the RNG shits on you enough roundstart. Tired of all these slimes having babies of every color but their own.

**Comment by DrSnips** [comment]
I was the one who most recently touched their code. Currently they have a 100% chance for AT LEAST 1 new color and then after that it's an equal chance to get new or same color except in special cases like end tier colors.
You just have shit luck by the sound of things. BUT if I had to make a suggestion to deal with the issue you could either:
A)Increase the total number of resulting slimes to 5 so it doesn't affect any of the old RNG(1 new, 3 random).
B)Keep it at 4 but make it so you get at least 1 same colored, 1 new, and 2 random.

**Comment by Killette2** [comment]
A would be a buff, but I'd take B just to not deal with it if that's the compromise.

**Comment by strawberrytan** [comment]
I like the idea of getting a baby of the type you've split as a guaranteed result, half the babies being random isn't really that bad but i haven't played much slime ranching

**Comment by Killette2** [comment]
I'm still crying. This was my only purple and I needed another purple or blue.
![image](https://user-images.githubusercontent.com/5169310/51574380-83a5c280-1e7b-11e9-850c-369220d6ac98.png)

**Comment by PaulRitter** [comment]
this issue is resolved i believe

**Comment by Killette2** [comment]
This one is resolved. I have another issue with slimes but that will be for another post.
