### ISSUE TITLE
Scrying orb silicon law check.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21200]
(WEB REPORT BY: tobiaskunst REMOTE: 206.221.180.138:7777)
# Revision
4f2a9f0eae24eaf67c064ddeb8efa088f956073b

# Description
When alive and holding a scrying orb it is not possible to view the laws of AIs and cyborg.

# Steps to Reproduce
1.Be alive
2.Use orb
3.Examine AI/Cyborg

# What you Expected
Examining shows laws

# What Actually Happened
Examining shows no laws

**Comment by Exxion** [comment]
https://github.com/vgstation-coders/vgstation13/blob/4f2a9f0eae24eaf67c064ddeb8efa088f956073b/code/modules/mob/living/silicon/examine.dm#L5

**Comment by SonixApache** [comment]
@Exxion are **you** reading that line wrong, or am I?

\*edit*
I read the OP wrong 😄

**Comment by Exxion** [comment]
Probably neither
Read the *next* line though

**Comment by Intigracy** [comment]
https://github.com/jknpj/qwilfish-on-head-retard/commit/8a3f792c22f94a6d0f5baa2df2d4df6724d28a1b#diff-b2ee3b29cb5d3d826db026a744e1a70e

**Comment by jknpj** [comment]
It's a feature.
