### ISSUE TITLE
Weeaboo Katana

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21218]
(WEB REPORT BY: jalis REMOTE: 206.221.180.138:7777)
# Revision
814ef849a66e22865acbe4f63811d3c43479447f

# Description
Description of the weeaboo katana is not intuitive. Description should be changed to say "ALT CLICK on the Sword" and not Alt Click to teleport attack. Maybe change the function for teleporting to the Z key bind for ease of use?
# Steps to Reproduce
Try to alt click on a mob
# What you Expected
To do a teleport attack
# What Actually Happened
Nothing because item description is worded poorly.

**Comment by SonixApache** [comment]
it does actually say "alt-click on it" when you examine it
use (attack self?) might be a better button for it
