### ISSUE TITLE
shelter disrobing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21224]
(WEB REPORT BY: davidsamathy REMOTE: 206.221.180.138:7777)
# Revision
4844c533ed116308b5a4b00525eaa5c77277ad61

# Description
when clicking on inflatable shelter does not remove contaminated hat
# Steps to Reproduce
put on hat enter plasma gas until contaminated enter shelter and click on it to remove plasma clothes
# What you Expected
the contaminated hat to be removed
# What Actually Happened
it was not removed

**Comment by ghost** [comment]
I tested this and my hat wasn't contaminated. In addition, `/mob/living/carbon/human/proc/suit_contamination()` is only called on uniforms, gloves, and shoes.
Are you absolutely sure your hat was infected? If so, which one was it?

EDIT: Nevermind I'm fucking stupid
