### ISSUE TITLE
The create traitors admin button can make borers antags (again, apparently)

### ISSUE THREAD

**Issue by samGeorgeson** [d3athrow/vgstation13#21227]
#### Description of issue
Borers (and presumably PAIs) can still be made traitors by admins via the "Create Traitors" button.

#### Difference between expected and actual behavior
Expected:
Borers not to be a member of the syndicate, given they were born today

Actual:
Mission specifications decrypted, welcome to the syndicate.

#### Steps to reproduce
Have an existing borer (with traitor preference turn on, presumably), click that gimmie syndies button

#### Length of time in which bug has been known to occur

Had an autotraitored borer in me today, past issues show it happened before dynamic mode became a thing and was fixed (it isn't)

**Comment by Reviire** [comment]
New recruits

**Comment by Kitfox88** [comment]
I got a random tatoring last week as PAI so that's still possible as well. Sadly the CMO who was my target did not oblige my PDA message requesting him to kill himself so MISSION FAILED

**Comment by Killette2** [comment]
If you were creative you could technically PDA others misinformation to make them kill the CMO for you

**Comment by Kitfox88** [comment]
We only had about 6 minutes till centcomm since the shuttle'd been called and I spent a few of those chatting with an admin asking if this was a bug or not first. If there'd been more time I probably would have given it a college try, yeah.

**Comment by MadmanMartian** [comment]
Apparently borers being traitors is a feature, according to the trim candidates of the midround ruleset
