### ISSUE TITLE
Rockernaut gloves but when preventing drilling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21221]
(WEB REPORT BY: sergewind REMOTE: 206.221.180.138:7777)
# Revision
4844c533ed116308b5a4b00525eaa5c77277ad61

# Description
see title

# Steps to Reproduce
>get rockernaut gloves
>get d-drill
>punch a rock with fist
>walk into roid rock or touch rock with drill
>repeat last action done without actually doing anything

# What you Expected
drilling
OR a clear "you can't do that, you got big boy gloves on"

# What Actually Happened
everything bugs out, the end

**Comment by MadmanMartian** [comment]
FIGURED IT OUT

It's not the fists of the rockernaut attempting to mine, it's the fact that they return FALSE on the dexterity check.

I've been able to reproduce this bug with both the fists, and boxing gloves.
