### ISSUE TITLE
Placing Windows Sometimes Wants to Build Fulltile

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21223]
@MadmanMartian 

A side effect of going OOP
The code looks for a window recipe on the glass sheets but this can be fulltile or directional window depending on how the runtime decides to order the recipe list. It is inconsistent.

**Comment by MadmanMartian** [comment]
but, the list should be in a static order

**Comment by Kurfursten** [comment]
Doesn't explain why it differs between sheet types and rounds by fey mood

**Comment by Dacendeth** [comment]
another bug i noticed was placing a window diagonally always builds a full tile where previously it told you were not close enough. There is also the oddity that if you click on a grille with glass that you're next to, take a step to the side the first action will cancel but without any further input the game will start building a full tile on the window, even if you're not close enough
![image](https://user-images.githubusercontent.com/26881007/50725482-24e6f780-10cc-11e9-8f44-c9692ffde77e.png)

**Comment by Kurfursten** [comment]
90% sure this was fixed
