### ISSUE TITLE
[Cult] Summon Forge not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21230]
(WEB REPORT BY: tobiaskunst REMOTE: 206.221.180.138:7777)
# Revision
4844c533ed116308b5a4b00525eaa5c77277ad61

# Description
Cultists are unable to summon a forge with the "Raise structure" rune when reaching the second phase of the cult (ACT II: The Sacrifice). The bug remains throughout the other phases.

Being unable to summon a forge results in a round breaking bug, since the cultists need a cult blade which can only be obtained by a forge to progess into the next phase.
 

# Steps to Reproduce
Reach the second phase: (ACT II: The Sacrifice)

Trace a "Raise Structure" rune

Use "Raise Structure" rune

# What you Expected
Get a selection between summoning a altar,spire or forge.

# What Actually Happened
Get a seletion between summoning a altar or a spire.

**Comment by iFlashYou** [comment]
@ShiftyRail
