### ISSUE TITLE
Holding an auto ore loader permanently puts the toggle icon on your screen even after it's gone

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21231]
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
4844c533ed116308b5a4b00525eaa5c77277ad61
what title says, but you can also toggle the setting of the ore loader even though it's not in your possession and probably in the hands of some miner on a totally different z-level

**Comment by jknpj** [comment]
Because the item was made for silicons, then added to humans without testing
