### ISSUE TITLE
Becoming the grinch: nullspace no-control edition

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#21257]
#### Description of issue
was a autotraitored posibrain
got put in a borg shell
died
ghosted
got polled for grinch, poll immediately closed when i applied
didn't actually get pulled as grinch
found an AI grinch feeling up walls
grinch got robusted
tried to re-enter corpse, ended up in dead grinch
went back to where I died to look at my old body but it was gone
kurfursten did a lookup and found my borg body in nullspace
[bugfix]

#### Server revision
69b5c5b6808562168fbd1494efcc5bd70865f458

**Comment by Kurfursten** [comment]
no, the posibrain was in nullspace

and midround grinches having no mind is a dupe of #21142
