### ISSUE TITLE
Grinch Suggestions [MY OPINION] 

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#21254]
I think Grinch SUCKS [as its currently implemented]
For one, I don't think it it should be roundstart. It's way, way too gunky. The ability to instantly spare rush nearly as fast as a Captain who spawned in the room is insane. Being completely unknown to anyone and then being able to run back and forth in the armory and take out everything and just dump it somewhere obscure is also very gay, at roundstart.
Because of this non-roundstartness, I think it should pull from ghosts instead of whoever ready'd up. Maybe the grinch /event/ rolls at roundstart, but the thing itself isn't spawned until 10/15/20/30/40 minutes in or whatever. Make it semi random or something, depending on how much dynamic % it takes up, the less it takes up the later it spawns or something. I dunno. Ideas.
Also

just, give it a time limit. After that time limit, just teleport it to it's grinch cave where it counts up everything it stole or something. maybe drop its bag in a random place in maintenance so the stuff it takes doesn't get baleted. I'm spitballing ideas here. The mini antag can be funny, being a player controlled gremlim and being annoying is a good miniantag, but as it stands it can easily be more threatening than a major antag and often just ends up pooping all over rounds, especially the lowpop ones. 
I want to see it come back next year, just better.

**Comment by Killette2** [comment]
I agree, grinches have too much success too many of the times.

**Comment by ShiftyRail** [comment]
Thanks for the suggestions.
Grinch retires tommorow, but I'll try to take your suggestions into account.
