### ISSUE TITLE
AIs can right-click, even through static

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#21258]
#### Description of issue
oh god it's loose [bugfix]
![rightclick](https://user-images.githubusercontent.com/8468269/50826180-397cf700-133b-11e9-88b5-bd800a431d23.png)

#### Difference between expected and actual behavior
shouldn't be able to rightclick anywhere but the AI core vision box

#### Steps to reproduce
right click anywhere as AI

#### Length of time in which bug has been known to occur
month or two, i keep forgetting to report it

#### Server revision
69b5c5b6808562168fbd1494efcc5bd70865f458

**Comment by ShiftyRail** [comment]
Say thanks to Byond

**Comment by ddolll** [comment]
I thought this was an open issue but it's only #10507

I wanna say that this is as old as static but I'm not 100% sure

**Comment by iFlashYou** [comment]
Can AI's still take photos too see stuff they should not?

**Comment by ShiftyRail** [comment]
I think they still can use photos to take pictures of runes.

**Comment by Exxion** [comment]
I'm pretty sure this is old as shit
Also it's either a one-line fix or completely unfixable depending on how a particular BYOND feature works
I think it's the former but I can't remember for sure

**Comment by ShiftyRail** [comment]
Dupe of #20772
