### ISSUE TITLE
Hornets can get distracted by borgs

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#21268]
I decided to do a cool idea to release 100 hornets on the emergency shuttle, and when I executed the plan a good amount of them went for a cyborg. They do no damage to borgs, even though they are supposed to be the bees but can pierce through hardsuits. Borgs aren't even carbons so why would hornets think to sting them, especially if they can't?

**Comment by Irradiation** [comment]
>They do no damage to borgs

My experience of seeing Borgs get rapidly lynched by random event hornets disagrees.

**Comment by jknpj** [comment]
Borgs DO take damage from bees and hornets, deity said it's a feature.

**Comment by Killette2** [comment]
Maybe I just didn't notice the damage, closed issue will use more hornets next time.
