### ISSUE TITLE
December is over but the grinch is still in whoville

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21265]
(WEB REPORT BY: boosterrooster REMOTE: 206.221.180.138:7777)
# Revision
c17f20e557cc58456a7bc23ab552b5ce3b28d1dd

# Description
I think it's time for the grinch to go. December is over and it happens once if not twice ever round. Its time to tone it down a bit or off.

**Comment by Kurfursten** [comment]
It ends tomorrow, did we really need an issue for this?

**Comment by Exxion** [comment]
Not really
