### ISSUE TITLE
Secbelt cannot hold stun revolvers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21278]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
0e50b00c6c00b3f683b4b76885e5073d2b636989

# Description
just seems like an oversight since they are meant to be the "upgrade" to tasers

**Comment by DrSnips** [comment]
Easy fix.

**Comment by SonixApache** [comment]
[seccreep]
