### ISSUE TITLE
putting telecrystals from Mining satchels into oreboxes deletes them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21271]
(WEB REPORT BY: manfreed REMOTE: 206.221.180.138:7777)
# Revision
5637481bd5911efa33d1ef13990491ab0750877c

# Description
What it says on the tin.
putting telecrystals (purple triangle things) from Mining satchels into oreboxes deletes them.

# Steps to Reproduce
Find and mine telecrystals
Put them in your satchel like anything else you mine
empty satchel into ore box
TC are gone

# What you Expected
to keep my precious loot

# What Actually Happened
Admin PM: i got no clue about what happened to em

**Comment by ghost** [comment]
can't be bothered to make my own issue but maybe he'll get notifs for this:
mythril ore can be put in the ore smelter but not actually smelted because it doesn't have an option for it
how to fix: rewrite the entire ore smelter because its fucking garbage shit

**Comment by MadmanMartian** [comment]
I saw during observation yesterday, will work on it during the weekend.
