### ISSUE TITLE
Feature Request: Moving Chat Bubbles 

### ISSUE THREAD

**Issue by KingofHONK** [d3athrow/vgstation13#21279]
It'd be neat if we had a chat bubble that would move while people are typing stuff, so that we don't miss the EXTREMELY IMPORTANT messages that fellow spacemen say. A few others have expressed a similar sentiment, so i'm slapping it here and seeing where it goes.<featurerequest>

**Comment by strawberrytan** [comment]
it would help cut down on people sanicing away at mach 30 just before you finish typing, and end the awkward moments where two people don't know if the other intends to say something or not

**Comment by SonixApache** [comment]
had a discussion about this before, people agreed it should be opt-in (typebaiting and other gay things considered)

**Comment by Kurfursten** [comment]
This is a complicated issue, because while it benefits players in that way, it also hurts players due to typebaiting. Right now you don't know if someone is typing a reply or hovering a taser.

**Comment by LumpyGiraffes** [comment]
> This is a complicated issue, because while it benefits players in that way, it also hurts players due to typebaiting. Right now you don't know if someone is typing a reply or hovering a taser.

I don't think it would make typebaiting much worse, while it would give you confirmation that someone is typing, the benefits to communication outweigh the possible issues it would cause.

**Comment by ShiftyRail** [comment]
Idea : you need to have bubbles enabled for you to see other people's bubbles.

**Comment by kilozombie** [comment]
Typebaiting would be even more powerful for people without hotkey mode
We can just type into the bottom bar and always be in type mode while also completely prepared to fuck people up

**Comment by ghost** [comment]
typebaiting is pretty gay already
if it was a toggle i wouldn't mind, i'd just turn it off. personally i don't want them because i think it's just a polite thing to stay around until you're sure someone is done talking, if people don't care they'll just run away even if they see you typing

**Comment by Exxion** [comment]
For the record this would only even be possible to implement for people in hotkey mode
EDIT: Well, you could do something like check every tick if the command bar's contents are different from the last tick, but it would be pretty unresponsive
