### ISSUE TITLE
Xenos Not Counted As Antags

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21294]
* Aren't listed in red bold on who advanced
* They don't appear on check antags
* They are eligible to become antag rolled #20941 
* They aren't factored into dynamic antag injection roll chances (e.g.: station can be 90% xenos and still have a chance to spawn a wiz)

**Comment by Kitfox88** [comment]
>They aren't factored into dynamic antag injection roll chances (e.g.: station can be 90% xenos and still have a chance to spawn a wiz)

I dunno about you but that situation sounds like a feature and not a bug.

**Comment by jknpj** [comment]
We also don't count other player-controlled mob as antagonist

**Comment by Kurfursten** [comment]
That's true but in general it's less of a problem with other mobs like
>Monkeys, borers, slimes
or
>Bussed mobs (usually not too many, and a well behaved badmin is probably only bussing after threat runs out anyway)

With Xenos in particular you can get a massive infestation and still be spawning antagonists. And unlike players bussed into Ian or Dave they're pretty much always hostile.

**Comment by robintime** [comment]
more descriptive duplicate of #9361

**Comment by Kurfursten** [comment]
This was added
