### ISSUE TITLE
Cooler broken for xenoarcheology on Astroid station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21298]
(WEB REPORT BY: crazygamer313 REMOTE: 206.221.180.138:7777)
# Revision
7b3823d3b9d8a3551d46aa720425486672690a3e

# Description
cooler in the mass spectrometer lab isnt connected
# Steps to Reproduce
1. go into room 
2.unwrench cooler
3.lever up tile 
4. no pipe there
# What you Expected
that there si a pipe 
# What Actually Happened
there is no pipe

**Comment by DrSnips** [comment]
Big brain suggestion. We remove all the cooling garbage from xenoarch mahines.
