### ISSUE TITLE
Request: Make Advanced Clownshoes Require Clumsy

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21312]
Currently they are hardcoded to only work if you have the assigned role clown. I feel that instead, it should just check for the genetic defect. This way clowns who lose their clumsiness can't use the shoes and those who earn the mighty clumsy power CAN use them.

This would be an easy change/good first issue.

**Comment by SonixApache** [comment]
same for the banana sword(s)
