### ISSUE TITLE
locks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21333]
(WEB REPORT BY: davidsamathy REMOTE: 206.221.180.138:7777)
# Revision
bb63ddce05994af52f74554b0f64aaaca5d39e84

# Description
found that right click toggle lock worked on abandoned crates in centcom cargonia
# Steps to Reproduce
while unsure of how far this goes it happened for me in the vault that holds the cargo shuttle when not docked with the station also of note one I did try normally and it offered a decacode prompt and then the right click toggle lock still worked but the crate was empty
# What you Expected
right click toggle lock might open the decacode prompt as normal or create some flavortext error telling you it didn't work
# What Actually Happened
the lock is disabled and the contents inside can be gotten by clicking the crate as normal

**Comment by nervere** [comment]
It's because these crates have no access requirements on them. They should either be added or have the togglelock proc just say access denied when you try to use it on them.
