### ISSUE TITLE
blob appears to have absolutely no attack cooldown

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21336]
(WEB REPORT BY: whoru REMOTE: 206.221.180.138:7777)
it can just autoclick and make a borg instantly go from 300 health to gibbed
it also has no expansion cooldown so it can expand-sprint in a straight line across a room in 1 second

**Comment by Killette2** [comment]
Expand sprinting is unreliable unless I've been doing it wrong. Ctrl+click works when it feels like it it seems
