### ISSUE TITLE
blob growth from portions disconnected from core

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21337]
(WEB REPORT BY: saronsen REMOTE: 206.221.180.138:7777)
# Revision
9f9dfc57b99fdb42e02edae4c7ba2f6175c7d002

# Description
blob can expand from other blobs that arent directly attached to their core anymore lul

# Steps to Reproduce
play blob, get someone to separate a portion of blob, keep growing from separated bits

# What you Expected
blob to not control from disconnected sections

# What Actually Happened
blob controls from disconnected sections

this shit's a bug and not a feature now right?

**Comment by Killette2** [comment]
I don't remember node jumping ever not being a feature

**Comment by ShiftyRail** [comment]
I think it's a feature, if a annoying one.
I think that a blob not directly connected to a node or a core shouldn't be controlled by the blob camera.

**Comment by Exxion** [comment]
I haven't tested it or anything but BYOND's incredible performance quite likely makes changing this infeasible anyway
