### ISSUE TITLE
Borged wizard still have thier spells, and can use them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21342]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
20069ad676141482f25a07a261d32251dc417301

# Description

Borged wizards can use spells that don't require robes after being borged.

**Comment by boy2mantwicethefam** [comment]
And that's a bad thing?

**Comment by ghost** [comment]
_IT'S A FEAAAATUUUUREEEEEEEEE_

**Comment by SonixApache** [comment]
considering borging is one of the only ways to 'pacify' a wizard, i'd say this is a minor issue

**Comment by Kitfox88** [comment]
they're still constrained by their asimov laws so it doesn't seem like too big a problem? i may be biased because a week or two ago there was a packed round with a borged wiz who kept using his 'spawn a fuckton of snakes' spell and it was hilarious
