### ISSUE TITLE
donutgiver doesn't support a tactical light

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21341]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
20069ad676141482f25a07a261d32251dc417301

# Description
Donutgiver may look like a generic sec helmet, but it doesn't support the tactical light like the helmets do.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Close this
