### ISSUE TITLE
Plant-B-Gone not working off of solanine

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21353]
(WEB REPORT BY: seymourbutts REMOTE: 206.221.180.138:7777)
# Revision
4492b9c4e355ca292343e337d366499b2fd4d569

# Description
Plant-B-Gone recipe not using Solanine
# Steps to Reproduce
Attempt to mix Plant B Gone
# What you Expected
4 parts water 1 part solanine = Plant B Gone
# What Actually Happened
Contents dont mix

**Comment by Kurfursten** [comment]
@MadmanMartian
