### ISSUE TITLE
Can deconstruct mech barriers on Wild West away mission

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#21357]
#### Description of issue
On the wild west away mission, there are mech wrecks strategically located to railroad players through a certain path. Problem here is that you can deconstruct them for mech parts, subverting the railroading.
#### Difference between expected and actual behavior
Expected: Being unable to deconstruct the mechs

Actual: Can deconstruct the mechs and skip the 'town hall'
#### Steps to reproduce
Approach mecha wreckage on Wild West away mission
Examine
It should say 'there are some thing you can weld off of this wreck.' and 'There are some things you can remove with wirecutters on this mech.'
Do so.
Deconstruct the mecha wreckage
Proceed onward.

#### Specific information for locating

Wild West Mission, mecha wreckage.

**Comment by Kurfursten** [comment]
I feel like this is not a bug, rewarding resourceful players.

**Comment by Durgen** [comment]
feature

**Comment by Ratvar** [comment]
There's nothing resourceful in having a toolbelt, thought

**Comment by Kurfursten** [comment]
It's resourceful in the literal meaning of the word

Well stocked with resources

**Comment by west3436** [comment]
Feature
