### ISSUE TITLE
Cyborg cannot wield its battering ram

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21352]
(WEB REPORT BY: saronsen REMOTE: 206.221.180.138:7777)
# Revision
4492b9c4e355ca292343e337d366499b2fd4d569

# Description
Cyborg cannot wield its battering ram from the security cyborg W.A.T.C.H. upgrade board.

# Steps to Reproduce
get upgrade board
try to use ram
cant use ram

# What you Expected
smash bash this is the robopolice

# What Actually Happened
you cant do that

**Comment by Kurfursten** [comment]
@jknpj

**Comment by jknpj** [comment]
But you dont need to. It just works.

**Comment by jknpj** [comment]
Ok, someone messed with either rams or doors, because it worked before.

**Comment by jknpj** [comment]
@Kurfursten 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/17928298/51490045-cdfa4700-1d88-11e9-9c36-b1261b830e87.png)

**Comment by Kurfursten** [comment]
Ah, you're right that it's from that PR, but you're wrong that that's what causes it. It's actually airlock.dm line 1213

I'll fix this later today if you won't. It could be a web edit but it's logic statements so I want to make sure it tests right.

**Comment by jknpj** [comment]
Yeah when i noticed it wasn't that i literally passed out, still, at least we found out why.
