### ISSUE TITLE
You can crawl away from an ebow shot.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21360]
(WEB REPORT BY: kavlax REMOTE: 206.221.180.138:7777)
Thanks crawling.

**Comment by boy2mantwicethefam** [comment]
Security powercreep doesn't exi-

**Comment by SonixApache** [comment]
crawling was a mistaaaaaaaaaaaaaaaaaaaaake

you can crawl from being disarmed
