### ISSUE TITLE
Abandoned Vox Shuttle Floating in Space

### ISSUE THREAD

**Issue by GeneralVeers25** [d3athrow/vgstation13#21365]
Someone (@Kurfursten) just told me that there's an abandoned Vox Trade Shuttle floating in space on Roidstation between Cargo and Virology.

Being a total dipshit, I probably left it there while trying to see if I could fit in another dock for the Traders. This will need to be removed.

[roid]

**Comment by SonixApache** [comment]
I TOLD YOU ABOUT THE SHUTTLE
I TOLD YOU BRO

**Comment by GeneralVeers25** [comment]
Kurfurst told me first :^)
