### ISSUE TITLE
Biogenerator issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21373]
(WEB REPORT BY: nuklearcellphoneg REMOTE: 206.221.180.138:7777)
# Revision
84fed950379a8c3b03ea8bf0bdc894c16776706a

# Description
Biogenerator options don't work:
10 milk
10 EZ nutrient
10 Left 4 Zed
10 Robust harvest

The x50 options also do not work.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by MadmanMartian** [comment]
Resolved: Didn't check the large beaker attached to the biogenerator

![image](https://user-images.githubusercontent.com/30557196/51571208-67188300-1e99-11e9-980d-fefafe24a993.png)
