### ISSUE TITLE
SOMEBODY BROKE BORG CONSTRUCTION

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#21425]
IT'S BROKE IM EDITING THIS BUT POSTING IT QUICKLY SO PEOPLE COME HERE:

EDIT

You can't make functioning borgs. Or at least I couldn't.

When I put the MMI in the borg, instead of using up the shell, it spawned a borg on top of it and the borg was full of problems:

It moved like it had no cell in it, you'll have to ask what else they experienced because I don't know but it's BAD and not good.
The borg was also invincible. It took no damage from anything.
I could not take out the battery, or interact with the insides in any way.
Screwdriver gave a message about radios.
Multitool and wirecutters told me to expose the windows.
Empty had did nothing.
A battery swapped out the battery but I don't know if that did anything.
Cyborg diagnoser thing told me everything was completely fine.

Oh and I also tried to put new parts in but it just make me hit them with the part so nothing happened.

**Comment by MadmanMartian** [comment]
looking into this, had the same thing happen last round

first thing that I can find is a weird runtime involving an arg called unfinished

``[21:59:13] Runtime in ,: bad arg name 'unfinished'
  proc name: New (/mob/living/silicon/robot/New)
  usr: Cyborg () (/mob/living/silicon/robot)
  usr.loc: The floor (291, 234, 1) (/turf/simulated/floor)
  src: Cyborg (/mob/living/silicon/robot)
  src.loc: the floor (291,234,1) (/turf/simulated/floor)
  call stack:
  Cyborg (/mob/living/silicon/robot): New(the floor (291,234,1) (/turf/simulated/floor), null)
  the robot endoskeleton (/obj/item/robot_parts/robot_suit): attackby(the positronic brain (ARMA-960... (/obj/item/device/mmi/posibrain), Lily Ludwig (/mob/living/carbon/human), "icon-x=21;icon-y=10;left=1;scr...")
  Lily Ludwig (/mob/living/carbon/human): ClickOn(the robot endoskeleton (/obj/item/robot_parts/robot_suit), "icon-x=21;icon-y=10;left=1;scr...")
  the robot endoskeleton (/obj/item/robot_parts/robot_suit): Click(the floor (291,234,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=21;icon-y=10;left=1;scr...")
  Crumplehat (/client): Click(the robot endoskeleton (/obj/item/robot_parts/robot_suit), the floor (291,234,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=21;icon-y=10;left=1;scr...")``

**Comment by MadmanMartian** [comment]
So, because it runtimes in robot/new, the components aren't initialized, so it all comes tumbling down

**Comment by MadmanMartian** [comment]
Think I've got it.

**Comment by SonixApache** [comment]
Fuck.
