### ISSUE TITLE
Feature Request: Syndicate Bundle Rotation

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#21435]
copied over from where I put it originally in the new bundle comments.

----------------------------------

I don't think they're picked very often, and one of the things is there's currently 16 things you're rolling for and that seems like a big game of chance.
What if instead of rolling on each and every bundle when you press the button, each round picks 4-6 of the bundles (maybe using some sort of TC worth weighting? I don't know) and then lists the ones available you can roll from on the [?] text of the bundle. This way it might prompt some people to give it a roll, if one of the fun ones is up, they can give it a shot to try it out. Might also make it so we can make some more bundles and stuff without "bloating" it.

Can't really think of anything else to add to this, but that's just the idea. Slims down the random list round-to-round and tells you which ones you get to roll from. Could lead to them being used more as people sort of have an idea of what they're getting.

**Comment by DrSnips** [comment]
I thought gamers loved the gacha system :^)
Shitpost aside I think breaking them down into offence, defence, and support (anything not in the other two) bundles would be a possible way to approach this. For example if you wanted to have a chance for go loud bundles you select offence based bundles but if you wanted to do something more stealth based you would select defence.
