### ISSUE TITLE
Can't construct officer cheapskies

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21440]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
e8047788b6173fa09f1825ae0bbbe6a948346220

# Description
Wiki says
Use a screwdriver on a Remote Signaling Device.
Combine with a cardborg helmet.
but nothing combines

**Comment by boy2mantwicethefam** [comment]
Apparently it doesn't have to be screwdrivered. During testing, it turns out it has to be ready, not that it is ready to be attached.

**Comment by boy2mantwicethefam** [comment]
So yeah uh, it's a wiki issue I suppose. Signalers have to be secured, not ready to be attached, in order to be used on assemblies.

**Comment by Repth1** [comment]
this was apparently wrong for all secbot construction instructions

now updated on the wiki: http://ss13.moe/wiki/index.php?title=Guide_to_Robotics&diff=12989&oldid=12724
