### ISSUE TITLE
You get permanently horizontalled when you use the extendo baton on harm when clumsy.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21444]
(WEB REPORT BY: meetmeindorms REMOTE: 206.221.180.138:7777)
# Revision
59f7448d83785dc6e66f5590ed7894ab74696768

# Description
I used the extendo baton with harm on while clumsy, hit myself and got horizontalled for at least 2 minutes.

# Steps to Reproduce
>be clown
>clumsy
>get extendobaton
>hit someone with it on harm
>fail

# What you Expected
To stand up.

# What Actually Happened
Horizontalled.

**Comment by boy2mantwicethefam** [comment]
Stuns for about 90 or 100 seconds, I will definitely look into this. The knockdown value is quite literally force (item's damage) multiplied by 3.
