### ISSUE TITLE
Transplanting head on a body of someone that commited suicide make other player uncloneable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21458]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
59f7448d83785dc6e66f5590ed7894ab74696768

# Description
Whats in the title. My head got transplanted on a body of player that killed themselves. Neither defib nor cloning worked - I just got this message when I was i cloner "Someone is trying to clone your corpse, but you may not be revived as you committed suicide."

# Steps to Reproduce
Suicide, transplant head, try to clone

# What you Expected
Be cloned since I wasn't the one who commited suicide

# What Actually Happened
No bueno, still ded

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Alternative title: Suicide is stored in the chest
