### ISSUE TITLE
De-traitor'd traitors still have the syndie codewords in their memory.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21455]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
59f7448d83785dc6e66f5590ed7894ab74696768

# Description

Not major, and in a sense, it's a feature, but it's kinda metagaymey.

**Comment by west3436** [comment]
Feature

**Comment by SonixApache** [comment]
that's definitely an oversight and not a feature
traitor status is a brainwashing thing that's not easy to remove

regexing one's notes for the codewords and stripping them out would not be very difficult code to implement, and should probably be done
