### ISSUE TITLE
pAI universal translator causes crash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21450]
(WEB REPORT BY: crumplehat REMOTE: 206.221.180.138:7777)
# Revision
59f7448d83785dc6e66f5590ed7894ab74696768

# Description
What it says. As a pAI, selecting the Universal Translator software causes the game to crash. And, any subsequent time I try to open the software interface, the game crashes again. This is the second game I've had this happen.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by jknpj** [comment]
pretty sure i had someone with the same issue once, seems related to a special character.

**Comment by Eneocho** [comment]
Can't reproduce, seems to be fixed by now. Note to reopen if it happens again.
