### ISSUE TITLE
Clown Name on Manifest

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21462]
Clown/mime get slot name instead of picked name on manifest. Needs datacore update. Only applies to roundstart.

So for example, they might have the slot character named John Reid and when they spawn, they are asked for a new name. If it's a latejoin, they get that new name (e.g.: Pocket), if it's a roundstart spawn, it only updates ID and PDA, not sec/med/manifest records.

**Comment by DeityLink** [comment]
Are you sure this also happens to mimes?

**Comment by Kurfursten** [comment]
No

**Comment by DeityLink** [comment]
Right, because what I believe caused the bug for clown isn't there for mimes, so it shouldn't.

**Comment by Kurfursten** [comment]
That probably explains why I had trouble finding the problem in the replace name code if it was something specific to clown setup 👌
