### ISSUE TITLE
Injectors from Safe Don't Work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21484]
(WEB REPORT BY: flubby REMOTE: 206.221.180.138:7777)
# Revision
9cc09bcd137dcec7d642c9cea2bb51cdaa8d41c2

# Description
SE injectors from safe do not function.
# Steps to Reproduce
Crack a safe. Receive injector. Inject self.
# What you Expected
Recieve power listed on injector.
# What Actually Happened
Absolutely nothing.

**Comment by SonixApache** [comment]
#21131, possibly #15297
