### ISSUE TITLE
Staying buckeld to a chair/sofa after getting teleported via bluespace plants

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21499]
(WEB REPORT BY: iflashyou REMOTE: 206.221.180.138:7777)
# Revision
dcd09113c3133b55b7e05fa04d71abe249520a79

# Description
You stay buckeled to a chair after you teleport via a bluespace plant and someone has to unbuckel you from the chair while you cant move.
# Steps to Reproduce
Sit on chair, throw bluespace plant, get teleported, stay buckeled and unable to move

**Comment by iFlashYou** [comment]
@ShiftyRail

**Comment by beesil** [comment]
can confirm, you become an immovable rock

**Comment by ShiftyRail** [comment]
Thanks for reporting it
