### ISSUE TITLE
AI crew holograms are busted

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#21492]
#### Description of issue
All you get is a naked bald human, the default `carbon/human` sprite.

#### Difference between expected and actual behavior
select vox captain as hologram, show up as vox in captain outfit
vs
select vox captain as hologram, show up as naked bald man

#### Steps to reproduce
AI -> AI commands -> Change Hologram -> Crewman

#### Server revision
dcd09113c3133b55b7e05fa04d71abe249520a79

[bugfix]

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
You may not like it, but that's what peak performance looks like.

**Comment by MadmanMartian** [comment]
Hologram draws from the locked data record, which is generated by manifest_inject() through getFlatIcon(H), H being what the person is at that time.

Has somebody messed with it lately, that the person is injected into the manifest before their features are generated?

Either that or getFlatIcon of people is busted

**Comment by DeityLink** [comment]
getFlatIcon was definitely busted considering all the workarounds I had to do to bandaid photography for so long. But I'm sure getFlatIconDeluxe can solve it now. I'll take care of it tomorrow.
