### ISSUE TITLE
Wiki Guide to Genetics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21501]
(WEB REPORT BY: flubby REMOTE: 206.221.180.138:7777)
# Revision
dcd09113c3133b55b7e05fa04d71abe249520a79

# Description
Manifestation message for asthma is incorrect. Actual message: "You feel short of breath." Wiki states:"You gasp."
# Steps to Reproduce

# What you Expected

# What Actually Happened
The mighty wizard died of asthma because he didn't know what was wrong with him.

**Comment by Repth1** [comment]
went through and gave them a check over, seems to be just asthma: http://ss13.moe/wiki/index.php?title=Guide_to_Genetics&diff=12995&oldid=12863

**Comment by Eneocho** [comment]
was fixed by repth1
