### ISSUE TITLE
Red Ribbons (as seen on stacks of paper) can be worn but have no sprites

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#21536]
#### Description of issue

The ribbon goes on your head but there's no sprite for it which is a shame and a waste.

#### Specific information for locating
`/obj/item/weapon/ribbon`

#### Server revision
9547c64b102a4f2bd208c9a7108ed2117e0d386c

[needspritework]

**Comment by jknpj** [comment]
I could swear they had one
