### ISSUE TITLE
SPS icon issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21530]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
9547c64b102a4f2bd208c9a7108ed2117e0d386c

# Description

The SPS icon sometimes becomes the inactive icon when you switch it from your hand to your pocket.

I'm not exactly sure how or when it happens, I had it opened in a separate window and realised it went dark when I used it from my hand.

**Comment by Dacendeth** [comment]
experienced this with paramedic gps as well.

**Comment by nervere** [comment]
can't reproduce
