### ISSUE TITLE
Feature Request: Round start spawn as a monkey doctor

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#21588]
A silly request, I always feel bad taking the geneticist slot to be a monkey doctor. Maybe we could make a slot for medbay to spawn as a monkey doctor. Maybe start them off with a couple pills of their ritalin as a small QoL so they can start off right away goin about their duties.

**Comment by Irradiation** [comment]
>I always feel bad taking the geneticist slot to be a monkey doctor.
You could also just spawn as a normal doctor/any other medbay job, get some Methylin from chemistry and walk into genetics (because you got access there anyway).
