### ISSUE TITLE
Mask of Change Slime form does not have ventcrawl verb or possibility

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21584]
(WEB REPORT BY: shadownil REMOTE: 206.221.180.138:7777)
# Revision
7558a114da28b47f8efc5fdce2151552e68b9c37

# Description
See title

# Steps to Reproduce
Get a mask that changes you into a slime
try to ventcrawl

# What you Expected
ventcrawl or an Alien verbs tab

# What Actually Happened
nothing, not even when I alt click and manually click the vent

**Comment by MadmanMartian** [comment]
likely made you the simple_animal slime, which doesn't have the ventcrawl stuff that a carbon slime does

**Comment by ShiftyRail** [comment]
Duplicate of #20511
