### ISSUE TITLE
Labor console megathread

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#21580]
Could just make UNLIMITED HOP WORKS by just freeing the head of personnel slot each time a new head of personnel joined

The assistant slots could be set from -1 to 0, blocking anyone from joining as an assistant

![image](https://user-images.githubusercontent.com/30557196/52366962-df0ead80-2a42-11e9-9558-d7992bd3dea4.png)

**Comment by ShiftyRail** [comment]
We finally solved the assistant question

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
>Could just make UNLIMITED HOP WORKS by just freeing the head of personnel slot each time a new head of personnel joined

What's the problem with that :^)

>The assistant slots could be set from -1 to 0, blocking anyone from joining as an assistant

I'll look into that later, for the time being you can just keep bumping if you want more

**Comment by SGuivenne** [comment]
Be careful about logging on this, I can see a few blatant shitter things to do that are probably job ban worthy but may be initially subtle. 

Perhaps mandatory minimums on default job slots and then some mandatory maximums too?  I can see 99 security being abusive.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Logging is extremely loud and alerts admins everytime someone does something with this
99 of any job requires you to wait until said job reaches cap, bump the cap by 1, wait until 1 person joins, bump the cap by 1, etc.
And it's not like the security department ever reaches the cap anyways...
