### ISSUE TITLE
Feature request: Cycle command for airlocks

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#21597]
#### Description of issue

There's no command that opens an airlock when it's closed, or closes it when it's open.
There's also no command that just opens the airlock as if someone with access bumped it.
Having these two commands would make buttons more useful and allow for better rebuilding after explosions.

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/418a659bd6fdd095cbb530fcc060904cf5ae7888/code/game/machinery/airlock_control.dm#L24

#### Server revision
9c9cc88d53352ec60b4b19f52dd8c82b601328c0

[featurerequest]

**Comment by Zth--** [comment]
I was thinking the same the other day when I was fooling around with NTSL scripts.
It would be a nice feature. I can think of some nice systems with it.

**Comment by SonixApache** [comment]
I did this in #24547
