### ISSUE TITLE
Firelocks act as a safety pocket.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#2161]
Stand in firelock. Close it. Watch and laugh from your safe haven as others die from pressure loss (or extreme temperature).

**Comment by d3athrow** [comment]
Only way to fix this is to kill air in the tile when the fire/airlock closes.

**Comment by ComicIronic** [comment]
Or to use directional firelocks.

**Comment by d3athrow** [comment]
those work awfully

**Comment by clusterfack** [comment]
Resolved with #4753
