### ISSUE TITLE
Ghosts are able to eject pilots from mechs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21614]
(WEB REPORT BY: bip REMOTE: 206.221.180.138:7777)
# Revision
c9b686a9781c2cd4e6dd627999c8cb4f0ba73c79

# Description
Ghosts can eject pilots from mechs. Tried on a Phazon with a human pilot. I don't know if the mech was DNA locked but I don't think it matters.

# Steps to Reproduce
1. Haunt pilot
2. Use 'eject' verb
3. Pilot is ejected
Zealotron was online and he was able to reproduce it.

# What you Expected
Pilot not to be ejected.

# What Actually Happened
Pilot was ejected. Heh heh whoops.

**Comment by Kitfox88** [comment]
[FEATURE NOT A BUG](https://i.imgur.com/zka4aBg.png)
