### ISSUE TITLE
Borgs not bound to AI on roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21626]
(WEB REPORT BY: mystry REMOTE: 206.221.180.138:7777)
# Revision
b256a1007fbf0d334bedff06b1af30fd264d5e44

# Description
Borgs who start as borg on roundstart do not start off bound to an AI (when there is one)
# Steps to Reproduce
Pick borg at roundstart
# What you Expected
Expected to be bound to AI
# What Actually Happened
Wasnt bound to AI

**Comment by Kurfursten** [comment]
Related to the new cyborg spawning system, I'll fix it some time this week
