### ISSUE TITLE
Ambiance sounds are weird

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21643]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
c5e14fd51e3a20ed653f3344cd27e431b21b32d7

# Description

I keep hearing a lot of ambiance sounds from various zones (notably, "may I have your attention please" as a new player, ie, in the lobby)

**Comment by ShiftyRail** [comment]
To complete, it fires WAY too frequently, as a normal player, I've got an ambiance sound every 3-5 secs.

**Comment by Kammerjunk** [comment]
also #20856
