### ISSUE TITLE
Background Music bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21645]
(WEB REPORT BY: redworthy REMOTE: 206.221.180.138:7777)
# Revision
c5e14fd51e3a20ed653f3344cd27e431b21b32d7

# Description
The background music kept changig every few seconds.

# Steps to Reproduce
It started as soon as I joined the round (Asteroid Station)

# What you Expected
For the music to not fuck up

# What Actually Happened
The opposite

**Comment by Kammerjunk** [comment]
probably related to #20856 idk when did I last play anyway
