### ISSUE TITLE
roid SME scrubbers cannot be accessed from the room's air alarm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21653]
(WEB REPORT BY: whoru REMOTE: 206.221.180.138:7777)
you HAVE to use the AAC which is quite fucking gay and unlike other stations

**Comment by Kurfursten** [comment]
Someone doesn't know how to use a multitool

**Comment by ghost** [comment]
Tap the scrubbers with your multitool and hit "reset" next to the frequency if you don't like the AAC.
