### ISSUE TITLE
Being EMPd as a borg fucks your radio forever regardless of what you do.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21654]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
412637023d3ca81836c833e3569002453d53dc4b

# Description

Being EMP'd bugs out your radio and it seems like it cant be fixed even if it has 0 damage and is power cycled

# Steps to Reproduce

be engineering borg, get EMP'd possibly by just the singulo
# What you Expected

To be able to fix my comms
# What Actually Happened

Broken forever

**Comment by SGuivenne** [comment]
disregard I'm retarded

**Comment by Goldsteel** [comment]
This is a strange problem, but you need to use the radio UI to enable it again like a headset after it gets EMPed. Toggling your radio unit doesn't actually change the settings. There is a button in the cyborg UI that lets you toggle which radio channels you want to view.

**Comment by SonixApache** [comment]
he forgot to just use the radio UI to turn everything back on, i've made the same mistake
