### ISSUE TITLE
Cyborgs can shower without consequences

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21652]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
412637023d3ca81836c833e3569002453d53dc4b

# Description
Cyborgs, despite reacting negatively to water, do not react to showering.
# Steps to Reproduce

Be cyborg, enter shower, activate shower
# What you Expected
Horrific things to happen
# What Actually Happened
Squeaky Clean

**Comment by Dacendeth** [comment]
huh what other horrible consequences do borgs have with water?

**Comment by jknpj** [comment]
they're spaceproof, why would water harm them?

**Comment by Goldsteel** [comment]
I don't see why a robot in the 26th century would be designed to not handle liquids being poured on them.

**Comment by SGuivenne** [comment]
pouring water on them from a glass stuns them briefly.
