### ISSUE TITLE
Add a justification line in the labor console?

### ISSUE THREAD

**Issue by Aryuananime** [d3athrow/vgstation13#21657]
While the labor console is a really cool update, and red is a color people like to click, I feel like it would be worth the time to discuss adding the possibility to justify why you are prioritizing the jobs you are prioritizing.

I could see this being done in two ways, or maybe combine the two.

**Per job:** 
In this case, you can justify why you recruit for any job.
So say, you would see from the Join Game screen:

Chief Engineer: No Power/Build a Bar SME
Chaplain: Cultist activity confirmed.
Clown: HONK

**Generic:**

You could also just have a specific line to justify all of the roles you're requesting to be filled.

Captain
CE
HoS

Reason: Lack of Heads on the station.

Of course, there's also the possibility of keeping it as is, if people feel it's too icky ocky, but I feel like it's not that much different from sitting on the main menu and seeing Shuttle calls or even Station wide announcements. Plus, a traitor HoP could even use this feature to help his antagging by gaslighting newcomers. (Need security to handle Revolution when you're actually a vampire, etc.)

(About HoP traitor extra idea: Bonus points if you can Emag the console so you can *lower* the number of free slots on a job, in exchange for opening more assistant slots or something perhaps.)

<Discussion>

**Comment by west3436** [comment]
Admins hate this one simple trick!
