### ISSUE TITLE
Cannot quench forged blacksmithing recipes in toilet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21656]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
412637023d3ca81836c833e3569002453d53dc4b

# Description
Please fix.

**Comment by jknpj** [comment]
i doubt you can do it in real life too.

**Comment by west3436** [comment]
Low quality feature request/5 years since this was opened so there's no interest in implementing it
