### ISSUE TITLE
Packed station - Certain APCs not charging/showing on power console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21663]
(WEB REPORT BY: autisticmouse REMOTE: 206.221.180.138:7777)
# Revision
41ddfa697b990f9d88f6eca8822e6b0b0471221f

# Description

The following APCs do not show on the power console and will not charge;

CE office,
APC above singulo
AME APC
Engine Room APC

# Steps to Reproduce

# What you Expected

Charging APCs

# What Actually Happened

They don't want to charge, even though they seem to be connected.

**Comment by MadmanMartian** [comment]
The APCs are on a different power network
