### ISSUE TITLE
Roundstart Assistant Cap is Borked

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21674]
Roidstation

7 Assistants
No security department members of any kind

**Comment by Coxswain-Navigator** [comment]
NOT A BUG

**Comment by SonixApache** [comment]
[oh god it's loose]

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
From doing #21590 I learned that this is explicitly a feature for some reason.

**Comment by SonixApache** [comment]
[feature loss]  then?

**Comment by Dacendeth** [comment]
Perhaps the cap is ignored for the setting to become an assistant if my job that I wanted isnt available?

**Comment by Kurfursten** [comment]
May also apply to latejoins

![image](https://user-images.githubusercontent.com/9782036/53219366-4a50a600-3625-11e9-98fa-676bef2cf3fa.png)
