### ISSUE TITLE
THE SERVER IS ON FIRE WHAT HAVE YOU DONE

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#21671]
#### Description of issue

THE SERVER IS STUCK IN A LOBBY LOOP YOU FOOLS YOU HAVE DESTROYED US ALL

#### Difference between expected and actual behavior

The server is supposed to not be fucked

#### Steps to reproduce

Do whatever the fuck you did

**Comment by Exxion** [comment]
We didn't do anything. It was on the server's end.
In fact nothing in the code was changed in the round before it broke.

**Comment by SonixApache** [comment]
yeah about that

**Comment by Exxion** [comment]
*shrug
Hey I was told it was a bug with Dream Daemon
