### ISSUE TITLE
Shunting is broken

### ISSUE THREAD

**Issue by FUCKYOUDYLAN** [d3athrow/vgstation13#2167]
It doesn't work. Period.

Is it raining in North America? It doesn't work.
Did you have a bad day at work today? It doesn't work.
Did Obama legalize slavery? It doesn't work.

When I say, it doesn't work PERIOD, that means that any under context no matter what, it does not work ever.

WHAT DOES NOT WORKING MEAN??!?!? I'M A RETARD!!!

It means you click the button and nothing happens. What does nothing happens mean? IT MEANS NOTHING HAPPENS.

WHY YOU NEED A REPORT FOR AN ISSUE THAT HAS BEEN IN FOR MOOOOOOOOOONTHS AND REARS ITS HEAD EVERY TIME THERE IS A MALFUNCTIONING AI ROUND I WILL NEVER KNOW BUT HEY MAYBE ALL YOU CAN DO IS READ REPORTS RIGHT?

**Comment by Duny-** [comment]
>not closed

**Comment by wild-billy** [comment]
Should be fixed, see a70d2f5
