### ISSUE TITLE
Catbeast Megathread

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21675]
* ~~Noticed it fired by itself on 50.3 threat, shouldn't happen. Then later it couldn't ready up naturally with 14 threat unless forced. Something wonky with threat code? Works fine when forced.~~ Could not reproduce on local, functioned exactly as intended. New logging PR should clear this up.
* ~~Seemed to fire rather early in the round, 10ish minutes in? Expected it to be later with weight 1. Consider requiring later in the round. (Note, didn't happen for over an hour in another round, outlier?)~~ After studying multiple rounds, I have determined this was an outlier. Some rounds they don't appear at all, working fine.
* So far both catbeasts have had very high threat generation (35 and 50) but those were exceptional circumstances (in one case no airlock restrictions). Need to continue to monitor this and scale back threat generation if it continues to be this high. It could be as easy as lowering threat per room to 0.5 since this is the main threat generator.
* One beast appeared to create ~27 threat with only 168 seconds alive and 9 rooms defiled, that should be 17 threat. Need to check threat generation, but this could also just be me being bad at watching the numbers. I need to implement a threat tracker up and down for admins. New logging PR should clear this up.

**Comment by Zth--** [comment]
It should clarify somewhere that catbeasts _can't_ attack. Preferably on spawn. I've just seen a catbeast attacking people and it should be clear that he's not a normal antagonist.

Correct me if I'm wrong (I haven't been here for a whole year so I'm not 100% sure if catbeasts can now antagonize)

**Comment by Kurfursten** [comment]
If you're catbeasted normally by an admin as punishment you are not an antagonist. If you get this role from dynamic mode you are an antagonist (granted, I can't imagine you'd have a very long lifespan). It's the difference between being selected to stir up trouble as something you volunteered for and being punished with a humiliating death for being a twit. (Note that the catbeast punishment in the admin panel does not award this role)

That being said... catbeast shouldn't be very capable of holding its own in a fight unless it has some very very fortunate looting on the scale of "someone left guns in the hallway", and even then it gets stunned once a minute or two by a random hairball vomit. I will definitely continue to monitor this, though - if our crews are regularly dying against catbeast (oof if true) then we can just give it clumsy or something.

**Comment by Kurfursten** [comment]
Addressed in #21686
