### ISSUE TITLE
Hydroponics hallway door is linked to kitchen, not hydroponics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21698]
(WEB REPORT BY: qbone REMOTE: 206.221.180.138:7777)
# Revision
92b133c95d85ff7010d5e4f8201365949e292928

# Description
The door to hydroponics on Box's is tied to Kitchen access, I believe. At least it's not tied to hydroponics.

# Steps to Reproduce
Walk into a door with only Hydroponics access, see door flashing red, feel dumb.

# What you Expected
Door to open

# What Actually Happened
BEEP BEEP

**Comment by Exxion** [comment]
Kitchen and hydroponics have the same access
IIRC it requires maint access as well as service because ???
Though I thought it was only an issue on local due to config stuff

**Comment by Aryuananime** [comment]
Yeah, I only bothered because as HoP, I gave Grug Hydroponics access only so I could make him a berry picker, and he couldn't open the hallway door.

**Comment by Kurfursten** [comment]
Dupe of 
https://github.com/vgstation-coders/vgstation13/issues/11998
https://github.com/vgstation-coders/vgstation13/issues/4654
