### ISSUE TITLE
RD Locker on Asteroid Station can't be opened with RD Access.

### ISSUE THREAD

**Issue by TurboGay** [d3athrow/vgstation13#21693]
#### Description of issue
RD Locker in the RD office can't be opened with RD access on asteroid station.

#### Difference between expected and actual behavior
Expect to be able to open my own locker with my access, find I cannot.

#### Steps to reproduce
Try to open the RD locker on asteroid as the RD.

#### Length of time in which bug has been known to occur

Unsure, just noticed it recently and I don't remember having the issue previously on the map.

#### Server revision

45d11a8a3a1445a6ed66540ce56b2a6137e7f46e

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Seems 99% impossible since it's the same locker everywhere
A more likely explanation is that it might have been EMPd somehow, and EMPs have a small chance to scramble locker access
