### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21705]
(WEB REPORT BY: coldud13 REMOTE: 206.221.180.138:7777)
# Revision
7a930038e55493822abc18ae245139949f736003

# Description
Incorrect spelling of licorice treat:

That's a liquorish sweet. It is a tiny item.

Wikipedia lists its spelt either Liquorice (British English) or licorice (American English), but is neither.
# Steps to Reproduce
Insert coin into sweet machine, get bag of sweets.
# What you Expected
Proper spelling
# What Actually Happened
Incorrect spelling

**Comment by SonixApache** [comment]
>he actually did it when I asked him to

madman, good job

**Comment by Goldsteel** [comment]
I don't remember why I put that. Trivial to fix.
