### ISSUE TITLE
Jobslots taken by people who get transformed into nuke op members remain closed.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#21711]
#### Description of issue
When someone is transformed into a nuke ops (probably wizard too?) the job they had remains taken up even though they don't even exist on the manifest. It's easy to metagame using this information with jobs that have a single slot available as a latejoiner, and potentially in game using the labor console though I did not test that.

It would be nice if the slot auto refreshed so the job became available to play and some metagay was removed.

**Comment by Kurfursten** [comment]
Confirmed this on local with wiz, disallow_job = TRUE is supposed to cover this exact thing and it isn't.
