### ISSUE TITLE
Latejoin Weeb Getting Arrivals Announcements

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21752]
Someone reported this to me and didn't make a github issue even though I told them to, they should be ashamed

**Comment by Killette2** [comment]
Merely honorably warning his prey

**Comment by ghost** [comment]
Is this about people who latejoin having their weeb roll picked immediately afterwards, so they get announced and then replaced with their weeb self, or is this a new one?

**Comment by Kurfursten** [comment]
yeah basically
