### ISSUE TITLE
invis spray bag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21767]
(WEB REPORT BY: kyunny REMOTE: 206.221.180.138:7777)
>try to put invis spray in your backpack
>spray the backpack
No way this is intended

**Comment by SysadminJeroen** [comment]
Works as intended.

**Comment by Kurfursten** [comment]
Literally intended, how else would you get an invisible backpack for a full stealth run?

**Comment by Dacendeth** [comment]
It used to only invis spray your backpack if it was full I think
