### ISSUE TITLE
Eating Grass Deletes it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21760]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
64dc6b6e757c6c5353dec9e121fcb68278cdf803

# Description
Eating Grass causes you to get a "theres nothing left of the grass" error and then it deletes itself, as if you actually ate it.  

How are we supposed to live our Irish ancestors lives otherwise

**Comment by RealestEstate** [comment]
grass has no reagents and eating any harvested plant item that has no reagents will result in message, just to clarify.

**Comment by SGuivenne** [comment]
Shouldn't grass have some kind of garbage nutritional value or at least insult you for eating it?

**Comment by ghost** [comment]
Grass not having reagents is a staple of botany genetic engineering. It is required to be able to pass 'unpolluted' potency gene onto other plants without adding to their produced chems.

This is not unique to just plants, all empty consumables such as pills or food items behave this way. Solution could be to remove the empty check text feedback and replace it with the regular eating sound even if it has no reagents.
