### ISSUE TITLE
Labor Console: Remove Job

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21787]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE 

It'd be really nice if you could -1 a job, no lower than the initial number of positions. You know, in case the clown runs in, opens a slot, and rolls a natural 20 kick -- there's no way to take that back.

**Comment by Aryuananime** [comment]
I agree with that. It's the most annoying part of the Labor Console, the lack of takebacksies.
