### ISSUE TITLE
Security EVA airlock is mapped wrong. [Box]

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#21807]
#### Description of issue
The vents in the security EVA room on box are hooked up directly to the scrubber line, so if the scrubber system doesn't have air (which it normally doesn't) it will never refill when you cycle it to the station side.

#### Difference between expected and actual behavior
Expected the airlock to work however poorly airlocks normally work and I didn't even get that.
[box]

**Comment by Probe1** [comment]
This was fixed at some point.

**Comment by Probe1** [comment]
Which upsets me because I wanted mapper valids.
