### ISSUE TITLE
Normal lazarus injectors are stronger than intended.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#21819]
#### Description of issue
Using a normal lazarus injector allows you to reskin a simple mob, I'm pretty sure previously  you had to use an advanced one to get more skins/teeth.

[bugfix]

**Comment by MadmanMartian** [comment]
issue located. living/death is initializing the butchering list, which is being inherited by living/simple_animal/death which does it itself.

**Comment by aceedex** [comment]
A long time ago, jkpnr told me "Id rather just revert the changes to the old injectors than to have the advanced ones. Its pointless tiering" 
If anyone wants to leave this as is and just delete the advanced ones off the serb I wont say anything
