### ISSUE TITLE
Laser gun sprites could be more accurate.

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#2182]
Laser weapons usually have 5 different sprites to indicate remaining ammo. 0%, 25%, 50%, 75% and 100%. Most have 10 shots, and round to the closest % sprite. This means that a gun with 9/10 shots left will appear full and a gun with 1/10 shots left will appear empty.

**Comment by PJB3005** [comment]
So, below 50%, round up and above round down?
