### ISSUE TITLE
Rigsuit modules do not work when helmet is toggled off

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#21827]
#### Description of issue

Rigsuit modules do not work when your helmet is toggled off.

#### Difference between expected and actual behavior

Expected all modules to continue working regardless of helmet status. Instead, they stop working the moment I flip down the helmet, and resume when I flip it up again.

**Comment by MadmanMartian** [comment]
That's the intention.

**Comment by ghost** [comment]
It does seem a bit weird, though. Is it supposed to imply you're controlling it with a helmet HUD, or did you just not want people refilling their tanks or moving faster without a helmet up?

**Comment by LordMyroc** [comment]
Even if it's intentional it is all the same pretty fucking strange. What's the reasoning behind it? None of the modules except for maybe the internals refill seem like they would require the helmet to be active to function. Is it for gameplay reasons? Even in that case it would still be weird considering it's tied to such a minor feature.

**Comment by ghost** [comment]
I think labeling something not a bug will not change how it is perceived by users.
