### ISSUE TITLE
Roidstation voxpost is not radproof.

### ISSUE THREAD

**Issue by Kevak** [d3athrow/vgstation13#21839]
Quite literally what it says on the tin. During radstorms, the full voxpost on roid gets irradiated, there is not a single safe spot barring the vox shuttle. This is obviously a mapping whoopsie.

**Comment by Irradiation** [comment]
Just like God intended.

**Comment by SGuivenne** [comment]
> Just like God intended.

Says Irradiation.

**Comment by SonixApache** [comment]
feature
