### ISSUE TITLE
[Feature Request] Borg cell destruction forcibly pops open your cell cover

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#21832]
[featurerequest]

#### Description of issue
When a cyborg's cell is destroyed, (which can happen from even a tickle of damage, due to the way borg component damage works), their lights shut off, but they can still move about slowly. They cannot hear, speak, see emotes, pull, point, or in any way communicate, and to anyone who has not personally suffered this very special hell, they just seem like a very slow-moving borg that isn't responding to orders.

I swear I have brought this exact same issue up in the past for these exact same reasons. You take a laser or two, you get unlucky and have your cell destroyed, and then you spend the _entire round_ wandering around aimlessly, unable to suicide due to your laws, but unable to spectate or even participate in events because you have been rendered mute, deaf, and blind.

There is a "power warning" verb accessible to borgs that seems to imply that it can notify those nearby that you are unpowered and require assistance, judging from the text when you click it when everything is fine, but as far as I was able to tell, it does _absolutely fucking nothing_ if your cell is destroyed.

My suggestion to correct this problem is simple: When a cyborg's cell is destroyed, their cover should unlock and forcibly pop open, and remain that way, if possible. 

Additionally, a bold or otherwise noticeable examine message should be present when a borg is unpowered or otherwise critically damaged, but not dead, if it isn't already.

#### Difference between expected and actual behavior
**Expected:** My cell is destroyed and I am left with the ability to at least point or drag things, to try to mime to humans that I require assistance. At the very least, I expect that humans will be able to look at me and immediately tell what has gone wrong.

**Reality:** My cell is destroyed and I am reduced to the speed of a starving diona. My lights are dim but otherwise I appear outwardly okay. I cannot see, speak, hear, pull, or point. Antags in the know leave me in this state, knowing that I have been permanently removed from the round with no means of suicide or revival, and everyone else ignores or runs from me due to the general mistrust/dislike for borgs.

#### Steps to reproduce
1. Be a borg
2. Take any kind of damage
3. Be rendered completely inert for the rest of the round

**Comment by ghost** [comment]
I think I saw you walking back and forth slowly in-game, thought the borg was controlled by AI.

**Comment by Sooose** [comment]
I saw you and knew exactly what was wrong with you, but vampires happened.

**Comment by SonixApache** [comment]
The *power warning* verb, funnily enough, only works when you have a cell but are out of power.
It's very pointless as-is.

**Comment by nuklearcellphoneg** [comment]
Back in 2013 I saw a janiborg this happened with and ignored it. I shot an ion rifle, because I wasn't sure what they did. It blew off my cargo tech's legs because they were mechanical.  The janiborg went over his body, so I assumed emagged janiborgs got an ability to clean people to death so I shot it with the ion until it died.
