### ISSUE TITLE
Prisoner space suit doesnt have built in hardsuit helmet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21840]
(WEB REPORT BY: autisticmouse REMOTE: 206.221.180.138:7777)
# Revision
8f99ee1987554bfcdbeed596f1d7168b39513b67

# Description

Prisoner space suit doesnt have built in hardsuit helmet

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by SonixApache** [comment]
work in the dark, slaves
