### ISSUE TITLE
NOIR mutation not working properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21866]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
92cac1831df201082d596b2d53cb3bcab30b1886

# Description
NOIR mutation claims to make everything black and white, only blood stays red. It actually just makes EVERYTHING B&W 
# Steps to Reproduce
I signed up as Gumshoe (another name for detective, can pick it in character setup). Blood is not red.
# What you Expected
I expected everything to be black & white and blood shining red
# What Actually Happened
Blood is not red. Refer to screenshot https://i.imgur.com/ou6lQNx.png

**Comment by Dacendeth** [comment]
This worked a month or so ago.  #21622 maybe broke it?
