### ISSUE TITLE
AIs can be headrevs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21873]
(WEB REPORT BY: fozzington REMOTE: 206.221.180.138:7777)
# Revision
64777ebf692130ae47c2423dab832c2cf9c96ed7

# Description
When revolutionaried, the AI receives no new or updated laws to fulfill carrying out its objective, thus also posing the risk of blowing the entire mode open via warning heads of upcoming murder
# Steps to Reproduce
>Be AI
>Get selected as Revhead
# What you Expected
Valids
# What Actually Happened
A clusterfuck of Asimov and Rev

**Comment by Kurfursten** [comment]
it's on the restricted list, odd
