### ISSUE TITLE
Gun inhands that need replacing

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#2187]
Many guns reuse the generic revolver or laser sprite and could use better ones.

:white_large_square: Ion rifle
:white_large_square: Laser rifle
:white_large_square: Captain's antique laser
:white_large_square: Combat shotgun
:white_large_square: Pump shotgun (armory)
:white_large_square: Double-barreled shotgun
:white_large_square: Mini uzi
:white_large_square: Laser pistol
:white_large_square: Retro laser
:white_large_square: Laser AK470
:white_large_square: Blue/Red laser tag guns
:white_large_square: Laser cannon
:white_large_square: Xray gun
:white_large_square: Plasma pistol
:white_large_square: Light plasma rifle
:white_large_square: Plasma rifle
:white_large_square: Plasma MP40K
:white_large_square: Decloner
:white_large_square: M1911-P
:white_large_square: Floral somatoray
:white_large_square: Radgun
:white_large_square: Stun revolver
:white_large_square: Xcom assault rifle
:white_large_square: Submachine gun
:white_large_square: Silenced pistol
:white_large_square: Desert eagle
:white_large_square: Gyro pistol
:white_large_square: Dart gun
:white_large_square: Syringe gun

**Comment by ComicIronic** [comment]
The new system is explained in #2116.
Python is for nerds.
