### ISSUE TITLE
More Observed Blob Issues

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21872]
~~It seems /datum/event/thing_storm/blob_storm can still fire, causing a blobstorm without costing threat.~~ fixed

You can't right click on an overmind to admin pm

~~Blobs can actually expand into a full strength emitter faster than they get deleted, making an odd situation where it appears a single blob piece is moving forward (because the piece behind it dies as it grows). Needs a CD.~~ fixed by #21931

~~Blob still firing on roid? Needs testing~~ Now has its own issue

**Comment by ShiftyRail** [comment]
Non-overmind storms are still random events, that's intended

**Comment by Kurfursten** [comment]
It had an overmind and resulted in 45 minutes of blob creeping around the asteroid

**Comment by Kammerjunk** [comment]
just find the player in the F6 player panel, the mob is the untargetable camera

**Comment by Kurfursten** [comment]
It shouldn't require the extra step
