### ISSUE TITLE
[Feature Request] Remove the Curb Your Enthusiasm music from the escape shuttle playlist

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#21883]
[featurerequest]

It already plays during Curb Your Round End, so it's really redundant when it plays on the shuttle, then again during the credits.

**Comment by Kitfox88** [comment]
>not having music muted other than the actual credits CYE theme

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Close this
