### ISSUE TITLE
trying to strip someone as borer controlled monkey freezes game

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21895]
(WEB REPORT BY: spoonylove REMOTE: 206.221.180.138:7777)
# Revision
f7042e5b775849c5e18e95afa4c0fd41d9e879a4

# Description
Tried to strip someone, game froze up and booted me out, dreamseeker improper argument window popped up.
# Steps to Reproduce
be monkey controlled by borer, try to strip a dead body.

# What you Expected
to work as normal
# What Actually Happened
dreamseeker window pop up, then game freezing a few seconds later.

**Comment by DeityLink** [comment]
the fuck?

**Comment by DeityLink** [comment]
Unable to reproduce over here.

**Comment by spoonylove** [comment]
Im not sure what the problem was. The body was a recent suicide. Later on in round tried it again on the pets around station stripping worked fine, maybe it was just on my end somehow?

**Comment by DeityLink** [comment]
Sounds like a weird Byond bug that had like one in a million chance to occur. Let's keep it open for a month or so.
