### ISSUE TITLE
Double Taser gun

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21891]
(WEB REPORT BY: haligue REMOTE: 206.221.180.138:7777)
# Revision
f7042e5b775849c5e18e95afa4c0fd41d9e879a4

# Description
That's an a taser gun and a taser gun. It is a normal-sized item.

# Steps to Reproduce
Get a taser and with the same hand click in another taser.

# What you Expected
Nothing to happen.

# What Actually Happened
MainGrip with double taser icon, one next to other, and a icon of another taser in second grip.

**Comment by MadmanMartian** [comment]
This madlad's discovered akimbo!
