### ISSUE TITLE
Moving along a beam's axis let's you phase through it.

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#2190]
![emitter](https://cloud.githubusercontent.com/assets/7573912/5428714/85ef4404-83ce-11e4-9490-33e2dec68e4c.png)

WEBM to illustrate: https://dl.dropboxusercontent.com/u/33846352/beam_issue.webm

Steps to reproduce:
1-turn on an emitter
2-move onto the beam, the beam will stop at you and deal damage as usual
3-move one tile on the beam's axis (in one direction or the other) and the beam will now continue through you and you won't take any damage.
4-moving one tile again will make the beam stop at you and deal damage again.

**Comment by d3athrow** [comment]
does this still exist?

**Comment by DeityLink** [comment]
It does. half of it at least, I just tested. The beam stops at you if you move toward the emitter, but it still goes through you if you move further from it.
