### ISSUE TITLE
Improve Objective Tracker (for players)

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21906]
It would be really nice if, as a player, you could see if your objective is currently considered successful or not, like on the admin panel.

**Comment by aceedex** [comment]
Thats nice but also you can check if your target is dead or alive which is worrying

**Comment by Kurfursten** [comment]
Some objectives could be marked as uncertain if not false

e.g.: escape alive and free shows FAILED if you are currently cuffed or sitting on the red shuttle squares, but otherwise UNCERTAIN. This is particularly the case for things like the wish granter "kill everyone" or the syndie "hijack with no other organic lifeforms" objectives.

Objectives that are incremental (blood, soul blood, chemicals absorbed, genes absorbed, rooms defiled, survive 5 minutes, cover tiles in blood, cover tiles in blob, steal skulls) would show progress.
