### ISSUE TITLE
timer-timer assembly bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21920]
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
fd2459528f0aac4e9209e6ad1554018738a509bb

# Placing timer timer assembly on fueltank repeatedly, moves the sprite to the right, to the point it is not visible anymore

# place assembly on tank, take it off, rince and repeat

# expected sprite to stay in place

# It actually moved and disappeared

**Comment by Tokanova** [comment]
hilarious

**Comment by SonixApache** [comment]
dupe of #21301
