### ISSUE TITLE
Cryo doesn't kill slime people.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21927]
(WEB REPORT BY: buttbot REMOTE: 206.221.180.138:7777)
# Revision
b734333e44125ed77249df35a0ea86f9177c5551

# Description
Whatever cold vulnerability slime people have doesn't stop them from being cryo'd just as well as anyone else.
# Steps to Reproduce
Become a slime person from xenobio
Get shoved in a tube
# What you Expected
Death
# What Actually Happened
Healed to full

**Comment by DrSnips** [comment]
FeatureTM. Cryo is snowflaked to prevent people inside from getting celt'd. It you want some kind of bullshit ic reason they play nicely with the magic heal tube's biotic fluids and it prevents them from truely freezing.

**Comment by bathosbathtime** [comment]
While a slime person would be worse off, I can assure you that the temperature cyro works at would kill a real human bean as well.

**Comment by Sooose** [comment]
I can vouch that the cryo murders slimes instantly, just not slime people.

**Comment by MadmanMartian** [comment]
Fairly sure the cryox and clonex is also supposed to basically eat slimes.

**Comment by MadmanMartian** [comment]
Were they wearing the coat you can get from xenobiology? The one that basically undoes any negatives slimes have?

**Comment by DrSnips** [comment]
Neither of those statements are true. Clonex and cryox don't have a special interaction and why would they. The raincoat dispite the name doesn't prevent you from getting sprayed it's a wintercoat.

**Comment by MadmanMartian** [comment]
Huh.

**Comment by Killette2** [comment]
I thought the logic behind this was that cryo was just warm enough to not affect slime people on minimum default freezer temps
