### ISSUE TITLE
Cult sacrifice target can be the last person to be converted during Act II

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21935]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
3ef18b052f04ee18f7b3d6cb762702a8ec7063af

# Description

Which is extremely problematic if said target chooses to box.

**Comment by Kurfursten** [comment]
Not sure if this would be abusable, but it would be nice if "talking to narnar for advice" reset the sac target automatically if it's an impossible target
