### ISSUE TITLE
Another beam issue

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#2195]
If you push a dense (like a welding fuel tank) item directly against an emitter (on the side that it's facing), the first part of the beam will be directly on top of the emitter. Pushing the item aside will let the beam pass but this first beam tile will stay on top of the emitter until turned off.

Oh, and imo beams should blow up welding fuel tanks and crack open canisters. but that's something different.

**Comment by d3athrow** [comment]
Does this still exist?

**Comment by DeityLink** [comment]
Nope, it's been fixed apparently.
