### ISSUE TITLE
Invade Runtimes

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21951]
[19:11:27] Runtime in invade.dm, line 18: type mismatch: cannot compare /list (/list) to 2774
proc name: IsFulfilled (/datum/objective/invade/IsFulfilled)
usr: Carrie Loyce (kurfurst) (/mob/dead/observer)
usr.loc: The floor (153, 258, 1) (/turf/simulated/shuttle/floor)
src: Invade the station. (/datum/objective/invade)
call stack:
Invade the station. (/datum/objective/invade): IsFulfilled()
/datum/objective_holder (/datum/objective_holder): GetObjectiveString(0, 1, /datum/admins (/datum/admins), null)
blob conglomerate (/datum/faction/blob_conglomerate): AdminPanelEntry(/datum/admins (/datum/admins))
blob conglomerate (/datum/faction/blob_conglomerate): AdminPanelEntry(/datum/admins (/datum/admins))
/datum/admins (/datum/admins): check antagonists()
Kurfurst (/client): Check Antagonists()

**Comment by Zth--** [comment]
#21938

**Comment by Kurfursten** [comment]
Great
