### ISSUE TITLE
lightning x2

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21971]
(WEB REPORT BY: repertor REMOTE: 206.221.180.138:7777)
# Revision
4cc066f3b557ca5ff239511d628e33520ccfc3c9

# Description
There are two instances of lightning in the spellbook, possibly replacing ice barrage
# Steps to Reproduce
open spellbook
# What you Expected
to find ice barrage
# What Actually Happened
Lightning in its place, allowing for two seperate lightning spells

**Comment by MadmanMartian** [comment]
Oh lawd, I think the one is the one from the emperor bundle.

**Comment by ShiftyRail** [comment]
Got fixed.
