### ISSUE TITLE
Old viruses are seemingly incurable, and can be acquired on Roidstation

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#21972]
#### Description of issue
We had a round of Extended on Roidstation the other night where the captain found a crate with old virus samples (magnitis, specifically). About half of the active crew tried, one by one, to find a cure for it, but nobody could figure it out. Eventually we all just gave up and accepted that the entire station would have to live with it. It was sort of fun, but also clearly unintended gunk.

The old viruses show up on health analyzers and scanners, but don't behave like modern viruses with radium, antibodies, the isolation centrifuge, et cetera. The suggested cure of "iron" didn't work, either, and honestly, I don't remember how the old viruses worked.

#### Difference between expected and actual behavior
Expected: The old virus to behave like the new viruses, or at least to respond to iron as the health analyzer suggested

Reality: Every member of the crew winds up with a permanent magnetic field

#### Steps to reproduce
1. Acquire old viruses
2. Spread that shit around
3. Everyone is permanently gunked

**Comment by SGuivenne** [comment]
The obvious easy fix is to remove that crate, the less obvious actually useful fix would be to find out what the hell happened and make sure its not something horrifying that'll come back to bite everyone in the ass four patches down the road.

**Comment by DeityLink** [comment]
I'll never understand why we still have old virus code. Just replace them with new disease2 symptoms.

**Comment by DeityLink** [comment]
Fixed by #23724
