### ISSUE TITLE
AI using cusom emotes (/me "...") don't have their name displayed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21984]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
bd8449478efeeddc20da5c9501edd64a70bf8ce0

# Description

See title, they just get displayed as "(stuff)" instead of "<b>(AI name</b> (stuff)"

**Comment by boy2mantwicethefam** [comment]
You feel the urge to SCREAM!
I thought I reported this bug. Nobody picked up on it. Maybe a runtime? I'm too scared to delve into saycode which probably has the "me" emote
