### ISSUE TITLE
EMP Pulsar not on by default

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#21985]
(WEB REPORT BY: shadownil REMOTE: 206.221.180.138:7777)
# Revision
bd8449478efeeddc20da5c9501edd64a70bf8ce0

# Description
EMP Pulsar revheads get does jack shit because it's not on by default in your pocket.

# What you Expected
For it to do stuff and stop me from being fucked by shitter silicons

# What Actually Happened
Waste of an antag roll

**Comment by Kurfursten** [comment]
This isn't a bug, it would immediately give you away since it pulses every tick. Use it in hand to turn it on, dummy.
