### ISSUE TITLE
Revs Should Account for Latejoin Heads

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#21990]
This is the perfect thing for faction processing

**Comment by boy2mantwicethefam** [comment]
Would be neat but it would lead to revs spawncamping to kill the heads who late-join in the worst case scenario

**Comment by Kurfursten** [comment]
not a bad idea, we can put it on a 5 minute timer

**Comment by Hoshi-chan** [comment]
Will cult account for latejoin sec?

**Comment by Kurfursten** [comment]
Cult does not receive objectives to assassinate each member of security if that's what you're asking.

**Comment by Hoshi-chan** [comment]
Cult fires or doesn't depending on whether or not there is roundstart sec.

See #21946

**Comment by Kurfursten** [comment]
You may be missing what I'm talking about in this topic. Revs and Cult are roundstart *only* (not counting RevSquad and Provocateur) which means by definition they cannot factor in latejoin sec that aren't there.

What I'm talking about is that Revs should get new objectives to target heads who latejoin, not just the heads present when the revolution starts.

**Comment by ShiftyRail** [comment]
It already accounts for latejoins heads to add them to the objective using an event.
I don't know what else you want to do but you could build it from that.

**Comment by Kurfursten** [comment]
Does it? I asked around and people said no

**Comment by ShiftyRail** [comment]
https://github.com/vgstation-coders/vgstation13/blob/4cc066f3b557ca5ff239511d628e33520ccfc3c9/code/datums/gamemode/factions/syndicate/rev.dm#L141-L151

`OnArrival` is (should) be called every time a new player joins in.
It worked when I tested it.
