### ISSUE TITLE
Roundstart blob assistant spawns in very noticeably different jumpsuit.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22005]
(WEB REPORT BY: spoonylove REMOTE: 206.221.180.138:7777)
# Revision
b35f642e5728df5cd89796e58f7107879dfa3196

# Description
Spawn in as blob assistant in aux tool storage with about 4 other assistants. Everyone sees Im in a purple jumpsuit and proceeds to lynch me before I've even begun playing.

# Steps to Reproduce
roundstart assistant blob

# What you Expected
to secretly be the blob unnoticed until I popped away from everyone.

# What Actually Happened
Insta Lynch because the game tells everyone next to me I'm the bad guy.

**Comment by bathosbathtime** [comment]
Did you know that if you have a subjob as an assistant, your jumpsuit changes to match the department you are an assistant to?
EDIT: Did you have the research assistant subjob?

**Comment by Kurfursten** [comment]
he confirmed that was the cause in ahelps
