### ISSUE TITLE
Blob: Lock down the station for ever edition

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22001]
#### Description of issue
- blob spawns 2 minutes into the round
 - valiant squad of assistants beat it to death with welders
 - `Directive 7-10 to 7-12 Concluded.`
 - one minute passes
 - `Directive 7-10 Initiated`
 - station now permanently locked down

#### Difference between expected and actual behavior
lockdown shouldn't occur when there's no blob

#### Steps to reproduce
good luck. Probably kill a blob within a minute of it spawning?

#### Length of time in which bug has been known to occur
~~#21968 probably.~~ yes surely an unmerged PR will affect this
no idea

#### Server revision
2c36cc95a9a145d86365513d3a6ddd4fb2c0e6b8
[bugfix]

**Comment by Kurfursten** [comment]
I believe staging will fix this but remind me to check
