### ISSUE TITLE
Spaceacillin prevents antibodies from curing diseases

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#22004]
#### Description of issue
Took Spaceacillin to slow disease progression, made antibodies, injected them and stood around still with my little sad face HUD icon. 

#### Difference between expected and actual behavior
for spaceacillin to slow disease only not prevent cure.

#### Steps to reproduce
be infected, inject spaceacillin, then antibodies, check and see if still cured.

**Comment by Kitfox88** [comment]
does it just slow down everything to do with the viruses including the curing effect because if so laffo

**Comment by DeityLink** [comment]
Fixed by Nuviro
