### ISSUE TITLE
Mobile immobile lockers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22019]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
e2adab7432543216b9babc334ff5d3440c4e306c

# Description
Security lockers on packed station can be dragged ez pz
# Steps to Reproduce
drag warden or hos or sec. officer locker.
# What you Expected
I expected them to be immobile
# What Actually Happened
they are mobile

**Comment by Sooose** [comment]
None of these lockers are immobile on any map.
