### ISSUE TITLE
Suggestion: Make Antimov's laws more obvious to the silicon.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#22016]
My suggestion would be having the text red when the silicon is viewing their laws; too many times people don't even notice they're on antimov since its so easy to just skim over it when you think its just asimov.

EDIT: I didn't realize how vague I was being, I mean only the silicon should notice they are on antimov, not the rest of the crew.

<featurerequest>

**Comment by SonixApache** [comment]
i thought the whole point of antimov was that it flies under the radar for most people causing hilarity

**Comment by Sooose** [comment]
@SonixApache My suggestion was to make it more obvious for silicons, not players. Silicons breaking their laws should be avoided at all costs, laws are the only reason they're allowed to exist.

**Comment by Kammerjunk** [comment]
>having the text red when viewing laws

So what, matching law text to (current) Antimov text? Making Antimov specifically output some red text when you get it?
either sounds ehhh

**Comment by Sooose** [comment]
The idea was that the text displayed via Show Laws verb would be red, the actual text itself would be identical. I'm open to other ideas but I feel it should be more obvious for the silicon receiving the lawset that its not asimov.

**Comment by SonixApache** [comment]
fair, I guess.

**Comment by Kammerjunk** [comment]
thing I'm asking is what determines it
Would it be literally just checking for the Antimov laws text or making a "bad stuff" lawset type
Would that work at all for freeform?
etc

**Comment by Sooose** [comment]
It could expand to all bad stuff if the coder felt so inclined but I only feel it's needed for antimov. People tend to actually read their other lawsets, antimov you might just skim over when you think it's Asimov.

**Comment by Kammerjunk** [comment]
It isn't really critical enough to warrant a bandage
not my codebase and it isn't really used often so whatever but not measuring technical debt (and/or having so much of it already) shouldn't mean encouraging it

**Comment by Sooose** [comment]
This was just a suggestion, If it's truly not liked I don't care one way or the other. The only reason I even bothered to make this suggestion was based off an AI and Borg completely missing the fact that they were on antimov until I checked their laws an hour later. It's definitely not the first time this has happened either.

**Comment by SonixApache** [comment]
One time there were two AIs, me and another, and we were both rogue without knowing that the other was rogue.
The other AI framed me for some crime, PDA'd humans to order me to state my laws, and then uploaded a script to telecomms that replaced my normal asimov callout with antimov.
I didn't notice till after I was lynched.
