### ISSUE TITLE
Golems DNA locking mechs does nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22015]
(WEB REPORT BY: spoonylove REMOTE: 206.221.180.138:7777)
# Revision
59316332ccd540d08e963bf931aa5b44b52a0783

# Description
As a golem DNA locking a mech shows that you did it but doesnt stop others from entering your mech. The other in this case, another golem
# Steps to Reproduce
as a golem go inside mech, dna lock, then have a different golem get in and pilot it.
# What you Expected
for my lock to work
# What Actually Happened
nothing

**Comment by Kitfox88** [comment]
why would a magic rock monster have dna
