### ISSUE TITLE
Inflatable shelters do not show multiple people in them anymore, defualting to only the sprite of the first one in.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22025]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
bdd516573cc6f178b6e13b2f76dd7494fb98adbd

# Description
This was observed as of the current patch.
# Steps to Reproduce

Get multiple people in a shelter, watch only one sprite
# What you Expected

Multiple people crowded awkwardly
# What Actually Happened
Dissapointment

**Comment by SGuivenne** [comment]
In addition, chairs clip into the shelter in a way that shows them inside of it when they should probably just be hidden.

**Comment by Kurfursten** [comment]
It never showed more than the first person
