### ISSUE TITLE
Game breaking bug involving teleporters and beacons

### ISSUE THREAD

**Issue by SirSkeleto** [d3athrow/vgstation13#22021]
[bugfix] [byond] [loose]
Throwing a beacon or something containing a beacon into a teleporter (rightly) throws it in a random place on a random z level. If the beacon is inside of a subspace tunneler, it will teleport inside of itself forever, destroying the server and crashing your game if you witness it.

**Comment by Shadowmech88** [comment]
Do you mean the thing with the beacon inside of it is teleported randomly, or the beacon itself is removed from the item and teleported randomly?
If the former, then based on the code, I can't see why this would be happening, The subspace tunneler stores its held objects in its contents list, which should be essentially the same as storing a beacon inside a backpack or a locker or anything else.

**Comment by Exxion** [comment]
Works On My Machine:tm:

**Comment by SirSkeleto** [comment]
> Do you mean the thing with the beacon inside of it is teleported randomly, or the beacon itself is removed from the item and teleported randomly?
> If the former, then based on the code, I can't see why this would be happening, The subspace tunneler stores its held objects in its contents list, which should be essentially the same as storing a beacon inside a backpack or a locker or anything else.

operative word being should
try doing it on the test server
you can't, because i crashed it

to address your question, here's my guess at what's happening:
the teleporter checks if there's anything inside of it to teleport to the beacon
if the beacon in question (or a container holding it) is the thing being teleported, give it a random location
but because of the weird way in which the subspace tunneler "stores" items, it treats it as if it did not hold the beacon, so it teleports inside of itself forever. I think it tries to handle all of the stuff inside of it at once, so it never does anything else. I ghosted and tried to respawn and it said 0 seconds had passed since i died. that or byond sucks iunno

**Comment by Exxion** [comment]
You've gotta be skipping a step somewhere, because it consistently works just fine for me.

**Comment by Exxion** [comment]
Oh wait
It's not crashing but something weird is indeed going on

**Comment by Exxion** [comment]
OK yeah this has nothing to do with the subspace tunneler
It's just random
Turns out that the getting sent to deep space if you're holding the beacon isn't a feature
It's just because you have a 5% chance of ending up in deep space every time you use it if it's not accurate
And you're teleporting to the tile that the beacon is on, which is the teleporter's tile
So you just teleport again until you roll that 5% chance and end up in deep space
This happens anytime a beacon that the teleporter is set to goes through the teleporter, not just with the tunneler

**Comment by Shadowmech88** [comment]
Still, it'd probably be a good idea to just make the teleporter send you to space outright if you're holding the beacon it's pointing to. Avoid the unnecessary looping until it hits the 5%.

**Comment by Exxion** [comment]
Definitely
Among other reasons, it almost instantly drains the room's APC

**Comment by SirSkeleto** [comment]
test fire the station beforehand and you get a 0% chance
forgot to mention

**Comment by SirSkeleto** [comment]
that makes it the big fucky
