### ISSUE TITLE
Sprite Request: Corey In The House Anime Poster Skin.

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#22033]
#### Description of issue

It'd be glorious and that meme is ancient enough to fit with it.

**Comment by Hoshi-chan** [comment]
Anime posters are gone, friend. Server vote killed weeb. Now we just have a neutered space ninja.

**Comment by SGuivenne** [comment]
Well.  Shit.

**Comment by agentofzog2** [comment]
Being back anime posters.
Also Corey in the House is a boomer meme.
Now Neo Yokio, that's an anime.
