### ISSUE TITLE
QM debit card can adjust prices on all vending machines, making them ridiculously cheap

### ISSUE THREAD

**Issue by MadmanMartian** [d3athrow/vgstation13#22041]
Behold, economy

![image](https://user-images.githubusercontent.com/30557196/54461265-03595a80-4764-11e9-8f81-083afad6b87e.png)

Assumedly could also do it with the trader vending machine, as the set price thing came up there too, but didn't have a trading ID at the time.

**Comment by SGuivenne** [comment]
Delet this.

**Comment by SonixApache** [comment]
delet this

**Comment by DrSnips** [comment]
Feature

**Comment by Hoshi-chan** [comment]
It's a feature.

**Comment by Dacendeth** [comment]
The money you spend at vending machines goes to the QM card anyways so even if you couldn't set the prices you'd still be able to buy everything for free if you had it.
