### ISSUE TITLE
Leaper necromorphs should be shovable, like slimes

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22050]
#### Description of issue
- get glomped by necromorph
- switch to blue intent
- die within ten seconds because the fucker just won't come off
- turns out you have to hit them with brute to dislodge them

I feel like this could use some work. Sure, they're necromorphs, and our man Isaac goes around decapitating them since that's the only thing that works, but still.

#### Server revision
ce3cb14c600b5851e80d2a15b1aede0f77039772
[wyci]

**Comment by agentofzog2** [comment]
i died pls nerf
Also I feel like the mob is rare enough that it's okay for them to be absolute motherfuckers.

**Comment by SonixApache** [comment]
More of a consistency issue than a NERF IT PLS issue. Died because of lack of know-how.
Considering that using a toolbox gives you a solid 75% chance to knock the fucker away anyway, I feel it isn't too much of a stretch.
