### ISSUE TITLE
emagging a milf borg removes the milf

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22060]
- hot MILFs **ON YOUR STATION**
- :b ok get ready to gas the carbons on my signal
- :b no AI, it is you who is being gassed
- LONG LIVE THE SYNDICATE
 - round ends

When you emag a borg that's slaved to a malfunctioning AI, it completely overrides the malfunctioning laws. Which is kind of dumb.

#### Server revision
dd729f397d9a2abebbb8cc816dfe90a31327fed7

**Comment by Tokanova** [comment]
working as intended
emag strong

**Comment by ShiftyRail** [comment]
Nothing wrong with that.

**Comment by SonixApache** [comment]
>Nothing wrong with that.

No, there's actually a lot wrong with that.
Malf, as-is, is a round-ending gamemode. Killing the AI ends the round.
Malfs get very little tools to actually do things. Their only real interaction with the world is through the borgs. Being able to steal a borg from their control is intensely crippling.
Emagged borgs would make for a great diversion tactic for a malf AI, and the additional equipment would help as well.
Not to mention that traitor borgs can be emagged without them losing their original objective.

It's a dumb oversight that should be fixed.
