### ISSUE TITLE
Trash outlet in asteroid station just dumps into a roid tile instead of space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22066]
(WEB REPORT BY: gunosaguki REMOTE: 206.221.180.138:7777)
See description, the outlet at engineering just collects outside of engineering, causing a massive lag fest if you try clicking on it to inspect

**Comment by GeneralVeers25** [comment]
Functioning as intended - the idea is that it gathers there then can be launched into space to land on the Vox outpost.
