### ISSUE TITLE
Some Maps Have An Extra Null Rod

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22078]
(WEB REPORT BY: arxix REMOTE: 206.221.180.138:7777)
# Revision
39eabef0ce403b26f919bf72d5f27ce47970550e

# Description
Two null rods one in my pocket, second on the table on box station
# Steps to Reproduce
Start as Chap
# What you Expected
3 Null Rods if possible
# What Actually Happened
Woke up as a priest of Old Headism and saw that I have one null rod in my pocket and second one is on the table

**Comment by MadmanMartian** [comment]
Chaplains start with a null rod, and there's a null rod mapped on some maps.

**Comment by Exxion** [comment]
You know, I think this is the first time someone misinterpreted the bug report form in this particular way

**Comment by DamianX** [comment]
>What you Expected
>3 Null Rods if possible

I think he knew exactly what he was doing.

**Comment by Exxion** [comment]
I meant the title

**Comment by Kitfox88** [comment]
taking some cable and making nullrod nunchucks when
