### ISSUE TITLE
Shuttle Doors Need Robust Logging

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#22085]
Investigating them with fingerprints doesn't cut it, too much shit that can just bump it without prints

**Comment by ghost** [comment]
They should bolt when shuttle takes off, there's glass windows right there anyway.

**Comment by Kurfursten** [comment]
Shuttle doors are in pods too

**Comment by ghost** [comment]
Those should bolt too, doesn't make much sense to freely open doors during transit.

**Comment by Kitfox88** [comment]
I'd miss ZAS shenanigans but bolting on transit seems like a reasonable and easy solution.
