### ISSUE TITLE
Dynamic Antagonist System starts to fall apart at high pop

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#22094]
#### Description of issue
Round quality has been significantly hampered lately with incidents of 15+ antags in a dangerously short period of time due to the sheer high pop.  While this systems decent on low and medpop it seems to be struggling with the current 80+ server players.

On the bright side the station lags been surprisingly tolerable so clearly the coders have done well with that.

**Comment by Kurfursten** [comment]
This is being caused by latejoining refilling the threat over and over and over.

this #22059 will probably stop most of it and turn these rounds rapidly into extended
