### ISSUE TITLE
Lascannons are doing 60burn.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22095]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
1de47cdf182848f59d9097eefbd4c3f8b82f33c3

# Description
Remember when that pedo dude doubled their damage?
# Steps to Reproduce
Shoot a lascannon, perhaps as a combat borg
# What you Expected
less damage
# What Actually Happened
kind of too much damage

**Comment by SirSkeleto** [comment]
this is intentional

**Comment by Killette2** [comment]
I could have sworn it was supposed to be 40 up from 30

**Comment by SirSkeleto** [comment]
lasers used to be 20, but they were changed to 30
lascannons were 40, but after lasers were changed to 30, they were changed to 60 so they would remain twice as strong as lasers as intended
