### ISSUE TITLE
Invulnerable on cargo cart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22115]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
1db74ee5c0d25bc25f49b3181d3df7db8a103d2b

# Description
I got stunned by shard hallucinations while buckled to a cargo cart, I became invulnerable and untargetted by simple mobs. It appeared that I was still wielding the guitar but I was able to grab items. I could not however, be unbuckled or do anything beyond talk.

# Steps to Reproduce
Follow the above.

# What you Expected
To fall off the cargo cart, or at least be able to unbuckle once the stun expired.

# What Actually Happened
I became an unkillable God with a guitar.

**Comment by Zth--** [comment]
Yeah I have to change a few things related to carts. I'll fix this
