### ISSUE TITLE
Feature Request: Xenoblood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22133]
(WEB REPORT BY: kharkov72 REMOTE: 206.221.180.138:7777)
Cult benos have been a thing coming up once in a while, yet the cultist xenos cannot actually do any cult things by themselves, due to not having blood (Even though they should have green, acidy blood). I think they should be tweaked a bit to have proper blood value and be able to do culty things.

**Comment by SonixApache** [comment]
i think xenos shouldn't be cultable in the first place

**Comment by SGuivenne** [comment]
that just sounds like 0 fun and being lazy.  Plus this would allow vampires to give xenos the S U C C.

**Comment by iFlashYou** [comment]
if vamps give xenos the succ then they should get their face melted

**Comment by gurfan** [comment]
close this janny
