### ISSUE TITLE
Gumshoe Vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22146]
(WEB REPORT BY: neray REMOTE: 206.221.180.138:7777)
# Revision
d77d0d64c9367122d57ec493349bb10a00987240

# Due to some changes to the way blood and steps on the floor work, Gumshoe can't see em in red as it should be according to wiki.

**Comment by Kurfursten** [comment]
Could this be #21622 related?

**Comment by AutisticDwarf** [comment]
I'd like to add that it's also impossible to examine anything on the floor: from blood and footprints to ghosts writings. Might be linked to that optimization as well or perhaps might be some dev decision, but regardless, it's breaking some intended features like, again, ghosts writing stuff in blood. Cheers!

**Comment by Kurfursten** [comment]
I don't think you've ever been able to examine blood, gibs, or footprints(?)

There are other things you can't examine too, like ash, dirt, gas overlays for N2O and Plasma, etc.

**Comment by AI-Is-Rogue** [comment]
IIRC you could just mouse over the blood, then eventually you had to alt-click on the tile, and now you can't even examine it at all.

**Comment by AutisticDwarf** [comment]
Well it seems that whoever was redesigning this thing forgot to do workarounds for some of the features linked to examining the stuff. But I digress, hopefully we'll get em red colors.
