### ISSUE TITLE
Bolas stuck on interface after being removed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22148]
(WEB REPORT BY: autisticmouse REMOTE: 206.221.180.138:7777)
# Revision
d77d0d64c9367122d57ec493349bb10a00987240

# Description

Get bolased, get them removed and they still appear on screen, floating above the backpack icon.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment]
Duplicate of #22482
