### ISSUE TITLE
Telescopic baton blood bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22152]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
d77d0d64c9367122d57ec493349bb10a00987240

# Description
Extending telescopic baton covers it in white blood
# Steps to Reproduce
grab telescopic baton, use it in hand
# What you Expected
my baton to be clean
# What Actually Happened
my baton got dirty

**Comment by Tokanova** [comment]
this has been happening for years.
no one reported it for some reason until now

**Comment by Kitfox88** [comment]
lewd

**Comment by Blithering** [comment]
https://github.com/vgstation-coders/vgstation13/issues/14166

**Comment by ShiftyRail** [comment]
Duplicate of #14166
