### ISSUE TITLE
Feature request: Cultist Mice

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22170]
(WEB REPORT BY: kharkov72 REMOTE: 206.221.180.138:7777)
Janitors can understand them, why can't cultists?
I want a scouting squeaksquad.

**Comment by Coxswain-Navigator** [comment]
I love it but it's gonna need a bare minimum of sanity, perhaps make it so that mice can't see runes so that the cultists have to lure them onto it with food (or maybe just a stun talisman?)

**Comment by DeityLink** [comment]
>converting simple animals

oh boy my sanity crumbles thinking of all the sanity I'd have to implement. I like the meme on principle, but I'm not eager to implement it anytime soon. Also janitors only have had this ability for like an hour.

**Comment by SonixApache** [comment]
🛑
