### ISSUE TITLE
Make coins useable as ghetto screwdrivers

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#22172]
'cus it's cool. Maybe make them a lot worse than screwdrivers, like 30 seconds to unfasten a window or something.

<featurerequest>

**Comment by punishedtoad** [comment]
>try to put coin in vending machine
>open up the maintenance panel instead
Same issue we have with trying to put wrenches on table, except it will come up every single time you try to use a coin for it's intended purpose.

**Comment by GoodG1448** [comment]
Haven't thought about that. Still, you can always click first on the vend and then click the "Insert coin" slot to place the coin.

**Comment by PaulRitter** [comment]
maybe just do it on harm intent?
