### ISSUE TITLE
Can spawn as ninja when latejoining trader

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22199]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
7a8a5f3a167a88516dbbb4de15cf45e8622dc167

# Description
Can spawn as ninja when latejoining trader

# Steps to Reproduce
Get unlucky when joining vox, end up a human with no suit in space

# What you Expected
Join as KAW

# What Actually Happened
Be a filthy dustbreather and die within seconds

**Comment by Kurfursten** [comment]
This is supposed to be forbidden

**Comment by SGuivenne** [comment]
What?  The secret of Crouching Tiger, Hidden vacuum exposure?

**Comment by Kurfursten** [comment]
Trader is on the forbidden list for ninja

`restricted_jobs = list("Trader")`

**Comment by tayachiya** [comment]
What about the other titles for trader? Because technically speaking I was a Salvage whatever

**Comment by SonixApache** [comment]
~~This was a latejoin. I don't see that line in the rule def for latejoin ninja.~~
Because that's all unrelated. I guess the code just doesn't work?
