### ISSUE TITLE
Cloning and cryo should be replaced with something different

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22202]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
7a8a5f3a167a88516dbbb4de15cf45e8622dc167

# Description
Medbay/cryo/making cryo mixtures is old and gay.

I suggest replacing them with a skeleton production machine that requires milk to function. Skeletons are automatically rolled out on a hanging rack onto a firing range in medbay.

The firing range has a biomass cannon pointing down it. Medical staff are required to operate the cannon and fire chunks of biomass onto the skeleton's limbs and torso until a humanoid shape is formed. The brain is then shot at the head of the humanoid mess to finish the job and clonexadone is splashed onto the finished product so that it grows skin, before being defibrillated.

**Comment by SonixApache** [comment]
can we ban nuke from git

wait

**Comment by west3436** [comment]
Low quality issue report

**Comment by SECBATON-GRIFFON** [comment]
TG is down the hall and to the left
