### ISSUE TITLE
MALF Ais cannot hack their borgs, nor can they Recall Shuttles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22206]
(WEB REPORT BY: agentofzog REMOTE: 206.221.180.138:7777)
# Revision
7a8a5f3a167a88516dbbb4de15cf45e8622dc167

# Description
A malfunctioning AI used to be able to hack its cyborgs through the robotics console, now that feature is gone.
Traitor Cyborgs cannot use this feature either though I don't actually know if they used to be able to do that.
# Steps to Reproduce
get antag roll as a silicon
# What you Expected
Cool gadgets, and a shuttle that won't just make you lose the round if you get spotted early.
# What Actually Happened
gotta make do with what I got and hope I don't do anything that might get the shuttle called while trying to kill everyone.

**Comment by Zth--** [comment]
First part was fixed here #24004
Keeping track of the second part here #23072
