### ISSUE TITLE
Age requirement for medbay?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22203]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
7a8a5f3a167a88516dbbb4de15cf45e8622dc167

# Description
Dark clouds gather over the medical wing.
Morgues, dimly lit by green lights.

The chemistry lab, populated by silent, bizarre men who shuffle around in muted torment, occasionally raising their hands to press a seemingly random button upon their arcane machines.

The cloning pod... eternally hungering for flesh, any flesh at all. Always deprived, always empty.

Yet no realm is more hopeless than Cryogenics, where dying men are trapped within tall tubes of biotic fluids, left to rot for hours as their wounds heal and rip apart simultaneously. The screams from these tortured souls puts any hell to shame. 

Their neon-haired torturer simply stares.

**Comment by Caboozles** [comment]
Saw someone immediately be an absolute chad and use all plasma on oxycodone. Then made 5u hyperzine pills.

I am all for this.

**Comment by vampirebat74** [comment]
In-game tutorial for age 0 medbay players when
