### ISSUE TITLE
Cult loses, but wins

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#22201]
>Objective #1: The Reunion: Meet up with your fellow cultists, and erect an altar aboard the station. Success!
>Objective #2: The Followers: Perform the conversion ritual on 4 crew members. Success!
>Objective #3: The Sacrifice: Nar-Sie requires the flesh of Cass Leek, the (Assistant), to breach reality. Sacrifice them at an altar using a cult blade. If you feel merciful for their soul, you may use an empty soul blade. Success!
>Objective #4: The Blood Bath: The blood stones have risen. Spill blood accross 478 of the station's floors to fill them up before the crew destroys them all. Success!
>Cult of Nar-Sie was successful!

In the round, all the blood stones were destroyed, every cultist was killed, and Nar-Sie did not appear. I don't even think there was nearly enough blood for the requirement, either.

**Comment by Kurfursten** [comment]
This is caused when the cult is defeated before spreading enough blood but blood gets spread later, because the stage() code exits out at L235 if the veil is mended.

@DeityLink

**Comment by DeityLink** [comment]
That's because faction code declares faction victory if not a single objective was failed, and yeah the objective was completed after Cult was defeated. That's an easy fix.

**Comment by DeityLink** [comment]
I added the fix to #22196
