### ISSUE TITLE
Lemme talk about some redirect to lobby job bullshit

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#22219]
Have a job selected to be high, med, or low, doesn't matter
Don't get that job and forced to roll assistant
Don't get assistant so forced to lobby
Hit join
My job was available

Jobs infamous for this are scientist and botanist, where botanist will only let you start with 2 but it will let you latejoin to get 3, and scientist lets you start with 3 but will let you latejoin to get 4. What is the point of this bullshit? Why can't I just get the role roundstart if it's open?

**Comment by Kurfursten** [comment]
~~I am 90% sure I know the reason this is caused. You sure this is being caused for Scientists on Box? It shouldn't. It makes sense you can't get 3rd botanist because there are only 2 spawn locs and that's what it's searching for. (Mapping issue)~~ Looks like Inti solved it

**Comment by Intigracy** [comment]
https://github.com/vgstation-coders/vgstation13/blob/578f7e7adb26f4a52cce49f9020b50a7ac6ac80f/code/game/jobs/job/science.dm#L53
https://github.com/vgstation-coders/vgstation13/blob/578f7e7adb26f4a52cce49f9020b50a7ac6ac80f/code/game/jobs/job/science.dm#L54

https://github.com/vgstation-coders/vgstation13/blob/578f7e7adb26f4a52cce49f9020b50a7ac6ac80f/code/game/jobs/job/job.dm#L21
https://github.com/vgstation-coders/vgstation13/blob/578f7e7adb26f4a52cce49f9020b50a7ac6ac80f/code/game/jobs/job/job.dm#L22

with the code as-is this was intentionally done

**Comment by Killette2** [comment]
But why? Surely this isn't intentional

**Comment by Kurfursten** [comment]
Fixed by Inti

**Comment by SirSkeleto** [comment]
why not just have 'em spawn in the shuttle roundstart so they can roll for antagge
