### ISSUE TITLE
Roid Derelict MoMMIs have no minerals on their Z-level

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#22220]
#### Description of issue
Derelict MoMMIs cannot go mining anywhere on the z-level they're not supposed to leave.
That means no T3 or T4 stock parts or batteries.
Sad!

#### Difference between expected and actual behavior
Box and Deff have the clown 'roid south-south-east of the derelict.
[roid] 
[oversight]
[discussion]

**Comment by Gunosaguki** [comment]
theres also a PR request to remove the clown roid, so if that goes through make sure to leave a base roid for the mommis!
