### ISSUE TITLE
RevSquad conversion may be broken

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#22241]
They do not have a limited number of conversions, this is caused because

https://github.com/vgstation-coders/vgstation13/blob/54b867f43151fc72a0689e4ef4375e6d321f4c33/code/game/objects/items/devices/flash.dm#L251

HandleRecruitedMind returns a role not a number... thanks Martian. In fairness he was porting it from predatum code and probably wasn't thinking too carefully.

**Comment by MadmanMartian** [comment]
>probably wasn't thinking too carefully

way to turn it into a double-stab. Dang.

**Comment by Kurfursten** [comment]
I didn't mean it in a cruel way, you had a lot on your plate to port

**Comment by MadmanMartian** [comment]
HandleRecruitedMind would've been still returning boolean at that point
