### ISSUE TITLE
Wine Pear and Baked Pear Recipe appear broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22276]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
b535c401647fd69a3d012c1668bb3ae4b155e652

# Description

After experimenting with both, neither seem to actually make proper recipes
# Steps to Reproduce

Try following wine pear and baked pear recipe
# What you Expected
Wine pears or baked pears
# What Actually Happened
Burned mess

**Comment by Irradiation** [comment]
Wiki updated to fix the recipe fuckup.

**Comment by SGuivenne** [comment]
That would do it.  Issue resolved, Irradiation with the fastest ticket fix in the west.
