### ISSUE TITLE
unlimited metal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22280]
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
b535c401647fd69a3d012c1668bb3ae4b155e652

# Description
if you only have one metal sheet you can make an embedded controller frame for one metal. Disassembling it with a wrench gives you two metal back. 
# Steps to Reproduce
Take metal sheet
Go to mounted frames
create embedded control frame for one metal
disassemble it with a wrench
get two metal back
# What you Expected
to not double my metal
# What Actually Happened
i doubled my metal

**Comment by Kitfox88** [comment]
learn this one mechanic's secret trick! miners hate him!

**Comment by SGuivenne** [comment]
if its just with metal this doesn't really seem like a big deal.  You can just use the borg rapid material printer and have them insert a shit ton of metal into machines anyway, its not that energy intensive.  Plus its common as dirt anyway.  

If this works with literally anything except metal or glass then I can see it being a concern.
