### ISSUE TITLE
Right-clicking a job preference to reduce the priority sets the high priority job to medium

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22283]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
Two different jobs, duh
Job 1 has medium preference
Job 2 has high preference
Right-click job 1 to make it low preference
Beside job 1 having low preference job 2 gets medium preference

**Comment by DamianX** [comment]
duplicate #8235
