### ISSUE TITLE
Captains armor doesnt fit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22294]
(WEB REPORT BY: alandemarest REMOTE: 206.221.180.138:7777)
# Revision
d1cd189c68cdc540d1dd0e4e1787dc170a09daea

# Description
Captains armor(chest) cant be put into suit storage unit, and therefore can't be decontaminated or stored.
# Steps to Reproduce
Take Captains armor out of storage, try to put in
# What you Expected

# What Actually Happened

**Comment by beesil** [comment]
Cap armor is a snowflake child of sec armor- it can be cleaned in a washing machine.
