### ISSUE TITLE
Tinfoil hats prevent teleportation even when in backpacks

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#22317]
Caused by https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/datums/helper_datums/teleport.dm#L236

[easy][bugfix]

**Comment by ShiftyRail** [comment]
I can only assume the recursive typecheck is for when you're hiding in a locker wearing a tinfoil hat.
The proc should check if the hat is effectively being worn.
