### ISSUE TITLE
C4 in lockers

### ISSUE THREAD

**Issue by ValkyrieSkies** [d3athrow/vgstation13#22327]
#### Description of issue
Bombs inside lockers don't do shit with anything in said locker.

#### Difference between expected and actual behavior
Expected: Place C4 with 3 Antimatter jars into locker and close door for big bang after 10 minutes.

Actual: The locker and 1 Antimatter jar are deleted and nothing else happens.

#### Steps to reproduce
See expected.

[bugfix] [oversight] [sanity]

**Comment by PaulRitter** [comment]
dunno if someone silently fixes this, but according to the code, this should have worked.

see: [closets.dm:320](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/objects/structures/crates_lockers/closets.dm#L320)

**Comment by Kurfursten** [comment]
tested, same effect inside and outside a locker
