### ISSUE TITLE
Brain Damage spell not blocked by tinfoil hat

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#22325]
`mind_affecting` instead of blocking spell being used on users wearing a tinfoil hat, instead prevents casting the spell as a user wearing tinfoil hat.

https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/spells/targeted/retard.dm#L18
`mind_affecting = 1 //Blocked by tinfoil hat`

`mind_affecting` is defined here https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/spells/targeted/targeted.dm#L31
`var/mind_affecting = 0 //Determines if it can be blocked by PSY_RESIST or tinfoil hat`

[easy][bugfix]

**Comment by Kurfursten** [comment]
Are you sure? Based on the code it looks like it works.

code/modules/spells/targeted/targeted.dm
`if(mind_affecting && tinfoil_check(user))`

Tinfoil hats are supposed to work both ways (prevents casting mind spells and prevents being targeted by them)

Targets get their protection in can_mind_interact (carbon.dm, starting L663)

**Comment by ghost** [comment]
I may have made a mistake.

**Comment by ghost** [comment]
Did testing, this issue still exists.

**Comment by ghost** [comment]
I hope someone checks reopened issues, ever.

**Comment by Kurfursten** [comment]
Confirmed in thunderdome

**Comment by boy2mantwicethefam** [comment]
It's a feature
I'll fix it

**Comment by DamianX** [comment]
closed by #22801
