### ISSUE TITLE
Can give Marble Statues of people the Ninja's Energy Katana

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22320]
(WEB REPORT BY: tokanova REMOTE: 206.221.180.138:7777)
# Revision
f71c67f5b69c1fcaa76465c747c4e5c7d4054a69

# Description
When messing around with a marble statue while a energy katana was stuck to my hand, It swapped with what the marble statue was holding, freeing up my hand
# Steps to Reproduce
Create Marble statue
Give Statue an item in its hands
Click its hand with the stuck on energy katana
Have your hands free again
# What you Expected
Not to be able to put the katana on someone and be stuck with a sword in my hand forever
# What Actually Happened
I was able to remove it from my hands by giving it to a statue

**Comment by Tokanova** [comment]
Addition: The Statue doesn't need to be holding anything, you can put it in an empty hand

**Comment by Kurfursten** [comment]
Yes deity used drop_from_inventoy instead of drop_item

I already have a fix for this and it considers both the "swap item" and "give item" cases (there are actually 4 total cases because you can also swap/give superglued clothing items which use a different if tree)
