### ISSUE TITLE
Tier 4 (Ultra) Capacitors disappear when unwrenched and don't work in railguns

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22333]
#### Description of issue

See title.
Not sure if it runtimes, don't have access to that kind of info.

#### Difference between expected and actual behavior
Wrench capacitor to grid -> charge -> unwrench -> 5 million joules of fuck -> place in railgun -> fire -> railgun deletes station
vs
Wrench capacitor to grid -> charge -> unwrench -> capacitor disappears :(
+
put VV'd capacitor into railgun -> fire -> charge var gets set to 0 and that's it

#### Server revision
8985a39ae581dea59b0fa8f002beedf1abda31e7

**Comment by Exxion** [comment]
>don't have access to that kind of info

The runtime logs are just as public as the other logs
You just don't have the pretty in-game runtime screen

Anyway, I don't see any runtimes related to capacitors, but sometimes these things don't show up very well

**Comment by SonixApache** [comment]
I fixed this in #23277
