### ISSUE TITLE
spider migration season 5: literally why edition

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22347]
#### Description of issue

![why](https://user-images.githubusercontent.com/8468269/55631697-ee974200-57b8-11e9-9369-94ac2456cfc6.png)
Spider queens launching themselves into space, shitting out webs constantly and eventually slamming into the station is really fucking dumb.

#### Difference between expected and actual behavior
fly through space until i hit something
vs
fly through space till i hit a web while a spider queen ODSTs through the virology windows

#### Steps to reproduce

literally any round with a spider queen anywhere near space

#### Length of time in which bug has been known to occur
since the spider AI changes

#### Server revision
6488a85bdbea69bbf1b4a005ffe9c5c544cbfad3

**Comment by MadmanMartian** [comment]
this happened before the change

**Comment by ShiftyRail** [comment]
The only way to solve this is to bring back tape

**Comment by DrSnips** [comment]
What if. Now hear me out on this. We make them require air like every other living thing so they don't walk in space forever until they hit the station.

**Comment by ghost** [comment]
Could just make them require a floor to make webs on.

I think emergent events such as spiders physically traveling from their nest to station are much better than random events spawning things out of thin air.

**Comment by DrSnips** [comment]
This still lets them float through space to the main station and doesn't solve the issue.

**Comment by FudgePucker** [comment]
Seriously, spider queens shouldn't have the same wondering around ability as normal space spiders.
They spawn in vaults to protect some super loot, and instead just fuck off into space.
One round I managed to make it to the ruskie DJ station, mock the crew for having to deal with xenos, only to have a spider queen bust down the airlocks and fuck my shit up. I thought it was an admin deciding to have a giggle, but when in dead chat they told me that it was a feature.

How many laser guns does it take to kill a single spider queen anyways?

**Comment by DrSnips** [comment]
I know it's more than about one ore two. Just give the a breathing requirement and call it a day. My other suggestion would be to not have queen spiders exist outside of hard mapping (spiders don't grow up to queens ever).

**Comment by FudgePucker** [comment]
Maybe have two different AI for space spiders, one that is mostly stationary until it finds a target for space vaults and pre spawned areas, and the roaming looking for shit to smash version for the infestation event and admin button pushing. The current behavior doesn't lead to them fucking around space when there are so many airlocks and things to smash on the station. It's only when they are pre spawned to guard important things that they fuck off into space.

**Comment by agentofzog2** [comment]
Making a creature that breaks windows above all else(besides lights) need to breathe is a retarded idea.
Spider migrations are a feature and the only negative part is them  making web roads in space.

**Comment by SonixApache** [comment]
>Spider migrations are a feature

Spider migrations are an unfortunate side-effect of a relatively recent AI change.
Your disposition towards random but guaranteed spiders in every round may vary.

**Comment by SonixApache** [comment]
related: #22363

**Comment by DrSnips** [comment]
Maybe dying to the cold or something then? Space traveling spiders are pretty shitty.

**Comment by FudgePucker** [comment]
What areas in space have round start spiders?
What incentives are there to risk fighting spiders is there to get the loot from those areas?

Why should it be the same risk of being sleep toxin'd and bleeding to death wondering around derelict station, compared to the shuttle that let's you travel practically to every consistant landmark in space?
You are just as likely to get ambushed by a perfect killing machine of death just minding your own business as the shuttle that let's you go anywhere being empty and free to take.

**Comment by MadmanMartian** [comment]
closed by #22391 and #22372

**Comment by FudgePucker** [comment]
If you want spiders coming and attacking the station, then add in a space spider migration event. Where they use the spawns of the space carp event.

**Comment by DrSnips** [comment]
I think the objective is not to have that happen

**Comment by FudgePucker** [comment]
Apparently some people think it's a feature

**Comment by PaulRitter** [comment]
should have been fixed in #22372?

**Comment by SonixApache** [comment]
i hate spiders but yeah
