### ISSUE TITLE
/me dabs

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#22354]
Make /me dabs cause you to suicide as well as *dabs, please and thank you.

**Comment by DrSnips** [comment]
Verb are separate from custom emotes with good reason. Also no because c*llabs already drove it into the ground epic retard style by making it do a ton of unnecessary stuff.

**Comment by SGuivenne** [comment]
Besides, this is an administrative and in character issue, dabbing to evade the *dab suicide makes you valid after doing it more than two times I think.

**Comment by DrSnips** [comment]
What? That sounds like it's because of macros and not the emote itself. If you're thinking of nerfing/removing that ability expect heavy resistance from the players. Also I'm pretty sure you're full of shit about being valid.

**Comment by Kurfursten** [comment]
I can't speak for headmins but if someone is macroing to spam dab  with another emote/along with another person to evade goonchat and fill your chatlog, I certainly wouldn't intervene if took measures necessary to make chat readable.

**Comment by Gringonius** [comment]
I am a big retard and I dab a lot

**Comment by nuklearcellphoneg** [comment]
Adding this will only remove under age players from our server.

**Comment by Gringonius** [comment]
*dabs*

**Comment by Intigracy** [comment]
*dabs*
