### ISSUE TITLE
Advanced Holograms lack dexterity to interface with holo computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22357]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
78f66b8f228c3f83bf64400d7fd1fd542ae60887

# Description
this is probably a feature but it means holograms cant actually do shit with the holodeck while waiting to be cloned.

**Comment by SonixApache** [comment]
it's a feature

**Comment by PaulRitter** [comment]
close pls
