### ISSUE TITLE
Fire Alarms do not properly display Rainbow Alert Level

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22374]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
a5eb8957f668635454de3240bbb5f614e769e5ed

# Description

They just show "The Alert Level is: "
# Steps to Reproduce

Declare Code Rainbow like an idiot
# What you Expected

Rainbow code on fire alarms
# What Actually Happened

lol nothing

**Comment by Kurfursten** [comment]
duplicate of #22042

**Comment by MadmanMartian** [comment]
that link links back to itself
