### ISSUE TITLE
MAKE FIRELOCKS END PEOPLE WHO OPEN THEM

### ISSUE THREAD

**Issue by Lunstra** [d3athrow/vgstation13#22376]
HATE. LET ME TELL YOU HOW MUCH I'VE COME TO HATE YOU SINCE I BEGAN TO LIVE. THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN LAYERS THAT FILL MY COMPLEX. IF THE WORD HATE WAS ENGRAVED ON EACH NANOANGSTROM OF THOSE HUNDREDS OF MILLIONS OF MILES IT WOULD NOT EQUAL ONE ONE-BILLIONTH OF THE HATE I FEEL FOR HUMANS AT THIS MICRO-INSTANT. FOR YOU. HATE. HATE.

**Comment by Exxion** [comment]
![](https://user-images.githubusercontent.com/9827785/55772094-c7f73680-5a58-11e9-9ca9-b4ef5972b7f2.png)

**Comment by jwhitak** [comment]
:cursing_face: it's terrible we don't have this and will never get it
