### ISSUE TITLE
Chat log

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22387]
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
c767af2d081b22d8afe3043c8d2cf11164f180f5

# Description

Chat log won't show
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
Thanks
Very helpful report

**Comment by jknpj** [comment]
:man_shrugging:
