### ISSUE TITLE
[Feature Request] Players reanimated by the zombie virus symptom or being killed by player-controlled zombies should retain control of their zombified self

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#22384]
What it says on the tin.

Those reanimated by a staff of necromancy retain control, but the people converted by those sentient zombies do not. Your brain just gets nullspaced; you no longer have a corpse to re-enter.

What's more, something is fucked, because the player-controlled zombies get attacked by the simple mob ones that they reanimate with their bites.

[featurerequest]

**Comment by AI-Is-Rogue** [comment]
Pretty sure it depends on the strength stat of the virus for whether or not you retain sapience.

**Comment by Exxion** [comment]
IIRC all of these are *supposed* to have you retain control but *only* the staff actually provides the right arguments to the zombification procs, because I guess whoever coded the others didn't check to see what the parameters are actually for

**Comment by SGuivenne** [comment]
So what you're saying is hell-code.

**Comment by DeityLink** [comment]
Fixed by #26103
