### ISSUE TITLE
inflatable shelter deletes uniform + contents

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22383]
(WEB REPORT BY: rpaul REMOTE: 206.221.180.138:7777)
# Revision
0390d6a1cd4b3c6cb0e6eda1e2586884c8875bf2

# Description
if you leftclick the inflatable shelter it removes your contaminated clothes and puts em in a parcel, only that it only places one item in there (in my case only my shoes). It ate my uniform, as well as my belt and my pda+id.

# Steps to Reproduce
click a shelter when you're wearing a contaminated uniform

# What you Expected
not to have my id taken away, and all the other shit. or to actually get it back when opening the parcel

# What Actually Happened
my shit got taken away

**Comment by Kurfursten** [comment]
Could not reproduce on live, all items were moved into the package

**Comment by juanototo2** [comment]
if you do it while inside the shelter and then click it all inside the shelter it deletes it, giving only 1 item
i think its because being in an inflatable shelter doesnt let you drop shit on the floor

**Comment by Kurfursten** [comment]
That wouldn't explain it either because in that case the items would just be inside the shelter and get dumped as soon as anyone deflates/pops the shelter.
