### ISSUE TITLE
Wizard clones can lock down a borg permanently

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22395]
(WEB REPORT BY: kitfox88 REMOTE: 206.221.180.138:7777)
# Revision
c0abe7a2d014d6cde8a4af1e58598c500dbcd180

# Description
Title
# Steps to Reproduce
Be a borg, encounter a wizard
# What you Expected
To be able to maybe stun a clone with my taser or something
# What Actually Happened
Got pushed into 16% systems integrity because the clone just runs around spamming magic missile and can't be stunned

**Comment by Kammerjunk** [comment]
maybe it's time to let simple animals be stunned

**Comment by Kitfox88** [comment]
It's not that big a problem with most simple mobs but then again most simple mobs don't have an autotracking ranged stun that they spam every other second while jittering around like a clown on crack. Lots of non-silicon crew also got deep dicked by the clones, unless you were able to engage them from multiple angles with multiple folk or had an extremely lethal ranged weapon like the glock or an egun.

**Comment by Kammerjunk** [comment]
well, simple animals that are supposed to be human anyway
would also fix the "how do prevent harm from Russian mobs as Asimov" problem

**Comment by Caboozles** [comment]
I think more annoying is creating clones while knocked down. Especially in conjunction with fireball or magic missile.

It pretty much means you can’t do anything without a lethal ranged weapon.

If you get close enough to stun baton someone, there should be some reward besides death. Even blink means they have to leave whatever they’re holding or driving.

**Comment by Dacendeth** [comment]
Why do the clones even get to cast magic missile, kind of devalues the actual magic missile spell similarly to how old blink devalued the smoke spell?

**Comment by Kitfox88** [comment]
they either need to die after a short time or a single pip of damage or cast fake spells that don't actually do anything, so that they're a distraction instead of an effortless way to kill people with zero risk due to the cloak of invishittery
