### ISSUE TITLE
Ethereal Jaunt on cooldown without use.

### ISSUE THREAD

**Issue by Sooose** [d3athrow/vgstation13#22402]
Ethereal Jaunt was going on cooldown without me using it all round, when I tried to click the button to see if it was really going on cooldown it would say that I am unable to use the spell. Also, the spell would displays the chains of being "locked" like someone else was using it for a period of time before it would randomly go on cooldown. I was never cloned or mind swapped, I was in the body I spawned with. The only spells I had were no clothes, jaunt and brain damage (upgraded). This was during CWC where a fellow faction caster also had jaunt (maybe the cooldown is tied to faction?).

**Comment by MadmanMartian** [comment]
Did you use mindswap at all?

Could you give me a list of all your spells?

**Comment by Sooose** [comment]
I listed both of those things in the OP, MM.
No mind swap, no clone.
Spells:
No clothes
Ethereal Jaunt
Brain Damag (upgraded)

**Comment by SonixApache** [comment]
this was during a civil war of casters, with one of the other wizards having the jaunt spell. Couldn't find any weird shared refs in the spell related stuff though I didn't search thoroughly.

**Comment by Sooose** [comment]
@madmanmartian come back I didn't mean it.

**Comment by DeityLink** [comment]
I'll blame that one on pooled objects
