### ISSUE TITLE
chatlog

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22406]
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
98bdcf1614d6106021052cf7d823889ff7506cab

# Description
Never finishes loading in 
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
You submitted an equally-unhelpful report on the same thing yesterday
