### ISSUE TITLE
black/white vision doesn't include bloodsplatter/footsteps etc

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22408]
(WEB REPORT BY: rpaul REMOTE: 206.221.180.138:7777)
# Revision
98bdcf1614d6106021052cf7d823889ff7506cab

# Description
i had my genes manipulated and saw black/white. then i walked into medbay cause i was seizing out and all the blood and vomit was in color.

might be that the blood and vomit was created after i went black/white

**Comment by Sooose** [comment]
Working as intended, it's noir vision for a reason.

**Comment by Exxion** [comment]
The blood is supposed to be in color, but I don't think the vomit is

**Comment by boy2mantwicethefam** [comment]
Vomit shouldn't, but blood is. @I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE 's fixes to blood so it's no longer a colored overlay was the thing that broke it

**Comment by robintime** [comment]
now you see NO colors!
