### ISSUE TITLE
Request, Remove all Collaborators and Form a perfect Communist Coding Society

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#22419]
#### Description of issue

The current collab system seems to stir up salt and drama at least once a month.  I propose instead we seize the means of collaborating and form the proper bleeding edge of a sickle, as our founding father Joseph Pomf intended to begin with.

**Comment by DrSnips** [comment]
Gamers rise up.

**Comment by ValkyrieSkies** [comment]
The c*ders killed Bagel... Our time is at hand for vengeance...

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
When you code it

**Comment by SonixApache** [comment]
😒

**Comment by SirSkeleto** [comment]
proposition: remove all collabs, collab a bot that merges a pr if it has more upvotes than downvotes after a certain period, depending on the type of change e.g. bugfixes are faster, balance/powercreep has to wait and get feedback first
