### ISSUE TITLE
[Discuss]Latejoins that aren't sec or captain or whatever role gives threat points right now should increase threat points by 1

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#22411]
They aren't included in the round's calculations except for midround roles for the purposes of population checks, this change should be negligible enough that at best it's going to squeeze several points out of the roundstart latejoiners or gradually increase the threat amount as people join the round by up to maybe 15 in the best case scenario when server pop transitions from european to american
Clowns should be excluded because they are bad enough to the station by themselves :clown_face:

**Comment by Irradiation** [comment]
Oh god no.

**Comment by ShiftyRail** [comment]
But no

**Comment by ghost** [comment]
I agree with this
![1521346680889](https://user-images.githubusercontent.com/39570790/56034354-f20c5b00-5cdb-11e9-9b7d-951cd4dedd0d.jpg)

**Comment by FudgePucker** [comment]
How comparable to readying up is this change? There are a lot of people that late join just after the round starts.
If it's about the same then :+1:, but if it increases the danger than the late join crew will substantially increase because people want to watch the world burn.

**Comment by bathosbathtime** [comment]
I agree with the core of the idea that more crew present more of a challenge to antagonists and the system should reflect that as well as possible.  Having late-joining crew give lesser amounts of threat makes sense and makes it so joining as security isn't completely shooting yourself in the foot by comparison.  However, I feel that dynamic is overtuned as is even without the population spike.  There's already too little downtime between antagonists currently for me to support this.
