### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22427]
(WEB REPORT BY: robosperg REMOTE: 206.221.180.138:7777)
# Revision
1cc52c6e232dea3accd207a72aa6b028ec0fc484

# Description
That's a ghost pepper. It is a tiny item.

This pepper is hainted. And pretty spicy, too.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Dacendeth** [comment]
Haint is a southern us word for haunt technically.

**Comment by ValkyrieSkies** [comment]
Cowboy speak isn't real English.
