### ISSUE TITLE
Add a darkmode for the chatbox/status/ic/ooc tabs.

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#22433]
My eyes want this. Also, fix the auto tagging stuff, the <[label]> thing doesn't seem to work.

Reminder that Tomorrow is superior to Yotsuba and all the other styles.
<featurerequest>

**Comment by aceedex** [comment]
the label goes on the OP not the title

**Comment by GoodG1448** [comment]
> 
> 
> the label goes on the OP not the title

There's a label in the OP, it's just invisible because of the <->. The MoMMI bot should set the tags.

**Comment by Exxion** [comment]
It's square brackets, not angle brackets.

**Comment by cadaverouscoyote** [comment]
hmmm sounds gay

**Comment by ShiftyRail** [comment]
The eyelets finally won #22914
