### ISSUE TITLE
IAA Printer to NT HR not giving admin notice

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22446]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
66375b7324cf4834d8c73bd19982a379f5555d1c

# Description

Tested, its giving a message transmitted successfully on client side, but admins didnt see anything
# Steps to Reproduce

be IAA, actually do job
# What you Expected

Admins to see I sent shit
# What Actually Happened

Apperently nothing?

**Comment by Sooose** [comment]
HR is for automated demotion chips with the right paper iirc
