### ISSUE TITLE
Blob Core Meteors May Be Creating 2 Cores

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#22469]
I talked to Avada about this over Discord and he reported to me that the bug of 2 cores next to each other during blobstorm is very common and usually the second core has no mind.

I'd like @ShiftyRail to take a look at this since I think this could be related to the new logic for throwing blob meteors. It's possible something with the impact is causing it, like tick delay.

**Comment by DeityLink** [comment]
It's been fixed now.
