### ISSUE TITLE
Latejoin Trader Ninja

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22463]
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
fa70a487ba634b85c7582ee9a54572fbd9b12fd3

# Description
When a trader latejoins they are launched towards the vox outpost in space. When a trader latejoins and gets randomed as a ninja their ninja is launched towards the vox outpost in space. Then they die in space.
# Steps to Reproduce
Latejoin as trader
Get randomed as ninja
# What you Expected
To play the video game in one way at least
# What Actually Happened
Ninjas aren't atmosproof and don't have internals

**Comment by spoonylove** [comment]
Ninja is just a rigged role.

**Comment by Kitfox88** [comment]
while you were gathering n2 tanks i was studying the sword

**Comment by Hoshi-chan** [comment]
Wouldn't have this problem if ninjas had the sweet ninja hardsuit that they used to have...
