### ISSUE TITLE
NuCult gemming sacrifice

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22464]
(WEB REPORT BY: kitfox88 REMOTE: 206.221.180.138:7777)
# Revision
fa70a487ba634b85c7582ee9a54572fbd9b12fd3

# Description
Nucultists cucked themselves cause they didn't realize a gem wasn't a sacrifice
# Steps to Reproduce
Be nucult, cuck yourself
# What you Expected
not for cult to be able to gem their sac target
# What Actually Happened
TRIED SO HARD AND GOT SO FAR BUT IN THE END IT DOESN'T EVEN MATTTERRR *clusterbangs in escape*

**Comment by Kurfursten** [comment]
Since you can request a new sacrifice target at the altar, this is not a bug as far as I'm concerned

**Comment by ghost** [comment]
It should automatically request a new sacrifice target when current one gibs/is not viable.

**Comment by Kitfox88** [comment]
if they're so new they don't realize gemming is not what to do i doubt they'll know how to request a new sac target, make that shit automatic

**Comment by Kurfursten** [comment]
If they haven't read enough of the wiki to know they have to drive a blade through the body of the sacrifice, they will never be able to get past act 2, no matter how many times the target switches. If we're going to go full handholding for antags, it would be more efficient to just make it impossible to gem the sacrifice target.

Automating the new sacrifice target is just a way of giving more free information to cultists about their objective status. In a game about information, do we really want to automatically and instantly inform the cult if their sac target has been gibbed or flew off level? They can already gather that information by Astral Journey or by testing at the altar.

**Comment by Allspice** [comment]
Was astral journey changed to let you haunt again yet? Because "use the haunt list to locate the target" was removed in cult 3.0.

**Comment by Kurfursten** [comment]
AFAIK you still can't haunt, but being able to float around the whole station like an AI eye that sees maint is a pretty nifty tool for finding targets.
