### ISSUE TITLE
All flashlight-like objects not functioning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22472]
(WEB REPORT BY: subs455 REMOTE: 206.221.180.138:7777)
# Revision
fa70a487ba634b85c7582ee9a54572fbd9b12fd3

# Description
A lot of objects that provide light arent providing light. Flashlights, PDAs, Hardsuit helmets, you name it.
# Steps to Reproduce
Obtain light.
Turn on light.
Bumble around in the dark.
# What you Expected
I expected them to like, provide light. like before. those were the good ole days.
# What Actually Happened
Their sprite shows that they're on, but no light is actually being emitted.

**Comment by ShiftyRail** [comment]
This was adminbussed
