### ISSUE TITLE
Glass Floor tiles aren't creating

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22471]
(WEB REPORT BY: suchai REMOTE: 206.221.180.138:7777)
# Revision
fa70a487ba634b85c7582ee9a54572fbd9b12fd3

# Description
glass floor tiles aren't creating
# Steps to Reproduce
try to create glass floor tiles
# What you Expected
having some neat floor
# What Actually Happened
disappointmend and day ruined

**Comment by FudgePucker** [comment]
Can confirm.
Glass tiles are fucked.

**Comment by Exxion** [comment]
As in you can't place them, or can't make them?

**Comment by FudgePucker** [comment]
You cant make them. An admin can spawn them in and you can place them. There is just no way to craft them

**Comment by Exxion** [comment]
I believe this is because the new path for them doesn't have a defined `max_amount`, resulting in runtimes
