### ISSUE TITLE
Radiation not being shown

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22489]
(WEB REPORT BY: glchun REMOTE: 206.221.180.138:7777)
# Revision
1f55ded4986a45a87b3247b831fd8559b094ff29

# Description
When the station went through a radiation belt, the botany lab was marked as a safe place. It wasn't.

# Steps to Reproduce
Test the radiation event.

# What you Expected
That botany was a safe place according to the flashing green light. 
# What Actually Happened
I got heavily irradiated and died.

**Comment by SonixApache** [comment]
what map tho

**Comment by Zth--** [comment]
Closing because lack of info and no one is going to test botany on each map to see if it's still relevant
