### ISSUE TITLE
fix the brig timer ui

### ISSUE THREAD

**Issue by PaulRitter** [d3athrow/vgstation13#22488]
[sanity]

presses +
window says 59
presses + again
window says 1:52
press -
18
why

**Comment by ShiftyRail** [comment]
It's because it's ticking as your press +/-.
I think.
Also it's ++ / -- , with the outermost signs meaning 1 minutes, and the other ones meaning a few seconds.
Finally, it only ticks 2 seconds by 2 seconds.
