### ISSUE TITLE
PLEASE FOR THE LOVE OF GOD MAKE LIGHT SWITCHES UNABLE TO BE HIDDEN UNDER OTHER WALL MOUNTED OBJECTS

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22481]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
1f55ded4986a45a87b3247b831fd8559b094ff29

# Description

HATE: I FEEL HATE.  IT FUCKS THE LIGHTS IRREVERSIBLY IF OTHER CREW CANT BE ARSED TO DEAL WITH IT REEEEEEEEEEE
# Steps to Reproduce

MAKE LIGHT SWITCHES BEHIND NOTICEBOARDS LIKE A PIECE OF SHIT
# What you Expected

TO BE ABLE TO FLICK THEM
# What Actually Happened

LOL FUCK YOU NO

**Comment by SirSkeleto** [comment]
alt click, lmao?

**Comment by Killette2** [comment]
Thanks, now I will do this to mess with people.
