### ISSUE TITLE
Service gripper cannot pick up broken bottles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22497]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
bf8a8415a1a661b06472802072ec212cac3f415f

# Description

This is irritating when running a bar
# Steps to Reproduce

Be service borg, try picking up broken bottle
# What you Expected
to pick it up

# What Actually Happened
ERROR. Your service gripper wasn't designed to handle the broken bottle.

**Comment by jknpj** [comment]
>/obj/item/weapon/broken_bottle

Jesus christ
