### ISSUE TITLE
Feature request 2: Make ninjas spawn in space

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22501]
[featurerequest]

As alternate to #22500, giving ninjas their original suit (we've still got sprites for it), internals and spawning them in space would be pretty rad. *Space* ninjas, y'know? Pretty sure that's how the old ninjas used to spawn as well.

Or maybe spawn them in a Z-2 Dojo, with a mass driver to launch them at the station?

**Comment by aceedex** [comment]
aint someone working on a ninja dojo or something

**Comment by Kurfursten** [comment]
@DrSnips is working on a dojo. He said to me that he started work in it on March 24.

**Comment by DrSnips** [comment]
Soon TM. There was a few ninja PRs so I held off of working on it for a bit. Seeing as those PRs are now merged I will continue.
