### ISSUE TITLE
telescopic baton

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22517]
(WEB REPORT BY: ktvii REMOTE: 206.221.180.138:7777)
# Revision
a6602c19991f2a5c0781952f2e44cd9357171de8

# Description
The telescopic baton is automatically covered in some icky white stuff when extended or collapsed.
# Steps to Reproduce
Extend or collapse telescopic baton.
# What you Expected
A telescopic baton without semen on it.
# What Actually Happened
A telescopic baton with semen on it.

**Comment by DrSnips** [comment]
The cum is stored in the baton.

**Comment by ShiftyRail** [comment]
Duplicate.
