### ISSUE TITLE
Hornets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22514]
(WEB REPORT BY: ktvii REMOTE: 206.221.180.138:7777)
# Revision
c33fc00d728036cd3e9267ba3c3fbc47b5f57d9c

# Description
The hornets will just kill the traitor botanist who planted them as soon as they start coming out, which makes them very unreliable in the longer run, since there's nobody to defend them from any would-be killers. They should consider the botanist planting them as their ally and never attack them.
# Steps to Reproduce
Plant some fucking hornets and die.
# What you Expected
I expected the hornets to see the traitor botanist who planted them as a bro of theirs.
# What Actually Happened
They fucking killed him, bastards. Fix it.

**Comment by SonixApache** [comment]
hornets are fucking assholes
