### ISSUE TITLE
Cult feedback and bug reports

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#22525]
@DeityLink

- Getting a target braindead in a locker or trapped in solitary is hellish. If your target goes braindead, or kills themselves, or is hiding in a locker for a prolonged period of time, they should reroll automatically after a few minutes. Alternatively, give the cult the ability to manually choose to reroll their target if they're having trouble finding them. Like, say they can't find someone for 30 minutes, let them reroll it themselves.

- I get why you'd keep cultists from speaking to deadchat or being able to use Haunt to just jump to people during Astral Journey, but their ghost form needs to move faster, and it should be able to see in the dark. A dark room is as bad as someone stuck in a locker, as far as finding your target with astral journey goes. In fact, as an information-gathering tool, it's virtually useless right now. It provides nothing that a radio tuned to sec doesn't already.

- Cancelling a cult reminder gives everyone a blank cult reminder. It should cancel properly.

- Soul blades inserted into altars _still_ aren't recruiting properly. It assigns the person's ckey to the gem in the blade, but it doesn't actually put them back into it, or something. You wind up with a braindead soul gem. This bug has existed for well over a month at this point.

**Comment by Irradiation** [comment]
> Alternatively, give the cult the ability to manually choose to reroll their target if they're having trouble finding them. Like, say they can't find someone for 30 minutes, let them reroll it themselves.

Now this is gonna be some serious dangerous territory unless it's balanced correctly.

**Comment by Allspice** [comment]
One alternative I remember reading (mebe from deity) is to give the altar an lock onto the sac target and watch where they are and such. Also has the upshot of finding the target through disguises/new UIUE/whatever. It's either that or letting Astral haunt people again, don't like the gimpy new astral for finding the target.

**Comment by DeityLink** [comment]
- he first issue can be addressed by re-adding the timer, but leaving the option of actually reroll to the cultists themselves. though @Irradiation 's concerns make sense, but I don't think it was such an issue in the previous version (granted the timed reroll was bugged for most of Cult 3's history). I could give the altar the ability to spy for a few seconds on the target on a global cooldown, but then I think it'd be interesting to let the target know that they've been spied on (and thus that they are the sac target), this way it's more of an emergency measure you'd only use if the cult is already outted and the target is impossible to find but still on Z1, while everyone will now converge on the target to capture/protect them.
- second issue is sensible, this rune deserves a buff.
- 3rd sounds like an easy fix.
- >It assigns the person's ckey to the gem in the blade, but it doesn't actually put them back into it, or something. 

I've seen that occur ingame myself, but that's really weird like what the fuck BYOND? Well now that only cultists can be channeled, I'll probably just reuse the mind transfer proc.

**Comment by Hoshi-chan** [comment]
One more thing that I JUST remembered: cult tomes stored in webbing (and perhaps other niche storage) cannot have talismans sent to them. Like, when you slap a talisman on the "conjure talisman" rune, if the person's tome is stored inside of webbing, it just won't appear on the list.
