### ISSUE TITLE
Can no longer open firelocks with an empty hand

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22538]
#### Description of issue

empty hand
click on firelock
why it no open???

#### Length of time in which bug has been known to occur
#22513 ?

#### Server revision
0eb3730c9a2610da9db64fefcffa8051713cab43

**Comment by Kurfursten** [comment]
did you have engineering access?

**Comment by SonixApache** [comment]
Yes.

Not that that matters for non-alert firelocks.

**Comment by Blithering** [comment]
This is also the case for open firelocks. Something definitely went fucky

**Comment by Kammerjunk** [comment]
Oh, I thought it just required an ID to do now for some reason. good to hear it's a bug.
