### ISSUE TITLE
streaming fixed on 100% volume

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22531]
(WEB REPORT BY: jatopreto REMOTE: 206.221.180.138:7777)
# Revision
0eb3730c9a2610da9db64fefcffa8051713cab43

# Description Everytime I try to change the volume of the streaming, I get the 100% volume for it.

# Steps to Reproduce Just trying to change the volume in general settings

# What you Expected I expected to put the volume on 15%

# What Actually Happened I got 100% all the time

**Comment by PaulRitter** [comment]
well someone did not understand the formatting
