### ISSUE TITLE
Can Combine Energy Katanas

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#22539]
Whoops

**Comment by boy2mantwicethefam** [comment]
It's a feature
Make it a dual katana

**Comment by SonixApache** [comment]
combining katanas should turn you into a space samurai

**Comment by Hoshi-chan** [comment]
Instead of a double katana, make it turn into an energy naginata or daikatana or something.

**Comment by Shadowmech88** [comment]
Fixed by #22871.
