### ISSUE TITLE
You can no longer insert coins into vending machines because you now use them to screw the machine open

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22537]
#### Length of time in which bug has been known to occur
#22442

#### Server revision
0eb3730c9a2610da9db64fefcffa8051713cab43

**Comment by boy2mantwicethefam** [comment]
just switch off from harm intent bro

**Comment by Irradiation** [comment]
What the hippiefag said.

**Comment by SonixApache** [comment]
that's fuckin' stupid

**Comment by Exxion** [comment]
Why were you even on harm intent in the first place

**Comment by Irradiation** [comment]
Because sec people and assistants get aids if they aren't on anything else than disarm/harm

**Comment by SonixApache** [comment]
probably had to move something or someone
