### ISSUE TITLE
Virology Creatine/Strengthening agent ineffective

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22548]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
85af3cc1cfa9b209738da9c980ce3dfcec7c5107

# Description
Trying to use the Strengthening Agent on a prion in the fully upgraded pathogenic incubator does not strengthen the symptoms, targeted or no.
# Steps to Reproduce
Repeat steps required to have creatine and a modified prion pathogen inside of pathogenic incubator while on.
# What you Expected
Strength of symptoms to increase
# What Actually Happened
Strengthening agent gets consumed but there is no apparent value change in the symptoms' strength

**Comment by DeityLink** [comment]
Disease strengthening code was completely rewritten 3 months later with the coming on nuViro. (#23461)
