### ISSUE TITLE
Box Security is a mess

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#22549]
Unplayable

![Untitled](https://user-images.githubusercontent.com/25004372/56456884-050cd400-6349-11e9-8be2-71241c11060b.png)
![2](https://user-images.githubusercontent.com/25004372/56456859-9d568900-6348-11e9-8a2f-f0f3d0ecd56f.png)
![3](https://user-images.githubusercontent.com/25004372/56456860-9e87b600-6348-11e9-9f58-731bb0e30c1b.png)
![4](https://user-images.githubusercontent.com/25004372/56456950-f96ddd00-6349-11e9-92af-626202809b28.png)

[box] [easy] [first] [oversight]

**Comment by ShiftyRail** [comment]
The tables in the unsecure armoury are a mix-and-match of r-tables and regular tables as well.

**Comment by Lokiamis** [comment]
Good catch

**Comment by Kitfox88** [comment]
box is a mess

**Comment by Lokiamis** [comment]
That fucking flashlight has been in space outside virology for like 3 years

**Comment by SonixApache** [comment]
pretty sure the virology flashlight is supposed to be there
rest is all cheap copypasta 
briefing room tables that hold the badges should 500% be non-reinforced tables
