### ISSUE TITLE
infinite metal rods

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22557]
(WEB REPORT BY: repertor REMOTE: 206.221.180.138:7777)
# Revision
6478a3d0a48ba64b48ab766d8d11996b1a4ced0b

# Description
creating a full stack of 60 rods makes an empty stack that can be used forever
# Steps to Reproduce
make full stack of rods and make a space bridge
# What you Expected
one stack of finite rods
# What Actually Happened
one stack finite one stack infinite

**Comment by LordMyroc** [comment]
This also appears to work with floor tiles.

**Comment by Exxion** [comment]
It's reasonably clear from the code why this drops an empty stack, but why the fuck does an empty stack let you use itself endlessly?

**Comment by PaulRitter** [comment]
so basically add sanitychecks material stacks

**Comment by Exxion** [comment]
Well that and fix `drop_stack()` so it doesn't drop an empty stack if told to spawn exactly the stack limit of something

**Comment by ShiftyRail** [comment]
Unable to reproduce
Nevermind
