### ISSUE TITLE
Mice can butcher corpses and attack inflatable shelters

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#22556]
#### Description of issue
Mice can butcher corpses and attack inflatable shelters

#### Difference between expected and actual behavior
What I expected:
Mice to be a cucked ghost role that eats cheese and screams profanities at the silicons

What I got:
Mice popping inflatable shelters and cutting meat and teeth off of human bodies

#### Steps to reproduce
1. Be a mouse
2. Repeatedly click on a body or inflatable shelter
3. Await bwoink for your terrible misdeeds

**Comment by Dacendeth** [comment]
Nothin wrong with eatin the dead squeak.

**Comment by bathosbathtime** [comment]
Mice butchering a feature

**Comment by DeityLink** [comment]
Looks like mice butchering was already fixed
