### ISSUE TITLE
Turning off your energy katana while cablecuffed makes you drop it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22566]
(WEB REPORT BY: shadownil REMOTE: 206.221.180.138:7777)
What the fuck I thought Space Ninjas were supposed to have their katana attached to their hand what gives?

**Comment by SirSkeleto** [comment]
only stuck to you while it's on.

**Comment by PaulRitter** [comment]
close pls

**Comment by PaulRitter** [comment]
also this explains me having seen some command dude running around with it
