### ISSUE TITLE
Wizard clones are overpowered

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22568]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
e9f3921ec3d280ce999448dcaba994b6080fd2e4

# Description
Wizard clones are unacceptably broken.
Full stop.

# Expected
Illusions or diversions
# Results
Unstunnable chainstunning Gods that will destroy everyone.

**Comment by FudgePucker** [comment]
They have 100 hp.
The same as a human.
Only they don't feel pain or bleed, only slow down from their crack speeds when dead.
Oh yea they also can move diagonally.
Did I mention they spam magic missile at everything?

**Comment by Kitfox88** [comment]
>pr up to drop them to 'only' 40 hp while touching nothing else about them

just. fucking. remove. them.

**Comment by ShiftyRail** [comment]
They no longer cast magic missile as of #22586
