### ISSUE TITLE
Ideas guy - Toggle Nightmare mode for medbay

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#22582]
We used to have infection from doing surgery with bloody gloves/tools and drag damage from dragging hurt people without a closet/rollerbed/bodybag. Admins can toggle hardmode for ZAS or hunger. What about doing the same thing for medical stuff?.

**Comment by Caboozles** [comment]
ZAS is already on hardmode.
The drag change was because it punished the doctors and patients but had zero effect on the person causing the trouble by dragging. It wasn’t to be “easymode.”
