### ISSUE TITLE
NO LATEJOIN CLOWNS (even on Code Rainbow)

### ISSUE THREAD

**Issue by agentofzog2** [d3athrow/vgstation13#22598]
Clown limit is permanently set to 0 and can only be bypassed by being a roundstart clown.
Also ban whichever c*der did this.

**Comment by jknpj** [comment]
feature

**Comment by Kurfursten** [comment]
What does the labor computer say if you try to raise it?

**Comment by RealestEstate** [comment]
this is bad. clown gang rise up.

**Comment by agentofzog2** [comment]
> 
> 
> What does the labor computer say if you try to raise it?

Nothing, it starts at 0 and stays there no matter what button is pushed
edit: actually it started (and stayed) at (0/) instead of (0/X) like for most jobs

**Comment by Kurfursten** [comment]
This sounds like a runtime.

**Comment by Kurfursten** [comment]
Caused by @boy2mantwicethefam in #22267

https://github.com/vgstation-coders/vgstation13/blob/14a156d135b2e2b135ecb2f2ecf3bf326252f07c/code/game/jobs/job/civilian.dm#L366

Does not return ..()

**Comment by brndd** [comment]
I've noticed that the clown limit doesn't change when you try to increase it as HoP during code rainbow. I thought this was a feature, but if it is, it's a dumb one.

**Comment by ShiftyRail** [comment]
>Caused by @boy2mantwicethefam in #22267

Repo ban when
