### ISSUE TITLE
Losing Mouse control

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22596]
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
14a156d135b2e2b135ecb2f2ecf3bf326252f07c

# Description
If you ever get down to the horrible "starving" nutrition level as a mouse your mouse will auto move towards and eat food, losing you most control of your mouse. If you ever reach this point no matter what you do you cannot stop the mouse from automoving towards food for the rest of it's life, no matter how fat you become. If this horrible loss of control mechanic is in the game, at least remove it when you are no longer starving.
# Steps to Reproduce
be a mouse
get under 100ish nutrition
be auto attracted to food
get over x nutrition
still be auto attracted and autoeating food until you die
# What you Expected
to not lose control of my character or at least regain control of it when it was no longer starving
# What Actually Happened
loss of character control to forced movement feels really bad

**Comment by Kitfox88** [comment]
c*ders going to buff mice thanks to miceclub smh
