### ISSUE TITLE
c*ders are retarded and made ir lasers delete themselves on spawn

### ISSUE THREAD

**Issue by PaulRitter** [d3athrow/vgstation13#22595]
apparently ir lasers made alot of errors but instead of fixing it c*ders just put qdel(src) in their New()

relevant lines [infrared.dm#L24](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/assembly/infrared.dm#L24)

wtf seriously

**Comment by SonixApache** [comment]
Man, that shit's been gone for three years already? I still remember using them to set up doorbells in cargo as if it were yesterday...

**Comment by PaulRitter** [comment]
blame pomf, the sneaky chicken

**Comment by DeityLink** [comment]
Fixed by #26698
