### ISSUE TITLE
dynamic mode exists

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#22616]
![rC4RIiY0mD](https://user-images.githubusercontent.com/6307265/56713001-63aac700-6728-11e9-953f-396eb003ef7e.png)

**Comment by ShiftyRail** [comment]
Okay maybe weight the curve center with the number of sec offs I dunno

**Comment by DamianX** [comment]
Literally hardcode only one roundstart roundender?

**Comment by ghost** [comment]
Some gamemodes hould never overlap, this was said before but ignored for some reason.

**Comment by SonixApache** [comment]
@DeityLink Two of the major complaints pre-datums were
 - x-stended because no new antags will ever spawn except on autotraitor
 - it's hard for admemes to bus in more high-level antags like cult

Now with dynamic and datums those two are solved, but I think the current setup for dynamic is a bit over the top.

**Comment by DeityLink** [comment]
I'd like us to put this into perspective, in the past 20 rounds:

* 15 times the threat level was between 40 & 60
* 2 times the threat level was bellow 40
* 3 times the threat level was above 60

Dynamic Mode was MEANT to allow for imbalanced chaotic rounds once in a while, and I think that with Shifty's new algo the frequency of those rounds has be quite toned down. If threat level is at 80% you expect the round to be chaotic for everyone, antags included.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Deity the theory is good and all but that screenshot is from when we got THREE CULT+OPS IN A ROW yesterday

**Comment by ShiftyRail** [comment]
The problem isn't that there's too many >60 rounds (my PR helped with that)
It's that 60 threat is enough for cult ops on some circumstances

**Comment by DeityLink** [comment]
and can't those circumstances alleviated by simply raising the costs a bit?

**Comment by ShiftyRail** [comment]
Was dealt with
