### ISSUE TITLE
Syndicate Codewords should appear in a color that stands out in chat, but only for the agents that have them.

### ISSUE THREAD

**Issue by SNilWillIllShill** [d3athrow/vgstation13#22613]
[featurerequest] [qol]

Basically like this:

Syndie Scum 1 has the codewords "tequila, MoMMI, scrubber" and the responses "janitor, medbay, screwdriver"
Syndie Scum 1 and Syndie Scum 2 share the same codewords and responses, and see the same text effects in the chat.

>Syndie Scum 1 [Common] (Assistant) says, "Hey, barman! **Tequila** sunrise please!"
>(not long afterward)
>Syndie Scum 2 [Common] (Scientist) says, "Could we get a **janitor** to science, please?"

I'm not sure if there should be two different colors (one for codeword and one for respective response) or if all codewords and responses should share the same color? Either way, this is to make people attempt to use their codewords and responses more, and maybe coordinate between other Syndicate agents in more rounds? Saying your codeword would make other Syndicate agents also see the codeword with the different text color in the chat - which would out you to them. And Syndicate agents are not obligated to cooperate with each other in their nefarious antagging.

This would:
>A) Cause uncooperative Syndicate agents who hear you to know you're a fellow agent and possibly target you. You wouldn't know who they are in turn unless they follow up with the appropriate response, which carries about as much risk as you would expect… unless you're doing this intentionally for a fun round of counter-subterfuge.

>B) Cause cooperative Syndicate agents who hear you to know you're a fellow agent and try to establish contact with you. By dropping your codeword and fishing for a response, you could bait other agents into outing themselves to you and risking you working against them in turn. This doesn't stop them from being more subtle about _how_ they establish contact outside of dropping their response word, though.

Thoughts on this? I cannot code anything for shit, but I wanted to drop this here anyway so others may benefit from the idea.

**EDIT:** Also should the words _only_ be color-indicated when it is another Syndicate agent that speaks them in chat, or when _anybody_ speaks them in chat?

The possibilities I see from "anybody who speaks a codeword, regardless of if they are a Syndicate agent or not, has it show up in color for Syndicate agents who hear it (but not themselves if they are a non-traitor)":

>A) You as a traitorous faggot speak your codeword over comms. The respective response to your codeword is enough of a commonly-used word or phrase that you can get multiple other people using it at the same time, but each time the word still has the same color indication. A devious Syndicate traitor who sees your codeword in the chat knows you are a traitor now, and might have spoken the response mixed with, say, _the four **other** greyshits spouting the same thing in a clusterfuck_ to muddy the waters for you - if they even speak their response for you to catch it at all.

>B) Same as the above, but applying to the initial codewords themselves too. A common-enough codeword could be something plausibly said by any multiple people within close timing of each other.

This way it won't simply be "Double Agents II: Electric Boogaloo" unless you make sure you use your codewords/responses in intentional ways only obvious to other agents through the color indication.
If ONLY Syndicate agents have their codewords/responses color indicated to other Syndicate agents, then that could allow for interesting wordplays and strategies like using "medical bay" instead of "medbay" if "medbay" specifically is your codeword, to avoid having you say "medbay" show up in unique color indication to that paramedic running by you in the hallway (who is a Syndicate agent but you don't know that - and since they notice the specific color text thanks to you, _they_ know _your_ identity now.)

**Comment by Irradiation** [comment]
Turns out that bumfuck non-antags are often code words recipients, which makes for very awkward scenarios where you splurge code words and they look at you with a blank face.

**Comment by Kurfursten** [comment]
Seth Tide [Common] says, "How are you guys doing the bold red text on radio?"

**Comment by Coxswain-Navigator** [comment]
Im all for it, its just a matter of finding someone to code it.

**Comment by brndd** [comment]
@Irradiation what do you mean? That non-antags have codewords spoken to them? Isn't that the entire point of code words, you can speak them to anyone and people will only know the real meaning of them if they're in on it?

**Comment by MercuryDoll** [comment]
It should trigger when ANYONE says it, this way there's no risk attached if the codeword is spoken accidentally. Taking your example, a syndie pointing out the MoMMI building cool shit in the ghetto bar and they're like "oh fuck that was a codeword!". It would immediately out them to other agents.
Responses should probably also be the same, and use the same color. That way there's an emphasis on context, making approaching other agents a more conscious action.
