### ISSUE TITLE
Assembly Frame copy/paste importing errors. 

### ISSUE THREAD

**Issue by spoonylove** [d3athrow/vgstation13#22611]
#### Description of issue
For some reason trying to import assembly frame data from a saved doc file on my computer causes the text to change when pasted into the game. If you look at this bit I put in picture form, for some reason the text fucks up voice analyzer turning it into aanalyzer. Trying to correct this error still leads to corrupt input data (possibly because the text is fucking up in other places as well now, and I have no idea what those errors are). Now heres the next dumb thing. The only way I can get the text to ever import properly for an assembly frame is to copy it into my PDA notekeeper first, rehighlight it in-game, the copy and paste it onto a paper. ONLY THEN will the assembly be able to be built when jammed into a frame. I had given up trying to import data a few months back because even doing that didnt seem to work. Theres gotta to be a better way to import an assembly frame into the game.

![errors](https://user-images.githubusercontent.com/32474532/56649174-80b49c80-6639-11e9-91f4-3b0546ea1489.png)

#### Difference between expected and actual behavior
Theres a few problems, import and export SHOULD be as easy as copy/paste from a text file onto a paper in game. What is actually required is a multi-step process of PDA to paper to ever get it to not be corrupt. 

#### Steps to reproduce
https://pastebin.com/x8vEuPH1 This is a pastebin of the assembly frame import file for my stupid ive been working on on and off. Try just copying that text onto a piece of paper then sticking it into an assembly frame. It should error out. Now copy that into your pda, rehighlight it and copy THAT text, it should build now.

**Comment by ghost** [comment]
The pastebin you posted has "aanalyzer" in it causing it to error out when directly pasted into a paper and then inserted into a frame. Changing "aanalyzer" into "voice analyzer" fixes the error. Exporting such a fixed version once successfully imported results in a correct version that can be imported/exported without issues or any pda pasting.

**Comment by spoonylove** [comment]
Fuck I swear I copied the right paper. I dont know why but when I change it manually myself It still comes back corrupt. 

Edit: I dont know what the fuck is up then, when I direct copy/paste from word it comes back corrupt even correcting the mistake, but copy/paste from notepad+ onto a paper in game it works fine. I have no idea now if the text error was on my end or if it actually was an export error.
