### ISSUE TITLE
AIs nullspace the cell in the telepad control console when they eject it

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22623]
#### Description of issue

click on telesci computer
click on eject cell
cell is now in nullspace

probably tries to put it in your hand or something, stupid

#### Difference between expected and actual behavior
be AI
go to telepad control console
click eject
cell pops out of computer
vs
be AI
go to telepad control console
click eject
cell disappears for all eternity

#### Steps to reproduce
be AI
go to telepad control console
click eject

#### Server revision
d93d06b0497bc2f47d4fa4534c4f9c4e69a8e0df

**Comment by PaulRitter** [comment]
this seems to go deeper than just this. normally user.put_in_hands drops the item when it can't put them in their hands. when the ai call it, it just yeets the item into nullspace.

**Comment by ShiftyRail** [comment]
Possible explanation :
The AI
1) has hands
2) said hands are in nullspace

**Comment by PaulRitter** [comment]
alternate reason:
`/mob/living/silicon/ai/put_in_hands(var/obj/item/W)
	return FALSE`
nice job c*ders
