### ISSUE TITLE
Change the cost of .357 revolver from 13TC to 12TC

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#22628]
It's shitty that when you buy the revolver for 13TC, you can only afford 1 additional box of ammo for 4TC and not 2 because you're short by 1TC for the second ammo box.

**Comment by Exxion** [comment]
Wow
Who was this?

EDIT: Apparently he made an account just to post this, then deleted it
I guess he didn't know about the in-game report button?
