### ISSUE TITLE
Only one person at a time can use the security cameras console

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#22637]
@ShiftyRail 

#### Steps to reproduce
- Be spessman
- Look at security camera console
- Have another spessman look at it
- Your camera gets reset

#### Server revision
Game: 1f131da8bd4dfb55546a640abc52a4859cb79461 
Patches: c93a73e08cbc2c3971a2b5fa69382c10ba7ad9e5

**Comment by Kitfox88** [comment]
But you can't use any console as two people without getting in each other's way, why would the sec cam console be different?

**Comment by DamianX** [comment]
What did he mean by this?
Most machines are designed to be used by multiple people.
Regardless, it used to work before shifty's change.

**Comment by DamianX** [comment]
Closed by #22966
