### ISSUE TITLE
simple mob speech broke

### ISSUE THREAD

**Issue by Chazach** [d3athrow/vgstation13#22633]
#### Description of issue

they dont speak anymore, just whitespace
tested and it occurs with zombies and other ones that dont make sounds, cats and dogs make their sounds and mice still speak like mice

probably #22351 [bugfix]

**Comment by ShiftyRail** [comment]
The exact runtime is : 

[05:07:13] Runtime in simple_animal.dm, line 328: pick() from empty list

proc name: say quote (/mob/living/simple_animal/say_quote)
src: the chicken (/mob/living/simple_animal/chicken)
src.loc: the floor (236,231,1) (/turf/simulated/floor)
call stack:
the chicken (/mob/living/simple_animal/chicken): say quote("<span class=\'\'>\"BWAAAAARK B...")
chicken (/datum/speech): render message()
the chicken (/mob/living/simple_animal/chicken): render speech(chicken (/datum/speech))
the chicken (/mob/living/simple_animal/chicken): send speech(chicken (/datum/speech), 7, null)
the chicken (/mob/living/simple_animal/chicken): say("BWAAAAARK BWAK BWAK BWAK!", null)
the chicken (/mob/living/simple_animal/chicken): say("Bwaak bwak.", null)
the chicken (/mob/living/simple_animal/chicken): handle automated speech()
the chicken (/mob/living/simple_animal/chicken): Life()
the chicken (/mob/living/simple_animal/chicken): Life()
Mob (/datum/subsystem/mob): fire(0)
Mob (/datum/subsystem/mob): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing()
