### ISSUE TITLE
The sound that airlocks make when opened/closed/blocked is hardcoded, even on sub-types (airlock/clown for instance) using istype

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#2263]
Any person who uses istype checks to assign different sounds to SUB-TYPES of an object should just not be allowed to code, period. That's LITERALLY what variables are supposed to do, WHY WOULD YOU RUN AN ISTYPE CHECK, THE ONE THING THAT CAUSES LAG WHERE THERE OUGHT TO BE NONE

I'll leave this here because I'm too busy to give a serious look and it should be a short fix

**Comment by ComicIronic** [comment]
Closeable.
