### ISSUE TITLE
Spawning normal catbeasts results in a runtime and a normal-looking human

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22632]
#### Description of issue

How am I supposed to destroy catbeasts if they ain't catbeastin'?

#### Length of time in which bug has been known to occur
Since #22541 maybe?

#### Steps to reproduce

spawn an/ta
behold, a human

#### Server revision
1f131da8bd4dfb55546a640abc52a4859cb79461

**Comment by SonixApache** [comment]
oh and krampus has the same issue

**Comment by SonixApache** [comment]
i was 5 hours out of date this was fixed in #22627

**Comment by Kammerjunk** [comment]
behold, Plato's man
