### ISSUE TITLE
Fist hits your own doppelgangers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22648]
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
716b4b042f245ae472a465c7dbf2b8cffacb9598

# Description
if you take fist and doppelgangers as a wizard your fist spell will hit your own doppelgangers. This is not good.
# Steps to Reproduce
get fist
get doppelganger
cast doppelgangers
cast fist
# What you Expected
to hit people other than my own clones
# What Actually Happened
i punch clone instead of people

**Comment by Intigracy** [comment]
Haha

**Comment by kernikov** [comment]
You also punch yourself, not sure if intended.

**Comment by ShiftyRail** [comment]
Simply check if the mob is indeed a doppelganger in the `get_targets` proc of the fist or whatever that's spelled

**Comment by ghost** [comment]
If you think that is bad, never take arcane golem and magic missile.
