### ISSUE TITLE
Cereal Maker Remove Incredient verb broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22644]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
1f131da8bd4dfb55546a640abc52a4859cb79461

# Description

Using it does nothing
# Steps to Reproduce

Put object in ceral maker, try rmeoving
# What you Expected
to remove item
# What Actually Happened
nada

**Comment by PaulRitter** [comment]
the cooking machines automatically process stuff added to them and spits it out, so this is not an actual bug i guess
