### ISSUE TITLE
MoMMI can't interact with bar dispensers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22642]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
1f131da8bd4dfb55546a640abc52a4859cb79461

# Description
MommI are unable to interact with bar dispensers in any way and there is no module apparent to enable them to do so
# Steps to Reproduce
Use bar-placed dispenser as MoMMI with or without shaker
# What you Expected
Access to shaker
# What Actually Happened
"Your programming forbids interaction with this device." According to Otatoh, there isn't a way to enable interaction.

**Comment by FudgePucker** [comment]
#22599
Should be merged soon if the "ivory tower" doesn't shoot it down.
