### ISSUE TITLE
Long Island Iced Teas don't show up in photos

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22667]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
318ba4fe86226e61f0e46918497bc62034299cdd

# Description
Taking a photo of a Long Island Iced Tea will result in it not showing up.
# Steps to Reproduce
Take photo of drink. Problem was not noticed until after sticking in news feed. That additional step may be required.
# What you Expected
Iced Tea to show up
# What Actually Happened
Iced Tea did not show up.
https://cdn.discordapp.com/attachments/563458184153661440/572126761450733599/unknown.png

**Comment by DeityLink** [comment]
Fixed by #29822
