### ISSUE TITLE
Make mecha DNA locks hackable?

### ISSUE THREAD

**Issue by PaulRitter** [d3athrow/vgstation13#22664]
[discussion]
DNA locks on mechs are very powercreep imo, should we add a way to hack them open/reset the dna lock?

obviously this would require alot of steps and time and would not be something that you can quickly powergame with two hands like unhinging a window.

**Comment by aceedex** [comment]
Emag/emp with maint door open IMO

**Comment by Caboozles** [comment]
Let’s not make emags even more of a godtool.

Make it require 1 minute plus of time. All this would do is encourage people to just scoot around in the mechs all day because the risk of it being stolen is too great.

**Comment by ghost** [comment]
I think having it be a simple timer is not a good enough discouragement. It should involve some active effort like solving a minigame, guessing the correct number sequence with some feedback about accuracy of current guess.

If it's just a click mech with x then wait then y and wait, everyone can attempt it it without much thought.

**Comment by PaulRitter** [comment]
maybe something like the locked crates, where you need to use the multitool and still have a 50% at the end if you do everything right

something like that but with having way less, maybe 25% at the end

and if you fail you get electrocuted or something, or the mech malfunctions and uses its weapon on you

**Comment by ghost** [comment]
Lethally punishing a player for a random chance fail check with no way of preventing it is something I'd rather avoid.

**Comment by DrSnips** [comment]
Just have it as a RD access locked function while main protocols are in effect. If the idiot inside forbid maint I think the RD can force them while at the console. If they removed the tracking beacon then the mech is valid salad and is likely being gunned down.

**Comment by ghost** [comment]
@DrSnips this is not about forcing a person out, it's about the mech being a brick when dna locked and the dna locker is unwilling/unable to unlock it.

**Comment by ghost** [comment]
Allow Sec/Med record computers to be able to print out "DNA Samples" of the crew, and if it matches the individual who it is locked to when applied to the mech, it will unlock.  It would also be really cool if you could cut off people's hands for it as well or draw their blood.

**Comment by ghost** [comment]
@DrSnips You even wonder if that maybe you are a little biased in regards to pushing things to benefit the only role you play/play mostly, and push for things for your own personal benefit as opposed to what is good in a greater regard?  Not saying anything in particular, of course.  Just thinking and stuff.

**Comment by PaulRitter** [comment]
this discussion is dead and so is this idea, im gonna close it
