### ISSUE TITLE
Russians don't say anything and only their names show up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22663]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
This is what happens when russians say something
![Russian](https://i.imgur.com/VzYb2h2.png)

**Comment by PaulRitter** [comment]
>[complains in russian] x12

seems good to me

**Comment by ShiftyRail** [comment]
Related to #22633 and fixed by #22634
