### ISSUE TITLE
New holomap CMC uses wrong coordinates

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#22681]
#### Description of issue

The CMC console shows coordinates which do not match the coordinates intended by Telescience, so there are really big offsets above the intended limit of 10 now

#### Difference between expected and actual behavior

Expected offsets which aren't gigantic

#### Steps to reproduce

Try to calibrate Telescience, notice gigantic offsets

#### Length of time in which bug has been known to occur

Since #22461 

#### Server revision

7a9df6c928d601bdeea7299a7e6ee84a3fef8697

You can now self-label your issue! The syntax is simple. Just put [<labeltag>] anywhere in your issue,
where <labeltag> is to be replaced by one of the following (allowing with the resultant tag)
just ctrl+f the list or something. I know it's long.

[bugfix] [oversight]

**Comment by boy2mantwicethefam** [comment]
What you're noticing is map drift, which is separate from telescience drift

**Comment by StreptoMutans** [comment]
You can only set the Telescience console to an offset maximum of +-10, which is not enough now. The c*der probably messed up the map drift thing so it's like this now.
Leaving the CMC open also produces lag

**Comment by SonixApache** [comment]
@PaulRitter

**Comment by PaulRitter** [comment]
Interesting, cause the vars i am showing are literally the turfs x and y values. I have no idea why this is happening, but im gonna test it later

**Comment by PaulRitter** [comment]
Important to note that these are also the vars used in the old one

**Comment by Exxion** [comment]
It's because the x and y values aren't the in-game coordinates

**Comment by PaulRitter** [comment]
which vars should be used

**Comment by PaulRitter** [comment]
`					see_pos_x = pos.x - WORLD_X_OFFSET[z]`
`					see_pos_y = pos.y - WORLD_Y_OFFSET[z]`
OOOPS

**Comment by brndd** [comment]
Yeah all the coordinates displayed in-game are intentionally muddled to make it harder to teleport stuff by looking up its location in DreamMaker.

**Comment by StreptoMutans** [comment]
When you scroll down it also goes back up every time it's updated, along with the increasing lag when you leave it open it cucks AIs

**Comment by PaulRitter** [comment]
@StreptoMutans i included a button to make it toggle the window updating, but i'll look into saving the scroll thingy.

What do you mean by increasing lag?

**Comment by StreptoMutans** [comment]
The game becomes more of a slideshow the longer you keep the CMC open. I had close it every couple minutes

**Comment by PaulRitter** [comment]
interesting, i'll look into it
