### ISSUE TITLE
Syndie Hardsuit and energy combat shield cant block ninja shurikens

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22683]
(WEB REPORT BY: oversane REMOTE: 206.221.180.138:7777)
# Revision
7a9df6c928d601bdeea7299a7e6ee84a3fef8697

# Description
literally why who the fuck coded the new space ninjas and why do they spawn on arrivals shuttle
# Steps to Reproduce
get hardsuit and syndie shield then get hit by shooricken
# What you Expected
to robust a weeb
# What Actually Happened
Overglorified Greytide has been hit by 3D printed shuriken.
You feel something rip in your head!
Your face becomes an unrecognizable, mangled mess!
Something feels like it shattered in your head!

**Comment by ShiftyRail** [comment]
>Bolas not being blocked by holograms

THIS CANNOT STAND

>Shurikens going through literally everything

I sleep

**Comment by ghost** [comment]
Armor doesn't make you immortal. All armor does is roll % chance to ignore or halve damage. There's always a high chance it will do nothing.
