### ISSUE TITLE
Crashing upon rendering Cult objects

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22700]
(WEB REPORT BY: anacondawarriorsupercommando REMOTE: 206.221.180.138:7777)
# Revision
15a47a9af88dbb372aeb563348dc6e7e3609dbe7

# Description
Sometimes when i get near a cult base i hard crash, i do not know what exactly is causing it
# Steps to Reproduce
 Walk near a cult base for the first time in a round
# What you Expected
Not Crashing
# What Actually Happened
I hard crashed and it took 2 minutes to restart byond

**Comment by DeityLink** [comment]
Need more information, has it been happening to other players as well?

**Comment by Exxion** [comment]
Are there a lot of icons created at runtime involved in Cult or something?

**Comment by ghost** [comment]
These crashes are caused by byond `animate` proc, which is used in large quantity for every flashing (correctly drawn with correct act) rune.

**Comment by DeityLink** [comment]
Huh, so other people have had it happen to them?

**Comment by SonixApache** [comment]
It happened to me at the same time yesterday. About an hour and a half in.
It was in a cult base, just post-sacrifice. There were two altars, a spire, two forges, buncha runes, cult floors, cult walls, cult doors, the works.
It became a crashbang, somehow.

**Comment by DeityLink** [comment]
Did it happen spontaneously, or was a specific rune/thing used?

**Comment by SonixApache** [comment]
Seemed spontaneously, but I didn't really get a good overlook on what happened.

**Comment by Exxion** [comment]
I'm not totally sure why this was closed, but there have been a lot of fixes to `animate()` in versions of BYOND released since this, so it's probably fixed

**Comment by DeityLink** [comment]
> 
> 
> I'm not totally sure why this was closed, but there have been a lot of fixes to `animate()` in versions of BYOND released since this, so it's probably fixed

I requested this to be closed since I haven't had reports of the issue in over 2 years now, and if it comes back we can always open a more current one.
