### ISSUE TITLE
Construct Health bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22706]
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
a7fe90035c38e7f62b461cf4cd2f175b504e25b4

# Description

HEalth constantly keeps decreasing, there is a fire icon 

# Steps to Reproduce

I have no idea, i was turned into artificer and the other guy was turned into wraith and both our health bars kep decreasing as if we were on fire

# What you Expected

not to die

# What Actually Happened

Health bars kept decreasing

**Comment by SonixApache** [comment]
To add to this, they were on an unenclosed space platform, on Deff, with a forge and altar on it. Quick investigation didn't reveal anything. @DeityLink

**Comment by DeityLink** [comment]
I'm theorizing that the altar's heating properties had a role in it, though it shouldn't heat past a certain point. Then again it was fully enclosed and with no air vents to cycle the air so.

**Comment by Exxion** [comment]
The forge won't heat if the temperature is currently above 50C, but it doesn't seem to have anything preventing it from overshooting that temperature in one operation
If there is very little gas in the area and the area is quite small, it can heat it up quite a bit
It takes half a tile of air and heats it up to a maximum of 1000K, so if the area is only a few tiles large it could conceivably get a bit toasty

**Comment by SonixApache** [comment]
there's no air on a space platform is there

**Comment by Exxion** [comment]
There is if there is
