### ISSUE TITLE
Right clicking an item as admin always offers the Admin-PM-Overmind verb

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22718]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
a3c1c05c5ed3e5945783bf1cfc18223fb90f3816

# Description
listed at the top before delete, happens only on items and not floors or people
why

**Comment by ShiftyRail** [comment]
It's either it happens on all objs (but only for admins) or it only shows up on blob overminds (but for all ghosts)
