### ISSUE TITLE
Please for the love of god buff cybernetic organs in some manner

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#22713]
#### Description of issue
Currently there is literally no reason to have cybernetic, assisted, or any other variety or organ of this manner because doing so is effectively an opt in to die within 1 minute of a supermatter shard detonates on the station.  If they provided some tangible benefit (decreasing oxyloss in crit, reducing plasma toxin damage, etc.) then perhaps people would actually use them as something other than a meme.

With the EMP gas proposal currently, there is effectively no reason to ever go near cybernetic organs lest you immediately die.

**Comment by ValkyrieSkies** [comment]
please stop trying to buff robotic prosthetics, let them be shit so they can peacefully be used as simple RP fluff without being another powergay topic of the hour

just add an advanced version of the limbs to robotics like there are for internal organs and get them that way if you want improved arms/legs

**Comment by Exxion** [comment]
There *is* a benefit to assisted and mechanical organs, but it's so minor most people don't know about it and it's completely overshadowed by the EMP vulnerability
But IIRC they can take *slightly* more damage before they begin to suffer negative effects from it
Very few things actually deal organ damage, so it's basically useless, though

**Comment by Caboozles** [comment]
Snowflake Tax.

I would be okay with there being some sort of high-tech requirement cybernetics/bionics that could give bored doctors something to do on less-busy rounds.
