### ISSUE TITLE
cult rolled at 49 threat with 1 sec and 10 people overall

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22719]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
a3c1c05c5ed3e5945783bf1cfc18223fb90f3816

its just taking the piss now

**Comment by DeityLink** [comment]
@ShiftyRail with your last update to dynamic, is high pop override disabled by default or not?

**Comment by DamianX** [comment]
yeah but 70% of the rounds are something something

**Comment by DeityLink** [comment]
With regular dynamic mode, threat level should be at 80 (or maybe 60) minimum to allow for roundstart cult. high_population_requirement however is 40, so it was most likely enabled.

**Comment by ShiftyRail** [comment]
The code for it is dispersed to the 4 winds
I'll put a fix
