### ISSUE TITLE
Metastation has a specific pop requirement for some reason even though it's literally box shuffled around

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22714]
(WEB REPORT BY: helpmepls REMOTE: 206.221.180.138:7777)
There is no conceivable reason why meta should have a pop requirement which effectively just means it's out of rotation in our post-sseth hellscape

**Comment by FudgePucker** [comment]
It creates server crashing gas

**Comment by ghost** [comment]
Ah yes, the station where you can access the AAC and atmos suits by just crawling under some flaps in the main hall.  I like that station.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Put meta back on and see if it crashes again
