### ISSUE TITLE
space bears can navigate in space at will

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22722]
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
82222271d15a05ce2820f3815a5b1518dbe726b6

# Description
In space space bears can move at will and chase anyone perfectly
# Steps to Reproduce
be in space
be near a space bear
try to run from the bear
get perfectly chased by it
# What you Expected
to be able to navigate away from the bear as it doesnt have a propulsion system
# What Actually Happened
the bear can navigate like it has a propulsion system

**Comment by boy2mantwicethefam** [comment]
That's just shitty simple_animal code, none of them care about gravity so they all move perfectly in space to chase you

**Comment by Exxion** [comment]
No they don't
Most simple animals can *sort of* navigate in space, but not very well
For bears specifically this is 100% intentional
![image](https://user-images.githubusercontent.com/9827785/57032230-e4316200-6c17-11e9-888c-97474e83aea0.png)

**Comment by SonixApache** [comment]
that's why they're SPACE bears

**Comment by Coxswain-Navigator** [comment]
Well thats kind of stupid
