### ISSUE TITLE
Ruleset idea : LASER TAG WAR

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#22744]
#### Description of issue

I have a good idea for midround semiantags
Two partners of NT are having a dispute over who gets the rights to distribute plasteel
So they have decided on the space station as a neutral ground, TO HAVE A LASERTAG WAR
They get a tag hardsuit (Can't be removed) a laser tag gun, and jetpack (O2). Their bodies gib upon death
Getting hit with a laser tag shot damages them, they gib upon death
They score points for their team based upon how many shots on the enemy they make, they can trade points for better gear
Like a long shot two handed tag cannon that acts like the sniper rifle that gives you far sight when two handing it
And a gatling laser tag gun
If the crew starts to interupt or disrupt their fight too much admins can push a button that lets them get laser tag eguns, like normal laser tag weapons, only they can hurt people not wearing lasertag vests/hardsuits

**Comment by ShiftyRail** [comment]
See also #10733

**Comment by FudgePucker** [comment]
Yea I remember making this request before antag datums were a thing.
