### ISSUE TITLE
vox can't alter farmbots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22745]
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
3a40e3639507f56e105c8d6b7521b0b9f3bcce8f

# Description
vox cannot alter farmbots that come with their station's permissions with their id.
# Steps to Reproduce
try using vox id on farmbot
# What you Expected
i would be able to unlock farmbot and alter it
# What Actually Happened
i was not able to

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Security measure to prevent farm animals from rising up

**Comment by Exxion** [comment]
My favorite type of issue is one with a title that sounds absolutely insane, but then when you read the report it turns out they only left out a little bit of information but it completely changed the meaning

**Comment by DDihanov** [comment]
I spawned with vox botanist and it had no problems unlocking the controls. Is there something I am missing?

**Comment by Exxion** [comment]
He said on the vox station
As in trader IDs don't have the access
Or more accurately, the farmbots on the trading post don't have the right access
