### ISSUE TITLE
the anti-buddybag """nerf""" makes it annoying to use bodybags on monkeymen which is a retarded collateral

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22750]
(WEB REPORT BY: helpmepls REMOTE: 206.221.180.138:7777)
if you want to carry a monkeyman in a bodybag you have to disarm him  like a retard and then it takes 5 seconds to open the bag again
all because one dumbass got mad at sec
sasuga c*ders

**Comment by SirSkeleto** [comment]
just use a rollerbed lmao

**Comment by boy2mantwicethefam** [comment]
just use a locker lmao

**Comment by jknpj** [comment]
>using something made to transport dead bodies to transport living mindless mobs
>complain that they don't behave

**Comment by Kammerjunk** [comment]
but I actually used that for real medbay applications

**Comment by ShiftyRail** [comment]
Or perhaps grudge coding is made by retards who actually didn't thought of what their change would cause
Who could have guessed

**Comment by strawberrytan** [comment]
just chloral them

**Comment by ghost** [comment]
There are other ways to balance buddy bagging. Random ideas in ascending order of frustration, least to most, top to bottom:

* Make pulling anything induce a large nutrition penalty, causing them to go hungry (slow) fast from hard work. Pulling is full speed only above yellow level nutrition.
* Pulling containers of human size mobs slows the puller down, includes prone human mobs.
* Can only walk when pulling objects.
* Pulling occupies both hands and takes time to stop/start manually.
* Can only push large objects and must use dollies for pulling. Loading/unloading dolly takes time.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
![1556908383246](https://user-images.githubusercontent.com/40967382/57167518-6ebec080-6dd4-11e9-8f2c-89a868865f9c.png)
I yearn for an alternate timeline where instead of clumsy reactionary nerfs and accelerationist psyops, we just ban the top 5 faggiest tactics.
But that's never gonna happen, so here goes this shit again

**Comment by ghost** [comment]
That is a very uninformed post.

**Comment by codeungabunga** [comment]
That is a very uninformed post.

**Comment by jknpj** [comment]
only a sith deal in absolutes

**Comment by bathosbathtime** [comment]
What, would we be banning the security officers for buddy bagging?  Even if all of the shitty counters or causes of buddy bagging gets banned, I believe it would still see use in its previous form as it is both useful and funny.
Of course I also like buddy bagging itself and think that security officers being hard to kill is a non-problem so I'm having trouble finding the issue with buddy bagging.  Do like the new sprite a lot, though.

**Comment by ghost** [comment]
clearly the best solution here is to remove all game mechanics so that it's just a chat and force everybody to engage in civil roleplay
