### ISSUE TITLE
the big boy blob red alert quarantine gives the crew nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22752]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
7f762ccaa4e8b87c25cc588425cc9ea8ec698475

# Description
no AIs and no consoles with power, the crew just gets a big "fuck you" along with having no shuttle

**Comment by west3436** [comment]
This was improved via the addition of the blob DEFCON levels in #29176.
