### ISSUE TITLE
ingesting phazon should be able to turn your blood to a random color

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#22757]
[wyci]

**Comment by SGuivenne** [comment]
If you want to be lazy you may be able to steal something to work off of from goonstations colorful reagent.  Should be in the 2016 release.

**Comment by Exxion** [comment]
1. We have colorful reagent
2. That has nothing to do with this request

**Comment by spoonylove** [comment]
Make it match the color your sprite turned into after eating the phazon
