### ISSUE TITLE
Loose catbeasts can and very often do use guns

### ISSUE THREAD

**Issue by Chazach** [d3athrow/vgstation13#22754]
#### Description of issue
lots of them seem to just stealth a hardsuit then go around shooting people and lurking in space, it doesnt really feel like what the design intention was (if there was any)

**Comment by boy2mantwicethefam** [comment]
Make them not use guns but make them start with maintenance access

**Comment by ghost** [comment]
What's with the recent trend of making antags into clumsy clowns? They have already many penalties, no need for more.

**Comment by ghost** [comment]
This is a non-issue, catbeasts always spawn in the same place with a pretty hard to miss announcement. If the crew doesn't kill them fast enough that's their fault.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
They really shouldn't do that to begin

**Comment by Kurfursten** [comment]
Catbeasts definitely should not start with maintenance access. Having to steal an ID is a major part of their progression and it limits their mobility. This punishes the crew for allowing someone to get killed/robbed/leaving unattended bodies and braindeads around, and in the opposite case rewards the crew for not letting those things happen.

Catbeasts in space do not generate threat, they are nothing more than traitors with no traitor gear, and an inability to wear magboots, and periodic self stuns. Get it together crew, if a catbeast is shooting you from space shoot back or walk away from the window.

**Comment by Allspice** [comment]
I believe "the idea" for the catbeast in space, would be to shoot out the windows and chump the crew as they fall over and get sucked out.

**Comment by SGuivenne** [comment]
> I believe "the idea" for the catbeast in space, would be to shoot out the windows and chump the crew as they fall over and get sucked out.

Without magboots catbeast would end up in Zas hell too trying to take advantage.  Magboot toggle is a major part of that strat.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
No. You're ZAS immune while standing on a space tile.

**Comment by Kurfursten** [comment]
I don't understand where we got to the point in Space Station 13 history where we're complaining that an antag can steal a hardsuit and shoot out windows. Is this really the server that has always demanded Hellish ZAS?

**Comment by LordMyroc** [comment]
Honestly if you're so incompetent that you let a self-stunning handicapped antag whose arrival is announced to the entire station manage to get a hold of hardsuit and **guns** then you kinda deserve your fate. Git gud you unrobust scrubs.

**Comment by ShiftyRail** [comment]
Catbeast was the most stupid idea in forever, both for the generated threat and for that

**Comment by Kammerjunk** [comment]
wow it's only like a few days I ago I asked how the proposed purpose of the catbeast antag (a sort of fast burner high-score thing supposed to just generate some threat and conflict until it dies) fit with it being entirely incognito as soon as it slips into an exosuit (hardsuit, fire suit?, softsuit)
imagine that

maybe a lot of things are mistakes

**Comment by bathosbathtime** [comment]
Loud antagonists spawning on the arrivals shuttle is a very interesting design choice.
As for the announcement, does that pop as soon as the catbeast spawns?  I was under the impression there was a delay.

**Comment by Kurfursten** [comment]
90 seconds

**Comment by Blithering** [comment]
I'd prefer if catbeasts were focused on evading getting rightfully lynched rather than killing anyone in their path, not much point in different antag types if they're all going to be murderboner but with a different skin.

**Comment by Killette2** [comment]
Hot fix: Threat isn't generated unless your body is exposed where flags like your tail aren't hidden. You can't defile rooms (too much) if you're not exposing your catbeast bits.

**Comment by Kurfursten** [comment]
It just feels like babyproofing the ruleset. All you have to do is stop unknowns in the hallway and make them say "me". This is a 100% foolproof test because catbeasts are forced to say "meow" instead (plus you'd see their name which is always a cat joke). You don't even have to make people pull off their helmets. And you only have to do this test in the first place if you have a bunch of people running in hardsuits AND you're being punished for letting someone get robbed of a bulky suit+helmet.

I've said my piece though, all of these arguments more or less boil down to how little we expect of the modern player. In a game ostensibly about gathering information we don't expect them to do any searching at all.

**Comment by ShiftyRail** [comment]
I'm sorry but it reads like "how are vampires even real, just ask them to stand in the chapel"

Catbeasts are still antags and still have the initiative

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
At some point we really have to stop and consider 'OK, maybe we can force the player to go through this laundry list to metastomp the catbeast when it happens, but is this actually good gameplay? Or just a completely unplanned song and dance spawned from a half-assed addition, that we're retroactively defending so we don't have to say whoops we added a bad ruleset?'

**Comment by Intigracy** [comment]
The antag is fine, the ease at which it can hide itself is the problem.

**Comment by ghost** [comment]
Imagine if there was an antag type that spawned with an ID, crew manifest entry, looked exactly like a regular human, could wear shoes and gloves, had instant access to numerous powerful tools via a hidden item spawner and started at a random department with access to that department and no drawbacks whatsoever. And there were like 5 of them.

How would the crew even cope? Might as well call the shuttle.
