### ISSUE TITLE
Safes have an inconsistent and lesser amount of items

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#22763]
This shouldn't be happening
Every map has a bunch of spawners for the safe, some are generous, but let's say the minimum is 5 spawners, all of them have guaranteed drops
3 items appeared once for the Defficiency vault safe
Less amount of items appeared occasionally, basically, not sure what's the cause, try to check for runtimes regarding the following spawners:

/obj/abstract/map/spawner/safe/any
/obj/abstract/map/spawner/safe/medical
/obj/abstract/map/spawner/safe/food
/obj/abstract/map/spawner/safe/weapon
/obj/abstract/map/spawner/safe/clothing
/obj/abstract/map/spawner/safe/medal

There is no real "safe" parent

**Comment by Kurfursten** [comment]
This is a feature. Safes are empty just like crates and spawners get mapped on them.

They were intentionally made inconsistent for variety.

**Comment by boy2mantwicethefam** [comment]
But the spawners are supposed to be guaranteed, which means at least 5-6 items (as long as it doesn't exceed the safe's w_class limit, which is hard to exceed 48 because just a huge thing is 5 and there are no gigantic items), I looked at the safe code and all items on the same tile as itself get moved into the safe when it's newly-made with no failure

**Comment by boy2mantwicethefam** [comment]
It appears to be a mapping problem, someone has mapped lower chances for certain things to spawn. I am going to rectify this because this was annoying to find, and if people want lower chances for things to happen they should make children of the spawners that are map-specific and then use those
