### ISSUE TITLE
Re-invent meteor or drop meteor.

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2276]
When meteor rounds start, people just jump to the teleporter and shill on the derelict for 45 minutes or some other z-level, There are around 3 or less people who stay and WE BUILD.

The shuttle comes regardless on how much the station is damaged, and usually that means "lol fuck you meteors hit the shuttle too".

tl;dr:Just give up. meteor is too laggy, and only a minority likes it. Complete rework or drop it.

**Comment by d3athrow** [comment]
This will be closed in 2 days if no furthur discussion is given.

**Comment by d3athrow** [comment]
Oh wow look at the time has it been 2 days already?
