### ISSUE TITLE
New robot law stating is spiffy but could use a change

### ISSUE THREAD

**Issue by Kitfox88** [d3athrow/vgstation13#22788]
#### Description of issue
When you state your laws you have a nifty little nanoui window so you can be a cheeky breeki and lie if need be, or leave some out. Unfortunately even if there's zero laws in a slot it's still selected to say by default so unless you take the time to click off a dozen+ laws you count to 20 over radio. Would be nice to have it changed so it only states lines that have a law in them by default but it's not a huge deal.

#### Difference between expected and actual behavior
To not shit up comms
Shitted up comms

#### Steps to reproduce
BORG STATE LAWS

#### Specific information for locating
Be a silicon I guess

#### Server revision
Game: 645fe1a653e7412dcd75129f12a8890491c2207f 
Patches: 7bb99370800d087bde7033c7457ff5ab5a43f4e1 

[easy] [qol] [ui] [tweak]

**Comment by press-mark** [comment]
oh hey i just made an issue about the exact thing in #22787

**Comment by Kitfox88** [comment]
herp derp dupe of #22787 
e: yeah i didn't think to refresh while writing this up
