### ISSUE TITLE
Suggestion: Make comms from your assigned department appear in bold text

### ISSUE THREAD

**Issue by ValkyrieSkies** [d3athrow/vgstation13#22796]
Comms can get very messy and it can be difficult to focus (ESPECIALLY for newer players), so for readability maybe it could be made that your assigned job's comms (:h) appear in bolded text to better catch your attention.

It's been extremely common lately that cyborgs haven't been responding to anything in binary chat and it's a very common complaint amongst regular new jobbies that they can't keep up with chat.

Making it toggle-able in preferences would be a fine impasse too for people who don't like such an idea, or hell, maybe give it a button in IC or OOC to allow you to change it to any other channel if your focus changes to some other channel, like a Captain dealing with a security situation.

[discussion]

**Comment by DrSnips** [comment]
I think the color is enough personally but binary chat is a bit tiny overall so a slightly bolder font on just that one would be nice.

**Comment by ValkyrieSkies** [comment]
If it were possible, we could switch to a different more distinct monospace font to make it clearer without losing that coder aesthetic, like https://en.wikipedia.org/wiki/Nimbus_Mono_L for example.

**Comment by SGuivenne** [comment]
Can we get a toggle for this if we choose to fuck off from our job?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Honestly I don't see the point, it's already all color coded
