### ISSUE TITLE
pAI names are missing \improper

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22792]
(WEB REPORT BY: burneddi REMOTE: 206.221.180.138:7777)
# Revision
2ab1e4064adad0e0dc69f36884921a1d31dead68

# Description
pAIs show up as "the pAI" if their name starts with a lowercase letter.

**Comment by ShiftyRail** [comment]
That's a feature, same goes for cyborgs explicitly so they can appear as `the robot`

**Comment by Exxion** [comment]
Giving them `\improper` would have the effect of *always* including the `the`
`\proper` is what would have the effect you're looking for

**Comment by beesil** [comment]
it's a feaaaature

**Comment by nervere** [comment]
Maybe a `\proper\` could be used in some places, but without a specific message that needs fixing, this isn't actionable.
