### ISSUE TITLE
Issue the revolution takeover centcomm warning once a certain number of crewmembers have been brainwashed.

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#22799]
Currently, the "IT IS REVS OH FUCK" announcement is displayed after half of the heads at the current moment are killed. I guess this change would actually put pressure on the revs if they get they numbers up too quickly and it would also give security/heads of staff time to get their shit together without realizing that they are 5 minutes away of getting fucked/losing.

[feature request]

**Comment by jknpj** [comment]
[apocalypse juke starts]

**Comment by DamianX** [comment]
Just let it be autoclosed eventually
