### ISSUE TITLE
Robotic limbs inherit damage of the human limbs

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#2280]
Appearently when you delimb a person and attach robot limbs those robot limbs inherit the exact damage and requires fixing afterwards. I did the surgery on a dead person so I am not sure if it applies to robotic limb attachment surgery done when the patient is alive.

http://imgur.com/mZyMkHP,5jZUAoW#1
http://imgur.com/mZyMkHP,5jZUAoW#0

^health scan results.

**Comment by d3athrow** [comment]
cannot reproduce.
