### ISSUE TITLE
Bomberman lag

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#22814]
Ghost can create bomberman arenas. Those arenas spawn in space. Walking in them will sometimes play that space.ogg that lags you like fuck as if you were actually in space.

**Comment by Exxion** [comment]
If your computer can't play a fucking ogg without lagging maybe it's time to let go

**Comment by ShiftyRail** [comment]
I will blame the ambiance subsystem

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
BYOND is not very good at playing 7mb OGGs, especially adminbus OGGs
Honestly just disable ambience and admin media they're both irredeemably shit

**Comment by west3436** [comment]
issue posted by a user with a Pentium 4 processor
