### ISSUE TITLE
Various reagents try to do special things to Vox, fail

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#2282]
Such as oxygen and inaprovaline.  

It appears that if(alien && alien == IS_VOX) is evaluating to false for /mob/living/carbon/human/vox.

**Comment by 9600bauds** [comment]
Can confirm. inaprovaline is supposed to act as some sort of Dexalin life-support analogue, removing toxin damage from oxygen:
>if(alien && alien == IS_VOX)
>	M.adjustToxLoss(REAGENTS_METABOLISM)
However sadly enough this doesn't actually work. There's a check for Diona for Bicaridine too, not sure if that works:
>if(alien != IS_DIONA)
>	M.heal_organ_damage(2*REM,0)
