### ISSUE TITLE
[Feature Request] Buffing Station Blueprints.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#22821]
[featurerequest]
Why are blue prints a traitor objective?
Does the syndicate want to help out agents by giving them the ability to rename rooms to "benis"?
It would possibly have some classified information about the station on it, what information about the stations equipment is classified and unknown? The colors of wires in machines.
Give the blueprints the ability to know what the wires of, airlocks, air alarms, APCs, cameras, and what ever machinery you want. Maybe not the vending machines and jukeboxes, those aren't NT property.

The CE shouldn't have to power game to find out the wires every round, and they are expected to help out in cases of a rogue AI. It would be up to the CE if they wanted to share the wires with their department.
It would also increase the value of the blueprints for antagonists outside of just being an objective. The hypospray is EXTREAMLY valuable to a traitor, even if it isn't their objective.

**Comment by jknpj** [comment]
Are you aware that they're the station's blueprints, not the machinery, right?

**Comment by FudgePucker** [comment]
Does a blueprint not contain information on wiring. Would be kinda difficult to install an airlock without knowing what color the hot and ground leads were? (yes I know that power is magical in this game and this is a stretch)

**Comment by Caboozles** [comment]
Even as a CE, I can’t give a shit if they’re stolen. It’s not useful in the slightest exept naming.

**Comment by SonixApache** [comment]
- >blueprints for a multi-dozen dollar space station that would expose all the safety hazards, health hazards, and cut corners
- >as well as showing where all the high-value targets are like the vault, captain's office, AI core, etc
- >not valuable

at least try to RP a bit

**Comment by Kitfox88** [comment]
/vg/station's a norp server at this point

**Comment by west3436** [comment]
Nothing productive has come from this
