### ISSUE TITLE
Cult sacrifice target can be sharded

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#22829]
By sharding I mean putting their soul into a gem and deleting the body, either with a gem or a gem sword.

There is no circumstance when you would want to shard the cult sacrifice target as a cultist. Sacrifice target should be prevented from being sharded in code.

Steps to reproduce:
1. Make a fancy sword with gem
2. Try to kill the sacrifice target
3. Sacrifice target is now in sword instead of being dead and ready for sacrifice

[Oversight]

**Comment by Killette2** [comment]
Whoops

**Comment by SonixApache** [comment]
cultists should just get a giant red glowing crosshair over the sac target that when examined says "DO NOT KILL OR MAIM OR OTHERWISE DESTROY THIS GUY WE NEED TO SACRIFICE HIM"
maybe it'll boost the winrate by 2%

**Comment by Killette2** [comment]
What about when the sacrifice is in disguise, should they be auto revealed?
