### ISSUE TITLE
Make Box Brig Gr8 Again

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#22822]
#### Description of issue
Over time the brig has become the sleazy Security powergamers plaything. The brig needs to be put back into the players' hands once again.

#### Difference between expected and actual behavior
You used to could have a good time in the brig, now you can only have a good time in the brig if you're a sec officer or someone with access.

I've included a picture with two simple changes which would greatly improve box brig.

![image](https://user-images.githubusercontent.com/6540760/57323648-2228fd00-70d4-11e9-8c3f-e395910493d6.png)

**Comment by Kharkov72** [comment]
🤔

**Comment by SonixApache** [comment]
I don't think anyone has ever broken out of perma by using the execution chamber, but the new execution chamber is ugly trash and I'd rather have the old one back.

Fuck replacing walls, just hack the door.

**Comment by nuklearcellphoneg** [comment]
Hacking the door or dealing with rwalls removes your ability to quickly make false walls without getting caught due to drawn out audio cues.

**Comment by Kurfursten** [comment]
Pretty sure we've had the syringe/bed execution room forever. Can't speak to the wall reinforcedness because that's such a minor detail. You got a year I could open up the map file for and see if it used to be like this as you say?

**Comment by SonixApache** [comment]
The walls were never unreinforced far as I can tell.
The old execution chamber is from before #21361.

**Comment by Kurfursten** [comment]
No, no, he's talking about a time when the *bed* execution chamber didn't exist, not the chair one

**Comment by nuklearcellphoneg** [comment]
> Pretty sure we've had the syringe/bed execution room forever. Can't speak to the wall reinforcedness because that's such a minor detail. You got a year I could open up the map file for and see if it used to be like this as you say?

Maybe 2015? I know 2013, or prior to the addition of the six trash can room-

http://ss13.moe/wiki/images/7/71/YE_OLDE_MAPPE%2Cjpeg.jpg

I'm fairly certain  there was a time when that room lacked them, my best guess would be 2015, but my memory could be running together.

As far as the execution chambers go, they were combined into one room west of main perma- this meant you could break into perma execution via the glass window, and gain access to the spray bottle, dexalin kit, and  more importantly, chloral to assist in breaking out.

**Comment by nuklearcellphoneg** [comment]
Enjoy this blurry img

![image](https://user-images.githubusercontent.com/6540760/57346070-33492c80-711b-11e9-9054-5fdc91eb2a00.png)

**Comment by Lokiamis** [comment]
I think I moved them to the smaller room in 2013-2014 to differentiate the two rooms when I powercreeped security. The good old days when escaping from perma was as simple as smashing the windows with a stool and just breaking into maint from space.

**Comment by SonixApache** [comment]
woah, i guess that's from before my time

**Comment by Probe1** [comment]
Does anyone think this should remain open?
