### ISSUE TITLE
blob icon got all fucked when it ate the ame

### ISSUE THREAD

**Issue by PaulRitter** [d3athrow/vgstation13#22839]
[bugfix]
![image](https://user-images.githubusercontent.com/16618384/57384147-540f9180-71b0-11e9-8c3b-33aba0b60599.png)

**Comment by PJB3005** [comment]
I'm pretty sure this is a feature.

**Comment by jknpj** [comment]
literally a feature

**Comment by Caboozles** [comment]
AME blob is a feature

**Comment by PaulRitter** [comment]
oh ok, nevermind then
