### ISSUE TITLE
pill crushing bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22838]
(WEB REPORT BY: rpaul REMOTE: 206.221.180.138:7777)
# Revision
94b242b9967393e8c384adcf9e80ccd35362bda3

if you crush pills into a container, it always says "the [container] is full" even if its empty/has space, but add then anyways

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Fixed
