### ISSUE TITLE
Water MUCH more lethal to greys than sacid is to humans

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#2283]
Namely, because water metabolizes at 1/20th speed and sacid doesn't, but the damage dealing code's the exact same.

**Comment by DeityLink** [comment]
sacid was never this harmful to humans. water is supposed to harm greys as much as Pacid harms humans.

**Comment by clusterfack** [comment]
So is this not a bug? Or what.

**Comment by DeityLink** [comment]
it's not.

**Comment by Aurx** [comment]
Preeeetty sure it's supposed to be an inversion between sacid and water for humans and greys.  
That's what I remember from the threads when it was hashed out.

**Comment by DeityLink** [comment]
pacid, not sacid, god damnit pay attention people

**Comment by Aurx** [comment]
Water for greys != pacid
Just look at the on_mob_life() and reaction_mob() effects of sacid, water, and pacid.  Water for greys is pretty much a copy/paste of sacid code.  NOT pacid code.  
The reason for the exceptional lethality of water to greys is, as I said way up there, due to a different metabolic rate for water.

**Comment by DeityLink** [comment]
b-buh muh showers of death
