### ISSUE TITLE
Vox don't use seperate uniform, hat, and glasses sprites.

### ISSUE THREAD

**Issue by oversane** [d3athrow/vgstation13#22844]
#### Description of issue
They only use default human ones. Para and Bay are one step ahead of us. I know we have pressure suits but come on.

#### Steps to reproduce
Wear a uniform as Vox.

**Comment by oversane** [comment]
Turns out they do have their own sprites, but don't use them, t-thanks c*ders.

**Comment by MadmanMartian** [comment]
They should be using them

**Comment by oversane** [comment]
> They should be using them

I spoke about this on the Discord. It might be with one of your pull requests, #22049.
If you're there, check code-map-sprite.

**Comment by Exxion** [comment]
So was that PR tested? Because this certainly used to work
