### ISSUE TITLE
Docking port part of emergency shuttle moving?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22857]
(WEB REPORT BY: sovietago REMOTE: 206.221.180.138:7777)
# Revision
b8890d2f719ef026a1309ce5d6df10a563d0dd34

# Description
Docking port arrow present on emergency shuttle while in transit
# Steps to Reproduce
escape on shuttle on deficiency station
# What you Expected
no random arrow in space
# What Actually Happened
arrow in space marked Docking Port

**Comment by Exxion** [comment]
Yes, that's how shuttles work
Ghosts can see them
Assuming you were a ghost, this is normal
