### ISSUE TITLE
Make some weapons spawn with flashlights attached by default?

### ISSUE THREAD

**Issue by DDihanov** [d3athrow/vgstation13#22854]
[qol][discussion]

Maybe like sec tasers in the lockers and weapons in the armory?

What do you think?

**Comment by SonixApache** [comment]
i think powercreep has come a long way

**Comment by DDihanov** [comment]
It's just flashlights dood. It would look cool and wouldn't add that much more power to sec.

**Comment by SonixApache** [comment]
Helmet lights are a pretty recent powercreep. Before that, officers just had to keep a flashlight in one of their pockets if they wanted to be able to see in the dark.

**Comment by DDihanov** [comment]
Doesn't it make sense for officers to have a flashlight attached to their gun?

**Comment by yclatious** [comment]
Fuck off with the Tee Gay tacticool niggershit. Keep a flashlight in your helmet, in your pants pocket or implanted in your ass, do not sully the perfection of the Las rifle sprite with some fucking awfull sec lite wanabee garbage.

No scopes, no flashlights, no rail garbage. Keep ti bloody simple, you utter numpty.

**Comment by DDihanov** [comment]
> Fuck off with the Tee Gay tacticool niggershit. Keep a flashlight in your helmet, in your pants pocket or implanted in your ass, do not sully the perfection of the Las rifle sprite with some fucking awfull sec lite wanabee garbage.
> 
> No scopes, no flashlights, no rail garbage. Keep ti bloody simple, you utter numpty.

Hey why are you so upset? I was just asking for opinions.

**Comment by SonixApache** [comment]
Ignore yclat, he's a fag.
Honestly, I think being able to attach your taclight to a gun would be pretty fun. Just worried about powercreep.
