### ISSUE TITLE
[Feature request] Separate "hear streamed media" toggles for different machinery

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#22888]
[featurerequest]
An unfortunately long time ago the jukebox was the only source of streamed music, this made it quite the central piece of the bar and became an iconic feature of it. If you wanted to hear assorted music you went to the bar and if you did not want that you just had to toggle streamed media off
Then a bald, angry coder added those garbage sound systems everywhere and that meant the player hearing loud shitty anime music everywhere on the station that reset every few seconds as they moved through rooms for most rounds. This meant that a player had to either manually turn every single sound system off, often ending in others repairing them, or muting streamed media altogether, bar included.

This is really the only request here: that sound systems have a separate toggle for hearing their media in the player options so one can mute them but not the classic juke at the bar. At least not without having to do it every round or whenever they remember it.
A toggle for the intrusive shuttle music would also be nice but then that comes from an invisible jukebox if I'm not mistaken.
Just dropping this suggestion to be ignored as it has been for years before I forget about the music I have muted ages ago again.

**Comment by Hoshi-chan** [comment]
Feature loss. Hooking the emagged juke up to the sound system with scotland forever on loop is a feature.

**Comment by SonixApache** [comment]
I generally keep byond at 1% volume because of the loud-ass media nonsense.

**Comment by Gringonius** [comment]
and the new juke selection is shit, nevermind

**Comment by Kharkov72** [comment]
😂

**Comment by Gringonius** [comment]
:persevere:
