### ISSUE TITLE
Doing a resist when in cuffs stuns you out of movement

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22887]
(WEB REPORT BY: ktvii REMOTE: 206.221.180.138:7777)
# Revision
4541fb658f1b01a9a8925a599a6e0178b83b287a

# Description
When you resist in order to take your cuffs off and you try to move, you are unable to move for first 3-4 seconds. What fucking c*der designed this? It's already bad enough that cuff removals are announced.
# Steps to Reproduce
Get cuffed and try to resist faggot.
# What you Expected
I'm removing cuffs from my fucking wrists why are my legs not working STOP
# What Actually Happened
MY LEGS ARE BROKEN

**Comment by boy2mantwicethefam** [comment]
Sorry

**Comment by jknpj** [comment]
>wants silent mobile cuff removal

:thinking:

**Comment by boy2mantwicethefam** [comment]
Cringe
What actually happens is that after resisting out of something if it was fast enough you can't move for a while and that's because of a delay in restraint code

**Comment by jknpj** [comment]
https://github.com/vgstation-coders/vgstation13/blob/1bdd3700451228d07e4109b142a1185a288c6cea/code/modules/mob/living/living.dm#L1111

still not a bug

**Comment by SirSkeleto** [comment]
it's stupid
moving still interrupts it
this just makes it really finnicky

**Comment by PaulRitter** [comment]
well it prevents shit like
unbuckle -> sec runs towards you -> speed off -> try to unbuckle again

imo buckles should restrain people and disrupt the manipulation capabilities, and thats exactly what this is doing

**Comment by SirSkeleto** [comment]
is that the way it should be though?
no, imo

**Comment by DeityLink** [comment]
I think it's fine as it is though, for the reasons mentioned above by Paul and jknpj

**Comment by west3436** [comment]
Feature
