### ISSUE TITLE
Limb issues

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#2288]
So, there was this catbeast changeling clown, and I made it my mission to remove every one of his limbs.

And I did! Head, left arm, left hand, right arm, right hand, left foot, left leg, right foot, right leg. I removed every single piece and displayed him in the chapel!

The problem was, his sprite and description didn't update to reflect this fact, even with all of his limbs sitting in a pile around him, it didn't say he was missing them, except when I tried cutting them off again.

![http://puu.sh/dC3AS/2f086360ea.png](http://puu.sh/dC3AS/2f086360ea.png)

![http://puu.sh/dC3C6/f6fdab0945.png](http://puu.sh/dC3C6/f6fdab0945.png)

**Comment by d3athrow** [comment]
![ok](http://i.imgur.com/SSlOHD5.png)
