### ISSUE TITLE
The hyperspectral Imager report doesn't load the image correctly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22896]
(WEB REPORT BY: mentgah REMOTE: 206.221.180.138:7777)
# Revision
02e31c5048997e5d157bbb65008a64e35fb0cdf2

# Description
The hyperspectral imager doesn't work, it just displays an X in place of the image it's supposed to display.
# Steps to Reproduce
Put a sample analysis in the hyperspectral imager and read the report
# What you Expected
The admins told me that it should display a graph.
# What Actually Happened
It doesn't load correctly / displays an X

**Comment by west3436** [comment]
Ancient xenoarch machines are no longer required, mapped in, or supported
