### ISSUE TITLE
Mind swapping a vampire while being a wizard doesn't turn you into a vampire wizard

### ISSUE THREAD

**Issue by god-jesus** [d3athrow/vgstation13#22895]
#### Description of issue
Using the mind swap spell on a vampire does keeps your wizard powers, but does not give you vampire powers. I think they should be tied to the body. 

#### Difference between expected and actual behavior
Expected to be wizvamp. Ended up just a wiz. Other guy still had vamp powers iirc.

#### Steps to reproduce
Be a wizard. Find a vampire. Mind swap him.

#### Length of time in which bug has been known to occur
I have no idea

**Comment by ShiftyRail** [comment]
I'd say it's fair

**Comment by god-jesus** [comment]
Muh realism and/or consistency. Don't think it makes sense to transfer vamp powers from body to body like that.

**Comment by SirSkeleto** [comment]
in a game where cloning is a thing, i think it's fair to say that your "soul" or w/e is what makes the magic, not biology

**Comment by strawberrytan** [comment]
before dynamic mode, you could bodyjack captured wizards for their powers

**Comment by ShiftyRail** [comment]
You still can, you simply need to defib rather than use the cloner.

**Comment by strawberrytan** [comment]
That was what I always did, I guess I can try again some time in the future

That was the reason intact wizards were important

**Comment by west3436** [comment]
Feature
