### ISSUE TITLE
Head Transplant on Suicided Body Prevents Cloning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22891]
(WEB REPORT BY: entya REMOTE: 206.221.180.138:7777)
# Revision
c3823fba27118f8201df5fc85931e360fc337403

# Description
When a head is transplanted onto a body that has been suicided, it prevents the transplant recipient from being cloned. 
# Steps to Reproduce

# What you Expected
To be able to be cloned
# What Actually Happened
I wasn't as the body's previous owner suicided and as a result the doctor that did the transplant left me at the cloner.
# Thoughts

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Suicide is stored in the chest

**Comment by brndd** [comment]
Maybe suicide shouldn't make you uncloneable in the first place. If you suicide and don't want to be cloned, you'll probably be MiF by the time someone tries to clone you. If you're not MiF, you can just ignore the cloner prompt, annoying as though it is.
