### ISSUE TITLE
You can explode plasma lights from beyond the grave

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#22897]
- 1)Be Traitor

- 2)Emag a light replacer

- 3)Turn off the light switch of a room and replace the tubes/bulb with replacer

- 4)Die because any reason

- 5)Ghost and go back to that room

- 6)Click on the lightswitch again

- 7)Antagonize from beyond the grave

By the way, this also meas that any ghost/observer can cuck the person placing plasma lights by just switching the lights when he replaces them with plasma ones.

[oversight][loose]

**Comment by boy2mantwicethefam** [comment]
Good

**Comment by Allspice** [comment]
Sounds like emergent gameplay to me breh

**Comment by Killette2** [comment]
Now if only someone would do this, as nobody has done this in the many years it was possible

**Comment by Coxswain-Navigator** [comment]
I think the main reason nobody has done this is because nobody is willing to risk getting killed by ghosts. At least, that's the reason I've never done it.

**Comment by Kitfox88** [comment]
how often do people emag light replacers anyway? ghosts flicking lights off constantly sucks anyway, limit their dead asses to spookin' and flickerin'

**Comment by Kurfursten** [comment]
I actually have seen this done before but it was many years ago

Took us 30 minutes to figure out what the hell was blowing up crewmen, we kept assuming it was the janitor signs

Good shift

**Comment by PaulRitter** [comment]
spooked ya

**Comment by west3436** [comment]
the coder cabal has deemed this a Certified Feature:tm:
