### ISSUE TITLE
[Feature Loss] Diona lacks dexterity to vent crawl?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22900]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
43d8c3d3c30457234b5a8209203659655bf62150

# Description
Doubleclicking on airvents dont work anymore.
# Steps to Reproduce

Be diona, Doubleclick on air vent
# What you Expected

To begin entering the vent
# What Actually Happened

You don't have the dexterity to do this

**Comment by brndd** [comment]
You ventcrawl by alt-clicking. Doubleclicking to ventcrawl has never been a thing on /vg/station to my knowledge.
