### ISSUE TITLE
Changelog PR fuckery has broken changelog updating

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#22919]
@Intigracy @I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE 
Just so you know this changelog fuckery in https://github.com/vgstation-coders/vgstation13/pull/22909 screwed up changelogs for my PR https://github.com/vgstation-coders/vgstation13/pull/22859 and https://github.com/vgstation-coders/vgstation13/pull/22852 and https://github.com/vgstation-coders/vgstation13/pull/22861 because none of them show up ingame at all
Every PR after this one was merged has had broken changelogs, it seems.

![broken](https://user-images.githubusercontent.com/6062247/57649362-e29f5c80-757c-11e9-96ac-34ade6127abe.png)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Not again
I didn't even use special characters in the message
@PJB3005

**Comment by Kharkov72** [comment]
Oh god, oh fuck.

**Comment by PJB3005** [comment]
Manually fixed the changelogs.

If it happens a third time I'm actually gonna go investigating on this. Last time I chalked it up to GitHub hiccuping.

**Comment by Exxion** [comment]
Reopen if it isn't fixed, then
