### ISSUE TITLE
Unpopular Bundle

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#22912]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE said "when you feature request it" a lot so here we go

There should be a bundle that gives you a box with the 10 least popular non-job traitor items (even if they wouldn't fit in a box, so they can't go back in). Least popular would be determined automatically with persistence and stat tracking. So for example, based on his last gathered stats, that would be

uplink implant: seen in 6 out of 1606 traitors
inflatable decoy: seen in 6 out of 1606 traitors
trophy-belt: seen in 7 out of 1606 traitors
instant smoke bombs: seen in 9 out of 1606 traitors
bug detector & camera disabler: seen in 9 out of 1606 traitors
quick vent jumpsuit: seen in 9 out of 1606 traitors
compressed matter implant: seen in 9 out of 1606 traitors
explosive chewing gum: seen in 9 out of 1606 traitors
syndicate balloon: seen in 10 out of 1606 traitors
suspicious looking toolbox: seen in 11 out of 1606 traitors

**Comment by ghost** [comment]
Syndicate bundles are already trash most of the time, why would you want to introduce one that is deliberately bad?

**Comment by boy2mantwicethefam** [comment]
Maybe they should be better

**Comment by Caboozles** [comment]
Getting a lot of bad items could be fun.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I mean
It's definitely an idea
But I don't really like this idea

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I'd rather add something that says "if an uplink item hasn't been purchased in 20 rounds you get it 50% off"
But I'm probably not gonna code it

**Comment by SGuivenne** [comment]
Syndicate Balloon is, has, and always will be a meme pick by Traitors.  Its not intended to be a popular traitor item seeing as its literally a balloon that says "HEY, IM A TRAITOR".
