### ISSUE TITLE
Staff of change can turn you into a manifested person, manifested people cannot be staff of changed

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#22918]
Pretty much what the title says. seems like an oversight because if a wizard turns someone into a manifest human via the random change option, then they can't turn them into anything else from there on, they basically get 'stuck'.

**Comment by boy2mantwicethefam** [comment]
Incredible

**Comment by PaulRitter** [comment]
blessed

**Comment by Arthurdentist** [comment]
also keep in mind manifested people turn into ash on death, which is irreversible as well

**Comment by PaulRitter** [comment]
blessed x2

**Comment by SonixApache** [comment]
the oversight is non-wizards being able to use the staff

**Comment by jknpj** [comment]
another reason to not use blacklists

**Comment by Lunstra** [comment]
more like another reason the staff of change is a garbage item that should never have been taken off the adminspawn only list.
