### ISSUE TITLE
block injectors dont work

### ISSUE THREAD

**Issue by chesse20** [d3athrow/vgstation13#22928]
#### Description of issue
i put one mutation into a block injector and expect one mutation

#### Difference between expected and actual behavior
i get every mutation at once

#### Steps to reproduce
make a bunch of mutations and try and make a block injector

#### Server revision

e843a4e0b54eadd592ee40a326a096c8d43ffcde 
<!-- SELF LABEL YOUR ISSUE TODAY!

<bug>

**Comment by PJB3005** [comment]
This is completely possible behavior due to how the genetics system works. Ryetalyn does not reset your SE, it simply disables all mutations. Next time you use an injector it re-checks and re-activates everything.
