### ISSUE TITLE
when getting smashed to death sometimes mommis will just disappear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22938]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
c9bd418a99f4692633338fc502d8f90a05560520

# Description
only seen it happen twice both with posibrain mommis, but its more than just null spacing, the thing can scream but cant be teleported out
cant be seen on alt click but teleporting to it leads to where it got smashed/where you teleported it

**Comment by ghost** [comment]
I've experienced this too. When this happens and the posibrain speaks, you can click on the chatbubble when standing next to it to pick it up. It will be invisible in your hand. You can then click on a machine-man interface (the artificial brain from NT tech) and it will be normally put in.

**Comment by ShiftyRail** [comment]
Most likely an invalid icon_state

**Comment by Exxion** [comment]
Sounds more like a failed qdel

**Comment by FudgePucker** [comment]
I have seen this happen too, the singularity ate the other MoMMI, but he could still talk over damage control, so he was still a MoMMI and not a possibrain
