### ISSUE TITLE
Closets call initialize() twice under certain circumstances

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#22933]
First on https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/objects/structures/crates_lockers/closets.dm#L41

And then on https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/objects/structures/crates_lockers/closets.dm#L74

There are no checks in place to prevent the second call, resulting in duplicate items.

[easy][bugfix]

**Comment by ShiftyRail** [comment]
I'm not sure if this is actually the cause of duplicated items in closets, as those are not reliable reproducable.

**Comment by ghost** [comment]
It may not be that particular proc for map elements, however the initialize itself has no checks whether it was already called and you can clearly see that a `new`ly created closet that has `spawned_by_map_element` proc called will have initialize called twice.

**Comment by ShiftyRail** [comment]
Setting a hard "has already been initialised" flag to a locker looks like a ill-advised solution with possible unforseen consequences

The only scenario I can see this happen is
```
Vault is loaded => spawns its map elements => objects subsystem is called => re-intialises the lockers
```
Which isn't the bug that we observe on live

**Comment by SonixApache** [comment]
#20766

**Comment by ghost** [comment]
@ShiftyRail

What do you mean unforseen consequences? Something somewhere manages to call `initialize` twice on some lockers. At the very least a runtime should be produced when a second `initialize` is called on lockers so the problem can be traced further.

Same principle should be applied to `/proc/equip_wizard` for wizards receiving duplicate books. Without logging it's stabbing in the dark.

**Comment by jknpj** [comment]
There's an easy way to get runtimes, at least for lockers, just remove libvg:

```Runtime in utf8.dm,24: Unable to load library ./libvg.so
  proc name: utf8 sanitize (/proc/utf8_sanitize)
  src: null
  call stack:
  utf8 sanitize("Medical DEPT", null, 22)
  the Medical Account debit card (/obj/item/weapon/card/debit/preferred/department/medical): change authorized name("Medical DEPT")
  the Medical Account debit card (/obj/item/weapon/card/debit/preferred/department/medical): set department account("Medical")
  the Medical Account debit card (/obj/item/weapon/card/debit/preferred/department/medical): New(Chief Medical Officer\'s Locke... (/obj/structure/closet/secure_closet/CMO), "Medical", null)
  the Medical Account debit card (/obj/item/weapon/card/debit/preferred/department/medical): New(Chief Medical Officer\'s Locke... (/obj/structure/closet/secure_closet/CMO), "Medical", null)
  Chief Medical Officer\'s Locke... (/obj/structure/closet/secure_closet/CMO): spawn contents()
  Chief Medical Officer\'s Locke... (/obj/structure/closet/secure_closet/CMO): initialize()
  Objects (/datum/subsystem/obj): Initialize(478111)
  Master (/datum/controller/master): Setup()

**Comment by ghost** [comment]
@jknpj

What I meant was that lockers should force a runtime (they do not currently) whenever their proc for item spawning is called a second time, so we know how it is being called.

**Comment by jknpj** [comment]
Oh, i see.
