### ISSUE TITLE
Suggestion: shuttle call logs

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#22943]
Perhaps it would be nice to have a log, accesible ICly on comms consoles, of shuttle calls/recalls with :
- reason for calling
- ID used for authorisation
- time of the call/recall
- location of the console used

Would help with recall spam that can plague rounds.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Dunno about the ID used but at the very very least we should have the location of the last call/recall to have a counter to zoo consoles and shit.

Doing this for AI uploads would be great too.

**Comment by ShiftyRail** [comment]
#23136

**Comment by toomykins** [comment]
>Doing this for AI uploads would be great too.

Logging law changes IC may end up giving you a huge fucking list of laws, as people tend to spam the boards on the pc.
