### ISSUE TITLE
I ded please nerf Blink

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22946]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
cc0f7ef19168e7e1bc1a898b17e473c22fb96f69

# Description

Holy shit at least make it you can't just blink lube spam, its cancer and the way lube works means that you cant outrace the lube to get to the wizard even.

**Comment by Coxswain-Navigator** [comment]
"no"
