### ISSUE TITLE
make all traitors button doesnt give the traitors their PDA code

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22940]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
c9bd418a99f4692633338fc502d8f90a05560520

# Description
as says on tin

**Comment by iFlashYou** [comment]
To add: it does not even give them any notes

**Comment by ShiftyRail** [comment]
Fucking `Greet()` proc

**Comment by DDihanov** [comment]
`Greet()` proc didndu noffin wrong.
