### ISSUE TITLE
Emagging sec items ideas(emag buff)

### ISSUE THREAD

**Issue by DDihanov** [d3athrow/vgstation13#22955]
[discussion]

I would be up to make some new additions to the emag but I thought I can get some opinions:

* Emagging a taser gun stuns the user, sparks fly everywhere, user gets knocked down and takes some damage.(kinda like electrocution)

* Emagging an ~~laser gun~~ egun(and here is where there are several options):
   * Just stuns the user on use, regardless of the mode it's on(like the taser gun)
   * Stuns the user if it's set on blue, explodes in the hands of the user if set to kill
   * Alternatively emagging an egun ~~laser gun~~ unlocks a third(purple) mode, which makes it expend all            ammo at once, but fires a big projectile that has an AOE effect.

* Emagging a stun baton can have the same effect as the taser, stunning it's user on use

* Emagging a flashbang can make it explode immediately?

All those can be also replaced with a chance for the item to malfunction.

**Comment by boy2mantwicethefam** [comment]
Emagging for equipment sabotage is not a good thing when there's almost never a window of opportunity to do so

**Comment by boy2mantwicethefam** [comment]
Here's this for an idea: If you attack someone with an emag, you covertly swipe them and it emags a random thing on them if they have any emaggable things, it can be feasibly done

**Comment by DDihanov** [comment]
Well if somebody was to sneak into sec or if sec gets totally fucked like some rounds, you can easily emag everything. But I also like your idea too.

**Comment by DrSnips** [comment]
Sec is either super full or super dead with it leaning to the dead side most often. An emag is basicly all access and is near instant so we often end up with emagged-everything-station if the person with it is in the mood.
If the department isn't staffed round start a person can permanently screw everything. You could say the same right now with stealing but stealing requires inventory space and time while the emag is instant and can just have a click macro to sweep items.
I'm also against it because we keep treating the emag like a magic ticket that can do anything with an ever fixed cost that you can buy multiple(~3) of.

**Comment by Kurfursten** [comment]
>calling an egun a "laser gun"

That's a different item reeee

**Comment by DDihanov** [comment]
> > calling an egun a "laser gun"
> 
> That's a different item reeee

Fixed it SPECIALLY for you.

**Comment by Caboozles** [comment]
Do we really need more buffs for an emag?

**Comment by DDihanov** [comment]
Maybe not - that's why it's a discussion.

**Comment by SonixApache** [comment]
lock tasers and laser guns to IDs with security access to compensate

**Comment by DDihanov** [comment]
Hmm sounds interesting. Wouldn't this be a meta-changing thing though?

**Comment by SirSkeleto** [comment]
he's a sec metaclubber
don't listen to his drivel

**Comment by SonixApache** [comment]
it was somewhat of a joke
emags are generaully used to bypass ID locks
for some reason they're also used to bypass safety features or access 'hidden' features

making guns just lolexplode without anything to compensate for it is pretty shit
the AoE magdump thing is a good example of decent trade-offs

imo emags are already way too powerful and gay

**Comment by FudgePucker** [comment]
The ability to make a one time use emag using a charged capacitor and wires on a ID when?

**Comment by kilozombie** [comment]
Remember when emags had like 4 uses and did barely anything
There has to be some kind of happy medium between "opens every door and converts every item/machine into a deathtrap or weapon" and "panic button for prying open an airlock a couple times i guess"

**Comment by DDihanov** [comment]
Swiping somebody with emag EMPing his items - too OP?

**Comment by SonixApache** [comment]
OtherCode™ had the option to swipe someone's robo-limbs to emag them. That's one feature I wish we had.

Swiping someone to EMP them is a bit over the top, the emag doesn't normally have any EMP abilities. We have that EMP flashlight for that.

**Comment by FudgePucker** [comment]
Emag is just a feature sink.
