### ISSUE TITLE
Anitbody injecitons, Disease Splicer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22974]
(WEB REPORT BY: mcgstyle REMOTE: 206.221.180.138:7777)
# Revision
1ee89f95dfe4a866fae803311d3f423faaa26910

# Description
Regardless of map, Disease splicer not working (Roid, Box tested). Transfer of antibodies not working.
# Steps to Reproduce
Create Antibodies from Monkey as usual, inject yourself with them
# What you Expected
I'd get the monkey's antibodies into my system
# What Actually Happened
Unable to detect antibodies

**Comment by DeityLink** [comment]
Fixed by #23461
