### ISSUE TITLE
Disease Splicer on Roid is borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22973]
(WEB REPORT BY: mcgstyle REMOTE: 206.221.180.138:7777)
# Revision
1ee89f95dfe4a866fae803311d3f423faaa26910

# Description
Viro Disease Splicer shows empty NanoUI window
# Steps to Reproduce
Play Viro on Asteroid Station
# What you Expected
Spilce diseases as usual
# What Actually Happened
The Window loaded only the background

**Comment by DeityLink** [comment]
duplicate of #26957
the usual Nano UI bug
