### ISSUE TITLE
Remains are layered behind everything

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#22987]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
051f2ae5720203ea52878cfe311007421044b048

# Description
Remains spawned by ashing or cult or whatever hide behind shit like floor scrubbers and graffiti
# Steps to Reproduce
Find remains
put crayon rune down or pull on top of floor layer stuff
# What you Expected
bones on top of shit embedded in floor
# What Actually Happened
bones underneath

**Comment by SGuivenne** [comment]
also great for ""stealth"" shards
