### ISSUE TITLE
Mature vampire vision sucks

### ISSUE THREAD

**Issue by SirSkeleto** [d3athrow/vgstation13#22998]
#### Description of issue

It's worse x-ray vision and usually just shittier than staying at 300 blood

#### Difference between expected and actual behavior

\>play darkness based antag
\>lose the ability to see where darkness is
\>also everything is ugly as fuck now too lol

#### Steps to reproduce

hit 400 blood, weep

#### Specific information for locating

vamp_mature

#### Length of time in which bug has been known to occur

beats me

#### Server revision

current

i think the xray mutation does this in a not terrible way? should be an easy fix

**Comment by Accipitermaris** [comment]
xray mutation + catbeast dark vision is superior yeah, it lets you see every tile while also seeing what is dark
its possible to brute force exactly this as a vamp by wearing sechuds + have mature vision. havent tested it with sunglasses or other items that reduce darkvision range

**Comment by Killette2** [comment]
I've also been annoyed at this

**Comment by SonixApache** [comment]
should just be a toggle

**Comment by robintime** [comment]
#13561
