### ISSUE TITLE
Mechs are absolutely fucking useless now

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#22993]
# Revision
5816b71bc3d3945b185175e357870da987ccf34e

>Man looks at a mech
>Suddenly pilot is ejected fucking randomly

So mechs are just completely worthless now, very epic!
It may just be harm intenting a mech, it may be hitting a mech, but all I know is that I was hit by a toolbox in a clarke and suddenly whoops I have radical larried outside the mech.

[bugfix]

**Comment by Kurfursten** [comment]
Did you get memed by an electropack?
Was your mech in maintenance mode?

**Comment by Kharkov72** [comment]
No.
No, it didn't even have maintenance mode turned on.

**Comment by Kurfursten** [comment]
If you're not occupied, log in and I'll test it with you. This report you've made is -- sincerely no offense -- pretty worthless. Could not reproduce on live, tried both hitting with open hand and toolbox in all intents.
