### ISSUE TITLE
New Antagonist - Psionic (Will code myself)

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#22990]
This post is here for two reasons:
- To survey interest in the idea.
- To help balance and come up with new ideas if there is interest.
I would like to clarify that this isn't just meaningless "Ideaguying", as seems to be so common throughout open source projects. It's my intention to do this all myself if needed. I lack significant experience with BYOND, but having several years of programming experience tells me that it'll take like 6 months tops. I'm a lazy fuck.

Here's my philosophy on what creates a good antagonist:
- Interactive, meaning that there are many avenues of action one can take. Some can be gimmicky, but not they don't all have to be.
- Entertaining for both sides most of the time. It can't be perfect but as an example, stunning somebody then taking them to a derelict room to suck their blood and then space their body is NOT very fun for the victim. On the other hand, being converted to a cultist or soul-gemmed into a construct is okay.
- Brings something to the table that other antags don't have. >muh ling vs vampire discussions
- Creates interesting situations AKA spices things up

### THE PSIONIC
Psionics are men (femstatics) with the power to manipulate the world around them using only their mind. They spawn in at roundstart only, similar to vampires. However, they are considered human for Asiimov purposes.

### ABILITIES
Psionics, similar to changeling, get to use their Psi-points (name pending) to go down one of many branches of abilities. They are not locked into one single branch. Focusing upon a branch allows for stronger abilities, whereas spreading out points allows for more versatility. I currently have no concept on how to gain Psi-points, but my best idea right now involves channeling mental power from other players, a process which leaves them unharmed. 

Every ability has a 1 second cooldown. Instead of an enforced cooldown, every psionic has a 100 Psi-power reserve (name also pending). Every ability will use from this reserve, and using abilities after it is empty will result in massive penalties. See the section below for the proposed penalties. Psi-power is recharged over time, about 10 points per minute. There are other ways to recharge it as well.

**Push**
_“The brain is a muscle that can move the world.” - Stephen King, the author who also came up with the push._
Costs: 80 
The Push is a targeted, single-tile ability with a range of 5 tiles. Can only be used on sentient creatures. Upon use, the target will enter a state in which it cannot move or act, but will still be able to see and hear around them. This pre-trance state lasts 30 seconds or until the psionic uses the "Begin Push" spell on the target. 
During this pre-trance, the psionic can give verbal instructions that must be followed by the victim. The trance then lasts for 2 minutes following the activity. For instance:

- Psionic: You will bring me a gun from the armory.
- HoS: I will do that.

Trance begins, he gets a gun from the armory. The HoS is still able to alert the sec team during and after the trance that he's being forced to get a gun, so better yet:
- Psionic: You will bring me a gun from the armory. You will tell nobody else but me about this, and you will forget this event after the trance ends.
- HoS: I will do that.

Trance begins, but let's say the HoS doesn't manage to get the gun in 2 minutes due to the warden stopping him. Once it ends, he is forced to "forget about it" and act as if he forgot his intention

Keep in mind that psionic powers aren't perfect and neither is RP. There will always be bias. This is a feature(tm). Gameplay-wise, you need to act as if you think nothing is wrong. But you and I both know that we'll end up checking security cameras around that person.

So more instructions, the better. However, the more complex the instruction is the greater chance there is of fucking somebody's brain up. This is measured by both length of words and number of words. When someone's brain is fucked up, they will begin to mutter to themselves and have increasingly worse psychotic conditions. This will be an obvious tell to get that person treatment. Treatment would involve a drug or something.

I see potential issues with RP (what if you're new and get pushed?), so there would be massive red text guiding you on how to obey this person. In addition, you probably don't want to push an idiot. Deliberately taking your time to finish an objective may also be an issue, so most requests would probably be for simple stuff like "giving all access" or "open this door".

**Fire branch**
This branch is the more murderboney side of spells. Burst out those foam extinguishers.

**1 - Ignite**
_You feel hot._
Cost: 20 Psi-power, 5 Psi-points to learn. Targeted spell, 5 tile radius, will set anything flammable on fire. Alive units will have their body heat raised a fair bit to make the burn damage start faster. Can also be used on walls similar to thermite, but requires 15 seconds of concentration and adjacency.

**2 - Firestarter**
_The flames grow brighter._
Passive, 12 Psi-points to learn. Makes you immune to fire. In addition, ignite now affects a 3x3 radius around the target. The thermite effect is now placed on a wall within range and takes 15 seconds to effect, channeling not required.

**3 - Exothermic Scar**
_Your fire spreads with little regard._
Cost: 30 Psi-power, costs 18 Psi-points to learn. Targeted. 3 tile radius. Instantly scorches off an arm and raises body temperature. If there are no arms, it will target a leg instead. If the target is a nugget, nothing happens and no points are spent.

**4 - Oblivion (rawr)**
_Your fire cannot be stopped._
Cost: 90 Psi-power, costs 25 Psi-points to learn. Untargeted. This spell turns the air in your room to a scorching 300C and sets everything on fire that can be on fire. Any living targets in that room are stunned for 3 seconds. You also get some hyperzine/tricordrazine pumped into your system.
In addition, this also makes the thermite effect take 3 seconds.

**Psi Branch**
Upgrades the Push and gives other neat abilities for mind games.

**1 - Telekinesis**
_The world speaks out to you._
Passive, 5 Psi-points to learn. Targeted spell, global radius (so, within sight). I'm still debating on how to go about this one - it'll definitely involve reworking telekinesis to some extent, but I'm unsure on whether I want to remove genetics' version or what. 

**2 - Mirror**
_Vision is a detached screen._
Cost: 40 Psi-power, 7 Psi-points to learn. Permanently changes any item in sight to be another. Still working out the selection method. In addition, you will be able to mimic someone's else's form and voice (similar to polymorph). If mirror is used again, you will revert to your normal state.

**3 - Mindgames**
_The human mind reveals itself._
Passive, 20 Psi-points to learn. Push's cost is reduced to 70 Psi-power and the trance state will last 3 minutes more. You gain X-ray vision and can read minds now (genetics mutations). Using push again during a trance or pre-trance state will make them permanently bound to your will. This will make you sick, assuming you're at full power.

**4 - Psychic Domination**
_Your brain throbs with the universe._
Cost: 150 Psi-power, 25 Psi-points to learn. Untargeted. All people in vision range are pushed. Any commands given will go to all people at once. This push lasts only 20 seconds. 
Cost: 30 Psi-power. Secondary ability, active and untargeted. Gives all nearby people hallucinations and blurred vision, effective immediately.

### PENALTIES
Remember that Psi-power recharges over time, meaning you will go through all the stages below a given deficit. You will also get the penalties of the previous stages. Penalties are as follows:
20 points:
- Blurred vision
- Shaking
- Flavor messages
40 points:
- Vomiting
- Slowed movement
- Flavor messages
80 points:
- Loss of consciousness after 10 seconds, lasting until the stage is over.
120 points or more:
- Severe brain hemorrhaging, resulting in death 1-2 seconds after casting the spell.

### GOAL
Obtain enough Psi-points to transcend, giving you an ultimate form where you get a bonus 20 psi-points, stun immunity, and a shiny body. At this point you can do whatever you want, whether it become a Buddha or kill everybody.

### ENDING THOUGHTS
There's a lot of ideas here and the final concept would have a lot more spells to work with. All these numbers are arbitrary, pulled straight from my ass, and a lot of spell ideas were put there just for substance. I personally think it's a neat idea, but that's just my opinion. Any feedback will be appreciated.

**Comment by Caboozles** [comment]
I don’t like the idea of a “roleplay” ability. You’ll always get someone who gently times the 2 minutes to laser you in the face. And people will inevitably just turn it into a “shoot yourself *ahelp he didn’t kill himself”

Turn it into a randomly timed thrall effect that the psionic knows but not the victim, or maybe even just have them do it until their task is completed or a timeout.
And obviously make it so that the victim can resist extreme tasks.

As is I find the idea more interesting than the current abilities. A non-lethal antag that more causes shenanigans for those around them sounds great.
Maybe make it that their continued presence causes issues somehow? Like a passive ‘luck’ that causes things to go wrong with electronics?

**Comment by agentofzog2** [comment]
1. This should go in pull requests cuz it's just gonna get buried in issues.
2. Temporary mind control will turn into a clusterfuck even if we get past the "kill urself my dude" hurdle
3, head explosions are a must, either as something that happens to the psychic or his victims or both but it has to happen

**Comment by SirSkeleto** [comment]
i like it except for push

**Comment by LordMyroc** [comment]
Psionic: "Give me your gloves."
_Greyshirt McGriff has thrown the insulated gloves._
_Greyshirt McGriff fires the laser gun!_ x8
_Psionic seizes up and falls limp..._
(Admin PM) Greyshirt McGriff: "he didn't say I couldn't also laser him to death"

I think the idea behind Push is absolutely fantastic but I am very skeptical of how it's going to work with our current playerbase.

**Comment by juanototo2** [comment]
How about you can collect Psi-points and psi power with a short channeled ability that puts a target into a short sleep, refreshes power instantly/gives some extra above the threshold, gives one psi point to the Psionic, and wipes said target's memory of how he got to this point with LARGE HUGE RED TEXT included.

**Comment by agentofzog2** [comment]
Kewl ideas:
The mind control power lets you type out your orders before using it on someone. The orders show up on their screen and in their notes.

The power works like Yuri in RA2, you can control one guy until they die, maybe control more but it drains your psi points and can even kill you.
Maybe it'll be like NuCom mind meld wherein if the target dies/takes damage you feel it too.

Psi shield because fuck getting robusted by the first dude with a tazer.

Psi telekinesis should be able to throw people.

Epic Earthbound reference only tru gaymers will get: you can name your ultimate move.

You can do an Akira and nuke the station, or become a blob (but how do we get to that point?)

No idea how psi resources would work. Maybe having to set up psychic amplifiers around the station (that have to be X tiles away from each other to work) which can be built by changing metal into psychic metal or something. But that would make it shit on b*x, unless you can make em invisible up until the point where you go Tetsuo.
Alternatively just succ brains but nobody wants another succ antag,

Maybe turn this into a team but not quite a team antag like ling.

**Comment by Demagogue-Dimension** [comment]
Remove vampire. Replace with this. Vampire is just a dumb idea and this antagonist sounds like it'll have the same function as vamp but better.

**Comment by DeityLink** [comment]
He never coded it 😔
