### ISSUE TITLE
Setting spaceninja name after late join or from admin role panel doesn't work

### ISSUE THREAD

**Issue by DDihanov** [d3athrow/vgstation13#23009]
After the prompt with the ninja name comes up and you click enter the name quickly sets and then resets to "Unknown" - doesn't matter which race you choose. Started happening after #23002

![space_ninja_bug_2](https://user-images.githubusercontent.com/24612466/58175639-41658400-7ca9-11e9-8847-30af95eb79a0.gif)

~~This bug doesn't happen  with mid round ruleset(from ghost).~~

**Comment by SonixApache** [comment]
Did you check their actual name because afaik that's just because their identity is hidden.
Couldn't reproduce on admin-toggle.

**Comment by DDihanov** [comment]
~~This doesn't happen on midround rule though. So either this is bugged or the midround is bugged.~~

Also happens midround

**Comment by DDihanov** [comment]
Here is the admin toggle

![space_ninja_admin_toggle](https://user-images.githubusercontent.com/24612466/58186319-521ff500-7cbd-11e9-97b1-ca20c4423a25.gif)

**Comment by SonixApache** [comment]
working as intended
take the hood off to see the name

works fine on midround on live as well

**Comment by DDihanov** [comment]
So it's supposed to flash your name for a second and then set you as 'Unknown'? 🤔

**Comment by SonixApache** [comment]
Yeah, because it inits your new identity after your face is covered, so it has to realize that you're covered and turn you into an unknown

**Comment by DDihanov** [comment]
Ah that makes sense.
