### ISSUE TITLE
Fucking black magic happened to tiles in the bar

### ISSUE THREAD

**Issue by Lunstra** [d3athrow/vgstation13#23004]
#### Description of issue

The tiles in the bar went real fuckin weird and looked like space even though they weren't, even weirder they fixed themselves if you moves so they were visible on the edge of the screen

https://cdn.discordapp.com/attachments/245856152276041728/580517591353655303/fucking_floors_what_the_fuck.png

https://cdn.discordapp.com/attachments/245856152276041728/580517919050563614/floors_2_electric_boogaloo.png

#### Difference between expected and actual behavior

Sprites to not bug out

#### Steps to reproduce

I have no idea, possibly something involving an actual breach and kudzu

#### Specific information for locating

Possibly in todays runtime logs but I really don't know

#### Length of time in which bug has been known to occur

Not a goddamn clue.

**Comment by Kharkov72** [comment]
visually looks cool as shit honestly

**Comment by Lunstra** [comment]
Apparently this was bussed in before I joined, but the sprites wigging out on the edge of your screen is still technically a bug I guess which is what made me think the entire thing was bugged.

**Comment by Exxion** [comment]
Sounds like someone didn't remove `TILE_BOUND` from `appearance_flags` when bussing it
