### ISSUE TITLE
Highlanders aren't hulked anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23005]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
af713b0a03040bf7243ad3daad866cc4979effc5

# Description
Highlanders are no longer hulked, they still scream a lot but are vulnerable to stuns.
# Steps to Reproduce
Press the scotland button, baton self in face
# What you Expected
Swordfights
# What Actually Happened
Stun and done

**Comment by DeityLink** [comment]
@Blithering wait they used to be hulked?

**Comment by Blithering** [comment]
Yes, full on hulk, green skin YELLING!! and more importantly stun immunity + inability to fire guns. Now they seem to only have the yelling.

**Comment by DeityLink** [comment]
Seems like it still works as intended, there's a check that prevents them from getting the green skin but they can still punch walls down and cannot slip or be disarmed.
