### ISSUE TITLE
Binary chat is unreadable on darkmode

### ISSUE THREAD

**Issue by GoodG1448** [d3athrow/vgstation13#23008]
![can't read shit](https://user-images.githubusercontent.com/38330373/58158245-6d085000-7c50-11e9-8586-64890c8f88d5.png)

Not sure about damage control, might want to check.

**Comment by PaulRitter** [comment]
![image](https://user-images.githubusercontent.com/16618384/58167704-d3ab5f00-7c8c-11e9-85fc-b87705f035a5.png)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Sometimes I forget silicons exist

Then I wake up
