### ISSUE TITLE
reagents_to_log doesn't initialize right

### ISSUE THREAD

**Issue by Aurx** [d3athrow/vgstation13#2300]
It's 0 for everything instead of the list it's supposed to be.
This breaks dangerous reagents logging.

**Comment by clusterfack** [comment]
Looks like it was fixed in https://github.com/d3athrow/vgstation13/commit/0f539e06c04655c79ef913ba442299023c264814

**Comment by clusterfack** [comment]
Is this still broken? I believe I've seen adminlogs about dangerous reagents being used recently.

**Comment by Aurx** [comment]
Still broken.
