### ISSUE TITLE
Dark Mode: Binary Text Color too dark

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23015]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
cbe73fb072aa57b0cff076be254f1df205258952

# Description
The color used for the silicon binary channel is very dark and hard to read in dark mode.
https://puu.sh/DvScw/13aeed6f1c.png

**Comment by Exxion** [comment]
Duplicate of #23008
