### ISSUE TITLE
Bees can attack through firelocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23011]
(WEB REPORT BY: assfaget REMOTE: 206.221.180.138:7777)
# Revision
cbe73fb072aa57b0cff076be254f1df205258952

# Description
Angered bees can attack through firelocks.
# Steps to Reproduce
Stand in front of a closed firelock with angered bees on the other side of it.
# What you Expected
Not to receive damage.
# What Actually Happened
Received damage.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Border objects were a mistake

**Comment by Kitfox88** [comment]
just make firelocks full tile objects again reee
