### ISSUE TITLE
On top of a myriad of other problems with it, biomass has a weird fetish for only growing southward

### ISSUE THREAD

**Issue by Lunstra** [d3athrow/vgstation13#23021]
#### Description of issue

The random event biomass has a raging hardon for only growing southwards, see pic below
https://i.imgur.com/WKmn1wh.png
That biomass went south through 3 windows all the way to the goddamn PA in engineering before growing north a single tile

#### Difference between expected and actual behavior

For it to grow in a somewhat balanced fashion like vines (and also not grow into windows where it is AIDS to remove but thats a different problem)

#### Steps to reproduce

Literally just watch biomass spawn, I've seen this happen every single time this crap spawns I just never bothered making an issue about it before

#### Specific information for locating

Mash that spawn vines button until biomass happens

#### Length of time in which bug has been known to occur

Fuck knows, probably since biomass was first made because its horrible gunk.

**Comment by ShiftyRail** [comment]
The south will rise again
Given it is purely probabilistic it could very well just be random occurence but you'd need to look at the code for that

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
IIRC the BYOND function step_rand() is bugged and goes south almost always
So 99% chance this is that

**Comment by Demagogue-Dimension** [comment]
FEATURES

**Comment by Killette2** [comment]
Now that you mention it, south is kinda hot
