### ISSUE TITLE
[Feature request] "Low" effecency lights

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#23025]
What's the point of having high efficiency lightbulbs when there's a gigawatt in the grid?

Have super high powered lights that are double as bright as normal lights, and consume five times the power.
Maybe have it have red text when examining it stating "the bright light hurts your eyes" and cause eye damage.

**Comment by FudgePucker** [comment]
Also what's the point of having goon lights if we dont have different colored lightbulbs? No drug den is complete without black lights

**Comment by brndd** [comment]
But why? Replacing lights is already a pain in the ass that nobody does. Why would someone voluntarily put *worse* lights in? Them being brighter won't help when every map is mapped to have 100% coverage with regular light bulbs.

**Comment by SonixApache** [comment]
- High efficiency lights *already* have more lighteous power than normal lights
 - Colored lighting would be a **very** good addition

**Comment by Kitfox88** [comment]
make janiborgs able to synth lights in their replacer with power instead of needing to recharge mats at stations reeee

**Comment by Intigracy** [comment]
You can already inject light bulbs with chems, and my goal at one point was to make it so the color of the combined chems in a light makes the light color change, but I'm a lazy sod and never got around to it.

**Comment by Demagogue-Dimension** [comment]
> 
> 
>     * High efficiency lights _already_ have more lighteous power than normal lights
> 
>     * Colored lighting would be a **very** good addition

I've noticed that the lights are brighter along the tube axis but dims in front of it. Could be a BYOND feature.

**Comment by Exxion** [comment]
There are multiple reasons why that doesn't make any sense

**Comment by Blithering** [comment]
Add super lights that are so bright they give people tans. In all seriousness, while we could use more use for power, lights are too basic of a utility to have much need for advanced versions. Maybe some kind of wall mounted scanners that sweep the area for injured people, wanted people or messes depending on setting, and ping the relevant robots to come fix it if they exist?

**Comment by west3436** [comment]
Low quality feature request
