### ISSUE TITLE
xeno pie recipe doesnt work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23026]
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
6ee990d58db0b9f3162940367caaecd0f22fef2a

# Description
xeno meat and flour makes meat pies not xeno pies. could be outdated recipe on the wiki or bug.
# Steps to Reproduce
attempt cooking 1 xeno meat with 10u of flour.
# What you Expected
for the recipe xeno pie to be produced with 1 xeno meat and 10u of flour, in accord with the wiki.
# What Actually Happened
a normal meat pie was produced instead.

**Comment by Kharkov72** [comment]
/datum/recipe/xemeatpie
    reagents = list(FLOUR = 10)
    items = list(/obj/item/weapon/reagent_containers/food/snacks/meat/xenomeat)
    result = /obj/item/weapon/reagent_containers/food/snacks/pie/xemeatpie

/datum/recipe/meatpie
    reagents = list(FLOUR = 10)
    items = list(/obj/item/weapon/reagent_containers/food/snacks/meat)
    result = /obj/item/weapon/reagent_containers/food/snacks/pie/meatpie

something something inheritance
