### ISSUE TITLE
ROGANbot is capable of extremely strong soundwaves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23039]
(WEB REPORT BY: juanototo2 REMOTE: 206.221.180.138:7777)
# Revision
d214e7c3d8f16aa7a9c16b0b27c7e67d9091a415

# Description
If you tune 14 radios to any channel, doesn't matter which, and then proceed to enable both speaker and microphone
then sit next to a roganbot and say a number a soundblast occurs, oversizing logs and violating the ears of anyone nearby
This effect can be amplified with a voice analyzer and speaker tied together. If you set the voice analyzer to the response made by ROGANbot after saying a number and set the speaker to the number, YOU CRASH THE SERVER.
# Steps to Reproduce
See above
# What you Expected
For it to not log or crash servers when doing ungodly screeches
# What Actually Happened
It crashed my client and caused untold amounts of hilarity

**Comment by juanototo2** [comment]
Basically the way it works is that when you screech the number over the radio and the radio reports it inside of its radio channel it can also hear that particular number separately
This causes it to say as many times the number as you have radios on you
This also works with using the chatbar to ctrl c ctrl v screech out
The result is a blast of sound nothing can escape

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I really wanted the ROGANbot to not have a delay because that's how AoE2 was
THIS is why we can't have nice things
