### ISSUE TITLE
Bloodstones are a tad extra bullshit on roid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23048]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
bc187937068fa7fb30a51cf9cb9ba0c1614ef4bc

# Description
as well as spawning on the edge of nowhere they also delete some roid tiles and turn them into space

**Comment by ShiftyRail** [comment]
![image](https://user-images.githubusercontent.com/31417754/58387409-42324900-800e-11e9-81a8-68a6c1ddfd04.png)

Cultists will defend this

**Comment by DeityLink** [comment]
What area was the stone located into exactly? Unsimulated roid turfs shouldn't be elligible.
