### ISSUE TITLE
Paroxetine/Citalopram don't protect against fake doorshocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23051]
(WEB REPORT BY: lazyrobot123 REMOTE: 206.221.180.138:7777)
Despite being dosed with about 6~ units of paroxetine during a hallucination, attempting to pass through a door will give you the snowflake "You feel a powerful shock course through your body!"

This may be because it checks if your hallucination is above a certain threshold, without checking if you have any anti-psychotics.

**Comment by SirSkeleto** [comment]
for anyone who intends to fix this, consider implementing a proc that checks the hallucination value and the anti psychotics and returns stuff that can be useful rather than fucking whatever this is

**Comment by west3436** [comment]
Doorshock hallucinations were removed in #35745 so this one is O.B.E.
