### ISSUE TITLE
Revs couldn't convert people with flashes

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#23063]
Time of round: Around 4 EST
Problem: Multiple head revs were attempting to flash people to convert them to revs, and it wasn't working.
No flash protection, they weren't implanted yet, just wasn't working, they weren't implanted as it was WAY too early in the round for that to be the case.
🤔

**Comment by Irradiation** [comment]
But did they use their snowflake roundstart flashes or did they use whatever flash they found?

**Comment by Kharkov72** [comment]
It's normal revolution, that literally doesn't matter.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
It was RP rev, you had to convert people with roleplay
