### ISSUE TITLE
Activated Charcoal needs a reason to exist

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#23069]
[discussion]
The water+potassium explosion clearing reagents was brought back for some weird reason despite other methods existing and charcoal having been buffed to be actually useful for quite a while now.
However it really has no reason to exist now, smoke and waterpot pills are completely superior to it by both being instant and not requiring a heater mass-produce.
Could we come up with any reason to justify its existence? I've been drawing a blank for a while since its only other realistic feature would be reducing toxin damage but dylovene has always been ubiquitous and more efficient.
Maybe it's time to remove it, who would miss it?

**Comment by Allspice** [comment]
Charcoal has the benefit of less clicking and working most of the time.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Charcoal
 + has no preparation time (you get it for fucking free in the medvends and it never ever runs out)
 + only requires you to pill/feed the guy once
 + is blazing fast, clears 99% of overdose cases in seconds, most of the time even faster than it would have taken you to feed the guy the second pill

Water+pot
 --- causes significant burn damage on the patient thanks to the byproduct 
 - requires 2-step pilling
 - requires preparation
 + ""instant""

**Comment by bathosbathtime** [comment]
There is absolutely nothing wrong with giving players multiple solutions to the same problem.

**Comment by DrSnips** [comment]
I think both are fine as is. Personally I prefer charcoal due to it being a safer method.

**Comment by Killette2** [comment]
Actually botany can mass produce charcoal too with the biogenerator

**Comment by kilozombie** [comment]
>However it really has no reason to exist now, smoke and waterpot pills are completely superior to it by both being instant and not requiring a heater mass-produce.

I agree-- the first thing I want to do when a patient is filled with poison is turn that poison into an AoE smoke reaction.

**Comment by Kurfursten** [comment]
>smoking out poison

based and pAIpilled

**Comment by SonixApache** [comment]
I have an idea.
We could remove that thing where water-potassium deletes all reagents inside people.

**Comment by Chronakai** [comment]
> all reagents inside people.

Or have it also include blood. Blood's a reagent.

**Comment by SonixApache** [comment]
yeah but that's not in their reagent container, but in their vessel, so it's different
