### ISSUE TITLE
Credits music isn't playing

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#23066]
*scream

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
http://ss13.moe/media/source/roundend/credits/Frolic_Luciano_Michelini.mp3 is dead
@d3athrow what hapen

**Comment by d3athrow** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE the jukening was very large so I moved the folder and didn't realize you hard linked the credit thematic.
http://ss13.moe/media/m2/source/roundend/credits/Frolic_Luciano_Michelini.mp3 is the new link.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Do the roundend jingles werk?

**Comment by d3athrow** [comment]
are they also hard coded by url?

edit: seems like they are, i'll see if doing a url rewrite will work in game.
