### ISSUE TITLE
bedsheets are layered under people in a specific case

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#23070]
#### Description of issue

- walk onto tile that has bed and bedsheet
 - rest -- you will be under the sheet
- buckling will keep you under the sheet
- stand up
 - buckle yourself to the bed
- behold, above the sheet

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Woooow bugged bedsheet mechanics

**Comment by SonixApache** [comment]
this was caused by #22111
