### ISSUE TITLE
Activating the Pirate energy cutlass doesn't update your sprite

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2308]
You have to drop/equip something with a in-hand sprite for it to show.

**Comment by clusterfack** [comment]
I can't reproduce this, they seem to work perfectly fine at the moment. We have made more recent changes to updating player icons than this.

**Comment by ComicIronic** [comment]
I'll give everyone a chance to reply, but if it can't be reproduced then I'll close this.

**Comment by clusterfack** [comment]
Closeable I guess
