### ISSUE TITLE
Organic debris shower event is basically nothing

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#23081]
#### Description of issue
The organic debris event has no impact on the station, good or bad. Noone to my knowledge has ever picked up and made use of the random organs that bounce off the station. At this point its just a thing that puts the event timer back on cooldown
Could change it to maybe have the guy thrown at the station have random gear equipped so there's something worth salvaging, have the organs be bizzare alien ones with benefits or side effects, or maybe have a chance that the debris is actually a xeno egg or dormant changeling.

**Comment by SonixApache** [comment]
even better is that the force of impact causes most of the organs to gib anyway

**Comment by Exxion** [comment]
Was the bug where you couldn't even really pick the pieces up ever fixed?

**Comment by west3436** [comment]
This event was greatly improved in #32745.
