### ISSUE TITLE
Feature Request: Oh god oh fuck ops button

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#23098]
The music playlist that revs uses was also planned to have functionality with ops, but ops doesn't have an "Endgame" at the moment
One of the ideas we discussed was having some sort of verb for the ops leader that would trigger endgame music when they decided to go loud.
gibe code

**Comment by SonixApache** [comment]
Or, more globally, a 'play playlist' button.

**Comment by Zth--** [comment]
Fullfilled here #23098
