### ISSUE TITLE
Time Suit's "Jump to Past" spell deletes clothes off it's user

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23095]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
ecb0869bee507f0ce298ff2e7311301da51c294f

# Description
The Time Suit's "Jump to Past" spell removes the clothes and other things off of whoever uses it. From what I see it's still in the contents of the user, they just don't wear it anymore.
The suit is pretty old and the spell probably broke at some point in the past.
# Steps to Reproduce
-adminspawn full time suit set
-use "jump to past"

**Comment by tayachiya** [comment]
The entire suit is a bunch of bugs. After using any ability, I remember everything going wrong. My blood was going down, when trying to drink anything i'd refill the beaker instead, etc. It's just a mess that can also very much lag the server to oblivion.

**Comment by Allspice** [comment]
Blood loss and clothes deletion should be fixed now.
