### ISSUE TITLE
Messages get endlessly repeated as a MMI in a cyber-trophy belt

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23096]
(WEB REPORT BY: vasby REMOTE: 206.221.180.138:7777)
# Revision
ecb0869bee507f0ce298ff2e7311301da51c294f

# Description
https://i.imgur.com/kvO6EUY.png
and
https://i.imgur.com/EUgv6hM.png (I got those messages in about 10 secs)

# Steps to Reproduce
Not sure. the counter of x28 increased each time I talked

# What you Expected
To not have the messages repeated so many fucking times, making this a slideshow.

# What Actually Happened
every single chatter (be it radio or not) got repeated N times

**Comment by frangi** [comment]
Here a pic of me (Serenity Bullard) talking in the belt, and the counter increasing
https://i.imgur.com/ORlEUuU.png
