### ISSUE TITLE
Packed N2O

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23116]
(WEB REPORT BY: baronze REMOTE: 206.221.180.138:7777)
# Revision
bb09e79c323141966e906be3f0866e9970472c66

# Description
N2O cannisters in the Packed atmospherics show up as having "unknown" gas when analyzed.

# Steps to Reproduce
Just analyze the N2O cans in Packed atmospherics.

# What you Expected
Analyzer to show the gas correctly as N2O.

# What Actually Happened
Analyzer showed it as "Unknown" gas causing some small confusion.

**Comment by Kammerjunk** [comment]
duplicate of #23115
