### ISSUE TITLE
Being in a tractor cart when it explodes sends you to the shadow zone

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23119]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
8778af6323c83c48c9db41801181215fcae292a4

# Description
If you are in a tractor cart and it gets destroyed you are immediately deleted.
# Steps to Reproduce
be in cart, get caught in an explosion
# What you Expected
damage from explosion
# What Actually Happened
ghost appears in arrivals shuttle.

**Comment by Kitfox88** [comment]
too much power for mortals
