### ISSUE TITLE
Atmospherics Packed Gas N2O

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23115]
(WEB REPORT BY: baronze REMOTE: 206.221.180.138:7777)
# Revision
bb09e79c323141966e906be3f0866e9970472c66

# Description
N2O cannisters in the Packed atmospherics show up as having "unknown" gas when analyzed.

# Steps to Reproduce
Just analyze the N2O cans in Packed atmospherics.

# What you Expected
Analyzer to show the gas correctly as N2O.

# What Actually Happened
Analyzer showed it as "Unknown" gas causing some small confusion.

**Comment by Kammerjunk** [comment]
not a Packed issue, N2O always shows up as unknown
here's me spawning in a can of `/obj/machinery/portable_atmospherics/canister/sleeping_agent` on Deff locally
![image](https://user-images.githubusercontent.com/5942183/58765385-d9e5e900-8572-11e9-87bd-d109264f7f8a.png)

**Comment by Exxion** [comment]
It's always been this way
See #20082
