### ISSUE TITLE
Juke Fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23120]
(WEB REPORT BY: originalbubsra REMOTE: 206.221.180.138:7777)
# Revision
8778af6323c83c48c9db41801181215fcae292a4

# Description
Changing access to jukebox does not seem to actually give access to change playlists.
# Steps to Reproduce
Asked bartender to change permissions to none.
# What you Expected
Being able to change the playlist.
# What Actually Happened
Still cannot change the playlist.

**Comment by west3436** [comment]
Unable to reproduce - this works fine
