### ISSUE TITLE
T-ray and P-ray scanners don't reveal invisible-sprayed people

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#23121]
It seemed to me like these were the tools for uncovering invisible people, but this doesn't seem to apply when invisible spray is involved.

If this is intentional, feel free to close.

**Comment by Gringonius** [comment]
Scanners work on invisible wizards, never did for invisible spray, which goes away with water.

**Comment by Dacendeth** [comment]
I thought they did before, and if they never did I dont see why it should stay that way.

**Comment by Killette2** [comment]
abandoned. all hope is lost
