### ISSUE TITLE
Maybe it's time to tone down or revert permagunk

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#23124]
#### Description of issue

Permagunk is a bad addition for the game for two reasons.

Chiefly, there is very little way to explain it IC-wise ; it boils down to the tentative "morning shift are animals", which gets boring to repeat after the n-th time.
As a result, you end up with a station of sociopaths who are content to ignore the rotting corpse next to them if there's no janitor or if there's no soap available.
The end result is inherently harmful to RP ; it's harder to keep in character when there's 4-th wall breaking messes everywhere?

How can your submarines immerse themselves in such conditions ?

Secondly, permagunk makes it a lot more difficult to detect signs of unusual activity or messes ; was this bloodtrail leading to maint from a previous shift, or did someone just get murdered ?
Did someone kill a borg in maintenance, or is it just junk from a round before ?

Combine that with the tendency of rounds to go to shit relatively fast, with dozens of blood tracks, vomits, and other effects (particularly visible in places like medbay), and you end up in a confused haze in which you ignore any and all blood because it's gonna be a false lead 75% of the time.

Much like the first point, this further encourages the idea that spacemen are just sociopaths, used to living in the trash, and removes a lot of opportunities to build up narratives by following blood tracks in maintenance.

#### How to fix it

Reverting it completely may be a bit too excessive, but I believe capping the number of decals and trash carried over from one round to the next to, say, 10 **per zone** wouldn't be so bad.

The decals should also not last more than 1 round.

Feel free to discuss.
[discussion]

**Comment by Exxion** [comment]
I don't like permagunk either, but blood from previous rounds is a considerably darker color than fresh blood
I think it also has a different name, but I'm not sure about that one
Either way it's not that hard to tell

**Comment by boy2mantwicethefam** [comment]
No.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I still want the poll, it was supposed to be a test merge.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Also, I agree that there are immulsion problems with it and that it steps on the detective etc's toes. I think 90% of that is focused entirely around blood and gibs however (which are also, like, 90% of the cleanable messes generated)

**Comment by Intigracy** [comment]
I think making it even darker to be more obvious in blood's case would help a lot

**Comment by soyconsumer** [comment]
It's way too much gunk. A roundstart station now looks like one after a 5 hour round.

**Comment by KingofHONK** [comment]
im in favor of a tone down, but outright removal would be fake and fuckin gay. Its a cool subsystem that gives janitor shit to clean round start and is worth keeping.

**Comment by Chazach** [comment]
no one gets mad at cigarettes and trash on the floor, but when you spawn knee deep in gibs and there is absolutely no way to reconcile this IC its pretty gay

**Comment by Kitfox88** [comment]
if we have evidence of previous rounds then we must also be allowed to metagrudge staticname shitters

**Comment by SonixApache** [comment]
yeah permagunk is stupid, distracts from actual blood and any blood-related bus
trash is probably fine, a cig bud here and there fits, especially in maint

**Comment by MadmanMartian** [comment]
Cig bud's probably not until they're fixed from becoming unlimited fire

**Comment by Caboozles** [comment]
Leave trash and such, but there’s way too much blood.

**Comment by Coxswain-Navigator** [comment]
I always thought permagunk was a fucking terrible idea but i never got a chance to voice my opinion on it. And it went just about as badly as i expected. How are detectives supposed to even work now? Fresh blood looks more or less the same as mapped blood in certain places.

**Comment by DrSnips** [comment]
I think blood should be removed from the carry over to start. I'm ok with SOME trash but 5 per zone should be the limit. Footprints also get super out of hand sometimes.

**Comment by Allspice** [comment]
On a tangent, beating the shit out of people and generally people hemorrhaging to death leaves a pitiful amount of blood at the moment.

**Comment by ghost** [comment]
I really like how permagunk gives the Janitor role an incentive, and much more importance. I think:

>How to fix it

>Reverting it completely may be a bit too excessive, but I believe capping the number of decals and trash >carried over from one round to the next to, say, 10 per zone wouldn't be so bad.

is a good compromise.

**Comment by SonixApache** [comment]
Enough gunk is generated in an average round to warrant janitors existing, on top of their ability to griff and do other things.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Where is the poll
