### ISSUE TITLE
Advanced EOD suits are hilariously fucking strong

### ISSUE THREAD

**Issue by KingofHONK** [d3athrow/vgstation13#23125]
Jesus christ how horrifyingly OP these are. 20-30 minutes into the round and you can survive all kinds of deadly shit that would make even the most egregious powergaming faggot (me) giggle in disbelief.

Intended to be a discussion. I still dont understand how to tag.

**Comment by Irradiation** [comment]
Now imagine if they were spess resistant :smile:

**Comment by DrSnips** [comment]
The other not EOD armor from the proto is pretty trash both visually and mechanicly. Having some good armor behind mats is nice to have around for bus and/or away missions and I don't see a lot of people complaining about it if any.
