### ISSUE TITLE
Cheif Enginner Vox Spawn with Extended Oxygen Tank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23137]
(WEB REPORT BY: laserdog REMOTE: 206.221.180.138:7777)
# Revision
fef580631c834e36afd6c75a9c0954e020c6050d

# Description
Cheif Enginner Vox spawns with a emergency extended-capacity oxygen tank instead of an emergency extended-capacity nitrogen tank
# Steps to Reproduce
Spawn as Chief Enginner as Vox
# What you Expected
Have a nitrogen tank in my emergency box
# What Actually Happened
Had a oxygen tank in my emergency box

**Comment by FudgePucker** [comment]
>not scrubbing the O2 out and filling the extended emergancy tank with N2 for the boosted volume

Also
>Implying you are ever going to take your suit off anyways

**Comment by FudgePucker** [comment]
All head roles being human only when?
No red blooded captain would let a sub species have authority over a department.
