### ISSUE TITLE
vox mechanic spawns with wrong survival box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23149]
(WEB REPORT BY: suchai REMOTE: 206.221.180.138:7777)
# Revision
51ecab414b20d9cfce8a4c0198da691fb00cb173

# Description
at least on packed, vox mechanic spawns with survival equipment box that holds human breath mask and oxygen emergency tank.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
this just in, packed is anti-vox?
