### ISSUE TITLE
Cult requires exactly 1 (one) enemy to fire

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#23142]
#### Description of issue

Cult is coded to require 2 enemies at below 20 threat, 1 enemy from 20 to 80, and no enemies after that
It, however, costs 25 threat to fire so it will always just check for one adversary

Said adversary can be a lone officer without access to the armour, a dummy Head of Personnel, or a simple captain with little concern for station matters

I feel this should be changed

**Comment by boy2mantwicethefam** [comment]
No.

**Comment by KingofHONK** [comment]
what you dont like 1pop sec cult gangbang free wins as well?

**Comment by SonixApache** [comment]
I would like this changed because cult is gay, but first I would like the possibility for midround cult.

**Comment by DeityLink** [comment]
Raise it by one then wait a bit before doing it again. I'm fine with that, justifies buffing the cult later and change the meta :^)
