### ISSUE TITLE
Roomba PAIs are stupidly strong

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23154]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
ecc780ec488825875ecc70fcc150af774b831457

# Description
incredibly difficult to click, can kill incredibly fast due to smoothmove touch memes, can be generated indefintely if the guy is being gay enough

**Comment by RealestEstate** [comment]
this always happens when we make something that damages simply by moving into mobs.
ie. syndiechairs, PAI MULEs, this.

**Comment by RealestEstate** [comment]
but also
rack parts and tables and git gud

**Comment by Blithering** [comment]
The battle roomba was mostly a joke, lowering the damage seems sensible. Either that or restricting the pAI to bucketbots
