### ISSUE TITLE
CMC doesn't show anyone

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#23167]
#### Description of issue bugfix

The CMC just says "No data currently available" on every z-level, although there are people with sensors, especially on z1

#### Difference between expected and actual behavior

Expected people with sensors to be shown on CMC, was disappointed

#### Specific information for locating

No data currently available
--

#### Length of time in which bug has been known to occur
I noticed it today

#### Server revision
6bad4ad2c5f578471931579971b79656fe5a47ca

**Comment by PaulRitter** [comment]
nothing go changed, so i wouldn't know what would cause this.

For anyone who wants to look into it, the data gets updated by a js function call, so this either means that
a. the function never triggered
b. the function got invalid params resulting in no results
c. there were no people with active suit sensors
