### ISSUE TITLE
Inconsistency Cargo: Security Barrier

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#2316]
Price of Security Barrier is listed as 10

When I try to approve my order for a security barrier with 15 left in my account, it tells me I don't have enough.

Didn't bother testing to see what the actual price is, but I suppose you'll see it in the code.

**Comment by ConkerDev** [comment]
Not a bug?

**Comment by clusterfack** [comment]
Yeah there is a tax on cargo shipments
