### ISSUE TITLE
[Feature Request] The Gunked

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#23173]
[featurerequest]
A creature of pure hate and anger, a makeshift space suit and space helmet have been grafted into their skin, if they had any left, only thing really holding them in place is that grey jumpsuit. They have only one objective, shit up everything.

As I had said in another issue, we need more antagonist types to dilute the pool that dynamic picks from, so every round isn't the same.
So here is my idea, a former assistant survived a destroyed station, but lost all humanity in the process, fueled by hate of "jobbies" and "shitcurity" it flys though space looking for more shit to ruin.
It has a ghetto space suit and helmet that are different on examine, has no slow down, and can't be removed.
A tattered gray jumpsuit that cant be removed. Melted insulated gloves that cant be removed. Ruined black shoes, I will leave it up to you if they should be removable or not (do you want them to be able to wear magboots). Advanced welding goggles. And a jetpack.
A gray toolbox that is super glued to their hands, inside is wirecutters, crowbar, screwdriver, wrench, spray bottle filled with lube, ion pistol, and a pill bottle filled with basic meds.
At creation they choose their name and get an assistant ID with external airlock access added to it, but they are not on the crew manifest. They spawn in space like ninjas.
They do not need to breath, turn into ash on death, and are not human (that is, if the Silicons can tell the diffrence.)
How they should talk is up for debate, full ability of common, mute (the silent shuffle), only being able to say a few phrases randomly when typing in say, "fuck security" "get dabbed on jobbie" "valid secured", or having a word replacer "captian" into "condom" "security" into "shitcurity" and so on. Also give them the dab emote but it doesnt kill them :^).

This would provide a threat to the station, that isn't, ninja with autoclicker insta killing shuriken, fireball blink hard suit wizard, or nukeops. Potential to ruin shit, but not God awful.

**Comment by AI-Is-Rogue** [comment]
Sounds like it could become a sort of slasher-like antagonist.

**Comment by FudgePucker** [comment]
That's the idea I was going for, but more related to our servers "culture". Remember, we also have loose catbeasts.

Also another funny idea for an objective is to acquire the captains spare ID,  and you get a pin pointer towards it in your pocket.

**Comment by ghost** [comment]
I really want to see a saboteur midround role, this sounds like an interesting way of doing it even if it's a bit memey.

For the point about them talking, maybe let them speak in common but only one word at a time on a cooldown (10-30 seconds)?

**Comment by Exxion** [comment]
Going to point out that the name, in addition to just being bad, fails the one-year rule
Not a fault with the idea, just the name

**Comment by GoodG1448** [comment]
I thought the name had to do with something related to trash. Something like a being that emerges from vomit, blood, oil puddles or something like that.

**Comment by FudgePucker** [comment]
Well anybody got any ideas for names then?

**Comment by jknpj** [comment]
Hollow (Not the ones that come from Neo-Space-Mexico)

**Comment by ghost** [comment]
I'm gonna attempt messing around with this. It seems fun, and therefore, right up my alley. Don't expect anything. 🥇

**Comment by ThatRedPyro** [comment]
Maybe a half-burnt stolen emag to fuck around and sabotage stuff with?Make it so it can't open doors and do some of the more extreme things an emag can do as well to restrict it a bit?

**Comment by Blithering** [comment]
I have sprites for ghost people (from new vegas) from a vault that was never finished, they fit the "assistant gone feral" kinda aesthetic if you'd want them.

**Comment by west3436** [comment]
It's been nearly 5 years + assistants already do all of this (for free)
