### ISSUE TITLE
Vox in roboticist jumpsuit has no tail on sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23178]
(WEB REPORT BY: suchai REMOTE: 206.221.180.138:7777)
# Revision
404bcadfbc1ff374de2253cf8e5e0a6728e9bf06

# Description
like in title. Voxes wearing roboticist jumpsuit have no tails.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
No, the problem is the skin (quill?) color
The "newer" colors don't have them

**Comment by Zth--** [comment]
Duplicate of #13714
