### ISSUE TITLE
Suggestion for Stun Glove balance

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#2318]
Stun gloves can be seen on hands; if someone wears a hard suit or something, they can no longer be seen.

Stun gloves can not be disarmed out of the hand. If you can't see the stun gloves, is there a way to cause them to be unusable?

**Comment by EenKogNeeto** [comment]
Stun gloves were already nerfed into the dust and are completely irrelevant in modern 2d Spessmen. I have seen them maybe once in 30 rounds. I don't think they need any more balancing.
