### ISSUE TITLE
robotics machines need to be updated to allow printing of ultra-capacity power cells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23182]
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
d1f77d31c24efbcb13c8e8054db264ad0cbdf27e

# Description
what it says on the tin. fully researched RnD can print ultra cells but robotics can't
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Implemented in #30414.
