### ISSUE TITLE
Bunsen burner doesn't work with densely separated sample

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23195]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 206.221.180.138:7777)
# Revision
dbae2216dd4d2e4b0c59107a90d112212abaa838

# Description
Densely separated sample does not react with bunsen burner to produce carrier fluid. 

# Steps to Reproduce
Add densely separated sample from xenoarch to bunsen burner, turn on, wait for something to happen. 
# What you Expected
Carrier fluid is produced.

# What Actually Happened
Nothing, save for wasted fuel.

**Comment by icantthinkofanameritenow** [comment]
Forgot to clarify, tried this once with ethanol fuel and once with plasma fuel.

**Comment by ghost** [comment]
Remove the ground rock and try again.

**Comment by icantthinkofanameritenow** [comment]
> Remove the ground rock and try again.

From the grinder? I had already mixed it with the sodium lithium tungstate or whatever it's called at the time, so that wouldn't have been possible.

**Comment by T-Wiz** [comment]
> Remove the ground rock and try again.
Tried that, doesn't work.

**Comment by DeityLink** [comment]
densely separated sample was removed
