### ISSUE TITLE
Boxstation air injector in toxins is off by default, cannot be turned on directly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23202]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 206.221.180.138:7777)
# Revision
efdc09934e060ed1aee967004ae59a22dd6019e0

# Description
See the title; due to lack of nearby atmos computers the injector cannot be activated normally. 
# Steps to Reproduce
Use toxins, making sure to follow the wiki's instructions about the pumps.
# What you Expected
Gas goes into burn chamber.
# What Actually Happened
Nothing, struggle to figure out what's going on until admin tells me that no gas was going in.

**Comment by icantthinkofanameritenow** [comment]
Correction: there is an AAC in toxins storage, but the injector does not show up on it. Perhaps there's a frequency mismatch?
