### ISSUE TITLE
Say window appears horribly offset from centre over the chat log now

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23204]
(WEB REPORT BY: lunstra REMOTE: 206.221.180.138:7777)
# Revision
493e3fcfc5b398805f1bdae9173b61e55eb29a76

# Description
MY AUTISM AHHHHHHHHHHHHHHHHHH

**Comment by ShiftyRail** [comment]
The main reason being that because byond does not tell us what your resolution is, what is the centre on one monitor isn't in another one

**Comment by DamianX** [comment]
fixed
