### ISSUE TITLE
Ragin Mages should switch with Wizard mode instead of being added to rotation when on High population

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2320]
1 wizard doesn't cut it versus 30+ people, and we're getting too many Wizard Rounds lately.

**Comment by clusterfack** [comment]
Partial means you like something Dylan. I think wizards should get spell points based on playercount, not the raging mages obviously. Now that we've needed the insanely overpowered spells this seems fairly reasonable.

**Comment by Imagebard** [comment]
Now that I know why Ragin Mages exists, Clusterfack suggestion sounds a lot better.
Closing.
