### ISSUE TITLE
DamianX fucked up hotkey "t" chat window. reee

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23218]
(WEB REPORT BY: spcmn REMOTE: 206.221.180.138:7777)
# Revision
8f063522a32cf48e71908e333b16b4d5df91573e

# Description
Can't exit out of a window to delete chat. It re-adds the last typed up words to the new window. Cannot open multiple windows to type down diffrent things, because it remembers only the last things spoken, preventing multiple windows for chat. Using " more than 4 times breaks the type and makes it so you cannot use space afterwards
# Steps to Reproduce
Use the chat window

# What you Expected
"t" hotkey to work like it used too.# What Actually Happened
 It proceeds to don't work like it used to.

reee

**Comment by kilozombie** [comment]
https://github.com/vgstation-coders/vgstation13/pull/23188

**Comment by DamianX** [comment]
>Can't exit out of a window to delete chat. It re-adds the last typed up words to the new window. 

this can be fixed

>Cannot open multiple windows to type down diffrent things, because it remembers only the last things spoken, preventing multiple windows for chat. 

this cannot be fixed

> Using " more than 4 times breaks the type and makes it so you cannot use space afterwards

this cannot be fixed as far as I know, because of how sending the message when ENTER is pressed is handled

let's smash that revert button, we can't have nice things

**fuck**

**Comment by Exxion** [comment]
I'm not convinced the second can't be fixed, but it would definitely be a pain in the ass
Check out `winclone()`
You'd want to do it ahead of time somehow though because there's no clientside version of that

**Comment by DamianX** [comment]
I forgot about `winclone()` but as you say it's server-side which is a deal-breaker for this thing. Creating a bunch of invisible windows ahead of time could work but it sounds like a lot of work.
