### ISSUE TITLE
Turrets can't hit you if you're ontop of something, apparently.

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2324]
http://s7.postimg.org/51atf9orf/000_Fuck_Off.png

**Comment by Kurfursten** [comment]
Solved more than a month ago according to Comic in #2371 

Close this

**Comment by clusterfack** [comment]
Different issue is different

**Comment by Kurfursten** [comment]
Please describe the difference, photocopier is used in the OP image

**Comment by clusterfack** [comment]
Ririchiyo made the same mistake, that issue was about the enter proc not being called for the area, as such the mob was not being considered a valid target to shoot at.

**Comment by ComicIronic** [comment]
Can confirm this issue is unrelated to #2371 except that they both involve photocopiers.

This could be fixed by making the photocopier's CanPass return 1 if the atom can go over tables.
Otherwise, density works as expected.

**Comment by clusterfack** [comment]
I mean thanks for that pomf, but I think the issue was supposed to be that lasers dont hit mobs on top of ANY dense object?

**Comment by ComicIronic** [comment]
That's intended behaviour.
A mob in a dense turf is embedded inside the turf. Mobs aren't otherwise meant to be able to reach those positions.
