### ISSUE TITLE
I CANT BUCKLE IN AHHHHH

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23247]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
cee027c70bb5981243063e2a97d3cb832619a579

# Description
cant buckle myself or other people to chairs

**Comment by JedediahSmith** [comment]
Fixed

**Comment by Zth--** [comment]
Closing this because of the lack of info and it's very unlikely this is still relevant. Report again with steps if you keep having this problem
