### ISSUE TITLE
Silicate Sprayers Don't Work Through Windows Anymore

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#23252]
The preattack doesn't check adjacency, only distance, so you can spray windows on the far side. Something with preattack probably changed.

**Comment by DrSnips** [comment]
Is this really a bad thing? It saves having to move windows to spray one on the far side. I don't see how this could be used in a negitive way so call it a feature.

**Comment by Kurfursten** [comment]
You seem to think things are the opposite way they are. Originally you could spray the far side, now you can't.

**Comment by DrSnips** [comment]
Oh I thought that the title was wrong based on the body. My bad.

**Comment by Kurfursten** [comment]
This was fixed
