### ISSUE TITLE
Request: Machine that prints out custom medals for the captain to give out to the crew

### ISSUE THREAD

**Issue by small-boss** [d3athrow/vgstation13#23258]
Add a machine to the captain's office that allows command to create medals with custom title to give out to crew members for heroic acts like getting valids, fixing holes etc etc.
The medals are just fluff but it would still be a fun addition and we already have sprites for medals that barely ever get used.
I would code it myself but I'm a brainlet

**Comment by JedediahSmith** [comment]
Examine: This is Greyshirt McJonson. He is wearing a grey jumpsuit. The jumpsuit has a medal that reads, "Tide Tard"

I might learn code to do this

**Comment by spoonylove** [comment]
Like a chem master but with medals.
