### ISSUE TITLE
Cannot recharge plasma cutters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23285]
(WEB REPORT BY: utilitas REMOTE: 206.221.180.138:7777)
# Revision
1badcae66dfbc06c8217db0c3306f0e381dbcb1c

# Description
 You can't recharge plasma cutters.

# Steps to Reproduce
 Try to put a spent plasma cutter in a gun recharger.

# What you Expected
 A plasma cutter that will get recharged.

# What Actually Happened
 Nothing.

**Comment by aceedex** [comment]
That's intended. Feed them plasma
