### ISSUE TITLE
Box is gunked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23299]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
8cb358fd22bcdc25ac3e8c3195a7804b64785d3d

# Description
Something gunked up the map and placed around random shit
Added images of what I found but there's more stuff around probably
# Steps to Reproduce

# What you Expected
normal round on the best map
# What Actually Happened
https://puu.sh/DIlvU/77419e9a96.png
https://puu.sh/DIlwR/8c7b81a9ab.png

**Comment by Exxion** [comment]
God damn
Never, ever use the revert button on map PRs
They *must* be reverted manually

**Comment by Exxion** [comment]
Hm
Actually, did that even happen? I don't see any reversions on map PRs
Maybe someone just fucked up the mapmerger

**Comment by ShiftyRail** [comment]
Yeah that'd be me

**Comment by Exxion** [comment]
Fixed by #23300, presumably
