### ISSUE TITLE
Remove SPS beeps

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#23296]
They were and are a terrible addition to gameplay.

**Comment by ghost** [comment]
*drags officer into maint*
*leaves him dead forever*

**Comment by nuklearcellphoneg** [comment]
>going into maint alone

Dumb secci

**Comment by ShiftyRail** [comment]
The creativity and sense of fun of our antag and their freedom would rather end with a behead and hiding the head in a red toolbox
Dupe of #18872 and was attempted in #18856 which was an overwhelmingly negative feedback

I will leave this one open as it's more fresh but it's shitpost-esque nature isn't going to convince a lot of people

**
![image](https://user-images.githubusercontent.com/31417754/59802552-88b35480-92e9-11e9-9824-1fb9a4f5941d.png)
**

**Comment by Caboozles** [comment]
I'm sure this would help our security population.

**Comment by DamianX** [comment]
I'd testmerge a PR doing this TBH

**Comment by ShiftyRail** [comment]
![image](https://user-images.githubusercontent.com/31417754/59803554-1abc5c80-92ec-11e9-961d-1bb52da29928.png)

This is IMO the best summary of the SPS discussion
Not to mention it's a good tool to simulate teamplay and helping newbies/creating a more enjoyable experience in a team-based departement

**Comment by nuklearcellphoneg** [comment]
If you decide to nonlethally knock out a sec officer and impersonate them... well, you can't do that, it will alert all of security.

If a security officer walks up on you in maint while randomly patrolling while you are in the middle of antaging.., you must knock them out, then you must space them. You can't strip them and weld them in somewhere- sec will be incoming and search the surrounding area.

If you are any random crewmember, why call for help if someone is attacking you? Why risk being killed and hidden? Just equip an SPS, and it will notify every single security member. You have no idea if someone has an SPS... until you remove it, and you can't search a bag... without removing it.

Security automatically knows when something is happening to one of theirs or anyone with an SPS. Why even bother looking at cams? The SPS will notify you of death, stripping, converting, etc etc. 

It is not conducive to teamplay. It is a substitute for teamplay. Why use the buddy system as security? The SPS will notify you if your buddy is in trouble.

**Comment by nuklearcellphoneg** [comment]
>Dupe of #18872 and was attempted in #18856

Where's the polls?

**Comment by ShiftyRail** [comment]
The buddy system existed in the form of buddybags.
Then, someone died and made a PR to remove them.

**Comment by Caboozles** [comment]
You wouldn't be able to impersonate Sec anyway because of implants, unless you're already someone with an implant.

How often do non-security personnel have SPS on them? This is such a false narrative that it's frankly almost insulting. Maybe during a late-stage cult round, but at that point in time you have way more than enough tools to handle it.

**Comment by nuklearcellphoneg** [comment]
>You wouldn't be able to impersonate Sec anyway because of implants, unless you're already someone with an implant.

Not true

>How often do non-security personnel have SPS on them?

HoP and Cap for one.

**Comment by ShiftyRail** [comment]
If it had to come to this, a non-meme option would be to complexity the system a bit. 
For instance, allow you to tear down a belt, backpack, or pockets, with a knife so that you could remove the SPS if you prepared enough.

**Comment by iFlashYou** [comment]
You mean the sound they make or general sps beeps?

**Comment by Desuiseiseki** [comment]
We don't have health analyzer grenade/assembly components, we should not have SPS.

**Comment by JedediahSmith** [comment]
What if SPS simply detected death but not removal? Allowing for all the shenanigans that @nuklearcellphoneg proposes while still adding an interesting failsafe.

**Comment by utilitas-** [comment]
Except you can knock out SPSes, Nuke, you unrobust piece of shit.
Hint: Electromagnetic pulse.
Delete this.

**Comment by FudgePucker** [comment]
>we don't have health analyzer grenades

We kinda do actually, mouse trap assimbaliys. Keep a plolyacid smoke grenade rigged in your pocket, if somebody strips your jumpsuit or picks your pocket they get totally fucked.

Also on the subject, the SGPS does have some counter play with proxy sensors. Sure when you kill someone with a SGPS all of security is going to pour into that location. But that ALSO means all of security is going to pour into one location. Polyacid smoke or max cap bomb on a proxy, they will run straight into it. You can turn one officer roaming maintenance by themselves into half of security being wiped.

Also Nuke, captain and HoP having SGPSs is really important for round health. An antag getting all access and a energy gun will gunk things hard.

**Comment by JedediahSmith** [comment]
>You wouldn't be able to impersonate Sec anyway because of implants, unless you're already someone with an implant.

Lol

**Comment by nuklearcellphoneg** [comment]
Okay, make it a poll.

**Comment by FudgePucker** [comment]
Fuck you, if the Japanese nantes gets closed without a poll with more :+1: than :-1: you aren't getting a poll for the issue that has been reposted over three times.

**Comment by nuklearcellphoneg** [comment]
I have no clue what you're talking about, but if this has been brought up three separate times it's clearly an issue.

**Comment by FudgePucker** [comment]
A vocal minority is still a minority

**Comment by Blithering** [comment]
Nothing stopping you knocking them out, stripping their headset, ID and PDA and leaving them cuffed to a chair while you go buy a discount chocolate bar

**Comment by DeityLink** [comment]
it's been changed now hasn't it?
