### ISSUE TITLE
You can blow up emagged borgs, even though you should not

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#23297]
#### Description of issue

The code for blowing up an emagged borg is :

```dm
/mob/living/silicon/robot/proc/self_destruct()
	if(mind && mind.special_role && emagged)
		to_chat(src, "<span class='danger'>Termination signal detected. Scrambling security and identification codes.</span>")
		UnlinkSelf()
		return FALSE
	gib()
	return TRUE
```

However, `mind.special_role` isn't used anywhere after role datums.
So, this protection emagged/traitor borgs used to get from being blown up no longer exists.

**Comment by Killette2** [comment]
Wasn't the intended behavior that you could still blow them up with the 60 second blow up countdown that blows all borgs? Otherwise that button has no purpose than a delayed blowing when lock and blow buttons are otherwise instant.
