### ISSUE TITLE
It Ain't Fucking Cheers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23298]
(WEB REPORT BY: originalbubsra REMOTE: 206.221.180.138:7777)
# Revision
1badcae66dfbc06c8217db0c3306f0e381dbcb1c

# Description
Juke is fucked
# Steps to Reproduce
Attempt to play the theme from cheers on the jukebox.
# What you Expected
Making my way in the world today, being in a place where everybody knows my name
# What Actually Happened
some faggot ass music instead

**Comment by Gringonius** [comment]
Sorry but we're not allowed to have a good jukebox.

**Comment by RealestEstate** [comment]
I’m sorry mama, but me and the boys have been drinking again.

**Comment by ghost** [comment]
Pretty sure the jukebox rework happened after this issue was made so it's probably not relevant.
