### ISSUE TITLE
Greytide implants don't drop when cloned nor when de-implanted

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#23302]
#### Description of issue

First one is an oversight, second is technically a feature but a very bullshit one.
(you need to get loyalty implanted to actually drop the role, which makes it impossible for a civilian to "liberate" an implanted dude).

**Comment by ShiftyRail** [comment]
And before anyone draws conclusions, I was a greytide implanted officer in the round in which it happened. Because all of sec got greytide'd.com, civilians couldn't deimplant us because they didn't have access to loyalty greenies.

**Comment by FudgePucker** [comment]
Wait you can remove the implant and use it again and it impacts everyone implanted at one point?
