### ISSUE TITLE
HoP cannot access his own locker.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23305]
(WEB REPORT BY: utilitas REMOTE: 206.221.180.138:7777)
# Revision
854a9d0792df998887759bbddc23e9e9f334a119

# Description
 As a fresh HoP, I cannot unlock my own locker.
# Steps to Reproduce
 Try to open locker.
# What you Expected
 An open locker.
# What Actually Happened
 Access Denied, and remained that way until I made a captain's ID.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
99.9% chance this is a locker that got EMPd and scrambled access also bugreport does not include map

**Comment by Kurfursten** [comment]
Come now, there's at least a 15% chance he put his PDA on his belt slot by accident instead of his ID slot, rendering it useless for opening things.

**Comment by Killette2** [comment]
I vote he left the ID in the computer

**Comment by Zth--** [comment]
This issue lacks so much info it's pretty much useless. Report again if you can reproduce it
