### ISSUE TITLE
Teleporters Don't Seem to Teleport Structures Anymore

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#23301]
Didn't they do this before? You can't send salvage back home with it

**Comment by MadmanMartian** [comment]
odd, they teleport anything that's a child of atom/movable

**Comment by Kurfursten** [comment]
Somehow some trader managed to get a wardrobe *under* the teleportation particles. It showed up properly when I used TH to throw it. I think he bumped it to push it.

**Comment by Kurfursten** [comment]
At some point fixed
