### ISSUE TITLE
Syndicate Nuke Op Shuttle is way too close to the station on roidstation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23330]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
2d0ef0b05ab2e3db3208de34cf2c01764ca647b6

# Description
The syndicate shuttle that nuclear operatives use is way too close to the station in the southern dock, making it pretty much a loot pinata for anyone who takes a walk through space

https://puu.sh/DJU7W/f67d56486c.png
https://puu.sh/DJU7C/6a00727409.png

**Comment by Kharkov72** [comment]
Jesus christ
yeah, I'll move it soon

**Comment by Kurfursten** [comment]
Probably a bad sign for placement if bombing the armory would put your own ship in the blast radius
