### ISSUE TITLE
Horse Head Masks do not allow internals for Plasmamen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23351]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
52c35202e1e9a3c040404d749026129131e1293c

# Description
Getting a horse head mask via wizard results in not being able to use internals. Doesn't seem to be a problem for plasmamen since apparentlyI was still getting air without asphyxiating. However the UI keeps the oxygen warning up and internals are turned off a second after turning them on.
# Steps to Reproduce
Be plasmaman, get horde headed, try to turn on internals. May be particular to mime plasmaman.
# What you Expected
Internals to work
# What Actually Happened
Internals do not work and turn off immediately

**Comment by Exxion** [comment]
That's like half of the point of the spell
Though it is odd that you didn't *actually* suffocate

**Comment by west3436** [comment]
Feature
