### ISSUE TITLE
Latejoining as a trader throws you to fucksnowhere

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23353]
(WEB REPORT BY: koltarius REMOTE: 206.221.180.138:7777)
# Revision
52c35202e1e9a3c040404d749026129131e1293c

# Description
Latejoining as a Trader on Packed throws you to the beach vault
# Steps to Reproduce
Latejoin as trader
End up on a beach
Suprised pickachu face
# What you Expected
To hit the trading station
# What Actually Happened
Ended up not hitting the trading station

**Comment by MadmanMartian** [comment]
it probably spawned between you and the asteroid

**Comment by Durgen** [comment]
feature
