### ISSUE TITLE
Cigs, fags and sparks light tiles on fire.

### ISSUE THREAD

**Issue by Rumiluntti** [d3athrow/vgstation13#23359]
#### Description of issue
Shit's on fire when shit should not be on fire

#### Difference between expected and actual behavior
Smoking a cigarette or having a spark shitting apparatus in your pocket shouldn't turn you into a walkign fire hazard of doom, but it does

#### Steps to reproduce
Make a prox sensor-igniter assembly, arm it, walk around. Eventually 2 spark overlays get together and produce a beautiful baby called "tile on fucking fire"
Or smoke a cig and toss in on the ground.

#### Specific information for locating
Got it to happen more with the prox sensor-igniter sparkmachine

#### Length of time in which bug has been known to occur
Fuck, man. I remember this bug from, like, 2015

**Comment by DeityLink** [comment]
Isn't this the result of plasma being in the air in low concentration? I remember that happening.
