### ISSUE TITLE
Taking a sample from a fully grown and harvest ready diona pod always kills it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23364]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
6240f8430e929871de471670661615b958bcb2e1

# Description

This is another weird botany harvesting bug
# Steps to Reproduce

Use clippers on fully grown diona pod
# What you Expected

To take a sample
# What Actually Happened
Yes, but also it died.

**Comment by MadmanMartian** [comment]
It does the same thing for every level of pod. It's to prevent pod duping.

**Comment by brndd** [comment]
I thought this was intentional. It also does this for mushmen. Seems random though, I've had clipped mushmen shrooms survive.

**Comment by Lunstra** [comment]
Yeah this isn't a bug, they intentionally have low as fuck health to prevent you from making like 500 diona nymphs and lagging the ever loving shit out of the game

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Was this changed recently? Last I checked you used to have about a 50% success rate so you could still infinidiona.

**Comment by Kurfursten** [comment]
Nah, you can still infidiona it can just be bad luck
