### ISSUE TITLE
Plasma is worthless when given to centcomm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23378]
(WEB REPORT BY: bomberharris REMOTE: 206.221.180.138:7777)
# Revision
1bbc8016f2d4de96cd42b6e704e9b75db58fcc0c

# Description
When sending plasma to centcomm, it gives the low miner prices instead of the original prices.
# Steps to Reproduce
Send plasma to centcomm with cargo shuttle
# What you Expected
Enough money to buy 25 shards
# What Actually Happened
Poverty, despite the mining PR saying it didn't touch cargo plasma

**Comment by agentofzog2** [comment]
sneaky coders strike again

but I'm sure the economy rework that will come in 2525 will alleviate this issue
