### ISSUE TITLE
wiz hardsuit gets double-helmet

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#23388]
#### Description of issue
wiz hardsuit gets a helmet object (that they can unequip) but their RIG also has an "extend hardsuit" button
I checked if maybe you could just dupe RIG helmets by unequipping them but nope, it's just this hardsuit
forgot to grab a picture of it but I looted a dead wiz last round, took the helmet off in the shuttle, and whizzed a new one up from the suit

#### Difference between expected and actual behavior
gee bill how come your mom lets you have 2 helmets

#### Steps to reproduce
- spawn wiz scroll
- grab suit
- take off helmet
- extend another one from the suit

#### Length of time in which bug has been known to occur
probably since the "extend helmet" button was added

#### Server revision
ae08d9516507f780a5f265248f27294c597a94bf

**Comment by DeityLink** [comment]
Seems like it was fixed.
