### ISSUE TITLE
Head Transplat Surgery deletes the brain

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23381]
(WEB REPORT BY: agentofzog REMOTE: 206.221.180.138:7777)
# Revision
1bbc8016f2d4de96cd42b6e704e9b75db58fcc0c

# Description
If you reattach the head to a body after it was removed the brain is deleted, showing the body has had it's brain removed
# Steps to Reproduce
get beheaded and have someone try to revive you the regular way
# What you Expected
life
# What Actually Happened
permadeath

**Comment by ghost** [comment]
can confirm this is happening latest revision

**Comment by MadmanMartian** [comment]
heck

**Comment by Blithering** [comment]
You used to be able to get infinite brains by cutting off and reattaching heads, now the opposite is happening. What a world.

**Comment by SGuivenne** [comment]
Was this patched?  Theirs a PR claiming to fix it that was merged but this is still open.

**Comment by MadmanMartian** [comment]
Not sure if this is still valid

**Comment by Cyadox** [comment]
Could not reproduce, and tested many, _many_ times.
