### ISSUE TITLE
Cult swords can be used as ranged weapons

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#23393]
They're SWORDS
Made for MELEE

If you want a ranged cult weapon make it a cult wand or something

**Comment by Irradiation** [comment]
I ded, pls nerf

**Comment by boy2mantwicethefam** [comment]
Goodbye cult sword blood attack
Hello 3-tile stun talisman

**Comment by AI-Is-Rogue** [comment]
If it gets removed, make throwing the blood dagger do the effect instead.

**Comment by DrSnips** [comment]
CULT
GUNS
U
N
S

**Comment by Blithering** [comment]
Counterpoint: swords with projectile attacks are cool

**Comment by DeityLink** [comment]
Sword projectiles are a video game (and other media) staple. You're grasping at straws there.

**https://tvtropes.org/pmwiki/pmwiki.php/Main/SwordBeam**

![image](https://user-images.githubusercontent.com/7573912/60686480-3d807080-9ea9-11e9-80fd-0df4b6760e9b.png)

**Comment by Blithering** [comment]
Also I tried spriting a cult gun @drsnips it didn't turn out pretty at all
