### ISSUE TITLE
paper bins are full-tile after being picked up

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#23394]
#### Description of issue
so I grabbed a paper bin so I could start writing ideas for a play (captain's idea). I got converted to the cult shortly thereafter, so in order to make my little "writing room" look legitimate, I went to put down the paper bin on the table and put a pen and a piece of paper with writing on it on along with it. here's the result of _throwing_ the paper bin onto the table (so that it becomes perfectly centered) and holding the cursor over the _plating_ of the turf:
![image](https://user-images.githubusercontent.com/5942183/60466320-98b92580-9c53-11e9-9917-7696c5a8a3f8.png)

#### Difference between expected and actual behavior
couldn't click on anything else on the turf without alt-clicking first (including the table which I was trying to wrench up to stand and click on the rune underneath)

#### Steps to reproduce
drag a paper bin to your character to pick it up
place it somewhere
try to do anything else on that tile

#### Server revision

ae08d9516507f780a5f265248f27294c597a94bf

**Comment by DamianX** [comment]
Can't reproduce it. Do you remember where you took the bin from? https://streamable.com/rgugz

**Comment by Kammerjunk** [comment]
yeah, it was one of the two in the medbay lobby. took it, put it in my bag, took it out of my bag, clicked a table with it.

**Comment by DamianX** [comment]
Putting it in the bag was key.
