### ISSUE TITLE
Crit disease + internals race = ???

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23409]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
a4d8115ea7dc411d62ca71af0ea4f83494724a60

Just had a round where I spawned in as traitor, but I had also spawned in with a disease as a Plasmaman. The disease put me in crit within 10 minutes. I started with mucus running down my throat and random collapsing. It may have been something else but I want to consider the possibility that it was RNG. 

The main issue is that shortly before my crit there was a biohazard alert but nobody was complaining about the symptoms I was having. I assume this biohazard spawned in with me. However, because I start with internals as a plasmaman, it is unable to spread. Can we make sure that diseases don't spawn with characters that have internals? Otherwise it's a dead-end. This is assuming internals goes both ways, that those using internals can't infect others as internals can't get infected via normal sources.

**Comment by aceedex** [comment]
Lmao nigga got the athsma crit.
Why did we add athsma again?

**Comment by strawberrytan** [comment]
yeah dude you spawned with asthma and died of an asthma attack because you didn't get it treated at all
