### ISSUE TITLE
Disassembling weedkiller grenades leaves a fuel reservoir instead of a grenade casing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23414]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
a4d8115ea7dc411d62ca71af0ea4f83494724a60

# Description
Disassembling a weedkiller gives you two beakers and a fuel reservoir

# Steps to Reproduce
1- Find or order weedkiller grendades
2- Screwdriver it and then crowbar it
3- Get two beakers full chems and a fuel reservoir

# What you Expected
Grenade casing

# What Actually Happened
It gave me fuel reservoir

**Comment by Coxswain-Navigator** [comment]
try just using it in your active hand instead of using a crowbar.
