### ISSUE TITLE
Killgrabs are a death sentence

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#23410]
You have a 5% chance of resisting out of a neck grab
You can't resist out of a kill grab, and you're stunned for 10 seconds every tick

Grab code

/obj/item/weapon/grab/process()

	if(!confirm())
		return
	if(!assailant)
		affecting = null
		returnToPool(src)
		return
	if(assailant.client)
		assailant.client.screen -= hud
		assailant.client.screen += hud

	if(assailant.pulling == affecting)
		assailant.stop_pulling()

	if(state <= GRAB_AGGRESSIVE)
		allow_upgrade = 1

		for(var/obj/item/weapon/grab/G in assailant.held_items)
			if(G == src)
				continue
			if(G.affecting != affecting)
				allow_upgrade = 0

		if(state == GRAB_AGGRESSIVE)
			for(var/obj/item/weapon/grab/G in affecting.grabbed_by)
				if(G == src)
					continue
				if(G.state == GRAB_AGGRESSIVE)
					allow_upgrade = 0
		if(allow_upgrade)
			hud.icon_state = "reinforce"
		else
			hud.icon_state = "!reinforce"
	else
		if(!affecting.locked_to)
			affecting.forceMove(assailant.loc)

	if(state >= GRAB_NECK)
	//	affecting.Stun(5)	//It will hamper your voice, being choked and all.
		if(isliving(affecting))
			var/mob/living/L = affecting
			L.adjustOxyLoss(1)

	if(state >= GRAB_KILL)
		affecting.Stun(5) //Should keep you down unless you get help.
		affecting.Knockdown(5)
		affecting.losebreath = min(affecting.losebreath + 1, 3) //builds up to 3 over a few seconds
		affecting.stuttering = max(affecting.stuttering, 6)
		if(isliving(affecting) && affecting.losebreath >= 3) //if you've been choked for a few seconds
			var/mob/living/L = affecting
			L.silent = max(L.silent, 2)

Resist code

	//resisting grabs (as if it helps anyone...)
	if ((!(L.stat) && L.canmove && !(L.restrained())))
		var/resisting = 0
		for(var/obj/O in L.requests)
			L.requests.Remove(O)
			qdel(O)
			O = null
			resisting++
		for(var/obj/item/weapon/grab/G in usr.grabbed_by)
			resisting++
			if (G.state == GRAB_PASSIVE)
				returnToPool(G)
			else
				if (G.state == GRAB_AGGRESSIVE)
					if (prob(25))
						L.visible_message("<span class='danger'>[L] has broken free of [G.assailant]'s grip!</span>", \
							drugged_message="<span class='danger'>[L] has broken free of [G.assailant]'s hug!</span>")
						returnToPool(G)
				else
					if (G.state == GRAB_NECK)
						if (prob(5))
							L.visible_message("<span class='danger'>[L] has broken free of [G.assailant]'s headlock!</span>", \
								drugged_message="<span class='danger'>[L] has broken free of [G.assailant]'s passionate hug!</span>")
							returnToPool(G)
		if(resisting)
			L.visible_message("<span class='danger'>[L] resists!</span>")

**Comment by FudgePucker** [comment]
What would be the point of a "kill grab" if it didnt kill? 'Oh no they have a choke hold on me, let me just press the resist button and disarm shove them.'
Isn't the current meta to disarm spam and hit with blunt object until crit?

**Comment by small-boss** [comment]
theres a lot easier ways to kill someone who is unable to move for such a long time that their attacker can fully kill grab them.
cable cuffing them and then just killing them in maint would be one option
