### ISSUE TITLE
Ghetto restraints are broken

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#23416]
- When you use a ghetto restraint on someone, it just falls off without doing anything (eg. bedsheets, toolbets, etc)
- food-based restraints don't work at all, you always try to feed people

**Comment by strawberrytan** [comment]
ghetto restraints worked a few months ago for sure but can confirm they just appear at the cuffee's feet

**Comment by SonixApache** [comment]
#23397 related
