### ISSUE TITLE
Tweaks needed to the "stun changes"

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#23415]
#### Description of issue

http://ss13.moe/index.php/poll/193

"Merge it again" and "Merge it again, with some tweaks" have a little over 50% of the votes.
Here are the tweaks I think are needed to make this work :

- tasers should stun for **14**, from 20, rather 10.
- water slip should be unchanged.
- lube slip should be just a few more seconds above water.

Anything else ?

**Comment by boy2mantwicethefam** [comment]
Preferably remove the grace period before collapsing from electrodes as electrodes will be weaker
Or port over the Hippie thing, 2 electrodes to down someone with the first tap slowing a lot and making whoever got shot drop whatever they held in their active hand, but it also has 2 stunprod taps to down someone

**Comment by aceedex** [comment]
If you ask me, a vote or two over 50% aint big enough to re-merge. specially when the "with some changes" options had none of the voters actually give feedback, and having an abstain option at all.

that being said; I enjoy water and lube being as strong as they are. The only stupid part of them is that half the time you can't see where a floor will kill you
