### ISSUE TITLE
Getting auto dionea'd as a ghost

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#2341]
It doesn't ask you if you want to be one or not, it just spawns you as one if botanists harvest a dionea when you are a ghost. It is pretty annoying when you get dionea'd while waiting to be recovered. I know you can disable it using preferences console but still, game should ask if you want to be one or not (like with posibrains.)

**Comment by clusterfack** [comment]
It asks you if you have it set to yes and not always. If you have it set to always it will just put you in it, because you have it set to ALWAYS. This is intended behavior.

**Comment by ComicIronic** [comment]
Unless this is an issue with code not working as intended, it's getting closed.
Preferences are not a bug.

**Comment by ComicIronic** [comment]
PREFERENCES ARE NOT A BUG.
