### ISSUE TITLE
Runtime on inactive photocollector

### ISSUE THREAD

**Issue by utilitas-** [d3athrow/vgstation13#23434]
[runtime][easy]
Revision: 858973dd68b69b5bc564a0ea5a2164b3428fcef5 

Runtime when the photocollector is wrenched down and isn't being blasted by any emitters. Just needs an additional check.

[09:47:33] Runtime in photocollector.dm,35: Cannot read null.len
  proc name: process (/obj/machinery/power/photocollector/process)

**Comment by FudgePucker** [comment]
There should be a method to get these. Also thanks for fixing the small things, a lot of small problems add up to big problems.

I think that these would be neat on a map that is separated by space like taxi, you could send power across space with FRIGGEN LASER BEEMS
