### ISSUE TITLE
mommer mmi somehow uses static human name

### ISSUE THREAD

**Issue by PaulRitter** [d3athrow/vgstation13#23456]
[oversight][bugfix]

dying as a mommer spawns a mmi with your static human name, if you have one set

**Comment by ShiftyRail** [comment]
That's a feature of borgs as well
I don't see what the bug is ?

**Comment by PaulRitter** [comment]
it uses the literal static HUMAN name from your prefs, not your mommer/borg name

**Comment by ComradeDispenser** [comment]
Yeah, that's what borgs do too, I think it's just intended. Why, are you ashamed to be a MoMMI player or something?

**Comment by Ephx1** [comment]
That's a standard feature that's been in the game for years.

**Comment by SonixApache** [comment]
brain type should be a pref tbh

**Comment by PaulRitter** [comment]
it just doesn't make sense to magically have a MMI name Watson Jones pop out of a mommi called R.U.S.T.Y

**Comment by Ephx1** [comment]
Why doesn't it? All MMIs are organic brains.

**Comment by PaulRitter** [comment]
good point
