### ISSUE TITLE
Bluespace Cocktail Shaker

### ISSUE THREAD

**Issue by ComradeDispenser** [d3athrow/vgstation13#23460]
[featurerequest][spriteworkdone][wip][help]
![bluespaceshaker](https://user-images.githubusercontent.com/19643670/60849718-9e61be80-a1b1-11e9-8d77-e8945cf23e2c.gif)

Playing bartender, I got a little frustrated in the fact that while drinking glasses hold 50 units, when you're mixing drinks, in most cases you end up with some odd number like 90 units of whatever you made instead of two full glasses, I also liked the idea of being able to mix more at a time when you're trying to make a lot of the same drink, such as serving large parties.

I had the thought, if we have large beakers, which hold 100 units, just like a shaker, and we have large bluespace beakers, which hold 300 units, why don't we have a bluespace shaker that can hold 300 units too? I even tried to make a sprite to go along with the idea.
![ezgif-1-9f9ee8c21fbd](https://user-images.githubusercontent.com/19643670/60849659-5e9ad700-a1b1-11e9-82a6-18113884f3cc.gif)
Not quite sure how I can get the shaking animation or the in hand version to look as good, there's a lot more at editing those files than I'm used to, but I tried my best to get this one done. The colors are a little off from the normal shaker, because I tried to make it work using the same palette as the bluespace beaker has. Maybe someone else can lend a hand in finishing the idea? 
I'm really not a spriter, just making this was a challenge for me, and when it comes to implementing the thing, I'm not afraid to admit I don't know the first thing about coding. But I thought it could be a neat idea.

Is the ability to have access to a 300 capacity stasis beaker powercreep? Maybe. But it would be fun at least.

**Comment by Kurfursten** [comment]
High level bartending tip: invest in a cauldron, do all your mixing in that, then scoop out drinks.

**Comment by boy2mantwicethefam** [comment]
Good excuse to add more stuff to Research

**Comment by ComradeDispenser** [comment]
Yeah, but using a cauldron isn't as fun as getting to shake the drinks up in a shaker. Muh arrpee!

**Comment by SonixApache** [comment]
bluespace beakers hold 200
LARGE bluespace beakers hold 300 (and require diamonds)

**Comment by ComradeDispenser** [comment]
I'm aware, I did say LARGE bluespace beaker already, not the normal one. 
If the normal shaker is equivalent to a normal large beaker in capacity, I don't see why the bluespace shaker shouldn't hold the same amount as a large bluespace beaker.

**Comment by FudgePucker** [comment]
Also do shakers fit in cyro or grenade casings? If they dont then there is no balance concerns, out side of those bastards in science forcing chemists to have to shake to do chemistry because they need those diamonds for guns.

**Comment by west3436** [comment]
Implemented via #35101.
