### ISSUE TITLE
UI explanation text in weird places all over the screen

### ISSUE THREAD

**Issue by Waismuth** [d3athrow/vgstation13#23462]
#### Description of issue
I seems to have encountered a bug/graphical glitch: When I hover over the items on the screen , like a flashlight in top left corner, or genetic powers on the right top one, the text box with explanation (which normally should be places slightly below when you hover over the item) gets randomly placed all over the map. This started happening after I tried “change color preset” option in the text box menu, the one that changes the text portion of the screen to black. I never had this problem with ui textboxed flipping all over the screen like that so it must be somehow connected with color preset option messing something up

https://i.imgur.com/hHsNtUk.png

Last minute PS: It seems the bug fixed itself, but I did a full reinstall of my byond and its folders like <user>/documents/byond. So either it fixes itself after server restart/new shift or you have to fix/delete some files in your folders

That's how it looks right now for me https://i.imgur.com/fp8vFR7.png

#### Difference between expected and actual behavior
I wanted the text boxes to appear right below the said item, at least that's what I think it's supposed to do

#### Steps to reproduce
log in, click on the "change color preset" option

#### Length of time in which bug has been known to occur
hard to tell, I never fiddle with the text options, but it appeared yesterday 

#### Server revision
64de0c81011da71830969a34a1408f56b46cbcaa 
0bc8557237b1041757eaaf620d7ede656a5723d5 patches

 [<ui>]

**Comment by DeityLink** [comment]
cursed bug
