### ISSUE TITLE
Bug and Hornets do not spawn on defficiency and meta club

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23493]
(WEB REPORT BY: germansanta REMOTE: 206.221.180.138:7777)
# Revision
106e9d17accd7614718b17a92a2df0e547522cab

# Description
Fill the apiary's with beeezz, with vegetables, fruit, and basic plants around them. They never spawn on defficiency and meta club.

# Steps to Reproduce
Make bees with beeezz and a queen bee packet. On defficiency and meta-club.

# What you Expected
Bees to spawn out of hive

# What Actually Happened
Nothing spawned

**Comment by DeityLink** [comment]
:thinking:
