### ISSUE TITLE
You can't emag open abandoned crates in the asteroid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23490]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
106e9d17accd7614718b17a92a2df0e547522cab

# Description
I had a emag, found an abandoned crate while mining, couldn't emag it open.

# Steps to Reproduce
1- Find a abandoned crate while mining
2- Get an emag
3- Try the emag the crate
4- Fail

# What you Expected

Goodies

# What Actually Happened

Dissappointment

**Comment by jknpj** [comment]
Those are from xenoarch and they use an emagproof snowflake kind of locking system.

**Comment by DeityLink** [comment]
Yes you can

**Comment by pedr69** [comment]
or just ask the QM to swipe his ID to open the things
