### ISSUE TITLE
pAI controlled Mulebots can open Resin Doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23502]
(WEB REPORT BY: sybil REMOTE: 206.221.180.138:7777)
# Revision
b83bd5424e8e3d96a4feab14fada68e13e9b61a0

# Description
pAI controlled Mulebots can open Resin Doors
# Steps to Reproduce
be a pAI in a mulebot, interact with an alium resin door
# What you Expected
Resin doors to stop pAI mules like they stop normal people so that building defenses as a lone alium isnt pointless
# What Actually Happened
A pAI mule carrying people/cyborgs through all of my doors so they can attack me and ignore my walls/doors

**Comment by DeityLink** [comment]
Fixed by #30171
