### ISSUE TITLE
New small cage should pacify spiders

### ISSUE THREAD

**Issue by chesse20** [d3athrow/vgstation13#23500]
I put a spiderling into a small cage(that comes with the mouse testing medical supply from cargo)  and then it grew up and nearly murdered me on the escape shuttle becuase it could still attack when it was in the small cage. If you put a spiderling in a small cage it should be domesticated when it grows up.

**Comment by DrSnips** [comment]
>Hold something captive for it's whole life
Baffled when it tries to kill you

**Comment by DeityLink** [comment]
I agree that hostile mobs shouldn't be able to attack from inside the cage though.

**Comment by AutismSpider** [comment]
Domesticated mobs should be its own thing/type of kit

**Comment by DeityLink** [comment]
Pacifying hostile mobs would be an awesome side-job for xenobiologists.
