### ISSUE TITLE
You can't interact with gas cannisters while riding a janicart

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#2351]
Title explains it all, you can't. You can connect a tank to the cannister, you can open the menu but buttons don't respond. I had to get down from the janicart and continue my business on foot. I tried it few more times on and off janicart. You can't use cannisters while you are on a janicart. This happened on Box, just in case map type matters.

**Comment by PJB3005** [comment]
IIRC, canisters use some sort of snowflaky alt to Topic()'s ..(), because 'they wouldn't work in an unpowered room', almost certainly related to this

**Comment by PJB3005** [comment]
This might've been fixed in #4141

**Comment by PJB3005** [comment]
Can confirm, this has been fixed due to #4141

**Comment by ComicIronic** [comment]
Comment if still an issue.
