### ISSUE TITLE
How to cure rats with the palm of your hand

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#23529]
1. see sick rat, examine info says it is sickly
2. pick rat up, examine it in your hand, it is no longer sick
3. put rat down, examine it, it is still no longer sick

**Comment by DeityLink** [comment]
:thinking: sounds like a visual bug. I've manipulated sick rats earlier today and they remained sick

**Comment by Kurfursten** [comment]
It is true though that you can prevent a rat from spewing an airborne cloud by picking it up, probably because it is contained in the mob holder item

**Comment by DeityLink** [comment]
Mobs have to be on a turf to either breath or emit pathogenic clouds, so that's kind of intended.

**Comment by Exxion** [comment]
Mobs definitely do not have to be on a turf to breathe

**Comment by DeityLink** [comment]
to breath diseases they do 
![image](https://user-images.githubusercontent.com/7573912/61185633-deb2b800-a65b-11e9-8735-66a031ffacd7.png)

I meant to "breath pathogenic clouds" and "emit pathogenic clouds"

**Comment by DeityLink** [comment]
Unable to reproduce. The rat probably got cured one way or another.
