### ISSUE TITLE
Weird Spell Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23541]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
31026545d6e2c720ae664194193c128ba09a889e

# Description

My Boo! Sprite is the gygax overload having gotten into the gygax and had superpowers
# Steps to Reproduce

Not sure, presumably have superpowers, use the gygax, and die outside of it at some point later in time???
# What you Expected

To have regular Boo!  Sprite
# What Actually Happened

Gygax overload sprite.

**Comment by SGuivenne** [comment]
Note this only applies in the spell tab on the menu bar, not the spellbook thingy.

**Comment by DeityLink** [comment]
Probably caused by screen object pooling, but pooling's gone so...
