### ISSUE TITLE
pathogenic incubator ui doesn't update when you insert a new dish

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23549]
(WEB REPORT BY: rpaul REMOTE: 206.221.180.138:7777)
pathogenic incubator ui doesn't update when you insert a new dish

**Comment by PJB3005** [comment]
Will probably already be fixed by #23489.

**Comment by DeityLink** [comment]
On the other hand if I fix it that means you'll have to fix a conflict so it's tempting.

**Comment by DeityLink** [comment]
Fixed by #23489
