### ISSUE TITLE
unpowered isolation centrifuge is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23556]
(WEB REPORT BY: rpaul REMOTE: 206.221.180.138:7777)
> click it
> only vial inside pops out
> click it again
Deprived of power, the isolation centrifuge is unresponsive.
> try to add vial
You cannot add or remove vials while the centrifuge is active. Turn it Off first.
> click it again
Deprived of power, the isolation centrifuge is unresponsive.

**Comment by DeityLink** [comment]
You cannot add vials to an unpowered centrifuge. The only bug is the message you get when trying to insert a vial.
