### ISSUE TITLE
Thralls not visible in Check Antagonists

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23579]
(WEB REPORT BY: meetmeindorms REMOTE: 206.221.180.138:7777)
# Revision
cfdcd7d8648b8b664ae10f92557cbd9fcf81653f

# Description
There were many thralls during a round, but none showed up on check antagonists.

# Steps to Reproduce

# What you Expected
A long list of thralls.

# What Actually Happened
No thralls on it.

**Comment by MadmanMartian** [comment]
For some reason, the vampire did not get a faction. This led to the faction that the thralls would be under to not be shown, as they're not considered an independent.
