### ISSUE TITLE
Thralls not showing on HUD or in round end

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23580]
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
cfdcd7d8648b8b664ae10f92557cbd9fcf81653f

# Description
i became a thrall but could not tell who my vampire master or fellow thralls were-they didn't have the box by their head. in the round end report, myself and my fellow thralls did not show up on it either. i ahelped it and both admins said they could not tell either.
# Steps to Reproduce
become a thrall. i was handcuffed at the time, and plasmaman, but i doubt it matters since admins couldnt tell either
# What you Expected
to be able to see my fellow thralls and the vamp and for us to show up in the end round report
# What Actually Happened
the above did NOT happen and while i had my thrall perks like not being scared when looking at master vamp in the dark, i could not tell

**Comment by MadmanMartian** [comment]
for some reason, the vampire didn't get a faction. This led to the thrall and the vampire not sharing a faction.
