### ISSUE TITLE
Janicart Runs on Smart Technology

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23594]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
b450d61591ed9b241f09ade946d6737eb3431e4a

# Description

The Janicart key, despite explicitly being intended to be inserted, works so long as you have it in your hand
# Steps to Reproduce

Hold janicart key in hand, board janicart
# What you Expected

It to not start unless I actually put a key in the ignition
# What Actually Happened

It starts because its like a smart dongle

**Comment by utilitas-** [comment]
It's a feature. That's how it was used originally until someone made it insertable.

**Comment by DrSnips** [comment]
Close this.

**Comment by Exxion** [comment]
Kids these days
