### ISSUE TITLE
Rambler Weight Appears to Break (If Forced?)

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#23590]
>Soul Rambler Migration had 6.25 weight (--5.25) @ 51 players.

That is wrong. Based on the way it has -- and 5.25 lines up nicely with 6.25, I'm guessing it's something to do with the weightloss system. Rambler had been manually forced two times before, and somehow it got penalized a negative amount, resulting in +5.25

**Comment by Kurfursten** [comment]
Update:

ADMIN LOG: Soul Rambler Migration had 10 weight (--9).

From a round with no forced antags. Something is wrong with my weight formula, this one had 24 players. I'm guessing population isn't what I thought it was, basically.

**Comment by DeityLink** [comment]
Weight was reworked.
