### ISSUE TITLE
Aliens can't dab

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23605]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
35d7d378b3838b919c80cc42b5b5b233f416b009

# Description
Can not *dab as an alien
# Steps to Reproduce
Type *dab
# What you Expected
A sick dab
# What Actually Happened
Nothing

**Comment by chesse20** [comment]
dabbing as an alien should give you a one percent chance to gib as a reference to the administration policies of colonial marines (they gib aliens that dab and blow the arm off of marines that dab)
