### ISSUE TITLE
You can fold metal/glass-looking alien boxes into cardboard sheets

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#23603]
Yeah I'm not convinced that this ![image](https://user-images.githubusercontent.com/7573912/61551741-4602aa80-aa56-11e9-8973-bd156a215cba.png) can just turn into this ![image](https://user-images.githubusercontent.com/7573912/61551749-4dc24f00-aa56-11e9-9f89-e683d5ac806d.png)

**Comment by boy2mantwicethefam** [comment]
That's why they're alien

**Comment by MadmanMartian** [comment]
"We don't know how to make it, but we sure know how to break it"

**Comment by SonixApache** [comment]
just
`foldable = null`
in the archeo finds that spawns them or something
