### ISSUE TITLE
dwarf swords should break open crates and do damage to airlocks

### ISSUE THREAD

**Issue by chesse20** [d3athrow/vgstation13#23608]
the dwarf swords don't break open doors or crates but ~~the swords made from kitchen knifes and a welder break open airlocks~~ well i guess they don't anyways so i think the swords made with a forge and and anvil should be strong enough to break open airlocks (and locked crates too so cargo gets a good reason to build the crew swords)

**Comment by MadmanMartian** [comment]
why do the kitchen knife swords open airlocks?

**Comment by DrSnips** [comment]
I bet b*rry is behind this.

**Comment by Dacendeth** [comment]
Cant seem to get the kitchen knife sword to cut through airlocks, at least on test right now.

**Comment by SonixApache** [comment]
I'm 80% sure neither of those is possible.

**Comment by MadmanMartian** [comment]
Yeah, confirmed it. I think they're getting /tg/ flashbacks
