### ISSUE TITLE
Powercreepers spread through space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23614]
(WEB REPORT BY: sybil REMOTE: 206.221.180.138:7777)
# Revision
1f96709e35315fd664237c9b15e3bb2c6d4ee092

# Description
Powercreepers spread through space
# Steps to Reproduce
Holy shit they spread on space turf

# What you Expected
not this holy fuck
# What Actually Happened
unfightable powercreepers in spess

**Comment by ghost** [comment]
And to add on, I think shocking corpses should be disabled. Seeing a person take 4000 burn damage is entertaining at first, but it causes some lag as everyone begins to die to it.
