### ISSUE TITLE
Switch Supermatter Bluespace expansion to the old sprites

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2362]
People think they're supposed to jump on the bluespace the Supermatter creates.  Its retarded.

**Comment by DeityLink** [comment]
I have plans for the BlueSpace Of Death...it'll be pretty

**Comment by DrCelt** [comment]
@gbasood this is not a feature freeze issue

**Comment by NigglyWiggly** [comment]
This isn't a feature freeze thing yeah. 
Why did we change the sprites anyway? they look dumb now.

**Comment by clusterfack** [comment]
I agree, old bluespace or RIOT

**Comment by DrCelt** [comment]
I like nu-bluspace though. It's literally blue.

**Comment by Shadowmech88** [comment]
Someone post a comparison picture, I never saw bluespace before it was changed.

**Comment by ihadtoregisterforthis** [comment]
First thing I did when I saw supermatter was indeed jump into it.
Second time I tried to escape from it by jumping into space.
Last time?
![surviving the end of reality](https://cloud.githubusercontent.com/assets/13305885/12603073/0a1bd124-c48e-11e5-82cb-a5c736d0b4cc.png)


I think I recall seeing the old sprite, and it wasn't very blue.

**Comment by NigglyWiggly** [comment]
Old 'bluespace' was gold and glowy. It was called Supermatter, IIRC.

**Comment by gbasood** [comment]
Is anyone actually going to do this

**Comment by Imagebard** [comment]
Nobody really cares I suppose.
