### ISSUE TITLE
Plague mice can spawn on disconnected station parts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23635]
(WEB REPORT BY: koltarius REMOTE: 206.221.180.138:7777)
# Revision
5dee8676dac43ea4726ec8a8d2a005f77093dfdb

# Description
Plague mice can spawn on non-main station tiles, like perma on asteroid station
# Steps to Reproduce
Spawn as plague mouse
Realize you are in perma with no way to the station
# What you Expected
Bringing Deity's blessing upon the crew
# What Actually Happened
Cucked out of eating the chef's food and spreading aids

**Comment by DeityLink** [comment]
Fixed by #30061
