### ISSUE TITLE
Rebuilding Chemmasters

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#2363]
If you rebuild the chemmaster, it changes its max energy to 100. I think that's supposed to be reserved for an upgrade so.

**Comment by clusterfack** [comment]
>Everyone here calling them chemmasters

Stop triggering me that's not their name

**Comment by nuklearcellphoneg** [comment]
ur right thank u

**Comment by ComicIronic** [comment]
To clarify: the issue here is that using non-base components sets their energy to max, right?

**Comment by nuklearcellphoneg** [comment]
Nah.

Max energy for the Chem Dispenser is set at 50. At roundstart, you can disassemble it and rebuild it, which sets the new max energy to 100.
