### ISSUE TITLE
E-Implant issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23645]
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
5dee8676dac43ea4726ec8a8d2a005f77093dfdb

# Description
I went to the shuttle to blow myself up, Admin turns me into a martian to keep in line with some gimmick, and it removed my explosive implant, completely wasting the 12 crystals i spent on it, and fucking the only thing i had to do as antag
# Steps to Reproduce
>Get antag
>Get E-implant
>Get Badminned into a martian
>Try to detonate implant
>Can't
# What you Expected
To be able to antagonize
# What Actually Happened
The escape shuttle was a japanese hentai with no explosive climax.

**Comment by tayachiya** [comment]
Not really an e-implant issue. It was your previous body that was implanted, is all.

**Comment by SonixApache** [comment]
user error
