### ISSUE TITLE
Mini mining outpost pipe issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23646]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
5dee8676dac43ea4726ec8a8d2a005f77093dfdb

# Description
The mini mining outpost on box has an ore deposit which leads to a  Delivery chute that sends ore to the main mining outpost said chute does not work 
https://puu.sh/DVWq8/1fb160bb2d.jpg
# Steps to Reproduce
use the mini mining outpost
# What you Expected
ore to go into the chute and arrive at the main mining outpost
# What Actually Happened

**Comment by Probe1** [comment]
It works fine just use the lever.

**Comment by kernikov** [comment]
@DeityLink This is no longer an issue.
