### ISSUE TITLE
Mediborgs can't pick up vials for virus curing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23659]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
b27e536b35093cab5f736df005aa16a508b4d2cc

# Description
You need vials for centrifuge, grabber can't get em

# Steps to Reproduce
try to pick up vial
# What you Expected
pick up vial
# What Actually Happened
no

**Comment by ArchSunder** [comment]
also unless you can administer liquid vaccines you can't feed people vaccine either, afaik borgs not pillgrabbing is intended though

**Comment by DeityLink** [comment]
Medborgs have syringes right? They can just inject 5u of vaccine themselves. Vial grabbing is getting fixed though.

**Comment by ArchSunder** [comment]
yeah that'll work

**Comment by DeityLink** [comment]
Actually grabber can pick up vials just fine, I just tried it. Can you get some at a nanomed vendor?

**Comment by DeityLink** [comment]
![grip](https://user-images.githubusercontent.com/7573912/61814962-817fe900-ae49-11e9-81fd-812eaa032f23.gif)

And yes as I checked you can get vials from nanomeds as a borg just fine.

![image](https://user-images.githubusercontent.com/7573912/61815040-a6745c00-ae49-11e9-8c1c-7f9c7bbc24f2.png)

**Comment by DeityLink** [comment]
So after testing I found out that borgs can do virology just fine but for the sake of QoL they can now pick up vials from vial boxes instead of having to reach a nanomed vendor.
