### ISSUE TITLE
noir still does not always take effect on injection

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23662]
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
b27e536b35093cab5f736df005aa16a508b4d2cc

# Description
when injecting a dna block containing noir, it does not always appear the first injection like it should, being a disability and all. instead it only has a chance to, like a superpower.
# Steps to Reproduce
inject yourself with a dna block containing noir
# What you Expected
that it would always show up the first injection
# What Actually Happened
it doesnt, it has a chance like a superpower, rather than acting like a disability like it should

**Comment by utilitas-** [comment]
Feature. It isn't a disability for some reason, and does count as a superpower.
