### ISSUE TITLE
super soakers blow up weldertanks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23661]
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
b27e536b35093cab5f736df005aa16a508b4d2cc

# Description
super soakers blow up weldertanks, this should not happen.
# Steps to Reproduce
shoot a weldertank with a supersoaker filled with water.
# What you Expected
that it would not blow up(it was hit by accident)
# What Actually Happened
it blew up and killed someone. how about nah

**Comment by Kurfursten** [comment]
Includes all beams, e.g.: whips, laser tag, super soaker

**Comment by FudgePucker** [comment]
Hold on, are you telling me laser tag guns can blow up welding fuel tanks?

Time to "accidentally" blow up tool storage round start
