### ISSUE TITLE
Recipe Request: Crab Cakes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23680]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
084c9350535842ff05b62572610f22fed755c38a

# Description

Crab meat is woefully underused at this time, with only the "not-so-immitation crab sticks" as the only product.  At least give us this if not a sushi recipe or something.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by calzilla1** [comment]
I want crab stuffed salmon in my autism sim

**Comment by GeneralVeers25** [comment]
Crab cakes are incredibly based.
