### ISSUE TITLE
Wood siding panels are unavailable outside of mapping(?)

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#23686]
#### Description of issue

You can find these on roid and some other rare places, it's the yellow/gold panel detailing on wooden underfloors.
![image](https://user-images.githubusercontent.com/8468269/61941389-ab472600-af97-11e9-8cb5-a288492a11ca.png)
Doesn't seem to be any way to construct them. I found only one related mention in the code, and that's stuck under a `isgrasstile()` check which is extremely weird.

#### Server revision
3d464aaf1e3345d2a8ee372e7d478af567ab0efb

**Comment by utilitas-** [comment]
The siding panels are all themselves turfs, just partially transparent. All those floors you see on roid, they are actually two turfs stacked on top of eachother. It's really buggy with lighting tiles and probably best left to be revamped as structure overlays/decals instead of outright turfs.

**Comment by RealestEstate** [comment]
why not allow the tile painter to paint decals on wood (and any other) tiles?

**Comment by utilitas-** [comment]
But it can. It can paint anything from /obj/effect/decal/warning_stripes. Those are decals. It simply can't paint the area warning signs and siding panels, which are technically not decals at all.

**Comment by Kharkov72** [comment]
we should make them decals

**Comment by GeneralVeers25** [comment]
We should make them decals, I agree
