### ISSUE TITLE
Rambler Objective May Not Be Possible

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#23684]
I noticed this when I rambled last week and I correctly entered an antag. Check might be borked.

**Comment by Tokanova** [comment]
Working As Intended

**Comment by DamianX** [comment]
Works on my machine. Spawned as an assistant, adminbussed myself as a traitor. Second client logged in as an assistant, frankensteinized, adminbussed as soul rambler. Spoke with the traitor, identified the traitor, checked role panel, success.

**Comment by Kurfursten** [comment]
It might be some weirdness like if they get cloned and your are reffing their old body

**Comment by DamianX** [comment]
That does it.
