### ISSUE TITLE
Spectral Illiteracy: It Came From Virology

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23682]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
3d464aaf1e3345d2a8ee372e7d478af567ab0efb

# Description
Ghosts/Observers can't read labels on diseases. Also, I don't think they can read books, either.
# Steps to Reproduce
>be a ghost
>float over to Virology (there's always a Virologist nowadays)
>look at a labeled petri dish
>can't read it
# What you Expected
to read it
# What Actually Happened
can't read it

**Comment by DeityLink** [comment]
I'm able to read manuals just fine as a ghost
![image](https://user-images.githubusercontent.com/7573912/61924566-af0f8400-af68-11e9-9dfe-fe18163f0469.png)
