### ISSUE TITLE
Immunity Scanner Has no tech levels

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23695]
(WEB REPORT BY: robosperg REMOTE: 206.221.180.138:7777)
# Revision
dbe01311cf0a9af1b10c0505a7c697f6fb0c8938

# Description
The device analyzer can't seem to scan the immunity scanner!

**Comment by utilitas-** [comment]
It's a feature. It's actually a collection of twigs and rocks, a central-space-african divining tool used when coping with disease. The feldspar makes it look a lot shinier than it should.
