### ISSUE TITLE
Plasma contamination bug

### ISSUE THREAD

**Issue by utilitas-** [d3athrow/vgstation13#2369]
Atmospheric suits (both normal and golden variant) do not stop plasma contamination or plasma burning. Same applies to every space suit (except for plasmamen suits(?)). Plasma contamination affects anything in suit_under, shoes and gloves slots, as expected, even while wearing atmospheric hardsuits.
Plasma burns skin through hardsuits as well (sometimes minimal damage, but still displays the message).

**Comment by clusterfack** [comment]
Comic fixed this. Closeable.

**Comment by ComicIronic** [comment]
Fixed in #2681. Reopen if not fixed.
