### ISSUE TITLE
Medbots will inject you with spacecillin even if you have a beneficially marked virus

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#23710]
https://github.com/vgstation-coders/vgstation13/blob/2d28007c770281b89c9e8fa12edc0a8e5df7d8fe/code/game/machinery/bots/medbot.dm

1. Make a beneficial virus 100 strength
2. Get injured via anything
3. Have medbot inject you with spaceacillin because it detects a virus
4. Have eternal fever until you husk

**Comment by Kurfursten** [comment]
"But it's BENEFICIAL" - Antag Virologist

**Comment by AI-Is-Rogue** [comment]
I bet the silicon metaclub is behind this
