### ISSUE TITLE
Photocopiers 2 - 0 AI

### ISSUE THREAD

**Issue by vgrainicorn** [d3athrow/vgstation13#2371]
Even if photocopier surfing is super cheesy I think it would be easily fixed by giving the photocopier health so lasers can destroy it.

But this is 100% broken. I'M GUESSING that by using the copier to enter a new area the turrets aren't told you're there, so they never target you. I wanted to get a recording of it before making the issue so here it is.

http://puu.sh/dKdo2/63e462103a.webm

Featured: A malf Nicole and a crewmember with 5 minutes left to live.

**Comment by ComicIronic** [comment]
No longer an issue, as tested on local. Proper entry procs are called now.
