### ISSUE TITLE
[Feature Request] message boards

### ISSUE THREAD

**Issue by bathosbathtime** [d3athrow/vgstation13#23720]
[featurerequest]
New PDA functions/upgrades that are space Yahoo! answers and space 4chan to go with blackmarket being turned into space craigslist.  Could even have ghosts answer space Yahoo! to help out new players more.
You can currently do space 4chan with newscasters but I would like a dedicated feature for it.

**Comment by Kurfursten** [comment]
I've heard other servers have this (on laptops?) and nobody uses them. Kind of like our requests consoles. You see those used (by one person, they don't even get a reply) once every 10 shifts.

**Comment by kilozombie** [comment]
The only case in which they'd actually be used is if they were roundstart functions on all PDAs, IMO

It *might* not happen but I'd really love if it was implemented and did actually work, and people posted actively

**Comment by utilitas-** [comment]
They should be accessible from PDAs and newscasters alike. By pAIs, too. With anonymity by default.

**Comment by Lokiamis** [comment]
I've wanted an anonymous PDA imageboard for a long time. Shitposting about command staff, gore threads, bait posts.
And of course the janitor would be able to delete posts (for no monetary compensation)

**Comment by tuypo1** [comment]
I would say no anonymous posting if you were to have such a thing but at the very least give heads and sec the ability to see who posted shit

**Comment by kilozombie** [comment]
> I would say no anonymous posting if you were to have such a thing but at the very least give heads and sec the ability to see who posted shit

Literally the whole point would be anonymity

**Comment by tuypo1** [comment]
A truly anonymous message board would be the most powerful tool in the game by a huge margin

**Comment by AI-Is-Rogue** [comment]
I want to see how things would play out if we replaced the common channel with a message board

**Comment by calzilla1** [comment]
Make it so that if you view PDAs to see their (you)s

**Comment by ShiftyRail** [comment]
Solved (in its own way) w/ spesschan.
