### ISSUE TITLE
Gay Noir: Privates Guy - Canceled!?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23730]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
63b1c180425a01d3bbcca946bae9ca9f7f04857c

# Description
Food inflicted Noir effects don't last
# Steps to Reproduce
>Be non-noir
>eat noir food or drink noir coffee
>a dark night...
>IS GONE
# What you Expected
permanoir
# What Actually Happened
tempnoir

**Comment by ghost** [comment]
is feature

**Comment by utilitas-** [comment]
is feature

**Comment by Probe1** [comment]
is closed
