### ISSUE TITLE
Feature request: Lampy on Black Market

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#23753]
In honor of Lamprey being retired for the forseeable future, I would like to request that we get the mascot onto the black market for people to enjoy and pet him. However, I do not have secret repo access and he is on there.
I even made the code for ya to copy paste into the sekrit repo <3

/datum/black_market_item/agriculture/lampy
	name = "Lampy"
	desc = "He's everyone's favorite Lamprey."
	item = ADD PATH TO LAMPY HERE
	delivery_available = list(0, 1, 1)
	stock_min = 1
	stock_max = 1
	cost_min = 250
	cost_max = 350
	display_chance = 70

**Comment by DeityLink** [comment]
forseeable future? as in next week?

**Comment by ghost** [comment]
I believe I was told by the admins that Lamprey was not to be played for a few more months as deadharold is dead and it was being overplayed. Maybe I misheard?

**Comment by Kharkov72** [comment]
Lamprey is not planned to be used again until it is reshuffled

**Comment by DeityLink** [comment]
Lamprey WAS a bit overplayed these past few weeks, and it's planned for a shuffle, but it's definitely coming back. Unlike, you know, Taxi.

**Comment by ghost** [comment]
Still, Lampy a cute.

**Comment by SonixApache** [comment]
dumb

**Comment by kilozombie** [comment]
This really contextualizes how vestigial and confused the Black Market concept is.

It doesn't really fill a niche that isn't already filled, it doesn't have a unique enough loop to stand out above any other illicit act, and at this point it just seems like an excuse to add whatever it is you want without giving it some proper reason to be there.

I mean, imagine if you could only get Lampy through xenobio, a perfectly sensible route. It's thematic, gives an existing job more things to do, and is going to take some degree of directed effort.

This is just... you see Lampy on the Black Market and buy him. Okay?

I've been very ambivalent about Black Market, waiting until you started really rolling out its content, but if this is the best you can do, then you're not coding to make the server better, you're thoughtlessly putting your personalized wedge into the codebase and filling it with so much miscellaneous content that it's more unfocused than a smudged-up lens.

**Comment by ghost** [comment]
Well if we want to shift discussion to black market, currently it's just a toy shop for extended rounds. Let's be real here. With Spess craigslist it will hopefully change to be more player-to-player focused, but the gift shop of random drek will still remain. It's a black market, the sold goods vary a lot.
You do have a point with the typical item being a little unfocused, which is why I removed the portal gun and such in the newest PR so the market will look like so:
>Mushman seeds, skub, emagged nikita, dorkcube.

So it's mostly random, rather shady drek. Lampy fits in perfectly.

**Comment by DeityLink** [comment]
I actually entirely agree with @kilozombie

**Comment by DeityLink** [comment]
Black market will become more interesting when players can sell their own items on it and it becomes easier to access.

**Comment by ghost** [comment]
It's already pretty easy to access, just takes a fair amount of steps.
