### ISSUE TITLE
Recommended Mommi Buff/Balance

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#2375]
Remove the ability for a mommi to see/hear mobs unless emagged.

**Comment by nuklearcellphoneg** [comment]
This is legit. This is my OC idea perhaps jokingly, but it has some legitimate pros, albeit with its own cons. Just to name a choice few:

The mommi purposefully allowed itself to be emagged! I personally have seen a mommi approach a traitor after said traitor has emagged a different mommi. I watched the mommi deliberately approach the human with no reason and calmly wait to be emagged.

Mommis interfering with construction or sabotage: They can't with this. Interfering with a  being's work is against its law. However, if a mommi starts to, say, clean a room of plasma, and a being says, "Don't interfere", and the mommi ceases what its doing, that is essentially involving itself, in a roundabout way, with the goings on of a being.

Mommis are not allowed to communicate with beings; it would seem to me that there is no really good reason for them to be able to see beings either.

**Comment by ComicIronic** [comment]
This got done, so I'll close it.
