### ISSUE TITLE
Blob should probably take a bit longer to start

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#23759]
Blobs themselves can't do a bunch of sabotage because they pop so fast, the crew doesn't have a bit of time to get their bearings.
I think it should take 2-3 more minutes to pop.

**Comment by Kurfursten** [comment]
I warn you, we experimented with this and with experienced players it lead to nightmare levels of sabotage. Even just grabbing a can of plasma to open up multiplies early blob difficulty significantly.

**Comment by ghost** [comment]
Just give crew a gun/blob fighting shipment at 700 tiles or so.

**Comment by Killette2** [comment]
I've opened a plasma canister and/or walled myself in somewhere any time I was a blob. I've also been playing over half a decade so this might help newer players out but will greatly help older ones more.

**Comment by Kharkov72** [comment]
fair
