### ISSUE TITLE
Balaclavas SHOULD be blocking hair, but don't.

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#23769]
Probably a check just checking for stuff on your head and not on your face as well in icon code, but FUCK me if I'm digging through that. 
Balaclavas have `flags = FPRINT|HIDEHAIRCOMPLETELY`

**Comment by Blithering** [comment]
Also on the should hide hair but don't list:
sec helmets
Xenos helmet
chicken suit mask
probably more that I'm forgetting

**Comment by DamianX** [comment]
`/mob/living/carbon/human/update_hair` is only checking whether the `head` piece has `HIDEHAIRCOMPLETELY`. The balaclava is a mask.
Sec helmets were made specifically not to hide hair, don't know about the rest.

**Comment by ShiftyRail** [comment]
Whoops I forgot about masks
