### ISSUE TITLE
Reorganize crew manifest

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#2376]
These jobs have no business being lumped together. At least make supply its own thing. Geneticists are listed twice under science and medical, which is stupid.

![untitled](https://cloud.githubusercontent.com/assets/4674335/5560408/07efde22-8d5d-11e4-9e7a-37119ad97b3e.png)

**Comment by Cisrox** [comment]
Never fixed. Should be a trivial change. Maybe closeable though, because it is trivial.

**Comment by ihadtoregisterforthis** [comment]
Are you really going through every year old feature request to say it should be closed?

**Comment by PJB3005** [comment]
@Cisrox fucking hell _stop_, also you obviously don't understand what a feature request is.
