### ISSUE TITLE
Robolimbs can be repaired with an unlit welder, consuming zero fuel but healing brute.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23776]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
143d55f18e84d042ba1acd66a20cac231e113e77

# Description
Heal for brute damage FOR FREE. How long have the robolimb waifu snowflakes been abusing this...
# Steps to Reproduce
Take brute damage on robolimb
Apply unlit welder to damaged limb
# What you Expected
bro you didn't turn the welder on/bro you're out of welding fuel
# What Actually Happened
free heals, died anyway due to bullet in face

**Comment by beesil** [comment]
pls delete this

**Comment by SonixApache** [comment]
🤔
