### ISSUE TITLE
borers can become real human

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23779]
(WEB REPORT BY: fuzzynut51 REMOTE: 206.221.180.138:7777)
# Revision
a30c539897c1bd96e6e5220d64ab1c8b86bc8988

# Description
If a borer monkey gets turned into a human through genetics the borer player gets put into the human and the borer is left alone
# Steps to Reproduce
put a borer controller monkey into genetics and change the block to human it
# What you Expected
to be either in a human or thrown out of the human
# What Actually Happened
became a real human being

**Comment by SonixApache** [comment]
i believe this is intended behavior for whatever reason

**Comment by ArchSunder** [comment]
real human bean...

**Comment by DeityLink** [comment]
@SonixApache Definitely not intended behaviour and I tested it to make sure it couldn't happen. No idea why it works now.

**Comment by Dacendeth** [comment]
I'm honestly surprised the borer doesn't get nullspaced while making a braindead monkeyman.

**Comment by DeityLink** [comment]
Alright found it, it's on you @brndd https://github.com/vgstation-coders/vgstation13/pull/22693/files#diff-7b93afe828b41277b1c8701f0f6ae62aL51
