### ISSUE TITLE
Bused Cat Magical Abilities

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23780]
(WEB REPORT BY: blindwatcher REMOTE: 206.221.180.138:7777)
# Revision
a30c539897c1bd96e6e5220d64ab1c8b86bc8988

# Description
Last night I was bussed into Salem's body, and given a Mind Projection ability under mutant powers, but the button did nothing both in the UI and in the Mutant Powers tab, it just said I had a 5/5 second cooldown and that never went to zero (and thus was never activated to begin with). I've noticed bused player controled cats have far less interactivity than dogs - for example, cats seem unable to eat food in my experience - and while I do not expect that to be corrected, I think badmins should be unable to grant cats abilities they cannot use. A simple 'that don't work, my dude' response when they try.
# Steps to Reproduce
1. Try to become cat.
2. Give self mind mutant powers
3. See if the cooldown ever goes to zero.
# What you Expected
That either the abilities work, or that cats aren't allowed to be given useless abilities.
# What Actually Happened
The button did nothing. I ain't mad.

**Comment by Probe1** [comment]
Bussssssssssssssssssssssss
