### ISSUE TITLE
Coins acting as screwdrivers, opening vending machines.

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#23783]
What it says on the tin, lately people have been reporting to me that coins, rather than going in the machine, have been acting as screwdrivers and opening the panel.
I haven't seen any runtimes on the matter, so there's probably spaghetti code in there somewhere.
When it was first reported they thought it was something to do with inventory management, with a bag full of coins and one screwdriver, but I couldn't recreate it.

**Comment by Irradiation** [comment]
Change your intent when using the coin, dummy.

**Comment by bathosbathtime** [comment]
Were they using help intent or harm intent

**Comment by aceedex** [comment]
Silly features that seem like bugs are my favorite thing
