### ISSUE TITLE
Swiss Army Knife Hatchet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23781]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
a30c539897c1bd96e6e5220d64ab1c8b86bc8988

# Description
Swiss Army Knife hatchet doesn't work on tower caps
# Steps to Reproduce
use swiss army knife hatchet on tower caps
# What you Expected
wood!
# What Actually Happened
I got this message 
"The stems on this plant are too tough to cut by hand, you'll need something sharp in one of your hands to harvest it."

**Comment by Probe1** [comment]
The fuck a hatchet in a swiss army knife?

**Comment by ghost** [comment]
I'm gonna um like look into this
