### ISSUE TITLE
latejoin as MoMMi when

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23797]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
a30c539897c1bd96e6e5220d64ab1c8b86bc8988

# Description
i want to be the little crab but it's deadpoop and there's NOSCI
# Steps to Reproduce

# What you Expected
my SSRI's to provide some benefit
# What Actually Happened
lmao

**Comment by SonixApache** [comment]
WYCI

**Comment by utilitas-** [comment]
just join as assistant, break into kitchen/robotics/chemistry/xenobiology and make yourself MoMMI spaghetti
also go to N3X15 home of residence and personally thank the autistic fuck for removing MoMMI spawners from the main station because ???

**Comment by ArchSunder** [comment]
> just join as assistant, break into kitchen/robotics/chemistry/xenobiology and make yourself MoMMI spaghetti

I hate myself for not thinking of this

**Comment by Probe1** [comment]
Server policy or whatever.  We don't do late join silicons in general so make an issue about that if it's really what you want.
