### ISSUE TITLE
Emitters Don't Pass Through Windows

### ISSUE THREAD

**Issue by beesil** [d3athrow/vgstation13#23803]
[IT'S LOOSE]

Emitter beams on a tile with a window (regardless of the window's direction) will not continue to the next tile. Tested both normal windows and reinforced, one window and two, emitter beam works as usual without the window. 

![image](https://user-images.githubusercontent.com/23635874/62745865-db240e00-ba1a-11e9-978e-f0c45417d245.png)
![image](https://user-images.githubusercontent.com/23635874/62745874-ed9e4780-ba1a-11e9-9f70-fc9b31dc9cf1.png)

**Comment by Kurfursten** [comment]
I suspect #23706 as the most recent thing to touch beams

**Comment by Kharkov72** [comment]
powercreeper why must you hurt us with each update pr we get
