### ISSUE TITLE
Zombie code is all sorts of gunk

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#23804]
1. be virologist
2. zombie virus myself and die
3. my ghost goes into nullspace when I enter body after leaving
4. chaplain comes and bibles up my NPC zombie (I am currently a ghost, not inside my nullspaced "body")
5. I don't come back with the error message "Royce Focell grumbles for a moment, then begins to decay at an accelerated rate, seems there was nobody left to save."

Why did my ckey stay detached even after the cure? Is bible thumping really only supposed to save player-controlled zombies, this seems like an oversight

**Comment by DeityLink** [comment]
Potentially fixed by #26103
