### ISSUE TITLE
Emitter beam updating is busted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23810]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
5d397b0b53a1322bc3fd45bd9e5fc6b870ed15b5

# Description
Emitter beam updating is busted - won't actually update to hit people.
# Steps to Reproduce
set up massive emitter array
stand in it
cry
# What you Expected
deathbeam
# What Actually Happened
beam that flies over people

**Comment by ShiftyRail** [comment]
Must have been #23803

**Comment by SonixApache** [comment]
it's very fucky - we're reproducing it with 10 emitters, 5 prisms, and a filing cabinet as beamstop (which then stops the beam from hitting people)
