### ISSUE TITLE
Eject Beaker verb on Cryo Cells not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23826]
(WEB REPORT BY: glasseclipse REMOTE: 206.221.180.138:7777)
# Revision
277a76537de9323d1909b9f1d99f45b5e23b7a7c

# Description
Title

# Steps to Reproduce
1. Find a loving wife
2. ???
3. Get rejected

# What you Expected

# What Actually Happened

**Comment by SonixApache** [comment]
because it's a UI option now (?)

**Comment by ShiftyRail** [comment]
The verb was added when the UI was a thing, and it's tied to ctrl-click, and I ctrl-clicked in a recent round

**Comment by Probe1** [comment]
Works on my machine ( I tested it in game on the live, current revision of our code and it works ).
