### ISSUE TITLE
Slimes don't get temperature warnings

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#23822]
Ever since hypothermia was a thing slimes will get frozen in place unable to move, despite being conscious and able to speak. You have no temperature or pressure warnings as a slime, so this totally shafts you and you must sit in place until you slowly die.

**Comment by Kharkov72** [comment]
I don't see the problem

**Comment by Killette2** [comment]
You don't see the problem until you're frozen, that's the problem. By the time you realize you're in a cold place it's too late. You can't sense cold other than by being frozen in place until you die.

**Comment by Blithering** [comment]
Unfairly seems to be a bit of an exaggeration

**Comment by DeityLink** [comment]
This is a disguised bug report that slimes don't get temperature warnings. You should rename that issue.
