### ISSUE TITLE
Remove cult 3 go back to cult 2

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#23835]
We already one TDM mode it's called revs

**Comment by Kharkov72** [comment]
>cult 2
>any better

just wait for the deconversion update that's soon:tm:

**Comment by brndd** [comment]
remove revs instead then

**Comment by Irradiation** [comment]
Woah there, you said the R-word, Damian is gonna show up soon!

**Comment by ShiftyRail** [comment]
Won't fix the 

>bloodstones
>juggers
>pale bodies
>converting through implants

And counting
Remove research and bring back cult 2

**Comment by DeityLink** [comment]
Cult 2 was worse on almost every level, I agree with @brndd let's remove revs instead lol

**Comment by BomberBro** [comment]
stunning and brave

**Comment by boy2mantwicethefam** [comment]
based

**Comment by Allspice** [comment]
does the juggaloo bitching still have merit after the charge got doinked

**Comment by SonixApache** [comment]
i think cult3 is good, though i think some more objectives might be better

**Comment by DeityLink** [comment]
There's definitely room for improvement, and I think it'd be healthier for the game to move forward and explore new mechanics than go backward because "it was (debatably/not really) better before".

**Comment by PaulRitter** [comment]
+1 for removing revs
or at least make then more interesting, there was talk that a successful rev round would trigger a dorf round(if we ever automate it)

**Comment by agentofzog2** [comment]
Fix revs so they won't just keep revvin after all the head revs are dead when?

**Comment by SonixApache** [comment]
Also, I don't see how replacing asymmetric TDM with the old clunky dodgeball mode would somehow be an improvement.

**Comment by ShiftyRail** [comment]
Cultists are indeed unable to reproduce

**Comment by SonixApache** [comment]
other way around really
a cultist can asexually create another cultist in less than a minute
secmains on the other hand are a dying race
