### ISSUE TITLE
Standardized Procedures for dealing with Antag Book?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#23837]
How about an in-game manual to dealing with antags for security, command, and borgs? Call it "The Hostile Entity Nanotrasen-Typed Aggravation Intel", or HENTAI.
The book would give procedures to dealing with various antags, like how security should handle implanting cultists during act II and how to combat blobs. The book would help newer players deal with antags and would also clarify what amount of info we have on antags for RP reasons. 
As an AI, you currently get a lot of leeway for deciding what is human harm and what isn't. Do you know whether a cult conversion is human harm, or can they law 2 you to keep quiet about their activities? Things like that ought to be clarified too.

**Comment by boy2mantwicethefam** [comment]
Some clarification for stuff and some updated standards would be nice, but neither the headmins nor the host ever bother with server policy nowadays
The way I see it, converting people is only human harm if the person is turned into a box, but reporting cult activities will lead to human harm as cultists have to be killed, but as with the previous it can fall into muh potent ham territory. Besides, why wouldn't you help antags as a roundstart silicon? You're a criminal borged against their will
You should call it the Penned Enumeration of Nanotrasen Uncooperative Savages, or PEoNUS, get it it's a peanus weanus reference can't spell reverence without reerence

**Comment by Blithering** [comment]
Well since titles are being thrown about I vote for Boarders, Infiltrators, Genestealers and Traitors. Identification, Disposal and Defending Yourself Grand Order of Theological Historians Gathered Facts. While it seems long I wager every spessman will want a BIGTIDDYGOTHGF of their own

**Comment by Probe1** [comment]
What do you want clarified @boy2mantwicethefam

**Comment by west3436** [comment]
Implemented in #34643.
