### ISSUE TITLE
[Meta+Box] Supermatter Chamber

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2384]
Nexis made the tiles properly simulate atmospherics for the barrier between the supermatter control room and supermatter chamber. However since the chamber starts out devoid of air once it is opened air will rush into the chamber and pull every object in the room.

Therefore it would be useful if the room was filled with 101.3 kpa of nitrogen to prevent airflow

**Comment by dylanstrategie** [comment]
Airlock needs to be changed to make air unsimulated

**Comment by clusterfack** [comment]
That is precisely what we undid before. Because muh realism.

**Comment by Cisrox** [comment]
Pretty sure this doesn't happen anymore, should be closeable.

**Comment by PJB3005** [comment]
We just had a report come in 17 days ago and I have not seen any fix for this.

**Comment by Probe1** [comment]
Why pure nitrogen specifically and not regular air?

**Comment by clusterfack** [comment]
Cant you read the no O2 sign printed clearly on the floor outside of it?

**Comment by Probe1** [comment]
I didn't go to clown college to have a sign tell me how to think!
