### ISSUE TITLE
Quick Idea Poll: "Syndie Traitors now use their uplink to call a drone near the station to deliver their stolen objectives to the Syndicate instead of just carrying them at round end"

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#23845]
I've got a few different ideas on how the drone would work specifically, this would open the door to new objectives being given dynamically without having to request admins for them, and alleviate the issue of traitors doing nothing at all once their objectives are completed.

Obviously this won't punish traitors who just wish to ignore their objective to do whatever gimmick they had in mind.

**Comment by Killette2** [comment]
How fleshed out is this concept? Can you give anything to the drone even if it's not an objective? How long do you have to wait and will you have to hunt down the drone after it spawns or will it come to you?

**Comment by DeityLink** [comment]
1. Open uplink, "call delivery drone" button at the top, you have to specify coordinates that are in the space area.
2. Drone uplink gives you a timer, You can cancel the rendez-vous at any point.
3. The drone either teleports in or paths from the edge of the Z level, if you set the destination at an airlock you won't need a spacesuit as it's dense and will prevent you getting sucked out. you use the items on it to load them up
4. You either use your uplink or the drone itself to dismiss it
5. Drone call goes on cooldown. You get a message from the syndicate to acknowledge your delivery, potentially reward you, and/or giving you new objectives

Also the drone could potentially have a cloak so it's barely visible unless you're near it.

**Comment by DeityLink** [comment]
>Can you give anything to the drone even if it's not an objective?

Maybe. Obviously you can't give the nuke disk for reasons, maybe some resources could net you points even if they aren't specific objectives. Or getting the captain's uniform would net you points if you ship it along with the HoP's uniform that was your actual objective. I'm not yet set on that specifically.

>How long do you have to wait and will you have to hunt down the drone after it spawns or will it come to you?

I was envisioning the wait to be something between 5-10 minutes (could be more or less) that you could cancel if you realized that the area might have witnesses. You specify the specific coordinates for the drone to come in, and it tries to path there from the edge of the Z level, but it has to be in space. If it cannot path in, the drone will send an error message and request you to try again on a lower cooldown.

**Comment by ShiftyRail** [comment]
There is no fixing objectives in their current form

**Comment by boy2mantwicethefam** [comment]
Make it so it gives you more TC

**Comment by DeityLink** [comment]
@ShiftyRail That's what I'm doing though.

@boy2mantwicethefam that's a possible reward, I think someone had counter arguments to it though.

**Comment by SGuivenne** [comment]
People want to say objectives can't ever be fixed to support their idea of antag changes.  I don't get it personally.

**Comment by FudgePucker** [comment]
What would be the problem with having the nuke disk be givible to the drone? Just let the nuke ops buy it for 0 TCs if it was sent back and send a PDA message to who gave it to the drone saying "GET OUT" when ordered by the Ops.

**Comment by boy2mantwicethefam** [comment]
Shifty wants jecties to be removed so that he can yell at people for murderboning, the server has been in a downward spiral RP-wise since the ssethtide that none of the 3 people that can do anything about it are doing anything about it, and he thinks that if antags are more restricted in how they play (eg. no murderboning, keep in mind other people's fun when antagging, maybe other things) it will make the dead cat bounce when all it would take is yelling hard enough at any of the 3 people to do something about the current state of the server

**Comment by DeityLink** [comment]
People will stop murderboning if we give them something more fun to do instead.

**Comment by DeityLink** [comment]
@FudgePucker and deny the Ops the fun part of their mission? aka "getting the fooking disk"? Maybe something can be done but it has to be more elaborate.

**Comment by Allspice** [comment]
@boy2mantwicethefam Not seeing where in `Solo antags no longer have defined objectives, and instead are just told to do what they want` the crackdown on antag freedums is

**Comment by Killette2** [comment]
Idea dump, but I'd like a one time TC bonus for turning in your objectives. The drone could then encourage a traitor to emag a communications console to talk to admins for a further objective. The drone gives you an emag to do so, but a variant that only works on communication consoles. When messaging the syndicates for objectives admins get 1 minute to accept that they want to give another objective, and then has time to write it customly, or the traitor gets another random objective just for bragging rights.

**Comment by incakola** [comment]
does it cost any TC to request the drone?
Should buying loads of gear force you to hold onto your objectives until the shuttle (which is riskier than dumping it on the drone halfway through a shift?)

does the emergency shuttle calling/arrival/dispatch influence the drone flightplan?
or any other shuttles or cult behaviour?

I mentioned in another one of your discussions about this same idea that you could explore sending traitor objectives on the cargo shuttle (which promotes cargo interaction?)

**Comment by DeityLink** [comment]
>does it cost any TC to request the drone?

no. wouldn't make that much sense either since TCs are meant to allow the bluespace teleportation of uplink items to you, while here you're requesting the arrival of the drone from space.

>Should buying loads of gear force you to hold onto your objectives until the shuttle (which is riskier than dumping it on the drone halfway through a shift?)

I'm not sure I follow, what gear? uplink items? Why would you have to hold onto your objective until the shuttle?

>does the emergency shuttle calling/arrival/dispatch influence the drone flightplan? Or anything that changes turfs?

If you call the drone in the shuttle landing area and it arrives before the shuttle arrives, the drone will be destroyed which will put it on cooldown (objectives are only marked as complete when the drone exits the Z level with them). If the drone arrives after the shuttle has docked, it'll be unable to path to the location (which is no longer space) and send you the same message as if you had given a coordinate that isn't space in the first time. I might allow the uplink to let you change the rendez-vous coordinate until the drone has made it to the station.

Cult ACTs won't affect the drone in the slightest.

>I  mentioned in another one of your discussions about this same idea that  you could explore sending traitor objectives on the cargo shuttle (which  promotes cargo interaction?)

I don't dislike the idea but there are too many cons:
* no one else currently uses cargo to ship items to centcom aside from cargo themselves so that'd be highly suspicious
* the traitors now rely heavily on cargo functioning properly.

In practice it'd be doable, but from a meta standpoint I don't see it working.

**Comment by incakola** [comment]
I meant that calling the drone costs nothing and there is no drawback/risk apart from being seen interacting with it.

If it costed TC:
- a traitor who spent all their TC (and would likely have a lot of powerful items) would have to manage keeping their objective items on their person until round end for their greentext.

- traitor who uses their TC frugally could use some to call the drone but then have less TC for traitor items

"Do I call a drone and secure my greentext?" vs "do I get more traitor items but keep my objective on my person?"

Though making the drone cost TC isn't a guarantee to make the game more interesting.

Re cargo shuttle: Correct and Correct. It would be a much bigger task that doesn't get ruled out by the drone implementation. Both can be done separately. Maybe CargoDatums can make it the free version of the drone.

**Comment by DeityLink** [comment]
>If it costed TC <etc>

Yeah those are both things I'd like to avoid, hence more reasons for it not costing TC, being seen interacting with it is enough of potential risk to me, and I really don't think that it costing TCs adds anything of value.

And yeah, more traitor-cargo interaction can be implemented down the line, but that's a tangent to the concept at hand.

**Comment by ArchSunder** [comment]
If we do keep jecties and (target silent round removal -> escape quietly during crew transfer/emergency) memes do continue, then what about delivering the corpse/head of your jectie target to the drone for a kill confirmation, reward or something. I'm not sure if you'd actually have the drone fly away with the body or not, but maybe it could "scan" the body. 

The drone sounds like a fun feature to have anyway. Maybe if jecties do get removed the drone could still take high value items for rewards.

**Comment by MisterStaub** [comment]
Big fan of the idea as it could branch out into a whole ton of new shit for traitors, interested in seeing what comes of it should it become a thing

**Comment by DeityLink** [comment]
@ArchSunder That's definitely something I've been considering. Ideally the drone would serve as some way to diegetically confirm your objective to the syndicate. You could also send a photograph featuring them being dead (since photograph actually contain such data)

**Comment by DeityLink** [comment]
So objectives are gone for now but I'm not giving up on this one. There are three ways I see it happening:

1. You use your uplink to get stealth/assassination objectives, and call the drone to deliver the items/proof of your murder
2. You use the drone to get objectives AND deliver the results (which means you call the drone a first time without giving it anything, just to get the objective(s)
3. You call the drone to just dump any stolen items/proofs of kills for "points" and there's a leaderboard maybe. I don't like that one since no objective limit means that people will just always murderbone and steal the same items across the whole station each time.

So obviously I prefer the first one, but what about you.

**Comment by Blithering** [comment]
1 sounds good, maybe have an end round screen section with items stolen and who did the deed, so there's at least some confirmation you did something.

**Comment by DeityLink** [comment]
Reposting from #23986 , here's a system that allows drones to give us an objective system that should satisfy most people :

1. You use your uplink to request an objective, can be random, or from a category (steal, assassinate, harm, subvert), along as an either random or set difficulty level (harm an assistant / steal a stamp -> kill the HoS / steal a deadly virus sample) You can only have one active requested objective at once.
2. Once your deed performed, you use your uplink to call the drone and rendez vous with it to deliver the stolen item / proof of the deed (in the case of harm / kill, it could either be a severed limb or simply a picture of their dead body if you don't want to remove them from the round)
3. The drone then leaves the station, and once it exits the Z level, your objective is marked as successful, and your uplink allows you to pick another objective. No specific rewards.
4. Repeat 1->3 as many times as you wish.

**Comment by Kammerjunk** [comment]
unimportant opinion from a non-player, but I've been convinced that this is a pretty fun idea after the thread first brought up the issue of the (usually unique) item being permanently gone from the round after being fetched and then solved it by suggesting that they appear on the black market and that sec could fight the drones with devices of their own
it's a cool way to tie it in with existing systems, "encourages" confrontation between sec and tators, and keeps stuff like the pinpointer or the blueprints in the game

**Comment by DeityLink** [comment]
Yeah I read lots of very good suggestions from the thread. It's best when features are linked with each other like that.

**Comment by MadmanMartian** [comment]
If anyone can drum up a syndicate sprite for a drone, I can code this today

**Comment by DeityLink** [comment]
I've already started both spriting and coding it 
![image](https://user-images.githubusercontent.com/7573912/64035552-60e63580-cb51-11e9-8cbf-c5a029b760b1.png)

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/64035575-6cd1f780-cb51-11e9-8983-200112f831c4.png)

**Comment by MadmanMartian** [comment]
Oh dang

**Comment by MadmanMartian** [comment]
I'll race you to it!

**Comment by DeityLink** [comment]
please don't

**Comment by Kammerjunk** [comment]
what'll be the deal for all other objectives than steal? objectives that can't be verified by a hand-in, possible future objectives that can't be verified at all - I'm sure people might still want more objectives once they complete (or "complete") those

**Comment by DeityLink** [comment]
I described how to verify assassination/harm objectives a few posts above. Other ways could be added to verify things such as a singuloose or a subverted silicon

**Comment by SonixApache** [comment]
repost from the thread discussions:
Having delivered items show up on the black market would be a good addition.
Jobbies can pay a premium to get their stuff back, other people can pay a premium to get good stuff, security can pay a premium to have a chance at getting fibers / prints off the stolen goods.

**Comment by DeityLink** [comment]
@SonixApache 

![image](https://user-images.githubusercontent.com/7573912/64040972-7a41ae80-cb5e-11e9-8983-c186c483d187.png)

**Comment by MadmanMartian** [comment]
we're still working on this one, probe

**Comment by Probe1** [comment]
Sure, sorry for being overzealous.

**Comment by DeityLink** [comment]
I might rework the concept later now that freeform objectives are a thing, and R0B0 isn't actively working on it anymore.

**Comment by SonixApache** [comment]
for the record - throwing a Security Alerts Computer alert as soon as one of these drones departs might be an idea
