### ISSUE TITLE
Concrete Plating Tile Graphics Problem

### ISSUE THREAD

**Issue by plosky1** [d3athrow/vgstation13#23847]
#### Description of issue

Concrete snow tile in dreammaker appears as regular plating in actual server.

#### Difference between expected and actual behavior

![dreamseeker_tKxAUmNP6f](https://user-images.githubusercontent.com/1761674/62889156-5d0b8400-bd06-11e9-888e-a5e722104532.png)

![dreammaker_hK0FVG8seg](https://user-images.githubusercontent.com/1761674/62888947-fab28380-bd05-11e9-915c-bae6a2984d67.png)

#### Steps to reproduce

Use /turf/simulated/floor/plating/snow/concrete in dreammaker, then run a server.

#### Specific information for locating

/turf/simulated/floor/plating/snow/concrete

#### Length of time in which bug has been known to occur

Unknwon

#### Server revision

[consistency]
[snowmap]

**Comment by ShiftyRail** [comment]
That second screenshot appears to be from the editor itself
Screenshots from editors look bad because wallsmoothing and other things is done directly in game.

**Comment by plosky1** [comment]
Right, the problem is the concrete floor icon is completely different, and for whatever reason it's being shown as a regular floor plating tile.

This is what it shows up as in dream-maker and in the floor.dmi

![dreammaker_KTq0r8L9jX](https://user-images.githubusercontent.com/1761674/62891882-83ccb900-bd0c-11e9-9cd6-a1ee3ff87be5.png)

**Comment by kilozombie** [comment]
I don't know because I haven't checked but usually things reverting to plating is because they have a New() or similar proc that changes their icon_state to something specific, but because their newly set Icon doesn't have that icon_state, it breaks and becomes plating

**Comment by Kurfursten** [comment]
this was fixed
