### ISSUE TITLE
Icons in xenoarch papers (Spectral signature) are broken

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#23851]
![1565736124977](https://user-images.githubusercontent.com/25846834/62982498-54947580-bdfa-11e9-9b5b-f4dd05ed3ad8.png)

bottom text

**Comment by ArchSunder** [comment]
i miss those graphs

i'm 1 out of the 1 people that likes to keep those papers in a little folder when im looking for big artifacts

**Comment by west3436** [comment]
Ancient xenoarch machines are no longer required, mapped in, or supported
