### ISSUE TITLE
You cannot kick while handcuffed

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#23852]
That's dumb

**Comment by bathosbathtime** [comment]
We do have leg cuffs so moving the kick restriction to those and bolas wouldn't be a crazy idea

**Comment by Kharkov72** [comment]
#23255

**Comment by DeityLink** [comment]
>on Jun 14
>27 :+1: 

and why is that PR still open exactly?

>two small changes requested still not performed

welp

**Comment by FudgePucker** [comment]
The only good part of this is that it gives you an excuse to field execute and dispose of bodies after they start spamming bites and kicks at you while you take them to brig. Which is everytime.

Also leg cuffs are terrible

**Comment by DeityLink** [comment]
Funny how my opinion on the matter has done a 180° over the past two years.
