### ISSUE TITLE
Slime Tiles r Fucked

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#23868]
They are supposed to make slime people go WOOOSH and normal people sticky and super slow, but you see in the code that it sets the slime person modifier to 5 and the normal person modifier to 0.01. It should be the other way around since lower values are faster.
Too lazy to fix it, dont (You) me

**Comment by Killette2** [comment]
Also rabid slimes, unlike normal slimes, aren't affected by slime tiles. Fix this too pl0x

**Comment by Zth--** [comment]
Fixed here #23877
