### ISSUE TITLE
Snow-taxi station no shuttle for miners

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23879]
(WEB REPORT BY: jakedb REMOTE: 206.221.180.138:7777)
# Revision
49089b7f224331468ba203bc3f27d3bebf810bf7

# Description
There is a shuttle for the mining cave, miners can't access it. 
# Steps to Reproduce
???
# What you Expected
To get to the usual mining place
# What Actually Happened
I didn't

**Comment by plosky1** [comment]
Miners are meant to use the same shuttle as the research since it's a combined station. I've just re-checked access and miners already have access to both doors and the shuttle.
