### ISSUE TITLE
(Snow) Footprints are uncleanable and show up over anything you build on them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23878]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
49089b7f224331468ba203bc3f27d3bebf810bf7

# Description
They are unstoppable.
# Steps to Reproduce
Make footprints in the snow
Build wooden wall/floor over them
# What you Expected
Footprints to not be visible
# What Actually Happened
Footprints visible on top of everything and are unsoapable, big mess

**Comment by Lokiamis** [comment]
Would be nice to be able to kick them or use a snowball on them to cover them up
