### ISSUE TITLE
Exosuit fabricators in robotics lose the button to make robot parts under certain conditions.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2388]
After a lot of experimenting and feedback in the thread, I'm submitting what I've found.  

The exosuit fabricators tend to semi frequently "lose" parts when using either the sync button or the quick X button.  A common iteration of this is the roboticist will hit Quick Robot and the right leg won't be added.  On consulting the robot parts list, it's no longer there.  With enough finesse and syncing, you can get it to reappear AT THE BOTTOM of the part list.  However when added to the queue or built directly, it will produce something other than a robotic right leg.  

The only solution to this is to unscrew/crowbar disassemble the exosuit fabricator, rebuild it, then resync it to the network.  Which sucks.  Really bad.  

This needs a lot more investigation but I would start with repeatedly syncing it and using the quickbuild button.  I've noticed this bug occur both when quickbuilding robots and Odysseus mechs.

**Comment by ComicIronic** [comment]
Our current system does use designs for all fabricators. The PR which unified them was #1773.

**Comment by clusterfack** [comment]
TG has a number of large-scale fixes to exofabs that promise to fix the current issues if we port them.

**Comment by d3athrow** [comment]
This should have been fixed, please test again.
