### ISSUE TITLE
Being blind via radstorm when not blind on screen disallows inspection

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23899]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
c6e131fd659f79d85b6d1c79571679a4f20b82ad

# Description
Add on to the blind issue where regaining it via rad storm doesn't work, being 'blind' like this lets you see everything but still acts like you can't on inspecting

# Steps to Reproduce
Get blind, fix it, stand in radstorm
# What you Expected
Blindness
# What Actually Happened
Semi-blindness where you can see everything and the game thinks you can't

**Comment by Exxion** [comment]
The bug is that you could see while you should be blind, which you already reported separately
This part isn't a bug
