### ISSUE TITLE
Ramming locked lockers with shuttle deletes them from reality

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23897]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
c6e131fd659f79d85b6d1c79571679a4f20b82ad

# Description
Shuttle ramming a locker just gets rid of it entirely

# Steps to Reproduce
Put shuttle in path of ship. Summon ship.

# What you Expected
It does nothing or breaks it open.

# What Actually Happened
No locker.

**Comment by Exxion** [comment]
Pretty sure it *is* breaking open the locker but then hitting and destroying everything inside too, as intended

**Comment by Probe1** [comment]
Intended.
