### ISSUE TITLE
Dionae can use blackmarket uplink

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23904]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
c6e131fd659f79d85b6d1c79571679a4f20b82ad

# Description
Dionae can use blackmarket uplink
# Steps to Reproduce
Be dionae, use it
# What you Expected
''You don't have the dexterity to use this'' like nearly all other machines
# What Actually Happened
Uses it no issue

**Comment by Kharkov72** [comment]
nymphs steal shit, nymphs sell shit, makes sense to me

**Comment by SonixApache** [comment]
nymph niggedry should not be promoted
