### ISSUE TITLE
Odd behavior of passive vents

### ISSUE THREAD

**Issue by Novakza** [d3athrow/vgstation13#2390]
I decided to replace the unary vents in the supermatter chamber with passive vents, which resulted in some weird behavior. Namely, cold fire everywhere.
![screenshot 2014-12-27 18 39 49](https://cloud.githubusercontent.com/assets/6424768/5563031/0d292ac0-8e06-11e4-8058-5b9e4bb45fa7.png)
The specific method of doing this was to wrench off the reinforcement, wrench off the vents (which I shut off by turning off the APC), reinforce the floor, then place 2 passive vents and wrench them down.
I then constructed a few other things, which I'll attach.
![screenshot 2014-12-27 18 41 48](https://cloud.githubusercontent.com/assets/6424768/5563034/592fa700-8e06-11e4-9621-b7786b53732c.png)
![screenshot 2014-12-27 18 42 47](https://cloud.githubusercontent.com/assets/6424768/5563036/5ddb4ea8-8e06-11e4-8b98-ed6cf869a881.png)
![screenshot 2014-12-27 18 43 34](https://cloud.githubusercontent.com/assets/6424768/5563037/614387d6-8e06-11e4-93b9-0a9feb5c82ab.png)
![screenshot 2014-12-27 18 44 03](https://cloud.githubusercontent.com/assets/6424768/5563038/636a65f2-8e06-11e4-9334-36143636ec15.png)

Now comes the weird behavior, I turned on the emitters just fine, with no issues; 
![screenshot 2014-12-27 18 46 44](https://cloud.githubusercontent.com/assets/6424768/5563039/77761eb0-8e06-11e4-9351-337ead01d961.png)
However, I forgot to wrench down the N2. I immediately did that, and the emitter sparked shortly after, resulting in an explosive plasma fire that burned cold.
![screenshot 2014-12-27 18 47 23](https://cloud.githubusercontent.com/assets/6424768/5563040/8dadfa72-8e06-11e4-99ad-d56983230eab.png)
![screenshot 2014-12-27 18 47 26](https://cloud.githubusercontent.com/assets/6424768/5563041/8ffa84d0-8e06-11e4-8978-5b329364cc08.png)

My best guess is that some weird interaction with the passive vents leaked oxygen and plasma into the room, which ignited.
At this point I re-tested, and could reliably reproduce the results by doing what I did above.
I chose to try to isolate things, though, and tested two possible fixes: blocking the door with a wall and NOT re-reinforcing the floor.
![screenshot 2014-12-27 20 26 48](https://cloud.githubusercontent.com/assets/6424768/5563051/e1fb5dfe-8e06-11e4-8487-afb112bef47f.png)
At this point the supermatter was safe.
I'm not at all sure how or why, but it may be related to the reinforced floors. That'd be pretty weird though. I'm not sure what else to test unfortunately, since I don't really understand the supermatter; ran across this while trying to learn howe 2 supermatter.

**Comment by Probe1** [comment]
Bug still exists.
