### ISSUE TITLE
Map Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23913]
(WEB REPORT BY: jadinthedog REMOTE: 206.221.180.138:7777)
# Revision
ffc3fd9e1677bee3f22e8cec8cdff8bc1d9cf46c

# Description
There is no way to reach the back right table and virus food dispenser

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment]
This is probably from Snaxi by the way

**Comment by Probe1** [comment]
Just checked.  It's not dense and its fixed.  Viro could use some work map wise but this issue is resolved.
