### ISSUE TITLE
Creating floors on snow causes atmos fuckery

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#23914]
#### Description of issue
When creating flooring on snow, the tile loses atmosphere briefly and hurts you.

#### Steps to reproduce
Rods on snow, floor tile on snow

**Comment by Kharkov72** [comment]
tested, when the plating is created on a snow tile, it has 0 atmosphere.
not really sure where you would look to fix this

**Comment by Exxion** [comment]
It's good old `ChangeTurf()`
I don't remember for certain whether or not it copies the air of the old turf into the new turf if the old turf is simulated, but if the old turf is unsimulated, it just doesn't bother and spawns the airless version of the new turf, if memory serves

**Comment by ghost** [comment]
I will fix this and have it grab unsimmed atmos
