### ISSUE TITLE
[gamebreaking] wintercoats don't fit on wooden coat racks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23910]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
ffc3fd9e1677bee3f22e8cec8cdff8bc1d9cf46c

# Description
comfiness: destroyed
# Steps to Reproduce
apply wintercoat to coat rack
# What you Expected
coat on rack
# What Actually Happened
coat in hand

**Comment by Lokiamis** [comment]
Was just about to add this issue

**Comment by Blithering** [comment]
Just doublechecked my old snow coat files, this was definitely sprited back in the day at least.
![coatrack](https://user-images.githubusercontent.com/15067109/63285549-e1817800-c2ad-11e9-9506-1b3b0dc2aa7a.png)
