### ISSUE TITLE
Stun gloves stun you on every action regardless of intent, or try to

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23922]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
6367af1c45e308bd7d5852037e1eee2922b71544

# Description
They stun all the fucking time
# Steps to Reproduce
Equip, any intent, click people or yourself with empty hand
# What you Expected
They only stun on harm
# What Actually Happened
They stun on any intent leading to weird shit like trying and failing to stun yourself on inspection or stunning then helping a guy up immediately in the same click

**Comment by MadmanMartian** [comment]
Who knew making your hands deliver stunning shocks then touching yourself would be a bad idea

**Comment by Dacendeth** [comment]
Feature.

**Comment by Probe1** [comment]
Intended
