### ISSUE TITLE
Janicart Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23933]
(WEB REPORT BY: ratstar REMOTE: 206.221.180.138:7777)
# Revision
0ea7e80db17af7f2a68fd12a1bce93535387ce02

# Description
Janicart no longer works, you can not buckle yourself onto it.
# Steps to Reproduce
Insert keys, click and drag self onto janicart.
# What you Expected
To ride the janicart.
# What Actually Happened
Nothing.

**Comment by Kurfursten** [comment]
#23793

**Comment by ghost** [comment]
I guess you could say, I dabbed on the jannys. 💯
