### ISSUE TITLE
Plans to remove Asimov MK2 Eletric Bogaloo

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2394]
Okay in the 1 millenia of Asimov, nobody has managed to fix this piece of crap.
The moderation "can't participate in thread drama", the players won't EVER hit a decision on if potential harm is a thing or not, and if anyone tries to do anything about it OOC is muted and the thread is de-railed.

The only way to fix it now. Is for the coders to take the dicks off their ass and find anoter default lawset.
Good fucking luck.

**Comment by ComicIronic** [comment]
As this is an open-source project of community contribution, I suggest you create a lawset yourself if you're unhappy with the current one.
However, it has to be:
1. As unambiguous as possible, especially in terminology
2. As rigid as possible, with little possibility to bend laws
3. As clearcut as possible, with as small a doubt in the action desired of the silicon player in any situation
4. Fun to play with
[PROTIP] This is actually very difficult.

As for my two cents, Asimov is a great lawset. It fulfills the criteria pretty well, leaves the AI and borgs as a neutral party in most antag events, and has systematic flaws which create interesting situations and stop the station immediately becoming the same Validsalad 13 every round.

**Comment by Cisrox** [comment]
This is garbage, it's closeable. A new discussion could be made but this is going nowhere.

**Comment by PJB3005** [comment]
@Cisrox that's not how discussions work, Jesus Christ.

**Comment by Intigracy** [comment]
Well this discussion still is garbage.

Asimov may be flawed, but nowhere near as flawed as some of our other possible lawsets.
It's flawed in just the right amount to have the AI be a pain in both the crew's ass and the antag's ass, which is perfect.

**Comment by gbasood** [comment]
It's also a year old now. Actually it was started two years ago. I'm pretty sure the way we treat AIs in general has changed since then.

There's already a newer issue related to ASIMOV shit anyways so if someone wants to start a new conversation related to this, they can reference this and start up the ASIMOV hate train again.
