### ISSUE TITLE
Cat Mobs Do Not Attack and Kill Vox

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#23940]
#### Description of issue

Cat mobs such as runtime do not attack and kill Vox on sight

#### Difference between expected and actual behavior
They are cats they should hate Vox

#### Steps to reproduce

Show a cat any Vox

#### Specific information for locating

 [<runtime>]

**Comment by ghost** [comment]
Based

**Comment by FudgePucker** [comment]
Based

**Comment by tomacatx2** [comment]
Based
