### ISSUE TITLE
plague mouse spawns on vox station (roid)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23960]
(WEB REPORT BY: bobthomas REMOTE: 206.221.180.138:7777)
# Revision
5dc47114302851e97160390f34e807187d7d50e4

# Description
plague mouse instantly dies to vox atmosphere
# Steps to Reproduce
spawn as plague mouse on asteroid station
# What you Expected
to spawn on the main station
# What Actually Happened
spawned on the vox station and died to atmosphere instantly

**Comment by Probe1** [comment]
It'll happen on all maps it's unfortunately the way the code works.

**Comment by Intigracy** [comment]
Pretty sure it only spawns on z1, so it would be asteroid exclusive

**Comment by Probe1** [comment]
Hardmapping a couple vents per map to not spawn mice is ok for the supermatter but its starting to feel mighty shitty to do it for a whole outpost.  Like our design is bad and we're making up for it with lots of silly exceptions.
