### ISSUE TITLE
Invisible wall in viro

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23969]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
c43108a75755f6a42996f5c9a57d3c235e054750

# Description
inviso wall in viro below table just south of the centrifuge
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by AI-Is-Rogue** [comment]
It's the food dispenser taking up the tile but the sprite being displayed on the wall

**Comment by DeityLink** [comment]
It being on that tile is intended. It having density is not. Wall structures don't have density normally.

**Comment by Probe1** [comment]
We fixed this at some point
