### ISSUE TITLE
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#23978]
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 

#### Description of issue

deleting the retarded chatspam singulo doesn't save you from chat spam

#### Difference between expected and actual behavior

delete singulo
chatspam stops
vs
delete singulo
chatspam continues uselessly, endlessly

#### Steps to reproduce

make vote controlled singulo
delete singulo

#### Specific information for locating
No votes were cast this cycle. Remember, type UP, DOWN, LEFT, or RIGHT to cast a vote! 

#### Length of time in which bug has been known to occur
#23279  @GlassEclipse

**Comment by boy2mantwicethefam** [comment]
Sounds like a feature to me
