### ISSUE TITLE
Emagged defib harms slime people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23975]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
8b0eec6c7784ed74f405ced4dc443c6bcdb6daf3

# Description
Slime people, who are immune to shocks, still get shocked and hurt by this
# Steps to Reproduce
Get shocked as slime person
# What you Expected
It heals
# What Actually Happened
Straight to orange

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by tayachiya** [comment]
Same thing happens with electric chair. Possibly also a feature.

**Comment by Probe1** [comment]
You both know it was an oversight.
