### ISSUE TITLE
Advanced xenoarch scanners aren't available

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23980]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
2019bbfabe48b10700cd9db44030d80f9e8e5453

# Description

We had anomaly to 6, plasma to 5 and electromagnetic to 5. We could only print the basic ones. We even got the NT research disk

# What you Expected
Being able to print advanced xenoarch scanner

# What Actually Happened
They aren't there

**Comment by DrSnips** [comment]
Line 54 of code/modules/research/designs/anomaly.dm is causing the issue. Duplicate design ID. Can be fixed by simply adding something like _adv to it

**Comment by arc166** [comment]
Isn't it also commented out.

**Comment by DrSnips** [comment]
No. You're thinking of a different item. If you read the title it says the adv. scanners which implies the ones recently added. Also if you read the file I posted at the line# you would know which.

**Comment by arc166** [comment]
Oh I see, my shits out of date. Its something else which is commented out for some reason.
