### ISSUE TITLE
Issue with air

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#23998]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
538f9f12d1add4bffcd1bc537c9050dc5e5912e7

# Description
filled extended-capacity emergency oxygen tank with air from an "air" canister. this caused me to gasps and take oxygen damage 
# Steps to Reproduce
fill tank with air
# What you Expected
breathing
# What Actually Happened
no breathing

**Comment by ghost** [comment]
Did it actually have air in the tank

**Comment by brndd** [comment]
if your mix is 80% nitrogen then logically you need more partial pressure than the 17 kPa you need with pure oxygen. Try setting the tank to 103 kPa and it should work.

**Comment by Exxion** [comment]
There's a reason it's an emergency *oxygen* tank, not *air* tank
