### ISSUE TITLE
Played nukeop while banned

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#24005]
Apparently I'm antag banned from newkops and joined as a midround antag with no issues. Kharkov pointed it out and forcefully booted me out for those misery valids after giving me a passive aggressive threat. Might be that it's midround or something else.

**Comment by SGuivenne** [comment]
Hope you didn't get dinged for that, some of those are a bitch to opt out of.

**Comment by DeityLink** [comment]
Fixed by #29602
