### ISSUE TITLE
Shocked to death as Slime-man.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24009]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
c3702e1414f4cbe5872d591518b58e34fe2ca17a

# Description
got bussed in as a cultist-chaplain-slime due to the crew wanting one on cult. got shocked by the AI and it put me into crit instead of healing. how peculiar? Left security lobby door on box.
# Steps to Reproduce
be a slime lad and get shocked on a door. perhaps wear a cultist outfit? it might just be because it was bussed in
# What you Expected
getting healed by a shock
# What Actually Happened
getting crit'd by a shock

**Comment by Dacendeth** [comment]
The spawned in ones using the game panel create mob verb dont have shock healing for whatever reason, tested this just now.

**Comment by SonixApache** [comment]
I spawned the slime with the spawn command, `spawn man/slime` and they didn't have shock healing either.

**Comment by AI-Is-Rogue** [comment]
Could it be spawning species/slime rather than species/slime/xenobio? The former doesn't have the ELECTRIC_HEAL flag while the latter does.

**Comment by Dacendeth** [comment]
Well in the mob spawn menu slime/xenobio inst a choice, and the thing that is there that looks right,  carbon/human/slime is the one that dies to shocks despite looking identical and having the same regenerate limb powers.

**Comment by AI-Is-Rogue** [comment]
Yeah, I'm not sure why electric healing was made to be a xenobio thing when slimes in general are capable of harnessing electricity.

**Comment by DrSnips** [comment]
Something something intended for balanced round start slime people.

**Comment by DrSnips** [comment]
A solution to this would be to have a dummy spell just to indicate if you have shock healing. A simple bolt would do.
