### ISSUE TITLE
Performing a magic trick and making any small thing permanently inaccessible by using a tesseract

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#24010]
I have the labcoat slots open
I put on my robes and cultist hat
I place the tesseract into the labcoat slot
I close the slot
Tesseract is in labcoat
Labcoat is in tesseract
Can't reach either
Theoretically you can put a nuke disk there

**Comment by Exxion** [comment]
You *can* put the nukedisk there but IIRC its nullspace detection would catch it and respawn it after a while

**Comment by Coxswain-Navigator** [comment]
Thanks now I know what to do with my monkey cubed discord trannies
