### ISSUE TITLE
AI Pictures Cause Lag

### ISSUE THREAD

**Issue by Demagogue-Dimension** [d3athrow/vgstation13#24016]
Current revision unable to pull due to client issues resulting from bug.
# Description
Taking a picture as AI on Snow Station causes massive client-side lag
# Steps to Reproduce
Play as AI on Snow Station. Take photo. View photo.
# What you Expected
Regular gameplay and connection.
# What Actually Happened
Connection got progressively worse, eventually resulting in over 10,000ms loss and inability to use user interface due to unresponsiveness. Monitored packet loss minimal so it is likely due to the client-side conditions for this glitch being met. Glitch continues indefinitely regardless of resetting internet or connection.

**Comment by Demagogue-Dimension** [comment]
Sonix went ahead and deleted the photos I took as AI. Now the lag is gone. I think this confirms my suspicions on the cause of this glitch.

**Comment by Demagogue-Dimension** [comment]
I checked just now if I could replicate the issue. It did not happen again. There's a chance that there was another variable that led up to the conditions of the glitch being met or the action by Sonix removed a condition. In any case, please reference this report in case other users have the same issue in the future.

**Comment by Kurfursten** [comment]
Unless this happens again on Snaxi I think I'm going to say it's not specifically related.

**Comment by nervere** [comment]
Tested this, couldn't replicate. There haven't been any reports about this since and there's too many potential confounding variables to pin it squarely on AI pictures.
