### ISSUE TITLE
Slime people and their brains are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24015]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
c42aab6f351798161d7d6fdcdbbccc02de66987f

# Description
Can't put their shitty slime core brains in their dead puddless
# Steps to Reproduce
Get slime-man. Kill slimeman. Try to put their rainbow slime core into their puddle to clone or something.
# What you Expected
Expected the core to go in and them to get cloned
# What Actually Happened
Slime core (the brain) dropped at my feet

**Comment by SonixApache** [comment]
It was runtiming. Something about cannot read null.name. Other admins mentioned that they might've been gibbed, which might've caused it? Not sure.
