### ISSUE TITLE
Paper Spamming the AI

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#2402]
I don't believe this has been addressed before but it is possible to continuously spam the AI with Paper via the station Cameras which makes it impossible for the AI to talk or do anything like that. Easy enough to replicate, simply be the AI and get someone to click on a camera whilst holding paper as quickly as possible, you'll see how annoying and detrimental it can be. 

There should probably be a delay on how often you can display a piece of paper on the AI's cameras.

**Comment by Kurfursten** [comment]
Filled https://github.com/d3athrow/vgstation13/pull/3341
