### ISSUE TITLE
Starman Thoughts

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#24027]
-The heal is broken (literally)
-Having something with a pulse rifle and an AoE disorient/stun is a bad idea.
-Starstorm is really fucking strong and should have a much higher cooldown
-As a silicon it can still fuck with electronics, bolting/shocking doors, syphoning, etc
-It has no deadstate

**Comment by Irradiation** [comment]
Sasuga, enterprisecode-sama

**Comment by Killette2** [comment]
If you get shot your cyborg eye camera can break. Even if you sweet talk a roboticist about it they can't fix you if they wanted.

**Comment by kilozombie** [comment]
>-As a silicon it can still fuck with electronics, bolting/shocking doors, syphoning, etc

>If you get shot your cyborg eye camera can break. Even if you sweet talk a roboticist about it they can't fix you if they wanted.

why did he make it a silicon

_why_

**Comment by jknpj** [comment]
wasn't it supposed to be deathsquad-tier bus

**Comment by Killette2** [comment]
I hope not. You're way too immobile to even with your awkward controlled blink.

**Comment by west3436** [comment]
Starman is an incomplete antagonist which is not currently implemented.
