### ISSUE TITLE
recycler doesn't handle sheets properly

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#24031]
#### Description of issue
\>add a stack of 50 sheets of iron
\>recieve one point worth of iron

\>drop in an adminspawned bigstack of iron
\>recieve 0 iron because technically it doesn't have anything in it

#### Difference between expected and actual behavior
50 sheets recycle into 50 sheets
vs
50 sheets recycle into 1 sheet

#### Specific information for locating
`/obj/machinery/mineral/processing_unit/recycle`

#### Server revision
393a3e9653daf4971c1fd40c73e46a2b6a222931

**Comment by jknpj** [comment]
hmmm

**Comment by tuypo1** [comment]
I feel like their should at least be some loss but not a 98% loss

**Comment by SonixApache** [comment]
fixed, probably by robo's change
