### ISSUE TITLE
Evidence not being removed from evidence bags correctly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24033]
(WEB REPORT BY: dtscurvy REMOTE: 206.221.180.138:7777)
# Revision
393a3e9653daf4971c1fd40c73e46a2b6a222931

# Description
When an evidence bag is placed into a scanning computer, the object is removed from the bag and placed in the computer. But the evidence bag, despite the sprite being changed, retains the properties of a bag containing the item. So, an evidence bag with a plasma tank, for example, will not be able to fit into the evidence bag box anymore and will retain the description of the plasma tank.

# Steps to Reproduce
Use an evidence bag to pick up a plasma tank

Use the evidence bag on the scanning computer

Examine evidence bag

**Comment by MadmanMartian** [comment]
Ill take this one
