### ISSUE TITLE
Zombie Syndrome Nullspace bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24056]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
9cf2023f9c014fdc2c7c2269481ece58f986a021

# Description
Become patient zero (infect yourself with zombie virus). Die. When your corpse rises as zombie - you have black screen and hud. You ghost - you're naked at shuttle. Try to re-enter corpse - you have no body.
# Steps to Reproduce
Make zombie virus, infect yourself. Let it develop to stage four. Die. Suicide or something.
# What you Expected
To be player controlled zombie
# What Actually Happened
AI controlled zombie, I am nullspaced, admins have to put me in.

**Comment by Killette2** [comment]
https://github.com/vgstation-coders/vgstation13/issues/23804

**Comment by DeityLink** [comment]
Potentially fixed by #26103
