### ISSUE TITLE
Magboots icon clipping through hardsuits

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#2406]
They should either be above the hardsuit layer or have the extra pixels on the side trimmed off. Or maybe they just shouldn't be thigh highs compared to all other footwear in the game

![untitled](https://cloud.githubusercontent.com/assets/4674335/5576741/84ab174c-8fd8-11e4-86b7-6cfd8138b41f.png)
.

**Comment by Edwardius** [comment]
I think they may as well be jackboots edited to look similar without being so fat.

**Comment by SkowronX** [comment]
Missing hide flags
