### ISSUE TITLE
Washing Machines Can't Close

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24074]
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
f0921823555d31f6e95d73dc284786a4f435d12f

# Description
Washing machine wouldn't close, and so couldn't start or get items out.
# Steps to Reproduce
Put leather inside a washing machine.
# What you Expected
To be able to wash the leather or at least be able to retrieve it.
# What Actually Happened
Washing machine could never close and so things could not be taken out.

**Comment by nervere** [comment]
Washing machines aren't meant to take leather, and the washing machines closing was apparently fixed by Deity.
Thanks to @Inorien for testing this!
