### ISSUE TITLE
Mechanic's Blueprint Printer Menu being inaccessible

### ISSUE THREAD

**Issue by omeno** [d3athrow/vgstation13#2407]
After using the Blueprint Printer a few times the NanoUI menu became unresponsive (as in window not appearing), tried a multitude of methods to get it to respond including opening/closing maintainence panel, relinking it to the R&D console, and restarting Byond.

**Comment by ComicIronic** [comment]
Was Resend Resources used?

**Comment by omeno** [comment]
No, but since this point I have yet to encounter this bug, or see anyone else mention it.

**Comment by omeno** [comment]
Seeing as how this hasn't occurred since Lokiamis reported it happening to him I'm going to close the issue.
