### ISSUE TITLE
Vicerator gets stuck on monkey pen when the door is open

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24076]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
f0921823555d31f6e95d73dc284786a4f435d12f

# Description
Bug gets stuck on door to monkeys
# Steps to Reproduce
Summon it by the door, open it
# What you Expected
It kills monkey
# What Actually Happened
It kills the open door

**Comment by nervere** [comment]
Seems to no longer be an issue. Thanks to @Inorien for testing this!
