### ISSUE TITLE
Printing all PDA credits empties PDA wallet and produces no credits

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24087]
(WEB REPORT BY: incakola REMOTE: 206.221.180.138:7777)
# Revision
2d85dbb5d7dffcb574b4f5e5263ef55b229ee50b

# Description
Printing all PDA wallet credits does not print any credits

# Steps to Reproduce
1. Open PDA
2. Go to print credits from virtual wallet
3. Have $237, and print $237
4. Receive invalid amount error
5. No credits in PDA or on ground anywhere

# What you Expecte
No error and money somewhere nearby

# What Actually Happened
I fell short of my next child support payment and now she's taking my dog

**Comment by incakola** [comment]
I should add I was the CE in packed bridge with a blackmarket uplink in my other hand.
The engineering bank card was inside a cardboard box in my backpack.
My ID was inside the PDA.

**Comment by Blithering** [comment]
Did you by any chance have a wallet in your inventory?

**Comment by incakola** [comment]
No wallet

**Comment by nervere** [comment]
Seems to have been fixed in a PDA rework some time ago. Thanks to @Inorien for testing this!
