### ISSUE TITLE
Remove chance of Internal Bleeding and Broken Bones from Cult runes

### ISSUE THREAD

**Issue by Rockyrancher** [d3athrow/vgstation13#2408]
As the title suggests, using cult runes can murder the shit out of you if you're already pretty damaged and it's really pretty shitty.

EX: summon cultist rune drops you down to orange and breaks bones and/or causes internal bleeding.

This pretty much gives a lot of cultists to not consider using other runes for such a heavy cost. I'm not saying to remove the damage, just make it so you aren't guaranteed to die, because we all know cultists aren't going to go in for surgery (and even then, what're the chances of even getting surgery).

**Comment by MasterofNothing** [comment]
Do the two types of damage both have a chance to cause internal bleeding, or is it just organ damage that does? Otherwise you can just remove organ damage and use overall damage.

**Comment by Cisrox** [comment]
Closeable.

**Comment by PJB3005** [comment]
@Cisrox [angry rant]

**Comment by Zth--** [comment]
This has been fixed long ago. I can confirm it's closeable

**Comment by Cisrox** [comment]
^^ SEE PJB
