### ISSUE TITLE
Making sand blocks is tedius

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#24080]
It used to be a streamlined process that turned all sand on the tile into blocks. For months this feature has suddenly stopped working. For this screenshot I used an autoclicker on sand because you have to do each block manually.
![2019-09-04_21-42-08](https://user-images.githubusercontent.com/5169310/64308947-0857d380-cf69-11e9-93b0-e5f3717e9ee1.png)

**Comment by MadmanMartian** [comment]
gonna need more details, boss

**Comment by Killette2** [comment]
1. dig a bunch of grass into sand with a spade
2. use sand block in hand by clicking on sand, or using the pagedown key/whatever hotkey for use is on hotkey mode
3. do it again, and again, and again
4. miss the time where when you did this once, it automatically stacked all sand into one block (see grass into grass tiles for reference)
