### ISSUE TITLE
Snowmap

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24098]
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
be7fa031c20379fc956a2792473b75be8d500465

# Description
Under the door to the storage room next to the server room is space.
# Steps to Reproduce
Looking under the door.
# What you Expected
A floor.
# What Actually Happened
Space.

**Comment by SonixApache** [comment]
also the central part for the gateway appears to be missing

**Comment by Kurfursten** [comment]
Also in the SME room there is a floating light on top of one of the computers.

**Comment by SonixApache** [comment]
I think I saw a floating extinguisher cabinet near the HoP's office as well.

**Comment by plosky1** [comment]
All taken care of.
