### ISSUE TITLE
Powercreep Powercreep UnScythable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24106]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
be7fa031c20379fc956a2792473b75be8d500465

# Description
Heavy Duty Pneuymatic Scythe or whatever doesn't hack away at powercreeper vines wtf coders
# Steps to Reproduce
APU ripley with Scythe at Powercreeper
# What you Expected
it work
# What Actually Happened
not work

**Comment by PaulRitter** [comment]
scythe apparently isn't is_sharp or something
