### ISSUE TITLE
Zas looped to death

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24109]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
23c1f529c212e24d8b88720717f3b1d98190e551

# Description
Broke 1 tile, got zas slammed repeatedly in a tiny area for around 3 minutes, the items in the area continued to loop for even longer
# Steps to Reproduce
Break the tile 1 step above chem machine in sci outpost on box
# What you Expected
Hole in floor, maybe slammed into wall once
# What Actually Happened
Hole in floor, slammed into walls for over 3 minutes

**Comment by SonixApache** [comment]
as i explained multiple times, this was intended
the small room was being repressurized faster than the hole in space could succ it out
causing infinite succ

**Comment by Dacendeth** [comment]
feature
