### ISSUE TITLE
Alt-clicking grills doesn't do anything, including not showing the turf investigation tab

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24116]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
d0eb370afc8eb5af5eeb6bb43e947570f08e6d3e

# Description
title
# Steps to Reproduce
altclick grill
# What you Expected
plating (window, window, window, window, grill)
# What Actually Happened
nothing

**Comment by Dacendeth** [comment]
#21754 didnt fix this?

**Comment by SonixApache** [comment]
nope

**Comment by Exxion** [comment]
If the tile isn't blocked, the supercall at the beginning lists the turf contents, and then the code afterward reverts it
