### ISSUE TITLE
Snow Taxi is pretty shit (and 10 reasons you wont beleive why!!!!1)

### ISSUE THREAD

**Issue by MaverickEsq** [d3athrow/vgstation13#24117]
#### Description of issue
Feedback on snow taxi map, sonix was all bein a bitch like "waaaaaaa u b mean and say u dont like so write feedback" well I am so there.

#### Difference between expected and actual behavior
Expected: good map
Got: Snaxi

#### Steps to reproduce
Have adspergs force badmap

Okay shit memes aside,  Sonix said to give some feedback about new snaxi map so here goes:

~~Shit needs population minimum. It beyond sucks ass with only a few people. On top of that, everything is so fuckin far apart its going to be isolating and therefore boring as fuck. Like, how many people go to the extra mining base on the mining asteroid? None, yeah cause no one is there and its too far away to be useful. This whole map is that. Why would I walk the distance of all the way accross box 3-4 times over to go to the bar? I wouldn't and probably no one else will either so we'll all crowd north east station or central.~~

~~Needs a fuckin map on the website. "Waaa powergaming" its a new map, we gotta figure out where shit is. The feeling of exploration is great but at the same time so is knowing where my office is.~~

~~The movement lag is shit.~~

The central/security substation feels incomplete. Possibly because its the size of box and all it has is sec and bridge (and a shitty half done R&D). Either make nice big dedicated substations for a dept or focus them in one place, spreading them out just means you either don't have access to what you need or everything is coppied 10 times. Also the location of mining in r&d is weird and both the shuttles are next to each other. Move mining out to the big ol space dock you got or something. Or with cargo since its part of cargo anyway.

~~The permabrig is cool. The rest of the brig is average at best. Armoury shutters leading into the medbay is whack, that should be a seperate switch.~~

The "EVA" by bridge is weird and empty, there are coats everywhere already.

The shuttle bay was cool but good fuckin luck finding it. Should really be connected to the engineering substation or have a special office there, and a dedicated airlock from main station.

The whole "on a planet" thing is average as well, basically tators are gonna be longshotting everyone or doing stupid shit and running into the trees never to be seen until they blow shit up again. So either sec will ignore them (ya forced shitcurity) or all disperse into the bush and leave station sec-less. On top of that, there were what like 3 ID/Coms consoles that are accessible from outside? Sure thats fine on space station where its hard to get to without being thrown into space and theres carp and breaking through the windows to bridge is gonna be very quickly noticed, less cool when people can walk up in a coat. So outside needs to be dangerous in some way aparrt from "you get cold unless you're wearing one of the many hardsuits around or a warm coat that are everywhere"

Speaking of dangerous outside, no one is gonna go between substations even if its not dangerous. Glass tubes are a possible idea, that way you can have snowmen or some shit out there and still quickly get between stations. Or make a reskinned trashbin that uses disposal pipes to get folks from place to place. Shit, make a portal system, put it in mechanic's office and now mechanic can do something apart from either being a shitty engineer or building 2 of every machine because shits and giggles. Also, just put things close together I guess.

Having more destination taggers/wrapping paper would be cool because then everyone could send shit to each other via the trash. Send food to bridge, send corpses to med, send guns to engineering or get no power. You know, normal shit.

Also, the cold air could rapidly lower temperatures until inside also gets fucked so now instead of supplying air, atmos can supply warm air by using a thermo chamber like teg (that you can add to atmos). This works because now the tators in the great outdoors can sabotage air lines and sec+atmos teams will have to be dispersed to deal with it.

Blah blah blah I'm a whiny faggot and this isn't a professional bug report, ok, but as proffanity filled as this is I feel I raised some good points and ideas.
Its a cool map, but its gonna be a free for all shitshow because everyone is so isolated they can do whatever the fuck they want, at which point they'll get bored and dab. Just suffers from being TOO FUCKING BIG

**Comment by SonixApache** [comment]
Snaxi also still has solars rooms for some reason. Why? Who knows.

**Comment by MaverickEsq** [comment]
I assumed that was so there were more charged smeses to offset the fact no one knows where the fuck engineering is.

Oh yeah and the hardsuit tank in HoP's office/bridge thing is broken. Also two bridges just means we're gonna have control wars.

**Comment by Durgen** [comment]
needs a derelict maint substation so it can out deff deff

**Comment by Kurfursten** [comment]
Who knew? You remove the taxis from taxi and suddenly it's a slog to get around. It's almost like the taxis were important.

**Comment by FudgePucker** [comment]
Add department teleporters, that only jobbies have assess to.
Gotta get a corpse to cloning? Not a problem. Gotta deliver stuff from research to somewhere else? It's a breeze. Need to deliver food? Take the short cut though time and space.

Assistants can take the long way though the cold.

**Comment by SonixApache** [comment]
Disposals being launched into permanent teleporters to connect them from station to station would be interesting.

**Comment by incakola** [comment]
I disagree with pre-built teleporters, disposals, tubes, anything that can move between the substations easily
this is something jobbies can set up on their own after the round starts

right now snaxi's appeal is that it's cold outside and to get from one place to another you have to slog it through the snow and risk brigands popping out of the trees
putting a transit system in by default is like taking the singulo out of the middle of bagel/donut - ruins part of the unique draw the station has

**Comment by tuypo1** [comment]
The isolation of the segments being so far apart is what makes it great
