### ISSUE TITLE
Custom Cakes, Pies, and Bread created in the oven cannot be sliced

### ISSUE THREAD

**Issue by Sir-Sneaky** [d3athrow/vgstation13#2411]
Pretty much as the title says, attempting to slice a custom cake, pie, or bread loaf with the kitchen knife has no effect and no message.

**Comment by 9600bauds** [comment]
Fixed by #4374
Pies were never sliceable AFAIK

**Comment by ComicIronic** [comment]
Pies don't make slices, no.
