### ISSUE TITLE
dogs are essentially fucking locusts with how much they eat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24122]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
259b9a7c16d1244ca5e795e45a3255f4d741994b

# Description
dogs literally won't stop eating
a single corgi ate everything in the kitchen
they just won't fucking stop
# Steps to Reproduce
spawn 200 pizzas
spawn a corgi
observe the destruction
# What you Expected
Make food, serve food to people, corgi eats a slice of pizza and is content
# What Actually Happened
Slave to the canine syndicate, shoveling barrels of food into its gaping maw every second to keep it somewhat sated

**Comment by Shadowmech88** [comment]
This should be fixed, but on a side note we should add a locust mob that are like cockroaches except they can eat food, track it through walls, and ventcrawl.

**Comment by boy2mantwicethefam** [comment]
Feature
