### ISSUE TITLE
Bombs OP pls nerf

### ISSUE THREAD

**Issue by haligue** [d3athrow/vgstation13#2413]
Bombs are easy to make and easier to dissarm... they should be harder to make and even harder to construct and even more harder to dissarm, that why we have bomb suits. Bombs should have circuits with some wires and the bomb maker should select wich wire is the detonation, timer, dissarm....

**Comment by SarahJohnson489** [comment]
High-strength bombs are already hard to make and smaller shit is negated by a single metal foam grenade or 4 minutes of securing glass windows. Even if you double bomb medbay most of it is wasted space. If you can get rnd to do its job and send or at least make boards and parts you can have a 100% functional and repressurized medbay in under 20 minutes with only 2 guys. It really is a case of people just need to gitgud.

Anyone with sense is going to have them on a signaller with a prox-signaller in the same container if they're not keeping it on them.

**Comment by Kurfursten** [comment]
@clusterfack Can probably be safely closed, since you touched on this one yourself.
