### ISSUE TITLE
[Feature Request] Stable Wormhole Generator

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#24136]
[featurerequest]
The problem with teleporters is that, they can fail, sending you into the middle of space, also telebeacons can be placed in high security areas, making the teleporter command access only.

What if we had a different teleportation method that, never fails, and can only go to teleporters of the same type.

This would have very important uses for bigger maps, put one in cargo and the bar so you can ignore orders and get smashed on box, put one in each station on snaxi so you dont have to fight the cold. Set up some to every department whenever someone is making a burn chamber in the bar, someone is going to break a glass tile, and you dont want people that think they are more important than the atmosphere on the station to start opening firelocks (remove that excuse). Set up behind a false wall that leads to a burn chamber, they wont see it coming!

**Comment by DrSnips** [comment]
We actually do have stationary portals that are a simple means of connecting point A and B. They just aren't used yet afaik.
As for the teleporter I think its about time the random sends-u-2-deep-space thing got removed. I'm sure admins can back up how often this happens. A huge issue is that the way to not have it send you to deep space is a hidden right click verb on the generator.

**Comment by FudgePucker** [comment]
Thanks for the PR. 
I think I recall those portals are just magic and look like hand teleporter portals and also dont use power. Also hard mapped in so you cant make them. I recall that they were going to be used on bagel to make it more bearable to cross the station
