### ISSUE TITLE
Clumsy and zippos

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24140]
(WEB REPORT BY: dacendeth REMOTE: 206.221.180.138:7777)
# Revision
10c21eb6f6d1f76e212c5666263d10b980f452bb

# Description
Clumsy people can use zippos just fine with fancy emote text, this feels wrong.

**Comment by tuypo1** [comment]
Make it deal burn damage if you try to use it while clumsy
