### ISSUE TITLE
double desc.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24155]
(WEB REPORT BY: robosperg REMOTE: 206.221.180.138:7777)
# Revision
3cdb4071343acaf14e88456efd4c089b5bcc1f25

# Description
When examining items on people as ghost, the description shows up twice

# Steps to Reproduce
hit observe, examine something a spessman is wearing

# What you Expected
to see the examine text

# What Actually Happened
I seent it twice

**Comment by Zth--** [comment]
Can't reproduce
