### ISSUE TITLE
Meta MULE gets stuck on Security tracking beacon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24151]
(WEB REPORT BY: tsea REMOTE: 206.221.180.138:7777)
# Revision
3cdb4071343acaf14e88456efd4c089b5bcc1f25

# Description
Sending mule bots to the security destinationg leads to the bot getting stuck on the tracking beacon there.

# Steps to Reproduce
Send a MULE to the security destination.

# What you Expected
MULE coming home after dropping off the package.

# What Actually Happened
MULE stayed in place and panicked.

**Comment by Kurfursten** [comment]
Did you send just one or two at once? MULEs always get stuck if you send 2
