### ISSUE TITLE
Time Suit Jump to Past Is Rarted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24152]
(WEB REPORT BY: tsea REMOTE: 206.221.180.138:7777)
# Revision
3cdb4071343acaf14e88456efd4c089b5bcc1f25

# Description
Using the "Jump to Past" feature in the Time Suit simply strips you except for your backpack.

# Steps to Reproduce
Try jumping to the past.

# What you Expected
Jumping to the past.

# What Actually Happened
Unwanted nudity.

**Comment by Shadowmech88** [comment]
I discovered this with past grenades the other day on the test server. It appears that some things have broken with the `send_to_past()` proc, human clothing being one of them. I'm assuming inventory code has been changed since it was added and the change didn't account for its existence.

**Comment by Allspice** [comment]
This was fixed in the Time Agent PR, think that send_to_past was runtiming on antibodies or something.
