### ISSUE TITLE
[Bug] Emitters flash on and off when added to automation console?  Needs testing.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2415]
WebM of bug in action.
http://a.pomf.se/vwchce.webm

Instead of being solid beams, the emitters flashed on and off.  I do not believe this caused any functionality loss because I tested a rad collector and compared it to its previous power output, which was very close and attributable to normal decay.  

Here's what I did.  I set up the SME with injectors venting oxygen and plasma to space and nitrogen being filtered to a series of thermal plates then back into the loop.  Then I added injectors inside, added appropriate insulated pipes and used a multitool to set both the injectors and scrubbers to frequency 13.3 GHz.  Then I set the atmospherics automations console for the SME to 13.3 GHz frequency and added the injectors and scrubbers, which I set to on and syphon.  After that I turned on the 3 emitters and snd added uncooled plasma tanks that had been maxed out at 1100 kPa. 

At this point the emitters were a solid beam and behaving as expected.  Then I used a multi tool on the emitters and added them to 13.3 GHz.  I **did not** turn them off first.  I added them to the automations console and turned them on.  They immediately started flickering on and off. This did not show any appreciable power or quality loss and it may have been solely a graphical bug.  

I would hazard a guess that this was related to them being on then adding them to the script and toggling them from off to on.  I did not have time to investigate it in game but turning them off, then toggling them on with the automations console may have fixed it.  

That's all I know.  Hopefully this helps.

**Comment by clusterfack** [comment]
Wait wait reopen this, it SHOULD get fixed at some point.

**Comment by Probe1** [comment]
to be honest the workaround is pretty simple.  give emitters unique IDs that aren't shared with any other scrubbers, injectors or whatever else you have in the script.  problem goes away.

**Comment by Probe1** [comment]
@clusterfack this'll be a good one for when feature freeze hits eh?

**Comment by d3athrow** [comment]
Pretty sure the issue here is the signal only has one setting which toggles it.

**Comment by d3athrow** [comment]
nope ended up being that emitters did not check their signal data.
