### ISSUE TITLE
ctrl clicking clothes to pull them doesnt work anymore

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#24156]
#### Description of issue
You cannot ctrl click clothing on the ground to drag them behind you, you used to be able to do this.

#### Difference between expected and actual behavior
ctrl click something to initiate a pull and it working
doesnt work.

#### Steps to reproduce
ctrl click a jumpsuit on the ground and try to move with it behind you.

#### Specific information for locating

works for everything else except pieces of clothing, hats, suits, boots, etc.
obj/item/clothing items are the problem

#### Length of time in which bug has been known to occur

This works on a 3 month old localtest.

#### Server revision

3cdb4071343acaf14e88456efd4c089b5bcc1f25

**Comment by Dacendeth** [comment]
#23950 probably is the culprit

**Comment by ghost** [comment]
xd

**Comment by ghost** [comment]
The spirit of Enterprise-tier Code™ haunts us still.
