### ISSUE TITLE
pressing enter in non-hotkey mode now auto-inputs 'say'

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#24163]
See title. This is a very recent problem.

After using any verb in the bottom text box (like 'say' or 'analyze-air' or whatever), it will immediately place

>say "

in the text chat, making it annoying to do any other verb in sequence.

**Comment by SonixApache** [comment]
![chat](https://user-images.githubusercontent.com/8468269/64917726-9b77e100-d793-11e9-84ec-2526243b551d.png)
Did you have the Chat button toggled on...?

**Comment by kilozombie** [comment]
oh

That's a very non-communicative button, but thank you
