### ISSUE TITLE
Ninja holoprojector doesn't save you from electrodes

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#24179]
1. Be ninja holding hologram thingy in hand
2. get tased
3. teleport away but ALSO get hit by the electrode, quickly defeating the point, even if you say a sneaky quote automatically when you teleport
![image](https://user-images.githubusercontent.com/5169310/65215649-2c90d580-da7c-11e9-8ea0-54f51d3d031d.png)

edit: I am not going off of the word in this picture. It personally happened to me which lead to that discussion.

**Comment by Kurfursten** [comment]
It probably got broken when Shifty tried to refactor shields and bolas. They used to work. The block check is supposed to happen before the projectile can apply a stun.

EDIT: Nope, can't blame shifty on this one. It was when r0b0 changed projectile on_hit for "armor fixes" under the radar 3 months ago.
