### ISSUE TITLE
Plague Doctor Mask, Balaclava and Lucha mask don't hide identity 

### ISSUE THREAD

**Issue by ComradeDispenser** [d3athrow/vgstation13#24173]
[bug]
I was playing around with the voice changer item and seeing how it worked and interacted with wearing IDs with different names, and I realized that the Plague Doctor Mask (which covers your entire head) and the balaclava (classic headgear for the iconic "criminal") and the lucha masks (worn by wrestlers to conceal their real identity as part of their act) don't actually conceal your real name, so when you talk it will say "Real name (as unknown/fake name)" instead of letting you bask in anonymity.
I'm not sure if it affects the actual items themselves since I only noticed it when testing the voice changer out and it's chameleon abilities, but I feel like they probably also have these issues.
 
I was going to try and fix this myself, because it seemed like it would be easy, but man the code for masks is kind of confusing when you barely know how to code.

**Comment by kilozombie** [comment]
Well, as far as I'm aware, the voice changer is a mask with tech in it that allows you to alter your voice. Other masks don't actually alter your voice, they just hide your face (so when you're examined, your ID is what's seen, and Unknown if you're not wearing an ID). If you're a crewmember and somebody else hears your voice, it makes sense that they would be able to know you're faking. This is intended behavior, not a bug.

Now, humans IRL are able to change their voice without needing special technology, and there are odd cases if you're speaking to somebody who shouldn't know your other persona. However, it's still intended behavior with the current code, and making it possible to change your voice would invalidate the Voice Changer quite a bit.

You can observe this behavior with any mask item that's meant to hide your identity, but also with hardsuit helmets-- a lot of objects actually hide your face. Then, when you speak, if your voice doesn't match your ID, that message pops up.

**Comment by ComradeDispenser** [comment]
@kilozombie As I said I was just testing it with the voice changer item set to look like the items in question, not the items themselves. But it also doesn't hide your identity when examined either when you have the plague doctor mask, balaclava or lucha mask as the voice changer appearance.

**Comment by kilozombie** [comment]
Oh, I was unaware it could chameleon! That's super weird then, especially the fact that it doesn't help with examine text.

**Comment by Kharkov72** [comment]
related, #23769

**Comment by kilozombie** [comment]
@ShiftyRail @Zth-- I don't think that PR fixes this

This is the voice changer item's possible chameleon variants not hiding identity.
