### ISSUE TITLE
Suit storage units don't have helmets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24186]
(WEB REPORT BY: pomf123 REMOTE: 206.221.180.138:7777)
# Revision
0ef99e4c8ecd42c7575bf8f9f5df53d198eb5ae5

# Description
Space/hard Suit storage units don't have helmets in them
# Steps to Reproduce

# What you Expected
A helmet in it

# What Actually Happened
No helmet, everything else is there.

**Comment by bathosbathtime** [comment]
Was it a hardsuit storage or softsuit?  The hardsuits have the helmet stored in the suit itself that you active with a verb or something.

**Comment by AutismSpider** [comment]
https://www.youtube.com/watch?v=D00M2KZH1J0

**Comment by d3athrow** [comment]
Yeah I figured that out after r0b0 told me. Seems weird tbh
