### ISSUE TITLE
Monkey armor doesnt work for melee damage

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#24184]
#### Description of issue
Armor a monkey is wearing doesnt work for melee damage, works for all other types.

#### Difference between expected and actual behavior
Armor a monkey is wearing to be fully functional.
Only works for lasers and guns.

#### Steps to reproduce
Put monkey cult robes on a monkey, laser it for reduced damage but melee it for full damage.

#### Server revision

Revision: 0ef99e4c8ecd42c7575bf8f9f5df53d198eb5ae5

**Comment by ghost** [comment]
After testing, I believe armor doesn't work for monkeys at all regardless of damagetype. I'll look into it now.
