### ISSUE TITLE
Stun Pain Phantom burns.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24192]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
0ef99e4c8ecd42c7575bf8f9f5df53d198eb5ae5

# Description

When stun critted you get phantom injuries.
# Steps to Reproduce

Be stunned to hell and back, examine self.

# What you Expected

No real injuries

#What Actually Happened

On Self Examine

You check yourself for injuries.

My groin is blistered.

My head is badly wounded and blistered.

My left leg is blistered.

My left hand is badly wounded.

My right hand is badly wounded.

My left foot is blistered.

On medical scan
Note No Clone Damage
Overall Status: 79% Healthy
Key: Suffocation/Toxin/Burns/Brute
Damage Specifics: 0 - 0 - 0 - 0

**Comment by MadmanMartian** [comment]
That'll be halloss, it makes you think you're dying, so it shows you fake injuries
