### ISSUE TITLE
Space Ninja Darkness Seeing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24194]
(WEB REPORT BY: nomixam REMOTE: 206.221.180.138:7777)
# Revision
92533d42435e024a1766ed548b6975420aa50dab

# Description
I can't see anything in the dark as a space ninja. Anything, it's just black. This happened the other day when I played ninja as well.
# Steps to Reproduce
1. Be a space ninja.
2. Remove lightbulbs and fumble around in the dark.
# What you Expected
To see something in the dark.
# What Actually Happened
I saw nothing.

**Comment by Kurfursten** [comment]
People don't seem to understand, "seeing in the dark" isn't the same as nightvision, it's still dark, you just don't get the total black overlay. You can still aim and even (dimly) view things happening at great distance.

**Comment by SonixApache** [comment]
that or he spawned in the rocks on roid

**Comment by Kurfursten** [comment]
He did mention lightbulbs though
