### ISSUE TITLE
what did you do to the AME

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24190]
![image](https://user-images.githubusercontent.com/6307265/65374209-a34dee80-dc87-11e9-88da-e907b14f227c.png)

**Comment by MadmanMartian** [comment]
what in the god damn

**Comment by SonixApache** [comment]
all the nanoUIs have been fucked for a while, @ririchiyo did a small fix for some specific ones but it's been busted for a while
autolathe had issues, other stuff had issues
