### ISSUE TITLE
cannot re-enter corpse

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#24209]
People are running into this problem on snaxi at the moment. They are getting an error message that says "You have no body." despite clearly having a body they can haunt.
This is possibly an ITS LOOSE tier bug, considering the server just restarted and re-enter corpse might have just been broken.

**Comment by MadmanMartian** [comment]
@DamianX here's the unexpected consequences you were talking about

**Comment by Durgen** [comment]
the clickable RE-ENTER CORPSE text from the cloning message also doesn't function
