### ISSUE TITLE
MORE PIPES FOR THE PIPE GOD

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#2421]
Why don't we have diagonal pipes yet? 
-8 way manifolds
-more efficiency in atmosia
-a way to have both waste and distro go through the same door and thus never having to cross a rwall
Why are there no bent-pipe pumps or valves
why are there no 4 way valves
make this happen n3x
and if you don't I will.

**Comment by ririchiyo** [comment]
four-way pipes are dumb.

**Comment by Duny-** [comment]
>-a way to have both waste and distro go through the same door and thus never having to cross a rwall

I much prefer bay's solution to this

>four-way pipes are dumb.

u're dumb
Diagonal pipes are dumb though

**Comment by ComicIronic** [comment]
>bays solution
You mean the double layer? I thought it made distro modification impossible.

**Comment by Kurfursten** [comment]
@clusterfack Can probably be closed now that we have pipe stacking. Thanks, Comic.

**Comment by ihadtoregisterforthis** [comment]
This reminds me of certain pipe/hose sprites with the same directions and shapes as cables. Atmos can never get too much love.
