### ISSUE TITLE
Temporary Crewmembers

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#24218]
In reading through #24176, one of the comments stuck out to me.
>think I might not be able to play for long, in such situations I don't want to take an important job slot

I realized that I've seen this concern a lot over the years, and I've been thinking about what could be a complete solution to such a problem.
What if we had temporary crewmembers? A new species which are literally just humans, except they have an expiration date. Synthetic humans or mass-cloned humans or something. Players could use the disability field to choose how long they want to live during character creation, and then join the game as whatever job they want. Instead of having to beat themselves to death or go braindead in the dorms or throw themselves out of an airlock as they do now, the player would simply turn to dust after X minutes. No trouble, no explaining to your coworkers why you've suddenly lost the will to live. Everyone is able to acknowledge both IC and OOC that you'll only be there for a short time. Hell, you could even allow other players to see roughly how much time you have left via a smart tattoo on the forehead or something. And because their death is guaranteed, it could even be coded so that the job slot they take upon joining is automatically freed when they die, thus players don't have to be concerned about "taking up a job slot."
I imagine that the majority of people who know they will not be able to play a whole round *also* know exactly when they'll have to leave, and so will be able to set up their character so that not only will they drop dead exactly when they want to, it won't even come as a surprise to the other crewmembers. Everyone wins.

I'm curious what others think about this.

**Comment by Kurfursten** [comment]
Could also just steal cryostorage from other codebases

**Comment by Shadowmech88** [comment]
Wouldn't that be essentially the same thing as going braindead in the dorms, except slightly more flavorful IC?

**Comment by kilozombie** [comment]
I would play several more rounds if I could join as the Five Minute Man whose only purpose is to go do some shit before he dies and I can observe

I don't know. There's something attractive about not only having no expectations, but having an expectation from *everything* diagetically that you're going to leave soon. Dorms and to a lesser extent cryo feel like you're passing up an opportunity to play the round because of an external factor. Sometimes I just wanna join and not dedicate myself to playing the whole round, I guess.

**Comment by Kurfursten** [comment]
@Shadowmech88 Yes but it would let you safely poof away your body and ID so others can't loot it.

I think ideally it would only delete things you arrive with (e.g.: PDA, ID, starting clothes) but not things found on station (to prevent it from becoming a void that eats all the glubbs, etc) - those would just go into a storage bin. Perhaps someone's job (cargo?) would be to make sure that stuff gets back to its proper department.

Not that they necessarily would carry that out of course.

**Comment by SonixApache** [comment]
**Half Minute Hero: Super Mega Neo Climax Ultimate Assistant**

Temp lives would be interesting, though having piles of ash with department gear laying around would confuse a lot of people. That'd need some thought. Lockboxes and purple goo, maybe.

**Comment by Blithering** [comment]
Holomen being expanded on onto this would be great. Have holo emitters in departments that make temporary hologram crewmembers, explaining much easier why they're set to vanish.

**Comment by ghost** [comment]
Literally just port cryo storage. Job slot is freed if you cryo store
