### ISSUE TITLE
Cuffs as Secborg not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24217]
(WEB REPORT BY: blindwatcher REMOTE: 206.221.180.138:7777)
# Revision
12a9198a2be3f8297f3d233c2fc478ba901f3a2a

# Description
Cuffs not working as borg, brah
# Steps to Reproduce
1. Be Secborg
2. Try to cuff.
3. Cancels 25% of the way through.
# What you Expected
Cuffs, brah.
# What Actually Happened
No cuffs.

**Comment by boy2mantwicethefam** [comment]
Already fixed in #24126 which was merged before the round ended
