### ISSUE TITLE
[Defficiency] Where the fuck is the canes and why are latex gloves blue

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#2422]
fuck you duny fix this shit now
thanks

**Comment by Duny-** [comment]
Latex gloves are blue because someone made them blue, if you want white gloves find white gloves faggot
I'll had canes

**Comment by DrCelt** [comment]
>find white gloves
fucking where

**Comment by Duny-** [comment]
On the mime's hands for exemple
Have you ever played this game before? :^)

**Comment by DrCelt** [comment]
>if you want white gloves you've got to rob the mime

well, fine then

**Comment by Duny-** [comment]
>not giving a blowjob to the mime in exchange for his gloves

It's always about violence with you people.

**Comment by DrCelt** [comment]
It is always about violence. which is why the blowjob will be forced and the gloves torn off. But that's another issue

gib cane in medical and white gloves in HoP's closet pls
