### ISSUE TITLE
Cult really shouldn't be able to fire on snowmap

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#24226]
#### Description of issue

Snowmap has a TONS of places to hide, perhaps even more than roid and deff cult. The impossibility of raising an altar in the roid is null and void if you can just raise one in bumfuck nowhere in the woods

Relying on sufficient maint coverage is made impossible unless you have 5+ officers, given how far away everything is ; same for responding to calls or raiding departments

I don't even want to begin to imagine what would be bloodstone hunting on snowmap

**Comment by DeityLink** [comment]
bloodstones cannot spawn on unsimulated turfs so at least that isn't a concern.

**Comment by ShiftyRail** [comment]
Leaves open the podbay, which is far away ; one of the little cubbys in the forest/around the bases (iirc, they're all the same area), and a few other locations which are just a lot more inconvenient to reach than the normal areas in a normal space station

I feel a better kind of snowcult with different mechanics would be a better fit for snowmap. The flaws/difficulties of cult 3 (needing to cover a large area with few people, responding to calls for help fast, as every second matter, and when the stones do rise, having to locate & destroy extremely buffy buildings in a very short time) just don't mesh well with the map.

There are no rechargers in the sec lobbies, for the Angel's sake. Am I supposed to walk back to brig everytime I spot & destroy a runestone ?

**Comment by utilitas-** [comment]
why stop there
cult should not be able to fire on _any_ map.

**Comment by ShiftyRail** [comment]
@utilitas- would never win a vote and even if it did, someone would revert it and have it merged

**Comment by incakola** [comment]
feature

adjust the numbers for snowmap perhaps?

**Comment by agentofzog2** [comment]
Don't remove snowcult before someone actually manages to make a big cult mansion (bonus points for making it public with secret conversion rooms and catching visitors)
