### ISSUE TITLE
Bartender Coat (And Probably Others) Still Broken

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24229]
Icon state is invisible, it's a broken sprite. Its item state (on the wearer) is just a basic winter coat until you toggle the hood.

Hood up sprite is layered wrong, it covers the human's head even when facing down (so you have a black void face)

Apparently can't hold a shotgun, though it's supposed to

**Comment by SonixApache** [comment]
could've sworn i fixed them

**Comment by SonixApache** [comment]
The bartender mob icon only has the south facing sprite.
The paramedic mob icon is missing outright.
Hood thing should just be a single flag.

**Comment by robosperg** [comment]
the shotgun is intentional, its only able to hold the double barrel, bartender has a riot shotgun on snowmap.

**Comment by robosperg** [comment]
can either swap out mapped gun or add to allowed on coat, unsure on which is better way to go.

**Comment by ComradeDispenser** [comment]
@robosperg It's a normal pump action not a riot shotgun. Should just make the coat be able to hold it, the body armor the bartender spawns with can hold it, it's a neat thing that makes snowmap unique.

**Comment by Probe1** [comment]
Just fixed
