### ISSUE TITLE
Wizards Fucked by Cold On Snowmap

### ISSUE THREAD

**Issue by dsfartgeg** [d3athrow/vgstation13#24238]
#### Description of issue
Wizards on Snowmap have to deal with cold, and most of their available attire does not protect from it.   The gemsuit costs 20 points.

#### Difference between expected and actual behavior
Wizards should receive some sort of free protection against cold on Snowtaxi, such as providing eskimo suits or by beefing existing attire against cold.

#### Steps to reproduce
0. do a snowmap
1. maek wizard
2. walk into cold

#### Server revision

Game: d9b0991744980e5ad9cedcc60231f0dba52f4e6b 
Patches: 516247231af6368c2a9a1ba80b61f3000eb4911f 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

[consistency][easy][gameplay][gamemode][oversight][qol][snowmap]

**Comment by Probe1** [comment]
We can easily just add a wizard coat for snaxi.

**Comment by Blithering** [comment]
Will be trying to get outta my spriting funk this weekend, I'll give spriting a snow wiz robe a go

**Comment by Blithering** [comment]
![wizrobe](https://user-images.githubusercontent.com/15067109/65794757-bd447100-e160-11e9-8740-ab5678cb2045.png)
I thought long and hard about how a wizard would keep warm in the snow and this is what I came up with.

**Comment by dsfartgeg** [comment]
Das gut but also ice lichs

**Comment by Blithering** [comment]
This can be closed now, https://github.com/vgstation-coders/vgstation13/pull/24550 gave us not one, not two, but two and a half new cold resistant robes.
