### ISSUE TITLE
Borer can't do shit

### ISSUE THREAD

**Issue by markmce1** [d3athrow/vgstation13#24231]
#### Description of issue
So borers and possibly slimes can't interact with much. Borer can enter a vent, but cant exit. Also can't infest someone as all these action just instant cancel

#### Difference between expected and actual behavior
Expected: Action starts and completes
Actual: action starts and cancels

#### Steps to reproduce
Be borer
Enter vent
Try to exit vent, fail
Get taken out of pipe by human
Can't infest willing human

**Comment by Kurfursten** [comment]
both of these rely on do_after and it is likely one and the same with the #24234 bug
