### ISSUE TITLE
Electrocution is broken

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24233]
- Walk into a shocked airlock, you will take no damage
- Walk into an electrified grille, you will take damage but total health won't be updated so you'll stay at 100%

what the fuck

**Comment by MadmanMartian** [comment]
It's because the damage is dealt to arms, legs, hands, feet, which are no longer a factor of your full health.

**Comment by DamianX** [comment]
so this is working as intended?

**Comment by MadmanMartian** [comment]
Unfortunately yes, It's why I was holding off on the PR while we figured out an alternative downside to burn damage on extremeties, but it was merged

**Comment by ghost** [comment]
Electrocution damage through the arms should also damage the chest/heart and a random leg for immulsions.

**Comment by MadmanMartian** [comment]
Not every race has a heart to damage

**Comment by ghost** [comment]
It could just do more damage to the chest if they don't have a heart, or be a sneaky buff to the two or so races that don't have a heart and don't heal from shocks.

**Comment by agentofzog2** [comment]
Okay so it's not [completely] broken, just mostly broken
You can still die to electrocution but it requires a superhot grid and bad RNG on top of that since you can still survive with 200+ burn damage as long as the vitals don't get 100 damage (which I assume only happens though limb overflow or something)

Still a great example of the "cart before the horse" mentality the c*ders have.

**Comment by tayachiya** [comment]
I guess another related thing - being set on fire doesn't actually damage you either

**Comment by agentofzog2** [comment]
You can also welderbomb yourself and live (some of the time).
Really there's a very long list of stuff that can't reliably kill someone now.

**Comment by tayachiya** [comment]
Did this nerf e-guns as well?

**Comment by agentofzog2** [comment]
> 
> 
> Did this nerf e-guns as well?

Not really  since you can choose which area to target
Well technically damage has a random chance to go to a limb so pretty much everything that doesn't kill in one shot got affected by the change. Though eguns would obviously be less affected.

**Comment by strawberrytan** [comment]
this doesn't nerf stuns but it nerfs everything that isn't a stun and not lethal damage to the head or chest

**Comment by Blithering** [comment]
You could have burn wounds open up if the victim moves around too much, causing it to begin bleeding

**Comment by DamianX** [comment]
The PR that caused this was reverted.
