### ISSUE TITLE
can't exit scrubbers as slime

### ISSUE THREAD

**Issue by Durgen** [d3athrow/vgstation13#24243]
I crawled into a scrubber and couldn't get out of any scrubbers on waste
I'm not sure if this problem would also occur with vents.

I ahelped and Deadharold said it was throwing up runtimes

plz help i am stuck in waste oh god

**Comment by SGuivenne** [comment]
Good job @MadmanMartian 

#24237
#24234

**Comment by MadmanMartian** [comment]
Why are you blaming me? I'm the one fixing the bugs introduced by the doafter change for needhands!

**Comment by SGuivenne** [comment]
> Why are you blaming me? I'm the one fixing the bugs introduced by the doafter change for needhands!


Honestly I just needed to blame SOME coder for this and it was either you, Kurf, or Shifty and they both scare me more.

**Comment by MadmanMartian** [comment]
It was barry that coded it!
