### ISSUE TITLE
Bartender Has Wrong Shotgun on Snowmap

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24242]
revealed by #24229

Bartender got a riot shotty by accident it seems

**Comment by Probe1** [comment]
"accident"

**Comment by Exxion** [comment]
It's always been that way on Taxi

**Comment by ComradeDispenser** [comment]
No Kurf! I told you about the shotgun thing so you could fix it, not take away part of snowmap's unique character!

It's just a regular pump action shotgun, not a riot shotgun.

**Comment by Durgen** [comment]
feature

**Comment by robosperg** [comment]
the regular pumps are riot shotguns, the ones from cargo are combat shotguns

**Comment by Probe1** [comment]
So to be clear what do we want?  Double Barrel or Pump Action on Snaxi?

**Comment by ComradeDispenser** [comment]
Pump action. It's a unique feature of the map.
