### ISSUE TITLE
(SoC Schenanagins) Golem Does not suffer burns from being set on fire by campfire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24248]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
a085e3af93215d4aef6691f88b927d0cad4d6b9f

# Description

For some reason being on fire from the camp fire doesn't actually do damage here.  Every other fire seems to.
# Steps to Reproduce

SoC incident, be golem now, stand on fire
# What you Expected

To die in a fire
# What Actually Happened

I am a walking torch.

**Comment by agentofzog2** [comment]
Golems shouldn't be able to take burn damage. Doubt it was changed.

**Comment by RealestEstate** [comment]
feature

**Comment by Zth--** [comment]
I'm 99% sure this is intended

**Comment by Probe1** [comment]
Please check and see if they are taking fire damage from sources other than campfires like the issue States

**Comment by west3436** [comment]
Golems are fireproof
