### ISSUE TITLE
Hardsuits and helmets should cover foot and mask wear.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#2425]
Sprite clipping issue.

**Comment by Aurx** [comment]
But then you won't have clownmasks visible through spacesuits.

**Comment by SkowronX** [comment]
An exception can be made for that

**Comment by Dr-Explosion** [comment]
Is that exception for clownmasks still in the cards?

**Comment by ComicIronic** [comment]
Yes.
It's being developed along with a wider system for unhideable overlays, like stun gloves.
