### ISSUE TITLE
Snaxi southwest security solar APC is offset the wrong direction

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#24251]
#### Description of issue

![image](https://user-images.githubusercontent.com/8550416/65568584-6b190b00-df28-11e9-857f-b2589139803a.png)

pretty sure you did x = -20 instead of 20
@plosky1

**Comment by plosky1** [comment]
So it's definitely x = 24 on my local version, and looks right too. This has happened before and for the life of me I can't figure out why on the main serb some of the APC's do this, and others don't. It's super frustrating. It can be fixed by replacing it entirely by copy-pasting a different APC.

**Comment by Probe1** [comment]
I BELIEVE it's to do with the specific apc obj being unique for each cardinal direction and it automatically offsets on round initialization but dont' quote me on that, it's been a few years.  Like it's not enough to offset it.  You need to set a var to 1 2 4 8 or something to give it the cardinal direction that it will automatically offset to.  

Which is why we all just copy and paste APCs from other parts of the map like the lazy fuckers we are.
