### ISSUE TITLE
Research outpost airlock vent malfunction

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#2426]
At least on the round I saw it on; The research outpost southern airlock cannot cycle to exterior properly. When cycle to exterior mode is engaged, the vent responsible for the airlock does not switch to siphon mode and stays in output mode. As a result, the airlock never empties. The filling of the airlock and cycling to interior, however, functions as intended. I've even seen a scientist struggling with it even manage to over-pressure the airlock slightly with it.

**Comment by Midaychi** [comment]
This is on box-station, btw.

**Comment by wwjnc** [comment]
Forgot to reference this one; this was addressed on #2675.

**Comment by ComicIronic** [comment]
Reopen if not fixed,
