### ISSUE TITLE
Increase snaxi's player count requirement

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24263]
it's too big

**Comment by ghost** [comment]
It should be at least 20 or maybe even 30 min, right now rounds will drag out forever if there's under 20 players.

**Comment by Probe1** [comment]
We don't really get that many players so 50% of the day it would be closed off.  Then it won't get played as much then it won't get as many updates cause people won't play it and catch bugs or make suggestions..

Why don't we have this talk in a couple weeks when the map has gotten more attention

**Comment by DamianX** [comment]
If you think finding bugs and updating the map is more important than having a good time playing the game, then go ahead and keep things as they are.

**Comment by utilitas-** [comment]
it is the responsibility of the mapper to polish their map to spotlessness _before_ unleashing it on the server
if they are too braindead to even play through their own map, they shouldn't be mapping in the first place

**Comment by SonixApache** [comment]
It's literally a lowpop map except you can fuck off into 'space' easily because there's free 'space' suits at every substation.

I think raising the pop would be a horrible idea.

**Comment by Probe1** [comment]
What should its pop be @DamianX ?

**Comment by ShiftyRail** [comment]
I think giving it the same level of population requirements as metaclub would be a good start.

Snaxi feels alive when I can go into a bunker and see people doing work. If most of the population is confined inside of the bridge bunker, with personnel roaming from one place to another to run an errand, the vastness and emptiness of the place really shows (in a bad way)

The problem isn't that the stations themselves are small, but that they're outdated (snaxi brig is a good example, should probably be redone from scratch.)

**Comment by DamianX** [comment]
What makes snaxi a lowpop map?

**Comment by Probe1** [comment]
Give me a number that you feel is right.  I don't object to putting it with Meta for now.

**Comment by DamianX** [comment]
sure, I don't know the actual values. I just see the number of players and the state of the rounds and draw my conclusions.

**Comment by SonixApache** [comment]
Snaxi is a lowpop map because all the departments are fucking tiny. They were designed to be tiny, because Taxi was a lowpop map.

**Comment by Probe1** [comment]
Metaclub requires 24 people connected to be available.
Snaxi 10.

I asked Pomf to increment it to 15.  If it still feels too empty we can keep going up and up, and we aren't rushing into an overcrowded scenario that Sonix fears or a not enough feedback scenario I fear.

**Comment by Probe1** [comment]
@utilitas- bruh maps are fucking retardedly time consuming endeavors.  It takes dozens of hours to make just the most basic bitch shit that you see the first iteration of.  

No ones going to catch all the bugs themselves.  I agree with not shoveling shitcode on the server and calling it a testmerge WIP LOL but there's gonna be bugs.  Every map, every time.

**Comment by plosky1** [comment]
@utilitas- implying it's not 5000x times easier to let braindead players play and catch bugs for you.

As for pop, I personally think its a high-pop station. Some argue that its lowpop due to taxi being a lowpop station, but the entire idea behind snaxi is that you can leave station and fuck around in the world, which admittedly is pretty big.

I wouldn't mind keeping pop reqs low IF I could map the stations much closer and make the comet smaller, but last time I tried that people threw shitfits.

**Comment by Probe1** [comment]
![image](https://user-images.githubusercontent.com/8550416/65814548-497e8480-e1b1-11e9-9552-2052340c1f5e.png)

**Comment by DamianX** [comment]
Seems good to me now.

**Comment by DamianX** [comment]
On second thought, should probably require 50 or 100 players

**Comment by jknpj** [comment]
:thinking:

**Comment by brndd** [comment]
based and shitxipilled

**Comment by Kurfursten** [comment]
It was raised to 30
