### ISSUE TITLE
Snowmap research outpost metal/glass stack in maint only has 1 amount in each sheet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24266]
(WEB REPORT BY: probe1 REMOTE: 206.221.180.138:7777)
# Revision
296097048c158a5f8057f5059d6cf9a6cc1d20a6

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
no longer true
