### ISSUE TITLE
Polyacid kudzu breaks on snaxi

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#24260]
It melts the floor then stunts itself. Kudzu I grew had max temperature resistance. Pretty pissed. fuck your snow map

**Comment by DrSnips** [comment]
God forbid there is something that stops it.

**Comment by dsfartgeg** [comment]
should have grown it with cold resistance lol

**Comment by Killette2** [comment]
Kudzu that can survive space due to temp resist and mass temp temp condition variation doesn't work on much warmer snow? Looks legit

**Comment by MadmanMartian** [comment]
Might be it can survive space due to a bug?

**Comment by Killette2** [comment]
It has temperature resistance and pressure resistance levels, with the default pressure resist mentioning that it's so people can't syphon kudzu out. Maybe if I gave the kudzu insane health too it might help.

**Comment by Killette2** [comment]
![image](https://user-images.githubusercontent.com/5169310/65737877-ed7f0780-e0ad-11e9-842a-91748de8eab0.png)
If powercreeper can do it...
I'm still very convinced that it's a bug having to do with eating the tiles rather than the snow itself, due to polyacid kudzu always surviving the space that it makes.

**Comment by DrSnips** [comment]
Hm I wonder why the extremely buggy since day 1 and hardly fixed electric vines can do that.

**Comment by Killette2** [comment]
Now I see that I have downvotes to this with quotes such as "God forbid there is something that stops it." and "should have grown it with cold resistance lol". As these concerns are valid for kudzu growing over snow, let me address them so maybe your vote will change.

Let's start off by saying snow is -50 celsius. That is a blistering cold temperature and I can see why it might make kudzu have trouble growing, or kill it near the start when it still has low health. After all if you plant kudzu in a room that has high heat, improper temperatures, or improper lighting even it may die off before it even has the chance to expand! Now let's see if we can make kudzu that will even survive -50c before going further. For plants which read in kelvin we must hit 223.15k 

First we start off with a basic seed. The generic "ideal heat" for plants is 293k, or 19.85c. This can definitely not survive in the snow due to such a drastic difference. Whatever, let's just order a bunch of exotic seeds from cargo. Surely if we order seeds in bulk we can win with some simple RNG of seed creations!

So we go to cargo and order 4 or so crates, however there is a problem in the code. When seeds are generated from cargo, they get to pick a heat from [ideal_heat =       rand(273,313)] (source is line 122 in https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/seed_datums.dm)
There is also a temperature tolerance of 10-30, which would lower you by 30 at best with extremely good RNG, stacking a 1/20 chance on top of a 1/40 perfect chance, but then you'd only get 253 at best. This is STILL not enough luck to survive the harshness of snow, so exotic seeds are out of the question.

Looks like our final option has to be using mutagen. But you can't just use mutagen in this case. You must abuse it. I'm talking about emptying chemistry dispensers and pray that you get the results without your department becoming a blazing n2o plasma fire with vines biting off your flesh. Let's go over what we must do to reach our goal. Following is the code to mutation. Now I am not a coding expert, so things such as clamps make the exact math a bit shaky, but I implore that for results you need over 100 units of mutagen in your tray while also feeding it left4zed to counter the mutation resistance that builds up, and also diethyl, antitoxin, and nutriment to prevent your plant from dying from the radioactive sludge you're continuously dumping inside of it.

https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/hydroponics_mutations.dm

First with your gigantic puddle of mutagen, you will want to roll MUTCAT BAD2. That will randomize your plants temperature that it thrives in. Now when you roll this, instead of the 5 other categories that you can roll, you must then hope that out of that category that it rolls temperature instead of the 4 other submutations that that category contains. This will completely randomize your seed's temperature anywhere between seed.ideal_heat = rand(253,343). There are no straight upgrades, since this is completely random it can help you or hurt you by extremes. Even if you roll a perfect 1/90 your roll is still not lucky enough to grow kudzu on snow. Now we must go back and roll another one of the 6 categories under the MUTCAT GOOD category, which has 9 total subcategories. You want to roll the ideal heat and pressure category, which of course goes off of diminishing returns clamp math, and while this goes up to 800 there's two catches. The first, being due to the way the mutagen clamp code works that will never ever fucking happen. The second is that you can never see this value. The only way you know if you're even close is once it goes over 50, where the seed will then scan as "is well adapted to a range of temperatures". Now a botanist that plays with mutagen is rare to ever find this, and I feel I have done it enough to stake this claim. Now if you subtract a plant that is adapted to temperatures to at least 50, you need to get an ideal heat of at least 273k, which while that is an exotic seeds perfect roll, good luck buffing your seeds temperature variation resistance without completely rerolling that. You might want to say you can just play it safe and use low amounts of mutagen to keep the rolls out of MUTCAT BAD2, but if you do that you will never use a high enough mutagen value to get the clamp to your desired number, especially since you then have to do a balancing act of countering the mutagen resistance your plant has developed and the mutagen you're pouring in. Good luck if you're not a super computer.

To sum this up you basically need RNG (mutcat bad2 on a d6) on top of RNG (mutate ideal temperature trait on a d5) on top of RNG (mutate ideal temp trait to not be counterproductive on a d90) on top of RNG (mutcat good, d6 again) on top of RNG (temp resist, d10) and then pray you're using enough mutagen without your needed RNG or random fuck you RNG reversing your previous RNG. You might think this is insane.

Well I did it.

![2019-10-10_01-29-35](https://user-images.githubusercontent.com/5169310/68181737-6d7a7600-ff66-11e9-898e-51efc9950aac.png)

I defied all odds and made a plant under these absurd conditions. The plant was able to quickly mature into it's fruit bearing state. This is it's maximum growth level and represents that the plant was able to survive and thrive on the snow. However I am assuming that because snow is unsimulated that that is the reason that all my hard work has gone to waste. I have made kudzu that defies all odds and should be able to spread on this snow, but it just sits there growing in place free for the picking of anyone who needs fruit on the go. All of this research was done to fight the people who argued that snow should just magically stop a plant that grew to defy all odds. People who just because people like GermanSanta who make half-assed ez splice kudzu, make such blank statements that undermine the work put into this art. Plants that do not wither when they are exposed to space after being fully grown. If someone is willing to put themselves through all of this insanity, why should it not be allowed? Many jobs when enriched with high octane autism, including botany on other maps, can devastate the station with much less work. I do believe that this is a bug and in fact not a feature, but a challenge to all great botanist out there.

![dreamseeker_2019-10-10_01-33-09](https://user-images.githubusercontent.com/5169310/68182291-6ef86e00-ff67-11e9-9fa0-2a8c66631253.png)

**Comment by DrSnips** [comment]
Cool autism story but I'm not really sure what to take away from that. You could have just var edited it if you wanted to point out its not due to one factor.
A completely open z-level and a plant that can grow to fill any space, including planting multiple of them to speed it up, will undoubtably create a negative server wide experience. You would be hard pressed to find someone that would legitimately enjoy having to fight a whole 500x500 z-level of vines that can grab you from range and then basically instantly kill you if you don't have a mech. I personally don't like situations vines create ever. It creates a less interesting blob round along with the ability to have near infinite sources that can easily be made to not care about their environment at all.

**Comment by Killette2** [comment]
You're supposed to take away that it takes effort to do on snowmap. While you can easily goldcore bomb, viroloose, plasmaflood, mech murderbone, emagged secborg, and more under 30 minutes, vines with this amount of luck and effort take well beyond half an hour which was the whole point of explaining the process. It actually takes time instead of varediting up a scenario and claiming it can be done just as fast. There are multiple cheese counters to vines that you aren't listing, even more for the halfassed ones that you think can be pumped out in an unrealistic timeframe, and your argument of "I don't like" can be applied to singulo, plasmaflood, etc. It's intended to be able to end rounds if you work hard, else the crew can easily stop it and it's far less rushable than other things that can make the round gunk within minutes.

**Comment by Killette2** [comment]
It can grow on the snowturf now?

**Comment by Kurfursten** [comment]
The opposite, powercreeper dies in snow now, consistency achieved
