### ISSUE TITLE
powercreeper still lags a lot

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24279]
![image](https://user-images.githubusercontent.com/6307265/65810399-3a480880-e1aa-11e9-8099-52c2363529e1.png)

**Comment by DrSnips** [comment]
When are we just going to <strike>remove</strike> detain powercreeper until its fixed?

**Comment by DamianX** [comment]
This was because it was on snaxi and expanded to cover the entire map, but that can't happen anymore.
