### ISSUE TITLE
Snowmap: weird bar areas

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#24289]
![Untitled](https://user-images.githubusercontent.com/25846834/65819548-0f7ea400-e1ec-11e9-9d76-5a5afb6a7d9d.png)
-weird 4-tile area in the bar for the kitchen tables, why
-that botany-kitchen junction is weird too, should probably be kitchen area before the door, no?

**Comment by DamianX** [comment]
🤔

**Comment by utilitas-** [comment]
Zero polish.

**Comment by Kurfursten** [comment]
probe fixed
