### ISSUE TITLE
Space Ninja takes name too literally on snowmap

### ISSUE THREAD

**Issue by TheManNamedTom** [d3athrow/vgstation13#24280]
Late joined and rolled Space Ninja but my airbag launcher thing spawn in space and then got stuck outside all the stuff in the map.
![atleastnowweknow](https://user-images.githubusercontent.com/20178892/65810598-4b792100-e17a-11e9-8c95-8b9e020cbfda.PNG)
help

**Comment by SonixApache** [comment]
@DrSnips dojo when

**Comment by Probe1** [comment]
Since it's handled via the code and not the map I can't do anything for this at this time.

**Comment by Kurfursten** [comment]
no longer applies
