### ISSUE TITLE
Autolathe Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24284]
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
296097048c158a5f8057f5059d6cf9a6cc1d20a6

# Description:

Autolathe doesn't inkate resources, happened 2 times, both times ahelped

# Steps to Reproduce

No idea

# What you Expected

autolathe to take materials

# What Actually Happened

nothing

**Comment by Probe1** [comment]
We should add a message when it's full

**Comment by nervere** [comment]
there's a message for it being full now
