### ISSUE TITLE
Pick-up verb allows you to remove your loyalty implant

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24307]
(WEB REPORT BY: bobthomas REMOTE: 206.221.180.138:7777)
# Revision
5980f011aa6f657f30e24d85b1e7c2c7c18ea8dd

# Description
pick up verb is able to remove your own loyalty implant
# Steps to Reproduce
go to object tab and hit Pick up and select loyalty implant
# What you Expected
for this not to work
# What Actually Happened
it worked

**Comment by Probe1** [comment]
What

**Comment by MadmanMartian** [comment]
``/mob/living/verb/verb_pickup(obj/I in view(1))``

The problem here is that obj/I in view(1). I'll fix this now
