### ISSUE TITLE
snaxi: weird lighting

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#24311]
![Untitled](https://user-images.githubusercontent.com/25846834/65840622-2eaf2b80-e2e9-11e9-9c28-6632f9bf76eb.png)
This is in the engineering station.
Emergency lights are kinda weird. I believe that's an area var?
[snowmap]

**Comment by Probe1** [comment]
![image](https://user-images.githubusercontent.com/8550416/66209609-b5fff480-e685-11e9-8bea-c3e443886a46.png)


_why_
