### ISSUE TITLE
Snaxi: wrong access for chaplain's office

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#24325]
#### Description of issue

It's public access rather than chaplain access.

**Comment by Kharkov72** [comment]
That's a [Feature], everything behind the window is his actual office. Think of it like a communion room.

**Comment by Probe1** [comment]
I reviewed it and it makes more sense as Kharkov described it.  The area is too small and is better disposed to having two public rooms rather than one small chapel.
