### ISSUE TITLE
Player Minds Can Get Stuck in Goofkitchen Machines

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24320]
In the case that a player is monkeycubed and that cube is used to make candy, cereal, etc. their self gets left behind inside the candy/cereal machine instead of coming out as food. This is because the human is still stored inside the mobcube, and presumably goofkitchen things don't properly delete the mobcube when creating the new candy/whatever.

**Comment by SGuivenne** [comment]
How is one monkeycubed?

**Comment by Kurfursten** [comment]
emagged trash compactor

**Comment by Probe1** [comment]
Machine spirit.
