### ISSUE TITLE
You can attempt to unbuckle when sleepy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24332]
(WEB REPORT BY: fuzzynut51 REMOTE: 206.221.180.138:7777)
# Revision
0d0e6f7f6e2c87612744451239c9cb785a9c1149

# Description
You can attempt to unbuckle from a bed when you are sleep
# Steps to Reproduce
Sleep while cuff to a bed
# What you Expected
To have no interaction with the world as I sleepy
# What Actually Happened
I could do something such as unbuckle from my bed

**Comment by Killette2** [comment]
It's so easy I can do it in my sleep
