### ISSUE TITLE
If you random body and roll no underwear your preferences will break for good

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24337]
(WEB REPORT BY: morphi REMOTE: 206.221.180.138:7777)
https://i.imgur.com/FJJIlIc.png

Can't do anything about this, if I open the General Settings through the menu on top I can't load/save another slot, nothing happens, though everything else but the Character Settings work. 

Took a look at this myself and it's happening because on https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/new_player/preferences_setup.dm#L16 it tries to do list[0] which doesn't work on byond because on another file it'll do list[underwear] and if it's 0 it won't work because lists on BYOND start at 1, and if you save setup after this shit happens then the only fix is switching accounts (and hoping as a new player you don't randomly roll no underwear as well)

**Comment by Intigracy** [comment]
pomf fixed the preferences side of this, should be fixed for everyone now
