### ISSUE TITLE
Secborg trader upgrades

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24343]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
eed2edfacf52a2caf6b0cacfdcbdd50763840250

# Description
One of the special upgrades deletes secborg's taser, replacing it with a lawgiver instead. The lawgiver itself needs to be DNA secured to the CYBORG. And secborg's gripper doesn't reach inside boxes, making it incredibly hard to grab grenades

**Comment by jknpj** [comment]
I don't follow, the gripper is supposed to work like that and the lawgiver works for them just like for humans, submit your sample before using it, dum dum.

**Comment by Probe1** [comment]
All it needs then is a check to see if the user is silicon and flavor text since they don't have DNA.

**Comment by tayachiya** [comment]
But is the lawgiver supposed to replace a taser?
Because I had only that, no other way to tase. And the lawgiver requires regular charger as well, which is silly with how you need to recharge yourself and the gun at two different places.
And my bad, I assumed medborgs can reach inside boxes to pick up any beakers, but it seems its a vial specific thing

**Comment by Probe1** [comment]
Oversight possibly I don't know I wasn't around when this was added.

**Comment by Blithering** [comment]
I think the lawgiver replacing the taser is intentional, as the detective module follows the same pattern, replacing taser with revolver, and having two tasers would mean a LOT of consecutive shots without recharging.

**Comment by jknpj** [comment]
@Probe1 when you get the upgrade, you DO get your own silicon DNA

https://github.com/vgstation-coders/vgstation13/blob/c4afda3e65496b738bcddb3a7798175e2d249c1e/code/game/objects/items/robot/robot_upgrades.dm#L443-L446

Also yes, it is intended that the taser gets replaced, as it also has stun bullets. You're able to remove the energy pack from your lawgiver and put it inside gun chargers with your gripper.

https://github.com/vgstation-coders/vgstation13/blob/c4afda3e65496b738bcddb3a7798175e2d249c1e/code/game/objects/items/robot/robot_upgrades.dm#L429-L433
