### ISSUE TITLE
Snowmap Signs are Shit (SSS)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24345]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
eed2edfacf52a2caf6b0cacfdcbdd50763840250

# Description
The science and medbay signs on the glass grilles point down but those places are up.
# Steps to Reproduce
bitch look at it
# What you Expected
sign = up
# What Actually Happened
sign != up

**Comment by Probe1** [comment]
Gross there's only _one_ direction for each.
