### ISSUE TITLE
rezadone healing oversight

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#24355]
[easy] [autism]

#### Description of issue
rezadone first heals at `data` (which is used for how many ticks it's been in the body) "1 to 15" and then for "15 to 35"
rezadone has an overdose_tick = 35 and on_overdose happens on `(overdose_tick && tick >= overdose_tick)`

one of two things is happening here. one is dumb and the other one triggers my autism:
1. the ranges in the if-statements are inclusive on both limits, which means that rezadone heals for an even 7 units but the last tick also triggers on_overdose. this is dumb.
2. the ranges in the if-statements are exclusive on either the upper limit or both limits, which means that on_overdose only triggers once rezadone stops healing, but rezadone only heals for a maximum of 6.8 units (or 6.9 if you abuse reagents metabolising at doses as low as `custom_metabolism * 0.5`, if that's still a thing). this is what gives me the strength to escape from my wrangler and write this issue.

solution: ensure that rezadone runs for an even 7 units and it doesn't overdose during its healing period.

#### Steps to reproduce
ask again when you turn 18

#### Specific information for locating

[rezadone declaration](https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm#L3025)

#### Length of time in which bug has been known to occur

since like e2fac2ceea14378c0a98cebe03e7b9951040a6c2 when the current OD system was added

#### Server revision

96a76a97b6f96ca7c86834fe0bc1e2b5a7a1ce9b

**Comment by Kammerjunk** [comment]
actually it's probably option 3: `data` initialises to 1 but `tick` initialises to 0 (probably - it's declared in the base /reagent declaration but never actually set to 0, only incremented on `metabolize()`), which means that rezadone should heal for all 7 units *and* on_overdose should only trigger once it's done healing.
that's an annoying difference

**Comment by Probe1** [comment]
Another issue resolved by the crack team of mad dev ops from your local /vg/ brain trust.

**Comment by Probe1** [comment]
![tenor](https://user-images.githubusercontent.com/8550416/66222578-7ba35100-e69f-11e9-86c6-5206e46160f8.gif)
