### ISSUE TITLE
Clown Crayon doesn't retain color selection, reverts to black.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24359]
(WEB REPORT BY: lemonthefruit REMOTE: 206.221.180.138:7777)
# Revision
f1da39ed6d91ae815f26df4596947f64367b65d7

# Description
The clown's rainbow crayon doesn't retain colors you choose, it reverts the two colors that you pick back to black.

# Steps to Reproduce
Be clown
Pick up crayon
Use crayon
Select colors
Notice that the colors revert to black

# What you Expected
For my colors to be the bright and colorful ones that I selected.

# What Actually Happened
The colors reverted to black.

**Comment by Zth--** [comment]
Can't reproduce
