### ISSUE TITLE
The genius that made frequencies randomised forgot to give departement members their frequencies.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24366]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
36a8c0570da05649cc94fc8cbc805aa719754133

# Description

Good job.

**Comment by ShiftyRail** [comment]
This is most definitively an oversight. You used to be able to toggle radios to Mr. VALID. Now you can't.
Feature loss.

**Comment by MadmanMartian** [comment]
![image](https://user-images.githubusercontent.com/30557196/66258223-6b23d100-e79a-11e9-82b4-67ae383f4ff6.png)

**Comment by ShiftyRail** [comment]
That's a feature and it has always been.

**Comment by MadmanMartian** [comment]
I was asked to make it random frequency precisely because assistants were just using SBRs and the wiki to listen in on security.

Making it random goes both ways.

**Comment by ShiftyRail** [comment]
No matter, I'll fix it tonight

**Comment by boy2mantwicethefam** [comment]
Shifty "balance for thee but not for me" Rail

**Comment by Exxion** [comment]
I really don't see how giving the frequency only to department members somehow goes against randomizing it

**Comment by ShiftyRail** [comment]
I don't care about random freqs one way or another, I'm simply against feature loss.

**Comment by Probe1** [comment]
Please do not have open and close Wars.

**Comment by MadmanMartian** [comment]
>I'm simply against feature loss

You removed objectives because you didn't like them
