### ISSUE TITLE
Admins rigging votes is not logged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24376]
(WEB REPORT BY: absolutely REMOTE: 206.221.180.138:7777)
Admins editting the vote screen vote counts is not logged anywhere, it's hard to hold someone responsible for sabotaging snaxi votes when there's no logs. Just the other day someone added 10000 votes to their favourite pick and nothing came of it aside from everyone being forced to play their map.

**Comment by MadmanMartian** [comment]
Could we get a specific date for this? Any event of an admin changing a variable is logged in the admin-logs for that date

**Comment by Kurfursten** [comment]
he means with the rig vote button, it sends an adminwarn to the other admins but doesn't get logged
