### ISSUE TITLE
Superimmune mice

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24377]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
c3e49c7f3241a7291d2b38975c35f51da2f99573

# Description
Maintenance mice can't be infected with ANY kind of disease
# Steps to Reproduce
Be virologist. Catch mouse. Try to use it as lab rat. Inject Maintenance Mouse with any kind of disease. It doesn't get infected.
# What you Expected
I expected the mouse to get sick
# What Actually Happened
The mouse did not get sick.

**Comment by DamianX** [comment]
not much to be tested here
if a mouse spawns in maintenance it has a 20% chance to be infectable
if it isn't, it will never get sick
the only question is whether this is intended

**Comment by DeityLink** [comment]
@DamianX I'd argue that it isn't intended in the original design of nu-viro but since mice were nerfed because of player abuse, it's kinda been how it works since then. Only Balbc mice can get infected by diseases.

**Comment by DamianX** [comment]
What's a Balbc

**Comment by DeityLink** [comment]
lab mice https://en.wikipedia.org/wiki/BALB/c

they were added as a new mouse species with nu-viro. They look similar to white mice but have a few different traits.

They are exclusively spawned from either lab mice cube or the Virologist's pet.

**Comment by west3436** [comment]
Feature as Deity pointed out; only lab mice can get infected with diseases.
