### ISSUE TITLE
Requests for Next Batch of VOX Words and Announcements

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#24387]
Request VOX words and announcements here. These will be included in the next batch of VOX words/announcements, delivered on a (hopefully) regular basis.

**Current lists:** [announcements](https://github.com/N3X15/ss13-vox/blob/master/announcements.txt), [words](https://github.com/N3X15/ss13-vox/blob/master/voxwords.txt)

**Mispronunciations:** Lots, please fire me a note if you find one.

**Features**: Introduction of male voice and *possibly* a separate voice for automated announcements.

**Comment by brndd** [comment]
I don't know how much bloat you're willing to add to this list, but I checked it against [the 1000 most common English words](https://gist.github.com/deekayen/4148741) to see which ones were missing, and this is the result: https://gist.github.com/brndd/ba4fb6f05eaf77f5d6e21d5db47661f9 — 690 words all in all.

This is in order from most common to least common, so if you want to add only some of them, truncating the list is a good place to start.

Also, a personal request not on the above list: "adjust"

**Comment by brndd** [comment]
And while I'm here, how about adding common suffixes so you can kind of conjugate words. Stuff like "-ing", "-ed", "-es". It may or may not sound kind of shitty in-game though I guess.

**Comment by SageOfLight** [comment]
Penis as a separate word from the abortion rant.

**Comment by Dacendeth** [comment]
scrungularity

**Comment by N3X15** [comment]
Conjugates don't work well, as there's a necessary pause between words that can't be easily trimmed, so it just ends up sounding all fucked-up.  Each conjugate has to be added in as a whole word. [Example](https://github.com/N3X15/ss13-vox/blob/master/voxwords.txt#L80-L83)

**Comment by DiscountDirtyDan** [comment]
chad
virgin
gang
deff
box
meta
scrungularity
packed
snow

It'd be a fuckton of work but I think it'd be really cool if certain foods and drinks were added to the VOX system as well so the AI can say shit like "Gargle Blasters in Bar" or "Deep Fried Security Ass at Medbay" and what have you.

**Comment by N3X15** [comment]
100 words from @brndd 's list added, plus a few conjugates. Working on the others now, will probably need to add a pronunciation guide (AKA Lexicon entry) for scrungularity so it may be a bit.

**Comment by N3X15** [comment]
Well, that turned out better than expected
https://www.nexisonline.net/downloads/scrungo-preview.ogg

**Comment by ded-game** [comment]
_dump it_

**Comment by TothBrush** [comment]
door
stuck
please
i
beg
you

**Comment by N3X15** [comment]
@TothBrush All of those words except beg are already in.

**Comment by utilitas-** [comment]
https://pastebin.com/2i4rv3dt
These are all the words missing that are necessary to recite the entirety of Smash Mouth - Allstar.
For illustrative material, see: https://www.youtube.com/watch?v=FTRB7Vkc81k

**Comment by ArchSunder** [comment]
cock
ball
torture
cringe
waifu
bootyborgs
gorillionaires
coomer
ahelp
thumb

**Comment by SGuivenne** [comment]
The following are words I've found missing when trying to do either shilling, thematic voxes, or in some cases begging for mercy from the crew or watching the world end.  Some are more useful than others.  Particularly important are oh, Stop, please, Reminder, into, and Asteroid.   All of these are useful regularly in conversation or denote a region.


Mommy
Daddy
Please
Stop
Oh
God
Satan
Devil
Priest
Rabbi
Imam
Send
Nudes
breaking
Antimatter
Carp
Fish
Void
Spooky
Ghost
Demon
Discount
Dan
Dans
Buy
Purchase
Consume
Evolute
Laugh
Laughing
Violence (Jesus christ how do you not have this one)
Android
Monster
Vine
Into
Music
Moon
Different
Monolith
Asteroid
Deceased
Reminder
Chopper

**Comment by N3X15** [comment]
@ArchSunder no fun allowed
@SGuivenne  on it

**Comment by Exxion** [comment]
I need to point out that the copypasta is "scrungulartiy", not "scrungularity"
The latter honestly sounds funnier though

**Comment by brndd** [comment]
I want to point out that this is a thing that TG made and uses https://raw.githubusercontent.com/tgstation/tgstation/master/sound/roundend/scrunglartiy.ogg

**Comment by utilitas-** [comment]
That sounds modified. [This one sounds like the original.](https://raw.githubusercontent.com/Metastruct/garrysmod-chatsounds/master/sound/chatsounds/autoadd/ss13/how%20do%20i%20set%20up%20the%20show%20do%20i%20set%20u%20p%20the%20singu%20how%20do%20i%20setup%20the%20sco%20i%20do%20i%20setup%20how%20i%20the%20scrungulartiy.ogg)
