### ISSUE TITLE
Miner's Equipment Vending Machine: "Eats" ID Cards

### ISSUE THREAD

**Issue by omeno** [d3athrow/vgstation13#2438]
Sometimes when you insert your ID card into the Mining Equipment Vending Machine it won't register than an ID has been inserted, so you can't eject your ID to get it back. You can try inserting someone else's ID and then ejecting, or just repeatedly exiting and opening the Vendor's windows to try to get it to register your ID within it but it doesn't always work.

**Comment by Killette2** [comment]
Can confirm that my ID was eaten once

**Comment by Intigracy** [comment]
Got fixed by something somewhere.
