### ISSUE TITLE
Beedot Backslash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24389]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
3ae5169ef5f2314ad34b17357b3398305f73ddef

# Description
AI VOX says "B" as "BeeDOTbackslash"
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by N3X15** [comment]
Fixed for next VOX batch update

**Comment by N3X15** [comment]
This was fixed.

**Comment by nervere** [comment]
N3X15 says this was fixed so I'll close this. Thanks to @Inorien for bringing this issue to my attention!
