### ISSUE TITLE
White airlocks sound

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#2439]
Possibly a part of the airlock sound refactoring, white doors e.g. primary tool storage now have the windoor noise instead of the airlock noise.

Maybe deliberate?

**Comment by ComicIronic** [comment]
Oddly enough, the code for the windoor noise has always been there, apparently.
I think the airlock sound refactor just removed the airlock sound playing over it.

**Comment by IratePirate** [comment]
That is very weird.

**Comment by Duny-** [comment]
Glass airlocks doing this sound makes more sense to me

**Comment by SkowronX** [comment]
It was like that on bay when I played a round there. Seemed deliberate.

**Comment by clusterfack** [comment]
From the code it seems it should have always done that. The change I made to the sounds shouldn't have really affected anything.

**Comment by IratePirate** [comment]
Well i guess it doesn't really matter then. Its a less obnoxious noise anyway.
