### ISSUE TITLE
Cannot equip oxygen tank on Captain's armor suit storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24391]
(WEB REPORT BY: bobthomas REMOTE: 206.221.180.138:7777)
# Revision
1f942ee419127ff2360ee9eec323f20afae210c0

# Description
exactly what it says
# Steps to Reproduce
try to put an oxygen tank on your captain's armor
# What you Expected
for it to work
# What Actually Happened
it doesn't work, please fix

**Comment by Killette2** [comment]
Only the small ones fit. This is an age old joke

**Comment by Blithering** [comment]
This has been brought up before, I think the gist of the verdict was that the caps armour is less an armoured space suit, and more a suit of armour that is space proof as an afterthought.

**Comment by Intigracy** [comment]
Not enough support for changing it to let big tanks in.
