### ISSUE TITLE
Changing the timer via the "emergency shuttle panel" sends the announcement again

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24408]
#### Steps to reproduce
- Call the shuttle
- Change the ETA
- Get a second big PRIORITY ANNOUNCEMENT "The emergency shuttle has been called."
- now everybody knows you're a shitmin

**Comment by SonixApache** [comment]
i knew this was going to happen when I saw that PR

**Comment by Zth--** [comment]
This is not a bug, this is clearly intended behaviour.
How should we approach this? What if the admin wants to notify the players instead of silently modifying the timer? A new flavour message like _"The emergency shuttle found a shortcut. It will arrive in X"_ could do it

**Comment by DamianX** [comment]
Sure, sounds good.
Once you set the timer you get an `alert("Do you want this to be announced?")`.
If you click yes, you get _The emergency shuttle found a shortcut. It will arrive in X._ if it's lower than the current time left, and something like _The emergency shuttle has been delayed. It will arrive in X._ otherwise.
Add a cancel option while you're at it.
