### ISSUE TITLE
All Wall Interocoms are set to default

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24400]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
3905d226396809be9254752f0677fc11b9f995ea

# Description
Every single wall intercom is set to common, even the AI's. It's very shit. Why would every single wall mounted intercom in an AI core be set to common. This is every map. Also, every department. Please fix.

On another note, AI's don't know all frequencies. Can we add that to the notes of the AI>
# Steps to Reproduce
try and figure out the freqs as AI, dont figure them out and ahelp
# What you Expected
freq's to be relevent to their locations
# What Actually Happened
every single intercom is set to common

**Comment by Probe1** [comment]
duplicate https://github.com/vgstation-coders/vgstation13/issues/24306
