### ISSUE TITLE
you can make copies of brains

### ISSUE THREAD

**Issue by 9percents** [d3athrow/vgstation13#24411]
#### Description of issue

brains inserted with an inactive hands don't disappear

#### Difference between expected and actual behavior

brains gets inserted and not in your hand

#### Steps to reproduce

have a corpse in surgery
open head
take out the brain
place the brain inside
while it's in progress, switch hands

#### Server revision

4a5a89e5cb951946dfd5b119aaf18989a37d0e5e

**Comment by jknpj** [comment]
thanks, barry

**Comment by ghost** [comment]
it's loose?

**Comment by ShiftyRail** [comment]
Worth noting that it's seamless for the player inside the brain. No drifting.

**Comment by Cyadox** [comment]
Tested and can't reproduce. Swapping hands during insertion always removes the brain in whatever hand it was in. (And likely fixed before my PR)
