### ISSUE TITLE
Snowman cold attacks affect crew with cold resistance power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24415]
(WEB REPORT BY: smed REMOTE: 206.221.180.138:7777)
# Revision
4a5a89e5cb951946dfd5b119aaf18989a37d0e5e

# Description
If you have the cold resistance power, a snowman can still make you hypothermic
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Zth--** [comment]
https://github.com/vgstation-coders/vgstation13/blob/4a5a89e5cb951946dfd5b119aaf18989a37d0e5e/code/game/gamemodes/endgame/xmas/snowman.dm#L113-L120
