### ISSUE TITLE
blind spot in AI Eye near MoMMI Nest

### ISSUE THREAD

**Issue by YakumoChen** [d3athrow/vgstation13#2443]
The MoMMIs made a room during one shift, and despite building a camera in there, sending a borg in, or watching through MoMMI's camera I could not see into the room except a few squares.
![corrogated colony alpha 2015-01-05 045620](https://cloud.githubusercontent.com/assets/10399117/5611674/953175f2-9497-11e4-94e7-7769269d36d3.png)

**Comment by ComicIronic** [comment]
Was the room given an area with an APC?

**Comment by AutismSpider** [comment]
Yes the room had APC and Air Alarm.

**Comment by clusterfack** [comment]
This is probably going to be hard to fix without knowing how to reproduce it. As far as I know you can add cameras to other areas just fine.

**Comment by Intigracy** [comment]
I've been building cameras for the AI lately and haven't had any issues with this sort of thing.

They may have built the camera with a modified network rather than the default SS13.

**Comment by ConkerDev** [comment]
Has this issue been reproduced since then?

**Comment by Cisrox** [comment]
Closeable. It's apparently fixed.
