### ISSUE TITLE
Roid Warden Locker still has .45 ammo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24436]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
c7a7a2a1f03c9d1d0fcc7715c9915e616b238af4

# Description
Some mapper goons took my beloved .45, my queen, and replaced her with a rancid NT Glock Custom. Though I have many issues with this, the main problem is a definitive lack of .380 ammo in the locker. Instead, the .45's ammo is still in there. This is cruel, and only reminds me of the loss of a loved one.
# Steps to Reproduce
Go to warden's locker and look at it
# What you Expected
To have an ammo that fits my new ""gun""
# What Actually Happened
I cried in the corner of the room, wishing I still had my .45 with me.

**Comment by calzilla1** [comment]
What PR changed that anyways? Why remove the .45?

**Comment by SkowronX** [comment]
.380 fags cant handle the stopping power of .45

**Comment by cloutcode** [comment]
#23711 is what changed the gun
