### ISSUE TITLE
old AI VOX sound effects missing

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#24434]
#### Description of issue

non-exhaustive list of missing sounds:
doop
bloop
dadeda
bizwarn
woop

#### Server revision
Game: 55c04da5a9a6e99aaca74dabcf0bb5e834778da7 
Patches: dc0912f2159f3b4905fa12025e9f5d5d4fa9ed55

**Comment by Probe1** [comment]
@N3X15

**Comment by N3X15** [comment]
On it.
