### ISSUE TITLE
Can't talk as Cyborg named Epic Hacker Bot 9000

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24445]
(WEB REPORT BY: tokanova REMOTE: 206.221.180.138:7777)
# Revision
d3064c0b45821ce39c1c1e12380e16d7788dd126

# Description
I have no idea if my name has anything to do with why my borg was unable to talk. I tried setting my language to Common and then tried pressing reset and got the message 'You try mouthing a few words to yourself before realizing you have no idea how to speak . Idiot.' back.
# Steps to Reproduce
Be a cyborg named Epic Hacker Bot 9000
Try to talk, fail
Try to reset current language, be called an idiot who knows no langauge.
# What you Expected
To be able to talk
# What Actually Happened
I sure couldn't talk.

**Comment by Zth--** [comment]
He's runtiming

> [00:44:45] Runtime in , line : bad arg name 'forced'
> proc name: say (/mob/living/silicon/say)
> usr: Epic Hacker Bot 9000 (tokanova) (/mob/living/silicon/robot)
> usr.loc: The floor (212, 254, 1) (/turf/simulated/floor)
> src: Epic Hacker Bot 9000 (/mob/living/silicon/robot)
> src.loc: the floor (212,254,1) (/turf/simulated/floor)
> call stack:
> Epic Hacker Bot 9000 (/mob/living/silicon/robot): say("Nice", null)
> Epic Hacker Bot 9000 (/mob/living/silicon/robot): Say("Nice")
