### ISSUE TITLE
CE rig light not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24448]
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
13f0cba75837b1bd5458907f1e7e5de458746336

what it says on the tin

**Comment by DrSnips** [comment]
I bet $5 he took the helmet off by hand and it became unlinked from the suit so it stopped working.

**Comment by DamianX** [comment]
So THAT's why that happens?
There's no warning message or sound or anything. The action button is also still there, just does nothing.

**Comment by DrSnips** [comment]
A bit of feedback on trying to use it without a linked suit would fix this. Something like "No suit connected. Please re-establish a connection."

**Comment by SonixApache** [comment]
helmetlights should just have a tiny internal battery tbh

**Comment by RealestEstate** [comment]
safe to close this
