### ISSUE TITLE
Chinesium Speakeasy Invisible At Dusk

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24453]
(WEB REPORT BY: utilitas REMOTE: 206.221.180.138:7777)
# Revision
d9cdb62c74448c77e5655fcb2b2fff4d9c54256c

# Description
Sol Common (:3) is extremely hard to read on the Dark theme, and becomes completely impossible with one of those fancy schmancy screen reddening programs like Redshift or Sunset screen
# Steps to Reproduce
Talk in chinesian ingame
# What you Expected
To be understood
# What Actually Happened
Whuh?

**Comment by Zth--** [comment]
Fixed here #24453
