### ISSUE TITLE
Nanopaste in Destructive Analyzer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24458]
(WEB REPORT BY: tsea REMOTE: 206.221.180.138:7777)
# Revision
d9cdb62c74448c77e5655fcb2b2fff4d9c54256c

# Description
Processing nanopaste in the DA seems to work and the animation progresses, but following completion it is not possible to place another item in the DA. Clicking on the DA then removes the nanopaste.

# Steps to Reproduce
1. Insert nanopaste and run DA
2. See animation complete
3. Receive nanopaste

# What you Expected
Nanopaste being consumed upon analysis.

# What Actually Happened
Nanopaste was not consumed.

**Comment by DrSnips** [comment]
I'm pretty sure we just had an issue created about this the other week. This is not a bug but due to the behavior of stack items in the DA where it only consumes 1 sheet of it as it should.
