### ISSUE TITLE
Feature request: Kicking shoes when you have no shoes should have a chance to equip the shoes

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#24467]
#### Description of issue

\>bare feet
\>apply foot to shoe
\>shoe sticks to foot
Why isn't this a thing?

#### Server revision
Game: e9f2d483ad8b5209e3afe4aacf97da81579cdb8a 
Patches: dc0912f2159f3b4905fa12025e9f5d5d4fa9ed55

**Comment by Zth--** [comment]
Close this
