### ISSUE TITLE
Signaller PDA cartridge doesn't work anymore

### ISSUE THREAD

**Issue by vgrainicorn** [d3athrow/vgstation13#2446]
It probably happened when the PDA map and other stuff was added.

1. Insert generic signaller cartridge into PDA.
2. No new application or utility links appear in the PDA menu.

**Comment by SarahJohnson489** [comment]
Confirming this

**Comment by ConkerDev** [comment]
Does this work with the Toxins PDA?. Because else I think why it happens: Generic signalers have no embedded signaler, blame DeityLink.
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/objects/items/devices/PDA/cart.dm#L115

**Comment by ConkerDev** [comment]
Tested in round, toxins PDA work, generic signalers dont. It can be solved by changing this code:
```DM
/obj/item/weapon/cartridge/signal/toxins/New()
	..()
	spawn(5)//giving time for the radio_controller to initialize
		radio = new /obj/item/radio/integrated/signal(src)
```
to
```DM
/obj/item/weapon/cartridge/signal/New()
	..()
	spawn(5)//giving time for the radio_controller to initialize
		radio = new /obj/item/radio/integrated/signal(src)
```
