### ISSUE TITLE
Some More Things are FuCkEd UP! in the VOX.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24468]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
e9f2d483ad8b5209e3afe4aacf97da81579cdb8a

# Description
*masculine "the" is "they" (not sure about femuline)
*periods and commas display error ". is not a word, try a different word" and grey-out the announce button

CODERS ARE _EXCELLENT

**Comment by utilitas-** [comment]
Confirmed outbreak of level biohazard aboard Stanford Fortification Twelve. All personnel must contain the outbreak. Three.
That's how the vox says the announcement now.

**Comment by N3X15** [comment]
> Confirmed outbreak of level biohazard aboard Stanford Fortification Twelve. All personnel must contain the outbreak. Three.
> That's how the vox says the announcement now.

BYOND loads assets in a way that's not guaranteed to maintain order.  So, you'll occasionally get scrambled words.  #24428 will hopefully resolve this by forcefully preloading some words to your client on connect.
