### ISSUE TITLE
Engineer cams might be glitchy on packed

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#24474]
#### Description of issue
I was looking through the engineer cameras using the quick menu shortcuts on the top left, when looking through them I ended up seeing the deathsquad area with the mechs in it and once I panned past it it stopped working entirely for a bit, after taking it apart and rebuilding it it detected a a single camera in the burn chamber and would let me view it and one in the brig for some reason, though in the list menu it did not detect the brig one.

#### Difference between expected and actual behavior
Engineer cameras to work correctly and see what they normally do.
Saw some shit I wasnt supposed to and then a lot of nothin

#### Steps to reproduce
Not really sure on this one, It was right after a meteor storm and it just sort of happened.

#### Length of time in which bug has been known to occur

Never seen this before now.

**Comment by incakola** [comment]
Flicking through Singularity cameras sometimes shows a camera in what looks like the derelict?
Not sure which maps this happens on but at least box

**Comment by Kurfursten** [comment]
@incakola that one is a feature, you're seeing an engineering vault
