### ISSUE TITLE
dionea monkey cube

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24483]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
7fe8f9f09cba421dbc8d164b18f0d9ab9018d982

# Description
dionea can't eat monkey cubes
# Steps to Reproduce
be dionea, eat monkey cube
# What you Expected
obtain ton of nutrition
# What Actually Happened
explode

**Comment by Exxion** [comment]
That's... how it works for everyone, isn't it?

**Comment by SGuivenne** [comment]
I'm like 90% sure this is a feature with all monkeyform mobs.  With humans it just breaks bones, causes organ damage and IB, and then requires surgical removal.

**Comment by Killette2** [comment]
Pretty sure this intended since dionae nypmhs are a lesser form
