### ISSUE TITLE
Fucking lag

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24492]
#24428 made my menus take like 30 seconds to open (until it's done downloading, which took until 12:10 in-game, and I had been there since the very moment the server restarted).

**Comment by N3X15** [comment]
We're currently up to 4,500 words in the repo, so this was bound to happen eventually. 30s for 4,500 OGGs is pretty good, though, so I'll look at lazily-preloading sounds.

**Comment by DamianX** [comment]
I think you misunderstood, it's 30 seconds per-window while it's downloading, and it took about 10 minutes to finish downloading, it seems.

**Comment by Exxion** [comment]
Yeah preloading tends to absolutely fuck your connection for some reason. Like even worse than you'd expect. Even if you're preloading from a CDN. Whenever people post screenshots of five-digit pings, it's because they're still loading resources.
