### ISSUE TITLE
Ping Players

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24498]
There are some things that I think should automatically ping players. If you send a fax, it should probably let the IAA/all heads know. Sometimes you reply by fax to a message and then the heads never realize it.

Also, I think it would be nice if the labor console could be pinged by players on the lobby screen, requesting someone to give them guidance by setting high prio jobs.

**Comment by SkowronX** [comment]
Make a PDA cartridge for IAAs that pings them with a new fax

**Comment by SkowronX** [comment]
and include it for cap/hop cartridges

**Comment by utilitas-** [comment]
>not always setting Assistant, Clown and HoP to high priority

**Comment by utilitas-** [comment]
/>not always setting Clown, Assistant and HoP to high priority

**Comment by utilitas-** [comment]
\>not always setting Clown, Assistant and HoP to high priority
