### ISSUE TITLE
Sugar adds in .95u increments

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24490]
(WEB REPORT BY: tsea REMOTE: 206.221.180.138:7777)
# Revision
18e97bcc9ef7a36d26491db3febe60c6466fe9fb

# Description
Adding sugar to a microwave with a transfer size of 1 only transfers .95 units. This leads to all recipies failing.

# Steps to Reproduce
Set transfer amount to 1 in a container and add sugar to the microwave.

# What you Expected
1u of sugar in the microwave.

# What Actually Happened
.95u of sugar in the microwave.

**Comment by Killette2** [comment]
Similar duplicate report to this issue.

I put in 5 creatine and 5 unstable mutagen into a virus dish

it works normal taking 0.5 unit each at a time, but when it gets low I see the mutagen is at 2.5 and the creatine is at 2.49
Something is fucky wucky

**Comment by DamianX** [comment]
Can't reproduce the OP.

**Comment by utilitas-** [comment]
Did you accidentally add some reagent to the sugar bag?

**Comment by Zth--** [comment]
Fixed here #26135

**Comment by DamianX** [comment]
This SOUNDS like the same issue I addressed, but is it really? In my testing the reagents always showed up as 1u even though they were slightly less.
Also Killette's issue was not addressed by my PR for sure.
