### ISSUE TITLE
Using Ctrl-E quickswap from helmet (one that hides hair) to a hat makes you lose your hair

### ISSUE THREAD

**Issue by vgrainicorn** [d3athrow/vgstation13#2450]
1. Wear a helmet that hides your hair (any EVA helmet)
2. Hold a hat in your hand (like a paper hat)
3. Press Ctrl-E to put it on.
4. BALD

Doesn't bald if you put it on by clicking on the head slot, only Ctrl-E does it.

**Comment by d3athrow** [comment]
not calling update overlays so you end up with lolnohair
