### ISSUE TITLE
Why do I have the xeno plasma meter

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#24500]
I ain't no xeno I am but a simple bartender who just got sucked by a vampire
![uh](https://user-images.githubusercontent.com/25846834/67151508-49941080-f295-11e9-94b8-9c96c80c74cf.png)

**Comment by SonixApache** [comment]
it's just telling you that there's plasma in the room, 150 moles of it in fact

**Comment by MadmanMartian** [comment]
HUD pooling not resetting things properly

**Comment by DeityLink** [comment]
Well Pooling is gone so...
