### ISSUE TITLE
Creatine killing when it shouldn't

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24504]
(WEB REPORT BY: vladorf REMOTE: 206.221.180.138:7777)
# Revision
fcbf3ce6f5e139a3ce8b5e5ff4fa5c302caba5e5

# Description
I injected 60u of Creatine and died about 5 seconds later.
There is no way my body metabalized all 60u of creatine.  You're only supposed to die when you go back down to 0 after taking that much.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by N3X15** [comment]
![LOOK AT HIM AND LAUGH](https://user-images.githubusercontent.com/110073/67154671-66404080-f2b5-11e9-9d57-6f6768404822.jpg)

**Comment by Kammerjunk** [comment]
sounds right

**Comment by Zth--** [comment]
>60u of creatine

**Comment by SGuivenne** [comment]
Feature
