### ISSUE TITLE
AI Still doesn't have the freqs in its notes?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24501]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
1e03a2c4b390c04985866c27abfabe48e001c794

# Description
The AI still has no way of knowing the AI private freq due to all radios in his core being set to common, AI private not being listed in telecomms, and the notes not listing anything for AI. The only way to find out is asking someone to read the librarians paper.
# Steps to Reproduce
Play AI, Check notes
# What you Expected
Seeing all freqs
# What Actually Happened
Seeing no freqs whatsoever.

**Comment by DeityLink** [comment]
Is that still a problem @PrimeDSS13 ?

**Comment by nervere** [comment]
No longer an issue. Tested and unable to replicate.
