### ISSUE TITLE
Holo-Impersonation is DONE FOR

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24510]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
7b1a7a920c1f361459c0bc5a9b39274e7846c1a9

# Description
AI changing hologram to crew member displays featureless nude model.

Gee, AI sure is bugged lately, huh? Better keep an eye out for blue APCs.

**Comment by Killette2** [comment]
Are you expecting holoclothes?

**Comment by SonixApache** [comment]
dupe of #21492

**Comment by Blithering** [comment]
It used to have the appearance of their hairstyle and  their job's starting gear
