### ISSUE TITLE
Being in a disposal pipe can sometimes delete you (yes, delete, not nullspace)

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#24515]
#### Description of issue

Weird issue. Setup was as such:
![image](https://user-images.githubusercontent.com/8468269/67165911-dec50100-f38a-11e9-8fd0-8f947a19f6c7.png)
one disposal chute (delivery chute) facing a wall - wall can be an R-wall or a normal wall
one trunk below it, also facing the wall
no pipe under the wall 

person gets in, gets stuck in pipe
borg comes along, slices pipe
person in pipe gets deleted

related error from the log: 
`## ERROR: transfer_to(): Some idiot has tried to transfer_to() a non mob/living mob. Please inform Carn`

So far, I've only managed to reproduce it *twice* out of multiple tries. Not sure what causes it. Holding direction keys while being sliced doesn't seem to affect it, though that's what I was doing when it happened.

This happened on the live server on october 20th, 2019, at 7:50 AM
related ckeys were `Jalis` and `Edwarus`

**Comment by Zth--** [comment]
It clearly states we should inform Carn. Anyone got his phone number?

**Comment by utilitas-** [comment]
her*
Carnwennan is a colourblind cunt, don't bother.

**Comment by DamianX** [comment]
I tried three times and was unable to reproduce this.
