### ISSUE TITLE
Closing Trader access does not work on code red

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24512]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
7b1a7a920c1f361459c0bc5a9b39274e7846c1a9

# Description

Trying to close trade dock should work on red OR with HoS auth, it only works with HoS auth at the moment.
# Steps to Reproduce

Code Red, Call it as anyone not captain, HoS, or shithead HoP.
# What you Expected

To close the dock
# What Actually Happened

This action requires either a red alert or head of security authorization. 

(On code red)

**Comment by Kurfursten** [comment]
It should

`(access_heads in I.access && security_level >= SEC_LEVEL_RED)`

But he and the CE couldn't do it. He had access and it was red alert.

Probably a quirk of how the logic is interpretted

**Comment by SGuivenne** [comment]
Tested with CMO and CE?  (He might have been impersonating the CE)

**Comment by Kurfursten** [comment]
This is being caused by operator precedence, it just needs () in the check
