### ISSUE TITLE
Deff's starter shard crate has two shards stacked on top of eachother

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24520]
(WEB REPORT BY: bomberharris REMOTE: 206.221.180.138:7777)
# Revision
6aea0f19b425304c4f73532ca2914cd34357cde9

# Description
The shard crate on deff, either the one in storage or in the SME room roundstart, has two shards in it.

# Steps to Reproduce
Make a conveyor engine with shards.

# What you Expected
The praise and commendation of my peers for my ingenuity.

# What Actually Happened
The warm glow of radiation, explosions, then silence.

Fuck you Duny

**Comment by SonixApache** [comment]
[doubt]
it's probably the double locker contents bug activating again

**Comment by DamianX** [comment]
ok now this is epic
I still maintain that it's a BYOND bug, but we can work around it with an `INITIALIZED` atom flag

**Comment by DeityLink** [comment]
Fixed by #30184
