### ISSUE TITLE
Can't delete a list entry with VV

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24537]
#### Steps to reproduce
- VV any airlock that requires access
- Try to click the (Delete) link next to any entry in the `req_access` list
- Nothing happens, no runtimes either

**Comment by utilitas-** [comment]
Editting lists within lists is generally fucky, someone should take a look at it.

**Comment by SonixApache** [comment]
it worked a few weeks ago

**Comment by SonixApache** [comment]
The most recent related things I can see are #24084 and #24082
