### ISSUE TITLE
Soul rambler can no longer spawn in lowpop

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24539]
It's because of the recent forced "secret" (read: dynamic autotraitor) on lowpop.
It was originally intended to be a lowpop thing and I think it should be restored.

**Comment by utilitas-** [comment]
Can't you still cause them to spawn manually?
It's not like they ever trigger anyway.

**Comment by ShiftyRail** [comment]
You can still spawn them manually.
The original version of dynamic+secret had minor roles (which included rambler, and catbeasts) able to spawn.

**Comment by DamianX** [comment]
Fixed by murdering "classic secret".
