### ISSUE TITLE
admin faxes aren't sending

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24532]
(WEB REPORT BY: probe1 REMOTE: 206.221.180.138:7777)
# Revision
dd1204b47ba0d3de75de1b62b2bf8fe6c80bee94

# Description
Send-fax isn't sending faxes to the station.
# Steps to Reproduce
Send a fax
# What you Expected
A fax to be sent.
# What Actually Happened
No fax was sent.

**Comment by Kharkov72** [comment]
Happened to me too today, gave this message:
`[12:24:16]ADMIN: MOD: Kharkov72/(Kolton Hunt) : >Message reply to Exbod/(Charles Rhinehart) failed.`

**Comment by Kurfursten** [comment]
It's my fault, lacked a sanity check in the fax PR. It got merged too fast and I shouldn't have posted it without saying "this is untested".

My other ping PR has the fix included in it.
