### ISSUE TITLE
Friend/buddy cuffing is absurdly broken shitcode

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#24545]
#### Description of issue
I don't even know where to begin on this there's so many problems with it but here I go.
You can cuff yourself to a monkey to get stuck into a meatrack
You can cuff yourself to someone to get stuck inside a sleeper/scanner/cyrotube
You can cuff yourself to put two people into a mech that neither can operate correctly
you can cuff a human to a nymph and have someone put that nymph in their backpack to hide in the backpack along with the nymph.
You can teleport the nuke disk by teleporting someone cuffed to someone holding it.
You can hide inside a washing machine by being cuffed to a monkey you put in there.
I have like 10 more examples I could give/find if I really need to go on about how broken this is.

#### Specific information for locating

https://github.com/vgstation-coders/vgstation13/pull/23079

**Comment by SGuivenne** [comment]
Out of curiousity, is it possible to nullspace yourself via some of this?  Like say you buddy cuff to someone who gets deleted by one thing or another?
