### ISSUE TITLE
Label Roll boxes are empty

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24558]
(WEB REPORT BY: dacendeth REMOTE: 206.221.180.138:7777)
# Revision
57d78c144e6a56ca7239ab113fd7952b53da9d73

# Description
all the boxes anywhere dont have anything in them.
# Steps to Reproduce
Look in a box
# What you Expected
find rolls
# What Actually Happened
empty

**Comment by Zth--** [comment]
for some reason they are duplicated in the code
https://github.com/vgstation-coders/vgstation13/blob/15cfa56626c5b0d2ce4c0c5321a29b1bab529b49/code/game/objects/items/weapons/storage/boxes.dm#L653-L671
