### ISSUE TITLE
Captains Armour

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24557]
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
57d78c144e6a56ca7239ab113fd7952b53da9d73

# Description

Captains armour is space proof and also spawns inside Suit Storage Unit, but it can't be put back inside it.

# Steps to Reproduce

try to put captains armour to the Suit Storage Unit

# What you Expected

to put the armour inside

# What Actually Happened

nothing

**Comment by ghost** [comment]
dibs. The captain armour isn't a literal space suit subtype and that's what the SSU expects.
