### ISSUE TITLE
Dismantling Glass tables give plasmaglass.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24551]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
10b07630d853eef4a4d81deba3e025a9fd7fe04f

# Description
When you dismantle a glass table, instead of getting glass and metal you get plasmaglass, glass, and metal.
# Steps to Reproduce
Build a metal table. Hit it with glass. Dismantle glass table with wrench.
# What you Expected
The supplies that went into the table come out the same
# What Actually Happened
Plasmaglass enters the equation somehow.

**Comment by Kammerjunk** [comment]
read from here on down: https://github.com/vgstation-coders/vgstation13/blob/6bfb56a2c132e1126df9a19a66cae890ff5250a3/code/game/objects/items/weapons/table_rack_parts.dm#L163
the attackby() on line 175 is supposed to be for `/obj/item/weapon/table_parts/glass/plasma` but it's actually `/obj/item/weapon/table_parts/glass/attackby()`
change it to `/obj/item/weapon/table_parts/glass/plasma/attackby()`

**Comment by Probe1** [comment]
I'm crossing my fingers that I didn't create this bug.

**Comment by Probe1** [comment]
Thank god it was @ShiftyRail I thought I did it when I added glass tables.

**Comment by ShiftyRail** [comment]
Oops
