### ISSUE TITLE
Clothier, the job

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#24559]
Dumping a job idea I've had for some time. It really never passed the design stage since I could not find how to properly make it fun and antagonizable, so I'm dumping it here instead of having it in a dead folder
Please note that these notes are very uncomplete and just give a general idea of how everything should work.

# Clothier
  The guy in charge of making clothes, space suits, bags, etc, and improving them. The idea is that everyone starts with _shit tier_ clothes and this guy can make everyone's life better by adding pockets, resistances, or features in general.
Possible interesting features are: bluespace pockets, iv drip components, for example
Every feature should have a drawback, otherwise it would be _Powercreep, the job_
## Items
   Clothes should be made of material, every material has its own properties. We already have ways of obtaining silk, or leather, for example.
### Materials needed
    - Fibroglass
    - ???
      
### THREADS
    - Silk
    - Cotton
    - Polyester

### Clothes
    #+NAME: silk
    - Silk cloth: made from silk /thread/. Silk thread can be gathered from the webs of spiders and silk worms, which is then woven into cloth at a /loom/. 
      PROPERTIES: Strong, very elastic, fine in diameter.
    - Nylon and polyester: no shrinkage, high strength, excellent abilities to stretch and recover.
    - Animal wool: Shearing sheep or other animals. Wool > yarn > thread
    - Plants: some plants produce stuff that can be thread. Quality of the plant tells the resistance.
### Space suits
    - Inner: Nylon tricot, spandex
    - Pressurization: uerthane-coated nylon, dacron
    - Fiberglass is the primary material for the hard upper torso segment.
    - Lithium hydroxide is used in making the filter which removes carbon dioxide and water vapor during a space walk
    - power??
    - Polycarbonate for shell of the helmet

#### SPACE SUITS COOLING SYSTEM
     To maintain temperature, a liquid cooling and ventilation garment is worn under the outer garment.
     It is composed of cooling tubes, which have fluid flowing through them. The undergarment is a mesh one-piece suit composed of spandex.
     It has a zipper to allow for front entry. It has over 300 ft of plastic tubing intertwined within which it circulates cool water.
     Normally, the circulating water is maintained from 40-50° F (4.4-9.9° C). The temperature is controlled by a valve on the display control panel.
     The lower garment weighs 8.4 lb (3.8 kg) when loaded with water

### Misc
    - Containers (bags)
    - Splints for medbay
    - Rolls of gauze
    - Rolls of ...?

## Processes
   How the fuck should the workflow be? I have no fucking idea

### Dye
     Dye-ing happens on a pot with dye.
### Weaving
    ???
### Everything else
    ????????

[discussion] [featurerequest]

**Comment by utilitas-** [comment]
I remember there being a somewhat similar Blacksmith job on one of the very old servers. TL;DR made guns'n'shiet out of individual parts in a far, **far** more intuitive way than currently implemented. Take gun frame made from metal, combine with trigger, safety, capacitor/battery system, barrel, whack with wrench, weld, and you get an egun. You know, the way RnD was _supposed_ to be designed instead of a retarded trial and error deconstruction minigame.

**Comment by Kurfursten** [comment]
Hot take: we don't need a bloat role that sounds like it belongs more in lifeweb than space. If you want to add clothing customization, great. Maybe you can roll it into mechanics since they are constantly searching for more of an identity.

>but mechanics won't do their job

What makes you think a clothier would?

**Comment by Probe1** [comment]
Tailor could be a cool alt title for assistants.

**Comment by incakola** [comment]
roll it into the mechanic's job description

**Comment by west3436** [comment]
Closed via #35527 and associated follow up PRs

**Comment by Eneocho** [comment]
but bro, it isn't
those PRs only added clothes making, not a dedicated clothier job, like how the librarian can be a curator

**Comment by Kurfursten** [comment]
Given that this was a Zth-- wyci and he isn't active anymore, I think this is a safe close until he returns if ever
