### ISSUE TITLE
Railgun rod issues

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#24560]
#### Description of issue

If you use any stack of rods on a railgun, it consumes the whole stack.
Secondly, once you fire it, you no longer find a single rod where the saibot round stopped

#### Difference between expected and actual behavior

Expected no magic rod disappearance

#### Steps to reproduce

1. Load railgun with rods
2. Watch it swallow the whole stack
3. Fire railgun
4. Wonder where the rod went

#### Length of time in which bug has been known to occur
Unknown, but I remember it working correctly

#### Server revision
57d78c144e6a56ca7239ab113fd7952b53da9d73 

bugfix = "Bug / Fix"

**Comment by SonixApache** [comment]
former is a bug and shouldn't happen
latter is not

**Comment by Shadowmech88** [comment]
>once you fire it, you no longer find a single rod
>no longer

Did it used to drop a rod where the projectile stopped?
I feel like it did, but I can't remember.

**Comment by SonixApache** [comment]
It used to, I changed that.
