### ISSUE TITLE
Random Sound Event For AI Request

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#24565]
#### Description of issue

Not sure exactly where/when I would want this, but I would like it to fire perhaps when an AI/Silicon dies, or have a chance to fire in lieu of the Space Jam when walking into the AI chamber or to have a chance to fire when leaving the AI chamber, preferably tied to a 1/500 chance to fire.

https://soundcloud.com/aintaintcountry/have-a-safe

**Comment by nuklearcellphoneg** [comment]
https://soundcloud.com/aintaintcountry/please-do-not-harm

**Comment by nuklearcellphoneg** [comment]
https://soundcloud.com/aintaintcountry/ambimalfbackback

**Comment by Probe1** [comment]
I don't think the AI gets notifications on the death of cyborgs does it?
