### ISSUE TITLE
Debug spam everywhere as a test dummy

### ISSUE THREAD

**Issue by Duny-** [d3athrow/vgstation13#2457]
![ss 2015-01-06 at 09 19 55](https://cloud.githubusercontent.com/assets/5224390/5635495/e507468a-95e9-11e4-96a7-644249e6b20c.png)
I get spammed CONSTANTLY with that whenever I spawn myself as a test dummy with debug log messages toggled on. WHY WOULD YOU DO THIS? Do you want to read a book with test dummy debug logs?

**Comment by ririchiyo** [comment]
It's called a test dummy for a reason.

**Comment by Duny-** [comment]
Tell Deity to let me spawn as a human then :^)

**Comment by Iamgoofball** [comment]
You guys aren't supposed to be using these, they are for testing critical human functions and not for being admin godmode fun time

**Comment by Duny-** [comment]
Tell Deity to replace the test dummy by a human then nigga
And to make the adminbus be driveable by a human instead of a test dummy or something

**Comment by Iamgoofball** [comment]
imo adminbus shouldn't be using test dummy then, it should be using something else
