### ISSUE TITLE
Xenoarch artifacts lack tech levels.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24575]
(WEB REPORT BY: boosterrooster REMOTE: 206.221.180.138:7777)
# Revision
3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

# Description
On packed station items dug up from xenoarch lack tech levels such as anom. when tried in a DA.

**Comment by DeityLink** [comment]
Wouldn't it be great if they specified what items?
