### ISSUE TITLE
Kurf broke my box (containers not having correct storage space)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24582]
(WEB REPORT BY: pancakemines REMOTE: 206.221.180.138:7777)
# Revision
3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

# Description
Cardboard boxes and possibly other boxes now have their old space limits from before the bag changes. Likely from https://github.com/vgstation-coders/vgstation13/pull/24561.
# Steps to Reproduce
Put things in boxes util it fills up.
# What you Expected
To be able to carry more than 7 items in my cardboard box.
# What Actually Happened
It was limited to the 7 item limit from before bag slot changes.

**Comment by Kurfursten** [comment]
Loud sigh

So this is the cause.
