### ISSUE TITLE
Surgery holosign

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24581]
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

# Ghosts can turn on and off the surgery holosign without a delay

# ghost, click switch

# being delayed

# rave party

**Comment by Dacendeth** [comment]
feature

**Comment by Probe1** [comment]
a feature.
