### ISSUE TITLE
Can't Delete R&D Designs Due to Duplicate Server on Derelict

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#24587]
Or, more specifically, "designs can't ever be completely deleted because the R&D server on the Derelict, which receives the designs on sync, is the exact same type as the Robotics R&D server and shares its `server_id` which makes the Derelict server inaccessible from the server control console."
Update of #4057.
Because only two types of server exist, and under the assumption every map has a Derelict of some kind, this bug probably applies to all maps.
The fix for this is to replace the duplicate servers and consoles on the Derelict on each map with the Derelict-specific ones created by #24586.

**Comment by Kurfursten** [comment]
This has been a mystery for AS LONG AS THE SERVER!

**Comment by Zth--** [comment]
`/obj/machinery/r_n_d/server/derelict` was added in packed here #25036
