### ISSUE TITLE
Atmospherics Balance Feedback

### ISSUE THREAD

**Issue by utilitas-** [d3athrow/vgstation13#24595]
Because fuck retarded jannies. [discussion]

From some mild testing on the test serb, the first changes kinda just mean that plasma burns nowhere near as hot while producing just as much CO2. It also makes natural scrubbers much more effective, and able to remove most of the plasma/CO2 in the matter of minutes, even while the plasma is still burning.

But if I disable the scrubbers, a plain popped canister in the main hallway burns for about three times as long. Still nowhere near as long as before, I'd lower the amount of CO2 produced to keep it burning longer.
More importantly, messing with the variables seems to have fundamentally fucked the pressure calculations. Even at ~350C with the scrubbers turned only to filter out CO2 and the fire burned out, the hallway is actually at _below_ ambient pressure, at 100.7 kPA. I have no clue whatsoever why that is happening.

**Comment by Exxion** [comment]
There are fewer moles of gas after the fire. One mole of oxygen plus (if memory serves) 2/3 of a mole of plasma becomes 1 mole of CO2. It's surprising that you could get a fire cold enough that the heat change wouldn't make up the difference for pressure, though

**Comment by utilitas-** [comment]
Yeah, I figured that's why it was happening, anyway.
Realistically speaking, its combustion should mostly result in water vapor and CO2 (if we assume plasma to be basically irradiated ethanol), but we kind of don't have water vapor, though with ZAS it shouldn't be an issue to add it - the difficult part is figuring out what the fuck to do with it.
I had to add a preburner to the TEG in order to get it above 600K with a direct burn mix feed, and a fire in the hallway generally resulted in a raise by several hundred degrees which is far more realistic than the usual multiple thousand degree hellscape. But even then it didn't go above ambient pressures by more than 1-2 kPA, dipping below with scrubbers set to scrub CO2.

**Comment by Exxion** [comment]
Only 600K without a preburner? Was this on local? If so, have you made sure the config for `fire_fuel_energy_release` in `config\ZAS.txt` was updated to the new value of 2000000?
Actually if it was on the test server that may still be the old value too

**Comment by utilitas-** [comment]
It was on the test serbian. It was definitely the new value, it updated.

**Comment by Exxion** [comment]
The test server's code updated, but the config files are separate

**Comment by Exxion** [comment]
Yeah, I just checked and on the test server it's 40000, which is actually even *lower* (by a *lot*) than the 550000 it used to be everywhere else
It's frankly amazing that fires even do anything significant on there
(For the current round on the test server, I set it to the proper value, but I'm waiting on Pomf to do something with the secret repo before I can fix it permanently)

**Comment by d3athrow** [comment]
```
# Fire - Air Consumption Ratio
#   Ratio of air removed and combusted per tick.
/datum/ZAS_Setting/fire_consumption_rate 0.2

# Fire - Firelevel Constant
#   Multiplied by the equation for firelevel, affects mainly the extingiushing of fires.
/datum/ZAS_Setting/fire_firelevel_multiplier 30

# Fire - Fuel energy release
#   The energy in joule released when burning one mol of a burnable substance
/datum/ZAS_Setting/fire_fuel_energy_release 800000

# Airflow - Small Movement Threshold %
#   Percent of 1 Atm. at which items with the small weight classes will move.
/datum/ZAS_Setting/airflow_lightest_pressure 40

# Airflow - Medium Movement Threshold %
#   Percent of 1 Atm. at which items with the medium weight classes will move.
/datum/ZAS_Setting/airflow_light_pressure 50

# Airflow - Heavy Movement Threshold %
#   Percent of 1 Atm. at which items with the largest weight classes will move.
/datum/ZAS_Setting/airflow_medium_pressure 60

# Airflow - Mob Movement Threshold %
#   Percent of 1 Atm. at which mobs will move.
/datum/ZAS_Setting/airflow_heavy_pressure 70

# Airflow - Dense Movement Threshold %
#   Percent of 1 Atm. at which items with canisters and closets will move.
/datum/ZAS_Setting/airflow_dense_pressure 80

# Airflow - Mob Stunning Threshold %
#   Percent of 1 Atm. at which mobs will be stunned by airflow.
/datum/ZAS_Setting/airflow_stun_pressure 60

# Aiflow Stunning - Cooldown
#   How long, in tenths of a second, to wait before stunning them again.
/datum/ZAS_Setting/airflow_stun_cooldown 100

# Airflow Impact - Stunning
#   How much a mob is stunned when hit by an object.
/datum/ZAS_Setting/airflow_stun 1

# Airflow Impact - Damage
#   Damage from airflow impacts.
/datum/ZAS_Setting/airflow_damage 2

# Airflow Speed Decay
#   How rapidly the speed gained from airflow decays.
/datum/ZAS_Setting/airflow_speed_decay 1

# Airflow Retrigger Delay
#   Time in deciseconds before things can be moved by airflow again.
/datum/ZAS_Setting/airflow_delay 20

# Airflow Slowdown
#   Time in tenths of a second to add as a delay to each movement by a mob if they are fighting the pull of the airflow.
/datum/ZAS_Setting/airflow_mob_slowdown 1

# Airflow - Push
#   1=yes please rape my server, 0=no
/datum/ZAS_Setting/airflow_push 1

# Connections - Insulation
#   How insulative a connection is, in terms of heat transfer.  1 is perfectly insulative, and 0 is perfectly conductive.
/datum/ZAS_Setting/connection_insulation 0

# Connections - Temperature Difference
#   The smallest temperature difference which will cause heat to travel through doors.
/datum/ZAS_Setting/connection_temperature_delta 10

# Airflow - Enable Ice Formation
#   1=yes, 0=no - Slippin' and slidin' when pressure &gt; 10kPa and temperature &lt; 273K
/datum/ZAS_Setting/ice_formation 0

# Airflow - Disable Cold Space
#   1=yes, 0=no - Disables space behaving as being very fucking cold (0K).
/datum/ZAS_Setting/space_isnt_cold 0

# Plasma Damage Amount
#   Self Descriptive
/datum/ZAS_Setting/PLASMA_DMG 3

# Cloth Contamination
#   If this is on, plasma does damage by getting into cloth.
/datum/ZAS_Setting/CLOTH_CONTAMINATION 1

# PlasmaGuard Only
#   If this is on, only biosuits and spacesuits protect against contamination and ill effects.
/datum/ZAS_Setting/PLASMAGUARD_ONLY 1

# Genetic Corruption Chance
#   Chance of genetic corruption as well as toxic damage, X in 10,000.
/datum/ZAS_Setting/GENETIC_CORRUPTION 0

# Skin Burns
#   Plasma has an effect similar to mustard gas on the un-suited.
/datum/ZAS_Setting/SKIN_BURNS 1

# Eye Burns
#   Plasma burns the eyes of anyone not wearing eye protection.
/datum/ZAS_Setting/EYE_BURNS 1

# Contamination Loss
#   How much toxin damage is dealt from contaminated clothing
/datum/ZAS_Setting/CONTAMINATION_LOSS 0.075

# Plasma Hallucination
#   Does being in plasma cause you to hallucinate?
/datum/ZAS_Setting/PLASMA_HALLUCINATION 1

# N2O Hallucination
#   Does being in sleeping gas cause you to hallucinate?
/datum/ZAS_Setting/N2O_HALLUCINATION 1

```

**Comment by d3athrow** [comment]
next restart will have those values

**Comment by west3436** [comment]
Some elements covered in #25128
