### ISSUE TITLE
Mini hoe has no attack message

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#24606]
Good for dabbing on people who don't have animations on. It only shows a message when it misses.

**Comment by Kammerjunk** [comment]
https://github.com/vgstation-coders/vgstation13/blob/f515e32fb8b6a9682d050d288da65a457b7af36e/code/modules/hydroponics/hydro_tools.dm#L319
```flags = FPRINT  | NO_ATTACK_MSG```
seemingly intentional I guess
should it be so, though?

**Comment by Kurfursten** [comment]
It was probably a bad implementation before of clearing weeds from the hydro tray and it would send "X attacks the Hydroponics Tray"... that would have been truly ancient oldcode but I'm guessing the most plausible explanation. Of course modern implementations don't need to worry about this.

**Comment by UndeadOrb** [comment]
I didn't even realize they had attack animations in the settings
