### ISSUE TITLE
I got genetic damage in my robotic leg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24605]
(WEB REPORT BY: dacendeth REMOTE: 206.221.180.138:7777)
# Revision
70337a2a04d0c525b7412ba23f3681b83b0a98c8

# Description
A virus make my robotic leg weirdly shaped
# Steps to Reproduce
have a robotic leg and get whatever virus does that
# What you Expected
robotic limbs to be immune to genetic damage
# What Actually Happened
couldnt stand up

**Comment by Kammerjunk** [comment]
https://github.com/vgstation-coders/vgstation13/blob/f515e32fb8b6a9682d050d288da65a457b7af36e/code/modules/mob/living/carbon/human/human_damage.dm#L131
can't actually find a check for ORGAN_ROBOT in the candidate selector for mutating limbs

**Comment by Zth--** [comment]
You could say it was a software virus :eyes:
