### ISSUE TITLE
Remove the dang AI announcement in the chat

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#24603]
It works now I think we're good

**Comment by boy2mantwicethefam** [comment]
no

**Comment by N3X15** [comment]
WIP, it'll be removed in the next batch update.

**Comment by boy2mantwicethefam** [comment]
come on its more fun this way

**Comment by utilitas-** [comment]
make it a preference toggle for people who're playing without sound

**Comment by Zth--** [comment]
Don't. Muting an AI should be an ingame mechanic, not a player preference.

**Comment by utilitas-** [comment]
\>muting
\>when you'll still be hearing the announcements, you just choose not to see them in the chat
ligga what

**Comment by Zth--** [comment]
my bad, I was sleepy. I agree with removing it entirely
