### ISSUE TITLE
monkeys invisible while inside inflatable shelter

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24611]
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
8fbe022e8828cb6fbaf920712391cf6e1b1faf74

what the title says. placing a monkey into an inflatable shelter doesn't transfer its icon or something so the inflatable appears to be empty.

**Comment by Kurfursten** [comment]
They were never meant to be monkey compatible!
