### ISSUE TITLE
You can nullspace people by dual handcuffing them and placing them in cryo.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24612]
(WEB REPORT BY: meetmeindorms REMOTE: 206.221.180.138:7777)
# Revision
8fbe022e8828cb6fbaf920712391cf6e1b1faf74

# Description
You can nullspace people by dual handcuffing them and placing them in cryo.

# Steps to Reproduce
Dual-handcuff peeps.
And put them in cryo or anything else that bugs them.

# What you Expected
No can do

# What Actually Happened
Yes can do and lots of fun

**Comment by ghost** [comment]
It's loose(?)

**Comment by Tokanova** [comment]
aboose is happening

**Comment by SonixApache** [comment]
should be fixed after #24571 right?
