### ISSUE TITLE
Syndicate genral issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24625]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
fa644522ac75d9eec90821f927188dbe07f7ab6a

# Description
when you don't have your PDA on you as a human syndie the code changes to a radio headset code that makes syndicate items unobtainable unless through admin help
# Steps to Reproduce
take off your pda and get syndicate job
# What you Expected
to get my traitor items from my headset
# What Actually Happened
The promopt didn't come up and I was up shit creek with out a river even with admin help

**Comment by Kurfursten** [comment]
Could not reproduce on live, it worked perfectly normally. Was able to dial into the headset uplink with provided code.

**Comment by Exxion** [comment]
>up shit creek with out a river
