### ISSUE TITLE
Reloading the xenoarch revolver makes the gun dissaper

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24627]
(WEB REPORT BY: adepressedpyroshark REMOTE: 206.221.180.138:7777)
# Revision
fa644522ac75d9eec90821f927188dbe07f7ab6a

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by jknpj** [comment]
I could swear these guns had their update_icon() disabled
