### ISSUE TITLE
Please Suggest High Priority Rewards

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24632]
These jobs get a special reward for joining as high priority:
* MD: med belt
* CMO: med belt
* Paramed: med belt
* Geneticist: med belt
* Chemist: pill collector
* Virologist: random dish
* Roboticist: synthetic flash
* Bartender: circuits for soda and booze dispensers
* Chef: 2 bags flour
* Botanist: 2 bottles diethylamine
* Miner: basic drill
* Clown: clown coin
* Mime: baguette
* Janitor: extra cleaner grenade and cleaner spray bottle
* Assistant: blue toolbox
* Chaplain: holy water bottle
* CE: mesons, glubbs, cracker
* Atmos: mesons, glubbs
* SE: mesons, glubbs

These jobs get no special reward, just default box:
* Captain
* HoP (laz injector for Ian? box of hats for Ian?)
* Scientist (bonus based on job title? e.g.: box of monkey cubes, excavation drill, one extra TTV)
* RD (dare I say it? 5u creatine syringe for Lamarr)
* QM (extra cash deposited into cargo account?)
* Cargo Tech
* Librarian (bag of dice? paper indicating that librarian was set high prio by accident?)
* IAA
* HoS
* Warden (donut box?)
* Sec Off (coin for secvend cosmetics? donut box?)
* Detective (extra bugs?)

**Comment by boy2mantwicethefam** [comment]
Assistant: All access ID

**Comment by brndd** [comment]
QM: emitter voucher

**Comment by Shadowmech88** [comment]
Most of the current rewards don't really seem reward-like at all. Can't medical belts be found in Medbay already? An extra pill collector might be nice if there are two chemists at once, but if they're highly requested then it's likely there are no chemists.
I feel like the reward, even if it's not something that's otherwise impossible to get, should at least be something that it's a hassle to get. It's not really a quality-of-life improvement for an Assistant to spawn with a blue toolbox considering those litter the station like weeds.
The clown's bananium coin is really the only standout, among the current ones.

**Comment by brndd** [comment]
>An extra pill collector might be nice if there are two chemists at once, but if they're highly requested then it's likely there are no chemists.

If anything they should probably get a large beaker, considering the chances of Chemistry having been robbed by the time they get there.

**Comment by Dacendeth** [comment]
Hos: egun modkit, warden some loyalty implanters

**Comment by Kurfursten** [comment]
@Shadowmech88 I agree with you, however, the basic drill is a very nice freebie as a miner (I can attest to this personally), bartender circuits are very nice, and the diethylamine bottles are handy as a botanist (these actually speed up growth). Viro and janny rewards are also decent.

Most offensive is the holy water bottle for chaplain, who can bless entire water tanks.

**Comment by Shadowmech88** [comment]
As for suggestions:
* Captain: How flexible is the code for giving the item? Is it a var, or a proc? Can it be made into a proc? Of the absentees, I think the Captain's office is the most likely to have been ransacked. It'd be nice if you could make a proc that loops through all the items in the Captain's Office area searching for important items like the hand teleporter, captain's armor, antique laser, etc, and have the captain spawn with a replacement if any of them are missing. If that's not possible, then an extra hand teleporter would probably be the most convenient.
* HoP: Lazarus injector would be nice. Alternatively, one could code a tracking collar and linked pinpointer for Ian, or animal mobs in general.
* Scientist: R&D disk that contains max research in one or two areas.
* Roboticist: Enough circuit boards for one durand or gygax.
* RD: The issue with the creatine syringe is, how many players know about the existence of the Hivehand? It's a neat interaction, sure, but I wonder if most players who would spawn as RD with creatine would know what to do with it. An alternative option might be a suit of reactive teleport armor, or a paper with the coordinates to a random structure in space.
* QM: More cash would be fine, but how often does Cargo run out normally?
* Cargo Tech: Given everything their department can order, I'm not really sure what they might need or want. An emitter wouldn't fit in their backpack.
* Librarian: A copy of Woody's Got Wood.
* IAA: That paper with the radio frequencies that the Librarian gets.
* HoS: When I played HoS, I always liked to buy a hookshot. It was incredibly convenient for getting into certain places, navigating on short spacewalks, capturing fleeing prisoners, and being able to transport two cuffed prisoners at once. However, being a Mining tool, if that's not thematic enough I think one or two additional Lawgiver magazines would also be nice.
* Warden: We have collapsible battering rams, don't we? Would one of those be too much?
* Sec Officer: A cosmetic coin would be nice. Alternatively, do we have higher-capacity tasers? Or could they be added? That would be convenient. Or maybe an autocuffer, I'm pretty sure we have that.
* Detective: I forget, when the detective modifies his revolver, does that allow it to then only shoot lethal rounds, or can it still fire both lethal and nonlethal? If the latter, a modified revolver and box of lethal rounds would be nice.

**Comment by Kurfursten** [comment]
You could have it search his office for missing stuff, yes, but you'd need a full list of what you consider important.

>autocuffer/ram modkit

Both trader items and they can be mass produced at gen fab. Maybe a non-scannable version of the autocuffer though...

>detective modkit

Isn't this a tot item?

**Comment by DrSnips** [comment]
I agree with shadow on the items that are too common to matter.
MD, CMO, Para, etc: A pill bottle with 2-3 of each of the big 4 staple chems. KeloDerm 20u, Dex+ 5u, Bicar 20u, Antitox 20u. If you're high request it likely means chem isnt done so being able to toss pills at one or two people.
Robo, Sci(general): you need 2 to make a borg and can be made with a small bit of basic mats already. Honestly Id rather just get 25 glass and metal. It would allow me to build at least 1 of any bot/borg I wanted or do research as sci since its not likely done if on request.
RD: God please no on the creatine. Tele armor is hot garbage. My take is 1 T4 stock part thats not the bluespace bin and/or an advanced scanner(CE one). The intended use is clear here.
Assistant: Double extended E. air tank maybe? A bluebox and multitool? They don't really have a job so its kind of hard to say what they need thats not tools.
Chap: Some wood I guess. Lets them build more pews, coffins, tables, etc to make their room.

**Comment by Kurfursten** [comment]
You actually can't build more pews, and no one has ever made an issue for this

**Comment by SonixApache** [comment]
give late-join officers a loaded bootknife holster and a can of coffee
 - knife holsters always get fucking stolen by detectives, HoPs, captains, etc
 - coffee is good and canned coffee is rare enough to seem interesting
 - if you want, I can make a new can of security coffee with Wake-up call in it

scientists: give them a toy made out of plasma (that's actually just a reskinned, non-stackable sheet of plasma to grind / stick in the fabs) that's worth a bit of money on the black market.
RD gets a super exclusive version of the above that's worth double the plasma and double the money.

**Comment by calzilla1** [comment]
You guys should be asking your self WHY there being put on HP in the first place

**Comment by Kurfursten** [comment]
It looks like there's currently strong opposition to the idea that people should receive a reasonable reward for pitching in where they're asked. Maybe someone will pick up the idea of improving this system in a year or two.

**Comment by Shadowmech88** [comment]
And when they do, perhaps this issue and the discussion that may be yet to come in it will be of use to them.

**Comment by Blithering** [comment]
Would a police baton be too OP for warden? it doesn't require charge to work, so that's kinda strong, but there's no guaranteed way to obtain one for bobbybots outside of roidstation right now.

**Comment by Allspice** [comment]
ceemo gets trauma kits and an upgraded switchtool, alternately swanky gloves that halve surgery time

**Comment by nuklearcellphoneg** [comment]
20u liquid plasma in a beaker 100% for medbay

**Comment by nuklearcellphoneg** [comment]
There should be a cost for making jobs a priority though if it comes with a benefit

**Comment by brndd** [comment]
>There should be a cost for making jobs a priority though if it comes with a benefit

How to ensure nobody ever uses the feature ever.

**Comment by Killette2** [comment]
Captain: the nuke code

**Comment by Durgen** [comment]
robotocist: posibrain and 2 sythn flashes

**Comment by tuypo1** [comment]
Give the captain a beacon that spawns in a grandfather clock for their office

**Comment by tuypo1** [comment]
I think an entire foldable battering ram would be too much for the warden but giving him the kit to make one as a high priority reward sounds good

**Comment by west3436** [comment]
Inactive discussion
