### ISSUE TITLE
maxx and maxy are varying

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24645]
maxx and maxy are varying, they are not consistent between rounds, something is inflating them past mapsize causing weirdness with borders. However, since I can find no way to get a VV ref for world, I am having trouble even figuring out numbers on it other than testing the transition edge.

This mystery needs to be solved before a "surface world" map can be realized. Please send top minds to this issue.

**Comment by DamianX** [comment]
The map loader can increase max{x,y}, check the dimensions of all vaults, or put a debug statement in /dmm_suite/load_map

**Comment by Kurfursten** [comment]
Dungeon loader too close to new boundaries, seemingly.
