### ISSUE TITLE
Cryo tube rework was done by a complete brainlet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24653]
(WEB REPORT BY: absolutely REMOTE: 206.221.180.138:7777)
Entire rework is completely negated by making multiple copies of the same mix, achieving nothing in the end but extra tedium.

It should be reverted since it didn't make cloning any less viable or cryo tubes any less good.

[discussion]

**Comment by Kammerjunk** [comment]
owned

**Comment by brndd** [comment]
What if its point wasn't to make cryo tubes less good, but to fix cryo duping reagents?

**Comment by Kammerjunk** [comment]
well, I suppose it was both to fix cryo duping reagents and to make it a less attractive option for cloning people with minor damages
"it's tedious" and "it's slow" are both reasons to not do it

**Comment by brndd** [comment]
The rework fixed reagent duping, improved cryo component upgrades and made hardsuited patients not slurp the chamber dry. Requiring more mix honestly seems more like a side effect, though maybe @MadmanMartian will want to comment on this himself.

edit: oh yeah and cryo consumes power now

**Comment by SonixApache** [comment]
😄

**Comment by jknpj** [comment]
Entire [thing] rework is completely negated by making multiple copies of the same [thing]

**Comment by MadmanMartian** [comment]
The cryo rework was to

- Remove duping
- Fix cryo giving phantom chems and ignoring permeability

And the rest was feature creep/QoL from requests because why not.

Now cryo actually consumes chems at 1 input:1 output, rather than 1 input:15 output. Congratulations you're gonna need more mix

**Comment by FudgePucker** [comment]
Wait did the cyro rework make it so that you dont have to strip people before sticking them in? Nothing is worse than just being shoved into cyro with broken bones, and by the time they realize, all your shit has been looted.

**Comment by Kammerjunk** [comment]
no
source: changelog and also it's still a TOUCH reaction

**Comment by brndd** [comment]
No, it made it so that if you're in cryo with full clothes (or god forbid a hardsuit) you no longer consume a disproportionate amount of reagents. You just get reagents injected to you slower.

**Comment by FudgePucker** [comment]
Close enough, hell I would take sitting in a tube over some asshole lifting my hardsuit or ID

**Comment by Dacendeth** [comment]
Cryo doesnt work at all if you're completely naked with the exception of a breath mask on, feels really odd.

**Comment by Exxion** [comment]
Permeability code is still, after all these years, fucking awful

**Comment by DeityLink** [comment]
I'm fairly sure it was reverted, or at least it's not an issue anymore
