### ISSUE TITLE
TTVs are now bad

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24652]
(WEB REPORT BY: absolutely REMOTE: 206.221.180.138:7777)
Someone nerfed plasma burn, TTVs got nerfed to the ground.

**Comment by Dacendeth** [comment]
yeah the old speedmix is dead find the new one.

**Comment by SonixApache** [comment]
git gud retard

**Comment by DrSnips** [comment]
Feature

**Comment by west3436** [comment]
Skill issue/low-quality issue report
