### ISSUE TITLE
Dark Forcefields in Nonsensical Locations

### ISSUE THREAD

**Issue by dsfartgeg** [d3athrow/vgstation13#24656]
## Description of issue
There are observer-blocking dark force fields in stupid locations on meta, deff, and other maps.

![dreamseeker_2019-10-29_13-50-04](https://user-images.githubusercontent.com/54866161/67810440-d722ed80-fa57-11e9-994c-3658e21ad380.png)

## Locations
I don't expect any secret shit in:

### Meta
![dreamseeker_2019-10-29_13-56-35](https://user-images.githubusercontent.com/54866161/67808571-29620f80-fa54-11e9-8a42-006ee458e704.png)
![dreamseeker_2019-10-29_13-54-32](https://user-images.githubusercontent.com/54866161/67808572-29620f80-fa54-11e9-94ac-9ba560053067.png)

### Deff
![dreamseeker_2019-10-29_14-23-14](https://user-images.githubusercontent.com/54866161/67810421-d0947600-fa57-11e9-8e53-8023cdf4aac8.png)

I haven't gone through and checked the other maps.

I can't think of any reasons these should have forcefields.

## Server revision
Game: 9415a993d26b2662d1415b729fdaf229456486e6 
Patches: da44da876314cce5aa0456a0a05b88794e19dc79 

[deff][meta][oversight][general]

**Comment by brndd** [comment]
Some moron has used the russki satellite area (`/area/tcommsat/computer`) when mapping the telecomms on these maps, instead of the actual telecomms area (`/area/turret_protected/tcomms_control_room`).

**Comment by dsfartgeg** [comment]
Why the fuck would the ruskii sat have anti_ethereal?  Isn't it just a DJ station?

**Comment by brndd** [comment]
tcommsat is the one with goonecode on it
