### ISSUE TITLE
Xenomorphs need an HUD element with their amount of plasma available

### ISSUE THREAD

**Issue by Duny-** [d3athrow/vgstation13#2466]
Being forced to switch to the status tab when you want to know the amount of plasma you have is a fucking pain. A simple HUD thingy with amount of plasma available and max amount would be perfect.

**Comment by ComicIronic** [comment]
Should it be like a filling bar, or a filling bar with an overlay of numbers, or just numbers?

**Comment by dylanstrategie** [comment]
I think a visible numeric value would be nice, but a filling gauge could also work for maximal immersions since maximal plasma is capped

**Comment by Probe1** [comment]
A gauge would be a really good improvement.  It could be a vertical gauge at the top right next to the fire/oxygen/whatnot icons.  Having to switch between tabs or keep a running mental notepad is annoying.

**Comment by Duny-** [comment]
A number is required, everything xenos do cost a fixed number of plasma so if you can only see the approximate percentage of what you have left it's pointless. A gauge AND a number would work and probably look cool. A number alone is fine, that's what blobs and vampires have but it looks like shit.

**Comment by Probe1** [comment]
I can't see any reason not to add this!

**Comment by MusgardTiger** [comment]
![alien-plasmabar](https://cloud.githubusercontent.com/assets/10194313/5697743/6a9f6b62-9a02-11e4-9f55-a8b1efe0c894.png)

people on thread said its nice, since i know jackshit about code and this is my first sprite work to be. Should I add every single number to max plasma cap or should it go like 10 50 100 150 200?

**Comment by Probe1** [comment]
both ways work in my mind but what its missing is having it fill up.  honestly I think it should be like the health meter recolored to plasma-purple/pink and not an exact number but that's me.  consistency in the UI.

**Comment by MusgardTiger** [comment]
We need numbers to make this bar useful. I don't know if its possible to make it both fill up and add numbers without making it look like a rave party in a tiny sphere.

**Comment by Duny-** [comment]
I like it

**Comment by Probe1** [comment]
@Duny- did this ever go anywhere?

**Comment by Duny-** [comment]
Nope, still no hud.

**Comment by Intigracy** [comment]
Fixed via https://gitlab.com/vgstation/vgstation/merge_requests/166
