### ISSUE TITLE
How should wizard apprentices be changed?

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24663]
Most people don't seem to enjoy having 5x mindswap mini-wizards per-wizard.
- Should each apprentice type be restricted to a maximum of 1 per wizard? (That is, a wizard would be able to get one of each type of apprentices, but not 5 mindswap apprentices)
- Should the contract of apprenticeship cost more?
- Should the contract of apprenticeship just get r-word'd?

Ideaguys now is your time to shine

**Comment by Dacendeth** [comment]
Perhaps if mindswap apprentices had a weaker version of the spell that had 1-x charges, so they had to make careful tactical choices about who they swapped into?

**Comment by Diavill** [comment]
just alex jones it up bro how is mind control even real, I love my Discount Dan TM pies

[this post sponsored by Discount Dan]

**Comment by DamianX** [comment]
I don't like the idea of a spell with limited charges, it would be the only wizard spell to work like that.
What if No Clothes was replaced with something else, instead?

**Comment by Kurfursten** [comment]
The following is a true story from last night.

>Get pinged for an apprentice contract

Reject

>Again

Reject

>Go to grab a drink from my garage

He got me with the third contract when I wasn't looking. Shouldn't contracts be opt-in instead of opt-out, like other midround stuff?

**Comment by DamianX** [comment]
see #24351

**Comment by Dacendeth** [comment]
Why do they even get no clothes, mindswap doesn't require it does it? if mindswap required robes to cast and the mindswap apprentice didnt have norobes I think that would be good too.

**Comment by incakola** [comment]
- Hard limit on specific apprentice types.
- Apprentice types have different costs like spells.
- Do the points for spending on apprentices draw from the same pool or are the different pools? 
- Can the points be exchanged between the different pools, is the exchange rate consistent, and is there a conversion fee?
- Leftover apprentice buying points can be used to empower/enhance existing apprentices somehow.
- If the apprentices have charges for their spells as suggested previously, can the apprentices be empowered to have more charges/spell level? 
- Does the apprentice get to decide how it gets empowered?

**Comment by DamianX** [comment]
Mindswap apprentices were r-worded
