### ISSUE TITLE
[WIP Feature] Smart Lights

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#24707]
I'm working on adding new light tubes/bulbs that can have their color/brightness changed (possibly  remotely with a PDA app). Right now the idea is to implement a sort of "advanced light replacer" which only uses these new lights and allows the player to select color/brightness for the ones it creates.

Opening an issue for the feature in case anyone has different ideas on how these new lights should work or other suggestions. Also taking suggestions to improve the existing light replacer, if there's any notable problems with it.

Progress checklist:
- [x] Port light replacer to Nano
	- [x] Base features work
	- [x] Emag functionality works
	- [x] Borg replacer works
- [ ] Smart lights
	- [x] Base type added, can be customized with light replacer
	- [ ] Remote light controller, linkable with lights by multitool
	- [ ] PDA app that works as a light controller

**Comment by PJB3005** [comment]
Sort of related: Eris turns the lights in an area blue when the area gets decompressed, and I believe red when a fire alarm is active. Instead of that ugly overlay we have right now.

**Comment by nuklearcellphoneg** [comment]
Now that's a bright idea! @Probe1

**Comment by ghost** [comment]
I like the alarm light idea, though it's not necessarily reliant on this. It can technically be done without any special light types though I don't like that since it wouldn't make sense for default lights to be able to change color. Maybe special alarm lights could be added and mapped in that have a really wide range but only turn on when there's an alert?

**Comment by Probe1** [comment]
STOP IT @nuklearcellphoneg

**Comment by west3436** [comment]
Closed via #35322
