### ISSUE TITLE
Clown crayon color selection is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24701]
(WEB REPORT BY: lemonthefruit REMOTE: 206.221.180.138:7777)
# Revision
de55f3e248eb792412a720de8606af4810609eb1

# Description
When selecting the two colors for the clown crayon, each color changes to black no matter which color you select. This results in a very drab clown crayon.

# Steps to Reproduce
1.Get a clown crayon, and hold it in your active hand.
2.Use the clown crayon (activate held object)
3. in the color selection menu, pick any two colors.
4. Watch the box where your selected colors should appear, notice that your first color changes to black after it prompts you to select your second color
5. after selecting your second color, try and draw with the clown crayon.
6. Notice that any drawing you have, is black, despite the colors that you selected.

# What you Expected
Expected behavior is for the clown crayon to have the ability to select two different colors, and allow you to draw graffiti and other things in customizable multicolor.

# What Actually Happened
My clown crayon just makes edgy emo graffiti in black. Very drab, very boring. Not at all joyous or funny.

**Comment by Zth--** [comment]
Duplicate of #24359 but this one has more information

**Comment by ghost** [comment]
Unable to reproduce on latest de55f3e .

**Comment by Dacendeth** [comment]
Couldnt get this bug reproduced either, did notice the box for "current color" always is black despite what it actually draws 
![image](https://user-images.githubusercontent.com/26881007/68048095-39792980-fcb6-11e9-9812-3a12f99f08ee.png)

**Comment by murnandreams** [comment]
Nevermind, I'm retarded.

**Comment by Zth--** [comment]
@LemonTheFruit can you explain how did you fix it in case someone else comes with the same issue?
