### ISSUE TITLE
Can no longr hear while vent crawling.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24713]
(WEB REPORT BY: pancakemines REMOTE: 206.221.180.138:7777)
# Revision
9a956dd2dffa5b0b5e800ddb2bd3b31ea0bd2c49

# Description
While ventcrawling as a MoMMI I am unable to hear anyone "instead getting the error of appears to say something, but you can't make it out from here." Likely caused from https://github.com/vgstation-coders/vgstation13/pull/24664. (This many affect anything in a vent not just MoMMIs.
# Steps to Reproduce
Be in a vent, have someone talk nearby as a MoMMI
# What you Expected
Being able to make out what they said
# What Actually Happened
Couldn't hear them at all instead appears to say something, but you can't make it out from here.

(This makes some sense but really hurts motivation to play MoMMI and if it affects all vent crawlers would hamper the ability to use vent crawling suit to spy on people and I'm sure there's other things it hurts too."

**Comment by Shadowmech88** [comment]
Fixed by #24711 .
