### ISSUE TITLE
[Feature Request] Add ability to measure moles of gas

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2471]
The title covers it.  Ghosts can find out how many moles of gas something contain but regular players cannot.  The device analyzer and breathe deep cartridge PDA are well suited to have this functionality added.  It will improve players ability to understand the amount of gas in an object.  

Adding this function to the device analyzer/breathe deep cartridge and letting it measure rooms, pipes, canisters, and plasma tanks will improve understanding.

**Comment by ComicIronic** [comment]
Analyzers do this. The grey ones.

**Comment by clusterfack** [comment]
I believe he means give it the ability to directly display the moles of a gas. Not give the player the ability to calculate it from the ideal gas law.

**Comment by Probe1** [comment]
Clusterfack is correct.

**Comment by ComicIronic** [comment]
Oh. I should point out, then, that regular analyzers and device analyzers are different things. I'll change the name to avoid confusion over this in a PR.

**Comment by ConkerDev** [comment]
This could be a nice addition to Gas Sensors, and allow for even more autistic TEGs.

**Comment by ComicIronic** [comment]
Closeable since #2508.
