### ISSUE TITLE
Snaxi: Remove Loot

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24748]
Ice cave loot was fun for a while but now people are powergaming it with tsci so it has got to go

**Comment by ProfanedBane** [comment]
Don't we have teleblocking or some such for exactly this?

**Comment by Kharkov72** [comment]
we do, but teleblocking something in relatively easy to access snow on z1 feels like a recipe for silent depopulation

**Comment by Tokanova** [comment]
will uh, the loot be replaced with something?
could put anything worth getting into the Safe in the syndie loot cave, can't telesci powergame that.

**Comment by Kurfursten** [comment]
The room itself is nice. It's a rapecape in an isolated location with advanced security cameras, a crew monitor, a message monitoring computer, a few close proximity radios, and generally just a well lit, warm place in the wastes to do stuff in secret. There's no longer hostiles so YOU can be the syndie at the listening post.
