### ISSUE TITLE
Snaxi engineering problems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24742]
(WEB REPORT BY: pancakemines REMOTE: 206.221.180.138:7777)
# Revision
2b3919b774cdac865f5eeaf216710de85cbfaf31

# Description
Just a list of things that I think should probably be changed on snaxi ranging from actual issues to my autism.

There are no cameras in the small shacks in the snow where the bypass valves are for distro and waste for each dome. This means an AI CANNOT without help bypass the dome filters. This hurts AI plasmaflooding by making it impossible to flood anything but the engineering dome.
The plasma sheets provided to engineering are only 1 sheet, this should be 30.
There is no stock part vendor in tech storage or in engineering however there are two youtools within 7 tiles of eachother.
There are no viro circuitboards in tech storage.
The metal and glass placements are strange. Other maps provide 3 stacks of metal 2 stacks of glass requiring only basic engi access with two more stacks within atmos. Snaxi has one stack of metal and glass requiring engineering access (no mechanics)

From this point it's autism issues only.

The vents in the miners are not set to 1441hz frequency, every other map has them on this except possibly packed.

The pump to vent distro into waste is a Gas pump instead a volume pump, every other map uses a volume except packed.

The distro gas meter is unlabeled and on 1439hz. Every map including packed has this labeled as dloop_atm_meter and on 1441 hz.

The RPD and the glass are on a table at the far top left of atmos while the metal is right by the door, I would suggest swapping the locker to the top left and making the table a double with both the glass metal and RPD. Also there should be one extra stack of metal and glass inside atmos.

On looking closer all meters in atmos are unlabeled and on 1439hz I would imagine they usually all have IDs and are on 1441hz but I don't know them all on other maps.

**Comment by Tokanova** [comment]
bro how can you even get plasma flooded, just walk out into the snow bro, just walk outside

**Comment by Kharkov72** [comment]
it seems to be 1443 on the map I'm using as a basis "Box" (for the meters not the scrubbers), but this will be done
