### ISSUE TITLE
Krampus is part starfish

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#2474]
![ss 2015-01-08 at 04 52 05](https://cloud.githubusercontent.com/assets/9064611/5660793/4191d3c6-96f2-11e4-80c7-066acd2e5a41.jpg)

When Krampus loses a limb, the sprite for the severed part is just the Krampus sprite again.

Apparently Krampus can come up from the Staff of Change, so this is probably a bad thing

**Comment by Arthurdentist** [comment]
I don't think Krampus should be available from the staff of change anyway, it strikes me as really weird that you can become a race that only exists for Christmas badminery via the staff of change.

**Comment by Arthurdentist** [comment]
Jumped onto the server just now to test this for certain, you can staff of change someone into Krampus.

**Comment by Cisrox** [comment]
Fixed. Please close.
