### ISSUE TITLE
Holomaps are fucked on snaxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24759]
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
fe2dbdd6e4266ec842f8cd0f30224d5048699afd

# Description
Holomaps are very off center
# Steps to Reproduce
Just use a holomap on nusnaxi
# What you Expected
a good holomap
# What Actually Happened
a shit one

**Comment by Probe1** [comment]
@Kurfursten

**Comment by Kurfursten** [comment]
Should base it off world size or world center
