### ISSUE TITLE
[Snowmap] People with Medbay access can't open the Medbay Breakroom Maintenance door

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24757]
(WEB REPORT BY: irradiation REMOTE: 206.221.180.138:7777)
See title.

**Comment by SonixApache** [comment]
not a bug

**Comment by Kharkov72** [comment]
seems implimented, just implimented wrong?
It's supposed to be in req_one_access_txt not req_access_txt, because that makes it require both
