### ISSUE TITLE
SnowMap Holomap

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24754]
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
fe2dbdd6e4266ec842f8cd0f30224d5048699afd

# Description
Holomap is off center as a sprite and as a popup.
# Steps to Reproduce
Go to a holomap.
# What you Expected
It to be centered.
# What Actually Happened
Its off center.

**Comment by Probe1** [comment]
duplicate even though this is the first i commented in the other one oops
