### ISSUE TITLE
Cargo Shuttle Conveyor Belt Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24756]
(WEB REPORT BY: hoborobo REMOTE: 206.221.180.138:7777)
# Revision
fe2dbdd6e4266ec842f8cd0f30224d5048699afd

# Description
The conveyor belt on the cargo shuttle for snow taxi is animated but does not move objects on top of it.
# Steps to Reproduce
Turn the belt on then put something on the shuttle section of belt.
# What you Expected
Stuff moves
# What Actually Happened
Stuff no moves

**Comment by Kurfursten** [comment]
This report is wrong: the conveyor belt DOES work, the problem is the first (topmost) conveyor has the wrong ID tag and won't turn on (Beltinator is capitalized)
