### ISSUE TITLE
Plants wrong sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24765]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
9fdc9f256f0412af3473b54f6f183fe3e86af2f2

# Description
It seems mulitple plants and their interactions sprites are messed up.
# Steps to Reproduce
Find plants / vegetables
# What you Expected
For them to be their regular sprites
# What Actually Happened
I know that glowshrooms and reshi look like apples. And cutting avocado into half makes it so there is no sprite but the item is there.

**Comment by Kurfursten** [comment]
@ancientpower

**Comment by ghost** [comment]
Fixed the avocados but I don't see an issue with reishi and glowshrooms.
