### ISSUE TITLE
Carrots do not appear when grown

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24769]
(WEB REPORT BY: hoborobo REMOTE: 206.221.180.138:7777)
# Revision
cd0b88506175617b8ced59a65b07cc613ef78cb5

# Description
Carrots do not appear in dirt or hydroponics trays when they have finished growing. They can still be harvested.
# Steps to Reproduce
Plant carrots and wait.
# What you Expected
Visibly growing carrots
# What Actually Happened
Carrots are invisible until harvested

**Comment by ghost** [comment]
ez fix, will wait a bit to see if there's any more issues before making it
