### ISSUE TITLE
[Wheelstation] EVA maints isn't radstorm protected.

### ISSUE THREAD

**Issue by SysadminJeroen** [d3athrow/vgstation13#24775]
#### Description of issue
Wheelstation EVA maints isn't radstorm protected.

#### Specific information for locating

![dreamseeker_2019-11-03_23-32-17](https://user-images.githubusercontent.com/2915526/68093163-15267400-fe93-11e9-9c1c-cb0f192c8c63.png)

#### Server revision

3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

**Comment by brndd** [comment]
This is something of a wontfix, because that "maintenance" is part of the utility closet next to it, and creating a separate area for such a small segment of maintenance would be a bit weird.

**Comment by brndd** [comment]
Actually what the hell it's just an area definition and an APC.
