### ISSUE TITLE
Wheelstation PIPES UNDER RWALLS

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#24776]
Pipes under r-walls is a last ditch "I cannot make this work any other way" thing.  Fix this up.  
![image](https://user-images.githubusercontent.com/8550416/68093297-24d99480-fe62-11e9-998f-6aff5132922b.png)

**Comment by brndd** [comment]
This is one of those "can't make this work any other way" things. I can either route the piping through not-maintenance, which is ugly and wrong, or make those tiles glass instead which is bad for engineering's security and would look weird.

**Comment by Probe1** [comment]
Two pipes going under r-walls is better than four.  There's room to cut it in half if you can't think of a better way.

**Comment by brndd** [comment]
I really don't see a better way to do it, but if you have ideas I'm all ears. I don't want to snake the pipes through atmos or the engineering lobby because that's ugly, illogical and something I specifically tried to avoid on this map.

**Comment by Kurfursten** [comment]
Just make them normal walls. Walls aren't super secure.

**Comment by utilitas-** [comment]
No, fuck you, pipes under walls are perfectly fine. Disposals under walls are a crime, but pipes are just fine as long as you make them visible and not hidden.
In fact, I find it a much greater crime to pipe under fucking windows. You can't RPD into those. You can RPD into walls.
