### ISSUE TITLE
[Wheelstation] There is no station power monitoring console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24793]
(WEB REPORT BY: utilitas REMOTE: 198.245.63.50:1337)
# Revision
3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

Ain't no power monitoring computer in engineering that's actually on the station grid, just on the engineering grid. Put one next to the SMES.

**Comment by brndd** [comment]
There should be one in the engineering lobby and one on the bridge. I'll move the lobby one next to the SMES I guess, that's a good idea.
