### ISSUE TITLE
[Wheelstation] No mirror/shower in public science toilet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24795]
(WEB REPORT BY: utilitas REMOTE: 198.245.63.50:1337)
# Revision
3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

Thanks for explaining 95% of the issue, title. That toiled south of the paramedic station? No mirror or shower. Needs at least a mirror. Also, borg recharging station.

**Comment by brndd** [comment]
I'm adding mirrors in there, but not showers. Nor a borg recharging station because there's one two rooms to the left in the mech bay.
