### ISSUE TITLE
Putting on shoes necessitates two clicks

### ISSUE THREAD

**Issue by Duny-** [d3athrow/vgstation13#2479]
Tested with magboots. Works correctly when swapped, but you need to click twice to put on shoes on bare feet. Things get wonky when combined with the helmet light issue.

**Comment by d3athrow** [comment]
I dont understand.

**Comment by Duny-** [comment]
Strip, take shoes, click in your inventory where shoes go, shoes stay in your hand.
Click again, shoes actually go in the inventory.

**Comment by clusterfack** [comment]
I tested this and didn't encounter this issue at all.

**Comment by Duny-** [comment]
Just tested it again, seems to be fixed now for some reason.
