### ISSUE TITLE
[Wheelstation] Certified Mint Fwesh

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24801]
(WEB REPORT BY: utilitas REMOTE: 198.245.63.50:1337)
# Revision
3b89a11cb244e3fde2e19fcd4f43a5d07b10fcc1

You didn't change the directions on the coin mint when you copy'n'pasted it, my dude. It inputs from the west and outputs to the east. West is a wall. It should input from the north and output to the south. Also, there are crates in the way.

**Comment by brndd** [comment]
I thought this thing uses the markers like some of the other `/obj/machinery/mineral/` machines, but guess not.
