### ISSUE TITLE
Smelting at mining outpost lacks an ore redemption machine

### ISSUE THREAD

**Issue by GalagaTwo** [d3athrow/vgstation13#2482]
The machines at the outpost are outdated and require updating.
As it stands, smelting ores at the mining outpost leads to a miner gaining no account credit for their collected materials, which can be frustrating in the journey to purchase a Jetpack or a Lazarus Injector.

**Comment by dylanstrategie** [comment]
Problem with the ore redemption machine, not the mining smelter

No way I'm trashing the entire smelting apparatus for some magic smelting into alien toys machine, which doesn't even do special alliages

**Comment by Intigracy** [comment]
Fixed recently.
