### ISSUE TITLE
wheelstation vox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24837]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
0917fb8db0c423346b5b89c63853ec3bd0d38165

# Description
vox shuttle doesn't have ATMs and also i want an armory with a crossbow like roid but that's just a personal thing
# Steps to Reproduce

# What you Expected
get credit
# What Actually Happened
my business was run out of town for not properly facilitating trade

**Comment by brndd** [comment]
I'm adding an ATM on the shuttle as well as fixing a bunch of other issues about the outpost. Don't think I'm gonna add the crossbow, but you do get a water gun that hopefully is a worthy replacement.
