### ISSUE TITLE
Atmos control in TEG room

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24834]
(WEB REPORT BY: nakerbott REMOTE: 206.221.180.138:7777)
# Revision
0917fb8db0c423346b5b89c63853ec3bd0d38165

# Description
Atmos control in the TEG room in Wheelstation is broken. It's turned on the wrong way and you can't control the vents and scrubbers with it.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by brndd** [comment]
There actually was no air alarm in that room at all. The misaligned one was built by someone. #24825 adds an air alarm in the room.
