### ISSUE TITLE
Wheelstation pipe feedback

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24843]
(WEB REPORT BY: pancakemines REMOTE: 206.221.180.138:7777)
# Revision
2f0112a1a023502d681c11f20a59b267a7e9abcc

# Description
piping issues.
Distro.

Section N
4 way manifold outtside medbay by the west vent should be a 3 way manifold the one west of this next to research
Vent inside server room is under the RD server console 
cent in cmo office is under the desk

Section E
Pipe at Evac missing for distro and waste after second vent leaving security area disconnected
Kitchen vent pump is under the table

Section C
Manifold attached to vents outside arrivals pod is 4 way should be 3 way
Main dorms vent is under a table

Section W
Captains room vent is under a table

Section S
Atmos main room vent under table
atmos suit room vent under table
Something weird with the secure storage distro pipe you can crawl out of secure storage but not into it might be layering?
The dual port vent in telecoms links engineering waste and distro no idea if that might be an issue never seen one before. same thing in security airlock

Waste. 

Section S
Another laying issue can't vent crawl into telecoms 
Engineering main lobby scrubber under table
scrubber under table in atmos suit room

Section W
Scrubber in HoP bedroom under table

Section C
Trader dock air scrubber 2 under table
Arrivals hallway scrubber 2 has a 4 way mainfold instead of a 3 way (I just realized I should have been using their assinged names but i cant be bothered to go back and give the names for the others my bad)
Secruity checkpoint missing a pipe under the locker, scrubber isn't connected
Dormitories air scrubber #1 under bed

Section N
Northern hallway air scrubber #2 & #3 both using 4 way manifolds instead of 3
CMO office air scrubber #2 under desk

Section E
Evac security waste not connected as mentioned
Kitchen air scrubber #1 under table

And we're done, I mentioned all vents and scrubbers under tables because I feel like it's good practice to keep them in the open in case of emergencys where they need welding/fixing/are the source of a problem.
Final notes, expect to see a lot of mommis walking about opening doors navigating five distros that seperate departments is tedious and honestly it doesn't do much for preventing a total plasmaflood but selective flooding is kind of cool not sure if it's worth it.
Also the ghetoo kitchen needs a meat locker and a cleaver unless it was taken by the time i looked.

**Comment by brndd** [comment]
Good list, thanks.

>Final notes, expect to see a lot of mommis walking about opening doors navigating five distros that seperate departments is tedious and honestly it doesn't do much for preventing a total plasmaflood but selective flooding is kind of cool not sure if it's worth it.

Yeah. This is something where I'd like to make the MoMMIs lives a bit easier somehow, but I'm not really sure what can be done for them without compromising on the pipe design. The purpose of the segmented design isn't to prevent a total plasmaflood, it's to make the pipe system more resilient to sabotage and getting drained by breaches. This way if there's a problem with atmos, say distro connected to waste somewhere, it's narrowed down to 1/5th the station.
