### ISSUE TITLE
[Wheelstation] Telecomms broken vent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24846]
(WEB REPORT BY: nakerbott REMOTE: 206.221.180.138:7777)
# Revision
2f0112a1a023502d681c11f20a59b267a7e9abcc

# Description
one of the vents isn't connect to its atmos control and is siphoning instead of venting

**Comment by brndd** [comment]
That's the telecomms cooling setup. Working as intended.
