### ISSUE TITLE
Wheelstation Arrivals shuttle Space door

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24842]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
2f0112a1a023502d681c11f20a59b267a7e9abcc

# Description
Arrivals shuttle has 2 doors go to space
# Steps to Reproduce
Play Wheelstation
# What you Expected

# What Actually Happened
SPACE

**Comment by brndd** [comment]
This is fixed by #24818
