### ISSUE TITLE
Wheelstation mounted flashers in the brig are not connected

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24849]
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
8e738f033447e7f6a832ad062d270088001176a4

# Description
The mounted flashers in the brig are not connected to anything on wheelstation. They can't be triggered from outside the cell.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by brndd** [comment]
Oof, I forgot their ID tags. The only one that works is cell 4's flasher, I presume.

**Comment by stormcloud23** [comment]
Yes, cell 4 has 4 "activate flash" buttons
