### ISSUE TITLE
Cannot talk as pAI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24848]
(WEB REPORT BY: rhydensmethod REMOTE: 206.221.180.138:7777)
# Revision
920060a228429861c5d3d530df55274899eb0059

# Description
Unable to use Say/Me command as a pAI, when relogging they commands vanish entirely
# Steps to Reproduce
On inital download, I was okay, but once shifted around an inventory say/me stopped working
# What you Expected
To be able to talk (say)
# What Actually Happened
Unable to talk (say)

I tried reporting this last round, but it didn't seem to work. Don't know if there will be seperate reports.

**Comment by Shadowmech88** [comment]
I doubt this is due to the recent saycode changes for atmospheric speech, if the verbs themselves disappeared and even emotes were affected.

**Comment by Dacendeth** [comment]
apparently changing your screen breaks it.

**Comment by jknpj** [comment]
This makes no sense

**Comment by jknpj** [comment]
Unable to reproduce the issue with changing screens
