### ISSUE TITLE
Heads of Staff Meeting Room Needs Windoor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24841]
(WEB REPORT BY: generalveers25 REMOTE: 206.221.180.138:7777)
# Revision
2f0112a1a023502d681c11f20a59b267a7e9abcc

# Description
You can just crawl under the airless flaps and get into the Meeting Room on the Bridge. Maybe this shouldn't be so easy?
# Steps to Reproduce
Lay on the ground.
Do the worm
Murder the Heads of Staff
REVOLUTION MAJOR VICTORY
# What you Expected
A windoor
# What Actually Happened
No windoor.

**Comment by brndd** [comment]
Presumably this is for Wheelstation. There should already be a windoor there set to bridge access. Perhaps someone broke it?
