### ISSUE TITLE
Wheelstation doors aren't labelled

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24840]
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
2f0112a1a023502d681c11f20a59b267a7e9abcc

# Description
On other stations, doors will have a description pop up in the bottom left, like "Maintenece", "Primary Tool Storage", etc when mouseovered. Wheelstation does not have this.
# Steps to Reproduce
Mouse over doors/airlocks.
# What you Expected

# What Actually Happened

**Comment by brndd** [comment]
*most* of them should be. Case in point, Primary Tool Storage: 
![1572924723643](https://user-images.githubusercontent.com/5822375/68176470-a1b55d00-ff8d-11e9-88a0-603954bc2647.png)


That said, there are no doubt individual doors that have generic names, so let me know about any specific ones you find.

**Comment by stormcloud23** [comment]
Apologies, this may actually have been an issue on my end. Most of the doors seem to be labelled. I had an issue where none of them appeared to be.
