### ISSUE TITLE
Wheelstation holodeck camera is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24854]
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
ced1b64810a7dc1686864cd0d741fefd8fe28230

# Description
Wheelstation holodeck security camera starts the round broken
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by brndd** [comment]
That's just the random broken cameras feature at work.
