### ISSUE TITLE
Captains helmet lighting nonfunctional... and can be two hand held?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24900]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
18a8a1b1ea425695a47f25b7a47ed2b06519441d

# Description

For some reason captains helmet isnt lighting when the toggle rig light is activated
# Steps to Reproduce

Try activating captains helmet rig light
# What you Expected
light
# What Actually Happened
darkness

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/68437348-ab59e300-018e-11ea-8b38-3f4756c703a0.png)
blame this I think

**Comment by ghost** [comment]
>and can be two hand held?

This is a bug with all rig helmets, apparently. It's not caused by my PR #24563. ~~I just tested locally and the light still worked for me.~~ ~~It works at first but I think two-handing it breaks it? I'm looking into it.~~

**ITS A FEATURE**

**Comment by jknpj** [comment]
The light thing isn't a bug, but the two handling...

**Comment by Exxion** [comment]
Why isn't `HIDEHAIRCOMPLETELY` on `clothing_flags`?

**Comment by Zth--** [comment]
Remove that flag, I'm 98% certain it's unnecessary
