### ISSUE TITLE
Honkstation issues: #6, #7, #8, #9

### ISSUE THREAD

**Issue by nullquery** [d3athrow/vgstation13#2490]
Hi,

This issue is for the discussion of implementation of issues from our project Honkstation.

How I see this working is that I post a list of issues that I intend to work on, and everyone else complains about how it can't be done / would be useless / would break things.

Then I'll (probably) do it anyway (taking into account some of the suggestions made here), and hope that my stuff gets pulled so I don't have to manually resolve conflicts in the future.

[#6](https://github.com/gonebananas/vgstation13/issues/6): Generic database management

Involves: Creating a wrapper for database operations that allows both MySQL and SQLite to be used & passed through one method. The idea is to include support for prepared statements (or the soft-coded equivalent thereof in MySQL) and 'helper' procs such as:

```
Database.getDBV("SELECT byondkey FROM players WHERE ipaddress = '127.0.0.1' ORDER BY byondkey LIMIT 1")
```

Which would either return an empty text string or the BYOND key of the 1st player encounted with the IP address 127.0.0.1 sorted by BYOND key.

My intention is to migrate the players2.sqlite file immediately, and leave the rest as-is for possible future migration or deletion (whichever is preferred upstream).

[#7](https://github.com/gonebananas/vgstation13/issues/7): Administrator panel

The current one is just awful. Multiple screens to navigate through, no automatic updates when stuff changes.

My new approach would involve using the HTML interface module to create a single admin panel which can then be duplicated by administrators and navigated to the appropriate module.

When watching players/objects it would automatically update variables as they change. Also intend to look into including a station map similar to crew monitoring but with everything located on it.

This would also involve redoing the permissions system and managing administrators and ranks in an XML file.

[#8](https://github.com/gonebananas/vgstation13/issues/8): Generic configuration

Involves getting rid of all existing .txt files and adding an XML parser instead, to standardize the creation of configuration files and making it OOP instead of manually parsing individual files.

[#9](https://github.com/gonebananas/vgstation13/issues/9): Clown population

We intend for administrators to be able to force players to be a clown every time they join as an alternative to banning them outright. I intend to develop a feature that allows this, but I'd like to implement it in a generic way so that it can be used for all sorts of roles. This is on hold for the moment pending other issues.

**Comment by nullquery** [comment]
Note: I've updated the issue with links to the issues in our repository. If you click on the issue numbers you will be redirected to our issue tracker.

**Comment by ririchiyo** [comment]
Well, people can already be forced as cluwne only when they join, so that's already in at that moment. There's a cluwne ban. The entire database stuff does need to be reworked though, I only threw the sqlite functions for character saves in a quick manner. None of the information is really cached because of how unoften it will be updated outside of when a round starts. I started working on a ticket system where I was probably going to use the current sqlite database we have but it would work with cached information and only open and save the database when saved and then close it instead of the current one where the sqlite database is open throughout the round making it easy for people to update preferences any time.

**Comment by ririchiyo** [comment]
I'd like to clarify that proper use of SQLite queries is to use ? and specify the variables at the end as it has its own bindings before you heavily get to work on it.

**Comment by nullquery** [comment]
I know -- I'm aware of how prepared statements work because of my day job. I intend to implement it in the same manner.

**Comment by Kurfursten** [comment]
@clusterfack Can probably be safely closed. Honkstation hasn't seen development in 9 months, and it is a /vg/ fork. Null is more active on /tg/ branches nowadays anyway, as far as I can assess.
