### ISSUE TITLE
Remove virus spam PLEASE

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#24902]
```
DEBUG: Bacteria 1868-8429 in *no key*/(Spencer Fryer) has been cured, and is being removed from their body.
DEBUG: Bacteria 4634-4700 in *no key*/(monkey (792)) has been cured, and is being removed from their body.
DEBUG: Bacteria 4634-4428 in *no key*/(monkey (792)) has been cured, and is being removed from their body.
DEBUG: Bacteria 4634-2942 in *no key*/(monkey (792)) has been cured, and is being removed from their body.
DEBUG: Bacteria 1868-8429 in *no key*/(monkey (359)) has been cured, and is being removed from their body.
```

It lags the fucking game with all the fucking spam and it's not being used, move it to a debug verb for fucks sake. Why the fuck is this even a thing?

**Comment by boy2mantwicethefam** [comment]
How can messages lag the game?

**Comment by Zth--** [comment]
When you to_chat a lot of messages at once your client freezes a bit (at least mine)

**Comment by DeityLink** [comment]
That's a very old debug message, definitely predates nuviro. I think admins don't really need to have that message displayed to them though so I'll remove it as requested. It'll still appear in the logs I guess.

**Comment by DeityLink** [comment]
Oh ok the procs that saves stuff to the logs also spams admin chat, that's dumb

**Comment by DeityLink** [comment]
@Zth-- 
![image](https://user-images.githubusercontent.com/7573912/68503044-335ced00-0262-11ea-8600-6ce35f484b76.png)

**Comment by DeityLink** [comment]
so yeah it's a log_debug()
