### ISSUE TITLE
Windows that lasers are not passing through physicall reduce the damage still.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#24922]
#### Description of issue
Lasers do reduced damage when they pass through windows (light scattering or whatever) which is an alright feature, but where the problem lies is that windows the laser isnt actually physically passing through reduce it's damage, and full windows do nothing to reduce.

#### Steps to reproduce
The biggest glaring example I can provide for this is the following picture. 
![image](https://user-images.githubusercontent.com/26881007/68527345-cd00ba80-02b3-11ea-99d4-7f2857306c90.png)
 Each one of those windows on the tiles the laser is going through is reducing the damage to the target on the other side to almost zero as all 10 of those window panes are counted, when it physically looks like none of them would do that.

Full tile windows don't reduce laser damage at all, which seems like an oversight to me or something changed involving them to make them not count, either way it feels wrong.

**Comment by utilitas-** [comment]
full tile windows are fucky in general, they still have a "direction" in which they actually block everything, they aren't full at all
