### ISSUE TITLE
Mouse and spiderbot ventcrawl verb is out of date

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#2492]
Aliens, monkeys and other ventcrawlers use the handle_ventcrawl() proc, while mice and spiderbots don't

This results in harder ventcrawling for mice and spiderbots as the list of vents isn't sorted, and they always crawl to the most bottom-left vent in the area instead of being able to choose a particular vent. This makes cargo warehouse and possibly some other areas impenetrable to mice & spiderbots.

**Comment by vgrainicorn** [comment]
You can reach those vents as a mouse actually, crawl to a vent, don't move and crawl to it again to cycle between all the vents in that area.

I'm not saying this isn't an issue but I was just throwing that out.

**Comment by Unfit** [comment]
That didn't work for me, because there are three vents in the area, with the warehouse one being the most top right one (meaning it was the farthest one from 0,0). And in its current state, ventcrawl verbs on mice and spiderbots teleport you to the most bottom left vent in the area (that isn't the one you're crawling through).
