### ISSUE TITLE
Snowmap Asteroid Turfs (Cave Floor)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24928]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
d9a448cb52478dd856d1d65eefa22203a2e3f86c

# Description
Cave Floor turfs on the Snowmap hold pressure, 55kpa, 20/80 O2 N2 at -150c constantly to be specific. This means that half the "asteroid" is pressurized and the other half isn't. Which also then means, if a mob you're fighting steps off into the Cave Floor tiles suddenly you're fighting something 5x stronger because your KPA does no damage and then a goliath walks up to you and breaks all your toes and you die screaming thinking the goliath is super mega buffed and admins are just fucking with you god i'm really mad can't you tell 

# Steps to Reproduce
1. load snowmap
2. get shuttle to asteroid
3. whip out that kpa
4. kite a goliath like a pro
5. uh oh it's on a cave floor tile
6. atmospheric analyzer when your kpa has a reduced effect for ???
8. more question marks appear above your head
9. die while you're confused

# What you Expected
there's actually two expectations here
the first is:
the asteroid to be airless, like al the other asteroids.
the second is:
the whole cave to be pressurized and cold like it's a cave under the snowmap we're mining out and for us to then have different guns for it or something that aren't pressure reliant

# What Actually Happened
i died please restart my gun no work everything sucks i'm crying irl don't go to the asteroid tomorrow

**Comment by Kharkov72** [comment]
feature
(really, I think the best way to fix this would be to have special roid rocks that decon into cave tiles.
mmmm, underground mindshaft 🤤 )

**Comment by Kurfursten** [comment]
I likely will do that, in time, but until then, we should kill the cave tiles -- especially on the roid
