### ISSUE TITLE
Bussing revolutionaries instantly ends the round

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#24923]
#### Steps to reproduce
- Give someone the revolutionary role
- Add them to the revs faction
- SMELELELELELELE
- die inside

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by utilitas-** [comment]
so what you're saying is copy this behavior to cultists

**Comment by ShiftyRail** [comment]
Was there any heads of staff present

**Comment by DamianX** [comment]
yes

**Comment by Kurfursten** [comment]
end() shouldn't even be getting called anymore at all by revs for a fail condition, what did the message say? did it say all heads dead?

**Comment by Intigracy** [comment]
might be that it thought all revheads were dead, if the person was made a normal rev

**Comment by Kurfursten** [comment]
What I think is more likely is that the code checks regularly to see if any of the jecties are pending, and if there are no jecties without SUCCESS, it ends the game. Probably the code did not automatically populate faction jecties to target all heads when the first rev was made, resulting in instant victory.

Basically, you would need to immediately call either forgeobjectives or onpostsetup after creating the rev faction... you'd only have one tick, 2 seconds, to do this.

**Comment by DamianX** [comment]
Yes, the jecties list was empty.

**Comment by Kurfursten** [comment]
I think the easiest solution to this is that if the jecties list is empty, instead call forgeobjectives and exit early. Revs would be unable to win if there are no heads in the first place.
