### ISSUE TITLE
Placing APC down on Snow Taxi (And respectively turning it back on) causes nuclear lag.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24932]
(WEB REPORT BY: caboozles REMOTE: 206.221.180.138:7777)
# Revision
d9a448cb52478dd856d1d65eefa22203a2e3f86c

# Description
Was trying to make a small room, threw an APC down, nuked the planet. Probably should have used the blueprints to change it first.

# Steps to Reproduce
Just put an APC down, don't change the blueprint, it shuts down the grid of everything not indoors. (THANKS ANCIENT, THAT'S WHY I AHELPED TO ASK FIRST)

# What you Expected
For the world to not explode

# What Actually Happened
The world exploded and caused horrendous lag for about thirty seconds. Probably reinitialized everything.

**Comment by ghost** [comment]
whoops

**Comment by Kurfursten** [comment]
related to #23967
