### ISSUE TITLE
Snaxi security camera map bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24933]
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
d9a448cb52478dd856d1d65eefa22203a2e3f86c

# Description
Security cameras arer off-center on the advanced security cameras computer map on snaxi
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
duplicate of https://github.com/vgstation-coders/vgstation13/issues/26028
