### ISSUE TITLE
MEGAMADCRAB does not drop crab meat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24931]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
d9a448cb52478dd856d1d65eefa22203a2e3f86c

# Description

Muh Emmulshons
# Steps to Reproduce

Kill MEGAMADCRABS, butcher MEGAMADCRAB
# What you Expected

Crab meat

# What Actually Happened

Crabs drop RED MEAT

**Comment by Exxion** [comment]
Alchemy through anger
