### ISSUE TITLE
Snaxi vox station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#24934]
(WEB REPORT BY: burneddi REMOTE: 206.221.180.138:7777)
Half the vent pumps are set to the wrong frequency and aren't controllable through the air alarms.

~~The NanoMed in the room to the east across the hallway from the botany trays has access restrictions and can't be used by the traders.~~

**Comment by Durgen** [comment]
~~one of the tool vends also has access restrictions~~

**Comment by Kurfursten** [comment]
NOTE: I incorrectly marked this as fixed in my latest PR.

It does fix the access issues on all vending machines, but it does not systematically fix all the vent freqs.
