### ISSUE TITLE
Admin Jumpsuit Needs to Be Blacklisted

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24935]
Thanks to Yred for finding this one

/obj/item/clothing/under/acj isn't blacklisted from spessmart and even spawns as the uniform of the Agent Jensen corpse spawner on the away mission list

**Comment by Kharkov72** [comment]
feature

**Comment by Intigracy** [comment]
armor = list(melee = 100, bullet = 100, laser = 100,energy = 100, bomb = 100, bio = 100, rad = 100)

**Comment by SGuivenne** [comment]
Feature???

**Comment by boy2mantwicethefam** [comment]
FEATURE

**Comment by Exxion** [comment]
Honestly an invincibility jumpsuit found one round in a hundred is funny enough to just leave in

**Comment by tuypo1** [comment]
Great thing is if it showed up on rare occasions it would be a good chance to give an excuse for non antag sing loosing, it would be the only good way to take out somebody wearing one
