### ISSUE TITLE
Targeting rings never disappear

### ISSUE THREAD

**Issue by LisandraBrave** [d3athrow/vgstation13#2493]
Step 1: obtain laser tag gun
Step 2: set intent to target
Step 3: target someone
Step 4: set intent back to auto
Step 5: Repeat for everyone on the station
Step 6: Honk

Comic says: This appears to be affecting all weapons, and is therefore an issue with aim code.

**Comment by ConkerDev** [comment]
I think this might be an issue with more than the laser tag guns. It happened to me during a firefight. Needs testing

**Comment by Cipherature** [comment]
Can confirm it happens with more than just laser guns.

**Comment by clusterfack** [comment]
A fix has been merged. Closeable.
