### ISSUE TITLE
queueing on mechanic machine broken

### ISSUE THREAD

**Issue by LisandraBrave** [d3athrow/vgstation13#2494]
Step 1: put in blueprint
Step 2: put at least two things in the production queue
Step 3: machine prints the first thing till it runs out of materials

**Comment by d3athrow** [comment]
@ComicIronic

**Comment by ComicIronic** [comment]
I'm looking into the code, but it isn't immediately obvious what's going on.
I'll see if it's an issue with queue_pop() or something, but otherwise I might need to do a minor change to the way queueing affects the blueprint uses system.
Have experienced this myself in the past, though.
