### ISSUE TITLE
Trouble Swapping Into Belt Slot

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#24974]
I think #24626 probably caused it

Lately when I try to quickswap an item (whether by dragging the icon, hotkey, or clicking on the UI) to the belt slot, it won't work if the swapping in item is a container. This is very frustrating because this happens:

>accidentally misclick and swap the screwdriver into my belt slot, now have belt in my hand
>CANNOT quickswap the belt into my belt slot, must fully remove the screwdriver and place the belt into the open slot

**Comment by ghost** [comment]
I'll investigate this when I get a chance. I was sure I had addressed all the issues with swapping belts but I guess not.

**Comment by SonixApache** [comment]
fix it
