### ISSUE TITLE
[Feature Request] New Detective Title - Private Eye

### ISSUE THREAD

**Issue by stormcloud23** [d3athrow/vgstation13#24980]
<Feature Request>
I think it'd be neat if the detective got a Private Eye job title he could pick to go along with gumshoe and forensic technician. Functionally it would be the same as the gumshoe (IE starts with black coat/hat and the noir gene), so you could basically just copy that code and change the name, but gameplay/RP wise you'd be more of a private investigator for the crew, rather than working directly for security. Kinda like the Lawyer, you'd advertise your services, talk in metaphors, track down lost items, find out who broke into a client's office, etc. And of course nothing's stopping you from assisting security should the need arise. It's a pretty subtle difference I suppose, but the term "gumshoe" usually refers to police detectives, not private investigators, which were more the subject for those old noir films which the aesthetic is meant to fit. I think it'd give the detective role slightly more flexibility in role play without really detracting from anything.  

[This is the kind of vibe I'm thinking of.](https://i.pinimg.com/originals/a3/02/43/a302439211e424a99dc5eb390830715d.jpg)

**Comment by Kurfursten** [comment]
I don't have a strong mental association of gumshoes being only police detectives, I think no one would get on your case for roleplaying an independent contractor

**Comment by stormcloud23** [comment]
For sure you can, I just think the title fits a little better. Not a huge issue, of course. Just a bit of flavor that might be neat to have.

**Comment by Probe1** [comment]
I'm cool with it but wouldn't that mean they would lose their security access if they were an independent contractor?

**Comment by Shadowmech88** [comment]
Detective is an access class all its own for the Detective's Office, isn't it?
Would it being a separate title allow the access to be customized to just Detective and Maintenance access?

**Comment by stormcloud23** [comment]
> they would lose their security access if they were an independent contractor?

That's one way to go with it, yeah. I was just thinking as more of an RP thing, but losing sec access might force you to get a bit more creative with some things. 

>Detective is an access class all its own for the Detective's Office, isn't it?

Pretty sure it is, yeah. Regular officers can't get in there. 

>Would it being a separate title allow the access to be customized to just Detective and Maintenance access?

Either that or just a rename for flavor purposes. Though dropping sec access does make it a bit more interesting, and maybe it could get some other small thing to compensate. And the HOS/HOP can always bump their access up after the fact if they're deputized/working with the security team.

**Comment by DrSnips** [comment]
Considering how everything else detective office is already conneted to security by literal touching or neighboring it I don't think its going to do much. No offence to detectives but there's no reason any security officer would want to go into the detective office because the scanner is a joke 80% of the time.
I think just making it an alt title and calling it a day is fine. Don't overthink it.

**Comment by stormcloud23** [comment]
Alright. If it's just a matter of duplicating gumshoe and changing the title, it should be pretty easy to implement. I don't have much experience with byond, but that's probably something I can try to do.

**Comment by stormcloud23** [comment]
I managed to do just that, and after compiling and testing locally it seems to work just fine. Title shows up, and gets applied properly to ID/PDA. Do I need special permission to open a pull request for it?

**Comment by stormcloud23** [comment]
I managed to do just that. It compiles and after local testing seems like it works just fine, with the title applied properly to the ID and PDA. Do I need special permission to push a branch and make a pull request?

**Comment by Kurfursten** [comment]
You need to push to **your** remote repo and then it will allow you to make a pull request when you view this repo.

**Comment by stormcloud23** [comment]
Gotcha, makes sense. Working on it now. Thanks.

**Comment by gurfan** [comment]
shouldnt this be closed?
