### ISSUE TITLE
Defficiency Mechanic lockers

### ISSUE THREAD

**Issue by Pastamancer** [d3athrow/vgstation13#2499]
I'm not sure if this is intentional, but there's a huge lack of insulated gloves on defficiency. If this was box, I'd be fine with that, but when half the fun of the map is building things then it becomes an issue. Mechanics start with their standard 2 lockers, but the other 2 yellow lockers that are present on Boxstation are not in the Mechanic office on Deff. These lockers have relevant to supplies to the few mechanics that don't just spam chem dispensers everywhere.

**Comment by ConkerDev** [comment]
Solved by #2505
