### ISSUE TITLE
Snaxi: Virology Doors Buggy

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#25008]
They seem to not be responsive to the buttons fully? Cycle didn't work

**Comment by Kurfursten** [comment]
Also there's a floating sign by it

**Comment by Caboozles** [comment]
The sign isn’t floating at start. The sign is slapped directly on top of the external virology button. You physically cannot enter virology unless you move it. Which admittedly is just a screwdriver, but for doctors that’s hell.

**Comment by Exxion** [comment]
Couldn't you use Alt+click?
