### ISSUE TITLE
[Bug] Telecomms machines produce extra wires when disassembled

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2500]
When you disassemble and reassemble a telecomm machine (hub, transmitter, server, et cetera anything except the computers which weren't tried) you're left with an extra coil of wire.  I don't think the accurate amount of wire comes out when you use wirecutters to disassemble them but I'm not sure about the cause, just that when we reassembled all the overheated tcomms machines in a round earlier today, they all produced an extra coil of wire.

**Comment by clusterfack** [comment]
Tcomms in need of a future rewrite for better performance, or a good port. But this should be really easy to fix ill add it to my next
