### ISSUE TITLE
Remove Keys Require Buckle In?

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#25010]
I've had complaints about people running up and pulling the keys out of your janicart/snowmobile. Should we limit pulling the keys out to only the person driving?

Or at least add a timer to removing a key from someone else's vehicle?

**Comment by Zth--** [comment]
Realistically a person would be able to snitch your vehicle key while you're on it. I propose adding a `do_after` for those who are not the driver

**Comment by west3436** [comment]
Linked PR was not merged
