### ISSUE TITLE
Playing bartender on Snaxi is like water torture

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#25014]
This issue dates back to long before it was Snaxi but somehow has never been reported, either by myself or by anyone else, as far as I can tell
If engineers build the AME in the normal place, you can hear it from behind the bar
The occasional but incessant bang noises WILL drive you insane IRL

**Comment by N3X15** [comment]
just hack in and turn it off ezpz

**Comment by Killette2** [comment]
Xenobio on snaxi is torture because you can hear minings vending machines and doors 24/7
