### ISSUE TITLE
Snowmap cargo oversight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25011]
(WEB REPORT BY: bleachednegro REMOTE: 206.221.180.138:7777)
# Revision
f1900bf61d0e7ffaf25ff0e87d3b2e58a75cf0bc

# Description
The top belt of the cargo shuttle conveyor has an improperly capitalized tag, making it not sync with the rest of the belts.
# Steps to Reproduce
Use lever on snowmap cargo shuttle

# What you Expected
Belts to move

# What Actually Happened
One belt not moving

**Comment by Kurfursten** [comment]
Duplicate and already fixed in next PR
