### ISSUE TITLE
Gondola Does Not Understand

### ISSUE THREAD

**Issue by utilitas-** [d3athrow/vgstation13#25017]
They've got no languages and therefore cannot understand anyone.
I think they should have at least Galactic Common, but be otherwise mute.

**Comment by brndd** [comment]
They should be able to understand everything but be unable to speak at all.

**Comment by utilitas-** [comment]
Also do note, Gondola should be able to emote freely. Just, usual emoting rules apply. No
`Jizzle McGondolaFizzle Shut the fuck up`
`Jizzle McGondolaFizzle cuck`
