### ISSUE TITLE
Change map voting so that the same map cannot be voted twice in a row

### ISSUE THREAD

**Issue by brndd** [d3athrow/vgstation13#25018]
[discussion]

Endless streaks of Boxstation or Snaxi or whatever are tiring and can lead to players ditching the server. I think it'd be good to change the map voting so that the incumbent map cannot be voted in for a second term.

For an alternative, more complex solution, make it so that in any sequence of 3 rounds the same map cannot occur more than 2 times. This would mean that you can still vote for a rematch of the map, but after that you'll have to keep alternating between it and some other map if you really want to play it.

Reasons I think this change would be good:

- more map variety

**Comment by utilitas-** [comment]
nah
simpler solution: just remove box and snaxi

**Comment by DamianX** [comment]
What about the 12-hours time span during which packed is the only viable option, though?

**Comment by utilitas-** [comment]
I got the map just 4 u, [rodina](http://i.imgur.com/bOe7cAQ.png)
Alternatively, Microstation

**Comment by brndd** [comment]
~~The problem during those 12 hours isn't Packed, it's the number of players.~~ I parsed that wrong. Packed could be exempt from this or alternatively just deal with lowpop boxstation.

**Comment by SonixApache** [comment]
muh box tho

**Comment by Kurfursten** [comment]
The serverditch thesis is bizarre. There's no evidence for it. Consistently player counts follow American time of day, not 
* game mode
* map
* amount of bus
* whatever
Yet people accept on the face that populations are heavily dependent on [boogieman of choice].

That said I don't feel strongly about this. I do dislike runs of box but not enough to want to ban them if that's what people want.

**Comment by brndd** [comment]
I doubt game mode/map/amount of bus/whatever have a great impact, but long streaks of the same map do lead to people getting upset. While we can only guess at the motivations of the captain last week who called the shuttle on Snaxi and shot anyone who tried to stop it (and then got banned for it), I'd wager there's a pretty good chance he did it because it was the 3rd round in a row of the same station.

I must admit this ~~PR~~ issue wouldn't exist if not for Snaxi. I don't like playing long streaks of *any* map, but the traditional space maps at least play similar to each other. Even the most gimmicky ones like Roidstation are still spacemen in space. Snaxi not only changes round flow dramatically by having 50% of the station's population fuck off into the woods, but the crap design of Taxi combined with having to trudge through snow for five minutes to get food makes it a miserable jobbing experience if you *don't* fuck off into the woods.

If the same map can't be voted twice in a row, there's at least light at the end of the tunnel when a map you can't stand gets voted on. Plus it'd help reduce Boxstation dominance, for whatever that's worth.

edit: it's not a PR; it would be but map voting can't be changed by PRs

**Comment by tuypo1** [comment]
If this happens it probably shouldn't apply to Packed, not unless somebody wants to spruce ministation back up so we have 2 low pop maps to choose from
