### ISSUE TITLE
Construct mob chat

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#2503]
They seriously need one. No really. You can't stay coordinated at all.

**Comment by ConkerDev** [comment]
Use the communicate runes. You even start with them on the rune paper. It makes no sense for humans to have extraordinary telepathic abilities, and it would be way too overpowered.
There is already a hivemind chat, by the way.

**Comment by ComicIronic** [comment]
What is the word construct in the title?

I'd support adding this. Might encourage people to build more constructs, since cult takeover is so rare.

**Comment by IratePirate** [comment]
I think this is a good idea. Right now people barely every make constructs because they're usually so unorganised that they can't coordinate with the cultists or each other. If this was a thing people would be more likely to make them leading to more people coming back into the round.

**Comment by ComicIronic** [comment]
Added in #2716.
