### ISSUE TITLE
Powercreeper and Snaxi are able to exist at the same time

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#25041]
#### Description of issue
You can plant powercreeper on Snaxi, making it impossible to traverse the station without glubs after 20 minutes and making for a truly impossible to destroy monstrosity unless you shardbomb it.  It also lags the serb to hell and back, all for the tidy sum of 16 syndiebux max.

#### Difference between expected and actual behavior
I'm not really sure what I expected, since powercreep is already cancer, but somehow when added to snowmap it manages to not only gunk the map up (expected) but do it in a huge way and slows the game to a crawl (actual).

#### Steps to reproduce
Plant powercreep in the middle of the map on snaxi and wait 30 minutes.

#### Length of time in which bug has been known to occur
It's only really been abused for the last week or so.

[snowmap]

**Comment by utilitas-** [comment]
just remove powercreeper

**Comment by DrSnips** [comment]
Honestly it should be locked away until its creator decides to do something about it or anyone really. The novelty of it has worn off and it's apparent that it's just a buggy mess that negatively impacts the server's health when unchecked.

**Comment by utilitas-** [comment]
powercreeper should act more like the blob, where it can't actually grow very far from any source of power (at least not in any timely fashion) so it doesn't spread like a cancer wildfire
it also looks like ass and is horribly annoying to remove, so I'd add the option to make it decay by wildly varying the amount of power in the network

**Comment by Tokanova** [comment]
no reason not to shard bomb powercreeper on snaxi, theres no breaching on snaxi.

**Comment by tuypo1** [comment]
>no reason not to shard bomb powercreeper on snaxi

Some of us have mechanical organs you know
