### ISSUE TITLE
Intentional? Species loci doesn't transfer over reagents or potency/

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#2506]
Like in the title and using the bioballistic machine, if you bombard a plant with the species loci of another on original baycode and in addition to fruiting data, it transfers over reagent data from the centrifuge'd plant origin and also transfers potency (Though I think it might get halved sometimes).

On vg, however, it only transfers over fruiting data.

I also know that the harvestable mutation is supposed to be transferred over, I think also on the species loci, but it doesn't on vg.

An in use example:
On bay: If you had a chili plant you can stuff it into the centrifuge and find the species loci and put it onto a disk. You can then say, take wheat and put it into the bioballistic along with the chili plant disk. Machine Gunning the wheat plant with the chili genome will result in a wheat plant that is: reharvestable, creates both wheat and chili fruits, has 10-20 potency, and produces capsaicin in addition to nutriment.

On vg: If you did the same thing, you'd just end up with a non-reharvestable wheat plant with base wheat potency that produced chilis with no capsaicin.

You would have to do it the other way around on VG; bombard a chili plant with wheat, and the only thing that would transfer over is the wheat fruiting.

Example 2: On bay you can combine multitudes of plants and each plant adds its reagent data to the result. Thus you can have a deathberry bush that produced cyanide and pacid in addition to deathberry stuff by crossing it with cyanide apple and deathnettle.

You could also mutate a plant's potency way up, and apply that plant to other varieties to transfer the potency over. The only downside is the plant would also produce the fruits and reagents of both plants.

ON vg, however, only the base plant counts for reagents and potency and reharvestability.

**Comment by 9600bauds** [comment]
Pretty important stuff right here - right now xenobiology is only worthwhile for altering the production times of plants. It's sad that you can't combine medicinal plants for alternative treatments, and also sad that there is literally no use to be had out of mutating the products of single-harvest plants with important chemicals such as wheat or liberty caps.

**Comment by Midaychi** [comment]
Semi-unrelatedly, for some reason synaptizine was made to poison people on a pretty decent chance per run of the chemical, even if its in minescule amounts. I guess it could be some sort of slapdash and half-assed attempt at balancing the anti-stun drug?
Whatever the reason is is, it's turned ambrosia deus into a deadly plant, so that should probably be removed from the list of reagents deus has because the point of the plant is to be a beneficial mutant and weed analogue, and it gets really awkward when your druggy palls start keeling over dead from it.

**Comment by 9600bauds** [comment]
Pomf, blessed be his name, has worked his hands on this issue. Both this and #2028 can be considered fixed.

**Comment by ComicIronic** [comment]
Apparently fixed, reopen if not.
