### ISSUE TITLE
Helmets make you bald again when you wear them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25068]
(WEB REPORT BY: bomberharris REMOTE: 206.221.180.138:7777)
# Revision
efcdb7466658eb94f2e3b734763c1d8775789af4

# Description
Helmets have taken a page of of Ushanka's book and now remove your hair when wearing, probably from the recent change that fixed dual wielding helmets.

# Steps to Reproduce
Put on sec helmet, or any helmet probably.

# What you Expected
My Johnny Bravo tier hair to come out of my helmet like a ray of sunshine parting the darkness

# What Actually Happened
Bald :(

**Comment by ghost** [comment]
WHY WONT YOU DIE

**Comment by ShiftyRail** [comment]
My code worked perfectly

**Comment by jknpj** [comment]
I wouldn't call dual-wielding helmets perfection

**Comment by ghost** [comment]
> 
> 
> I wouldn't call dual-wielding helmets perfection

Based
