### ISSUE TITLE
[Defficiency] [Mapping] Add station bounced radios to engineering

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2507]
Engineers need station bounced radios when tcomms fucks up.  Any of these 3 spots would be great to add four station bounced radios.  

"Go ask cargo to use the autolathe" or "Ask a mechanic to build an autolathe" is all well and fine when things aren't bad but generally when people rush for a station bounced radio, it's because things are already bad and they need comms immediately.  And in that scenario, like the one yesterday that left me combing nearby maint for a radio to snag, isn't one where you have time to cross half the station, ask for a radio, hope someones there, wait for it to print, then get to work. It's a no brainer, add them to engineering please.

![image](https://cloud.githubusercontent.com/assets/8550416/5709984/7b2619c6-9a6c-11e4-83ed-57aefb4d7a8a.png)

**Comment by Gontranos** [comment]
This. Engineering should at least be equipped with four Radio just like on Box.

**Comment by Duny-** [comment]
Will add four radios next patch.
