### ISSUE TITLE
Eggs don't break into beakers anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25070]
(WEB REPORT BY: spcmn REMOTE: 206.221.180.138:7777)
# Revision
efcdb7466658eb94f2e3b734763c1d8775789af4

# Description
Eggs won't break into beakers anymore
# Steps to Reproduce
Tap egg against empty beaker to break out yolk and stuff
# What you Expected
To have egg go into beaker
# What Actually Happened
Egg did not break or interact with beaker at all.

**Comment by Zth--** [comment]
Can someone confirm we had this feature? it sounds like you're mixing up servers

**Comment by SirSkeleto** [comment]
i dont think this has ever been a feature

**Comment by Zth--** [comment]
I'll just close this, it doesn't even have sense as a feature request
