### ISSUE TITLE
Veganism & Noir

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25076]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
5f8636e9dd71c0e00fc74f6d9555dd769fd0b644

# Description
I think Veganism and Noir always share a block? Every time I get cloned, I come out with the Noir "ability" and veganism "disability". It's a bit weird.

# Steps to Reproduce
Be Vegan
Die
Get cloned
Everything is black and white.

# What you Expected
Not to be colourblind every time I get cloned

# What Actually Happened
Depression

**Comment by DeityLink** [comment]
Getting cloned gives you a random disability. Looks like you were just unlucky.
