### ISSUE TITLE
Plump Helmet's Description

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25074]
(WEB REPORT BY: pump321 REMOTE: 206.221.180.138:7777)
# Revision
5f8636e9dd71c0e00fc74f6d9555dd769fd0b644

# Description
"Plumus Hellmus: Plump, soft and s-so inviting~"
instead of the original description, what the hell
# Steps to Reproduce
Examine a plump helmet
# What you Expected
The original description
# What Actually Happened
Some really gay shit.

**Comment by Zth--** [comment]
What is "the original description"? This description exists since (at least) Aug 18, 2012

https://github.com/vgstation-coders/vgstation13/commit/e476b418be4b7e16f86897efb85e71b7a26324f1

**Comment by Irradiation** [comment]
Looking at gitblame, what Zth said. It's been 7 years.
