### ISSUE TITLE
Lights are bleeding through walls more than usual

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#25073]
What did (You) do
![wtf](https://user-images.githubusercontent.com/25846834/69017489-69daec00-0975-11ea-9241-01760022b332.png)

**Comment by ghost** [comment]
can you post a screenshot including the area it's leaking from?

**Comment by Kharkov72** [comment]
![Untitled](https://user-images.githubusercontent.com/25846834/69020530-d3152c00-0982-11ea-8fba-4bc470f5b477.png)

**Comment by ghost** [comment]
I may or may not investigate this depending on how much I want to learn about the lighting system

**Comment by Exxion** [comment]
Anyone know when this started?
