### ISSUE TITLE
Space Pods unconstructable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25093]
(WEB REPORT BY: robinbert REMOTE: 206.221.180.138:7777)
# Revision
9bb3ac297ca7e9031422f50d7279d705d78440e8

# Description
The step to wire the space pods is simply broken. It will not let you wire it at all.
# Steps to Reproduce
Build a pod, use the rods, try and fail to wire the shuttle.
# What you Expected
A functioning space pod
# What Actually Happened
No functioning space pod

**Comment by Zth--** [comment]
Duplicate of #25078
I'll leave it open temporarily for visibility
