### ISSUE TITLE
Disconnecting Mid-Absorbtion as Changeling castrates you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25091]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
18afa41ebae62f176ed095e979b19df58d63e6d8

# Description
Disconnecting while in the process of absorbing someone will cancel out the absorbtion, but will also give a failing message when trying to absorb anyone else: https://puu.sh/EGe7h/d54c6ecaa2.png
I've tried to change my DNA, turn into monkey form and turn back. The only way the problem got fixed was via putting me into a new body.
# Steps to Reproduce
1. Play changeling
2. Start absorbing someone
3. Disconnect while in midst of the process
# What you Expected
Absorbtion cancels out, have to begin from anew when reconnected
# What Actually Happened
Absorbtion cancels out, but you are unable to begin any new absorbtions

**Comment by Killette2** [comment]
You are now sterile!

**Comment by Kharkov72** [comment]
feature
