### ISSUE TITLE
Purple crayons are incapable of coloring stuff.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25102]
(WEB REPORT BY: potatomancake REMOTE: 206.221.180.138:7777)
# Revision
a7ab877f80e501efc4e4d07471cdd98625ef80ca

# Description
Washing machine reactions for purple crayons no longer work since https://github.com/vgstation-coders/vgstation13/pull/24706 .

Purple crayons got renamed to violet crayons, and since it looks like the washing machine looks at colourName on crayons to figure out what it should be colored, it's looking for violet versions of things instead of purple and breaking. Also tested it on coloring eggs, which calls the same line.

The irony is palpable.
# Steps to Reproduce
Put the crayon formerly known as purple in the wash with my gloves
# What you Expected
Purple gloves
# What Actually Happened
Machine ate my crayon and I still have yellow gloves

**Comment by ghost** [comment]
god damn it I changed this to fix a discrepancy between crayon names and paint names, easiest way to fix it would be to choose one or the other and rename ALL items that reference the color to match

**Comment by tuypo1** [comment]
Just naming them purple is better, keep things simple

**Comment by ghost** [comment]
You know I looked to see how many things come up as violet rather than purple. One is the paint thing. The other is an artifact thing where colours like indigo are used. Eight instances of violet in the repository. Over a hundred of purple.
