### ISSUE TITLE
An AI on the emergency shuttle cannot see the shuttle until it hits the AI core button

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25108]
(WEB REPORT BY: bobthomas REMOTE: 206.221.180.138:7777)
# Revision
c548359e0d10d3bc33caaf6fb8ce90e803ac478a

# Description
title
# Steps to Reproduce
be ai, get moved on emergency shuttle, try to see
# What you Expected
to see
# What Actually Happened
you see static until you hit the AI core button

**Comment by jknpj** [comment]
The shuttle literally has no cameras

**Comment by Intigracy** [comment]
The AI core is able to see around itself without cameras, isn't it.

Just like you can see when you're intellicarded.

**Comment by jknpj** [comment]
Yes but not in eyemode. When he used the "come back to core" he went from eyemob to AI, so he could see around just fine.

**Comment by SonixApache** [comment]
why doesn't the core mob just act like a fuggen camera

**Comment by west3436** [comment]
Feature
