### ISSUE TITLE
AI Private is bugged

### ISSUE THREAD

**Issue by brndd** [d3athrow/vgstation13#25100]
After the dynamic radio frequency thing, the `:p` code for AI private no longer works. Additionally, the AI Private intercoms in the upload and core start on the Common channel instead of AI Private.

**Comment by Kharkov72** [comment]
the private intercomms in interrogation are like this too

**Comment by nervere** [comment]
The Common channel thing was fixed in #31392.
As for AI private not working, it seems that's no longer an issue as I can't replicate it.
