### ISSUE TITLE
DAB Block Injector doesnt seem to work.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25106]
(WEB REPORT BY: theula123 REMOTE: 206.221.180.138:7777)
# Revision
a7ab877f80e501efc4e4d07471cdd98625ef80ca

# Description

now for three rounds straight i went to genetics and asked to be monkified we tried everything from injected me with a S.E 58 BLOCK injector, to doing it manually. and just pulsing me.

# Steps to Reproduce

Print out DAB 58 block injector,
inject oneself.
wont turn into a monkey.

# What you Expected

to turn myself into a monkey.

# What Actually Happened

i am just a human with the DAB Genome on block 58

**Comment by jknpj** [comment]
>DAB

It's DAC, not DAB. But monkeying gene should activate after 800, not DAC
