### ISSUE TITLE
[Deff] Telecomms next to supermatter at roundstart

### ISSUE THREAD

**Issue by Pastamancer** [d3athrow/vgstation13#2511]
This problem doesn't initially sound like a problem until you realize that every round on dunystation ends up with the Supermatter exploding. Assmad boxbabies will gladly take any opportunity to fuck over the station when they get antag on Deff. Even worse, engineers setting up the engine half of the time just fuck around in the bar, malf AIs wanted telecomms blown up anyways, etc, etc. I have two proposed locations to put telecoms, making it still easy to sabotage telecoms, but at least not forcing the issue every round.
![ss 2015-01-12 at 03 37 03](https://cloud.githubusercontent.com/assets/10264468/5713696/c6834d6a-9a73-11e4-981a-b1817b4a0877.png)
I don't like this one as much, because it's a fun little area as-is. But there's a lot of space to spare around here, It's close to science and medbay, so it isn't exactly in the middle of nowhere. This is still easier to fuck with than Box.
![ss 2015-01-12 at 03 37 28](https://cloud.githubusercontent.com/assets/10264468/5713762/8ce46db8-9a74-11e4-9272-4a1426749174.png)
I like this better. Swap the MoMMI nest with Telecomms and vice-versa. Those crab-looking assholes will love this, they always want to set up the supermatter anyways. I think this change helps both the telecomms issue and puts MoMMIs closer to the engines they're probably going to spend the roundstart setting up, too.

**Comment by Probe1** [comment]
I think telecomms being next to the AME is the bigger problem since that's much easier to sabotage without anyone noticing, and still completely shits up tcomms.  Same diff though.

**Comment by Gontranos** [comment]
When the Supermatter blows, it's both takes down the Ame, Tcomm, and the old singulo room. And If someone did the Singulo In that same room, the explosion actually gets rid of the top containment field and leaves the Singulo rampaging the Station. Just seeing the shard explode makes it a game over for Engineering as all that Is left Is the solars to power the station and no T-Comm unless If there's hope with Cargo. And even then, it's takes a long while to set shit right again.

T-Comm at one of those position would just be fine and dandy,

**Comment by Probe1** [comment]
that's the same deal as box.  If the SME blows there's a good chance SE singlo containment blows with it and the AME rooms fuckin *gone*.  If the AME blows on Box, singlo containment is definitely compromised and SME chamber is possibly breached.  

The key difference is tcomms does not automatically get shit on when something blows on meatclub or grorious infallible Box Station.

**Comment by Duny-** [comment]
I don't plan on moving tcomms into an obscure abandoned part of the station but I'm planning on rearranging engineering to make sure tcomms can't be too affected/affected at all by baby-supermatter exploding. Baby's first engine aka the AME should still endanger tcomms, but I want the cooling room to be out of harm's way because that shit is hard as fuck to rebuild compared to tcomms itself as someone pointed out.

**Comment by Duny-** [comment]
I'd like your thoughts on this https://github.com/d3athrow/vgstation13/pull/3068
