### ISSUE TITLE
Player controlled mobs breaking.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2512]
Whenever you play as a player controlled mob without a knockdown sprite, two I've experienced with this is being a slime and being a shade, and you get knocked down by zas airflow, you break. You can move while 'knocked down' but you can never use your ability to attack people or break windows ever again no matter how long you wait, making you for the most part useless. If this applies to constructs this can be gamebreaking for a cult and I'm not sure what other mobs this may apply to.

**Comment by SkowronX** [comment]
For some mobs it "knocks them down" but there is no sprite for it. What sort of mobs are you talking about? Cult constructs?

**Comment by Killette2** [comment]
Player controlled slimes and shades are ones I've personally experienced this bug with. I have not had it happen to me yet as a construct so I wouldn't know. I had to ahelp about not being able to break windows anymore or glomp people as an adult slime but there was no idea how to fix it.

**Comment by ririchiyo** [comment]
I think this is an old bug.

**Comment by d3athrow** [comment]
Knocked down aka weakened. Happened to constructs.

**Comment by ririchiyo** [comment]
It was fixed in #1464 if anyone wanted to look into it.
