### ISSUE TITLE
[Deffiency] Supermatter change request

### ISSUE THREAD

**Issue by Gontranos** [d3athrow/vgstation13#2514]
The setup of Deffiency's Supermatter Is a poor one. Only six Rad Collector, with four of them stacked In Secure Storage, which can get swooped by those making King Singulo. Barely enough Emitters for it. No real piping work done at the start and you need to get rid of enforced walls to make a cooling loop.

The supermatter might be the main power source of the station, but the way she start makes it a bigger pain In the ass to set up and Is prone to blow at some point. It's should start like Box's setup http://ss13.nexisonline.net/wiki/Supermatter Instead of barely having anything for it In the room.

**Comment by Probe1** [comment]
I've given this some thought before and flipping the entire SME chamber horizontally would be interesting and easier.  If the pipes were all on the east side instead of the left side it'd be cool.  there'd still be one rwall you'd have to get through but at least its close and it makes a little sense.

**Comment by Duny-** [comment]
>Only six Rad Collector, with four of them stacked In Secure Storage, which can get swooped by those making King Singulo.
Cargo exists if you need more.
>Barely enough Emitters for it.
One emitter is plenty and is what the base setup can handle, but you can still get more the same way as rad collectors, or in the storages (singulo storage has four).
>No real piping work done at the start and you need to get rid of enforced walls to make a cooling loop.
The piping work is shit, but done completely at the start. All you need is canisters and you can use supermatter the way it was meant to be used (non-continuous emitter fire). You're free to change the piping to improve the output significantly. You can make a cooling loop without going to space, if you want to make a space cooling loop you can use the external airlock made especially for it.

I'll see what I can do about the pipes being too far from space to your tastes when I rearrange engineering.

**Comment by Duny-** [comment]
I'd like your thoughts on this https://github.com/d3athrow/vgstation13/pull/3068
