### ISSUE TITLE
Holomen cannot disarm people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25143]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
a10dd083103e00f321618fc1174ee97a44e03a6b

# Description

Testing with holomen shows they cannot disarm people and when shoved become stunned for a period without any horizontal sprite
# Steps to Reproduce

Join as holoperson (literally nobody does) disarm vox
# What you Expected

vox go horizontal
# What Actually Happened

No horizontal, when shoved just become static

**Comment by jknpj** [comment]
Holomen aren't supposed to harm, or disarm people

**Comment by SGuivenne** [comment]
disarm isn't harm though and it effectively renders them unable to play basketball.   You might as well remove basketball if holomen aren't allowed to disarm.
