### ISSUE TITLE
snaxi captains locker contains HoS Ushanka

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25164]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
dc4c5ff0152cf8778ee6714818dad1bb564bc051

# Description
captain has the HoS hat thingie for some reason 
# Steps to Reproduce

# What you Expected

# What Actually Happened
capcurity

**Comment by ghost** [comment]
This is intentional but obviously it'd be better if he got a captain's ushanka
