### ISSUE TITLE
Snaxi Paramedic carts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25167]
(WEB REPORT BY: tobiaskunst REMOTE: 206.221.180.138:7777)
# Revision
dc4c5ff0152cf8778ee6714818dad1bb564bc051

# Description
Snaxi paramedic carts are unable to load anything, unlike their cargo counterparts.

# Steps to Reproduce
1. Have cart + random object.
2. Drag random object on cart.

# What you Expected
Object moves on the cart and stays on it until unbuckled.

# What Actually Happened
Nothing. Nothing at all.

**Comment by SonixApache** [comment]
issue is that they're just `cart` unlike the `cart/cargo` subtype that can actually load things

**Comment by Zth--** [comment]
But they're `cart/cargo`
`/obj/machinery/cart/cargo/toboggan`

Also couldn't reproduce

**Comment by SonixApache** [comment]
The paramedic spawns with a `/obj/machinery/cart`
![proofs](https://user-images.githubusercontent.com/8468269/69497354-3ef41900-0edc-11ea-8911-63c4f137619f.png)
