### ISSUE TITLE
Ammolathe doesnt display gold requirment rocket launcher

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25169]
(WEB REPORT BY: landshark4444 REMOTE: 206.221.180.138:7777)
# Revision
dc4c5ff0152cf8778ee6714818dad1bb564bc051

# Description
The auto lathe doesnt display the 6000 gold requirment for the rocket launcher only the plastic iron and glass requirment
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
Please close #25170 

And for reference the requirement shows, it just overflows from the button. Either a material should be bopped or the UI needs fixing

![image](https://user-images.githubusercontent.com/6137403/69491863-6676c180-0e9b-11ea-9995-d4e802419804.png)

**Comment by calzilla1** [comment]
Up the Iron cost and remove the gold
Adding shemaghs and AK-74s for ISIS-curity when
