### ISSUE TITLE
Gysers are the wrong color

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#25174]
snowstation not beachstation okay
![Untitled](https://user-images.githubusercontent.com/25846834/69499707-fda33f80-0ec2-11ea-94dc-e8f9a3458534.png)

**Comment by Zth--** [comment]
why does everyone spell geyser wrong

**Comment by RealestEstate** [comment]
imagine not being esl

**Comment by Kharkov72** [comment]
because I'm dumb @Zth--

**Comment by N3X15** [comment]
yellow snow

**Comment by Kurfursten** [comment]
They were originally intended for a hypothetical sandy "melted" area of snaxi but I guess somebody made them spawn everywhere

**Comment by ShiftyRail** [comment]
I did that, yeah. Wasn't aware that they were only intended for this area of snowmap.

**Comment by Kurfursten** [comment]
It's alright, I'll do something about it on Friday since I'm less busy over Thanksgiving
