### ISSUE TITLE
Items in hand can't be examined

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25197]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
fcfe9d7e8cad091216825ad6bbab61a8815b6fc2

# Description
Examining Stuff in hands doesn't work right no prompt comes up
# Steps to Reproduce
Just grab something and examine it while holding it
# What you Expected
a description
# What Actually Happened
nothing

**Comment by Goldsteel** [comment]
Tested this locally. Right click examine doesn't work. Shift click examine does. Right click still works if you're not holding it.

**Comment by Exxion** [comment]
lol
