### ISSUE TITLE
Horns from genetic defect doesn't dissapear after ryetalin intake

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25209]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
c46ce747fbe3785ce1128275a07024a0821e08a9

# Steps to Reproduce
1. Get the horns defect
2. Sip ryetalin
# What you Expected
No horns
# What Actually Happened
Horns

Why do we still have this homestuck reference anyways? The horns also goes through items, which looks like shit.

**Comment by RealestEstate** [comment]
pretty sure it's just a leftover from bay from before we forked. There's no reason someone couldn't make a new sprite for the horns or even add them some functionality like a headbutt attack.

**Comment by Exxion** [comment]
It dates back to before Bay, but yes, it's just a relic

**Comment by PJB3005** [comment]
Fixed by #25578
