### ISSUE TITLE
Remove screwed bundle

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25204]
Remove screwed bundle

**Comment by boy2mantwicethefam** [comment]
I was about to make a PR before I found out it's just bombs and bombs are based, I thought it was the balloon bundle

**Comment by Kharkov72** [comment]
DUDE

**Comment by Irradiation** [comment]
HE DID IT
HE SAID THE "R" WORD

**Comment by SneakyCanuck** [comment]
Replace all bundles with the screwed bundle
