### ISSUE TITLE
The new VOX voice is really bad

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25207]
revert when

**Comment by SonixApache** [comment]
i hate the britbong vox so much

**Comment by BomberBro** [comment]
It really is a bad voice, it shouldn't be the default at the very least

**Comment by jknpj** [comment]
It feels really weird to not hear female vox at roundstart

**Comment by N3X15** [comment]
Oh shit I thought I set it back to femvox before pushing

Just got home, will fix.
