### ISSUE TITLE
Ui Obstruction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25219]
(WEB REPORT BY: salmonistasty REMOTE: 206.221.180.138:7777)
# Revision
83a076d347bb8adc991340c83e58127c226cc7b9

# Description

After joining the round with cult on the last but not least chapter, my Ui got obstructed with cult ui (while not being cultist) in the place of drag/drop and throw icons. Cult icons were the tatoo circle and chapter circle.

# Steps to Reproduce

Join game while cult is in "blood stones" chapter

# What you Expected

ui not being fucked up

# What Actually Happened

Ui obstruction

**Comment by DeityLink** [comment]
I'm ready to bet this had something to do with pooling, so it shouldn't be able to occur anymore.
