### ISSUE TITLE
Bluespace Matterbin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25215]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
94667bc2531bac737b465c26cc370d15a831fb6e

# Description
Materials don't share on all bins
# Steps to Reproduce
Put bluespace matterbin inside General Fab or Flatpack
# What you Expected
To be able to use materials from other machines with bluespace matterbins
# What Actually Happened
No access to said materials

**Comment by SonixApache** [comment]
[needs more testing] 
this report doesn't really help much

**Comment by tuypo1** [comment]
I'm pretty sure it's meant to be a feature request
