### ISSUE TITLE
Wolf Attack Logs Are Gunked

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#25222]
ADMIN LOG: NAME (CKEY) ordered **a wolf a wolf** to attack Unknown **with WOLFNAME** (INTENT: HELP). 

Instead it should say 
>ADMIN LOG: NAME (CKEY) ordered a wolf (WOLFNAME) to attack Unknown.

**Comment by Goldsteel** [comment]
I'll take a look.

**Comment by Goldsteel** [comment]
ADMIN LOG: Grug Unga (goldsteel) ordered a wolf to attack Test Dummy with Bob (INTENT: HELP). (JMP)

Looks like it was just a copying mistake.

**Comment by Kurfursten** [comment]
Strange, it was definitely happening. That's a pasted line. Maybe not in the logs but in the actual adminwarn it sends?

**Comment by Goldsteel** [comment]
I corrected the code. It was 'a wolf a wolf' before.
