### ISSUE TITLE
Vox Raiders is still broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25220]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
-It still only spawns one vox, even with multiple sign-ups
-The vox spawns naked now, something it did not do before
-Items on the vox shuttle spawn outside of their lockers
-The vox raider vending machine has no items in store, even after a raider coin was put in

Tested after #25199 was merged obviously
Please fix, Vox Raiders was the second best gamemode after Revolution

**Comment by ShiftyRail** [comment]
```
-The vox spawns naked now, something it did not do before
-Items on the vox shuttle spawn outside of their lockers
-The vox raider vending machine has no items in store, even after a raider coin was put in
```
Those aren't me

```
-It still only spawns one vox, even with multiple sign-ups
```
This could be me, I'll check further
