### ISSUE TITLE
Nothing tells what the nuke ops loadouts contain

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25226]
There's nothing in-game, there's nothing on the wiki.
The only way one can know about them is by playing or reading #23246

**Comment by SonixApache** [comment]
Bandaided.
Updated the wiki page a bit, jotted down the loadouts, updated some other stuff.
Wiki page still needs a bunch of updates, and the loadout system should *very much* be changed ingame to make it easier for ops to pick what they actually want.

**Comment by Eneocho** [comment]
seems to be fixed now
