### ISSUE TITLE
security camera control buttons disappearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25232]
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
fe2b27b635d9b164eee8b19e436e7ccc7db1c46a

I think it's as simple as they just disappear a few seconds after you peer into a security console, making it impossible to switch views and yaddayadda

**Comment by RealestEstate** [comment]
I think its safe to close this issue now
