### ISSUE TITLE
Phylactery & Language

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25237]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
7ef8e0164f09da2e119206bc7698ed1734d3c7cc

# Description
Upon revival through a phylactery, you seem to forget any additional languages you know. In my case it was Cult since I got the soulstone belt. This lead to me not being able to understand my construct
# Steps to Reproduce
Buy phylactery and bind it to you
Buy soulstone belt and learn the langauge
Die and revive at a phylactery
# What you Expected
Being able to understand my constructs even after I revive 
# What Actually Happened
No longer able to communicate with my contructs

**Comment by DeityLink** [comment]
constructs can use :1 to speak human now, and they should have it as their default language even unless they're made by cultists.
