### ISSUE TITLE
Bridge Maintenance Access on Snaxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25231]
(WEB REPORT BY: smokepole REMOTE: 206.221.180.138:7777)
# Revision
fe2b27b635d9b164eee8b19e436e7ccc7db1c46a

# Description
Bridge maintenance opened for me, as an engineer, allowing me access to the bridge foyer area. As far as I know, the Engineer does not come standard with Bridge access.
# Steps to Reproduce
open up Bridge Maintenance on Snaxi as Station Engineer
# What you Expected
I expected not to have access to bridge via maintenance
# What Actually Happened
I walked into the bridge

**Comment by Kurfursten** [comment]
also fixed in docking patch
