### ISSUE TITLE
Newscaster giving "improper argument" error when trying to access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25234]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
b74253e9f8ff6ed5387ba4f21147475cf1e822b0

# Description
Started a round ago where I made a post to the newscaster fine, then when I tried to make another post Dreamseeker gave me a "encountered an improper argument" error. This caused my game to freeze up and me having to restart. Trying to so much as access the newscaster after this would also cause the same error to occur. Next round, I tried to make a newscaster post and I couldn't even get one in before the same error occured. This is only affecting me because during this round multiple people had been posting repeatedly to the newscaster.
# Steps to Reproduce
I have no clue.
# What you Expected
Being able to post a picture of the mime with no mask on to a Live PD channel
# What Actually Happened
Game freezing uh oh

**Comment by cloutcode** [comment]
i figured out what the problem was the problem was that i had the japanese locale on to play my horny japanese games case closed
