### ISSUE TITLE
NTSL Frequency Variables No Longer Accurate

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25241]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
151ae5d4b7d14c208b2a07631b270c5787fae243

# Description
Calling frequency variables in NTSL such as $medical or $command no longer works since departmental frequencies are random.

# Steps to Reproduce
Try running this:
if($freq == $security)
{
broadcast("[SEC] " + $content, $common, $source, $job);
}

# What you Expected
To spy on security.

# What Actually Happened
I did not spy on security.

**Comment by west3436** [comment]
Can't reproduce anymore, please close @Kurfursten
