### ISSUE TITLE
[Box/General] The Arrivals Hallway never seems to depressurize properly

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#2524]
Even when a huge hole is made in the window bay or the hull, the Arrival Hallway just doesn't seem to depressurize. This even goes as far as having individual, isolated and broken plating tiles having a perfect 101.3 kPa in the middle of a full hull breach

This might be a more widespread problem, although I've seen it happen the most often in the Arrivals Hallway (other rooms like Escape seems to depressurize properly)

This doesn't seem to affect overpressure and "normal" loss of pressure via area transfer. However, I have also witnessed fire being randomly blocked by invisible walls at around the level of the small Arrivals Lobby (front of the Arrivals Security Office)

**Comment by clusterfack** [comment]
What mode was ZAS on?

**Comment by dylanstrategie** [comment]
I didn't check, but I'm going to guess Normal ZAS

**Comment by clusterfack** [comment]
Notabug

**Comment by ComicIronic** [comment]
So I tried this on local, and it depressurized fine under an admin bomb.
Given the info on ZAS settings, I'll call this closed.
