### ISSUE TITLE
sec helmet cuts hair

### ISSUE THREAD

**Issue by 9percents** [d3athrow/vgstation13#25257]
#### Description of issue

sec helmet, a.k.a. Tactical Helmet cuts off hair when worn

#### Difference between expected and actual behavior

Hair should've popped back after taking the helmet off

#### Steps to reproduce

Have a stupid big haircut
Put on a sec helmet
Take off a sec helmet

#### Specific information for locating

I blame the MASKHEADHAIR flag

**Comment by Zth--** [comment]
Related to #25252

**Comment by ShiftyRail** [comment]
It keeps the "cropped" hair cut even after being worn.
