### ISSUE TITLE
New UI for Cyborgs and MoMMIs

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#2525]
Old Stun arm bug is back thanks to new UI for mommis.(Need test this on the other emag gear cyborgs get)

Stun arm does not pop up in the new UI list got use old one trying to store it makes the MoMMI drop it.

New UI bugs out with the MoMMI jet-pack pops up in the new UI can't use it at all.

**Comment by clusterfack** [comment]
Also storing an item doesn't make it reappear in the list. As well lots of items seemed to disappear (imagewise) at random points, I'm not sure when/why.

**Comment by AutismSpider** [comment]
Using the Hot-key for fast drop/store makes that happen (home key)

Ui fails to update when its used 

this happens for both mommis and cyborgs

**Comment by Probe1** [comment]
>Also storing an item doesn't make it reappear in the list. As well lots of items seemed to disappear (imagewise) at random points, I'm not sure when/why.

This is easily replicated.  Hit q to drop (store in MoMMIs case) an item and it doesn't reappear until you reopen the storage.
