### ISSUE TITLE
Hoods hide facial hair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25252]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
5b8b2c2d037cfa432b3f7eaedfe4773cf577fd5f

# Description
Several hoods (example: Chaplain's Hood, Winter coat hood) hide facial hair when put on. This makes it hard to look stylish.

Images:
https://puu.sh/EKtXA/0cb295381d.png
https://puu.sh/EKtXD/d0a9c001e3.png
https://puu.sh/EKtY2/aeb7aec35f.png
https://puu.sh/EKtY7/52a00e4f85.png

**Comment by Lokiamis** [comment]
I've seen this issue be fixed and then reappear at least a dozen times in the last few years. How does it keep happening?
