### ISSUE TITLE
Emitter beams are fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25276]
(WEB REPORT BY: reind REMOTE: 206.221.180.138:7777)
# Revision
fd021df314ea9f8103248ad16d048a083c526727

# Description
Emitter beams do not pulse the shard when the beam is on a tile with a window pane.
# Steps to Reproduce
Will post pictures after round end.

# What you Expected

# What Actually Happened

**Comment by ReindH** [comment]
![emitter bug](https://user-images.githubusercontent.com/23237185/70017701-0b705900-1584-11ea-8301-e5fe68f25f76.png)

**Comment by Exxion** [comment]
God I love beams
