### ISSUE TITLE
Creating rods while in cyborg charger and hands full drops rods into charger contents

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#2528]
Something simple minor and silly.

How to cause: Be in cyborg charger as mommi and holding a stack of metal. Attempt to create rods but less than maximum for the amount of metal you're holding. The rods will be placed inside of the contents of the charger instead of dropped outside.

**Comment by ComicIronic** [comment]
This is a good reason for either restricting crafting to spawning using get_turf(), or preventing crafting in places where the mob's loc is not a turf.

**Comment by gbasood** [comment]
Sure, you could restrict it based on if the mob's loc is a turf, but then you wouldn't be able to craft while in lockers like a silly person.
