### ISSUE TITLE
Please, for the love of god, add mugs to the service fabricator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25286]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
c2f050167eb75159cce36731bad084fae379ef56

# Description

Jesus christ why isnt this a thing.

**Comment by brndd** [comment]
The cyborg one does mugs already I'm pretty sure.

**Comment by Kurfursten** [comment]
More desperate version of https://github.com/vgstation-coders/vgstation13/issues/22498
