### ISSUE TITLE
Hydroponics access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25281]
(WEB REPORT BY: ribeira REMOTE: 206.221.180.138:7777)
# Revision
f3743b051cb20f8727e54e522f0c9f6c113cf02c
Hydro access does not work, hydro doors are opened by kitchen access
# Description
Hydroponics main doors are opened by kitchen access instead of hydro access
# Steps to Reproduce
get an assistant, give him hydro access and try to open main doors, then give him kitchen access and watch the doors open
# What you Expected
I expected hydro access to give access to hydro
# What Actually Happened
it did not give access to hydro

**Comment by Kurfursten** [comment]
Probably Box based on time of report

**Comment by jknpj** [comment]
betting 10 pomfcoins on being a mapping issue

**Comment by Lunstra** [comment]
I am 90% sure I remember checking those doors with VV when I was still a min and unlike basically every other door on the station their access is set to require ALL instead of require ONE, so they need the full gamut of service access to open

**Comment by kernikov** [comment]
@DeityLink No longer an issue (on box).
