### ISSUE TITLE
securitrons can infinitely stun through windoors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25298]
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
07e4736e0cbd599f114588399837a8d52a53962c

# Description
securitrons can infinitely stun through windoors and can't actually put cuffs on so you're literally CC'd forever
# Steps to Reproduce
aggro a securitron
be on the opposite side of a closed windoor from it
never move again in your life
# What you Expected
them to not be able to hit through objects
# What Actually Happened
permastun

**Comment by Blithering** [comment]
God made tomorrow for the crooks we don't handcuff today.

**Comment by Exxion** [comment]
Duplicate of #20446

**Comment by FudgePucker** [comment]
Damn it beepsky, your a lose cannon, but your still the best officer on the force.
