### ISSUE TITLE
Spelling Anomaly in Snow Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25326]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
c052e422c7311c2a8cbddf0dec1fd6afcddac7a2

# Description
"""accoustic panel"""
# Steps to Reproduce
>stand in radstorm
>drink chaplains """holy water"""
>no 10u Alkysine pill
>spell it like that
# What you Expected
acoustic
# What Actually Happened
acccccoustic

**Comment by Kurfursten** [comment]
dupe of #25221
