### ISSUE TITLE
Horizon SME vents

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25329]
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
c052e422c7311c2a8cbddf0dec1fd6afcddac7a2

# Description
They aren't linked to the coolant control.
# Steps to Reproduce
Try to turn on the SME.
# What you Expected
Them to be linked to the coolant control console.
# What Actually Happened
They are set to 144.1 while the console is set to 144.3. Also, the tag for each vent is 'coolant_in' and 'coolant_out' while the console checks for 'SM_coolant_in' and 'SM_coolant_out' respectively.

**Comment by ghost** [comment]
It shouldn't be reliant on everyone else to alpha test this map for you, not when it is in current rotation.
