### ISSUE TITLE
Snowmap: Winter coat storage access requirements are too high on the south sector.

### ISSUE THREAD

**Issue by DrSnips** [d3athrow/vgstation13#25327]
[snowmap]
#### Description of issue
The winter coat storage on the south station section are behind an engineering access airlock whle others are behind open access ones.
A sec officer arrested me for 3 minutes for rotating the windows to get a coat. Either the map needs to be changed or space law does because this made me sad.

**Comment by Kurfursten** [comment]
Dylannn
