### ISSUE TITLE
Vehicles use the same unbuckling alarm as chairs

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25345]
So it says you can't move, but you clearly can 
![image](https://user-images.githubusercontent.com/6307265/70408441-77513680-1a48-11ea-80dc-e46f30203274.png)

**Comment by N3X15** [comment]
(Because vehicles are actually chairs)

**Comment by jknpj** [comment]
You technically can't. The vehicle is moving, not you.

**Comment by west3436** [comment]
You are not moving, the vehicle is
