### ISSUE TITLE
Thingstorm Children Still Happen on Snaxi

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#25358]
iirc there might be some arcane old thing with typechecking from a list?

https://github.com/vgstation-coders/vgstation13/blob/3bab4ba6d0c30a37c507aee8a844b15edbf1cd4e/code/modules/events/event_dynamic.dm#L36

For clarity, snaxi bans /datum/event/thing_storm but its children like /datum/event/thing_storm/meaty_gore still happen

**Comment by Kurfursten** [comment]
Oh shit of course, Find looks for an exact match, it's not a typecheck

**Comment by ShiftyRail** [comment]
`is_type_in_list(map.event_blacklist, type)` ?
(order of parameters may not be correct)

**Comment by Kurfursten** [comment]
It's using Find()

**Comment by Exxion** [comment]
Yes, he's suggesting what to do instead

**Comment by Kurfursten** [comment]
I thought on this overnight and I decided it might be best that it searches for exact matches, that seems like it may have been intentional.
