### ISSUE TITLE
[Bug] Cyborgs can no longer hear their departments channel

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2535]
Engineer borgs can't hear engineering, security borgs can't hear security and so on.  So borgs have to choose between hearing common and their department channel.  This is a clusterfuck for players.  

It wasn't added to the changelog so I assume it's a bug.  Fix it please, there's no good way to find out a borgs module without seeing it in person or asking it directly and not knowing you have an engiborg in your department is really shit for teamwork.  Currently borgs will have to change their radio from common to their department frequency, which again causes a mess of issues since they'll hear their department but not common.

**Comment by ComicIronic** [comment]
Closeable after 1263bb6d.
Open again if it wasn't fixed.
