### ISSUE TITLE
You Can Gather Snowballs from Across the Screen (and through windows)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25356]
(WEB REPORT BY: generalveers25 REMOTE: 206.221.180.138:7777)
# Revision
5fa0e354d0dc1f119a770594cd53f12b6230910f

# Description
Stand in one place, ctrl+click snow which is like a screen away from you and snowballs form under your feet - making snowballs from the comfort of your home.

# Steps to Reproduce
Above
# What you Expected
Have to go outside to get snow
# What Actually Happened
Bluespace Snowballs

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by Toxici11i** [comment]
feature

**Comment by juanototo2** [comment]
Feature.
