### ISSUE TITLE
Cells above Hyper don't appear in Exosuit fabricators.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25354]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
5fa0e354d0dc1f119a770594cd53f12b6230910f

# Description
RTG, Ultra and PTG cells don't appear on the exosuit misc list even with the correct research. They are only available from the Protolathe.

**Comment by DeityLink** [comment]
Fixed by #30414
