### ISSUE TITLE
Voice Changers do not work when heard by Holopads

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#2536]
Uncertain it was fixed or something since last time, but it seems when someone wearing a Voice Changer speaks, and you, an AI, hears it through the holopad, it will come out not as the ID they are wearing, but their actual identity.
So a person with "Guy Joe" as their name, with an ID of "John Person" will be heard as "Guy Joe" even with a voice changer equipped.

**Comment by PJB3005** [comment]
Unable to reproduce, might've been fixed.

**Comment by Ephx1** [comment]
Literally months ago. If you can't reproduce it, I suppose I'll close it then.
