### ISSUE TITLE
SNaxi mining door

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25361]
(WEB REPORT BY: westbend REMOTE: 206.221.180.138:7777)
# Revision
1f7eb817292ca1eb1d0316d27fa4613dec4333ee

# Description
Mining EVA airlock on SNaxi spacestation doesnt allow miners access out/in.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by PJB3005** [comment]
Also, on the south station (with the mineral processing machinery), the south airlock on the shuttle doesn't allow cargo through even though it's on the side with the mining related machinery.

**Comment by Kurfursten** [comment]
Both of these accidentally used Theater (46) instead of Mining (48)

Also that same exit door has a double pipe
