### ISSUE TITLE
snaxi: southern station medbay area is named Medbay

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25377]
which means you can't teleport to the actual medbay with the scroll of teleportation because this second area always overrides it
remove snowmap

**Comment by Kurfursten** [comment]
Wrong tag, reee

**Comment by DamianX** [comment]
why is that tag a thing?

**Comment by Kurfursten** [comment]
Dates back to tgstation-snow iirc

**Comment by Exxion** [comment]
It was for the original snowmap project, which does not exist anymore, so the label doesn't really seem necessary
