### ISSUE TITLE
Reagent Threshold in Cryo isn't working as intended

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25373]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
44f8645f31286ecd1c46d701f8284cf4e16808a5

https://github.com/vgstation-coders/vgstation13/pull/25339
Seen nothing but complaints and first-hand accounts of this change causing something to break in the Cryo tubes. The mix is being eaten up but people aren't getting healed properly, and sometimes it just won't transfer the buffer to people. 

Please revert this until it's tested and shown to be working properly.

**Comment by MadmanMartian** [comment]
Got some further details from rabbit, it's not transferring to fresh clones, as they already have chems in them to start with. (Fresh clones get a dose of inaprov, or whatever vox get, so they don't oxydep out during the cloning process)
