### ISSUE TITLE
Antimatter SHOCKS voters by revealing controversial Anti-Power stance!?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25375]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
44f8645f31286ecd1c46d701f8284cf4e16808a5

# Description
I genuinely suspect there is something fucky going on with the Antimatter Engine APC. In this round, there is enough power to fully charge the station three times over and the Antimatter APC refuses to charge.
# Steps to Reproduce
>engineer
>set up power generation/distribution
>look at Antimatter APC
>fucker's orange
>what the fuck
# What you Expected
Energizer. It just keeps on goin'.
# What Actually Happened
The Energizer Bunny is dead.

**Comment by Dacendeth** [comment]
Quit putting all the SMES on auto 200,000.

**Comment by Exxion** [comment]
If it's on auto it shouldn't matter, right? Honestly I haven't really used SMESes since the auto mode was added

**Comment by Dacendeth** [comment]
im not sure about auto 200,000 or just 200,000 on all three, but doing so causes engineering to not charge as it's too busy trying to fill the SMESs.

**Comment by Kurfursten** [comment]
Yes, SMES get prioritized above APCs for charging. Either put in more than the SMES wants or lower the SMES input
