### ISSUE TITLE
Stabby roombas

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25376]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
44f8645f31286ecd1c46d701f8284cf4e16808a5

# Description
Roombas stabbing people even when sprite doesn't show a knife

# Steps to Reproduce
I think that if you destroy an armed roomba and rebuild it with the same items, it keeps the knife while not having it visible

# What you Expected
Not being shanked

# What Actually Happened
The little shit, Cleanbot, stabs you with its attached fork!

**Comment by jknpj** [comment]
Cleantbot code has a few issues, but this isn't one of them.
