### ISSUE TITLE
Spawning a syndie borg lets cyborgs latejoin

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25388]
This may or may not be exactly what happened but it's my best guess.
The following happened:
- Nukies summon a syndie cyborg
- Latejoiner opens the join game menu
- There's a (-1) cyborg entry
- It spawns a cyborg in arrivals when clicked

This is not supposed to happen

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by jknpj** [comment]
how the fuck this happens
