### ISSUE TITLE
Cyro Tubes use chemicals too quickly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25381]
(WEB REPORT BY: subs455 REMOTE: 206.221.180.138:7777)
# Revision
44f8645f31286ecd1c46d701f8284cf4e16808a5

# Description
Cyro Tubes got the big nerf.

r0b0 has singlehandedly made doctor less fun to play. Its already a really fast paced and stressful job during med-high pop rounds with antagonists. I just don't have the patience to play medbay jobs anymore, all because of this nerf.

I suggest 2 fixes, to this absolute crisis.
1] Include a Plsama Beaker inside the chemistry lab of every map, so cyro mixes are easier to produce.
2] Slow down the rate at which Cyro uses chemicals.

like seriously r0b0. Its better to chug the cyromix then it is to use it how it's intended, man. Fucking c*ders.

**Comment by SonixApache** [comment]
*cyro*

**Comment by jknpj** [comment]
with the new threshold it all depends on the reagent's metabolism rate.

**Comment by Tokanova** [comment]
okay but how is anyone supposed to know what the metabolism rates of things are? we are just simple med people we put healy juice in tube and hope it makes the man not dead

**Comment by jknpj** [comment]
>how is anyone supposed to know what the metabolism rates

Add to the wiki? You can also check them in here:

https://github.com/vgstation-coders/vgstation13/blob/a3d7caf0aa7584730755a5192c1dbae100cf21f7/code/modules/reagents/Chemistry-Reagents.dm#L30
