### ISSUE TITLE
All hairstyles display regardless of race

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#2538]
Go to a mirror, set up your facial hair, then go on to the next menu, and all variations of hairs, including alien ones that you can't use will appear.
Skrell, catbeast, Vox, all of their hairstyles appear on the normal list even if you're human, selecting them just makes you bald.

**Comment by ComicIronic** [comment]
If you're an alien, do you get the human hairstyle choices and can you choose them?

**Comment by ririchiyo** [comment]
I'm pretty sure this is because there's no sanity checking here.

**Comment by gbasood** [comment]
Fixed in #2544 
There WAS sanity checking, the results just weren't used. Whoops.
