### ISSUE TITLE
ZAS Interaction with Energy Wall

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25394]
(WEB REPORT BY: dtscurvy REMOTE: 206.221.180.138:7777)
# Revision
d894c34d200c629690bcb0b719a1d87d636cb27f

# Description
When being dragged by ZAS into an energy wall, the ZAS never ends and constantly does damage because a player is being pulled into a vacuum occupied by a solid wall that does not conceal the vacuum

# Steps to Reproduce
Open an airlock to a space tile covered with an energy shield without magboots on, and you will be stunlocked to death.

# What you Expected
For the energy shield to contain the space tile.

# What Actually Happened
1000+ brute damage

**Comment by SonixApache** [comment]
feature

**Comment by SirSkeleto** [comment]
the barrier is fully permeable to gasses
