### ISSUE TITLE
Can't harm intent while aiming at the eyes with a hand labeler to label people's eyewear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25403]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
98e4ad71e594bbd68197ae6c63dbc0ff880da507

# Description
I can't label people's sunglasses as GAYEYES

# Steps to Reproduce
1- Harm intent and a hand labaler
2- Aim at eyes
3- Find a person wearing any eyewear
4- Click on them
5- Be unable to express your opinions on their eyewear

# What you Expected
GAYEYES

# What Actually Happened
No GAYEYES

**Comment by DeityLink** [comment]
What a shame
