### ISSUE TITLE
stupied emiter,,

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25405]
(WEB REPORT BY: assburgeri REMOTE: 206.221.180.138:7777)
# Revision
98e4ad71e594bbd68197ae6c63dbc0ff880da507

# Description
one day,  i sigend up as an engineeer personnel, and i was seeting up spermatter...
# Steps to Reproduce
1. go to horizon. ( station!!)
2. go to supermatter room.
3. press emiter .
4. this hapens https://gyazo.com/dbe043994ec03af39ddf4c2f2fdbdc25
# What you Expected
laeserbeme would hit the spermateer
# What Actually Happened
noth ing

**Comment by N3X15** [comment]
![fark_bR7LH4eGj9O1SNiUWLAMfM0LgT4](https://user-images.githubusercontent.com/110073/70846465-53a63b80-1e0e-11ea-9f25-e377b3398d67.gif)

**Comment by Exxion** [comment]
Holy shit
That one's puzzling even for beams

**Comment by Exxion** [comment]
Wait the beam on the other side is from a separate emitter isn't it
If so ignore my last comment
