### ISSUE TITLE
Xenoarch beacon locators are extremely busted and cursed

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#25401]
`/obj/item/device/beacon_locator`
Did you know this existed? I didn't.
The UI for it doesn't update the frequency var, which it needs to work.
It doesn't ever ping happily to indicate both it and the beacon are on the same frequency.
Setting the vars through VV doesn't make it work either.
The `frequency` var is a NUM even though the `/obj/item/beacon` `frequency` var is a STRING *even though you input a fucking NUM*!
How fucking old is this shit? Did this even ever work? Does anyone know?

related files:
https://github.com/vgstation-coders/vgstation13/blob/d9e848094b6925abf2f76e05e25d483a69edf908/code/modules/research/xenoarchaeology/tools/tools_locater.dm#L5

https://github.com/vgstation-coders/vgstation13/blob/d9e848094b6925abf2f76e05e25d483a69edf908/code/game/objects/items/beacon.dm#L3

might be fixable by synchronizing their input methods and formatting?

# Revision
98e4ad71e594bbd68197ae6c63dbc0ff880da507

**Comment by tayachiya** [comment]
Is it the admin-spawn only item that leads you to an exact location of a large artifact?
Or is that some new xenoarch tool?

**Comment by DeityLink** [comment]
Oh hey that was the useless pinpointer-looking item I removed back in #27594

I kept it in the protolathe for legacy reasons but better leave it be forgotten from memory until locating beacons has an actual purpose.
