### ISSUE TITLE
Metaclub Vox Ship Lacks Jetpacks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25411]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
4201fc850f545e6d1c5f187192b336e7df80619b

# Description
Vox Ship on Metaclub has zero jetpacks, forcing Salvage Brokers perpetuate the shitbird stereotype by stealing ones from NT station to do their damn jobs.

# Steps to Reproduce
Play as Salvage Broker on Metaclub.

# What you Expected
A jetpack so I can do my job.

# What Actually Happened
I wandered around NT station angrily in search of a jetpack since EVA was already looted.

**Comment by SirSkeleto** [comment]
remove nonantag vox from the game

**Comment by AI-Is-Rogue** [comment]
Are they not in the vox lockers in their botany area?
