### ISSUE TITLE
mouse and borers die instantly in vents

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25418]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
4cac1f2dc1df0dcf694adefd35610306bb64b48c

# Description
you feel cold and die, done roundstart

**Comment by Dacendeth** [comment]
mice are no longer immune to pressure in vents so they die instantly to roundstart no pressure pipes.

**Comment by Ephx1** [comment]
This really shouldn't be a thing for borers. Climbing just from the borer area out of research into the hallway on Box can put you in near crit. So unless you only target research personnel, you're kind of fucked and have to just wriggle through the halls for someone.

**Comment by DeityLink** [comment]
I'd say #25418 handled this issue. Re-open if it's still a problem for borers.
