### ISSUE TITLE
Magboot equipping over magboots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25414]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
97e8fd1879e179648575659064a81452d348ec75

# Description
trying to equip magboots (with e) over other magboots causes a spam of red text
# Steps to Reproduce
equip magboots, equip more magboots
# What you Expected
1 error message
# What Actually Happened
not that

**Comment by jknpj** [comment]
Remember when i said to not cross the beams?

**Comment by Dacendeth** [comment]
This does only happen with quick equipping, equipping with the mouse produces a single message.

**Comment by Kurfursten** [comment]
This is because the quick equip tries to slot it into every slot instead of just the shoes.
