### ISSUE TITLE
Remove the limit on assistants

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25420]
(WEB REPORT BY: nuklearcellphoneg REMOTE: 206.221.180.138:7777)
Getting real tired of having to join as a different job and put on a grey jumpsuit.

**Comment by SonixApache** [comment]
add a limit to the amount of cocks in your mouth

**Comment by boy2mantwicethefam** [comment]
The corridors of the station must be littered with the blood of jobbies and people who don't support this, a revolution has never been peaceful

**Comment by charlottesgit** [comment]
Oh god no, this seems like horror. 6 assistants might be too much even.
