### ISSUE TITLE
Horizon Brig

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25422]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
73ce10c7f51fff116dc559d12cb56b4762c3cc5f

# Description
The Horizon brig is all fucky wucky, mostly the cells.
# Issues I saw
The first cell doesn't work, Its paired to a different cell. Also, the third cell had buttons for three flashes.

Small post but yeah, that's what I saw. Might wanna look over all the stuff for it.

**Comment by Kurfursten** [comment]
cell 1 and 2 have cell 3 flashes and doors
