### ISSUE TITLE
grenade launcher unload button is busted

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#25428]
#### Description of issue
#24760 added the ability to unload grenade launchers.
The grenade launcher unloading feature, when used, opens a menu with all mobs within visible range.
When one of these mobs is selected, the grenades in the launcher are dumped at that mob's location.

I feel like that's unintended.

#### Difference between expected and actual behavior
press unload button, grenades fall out
vs
press unload button, choose invisible wizard on the other side of two shield generators and 5 plasma walls, grenades drop under his feet
#### Steps to reproduce
spawn a grenade launcher and hit the unload verb on it

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/0d8670fd0ea854e3166f4bb46af64b91d83cbb2e/code/modules/reagents/grenade_launcher.dm#L91-L100

#### Length of time in which bug has been known to occur
since #24760

#### Server revision
cf15f73a99f3c65356b88c3a3bf7fe1bef76eec6

**Comment by SGuivenne** [comment]
I mean you are technically unloading the grenade launcher.  Just through the shooty bit rather than the loady bit.

**Comment by RealestEstate** [comment]
makes me wonder if it would’ve worked through cameras.
