### ISSUE TITLE
NPC zombies attack zombies they raise

### ISSUE THREAD

**Issue by charlottesgit** [d3athrow/vgstation13#25426]
#### Description of issue
When you're revived or turned by an NPC zombie, you will be immediately chased and bitten by it, until death. It treats you as a human still.

#### Steps to reproduce
Be bitten by an NPC zombie, and after you're killed an turned, it will begin attacking.

#### Server revision

Game: cf15f73a99f3c65356b88c3a3bf7fe1bef76eec6 
Patches: fc6cfdf0edbca13310b472292d5628b92dced134

**Comment by DamianX** [comment]
I looked into this briefly while it was happening once. The reason why this happens is their `faction` variables are different, so they don't see each other as allies. One of them was set to some fixed string, the other was set to a `"\ref[]"` to some mob that I didn't bother resolving.

**Comment by west3436** [comment]
Fixed in #26120
