### ISSUE TITLE
ID/pocket stealing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25421]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
73ce10c7f51fff116dc559d12cb56b4762c3cc5f

# Description
Taking someone's ID or stuff out of their pockets gives no messages

# Steps to Reproduce
STEAL

# What you Expected
Them noticing

# What Actually Happened
Super stealthy spacemen

**Comment by Kurfursten** [comment]
confirmed on live

**Comment by Dacendeth** [comment]
This has been like this for years, It sometimes tells the person their id is being fumbled with last I tested this.

**Comment by Kurfursten** [comment]
It didn't show a fumbling message in thunderdome

**Comment by DamianX** [comment]
This is a feature. It shows the message only if you fail the action. See #17483.

**Comment by tayachiya** [comment]
Still feels weird with how low the chance is.

**Comment by DamianX** [comment]
It's not a chance. If either target or attacker moves, or the attacker is incapacitated, it fails, otherwise it succeeds.

**Comment by tayachiya** [comment]
I don't recall any failure messages showing up even after my target moved, but I might be wrong on that one.

**Comment by SonixApache** [comment]
it used to have a small chance to show
90% sure this was caused by #25046
