### ISSUE TITLE
Tactical lights can be clicked on/off while incapacitated

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#25434]
#### Description of issue
The action buttons are greyed out but they still work.

#### Difference between expected and actual behavior
chloral man, drag him through maint, succ
vs
CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK 

#### Steps to reproduce
get knocked out with a tactical light on your headgear, press action button

#### Specific information for locating
Probably just a missing sanity check.
https://github.com/vgstation-coders/vgstation13/blob/cb75bae895d30673a798961566b1965abb2c679b/code/modules/clothing/accessories/tactical_light.dm#L91-L98

#### Server revision
cf15f73a99f3c65356b88c3a3bf7fe1bef76eec6

**Comment by Kharkov72** [comment]
feature

**Comment by ShiftyRail** [comment]
Taclight morse code from beyond the veil
