### ISSUE TITLE
You can apply HOS upgrades to security borgs even when they don't have the two prerequisite upgrades.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#25431]
#### Description of issue
take borg
apply upgrade/hos
borg gets an error message saying the upgrade was not installed
upgrade gets installed anyway
laugh as it fruitlessly tries to use its broken lawbringer

#### Difference between expected and actual behavior
ERROR: UPGRADE REQUIRES PREREQUISITES
vs
```
You open the cover.
You successfully apply the security cyborg H.O.S. upgrade board to Security Robot-941.
Security Robot-941 is missing one of the needed components!
--- and ---
Cover opened.
Installation of security cyborg H.O.S. upgrade board failed.
```
![guns](https://user-images.githubusercontent.com/8468269/71134741-b416ed80-21ff-11ea-9357-9bc676854d81.png)

#### Steps to reproduce
acquire security cyborg
pop the cover
apply upgrade

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/f80e3bf6015a4078edc5b1cf4aea274f6305ac73/code/game/objects/items/robot/robot_upgrades.dm#L405-L411

https://github.com/vgstation-coders/vgstation13/blob/f80e3bf6015a4078edc5b1cf4aea274f6305ac73/code/game/objects/items/robot/robot_upgrades.dm#L41-L45

@jknpj 

#### Server revision
cf15f73a99f3c65356b88c3a3bf7fe1bef76eec6

**Comment by jknpj** [comment]
>broken lawgiver

REGISTER YOUR DNA YOUR FUCKING SHITTERS

**Comment by SonixApache** [comment]
Oh yeah they can actually just do that, though they lack the gripper to put the magazine back in.
Added the proper error messages after reproducing.
