### ISSUE TITLE
[Proposal/Task] Integrate firelocks into doors

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#25459]
Firedoors are sort of a half-assed solution to containing fires.  A while ago, We On Highest Discord discussed ways of de-half-assing them.  One of the things that was brought up was how fucked-up and awkward the current firedoor + airlock system is. So while there were a number of possible solutions, I think the best one we came up with was just integrating firedoor functionality into airlocks, and leaving the current firelock system for things like medbay's desk: things that actually NEED to be sealed with a separate system.

I'm not going to be working on this myself, since I already have a full tray of shit to work on (VGWS overhaul being No. 1, soundspess, and mechlimbs).

## Overall Design
* Airlocks would close and bolt using a seperate interlock bolt (so as not to fuck with existing bolts) when triggered by air alarms.
* Airlocks can have this functionality disabled with a wire (or in map via a variable)
* Airlocks would have directional hazard lights, like on the large firelocks that we don't use anymore for some fucking reason
* Overriding the firelock would also open the door, if usual door permissions are granted (or enough wireshittery has taken place).
* Existing firelocks on top of doors would be rendered redundant and removed.

## Benefits
* Life made slightly less hellish on the station [qol]
* Less bullshit needed when mapping new doors

## Cons
* Spritework
* Lots of spritework
* Removal of shitloads of existing firelocks from existing maps.

[feature request]
[discussion]
[help]
[sprites]

**Comment by Kurfursten** [comment]
people may hate em but directionals have 2 advantages

* they don't trap bad gas, it gets scrubbed on one side or the other
* you can open two firelocks sequentially, working like a thiefcatcher, so that means gas doesn't leak as much vs 1 large firelock

**Comment by SonixApache** [comment]
Spriting could be simplified by just adding firelock overlay lights or something.

**Comment by PJB3005** [comment]
> you can open two firelocks sequentially, working like a thiefcatcher, so that means gas doesn't leak as much vs 1 large firelock

Double firelocks are not that common and by god are they a complete pain in the ass for everybody involved.

But yes, the trapping of gas is problematic.

**Comment by N3X15** [comment]
That's more of a limitation of ZAS itself, especially when you have to factor in how zones are treated.  We'd have to make fundamental changes to ZAS to fix it.

**Comment by SonixApache** [comment]
Why not just make airlocks slowly vent gas that's trapped under them ~~while the firelock system is active?~~
- Vent gas until area's air alarm parameters are met
- Vent gas into area that's least like air alarm preferred parameters
- Compensate for temperature with lower preferred pressure

**Comment by tuypo1** [comment]
That sounds fantastic, I am personally of the opinion they should just be removed outright but that will never happen so this is the next best thing

**Comment by Kammerjunk** [comment]
you are too good for this world

**Comment by Kammerjunk** [comment]
having passed to the next, you are still too good for this world

**Comment by TGFH** [comment]
If it takes more than a crowbar to open them then I'd rather just not have firelocks or firedoors at all. In most cases they're more likely to get everyone killed than make anything better.

**Comment by west3436** [comment]
Derelict
