### ISSUE TITLE
Say Code Issues

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2545]
A place where you can put any issues with the say code

-Xeno languages do not work. [Haven't witnessed, reported in OOC]

-Non-mobs can get a [follow] option. i.e. Evil vending machines when they make a 'strange sound'

-The [follow] command has been moved to the front of said messages, but not for any other kind of chat like robotic, etc.

**Comment by ririchiyo** [comment]
No actual languages work, unless you mean the hivemind. It's intentional that non mobs can get a follow option at the moment.

**Comment by clusterfack** [comment]
In that case let me change my message that non-mobs follow command doesn't actually work. Also by xeno languages I believe they mean something like vox-speak.

**Comment by SarahJohnson489** [comment]
Voice analyzers no longer work meaning no final solution in hostage negotiations

Poly is getting a big "                    IT"S LOOSE!"

Vendors get the makes a strange sound message instead of their ads

**Comment by ririchiyo** [comment]
If one of these issues remain reopen it with a new thing please stop making issues with multiple issues in them.
