### ISSUE TITLE
Toxins Test Viewing Area ZAS Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25474]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
2505603b5898ed9dea75cfc98d4f8d2c8b4cd514

# Description
This has happened previously on Box as well but I didn't report it. On Snaxi, when launching a bomb from the mass driver for the first time the bomb will only move 3-5 spaces from the outlet. I think the mass driver area or the airlock outlet may start with low pressure which is slowing the bomb down.

# Steps to Reproduce
>make bomb
>place bomb in trash chute but don't open mass driver windoor
>press shoot button
>launch bomb 3-5 spaces from the launcher room
>die while your bomb detonates right by you

# What you Expected
Bomb to end up in the toxins test chamber

# What Actually Happened
Bomb ended up 3-5 spaces from the outlet of the mass driver area

**Comment by brndd** [comment]
As far as I know the bomb mass driver area starts with air on all the maps.

**Comment by Dacendeth** [comment]
There are cameras to make sure it got there for a reason.

**Comment by Exxion** [comment]
Air doesn't affect throwing anyway
EDIT: Well, except when it's flowing, but that shouldn't matter since it should get to the test area either way. It would just take longer.

**Comment by Kurfursten** [comment]
Can't reproduce

**Comment by Exxion** [comment]
I'm actually fucking stupid for not realizing this before
No, air doesn't affect throwing, but airflow sure can push the object off the tile of the mass driver when the doors open
If that's what is happening, it would only happen on the first launch (maybe second) and only if the timing is just right
