### ISSUE TITLE
Showers do not put borgs on fire out

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25472]
(WEB REPORT BY: miniaturebigfoot REMOTE: 206.221.180.138:7777)
# Revision
ebb10a2fbfbfbfb2dd7285ab480c52949692e27e

# Description
Showers cannot put borgs if they are lit on fire. Is this a feature?  
# Steps to Reproduce
Get lit on fire as a borg,I stumbled into a fire created by my RSF and tried to put it out with showers. It did not work. 
# What you Expected
To not be on fire
# What Actually Happened
I was on fire

**Comment by jknpj** [comment]
Unless someone changed how ExtinguishMob() works, i don't know how this can happen.

**Comment by jknpj** [comment]
A quick test shows that ExtinguishMob() works so i'll check what is happening later.

**Comment by Kurfursten** [comment]
sometimes regenerate icons doesn't get called (cosmetic only)

**Comment by jknpj** [comment]
It's not working for humans too

**Comment by jknpj** [comment]
Seems related to atmos fires

**Comment by west3436** [comment]
Duplicate of the ancient bug #13393
