### ISSUE TITLE
Ghost sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25477]
(WEB REPORT BY: dustyny REMOTE: 206.221.180.138:7777)
# Revision
2505603b5898ed9dea75cfc98d4f8d2c8b4cd514

# Description
While playing a medborg, if you pick up a vial of blood (doing viro stuff), there is a ghost sprite left behind above your modules.  https://imgur.com/a/H0btxTZ
# Steps to Reproduce
Use your gripper to handle vials, inject blood in them.
# What you Expected
Putting down the vial gets rid of the sprite
# What Actually Happened
Sprite stays

**Comment by Zth--** [comment]
I could not reproduce
