### ISSUE TITLE
Horsemask doesn't make you speak like a horse

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#2547]
If you are cursed with a horse mask you no longer speak like a horse, I believe the same will be true if you get the virus symptom as well.

**Comment by ConkerDev** [comment]
Weird, Im pretty sure I got horsemasked a week ago, and it NEEIGH'd. Any specific test?

**Comment by ComicIronic** [comment]
The saycode hit less than a week ago. I'll do some testing.
