### ISSUE TITLE
Ghosts can activate the suspension shield generator

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#2548]
![image](https://cloud.githubusercontent.com/assets/10002997/5790335/17bc2eac-9ea4-11e4-82b6-381e7d2f76d9.png)

**Comment by ComicIronic** [comment]
Even more ghost attack issues.
The wonders of oldcode.

**Comment by utilitas-** [comment]
That is not oldcode. That is terrible baycode. All the machines related to xenoarchaeology were fully open to ghosts messing around until we fixed it, and it probably still is left unfixed on the baystation branch. It's likely that more xenoarch machinery has these issues.
