### ISSUE TITLE
Grinch's bag can't fit as many items as it used to.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25485]
(WEB REPORT BY: irradiation REMOTE: 206.221.180.138:7777)
Read the tin.

Very probably possibly caused by Barry's rework of bag space [#23942].

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by ShiftyRail** [comment]
This is unacceptable

**Comment by DeityLink** [comment]
It seems to stack items as good as a bag of holding does, as it did before.
![image](https://user-images.githubusercontent.com/7573912/133503676-6e3c7c9e-8c5e-497c-a9c0-81479fc4513b.png)
