### ISSUE TITLE
The TacLight fix broke Taclights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25490]
(WEB REPORT BY: irradiation REMOTE: 206.221.180.138:7777)
IF you want to use them, you have to take them off your equipment THEN turn them on by hand. The action button doesn't work anymore.

Also Taclights don't even have an icon anymore, ayy lmao.

Use-in-hand bug definitely caused by [#25486], as it didn't happen before the merge.

**Comment by SonixApache** [comment]
@MadmanMartian

**Comment by Exxion** [comment]
The action button doesn't pass `user` to `attack_self()` so the new checks runtime
