### ISSUE TITLE
AI STATUS NOT WORKING

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25531]
(WEB REPORT BY: salamandooo REMOTE: 206.221.180.138:7777)
Setting my AI status through the button only changed the AI status on the left of the upload.. This is on BOX. I have to manually set all the rest.

**Comment by toomykins** [comment]
not necessarily a bug.
there are 2 types of status displays. AI ones and normal ones. AI ones can be mass set, normal ones cannot.
There are 8 AI status displays on box.
there are 68 normal displays on box (including other Z-levels)

**Comment by west3436** [comment]
Not a bug - you can mass-set the status displays on the comms console
