### ISSUE TITLE
Goldgrubs can burrow underground on space tiles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25533]
(WEB REPORT BY: rfultra REMOTE: 206.221.180.138:7777)
# Revision
9fce9621b057385c92a4817a7cda9f5d12a66fab

# Description

Goldgrubs can burrow underground on space tiles

# Steps to Reproduce

Be in space with goldgrub, make it flee, watch it burrow

# What you Expected

Either better wording or it not happening at all

# What Actually Happened

it 'burrowed' and disapeared from sight on a space tile

**Comment by SirSkeleto** [comment]
quantum tunneling

**Comment by DeityLink** [comment]
Duplicate of #26934
