### ISSUE TITLE
ATM eats card

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25534]
(WEB REPORT BY: silvorz REMOTE: 206.221.180.138:7777)
# Revision
9fce9621b057385c92a4817a7cda9f5d12a66fab

# Description
The ATM at the roid station keeps eeting the cards, making them stuck in the ATM, I also cant get to the actual withdraw screen
# Steps to Reproduce
Put the ID into the ATM, then try to take it out
# What you Expected
I expected to be able to take out money, then take out the card
# What Actually Happened
I couldnt do either of the things it should have

**Comment by Kurfursten** [comment]
Confirmed by admins to be power offline

**Comment by SysadminJeroen** [comment]
It wasn't a bug, the ATM didn't have have any power.
