### ISSUE TITLE
Roid HoP Office not working with Spess Pets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25545]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
40c840911a6a57cf1b4e0921f5cf2a81ec019c08

# Description
See title. My Ian pet asked me to head to the office but no spot inside worked.
# Steps to Reproduce
Get Spess Pets
Get Ian
Wait for him to ask to head to HoP office
# What you Expected
Spess Pet to level up and work properly
# What Actually Happened
Spess Pet cannot level up from visiting and I can no longer visit new areas

**Comment by ghost** [comment]
this makes corgi spesspets unlevelable on roid
fix this immediately
