### ISSUE TITLE
cheat death does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25540]
(WEB REPORT BY: ribeira REMOTE: 206.221.180.138:7777)
# Revision
1a83a40870d349afea66f0ff8b5c9eb8ad69bd18

# Description
I tried using cheat death as a vampire, waited the time, got the message my body twitches slightly, click action buttom again to revive, but when i clicked it i got a msg saying you are already reviving and it did not work.
# Steps to Reproduce
dies as a powerful vamp, try using cheat death
# What you Expected
to revive once i clicked the buttom again
# What Actually Happened
It said i was already reviving and did not revive me.

**Comment by SirSkeleto** [comment]
wrong button

**Comment by Zth--** [comment]
you revive with this button 
![image](https://user-images.githubusercontent.com/11085293/71729031-7d56ef00-2e1d-11ea-80e4-b75c453c18b4.png)

it could get a QoL tho
