### ISSUE TITLE
lordsingulo bundle can be obtained from traitor pda on snaxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25559]
(WEB REPORT BY: rfultra REMOTE: 206.221.180.138:7777)
# Revision
7df82398bdb1219b607eb533c3f388400810d40f

# Description
lordsingulo bundle can be obtained from traitor pda on snaxi

# Steps to Reproduce
Be traitor on snaxi, keep getting bundles until you get it

# What you Expected
Not to get a bundle centered around the singularity engine on a map with no singulatirty engine

# What Actually Happened
Got the bundle despite there being no singulo on snaxi

**Comment by Kurfursten** [comment]
You can order and build a singularity on Snaxi (and Deff, Roid, Horizon)

Then again, bundles are full of chance to begin with. Like the upload bundle if there's no AI. Honestly if someone would revisit bundles and make them more fun that'd be great.
