### ISSUE TITLE
Cult just works

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#25560]
![Cursed image](https://user-images.githubusercontent.com/31417754/71646229-23eba480-2ce5-11ea-8fff-1e9711ad566d.png)

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by ShiftyRail** [comment]
Cultists can't dance around it without equiping an atmos suit
Most grunts of the station can't do shit about this because they don't have ranged weapons

**Comment by Kharkov72** [comment]
feature, just set up an emitter

**Comment by boy2mantwicethefam** [comment]
Still a feature, deconstruct a wall to space the gas, the time it takes to kill you from lack of pressure (and you also have an oxygen tank + mask, and even if the plasma miner keeps spewing gas you just have to take off your clothes) will be more than enough time to destroy the stone with a spear, you sound like an assmad noob that needs his hand held, go back to bay......

**Comment by ShiftyRail** [comment]
So basically it doesn't have to make sense if it's cult
At last I truly see

**Comment by boy2mantwicethefam** [comment]
sorry...it's the server culture......(insert insist on leaving here)

**Comment by RealestEstate** [comment]
this is fine and funny and makes the game better

**Comment by DeityLink** [comment]
Like I said on Discord, why isn't there an area subtype for the gas miner pens?

**Comment by DamianX** [comment]
Because then they'd need their own APC, duh.
