### ISSUE TITLE
MC Tab Tanks Framerate

### ISSUE THREAD

**Issue by SheepFighter** [d3athrow/vgstation13#25576]
#### Description of issue
When active, the MC tab absolutely tanks the framerate.

#### Difference between expected and actual behavior
It's supposed to be a helpful diagnostic tool, not a hindrance to basic gameplay.

#### Steps to reproduce
Switch to the MC tab. Weep as your framerate plummets. Switch to another tab. Breath a sigh of relief.

#### Server revision
9a553e846624d84f2f7596e401961c7dbd940eaa

**Comment by boy2mantwicethefam** [comment]
I think it's just a problem with how much it's packed in it, I'm pretty sure it's a BYOND problem and IIRC it's a lot of statpanels that get updated constantly

**Comment by SheepFighter** [comment]
Quite probably, in which case the best solution is to reorder it so it's not the default tab. That way, unwary coders will be able to grok the cause of their distress fairly quickly.

**Comment by boy2mantwicethefam** [comment]
I'll see what I can do
