### ISSUE TITLE
Exosuit Fabricator processes no/bad requests

### ISSUE THREAD

**Issue by zxpr0jk** [d3athrow/vgstation13#2557]
When queuing a quick robot, the queue will not add the right leg.

When trying to build the right leg manually, it prints armor instead.

When trying to queue/build a diamond drill, while having needed materials, nothing is queued or built.

Early options on the list still operate normally, as did the first few processes. At some point during the round, mid to late entries on the process/build prompt became unresponsive or incorrect.

**Comment by Probe1** [comment]
issued here as well https://github.com/d3athrow/vgstation13/issues/2388#issuecomment-69125475

**Comment by d3athrow** [comment]
Duplicate
