### ISSUE TITLE
Mining Ore Box Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25584]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
c0d6e1094415b6ab31b07c594f892a97db922c12

# Description
Can't put any ores in the box but plasma
# Steps to Reproduce
Be miner mine ores put ores in box
# What you Expected
To be able to store ores in box
# What Actually Happened
only plasma go in

**Comment by PJB3005** [comment]
Caused by #25562
