### ISSUE TITLE
Suggestion: Merge Heist into Traitor/Blob/Nuke

### ISSUE THREAD

**Issue by Cipherature** [d3athrow/vgstation13#2558]
Heist as it stands now doesn't work very well with the server.

If the only antags in a mode are supposed to be non-hostile, and the crew aren't supposed to kill them, the crew will inevitably start killing them.

A vox round without any killing would probably not be fun for most of the server either. Merging it with actual hostile antags might add a fun third factor to the round without having to go hunting the heisters.

Also suggested was shrinking the heist team down to three, six is far too many to coordinate either stealthily or non-hostile.

**Comment by Probe1** [comment]
Traitor + Heist would work really well.  If you were to merge it into another mode you would absolutely have to reduce the number and 3 is probably the best bet.  If you have too many  players in antag roles the rounds going to be crazy (and not in a Cult way).  Something like having it trigger when there's at least 30 players and the game dishes out 3 heist roles and 3-5 traitors would work very well.

**Comment by clusterfack** [comment]
I agree heist has major issues, mainly with the fact the crew either has no reason to oppose them, or a reason to just kill them outright. But the problem is what happens to the traitor + heister round once they send back their ship, does the round continue? If so do the vox just become ghosts?

**Comment by IratePirate** [comment]
Heist with one or two traitors would be good.

**Comment by Uso15** [comment]
That would definently help, if it was heist + other round type then it would both take some heat off of the Raiders and still give 'valids' If the vox team decides to stay peaceful.

While we're on the topic of vox raiders, I'd like to know if we plan on merging something similar to Paradise ' s merchandise for the Skipjack inventory. Trinkets and tools the vox can barter with should they decide to trade for their objective.

**Comment by Cisrox** [comment]
Pretty sure heist has been removed, closeable.

**Comment by ihadtoregisterforthis** [comment]
Heist is not removed.

**Comment by Probe1** [comment]
This discussion has run its course.  This definitely should be coded but I think we can empirically say no one is going to.
