### ISSUE TITLE
Holding Item Stacks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25594]
(WEB REPORT BY: datemono REMOTE: 206.221.180.138:7777)
# Revision
a852b10ed7454edb4c69271b42f1a319a6ad6e8b

# Description
as a diona, if you take a stack of items out of a plant bag, you hold the entire stack, even being able to drop the stack of x50 or so, and the stack showing as 'x50 Tomatos' or whatever on the floor
# Steps to Reproduce
as diona click on produce from inside a plant bag, you now hold a stack of items
# What you Expected
to take one tomato out
# What Actually Happened
i now hold 50 bluespace tomatos in my tiny feeler hands

**Comment by DeityLink** [comment]
Seems to have been fixed.
