### ISSUE TITLE
Random Cargo Console on Snaxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25596]
(WEB REPORT BY: themannamedtom REMOTE: 206.221.180.138:7777)
For some reason it looks like a cargo console spawns on Snaxi at 146, 64, 1. I was told to make this report by Dylan.
https://i.imgur.com/LaSEZ5X.png

**Comment by Kharkov72** [comment]
🤔

**Comment by Kurfursten** [comment]
now that is a weird one

**Comment by Kurfursten** [comment]
It was hidden behind a tree in the editor
