### ISSUE TITLE
Starting to disposal someone and then buckling them leaves them unable to move

### ISSUE THREAD

**Issue by Cipherature** [d3athrow/vgstation13#2559]
Steps
1. Start stuffing someone into disposals.
2. Buckle them into something.
3. Let them go on a journey through pipes.
4. When they come out the other end, they will be unable to move until someone clicks on the chair they were buckled to.

**Comment by ComicIronic** [comment]
How you can stuff someone who's buckled is beyond me.

**Comment by Cipherature** [comment]
Sorry, the steps were slightly wrong. You have to stuff them in to start the process and THEN buckle them.

**Comment by ComicIronic** [comment]
Ah. That presents a more interesting issue, and it might be needed to shove a buckle check into do_after or something similar.

**Comment by eswordthecat** [comment]
@ComicIronic

**Comment by ComicIronic** [comment]
Closeable according to #2569. Reopen if not fixed.
