### ISSUE TITLE
Space blanket speed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25590]
(WEB REPORT BY: robosperg REMOTE: 206.221.180.138:7777)
# Revision
a852b10ed7454edb4c69271b42f1a319a6ad6e8b

# Description
Space blankets slow you down when held in a pocket
# Steps to Reproduce
Put blanket in pocket
# What you Expected
Nothing
# What Actually Happened
Slowdown

**Comment by RFultra** [comment]
Real talk have you ever tried to move at any decent speed with an entire blanket in your pocket?

**Comment by Exxion** [comment]
I know this isn't what space blanket means in the game, but the blankets by that name in real life very easily fit in a pocket
