### ISSUE TITLE
ERT Shuttle destroys the ground it's on when it arrives at snowmap, causing said ERT to get ZAS'd

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#25609]
A moment of silence for the 2 men and a random vox who died a minute after it landed.

**Comment by Kurfursten** [comment]
What ZAS'd them? Walking out? Opening the door? Unclear exactly what happened.

**Comment by BomberBro** [comment]
Sorry, when the shuttle arrives the four engine tiles destroy the ground under it and create space, which, combined with the non space tiles, creates an inescapable hellhole for anyone unlucky enough to go near. Two ERT walked out the shuttle and got owned instantly, and the vox was just next to the back when it happened.

**Comment by Kurfursten** [comment]
Of course, the engines have space under them
