### ISSUE TITLE
Blob overmind storm possibly spawns two blob cores in the same impacted location

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#25603]
Unsure, please track or test rounds where the ruleset is drafted and observe if the meteors spawn separately or bundled together. I am unsure because I remember it happened once, but I haven't found a PR that would fix it yet.

**Comment by BomberBro** [comment]
I always assumed this was a feature to give the blob a bit of an advantage, midround overminds are generally at a massive loss since the crew already has materials to mass print weapons and mechas and power is already set up.

**Comment by Killette2** [comment]
Siamese twin feature

**Comment by PrimeDSS13** [comment]
They spawn together yes, but feature.

**Comment by Killette2** [comment]
I actually thought this was a bug. Sometime the 2nd blob doesn't even have a mind

**Comment by DeityLink** [comment]
> 
> 
> I actually thought this was a bug. Sometime the 2nd blob doesn't even have a mind

I'd even say it never has a mind unless a ghost clicks on it.
