### ISSUE TITLE
Blob in engineering is nearly impossible to fight due to severe lag.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25625]
(WEB REPORT BY: caboozles REMOTE: 206.221.180.138:7777)
# Revision
4fa921ad1b6e61be8201d824095c748583242a8b

# Description
A blob spawned in engineering on Box and even getting near the blob caused features at an insane rate. Trying to attack the core then became a suicide attack because there was no way to react other than hope that your clicks were accepted.

# Steps to Reproduce
See bleb in engineering
Attempt to get within distance of it.
Crash multiple times.

# What you Expected
To be able to fight it normally

# What Actually Happened
Game crashed and froze multiple times.

**Comment by Caboozles** [comment]
I should possibly reference that multiple people in dedchat also experienced bluespace hell while viewing the blob, but not the same round blob in arrivals. Possibly a client issue?

**Comment by west3436** [comment]
Can't replicate
