### ISSUE TITLE
RCD and borgs in snow taxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25624]
(WEB REPORT BY: matomatto REMOTE: 206.221.180.138:7777)
# Revision
55d9f23b6b87593731f16a0bd108fa0e148ebf58

# Description

RCD cannot place tiles on snow taxi station. Affects borgs by limiting their capability to build new tiles other than already built.

# Steps to Reproduce

get RCD 
deconstruct floor
try place new floor

# What you Expected

Using RCD should be able to place floor on snow or asphalt.

**Comment by RaccoonBro** [comment]
legitimately forget, does the RCD create floor on space tiles? on snaxi you need to build a grille and then use a floor tile to build floors, like you would in space

**Comment by tayachiya** [comment]
Can't you just.. slap floors on the snow? I think that's how you build stuff there
