### ISSUE TITLE
top-right frame size is fucked so you can't see everything in it

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#25636]
[wherestheskinlabel]
#### Description of issue
![image](https://user-images.githubusercontent.com/5942183/72206430-14f7b580-348e-11ea-984e-3a695f969723.png)
notice the scroll bar to the right: the frame isn't set to the proper height

#### Difference between expected and actual behavior
I can't see everything when alt-clicking a turf and I have to restart my client to fix it

#### Length of time in which bug has been known to occur

less than like a year, probably

#### Server revision

803c5ab596c5c44f1f610657e064ecd25e43b9bf

**Comment by PJB3005** [comment]
Duplicate of #23788

**Comment by Kammerjunk** [comment]
I searched for "scroll bar" instead of "scrollbar" and assumed GitHub could handle it 😔

**Comment by Kammerjunk** [comment]
also I'm pretty sure this happened before I re-adminned but maybe my brain is gunked

**Comment by Irradiation** [comment]
IIRC, this only affects admins (and those currently deadmined for the round).

**Comment by SonixApache** [comment]
fix it

**Comment by PJB3005** [comment]
How.

**Comment by DamianX** [comment]
You should try disabling the MC tab entirely, lock it behind the `debug verbs` verb

**Comment by Kammerjunk** [comment]
probably not an issue anymore
