### ISSUE TITLE
Packed Station Engineering Foyer APC disconnected from grid.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#25632]
![image](https://user-images.githubusercontent.com/5549060/72152302-2fd40800-3370-11ea-8772-746df1b4e23a.png)

[packed]

**Comment by jknpj** [comment]
the wire was shortcircuit'd, see the ashes

**Comment by kernikov** [comment]
Oh, it's intentional?
The ashes are less obvious with all the stuff piled on the tables.

**Comment by jknpj** [comment]
I'm just jesting but maybe?

**Comment by Kharkov72** [comment]
veers...
