### ISSUE TITLE
Wheelstation Research Outpost External Airlock Fuckery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25641]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
acfeb0a3487f21d8402b24c7832ad5bf369c7dc1

# Description
Neither of the buttons inside the airlock portion of the exit from the research outpost onto the asteriod begins the depressurization process and opens the external door. The only way to get out is to force both doors open.

# Steps to Reproduce
Try to get onto the asteroid from the outpost.

# What you Expected
Pressing the button from within the airlock would depressurize the airlock and open the exterior door.

# What Actually Happened
I pressed the button, the pressure didn't change, and the interior door opened.

**Comment by SonixApache** [comment]
the obvious solution is to remove wheel

**Comment by west3436** [comment]
Wheelstation is gone please close @Kurfursten
