### ISSUE TITLE
Medicine doesnt heal you when you have damaged robotic limbs

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#25640]
#### Description of issue
if you have metal limbs that are damaged medicine will waste ticks trying to heal it and failing, isntead of healing actual organic wounds.

#### Difference between expected and actual behavior
Expected: Have wound in chest, minor scrape in robotic leg, expect bicaridine heal wound in my chest.
Got: Bicaridine basically doesnt function

#### Steps to reproduce
Have robotic limbs and damage them all with a toolbox, the more you have the more noticible.
Damage your torso with some brute, then drink some bicaridine/etc
Watch as it doesnt heal you for several to all ticks. 
also happens with burns and kelo/derm/etc

#### Length of time in which bug has been known to occur

Years, forgot about it until it just happened again.

#### Server revision

Revision: acfeb0a3487f21d8402b24c7832ad5bf369c7dc1

**Comment by Zth--** [comment]
I couldn't reproduce it. Bicaridine healed my chest

Edit: wait, ALL robotic limbs? brb checking

**Comment by Dacendeth** [comment]
Yeah they gotta be damaged too, one damaged limb will be like, 50% to heal the chest 50% chance to waste the lifetick failing to heal the limb.

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/72213605-9287e980-34bf-11ea-8631-a366bbf560d0.png)
Before and after 30u of kelotane
