### ISSUE TITLE
Welding cameras makes them not drop an assembly and get stuck. strange bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25653]
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
353c42106c0186a81630c78019c20f331ff1b490
to do this bug you snip the wires on a cam and weld it off and you can see for yourself it don't work right

**Comment by iFlashYou** [comment]
use a wrench after the welder
