### ISSUE TITLE
nuke ops shuttle broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25650]
(WEB REPORT BY: ribeira REMOTE: 206.221.180.138:7777)
# Revision
353c42106c0186a81630c78019c20f331ff1b490
The nuke ops shuttle wont work when you move to station, you get stuck forever on bluespace
# Description
read above
# Steps to Reproduce
try moving nuke ops shuttle to station
# What you Expected
I expected it to work, this has been happening for weeks and admins are well aware of it, but none cared enough to tell coders to fix it
# What Actually Happened
we got stuck at bluespace and had to ahelp, wait several minutes until admin found a way to move us

**Comment by dunsel-hordon** [comment]
can confirm this has happened to me before.

**Comment by DamianX** [comment]
This happened to me once but I don't know why. It's been a long time since it happened, though, so I'm closing.
