### ISSUE TITLE
you're still inside a sleeper if you jaunt out of it

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#25666]
#### Description of issue
wiz got caught
wiz got put into a sleeper by a sec officer
wiz jaunted away
but he was still technically inside the sleeper so the sec officer just pulled him out of the sleeper and right next to himself

#### Server revision
Game: 95979fd70891eb043a18ffd228ffc9c924c77f66

**Comment by ghost** [comment]
Amazing.

**Comment by Kammerjunk** [comment]
bless you
