### ISSUE TITLE
roboduck can get triggered by things that do 0 damage to him

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25677]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
696119c0217392c95cefdb9947c7482578f53c5b

# Description

Such as hitting it with a hailer on help intent

```
Fabrice Leforestier pats the robot duck with the hailer.

You hail for The robot duck to halt!
```

cool and good feature

**Comment by MadmanMartian** [comment]
Shouldn't have taunted the duck

**Comment by Kharkov72** [comment]
feature

**Comment by ShiftyRail** [comment]
You know another fun feature, it's called security tape and it would make situations like that much more hilarious

**Comment by MadmanMartian** [comment]
![bleh](https://media2.giphy.com/media/dEdmW17JnZhiU/giphy.gif)

**Comment by jknpj** [comment]
quack, quack...quack!

**Comment by Kurfursten** [comment]
Say Jimbo, did you know that every officer who taunts the duck gets filled with lead?

Now that's just quackin crazy!

**Comment by DeityLink** [comment]
don't taunt the duck
don't mess with the duck
don't anger the duck
