### ISSUE TITLE
PDA holomap tracking on vehicle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25672]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
77464a6e27e56b86f24ac8fef4a46dfcaa9dc86f

# Description
PDA holomap doesn't track your location while moving on a vehicle
# Steps to Reproduce
uh
# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
posting so I remember to fix it later
