### ISSUE TITLE
broken black slime extract

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25676]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
696119c0217392c95cefdb9947c7482578f53c5b

# Description
black slime disappears when injected w/ plasma
# Steps to Reproduce
inject black slime w/ 5 units of plasma
# What you Expected
1 unit of adv. slime mutagen in the resulting used extract (black).
# What Actually Happened
it disappeared :(

**Comment by Zth--** [comment]
#25582 probably

**Comment by Irradiation** [comment]
You mean "definitely".

**Comment by boy2mantwicethefam** [comment]
That's the point, it creates a bottle on the spot that contains the reagents instead

**Comment by FoggyDayWindyCay** [comment]
That'd be nice but it doesn't spawn anything, the slime extract just disappears and that's it.
If you use slime enhancer it just lets you inject it three times before disappearing, still doesn't spawn anything.

**Comment by boy2mantwicethefam** [comment]
Oh yeah, that was the intention of the PR, to get rid of the unusable garbage. I've been itching to work on the suggestion of making it leave slime jelly behind

**Comment by boy2mantwicethefam** [comment]
whoops
