### ISSUE TITLE
Using a "ghost self" rune that is in the same tile as other runes prevents you from re-entering your body

### ISSUE THREAD

**Issue by vgrainicorn** [d3athrow/vgstation13#2568]
I was pretty sure I reported this a while ago but I couldn't find the issue so here it is again. Maybe I just posted in the thread or something.

1. Draw any rune.
2. Draw a ghost self (hell travel self) rune.
3. Activate the ghost self rune.
4. Using re-enter-corpse tells you the astral cord has been severed, blah blah.
5. Panic and ahelp.

I think if the ghost self rune is the FIRST rune on the tile then it works correctly.

**Comment by ComicIronic** [comment]
Caused by a look through the runes on the tile, no doubt.

**Comment by clusterfack** [comment]
You can stack runes on tiles? That doesn't seem intended
