### ISSUE TITLE
book of binding has unlimited uses

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25684]
(WEB REPORT BY: ribeira REMOTE: 206.221.180.138:7777)
# Revision
0ad4dc830f85d2183c0faa3a6ee3cd6dbb224904
For whatever reason an officer managed to read my book of binding and get bound object spell.
# Description
I got syndicate bundle, it was the sith one, got killed, an officer read the book of binding i had on bag and got the powers
# Steps to Reproduce
I dunno, admins failed at it, i guess get a syndicate buddle with syth stuff, use the book, get killed and have someone else read the book
# What you Expected
I expected the book to only work once like most single spell spellbooks
# What Actually Happened
It gave the officer powers, even though the book was already used.

**Comment by nervere** [comment]
can't reproduce
