### ISSUE TITLE
Trying to buy from a vending machine with insufficient funds causes it to keep your credits as a penalty for being a smartass

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25680]
(WEB REPORT BY: potatomancake REMOTE: 206.221.180.138:7777)
# Revision
0ad4dc830f85d2183c0faa3a6ee3cd6dbb224904

# Description
Tried to see if I had enough money for a jetpack by just seeing if it would let me buy one. The transaction didn't go through, and my wallet is now missing 136 creds, plus 10 for the test to make sure it wasn't a fluke. Fortunately it did not also eat my bank money.
# Steps to Reproduce
Buy a thing with insufficient wallet funds, allow the machine to draw on your bank account, and still have insufficient funds.
# What you Expected
Bug "fixes"
# What Actually Happened
Why do you hate mining?

**Comment by Exxion** [comment]
The quotation marks around "fixes" up there are really baffling
