### ISSUE TITLE
Angie ate the Cult site

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25688]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
0ad4dc830f85d2183c0faa3a6ee3cd6dbb224904

# Description

Mining on def today and the cult site and angies den spawned on the same exact site.  This resulted in virtually the entire cult site being disintegrated.

**Comment by Irradiation** [comment]
Angie 1
Narsteel 0

**Comment by Kurfursten** [comment]
Feature
