### ISSUE TITLE
Upgrading the monkey recycler with tier 4 manipulators lets you produce infinite monkey cubes

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#25693]
The monkey recycler has two manipulators
Tier 4 manipulators have a rating of 4

`minimum_monkeys = 4 - (manipcount/2)`

4 - 8/2 = 0 monkeys consumed when making monkey cubes

**Comment by dunsel-hordon** [comment]
should just leave it in as a feature seeing as its almost impossible to get tier 4 parts
