### ISSUE TITLE
[Suggestion] Clown AI

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#25707]
Add a 1/100 chance that if:

1. No players with AI preferred readied

2. Two or more players with Clown readied

Then, the clown will spawn in the AI chamber, with the AI Job title, with a camera console that lets them jump to players who speak over the radio, and open doors near that player with the console, with nothing to indicate to the crew that there is  just a clown in the AI Chamber. And a curtain they can open and close which, when closed, looks like one of the AI sprites, and a curtain that looks like the floor tiles to conceal the two extra consoles.

Edit:

Second thought I had: If there is no AI at round start and it's Wiz, spawn a special item for the Wiz that uses up some of his Spell selection to put him in the AI chamber , on the crew manifest, with the same conditions, for muh wizard of oz gimmick

**Comment by Gazathor** [comment]
holy based

**Comment by RealestEstate** [comment]
best feature request of the century

**Comment by SageOfLight** [comment]
Fund it.

**Comment by tuypo1** [comment]
Anything that encourages non slip based clowning is great in my book

**Comment by Eneocho** [comment]
want

**Comment by BomberBro** [comment]
![cameraclown](https://user-images.githubusercontent.com/51391726/113957323-00b77b00-97ed-11eb-83c3-8cff4746b17f.png)
I demand my creative royalties (this post was 10 minutes before the issue)

**Comment by Servalfang** [comment]
needs a cardborg helmet so it has the silicon style text

**Comment by ghost** [comment]
pay no attention to that clown behind the curtain

**Comment by Eneocho** [comment]
> pay no attention to that clown behind the curtain

Do you get a wish if you steal the shoes from the wicked mime?

**Comment by nuklearcellphoneg** [comment]
the wicked wiz of the west...
