### ISSUE TITLE
Canister UI Is Blank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25703]
(WEB REPORT BY: thatredpyro REMOTE: 206.221.180.138:7777)
# Revision
f8175ff424ca30638019cec40d6ecde37c266265

# Description
For like the last week or two, I am unable to view canister UI so I can't fill tanks or leak the contents in any way. It is somehow only affecting the NanoUI of canisters and nothing else seems affected.
# Steps to Reproduce
Find a canister, click on it
# What you Expected
For the canister interface to open so I could fill whatever tank I have on me/already inserted.
# What Actually Happened
A blank popup with Nanostren logo in the background comes up and if I had already put a tank in the canister, it's now non-retrievable for me.

**Comment by ThatRedPyro** [comment]
Should've also specified that I had tried like 4 different Byond versions, including the beta and the latest stable build and some older ones. Deleting the Byond cache, using the resend resource or fix NanoUI buttons seem to have no effect.

**Comment by ThatRedPyro** [comment]
Just noticed this was actually constant on portable pumps too but who the hell even uses them

**Comment by ghost** [comment]
I don't think this isn't an issue with nano, it's an issue with html UIs in general

Closing this either way as it the same issue as #23563
