### ISSUE TITLE
Some xenoarch guns Vanish

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25709]
(WEB REPORT BY: gunosaguki REMOTE: 206.221.180.138:7777)
I've noticed this twice now that some xenoarch revolvers/alien guns when you expend their ammo they go invisible and vanish entirely if you drop the gun itself.

**Comment by DrSnips** [comment]
Some artifacts from arch vanish from existence as well even when digging them up perfectly and with a field. Maybe these issue are related?

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by Dacendeth** [comment]
I believe their sprite just becomes invisible, you could still get it by right clicking or using the alt click menu on at tile.
