### ISSUE TITLE
Packed engineering foyer apc not connected

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25712]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
1631fe43d05f3329a571b7e2a25b757c7bb88356

# Description
on packed, the engineering foyer APC is not connected to the grid. The missing wire is under a table to the left. Also what happened to the engineering SMES?
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by kernikov** [comment]
Duplicate of [#25632]
