### ISSUE TITLE
Diona Popcorn Hair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25710]
(WEB REPORT BY: burntdevil REMOTE: 206.221.180.138:7777)
# Revision
ab1f39942d6bf682c3f9ce5c04b653e703104139

# Description
It wasnt added to the list for female dionas, and with the diona hair pr, became unavilable for use.

# Steps to Reproduce
roll a female diona
# What you Expected
the hair to be selectable
# What Actually Happened
it wasnt. it was taken off my static's head like some sort of hair bandit.

**Comment by DeityLink** [comment]
It's called Popped Hair @BurntDevil
