### ISSUE TITLE
redtext after reborging

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25722]
(WEB REPORT BY: zanith50 REMOTE: 206.221.180.138:7777)
# Revision
38a4e32e1804b608084da495916fca90aefad225

# Description

started as borg had laws purged, then actions led to borg getting blown and while as an mmi was made a sleeper agent and then after reborging i still had the redtext codewords from being a syndie agent nto sure if bug or intention

**Comment by jknpj** [comment]
It says in the thing "If you're seeing this after being borged..."
