### ISSUE TITLE
I bought redundant threading two times

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25732]
(WEB REPORT BY: mentgah REMOTE: 206.221.180.138:7777)
# Revision
31af501e0305da9379a7ace22ca772c7cd80411b

# Description
see title

# Steps to Reproduce
click on redundant threading and lag
# What you Expected
to not buy it two times
# What Actually Happened
i bought it two times

**Comment by Kurfursten** [comment]
Extra redundant

**Comment by boy2mantwicethefam** [comment]
Redundant

**Comment by SGuivenne** [comment]
Same bug as #25711
