### ISSUE TITLE
[Bug/Feature Loss]Cargo radio frequency now displays as black instead of brown

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2573]
:u used to be a pleasant brown and now it's just black.  someone fucked something up somewhere and now someone has to fix it.

![image](https://cloud.githubusercontent.com/assets/8550416/5811353/854a9e06-a023-11e4-8236-2ee43ba1e5ca.png)

**Comment by clusterfack** [comment]
Same with service

**Comment by clusterfack** [comment]
Fixed with 0ab7469c72bebe40b1926f095047ca4c13c075d3 I believe

**Comment by ComicIronic** [comment]
Reopen if not fixed.

**Comment by Probe1** [comment]
It's not fixed on the test server.

**Comment by d3athrow** [comment]
well fuck

**Comment by d3athrow** [comment]
Seems i managed to fix it finally.
