### ISSUE TITLE
C-20r Magazine (12mm) does not accept 12mm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25731]
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
386474467ea5d5fc0a04040c7ce57cfd39dd9a7c

# Description
What it says on the tin.
# Steps to Reproduce

# What you Expected

# What Actually Happened
Loading bar took place, but no bullets went in. Loading single bullets by hand brings up 'the bullet casing does not fit into C-20r magazine (12mm). '

**Comment by Irradiation** [comment]
Feature. The C-20 SMG uses a snowflake kind of 12mm that stuns on hit, whereas the 12mm meant for the Assault Rifle doesn't stun and isn't compatible with the C-20 SMG.

**Comment by SonixApache** [comment]
the assault rifle ammo is 12mm special as opposed to 12mm hydrashock
