### ISSUE TITLE
box tcomms isn't connected to the grid

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#25754]
[box] [why] [and how]
#### Description of issue
here I've drawn a stunning visualisation of how the wires on Box are set up near tcomms
![image](https://user-images.githubusercontent.com/5942183/73141282-b1bb7500-4082-11ea-8ebe-9425aad65690.png)

#### Difference between expected and actual behavior
tcomms invariably loses power on Box instead of actually functioning

#### Length of time in which bug has been known to occur

honestly it's probably been this way since tcomms was reworked to how it is currently

#### Server revision

4d2a5ba161d36be983ea882a7ed73822a72206b7

**Comment by jknpj** [comment]
...check the wiring in the SMES.

**Comment by Kammerjunk** [comment]
thank you jkn
just for you, I compiled the newest version locally
yeah you're right that the wiring connects to the SMES
but not that there's no bug in the mapping:
![image](https://user-images.githubusercontent.com/5942183/73141625-715df600-4086-11ea-9dbc-4ceb46901602.png)

**Comment by Kammerjunk** [comment]
(also yes that wiring is actually connected through the airlock - but a lot of the cables in tcomms seem to be invisible)
![image](https://user-images.githubusercontent.com/5942183/73141650-d0bc0600-4086-11ea-860d-8a8def2566c2.png)

**Comment by brndd** [comment]
The wire is just under the pipe.

I've noticed that the SMES often either starts out not charging or turns off when power is not set up properly, which is why tcomms sometimes runs out of power.

**Comment by jknpj** [comment]
How did they manage to make that cable go under the piping?

**Comment by Exxion** [comment]
The problem is that the powernet is maxed out at roundstart, and SMESes only charge if there's extra power in the net
Turning up the output of the main grid SMESes fixes it

**Comment by Kurfursten** [comment]
>orange pipe going into scrubber pipe suddenly
>orange pipe and scrubber pipe possibly stacked

uhh

**Comment by Exxion** [comment]
That one *is* a problem but a separate one

EDIT: Actually that orange pipe in the door isn't connected to anything *other* than the scrubbers line
I suspect it's just a mapping mistake
The actual orange pipe line goes a tile south of that
