### ISSUE TITLE
Planning board and One Human Law

### ISSUE THREAD

**Issue by Dr-Explosion** [d3athrow/vgstation13#2576]
I put a one human law in a planning board after imputing the name of the "one human" and I'm pretty sure it bugged and cleared the name out of the law. I wasn't able to replicate the bug, so it might have been error on my part or something related to lag.

**Comment by d3athrow** [comment]
85c056a934eb7abd3b2705087e41a14e364284a4
Should be fixed but need testing.

**Comment by clusterfack** [comment]
Yes this is fixed
