### ISSUE TITLE
make the report falsifier unable to make freeform reports

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#25762]
#### Description of issue
1. the report falsifier allows any tator to rewrite any server rules regarding behaviour
2. people are allowed to act on these reports even if they say e.g. "station is anarchy you can kill everyone"
3. you cannot make any rules about the report falsifier that won't also apply to real announcements by admins
4. for that matter, it shouldn't be necessary to add a rule about one item just to ensure the server doesn't become fucking deathmatch

#### Steps to reproduce
find someone you really love or it won't count

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/028436880d6e52abe0098cd725d21bc1d4c2fcc5/code/datums/uplink_item.dm#L469

https://github.com/vgstation-coders/vgstation13/blob/199903a314416bf6766c299badad19d4753183fe/code/game/objects/items/devices/reportintercom.dm#L1

#### Server revision
f2d29742d211053555ffe8f8f16ff3fe8c657b6b

**Comment by dunsel-hordon** [comment]
Is it just time to remove that item? Or maybe increase the crystal cost to where it takes all your crystals? Not sure how much it cost right now.

**Comment by DrSnips** [comment]
Or we just do as the OP title says and it solves the issue of it being too close to admin abilities/rulings in a round.
Another idea is to make ONLY freeforms distinctly different from normal reports like a different color of text(orange or dark syndie red) and something else like gibberish on the ends or comic sans but regular reports are unchanged. This allows for syndies to still shitpost to the station if they wanted but not completely fuck rounds by false flagging.

**Comment by ShiftyRail** [comment]
The people want this item in, though. I think it's a dumb item, but there's been a sizable majority that wants it to remain in the codebase.

**Comment by SonixApache** [comment]
Maybe admin announcements just shouldn't lean towards `le epic no rules kill everyone` events, ever.

That said, changing the tool to be equal to the one malfs get, an item that lets you pick from the standard announcements rather than a complete freeform one, might be a good idea.

**Comment by DamianX** [comment]
@d3athrow what do you think?

**Comment by d3athrow** [comment]
@SonixApache rarely does that happen, or it should be rare but given people are likely too eager to take advantage of any chance to toss their humanity and submit to bloodlust it may warrant a change.

**Comment by SGuivenne** [comment]
Like 80% of the time I see this item used either nobody buys it or its used to fake an AI malf/meteor storm/ion storm announcement.  Heck I've seen it used to fake an IRA admin bus once.

**Comment by boy2mantwicethefam** [comment]
don't kneecap it like the false standard announcements because announcements are stupidly easy to determine that they are fake

**Comment by DrSnips** [comment]
Well duh people aren't going to if you press meteors and they don't hear bangs.
I see it solely to shitpost server wide for your TC but that shouldn't be causing admin level issues and here we are.

**Comment by Kammerjunk** [comment]
80% of the time I see it, it's used to turn the station into a deathmatch (whether by ancap, PVP zone, or whatever other excuse clears everyone in the game from responsibility)
20% of the time, it's used for fun stuff

**Comment by ShiftyRail** [comment]
My suggestion (that got taken down and hence I don't think it should be presented again) was to have it need some degree of cooperation between antagonists to make sure it would be something with a tiny bit of effort.

**Comment by west3436** [comment]
Make a PR with this change, if desired
