### ISSUE TITLE
Solution to the roach question

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#25779]
#### Description of issue

Roaches shouldn't be able to have any other job than civilian jobs and engineering.
It make absolutely no sense than a sentient bug would be a security officer in a corporate-state station.
They probably lack the lifespan to do the studies required for medical/science.

That's all.

**Comment by SageOfLight** [comment]
Does agreeing to this let them become playable faster.

**Comment by SonixApache** [comment]
better solution: 
remove bug

**Comment by d3athrow** [comment]
remove sonix

**Comment by boy2mantwicethefam** [comment]
vox and ayy lmaos aren't better
Down with the vox in head of staff positions, they are literally space gypsies

**Comment by ShiftyRail** [comment]
The question of CMO vox or "ayyds of staff" (more like AIDS of staff, am I right ?) is for another issue/PR

**Comment by Kurfursten** [comment]
This is terrible

Roach makes more sense in sec and sci than in service. Why would you want roaches handling your food??? Also no thank you to roach religions and roach clowns.

**Comment by SonixApache** [comment]
Sec are supposed to be able to withstand a beating, not die the moment someone looks at them funny.

**Comment by RealestEstate** [comment]
sec is supposed to die because they oppress our freedoms

**Comment by cloutcode** [comment]
> Sec are supposed to be able to withstand a beating

Plasmamen sec, diona sec, no arms no legs sec...

**Comment by ghost** [comment]
how about this:
- no bugs as head roles period
- no roaches as chef/bartender/medbay, mantids can be allowed if they pass

optional compromises:
- no vox as head roles
- only humans and dionae as sec

**Comment by SonixApache** [comment]
how about this:

- roachpeople aren't people and aren't given any rights
- they're disgusting and horrifying in any job
- people banish them to the asteroid to do slave labor

**Comment by ghost** [comment]
just because you're scared of bugs doesn't mean other people aren't allowed to have fun

**Comment by tuypo1** [comment]
Force roaches to be the less popular jobs of each department, give them the boring repetitive labor part of the department nobody else wants to do like research and development or chemistry

**Comment by salamandooo** [comment]
I love bugs and think this will be great. Bugs are gross things and walking talking ones are accidents that should not exist - this will help put them in their place. Bugs should not be equals.

**Comment by ShiftyRail** [comment]
I think bundling up the vox problems with the insectoids isn't helping to move things forwards

**Comment by west3436** [comment]
PR created and closed for this.
