### ISSUE TITLE
Endless delivery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25773]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
94e4ee25da2bbd1eb53aff5a4a26d0b19cfda7e6

# Description
Tried sending 2 crates to BAR using disposals. Packaged, labeled and sent off, only to notice the packages keep showing up in delivery.

# Steps to Reproduce
Try sending something to bar on box station

# What you Expected
Orders being delivered

# What Actually Happened
Packages making a giant circle and ending up back in delivery.

**Comment by jknpj** [comment]
There at least 3 things that can cause this and honestly the roundstart mapped setup isn't one of them.
