### ISSUE TITLE
You can emag the material synthesizer, and uh

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#25771]
It outputs any item that starts with /obj/item/device
And that includes uh
/obj/item/device/illegalradio
/obj/item/device/soulstone/gem
/obj/item/device/gps/secure
/obj/item/device/chameleon
/obj/item/device/instrument/recorder/shakashuri
/obj/item/device/pulsar
/obj/item/device/uplink
/obj/item/device/flashlight/emp
/obj/item/device/multitool/ai_detect
/obj/item/device/encryptionkey/binary
/obj/item/device/encryptionkey/syndicate/hacked
/obj/item/device/powersink
/obj/item/device/does_not_tip_backdoor
/obj/item/device/reportintercom
/obj/item/device/megaphone/madscientist
/obj/item/device/detective_scanner/forger
/obj/item/device/device_analyser/syndicate
/obj/item/device/modkit/spur_parts
But the likelihood to get any of these is still incredibly low because there are a TON of devices in the game, including the parents of those that have a parent like encryption keys and instruments and modkits, there's also every type of radio headset, PDA
The code itself only lets you emag a material synthesizer once, but you can print more if you have the materials

**Comment by PrimeDSS13** [comment]
feature

**Comment by boy2mantwicethefam** [comment]
Yes
