### ISSUE TITLE
no light on golden modified atmos hardsuit helmet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25789]
(WEB REPORT BY: badgoyguy REMOTE: 206.221.180.138:7777)
# Revision
1bf9cfcf2925c689e02de2fdf25f8ec2767c915b

# Description
when modding an atmos hardsuit into a golden atmos hardsuit with the kit in engineering on boxstation the Helmet will have no option to "Toggle Light"
# Steps to Reproduce
modify a atmos hardsuit into a golden atmos hardsuit with the kit on the table in boxstation
# What you Expected
light on my helmet
# What Actually Happened
cant see SHIT

**Comment by MadmanMartian** [comment]
IT'S A FEATURE

**Comment by Kurfursten** [comment]
Literally a feature, gold atmos modkit is your ticket to the past

**Comment by SonixApache** [comment]
Stick a tactical light on it 🙂

**Comment by west3436** [comment]
Feature (it's a relic)

**Comment by west3436** [comment]
Disregard my previous comment as it does have a light now!
