### ISSUE TITLE
MoMMI's keeper flag

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#2578]
Best bet this has to do with new TG shit fucking with the var.

When a mommi has a different lawset other than keeper, their keeper var is set to 0, which allows them to speak regularly and, in turn, disabling damage control.

So i was on paladin law set and could only talk on damage control.

After ahelping find out if the keeper var was set to zero or not it was set to zero and i could not talk normally.

**Comment by IratePirate** [comment]
Can we have people properly bugtest before porting TG stuff to avoid stuff like this?

**Comment by ririchiyo** [comment]
Since no-one used the test server, we have to do testing on the actual live server and that's why it runs BE instead of master.

**Comment by AutismSpider** [comment]
So whats going on with this.

Is the TG Chat stuff making the flag bug out or what?
