### ISSUE TITLE
Unable to pick up objects when missing a leg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25801]
(WEB REPORT BY: gunosaguki REMOTE: 206.221.180.138:7777)
Bought a viscerator grenade when i was missing a grenade thanks to having an uplink implant, unable to pick up the grenade because of ???? that or it considered me still handcuffed despite freedom implanting

**Comment by Gunosaguki** [comment]
When missing a leg, whoops.

Also, the leg was lost from matter eater from someone else, I broke free from their third grab attempt which may have bugged it out?

**Comment by ShiftyRail** [comment]
You can't pick up objects at all when you are lying sideways, which is most probably the case if you've lost a leg.

**Comment by Gunosaguki** [comment]
seems like an oversight still, as why would lacking a leg prevent you from grabbing things?

**Comment by ShiftyRail** [comment]
Lying sideways has always prevented you from doing anything. (except crawling, and that's relatively recent)

**Comment by ghost** [comment]
Please respond as to whether your sprite was horizontal during this as that would confirm it's not a bug.

**Comment by Gunosaguki** [comment]
It was horizontal, if it is in fact intentional oh well. a bit strange but if its not abug then I have no problem with it

**Comment by Exxion** [comment]
See #16962
