### ISSUE TITLE
(Packed?) Derelict Shard Area Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25803]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
9b2511f9c61d70d99053697419373810ee62d877

# Description
There is a lot wrong with the tiles bordering the hole in the derelict station that contains the supermatter shard box. Floor tiles are there but invisible, and wire laid on these tiles disappears
# Steps to Reproduce
Crowbar up invisible tiles. Lay wire until some segments start disappearing
# What you Expected
Not shit
# What Actually Happened
Shit

**Comment by Kharkov72** [comment]
thank you duny
