### ISSUE TITLE
my little foam extinguisher can't possibly be this broken

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#25808]
#### Description of issue
you all know it: foam extinguishers are really dumb and I don't think they even care about things like mols or pressure
pic underneath happened in like 2 seconds
![image](https://user-images.githubusercontent.com/5942183/73877868-c0abdf80-4859-11ea-93ec-b7a15b066b28.png)
you shouldn't get niggawatts without working for them

foam does have a var called `lowest_temperature`, but it's set to 0.

**should it be different? what should it be?**
and since people will apparently still sperg even though this is an issue in which I outline what I think is dumb and ask what people think:
*I* think it's really stupid to be able to hit 1 K with a foam extinguisher and 1 GW with a single supermatter shard and 3 emitters. Space cooling with H/E pipes can only take you to about 12 K and I understand that people do want to hit 1 K and that's fine I guess (mind that the power increase from 12 K to 1 K is *MASSIVE*), but it shouldn't be this easy.

#### Specific information for locating

https://github.com/vgstation-coders/vgstation13/blob/f688d318d179487441a67c0be86fb7247b88f711/code/game/objects/effects/effect_system.dm#L707
#### Server revision

9b2511f9c61d70d99053697419373810ee62d877

**Comment by GelatinousGlob** [comment]
It would be nice to have something to replace this then because it is practically impossible to freeze gas down like that even with fully upgraded coolers. It already took like an hour and a half to fill up a single can worth of gas that cold with the extinguisher.

I also feel like 0C will be useless at stopping fores but ill have to test it.

**Comment by Exxion** [comment]
That comment would be more fitting on the PR than this issue
Also replacement coming Soon:tm: (probably within a few days but I've been busy)
