### ISSUE TITLE
bar drink sprites are fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25819]
(WEB REPORT BY: awsmnamedude REMOTE: 206.221.180.138:7777)
# Revision
24301c198fc16dd412f35ff37e213d2e09e8c0d2

# Description
BAR DRINKS SPRITES ARE FUCKED SINCE NEW BAR DRINKS WERE ADDED
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment]
very easy to work with

**Comment by DamianX** [comment]
brian damag
