### ISSUE TITLE
Using light switches restarts emagged jukebox's song

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25817]
#### Steps to reproduce
- Be spessman
- Emag jukebox and start playing a song
- Flick the light switch
- The song just restarts??

#### Specific information for locating
why does this code exist
```
/obj/machinery/media/jukebox/power_change()
	..()
	if(emagged && !(stat & (NOPOWER|BROKEN)) && !any_power_cut())
		playing = 1
		if(current_song)
			update_music()
	update_icon()
```

**Comment by Exxion** [comment]
I guess it's supposed to turn on automatically?

**Comment by Kurfursten** [comment]
This is so magical I think it should be preserved as a symbol of how broken and janky emags make things they hack

**Comment by ghost** [comment]
its a feature, it allows ghosts to keep shitty songs playing on loop by flicking the light switch

**Comment by SonixApache** [comment]
wiring issue
http://www.catb.org/jargon/html/magic-story.html
