### ISSUE TITLE
Thermoelectric Cooler

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#25818]
I'm probably going to code this, but I'm making an issue here first for discussion and also in case I don't.

Currently, there's no legitimate way to get gases below 6.4K, and no way at all to get them below 1K. This is because we have no active means of heat transfer at all. In reality, active heat transfer is usually achieved through thermodynamic effects of compression heating/cooling and phase change. We don't have any of that, and it's not simple to implement.
What is (relatively) simple to implement is just a powered heat pump atmospherics component. My general plan goes like this:
* Pumps heat from one pipeline to another (like the heat exchanger but active)
* Has a maximum possible temperature difference between the cold side and the hot side
  * This temperature difference depends on the absolute temperature of the cold side, so the maximum difference is smaller the closer you get to absolute zero
* Consumes a constant amount of power and moves a variable amount of heat
  * Always less efficient than the TEG, so no infinite power memes
    * It could still be used to get big numbers on the TEG interface if that's what you want, but doing so would reduce the *net* production
  * Amount of heat moved per tick depends on the current temperature difference and the maximum temperature difference, so that in the absence of other effects it asymptotically approaches the maximum difference

Note that (if it's coded properly) you could get arbitrarily close to absolute zero with this device by building a multi-stage setup. Each stage would reduce the temperature by less than the last and do so more slowly, but there's no *hard* limit on how cold you can get. It asymptotically approaches absolute zero as the number of stages increases.

**Comment by DrSnips** [comment]
Sounds like a fun and cool[ing] concept except for that fact that it also sounds completely useless and a waste of time because, assuming what you say is correct in the final product, will produce less power than it takes to preform. On top of that my 5th dimensional brain already saw into the future with people saying it should be gated behind research and me posting "if its going to be behind research I can already make big numbers for a fraction of a second just to make my railgun caps. without this dumb machine and wasting less of of my time."

**Comment by Exxion** [comment]
It produces less power than it uses if you're just running it into the TEG. This is not the primary use for supercooled gases, which can be used in radiation collectors, bombs, etc. for a much larger benefit than the TEG.

**Comment by DrSnips** [comment]
I guess you can for other methods. I just pray to god its a round start machine sitting in atmos unlinked without any research bullshit. You know if you throw it in there it will never see the light of day.

**Comment by Exxion** [comment]
I meant as just another component in the RPD
