### ISSUE TITLE
Episode number in the credits is null

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25815]
or something like that

![image](https://user-images.githubusercontent.com/6307265/73924999-a01d6d00-48cd-11ea-86fe-0f8288238411.png)

it's been happening for a while according to anon
![image](https://user-images.githubusercontent.com/6307265/73925048-b9beb480-48cd-11ea-9cd7-cc4aed3f2b6f.png)

**Comment by PrimeDSS13** [comment]
for as long as it's been season 20

**Comment by ghost** [comment]
is #24380 to blame? doesn't look like the `"data/persistence/round_counts_per_year.json"` exists ever.

**Comment by DamianX** [comment]
That PR wasn't merged though?

**Comment by DamianX** [comment]
It must be something with #22580.
Calling `SSpersistence_misc.read_data(/datum/persistence_task/round_count)` on pomf's serbian yields a puzzling `19 = "341"`.
Why is it 19?
