### ISSUE TITLE
Deficiency disposal deliveries not working

### ISSUE THREAD

**Issue by invoid9** [d3athrow/vgstation13#2582]
It seems when you send crates through disposals for delivery, they end up on the surgery maintenance door. There may be a missing pipee

**Comment by Duny-** [comment]
I'm not going to fix it. Fuck off with your criticism my map is perfect.

**Comment by Duny-** [comment]
Found the missing pipe, I probably didn't notice it under the door when I added overflow. Will push a fix soon.
