### ISSUE TITLE
Screwdriver sounds are just weird clicks half the time

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25822]
(WEB REPORT BY: dacendeth REMOTE: 206.221.180.138:7777)
# Revision
b8af45303390f398912b98331ff36dc5f59b2a4b

# Description
Screwdriver noise makes some click when screwdriving windows half the time, probably other stuff.
# Steps to Reproduce
Screwdriver something
# What you Expected
Nice screwdriver noise
# What Actually Happened
sometimes weird click, sometimes nice screwdriver noise

**Comment by jknpj** [comment]
sound/items/Screwdriver2.ogg

**Comment by ghost** [comment]
this isn't a bug so if you think the sound should be changed you can go right ahead
