### ISSUE TITLE
Atmos Pipe issues

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#25858]
Compare the mass colored pipes from this picture from today (Fed 16, 2020)
![2020 piping](https://user-images.githubusercontent.com/5549060/74627093-680cfa00-5117-11ea-9cde-7092fc0e8b66.png)
with this one from April 2, 2019
![TEG 2019](https://user-images.githubusercontent.com/5549060/74627217-c9cd6400-5117-11ea-8981-a39f4ad6dac6.png)

I blame #25192 or #25193

- Manifolds (3 and 4 directions) cannot be painted
- Pipe adapters cannot be painted

also
- Manifolds cannot be secured over top vents/scrubbers, but this works vice versa.

**Comment by DeityLink** [comment]
Is this still occurring?

**Comment by kernikov** [comment]
no.
