### ISSUE TITLE
Alien revolver(?) invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25854]
(WEB REPORT BY: neonphile REMOTE: 206.221.180.138:7777)
# Revision
f6c4dfcdec9131ecbca3b7dd4b8be5dfa659143d

# Description
This weird alien revolver thing the xenoarch found is invisible on the ground and on the UI, visible in-hand.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
Missing or incorrectly-named `icon_state`
