### ISSUE TITLE
Rocknuts force and throwforce isn't scaling at all

### ISSUE THREAD

**Issue by RealestEstate** [d3athrow/vgstation13#25867]
what the title says. whichever idiot coded them fucked something up.

**Comment by Exxion** [comment]
For some fucking reason, the code that sets the thing's `potency` in `New()` is `spawn()`ed off and doesn't happen until after the code that should set the `throwforce` based on it has already executed

**Comment by RealestEstate** [comment]
is it in initialize()?
that’s where the rest of the grown food has its forces defined based on thorniness and etc. What I might do is put a conditional in initialize to check if the src is a rocknut and use the potency scaling formula instead if true.

**Comment by Exxion** [comment]
1. The rocknut does it in `New()` instead
2. Never ever do typechecks on `src`

**Comment by boy2mantwicethefam** [comment]
The rocknut fanbase is dying, hit the like button if you're truly rock hard

**Comment by RealestEstate** [comment]
yeah I know there’s a throwforce define in its New(), the problem is it’s being called too late right? wouldn’t the solution be to place the check in initialize()? I wouldn’t be type checking since that is a big no no, I’d be overwriting initialize for rocknuts specifically and so on and so forth

**Comment by Exxion** [comment]
Again, `initialize()` is spawned off, so putting it in a child would not work
I'd just remove the `spawn()` from the parent but maybe it's there for a reason

**Comment by DamianX** [comment]
Do it, remove it and let's see what happens.
