### ISSUE TITLE
[Bug] Powernet shutdown doesn't work properly

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2587]
A random event powernet shutdown on metaclub only disabled power in some sections temporarily.  When I moved from medbay to arrivals to fix breaches I found that the power was still on, apcs were still charging and everything was just fine.  The event was still active and the power was 'restored' despite being already on a few minutes later.

**Comment by clusterfack** [comment]
Yeah I saw a similar thing happen on box. I'll have to check and see exactly why.

**Comment by clusterfack** [comment]
It seems when an engine is wired directly into the grid, a random number of about 5-10% of apcs set themselves back to charging mode during the power failure event.

**Comment by Probe1** [comment]
During the times I've seen this occur, the solars were wired to the grid (which supply sufficient power to run the station on their own).  So that lines up, every time I've seen it happen there have been engines wired in directly.
