### ISSUE TITLE
Able to Request Priority Roles When They Are Set

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25886]
(WEB REPORT BY: thatredpyro REMOTE: 206.221.180.138:7777)
# Revision
2a19bb49cc411ab7185bad373e03ed644601f814

# Description
You can request high priority jobs even when there are some already set if you had the join screen opened before they were set, making you able to possibly ping all round.
# Steps to Reproduce
Open the late-join panel when nothing is requested
Press Request high priority Jobs
Someone IC requests certain Jobs
Press the same request button again
# What you Expected
Being unable to ping for priority jobs
# What Actually Happened
Having the ability to be an annoying cunt, probably

**Comment by ThatRedPyro** [comment]
Here's the proofs because you can't attach pics through the bug report function or I'm dumb.
![a](https://user-images.githubusercontent.com/52574273/74967549-4454f700-542a-11ea-8b2f-ef20f22f1223.png)
