### ISSUE TITLE
Mech Bay Power Control Console doesn't glow

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25899]
(WEB REPORT BY: gibbi600 REMOTE: 206.221.180.138:7777)
# Revision
8ff8703263072dc377ce53cda5fe0abadf98566c

# Description
the title

# Steps to Reproduce
Turn off lights in mechbay

# What you Expected
soft purple light

# What Actually Happened
dark room

**Comment by DeityLink** [comment]
Fixed by one of the recent moody lights PRs
