### ISSUE TITLE
Blindness bug?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25900]
(WEB REPORT BY: neonphile REMOTE: 206.221.180.138:7777)
# Revision
8ff8703263072dc377ce53cda5fe0abadf98566c

# Description
Aug eyes blinded by EMP, I did use a welder while blind on my limbs because fuck it right? And now my eyes are replaced and I'm still blind.

# Steps to Reproduce
Be blind from shard delam, use welder on self until blind message displays again(?)

# What you Expected
Being able to see
# What Actually Happened
Not being able to see

**Comment by Dacendeth** [comment]
probably had genetic blind still, take some rye. still kind of odd eye replacement doesnt fix that though.

**Comment by DeityLink** [comment]
I'm pretty sure you need to multitool them to undo the EMP scrambling. A surprisingly little known fact.
