### ISSUE TITLE
[Metaclub] Maint door to engineering does not require engineering access

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2590]
There's a goddamn door in engineering with only maint access requirement so everyone and their maint loving mother can walk right in, diddle the singlo and touch engineers precious gloves.  This is an outrage.  

Its the door on the NW side.

![image](https://cloud.githubusercontent.com/assets/8550416/5845963/3a6d876a-a18e-11e4-936d-6fdafb3a3191.png)

**Comment by ComicIronic** [comment]
Very typical issues with maint doors.

**Comment by IratePirate** [comment]
Are there any other examples of this you can pinpoint?

**Comment by Probe1** [comment]
nope, issue was brought up IC during a round and I made a note of it after checking on a test server to ensure it was there.  i'll post an issue immediately if I find any.

**Comment by IratePirate** [comment]
Cheers brah.
