### ISSUE TITLE
NanoUI shows just background, then becomes blank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25910]
(WEB REPORT BY: gibbi600 REMOTE: 206.221.180.138:7777)
# Revision
b82f654b1da2d294b74d0ccf58967783d98f2c56

# Description
"Advanced" NanoUIs like Cargo Console and PDA console don't show anything but the background N letter (Merch computer works though). After a minute or so ALL external GUIs become white blank.
So far I tried
1) Resending resources
2) FixNanoUI
3) Clearing BYOND cache
Gonna try:
1) Reinstalling BYOND
2) Google

# Steps to Reproduce
No idea. Could be client-side. On my self-host server Cargo Console brings an error "Cargo-console.tmpl not found".

# What you Expected
Working Cargo Console

# What Actually Happened
Lost all ability to read, write and operate machinery

**Comment by ghost** [comment]
Reinstalling didn't help. 
Whew, okay, it's seems to be dark preset problem. I switched back and forth and it all works now.

**Comment by ghost** [comment]
Out of curiosity, what OS are you using?

**Comment by ghost** [comment]
Win10 Education

**Comment by DeityLink** [comment]
Duplicate of #26957
