### ISSUE TITLE
[Metaclub] AI minisat SMES is improperly configured and causes power failure if unaddressed

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2591]
The SMES needs to be set higher than 50,000 or else power will not charge on the minisat, stranding the AI and causing issues.  Since the minisat is isolated from the main stations powernet its dependant on the one small solar which must be set to rotate immediately at round start and the SMES output must be increased in order to power the entire minisat.

This could use some fine tuning to make it more user friendly by increasing the SMES output and having the solar set to automatic rotation at round start.

**Comment by IratePirate** [comment]
I've increased the SMES output.

The var for the solar computer to automatically track is unknown to me, i've gone through the list several times. If anyone else has any idea it'd be nice to know.

**Comment by Probe1** [comment]
Fixed in  #2595
