### ISSUE TITLE
Regular ghosts can access fax commands

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25919]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
523c8e97d4d0a3c33d5a2e8875ef8848ea3ba914

# Description
A command tab appears when you get near a fax machine as a ghost

# Steps to Reproduce
1- Ghost
2- Find a fax machine
3- Put your sprite near it
4- Watch the command tab pop up

# What you Expected
Nothing tbh

# What Actually Happened
I wonder if I can fuck with IAA using this

**Comment by ghost** [comment]
Fixed #35710

**Comment by west3436** [comment]
Fixed via #35710
