### ISSUE TITLE
Shunted AIs show up on the lobby crew manifest

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25927]
(WEB REPORT BY: mxr41 REMOTE: 206.221.180.138:7777)
# Revision
9e20b09cdb1324809e7349192e91b9aebff16779

# Description
https://i.imgur.com/ToiyHrf.jpg
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by SECBATON-GRIFFON** [comment]
fixed by #32797
