### ISSUE TITLE
[Metaclub] No pipe wrenches or RPDs in Atmos and Engineering has no metal

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2592]
Add autismos lockers with RPDs and Pipe Wrenches.  Add extra RPDs in Atmos on a table.  

The metal sheet stacks in engineering have 1 sheet each instead of 50.
![image](https://cloud.githubusercontent.com/assets/8550416/5849758/e47b2270-a1b7-11e4-8c33-25ecd5e6d0a2.png)

**Comment by IratePirate** [comment]
Holy crap.

Will fix.

**Comment by Probe1** [comment]
The pipe wrenches were added, which are great.  The atmos lockers didn't get added.  The RPDs in engineering department are still at 2, one in atmos and one in the CEs room.  

Try to add more lockers and another RPD on the table please.  5 (including the CEs) is the magic number.
