### ISSUE TITLE
Deleted Items non-Vox Raider

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25922]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
523c8e97d4d0a3c33d5a2e8875ef8848ea3ba914

# Description
Items on and in hand deleted on return to  home base as non raider
# Steps to Reproduce
Get on Vox raider skipjack and use the raiders ID to go to their home base.
# What you Expected
To arrive at vox raider home base
# What Actually Happened
When it arrived all the items on me and in hand were deleted and my id and a station bounced radio were put in my hand and all my gear was gone.

**Comment by ShiftyRail** [comment]
That's because non-vox aren't supposed to use the ID to get back to the base, since there's nothing to explore here. Only raiders are supposed to use that button.
