### ISSUE TITLE
non-ascii characters show up as garbage on BYOND 513.1511

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#25929]
#### Description of issue
![image](https://user-images.githubusercontent.com/6307265/75500576-b189fe80-59cd-11ea-93f8-b77136e80f89.png)

presumably has something to do with byond supporting utf8 internally now

paging dr @PJB3005

**Comment by DamianX** [comment]
actually it seems to break only for things said by players
![image](https://user-images.githubusercontent.com/6307265/75500779-3d9c2600-59ce-11ea-9207-6daaf1bb2e85.png)

**Comment by Exxion** [comment]
Yeah, it's presumably input, not output

**Comment by PJB3005** [comment]
It's input. Have the code skip the libvg conversions if it's running on 513.

Also maybe a good idea to remove uses to libvg UTF-8 functions like used by telecomms.

**Comment by Exxion** [comment]
The problem is that the input change is clientside.
We could just update to 513 and require players do the same

**Comment by DamianX** [comment]
We could check for the BYOND version of the client at runtime but I don't see the point of supporting 512. I say update to 513.

**Comment by SonixApache** [comment]
isn't 513 still in dev?

**Comment by Exxion** [comment]
So was 512 when we required it
And 511 probably but I don't remember
And probably many before that
