### ISSUE TITLE
Botany is kinda broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25937]
(WEB REPORT BY: luzzgawr REMOTE: 206.221.180.138:7777)
# Revision
26cf227e3ccd1c41f1bdff3879c5f38eb3802739

# Description
Several rounds have been spent splicing and purging potency and different properties into plants, only to find that it does absolutely nothing. Trying to purg condense capascin into chilis from ghost chilis, for example, will result in the normal capascin. Ive also seen other botany peeps talk about this issue, that potency isnt increasing the chems in certain plants they are making
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
[Unforeseen Consequences]

**Comment by KingofHONK** [comment]
oh also- splicing is fucked too.
