### ISSUE TITLE
Washing your hands as a gray does not do anything besides washing your hands

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25934]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
9e20b09cdb1324809e7349192e91b9aebff16779

# Description
what happened to that weakness to water huh if you dipped your hands into a ceramic bowl of acid you'd be like "ow ooof my fingerrrs"
# Steps to Reproduce
Wash hands as gray in sink without gloves on
# What you Expected
Horrible mutilation of my digits
# What Actually Happened
My hands were cleaned and my emulsions were devastated

**Comment by tayachiya** [comment]
This raises an important question - what about swirlies? Can simple bullying procedure be turned into horrible torture for greys?

**Comment by Dacendeth** [comment]
@tayachiya that's already a thing.

**Comment by SonixApache** [comment]
swirlies kill the shit out of grays

someone tried to fix the hands washing thing but then made it so it went *through gloves* which then didn't pass
