### ISSUE TITLE
I turned a thermoelectric cooler on as a ghost, apparently

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25933]
(WEB REPORT BY: mentgah REMOTE: 206.221.180.138:7777)
# Revision
9e20b09cdb1324809e7349192e91b9aebff16779

# Description
see title
# Steps to Reproduce
click on a thermoelectric cooler as a ghost
# What you Expected
to not turn it on
# What Actually Happened
i turned it on

**Comment by Exxion** [comment]
I'm 99% sure I tested this

**Comment by Exxion** [comment]
Yes, I definitely remember testing this, but apparently somehow broke it after doing so
