### ISSUE TITLE
Your nose starts bleeding as a race with no blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25942]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
dffa253d1b5ecdbf13785fa12b7be3b6ce1a9be7

# Description
Whatever causes this caused it. Braindamage? I had that.
# Steps to Reproduce
Do whatever causes this message as a race with no blood
# What you Expected
No message
# What Actually Happened
Bled

**Comment by Kammerjunk** [comment]
https://github.com/vgstation-coders/vgstation13/blob/f5f606205415903fe654e5521e2b3efc038571fb/code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm#L133

**Comment by Kreyfag-the-social-african-american** [comment]
`			if(anatomy_flags != NO_BLOOD)	
				if(prob(15) && drip(1))
					to_chat(src, "<span class = 'danger'>Your nose starts bleeding!</span>")`

**Comment by Kreyfag-the-social-african-american** [comment]
This should fix it I believe.
https://pastebin.com/mCA6GWGr

**Comment by Kreyfag-the-social-african-american** [comment]
> This should fix it I believe.
> https://pastebin.com/mCA6GWGr

vgstation13/code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
In here
