### ISSUE TITLE
botany is STILL broken bro

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25950]
(WEB REPORT BY: luzzgawr REMOTE: 206.221.180.138:7777)
# Revision
https://media.discordapp.net/attachments/675531244552847367/683847016924708897/stillbustedbro.png?width=991&height=543

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by PrimeDSS13** [comment]
good description

**Comment by Exxion** [comment]
It's just
1. Inedible grown items
2. Rocknuts
3. No-fruits

Because I somehow didn't think to check if the one fucking reason I was uncomfortable with my previous fix might possibly actually break things

Anyway I have code that should fix it but I haven't tested yet
