### ISSUE TITLE
Honk serum isn't fixing mime curse.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25965]
(WEB REPORT BY: pancakemines REMOTE: 206.221.180.138:7777)
# Revision
99a7c3a156bc3c589c9c7dbd5198c4dd989f4884

# Description
Guy was mimed gave him increasing units of honk serum to try and fix it no results. 3,5,13,30,50 none worked. Person in question was a plasmaman not sure if that would be a factor.

**Comment by ShiftyRail** [comment]
:thinking:
