### ISSUE TITLE
cr20 magazines cannot be loaded

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25969]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
143e2d359e9b8c71b921cac7f9457395a9c08929

# Description
cr20 magazines printed from the ammolathe cannot actually be loaded with 12mm bullets. Any ammo type can initiate a loading progress bar but the magazine remains at 0 rounds upon completion.
# Steps to Reproduce
Print a cr20 magazine from the ammolathe and try to load it.
# What you Expected
cr20 magazines should be loaded with 12mm rounds and reject other ammo types.
# What Actually Happened
cr20 magazines accept other ammo types but cannot actually be loaded.

**Comment by Irradiation** [comment]
CR20 magazines take a snowflake version of 12mm that can't be interchanged with the regular science/ammolathe 12mm.

**Comment by yackemflam** [comment]
Why?
Why not just let them load into each other?

**Comment by SonixApache** [comment]
C20rs use longer boolets :)

**Comment by west3436** [comment]
Feature
