### ISSUE TITLE
janicart bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25974]
(WEB REPORT BY: tornader REMOTE: 206.221.180.138:7777)
# Revision
143e2d359e9b8c71b921cac7f9457395a9c08929

# Description
can use the janicart without needing the key
# Steps to Reproduce
pick diona, get critted while on janicart with the key, heal up, don't need the key anymore
# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
You sure the key wasn't just in the cart?
