### ISSUE TITLE
[Balance Discussion] RPDs/Autolathe items printed by General Fabricators are not cost effective

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2597]
Taking RPDs as an example, a General Fabricator in the Mechanics Office requires in addition to nanopaper and scanning the RPD (resource is time):
3024 Iron | 1080 Glass | 691 Plasma | 259 Gold | 505 Plastic.  

Conversely, a hacked Autolathe can build an RPD with:
75000 Iron | 37500 Glass

The math just doesn't add up.  You would have to get resources from miners, plastic from botanists, scans and use up your precious nanopaper just to print something an autolathe can cheaply manufacture.  Why do General Fabricators have a steep resource cost and does anyone have an argument against bringing them in line with an autolathes material costs?  The only advantage a General Fabricator holds is you can queue an item instead of waiting for it to be produced first before beginning the next production style like an Autolathe.  

Discuss.

**Comment by Duny-** [comment]
Consider the following:
Remove the autolathe, give everything it had to general fabricators, lower the costs a bit. Mechanics are now useful for something. Maybe do the same with the protolathe and make it so mechanics can help do research or whatever.

Now consider the other following:
Remove mechanics as they are redundant and pointless.

**Comment by Probe1** [comment]
Mechanics seldom use the general fabricator for benign things that autolathes are used for.  Mostly I see general fabs being used to pass produce hand teles or something questionable.  Part of that falls on the resource costs for general fabricators being cost preventative and it being much more effective to scan an autolathe, build a flatpack and have your own autolathe.

Removing autolathes, protolathes or general fabricators is a big change that would require significant rebalancing of the entire RnD path and the game in general.  I'm more interested in making a few small changes instead of throwing the whole thing into the wind.

**Comment by Riukanojutsu** [comment]
Just so you know, upgtading the general fab makes stuff cost way less. unupraged general fab is useless but once upgraded its pretty good

**Comment by Probe1** [comment]
There wasn't enough agreement with my point of view and I'm closing this now.
