### ISSUE TITLE
Add airlocks/emergency vents to the gas miner chambers.

### ISSUE THREAD

**Issue by coronasaurus** [d3athrow/vgstation13#25979]
[box][featurerequest]

I think it would be nice to have airlocks on the backside of the gas miner chambers so you can enter them without removing the windows and grille. Or emergency vent shutters like the Mixed Air chamber has would be nice, too.
I think one other map has airlocks for the gas miners so you can go in but I don't remember which one. Also the derelict station gas miners have airlocks, too.

**Comment by SonixApache** [comment]
deff has this
