### ISSUE TITLE
Summon Pitbulls is just totally missing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#25986]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
0d9a95e2d29855159e013eb9ed4b89b0b55e697e

# Description
Its not available in the spellbook or the givespell list
# Steps to Reproduce
try to give self summon pitbull
# What you Expected
learn summon pitbull
# What Actually Happened
pitbulls not available, probably too busy mauling children to death

**Comment by Kammerjunk** [comment]
yeah you kinda forgot to add the new files to the DME

**Comment by Kammerjunk** [comment]
@RealestEstate

**Comment by SonixApache** [comment]
leave it as-is, it's fine

**Comment by RealestEstate** [comment]
how in the fuck

**Comment by Exxion** [comment]
Kammer said right above how

**Comment by RealestEstate** [comment]
ready to be closed
