### ISSUE TITLE
[Bug] Could not remove biomass from Rwindow

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2598]
On Metaclub yesterday biomass got out of control and took over the escape/Aft Primary Hallway.  After removing a lot of it I got to the Robotics RWindow (4 RGlass panes, a full RGlass window and a grill).  There were also two RTables adjacent to it.  Once I sorted out the tables, I could not use a welder to remove the biomass from the window. I couldn't disassemble the window with a screwdriver either!  I couldn't click on the tile at all, making it impossible to remove.  

Wasn't someone working on something to prevent the spread of biomass and kudzu through windows?  If that fell through, can we somehow make Biomass and Kudzu be "on top" of other objects in a tile so it can be removed without disassembling the window?  That aside, there was some kind of bug there.  I couldn't remove the window because of biomass but I couldn't remove the biomass because of a window.  This will probably be a bitch to test further.

Tile in question -

![ss 2015-01-21 at 08 41 10](https://cloud.githubusercontent.com/assets/8550416/5862377/6fed144e-a23f-11e4-829a-c822ffbbaa7c.png)

**Comment by ComicIronic** [comment]
Did you attempt to use the altclick menu?

**Comment by Probe1** [comment]
Yeah, I could not bring the alt click menu up when clicking on the window directly or trying to pixel snipe the nearest possible floor which sometimes works.  Wouldn't do it.

**Comment by Probe1** [comment]
will reopen if it recurs, I believe it was a mapping issue that was rectified.
