### ISSUE TITLE
Mice can't emote, mice can be understood by humans

### ISSUE THREAD

**Issue by vgrainicorn** [d3athrow/vgstation13#2600]
How to reproduce:
mouse (159) squeeks, "Can you understand me human?"
Jackson Manchester says, "I can"
mouse (159) squiks, "That's terrible"

How to reproduce:
1. Try to emote
2. It doesn't work

**Comment by ririchiyo** [comment]
I'm not really sure I want to fix the emoting, but it shouldn't be heard by humans anymore.

**Comment by ComicIronic** [comment]
Since I believe mice emoting was deliberately left out to prevent it being used for communicating, this is closed.
