### ISSUE TITLE
Non-Clumsy Officer able to use Energized Bananium Sword

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26003]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
be0273017311d5b539fd746e8c28e7887107af0b

# Description
Traitor clown buys invisible spray, Energized Bananium Sword. Invisible traitor clown attacks a security officer. Clown gets tazed and falls over, dropping the sword. Security officer picks up the sword and kills the clown with it. The officer did not have clumsy. 
# What you Expected
The officer being unable to use the sword.
# What Actually Happened
The officer slays the clown with the sword.

Logs at 10:27-ish at 3/17/2020

**Comment by boy2mantwicethefam** [comment]
Implying officers aren't clowns

**Comment by PrimeDSS13** [comment]
this might not be a bug, I might just be stupid.

**Comment by PrimeDSS13** [comment]
okay it turns out this is a feature, and only the twin-bladed banana sword is clown only.
honestly the one handed sword should probably have a similar effect.
