### ISSUE TITLE
Ship Build Don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26017]
(WEB REPORT BY: haligue REMOTE: 206.221.180.138:7777)
# Revision
f6e03d732a849c094e549aab10a46470334325f7

# Description
I tried several times, in several maps, with several sizes, to build a shuttle and make it go anywhere. I failed all times. I try to move it to any location, it send the message that its moving, it activate the engines and nothing happens. Admin said he receive this message all time I try to activate the shuttle "ADMIN LOG: WARNING: A shuttle (Armoured Shuttle; /datum/shuttle/custom) has attempted to move to a location which overlaps with its current position. The shuttle will not be moved."

# Steps to Reproduce
Build a shuttle at space, try to move it.

# What you Expected
It to move.

# What Actually Happened
Not moving.

**Comment by ShiftyRail** [comment]
dupe
