### ISSUE TITLE
no age restriction for becoming a borg midround

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#26013]
#### Description of issue
cyborg has a minimum age requirement of 10
last round, I saw a borg with a player age of 2.
when the borg died and ghosted, it was a posibrain.

presumably, the minimum age restriction doesn't count things like being manually placed into a silicon shell.

#### Difference between expected and actual behavior
people who are so new that they can't possibly be expected to know the nuances of laws can become silicon roles despite not being supposed to

#### Steps to reproduce
seize the means of reproduction

#### Specific information for locating

https://github.com/vgstation-coders/vgstation13/blob/e603182c409877ff384caba0d4afe988c810ab17/code/game/jobs/job/silicon.dm#L30

#### Length of time in which bug has been known to occur

probably forever, honestly.

#### Server revision

45f86bad83ef8acb1674171915208b09b08bd2f5

**Comment by cloutcode** [comment]
these damn underaged posibrains keep showing me fake IDs during my roboticist rounds

**Comment by Kammerjunk** [comment]
tell it to the judge
