### ISSUE TITLE
Can't spawn as diona if observing

### ISSUE THREAD

**Issue by vgrainicorn** [d3athrow/vgstation13#2601]
1. Enable diona role
2. Observe after roundstart
3. Diona pods spit out braindead nymphs

It works correctly if after observing you become a mouse and then ghost.

**Comment by clusterfack** [comment]
I fixed this when I fixed special roles a while back.

**Comment by ComicIronic** [comment]
Name the PR, and I'll close it.

**Comment by clusterfack** [comment]
https://github.com/clusterfack/bugfixstation13/commit/d8fa66d77c9a082ef9a29661c1e7ccf2361aeb44

**Comment by ComicIronic** [comment]
Fixed in #2685, reopen if still an issue.

**Comment by clusterfack** [comment]
It's... still open
