### ISSUE TITLE
AI UI has unremovable entertainment module buttons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26015]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
600713bdc9fb4090a2bd668f5135baa70e7ab9b4

# Description
When playing AI, clicking on an entertainment monitor puts the usual buttons on your HUD but you can't remove them (you can't even watch what's on the monitor, what a joke). If you click on a different monitor, it puts that monitor's buttons on your screen too. This can get out of hand.
# Steps to Reproduce
1. Be AI
2. Click on entertainment monitor.
3. Be dissapointed you can't watch the admins fuck around with chaplains and cultists in the 'dome
4. Click on another monitor
5. Repeat until half of screen is unrecognizable.
# What you Expected
To watch admin fuckery
# What Actually Happened
Buttons

**Comment by cloutcode** [comment]
![image](https://user-images.githubusercontent.com/51810865/77200973-a7818a00-6ab9-11ea-9d4f-912db960803c.png)
Resetting doesn't fix it. Pain.

**Comment by cloutcode** [comment]
Thankfully when you reset it gives you the option to hide the buttons

**Comment by gurfan** [comment]
AIs can't use the entertainment monitor anymore, and I thi the monitor uses tgui now anyway, this can be closed
