### ISSUE TITLE
Cannot use MoMMI modules

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26029]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 206.221.180.138:7777)
# Revision
781de7156feacfc4425eed8f8463861224eb8c07

# Description
Self-explanatory- clicking the module panel endlessly repeats the "select an appearance" dialog

# Steps to Reproduce
Be a MoMMI, try to use a module

# What you Expected
Module list pops up

# What Actually Happened
See description.

**Comment by icantthinkofanameritenow** [comment]
Disregard the above, turns out I'm just an idiot. Consider this issue closed.
