### ISSUE TITLE
Snaxi Advanced Security Cameras console's cameras don't line up with map

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26028]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
781de7156feacfc4425eed8f8463861224eb8c07

# Description
It looks like the map's smaller than it's supposed to be or something
# Steps to Reproduce
Be on Snaxi and use Advanced Sec Cams
# What you Expected
Reasonable
# What Actually Happened
Not reasonable

**Comment by cloutcode** [comment]
![image](https://user-images.githubusercontent.com/51810865/77264099-ad1cd280-6c67-11ea-83f9-6d7b79b854be.png)
Image for proper showing

**Comment by Kurfursten** [comment]
This is caused because Snaxi is smaller in XY than other maps (300x300 instead of 500x500) but I don't know how to fix this. It's UI wizardry. I asked Pomf a while back if he'd look at it.
