### ISSUE TITLE
Why is Snaxi in the rotation?

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#26037]
Not only is it nearly March, nobody ever liked Snaxi in the first place. Throw it out of the rotation and ban anyone who ever suggests doing a snow map ever again.

**Comment by gurfan** [comment]
contribute to the cause, pollute the air and raise the temperature today

**Comment by d3athrow** [comment]
as long as it's cold enough it's snaxi time gay boy
