### ISSUE TITLE
custom shuttles borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26047]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
f5513626635c21b2743dbeb4a92bf6f9e2464e86

# Description
ADMIN LOG: WARNING: A shuttle (Dan's Promotional Shuttle; /datum/shuttle/custom) has attempted to move to a location which overlaps with its current position. The shuttle will not be moved.
# Steps to Reproduce
make shuttle, try to send/teleport it
# What you Expected
movement
# What Actually Happened
error logs

**Comment by SonixApache** [comment]
worked when i was still fucking with it, you sure you didn't just fuck up the docks?
