### ISSUE TITLE
nonhumans? on my nukeops? its more likely than you think

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26059]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
d6c0232f52e8b2f0c32c0b3bb051bbb9849db639

# Description

nonhumans can be nukeop leaders. this is bad, okay? we are syndicate AGENTS not syndicate ALIENS

# Steps to Reproduce

ready up for round, get excited to be picked as a nukeop, deathgasp after seeing that your leader is a filthy r*ach

# What you Expected

to have a pleasant murderbone

# What Actually Happened

not a pleasant murderbone

**Comment by cloutcode** [comment]
the syndicate doesn't discriminate

**Comment by Blithering** [comment]
Nuke ops are disposable shock troops, perfect for nonhumans.

**Comment by DamianX** [comment]
The Syndicate does not condone racial discrimination.
