### ISSUE TITLE
security roaches are a thing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26058]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
4397906c7eb6a65d1967e1d708e0623f09b19573

# Description

security roaches are a thing

# What you Expected

no roaches on my sec force

# What Actually Happened

roachez on the zec force

# Steps to Reproduce

find a suitable partner and build a family together

**Comment by Verin-Verdelet** [comment]
Wow you sound like a no fun faggot.

**Comment by cloutcode** [comment]
hmmm can't seem to get those steps to reproduce right
