### ISSUE TITLE
Moved while locked down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26069]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
1d80881f4e08a2c97da9b29c626f6d5d16aae100

# Description
Moved while locked down either during or as a result of singulo
# Steps to Reproduce
Get hit by singulo and locked down and walk
# What you Expected
Not able to move
# What Actually Happened
Moved just fine

**Comment by ghost** [comment]
what DID he mean by this

**Comment by DamianX** [comment]
I'm going to extrapolate that he the OP was a locked-down cyborg that happened to stand near a loose singularity, which is capable of setting `anchored = 0`. Feature?

**Comment by nervere** [comment]
Definitely a feature. Much weirder things are unanchored by singularities than a locked down cyborg, and I doubt anyone wants to change that or add snowflake exceptions to it.
