### ISSUE TITLE
You can see the ninja den through the cyborg camera.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26065]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
bb9be254eab2b999f9a9946613f9d60b0746b520

# Description
The cyborg that is placed in the "Spider Clan Dojo" or whatever has a camera in it. People can see when a ninja spawns using the cyborg camera. 
# Steps to Reproduce
1. Ninja Spawns
2. Crew laughs and watches him practice in the ninja den through the cyborg camera.

**Comment by PrimeDSS13** [comment]
little SHIT 
![image](https://user-images.githubusercontent.com/57536342/77838266-61bf6400-7140-11ea-9da6-8d9dab401d37.png)
