### ISSUE TITLE
Midround Malf is broken

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#26071]
#### Description of issue

When dynamic decides to make you a malfunctioning AI midround, it is completely broken.

#### Difference between expected and actual behavior

Expected: Your normal, average, malf.
Result:

You get the malfunctioning message, but you  
-Have no malf law
-Have no malf abilities
-Cant hack APC's

#### Steps to reproduce

Be AI, become malf through dynamic fuckery

#### Length of time in which bug has been known to occur

Since midround malf was added, probably

#### Server revision

[gamemode]
[bugfix]

**Comment by gurfan** [comment]
Getting an admin to manually make me a malf fixed it, this seems to only be an issue with dynamic.

**Comment by xeroxemnas** [comment]
Malf is such a gunked fucking antag. It really needs an overhaul.

**Comment by SonixApache** [comment]
#23072

**Comment by Zth--** [comment]
Fixed here #26224
