### ISSUE TITLE
Chaplain's custom crew manifest title doesn't update

### ISSUE THREAD

**Issue by Waismuth** [d3athrow/vgstation13#26072]
#### Description of issue
Seems the system which gives chaplains a custom name on the manifest upon picking a special religion like Cult or Vampire is broken, it stopped giving special job titles.

#### Difference between expected and actual behavior
It used to work months ago but now it doesn't. I wanted to have a snowflake name on the manifest, but instead I'm stuck with just the "chaplain"

#### Steps to reproduce
Become roundstart or midround chaplain, pick custom religion like cult, vampire, ling. You also actually have to manually click "UPDATE PDA" on your pda next to the ID, otherwise the pda still is called "chaplain" rather than for example "vampire". This however doesn't update the crew manifest 

#### Length of time in which bug has been known to occur
I had a few months break from playing ss13, so it seems it's been present for at least 3 or so months

#### Server revision
Game: 1d80881f4e08a2c97da9b29c626f6d5d16aae100 
Patches: 507d5b7414433f4eeacf1549f11116d50a2ca7ba

**Comment by DamianX** [comment]
good issue
