### ISSUE TITLE
Highlander stun

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26092]
(WEB REPORT BY: sneakycanuck REMOTE: 206.221.180.138:7777)
# Revision
b70417adec551df9041e1eaad777d5217bb25beb

# Description
The Highlander spell from the highlander traitor bundle says it makes you immune to stuns but this is not the case and now my headtaking/bombblowing master plan is ruined reee

# Steps to Reproduce
Use highlander spell on self, get shot with taser

# What you Expected
Not get stunned, remove heads, desroy station

# What Actually Happened
Get stunned, have sword arm removed, big gay

**Comment by Killette2** [comment]
The spell only works for about 60 seconds. Did you get tased within a minute of casting it? It's hulk

**Comment by DamianX** [comment]
Works on my machine. The stun only lasts for as long as HULK is active.
