### ISSUE TITLE
Roid medbay dark as FUCK

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26113]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
4fbef73ef524868ef171a6b93a4f34995005ea14

# Description
There are way too many dark spots on roid medbay. I blame ancient's fuckery with the lights.
# Steps to Reproduce
Walk to the roid medbay and look at the dank dark morgue, storage and surgery
# What you Expected
A well lit hospital
# What Actually Happened
NT looks broke as fuck no lights whore house

**Comment by SonixApache** [comment]
\>NT looks broke as fuck no lights whore house
working as intended

**Comment by cloutcode** [comment]
i mean literally in the surgery room the light fixture is on the window facing the hallway, it do not need to be there since enough light comes in from the hallway
