### ISSUE TITLE
Microwave recipes involving reagents often fail

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#26129]
In recipes that require reagents, it seems very common that something will fuck up and the microwave will just produce burnt mess, even with the correct ingredients.
Two microwaves side by side, both with 15 flour in? One will fail, one will correctly make bread. Is there some kind of attached random fail chance for microwaves that was added in the last couple of years? AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by kilozombie** [comment]
It might be something related to server lag? Multiple times I'll try to click on an ingredient then the microwave, but it turns out I didn't pick up the ingredient and so clicked on the microwave with an empty hand, but I don't open up the menu. Then I try cooking with the correct ingredients and it becomes burnt mess. It's like there's hidden extra ingredients being put in.

**Comment by kilozombie** [comment]
I don't even care that this is ick ock, I've been cooking shit over and over using the right ingredients and one microwave always fails

**Comment by kilozombie** [comment]
AHA
AHA!!!!

**Comment by kilozombie** [comment]
FUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOUFUCK YOU FUCK YOU

**Comment by kilozombie** [comment]
https://github.com/vgstation-coders/vgstation13/issues/22118

@Kurfursten @SonixApache I KNEW THIS WAS HAPPENING AND NOBODY BELIEVED ME

I AM THE HERO

**Comment by kilozombie** [comment]
I stopped playing chef before this https://github.com/vgstation-coders/vgstation13/pull/19953 and when I went back to playing chef the bug existed
I believe that PR caused it

**Comment by kilozombie** [comment]
Very hard to replicate. I might be wrong about the cause. There is 100% something wrong with microwaves that causes one to fail with the correct recipe. I don't know what it is and it's immensely frustrating

**Comment by kilozombie** [comment]
It keeps happening with cream cheese bread. I put 15 units of flour into each microwave, then I put two cheese wedges in the top one and then two cheese wedges in the bottom one, and then the top one often fails. For what it's worth I ctrl+click to activate both microwaves

**Comment by kilozombie** [comment]
I took video. I can't post it until it stops being ick ock. Then you'll see. Then you'll ALL see.

**Comment by kilozombie** [comment]
It's not related to the timing or the tick delay but I have footage of it failing many times

**Comment by kilozombie** [comment]
I believe it's most likely related to reagent transfer, I hadn't recorded it but once I saw salt listed as "1 unit of salt" in a microwave and "1 units of salt" in the other microwave, and one of them failed
Video soon

**Comment by kilozombie** [comment]
https://www.youtube.com/watch?v=GtLyBJeX6fM

**Comment by Kurfursten** [comment]
Try to reproduce this with something that
1) Involves only reagents
2) Involves no reagents

I notice you are only using mixed cases
I am certain this has to do with locating the recipe datum

**Comment by kilozombie** [comment]
Will do chief

**Comment by kilozombie** [comment]
https://www.youtube.com/watch?v=evHyreKnTok

**Comment by SonixApache** [comment]
Well that ~~looks~~ is reproducible. Weird.
![microwave](https://user-images.githubusercontent.com/8468269/78847771-06c72000-7a10-11ea-9fec-34d6f1c3d7b2.png)

**Comment by Kurfursten** [comment]
When this happens, I VV'd the microwave and it does have the same reagents at 1u volume correctly. The two microwaves have identical reagents lists.
