### ISSUE TITLE
Failed forced roundstart rulesets prevent all other roundstart rulesets from firing

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#26153]
#### Steps to reproduce
- Force nuclear assault before roundstart
- There aren't enough players for it at roundstart
- Dynamic spawns 0 roundstart antags

I think it should proceed as if nothing was forced, instead.

**Comment by ShiftyRail** [comment]
Forced rulesets should ignore population conditions. Do you mean there's not enough volunteers at roundstart ?

**Comment by DamianX** [comment]
Yes, that is what I meant but it's not the point. The point is what happens after the forced rulesets fail, regardless of why they failed.
