### ISSUE TITLE
Ghetto ansible recipe doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26152]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
ee0c81a7606704ba610c1fccaaabd8908fb2f3d3

# Description
welding table parts doesnt work
# Steps to Reproduce
weld table parts
# What you Expected
thing
# What Actually Happened
no thing

**Comment by ArchSunder** [comment]
Turns out this was part of the black market
