### ISSUE TITLE
#26125 may not be working (dynamic machine broke)

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#26159]
`ADMIN LOG: Dynamic Mode: Despite Nuclear Emergency having enough candidates, there are not enough pop and enemy jobs ready (5 and 0 out of 25)"`

Actual admins need to vet this issue because I can't check as a lowly peabrain

https://github.com/vgstation-coders/vgstation13/pull/26125

@ShiftyRail

**Comment by oversane** [comment]
nukies are gone we only have wizards traitorstended and revs now

**Comment by ShiftyRail** [comment]
First a mea culpa as I didn't actually test my code yesterday (I was pinged about it in game, logged off and pushed the hot"fix" before going to sleep)

I *thought* the was clearly that `new_players` weren't alive but it seems something's else is afoot

I'm on it and should give a fix very soon

**Comment by kilozombie** [comment]
Thanks bub, testing stuff that requires high playercount sounds like a pain in the ass

**Comment by ShiftyRail** [comment]
False alarm, the wrong value is displayed but the correct value is used in calculation.
During that round, there was 19 people ready and 5 sec jobs. 19 + 5 = 24, under 25, so it displays a failure message.

But it displays 0 when it should display 19, which is a bug I'm going to fix.
