### ISSUE TITLE
Requesting Brave Coder to Lead The French to Victory (Snails)

### ISSUE THREAD

**Issue by SageOfLight** [d3athrow/vgstation13#26156]
![ss13 snail](https://user-images.githubusercontent.com/10042344/78987004-4f570a00-7af2-11ea-99f0-e3ffb4e2a4cb.PNG)
I've been making icons for a snail-based addition, including but not limited to the actual critter, meat and shells, escargot food item, **es-cargo**, and a helmet, or shelmet if you will. I have absolutely no coder knowledge nor the conviction to learn, but I do sprite.

**Comment by ShiftyRail** [comment]
Give me the DMI and you've got it

**Comment by SageOfLight** [comment]
Gotcha monsieur.
