### ISSUE TITLE
Bear Traps - abusing failed opening attempts to instakill people/phantom linking people to them by dragging them onto it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26161]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
b7456e1fb937156c6f49c4a45e23c4f238229570

# Description
heres a video showing both
https://streamable.com/n6so1x
if you tiledrag someone onto the trap it fake triggers but leaves the person linked to it, they can be pushed away from it

you can also spamclick traps that have latched correctly and then walk away from the trap or just let it fail to instantly fuck people to death
# Steps to Reproduce
do things in video
# What you Expected
things in video to not happen
# What Actually Happened
things happened

**Comment by RaccoonBro** [comment]
ah fuck
