### ISSUE TITLE
IED Bear Traps Have Gone Haywire

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#26162]
#### Description of issue
>Procure IED Bear Trap and arm it
>Have victim walk on it
>IED explodes as normal
>Victim's leg doesn't fly off(!)
>Bear trap is thus still stuck on him(!)
>It's now impossible for Victim to attempt to remove the bear trap or move at all(!)
>Although the immobile Victim (and his trap) can be dragged around, it is also impossible for Onlookers to attempt to remove the bear trap(!)
>If onlookers pick up the bear trap at this stage, they pick up the Victim who is temporarily trapped INSIDE the bear trap when this happens(!)

(Distinct from the other issue open about bear traps right now, this is specifically about IED Bear Traps)

#### Difference between expected and actual behavior
Leg should blow off, leg does not blow off, slapstick ensues

#### Steps to reproduce
IED Bear Trap anyone you want

#### Length of time in which bug has been known to occur
Bear Trap rework thingy did it 

#### Server revision
Game: b7456e1fb937156c6f49c4a45e23c4f238229570

**Comment by ShiftyRail** [comment]
>It's now impossible for Victim to attempt to remove the bear trap or move at all(!

Not what happened during testing, I could remove the IED by clicking on it whilst trapped in it.
Could reproduce the other issues.
