### ISSUE TITLE
security firing range control console moves EVERYTHING in security when cranked up to max

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#2616]
(might be intended idk)

how to reproduce

1. click on firing range control console
2. set everything to maximum
3. enable magnets and movement
4. set path to r;r;r
5. all items in security will be possessed now

it's loose when combined with https://github.com/d3athrow/vgstation13/issues/2615

**Comment by IratePirate** [comment]
Holy shit thats funny.

**Comment by utilitas-** [comment]
The most fun you can have with [REVVING INTENSIFIES] is when the whole security derpartment is at home, possibly brigging someone. You can set it up to a point where everyone moves so fast that no one can disable it without AI intervention.

**Comment by PJB3005** [comment]
Unable to reproduce.

**Comment by Unfit** [comment]
![](http://puu.sh/j9Wsr/32e08fd21d.png)
Just checked and it still works

**Comment by PJB3005** [comment]
Welp guaranteed to be oldcode.

**Comment by Unfit** [comment]
so yeah looks like it's nto a bug, just an unintended feature I guess
