### ISSUE TITLE
Remove chance to receive genetic defects / benefits from Wizard / Nuke-Op

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#2617]
You can receive random genetic defects and benefits when you arrive on the station or at roundstart. There is a potential issue in that a Wizard or Nuke Op could receive a starting defect so bad as to make it impossible for them to do anything without admin intervention.

I've seen Deaf / Blind Nuke Ops already, one day we will have a blind wizard when no admins are online to fix it, and it will be awful for everyone involved.

**Comment by ComicIronic** [comment]
I'd support this being also being removed from Head Rev and Cult, as well as potentially human blobs.
Wizard is the most crucial role, though, just for being sole antag.
