### ISSUE TITLE
Spoons are useless

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26177]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
24a982c926498855f7066a32fe5321a7471ffc12

# Description
Spoons serve no purpose.
# Steps to Reproduce
Try using a spoon to eat soup
# What you Expected
Eat soup like a human being, using utensils
# What Actually Happened
nothing

**Comment by oversane** [comment]
grab a forkful of the bowl

**Comment by ghost** [comment]
Spoons are strange ancient technology and spessmen don't know how to use them.

**Comment by Kurfursten** [comment]
*holds up spoon*

**Comment by strawberrytan** [comment]
there is no spoon
