### ISSUE TITLE
Vox raiders are unable to hear anyone not in their raiding party

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2619]
When you are a vox raider no communication interceptions can be heard through your syndicate radio and when the crew speak to you chat bubbles appear in game but there is no log of what they said. By no log I mean no messages at all. They can however be heard by the crew.

Also vox raiders is still in rotation please remove

**Comment by AutismSpider** [comment]
more awfulness with this half ass port of the TG chat.

**Comment by clusterfack** [comment]
Fixed via https://github.com/d3athrow/vgstation13/commit/970a0d25e9bc399cfdc983d8e8cec58707510343
