### ISSUE TITLE
Mulebots lack the access to deliver their package in most cases

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#26208]
#### Description of issue

The AStar rework fixed most of the pathing issues related to bots, which are now able to path to the Bridge/the Brig/medbay properly.

However, they lack the access to cross the windoors. This means that the bots will just advance up to the plastic flaps, get stuck here, and their package won't be noticed.

Either we should let the mulebots deliver closer to their destination, or warn the persons in the targeted department that something is waiting for them by the plastic flaps.

**Comment by Kurfursten** [comment]
The way they're supposed to work is that they go to the tile of the flaps, unload into the open space (marked in yellow) by the windoor, and then leave. They aren't supposed to go past the windoor.

They get stuck most commonly when something moves behind them after they go to the unloading position (e.g.: another mule)
