### ISSUE TITLE
Observers are not polled for special roles

### ISSUE THREAD

**Issue by AceDick** [d3athrow/vgstation13#2621]
This goes for stuff like pAI, posibrains, diona nymphs, xenos and so on. Those who hit observe are not polled for special roles, only those who have been in the round already are notified. Found that after being a mouse and ghosting, prompts for roles show up as they should.

**Comment by clusterfack** [comment]
I've seen this for nearly every special role. All the diona will die malformed until you spawn as a mommi and suicide. 

It seems if you don't have a body your mind is tied to you wont become most special roles like diona/alien/more(?)

**Comment by Ephx1** [comment]
I can attest to this, Positronic brains still work if you click on them to sign up though.
