### ISSUE TITLE
Biolobulin Syndrome is rated danger 0

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26213]
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
2d30d9c100a27334373398ca5cea59828eee5cc6

# Description
Biolobulin syndrome (a stage 4 virology symptom) is rated as danger level 0 despite the fact that it causes people who are infected to generate explosive throwing blobs.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Killette2** [comment]
It's beneficial

**Comment by Exxion** [comment]
It's not dangerous to the person who *has* it
It can be annoying though

**Comment by DeityLink** [comment]
Intended, it's generally a desirable Stage 4 symptom, which is what the danger rating correlates to.
