### ISSUE TITLE
Bear traps fuse with your existence, trapping you forever

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26222]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
f75a218939aa740a0a48badda5577a6434eeafaa

# Description
I walked into my own IED and it blew up, tried disarming it and did so but it got fused with me. I couldn't move at all except by picking up the bear trap and throwing it. Crowbaring or prying it open had no effect, grabbing it up and re-arming it had no effect. Other people could grab the bear trap and me with it, and carry me along.
# Steps to Reproduce
uhhh step on a beartrap wearing magboots that are on probably???
# What you Expected
not to get stuck
# What Actually Happened
got stuck lmao

**Comment by ShiftyRail** [comment]
fixed
