### ISSUE TITLE
Vox raider skipjack sleeper room windoor access requirement is something raiders do not possess

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2622]
It's a minor issue but the windoor usually gets destroyed or emagged since the vox raiders can't open it.

Also the prison windoor has no access requirement meaning anyone captured will eventually walk out.

**Comment by Probe1** [comment]
why not make a door bolt button similar to the dorms on the other side of the cells.  that'd get around the issue.

**Comment by clusterfack** [comment]
Seems like a map issue isn't it?

**Comment by ComicIronic** [comment]
It is, but we don't have a general map tag.
Speaking of which, I'll go make it.

**Comment by Probe1** [comment]
@Konater do you know if this ever went anywhere?

**Comment by Probe1** [comment]
Issue still exists.  Why the hell would it require sec access of all things.

![orbital_fishery_vii_2015-09-24_23-28-18](https://cloud.githubusercontent.com/assets/8550416/10092414/021da4e2-6314-11e5-857e-1d2a9a6b70c4.png)
