### ISSUE TITLE
Nearsightedness not going away with ryetalin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26249]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
20ea1d6ea0a09c76bc3d265bc59476ada9a533c8

# Description
Have nearsightedness as roundstart genetic defect. Remove my prescription glasses due to reasons, put on sec sunglasses because I needed it. Later, put back my prescriptions - still black "fog" around screen edges. Took rytalin pill. "Your eyes no longer feel weird". The black "fog" still stays.
# Steps to Reproduce
Have roundstart disability. Play for long time. Try to remove such disability. Be unable to remove it unless you get new body or do monkey trick
# What you Expected
Ryetalin to cure my shortsightedness
# What Actually Happened
Nothing, much like Detective's roundstart Noir issue not being fixed, refer to that issue.

**Comment by DeityLink** [comment]
most likely fixed by #29375
