### ISSUE TITLE
Invisible Icons On Plants

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#26246]
This is pretty bad if it happens, since you can make a bunch of invisible stinging fruits on the floors

It was said to be a nofruit variant in https://ss13.moe/forum/viewtopic.php?f=20&t=5541 but I don't think that's right?, since nofruit is supposed to not be genemoddable.

We don't know because the person didn't report it

**Comment by Kharkov72** [comment]
#26238 fixed it
