### ISSUE TITLE
snack voucher

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26242]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
35137403a8135915c4dca85aafe98306a6ea15e8

# Description
snack vouchers don't work with getmore vendors despite being used
# Steps to Reproduce
use a free snack voucher on getmore machine
# What you Expected
my snack
# What Actually Happened
robbery

**Comment by Kurfursten** [comment]
cannot reproduce
