### ISSUE TITLE
Malf AI overload machine does nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26245]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
d25897077baae5793b5b192c3775b8ea5b02b2e6

# Description
Buy machine overload. Try blowing up vents, scrubbers, airlocks, intercomms that crew are near. Nothing happens.
Right click, to click "explode machine" or whatever - no such option.
# Steps to Reproduce
Be AI. Roll malf midround. Try to overload scrubber or vent or airlock or computer. Nothing happens.
Could be because malf midround, could be because the objects weren't in my direct line of sight, but rather through cameras.
# What you Expected
I expected warden lying near scrubber to explode
# What Actually Happened
warden got up and left, scrubber did not explode.

**Comment by Zth--** [comment]
The spell works fine but it does not work for the cases you mentioned
