### ISSUE TITLE
Borgs are stunned and deafened by flashbangs

### ISSUE THREAD

**Issue by gayniggersex666** [d3athrow/vgstation13#2625]

**Comment by Konater** [comment]
The AI is also affected by them

**Comment by ComicIronic** [comment]
Considering borgs are affected by flashes, I wouldn't mark this down as an issue.

The AI thing, maybe.

**Comment by Aurx** [comment]
As long as they recover, I don't see what's wrong.  The flash stuns the borg, the bang deafens it.

**Comment by Kurfursten** [comment]
@clusterfack Not a bug, close this
