### ISSUE TITLE
plastic bags take way too long to incapacitate or kill you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26254]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
45cab95a641dd02d00234eb2952e992a541f8dea

# Description

Plastic bags make you suffocate but dont do a good job of truly killing you at an acceptable speed or even incapacitating you.  YOu can last about 3 minutes without blacking out with one on
# Steps to Reproduce

Wear plastic bag on head
# What you Expected

Fast Death
# What Actually Happened

slow death

**Comment by Kurfursten** [comment]
That sounds about right. In an environment totally devoid of oxygen, a human won't pass out for about 1 minute. An average plastic grocery bag contains about 8 liters of air max, which is conveniently about what a human breathes in a minute.

So maybe it should be around 2 minutes. It shouldn't be a quick assassination tool by slipping it over someone's face.

**Comment by ghost** [comment]
Wearing plastic bags on your head is supposed to be a meme feature that makes people go "wow, I can actually do that?" It doesn't need and shouldn't have any practical use in killing people.

**Comment by DeityLink** [comment]
If you want to kill them quicker, choke them to death at the same time with grab intent. Choking gives oxy damage but ironically doesn't prevent breathing, so they kinda both syngergize. Not like you could kill someone with a plastic bag without a way to restrain them in the first place anyway.
