### ISSUE TITLE
Revs music will go on ENDLESSLY

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#26250]
I'm not sure what the conditions are for revs music, but they seem wrong. A round where 3 of the headrevs died and 1 headrev became a Robocop borg continued on, revstended, with the music blaring all the way through for two hours. There's no way to stop the music even if you change your settings mid-shift and it's pretty confusing even just as an observer

![image](https://user-images.githubusercontent.com/6062247/79792651-1db91c80-8304-11ea-9d06-dbc9139a1133.png)

**Comment by boy2mantwicethefam** [comment]
feature

**Comment by kilozombie** [comment]
Reeeeee

**Comment by DamianX** [comment]
There's no loss condition at all for revolutions. See #23126

**Comment by Kurfursten** [comment]
There is a loss condition, but it's very hard to obtain. Every single rev has to be dead, which sends the Order Restored command alert.

**Comment by Kharkov72** [comment]
so the question becomes what the hell broke it because it was working a week ago

**Comment by Zth--** [comment]
There are runtimes on the rev flash and on the gamemode process, I'm investigating

`[13:50:39] Runtime in rev.dm,152: Cannot read null.stat`
`[13:22:46] Runtime in flash.dm,293: Cannot read null.stat_datum`

**Comment by DamianX** [comment]
https://github.com/vgstation-coders/vgstation13/blob/20ea1d6ea0a09c76bc3d265bc59476ada9a533c8/code/datums/gamemode/factions/syndicate/rev.dm#L152
Won't this runtime if a rev's body is destroyed?

**Comment by Zth--** [comment]
yep
