### ISSUE TITLE
Robohands somehow getting disconnected from arms?

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#26257]
Man gets EMP'd, fixes his robotic arm and hand. Somehow his hand no longer works!
Changing the limb did not fix it, only complete removal and reattatchment.
Game thinks his hand is a stump even though it's still on him as evidenced from his message being from
`//called when we try to click but have no hand
//good for general purposes
/atom/proc/attack_stump(mob/user as mob, params, var/proximity)
	if(!requires_dexterity(user))
		attack_hand(user, params, proximity) //if the object doesn't need dexterity, we can use our stump
	else
		to_chat(user, "Your [user.get_index_limb_name(user.active_hand)] is not fine enough for this action.")`
Possibility: Hand got delinked from parent arm, causing mustard gas? Not sure, more testing needed.
Told this happens a majority of the time when EMP'd, but not ALWAYS.

**Comment by tayachiya** [comment]
Have you tried using a multitool to fix it?
