### ISSUE TITLE
once it starts, gamer music on Revolution never stops

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#26251]
#### Description of issue
>-gamemode is revs
>-revolution reaches the point where it's automatically announced over the PA, music starts, and the code is automatically elevated to red
>-all head revs die
>-music never stops, automated announcement that the happening is over (like when the delta malf 
dies or when the late stage cult is defeated) never comes
>-not sure if this means that converted revs don't get auto deconverted too
>-stuck forever listening to **gamer music**

**Comment by boy2mantwicethefam** [comment]
feature

**Comment by Accipitermaris** [comment]
#26250
