### ISSUE TITLE
[Deff] Issues/criticisms

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#2627]
No HoP attire locker spawns in the HoP Office
No privacy shutters in HoP Office
Firelocks under the windows west of cargo are ugly
Visible pipe one tile north of Mining Station Maintenance near where the shuttle is

**Comment by Duny-** [comment]
>Firelocks under the windows west of cargo are ugly

Make a new sprite for firelocks under windows then :^)

**Comment by Duny-** [comment]
Fixed here https://github.com/d3athrow/vgstation13/pull/3068
I don't think I can do anything about the firelocks being ugly.
