### ISSUE TITLE
[Feature Request] [Discussion] Fire rework

### ISSUE THREAD

**Issue by stormcloud23** [d3athrow/vgstation13#26284]
<featurerequest>
<discussion>
####Description of issue

I'd like to open a discussion on how fire can be reworked to be a more relevant and present danger. Considering the legacy of SS13 as an atmospherics simulator, the idea that fire behaves the way it does currently (just shows up in the "air" of a tile and disappears a second later) doesn't really sit well with me. I think if we had a reworked version of fire, which could burn on tiles, spread, block passage, etc, it could add some utility to fire producing items for antags, while also buffing the atmospheric technician role. Considering the wiki describes them as the station's fire fighters and yet they never do any actual fire fighting, this feels like a good buff for them to get. CM has a fire system similar to what I'm envisioning, I'll attach an image here so you can get an idea.

![Helpintentkills](https://user-images.githubusercontent.com/57145867/80018120-92768d00-84a3-11ea-8e20-0e0e8b325cdf.gif)

[https://cm-ss13.com/wiki/images/e/ef/Helpintentkills.gif](url)

Pros:
Gives Atmos tech a more defined role
Makes fire extinguishers actually useful
Make people consider the risks of fire in a space station/atmos simulation game (they should have to fear it already, rather than just thinking of it as something that just kinda shows up sometimes and doesnt really do much besides discolor tiles.)
Gives antags another way to destroy the station/more variety

Cons:
Might be kind of strange seeing metal tiles burning. Maybe make it so only wood/carpet/grass/tiles with fuel on them burn, unless there's some special kind of fire (napalm or something)
Could be overtuned and fuck balance
Could be "obnoxious" in blocking passage, although I imagine fire extinguishers would help relieve this.

**Comment by kilozombie** [comment]
Having a flamethrower that shoots out welding fuel in addition to the flame projectile would be great, if that welding fuel then lingered as flames for a couple minutes.
Fire being a threat is good for the same reasons ZAS is good-- there's a lot of emergent gameplay that can come out as a result. Right now flamethrowers are also super mega lame and useless in almost every single situation.

**Comment by Buchse** [comment]
https://www.youtube.com/watch?v=exq0CIA_xCg

**Comment by ThatRedPyro** [comment]
I'm assuming the ''blocking passage'' part only applies in extremely big fires and against people who don't have resistant suits? Otherwise that part would be just annoying.

**Comment by Buchse** [comment]
I honestly really like the idea of more persistent, dangerous fire. It makes more mundane things like molotovs more useful, and makes accidental fires more serious, rather than a "whoops" moment.

**Comment by stormcloud23** [comment]
@ThatRedPyro Well, I imagined it as a soft block in the case of just a small fire, IE you can walk through it, but it would do damage and potentially light you on fire as well. If it was a large fire, I imagine something more like a message popping up saying "The heat of the flames is too intense for you to proceed", unless you're wearing a fire suit or atmos suit or something.  Perhaps as a fire spreads, it would have an outer layer of "small fire" that can be maneuvered through to some degree, and an inner core of "large fire", which is essentially a blocked tile until the fire is brought under control. Fire extinguishers could demote a large fire into a small fire, and then a small fire into a regular tile.

**Comment by stormcloud23** [comment]
@Buchse Yeah, improved molotovs could be a lot of fun. It's a neat item but as it stands not it really doesn't do much.

**Comment by stormcloud23** [comment]
Or, better idea, what if regular fire extinguishers could take out small fires which would stop large fires from spreading, but large fires themselves could only be handled by an atmospherics extinguisher. Lets the crew handle small issues but gives the atmospheric technician a defined role in handling large fires.

**Comment by Buchse** [comment]
> Or, better idea, what if regular fire extinguishers could take out small fires which would stop large fires from spreading, but large fires themselves could only be handled by an atmospherics extinguisher. Lets the crew handle small issues but gives the atmospheric technician a defined role in handling large fires.

the issue with that is that the foam extinguishers were changed recently, making them useless for fires

**Comment by stormcloud23** [comment]
@Buchse Ah. Well I'm sure they could be updated to work with the proposed system as well. The idea is just that regular extinguishers found throughout the station can work for regular fires, but if something really goes wrong or people ignore a small fire for too long, it takes more specialized equipment to manage.

**Comment by Buchse** [comment]
yeah, it's a good idea, it would just take some doing

**Comment by strawberrytan** [comment]
being set on fire isn't very dangerous in most circumstances

**Comment by Kurfursten** [comment]
West overhauled fire
