### ISSUE TITLE
Female ninja armor sprites (and all ninja shoe sprites) are broken

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#26288]
The body clips through the sides and it looks really bad.

![nothinatall](https://user-images.githubusercontent.com/51391726/80056298-e5773100-84f1-11ea-8d5d-af9f87018155.PNG)
Feels like I'm wearing nothin' at all!

**Comment by Kharkov72** [comment]
admin, I'm trying to sneak around the station, but I'm dummy thick, and the clap of my exposed asscheeks keeps alerting the AI
I'd ping sonix but his account is dead so

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/132241161-1a3885e6-67e1-4645-844a-2c63827a9108.png)
