### ISSUE TITLE
Solar panel assemblies are dense now for some reason

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2628]
Being made to pull every panel into position discourages people from setting up their own solar array or replacing one. It wasn't like this before, a stack of them spawn in a crate in engineering but due to the way it is now you have a stack of roughly thirteen assemblies that you can't pick up or walk through.

**Comment by clusterfack** [comment]
Alright I'll make them no dense when in an unanchored state so you can store them in crates.
