### ISSUE TITLE
Telescience chamber should have at least scrubbers added to it if not vents

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2629]
Sometimes scientists like to fill it with n2o or fire and usually the only way to clean it up is to seal the entire room off and have a synthetic player turn on the scrubber outside the chamber. There is an orphaned waste pipe leading to space just north of xenobiology that could be used.

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/5896887/24431b46-a50b-11e4-80d8-c09f52888615.png)

If you look closely there's a waste line that leads to it but isn't connected.  I'm not entirely sure why it isn't finished.  It'd be lovely if it was.  I've put out telesci fires a few times as the CE and it's pretty simple, just wrench down huge scrubbers in maint and partially knock down the rwall so the gasses leak into the room you've prepared.  But it really should have a vent and pressure pump leading to the waste line.

**Comment by Intigracy** [comment]
Fixed at some point, please close.
