### ISSUE TITLE
Weird plasmaman gib bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26294]
(WEB REPORT BY: senaat1 REMOTE: 206.221.180.138:7777)
# Revision
f77b7e897733c99639f6be7baa8928a3d962436e

# Description
Events:
1. Clown slips me and puts C4 on me
2. Moments before i explode he puts me in the trash
3. I explode
4. Visualyl when i'm inside my corpse, i see my ungibbed corpse in the trash, when i ghost it isn't there
5. My SPS still shows as being on the tile of the trashcan, but none of my equipment is actually there. Removing the trashcan doesn't change anything, SPS still points to this empty tile, admins also can't move my corpse.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Zth--** [comment]
#25406
