### ISSUE TITLE
Alternate Proposal to #26295: The Stamp Act

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#26296]
#### Description of issue

Currently Envelopes are just returned to sender if disposaled.  What I propose is that in order to mail an envelope one must destination tag and affix one Standard NT stamp to the envelope, which can be purchased and come in multiple different colors and images.  Stamps will be consumed on envelopes each time they are mailed, and will be disposaled without one.  This could eventually allow the crew to stamp and mail themselves.  

This is not a transparent attempt to add stamp collecting to SS13 as yet another autism project to do during a long shift, or to allow an eventual seguey into the eventual collection of Discount Dans, Syndicate, and Getmore Corporate stamps, or mysterious vault stamps nobody will ever know nor care about.

**Comment by DeityLink** [comment]
well since #26295 was merged I guess this one fell through.
