### ISSUE TITLE
beepsky machine broke

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26300]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
693519738dad6824a1adc7cd7fd9d9a274daef22

# Description
he wont do anything he just sits there

# Steps to Reproduce
look at beepsky
# What you Expected
beepsky move
# What Actually Happened
beepsky still

**Comment by ShiftyRail** [comment]
Is this early in the round ? After some patrols ? After arresting someone ?

**Comment by dunsel-hordon** [comment]
i have been noticing it multiple rounds too. Even turning it off and on again doesnt work
