### ISSUE TITLE
You can still gain spells by transferring your brain to a wizard body

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#26307]
And the wizard's mind retains its original spells, meaning the spells get duplicated

**Comment by DamianX** [comment]
https://github.com/vgstation-coders/vgstation13/pull/20030#issuecomment-432178823

**Comment by Kharkov72** [comment]
feature

**Comment by dunsel-hordon** [comment]
Yes you can get the spells. Problem is that most spells with a verbal component do not work when you do this.

**Comment by west3436** [comment]
Feature
