### ISSUE TITLE
Radguns do burn damage instead of toxin

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#2630]
Radgun description states that "fires radioactive projectiles that deal toxin damage, irradiate, and scramble DNA" but the projectiles (/obj/item/projectile/energy/rad) cause burn damage instead of toxin.

**Comment by eswordthecat** [comment]
@ComicIronic

**Comment by ComicIronic** [comment]
Should have been fixed in #2638, reopen if not fixed.
