### ISSUE TITLE
how the fuck do seeds work botanycode

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#26302]
>recipe requires /obj/item/seeds/poppyseed
>getting seeds out of an extractor just gives /obj/item/seeds

BRAVO NOLAN I LOVE YOU

**Comment by assmops** [comment]
have you tried to run poppies through a food processor you gaybo

**Comment by Allspice** [comment]
// Create a seed packet directly from the plant.
/datum/seed/proc/spawn_seed_packet(turf/target)
    add_newline_to_controller()
    var/obj/item/seeds/seeds = new(target)
    seeds.seed_type = src.name
    seeds.update_seed()
    return  


/obj/item/seeds/poppyseed
    name = "packet of poppy seeds"
    seed_type = "poppies"
    vending_cat = "flowers"

not seeing anything obvious in the growing plant that refers back to poppyseed
seems that you can currently only make poppy recipes from seeds directly from the seed vending machine or mapped-in seed spawners
