### ISSUE TITLE
Security Tape Breaks Airlocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26315]
(WEB REPORT BY: generalveers25 REMOTE: 206.221.180.138:7777)
# Revision
adf312319855eb4b3b6a1c67e9a3ca149c6910da

# Description
When you place Security Tape through an airlock, if the airlock closes or is closed while the tape is there, the door will get stuck open and cannot be closed.

It also cannot be hacked. Admins cannot close it.
# Steps to Reproduce
Place security tape through airlock.
Close airlock manually.
Airlock is now permanently stuck open.
# What you Expected
Well the damn airlock shouldn't be defeated this easily.
# What Actually Happened
See above.

**Comment by ShiftyRail** [comment]
Acknoweldged. The admin hotfix is to set "operating" to 0
