### ISSUE TITLE
Game breaking bug net bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26313]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
e8901e403c91ffc888a40228c693b1ec56089340

# Description

"There's 60 caught beess in it!"

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by DamianX** [comment]
He's clearly talking about the fact that there's an extra S in "beess".
