### ISSUE TITLE
Glasgow appears to be showing up in just about every random minor virus

### ISSUE THREAD

**Issue by ArchSunder** [d3athrow/vgstation13#26320]
#### Description of issue
I guess since the rando viruses were nerfed to have lesser symptoms this is a consequence? Nearly every random "minor" virus rolls in with glasgow, which is actually a pretty gunky and annoying virus.

I'm not sure how I could demonstrate this, but i've been checking the disease panel when random viruses roll and drunky symptom comes up a whole bunch

**Comment by dunsel-hordon** [comment]
glasgow should be a phase 3 virus as should bees

**Comment by Killette2** [comment]
This was intended behavior to remove meme transmission
You could look at code and logs to ballpark how often we get it if you care to show

**Comment by DeityLink** [comment]
> This was intended behavior to remove meme transmission

What? No that was the default original behaviour, Meme diseases had higher badness on average which led to a ton of glasgow which was just bad design for something that could so easily enter a round.

> I guess since the rando viruses were nerfed to have lesser symptoms

When? The last nerfs to viro were years ago now. Pay attention to the outbreak announcement. If it's level 2-4 it's a minor one, if it's 5-7 it's a major one. I also don't think glasgow is THAT much more prevalent, it's just that it leaves a bigger impression on people.
