### ISSUE TITLE
Removing Coins from Money Bag while it is in your hand

### ISSUE THREAD

**Issue by omeno** [d3athrow/vgstation13#2634]
If you hold the moneybag in your hand while removing coins from it, the coin vanishes into thin air. The bag will register that it has one less coin, but no coin, visible or invisible, will be in your hand or on the tile.

**Comment by ComicIronic** [comment]
And this is why you don't place stuff in mobs manually.
Caused by http://puu.sh/f4Fol/b39175522c.png.
