### ISSUE TITLE
Telekinesis plant harvesting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26351]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
07d190f70ffe593f358378c82c46afedc9a02b6e

# Description
Harvesting plant with telekinesis, even  a screen across, spawns fruits at your feet.
# Steps to Reproduce
get telekinesis, get plant, harvest plant from afar.
# What you Expected
fruits at plant place or near
# What Actually Happened
fruits at my feet

**Comment by SGuivenne** [comment]
Are you sure you're not being haunted by Carmen Mirandas ghost?

**Comment by boy2mantwicethefam** [comment]
feature

**Comment by Killette2** [comment]
You can get similar results when you remove things stuffed in chairs/plant pots. TK is a whacky power when it comes to sanity
