### ISSUE TITLE
Cant equip surgery tools as borg

### ISSUE THREAD

**Issue by Riukanojutsu** [d3athrow/vgstation13#2636]
I couldnt equip any surgery tool as mediborgs. I could equip other items but not surgery tools and the wakeup baton

**Comment by gayniggersex666** [comment]
this happens to engineering borgs too, gotta go into the menu and pick them from the list instead of using the inventory bar

**Comment by Ephx1** [comment]
The new inventory system is really fucked, and will sometimes work and sometimes won't. It seems like it works depending on how many things you have on, and where in the inventory space the item is.

**Comment by Riukanojutsu** [comment]
I also had issue with a beaker when I was mediborg. I put it in a chemdis and when it came out i couldnt equip the module anymore

**Comment by ComicIronic** [comment]
Should have been fixed in #2709, reopen if not fixed.
