### ISSUE TITLE
Mapping: Roidstation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26368]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
Maybe I'm just insanse but the SME core scrubbers are not attached to the air alarm control system???
Editor's Note: how the fuck do I scrung

**Comment by Kharkov72** [comment]
if they aren't on the air alarm they're on a different frequency and you should multitool and reset the frequency for it to show up
this was changed in #26328 for AAC autism
