### ISSUE TITLE
Dragging people out of the time stop bubble freezes them permanently

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#26385]
#### Description of issue

When you drag a time stopped person out of the "time stop circle", they stay frozen in time forever

#### Steps to reproduce

Timestop a person, the bug happened with a xenoarch artifact timestop but it probably works with them all. Drag the frozen guy out of the circle, watch as everything in the circle gets unfrozen but the guy is cursed forever 

#### Length of time in which bug has been known to occur

Probably like, forever! Think about that.

#### Server revision

[bugfix]

**Comment by DamianX** [comment]
I can't reproduce this.
Tried both the wizard spell and a bussed artifact.
I can drag someone out of the timestop range and they get unfrozen correctly.
#26360 changed timestop but I dunno.

**Comment by gurfan** [comment]
I don't remember exactly what happened, it was djkramer/crush martins who got frozen on the shuttle, I remember hearing tasers getting shot and he might have been hit by one while timestopped, but I need to check the logs

**Comment by DamianX** [comment]
Did the shuttle move while he was timestopped?

**Comment by gurfan** [comment]
I believe it was in transit
