### ISSUE TITLE
Space Ninja Role Assignment Strangeness

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#26393]
If you manually give someone the space ninja role but decline to make htem part of a faction, there's no postsetup. They get the role but no objectives, don't go to the dojo, no sound, no loadout, etc.

Runtime
```
[14:40:34] Runtime in ninja.dm,20: pick() from empty list
  proc name: OnPostSetup (/datum/role/ninja/OnPostSetup)
  usr: Crush Mccune (kurfurst) (/mob/living/carbon/human)
  usr.loc: The floor (201, 230, 1) (/turf/simulated/floor)
```

**Comment by boy2mantwicethefam** [comment]
feature

**Comment by SonixApache** [comment]
Reason for this is that the dojo is created when the faction is created, and some of the post-setup is related to the dojo.

Fix is to just add them to the faction, and then remove them if you don't want them to actually be in the faction.
