### ISSUE TITLE
There's only one mechanic spawner on Packed but 2 are allowed

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#26405]
So the second mechanic gets stuck on the splashscreen

**Comment by ShiftyRail** [comment]
The real bug here is that the first mechanic can spawn at all.

**Comment by GreatBigFailure** [comment]
![cantwakeup](https://user-images.githubusercontent.com/64218965/81231686-946f3e80-8fc1-11ea-8b77-271f9344d231.png)

Here is an example from my personal experience with hell
