### ISSUE TITLE
Object subsystem initialization takes too long

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#26407]
About 35 seconds on Box, there are two problems:
- Initialize() gets run on every single atom in the game
- space turfs have initialize() and there's a maximum of 250,000 space turfs per z-level, the Initialize() is based on building the parallax

**Comment by boy2mantwicethefam** [comment]
After some profiling, it turns out space tiles take 4 seconds of processing
However, pipes take 9 seconds of initialization

**Comment by boy2mantwicethefam** [comment]
The pipes' findAllConnections() takes a total amount of 12 seconds

**Comment by ShiftyRail** [comment]
BSQL sped it up a bit and it's not really something we can do.
