### ISSUE TITLE
Adminbus-only immovable rod subtypes show up in the immovable rod event

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26403]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
f2c56e0959252875ba62c4ae1085a03826114771

# Description
The immovable pillar (and probably the monolith, too) show up in the immovable rod events, even thought they were only ment as adminbus-only rods that you trigger from the secret menu. I can't find a PR that actually, officially added them to the random event list, so I think its a bug that slipped through later down the line.

**Comment by tayachiya** [comment]
Weren't those supposed to be just super random?

**Comment by ghost** [comment]
If a PR actually added those as random events then disregard this, but I've never seen a PR for it, so I always thought that it was a bug

**Comment by tayachiya** [comment]
Just 1 search later I found out monolith was removed from random events, while large rod can fire if there are 3 or more engineers on board.
https://github.com/vgstation-coders/vgstation13/pull/24997

**Comment by ghost** [comment]
Then this issue is resolved. Thanks for looking it up.
