### ISSUE TITLE
Hardsuit storage units are borked

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#2641]
So this is how the hardsuit storage units look at roundstart now
![scrnshot1](https://cloud.githubusercontent.com/assets/9064611/5912682/65e68e94-a5a5-11e4-9260-273643b8de65.png)
![scrnshot2](https://cloud.githubusercontent.com/assets/9064611/5912684/6a2a4da6-a5a5-11e4-8c13-90c46c68521d.png)

**Comment by Probe1** [comment]
On top of this the far left hardsuit seems to be missing in secure storage.

 
![ss 2015-01-26 at 09 44 10](https://cloud.githubusercontent.com/assets/8550416/5913775/499cf202-a5b7-11e4-9e71-0f80cf973248.png)

**Comment by clusterfack** [comment]
There is a simple reason for this I believe. Unpowered hardsuit storage units drop the items they contain. A recent pull made it so machines created in unpowered rooms are unpowered, bang boom hardsuit storages drop their shit at initializing the round.

**Comment by Probe1** [comment]
That's what I suspected as well.
