### ISSUE TITLE
You can send people to nullspace by unwrenching the chair they sit in

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26415]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
3835445ab853608e701684ab9905915b875e5134

# Description

>be normal human being
>relax after a hard at work on my comfy chair
>mischevous mommi (probably from a birdbrain) unwrenches my chair
>get sent to cuckspace

# What you expected

Fall off my chair and unleash my anger on the mommer

# What actually happened

Sent to the shadow realm

**Comment by Kharkov72** [comment]
how the fuck

**Comment by boy2mantwicethefam** [comment]
feature

**Comment by Allspice** [comment]
featureeeeeee
