### ISSUE TITLE
small light fixture frames don't work if they do not start with a broken lightbulb already in them.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26411]
(WEB REPORT BY: germansanta REMOTE: 206.221.180.138:7777)
# Revision
3835445ab853608e701684ab9905915b875e5134

# Description
small light fixture frames don't work if they do not start with a broken lightbulb already in them.
# Steps to Reproduce
try putting light bulbs in small light fixture frames, that do not start with broken light bulbs in them
# What you Expect
that i could put lights in them
# What Actually Happened
i couldn't

**Comment by Kharkov72** [comment]
>frame

wire them
