### ISSUE TITLE
AI core turret broken/unpowered (box)

### ISSUE THREAD

**Issue by gayniggersex666** [d3athrow/vgstation13#2642]
top right turret was broken/unpowered on a round, but not the next round

**Comment by wwjnc** [comment]
Could it be related to #2645, #2641? The commit has been reverted already, it shouldn't happen on future rounds.

**Comment by clusterfack** [comment]
The commit was reverted, the problem is resolved

**Comment by ComicIronic** [comment]
Reopen if still an issue.
