### ISSUE TITLE
No cancel button for ahelps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26429]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
60dd7ab10c88345c98a565beb877565fdf203034

# Description

See title
There used to be one

**Comment by ShiftyRail** [comment]
As an edit, you'll just need to add `as null |||` after the `input()` call in the related verb to fix it.

**Comment by Kharkov72** [comment]
feature
