### ISSUE TITLE
You don't actually need a spacepod mainboard or core to assemble a spacepod

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26426]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
60dd7ab10c88345c98a565beb877565fdf203034

# Description
see title

# Steps to Reproduce
just skip the core and mainboard steps

# What you Expected

# What Actually Happened

**Comment by dunsel-hordon** [comment]
this is lies dont take notice of this at all. Please disregard. EVERYTHING WORKS AS IT SHOULD!

**Comment by Exxion** [comment]
#25736

**Comment by DeityLink** [comment]
Fixed by #27519
