### ISSUE TITLE
revs announcement played more than 20 times

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26456]
(WEB REPORT BY: mentgah REMOTE: 206.221.180.138:7777)
# Revision
e8b8de504136fc1ce7cfd0ef1eed6e62eae86b25

# Description
see title
# Steps to Reproduce
>it's revs
# What you Expected
; oh god oh fuck why is there gamer music
# What Actually Happened

Subversive Union-aligned elements have been detected aboard the station. According to latest reports, targeted removal of heads of staff is already underway. Loyal crew should take immediate action to secure station against revolutionaries. x20

**Comment by ShiftyRail** [comment]
I know why this happens
