### ISSUE TITLE
Narsie is broken [METACLUB]

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#2646]
This happened on Metaclub just now. Narsie was spawned in Medbay and sat there doing nothing. The shuttle wasn't automatically called and the station didn't get converted to cult station. Some cultists became Harvesters but Narsie didn't do any of the other things he was supposed to do.

I tagged this with metaclub because I wasn't sure if it was specific to metaclub or if it is a wider issue with Narsie. This is the first time I have seen this but unfortunately I had deadmined that round in order to play, so I couldn't get more indepth information about what happened.

**Comment by clusterfack** [comment]
I don't think this is a map issue. But I'm curious as to where he hung, did it say NARSIE HAS ARISEN?

**Comment by clusterfack** [comment]
Please reopen this if you hear of this occur again.
