### ISSUE TITLE
Equal ruleset weights and its consequences have been a disaster for the server part 2: A response to @ShiftyRail

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26463]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
THERE ARE TOO MANY WIZARDS JESUS FUCK

**Comment by RaccoonBro** [comment]
make a github account instead of abusing the poor issue robot, dork

**Comment by DamianX** [comment]
reactionary

**Comment by DeityLink** [comment]
Things have been tweaked a bit by now, plus weights are highly reduced when the rulesets fired the rounds prior.
