### ISSUE TITLE
Beepsky doesn't seem to like corners

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26477]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
800a44d8bef2c45036f5dce0e4ef16b5ee1aac7e

# Description

Note to self for the future, if it tries to get a target who kicked it from a corner of tile-border glasses, it just strangely breaks.

**Comment by ShiftyRail** [comment]
Another issue alltogether
