### ISSUE TITLE
AI being put into Ninja trophy belt causes chat issues

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#26478]
#### Description of issue

When an AI is carded and put onto the trophy belt, the chat goes crazy in multiple ways:
Firstly, I could sometimes hear deadchat and sometimes talk in it.
Secondly, I could sometimes hear people speak who were nowhere near me.
Thirdly, the chat is being duped in increasing quantities. Noticed it going 3x at first, then it kept increasing to 23x. The Ninja wearing the belt could also hear it, causing him to lag and being validated. Ghosting in the belt made the horror stop for a moment, until the Captain put me into the restorer and I reentered, where it all kept happening.
Then I was put back into AI core, but none of the issues stopped until I typed "suicide"

#### Difference between expected and actual behavior

I expected the chat not to sperg out.

#### Steps to reproduce

1. be AI
2. have a Ninja go to your core
(3. get killed) Not sure if that's a necessary step
4. Get carded
5. Get put on trophy belt
6. Chat starts emitting mustard gas

#### Specific information for locating
![image](https://user-images.githubusercontent.com/22218882/81991490-a3996080-9641-11ea-95e0-d2c2731385a7.png)
![image](https://user-images.githubusercontent.com/22218882/81991826-62558080-9642-11ea-89e7-042d475475b2.png)

Goonchat hanging itself

#### Server revision
800a44d8bef2c45036f5dce0e4ef16b5ee1aac7e

**Comment by gurfan** [comment]
what the fuck

**Comment by StreptoMutans** [comment]
The special chat you get inside the belt still worked when the messages didn't end up in deadchat. It's a mysterious helltrip

**Comment by Kurfursten** [comment]
Fixing the belt is on my hitlist

**Comment by SonixApache** [comment]
Truly, ninjas are the most powerful anti-silicon tool we have. Getting silicon valids is one thing, but getting valids on the silicon player is the ultimate victory.
