### ISSUE TITLE
Beepsky hates tile-edge objects

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26485]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
e8d96be0f8f739648f3105744223f16b80bb98ad

# Description

If he gets a dense tile-edge object, like a window or a windoor in its path, he won't do shit.

Worst, he'll get PTSD and stand in place doing nothing after the initial bug happens.

**Comment by ShiftyRail** [comment]
he doesn't actually
