### ISSUE TITLE
People still have their flavor text after being burned, drained of fluids, having their soul ripped and their ID stolen

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2648]
http://s10.postimg.org/sl265e9ih/000_Hattu.png

**Comment by ComicIronic** [comment]
Flavor text is sort of awful anyways. I'd support removing it, since there's no checks on whether a sentence has to be conscious or unconscious or dead description.

Otherwise, no immediate solution I can see.

**Comment by Probe1** [comment]
flavor text is still broken anyways and only lets you get in about 50 characters before it cuts off.

**Comment by clusterfack** [comment]
Make the same code that makes someone (Unknown) should remove flavor text.

**Comment by Imagebard** [comment]
So are we going to fix this metagame extremo or not

**Comment by PJB3005** [comment]
People use flavour texts?

**Comment by Imagebard** [comment]
If someone has a flavor text, this is basically a solid way to know if someone is who they claim to be or not. Only some people use flavor text by default, but those who do are affected.

**Comment by ihadtoregisterforthis** [comment]
Can't the flavor text be tied to the name and appearance?

**Comment by WeinerMaster69** [comment]
I have a great idea
















































Remove flavour text all together

**Comment by Angelite191** [comment]
This was actually on my to-do list back when I was coding for this place. I was going to take @clusterfack 's approach to it but I realized that I'd also have to take the flavor text from people who got ling'd to give to the linger. There's also the fact that you'd to make an array sort of thing to store the flavor texts of the people you ling'd so you can get them back when you'r swapping around identities like a dirty whore. It's just so much more work than the whole dumb flavor text system is worth.

We can either implement a stricter flavor text system (preset character definitions you can select for different body parts to get dorf fort like body descriptions) which is very unlikely to happen, or we can take the master of weiners route and prune flavor text all together. It's done nothing but enable meat gaming, foster cancer, faggotry, and cancerous faggotry. Trust me, I would know about the last bit.

**Comment by Exxion** [comment]
On this server, maybe 30% of people who use flavor text use it for what it's actually for, and in exactly 0% of cases would removing it cause significant problems.

**Comment by 9600bauds** [comment]
Apparently flavor text also persists through ling transform

**Comment by Exxion** [comment]
Flavor text is attached to the individual mob for some fucking reason
It persists through ling transform but not cloning, etc.

**Comment by Intigracy** [comment]
Remove flavor text 2016

**Comment by Angelite191** [comment]
Let's make flavor text great again!

**Comment by Intigracy** [comment]
by removing it

**Comment by Imagebard** [comment]
Current issue number: 10107
This issue number: #2648

**Comment by Probe1** [comment]
That means its a pain in the ass to fix.

**Comment by 9600bauds** [comment]
Just nuke it
