### ISSUE TITLE
Every single one of Horizon's navbeacons is called "navigation beacon"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26484]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
e8d96be0f8f739648f3105744223f16b80bb98ad

# Description

Observed this while debugging a PTSD'd beepsky, it could be what makes him stand in shock and do fuck all.

**Comment by ShiftyRail** [comment]
this isn't the issue, the issue is me being legally braindead
