### ISSUE TITLE
[Request] Give The Barkeep Some Upgrades

### ISSUE THREAD

**Issue by Boxe** [d3athrow/vgstation13#2649]
i vote that the bartender needs some upgrades

like a drink dispenser that dispenses gin, vodka, etc but not full blown drinks
also a soda dispenser
also a bottle rack that functions like a smart fridge so you can keep bottles around without a huge fucking mess

**Comment by Probe1** [comment]
bottle rack is a must

**Comment by AutismSpider** [comment]
Move the Booze-O-Mat and Still.to Bar Storage room put in drink dispenser/soda dispenser.

**Comment by DeityLink** [comment]
If anything needs to be moved to the bar storage it's that fucking Ice Cream dispenser. But yeah barkeep needs some love, we talked about it over a month ago. I have a few ideas.

**Comment by AutismSpider** [comment]
Why does the barkeep have the fucking cream dispenser any way?

Take it out and put in a soda dispenser/drink dispenser hybrid.

**Comment by Probe1** [comment]
I feel like the addition of three new machines (brewer, cafe, that other one) the bartender can build, this has been fulfilled

@N3X15

**Comment by Zth--** [comment]
Also the bar needs some remapping, it's 0/10 comfy

**Comment by Kurfursten** [comment]
@clusterfack Seemed filled, close this
