### ISSUE TITLE
You cannot walk over hydroponics trays anymore

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2650]
Due to a recent update, you are no longer able to walk on hydroponics trays because they are solid again. You also are no longer able to spray them with plant-b-gone, unless you use some pull magic to pull the loosened tray under yourself, also spraying yourself in the process either way.

**Comment by eswordthecat** [comment]
https://github.com/d3athrow/vgstation13/commit/2b78e16bf38d54689aa2f5f839760d79d3723012

**Comment by wwjnc** [comment]
This is fixed but you can't interact with a tray in a diagonal direction if the orthogonal directions leading to it are occupied by a tray, so it's a hassle if you put multiple adjacent rows of trays because you need to move around.

**Comment by Probe1** [comment]
This has been fixed and can be closed 
@ComicIronic 
@wild-billy 
@ririchiyo
