### ISSUE TITLE
Killer tomato mobs do nothing

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2651]
If you create a killer tomato mob, they no longer even move on their own. You can shift their position and kill them, but they will sit in the same place forever. On a side note, they do not attack anything like they used to long long ago. Would be happy if killer tomatoes lived up to their name, or at least moved.

**Comment by ComicIronic** [comment]
Potential problem with A*.

**Comment by eswordthecat** [comment]
It's a feature request. Killer tomato is friendly since forever.

**Comment by Killette2** [comment]
The killer tomato was deadly a long time ago and invulnerable. So they made it friendly but killable, for some reason. It used to move similar to the old walking mushrooms, but now walking mushrooms also eat each other. Plant a killer tomato, and unlike it used to, it no longer idly moves like monkeys, slimes, or any other mob in existance. It just sits until moved by a mob.

**Comment by Killette2** [comment]
So the killer tomato now moves around and such but it doesn't really do anything and is just called tomato instead of killer tomato. Maybe It could get another mutation so the tree goes tomato>beef tomato>killer tomato where the killer tomato mob is actually aggressive.

**Comment by Killette2** [comment]
https://github.com/d3athrow/vgstation13/blob/master/code/modules/mob/living/simple_animal/friendly/tomato.dm

It also just seems odd that a plant called 'Killer tomato' is under friendly mobs. The friendly version should just be beef tomato and killer tomato should be a hostile thing

**Comment by Probe1** [comment]
they definitely move as of July 1st.

**Comment by ConkerDev** [comment]
Not a bug

**Comment by Zth--** [comment]
Close it
