### ISSUE TITLE
TRASH BAG PERMANENTLY GLUED TO SELF WHEN WORN WHILE FAT

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#26519]
1. wear trash bag on exosuit sprite

2. become fat

3. can't remove trash bag

4. become thin

5. STILL can't remove trash bag

6. trapped as a trash man forever

**Comment by drawsstuff** [comment]
you are what you eat

**Comment by RealestEstate** [comment]
I believe this has been reported before

**Comment by DamianX** [comment]
Duplicate of #20842
