### ISSUE TITLE
Toggle Floor Bolts Doesn't Work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26529]
(WEB REPORT BY: serwind REMOTE: 206.221.180.138:7777)
# Revision
0a67788c71803328ed9acf9702c20a4677abbf75

# Description

As AI, toggling floor bolts does nothing

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
what floor bolts?

**Comment by nervere** [comment]
No longer an issue.
