### ISSUE TITLE
Jukebox Immersion Ruined

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26525]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
0a67788c71803328ed9acf9702c20a4677abbf75

# Description
DARK RED off Steve Lacy's Demo is actually a few songs off Steve Lacy's Demo combined into one rather than just Dark Red

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Not really a bug please close @Kurfursten
