### ISSUE TITLE
Horizon: Entire Map Needs Area Redefinement

### ISSUE THREAD

**Issue by Accipitermaris** [d3athrow/vgstation13#26523]
[12:55 PM] small_boss: >literally half the station has no area set

this is a very general thing but a ton of zones on the map have no areas set and/or are missing APCs. i know there are a lot of individual issues open for APC problems but this is really worth making an issue for in general due to how wide reaching the issue is so it doesn't get forgotton about

**Comment by Kharkov72** [comment]
plosky...

**Comment by chaklett** [comment]
no escape apc
