### ISSUE TITLE
enable & fix or delete the PDA IRC app

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26549]
Apparently this is a thing, but it's commented out. But it's a loaded file in the RSC.
Someone should take a look at this, and either fix it up and get it in the game or throw it out. Based on the complete lack of code, I would go with the latter.

https://github.com/vgstation-coders/vgstation13/blob/d9e848094b6925abf2f76e05e25d483a69edf908/code/game/objects/items/devices/PDA/chatroom.dm#L1-L16

https://github.com/vgstation-coders/vgstation13/blob/9b553d820ba84cf56246637fa98bcb704ec075ff/code/game/objects/items/devices/PDA/PDA.dm#L706

**Comment by RaccoonBro** [comment]
TG had chatrooms years ago, got removed since nobody bothered to use them. Probably best they just get deleted.

**Comment by Exxion** [comment]
Another casualty of roundstart comms...

**Comment by SonixApache** [comment]
replace them with a SpaceChan app tbh
