### ISSUE TITLE
Windoors on Box stays permently opened 

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#26543]
#### Description of issue

All non-armoury reinforced windoors on Box will stay opened instead of closed by default. Clicking on it with the proper access will close it the windoor for a while, then it'll pop back open, which is the exact opposite of the previous behaviour.

#26506 (probably) did it.

Evil mappers strike again.

**Comment by DeityLink** [comment]
I'm gonna assume it's fixed by now, haven't seen it occur.
