### ISSUE TITLE
Mushmen darksight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26565]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
5fe14f48b619bbc0c031b216d58d63a82b865cb7

# Description
Mushroom men, the creatures thriving in darkness, have darksight like humans. 
# Steps to Reproduce
Be mushman, walk into maint tunnel, get disappointed that you, creture that's supposed to live in darkness, can't see jack shit in said darkness
# What you Expected
To be able to see far in darkness, like ninja or at least gray
# What Actually Happened
I can't see shit and have to rely on flashlights that starve me

**Comment by Kharkov72** [comment]
dont they have a verb that inverts it so you can see in the dark but not on the light

**Comment by SonixApache** [comment]
they do, yes
it's a spell

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/82613789-3c753200-9b94-11ea-9f5a-31e7e726dccc.png)


this is all it does though, nothing that having higher gamma cant already help you do or wearing mesons. without a light you can only see a single tile away from yourself.

**Comment by DeityLink** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/26881007/82613789-3c753200-9b94-11ea-9f5a-31e7e726dccc.png)
> 
> this is all it does though, nothing that having higher gamma cant already help you do or wearing mesons. without a light you can only see a single tile away from yourself.

wow that's awful
