### ISSUE TITLE
Glass Duplicating Bug

### ISSUE THREAD

**Issue by Senaat1** [d3athrow/vgstation13#2656]
You can use a shard and a welder to spawn infinite glass.

Step 1: Break a window and acquire a shard
Step 2: Get a welding tool
Step 3: Weld the shard, which will produce a sheet of glass on the ground.
Step 4: Switch to the hand that once held the shard. The shard is still here, but has no in-hand icon.
Step 5: Press the drop button, and a shard of glass should drop on the ground.
Step 6: Repeat step 3-5.

**Comment by DeityLink** [comment]
See? this is Alchemy. For everything, there is an opposite reaction. We get a bug that removes all the glass from the station at round start, then we get another one that let's us get infinite glass.

**Comment by clusterfack** [comment]
Thanks for the quick report

**Comment by clusterfack** [comment]
Should be fixed with https://github.com/d3athrow/vgstation13/commit/3e8e374d06407a5d591eff04576c7092f9a1b5a3
