### ISSUE TITLE
deathswaud mechs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26567]
(WEB REPORT BY: tristain01 REMOTE: 206.221.180.138:7777)
# Revision
5fe14f48b619bbc0c031b216d58d63a82b865cb7

# Description
death sqaud mechs dont start with cells in them.
# Steps to Reproduce
be death sqaud,get in mech,no profit.
# What you Expected
DEATH FOR THE GLORY OF NANOTRASEN!!!!
# What Actually Happened
room tempature coffee and a workers sensitivity training seminar

**Comment by Kurfursten** [comment]
Confirmed all marauders including seraphs and maulers start with no cell on live

**Comment by SonixApache** [comment]
this was fixed in #26604 (?)
