### ISSUE TITLE
mule bots don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26579]
(WEB REPORT BY: yocutzo REMOTE: 206.221.180.138:7777)
# Revision
89e16f62ba7eae1337840864044319467589aed3

# Description
they don't show up on the PDA app and the commands on the mule bots itself rarely work

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by SonixApache** [comment]
should probably find out what map this was on, could be a navigation beacon issue

**Comment by DeityLink** [comment]
Mulebots need a rewrite, in fact I'd argue most bots do. Our current AStar pathing solution too easily leads to endless path searching.
