### ISSUE TITLE
EMPs won't turn off headsets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26575]
(WEB REPORT BY: spyroshark REMOTE: 206.221.180.138:7777)
# Revision
a9c68de6588398630f194b2134e55e60bdd60cbf

# Description
When a headset is hit with an EMP you will still be able to speak over it even though broadcasting should be disabled

# Steps to Reproduce
Use an EMP grenade or EMP flashlight on a headset, then talk through it. You won't be able to hear yourself through the headset but other people will hear you on comms

# What you Expected
To not be able to speak on a headset while broadcasting is disabled

# What Actually Happened
Everyone can hear you when you talk over a disabled headset

**Comment by Kurfursten** [comment]
confirmed on live

**Comment by Killette2** [comment]
This has always been the case and I thought it was a shit feature and not a bug. You can only disable the earpiece but you can never disable the mic.

**Comment by SonixApache** [comment]
killette is right, this has always been the case
