### ISSUE TITLE
[Metaclub] Chem dispensers are starting at 0 instead of 50

### ISSUE THREAD

**Issue by invoid9** [d3athrow/vgstation13#2657]
yeah, what the title said. Boxstation's dispensers start at 50, while metaclub's start at 0, which is quite frustrating

**Comment by invoid9** [comment]
Also, I'm not sure if it's still a thing, but, the chemlab didn't start with a chemistry cleaner

**Comment by ComicIronic** [comment]
Caused by them not using the version used in mapping.
