### ISSUE TITLE
Entering the bar or the ghetto bar's area will stop your movement

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26585]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
47bb5cebba63d2412410d91c985eb4a6caadf3cb

# Description

See title. It ONLY happens with the bar or the ghetto bar, and only as a ghost. You are just stopped dead in your tracks and need to wait a split second before moving again.

No other areas transitions are affected.

**Comment by RaccoonBro** [comment]
probably the jukebox being a shit

**Comment by Exxion** [comment]
Yeah it's just network lag due to starting the streaming music
I don't really think it's fixable
