### ISSUE TITLE
Some wires that should be yellow are red

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#26586]
In #26471 I search-and-replaced for `/obj/structure/cable{` in order to avoid replacing cables of different colors such as `/obj/structure/cable/white`. I did not consider that south-facing knots would not have any vars overridden and therefore not have a `{` after the type.
![image](https://user-images.githubusercontent.com/6307265/82757441-c6b1d600-9de0-11ea-9a78-704d34eed17b.png)

**Comment by Kharkov72** [comment]
also the APC terminal sprite uses red wires so I am eternally triggered

**Comment by CptWad** [comment]
Are there other maps than box, deff and packed where this is an issue or is it only the three
