### ISSUE TITLE
gold grubs spawn near the TEG area in deff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26581]
(WEB REPORT BY: yocutzo REMOTE: 206.221.180.138:7777)
# Revision
89e16f62ba7eae1337840864044319467589aed3

# Description
they spawn near the outer catwalk area. no clue
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by CptWad** [comment]
🤔 does this, still happen?
