### ISSUE TITLE
Boxstation Kitchen Windoor stuck open

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26580]
(WEB REPORT BY: smallboss REMOTE: 206.221.180.138:7777)
# Revision
89e16f62ba7eae1337840864044319467589aed3

# Description
The secure windoor in the kitchen on boxstation is stuck open roundstart and cannot be closed.

**Comment by SonixApache** [comment]
How does shit like this even keep happening?

**Comment by ShiftyRail** [comment]
Same as #26543, mappers changing a variable on every windoor

**Comment by DeityLink** [comment]
I'm gonna assume it's fixed by now, haven't seen it occur.
