### ISSUE TITLE
AI mentions nuke AM-AIs chat

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#26592]
#### Description of issue

Activating "AI mentions" causes beeps on every chat message, and mutilates the chat. Happened on the AI name of "AM"
![image](https://user-images.githubusercontent.com/22218882/82776832-8a1bc400-9e4c-11ea-8a4c-190eaa898f90.png)

#### Difference between expected and actual behavior

Expected a good feature, got useless spam

#### Steps to reproduce

Set AI name to "AM"
Press the "activate AI mentions" button

#### Specific information for locating
#26333 
#26460

#### Server revision
beb84d87d66d14cc6e47d03d44552793a1c19df0

**Comment by Exxion** [comment]
It looks like it's catching something inside an HTML tag, maybe? That's not good
We can fix that, but you're still going to get a lot of false positives when you have a name that short anyway

**Comment by StreptoMutans** [comment]
It also triggers when a pAI says something, and on AI private channel. Which should happen for all AI names

**Comment by nervere** [comment]
This was fixed in #27928
