### ISSUE TITLE
ghosts can't move around in the hallways

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26595]
(WEB REPORT BY: mentgah REMOTE: 206.221.180.138:7777)
# Revision
beb84d87d66d14cc6e47d03d44552793a1c19df0

# Description
see title
# Steps to Reproduce
>be ghost
# What you Expected
to float around freely
# What Actually Happened
movement gets interrupted
additional notes:
(Follow) DEAD: Tess Dummy whines, "seems to be"
(Follow) DEAD: Tess Dummy whines, "sound rendering relatyed"
(Follow) DEAD: Tess Dummy complains, "delay from changing music zones"

**Comment by ShiftyRail** [comment]
#26585 ?
Exxion says it's not fixable, but it wasn't an issue before #26355, wasn't it ?

**Comment by mentgah** [comment]
it never happened before that pr passed, I think

**Comment by ShiftyRail** [comment]
Oh, I know why this happens.

**Comment by Exxion** [comment]
Oh, it's always happened on slow connections, but apparently that made it happen for everyone
