### ISSUE TITLE
No longer able to read newscasters as ghost.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26598]
(WEB REPORT BY: pancakemines REMOTE: 206.221.180.138:7777)
Because of whatever fix was put it because of casualbro I would assume, you can no longer read newscasters as ghost and you can't read papers either. News often gets ignored enough as is please make it so I can read it again as a ghost/obs. My solution; permaban casualbro and revert the fix, easy. I WANT MY NEWS.

**Comment by ShiftyRail** [comment]
fuk you obsgang
