### ISSUE TITLE
Vox CE's suit does not protect from being on fire

### ISSUE THREAD

**Issue by GalaxyGryphon** [d3athrow/vgstation13#2660]
walked into a fire and instantly died GG, seems to be fine for protecting from heat but i was dead pretty quick from being actually on fire.

this was from a flame thrower.

**Comment by GalaxyGryphon** [comment]
actually the suit works fine in heat, it just didn't work for being on fire.

**Comment by ComicIronic** [comment]
Should have been fixed in a5c98594. Reopen if not fixed.
