### ISSUE TITLE
"Station has cleared the meteor storm" is inaccurate

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26601]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
b9a24883bc1f17baaf3c5550993d0f1bc4a4ef75

# Description
This has happened as long as I can remember, but the Galactic Empire Update stating that the station has cleared the meteor storm is comically inaccurate - it usually fires right in the middle of a massive wave of asteroids.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
It fires after the last wave of asteroids has been launched, but it takes time for them to actually reach the station
If I had to guess, it's probably timed to appear after they'd be over back before we made Z-levels huge, but now that the meteors have longer to travel, it's early
