### ISSUE TITLE
Kudzu not growing out of its tray

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26619]
(WEB REPORT BY: baronze REMOTE: 206.221.180.138:7777)
# Revision
a8aacb768e943a059117afcd4e648215558372a7

# Description
Made an emp kudzu(rocknuts+glow berries), little bitch refuses to leave its tray i want my money back.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
need more info
