### ISSUE TITLE
Esc doesnt close say or me boxes anymore

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#26616]
#### Description of issue

in hotkey mode popping up chat you used to be able to hit esc to close it, you cant anymore

#### Difference between expected and actual behavior
esc getting me back to movin in a pinch.
esc does nothin

#### Steps to reproduce
press f3 or t or whatever, try to hit esc

#### Server revision

a8aacb768e943a059117afcd4e648215558372a7

**Comment by Exxion** [comment]
You may want to check your skin file. This works for me.

**Comment by Dacendeth** [comment]
I tried deleting everything in my documents byond folder, where the skin file seems to be and getting a fresh everything and it still persists, It does seem I am the minority with this issue though.

**Comment by Dacendeth** [comment]
Works for me on the test server still, just not live and im having multiple people tell me it's never worked for them, really at a loss now.

**Comment by Dacendeth** [comment]
Upgraded to latest beta fixed it.
