### ISSUE TITLE
No way to get virology vials

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26613]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
d508125db02727af9daaa41d0138bb0b63787202

After the initial 6 from virology are gone, you're fucked. If an antag destroys 6 and releases a virus above 50, you might as well call the shuttle because you are not curing that bitch

**Comment by Dacendeth** [comment]
You can autolathe vials.

**Comment by Kurfursten** [comment]
They are available at the autolathe, inside the medivend, and you can also get more from the DIY Dr. Pecker kit at soda vendors.
