### ISSUE TITLE
[Metaclub] There are no mining vending machines

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2661]
Someone re-did the asteroid and forgot to add them.  Whoops.  Fix em please.

- 13 hour later edit:  Map design wise, the vending machines were on the asteroid originally and that's a crappy idea.  I have to go to the station to use the ore machine, get money, head back to the asteroid, spend money, then potentially head right back to the station!

Keep the vending machines on the main station level.  Since Cargo is pretty empty on meta this is not a problem

**Comment by d3athrow** [comment]
@iratepirate

**Comment by IratePirate** [comment]
Noted it down. Will fix pronto.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/pull/2676
