### ISSUE TITLE
Messagebox will not load

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26622]
(WEB REPORT BY: fishgrease REMOTE: 206.221.180.138:7777)
# Revision
a8aacb768e943a059117afcd4e648215558372a7

# Description
Messagebox will not load
# Steps to Reproduce
Joining the server
# What you Expected
For the messagebox to load

# What Actually Happened
It did not load

**Comment by GreasyFishy** [comment]
nvm fixed it (I'll pm the fix)
