### ISSUE TITLE
Clean up blood bag code

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2662]
Those empty blood bags stay labeled as empty blood bags forever.  Right now the only thing you can do about it is label it with a hand labeler (which medbay fortunately has) and hope people ignore the EMPTY BLOOD BAG portion and read the (FILLED WITH O-) portion.

Can't we fix this up somehow to look better?  Maybe remove 'empty' and just have them called blood bags.  That way they don't look dumb when they're filled and still labeled as empty despite clearly being filled.

Second part to improve blood bags - have their unit amount displayed on shift click.  If the bag has half the blood left let it say that.  Either precisely (110 of 220) or vaguely (looks about half full) or however you please.  Those two things would really polish up blood bags.

**Comment by d3athrow** [comment]
Vaguely remember being able to use a pen on blood bags.

**Comment by Probe1** [comment]
You can only use a labeler and it still says EMPTY BLOOD BAG (O-).  Pens work on beakers though.

**Comment by Kurfursten** [comment]
Addressed by https://github.com/d3athrow/vgstation13/pull/3349

**Comment by Probe1** [comment]
addressed by [3349] like the man says
