### ISSUE TITLE
mechs are fucked, fucked!

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#26634]
#### Description of issue

The mech HUD hasn't been displaying, things like the equipment icons on the top right don't appear and you need to use the stats menu. 

Sometimes DNA-Locked mechs can become irreversibly fucked and will not let anyone enter, even the person who locked them. (see below)

#### Difference between expected and actual behavior

Expect ordinary mech HUD, get nothing.

For the "Access denied" issue, I've noticed it a couple times, here's what caused it recently.

-DNA Lock a mech
-Exit mech, ask captain to give it additional access
-Captain swipes ID and sends it into maint mode, edits operation keycodes and finishes
-Maint mode can be initiated and terminated as usual, but neither me nor the captain could access the mech. Locking and unlocking through the mech console does nothing

#### Length of time in which bug has been known to occur

I don't know how long the locking issue as lasted, but the HUD issue is recent since I remember being able to see it in the past.

#### Server revision

[bugfix]

**Comment by 9percents** [comment]
I laughed at 2nd part, operational keys isn't the access tied to mech, but access reqs, meaning if you add surgery to it, it will only allow someone who has surgery access to operate it

did captain give you his ID to try to get in the mech?

**Comment by gurfan** [comment]
the captain used his ID and edited it himself. He was giving me maint and firelocks access. He wasn't able to access it himself, but that's probably from the dna lock. I thought operation keycodes were related to access requirements because I was able to give an MMI mech all access using them, but I'm probably misremembering it.

cap never gave me his ID, I should have tried that

**Comment by 9percents** [comment]
I think it's probably the unintended way MMI mechs work, maybe they get the access required to pilot when inserted, that way they get all access if mech requires all access to pilot
