### ISSUE TITLE
RECHARGER MACHINE BROKE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26638]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
a407fc1f5c25cbce8b653c553f53be294d15b071

# Description
recharger machine broke, can't be wrenched to move, dismantled, or used for charging.
# Steps to Reproduce
get recharger, try to put in RCS - no result. Try to unwrench recharger - no result. Screwdriver to dismantle it - no result.
Try to put in laser pistol, stun revolver - no result
# What you Expected
recharger to recharge
# What Actually Happened
recharger no recharge

**Comment by Kurfursten** [comment]
Was it powered?

**Comment by Dacendeth** [comment]
RCS?
