### ISSUE TITLE
new "say" window is chunky

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#26647]
#### Description of issue
Say window blocks other dialogues, meaning that you can't open another (blocking) dialogue window until it closes (which also means you can't have multiple Say window opens)
it also takes like half a second to actually open.
BYOND version is 513.1525. updating to 513 fixes not being able to close it by hitting esc, but nothing else.

also, Pomf just said you can get around it for now by rebinding the key to the old verb, `say` (or just manually typing it in), since it still exists

#### Difference between expected and actual behavior
expected to be able to type right after I hit the key instead of potentially executing other commands because I start typing immediately
expected to be able to open multiple Say windows (mainly for silicon ""fun"") instead of being locked for 10 windows cause I hit the key 10 times

#### Steps to reproduce
enable hotkey mode and hit T (or manually type in the new command, I guess)

#### Length of time in which bug has been known to occur
it started somewhere between 1a1e70753770215f4a3d88eb76bbd6e9c168d02f and b72127f60f54a5073e3bc02b9d3afd8bde81c947, as I tested the latter commit and the commit just before the former (2f2028676c7540d9e7fe220faca18bcdbf295da3)

#### Server revision
c2a5b4649b6657b9eb5bdaa0c622daae1cae212d

**Comment by ShiftyRail** [comment]
Rebinding the window to "Say" prevents the code displaying the typing overlay, if you have that enabled, to be called. I *think* I know how to fix this, but I'm not sure.

**Comment by Kammerjunk** [comment]
it has absolutely nothing to do with the overlay. the issue is the window itself.
source: don't have the overlay enabled

also don't "fix" it so `Say` still toggles the overlay, that's exactly what I want because it's free from the apparent gunk of `.Say` that I described just above

**Comment by ShiftyRail** [comment]
The idea is obviously to fix the lag to `.Say`.
