### ISSUE TITLE
[META] Metastation needs to be updated to vgstation code

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#2664]
1.Machine in corporate showroom next to "the perfect man" seems to be gone.
2.Mechanics needs somewhere to do his job
3.???
4.If i remember something else i'll update this

**Comment by Probe1** [comment]
> Mechanics need somewhere to do his job

Huh?  
![image](https://cloud.githubusercontent.com/assets/8550416/5948361/54301508-a712-11e4-9c70-84f3c5b625a5.png)
