### ISSUE TITLE
Colt single action army can't be reloaded

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#26640]
another fucking problem from #26608 
it requires the empty bullet casings be removed before it can be reloaded, but using its attack_self merely spins it because its super cool
`works with the colt` huh, you think someone would do that? just lie in a pr?

**Comment by Irradiation** [comment]
[UNFORESEEN CONSEQUENCES]

**Comment by Kharkov72** [comment]
actually it can be emptied, but it needs to be fucking alt clicked? piece of shit, make the spin the alt-click since normal-inhanding to empty is how the other guns empty which probably means move it cocking to its attack
