### ISSUE TITLE
Virology symptom suggestion: Afflictus Emittus

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#26649]
![image](https://user-images.githubusercontent.com/6062247/83340118-55af6a00-a289-11ea-8e5e-6db0eef82789.png)

Probably stage 4
Makes you constantly have an emitter beam coming out of your face.
It does way less damage than a normal emitter but can still rarely break lockers and make shards radiate

**Comment by SonixApache** [comment]
combine with vox pox for _laser beak_

**Comment by deadharold** [comment]
Repoban

**Comment by DeityLink** [comment]
sounds beneficial to me :^)

**Comment by DeityLink** [comment]
Gotta check if emitter code allows for constantly moving beams

**Comment by kilozombie** [comment]
> Gotta check if emitter code allows for constantly moving beams

Deadharold tested it and it can work I think, but unanchored emitters turn off repeatedly, seemingly every tick

**Comment by Exxion** [comment]
Oh god please don't add things that use beams they're so fucking buggy

**Comment by kilozombie** [comment]
> Oh god please don't add things that use beams they're so fucking buggy

Who cares about your lame opinion. Bugs are healthy for the environment. They compost materials and pollinate flowers

**Comment by beesil** [comment]
Virus engine? 👀

**Comment by DeityLink** [comment]
@Exxion wouldn't that be a great opportunity though to freshen up beam code?

**Comment by DeityLink** [comment]
Ok nevermind, this isn't suitable as a virus symptom at all with emitter beam code. Better make new beams from scratch, this is ridiculous.
![image](https://user-images.githubusercontent.com/7573912/83342906-c50e7380-a2f4-11ea-92ba-d93df32b5867.png)
![image](https://user-images.githubusercontent.com/7573912/83342908-c8a1fa80-a2f4-11ea-9bd3-6f49ffd2e9f3.png)

lagging like crazy.

**Comment by Exxion** [comment]
I was working on rewriting beamcode a while ago but stopped due to something about movecode that has since been changed, so I could probably pick it back up
However I can't guarantee that it wouldn't still lag just because of how beams must necessarily work

**Comment by kilozombie** [comment]
I can't believe the madman even attempted it

**Comment by DeityLink** [comment]
Do not lose hope just yet
![image](https://user-images.githubusercontent.com/7573912/83353909-05520e00-a356-11ea-8b2f-8f12a34267e5.png)
