### ISSUE TITLE
Hitting the escape key in "say" window no longer closes it

### ISSUE THREAD

**Issue by streaki** [d3athrow/vgstation13#26642]
#### Steps to reproduce
Hit T in hotkey mode or F3 in any mode, then hit Esc
#### What you Expected
the "Say" window to close
#### What Actually Happened
it don't close

**Comment by ghost** [comment]
Check #26616 and please let us know if it's still happening after following the instructions there.

**Comment by streaki** [comment]
Didn't help, I even tried deleting the entirety of my Byond dir in my documents.
Admittedly, I'm playing on Wine, might be related to that. Though it shouldn't be.

**Comment by d3athrow** [comment]
works on my machine

**Comment by ShiftyRail** [comment]
Fixed
