### ISSUE TITLE
Malf Ending Issue

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#26646]
When the Malf AI ends by nuking the station, it kills itself, thus triggering the FACTION_DEFEATED stage after the round should be over, calling the shuttle on a 10 minute timer even though everyone's dead.

**Comment by SonixApache** [comment]
was this not listed in #23072 ?

**Comment by Kurfursten** [comment]
Yeah, this is different

**Comment by kernikov** [comment]
This is still an issue as of August 27.
![image](https://user-images.githubusercontent.com/5549060/91484518-fb657b80-e86e-11ea-9895-c4f795a36a24.png)

**Comment by SonixApache** [comment]
#23072 remains up-to-date.

**Comment by DeityLink** [comment]
Fixed by #27727
