### ISSUE TITLE
Red X over exosuit slot as a plasmaman

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#26651]
#### Description of issue

![image](https://user-images.githubusercontent.com/26881007/83344621-73a3bb80-a2d7-11ea-9341-a271b50e4b67.png)
every round I have this, it doesnt seem to do anything though.

#### Difference between expected and actual behavior
 no useless red x, got one.

#### Server revision

Revision: c2a5b4649b6657b9eb5bdaa0c622daae1cae212d

**Comment by chaklett** [comment]
who care

**Comment by Dacendeth** [comment]
it's not doin this anymore
