### ISSUE TITLE
Brains Don't Need Attaching!

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#26660]
You know how you normally fixovein something to secure it once it has been inserted? You don't need to do that with brains, there's no penalty for having a separated brain. In fact, I doubt it matters for eyes either, based on the code. Kidneys and livers definitely have a consequence. Unsure on lungs.

**Comment by strawberrytan** [comment]
You do need to attach eyes for sight, this is unique to the brain
