### ISSUE TITLE
bbcode is not working properly

### ISSUE THREAD

**Issue by Riukanojutsu** [d3athrow/vgstation13#2666]
When you use a fonction is applies it to the whole paper instead of the part where you want it to apply.

**Comment by Riukanojutsu** [comment]
Yea actually im stooped and made bug report on tg instead of vg first. which would explain why i didnt see it in the github. My va

**Comment by Riukanojutsu** [comment]
My bad*

**Comment by d3athrow** [comment]
when was the last time you remember this working properly.

**Comment by Riukanojutsu** [comment]
Ive only recently started to use paper. Is this the kind of thing thats been buggy since day1 and will never be fixed?

**Comment by ririchiyo** [comment]
This should behave differently now.
