### ISSUE TITLE
CARGO SHUTTLE TIMER INDICATORS ARE STILL NOT LINKED TO THE CARGO SHUTTLE

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26668]
#### Description of issue
whoever broke this fucking thing, please unbreak it

Game: a76566e8a675818b3a0600ce53a4c45d84fddedf 
Patches: f5d3ae3ebbf122edba71e667a0197c8716bce266

**Comment by DeityLink** [comment]
I think it's fixed by now?
