### ISSUE TITLE
Custom Shuttles still borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26676]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
75db289e16a4e2c3db1fc1a7127f4fc8c51e3300

# Description
When you "move it" the console states it has arrived at the location even though it doesn't move. After that, it gives this error:
ADMIN LOG: WARNING: A shuttle (Cargo Shuttle; /datum/shuttle/custom) has attempted to move to a location which overlaps with its current position. The shuttle will not be moved.
# Steps to Reproduce
make custom shuttle, try to move
# What you Expected
go
# What Actually Happened
no go

**Comment by ShiftyRail** [comment]
dupe
