### ISSUE TITLE
glasses aren't visible under transparent helmets

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26684]
#### Description of issue
you can see the eyes but not the glasses covering the eyes which is silly

**Comment by DeityLink** [comment]
So the problem is that the IGNORE_INV flag that allows clothing to not hide the stuff it covers doesn't discriminate between what to hide/show.

For example, if someone is wearing a bio hood, you have to either hide their hair AND their glasses, or neither. Looks like we have to add another flag.

**Comment by DeityLink** [comment]
@SonixApache are you thinking of some helmets in particular?

**Comment by DeityLink** [comment]
There's also the problem of face/eye/ear accessories that should be visible through the cover, but not go through them. See for instance how gas masks would appear through bio hoods looking to the side even though they should be visible when looking down 
![image](https://user-images.githubusercontent.com/7573912/83675152-d7303080-a5d8-11ea-96e3-20a326e8200d.png)

**Comment by SonixApache** [comment]
I was mostly just thinking of the security helmets, since they very obviously lack the HUD sunglasses that are almost always worn behind them.
