### ISSUE TITLE
Space Pod (built in Space Pod bay) is immovable

### ISSUE THREAD

**Issue by omeno** [d3athrow/vgstation13#2668]
After constructing a space pod in the space pod bay you can't move it, while inside you'll see the battery drain as if it were in movement the pod itself is inert.

I'll get around to testing the space pod that is spawned out in space to see if that works at some point soon™.

**Comment by NigglyWiggly** [comment]
I've now gotten about 3 or 4 ahelps about this, haven't tested it myself but I can confirmed that they aren't working.

**Comment by NigglyWiggly** [comment]
Can now confirm that space pods that are spawned in don't work either

**Comment by d3athrow** [comment]
Looking like a byond bug at the moment with bounding sizes
