### ISSUE TITLE
you can click-drag things into disposals as a ghost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26685]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
if i dont make this bug report ill get my peepee slapped

**Comment by drawsstuff** [comment]
feature

**Comment by PrimeDSS13** [comment]
I think it's also important here that as a ghost you can click-drag intercoms off the wall and into disposal bins. Very nice.
