### ISSUE TITLE
Xenoarch suspension field generators become unresponsive

### ISSUE THREAD

**Issue by AceDick** [d3athrow/vgstation13#2670]
Found that on some occasions, seemingly randomly after inserting your ID the suspension field gens become useless, any clicks on the panel options are unresponsive, and you are unable to switch fields, turn it on or off, or lock it.

**Comment by AceDick** [comment]
Seemed to work alright when slotting your ID into the field, but clicking the machine with your ID screws it up and causes this to happen.

**Comment by d3athrow** [comment]
This should be fixed with d9845590303c933d4d8bb80091335501d01777aa
