### ISSUE TITLE
ADMIN LOG: Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'gillihead' OR cuiRealName='*')' at line 1

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#26709]

**Comment by jknpj** [comment]
Happens to Shifty O'Rail names

**Comment by DamianX** [comment]
Do we just dump raw strings into SQL queries? that's pretty epic

**Comment by ShiftyRail** [comment]
Not raw strings. They're using the BSQL sanitisation thing which breaks for a single quote.

**Comment by DamianX** [comment]
So is this fixed?

**Comment by ShiftyRail** [comment]
#26713 
The only actually unsanatised items were ckeys and character names, the rest were just sanitised in their own proc rather than through the lib.
