### ISSUE TITLE
Streaming media doesn't stop when you move from one area playing media to another area playing different media

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#26715]
Gee Bill! How come your mom lets you listen to TWO songs?

@ShiftyRail

**Comment by ShiftyRail** [comment]
Can't reproduce on local, having a juke on the bar, another in the hallway, it stops when I switch areas. The only time they play one over the other is if there's less than 10 seconds on the track.

**Comment by Exxion** [comment]
Try the sound systems in the hall instead of another juke

**Comment by ShiftyRail** [comment]
This was it
