### ISSUE TITLE
[Feature Request] Add notifications that flatpack steps have begun

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2671]
Flatpacks occasionally have the wrong step listed and you have to rely on audio cues to know if something is working or not.  To get around that and just in general give good player feedback, please add "You begin to weld the plates" et cetera when doing each step.  The same goes for disassembling catwalks with a screwdriver which can take some time and has minimal cues to let you know you've successfully done something.

**Comment by Riukanojutsu** [comment]
Flatpacks only have wrong instructions if you are uaing paper instead of nanopaper. Which you should never do anyways since you have an indinite ammount of nanopaper

**Comment by ComicIronic** [comment]
I don't know who informed you of this, but it is untrue.
Any type of flatpack can make misprinted instructions, but the chance for any instruction is quite low and it can only happen once per flatpack.

The suggestion is sensible, anyhow.

**Comment by Riukanojutsu** [comment]
Really? Whenever I used paper id get incorrect imstructions and I never had a problem with nanopaper.

**Comment by Probe1** [comment]
@Riukanojutsu you're super lucky.  Start playing outbomb cuban pete.

**Comment by Probe1** [comment]
Catwalks now have appropriate feedback that indicate its working.  Strike that from the list.
