### ISSUE TITLE
[Request] Boxstation needs a freezer in toxin storage

### ISSUE THREAD

**Issue by wiredhuman** [d3athrow/vgstation13#2672]
Since player built freezers dont work, it would be beneficial to have one in toxin storage at roundstart already. 
Its usually built the second the circuit becomes avaliable, so Im pretty sure no harm´s done.

**Comment by GalaxyGryphon** [comment]
player built freezers you just need to get good, the pipe needs to be facing south and you can only attach more pipes to it south, its a feature!!

**Comment by d3athrow** [comment]
I tried to get nexis to fix freezers, nobody wants to touch pipenets.

**Comment by clusterfack** [comment]
I fixed freezers and heaters @d3athrow

**Comment by Konater** [comment]
If we're adding things that get built a lot there would be a lot of chemistry dispensers suddenly

**Comment by wiredhuman** [comment]
Chem dispensers work as indended tho, so your analogy a shit, Konater.

But since clustefack fixed em the request is dropped.

**Comment by clusterfack** [comment]
>request is dropped
