### ISSUE TITLE
BEE BUG

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2673]
Bees are now like all other simple mobs. You can no longer walk through them, and if there's many bees you can't move through botany without help intent. They also shift you around when you do have help intent on. This is a nightmare for me.

**Comment by Duny-** [comment]
WHO DECIDED YOU SHOULDN'T BE ABLE TO WALK THROUGH BEES

**Comment by d3athrow** [comment]
BEES

**Comment by d3athrow** [comment]
316fd5f4c41428769ef3ba497677dce7abb53aeb

**Comment by clusterfack** [comment]
NOT THE BEES

Also closeable, yes?

**Comment by ComicIronic** [comment]
Reopen if it's still an issue.
