### ISSUE TITLE
[Idea Poll] Flies over dead bodies

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#26740]
So that's an idea I had for PR but given its potential impact on the gameplay I wanted to gather some opinions on the matter first. The basic idea is this:

A new kind of bugs that can fly in swarms, like bees, "**spess flies**" (or just flies really) that automatically spawn and hover over dead bodies left in the open for more than X minutes (5? 10? 30?). They are mostly cosmetic though they can be killed like bees (and unlike bees, don't get angry). They can spawn as long as the dead human are either on the floor, or in a container that's on the floor (in all cases, only in an area with suitable air conditions). 

**Exceptions are body bags, morgue trays, fridges**, that automatically prevent the spawn of flies, containing the body in two layers of containment may also work. However dead bodies in lockers that aren't in a body back will eventually cause the appearance of flies around the locker.

More exceptions could be added such as the mob's species (skellingtons won't attract flies) or reagents (mobs with some specific reagents in them won't attract flies), as well as the mob's clothing (low permeability clothing such as hardsuits and biosuits would prevent flies spawning)

The flies will despawn by themselves if the body is moved (though they may respawn at the body's new location after a while), placed in a body bag, destroyed, etc...

A wild ride medbay full of bloody dead bodies might look even nastier than usual.

![flies](https://user-images.githubusercontent.com/7573912/84011429-64c3a580-a976-11ea-846d-2df7c6e6bbd8.gif)

**Comment by Kurfursten** [comment]
What would they do?

If the answer is nothing, you could just make it a simple overlay

**Comment by tuypo1** [comment]
Doesn't sound great for immersions that the flies somehow end up on station to begin with but then there are plenty of things that end up on station that logically shouldn't so I suppose that's not a big deadl

**Comment by DeityLink** [comment]
@Kurfursten nah I want to give people the options to spray/catch/kill them, bee mobs without any of the bee pathfinding for plants and enemies are quite cheap. And they'd also benefit from the swarm behaviour and "procedural" movement.

**Comment by SageOfLight** [comment]
Only if we can cook them as french flies.

![image](https://user-images.githubusercontent.com/10042344/84024059-ce2fbe00-a94e-11ea-9549-51fd4cedf0d1.png)

**Comment by DrSnips** [comment]
Personally I don't see much coming out of this and I'd rather not have more garbage floating around in halls/medbay. Generally speaking when there's dead bodies lying around there's already enough shit laying around and doesn't need even more noise.

**Comment by Zth--** [comment]
reminds me of #16118, rip in pieces (the code is probably not recoverable, almost guaranteed shitcode)
