### ISSUE TITLE
PDA messages cannot be read by ghosts

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#2674]
Ghosts cannot read PDA messages, even with the preference set to read. I suspect it has to do with the new say code.

**Comment by d3athrow** [comment]
pda messages are unrelated to say code.

**Comment by gbasood** [comment]
Worked fine for me recently as well.

**Comment by sonime** [comment]
just tried it some more, it worked once and then stopped,

**Comment by d3athrow** [comment]
I looked over it agian and i can't see any issue.
