### ISSUE TITLE
The SAC doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26750]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
8d8e3ef742a9db9106924df57b3812e7aba6bd70

# Description

Ko-fi links were a mistake

**Comment by ShiftyRail** [comment]
More precisely, it doesn't seem to receive or push any info BEFORE someone interacts with it once.
Maybe it is dependant on the nanoUI being initialised first.

**Comment by SonixApache** [comment]
That's interesting, I'll look into that.

\*edit*
Can't reproduce this.
Spawn in, strip an SPS, kill an SPS holder, interact with SAC - alerts are present.
Maybe some sort of server hiccup or init failure?

If it happens again, ask an admin to VV the console and check the `saved_security_alerts` var.

**Comment by DamianX** [comment]
Is it possible nano randomly displayed its classic empty window for no reason and this was just that?
