### ISSUE TITLE
problem with masks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26753]
(WEB REPORT BY: assburgeri REMOTE: 206.221.180.138:7777)
# Revision
7b14c9d79251269e92dc04ed4ef1a10ce29c44be

# Description
putting a gas mask doesn't appear on sprite
# Steps to Reproduce
take a mask
wear it
nothing in ur sprite
# What you Expected
mask in sprite

**Comment by SysadminJeroen** [comment]
All masks are bugged right now, including the clown's mask.
The mask icon shows up in the examine output, but doesn't show on the person in the viewport.

**Comment by SysadminJeroen** [comment]
![dreamseeker_Ybj0R9r8ZM](https://user-images.githubusercontent.com/2915526/84139482-3914ee00-aa50-11ea-9ab9-6084517892cd.png)
Looks like it isn't 100% a missing sprite.
