### ISSUE TITLE
BoxStation ATM spawns money under the Restroom Doors.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26755]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
56bbd549cb8413b61baf6856190c306ccf8a27a7

# Description
I was taking some money from my account to play on the slots, but the money didn't appear to spawn, after help from meetmeindorms, I found them under the Unisex Restroom Door.
# Steps to Reproduce
Insert your ID on the ATM, try to withdraw funds directly.
# What you Expected
The credits to spawn under me on on the ATM.
# What Actually Happened
The credits spawned under the Unisex Restroom Door, leading me to think that the ATM lost them.

**Comment by RaccoonBro** [comment]
why is atm code so bad agh
