### ISSUE TITLE
You can fit an infinite number of cigarettes in your mouth

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#26768]
#### Description of issue
![cigstack](https://user-images.githubusercontent.com/51391726/84200278-78edcc80-aa74-11ea-9274-b6bbbcfea239.png)
![filephoto](https://user-images.githubusercontent.com/51391726/84200291-7c815380-aa74-11ea-96bf-e9bc9cda48e5.png)
#### Steps to reproduce
Try to put another cigarette in your mouth, instead of replacing they just combine

**Comment by boy2mantwicethefam** [comment]
![gentlemen](https://i.kym-cdn.com/entries/icons/facebook/000/000/088/Gentlemen.jpg)

**Comment by Kharkov72** [comment]
feature

**Comment by DrSnips** [comment]
I say deem this one a feature. Pretty funny.

**Comment by pwnzer185** [comment]
![733bb15676ed5e4bd4feabaa91c1d611](https://user-images.githubusercontent.com/60371703/84200630-23fe8600-aa75-11ea-98bf-4ecb93e698df.png)

**Comment by GreatBigFailure** [comment]
Only thing I can think of that might cause problems is facehuggers since they're considered a mask. Turning on internals might cause ragnarok? I say test the few things that could go wrong before we fix it and if not then it's a feature

**Comment by BomberBro** [comment]
Unfortunately this doesn't show up in their description, an observer can only tell if they're chain smoking by VV'ing their contents. Beyond that, this also allows you to stack an infinite number of masks via cigarettes which is gunky as hell (sadly only one shows up as the icon)
![maskstack](https://user-images.githubusercontent.com/51391726/84201001-9bccb080-aa75-11ea-866e-ef88d3895ced.png)

**Comment by Dacendeth** [comment]
Good luck trying to suck my blood vampire im behind 7000 clown masks.

**Comment by west3436** [comment]
feature

**Comment by DeityLink** [comment]
ok that's completely my fault, I'm on it

**Comment by SonixApache** [comment]
also, if you have a mask you can't take off, like the happiest mask or a cursed clown mask quick-equipped a cigarette makes it go into your pocket and override whatever's in there
functionally giving you a third pocket slot - the item in your left slot stays there till removed but the pocket can still be used
