### ISSUE TITLE
"Make all areas powered" secret seems to have broken

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26779]
#### Description of issue
secrets -> Fun Secrets -> Make all areas powered
doesn't seem to do anything - APCs are not charged
i blame get_cell()

#### Difference between expected and actual behavior
press button, all APCs charge to max
vs
press button, nothing

#### Server revision
5395b46d85c69bbe3611f687f075dcca260ad980

**Comment by Exxion** [comment]
IIRC this secret simply doesn't do what it sounds like and never has (well, not for several years at least)
It just cancels the blackout secret/event
I could be wrong though

**Comment by DamianX** [comment]
Exxion is correct.
"Power all SMES" is the secret you are looking for.

**Comment by SonixApache** [comment]
then i am a fool, thank you
