### ISSUE TITLE
Hardsuit mod stations can be activated multiple times to install mods multiple times

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26795]
(WEB REPORT BY: hatterhat REMOTE: 206.221.180.138:7777)
# Revision
22e973e964523aba82396fcd25d65769443c6410
# Description
Hardsuit modification stations can be clicked repeatedly to install a given module repeatedly, stacking effects and power draw.
# Steps to Reproduce
* Step in a hardsuit modification station.
* Click on it repeatedly.
* Wait for all the modules to install. This takes a while.
* Realize you have so many modules.
* Realize the power draw is godawful and you have nobody else to blame but yourself for this.
# What you Expected
Hardsuit modules to only install once.
# What Actually Happened
Stackable hardsuit module installation.

**Comment by Kurfursten** [comment]
@jknpj
