### ISSUE TITLE
Can't press E to quickswap some glasses anymore.

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#26819]
#### Description of issue

Pressing E attempts to place some glasses like mesons over whatever glasses you're already wearing, rather than quickly swapping one pair for another.

#### Difference between expected and actual behavior

Wear glasses/goggles that can't have mesons worn over them, like welding goggles. Press E on hotkey mode while holding mesons expecting it to exchange my goggles for my mesons. Instead get a message saying the mesons won't fit, and have to manually shift around items to out them on.

#### Specific information for locating

Caused by #26730 

#### Server revision

[bugfix]

**Comment by Kurfursten** [comment]
because of that exact same thing I commented
