### ISSUE TITLE
box station external airlock access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26823]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
4975fc891c4880dc963c78d6b7aa6824dd228803

# Description

scientists do not have access to box station research outpost's external airlocks that opens up to the bomb range, which means if you want to retrieve something from there as a standard scientist you have to go all the way around

**Comment by Kharkov72** [comment]
those airlocks use research access, however it has it under both access requirements instead of just using one so maybe that fucked it up.
