### ISSUE TITLE
You can see typing indicators from Cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26844]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
43b98d1263edabee11d2adae39663aa1ce2d9153

# Description

See title

**Comment by bathosbathtime** [comment]
What even is a typing indicator in character? You can certainly see if someone is talking over a visual feed even if you don't have an audio feed to go with it.

**Comment by Dacendeth** [comment]
Seems like a good feature to me.

**Comment by DeityLink** [comment]
You just see their lips move
