### ISSUE TITLE
Gas mask + cig bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26840]
(WEB REPORT BY: cervixdentata REMOTE: 206.221.180.138:7777)
# Revision
bc3fc98cb5273d78aebccbcf769da563283f669e

# Description

https://ibb.co/8rPWwCw

Equipping a gas mask and afterwards a cig will delete the mask but keep the icon in the top left. That's all it seemingly does. 

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
Cigarette bug, duplicate of #26768
