### ISSUE TITLE
Sometimes not all of the shuttle leaves at the same time, causing instant ZAS and shuttlecrushing

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26842]
# Description
oh god oh fuck
the bottom row of the shuttle (literally the entire south wall) left before the rest of the shuttle did
it sucked out like 3 dudes

# Steps to Reproduce
No idea, it was a summon magic round on deff and a mommi was busy setting up a few pipes into a wall.

# Revision
bc3fc98cb5273d78aebccbcf769da563283f669e

**Comment by Exxion** [comment]
Did the rest of the shuttle leave eventually or did it just stay there?

**Comment by SonixApache** [comment]
I believe the rest of the shuttle left a second or two afterwards.

**Comment by KingofHONK** [comment]
This is a frequently occuring bug that has been gibbing people for a month now. I think it may have something to do with spawning shit on the shuttle but not 100% sure.

**Comment by Kurfursten** [comment]
Was it exactly an even row of turfs, or did it get a few tiles into the next row or something?

I could see how if something caused lag (an errant delay? a runtime? a move operation looping through too many things?) during the operation it could stutter a second

**Comment by Exxion** [comment]
My guess would be some object `sleep()`ing in its `Move()` or `forceMove()` or something, directly or indirectly, but I don't know which object that might be
Since BYOND is single-threaded, lag alone should not cause that unless the code is specifically written to allow it, which would be very stupid

**Comment by Dacendeth** [comment]
Every escape shuttle does this to some degree when taking off and landing in my recent experience, though i've never seen ZAS or gibbing just the front half of the shuttle moving before the last half.

**Comment by KingofHONK** [comment]
**OH GOD OH FUCK**
![ohgodohfuck](https://user-images.githubusercontent.com/24867955/84814920-31b98b80-afe0-11ea-982a-343ea2825831.PNG)
![ohgodohfuck2](https://user-images.githubusercontent.com/24867955/84814928-341be580-afe0-11ea-8475-c4a5c8800a62.PNG)
![yikes](https://user-images.githubusercontent.com/24867955/84814956-485fe280-afe0-11ea-8322-52d8d0342fbd.png)

EDIT: I think the shuttle bug has SOMETHING to do with bussing anything on it
and i mean anything. Im noticing a increase in likelihood whenever any changes are made to it. Ill try testing.

**Comment by Kurfursten** [comment]
Hmm, notice how that one tile the clown backpack man is on is present in both versions. I wonder what was on his person?

**Comment by KingofHONK** [comment]
Also pictured: someones emitter eyes bugged out and the sprite stayed in that spot

**Comment by Kurfursten** [comment]
If people could take screenshots of the splits like the one above it could be very useful for information gathering, I'll also try to reproduce this

**Comment by SonixApache** [comment]
Extremely helpful screenshots:
![dreamseeker_2020-06-20_08-37-53](https://user-images.githubusercontent.com/8468269/85195345-dc2bfa00-b2d1-11ea-84f5-d53161079ea1.png)
![dreamseeker_2020-06-20_08-35-54](https://user-images.githubusercontent.com/8468269/85195346-dd5d2700-b2d1-11ea-9978-8779150a8732.png)

**Comment by Kurfursten** [comment]
we really need to see the tile where it split at the moment of splitting, which seems like it was probably out of frame on the right

**Comment by KingofHONK** [comment]
I DID IT REDDIT. I found a way to replicate this bug.
1. Spawn juke on shuttle, any shuttle that moves.
2. Play music on juke
3. Send shuttle
4. watch it split open as it takes off and lands
5. Now turn off music and delete juke
6. Try shuttle again
7. No more split.

**Comment by SonixApache** [comment]
Caused by #26645 or #26644 then maybe? Or #26802, seems closer to the start of the bug.
