### ISSUE TITLE
advanced security cameras ghost interaction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26848]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
43b98d1263edabee11d2adae39663aa1ce2d9153

As a ghost, you can interact with the Advanced Security Camera console that starts in Security.
In doing so, the UI opens and your viewport moves to the last viewed camera through it. But, the UI doesn't work and you can't cancel the viewport by moving.
This means the only way out of the view is the 'Cancel Camera View' verb in the IC tab people probably don't know too much about, as the button on the UI doesn't work. You can type the verb cancel-camera-view too but again, not something the common player has much experience with. 
Normal Security Camera console doesn't have ghost interaction, so this shouldn't either.

IMO ghosts don't need to be able to view most consoles so they shouldn't really have interactions at all. 
e.g. the CMC can be opened by a ghost but it just refuses to load, it should just not open.

**Comment by nervere** [comment]
No longer an issue.
