### ISSUE TITLE
Earmuffs don't block instruments

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#26847]
#### Steps to reproduce
- Be spessman
- Wear earmuffs
- Have someone play an instrument near you
- I just wanted to have some quiet
- Please

**Comment by BomberBro** [comment]
This also doesn't block the shakashuri peace effect the soul ramblers have, which is really annoying

**Comment by anunknownentity03** [comment]
also if you have the headset earmuffs you cannot hear your own voice over the radio too since that blocks it out
