### ISSUE TITLE
Face huggers and new rigsuit mechanics

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#26852]
#### Description of issue
if a facehugger rips your rigsuit helmet off it's on the ground for a little before teleporting back to your rig in a split second, where you can instantly redeploy it to be immune to further hugging. Kind of makes rigsuits incredibly strong against facehuggers as you no longer have to risk going back and picking up your helmet.

**Comment by jknpj** [comment]
Magnets

**Comment by DrSnips** [comment]
Personally I'd like to see a counter to huggers finally. They have been max levels of gunk through their entire lives and completely outclasses the spit shot the one xeno class has by effectively having homing.
To anyone without a ranged weapon it almost guarantees you can't fight it.

**Comment by tayachiya** [comment]
Happiest mask is the counter you're looking for

**Comment by Dacendeth** [comment]
nobody really cared about this.
