### ISSUE TITLE
Runechat doesn't work for observers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26858]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
32512547bcba1b86a313a92bd362d9ee335e0f2f

# Description

My fault for not caring enough to test that case

**Comment by Exxion** [comment]
It *does* work but only if you *aren't* in view
If you teleport to someone right after they say something, you can see it
Flipped check, maybe? Or something wacky
Or maybe something to do with how ghosts hear things nearby differently from ghostears
