### ISSUE TITLE
Cult fires way more often than any other round-ending gamemode

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#26866]
I think half of the reason people get tired of this mode is because it fires every single day, sometimes back to back (a couple days ago we had three cult rounds in a row). Since the start of June we've had 7 nukeop rounds, 10 malf rounds, 6 rev rounds, and **23** cult rounds. Why does it fire so much? Constant traitorstended was awful but surely there's a middle ground, right?

**Comment by Dacendeth** [comment]
I guess cult only cares if there's sec or not, which there usually is and the other game modes need ai's and heads of staff and such?

**Comment by BomberBro** [comment]
I would like to say that the round right after I made this was cult, so the grand total is now **24**

**Comment by Irradiation** [comment]
It "fires so much" because all gamemode weights are the same and you may or may not have the requirements to roll Revolution/Nuke at the time.

**Comment by BomberBro** [comment]
Then my question stands as "Why is the cult requirement so low", given that it ends the round just the same as the others

**Comment by DeityLink** [comment]
That's not really the case anymore
