### ISSUE TITLE
Can strip through full helmets.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#26864]
#### Description of issue
You can remove someones headset, glasses, mask, through any helmet that should block this (plasmaman, hardsuit, vox hemets, etc). Also gender on inspect is not being hidden either when someone is in a full hardsuit

#### Difference between expected and actual behavior
Helmets blocking stripping headsets and masks
can strip through them magically

#### Steps to reproduce
Put sunglassses on someone and a full hardsuit, strip through it.

#### Length of time in which bug has been known to occur

This is pretty recent as far as im aware.

#### Server revision

Revision: 6beff86079b862165961fccfbfd8dcfa02bf2beb

**Comment by DamianX** [comment]
#26876 appears to not have fixed the second part of this issue: you can still determine a spessman's gender through their hardsuit.

**Comment by DeityLink** [comment]
some hardsuits feature transparent visors that clearly let you see the face behind though, and unfortunately that includes the default spacesuit, so it's not that straightforward.

**Comment by Dacendeth** [comment]
Every single hardsuit/softsuit shows gender now though.

**Comment by Dacendeth** [comment]
other part fixed by #28229
