### ISSUE TITLE
Plants grow at any (?) temperature and any light level.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#2687]
Each plant is supposed to have a range of temperatures and light levels that it will thrive in, however this does not seem to be the case in /vg/station. That's basically it.

Sunflower and wheat healthily grown in the pitch dark of Maintenance.
![a bleak scenario](http://i.imgur.com/CtLwRkE.png)

Bananas thriving in space.
![this is just bananas](http://puu.sh/fdyZb/dd464162d1.png)

Additionally, all plants seem to have the exact same nutrient/water requirements when inspected with a plant analyzer, but I can't really test for that.

**Comment by Killette2** [comment]
All basic plants have the same food and light requirements because they are normal, order exotic seeds for different traits to splice. Also they won't instantly die when in the wrong environment, but they will die a lot faster.

**Comment by 9600bauds** [comment]
Mushrooms are supposed to be adapted to darker areas for sure, and somewhat worryingly it seems that common plants are adapted for light levels around 8 - when I believe the maximum is 5?
Also, the "a lot faster" isn't really felt, if it even works. The bananas you see in the picture were airlocked as soon as they were planted, and they still reached full maturity in space. Five minutes later the red light wasn't even flashing yet.

**Comment by d3athrow** [comment]
Yeah space isn't actually cold as it doesn't have a zone, it just makes mobs cold by being on a space tile.

**Comment by 9600bauds** [comment]
Oh.
Well I'm silly then. Still, I think plants shouldn't grow in the dark.
