### ISSUE TITLE
goonsat isn't a guaranteed vault spawn

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26873]
why

**Comment by Irradiation** [comment]
Because "scientists abuse Tsci to have a chance to yoink an Emag".
#23716

**Comment by boy2mantwicethefam** [comment]
the emag was removed I think

**Comment by jknpj** [comment]
It wouldn't be a vault if it was a guaranteed spawn

**Comment by SonixApache** [comment]
angie's lair is a 'vault' that's guaranteed to spawn and i somehow have in my head that the new goonsat was supposed to be guaranteed as well
