### ISSUE TITLE
Plant Pots are High as Shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26882]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
38fe8336fa204264c2cc078c964df4e682af1ccb

# Description
Plant pots don't actually show plants when you put plants in them, they just say they do.
# Steps to Reproduce
>be me, gardener
>get plants grown
>microwave sand and water to make plant pot
>use space on tray to put plant into adjacent pot
>look on in bewildered pikachu face

# What you Expected
plant show up in pot and make station pretty for pretty boys
# What Actually Happened
plants are in but don't actually show up so pretty boys are sad :(

Give me coffee at: Vox.cock.li

**Comment by DeityLink** [comment]
On one hand I'm really happy that people are actually using plant pots, on the other I really wish you indicated WHICH PLANT you tried to place in the pot when that happened. Does it happen with all plants?
