### ISSUE TITLE
Forcing Nuke Ops is Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26880]
(WEB REPORT BY: bathosbathtime REMOTE: 206.221.180.138:7777)
# Revision
38fe8336fa204264c2cc078c964df4e682af1ccb

# Description
Round start forcing nuke ops does not work.

# Steps to Reproduce
open game-panel
force roundstart ruleset
force ops
wait for game to start
# What you Expected
nukies
# What Actually Happened

ADMIN LOG: 1 rulesets being forced. Will now attempt to draft players for them.

ADMIN LOG: Not a single forced ruleset could be executed. Sad! Will now start a regular round of dynamic.

**Comment by ghost** [comment]
Were there enough candidates?

**Comment by ShiftyRail** [comment]
Unable to reproduce
