### ISSUE TITLE
at last we have discovered infinite food

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#26895]
>put food in a bowl
>take food out of bowl with a knife
>food is still bound to bowl so if you eat whats in the bowl the food dissapears
>BUT
>put food in ANOTHER bowl
>first bowl is now safe to eat
>knife second bowl
>continue infinitely for infinite bowls of whateverthefuck

told it also works with pizza
sounds like something's missing a check

**Comment by anunknownentity03** [comment]
feature, food fabrication

**Comment by ShiftyRail** [comment]
David Hilbert's feed and seed

![image](https://user-images.githubusercontent.com/31417754/85072070-c2e35a80-b1b8-11ea-8589-f9b45be71817.png)

**Comment by DeityLink** [comment]
Duplicate of #26654
