### ISSUE TITLE
red suit cigarette packets have lucky strikes in them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26892]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
59c47e0db13b2914df0cd4ed572259ae91b05acc

I BOUGHT RED SUITS AND THE FUKKIN PACKET HAD LUCKY STRIKES IN THEM. FUCK.

**Comment by SonixApache** [comment]
@Buchse 
edit: fixed in #26894
