### ISSUE TITLE
rigsuit mod stations can't accept better cells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26898]
(WEB REPORT BY: hatterhat REMOTE: 206.221.180.138:7777)
# Revision
5e55a91b75ca9147e0e6a1edb48b7d8f02eeedb5

# Description
smacking a rigsuit mod station with a power cell doesn't take the cell
# Steps to Reproduce
get a cell, get a rigsuit mod station, smack station with cell, receive disappointment
# What you Expected
rigsuit station accepts cell, gives me a better hardsuit cell upon modification
# What Actually Happened
cell not accepted, no cool cell

**Comment by dunsel-hordon** [comment]
pretty sure you don't need a cell in a hardsuit on vg

**Comment by Kurfursten** [comment]
you do need a cell nowadays, however most people never run out of charge because they aren't using anything besides the helmet light

that said I think this was a conscious choice by @jknpj because one of the upgrades gives you hulk and getting an ultracell for that would be dumb

**Comment by jknpj** [comment]
I didn't code the suit modifier

**Comment by Hatterhat** [comment]
the suit modifier specifically has code for accepting cells and it worked beforehand, dunno if it was just that one round or not

**Comment by Hatterhat** [comment]
i think this can be closed it's workin again
