### ISSUE TITLE
Flame Thrower

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#2689]
Flame thrower fails to ignite the fuel that comes out of it.

**Comment by SarahJohnson489** [comment]
Were you using it on the shuttle when it docked at centcomm? That causes it to spaghetti hard cause it's all unsimulated pretty much

**Comment by AutismSpider** [comment]
not on centcomm in the mommis nest

The fuel only burn after i drop a lit welding tool on it

**Comment by Konater** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7538670/6203817/97a96e06-b52c-11e4-9804-0a85d48bd22e.png)
Getting set on fire/walking through fire also seems a bit shit
