### ISSUE TITLE
Runechat hang

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26896]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
3a38364b22bc950935cf3cada535655362742a3c

# Description
Runechat is causing issue with ingame comms hanging.
# Steps to Reproduce
Play game try and talk
# What you Expected
nice smooth text to pop up when i hit enter
# What Actually Happened
Either it will hang for a second then appear or have had other times where it hangs for more than a minute before it appears. Makes cult almost unplayable.

**Comment by ShiftyRail** [comment]
No longer a thing after optimisations.
