### ISSUE TITLE
Can't draw weapons from the Holster with only one hand, I think.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26906]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
b22801b06dff94b8465675e44bc6bf99ed543563

# Description
After putting a holster on my outfit and a taser in the holster, I was unable to draw it to the response "You can't hold the taser gun like this!". I was missing both my legs, and the right hand while in a wheelchair, yet could not draw the taser with my left.

**Comment by SonixApache** [comment]
![image](https://user-images.githubusercontent.com/8468269/85187987-1a122980-b2a4-11ea-9544-a15b70b53789.png)
![image](https://user-images.githubusercontent.com/8468269/85187990-1f6f7400-b2a4-11ea-9a0f-4737a4ff3641.png)
cannot reproduce?

**Comment by DeityLink** [comment]
Most likely had their cut hand selected.
