### ISSUE TITLE
Shrunken vampire head does NOT pierce flash protection

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26904]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
ef5dd637cab0f6dfa2a03487b4dddacc724dfde8

# Description
Wiki says it pierces eye protection. It really doesn't. Sunglasses protect, as usual.
# Steps to Reproduce
buy/steal shrunken vampire head from trader, use on people with sunglasses / welding goggles / hardsuit helmets, notice that it doesn't work
# What you Expected
for it to glare like proper vampire and pierce, like it says in wiki and in code
# What Actually Happened
IT NO PIERCE IT'S JUST A SILENT INVISIBLE FLASH

**Comment by robintime** [comment]
fixed by #28770
