### ISSUE TITLE
Cult conversions work on dead bodies, even headless ones

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#26908]
They say a picture is worth a thousand words, so here's my novel:
![headlessconversion](https://user-images.githubusercontent.com/51391726/85190274-b62c3880-b284-11ea-938f-b02c82d0369d.PNG)

**Comment by KingofHONK** [comment]
FEATURE

**Comment by west3436** [comment]
feature

**Comment by gurfan** [comment]
fonctionnalité
