### ISSUE TITLE
More bugs with cult

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#26918]
#### Description of issue
yesterday there was a cult round where we built a base in space and three wierd bugs all happened. I've never seen them before and I have no clue what caused them, but I'm reporting them here in case they happen again.

1. A shade somehow got "duplicated"
A cult member was killed and flew over to the base as a shade. During that time we were planting soul blades on the altar in order to summon some ghosts. Somehow one of the soul blades had a soulstone with this guy's shade in it, even though he was already a shade flying around. This resulted in two shades of the same player, with one being "braindead"

2. The spire didn't upgrade itself and unlock tier three tattoos after we performed the sacrifice. Building a brand new spire fixed this issue.

3. A cultist plasmaman was performing the ressurection when for some reason, the progress bar stopped halfway through. The husk that appears when the ritual starts never gibbed, even when the cultist left the vicinity of the rune and stopped the ritual. The husk was still on top of the ressurection rune until round end.

[bugfix]

**Comment by DeityLink** [comment]
1. Oh god more soulblade+altar bugs. Probably a sanity issue. If you've got the exact date of the round that'd help me find if there are any runtimes in there.
2. That's weird, was the spire built right as the sacrifice was made or something?
3. Seems like another runtime to me. Did the ritual keep consuming blood when the progress bar stopped? or did that stop as well? May or may not be related to the plasmaman's blood container running out of blood and himself not having blood vessels.

**Comment by gurfan** [comment]
1. The round was on 6/19, and it started at 22:19:16.

2. The spire was built long before we performed the sacrifice.

3. I don't remember if it was still consuming blood or not, all I do remember was seeing the ritual animation still playing even after the only people left in our base were shades. You'll have to ask ckey Cockswain for more information.

**Comment by DeityLink** [comment]
@gurfan you can know if a ritual is consuming blood from small red particles moving from the cultist to the rune.

**Comment by gurfan** [comment]
> @gurfan you can know if a ritual is consuming blood from small red particles moving from the cultist to the rune.

I don't remember if I saw them or not, sorry.

**Comment by DeityLink** [comment]
Has this been observed again recently?

**Comment by gurfan** [comment]
not personally, the only cult related bug that I observed since then was when I found a morphing mask that made me a shade, I got recaptured with a shard while as a morph mask shade then put into a construct shell. The person who shelled me was able to withdrawl the mindless shade from the shard afrerward

**Comment by DeityLink** [comment]
Seems more like a morphing mask issue to me.

**Comment by DeityLink** [comment]
Will close this for now, if issues re-appear please make a separate ticket (and possibly ping me as soon as you observe them unless I'm playing in the round)
