### ISSUE TITLE
Horror Form Changeling Regenerative stasis bug

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2691]
Used regenerative stasis while hurt in horror form to fix up some burn damage. It locked my camera view and had to relog to fix it. By which point it was Ogre.

This was where I was buckled into the shuttle brig chair despite still locked in sight of chapel.
![untitled](https://cloud.githubusercontent.com/assets/5564796/5976553/c01cab94-a83b-11e4-982b-b3ddaa132c50.png)

Steps to reproduce:
>Go smash a bunch of lights with a scalpel to get some burn
>Mash regenerative stasis while still alive and not crit
>Camera lock
>Have dude move you to confirm.

**Comment by ComicIronic** [comment]
I've had this happen in various other situations as well.
It might be an issue with regen code in some way.

**Comment by d3athrow** [comment]
Temporary IC fix is to use cancel camera view verb.

**Comment by clusterfack** [comment]
We had this for awhile with defib bugs months back. Your mind or something would get stuck in location even when being inside your body.

**Comment by clusterfack** [comment]
This is too old to be regarded as a reliable report for the current state of the code, please reopen or make a new issue if something similar occurs again.
