### ISSUE TITLE
Malf Catbeast Borg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26913]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
ff234cda61fb2da2c486eb3f97fc947c55f4128b

# Description
a catbeast will instead be force ghosted when autoborged
# Steps to Reproduce
force malf ai, force catbeast, catbeast go in borger
# What you Expected
being borg from cat
# What Actually Happened
ghost

**Comment by strawberrytan** [comment]
Catbeasts don't have souls in the way the MMI requires

**Comment by nervere** [comment]
works on my machine
