### ISSUE TITLE
Can't see runechat in the dark

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26927]
(WEB REPORT BY: jellyveggie2 REMOTE: 206.221.180.138:7777)
# Revision
8021aaf5395f8ad5300f936e9b7845ac202b370e

# Description
Runechat seems to be affected by light, despite being an abstract representation of speech and sound.

# Steps to Reproduce
Enable runechat on mobs, hang around maint in utter darkness and wait for the clown to sneak behind you and whisper sweet nothings to you.

# What you Expected
Spooky voices in maint

# What Actually Happened
Deafening darkness, breaking my emulsions

**Comment by ShiftyRail** [comment]
This is intended. It is so that someone can sneak in maint and talk/whisper without being seen.

**Comment by Killette2** [comment]
Imagine not mastering echolocation to a degree where if someone speaks in the dark that you know where their exact location is
