### ISSUE TITLE
vampire is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26924]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
8021aaf5395f8ad5300f936e9b7845ac202b370e

# Description
https://gyazo.com/2495f2ba2906dfdf6848f0a5795eb4e6
# Steps to Reproduce
glare then try to hypnotise
# What you Expected
be able to hypnotise
# What Actually Happened
I died

**Comment by Dacendeth** [comment]
I recall someone reporting something like this, and we found out the bug was just pressing buttons too fast?

**Comment by west3436** [comment]
I have also had this happen to me recently - it seems like Hypnotize is just being shrugged off

**Comment by DamianX** [comment]
He got a message saying his target was blind.

**Comment by Dacendeth** [comment]
yeah because eye flash blinds for a short time doesnt it? hypnotize doesnt work on blind people, aka you did the combo too fast?

**Comment by DamianX** [comment]
It's stupid that it's possible to do it too fast.

**Comment by Dacendeth** [comment]
Agreed

**Comment by tayachiya** [comment]
Hi yes, that was me. If you do it PERFECTLY, hypnotising the target will not work.
Glaring or whatever it's called actually blinds the target for 0.5 second or so, meaning you have to glare, wait and only then hypnotise. And indeed,it gives the message the target is blind.
