### ISSUE TITLE
Bunnybot Spontaneous Combustion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26933]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
f32e201dac468dfebe6bc3381173572557f67e26

# Description
using an amorphous mask that turns you into a Bunnybot will kill you after a few moments

# Steps to Reproduce
dig up an amorphous mask that turns you into a bunnybot, walk around, die randomly and leave behind nothing more than an ID

# What you Expected
not blowing up/turning back into my old identity when the bunnybot machine breaks

# What Actually Happened
my disappointment was immeasurable and my round is ruined

**Comment by Kharkov72** [comment]
tl;dr blacklist bunnybots from random masks
