### ISSUE TITLE
Cant take apart intercoms anymore

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#26936]
#### Description of issue
Screwdriving intercoms to reveal wires doesnt reveal wires.

#### Difference between expected and actual behavior
screwdriving intercom to let me cut wires
didnt do that

#### Steps to reproduce
screwdriver an intercom

#### Server revision

Revision: 55298211d5b5d7985e506c3df7b7c8354abd86de

**Comment by SonixApache** [comment]
Yeah, I noticed this a few days ago as well. Annoying. Can't disable intercoms anymore.

**Comment by Kurfursten** [comment]
It would appear that this was a casualty when @ancientpower killed the black market, he didn't look carefully at the attackby code he was deleting in #25804

Using a screwdriver should toggle `b_stat` in radio.dm
