### ISSUE TITLE
Vox do not have audible shrieks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26946]
(WEB REPORT BY: armadingus REMOTE: 206.221.180.138:7777)
# Revision
368b8132480a94241bec83a3ebad472b8b0a2c42

# Description
When a vox would shriek in agony, the sound that would usually play does not play.

# Steps to Reproduce
Shoot a vox with a taser.

# What you Expected
Skree.

# What Actually Happened
Vox have turned into mimes.

**Comment by boy2mantwicethefam** [comment]
Will fix

**Comment by ShiftyRail** [comment]
No longer an issue.
