### ISSUE TITLE
Cult 4.0

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#26941]
Alright good, got your attention. I stayed up till late last night to finish up this google doc summing up some of the ideas we discussed a bit over a week ago following over a year and a half of feedback on cult 3.0. This includes my plan to "fix" cult, and the reasoning behind each step. Please give it a read, and come discuss it in this issue so I can make adjustments to the document as needed and start coding ASAP.

# [Cult 2020 Design Doc](https://docs.google.com/document/d/1e49TxEMFdzAwpvIy6alBgYrytWfAo5F-O5A62PW2KvY/edit?usp=sharing)

**Comment by boy2mantwicethefam** [comment]
Aw man I wanted to try my hand at reworking cult first

**Comment by DeityLink** [comment]
You've had a whole year to do it :P I also stayed away from cult all this time to let other coders have a go at it, but I've waited long enough now. If there are some aspects of your intended rework that you think could mesh well with this design doc, feel free to suggest them.

**Comment by tayachiya** [comment]
Crudux cruo!

**Comment by BurntDevil** [comment]
I think bringing back deconversions is a good idea. However, there should be risk with it. After all, the cult has to put itself at risk to convert, thus so should the crew to deconvert. I think if a nonchaplain attempts to do an exorcism, being untrained in how to perform one, they should botch it. This should pull the tainting presence out of the victim, but should also release it out into the wild. In gameplay terms, if a nonchappie deconverts someone, it should spawn a strong ghost mob that attacks the offending party. Chaplains, being trained to contain spirits, would not botch it, sending it directly back to hell out of the player affected, but will need to perform the proper ritual.

This gives a risk to the crew, and a value to having a chaplain around. I think this is how you make that more balanced and engaging.

**Comment by DeityLink** [comment]
@tayachiya 
![image](https://user-images.githubusercontent.com/7573912/85391933-1ce27800-b54b-11ea-8488-04ae01331ce3.png)

@BurntDevil 
The risk doesn't come from the conversion itself, but from managing to capture a crew member (ok, and also the possibilty that they reject the conversion). So the same way, the risk with de-conversion is managing to capture a cultist, but the deconversion itself shouldn't have much risk associated with it, and I mean, I've suggested an implementation of deconversions in last year's suggested cult update that featured a chance of backfire for both accepting and refusing it, and the reception was pretty bad.

The idea of non-chaplain having a chance to spawn hostile cult mobs when trying to deconvert someone who refuses the deconversion is pretty good though, and gives the chaplain a slight advantage without becoming a must. I'll update the doc.

**Comment by ShiftyRail** [comment]
Algebraic geometer of blood or differential geometer

**Comment by DeityLink** [comment]
@ShiftyRail I used to go with algebraic, but recently I've discovered that geometers are also a species of moths, "Their scientific name derives from the Ancient Greek geo γῆ or γαῖα "the earth", and metron μέτρον "measure" in reference to the way their larvae, or "inchworms", appear to "measure the earth" as they move along in a looping fashion." in other words, seems like Nar-Sie was a moth all along, explains the wide arms and small legs.

**Comment by boy2mantwicethefam** [comment]
@DeityLink I got a whole notepad of ideas which I posted on the thread, I can post some ideas here too.

**Comment by DeityLink** [comment]
Well I kinda opened this issue specifically so we could discuss the doc, otherwise I'd have posted it back in the #26811 issue. If you've got ideas unrelated to the doc come discuss them on the coder discord's game-design channel.

edit: unless you believe they could mesh well with the redesign being discussed here.

**Comment by SonixApache** [comment]
add clock cult and glock cult and we're good on variety
discord also suggests rock cult for miners and xenoarchs, and cargo cult for cargo

**Comment by DeityLink** [comment]
I updated the doc with stuff we've discussed today on Discord. The new things are highlighted in blue.

**Comment by Spyroshark** [comment]
"Instead of requiring the cultists to spill blood to fill the bloodstone, it will automatically slowly fill up over 10 minutes or so" I can see this being an issue if cult has already steamrolled security and taken over the station, people will have to sit around and recall while everyone is dead and waiting for the round to be over

**Comment by DeityLink** [comment]
@Spyroshark well two things to that:

1. That's already an option to current cult, and to most other antags as well in fact, not much you can do to prevent that really
2. 10 minutes is exactly the time it takes for the shuttle to arrive, so this would still end the round faster than just calling the shuttle.

**Comment by drawsstuff** [comment]
I feel like there's some room for fun with cult that's overshadowed in the name of conversions. Half the point of a cult is the random kidnappings of crewmembers, where's the fun if they just walk away unscathed? Currently, cult only really has one option if the target refuses conversion, and that's to soul stone them and move on. I feel like there's a lot fun, creepy potential in "using" crewmembers in another way, be it through rituals, or even replacing the current "Blood Monkey" meta with players, as the cult hooks them up to IV drips and shoves iron down their throat to get as much use out of them as possible. Might make for some interesting RP potential as well.

**Comment by ShiftyRail** [comment]
>The cult may no longer make up more than 25% of the crew’s max population (that is, the highest number of living crew members reached at a single point during the round). Above that amount, conversion runes will fizzle.

While I understand where it comes from, it's a hard threshold that may feel like it's taking away options from players.
I think it would be maybe better to just have them take longer and longer.

**Comment by GreatBigFailure** [comment]
Conversions just not working on implanted people I think is a bit much. Since deconversions are also a thing and the cult is meant to be known it'll just be too easy to counter with forced implants. It would turn into the cult needing to race sec to the finish line with ritual vs implant. That would remove the whole spooky atmosphere you're going for. 
At the very least I'd say a cult tool that un-implants people would be mandatory if you continue with that combination of mechanics. Surgery does exist but I don't think anyone would go through with chloral surgery for every individual recruit. 

On top of that for sec/head players it's basically an antag restriction which isn't fun. I play a lot of HoP and I'd like to be able to get culted now and then. Instead they'd probably be forced to just kill me, though I assume your planned rituals would push them toward something else.

Besides that I think the ideas are fantastic. Just make sure there's a good enough way to hide your identity and keep in mind all the meta nonsense at play with anything sneaky.

**Comment by DeityLink** [comment]
@ShiftyRail I could explore doing that I guess. The % value is arbitrary right now, I might change or remove it depending on how the rounds develop.

@GreatBigFailure @ShiftyRail i'm trying to push the idea that conversions no longer being the cult's main activity, and rituals _requiring_ that there are non-cultists around should make both the conversion limit and the restriction on loyalty implant much less of an issue that they would be on Cult 3.0

**Comment by AI-Is-Rogue** [comment]
Aside from requiring there to be non-cultists for rituals, did you have any other ideas for utilizing the unconvertable?

**Comment by DeityLink** [comment]
Well they will have their role as either bystanders or enemy of the cult. Cultbanned/Never players won't have much of an other role to play considering that they probably don't want anything to do with cult. Loyalty Implanted however may more easily have surgery done on them due to conversion runes cuffing them. Or were you thinking of something in particular? (Maybe altars and blood dagger could work as ghetto-cult surgery table/tool to extract implants, but you'd have the time to ask them beforehand how much they'd like to help the cult or not)

**Comment by AI-Is-Rogue** [comment]
I was thinking more about the idea of what cultists could use people for past the 25% inducted. Something along the line of performing rituals on them to turn them into magical payloads or other possible eldritch things. A bit like to the non-cultist curse in the doc but more involved, sowing potential chaos or creating distractions.

**Comment by DeityLink** [comment]
Well yeah that's basically what I had in mind. You could poison food and have cult tentacles grow on people, cult viruses, stuff that would occupy the crew a bit to fix.

**Comment by AI-Is-Rogue** [comment]
Guess we're on the same wavelength then, the things you listed sound pretty rad.

**Comment by ghost** [comment]
I had said this in the previous post but a way to retrieve people who got bloodstoned would be nice.

Also why not go full on Berserk mode if you are doing eclipse stuff? You could have the cultists turn into monstrous humanoid forms instead of just getting aura. Extra arms and all that eldritch horror goodness.

**Comment by DeityLink** [comment]
@Baronzegit The idea is that the rituals they do beforehand also let them unlock perks that may help them during the Eclipse, so this will be the case to some extent. (I don't dislike the idea but I'd like to get the base rework out before doing extensive additional spritework)

Also you meant soulstoned right? There are a few ideas I'd like explore. One of them involves adamantine slimes/golems, which would also further the plan of having Cult involve potentially more jobs (without having any job being critical, other than sec maybe I guess)

**Comment by gurfan** [comment]
Will harvesters make a return? Do you have any plans to change how constructs work in general?

**Comment by ghost** [comment]
> Also you meant soulstoned right? There are a few ideas I'd like explore. One of them involves adamantine slimes/golems, which would also further the plan of having Cult involve potentially more jobs (without having any job being critical, other than sec maybe I guess)

Yeah, i keep calling them blood stones accidentally. Adamantite golems? Could actually be cool since those use runes as well. So player returns in golem form but not bound to whoever created it?

**Comment by DeityLink** [comment]
@gurfan yes
@Baronzegit well the matter of allegiance isn't quite set in stone, I know that most adamantine golem get to live however they want anyway, and non-cultists getting their hands on both soulstones and construct shells often want to create their own slave constructs, so I'll leave that up in the air for now.

Anyway I've taken a few hours today to actually start working on the document detailing the Ritual system, the order that runes are other bonuses are unlocked, and imagining a bunch of rituals, so if you guys have ideas now is the time to pitch them forward.

[Cult 2020 - Rituals List](https://docs.google.com/document/d/1rlOxtkmFLOlVJVRo1jeVumdv8Tc_VcdAIqkk-0BwvOQ/edit#)

**Comment by Eneocho** [comment]
I request a Clown Cult. 
A reskin of Nar-Sie's Cult, but every blood related thing is swapped with bananas and banana related items.
You start with a small amount of banana juice in your backpack, in a special vial that fills with non clown slippings you do with the PDA.
You raise an altar (A clownmask), you raise a forge (A banana peel), you raise spires (a banana tree), runes get their appropiate transformations: Conversion makes you a Cult Clown, clumsy mutation included. Stun slips you as if you had been lubed. Confusion throws a super cream pie to your face, blinding you for a minute and making everyone look like a clown or mime. Deaf-Mute makes you say Honk and only Honk. Summon robes gives you clown attire, etc.

**Comment by ShiftyRail** [comment]
>removal of the ACT Structure 

Good idea, ritual tree might however feel small (no matter how big you make it) because we have to keep in mind that it's a game people play day after day for months (if not years), and as a result if the same options keep re-appearing the same boredom will ensure.

>Nar-Sie is no longer the de-facto end goal

Good idea, branching possibilities is a good thing that was lacking in original cult 3.
Not a fan of the way it is written currently, though, prefer different end goals than restraining "summon Nar-Sie" to one phase. Making cultists visible during that phase also feels odd, but time will tell :tm:

>Deconversions are back

Good. The actual details seem good too.

>You can no longer convert through implants

Good thing.

>The cult may no longer make up more than 25% of the crew’s max population

Time will tell, but I'd rather have a "soft-cap" (conversions taking exponentially more time, requiring more cultists simultanously, etc) rather than a hard one.

Overall, pretty good, maybe it would be good to go all-in "modularity" and offer many paths, combinations, and little hidden interactions. Make it something people aren't afraid to expend on their own.

**Comment by DeityLink** [comment]
@ShiftyRail the way I see it, it'll be less of a tree and more of a "all the rituals of this tier can now be performed", with no ritual being locked by a specific other ritual (bare exceptions that I haven't quite planned yet)

Also here's an attempt at drawing a concept for the Cult UI I drew a few months ago 
![image](https://user-images.githubusercontent.com/7573912/99440778-590ddf00-2917-11eb-80be-41c49ae55d02.png)

You can see rituals listed by column along with the points they've brought the cult so far, and the point gauge above tracks the progress to the next tier.

>if the same options keep re-appearing the same boredom will ensure.

The idea is also to have available rituals cover a variety of play styles, whether you wanna remain stealthy, go loud, or do something gimmicky. Basically offer every cultist the ability to help the cult by just doing what they think a cultist should do. If some people still have fun playing Cult 3.0 in its current state I'm sure a version with even more options will last much longer before people get bored of it.

>though, prefer different end goals

If traitors can have freeform objectives (and the cult even used to do at some point a long time ago) I'm sure cultists will come with fun stuff to keep themselves busy that doesn't involve ending the round. I hope seeing such stuff occurs especially when the Eclipse ends without the cult tearing dimensions.

>conversions taking exponentially more time, requiring more cultists simultanously, etc

In my opinion making it more bothersome won't stop people from doing it, and we end up with the same problem of optimal cult 3.0 plans being to deal with sec before Act 3. I really want the cult to mess with the crew in other ways than just conversion/murder.


And yes I want rituals to be easy to implement so more can easily added down the line. Adding more rituals should be much less of a problem than adding a new rune.

**Comment by jknpj** [comment]
Transfering this to #28636
