### ISSUE TITLE
All NanoUI Interfaces are borked.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26957]
(WEB REPORT BY: buchse REMOTE: 206.221.180.138:7777)
# Revision
92a6267090ade0f8764d65fc43012ee3524cfc17

# Description
When trying to do things like set tank pressure or so, just like the replacer, the screen is broken, showing a white, blank window. 

# Steps to Reproduce
use any nanoUI
# What you Expected
interface to work
# What Actually Happened
white expanse of nothing.

**Comment by boy2mantwicethefam** [comment]
press the fix nanoui button in the ooc tab

**Comment by PavelCIA** [comment]
I have the same issue and the fix nanonUI button doesn't fix it. I usually just spam open and close the window until it loads
