### ISSUE TITLE
What if human dust'ing no longer destroyed their uniforms and most of their equipment?

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#26955]
Since that's what leads to cultists destroying their loot upon becoming shades, I thought I'd ask people their thoughts about whether it should be removed from all forms of dust'ing as well while I'm at it.

**Comment by DrSnips** [comment]
As an extension to this I think almost all forms of body destruction (namely gib) should drop their items. I see no reason why getting shot by a rod should magically vanish certain things but not others or why an internal issue like gibbingtons should cause any item from being lost at all.

**Comment by Accipitermaris** [comment]
cult shading isn't just bad because it deletes their items, it's also bad because they can do it on demand when 100% healthy & in handcuffs with the intent to delete all their evidence/weapons and escape

**Comment by ghost** [comment]
Supermatter should still destroy everything due to its nature, any other means I'd consider it fine to drop items.

**Comment by DeityLink** [comment]
Well being able to escape thanks to it is intended, destroying evidence and weapons is not.

**Comment by Dacendeth** [comment]
the supermatter just leaving behind a single id just feels right but other things should drop all.

**Comment by BomberBro** [comment]
Yeah I agree, with the supermatter it's fine but since you have total control over it as a cultist it's easy to abuse it

**Comment by GreatBigFailure** [comment]
Supermatter destroys everything, other kinds of dust/gib shouldn't.

**Comment by tuypo1** [comment]
I would prefer supermatter leaving shoes rather than ids, it's funnier that way
