### ISSUE TITLE
Credits are broken sometimes

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#26958]
#### Steps to reproduce
- Witness the end of a round
- Watch the credits black screen briefly appear
- Get disconnected
- Get reconnected shortly after for some reason, making the credits disappear
- Get disconnected again and left with a frozen screen once the server shuts down for real

It's been happening for a week or more.

**Comment by Exxion** [comment]
Last I checked it worked fine for me, and I'm pretty sure that was less than a week ago

EDIT: Oh I read the body but apparently not the title
Only sometimes happens, then

**Comment by SonixApache** [comment]
#21684

**Comment by DamianX** [comment]
That sounds exactly like this, though I haven't experienced it at all until recently. Closing because duplicate.
