### ISSUE TITLE
Light Replacer Interface is fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26956]
(WEB REPORT BY: buchse REMOTE: 206.221.180.138:7777)
# Revision
92a6267090ade0f8764d65fc43012ee3524cfc17

# Description
The interface screen for light replacers is completely blank

# Steps to Reproduce
use replacer in-hand or click it or something

# What you Expected
to make more lights

# What Actually Happened
blank screen of death

**Comment by Kurfursten** [comment]
it's just the nanoui bug

**Comment by DeityLink** [comment]
Duplicate of #26957
