### ISSUE TITLE
If wizman tries to get fireball after buying firebreath it says wizman already has it.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26961]
(WEB REPORT BY: archsunder REMOTE: 206.221.180.138:7777)
# Revision
4f8624b0c037c8812a00df56bf4494324b86b828

# Description
because breath is a child of fireball i guess

# Steps to Reproduce
buy firebreath
try to buy fireball
# What you Expected
fireball and firebreath
# What Actually Happened
"bro u already know firebreath"

**Comment by SonixApache** [comment]
#17346  #22200
