### ISSUE TITLE
CMC damage number colors SUCK

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26968]
#### Description of issue

![image](https://user-images.githubusercontent.com/8468269/85924381-44f71180-b892-11ea-9c76-467becb0e92a.png)
what the fuck is this
I can't ever read that blue number without highlighting, and I have to squint to read the dark green one.
Why don't these just use the same color as the handheld medical scanners?
The contrast needs to be improved vastly!

**Comment by Kammerjunk** [comment]
it says (0/0/0/0)

**Comment by DrSnips** [comment]
The blue I can understand but the green doesn't if you ask me.

**Comment by Dacendeth** [comment]
The blue could be lighter I guess but the rest seem fine to me.

**Comment by SonixApache** [comment]
I fixed this in #28732
