### ISSUE TITLE
prescription glasses have the human sprite on bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26973]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
a98a4b0000de7933858827660d65312b322124af

When bugs wear perscription sunglasses, they use the sprite for humans, which makes it look like youre wearing sunglasses on top of your head.

**Comment by DeityLink** [comment]
They seem to have their own sprite properly now.
