### ISSUE TITLE
make the 'heart attack' heart mob turn into the actual heart organ when killed

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#26971]
#### Description of issue

The heart attack symptom is funny but also kinda dumb (literally just a floating heart organ icon that hits pretty hard)
But the worst part about it is that it leaves behind a dead mob instead of the heart organ. Can't even stick it back in there after beating your heart attack.

https://github.com/vgstation-coders/vgstation13/blob/dd91f267e02b4b307077854930e4b09b40abc2f0/code/modules/virus2/effect/stage_4.dm#L619-L641

**Comment by DrSnips** [comment]
I feel like it would be funnier if the heart splattered(gibbed) on death if it's not going to do anything after you kill it.
If we're going for a functional heart I would just make it one of the death drops an actual heart (stored from the originator in a var maybe) and then delete the dummy mob afterwards.

**Comment by DeityLink** [comment]
It should just gib up imo
