### ISSUE TITLE
Une cards glitch out.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26984]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
cbfe7e4e47fcbc5ba777dfdd7d0bc1d94ddeb64a

# Description
I was playing Une with Tiya and Xizz, my cards disappeared from my hands, but if i add a card to the invisible deck it appears again, not always however.
# Steps to Reproduce
Play Une till one of your cards disappear

# What you Expected
Not glitched gameplay.
# What Actually Happened
FEATURES(TM)

**Comment by Armadingus** [comment]
Same issue probably https://github.com/vgstation-coders/vgstation13/issues/26700#issue-631309077.

**Comment by Exxion** [comment]
If memory serves I told people how to fix this long ago, but nobody did and everyone forgot
Guess I'll do it if it is the bug I remember

**Comment by Exxion** [comment]
It's not the same bug I remember, and someone did fix that one
I'll still take a look
