### ISSUE TITLE
Gyrotrons simply do not work

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#26987]
#### Steps to reproduce
- Turn on a gyrotron
- Watch the beam disappear midway
![image](https://user-images.githubusercontent.com/6307265/86135202-c77a0e00-baea-11ea-8c74-4f9b7f9eae57.png)

**Comment by Dacendeth** [comment]
lots of beams just turn invisible over space tiles, like spacepod lasers, that one pump laser gun from the salvage ship.

**Comment by Exxion** [comment]
Those beams are not the same beams as these beams
Also wasn't that fixed years ago?

**Comment by Dacendeth** [comment]
The spacepod one I can say is still bugged, the others im not sure about.

**Comment by Exxion** [comment]
Apparently gyrotron beams ARE projectile beams and what's going on is exactly what @Dacendeth said. Sorry.
![image](https://user-images.githubusercontent.com/9827785/86252645-78cb8300-bb81-11ea-94ed-e966180525d6.png)

**Comment by DamianX** [comment]
my tokamak field was not charging, that is all I know, I'll see if I can reproduce it

**Comment by DeityLink** [comment]
Should have been fixed now that pooling was removed right?

**Comment by DamianX** [comment]
It looks like the issue is with windows, they block the beams no matter what. Pooling made no difference.
![image](https://user-images.githubusercontent.com/6307265/86600746-c4769600-bfa0-11ea-8a48-6f41aaf6004d.png)
![image](https://user-images.githubusercontent.com/6307265/86600755-c7718680-bfa0-11ea-997f-055648358282.png)
![image](https://user-images.githubusercontent.com/6307265/86600767-cb050d80-bfa0-11ea-841b-99aacc518087.png)
![image](https://user-images.githubusercontent.com/6307265/86600774-cd676780-bfa0-11ea-98bb-5af1107b27aa.png)

**Comment by DeityLink** [comment]
Windows randomly blocking beams was a bug I observed with emitter beams as well. I'm still not sure what specifically causes it but I implemented a fix for emitters. Might want to apply it here as well.

>Pooling died for this

**Comment by Exxion** [comment]
Pooling died for being a shit system with no redeeming qualities. This just gave the kick to actually do it.

**Comment by DeityLink** [comment]
Oh yeah gyrotron are just laser beams, not actual emitter beams, despite having "emitter" in their path name, talk about confusing.

So that means that bug is completely unrelated to emitters, but on the other hand might happen with every single laser guns.
