### ISSUE TITLE
Cant rotate windows properly anymore as well as other object verb targeting issues.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#26981]
#### Description of issue
If you right click something to try to do something like rotate a window, or flip a table, or spin a chair, etc, it wont target the one you selected if another one is around that it deems higher priority.

#### Difference between expected and actual behavior
the verb being used on the target i selected
favors one target as long as it's in range

#### Steps to reproduce
Put down multiple windows next to each and try to rotate each one of them by right clicking and using rotate clockwise
Notice how no matter which one you select to rotate one of them will rotate everytime only.

#### Server revision

Revision: cbfe7e4e47fcbc5ba777dfdd7d0bc1d94ddeb64a

**Comment by Exxion** [comment]
I believe this is a BYOND bug, fixed in 1525
Should be fixed whenever we update to latest (currently 1527)

EDIT: Actually the latest is apparently 1526 because Lummox still hasn't released 1527

**Comment by Dacendeth** [comment]
Doesnt happen anymore.
