### ISSUE TITLE
RCD crashing the server

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#26983]
(WEB REPORT BY: feldnost REMOTE: 206.221.180.138:7777)
# Revision
cbfe7e4e47fcbc5ba777dfdd7d0bc1d94ddeb64a

# Description
lately messing with doors on the rcd has been crashing the server, usually when this happens it happens when theres a diamond with a question mark in the middle symbol, deleting this symbol or placing the door crashes the server, im a borg when i mess with the rcd but i dont know if that has anything to do with it
# Steps to Reproduce
be borg and open up/fuck with names/ placing doors with rcd 
# What you Expected
to place a door
# What Actually Happened
crash the server instantly

**Comment by BomberBro** [comment]
Tried to recreate this on the test serb as an engiborg and couldn't for the life of me get the broken character, this definitely does happen though.

**Comment by Dacendeth** [comment]
I can get the symbol to appear on the test serb ~~but nothing i do with it seems to crash the server~~ okay it crashed after a bit i think.

**Comment by jknpj** [comment]
Unicode...

**Comment by Exxion** [comment]
You'd think so, but no
The character shows up because of 513, but the crash always would have happened if you pasted it in
