### ISSUE TITLE
Suggestion: Only deathsquad leader should have a mecha

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#27000]
There are never any old-fashioned deathsquads because all of them go into meme mechs with a gorillion health and damage, only the deathsquad leader should have a mecha because he is the leader

**Comment by boy2mantwicethefam** [comment]
Check out my trips

**Comment by anunknownentity03** [comment]
just place blast doors in the mech bay or leading to it and have the admins either auth or deny mech usage

**Comment by BomberBro** [comment]
my major issue with it is that most deathsquads are full of salty ghosts and unrobustos, so the mechs are basically there to ensure they don't just all fluke horribly

**Comment by Caboozles** [comment]
Flukesquads are a gift, and typically the station is fucked up enough that their goodies won’t impact much. 

It also means you can decide if you want to give the crew a fighting chance by not giving them the mechs. I say admin auth sounds good.

**Comment by robosperg** [comment]
once upon a time the mechs did need an admin to push the button to unlock the door

**Comment by boy2mantwicethefam** [comment]
It didn't work out.
