### ISSUE TITLE
Grammar Error In Magstomping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27013]
(WEB REPORT BY: beelzewax REMOTE: 206.221.180.138:7777)
# Revision
827fb07bfe7feac1bb705caac256abee574a9da2

# Description
[bugfix][grammar][easy] Magstomping someone uses the stomper's pronoun rather than the stompees. 

>Brandon Flickenger slowly raises her magboot above the lying Arie Wilgenhout, preparing to stomp on her.
>This is Arie Wilgenhout!
>He is wearing  a security hardsuit helmet on his head. Examine.

Line in question:
https://github.com/vgstation-coders/vgstation13/blob/81e00448c9d3b670b2b728c7fd50ebc062a6b1f8/code/modules/clothing/shoes/magboots.dm#L73
`user.visible_message("<span class='danger'>\The [user] slowly raises \his [stomp_boot] above the lying [victim.name], preparing to stomp on \him.</span>")`
`\him` at the end should be something else.

**Comment by Exxion** [comment]
Just changing `victim.name` to `victim` should fix this if I remember correctly how those macros work, though it would cause weirdness if the victim's name isn't capitalized

**Comment by cloutcode** [comment]
arie wilgenhout is a female
