### ISSUE TITLE
borgs don't patrol

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27018]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
827fb07bfe7feac1bb705caac256abee574a9da2

# Description
they just don't
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DamianX** [comment]
Borgs are player controlled so obviously they don't patrol on their own, duh.
