### ISSUE TITLE
Bypass admin PM mute

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27011]
(WEB REPORT BY: pancakemines REMOTE: 206.221.180.138:7777)
you can continue to bully admins after they mute you if you make sure to build up admin pm boxes prior to the mute, I did it by clicking the admin name to respond to them but it probably works by spamming f1 too. Personally I think it should stay because admins have to be put in their place but some crybabies want it removed because they hate being bullied. [22:47:03] Damiamin PM from-DamianQ: you should report this, it's an easy fix.

**Comment by Kurfursten** [comment]
Getting around a mute is actually evading a chat ban, ergo this is just an excuse for an admin to get some permaban valids

**Comment by AliceDTRH** [comment]
Perhaps this is easy to fix codewise but is the issue that the admin pm mute flag isn't set at all during a default mute (intended behaviour as far as I can see) or that the admin pm mute is not working in this situation (would be a proper bug and indeed easy to fix)?

**Comment by Kurfursten** [comment]
It's the latter - basically just add a sanity check when they submit the input for the adminhelp instead of only checking if they're muted when they click the hyperlink

**Comment by AliceDTRH** [comment]
Okay, thank you for explaining that.
