### ISSUE TITLE
Cyborg Jetpack breaks after refueling

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2702]
I've seen this occur a few times, mommi or cyborgs that refill their jetpack do not regain the ability to jetpack move through space. Space will still be 'sticky' to them if they have jetpack stabilization on and they will have the jetpack move effect going over lattices but they can no longer spacemove.

**Comment by Probe1** [comment]
sticky space is something a lot of us are experiencing not limited to jet packs.  there's something fishy going on. for example when I'm mining, some rounds I'll be unable to move more than one tile at a time into space after leaving the asteroid and have to use my fire extinguisher - to go just one more tile in the direction I need to.  

it's very uncommon but when it comes up it's pretty bad.  I can't figure out the triggers that make the bug happen so I haven't reported it

**Comment by clusterfack** [comment]
If that happens probe try to let an admin know so they can view variable you and check for any runtimes and such.

**Comment by SarahJohnson489** [comment]
I'm not sure if it's related or not but I've had issues both as a nuke op and with EVA jetpacks not actually letting me move around space despite showing its animation.

**Comment by Probe1** [comment]
That was what I was referring to.  It's pretty damn inconvenient when it happens.

**Comment by ComicIronic** [comment]
Cannot reproduce on local as a Mining Borg with the jetpack. Refilling works fine, toggling works fine, going back to momentum movement works fine.

**Comment by clusterfack** [comment]
During testing did you make sure to fully drain the jetpack? I believe it it a problem with the pulse pressurization.

**Comment by Probe1** [comment]
I frequently encountered this during a specific round yesterday as a miner.  With magboots on, whenever I left the edge of the asteroid I would get stuck 1 tile away from the edge.
