### ISSUE TITLE
BORGS DON'T MOVE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27020]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
827fb07bfe7feac1bb705caac256abee574a9da2

# Description
THEY STAND STILL

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by gurfan** [comment]
what the fuck did he mean by this

**Comment by ShiftyRail** [comment]
I have it on good authority that borgs can actually move.
Please include more details in subsequent bug reports.

**Comment by Exxion** [comment]
Apparently he meant Britsky and just called it a borg for some reason
