### ISSUE TITLE
R&D - Destructive Analyzer does not work

### ISSUE THREAD

**Issue by Operativ** [d3athrow/vgstation13#27025]
#### Description of issue

Destructive Analyzer machine does not allow to be accessed via the Core R&D Console when an object is inserted in the Destructive Analyzer.

Tested on current latest, fresh compilations of Packed Station & the default Box Station.

#### Difference between expected and actual behavior

Destructive Analyzer menu is supposed to proceed as usual and allow for research to be progressed.

#### Steps to reproduce

1. Walk into Research and Development
2. Take the battery that is there
3. Place it into the Destructive Analyzer
4. Access the Core R&D Console
5. Press "Destructive Analyzer Menu"

Workaround: kick the Destructive Analyzer while a tech object is present.

#### Specific information for locating

Core R&D Console (/obj/machinery/computer/rdconsole/core): Topic("src=[0x2006970];menu=2.2", /list (/list))
  Operativ (/client): Topic("src=[0x2006970];menu=2.2", /list (/list), Core R&D Console (/obj/machinery/computer/rdconsole/core))
  Operativ (/client): Topic("src=[0x2006970];menu=2.2", /list (/list), Core R&D Console (/obj/machinery/computer/rdconsole/core))
Runtime in rdconsole.dm,863: Cannot read null.level

[tested] [featureloss]

**Comment by d3athrow** [comment]
http://www.byond.com/forum/post/2581688
