### ISSUE TITLE
Noir is bugged if you take Ryetalyn

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27035]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
f173a2c55ad9c1f7023d1e2730d0ce643dfd5e9d

# Description
While everything stays black and white, you need longer see red blood

# Steps to Reproduce
just take some Ryetalyn
# What you Expected
you still see black and white with red blood

# What Actually Happened
no more red blood

**Comment by robintime** [comment]
dupe of #26007
