### ISSUE TITLE
Blisterol chem recipe not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27030]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
44a75b7a0d1cfdd2c9866b12d6126272ca6be7fa

# Description
Tried to make blisterol, it not work. Recipe: 1 aluminium, 1 copper, 2 fuel.

That's a mortar. It is a tiny item.
This is a reinforced bowl, used for crushing stuff into reagents.
It contains:
10 units of Aluminum
10 units of Copper
20 units of Welding fuel
It has nothing to be crushed.

# Steps to Reproduce
Try to make blisterol, you can't.
# What you Expected
Blisterol
# What Actually Happened
10 aluminium, 10 copper, 20 welding fuel.

**Comment by SonixApache** [comment]
🤔

**Comment by Dacendeth** [comment]
required_reagents = list(ALUMINIUM = 1, COPPER = 1, FUEL = 2)
#define ALUMINUM "aluminum"
wrong spelling.
