### ISSUE TITLE
Clown pods and test data

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2704]
There are two seeds coded in the game, but they are not spawnable. The first is a clown pod, and the second is testing data. You can find them at the very bottom of this page https://github.com/d3athrow/vgstation13/blob/master/code/modules/hydroponics/seed_datums.dm

They are not spawnable however, because they are not put in the code here. https://github.com/d3athrow/vgstation13/blob/master/code/modules/hydroponics/seeds.dm

I would very much like this finished for horrifying, horrifying, botany purposes.

**Comment by gbasood** [comment]
This seems like an awful idea, since the clowns that the seeds would produce would be hostile on spawning.

Runtime seeds seem fine though.

**Comment by AutismSpider** [comment]
clown pod seeds make hostile mobs if any thing as antag item it be fine.

**Comment by Killette2** [comment]
I didn't say they need to be obtainable without admin intervention, just that they need to at least exist since partially coded.

**Comment by NigglyWiggly** [comment]
The retaliate clowns wouldn't be hostile on spawning, would they? They're the ones that are peaceful until you attack them, then they HONK your shit in

**Comment by Killette2** [comment]
products = list(/mob/living/simple_animal/hostile/retaliate/clown)

I'd assume so, but it would still be fun. Don't attack the clowns or they all fuck you up. Please add this as it is partially coded and someone decided it was a good enough idea to do so.

**Comment by Cisrox** [comment]
Garbage suggestion. Closeable.

**Comment by Killette2** [comment]
Says you, dickface.

**Comment by PJB3005** [comment]
@Cisrox just because something is retarded doesn't mean it should be closed.
