### ISSUE TITLE
shuttles are still broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27041]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
c320708d1b0618986e28742b418e1ab6e6951bb1

Shuttles will still split in half upon departure/arrival, leading to many splats.

**Comment by gurfan** [comment]
I forgot to mention that carpets seem to get deleted on the salvage shuttle whenever it moves.

**Comment by ShiftyRail** [comment]
Need some context. Which maps? How many people? Did you bring something special or not? Last few rounds I observed, I didn't notice it.

**Comment by DamianX** [comment]
This hasn't been happening anymore
