### ISSUE TITLE
Targetable spells/abilities dont work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27042]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
c320708d1b0618986e28742b418e1ab6e6951bb1

# Description
After activating a targetable power/ability the power does not cast

# Steps to Reproduce
Use any ability that requires you to activate it then click a target

# What you Expected
click the funny square then click the greyshirt to turn him into a statue

# What Actually Happened
spell activates but never casts

**Comment by DamianX** [comment]
I am unable to reproduce this. "Flesh to stone" works just fine.
