### ISSUE TITLE
Metaclub botany sucks

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2705]
Everything about metaclub botany is bad. I do not currently have pictures so I will try to explain my best until I can get them. For starters, despite being the biggest botany, it has less trays compared to box and the maintenance is tiny. That would be a bit forgivable but the main problem is the xenobotany section. First there are no flora data disk boxes in there, so you can't even do it in the first place without admins spawning them for you. Second, the xenobotany equiptment is in a 3x3 room, at the ENTRANCE of botany, with objects filling every corner and only 4 out of 9 movable tiles. How are you going to work there when people use that area to go in and out of work? It is a very awkward place to have those machines, especially in a spot where you need to stand still for a little bit to use both of them. Since you cannot build the xenobotany machines, I am sure you cannot move them still, unless that has been updated. The best solution overall would be to remove metaclub, forget it existed, and hope a new map takes its place.

**Comment by IratePirate** [comment]
I'll go over it now.

**Comment by ComicIronic** [comment]
Is this still an issue?
