### ISSUE TITLE
Ian Can't Wear Cowboy Hats

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27054]
(WEB REPORT BY: rubylips REMOTE: 206.221.180.138:7777)
# Description
Ian can't wear cowboy hats.

# Steps to Reproduce
Try to put a cowboy hat on Ian

# What you Expected
Yeehaw Ian

# What Actually Happened
Ian

**Comment by Kharkov72** [comment]
🤠
