### ISSUE TITLE
Ghosts can use the disease analyzer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27058]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
bcfd4a831bf6f64d9ef152182bcc7fcb46fc8375

# Description

>Notice that the disease analyzer is turning on and off
>unwrench it to try and fix it
>[ghost name] is currently using the disease analyzer

**Comment by Kharkov72** [comment]
was it an admin

**Comment by gurfan** [comment]
no
