### ISSUE TITLE
Making floors doesn't update illumination

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2706]
Making space turfs into regular tiles doesn't remove their space illumination anymore. Other types of turf changes may be affected as well.

**Comment by clusterfack** [comment]
I know for a fact that adding floor tiles to lattices to make regular turfs does it, and admin build click does the same. Modifying changeturf is likely required.

**Comment by eswordthecat** [comment]
Because the area is on space (lighting_use_dynamic = 0)?

**Comment by clusterfack** [comment]
A picture is worth a thousand words? This is the derelict
![picrelated](https://cloud.githubusercontent.com/assets/8516830/5986955/9b766d96-a8d8-11e4-93c4-f0a7346df957.png)
