### ISSUE TITLE
Ammolathe on Roid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27073]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
d4d08bfef598b9e6759d3d0b80f186ccc822a34c

# Description

it has .38 rubber but not .38 normal, like most other stations

# Steps to Reproduce
use an ammolathe on roid
# What you Expected
to see .38

# What Actually Happened
no .38

**Comment by DeityLink** [comment]
there is no lethal .38, you fire .357 instead
