### ISSUE TITLE
Wizard spells cannot be cast during time stop

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27074]
(WEB REPORT BY: ezudiko REMOTE: 206.221.180.138:7777)
# Revision
d4d08bfef598b9e6759d3d0b80f186ccc822a34c

# Description
Attempting to cast clown curse while time stop is active fails with the error "another spell is currently being cast"
# Steps to Reproduce
Cast time stop then try to clown curse
# What you Expected
To clown curse
# What Actually Happened
An error message that another spell was being cast

**Comment by DeityLink** [comment]
@DamianX

**Comment by DamianX** [comment]
Fixed by #27104
