### ISSUE TITLE
Dark Mode Channel Colours

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27079]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
dfe8704726a02c4997f4991d98c6d476c029a6c5

Supply, Service and Common all have the same colours on Dark Mode for me. And as I'm very lazy and don't know how to read it's nearly impossible for me to tell if someone is trying to talk on these radios over common, so most of the time I miss it, because paying attention to every message on common will drive anyone insane so sometimes I filter it out.

**Comment by Kammerjunk** [comment]
yes hello this is still an issue

**Comment by PavelCIA** [comment]
yes fuck this
