### ISSUE TITLE
Common Problem: ' turns in %&39 or something like that.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27084]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
This isn't unique to any one issue but a lot of times when the game has to convert input text and render it somewhere else, apostrophes get garbled. They turn into a weird string.
Some examples:
>when praying 
"I&#39;m jzut checking, don&#39;t mind me."
>locking in vows 
Ramblah says, "Xizz, I vow I won&#39;t let the tranny win.."
Ramblah exclaims, "VOW LOCKED IN!"
Is there any way to fix this? It seems to be an internet wide problem, admittedly.

**Comment by Exxion** [comment]
Sounds like an extra `html_encode()` in each of those places
