### ISSUE TITLE
Ammolathe issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27082]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
bb4fd4fc85b914bec3149178b09c52349d3b8243

# Description
I checked the code to make sure this isn't intended, but it seems the ammolathe only has rubber .38 ammo

# Steps to Reproduce
use an ammolathe

# What you Expected
both types of ammo

# What Actually Happened
only rubber

**Comment by hbycyl** [comment]
The present issue and #27073 are both non issues. The detective's revolver does not have a lethal ammo in .38, but it can fire (unsafely without modification) lethal .357 rounds which the ammolathe does have.

**Suggest closing both issues**
