### ISSUE TITLE
Veers.... (ROIDSTATION- MAPPING)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27090]
(WEB REPORT BY: luzzgawr REMOTE: 206.221.180.138:7777)
# Revision
bb4fd4fc85b914bec3149178b09c52349d3b8243

# Description

One of the consoles in genetics is not a genetics console, but is instead a cloning one.

**Comment by Exxion** [comment]
![image](https://user-images.githubusercontent.com/9827785/87316993-6abc2180-c4f4-11ea-9a7b-b1f6cb966e41.png)
