### ISSUE TITLE
Broken Legs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27108]
(WEB REPORT BY: aerywyn REMOTE: 206.221.180.138:7777)
# Revision
a19aff7a75b3e73242a071f2ab68b14728a32ae8

I tried to cut off the legs of a man with a peg groin and the operation did not work. The text comes up:

"You are beginning to cut off Spray [name]'s leg with the saw.

You cut off [name]'s leg with the saw."

However the leg is not removed. I can keep performing the operation again and again without removing the leg. If I intentionally fail the operation it breaks the leg as it should.

**Comment by DeityLink** [comment]
seems like a runtime error.
