### ISSUE TITLE
Sans text can be affected by stuttering and other effects

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#2710]
This breaks the span, resulting in a message like "<span = $%$^$%^FUCK"

**Comment by NigglyWiggly** [comment]
![ss 2015-01-31 at 04 25 19](https://cloud.githubusercontent.com/assets/9064611/5989899/d533ad0e-a965-11e4-839b-60e5570b1d91.png)

**Comment by ComicIronic** [comment]
Could be fixed by splitting speech genes into ordered groups. Something like "content", which is words and voicechange, "message", which is stutter and loud, and "syntax", which is sans and maybe whisper.
