### ISSUE TITLE
Only readied up Assistant, still returned to lobby.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27100]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
978619d845c1a1888f51b6e04d366a1889586583

# Description
One atmos tech, one doctor, and one mime/botanist. I have assistant on high, readied up roundstart. I get this message. "You have been returned to lobby due to your job preferences being filled." I am able to latejoin as Assistant right after this.

**Comment by PrimeDSS13** [comment]
It keeps happening.
![image](https://user-images.githubusercontent.com/57536342/87668730-a34d3c80-c73a-11ea-8791-1bfe30bc6bea.png)
