### ISSUE TITLE
SOP grenade launcher

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2711]
The SOP grenade launcher for the mechs, cannot be rearmed like the SGL grenade launcher can. Once you use those 6 uses, it's fucked. De and reattaching the weapon does not fix this.

**Comment by ComicIronic** [comment]
Know if any runtimes are firing?

**Comment by Aurx** [comment]
Last I checked, that was deliberate.

**Comment by ComicIronic** [comment]
This is deliberate in the code - the clusterbang launchers made by the mech fabricators are limited-use.
It's a balance issue, then.

**Comment by ConkerDev** [comment]
Balance issue from APRIL. Admin decision?

**Comment by Imagebard** [comment]
Balance issue form last year.
Admin Decision?

@d3athrow

**Comment by ConkerDev** [comment]
Almost a full year. Admin decision? @d3athrow

**Comment by Killette2** [comment]
ban killette2, shitty idea guy!

**Comment by Imagebard** [comment]
@clusterfack Well I daresay this can be closed.
