### ISSUE TITLE
Robotic limbs not working properly after being replaced

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27117]
(WEB REPORT BY: theophrastus REMOTE: 206.221.180.138:7777)
# Revision
5c893c8759ed21c880780549df29cd42d3387567

# Description

Mime blows my robotic arm off with an ion rifle. I get a replacement arm. I can now select that hand, but the hand is "not fine enough for this action"

Tried with two different arms that were printed and surgically attached

# Steps to Reproduce
Gib robotic limb with ion rifle. Replace limb with new robotic limb

# What you Expected
the hand to work.

# What Actually Happened
the hand was selectable, but didn't work

**Comment by Theophrastus1** [comment]
Haha disregard this, I was not aware of the multitool reboot function; please close
