### ISSUE TITLE
Large Artifacts Bug on Roid Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27114]
(WEB REPORT BY: bmurdoc REMOTE: 206.221.180.138:7777)
# Revision
17fb1078b5eb0b1c551e8f085139cb1f9afcf954

# Description
Had a large artifacts signature end up being somewhere in empty space, not on a rock on Roid Station. Haven't had that problem on any other station. 

# Steps to Reproduce
Collect core samples and process them on Roid Station until you have the signal triangulated onto its targeted area, target area brought me to empty space or an area that was cleared out already.

# What you Expected
To find a large artifact

# What Actually Happened
Found that no matter how many samples i took of the area, it always pointed away from rocks and into space.

**Comment by DeityLink** [comment]
Really not sure how that could be. I'll close now, if it happens again notify an admin so they may use the Artifacts Panel to try and find it.
