### ISSUE TITLE
Chameleon cultists that dance around the blood stone remain invisible despite "moving"

### ISSUE THREAD

**Issue by drawsstuff** [d3athrow/vgstation13#27136]
#### Description of issue
I'm still reeling from a cult round the other day. Highlights include a triple conversion, clutch sacrifice in the nick of time, and a skeleton cultist security officer carrying the cult to victory despite a complete lack of all blood. But what sticks with me the most was the dance around the anchor stone, which is where the fun begins. While dancing around the final stone, I wasn't sure if I was going to be able to pull it off on my own, with security bearing down with shotguns, I was sure my time was up. However, the officer (HoS? It doesnt matter) never noticed me because I had the chameleon mutation. Despite chameleon requiring you to stand still, I remained invisible while dancing around the stone, allowing me to summon Nar-Sie even with officers and most of the station bearing down and breathing down my back.

#### Steps to reproduce
1. Gain the chameleon mutation
2. Spread enough blood to enter the second to final chapter of cult.
3. Dance around the anchor stone

You should slowly fade into invisibility, despite being in motion.

#### Server revision

98eed8c1e3d6ad26df1a424f12de40d802c6fd95

**Comment by Allspice** [comment]
feature

**Comment by DeityLink** [comment]
That's hilarious, gonna have to fix it though
