### ISSUE TITLE
Full windows won't connect

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27139]
(WEB REPORT BY: repertor REMOTE: 206.221.180.138:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
Full windows created by diagonally clicking on a grille won't connect to eachother but ones created through using glass in hand will.
# Steps to Reproduce
click two grilles diagonally and connect the glass for test one and create two full windows from the menu and connect them.
# What you Expected
for them to seamlessly connect
# What Actually Happened
They did not connect at all

**Comment by DeityLink** [comment]
oh yeah, I think you're not supposed to place windows on grilles diagonally.
