### ISSUE TITLE
Sheet Snatcher 9000 causes screen stretching

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27141]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
Using the cyborg sheet snatcher and dragging on self to check conents creates vertical, not horizontal, contents menu. Once dragging has happened and contents are dumped, next additions will show vertical menu without dragging to see contents.
https://cdn.discordapp.com/attachments/563458184153661440/734120974798028800/unknown.png
https://cdn.discordapp.com/attachments/563458184153661440/734121545026371664/unknown.png

# Steps to Reproduce
Put sheets into Sheet Snatcher 9000
Drag Sheet Snatcher on self
Menu should look like in the screenshots

# What you Expected
To see the contents of the Sheet Snatcher horizontally.

# What Actually Happened
The Sheet Snatcher caused a vertical menu and shrunk the playable screen, showing black where the screen used to be.

**Comment by DeityLink** [comment]
Is that still happening?

**Comment by DeityLink** [comment]
Well I guess this answers that lol.
