### ISSUE TITLE
:H defaults to common channel instead of department

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#27182]
#### Description of issue
using :H is supposed to talk to your main department, but as a cargo tech it made me speak over common radio.
Might impact all jobs dunno.

#### Difference between expected and actual behavior
talking on cargo
spoke on common

#### Steps to reproduce
be a cargo tech and use :h to talk

#### Length of time in which bug has been known to occur

Whenever common got added to headsets.

#### Server revision

Revision: 98eed8c1e3d6ad26df1a424f12de40d802c6fd95

**Comment by DamianX** [comment]
#27262 has more information
