### ISSUE TITLE
pre-setup lobby status tab often crashes my client

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27180]
(WEB REPORT BY: repertor REMOTE: 206.221.180.138:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
I don't know if this is something on my end or not but something about the list of players in the status tab will more often than not crash my game.
# Steps to Reproduce
unsure
# What you Expected
Not to crash when I want to see how many are readied up
# What Actually Happened
I have to struggle to open multiple byond loading instances when one inevitably crashes

**Comment by DeityLink** [comment]
Please open a new issue if the problem persists.
