### ISSUE TITLE
pAI GPSes still use nanoUI and can't be interacted with

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27192]
(WEB REPORT BY: potatomancake REMOTE: 206.221.180.138:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
Took GPS as a pAI and was surprised to see the old nanoUI GPS, and was more surprised to see that I couldn't click any of the buttons. The only way to update it was closing and opening it, like you do. Not sure if these were intended to be updated to tgUI or not, but I've never had it unable to work before.
# Steps to Reproduce
be pAI
take GPS
# What you Expected
tgUI and interactivity
# What Actually Happened
nanoUI and no interactivity

**Comment by DamianX** [comment]
fixed
