### ISSUE TITLE
Horizon breaches can't be repaired

### ISSUE THREAD

**Issue by hbycyl** [d3athrow/vgstation13#27198]
#### Description of issue

If there is exposed space in the ship from an explosion or something, you can't build new lattice to fix it

#### Difference between expected and actual behavior
 expected: attack space with rod, receive lattice
actual: nothing happens

#### Steps to reproduce

see above

[horizon]

**Comment by Kammerjunk** [comment]
@GeneralVeers25 toil, slave
also I guess we need a Horizon tag

**Comment by Accipitermaris** [comment]
the real dark souls starts here

**Comment by Exxion** [comment]
We've had a Horizon label
Probably not in the self-tags though

**Comment by Exxion** [comment]
Also I have no idea how this could be map-related but I guess we'll see

**Comment by Kammerjunk** [comment]
well Horizon has special space

**Comment by Exxion** [comment]
Does it? That would do it

**Comment by Kurfursten** [comment]
Yeah horizon has its own base turf for z1

**Comment by GeneralVeers25** [comment]
Yeah this is definitely an issue with the space transit turfs.

**Comment by hbycyl** [comment]
The turfs under the ship should be normal space, or if you really need immersion , you could do some kinda shiny 'hyperspace bubble' turf that's just a reskin of normal space.

The other option is make the transit turfs buildable like regular space, in which case 1 tile wide lattice 'rear-wings' going out really far will be meta, and that just negates the point of the transit turfs to begin with
