### ISSUE TITLE
recycler bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27194]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
recycler eats matts for no rason
# Steps to Reproduce
place 50 stacks of metal glass and plasma in the recycler, set R-plasmaglass to highest proirotiy, watch as it eats your metal and glass
# What you Expected
a bug I reported one year ago to be fixed, and my plasma glass
# What Actually Happened
2 sheets of plasma glas, 48 sheets of plasma, 2 sheets of metal and glass

**Comment by SonixApache** [comment]
AGAIN?
