### ISSUE TITLE
Positronic brains can no longer speak on Binary [SAYCODE]

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#2720]
another issue caused by our half arsed saycode port. Positronic brains are no longer able to speak on binary, previously they were able to do so but unable to hear it.

**Comment by ComicIronic** [comment]
I think this is actually the intended effect, and the previous implement was a bug.
Because posibrains should be able to hear binary, but not speak it.

**Comment by AutismSpider** [comment]
Before it was both they could talk and hear it.

until some shit happen with people using pos brains to find out if the Ai was rouge or not etc so it just talk and can't hear it.

**Comment by Ephx1** [comment]
I think we should at least keep the ability to speak on binary, it's not possible to make a posibrain with a radio so when their body explodes there's no way to alert someone to their presence.

**Comment by d3athrow** [comment]
Thing is they really shouldn't be able to talk on binary without being able to hear it, and if they can hear binary then you get ghosts ruining malf AI rounds like they were doing before.

**Comment by ComicIronic** [comment]
So, notabug?

**Comment by ConkerDev** [comment]
Not a bug, and as discussion, its quite stale.

**Comment by Cisrox** [comment]
Closeable.
