### ISSUE TITLE
Golden Carp Cigarette sprite issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27201]
(WEB REPORT BY: cowboybuttsdrivemenuts REMOTE: 206.221.180.138:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
As a vox facing eastwards, the lit golden carp cigarette sprite is in the wrong position, attatched to your chest.
The unlit sprite is in the correct position, though.  https://i.imgur.com/5FA9oNh.png
# Steps to Reproduce
Be vox, light a golden carp brand cigarette and smoke it, then turn right.
# What you Expected
Smonk in right space
# What Actually Happened
smonk glued to chest

**Comment by GreatBigFailure** [comment]
They say when you're lost without a map you should give a Vox a smoke. Nature's mossy rocks they call them.

**Comment by DeityLink** [comment]
Amazing ckey

**Comment by Eneocho** [comment]
Ram Ranch
