### ISSUE TITLE
You cannot close a locker if it is infront of a fireaxe cabinet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27208]
(WEB REPORT BY: repertor REMOTE: 206.221.180.138:7777)
# Revision
98eed8c1e3d6ad26df1a424f12de40d802c6fd95

# Description
Everything is apparent from the title. plus one spawns like this on horizon
# Steps to Reproduce
open locker in front of axe
# What you Expected
close locker
# What Actually Happened
locker stuck

**Comment by GeneralVeers25** [comment]
I moved the fire axe on Horizon but did not otherwise address the code behind this issue.
