### ISSUE TITLE
photocopier feature requests: toner adjustment

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#27228]
#### Description of issue

~~Photocopiers don't copy the name/title of photos. I think they *do* copy the name of documents.~~
Photocopiers hold like 30 toner or something which is only enough for 3 color copies of photos. That's lame. I guess it's done to prevent document spam, since copying a normal paper only costs 1 toner... but still.

**Comment by west3436** [comment]
Toner cost reduction or even the removal of toner altogether would benefit those of us who enjoy submitting the crew to paperwork or the paperwork SME
