### ISSUE TITLE
Viewport stuck after using Advanced Security Cameras Console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27229]
(WEB REPORT BY: runian REMOTE: 206.221.180.138:7777)
# Revision
0289efc8b46ac444714402573ba115a2b2393548

# Description
Camera/view stuck on last camera viewed when using advanced security camera console.

# Steps to Reproduce
Be MoMMI.
Create an advanced security camera console.
Use advanced security camera console.
Click a bunch of random cameras (to view) fast.
Exit the window used to click on cameras.
Be stuck viewing the last camera used.

# What you Expected
To return back to viewing my character.

# What Actually Happened
Stuck viewing from perspective of a security camera.

**Comment by west3436** [comment]
Advanced Security Cameras Console was removed in #30607.
