### ISSUE TITLE
Mindswap crashes clients

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27235]
(WEB REPORT BY: repertor REMOTE: 206.221.180.138:7777)
# Revision
16d9bd953207bbc8b3f85b458463abe7b98ba746

# Description
Mindswap crashes both users clients but sends the one who cast it to the lobby and makes them capable of joining the round. Circumstances involved casting pain mirror and a shotgun right before mindswap was cast.
# Steps to Reproduce
Mindswap(maybe shoot a shotgun and cast pain mirror) and record results
# What you Expected
no crashing and not going to the lobby
# What Actually Happened
both of the prior things

**Comment by DeityLink** [comment]
Should have been fixed since then right?
