### ISSUE TITLE
[Feature Request] Add pill collector to medical supplies cargo crate

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2724]
Why is the pill collector a magical item that cannot be created or ordered?  It's a pill collector.  And if someone loses it or there's a fire or any reason then chemistry gets a big old dick right in the behind.  

Add it to the medical supplies crate from cargo would you?

For bonus points, add them to RnD as a medium level medical unlock so mechanics can hand them out.

**Comment by Probe1** [comment]
[17:14:16] <Comic> We could make it big
[17:14:19] <Comic> w_class = 4
[17:14:29] <Comic> Swhat I did for the socket wrench to make it inconvenient

this works if the coder is hesitant about balance.  the core issue is medbay gets fucked very hard when the pill collector is lost and there's no recourse.

**Comment by Riukanojutsu** [comment]
Making it scannable for the mechanics could also work.
