### ISSUE TITLE
No way to roll for primary wizard without being autoadded to apprentice rolls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27247]
(WEB REPORT BY: jackmassacre REMOTE: 206.221.180.138:7777)
# Revision
eaef1d8914b69dae58f589ffda776e5710116120

# Description

With wizard set to yes or always, the only two options that allow you to roll for primary wizard, you are also automatically added to apprenticeship rolls, and must manually remove yourself from the roll if you are dead and dont' want to apprentice.

There should be a way to roll for wizard without risking being apprenticed while dead and AFK. A separate setting, or the autoadd for apprentice only working when set to "always", either would be great.

**Comment by DamianX** [comment]
scrolls always require you to sign up manually now
