### ISSUE TITLE
[Bug] Culted diona nymphs lose cult status when they grow to be dionas.  

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2726]
This is as you would imagine a serious issue.  They lose their cult status and can blab about everything they've seen at any time they choose to evolve.

**Comment by DeityLink** [comment]
Now that's indeed a problem. Cult status is tied to the mind of a mob, that'd mean that until now the mind of dionas wasn't properly transferred.

**Comment by Probe1** [comment]
i <3 @DeityLink
