### ISSUE TITLE
Asteroid Z-level transition.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27268]
(WEB REPORT BY: holyshiznignog REMOTE: 206.221.180.138:7777)
# Revision
c015a2f9cab556642934955ce79b0ccd1eaa1f92

# Description
Changing z-levels well moving towards the west can stick you in a rock, one of the ones floating on the very east most edge on the station z-level, in the south east, the biggest of the north ones in that cluster following around the back of the prison station rock and directly north of the ruined nuke ops ship.
# Steps to Reproduce
Go through a z-level
# What you Expected
Not to get fucking stuck in a rock.
# What Actually Happened
Stuck in a rock.

**Comment by Dacendeth** [comment]
He's talkin about roidstation if that wasnt obvious
