### ISSUE TITLE
A lot of special-frequency intercoms are now stuck on common

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#27276]
#### Description of issue

AI private intercoms, chaplain's confessional intercoms, probably the interrogation room one as well.

#### Difference between expected and actual behavior

:I hey AI open your core
[AI private]: hey AI open your core
ai: ok come on in
vs
:I hey AI open your core
[common]: hey AI open your core
everyone: lynch he

#### Length of time in which bug has been known to occur
This is the tough part. Probably a few weeks.

**Comment by StreptoMutans** [comment]
Change "probably a few weeks" to "since #23876 ".
I don't think :p works at all.
#25100
And while we're here, :i hasn't been working for me either in deathgasping

**Comment by DeityLink** [comment]
Does this still occur?

**Comment by StreptoMutans** [comment]
I know the Box confessional booths intercoms aren't set properly, AI Upload ones should be fine.
:p works now, :i is still broken for deathgasps
