### ISSUE TITLE
Doppelganger doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27286]
(WEB REPORT BY: blitzikaze REMOTE: 206.221.180.138:7777)
# Revision
8840a61963f0f1b9d64840b2dfd0241d4e16746d

# Description
The Doppelganger spell does nothing when the spell button is pressed, even in full clown wizard garb
# Steps to Reproduce
Buy doppelganger, click spell, nothing happen
# What you Expected
I upgraded doppelganger twice, and i expected to leave funny clown wizards everywhere
# What Actually Happened
Nothing, i used 60 spell points for a spell that didn't work

**Comment by SonixApache** [comment]
![image](https://user-images.githubusercontent.com/8468269/88554264-98da4f00-d026-11ea-9bfd-0134fead1086.png)
![image](https://user-images.githubusercontent.com/8468269/88554594-fbcbe600-d026-11ea-90b3-8acbcde128d6.png)
unable to reproduce
