### ISSUE TITLE
Pipe Tomahawk doesn't retain drugs in plants

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27293]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
804b305f5e73b84a04d81c5813c22379ced08eac

# Description
Putting a plant into a pipe tomahawk seems to remove all of the chemicals you may have injected into it. This has ruined my opium den's profits.

# Steps to Reproduce
1. syringe drugs into a plant
2. stuff plant into pipe tomahawk
3. be disappointed at the lack of drugs in your system

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Unable to reproduce @Kurfursten
