### ISSUE TITLE
Autolathe can't recycle anything

### ISSUE THREAD

**Issue by assmops** [d3athrow/vgstation13#27291]
#### Description of issue
Last round on Horizon, wizard bought darkness and broke all the lights. I was QM so I printed replacements on the autolathe.
I tried feeding the broken tubes into the lathe, but got an error stating that "the lathe only accepts metal and glass".
I also tried recycling airlock electronics and cable coils, with the same result.

#### Difference between expected and actual behavior
Expected:
To be able to recycle things made of metal and/or glass
Actual:
Items remain in hand and not recycled

#### Steps to reproduce
-Go to autolathe
-Try to recycle broken lighttube
-Get error

#### Length of time in which bug has been known to occur
Probably since the ammolathe recycling pull

#### Server revision
Game: 34284be56eaaa39de48ef7ce001851b21c30a7a6 
Patches: d2ab4eb4f06a63d241b13123f1b307e0b3de5b5c 

[<consistency>]
[<easy>]
[<featureloss>]

**Comment by BomberBro** [comment]
probably caused by #27190
