### ISSUE TITLE
You can drag items to cult altars from any distance as any mob

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#27303]
#### Description of issue
Dragging items to a cult altar will put the item on top of the altar. It does not matter if you are next to the altar, it does not matter if you are a human, a monkey, a ghost, you can just mail things straight to cultists.

#### Difference between expected and actual behavior
I'd expect this to only work if you are adjacent to the table, with the object adjacent too, as a living person with opposable thumbs. That turned out to be wrong.

#### Steps to reproduce
>be any mob
>click drag any item
>move until you see a cult altar
>drag and drop item on altar

**Comment by gurfan** [comment]
holy shit

**Comment by DeityLink** [comment]
ahhhh
