### ISSUE TITLE
Cultist converts getting boxed destroys their borer even if the borer leaves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27305]
(WEB REPORT BY: spookman REMOTE: 206.221.180.138:7777)
# Revision
f128ebe51c76f70d462ef44283f4661e5d6810c9

# I was playing a Cortical Borer 

# First, enter a non-cultist host. Then, have a cultist perform a conversion ritual on them, and leave during the ritual. Enter another host. If your first host refuses the conversion and has their body destroyed as a result, you will also be destroyed (force ghosted).

# I expected that only being inside of the host at the time of the boxing would destroy you.

# Instead, it seems the moment the ritual starts, you are considered part of your hosts body no matter what.

**Comment by DeityLink** [comment]
Shouldn't be an issue now that boxing is removed.
