### ISSUE TITLE
AI defensive measures feature request: CTRL/Alt-clicking edition

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#27301]
#### Description of issue
Foam dispensers use an UI to work - the same window as the laser menu, I think.
It's annoying to have to use them, especially if you want to use more than one.
As such, it'd be really nice to just be able to CTRL+click or alt+click on them to activate them.

Likewise for turret controls - CTRL+click to enable/disable, alt+click to switch between stun and lethal.
[featurerequest]

**Comment by toomykins** [comment]
this already exists for turret controls. I will add the foam dispenser feature.
