### ISSUE TITLE
it's always cult

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27314]
(WEB REPORT BY: mentgah REMOTE: 206.221.180.138:7777)
# Revision
1f256d195689efba7424d1310c383a72871e538f

# Description
setting all weights to 1 was a mistake
# Steps to Reproduce
log in
# What you Expected
to have a good time
# What Actually Happened
cult rounds all day everyday

**Comment by west3436** [comment]
feature

**Comment by gurfan** [comment]
feature
