### ISSUE TITLE
Russians keep saying slurs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27324]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
![russian](https://i.imgur.com/CpAPy5k.png)

![zhanna](https://i.imgur.com/OPy7RJR.png)

**Comment by Exxion** [comment]
Didn't I just fix this like a week ago?

**Comment by Exxion** [comment]
Oh, right. I did but the server is on an older version and my fix doesn't work. Update to latest 513 to fix it.

**Comment by Exxion** [comment]
Server's been updated and this has thus been fixed.
![image](https://user-images.githubusercontent.com/9827785/89126695-c2c3c380-d4b5-11ea-8ecf-56dbb18223c0.png)
Sorry for shit cropping
