### ISSUE TITLE
Forcing a borg's name by using a pen on an exoskeleton doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27323]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
It's because they still get the prompt to change their names

**Comment by DeityLink** [comment]
I dunno, seems better to me to let people name themselves.
![image](https://user-images.githubusercontent.com/7573912/131126040-57b0d81e-b2e9-4821-892a-af014a0ba4df.png)

**Comment by west3436** [comment]
Feature (just give them a law 2 order on Asimov)

**Comment by Pastamadness** [comment]
Actual bug you hack.

**Comment by west3436** [comment]
> Actual bug you hack.

It's not in the wiki, hasn't worked since at least 2019, and isn't advertised anywhere as a feature so no, it's not a feature.

**Comment by SonixApache** [comment]
this is an actual bug

**Comment by west3436** [comment]
> this is an actual bug

I realized that after digging through the code. Pastamadness opened a new issue and I've created a PR to close it.
