### ISSUE TITLE
automatic ore loader

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27332]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
36e5521888203563624910e57c6444d9b9f301f7

# Description
Automatic Ore Loader no longer automaticly picks up ore from the floor, it acts like a normal ore loader
# Steps to Reproduce
Use an automatic ore loader
# What you Expected
To pick up ore from the floor
# What Actually Happened
It acts just as a normal satchel thing

**Comment by Kurfursten** [comment]
could not reproduce on live

talked to flarg and he said he didn't turn it on
