### ISSUE TITLE
Shuttle wall corner icons seem a bit fucked

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#2734]
![shuttlesprite](https://cloud.githubusercontent.com/assets/6830971/5993324/e3211318-aa44-11e4-9324-2315c9ace30a.png)

Been like this for a while now. No idea what the issue is.

**Comment by Konater** [comment]
I noticed they overlap with other turfs or something, you need to put down the space or shuttle floor tile first then ctrl click the corner on

**Comment by d3athrow** [comment]
The way turfs that have transparency works is if you place it over an existing turf it adds that turf as an underlay, when shuttles move they don't retain the underlays for some reason.

**Comment by IratePirate** [comment]
Well that's irritating.

**Comment by clusterfack** [comment]
Fixed by the chicken
