### ISSUE TITLE
Monkeys can wear tools

### ISSUE THREAD

**Issue by GarrusVakarian** [d3athrow/vgstation13#2735]
![k](https://cloud.githubusercontent.com/assets/6507460/5993328/5e8d886c-aa4d-11e4-85db-58d482d09560.png)

**Comment by gbasood** [comment]
I noticed this when trying to put a plastic bag on a monkey's head.

Disappointed at the results but didn't think it was a bug at the time.

**Comment by d3athrow** [comment]
pff haha

**Comment by DeityLink** [comment]
er... I plead guilty I guess.
