### ISSUE TITLE
Phylactery Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27355]
(WEB REPORT BY: jackmassacre REMOTE: 206.221.180.138:7777)
# Revision
9bc85f12157021425f4dece73911fcc7777222a9

# Description

Wizard phylactery is either entirely broken, or breaks when it tries to activate if the wizard dies while disconnected.

Results in the body reviving, but the player being stuck as a ghost and unable to enter body. This seems to persist even if the same player rolls wizard again and buys a new phylactery, at which point their death even while connected produces the same bug with a brainless body and stuck as a ghost.

**Comment by kernikov** [comment]
That's what you get for not being a meta goblin when you picked your spells.
