### ISSUE TITLE
Ion rifle sprite bugs out when it's empty

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#27370]
#### Description of issue
the sprite pulses between some old sprite and the new sprite
![gunflash](https://user-images.githubusercontent.com/26881007/89296574-84064880-d630-11ea-970e-31a315ce72a2.gif)

#### Difference between expected and actual behavior
all new sprites for ion rifle
one old holdover makin things ugly

#### Steps to reproduce
empty an ion rifle and drop it on the ground to look at.

#### Length of time in which bug has been known to occur

 #27081 missed one sprite I guess?

**Comment by drawsstuff** [comment]
I'll see what I can do to fix this
