### ISSUE TITLE
[Bug] Farmbots stop working after an indeterminate amount of time

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2737]
I don't have a solid report for this but it's happened several times in the last few days.  Farmbots with plenty of water left seem to crap out and stop working at some point.  It happens when one or multiple farmbots exist in the same area.  They stop moving and watering crops on their own.  Could have to do with bees being on the same tile but I'm not sure.  

Weird one and hard to test because it takes 30~ minutes to occur.

**Comment by d3athrow** [comment]
something is amiss with a* as it stops working randomly.

**Comment by Probe1** [comment]
being worked on at gitlab
