### ISSUE TITLE
cult typo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27377]
(WEB REPORT BY: chucklemonger REMOTE: 206.221.180.138:7777)
# Revision
74e6a1dd6bbde21477e036e89b54d138a23356d9

# Description
Missing punctuation and incorrect plural in talisman

# Steps to Reproduce
Create a talisman

# What you Expected
"The blood drops merge into each other, and a talisman takes form in their place."

# What Actually Happened
"The blood drops merge into each others, and a talisman takes form in their place"

**Comment by DeityLink** [comment]
Fixed by #27409
