### ISSUE TITLE
Bear meat does not work for basic burger recipe

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27382]
(WEB REPORT BY: theophrastus REMOTE: 206.221.180.138:7777)
# Revision
036a826299c47776d918f61b540799cec0f23150

# Description
Using bear meat in a 5 flour 1 meat burger in the microwave produces burned mess

# Steps to Reproduce
add 5u flour and 1 bear meat to microwave and cook

# What you Expected
bear burger and or generic burger

# What Actually Happened
gunk

**Comment by DeityLink** [comment]
Feature Request it is then
