### ISSUE TITLE
Feature Request: Change how vaults are spawned

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#27385]
**Reasoning**
Right now vaults are just spawned randomly from a list. On startup the server decides how many will spawn then just picks that many. Problem is that not all vaults are made equally. On paper this just adds RNG and makes vault hunting exciting but not necessarily round changing every time. In practice it makes it so adding several small, less interesting vaults actively makes vault hunting less fun because your cute little garden or space bakery that's really very charming has overwritten spessmart. 

**Suggestion**
A point system, make small or less rewarding vaults cost few points, make large vaults like spessmart or the zombie one cost a lot of points. We don't have enough vaults to make retro-actively adding a point value much effort at all. This way if 10 small flavor vaults are added it won't make anyone's round boring after the first time they see them. This means space can be more populated without just raw powercreep. 

I'd do this myself but I'm not confident enough tinkering with things related to the server itself in this regard. If it gets added I'll likely pump out some small vaults though. 

[vault] [system]

**Comment by kernikov** [comment]
![Yo-Dawg-Heard-You](https://user-images.githubusercontent.com/5549060/89448725-9c07c600-d71d-11ea-8a44-5e7ba56aa935.jpg)
Yo Dawg, I heard you like Dynamic so I put dynamic vault spawning in your dynamic gamemode.

**Comment by GreatBigFailure** [comment]
Yes, gib

**Comment by Kurfursten** [comment]
I don't know, this *does* sound like powercreep. Trying to ensure a minimum number of guns spawn in space to reward those who abandon the round to go cheese the vaults the 40th time?

**Comment by GreatBigFailure** [comment]
Not all vaults reward guns. A lot definitely do but there's plenty of other things out there. 
I admit this is a semi-selfish request. I'd like to be able to spend a day lazily mapping some simple vaults but would actually like to PR them without reducing the reward of going into space.
>abandon the round

It's basically miner in that regard. When you first start vault hunting you just want to see what's out there so you spend the whole round doing that. Once you're more familiar you're looking for things to bring back to the station like some weird santa clause. 

It's just silly that the thought of making more of something could reduce fun/variety for a group of people. The vault with the fake malf AI surrounded by turrets for example, fuck that vault. Just eats up a vault spawn. There's nothing but death there. Not all vaults need amazing rewards but there needs to be something more than "Oh huh some turrets".

**Comment by DeityLink** [comment]
>point-based Vault spawning

I can get behind that.

**Comment by dunsel-hordon** [comment]
Sounds better than the current way vaults are spawned

**Comment by Kurfursten** [comment]
Vaults are just part of the experience of seeing space, they're scenery to make the game feel more alive.

It feels really lavalandbrain to have the outlook `vault 14 identified... "MALF SAT" - verdict: no powergame tools, ignore`

**Comment by GreatBigFailure** [comment]
Well once you've seen them all that's how it is. The current vault system doesn't lend itself to "scenery" either since you need to specifically go out and search for them rather than ever really spotting one when you get spaced or whatever.
Besides that this change would actually support wanting them to be scenic. I've requested this because I want to make some small, simple vaults without much reward in them. If I make those on our current system it'll overwrite more fun/rewarding vaults. With this system they wouldn't.
