### ISSUE TITLE
General Fabricator can't make 0 cost items

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#27408]
#### Description of issue
![gravyboat](https://user-images.githubusercontent.com/64218965/89600047-1411e100-d82f-11ea-9763-ee995f0a1c08.png)

Items that cost 0 materials can't be made. The machine says it doesn't have enough materials. This has only happened with law planners since they cost so little pre-upgrade, but it's probably more than just them.

#### Steps to reproduce
Add planning frame to gen fab
Upgrade gen fab
Try to make planning frame

**Comment by Kharkov72** [comment]
>censored the chef saying cum bucket but not me

owned

**Comment by GreatBigFailure** [comment]
Aaaah noooo

**Comment by DrSnips** [comment]
owned

**Comment by Kharkov72** [comment]
anyways according to barry it's something along the lines of
`starting_materials = list(MAT_GLASS = 2000/CC_PER_SHEET_GLASS) is a mistype 
the price to print one is glass divided by 3750
/obj/machinery/r_n_d/fabricator/proc/get_resource_cost_w_coeff(var/datum/design/part as obj,var/resource as text, var/roundto=1)
    return round(part.materials[resource]*resource_coeff, roundto)
rounds it to 0`

rounding...
