### ISSUE TITLE
We should have location-specific SMES units with appropriate input/output numbers and charge settings.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#27407]
#### Description of issue

Certain SMES units should charge but don't.  Their numbers are also way off and need tweaking every round. This is stupid.
We should make a subtype for solars, telecomms and AI cores, and add them in the appropriate locations.
I haven't gotten the numbers for all of those, but a round or two per map should be plenty.

Box telecomms SMES:
output is too high - should be lowered to ~8k default
input is too high - should be lowered to ~10k default
doesn't charge by default - should be set to charge by default

**Comment by DeityLink** [comment]
I'd argue that setting those up should be part of engineers' job.
