### ISSUE TITLE
Xenobiology didn't spawn a starting slime

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27418]
(WEB REPORT BY: nukas REMOTE: 206.221.180.138:7777)
# Revision
e038c90164be9688be015651dc492d8f13905323

# Description
Xenobiology didn't spawn a starting slime.
# Steps to Reproduce
Play on the new meme map.
# What you Expected
My fucking slime to be there.
# What Actually Happened
NanoTrasen decided to cut expenses and fuck me in the ass.

**Comment by d3athrow** [comment]
@Viciousaurus
