### ISSUE TITLE
synergy bar storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27417]
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
e038c90164be9688be015651dc492d8f13905323

# Description
try to enter bar storage as bartender, cannot
# Steps to Reproduce
run face into airlock as bartender
# What you Expected
be able to get bartender stuff
# What Actually Happened
door stuck

**Comment by d3athrow** [comment]
@Viciousaurus
