### ISSUE TITLE
synergy bar sign

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27420]
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
e038c90164be9688be015651dc492d8f13905323

# Description
changing bar signs on synergy 
# Steps to Reproduce
change the damn sign
# What you Expected
it to stay in one place 
# What Actually Happened
shifts off the wall

**Comment by d3athrow** [comment]
@Viciousaurus

**Comment by Kammerjunk** [comment]
I set the sign's pixel_y to 32 when bungo ahelped to make it look like it's in the wall, but I guess it reverted when it changed icon state?

**Comment by Viciousaurus** [comment]
it's strange, it should be reachable by people
![bars](https://user-images.githubusercontent.com/68832462/89694632-a5448e80-d8e7-11ea-8e47-22d49b3abb42.png)

**Comment by Viciousaurus** [comment]
nvm got it
