### ISSUE TITLE
Synergy: missing acid in R&D

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27423]
(WEB REPORT BY: kammerjunk REMOTE: 206.221.180.138:7777)
# Revision
e038c90164be9688be015651dc492d8f13905323

# Description

R&D spawns with 2 empty beakers and 0u sacid
suggestion: use the sacid beaker subtype: `/obj/item/weapon/reagent_containers/glass/beaker/sulphuric`

**Comment by d3athrow** [comment]
@Viciousaurus
