### ISSUE TITLE
Synergy: AI can't click AI shutter buttons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27425]
(WEB REPORT BY: kammerjunk REMOTE: 206.221.180.138:7777)
# Revision
e038c90164be9688be015651dc492d8f13905323

# Description

there are 2 buttons on the walls to the south and the north of the AI core that control the south and north shutters at the AI core. the AI can't see them.
suggestion: move them to the turfs to their right and use pixel_y to make them look like they're on the wall (common practice), then either give the AI an internal button that does this too or give the camera inside X-ray.

**Comment by d3athrow** [comment]
@Viciousaurus
