### ISSUE TITLE
Synergy: chapel backroom has no chapel access requirement

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27421]
(WEB REPORT BY: kammerjunk REMOTE: 206.221.180.138:7777)
# Revision
e038c90164be9688be015651dc492d8f13905323

# Description

anyone can walk into the chapel office from maint because the only access check is maint (req_access contains one entry: 12)

**Comment by d3athrow** [comment]
@Viciousaurus
