### ISSUE TITLE
Chickens, cows, etc. can swap places with other mobs through a one-direction window/regardless of intent

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#2742]
The window has to be placed on the chicken's tile, placing it outside won't work. This also happens even if your intent is set to harm/push/grab. I assume this happens with every `simple_animal`, but god knows what else could be affected.

WebM that illustrates this: http://a.pomf.se/yclmqq.webm

**Comment by clusterfack** [comment]
Yeah chickens have no special code so it probably applies to all simple animals. Possibly a result of changing bumped to bump to fix the bug where they used to jump 2 squares.

**Comment by IratePirate** [comment]
Is this what leads to monkeys breaking out of their pen all the time?

**Comment by clusterfack** [comment]
No Irate, I believe thats a completely different issue that has to do with windows not blocking diagonal motion, so the monkeys are being pushed out diagonally by two other monkeys.

**Comment by wwjnc** [comment]
Yeah, there's some issues with diagonal windows too, especially when the room depressurizes quickly in that direction--some items fly off the room through them.

**Comment by d3athrow** [comment]
Diagonal movement should have been fixed from the TG stuff I merged.

**Comment by clusterfack** [comment]
Can you close issue https://github.com/d3athrow/vgstation13/issues/1747 then

**Comment by d3athrow** [comment]
Spent the better part of a day trying to figure out why its happening. Simple animals, excluding Ian, are bumping into things even after turf/Enter returns false, except their second bump seems to be byond's default turf/Enter check which shouldn't ever be ran.

**Comment by d3athrow** [comment]
Turns out that Move() calls Bump on the first dense thing it finds in the target location if turf/Enter or atom/Cross returns false. This resulted in us bumping the window when we found it in our way resulting in no move, then Move caused us to bump the human on the other side of the window. Simple animal code causes it to switch places with any mob it bumps into.
