### ISSUE TITLE
Synergy Security Door Access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27428]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
e038c90164be9688be015651dc492d8f13905323

# Description
for some reason security officers can't open evidence storage, and the warden can't actually open the door to the execution gas room chamber.

**Comment by Kammerjunk** [comment]
evidence storage has req_access list with one entry: 3 (access_armory)
suggestion: make it 4 instead (access_forensics_lockers)

execution chamber (the outer door named Execution Chamber) has one entry: 1 (access_security). warden should be able to open that.
inner door (sec door named Incinerator) is accessible to anyone who can enter sec (same access as the front doors, which actually makes it more lenient than the outer door), but the inner Incinerator door requires one of 2 accesses: 20 (access_captain) or 58 (access_hos)
that seems fine to me, honestly.

**Comment by Viciousaurus** [comment]
The idea was that the presence of a relevant head of staff, either the HoS or the Captain, are needed to run an execution.

**Comment by PrimeDSS13** [comment]
I get the logic behind that, but I feel like it'll most likely just lead to it being used less than it deserves to be.
