### ISSUE TITLE
Power monitering in enginerering doesn't seem to be connected to anything

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27433]
(WEB REPORT BY: sguigel REMOTE: 206.221.180.138:7777)
# Revision
8b25c338ab58ef508f8004ec868595ba0f4cc45e

# Description
Power monitering in enginerering doesn't seem to be connected to anything
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Viciousaurus** [comment]
This one needs to be closed @ShiftyRail

**Comment by DeityLink** [comment]
Fixed by #27438
