### ISSUE TITLE
[Sprite Request] Redo white cable wires to have improved contrast

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2743]
![image](https://cloud.githubusercontent.com/assets/8550416/5994435/0389acc2-aa41-11e4-99a4-8d45b5903b96.png)

Feels petty to ask for this to be changed but it's something thats bugged me and others for a long while.  The white cable wires have very poor contrast on catwalks and in general.  It's harder to make out detail (notice the knots are discernable with other cable colors more easily) and has a pretty big eye strain factor when you're trying to look at an entire solar wired with white cables.  Could someone do some shading or make the white a little more off-white, or find some solution to improve its visibility?  It stands out as the only wire color that's a major pain in the ass and I think we can fix that, even if it's not a game breaking bug.

**Comment by Riukanojutsu** [comment]
At this point I dont think anyone would.mind it they were simply removed. It would be simpler and we already have tons of other colors anyways

**Comment by Probe1** [comment]
yeah you could just comment it out and save a lot of work.
