### ISSUE TITLE
borer monkeys can't vent crawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27447]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
030df69fea7c8ecd70924c0451b3954b62d1ff55

# Description
borer monkeys seem to always have something equipped, even when naked and empty-handed, and thus cannot enter vents.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
Similar thing happens with mice spiderbots.
