### ISSUE TITLE
Mutated fruit can be invisible

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#27442]
#### Steps to reproduce
>Basically, order exotic seeds from cargo. Grow plants. Each plant has different fruit sprite. I.e. you can get plant that grows and looks like death nettle, its fruits are death nettle sprite, but actually they are silver pear. There is a chance a plant will have fruit of avocado half. If that happens - it's invisible.

**Comment by Zth--** [comment]
Seems to only happen with avocado halves
