### ISSUE TITLE
Synergy General Feedback Thread

### ISSUE THREAD

**Issue by beesil** [d3athrow/vgstation13#27440]
For compiling all the small/design feedback that doesn't need its own issue report into a thread. Here's the stuff I've noticed:

- Not enough o2 lockers in the halls.
- Dead end maint in a couple of spots, notably above and below engineering, on right side of science and medbay.
- Maint plant room could use a window, they're not getting enough sun!
- Service department backroom is a cool idea, but the room itself is WAY bigger than it needs to be.
- Library could use more room dressings, feels bare (carpets, desk lights, etc).

**Comment by BomberBro** [comment]
might just be blind but I couldn't find a holomap

**Comment by Viciousaurus** [comment]
> might just be blind but I couldn't find a holomap

There are at least 4 holomaps but they are not particularly well signaled

**Comment by DamianX** [comment]
megathreads dumb
