### ISSUE TITLE
Horsemasked / drunk has no effect when talking over the radio [saycode]

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#2745]
If you are horsemasked and speak over the radio you speak correctly, the same is true if you are drunk. 

To test: 
Step 1 - Get Drunk
Step 2 - Speak in local, observe how your speech is slurred
Step 3 - Speak over the radio via your headset, speech is slurred no more

Alternatively:
Step 1 - Get horsed 
Step 2 - Neigh in local
Step 3 - Speak over the radio via your headset, no more neighing.

**Comment by Probe1** [comment]
Well that's downright weird cause I've absolutely heard NEIIIGH and drunk-text over the radio as recently as yesterday.  I wonder what skeletons in saycodes closet are causing this

**Comment by Arthurdentist** [comment]
If you speak using an intercom then what you say is altered. If you speak into your headset IE 'say ; wizzard is griffing me halp' then it comes out normal.

**Comment by Probe1** [comment]
You've got it, that must have been it they were using intercomms.
