### ISSUE TITLE
Invisible security armor?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27454]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
9d2306b18d36893b85600b275dd4975ac03f9e98

# Description
I spawned in as a secoff on box and seemed to have no security armor. Instead I was wearing an invisible item labeled "Suit". I also had green text hovering by my sprite that said "vit" or something

# Steps to Reproduce

idk lol

# What you Expected
armor

# What Actually Happened
not armor

**Comment by Dacendeth** [comment]
Sec is spawning with /obj/item/clothing/suit/armor instead of /obj/item/clothing/suit/armor/vest/security
