### ISSUE TITLE
Incorrect starting loadouts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27455]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
9d2306b18d36893b85600b275dd4975ac03f9e98

# Description
Joined round as salvage broker. Spawned with assistant pressure suit, human breath mask, and without salvage telepad kit or crate sender

# Steps to Reproduce
Join game as salvage broker role

# What you Expected
correct loadout

# What Actually Happened
c*ders

**Comment by Dacendeth** [comment]
I didnt get my trader coin/thermos/donk pockets either.

**Comment by PrimeDSS13** [comment]
also I think the trader wallet starts empty now?
