### ISSUE TITLE
Missing biohazard shutters, no metal/plasteel in EVA on Synergy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27462]
(WEB REPORT BY: archinist REMOTE: 206.221.180.138:7777)
# Revision
8b069e4c8cb64a0b5cc6085c9fa79572b10e21d1

# Description;

There's no metal/plasteel in EVA (near robotics) on the Synergy map. 

There's also no firelockers in the science airlock, meaning you can't make RIPLEY FIREFIGHTERS without maint delving.

There's also a few biohazard shutters missing, according to the other maps there should be a shutter blocking the front door and desk, but there isn't.

Also, there aren't any spare toolbelts in RnD like there are on other maps..

# Steps to Reproduce: Load the map Synergy, look around.

**Comment by Viciousaurus** [comment]
There are currently 2 toolbelts in R&D and 1 in robotics
I'll adress the other issues
