### ISSUE TITLE
No internals box in synergy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27465]
(WEB REPORT BY: buffengineering REMOTE: 206.221.180.138:7777)
# Revision
a51e7445cc73f2ab058160f714486502d8d4f16a

# Description
Spawned without that little box that has a bandage and internals 
# Steps to Reproduce
Ready up at the start of the round
# What you Expected
Box
# What Actually Happened
No box

**Comment by BuffEngineering** [comment]
Forgot to mention, but I was an atmos tech.
