### ISSUE TITLE
You can see it's going to be Ninja because the borg in the den gets linked to the station's cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27477]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
9f7d3c853fb42c811b6216960e52ddb21c3e5037

# Description

See title
Shame on whomever didn't report it

**Comment by DamianX** [comment]
Shame on whomever didn't check for duplicates such as #26065
