### ISSUE TITLE
Synergy: The armory is missing like half the usual shit

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#27471]
no proper riot gear
batons with no batteries
what the fug man :DDDD

**Comment by Viciousaurus** [comment]
Can you elaborate?
There's x2:
Riot Suit
Riot Helmet
Riot shield
stun baton 
balaclava

what's missing?

**Comment by 9percents** [comment]
I didn't see holsters, bandoliers and swat gloves
not sure about holsters and bandoliers, but I doubt everyone took them before me

**Comment by SonixApache** [comment]
Uhhhhh maybe we got bullshitted on this one, lemme check the actual map file.

**Comment by Viciousaurus** [comment]
> I didn't see holsters, bandoliers and swat gloves
> not sure about holsters and bandoliers, but I doubt everyone took them before me

adding them right now

**Comment by SonixApache** [comment]
Yeah the riot gear got stolen so that's just a bad report.
Replace the 
`/obj/item/weapon/melee/baton`
with
`/obj/item/weapon/melee/baton/loaded`
and you should be set.

Personally, I feel the armory seems a bit tight, would be nice if we had a little more room. Box armory is essentially the gold standard. But it's not a dealbreaker.
