### ISSUE TITLE
Xenomorphs are weird now.

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#27474]
#### Description of issue

They go vertical. They can crawl. Their dexterity checks are weird.
Something's really really fucked with them.
I for one think it's related to outfit datums, though I could be wrong.

#### Server revision

4e6cf2dc11d39f701611cdc69bb8cc934ec48986

**Comment by DeityLink** [comment]
Xenomorphs should fail all dexterity checks according to the code, since it's related to their has_fine_manipulation var which is always at 0 except for an non-compiled subtype.
