### ISSUE TITLE
secHUD question mark icons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27479]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
9f7d3c853fb42c811b6216960e52ddb21c3e5037

# Description
I have noticed that a number of jobs have [?] icons on the secHUD now for some reason. Namely the librarian/journo and mechanics. I am not sure if this is only alt titles or what.

# Steps to Reproduce
1. wear sechuds
2. look at people

# What you Expected
journo/mechanic icons

# What Actually Happened
[?]

**Comment by APCUnlocked** [comment]
Some other jobs have also been subjected to this, I've seen scientists and bartenders with a ? even if their ID's are valid.

**Comment by SonixApache** [comment]
also chefs
definitely an outfit datums thing

@ShiftyRail
