### ISSUE TITLE
Ei Nath and hardsuit helmets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27485]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
d7f6c4dd11d37a5ea97b7d8f3454f0f75a07ff09

# Description
Engineering hardsuit helmet got stuck on my head

# Steps to Reproduce
1. Ei nath someone in an engineering hardsuit
2. Put their helmet on
3. try to take the helmet off
4. ????
5. Polyacid yourself in the face several times

# What you Expected
that the helmet would come off

# What Actually Happened
the helmet had to be pacid'd'd off

**Comment by DeityLink** [comment]
Looks like rig helmets can be removed just fine even if you're not wearing a rigsuit.
