### ISSUE TITLE
Hitting a blob with a fireball causes infinite explosions and lags the game to death

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#27498]
Good thing blob and wizard will never fire together, r-right?

**Comment by kernikov** [comment]
Shows you right for fighting each other instead of shitting on the crew that didn't get ant*g.

**Comment by Exxion** [comment]
It also on very rare occasions does this when it hits something other than blob, and I have never been able to figure out why
But if it consistently happens with blob it should be fairly easy to diagnose

**Comment by Exxion** [comment]
Projectiles are wacky
Removing the manual `to_bump()` call from `blob/Cross()` *should* fix this but I still feel like something deeper is wrong here

**Comment by Zth--** [comment]
Can someone confirm if this still happens? It shouldn't happen anymore as of #27640

**Comment by Exxion** [comment]
It does seem to be fixed
