### ISSUE TITLE
synergy bartender beanbags

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27496]
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
6632d747845396693ffde20ee0624951ba76b23d

# Description
roundstart bartender seemingly starts with only 1 spare beanbag slug versus the usual 4
# Steps to Reproduce
start round as bartender
# What you Expected
have some beanbags to fill a bandolier and put down shitters
# What Actually Happened
oh god there's only one extra for a gun that shoots two bullet

**Comment by Viciousaurus** [comment]
This is not a map related bug I think.

**Comment by cloutcode** [comment]
this isn't a mapping thing, this happens on other maps too, this is probably an outfit datums thing
