### ISSUE TITLE
Can't buy fireball after firebreath, can do the reverse.

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#27504]
#### Description of issue
Wizards can't buy fireball after firebreath, it says you already know the spell. You can however do the reverse.
Firebreath is a child of fireball so that's definitely the reason.

#### Steps to reproduce
Try to be a sweet pyromancer
Buy firebreath then fireball
Not a sweet pyromancer
Hit refund and do it in reverse
Be a sweet pyromancer

**Comment by SonixApache** [comment]
dupe of #26961, #22200, #17346
