### ISSUE TITLE
Pitbulls and Arcane Golems fight each other

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27508]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
3bb9b5316d9d8d35158c9cb1d3167886c2570bd7
# What you Expected
Six thousand pitbulls
# What Actually Happened
Captain's Quarters turned into a dogfighting ring.

**Comment by kernikov** [comment]
Duplicate of #26736

**Comment by DeityLink** [comment]
Duplicate of #26736
