### ISSUE TITLE
No newscaster in cargo on synergy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27512]
(WEB REPORT BY: sguigel REMOTE: 206.221.180.138:7777)
# Revision
3bb9b5316d9d8d35158c9cb1d3167886c2570bd7

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Viciousaurus** [comment]
I think is funny this was reported but not that there's no RC in cargo
