### ISSUE TITLE
Synergy doesn't seem to start with flashes in robotics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27545]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
b1466135194e9716b8efae9002936c34713fd058

# Description
Synergy doesn't seem to start with flashes in robotics
# Steps to Reproduce
Play synergy
# What you Expected
Flashes in robotics
# What Actually Happened
None

Either that or people consistently every single round steal them within a minute of starting

**Comment by PrimeDSS13** [comment]
I don't think there's a flash on the bridge roundstart either, oh my!

**Comment by Viciousaurus** [comment]
There's two flashes in robotics at roundstart.
However, there aren't any flashes in the Bridge
