### ISSUE TITLE
Ai tracking Voice Changer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27542]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
b1466135194e9716b8efae9002936c34713fd058

# Description
Seems when ai trys to track a person that has used the voice changer it gives the ai the name of the person instead of just saying can't find the madeup individual
# Steps to Reproduce
Track someone that is using a voice changer as ai.
# What you Expected
Just to get a negative message
# What Actually Happened
Gives the ai the persons actual name.

**Comment by toomykins** [comment]
apparently this is a feature
admins explained it as being a visual thing.
If you don't want to be spotted on camera talking into a device that makes your voice strange on radio, then don't be spotted on camera doing it.

**Comment by dunsel-hordon** [comment]
no the person was spotted while off cameras. It said something along the lines of can't track player so and so when the ai tried to track the voice changed message
