### ISSUE TITLE
Cultists can dance, move and spin while stunned

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27557]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
d5e7eddcca93d7611800267adbb8cf6a41cb8806

# Description
I was being sacrificed at altar. Fellow sec stunned a cultist. I thought I was saved. Cultist continued to spin and dance around altar and successfully sacrificed me, raising a blood stone.
# Steps to Reproduce
Stun a dancing cultist
# What you Expected
Stuns to be viable at stopping unholy rituals and to be saved from a terrible fate
# What Actually Happened
Cultist successfully sacrificed me by rolling around altar while screaming in pain and twitching on floor.

**Comment by DeityLink** [comment]
That's completely unintended but that's hilarious.

**Comment by dunsel-hordon** [comment]
no it works as intended. You can't merely stop the POWERFUL BLOOD MAGICS with a stun. You must separate the cultist and his magic.
