### ISSUE TITLE
Fat Jutsu

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#27550]
If you join as a fat ninja, `equip_ninja` uses equip or del so it deletes the suit, and since the sword goes in the suit storage, it deletes that too

**Comment by boy2mantwicethefam** [comment]
https://en.wikipedia.org/wiki/Beverly_Hills_Ninja

**Comment by Substance455** [comment]
Have fat ninja's become Sumo Wrestlers.
