### ISSUE TITLE
Broken name and icon for replicated xenoarch jar 

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#27568]
Scanning the red jars from xenoarch lets mechanics print these nothings. 
![itcontainsnothing](https://user-images.githubusercontent.com/64218965/90327273-debc7000-df5f-11ea-87f7-ad7796851379.png)

I'd give the proper name but they're also sometimes named nothing. 
![nothing](https://user-images.githubusercontent.com/64218965/90327274-e11eca00-df5f-11ea-9fb3-4258bb884dfa.png)

**Comment by DeityLink** [comment]
Should have been fixed by #27723
