### ISSUE TITLE
[Bug] Player took the identity of a monkey after having head attached to humanized monkey body.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2757]
It'd be easier to describe what happened than whats wrong.  An engineer was killed by an AME explosion and their head was recovered but body was gibbed.  I genetically altered a monkey into a human, decapitated it, and attached the engineers head.  Then I stuck the engineer in the cloner.  Instead of the engineers name or the humanized monkeys name, the cloners records said "monkey (417)".  I cloned the engineer succcessfully, and put them in cryo and back to full health successfully, but their new identity was monkey (147).  Their brain was never removed from their head (but heads were swapped with a humanized monkey).

It could potentially be related to https://github.com/d3athrow/vgstation13/pull/2732

**Comment by DeityLink** [comment]
nope, not related to #2732 at all.
The issue is that the identity of a human in SS13 is actually kept in their body (their heart) rather than in their head. This probably requires a surgery edit so when attaching a head the body takes the identity of the head.

**Comment by Probe1** [comment]
Weird, I've attached heads to humanized bodies before but not gotten this result.

**Comment by clusterfack** [comment]
^see above

**Comment by Probe1** [comment]
THANK YOU
