### ISSUE TITLE
Synergy Secure Armory Air Alarm is on ground

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27577]
(WEB REPORT BY: theophrastus REMOTE: 206.221.180.138:7777)
# Revision
6088c4cee9d356ca11d81d98d584e448fbe07074

# Description
The Air Alarm in the Secure Armory on Synergy is not mounted on the wall, but instead on the floor under the security armor rack

# Steps to Reproduce
walk into the armory and look under the armor rack

# What you Expected
it to be mounted to the wall
# What Actually Happened
it wasnt

**Comment by DamianX** [comment]
Fixed at some point
