### ISSUE TITLE
Editing the ban reason using the unban panel gives a MySQL error.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27595]
(WEB REPORT BY: meetmeindorms REMOTE: 206.221.180.138:7777)
# Revision
ca0a5fc03b7320dbb3c1b0bd0fe33c29225796f6

# Description
I tried editing the ban reason of someone's ban in the unban-panel.
# Steps to Reproduce
1. Open up the unban-panel.
2. Look a ban up.
3. Edit the reason.

# What you Expected
An edited reason.

# What Actually Happened
```
ADMIN LOG: Error: MySqlError { ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' edits = CONCAT(edits,?) WHERE id = ?' at line 1 }
```

**Comment by DamianX** [comment]
fixed
