### ISSUE TITLE
AI Holograms triggering proximity detectors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27599]
(WEB REPORT BY: kirbythewizard101 REMOTE: 206.221.180.138:7777)
# Revision
da15a18e44ec33aa491cf92a0ab25dccb1d76331

# Description
As an AI my hologram went over a proximity detector / sensor and triggered it.
# Steps to Reproduce
Use an AI holopad and go past an active proximity sensor
# What you Expected
For it not to trigger it
# What Actually Happened
It did.

**Comment by Exxion** [comment]
I'm gonna say unironically feature
