### ISSUE TITLE
Synergy coin-less QM

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#27590]
I believe every other map has at minimum one coin spawning in the QM's office for ~~MoMMIs to steal~~ giving the miners some toys.
[consistency]

**Comment by SonixApache** [comment]
synergy has coin mint boards in maint, though

**Comment by DamianX** [comment]
Three silver coins are in the QM's locker.

**Comment by jwhitak** [comment]
Synergy has the coins in the locker. The only map that lacks coins completely is MetaClub.
