### ISSUE TITLE
fire extinguisher cabinet wacky

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27591]
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
ca0a5fc03b7320dbb3c1b0bd0fe33c29225796f6

# Description
fire extinguisher cabinets do not return metal when removed from walls, they also dont deploy onto walls when made with metal sheets and applied in hand 
# Steps to Reproduce
attempt to weld cabinet off wall and make a new one and put it on another wall
# What you Expected
cabinet go on wall
# What Actually Happened
cabinet deploys onto the floor and makes you look like a fucking fool

**Comment by DeityLink** [comment]
Partially fixed by #30203
Needs to return metal as well
