### ISSUE TITLE
RPD's missing from atmos lockers in Synergy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27607]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
66020c8ccbf9b00525b0084e06d3d5b04c3f2837

# Description
No RPD's can be found in atmospherics lockers in synergy
# Steps to Reproduce
Go to atmos, open locker, despair
# What you Expected
Pipes mufugga
# What Actually Happened
No pipes today bitch

**Comment by DamianX** [comment]
Atmos tech lockers do in fact contain RPDs by default, dunno what this is about.
