### ISSUE TITLE
late join plasmaman mechanic spawned without suit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27610]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
66020c8ccbf9b00525b0084e06d3d5b04c3f2837

# Description
late join plasmaman mechanic spawned without suit
# Steps to Reproduce
play plasmaman mechanic late join
# What you Expected
to spawn with a suit
# What Actually Happened
spawned without suit

**Comment by DamianX** [comment]
fixed
