### ISSUE TITLE
Priority Voxsec Gets Gassed on Arrival

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#27611]
#### Description of issue
I latejoined as a vox security officer. Security officer was on high priority, which means you get free items, such as a taser on your suit slot. I did get a taser on my suit slot, I also got gassed immediately, because this taser ended up putting my N2 tank inside my backpack.

#### Difference between expected and actual behavior
N2 tank should be in the suit slot and the taser in the backpack, not the reverse.

#### Steps to reproduce
>Set security officers to priority
>Latejoin as voxsec

#### Length of time in which bug has been known to occur

I bet YOU did this https://github.com/vgstation-coders/vgstation13/pull/27340

**Comment by Kharkov72** [comment]
feature

**Comment by ShiftyRail** [comment]
FUCK vox tbh

**Comment by mrflarg** [comment]
good feature
