### ISSUE TITLE
Feature Request: Killdozer modkit

### ISSUE THREAD

**Issue by virus533** [d3athrow/vgstation13#27615]
### What is it?
Killdozer modkit is an item that turns civilian mechs (Ripley, Firefighter Ripley, Odysseus, Clarke) into low cost and stealthy combat mechs
### How does it work?
Inserting a modkit into a mech under maintenance (like batteries or tracking beacons) enables it to use mounted weapons. Visually, the mech sprite is not changed, but if inspected, you can tell the mech has been tampered with (ie. "There are some odd pieces of equipment on this mech" after examining it). However, they also keep the same armor of the civilian models, and are easily taken down by proper combat mechs or weapons.
### Acquiring and using the modkit
Modkits can either be ordered via Syndicate PDA or manufactured after science has done some illegal research. Before using the modkit, it needs a weapons board, similar to how a plasma cutter needs a diamond mining drill (or is it kinetic accelerator) to be completed. Killdozer mechs allow a syndicate agent to make an inconspicuous combat mech that will not raise any eyebrows till its true purpose is revealed. They can also be used as extremely low cost combat mechs when shit hits the fan, like blob or xeno, to quickly get heavy support to the crew

**Comment by pedr69** [comment]
fund it
