### ISSUE TITLE
Science's trash can on Horizon still spits out garbage for no reason

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27622]
(WEB REPORT BY: koshachyamyata REMOTE: 206.221.180.138:7777)
# Revision
7c7a5072a86309c321aa725b389f8bff79daad25

# Description
Horizon's main science hall still spits out trash and says got mail even without cargo sending anything
# Steps to Reproduce
Throw trash on horizon away and watch as science becomes garbage central
# What you Expected
A nice clean lab
# What Actually Happened
Science is the ships landfill

**Comment by kernikov** [comment]
RD's disposal junction needs to be flipped from W <- E with a north split, to W -> E with a north split.
That said, a bunch of the pipes are fucked OR it's presistant gunk I see.
