### ISSUE TITLE
Synerge Research Shuttle has no wire connecting to it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27623]
(WEB REPORT BY: koshachyamyata REMOTE: 206.221.180.138:7777)
# Revision
7c7a5072a86309c321aa725b389f8bff79daad25

# Description
The Research Shuttle Dock has a reinforced window that has a scrubber pipe but no wire in it so the apc never gets power unless someone fixes it themself
# Steps to Reproduce
Go to the research dock on synergy and bask
# What you Expected
The niggerwattz to go to the sea
# What Actually Happened
dark dockyard

**Comment by DeityLink** [comment]
Seems like it was fixed at some point.
