### ISSUE TITLE
lightspeed ship/kessel/whiteship

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27627]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
d6b20e81c042c99a38196b3c7d61206d420c609f

# Description
Wires disappear when the ship moves
# Steps to Reproduce
I added a wire from the AME to the APC
# What you Expected

# What Actually Happened

**Comment by gurfan** [comment]
oh god
