### ISSUE TITLE
[Saycode?] The AI will speak over the intercom despite using :h if using a holopad that has sight of the AI core

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2762]
Thankfully I did not discover this while talking to a subverter

**Comment by ComicIronic** [comment]
So if the blast door is closed but the hologram is in range, it'll work normally?

**Comment by Konater** [comment]
At least that's what I recall, I'll need to test and confirm it next time I play AI sorry. I also think that you can't hear or talk to people with a wall between you and the holopad but I'll need to try and recreate that one too.
The talking over intercom part is all I'm sure of at the moment

**Comment by d3athrow** [comment]
Looking like this is intended behavior as it uses send_speech with the holopad as the 'source' but i can override it i suppose.
