### ISSUE TITLE
Synergy mapping issues

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#27633]
Xenoarch anomaly scanner pad has an overlapped light fixture that is always scanned over your artifact, forcing you to disassemble it. 
![image](https://user-images.githubusercontent.com/5549060/91091520-4d629300-e61c-11ea-93fc-52166a7630a8.png)

No south-side r-windows under the Bar sign (two missing)
![image](https://user-images.githubusercontent.com/5549060/91091735-a7635880-e61c-11ea-9e5c-b4a3a490c1ff.png)

All MULE delivery points with a windoor between flaps and the delivery point cause the crate to be dropped before the windoor as the MULE dumps without opening it.
Ex. Janny's closet 
![image](https://user-images.githubusercontent.com/5549060/91092194-45572300-e61d-11ea-8397-23309269224d.png)

**Comment by 9percents** [comment]
also, missing sinks in chemistry, surgery and virology

**Comment by kernikov** [comment]
Several escape pods need shuttlewalls under the thrusters, which by themselves are not airtight apparently.
Examples I found were Arrivals and Science Escape Pods.
![image](https://user-images.githubusercontent.com/5549060/91092514-bd254d80-e61d-11ea-857f-41107fcece23.png)

Detective's TV style is an entertainment console, instead of security cameras.

The maintenance connecting Robotics, R&D, chapel, spacepod bay, etc. is one big fucking hall with zero partitioning, leading Robotics and R&D maint being vented if someone welderbombs by atmos.
![image](https://user-images.githubusercontent.com/5549060/91093921-b697d580-e61f-11ea-8bfe-7f79bb6f8b11.png)

**Comment by kernikov** [comment]
@Viciousaurus

**Comment by DamianX** [comment]
The missing windows in the bar are arguably a feature. If there were windows there you wouldn't be able to change the bar sign.
MULE tracking beacons seem to be mapped like this elsewhere as well.
This issue is unatomic and I really hate it.
