### ISSUE TITLE
Detective Handheld TV Not Detecting Camera Bugs

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#27634]
#### Description of issue
This was on Synergy Station. The detective's handheld TV is not registering camera bugs that have been tagged with an ID. A message shows up as "No camera bugs found.", despite having active bugs.

#### Difference between expected and actual behavior
I expect you to be able to see the cameras that you have tagged once you use the TV, the actual behavior is that the TV doesn't show the cameras.

#### Steps to reproduce
>Be on Synergy station
>Set camera bug ID
>Use handheld TV

**Comment by Eneocho** [comment]
Can't reproduce. Works fine.
