### ISSUE TITLE
Darkmode service channel color is the same as common

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27651]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
bef81d7aae4331e924bd6e93041e3c10170a8230

# Description
Darkmode service channel color is the same as common
# Steps to Reproduce
1. join as service job
2. use :d prefix
3.observe color
# What you Expected
a slightly darker yellow-y or at least different color
# What Actually Happened
same color as common

**Comment by wotisjanitor** [comment]
NOTE: Supply has the same problem. Color should be brown.
