### ISSUE TITLE
mutated fruit can be invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27654]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Steps to Reproduce
Basically, order exotic seeds from cargo. Grow plants. Each plant has different fruit sprite. I.e. you can get plant that grows and looks like death nettle, its fruits are death nettle sprite, but actually they are silver pear. There is a chance a plant will have mustard flower sprite. If that happens - it's invisible.

**Comment by Kurfursten** [comment]
This happened again with strange diona nodes

because produce is supposed to use the produce icon_state, but dionanodes.dmi lacks one, it was invisible
