### ISSUE TITLE
Toggling the FAT gene doesnt actually make someone fat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27660]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
34b7e27544426513a953120e983ab3f27913f9c5

# Description
says on tin
# Steps to Reproduce
Toggle FAT gene on admin panel
# What you Expected
epic pwn dumb ablinos
# What Actually Happened
nothing

**Comment by boy2mantwicethefam** [comment]
owned
