### ISSUE TITLE
You lose the absorb spell spell on cloning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27675]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
6aae6aca47c4764a1e6efaf6b0c433e3aabc6c56

# Description
Cloned, kept my other two spells but lost the absorb spell gained from "summon spells".

**Comment by jwhitak** [comment]
Adding that it's not just the absorb spell. Certain other spells seem to be lost by cloning as well. In a recent game for me, being cloned caused me to lose the Fist spell.

**Comment by DeityLink** [comment]
Grouped up in #30360
