### ISSUE TITLE
Wizard is really fucking bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27683]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
675f30e1f710ce4e2ecc5804dda3c67d2990a143

# Description
A wizard currently has some weird properties:
- immunity to electrodes (tazer stuns)
- no need to breathe
- spaceproof 
- ZAS proof apparently as well
- can't use machines, not even PDA's (you lack the dexterity to do this)
- Might be just me but I always get fat even if I eat only two donuts all shift

# Steps to Reproduce
roll wiz on verygaystation 13
# What you Expected
hulk and spaceproof not being free features
# What Actually Happened
owned everybody by fisting them because oxygen+stuns weren't an issue

**Comment by GreatBigFailure** [comment]
Is this consistent or just something that happens randomly? Is it new? Could it be a specific spell/potion doing it?

**Comment by Zth--** [comment]
what spells did you buy

**Comment by Zth--** [comment]
I'm confident #27688 fixed it. If not please make another issue.
