### ISSUE TITLE
The Walking Dead (Mushroom)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27689]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
7583d5e8c4c8a9cc8112f584bda66bbd0e5bc9ab

# Description

During a bout of alcohol induced boredom I performed science, and elected to left click a flaming walking mushroom to see if I could truly take science too far.  It turns out yes you can.

# Steps to Reproduce

Clickjoin a dead mushroom (possibly also works with dionas), say yes to the prompt, go from being a dead player... to being a dead mushroom.
# What you Expected

Honestly, I dont know what I expected
# What Actually Happened

Double Death

**Comment by DeityLink** [comment]
I mean, looks like it's working as intended to me. not sure what you expected.

**Comment by SonixApache** [comment]
@DeityLink being able to inhabit the dead is a really bad feature, it locks you out of your old body, resets certain post-death cooldowns, etc. Can't revive the little buggers either far as I'm aware.
Should re-tag this as feature request and fix it by making it impossible to inhabit dead mobs.
