### ISSUE TITLE
synergy engineering oversights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27680]
(WEB REPORT BY: locese REMOTE: 206.221.180.138:7777)
# Revision
6aae6aca47c4764a1e6efaf6b0c433e3aabc6c56

# Description
synergy engineering still lacks some things, namely matter for the RCD for CE, an actual shard in the shard box and fire alarm in supermatter engine room
# Steps to Reproduce
play synergy
# What you Expected
to have this things there
# What Actually Happened
they aren't there

**Comment by kernikov** [comment]
I'm fairly certain the shardbox meme is intentional.
