### ISSUE TITLE
something is fucked with midround ops and it is shiftys fault

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#27700]
Midround operatives is screwed up in a bunch of ways.

Ballistics guys spawn with three berettas.
Sometimes a leader doesn't appear.
Sometimes the leader gets split up somehow: one guy had the leader icon and gets to pick the names, another guy had the nuke code, go loud button, and hardsuit kit
The radios that the ops wore werent syndicate ones so the operatives all talked into the common radio channel.

**Comment by ShiftyRail** [comment]
I can fix the things related to outfits, but the leader might be something else, or something special that round.
