### ISSUE TITLE
Traitor codeword generation can include a blank codeword, and if it does, all traitors are deaf

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#27712]
At least that's what I *think* is happening. I see that there is a blank codeword, and I see that all traitors are deaf (or rather the messages they receive are invisible), and I assume this is because codeword highlighting is breaking on the blank codeword.
I do not know how a blank codeword is getting in there. I checked the lists it picks from and did not see any nulls/empty strings, but maybe I missed them.

Loose because, while it's an extremely rare issue, when it happens it's very bad

**Comment by DeityLink** [comment]
*wheeeeze*

**Comment by Theophrastus1** [comment]
eldritch codewords
