### ISSUE TITLE
New sec uniforms aren't aesthetic

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27714]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
d888aa9714e78fb1bd1d99d7922558b79809fef7

# Description

They rendered well in pictures, in game it's very bad

The little hair you were seeing from the  helmet, humanising the officer, is gone

The new armour is bad and way too bulky at the shoulders

The belt is way too thick too

I'm sorry but this isn't cutting it

**Comment by gurfan** [comment]
sec officers were never human

**Comment by SonixApache** [comment]
needless sprite changes were a mistake

**Comment by Kurfursten** [comment]
Give back old flare gun too

**Comment by mrflarg** [comment]
they never were.
