### ISSUE TITLE
Walk at Full Speed While Sprite Horizontal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27721]
(WEB REPORT BY: flubby REMOTE: 206.221.180.138:7777)
# Revision
2b8839b8465701e73d74737e2aef0a2e6edbde36

# Description
Being time stopped and then ZASed will lead to being able to move at full speed while sprite is horizontal.
# Steps to Reproduce
Activate a time stop artifact immidiately after opening an exterior airlock. Move with a downed character sprite at full speed.
# What you Expected
Stand back up after time stop wears off.
# What Actually Happened
Did not stand back up after time stop wore off.

**Comment by kilozombie** [comment]
Finally, a chance to self-promote
https://www.youtube.com/watch?v=_2lVPyn5SAE

**Comment by DeityLink** [comment]
Fixed by #30069
