### ISSUE TITLE
Horse Mask lets you speak over radio.

### ISSUE THREAD

**Issue by Senaat1** [d3athrow/vgstation13#2773]
When horsemasked you can speak normally over radio, even though your speech still shows up as NEEIIGGHH or HAAAAAW

**Comment by ComicIronic** [comment]
Duplicate, please check before making issues.

**Comment by d3athrow** [comment]
Just confirmed that I did fix it with !(HAWW)[http://puu.sh/fsj2R/57877e1194.png] https://github.com/d3athrow/vgstation13/commit/e8687523a634386c8a1eb0477a848563b0861fd5
