### ISSUE TITLE
Huggers are dumb and make an otherwise fun gamemode not so fun

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27740]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
2d0871dc033ff26282e70252c62016cd395dbac9

# Description

See title
If I'm wearing a mask, it should take at least one or two huggers to remove it, not have it be done first try

No, I'm not coding it because I died to it

**Comment by Kharkov72** [comment]
just ward their jungle

**Comment by Dacendeth** [comment]
just wear a hardsuit and instantly redeploy magic helmet to be immune to huggers.

**Comment by ShiftyRail** [comment]
>just wear a hardsuit and instantly redeploy magic helmet to be immune to huggers.

why not make huggers less retarded instead

**Comment by Exxion** [comment]
Have you considered just walking away from them

**Comment by west3436** [comment]
Low quality issue report
