### ISSUE TITLE
NanoUI not working.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27749]
(WEB REPORT BY: tetrako REMOTE: 206.221.180.138:7777)
# Revision
5febbc6e9b87e5dcbfbd81f3472d91265343fd85

# Description
Nano UI's no longer functioning, can't do shit involving them. Other UIs work for a time then they disappear too.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by toomykins** [comment]
i wonder if this person tried to click the "close nano-ui" verb or not

**Comment by robintime** [comment]
#27755 is a more descriptive duplicate by the same person
