### ISSUE TITLE
Something is wrong with being a ghost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27758]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
091781e69ab3bdadb77a2caa61d724e6e197724e

# Description
- Start game as observer
-Can't zoom in or out, view just bugs out and keeps me at the same zoom level
-Also drops my FPS to like 2 constantly, the entire byond window lags like fuck, even writing this bugreport is a powerpoint
# Steps to Reproduce
join game
# What you Expected
to be able to see
# What Actually Happened
everything went to shot

**Comment by Exxion** [comment]
Works On My Machine

**Comment by Kammerjunk** [comment]
stretch to fit

**Comment by APCUnlocked** [comment]
Stretch to fit fixed everything, thanks Damian, this can be closed or whatever
