### ISSUE TITLE
Roles and "No Backpack" preference

### ISSUE THREAD

**Issue by strawberrytan** [d3athrow/vgstation13#27767]
#### Description of issue
There are problems with how the game handles inventory when you select "No backpack" as your backpack preference in certain jobs and circumstances

#### Difference between expected and actual behavior
I signed up as a high priority request medical doctor with no backpack. Usually, this means I come aboard holding the first aid kit that medical doctors start with.

Instead, I spawned in holding an emergency internals box in one hand, and a medibelt in the other. Everything else was nullspaced as far as I'm aware, because there was nothing on the floor.

#### Steps to reproduce
1. Have preference for no backpack.
2. Join as a role that gets more than one item on join.

#### Specific information for locating

<oversight>

#### Length of time in which bug has been known to occur

I assume outfit datums

**Comment by ShiftyRail** [comment]
The bug here is that they're nullspaced.
