### ISSUE TITLE
No Music with VLC mode.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27775]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
825664fb0c001e2630683335db9dc7dd26320d67

# Description
VLC x32 stopped playing the juke music.
# Steps to Reproduce
Change sound mode to VLC x32 on the latest VLC version.
# What you Expected
Sound, music, etc.
# What Actually Happened
Silence.

**Comment by ShiftyRail** [comment]
Need more context, because it works fine on my end, locally and on live.

**Comment by west3436** [comment]
his ass did NOT provide more information
