### ISSUE TITLE
[Balance Issue] More plastic

### ISSUE THREAD

**Issue by Riukanojutsu** [d3athrow/vgstation13#2777]
We definitely need a new way to get plastic for mechanics or make them spawn with more plastic or make everything cost less plastic. Shit is a nightmare.  I really like the mechanic gimmick but the plastic turns me off so much, even with an upgraded flatpack fabricator, machines cost like 3 or 4 sheets. This has to stop.

I suggest making it avaible to order in cargo the same way wood planks are oderable but its more efficient to nag a botanist for some.

**Comment by SkowronX** [comment]
Yield for mixing plasticide and polyacid is way too small.

**Comment by Riukanojutsu** [comment]
That would help but the steps are still pretty annoying to accomplish. Especially since the mechanics dont have a grinder in their office at round start.

**Comment by ComicIronic** [comment]
Whats wrong with the current system of getting plastic from Botany?

**Comment by Probe1** [comment]
Because the plastic returns on plasticicillum is very poor.  It takes something like 4 unmodified plants to  grow enough plasticicicicicicillium for 20 sheets.  Now 20 sheets goes a long way for mechanics, but its also one of the more intensive things to have to grow.  

Honestly months ago  I said it should be orderable from cargo but now I kind of like it only being a manufacturable thing.  The problem is it sucks for botany and should give more plasticisillyyum per plant.

**Comment by Riukanojutsu** [comment]
20 sheets is eh
if you are a shit mechanics it can last you the round but you wont be able to build a lot of stuff with that

**Comment by ComicIronic** [comment]
Plastic shortage is meant to control Mechanics production. 

Other than that, I'll increase plant yields slightly.

**Comment by Probe1** [comment]
@ComicIronic do it -very- slightly.  it doesn't need much, just making it a little less painful for botanists to care would do it.

**Comment by SkowronX** [comment]
Also iirc grinders aren't scannable for assembly.

**Comment by Riukanojutsu** [comment]
that mightve been fixed though
I cant remember if it was.

**Comment by SkowronX** [comment]
If that's the case. Scan a chem dispenser, grinder, hydro tray, and a seed extractor and "borrow" some plastellium seeds. You now have everything you need to make plastic. All that's really required here is a small yield increase to amount of plastic made from a mix.

**Comment by ComicIronic** [comment]
Is production still an issue?

**Comment by Probe1** [comment]
It's pretty easy, but I wouldn't call it a pressing issue.  It's self regulated by botanists infrequently growing plasticillum.  I'd say its good.
