### ISSUE TITLE
Runechat doesn't appear for mobs in an atom's contents

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#27774]
1. put pAI in backpack
2. pAI speaks
3. speech bubble appears but not runechat

**Comment by ShiftyRail** [comment]
Intended, it's to not give away the location. You can fix it if you want, but for me, it's a feature.

**Comment by ghost** [comment]
If it's intended then I'll just close the issue, makes sense to me.

**Comment by Exxion** [comment]
Why wouldn't the location be given away? You can hear where something is coming from in reality. Also the location is already given away by the speech bubble.
