### ISSUE TITLE
DNA injectors can be used on silicons

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#27781]
how does this even happen

**Comment by SGuivenne** [comment]
Specifically, this works on AI.  I take full credit on being the psychopath to discover this.

**Comment by PrimeDSS13** [comment]
they don't actually work though, it gives you a specific message indicating that it didn't give them the powers.

**Comment by Kurfursten** [comment]
Not a bug, it gives a fail message and does not inject
