### ISSUE TITLE
Starting to build an APC in a room without one breaks all machinery

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2778]
Yeah, so if you have computers/vents/doors in a room that rely on APC power they can be run without power.

But once you start constructing an APC (i.e. laying down the frame) they all become unpowered, and they do not become repowered when the APC is completed and turned on. Even toggling the APC's power on/off doesn't cause them to become powered.

**Comment by d3athrow** [comment]
I see.
