### ISSUE TITLE
Rigsuit health display not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27794]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
5b8846b4294e8e55b1c8c0086c96c703d0c22551

# Description
Rigsuit health display (articulated spine) upgrade description:  Lets passers by read your health from a distance. It doesn't do anything, and passers by have to examine your suit.
# Steps to Reproduce
Install rigsuit health display into a rigsuit. Nothing happens.
# What you Expected
To see a healthbar above head.
# What Actually Happened
no healthbar, passerby can't tell their health.

**Comment by DrSnips** [comment]
It doesn't really work like that. Only by examining the person and then clicking on the suit can you see health info. In all fairness this method isn't really clear cut. Displaying a med hud above you globally could be interesting but might be a bit intrusive.
