### ISSUE TITLE
Forced "respawn" is not good.

### ISSUE THREAD

**Issue by Riukanojutsu** [d3athrow/vgstation13#2779]
The new system of "Respaw" is not fun, since you dont get the prompt anymore sometimes you are about to be cloned and then you become a Diona and you missed your cloning. Sometime I feel like being a diona sometime I dont and just want to observe, having to go in the options all the time is annoying and most of the time I just forget to do it, possibly taking the spot of someone else. 

Adding a "ask me each time" section to the menu could really improve this system.

**Comment by clusterfack** [comment]
Seriously put your setting on 'yes' instead of 'always', and it will give you a prompt asking if you want to be a diona in each round if one is harvested. This ISN'T a bug.

**Comment by Riukanojutsu** [comment]
The description for yes is "yes for this round". That needs clarification.

**Comment by d3athrow** [comment]
I don't understand can you explain the issue a bit better?

**Comment by Riukanojutsu** [comment]
Now I realise that the issue I had was because my preference werent setup right. I had my stuff on "always" which made me auto respawn as diona and other stuff when I actually wanted it on "yes". I checked and the desciption of "yes" is "Always yes for this round" instead of "It will asked you if you want to register".

**Comment by clusterfack** [comment]
Alright I've come to agree with you riu.

The 'always' option is shit. It just doesn't work well because it forces you into respawning and most people just turn it on always without thinking. 

Having it set to yes and then having it poll a player always for this round/yes/never for this round is the one true solution.
