### ISSUE TITLE
Pillow bugs can SMASH THOUGH WALLS

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27795]
(WEB REPORT BY: calzilla1 REMOTE: 206.221.180.138:7777)
# Revision
5b8846b4294e8e55b1c8c0086c96c703d0c22551

# Description
A pillow bug can smash though walls and tables. Real fucking fun having that happen to your department and not being able to do jack shit about it.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kharkov72** [comment]
how are pillowbugs even real just disposal them

**Comment by dunsel-hordon** [comment]
i thought this was fixed?
