### ISSUE TITLE
Can't Speak Siik'Tajr

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27802]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
be70fc2534d7c9cb3f5962b11dbc62f0d4d568b7

# Description
When trying to speak Siik'tajr as a Librarian (you get a random language as a librarian), it doesn't proc, be it using the :% key or the set default button.
# Steps to Reproduce
Learn Siik'tajr, be it from a random roundstart of adminbus.
# What you Expected
Being able to speak Siik'tajr.
# What Actually Happened
Can't speak Siik'Tajr.

**Comment by gurfan** [comment]
:% is currently the insectoid language key, this is probably the problem.

**Comment by SonixApache** [comment]
double defines haha

**Comment by ShiftyRail** [comment]
Duplicate
