### ISSUE TITLE
Vending machine keeps wallet money even if you can't afford the item with account credits included

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27803]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
be70fc2534d7c9cb3f5962b11dbc62f0d4d568b7

# Description
I was purchasing a diamond pick on a dwarven vending machine, I hadn't enough credits on my wallet, so it asked for me to use said credits AND the bank credits. It took the wallet credits (26 credits, in this case), said I hadn't enough funds and kept said credits anyway.
# Steps to Reproduce
Try and purchase something you cant afford even if you count bank money as well as wallet money. Say yes when asked to use wallet cash. Not enough money sign will appear, you lost your wallet credits.
# What you Expected
To not lose said 26 credits.
# What Actually Happened
Lost the credits, made the bug report.

**Comment by DeityLink** [comment]
Related to #30316
