### ISSUE TITLE
New Antagonist: Syndicate Blob

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#27819]
Now the blob can devour the station AND the threat!
Doubt this is intentional. Considering the death timer it's kind of a waste of the syndicate threat. Only special thing to note is that I seemed to get blob before the round started, few seconds before while it loaded in, but not before the timer hit 0.

![heresyourantaground](https://user-images.githubusercontent.com/64218965/93155477-302d5b80-f6d4-11ea-911d-7e41a42ce855.png)

**Comment by Kharkov72** [comment]
WHIRRRRRRR
NOOO MY THREAT

**Comment by gurfan** [comment]
This has also happened with wizards. I don't know why but it seems like people roll blob+another antag every fucking round.

**Comment by Irradiation** [comment]
Similar things happened before Dynamic where some people got both Changeling AND Traitor.

**Comment by Kurfursten** [comment]
Changetraitor was intended iirc

This is a Feature™ I'd say. Dump your TCs into some fast powersinks or emag+gun for creative pop positions

**Comment by DeityLink** [comment]
Absolutely hilarious, make wise use of your TCs.
