### ISSUE TITLE
Nulasers shoot through walls sometimes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27817]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
43e0569f3f08cd4e12854ff583ec8dc4c73ac7d9

# Description
new beam weapons can shoot through walls sometimes
# Steps to Reproduce
Target someone with a laser weapon on the other side of a wall by viewing them with thermals or a targettable mob (like turrets)
# What you Expected
walls to block beam weapons
# What Actually Happened
beams go right through walls unobstructed

**Comment by DeityLink** [comment]
Probably fixed by #29708

**Comment by SonixApache** [comment]
@DeityLink you linked an open issue

**Comment by DeityLink** [comment]
Thanks github auto-complete.
