### ISSUE TITLE
Got the milf Explode button as a borg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27826]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
1ac5ce9aa9e3b8c01bb04240a6485362e1ede541

# Description
Was autoborged CMO, AI won, I got the button in top right corner

# Steps to Reproduce
Be an autoborger head maybe?

# What you Expected
Not have a button

# What Actually Happened
"How did you get to this point without actually being a malfunctioning AI?"

**Comment by west3436** [comment]
This is fixed now
