### ISSUE TITLE
roboburger transformation is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27821]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
1ac5ce9aa9e3b8c01bb04240a6485362e1ede541

happened throughout multiple rounds, nothing happens when you eat one of the borgs

**Comment by DeityLink** [comment]
another old disease found to be broken, huh. I'm starting to wonder if appendicitis works at all either.

**Comment by toomykins** [comment]
roburgers have been ammended, i may have to find who did it and when, but it's a prob(10) thing now, i am unsure if it was done well or not, it's in chemistry reagents for nanites.

**Comment by tayachiya** [comment]
I thought its not guaranteed for roburgers to work?

**Comment by DeityLink** [comment]
they contain nanites which give you the robot transformation disease. Once you have the disease you SHOULD eventually become a borg.

**Comment by robintime** [comment]
fixed by #27946
