### ISSUE TITLE
IAA HR papers no longer send automated replies

### ISSUE THREAD

**Issue by toomykins** [d3athrow/vgstation13#27825]
saw some PR pop up a while ago about how messages sent to HR are now redirected to admins too, but now the pieces of paper that the IAA gets at roundstart to demote/reward someone no longer work. no response, nada.

**Comment by ShiftyRail** [comment]
There was a deliberate choice to remove the automation element, yeah. I don't like that any piece of paper containing "demotion" faxed to the right address would automagically give away a demotion key.

**Comment by toomykins** [comment]
I don't believe the demotion patches were used often, if at all. It'd require an active scenario where the IAA and security work together (rare) to demote a malignant higher-up (even more rare), that small amount of unused power is now lost.
furthermore, the loadout of the IAA has not changed, and still contains the pieces of paper with instructions on how to use them.
