### ISSUE TITLE
Rename all GPSes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27828]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
*hits Godblunt*
Why's it called a global positioning system if we're in space?

**Comment by Kharkov72** [comment]
at last I truly see

**Comment by GreatBigFailure** [comment]
Galaxy Positioning System

**Comment by SonixApache** [comment]
global is the scope

**Comment by west3436** [comment]
honk
