### ISSUE TITLE
Ling lesser form

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27833]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
d5a5320d61bcdeac10b31cab91e4e60e775a6d45

# Description
Can crash clients and boot people to the lobby

# Steps to Reproduce
https://i.imgur.com/jugW8Nj.png

# What you Expected
Transforming easily

# What Actually Happened
A whole lot of fuckery

**Comment by Eneocho** [comment]
imgur link is dead and the ling fixes #31891 probably took care of it, since no further reports about lesser form crashing have been made since it was restored, reopen if it somehow happens again, though i doubt it
