### ISSUE TITLE
(possibly) Outfit Datums: Nonhuman jobs who start with some slots filled don't have the missing clothes dropped on the ground at roundstart

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#27842]
Hard to describe this problem verbally, but basically

Step 1. Start round as chef vox
Step 2. Expect to see the chef apron suit and chef's hat
Step 3. Since those slots are occupied by pressure suit, they evaporate

Previously, they would not be equipped, but they would be dropped on the ground where you spawned. I think that's much more preferable to having them not exist at all, since some stuff (like the chef's spawning apron) is unobtainable except from spawning.

I could imagine this arises with a few other niche cases, and it'd be nice if the fail case dropped the items down instead of deleting them.

**Comment by kilozombie** [comment]
According to jknpjr they drop in the cuck cube instead. It'd be nice, though I can't imagine that easy to code, if they were moved to where you spawn instead.

**Comment by ShiftyRail** [comment]
>According to jknpjr they drop in the cuck cube instead. 

No they don't. Outfit datums was made specifically so that wouldn't drop there. They are simply never spawned. A possible fix would be to put these in your backpack. If you chose to spawn without one, to put it in on the ground.

**Comment by Armadingus** [comment]
Please sir, my yellow hardhat. I can't live without it.
