### ISSUE TITLE
Synergy medbay escape pod is vented

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27847]
(WEB REPORT BY: fuzzynut51 REMOTE: 206.221.180.138:7777)
# Revision
94c72ab70c00dbcff1f7dfa671216df3e82b3b7e

# Description
Escape pod outside medbay has bad pressure and no air
# Steps to Reproduce
Open airlock, slip over and stop breathing
# What you Expected
To sit in a small room that flies
# What Actually Happened
It hurt me

**Comment by Irradiation** [comment]
Podbaby gets what he deserves.
