### ISSUE TITLE
Stubborn brain not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27855]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
f2ff257a12d56756871ee885022e04bcd6887dc2

# Description
IT NO MAKE ZOMBIES.
[10:57:18] Gimme the Mutamin PM from-PrimeD: say "it broke no zombies"
[10:57:40] Gimme the Mutamin PM from-PrimeD: your body was on stage 4 it just wasn't zombifying you

# Steps to Reproduce
get disease with stubborn brain, get to stage 4, die.
# What you Expected
zombie apocalypse
# What Actually Happened
zombieless apocalypse

**Comment by AI-Is-Rogue** [comment]
Through log diving and local testing what I can tell is this was likely an issue of the disease progressing too slow to activate stage 4, local testing confirms that the symptom itself works. Being a fungus disease it has a progress speed of 15%(15% chance to up the stage past 100 ticks of existing), from what I can tell in the logs the round ended twenty minutes after the first shouts of flesh melting from the virus, which left little time to reach stage four on top of the virus making you drunk and killing you if anyone runs into you with non-green intent. 
Theoretically, it could have also been a lack of robustness, the virus was likely at strength 100% which would mean the robustness of the virus has to be <50% to be disabled by 5u of spaceacillin. 
Hot tips: virus food will accelerate disease growth and high robustness is very important to make sure your symptoms are activated.
