### ISSUE TITLE
Vegetable pizza is not vegan

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27856]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
0806b26f8ca2b00addb6dd470e68986b68662d91

# Description
Vegetable pizza slice is disgusting! Your vegan digestive system rejects it.
You feel nauseous...
You throw up!
# Steps to Reproduce
Be vegan, order pizza from cargo, eat Vegetable Pizza, throw up

# What you Expected
Vegetable pizza to be vegan
# What Actually Happened
I threw up

**Comment by ghost** [comment]
vegetarian != vegan, not a bug

**Comment by PrimeDSS13** [comment]
pizza has cheese on it

**Comment by Exxion** [comment]
Cheese.
