### ISSUE TITLE
Please dont count destroyed silicons against Crew Score on Malf

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27868]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
9235a1c75374f52dea6a9a7da710d8b4170f9309

# Description
Its a bit unfair to my autism to get -500 because we murdered the AI in cold blood for trying to kill us.

**Comment by Dacendeth** [comment]
Destruction is silicons should give bonus points under all circumstances
