### ISSUE TITLE
Man stung to death by hornets, wont stop screaming and dying despite being beheaded and dead.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27861]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
c0bf4ce71545169d551ccc5057eef9d25ff8fe93

# Description

Holy shit these hornet necromancers are horrifying.
# Steps to Reproduce

Get stung to death by hornets from the bee gun
# What you Expected

The sweet release of death
# What Actually Happened

EVEN IN DEATH HE STILL SCREAMS AND DIES AGAIN IS NOTHING SACRED

**Comment by DeityLink** [comment]
Chances are that the bug isn't hornet specific, audible_scream() seems to bypass status, which means that if you keep attacking someone who's already dead with enough damage you might hear them scream again at some point.

**Comment by ShiftyRail** [comment]
might I say `feature`

**Comment by DeityLink** [comment]
surely they're bound to stop screaming once their head explode right?
