### ISSUE TITLE
Spessmart can spawn live headcrabs as hat clothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27867]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
9235a1c75374f52dea6a9a7da710d8b4170f9309

# Description
Because headcrabs are technically hats spessmart has a chance to spawn live headcrabs in its clothing department. This causes concern of spessmart becoming locked down by killing the headcrab or aggroing the headcrab into breaking stuff.

# Steps to Reproduce
Find spessmart and be very unlucky.

# What you Expected
Cool hats.

# What Actually Happened
Oof ouch my skull.

**Comment by DrSnips** [comment]
Based and unforeseen consequences' pilled. Time for the blacklist-ening.

**Comment by ghost** [comment]
its a feature, they're funny alien hats

**Comment by gurfan** [comment]
live facehuggers can also spawn there

does killing the headcrab/facehugger lock down spessmart or was that just a concern

**Comment by Dacendeth** [comment]
can headcrabs break windows/racks trying to get to people? If so that would be a problem.

**Comment by Blithering** [comment]
I have had the bad luck to have a toy facehugger jump on my face as I was leaving spessmart, setting off the alarms on the way past. With how strict the rules are maybe objects capable of independent movement are a bad idea to stock.
