### ISSUE TITLE
Certain Vox skintones lack tails

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27875]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
990cdc99ced567d3493067a30470dabfc14523c4

# Description
Vox skintones 4,5, and 6 (Light green, Azure, Emerald) all lack tails on their sprites (or atleast in the character set-up auto-gen'd preview)
# Steps to Reproduce
Create a vox character, set skin tone to 4, 5 or 6
# What you Expected
Mangy shitbird tail
# What Actually Happened
tailless

**Comment by Exxion** [comment]
Duplicate of #13714
Nobody will ever fix this because they would be called a furry

**Comment by ghost** [comment]
I guess I have a job to do then
