### ISSUE TITLE
AI shell cant hear all frequencies AI can

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27887]
(WEB REPORT BY: surrealitarian REMOTE: 206.221.180.138:7777)
# Revision
de1e2dcefd563f0cc95be10906f814ef4b9f7c02

# Description
cant hear security as engiborg
# Steps to Reproduce
be a module, cant talk in radio of other modules
# What you Expected
i need to hear things i am the AI
# What Actually Happened
cant hear shit while shelled

**Comment by jknpj** [comment]
While inside the shell you're a cyborg, not an AI.
