### ISSUE TITLE
shells are fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27885]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
82826c927ee657eccbaa80b99bf60e101e48f630

getting not while incapacitated message when trying to jump to shell, shell didnt get proper name, aahhh this all worked in testing

**Comment by SonixApache** [comment]
[100% tested], etc

**Comment by ghost** [comment]
@jknpj this issue can be closed now since the feature was shot down.
