### ISSUE TITLE
Virology enhancements

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#2789]
- Pathogenic incubator should have an icon state instead of pinging
 - Pathogenic incubator beeps should be audible
 - Something like a filing cabinet for syndrome disks should be placed in the lab

**Comment by ComicIronic** [comment]
One part of this (the cabinet) isn't fufilled.
Should leave this open.

**Comment by Faptastic** [comment]
I took care of symptom storage via the disease analyser, it's all fulfilled now.
