### ISSUE TITLE
EVERYTHING IS CANDY

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#2790]
The candy machine at the kitchen won't take any item known to man because it thinks "it's already candy".
Apparently this is caused by it being admin-disabled, which begs the question: what does this thing even do to deserve getting admin-disabled?

**Comment by AutismSpider** [comment]
Candy Machine needs rework we have sugar jelly coco and slime jelly

Make the candy machine run off that.

**Comment by 9600bauds** [comment]
Well, we also have a lot of grilled and baked goods, yet unique grilling and baking recipes still use the microwave.
We'd need a MAJOR cooking overhaul which for the moment I don't think is very necessary since the chef already has a ton of options for food.

**Comment by CptWad** [comment]
Why is this not fixed yet.
Candy machine still does not work and nobody else has said anything for a month

**Comment by AutismSpider** [comment]
This and flamers are bug too. so meh
