### ISSUE TITLE
UI+UE injectors have no effect on vox post-tailfix

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27909]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
4cc7a43be7c4d794b89b9a34c50ba5be7403b6bc

# Description
UI+UE injectors do not update vox sprites. Possibly related to recent colored vox tailfix.

# Steps to Reproduce
Clone vox for random apperance. Copy UI+UE from original body and inject.

# What you Expected
Clone takes apperance of original sprite

# What Actually Happened
Sprite unchanged

**Comment by DamianX** [comment]
I thought I could have caused this with #27872 or #27762, but I reverted them locally and the sprites still don't update.
It looks like non-human skin color was never changeable through genetics.

**Comment by Exxion** [comment]
Probably dates back as far as discrete skin colors in general do
