### ISSUE TITLE
Radio channel colors are messed up in dark mode

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27913]
(WEB REPORT BY: stormcloud23 REMOTE: 206.221.180.138:7777)
# Revision
4cc7a43be7c4d794b89b9a34c50ba5be7403b6bc

# Description
I've always played in dark mode, and previously different radio channels would be color coded. Orange for engineering, brown for supply, red for security, etc. I took a break for a month or two and now I've come back and something seems to have broken the color coding, because all radio communictions show up in the same light green color now. Anyone know what's going on? 

# Steps to Reproduce
Dark mode and check radio channels
# What you Expected
Color coded radio
# What Actually Happened
all radio comms share the same light green color

**Comment by DeityLink** [comment]
Re-open if issue still occurs. Seems like a weird one-off occurrence.
