### ISSUE TITLE
Roid lich can cause corpses to hallucinate in deadchat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27918]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
f71eb96f269ee37767bd56be5e1320bf6cc53c99

# Description
Azlin can cast hallucinate on corpses which causes them to deadsay hallucination effects that would normally be sound effects to the player ([03:34:22]SAY: Zezree/*no key*/(Zezree) (@209,140,3) Deadsay: stammers, "Beep, boop")

# Steps to Reproduce
Die to azlin, might also require mousing or some other method to make your old corpse catatonic

# What you Expected
nothing

# What Actually Happened
old corpse randomly speaks hallucination effects into deadchat

**Comment by GreatBigFailure** [comment]
Not even the dead can know peace from this evil etc

**Comment by DeityLink** [comment]
Need to make it speak in living-chat because I love the idea of plants mind-controlling corpses to make them speak.

Oh wait, it's lich, not lichen. Damn I'm tired.
