### ISSUE TITLE
The way nonhuman races are handled in Genetics

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#2791]
Okay, so I'm sure most of you know by now there's a major bug in cloning. If you're a nonhuman race, and you're cloned, you always become human. No buts about it.

That's a major bug, if I ever saw one. It's even worse that some people haven't caught on, and some people even refuse to use the defrib on a nonhuman patient, for 'm-muh griffs'.

In what is probably a related bug(or feature??), if you take the UI+UE from someone, and you're a different race from them, you will not take on their appearance or race, only their name. Were it to take the appearance and race, this would open a lot more options for Genetics.

**Comment by gbasood** [comment]
Does the SE even have a segment for race?
