### ISSUE TITLE
Chaplain Request: Blakism

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#27921]
#### Description of issue

We've got all these great degenerate religions but we have absolutely fucking nothing for the Blessed Blake, he whom shall return one day to reunite the Star League and bring about eternal peace.   Also this should give you telecomms access and Comstar Acolyte as a title. 

#### Difference between expected and actual behavior

Pay your phone bills fuckos

**Comment by Kurfursten** [comment]
No other title gives you increased access (e.g.: ZAS the atmos tech religion, Security religion, Gaia/botany, or Clownism) and I think we should not go that direction either. Ask the HoP if you want more access.

**Comment by SGuivenne** [comment]
Sorry, I was under the impression they did.

**Comment by anunknownentity03** [comment]
its all just fluff with the titles nothing more
