### ISSUE TITLE
Condimaster Conundrum, Pepper Problem

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#2794]
When trying to bottle salt with the CondiMaster in the kitchen, the resulting salt shaker will be invisible. After emptying it, it will turn into a nondescript "Condiment Bottle". Not that it really matters honestly, but I thought I'd report it.

A bigger issue is that there is currently no recipe for black pepper, which means you're shit outta luck when you run out. I combed through the code and found this in the blending results code:

/obj/item/seeds = list("blackpepper" = 5),

It uses nondeclared seeds which you can't obtain. Perhaps it was supposed to be chili seeds?

**Comment by AutismSpider** [comment]
it was chili seed pack to make some pepper.

unless some thing happen to that line of code?

**Comment by 9600bauds** [comment]
Tried both juicing and grinding - nothing produces.
Easy fix though I imagine, replacing the line with /obj/item/seeds/chiliseed should work right?

**Comment by d3athrow** [comment]
People assumed it would work on child types I assume

**Comment by 9600bauds** [comment]
Apparently at some point it used to work, but I can't vouch for that

**Comment by ComicIronic** [comment]
Oddly enough, even the base seed type does not produce pepper in the grinder.

**Comment by 9600bauds** [comment]
HALLELUJAH
ALL PRAISE
