### ISSUE TITLE
Placing regular welding goggles in the DA and deconstructing it afterwads puts the DA in an infinite loop.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27943]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
2053490328548bf4a34151691bfe39118f5790ef

# Description
Some dumbass in R&D placed welding goggles inside the DA, decided to deconstruct it and for some reason the DA got stuck in a infinite work loop. It didn't allow me to screwdriver it open to deconstruct the DA and the R&D console didn't deconstruct or ejected the goggles since it gave you the "The DA is in use" message

# Steps to Reproduce
1- Get welding goggles
2- Place it in the DA
3- Deconstruct it or kick the DA
4- Pray for Jesus

# What you Expected
Being able to keep working on research

# What Actually Happened
Got arrested for Vandalism

**Comment by Eneocho** [comment]
Couldn't reproduce so it is probably fixed.
