### ISSUE TITLE
Detective scanner can no longer identify blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27947]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
b92f930d658af4973aa970b38ad5141f69843996

# Description
All blood, no matter how fresh shows up as N/A old blood spatters, so cant be used to solve crimes.
# Steps to Reproduce
cut self with knife, scan own freshly dropped blood.
# What you Expected
blood type O+, dna 5531b24b27c82c0de0040740b8180871

# What Actually Happened
N/A old blood spatters

**Comment by DeityLink** [comment]
I'll look into it tomorrow
