### ISSUE TITLE
roid R&D shutter only covers one window

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27962]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
339ef2fd27f772ac2512543c4c66552105b7b19f

bad

**Comment by Kharkov72** [comment]
if I had to make baseless acusations, its because the shutters and the button aren't on the same frequency and the button shouldn't even *exist*, HOWEVER since the button is directly next to one of them it triggers that one by proximity because god is dead.

**Comment by DeityLink** [comment]
@Kharkov72 Nope. Turns out that there's supposed to be TWO shutters on each tile. One is the regular R&D lab shutters, the other is the global Science Biohazard shutters controlled from the RD's office. Both tiles of R&D's desk have the Biohazard shutters, but only one has the regular lab shutters.
