### ISSUE TITLE
Ancient flatpacks sometimes print the wrong instructions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27966]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
339ef2fd27f772ac2512543c4c66552105b7b19f

# Description
Ancient flatpacks sometimes print an incorrect list of instructions or duplicate steps instead of listing the correct ones. I got one with three wrench steps in a row that were actually wrench, welder, then screwdriver. Admin online at the time also notified me that you can spam one tool during the progress bar to complete all steps.

# Steps to Reproduce
Order an ancient flatpack from the trader vendor and get unlucky.

# What you Expected
Ikea quality furniture.

# What Actually Happened
Ikea quality furniture complete with incorrect instructions and random extra parts.

**Comment by Killette2** [comment]
I want to think this is actually a feature

**Comment by Zth--** [comment]
Intended behavior
