### ISSUE TITLE
The NT disk paper instructions don't mention the mind swapping pod machinery anywhere

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27973]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
339ef2fd27f772ac2512543c4c66552105b7b19f

# Description
The NT disk paper just tells you about the shit you can make under the Nanotrasen tab. There's no mention of the mind swapping pod machinery anywhere

# Steps to Reproduce
1- Order the NT research crate
2- Open it
3- Read the instruction
4- No mentions of the mind swap pod machinery

# What you Expected

At least a shoutout
# What Actually Happened

**Comment by GreatBigFailure** [comment]
I didn't even know there were instructions. Thanks, I'll update it either tonight or tomorrow.

**Comment by DeityLink** [comment]
And he never did.
