### ISSUE TITLE
Gas mask

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27976]
(WEB REPORT BY: zanith50 REMOTE: 206.221.180.138:7777)
# Revision
339ef2fd27f772ac2512543c4c66552105b7b19f

# Description
Gasmask works when in the up possition for giving air/o2
# Steps to Reproduce
find a gas mask put it on go in vaccum with interals on
# What you Expected
the gasmask to not function when lifted up
# What Actually Happened
gasmask continues to function normaly

**Comment by DamianX** [comment]
Duplicate of #21912
