### ISSUE TITLE
Bump lets you move another mob onto anywhere.

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#2797]
How to reproduce:
1. Get a mob next to you.
2. Build a wall on the turf you're on.
3. Attempt to move into the mob's turf. The mob will switch places with you, onto the wall.

Hilarious effects:
You could build a conga-line of people in walls to have a ferry system back and forth over one or several wall tiles.

**Comment by d3athrow** [comment]
Goddamnit

**Comment by ComicIronic** [comment]
You are on the wall and move off the wall.
You can actually be on any object and switch another mob onto that object.

I noticed this when I was messing around with Poly's saycode for testing and she moved me onto the suit storage unit.
