### ISSUE TITLE
Asteroid - Broken camera

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#27991]
(WEB REPORT BY: mikeytwolf REMOTE: 206.221.180.138:7777)
# Revision
68357f0b64a296d122ff1bdb2f13e9b0cb04a003

# Description
Wall mounted camera in same place as wall mounted lantern, so it's just on the floor

# Steps to Reproduce
Go to Asteroid and visit the catwalk outside of Artifact

# What you Expected
A working camera

# What Actually Happened
A camera lying in space/the floor

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/130507253-1405e6ee-d782-46b3-ae4e-4e21368e8732.png)
🤔

**Comment by DeityLink** [comment]
I mean yeah you probably cannot do it in-game but I think that's intended, a power reserved to mappers.
