### ISSUE TITLE
supermatter shards sometimes wont delete themselves when exploding causing an infinite explosion loop that destroys the server

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#27999]
#### Description of issue

>welderbomb shard
>shard explodes as usual but doesnt get deleted after explosion
>supermatter cascade lite

#### Length of time in which bug has been known to occur
it is a mystery

**Comment by Exxion** [comment]
It would be really funny if explosion throwing is dragging it back from qdeletion
This is my best theory so far but that's not saying much

**Comment by gurfan** [comment]
@Exxion 
also an admin tried forcefully deleting and it refused to die despite the log saying that it was deleted

**Comment by Exxion** [comment]
Was it visible while it was constantly exploding?

**Comment by boy2mantwicethefam** [comment]
Nice trips

**Comment by Exxion** [comment]
Copypasting what I wrote in the Discord:
>Given that people report it was still visible, when `invisibility` is set earlier in `Destroy()` than `gcDestroyed`, my only possible guess is that it was some kind of chance memory error resulting in `gcDestroyed` being set to some truthy value without `Destroy()` ever having been called on it

Could be some kind of weird bug in our code that somehow changes a var incorrectly, could be a BYOND bug, could be a fucking cosmic ray flipping a bit in the server's memory. But I can't see any way it could possibly happen in a repeatable fashion.
In other words, don't worry about it unless it happens again.

**Comment by SonixApache** [comment]
hey that's what happened that one time when i made a rocket that wouldn't stop exploding
![infiniteexplosions](https://user-images.githubusercontent.com/8468269/95766923-48cd6900-0cb4-11eb-9cdc-9cdcf5555154.png)
maybe related to the famous wizard fireball blob issue as well?

**Comment by Exxion** [comment]
Wizard fireball blob was fixed. Rocket is probably a separate issue to both of these.

**Comment by DeityLink** [comment]
I think I saw it occur on another occasion. At the very least a simple patch for the sake of preventing lag would be to add a variable that prevents the supermatter from exploding twice, and send an log message if it tries to explode a second time.
