### ISSUE TITLE
dude horizon lmao

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28009]
(WEB REPORT BY: originalbubsra REMOTE: 206.221.180.138:7777)
# Revision
46d93b754cbb06b2726fb198a3088a4498985d7b

# Description
what's an OSHA regulation? vox merchants investigate

# Steps to Reproduce
walk into the vox landing pad at any giving point the shuttle is not on-station

# What you Expected
a warning or indication that instant, round-removing death was imminent

# What Actually Happened
>open the door
>get on the floor
>everybody kill the dinosaur

**Comment by Kurfursten** [comment]
There are in fact blinking landing lights, both on the airlock and docking lights in the windows.

Darwin claims another

**Comment by DamianX** [comment]
These "blinking" landing lights only start blinking once the shuttle is moving, the rest of the time they are a black patch of pixels on a black and grey grille. There should probably be a cycling airlock or at the very least big yellow warning signs.

**Comment by Kurfursten** [comment]
There definitely is a warning sign that says it's the trader dock.

**Comment by DamianX** [comment]
Definitely not OSHA-approved 
![image](https://user-images.githubusercontent.com/6307265/96000900-b48c0f00-0e37-11eb-999c-d7ffd8696aea.png)

**Comment by toomykins** [comment]
honestly horizon has had more of these "1 door to space" airlocks, and it's caused lots of unneeded wild rides.

**Comment by Kurfursten** [comment]
I just don't know what else to do for players who ignore an external airlock, parking sign, vox sign, and docking lights.

Let em squish.

**Comment by Exxion** [comment]
Might want to move the signs closer to the airlock, but work beyond that would just be babyproofing

**Comment by Eneocho** [comment]
@Kurfursten since this applies to the previous iteration of Horizon, should this be closed?

**Comment by Kurfursten** [comment]
I feel like players have successfully adapted to this situation (which hasn't changed) in 4 years
