### ISSUE TITLE
funky laser visuals

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#28010]
#### Description of issue
the visible laser beam is laggy, wierd, and inconsistent on two occasions:

rainbow gun laser:  it's white instead of rainbow, the visible lasers appear almost a second or so after firing, the lasers sometimes go through walls (and actually hit people across the map..? not sure about that part) the whole thing is fucked

Shooting AI turrets with any laser also messes up the beam for some reason, you see the actual laser beam 0-1 seconds after actually firing, just like the rainbow laser

#### Steps to reproduce

fire a rainbow laser gun anywhere
fire any laser gun at a turret

#### Length of time in which bug has been known to occur
since the laser update

**Comment by Dacendeth** [comment]
weird things happen with the spacepod laser too, sometimes one will shoot way before the other when they're supposed to shoot simultaneously.

**Comment by DeityLink** [comment]
Partially fixed by #29708
The weird delay that appeared when firing a laser is gone. Rainbow laser still needs more changes.
