### ISSUE TITLE
You can see the borg in the Dojo using the security camera console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28022]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
134b7338e012e9a778449d8a79a7aa4b926570e7

# Description
You are able to access the Dojo borg's camera using the regular secuirty camera console

# Steps to Reproduce
1- Find or make a security camera console
2- Click the robot icon in the top left
3- Check for default borgs
4- Take a look at the dojo

# What you Expected
Nothing, tbh

# What Actually Happened
Cool place weeb

**Comment by SonixApache** [comment]
gods
