### ISSUE TITLE
Chemical Requests: Immunosupressant

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#28025]
#### Description of issue

The current immune systems reliance on the production of antibodies meant that immunosuppressant, as a form of poison or even intentional chemical to prevent developing immunity would be a valid addition.  This would also have usage if you folks ever add auto immune diseases, as a fun landmine for if people try to just roulette vaccination types for everything.

**Comment by SonixApache** [comment]
radium destroys your immune system

**Comment by west3436** [comment]
Pretty much already a feature via Radium

**Comment by SonixApache** [comment]
radium destroys your immune system
