### ISSUE TITLE
No bagelstation despite having made 17 bagels

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28028]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
a6892f543e5ef978de5818be03c4bed26b0d72c9

# Description
What it says on the tin.
# Steps to Reproduce
Make 17 bagels.
# What you Expected
Bagelstation to appear on the voting.
# What Actually Happened
Nothing

**Comment by DamianX** [comment]
Should be fixed
