### ISSUE TITLE
Buttons on the top right opens the URL wrongly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28026]
(WEB REPORT BY: epicbawmba REMOTE: 206.221.180.138:7777)
# Revision
a6892f543e5ef978de5818be03c4bed26b0d72c9

# Description
When clicking the 'Wiki' button in the top right corner (near Info, Forum, etc). This seems to happen with every button from 'Wiki' until the button for the station render.
# Steps to Reproduce
1. Click on any button (Wiki/Forum/Rules/Changelog/<station render>)
2. Incorrect URL opens
# What you Expected
I'm expected to, for example, get http://ss13.moe/wiki/index.php/Main_Page

# What Actually Happened
The button redirects me to "http://%22http//ss13.moe/wiki/index.php/Main_Page%22"

**Comment by DamianX** [comment]
works on my machine

**Comment by Exxion** [comment]
Lummox broke links in BYOND. Update to latest.
