### ISSUE TITLE
Safes can spawn impossible to open due to overlapping tumbler positions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28027]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
a6892f543e5ef978de5818be03c4bed26b0d72c9

# Description
Safes can spawn with their target tumbler positions too close together making them impossible to open due to overlap. The position to get the tumblers moving again after locking one will be after the target position to lock the other tumbler, making it impossible to reach without resetting the tumblers.

# Steps to Reproduce
Get an unlucky safe spawn.

# What you Expected
This is a bug I recognize from years ago that was fixed until a few days ago.

# What Actually Happened
Unsurprisingly when I look up the safe code on github shiftys clothing datums are listed as the most recent changes. Thanks obama.

**Comment by boy2mantwicethefam** [comment]
I tried to fix it but the fix didn't work

**Comment by DeityLink** [comment]
Damn I also remember that bug from literally years ago
