### ISSUE TITLE
We got a score of -69559 but still no Lamprey on the round selection.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28033]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
2cfb9d7c57369825e0e48cdd2dd56f751b51f02a

# Description
We literally infected 1480 monkeys to get a low score (-69559) and still no Lamprey.

On another bug report I did, I baked the 17 Bagels to get Bagelstation, it didn't appear either. 

Test your code before promising non-existing features.
# Steps to Reproduce
Get a score of -20000 or lower. We got to -69559 via infecting 1480 monkeys, try to aim for that.
# What you Expected
Getting Lamprey on our Map selection as promised.
# What Actually Happened
Lamprey didn't appear on the Map selection. We didn't get to see Lamprey at all.
We got the exact opposite of what we wanted. Instead of Lamprey, we got Horizon.

**Comment by SonixApache** [comment]
this issue is proof that adding lamprey to the voting was a horrible horrible idea
