### ISSUE TITLE
Pears missing sprite.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28038]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
eb47d7299a6ecc0b4248b5f1923040614b45738f

# Description
Pear tree missing sprite for fully grown stage, but not ready to harvest stage.
# Steps to Reproduce
Grow pear tree. Wait for pears. Harvest pears. Pear tree vanishes.
# What you Expected
Pear tree to stay there
# What Actually Happened
Pear going stealth mode.

**Comment by gurfan** [comment]
here we go again

**Comment by coronasaurus** [comment]
self harvesting invsibile pear kudzu when
