### ISSUE TITLE
lamprey still isnt votable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28032]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
2cfb9d7c57369825e0e48cdd2dd56f751b51f02a

-69000 score, lamprey still not votable
fuck you barry

**Comment by d3athrow** [comment]
based

**Comment by SonixApache** [comment]
working as intended

**Comment by robintime** [comment]
#28033 is a more descriptive duplicate of this issue
