### ISSUE TITLE
There is no medical records machine in virology

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28048]
(WEB REPORT BY: sailol REMOTE: 206.221.180.138:7777)
# Revision
b601cfc730820704ad3bd54691eea3be412b66a5

# Description
There is no medical records machine in virology to check for the diseases one has analysed and to properly identify symtoms
# Steps to Reproduce
Just look at virology
# What you Expected
A medical records laptop in virology
# What Actually Happened

**Comment by DeityLink** [comment]
@Sailol what map?

Assuming it's bagel @DamianX

**Comment by DamianX** [comment]
There's a medical records laptop in virology. He couldn't be bothered to specify which map, I certainly cannot be bothered to check all of them.
