### ISSUE TITLE
Airtight flaps don't seem to work when moved

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28058]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
b973ac56beed5fa842ee52a34056d7a840268ac7

# Description
airtight flaps aren't airtight when you move them around and rebolt/tighten them. Nuff said
# Steps to Reproduce
move airtight flaps (e.g. from the podbay) and reanchor them. Gasses still slip through after they're tightened
# What you Expected

# What Actually Happened

**Comment by SonixApache** [comment]
I made this room, wrenched the flaps loose and tight, then crowbarred them airtight.
![image](https://user-images.githubusercontent.com/8468269/96447534-52a21f80-1212-11eb-9336-0bc8f5deeb47.png)
Works vertically.

I made this room, wrenched the flaps loose and tight, then crowbarred them airtight.
![image](https://user-images.githubusercontent.com/8468269/96447697-9ac14200-1212-11eb-8b2c-813d36a86479.png)
Doesn't work horizontally?

I went back to the first room and moved the flaps.
![image](https://user-images.githubusercontent.com/8468269/96447822-cb08e080-1212-11eb-8a59-d8eb13ad824d.png)
????air zones not updating?

**Comment by DrSnips** [comment]
The obvious solution is to make a horizontal sprite so they block gases in the other direction.

**Comment by Exxion** [comment]
They probably just don't mark their turfs for update when moved

**Comment by DeityLink** [comment]
So I tried spawning airtight flaps in the thunderdome to test but they just don't seem airtight at all, at least when spawned. Calling 
update_nearby_tiles () on the central canister doesn't help.

**Comment by Eneocho** [comment]
Tested it a bunch and couldn't reproduce the issue so it is probably fixed.
