### ISSUE TITLE
Mesons and Meterial Scanners no longer fit in pockets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28059]
(WEB REPORT BY: subs455 REMOTE: 206.221.180.138:7777)
# Revision
b973ac56beed5fa842ee52a34056d7a840268ac7

# Description

Meson glasses, and Material Scanner glasses no longer fit inside jumpsuit pockets, despite being classified as Small items.

I spoke with Armadingus about this issue and he repots that it might have something to do with the PR that made mesons fit over prescription glasses.

**Comment by DeityLink** [comment]
Fixed by #29930
