### ISSUE TITLE
Lit match in matchbox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28061]
(WEB REPORT BY: thiccccccer REMOTE: 206.221.180.138:7777)
# Revision
570ca72faccfde6741b66b2f4b2ecb3ccd5f5393

# Description

Not really that important, but put a lit match into a matchbox and the box and match disappear completely.

# Steps to Reproduce

Purchase/take matchbox
Light match
Put match in box
Both disappear

# What you Expected

Not sure to be honest, box to catch fire or something with a message?

# What Actually Happened

**Comment by SonixApache** [comment]
it used to light all the other matches in the box, didn't it?

**Comment by toomykins** [comment]
fixed

**Comment by DeityLink** [comment]
Fixed by #33440
