### ISSUE TITLE
PAI positioning is hot garbage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28060]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
1680a6d8b59493b27882c6534ebee86412b607af

# Description

It can neither be deactivated nor opened while moving, which makes it useless for anything really.

**Comment by SGuivenne** [comment]
Update; It wont open after being closed, period.

**Comment by Eneocho** [comment]
Can be properly opened while moving or while static, not being able to disable the GPS is a feature of all GPS/SPS systems.
