### ISSUE TITLE
Vending Machine Eats Your Cash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28064]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
570ca72faccfde6741b66b2f4b2ecb3ccd5f5393

# Description
If you don't have enough funds in your account to make a vending machine purchase, it allows you to combine your Wallet funds to make the purchase! The issue is if you do not have enough funds in the combined accounts, the transaction fails and completely empties out your wallet (though your account funds are safe, and any coins used are not consumed).

# Steps to Reproduce
Try to buy a diamond pickaxe without a combined $300 in wallet and account funds. It will offer to use the wallet funds. Accept. It will reject the transaction due to not enough funds, and your wallet will be empty.

# What you Expected
Rejected transaction, wallet funds left in place.

# What Actually Happened
Rejected transaction, it charges you all of your wallet funds for even trying.

**Comment by SonixApache** [comment]
feature

**Comment by ghost** [comment]
known issue that no one cares to fix

**Comment by jwhitak** [comment]
Nearly two years later, I return to collect my bugfix valids.
