### ISSUE TITLE
All capacitors have same level of charge

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28079]
(WEB REPORT BY: doomergloomer REMOTE: 206.221.180.138:7777)
# Revision
5e67ccdbcda882a4001205640f3ba5e6f8d9ee2b

# Description

Capacitors produced by Vox upgrade kit have same level of charge

# Steps to Reproduce

1. Find machine with capacitors
2. Use Vox upgrade kit
3. Decon and take upgraded capacitor

# What you Expected

That upgraded capacitors would have more charge

# What Actually Happened

All capacitors have same charge level

**Comment by Dacendeth** [comment]
You're not supposed to be able to get the better parts out of the vox upgrade things by taking the machine apart.

**Comment by Kurfursten** [comment]
This isn't a bug, all capacitors have 0 charge by default, only the max charge changes

**Comment by Aegon526** [comment]
But max charge doesn't change, they are all 50,000 charge.  Ultra caps, super caps, normal capacitors.

**Comment by Exxion** [comment]
Pretty sure he meant max charge

**Comment by Eneocho** [comment]
Tested it, all capacitor types have a different max charge that increases according to the tier.
