### ISSUE TITLE
MoMMi's missing stun arm

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#2807]
What the fuck is this?
![stun arm is gone](https://cloud.githubusercontent.com/assets/10268342/6052919/790719b2-ac9e-11e4-872b-786b142a02f4.PNG)

**Comment by d3athrow** [comment]
hah nice.

**Comment by AutismSpider** [comment]
if its a placeholder item make it real Esword if not put the Stun arm back in.
