### ISSUE TITLE
wizards spawning with no jansports

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28083]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
9259913a8a94517e83b48b828aa2c24eac3ca9c2

# Description

wizards often spawn with no backpack

# Steps to Reproduce
1. spawn as a wizard

# What you Expected
backsack

# What Actually Happened
a lack of sack on my back

**Comment by DeityLink** [comment]
Duplicate of #27766
