### ISSUE TITLE
Add tool belts to roboticist's starting gear (Suggestion)

### ISSUE THREAD

**Issue by githubuser4141** [d3athrow/vgstation13#28093]
#### Description of issue

Roboticists don't start with anything that'd give them an advantage over a generic scientist, in fact they only have less access. 

#### Difference between expected and actual behavior

Roboticists should spawn with a full belt of tools while lacking access to xenobio/toxins because that's  the scientist's job.

#### Steps to reproduce

1. Join as roboticist. 2. Try to access xenobio/toxins. 3. Realise you're basically a back-up role for when the scientist slots are full.

### Suggestion: 

Add a full toolbelt to people who spawn as roboticist, so that they don't have to loot from tool storage like assistants and add a reason to join as roboticist rather then scientist.

**Comment by Irradiation** [comment]
You get access to Tech Storage, for all it's worth.

**Comment by SonixApache** [comment]
Throw them a diagHUD for good measure.
Why the hell is the Science autolathe not just available to all of science? Dumb stuff.
