### ISSUE TITLE
Master trainer belt balls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28094]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
5af7a6c517f903be1f4a6e4acd666bb422582a29

# Description
Balls from belt and station do not mix
# Steps to Reproduce
Capture monsters from with station balls. Get balls from Master trainer belt. Throw both out and they attack each other. Also Frost Kinght from the Master Trainer belt attacks the owner
# What you Expected
For my monster to not kill each other and only kill other people. Also for my own Frost Knight to not attack me.
# What Actually Happened
Monsters started killing each other and the Frost knight put me in crit.

**Comment by Killette2** [comment]
Frost Knights attack anyone when they shouldn't be attacking friendlies in other cases too
