### ISSUE TITLE
Mechs can open xeno doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28098]
(WEB REPORT BY: kereanil REMOTE: 206.221.180.138:7777)
# Revision
6e89085bbd7e8ed70ae37ae1924fae622664392e

# Description
When a mech walks into a xenodoors it opens

# Steps to Reproduce
Walk into one

# What you Expected
Doors actually protecting me

# What Actually Happened
Mech walked through like its nothing

**Comment by githubuser4141** [comment]
I'm not a coder, but wouldn't it make sense lore-wise that a mech would be able to "shove" its way through via sheer strength?
