### ISSUE TITLE
[Metaclub] Detective needs a photo album in his office (Feature Request)

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2809]
Putting the album, evidence bags, camera, folder with paper for notes/write-ups, etc. is a standard loadout. Without the album right there in your office to store a bunch of photos while you're investigating it's more fuss and makes using the camera a bigger turn off since it's causing more storage conflicts

**Comment by IratePirate** [comment]
Added. If you find more job specific items that are missing from offices across the station please let me know. Cheers.
