### ISSUE TITLE
[Feature Request] Round Statistics and Score needs more work!

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2810]
People have learned to look over it because half the things on the list don't work.  Random events endured, ore mined, research completed, hydroponic harvests.  All these are things that give a small nod to players for doing their jobs that may not otherwise get noticed.  Please have a look at why this isn't implemented, find out how to, and implement it.  Then rebalance the score system to take those in effect.  

Like Away Missions and economy, it's one of those things that looks really cool but needs someone to come along and devote some of their time for it.

**Comment by Boxe** [comment]
i vote to just have the damn thing removed

the hell is it good for

**Comment by d3athrow** [comment]
m-muh goone

**Comment by Probe1** [comment]
@boxe because it looks nice and rewards people for doing their job in a superficial but enjoyable way and provides closure to people who have done really well that round but otherwise would not be congratulated for it.  it provides structure and goals for people to strive towards but it isn't limiting and doesn't force people to play a certain way.

**Comment by Probe1** [comment]
It should be noted that deity link recently improved it but set the values for botanical harvests and ores mined too high so it's impossible to get any kind of failure.
