### ISSUE TITLE
Typing indicator prevents mulebot climbing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28103]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
162412e36b3ae5c001ef79ae9a71805f34f7cc7c

# Description
Typing indicator won't let you ride mulebots. Ask DamianQ more about it.
# Steps to Reproduce
Speak or do emotion, try to climb on mule
# What you Expected
riding mule
# What Actually Happened
SAUL IS MULEBANNED

**Comment by boy2mantwicethefam** [comment]
hahaha oh no no no
