### ISSUE TITLE
You can roll AI and MALF on Castlestation

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#28112]
#### Description of issue

1. Have Castlestation as map
2. Have a save file with AI job enabled
3. 
![image](https://user-images.githubusercontent.com/22218882/97640006-0d66c480-1a40-11eb-96a7-51909d6197a1.png)
4. Get sent back to lobby

#### Difference between expected and actual behavior

Didn't expect the actual code to malfunction

#### Server revision
30620e2f95772532d566e322776c29487861b084
[bugfix]

**Comment by d3athrow** [comment]
sounds about right for something @boy2mantwicethefam made

**Comment by boy2mantwicethefam** [comment]
Don't fix what ain't broken except for AIs still existing
