### ISSUE TITLE
Petritricin can dupe your character's statue

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#28110]
#### Description of issue
![Untitled](https://user-images.githubusercontent.com/55976761/97594851-5cdacf80-1a03-11eb-98c6-6296f869deff.png)
Doesn't actually duplicate your character, as the second statue is just empty.

#### Difference between expected and actual behavior
I expect there to be only one statue of myself spawning but that is not the case, I have one extra duplicate me.

#### Steps to reproduce
1. Make two 1 unit petritricin pills
2. feed one to a guy
3. let it metabolize until gone from person
4. repeat step 2 and 3 once to same person
5. now feed 2 units to said person and watch him become two statues

#### Specific information for locating

These messages popped up for me during the round it happened.
![image](https://user-images.githubusercontent.com/55976761/97596441-02db0980-1a05-11eb-90d1-a46fff8156fa.png)

**Comment by boy2mantwicethefam** [comment]
lmao2statue
