### ISSUE TITLE
Ian barks at Unknown and wags her tail.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28127]
(WEB REPORT BY: bobobozo REMOTE: 206.221.180.138:7777)
# Revision
30d4e5fce7cc007ee0d22dd7effa129c969ece5a

# Description
Ian barks at Unknown and wags her tail.
# Steps to Reproduce
Ian barks at Unknown and wags her tail.
# What you Expected
Ian barks at Unknown and wags his tail.
# What Actually Happened
Ian barks at Unknown and wags her tail.

**Comment by Exxion** [comment]
Bet it uses `\his` and thus goes off the gender of the person he barks at

**Comment by Kharkov72** [comment]
trans ian
trans ian

**Comment by drawsstuff** [comment]
trans ian
trans ian
