### ISSUE TITLE
[Feature] Give an option to use a character preset for ERT/Deathsquad

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2812]
Pretty much what it says on the tin, let players choose to either custom make a character when chosen for ert/deathsquad like we have now, 

Or give them a new option to choose one of their premade characters that they have saved to one of the 10 slots before roundstart. That way they can be instantly ready to do whatever upon being recruited.

**Comment by eswordthecat** [comment]
@ComicIronic label please.
