### ISSUE TITLE
Fotify Only protects the AI itself

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28130]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
30d4e5fce7cc007ee0d22dd7effa129c969ece5a

# Description
Fotify is supossed to defend the AI core (aka the room) it only defends teh AI 

# Steps to Reproduce
use fotify

# What you Expected
a ring of protection around the room

# What Actually Happened

ring just around the AI itself

**Comment by Dacendeth** [comment]
>When toggled, a nifty blast door appears around the AI, reducing the damage taken by 3/4. However, while the shield is up, the AI will take constant damage as if they were out of power.

**Comment by gurfan** [comment]
this is indeed not a bug

**Comment by jknpj** [comment]
It was never about the room
