### ISSUE TITLE
Singularity won't delete bags of holding

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2814]
It will just drag the bag around with it

**Comment by Probe1** [comment]
I've been meaning to look into this but haven't.  Weren't bags of holding supposed to explode and remove the singularities energy?  Cause I've thrown 5 bags into a stage 5 singlo before with absolutely no effect except it dragged the bags around sheepishly.

**Comment by Konater** [comment]
They are supposed to be deleted and have like a (25%?) chance of deleting the singularity and creating a large explosion

**Comment by Probe1** [comment]
That's how I understood it as well and have not seen a bag explode or be deleted in a month or more.  I'd definitely consider this bugged.

**Comment by NigglyWiggly** [comment]
Did something change regarding the singularity?
I've noticed that, in addition to this, super-singularities are impossible to create now, though that probably warrants its own issue report
