### ISSUE TITLE
Flamethrowers are bricked versus mobs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28153]
(WEB REPORT BY: mxr41 REMOTE: 206.221.180.138:7777)
# Revision
6603379ec673f9b854d8f70db6c15c4648bcec56

# Description
Shooting a flamethrower directly at a mob does no damage to the mob and stops the fire plume from spreading further. 

# Steps to Reproduce
1. Stand several tiles below mob. 
2. Shoot flamethrower at mob. 
3. Watch as mob blocks the fire plume completely, taking no damage. 

# What you Expected
The fire rises. 

# What Actually Happened
We didn't start the fire.

**Comment by Blithering** [comment]
Can confirm this also affects the tomb of rafid/roidstation satellite fire traps
