### ISSUE TITLE
State Laws window blank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28159]
(WEB REPORT BY: thiccccccer REMOTE: 206.221.180.138:7777)
# Revision
e6be5cb8a76ddbf9bea88ab95423df06cfbe69bb

# Description

The State Laws window is showing no laws whatsoever, despite the laws showing correctly in the Show Laws window. This happens even after a relog and is happening to more than one person (AI and Cyborgs).

# Steps to Reproduce

Honestly do not know.

# What you Expected

Window to show interface to state laws

# What Actually Happened

Window shows nothing apart from the N logo.

**Comment by DeityLink** [comment]
Seems like adding too many laws causes that.
