### ISSUE TITLE
[Metaclub] Kitchen is missing a snackbar maker

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2815]
Shift the gibber 3 tiles southeast and put a snackbar maker in would you please?
![image](https://cloud.githubusercontent.com/assets/8550416/6064298/062b69ba-ad2b-11e4-910b-41367a6ed8ac.png)

**Comment by Probe1** [comment]
Also while I'm looking at it, that second sink in the back room is superfluous.  There's already a sink in the kitchen and no real purpose for a second one in an adjacent room.

**Comment by IratePirate** [comment]
Done.

**Comment by Probe1** [comment]
Make sure you reference it with the PR so I can close it with documentation please.
