### ISSUE TITLE
[Feature Request?]Bagel Armory is Lacking.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28160]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
e6be5cb8a76ddbf9bea88ab95423df06cfbe69bb

# Description
The Bagel Armory is lacking a lot of things, and is rather empty. There are no holsters, and there are a lot of empty racks. Additionally, I don't think there is a roundstart beepsky in it. It could really use some modern touches.

**Comment by PrimeDSS13** [comment]
Additionally there's no ammolathe nor ammolathe disk.

**Comment by PrimeDSS13** [comment]
and maybe there should be an additional security camera console in the sec lobby room
