### ISSUE TITLE
You can thrall corpses, and it doesn't warn the corpse when they get thralled

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#28168]
>get owned
>vampire thralls corpse
>chat doesn't say this
>no warning or message at all if you already ghosted by then
>re-enter corpse when being revived
>have a thrall symbol
>confusedly check notes

Based on a true story.

**Comment by west3436** [comment]
similar to #26917's converting corpses, may wanna steal that approach here

**Comment by boy2mantwicethefam** [comment]
if anything it should revive the thrall, or turn it into a vampire

**Comment by dunsel-hordon** [comment]
Real question is why is there no way for a vampire to spread vampirisim?

**Comment by Zth--** [comment]
Adding a message to the ghost is sufficient? Or maybe vampires shouldn't be allowed to thrall dead corpses?
