### ISSUE TITLE
Mech tesla energy relays have illegal research in them.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28170]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
72bb1ebe498d87144d8fc7cae4d0d9bd519ee5ef

# Description
Tesla energy relays have illegal research in them.
# Steps to Reproduce
Deconstruct tesla energy relay for illegal research.
# What you Expected
No illegal research in legal nanotrasen tech.
# What Actually Happened
You gain insight into syndicate tech by deconstructing energy relays you developed yourself.
Illegal tech should come from illegal things, not from something you can develop without illegal tech.

**Comment by PrimeDSS13** [comment]
not a bug

**Comment by Exxion** [comment]
You are absolutely correct that it makes no sense but it's probably way too old to get people to agree to change without completely overhauling R&D

**Comment by DamianX** [comment]
This is what the people want
