### ISSUE TITLE
I can't poke bloodbags

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28173]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
72bb1ebe498d87144d8fc7cae4d0d9bd519ee5ef

# Description
Purchase bloodbags from cargo, poke it with my pen. It doesn't poke. Odd!

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/74737391/99724700-9e4a2200-2a79-11eb-8843-523e1806e1b1.png)

Seems fine to me.  I was unable to recreate this.  Were you using a normal pen? @PrimeDSS13

**Comment by PrimeDSS13** [comment]
I think I was using either the pen in box perma, or my PDA pen. I wonder why it wasn't working.
