### ISSUE TITLE
Barrels are modern tabe

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#28178]
I held off on posting this for a while but I think we've had our fill

It's no surprise that the one who added barrels would be @Irradiation 

You can shove any mob into barrels so a little metal can be used to easily neutralize any melee simple mob, since they don't know how to resist out. With riot armor you can use this to solo entire vaults and events with no danger. They've also been growing popular as cage+++ for containing things like roboduck since the duck won't get hit through the bars, they're cheaper than platsteel, and duck doesn't object to being permanently trapped in the barrel

**Comment by DeityLink** [comment]
There should be a size-related limit. Things like robo duck and giant spider queens are definitely too big for barrels, but maybe you could fit 2-3 regular giant spiders in or 10 chicken.

**Comment by ghost** [comment]
Or make them harder to construct. They're pretty funny so maybe lock them behind smithing or something, since people enjoy having them but maybe they're a bit too powerful to be stack-of-metalable (and god knows smithing could use some love).

also if you can convince someone to give you riot armor you probably don't need additional help soloing vaults

**Comment by Kurfursten** [comment]
It may surprise you but simply having full riot armor and a riot shield (or two) isn't enough to solo the rattle bones vault [choosing to fight through instead of the intended way of just not bumping skeletons]... UNLESS you have a barrel. Since you can stack near limitless skeletons inside and this action doesn't take a hand, and it removes about one enemy per second without needing to actually deal damage to it, yes, it is in fact a non-theorycraft factor in terms of trivializing vaults

**Comment by Irradiation** [comment]
As much as it's a meme feature to make a barrel of (Insert mob here), there indeed should probably be a cap on how many things you can shove in there (or size of XYZ). I more or less copied over the code for how Inflatable Shelters work for shoving mobs in there, so I'd have to check if Inflatable Shelters have the same issue of being able to ownzone a bunch of mobs. 

If mobs can't break out of shelters either, then whoever fixes this issue will probably have to fix shelters as well.

**Comment by Irradiation** [comment]
Some brief testing later, simple mobs can break out of shelters, so there's a few ways of doing this:
- Making barrels destructible so mobs can break their way out.
- Setting a mob capacity limit and/or making it so only "player" mobs can be shoved into barrels.

**Comment by ghost** [comment]
I agree with nerfing them so I dunno why this incredibly specific corner case has to be defended so strongly. Making them destructible might be good, though it'd be nice if it could survive a few hits before releasing everything. And frankly, I'm surprised they don't have a mob capacity already, and same for shelters for that matter.

**Comment by Irradiation** [comment]
Shelters tank a few hits before breaking ,so it wouldn't be much of a stretch to apply the same thing to Barrels.

**Comment by Jackreturnswithaveangenace** [comment]
what if we were to fix bugs rather than defining gameplay features as bugs
![open](https://user-images.githubusercontent.com/74394867/99030300-c7296d80-25c8-11eb-8c39-872a9f2ece2a.png)

**Comment by Kurfursten** [comment]
Not sure why you posted this here, but it's great to hear from new contributors. If you want to get started learning about how to fix bugs, feel free to ask around in our Discord. Some good bugs to start with would be some with the Easy Fix tag. There's quite a few you can jump right into here:
https://github.com/vgstation-coders/vgstation13/labels/Easy%20Fix

Honestly, dealing with git is the tougher part. Once you get over that initial hurdle you'll be fixing bugs in no time. I wouldn't worry about fixing this one yourself though, I think Irradiation already commented he has a fix underway.

**Comment by Jackreturnswithaveangenace** [comment]
Thank you for illustrating my point for me in classic Kurfust fashion, I hope to see more quality features from you in future. By the way, there's a link in the post above me, it might be a useful one to examine sometime. If you want to get started learning about how to fix bugs, feel free to ask around in our Discord.

**Comment by DeityLink** [comment]
@Jackreturnswithaveangenace Kurfurst might be passive-aggressive but he has a point. You joined just to tell the people here to get to work on fixing bugs like we're not allowed to also discuss game design for a game that we're all working on as a hobby.

And you paraphrasing him in return also kinda proves his point: if there's a bug you want to see fixed above all else, learn to code in DM like everyone else here did, me included. Also of the 3 thousands issues open, a good chunk are either deprecated, duplicates, or just suggestions or discussions (you know? like the one we're in right now).

So if you want to help but aren't going to code yourself, you can help us trim away deprecated issues, or bring to our attention ones that really ruin your experience playing the game. Either would be more useful to everyone than just coming in an unrelated feature discussion just to yell at coders to get back at fixing bugs like you're on some sort of high horse.

**Comment by Kurfursten** [comment]
@Jackreturnswithaveangenace If you'd like incentivization to get into bug fixing, I will double all your bug fixes for the next week (until end of day November 20). That is to say, for every bug you fix, I'll fix two. That's a good deal! Now stop being easily offended and be the change you want to see in the world.

**Comment by Zth--** [comment]
Giving the ability to escape from containers seems like the correct approach. 

Being able to put big mobs inside those containers sounds dumb, so maybe that shouldn't be allowed

**Comment by Kammerjunk** [comment]
a historic thread for "c\*ders don't understand why people call them c\*ders"
