### ISSUE TITLE
double barrel shotgun sprite error

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28187]
(WEB REPORT BY: generalapathy REMOTE: 206.221.180.138:7777)
# Revision
c2b50c04da7af68785d08a79730e1ac0eab58fd2

# Description
when you make the bar shotgun a sawn off, and then reload it, the sprite becomes the regular model. 
# Steps to Reproduce
saw off the gun with any saw and then load the shells, i only tried it with beanbag shells so that might be it
# What you Expected
the sprite not to change
# What Actually Happened
the shotgun barrel grew three inches that day.

**Comment by SonixApache** [comment]
![image](https://user-images.githubusercontent.com/8468269/99183011-18f10580-2739-11eb-81d1-ec4b334fe8fb.png)
reproduced
