### ISSUE TITLE
Pipe endcaps appear detached from pipes

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#28196]
#### Description of issue
Pipe caps connected to pipes don't appear connected. Literally unplayable.

#### Steps to reproduce
- Be spessman
- Make pipe
- Make pipe cap
- Observe

#### Specific information for locating
![image](https://user-images.githubusercontent.com/6307265/99249324-380b9800-280a-11eb-9bb1-51a95c7b4fe5.png)

#### Length of time in which bug has been known to occur
idk

**Comment by DeityLink** [comment]
Yeah apparently they don't just appear un-connected, they aren't connected at all.

**Comment by DeityLink** [comment]
I'm expecting it to have been the case ever since multi-layer manifolds were introduced.
