### ISSUE TITLE
Windoors are semi-passable.

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#2820]
If you approach a windoor from the turf it's on, you pass through it onto the other side.

**Comment by Probe1** [comment]
There's a lot of that going around on the derelict.  I noticed if you deleted a rtable in dreammaker the windoor could be passed over without using it.

**Comment by d3athrow** [comment]
I can't reproduce.

**Comment by wwjnc** [comment]
Works with disposals' windoor, latest commit. http://a.pomf.se/msolvm.webm

**Comment by ComicIronic** [comment]
This is happening with or without access.

**Comment by Probe1** [comment]
can be reproduced by deleting an rtable http://i.4cdn.org/vg/1423264416891.webm
that square room on the derelicts always been buggy and probably not related but still the same issue http://i.4cdn.org/vg/1423264080188.png

**Comment by wwjnc** [comment]
Derelicts' fucked up windoors have nothing to do with this, those are a map issue.

**Comment by d3athrow** [comment]
This is due to a byond issue, upgrade to latest 507.
