### ISSUE TITLE
items in cigarette packs turn into cigarettes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28205]
(WEB REPORT BY: suchai REMOTE: 206.221.180.138:7777)
# Revision
4d39eee036c0748872a4ba26f8d069018a05fc0f

# Description
so if you put your lighter into cigarette pack, (tested only for new ones, this would be NT classics) and then use the function of - targetting mouth and clicking on self with pack, the lighter will be turned into cigarette and put on the mask slot instead.
# Steps to Reproduce
take any cigarette out of pack, put lighter in, target mouth, help intent, click self with pack
# What you Expected
to not turn my lighter into the cigarette
# What Actually Happened
exactly that huff.

**Comment by SonixApache** [comment]
known issue, simple shitcode, left in because of memes
might be time to destroy this meme
