### ISSUE TITLE
secure windoors STILL start open

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28208]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
c873c95f926331c9b7f74e32c5bce58e61569ca5

# Description
round starts
window is open
window should be closed
fix it already

**Comment by SonixApache** [comment]
i spent a few hours looking into it and couldn't find a fucking thing
yet now someone's saying that it's real
i don't get it

**Comment by ghost** [comment]
reopened for further investigation on behest of sonix

**Comment by Dacendeth** [comment]
I always see it on box, with the courtroom and all the other ones in sec. Just a shot in the dark but maybe brig cell timers are somehow forcing all the ones near them open somehow, since they do that for cell windoors?

**Comment by SonixApache** [comment]
It happened today,  during the round that lasted from 8:20 AM till 10:34 AM.
The round started with 5 people, and ended with 13.

**Comment by DamianX** [comment]
Do you know if they are open before the game starts, during the pre-game lobby? Observers can check

**Comment by SonixApache** [comment]
Haven't checked, will try to find out.
Event happened again on the round that started at ~ 4:56 PM.
