### ISSUE TITLE
Plasmaman Mechanic no suit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28210]
(WEB REPORT BY: aquz REMOTE: 206.221.180.138:7777)
# Revision
c873c95f926331c9b7f74e32c5bce58e61569ca5

# Description
You do not start with a plasmaman suit if you choose machanic job
# Steps to Reproduce

Choose plasmaman and the job mechanic
# What you Expected
start with a suit
# What Actually Happened
no suit

**Comment by DamianX** [comment]
fixed
