### ISSUE TITLE
Beneficial Virus Order Runtimes (Impossible to Complete)

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#28216]
@DeityLink 
Caused due to L158 of orders_medical.dm

Attempts to total badness, but badness is a text string (e.g.: it might be `"0"` instead of `0`). Cannot add 0+="0".

Due to this runtime, the order cannot be completed.

**Comment by DeityLink** [comment]
Incidentally the Harmful Virus is impossible to complete as well.

**Comment by AbsalomAchitophel526** [comment]
Hate to be that guy but I am 99% sure this exact same bug applies to the GNA disks and Vaccine antibodies requests as well as they cannot be completed atm

**Comment by DeityLink** [comment]
Not the same bug. those orders don't require checks of the "badness" var. If you've confirmed that those orders don't work (and are certain they were shipped in a crate, in case of doubt carry them yourself in a crate to the escape shuttle) then please open a new issue @AbsalomAchitophel526 .
