### ISSUE TITLE
VENDING MACHINES FUCK MATTS

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28237]
(WEB REPORT BY: mrflarg REMOTE: 206.221.180.138:7777)
# Revision
4aceb2a7faad1327f7209c36a38dc84b8f191004

# Description
have 30 stacks of 50 sheet plasma glas, put em in the vendor, it now reads as 30 sheets, vend it you only get 30 sheets.

# Steps to Reproduce
do as I said
# What you Expected
30 sheets that could be sold that are made up of 50 stacks
# What Actually Happened
30 sheets

**Comment by Exxion** [comment]
#28238-#28241
