### ISSUE TITLE
why cult 3.0 sucks part 69

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28236]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
4aceb2a7faad1327f7209c36a38dc84b8f191004

# Description
Convert cult into target
# Steps to Reproduce
Convert someone to cult as the last conversion before the sacrifice act
# What you Expected
I expected literally anyone but me to be the sacrifice
# What Actually Happened
I became the sacrifice while being a member of the cult, and thus everyone was eating my ass as a result

**Comment by TGFH** [comment]
Nar-Sie likes to play tricks on the faithful.

**Comment by Killette2** [comment]
Sounds like a good thing more than a bad. You can even become a sword if they're nice enough to sac you with a gemstone in the sword

**Comment by tayachiya** [comment]
Makes sense imo. You already want the entire world to burn, no difference if you're a soul or a humie when it happens

**Comment by SGuivenne** [comment]
Sucks to be you I guess.  Get saccing bro.

**Comment by DamianX** [comment]
If there are no implanted dudes, anyone can chosen as the sacrifice. Feature!
