### ISSUE TITLE
The commands tab has made a return for the AI

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2824]
![not again](https://cloud.githubusercontent.com/assets/7538670/6071875/d6c2f19e-ad92-11e4-841f-72e79e1779e2.png)
Please remove the robot commands tab too while you are there since it's also useless

**Comment by d3athrow** [comment]
What's wrong with the commands tab?

**Comment by Konater** [comment]
There's already an AI commands tab

**Comment by d3athrow** [comment]
ah, right.
