### ISSUE TITLE
Packed Station: shocked grill wires bad

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28248]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
a883c2efe3f6c6de904ece329b0f465f569df46f

# Description
shocked grills have fucked up wiring leading to the station powernet being all retarded.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
We may never know what he meant by this

**Comment by Armadingus** [comment]
He meant that some wire knots in these locations are not connected properly and leaves the station without power, it's pretty serious.
![image](https://user-images.githubusercontent.com/55976761/99978330-1b410880-2da6-11eb-85e6-331677632850.png)
![image](https://user-images.githubusercontent.com/55976761/99978429-3ad83100-2da6-11eb-8646-e20781e9a15b.png)
