### ISSUE TITLE
GNA Disks and Antigen Vaccine requests unable to be completed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28251]
(WEB REPORT BY: doomergloomer REMOTE: 206.221.180.138:7777)
# Revision
a883c2efe3f6c6de904ece329b0f465f569df46f

# Description

The CentCom request for GNA disks and Vaccine's cannot be completed

# Steps to Reproduce

1.  Get CentCom request for either GNA disks or Vaccine
2.  Load requested items on a crate
3.  Ship to CentCom

# What you Expected

For requests to be accepted.

# What Actually Happened

They were not.

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/100024801-caea9a80-2de7-11eb-8bb4-88dbaaf662d9.png)

BRUH...

**Comment by DeityLink** [comment]
Well that explains why the vaccine order doesn't work but not the GNA disk one, alright I'll try to reproduce it.

**Comment by DeityLink** [comment]
Well I tested the GNA Disk order twice and it failed the first time without any runtimes, but the second time after adding some commentary in the code it worked just fine so I just don't know anymore...
