### ISSUE TITLE
Masks for Snaxi

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#28274]
Keep the cold off your face - we need ski masks on Snaxi

**Comment by PrimeDSS13** [comment]
this is 100% correct you literally cannot protect yourself from the cold fully without it
theres also a huge lack of gas masks and fire stuff due to the lack of maint, so it's hard to find them currently.

also I think scarves are cooler than ski masks

**Comment by Dacendeth** [comment]
dont we have balaclavas in the hat vendor?
