### ISSUE TITLE
Merge all kitchen appliances into one big range.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#2827]
They take up too much space than what they deserve. Consolidate all the actions into one appliance that can be can be easily handled by one sprite with separate overlays. I'll even sprite a 64x64 sprite + overlays if someone does this.

**Comment by Probe1** [comment]
ALL is a little too much but I agree with what we talked about and strongly believe what I said about combining the snackbar maker and condiment maker into one machine should be done.  In the kitchen we have:

1. Microwave
2. Grill
3. Oven
4. Deepfryer
5. Cereal Maker
6. Candy Maker
7. Food Processor
8. Ice Cream Maker
9. Condiment Maker
10. Snackbar Maker
11. Gibber

That's eleven unique machines.  Next door the bartender has 1.  Medbay has 16 by comparison.  Medbay.  

I think the redundant machines need combined but  one appliance is a bit too far.

1. Combine ice cream and candy makers (ice cream has a great UI by the way)
2. Combine condiment and snack makers
3. Combine oven and cereal makers.
4.  Combine grill and oven.
