### ISSUE TITLE
Plasma does not react with Oxygen anymore

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#28278]
## Description of issue
It's impossible to obtain Dexalin anymore, because Plasma and Oxygen do not react.

#### Steps to reproduce

1. Get a beaker with 5u of Plasma
2. Add Oxygen to it
3.
![image](https://user-images.githubusercontent.com/22218882/100565647-5f5f6c00-32c4-11eb-82a8-52a5a7e4488e.png)

#### Length of time in which bug has been known to occur

Noticed it just this round

#### Server revision
1a849f32ca9dbb9ed92d7512cf6c7d8624332aa6

**Comment by Kurfursten** [comment]
Something funky that round it seems, works again (even made by the same guy)
