### ISSUE TITLE
Bundle quintupled itself

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28282]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
5ae5cb4e8630ea08b88156067a40827a19de69a2

# Description
Purchased a syndicate bundle, got emags and glue except I got 5 boxes of said emags and clue bundle. Got told to bug report.
# Steps to Reproduce
Buy bundle

# What you Expected
One bundle that contains a box of emags and glue
# What Actually Happened
Got one bundle that contains 5 boxes of emags and glue

**Comment by BomberBro** [comment]
Not a bug #16369 it's just supposed to be a rare bundle
