### ISSUE TITLE
The frozen core makes Snowmap hell

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#28293]
The hall around engineering is consistently below 0 because even just walking into that abomination causes the entire substation to become an industrial meat freezer. Actually leaving the doors open for any appreciable amount of time nearly instantly conks anybody in the substation out before firelocks start to matter and kills them through jackets with hypothermia. 

Heating back up the area is nearly impossible too unless you set it on fire, I watched the best and brightest minds in engineering take 20 minutes to turn a -150 C hallway into -50 C, which is still enough to kill somebody without gear. If something so catastrophic is mapped in like this it really should have more security than a couple of doors and a "Do Not Enter" sign, I'm tired of a third of the station keeling over and dying because the door was left open.

**Comment by DeityLink** [comment]
I've never actually played on snowmap or really looked at it but isn't there like a vacuum chamber to prevent that from happening? It should be an airlock like the one on box roid outposts, where both doors can't be open at the same time and the air gets cycled out.

**Comment by PrimeDSS13** [comment]
I'm gonna try and make it more secure tonight.

**Comment by Kurfursten** [comment]
While this post has a lot of hyperbole, I don't think it would hurt to increase the power of the VESTA heaters and put a couple more in engineering specifically. Particularly inside that transition room.

Another option would be to not have a direct path into the Frozen Core - if you had a normal snow room between like passing through a short cave room, the ultracold would not be able to spread.

**Comment by TGFH** [comment]
This forces a shuttlecall. It's a feature.
