### ISSUE TITLE
Mechanic machine don't link to the bluespace bin network

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28298]
(WEB REPORT BY: koshachyamyata REMOTE: 206.221.180.138:7777)
# Revision
a7a925b91f1bdc17b29b416b33320e3b478fbc52

# Description
Even if you put bluespace bins into the mechanic machines they still will reqauire resources put in 
# Steps to Reproduce
Add bluespace bins to general fab or flatpack machine
# What you Expected
Flatpacks unlimited
# What Actually Happened
Begging for mats

**Comment by SonixApache** [comment]
something something plastic

**Comment by PrimeDSS13** [comment]
I think they dont display the materials but they're in there, but I'm not 100% sure. I'd have to test it.
