### ISSUE TITLE
Plasmamen runtime when gibbed

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#28304]
When a plasmaman is gibbed, its head is removed correctly, but the body turns invisible and stays dense indefinitely.

I have no idea if it's possible to end up in a scenario where the invisible and uninteractible plasmaman has a player in control of it. Its head is detached right before it turns invisible and uninteractible, so any player in it at the time is kicked out, and the head cannot be reattached because the plasmaman is uninteractible. My best idea for doing it is taking a headless plasmaman, having someone start the surgery to attach a head, having someone else start the process of defibbing the corpse, then having someone else somehow gib the corpse before the two progress bars finish, with it timed such that the head attachment finishes before the defib. I don't know if this would work, but it's all I can think of.
I really want to see someone pull this off on live without admin intervention. This method or any other you can think of. Please. I'm begging you.

**Comment by Irradiation** [comment]
IT HAPPENED AGAIN, AAAAAAAAAAAAAAAH.

**Comment by ShiftyRail** [comment]
A reliable way to do it is to gib yourself with a rubber ducky.

**Comment by Exxion** [comment]
Yes, it happens literally every time a plasmaman is gibbed by any means whatsoever
