### ISSUE TITLE
Swiss army knife screwdrivers getting yoinked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28305]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
c6647ec5c221097d74e3efaa5e5ba05c3316678b

# Description
Sometimes the screwdriver in the swiss army knife comes out for reasons I don't really understand and cannot be put back.

# Steps to Reproduce
1. Deploy swiss army knife screwdriver
2. With the screwdriver deployed click on a container garment like webbing
3. Sometimes this makes a click noise and the SCREWDRIVER is placed in the pocket, but the knife stays in your hand

# What you Expected
To place the entire tool in my pocket

# What Actually Happened
Jeff Bezos would not refund my $50 swiss army knife purchase after the screwdriver fell out.

**Comment by DrSnips** [comment]
Funny stuff. You know what's likely happening here? The screwdriver is likely doing some jank interactions with wthe switchtool and removing modules from the tool since screwdrivering the tool is how you remove things.

**Comment by Dacendeth** [comment]
these things are busted in other ways too, clicking a table with the tool put makes you put the deployed tool on the table
