### ISSUE TITLE
Snaxi Shuttle Base Lacks Fire Alarms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28325]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
9c11db3ad5517d57df1c857ab5486f04c18f7e12

# Description
the central base where the shuttles dock to doesn't have a single fire alarm

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by jjpark-kb** [comment]
![image](https://user-images.githubusercontent.com/55967837/101427557-1b282900-38cd-11eb-811f-4114449a5818.png)

**Comment by west3436** [comment]
I was referring to the place where you spawn if you're a late-joiner which is off z1
