### ISSUE TITLE
The Grinch Stole My Soul

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28326]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
9c11db3ad5517d57df1c857ab5486f04c18f7e12

# Description

Applied to be Grinch, it runtimed repeatedly, Chaz decided to triple down. When selected my Character name changed, and I went from a ghost to a naked ghost, instead of becoming the Grinch.
# Steps to Reproduce

Sign up for Grinch, be selected for grinch, cease to be you and be someone elses naked ghost
# What you Expected

To be grinch
# What Actually Happened

I'm now a ghost, but a different one, and not even the ghost of Christmas Past, Present, or Future.

**Comment by DeityLink** [comment]
https://www.youtube.com/watch?v=BuKft9LpL_0

**Comment by ShiftyRail** [comment]
It's probably on a map without a dedicated grinch spawn (snaxi, synergy, etc.)
