### ISSUE TITLE
Changing identity is fucky

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#28329]
#### Steps to reproduce
- Change a monkey into a human
- Its name will remain "unknown" until a piece of clothing is equipped by them

OR

- Inject self with UI+UE of someone else while wearing a mask
- Keep the same identity
- Or something? I don't know, it's confusing.

#### Specific information for locating
#28233 did this, I'm sure
@Zth--

**Comment by Sooose** [comment]
Also, fixing someone's face doesn't actually fix their unknown status.

**Comment by PrimeDSS13** [comment]
say you have a balaclava on and your ID on, it says it's you
take your ID off, it still shows your identity
take your balaclava off and put it back on again, you are now unknown.

something is fucky

**Comment by Zth--** [comment]
The name used to get updated on Life(), so instead of updating the name when it should (for example when you remove or put some piece of clothing), it was doing it every single tick. That's lazy shitcode. Another reason I had to remove it was to add proper unit tests.

I'll fix it

**Comment by PavelCIA** [comment]
FIIIIIIIIIIIIIIIIIX IT
