### ISSUE TITLE
getting zas'd into supermatter doesnt kill you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28336]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
9adf6be7302d5955dae2d71daa69288a6dd7b006

Larry Burns slams into a Supermatter Shard!

**Comment by Zth--** [comment]
#27642

**Comment by DamianX** [comment]
Duplicate of #27642
