### ISSUE TITLE
Bear traps disarming bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28343]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
9adf6be7302d5955dae2d71daa69288a6dd7b006

# Description
Bear traps don't disarm if you click them with an object. You have to throw object on them.
You carefully set the bear trap off with the pickaxe x6
# Steps to Reproduce
Buy/Steal/Make bear trap
Set it
Click it with an object in hand.
# What you Expected
Disarmed bear trap
# What Actually Happened
Armed bear trap

**Comment by Dacendeth** [comment]
they do disarm the sprite just doesn't properly update
