### ISSUE TITLE
Wires partially layering above uniform

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#28350]
#### Description of issue

![dreamseeker_2020-12-10_00-35-15](https://user-images.githubusercontent.com/8468269/101726303-8da62e00-3ab2-11eb-93c8-0f5741d0d4e0.png)
there's wires on my pants

**Comment by DeityLink** [comment]
Isn't there just a space between your legs DUH ?

**Comment by Exxion** [comment]
dude...
