### ISSUE TITLE
You can't deconstruct a lot of stuff

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#2835]
Making expanded or conjoined rooms pretty ugly without admin intervention or a good bombing first

Examples:
-Lightswitches
-Newscasters
-Those computers which message other departments
-Firelocks
-ATMs
-Sinks and showers

**Comment by 9600bauds** [comment]
-Hazard Shuttles

**Comment by Kurfursten** [comment]
Lightswitch: screwdriver, wirecutter, crowbar.
Windoors: use crowbar while open

I'll work on the others

**Comment by gbasood** [comment]
no one's working on this currently, not sure what all has been fulfilled from this list if at all
