### ISSUE TITLE
Snaxi RnD servers overheat by themselves

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#28376]
![Untitled](https://user-images.githubusercontent.com/55976761/102071454-c884ca80-3e00-11eb-89eb-2c8e6ebb34c6.png)
There are two vents under those servers, they are set to cycle air in and out of the room and into the freezer. This isn't effective for cooling the servers and causes them to die out and research levels will keep being reset because of that.
Also the RD office is missing a stamp, a head's stamp is the cornerstone of HRP decor and decorum.

**Comment by Kurfursten** [comment]
It did take about 2 hours for this to happen

Also, you should be able to solder servers to repair them, feature request
