### ISSUE TITLE
[Say] Changelings cant be heard by ghosts

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2838]
As far as I have seen changelings cant be heard by ghosts at the moment. 

This MAY apply to other special role chats as well like cultist chat but I haven't yet seen them in play enough to have any verification.

**Comment by ComicIronic** [comment]
Dead ghosts seem to be failing some part of
![This call](http://puu.sh/fz5Bn/782ef5bc4f.png)

**Comment by d3athrow** [comment]
way dm works is if you use x in list && othercheck it will look in the other check, need to seperate them with ()
