### ISSUE TITLE
Disposal bins mess up the floor below them

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#2839]
When something flies out of the disposal bin, the floor turf below the bin changes the sprite to plating
I remember not being able to fix that so it's pretty annoying

Haven't tested this a lot, but this should reproduce the bug:
1) build a ride using disposal pipes with two entry/exit points on naked plating (disposal bins, chutes etc)
2) cover it with floor tiles
3) jump into the ride and when coming out the floor underneath the exit point will break

Looks like this
![](http://puu.sh/fz20b/d8dc93df5b.png)

**Comment by Probe1** [comment]
all you have to do is send something through disposals via cargos tagger and this will occur.  honestly I thought it was a feature because it's fast, reliable and no one can intercept it.
