### ISSUE TITLE
URGENT: Pornospam misspelling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28392]
(WEB REPORT BY: neonmeatdream REMOTE: 206.221.180.138:7777)
# Revision
dcefcc9649e459feb812fb972b48a7b4be76b0f6
# Description
A misspelling of a word in a pornographic advertisement aimed at lewd girls and gay boys.
# Steps to Reproduce
Receive the same pornospam.
# What you Expected
Wetskrell.nt only provides the highest quality of male entertaiment to Nanotrasen Employees.
# What Actually Happened
Wetskrell.nt only provides the higest quality of male entertaiment to Nanotrasen Employees
# Categorical Imperative
Please fix, i'd do it for you, you know.

**Comment by Exxion** [comment]
>i'd do it for you, you know.

You can
