### ISSUE TITLE
light bulbs/tubes break when you click anywhere on the screen

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#28418]
#### Description of issue
bulb in hand
click screen
bulb explodes

also happens when you put them in disposal bins

#### Difference between expected and actual behavior
bulb not explode
vs
bulb explode

#### Steps to reproduce
take bulb / tube in hand
click screen

#### Specific information for locating
some sort of afterattack fuckup? not sure

#### Length of time in which bug has been known to occur
not long, maybe a few weeks

**Comment by toomykins** [comment]
```
// called after an attack with a light item
// shatter light, unless it was an attempt to put it in a light socket
// now only shatter if the intent was harm

/obj/item/weapon/light/afterattack(atom/target, mob/user)
	if(istype(target, /obj/machinery/light))
		return
	if(user.a_intent != I_HURT)
		return

	shatter()
```
shouldn't happen unless you were on harm intent

**Comment by SonixApache** [comment]
I probably was, but shattering lights by crushing them in your hand is pretty whack.
