### ISSUE TITLE
Buncha pAI shit

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#2842]
Sorry if this is too much, but here's a general list of nuisances and stuff I feel would make pAI a generally more fun role, I don't know, scream at me if it's shit.

-PDA messengers are built in, the downloadable one is just slightly nicer. Merge them to be built-in, or just make it so you have to download PDA functionality.

-Door Jack is slow as fuck, alerts the AI, and can't even unbolt doors. I feel as though it should still be slow as fuck and alert the AI, but give accessibilities to door mechanics, at least the ability to unbolt

-Emaggable pAIs, we already got a sprite for it and practically everything a syndie can grab out-does you, even if it's just a mobility function, ANYTHING.

-MedHUD is great, and is arguably the only useful thing pAIs have, but the problem with it is scanning your master. You scan once, get the results, then have to exit back out of it and scan again, it should be more like the atmos scanner where you can just click "Refresh Readings".

-Maybe reformat door jack into just a general hacker, so you could use it on things like APCs or vending machines.

-Have the "Supplemental Directives" change along with an Ion storm like the normal AI does. I've had them changed once during a stray EMP and never again.

-Downloadable for tuning radios to stuff like medbay and sec, with a high cost of course. Standard pAI has a limited range, much like the others standard aboard the station.

That's all I can think of right now.

**Comment by Probe1** [comment]
MedHUD and reformatting doorjacker into a general jacker are both really great ideas.

Same with radio freqs.

**Comment by Kurfursten** [comment]
@clusterfack Almost all of this was actually added. Close this.

**Comment by Ephx1** [comment]
You betcha
