### ISSUE TITLE
Head reattachment still broken, thanks pomf you fuck

### ISSUE THREAD

**Issue by d3athrow** [d3athrow/vgstation13#2843]
When doing head reattachment surgery, when using the hemostat on a corpse it brings up the menu to remove a brain or eyes that dont exist
Also when doing head reattachment surgery on a braindead, it wouldnt count the person as revivable but when i walked in they gasped at me dead

**Comment by SkowronX** [comment]
Oddly when doing chest surgery after sawing the ribcage open, using a retractor opens the organ severing menu.

**Comment by d3athrow** [comment]
its because surgery code is shit

**Comment by SkowronX** [comment]
I beleive this was fixed
