### ISSUE TITLE
Snaxi: Add airless plating under space port docks

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#28461]
An idea I had to reduce this

![image](https://user-images.githubusercontent.com/9782036/103188283-6e1e4c00-488d-11eb-9c1f-e82ce52728fc.png)

How are people not accustomed to ZAS? ALL our other stations take place in space

**Comment by SonixApache** [comment]
a lot of other stations have special little fans that kill ZAS in their spot
