### ISSUE TITLE
Opening slots probably shouldn't be doable infinitely by HoP

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#28466]
![image](https://user-images.githubusercontent.com/6062247/103318577-b94a7300-49e3-11eb-8a53-16031dc1a49e.png)

As funny as it is as a gimmick, this gunked the round to hell and back. Opening one extra slot should be doable, but opening infinite slots should require code rainbow or bus or something, because otherwise you're letting one role (HoP) add a LOAD of chaos to the round.

**Comment by PrimeDSS13** [comment]
just beat up the HoP

**Comment by gurfan** [comment]
no

**Comment by kilozombie** [comment]
> just beat up the HoP

>leaving the brig
>as Warden

**Comment by DeityLink** [comment]
I think it happens rarely enough to just be a fun gimmick when it does.
