### ISSUE TITLE
Captains Winter Coat Transparency Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28465]
(WEB REPORT BY: kromkar REMOTE: 206.221.180.138:7777)
# Revision
06f9c4cf80357e46278925a11e0df99ea6641ffa

# Description

The Captains Winter Coat hem and sleeves are transparent.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
can't see anything anormal
