### ISSUE TITLE
AI on lamprey will die almsot instantly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28475]
(WEB REPORT BY: surrealitarian REMOTE: 206.221.180.138:7777)
the SMES thingy in the AI core on lamprey has no power, and the room has a lotta shit that sucks power, so it'll run out really quickly.

**Comment by Irradiation** [comment]
Good.

**Comment by Dacendeth** [comment]
Good

**Comment by jwhitak** [comment]
Good

**Comment by kilozombie** [comment]
Good

**Comment by SonixApache** [comment]
lamprey should probably just not have an AI slot

**Comment by nervere** [comment]
lol
