### ISSUE TITLE
[Feature Request] MoMMi's cannot lock emitters.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28478]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
f64275876eb305f829d23b86e673a9cc035d4989

# Description
MoMMi's cant lock emitters because they have no IDs. Maybe a verb that checks access would help? Not sure.

**Comment by Dacendeth** [comment]
just steal the captains spare

**Comment by toomykins** [comment]
the emitter lock is only to stop people from tampering with it.
mommis arent supposed to stop people from tampering with it.
