### ISSUE TITLE
"Unique" holograms are all just bald men

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28489]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
5057df2a3e212bf47ab66f123eed41a7a7eabd3c

# Description
They aren't unique, they're all the same.

**Comment by SonixApache** [comment]
#21492

**Comment by xeroxemnas** [comment]
Bald men, running the world, a new age.
