### ISSUE TITLE
[Feature Request] Setting cult to NEVER forces you to observe the round if cult fires. 

### ISSUE THREAD

**Issue by drawsstuff** [d3athrow/vgstation13#28491]
Until this is added I will be committing suicide every single time cult gets called out and I'm an officer. There is no winning play in cult for an officer than to not play at all.

I'm not joking. I mean it.

**Comment by ghost** [comment]
lol?

**Comment by toomykins** [comment]
salt

**Comment by Cieyl92** [comment]
That seems a little extreme. Cult can be fun if both sides choose to roleplay a little bit and avoid the "meta" options for dealing with each other.

**Comment by drawsstuff** [comment]
> That seems a little extreme. Cult can be fun if both sides choose to roleplay a little bit and avoid the "meta" options for dealing with each other.

I have never had fun on a cult round when I was not a cultist

**Comment by Exxion** [comment]
>Cult can be fun if both sides choose to roleplay a little bit and avoid the "meta" options for dealing with each other.

Cult can be fun if [thing that never happens]

**Comment by APCUnlocked** [comment]
lol

Just don't play security then, don't need no pansies who quit when the going gets rough.

**Comment by drawsstuff** [comment]
i would, I like stomping out cultists, its just every time I do i get the same little whiney shitstains making ban reqs on me. sending me weird messages for 4 months over byond messanger, and throwing a tantrum in discord after the fact

**Comment by BomberBro** [comment]
this doesn't sound like a code issue

**Comment by cloutcode** [comment]
it is a code issue because cult is still in the game

**Comment by ghost** [comment]
Hoes mad


Hoes mad

**Comment by toomykins** [comment]
as a seccie you have nothing to complain about, it's basically your free-card to doubt the motives of anyone on the station, imprison them and implant them.
It's often the case that cult is utterly defeated purely because the players don't understand the mechanics.
if you're being haunted and meta'd by salty players i'd say just make a player thread about them on forums.

**Comment by PJB3005** [comment]
Yo I was playing CMO yesterday and captain called out that there was a cult.

I checked viro, called sec, and one minute later all of sec was rolling into viro with mechs. Destroyed.

Then I chloral'd everybody else in medbay to check if they were cult and paramedic sure fucking was.

All I'm saying is playing counter cult can be fun alright?

**Comment by Kammerjunk** [comment]
I support this idea.

**Comment by APCUnlocked** [comment]
> i would, I like stomping out cultists, its just every time I do i get the same little whiney shitstains making ban reqs on me. sending me weird messages for 4 months over byond messanger, and throwing a tantrum in discord after the fact

I've not had such problems and making the 40-player manifest into a 20 player manifest is not going to stop autists from being autistic.

**Comment by DoomerGloomer** [comment]
>cult round fires
>every one except cultists auto-observe due to setting Cult: Never
>roundstart pop of 3 starting cultists, an AI, and twenty ghosts

**Comment by SonixApache** [comment]
i am not as much of a powergay, but i've had plenty of fun blasting my way through cult rounds as sec
sounds like a personal problem tbh

**Comment by drawsstuff** [comment]
> i am not as much of a powergay, but i've had plenty of fun blasting my way through cult rounds as sec
> sounds like a personal problem tbh

then what's the problem with having this be an option? If I don't want to play a cult round, which is a very valid thing to want shared by many people in opinion, I should have the option

**Comment by SonixApache** [comment]
just end yourself and take the tempban when you do it too often

**Comment by Kammerjunk** [comment]
@DoomerGloomer dang maybe that happening would be pretty indicative of the mode

**Comment by DeityLink** [comment]
Here's another idea, disable cult altogether until I re-enable it after making all the changes I want to bring to the role.

This idea if implemented would just increase resentment against cult for increasingly memetic reasons and I just can't deal with that anymore.


>  @drawsstuff 
> 
> > That seems a little extreme. Cult can be fun if both sides choose to roleplay a little bit and avoid the "meta" options for dealing with each other.
> 
> I have never had fun on a cult round when I was not a cultist

Would you not just log off then if you were forced to observe a cult round then?

**Comment by xeroxemnas** [comment]
I'm fine with Deity's suggestion. As it stands the ability for people to box themselves ruins the game mode and makes cult a fucking miserable experience to play.

**Comment by PJB3005** [comment]
\>try to convert sec officer who just got cloned
\>perfect crime: no SPS, excuse for missing loyalty implant
\>the sec officer gets turned into a box and I now have to explain where he went 

not great, sadly.

**Comment by calzilla1** [comment]
On one hand I find blitzkrieging though team antags to be an enjoyable, soothing experience. On the other, less femsec.

**Comment by DeityLink** [comment]
@drawsstuff Have the removal of boxing and other changes done over the past few months including the re-addition of deconversions alleviated your suffering of cult rounds?
