### ISSUE TITLE
ALERT! Revert SPS noises

### ISSUE THREAD

**Issue by 49bluesun** [d3athrow/vgstation13#28494]
Idea simple. Re-insert the myraid of Civil Protection death cues and soundclips from Half Life 2 that would trigger upon the death of an active SPS holder. These were removed from player use and enjoyment after a certain change happened that led to the existence of the 'Security Alerts Computer'. I am **not** asking to reset and revert that. Mechanically, the current SPS system can stay the same, and we can just keep dropping a handheld radio in front of that computer tuned to the Sec frequency roundstart like nothing happened. My only hope is that the current, soulless alert noise dropped in as a placeholder be utterly ripped out, and replaced with our old Combine Overwatch noises.

I have no coding experience, at all. This is merely the humble, uneducated plea of a backwoods burger. If a majority approves of this and the emojiocracy shows favor, the likely way forward is someone who actually handles the code to **GENEROUSLY** lend their time to restore this, instead of this junk I wrote up in an attempt to raise awareness. I don't know, this is my first time using this. But I swore an oath that I would refuse to play security until this was fixed

Also, we have like, **actual** Civil Protection armor in the game now, so it confuses me how this issue remains. What's there to lose? Discuss, or show approval

**Comment by Dacendeth** [comment]
What like if the person wearing the armor dies it plays the sound at their location?

**Comment by drawsstuff** [comment]
bring it back, being in the bar talking to an officer and then you hear [KRRRRRRRRRRRRRRRRRRRRR] and they shit their pants was the funniest fucking thing

**Comment by 49bluesun** [comment]
> What like if the person wearing the armor dies it plays the sound at their location?

I had that thought earlier. We've got HL1 scientist screams for any nerds wearing science coats, and switched the pain screams for anyone wearing standard security armor vests as well. Both are amazing and I honestly would be okay if that happened to this as well. We just had this setup with the SPS's first, which existed for longer than I messed around in the serb, so it's what stuck to my mind

**Comment by cloutcode** [comment]
> What like if the person wearing the armor dies it plays the sound at their location?

bring this back i want the death knell to return please

**Comment by SonixApache** [comment]
barry has done some outfit-based sound changes, i'm sure it wouldn't be too hard to add that horrible loud noise back as long as someone is wearing the CP gear
the issue that i shared with some others regarding the CP screams was that they were annoyingly loud and always felt out of place, the radio bloop was aimed to fix that

**Comment by APCUnlocked** [comment]
Could just tone down the volume? I can't speak for everybody here but for me the sound was very iconic and whatever assumed ear-rape was gotten rid of, the void in my heart is still there, waiting to be filled.

**Comment by juanototo2** [comment]
M8 half the reason the SPS noise was good was precisely BECAUSE it was horribly loud. Seeing effectively everyone involved shit their pants when they hear the sound was hilarious.

**Comment by SonixApache** [comment]
the SPS started with not having a noise, celt's horrible noise spaghetti was an unwelcome addition

**Comment by 49bluesun** [comment]
So far, at least a few people expressed their joy at the idea of the the return of the sounds. And by contract, we have  one voice in the minority. Glad to see words and not just emoji votes

It was VERY loud yes, no lie there. That never bothered me since I loved it, but something I noticed is that the current alert noise, with how much shorter and passive it was, is that some sec may just ignore or miss it, especially if the chatbox is moving fast enough. The old HL2 gave a long, unmistakable noise that couldn't be missed; it instilled security with both **excitement** and **fear**, but more importantly gave a sense of **urgency**. At least this is how I felt looking at the behavior of others

**Comment by 49bluesun** [comment]
Closing this since we have an actual coder working on this now as this was my idiot savant attempt at raising awareness, that worked. Well done all
#28509
