### ISSUE TITLE
Bigger z-level for box

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2850]
It would be nice if box had more room at escape to build space forts, as it is possibly the smallest area from escape to another z-level in space tiles. There is currently some room, but it is nice to expand until you are past the shuttle so lighting features do not happen.

**Comment by ComicIronic** [comment]
You shouldn't be building out of escape anyways. It's a terrible idea, both ingame and from a code perspective.

**Comment by Killette2** [comment]
When doing so I try to make sure to build past the shuttle, which is why there isn't much room on box station for this.

**Comment by SarahJohnson489** [comment]
Buttload of area to the corners of the map. You can put a whole dept and some in it.

**Comment by clusterfack** [comment]
The problem is the only main hallways that go to an area near space are arrivals and escape. I think all the maps have this problem really.

**Comment by CptWad** [comment]
#8064

**Comment by 9600bauds** [comment]
Addressed
