### ISSUE TITLE
Metaclub brig has no forensics computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28508]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
e58ba5441ba541e0beb1b73c9f435c40e38f836b

# Description
Metaclub's brig is so bad it's completely missing even a single forensics computer
# Steps to Reproduce
Play metaclub
Be Horatio Caine

# What you Expected
Using the power of DNA to catch bad guys
# What Actually Happened

Weeping in a corner because your scanner is useless

**Comment by SonixApache** [comment]
![image](https://user-images.githubusercontent.com/8468269/103612408-a88a8780-4f24-11eb-9eb5-2f50ac9ff653.png)
local man gets trolled and/or is blind
