### ISSUE TITLE
Double Captains rig on some (all?) maps

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#28518]
The captains rig armor is in his locker and some maps if not all of them also have a Rigsuit storage unit with it inside as well. The armor should probably be removed from the locker and every map without a rigsuit storange unit should get one. 

Box is the only map I know of 100% where two spawn but im sure others do too.

**Comment by Blithering** [comment]
Pretty much all maps have this, my guess is it's for captain spare, the mythical figure that also leaves his ID behind wherever he visits.

**Comment by DeityLink** [comment]
Fixed by #30184
