### ISSUE TITLE
Vaults on snaxi sometimes cause most of the emergency shuttle to not actually fly to the station

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#28521]
![snowmapshuttle](https://user-images.githubusercontent.com/51391726/103850265-d8e13b80-5074-11eb-9c53-0c6ae16d773b.PNG)

bravo nolan

**Comment by Kharkov72** [comment]
why the h*ck are vaults spawning there

**Comment by Kurfursten** [comment]
duplicate of https://github.com/vgstation-coders/vgstation13/issues/24967
