### ISSUE TITLE
Catbeast Language Doesn't Work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28535]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
f2267c0f3fdf6056f6d3a2ee2ee892e088c6ab77

# Description
talking with the :% preface doesn't work
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ShiftyRail** [comment]
That's because `:%` is already here for insectoids.
