### ISSUE TITLE
Amorphous Masks when turning the player into headcrab zombies make immortal zombies when killed and ghost the player, the immortal zombies create insane infinite lag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28539]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
81b84a0e2ef9b7569516aa9ac5608e7eca107b5b

# Description
See title
# Steps to Reproduce
Get a transforming mask that turns you into a headcrab zombie
# What you Expected
To revive as a zombie or drop dead 
# What Actually Happened
the zombie lived and I was ghosted

**Comment by drawsstuff** [comment]
This bug is multi-layered, I'll post a recording when the round is over

**Comment by drawsstuff** [comment]
https://files.catbox.moe/789ez2.mp4

**Comment by drawsstuff** [comment]
![unknown](https://user-images.githubusercontent.com/16404218/104105709-fd5c3400-527d-11eb-99f7-ead18703db8b.png)

Lag got so bad it forced a restart

**Comment by DrSnips** [comment]
I felt like headcrabs would lead to issues but I didn't expect something like this to happen nor literally server ending

**Comment by gurfan** [comment]
what in the fuck
