### ISSUE TITLE
Mininig shuttle breaks on starscreen shield on Box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28534]
(WEB REPORT BY: ezudiko REMOTE: 206.221.180.138:7777)
# Revision
f2267c0f3fdf6056f6d3a2ee2ee892e088c6ab77

# Description
Mining shuttle breaks into pieces because of the starscreen shield, stating it doesn't have destroy_allowed=1 or whatever
# Steps to Reproduce
1.Build a starscreen around the station
2.Send the mining shuttle back to the station

# What you Expected
The shuttle to arrive
# What Actually Happened
The shuttle broke into pieces

**Comment by Exxion** [comment]
Surprisingly enough, it actually *was* the cluwne, not the shield.
#28533
Or potentially a combination of the two, but the cluwne was definitely involved
