### ISSUE TITLE
Lazarus monsters attacking after you morph into their owner

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28547]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
81b84a0e2ef9b7569516aa9ac5608e7eca107b5b

# Description
Kill miner with lazarus capsules. Morph into them. Throw capsules. Monsters hostile to you
# Steps to Reproduce
Morph into someone with lazarus capsules and throw them
# What you Expected
Monsters friendly to me after I morphed into their previous master
# What Actually Happened
Monsters hostile to me after I morphed into their previous master because they're tied to CKEY.

**Comment by DeityLink** [comment]
not to the ckey, but to their owner's mob. mind-swapping would work, otherwise they smell that you aren't their real owner.
