### ISSUE TITLE
Cannot build borgs on Castle

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#28544]
*due to a runtime error.

Because castle physically deletes the cyborg job (apparently??) the borg construction code nullrefs on this check:

https://github.com/vgstation-coders/vgstation13/blob/81b84a0e2ef9b7569516aa9ac5608e7eca107b5b/code/game/objects/items/robot/robot_parts.dm#L204-L207

**Comment by PrimeDSS13** [comment]
feature

**Comment by d3athrow** [comment]
@boy2mantwicethefam  thanks

**Comment by boy2mantwicethefam** [comment]
I didn't touch this so not my problem, lol

**Comment by BomberBro** [comment]
truly the best map we have
