### ISSUE TITLE
Vox Raiders does not work on Snow Taxi

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#28549]
[snowmap]

The shuttle can spawn when the gamemode is called, but it only has three destinations. It can't go to any of them, bugging out seemingly due to having no transit space? Even when a transit space was manually added and other shuttle variables were fucked with by an admin, it still didn't work.

Sidenote: Raiders having a timer is pure shit. Just make it a normal gamemode without the cross-round high scores, it's impossible to have a good time in 15 minutes.

**Comment by kernikov** [comment]
> it's impossible to have a good time in 15 minutes.

ur mum disagrees

**Comment by kilozombie** [comment]
> > it's impossible to have a good time in 15 minutes.
> 
> ur mum disagrees

Fuck fuck fuck fuck fuck fuck fuck fuck

I'm not owned I'm not owned I'm not owned I'm not owned
