### ISSUE TITLE
Metal barrels do insane damage when thrown by TK

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#28543]
literally kills people in two throws.

**Comment by Irradiation** [comment]
Looking into this, the same can occur with Anvils. As barrels (and anvils) were designed to have a throw force (so you can throw them if you have Hulk & the Strong gene at the same time), TK lets you disregard the above snowflake requirements and just chuck them and use the high throw force.

tl;dr fuck TK

**Comment by boy2mantwicethefam** [comment]
I warned you about TK #24067

**Comment by Exxion** [comment]
Yes because removing it entirely is a good approach to fixing a couple oversights

**Comment by boy2mantwicethefam** [comment]
Yes

**Comment by Exxion** [comment]
Allow me to direct you to #9579

**Comment by boy2mantwicethefam** [comment]
In all seriousness though TK is incredibly janky and genetic powers overall have been janky and I say this as a former geneticist main
TK is no exception, the default interaction is attack_hand, you can push walls remotely and if you combine it with hulk you can smash them, and if one were to remove this then one would have to comb a ton of stuff just to re-add the lost functionality back to the telekinesis behavior, far more hassle than it's worth

**Comment by Exxion** [comment]
As you just said in a different issue, emergent gameplay

**Comment by boy2mantwicethefam** [comment]
But I did warn you about TK, as the server rapidly falls down a set of infinite stairs, yelling "IT KEEPS HAPPENING"

**Comment by SonixApache** [comment]
just make it so you also need the strong mutation
need a strong mind to throw heavy stuff
