### ISSUE TITLE
Drag Smoke

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28540]
(WEB REPORT BY: kirbythewizard101 REMOTE: 206.221.180.138:7777)
# Revision
81b84a0e2ef9b7569516aa9ac5608e7eca107b5b

# Description
Being able to drag smoke
# Steps to Reproduce
set off a smoke bomb (in this case it's weed killer) and right click drag it
# What you Expected
Not to be able to drag fucking air
# What Actually Happened
watching a plasmeme drag weed killer to kill kudzu

**Comment by ShiftyRail** [comment]
```
/obj/effect/effect/smoke
	name = "smoke"
	icon_state = "smoke"
	opacity = 1
	anchored = 0
```
What
