### ISSUE TITLE
The admin cult confusion button bugs out and blinds players by making their screen all white.

### ISSUE THREAD

**Issue by TGFH** [d3athrow/vgstation13#28568]
#### Description of issue
An admin pushed the confusion button and it blinded all the doctors in medbay. I have seen this happen before some months back but forgot about it until now.

#### Difference between expected and actual behavior
What people expect: Temporary confusion.
What they got: Ray Charles: The experience

#### Steps to reproduce
1. Be admin
2. Push cult confusion button
3. ????

#### Specific information for locating
http://game.ss13.moe/logs/2021/01-January/13-Wednesday.log
[21:01:36]ADMIN: Kernikov/(Jack Clark) spawned /obj/effect/cult_ritual/confusion at (249,280,1)
[21:28:19]SAY: Wayne Schaffer/Naxas (@@224,274,1) As Galactic Common :  after those hallucinations we went blind

#### Length of time in which bug has been known to occur

Idk, a long time. Just disable the button or something.

<administration>

**Comment by ShiftyRail** [comment]
You can fix it by using `clear_fullscreens` in atom proc call.

**Comment by DeityLink** [comment]
There is no such button. Admins can spawn the object itself. It's the same object spawned by the rune, so it's a bug related to the rune itself. I'm trying a few potential fixes.

**Comment by DeityLink** [comment]
Alright I've figured it out. This was caused by the object being tasked to do stuff after being qdel'd (via spawn()). I've changed it so the object only gets deleted after no confused players remain as such.

I'll push it with the conversion/deconversion changes. Should come later today.
