### ISSUE TITLE
MoMMis do not get the noir overlay when they drink Joe / Smoky room

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28573]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
9b3f2061378892849733d45b828dd80efe43e78d

# Description
MoMMis do not get the noir overlay when they drink Joe / Smoky room
# Steps to Reproduce
1. Be a little crab
2. Get drunk
# What you Expected
Hard Boiled Crab Eggs
# What Actually Happened
Soft Boiled Crab Eggs

**Comment by Kurfursten** [comment]
pretty sure the only booze mommis can actually get something out of is electric sheep

**Comment by DeityLink** [comment]
They're made of metal, they're hard boiled enough
