### ISSUE TITLE
some more issues with surgery

### ISSUE THREAD

**Issue by xevonix** [d3athrow/vgstation13#2857]
When the incision management system is used once, the sprite will disappear from existence.
example: http://puu.sh/fALMF/102478769c.png

If you preform a head reattachment surgery on a body that has previously debrained you wont be able to defib them because it still counts them as not having a brain.

When applying hemostat to the head area of a headless person for head reattachment surgery, it will ask if you want to remove the brain or eyes. 
It still allows you to finish the surgery without accepting either of these options.

When preforming organ repair surgery, when you apply a bandage to the chest it will ask what organ you want to remove. It also asks this for the final use of the retractor.
It still allows you to finish the surgery without accepting any of these options.

Not sure if you can actually remove any of the organs with these items.

**Comment by d3athrow** [comment]
Fuck surgery code, seriously
