### ISSUE TITLE
I dont know what happened but custom strike teams spawn in deathsquad gear again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28594]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
87cd93dd816c145ad98be868291bcaad281167b1

# Description
Fixed by #22671 but now seems to not work again
# Steps to Reproduce
click the Send in a Custom Strike Team button

**Comment by SonixApache** [comment]
i can only assume it's related to outfit datums
