### ISSUE TITLE
Null spaced

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28598]
(WEB REPORT BY: wemic82 REMOTE: 206.221.180.138:7777)
# Revision
87cd93dd816c145ad98be868291bcaad281167b1

# Description

# Steps to Reproduce Flaoting in space I guess.

# What you Expected Nothing

# What Actually Happened
I got sucked into nothing

**Comment by toomykins** [comment]
this report was made on Lamprey btw

**Comment by SonixApache** [comment]
powerful and useful report

**Comment by Exxion** [comment]
Information-free
Reopen in the event the reporter provides some detail at all
