### ISSUE TITLE
Mind Projecting clings to dead people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28608]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
e3d4b9d3fa7eabfaa978f06a878c384adf29016c

# Description
See Greyshirt McGriff. Shift+Click, project mind to him.
Greyshirt McGriff dies. Clone him.
Try to project mind to Greyshirt McGriff: Target mind is too faint.
Examine the cloned Greyshirt McGriff, still can't project mind to now living clone, target mind is still too faint.
# Steps to Reproduce
Project mind to guy, kill guy, clone guy, try projecting mind to same guy - target mind is too faint.
# What you Expected
Projecting mind to cloned guy
# What Actually Happened
Target mind is too faint...

**Comment by Killette2** [comment]
I've seen this happen with other byond games too. Usually the first of an object in a world when selected from a menu like this is the one that will always be referenced. If there isn't there would need to be some way to refresh this. Until this is fixed you can try gibbing the body of the dead person and then see if remote view works on the living version

**Comment by DeityLink** [comment]
Nah it's because of the TALKED_BEFORE spell flag tracking mobs instead of minds, easily fixable.
