### ISSUE TITLE
Gumshoe: Blood no longer appearing red

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28603]
(WEB REPORT BY: germansanta REMOTE: 206.221.180.138:7777)
# Revision
https://prnt.sc/wx779s

# Description
Same as issue
# Steps to Reproduce
Join as Gumshoe Detective. Look at blood.
# What you Expected
Red Blood
# What Actually Happened
Grey Blood

**Comment by Dacendeth** [comment]
Has noir ever worked with blood here? It's been like this for years as far as im aware.

**Comment by ShiftyRail** [comment]
Maybe the very first iterations of it.

**Comment by djkramer123** [comment]
It used to work, years ago, good luck finding a coder that cares given how often it's bug reported.

**Comment by robintime** [comment]
duplicate of #21866
