### ISSUE TITLE
Secure Briefcase inhand state is inverted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28616]
(WEB REPORT BY: plausibledeniability REMOTE: 206.221.180.138:7777)
# Revision
62dcdc1bfb20610bb8772c9a0686c199ce5971c2

# Description
Secure Briefcase inhand sprite being locked or unlocked is inverted
# Steps to Reproduce
Have locked secure briefcase, hud icon is red for dead but inhand is green for go.
Have unlocked secure briefcase, hud icon is green for go but inhand is red for dead.

# What you Expected
Unlocked is green means go for hud AND inhand, Locked is red means dead for hud AND inhand
# What Actually Happened
green wasn't go
red wasn't dead

**Comment by PlausibleDeniability** [comment]
![dreamseeker_DNyEkIRFlL](https://user-images.githubusercontent.com/71354469/104966623-47a98780-59d9-11eb-8166-cbf6b84142d6.png)
![dreamseeker_peUBtBJPsn](https://user-images.githubusercontent.com/71354469/104966625-48421e00-59d9-11eb-8277-e2e5d7a55e95.png)
