### ISSUE TITLE
Barrels thrown with TK do extreme amounts of Damage.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28627]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
5b5c55ecbadab565075667ecdaac6b28d88f2c7f

# Description
Telekenesis Barrels do shittons of damage.  Like, kill someone in a few throws damage. It ain't right.

**Comment by Kurfursten** [comment]
Everything about barrels was a mistake 😌
