### ISSUE TITLE
subspace tunnelers can move emitter lasers.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28621]
(WEB REPORT BY: surrealitarian REMOTE: 206.221.180.138:7777)
subspace tunnelers can move emitters, but the laser wont update until you switch the emitter off, but the lasers themselves can also be moved piece by piece.

**Comment by ghost** [comment]
Tested this myself, the emitter part about the laser remaining behind is true, but the lasers themselves cannot be moved due to lack of mouse opacity or something.
