### ISSUE TITLE
Feature Request: A way to remove specific chems from a plant's phytochemistry via either a tool or xenobotany machine.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#28624]
I play botany a lot, and it's always a kick in the nuts to see a great plant that I can't effectively mass use because it has a chem that doesn't help, like the solanine (toxin) in ambrosia vulgaris or the cyticine (synaptizine) in ambrosia deus, both of which make blunts pointless, since smoking a normal blunt makes you somewhat poisoned while a godblunt can kill you (1u cyticine equals about 60 toxdamage and since a godblunt, regardless of potency, has more than 1u, smoking a godblunt is a death sentence.)

Other times, when making materials-fruit (like glowberries for uranium) the presence of nutriment is a problem, since it always outnumbers the material, making any grinding woefully slow since you have to remove the nutriment every time to keep going.
Many times you find the ideal exotic seed, only to find out it not only makes the chems you wanted but also 3 different poisons.

You can ADD chems to a plant via splicing, but there's no way to remove specific chems from it.
Please add a way to remove specific chems from a plant's phytochemistry.
[featurerequest] [qol]

**Comment by Killette3** [comment]
This is something me and other botany players have talked about wanting for a while. If you need any ideas regarding this, something that seemed agreeable was a machine that could modify the amount a chemical was present in a plant, from 0-100% (with upgrades raising the cap over 100).
Nutriment alone is the main reason that there is no such thing as beneficial stinging creeper, as even if you don't have chemicals you can overdose on being fat still really sucks.

**Comment by coronasaurus** [comment]
I want this

**Comment by FoggyDayWindyCay** [comment]
this and a machine upgrade that lets you splice more then one disk at a time would make my year
