### ISSUE TITLE
Plants can't get potency above 200, in code max potency is 300.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28638]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
b33ea3bcb018f5df4efea480a94df521b0b02ece

# Description
According to mutations code here:
https://github.com/vgstation-coders/vgstation13/blob/e9a806f30b4db0efa2a68b9eb42e3120d2321b6a/code/modules/hydroponics/hydroponics_mutations.dm

potency is capped at 300.
pour ungodly amounts of mutagen on plants over span of an hour, still 200 potency
Picture related.
https://i.imgur.com/pIqTet8.png
# Steps to Reproduce
Get plant, pour mutagen on it and shoot with floral somatoray, hope to get 300 potency eventually over span of an hour, still 200 potency
Picture related.
https://i.imgur.com/pIqTet8.png
# What you Expected
Potency above 200
# What Actually Happened
Potency stuck at 200.

**Comment by dunsel-hordon** [comment]
get cucked plant nerd

**Comment by Killette2** [comment]
The code is written really confusingly, but I have a point that might clear things up a bit.
At line 165 we begin to see these lines of code
// Now that we have all the final modifiers, we can calculate the mutation's final strength.
			var/deviation = severity * (rand(50, 125)/100) * cap_ratio
			//Deviation per 10u Mutagen before cap: 5-12.5
			seed.potency = clamp(seed.potency + deviation, 0, 200)
			generic_mutation_message("quivers!")
			
Therefore until that number is changed it will always cap at 200 until that is raised. I'm not a math expert, but here is my best guess. When you use robust harvest your potential potency is capped at 150 but after 120 it starts to very noticeably slow down. Robust harvest and mutagen are coded  differently as one is a clamp and another is not but the principal is similar enough for a comparison. The mutagen cap does go to 300 but I believe the number is higher than 200 to prevent such an annoying mutagen creep, allowing you to hit max potency "reasonably"
You'll see that with most of the other traits such as yield, they have a potential number you can go for but then later a similar hardcap to the results. You made what is essentially a max stat plant from mutagen and it's always nice seeing a plant that impressive, keep up the good work farmer

**Comment by DeityLink** [comment]
I think it's supposed to cap it at 200, the values in the list are just there for the calculations or something.
