### ISSUE TITLE
[Box] Permabotany map issue

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2863]
Needs a chem master/condimaster to be able to separate out the sugar/jelly for making jelly sandwich/donut/jelly toast. And pref at least 3 large beakers/condibottles to support flour, sugar, jelly containers for cooking. I'd like a sink so prison farmbot can refill and you can make candied apple too but faggots will slipathon

Comic says: Updated the issue.

**Comment by ComicIronic** [comment]
Knives are a black hole.

Who knew simple things were so complicated.
Can you also rename this Perma Botany Issues or something, and specify the maps.

**Comment by Unfit** [comment]
plastic knives and other dinnerware aren't coded as subtypes of their metal counterparts
also plastic knives are just as strong as metal knives, meaning they break bones in a few hits

there should be a total rewrite of forks as well, their code is awful

**Comment by Probe1** [comment]
You could comment out forks and few would notice.

**Comment by 9600bauds** [comment]
Partially addressed by #3501
