### ISSUE TITLE
H/E pipes cooling shit too low without a sufficiently cold source. 

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2864]
Can you look at https://github.com/d3athrow/vgstation13/commits/Bleeding-Edge/code/ATMOSPHERICS/he_pipes.dm

Supposedly there was a commit in there or around that time that was supposed to buff HE Pipes and that may have done it. May be from an ignition source on top spazzing it out. I doubt it but tossing it out there

For reference, just last week I used the burn chamber in eng. the burn chamber would continually cool which cooled the pipes until I put a manual valve on so it wouldn't fuck with my tank mixing experiments. It's made the TEG pretty unviable without a piped fuel source

**Comment by clusterfack** [comment]
H/E pipes were made equivalent but just a bit better than thermal plates codewise.

**Comment by ComicIronic** [comment]
What are the common factors?
Are pipes going under walls, for example? Walls have no atmosphere, so it might be causing an issue.
