### ISSUE TITLE
BoxStation Janitors have access to delivery office from janitor's office but not from cargo lobby.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28659]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
a9e20395cd9363c8696e4d0aa500e49fa62f2695

# Description
What it says in the tin.
# Steps to Reproduce
Be a janitor on BoxStation, try to enter delivery office from janitor's office and you can, but can't from the southern, lobby entrance.
# What you Expected
Being able to enter from both areas.
# What Actually Happened
Wasn't able to enter from both areas.

**Comment by toomykins** [comment]
not a bug?

**Comment by Exxion** [comment]
I always figured this was intentional, but who knows
