### ISSUE TITLE
Telepathy and dualwielding

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28652]
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 206.221.180.138:7777)
# Revision
06f90995700731eaf457eea202da204ef20015f6

# Description
Teleporting dualwieldable guns with telepathy
# Steps to Reproduce
Aquire telepathy control one gun and click on another viable dualwield gun
# What you Expected
Nothing really
# What Actually Happened
Guns teleported from the secure armoury to my position outside space since I had xray and telepathy

**Comment by Killette2** [comment]
At this point telepathy should have it's own tag

**Comment by SECBATON-GRIFFON** [comment]
it turns out combining ANY item that puts the results in your hands teleports it to you with tk
