### ISSUE TITLE
Identity Bug - Doesn't update identity.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28657]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
a9e20395cd9363c8696e4d0aa500e49fa62f2695

# Description
Have a hidden identity (miner outfit with no ID). Steal an ID and wear it. Throw the ID away. It still shows you as that identity even though you don't have the PDA on. I think it just doesn't refresh it, because if you redeploy your helmet it refreshes it. This shit SUCKS.

**Comment by ShiftyRail** [comment]
#28233 tried to fix it. I believe the event Zth coded doesn't work when you toss the PDA.
