### ISSUE TITLE
Insectoid vampires dont get thermal vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28658]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
a9e20395cd9363c8696e4d0aa500e49fa62f2695

# Description
Insectoid vampires do not unlock thermal vision at the blood threshold. You still get a message of something like your vampiric vision has greatly improved but nothing happens.

# Steps to Reproduce
Be insectoid. Be vampire. Get the succ.

# What you Expected
Special eyes.

# What Actually Happened
No killstreaks.

**Comment by APCUnlocked** [comment]
I've had this same thing happen to me the last two times I was a vampire as well. I was human. I was wearing sunglasses when succ'ing the victim and receiving the "your vampiric vision improves" message, but I didn't get thermal nor x-ray vision later on.

**Comment by xeroxemnas** [comment]
Doesn't work for human vampires either I think.  I was in that same round you were in and never got it and I had even more blood.

**Comment by xeroxemnas** [comment]
I think you're supposed to have better night vision too at some point but it was still dark as fuck so I think the whole vision thing is borked for vamps.
