### ISSUE TITLE
Box secondary interrogation (the private one) not radproof

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28667]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
6365f8e36e35d034b364b1628f997d75ae238a2f

# Description
The private interrogation room was not flashing green during a radstorm, but you still get irradiated in there.

# Steps to Reproduce
radstorm

# What you Expected
no cancer

# What Actually Happened
my hair fell out

**Comment by DeityLink** [comment]
Now that I think about it, areas that fully run out of power sometimes don't have alerts flash properly right?

**Comment by DeityLink** [comment]
That being said this room is in a subtype of /area/security and thus SHOULD be radproof 
![image](https://user-images.githubusercontent.com/7573912/130131719-c89e77e5-87da-4c00-8a62-b4ef290a79f4.png)

**Comment by DeityLink** [comment]
Sounds like it's due to the APC running out of power and thus not flashing the alarm. not a bug then.
