### ISSUE TITLE
Noir blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28677]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
dd7514b41386fde3a66d113a3b23a5b59d0c17d2

# Description
it's not red 
# Steps to Reproduce
just look at blood with noir 
# What you Expected
for it to be red

# What Actually Happened
it's not red

**Comment by robintime** [comment]
duplicate of #28603
