### ISSUE TITLE
Spawned as Mouse on Vox Station in Snaxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28674]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
8dcd9717ba6a81f77e73842c5c541ce241fee992

# Description
What it says in the tin.
# Steps to Reproduce
Try and spawn as mice on snaxi and pray to the gods that you get (un)lucky to spawn on voxstation
# What you Expected
Spawning in normal station and dying to the snaxi cold
# What Actually Happened
Spawned on voxstation and died to the lack of air

**Comment by Kharkov72** [comment]
today I will FUCKING remind them that mice being able to spawn or not is a fucking VENT VARIABLE

**Comment by Kurfursten** [comment]
Instead of a vent variable it should be area based
And you should have a chance to spawn on the vox outpost as a hilarious N2-breathing green mouse

**Comment by Eneocho** [comment]
> 
> 
> Instead of a vent variable it should be area based
> And you should have a chance to spawn on the vox outpost as a hilarious N2-breathing green mouse

Should the voxmice spawn with a tiny (emergency sized) N2 tank and a mice breathing mask?

**Comment by Kurfursten** [comment]
I guess that's up to whoever sprites them
