### ISSUE TITLE
C-20r Mags dont accept ammo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28675]
(WEB REPORT BY: burntdevil REMOTE: 206.221.180.138:7777)
# Revision
8dcd9717ba6a81f77e73842c5c541ce241fee992

# Description
Cant put 12mm ammo into 12mm C-20r mags.
# Steps to Reproduce
Take box of ammo, hit the mag, it does the animation, does nothing.
# What you Expected
It to reload the mag.
# What Actually Happened
I got jewed.

**Comment by SonixApache** [comment]
they're special mags that only take special c-20r ammo

**Comment by west3436** [comment]
With how often this comes up can't we just give the c-20r ammo a special snowflake caliber or name?

**Comment by west3436** [comment]
Duplicate and not a bug
