### ISSUE TITLE
Admin Delay 

### ISSUE THREAD

**Issue by Boxe** [d3athrow/vgstation13#2867]
delaying serbia won't work sometimes & round will just end

i think it's because of serb taking itself down to recompile but iunno

**Comment by Arthurdentist** [comment]
I believe this happens when the server receives an update. If it receives an update it doesn't respect admin delays and restarts the server at round end to apply the update.

**Comment by Kurfursten** [comment]
@probe1 @d3athrow @clusterfack @deitylink What have we learned about this? Does it still happen?

Is there anything we can do about it if it is update-related?

**Comment by Probe1** [comment]
not a bug

there is a point when it is too late to delay the round.  previously, it was not marked in any way.  now some red text describing a function pops up and that marks the point where you can no longer delay.

before, admins did not know when they could no longer delay.  now they can.  so its pretty much resolved.

**Comment by DeityLink** [comment]
If probe is right then I guess we can close that.
