### ISSUE TITLE
Galactic Common Say Key is Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28682]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
53320cf0775751099cdc5ac0fa4ecd3b781e1760

# Description
Setting default language to other than Galactic Common and using the listed ":l" key to try speaking it instead of Vox-pidgin or Gutter or w/e doesn't actually work. You continue to speak your default language.
# Steps to Reproduce
>be me, Vox
>speak Vox, because I'm a Vox
>these fleshy walking moneybags called humans want me to speak "Space English" w/etf that is, assume they mean GalCom
>suddenly feel tongue-twisted, the words won't come out right
>talon's weak, wings heavy
>nestmother's spaghetti
# What you Expected
Say ":l What you bingus human want, yaya?"
# What Actually Happened
SCree TIkitraaawk cawwwwk

**Comment by toomykins** [comment]
my nigger that says :1 not :l

**Comment by west3436** [comment]
Skill issue
