### ISSUE TITLE
Robo-Farmers Spill Fertilizer When Loading

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28681]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
53320cf0775751099cdc5ac0fa4ecd3b781e1760

# Description
Attempting to load "Special Vox Trader Farmbot" and presumably similar models of robot results in them eating the bottle and gaining 1 unit of the given fertilizer. Ejecting these containers returns them empty. For vending machines stocked with 30 bottles of E-Z Nutrient, it seems woefully inefficient to jam in 10 bottles for a full.
# Steps to Reproduce
>get Farmbot
>get container of choice filled with delicious biochemicals E-Z, Robust, Zed, your favorite flavor will do
>click on robofarmer with container
>despair
# What you Expected
it ain't much, but it's honest work
# What Actually Happened
i have doomed the harvest and my family will starve

**Comment by jknpj** [comment]
Dude, close the lid before inserting.

**Comment by west3436** [comment]
Feature and skill issue
