### ISSUE TITLE
Non-cultists can't use cultswords with non-cultists inside.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28683]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
53320cf0775751099cdc5ac0fa4ecd3b781e1760

diety where the fuck is my suicide gambits

**Comment by Blithering** [comment]
Sword is still made of evil

**Comment by DeityLink** [comment]
> 
> 
> Sword is still made of evil

This but unironically
