### ISSUE TITLE
Snaxi no bucket for janitors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28685]
(WEB REPORT BY: ezudiko REMOTE: 206.221.180.138:7777)
# Revision
53320cf0775751099cdc5ac0fa4ecd3b781e1760

# Description
Snaxi Janitor room has insufficient lighting and no bucket to fill the mop with from the roundstart water tank

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
Both are present, he got a roundstart broke light
