### ISSUE TITLE
Fat People Can't Wear Winter Jackets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28693]
(WEB REPORT BY: kromkar REMOTE: 206.221.180.138:7777)
# Revision
516404acc7b84a201eff64f996d36db09f5879c6

# Description
Fat people can't wear winter coats
# Steps to Reproduce
Be Fat
Be Unable to wear coat
# What you Expected
To not suffer more than I already do on Snaxi
# What Actually Happened
Effectively being trapped in the station sections

**Comment by Kurfursten** [comment]
Not a bug, only 3 coats are fat-approved
