### ISSUE TITLE
Deconversions are the new cult check.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#28699]
Way easier to do than choppin someones head off. Imo they shouldn't show the deconverter anything unless the cultist accepts being deconverted, or at the very least i should require progress bar so you cant be drive by cult checked.

**Comment by Blithering** [comment]
My ideas (that don't involve RNG) would be 
a) making deconversion require the person bibleslapping to at least be a member of the chaplain's religion (hey it gives that mechanic a purpose!)
b) holy water resistance tattoo makes deconversion not trigger at all (hey that gives that tattoo a purpose!)

**Comment by PrimeDSS13** [comment]
I think that making it so the deconvertee has to be cuffed and buckled might help, so you cant just catch people off surprise. I do really like that holy water idea though Blithering.

**Comment by dunsel-hordon** [comment]
were they just drive by the conversion? Ya its shit i still say the previous way conversions worked were fine with just bein forcefed holy water

**Comment by DeityLink** [comment]
Conversions being the new way to cult check was completely intended, so I'm glad people are using it.

But yeah it being used to catch people by surprise and such wasn't intended, so I'm nerfing that aspect in #28701 , on top of giving another incentive for chaplains to be the ones doing it, and an incentive for cultists to take the unholy tattoo.

**Comment by DeityLink** [comment]
>Way easier to do than choppin someones head off.

That's not a cult check ever since #28451 though

**Comment by Eneocho** [comment]
> 
> 
> My ideas (that don't involve RNG) would be
> a) making deconversion require the person bibleslapping to at least be a member of the chaplain's religion (hey it gives that mechanic a purpose!)
> b) holy water resistance tattoo makes deconversion not trigger at all (hey that gives that tattoo a purpose!)

There IS a purpose to religion. If you are part of a religion and hear the chaplain say a 20 letter word or longer, you recover from hallucinations, dizziness, pain, confusion, stuttering, drowsiness, and jitteriness.
