### ISSUE TITLE
[Box] Primary tool glass is an iconless "sheet"

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2869]
![untitled](https://cloud.githubusercontent.com/assets/5564796/6094503/ef0f2046-aed8-11e4-81c8-74a769e7e94e.png)

**Comment by Probe1** [comment]
This has been coming up a lot lately in the kitchen and botany for me.  I'll find an 'item' with no sprite when alt clicking to look through a pile of shit.  It's fairly recent too.

**Comment by ComicIronic** [comment]
There was a change recently from glass to glass/glass, and presumably the maps have not been updated.
