### ISSUE TITLE
Summon Bound Object

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28695]
(WEB REPORT BY: edwarus REMOTE: 206.221.180.138:7777)
# Revision
516404acc7b84a201eff64f996d36db09f5879c6

# Description
Summon bound object on being brained as wizard
# Steps to Reproduce
Become a wizard be brained and use summon bound object as soon as you become a brain.
# What you Expected
Not to be able to summon the bound object
# What Actually Happened
object was summoned when a brain

**Comment by Eneocho** [comment]
You can use most spells as an MMI wizard, feature.

**Comment by dunsel-hordon** [comment]
No the brain wasn't an mmi it was only a brain and managed to use a timing gap from being a brain in a skull to being a brain in the open.

**Comment by Killette3** [comment]
big brained magic

**Comment by DeityLink** [comment]
I'll call that a feature
