### ISSUE TITLE
General Fabricator, Flatpack Fabricator, and Spacepod Fabricator cannot make anything

### ISSUE THREAD

**Issue by omeno** [d3athrow/vgstation13#2870]
Any blueprints (nanoprint or regular) once inserted in a general fabricator or flatpack fabricator do not enable it to produce that item. The spacepod fabricator also has no parts listed in it, so the frame pieces cannot be constructed.

**Comment by ComicIronic** [comment]
Caused by an untested commit intended to fix a bug that was crashing the server and that broke a lot of other fabricators.

**Comment by ririchiyo** [comment]
I'm going to close this issue and reopen another one because this was fixed for the most part or should be, reopen if they weren't.
