### ISSUE TITLE
Bagel Science Outpost Vox Trade spot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28717]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
129c0dcfb1e694cea583118e774bacdfa556a00d

# Description
door is able to be open by AI
# Steps to Reproduce
just open it
# What you Expected
vox only access
# What Actually Happened

**Comment by DeityLink** [comment]
Silicons can open any door at will unless the AI wire is cut. It's a feature.
