### ISSUE TITLE
Snaxi shuttles can backblast each other

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28714]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
129c0dcfb1e694cea583118e774bacdfa556a00d

# Description
If the bar/cargo snaxi shuttle arrives perfectly timed with the medbay snaxi shuttles departure it can land into an exhaust plume that expands inside the shuttle. Put a line of windows or something between them.

# Steps to Reproduce
Get incredibly unlucky with your taxi timing. Land a taxi shuttle onto the exhaust of a departing taxi.

# What you Expected
not to melt in a horrible death

# What Actually Happened
nearly melted in a horrible death

**Comment by Eneocho** [comment]
Yet another argument against snaxi. Based. Waiting for someone to claim it's a feature.
Shitposting aside, you have to get some stupid timing for this to happen, I'm talking within the same tick. Is getting such an event to happen bad luck or good luck?
