### ISSUE TITLE
Request consoles consider ghosts reading their message as read

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28721]
(WEB REPORT BY: jellyveggie2 REMOTE: 206.221.180.138:7777)
# Revision
5583c003f930b20742859669e5504b1cb76ce9f5

# Description
As a ghost, clicking on a request console flashing red because of a Central Command supply request, marks it as "read". The visual alert is gone, and living layers might not notice (if they care at all).

# Steps to Reproduce
1. Suicide
2. Succumb
3. Wait for an order from centcomm
4. Click on Request Console

# What you Expected
For me to be able to snoop in on what's on the request console without the console thinking it's job's been done,

# What Actually Happened
Request consoles can sense ghostly readers.

**Comment by ConkerDev** [comment]
This happened to me as well
