### ISSUE TITLE
Snaxi's brig mix-and-match windows

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#28729]
See picture

![image](https://user-images.githubusercontent.com/31417754/106370395-e62ed480-6359-11eb-89d5-1832d6003d99.png)

**Comment by Kharkov72** [comment]
that seems to just be plasma windows on the outside facing windows, which isn't random, just weird

what did they mean by this?

**Comment by Kurfursten** [comment]
This is entirely intended. It lets you see into the window from the interior side even when shaded. It works perfectly, you can't tell how it works in ghost form because you can see through the smart windows.

The plasma windows are smartwindows (brig smartwindows are always plasma)
