### ISSUE TITLE
Firelocks don't show data when examined

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2872]
![data unavailable](https://cloud.githubusercontent.com/assets/7538670/6095040/3b85f122-af40-11e4-9fdf-dc1760ee86ab.png)

**Comment by ComicIronic** [comment]
I believe this is due to firelocks losing Process(), and so not updating at all.
A solution would be to have firelocks tie to an air alarms data values for the zone.

**Comment by Probe1** [comment]
Pomf removed it to save lag because of the way it updates.  It sucks and I hope he reverts the change.

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/commit/5f6007946c9247cff0d9cc9a56e5416e93adc294
