### ISSUE TITLE
Clown language is bright fucking yellow

### ISSUE THREAD

**Issue by djkramer123** [d3athrow/vgstation13#28724]
For the love of god make the clown language not bright fucking yellow.

It's impossible to read on light mode.

**Comment by boy2mantwicethefam** [comment]
no

**Comment by djkramer123** [comment]
![ClownLanguageWHY](https://user-images.githubusercontent.com/51164713/106357034-a8866900-62d1-11eb-82ec-b22017bca8b1.png)

**Comment by DrSnips** [comment]
no

**Comment by Exxion** [comment]
Who fucking merged that
