### ISSUE TITLE
Sashas In-Hand is Ian.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28727]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
5583c003f930b20742859669e5504b1cb76ce9f5

# Description
fucked up, literally unplayable.

**Comment by Kharkov72** [comment]
when you sprite it

**Comment by drawsstuff** [comment]
I literally made a sprite for this ages ago and it coders I sent it to haven't done shit with it
![sashainhand](https://user-images.githubusercontent.com/16404218/141500453-1ebd131e-fde1-4ec8-ac19-e59226626401.png)


take it or leave it
