### ISSUE TITLE
Malf AIs can Shunt to different Z-Levels.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28722]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
5583c003f930b20742859669e5504b1cb76ce9f5

# Description
Self Explanatory, an AI shunted to the mining station on another Z-level.

**Comment by PrimeDSS13** [comment]
close this bug report
I was misinformed the AI was just on the asteroid which is gay

**Comment by gurfan** [comment]
lmao

**Comment by Eneocho** [comment]
heh

**Comment by DeityLink** [comment]
hah
