### ISSUE TITLE
Clown Language is an unreadable yellow.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28737]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
d0e47d31b61ec6f0523164fd7f0656eeb056bb15

# Description
Its bright fucking yellow how do people even read this shit

**Comment by toomykins** [comment]
its also annoying as fuck. clown babbles to the AI in a language nobody but the two of them understand.

**Comment by Eneocho** [comment]
Intended as fuck.

**Comment by Eneocho** [comment]
Feature.

**Comment by Eneocho** [comment]
> 
> 
> its also annoying as fuck. clown babbles to the AI in a language nobody but the two of them understand.

That's basically how everyone feels when a V*x player talks in pidgin.

**Comment by PrimeDSS13** [comment]
why did you post three comments in a row

**Comment by Dacendeth** [comment]
There can be multiple vox though that could listen to it, there's usually/hopefully only ever one clown.

**Comment by djkramer123** [comment]
clearly the only purpose of this language is so the clown can ask silicons to do whatever over comms without other people knowing while also filling other people's chat with bright yellow text on white background

**Comment by Eneocho** [comment]
> 
> 
> clearly the only purpose of this language is so the clown can ask silicons to do whatever over comms without other people knowing while also filling other people's chat with bright yellow text on white background

If the yellow on white (why even use bright mode) is too annoying, I can change it to a medium brightness pink.
And the language's original purpose was flavour, since there's languages for every race and since clowns are basically a species of their own, I added the clown language.

**Comment by ghost** [comment]
you were told in the original PR that it was awful to look at and yet you went with it anyway so you can't really be surprised that people find it awful

**Comment by DamianX** [comment]
The obvious solution is to **remove silicons**' ability to understand clown language.

**Comment by APCUnlocked** [comment]
> The obvious solution is to **remove silicons**

We've finally reached the crux of the issue. Proceed with this and the playercount will soar sky high.
