### ISSUE TITLE
Vox language broken.

### ISSUE THREAD

**Issue by YertBogan** [d3athrow/vgstation13#2873]
:V doesnt speak vox anymore
how many people actually care

I only have basic understanding of code, should i be digging through say.dm?

**Comment by Ephx1** [comment]
I'm pretty sure all race specific languages are fucked, after the port of tg say code.

**Comment by 9600bauds** [comment]
Yeah they are. There's already an open issue on it but it'd be great to hear this is getting looked over.

**Comment by d3athrow** [comment]
Just gotta muster up the courage to break things to shove species langs back.

**Comment by 9600bauds** [comment]
Godspeed you brave poultry.

**Comment by ririchiyo** [comment]
#2606
