### ISSUE TITLE
Weapons now over penetrate simple mobs when you click past them.

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#28745]
[bugfix]
@ShiftyRail 

Clicking on floor on the far side of certain simple mobs causes the projectile to hit and penetrate all mobs between the shooter and your target.

https://i.gyazo.com/d76b018661766c00bfa8a56ddbfd920b.mp4

**Comment by ShiftyRail** [comment]
It's most likely deity's fault. I'll look at it.
