### ISSUE TITLE
Synergy Station Hos Locker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28744]
(WEB REPORT BY: burntdevil REMOTE: 206.221.180.138:7777)
# Revision
c0478ace14ebce2dfa85382a976b8cb1dfc90a07

# Description

The entire contents is duplicated. They get two of everything.

# Steps to Reproduce
open locker
# What you Expected
get one debit card
# What Actually Happened
got two, along with everything else in the stupid thing

**Comment by Jackreturnswithaveangenace** [comment]
Known bug, though I don't actually know what replicates it? Has been around for a while.
