### ISSUE TITLE
Particle accelerator isnt working

### ISSUE THREAD

**Issue by Riukanojutsu** [d3athrow/vgstation13#2875]
It wont spawn singulo. The particles it throws are all broken and singulo just dont spawn

**Comment by clusterfack** [comment]
In this specific case the particle accelerator middle section wasn't sending particles. 

But in general though this is a somewhat multi part issue
-Particles sent from the accelerators aren't coinciding
-Sometimes the PA doesn't send particles from all 3 locations

**Comment by d3athrow** [comment]
This is 99% my fault.

**Comment by clusterfack** [comment]
Now only 1 particle of 3 spawns now.
