### ISSUE TITLE
Mice and crates.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28774]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
6d1c74adb6b6adfb019882a5311955ae2a3b1674

# Description
Mice can put crates in disposals bins by drag-and-drop
Mice can also put stuff into crates by drag-dropping
# Steps to Reproduce
Become a mouse, get near crate, drag and drop stuff in it, bully vox scientist by stuffing them in crate, flush entire crate of minerals from R&D
# What you Expected
Shits and giggles, one seething vox.
# What Actually Happened
Shits and giggles, angry bird, admin bwoinks.

**Comment by Kurfursten** [comment]
The mice are stealing our cargo jobs

The left said mice would only take jobs human workers didn't want

**Comment by Eneocho** [comment]
You can also butcher as mice. Mice gang.
