### ISSUE TITLE
Wolfissues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28779]
(WEB REPORT BY: catandwet REMOTE: 206.221.180.138:7777)
# Description
Wolf gets hungrier while riding toboggan (even while halted), can't be unbuckled from toboggan without connecting to a snowmobile (the wolf falls off when it's connected)

# Steps to Reproduce
Put wolf on toboggan, panic
# What you Expected
for it to not be such a responsibility being a pet owner
# What Actually Happened
the wolf is forever hungry and my life was nothing but the wolf

**Comment by Kurfursten** [comment]
Wolves only get hungry from healing now, not from moving

**Comment by nervere** [comment]
tested, no longer an issue
