### ISSUE TITLE
You cannot pull bear traps.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28773]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
e4133001a55f1a06c7d44fef3621f04ae2b9a0c4

# Description
just as the title says

**Comment by Dacendeth** [comment]
deployed or undeployed?

**Comment by Kurfursten** [comment]
He reports on discord "while deployed"

I thought this was a feature from when they got buffed?

**Comment by SonixApache** [comment]
pretty sure that's a feature, yes

**Comment by PrimeDSS13** [comment]
hm
kind of lame but alright
