### ISSUE TITLE
Slippery Magboots while set to Walk

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28785]
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
ef33f27ec4c142ee71949a58e4a8ba0940c29b4d

# Description
When walking in space with magboot traction enabled, I was slipping consistently while set to Walk instead of Run. Tested on Space and Lattice floors.
# Steps to Reproduce
Put on magboots, turn them on, go into space, set your speed to walk, and walk around.
# What you Expected
Magboots to prevent slipping in space
# What Actually Happened
Magboots only guarantee no slipping while running, not walking.

**Comment by DeityLink** [comment]
Diplicate of #26988

**Comment by DeityLink** [comment]
Duplicate of #26988

**Comment by west3436** [comment]
Duplicate
