### ISSUE TITLE
If NOBREATHE is activated *while* taking toxins damage from bad gases in the air, you will permanently keep taking toxins damage.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#28791]
Does not work:

1. Spawn vox in O2 without mask/tank
2. Give NOBREATHE
3. Watch as vox keeps taking toxins damage

Does work: 

1. Spawn vox 
2. Give vox N2 tank/mask so it stops taking toxin damage
3. give NOBREATHE
4. Take mask/tank off
5. vox does not take toxins damage.

**Comment by Kammerjunk** [comment]
fuck, this actually explains a few things I've experienced

**Comment by Killette2** [comment]
It's because you breathed in the bad gas and got the no breathe power before exhaling, so it's still in your lungs

**Comment by DeityLink** [comment]
After testing turns out it's just a UI bug, you don't actually keep taking damage, you just see the alert remain.
