### ISSUE TITLE
PROJECTILES ARE STILL GOING THROUGH EVERYTHING

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28807]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
12324439a4a56d8be9f6000f233958b1c104f540

AHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by ShiftyRail** [comment]
They don't do through *everything*. They go through people if you shoot at them point-blank and if they move right after you shoot.

**Comment by gurfan** [comment]
no, they go through almost everything. Just this round a laser shot through the ai core to hit me on the other side, the previous round taser bolts were penetrating people to tase 3 guys at once

**Comment by drawsstuff** [comment]
can confirm, I was shooting an AI and fucked gurfan who has standing on the other side

**Comment by ShiftyRail** [comment]
The AI fortify effect is the only thing I can confirm here. It's an easy fix.
