### ISSUE TITLE
VOX Wordlist Requests

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#28800]
Long overdue, I know.

This is an issue for requesting all the words you want in the next package of VOX words. You can also list pronunciation errors so I can (try to) fix them.

## Known Issues
Words with bad pronunciations I know about but can't fix due to complex bugs in the voices:
* bag
* go

## Already Added

```
sound/AI/vox_reminder17 = Reminder: Do not take gifts from Santa Claus.  He is a registered sex offender. Please report him to security if seen.
sound/AI/vox_reminder18 = Happy Vox History Month!
```
(Considering making seasonal announcements and moving them to their own lists)

## Rurus
Because they apparently need to be said, and because I don't want to host this shit on gitgud.  Their upload speeds are atrocious.

* No slurs
* No lewds
* No illegals in the US of Free Speech
* If it's a sound effect, link to the sound effect and what the `_id` should be.
  * If you want it cropped out of a larger video/sound, make clear which section should be extracted or do it yourself with youtube-dl + audacity.
  * Bear in mind that sound effects are put through a series of bandpass filters and echoes so it sounds like a PA.  This will make them sound shittier *by design*, and not all sounds can go through this process without being rejected for shitty outcome.

## Current sounds
* https://github.com/N3X15/ss13-vox/tree/master/wordlists
  * You can also make PRs there.

## Timeline
* Due to commitments during the week of the 20th, submissions will be closed on the 19th.

[sound]
[vox]
[discussion]
[sound]

**Comment by N3X15** [comment]
Also, I should note that I am currently working on a system that will allow us to generate complete, less-jank-sounding sentences on the fly via a REST daemon.

**Comment by Kharkov72** [comment]
sneed and chuck when

**Comment by calzilla1** [comment]
Oh
Hyper
Brute
Burn
Sin
Zine
Woah
Beast
Spin
Contain
Maybe add a few basic chemicals like Inaprovaline or Bicaridine

**Comment by DamianX** [comment]
There seems to be a sound file that says DOOR STUCK at a very high volume, and I often hear AIs repeatedly use it seemingly out of context. Can you look into this bug?

**Comment by drawsstuff** [comment]
Stun
Valentine
Fancy
Goliath
Basilisk 
Wendigo
Cockroach
Insect
Flesh
Dave
Shunt
Spore
Gross
Grass
Frog
Feed
Beast
Blow
Contain
Reborn
Crab
Narsie
Wraith
Artifacer
Juggernaut
Harvest
Harvester
Fluid
Nova
Flower

**Comment by N3X15** [comment]
> Maybe add a few basic chemicals like Inaprovaline or Bicaridine

I went through and added pretty much every chem I could find a while ago and put them [here](https://github.com/N3X15/ss13-vox/blob/master/wordlists/vg/chemistry.txt).  Let me know if anything else is missing.



> There seems to be a sound file that says DOOR STUCK at a very high volume, and I often hear AIs repeatedly use it seemingly out of context. Can you look into this bug?

I can remove it. Volume *should* be equalized as part of the post-processing process, but SoX can be dumb sometimes.
