### ISSUE TITLE
Mushmen latejoin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28812]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
11265d4fb52e0da1bd28638e478124aaafa405cb

# Description
You konw how latejoin traders fly in?
The damage they take when they collide breaks mushmen bones
# Steps to Reproduce
latejoin mushman trader
# What you Expected
no bone breaking?
# What Actually Happened
bone broked

**Comment by Armadingus** [comment]
Maybe mushmen should start with an airbag in their pocket so they don't get owned on latejoin.

**Comment by Kurfursten** [comment]
This has actually happened to Vox before too on a few occasions. Bone breaking is RNG based on the brute damage. The initial impact is ~10 brute, so the odds are rather low, but for a mushman that raises to ~18 which is modestly higher. It won't break every time but it does sometimes.

I'm not opposed to adding airbags to the trader spawn outfit, but it is just one of those hazards that has been around a long time.

**Comment by Servalfang** [comment]
it's something that shouldn't happen to any latejoin traders, so I would endorse that yes

**Comment by xeroxemnas** [comment]
![4574554848](https://user-images.githubusercontent.com/38308926/107273012-851f9480-6a1c-11eb-9c64-f2fb1251e23e.jpg)

**Comment by west3436** [comment]
Fixed via #35674 as traders now get airbags.
