### ISSUE TITLE
very annoying to do farming as a mushroom

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28815]
(WEB REPORT BY: surrealitarian REMOTE: 206.221.180.138:7777)
click that random reishi plant that started growing? it'll pop up right under you, and you instantly start eating it.
poof, next thing you know theres sleeptoxin in your body.
maybe add a toggle function for that eating behavior, so we dont eat anything that meets our path.
at this point you could just throw poison on the floor and the mushroom couldnt walk past it.

**Comment by Dacendeth** [comment]
use a plant bag to harvest.

**Comment by Kurfursten** [comment]
> you could throw poison on the floor and mushman would have to pick it up before walking past, or walk around

Feature

**Comment by Servalfang** [comment]
I like mushmen. I think maybe they should have footwear (ie magboots or jackboots) that block eating while on. Then it's inconvinent in a different way.

**Comment by west3436** [comment]
Feature not a bug. If you want footwear to prevent eating, please make a feature request.
