### ISSUE TITLE
Blinded by own wiz pies

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28819]
(WEB REPORT BY: avadanatinde REMOTE: 206.221.180.138:7777)
# Revision
27882533ef0cca9c28f49ab76ececdefb854e06e

# Description
when spam throwing pies at people i would get blinded
# Steps to Reproduce
be wizard
spam throw pies using the spell
go blind
# What you Expected
to not go blind
# What Actually Happened
why can't i see

**Comment by west3436** [comment]
Unable to reproduce
