### ISSUE TITLE
Diethylamine plant bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2881]
If you put diethylamine in plants it creates pest instead of killing them like it's supposed to. Another bug I'm just going to slap in here too is that reshi and liberty caps have their chemicals mismatched, where reshi should make you sleep and liberty caps should make you have psilo.

**Comment by Killette2** [comment]
I've noticed the liberty caps and reshi are correct now, but what about the diethlyamine?

**Comment by 9600bauds** [comment]
I'm working on it as part of a bigger PR.
