### ISSUE TITLE
All fruit isnt a fruit at all

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28824]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7

# Description
All fruit can't be put in seed extractors for more all fruit seeds
# Steps to Reproduce
1. get all fruit (hardest part)
2. put in seed extractor
3. nothing
# What you Expected
Golden age for voxkind (and downfall of humankind)
# What Actually Happened
nothing

**Comment by APCUnlocked** [comment]
feature

**Comment by kilozombie** [comment]
You have to use the all fruit to get a box of all-fruits. That's their method of reproduction
Feature
