### ISSUE TITLE
so like the optical thermal eyepatch sprite is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28820]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7
and stuff
# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/66280799/73e6336d-3d64-404e-8424-1f692e115503)
Unable to reproduce
