### ISSUE TITLE
Bolas have escaped my grasp

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28827]
(WEB REPORT BY: datemono REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7

# Description
a set of bolas not float above my hotbar
# Steps to Reproduce
get hit by bolas, take them off and place them inside bag
# What you Expected
bolas to go into my bag for safe keeping
# What Actually Happened
I have a set of bolas sitting above my hotbar breaking my immersion forever

**Comment by Eneocho** [comment]
It happens with most objects if you add/remove items too quickly for some godforsaken reason. Muh Emmulshoins

**Comment by west3436** [comment]
Unable to reproduce
