### ISSUE TITLE
[Bug/Feature Request] [Plasmaguard] still lets your jumpsuit get contaminated

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2882]
Hardsuits have [plasmaguard] to stop the rig from getting contaminated but that doesn't matter a whole hell of a lot because your jumpsuit magboots and gloves will still get contaminated, poisoning the shit out of you.  I feel like plasmaguard needs revamped to apply over the jumpsuit, the same way a rig protects you from low/high pressure and heat.

**Comment by ComicIronic** [comment]
Can you give an example of this happening?

**Comment by Probe1** [comment]
Sure put on a hardsuit and walk into an area with plasma.  Presto, you've got plasma contamination on your uniform/jumpsuit, gloves and boots.

**Comment by Probe1** [comment]
This is strange.  I'm unable to reproduce what I've described but I've seen it happen so many times in game.  I'll test more and re-open when I find out what causes plasmaguard not to work.
