### ISSUE TITLE
Vox Prisoners spawn with Plasmaman Gear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28829]
(WEB REPORT BY: pulserider REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7

# Description
When you spawn as a Vox prisoner, you're spawned in wearing a plasmaman internals suit that shouldn't even fit on vox - you also have a nitrogen tank and a plasma tank, but you breathe from the plasma tank.
# Steps to Reproduce
Spawn as a Vox Prisoner
# What you Expected
To be breathing nitrogen and not in plasmaman clothes.
# What Actually Happened
Nearly dying from breathing in plasma instead of the nitrogen tank on my back.

**Comment by Servalfang** [comment]
feature
