### ISSUE TITLE
Wearing a Xeno-hide helmet makes you look like an Alien

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28825]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7

# Description

Seriously, this is goddamn freaky.  I am supposed to be wearing sunglasses in this too.
# Steps to Reproduce

Wear Xeno-hide helmet
# What you Expected

To look like a badass
# What Actually Happened

https://imgur.com/a/RJyZet2

**Comment by west3436** [comment]
Doesn't seem to be a bug but instead the intended behavior. Use the Xeno costume if you want to look like a xeno.
