### ISSUE TITLE
Amish Suit now missing on ground sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28821]
(WEB REPORT BY: kromkar REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Armadingus** [comment]
#28654 Turns out amish clothes and noir detective uniforms share the same on ground sprite, whoops.
