### ISSUE TITLE
Chemspray nozzle uses 15 when it says 5 and 30 when it says 10

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28834]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7

# Description
When you activate a spray item on hand, it switches between active pressure nozzle (10u) and no pressure nozzle (5u).  The chemsprayer says the same but uses 3 times the displayed amount
# Steps to Reproduce
Get a chemsprayer, fill with whatever and spray away.
# What you Expected
For 600u to last me 120 sprays at 5u each.
# What Actually Happened
Only lasted about 40 sprays.

**Comment by boy2mantwicethefam** [comment]
It's intended, it sprays 3 tiles worth rather than just 1 tile's worth, but I think someone was just too lazy to change the message for the sprayer
