### ISSUE TITLE
you can get silenced as a borg by mime goblin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28831]
(WEB REPORT BY: dogesimpson REMOTE: 206.221.180.138:7777)
# Revision
c48e4326f2ac3c98611d854a50183111166e54a7

# Description
sneed
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
Feature

**Comment by Kharkov72** [comment]
feature

**Comment by DamianX** [comment]
feature
