### ISSUE TITLE
Strong Blob Doomstack

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28838]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
d223e380e915d38840aa097194c6acace767f07a

# Description
Chance for strong blob creation to glitch out and allow stacking insane numbers of strong blob on one tile
# Steps to Reproduce
>be blob
>be at death's door and spamming strong blobs just to stall for time (manage to get a cerebrate built before you die)
>spamming the strong blob button though
>like going to town on it
>get bwoinked for creating 227+ strong blobs on one tile and not knowing about it
# What you Expected
for this to not happen
# What Actually Happened
I was accused of cheesing

**Comment by Eneocho** [comment]
>
>get bwoinked for creating 227+ strong blobs on one tile and not knowing about it

Who would even bwoink by a player using lawful game mechanics? How do you even "cheat" on spess if you're not an admin?

**Comment by Blithering** [comment]
Unless there's a real doomstack  issue being overlooked, the appearance of insane number of blobs shown when right clicking a tile is due to the sprites being 64X64, and therefore overlapping on every adjacent tile.

**Comment by Exxion** [comment]
That would only show a maximum of 9. If you actually see 227+ it's definitely not that.

**Comment by west3436** [comment]
Unable to reproduce
