### ISSUE TITLE
Botanists lost their access to bar sign

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28835]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
6b21bc8e94082a38126310779dc83bb1e544caa0

# Description
I used to have access to bar sign, now I don't.
# Steps to Reproduce
Be botanist and have no access to bar sign
# What you Expected
access to change bar sign
# What Actually Happened
no access to bar sign, access everywhere else in bar

**Comment by Kurfursten** [comment]
Hotfixed
