### ISSUE TITLE
Spiderbots can swap places with buckled mobs

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#2884]
The buckled mobs will still remain buckled to a chair, but they won't actually BE on the chair. They won't be knocked down by stuns, won't be able to be pulled or move in any way - just like as if they were normally sitting on a chair. Pretty sure they also can't unbuckle themselves.
The only thing that will save them is finding the original chair they sat on and rotating/moving/destroying it, which will teleport them to it.

**Comment by ComicIronic** [comment]
I'll have a look at making the Bump code for humans, which seems to be the best currently, the one used for all mobs.

**Comment by d3athrow** [comment]
Simple animal bump a shit
