### ISSUE TITLE
Spawned as Mice on Boxstation's vox station 2: Electric boogaloo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28846]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
12881c5ddc67237e7b044f96b7b323b5def079c0

# Description
What it says on the tin, but now on BoxStation. 
# Steps to Reproduce
Mouse gang.
# What you Expected
Boxstation mouse
# What Actually Happened
vox station (dead) mouse

**Comment by Kharkov72** [comment]
ITS 
A
VENT
VAR
AAAAAAAAAAAAAAAA

**Comment by DeityLink** [comment]
It'll try to spawn you as a mice on your current Z level.

If you actually intended to spawn on the main station just go there first.

If you wanted to spawn as mice on the research outpost then _someone_ has to edit all the vents on non-station Z Levels on all maps.
