### ISSUE TITLE
[Feature Request] Proper Multi-Z Functionality 

### ISSUE THREAD

**Issue by drawsstuff** [d3athrow/vgstation13#28845]
What it says on the tin. Proper multi-z is something we probably should get around to sooner than later, and the things it allows for are staggering. By "proper multi-z" I don't mean ladders, I mean support for stairs going up and down and falling down levels. 

It wont be easy though
<featurerequest>
<discussion>

**Comment by anunknownentity03** [comment]
coders, answer the call

**Comment by Kromkar** [comment]
Agreed

**Comment by Kammerjunk** [comment]
feasible? sure, but why would someone spend time adding and reworking so heavily for potential future benefits
hope it's not for multi-z stations. like, imagine the emptiness of a station the size of deff stacked on top of each other 4 times

**Comment by anunknownentity03** [comment]
having multi z will free us from the oppressive ceiling now we can go up or down.

**Comment by anunknownentity03** [comment]
> feasible? sure, but why would someone spend time adding and reworking so heavily for potential future benefits
> hope it's not for multi-z stations. like, imagine the emptiness of a station the size of deff stacked on top of each other 4 times

its entirely dependant on the mapper, but generally what will probably happen is that there will be departments spread out amongst the levels with a few maint segments snuck in.

**Comment by anunknownentity03** [comment]
not so big but not so small I hope

**Comment by Kurfursten** [comment]
Relevant #17194 #18628

**Comment by anunknownentity03** [comment]
so was it working then?

**Comment by Kurfursten** [comment]
It works in the sense that it compiles, sure

**Comment by anunknownentity03** [comment]
hmm

**Comment by Exxion** [comment]
This is, of course, a long-requested feature.
There's a fair amount of work in just setting up the system that distinguishes between whether two Z-levels are connected or separate. It shouldn't be especially technically difficult work, but it's still work.
Multi-Z atmos theoretically already Just Works, though I've never tested it. Surprisingly, it's pretty much the easiest part to get working.
The hard part is setting up falling, stairs, displaying things across Z-levels, etc.

**Comment by drawsstuff** [comment]
https://github.com/vgstation-coders/vgstation13/pull/30178

**Comment by drawsstuff** [comment]
THEY SAID IT WOULDNT HAPPEN
