### ISSUE TITLE
Can't remove guns from depowered rechargers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28850]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
12881c5ddc67237e7b044f96b7b323b5def079c0

# Description
I noticed this in a previous round as well as other earlier rounds. When rechargers with guns on them lost power, I was unable to take the gun off the charger. The charger could be wrenched a moved, but the gun remained stuck until it was powered again.

Is this intentional or is there some way to remove the gun other than simply clicking on it?

**Comment by Kurfursten** [comment]
You should be able to kick it loose for consistency with other kicks

It doesn't do this now, someone should add it, very easy to code

**Comment by Eneocho** [comment]
> 
> 
> You should be able to kick it loose for consistency with other kicks
> 
> It doesn't do this now, someone should add it, very easy to code

Or crowbar it.

**Comment by Exxion** [comment]
Or, you could just make it so that you can take weapons out normally while it's unpowered

**Comment by west3436** [comment]
@Kurfursten this should be closed, it just wasn't referenced properly from #28862
