### ISSUE TITLE
[Feature Request] Playable spider functionality

### ISSUE THREAD

**Issue by drawsstuff** [d3athrow/vgstation13#28876]
Spiders have some... interesting AI, to say the least. Hyper obssessing over unreachable objects to the point where you can toolbox them to death is a commonly reported issue, but it's only partially the reason I'm making this. If you're somehow turned into a spider, be it through a wizard's transformation potion, or amorphous mask, you have no way to control or use your abillties. 

![here](https://user-images.githubusercontent.com/16404218/107885686-b6d7a600-6ec9-11eb-9db9-2e3ef339c7dc.png)

I made these icons a long while ago, and I'd love to see them get some use. (from left to right, spin web, cocoon object, lay eggs, spit webs, evolve into queen). 

INFO FOR CODERS (For those who don't know how spiders work. This isnt a suggestion, it's how they're currently set up and what would need to be replicated for player funtionality):

-Only green eyed spiders and queens can lay eggs. 
-Only green eyed spiders can evolve into queens
-Using the cocoon spell on a corpse should give a use of lay eggs, otherwise you should not be able to lay eggs
-Only spider queens can spit webs, and though they dont have a spell, player spiders can already use this ability by clicking a distant object
-Living mobs can be cocoon'd and succ'd as well as corpses for means of producing eggs

OPTIONAL TO DOs:

-Make player spiders a possible ghost role / blob storm type event / gamemode / ect.
-Tie player spider existence outside of potions and masks to biohazard alert level.
-Allow Nurses and Queens to heal from feeding from dead mobs

**Comment by press-mark** [comment]
![image](https://user-images.githubusercontent.com/6972764/107893843-894e3380-6f81-11eb-9e7b-56ae338834c2.png)

**Comment by drawsstuff** [comment]
As of  https://github.com/vgstation-coders/vgstation13/pull/28947, all that remains for this feature request's closure is the optional TODO's.
