### ISSUE TITLE
Lime couch outwards turn use incorrect sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28872]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
0c42ad3d79382009bca6efe11ba3680923a7d5a9

# Description
Lime couch outwards turns use the grey couch outwards turn sprite

# Steps to Reproduce
make an outwards turn lime couch

# What you Expected
a lime colored outwards couch

# What Actually Happened
same sprite as grey outwards couch

**Comment by Kharkov72** [comment]
sounds like an error in the actual sprite, which begs the question _fucking how?_

**Comment by kernikov** [comment]
All coloured couch varients have a forced 'color' var to separate them.
Lime is #bab866.
The only lime couch part without that var being set is the /obj/structure/bed/chair/comfy/couch/turn/outward/lime

I don't know if there are more broken couches.
