### ISSUE TITLE
Should open firelocks separate zones?

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#28871]
First things first: I don't personally care. Just interested in what other people think.

Most kinds of airtight doors (airlocks and windoors) block zone formation even when open. Air flows through them when open, but the zones on either side don't merge. This is for performance reasons but also has a gameplay impact because air takes time to flow between zones whereas it "moves" instantly within a zone.
Border firelocks do not block zone formation when open. ~~(I haven't bothered checking whether or not fulltile firelocks do, but I don't *think* they do.)~~ (Fulltile firelocks do, in fact, separate zones when open.) They don't really open or close often enough to be a performance concern. Honestly I don't think zone formation is even expensive enough for it to be important on regular doors either, but that's how it is. I'm just asking if, for the sake of consistency, firelocks should also separate zones.
For the record, the code change is easy. Just a couple lines.

I know from experience nobody will give a shit about this enough to respond but I'd still rather ask anyway

**Comment by mentgah** [comment]
I'd be happy if we replaced every firelock with fulltile firelocks to be honest, but this is fine too as long as it doesn't make the game lag or anything like that.

**Comment by Kromkar** [comment]
> I'd be happy if we replaced every firelock with fulltile firelocks to be honest, but this is fine too as long as it doesn't make the game lag or anything like that.

Full tile firelicks were replaced by the current ones some time ago due to reasons I dont recall right now

**Comment by Exxion** [comment]
The zone separation certainly wouldn't kill the server. Might slightly increase CPU under normal circumstances but would vastly decrease CPU when the firelocks are opened or closed.
Fulltile firelocks were replaced with border firelocks because they had a nasty habit of trapping gas inside them. When a room got flooded, the firelocks would close and trap some of the plasma, etc. on their tile, then open when the alert cleared, releasing that trapped gas and often causing another alert, closing them again, etc. There may be other ways to deal with that problem, but border firelocks don't have it in the first place.

**Comment by west3436** [comment]
Closing this as not implemented as it's been 3 years. @Exxion re-open if you want to take another look at this.
