### ISSUE TITLE
[Box] Phalanximine bags still in medbay

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2888]
Sorry if I'm mistaken but were these not made obsolete when cancer was removed?

**Comment by Probe1** [comment]
I asked about this a few months back and the answer from headmins was they were a tribute to the bullshit the cancer PRs caused.

It would be nice if they were put to rest and a single bag was left in the CMOs office, instead of a dozen things you should toss in the bin every round.

**Comment by SarahJohnson489** [comment]
Look at this and guess what really works good as an additive in a rapid tox purge

		phalanximine
			name = "Phalanximine"
			id = "phalanximine"
			description = "Phalanximine is a powerful chemotherapy agent."
			reagent_state = LIQUID
			color = "#1A1A1A" // rgb:idk

			on_mob_life(var/mob/living/M as mob)
				if(!M) M = holder.my_atom
				M.adjustToxLoss(-2*REM)
				M.apply_effect(4*REM,IRRADIATE,0)
				..()
				return

Look at that and find the very important bit. It needs to stay

**Comment by Probe1** [comment]
Sarah it causes massive but buggy radiation damage.  It's not special and doesn't have a medicinal or malicious use.  It's just a poorly coded memorabilia item.

**Comment by SarahJohnson489** [comment]
Just went through it to make sure it's still good

Tox'd the shit out of a monkey human. IV'd a little phalanxamine in, checking the IV bag to not put in overkill, with a 20/20/10 AT-Tricord-arithazine pill. It's faster than just plopping an anti-tox pill in, cryo tox heal and you'll be getting even more if you load him up then plunk him in.

Scanned him when he was done an rad level was at 2. Well below any harmful level. Tricky murder chem or underused addative? You decide!

Nice to have more chems to hold down the tox damage from critically low blood patients too.
![0 blood 100 healthy](https://cloud.githubusercontent.com/assets/5564796/6162337/aeebeb04-b22d-11e4-839a-993ecd0fe0d5.png)

**Comment by 9600bauds** [comment]
Issue fixed, can be closed now.
