### ISSUE TITLE
Consider making the requirements for snaxi harder to meet

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#28889]
overplayed gimmick map

**Comment by PavelCIA** [comment]
>what is global warming

**Comment by DamianX** [comment]
Good point: by keeping snaxi locked behind new york's temperature I am incentivized to burn coal and oil. We can conclude that the existence of snaxi in its current form is unethical.

**Comment by GreatBigFailure** [comment]
I like Snaxi as an occasional little break and bit of variety. Maybe once every 2-3 days tops. The amount it fires off makes it stale though. Remove one snaxi vote for every snaxi round that happened that week.

**Comment by BomberBro** [comment]
But then what am I supposed to vote for before I leave?

**Comment by APCUnlocked** [comment]
Deff and or packed. Snaxi is poo though so hopefully *something* will be done about it

**Comment by Eneocho** [comment]
> 
> 
> But then what am I supposed to vote for before I leave?

There was a time when the griffvote was horizon. Boy I miss the times when Horizon was the worst map.

**Comment by Kurfursten** [comment]
![image](https://user-images.githubusercontent.com/9782036/108800287-4fb89200-7558-11eb-91c7-4b3e9dd9d418.png)
It takes a special kind of seething to look at this data set and say "Snow is overplayed".

**Comment by DamianX** [comment]
can you look at the shifts for a week before I created this issue?

**Comment by Kurfursten** [comment]
In that case, it only goes up to 7, or once per day, compared to 41 Box in the same period. But even if this weren't the case and the numbers didn't make you look silly, trying to permanently restrict voters' access to a map (when it already has one of the most restrictive sets of two combined restrictions) based on a single anomalous week would be very reactionary. Akin to removing the shard from cargo crates because it gets popular to shardbomb for a week.

**Comment by DamianX** [comment]
That (restricting shards from cargo) sounds like something I would wholeheartedly support if it proved to be an issue (which it isn't). I disagree with the notion that "reactionary" actions are inherently bad. I see an issue, I solve it. I don't care if you want to reject the solution because it's been submitted too soon after the issue has been identified, I simply don't consider that a valid counterargument.

Aside from that, thank you for providing the data as I never would have gone out of my way to find it myself. I would have liked to see the full data for the week that prompted me to create this issue, but I fully understand you're under no obligation to further entertain my insane ramblings, you've already been kinder to me than I can guarantee I would have been in your position.

I have been glad to see the frequency of snaxi rounds this week decrease, no doubt.

If people don't consider this an issue you can go ahead and close this, of course. I won't be offended.

**Comment by Kurfursten** [comment]
Here's the full data if it helps
![image](https://user-images.githubusercontent.com/9782036/108958170-35ee7c00-7638-11eb-90e4-7b5fcdd9a8b0.png)
Snaxis per day
2/11: 2
2/12: 1
2/13: 1
2/14: 0
2/15: 1
2/16: 1

This actually totals to 6, I guess I counted one twice before.

Both sets combined:
![image](https://user-images.githubusercontent.com/9782036/108958491-aeedd380-7638-11eb-999c-14133a615f08.png)

**Comment by west3436** [comment]
The Snaxi discussion has been held numerous times and has resulted in several player polls.
