### ISSUE TITLE
The ol' Dense Houdini

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28884]
(WEB REPORT BY: rubylips REMOTE: 206.221.180.138:7777)
# Description
If you mutual cuff two people, one of them is put in a cage, and the other moves the cage person will perform the greatest show on earth and escape the cage.
The person is still considered in the cage though. They act like they are locked to the atom, effectively making them completely immovable except for by the handcuff partner.
Also if the cage moves they teleport back into it.

# Steps to Reproduce
1. Handcuff yourself to man
2. Cage man
3. Leave man
4. Man leave cage

**Comment by Exxion** [comment]
If this happens for cages but not chairs, I don't even want to know the shitcode involved

**Comment by Exxion** [comment]
```
		//if pulling somebody who is buckled force them out of the buckled structure
		var/obj/structure/bed/locked_to = src.locked_to
		if (locked_to && istype(locked_to))
			locked_to.manual_unbuckle(src)
```
Why

**Comment by Rubylips** [comment]
Why doesn't it just break the cuffs? It was specifically commented to say it's intentional. Mutual cuffing is a special kind of broken.
