### ISSUE TITLE
Holy water is too holy to react with potassium

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28886]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
f9e70f0b79bed274003cae9dbbd2980ce20a47ca

# Description
holy water doesn't react with potassium
# Steps to Reproduce
mix holy water with potassium
# What you Expected
holy hand grenade
# What Actually Happened
potassium and holy water beaker

**Comment by Kammerjunk** [comment]
well it's a completely different reagent

**Comment by tomacatx2** [comment]
ye but waters in the name, should do what it says on the tin

**Comment by DeityLink** [comment]
I don't know how many features will break if we try to fix it by making holy water a child of water

**Comment by ghost** [comment]
feature

**Comment by Exxion** [comment]
Reactions work by ID, not type, so making holy water a child of water wouldn't even change this
On the other hand, this can also be easily changed without making holy water a child of water by just changing the reaction to accept either water or holy water.

**Comment by Eneocho** [comment]
> 
> 
> I don't know how many features will break if we try to fix it by making holy water a child of water

Just add a new reaction of holy water+potassium, the same way the plasmabeakers have their own reaction.
