### ISSUE TITLE
Rag Smothering is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28890]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
f9e70f0b79bed274003cae9dbbd2980ce20a47ca

# Description
Date rape is no more

**Comment by Dacendeth** [comment]
just tested it, it worked for me, you know it doesnt work if the target has anything on their mouth slot like a cigar or breathe mask.

**Comment by drawsstuff** [comment]
didnt work for me, i removed the mouth objects, even used it on myself
5 units gloral in a rag

**Comment by Kromkar** [comment]
> didnt work for me, i removed the mouth objects, even used it on myself
> 5 units gloral in a rag

So desperate you try and roofie yourself

**Comment by mentgah** [comment]
worked on my machine

**Comment by DamianX** [comment]
I tested this on the server during the same round, mixed results:
- Worked on a naked body
- Worked after I equipped the security officer loadout datum
- Didn't work after I put a cigar and a helmet
- Didn't work when I removed the helmet
- Didn't work when I removed the cigar (so it's the same as having the security officer loadout and nothing else, but this time it didn't work)
basically wtf

**Comment by drawsstuff** [comment]
> I tested this on the server during the same round, mixed results:
> 
> * Worked on a naked body
> * Worked after I equipped the security officer loadout datum
> * Didn't work after I put a cigar and a helmet
> * Didn't work when I removed the helmet
> * Didn't work when I removed the cigar (so it's the same as having the security officer loadout and nothing else, but this time it didn't work)
>   basically wtf

so it seems it stops working when you've had something in your mouth _at one point_

**Comment by Exxion** [comment]
I don't even see code in there that checks if there's anything in the mouth slot. It just checks if you're selecting the mouth and that the rag contains reagents (and, for some reason, that the target mob has a `reagents` datum)
Also, what the fuck is this file
>footprints_and_rag.dm

It's also just a huge fucking mess
There's no `do_after()`, it just works immediately and then, for some fucking reason, clears the rag's reagents half a second later

**Comment by Exxion** [comment]
I can't reproduce this at all. Works every time for me, as long as I refill the rag each time.

**Comment by DamianX** [comment]
`src.reagents.reaction(M, TOUCH)`
something something permeability

**Comment by Exxion** [comment]
Yeah sounds about right

**Comment by drawsstuff** [comment]
https://files.catbox.moe/ajjst5.mp4

**Comment by DamianX** [comment]
Basically because it uses a `TOUCH` reaction, it has a chance to not do anything depending on what clothes the guy is wearing. So it's possible for the guy's shoes to cause the rag to the mouth to fail. One possible fix would be to implement more ad-hoc logic for the rag specifically, or to make permeability checks less garbage in general.

**Comment by Exxion** [comment]
Notably, most gloves have extremely low permeability
Also, for the record, you don't have to wait for the progress bar. The smothering happens immediately. The progress bar is for wiping them with the rag.

**Comment by Eneocho** [comment]
> 
> 
> Also, for the record, you don't have to wait for the progress bar. The smothering happens immediately. The progress bar is for wiping them with the rag.

Wouldn't want the RapeRag victim to be dirty.
