### ISSUE TITLE
Toolbox Recyling allows for easy brain destruction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28896]
(WEB REPORT BY: yvvel REMOTE: 206.221.180.138:7777)
# Revision
851bbea25d6220a1fb55474d16c0e5bde09b3cdf

# Description
this might just be an oversight, but if you decapitate someone, stuff their head in a toolbox, and then stuff the toolbox into an autolathe, it'll eat the toolbox and destroy the contents. 
# Steps to Reproduce
decap->put into toolbox-> recycle-> profit and get added to someone's metagrduge list
# What you Expected
it to spit out organic matter
# What Actually Happened
the lathe ate it and then proceeded to ask for more

**Comment by APCUnlocked** [comment]
you can just eat brains so this is a feature

**Comment by Killette2** [comment]
> you can just eat brains so this is a feature

Do you even have to cook them anymore?
Besides this there's a ton of ways to get rid of a brain and it even dies after a while. Having it in your bag will likely have it die before you ever get caught

**Comment by Blithering** [comment]
This does seem like an issue, there's more things than brains you wouldn't want to vanish. Maybe just have the toolbox drop it's contents when being Recycled.

**Comment by west3436** [comment]
Fix implemented via #31593 as items now are dumped out when they are recycled.
