### ISSUE TITLE
Corporate lawset

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28897]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
851bbea25d6220a1fb55474d16c0e5bde09b3cdf

# Description
the law of of Corporate is supossed to be maximize profits but it's still minimize expenses

# Steps to Reproduce

Upload Corporate 

# What you Expected

To have the law 4 be maximize profits

# What Actually Happened

still the old law 4 despite the PR being merged

**Comment by ShiftyRail** [comment]
That's because you didn't change the actual board, just the `/datum/ai_laws`. You want to modify `/obj/item/weapon/aiModule/core/corp`.

**Comment by DeityLink** [comment]
Fixed by #28903
