### ISSUE TITLE
You can greytide implant Syndicate Challengers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28900]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
851bbea25d6220a1fb55474d16c0e5bde09b3cdf

# Description
Syndicate Traitors can't be implanted but challengers can, leading to someone having protect and kill objectives for the same person.

**Comment by Eneocho** [comment]
I'm betting on this being a fuckup, but it could be reworked into a feature. 
If you implant your target, he/she is defeated, since they can no longer kill you/the next on the chain.

**Comment by west3436** [comment]
feature

**Comment by DeityLink** [comment]
Gonna have to patch this out because this is an administrative nightmare.
