### ISSUE TITLE
Vox ATM's eats cash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28902]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
851bbea25d6220a1fb55474d16c0e5bde09b3cdf

# Description
Using the normal withdraw on the vox ATM makes it send to your virtual wallet, except it doesn't. It will even show the withdrawl on your PDA virtual wallet but it flags like you alrady recieved the physical credit
# Steps to Reproduce
Withdraw regularly from the ATM
# What you Expected
my cash on the floor
# What Actually Happened
The Vox Shoal just took my cash and didn't give me anything, business as usual.

**Comment by SkowronX** [comment]
feature

**Comment by beesil** [comment]
working as intended

**Comment by Kurfursten** [comment]
There is no difference between Vox ATMs and normal ATMs besides a var-edited description.

I'm guessing this is probably user error but it should be tested just in case ATMs are eating money somehow

**Comment by Eneocho** [comment]
The one time I had this problem, of ATMs not dispensing money, was because of a map issue. The credits were dispensed under a door, 2 tiles away from the ATM. Perhaps a similar problem happened here?
