### ISSUE TITLE
Thermal vision not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28909]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
2a626894a71f0d183204750a8f026bc80d048038

# Description
thermal vision does not work. Possibly related to having insectoid character slots. Vampire bugs dont get thermal vision when they suck enough blood and getting sucked into a xenomorph while observing from an insectoid character slot gave me a xeno without thermal vision.

# Steps to Reproduce
be xeno

# What you Expected
have thermal vision

# What Actually Happened
no thermal vision

**Comment by APCUnlocked** [comment]
Just had the same happen to me. Really hope this gets fixed at some point.
