### ISSUE TITLE
Mech punches don't damage objects (windows, walls, etc..)

### ISSUE THREAD

**Issue by githubuser4141** [d3athrow/vgstation13#28913]
#### What you expected

A durand to be able to break a fragile window or, perhaps, a wall if that's considered to be balanced fairly easily.

#### What happened instead

Hitting a window multiple times in a gygax, durand, seraph, w/e results in no damage to the window.

#### Steps to reproduce

1. Spawn a combat mech.
2. Mount a lethal gun on it (this is required for mech punches) and click a window
3. Make sure it doesn't _shoot_ the window
4. Nothing happens

**Comment by pedr69** [comment]
>Mount a lethal gun on it (this is required for mech punches) and click a window

i can punch just fine withut any guns on the thing
