### ISSUE TITLE
Synergy Station: Door access issue.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28911]
(WEB REPORT BY: xevonix REMOTE: 206.221.180.138:7777)
# Revision
4eb95736bf3df443de11a9249df11b62fed58e39

# Description
The kitchen maintenance door has no id restrictions on it so even an assistant can open it. Without an ID you cant open it but with an assistants ID you can.
# Steps to Reproduce
Open the kitchen door to maintenance with an assistants access ID.
# What you Expected
Door go beep beep.
# What Actually Happened
Door go whoosh.

**Comment by Kammerjunk** [comment]
probably needs the map specified

**Comment by DeityLink** [comment]
not sure which door is the problem here, the kitchen backroom only allows the chef to access it 
![image](https://user-images.githubusercontent.com/7573912/129987433-a4c71432-6807-4237-80ba-2f7e8792a284.png)

**Comment by DeityLink** [comment]
Remember fixing that specifically @Viciousaurus ?
