### ISSUE TITLE
Secure safes are now too secure due to UI failure

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28916]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
d59886e4bd0382cad24b75502884024bec978b79

# Description
The keypad on the secure safe doesn't load. I think I'm the only one who still uses them, so this may have been like this for a while.
# Steps to Reproduce
Click on a wall safe.
# What you Expected
Please enter new combination
7 8 9
4 5 6
1 2 3
# 0 .
# What Actually Happened
please enter a new combination

**Comment by Kurfursten** [comment]
@ShiftyRail Almost certainly caused by https://github.com/vgstation-coders/vgstation13/commit/1aeef36c458078b647bbf3018d7e8497639a1942#diff-94d0de271827b212dc073436984308dfacf8d9e39816c2ffc622c017ec3809cd
