### ISSUE TITLE
Feature request: Have ninja poll ghosts before recruiting latejoins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28910]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
2a626894a71f0d183204750a8f026bc80d048038

At the moment, latejoin players are recruited as ninjas. Ninjas are a notoriously short lived antagonist, so this typically results in a latejoin player getting killed 2 minutes into their round and remaining dead for the duration of the round. The idea here would be to poll ghosts for candidates before recruiting a latejoin, similar to how catbeast and wizard apprentice work.

**Comment by Kurfursten** [comment]
Ninja already does this, it's called midround ninja. We have two separate antag timers for midround antags and latejoin antags.

**Comment by DeityLink** [comment]
Many such cases, just like we still have random event NPC spider infestations/blob storms and midround event ones, it's intended.
