### ISSUE TITLE
Some machinery can't be unbolted and moved

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#2892]
In the case of some machines, the usual "use wrench on" method to unbolt them does not work since they try to interact with the wrench (This probably won't blend!) or, in some cases, the functionality is just mysteriously absent.
The result is machinery that can't be moved, when similar machines can be moved or it seems like you should be able to drag it somehow.
Off the top of my head:
>Food processor (gibber can be moved)
>All-in-One Juicer - DONE
>SmartFridge (The SmartFridge smartly refuses the wrench - booze-o-mat can be moved) - WOULDN'T WORK VERY WELL SINCE IT'S INSIDE A WALL, UNLIKE THE BOOZE-O-MAT
>SnackBar Machine (every single other chemmaster variation can be moved so I don't know why precisely this one is borked) - DONE
>Seed Extractor
>Bioballistic Delivery System & Lysis Isolation Machine - DONE

**Comment by ComicIronic** [comment]
There are also instances of wrenchable machines not using the general code.
If someone wants to do a little cleanup, I'd appreciate that being fixed as well.

**Comment by clusterfack** [comment]
To be clear the machines that cant be constructed shouldn't be movable in my opinion as it can lead to easy grief when you steal unreplaceable machines.
