### ISSUE TITLE
[Feature Request] Carp breeding in Xenobio.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#28925]
[featurerequest] 
Given that Xenobio works with dangerous life for resources and profit, they could also start with a few carps in a separate room, for carp breeding. Perhaps carp eggs to start the breeding/harvesting.

**Comment by Apogee-dev** [comment]
Makes sense for the department and gives players more reason to try out a feature that almost never gets used. I'm for it.

**Comment by DrSnips** [comment]
A nice concept but since they instantly go hostile and break out I don't see it going very far. It would require a good supply of carp pheromones in order to even start.

**Comment by Eneocho** [comment]
> 
> 
> A nice concept but since they instantly go hostile and break out I don't see it going very far. It would require a good supply of carp pheromones in order to even start.

What if Xenobio starts with a beaker-full of pheromones and some carp eggs? The eggs hatch if warm on a low pressure environment or something (something something, normal carps are born on space, with no atmosphere, so low pressure and warmth from the parent carps).

**Comment by ghost** [comment]
miners are way better at this anyways, whats the point

**Comment by west3436** [comment]
Both attempts to implement this were rejected

**Comment by Eneocho** [comment]
> Both attempts to implement this were rejected

In actuality it was only one attempt but I was retarded and had tried mapping it with no atomicity, then the atomic remap. I was suggested to try again now that a good while has passed since, but I haven't had the time.
Keep it closed either way.
