### ISSUE TITLE
Human prisoner was sent with nitrogen tank, literally gassed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28921]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
d59886e4bd0382cad24b75502884024bec978b79

# Description
Human prisoner filled with vox gas.
# Steps to Reproduce
1. spawn prisoner
2. roll human
3. get gassed
# What you Expected
oxygen
# What Actually Happened
nitrogen

**Comment by Rubylips** [comment]
Act like a vox get treated like a vox

**Comment by Kurfursten** [comment]
@ShiftyRail
