### ISSUE TITLE
Plasmaman blood on your hands

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28932]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
81aad06580cd937be6a4d7d811ee0445e2ee46d4

# Description

When you do surgery on a plasma man the plasma bood sprite never comes out of your latex gloves, likely due to them not having blood
# Steps to Reproduce

Do surgery on plasmeme wearing gloves
# What you Expected

To wash the blood out
# What Actually Happened

My hands are forever tainted.

**Comment by Kurfursten** [comment]
Out, damned spot!

**Comment by Eneocho** [comment]
Call it plasma instead of blood then clean it using bleach. Boom, now it's a feature.
