### ISSUE TITLE
Gult Nymphs can not shade

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28945]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
a0fc71b279ceb41c8c5387b08e60d2cc4f15bef8

# Description
Diona Nymph cultists can not shade once they die
# Steps to Reproduce
1. convert nymph
2. kill
3. they cant escape their mortal coil
# What you Expected
a second chance at life
# What Actually Happened
death

**Comment by DeityLink** [comment]
Yeah, monkey cannot either, can't recall if there was a specific reason for it.

**Comment by DeityLink** [comment]
Honestly I think it's better like this.
