### ISSUE TITLE
Pressing the Unbuckle Button in Top Right while holding an item hits you with the item

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28946]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
a0fc71b279ceb41c8c5387b08e60d2cc4f15bef8

# Description
Buckle into a chair and then take out a knife. Have knife in hand. Press unbuckle button in top right. You have now stabbed yourself.

**Comment by jknpj** [comment]
This is hilarious

**Comment by Eneocho** [comment]
I always thought this was a feature. Was it not?

**Comment by ghost** [comment]
i feel like this has been around for ages
