### ISSUE TITLE
Really Good Inhand Sprite for Left-Handed Ithaqua Bible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28959]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
presented without comment

**Comment by Dacendeth** [comment]
a lot of the bible sprites are fucked.

**Comment by DeityLink** [comment]
> 
> 
> a lot of the bible sprites are fucked.

I'm gonna need you to be more specific. Couldn't find the same problem the Ithaka had on other bibles.
