### ISSUE TITLE
Headless nymph sprite glitch.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#28960]
Immulshons shattered. 
[sprites] [bugfix]
![The Legend of the Headless Nymph](https://user-images.githubusercontent.com/67024428/109736026-8159da80-7ba2-11eb-8ef1-dfdd249710f5.png)

**Comment by SageOfLight** [comment]
That'sa penis.

**Comment by Dacendeth** [comment]
that's just what they look like resting

**Comment by Eneocho** [comment]
> 
> 
> that's just what they look like resting

We were talking, diona fella wasn't resting.

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/115047039-235d2a00-9ea6-11eb-8576-da7a58876630.png)
that's literally what they look like while **resting** not **sleeping**
