### ISSUE TITLE
[Feature Request] Using a filled pill collector on a reagent container crushes the pills into it.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#28968]
There's a particular type of pain you get when you make pills and brand them wrong, only to have to manually crush all 18-20 ones into the beaker/cauldron.

[featurerequest] [qol]

**Comment by west3436** [comment]
the pill collector drops pills into the grinder, just use that you ape
I will not stand for this endless pill collectorcreep

**Comment by Kurfursten** [comment]
@west3436 's solution also protects against **really** trivial griff where you quickly craft a cauldron next to the smartfridge, then in seconds melt the entire fridge stock

**Comment by Eneocho** [comment]
> 
> 
> the pill collector drops pills into the grinder

It does? Well fuck me then.
