### ISSUE TITLE
They Don't Think It Is Be Like It Is, But It Do.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28974]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
95d8be14ca09fd3f484043d82c6047571074c5ea

# Description
Remember when Celt added that event that makes the shuttle unable to be called? And it had that long fancy sound play? Well whoever changed it sucks at grammar.
# Steps to Reproduce
Fire the central command link failure event, listen to vox and read the words.
# What you Expected
The shuttle is unable to be called
# What Actually Happened
the shuttle is be unable to be called

**Comment by N3X15** [comment]
On it.
