### ISSUE TITLE
Amogus sprite is broken

### ISSUE THREAD

**Issue by Pspiotrek** [d3athrow/vgstation13#28970]
#### Description of issue

When you turn from initial position amogus sprite turns invisible

#### Difference between expected and actual behavior

I expected amogus. I turned invisible. Please make it look the same whatever direction you face.

#### Steps to reproduce

1. Be amogus
2. Turn

#### Specific information for locating
amogus

#### Length of time in which bug has been known to occur
 
It never worked I guess

**Comment by kernikov** [comment]
sus

**Comment by Kurfursten** [comment]
Unable to reproduce on live
