### ISSUE TITLE
Medibots skins are missing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28984]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
ff0589ffdc31642dae69da994d838a293aabb3c0

# Description
Medibots are always same skin no matter what medkit you use
# Steps to Reproduce
Make medibot with different medkits for different favorite damage type and different colors.
# What you Expected
green medibot, blue medibot, yellow medibot.
# What Actually Happened
white medibot, white medibot, white medibot.

**Comment by DeityLink** [comment]
Oh yeah I noticed that the other day. I'll see to it.
