### ISSUE TITLE
Borg bumping is borked

### ISSUE THREAD

**Issue by Shaska-** [d3athrow/vgstation13#2899]
Borgs are suddenly able to switch places with each other as well as humans when bumping into them, where before they were unable to switch places unless a human bumped into them.
It also broke our ability to walk into chargers. Right-clicking is the only way to get into them currently.

**Comment by ComicIronic** [comment]
I'd argue the first one isn't an issue.

As for the second, I knew I forgot something from the robot code.

**Comment by d3athrow** [comment]
Default mob action for byond on Bump is to swap places with each other.

**Comment by Shaska-** [comment]
First one isn't much of an issue, but it did give a bit of flavour to borgs.
I liked it at any rate.
