### ISSUE TITLE
Radio Transmitters are busted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#28999]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
7f246dd2599ee10533f9cf809968dffa81bfacac

# Description
The on-station radio transmitter never seems to work.

# Steps to Reproduce
Set up cooling loop for transmitter room, ensure APC in the room is charged, and even check for a powered cable beneath the transmitter.
Link transmitter with jukebox, turn the power on via multitool.

# What you Expected
Music to play throughout the halls.

# What Actually Happened
Radio Transmitter hums as it begins pumping energy into the air!

Radio Transmitter falls quiet and makes a soft ticking noise as it cools down.

**Comment by west3436** [comment]
For reference this was the transmitter in Roidstation, but I've also had this same problem with the one on Box as well so I don't think it's map related.

**Comment by Kurfursten** [comment]
This happens if you previously let it heat up too much and let it get damaged. You need to repair it with a solder.

**Comment by west3436** [comment]
What temperature does it take to overheat? Perhaps something could be added to show it has been broken?

**Comment by Kurfursten** [comment]
Overheats at 70C. Once it takes 100 points of damage it will shut off and has to be repaired, otherwise it will immediately shut off again.

Yes, a more descriptive message could be added.

**Comment by west3436** [comment]
The room it was in was like 25C max, I'm not sure how it could've heated up that much

**Comment by Kurfursten** [comment]
If someone ran it before you showed up it could have damaged it previously. It also shuts off instantly if you cut both radiation wires. If you can cause this to happen again, ahelp and ask the admin to check the integrity var (or solder it yourself)
