### ISSUE TITLE
Virology Airlock Access panel is inaccessable if firelock is down.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29001]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
7f246dd2599ee10533f9cf809968dffa81bfacac

# Description
The main virology airlock access panel is facing south (into inner airlock) instead of into the room, so if the firelock is down it is inaccessible.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
Bro name the fucking map
I'm guessing from context that it's NuBagel but please just include the name
