### ISSUE TITLE
You can blow up empty fuel tanks.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29000]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
7f246dd2599ee10533f9cf809968dffa81bfacac

# Description
why do they blow up they have no FUEL

**Comment by Dacendeth** [comment]
They blow up for a smaller explosion at least.

**Comment by Eneocho** [comment]
Petition to make empty weldertanks have a 20 percent chance to explode harder.

**Comment by APCUnlocked** [comment]
feature, the fumes explode

**Comment by DeityLink** [comment]
> 
> 
> feature, the fumes explode

Let's go with that then. The explosion does get weaker the less fuel there is.

![image](https://user-images.githubusercontent.com/7573912/129407981-02363bc6-0a3c-4428-9c71-e280d8693b42.png)
