### ISSUE TITLE
Cloned vampires lose spells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29003]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
7f246dd2599ee10533f9cf809968dffa81bfacac

# Description
When cloned as a dead dusted vampire, I lost all my spells except newly acquired ones afterwards
# Steps to Reproduce
1. Be vampire
2. Get spells 
3. Die permanently
4. Come back as scanned clone
# What you Expected
To keep my spells
# What Actually Happened
Got cucked out of them

**Comment by boy2mantwicethefam** [comment]
You clone a corpse and are surprised that the resulting thing is alive?
