### ISSUE TITLE
lowfatBagel permabrig can be teleported into

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29018]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
7cf95d4e3cb08da785c7217dc743210fe3f6a9d9

# Description
i'd assume that a prisoner shouldn't be able to get teleported out but it werks
# Steps to Reproduce
be in prison
smoke maltys teleports in with a toolbox

# What you Expected
that not to happen

# What Actually Happened
smoke got owned LOL

**Comment by GenericGoose** [comment]
i codedived recently to research telesci and from what I could find perma isn't actually a protected area

**Comment by gurfan** [comment]
This is the same on all maps, yeah.
