### ISSUE TITLE
MoMMI nest light is off on boxstation roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29022]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
7cf95d4e3cb08da785c7217dc743210fe3f6a9d9

# Description
When joining the round as MoMMI, the light was not on in my nest
# Steps to Reproduce
1. Ready up as MoMMI when it's box
2. Spawn in nest
# What you Expected
The light to be on
# What Actually Happened
Left in the dark with only the glow of the R&D console lighting the way

**Comment by Kurfursten** [comment]
Feature

https://comb.io/CRf12F

**Comment by Dacendeth** [comment]
crabs are not real
