### ISSUE TITLE
[Bug?] Occupation chances on setup character didn't work right?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2902]
I had CMO set to low and Shaft Miner set to medium.  Recently and as long as I remember, that means it would check to see if there is a empty Head slot first, then go to non-head positions.  When I joined however, it sent me to shaft miner and the station had no CMO.  It should have put me in the CMO slot instead of shaft miner.

It's really strange, and Senaat said he's heard of similar things happening.

**Comment by d3athrow** [comment]
job selection code has not changed but i'll take a look

**Comment by clusterfack** [comment]
If you had set CMO to medium you would have gotten it, job selection code is shit like that.

**Comment by Probe1** [comment]
Yes but previously heads were polled before non-heads.

**Comment by d3athrow** [comment]
Still is the case, order is.

>assistants

>heads

>AI

>everybody else

**Comment by clusterfack** [comment]
They still are, the fact you set it to low made it so you wont get it that often. If you have a head role set to medium you get it almost every time.

**Comment by Probe1** [comment]
If you say so but I still think somethings borked.
