### ISSUE TITLE
Gourmonger rads too fucking strong.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29035]
With a steady-ish supply of food, they released 20-25 rads per tick, killing unprotected people via rad poisoning in less than 20 seconds or so.

**Comment by GreatBigFailure** [comment]
They most certainly are. It's 1am so I can't fix it now but I'll just change the "This I guess" number into a "That I estimate" number in the morning.

**Comment by Killette3** [comment]
The problem is how easy they are to mass. Perhaps they should be coded as expected to be mass farmed?

**Comment by robintime** [comment]
pr #29037 fixes the radiation issue, as well as makes gours split slower. closing now!
