### ISSUE TITLE
SIlicon bumping into other mob behavior.

### ISSUE THREAD

**Issue by d3athrow** [d3athrow/vgstation13#2903]
>Borgs are suddenly able to switch places with each other as well as humans when bumping into them, where before they were unable to switch places unless a human bumped into them.

Reposting due to me fixing half the original issue.

**Comment by ComicIronic** [comment]
So what did they do?
Push the other mobs around?

**Comment by AutismSpider** [comment]
mommi/cyborg just switch's spots with the mob 

yes you can put people into walls/windows etc

**Comment by ComicIronic** [comment]
You misunderstand. I was asking what the functionality was before the changes to silicons.

**Comment by AutismSpider** [comment]
They would push mobs they walk into
