### ISSUE TITLE
[Bug] Vox Raiders objective didn't complete

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2905]
![ss 2015-02-08 at 11 47 10](https://cloud.githubusercontent.com/assets/8550416/6101209/ef06172e-afed-11e4-9883-cc9590c652c6.png)

We sent the ship back to deep space and I was holding 100 plasteel in my backpack.  It didn't count it towards the victory.  The code probably needs to be more robust and check mobs for the items.

**Comment by clusterfack** [comment]
I think I could fix this easily
