### ISSUE TITLE
NEED HELP FROM DAMIAN

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29058]
(WEB REPORT BY: secretoftheshapka REMOTE: 206.221.180.138:7777)
# Revision
02ff588d59b3c560c685d9ca75e882d32a72d8cb

# Description
I CANT TALK
# Steps to Reproduce
ADMINHELP DAMIAN
# What you Expected
I ADMINHEDLP
# What Actually Happened
HDE MUTED ME FROM EVERYTHING

**Comment by Eneocho** [comment]
You will become a person for the records
