### ISSUE TITLE
NEw feature suggestion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29060]
(WEB REPORT BY: secretoftheshapka REMOTE: 206.221.180.138:7777)
# Revision
02ff588d59b3c560c685d9ca75e882d32a72d8cb

# Description
ghosting twice

# Steps to Reproduce
ghost once
ghost twice

# What you Expected
something cool, maybe a new ghost sprite, ghost hell, destroying ur previous ghost? idk possibilities are endless
# What Actually Happened
nothing because it is not a feature yet, damian wont help someone take it up

**Comment by ghost** [comment]
I kinda had an idea similar to this, an observer chat seperate to ghost chat where you can't join the round at all but get access to more round info, like who's traitor and etc

**Comment by Eneocho** [comment]
Ghost 2: Electric Boogaloo: Now it is personal.

**Comment by kilozombie** [comment]
![image](https://user-images.githubusercontent.com/6062247/112498204-8a723d80-8d43-11eb-87a7-dcd3837d98e0.png)

**Comment by DeityLink** [comment]
You might want to give this a more descriptive title.

**Comment by west3436** [comment]
Resubmit with more info rather than a general thought.
