### ISSUE TITLE
AME

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29061]
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
02ff588d59b3c560c685d9ca75e882d32a72d8cb

# Description

The AME aren't deploting correctly and only make one core out of the 12 starting boxes you are given on box station
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
Try the refresh parts button.  You now have your 2 cores.

**Comment by robintime** [comment]
duplicate of #8510
like eneocho said, the fix we have right now is to press refresh parts on the AME control unit, which works pretty well
