### ISSUE TITLE
Gumshoe Not Showing Blood in Color

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29062]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
02ff588d59b3c560c685d9ca75e882d32a72d8cb

# Description
it's in the name.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
known for a while, nobody has taken the time to fix it, since overlays are a pain.

**Comment by robintime** [comment]
duplicate of #28603
