### ISSUE TITLE
simple_animal/hostile/ginger needs a sprite or to self-delete

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#29064]
Yes I spawned one without realizing it and couldn't delete it before it killed like five people, how could you tell?

Currently it's invisible to alt/rightclick as well and doesn't really show up on the mob list, so I couldn't figure out how to get rid of the thing nor realize it was there until it was too late.

**Comment by KingofHONK** [comment]
based

**Comment by Exxion** [comment]
Self-deleting is a no-go so someone get it a sprite or just paste one of the existing ones on it

**Comment by Exxion** [comment]
Oh wait that would break `existing_typesof()` wouldn't it
Maybe you should just not spawn it

**Comment by DeityLink** [comment]
Many such mobs should not be spawned directly. The default Giant Spider is another one.
