### ISSUE TITLE
lowfat bagel IAA Office has no stamp

### ISSUE THREAD

**Issue by Optimism333** [d3athrow/vgstation13#29066]
An official department stamp is one of the few tools that an IAA gets in their office on round start to do their very important job of writing official-looking paperwork and sending faxes. It seems Centcomm forgot to add one to this station's budget. Please fix this, if possible.

**Comment by plosky1** [comment]
This has already been fixed and can be closed.

**Comment by Optimism333** [comment]
Thanks for letting me know. Closed
