### ISSUE TITLE
HELP GOURMONGERS CAN COME OUT OF GOLD SLIMES

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29094]
(WEB REPORT BY: chaklet REMOTE: 206.221.180.138:7777)
# Revision
3abb1d9be42594e461b9353ebc952e3c1f3d96b9

# Description
gourmonger come out ofgold slime

# Steps to Reproduce
1. have bad luck with blood and gold slime

# What you Expected
1. funny pet

# What Actually Happened
1. MEAN PET

**Comment by APCUnlocked** [comment]
feature, don't fly too close to the sun or you'll end up burning

**Comment by Eneocho** [comment]
I would either add a "DONT TARGET" whitelist to the gours if spawned from gold slimes or blacklist the gours from gold slimes.

**Comment by Exxion** [comment]
The gold slime core reaction that produces just one creature (I don't remember which reagent it is) is supposed to make them not target the user, so if gourmongers don't respect that, that's a bug.
The reaction that produces multiple creatures doesn't do anything like that. They're expected to attack anyone.
Gourmongers are probably too strong to be reasonable for either reaction though, so they should probably just be blacklisted

**Comment by GreatBigFailure** [comment]
If I remember right I kept it so they check the normal slime stuff when looking for a target to attack, however their hungry charge thing doesn't follow the same rules. Their targeting is very odd and special snow-flakey. To make sure they keep working I might just need to blacklist them.
That said they shouldn't be attacking you regardless unless they're hungry.

**Comment by Killette3** [comment]
Drag it to the to space disposals immediately with slime heart in hand

**Comment by DeityLink** [comment]
People like it this way.
