### ISSUE TITLE
You can accidentally exit a mech via click-and-drag 

### ISSUE THREAD

**Issue by githubuser4141** [d3athrow/vgstation13#29093]
#### Description of issue

You can accidentally exit a mech via clicking and dragging the mech's icon to a floor which will instantly eject your person. This isn't an issue for 90% of mech encounters, but incredibly problematic for mech melee and when you're fighting vines with the hydraulic scythe which both require lots of fast clicking near the mech's sprite. 

#### Steps to reproduce
1. Hear about a antag/non-EMP kudzu on the radio
2. Hop into either a ripley or a combat mech to deal with it
3. (for combat mechs) Accidentally eject after furiously clicking all over the mech's adjacent sprite to stun the antag and die instantly
4. (for Ripleys against vines) Begin spamclicking the tile that the mech's sprite is sitting on while mech-strafing to avoid the cooldown and clunkiness of doing it normally. Accidentally 'catch' one pixel of the mech's sprite when clicking and eject headfirst into vampiric polytrinic acid vines. Get instantly husked.

#### Suggestion to fix

Add a small time delay to exiting a mech via the click-and-drag method or add an option to disable this ejection method completely. It can be useful in a handful of scenarios to hotswap between working mechs but isn't needed or useful most of the time, IMO.

[<featurerequest>] [featurerequest] [qol]

**Comment by Kurfursten** [comment]
There is something very amusing about wanting to take away a feature because it interferes with your use of a bug to avoid a cooldown

I prefer clickdrag exiting mechs

**Comment by githubuser4141** [comment]
> There is something very amusing about wanting to take away a feature because it interferes with your use of a bug to avoid a cooldown

> I prefer clickdrag exiting mechs


If that's a bug, then the intended gameplay consists of clicking on a tile, swinging and waiting for 1-2 seconds, then re-aligning your mech to the direction you wanted to face which is very clunky. And I suggested adding a option to disable it or a cooldown rather than just removing it.

**Comment by Dacendeth** [comment]
you click drag in, makes sense to clickdrag out.

**Comment by DeityLink** [comment]
We need a "mecha.dm" label
