### ISSUE TITLE
manifest predictor is unavailable if you leave the window open between rounds

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29106]
(WEB REPORT BY: applecrocodile REMOTE: 206.221.180.138:7777)
the manifest predictor button will not appear if you leave the window open as the server resets, you have to close the window and re-connect before it appears

**Comment by APCUnlocked** [comment]
I get that too but toggling ready will make the button appear, you can just unready after that to look at the manifest
