### ISSUE TITLE
donutgiver invisible when worn

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29105]
(WEB REPORT BY: applecrocodile REMOTE: 206.221.180.138:7777)
it just makes my hair slightly shorter but there is no helmet displayed on me

**Comment by Blithering** [comment]
Should be fixed once https://github.com/vgstation-coders/vgstation13/pull/29032 is merged.

**Comment by Blithering** [comment]
Fix PR went through, unless it's broken again this should be closeable.

**Comment by robintime** [comment]
the fix PR (#29107) works! good stuff
closing this now o7
