### ISSUE TITLE
Cargo Crate Forwarding

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#29108]
I had this idea today and I thought it would be nice for cargo lads who are having a slow shift. Lorewise the idea is that it's cheaper and more efficient for NT to send packages to the nearest station equipped with a cargo bay, who then distribute it to the next in the chain, and so on -- so that crates can be delivered without a straight shot.

In practice: there's a toggle switch on the cargo computer. When active (default: on), every time you call the cargo shuttle, it comes with additional packages that need to be forwarded besides just the ones that have been ordered for your station. Techies need to pull the crate off the shuttle, drag it onto a scanner (something flat like mech charger) for weigh-in, then stamp the manifest and send it on. Doing this will reward money to the cargo account. If something is _removed_ from the crate or you fail to forward the crate within a reasonable amount of time, your station is instead charged a penalty. Crates could come from the normal cargo list, or might be Centcomm orders, and might also include unusual special crates that could contain normally unobtainable items -- ones that might make the QM say: 'let's steal that crate'.

Why it's good:
* Gives Cargo something to do when no one is ordering
* Encourages cargo to make sure they're paying attention to what crates go where
* Adds a layer of interesting dynamic cargo where you weigh the value of bonus account money vs rare items

Anyone who doesn't want to fuss with it can just turn it off (useful in red alert situations where you just need implants and guns pronto, no distractions).

**Comment by kilozombie** [comment]
This sounds fun as fuck

**Comment by assmops** [comment]
Could also take a few ideas from `tg`, where duplicates of crates, or even entirely wrong crates, are sent for no extra charge, the shuttle can be hijacked by russians/syndie agents/escaped prisoners/etc. for a chance at a large payout to the cargo debit for the trouble, in addition to whatever loot you can scavenge from their bodies.
The real question is, how dangerous will the 'forwarded' items be? Rare mats like bluespace crystals/phazon? Traitor gear like emags? Rare and strong weapons like nikitas?

**Comment by Kurfursten** [comment]
I had in mind more like fun stuff (go karts? new content in general) rather than weapons, or things that are not necessarily strong but not normal things cargo can order directly. For example, we had a discussion in the other issue about how we wouldn't want cargo to just be able to order janicarts whenever, but it would probably be fine for this to be a possible source of them not-on-demand. Another example would be rigsuits: we're probably not at a place where we want cargo to order unlimited rigsuits, but extras showing up occasionally in forwarding would be fine. That kind of thing.

I think it sends the wrong message if a new core part of cargo's gameplay becomes "wait for the rocket launcher".

**Comment by DeityLink** [comment]
nice

**Comment by Eneocho** [comment]
> 
> 
> I had in mind more like fun stuff (go karts? new content in general) rather than weapons, or things that are not necessarily strong but not normal things cargo can order directly. For example, we had a discussion in the other issue about how we wouldn't want cargo to just be able to order janicarts whenever, but it would probably be fine for this to be a possible source of them not-on-demand. Another example would be rigsuits: we're probably not at a place where we want cargo to order unlimited rigsuits, but extras showing up occasionally in forwarding would be fine. That kind of thing.

I was thinking about that janicart PR. A solution to the powergaming that still allows for requestable janicarts would be: Janicart OG spawns on the map with no key, and you can order extra janicarts, again, with no key. Only way to acquire said key would be to join as a janitor.
