### ISSUE TITLE
[Feature Request] Telefragging

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#29102]
[featurerequest]
Making it a feature request instead of coding it due to probable controversy
Telefragging consists of gibbing or delimbing anyone standing on top of tracking beacons or telescience coordinates when someone is teleported onto them, like in quake or TF2 or something.

**Comment by GreatBigFailure** [comment]
Because of how teleporting works in SS13 I think it would be a poor fit. Usually if you open a portal in a hallway 5 people will suddenly appear on the other side 2 seconds after you go in yourself.

**Comment by Eneocho** [comment]
On my way to build a low pressure room to place my beacon to ZAS and telefrag my target and everyone nearby.

**Comment by Eneocho** [comment]
On my way to non antag PDA slip someone, drag them to the portal and telefrag them.

**Comment by gurfan** [comment]
time to silently gib everyone with telescience
