### ISSUE TITLE
Bagel has a brig evidence maint door

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#29112]
Stop doing this. 
![evidencemaint](https://user-images.githubusercontent.com/51391726/112938919-93bf2980-90f8-11eb-8c59-37eaa168fa5b.PNG)

Evidence should be the second most secure room in the entire brig, it allows sec to store stuff without turning into RPG protagonists and being forced to carry all their sick antag loot on them out of fear a guy can open one door and steal it all.

**Comment by Kurfursten** [comment]
> Evidence should be the second most secure room in the entire brig

When will we get the map that has executions and perma accessible by maint door as we deserve?

**Comment by BomberBro** [comment]
I always thought perma was supposed to be escaped, it's not very secure from the outside and doesn't really need to be. Execution is a room that our society has evolved past
