### ISSUE TITLE
teleporters can infinitely teleport the sparks of other teleporters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29110]
(WEB REPORT BY: zweikopfkatze REMOTE: 206.221.180.138:7777)
# Revision
1422282e88c6bfab4e134cd50f36a9ab99c14b09

# Description
teleporters next to each other produce sparks when teleporting the sparks when teleporting the sparks when telepo

# Steps to Reproduce
make gourmonger teleporter pen

# What you Expected
perfect gourmonger containment

# What Actually Happened
server crashed

**Comment by Eneocho** [comment]
I heard you liked sparks so I put sparks in your sparks so you can spark while you spark
