### ISSUE TITLE
Fake syndie ID buff request

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2911]
Due to the card skins of new IDs and the account system being in place instead of the old cargo points, I think fake ID's could use 2 new buffs

-the ability to change the skin of the card just like you can change the name. You can even do things like pretend to be a centcomm inspector but you still have the access of assistant unless you steal more

-the ability to attach any account number to your fake ID

This will make your fake ID more realistic unless someone decides to check it, as of right now it sticks out like a sore thumb the second it's ejected from your PDA.

**Comment by Intigracy** [comment]
/>-the ability to attach any account number to your fake ID

A++++++

**Comment by Venseer** [comment]
>-the ability to attach any account number to your fake ID
Like the same way you copy id access you copy the bank account related to it?

**Comment by Kurfursten** [comment]
@unid15 Was this handled on gitlab? If so, can this be closed?

**Comment by clusterfack** [comment]
It was
