### ISSUE TITLE
Drinks feature remove request

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#2912]
As of now, you can examine drink glasses and containers to see their contents, including the infamous item "a glass of ..what?". This ruins the possibility of sneaking a little bit of drugs or poison into a drink, as if you add a small amount to a beer for example, it still says that it is beer until a certain point until then it becomes a glass of ..what?

I'd like this to be fixed if it is a bug or revoked if it is a feature as it ruins a method of stealth completely.

**Comment by Probe1** [comment]
The point it becomes "A glass of what?" is when you've added more reagents to it than the drink you want it to be.  Keep it at 50/50 or less to prevent it.

**Comment by Unfit** [comment]
I feel like this issue isn't about the "A glass of what?" thing, more about the fact that precise amounts of liquids inside the glass are shown in the description, i.e. It contains 20 units of beer, it contains 1 unit of plasma.

**Comment by ComicIronic** [comment]
Poisoning someone isn't particularly difficult unless you mix very little drink.
The current poison system basically does what you described, except you want the limit to be raised which I think is a bad idea.

**Comment by Killette2** [comment]
I should also mention, YOU CAN EXAMINE GLASSES OF WHAT. Making the mystery of the glass also moot.

**Comment by Killette2** [comment]
*examine glass of what and see what chemicals are in there

**Comment by Killette2** [comment]
Not much discussion here but you can still examine glasses to see exactly what's in them. For example a mixed drink in the bartender, you can notice if the mix is not pure by somehow with your magic eyes, seeing that it's 40 units bilk but 10 of the units is just beer instead of the drink just being called bilk. I do not like this as even for glasses of what, which are a weird mix of whatever, can be examined to be identified without pouring them into a beaker causing easy metagaming.

**Comment by Kurfursten** [comment]
@Killette2 @clusterfack Can this be closed? Bartenders now have access to black food coloring which makes it possible to hide contents. Not quite the same exactly, though.

**Comment by Killette2** [comment]
This shouldn't be closed. You can examine para pens to see how much chloral is in them for example to make it obvious that it's a para pen

Black food coloring does not fix the grand problem, it only fixes the bartenders problem.

**Comment by Kurfursten** [comment]
The traitor item paralysis pen cannot be examined to see chemicals.

You CAN examine a sleepy pen to see its chloral, but it's not from the traitor uplink.

**Comment by Cisrox** [comment]
This isn't even fixed.

**Comment by Intigracy** [comment]
That's a mixture of chemicals.

There's too many different chemicals in the glass, you cannot tell them apart.

You can't quite make out its content!

The mixture of chemicals is about half full, or about half empty!

**Comment by Killette2** [comment]
I also like how anyone but the bartender can tell EXACTLY what booze is in a glass. I think if there's a minute amount of chemicals in a glass it shouldn't be examinable and still show the base drink. Hell the contents of glasses shouldn't be examinable at all.

**Comment by Iamgoofball** [comment]
This is a piss easy fix

**Comment by Killette2** [comment]
Also about the black food coloring, it's suspicious as fuck if it mask all chemicals instead of just the major one. For example if I have a drink of 29 beer 1 unstable mutagen, I'd want it to say 30 beer because what the fuck does my patron know if I sneak 1 unit of mutagen in a glass where it isn't even 4% of the glass's content. Otherwise if black food coloring mask everything, people wouldn't be as inclined to drink mystery drink.
