### ISSUE TITLE
When changing an area's name, lightswitch and firealarm names don't update

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#2914]
how to reproduce
1. get station's blueprints
2. rename any area to anything else
3. the APC and air alarms will get renamed, lightswitches and fire alarms won't

**Comment by clusterfack** [comment]
The blueprints need to be most robust in general

Here's a list of things they dont do
-Change names of associated machinery like the above
-Dont rename vents
-Dont assign vents to the new room when making a new room using them
-More things
