### ISSUE TITLE
Packed Station Auxillary Docking Disks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29151]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
27f31effa34fc0b94d5fba7c736f76b4512ccb6c

# Description
Aux docking disks printed at either the on-station or direlict autolathes on Packed Station do not actually provide any docking ports, leaving you trapped wherever you send your custom shuttle.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Closed in #31418 and improperly referenced @Kurfursten
