### ISSUE TITLE
Placing a burger onto a plate creates extra food

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29163]
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
8f90bcd2fac11108937a18a24826b7c2f06e752f

# Description
The big burgers made from buns and ingredients create imaginary food with 3 nutriment seemingly infinitely when combined with an empty plate.
# Steps to Reproduce
Take an egg, use a flour sack on it to make a bun, microwave the bun to cook it.
Take a piece of meat from the meat fridge, grill it, and put it in the bun to create a grilled meat burger.
Take a plate, and use the burger on it, it will not combine to create a grilled meat burger on a plate, but will instead create a " on a plate" and leave the grilled meat burger intact.
# What you Expected
The burger should be able to be combined with a plate to create a burger on a plate.
# What Actually Happened
The big burger does not properly fit on the plate and instead creates 3 nutriment on a plate and a fully intact burger.

**Comment by DeityLink** [comment]
now that's a runtime if I've ever seen one

**Comment by DeityLink** [comment]
Also I'm deeply grateful to see some descriptive Steps to Reproduce. Wish everyone did that.
