### ISSUE TITLE
Pouring Sports Drink on a ready to harvest plant removes it's harvestability until it's metabolized.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29162]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
3cdeb006dcce12b926134a66a5e1239609fdd413

# Description
what it says
# Steps to Reproduce
Plant something
Wait until it's harvestable
Pour sports drink
Realize you lost the harvest.
# What you Expected
being able to harvest sports drink'd plants
# What Actually Happened
lost me harvest.

**Comment by west3436** [comment]
this is game-breaking
sports drink have electrolytes, which plants crave

**Comment by Kurfursten** [comment]
You got tricked
This is a feature, it doesn't stop plants from being harvested, it stops any lights from appearing on the tray. Brawndo makes all the warning lights go away, because it has what plants crave.
