### ISSUE TITLE
Lack of atmo in LFB maint

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29195]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
82f46c4c0321c619a252be04ca06a1c3ba191462

# Description
Some of the little rooms in LFB maint (including the external airlock areas) have no atmophere at roundstart for some reason.

**Comment by nervere** [comment]
No longer an issue.
