### ISSUE TITLE
APC connected to nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29196]
(WEB REPORT BY: redstein REMOTE: 206.221.180.138:7777)
# Revision
82f46c4c0321c619a252be04ca06a1c3ba191462

# Description
The APC in the maintenance tunnel in front of arrivals isn't connected to anything

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
Thanks for specifying the map

**Comment by djkramer123** [comment]
![84832cd0164c16640f17fb05699fa1c2](https://user-images.githubusercontent.com/51164713/114258593-9726a080-9995-11eb-917e-3966ef732eb9.png)
lowfat bagel it seems
