### ISSUE TITLE
Siege cannons cannot shoot pies.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29207]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
82f46c4c0321c619a252be04ca06a1c3ba191462

# Description
This is shameful, I don't know why this doesn't work but banana crfeam pies cannot be put into siege cannons
# Steps to Reproduce
try to put a banana cream pie into a cannon
# What you Expected
to fire pies in a piratey fashion
# What Actually Happened
the pie isn't even recognized as an entity by the cannon

**Comment by GreatBigFailure** [comment]
Oh I know what's going on, easy fix. I owe you an apology, pie man.

**Comment by GreatBigFailure** [comment]
There, fixed

**Comment by robintime** [comment]
nice
#29204

**Comment by robintime** [comment]
WAIT IT HAS TO GET MERGED

**Comment by Eneocho** [comment]
A little trigger happy, ain't you.
