### ISSUE TITLE
[Feature Request] Make emag uses work like EMP flashlights

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#29211]
[featurerequest][controversial]
EMP flashlights give you 4 uses then can't be used again for another 30 seconds until it recharges, for reference.

**Comment by boy2mantwicethefam** [comment]
That was actually how it worked before some unintended change from aeons ago gave it infinite immediate uses, but everyone is used to the emag having infinite uses by now

**Comment by ghost** [comment]
> That was actually how it worked before some unintended change from aeons ago gave it infinite immediate uses, but everyone is used to the emag having infinite uses by now

Except the main difference here is that after 30 seconds, the uses all come back

**Comment by Exxion** [comment]
It wasn't an unintended change that made it infinite. It's a config option.
The other options in the code are:
* Limited uses
* Limited uses that regenerate over time

**Comment by ghost** [comment]
> It wasn't an unintended change that made it infinite. It's a config option.
> The other options in the code are:
> 
> * Limited uses
> * Limited uses that regenerate over time

Yeah no. 2 is what I had in mind, I vaguely remember there being a config option to set it but not that third one
