### ISSUE TITLE
Voting panel has 2 cancel vote buttons.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29227]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
bdd6cbeb74d7e75cd83187181bf81ab38a6a0cca

# Description
What it says. One above the voting options, one at the bottom between parenthesis.
# Steps to Reproduce
vote.
# What you Expected
1 button
# What Actually Happened
2 buttons.

**Comment by Kurfursten** [comment]
@ShiftyRail

**Comment by Eneocho** [comment]
Also, if you select the credits text and drag up or down, you can move the credit music buttons.

**Comment by robintime** [comment]
> Also, if you select the credits text and drag up or down, you can move the credit music buttons.

already working on a fix for this, the buttons use internet explorer media player functionalities and im swapping it over to pure jscript because i realized it looks janky on larger screens x_x

**Comment by Kurfursten** [comment]
This seems like a weird place to report/discuss that
