### ISSUE TITLE
[Box outpost] Two all-in one grinders on the same spot

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#29221]
#### Description of issue

See image

![image](https://user-images.githubusercontent.com/31417754/114471705-5925b880-9bf1-11eb-944c-c50ae7f56142.png)

**Comment by Eneocho** [comment]
Very Hihg Speed Grinding

**Comment by help-maint** [comment]
One for each hand

**Comment by kernikov** [comment]
@DeityLink No longer an issue since Box Sci Outpost was remapped.

**Comment by DeityLink** [comment]
Duplicate of #29472

**Comment by DeityLink** [comment]
Fixed by #29911
