### ISSUE TITLE
If you monkey an Umbra then humanize it again, they become a normal human with no powers and no eye difference.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29243]
What it says on the tin.

Become Umbra.
Inject with monkeyfier gene syringe.
Inject with humanifier gene syringe.
Lose all your cool features.

**Comment by DeityLink** [comment]
what's a grue anyway
![image](https://user-images.githubusercontent.com/7573912/129200766-f260372b-d08b-41d7-99e7-59a013d2383a.png)

**Comment by Eneocho** [comment]
Goddamnit, frenchman, you made me chuckle.

**Comment by Eneocho** [comment]
Closing it since I can't spawn any umbras in-testing and it seems Umbras have been removed from the game in #32814, part of their code reused for vampire trueform, though the issue probably can still happen with the inherited vampire stuff
