### ISSUE TITLE
Price Tagger useless

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29240]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
be6caf13f6ed3c453f705fbe3a658d6fe67962fd

# Description
See title
Tagging an item with a price and then inserting it into an empty refresh pack to charge a customvend does not have the price set in the vend
# Steps to Reproduce
Price tag item
Insert into vending recharge
Recharge custom vend(this one already had items inside)
Tagged item has no set price until you manually do it
# What you Expected
Item to be priced upon charging vend so I don't have to fiddle with unlocking and setting price manually
# What Actually Happened
Priceless item

**Comment by Eneocho** [comment]
People actually use the price taggers?

**Comment by toomykins** [comment]
theyre not for the vends
price taggers existed before the vends could be manually filled
the pricetaggers are for the cash registers that nobody uses afaik

**Comment by Zth--** [comment]
No, he's right. When I made the custom vendors I had this idea of using price taggers to set the price before insertion.
Also I wanted to add a small price tag overlay on the item you tag.

I guess I forgot about it.
