### ISSUE TITLE
AME does not charge its own APC

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29252]
(WEB REPORT BY: slightlyfloating REMOTE: 206.221.180.138:7777)
# Revision
be6caf13f6ed3c453f705fbe3a658d6fe67962fd

# Description
The AME does not charge its own APC.
# Steps to Reproduce
Set up the AME in the AME room. Observe as the APC turns red... somehow? Despite a massive antimatter engine powering it?
# What you Expected
For the APC to be charging.
# What Actually Happened
The APC aint charged and drains power. This causes the AME to shut off. Makes AME not a viable engine. Is this an intended feature?

**Comment by help-maint** [comment]
SMES input too high bro

**Comment by Dacendeth** [comment]
Yeah this is just someone improperly changing the settings on the SMES,
