### ISSUE TITLE
[Meta] Windows

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#2927]
The windows on Metaclub are really strange and slightly buggy.

They are apparently layered in such a way that the full tile windows on top of the one way windows cannot be interacted with. And also the full windows do not smooth together with one another.

I think they might just need to be ripped out and readded manually.

**Comment by Probe1** [comment]
That could explain this issue with biomass on metaclub https://github.com/d3athrow/vgstation13/issues/2598

**Comment by IratePirate** [comment]
Yeah I see the problem. I think in the map porting reinforced windows got placed in a layer below all the other reinforced window panes. Gonna fix now. Thanks for the heads up.
