### ISSUE TITLE
[Feature Request] Magic is stored in the ass

### ISSUE THREAD

**Issue by TurboGay** [d3athrow/vgstation13#29280]
#### Request
Fairly self explanatory, a request for magic to be stored in the ass so that you can disarm a wizard by removing their ass, thus being able to pacify wizards through other means than muzzling, implants, et al. I think anything that prevents straight round removal is a healthy thing for the game, especially for a mode like wizard.

Optionally, if you could receive a random spell they had upon wearing said magic ass on your head, with the ass being a condition for casting said spell, I think it'd be an interesting thing to add. Could also go the angle of magical ass burgers granting you the spell as well.

<featurerequest>

**Comment by ghost** [comment]
>use cloak
>sneak up on wizard during civil war
>ARSE NATH
>disarm them for good

i dunno

**Comment by Eneocho** [comment]
On the topic of magic and kitchen magic, I find it extremely shit that magica deluxe gives you the wiz robes and "spells" but no charge for said "spells", meaning you just have a pointless spellbox that just clutters the UI.

**Comment by Dacendeth** [comment]
> 
> 
> > use cloak
> > sneak up on wizard during civil war
> > ARSE NATH
> > disarm them for good
> 
> i dunno

How's that any worse than sneak up the wizard, turn him to stone, bash to death with toolbox?

**Comment by yclatious** [comment]
A new realm of powergaming, and a new age for /vg/.

Magical ass eating. Fucking 10/10, get this man a fucking medal and a glass of champagne, this is the feature request of the year.

**Comment by TGFH** [comment]
Make it happen, coders.

**Comment by Exxion** [comment]
XD so random

**Comment by TurboGay** [comment]
> 
> 
> XD so random

As opposed to magic being stored in the torso/head? Do you understand how dumb you sound right now? This would not only add a justification to not permanently round remove wizards but also give purpose to ass surgery beyond jokes, how is it random in the slightest?

**Comment by Kromkar** [comment]
> > XD so random
> 
> As opposed to magic being stored in the torso/head? Do you understand how dumb you sound right now? This would not only add a justification to not permanently round remove wizards but also give purpose to ass surgery beyond jokes, how is it random in the slightest?

They are antagonists, they exist to kill and be killed. Go to Bay

**Comment by Eneocho** [comment]
I for one am all for magical assburgers giving you magical powers.
