### ISSUE TITLE
Changeling oddness

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#2928]
Apparently Changeling wigs out on occasion
In one round I had the following happen to me

Changeling stings (Para and silence were what I used) will occasionally not work for players. After it failed once I tried again and nothing happened. Awkward moment there.
Notes: Aurtherdentist said he had heard it happen before. I had to revert to para pens to get kills.

After Transforming, gained a defect. May be due to how genetics handles things.
Notes: I had a conversation with them, Ate them, then gained the mute defect. Suggesting it was not from the person in question.

Changeling powers persist in mommi
Note: If only they worked that round

**Comment by Probe1** [comment]
You're sure you weren't trying to sting another changeling?

**Comment by ComicIronic** [comment]
With the stings, did you have the range upgrade?
It could be an issue with A*.

**Comment by CptWad** [comment]
Nah I wasn't stinging another ling. He would have responded to my :g because I was offering free bodies. I was a lone traitorling.

No range upgrade. I was right next to the dude and hit silence then para. He did not drop so I thought "Oh so he is just stunned or some shit?" Dragged him and he moved away. Somehow he did not catch the hint and I tried again and failed. Had to run like a madman and switch to para pens. Would there be some update to HoS jackets? He was unrobust but if the jacket can deflect stings then I would understand.

**Comment by Unfit** [comment]
I have had some problems with stinging people as well
Once I bought and activated the range upgrade everything became fine though

**Comment by d3athrow** [comment]
It is an issue with A* like comic said, it breaks for no apparent reason sometimes resulting in bots not moving and ling stings not working. I'd rather use adjacent for ling stings but fucking ranged stings make that not feasible.

**Comment by CptWad** [comment]
If I recall @d3athrow merged something fixing ling stings and just never touched this issue. Closing now.
