### ISSUE TITLE
ATTENTION NEW COMMAND REPORT CREATE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29295]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
c09f024220fbbae674bc294ce151774764a9ca34

# Description
When it's blob, the defcon levels go back and forth repeatedly, spamming everyone with tons of announcements.
# Steps to Reproduce
Have a blob conglom
???
ATTENTION NEW COMMAND REPORT CREATED
# What you Expected
One defcon announcement.
# What Actually Happened
ATTENTION NEW COMMAND REPORT CREATED

This was a request by PrimeD.

thanks -dilt

**Comment by Blithering** [comment]
Seems DEFCON should be a one time trigger, rather than constant seesawing across the threshold.

**Comment by jwhitak** [comment]
Related to https://github.com/vgstation-coders/vgstation13/pull/29176

**Comment by DeityLink** [comment]
The easy fix would be to have so margin between the requirement for defcon to go up or down so spawning/destroying a single blob tile doesn't cause non-stop reports.

**Comment by DeityLink** [comment]
example:
* if more than 15% of blob spread, defcon goes up to 3
* if less than 14% of blob spread, defcon goes down to 4

**Comment by Eneocho** [comment]
I could swear this was fixed. @nervere @Exxion

**Comment by nervere** [comment]
@Eneocho is correct, this is no longer an issue.
