### ISSUE TITLE
Request for Metaclub to get Medbay EVA

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29300]
(WEB REPORT BY: poxie2815 REMOTE: 206.221.180.138:7777)
# Revision
55123de2be824e14a48f3bde6183af8e0f760442

# Description
There is no Medbay EVA on Metaclub, only the paramed gear are the hardsuits available to doctors.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by CptWad** [comment]
@Kurfursten close pls
