### ISSUE TITLE
Voting for blank

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#29305]
If you hit Cancel Vote before actually voting it causes a blank vote thing to appear, which you can then vote on.

**Comment by Eneocho** [comment]
What happens if the mayority vote for the blank option though. Does the serb crash upon reset? Same map again?

**Comment by Dacendeth** [comment]
same map i was told.

**Comment by Blithering** [comment]
Blank winning should force dorf round.
