### ISSUE TITLE
[Feature Request] Borg Ban refactors

### ISSUE THREAD

**Issue by drawsstuff** [d3athrow/vgstation13#29314]
Borg banning currently is a bit of a mess. If you were to take a cyborg ban, it would also ban you from mommi, mmi, ai, positronic brains, ect. This is a bit of a problem because while some players enjoy playing mommi or ai for instance, it leads to the "ghost before autoborged" phenomenon that seems to plague most malf rounds. On top of that, things such as mmis have a use in surgery, where dead brains can be put into mmis to "Revive" them for re-implantation. 

This issue ties in to a feature request I have made in the past, which can be seen here: #28532

**Comment by jknpj** [comment]
If you're unable to follow your laws as cyborg, i don't think you're capable of following them as mommi/AI.

**Comment by toomykins** [comment]
All silicon laws work the same, if you don't understand how it works for one, it shouldn't be expected you understand the rest. The only exception to this should obviously be the PAI, which is sadly automatically included.

>  dead brains can be put into mmis to "Revive" them for re-implantation.

this is just a bug, and should've been reported separately.

**Comment by drawsstuff** [comment]
> If you're unable to follow your laws as cyborg, I don't think you're capable of following them as Mommi/AI.

I am able to follow my laws as a Cyborg, AI, Mommi, ect. Cyborg roles in particular cause me a large amount of undue stress because of extremely negative experiences I have had with them. 

Lets say for our hypothetical there is a human in a room with a breach. He has no magboots, and no crowbar, and the room is being sealed off with a firelock. The human is clearly dying. I must now act on law 1. This is an issue, however, because both of my possible actions would lead to me breaking my laws. I could open the door to free him and take him to medbay, but in doing so I would harm him because ZAS would slam him against the wall. I could also do nothing and not harm him through ZAS, but then I am harming him through inaction. 

As a Mommi, I could simply *ping and run past him, ignoring the issue entirely, and as an AI, I could completely ignore him because funny that, Malfunctioning AI doesnt require you to have AI turned on at all, and that's the only situation in which I roll it. As for MMIs, there are rounds where I've gotten my ass handed to me by security or so on and they decide it's more fun to keep the talking vampire head around instead of being done with it it, something I'd rather not deprive myself of. 

I've had nothing but bad experiences as a borg, even traitor borgs, and I feel like all of my actions end up leaving me at the mercy of an admin. It's mostly undue paranoia, not the fact that I'm incapable of playing the role. Still, a refactor of this banning system would be nice to have, there are plenty of people who enjoy certain silicon roles but ghost if they so much as suspect they're going to be borged to avoid the issue entirely.

**Comment by jknpj** [comment]
> as an AI, I could completely ignore him

point proven

**Comment by drawsstuff** [comment]
> > as an AI, I could completely ignore him
> 
> point proven

It's like you can't read, here, let me highlight it for you.





> as an AI, I could completely ignore him because funny that, Malfunctioning AI doesnt require you to have AI turned on at all, and that's the only situation in which I roll it.

**Comment by Kammerjunk** [comment]
wait, what?
![image](https://user-images.githubusercontent.com/5942183/115731688-9f181480-a387-11eb-890e-67894fca219b.png)
(from the jobban panel)

**Comment by Kammerjunk** [comment]
and it looks from https://github.com/vgstation-coders/vgstation13/blob/ab73db104137216e99d51bc9e5398ed7957c5f33/code/game/objects/items/robot/robot_parts.dm like it _does_ check for "Cyborg" jobban

**Comment by drawsstuff** [comment]
> wait, what?
> ![image](https://user-images.githubusercontent.com/5942183/115731688-9f181480-a387-11eb-890e-67894fca219b.png)
> (from the jobban panel)

I'm positive that cyborg bans ban you from MOMMI, MMI PAI, AI, ect. Please correct me if I'm wrong, it's the only reason I've yet to ask for one.

**Comment by Kammerjunk** [comment]
hopefully shouldn't:
https://github.com/vgstation-coders/vgstation13/blob/1ce25ff1b797f3a22ed9af5a5628ca61270dc4cf/code/game/machinery/computer/ai_core.dm#L111

**Comment by drawsstuff** [comment]
> hopefully shouldn't:
> https://github.com/vgstation-coders/vgstation13/blob/1ce25ff1b797f3a22ed9af5a5628ca61270dc4cf/code/game/machinery/computer/ai_core.dm#L111

Positive it does, please test it ingame.

**Comment by Blithering** [comment]
If you're a medical or engineering borg inflatables can save the guy in your example scenario. If you don't have the tools yourself it's best to call someone who does, since that satisfies taking action to prevent both instances of harm.

**Comment by drawsstuff** [comment]
> If you're a medical or engineering borg inflatables can save the guy in your example scenario. If you don't have the tools yourself it's best to call someone who does, since that satisfies taking action to prevent both instances of harm.

It doesnt matter if you have inflatables, opening the firelock harms the human, and no amount of healing after can fix the fact you broke your laws. But this isnt an issue for discussing asimov-isms.

**Comment by drawsstuff** [comment]
Going to be closing this for now until I run into bugs. I'll have a borg ban applied to my ckey and I'll re-open this issue when something breaks (inevitably).

**Comment by toomykins** [comment]
Seeing as cyborg used to be a punishment role and since the powers of AI are rather rewarding, I don't think you should be able to be one without the other. It just makes sense.

**Comment by drawsstuff** [comment]
> Seeing as cyborg used to be a punishment role and since the powers of AI are rather rewarding, I don't think you should be able to be one without the other. It just makes sense.

Used to does not mean is currently. Get with the times old man.

**Comment by Kammerjunk** [comment]
>used to be a punishment role

**Comment by Blithering** [comment]
>It doesnt matter if you have inflatables

Pretty much unrelated to the issue at this point but inflatables are REALLY handy for avoiding all firelock ZAS harm once you got the hang of using them.
