### ISSUE TITLE
MoMMi mat synth stacks bugs

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#2931]
1) The materials aren't called by their name when added, they're called by their path like:
/obj/item/stack/sheet/glass/glass
/obj/item/stack/sheet/metal
/obj/item/stack/sheet/glass/plasmarglass

2) Not all the materials show up on the status report:
Rplasmaglass and metal seem to be missing, didn't check other mats

3) Wonkiness with the produced metal stack:
-If you happen to finish a stack (tested with autolathe/protolathe), the metal icon doesn't go away
-You can't click and equip this icon/metal, even if you add more sheets with the matsynth
-This forces the mommi to actually overflow metal to get to use it, since its internal metal storage is borked for the remainder of the round.

may be related to #1578

**Comment by PJB3005** [comment]
I THINK you can get to the "glitched" metal stacks by using the text based inventory (panel button at the bottom right of the UI)

**Comment by clusterfack** [comment]
I believe this is technically a few bugs combined that all play around the way stacks work:

1. If you try to place all your metal in a machine and FAIL, your entire stack drops however it is still assigned to you as a module.
2. If you use all your stack it calls unequip and sets the location to null, however the unequip sets it back into your inventory instead, leaving a stack of size 0
