### ISSUE TITLE
Getting eaten by a gourmonger sends your head to nullspace when on a mulebot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29310]
(WEB REPORT BY: jameswbigmac REMOTE: 206.221.180.138:7777)
# Revision
21053fd45d3a3518cd5d2c4f12a8d7fa90f0dbd3

# Description
If you're eaten by a gourmonger while on a mulebot your head goes to the shadow realm
# Steps to Reproduce
Get on a mulebot
let a gourmonger have a few nibbles
head is nowhere to be found
# What you Expected
My head to still be there
# What Actually Happened
My head was gone

**Comment by robintime** [comment]
dilt's is better im sorry i have to do this to you ...

**Comment by DeityLink** [comment]
Duplicate of #29311
