### ISSUE TITLE
Low fat bagel has no virology GNA disks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29337]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
6ede77f981ad1a87e52aed0db8b4a0691448a03b

# Description
None in virology
# Steps to Reproduce
Look in virology for them
# What you Expected
Virology data disks
# What Actually Happened
None

**Comment by ghost** [comment]
nevermind these come out of symptom extractors, im dumb
