### ISSUE TITLE
Magic Missile + Staff of Animation can cause permastunlock on borg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29338]
(WEB REPORT BY: demagoguedimension REMOTE: 206.221.180.138:7777)
# Revision
6ede77f981ad1a87e52aed0db8b4a0691448a03b

# Description
See title. Wizard spells can be used to keep a borg from functioning ever again, stuck as an animated object.

# Steps to Reproduce
Have wizard stun borg using magic missile, have wizard then cast animate object on borg

# What you Expected
Animate object eventually wearing off

# What Actually Happened
Animate object causing permanence in status unless attacked enough to get out of that state. Cyborg may then be permanently stuck still unless moved around by an entity (this part needs to be tested).

**Comment by Dacendeth** [comment]
Feature

**Comment by Exxion** [comment]
I can't see any way in the code that Staff of Animation could possibly affect borgs. Do you mean Flesh to Stone instead of Magic Missile? Also, did you wait the two full minutes for the spell to wear off?

**Comment by Exxion** [comment]
Yeah, Magic Missile does not let you animate a borg. Only Flesh to Stone does that. Both of these spells wear off, but it takes quite a long time. The inability to move after no longer being animated is because you were still a statue. The only thing that *might* be a bug here is that borgs are affected by Flesh to Stone.

**Comment by Eneocho** [comment]
> 
> 
> The only thing that _might_ be a bug here is that borgs are affected by Flesh to Stone.

Just handwave it as the spell affecting the MMI'd brain.
