### ISSUE TITLE
Plasma bellows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29346]
(WEB REPORT BY: turingwept REMOTE: 206.221.180.138:7777)
# Revision
52376bfeb1177f3fe5ec325e396a0482556f13d5

# Description
#124907
Requested:
Cold Plasma Canister, amount: 1
Filled with over 1000 kPa of plasma bellow 2K.

Below: at a lower level or layer than.

bellow: to Emit a deep loud roar, typically in pain or anger.

**Comment by Eneocho** [comment]
A whole new meaning to the phrase roaring fire.

**Comment by SGuivenne** [comment]
note this was a cargo request from nanotrasen
