### ISSUE TITLE
Feature Request: Malf "Boxing" Equivalent 

### ISSUE THREAD

**Issue by SGuivenne** [d3athrow/vgstation13#29344]
#### Description of issue

With malf as is, there is an alarming habit of people "ghosting" before being autoborged, or otherwise quitting the game.  Similarly is if people are jobbanned from AI.  A solution here should be either some form of a boxing benefit, which either reduces the malf timer, gives the AI more points to do things, or alternatively gives a borg a respawn opportunity to make up for the otherwise waste of the risk and effort of autoborging someone instead of killing them.   

Boxing for cultists has already been incredibly useful for allowing people to "opt out" of cult instead of finding new shitty workarounds or elaborate ways to kill themselves or otherwise get jobbanned from cultist.

**Comment by help-maint** [comment]
Are we then gonna have to code boxing for vamp thralls, boxing for greytide implants, boxing for summon guns, boxing for having an antag put a bomb vest on your chest...

At what point do we admit this is an administration issue and not a code one

**Comment by BomberBro** [comment]
as far as I know this isn't a widespread issue, however I think it's dumb how badly antagbans fuck over certain antags like revs or malf since as soon as you call out the burger the entire crew gets up in arms.

**Comment by gurfan** [comment]
serverban people who do this

**Comment by SGuivenne** [comment]
Closing this because they are now serverbanning people who do this.
