### ISSUE TITLE
Map editor - Space heaters and air conditioners sprites have vanished

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#2935]
![issue](https://cloud.githubusercontent.com/assets/6830971/6134827/d48b6d76-b15b-11e4-8647-64437cf558a5.png)

Just a little irritation.

**Comment by PJB3005** [comment]
Wasn't even a BYOND issue

**Comment by PJB3005** [comment]
Oi, reopen this, it's happening again due to 07368b3c642711d5624ff6287b0056d691449b1a
