### ISSUE TITLE
Grayys have the same blood color as Humans

### ISSUE THREAD

**Issue by Optimism333** [d3athrow/vgstation13#29376]
# **Description of issue**
Despite their notable difference in reactivity to dihydrogen monoxide and overall difference in physical appearance, Grayys have an identical blood color to Humans.

# **Steps to reproduce**
1. Be Grayy
2. Bleed blood
3. Be somewhat sad that you're the only ayy without a unique fluff blood color

# **What was expected**
To have sulphuric acid orange blood, or maybe alien green (the other kind of alien) 

# **What actually happened**
Bled perfectly ordinary Human blood.

**Comment by GreatBigFailure** [comment]
I mean they breath O2 while Vox don't. Insects also have a weird water balloon circulatory system. So that accounts for the colours. Really the issue here is that iron still recovers blood for those two, I doubt they have the same deal with heme we do.

**Comment by Optimism333** [comment]
> I mean they breath O2 while Vox don't. Insects also have a weird water balloon circulatory system. So that accounts for the colours. Really the issue here is that iron still recovers blood for those two, I doubt they have the same deal with heme we do.

I do get what you're saying, but I simply think that a unique blood color would be a nice detail for Grayys to have. It would further differentiate them from a baseline Human, and every other ayy already has one. Having the same blood color as a species that has acid blood like aliens (at least in media), or a more orange color (since sulphuric acid is orange in-game) would be pretty neat.

**Comment by Optimism333** [comment]
With the passing of #31162, this issue is resolved.
