### ISSUE TITLE
remember the empty weldertank pr? it doesnt work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29384]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
4c09a724bde4dbd895b9468a1c8aa18c4f65c984

# Description
empty weldertanks are supposed to not explode
# Steps to Reproduce
empty tank and do the funny
# What you Expected
no explosion or just the tank poofs
# What Actually Happened
banned

**Comment by robintime** [comment]
@apogee-dev

**Comment by Kurfursten** [comment]
it wasn't merged

**Comment by robintime** [comment]
WAIT IT WASNT MERGED?
