### ISSUE TITLE
People Stand In Front Of Newly Built Couches

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29386]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
4c09a724bde4dbd895b9468a1c8aa18c4f65c984

# Description
If you build a piece of a couch, the the player sprite appears in front of the couch. The moment you sit down on the couch, it acts as intended and people pass behind it. It remains fixed even after you get up. Very curious.
# Steps to Reproduce
built a couch part
watch as your (plane/layer?) is over the couch
sit on the couch
the couch is now proper

# What you Expected
build a couch and it works right away
# What Actually Happened
build a couch and you have to sit in every individual piece so it works right

**Comment by Dacendeth** [comment]
not just couches, chairs too, only happens for couches built facing north i think, though i guess it mostly matters for ones facing north.
