### ISSUE TITLE
Hardsuits don't block a plasmen's self ignition despite being space suits that block atmos.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29382]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
4c09a724bde4dbd895b9468a1c8aa18c4f65c984

# Description
Title
# Steps to Reproduce
Be plasmeme
get a hardsuit
doesn't work
# What you Expected
not being on fire
# What Actually Happened
i am the god of hellfire

**Comment by jknpj** [comment]
Works like that by design.

**Comment by Eneocho** [comment]
> 
> 
> Works like that by design.

Well then it's poor design.
