### ISSUE TITLE
Juggernauts reflect lasers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29400]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
4c09a724bde4dbd895b9468a1c8aa18c4f65c984

# Description
Juggernauts reflect lasers
# Steps to Reproduce
Shoot juggernaut
# What you Expected
It dies
# What Actually Happened
Juggernauts are walking alabatives except better because they also negate most damage from things weaker than lasers what in the actual fuck

**Comment by BomberBro** [comment]
this is a feature of c*lt

**Comment by Allspice** [comment]
>they also negate most damage from things weaker than lasers what in the actual fuck

I'm pretty sure you've misunderstanding something.

**Comment by Eneocho** [comment]
thanks de*ty very cool

**Comment by gurfan** [comment]
feature

**Comment by TGFH** [comment]
Yes, they have built in ablative armor.

Yes, it's gay.

**Comment by Blithering** [comment]
How are juggernauts even a thing, just walk away bro. Close a firelock and laugh at it.

**Comment by DeityLink** [comment]
Will you push the button anon?

[ ] <<

Juggernauts lose their low damage shield (which includes their chance to reflect lasers)

BUT

They now move at "human in rigsuit" speed



> 
> 
> > they also negate most damage from things weaker than lasers what in the actual fuck
> 
> I'm pretty sure you've misunderstanding something.
> 
> edit: guess that could be referring to the recent change that expanded jugger 10-or-less damage resistance to ranged weapons as well, whoops.

what ranged weapons are there that deal less than 10 damage though?
