### ISSUE TITLE
[Metaclub] Add additional IVs

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2940]
Add 2-3 more IVs to storage.  Metaclub Medbay It only has the one near surgery and that's a bit unreasonable to ask medbay to go get metal to make basic supplies.  3-4 covers almost all regular possibilities and more can be made if needed.  

![image](https://cloud.githubusercontent.com/assets/8550416/6141335/f6aaa4f6-b171-11e4-8395-6c210169ba17.png)

Unrelated but I'd remove the advanced trauma/burn kits.  We have to annoy RnD for something!

Also unrelated but I'd remove a few of the O- bloodbags.  Seems a bit too generous to have that many.  I'd replace them with empty blood bags.

@IratePirate

**Comment by clusterfack** [comment]
Also I got an ahelp from a Bartender who said he lacked a shaker on the Meta map. Can you check that out as well?

**Comment by Probe1** [comment]
I'm fairly sure that is not accurate, I've stolen his shaker as chef quite a few times.

**Comment by Probe1** [comment]
Also while we're talking about the bar, please move the salt and pepper shakers to the back table instead of the counter.  Miscreants love to throw away pepper because there's no fackin way to replace it for some awful reason.  

![image](https://cloud.githubusercontent.com/assets/8550416/6142694/1fd59d60-b189-11e4-9d9f-1afedaf214e3.png)

**Comment by 9600bauds** [comment]
Another thing about the kitchen. You can't access the Sparts locker without breaking something, both the meat rack and the mailing system window block your way.
