### ISSUE TITLE
Buddycuff Spaghetti

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29416]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
8c17d6fb75a2c898db4ca9e9b6339ba42bdd0380

# Description
Buddycuffing with spaghetti is impossible. A horrible oversight
# Steps to Reproduce
Try to buddycuff with spaghetti
Nothing
# What you Expected
A romantic noodle restraining experience for two
# What Actually Happened
Nothing. A spaghetti restraint for only one

**Comment by ShiftyRail** [comment]
Buddycuffing is supposed to with handcuffs only in order to make it less available.

**Comment by GreatBigFailure** [comment]
My lady and the tramp gimmick, RUINED

**Comment by PavelCIA** [comment]
its not like more than three people know how to buddycuff anyway

**Comment by DeityLink** [comment]
I have ptsd of making on-mob sprites for all cuffs, buddycuffs use separate sprites so if we want them for all cuff types it's gonna be another long haul. Not to mention the point made by shifty, so I say it's better to keep it this way.
