### ISSUE TITLE
Advanced reagent scanner breaks when subject has blood in its reagents

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#29424]
`Runtime in scanners.dm,543: Undefined operation: /list (/list) * 2`

Happens because blood's data is a list:

https://github.com/vgstation-coders/vgstation13/blob/a2e588fe9788a7eda108c9b4f84415b123aaca64/code/game/objects/items/devices/scanners.dm#L543

**Comment by ghost** [comment]
I caught every single other one and missed this, will fix it

**Comment by help-maint** [comment]
Why don't you just check if data is a list instead of hardcoding out the subtypes that break

Why don't you use the tick variable and just replace "data" for "tick" in the few reagents that are still using the old system
