### ISSUE TITLE
Hippie's Delight screenshake

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#2943]
The screenshake you get from drinking Hippie's Delight is nowhere near as bad as it used to be. Before your screen would be all over the place which should be the intended effect, now all that happens is a tiny little bit of shaking that you get from drinking alcohol normally.

**Comment by clusterfack** [comment]
Yeah the shake is negligible

**Comment by Cisrox** [comment]
Closeable.

**Comment by PJB3005** [comment]
Again, somebody else say if this should be closed.

**Comment by gbasood** [comment]
No one in the server seems to care, so
