### ISSUE TITLE
"Bluespace connection lost" announcement is spoken twice

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#29445]
I think the sound file itself contains the same audio twice.
@N3X15

**Comment by Blithering** [comment]
Additionally the text still says "is be" as it did before the fix to the spoken version.

**Comment by N3X15** [comment]
Regenerating all sounds now to see if it fixes it.

**Comment by N3X15** [comment]
![image](https://user-images.githubusercontent.com/110073/118053764-f2073b00-b339-11eb-8da7-4c9087ab192c.png)
