### ISSUE TITLE
Zombies can bite while dead

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29441]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
143feabcfeab85537e191904009ef93450fef31e

# Description
they can bite while dead on the ground wtf

**Comment by Theophrastus1** [comment]
so can rattlesnakes bro be careful

**Comment by DeityLink** [comment]
Fixed by #29542
