### ISSUE TITLE
I want to get off Space Pod's wild ride.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#2945]
Upon entering a Space Pod, both through click+dragging yourself onto it and by rightclicking and selecting Enter Pod, you will not be able to leave. Both rightclicking the pod and the Object menu only give you the option to Enter Pod again, which gives you the error "The space pod is already occupied!".
The option to eject does not become available.

**Comment by Exxion** [comment]
If I remember correctly, you have to exit through a verb in the Object tab. It's not exactly broken, just fucking stupid. I know because I got stuck in one for several minutes before figuring that out, as well.

**Comment by 9600bauds** [comment]
Funny story actually, after finding my way back to the station in a space pod I had to send an ahelp to be ejected from the pod. This made it so that I couldn't get back in, as it said it was already occupied, but I didn't care because I wasn't going to keep using it.
I said through the radio I had a pod and was showing it to someone when a scientist ran out the airlock straight to the side of the pod, trying to board it, only to fail and continue to be sent straight into deep space after they slipped.
They were never seen again.

**Comment by 9600bauds** [comment]
Upon closer inspection, I missed the fact that a new tab called "Spacepod" opens when you get aboard.
![ss 2015-02-22 at 03 47 44](https://cloud.githubusercontent.com/assets/6526157/6319831/396af692-baaa-11e4-8728-8997a2ad2573.png)
I'm still leaving this issue open since it's not at all intuitive and could use a little improvement. Perhaps the rightclick verb and the on-click action could be replaced with "Enter/Exit Spacepod".
Same deal happens with mechs.

**Comment by Cisrox** [comment]
Closeable.

**Comment by 9600bauds** [comment]
But it wasn't addressed.

**Comment by Exxion** [comment]
It wasn't actually ever an issue though
At least the issue originally reported wasn't

**Comment by 9600bauds** [comment]
You really need me to open another issue for "please make exiting mechs and pods more intuitive"?

**Comment by Exxion** [comment]
Or at least rename and reopen this one
But people would be more likely to see it if you opened a new one anyway
