### ISSUE TITLE
Gee Timmy, how come centcom sent you two shards.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29462]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
648176ce0040d63f21f845a43f922bfbca856fb3

# Description
Two shards are spawning in the crates at engineering now a lot more frequently than usual 
# Steps to Reproduce
open a shard crate
# What you Expected
one shard
# What Actually Happened
two big old piece of cheese come out of the box

**Comment by Eneocho** [comment]
Assuming this is on synergystation with the 2 shardcrates. Feature.

**Comment by Eneocho** [comment]
Unless you mean 2 shards on the same box, if so, holy fuck run.

**Comment by Kurfursten** [comment]
Doubled contents in lockers/crates is an old persistent bug we've never been able to solve

**Comment by PavelCIA** [comment]
yeah that happens with all lockers
sometimes the HoS gets two lawgivers

**Comment by Eneocho** [comment]
On my way to open the shardbox on packed and accidentally ZAS the two shards from the same box into each other, delaminating both at once.

**Comment by DeityLink** [comment]
sounds like a case of initialize() being called twice. I'll investigate that later.
