### ISSUE TITLE
[Feature Request] Automatic Shuttle Call/ERT if nobody has been alive on Z1 for at least 5 minutes.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29460]
On the event of everyone dying in a round (something that, while uncommon, is a recurring affair on deadpop), you get an empty station with no way to end the round if there are no admins online. And methods to call it anyway (Derilect MoMMI making an AI and having it call the shuttle being the main one) are not done for fear of bwoink. 
Please add an automatic shuttle call or ERT if nobody's been alive on Z1 for at least 5 minutes. It could be IC'd as: "No life signatures have been detected on the station. An emergency shuttle has been sent in case our sensors are mistaken./An Emergency Response Team has been dispatched to inspect the situation." [discussion][featurerequest]

**Comment by Kurfursten** [comment]
Or just instantly call the shuttle if no one is alive on Z1, updated when a person dies.

**Comment by Armadingus** [comment]
I like the ERT idea, because it gives you the option of continuing the round. Also because it would be less awkward when the entire pop goes into spessmart or similar.
The fear is that it could be abused to get a SCP machine on deadpop and then you have people being xenos.

**Comment by Kurfursten** [comment]
You can always deadpop red alert with 2 people to call ERT and get the machine if that's your goal.

That SCP being available was a mistake if it affects our wanting to let the crew call an ERT.

**Comment by Eneocho** [comment]
Just blacklist the beno chem.

**Comment by Blithering** [comment]
If everyone's dead, you could just cut to the wide shot of the station and have the lights go out, no need for everyone to sit around in deadchat for a shuttle to arrive that noone's gonna board.

**Comment by Eneocho** [comment]
> 
> 
> If everyone's dead, you could just cut to the wide shot of the station and have the lights go out, no need for everyone to sit around in deadchat for a shuttle to arrive that noone's gonna board.

That actually sounds good. Though my immulshons when the autism TEG should've kept the station powered forever.
