### ISSUE TITLE
No trader clothes machine on Tradershuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29461]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
648176ce0040d63f21f845a43f922bfbca856fb3

# Description
the pr that split the two machines never got checked for meta
# Steps to Reproduce
meta trader
# What you Expected
two vendors
# What Actually Happened
just one

**Comment by Kurfursten** [comment]
It's at the casino
