### ISSUE TITLE
Unable to use numpad macros post Kanef targeting PR

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29466]
(WEB REPORT BY: burntdevil REMOTE: 206.221.180.138:7777)
# Revision
648176ce0040d63f21f845a43f922bfbca856fb3

# Description
Since the PR, macros using numpad have not functioned. Tested this with another user confirming the same. 

# Steps to Reproduce
>test \ key * spin macro
>rebind *spin macro from \ to num4
>hit num4 - no results
>rebind back to \
>spin

# What you Expected
Numpad macros to work off of hotkey toggle.

# What Actually Happened
Regardless of status of the hotkey toggle and numlock, macros bound to numpad buttons fail to fire off.

**Comment by ghost** [comment]
It explicity says in the keyboard controls help that numpad to target zones is irregardless of hotkeys, numlock just replaces numpad with arrows/home/end/pgup/pgdown etc

**Comment by cmdrstupid** [comment]
Having the same problem as well. Unbinding the new hotkeys in skin.dmf DID NOT restore old macros (windows just pings angrily when I press num5). Found a temporary workaround in manually adding old numpad macros to skin.dmf. I don't think I'm retarded, but it is a possibility.

**Comment by help-maint** [comment]
Yeah this is pretty shit, most of my macros are unusable now because there's no way to turn off the dumb targeting

**Comment by DeityLink** [comment]
Fixed by #29841
