### ISSUE TITLE
[Discussion] Extended frequency

### ISSUE THREAD

**Issue by PavelCIA** [d3athrow/vgstation13#29467]
[discussion]
I don't have anything against extended as a game mode but I think it should be toned down somewhat.
Is there going to be a change to the amount of extended rounds or at least an ingame poll for this with the options (more extended, less extended, already perfect)?

**Comment by drawsstuff** [comment]
1/20 rounds should be extended, is my personal take.

**Comment by PrimeDSS13** [comment]
17 extended rounds have rolled in 6~ days (unless I fucked up my counting somehow)

**Comment by Zth--** [comment]
> 17 extended rounds have rolled in 6~ days (unless I fucked up my counting somehow)

17 out of... ??

**Comment by Dacendeth** [comment]
17 out of 64, starting count at the first round of extended rolled after the pr merged.
9 out of 17 of those extended rounds had an admin press a button to make antags.

**Comment by PrimeDSS13** [comment]
67 to 70-ish rounds.
That seems around 25% of the time.

**Comment by gurfan** [comment]
way too often

**Comment by ShiftyRail** [comment]
I will get on it on Monday, Thursday at the very least. I am not available on the week-end.

**Comment by DeityLink** [comment]
Meanwhile there's been only 2 cult rounds since Extended was re-added. It's gone from about one a day to, well, it's been 4 days since the last cult round.

**Comment by Eneocho** [comment]
> 
> 
> Meanwhile there's been only 2 cult rounds since Extended was re-added. It's gone from about one a day to, well, it's been 4 days since the last cult round.

Some might argue that's a good thing, however.

**Comment by PavelCIA** [comment]
>Meanwhile there's been only 2 cult rounds since Extended was re-added. It's gone from about one a day to, well, it's been 4 days since the last cult round.

wtf I changed my mind, please make extended more frequent

**Comment by DeityLink** [comment]
Concerns should be alleviated after the latest changes
