### ISSUE TITLE
FRASS and SASS spheres don't protect against touching SM splinters.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29479]
Took a frass sphere and tried touching a SM spliter. Hand got vaporized.
[consistency]

**Comment by Kurfursten** [comment]
It doesn't call supermatter_act()

Should SASS/FRASS protect from picking up splinters? This wasn't in the intended scope but I guess it could be fine.

**Comment by Eneocho** [comment]
If it protects from both crystals and shards, it surely must detect SOME characteristic of the supermatter. If so, splinters should also be safe with a FRASS/SASS.

**Comment by gurfan** [comment]
seems reasonable that it would protect against splinters
