### ISSUE TITLE
Cant hit windoors with things you used to be able to.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#29486]
#### Description of issue
You used to be able to hit windoors with wrenches/crowbars/lit welders, doesnt seem to work anymore

#### Difference between expected and actual behavior
expected to Smash locked windoor with welding tool
got beep beep locked

#### Steps to reproduce
try to hit a windoor with a lit welder, as well as other tools, toolboxes still work though.

**Comment by tayachiya** [comment]
have you tried harm intent?

**Comment by Eneocho** [comment]
Even on harm intent you somehow try to open the windoor with the crowbar instead of breaking it open, which leads to the old dropping and kicking.
