### ISSUE TITLE
crit warnings fucking suck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29489]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
648176ce0040d63f21f845a43f922bfbca856fb3

# Description
they only appear when someone is cloned and it gives a link to JMP to the cloning tube, i have literally not seen them appear (as a min) at any other time

**Comment by Eneocho** [comment]
This must be the unforeseen consequence toomykins was warned about.

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/125772518-78221ecc-63fa-4642-b7f2-85c5e41cad0d.png)
what am I even looking at
