### ISSUE TITLE
Dionaea Adults perish from the cold in space (Intended Behavior?)

### ISSUE THREAD

**Issue by Optimism333** [d3athrow/vgstation13#29482]
# **Description of issue**
Through a series of unfortunate events, I ended up trapped in space and unable to move as a diona. I didn't expect it to be a serious problem beyond boredom and the inability to participate in the round. However, after about ten minutes, I started to take burn damage until eventually dying.

# **Steps to reproduce**
1.  Be diona
2. End up stuck in space without any gear
3. Be fine for a short time and then start taking burn damage until death

# **What was expected**
To be stuck in space for a LONG while and be bored, but alive.

# **What actually happened**
Died of burn damage that started to accumulate after about ten minutes or so.

**Comment by Dacendeth** [comment]
If you were naked I think you'd lose body heat slowly until you were cold enough to burn.
