### ISSUE TITLE
Vox and Diona don't have blood

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2950]
I seem to remember them having blood at some point but they sure as hell don't now.  It's one thing for skeletons and plasmamen not to, that makes sense, but this is a bit silly.

Now you could add blood in for them and be done but if you really wanted to do the job right, you would give them different blood than humans.  Whereas iron increases a humans blood regeneration rate, copper would do the same for Vox and plant fertilizer would do the same for Diona.

**Comment by AutismSpider** [comment]
Diona are base off the bay one 

Bloodless race over all same with the vox.

And when they did have working blood they were buggy as fuck you could drain them of blood and they would not died at fucking all.

**Comment by d3athrow** [comment]
Vox shouldn't have the no blood flag.
