### ISSUE TITLE
Feature Request: Players Can Vote for Dorf in August

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#29505]
I picked August because it doesn't have other holidays going on, Snaxi is disabled in that month, Dwarf Fortress was released in August, and as someone else said "it's hot like a forge".

Discuss.

**Comment by Theophrastus1** [comment]
I whole-heartedly support this

**Comment by boy2mantwicethefam** [comment]
I whole-heartedly support this

**Comment by ghost** [comment]
I'd be more specific and make it only votable on the very day, gonna work on this now.
