### ISSUE TITLE
Suicide Vest doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29508]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
87fa87bb2ba89c671b0abbab0b6b252295e3bc95

# Description
contrary to the vest's description, bumping into things/people does not trigger the suicide vest. I'm honestly not sure what does.
# Steps to Reproduce
wear the vest and don't explode
# What you Expected
exploding on contact with people
# What Actually Happened
nothing and sadness

**Comment by Securitymain** [comment]
@Kurfursten i think this can be closed, every time I've seen the vest it worked as intended

used it once too, worked fine. Probably a skill issue
