### ISSUE TITLE
Phazon and rtg cells also charge at -100% charge rate

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29512]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
87fa87bb2ba89c671b0abbab0b6b252295e3bc95

# Description
So a -100% charge rate phazon or rtg cell just negates one of their only downsides
# Steps to Reproduce
EMP cell
# What you Expected
To stop charging at -100%
# What Actually Happened
Keeps charging, and fast too

**Comment by Eneocho** [comment]
It means self charge rate, not regular charge rate, something something the inner generator circuitry gets fried and can't charge the RTG's battery side. It deserves a rewrite though.
