### ISSUE TITLE
Clone from backup doesn't keep vampire spells unlocked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29521]
(WEB REPORT BY: konater REMOTE: 206.221.180.138:7777)
I was backed up as a vampire with no blood drank, unlocked some spells later on and was then cremated. I was still a vampire after I was cloned but had no spells unlocked, my blood total was also set to when I was cremated rather than backed up. Sucking blood later gave me a later spell but didn't give me back the previous abilities.

**Comment by DeityLink** [comment]
Grouped up in #30360
