### ISSUE TITLE
Derelict MoMMi Law Message

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29522]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
87fa87bb2ba89c671b0abbab0b6b252295e3bc95

# Description
Derelict MoMMis do not see their unique law requiring them to remain on their original station when they join the game.
# Steps to Reproduce
Join the game
# What you Expected
See the ion law above law 1 requiring you to stay on your original station
# What Actually Happened
Don't see it. You stil lreceive the law since Show Laws shows the law, but it does not show up when you join the game.

**Comment by Eneocho** [comment]
You do. You literally get a line saying something along the lines of "You were made on this station, DO NOT LEAVE IT".

**Comment by nervere** [comment]
It actually does not say that. This law is completely invisible unless you use Show-Laws.
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/e231ab22-ac70-4bed-ad9d-78f0b70d7c24)
