### ISSUE TITLE
Computers are sort of broken, but just slightly

### ISSUE THREAD

**Issue by xevonix** [d3athrow/vgstation13#2953]
Alright, so it seems that computers are being real buggy.
They no longer auto-update when you press a button inside their box. For example, if you play the arcade game you will have to refresh the box every time you press an action to do something opposed to how it use to update immediately. This wouldn't be so bad of a thing if it was limited to only the arcade games, but it also happens to things like the genetics cloning computer. It makes it really difficult to tell if you have saved someones backup or not because you have to refresh it every fucking time.
The Crew Monitoring computers are always updating if their box is left up, even when you are nowhere close to them. In my opinion this isn't such a bad thing, but it is clearly a bug despite how much I wish it wasn't. I can walk to the computer once and click on it and keep seeing people's stats being updating no matter if I am in engineering or the permabrig.

**Comment by d3athrow** [comment]
Updates just fine for me.
