### ISSUE TITLE
Building an Airlock with a RCD gives you a weird default name for the airlock.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29538]
Whenever you try to build an airlock with an RCD it gives you "mproper [AIRLOCK NAME]" as the name. So if you built an engineering airlock, the default name is "mproper Engineering Airlock", which I assume is from an "/improper" line where it shouldn't be.
something something my immulshons.
[bugfix] [grammar] [oversight]

**Comment by nervere** [comment]
Can't replicate, doesn't seem to be an issue anymore.

**Comment by nervere** [comment]
Reopening because I just saw this happen in a round.

**Comment by Eneocho** [comment]
I have it happen every time. Whenever you want to build an airlock, the default name is "mproper [airlock type]".

**Comment by kacurasuo** [comment]
this is because of the area name i believe, since areas pop up on the blueprints called "mproper _____" like "mproper chapel" "mproper kitchen"
least on box

**Comment by kacurasuo** [comment]
actually I take that back, I don't think it's because the area names are weird, I think they're just both weird for the same reason
