### ISSUE TITLE
Annoying Storage UI Slapperoo Mk. II

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29533]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
Belts and the like which usually have a row inventory of 7 squares to put stuff, when you put 7 things in it activates the second row that would normally only matter if you have 8 or more things in there and it's a really small issue but it annoys me to have an empty row when this slot expansion crud was coded specifically to save screen space when 7 or less items are being stored. If you guys could fix this I'd buy you a pizza if I had a means of paying for it. Do you accept e-check?

**Comment by Eneocho** [comment]
See both #29408 and #29518.
