### ISSUE TITLE
Library uploads

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#2955]
When you upload a book, it no longer appears on the archive until the next round.

**Comment by d3athrow** [comment]
When you upload a bug it should be appended to the end of the book list.

**Comment by Kurfursten** [comment]
@NigglyWiggly What has your testing over the last eight months turned up?

**Comment by Zth--** [comment]
Still testing, will need more months

**Comment by Kurfursten** [comment]
Has anyone tested this further? Does anyone play librarian?

**Comment by NigglyWiggly** [comment]
I haven't uploaded a book in a while, but it looks like it might be fixed.

**Comment by NigglyWiggly** [comment]
Just tested, this is fixed.
