### ISSUE TITLE
nukies can also be blobs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29553]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
88ffb70118d9dfc7d757e0d0ead628f9a8955a45

# Description
nukie was a blob
but even that doesnt work, cause he just exploded into normal gibs instead of blobbing when he reached the station

**Comment by DeityLink** [comment]
> but even that doesnt work, cause he just exploded into normal gibs instead of blobbing when he reached the station

Beyond the obvious dual-antag problem, I'm really curious about this particular issue. Would the explosive implant have pre-emptively gibbed him to prevent blobification?

**Comment by ShiftyRail** [comment]
I don't even know how this is possible, because I can't reproduce it.

**Comment by Blithering** [comment]
We've had a bit of a spree of nukie+other antagonist role the last couple of days.

**Comment by Zth--** [comment]
There's no assigned candidates when drafting, that happens in execute() (and even then blob doesn't seem to use assigned on execute, while other rules do)
https://github.com/vgstation-coders/vgstation13/blob/d04f75dc75c50b203479d77c93aa6468c66f0b2f/code/datums/gamemode/dynamic/dynamic.dm#L433

So this loop never runs, making it so the candidate list keeps the same for every ruleset that gets picked
