### ISSUE TITLE
Cultist Tome Unreadable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29558]
(WEB REPORT BY: punishedpajeet REMOTE: 206.221.180.138:7777)
# Revision
88ffb70118d9dfc7d757e0d0ead628f9a8955a45

# Description
Every other time I open the cultist tome, it has a background that makes it totally unreadable. 1st time is unreadable, 2nd is blank background (readable), 3rd is unreadable, etc. The text also doesn't wrap according to the window

https://imgur.com/a/hJ0tZ3l

# Steps to Reproduce
Make a book using the See Blood Hell runes and open it

# What you Expected
Legible text with proper word wrapping

# What Actually Happened
Scribbles and chickenscratch

**Comment by DeityLink** [comment]
You mean people actually read it?

I mean to be fair you the window isn't meant to be resizable, it was an artistic decision so the background image would fit the text column. This was a very bad idea in hindsight. I've got a tome overhaul planned so this whole window will be replaced at some point.
