### ISSUE TITLE
Nukies and blob rolled at the same time

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29554]
(WEB REPORT BY: apcunlocked REMOTE: 206.221.180.138:7777)
# Revision
88ffb70118d9dfc7d757e0d0ead628f9a8955a45

# Description
Ops + blob both at roundstart in a contested system, who the fuck thought this is a good idea

# Steps to Reproduce
Play game, expect to have fun

# What you Expected
To have fun
# What Actually Happened
I did not have fun and this is stupid

**Comment by APCUnlocked** [comment]
Also one of the ops was apparently a blob as well, please fix this is really dumb
