### ISSUE TITLE
DYNAMIC IS FUCKED SOMEONE FIX IT

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29555]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
88ffb70118d9dfc7d757e0d0ead628f9a8955a45

# Description
duplicate of #29552 but with a better title

LOOK AT THIS:
Threat Log
Starting Threat: 55.0717, midround: 43.9724
12:05: Roundstart Vampires spent 15
12:05: Roundstart Blob Conglomerate spent 45
12:05: Roundstart Syndicate Traitors spent 10
Remaining threat/threat_level: 0/55.0717
Remaining midround threat/threat_level: 43.9724/43.9724

**Comment by anunknownentity03** [comment]
shiftyyyyyyyyyyyy!!!!!!

**Comment by APCUnlocked** [comment]
Really fucked, multiple rounds in a row with blob + other fucking round ender or a gorillion "normal" antags. bls fix literally unplayable

**Comment by drawsstuff** [comment]
fucking torture, unplayable

**Comment by Zth--** [comment]
I looked into it. Logs start at 22:21 [here](http://game.ss13.moe/logs/2021/05-May/18-Tuesday.log).
Drafting rules don't seem to decrease the threat used and there doesn't seem to be any check other than "don't draft this rule if its cost is higher than current threat". That means that if my threat is 50 I can draft 5 rules of 45 cost.

Also `spend_threat` doesn't check if it has _any_ threat to spend at all. So if you have 0 threat left you can still call `spend_threat` and keep doing things. This is simply bad design.

Roundstart nuke ops don't count as round-ender ruleset so blobs+nukes will still be possible unless that's changed.

**Comment by Exxion** [comment]
>Roundstart nuke ops don't count as round-ender

Oh, the antag whose primary goal is to end the round?

**Comment by DeityLink** [comment]
> Roundstart nuke ops don't count as round-ender ruleset

wait what?
