### ISSUE TITLE
Emitters no long increment the Megaenergy var on the R-UST EM field needed for operation

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2958]
The change from particles to beams no longer charges the EM field

**Comment by d3athrow** [comment]
The rust is not meant to be workable but I'll see what I can do.

**Comment by SarahJohnson489** [comment]
Well it worked fine as a heat generator so it was half working. Really shined when you had a bank of TEG's sucking in a large bit of plasma which outputs into more TEG's to step it down for either venting or recirculation back into the heater portion. If someone capable with familiarity with the rad collectors took a look at it they could just make X radioactivity in the EM field or however it was supposed to handle radioactive rods and spits out irradiation ala SM shard to the nearby X tiles and powers rad_collectors.

**Comment by PJB3005** [comment]
I think you should be able to circumvent this by using the RUST's gyrotrons (if they even work in the first place)
