### ISSUE TITLE
Shocked grilles are a LITTLE too easy to break now

### ISSUE THREAD

**Issue by help-maint** [d3athrow/vgstation13#29593]
Ever since grilles were made to take damage from thrown items, all you have to do is throw the glass shard into the grille to safely destroy it. You can do this even faster by just kicking the shard right where it drops, which instantly destroys the grille in one hit.
It used to be that you needed a welder or take a very long time breaking the grille with the shard in hand instead, powercreep ensued

**Comment by ghost** [comment]
Even just hitting them with the glass shard breaks them now, making breaking out of packed perma way too easy.

**Comment by ShiftyRail** [comment]
Our secret technique...

**Comment by APCUnlocked** [comment]
Shocked grilles might as well not exist at all but I assume that's just a feature, there is no scenario ever where you'd be cucked from getting in/out of a place with grilles because you can just kick things at them and be done with it.

**Comment by assmops** [comment]
I mean there is the `**TG**` mechanic where things that hit grilles are subject to electrical arcs that shock/EMP things around them
But I'm pretty sure no one wants that

**Comment by Exxion** [comment]
Huh. I thought the change that made grilles take damage from thrown items was longer ago than it was. #22038

**Comment by BomberBro** [comment]
Christ that was an unatomic PR

**Comment by DeityLink** [comment]
> 
> 
> Even just hitting them with the glass shard breaks them now, making breaking out of packed perma way too easy.

It always did, didn't it? I always saw shocked grille as a "metacheck" of your skill level.

**Comment by Exxion** [comment]
IIRC it always did, but it used to shock you because conductivity was broken
But that was a long time ago

**Comment by west3436** [comment]
Rewrite as a detailed feature request if desired
