### ISSUE TITLE
You can't put airshield in your bag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29592]
(WEB REPORT BY: awadwduwu REMOTE: 206.221.180.138:7777)
# Revision
7b5288fa0a7b44aeeb088fb28cf3f161d8442267

# Description
Clicking on bag acts as if you clicked your own tile
# Steps to Reproduce
click bag
# What you Expected
go bag
# What Actually Happened
no bag

**Comment by Kurfursten** [comment]
You can if you click twice, same with place on table
