### ISSUE TITLE
The mutant apple tree has suddenly mutated into apple tree!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29608]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
ce4bd604cdd766877e91219f8673d621c363b707

# Description
Tried turning an apple tree into a golden apple tree. It turned into itself and won't mutate.
# Steps to Reproduce
Plant Apple tree.
Dose Radium to mutate.
Observe the tree turn into itself.
# What you Expected
Golden Apples.
# What Actually Happened
Fucking normal apples.

**Comment by DeityLink** [comment]
It actually mutated into a poison apple tree, which is the other type of apple tree that regular apple trees can mutate into.
Those are actually named and look just like regular apple trees and apples, but they contain cyanide.

I sure hope you didn't just hand out those "fucking normal apples" to the crew for snacks.
