### ISSUE TITLE
Ghosts can remove alert from request console sprites

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29619]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
619fe85dc99425858e6a096a085ca592b3dd23e0

# Description
When attack handing as ghost, alert sprite changes to normal
# Steps to Reproduce
* Ghost
* Click on an active alert RC
# What you Expected
To not interact
# What Actually Happened
Changed sprite

**Comment by Eneocho** [comment]
Would've sworn this was fixed. Or was that the Station Alert Console?

**Comment by ghost** [comment]
that was sec alerts, and i fixed it
