### ISSUE TITLE
Biohazard Alert 5 DEFON2

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29628]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
619fe85dc99425858e6a096a085ca592b3dd23e0

# Description
The announcement is mispelled
# Steps to Reproduce
* Get it to be blob
* Have defcon 2 come
# What you Expected
DEFCON 2
# What Actually Happened
DEFON 2

**Comment by ShiftyRail** [comment]
feature

**Comment by nervere** [comment]
This got fixed a while back.
