### ISSUE TITLE
Feature request: On station vox raiders shouldn't be deleted if their shuttle leaves

### ISSUE THREAD

**Issue by TGFH** [d3athrow/vgstation13#29624]
In a recent round a vox raider was taken into custody and was being interrogated. The (human) captain flew the stolen vox shuttle back to the shoal for the hell of it. This instantly deleted the living vox raider on the station the same way it would delete returning vox raiders.
I don't think this really counts as a bug, but if you take a raider alive it'd be nice to be able to keep them in the round even if their buddies fly back home.

**Comment by Zth--** [comment]
>I don't think this really counts as a bug

this is DEFINITELY a bug

**Comment by Kurfursten** [comment]
even worse because NORMAL CREW can send the raider shuttle

if one person breaks out they can send the shuttle home and delete all raiders
