### ISSUE TITLE
laser beams seem really buggy in space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29620]
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
619fe85dc99425858e6a096a085ca592b3dd23e0

# Description
firing laser shots while using a jetpack seems to have some sort of desync, the beams either dont appear at all or appear very delayed 
# Steps to Reproduce
fly with jetpack and shoot laser, may only be the science laser rifle
# What you Expected
laser beam effect to work as usual
# What Actually Happened
invisible beams or beams appearing 4 seconds later

**Comment by Dacendeth** [comment]
I've seen this before with the spacepod lasers as well.

**Comment by Eneocho** [comment]
I have similar visual problems whenever someone fires the rainbow gun or very quickly fires a non-egun laser gun.

**Comment by TGFH** [comment]
I've noticed this too. There seems to be a big delay when you fire lasers while flying around with a jetpack. It feels like you're playing with 250 ping.

**Comment by DeityLink** [comment]
@PaulRitter how do your raytracing beams handle hitting the edge of the map? Do they move through Z-Levels?
