### ISSUE TITLE
Unable to melee attack windoor with crowbar regardless of intent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29647]
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
629303bbaa1ab005600faeecd06fac53cae4374a

# Description
Swinging at a windoor or clicking on it with a melee tool does not hit the door with the tool, but instead attempts to open the windoor, even on hurt intent.
# Steps to Reproduce
Go to the windoor in the box library, hold a crowbar in your hand, and click on the windoor.  Cycle through the intents while clicking on the windoor, finding that none will hit the windoor.
# What you Expected
I expected non-help intents to hit the windoor, eventually breaking it.
# What Actually Happened
I calmly attempted to open the windoor while on the harm, disarm, and grab intent until I gave up and went around it.

**Comment by robintime** [comment]
#29486
