### ISSUE TITLE
[Bug/Needs more testing] Somethings off about singularities

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2964]
This has happened twice now and there's no good explanation as to why.  I'll describe each instance and maybe someone can explain what happened.

1.  The singlo was at stage 1 and immobile, very close to one of the Field Generators.  I had late joined and was not aware of what happened during the round but some set of circumstances led to it being unable to move and seemingly producing 0 power.  Containment failed due to power issues and when I went to turn them back on I got very close to the singularity, well within its pull distance and I should have been sucked towards it.  But I wasn't.  I turned containment back on and increased the PA power and strength to increase the singlos stage to 3.  However the singularity did not increase in size, even after minutes of the full strength PA blasting it.  Even more inexplicably, 5 of the 6 radiation collectors read 0 watts generated (they all had 1013kPa of plasma in their plasma tanks!).  It was like the singlo wasn't even there, but it definitely was.  The round ended shortly after and I didn't have time to explain it.

2.  Again latejoining, the singlo had been acting strangely according to the people who had been playing engineer before I arrived so the PA was shut down.  The singlo was at stage 0 when I turned on the PA to investigate and increase its size but again after several minutes it did not increase in size.  However this time the radiation collectors were producing a meagre amount of power expected from their plasma tanks levels and singularity size.  

It's all very, very weird.  This has happened twice in roughly two weeks so it's not common, but frequent enough for me to notice.

**Comment by CptWad** [comment]
Oh hey I know what you are talking about
As someone who set it up:
*The singlo will lose its size much faster now. I think it either feeds the singlo less or fires off much slower now
*Generates shit power. When hovering between stage 3-4 was only producing a third of what I remember it producing. Will have to test the levels more.

Usually you used to be able to set the singlo off and leave it alone to shit out energy but now you need to keep an eye on it and make sure it stays alive for less power than the solars produce.

**Comment by Probe1** [comment]
Now normally you'd be right, dylan nerfed it a while back and it's reasonable now.  To get decent power you have to fill the plasma tanks all the way and to get real power like you used to you have to use cold plasma to fill em.  

But in both cases these plasma tanks were absolutely topped out and it still generated 0 watts the first time and something like 13kW the second time.  And it wouldn't increase in size no matter what steps were taken, including throwing things into it.

**Comment by CptWad** [comment]
I do fill the tanks. Even when I don't have CE access its easy enough to break in and open the shutters.
I know dylan nerfed it but I am saying that it seems even weaker than the nerf suggests.
I may try in one of the next rounds and do some science with the singlo to see if the guide needs adjustments to how to set up. May be that the PA is fucked though. Will report findings.

**Comment by CptWad** [comment]
Okay Post round test results:
3 Fully filled tanks of plasma: 348771W
3 unfilled tanks of plasma: 250873W
Time to grow:
It takes about a minute of power 2 PA fire to get to the next level in singlo life.
The PA left on one keeps the singlo stable

**Comment by Probe1** [comment]
Thank you for having a look there.  
https://github.com/d3athrow/vgstation13/issues/2875#issuecomment-74096926

I suspect these issues are tied together.

**Comment by Probe1** [comment]
I'm going to pray that https://github.com/d3athrow/vgstation13/commit/d4d6f5b32ba272ab9ff1aecdfb0eab0738d02119 fixes it and close for now.  Will reopen if further problems manifest.
