### ISSUE TITLE
Ore crates are leaky

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29650]
(WEB REPORT BY: cucumberia REMOTE: 206.221.180.138:7777)
# Revision
629303bbaa1ab005600faeecd06fac53cae4374a

# Description
Mining crates randomly drop all the ore inside
# Steps to Reproduce
drag a mining crate around near the mining outpost
# What you Expected
ore to stay in the crate
# What Actually Happened
having to stuff ore back in every couple of tiles

**Comment by SonixApache** [comment]
inb4 ghosthands

**Comment by DeityLink** [comment]
Actually playerhands
