### ISSUE TITLE
Biohazard outbreak containment status reaching critical mass, total quarantine failure is now "possibile".

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29663]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
4ae74d0e58d67f2ce8d209c8426d71481d82ea73

# Description
It says possibile.
# Steps to Reproduce
Blob reaches nuke stage.
# What you Expected
Possible.
# What Actually Happened
Possibile.

**Comment by help-maint** [comment]
Unplayaible
