### ISSUE TITLE
The vermin infestation says gremlin assistants, but the mob name is greymlin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29661]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
4ae74d0e58d67f2ce8d209c8426d71481d82ea73

# Description
Title.
# Steps to Reproduce
Vermin infestation with gremlins.
# What you Expected
Consistency.
# What Actually Happened
Immulshons shattered.

**Comment by gurfan** [comment]
literally not a bug
