### ISSUE TITLE
Cardboard doesn't fit in microwave unless you have lots of it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29672]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
6919a00ef3b6d38924641a6ccdc3fbbebb4ddb6d

# Description
Cardboard doesn't fit in microwave if you only hold 1 sheet.
# Steps to Reproduce
Have a stack of 1 cardboard. Try to put it in microwave. You can't
Add another cardboard to stack. Stack now has 2 cardboard. You can now put 1 of them in microwave.
# What you Expected
to put one piece of cardboard in microwave
# What Actually Happened
I need 2 pieces to put 1 piece in microwave.

**Comment by ghost** [comment]
yeah this makes cup ramen impossible to make

**Comment by Theophrastus1** [comment]
I've made chicken recipes with 1 cardboard fairly recently, so unless this was within like the last two weeks, that's pretty weird.

**Comment by DeityLink** [comment]
yeah same, I remember making chicken buckets/nuggets like less than a month ago.

**Comment by kernikov** [comment]
Same issue occurs with teeth
