### ISSUE TITLE
Shuttle consoles cannot be unbolted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29674]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
6919a00ef3b6d38924641a6ccdc3fbbebb4ddb6d

# Description
Shuttle consoles UI interact instead of allowing unbolting
# Steps to Reproduce
Use wrench on console
# What you Expected
Unbolt and move
# What Actually Happened
UI interacting

**Comment by ghost** [comment]
*Note: You can finally unbolt them after some deconstruction, but still why.
