### ISSUE TITLE
Taking the brain out of a slime man's corpse then putting it back in causes it to disappear to the shadow realm

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#29684]
Title

**Comment by Eneocho** [comment]
Slimemancode is horribly broken.

**Comment by Killette2** [comment]
I was the victim here. When I re-entered my body it took me back to my body leading me to believe medbay just didn't understand until they confirmed they were trying. Not sure if there was some horrible gunk where my brain was in my body but not my "head"
