### ISSUE TITLE
Unfuck transit tubes

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#2969]
At the minute they randomly cause pressure damage, can't have corpses ejected out of them permanently trapping within them and are generally rather buggy. It would make a world of difference if they could be improved.

**Comment by Cisrox** [comment]
Closeable, transit tubes are on only one map, and I think you can click the tubes or something to remove objects inside of it.

**Comment by ihadtoregisterforthis** [comment]
They are on tubes on box and deff, and tubes don't look like they've been touched in a while. This still stands

**Comment by PJB3005** [comment]
@Cisrox 1 map is more than enough.
