### ISSUE TITLE
Couldn't Thermite an R-Wall.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29702]
#### Description of issue
Splashed thermite on some reinforced walls, tried igniting it with both the Swiss' Zippo and a Welder, but all it said was that I "pushed" the wall.
#### Difference between expected and actual behavior
Expected to ignite the thermite and melt the wall, not to push the wall.
#### Steps to reproduce
Pour thermite on a wall, try to ignite it, fail miserably.
#### Length of time in which bug has been known to occur
Thermite worked last week, so at most one week.

**Comment by Dacendeth** [comment]
This is bigger than splashing thermite on Rwalls, you cant splash with beakers at all, think it might be related to #29630 since that touched splashing with condiment bottles and was merged yesterday?

**Comment by DeityLink** [comment]
Fixed by #29705
