### ISSUE TITLE
[Metastation] No atmospheric monitoring equipment in tcomms monitoring room

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2970]
We need a console to monitor the temperature of telecomms in the monitoring room.  Check out Box to see how it works.  Otherwise, you have to go in there yourself and find out what temperature it is and that's not an optimal solution.  

Speaking of going into tcomms, it needs proper airlocks like the setup on Box.  Losing cold atmos inside tcomms is bad news.

![image](https://cloud.githubusercontent.com/assets/8550416/6179935/576fc070-b2ec-11e4-8fd9-7ad2480ba753.png)

**Comment by IratePirate** [comment]
Fixed up sensor and added atmos monitor.

I had a Box style advanced airlock a few months ago but problems with the door buttons not working (they seem fucked elsewhere on the map too) means I had to postpone adding one. I'll try to get it working but don't hold your breathe. Blocking air tile at least helps to an extent.

**Comment by Probe1** [comment]
@IratePirate Was this fixed up?  I checked the map render and didn't see the change.

**Comment by Probe1** [comment]
Still an issue.
