### ISSUE TITLE
Yet another broken safe.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29710]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
bbba352827f0d8a6ffdc9b112ac5a3431fab7038

# Description
Plink on 140, plunk on 160. If I set the first tumbler, the second one unsets.
# Steps to Reproduce
Test with safes until you find another broken one.
# What you Expected
To be able to open the safe and get some goodies.
# What Actually Happened
PLUNK
CHINK
CLACK CLACK SCRAPE

**Comment by BomberBro** [comment]
MOM IT HAPPENED AGAIN

**Comment by Dacendeth** [comment]
The bug cant be fixed, it's time to label it a feature and just say sometimes safes are poorly made.

**Comment by Eneocho** [comment]
@DeityLink

**Comment by DeityLink** [comment]
You know what would have really been helpful would have been an actually screenshot of the messages sent by the safe, or if an admin was there the tumbler vars.

**Comment by DeityLink** [comment]
Also you're supposed to set the second tumbler first you know?

**Comment by DeityLink** [comment]
Anyway if by the end of the hallway I haven't found a broken safe I'll just assume that you're bad at breaking into safes. 
![image](https://user-images.githubusercontent.com/7573912/120922319-bfe2c200-c6c8-11eb-8c25-5c890a405718.png)

Next time it happens grab an admin and tell them to ping Deity. Or ask them to check and save the "dial" and all 4 tumbler vars.

**Comment by DeityLink** [comment]
Alright nevermind, turns out I misunderstood the bug. It occurs every time if both tumblers' unlock positions are exactly opposite (as in, there is a 180 degree angle between both). Now to see whether I should prevent that, or fix the tumbler going out of position when it happens (if that can even be done)

**Comment by DeityLink** [comment]
Alright so it's a bit wider. A 35, 36 or 37 difference (175°, 180°, 185°) will all lead to the second tumbler going out of position. Each tumbler unlock position can be one of 67 different position, so each distance between the two has about 1.5% chance to occur. There are 3 unsolvable distances, which means that each safe has 4.5% chance to be unsolvable.

**Comment by Eneocho** [comment]
> 
> 
> Also you're supposed to set the second tumbler first you know?

I did set up the second tumbler first, then the first. The second tumbler can't unset if it wasn't set before the first. It's the same bug from that one vox outpost safe.

>
> Next time it happens grab an admin and tell them to ping Deity. Or ask them to check and save the "dial" and all 4 tumbler vars.

There were no admins online, none at all.

**Comment by DeityLink** [comment]
> 
> 
> > Also you're supposed to set the second tumbler first you know?
> 
> I did set up the second tumbler first, then the first. The second tumbler can't unset if it wasn't set before the first. It's the same bug from that one vox outpost safe.
> 
> > Next time it happens grab an admin and tell them to ping Deity. Or ask them to check and save the "dial" and all 4 tumbler vars.
> 
> There were no admins online, none at all.

😔
