### ISSUE TITLE
Microwave Grammar for cherries (plural appears as cherriess)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29715]
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
bbba352827f0d8a6ffdc9b112ac5a3431fab7038

# Description
The microwave adds an extra s to the end of cherries when cherries is already plural.
# Steps to Reproduce
Put a couple cherries in the microwave, and examine or look inside the microwave menu.
# What you Expected
Cherries: 2 cherries
# What Actually Happened
Cherries: 2 cherriess

**Comment by nervere** [comment]
Not sure what could've caused this, but I just tested it and it's no longer an issue.
