### ISSUE TITLE
Laser tag lasers are not disappearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29721]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
3d5e21694789582e623a4e4b22f74a2ddf27baa4

# Description
I blame Deity. Look at this shit.
https://i.imgur.com/aI07I3X.png
# Steps to Reproduce
Laser tag gun
# What you Expected
Laser tag fun
# What Actually Happened
Cancer

**Comment by DeityLink** [comment]
Fixed by #29720
