### ISSUE TITLE
Invisible bullets leave visible shrapnel

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29723]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
66c1507e2a00b00972e891247a108462153cd1f8

# Description
Invisible bullets with shrapnel pulled out in surgery have visible shrapnel
# Steps to Reproduce
* Get shot by mime gloves
* Get bullet bits pulled out in surgery
# What you Expected
Invisible shrapnel or none at all
# What Actually Happened
It's visible

**Comment by Eneocho** [comment]
The immulshons. We can just handwave it as there being a mime spell that affects the bullet as a whole but not the bullet parts.
