### ISSUE TITLE
Cant unstack money

### ISSUE THREAD

**Issue by Riukanojutsu** [d3athrow/vgstation13#2973]
Once you stack credits chips ITS FOREVER

**Comment by Kurfursten** [comment]
@deity_link May interest you

**Comment by DeityLink** [comment]
Right, I'll fix that up.
Note that currently you can separate them by using a PDA though.

**Comment by Exxion** [comment]
Was this fixed?

**Comment by Intigracy** [comment]
Was this fixed?

**Comment by gbasood** [comment]
Needs more testing label for so long that I think we're good

**Comment by DeityLink** [comment]
I'm pretty sure I fixed it a long long time ago.
