### ISSUE TITLE
Ore Crate on Boxtstaion spits out ore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29736]
(WEB REPORT BY: miniaturebigfoot REMOTE: 206.221.180.138:7777)
# Revision
7aa4ceb62caa8080093a65e1aa1a4d5b1b0aae99

# Description
The ore crate in the south airlock on the mining roid cannot hold ore, and spits it back out. Other crates do work.
# Steps to Reproduce
Get the ore crate in the south airlock on the mining sttaion.
Put ore in.
Watch it fall out.
# What you Expected
For the crate to hold ore.
# What Actually Happened
It does not hold ore.

**Comment by Eneocho** [comment]
Related to #29650
