### ISSUE TITLE
being cloned resets your default language

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29733]
(WEB REPORT BY: locese REMOTE: 206.221.180.138:7777)
# Revision
7aa4ceb62caa8080093a65e1aa1a4d5b1b0aae99

# Description
title
# Steps to Reproduce
set default language as any other than the starting one, die, get cloned, it's back
# What you Expected
to continue lisk, lisk, hrr, hrr
# What Actually Happened
Galactic Common

**Comment by DeityLink** [comment]
ONE MORE TICKET REJECTED
