### ISSUE TITLE
[Box] Execution chamber shows up as title on APC and power/air alerts

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2974]
Somewhat of a problem for the AI and why the door title was changed from execution to prison wing. The area name was overlooked.

**Comment by Intigracy** [comment]
All of the airlocks to execution chambers are named execution chamber, as is the area for the execution chamber. It's not really a problem for the AI because just because there's an execution room doesn't mean that humans are going into it, considering there's nonhuman crew members.

**Comment by Cyadox** [comment]
>Bug label
Should we change it or keep it as it is? I haven't noticed any problems from AI players Law 1ing over it.

**Comment by Kurfursten** [comment]
@clusterfack I agree that this doesn't seem like a bug, and actually might deserve Not A Bug / close

**Comment by Cyadox** [comment]
>@clusterfack
@Kurfursten, I....

**Comment by Kurfursten** [comment]
I know you suggested it close, I wanted clusterfack to see the Issue and close it

**Comment by Cyadox** [comment]
My mistake then, I thought things were getting weird

**Comment by Intigracy** [comment]
close
