### ISSUE TITLE
Mech Riding View Is Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29755]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
16ebae11f40f3539400fd07f8cb13e4caaf428d5

# Description
Enter a mech and while the camera will follow you left to right, it will not follow you up and down.
# Steps to Reproduce
Enter a mech and move around
# What you Expected
Camera to follow
# What Actually Happened
It followed when moving left and right, not up and down.

**Comment by DeityLink** [comment]
Known Byond bug ( http://www.byond.com/forum/post/2690420 ) , I already made a demo for Lummox and he might have resolved it already, either way we can do nothing but wait for Byond to update. (or you can downgrade to 513 on the stable branch in the meantime)

**Comment by jwhitak** [comment]
Temporary fix: Restart byond client while inside the mech. Camera will be working normally. Bug will return if you exit and reenter.

**Comment by DeityLink** [comment]
Closing this one as #29757 is more encompassing
