### ISSUE TITLE
[Feature Request] For the richest escapees highscore to reset monthly/weekly as was promised.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29756]
Zth said that resets "Weekly or monthly was a plan from the start." on #27558. 
At least add a adminbus button to reset the money highscores so you don't have to see the same 5 guys who went vault exploring on lamprey and found the infinite money on the vox metaclub vault.
[featurerequest]

**Comment by ghost** [comment]
im not one of those people and i show up for the record, lot of it is the lotto event too

**Comment by Eneocho** [comment]
On one recent round I won a million credits on the lotto as a plasmeme librarian (Also, the lotto winner name is fucked as plasmeme, it didn't say the plasmeme name, it said a randomname, possibly the plasmeme's original body's name). I didn't even appear.

**Comment by DeityLink** [comment]
I was thinking earlier today when doing scoreboard stuff that it might be time to revamp this feature. Nobody even cares about it now that the top 5 are out of reach anyway. Either way I'll see in a few days.

**Comment by Eneocho** [comment]
@DeityLink Are you working on the richest escapee thing?
