### ISSUE TITLE
Alien Issues

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#2976]
More weird bugs from me
In a round with aliens the following issues arose:
*Facehuggers keep jumping on a host thats already implanted
*At one point all me and my alien friends could say was "a" when we typed anything in, This lasted mere moments
*Something to do with plasma and weeds when combined causes you to lose the ability to gain plasma from either source,

**Comment by clusterfack** [comment]
I had a bug myself, I threw a facehugger in one of my pockets.

Then I removed it and dropped it, and I was capable of removing it from my pocket again ad nauseam. This also prevented me from putting things INTO that pocket. It was the left pocket, the image of the facehugger didn't appear in it, and I think I closed my client at some point as well.

**Comment by CptWad** [comment]
Also facehuggers can become toxic from plasma meaning that planting them on humans faces cause massive damage due to wearing toxic "Clothing"

**Comment by clusterfack** [comment]
Oh dear god was that what that was? I was wondering why all the monkeys were just keeling over.

**Comment by CptWad** [comment]
More fuel to the flame
Beepsky will target xenos and handcuff them
There is no proper resist button and no message saying you are cuffed. Less robust players wont know that you can type resist in the console.

**Comment by d3athrow** [comment]
>

I had a bug myself, I threw a facehugger in one of my pockets.

Then I removed it and dropped it, and I was capable of removing it from my pocket again ad nauseam. This also prevented me from putting things INTO that pocket. It was the left pocket, the image of the facehugger didn't appear in it, and I think I closed my client before it disappeared as well.

I can't reproduce.

**Comment by CptWad** [comment]
Based chicken

**Comment by CptWad** [comment]
Alright thunderdome test results:
Facehuggers no longer get infected with toxins :+1: 
Beepsky no longer cuffs aliens or attacks them :+1: 
But when attacking I found that when aliens are stunned they can only stammer "a" I found this out from the test. 
Facehuggers will still jump on impregnated monkeys :-1: 
Weed and plasma regen is now good and not buggy :+1:

**Comment by CptWad** [comment]
Gonna close this now. The stammer "a" thing is fix but the monkey impregnate thing may just have to be a feature.
