### ISSUE TITLE
Soldering Iron for MoMMIs

### ISSUE THREAD

**Issue by churchtummy** [d3athrow/vgstation13#29760]
#### Description of issue
MoMMIs have every tool but soldering irons. It would be neat if they had soldering irons.

#### Steps to reproduce
1. Start as MoMMI.
2. Have no soldering iron.

**Comment by Eneocho** [comment]
This would need for a solder iron child that either doesn't use sacid but rather borg power, a soldering iron that self-refills, like the MoMMI cables or a run of the mill solder module that works like the welders.

**Comment by Kurfursten** [comment]
Crabs were never intended to come with a soldering iron, especially one that refills for free

**Comment by DeityLink** [comment]
do mommi welding tools also recharge for free? If not neither should a MoMMi soldering iron.


> Crabs were never intended to come with a soldering iron, especially one that refills for free

To be fair soldering irons are fairly recent compared to MoMMi

**Comment by churchtummy** [comment]
> do mommi welding tools also recharge for free? If not neither should a MoMMi soldering iron.

MoMMI welding tools do not recharge for free. You slap it against a welding tank to refill, like a normal welder. I was thinking that it would be refueled like a normal solder: you take a container of sulfuric acid and slap it against the iron. I assumed it would be possible in MoMMIs since I can refill one that way when it is in my toolbelt as a carbon.

> Crabs were never intended to come with a soldering iron

Why is that? They have every other tool short of a RCD (at least station ones do). It does not seem like it would be unreasonable or game-breaking to give them that tool.

**Comment by Kurfursten** [comment]
Because I added them shortly after crabs got new ventcrawling and people were pointing out how MoMMI is engineer++ and able to fix most shit before engineers can even reach the scene. Engiborgs have the niche of their powerful RCD which makes them inarguably the best at fast breach patching, MoMMIs can get to the scene first with vents, humans get the solder to handle the fine machinery.

**Comment by churchtummy** [comment]
I do not think that is much of a niche. The solder is not exclusive to humans; a MoMMI can just grab one from a vendor/autolathe and carry it with them. The RCD is an actual niche since the only one available to carbons is in the CE's locker (correct me if I am wrong about this). It does not seem like granting MoMMIs a solder will make engineers any more/less useful.

**Comment by Kurfursten** [comment]
Exactly, they can just carry it, so they don't need one built in. Don't pamper the crabs.

**Comment by churchtummy** [comment]
The same could be said about a silicate sprayer or the fire extinguisher but both of these are there. I would just prefer to not have to juggle a tool that has as much reason to be a part of the inventory as any other one.

**Comment by Eneocho** [comment]
> 
> The RCD is an actual niche since the only one available to carbons is in the CE's locker (correct me if I am wrong about this). 

You can make more from hacked autolathes, but it is (relatively) expensive.

**Comment by west3436** [comment]
Implementation rejected in #29769
