### ISSUE TITLE
Cyberhorrors are way too tame.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29765]
I've made a "Cyberhorror treatment center" on a few rounds. Quite literally a cyberhorror trapped inside a plastic flap cuck cube so if you're injured, you can crawl into the cuck cube and be forcefully injected mednanos. The idea was a high risk high reward kind of facility that could cause problems if not careful.
The problem is that the cyberhorrors are very tame, uncannily so. To the point you have to both hit them and move them around (either by swapping places or by dragging) for them to notice you and attack. They are supposed to be very dangerous and bloodthirsty simplemobs, but they barely do shit unless actively taunting them.
I think it's a side effect of the hostilemob AI change #29429, but I could be wrong.

**Comment by GreatBigFailure** [comment]
I remember that round. I hadn't considered the hostile mob AI change. 
I remember I crawled onto the same tile as the horror and it didn't attack me, but maybe it was distracted by someone else. I assume the flaps caused weird interactions though, ya. Later in the round I saw multiple horrors with evidence that someone had gotten turned in the enclosure and let them inject me. It worked then, and if I remember right I wasn't on the flaps.

**Comment by Killette3** [comment]
Are you sure they didn't have their sights locked on something else like a player or object that wasn't the player entering the cage?

**Comment by Eneocho** [comment]
>Later in the round I saw multiple horrors with evidence that someone had gotten turned in the enclosure and let them inject me. It worked then, and if I remember right I wasn't on the flaps.

The only people that got turned were monkeymen that I personally fed with 20u mednanos. Or are you referring to the packedstation one? Because in that round the CE (I think it was the CE) used the horrors to suicide.

>Are you sure they didn't have their sights locked on something else like a player or object that wasn't the player entering the cage?

If we assume that to be the case, the 4 second timer from the hostilemob change would make them switch to another target, but more often than not it just stands there, not even making their "KR@!!N" scream.
