### ISSUE TITLE
Cannot repair burn damage to a cyborg power cell via cable coil

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#2977]
You have to remove the cell, screwdriver to expose wires then use cable coil to fix burn damage to cyborgs. You cannot put the cell in with wires exposed and with it out you cannot repair it via cable coil. This means nanopaste is the only way to repair critically burned cells as even if you put in a non-broken component it needs to be repaired.

**Comment by d3athrow** [comment]
You need to explain a bit better
>have to remove cell to do X
>can't do X unles it has a cell in it

?

**Comment by SarahJohnson489** [comment]
Alright so you analyze your friendly cyborg. It has 300 burn damage from being cap lasered to death

Readout has all the components at broken component levels of burn damage.

Cyborg burn damage was originally fixed by:
Swipe Id to unlock cover
Crowbar cover open
Open hand to remove cell
Screwdriver to expose wires
Apply cable coil to repair burn damage to components
Cyborg power cell is not in it so it is not a valid target for repair via cable coil

If the components were broke you just crowbarred them out, replaced them, then repaired the damage. The problem with this, is that the component must be in for you to repair it. And you cannot repair burn damage to a power cell as it must be removed to repair cyborg burn damage with cable coil. Putting in an "undamaged" power cell doesn't remove the damage to the "power cell" var stored in the cyborgs variables. This means it cannot function as it needs its cell for modules and whatnot. The existing workaround is that you can use nanopaste or crowbar the mmi out and put it in a fresh body.

I guess it's more of a 2-part bug really.

New, undamaged components do not replace/"fix" the damage of the the broken component you replaced. So say the armor plating took 60 damage, broke, and you replaced it with a newly printed one. There's still 60 damage but now you can repair that 60 damage.

And that the repair cyborg burn damage via cable coil steps do not work for damaged/broken/replaced cyborg power cells.

**Comment by SarahJohnson489** [comment]
So I guess I'd suggest moving the wire to repair req to just an open cover. Then you can still repair the power cells without having to destroy and reconstruct an entire cyborg just because the power cell was destroyed.

**Comment by Cisrox** [comment]
Its. Fixed. Closeable.

**Comment by PJB3005** [comment]
With @Cisrox' recent "close this" spree I'm gonna need somebody else's word about if this is fixed first.

**Comment by Cisrox** [comment]
I personally have gutted a lasered out borg and fixed all of its components, it's fixed.
