### ISSUE TITLE
The delivery chute in cargo bay does not work unless a mob enters it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29785]
(WEB REPORT BY: gallywix4 REMOTE: 206.221.180.138:7777)
# Revision
3adc40ed4765fb67cc144be455884c88d0063474

# Description
If an item enters the delivery chute it won't start the countdown for the delivery (i only tested with the one in cargo)
# Steps to Reproduce
Throw a item in the conveyor belt and then turn it on
# What you Expected
It was expected for the delivery chute to activate after a few seconds
# What Actually Happened
nothing

**Comment by Killette3** [comment]
I've had similar problems the last week or two. Delivery is weird as fuck right now but this issue doesn't seem consistent either

**Comment by DeityLink** [comment]
I've seen it happen several rounds over the past few weeks. On box specifically. I remember varediting the chute and it appeared to be...off? Despite those not being on/off toggle-able. I'm really not sure what would cause that.
