### ISSUE TITLE
Things getting deleted 4noreason

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#2978]
Things you print out from fabricators, glass windows you add to grilles, mommi cells when they move into chargers, computer and machine frames, wires you put down. This kind of stuff only happens when you first do it, sometimes they get deleted sometimes they don't. I don't know how to reproduce this problem.

**Comment by MusgardTiger** [comment]
Nevermind that mommi cell problem. It is probably unrelated to this, I'll make a new ticket for it.

**Comment by PJB3005** [comment]
yep, loads of shit being deleted, even airlock assemblies, seems to effect specific tiles and only a couple times, weirdly

**Comment by Probe1** [comment]
oh god so it wasn't just me?  I built 6 apc frames during that round earlier when HoP office got bombed and 4 of them magically disappeared.  It was driving me NUTS.

**Comment by d3athrow** [comment]
This should be fixed.

**Comment by MusgardTiger** [comment]
Aight, things aren't getting deleted randomly anymore. Godbless.
