### ISSUE TITLE
Arcane Golems play the 3 stooges with you

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#29797]
If you use the wizard spell "Cast Fist" while an arcane golem is summoned, your fist spell can target your golems and your golems fist spell can target you

**Comment by Dacendeth** [comment]
Arcane golems have so many bugs, just remove them.

**Comment by ghost** [comment]
This is called "emergent gameplay".

**Comment by jwhitak** [comment]
Slap this on with pain mirror and watch funny mans gib all around you

**Comment by Eneocho** [comment]
Feature.

**Comment by Killette3** [comment]
> Slap this on with pain mirror and watch funny mans gib all around you

I just tested this with another person (so a target with a ckey) and it did next to nothing. Doesn't actually function like you'd think, fist doesn't get pain mirrored and target just gets 1 fist it seems

**Comment by DeityLink** [comment]
Duplicate of #29366
