### ISSUE TITLE
Derelict MoMMIS start without a cell

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#2979]
Two MoMMIS spawned without a cell, then I tried it myself and spawned with a cell. I don't know whatsup.

**Comment by PJB3005** [comment]
yep, something's up, my cell dissapeared out of the blue an hour or so ago

**Comment by ririchiyo** [comment]
This should have been fixed by now with changes to the garbage collector that had happened here if it occurs again, reopen this.
