### ISSUE TITLE
Cyborg Challenger Doesn't Work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29794]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
00b30133b69a752532a139cc645c270700690eb5

# Description
Cyborg spawned as my Challenger target. Took a photo of his brain in an MMI, posted it in a news feed, and was awarded no TC.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
Brain inside an MMI isn't equal to brain. It was "conscious". Oversight.

**Comment by west3436** [comment]
> Brain inside an MMI isn't equal to brain. It was "conscious". Oversight.

Fine - that should be made clear to the challenger then (and also requires them to purchase an emag to get them out of the MMI).

**Comment by DeityLink** [comment]
Cyborgs shouldn't be able to roll Challenger to begin with.
