### ISSUE TITLE
Boxstation's Vox Outpost Dormitories are named "Dormatories"

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29807]
Dormatories or something along those lines.

**Comment by Kharkov72** [comment]
vox no write good yaya

**Comment by Eneocho** [comment]
the vox space gypsie metaclub has gone too far

**Comment by DeityLink** [comment]
At this point I'd say it's a staple 
![image](https://user-images.githubusercontent.com/7573912/122300765-0e316580-cf00-11eb-8a33-4ed3df8dc872.png)
