### ISSUE TITLE
[Bug] EX Grenades and Large grenades are broken

### ISSUE THREAD

**Issue by GrandCanada** [d3athrow/vgstation13#2980]
Once primed, both EX and Large grenades do not activate.

**Comment by AutismSpider** [comment]
What did you use  for the grenade  timer+igniter?

They blow up fine with that after i made one.

**Comment by d3athrow** [comment]
Tested locally, large and ex grenades work fine.

**Comment by ComicIronic** [comment]
Closing this due to no further comments.
