### ISSUE TITLE
unloading machines not unloading boxes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29804]
(WEB REPORT BY: nottoomykins REMOTE: 206.221.180.138:7777)
# Revision
e624b2f422a981cd9aabce5367bc7e7ce048717f

# Description
unloading machines as seen on the roid no longer unload ore boxes, you have to unload the box and move it away from the machine for the ore to get picked up

**Comment by DeityLink** [comment]
Those old machines might need a slight rework by now. I'll see to it.
