### ISSUE TITLE
Extended can still fire by not executing any rulesets

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#29813]
Round lasted about a little more than an hour and a half and didn't net any antagonists despite plenty threat
![sextended](https://user-images.githubusercontent.com/51391726/122311390-b1ba5000-ced7-11eb-8563-19c0fe580bf9.PNG)

**Comment by DamianX** [comment]
But was it actually extended?

**Comment by DeityLink** [comment]
It wasn't, that was the "real" extended that Dynamic was designed to have occur naturally.

29 and 34% threat are not "plenty threat"

**Comment by Kurfursten** [comment]
>10 survivors, 4 ghosts

This is why. Most of the rulesets were void.

**Comment by ShiftyRail** [comment]
That's probably because nobody had antag roles on. 30 midround threat is enough to spawn 3 midround traitors.
