### ISSUE TITLE
[Box] Kitchen APC needs moved to the wall

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#2983]
![image](https://cloud.githubusercontent.com/assets/8550416/6197765/baf593ae-b3b9-11e4-8fa2-89a45d7d920c.png)

Calling @Rei1226

**Comment by Probe1** [comment]
In addition, Anonymous writes:  It would have a much better feel to switch the APC and the mirror in the bar backroom because a safe hidden behind a vending machine is good.  An apc is okay.  But a mirror is weird and stupid.  

![image](https://cloud.githubusercontent.com/assets/8550416/6197798/5fd0cc4a-b3ba-11e4-9707-70e81b6afefe.png)

**Comment by Yakk** [comment]
On another related note the windoor leading to the kitchen is not accessible by the chef.

**Comment by clusterfack** [comment]
In addition the scrubber shown in probe's second picture is turned off. You want scrubbers turned on at roundstart.

**Comment by IratePirate** [comment]
Rei APCs use the .dir var.

Please test all major Box changes before making a pull request in future.

**Comment by d3athrow** [comment]
this was fixed i believe?

**Comment by Probe1** [comment]
Fixed in https://github.com/d3athrow/vgstation13/pull/3042

reference issues you reiSlut
