### ISSUE TITLE
Stuff entered the cargo bay delivery chute while the windoor was closed.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29837]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
7b754492507e8178d9473d96f1960ab6018e1126

# Description
Title.
# Steps to Reproduce
Place stuff on the conveyor, without a crate.
Activate the conveyor.
See the stuff use quantum mechanics to instantly go through the closed window.
# What you Expected
Stuff to get trapped behind the window.
# What Actually Happened
Magic.

I assume it's cause of deity's recent delivery fix #29788.

**Comment by DeityLink** [comment]
It's not because of my PR, but I see the problem. Probably the lack of an adjacency check.
