### ISSUE TITLE
Shrunken vampire head doesnt detect cult runes.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#29836]
The shrunken head glows when it detects blood nearby, however it doesn't glow when cult runes are nearby even though they are made out of blood.

**Comment by DeityLink** [comment]
eldritch blood makes vampires sick, they hate it.

**Comment by Brotanics** [comment]
> eldritch blood makes vampires sick, they hate it.

Vampires commenting about a gross eldritch taste when they succ cultists when??

**Comment by drawsstuff** [comment]
> eldritch blood makes vampires sick, they hate it.

i refuse to believe this is the case until you add literal flavor text for vampires.
