### ISSUE TITLE
Conveyors go invisible when used

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#29844]
![boxconveyor](https://user-images.githubusercontent.com/51391726/122662324-b0975600-d157-11eb-970a-7160a0cdefe5.PNG)
Tested on a new test server on Box Station. The icon state for the conveyors was "conveyor-1". Conveyors with the icon state "conveyor1" worked just fine but animated moving to the right.

**Comment by DeityLink** [comment]
Fixed by #29847
