### ISSUE TITLE
Particle accelerator waves don't travel

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#2985]
Seems to only happen on this map. The acceleration waves generated don't travel from PA to beacon.

**Comment by Probe1** [comment]
might be tied to https://github.com/d3athrow/vgstation13/commit/d4d6f5b32ba272ab9ff1aecdfb0eab0738d02119

**Comment by clusterfack** [comment]
Fixed by https://github.com/d3athrow/vgstation13/commit/8cd30912aa5af13c1d9d09cc2d117c7beaa8b66a
