### ISSUE TITLE
Challenger can spawn alone

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29865]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
dba1ca7b0eba9c8852c659e40a3739a8135b54d0

# Description
Challenger spawns alone with no target on lowpop
# Steps to Reproduce
* Get on lowpop
* Roll challenger
# What you Expected
Someone else to roll it too
# What Actually Happened
One person

**Comment by SonixApache** [comment]
i recently found out we have a label just for these kinds of issues [ My Target's Issue]
