### ISSUE TITLE
Health Analyzers telling you how long ago someone died when scanning their corpse

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#29868]
yeah that feels like it should be a thing

**Comment by Kurfursten** [comment]
This is the main point of an autopsy

**Comment by Eneocho** [comment]
Do people ever do autopsies aside from the very, very rare occasion when someone does one for a trial?

**Comment by DeityLink** [comment]
> Do people ever do autopsies aside from the very, very rare occasion when someone does one for a trial?

> This is the main point of an autopsy

I do those out of curiosity to know how someone died, sometimes to make a newscaster article about it. Usually when they're unclonable.

I don't think anyone ever did an autopsy to figure how long ago someone died, generally it's as Eneocho said.

When I actually want to know how long ago someone died it's because I found their corpse somewhere and want to see the odds of them still being around to clone or defib them. And autopsy can only be done from a very single spot of the map, and doing an autopsy generally isn't something you do on a body you intend to clone.

**Comment by Kurfursten** [comment]
Just cut out the middleman then and instead have it say if there's a soul present. The health analyzer already does this with heads.

**Comment by Dacendeth** [comment]
Uh this is already a thing, and a health analyzer also tells you if they're still playing or not on corpses as well.

![image](https://user-images.githubusercontent.com/26881007/123003961-f3d50d00-d381-11eb-8837-c2f6b8b9d22b.png)

**Comment by Kurfursten** [comment]
Guess we're all blind
