### ISSUE TITLE
Bloody hands / gloves continue to unbloody with no washing and other oddities

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29875]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
815d2cfa9ced83ae57b9622fcc5f71cb621b2799

# Description
Punching people who are bleeding on a limb that is currently bleeding does not splash blood on your hands, putting blood on your hands through means of surgery will have the blood washed away seemingly at random. 

This makes writing in blood impossible.

Other odd behavoir includes the fact that you can be standing next to a pile of blood as a human but not be able to use to draw.

**Comment by DeityLink** [comment]
The blood goes away when you pick up an item, it transfers to it. It already worked like that, the blood just didn't disappear from the gloves as it should , now it's more obvious. I can increase the amounts of items you can bloody though, so you might less lose your bloody hands accidentally.

The punching bleeding limbs though might require some more testing.

**Comment by Eneocho** [comment]
>stab myself on the hand
>hand and gloves get bloody
>can't write with blood
>can't use the floor blood to write
>take off the gloves
>still can't write with the bleeding hand
