### ISSUE TITLE
Cant use a fork as a ghetto retractor for eye surgery

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#29876]
#### Description of issue
The only other tool besides the retractor for eye surgery is a fork, but attempting to use a fork, even on help intent stabs them in the eyes instead.

#### Difference between expected and actual behavior
For a ghetto tool to work as a surgery tool while the target is on a table
Got Eye Stabbing

#### Steps to reproduce
Target eyes, scalpel surgery the eyes, attempt to fork as the next step.

#### Specific information for locating

This is where it shows it should work.
https://github.com/vgstation-coders/vgstation13/blob/1ce25ff1b797f3a22ed9af5a5628ca61270dc4cf/code/modules/surgery/eye.dm#L67

#### Length of time in which bug has been known to occur

Dunno.

**Comment by DeityLink** [comment]
Probably since forever.
