### ISSUE TITLE
Space Hobo spawn doesn't overwrite the meteor properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29903]
(WEB REPORT BY: buttbot REMOTE: 206.221.180.138:7777)
# Revision
a4aa17bedc684db3c6f8338c1bff951e2d9ee215

# Description
https://i.imgur.com/nXlV9Jv.png
Whatever ore was in the meteor gets dropped and blocks in the spawn if it's a solid structure.
# Steps to Reproduce
Get an unlucky spawn with the meteor turf that gets spawned over having giant crystals
# What you Expected
Hobo vault clearing out all terrain
# What Actually Happened
Crystals, yo

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/123450929-84f3f000-d5dd-11eb-85e4-47feabb9b8de.png)

**Comment by DeityLink** [comment]
It's a geode, not a meteor.

**Comment by DeityLink** [comment]
also @beesil

**Comment by DeityLink** [comment]
or maybe @kane-f rather

**Comment by Eneocho** [comment]
> 
> 
> It's a geode, not a meteor.

![geodemeteor](https://user-images.githubusercontent.com/67024428/123487573-2bd78c80-d5dc-11eb-8705-bb43d3a59595.jpg)

**Comment by ghost** [comment]
I think area population code should be updated to check other vaults or something
