### ISSUE TITLE
[Feature Request] Eggs vomited while wearing the pomfsuit are pomfeggs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29904]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
Vomited eggs while wearing the pomfsuit and they were not pomfeggs, literally unplayable.[featurerequest]

**Comment by DeityLink** [comment]
no

**Comment by Eneocho** [comment]
evil c*derman
