### ISSUE TITLE
Taking a picture of your target's head as a challenger gives you no TC

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29917]
(WEB REPORT BY: xeroxemnas REMOTE: 206.221.180.138:7777)
# Revision
55d94b96bde1a2189d8a8a6cf35d70fb7f7feb22

# Steps to Reproduce
>kill target
>decapitate
>take picture of head
>upload picture to public newscaster channel
>get congratulations message and greentext, no extra TC

**Comment by DeityLink** [comment]
Because they had already spent all their TCs, duh?

If you got the congratulations message and not TCs then that's what happened.
