### ISSUE TITLE
Glass airlocks con/decon

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#2991]
It'd be nice to have these buildable and constructable, basically my way to go at this would be:
-new wide airlock frame in the metal building list
-the procedure to build it should require glass, not optional

Right now the decon stops at the "removing electronics" part, and that doesn't even return the electronics board, nor does it make the airlock non-functional: it'll still work.

It's also missing sprites past the screwdrivers ones, which I'm willing to make.

edit. seems like construction sprites are already in: door_assembly2x1.dmi

**Comment by ihadtoregisterforthis** [comment]
Look at that, a feature request that got fulfilled
