### ISSUE TITLE
Forge does not generate light

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29929]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
55d94b96bde1a2189d8a8a6cf35d70fb7f7feb22

# Description
The forge does not count as a light source when lit... very violation of immulsions my dudes...
# Steps to Reproduce
Make forge, light
# What you Expected
Cool firey effects
# What Actually Happened
No light

**Comment by Eneocho** [comment]
I'd also leave a comment about this on the europalights PR, since we're changing light engine soon(TM).

**Comment by ghost** [comment]
I'll fix this when my other forge stuff gets merged.

**Comment by Securitymain** [comment]
![grafik](https://github.com/vgstation-coders/vgstation13/assets/132118542/349b92bb-85ed-4f60-9d1d-536d90157c75)
must have been fixed at some point @Kurfursten
