### ISSUE TITLE
adding goliath plates to mining rigsuit breaks helmet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29921]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
55d94b96bde1a2189d8a8a6cf35d70fb7f7feb22

# Description
helmet won't turn on
# Steps to Reproduce
kill goaliath
take off my suit, reinforce it
put it on
turn helmet on
no helmet
# What you Expected
helmet
# What Actually Happened
no helmet

**Comment by xeroxemnas** [comment]
You know you dont actually have to take the suit off anymore, right?

**Comment by nervere** [comment]
Mining suits have since been reworked and I can't reproduce this.
