### ISSUE TITLE
All Space Hobos are called Unknown

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29924]
(WEB REPORT BY: sootybear42 REMOTE: 206.221.180.138:7777)
# Revision
55d94b96bde1a2189d8a8a6cf35d70fb7f7feb22

# Description

# Steps to Reproduce

# What you Expected
To have a random or custom name
# What Actually Happened
For my name to literally be unknown

**Comment by SootyBear42** [comment]
Messed it up sorry

Description: All Space Hobos seem to be called Unknown
 Steps to Reproduce: Be a space hobo

**Comment by jknpj** [comment]
accurate
