### ISSUE TITLE
Science Goggles (PathogenHUD) Can't be Stored in Pockets Anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29928]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
55d94b96bde1a2189d8a8a6cf35d70fb7f7feb22

# Description
I swear it wasn't always like this.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Dacendeth** [comment]
the pr that made them fit over eyeglasses broke this, same thing happens with mesons.
