### ISSUE TITLE
clothes get seperated from people in photos

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29934]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
baafa0cc5036e5288fad2f10815b43580d289dff

it sucks

**Comment by gurfan** [comment]
@DeityLink

**Comment by DeityLink** [comment]
AHHHHHHHHH

**Comment by DeityLink** [comment]
@gurfan works on my machine 
![image](https://user-images.githubusercontent.com/7573912/123945081-0fea3700-d99e-11eb-82d5-ae276fbe7bd4.png)

Do you have a screenshot at least?

**Comment by gurfan** [comment]
I forgot to take my own screenshot but it's exactly like this screenshot you posted before 
![unknown-4](https://user-images.githubusercontent.com/51427771/123987466-d4933c80-d98c-11eb-8dca-a99694fd39dd.png)
Anyone that was moving had their clothes displaced

**Comment by DeityLink** [comment]
Oh right, 

I'll fix that later. In the meantime, tell people to stand still to avoid blurry pictures :^)
