### ISSUE TITLE
Gibbed players can't become space hobos

### ISSUE THREAD

**Issue by Apogee-dev** [d3athrow/vgstation13#29946]
#### Description of issue
Space hobo button rejects gibbed players, presumably because they don't have a body to return to and therefore it thinks they're observers.

#### What you expected
be space hobo

#### What actually happened
You must have had presence on this plane to become this.

#### Steps to reproduce
1. get fed to duck or singulo or gibber or etc
2. press hobo button
3. don't be hobo

**Comment by ghost** [comment]
Intentional (t. guy who coded them)
