### ISSUE TITLE
Mass paint on the RPD excludes pipe endcaps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29948]
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
baafa0cc5036e5288fad2f10815b43580d289dff

# Description
Painting a pipe network that includes endcaps paints all but the endcaps normally, leaving the pipes painted, but the endcaps unpainted.
# Steps to Reproduce
Place some pipes, connect with endcaps on an end.
Paint with the mass paint setting on the RPD set to 'On' and paint one of the pipes.
# What you Expected
All of the pipes in the network to be painted
# What Actually Happened
The endcaps were not painted for some reason.

**Comment by DeityLink** [comment]
Fun fact, code-wise endcaps are not pipes. They're unary devices like vents and scrubbers. And they do nothing.
