### ISSUE TITLE
AI crew member hologram doesn't work properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29942]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
baafa0cc5036e5288fad2f10815b43580d289dff

# Description
Crew member hologram is naked bald human
# Steps to Reproduce
become AI somehow, click "Change hologram", then "crew member"
# What you Expected
hologram that looks like a crew member
# What Actually Happened
roundstart people holograms are naked bald men, latejoiners are bald men with clothes that don't match or turn with them

**Comment by SonixApache** [comment]
#21492
