### ISSUE TITLE
Emitter beams are barely visible, completely invisible in space tile.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29957]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
0f05e7a5f5225ae9881e3dc7e09bce65ea873e08

# Description
Title
# Steps to Reproduce
Try to see an emitter beam
# What you Expected
Easy to see
# What Actually Happened
Almost invisible

**Comment by DeityLink** [comment]
So I think I broke everything that was on the light plane, and to be fair there should never have been anything other than the lighting_overlays in there. At least that should be an easy fix.
