### ISSUE TITLE
Rolled wizard 3x as a single wizard

### ISSUE THREAD

**Issue by west3436** [d3athrow/vgstation13#29950]
#### Description of issue
I started with 3 spellbooks and 3x the absorb spell. I had lots of fun!

![image](https://user-images.githubusercontent.com/66280799/124370290-f3b2f800-dc32-11eb-9b76-b8b9d5235d01.png)
This is fun! The crew had lots of fun!

[<roleissue>]

**Comment by west3436** [comment]
![2](https://user-images.githubusercontent.com/66280799/124370393-5b1d7780-dc34-11eb-8093-e2016ad3b01d.PNG)

**Comment by Exxion** [comment]
The roll of legend...

**Comment by Killette3** [comment]
Lmao nice build

**Comment by Exxion** [comment]
Wait I just noticed that you were on both teams

**Comment by Eneocho** [comment]
> 
> 
> Wait I just noticed that you were on both teams

https://www.youtube.com/watch?v=_BlyYs_Tkno
