### ISSUE TITLE
Wall mounted hooks are invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29956]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
0f05e7a5f5225ae9881e3dc7e09bce65ea873e08

# Description
wall mounted hooks are only visible if you turn mesons on
# Steps to Reproduce
turn mesons on
see wall hook with lantern
turn mesons off
no hook
# What you Expected
hook and lantern visible always
# What Actually Happened
hook and lantern only visible in mesons wavelength

**Comment by assmops** [comment]
They show up with darkness off, and at centcomm, I have no clue how that works
![44](https://user-images.githubusercontent.com/45994070/124392243-7767f580-dcc2-11eb-8d53-aa4868037b0c.PNG)
![45](https://user-images.githubusercontent.com/45994070/124392244-78008c00-dcc2-11eb-8437-047b3bc8dc37.PNG)
![789](https://user-images.githubusercontent.com/45994070/124392245-78008c00-dcc2-11eb-9323-4e25f58165ac.PNG)

**Comment by Exxion** [comment]
Something something planes maybe

**Comment by DeityLink** [comment]
Yep, because for some ungodly reason some light objects are on the LIGHTING_PLANE. I changed it for regular light tubes/bulbs but forgot the lanterns. I'll fix it tonight.
