### ISSUE TITLE
[Bug] Wizards magic miss spell occasionally gets stuck and creates a AOE massive damage ward.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#2996]
Seen this happen twice.
Wizard will cast magic missle
It gets stuck so far only around fire doors?
When stuck there the projectile will stick there
Anyone who gets within one tile of it takes a billion burn damage instantly killing them

**Comment by frangi** [comment]
Had this happen to me a couple of days ago, too.

Was waiting by the HoP line on meta, wizard from the hall casted MM and the whole line insta-died.
