### ISSUE TITLE
Gingerfat man and zombie from syndie trainer belt still attack its owner

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#29975]
(WEB REPORT BY: fred104 REMOTE: 206.221.180.138:7777)
# Revision
23f89fb02d9d48e121bc8a3de5e44a27a0df61ed

# Description
Gingerfat man and zombie from syndie trainer belt still attack its owner
# Steps to Reproduce
get a ginger fat man and zombie from trainer belt of syndie uplink
# What you Expected
NOT getting mauled by my pet
# What Actually Happened
get mauled by MY pet

**Comment by DeityLink** [comment]
All the mobs were in fact hostile.

Their faction was `"lazarus [0x0]"`, their friends list had a null entry.

**Comment by DeityLink** [comment]
Looking at the code seems like it never actually worked before ever since the uplink item spawn code never gave the agent as arg.
