### ISSUE TITLE
Ghost and the Atmospherics Automations Console

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#2997]
Ghost can fuck with the Atmospherics Automations Console turning stuff on and off fucking with the many setting for Scrubber etc if its set up on it.

**Comment by d3athrow** [comment]
Tested this and can't reproduce as a non admin ghost.
![dicks](http://puu.sh/fVnYz/86a7b3086c.png)

**Comment by AutismSpider** [comment]
Odd i was able to turn off and play with the Scrubber gas setting etc  and  air injector inject rate as a ghost.

**Comment by d3athrow** [comment]
Was it the prebuilt one in the supermatter room or one you made with your own board

**Comment by AutismSpider** [comment]
prebuilt one in the super matter room

**Comment by Boxe** [comment]
dedmin'd and tested on metastation, ghosts can dick with the 'set power to off' spots and shit

**Comment by AutismSpider** [comment]
When it happen it was on Box though.
![setting i am using](https://cloud.githubusercontent.com/assets/10268342/6201527/22f4859e-b475-11e4-8781-f257a4fe798d.PNG)

A Ghost can play with this some how but not full on scripts.

**Comment by d3athrow** [comment]
Found out the issue.
