### ISSUE TITLE
Radstorm Radiation is NOT harvestable.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#29989]
Literally unplayable. How am I supposed to make the rare and mostly useless Radstorm Engine now. [consistency]

**Comment by ghost** [comment]
radstorms are snowflaked in general it seems

**Comment by Killette2** [comment]
They're too stormy to harvest

**Comment by DeityLink** [comment]
I'll argue that supermatter and singulos are pretty extreme too.
