### ISSUE TITLE
The photo booth circuit is a lie

### ISSUE THREAD

**Issue by StreptoMutans** [d3athrow/vgstation13#29995]
#### Description of issue
The "Photo Booth" circuit is listed under "Console Boards". Upon choosing the option, you get a teleporter console board instead.

#### Difference between expected and actual behavior

Wanted photos, but even the R&D console doesn't want more pictures of spessmen to exist

#### Specific information for locating
https://github.com/vgstation-coders/vgstation13/blob/ab654bb0d6c9a297dc348fc147bd9fc44330fb22/code/modules/research/designs/boards/machine_misc.dm
#29965 

#### Server revision
95c9b70436e6e91460df7e3784f370fd72b5462f 

[bugfix]

**Comment by DeityLink** [comment]
oops
