### ISSUE TITLE
Wizards cannot cast spells when stunned (most of the time)

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#2999]
rip several wizards who were unaware
I was unable to cast anything when I got tased or stunned by beepsky and heard complaints from other wizards about the same but only just now saw another wizard spamming magic missile fine when he was floored.

**Comment by d3athrow** [comment]
I can't reproduce, tried being stunned, weakened, stuttering, slurred, anything that modifies your speech.

**Comment by Konater** [comment]
What spells did you try? I recall trying magic missile/flesh to stone/blink/jaunt and getting nothing from it

**Comment by d3athrow** [comment]
MM, jaunt, fireball.
