### ISSUE TITLE
NOIR AIN'T RED

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30002]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
6085d3a81dfd045e69f4eb62b50421adfb3183c9

# Description
NOIR BLOOD AIN'T RED
# Steps to Reproduce
LOOK AT BLOOD 

# What you Expected
IT RED 
# What Actually Happened

IT BLACK

**Comment by DeityLink** [comment]
That means it's either viral sputum or dumb vox/diona/etc non-human blood 
![image](https://user-images.githubusercontent.com/7573912/125614130-8a822f05-659a-4e11-b308-29d4651229c9.png)
