### ISSUE TITLE
Newcaster Destroy Photos when Disassembled

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30007]
(WEB REPORT BY: exabod1 REMOTE: 206.221.180.138:7777)
# Revision
d430c433c67671e56aef97dee54696ab2c6665af

# Description
Newcaster deletes photos when disassembled, happened on a challanger round.
# Steps to Reproduce
As said above.
# What you Expected
Photo not deleted
# What Actually Happened
Photo got deleted >:[

**Comment by DeityLink** [comment]
This one is such an easy fix that I'm leaving it open to allow our newbie coders to train code diving and using git.

**Comment by ghost** [comment]
> This one is such an easy fix that I'm leaving it open to allow our newbie coders to train code diving and using git.

nuh uh, muh bugvalids
