### ISSUE TITLE
[Box/reiBar] Service ID access issues

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3003]
Botanists, Chefs and Bartenders need each others access to improve cooperation and functionality in the service department.  When one job isn't filled it can cause issues for all jobs.  Previously, and on Deff/Meta, botanist/hydroponist/chef/cook/bartender all started with access.  

Please give the access back.

**Comment by CptWad** [comment]
I would be ok with this if instead the backrooms required the jobs specific access but a universal access for hydro/bar/kitchen that allows going through the rooms.

**Comment by Probe1** [comment]
It wasn't important a few days ago before reibar was merged or important on any other map.  

It's more of a pain in the ass than benefit.

**Comment by Rei1226** [comment]
Uhh..I might be wrong but I'm pretty sure the three jobs never had cross-access to eachother's rooms.

**Comment by Probe1** [comment]
it's been that way for a long time.

**Comment by Rei1226** [comment]
Are you certain? Try going into botany as a chef/bartender. If you're able to then I suppose it was always that way, but if you aren't then it must not have been, since I never even touched botany doors.

**Comment by Probe1** [comment]
Yes, you can verify that yourself on the test server right now it's running the old bar.

**Comment by Probe1** [comment]
closed here https://github.com/d3athrow/vgstation13/pull/3042
