### ISSUE TITLE
Skrellington simplemob has skin you can butcher

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30032]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
a8c2447dc9bd10c96de4e3b6107c8b8728038ee2

# Description
title
# Steps to Reproduce
spawn a skrellington (in this case, via blood moon)
kill it
butcher the skin
# What you Expected
skeletons with no skin
# What Actually Happened
immulsions damaged and skeleton leather (?)

**Comment by DeityLink** [comment]
First of all you mean Skellingtons. Skrell are a race, and Skrellingtons do not exist.

Secondly,

```
/mob/living/simple_animal/hostile/humanoid/skellington
    name = "skellington"
    desc = "A skeleton, held together by scraps of skin and muscle. It appears to be feral."
```

So yeah, it's supposed to have a bit of skin.
