### ISSUE TITLE
xenoarch job spawns without a jumpsuit or ID

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#30037]
also the preferences menu has an extra, mostly-empty column

**Comment by gurfan** [comment]
related to #30009 obviously

**Comment by Apogee-dev** [comment]
Worked fine in testing. Were you playing as a nonhuman species when this happened?

**Comment by dackjaniels69** [comment]
I don't see an issue here

**Comment by Brotanics** [comment]
Feature.

**Comment by Apogee-dev** [comment]
Nevermind, found the issue.

**Comment by DeityLink** [comment]
Assuming fixed by #30038
