### ISSUE TITLE
[Bug] Unable to calm bees and unable to catch bees with nets

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3004]
I tried for almost an hour to get them in a damn net and it did not work.  I used the net, I attacked with the net, I prayed to the net, nothing.  I tried smoking the bees by combining beakers of potassium sugar and phosphorous, I tried using a fire extinguisher, I tried using an empty spray bottle with water.  I did all that directly targeting the bees and targeting the tile they were on.  None of that calmed them down.

So I think something is bugged.  BEEEES.

**Comment by Killette2** [comment]
Rowan the botany nerd here, you just have to spray the bees with a fire extinguisher and hit them with 100% of the spray, the same way to instakill slimes. A lot. You will need to refill around 3 or more times depends on how many bees and how angry they are. Do not piss bees off.

**Comment by Probe1** [comment]
Do you think it needs to be improved @Killette2 or am I being a scrub?  

I honestly do not think it's reasonable but you know your shit.

**Comment by Killette2** [comment]
Well the bees strength depends on how many bees there are. If you farmed a fuckton of bees, say 100, then yea it's going to be a pain in the ass calming them. But if you coworker fucks up early and harvest when there's only around 20 bees, then you should be able to calm them in about 20 sprays. Bees can be used as a powerful weapon for traitor botanist so nerfing them seems a bit silly.
