### ISSUE TITLE
Boxstation's Xenobio Cage 6's APC isn't wired to the grid.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30052]
The last one at the right, the one with the blast doors to space.

**Comment by DeityLink** [comment]
Unable to reproduce, it must have been disconnected by a player on one round in particular 
![image](https://user-images.githubusercontent.com/7573912/126457382-cc51ba38-f5af-400c-9b67-eb6e4e9b88b3.png)

**Comment by Eneocho** [comment]
I checked it after on localhost and that one cable was still missing. Weird.
