### ISSUE TITLE
TC Dupe glitch

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30066]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
0b935e3413c11d8b45274b8c65a1ae37298b7e13

# Description
Get station bounced radio uplink
Extract TC
Put TC back in.
Somehow you put it back twice.
TC duped.
# What you Expected
Extract 2 TC, put 2 TC back, uplink has 2 TC
# What Actually Happened
You withdraw 400 telecrystals from your uplink.

You insert 400 telecrystals into the uplink.x2

**Comment by jknpj** [comment]
Both /radio and /radio/uplink have the same .refund() and uplink calls the parent. Easy fix.
