### ISSUE TITLE
somethings fucked with robot arms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30065]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
0b935e3413c11d8b45274b8c65a1ae37298b7e13

# Description
robot arms broked but cannot be fixed and replacements are still broken for no
# Steps to Reproduce
get robo arms, emp them (try singu, that's what cucked mine), try to repair or replace
# What you Expected
arm fix
# What Actually Happened
why it no fix!!

**Comment by jknpj** [comment]
Tried nanopaste?

**Comment by DeityLink** [comment]
Brand new arms shouldn't be broken when surgically put on someone that had their previous arms broken.

**Comment by Dacendeth** [comment]
You probably forgot to multitool it to fix the EMP shutting the limb off, but swaping a new one on and having it still be broken is for sure a bug.
