### ISSUE TITLE
Character job prefs are FUCKED

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30076]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
5f61b9c3d78e50996b22c458711824dffdfead1c

# Description

Character job prefs are fucked. Upon saving a preference for one character, the same job prefs will mass apply to the rest. Trying to fix this by indivually redoing all my prefs has not worked because every time I set say, virology to high on my medical character, my mining character now suddenly has an interest in getting pozzered as well. fix he please

**Comment by drawsstuff** [comment]
![image](https://user-images.githubusercontent.com/16404218/126883699-0ca1aa7b-2b07-4594-8dfb-24b702eafbd5.png)

look at this jank
