### ISSUE TITLE
Sentient Ghouls can't be gene modified/scanned.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30084]
#### Description of issue
Sentient ghouls can't be gene edited/scanned, for better or worse.

#### Difference between expected and actual behavior
Expected to be able to inject genetic material to the ghouls but couldn't.

#### Steps to reproduce
Become ghoul, either by var-editing the species variable to ghoul or by doing the whole ghoulification process (I recommend you manually varedit the rad-tick to over 800 then manually varedit the radiation value to 100000000 or whatever, as long as it is higher than the radtick, for it to "naturally" ghoulify).
Try to inject ANY genetic sample from the xenoarch no-fail ones to any genetics lab one. You "inject" the sample _but it doesn't inject and drops to the floor, unused._

The gene syringes not injecting then forcedropping to the floor thing probably also extends to any situation where the NOCLONE flag gets raised.

#### Specific information for locating
Seems the M_NOCLONE mutation var added when irradiated doesn't get removed properly upon sentient ghoulification and as such you are unable to do anything gene related.

#### Length of time in which bug has been known to occur
Dunno, but probably since ghoulification was a thing.

[bugfix]

**Comment by Killette2** [comment]
Is it possible to skillfully stay out of gene destruction range during the ghoulification or is it RNG and pray

**Comment by Eneocho** [comment]
> 
> 
> Is it possible to skillfully stay out of gene destruction range during the ghoulification or is it RNG and pray

RNG and pray, but it's effectively impossible to stay out of the gene nuke range. The code calls for:
`if(rad_tick > RADDOSEADVANCED)`
		`if(prob(0.5*major_rad_multiplier))`
				`if(!(M_NOCLONE in mutations))`
					`to_chat(src, "<span class = 'blob'>You feel something twist and break.</span>")`
					`mutations |= M_NOCLONE`

Meaning your genes will get nuked way before you reach the ghoulification stage (RADDOSEFATAL). Even if you somehow manage to NOT get the gene nuke by keeping the radtick below rad dose, the chance is a multiplier based on radiation amount (the 0.5*mayor_rad_multiplier part), which means if you magically reached the ghoulification stage without the no-clone flag being set, you'd still get the noclone before the ghoulification, since both call for radtick > radlevel.

The only solution is to remove the noclone flag upon ghoulification.
