### ISSUE TITLE
Virus dishes have an area of annoying transparent pixels that click the object next behind it

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#30087]
In the area between the back of the top of the sprite and the virus clumps, there's a transparent area. Move your mouse around to see what I mean, may be different for every sprite

**Comment by DeityLink** [comment]
Don't you mean the disease analyzer that happens to have some overlay that appear above the dish? Because the dish themselves shouldn't have any transparent pixel 🤔

**Comment by DeityLink** [comment]
Due to the way lighting works the centrifuge's above-light overlays appear above the printed dish, and hinder clicking on it. The engine won't let you click on the dish through the light overlay, so the simplest solution is to offset the dish a bit when it spawns.
