### ISSUE TITLE
Enemy jobs check runtimes on late joins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30096]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
20c463986a1261f49a610d133321f8967f23ba33

# Description
[20:13:41] Runtime in dynamic_rulesets.dm, line 126: list index out of bounds
proc name: check enemy jobs (/datum/dynamic_ruleset/proc/check_enemy_jobs)
usr: [REDACTED] (/mob/new_player)
usr.loc: The floor (8, 95, 2) (/turf/unsimulated/floor)
src: Syndicate Infiltrator (/datum/dynamic_ruleset/latejoin/infiltrator)
call stack:
Syndicate Infiltrator (/datum/dynamic_ruleset/latejoin/infiltrator): check enemy jobs(1)
Syndicate Infiltrator (/datum/dynamic_ruleset/latejoin/infiltrator): ready(0)
Dynamic Mode (/datum/gamemode/dynamic): latespawn([REDACTED] (/mob/new_player))
[REDACTED] (/mob/new_player): AttemptLateSpawn([REDACTED])
[REDACTED] (/mob/new_player): Topic("src=\[0x30002e3];SelectedJob=B...", /list (/list))
Pulserider (/client): Topic("src=\[0x30002e3];SelectedJob=B...", /list (/list), [REDACTED] (/mob/new_player))
Pulserider (/client): Topic("src=\[0x30002e3];SelectedJob=B...", /list (/list), [REDACTED] (/mob/new_player))
# Steps to Reproduce
Have a latejoin rule fire successfully (or just infiltrators)
# What you Expected
Succesfully assigned
# What Actually Happened
Target is not antag

**Comment by ghost** [comment]
welp i forgot to redact everything
