### ISSUE TITLE
Advanced security cameras not accurate on SNAXI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30093]
(WEB REPORT BY: kahnn1 REMOTE: 206.221.180.138:7777)
# Revision
47c01796e762d2cc09d266df1f977d01cf206cd7

# Description
The advanced security camera console on snaxi is fugd. The ui has the cameras was out of actual position.
# Steps to Reproduce
use the console on snaxi
# What you Expected
Cameras to be in the actual position
# What Actually Happened
they arent

**Comment by Kurfursten** [comment]
Dupe of https://github.com/vgstation-coders/vgstation13/issues/26028

Dunno how to fix this. Apparently no one does.

**Comment by DeityLink** [comment]
Weren't those removed from most maps because they were bugged? Or were they fixed since?

**Comment by Kurfursten** [comment]
I believe they're roundstart removed but you can still build them

**Comment by DeityLink** [comment]
Duplicate of #26028
