### ISSUE TITLE
Camera on Taxi Engineering vault shows up on singularity camera net

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30128]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
87b7a43e2bb1e6886db885f212bddd9f96b451b3
[bugfix]
# Description
See title
# Steps to Reproduce
* Load map element 
* Pick taxi_engineering.dmm
* Access a singularity telescreen
# What you Expected
No camera access
# What Actually Happened
Camera access

**Comment by jknpj** [comment]
Probe said it\s a feature
