### ISSUE TITLE
[Goofchem] Dark matter pulls through firedoors

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#3014]
Honk

CC @iamgoofball

**Comment by Iamgoofball** [comment]
this is apparently a BYOND problem @ComicIronic

**Comment by ComicIronic** [comment]
What version of Byond is Test running on?

**Comment by Iamgoofball** [comment]
@ComicIronic @d3athrow this is fixed on the latest test server build, it can be closed
