### ISSUE TITLE
Radio Transmitter likes to turn itself off regardless of room temp

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30147]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
27c61b851146f75ef8e5437567891aa749b953be

After about 3-5~ minutes of use, the radio transmitter shuts itself off, seemingly from overheating. Once that happens though it'll keep shutting itself off whenever you try to turn on again, no matter how cold the room is.

**Comment by Dacendeth** [comment]
Not a bug, you need to solder it after it overheats, though I suppose a messaging saying so couldn't hurt.
