### ISSUE TITLE
[Goofchem] Robots can't use chem heaters

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#3015]
CC @iamgoofball

**Comment by AutismSpider** [comment]
Medborg/Mommi can not stick a beaker in the chem heaters

And this happens with Chlorine Trifluoride when use on cyborgs and mommis.
![it burns](https://cloud.githubusercontent.com/assets/10268342/6202451/e8674d66-b4b1-11e4-9f28-e7398299aa93.PNG)

need test other chems

**Comment by Iamgoofball** [comment]
@ComicIronic @d3athrow this is fixed on the latest test server build, it can be closed

this also includes the CLF3 effects on nonhumans, those have been fixed too
