### ISSUE TITLE
Can't disassemble EZ-bake fun ovens despite being able to make them with circuitry.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30151]
#### Description of issue
Title.
#### Difference between expected and actual behavior
Expected to be able to disassemble them. 
Got:
`You can't put that in Waffle Inc. Ez-bake FUN oven. `
`It's not edible food.`
#### Steps to reproduce
Try to use a screwdriver on the oven per standard machine disassembly.
Fail because it's not food.
#### Specific information for locating
#29899

Probably would need a whole rewriting of the cooking machines' code, since they all inherit from the ez-bake oven, but not all of them have circuitry.
[bugfix] [oversight]

**Comment by boy2mantwicethefam** [comment]
feature
