### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30166]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
41c4b1acd6f5d94a0534c72b2edf7207892bc714

# Description
This is the second time this has happened to me; if you ghost/shade the same moment that you are flashbanged/stun talisman'd then the viewport is permanently fucked for the rest of the round.

# Steps to Reproduce
1. Be in crit.
2. Get flashed.
3. Ghost at the same instant.
4. Suffer: https://pasteboard.co/Kf8yvjQ.png

# What you Expected
Vision

# What Actually Happened
Blindness even after shutting down Byond and relogging entirely.

**Comment by Eneocho** [comment]
That has happened to me a lot when getting out of a spacepod too.

**Comment by DeityLink** [comment]
Might need to know which version of Byond

**Comment by Eneocho** [comment]
> 
> 
> Might need to know which version of Byond

514 before the latest patch.
