### ISSUE TITLE
Mechs opening cult doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30169]
(WEB REPORT BY: ahuehuehue REMOTE: 206.221.180.138:7777)
# Revision
41c4b1acd6f5d94a0534c72b2edf7207892bc714

# A mech piloted by a non cultist opened cult doors.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by gurfan** [comment]
mechs are able to open xeno doors as well, iirc

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/128778217-dfe68107-782c-43f7-ad2a-aae7f536bf6f.png)

**Comment by DeityLink** [comment]
Duplicate of #30167
