### ISSUE TITLE
Mechs can use Cult Doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30167]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
41c4b1acd6f5d94a0534c72b2edf7207892bc714

# Description
See above - Durand waltzed right into the base by using the cult door.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
Might also happen with alien resin doors apparently.
