### ISSUE TITLE
Handtele portals are mouse transparent somehow.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30185]
#### Description of issue
You can't click the portal with the handtele to close it prematurely. Right clicking doesn't show there's a portal in the tile either. You have to alt-click the tile to see its contents then use the handtele on the portal that way.
#### Difference between expected and actual behavior
Expected to still be able to close the portals normally. Got some buggy interactions.
#### Steps to reproduce
Acquire handtele.
Make portal.
Go through portal (optional).
Try to click it with the handtele to close it remotely.
Fail.
Alt-Click the tile.
Click on the tile menu's portal to close it.
#### Length of time in which bug has been known to occur
Probably since #30138 got merged. @kane-f

[bugfix]

**Comment by boy2mantwicethefam** [comment]
feature
