### ISSUE TITLE
[Feature Request] Ability to trigger photo booth outside of the booth

### ISSUE THREAD

**Issue by jwhitak** [d3athrow/vgstation13#30206]
#Description
The photo booths should allow a person outside of the booth to push the button to take pictures of someone inside of the booth. This can be useful for proving you actually have someone hostage, forcibly providing an ID to unwilling hobos, or helping a wizard victim establish their new identity as a sentient crowbar.

#Steps to Reproduce
Ask Deity to code a feature, be told to make a formal feature request

#What you Expected
Throw man into photo machine, click machine, receive pictures of man

#What Actually Happened
Throw man into photo machine, click machine, no pictures

[featurerequest]

**Comment by Eneocho** [comment]
>Ask Deity to code a feature

hey, it worked!
