### ISSUE TITLE
[Goofchem] Toxins do not affect Dionae

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#3020]
CC @iamgoofball

**Comment by AutismSpider** [comment]
Eh that's normal for dionae they burn toxins to heal same with rads

**Comment by AutismSpider** [comment]
oh it works after more testing its that they heal form toxins so fast hard to pick it up
![diona toxin](https://cloud.githubusercontent.com/assets/10268342/6202975/40f716ee-b4cd-11e4-9154-fa3abec43d1c.PNG)

**Comment by Iamgoofball** [comment]
this sounds like an issue with diona

**Comment by AutismSpider** [comment]
It's intended for dionas to have passive healing vs toxins after looking at race stuff.

Goof chems are fine.

**Comment by Iamgoofball** [comment]
@ComicIronic @d3athrow this an intended function of Diona, this can be closed.
