### ISSUE TITLE
You hit yourself with the railgun projectile if you fire from a tile with a window

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#30209]
https://user-images.githubusercontent.com/6307265/129429015-19c734e5-99dc-40a4-8a79-7566b06f41b1.mp4

**Comment by boy2mantwicethefam** [comment]
feature

**Comment by Eneocho** [comment]
needs the Honk tag.

**Comment by ghost** [comment]
basado

**Comment by DriftingSkies** [comment]
this was hilarious to see in round

**Comment by GenericGoose** [comment]
same thing happens if you just throw any item at a window that you're standing next to

**Comment by DamianX** [comment]
Apparently, allegedly, fixed by #30209

**Comment by Servalfang** [comment]
> Apparently, allegedly, fixed by #30209

you linked to the same PR

**Comment by DamianX** [comment]
uhm well ackshually I linked to an issue
fixed by #35088
