### ISSUE TITLE
Latejoin role refused to assign due to null mind

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30216]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
e181a3e7eafcb4646cfa875c7c575c485b3a511e

# Description
[18:05:33] Runtime in dynamic_rulesets_latejoin.dm, line 99: Cannot read null.mind
proc name: execute (/datum/dynamic_ruleset/latejoin/raginmages/execute)
usr: [REDACTED] (/mob/new_player)
usr.loc: The floor (8, 95, 2) (/turf/unsimulated/floor)
src: Ragin\' Mages (/datum/dynamic_ruleset/latejoin/raginmages)
call stack:
Ragin\' Mages (/datum/dynamic_ruleset/latejoin/raginmages): execute()
Dynamic Mode (/datum/gamemode/dynamic): picking latejoin rule(/list (/list))
Dynamic Mode (/datum/gamemode/dynamic): latespawn([REDACTED] (/mob/new_player))
[REDACTED] (/mob/new_player): AttemptLateSpawn("[REDACTED]")
[REDACTED] (/mob/new_player): Topic("src=\[0x3000021];SelectedJob=C...", /list (/list))
[REDACTED] (/client): Topic("src=\[0x3000021];SelectedJob=C...", /list (/list), [REDACTED] (/mob/new_player))
[REDACTED] (/client): Topic("src=\[0x3000021];SelectedJob=C...", /list (/list), [REDACTED] (/mob/new_player))
# Steps to Reproduce
* Be admin
* Fire ragin mages as latejoin ruleset, wait for player
# What you Expected
Assigned role
# What Actually Happened
Runtimed, null mind

**Comment by boy2mantwicethefam** [comment]
Feature

**Comment by DeityLink** [comment]
It couldn't have been null all along since otherwise trim_candidates() would have removed him.

That being said I need to replace trim_candidates for latejoin rulesets, it's stupid using a list when you're only gonna have one candidate at a time.

**Comment by DeityLink** [comment]
wait hold on it's null.mind, not null mind, so the problem is a null mob.

wait why do all those rulesets pick from assigned instead of candidates
