### ISSUE TITLE
Mice can spawn in the Telecoms Coldroom

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30221]
(WEB REPORT BY: ithet REMOTE: 206.221.180.138:7777)
# Revision
5cc99d071856af04e2e3b130b89fdebc53a90916

# Description
The most inhospitable Telecoms Chamber vent is a valid spawn point for mice.
# Steps to Reproduce
Become a mouse.
# What you Expected
To live for a minute or two.
# What Actually Happened
Die from cold and asphyxiation before you can crawl into the vents

**Comment by boy2mantwicethefam** [comment]
feature
