### ISSUE TITLE
No entertainment monitors on metaclub

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30239]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
975f1ad29ab52ce940505ff6ca5f743e7ebf6794

# Description
There are none, at least as far as I could see.

**Comment by DeityLink** [comment]
There's 31 on metaclub

2 in the ghetto bar
1 in viro break room
6 in the library
1 in medbay break room
1 in the chapel office
1 in CMO's office
1 in HoP's office
1 in Captain's office
1 in Security Office
1 in HoS's office
1 in the Science break room
3 in the bar
3 in Engineering Foyer
1 in the CE's office

and also
4 on the research outpost
and 3 on the vox outpost

I can add a few to dorms/crew quarters, but we're a long shot from "no entertainment monitors" @kane-f

**Comment by ghost** [comment]
maybe im thinking of lowfat bagel? i dunno i obsed a round and didnt see a single one

**Comment by DeityLink** [comment]
sounds more likely, there's like 1 intercom in all of lowfat bagel medbay (minus those I added in Virology during its re-map)

**Comment by DeityLink** [comment]
Lowfat Bagel dorms has 12 by itself 
![image](https://user-images.githubusercontent.com/7573912/129782305-c3ddcf7a-d39f-4449-9119-21ea78109a93.png)

The bar has 4, try another map.

**Comment by DeityLink** [comment]
Checked Synergy, nothing standing out either.

**Comment by DeityLink** [comment]
Deff however seems to have barely a dozen. 1 in the bar, none in dorms.
