### ISSUE TITLE
Stop time function in timesuit blocks path on tile called

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30237]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
975f1ad29ab52ce940505ff6ca5f743e7ebf6794

# Description
Stop time function in timesuit blocks path on tile called and leaves empty null mobs with no types in place
# Steps to Reproduce
* Get time suit
* Stop time spell
# What you Expected
A space to freely walk through
# What Actually Happened
Invisible non type mob blocking it

**Comment by DeityLink** [comment]
Reminds me of #30114 
The fix should prevent that from happening again though, weird.

**Comment by DeityLink** [comment]
Actually now that I think about it, it fixes it for virtual hearers alone. If your timestop spawns other base-type mobs (why should it though) they may suffer from that and need the same fix applied to them.
