### ISSUE TITLE
Rewind rifle non-functional

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#30240]
#### Description of issue
Rewind rifle doesn't work

#### Difference between expected and actual behavior
Expected: Bang
Actual: Nothing

#### Specific information for locating
item: /obj/item/weapon/gun/projectile/automatic/rewind
>looks like laser rifle

>ammo_type = "/obj/item/ammo_casing/a12mm" 

>loaded ammo is:
contents:
1 [0x202471e] = /obj/item/ammo_storage/magazine/smg9mm 
2 [0x2024838] = /obj/item/ammo_casing/c9mm

**Comment by Allspice** [comment]
```
/obj/item/weapon/gun/projectile/automatic/rewind/special_check(var/mob/M)
	return istimeagent(M)
```

Need to be a time agent to use it. This was part of the original derelict PR; I'll probably lower the restriction to wearing the full time suit, and add better feedback for why it didn't work.

Or, did the rifle not work for a time agent?

**Comment by djkramer123** [comment]
it does work if you have the time agent role

**Comment by xeroxemnas** [comment]
what are time agents some kind of special race now? Weird how the suit works if you're not a time agent but the rifle doesnt.
