### ISSUE TITLE
[Goofchem]Cyanide

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#3025]
Make it harder to make or take out the list of chem stuff.

It took me 5 mins tops to make 30 units and it only takes 3 to kill some one with it.

required_reagents = list("oil" = 1, "ammonia" = 1, "oxygen" = 1)

**Comment by Iamgoofball** [comment]
cyanide was given a nerf because the reason it was so strong was it was loading both old cyanide and new cyanide effects

@ComicIronic you can close this now

**Comment by ComicIronic** [comment]
Reopen if still an issue.
