### ISSUE TITLE
[Goofchem] various

### ISSUE THREAD

**Issue by gayniggersex666** [d3athrow/vgstation13#3026]
Nerf cyanide, it takes like a minute and a half for 5u to kill someone, bp+clf3 smoke/foam doesnt set off an explosion either, needs a reagent that heats up other reagents while in the beaker like real goon chem.

**Comment by ComicIronic** [comment]
Cyanide is a duplicate of #3025.

**Comment by Iamgoofball** [comment]
@ComicIronic @d3athrow this is fixed on the latest test server build, it can be closed
