### ISSUE TITLE
Burnt Out Campfires are mousel ayer transparent or w/e its called

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30272]
(WEB REPORT BY: kromkar REMOTE: 206.221.180.138:7777)
# Revision
107ca1a63f21f1c15f1039f84afc06e7581ebe8a

# Description
Burnt out campfires must be alt clicked to be seen/interacted with via the mouse. Same issue as a lot of stuff, Deity should be able to fix it :^)
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
The gift that keeps on giving. On the bright side people are more likely to report /obj/effect that are supposed to be clicked than ones that aren't so I think it's better to keep fixing those one by one.
