### ISSUE TITLE
[Goofchem] Health Scanner (balance)

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3027]
The new health scanner tells you exactly how many units of reagents are in your body, along with addiction and overdose status.

I think that it's a bit too powerful, and makes the spectrometers obsolete.

I suggest retaining our current health scanner, and putting these new functions in an advanced health scanner, maybe using the spectrometer sprite, and removing the spectrometers altogether.

**Comment by Iamgoofball** [comment]
People actually use the spectros here?

**Comment by ComicIronic** [comment]
>People actually use the spectros here?

For the reason that they have no use, no.
Give them this.

**Comment by Iamgoofball** [comment]
One of the number 1 complaints at tg about goofchem was "we dont know if he's overdosing, addicted, or just taking damage from a chem" from MDs when patients would stumble in the door dying from shit.

I don't think locking a rather needed part of medical doctoring post-goofchem behind Mining and Research's Wild Ride is a good idea.

**Comment by frangi** [comment]
I'm not saying to make it an endgame item or to require special mats.

something like bio3 and some metal and glass would suffice

**Comment by Iamgoofball** [comment]
Hey guys look we fixed all the goonchem bugs

**Comment by clusterfack** [comment]
Codervalids acquired, lets call for a merge
