### ISSUE TITLE
[Goofchem] OD/Addiction wonkiness

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3028]
Is there no way to recover from OD?
dead bodies are still OD'ing/addicted too, even after death and rejuvenation.

**Comment by Iamgoofball** [comment]
OD: use calomel to purge ODing chemicals
addiction: either feed the addiction to keep it down, or go cold turkey on it long enough until it goes away

Chems don't process while dead.

**Comment by frangi** [comment]
We tested this:
>inject X with 50u cocaine
>let the chem go through its various stages
>brain loss
>heart attack
>dead
>rejuvinate X, which removes all chemicals
>scan him, he still turns up as addicted BUT not OD'ing, no trace chemicals.
>X reports to still have hallucinations
>He's taking brain damage
>He finally dies again by heart attack

**Comment by Iamgoofball** [comment]
That's addiction's effects, not ODing that causes the heart attacks. I'll doublecheck to make sure it's properly curing addictions.

**Comment by Iamgoofball** [comment]
addictions are curing just fine locally
