### ISSUE TITLE
Dwarven Mining Equipment will eat your credits if you don't have enough

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30316]
(WEB REPORT BY: lisyamyata REMOTE: 206.221.180.138:7777)
# Revision
4a98da0246687e378838d2ea8b210fc70dcc9f65

# Description
If you don't have enough money Dwarven Mining Equipment will just take the amount you do have.
# Steps to Reproduce
>Go to Dwarven Mining Equipment
>Try to buy something expensive like a Diamond Pickaxe
>It tells you that you don't have enough and ask to take the funds from your wallet
>It doesn't
>Then eats the credits you have on you
# What you Expected
The item
# What Actually Happened
I am in massive debt

**Comment by DeityLink** [comment]
Related to #28064
