### ISSUE TITLE
Ninja's can spawn on RoidStation's perma asteroid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30318]
(WEB REPORT BY: pulserider REMOTE: 206.221.180.138:7777)
# Revision
4a98da0246687e378838d2ea8b210fc70dcc9f65

# Description
I spawned in a little maintenence hole south of the perma asteroid, and I had to go into space to actually get inside the asteroid. I don't have any access to the station.
# Steps to Reproduce
Be a ninja, use the teleporter, and get (un)lucky?
# What you Expected
To be teleported on the main stations maintenence.
# What Actually Happened
Being teleported onto the perma-roid, with no way to get to the station.

**Comment by SonixApache** [comment]
there's space suits on that roid and you can cut through all the doors
improvise, adapt, overcome
