### ISSUE TITLE
Alkycosine is not possible to make

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30323]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
31be54a339af07b89bb0117b41540b32053d3560

# Description
I tried heating all the ingredients for alkycosine for like 10 minutes and nothing happened
# Steps to Reproduce
1. acquire 30 units of dylovene
2. acquire 30 units of bleach
3. acquire 30 units of alkysine
4. attempt heating with lighter
5. attempt heating with bunsen burner
6. nothing happens
# What you Expected
to be able to make alkycosine
# What Actually Happened
nothing!

**Comment by Kammerjunk** [comment]
haha acute brain damage

**Comment by boy2mantwicethefam** [comment]
I remember that the heating calculations are fucky and you need to do small amounts of chemicals at a time to actually heat it high enough. Yes, it is retarded.

**Comment by Armadingus** [comment]
It's perfectly possible to make alkycosine roundstart without use of advanced tools from science and without taking an hour to boil your bleach.

**Comment by Eneocho** [comment]
Bunsencode is buggy as hell, this has happened to me too. Just ask for a regular laser scalpel and heat the beaker that way.

**Comment by DeityLink** [comment]
It works properly nowadays
