### ISSUE TITLE
refilling an emergency plasma tank with a canister doesn't actually refill it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30324]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
31be54a339af07b89bb0117b41540b32053d3560

# Description
if you let an emergency plasma tank get to 0, refilling it doesn't work.
# Steps to Reproduce
1. get plasmaman
2. give him an emergency plasma tank
3. set internals on
4. allow him to exhaust the plasma supply
5. try to refill with a canister
6. it will appear full
7.set internals once again, he will still be gasping.
# What you Expected
to be able to refill tanks
# What Actually Happened
wasn't able to

**Comment by Dacendeth** [comment]
Did you turn the kpa on the tank back up, it would have been too low naturally if it got exhausted and he'd gasp from not getting enough plasma pressure.
