### ISSUE TITLE
Mugshot Photobooth

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#30337]
A security photobooth with a special sprite; it would have a special background called something like mugshot or lineup; presumably it would also not have most of the normal backgrounds, but NT dark and NT light might still be appropriate

Example of mugshot background sprite
![ mugshot](https://user-images.githubusercontent.com/9782036/130590897-d90a6b61-e912-4e38-9527-e5b13967a614.png)

It would be nice if it also had a red or otherwise security themed sprite, bonus points if the pic can be added to their security records when booking

Bonus if the mugshot background layers a little placard over the player sprite too

**Comment by DeityLink** [comment]
Honestly I think we could have that background sprite on all photobooth, makes it easier too, we only need the subtype to have a different default background.
