### ISSUE TITLE
At the end of the day, Sacrifice is just a suggestion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30346]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
25705ebd704a6888c329d12a7eb8adfd821e2c2e

# Description
Local fuckhead sacrificed by cultists, actually survives.
# Steps to Reproduce
1. Be the sac
2. get shot full of shitter juice
3. get sac'd
4. wake up perfectly fine, scold the cultists for being rude, get decapitated
# What you Expected
death
# What Actually Happened
life

**Comment by DeityLink** [comment]
> Be the sac

no yer not!

> The Sacrifice: Nar-Sie requires the flesh of Nass Bassford, the (Security Officer)
> Nass Bassford/Welrd5clence
