### ISSUE TITLE
Revsquad is Bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30341]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
977c56c8fa4216ba2aca034afc88cfa398d1fb3d

# Description
Spawned as a revhead for a rewvsquad and instantly won despite every head still being alive.
# Steps to Reproduce
Spawn a revsquad.
# What you Expected
A fun round.
# What Actually Happened
I won instantly.

**Comment by Eneocho** [comment]
The (((heads))) were too afraid of the working man and surrendered.

**Comment by kernikov** [comment]
Just crashed another round.

**Comment by Kurfursten** [comment]
Probably caused by https://github.com/vgstation-coders/vgstation13/pull/30287

**Comment by DeityLink** [comment]
I'll look into it.
