### ISSUE TITLE
add tasks.json (and .atom-build.json ig??) to .gitignore

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#30340]
![image](https://user-images.githubusercontent.com/5942183/130691591-5d79d504-c14a-4d92-a7b9-8a202529d097.png)
please I just want to `git add .` without adding build setup...

**Comment by Kammerjunk** [comment]
wait I mean this one
![image](https://user-images.githubusercontent.com/5942183/130691784-f5519e50-626e-4273-981f-1cfaceb1400c.png)

**Comment by DamianX** [comment]
>atom

😂

**Comment by DamianX** [comment]
tasks.json for vscode goes inside the .vscode folder and is already gitignored

**Comment by Kammerjunk** [comment]
wtf it is
why have I just had it lying around in root (_as well_) for several years
