### ISSUE TITLE
[Goofchem] Heat isn't retained when transferring chemicals to an empty beaker and heat isn't mixed when two beakers are mixed together

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#3034]
@iamgoofball
Sorry if this is intentional but I was trying to make a black powder grenade and was unsuccessful after trying clf3 black powder foam, clf3 black powder smoke and then I tried foam without clf3 heating up both the beakers to try and get it to reach that explosive temperature
Is there a way to use this chemical beyond blowing up your chemistry lab and chem heater?

**Comment by Iamgoofball** [comment]
heat is stored on the beakers themselves, not the chemicals

i can fix 'nades though
