### ISSUE TITLE
Feature Request: Whipped Cream

### ISSUE THREAD

**Issue by RonPaul08** [d3athrow/vgstation13#30350]
Please either add canned whipped cream, or be able to use a spray bottle to apply carbonated whipped cream to food. It's quite sad to eat a slice of pumpkin pie without whipped cream on top. 

It would just be a little white swirl that could be transposed on any food item, but would do wonders for muh immulsion.

**Comment by Killette2** [comment]
Can you lick/scoop it off the pie with your fingers?
