### ISSUE TITLE
[Feature Request] Glass should have a minimum damage threshold before actually taking damage

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#30354]
You should not be able to throw your shirt at a window until it breaks. Normal glass should have no threshold, Rglass should require over 5 brute damage to take damage, Pglass 10, and then RP (roleplay) glass should require either 15 or the damage throwing a shard does, whatever is lower, so that it's worthwhile to upgrade windows with what is possibly the most tedious material in the game to get in large quantities. Currently you can smash through windows in a matter of seconds, meaning that any prospective mapper or aesthetically inclined engineer has to make hacky workarounds.

**Comment by Kurfursten** [comment]
Imagine a world where electrified grilles weren't shardable

In seriousness though I thought this issue was going to be about making drinking glasses more durable when blown by wind or thrown by the vendomat

**Comment by Eneocho** [comment]
I once broke a reinforced window by throwing a live mouse to it about 50 times. fun gimmick.

**Comment by GreatBigFailure** [comment]
I got bwoinked for nearly causing a shard to explode by breaking the glass with IEDs that threw eggs everywhere. The eggs smashed through most of the windows.
