### ISSUE TITLE
Taking a picture of a brained challenger

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30355]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
0f2dde04d40ec40038ea3c7bca92e15aff6a7961

# Description
Braining an opposing challenger and taking a picture of the corpse and brain does not count as a kill.

# Steps to Reproduce
Brain your opponent, take a picture of the corpse and brain, post to a newsfeed channel, get nothing in return.

# What you Expected
Sweet, sweet dopamine rush.

# What Actually Happened
Nothing.

**Comment by gurfan** [comment]
thanks now I know my target is a challenger

**Comment by DeityLink** [comment]
Well I have honestly no idea, unable to reproduce on my end, please ping me next time you see the problem happen so I can try to debug it live.

**Comment by west3436** [comment]
Some more detail:
>brained the guy with a silenced pistol
>took picture of the aftermath and stole his PDA
>made a newscaster channel using his ID and posted the picture under his name

**Comment by DeityLink** [comment]
I tried to reproduce it in various ways, both ghosting before and after the head exploding occurs, but each time the brain properly had a brainmob with the target's mind in it, and pictures taken had the proper references to validate the objective.

I know I'm asking much but try to keep the brain at hand and call me so I can jump in and varedit it to check if the mind and stuff were properly transferred. Right now I don't understand how it could not happen. Looking at the logs the target properly ghosted only after their head exploded.

**Comment by west3436** [comment]
Unable to reproduce anymore please close @Kurfursten
