### ISSUE TITLE
Unwall spell doesn't work after cloning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30358]
(WEB REPORT BY: notaspider REMOTE: 206.221.180.138:7777)
# Revision
0f2dde04d40ec40038ea3c7bca92e15aff6a7961

# Description
When a mime gets cloned, the unwall spell no longer appears on their hotbar
# Steps to Reproduce
Die as a mime with Unwall and get cloned
# What you Expected
To keep the unwall spell when I was cloned
# What Actually Happened
I did not.

**Comment by DeityLink** [comment]
Grouped up in #30360
