### ISSUE TITLE
Ninja Discussion: Suit Importance

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#30371]
I have been actually thinking about this since ninjas got their modern suit. Some ninja features should be explicitly tied to wearing the suit. Currently, you do need to wear the suit to receive power when you drain something, but you can drain things regardless as long as you keep your power glove.

**My thinking is that in order to get your special bonus speed with throwing stars *and* to use ninja hologram projectors, you need to be wearing the suit**. If you choose to disguise yourself in a non-ninja suit, you can still throw stars slowly and you still get the other perks like the poster, nightvision, sword, etc. - but you lose some of the ninja's most potent combat abilities to compensate for your stealthiness.

Thoughts?

**Comment by jknpj** [comment]
For the love of god, they need a proper glove sprite, they\ve been using the power glove icon for YEARS

**Comment by SonixApache** [comment]
There were supposed to be more things tied to the suit; stealth mode, energy net, pAI with features, etc.
i wouldn't restrict ninjas into wearing their suits until there's a good reason for it
