### ISSUE TITLE
Unable to light mobs on fire

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#3038]
After playing with clf3 and flamethrowers for a bit I noticed fires were a bit fucked, while it's happy to heat up rooms it doesn't seem to damage you if you're standing in it or light you on fire.
I was able to light mobs on fire with clf3 spray but they were not taking damage and couldn't resist it or have it extinguished with a fire extinguisher
![untitled](https://cloud.githubusercontent.com/assets/7538670/6203900/83983e12-b52f-11e4-846d-84d87647809b.png)

**Comment by d3athrow** [comment]
CLF3? Is this on the main server or goofchem?

**Comment by Konater** [comment]
This was goofchem, but I was trying welder fuel fires too

**Comment by d3athrow** [comment]
I cant even get flamethrowers to ignite on live.

**Comment by Konater** [comment]
https://github.com/d3athrow/vgstation13/issues/2689

**Comment by Iamgoofball** [comment]
if this is happening on main this isn't my problem and therefore not a goonchem bug @d3athrow

**Comment by PJB3005** [comment]
This should be closed since rip goofchem on /vg/
