### ISSUE TITLE
[Feature Request] Make the foam from extinguishers slightly grey

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#30389]
Did you know that the foam from extinguishers actually has a texture and isn't just a gross solid white cube? For bonus points it shouldn't have a razor sharp edge and work like roid tiles, and also only cover the person's sprite on the bottom like water tiles. 

Here's foam with mercury instead of water for reference.
![foam](https://user-images.githubusercontent.com/51391726/131235720-cd0d9144-803a-4dc1-96fc-0ba35b83a93c.PNG)

**Comment by Blithering** [comment]
Doesn't the foam take on the colour of the reagent like other foams?
