### ISSUE TITLE
Surgery limb targeting 

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#3039]
If you swap your limb target during the surgery process whatever you do will apply to the targeted limb at the end rather than the one you started with. This used to be a funny way to saw off groins to those who knew how but when using it for limb replacements it turns into some clowny shit
![untitled](https://cloud.githubusercontent.com/assets/7538670/6204045/288dba92-b534-11e4-9dcf-9954ba2d60a2.png)

**Comment by ComicIronic** [comment]
>he has a peg head

Wontfix.

**Comment by CptWad** [comment]
Oh god. Given how you do it you could repair bones in multiple spots while only opening one spot open?
I imagine this should get fixed but I agree with comic the peg head must stay.
