### ISSUE TITLE
Waystation Cargo starting without their usual medkit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30394]
(WEB REPORT BY: ithet REMOTE: 206.221.180.138:7777)
# Revision
9113acdae55d0c39b171283d0a023efea8d69f32

# Description
Cargo lacks their usual medkit
# Steps to Reproduce
Have a techie swallow a floorpill
# What you Expected
Grab a scanner from the usual medkit to see how fucked he is
# What Actually Happened
No medkit, poor techie.

**Comment by GeneralVeers25** [comment]
It's there, someone stole it before you got to it.
