### ISSUE TITLE
WayStation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30398]
(WEB REPORT BY: walrusquake REMOTE: 206.221.180.138:7777)
# Revision
9113acdae55d0c39b171283d0a023efea8d69f32

# Description
Yeah it's not a big deal but this table placement is really strange. I can't access the fridge without cornering it. Would be better placed two tiles downward from where it is, next to the smartfridge in chemistry.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by GeneralVeers25** [comment]
I'm not entirely sure what you're referring to. Can you post a picture?
