### ISSUE TITLE
[Meta] Officer beepsky gets stuck in the escape hallway

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3041]
There are also two beepskys. so they play in escape all day until a traitor comes to collect his free stun batons

**Comment by AutismSpider** [comment]
Issue is the window is blocking them.

After i deacon and move the windows they work like normal

**Comment by d3athrow** [comment]
They're probably not realizing the window is blocking adjacency when it forms its a* path.

**Comment by Probe1** [comment]
@AutismSpider is he still trying to arrest mommis?
