### ISSUE TITLE
You can't transfer reagents from a condiment bottle to a cauldron.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30421]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
f41b3bf24cf6606264af548899a10d3111f59626

# Description
Title. If you try to transfer any amount from the bottle to the cauldron, it says that the bottle is full, regardless of bottle status or intent.
You CAN transfer from a condiment bottle to a beaker though.
# Steps to Reproduce
Get a Condiment bottle.
Try to transfer them reagents to a cauldron.
Fail miserably.
# What you Expected
To mass produce mayonaisse.
# What Actually Happened
Had to make it slowly.

**Comment by Kurfursten** [comment]
Confirmed on live
