### ISSUE TITLE
1x1 singularities wont destroy the floor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30426]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
9beaa3b9272824f5e15dfb19e142e8f6f61cc3ff

**Comment by gurfan** [comment]
isn't this a bug though, I'm 99% sure small scrungulos are supposed to destroy the floor below it and I remember them always doing it

**Comment by DeityLink** [comment]
it is, I thought the bug label was redundant, it is a feature loss which is a problem in itself.
