### ISSUE TITLE
phazon tiles dont make you speed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30427]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
9beaa3b9272824f5e15dfb19e142e8f6f61cc3ff

**Comment by DeityLink** [comment]
Wait really? It worked fine for me yesterday, need more info @gurfan

**Comment by BomberBro** [comment]
They make you faster, but not the retard fast speed (not to be meant in a negative way, it was fun) that it used to be.

**Comment by gurfan** [comment]
for two rounds I saw people walking along it at near normal speed. I did see a cyborg going fast on it though

**Comment by Eneocho** [comment]
Wait, phazon ZOOM nerf? Damn you C*ders!

**Comment by nervere** [comment]
works on my machine
