### ISSUE TITLE
Brig Paramedic doesn't have access to the brig medical area

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30434]
(WEB REPORT BY: dackjaniels REMOTE: 206.221.180.138:7777)
# Revision
9beaa3b9272824f5e15dfb19e142e8f6f61cc3ff

# Description
he needs it!
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by GeneralVeers25** [comment]
Not sure what to tell you, honestly - it's the same access on the windoors that Box has.
