### ISSUE TITLE
Waystation Feedback - Disposals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30437]
(WEB REPORT BY: punishedpajeet REMOTE: 206.221.180.138:7777)
# Revision
9beaa3b9272824f5e15dfb19e142e8f6f61cc3ff

# Description
Please add disposals to Waystation
# Steps to Reproduce
Play Waystation
# What you Expected
Disposals
# What Actually Happened
No disposals

**Comment by Kurfursten** [comment]
Related: no recycling room? Even packed had one
