### ISSUE TITLE
R&D Air Alarm Issues on Waystation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30435]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
9beaa3b9272824f5e15dfb19e142e8f6f61cc3ff

# Description
The atmos in the room appears to be a bit doinked up, whether it be the actual fire alarm or the room itself.
# Steps to Reproduce
Just look at it.
# What you Expected
Not borked R&D room.
# What Actually Happened
it's borked for some reason?

**Comment by DriftingSkies** [comment]
Didn't specify enough, I specifically meant the R&D server room.

**Comment by DriftingSkies** [comment]
Specifying even more, the Atmos in the R&D Server room gets to a very high pressure. It's just slightly annoying but not that big of an issue.
