### ISSUE TITLE
sec doggy doesnt like brig medic and other issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30431]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
9beaa3b9272824f5e15dfb19e142e8f6f61cc3ff

# Description
brig medic cant open wolf cage from traders and the wolf smashes tables/glass/anything it can when following its owner
# Steps to Reproduce
try to open wolf crate from traders as brig medic. Second part: tell your dog to follow you by pointing at it, lead it adjacent to tables, glass, etc, and watch it destroy the station as if the security it's made to help aren't doing that enough already
# What you Expected
friendly doggy who help
# What Actually Happened
doggy that i had to get help to open, and who smashed shit

**Comment by BomberBro** [comment]
Brig medics aren't Security.

**Comment by Kurfursten** [comment]
Brig medics aren't security

Good point about smashing tables though
