### ISSUE TITLE
[Goofchem] Goon healing chems

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#3043]
silver-sulfadiazine styptic-powder Saline-Glucose Solution *synthflesh and omnizine (sure i miss two more of them)

Better off taking it out we have chems for that or make them work via dropper/rubbing it on people with a rag only for healing (aka heals damage with out waiting but got keep rubbing it on them/using the dropper on the hurt zone this should make the mob hit the floor in pain+scream down side is if you eat any if them you start to heal slowly but take toxin damage)

For omnizine i should work only in pill its like MUCH stronger Doctor's Delight.

**Comment by Iamgoofball** [comment]
i'm not removing these chems.

**Comment by AutismSpider** [comment]
Don't have to. 

If you can have them work in new way by rubbing it on people via rag or using the dropper the hurt zones only.

**Comment by ComicIronic** [comment]
>omnizine is a much stronger doctor's delight

This is really getting abused if it's true. I'd suggest removing it in favour of just having specialised chems.

**Comment by Iamgoofball** [comment]
@ComicIronic the thing about omnizine is that it actually has an overdose so people will take 50u pills and die horribly of every damage type

**Comment by Iamgoofball** [comment]
@AutismSpider that would be so snowflake it's not even funny

no

**Comment by ComicIronic** [comment]
It doesn't matter if it has an overdose.
Unless goonchem involves stripping out cryo, botany is just going to grow insane amounts of weed because of its superior medicine and medbay is never going to use anything else.

**Comment by Iamgoofball** [comment]
alright, i'll remove it's healing effects

chem itself and it's source needs to stay for the purposes of other recipes

**Comment by Iamgoofball** [comment]
Omnizine no longer heals
