### ISSUE TITLE
The shuttle has fucking HOLES in it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30445]
(WEB REPORT BY: dackjaniels REMOTE: 206.221.180.138:7777)
# Revision
952674006672039516ff20a4efdf8535d20fa65d

# Description
FIX IT MY IMMERSION
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/131434052-2fa50785-bf00-49a8-a97a-077a41544423.png)
