### ISSUE TITLE
There's no floorpill in Waystation ghetto surgery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30457]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
41f4d4e29de1b5b765677d290a80058cfd37f5da

# Steps to Reproduce
Find a loving partner.
# What you Expected
A floorpill in Waystation's ghetto surgery.
# What Actually Happened
Pure unadulterated disappointment.

**Comment by DriftingSkies** [comment]
WHAT
