### ISSUE TITLE
legacy job slot issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30468]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
05326025248b53b993921e03e04bdc96cccb0393

related to the science job split for xenobio and xenoarch
joining as a legacy scientist (with the old xenobio/xenoarch/anomalist alt titles) spawns you as a near naked scientist with your ID in your backpack

**Comment by Kurfursten** [comment]
Feature

Encourage scientists to give up their legacy titles

**Comment by Eneocho** [comment]
There's bound to be at least 1 guy who'll keep the legacy alt title and will deal with the nakedness just for the bragging rights.

**Comment by Killette2** [comment]
This happened to me too when I kept virologist as a MD a few years ago
