### ISSUE TITLE
no containers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30460]
(WEB REPORT BY: heroinehero007 REMOTE: 206.221.180.138:7777)
# Revision
41f4d4e29de1b5b765677d290a80058cfd37f5da

# Description
Waystation lacks anomaly containers to contain large artifacts.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DriftingSkies** [comment]
As it should be
