### ISSUE TITLE
 [Feature Loss] Grinding seeds does not produce pepper

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3048]
Or anything at all.  Inserting seeds into an all in one grinder should result in pepper but it does not.  

Have a look and see what the problem is and for bonus points, rewrite the whole damn thing so adding chilis to the food processor results in pepper.  That'd be way more logical.

**Comment by 9600bauds** [comment]
Grinding chili results in capsaicin though, pepper is made from chili seeds, not the fruit.
See: #2794
I tried to fix this problem myself but couldn't, sadly.

**Comment by Probe1** [comment]
Yep you've described it.  I did say and meant 'use the processor, not the grinder' to produce pepper.  That avoids the snowflake process of using seeds to produce something, contrary to all the rest of cooking.

Still, duplicate issue is a duplicate issue!
