### ISSUE TITLE
Killer tomato simplemobsmove by "throwing" themselves, which floods the attack logs if more than just a handful are alive.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30494]
#### Description of issue
Title.
#### Difference between expected and actual behavior
Expected some really basic monkeylike AI instead of them throwing themselves. That also explains why they're so harmless.
#### Steps to reproduce
make a killertomato simplemob
check attacklogs
[logging]

**Comment by Kammerjunk** [comment]
oldcoders need to be dragged out into the streets to face mob justice

**Comment by DamianX** [comment]
This doesn't seem to be true. They are as basic as a simple_animal can get, nothing about their movement is special in any way.
So, what happened?

**Comment by Eneocho** [comment]
Check the 529MB 03-Friday Attack log. I had made a tomato engine and the attacklog got massively flooded with millions of "tomato has been thrown by () (what)" or something like that.

**Comment by Eneocho** [comment]
Nevermind, they edited the logs to make them readable. According to a guy from the thread, there were 5,659,200 tomato attack lines. Here's a screenshot.
![image](https://user-images.githubusercontent.com/67024428/132108441-ebe0ec01-c7e5-4489-833d-7b56fecdb188.png)

**Comment by DamianX** [comment]
Can you describe this tomato engine?
Here is an image of pulling teeth:
![image](https://user-images.githubusercontent.com/6307265/132115000-4e466b13-ec22-45d7-852b-5091b1d14881.png)

**Comment by Eneocho** [comment]
About 100-150 Killer tomatoes on a treadmill+mass driver combo. 
Here's a picture of a sleeping nukie:
![AYHbf4flqU8](https://user-images.githubusercontent.com/67024428/132120085-1cceda1c-dca5-45a4-b401-cd280efd159f.jpg)

**Comment by Kammerjunk** [comment]
damn I wonder what was throwing them

**Comment by DamianX** [comment]
Yeah, I'm starting to think the mass driver engine with a 150 tomatoes caused this, and that they didn't throw themselves.

**Comment by Eneocho** [comment]
Fair enough am retarded
