### ISSUE TITLE
Turn to stone while bleeding

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30492]
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 206.221.180.138:7777)
# Revision
2f6bcded66dad986d846ab7ed469038f01ec01a8

# Description
Getting turned to stone while having a bleeding external wound and still bleeding
# Steps to Reproduce
Get turned to stone by wiznerd or cockatrice
# What you Expected
To not bleed out while I am a statue and have time to bandage after I unstone
# What Actually Happened
Kept bleeding out while turned to stone

**Comment by DeityLink** [comment]
I witnessed it happen
