### ISSUE TITLE
[Feature Request] New camera machine for Wardens Office

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3049]
Brace for this cause it's a doozy.  Hold judgement until you get to the end.

I want a new machine in the Wardens office that acts like an atmospheric monitoring console for cameras.  Not a computer, a machine.  So we're imagining this image, except for security cameras instead of air alarms.

![2](https://cloud.githubusercontent.com/assets/8550416/6206472/a6c76380-b558-11e4-9fdf-2db0aee39939.JPG)

Already it's looking pretty neato right?  Well here's why I really want it.  If you upgrade it with the top level of parts (pico manipulators phasic scanners et cetera) instead of having to click a camera then back out and click another one, you have similar functionality as the AI with an important exception!  You can only see one room at a time, like you were wearing meson goggles.  You'll be able to look from room to room like the AI but you'll only be able to see things in the room you're focusing on.

 I think it'd be a great way to get RnD/mechanics involved in security since there are 0 machines security needs you to upgrade and only on rare occasion is building a little security autismfort somewhere on the station done.  So security really doesn't get much love from engineering/research in that regard.  Putting that last AI-esque functionality behind top level parts will make it infrequent enough that it isn't a balance issue, but give a really cool late game possibility for Wardens.

Does that sound cool or what?  I'm way too inexperienced to be able to code this so it's going to languish here forever/until someone picks it up.

**Comment by eswordthecat** [comment]
First for T-thanks BYOND tag!

**Comment by Shaska-** [comment]
Alternatively, change security cams to use the old AI view.
The code is probably still hidden in there somewhere.

**Comment by Probe1** [comment]
The old AI view is how I originally described it but people didn't understand what I was talking about.

**Comment by eswordthecat** [comment]
Show pic of old AI view.

**Comment by Probe1** [comment]
> D3athrow: probe1 its not possible because the camera net is a bunch of client images sent to the AI to block off view of areas out of cam range

Hold out hope..

**Comment by Shaska-** [comment]
It's not really possible to show a descriptive picture of it @eswordthecat 
What is was however, was the AI would see the world from the perspective of a camera, rather than the free-floating eye we have now, and it could jump between cameras by using the arrow keys to jump to the closest camera in the direction you pressed. To be honest, it felt a bit clunky, but it would be a massive improvement over what we currently have.

Sounds like it's not possible though unfortunately.

**Comment by d3athrow** [comment]
Old AI camera view is workable, current AI cam view is not  as when things are blocked off from view of a camera it gets that static image  placed over it.

**Comment by Probe1** [comment]
That's what I want!  I just wait to be able to move from camera to camera with the keyboard instead of backing out.  That simplicity puts a ton of power in the wardens hands and lets him very effectively follow people instead of searching for the next room in a clunky old UI.
