### ISSUE TITLE
Soups leave crumbs when eating

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30500]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
3cd2eb209be77ae7b7d8c434cf98a629f6a3e45d

# Description
FUCKING CRUMBS HOW THE FUCK DOES LIQUID MAKE CRUMBS
# Steps to Reproduce
eat soup
make magical crumbs
# What you Expected
fucking anything but soup crumbs
# What Actually Happened
MY IMMULSIONS, ANNIHILATED

**Comment by Killette3** [comment]
That's actually the soup mixed with the dead skin cells on your face and plaque on your teeth. You don't shower or brush as often as you should
