### ISSUE TITLE
Optical material scanners do not show station pipes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30517]
(WEB REPORT BY: armadingus REMOTE: 206.221.180.138:7777)
# Revision
a8348d981a4708139cf7b3857459f3fe7e88ecd4

# Description
I couldn't see the pipes and wires of the station layout with the very underused light blue optical material scanners. I could only see 3-way manifold pipes.

# Steps to Reproduce
>remove pipes from premises
>wear material scanners to see where the pipes once were

# What you Expected
I expected to have the material scanners guide me where to lay pipes.

# What Actually Happened
I had to load up a .dmm to see where the pipes were.

**Comment by Eneocho** [comment]
As far as I remember, these matscanners only show you the pipes like a T-ray scanner. You also need a holomap to see where the pipes once were.

**Comment by DeityLink** [comment]
Then there's an issue in its description, as it says it ""Allows one to see the original layout of the pipe and cable network.""

**Comment by Armadingus** [comment]
![image](https://user-images.githubusercontent.com/55976761/132171423-1b511c44-a0e4-4b20-8b59-35bb268b36ba.png)
Both the holomap and material scanner do not work as intended.
I have to point out here that the goggles and holomap work the same way, showing the original layout of wires, pipes, APCs, etc. Material scanners aren't t-ray scanners and never have been.

**Comment by Exxion** [comment]
Probably plane issues from multiZ again

**Comment by kernikov** [comment]
I second this. Please fix.
