### ISSUE TITLE
glass floors are STILL totally invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30510]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
d96c52c157af0e453d707e0d34a11f3547a5bb2f

they still are!

**Comment by beesil** [comment]
the server didn't update yet dummy

**Comment by DeityLink** [comment]
![image](https://user-images.githubusercontent.com/7573912/132128518-50e8b5d0-095b-4dcf-b8a6-e24ff6af0015.png)
Looks fine to me.
