### ISSUE TITLE
Wooden things don't catch on fire

### ISSUE THREAD

**Issue by west3436** [d3athrow/vgstation13#30525]
#### Description of issue
Flamethrowers don't set wooden tables, chairs, or bookcases on fire.

#### Difference between expected and actual behavior
Why don't wooden things burn when fire is thrown at them?

#### Steps to reproduce
1. Shoot flamethrower at wooden tables, chairs, or bookcases.
2. Nothing

**Comment by Exxion** [comment]
Not surprising that bookshelves don't ignite from a flamethrower, since the fire doesn't appear on the bookshelf's own tile. But I'm not sure why the others don't.

**Comment by Eneocho** [comment]
Possibly related to #21066, #29732 and #29798.

**Comment by SonixApache** [comment]
and #18698

**Comment by west3436** [comment]
Closed via #33351

**Comment by Exxion** [comment]
You sure? I'm 95% sure all of these objects were already possible to ignite

**Comment by west3436** [comment]
> You sure? I'm 95% sure all of these objects were already possible to ignite

When I opened this tables and chairs weren't burning, but they are now. That was really all I was going for here

**Comment by Exxion** [comment]
I've definitely ignited tables and chairs before that PR. I made a table-fueled fireplace on at least one occasion
