### ISSUE TITLE
Europa Lights - Teleporters Send You to Hell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30523]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
6f7fbe95c1a05d1fe7a6b333715d1583e4aae7f2

# Description
Using the teleporter spawns an infinite stream of sparks leading to insane lag.

# Steps to Reproduce
1. Set teleporter destination to a beacon near the teleporter.
2. Turn teleporter on.
3. Bluespace time

# What you Expected

# What Actually Happened

**Comment by GreatBigFailure** [comment]
This is such a consistent problem I think we should really just remove sparks from the teleporter. Admittedly this would lose some fun moments. I've accidentally set rooms on fire by being too lazy to walk, but still, this is one of many issues specific to teleporter sparks.

**Comment by Exxion** [comment]
I thought this was fucking fixed already
Like twice

**Comment by ShiftyRail** [comment]
@Exxion It got eaten by rebase. My bad.
