### ISSUE TITLE
toggling meson goggles is borked

### ISSUE THREAD

**Issue by tomacatx2** [d3athrow/vgstation13#30531]
#### Description of issue
cant turn meson goggles back on after you turn them off with the buttons in the top left

#### Steps to reproduce
equip meson scanners
click the button in the top left to turn them off
they are off
try the same button to turn them back on
wtf they wont turn on

#### Difference between expected and actual behavior
expected : to be able to toggle mesons on and off at will
actual behavior : they are always off after the first click

i think its something to do with Europa lights, cause it worked fine yesterday

**Comment by Dacendeth** [comment]
Yeah this is a europa light bug, i noticed it before when it was on the test serb.
