### ISSUE TITLE
You can get stuck in a kitchen/slime processor if you have your hands full

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#30546]
#### Description of issue
You can softlock yourself out of the game if you don't get help from other people by click-dragging yourself into a processor while having items in all of your hands.
You'd normally get yourself out of the processor by activating it while inside, you cannot do this without an empty hand.

I want to suggest an eject verb and the ability to click-drag things out of the machine.

#### Difference between expected and actual behavior
I expect a simple kitchen machine not to be a Chinese finger trap.

#### Steps to reproduce

1. Fill your hands by holding things
2. Click-drag yourself into a processor
3. ;help

#### Server revision

69bdef3a6a8981793aac786e7aabc4e2d06a242c

**Comment by Eneocho** [comment]
You can take items on and off, also store em into a bag/pocket while inside the processor. Just store that whatever item into your bag and activate.

**Comment by Armadingus** [comment]
This is true, there is also the case of where your inventory is full. You cannot drop items whilst inside of the processor, which makes it rare, but still pretty serious.

**Comment by DeityLink** [comment]
easily fixed by letting you drag n drop yourself out the same way

**Comment by Eneocho** [comment]
> 
> 
> easily fixed by letting you drag n drop yourself out the same way

That would ruin using the food processor to gib chicken-dressed people, since they could just drag themselves out.
