### ISSUE TITLE
Can't rotate the Waystation Shuttle Command Seats

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30548]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
69bdef3a6a8981793aac786e7aabc4e2d06a242c

# Description
unplayable

**Comment by DeityLink** [comment]
Are you talking about the one with a central pivot point? You sure?

**Comment by DeityLink** [comment]
![gamer](https://user-images.githubusercontent.com/7573912/132280395-aa8ccb84-ca5d-4f5b-87fc-5d9fcbbef33d.gif)

**Comment by DeityLink** [comment]
![gamer2](https://user-images.githubusercontent.com/7573912/132280591-3ff85fe3-a1ba-4ea0-9832-96160feaf309.gif)

Just have your ghost right on top of the gamer chair
