### ISSUE TITLE
All switchtools works as a multitool/wirecutter for pulsing/cutting wires

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#30553]
#### Description of issue
Open any hacking menu with those little babies and you will also find out that you can pulse and cut wires with just the tool itself.
What's also funny, once you have the hacking menu open, you could empty the switchtool of all of its tools and it would still function as both a wirecutter and multitool.

#### Difference between expected and actual behavior
I expect this switchtool type to require its missing tools to perform the task requiring said tool, but guess, not

#### Steps to reproduce

1. screw open panel of machine
2. open wire menu with either multitool or wirecutter
3. have any switchtool in an active hand and click on any pulse/cut/mend button

#### Server revision

69bdef3a6a8981793aac786e7aabc4e2d06a242c

**Comment by Eneocho** [comment]
Come on man. Why you gotta tell deity about this kinda thing? This is too much. This ain't helpful.

**Comment by DrSnips** [comment]
Someone brought this up with me a long time ago and I just deemed it a feature because it doesn't hurt anything.
t. Person who is possibly responsible for this behavior.

**Comment by Eneocho** [comment]
@DeityLink, This one should be closed since it got stealthfixed by D*mian.

**Comment by Armadingus** [comment]
It was fixed months ago, I'll close it.
