### ISSUE TITLE
You can put tables down to bypass obstacles

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#30552]
#### Description of issue
Because we can place tables adjacent to us now, we can use this to bypass machines blocking our path. Most notably blast doors, starscreen fields, security barricades, list goes on.
You can bypass obstacles by either **A)** having a buddy put you on the table. **B)** making the table you placed into a surgery table and then climbing on it yourself.

#### Steps to reproduce

1. put reinforced table beneath blast door
2. put scanner on reinforced table by using the alt-click turf tab
3. click-drag yourself onto surgery table by also using the alt-click turf tab
4. you are now on top of the obstacle and can move freely

#### Server revision

69bdef3a6a8981793aac786e7aabc4e2d06a242c

**Comment by DeityLink** [comment]
Yeah, already noticed that one when testing kitchen shutters the other day.

**Comment by Eneocho** [comment]
Ok, this is too much. Stop. Stop giving deity bugfix ideas.
