### ISSUE TITLE
Invalid name laxening

### ISSUE THREAD

**Issue by drawsstuff** [d3athrow/vgstation13#30604]
#### Description of issue

Character names currently can only contai the characters A-Z, a-z, -, ' and .

This is somewhat needlessly restrictive, especially when it comes to creating foreign characters. Here's a few examples of names that are completely valid but currently impossible to use (unless you're a silicon, which is somewhat hilarious)

Ċikka Farr
Fábián Benedek
Göktürk
Jérôme Mostinckx
Raperîn Nîwar

If a MoMMI can be literally named in Egyptian Hieroglyphics, I don't  think it's unreasonable to lax the filter just a little for people to allow for these completely realistic and plausible names.

#### Steps to reproduce
1. Create a new character
2. Enter a name with a non-english character based on the latin alphabet. (I'm sorry to anyone named 𓅱𓉔𓄿𓏏 𓏏𓉔𓇌 𓆑𓅱𓋴𓎡 𓂧𓇋𓂧  or 劉曉波 but your day to shine comes later. You may copy paste this character as an example : ú
3. Have name rejected

#### Specific information for locating

>Invalid name. Your name should be at least 2 and at most 52 characters long. It may only contain the characters A-Z, a-z, -, ' and .

#### Server revision

2d19efec36b8199ea67b75b2d5fa9b609a58a11c

**Comment by DeityLink** [comment]
I'm not sure where that "easy fix" comes from.

**Comment by DriftingSkies** [comment]
There's a lot of borked figures in certain places like sec records, for example I use █ to redact things in records and the SecHUD formatting for it's fucking BORKED bros

**Comment by Eneocho** [comment]
That explains why the Polish name Clown failed.

**Comment by Eneocho** [comment]
For reference, we have a decent amount of statics with spanish names (anyone with an -ez last name, sánchez, for example). Those names use accented vowels in certain syllables, but our current name system forbids accented vowels.
