### ISSUE TITLE
[Feature Request] Crayon text should be similar to text written in blood

### ISSUE THREAD

**Issue by PavelCIA** [d3athrow/vgstation13#30601]
[featurerequest]
Blood text is much more readable and looks way better overall. Just make it less bloody I guess and add the different colors.
![Carp Fortress Nineteen 2021-09-07 171348](https://user-images.githubusercontent.com/57631584/132369657-13b540cc-9b0a-45d8-8fde-bcaeedb7eace.png)

**Comment by DeityLink** [comment]
Being able to choose a different font would be nice, but that one specifically called "bloody" should be reserved to writing in blood.

**Comment by PavelCIA** [comment]
I don't want the exact same font, I just want crayon writing to be the same size so you can actually read it

**Comment by DeityLink** [comment]
Well you can use painting brushes to Alt+Click floors now to write with the bloody font.
