### ISSUE TITLE
Europa Light issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30612]
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
2d19efec36b8199ea67b75b2d5fa9b609a58a11c

# Description
lightsources disappear if you close a closet/crate ontop of them
# Steps to Reproduce
put a crate under a small lightbulb and close it
# What you Expected
for the light to keep shining
# What Actually Happened
the light gets trapped inside the crate

**Comment by ShiftyRail** [comment]
That's hilarious.
