### ISSUE TITLE
MoMMI meson augment with nu light system

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30616]
(WEB REPORT BY: blueelectrode REMOTE: 206.221.180.138:7777)
# Revision
2c23acabefcd08e24ccb3056741c5e37b0000177

# Description
While you guys are testing nu lights.

As a MoMMI at round start, turning on meson sight augment does not brighten visuals. Can still see other side of walls normally, just dark as fuck.

**Comment by DeityLink** [comment]
Duplicate of #30597
