### ISSUE TITLE
[Europa] Singulo shadows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30618]
(WEB REPORT BY: punishedpajeet REMOTE: 206.221.180.138:7777)
# Revision
2c23acabefcd08e24ccb3056741c5e37b0000177

# Description
The new Europa lights create a square around the singulo generator's location where the shadows abruptly cut off

# Steps to Reproduce
Go to the singulo generator (witnessed on Box)
# What you Expected
Shadows to exist around the singulo generator's location
# What Actually Happened
Strange shadowless box. When the singulo passes through it during a singuloose, you can see this very clearly as half the singulo is unlit and half is lit

**Comment by Kammerjunk** [comment]
the singulo should probably not be affected by this altogether
it's too imposing and too important a sight to hide

(also it probably shouldn't be affected by this in the first place cause every turf it's on is supposed to be space)
