### ISSUE TITLE
Wheelchairs now give their occupants the ability to levitate for a few seconds, then snap back onto them to deny them any hope of being able to move freely.

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#30626]
I don't know when this started happening when moving in a wheelchair but it looks incredibly jarring and not smooth whatsoever. I had no lag for it and others I LOOC'd said they saw it too.

This was not an issue yesterday, as far as I know.

**Comment by DeityLink** [comment]
Please give steps to reproduce

**Comment by BomberBro** [comment]
Step 1: Enter wheelchair
Step 2: Turn this on https://www.youtube.com/watch?v=ckM51xoTC2U
Step 3: Move wheelchair
Step 4: You now see what I mean by my issue title

**Comment by Kurfursten** [comment]
I first noticed the levitating on 8/28

**Comment by DeityLink** [comment]
I see the issue but it appears completely unrelated to #30573
