### ISSUE TITLE
Can't see after being transformed into a xenomorph

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30622]
(WEB REPORT BY: magicgarbage REMOTE: 206.221.180.138:7777)
# Revision
93431530b36f24b3a1bfd81c1c26af75c8754b36

# Description
Changed into a xenomorph, everything is black except lightswitches and speechbubbles
# Steps to Reproduce
Change from regular crew into a xenomorph or (possibly) a different mob with altered sight
# What you Expected
To not be blind
# What Actually Happened
Being blind

**Comment by DeityLink** [comment]
I should probably give them the same kind of dark visions I'm giving other mobs in #30620

Although in their case I think it's related to the meson bug #30597
