### ISSUE TITLE
Object Tab: Pick up item issue

### ISSUE THREAD

**Issue by TKJ96** [d3athrow/vgstation13#3062]
Been having this problem a lot recently. Right clicking works fine, but the object tab "Pick up" option is buggy. Looks like this http://i.imgur.com/6tavzaP.png

**Comment by clusterfack** [comment]
So you're saying you want it to filter out anchored items? That's pretty easy

**Comment by TKJ96** [comment]
It use to do that. Usually if I was over a locker it would ask me to pick up only the things in the locker. Now it's everything in the general area.

**Comment by d3athrow** [comment]
this was fixed
