### ISSUE TITLE
Light from lit objects appear to occupy inventory space

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#30637]
#### Description of issue
![image](https://user-images.githubusercontent.com/55976761/132538375-ad5b5831-4139-40b6-ab75-7807c73ecf91.png)
I observed this extra inventory row in my toolbelt when I stuffed my lit flashlight into it.
I took one other item out of my belt besides the flashlight and was back at two rows of 13 items, but I could not put that item back into my belt, as if it was full despite the available inventory slot.
This also happened with a lit welder, so I assume this is caused by the light itself.

#### Difference between expected and actual behavior
I didn't expect light to have a large volume.

#### Server revision

7575865e3fd3c543339f2c64eb61a1c0d2387e1a

**Comment by ShiftyRail** [comment]
Very funny
