### ISSUE TITLE
Holy water doesn't deconvert cultists or harm vampires when drank (Still hurts vampires when splashed on them)

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#3064]
After forcefeeding 1k units of holy water to people and dishing out as much brain damage in a cult round and seeing no deconversion message I think either it's not working or the method has changed yet again

**Comment by d3athrow** [comment]
Can't deconvert the starting cultists.

**Comment by Konater** [comment]
It is holy water in a drinking glass right now right?

**Comment by d3athrow** [comment]
Holywater in their system period has a 10% chance of deconversion.

**Comment by Konater** [comment]
I'm closing this for now but I swear I went through a water tank and a half or something and got nothing

**Comment by Konater** [comment]
Tried in a test environment with boxed and couldn't decult myself with holy water

**Comment by DrCelt** [comment]
ADMIN LOG: DrCelt/(Old Blind Blackburn) added holywater with 1.#INF units to Culshits (as Admin) 
He didn't convert.

**Comment by YakumoChen** [comment]
I thought you could decon starting cultists? I've had whole rounds ruined by shitcurity hunting down starting cult who didn't even manage to start anything.

Was this changed? iirc all cultists are supposed to be equal.

**Comment by ComicIronic** [comment]
Should -not- be possible now.

**Comment by Probe1** [comment]
Shouldn't there be some kind of message ala Rev that lets you know the deconversion failed because they were a starting cultist?

**Comment by Konater** [comment]
Issue might be with the holy water
