### ISSUE TITLE
Conversion ritual completed, no action on vitcim on shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30647]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
7575865e3fd3c543339f2c64eb61a1c0d2387e1a

# Description
On a moving shuttle, if the victim of a conversion in cult has to choose between accepting or not, it cancels out and the victim comes out as normal
# Steps to Reproduce
* Convert victim on shuttle
* Move it during or after conversion but before result (uknown where it happens)
# What you Expected
Converted or cuffed
# What Actually Happened
Nothing

**Comment by DeityLink** [comment]
Well yeah, moving the target interrupts the conversion ritual. The ritual is NOT over yet when the progress bar is filled up.
