### ISSUE TITLE
Every Modified Sight Overlay is Broken on Europa

### ISSUE THREAD

**Issue by DriftingSkies** [d3athrow/vgstation13#30640]
#### Description of issue
Benos, mesons, night vision, thermals, EVERYTHING is broken. It's nothing but pure darkness with them on.

#### What you expected
To fucking SEE!

#### What happened
OH GOD IT'S LOOSE.

**Comment by ShiftyRail** [comment]
Mesons worked last time I tried. The others did also but that was in an iteration long ago.

**Comment by DriftingSkies** [comment]
> Mesons worked last time I tried. The others did also but that was in an iteration long ago.

Very weird, my best guess is honestly byond being shitcode as per usual. Try it on 513 and 514 to see if it's got something to do with that

**Comment by Eneocho** [comment]
Do the nightmare vision goggles work?

**Comment by ShiftyRail** [comment]
Yes, they should now.
