### ISSUE TITLE
Unplayable Ping Caused by Europa Lights

### ISSUE THREAD

**Issue by Booperkin343435** [d3athrow/vgstation13#30650]
#### Description of issue
New lighting system and shadows cause terrible ping for me and possibly others. When I am on the station where there is lighting and shadows my ping is very bad and makes the game unplayable. It was even worse before I updated to the latest version of byond which I thought would fix the issue completely (it did not). Here are screenshots of my ping when I am on the station as a ghost and when I am far away from the station in the middle of space.
On station: https://gyazo.com/eb97f9c5ee1bdc03030fe433dd865eec
On station 2: https://gyazo.com/db39ea03fc0df9646092927764729ae6
Off station: https://gyazo.com/832b7d933e9cc5bdfd4e31721fc5740b

#### Steps to reproduce
Not sure I'm the only one I know of that has this issue and I don't know why exactly.

#### Length of time in which bug has been known to occur

This happened just today/tonight the first time I tried to play with these new shadows.

#### Server revision
Game: 7575865e3fd3c543339f2c64eb61a1c0d2387e1a

**Comment by west3436** [comment]
Europa Lights are no longer implemented.
