### ISSUE TITLE
sparks are a little too bright, especially when they stack together

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#30694]
sparks are unusually bright, and when several sparks are on the same tile they REALLY light it up, sometimes causing a bit of lag (though thats probably just because of my machine)
this is really noticable when you are beating the shit out of a borg, for instance

**Comment by ShiftyRail** [comment]
#30690 specifically deals with client-side lag originating from similar light sources in close vicinity.

**Comment by DeityLink** [comment]
does it reduce their brightness though?

**Comment by ShiftyRail** [comment]
No.

**Comment by gurfan** [comment]
On second thought this is less of an issue, the spark lifetime could probably be reduced but its not that bad.
