### ISSUE TITLE
Giftwrapping Beartraps

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#30706]
If you do this it allows you to nullspace a victim trapped in the beartrap, as they are atom locked to it (get put into the gift) and you can then open the gift.

**Comment by GreatBigFailure** [comment]
I should have been significantly more subtle about this.
To note though: The nullspace only happens with gift wrap. Package wrap doesn't nullspace. Probably something to do with the strange present mechanics.

**Comment by hacker-on-steroids** [comment]
closed by #36133
