### ISSUE TITLE
Box Robotics Surgery lightbulb has bad placement

### ISSUE THREAD

**Issue by YakumoChen** [d3athrow/vgstation13#3070]
Half the time I do debraining on Box I end up hitting the lightbulb and smashing it by accident because it's placed right over the surgery table. It's not vital for robotics but it is annoying and would be better if it were on the west wall or over the computer like how it is on meta.

**Comment by Probe1** [comment]
I've smashed that light so many fucking times.

**Comment by CptWad** [comment]
:+1:

**Comment by 9600bauds** [comment]
Issue fixed, can be closed now.
