### ISSUE TITLE
Please Just Do Away With Bunsen Fuel

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#30702]
Everyone chemheats with a lighter or welder

**Comment by boy2mantwicethefam** [comment]
Obviously the solution is to limit all chemical heating to bunsen burners

**Comment by Kurfursten** [comment]
I would be fine with that if in exchange bunsens don't require fuel anymore -- seems like a reasonable trade

**Comment by DriftingSkies** [comment]
just buff burners, simple solution

**Comment by Armadingus** [comment]
Map burners out and replace with the laser directed heater.

**Comment by Kurfursten** [comment]
I like the aesthetic of bunsens, why not just make them not a pain in the ass to use?

No amount of "buff" will make it better to have to hunt down fuel, go for that clunky port toggle, feed it, toggle again, toggle on, stick on your beaker, and wait. Even if it heated a lot faster, you can just slam your zippo on a beaker ten times and be done instantly, no fuss.

**Comment by Armadingus** [comment]
Not really immersive to have a burner without fuel, it'll be like the sinks that can be grounded anywhere.
What if you could connect the burner to a chemistry dispenser and have it burn freely in exchange for spending power units?

**Comment by Kurfursten** [comment]
Yeah, sinks can be grounded everywhere, and nobody's lining up to add water pipes.

You could say the bunsen fuel is synthesized the same way the chem dispenser synths chemicals. I mean, the laser scalpel doesn't have an external fuel source.
