### ISSUE TITLE
OH GOD MY FRAMES, WHAT DID YOU MERGE! (Europa Lights)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30714]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
f4e444c7e51eb16d00704d3d8afa7fe0a69add56

# Description
IT HURTS SO MUCH OH GOD MY FUCKING FRAMES
# Steps to Reproduce
Exist, have low end toaster, profit.
# What you Expected
To have stable framrate.
# What Actually Happened
OH GOD I'M HAVING FLASHBACKS TO MY HIGHSCHOOL POWERPOINT PRESENTATIONS!

**Comment by kernikov** [comment]
Issue may be specific to Waystation, and how many variable shadows are going on.
Ex. 
![image](https://user-images.githubusercontent.com/5549060/132998024-451ddda8-ac5c-4377-ab68-81eb19ba1f62.png)

**Comment by DriftingSkies** [comment]
> Issue may be specific to Waystation, and how many variable shadows are going on.
> Ex.
> ![image](https://user-images.githubusercontent.com/5549060/132998024-451ddda8-ac5c-4377-ab68-81eb19ba1f62.png)

Sounds about right, I haven't had an issue before but this round in specific just ass fucked my frame rate

**Comment by ShiftyRail** [comment]
😔

**Comment by DriftingSkies** [comment]
My FRAMES are STILL BAD WTF WTF

**Comment by gurfan** [comment]
This is happening on roid too.

**Comment by APCUnlocked** [comment]
I too had shit framerates in Waystation, way worse than in roid. Updating to the server's byond version helped but I still keep having random crashes I didn't have before evropa lights. Bls help.

**Comment by SootyBear42** [comment]
Did something new get merged because Europa was shit but now it's even worse for me.

**Comment by ShiftyRail** [comment]
Only new thing that got merged is #30687. I can disable it if that's wanted.

**Comment by gurfan** [comment]
everything is still horrible even after #30719

**Comment by ShiftyRail** [comment]
You probably need to clear your cache a bit more often than usual, I guess.

Can't work on this tonight, sorry.

**Comment by DriftingSkies** [comment]
It keeps on getting worse round by round, shit's wild. I love Europa but holy shit the framerates have been so inconsistent it's starting to make me hate it.

**Comment by SootyBear42** [comment]
I don't think it looks better compared to goonlights, and the lag only makes them seem worse.

**Comment by SootyBear42** [comment]
Jesus christ sometimes it's horrendous.

**Comment by ShiftyRail** [comment]
Is it still a thing after disabling all the post-processing and all that?

**Comment by DriftingSkies** [comment]
> Is it still a thing after disabling all the post-processing and all that?

A lot better, definitely shitcode on Lummox's part. Pairing that with whatever the fuck was corrupted in my BYOND.

**Comment by nervere** [comment]
Europa has had two years of development since this and framerate doesn't seem to be an issue anymore.
