### ISSUE TITLE
Implants Breaking after surgery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30729]
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
a8b0b98965c75ef83e623666d7513b7fa5c58ef0

# Description
Certain implants break after surgery

# Steps to Reproduce
>Inject person with Freedom (and potentially other) impant
>Perform surgery on their chest
>see if implant still works
# What you Expected
The implant would work as normal, uncuffing me 

# What Actually Happened
During a traitor round, I implanted myself with a freedom and uplink implant. The CMO performed surgery on my chest and afterwards I was unable to use my freedom implant.

**Comment by DriftingSkies** [comment]
Are you sure the implants weren't removed? Body scanners show implants of any sort.

**Comment by SonixApache** [comment]
probably not related to the implant fizzle thing i did so don't blame me just yet
more info would be helpful (exact code phrase, exact surgery type and damage at the time of surgery, etc)
