### ISSUE TITLE
Tackling's TOO Busted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30720]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
d27bd30f48f7eea7455126d4a2dd57b0ba716e5a

# Description
OH NONONONONO
# Steps to Reproduce
HOLY SHIT IT'S TOO POWERFUL
# What you Expected
FUCK MAN, NOT THIS SHIT!
# What Actually Happened
GOD IT'S SO BROKEN!

**Comment by GreatBigFailure** [comment]
Extremely helpful issue.

**Comment by west3436** [comment]
Low quality issue report
