### ISSUE TITLE
turrets set to lethal don't fire

### ISSUE THREAD

**Issue by YakumoChen** [d3athrow/vgstation13#3072]
After testing some stuff after a vampire round I've found that turrets set to lethal simply don't fire at you after you jaunt. Stuns will fire at you but once set to lethal they simply stop working.

I'm not sure if this only begins after a jaunt, but I tried lots of things short of starting a new game to get them to fire at me, including mindswapping into another person and walking in, and resetting the turrets, toggling lethal and stun, turning them off and on, etc. Lasers wouldn't shoot me.

**Comment by YakumoChen** [comment]
this only applies to the standard roundstart turrets around the AI core/upload, built turrets function as they should.

**Comment by CptWad** [comment]
Hold on theres already an issue for it and its right under this one.
