### ISSUE TITLE
[Feature Request] Crumbs should only appear if people eat on harm intent.

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#30738]
Contrary to popular belief, most people can eat a donut or apple without mashing it into their face and getting half of it on the floor.

Pic related, least dirty floor at the kitchen counter.
![crumbs1](https://user-images.githubusercontent.com/51391726/133023829-ab56e5a7-debe-452d-a80f-c050bd34367f.PNG)

**Comment by Servalfang** [comment]
snow

**Comment by PavelCIA** [comment]
Crumbs are stupid and annoying and I wouldn't miss them if they got removed.
Maybe make them forcefeed-only since you're literally pushing food down someone's throat.
