### ISSUE TITLE
Sales Vendor Off Sprite Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30733]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
a8b0b98965c75ef83e623666d7513b7fa5c58ef0

# Description
When unwrenching and dragging the sales vendor after the new sprite update, moving it will cause it to vanish (no sprite).
# Steps to Reproduce
Unwrench the sales vendor, move it around.
# What you Expected
See the sales vendor I am dragging with me
# What Actually Happened
It vanished when dragged!

**Comment by Kurfursten** [comment]
@gurfan

**Comment by gurfan** [comment]
whoops
