### ISSUE TITLE
Europa Lights Hates AMD Cards (Probably)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30735]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
a8b0b98965c75ef83e623666d7513b7fa5c58ef0

# Description
I've been gathering intel and everyone that's got shit frames has an AMD card. I believe there's something to do with how AMD drivers work or the cards themselves. Needs a lot more testing.
# Steps to Reproduce
Have AMD card, try Europa, profit.
# What you Expected
You know the drill.
# What Actually Happened
Oh no.

**Comment by DriftingSkies** [comment]
![image](https://user-images.githubusercontent.com/79872239/133011429-536b2cc7-bf1c-4259-8cc2-ddb388264033.png)
Got 5-8 FPS while observing with lights enabled and a solid 30 with darkness disabled.
CPU: Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz, 2501 Mhz, 2 Core(s), 4 Logical Processor(s)
Memory: 6.00 GB
VRAM: 8.00 GB
GPU: AMD Radeon HD 7400M Series

**Comment by DriftingSkies** [comment]
Another trend I've noticed is that on every map EXCEPT Box performance has been dogshit. No clue why, something broke something, and it's probably got something to do with drivers.

**Comment by Exxion** [comment]
If it's hardware-specific, I doubt there's anything we can do about it besides tell Lummox.
Well, other than turning the post-processing back off

**Comment by TGFH** [comment]
>  I doubt there's anything we can do about it

The answer is simple. We kill Europalights.

I have an R9 390 card and I'm also getting terrible performance. PJB's tool is saying that I'm averaging like 23 fps in lit areas with dips down to 16 fps at times. In areas with minimal lighting I'm getting around 40~ and in space or in totally dark areas I get 100~ fps.

**Comment by west3436** [comment]
Europa Lights are neither currently nor planned to be implemented.
