### ISSUE TITLE
Framerate's Still Not The Best (Europa)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30744]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
f96b42adf0e2b330843a2cdea696f45fefdd2b50

# Description
Once again I complain about my FPS, although not as bad as it was. Yet still bad. 
# Steps to Reproduce
Be me, exist on ss13, have terrible framerate, profit.
# What you Expected
I'm going insane I just want to play the game.
# What Actually Happened
Slideshow but not as bad as before.

**Comment by ShiftyRail** [comment]
Are you willing to hold on until 1567 is released so we see if Lummox unfucks his shit ?
Also - obligatory - when was the last time you cleared your cache ?

**Comment by DriftingSkies** [comment]
> Are you willing to hold on until 1567 is released so we see if Lummox unfucks his shit ?
> Also - obligatory - when was the last time you cleared your cache ?

Cleared my cache as soon as I started getting frame drops, didn't help very much. I'm fine with waiting a little bit longer but I am getting slightly tired of Lummox's shitcode preventing me from playing the game

**Comment by DriftingSkies** [comment]
> Are you willing to hold on until 1567 is released so we see if Lummox unfucks his shit ?
> Also - obligatory - when was the last time you cleared your cache ?

Did probably the stupidest thing ever of completely uninstalling and reinstalling BYOND so we'll see how this one goes

**Comment by DriftingSkies** [comment]
> > Are you willing to hold on until 1567 is released so we see if Lummox unfucks his shit ?
> > Also - obligatory - when was the last time you cleared your cache ?
> 
> Cleared my cache as soon as I started getting frame drops, didn't help very much. I'm fine with waiting a little bit longer but I am getting slightly tired of Lummox's shitcode preventing me from playing the game

It fucking worked.

**Comment by ShiftyRail** [comment]
1001% sure this is sprite corruption at work here.
Thanks Lummox. Very cool.

**Comment by Eneocho** [comment]
I also get notable lagspikes whenever I approach anywhere with more than a few lights, though that can be bypassed by finding and wearing some mesons.

**Comment by west3436** [comment]
Europa Lights are neither currently nor planned to be implemented.
