### ISSUE TITLE
Ventcrawling as a borer causes hard client crash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30745]
(WEB REPORT BY: drawsstuff REMOTE: 206.221.180.138:7777)
# Revision
f96b42adf0e2b330843a2cdea696f45fefdd2b50

# Description
I have no idea why but considering it happened twice in a row within a 1 minute period says something
# Steps to Reproduce
1. climb into a vent as a slug
2. never gonna break my stride, no body's gonna slow me down, oh no, ive got to keep on moving
# What you Expected
smooth sailing slug
# What Actually Happened
screeching halt

**Comment by drawsstuff** [comment]
just got another one

**Comment by drawsstuff** [comment]
and another one, gonna say this is a frequent issue

**Comment by drawsstuff** [comment]
and another one. game is unplayable now and logins result in an instant crash

**Comment by DamianX** [comment]
byond version?

**Comment by drawsstuff** [comment]
513.1505

**Comment by DamianX** [comment]
514.1566 is the only supported version at the moment

**Comment by Exxion** [comment]
1505? Holy shit that's old. It's remarkable that it worked even before the server was updated.
