### ISSUE TITLE
[Feature Request] Unify formatting for PDA Medical Scanner and Health Analyzer

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3075]
It looks like the PDA function for med-u cartridges didn't get brought in line with health analyzers whenever they were given a gloss over.  Have its Key/Damage specifics color coded, basically just copy and paste it from health analyzer to the PDA Medical Scanner.

![capture](https://cloud.githubusercontent.com/assets/8550416/6240829/ce041b52-b6e1-11e4-912e-df53ada91276.JPG)

**Comment by ComicIronic** [comment]
Ideally they'd do what the Device Analyzer does and just use an inbuilt scanner instead of copying code.
