### ISSUE TITLE
Windoors Infinite Cable Coil

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30754]
(WEB REPORT BY: rabbit2rabbit REMOTE: 206.221.180.138:7777)
# Revision
b53fc7b7bdd9c2e2779003828dfd6d15bc4dd3eb

# Description
You can farm infinite cable coils from Windoors while deconstructing them.

# Steps to Reproduce
Get a windoor in deconstruction to the wirecutters stage
Absolutely beat the living hell out of your mouse, clicking as fast as you can on the windoor with your wirecutters
Wait for all the progress bars to complete
Easy ~100 cable coil if you're good at fingering, more if you autoclick at speed

# What you Expected
the progress bar to be interrupted when the state changes

# What Actually Happened
blasting windoors at mach 8 for the bant

**Comment by Dacendeth** [comment]
This applies to basically every deconstruction step on machines where it's a progress bar to remove cables.
