### ISSUE TITLE
Magboots are STILL broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30752]
(WEB REPORT BY: dickwrath REMOTE: 206.221.180.138:7777)
# Revision
da878f52714b1e2ec22539f462ec24b03d735435

# Description
Magboots don't grip the surface anymore. This was a problem a little while back and still perpetuates. It's difficult to do mining, engineering, or even just getting back into the station from space when ZAS keeps knocking me on my ass.
# Steps to Reproduce
Try to turn on magboots and walk into a depressurised area.
# What you Expected
The magboots to make me not fall over
# What Actually Happened
Me falling over and getting massive ouchies

**Comment by SonixApache** [comment]
#30353

**Comment by Exxion** [comment]
I can definitely reproduce being *moved* by airflow while wearing enabled magboots, but I cannot reproduce being knocked down with them.

**Comment by Armadingus** [comment]
It happens if you get knocked into an object while that movement happens. For example if you are trying to drag a dense object behind you into an external airlock, you will be knocked into that object by airflow and get stunned.

**Comment by Exxion** [comment]
Ah, yeah, that would do it. Apparently being thrown into something by airflow doesn't check anything about whether or not you're airflow stunnable, and just directly stuns you.
