### ISSUE TITLE
The nearsightedness overlay doesn't show up anymore

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#30769]
1. Spawn as a nearsighted human
2. Remove your prescription glasses
3. Observe that you can see the world just as well, without any "grate" effect over the edge of the screen.

**Comment by Eneocho** [comment]
I tried it, I did get the "grate" overlay. But when I quickly equipped-removed the glasses, it bugged out and lost the overlay when not wearing em.
