### ISSUE TITLE
[Feature Loss] Power cables display as white when looked at with the alt click tab

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3078]
Interestingly when you clip one, its the proper color!  The straight North/South wire was placed after the round started and should be cyan, and the curved E/N one was there at roundstart and should be red.  Neither are.  So that's weird.  

I've also noticed in the past that blood on bloody items appears white when looked at in the little alt click menu.  Looks like someone splooged all over a gun for example.

![ss 2015-02-17 at 09 42 33](https://cloud.githubusercontent.com/assets/8550416/6242185/2d073916-b6f8-11e4-9e8c-3619519819a0.png)

**Comment by ComicIronic** [comment]
Alt click isn't applying Byond's color var.

**Comment by Probe1** [comment]
<D3athrow> probe1 pretty sure because the color is an overlay or something and alt click doesnt show overlays
 <D3athrow> just the base icon

**Comment by ComicIronic** [comment]
But humans are made of overlays and all those show up in alt-click.

**Comment by Probe1** [comment]
COLORS OR RIOT

**Comment by Probe1** [comment]
RIOT!

**Comment by ComicIronic** [comment]
Did you report it to the Byond staff?

**Comment by Probe1** [comment]
@ComicIronic I have no idea where to report this to byond staff or how I should describe it other than it being an overlay issue or something.  Please supply a link to the appropriate forum and I will try.

**Comment by ComicIronic** [comment]
Well, turns out there is a bug report for it already.
http://www.byond.com/forum/?post=1743314&hl=color
They might be working on a fix, but this is otherwise an engine issue.
