### ISSUE TITLE
mouse keeps flickering the 'loading' icon after using tgui security cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30787]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
d62852d844971f6bbecb0dcfd5d02dad14d07f54

I feel like the UI is still open in the background (even after closing it) and sending/receiving data but I'm not sure. I don't know if this is happening for everone else

**Comment by DamianX** [comment]
It's happening to me on the server consistently, but never locally.
