### ISSUE TITLE
camera console doesnt work with mesons enabled

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30786]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
d62852d844971f6bbecb0dcfd5d02dad14d07f54

the camera view shows up all black, the only things you can see are the little holomap overlays

**Comment by gurfan** [comment]
space tiles also appear solid black regardless

**Comment by DamianX** [comment]
I can tell you what the camera computer is doing but I can't quite decipher what mesons are doing. @ShiftyRail @DeityLink

**Comment by gurfan** [comment]
reverting europa lights seems to have fixed this @DamianX
