### ISSUE TITLE
Typo on the Phazon damage threshold text.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30788]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
"Greyshit McTider hits Phazon. Nothing happens"
It's missing a period.

**Comment by Eneocho** [comment]
Apparently it isn't anymore and could be closed @nervere @exxion.

**Comment by nervere** [comment]
No longer an issue.
