### ISSUE TITLE
Trader Mecha Graveyard Disk Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30796]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
b575a71b92add50e00eb6a85ae1b02d0ac9ed2e4

# Description
It don't work, or it don't spawn.
# Steps to Reproduce
Buy the disk, try and go there for some mech scrap, profit.
# What you Expected
To run a slavage broker gimmick.
# What Actually Happened
ERROR: Unable to read coordinates from disk (unknown encryption key

**Comment by Kurfursten** [comment]
Doesn't work on trade shuttle
