### ISSUE TITLE
Trade Window Language Barriers for Recruited Friends

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30799]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
b575a71b92add50e00eb6a85ae1b02d0ac9ed2e4

# Description
Human's are left in the dark by the table's fancy words! There should be something to remedy this!
# Steps to Reproduce
Get a human friend, have them become a trader at the window via the PROCESS TM, have them talk to the window, profit!
# What you Expected
Them to speak a different language or the human to learn pidgin!
# What Actually Happened
The didn't!

**Comment by Servalfang** [comment]
tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband tradeband

**Comment by Kurfursten** [comment]
I am going to make a change so that new traders get a joining gift. Vox and mushrooms will get the normal trader gear (coin, thermos, and donk pockets), everyone else gets a dictionary.
