### ISSUE TITLE
Head and eye wear for vox cancel each other out

### ISSUE THREAD

**Issue by Uso15** [d3athrow/vgstation13#3079]
When wearing different pieces of headgear (goggles, mask, welding helmet, etc.) the sprites for it cancel each other out. toggle the welding helmet and your mask is gone, toggle goggles and they disappear over your eyes.
![screenshot 2015-02-17 23 00 31](https://cloud.githubusercontent.com/assets/8187016/6242655/139c91a0-b6f9-11e4-841b-08c6f0bf0018.png)

**Comment by ririchiyo** [comment]
The only issue I was able to reproduce for this was if a medical mask was off and you used a welding helmet the now down medical mask was displaced which I don't believe is a bug.
