### ISSUE TITLE
Explosive implant not triggering on *deathgasp for Nuklear Operative.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30807]
(WEB REPORT BY: cmdrstupid REMOTE: 206.221.180.138:7777)
# Revision
b575a71b92add50e00eb6a85ae1b02d0ac9ed2e4

# Description
As a roundstart operative, got tased and cuffed, and eimplant didn't activate on *deathgasp. This was using a macro set to *deathgasp. Tried while stunned, tried while cuffed and being pulled, tried cuffed and not pulled, tried while in crit.

# Steps to Reproduce

# What you Expected
A borg getting the bing bong bannerino for dragging a bomb into a crowded area.

# What Actually Happened
A flukie spamming *siezes up and falls limp* like an idiot.

**Comment by DamianX** [comment]
I'm on it

**Comment by nuklearcellphoneg** [comment]
based

**Comment by DamianX** [comment]
based on what?

**Comment by nuklearcellphoneg** [comment]
sono selvaggio,

sono nuklear

**Comment by nuklearcellphoneg** [comment]
https://youtu.be/x6fpSiE953w
