### ISSUE TITLE
[Discussion] What plant/food/drink should be added?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3081]
It was brought up in OOC a few hours ago and it might as well get posted here where it won't disappear.

Service already has a ton of recipes but it's not like they lag the server so no harm in posting a few more right?  If you have any ideas of things you think are missing and should be added post em.  

Off the top of my head we're strangely missing garlic and onions.  Unforgivable.  Quesadillas and (non-toxic) burritos should make an appearance.

**Comment by AutismSpider** [comment]
We lack peanuts and fun stuff we could do with them.
![hot nuts](https://cloud.githubusercontent.com/assets/10268342/6243465/ac0fc020-b707-11e4-937f-0cf162aba927.png)

Some type of food made with the bee honey.

**Comment by CptWad** [comment]
Peanuts would ruin one of the older item descriptions for what I think was the jelly sandwitch.

We need more stuff to do with white beets. They are pretty much worthless.

I kinda want trees. Or some other plants that you can use that don't die but instead sit there and look pretty. The potted plants are nice but when you make a forest in maint they do not look good.

We could try some more colonial plants like coffee, tea, tobacco and cotton for fun times.

I had an idea earlier about expanding what you can do with wood planks and maybe make a carpenter pseudo job like a barber. Assistants can go run over and make wood shit like a boat which they can use like a ghetto space pod by attaching fire extinguishers etc. 

We could add various nuts, not just peanuts.

That's all I can spout atm.

**Comment by 9600bauds** [comment]
We could definitely use coffee and tea plants. They already exist at /tg/station, maybe we can borrow the sprites.
There's also unused ghost chili in the code, that might be cool.

**Comment by Arthurdentist** [comment]
I was thinking of adding some curries. Could maybe use the unused ghost pepper in one.

**Comment by SkowronX** [comment]
Oh here's a ghost pepper if anyone wants to use it.
![ghostchili](https://cloud.githubusercontent.com/assets/7810719/6250133/7d26bab2-b751-11e4-968b-a45a8ba35bcd.png)

**Comment by CptWad** [comment]
I recall ghost peppers in our code and they were sprited as just ghostly looking peppers and they had twice as much capsaisin in them or something.

More ideas:
Sweet potatoes into Sweet potatoe fries :sweet_potato: 
Onions into onion rings etc 
Pineapples :pineapple: 
Peaches :peach: 
We should also be able to make various oils. IE peanut, palm (its own plant could be one of the decorative trees I talked about) and soy oils.
Olives
Rubber trees? More fun stuff for chemist?
Sunflower seeds to make all sorts of stuff (not package rather a pile of them)
cucumbers
Coconuts to make bikini's out of or fancy drinks at bartenders. 

Oh more bartender drink ideas :cocktail: 
>Blue Hawaiian
2 parts pineapple juice
1 part rum
1 part  lime juice
1 part Coconut cream

>Kamikaze
3 parts vodka
1 lime juice
1 parts orange juice

>Bahia Breeze
3 parts pineapple juice
2 parts tequila 

>Peaches and cream
2 parts peach juice
1 part pineapple juice
2 part coconut cream
1 part rum
1 part ice

All for now. :beers:

**Comment by Killette2** [comment]
All this and nobody's said peppercorn? There is no way to get pepper after you use the bar's supply.

**Comment by Probe1** [comment]
That's a bug.  Grinding any seed should get you pepper.  https://github.com/d3athrow/vgstation13/issues/2794  Speaking of which it's time to pester someone about that.

**Comment by 9600bauds** [comment]
It'd be really nice to have an actual use for honey, as it is right now it doesn't even provide nutriment when eaten. Maybe some foods like honeyed ham, honey on toast, maybe a Queen Bee cake that uses the currently-worthless honeycombs? Could even add small amounts of tricord to honeyed foods so it's actually worth it to raise bees, at the moment they're outclassed by a farmbot.

**Comment by Killette2** [comment]
I agree with more uses for honey, as you risk your life to get it and the only use it has is making honeycomb cereal using the cereal machine for kicks as a reference to the real cereal. I would also note that grapes and watermelons have not a single recipe, and are only used for blending/juicing.

**Comment by CptWad** [comment]
>No watermelon recipies
Re add george melons when?

**Comment by AutismSpider** [comment]
George melons

Watermelon+Faggot
                 or
Watermelon+Dindu Muffin

**Comment by CptWad** [comment]
![hqdefault](https://cloud.githubusercontent.com/assets/3959840/6313639/ff99f632-b96b-11e4-8790-95f3c0d15629.jpg)

**Comment by Kurfursten** [comment]
Adding recipes is super, super easy to code. If you compile a list of new recipes, I'll code them for a PR.

Please come up with some sort of Tatortots. Ideally, cooked with a syndicate item.

**Comment by Killette2** [comment]
Bag of dicks

3 sausages + plastic bag

Now we can tell people to go eat a bag of dicks.

**Comment by AutismSpider** [comment]
Some thing like this?
![cookie dicks](https://cloud.githubusercontent.com/assets/10268342/6543809/aa0e78ae-c4f2-11e4-9f76-3f321e29d15a.jpg)

**Comment by Killette2** [comment]
Yes but more sausagy

**Comment by Probe1** [comment]
Curries were added.  Everything else is open.

**Comment by 9600bauds** [comment]
We need lasagna
