### ISSUE TITLE
Waystation's HOP desk windoors are on backwards

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30818]
(WEB REPORT BY: lisyamyata REMOTE: 206.221.180.138:7777)
# Revision
b575a71b92add50e00eb6a85ae1b02d0ac9ed2e4

# Description
The side that is meant to be nearest to hop is on the other side and means the hop has to open it for everyone
# Steps to Reproduce
Go to it without hop access and try to open it
# What you Expected
Useable HOP desk
# What Actually Happened
Non-useable HOP desk

**Comment by kernikov** [comment]
Fixed by #30834 @DeityLink
