### ISSUE TITLE
Feature Request: Heads "Automatically" Prioritized

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#30816]
As HoP I loved to prioritize slots, as a latejoiner, I love to join priority slots

What I don't love is the dilemma of what to mark as priority when I have an empty department. Consider medbay:
>It would be great to have a CMO - but people are scared of responsibility and more likely to take it if I just prio MD
>But if someone WOULD have played CMO, they might go MD now for the bonus

Basically if I mark anything in the department like MD or Chemist or Virologist, a CMO should get promoted to priority automatically.
Same for atmos tech/eng promoting CE, and so forth

**Comment by Servalfang** [comment]
agree

**Comment by GreatBigFailure** [comment]
A "head slot" for priorities would also work. You'd have the current 3 but also a single freebie for head roles. I think that would punctuate the necessity more to late-joiners too.

**Comment by Eneocho** [comment]
This is a thing now @Kurfursten. Should be closed.
