### ISSUE TITLE
Can't put grabbed person on table if windoor is on the same tile

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#30822]
#30567 did this

> Admin grabs the unknown passively!
> 
> Admin has grabbed the unknown aggressively (now hands)!
> 
> Research and Development Desk prevents you from dragging the unknown on top of the reinforced table

**Comment by DeityLink** [comment]
😏
just as intended

**Comment by Exxion** [comment]
Bro just use `Cross()`
