### ISSUE TITLE
freedom implants do not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30839]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
1f610026035b3f23b76127ae4537ce7e1624b81f

# Description
they don't work
# Steps to Reproduce
try em out none of the actions work
# What you Expected
to get outta my cuffs
# What Actually Happened
nothing

**Comment by Kurfursten** [comment]
@DamianX
