### ISSUE TITLE
Revolutionary Squad ruleset always fails due to a lack of eligible players

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30836]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
1f610026035b3f23b76127ae4537ce7e1624b81f

ADMIN LOG: kernikov/(David Hawkings wheelchair) executed the Revolutionary Squad ruleset.

ADMIN LOG: DYNAMIC MODE: The ruleset couldn't be executed due to lack of eligible players.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DeityLink** [comment]
This error can happen if there's already a rev faction, or there are no living heads of staff. Can you confirm that neither of those cases  happened that round?

**Comment by kernikov** [comment]
There was a rev faction existing, I figured it would just add reinforcements.

**Comment by DeityLink** [comment]
Might need to adjust the error message then to be a bit more general.
