### ISSUE TITLE
Greytide implants do nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30855]
(WEB REPORT BY: dackjaniels REMOTE: 206.221.180.138:7777)
# Revision
78b90e05228d9deb04cfc7d9d21ce0d343393889

# Description
Greytide implants immediately fizzle out after injecting them. Round end screen shows the individual as a previous follower, as if they had the implant removed.
# Steps to Reproduce
Implant someone with a greytide injector
# What you Expected
To have a friend participate in greytiding shenanigans
# What Actually Happened
Said friend immediately turned state and tried to get me sent to the gulag where Vladislav would increase the diameter of my asshole

**Comment by Kurfursten** [comment]
@DamianX

**Comment by Eneocho** [comment]
There was also one guy on the thread that was complaining about the freedom implants not working so it's probably a global implant thing.
