### ISSUE TITLE
Ghosts will stop haunting if the haunted guy goes through a portal

### ISSUE THREAD

**Issue by DamianX** [d3athrow/vgstation13#30854]
@DeityLink #29978 maybe?

**Comment by DeityLink** [comment]
Now that you mention it is completely because of that, since haunting ghosts are anchored. I had already assigned the issue to myself a while ago but now I know how to fix it, I'll handle it tonight.

**Comment by DeityLink** [comment]
Duplicate of #30352

**Comment by DeityLink** [comment]
Wait actually no, it's something else
