### ISSUE TITLE
Somatoray doesn't cause plant subspecies mutations

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#3085]
Zapping a plant with the somatoray should be equivalent to using 1u of unstable mutagen, but even if you irradiate it to death you'll never get a subspecies shift. Yield and other mutations seem to work, though.

**Comment by 9600bauds** [comment]
To add onto this: Somatoray still works like the old mutation code, meaning it's instantaneous. You can unload the gun onto your tomatoes to get ~2-3 mutations without having to wait for it to mutate each time or worrying about it becoming blood tomatoes.

**Comment by Probe1** [comment]
It just very, very rarely mutates into a new plant.  It's possible, but not worthwhile.  Even growing another plant to grind into radium is more worthwhile than the floral snoreatory.
