### ISSUE TITLE
Cable coil color

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3087]
The red cable coil is the same color as the insulated pipes, makes it difficult to work with.

Why was the black border even removed?

**Comment by ComicIronic** [comment]
![Is this really too hard](http://puu.sh/g2fE7/ce2fcc8cb3.png)
Doesn't seem like a massive issue to me. Plenty visible.

**Comment by frangi** [comment]
No I meant the power cable itself, sorry for the confusion

**Comment by frangi** [comment]
To be clear, the outline on the power cables is gone now, I'd like it to come back.
