### ISSUE TITLE
[Feature Req] Ability to initiate crew transfer votes from the communication console

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#3088]
Because "crew do you guys want to leave now" is too common

**Comment by Killette2** [comment]
But should the dead be able to vote for this? That is the question

**Comment by Konater** [comment]
If there are enough dead people wanting a restart the round should be ending anyway

**Comment by Cisrox** [comment]
~~Hasn't been added, but I believe this is closeable.~~

**Comment by PJB3005** [comment]
@Cisrox oh fuck off, why would it be closable if it hasn't been added.

**Comment by Cisrox** [comment]
because its a terrible idea

**Comment by PJB3005** [comment]
@Cisrox that's your opinion, personally I think this is a good idea.

**Comment by SECBATON-GRIFFON** [comment]
we can do this with PDA polls now, which is the closest possible way to have done this
