### ISSUE TITLE
DNA Lock Didn't Work

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#30887]
> Leta Pavlov says, "Dna lock that for sure"

> You feel a prick as the needle takes your DNA sample.

Soon:
> Michael Miller says, "This should have been DNA locked"

Expected behavior: mech doesn't get stolen while fixing telecoms

**Comment by DeityLink** [comment]
Might look into it since I've been dealing with so much DNA business lately.

**Comment by DeityLink** [comment]
Ok so.. we have a problem, everyone seems to have the exact same DNA lol, I guess ready_dna() is called before the mob's name is set or something. (Also this doesn't solve the problem of two spessmen with the same name ending up with the same DNA, I'll see if I can change the way it generates)
