### ISSUE TITLE
Genetics output same name for changed monkeymen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30882]
(WEB REPORT BY: locese REMOTE: 206.221.180.138:7777)
# Revision
446a29e3ef34e44f8349e121c91ec0fdc860f1ce

# Description
Monkeymen that get UI+UE from injector always have the same name
# Steps to Reproduce
Get monkey, humanize, give it someone's UI+UE, they have a different name to one in UI+UE
# What you Expected
to have my own copy
# What Actually Happened
some Horatio Summy

**Comment by ghost** [comment]
horatio summy

**Comment by Eneocho** [comment]
The UI+UE copies the name and appearance. You wanted the SE.

**Comment by DeityLink** [comment]
Working as intended. If you want to change an appearance without changing the name you might have to use individual UI block injectors. (don't know if full UI injector also changes the name but I assume it does)
