### ISSUE TITLE
The unloading machine in the mining base is facing the wrong way

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30897]
(WEB REPORT BY: niftyryanyan REMOTE: 206.221.180.138:7777)
# Revision
e69b2cecf42fbc56fa8e0374bbfa7c963745c8de

# Description
You can't use it beacuse its facing the wrong way.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by kernikov** [comment]
Based on the time, I think this was Asteroid Station.
