### ISSUE TITLE
No Guns Spell isn't on the spellbook.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#30890]
#### Description of issue
Title. I don't remember it having been removed, so reporting it as a [bugfix].
#### Difference between expected and actual behavior
Expected to be able to exchange the gun using for extra magic.
#### Steps to reproduce
Use spellbook.
Can't find the no-guns spell.
#### Length of time in which bug has been known to occur
Haven't rolled Wiz for about a month, but last time I played it was available.

**Comment by Eneocho** [comment]
Tested on latest localhost and it is? Dunno what the fuck is going on.

**Comment by SonixApache** [comment]
raging mages, probably
or maybe it's one of those "only roundstart wizards :)))" things
