### ISSUE TITLE
Decoration Crates

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#3090]
Would it be possible to make some sort of 'interior decorating' crate for cargo? I feel like it would be great if it were easier to get carpet, wood, lamps, etc. without going through tons of botany RNG stuff.

Also it might keep people from absolutely demolishing the library/chapel/dorms/bar for whatever carpet and wood they can get.

Not entirely sure how to label this as a feature request, so bear with me for a second while I bumble my way through github

**Comment by ComicIronic** [comment]
Fun fact about Github, you can't label stuff unless you have repo access.

:+1: idea, though.

**Comment by Unfit** [comment]
I feel like there should be a way to craft carpets instead, and maybe other clothing as well (think jumpsuits with customisable sprites, names and descriptions). Maybe a machine akin to autolathe which accepts fabric (which in turn is made in botany or ordered or idk) and outputs carpet/clothes?

**Comment by NigglyWiggly** [comment]
I was pretty sure you could mutate grass to grow carpet, but I might be thinking of another server

**Comment by Probe1** [comment]
I think you're thinking of another server.  You can't grow or munch carpet on vg..  

Add that to a cargo crate!

**Comment by NigglyWiggly** [comment]
By botany RNG, I meant the whole 'mutant grass=carpet' thing that isn't true, and as far as lamps, I was thinking specifically the ones that you find in the medbay lobby and library, not the slime lamps

**Comment by Probe1** [comment]
ah the librarian lamps.  you're right on that one there's no way to get them.

**Comment by Probe1** [comment]
well it looks like everything *except* lamps got added.  should we make a librarian crate with toner and lamps and other junk?

**Comment by NigglyWiggly** [comment]
Throw a Kickstool crab in there too for good measure
