### ISSUE TITLE
glass floors are cursed and seem to always be on the top layer even above the ui

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30903]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
e69b2cecf42fbc56fa8e0374bbfa7c963745c8de

# Description
what
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by kernikov** [comment]
@DeityLink duplicate of #30888
