### ISSUE TITLE
Asteroid Station SME scrubbers not assigned to air alarm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30929]
(WEB REPORT BY: higgsbonbon REMOTE: 206.221.180.138:7777)
# Revision
cdd473d6aeebd6c859e68ddb086fd667c71a2fe0

# Description
THE SME chamber's scrubbers aren't assigned to the room's air alarm and therefore cannot be shut off, making proper setup impossible
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
Newbie engineers...
