### ISSUE TITLE
Roid Medbay Windoor Access Is Borked for Brig Medics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30928]
(WEB REPORT BY: driftingskies REMOTE: 206.221.180.138:7777)
# Revision
cdd473d6aeebd6c859e68ddb086fd667c71a2fe0

# Description
It don't WORK
# Steps to Reproduce
Be brig medic, try and use brig medbay windoor, it no work.
# What you Expected
It to open.
# What Actually Happened
It didn't.

**Comment by DriftingSkies** [comment]
I'm tired, I meant the Brigbay, not the Medbay

**Comment by kernikov** [comment]
Roid Brig front doors use:
`/var/const/access_sec_doors = 63 // Security front doors`

Roid Brid Medbay windoor uses:
`/var/const/access_security = 1 // Security equipment`

Brig medics have access 63, not 1.
Sounds like a mapping issue maybe.
