### ISSUE TITLE
Captain's Log 17: A Hairy Situation

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#30931]
A beard's to a sailor like barnacles to a ship, the more you have the more your experience reflects. Despite this, a man can't simply let his visage grow asunder with Spanish moss. Shaving's imperative for any respectable seafarer, but a good blade may sometimes be scarcer on the waves than a sharp wit. Of course, where there's a will there's a way, and lack of sword or dagger will not stop a clever jack from his mission. 

In the pirate capital of Nassau, where life's cheaper than rum, many of the men have figured a way to use plentiful bullets to trim their faces instead of a razor. I shall detail these steps below:
**Step 1: Get shot in the face**
![beard1](https://user-images.githubusercontent.com/51391726/135032013-e50d2aa2-a7ef-486c-a3a5-6096328284e4.PNG)
It's not a clever art, hair's well-known to be scared of bullets just like any ordinary man, and it's commonly-held that gunshot victims are found hairless, the follicles simply hauling off like rats from a ship to find a better, safer life. Even if you get facial reconstruction surgery, as many a man does when confronted with grapeshot to the skull, the hair will remember the treacherous seas it once lurked and refuse to return. 

However, not all is lost for the sailor contemplating purchasing a beret, the cure is rather simple:
**Step 1: Get a new beard in the mirror**
![beard2](https://user-images.githubusercontent.com/51391726/135032378-c14e6580-8e6b-48a4-a43d-1f981ac1877c.PNG)
Now, dear reader, you may be saying, "But that's not strange at all, mirrors can always create beards!", and I'll concede that fact. What I'll raise you, however, is that the original hair returns from the æther as soon as it spies a beard, instead of needing to tend to it separately. 

May you find use from these logs, I wish you all the best.

**Comment by DeityLink** [comment]
Yeah instead of "not displaying hair", disfigured people have their hair style changed to Bald. It should probably work differently.
