### ISSUE TITLE
Time Agent Evil Twin escape doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30936]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
cdd473d6aeebd6c859e68ddb086fd667c71a2fe0

# Description
Role description says: "Steal your doppelganger's jump charge, erase him from the timeline,
and use the jump charge to escape through the temporal anomaly before it's too late."
Using a jump charge on an anomaly does nothing
# Steps to Reproduce
Use stolen jump charge on anomaly
# What you Expected
To get teleported off the station/deleted
# What Actually Happened
Nothing

**Comment by Eneocho** [comment]
The anomaly was adminspawned, not role spawned. That might've been the issue.
