### ISSUE TITLE
Hobo spawn typo + ignition for forge

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#30960]
[bugfix]
[grammar]
You are a Space Hobo.

The ID you wear _**IS**_likely not even your own. At least as far as you can remember. But this chunk of plastic still can be a rare oddity that can change your character. Find a way to stay out of trouble, and survive. Though this does not mean you have no home, as the asteroid is your home. Whatever planet you may have come from is now a distant memory.

Hobos also do not have a lighter for lighting their forge.
Not sure if intentional, but seems a little dumb maybe that they managed to make a shack without any tools.

**Comment by Eneocho** [comment]
Don't they have a welder?

**Comment by kernikov** [comment]
They do not.

**Comment by Eneocho** [comment]
I could've sworn that at one point they had a mechanical toolbox in there. Must've been removed.
