### ISSUE TITLE
Box kitchen lightswitchs control the same area

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30975]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
# Revision
3668def331c952f4bac6738a4cea657d3f08700e
There's one outside and one inside the coldroom, both are the same area so they both turn the same lights on and off.

**Comment by Kurfursten** [comment]
Not really a bug though

**Comment by kernikov** [comment]
The issue can be closed
