### ISSUE TITLE
Intent Bar Vanishes as Zombie

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30978]
(WEB REPORT BY: dangerousmaniac REMOTE: 206.221.180.138:7777)
# Revision
3668def331c952f4bac6738a4cea657d3f08700e

# Description
As a zombie my intent bar vanished

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DriftingSkies** [comment]
Intended, you become a player controlled simplemob and thus cannot do anything but HARM
