### ISSUE TITLE
You can no longer rotate gamer chairs on the shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30979]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
3668def331c952f4bac6738a4cea657d3f08700e

# Description
shuttle chairs can't spin or change direction anymore, not the normal metal ones they're fine

**Comment by SonixApache** [comment]
related: #26742

**Comment by BomberBro** [comment]
1. downvote bugfix to fix this
2. bugfix gets merged
3. open up a new issue despite this clearly not being a bug


sasuga, at least ask it as a feature request
