### ISSUE TITLE
Spawning into Dojo as Ninja is 100% pitch black, instead of dim.

### ISSUE THREAD

**Issue by Megadeadly** [d3athrow/vgstation13#30988]
<bugfix>
Description of issue:
First spawning into the Dojo as a ninja is 100% pitch black.

#### Difference between expected and actual behavior:
Should be able to see something as a ninja.

#### Steps to reproduce:
Roll Space Ninja. Cry as you spend 10 minutes trying to find the button to leave.

*Maybe* Important: Roll space ninja from just loading into the server, not from being dead and ghosted. That's how its happened to me both times, but both times, those were my only ninja rolls.

#### Specific information for locating:
The full darkness only occurs when first starting. Dark areas on the station are only made dim properly. An admin spawned me a lantern in the dojo as well, and after turning it off, it was no longer pitch black either. I would bet that setting everything dim requires a light update of some kind first to activate, and spawning in doesn't have that happen.

#### Length of time in which bug has been known to occur:
I don't have a specific time frame, but I think the last time it occurred to me was about maybe 2 weeks to a month ago, to today.

**Comment by SonixApache** [comment]
Additional detail: no runtimes, admin-called ruleset.

**Comment by 9percents** [comment]
dynamic called ninja, as an active admin for that round I concur that it was pitch black before i spawned a lantern

**Comment by Eneocho** [comment]
Similar thing happens with the Time Agent chamber. It is pitch black.

**Comment by SonixApache** [comment]
edit: okay it happened twice on the same day with the same issue persisting.. really weird, probably something to do with eurolights
