### ISSUE TITLE
Swapping clothes now makes you drop everything in your pockets, ID slot, etc.

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#3099]
![ss 2015-02-18 at 08 38 25](https://cloud.githubusercontent.com/assets/9064611/6260551/6cbbde0c-b7ae-11e4-90ef-0c0a2d1a7ce2.jpg)

![ss 2015-02-18 at 08 39 24](https://cloud.githubusercontent.com/assets/9064611/6260554/7034e3c6-b7ae-11e4-8660-b734dc49f2c4.jpg)

**Comment by ririchiyo** [comment]
This was a bug with how quick swapping was before, this was always the intended behavior but quick swapping was a bug that wasn't reported so people were confusing it as a feature and not a bug.

**Comment by Probe1** [comment]
that's a pretty gay feature.

**Comment by BestName** [comment]
Just like in the good old days before quickswapping was a thing.
