### ISSUE TITLE
Weird movement hijinks after freezing explosion.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#30998]
(WEB REPORT BY: exabod1 REMOTE: 206.221.180.138:7777)
# Revision
c149d81a504ee9e263995a545abb23a603ee905c

# Description
Weird movement related problems started to happen after a weird explosion that froze in place in the morgue.
# Steps to Reproduce
Move downwards. Not sure if it is related to pushing "not disarming" other living creatures, like dogs.
# What you Expected
"Look at these!" "Nice shoes!" "No!" "Legs!!"

# What Actually Happened
No mobiment ;[

**Comment by Exxion** [comment]
I'm **much** more interested in hearing about a frozen explosion.
