### ISSUE TITLE
Cheap lighters have no sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31005]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
6be6eba18b10f5126f23998f6d4d6e4777682c96
 
Cheap lighters don't seem to have a sprite anymore.

**Comment by Apogee-dev** [comment]
Can't replicate the issue locally and a cursory investigation of the relevant code doesn't show any obvious cause.

**Comment by jwhitak** [comment]
Cannot reproduce. Live play example of all sprites there, tested all directional inhands. Could it be some specific color variant? Are there color variants?

![image](https://user-images.githubusercontent.com/69739118/136349101-01b04141-bea8-482f-aed7-0611ad3d75b1.png)

**Comment by Apogee-dev** [comment]
> 
> 
> Cannot reproduce. Live play example of all sprites there, tested all directional inhands. Could it be some specific color variant? Are there color variants?
> 
> ![image](https://user-images.githubusercontent.com/69739118/136349101-01b04141-bea8-482f-aed7-0611ad3d75b1.png)

After some discussion on the discord, it appeared to have been a clientside issue. The user fixed it by clearing his cache- we can probably close this.
