### ISSUE TITLE
lights bleed through walls completely now

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31019]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
32bef7326bbb627108187dc537ba5ab0e78d7bb3

the tile behind the wall is even illuminated

**Comment by Dacendeth** [comment]
![image](https://user-images.githubusercontent.com/26881007/136642655-bff4b719-e2a0-4694-b7d6-b36efdb753e8.png)

There are no lights in this maint, just on the other side of the walls.
