### ISSUE TITLE
Mushrooms can no longer emote

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31014]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
4c175417928d26a1dd2b31fa85b93c32300d0e26

# Description
try to *wave, *fart, *nod, *clap, *spin to show my emotions to fellow traders. Can do none of those, accidentally say "*nod" into some poor vox's mind
# Steps to Reproduce
be a miserable mushroom and try to do emotions
# What you Expected
emotes
# What Actually Happened
I can no longer do emotions and can't even dab to end my misery in a powerful shower of gore.

**Comment by Servalfang** [comment]
also needs a button on the link that lets you pick nothing to chat with
