### ISSUE TITLE
Cyborg Chemistry Gripper doesn't work on containers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31038]
(WEB REPORT BY: locese REMOTE: 206.221.180.138:7777)
# Revision
33db6af663121ec6f0245f40210cfee0890f95ee

# Description
see title
# Steps to Reproduce
become a medborg, equip the chemistry gripper, try to take a beaker out of the box
Extra: vials can be taken out of their box but leave graphical artifacts
# What you Expected
to take out the beaker
# What Actually Happened
can't get a beaker in my gripper

**Comment by jknpj** [comment]
Unless someone half-baked a way to, they were never intended to be able to
