### ISSUE TITLE
spider queens have a weird auto-aim

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31040]
(WEB REPORT BY: gallywix4 REMOTE: 206.221.180.138:7777)
# Revision
33db6af663121ec6f0245f40210cfee0890f95ee

# Description
the ranged attack of the spider queen has a weird auto-aim that targets people both alive and dead
# Steps to Reproduce
click in a tile with no space man/ click on space man when there is another space man closer
# What you Expected
hitting the space man i clicked on
# What Actually Happened
free cs-go hacks

**Comment by Eneocho** [comment]
Was on the round as the other spider queen. This fucked me many times since it aimed all wrong and got me lasered.

**Comment by DeityLink** [comment]
This could be a bug with all simple animals featuring ranged attacks. Players rarely ever get to play as those.
