### ISSUE TITLE
Making a tooth necklace out of vox teeth renames it to human teeth

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31045]
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
6ad27a0d4a9774756fd7b4fce2f06862c0003bed

# Description
when making a tooth necklace, if you use vox teeth it gets renamed to a "human teeth necklace"
# Steps to Reproduce
get vox teeth and apply cable coil
# What you Expected
to get a vox teeth necklace
# What Actually Happened
getting a human teeth necklace

**Comment by Eneocho** [comment]
this happens with any teeth kind.

**Comment by Eneocho** [comment]
Fun, duplicate of #20968, reported by Kumarus as well.

**Comment by DeityLink** [comment]
Duplicate of #20968
