### ISSUE TITLE
Whips have the same description as hookshots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31044]
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
6ad27a0d4a9774756fd7b4fce2f06862c0003bed

# Description
what it says on the tin
# Steps to Reproduce
look at a bullwhip then look at the hookshot
# What you Expected
for them to have different descriptions
# What Actually Happened
they have the same description

**Comment by ghost** [comment]
whoops, I'll fix this when I get home if nobody else does first
