### ISSUE TITLE
Synergy shuttle wall corners have wrong directions

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#31056]
![image](https://user-images.githubusercontent.com/55976761/136835757-03c44e98-bed3-4c54-bdc8-65f4405f7dbd.png)

It's like this with multiple shuttles.
Where the fug is my mapping Synergy self label?
#### Server revision

f078d50999f549a053630cecb5a15f28c9522526

**Comment by RFultra** [comment]
Literally unplayable

**Comment by Eneocho** [comment]
We need a ton of new self label tags.

**Comment by ghost** [comment]
mustve forgot this map, had a lot to rectify when i converted them
