### ISSUE TITLE
Mushroom person talon prosthetic - pressure suit problem.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31050]
(WEB REPORT BY: glastonburymkii REMOTE: 206.221.180.138:7777)
# Revision
57f98cb5f619e36d4bb22530d430ec8df40e9016

# Description
When using the prosthetic to give a talon for document signing to a mushman, I lose the ability to wear the mushroom space suit, as it says that the misshapen hands prevent it. And vox suits, naturally don't fit.
# Steps to Reproduce
Use mushroom-to-talon prosthetic
Take off mushroom man pressure suit
Attempt to put pressure suit back on
# What you Expected
I expected things to work normal.
# What Actually Happened
See the 'description' tab.

**Comment by Eneocho** [comment]
Make the talon prosthetic also come with a pressure suit mod for the shroomsuits. Makes for RP too.

**Comment by Kurfursten** [comment]
My solution for this is going to be to finally combine the **default** trader suits into one object (much like how a grey and human can wear a default engineering hardsuit); old icons will be preserved with the species fit var
