### ISSUE TITLE
Shuttle Corner Pieces Are Space-Lit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31065]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
f078d50999f549a053630cecb5a15f28c9522526

# Description
The corners of shuttles and escape pods are fully lit up, as if they were space. This looks incorrect, since all the walls and other materials around it are lit correctly.

**Comment by ghost** [comment]
dont know an easy fix sadly

**Comment by Exxion** [comment]
Well, you can turn them back into turfs and use the solution that already worked

**Comment by ghost** [comment]
Found a better solution for it than that after all, plus working more on it.
