### ISSUE TITLE
Breathing doesn't affect body temperature

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#3106]
You just get burn damage on your head when breathing air at extreme temperatures. Seeing that it doesn't stop you from breathing it (`life.dm`/`species.dm`, you don't suffocate), it should at least have an effect on your body temperature.

Since noses are supposed to bring the inhaled air close to the internal body temperature, breathing probably shouldn't affect it unless the temperature is above/below `heat_level_1`/`cold_level_1`. Maybe make gases above level 3 unable to be breathed, too (_are you a tough enough dude to breathe *THE SUN*_?)

**EDIT:** this is specially an issue when using internals and sitting on a vacuum with a spacesuit!

**Comment by gbasood** [comment]
ew

**Comment by PJB3005** [comment]
This had been fixed as of hypothermia I think.
