### ISSUE TITLE
Forge Smelting Glitches

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31079]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
a138859aec54b20dac65eb76e94e9db1b2202f55

# Description
The Forge, made with Sandstone Bricks, has oddities when smelting ores. Ores will only smelt 15 of their amount, and the remaining ore when (removed from the forge) will be glitchy, invisible, and not smelt anymore. Metal Ore will not smelt, and Sand doesn't fit in the forge.
# Steps to Reproduce
Put any smeltable ore into a lit forge, observe what happens. 
# What you Expected
The amount of ore placed into the forge to be smelted, and if any were left, it would not be invisible. Also, some ability to smelt metal or glass.
# What Actually Happened
Glitchy ores, no metal or glass.

**Comment by Zth--** [comment]
I've seen plenty of runtimes related to smelting, so it's probably that

**Comment by jwhitak** [comment]
Metal not smelting may be temperature related, it's the highest melting point of all the standard ores. Sand will straight up not go in the forge.
