### ISSUE TITLE
ELECTRIC CHAIR IS KILL (elektropak actually is)

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3107]
Well, as the title says, they don't work. You can assemble the chair just fine, and you can configure the signal thingie on it too.

Problem is, the signal is never received? Or the elektropak not working at all? I don't know

Here are the steps to reproduce the problem:

>build chair
>print elektropak
>turn it on (also tried with it turned off)
>set its freq
>screw
>apply helmet
>screw
>apply to chair
>lure bolasthrower420 in your backroom
>sleepypen him
>strip him and buckle him to the death chair
>wait for him to wake up
>send signal from a properly configured remote
>???
>nothing actually happens
>disassemble the chair
>apply the elektropak to his back
>send signal again
>???
>nothing happens
>cry

**Comment by Zth--** [comment]
add this too
http://a.pomf.se/olepyx.webm
it was easier to explain with a video

**Comment by clusterfack** [comment]
Should have been fixed by https://github.com/d3athrow/vgstation13/commit/e325589349c7c064631fbf77999faebaa9935c77
