### ISSUE TITLE
Splicing spreading kudzu into unspreaded kudzu won't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31084]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
a138859aec54b20dac65eb76e94e9db1b2202f55

# Description
In spite of description saying it could, waited 5+ minutes
# Steps to Reproduce
Purge kudzu development then add spread trait back in from other kudzu seed pack with splice
# What you Expected
Spreadign vines
# What Actually Happened
Standstill

**Comment by gurfan** [comment]
iirc plants only spread if they are carnivorous or low on water+food, was the plant well fed?

**Comment by ghost** [comment]
> iirc plants only spread if they are carnivorous or low on water+food, was the plant well fed?

Fairly

**Comment by ghost** [comment]
yea this was because i didnt let it go hungry, was dum and didnt know that
