### ISSUE TITLE
Spawn menu is too small and unexpandable

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#3108]
Don't like guessing when I need/want to spawn an object with a ridiculously long path.

**Comment by ririchiyo** [comment]
Funnily enough the window actually performs better in the webclient for the spawn menu, try it out sometime, Skowron.

**Comment by Intigracy** [comment]
How would one go about fixing this?

Also eww webclient.

**Comment by clusterfack** [comment]
Making an html menu that it brings up instead

**Comment by PJB3005** [comment]
@clusterfack impossible to do properly due to BYOND.

**Comment by clusterfack** [comment]
@PJB3005 

Bullshit

**Comment by PJB3005** [comment]
Sure it's possible but there'll be a small delay on the inputs.

**Comment by clusterfack** [comment]
I don't think anyone would give a shit about a small delay to be honest

**Comment by PJB3005** [comment]
Alright I'll look into it.

**Comment by Probe1** [comment]
Can't do shit captain its a byond issue

**Comment by ComicIronic** [comment]
Well, the HTML request is still valid.

**Comment by PJB3005** [comment]
Problem with the HTML request being that if you go with HTML, your client will lock up badly in the same way as using the Game Panel right now does, so it's still not a solution.

**Comment by Probe1** [comment]
Game-Panel already does exactly what he asked but no one uses it because it uses HTML and takes 10+ seconds to load.  So no not really.
