### ISSUE TITLE
AI cannot use :h comms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31088]
(WEB REPORT BY: disgruntled REMOTE: 206.221.180.138:7777)
# Revision
17ed7d6bd407b047c5c2f686de418f675af10a8f

# Description
The station AI cannot use the Supply channel (:h).

# Steps to Reproduce
Type a message with the :h prefix.

# What you Expected
For the message to send on the Supply channel.

# What Actually Happened
It did not send on any channel, acting as though comms were not available.  This, despite Supply being enabled in the radio configuration.

**Comment by DriftingSkies** [comment]
It's :u, dummy
