### ISSUE TITLE
immulsions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31082]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
a138859aec54b20dac65eb76e94e9db1b2202f55

# Description
"The angry bee are stinging the pillow bug"
# Steps to Reproduce
Angry bee
Sting pillow bug
# What you Expected
The angry bee is stinging the pillow bug!
# What Actually Happened
The angry bee are stinging the pillow bug!

**Comment by ghost** [comment]
later that very same bee...
