### ISSUE TITLE
Toy double-bladed e-sword has no in-hand turned on sprite.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31081]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
a138859aec54b20dac65eb76e94e9db1b2202f55

# Description
title
# Steps to Reproduce
add toy e-sword to toy e-sword
# What you Expected
scary flashy thing
# What Actually Happened
only off sprite, disappears when turned on.

**Comment by RFultra** [comment]
Probably an easy fix

**Comment by Eneocho** [comment]
Duplicate of #30872, #30712 and #30731.

**Comment by RFultra** [comment]
It's not an easy fix. The sprites for one handed and multi coloured duelsabers don't exist.
