### ISSUE TITLE
Stop mapping in blood/antag scenes on the station

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#31092]
Inspired by #31077

Simply put, mapping in "post-crime" scenes on the station just leads to nonsense scenarios where you have to tell a detective investigating a blood splatter that actually the blood splatter is always there, it's just part of the station like the entire crew lives in a goddamn haunted house. 
![roid](https://user-images.githubusercontent.com/51391726/137558138-7f56d52f-1a02-47bc-b109-e3a5b938efac.PNG)
This isn't even an extremely niche, out of the way area, it's in maint right next to escape. Then we have bagel's new cult cave:
![bagel](https://user-images.githubusercontent.com/51391726/137558309-942806e9-e522-42da-80ee-d5c3da8c734e.PNG)
What's even the crew reaction to this supposed to be? "Oh, yeah, that's just the maint cult den, it doesn't actually mean we have a cult because... uh...". Can security and command start mass implanting people IC over it? If not, are they supposed to use OOC knowledge to know that it's not actually proof of a cult? I take issue with this one a bit more with the blood splatter specifically because in any other map it'd be 100% definitive proof there's a cult aboard, but on bagel you're supposed to just ignore it. The station shouldn't start with any random bodies (which bagel has in the ghetto bar, which you also have to tell the detective is just another haunted house prop), blood splatters, or antag evidence at the start of the shift outside of maybe nonsense maps like deff where the pvp zone is part of the charm. 

[discussion]

**Comment by Kurfursten** [comment]
I think the occasional dried blood is fine - you can leave that behind by accidentally wrenching yourself (I've done this myself as engineer a ton)

But yeah the cult den is a bit much, I probably should have spoken up more at the time that improving the realism of the cult den was a bad idea. That's really more suitable for a vault.

**Comment by GreatBigFailure** [comment]
Blood doesn't carry over between rounds at all, does it? Specifically adding a "dried blood" stain that carries over from uncleaned blood (keeping frequency within reason) would be much better than mapping it in and make it easily explainable IC as to why it isn't alarming.

As for the cult base, I agree with Kurf that it's more vault-like. Please spend any rounds you're able using that room as an excuse to implant everyone via high RP IC demands.

**Comment by BomberBro** [comment]
It's not dried blood, it's completely fresh afaik

**Comment by Dacendeth** [comment]
it's wet blood with no dna, just change it to an oil spill instead.

**Comment by DeityLink** [comment]
> in any other map it'd be 100% definitive proof there's a cult aboard,

Or that some badmin had fun.

That being said if that's really a concern why was this room mapped in the first place @plosky1 ? Runes are already there too, they're just invisible. 

> Can security and command start mass implanting people IC over it?

What does spess law say on mass implanting? Do they need a reason to do it? I don't think our server rules say anything regarding it either, so I'd reply "yes" to that, and even argue that they can do it for much less than that if they so desire. Security roleplaying as a paranoid bunch is a staple.

> are they supposed to use OOC knowledge to know that it's not actually proof of a cult?

OOC knowledge can be used while roleplaying you know. Not necessarily to spout lines like "oh yeah that cult room's always been there" but you can fake concern about it, ask the chaplain to cleanse the room, etc. And even if you don't have the knowledge one round, you'll have it the next ones.

**Comment by Exxion** [comment]
It's *extremely* immersion-breaking for something that would cause stationwide panic on any other map to just be lolnothing on one map. That people theoretically could pretend to actually be worried doesn't change that.

I don't mind the blood. It should be dried blood though.

**Comment by BomberBro** [comment]
>Or that some badmin had fun.

what's the IC explanation behind that one, if there's a cult there's a cult. We shouldn't hardmap something in just because an admin could do it, and potentially actually RP it out and take control of the bus. The room was mapped in the first place because most likely nobody noticed the broken runes. 

>Do they need a reason to do it? I don't think our server rules say anything regarding it either

Randomly mass implanting people would be metagaming normally, they **do** need a reason.

>OOC knowledge can be used while roleplaying you know. Not necessarily to spout lines like "oh yeah that cult room's always been there" but you can fake concern about it, ask the chaplain to cleanse the room, etc. 

Every single round? Every round somebody says that it's cult we should react in a completely different way than any other map because we're using OOC knowledge that it's not actually a real cult, just hardmapped in? It's incredibly silly to keep stuff like that in, it'd be akin to mapping in a blue APC in a solars room. I don't want to have to go through the same motions every time, or just not care about what people might genuinely believe is a real crime scene if they haven't seen the map, all because I should know OOC that it's not actually a real cult.

**Comment by plosky1** [comment]
To be fair I wasn’t the one who mapped that in, I stopped doing stuff like that after the box maint fiasco of “stuff that shouldnt be in a space station” mass of complaints.

**Comment by DeityLink** [comment]
I wonder who added that then

**Comment by Kurfursten** [comment]
This cult base did exist on LF Bagel when it was first PR'd on March 11. Bagel did not have the cult base at this time - and still doesn't today, nor did it have it between.
The same var-edited candles can be found on Roidstation since its original commit.

Someone who worked on LF Bagel added the cult room using objects from Roidstation, apparently not Plosky, between the time it was Bagel and the time it was released as Lowfat Bagel. It may have been Basil. He's an easy target to blame since he has left.

**Comment by DeityLink** [comment]
Well anyway I guess you've made your point. I closed my PR, feel free to re-map the room into a ghetto janitorial closet or something.
