### ISSUE TITLE
You can neuter a syndicate wheelchair for the price of two sodas

### ISSUE THREAD

**Issue by Killette3** [d3athrow/vgstation13#31118]
1. Get gun barrel craft from welding together 2 wirecutted soda cans (makeshift weapons)
2. Attach them to not any wheelchair, but our special red syndicate wheelchair
3. Take the assembly off, and notice your chair has become good and slow again

**Comment by Kurfursten** [comment]
You could also do this do ruin a multiman wheelchair or an electric wheelchair

Makeshift cannons were a mistake

**Comment by SonixApache** [comment]
simple fix, just allow for deconstruction

**Comment by Kurfursten** [comment]
It does have deconstruction, he's complaining that the wheelchair assembly does not store the wheelchair that was used inside it, meaning that when you deconstruct it, it makes a default wheelchair instead of remembering its subtype.
