### ISSUE TITLE
Forge cannot smelt metal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31110]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
89b1dbcd7e22e27866a48b81cc343b7ed8a2c489

# Description
Metal still can't be smelted in the forge
# Steps to Reproduce
Put plasma ore into furnace, light with welder, put metal ore in, no smelt!
# What you Expected
Metal
# What Actually Happened
No metal

**Comment by Zth--** [comment]
It needs plasma sheet instead of plasma ore

**Comment by Eneocho** [comment]
I could've sworn forges used any plasma as fuel.

**Comment by Zth--** [comment]
It does, but raw plasma reaches less temperature than plasma sheet
