### ISSUE TITLE
Reoccuring Lighting issues

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3111]
![lighting](https://cloud.githubusercontent.com/assets/3959840/6275154/c662f71e-b831-11e4-97bb-d41ee7f91ca5.png)

As seen above is my character providing light for no reason. While glowshrooms provide no light in the background

Among all other lighting issues:
When in a lit area any objects on you that provide light are cancelled out so when you get in a dark area you have to turn them off then on again to get them to light your way.

Its a long term issue but when I started glowing 4noraisns I thought it was too silly to ignore.

**Comment by ComicIronic** [comment]
What light-producing items had you interacted with?

**Comment by CptWad** [comment]
Glowshrooms, pda's in the picture.
It really works with any light producing object you carry it seems but more testing would need to confirm it.

**Comment by Probe1** [comment]
Yeah after a indeterminate duration light sources stop working.  It's related to having multiple light sources and they end up canceling the previous ones or something, deity_link explained it to me once.  

It's a very common bug for miners.  60 minutes into a shift you realize your lamp and hardsuit helmet light are on but aren't putting out light anymore so you have to toggle them off and on again to restore functionality.

**Comment by CptWad** [comment]
Blueprints-lighting issues were fixed.

**Comment by CptWad** [comment]
UPDATE:
There are still strange lighting bugs with items.
IE take a flashlight turn it on in a dark place. Turn your pda light on. Now put flashlight in pocket. Light dissapears. 
Not a priority but I am cleaning through old issues.

**Comment by CptWad** [comment]
closing because new lighting engine
