### ISSUE TITLE
golden gloves act as insulated gloves after touching the supermatter

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31119]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
7fbe9312eac94fb213c025e6bf8b9efc49cbbd84

**Comment by Servalfang** [comment]
feature

**Comment by ghost** [comment]
isn't this intentional? or do you mean you can't heal off shocks because they're completely negated?

**Comment by Kurfursten** [comment]
This is an unironic, intended feature

**Comment by gurfan** [comment]
~~What? In #29100 it says that they let you heal from shocks. The description of the gloves after touching suppermatter also says that. They don't heal you at all, they just act like normal insuls.~~
I'm dumb and they only heal burn damage.
