### ISSUE TITLE
rad collectors don't display the power generated

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31122]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
7fbe9312eac94fb213c025e6bf8b9efc49cbbd84

# Description
multitooling/gas analyzing a rad collector says it's producing 0 watts
multitooling the wire the collector is on says there is in fact power being made

# Steps to Reproduce
start singo
put tanks in collectors
SMES start charging but the collectors say they're still off

# What you Expected
The multitool registers that 58232 W is being produced every cycle

# What Actually Happened
The multitool registers that 0 W is being produced every cycle

somewhere:
- [bugfix]

**Comment by DamianX** [comment]
works on my machine
