### ISSUE TITLE
Screen with only turf and mobs after being mmi'd

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3113]
It doesn't always happen, but here: 
![edition_alpha_2015-02-13_14-39-41](https://cloud.githubusercontent.com/assets/4788171/6277391/80f765cc-b88e-11e4-9e8a-e2f496169ad8.png)
![edition_alpha_2015-02-13_14-40-27](https://cloud.githubusercontent.com/assets/4788171/6277393/80fc9ce0-b88e-11e4-89f2-e9d9f648029d.png)

![fatguy_outpost_alpha_2015-02-19_23-23-14](https://cloud.githubusercontent.com/assets/4788171/6277392/80fb7e32-b88e-11e4-9f05-6844256992ee.png)
![fatguy_outpost_alpha_2015-02-19_23-27-55](https://cloud.githubusercontent.com/assets/4788171/6277478/f9fbe45c-b88e-11e4-9e12-53d7133fa707.png)

as you can see, if I move objects appear.

If I reconnect it's fixed. I'm using latest byond beta. (1274)

**Comment by clusterfack** [comment]
I have literally no idea how to reproduce this in any way, I've never seen anything like it ingame

**Comment by clusterfack** [comment]
Has to be a byond fuckup

**Comment by DrCelt** [comment]
I've not heard of this reoccuring, blame byond and close I think
