### ISSUE TITLE
Matter Eater Power

### ISSUE THREAD

**Issue by Haigles** [d3athrow/vgstation13#3114]
I recently got this power and wasn't able to eat anything, not objects, not people, not monkeys.

**Comment by ComicIronic** [comment]
I can't confirm this on testing.

**Comment by Dizor** [comment]
Bumping this for recent weirdness
Matter eater can still be used on mobs (humanoid ones at least) but when used on items (banana peel, books, pens, etc) the player turns towards the item, but no further actions or text appear.

Something borked recently
