### ISSUE TITLE
Vox paramedics spawn with two PDAs

### ISSUE THREAD

**Issue by GarrusVakarian** [d3athrow/vgstation13#3115]
And an extra headset.

![k](https://cloud.githubusercontent.com/assets/6507460/6279645/69e66322-b8a4-11e4-87b3-f0317b7df908.png)

**Comment by 9600bauds** [comment]
Now I can finally ERP with myself

**Comment by 9600bauds** [comment]
This seems to happens with paramedics in general, not just Vox.

**Comment by ConkerDev** [comment]
Fixed by PR 5692
