### ISSUE TITLE
Forge - Iron Ore does not smelt with Plasma Fire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31165]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
e6136b5256db210d908183419c8dc5f19186c936

# Description
Plasma Ore forges should be hot enough to smelt iron, but they do not.
# Steps to Reproduce
Put iron ore and plasma ore into forge, light with lighter.
# What you Expected
Metal Sheets
# What Actually Happened
No metal sheets

**Comment by Zth--** [comment]
What's your endgame? You already made an issue about this but didn't discuss it when we commented on it #31110

It's not a bug, even though I agree it's kind of stupid

**Comment by Eneocho** [comment]
You can smelt iron with wood but not plasma ore? dumb

**Comment by jwhitak** [comment]
Mistake, I forgot I already bug reported it previously. It is a bug, to note.
