### ISSUE TITLE
Radstorm not glowing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31169]
(WEB REPORT BY: punishedpajeet REMOTE: 206.221.180.138:7777)
# Revision
e6136b5256db210d908183419c8dc5f19186c936

# Description
The station wasn't glowing green when a rad storm was incoming
# Steps to Reproduce
Play (on roid)
Encounter rad storm
# What you Expected
The station to glow green
# What Actually Happened
The station not glowing green

**Comment by DeityLink** [comment]
Was there a power outage? The glowing is actually meant to be emergency lights and tends to not appear at all when power is cut from a room.
