### ISSUE TITLE
Waystation Bridge has no Fire Extinguisher

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31171]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
dc19aa506357f03dcb0f4f0092f48310f3755b03

# Description
THIS IS A FIRE CODE VIOLATION
# Steps to Reproduce
>Be on Waystation
>Look for a thing to put a fire out
>Find nothing
>Be consumed by bees
# What you Expected
White box with red tube thing in it
# What Actually Happened
HEEELLPPP... I'M COVERED IN BEEES....

**Comment by djkramer123** [comment]
thank you
