### ISSUE TITLE
Mami mmi shenanigans

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#3117]
Putting a mami into an MMI and then removing it turns it into a regular human brain.
![ss 2015-02-20 at 01 08 25](https://cloud.githubusercontent.com/assets/9064611/6282121/2cd52128-b89d-11e4-8841-56a3899cc0f4.jpg)

**Comment by SkowronX** [comment]
They also can't speak as MaMis

**Comment by ComicIronic** [comment]
The speaking in a MaMI is intended behaviour.

Being able to put a MaMI in an MMI is not. I'll see about
 - Adding brain permanence
 - Making MaMIs uninsertable.
