### ISSUE TITLE
Biomass and kudzu growing through locked doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31199]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
97049d2459e9a2c79b195f3d0c32a57122ca46e2

# Description
What name says
# Steps to Reproduce
Please don't reproduce it
# What you Expected
Kudzu containable
# What Actually Happened
Kudzu grows through closedblast doors, airlocks.
I blame movement code overhaul, by Exxion.

**Comment by DeityLink** [comment]
@Exxion since you're being blamed
