### ISSUE TITLE
Telecomms Turrets No Longer Target

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31208]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
2ded66406d928e1e2ff9f06a4253cd984ce1f00a

# Description
Turrets in the telecomms chambers on likely all maps no longer target anyone. Reproduced this on Synergy and Box.

# Steps to Reproduce
Enter the Telecomms chamber.

# What you Expected
Taser bolts hitting the window.

# What Actually Happened
Nothing - I flexed at the foot of the turret set to lethal with no response.

**Comment by SonixApache** [comment]
AI turrets also don't work anymore. I noticed this yesterday.

**Comment by Exxion** [comment]
Works On My Machine. Possibly a BYOND bug? I am running a slightly newer version than the server is.

**Comment by Exxion** [comment]
Works for me on live, too. Was there anything unusual about the way you entered the area?

**Comment by west3436** [comment]
No, i just walked through the door. ID was in my PDA in the PDA slot.
