### ISSUE TITLE
Invisible walls

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#31201]
#### Description of issue
Joined game, walked down hallway, got stopped by an invisible wall. Nothing on alt-click menu.
Later found out there had been a time agent, which is probably related. Damian said he was getting runtimes for invisible walls.

#### Steps to reproduce
no idea

#### Specific information for locating
runtime log of 03 november 2021

#### Length of time in which bug has been known to occur
#31154 probably

#### Server revision
da18732ac60f5e2983c3c4a36f9b2c4c925c0ee7

**Comment by DamianX** [comment]
regular glass windows and timestop were involved

**Comment by Eneocho** [comment]
It happened to me while first testing Time Agent. I thought it got fixed. See #30248 and #30247. If I remember correctly it was some weird runtime with the spell expecting a mob then placing a blank unmovable mob on said tile.

**Comment by Exxion** [comment]
*Something* detached some border dummies from their windows, but I don't know what. Very likely related to whatever time agent bullshit was going on, but it's not as simple as just using a chrono grenade on them or whatever.
