### ISSUE TITLE
Escape shuttles by ACME corp

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31200]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
da18732ac60f5e2983c3c4a36f9b2c4c925c0ee7

# Description
Engines leave, shuttle stays
# Steps to Reproduce
Call the shuttle
# What you Expected
To leave this hellhole
# What Actually Happened
Engines left, I am still in hellhole.

I blame movement system overhaul.

**Comment by SonixApache** [comment]
happened again, except this time the bottom row of the shuttle went and left the rest of the shuttle behind

**Comment by Eneocho** [comment]
Happened yesterday, the shuttle's engines and some tiles arrived at centcomm while everything else remained at the waiting area.

**Comment by Exxion** [comment]
Fixed by #31202, unless it turns out it wasn't.
