### ISSUE TITLE
Mouser pistol design not visible in Flatpack fabricator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31213]
(WEB REPORT BY: jeems REMOTE: 206.221.180.138:7777)
# Revision
9c7e06a906e44425b18dd99a3225db726c0999da

# Description
Mouser pistol design can not be seen in flatpack creator after reading it in

# Steps to Reproduce
Scan mouser pistol with traitor device analyzer, print and read it in.

# What you Expected
to see the fucking design so I can print mouser pistols

# What Actually Happened
there is no designs. if I try to read it in it says design already read in

**Comment by gurfan** [comment]
look at this man and laugh

**Comment by Dacendeth** [comment]
Flatpack? Did you use the wrong machine?
