### ISSUE TITLE
regular sec vests have 25 explosion resist

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31221]
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
472e49c833afc6e9990864c46c34d11edbab5083

# Description
25 explosion resist? really? hmmm? when the MINING hardsuit has 35? Hmmm??? 
# Steps to Reproduce
get a sec vest and become immune to explosive implants
# What you Expected
sec not to have explosion resistance on bullet armor vests yeah thats kind of retarded
# What Actually Happened
they survived a pointblank eimplant. HUH?! why? that is soooo gaaayyy! change it. right now. this instance.

**Comment by BomberBro** [comment]
Skill issue.

**Comment by Kurfursten** [comment]
We don't have an "i died" label and I'm not making a new one so settle for this

**Comment by Eneocho** [comment]
We do, it's the "i ded" label. @Kurfursten, check this issue for the label. #30137

**Comment by Exxion** [comment]
It's right there bro

**Comment by Exxion** [comment]
Also 25 is pretty small
Does OP think 25 is better than 35?

**Comment by ghost** [comment]
provide actual test results if you think this is overpowered or this issue is getting closed

**Comment by SonixApache** [comment]
Now, supposedly, explosions don't work 100% the same way on live, but.
![1636199580 Science_Observatory_Omega](https://user-images.githubusercontent.com/8468269/140608626-baa0c5b1-1685-4079-9489-9c0e5cb93f9c.png) ![1636199592 Science_Observatory_Omega](https://user-images.githubusercontent.com/8468269/140608627-41df1ae0-6d47-43f9-a09e-0e587250a0be.png)
Explosive implant at point blank instacrits officers with their default gear.

**Comment by drawsstuff** [comment]
I've been point blank e-implanted as an officer several times. Can confirm it crits you instantly.
