### ISSUE TITLE
Chaplaincy issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31236]
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
66cd31ff16c3744fe61d92f5aabfc45d895b6b3d

# Description
Every time you try to pick a god, it's automatically space jesus
# Steps to Reproduce
>pick any non space jesus religion
>Pick not space jesus as a god
>Get space jesus and your bible is not what you picked
# What you Expected
>to have your proper god
# What Actually Happened
>space jesus

**Comment by Kurfursten** [comment]
Unable to reproduce on Test Server

**Comment by DamianX** [comment]
He's talking about pre-defined religions that let you choose from a list of deities or bible names. Those didn't work.
