### ISSUE TITLE
Bagel's shortcomings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31230]
(WEB REPORT BY: memdic REMOTE: 206.221.180.138:7777)
# Revision
6c2efa6d2d9a88a8a9d298b53cccaca718262455

# Description
On map "Loawfat Bagel" there are 2 problems that I found: First - there is just one pAI on station, instead of two.
Second bug I found is with borers. Borer development room lacks a pipe that would lead borers out of the plasma room.

# Steps to Reproduce

# What you Expected
First, there should be a pAI in the locker room roundstart. Second, there should be added a way out of the borer plasma chamber at borer development.

**Comment by Eneocho** [comment]
Also, lowfat is way too fucking big for it's current pop requirement. It always feels empty.
