### ISSUE TITLE
Vines can entangle ghosts who are astral projecting.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31243]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
817b97a29484419b87997667a2e63665ef34fdf5

# Description
See name
# Steps to Reproduce
Astral project as cult over vines, get entangled
# What you Expected
nothing
# What Actually Happened
vines reach beyond mortal plane

**Comment by SonixApache** [comment]
should be limited to vines with spiritbreaker in them

**Comment by ghost** [comment]
feature
