### ISSUE TITLE
Ultra-strong directional door tape

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#31249]
#### Description of issue
Tape, when placed on airlocks, can be lifted and removed when clicked.
However, if there is a (closed, alert) firelock in the direction that you are standing, this interaction cannot occur - no matter if the firelock is open or not, you cannot interact with the tape.

#### Specific information for locating
I'm guessing it doesn't allow you to actually open the firelock because the firelock is also a door and the tape prevents doors from opening.

**Comment by Eneocho** [comment]
it just works
