### ISSUE TITLE
Malf APCs stop being blue if you screwdriver them.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#31241]
They used to not update their sprite at all when you exposed the wires, but now it updates but doesnt go back to blue.

**Comment by SonixApache** [comment]
i dindu

**Comment by Eneocho** [comment]
on my way to screw-unscrew all the malf apcs as the nonantag clown

**Comment by Dacendeth** [comment]
Fixed, not sure by what but fixed.
