### ISSUE TITLE
Can't set network on newly built station relays

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3125]
![2015-02-20_17-52-55](https://cloud.githubusercontent.com/assets/4788171/6305162/6a13396c-b929-11e4-8934-c5fc3170934a.png)

the selection is blank.

Modifying the var to put in a network, doesn't make that change. Might just be an interface bug. Didn't test other tcomms devices

**Comment by ConkerDev** [comment]
I dont recall that happening anymore. Fixed?

**Comment by Cisrox** [comment]
It's fixed. Closeable.

**Comment by PJB3005** [comment]
Fixed, indeed
