### ISSUE TITLE
auto mining is not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31269]
(WEB REPORT BY: sylphyn REMOTE: 206.221.180.138:7777)
# Revision
785e0e00e590396a91f58ef1f43943ca9a5e60fa

# Description
auto mining by walking into minable rocks with a pickaxe in hand is not working
# Steps to Reproduce
walk into a rock with a mining pick, nothing happens
# What you Expected
for me to start mining the rock
# What Actually Happened
nothing

**Comment by SonixApache** [comment]
Works on 817b97a29484419b87997667a2e63665ef34fdf5, let me try...
Edit: Works on 785e0e00e590396a91f58ef1f43943ca9a5e60fa too, BUT
Only if you're not wearing any kind of gloves. I'll go ahead and blame #31244 for this.
