### ISSUE TITLE
cyborgs cannot interact with digital valves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31277]
(WEB REPORT BY: agentofzog REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
Cyborgs cannot press the digital valve to activate it or deactivate it.
# Steps to Reproduce
Try to flood as a borg, realize you need to be an engie and replace the valves entirely.
Or maybe you're trying to STOP a flood. That too
# What you Expected
Though this would be fixed by now, it was lsited as "oversight" in issue #23365 in 2019
# What Actually Happened
Nothing

**Comment by pedr69** [comment]
works on my machine? you don't even need to be standing next to it
you are clicking on them without an item in your hand right?
