### ISSUE TITLE
Pathogen Incubator Uninteractable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31279]
(WEB REPORT BY: balabalalde REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
Working as a Viro, had the incubator stop functioning until after an admin manually removed the trays and some time passed.
# Steps to Reproduce
Dont think I could
# What you Expected
to interact with incubator, but no gui appeared and no trays could be removed
# What Actually Happened
nothing

**Comment by DeityLink** [comment]
Can't seem to find any related runtimes, are you sure the incubator was powered? not broken? and not screwdrivered'd open? can't seem to reproduce.
