### ISSUE TITLE
sokoban machine broke

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31289]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
sokoban dungeon broke
# Steps to Reproduce
try to solve sokoban but it's rotated
# What you Expected
push crates to solve sokoban
# What Actually Happened
crates disappear on a tile one after another, and stepping on that tile sends you into deep space

**Comment by ghost** [comment]
understandable, have a great day

**Comment by Eneocho** [comment]
The sokoban vault is such a meme though. Who in their right mind puts the hardest puzzle at the beginning of the puzzlegame?
Yeah, yeah, I know sokoban is based on the Nethack Sokoban minigame, but the first map on the vault is the hardest puzzle in the nethack minigame.

**Comment by DeityLink** [comment]
hopefully Fixed by #31315

**Comment by DeityLink** [comment]
Fixed by #31315
