### ISSUE TITLE
PDA Photo Message

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31288]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
When trying to select a photo to send, there's only one option no matter how many photos you got taken. It will always be the first photo so you'll have to delete them all to send a different one.
# Steps to Reproduce
Get PDA camera cartridge
Take several photos
Try to send message with photo
Only one option
# What you Expected
Options for all photos
# What Actually Happened
Option for first photo only

**Comment by ghost** [comment]
yea i noticed this while coding those, this was a side feature so i never really worked on fixing it
