### ISSUE TITLE
Server reboot is too efficient, curbourroundend never gets a chance to completely roll anymore

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#31287]
dammit damian

**Comment by ghost** [comment]
what the fuck am I reading

**Comment by SonixApache** [comment]
it's a joke but the credits roll doesn't ever roll all the way down anymore, which is a waste of the credits roll

so the solution, obviously, is to make the credits roll by faster

**Comment by Eneocho** [comment]
In the meantime, you can select the credit roll text and manually pull down for it to "scroll" faster.

**Comment by DeityLink** [comment]
> 
> 
> In the meantime, you can select the credit roll text and manually pull down for it to "scroll" faster.

Holy shit that's a thing?

**Comment by ghost** [comment]
it never scrolled for me or did the music, but im on a win 7 vm and WINE before that so maybe why
