### ISSUE TITLE
Cultist Cap can be bypassed by soulstoning someone and reviving them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31301]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

also the reincarnation rune likes failing randomly at times

**Comment by gurfan** [comment]
The soulstone should probably just fail at the cap.

**Comment by gurfan** [comment]
@DeityLink

**Comment by DeityLink** [comment]
> 
> 
> The soulstone should probably just fail at the cap.

It does https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/objects/items/soulstone.dm#L122

Can you show me a pic of the altar's cult roster the next time this occurs?

**Comment by gurfan** [comment]
> > The soulstone should probably just fail at the cap.
> 
> It does https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/game/objects/items/soulstone.dm#L122
> 
> Can you show me a pic of the altar's cult roster the next time this occurs?

In that code you posted it checks if the cap was reached after the target was shaded and inserted into the stone. When the cult was at the cap yesterday they used the stones to create shades that weren't technically part of the cult, but after using the reincarnation rune it forced them into the cult faction. I'll try to get pics later today

**Comment by DeityLink** [comment]
@gurfan  Yeah I read my code again carefully today and face-desk'd in shame

I'll fix it tonight. This is what happens when I code while tired and burned out.
