### ISSUE TITLE
The unforgivable sin - Bring back XTREME SHOWERS [FR]

### ISSUE THREAD

**Issue by drawsstuff** [d3athrow/vgstation13#31317]
I have no idea what removed this, but it seems to have been long long ago. The issue I bring up today is _who in their right mind fucking removed EXTREME SHOWERS_.

Wrenching showers used to allow extreme high and low temperatures. These temperatures were actually capable of killing (if you stood under it for a minute like a moron, there's far more efficient methods of murder don't try and argue balance here.) and made hilarious, if impractical methods of suicide or the occasional murder for the detective to solve.

The real secret sauce though, was not the scalding hot showers, but the freezing cold ones. With these showers it was possible to preform **ghetto cryo**, where a patient would be fed cryomix and then put under a freezing shower. Highly impractical, but it worked for the fringe situation that medbay was overrun with xenomorphs and your cloneabortion of a boss can hardly function.

I'm requesting these EXTREME TEMPERATRES be brought back.

**Comment by F-OS** [comment]
Missed #9425, bringing back 300 degree showers might be cool though.

**Comment by Kurfursten** [comment]
You can actually still do ghetto cryo and I have seen flarg do it on live, it just takes longer than you think

**Comment by SonixApache** [comment]
Showers cool you down to -137°C, and heat you up to 60°C.
https://github.com/vgstation-coders/vgstation13/blob/3f56588d3e4d4c8c18516edb349b801820a03fa4/code/game/objects/structures/watercloset.dm#L453-L467
Cryoxadone kicks in at 170°K, or -103°C.
https://github.com/vgstation-coders/vgstation13/blob/4f5fb91300736a78f00ca497a0dd9c7a08c25b6d/code/modules/reagents/Chemistry-Reagents.dm#L3377
Ghetto cryo still possible, although the speed is one fiftieth of what it once was. Could up it to 5.

**Comment by Exxion** [comment]
Related: #25687

**Comment by Eneocho** [comment]
> Ghetto cryo still possible, although the speed is one fiftieth of what it once was.

By that point the guy would've died from hypothermia-based oxygen damage.

**Comment by Kurfursten** [comment]
He won't, but even if oxy damage was a threat though you could just add dexp to your ghetto cryo IV and be safe.
