### ISSUE TITLE
Spessmart alarm will trigger even if you paid for the goods you took.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31310]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
Found the spessmart just south of the mining outpost in meta. Went there, saw two shuttle destination discs for 90 credits each. Placed both disks in the table in front of a chasier and inserted 1190 credits into the chasier.
Walked out and got mauled to death by the securitrons.

There's also the chance that I did something wrong but there aren't manuals on how to properly do transactions in the mart. 

At least a fucking paper with transaction guidelines in the spessmart lobby could help.

# Steps to Reproduce
1- Go to spessmart
2- Find a item you like
3- Go to the cashier near the mart exit
4- Put the items you want to buy on the table in front of the cashier
5- Insert the credits needed to buy the item inside the chashier
6- Grab items and walk out
7- Get mauled to death by walmart

# What you Expected
Walking out of spessmart alive

# What Actually Happened
Death by mart-bot

**Comment by BomberBro** [comment]
I've done this before, you have to click the bot again after putting in the money, it's really unintuitive.

**Comment by Eneocho** [comment]
I should probably write a guide to spessmart.

**Comment by WindowsErrors** [comment]
whats the spessmart

**Comment by Eneocho** [comment]
A space vault that has tons of shit for you to buy, but is also filled with fucktons of very murderhungry bots that WILL fuck you up if you dare steal a 1 credit balloon. You can find antag-only goodies, rare clothes, unique items, circuits, food, bus only shit, etc.

**Comment by Kurfursten** [comment]
Instead of just triggering the warnbot should TELL YOU when you are walking out with goods so you have a chance to go back

It should also mention how the price tag needs to disappear from the item
