### ISSUE TITLE
farmbot doesn't move on itself

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31316]
(WEB REPORT BY: locese REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
see title
# Steps to Reproduce
build the farmbot, plant something in botany, wait until plant needs water/weeding/fertilizing
# What you Expected
for it to work
# What Actually Happened
it doesn't move to trays in sight, but it does weed/water/fertilize adjacent trays

**Comment by DeityLink** [comment]
Farmbots can't path around trays I believe, they probably got themselves stuck.

**Comment by Cartlord** [comment]
They don't path at all, this is still an active issue

**Comment by Cartlord** [comment]
also this is a duplicate of https://github.com/vgstation-coders/vgstation13/issues/22319
