### ISSUE TITLE
Lowfat Bagel Brig Medic Lacks Access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31311]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
c077fc9ee7966568780ee0d720de11689b5f719e

# Description
Brig Medic does not get access to the security lounge room or the brig's medbay.
# Steps to Reproduce
>be Brig Medic
>try to get to your workplace
>no access
# What you Expected
Get to set up a cool little brig bay in case of people getting hurt.
# What Actually Happened
AI OPEN DOOR KEEP OPEN THANK

**Comment by PrimeDSS13** [comment]
feature
