### ISSUE TITLE
Vox Spacesuit Mobs Die to Atmos Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31325]
(WEB REPORT BY: burntdevil REMOTE: 206.221.180.138:7777)
# Revision
3d8ae507e4f11ba7ba8fdc4bd53a4c9b0513d68b

Spawned a bunch of Vox mobs in spacesuits, which normally survive in vaccum or you know, any other enviroment, and they just fell over dead. There's an issue somewhere.

**Comment by Eneocho** [comment]
Did the mobs have nitrogen tanks?

**Comment by kilozombie** [comment]
> Did the mobs have nitrogen tanks?

Hostile humanoids (and Vox hostiles by extension) are simple animal mobs, they don't actually use internals, they use some shitcode around their maximum and minimum pressure or required atmosphere. It's probably been broken for ages

**Comment by Eneocho** [comment]
Are all animal mobs like that? Because I remember one experiment I did where all my monkeys died to CO2 because I had like 200 in the same 2 tiles.

**Comment by kilozombie** [comment]
I believe all animal mobs are like that, yeah. Monkeys may or may not have something like a MIN_O2 var or whatever. I can check if you can't

**Comment by Exxion** [comment]
Monkeys are carbons, not simple animals

**Comment by DeityLink** [comment]
https://github.com/vgstation-coders/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/simple_animal/hostile/human/vox.dm indicates that they (even the spacesuit wearing ones) have no custom minbodytemp, meaning they'll probably die of cold in space.
