### ISSUE TITLE
Garbage bags don't fit in janibelts anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31336]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description
Garbage bags used to fit in janibelts, but now they don't, because they're the same size as the belt. I blame MM for this.

**Comment by Kurfursten** [comment]
I was told months ago that this isn't the case when we talked about orderly biobags, not sure whether it has always been that way or not

**Comment by DeityLink** [comment]
It's always been that way, don't believe fake news.
