### ISSUE TITLE
Isand Station: Cargo Supply shuttle does not leave the dock.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31338]
(WEB REPORT BY: crudequip REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description
what it says on the tin

# Steps to Reproduce

# What you Expected
it to leave and return when the ETA had elapsed

# What Actually Happened
crates disappear when the shuttle "leaves", and appear when it "arrives" but the shuttle stays

**Comment by west3436** [comment]
Island is no longer included in the map rotation.
