### ISSUE TITLE
Island Station Disposals is a Loop

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31343]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description
The disposal route seems to be a loop with no exit.

# Steps to Reproduce
1. Hop into disposals to avoid dinos.
2. Stuck in endless loop around the station.
3. I want off Island Station's Wild Ride.
# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Closed via #31354
