### ISSUE TITLE
A malf AI can spawn alongside a non-malf AI

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#31346]
#### Description of issue
>[20:45:15]ADMIN: (nakerbott) started the game as a AI.
>[20:45:15]ACCESS: Logout: *no key*/(Nakerbott) (AI Chamber - 226,241,1)

>[20:45:15]ADMIN: DYNAMIC MODE: Picking a  ruleset...<font size='3'>Malfunctioning AI</font>!
>[20:45:15]ACCESS: Logout: *no key*/(Levi Whirlow) (AI Chamber - 230,241,1)
>[20:45:15]ACCESS: Login: Curver/(790) from [NOPE] || BYOND v514
>[20:45:15]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">Curver/(790) <span title='malfunctioning AI'>(A)</span> is now a malfunctioning AI. <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=230;Y=241;Z=1'>AI Chamber - 230,241,1</a></span></span>

memes aside this is a big bad and should not ever happen without admins pressing buttons

**Comment by ShiftyRail** [comment]
based

**Comment by SonixApache** [comment]
Based on what?

**Comment by SonixApache** [comment]
probably fixed

**Comment by SonixApache** [comment]
i saw this happen again on snaxi yesterday also #31439

**Comment by anunknownentity03** [comment]
feature

**Comment by nervere** [comment]
Seems to have finally been fixed in #31796
