### ISSUE TITLE
Island Station Jukebox transmitter instantly overheats in its tiny room

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31344]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
6789b69609d1c7787640ef3d2e97e4b469abd6a8

# Description
title
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Still an issue following #31354

**Comment by west3436** [comment]
Island station is kill please close @Kurfursten
