### ISSUE TITLE
Dynamic is picking restricted roles and people with their preference set to NEVER for rulesets.

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#31355]
On different rounds, I've seen a CMO and a HOP get picked for cult when they normally can't roll it roundstart. 
I've also seen two people with cult set to NEVER roll cult roundstart.
This is probably related to #31346 and likely caused by #31104

**Comment by Exxion** [comment]
Only vaguely related but I'll also point out that I *always* spawn as a traitor on my local server whereas I used to never spawn as an antag at all
