### ISSUE TITLE
it appears that latejoin rulesets are recruiting living players

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#31367]
#### Description of issue
guessing based off of this last round where we had 
```
(latejoin) - Ragin' Mages
(latejoin) - Syndicate Infiltrator
 ``` 

and i was a miner that got yoinked into the wizard den and someone else in OOC said 
`OOC: Pulserider: i was made a traitor with like 29 seconds left until the shuttle arrived, i didn't get a code though`

**Comment by ghost** [comment]
Did it show you your assigned job with all the "you are the [x]" stuff just before you rolled wizard too?

**Comment by SonixApache** [comment]
Just this.
![1637456696 Honk_Fortress_Victor](https://user-images.githubusercontent.com/8468269/142749585-b6401769-a7f6-4374-b659-3dca18332e79.png)

**Comment by west3436** [comment]
happened to me today as traitor - screen went black then i got the prompt asking me if i wanted to be a ninja
