### ISSUE TITLE
Island Station - Jukebox Transmitter Still Overheats

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31365]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
3d4cad4f9966fb21aeebbfb8fc517041809604eb

# Description
default setup still leads to xmitter overheating
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Duplicate of #31344 because I'm a retard
