### ISSUE TITLE
Clone Backups

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31363]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
3d4cad4f9966fb21aeebbfb8fc517041809604eb

# Description
Clone backups seem wonky. A backup was made of myself and then I died(by bible fart). I was unable to be cloned despite the backup existing. I then came back as a man from ancient cryo pod and died. Then I was able to be cloned again. Admin said something about the computer being unable to access the mind.
# Steps to Reproduce
Die with backup made
Fart on bible(Walk into shard?)
Attempt cloning. Nope.
Come back from ancient cryo(mice? posi? ruskie crab?)
Die
Get revived from first backup
# What you Expected
Backup after first death
# What Actually Happened
Mind fuckery?

**Comment by Eneocho** [comment]
Seems like that legacy code thing that needs the brain to exist for a clone backup to work.
