### ISSUE TITLE
duny

### ISSUE THREAD

**Issue by jewishneocon** [d3athrow/vgstation13#3136]
dunys an issue i dont like him please remove from codebase

**Comment by ComicIronic** [comment]
Wontfix.

**Comment by Probe1** [comment]
after a short search I found the culprit.  there are no fuck you dunys in the code.  not only does this represent a security threat (we cannot get valids and antag roles without saying fuck you duny) but its shoddy work.  

![proof](https://cloud.githubusercontent.com/assets/8550416/6314155/4559fbc0-b9a0-11e4-9b04-e70aa968ec06.JPG)

i'll hotfix this immediately.

**Comment by clusterfack** [comment]
You clearly left out #conflict, #honk, and #needsmoretesting. Also I literally cannot believe there isn't even a single fuck you duny in the code. Just wow, mind blown.

**Comment by ComicIronic** [comment]
I don't think it needs more testing at all.

**Comment by IratePirate** [comment]
Could Travis even get a grip on the issue?

**Comment by SkowronX** [comment]
Confrictu

**Comment by Riukanojutsu** [comment]
@IratePirate We did a merge test with the player base and it didnt work.

**Comment by N3X15** [comment]
Hate to combo break, but it'd be nice if this didn't turn into TG's github where every third issue is a fucking joke issue.

**Comment by clusterfack** [comment]
I dont know, it'd be almost preferable to "github, what's that?"
