### ISSUE TITLE
tag mode ends the round immediately

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31379]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
1396851f9b52ee8ca6e5a6576df23dc040a044c6

lol

**Comment by gurfan** [comment]
The game didn't seem to assign any mime roles, saw that there were no mimes alive, and ended the round.

**Comment by Eneocho** [comment]
![Based Tag Mode](https://user-images.githubusercontent.com/67024428/142810813-0115d6c9-16a3-472d-9cb0-8b98f3d9f2e7.png)
Fastest win. Thank you based admin for the ultraspeed balids.

**Comment by ValkyrieSkies** [comment]
Does it need a round end confition in the first place?

**Comment by Eneocho** [comment]
@ShiftyRail
