### ISSUE TITLE
Monkey Madness doesn't work when forced as a role

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#31377]
What it says on the tin, I set a guy's role as a monkey madness monkey and put him in the faction, then monkeyized him, and when he bit people it didn't turn them into monkeys.

**Comment by DeityLink** [comment]
Jungle Fever was never quite properly ported to datums was it?

**Comment by ShiftyRail** [comment]
Works on my machine. Just need to not give a faction.
