### ISSUE TITLE
Air alarm interface keeps re-opening after being closed

### ISSUE THREAD

**Issue by Skullyton** [d3athrow/vgstation13#3138]
During Defficiency, I was checking on an Air Alarm, then closed it after I had done what I needed to do. A few seconds later the window re-opened, so I closed it again, to which it re-opened again.

It seems to happen if somebody changes the active menus, or when the pressure or temperature changes, but it only seems to happen to certain Air Alarms (The TComms one doesn't keep re-opening, whereas a place like the RDs office does)

I managed to stop it for a while by relogging, but that doesn't seem very time efficient to have to keep logging in and out after checking each alarm.

**Comment by Duny-** [comment]
Most probably not a map issue

**Comment by eswordthecat** [comment]
Not a map issue, i'll fix this.

**Comment by Skullyton** [comment]
If it makes any difference, it's doing the same thing with the voting panel as well

**Comment by eswordthecat** [comment]
Make a seperate issue for vote.
