### ISSUE TITLE
metaclub permabrig has an air miner in it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31388]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
1396851f9b52ee8ca6e5a6576df23dc040a044c6

# Description
There's an air miner there, as in a gas miner that produces 100% normal air. These are not supposed to ever be available.

**Comment by Eneocho** [comment]
I can barely see the problem with air miners being available. It's not like they're dangerous (when compared to pure o2 miners, plasma miners, co2 miners or n2o miners).
