### ISSUE TITLE
Using a Seer Talisman to travel through hidden Pathway runes hides all concealed runes for the duration of the Seer Talisman. CULT 4!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31382]
(WEB REPORT BY: kumarus REMOTE: 206.221.180.138:7777)
# Revision
1396851f9b52ee8ca6e5a6576df23dc040a044c6

# Description
https://files.catbox.moe/f55apw.webm
# Steps to Reproduce
>hide pathways
>use seer to reveal
>use teleporation
>can no longer see concealed runes until the seer talismans effect has expired
# What you Expected
to still be able to use concealed runes
# What Actually Happened
i can not use concealed runes after teleporting

**Comment by DeityLink** [comment]
Oh boy that's gonna require some snowflakey fix. Blood jaunts give you some see invisible that you lose upon arrival, and Seer also gives you see invisible for its duration, so each need to be mindful of the other.
