### ISSUE TITLE
Latejoin Traitors do not get uplinks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31387]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
1396851f9b52ee8ca6e5a6576df23dc040a044c6

# Description
latejoin on island
don't see an uplink code
ask the admin what it is
they inform me I dont even have an uplink

**Comment by SonixApache** [comment]
unforeseen consequences
