### ISSUE TITLE
Mirrored filters are broken

### ISSUE THREAD

**Issue by Duny-** [d3athrow/vgstation13#3140]
One of the outputs seems to never connect. The MoMMI who reported problems with filters to me did an experiment after we discussed it:
![ss 2015-02-21 at 06 33 56](https://cloud.githubusercontent.com/assets/5224390/6312983/f230663e-b993-11e4-8f15-f1cceeb86306.png)

**Comment by ComicIronic** [comment]
Is it actually functioning and the connection sprites are broken, or is it broken?

**Comment by clusterfack** [comment]
A mommi reported that the pipes were checking the opposite direction for node 2
