### ISSUE TITLE
You can use the hookshot to cheat in Sokoban

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31416]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
5b727afe93d903e184a1282b614acd06c0dd0940

# Description
you can use the hookshot to pull sokoban crates making it a cakewalk

**Comment by DeityLink** [comment]
Emergent gameplay 😌

**Comment by Dacendeth** [comment]
There are so many ways to cheat in sokoban
