### ISSUE TITLE
Captain's Log 165: The Longest Station

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#31413]
It is the indomitable spirit of Man that drives him to explore, to seek out the lands Providence has provided to us and take in their grave beauty, whether they be the hottest stars or the cold emptiness of the void. Though Mother Earth mourns the sons she may never see again we have not forgotten her, and many manmade lights dot the blackness as oases to mirror her splendor. It is one such oasis (though whether this name be apt remains entirely up to you, dear reader) that I have visited in my travels quite recently: **The Island Station.** 

The Island Station, named so for its many "islands", carries the simple naming scheme once common to sailors and reflected in many lands even today, from Long Island to Whoresfield, and is connected by many bridges.
![capt7](https://user-images.githubusercontent.com/51391726/143292950-8b6ba446-7030-46bb-9fc4-0d9b1744eaa8.PNG)
The bridges span to and fro the entire complex, taking for themselves the lion's share of its size. The Lord above knows better than I that I have no evidence, but I'm rightly certain that the station I tread was nothing more than a scheme to create a new labyrinth, one to hold a thousand Asterions within its winding walls. There's no other explanation for the corners cut and the choices made, which I shall detail below:

**The Barren Brig**
![capt9](https://user-images.githubusercontent.com/51391726/143299113-56a6a44e-a7ec-4e53-8808-87eaed2d3209.PNG)
There's often little incentive for a brig funding. The only people that'll ever see it are prisoners and, perhaps worse, the brigmen themselves. That said, there are quite a few corners cut that'd make this slice of hell more fit for a small station, certainly not one of this size. The rechargers are stacked to save space and the computers follow this grim trend. The cells are smaller than a freightship cabin and, in the builder's haste to finish the straw house, a floodlight in the south has been attached to a door. The vast, cavernous interior lobby is partitioned into offices fit only for dwarves, and this space-saving transitions on to the entire station.

**Built for Bacteria**
![capt6](https://user-images.githubusercontent.com/51391726/143303679-72c60506-74d7-4fdf-bc39-3c146cb44d9c.PNG)
The entrance to the Virology is bleaker than most, a tiny room flanked by washing machines stacked atop eachother like a Haida totem pole. The only useful addition here is the ashtray, something that'll see quick use thanks to its proximity to the vendor as well as the tomblike interior of the vessel. Once past these doors a man is greeted to another tiny room the same size, but this time empty. A common legend says that at one time many washing machines lived amongst the entrance rooms, and it was only once the Virologists came bearing weapons of unfathomable fury that they were relegated to reservations, forced to live in miserable conditions on a single tile.
![capt4](https://user-images.githubusercontent.com/51391726/143304730-9ca64813-cfc0-4b6a-b2f9-a877c5c4376a.PNG)
Here I stand with the ~~freak~~ man himself. His office, like many, isn't particularly notable, though he did find great trouble with finding his dishes, something only resolved when I opened his wall locker and they spilled onto the empty table. Why they aren't simply on the table to begin with, like every other port, is a matter of grave debate, though personally I feel that, in a moment of brief clarity, the architects personally hid the dishes after finally understanding the pointlessness of the craft.
![capt3](https://user-images.githubusercontent.com/51391726/143305856-c0f074d3-9147-48b9-9fb8-1ca81e069a27.PNG)
The rest of medbay is rather unremarkable, though it seems that the builders forgot to bring in sinks at some point and and took to pouring water in a hole instead. 
![capt17](https://user-images.githubusercontent.com/51391726/143306598-75b05530-3a76-475b-a31f-671058c7dcfc.PNG)
And thus I leave Medbay, though while passing through I marveled at the power and influence of the Medical Reception Builder's Union, typically they only get one job per station.

**The Captain's Half Dollars**
![capt2](https://user-images.githubusercontent.com/51391726/143307455-8a99c503-bb30-46e5-ac38-19948f312b2a.PNG)
My own office is vast, larger than a whale with only half the smell. Central Command deems fit to provide an unfinished sword in the cabinets, whether that be a symbol of the ever-unfinished work of a Captain or the laziness of the builders is up to the reader's interpretation. That isn't the end of it either, what follows is a large vault and a truly king-sized bathroom. While I'm loathe to give up the only bathroom I've ever embarked on that reflected my greatness, the vault's use is debatable on account of it's as barren as a hag and most captain's don't accumulate enough riches in the few hours we supervise to justify it. 

**The Scientist's Plight**
![capt11](https://user-images.githubusercontent.com/51391726/143308758-c6337b4b-2bb8-4a30-9f1b-297d142e990c.PNG)
Over the course of my travels here I met a scientist who came to me, tears in those unfeeling scientist eyes, and cried about his unrequited love. He was wholly unable to visit the rocks he held with an almost religious reverence, and the conditions he faced in his daily work would make even a chimney sweep take off his dusty, child-sized hat in respect.
![capt12](https://user-images.githubusercontent.com/51391726/143309570-f49ef2b7-7860-4ce4-adde-7adc0c0863cc.PNG)
For a xenoarcheologist,  light is but a distant memory. No golden rays litter the halls like your typical department, instead the sheer darkness is meant to prepare the poor soul for what will become 40 years of their life digging for ancient spoons. The scientist, still sobbing, explained to me that the department didn't even have his tools. The 0.492126 foot pickaxe, which I am told is critical for taking useless garbage from the maw of the asteroid, was simply not provided.
![capt13](https://user-images.githubusercontent.com/51391726/143310266-1a746575-2694-4a51-ada3-cbe67f284a05.PNG)
He then took me to the door outside, before trying to fruitlessly open it. At this point the scientist kneeled down and tore at his garments like a biblical prophet, decrying the good name of the architects who forged this station and fate which had cruelly kept him away from his most beloved rocks. Though there were no doubt other entrances, and, as any Captain's Spare can attest, a locked door rarely keeps a scientist away, the xenoarcheologist could not find another exit. 

Now, dear reader, you may ask, "With so many corners cut, where did the funding go?". It has been made abundantly clear to me through my time aboard that the architects were less interested in making a station than making:

**The Hollow Hallways**
![capt14](https://user-images.githubusercontent.com/51391726/143310838-09bca6eb-b660-431c-9b7f-a77c60fae1f4.PNG)
The bureaucrats call this land an island, though I would liken it more to a spider web. It's quite easy to be caught in the strands that line the entire station, little enclaves of emptiness to cut the departments and make any travel abroad into a week-long trek. They permeate throughout the structure, stemming from the bridge into the halls and deep into the darkest corners of maintenance that only the pipe goblins dare tread.
![capt16](https://user-images.githubusercontent.com/51391726/143311105-011547a1-22e1-4f3a-838b-d0675062b6bc.PNG)
There lie about 16 in total and by and large serve little to no purpose that I can spy. Typically a hallway is meant to connect two rooms together, but, with a slice fit for a Gordian Knot, these areas could be cut with no grief to the crew or their fair station.

![hallways](https://user-images.githubusercontent.com/51391726/143311875-ec0a6e16-5b1a-4123-8be7-29535bc508a8.PNG)

When combined with the sorry state of the brig one has to wonder at what cost the hallway budget was increased, why were these hallways, which only serve to separate the crew from their fellow man both physically and spiritually, necessary? It's clear now that this station is a mere setup to contain a greater monster, whether a half-bull minotaur or something much greater. The crew, if they can be called that, are simply set up as bait for whatever monstrosity is foolish enough to take it, only to be caught in the web woven by the grand architects of Nanotrasen. If any reader of mine dares to visit Spiderweb Station, I do ask that they carry a knife close and hold fast to their courage, for both will be necessary when the beast arrives.

**Comment by Servalfang** [comment]
he's not wrong

**Comment by Eneocho** [comment]
You forgot to inspect Engineering, captain. It's terrible.

**Comment by ghost** [comment]
"eh" -burnt devil
