### ISSUE TITLE
You can enter vents as a SAMMI, but can't move and thus can't get out.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31429]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
e85a77501eba90655954a1c0bf16bd3a9c51b0cc

# Description
Title
# Steps to Reproduce
click on a vent?
# What you Expected
Nothing, it happened accidentally.
# What Actually Happened
SAMMI STUCK

**Comment by Servalfang** [comment]
as a what

**Comment by Eneocho** [comment]
Stationary Assembly MMI. A MoMMI with ONE directive that can't move from its spot.
