### ISSUE TITLE
Duplicating machine parts on taking apart Comms

### ISSUE THREAD

**Issue by Skullyton** [d3athrow/vgstation13#3142]
After rebuilding Comms twice, upon the second time of having to take the machines apart to rebuild them, I was given 2 sets of parts, one set of parts was located on the machine frame, the other at the point I was standing.

**Comment by clusterfack** [comment]
I happened to have fixed this with https://github.com/d3athrow/vgstation13/commit/cdc6bb038e8780d97b103dcd0a01f9c565cf784c, unintentionally
