### ISSUE TITLE
Boxstation medbaaay door directional access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31423]
(WEB REPORT BY: cmdrstupid REMOTE: 206.221.180.138:7777)
# Revision
f488cb7817061643880ecea37ca3d97e109daf80

# Description
Boxstation medbay doors are openable without any access if used from a diagonal direction.

# Steps to Reproduce
Put ID in backpack and click on medbay door while adjacent to it diagonally.

# What you Expected
An angry double buzz and red flashing lights.

# What Actually Happened
Door opens for any or even no access.

Thanks!

**Comment by Eneocho** [comment]
Intended if from the medbay side (that directional access pr thing).
FEATURE(TM) if from outside.

**Comment by Rhimrifer** [comment]
I was able to open Medbay doors diagonally from the wrong side without access from both entrances on Asteroid.

**Comment by Eneocho** [comment]
I dunno chief, sounds like a FEATURE(TM) ALL RIGHTS RESERVED to me.
