### ISSUE TITLE
You don't retain your original ghost sprite after you ghost from a SAMMI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31437]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
00a172457e4e2d98803fad5047cc03808d26f04e

# Description
My original ghost sprite got overriden by the SAMMI sprite after I ghosted from the SAMMI

# Steps to Reproduce
1- Ghost as any humanoid shaped species
2- Enter a SAMMI
3- Ghost
4- Now your ghost sprite is a SAMMI

# What you Expected
My original ghost sprite

# What Actually Happened
*beeps from beyond the grave*

**Comment by Eneocho** [comment]
Your name also changes.
