### ISSUE TITLE
Advanced Holograms Suffocate

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31435]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
00a172457e4e2d98803fad5047cc03808d26f04e

# Description
What it says in the title. Holopeople will suffocate if there is no air. Why do holo people need air? They probably die to other things as well such as lack of pressure maybe.
# Steps to Reproduce
Have Island voted for
Become holoman on Vox holodeck
Suffocate Slowly
# What you Expected
Only care about holodamage. 
Not require holo lungs
# What Actually Happened
Die because Vox holodeck makes human holoman.

**Comment by adacovsk** [comment]
lol
