### ISSUE TITLE
Dusky's Bizarre Adventure

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#31438]
Your next line is:
![dusky](https://user-images.githubusercontent.com/51391726/143657993-95185443-74b1-403f-baf1-dcc80f79465b.PNG)

**Comment by BomberBro** [comment]
This is from the Roid Bar vault.

**Comment by Exxion** [comment]
The classic "`Hear()` gets called before messages show up in chat for some fucking reason"
To be clear this is always the case and things that respond properly have code to do so

**Comment by Eneocho** [comment]
Just add a 0.5s delay.

**Comment by ghost** [comment]
i thought i did add a delay
worked in testing
weird

**Comment by DamianX** [comment]
Without the changes in #31421 there is indeed a delay, but it delays everything including the original "say" that the bot responds to, because there is no `set waitfor = FALSE`.
