### ISSUE TITLE
The Bhangmeter (on roid, at least) is cursed and causes your game to lag into hell and eventually crash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31453]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
81f4042e2a3ea8abea6a0cc816a5a0dc90e8e28c

# Description
title
# Steps to Reproduce
touch bhangmeter on roid
# What you Expected
frames
# What Actually Happened
features so bad they send your soul to space brazil

**Comment by SonixApache** [comment]
the bhangmeter in general does this, roid just does it more because it's too fucking big
