### ISSUE TITLE
Emagged doors when pryed open dont leave broken electronics.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#31450]
Supposed to be busted and require soldering, but they're just blank functional electronics.

**Comment by CptWad** [comment]
not blank they still have their old access assigned to them

**Comment by Dacendeth** [comment]
I pried electronics out of a sec door and put it back in and it didnt have any requirements on it.

**Comment by Dacendeth** [comment]
Looks like #31447 fixed this if I had to guess.
