### ISSUE TITLE
[Box] Hydro need another light

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3145]
![full-0](https://cloud.githubusercontent.com/assets/3959840/6313425/eaa13388-b95e-11e4-8c65-6cbbc8c108d0.png)
Right there
A small one
There is not enough light there for light sensitive plants
It may not look like it but for the new hydro shit you can LOSE plants in this death zone.
Pls fix

**Comment by Killette2** [comment]
I can testify for this, the light should be under the last hydro tray tile, near the sink but not right above the sink. If you plant a dionae pod there without any bees, it will die because the lumens are around 6 instead of a healthier 8
