### ISSUE TITLE
Remove fetish content from Island Station

### ISSUE THREAD

**Issue by RefinedVGgentleman** [d3athrow/vgstation13#31452]
Now on GitHub™, just like the admins like it.
Link to the original forum thread: http://ss13.moe/forum/viewtopic.php?f=49&t=6058

It recently came to my attention that our fine codebase and our fine server have been sullied, defiled and tainted. You see, recently a person called "BurntDevil" (a player, admin and mediocre mapper on this fine server) has added his map "Island Station" to our map rotation.
This map features a small garden area, slightly south of the medical bay, containing a punching bag. This item features a modified sprite. Furthermore, there is another modified item in aft-port maintenance, near the solars.

The problem lies within these two items, here you can see them pictured.
![image](https://user-images.githubusercontent.com/95150373/143723163-23914f25-6b19-4309-9361-3e9080559f61.png)
![image](https://i.imgur.com/eqyznnj.png)

You, an observant gentleman, might suggest that these are merely generic gnomes and not fetish content. While that is true at first glance, there is some context that the /vg/ playing gentleman must consider before reaching a verdict on these gnomes.
I would have no problem with these if they were created by somebody else (although the assistant gnome is quite similar to the assistant miniature figurine that is already in our codebase and thus not really necessary to add to the game), but sadly these sprites were "drawn" by the aforementioned player, admin and "mapper" BurntDevil.
BurntDevil is quite notorious for his sexual deviancy, especially in regards to gnomes. I have compiled a small album of images, showing BurntDevil posting his sexually suggestive sprites of gnomes on the /vg/station Discord server or simply stating his sexual attraction to these fictional creatures.

> ![amount of gnome messages](https://user-images.githubusercontent.com/95150373/143723214-6bb20008-6e37-4954-b4bf-048fd242e613.png)
> **Here you can see the amount of messages containing the word "gnome" BurntDevil has posted to the /vg/station Discord.**
> 
> ![gnome woman sprite](https://user-images.githubusercontent.com/95150373/143723226-7d623821-0c36-448d-ba9b-a98c1154de7d.png)
> **A "gnome broad" in a revealing dress, crated by BurntDevil**
> 
> ![tiddydress gnome](https://user-images.githubusercontent.com/95150373/143723218-488df216-8f6a-45e9-9205-927eaacb59ea.png)
> **More of the "gnome broad", this time titled "tiddydress gnome"**
> 
> ![gnome gif](https://user-images.githubusercontent.com/95150373/143723243-6d8add40-7e20-4e09-a11e-d888c4f1d75f.gif)
> **An animated .gif created by BurntDevil, showing the "gnome broad" aka the "tiddydress gnome"**
> 
> ![hottub gnome](https://user-images.githubusercontent.com/95150373/143723258-c7479f0b-a1e0-40e4-9ab0-712b77aec249.png)
> **A female gnome in a bikini sitting in a hot tub. Apparently created by BurntDevil for another gnome lover.**
> 
> ![i would if possible wow gnome](https://user-images.githubusercontent.com/95150373/143723263-59cd28df-5751-4c3a-9682-0452f382d98f.png)
> **BurntDevil voicing his urge to have sexual intercourse with a female gnome from another video game.**
> 
> ![nigga i'd fuck a gnome](https://user-images.githubusercontent.com/95150373/143723272-8ce0cc62-decc-4c5e-925a-7981eacc608c.png)
> **No comment needed**

**Now you might say, how are these related to the gnomes found on Island Station? Well...**

![burntdevil showing gnome collection](https://user-images.githubusercontent.com/95150373/143723317-318b3edb-ee18-4b59-90f1-56020473a499.png)
![gnome collection circle](https://user-images.githubusercontent.com/95150373/143723331-864b0178-933e-4367-8ea6-e609be568f59.png)

If you take a look at the circled gnome sprite, you can clearly see that it is the same as the one found in the garden area on Island Station. This sprite is literally in the same file as his other fetish sprites such as the "tiddydress gnome".

Now tell me, gentlemen of /vg/station, do you truly want gnome sprites, created by a man with a gnome fetish, on your server? A man who has created some vile fetish images of said creatures? I say, do not enable this behavior, as it might spiral out of control. Today it is a generic gnome sprite, tomorrow it is the "tiddydress gnome" added to your server.
I request the removal of the two gnome sprites from Island Station.

Thank you for your attention, gentlemen.

**PS:**

![Island](https://user-images.githubusercontent.com/95150373/143723341-cd2de50e-9eb8-4b0d-b467-feebadc15f7b.png)

**Comment by SonixApache** [comment]
oh great, now the thread schizos are leaking onto github

**Comment by ShiftyRail** [comment]
The absolute madman
There's arguably nothing schizoid about this request. It's a bit extreme, though.

**Comment by west3436** [comment]
this would've been such a quick and easy thing to thumbs up if you didn't go on a week long schizo jihad over this on the thread and forums

**Comment by djkramer123** [comment]
remove the assistant one since it references a static iirc, the regular garden gnome is fine and a weird thing to be so obsessed about

**Comment by Exxion** [comment]
Assistant one that references a static should totally go. I can't even imagine caring about the other one either way.

**Comment by smalIboss** [comment]
get rid of the assistant one for sure

**Comment by Viciousaurus** [comment]
Remove assistant gnome.
Leave lawn gnome.
Make Burnt explode if he holds a gnome in his hands.

**Comment by BomberBro** [comment]
The PR would take like 2 lines of change if you want to make it yourself, DMM isn't that complicated but you might need assistance with git.

**Comment by SECBATON-GRIFFON** [comment]
replace them with latex voxes, clearly

**Comment by N3X15** [comment]
The way I'd recommend approaching this would be:

1. PR to remove assistant gnome
2. PR to remove lawn gnome
3. PR to remove Burnt

**Comment by Kurfursten** [comment]
I wasn't aware that the assistant one is a reference to a static and if it is I support its removal

Although we have the Toy Snowflake and Toy HoPtard I don't think we want to go in the direction of more references.

**Comment by SageOfLight** [comment]
I'm fukken dead.

**Comment by Optimism333** [comment]
Just another day on gnome station 13

**Comment by jubisloviu1** [comment]
Ticker tbh
