### ISSUE TITLE
Astral Projection on Moving Shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31455]
(WEB REPORT BY: magicgarbage REMOTE: 206.221.180.138:7777)
# Revision
e9cc5567301931778ecb32597f261757b2d3c03c

# Description
Astral projecting while the shuttle moves gibs you on landing
# Steps to Reproduce
Astral project on a moving shuttle
# What you Expected
To not become a meat pile
# What Actually Happened
The g-forces tore my body and soul to shreds

**Comment by Eneocho** [comment]
Shuttles clearly exist in the astral plane too, it's the only explanation for them crushing your astral form.
