### ISSUE TITLE
The NT Microstation vault's double airlocks are misplaced.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31458]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
145612a93ed040e9b81cc0d685ae48f36f0fd163

# Description
Found the NT Microstation, saw that the double airlocks are encrusted into walls and they don't align properly with the hole they are supposed to cover

# Steps to Reproduce
1- Go to the NT Microstation
2- Pick up a weapon

# What you Expected
Airlocks properly installed

# What Actually Happened
Not that

**Comment by ghost** [comment]
probably was a consequence of map rotating, happens with those kinda doors, its disabled now

**Comment by west3436** [comment]
Rotation is disabled on the microstation now
