### ISSUE TITLE
Smartfridge issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31469]
(WEB REPORT BY: cptwad REMOTE: 206.221.180.138:7777)
# Revision
bd2827898e618f83950aefb1df25db67603346bf

# Description

Creating a smartfridge using RnD only allows for storing hydrophonics products
You should be able to multitool the board so you can have a chem smartfridge

**Comment by ghost** [comment]
Use a soldering iron on the board.
