### ISSUE TITLE
Ministation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31476]
(WEB REPORT BY: sootybear42 REMOTE: 206.221.180.138:7777)
# Revision
ad228795b09491ed99577e0a0cca55e8851adce3

# Description
Ministation Issues-Since it's flipped sometimes the double doors are broken and there isn't a destruction analyser or chem dispenser to do research
# Steps to Reproduce
Find ministation doors broken
# What you Expected
Doors to be normal
# What Actually Happened
Doors not normal and flipped

**Comment by Eneocho** [comment]
I told them that you'd need at least a destructive analyzer, but they didn't listen.
