### ISSUE TITLE
[Feature Request] colt single action army accidental discharge

### ISSUE THREAD

**Issue by godietxt80** [d3athrow/vgstation13#31478]
this is the greatest handgun ever made- *shoots own leg*

cowboys (famously) kept only 5 bullets loaded in their SAA, space cowboys should also stick to tradition, only keeping 5 rounds loaded, lest the shitty hammer strike the cartridge while holstering/unholstering putting a big ol' hole in the spaceman's leg.

**Comment by SonixApache** [comment]
it's a colt space action army, the upgraded model with three integrated safeties

**Comment by godietxt80** [comment]
> it's a colt space action army, the upgraded model with three integrated safeties

nanotrasen is too much of a cheapstake, older, obsolete but cheaper mechanisms are the way to go.

**Comment by Blithering** [comment]
It's a syndicate tool, not NT. Say what you will about syndies, but they make good quality murderer gear.

**Comment by godietxt80** [comment]
> It's a syndicate tool, not NT. Say what you will about syndies, but they make good quality murderer gear.

aye fair enough
