### ISSUE TITLE
Asteroid Bartender talks in Deadchat When Killed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31479]
(WEB REPORT BY: cyadox REMOTE: 206.221.180.138:7777)
# Revision
ad228795b09491ed99577e0a0cca55e8851adce3

# Description
DEAD: Cyborg states, "I should get a poker table..."
DEAD: Cyborg states, "You ever hear about those 'Goliaths'? Apparently their hide's as hard as plasteel!"
DEAD: Cyborg states, "I hear the weather on some of them planets ain't too nice to be caught out in. Especially them 'Gas Giants'."
# Steps to Reproduce
Have roid bar spawn, get robot bartender killed by mob
# What you Expected
Not this
# What Actually Happened
This

**Comment by Cyadox** [comment]
I should add that an admin during the round (I believe) respawned and killed it properly without issue. Also posting for notifications.
