### ISSUE TITLE
Master Trainer Belt Spawns Pulse Demons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31473]
(WEB REPORT BY: notaspider REMOTE: 206.221.180.138:7777)
# Revision
bd2827898e618f83950aefb1df25db67603346bf

# Description
When making a master trainer belt from your traitor uplink, it can spawn a pulse demon which isntantly dies and EMP's everything
# Steps to Reproduce
Make a master trainer belt until you get EMP'd
# What you Expected
Not to get EMP'd and be down a monster
# What Actually Happened
Pulse demon lmao

**Comment by ghost** [comment]
feature
t. pulse demon guy

**Comment by west3436** [comment]
Fixed in #33033.
