### ISSUE TITLE
NanoUI Issues

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3148]
Nanoui has some problems right now

-NanoUI refuses to close, and runtimes on close
-Adminghost nanoui gives an adminghost log on close
-Voting panel refuses to close and gains negative votes from this somehow

**Comment by d3athrow** [comment]
Should be fixed.

**Comment by clusterfack** [comment]
I believe the only remaining issue is

-Adminghost nanoui gives an adminghost log on close
still

**Comment by clusterfack** [comment]
Rechecked this

Current issues
-Adminghosts cant change APC settings
-All nanoui still give an adminlog when adminghost closing
-AAC consoles give adminlogs when non-admins use their interface
