### ISSUE TITLE
Muh freedom implant doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31495]
(WEB REPORT BY: niftyryanyan REMOTE: 206.221.180.138:7777)
# Revision
44fb21a2ddf929f23987c73fe632dd02280e3499

# Description
not much to add Im just doing the *shrug emote and its not woreking ive tried it a few times
# Steps to Reproduce
try to use a freedom implant
# What you Expected
for it to work
# What Actually Happened
it didn't

**Comment by DamianX** [comment]
works on my machine
