### ISSUE TITLE
Wraiths Suck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31497]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
44fb21a2ddf929f23987c73fe632dd02280e3499

# Description
Wraiths are not useful at all without the stunning bolts. You will lose every clickwar against someone with a gun.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
You're playing wraith wrong. You don't pick Artificier and complain he's not a combat pro

The point of playing wraith is to make so many teleportation routes that sec commits suicide because the cult can warp all over the station at will

**Comment by west3436** [comment]
I thought Wraith was supposed to be the offensive glass cannon while juggernaut is the tank?

**Comment by Eneocho** [comment]
That was before nu-nu-cult AKA Cult 4.

**Comment by Killette2** [comment]
Wraiths only purpose was to jaunt to the AI and dab directly onto it

**Comment by Eneocho** [comment]
They can still do that but are far weaker now.

**Comment by west3436** [comment]
@Kurfursten not a bug, please close
