### ISSUE TITLE
Tubes on snow

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31499]
(WEB REPORT BY: memdic REMOTE: 206.221.180.138:7777)
# Description
Tubes in the plasma chamber of xenobio are connected wrong, wich leads new borers to be stuck in between two doors if the outer one is nor opened
#Steps to reproduce
1-spawn as borer
2-try to get out of snaxi's plasma room
3-get stuck
# What you Expected
It is expected for the tube to lead in station's vent system
# What Actually Happened
Tube was disconnected

**Comment by kernikov** [comment]
Atmos piping
