### ISSUE TITLE
Pulse demon can't charge past 50k watts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31492]
(WEB REPORT BY: irish09 REMOTE: 206.221.180.138:7777)
# Revision
44fb21a2ddf929f23987c73fe632dd02280e3499

# Description
Playing pulse demon and I sat around APCs, SMEs, drained a ton of power but I could never charge past 50k. I purchased all of the upgrades and the abilities below 50k but afterwards there was no progression that could be done.
# Steps to Reproduce
Play pulse demon, go shlorp up some power from the SMEs, buy all the upgrades, get hardstuck at 50k power.
# What you Expected
UNLIMITED POWER
# What Actually Happened
Very limited power.

**Comment by ghost** [comment]
they can, its tied to the output cap level of an SME, i ahelped this guy later in game about it and notified him, said this issue can be closed
