### ISSUE TITLE
Pulse Demon: Cable Jump only works if you can actually see the cable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31502]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
ed5a0f0fa7efc9d2426ad4bb9c22e34054a4092e

# Description
you can only jump to cables that are exposed (ie tiles have been removed). this realy limits the use of this capability!

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by pedr69** [comment]
false
might just feel this way because the spell range is shorter than your vision range, trying to jump to the edge of the screen won't do anything

**Comment by west3436** [comment]
Unable to reproduce now @Kurfursten
