### ISSUE TITLE
Attempting to Insert Bolas into Full Secbelt Spawns Invisible "Movable"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31518]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
>be me
>seccyman
>getting me tacticool gear
>too much tacticool for a belt, even
>trying to cram a bola into my belt but it's full
>claims I throw bola and drops it on the floor
>check the floor and there's a bola and a "movable"
>hey dude come check this out
>it does nothing but it's weird
extremely cool thank you based bomberbroharriscord for mapping this

**Comment by DamianX** [comment]
Thank you. I have wondered where those movables were coming from for years.
