### ISSUE TITLE
Frankenlinestation Xenobio Lights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31519]
(WEB REPORT BY: rattleseaserattles REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
apc lights #3, 4, 5, and 6 didnt come on. Not sure if they do that all the time or not.
# Steps to Reproduce

# What you Expected
light
# What Actually Happened
dark

**Comment by adacovsk** [comment]
No clue why this would happen. I'll look at what's going on when the map is played again.
