### ISSUE TITLE
Suggestion/bug report - clear lockers/plastic walls

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#3152]
This is also a bug report, if you try to use plastic sheets on a girder as plastic registers as a mineral, it deletes the girder and uses the plastic rather than making a plastic wall. I think one would be neat.

I also think we should be able to have semi-see through plastic lockers. Thin lockers made of plastic that you can see through as to what's inside, as raincoats you can make with plastic are see through.

**Comment by TermedClepe** [comment]
Not all item sprites fit inside the locker sprite, meaning you'd see items visually leak out of the locker.

**Comment by d3athrow** [comment]
Termed is correct however it can be done in the same way that the storage case is. Granted they'll be tiny as shit and you cant really tell if theres a lot of them. Possibly list all the items on examine?

**Comment by Killette2** [comment]
I thought about that Termed, such as with dead body sprites being wider than a closed locker, but sprite sizes never seem to be an issue with how insane they all are anyways.

**Comment by Killette2** [comment]
Or it could force the dead body to stand up? I still don't know how this would work since some sprites are bigger than a tile itself it seems like

**Comment by d3athrow** [comment]
nope nope

**Comment by TermedClepe** [comment]
How about plastic lockers which could be colored using crayons?
