### ISSUE TITLE
Dude were my vent crawl!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31520]
(WEB REPORT BY: abumblingidiot REMOTE: 206.221.180.138:7777)
# Revision
#31477 @kane-f 
# Description
> try craw into a vent as a crab
> can't.
# Steps to Reproduce
Try to Vent crawl as a mommi
# What you Expected
Go into the vent
# What Actually Happened
Nothing.

**Comment by pedr69** [comment]
guessing this was caused by the "fix" making sammi's unable to ventcrawl

**Comment by AutismSpider** [comment]
Set mommis vent crawl to  FALSE when it should be TRUE.

Why is mommi code being touch at all for this?
