### ISSUE TITLE
Buff hydro gloves

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#3153]
Botanist gloves do very little ingame. I think they should be the only gloves that allow you to pick up nettle/death nettle without being stung/stunned(stun happens if the potency is strong enough). As of now you can pick up very sharp nettles with latex gloves even, and as a double edged sword weapon it seems silly. I think botanist gloves need more purpose rather than better than barehanded, and so botanist don't ditch them for any other glove.

**Comment by CptWad** [comment]
Yeah I usually ditch them because if I was gonna do antag shenanigans I can just make cyanide kudzu. It is not very easy to increase potency now and its easier to make death kudzu then carefully breed death nettles that you can only use with a certain type of gloves.

**Comment by Killette2** [comment]
But you can (I strongly beleive) pick up any potency death nettle with any glove. I've tested in the past where I picked it up a high potency death nettle bare handed and lost half my health and stunned, but then put on a latex glove and was fine. As a botanist any glove is better, so you might as well take a latex glove for fingerprints and bio protection or black glove for shock and fire resistance if you ever see one laying around and I could easily do a swap without going out of my way to get a better pair.

**Comment by Cisrox** [comment]
Botany3 fixed this sort of. Closeable.

**Comment by Killette2** [comment]
Not really. Any gloves still work.

**Comment by 9600bauds** [comment]
Botanyglubbs are still the worst glubbs in the entire game

**Comment by Killette2** [comment]
Even boxing gloves are better I believe

**Comment by Killette2** [comment]
Bufffff
