### ISSUE TITLE
Golems dont get eaten by singulo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31536]
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
06587834c95f399ac0abad28955002abee7f9839

# Description
Golems dont get eaten by singulo
# Steps to Reproduce
2x bag of holding someone as a golem and walk away after
# What you Expected
gibbed
# What Actually Happened
powerful anti singulo god

**Comment by Eneocho** [comment]
Duplicate of #27986.
