### ISSUE TITLE
[Feature Request] Make BODA vendomat packs obtainable without e-magging

### ISSUE THREAD

**Issue by ManopolisJones** [d3athrow/vgstation13#31535]
**BODA** Vendomats packs are currently only obtainable by virtue of either finding one placed by a mapper or e-magging a cargo console and ordering the dusty old crates pack that gives you both the nazi-vend and the commie-vend. This is quite frankly unacceptable as one, **BODA** is a third-wheel in with these two packs that are the only reason anyone that could order them in the first place would and two, **BODA** isn't even anything crazy or illegal, it's just russian soda water. 
It is due to these facts, I believe **BODA** should be given a separate cargo order that can be obtained by simply solder hacking the cargo console. I figure it makes sense given you can order normal russian shit like the outfit box that gives the ruskie DJ's transport disk or the neo-russian outfits, so why not the **BODA** vendomat packs to go with?

This Issue sponsored in part by the ASWDC (Ayy Soda Water Drinker Coalition).
[featurerequest]

**Comment by Armadingus** [comment]
just turn on antags bro why do you need this as non antag PREMIUM traitor items only

**Comment by ManopolisJones** [comment]
> just turn on antags bro why do you need this as non antag PREMIUM traitor items only

I shall give you my reasoning through an excerpt from the book **BODA** by Frank Herbert

![BODA_BY_FRANK_HERBERT](https://user-images.githubusercontent.com/89323872/153512758-8f5e96ab-017e-404a-b65d-fb866faa8664.png)

"In the year 2041, before the reign of the soda CEO, the universe was ruled by juicing machines with human minds.
The people deteriorated into a state of apathy. Then they became victims and slaves by other men with juicers. Finally began the great revolt, the religious crusade against juice. 

After the great revolt human beings were forced to develop their drinks. Thus soda training schools were established. These schools would change the history of the universe. Only two of these ancient soda schools remain. One is the Carbon Gesserit school which was established primarily for female drinkers. The function of the Carbon Gesserit school is to carry on a selective drinking program among humans.
Now the other existing school, The Soda Drinkers Guild, or The Guild emphasizes pure soda drinking. The Guild's Soda Navigators through the use of the carbonated **BODA** drink can quench space. That is to quench thirst without moving from one planet to another. It is through The Guild's monopolies on the economic life of the universe that makes it so powerful.
Know then, that it is the year 2525. The known soda companies is ruled by the soda CEO Shaddam the fourth. For many years the CEO Shaddam the fourth has ruled on planet Soadan over all the great houses of the Thristrod. The great houses of the Thirstsrod are members of the royal soda drinkers who rule or govern over the major planets of the universe, according to the ancient feudal system of government.
Two of the great houses of the Thirstsrod are the house of Cargonian on planet Coladan ruled by Duke Leto Cargonian and the house of Atraiders on planet Pepsi-Prime ruled by baron Vladimir Antagain. In this time the most precious drink in the universe is the _**BODA** Glugange_. The **BODA** extends life. The **BODA** expands consciousness. The **BODA** is vital to quenching thirst. 
Space Russia company controls the creation of the **BODA**. The Space Russia company is controlled by the soda CEO Shaddam the fourth, and the great houses of the Thirstsrod. With the Guild and the Carbon Gesserit as silent partners. This combine is the key of the wealth and political power of the universe. It is the CEO Shaddam the fourth who dispenses Space Russian directorship and contracts to the various great houses of the Thirstsrod.
The **BODA** exists on only one planet in the entire universe. A desolate wet planet with vast oceans. The planet Gully, also known as Soadrakis. Up until this time baron Vladimir Antagain has held a directorship from the CEO Shaddam the fourth. Giving him a contract to make the **BODA** on planet Soadrakis. The baron Vladamir with his two nephews the count Coalbban and Glug Atraiders, live on the planet Pepsi-Prime.
The planet Coladan is ruled by Duke Leto Cargonian, cousin of the CEO Shaddam the fourth. He resides in the ancient castle Coladan with the Carbon Gesserit lady Jessica and their son, the Dukal Heir Paul Cargonian. The CEO fearful of the dukes increasing popularity among the great houses of the Thristsrod has conspired with the dukes mortal enemies the Atraiders to destroy the house of Cargonian. 
A secret report within the guild: four planets have come to our attention regarding a plot to jeopardize **BODA** production. Planet Soadrakis, source of the **BODA**. Planet Coladan, home of house Cargonian. Planet Pepsi-Prime, home of house Atraiders. Planet Soadan, home the the CEO of all known soda companies. Send a third stage Guild Soda Drinker to Soadan to demand details from the CEO, the **BODA** must flow."

**_I rest my case._**
