### ISSUE TITLE
slow down the snaxi shuttles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31545]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
79f6e560719c8314ad3908b2cb92ef079dc6a368

# Description
the snaxi shuttles are death traps, they're faster than any sation shuttle and the warning lights might as well be labeled death lights they go around one siren and then the ship arrives, I have crushed two people in one round
# Steps to Reproduce
just see how fast they come and go it's break neck
# What you Expected
I don't know something like the mining shuttle.
# What Actually Happened
lotta gibs

**Comment by Kurfursten** [comment]
They actually go the exact same speed as any other mining shuttle, they don't have any special function to go faster

**Comment by nervere** [comment]
There is really not much more that can be done for these shuttles. They are clearly marked and fenced off whenever possible.
As Kurf points out, they also aren't any slower or faster than normal shuttles.
