### ISSUE TITLE
Grinch as of 2021

### ISSUE THREAD

**Issue by Killette3** [d3athrow/vgstation13#31548]
Got made a midround grinch thanks to a generous admin manually making it roll
Started out by getting my ghost teleported to the grinch for a split second before my ghost got teleported to the arrivals shuttle as a new observer and a grinch mob took over
Admin put me in the grinch and despite both of our best efforts we could not find a bag on me, I did generate a bag on death though. No amount of weird verbs or tricks helped
Grinch is still not very good at roleplaying as with no health regen and a small gremlin health pool you cannot roleplay away being shot by lasers

**Comment by ShiftyRail** [comment]
i really should've put more effort into this
