### ISSUE TITLE
FEATURE REQUEST: you know how wizards can summon guns/magic? well, i think it's about time for SUMMON METEORS

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31547]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
ah hello good morning crew, captain here. we've jus-
METEO-ME-ME-M-METEORS HAVE BEEN DETECTED ON COLLISION COURSE WITH THE STATION

**Comment by ghost** [comment]
no more wizard powercreep, especially not lazy shit

**Comment by Servalfang** [comment]
how is another option powercreep?

**Comment by Killette3** [comment]
This + a 40 spell point summon blob core wand
