### ISSUE TITLE
NT Microstation Vault can spawn upside down, messing up the door placement and stuff.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#31552]
[vault]
![Pizza HQ November 2021-12-07 025859](https://user-images.githubusercontent.com/67024428/144994067-aa3fdecd-b0a1-4d13-b7ae-9115166d21b4.png)
![Pizza HQ November 2021-12-07 025822 (1)](https://user-images.githubusercontent.com/67024428/144994076-a41d9a05-c784-4656-9801-bb45cdeb9489.png)

**Comment by Dacendeth** [comment]
Vault rotation as a mistake
