### ISSUE TITLE
Shroom ball feature request

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#3156]
I would like a lazarus capsule for walking mushrooms made by hacking the botany vender that gives plant food, but due to the way they work (with a special bruise feature, read the code to understand what I mean) you cannot throw the ball at the mushroom or it will make it so others cannot gain anything from eating it. The way a shroom ball should work is it will shoot a lasso like laser (like in pokemon) to recapture the shroom without it counting as an object hitting it.

A shroom ball can only hold 1 walking mushroom and it is bound to that ball. While in the ball you can name your walking mushroom whatever you want. You send it back out with the same way you beam it in, or if that's not very possible, then just throwing it like a lazarus capsule (which will probably end up bruising and breaking the enemy shroom)

The only current substitute for this is keeping your mushroom in a locker dragging it behind you, but this is obviously much better.

**Comment by Cisrox** [comment]
Closeable.

**Comment by Killette2** [comment]
B-b-but it's not added yet

**Comment by Cisrox** [comment]
Yeah but nobody will see it if it's here. If it gets closed you can reopen it then it will get more attention.

**Comment by PJB3005** [comment]
That's not how the FUCKING ISSUES SYSTEM WORKS @Cisrox 

CHRIST

**Comment by Cisrox** [comment]
ITS TERRIBLE

**Comment by PJB3005** [comment]
SHUTUP

**Comment by Killette2** [comment]
Hmmm this idea is kind of shitty looking back. Shroom chicken fights in hydro however, are still always fun. I wonder if you can pick them up, will test. In the mean time, closing this. May reopen a new issue being able to pick up walking mushroom mobs so they can have owners in the future.
