### ISSUE TITLE
Xenobotany machines provide infinite metal

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3157]
Attempting to deconstruct xenobotany machines (biobalistic and gene splicer) will result in infinite machine frames without a board when crowbar is applied, while preserving the original machine.

**Comment by d3athrow** [comment]
nice

**Comment by d3athrow** [comment]
Precursory glance shows it probably not having a circuit board to drop on deconstruction so it would runtime and fail to fully deconstruct.
