### ISSUE TITLE
Snaxi Chem lacks a syringe box.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31579]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
4859fed5ea35c650934b6732cec1bbac46a37721

# Description
It's on every map except snaxi.
# Steps to Reproduce
Join as snaxi chemist
# What you Expected
syringe box
# What Actually Happened
no syringe box

**Comment by nervere** [comment]
I fixed this a while back, forgot to link it in the PR.
