### ISSUE TITLE
Lobby screen, chem master, chem dispenser interface lag

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3158]
When opened for the first time, either of the interfaces in title will have a fixed delay of non-responsiveness, the buttons still work and will behave as expected, but without visual feedback.

**Comment by clusterfack** [comment]
I can confirm that the chem dispenser has more reports of not properly setting machine than any other machine, nanoui or not.

Also the chemmaster doesn't do anything for a long time when opening it for the first time in a new client before it updates the user dialogue at all.

**Comment by Probe1** [comment]
no longer current

@N3X15
