### ISSUE TITLE
Pulse Demon issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31606]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
1. Your max charge doesn't increase if you are in APCs, only in SMES.
2. You cannot actually interact with any machinery within the area, most likely because the Pulse Demon is not considered a proper AI.
3. Glow is still visible while under a floor. Intentional?

**Comment by ghost** [comment]
no. 3 is absolutely intentional

**Comment by Eneocho** [comment]
Also, when you take over an APC the power shuts down and I can't interact with machinery. Not sure if bug or if I just don't get it.

**Comment by boy2mantwicethefam** [comment]
@Eneocho You suck power from APCs you are inside of, if you are far from the max charge it will suck up all the power, especially if you improve your power-sucking.

**Comment by Eneocho** [comment]
No, I get that. I've had all my charge when entering an APC, take control of it and all power dies down, the APC simply stops delivering power to any machine nearby, even though it's fully charged.

**Comment by boy2mantwicethefam** [comment]
Oh

**Comment by Eneocho** [comment]
Also shuts down the lights and probably atmos as well.
