### ISSUE TITLE
Open plantbags display contents even when empty

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3160]
Using an open plant bag to load items into machines causes a visual glitch that keeps its contents displayed on screen until reconnect.

**Comment by d3athrow** [comment]
Wonder if this is related to @ComicIronic 's changes

**Comment by d3athrow** [comment]
I can't reproduce.

**Comment by clusterfack** [comment]
>I can't reproduce

Lay some eggs
