### ISSUE TITLE
Update libmysql.dll

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#31610]
If git is to be beleived, the DLL is _11 years old_.

**Comment by ghost** [comment]
will this fix the whole undeleted query issues?
also i wonder where youd find a newer one, even bay apparently still uses the 11 year old one.

**Comment by Eneocho** [comment]
Couldn't you just google libmysql.dll and find a non-sketchy website to download an update from? Dunno if a newer version exists though.

**Comment by DamianX** [comment]
We don't use libmysql.dll anymore, we use rustg.
