### ISSUE TITLE
Plasma man antag rolls (nuke ops/wizard) don't spawn with suit

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3161]
Plasma man antags such as nuke ops or wizard do not spawn with plasma man suit, resulting in quick death.

May apply to vox too.

**Comment by Ephx1** [comment]
Vox have specifically been coded for Syndie Suits and have their own Nuclear Operative hardsuits

**Comment by PJB3005** [comment]
Vox and plasmamen are both good for ops, not for wizard though

I'm gonna need some sprites for some suit to fix this

**Comment by Arthurdentist** [comment]
Vox don't need a unique sprite for wizard unless you want to give them a unique gem encrusted hardsuit, but I wouldn't consider that a huge issue. They just need to spawn with internals and a breathing mask.

Only unique sprite we need is for plasmamen,

**Comment by Intigracy** [comment]
Wizards are human only after a change by Pomf, never fear, this issue is clear.
