### ISSUE TITLE
box virology isn't connected to power grid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31627]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
2cd121808cffed99f71abb118d6b96594031b963

# Description
viro is missing 2 cables, it's not connected to the powergrid
# Steps to Reproduce
go to viro
# What you Expected
power
# What Actually Happened
no power

orange 2 cables in the pic were added by me
https://files.catbox.moe/e021g9.png

**Comment by ValkyrieSkies** [comment]
Confirmed, checked the tiles near round start and they're spawning without wires.
