### ISSUE TITLE
Some issues and feature requests for custom paintings

### ISSUE THREAD

**Issue by jellyveggie2** [d3athrow/vgstation13#31628]
I'm creating this issue so I can keep track of some of the issues that popped up on the thread during the first couple rounds with custom painting:
- [x] **Palette paint mixing is somewhat buggy**: Per anon's description, "_Not sure how to explain it really, but I tried mixing some colors for adjustment by using the palette and sometimes they just didn't mix_". Any info on which colors were involved is welcome.
- [x] **Painting remotely**: A player managed to paint on a canvas from a good couple tiles away, I either forgot to check for adjacency or fucked up. Palettes shouldn't be affected, since they're NanoUI. 
- [x] **Canvas in cargo crates come as structures instead of items**: Just mildly annoying I guess.
- [x] **Size descriptors for item canvas**: Per anon's description, "_You should make it able to tell the size of a painting when you inspect it so i don't have to sort through a pile of paintings hanging them up on the wall to see which one is a portrait_"
- [x] **Palette (item) colors carrying over to canvas palette (UI)**: A player ended up asking on LOOC if there was a way to not have to save canvas changes everytime you wanted to switch to a different color which is one of the things palettes were meant to allow you to do on the original PR, but I didn't get around to doing it.

[bugfix][featurerequest ]

**Comment by SonixApache** [comment]
put all the paintings in the round-end scoreboard
do it do it do it

**Comment by jellyveggie2** [comment]
I'm not sure it'd be wise to automatically adding every yellow-on-white penis and futa stickman produced by the round on the scoreboard.
But a way to export paintings into Base64 images would be neat as it'd open the way for admins to pick paintings to add to the scoreboard or round end credits, and also making it so you can draw on paper so mimes can doodle in-game.
Probably deserving of a feature request and PR of it's own.

**Comment by Eneocho** [comment]
I was the remote painter, yeah, it needs some sanity checks. Keep the remote painting as an astral painting kit that allows you to paint remotely.
