### ISSUE TITLE
Can't Clone Slime People

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31638]
(WEB REPORT BY: hinaichigo REMOTE: 206.221.180.138:7777)
# Revision
d44e644ea6d164c65b081bd0785eeecfd073077b

# Description
I tried putting a slime goo puddle into a cloner but it didn't go in.

# Steps to Reproduce
Drag slime puddle remains of a slime person into a cloner. 
# What you Expected
The puddle to go into the cloner.

# What Actually Happened
The puddle stays where it is.

**Comment by Killette2** [comment]
Did anyone at any point ever click the puddle to remove the brain, even if they put said brain back in like nothing ever happened?

**Comment by Hinaichigo** [comment]
I think this was fixed in #31687

**Comment by Hinaichigo** [comment]
@DamianX I think this can be closed.
