### ISSUE TITLE
Quantum linking players to machines

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3163]
Buckle a player to a movable chair
Drag chair with player next to a sleeper / cryo pod / any machine that can contain a player
Don't unbuckle the player
Click drag the player into the machine or ask him to climb in
Drag chair away
Player can now unbuckle or you can repeat this with as many machines as you want
Player is now in all machines at the same time
Any machine ejecting the player will result in him teleporting to the machine regardless of where he is

You can for example use yourself as your own DNA test dummy.

**Comment by ComicIronic** [comment]
Quality code.

**Comment by d3athrow** [comment]
Theres a fucking check in every machine for if they're buckled
