### ISSUE TITLE
C-20r 12mm magazines not refillable with 12mm ammo boxes.

### ISSUE THREAD

**Issue by Megadeadly** [d3athrow/vgstation13#31636]
#### Description of issue
C-20r mags not fillable with 12mm ammo boxes, despite saying they are 12mm. You will get a bar as if you are taking the time to fill the magazine, but it doesn't load the magazine once the time is over. I think you can't load in single bullets gotten from the 12mm ammo box, either. Loading C-20r mags with bullets gotten from other C-20rs works just fine, either mag to mag, or bullet to mag.

#### Difference between expected and actual behavior
Expected to be able to fill magazine with its supposed ammo, fail.

#### Steps to reproduce
Attempt to fill C-20r magazine with 12mm ammo box printed from an Ammolathe.

#### Length of time in which bug has been known to occur
Pretty long while, actually, I just totally forgot to put it up in issues. Couple months at least.

#### Server revision
Game: 6055659cb9a3d24a87d8a8666a5fe3922c02052a 
Patches: d2d8284cefe331992a20db0f4fedb3e1b63c7713

EDIT:
Fixed names to C-20r

**Comment by ValkyrieSkies** [comment]
CR-20 uses special ammo that isn't actually 12mm.

**Comment by Megadeadly** [comment]
Then the mags should be renamed. Either way, there is an issue.

**Comment by Eneocho** [comment]
I don't see why they should have snowflake ammo. You rarely see CR-20s outside of Ops or the very rare vault raiding round with the guy surviving. They should be reloadable.

**Comment by PavelCIA** [comment]
Doesn't Nuke Ops 12mm knock people down while normal one doesn't?

**Comment by Eneocho** [comment]
Either add the snowflake ammo to the ammolathe's contraband tab or allow compatibility with the non-snowflaked one.

**Comment by SonixApache** [comment]
nuke op 12mm has knockdown, which is why it can't be loaded into normal assault rifles
this is a feature

**Comment by Eneocho** [comment]
Then add the snowflake ammo to the ammolathe. It will only be useful if you somehow get a CR-20.
