### ISSUE TITLE
time agent doesn't link to wiki

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#31647]
i became a time agent and didn't see the wiki link
either i'm blind or there's no link
also too lazy to fix it myself

**Comment by Eneocho** [comment]
I tried to link the time agent page with the UI but I dare not touch UI code, even for a simple fix. There IS a time agent page but is not linked.

**Comment by SonixApache** [comment]
#31746 did not fix this
![image](https://user-images.githubusercontent.com/8468269/147835473-2fd5dbbe-3c2a-4218-9a3c-1fed6eb0b958.png)
