### ISSUE TITLE
Can't save paintings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31644]
(WEB REPORT BY: magicgarbage REMOTE: 206.221.180.138:7777)
# Revision
d44e644ea6d164c65b081bd0785eeecfd073077b

# Description
Can't save a finished painting after finishing my masterpiece
# Steps to Reproduce
Attempt to finalize your artwork
# What you Expected
To draw a dick to put in an art gallery
# What Actually Happened
My canvas remains dickless

**Comment by pulserider** [comment]
I tried to paint a piece with blood called "totally not blood" and my magnum opus remains unseen.

**Comment by jellyveggie2** [comment]
To clarify, I take you meant you had the painting UI open, drew a dick with a brush coated in blood, clicked save and it did not save, right?
Two things to get out real quick: Did you have the brush in your active hand? Did you move while saving? Painting is like other interactions in that you need to stand still and not be interrupted.

Anything else you can remember about what you were doing when this hapened?

**Comment by jellyveggie2** [comment]
Possibly caused by #31645
