### ISSUE TITLE
Defficiency Robotics Issues

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#3165]
- No firesuits for mechs. Hell, no firesuits anywhere on the station. Need more fire lockers.
 - No sink for washing your hands.
 - No starting posibrain. Not so much an issue, but a good thing to have.
 - No bodybag box for the debrains. Very annoying.
 - Machines are too close to the wall. Behind the fabricators, there's several tiles of empty space. In front of the fabricators, you got nothing. Move them back and open the workshop a bit more.

**Comment by Duny-** [comment]
\>Hell, no firesuits anywhere on the station
That bit is so very wrong my poor Comic. 
I'm going to look into all those issues today.

**Comment by Duny-** [comment]
All of it fixed here https://github.com/d3athrow/vgstation13/pull/3180
