### ISSUE TITLE
Frankenline asteroid z-level has the goonsat sticking out in one of its boundaries to the west

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31653]
(WEB REPORT BY: goodguy1448 REMOTE: 206.221.180.138:7777)
# Revision
496b8cae926632865462434645ea304e95d5de12

# Description
What the title says, one of the goonsat solar arrays can be seen sticking out if you toggle-station-holomap as ghost while in Z-level 5 to the east of the toxin's test chamber.

# Steps to Reproduce
1- Play in Frankenline
2- Ghost
3- Go to the asteroid (Z-level 5)
4- Click Toggle-Station-Holomap in the ghost tab
5- Check the weird green square to the east of the toxin test range
6- See the goonsat cut in half.

# What you Expected
Not that

# What Actually Happened
Just that

**Comment by adacovsk** [comment]
As discussed in my PR, the holomap takes extents greater than the z-level itself, which is the issue. It is not a map-specific issue... And I have no idea how to fix holomap extents. It might be related to #26028
