### ISSUE TITLE
you cant re-enter your real body after becoming a sammi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31662]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
ef5261ef37d43663094fe6d3b77d7163da4ae988

this is the whole fucking point of sammis why isn't this fixed

**Comment by Eneocho** [comment]
The only ways to leave SAMMI are to ghost or suicide, both methods change your former body so you're stuck.

**Comment by pedr69** [comment]
i've had it work with the cloner once (or maybe an admin did it without saying anything)
but defibs don't work after unsamming
