### ISSUE TITLE
Ministation Engineering Design Errors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31669]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
552d870af550fda58189a4cc0a136b70e0361e5d

# Description
Various bugs on Ministation (cool hobo-spawn vault!) related to engineering:

1) Disconnected atmos pipes in various areas.
2) Incorrectly set up SMES, there are two terminals attached to the APC below it and none to the SMES.
3) The power input from solars currently goes into the cable knot underneath the SMES. This is backwards. It needs to go into the SMES terminal (which isn't connected, despite the double-terminal below it attached to the APC). Power should output from the cable knot below the SMES.
4) No cable knots under the solar panels or solar tracker, so solars do not work until knotted. This is hard to notice because of the floor tiles under the solars.
5) Station does not use power (except for SMES when properly reset, provided by solars when properly reset).
6) Atmos straight up does not work for some reason, this may be related to in-game antics (admin was unable to tell if atmos was working somehow?) but should be checked.

**Comment by jwhitak** [comment]
Going to confirm that the power/atmos issues persist across rounds. It's likely some sort of vault-specific setting that's preventing the power drain.
