### ISSUE TITLE
A winter coat for janitor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31679]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
348f29631d6ca0f258fdd67a9b4142589cfcc449

# Description
Janitors don't have a winter coat
# Steps to Reproduce
No winter coat for janitors
# What you Expected
A winter coat for janitors
# What Actually Happened
There is no winter coat for janitors. Add it to the service or miscellaneous winter coat supply crate too

**Comment by drawsstuff** [comment]
ill work on spriting one for you today

**Comment by drawsstuff** [comment]
![image](https://user-images.githubusercontent.com/16404218/147118205-a37db2fa-4c22-462a-bd19-5199490d3eb2.png)
![image](https://user-images.githubusercontent.com/16404218/147118241-bc8e157b-6084-4d39-9770-06a088a43df1.png)

All done. I'll attach the files for any coder that wants to take a crack at adding them

(NOTE: Files must be turned into a DMI. Paste manually, files are slightly offset)
![janitor](https://user-images.githubusercontent.com/16404218/147118610-2108fd55-df8b-4568-ac7f-f6486c71d716.png)
![janitort](https://user-images.githubusercontent.com/16404218/147118621-2a756cb4-fd71-4184-abae-1f9da739057f.png)
