### ISSUE TITLE
Pulse Demon impressions

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#31678]
After playing Pulse Demon a whole round here is a list of things:
- Self-Sustaining Charge is incredibly powerful, it allows the pulse demon to move around with the only penalty being taking damage as if you aren't on a power net, and makes it nearly impossible to lock down a pulse demon within a certain area of the powernet.
- Engineers can shit on you from afar by disabling power output on the Engineering SMES for a few minutes, which forces you into areas with their own SMES to leech off, because sucking power out of machinery doesn't provide you with any health, only being in a powernet does. Additionally you can avoid losing health by just jumping into an APC and never coming out, which somehow doesn't count as a no-power powernet even if the APC is empty, countering the engineer strategy and causing them to cripple their own station with no power.
- Max charge is not a good system because it forces the pulse demon to suck as much power out of the network as it is being outputted, which means that not only are regular APCs useless (they have low-capacity batteries so they never raise the limit to anything above a few thousand W, which isn't enough to buy any upgrade), but it also forces you to find the nearest SMES to suck off, except that how much power you get out of one depends on its power output, which you can't manipulate if you aren't in an APC in the same room.
- Pulse demons seriously need a way to toggle whether you consume the power in a power system you entered or not, otherwise with high enough power-sucking rate you can't actually make use of any of the machinery within a room because you instantly drained the APC.
- You can't get out of an APC with no wires attached to it, even if you have Self-Sustaining Charge active.
- Upgrades have no descriptions or any indication of what they do outside of the wiki. Not even chat messages.

**Comment by ghost** [comment]
Stuff handled in #31688.

> Self-Sustaining Charge is incredibly powerful, it allows the pulse demon to move around with the only penalty being taking damage as if you aren't on a power net, and makes it nearly impossible to lock down a pulse demon within a certain area of the powernet.

Upped the cost for this.

> Engineers can shit on you from afar by disabling power output on the Engineering SMES for a few minutes, which forces you into areas with their own SMES to leech off, because sucking power out of machinery doesn't provide you with any health, only being in a powernet does. Additionally you can avoid losing health by just jumping into an APC and never coming out, which somehow doesn't count as a no-power powernet even if the APC is empty, countering the engineer strategy and causing them to cripple their own station with no power.

Fixed this.

> Max charge is not a good system because it forces the pulse demon to suck as much power out of the network as it is being outputted, which means that not only are regular APCs useless (they have low-capacity batteries so they never raise the limit to anything above a few thousand W, which isn't enough to buy any upgrade), but it also forces you to find the nearest SMES to suck off, except that how much power you get out of one depends on its power output, which you can't manipulate if you aren't in an APC in the same room.

Upped the max from APCs by a factor of 10.

> Pulse demons seriously need a way to toggle whether you consume the power in a power system you entered or not, otherwise with high enough power-sucking rate you can't actually make use of any of the machinery within a room because you instantly drained the APC.

Added one.

> You can't get out of an APC with no wires attached to it, even if you have Self-Sustaining Charge active.

Fixed.

> Upgrades have no descriptions or any indication of what they do outside of the wiki. Not even chat messages.

They very clearly do. Click "show description" in the panel.
