### ISSUE TITLE
Pulse Demon dies to Hornets.

### ISSUE THREAD

**Issue by Megadeadly** [d3athrow/vgstation13#31684]
#### Description of issues
~~While being a Pulse Demon, I lost and regained the ability to see wires seemingly at semi-random. I seemed to lose wire sight after entering an APC, then somehow got back later, then lost the ability to see them again. Power wasn't being supplied to the net (I think), so that may be related.~~
I also noticed that going through wires by hornets caused a 'Hornets stung the pulse demon', as well as getting the red edge around my screen, even though my health was stated to be 100%. I then entered the room FULL of hornets, and died instantly, unsurprisingly.

#### Difference between expected and actual behavior
~~Being able to always see wires so I can pathfind properly, and not being able to.~~
Being immune to hornets, as "Don't let your charge run out! If the powernet blacks out you'll start losing health and eventually die off! You are immune to all forms of damage and obstacles in the way of cables, but are also extremely weak to EMPs, so avoid those at all costs." Then I died to hornets. 

#### Steps to reproduce
~~Try going in and out of APCs, and seeing if you lose wire sight?~~
Go into room with hornets and get destroyed.

#### Length of time in which bug has been known to occur
First time being pulse demon, so I don't know

#### Server revision
Game: 348f29631d6ca0f258fdd67a9b4142589cfcc449 
Patches: d2d8284cefe331992a20db0f4fedb3e1b63c7713

**Comment by Eneocho** [comment]
Pulse demons are NOT immune to melee damage, but floortiles block regular melee attacks from connecting.
Hornets have no such limitations, they just sting the simplemob on the tile, no floortile check.

**Comment by Eneocho** [comment]
A fix I found for the wire sight breaking is to rapidly enter and exit both parts of a SMES unit (the core with all the storage that's connected to the grid and the terminal that's connected to the power sources). You can only see the wires on your grid and switch overlays when changing from one grid to another; sometimes you get stuck on the engineering-only grid view when you're on the stationwide grid.

**Comment by pedr69** [comment]
the hornet part is not fixed
