### ISSUE TITLE
Trader bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31685]
(WEB REPORT BY: memdic REMOTE: 206.221.180.138:7777)
# Revision
348f29631d6ca0f258fdd67a9b4142589cfcc449

# Description
I was playing a trader vox, and when I found the trader, it said that he was closed due to bad atoms. Atoms were 100% nitrogen. 
# Steps to Reproduce
Honestly, I am not sure. Guess sometimes "bad atoms" just happen and traders cant play
# What you Expected
To trade, duh
# What Actually Happened
Trader did not give me any crates even when I had the money on the table and clicked on the crate. Atoms were perfectly breathable.

**Comment by Kurfursten** [comment]
This was caused by Linestation placing a full tile firedoor over the trade window
