### ISSUE TITLE
head duplication surgery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31680]
(WEB REPORT BY: fitzbond REMOTE: 206.221.180.138:7777)
# Revision
348f29631d6ca0f258fdd67a9b4142589cfcc449

# Description
Head from monkeman attached to headless body results in body receiving head, but still having monkemanhead too.

# Steps to Reproduce
-find a headless playerbody (I had found a player's body and brain, but not their actual head, I put the brain into an MMI)
-take monkeman
-circularsaw head of on violent intent without finesse (this is what I did, I assume other forms of head removal will net the same end result, but I did not test)
-prep headless playerbody for head reattachment
-attach monkehead

# What you Expected
monkehead going from my hand onto the player body

# What Actually Happened
monkehead went onto the player body, but also still remained in my hand, i.e. head duplication.

**Comment by Cyadox** [comment]
Good report, thanks 👌

**Comment by Cyadox** [comment]
So I was in the same round this happened, and reproduced it while in-round - however, how I fixed it was doing the Help Intent saw to the mouth, removing the "invisible" head that was apparently already there (the person's original head), then reattaching it normally.

So, _somehow_, someone managed to eject someone's brain organ while also destroying the head while it was attached to the body, or the head was destroyed yet still attached.

Unfortunately, without knowing what happened to cause the head to be in this state, it's gonna be hard to narrow down how to fix it :/

**Comment by Cyadox** [comment]
Reproduced by shooting and gibbing someone's head with an Uzi (although any high-brute weapon would work). For whatever reason, the explode() proc doesn't delete the head external organ, so it still exists without the sprite being present.
