### ISSUE TITLE
All diona seeds change if diona plant changes

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3169]
When bees improve a planted diona plant, all diona seeds everywhere and future diona seeds will also get that improvement.

**Comment by d3athrow** [comment]
you what.

**Comment by TermedClepe** [comment]
The plant stats you get from plant analyzer when used on a diona plant / seed, they are always the same for every diona plant / seed, so if one gets changed all get changed. Space magic.

**Comment by 9600bauds** [comment]
This happens to all seeds
Bees are weird

**Comment by d3athrow** [comment]
Figured out, basic seed packets of a like type all share the same seed datum for whatever fucking reason resulting in changes affecting every kind.

**Comment by Zuhayr** [comment]
I'll do a fix for Bay and reference the commit here at some point today.

**Comment by Zuhayr** [comment]
https://github.com/Zuhayr/Baystation12/commit/ac233b9db7edad07e72107397e81fc221eec82d0

**Comment by d3athrow** [comment]
fancy git links are hard
