### ISSUE TITLE
Space Hobos can roll traitor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31698]
(WEB REPORT BY: irish09 REMOTE: 206.221.180.138:7777)
# Revision
4ad23bd0fe06b2c666ae869f8420aa625289b82b

# Description
Spawned as space hobo on near deadpop, got traitor like 3 or 4 minutes later while walking around.

# Steps to Reproduce
Spawn as space hobo and hope the RNG gods smile on you

# What you Expected
Comfy mining.

# What Actually Happened
No PDA nor headset uplink "Your memory clears up as you remember your identity as a sleeper agent of the Syndicate. It's time to pay your debt to them."

**Comment by ghost** [comment]
feature, enjoy it

**Comment by drawsstuff** [comment]
borers can too, feature
