### ISSUE TITLE
line cargo has no microwave

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31700]
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
4ad23bd0fe06b2c666ae869f8420aa625289b82b

# Description

no microwave in cargo

# Steps to Reproduce

go to cargo and get meat to cook
# What you Expected

to cook meat
# What Actually Happened
cant cook meat cause no microwave

**Comment by Kurfursten** [comment]
Only meta gets one of these roundstart, entitled cargo techies
