### ISSUE TITLE
Pulse Demons can't tamper with machinery if they drain all the APC power in the room

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31707]
(WEB REPORT BY: hinaichigo REMOTE: 206.221.180.138:7777)
# Revision
4ad23bd0fe06b2c666ae869f8420aa625289b82b

# Description
When pulse demons drain too much power they turn off all the machines in a room when they enter the apc, so they can't mess with the settings and such. Would be cool if they could keep it on so they could modify settings on things.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
gonna be dealing with this with the toggle ability in my new PR

**Comment by Eneocho** [comment]
@Kurfursten this one got fixed, can you close it?
