### ISSUE TITLE
Add crayons as a product of biogenerator in hydroponics

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3170]
It could poop out the whole package as found in art storage.

**Comment by 9600bauds** [comment]
The biogenerator could also use some work with the pricing, paper and cardboard are extremely expensive as is. Paper moreso when you could just steal a paper bin from anywhere else.

**Comment by Killette2** [comment]
>That shit partner not only grows weed, but draws green and purple runes all over botanty

Only if you could create soap with the biogenerator too, soap can be made from plants anyways (partially, I don't know how soap works I just hear this shit). And it's not like it would be causing a balance issue, as if botany wanted to slip people they wouldn't need soap they just need banana peels.

**Comment by 9600bauds** [comment]
Well the biogenerator can make meat anyways, so presumably it can make fat and oils. Soap isn't out of the question.

**Comment by Killette2** [comment]
Prisoners already have a default soap I believe still, not sure about this one, but they can definitely smash the farmbot for a bucket anyways. If a prisoner is dedicated enough to farm 4 mushroom trays for soap and then charcoal to put on top of it and a lone officer goes to check on them, then let them escape.

**Comment by 9600bauds** [comment]
This can be closed
