### ISSUE TITLE
PDA uplink too small and unresizable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31724]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
aa9a3b8c030e2bf4906724cf3f183bf7ab0c7089

# Description
the uplink is not wide enough to show the "buy item" buttons, and it isn't resizable either

# Steps to Reproduce
be traitor
open uplink

# What you Expected
antagonise people after buying my gamer gear

# What Actually Happened
no gear because the buttons don't exist

might also be because my IE is fucked, i'll try updating that but everything else seems to work normally

**Comment by Servalfang** [comment]
$rules

**Comment by Eneocho** [comment]
You can expand the TGUIs from the top left corner, not a fix but it can still be resizable.

**Comment by pedr69** [comment]
it was the IE, updating fixed it

**Comment by pedr69** [comment]
> the top left corner

you mean bottom right?
most other windows still keep the windows borders and can be resized from any side, but the syndi uplink doesn't have em, and can only be resized from the bottom and right

**Comment by Eneocho** [comment]
I do mean top left. I have that issue sometimes (not sure if byond or win10's fault), but I can more easily resize a window using the top left corner.
