### ISSUE TITLE
End-game Credits Don't Roll

### ISSUE THREAD

**Issue by PrimeDSS13** [d3athrow/vgstation13#31725]
#### Description of issue
When the game ends, you don't hear the credits music and they also don't appear. The game just freezes and then goes to the next round.

**Comment by SonixApache** [comment]
@PrimeDSS13  post Settings -> General settings

Possibly related to #21684

**Comment by Eneocho** [comment]
Happens to me as well, I have not changed my settings at all but it stopped rolling a few weeks later.
