### ISSUE TITLE
Grinch AI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31726]
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
aa9a3b8c030e2bf4906724cf3f183bf7ab0c7089

# Description
I signed up to be Grinch and it made an AI Grinch and said I was the Grinch after the round ended
# Steps to Reproduce
sign up as grinch, maybe also be on the asteroid
# What you Expected
to play as ther Grinch
# What Actually Happened
I was still a ghost and an AI was the grinch and did nothing

**Comment by SonixApache** [comment]
how is this *still* happening after a years of fixes
#31671 #28326 #21257
