### ISSUE TITLE
Wiz chapel teleport on roid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31730]
(WEB REPORT BY: cyrix01 REMOTE: 206.221.180.138:7777)
# Revision
aa9a3b8c030e2bf4906724cf3f183bf7ab0c7089

# Description
>teleport to the chapel with my one time use apprentice scroll
>spawn inside the chapel creamatorium 
>can't open the doors
this was not poggers

**Comment by Eneocho** [comment]
Feature(TM)
