### ISSUE TITLE
Can't equip donutgiver

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31742]
(WEB REPORT BY: bokoharamburger REMOTE: 206.221.180.138:7777)
# Revision
253a8cf19216f520479ef5331382c396a08a4edd

# Description
When i try to equip the donutgiver, says there is no stored dna profile

# Steps to Reproduce
try putting it on

# What you Expected
donuts
# What Actually Happened
nothing

**Comment by Kurfursten** [comment]
Like the lawgiver, you need to set a DNA profile with the verb
