### ISSUE TITLE
Borg tackling issue

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#31747]
#### Description of issue
I got recruited to play an eggborg, those from xenoarcheology with the hugging and chillwax. After a while I got tackled a few times by two players and they somehow managed to almost completely wreck my armor plating.
#### Difference between expected and actual behavior
Expected either little damage or no damage.
Got around 200KG of meat (in human form) tackling me and somehow almost dying while the humans remained unscathed.
#### Steps to reproduce
Become borg (possibly egg borg).
Get someone to tackle you a few times.
Die somehow (and get the immulsions broken).
[oversight]
@GreatBigFailure

**Comment by AutismSpider** [comment]
Time for him stop being lazy give other mobs tackle stats they are missing

**Comment by Eneocho** [comment]
A 1+ ton machine would be really hard to tackle, keep the borg tackling but give them stupidly big stats so you can only tackle them (and have any damage go through) if the guy has all the correct tackling buffs (armor, hulk, strong, etc).

**Comment by GreatBigFailure** [comment]
This is an oversight and will be fixed once I have time for the tackle update in a week or two.
Basically tackles compare two numbers that are meant to be nearly equal. Just that I forgot to give borgs numbers at all so they're at 0 meaning they always receive max stun and max damage from tackles. This may, in theory, work on some simple mobs too? I can't remember what level of mob I put that sort of thing on, but if it works on borgs it must not have been as high as carbon so ya. Go tackle a Goliath I guess.

**Comment by Dacendeth** [comment]
Borg tackling is a feature.

**Comment by GreatBigFailure** [comment]
I'll probably make it a more reasonable/unique interaction rather than just remove it. As it is now is pretty ridiculous and awful for the borg player, plus it gives very little feedback to the tackler.

**Comment by Eneocho** [comment]
> Borg tackling is a feature.

As it was, each tackle did more damage than a toolbox would've, not really reasonable.

**Comment by pedr69** [comment]
this seems fixed?

**Comment by Eneocho** [comment]
It is, rubylips forgot to add the "Closes #PR NUMBER" thing and I forgot about having opened it.
