### ISSUE TITLE
[Bug] Roundstart PDA and ID don't display.  Also that extra fucking headset.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3174]
They're there, but they aren't displayed.  It takes putting some item in your hands or something to get the game to display them.
![ss 2015-02-21 at 08 21 40](https://cloud.githubusercontent.com/assets/8550416/6317127/c7fb5900-ba10-11e4-8241-8974a1cae25f.png)

As well, everyone is STILL starting with a generic headset in their backpack for whatever reason.

**Comment by ComicIronic** [comment]
Can't reproduce the invisible items on local, nor have I had it happen when playing on the server.

**Comment by PJB3005** [comment]
I've had this happen, spawning as vox CMO on meta, latejoining
