### ISSUE TITLE
CREDITS DON'T APPEAR

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31743]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
253a8cf19216f520479ef5331382c396a08a4edd

# Description
NO CREDITS IT JUST ENDS

**Comment by robintime** [comment]
you already made this issue at #31725 which is already itself arguably a more descriptive duplicate of #31701. creating multiple reports of the same bug won't make it get fixed any faster, and instead just creates clutter on the github.
