### ISSUE TITLE
Can't mid-round join as assistant if there are no officers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31759]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
Title

**Comment by SonixApache** [comment]
feature

**Comment by Dacendeth** [comment]
It's supposed to be 2 base plus bonus for each officer, but that 2 base doesnt work if there's zero sec

**Comment by TGFH** [comment]
owned

**Comment by jwhitak** [comment]
@nervere Please close this issue, unable to be reproduced.
