### ISSUE TITLE
Observing at roundstart prevents being a diona / posibrain

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3175]
If you join the round as an observer, you cannot become a diona from diona plants.

You also cannot become a posibrain unless you manually find an activated posibrain and click it.

**Comment by CptWad** [comment]
I think its how the settings work
Needs more testing

**Comment by clusterfack** [comment]
Neither of those things are true.

**Comment by TermedClepe** [comment]
@clusterfack I have my preferences set to always for both diona and posibrain. When I join the round as a crewman and die in any way, I get automatically selected as a candidate for any activated posibrain and I get immediately placed into a diona once one is harvested. This however does not happen should I click observe to join a round.

It may be worth noting that I observe the round before it actually starts, i.e. when everyone else is readying up I'm already observing.

**Comment by Kurfursten** [comment]
@clusterfack You are correct, these things are not true. Close it.
