### ISSUE TITLE
pipes, scrubbers, and more cucking us out of suicide

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31750]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
9108844be12e3a298d7bbb8dc14979ce28d59635

# Description
Trying to suicide with an item in your hand such as a rubber duck, bike horn, bag of holding, etc, leads to a suicide by pipe/scrubber/cable 9/10 times. Can the choice of suicide be prioritized to held items first?
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
This. jesus christ. I've been cucked outta the funny honk too many times recently.
