### ISSUE TITLE
Line Station Atmos issues

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#31762]
The paramedic cryo is not piped correctly. There is a pipe missing so the canister does not actually feed the cryo tube.
The vent immediately east of the Paramedic's, in the medbay lobby is facing south instead of north.
The vent immediately east of the Medbay Break Room is also facing south instead of north.

There were other places where someone was ejected from the pipes with the contortionists jumpsuit due to poor mapping, that I could not locate in the 5 minutes before the round ended.

**Comment by adacovsk** [comment]
It's probably the double airlocks and not "poor mapping". I'll try to fix the airlocks
