### ISSUE TITLE
[Feature Loss] When adding rods to glass, it makes separate stacks instead of 1

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3176]
Dunno what caused it.  Hold rods in one hand, click glass tiles to make rglass.  It creates single stacks instead of one big stack.  

![ss 2015-02-21 at 09 47 24](https://cloud.githubusercontent.com/assets/8550416/6317401/f36f9020-ba1e-11e4-88ee-8a25e4311988.png)

**Comment by CptWad** [comment]
This goes with ALL stacks
Chopping wood results in many 1 stack boards
Mommis can also not increase the stack that they are holding by clicking on a stack of the same type. Meaning that when rebuilding shit its a lot more tedious.

**Comment by clusterfack** [comment]
Issue comes from
https://github.com/d3athrow/vgstation13/commit/53c96d034d24233bdf837ad25c022b4d3ca45f06
