### ISSUE TITLE
AME lab vault breaks a little when rotated

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31766]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
6e4e2ebf845e92f7ddd36be4722495e6f602dce9

decals get fucked up, AME room gets cluttered a bit, the destination disk also doesn't work, I'm not sure of that last one is related to rotation but I'd be willing to bet its the culprit

**Comment by DeityLink** [comment]
AME Lab vault can no longer rotate.
