### ISSUE TITLE
Proposal: All Maps Seasonal

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#31772]
We have a problem with too many maps. And they just keep coming. This splits up votes more and inflates compile times. Having joke conditions like "revs win", "low score", "low temperature" and "made bagels" etc don't actually fix the compile problem because they need to be compiled even if the condition isn't met.

I suggest we split maps into basically a few tiers and stagger them so that there are varying choices based on time of year.
>A Tier Maps: at least 1/3 of people consider this their favorite map based on the Ancientpowerer survey. Available 6 months.
>B Tier Maps: the more gimmicky lesser maps that are nice for variety but will be limited to 3 month cycles.
>Event Maps: Lamprey, Castle, Snowbox, Old Bagel, Dorf - might have these available for a month at a time or something instead of keeping them compiled year-round.

Example
![image](https://user-images.githubusercontent.com/9782036/147893042-85a5e671-bb4d-4dde-a3c1-0934ca0954a4.png)

Example situation:
It's July. Your options are Roid, Deff, and Lowfat Bagel.
It's November. Your options are Box, Deff, and Line.

Thoughts?

**Comment by calzilla1** [comment]
I'd say keep box all year round

**Comment by Eneocho** [comment]
Add lamprey to regular rotation and we're golden.

**Comment by boy2mantwicethefam** [comment]
Classic maps like Box, Meta and Deff all year round, alternatively just make it so that maps are compiled only once every 2-3 rounds, leaving a predictable pattern of maps to vote on

**Comment by joaomarcosh** [comment]
Only if synergy is available all the time

**Comment by Kammerjunk** [comment]
speaking as someone who _might_ see a GitHub thread but _won't_ see an in-game poll, this is not a thing where you want to restrict your opinions to people who look at GitHub threads.
as an aside, it's also a horrible solution to a problem I'm not sure anyone has heard of until now

**Comment by Lumbermancer** [comment]
What about just having smaller randomized list of maps to choose from every time, instead. I want to play only on Box, but if I don't have that choice, then I will want to play on Meta. You could even squeeze in memetic stuff like Lamprey in.
Fuck I don't know. I know not having map in rotation for half a year sucks fucking ass.

**Comment by Kromkar** [comment]
A solution nobody asked for to solve a problem that nobody noticed

**Comment by dackjaniels69** [comment]
delete everything but box and snaxi, Snaxi 24/7 and box only if more than 100 cardboard boxes are made in a round.

**Comment by Kromkar** [comment]
>server loads so fast the credits don't get to finish
"Here's why I should decide a random schedule of banned maps based on the month to make the server load faster"

Statement of the actually deranged

**Comment by PavelCIA** [comment]
No, fuck you. Just stop adding shitty meme map.

**Comment by adacovsk** [comment]
Jeff proposed a vote count that lasts past each round, and votes are only reset once the map is played. I think this is the best way to implement voting.

**Comment by GreatBigFailure** [comment]
Obviously the chart you posted isn't the only option but 6 months can feel like a long time. 
I don't like the idea of doing it by month, hell even by week might be a bit much. I think it would lower our player count too much. Despite not having any one map I really dislike, even snaxi and horizon have their charm, I would definitely play a lot less during months without maps I prefer, so I can only imagine the effect it would have on people who are a lot less neutral on map preference.

Are the compile times that bad? The time between rounds has only gotten smaller and smaller, didn't we have an issue recently where credits couldn't play because compile times shrank so much? I don't think "More map variety" is a problem. Hell, a few months ago there was a lot of requests for new maps because we had so few.

**Comment by Exxion** [comment]
Restricting the big three at all is simply not happening. We do indeed have a problem with compile times but there must be a better solution than this.

**Comment by adacovsk** [comment]
Why not just compile one map at a time, just when they're selected? Hehe

**Comment by Exxion** [comment]
Oh I should probably answer this
>Are the compile times that bad?

Yes. The server doesn't recompile every round, only when it receives an update. It takes like 15 minutes. Better hope it doesn't start right before a round ends.

**Comment by adacovsk** [comment]
Maybe set it to compile only at round start rather than when it receives the update

**Comment by Hinaichigo** [comment]
How about giving each map a "cooldown", so if it was just played, it won't appear in the voting until the cooldown is over.

eg. box having a cooldown of 0, meaning it can appear every round,
line having a cooldown of 5, so after a line round, it won't appear for the next 5 rounds

That way we can keep the more universally well-liked maps appearing more often but still mix it up from time to time.

**Comment by Exxion** [comment]
>Maybe set it to compile only at round start rather than when it receives the update

As in only compile the map required rather than compiling all of them? I've thought about that, and it seems fine in theory, but it would require changes on Pomf's end
Not to say it can't happen, but it's not simple

**Comment by Eneocho** [comment]
> > Maybe set it to compile only at round start rather than when it receives the update
> 
> As in only compile the map required rather than compiling all of them? I've thought about that, and it seems fine in theory, but it would require changes on Pomf's end Not to say it can't happen, but it's not simple

I think he meant it as instead of compiling whenever it needs to, if the serb gets an update, it starts the next round and THEN starts compiling the maps, while the round is happening. Basically to delay the compiling until the next round and use the time in the active round to compile.

**Comment by Kurfursten** [comment]
#31780 seems like a better solution
