### ISSUE TITLE
Ninja Teleporter has room with no doors on it as a destination

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31771]
(WEB REPORT BY: fargit REMOTE: 206.221.180.138:7777)
# Revision
6e4e2ebf845e92f7ddd36be4722495e6f602dce9

# Description
Used the Ninja Tele on Snaxi, got put inside the hole in the wall with the rainbow jumpsuit with no way of escape
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by SonixApache** [comment]
good thing you have a sword that cuts through walls

**Comment by Kurfursten** [comment]
Like Sonix said, if you use the maintenance button on ANY map you can end up in a wall hole. Cut out.
