### ISSUE TITLE
New maps.... bad ?

### ISSUE THREAD

**Issue by ShiftyRail** [d3athrow/vgstation13#31780]
### Description of issue

It won't have escaped the astute players that quite a few new maps have been merged over the past few months. Line, Island, Nerve, Waystation, and probably a few others that I am missing.
Making a new map is harder, and getting it to stand the test of time is harder. Island was, sadly, not able to pass this test. And even if a map is deemed playable, it can be hard to get to stay relevant and loved enough to get QoL updates and refrubishments that keep it fresh.

Aside from Box, Deff, and maybe Roid, our maps feel sadly unloved by their makers and by the community. At the same time, more and more new maps proposals flourish left and right, sometimes rushed and without enough momentum to fix their issues or with a fatal flaw preventing them from ever feeling perfect. We can remember Wheel, Horizon (V1 and V2), old Bagel...

### A solution

This might be unpopular, but maybe it's time to stop making new maps and instead focusing on finding a way to keep maps FRESH and dynamic. This is why I'm proposing a *soft* moratorium on new maps until we can figure out what we do to keep them relevant.

This means that you can make your map, request feedback, and PR it, but we won't merge it until something has been decided. (haha)

What I propose to fix the issue is **Transferable list voting** with a **monthly map rotation.** What does that mean?

It means that on the 15th of each month, players are asked to rank the maps they wish to see played in order of preference.
Come the 1st of the new month, we look at the players vote.

The map with the lowest number of votes is eliminated, and the 2nd choice of those voters is taken into account, and so on and so on until, say, we got 5 maps to be voted for the month.

### Details

Some maps could be "grandfathered in" and remain always available, excluded from vote. This would include Box, maybe a few others, and Snaxi during the winter.

Snaxi could be a votable candiate instead of an always available map during the Australian summer months.

The total number of maps on rotation is up for debate, and so is the total voting period.

I feel like voting should be secret and no intermediate numbers should be shown before the map reveal, but this is up for debate.

If ordering all maps proves to be too much work for players, we could simply do a list voting of 3 maps per player, sum all the votes, and pick the top 3 maps in the end.

**This change would not affect weighted voting at the end of each round**, and wouldn't affect individual map requirements, just how many maps are in rotation for a given month.

**Comment by Eneocho** [comment]
>The map with the lowest number of votes is eliminated

Does this mean permanently removed from rotation or just commented out during the month?

**Comment by ShiftyRail** [comment]
Neither, just unvotable during the month. An admin could still force them. And the process would be automatic.

**Comment by Hinaichigo** [comment]
Maybe instead of having it occur monthly, it could occur on a continuous basis. Each player can change their map ranking preferences at any time, and the top 5 maps (or another number) are added to the weighted voting. Inactive players (let's say for 1 or 2 weeks) would eventually have their votes reset or not-counted until they start playing again. 
That way it can adapt more quickly and someone who isn't on on the 15th can still impact the voting.

**Comment by PavelCIA** [comment]
Let's just remove all maps except Box, Deff and Roid and tell all "mappers" to fuck off.

**Comment by Eneocho** [comment]
> Let's just remove all maps except Box, Deff and Roid and tell all "mappers" to fuck off.

I will make 10 gimmick maps just to spite you.

**Comment by ShiftyRail** [comment]
@PavelCIA This is too extreme of a viewpoint for me to consider, sorry. 

@Hinaichigo Good idea, but harder to code. Maybe a daily reset.

**Comment by GreatBigFailure** [comment]
I really like synergy and waystation. Can't decide which is my favorite. That is all.

**Comment by SonixApache** [comment]
big new maps bad
smol new maps ok

if map bad kill bad map
why force vote? why even option? just kill bad map
mapper make many map - many many map
want new map? water mapper, wait 3 weeks, boom new map

**Comment by wotisjanitor** [comment]
waystation and synergy are good. also, i would like if more random things would load on stations. Like different vomit stains, different maint loot, etc.

**Comment by adacovsk** [comment]
> @PavelCIA This is too extreme of a viewpoint for me to consider, sorry.
> 
> @Hinaichigo Good idea, but harder to code. Maybe a daily reset.

- Votes that aren't reset every round
- Votes reset after map is played for that map
- Lowest votes after a week rotated out?

Going  to try to code it, but no promises
