### ISSUE TITLE
Botany bot (the walking water tank) has problems pathing

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3178]
Botany bot often gets stuck trying to path through trays which it should be able to pass through, gets stuck on airlocks it cannot open, gets stuck in general and needs to be bumped into / dragged a tile in order to resume operating.

**Comment by wwjnc** [comment]
Honk. #2737

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/pull/3714 may have fixed this

**Comment by clusterfack** [comment]
Please reopen if you encounter this again
