### ISSUE TITLE
(Metaclub) Vault spawned on top the Trader Ship

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31787]
(WEB REPORT BY: redstein REMOTE: 206.221.180.138:7777)
# Revision
c4ac4c4c16159f046924f82b6a91e9c3146c09a9

# Description
Syndicate vault spawned on the left side of the trader ship at roundstart, destroying part of it.

# Steps to Reproduce
lmao

# What you Expected
To trade

# What Actually Happened
Random vault crashed against innocent merchant

**Comment by jwhitak** [comment]
What map was this on? Meta?

**Comment by Kurfursten** [comment]
It is a meta issue that has happened too much

This is not a mapping issue, it's a lazy fucking vault algorithm issue

**Comment by GreatBigFailure** [comment]
I was wondering where the rest of the trader ship was

**Comment by Eneocho** [comment]
Vault mappers, I kneel...
