### ISSUE TITLE
mobs cant wake up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31793]
(WEB REPORT BY: fargit REMOTE: 206.221.180.138:7777)
# Revision
c4ac4c4c16159f046924f82b6a91e9c3146c09a9

# Description
Mobs can't wake up once they go to sleep
# Steps to Reproduce
become a zombie, get cryo'd
# What you Expected
to not fall asleep, or to at least "wake up"
# What Actually Happened
Permenantly paralyzed

**Comment by boy2mantwicethefam** [comment]
WAKE ME UP

**Comment by Kurfursten** [comment]
Dupe of https://github.com/vgstation-coders/vgstation13/issues/28179

**Comment by SonixApache** [comment]
\>issue for over a goddamn year
i think the dupe is warranted
