### ISSUE TITLE
FEATURE REQUEST: RUNECHAT FOR OSAY

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#31805]
Please enable runechat for object say / osay.

**Comment by Exxion** [comment]
Does it not already? There's a separate settings option to enable Runechat for objects, which I know works with vending machines, etc. but haven't tested with osay
EDIT: I tested it and it does indeed work

**Comment by SonixApache** [comment]
i've seen vending machines talk, but does it not work for possessing shit?

**Comment by nervere** [comment]
Tested, not an issue. Exxion's explanation is correct.
