### ISSUE TITLE
Diona plants never grow and always die

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3182]
Diona plants now never grow up and will disappear before maturation. Not sure if related to bees.

**Comment by d3athrow** [comment]
Double what

**Comment by CptWad** [comment]
Usually lumens is the culprit. Check the tray lumens if its under or over 8 lumens

**Comment by 9600bauds** [comment]
Disappear as in poof it's gone, or die before maturation?

**Comment by TermedClepe** [comment]
They just reverted to empty trays without any indication that they were unhealthy. I'm pretty sure they were lit properly, I suspect it happened the moment bees improved them.

**Comment by clusterfack** [comment]
Duplicate of the reference above, (its also explained better there)
