### ISSUE TITLE
Scripts are useless on custom channels

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31828]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
5c3669c3c4df2cdfbdf13721beb48cec0b1fef78

# Description
Since there is no way to make custom encryption keys or add frequencies to existing ones, there is no way to use scripts since people will only be able to use custom frequencies on station bounced radios or intercomms.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
Custom encryption keys are actually something I need to get around to someday but I don't know a good way to handle doing it.

**Comment by west3436** [comment]
@kane-f ever looked into this again?

**Comment by west3436** [comment]
(he did not ever look into this again)
