### ISSUE TITLE
lowfat bagel rad storm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31834]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
5c3669c3c4df2cdfbdf13721beb48cec0b1fef78

# Description
ghetto medbay (the area above medbay) is not rad shielded despite not flashing green
# Steps to Reproduce
run into a non neon green area
# What you Expected
not to die
# What Actually Happened
go deaf and blind

**Comment by nervere** [comment]
No longer an issue.
