### ISSUE TITLE
Changeling absorb genome broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31836]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
5c3669c3c4df2cdfbdf13721beb48cec0b1fef78

# Description
After eating one person and getting mousered/un-moused, trying to absorb more corpses resulted in an error message "We are already absorbing!"
It's not clear if the mouser transformation caused this bug, but it's the only abnormal thing of note. 
# Steps to Reproduce
Absorb body, transform into a mouse, return to original form, then try absorbing another body.
# What you Expected

# What Actually Happened

**Comment by adacovsk** [comment]
Don't know how to fix this one
