### ISSUE TITLE
Please make project mind more noticable with a sound or bigger, different colored text

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31857]
(WEB REPORT BY: wotisjanitor REMOTE: 206.221.180.138:7777)
# Revision
5c3669c3c4df2cdfbdf13721beb48cec0b1fef78

I have been asking for this for a long time come on man. Nobody even notices you talking to them

**Comment by Dacendeth** [comment]
You can use highlight strings yourself to highlight the booming voice message, but still I agree.
