### ISSUE TITLE
Existing airtight flaps are not as airtight as they appear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31861]
(WEB REPORT BY: gazmenark REMOTE: 206.221.180.138:7777)
# Revision
5c3669c3c4df2cdfbdf13721beb48cec0b1fef78

# Description
I used the existing map airtight flaps on metaclub (the ones in engineering at the maint to the AME room) as the "door" of the SME chamber. They were described as anchored and airtight but leaked.
I later made flaps out of plastic and they worked just fine.

# Steps to Reproduce
Use the exisiting flaps on Metaclub engineering/AME maint to seal a room in airtight mode.

# What you Expected
An airtight seal of the chamber

# What Actually Happened
Flooded the SME engine room with cold plasma

**Comment by twirling-jesters** [comment]
I'm having a little trouble replicating this one. Has anyone had any luck with making the plasma leak with airtight flaps? It seems to be working fine on my end.
![dreamseeker_2022-01-29_20-35-23](https://user-images.githubusercontent.com/7096270/151683357-bf8b7666-cda9-43ee-b560-e1c4f7af7a99.png)
