### ISSUE TITLE
I am a wizard AI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31872]
(WEB REPORT BY: blitzikaze REMOTE: 206.221.180.138:7777)
# Revision
d82f5c1877afc077b6d0b2bc287dff456d37dd65

# Description
I have wizard enabled and i readied up as an AI. I spawned as an AI core in the wizard den.
# Steps to Reproduce
Be a magical AI
# What you Expected
To not be a wizard AI
# What Actually Happened
I am a wizard AI with no powers

**Comment by Eneocho** [comment]
![1642626747080](https://user-images.githubusercontent.com/67024428/150396173-ab21803d-0d2a-4b60-aeac-4148249be96a.png)
