### ISSUE TITLE
Botony belts don'

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31871]
(WEB REPORT BY: thathazmatyoukilledinsof REMOTE: 206.221.180.138:7777)
# Revision
b1a9cb3faca436a418a94d0f78851e8e9e3505e0

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ManopolisJones** [comment]
Whoops, fat fingered it, anyway botony belts aren't able to carry plant clippers or spades.

**Comment by djkramer123** [comment]
You had one job kanef
