### ISSUE TITLE
lmao 2 narsie 2 NARSIE (and other cult adjustments)

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3188]
Now I can't be the only one who sees TWO nar-sie sprites when he gets spawned.
Either his sprite has twice itself over or there really is two nar-sies
Also the amount of hell mobs that get spawned needs to be reduced by some 50%
There are way too many mobs for server and players to handle.

**Comment by clusterfack** [comment]
The image doesn't animate properly, thats the issue
