### ISSUE TITLE
Spaghetti spills their Spaghetti

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31893]
(WEB REPORT BY: cyberpunkmrbean REMOTE: 206.221.180.138:7777)
# Revision
15c76035249b5ac162007d21d16b46e2d24c8f4a

# Description
Something about viruses makes people spill their spaghetti, accompanied by the message 'spaghetti spills their spaghetti'
# Steps to Reproduce
Not sure; but it happens when people have viruses, may be linked to new lizard symptom but might also not be
# What you Expected
Spaghetti free viruses
# What Actually Happened
Spaghetti spilled their spaghetti

**Comment by Eneocho** [comment]
When people get very ill they start getting feverish, their palms sweaty, knees weak, arms heavy, mom's spaghetti.
Intended that you spill your spaghetti but it shouldn't say 'spaghetti spills their spaghetti'. It broke after Deity's food in plates revamp.

**Comment by Eneocho** [comment]
You're also supposed to spill your spaghetti when it's in your pocket, but since the plate revamp, only the unplated spaghetti spills, the plated one doesn't.

**Comment by adacovsk** [comment]
handle_spaghetti(100)

**Comment by Kammerjunk** [comment]
https://github.com/vgstation-coders/vgstation13/blob/66e3f972de6fbe5ceaffb551813b6475dd665db6/code/modules/reagents/Chemistry-Reagents.dm#LL4842C5-L4842C139

`[src]` should be `[M]` and github should fix their shit so permalinks embed
