### ISSUE TITLE
Vox turned into chickens can't be made into nuggets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31906]
(WEB REPORT BY: theophrastus REMOTE: 206.221.180.138:7777)
# Revision
8e30fc8902d0de8c3422052a7b82fdb555af56bc

# Description
After the end of a round, a doctor turned a Vox trader into a chicken, chloraled him, and put him on the kitchen table. I then tried to run him through the food processor to turn him into nuggets

# Steps to Reproduce
>turn vox into chicken via genetics
>put vox chicken into food processor
>activate
>vox will pop out harmlessly

# What you Expected
Vox nuggies

# What Actually Happened
disappointment

**Comment by Eneocho** [comment]
literally unplayable
