### ISSUE TITLE
Hobo hut spawning in Box bar

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31902]
(WEB REPORT BY: qbone REMOTE: 206.221.180.138:7777)
# Revision
8e30fc8902d0de8c3422052a7b82fdb555af56bc

# Description

I joined a round as a space hobo and the hut was in the bar, of all places. I'm not quite sure what happened.

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
it was bus
