### ISSUE TITLE
Rubber ducky suicide no longer works

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31917]
(WEB REPORT BY: chazach REMOTE: 206.221.180.138:7777)
# Revision
60241ef44603819b89ed4ce8b8ca2e1f0b2e1e2f

# Description
does some dumb stuff about sticking your hands into a scrubber instead

**Comment by Hinaichigo** [comment]
It does seem like it always prioritizes scrubbers and vents and stuff, even when I'm holding a sharp object. Maybe held items should hold priority.
