### ISSUE TITLE
Only 2 botanist lockers but 3 botanist job slots - Box map

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3192]
There's only 2 botanist lockers in botany but 3 botany job slots, please add another botany locker.

Also https://github.com/d3athrow/vgstation13/issues/3166 while you're at it.

Perhaps another spade too. I should probably learn how to map.

**Comment by Scivirico** [comment]
Definetly needed, also just spawn a botanist locker in the area I would guess.
