### ISSUE TITLE
Changelings are gimped until they absorb somebody

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31925]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
a858910d2e78a647e23933bfa15effc8db5d838c

# Description
Roundstart changelings can't do anything until they husk somebody. Which is: can't channel DNA into air, can't absorb DNA from air, can't change species, can't transform, can't do regenerative stasis. Unless you husk somebody. Is husking a rite of passage for lings or something?
Another issue: once you husk somebody, your genome count goes up 1. Once you split, it doesn't go down. But you are back to being discount ling who can't transform or do anything described above.
# Steps to Reproduce
Please just reproduce goon ling.
# What you Expected
I expected the DNA ling starts with (you know, the one he has "equipped", the one ling "stole" before arriving on station) to work for this, so I don't have to husk somebody but instead can use stealthy DNA sting and transform into things without being silent husker
# What Actually Happened
I am a discount changeling from wish-dot-com

**Comment by adacovsk** [comment]
>goon ling

`name = "Fartonium Sting"
desc = "Let someone else let 'er rip"
icon_state = "stingfart"
venom_id = "fartonium"
inject_amount = 25
cooldown = 600`

`name = "Anti-farting sting"
desc = "You fartless bastard"
icon_state = "stingnofart"
venom_id = "anti_fart"
inject_amount = 25
cooldown = 600`

I'll just fix vg ling
