### ISSUE TITLE
Nu-Grue: Grue-o-vision emergency shuttle lights issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31933]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
a858910d2e78a647e23933bfa15effc8db5d838c

# Description
Emergency shuttle blinking lights in primary hallways are a blinking solid colour that overlays ontop of everything, making it impossible to see anything as grue
# Steps to Reproduce
be grue
shuttle gets called
# What you Expected
to be able to see
# What Actually Happened
can't see shit

**Comment by Hinaichigo** [comment]
This doesn't seem to happen with spiders so I wonder why. I'll take a look.

**Comment by Hinaichigo** [comment]
With #31920 they can see in emergency lights now, though the emergency lights still do interfere with the ability to see light and dark clearly.
Maybe grues shouldn't be able to see emergency lights or they should appear less intense?
Or I could take a look at a custom lighting thing for them that basically does the normal lighting engine but opposite.

**Comment by Hinaichigo** [comment]
Okay I fixed it in a better way.
I originally was just using `client.color` for the whole thing but using both `client.color` and `client.darkness_planemaster.color` in conjunction allows for more versatility.
