### ISSUE TITLE
Can't use self sustaining charge or cable hop while in an APC as pulse demon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31948]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
0ac93cb17c1ce3eecfb15c782a612ceb1fc57365

# Description
Someone clipped the cable while I was in an APC, so I had no cable tile to leave from. Possibly the cable jump not working is intentional, but not being able to leave the APC while self sustaining charge is active seems very weird.
# Steps to Reproduce
Be in an APC as a pulse demon while there is no cable on the tile next to it
# What you Expected
That I'd be able to leave since self-sustaining charge should have allowed me to exist on a non-cabled tile
# What Actually Happened
Was stuck in the APC

**Comment by robintime** [comment]
@kane-f

**Comment by ghost** [comment]
yeah i thought i fixed this, guess not
