### ISSUE TITLE
html is desanitized for traitors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31943]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
b879dddba0f6a2afcf72a77f4696f3e9c031ecb5

!(https://files.catbox.moe/ocej7s.png)

**Comment by gurfan** [comment]
<img width="410" alt="dreamseeker_FbHZ5CePnf" src="https://user-images.githubusercontent.com/51427771/151447783-029b52cb-ae8b-46b7-bb37-c5f60bffb944.png">

**Comment by ConfusedCactus** [comment]
feature

**Comment by Eneocho** [comment]
what the fuck based
