### ISSUE TITLE
Soul Ramblers have Dionea Fertilize Racial Ability

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31940]
(WEB REPORT BY: hinaichigo REMOTE: 206.221.180.138:7777)
# Revision
b879dddba0f6a2afcf72a77f4696f3e9c031ecb5

# Description
Soul Ramblers havea racial ability "Fertilize"
# Steps to Reproduce
Spawn as soul rambler and check racial abilities.
# What you Expected

# What Actually Happened
Soul Rambler has Dionea racial ability "fertilize"

**Comment by Hinaichigo** [comment]
At least I assume it's a dionea ability.

**Comment by Exxion** [comment]
Ramblers spawn with body parts of random species. You got a diona torso.

**Comment by Eneocho** [comment]
Or rather, a diona liver.

**Comment by Hinaichigo** [comment]
Oh I see, makes sense.
