### ISSUE TITLE
Overlays are fucked up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31970]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
2ab3c489c6f7a9108afad5f923f183a8028799f3

# Description
Most overlays are working wrong or weird recently. Runechat overlays under some stuff like vents, overlays when on crit like the damage one are covered by the dark overlay of crit itself, etc.
# Steps to Reproduce
No fucking idea. Speak and or die?
# What you Expected
Working overlays.
# What Actually Happened
Wonky shit.

**Comment by Eneocho** [comment]
Darkness also messes up the overlays.
