### ISSUE TITLE
Sentient mice spawned before round start roll for traitor.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31975]
(WEB REPORT BY: toadtheloser REMOTE: 206.221.180.138:7777)
# Revision
8731100a769a743424084f55156f857c152562a0

# Description
I decided to observer on a faily lowpop round, since I was also doing something else at the time, but still craved ss13. I also decided to spawn in as a mouse and gobble up all the donuts in the bar because I thought that would be funny. Once the round started, this popped up.  https://files.catbox.moe/9tqe3a.PNG
# Steps to Reproduce
Be a sentient mouse before round start, and roll for traitor.
# What you Expected
To be a normal mouse.
# What Actually Happened
The syndicate fatfingered their hiring list.

**Comment by Eneocho** [comment]
The mouse gang will rise up against the c*der metaclub.

**Comment by Theophrastus1** [comment]
biggie cheese

**Comment by tomacatx2** [comment]
MOUSE GANG MOUSE GANG

**Comment by Eneocho** [comment]
> biggie cheese

cheesie smalls

**Comment by ghost** [comment]
feature
