### ISSUE TITLE
Vox blood description error

### ISSUE THREAD

**Issue by chainsauce** [d3athrow/vgstation13#3197]
Although vox blood is blue, the description claims that it's red. Hardly a pressing issue but I figure it's worth reporting anyway.
![its red](https://cloud.githubusercontent.com/assets/6082418/6339723/9563e576-bb86-11e4-88e1-e48dd0619af1.png)

**Comment by CptWad** [comment]
Thats our description of blood?
I think a better fix is a more general description thats more fun.
Like one or a mix of the following:
>You swear it looks a lot like butterflies
>You swear it looks a lot like a face
>You swear it looks like a bunch of Cheezy Honkers
>You swear a splotch looks a lot like a chicken
>etc.

**Comment by unid15** [comment]
This has been fixesd
