### ISSUE TITLE
vox hair color is not tied to the character slot

### ISSUE THREAD

**Issue by robintime** [d3athrow/vgstation13#31988]
i genuinely have no clue why this is happening.

#### Steps to reproduce
have two vox across multiple character slots;
change the hair color on one to a different color, save;
switch to the other vox character. the hair color will have carried over to the unrelated slot.

**Comment by SonixApache** [comment]
copypasta from dc
```
vox hair color var gets set in prefs but not overridden by loading a character slot so it carries over
reason is probably that the new var isnt being saved to the db
solutions:
+ tie hair to existing db entry rather than adding new var
+ add var to db
```
