### ISSUE TITLE
Overlays are still fucked up.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#31984]
![Asteroid Relay Two 2022-02-03 002810](https://user-images.githubusercontent.com/67024428/152276827-f74e4291-4085-4b20-9593-c820273fa1cb.png)
![Immoral Drydock Xi 2022-02-01 224751](https://user-images.githubusercontent.com/67024428/152276832-6b117839-955d-44e5-bfdd-8bfd7c75971b.png)
![Immoral Drydock Xi 2022-02-01 221641 (1)](https://user-images.githubusercontent.com/67024428/152276835-d7b9518e-0e46-4f36-9514-b790f66211ab.png)

**Comment by gurfan** [comment]
@Eneocho when were these screenshots taken

**Comment by Eneocho** [comment]
The first one today, about 3 hours ago. The second and third one yesterday.

**Comment by Eneocho** [comment]
Thinking about it, the third one might have been patched already, but not sure. The text fuckery is still happening though.

**Comment by Eneocho** [comment]
Still happening. Confirmed it's an issue with sideways mobs.
