### ISSUE TITLE
Aft Starboard Derelict APC and Aft Port Derelict APC on Deff. labeled opposite!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#31999]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
e37bd3880fc7e30d48c74bd3508bfbf47ee7f247

# Description
The Port side APC is labeled Starboard and the Starboard APC is labeled Port on defficiency. I saw an atmos alert and was looking around all over and turns out it was on the other side of the station.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Theophrastus1** [comment]
fuck you duny

**Comment by pedr69** [comment]
think solars are also named wrong, IIRC the doors on em are all "aft port solar access"

**Comment by nervere** [comment]
Fixed by #32331
