### ISSUE TITLE
Soul Stones absorb unconcious, healthy players

### ISSUE THREAD

**Issue by mehmehsomeone** [d3athrow/vgstation13#3199]
Get stunned, get hit with chloral/sleep toxin, go unconcious, get hit with soul stone, instantly become sharded with your body gibbed despite remaining at positive HP.

2op, fix pls

**Comment by CptWad** [comment]
The problem is that you cant soulstone crit people because they succumb ghost the moment you pull a soul stone out because they get bitter over losing

**Comment by mehmehsomeone** [comment]
Make it work on 10-20 HP then, it's technically even stronger than C4 since it doesn't take time to apply and doesn't have a timer.
