### ISSUE TITLE
Head replacement surgery doesn't update body/name

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32004]
(WEB REPORT BY: exabod1 REMOTE: 206.221.180.138:7777)
# Revision
e37bd3880fc7e30d48c74bd3508bfbf47ee7f247

# Description
Trying to replace a body's head will instantly revert back to its original head and name.
# Steps to Reproduce
1.Create human monkey 2. remove human monkey head 3. replace it with a human (player) head. 4. (Player) is now named (Monkey 6969)
# What you Expected
To work.
# What Actually Happened
 I tried to attach a head from a gibbed player onto a decap'd human monkey, whoever that pretty much turned him into a human monkey.

**Comment by Theophrastus1** [comment]
just dont lose your head lol

**Comment by DamianX** [comment]
fixed
