### ISSUE TITLE
Security belt doesn't accept Smoke Grenades and Collapsible Baton

### ISSUE THREAD

**Issue by mehmehsomeone** [d3athrow/vgstation13#3200]
There's no reason it shouldn't.

**Comment by CptWad** [comment]
STOP :no_good: 
SECURITY :oncoming_police_car: 
Hailers also dont go in them and they are necessary.

**Comment by ComicIronic** [comment]
I'm sure the hailers should fit on the belts.

**Comment by d3athrow** [comment]
Fixed with https://github.com/d3athrow/vgstation13/commit/62744416e675eb84cbb63317755b5d45ceb3ab14
