### ISSUE TITLE
Traitor botanist idea: WASPS

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3202]
LOOK LIKE BEES
WORK LIKE BEES
ONLY ALWAYS PROVOKED TO EVERYONE BUT THE TRAITOR
WILL EXPAND TO OTHER HIVES AND KILL BEES

WASPS BEST TRAITOR IDEA 2015 :bee:

**Comment by SkowronX** [comment]
![gam_mgshiimdaisy2_580](https://cloud.githubusercontent.com/assets/7810719/6344609/861c24cc-bbc0-11e4-837b-6c10b1ab4d25.jpg)

**Comment by clusterfack** [comment]
NOT THE BEES, NOT THE BEEEEES

**Comment by wwjnc** [comment]
What about WIZARDLING WASPS?
https://www.youtube.com/watch?v=xdkLZNyEMVU

**Comment by Killette2** [comment]
I like it, but killer bees sounds cooler
