### ISSUE TITLE
Minor P.D.A. current events bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32020]
(WEB REPORT BY: cartlord REMOTE: 206.221.180.138:7777)
# Revision
4291f816bf92915d801dd7612759615a69e8ac2f

# Description
The P.D.A., in its "Current Events" function, shows simply "pick(facts)" under the "Did you know..." subheading.
# Steps to Reproduce
-Have P.D.A.
-Open Current Events
-Scroll down
# What you Expected
For it to show me something I might not know, I guess.
# What Actually Happened
It's seemingly just showing the code.

**Comment by Eneocho** [comment]
what the fuck i was gonna report it get outta my head
