### ISSUE TITLE
Pies Blind Pulse Demons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32032]
(WEB REPORT BY: kneegear REMOTE: 206.221.180.138:7777)
# Revision
fdfb1508429b2447967053fe8d40b75e05cb6a47

# Description

Being hit by a pie from a vending machine blinds pulse demons.

# Steps to Reproduce
Hack a vending machine to fire out contents, get hit by one as pulse demon

# What you Expected
Nothing to happen or for temporary blindness

# What Actually Happened
Blinded permanently

**Comment by Eneocho** [comment]
Powerful.
Do regular clown-thrown pies do the same?

**Comment by pedr69** [comment]
is there another function that happens when you get hit by thrown stuff other than hitby()?
returning in pulsedemon/hitby() will still make you get hit and blinded, but only temporarily
