### ISSUE TITLE
Unsimulated walls don't properly block air

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3204]
I believe this is a result of d3athrow's catwalk changes to ZAS. Unsimulated walls allow airflow towards/through them for some reason. 

You can check this by opening a plasma canister in the thunderdome for example, an item or mob will be jostled around by airflow towards one of the unsimulated walls and collide with it.

**Comment by clusterfack** [comment]
I think I should give an example of ingame relevance: duny's tcomms satellite on defficiency has gas miners and unsimulated walls, which results in everything being blown away into the walls meaninglessly

**Comment by ConkerDev** [comment]
is this still a thing?

**Comment by clusterfack** [comment]
Yes

**Comment by clusterfack** [comment]
Though it's more properly a problem with the interaction between simulated and unsimulated turfs (sim and unsim turfs fucking HATE each other). Which is a pretty well known issue for ZAS.

**Comment by Intigracy** [comment]
Sim vs Unsim is the eternal battle that afaik every codebase deals with.
