### ISSUE TITLE
vox drumstick recipe gives regular drumsticks instead

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32057]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
d2b8f37875e8b14a64db80433a0fdc99d12acb1e

# Description
title
# Steps to Reproduce
2 vox chicken meat 1 cardboard in the microwave
# What you Expected
vox drumsticks
# What Actually Happened
regular drumsticks

reminder to me to check what the fuck

**Comment by SonixApache** [comment]
https://github.com/vgstation-coders/vgstation13/pull/31909#issuecomment-1020627712

**Comment by VNLoverMay** [comment]
Replicated this.
Since it's a subtype of rawchicken, it finds the regular recipe first and does that instead.
Swap the priority around and it should be fixed, I think.
