### ISSUE TITLE
21 solar assemblies  [Box?]

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3205]
There are precisely 21 solar assemblies that are not placed on any ingame turf, that delete themselves at roundstart. I tried locating them using get_turf(src) but they just aren't anywhere.

How they got there? I don't know. But they're deleted automatically every round.

**Comment by Exxion** [comment]
Is this fixed? I have 20 deletes at roundstart when I test locally, but it won't even tell me what type of deletes they are, let alone let me see what was deleted.

**Comment by clusterfack** [comment]
No it was never fixed that I know of, there are still 21 solar assemblies that delete at roundstart.

**Comment by Exxion** [comment]
Maybe some solar assembly crates are too full or something
Would that cause it?

**Comment by clusterfack** [comment]
I'm not entirely sure, my most likely guess is it's a map issue that has to do with a varedit to something on the map, most likely in my mind on the solar panels themselves.

**Comment by Exxion** [comment]
Wait
Are they solar assembly items or machines?

**Comment by clusterfack** [comment]
Solar assemblies are a machinery type that you wrench down and place glass in to make a solar panel, the solar assembly is then placed inside the solar panel. All solar panels hold a solar assembly inside them and drop them when they are destroyed or diassembled.

**Comment by Intigracy** [comment]
Did this ever get fixed?

There's 13 solar assemblies in engineering in a crate, but I doubt those are the issue since it's not 21.

**Comment by clusterfack** [comment]
To my knowledge it was never fixed, I may have to just actually open up the map in notepad++ to find out whats up

**Comment by Exxion** [comment]
I did that once (well, a different text editor, but whatever) and I still couldn't figure it out
My best guess is that some of the solar assemblies found in crates at roundstart are being deleted when the crates close because they are going over-capacity
But that doesn't explain why (as I recall, at least) the number of deleted solar assemblies is not divisible by the number of solar assembly crates at roundstart.

**Comment by clusterfack** [comment]
Well I've checked it again, and though I dont know of anyone specifically going to fix it, it appears to have stopped at some point between then and now

**Comment by Exxion** [comment]
I guess it will always and forever be a mystery
