### ISSUE TITLE
You can erase time anomalies with a timeline eraser.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32052]
(WEB REPORT BY: toadtheloser REMOTE: 206.221.180.138:7777)
# Revision
d2b8f37875e8b14a64db80433a0fdc99d12acb1e

# Description
If you use a timeline eraser on a time anomaly, it gets rid of it. This seems more like an oversight, since it means that anyone with a stolen timeline eraser can get rid of it, cucking either the time agent or their duplicate.
# Steps to Reproduce
Use a timeline eraser on an anomaly.
# What you Expected
Nothing to happen to it, since it's a time anomaly.
# What Actually Happened
Someone destroyed the one I was meant to exit through, and the admin spawned one that Loppu very graciously made was able to be destroyed.

**Comment by Eneocho** [comment]
No need for time agents if you erase the anomaly. FEATURE(TM)(LTD)(R).

**Comment by ghost** [comment]
no thats funny, keep it
