### ISSUE TITLE
No Bleedings: Gene, The 1984 movie

### ISSUE THREAD

**Issue by Fizbun** [d3athrow/vgstation13#3208]
Bleeding is a issue. Losing blood could be fatal as it deals oxygen damage, this could be avoided if genetics could give the bleeder a gene that stops bleeding as the wound is drawn, which would lead to less death.

**Comment by clusterfack** [comment]
But bleeding SHOULD deal oxygen damage, your body isn't getting enough oxygen from the blood!

**Comment by gbasood** [comment]
Since blood loss has been modified since this issue was opened, I'm gonna go ahead and close this unless someone considers it an issue still.
