### ISSUE TITLE
Midround Spiders Can't Smash Windows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32084]
(WEB REPORT BY: spacedgod REMOTE: 206.221.180.138:7777)
# Revision
21738eaef1c8a1b8b1a08986b8929e6b91e293d1

# Description
player controlled spiders can't smash all windows. For no good reason, normally reachable windows can't be smashed by PC giant spiders. It seems to be a window orientation issue but fuck if I know
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
Its some weird issue. Sometimes you can smash them no problem. Sometimes it just does nothing. Try smashing them at an angle.

**Comment by Exxion** [comment]
I think it has to do with pressure? Spiders have code that prevents them from breaking windows with a large pressure difference to reach non-mob targets, probably to avoid having everything near them be depressurized always, but this code does not check if the spider is player-controlled.

**Comment by pedr69** [comment]
it might also be the thing where if you put about 6 directional windows on one tile, you can't break any of em using melee

**Comment by Eneocho** [comment]
> I think it has to do with pressure? Spiders have code that prevents them from breaking windows with a large pressure difference to reach non-mob targets, probably to avoid having everything near them be depressurized always, but this code does not check if the spider is player-controlled.

Might explain why I can smash windows to space but not from space.
