### ISSUE TITLE
Ejected TEG vault can spawn rotated and that breaks all the piping.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32095]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
Title

**Comment by Eneocho** [comment]
![Control Town Upsilon 2022-02-16 182507 (1)](https://user-images.githubusercontent.com/67024428/154361808-8129124e-3436-4fe9-9522-8804c939b74c.png)

**Comment by ghost** [comment]
yeah pipes do weird stuff with initialisation when rotated, forgot to set this one to false i guess
