### ISSUE TITLE
snaxi air mix tank in atmos not linked right

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32106]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
5c9b1517d08ac851ab37b0f6b13127c230149c26

# Description
the computer is at 144.1, the input port at 144.3
the input rate cannot be configured until you change the frequency of the mixed air supply control computer.
# Steps to Reproduce
go to atmos
# What you Expected
atmos linked
# What Actually Happened
not linked

**Comment by pedr69** [comment]
also, robotics has no borg charger
also also, no borer pen anywhere; theres an egg in xenobio but no plasma nearby
