### ISSUE TITLE
Disposals Pipes Can't Hold Trash and Delete People

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#32116]
#### Description of issue
Whenever someone would use the disposals system, be it for mail or trash, the pipes would sometimes, if not immediately eject the contents as if they were unfastened from their position. One player reported to me that they were stuck inside a pipe, making the usual rapid banging noise when fat people are stuck in a pipe, and when help came to weld them loose from the pipe, their body was deleted with only the ghost of the player remaining.
![image](https://user-images.githubusercontent.com/55976761/155022245-62041375-df7b-41cd-b2b1-bcd136a9d4cb.png)

#### Difference between expected and actual behavior
I expect disposals pipes to transport objects inside them. Instead they can't contain their spaghetti for a hot minute and sentence people inside them to round removal.

#### Steps to reproduce
This occurred roundstart as far as I know.

#### Length of time in which bug has been known to occur

Happened only recently here 21th of February.

#### Server revision

4116e41d7bc2942a4acebb4764ab3eb68e346ae5

**Comment by Exxion** [comment]
Presumably fixed by #32115, though I still don't know how people got deleted
EDIT: Oh, because the pipe was destroyed

**Comment by Eneocho** [comment]
For future reference, the banging sound is when you press a movement key inside a pipe, not because you're fat. The funny disposal circles are great for the soundgunk.

**Comment by DamianX** [comment]
:|
also, this was fixed
