### ISSUE TITLE
Plants can mutate into themselves

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3212]
![ss 2015-02-24 at 06 34 50](https://cloud.githubusercontent.com/assets/6526157/6359728/ede37b94-bc53-11e4-8ad9-3a59f2b6d4f0.png)

**Comment by 9600bauds** [comment]
There were absolutely 0 bees involved

**Comment by TermedClepe** [comment]
Not a bug.

It mutated into a poison apple tree which has the same name as the regular one for easier tatoring.

They contain pure cyanid after they mutate into that variant and lose their mutation attribute, which is the only way to recognize the seeds from regular apples.

**Comment by 9600bauds** [comment]
Well I'm silly then. Case closed.
