### ISSUE TITLE
Your species really, really, REALLY cannot wear that

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3214]
Attempting to quickswap (ctrl+e) a piece of garment that's not suitable for your species will result in the error message being repeated quite a few times.
![ss 2015-02-24 at 08 47 57](https://cloud.githubusercontent.com/assets/6526157/6361967/73230f92-bc66-11e4-9fac-db406d755af8.png)

**Comment by SkowronX** [comment]
That's because it iterates through EVERY SLOT.

**Comment by 9600bauds** [comment]
So that's what makes gloves end up in my pocket slot.

**Comment by ComicIronic** [comment]
Quick-e is tragically too stupid to check what slots you could put something in in the first place.

**Comment by Wizardcrying** [comment]
Wasn't this fixed?

**Comment by clusterfack** [comment]
Not to my knowledge

**Comment by 9600bauds** [comment]
I'd just like to state on record that I have no idea how is this a feature request

**Comment by PJB3005** [comment]
Because it requests a feature that checks if you can wear something correctly for quick equip.

<sup>I <sup>don't <sup>agree <sup>with <sup>comic's <sup>logic <sup>either
