### ISSUE TITLE
Packed TEG Is Unusable

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#32155]
#### Description of issue
When making a standard roundstart setup, the TEG on Packed will not produce any power. The gas inside the cold loop is as if it's in a standstill, no gas will update or move there when you fill them up and wait a few seconds.

This isn't me forgetting to set external checks or anything, it's legitimately the pipes being completely kaput.

#### Difference between expected and actual behavior
I expected the circulator to spin on the cold side so the gases could exchange and produce power, it did not and instead was completely still.

#### Steps to reproduce

1. Make a fuel line with O2 and plasma to the burn chamber or use canisters
2. Turn on the circulator volume pumps
3. Anchor plasma canisters to the connector ports to the hot and cold loop and turn on the gas pumps to max
4. Observe cold loop meter, circulator and plasma canister pressure
5. Cry because you have to build an SME chamber or, god forbid, a singularity

Here's my setup, for reference.
![image](https://user-images.githubusercontent.com/55976761/156149928-2263f017-1d6a-4d39-936f-561b01bc8fa1.png)
Note how the cold loop canister is showing a green light while the cold loop meter is completely blank, despite being directly connected with a straight pipe.

#### Length of time in which bug has been known to occur

Feels like at least a week this has been going on.

#### Server revision

636adb8fdcdfcd1e2928622cc288c9cb72da2fed

**Comment by Eneocho** [comment]
Was the circulator not circulating at all or were the pipes themselves frozen (gas didn't heat/cool/move)? Because if it's the former, I've had that happen to me before. Some odd circulator runtime that has only happened on the cold loop, even on custom TEG constructions.

**Comment by Armadingus** [comment]
The pipenet was definitely frozen, I want to say that the lack of circulation was because of the frozen pipenet, but I am uncertain.

**Comment by jwhitak** [comment]
Pipenet is busted, source seems to be this specific he junction pipe. After unwrenching/rewrenching, the pipenet seems to work properly.
![image](https://user-images.githubusercontent.com/69739118/156162362-486eb90e-a526-4955-b779-dbb155a91e9e.png)

Note: above image is after unwrenching/rewrenching. Before that it has a strange 'wrenched' sprite:
![image](https://user-images.githubusercontent.com/69739118/156162275-2364f040-c93d-4f82-ba7c-0e9548c47418.png)


Edit: Restarted server and took following actions:

1) wrenched plasma canister to cold loop connector
2) turned on gas pump, observed no gas pumping (for about 30 seconds before continuing with next step, as it was clearly frozen)
3) opened glass, removed grill, unwrenched/rewrenched above pipe

Pipenet immediately became functional.

Variables iconstate, inertia_dir, initialize_directions, and node1 are different.

**Comment by Eneocho** [comment]
It is possible that that one time the circulator froze to death was actually a rogue pipe somewhere and we could've fixed that Snaxi RUST and I'm hating that real bad.

**Comment by pedr69** [comment]
HE pipe magic strikes again
