### ISSUE TITLE
Pulse demon wire overlay is fucked up and laggy.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#32171]
#### Description of issue
Rolled Pulse Demon. The wire overlays started spinning or something (See pics), and the constant updating of the overlays lagged me horribly to more than 200000ms.

![East Observatory Nineteen 2022-03-07 014113 (1)](https://user-images.githubusercontent.com/67024428/156970660-64deca55-d11c-49b8-a8ce-fb99ec8586a5.png)
![East Observatory Nineteen 2022-03-07 014112 (1)](https://user-images.githubusercontent.com/67024428/156970666-620f208c-5b7d-4cba-962c-00913ba65b43.png)
![East Observatory Nineteen 2022-03-07 014110 (1)](https://user-images.githubusercontent.com/67024428/156970667-56ab0f9c-d9fc-468e-9d7f-5f41646061dc.png)

#### Difference between expected and actual behavior
Expected to play.
Got Powerpoint presentation on a potato PC.
#### Steps to reproduce
Dunno. Join as pulse demon?
#### Length of time in which bug has been known to occur
Last time I played PD (about a month ago) this didn't happen, so at most a month.
It probably is caused by the Multi-Z wire PR that just got merged.

[bugfix]

**Comment by Eneocho** [comment]
@kane-f

**Comment by ghost** [comment]
As said on that PR, could not reproduce it.
