### ISSUE TITLE
Delicious spider hardcoding

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#32170]
so spiders are hardcoded to not be able to break windows to space, which is nice, right?
```
/mob/living/simple_animal/hostile/giant_spider/proc/performPressureCheck(var/turf/curturf)
	if(!istype(curturf))
		return 0
	var/datum/gas_mixture/myenv=curturf.return_air()
	var/pressure=myenv.return_pressure()

	for(var/checkdir in cardinal)
		var/turf/T = get_step(curturf, checkdir)
		if(T && istype(T))
			var/datum/gas_mixture/environment = T.return_air()
			var/pdiff = abs(pressure - environment.return_pressure())
			if(pdiff > SPIDER_MAX_PRESSURE_DIFF)
				return pdiff
	return 0
```
however, this also applies to player spiders, so its easy to get stuck in places like xenobio or viro if the doors are bolted unless you, get this, go out the back through the doors, breaching anyways.
This should really (somehow) be updated to not apply to player spiders. maybe make npc spiders a deepepr subtype with this set of code so it only applies to them, but that'd have a lot of copycode, maybe a var? Idunno I don't get paid.

**Comment by Exxion** [comment]
#32084

**Comment by Exxion** [comment]
Also you can just do `if(client)`

**Comment by Eneocho** [comment]
There's also that FUCKING AUTOAIM issue (#31040) that fires the queen web-shot in a straight line to whatever mob is nearest, regardless of where you were aiming or obstacles, which makes you sometimes aim at a wall or at a simplemob when you intended to shoot a human.

**Comment by pedr69** [comment]
also, the spiders will force open external airlocks and then smash open the firelocks that will trigger
which will result in 80% of the station being spaced if the spiders aren't killed within 2 minutes
