### ISSUE TITLE
Camera assembly runtime?

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#3218]
https://dl.dropbox.com/s/bspy5xm6el5v4ru/runtime.png

Not sure why but I was playing mommi as one round and tried placing a camera on the tile to my left, and it doesn't work.

I left the assembly ontop of that meter, wrenched it (it ended up facing south), welded it, and put wires in it.

Normally you then screwdriver it and it gives you a prompt and such, but when I screwdriver'd this camera it did nothing. I even completely dis-assembled it and redid it to no change.

**Comment by Midaychi** [comment]
As a side note, on the same exact round, I moved that camera assembly somewhere else and it constructed fine, but I couldn't use a security camera console.

**Comment by Midaychi** [comment]
Turns out this is actually a bug with wine and the popup dialog boxes deciding they don't want to work anymore.. I ran into this again in another round on a separate place and unlike last time I couldn't fix the problem by trying somewhere else, so I closed the client and restarted it and I could finish it fine.

**Comment by gbasood** [comment]
Need someone to confirm whether or not this can still occur
