### ISSUE TITLE
Exactly half of the solars at WayStation's Trader outpost aren't wired at roundstart

### ISSUE THREAD

**Issue by Cartlord** [d3athrow/vgstation13#32190]
#### Description of issue
At the beginning of the round on WayStation, only have the solar panels have wire knots under them, meaning you need to crowbar up their tiles and add cabling.
[https://cdn.discordapp.com/attachments/532031427563356160/951810650747863150/Solars.png](url)
[way]

#### Difference between expected and actual behavior
I figured that, once I'd connected all the visible wires on the catwalks, the solars would be fine; I did not expect to have to crowbar up fifteen tiles and wire the floors under them.

#### Server revision
Game: 9cb902c4188a36706eb2a53364e083243ec4298a 
Patches: 609a806a066b5859e732b12938343551efcc77f7 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

**Comment by Cartlord** [comment]
okay i guess [way] isn't the tag for waystation

**Comment by Eneocho** [comment]
![image](https://user-images.githubusercontent.com/67024428/157902322-8de7d311-af5f-44d5-811a-08f4bb78ad6d.png)
You posted the image wrong.

**Comment by Eneocho** [comment]
> okay i guess [way] isn't the tag for waystation

There is none. PJBbot hasn't been updated in a long while, so the automatic tag system only goes so far. There is a manual tag though.
