### ISSUE TITLE
Latejoining Traders on Asteroid Station are deposited on the wrong Z-level

### ISSUE THREAD

**Issue by Cartlord** [d3athrow/vgstation13#32194]
#### Description of issue
So I latejoined as a Trader on Roid, and it sent me to Z-level 4, "Mining", where hobos spawn. I had no shuttle, no outpost, and no hope.
For clarity, I'm referring to [http://game.ss13.moe/minimaps/images/maps/AsteroidStation/#l=187,191,5;z=0.2](url)
[roid] [oversight]

#### Difference between expected and actual behavior
I expected to be able to play without AHelping to be teleported.

#### Steps to reproduce
Join as Trader or Merchant on Roid.

#### Server revision
Game: 640def376fa86972a10781008b1229fbd59a5072 
Patches: 609a806a066b5859e732b12938343551efcc77f7 
Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

**Comment by nervere** [comment]
lol

**Comment by nervere** [comment]
This has been fixed.
