### ISSUE TITLE
New puddle system spill reagent amount

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32197]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
640def376fa86972a10781008b1229fbd59a5072

# Description
Possibly a bug, possibly an oversight, but I had the exact same amount of puddle form when I was pouring 50u vs 100u of a substance on the floor. So there was no benefit to doing more.
# Steps to Reproduce
Pour 50u on the floor and 100u on the floor of any liquid
# What you Expected
The 100u pour would result in a bigger puddle or more spread
# What Actually Happened
They both made the same sized puddle

**Comment by ghost** [comment]
Spreading was turned off in server config (not a bug)
