### ISSUE TITLE
MoMMi can't use the AIO Grinder

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3219]
The interface doesn't pop up
tried resend-resources
tried reconnecting
nada

carbons could use the same grinder fine.

**Comment by clusterfack** [comment]
Already exists #2793 

Theres no decision on whether mommis should be able to use it

**Comment by TermedClepe** [comment]
@clusterfack
Was there ever a decision on why they shouldn't use it?

**Comment by AutismSpider** [comment]
No decision was made yet.

**Comment by SkowronX** [comment]
![yay](https://cloud.githubusercontent.com/assets/7810719/6385648/63fabcf0-bd32-11e4-943f-11df48a7c2e4.PNG)

**Comment by AutismSpider** [comment]
Give it to medborgs too.
