### ISSUE TITLE
You can't bite without arms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32206]
(WEB REPORT BY: cartlord REMOTE: 206.221.180.138:7777)
# Revision
640def376fa86972a10781008b1229fbd59a5072

# Description
Lost both arms, tried to bite, no dice

# Steps to Reproduce
-Lose arms
-Enable bite
-Click thing

# What you Expected
-Cronch

# What Actually Happened
-Jack shit

**Comment by WindowsErrors** [comment]
chomp

**Comment by coolguymcman** [comment]
This doesn't seem to happen if you've been revived after being dead for 35 years.

**Comment by Hinaichigo** [comment]
I tested it and you actually can bite (and kick) if you don't have arms, even if you're on the floor. You just need to be on harm intent, otherwise it defaults to attempting to pat them on the head or hug them. So this is not a bug I believe. @DamianX perhaps this could be closed?
