### ISSUE TITLE
You can move puddles around with telekinesis

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32201]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
640def376fa86972a10781008b1229fbd59a5072

# Description
See issue name
# Steps to Reproduce
Get telekinesis, move puddles
# What you Expected
That I wouldn't be able to move them
# What Actually Happened
I moved them

**Comment by Eneocho** [comment]
You're just waterbending, avatar style. Feature(TM).
