### ISSUE TITLE
Noslips do not work with nupuddles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32213]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
7ecbd7099769e02c0e34ae266d1bb852d55183ea

# Description
A
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
Tested locally and they do, unable to reproduce.

**Comment by west3436** [comment]
Do noslips not work with lube?

**Comment by Blithering** [comment]
No, lube is too slippy for mere shoes.

**Comment by west3436** [comment]
Ah ok I'm a retard then, please close this
