### ISSUE TITLE
Synergy Medbay Reception Missing Point of Sale

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32218]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
c5f22132166d1de934f94537484f696ae8e628b5

# Description
as one of three users of points of sale, you have single-handedly ruined my insurance gimmick
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
i now realize that no medbays have a POS mapped in and i was merely experiencing a hallucination
feel free to close this as i am a retard

**Comment by Cartlord** [comment]
you can close your own issue, retard

**Comment by west3436** [comment]
Not a bug, please close @Kurfursten
