### ISSUE TITLE
Storages are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32224]
(WEB REPORT BY: assmops REMOTE: 206.221.180.138:7777)
# Revision
06fa600c1b489807f8d1af590e522122bcba3db2

# Description
Backpacks, and suit storages like the hazard vest pockets, can only have items taken out of them, not put in
# Steps to Reproduce
>Get any appropriately sized item
>Shove in backpack
# What you Expected
>Item is shoved in backpack
# What Actually Happened
>Item still in hand

Someone in OOC said it was probably because broken objects check for 0 health, and most storage items like backpacks have a health value of null, therefore they're technically broken and unusable

**Comment by Cartlord** [comment]
CONFIRMED.

**Comment by Eneocho** [comment]
This just got fixed, wait until server recompile (next round). See #32225.
