### ISSUE TITLE
Can't kick stuff away.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32221]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
939588ed53ad3d41272c0c34b1c1f8fb470e6575

# Description
Tried kicking a crowbar and an airtank. It kicked 'em they didn't move.
# Steps to Reproduce
Drop stuff.
Kick.
# What you Expected
Kicking and the stuff moving.
# What Actually Happened
Kicked and the stuff remained in place.

**Comment by Hinaichigo** [comment]
Does it work on small or tiny objects? I think kicking distance depends on a few factors including weight class.

**Comment by Eneocho** [comment]
It did work on the survival box bandage.
