### ISSUE TITLE
tasers crashing server

### ISSUE THREAD

**Issue by adacovsk** [d3athrow/vgstation13#32227]
firing a taser through a window makes it bounce repeatedly forever

**Comment by tuypo1** [comment]
Why yes I tested my major code change for a minor effect, why wouldn't I have

**Comment by tinysaturn** [comment]
GLOCKGANG RISE UP

**Comment by Eneocho** [comment]
The end of stuns as we know 'em. Now you freeze the client, not the spessman.

**Comment by adacovsk** [comment]
@Hinaichigo can you test projectile health?

**Comment by Hinaichigo** [comment]
I think this is because taser bolts don't have a target. I'll see if I can do something.

**Comment by adacovsk** [comment]
tasers can go through doors too now

**Comment by Hinaichigo** [comment]
I think this is because taser bolts don't have a target. I'll see if I can do something.
