### ISSUE TITLE
made 30 bagels no bagelstation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32222]
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
06fa600c1b489807f8d1af590e522122bcba3db2

# Description
made 30 bagels no bagelstation
# Steps to Reproduce
make bagels
# What you Expected
bagelstation
# What Actually Happened
sadness

**Comment by Eneocho** [comment]
They remove the rarely used maps from the compiling to save on compiling times but that also means we get cucked of our well deserved bagel/lamprey.

**Comment by nervere** [comment]
The vote system considers whether or not the population requirement is met above everything else, this isn't a bug.
(Also I think all compiled maps are now voteable anyway.)

**Comment by Eneocho** [comment]
>The vote system considers whether or not the population requirement is met above everything else, this isn't a bug.

I could swear the only requirement for OG bagelstation (this issue is not about lowfat) were the 30 bagels.

**Comment by Exxion** [comment]
The requirement is apparently 17 bagels, and it doesn't appear to have pop limits, but it's currently disabled from being votable for whatever reason. It can only be admin-rigged.

**Comment by nervere** [comment]
My bad, I got it confused with Lowfat Bagel.
Seems like this is just an admin thing then, or as Eneocho said perhaps it's just not compiled.

**Comment by Exxion** [comment]
It has `is_enabled = FALSE`, so it's not going to show up in the voting menu regardless of whether or not it's compiled or its conditions are met

**Comment by Eneocho** [comment]
> It has `is_enabled = FALSE`, so it's not going to show up in the voting menu regardless of whether or not it's compiled or its conditions are met

Then why have the bagels condition in the first place?

**Comment by Eneocho** [comment]
Should this one be re-opened?

**Comment by Exxion** [comment]
>Then why have the bagels condition in the first place?

My guess is that it was disabled on Pomf's end at the time the code was refactored and it was set that way to maintain equivalence

>Should this one be re-opened?

I mean it could be but it would also be basically just as easy to have the discussion in a one-line PR to change it
https://github.com/vgstation-coders/vgstation13/blob/15e8ff2efd5f3e8c73ace1e8f70414c7f6f7852a/code/datums/next_map.dm#L33
