### ISSUE TITLE
Proto-kinetic accelerator cuts rock like butter

### ISSUE THREAD

**Issue by Duny-** [d3athrow/vgstation13#3222]
The proto-kinetic accelerator's projectiles destroy every rock in their path, leave the ore intact, and automatically detonate gibtonite.
Seen done by an enbiborg.

**Comment by YakumoChen** [comment]
I think it's intentional, as it helps clear a path to mobs in the 'roid, and it's also balanced by the fact that PKAs have limited ammo / recharge time if you're a borg.

Not really a big issue, it any.

**Comment by clusterfack** [comment]
They should delete after colliding with the first wall

**Comment by Duny-** [comment]
/>it's also balanced by
If it looked balanced and not like a bug I wouldn't have made an issue, the borg mined enough to build two new stations in the 5 minutes I observed him shoot everywhere. On top of causing a fuckton of explosions.

**Comment by YakumoChen** [comment]
oh, I thought you were describing it how clusterfack said, I understand now.

**Comment by 9600bauds** [comment]
Seems wonky - after a few hundred blocks mined out, the kinetic accelerator suddenly reverts to only breaking one tile.

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/commit/7b71cce700b2b1fea9ed089ca499af1918a68486
