### ISSUE TITLE
break toolboxes with one kick

### ISSUE THREAD

**Issue by adacovsk** [d3athrow/vgstation13#32230]
you can break a toolbox with one kick and delete the toolbox with everything inside of it

**Comment by Kharkov72** [comment]
feature

**Comment by Hinaichigo** [comment]
Toolboxes aren't supposed to be breakable (for now anyway); I think it's one place in item/kick_act that lacks a check. I think I know what has to be done to fix it.

Was this bug also active when kicking itself was broken? Or only after the hotfix?

**Comment by adacovsk** [comment]
before

**Comment by Hinaichigo** [comment]
Okay thanks.
