### ISSUE TITLE
ITS FREE MONEY

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32253]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
eae56453ce17b27f0b8c6958c1ede03269c9aefc

# Description
If you haven't got enough money in your wallet to buy a lottery ticket it prompts you to pay the rest using your bank account, selecting no doesn't charge you but you still get a ticket.
# Steps to Reproduce
have <20 credits, buy 20 credit lotto ticket, select no
# What you Expected
no ticket
# What Actually Happened
free ticket

**Comment by west3436** [comment]
the vendor inherits standard vendor behavior so I don't see why this would only affect lotto tickets

**Comment by Blithering** [comment]
Didn't test with anything but lotto tickets at the time but it's worth investigating, you could potentially get anything for free this way.

**Comment by Hinaichigo** [comment]
How do you get to the menu for this? I don't even see a "No" option, it just pays automatically out of the virtual wallet first, and when that's out of funds it pays from the bank account. When that runs out "Pay" says "insufficient funds" and "Cancel" just cancels normally.

**Comment by troots** [comment]
It ain't free, if you dont have enough money in your PDA, it will pull money from your virtual account instead - the issue here is that selecting "no" doesn't do anything, it still does the transaction as if you pressed Yes

**Comment by Hinaichigo** [comment]
The only options I see are "Vend" on the main screen where you select a type of ticket, and then "Pay" and "Cancel" on the subsequent screens. How do you access the screen with "Yes" and "No"?
![lotto1](https://user-images.githubusercontent.com/7112773/159163027-9ea9341d-cd83-44dd-9b21-d3185a7243a7.png)
![lotto2](https://user-images.githubusercontent.com/7112773/159163028-28b1ec13-d899-4105-a1fd-e655da0fa94d.png)

**Comment by troots** [comment]
not enough money in your pda, when you press pay it should put a window titled Card Transaction: "Apply remaining balance of $1 from NAME's ID CARD virtual wallet? YES/NO", and no matter what you press, it will still purchase (if there is money present)

**Comment by Hinaichigo** [comment]
What inventory slots are the PDA and the ID card in for the setup that gets that to happen?
Just keeping the ID card inserted into the PDA which is on the ID inventory slot, I can't seem to see it.

**Comment by Blithering** [comment]
> It ain't free, if you dont have enough money in your PDA, it will pull money from your virtual account instead - the issue here is that selecting "no" doesn't do anything, it still does the transaction as if you pressed Yes

It definitely didn't remove money from my wallet and I bought the entire stock of the vendor out. Either they're paying mimes a lot more these days or it wasn't draining my account either.

**Comment by Cartlord** [comment]
> What inventory slots are the PDA and the ID card in for the setup that gets that to happen? 



P.D.A. in ID slot, ID in P.D.A.. Have less cash in your P.D.A.'s virtual wallet than is needed for a transaction, and it'll ask if you want to drain the rest of the wallet or take all the money from your account. This is most easily done by playing a Shaft Miner, mining some shit (fills your account, but doesn't affect wallet), and then buying every piece of usual mining kit - two K.A.s, soap, knife, etc.
It might be that you need to have account security set a certain way for it to happen - I keep it at one.

**Comment by Exxion** [comment]
Also couldn't reproduce. It very clearly says that it's removing money from the bank account and says how much remains afterward, and you can see it go down. If you're not getting these messages, there must be something else required to reproduce it.
