### ISSUE TITLE
Small MaMI note

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3226]
Not sure if this would be a bug report or request, but MaMI's are treated as proper organs and because of this a certain time outside of a freezer or corpse will make them die and become worthless.
Considering they're made within Research, chances are they won't be able to be put into a corpse or freezer quickly enough unless everything was pre-planned, which while possible, can be frustrating if not known beforehand.

**Comment by CptWad** [comment]
That means someone needs to write a manual.
If I knew how I would.

**Comment by Kurfursten** [comment]
Addressed by https://github.com/d3athrow/vgstation13/pull/3340
