### ISSUE TITLE
PLASTIC BAGS ON HEAD

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32265]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
892c0e9fc1e2d48a2a83249fd6c93f526ff5112c

# Description
can't put them on my head anymore
# Steps to Reproduce
try to put plastic bag on head
# What you Expected
to suffocate self with plastic bag
# What Actually Happened
It went into my belt slot

**Comment by Exxion** [comment]
I was going to ask if you knew that quick equip wasn't the only way to equip things, but it turns out that it actually still preferentially quick equips to the head anyway!
I'm guessing the bag in question just wasn't empty.

**Comment by Eneocho** [comment]
>I'm guessing the bag in question just wasn't empty.

I think plastic bags empty to the floor if you try to put them in your head with stuff on.

**Comment by Exxion** [comment]
I don't remember if I specifically tried equipping it to the head while not empty, but it definitely doesn't *quick* equip to the head while not empty. Given that the report says it went onto the belt, he presumably used quick equip.

**Comment by WindowsErrors** [comment]
what's quick equip

**Comment by Eneocho** [comment]
> what's quick equip

Pressing the hotkey (or the E next to hand swap) to equip something moves it to the appropriate area, shoes to feet, headset to ear, gloves to hands, etc.

**Comment by WindowsErrors** [comment]
is it like that one time where i signed up for chemist for the first time in months and within seconds the orderly was shouting on the medical channel that she accidentally put the straitjacket on herself and now i know that it was because of quick equip

**Comment by Exxion** [comment]
From a game design perspective, quick equip's logic should be changed to avoid noob traps like those. So never quick equip plastic bag to head, straitjacket to body, etc.
However, the mishaps it causes are generally funny.

**Comment by nervere** [comment]
Tested this, putting a bag on your head doesn't quick-equip to head and instead goes to belt if there's contents inside of it.
Not a bug as this is intended behavior.
