### ISSUE TITLE
Crate Fowarding does not foward crates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32275]
(WEB REPORT BY: thathazmatyoukilledinsof REMOTE: 206.221.180.138:7777)
# Revision
93d2deb731e16ba6abcbf3a1ed330ebc0f2658c2

# Description
The crate foward system is simply broken. I weigh the boxes, I stamp the boxes, I send the boxes back, and sometimes, the game will even tell me I fowarded successfully. But you know what, nothing happens. The crates remain on the shuttle, the shipping manifests remain on the shuttle, and god forbid I open the super mario cart on the shuttle in a desprate attempt send it back, the keys will now be missing from the shuttle and the cart will still remain for the next time I call the shuttle. In one occurence, the game told me I sent the super mario cart back successfully, and when I called the shuttle back, with the cart still on the shuttle, with the supply console not listing any crates to be fowarded, after what must have been five minutes the console barked at me that I failed to foward the Go-kart due to the time running out, and the reward was to be docked. This was something I thought was funny since I was unsure where this reward was even to come from, is this a reward for pay increases, is this a reward for the cargo debit? And why is this happening anyway? Was this update not tested, or am I somehow doing something incorrect here? Either way this whole system is fucking retarded busy work, and I cannot even conveive why it was added in the first place.

# Steps to Reproduce
Place crate on crate weighter with the shipping manifest inside, once the manifest is spit out, place the crate with the manifest ontop of it and send the shuttle before the alloted time is up
# What you Expected
A successful crate foward with a departmental pay increase
# What Actually Happened
The crate remains on the shuttle even after sending the shuttle back and getting a "successful" crate foward. Uncertaincy if anything even happened followed by the supply console telling me I've failed the crate foward I succeeded in after it's alloted time runs out invisibly on the supply console.

**Comment by ghost** [comment]
It 100% worked in testing, including the deletion of items, so I'm not sure what went wrong

**Comment by ghost** [comment]
Oh it was
> O.associated_manifest.associated_thing == src (src being supply shuttle)

I'm amazed that worked in the first place.
