### ISSUE TITLE
Chameleon Jumpsuit insta freezing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32283]
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
727ed38d13c29ad049b0f8988c3bd39ada2e36ac

# Description
Put on a chameleon jumpsuit I rolled randomly, instnatly dropped to freezing temp and died in a celt coma on the spot
# Steps to Reproduce
Maybe above
# What you Expected
normal clothes
# What Actually Happened
celts revenge on deadpop when im the only player

**Comment by WindowsErrors** [comment]
my man heat sinked themselves

**Comment by Eneocho** [comment]
Not a chameleon suit, a heatsink suit.
Feature(TM).
You can wear the funnysuit if you're burning/leporazine'd.
