### ISSUE TITLE
Atmos system in Telecomms ironically hastens how quickly it heats up.

### ISSUE THREAD

**Issue by YakumoChen** [d3athrow/vgstation13#3228]
It needs some testing but I've noticed that leaving the vents off in telecomms actually slows down the heating. Turning them on slowly heats the room as pressure increases, and venting the gas does nothing.
Otherwise, only radio chatter serves to increase the heat with the vents off.

Still undergoing testing, however.

**Comment by clusterfack** [comment]
Yeah because its injection 20C air so of course its warming it up, telecomms rarely overheats anyway so not that big of a deal.
