### ISSUE TITLE
T-ray scanner reveals people with the chameleon gene

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#3229]
Makes them blink in and out of existence.
Might be intentional, I have no clue, but I thought it looked silly.
![t-rays](https://cloud.githubusercontent.com/assets/3892856/6392303/fbf71b3a-bdc7-11e4-958d-fa1a845b5339.gif)

**Comment by smet19** [comment]
Lel

**Comment by ComicIronic** [comment]
Deliberate, no?

**Comment by BestName** [comment]
You tell me.

**Comment by clusterfack** [comment]
T-ray scanner reveals things that normally cant be seen, I mean if you wrap your head around it it seems like it makes sense.

**Comment by Killette2** [comment]
I don't know what to think about this but I could stare at that gif for hours.

**Comment by PJB3005** [comment]
it's a feeaaaature

**Comment by Zth--** [comment]
Close it
