### ISSUE TITLE
Black Site Prism Boundaries

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32295]
(WEB REPORT BY: valkyrieskies REMOTE: 206.221.180.138:7777)
# Revision
e2fcfac9c8a29752da02d2338af4e0051f7fdab7

# Description
The Black Site Prism vault has a bad habit of spawning too close to the edges of z-levels and thus being impossible to properly navigate due to certain areas going beyond the threshold of the z-level.

**Comment by Exxion** [comment]
Sounds more like vault spawning code doesn't properly avoid Z-level boundaries
