### ISSUE TITLE
Banana Serum

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32306]
(WEB REPORT BY: adacovsk REMOTE: 206.221.180.138:7777)
# Revision
f4f39393aaf5bdfecb3b12b8ccefa69c4c8e3300

# Description
Consuming banana-nut bread gives you clumsy forever until consuming rye
# Steps to Reproduce
eat banana-nut bread in Box maint
# What you Expected
Enjoy some banana-nut bread without any negative effects
# What Actually Happened
blew up three e-guns and my captain's laser

**Comment by Eneocho** [comment]
You sure it was the banana nut bread? BNB has no honk serum (the chem that causes clumsy).

**Comment by Kurfursten** [comment]
Unable to reproduce on live, tried with both spawned and actually cooked variants

It must have been sabotaged
