### ISSUE TITLE
Liberator missing sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32314]
(WEB REPORT BY: thathazmatyoukilledinsof REMOTE: 206.221.180.138:7777)
# Revision
1b7e183a7c1318a872f65b023a4e425d78e72625

# Description
For whatever reason the liberator looses it's sprite when fully charged with a recharger
# Steps to Reproduce
Use liberator until empty, and then recharge to full in a recharger
# What you Expected
To see the sprite when I went to pick up the fully charged gun
# What Actually Happened
no sprite

**Comment by Kurfursten** [comment]
caused by #32236 
didn't properly update the gun sprites

should have tested your PR!

**Comment by Eneocho** [comment]
How though? That PR only reduces the cost per shot, not how much it has to charge or how much charge it can hold. Sprites should've worked the same.

**Comment by Eneocho** [comment]
I get it, you used power charge divided by powercost to get the iconstage. I'll see what I can do.
