### ISSUE TITLE
Body Bags Turned into Morgue Trays Delete People

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#32311]
#### Description of issue
When you have a body bag with a person inside and turn that body bag into a morgue tray, the person will be deleted, turning him into a ghost and sending that ghost to the arrivals shuttle.

#### Difference between expected and actual behavior
This used to just have the person inside the bag appear on top of the morgue tray when you turned the bag into a tray, honestly I'd rather just have the person appear inside the tray itself.
What actually happens is that the person inside the bag disappears completely.

#### Steps to reproduce
For this recipe, you need:

- 1 disposable buddy
- 5 sheets of metal
- 1 body bag

1. Have your buddy lie down the floor in a comfortable position
2. Position the body bag under them and unzip
3. Once you have zipped the bag closed, use your sheets of metal on the body bag containing your buddy
4. Let your brain cook for about a minute as you struggle to locate your buddy

#### Length of time in which bug has been known to occur

I feel like it's been at least a month with this going on, it's not a new issue for me.

#### Server revision

c97c32dafa1be14413a480d9c928117fee8fc169

**Comment by ValkyrieSkies** [comment]
Honestly the recipe for a morgue tray has always been rather stupid in my opinion. Why don't we just make it a structure built from metal?
