### ISSUE TITLE
MoMMIs and Tackling make mustard gas

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#32327]
so when you tackle someone, they eventually get back up, but not mommis! it might be related to how silicons process knockdown, but they never regain control, even setting knockdown to 0 and stunned to 0, they can no longer interface with shit. Kinda a big bug.

**Comment by ValkyrieSkies** [comment]
This can be fixed in-game via proc calling "self_righting" on the MoMMI/borg, but it's strange that it doesn't happen naturally.

**Comment by Eneocho** [comment]
It's intended that borgs can't right themselves when tipped, but they can still move/interact with some stuff. MoMMI being permafucked is definitely a bug though.

**Comment by Eneocho** [comment]
The intention is that you can still move/interact very basically as a crab. The fact that they can't even move is a bug.

**Comment by Exxion** [comment]
today i will tip over a six-legged robot wider than it is tall

**Comment by pedr69** [comment]
can close this now i think
