### ISSUE TITLE
Dumb Engineering Board Name

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32343]
(WEB REPORT BY: valkyrieskies REMOTE: 206.221.180.138:7777)
# Revision
8812b2a17649c71a1f59f7d9ee4512f38cfd6089

# Description
>Engineering >>>CYBORG<<< Mk-2 Upgrade Board
>Only upgrades MoMMIs
Literally unplayable.

**Comment by Kurfursten** [comment]
Unable to reproduce on live, was able to upgrade a eng cyborg with the module

**Comment by pedr69** [comment]
>only upgrades mommis

it upgrades both crabs and engiborgs
the mk2 upgrade sucks ass though; a socket wrench and nothing else
