### ISSUE TITLE
Custom Barsign Menu broke

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32354]
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
8c9698e6edeeae46352cf37bf53bdfe1067f682a

# Description
the Custom Barsign Menu's buttons don't work
# Steps to Reproduce
click the sign as a borg and press buttons
# What you Expected
to change the bar sign
# What Actually Happened
nothing

**Comment by Kurfursten** [comment]
Bug confirmed on live
Only happens to silicons

**Comment by Kurfursten** [comment]
Okay this is an extremely easy fix, it only effects borgs/mommis
at L196 of barsign.dm, the check is for the user to be in range OR an AI (or an adminghost). Just add `|| isrobot(usr)` and it will let borgs use the sign at range too.

Workaround: borgs can use the design from adjacent currently.
