### ISSUE TITLE
Beepsky and the sanity of cuffing in general

### ISSUE THREAD

**Issue by ValkyrieSkies** [d3athrow/vgstation13#32351]
#### Description of issue
Initially I was making this bug report about how Beepsky could cuff people who are missing a hand, but now I'm turning it into a complaint about cuffs in general. I've seen certain players use having only one hand on their tide-inclined characters as a tool to make themselves uncuffable, and it's an annoying instance of something that should be adding RP flavour just being used to powergame instead. I feel there should be some way to restrain these characters, whether it's making it so they can still be cuffed via arm-to-leg, or arm-to-arm if it's just their hand they're missing.

It'd also be appreciated if normal handcuffs could be used to legcuff people, as in the current state of things, the only way to leg cuff someone is via bolas, which are easily broken.

#### Server revision
Game: 4990a79704d91305fd563bfbf6a105f8cd80c6d1 
Patches: 609a806a066b5859e732b12938343551efcc77f7 

[sanity]

**Comment by Eneocho** [comment]
Just stunbaton/straitjacket/cuff to yourself.

**Comment by wotisjanitor** [comment]
get good

**Comment by Jack7D1** [comment]
People like that I usually just stunbaton and weld into a locker

**Comment by Servalfang** [comment]
cuff self to target

**Comment by gurfan** [comment]
kill them

**Comment by pedr69** [comment]
>the only way to leg cuff someone is via bolas

he doesn't know

**Comment by luigil101** [comment]
There's also bear traps for "leg cuffs"
if the tide becomes a tsunami, just close your eyes, say rapid, and let space law guide your hand

**Comment by Eneocho** [comment]
You can also actually make leg cuffs by using a pair of cuffs on some shoes.
