### ISSUE TITLE
Supermatter tickets only blow off real hands

### ISSUE THREAD

**Issue by west3436** [d3athrow/vgstation13#32358]
#### Description of issue
Supermatter lotto tickets will only destroy a real hand. Prosthetics, robot hands, or even peg hands are unaffected and survive the explosion. 

#### Difference between expected and actual behavior
Expected to lose a hand, ended up gaming the system. 

#### Steps to reproduce
1. Buy contraband lotto ticket and scratch it off using a tool in a robotic/prosthetic/peg hand.
2. Receive winning ticket and keep your hand. 

**Looking for feedback as to whether or not people see this as intended behavior or a bug. Will fix myself if seen as a bug.**

[bugfix]
[featureloss]

**Comment by Eneocho** [comment]
I think it was intended (and even if not, it's cool). Keep it.

**Comment by west3436** [comment]
> I think it was intended (and even if not, it's cool). Keep it.

It was not intended. Am still leaning towards keeping it, just wasn't sure if this was being abused excessively for free money.

**Comment by Eneocho** [comment]
The two guys I noticed messing with the tickets for free moneys and peg limbs got bored about 10 minutes in, sure it's free money, but with only 5 tickets per vendor you need a whole cargo operation for the funny money levels. Not to mention you that if you use them as intended (arm melting and all) you still get way too little for the cost of an arm.

**Comment by west3436** [comment]
Nobody seems to be up in arms over this, so it's not a bug
