### ISSUE TITLE
SaMMIs are able to use the Damage Control channel despite not being keeper.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#32372]
#### Description of issue
They can chat with soviet mommis and regular mommis on the mommichat just fine, despite not having keeper laws.
#### Difference between expected and actual behavior
Expected to NOT be able to talk.
We talked.
#### Steps to reproduce
Get a sammi and mommi together, they will talk on mommichat.
#### Length of time in which bug has been known to occur
When SaMMI was made, they didn't remove the mommichat from 'em when copying mommicode, so bug has happened from the start.
[bugfix]

**Comment by pedr69** [comment]
fixed in #33840

**Comment by Eneocho** [comment]
True. Thanks pedr.
