### ISSUE TITLE
transit tube construction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32378]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
it's all sorts of wonky

all the different segments turn into straight horizontal pipes when glass is added
pods turn into a horizontal segment
adding the board to the station and pod doesn't put the board inside, if you pry it out later it teleports the one you "put in" into your hand
you can't deconstruct the stations
the things dont even work

**Comment by Exxion** [comment]
Transit tubes have always been horrifically buggy and they don't even have an excuse for it
