### ISSUE TITLE
Plates used on the Poutine Ocean/Citadel are deleted upon consumption

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32375]
(WEB REPORT BY: luigil101 REMOTE: 206.221.180.138:7777)
# Revision
a5673433ee111725aa37837ed5e0f8f5ec0eff30

# Description
the relatively limited number of plates the chef gets evaporates before the might of Canada when they shouldn't be
# Steps to Reproduce
take plate
use on poutine ocean/citadel to get some
eat
# What you Expected
to get the plate back
# What Actually Happened
plate was consumed alongside the poutine

**Comment by Kurfursten** [comment]
Just give the poutine plate a dirty plate trash item
