### ISSUE TITLE
Engineering Silicon Fuckery

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3239]
Items that you have in your module inventory just start appearing and disappearing and they just go everywhere.
I don't know how to produce this, or how it happens, or why it happens.
It just seems to happen to the silicons geared towards engineering, Cyborg Engineer and MoMMI in my experience.
![whatthefuck](https://cloud.githubusercontent.com/assets/6224074/6401051/6bffbbb4-bdcb-11e4-819f-8ed3bc61b51c.png)
JUST LOOK AT IT

**Comment by ComicIronic** [comment]
You're going to have to be more clear in what is happening.
Are modules disappearing completely?
Are the icons disappearing?
Do the duplicate icons connect to the same objects, or different ones?

**Comment by Ephx1** [comment]
Sorry, should've mentioned just the icons themselves.
Duplicate icons just keep appearing and disappearing. Not selectable, and usually using the item in your inventory does nothing at all to alter their position.
They just sort've appear all over the place randomly.

**Comment by Midaychi** [comment]
I think it might have to do with other silicons creating metal material and it ending up in everyone's silicon thing from time to time.

**Comment by PJB3005** [comment]
mat synth stacks + autolathe = PAIN in general
