### ISSUE TITLE
1x3 maint room on Asteroid station griefs space ninjas

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32392]
(WEB REPORT BY: mcgstyle REMOTE: 206.221.180.138:7777)
# Revision
e002d4ed3ef571bbebb904372a65d6304fc0f565

# Description
Got to be a ninja on Asteroid. Chose TP to station. Stuck in a 1x3 room.

Ahelped to get out. Used hologram when shot at and got teleported right back in
# Steps to Reproduce
see above
# What you Expected
antagonizing the crew
# What Actually Happened
committed seppukku in said 1x3 room because the map is shit

**Comment by Kurfursten** [comment]
Every station, even box, has cubbies like this. With an esword you can slice the wall open and then slice the girder. You suicided for no reason.
