### ISSUE TITLE
lowfat bagel pipee

### ISSUE THREAD

**Issue by robintime** [d3athrow/vgstation13#32399]
![uhuikuiiuhkkllk](https://user-images.githubusercontent.com/81062934/163509256-a0ff83b9-4d8b-440a-9f97-40c8b9fe6daf.png)
what the fuck?

**Comment by Eneocho** [comment]
powerful pipegunk

**Comment by kernikov** [comment]
there's at least two instances of that there in that waste manifold
thank you robin
