### ISSUE TITLE
Laser pointing mulebots can pick up things it probably shouldn't

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32400]
(WEB REPORT BY: thathazmatyoukilledinsof REMOTE: 206.221.180.138:7777)
# Revision
e9f6a4213e72d2a2be2574f7aeb18b4755aefcf6

# Description
Mulebots have the likely unintended effect to pickup fucking everything from airlock doors, to wall flashes.
# Steps to Reproduce
Point at an airlock to have it load it then after switching modes, point somewhere you want it to placed
# What you Expected
Mulebots to act like mulebots
# What Actually Happened
Mulebots acting like MegaMulebots

**Comment by Kurfursten** [comment]
@ShiftyRail

**Comment by Eneocho** [comment]
bASED

**Comment by Eneocho** [comment]
bASED

**Comment by Eneocho** [comment]
Mulebot picking up the singulo when

**Comment by WindowsErrors** [comment]
i have already picked up the airlocks leading into the bridge and security department

**Comment by tuypo1** [comment]
Can this be permanent for emaged ones
would also justify giving the fucking captain a pointer for some reason, at least he has use for it now

**Comment by Kurfursten** [comment]
In fairness I thought giving extra copies to the hop and cap was strange. If replacements were needed they could be ordered or something. Maybe a QM access crate.

**Comment by Eneocho** [comment]
Or just make em mechanics scannable/RnD printable.

**Comment by tuypo1** [comment]
Hop is kind of understandable but yeah cap is weird, being able to just make more seems like a fine solution

**Comment by ShiftyRail** [comment]
Hahahaha
V. funny

**Comment by WindowsErrors** [comment]
on the plus side this has made mules more viable than anyone could have ever thought

**Comment by WindowsErrors** [comment]
i use the mulebot laser pointer to direct a mulebot somewhere down the hall

loppu unknowingly walks in between the mulebot's current position and its destination and in a reflex i use the laser pointer to direct the mulebot in a reverse direction

what ends up actually happening is that the mulebot goes to its original destination, pushing over and running over loppu, before then going to the second reverse destination, backing up over loppu again

there is now loppu blood all over the floor and I have run them over twice

oops

**Comment by Eneocho** [comment]
A hard stop button when the pointer is used inhand would be nice, to fix issues/stop the running over/backing up issue just mentioned.

**Comment by WindowsErrors** [comment]
can't help being a sagittarius

**Comment by Kurfursten** [comment]
Using in-hand toggles from load to unload so we don't want that to be used for hard stop
