### ISSUE TITLE
Can't Publish News Story on Metaclub

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32420]
(WEB REPORT BY: hinaichigo REMOTE: 206.221.180.138:7777)
# Revision
c894ce81b0592d33e1815fe225ae8b23d4955c93

# Description
When attempting to publish a news story with a photo for syndicate challenger on metaclub, it wouldn't allow me to publish. I was using an agent ID card if that makes a difference.

# Steps to Reproduce
Try to publish a news story on Metaclub.

# What you Expected
New story published.
# What Actually Happened
News story not published.

**Comment by Kurfursten** [comment]
cannot produce on live, most likely he wasn't wearing his ID

**Comment by DamianX** [comment]
Is there an error message telling players why it doesn't publish the thing?

**Comment by Kurfursten** [comment]
There is but it is directly on the UI and the top line of the error is ambiguous if you only read the first one

He explicitly said he was in a rush and dodging sec at the time, so he couldn't read the error message fast enough
