### ISSUE TITLE
R&D is P2W

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#32422]
Apparently those swiss army knives from cargo are children of switchtools, which for some reason have materials 9 bluespace 5; you can pay $150 ($50 ea) to get up to materials levels only ever seen by deconstructing phazon.

More bafflingly, the switchtool itself only takes materials 5 bluespace 3 to make, so there's no reason for it to be this high. Typo?

**Comment by jwhitak** [comment]
Dear lord.

**Comment by Eneocho** [comment]
Keep it as is, at least when the guy buys 3 swiss army knives you know he's gonna powergame the research.

**Comment by tomacatx2** [comment]
based, leave it in, miners need a way to skip a chunk of research when theres no nerds

**Comment by Kromkar** [comment]
> based, leave it in, miners need a way to skip a chunk of research when theres no nerds

Miners doing research. Lol

**Comment by Eneocho** [comment]
Miners tend to do some research to get the bag, drill and automatic orebag. If they feel fancy they also do normal research, but that's not that common.
Keep it in because it skips like 2/3ds of the miner research checklist.

**Comment by PrimeDSS13** [comment]
fuck they found out

**Comment by Eneocho** [comment]
The curse of the eternal coder. You either use your fun tech and have fun but risk losing it, or never use it to keep it hidden from the coder cabal. I'll never forget the absolute betrayal and heartbreak of #30553 and having lost that.

**Comment by luigil101** [comment]
You are the most homosexual man alive for exposing our devious tricks

**Comment by Eneocho** [comment]
> You are the most homosexual man alive for exposing our devious tricks

That title goes to armadingus after he exposed the multitool swiss army knife thing.
