### ISSUE TITLE
Synergy Teleport Scroll / Ghost Teleport Mismap

### ISSUE THREAD

**Issue by Kromkar** [d3athrow/vgstation13#32436]
#### Description of issue
On Synergy when you use the teleport scroll to go to Research and Development it puts you directly into a plasmafilled borer pen.

#### Difference between expected and actual behavior
>Use scroll to go dunk on science nerds
>Instead self-own via plasma bath

#### Steps to reproduce
On synergy, use the teleport scroll or ghost teleport to go to Research and Development.

**Comment by nervere** [comment]
Issue here is that there is no specific area defined in the code for the borer lab, so most maps just add it to science hallway or RnD.
Probably hasn't been fixed because it'd just be annoying to do so.

**Comment by Kromkar** [comment]
We could fix this by deleting synergy
