### ISSUE TITLE
Supermatter Chamber Issue

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3243]
This is a map issue for both meta and box

The supermatter chamber tiles have been varedited to block air and then not block air, so now they don't block air EVER, including when the door is closed. Someone needs to return the tile and likely airlock to their default state to prevent them from leaking air for no reason.

**Comment by PJB3005** [comment]
so THIS is why the SM chamber leaks

**Comment by Probe1** [comment]
AHH THATS WHY AT LAST

**Comment by ComicIronic** [comment]
Alt title: why you should not manually edit stuff to not leak air.

**Comment by Intigracy** [comment]
Was this fixed?
