### ISSUE TITLE
This shit is driving me up the MULE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32455]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
I swear to all that is good and holy that MULEbots never work! Ever! Not on Boxstation, not on Asteroid, never ever not anywhere, ever! You can load them up and try to send them with the PDA app but they don't show up there so you can't order them, and then when you manually order them by interacting with them directly (unlock the controls and fiddle around until you hit "proceed") they just BLINK RED AND SIT STILL like annoying little manchildren! And this is a big problem, because HALF the time, the mailtubes just send all the shit you're trying to shoot off around the station on a constant disposals loop EVEN THOUGH I MADE TRIPLE SURE TO WRAP THE CRATES AND TAG THEM. I'm just tring to tdo my gotmanm JOB!

**Comment by WindowsErrors** [comment]
mulebots used to be old code, which meant shit code

there's still the thing with mulebots where it's stuck in a constant loop of pathfinding which is probably what you're talking about

**Comment by ManopolisJones** [comment]
Part of me wants to say skill issue, but the other part of me wants to say remove mules in place of a rapid crate system on roundstart, with pads where the old mulebot delivery ports would be.

**Comment by Rhimrifer** [comment]
They've been broke since either pathing was switched to A* for mobs or one of the attempts to fix it. They're nothing but pAI murder tractors now.

**Comment by N3X15** [comment]
May be a side-effect of https://github.com/vgstation-coders/vgstation13/issues/26208
