### ISSUE TITLE
Remove ID from PDA lists mobs not in range.

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#32460]
#### Description of issue
It seems like something changed recently where now, when you try to remove an ID from a PDA, it will open a prompt asking to select a mob within sight range. For example, see this image:
![remove_id](https://user-images.githubusercontent.com/7112773/165342562-8cb8f067-d5db-4393-8897-a2d417e9dca9.png)
Pun Pun doesn't have a PDA. This only started happening in recent weeks at the earliest I believe, but could be wrong.

#### Difference between expected and actual behavior
Remove ID from PDA opens a prompt to select a mob within view range. I'd expect it just to remove the ID as long as there was only 1 PDA within range.

#### Steps to reproduce
Use "Remove ID" from PDA verb within view range of another human or carbon such as Pun Pun. Not sure if it applies to other mobtypes, but that shouldn't be too relevant. Putting one's ID into their PDA, walking into the bar in sight of Pun Pun, and "Remove ID"ing is an easy way to test it.

#### Length of time in which bug has been known to occur
A week or two at most.

#### Server revision
Game: c966ba59fd096079149309cff3c8c6ead946cfbc 
Patches: 609a806a066b5859e732b12938343551efcc77f7 

[bugfix]

**Comment by DorainGrey** [comment]
I thought this was something I'd broken by messing with preferences, it's definitely been present more than 2 weeks though.  At least a month.
I'd imagine it's related to #32163

**Comment by pedr69** [comment]
can confirm has been happening a while, almost certain i've been getting remove ID wonkyness in my verbs since #32163 
this is probably related
