### ISSUE TITLE
Pizza RPGs are fucking SCAMS

### ISSUE THREAD

**Issue by Kharkov72** [d3athrow/vgstation13#32463]
so it spawns a bunch of pizza slices right
but look at this
`/obj/item/weapon/reagent_containers/food/snacks/sliceable/pizza
	slices_num = 6
	storage_slots = 4
	w_class = W_CLASS_MEDIUM
	base_crumb_chance = 20`

`/obj/item/weapon/reagent_containers/food/snacks/sliceable/pizza/margherita
	name = "Margherita"
	desc = "The most cheesy pizza in galaxy!"
	icon_state = "pizzamargherita"
	slice_path = /obj/item/weapon/reagent_containers/food/snacks/margheritaslice
	storage_slots = 4
	w_class = W_CLASS_MEDIUM
	food_flags = FOOD_ANIMAL | FOOD_LACTOSE //cheese`
	
	`/obj/item/weapon/reagent_containers/food/snacks/sliceable/pizza/margherita/New()
	..()
	reagents.add_reagent(NUTRIMENT, 40)
	reagents.add_reagent(TOMATOJUICE, 6)
	bitesize = 2`

`/obj/item/weapon/reagent_containers/food/snacks/margheritaslice
	name = "Margherita slice"
	desc = "A slice of the most cheesy pizza in galaxy."
	icon_state = "pizzamargheritaslice"
	bitesize = 2
	food_flags = FOOD_ANIMAL | FOOD_LACTOSE`

the slice doesn't actually start with shit, it comes down from the full pizza when sliced
probably want to make a special subtype that adds reagents in the new()
[bus] [bugfix] [easy] [oversight]

**Comment by Kharkov72** [comment]
i thought the bus tag was for adminbus you fucking CRAB

**Comment by Eneocho** [comment]
Or we could make it spawn full pizzas.

**Comment by adacovsk** [comment]
there is a bus map?

**Comment by Eneocho** [comment]
I think it means bussed maps, like xoq, dorf, etc.

**Comment by Exxion** [comment]
There was a map called Bus a few years ago. I guess the label and autolabel option were never removed.

**Comment by Eneocho** [comment]
Many of the labels are outdated, dead or missing, but we ain't getting an update anytime soon (unless someone convinces PJB).

**Comment by Blithering** [comment]
Same happens with all sliceables. If silver cores spawn cake or bread you get a mouthful of nothing
