### ISSUE TITLE
Delete Bugs

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3246]
Current delete issues:

-deleting any machinery drops their components
-deleting mobs with adminghosts spawns a ghost
-making constructs makes ckeyless shades (or something to that effect) - fixed

**Comment by ComicIronic** [comment]
This has always been the way it works.
That's what Destroy does.

**Comment by clusterfack** [comment]
Eh, fine. But I certainly don't see why components should be coming out of deleted machines. That actually makes no sense.
