### ISSUE TITLE
Construction of cult items in crit pain

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32474]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
f96111739ee457b0f2dd4bcce80b6fdbc1aefb6b

# Description
in the middle of a fight against the cult I tried to finish a shell for the shade that got broken out of his sword, even in pain crit  I continued to build it
# Steps to Reproduce
get put into pain crit while building an item and even when you fall over in agony you continue to faithfully build
# What you Expected
to writhe on the floor in pain
# What Actually Happened
I built a shell

**Comment by Eneocho** [comment]
![based cultnigger](https://user-images.githubusercontent.com/67024428/165669567-e260a495-fc8b-448d-9f20-602040a71a0f.png)

**Comment by Kurfursten** [comment]
@DeityLink
