### ISSUE TITLE
Odysseus syringe gun doesn't work properly

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#3247]
Normally you analyze a reagent in analyze mode, go to the view riegents thing in info, check the reagent and start producing. It fills the reagent pool, and that works just fine.

What doesn't work: When you launch a syringe, it launches an empty syringe and doesn't detract from the reagent pool, and target gets injected with no reagents.
https://dl.dropbox.com/s/vp0dgzouddcj3i6/derpgnt.png

Edit: ok So I tested this quite a bit before I posted, on a live round, and as soon as I posted this issue I went back and the odysseus syringe gun started working as intended. Weird

Edit 2: what actually happened: I shot a syringe at the ground, and it was loaded from the reagent pool, then launched it at a target and it worked as intended.
I  launched another syringe at a target though and it didn't detract from reagent pool and was empty. Had to repeat step one to get working.

**Comment by gbasood** [comment]
I think this might actually still be relevant
We had an issue recently on the oddy being bad/too good/something

**Comment by Midaychi** [comment]
I mean, if it's still an issue then there might be something breaking behind the scenes that's triggering this behaviour only some of the time, and it would be hard to know when that is.
