### ISSUE TITLE
entertainment staff don't appear in the accounts database

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32480]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
f96111739ee457b0f2dd4bcce80b6fdbc1aefb6b

# Description
title
# Steps to Reproduce
have an entertainer join the round (maybe only from roundstart) and try to access their account via the accounts database
# What you Expected
game to work properly
# What Actually Happened
why it no work!!

**Comment by Eneocho** [comment]
The clown and mime names don't change in the account database. If you join as "john mcclown" but change it via prompt to "honky the mass luber", the name still appears as "john mcclown".

**Comment by adacovsk** [comment]
If you random name, it makes it difficult to find your name, but it's there, just gotta do elimination. It shouldn't be this way though
