### ISSUE TITLE
Gas miners don't turn on after being unwrenched and then wrenched

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3249]
I tried every tool, nothing, couldn't turn it on.

**Comment by ComicIronic** [comment]
Did you try using your hand?

**Comment by frangi** [comment]
Yes, but I tried it as a mommi

**Comment by ComicIronic** [comment]
That will likely have been the issue.
Remember to put as much detail as possible in your initial issue reports, because otherwise it's much harder to bugtest and fix.

**Comment by Probe1** [comment]
I've encountered this as a mommi on the derelict a month ago.  Unwrenched it and it turned off, wrenched it on and it didn't turn back on iirc.  But I do distinctly remember unwrenching it (and making it not attached) and it turned back on!  and then blew itself and me into the corner of the gas chamber.

Shit was fucked up.

**Comment by ghost** [comment]
Still an issue, this is odd

**Comment by Intigracy** [comment]
lmao commit reference spam sorry fams
