### ISSUE TITLE
Pulse demons can't raise their charge cap.

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#32494]
#### Description of issue
It seems like pulse demons have no way to raise the maximum amount of charge they can hold. I remember before you could buy upgrades to increase it but now I can't seem to find the option. Because of this you can't buy any of the other upgrades as they all cost more than the starting charge cap.

#### Difference between expected and actual behavior
I expected you to be able to increase the pulse demon charge cap via upgrades and thereby afford more upgrades.
The actual behavior was that there was no apparent way to do this.

#### Steps to reproduce
Be pulse demon. Try to buy upgrades. Notice that your maximum charge is less than the cost of all of the available upgrades, and that there is no upgrade to increase the cap.

#### Length of time in which bug has been known to occur
Maybe a few weeks or so.

[bugfix]

**Comment by wotisjanitor** [comment]
Man did you read the wiki page

**Comment by Eneocho** [comment]
Bruh. Literally on the wiki page. You gotta siphon power to increase your charge cap. The most you ever siphoned is your new charge cap, and you can't siphon more power than the max power I/O in a battery/SMES with the small exception that APCs give you 5x their charge to make them useable.
This means: An unupgraded SMES has a max power input/output of 200kw. Even if the SMES is half empty, you can get in and steal up to 200kw in one go without using it. If you stay on the SMES while at 200kw, you will not siphon more power until you use it.

**Comment by Hinaichigo** [comment]
Oh... my mistake. It changed from how it used to be so I was confused.

**Comment by Eneocho** [comment]
As a rule of thumb friend, if shit changed it was probably updated on the wiki (except the cult page, I aint touching that with a 10km pole).
