### ISSUE TITLE
Killtheking bundle has no implanter

### ISSUE THREAD

**Issue by west3436** [d3athrow/vgstation13#32511]
#### Description of issue
Bundle added in #32465 contains the actual implant items instead of greytide implanters, preventing you from using them in any way

#### Difference between expected and actual behavior
Expected implanters so I could actually greytide people, received useless implant items I left on the kitchen counter

#### Steps to reproduce
1. Get killtheking bundle
2. Suffer

#### Length of time in which bug has been known to occur
Since #32465 

[featureloss]

**Comment by WindowsErrors** [comment]
yea the assistant walked up to the security reception and awkwardly handed me 3 greytide implants that you put on the kitchen counter

**Comment by Servalfang** [comment]
FUCK

**Comment by pedr69** [comment]
you can still use those, but you need to surgery them inside people before they start working
at least thats how the explosive ones work

**Comment by Kurfursten** [comment]
Yes, you can; hence my joke in the PR that it's a skill issue

But it was probably too much to ask people to do that
