### ISSUE TITLE
Power cables disappear after being laid

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3251]
this happened outside the derelict teleporter multiple times, they don't ALWAYS disappear, but 70% they do.

**Comment by Ephx1** [comment]
It seemed like certain wires were "connected" in the sense that placing one wire will affect another very specific wire.

**Comment by 9600bauds** [comment]
Related webm's
http://puu.sh/gfdpn/04f0ef3323.webm
http://puu.sh/gfdt3/6e265202e2.webm

**Comment by ComicIronic** [comment]
Maybe be to do with objects not being removed from pooling correctly.
