### ISSUE TITLE
Vox becoming uninjectable

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3252]
Just tried to save a vox at 0% blood (died from it), but without giving him new blood defibbing will just result in a death shortly after, except I couldn't get him new blood (not with IV drip OR syringe, the syringe simply didn't inject anything)

also it seemed to start happening once I fixed his bleeding head

**Comment by IratePirate** [comment]
https://www.youtube.com/watch?v=Gt9vKzolN9c

**Comment by TermedClepe** [comment]
This is not related just to vox, I had this happen with a human patient. Were there vampires involved?

**Comment by PJB3005** [comment]
I don't know if there were any vampires that round, don't think there were

**Comment by gbasood** [comment]
Re-open if still relevant
