### ISSUE TITLE
[Meta] No Vox trading outpost, salvage ship jumps to nothing

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3253]
Metaclub doesn't have a Vox trading outpost, which would (theoretically) be used during Vox raiders and allows miners to grab jetpacks from breaking into the Vox armory (plus other stuff)
The salvage ship still has a "trading outpost" beacon, jumping to it just puts you over the asteroid floating around on nothing.
Not a HUGE deal but I miss getting free jetpacks and gas canisters when the server changes to Meta

**Comment by IratePirate** [comment]
I'll see what I can do about this.
