### ISSUE TITLE
ejecting a (tracking) implant case out of the implant pad destroys it without a trace

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32533]
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
c4b7bcdad6757afb6138ade2bffe48518a06143e

# Description
i put a tracking implant case in the implant pad and then ejected it and it poofed

i haven't tested this with any of the other implants though

**Comment by pedr69** [comment]
yeah you gotta take it out with an empty or it gets sent into the void
