### ISSUE TITLE
[Meta&others] Pod bay needs R&D console

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3255]
See #3074 and https://github.com/d3athrow/vgstation13/pull/3213
After recent changes, you need an R&D console to sync research levels for the Spacepod fabricator. As far as I know, Box is the only map that has it yet.

**Comment by IratePirate** [comment]
This is added in the PR i've got open. Duplicate issue.

**Comment by 9600bauds** [comment]
The Meta tag can be removed then, not sure if the other maps even have a pod bay. Leaving this open just in case.
