### ISSUE TITLE
powercreep neuters pulse demon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32572]
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
532018a78fb4a500f989fbccaf46683302a3a73e

# Description
a pulse demon entering a tile with powercreep (maybe just uncovered tile not sure) covers creep with vines, creep can no longer move, enter apcs, do anything.
# Steps to Reproduce
be pulse demon enter tile with vine
# What you Expected
for the vines to wear off or not be essentially death, as you can still wire warp but not enter any devices.
# What Actually Happened
made me unable to act

**Comment by Hinaichigo** [comment]
Would be cool if you could move around on top of the powercreep as if it were a wire.

**Comment by Eneocho** [comment]
Assist the powercreep in growing by opening doors and shit and get power on the wires (powercreep makes a little bit of power) so you can survive even when the crew cuts all power.

**Comment by Killette3** [comment]
Power creep should allow the pulse demon to go into overdrive and be way more powerful

**Comment by pedr69** [comment]
>Would be cool if you could move around on top of the powercreep as if it were a wire.

you can, powercreep is a subtype of wire
only problem being that walking into it still gives you shock damage, instantly killing you if you don't upgrade max health beforehand

**Comment by Eneocho** [comment]
>only problem being that walking into it still gives you shock damage, instantly killing you if you don't upgrade max health beforehand

`>be entity made of electricity`
`>die to electricity`
itjustworks
