### ISSUE TITLE
PDA Minesweeper is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32585]
(WEB REPORT BY: fargit REMOTE: 206.221.180.138:7777)
# Revision
19612aba969fbd5d3563dfc1e797e06c3f11c724

# Description
Doesn't actually work. Every 2nd click is always a mine. That and there seems to be no way to put flags.
# Steps to Reproduce
Start a game of PDA minesweeper, click twice
# What you Expected
When I click on a square that shouldn't have a mine in it (I.E. the square below a corner with a one to the corner's diagonal and a one next to the square) it will be revealed
# What Actually Happened
It somehow was a mine despite it being physically impossible for a mine to be there

**Comment by Armadingus** [comment]
Skill issue.
![image](https://user-images.githubusercontent.com/55976761/167786716-85d55128-78d9-4500-8dc6-a84af7629135.png)

**Comment by nervere** [comment]
Just tested and it works fine, definitely a skill issue.
