### ISSUE TITLE
Escape pod computer affected by ZAS

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#32611]
#### Description of issue
I smashed the window of an escape pod and a bunch of stuff got ZASd out of the breach, including, unexpectedly, the escape pod computer. It seems like it's not anchored to the wall properly or something.

#### Difference between expected and actual behavior
I expected it to stay mounted into the wall of the escape pod. In actuality, it got sucked out of the broken window.

#### Steps to reproduce
Go into a normally-pressurized escape pod and break the window so that the air gets sucked out.
[bugfix]

**Comment by Kurfursten** [comment]
Just needs anchored = TRUE

**Comment by Kurfursten** [comment]
@gurfan
