### ISSUE TITLE
Solanine + water doesn't react to form Plant-B-Gone 

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#32624]
#### Description of issue
According to the wiki, solanine can be used to produce Plant-B-Gone. However, this reaction doesn't seem to function.

#### Difference between expected and actual behavior
Expected 20 units of solanine + 80 units of water to produce 100 units of Plant-B-Gone.
In actuality, the solanine and water remained in the beaker, unreacted.

#### Steps to reproduce
Add 20 units of solanine and 80 units of water to a beaker.

[bugfix]

**Comment by jwhitak** [comment]
Confirming this does not work as intended. If you mix Toxin and Solanine and then add water, it uses up an equal amount of Toxin and Solanine but only produces the Toxin amount of result. Ex: 1u Toxin, 1u Solanine, 4u water results in only 5u Plant B Gone in the beaker, no other chemicals. If it were not reacting, it would be 5u Plant B Gone and 1u Solanine in the beaker. 

I tested the Hyroalin reaction with Allicin (part of the ANTI_TOXINS list alongside anti_toxin), and it works just fine... The issue doesn't seem to be a general one with Lists of chemical reactants. What is going on here? The code below looks OK, I don't see any oddities.

```
/datum/chemical_reaction/plantbgone
	name = "Plant-B-Gone"
	id = PLANTBGONE
	result = PLANTBGONE
	required_reagents = list(TOXINS = 1, WATER = 4)
	result_amount = 5
```
```
#define TOXINS list(TOXIN, SOLANINE)
```
```
#define SOLANINE		"solanine"
```
```
/datum/reagent/toxin/solanine
	name = "Solanine"
	id = SOLANINE
	description = "A glycoalkaloid poison."
	color = "#6C8347" //rgb: 108, 131, 71
```

**Comment by adacovsk** [comment]
#27530
#21353 
Wiki needs update

**Comment by Hinaichigo** [comment]
Edited the wiki.
