### ISSUE TITLE
Unable to take items out of storage with harm-bite intent on

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32620]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
[bugfix]
# Revision
9335b52b65476bac3da7d71aba0ad5667d7084b6

# Description
Items unable to be interacted with other than right clicking when selecting them in a storage box/backpack/etc type menu with harm and bite intents on.

# Steps to Reproduce
* Select harm and bite intent
* Have a backpack or similar on
* Put item in
* Try to take the item out

# What you Expected
Item in hand

# What Actually Happened
Nothing happened

**Comment by Hinaichigo** [comment]
Is the storage item in question in the player's inventory or elsewhere?
