### ISSUE TITLE
Syringes displaying Inject/Draw when not in-hand

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3262]
Syringes obviously aren't supposed to show the INJECT or DRAW text bits when on the ground, but it seems as though if you drop one without using the drop command, it will show it.
For example, holding a Syringe with a robotic hand and causing that hand to malfunction will drop the syringe with the INJECT/DRAW text above it.

**Comment by ComicIronic** [comment]
And this is why we use mob procs.

**Comment by ComicIronic** [comment]
This should have been fixed by #3876
