### ISSUE TITLE
Fire Axe + Antimatter axe kit on back

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32654]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
f4952c5aee5744e8fda1abc5105c48fb28db19d0

# Description
Use the antimatter axe kit while you have a fire axe in your backpack slot

# Steps to Reproduce
equip fire axe in back slot
use antimatter axe kit on back
it vanishes
# What you Expected
To have a weird breathing axe
# What Actually Happened
I lost a whole thousand credits to a mistaaake

**Comment by Exxion** [comment]
Wow. It just drops the resulting antimatter axe into the original axe's `loc`. So it just ends up in your mob if it's in any inventory slot, or your hand, or whatever.
