### ISSUE TITLE
Mass Telepathy Spams Chat

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#32655]
![image](https://user-images.githubusercontent.com/9782036/169743002-307d7504-0256-457a-a668-cbdd5509fe36.png)

@adacovsk There's no reason to display it like this; CAMO doesn't flood the chat log with a million PDA messages.

**Comment by adacovsk** [comment]
jesus that's a lot of people

**Comment by angryturnip** [comment]
come look
