### ISSUE TITLE
Galo Sengen Tanning Bed Sound Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32652]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
40308d0fd0a47cc36cb3fdc79b114d0ae1cf7641

# Description
The Galo Tanner needs the reverb flag turned off on the sound effect. It is speeding up and slowing down the GALO effect unnecessarily. Sounds awful. This is a one line fix.

**Comment by nervere** [comment]
Honestly I think it sounds pretty funny to have it vary but I can also see it sounding like crap and ruining someone's expectations.
