### ISSUE TITLE
MoMMIs can't hack autolathes

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3268]
"the Autolathe refuses your inbuilt module"

**Comment by TermedClepe** [comment]
1. screwdriver autolathe open
2. click on autolathe with empty hand so you see the interface
3. select multitool/wirecutters while interface is open
4. click on cables

**Comment by Midaychi** [comment]
They can't? Must be recent because I remember hacking an autolathe not a day or two ago as a Mommi
