### ISSUE TITLE
Zombism does not work on alien races?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32683]
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
0e23a9e008b82f37c379e263cf43c2ab81a67012

# Description
Admin did a zombie bus, made some putrid zombies, i was a trader, went in to get zombied, would not zombie.
neither did the grey soldier they spawned
# Steps to Reproduce
Be trader
See zombie that can infect
die to it
Do not get back up
# What you Expected
BRAAAAAINS
# What Actually Happened
RIP

**Comment by adacovsk** [comment]
There's no naked zombie vox or grey sprites to my knowledge. @Optimism333 ?
