### ISSUE TITLE
MALF AI: Disabling hacked APCs is too easy.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#32684]
A well trained autist can disable an APC in about 2 seconds and the malf AI upgraded turrets have about a 5 second cooldown. Maybe make it so hacked APCs can't be disabled.  This would help lone malf AIs a lot.

**Comment by pedr69** [comment]
disabled as in screwdrivered open and having all its wires cut? even after doing it the turrets kept firing and killed me, then shut off and the masses stormed in and kicked and bit the AI to death
also, lone malf AI's are pretty much doomed to fail, and roid especially has a god awful core
