### ISSUE TITLE
Clovers on lotto tickets got nerfed to the ground.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#32692]
#### Description of issue
The effect of luck on lotto tickets got nerfed so hard that there's no point in farming clovers for luck. 
I tried scratching tickets with three seven leaf clovers and twenty-ish six leaf clovers, the most I won were 200 credits from a phazon ticket. The total winnings from the tickets were under 2500. About the same luck and profit margins of playing on supermatter tickets. There's no point in making the tickets affected by luck when having 50000 luckiness stat barely affect the tickets. 
I then tried the slot machines and got considerably more money, around 60K.
#### Difference between expected and actual behavior
Expected sizeable profits comparable to the effort of farming high level clover.
Got piss level profits.
#### Steps to reproduce
Get 5 seven leaf clovers (to equal the 3x10000 and 20x1000).
Scratch tickets. Get only 40-200 credits.

@Hinaichigo, you overcompensated.

**Comment by Blithering** [comment]
I'd prefer it this way, rather than just speedrunning botany to cap out luck, you gotta find rabbits feet and the like as well.

**Comment by Armadingus** [comment]
Yeah I think you're right, we should bring slot machines in line with lotto and make lucky clovers a minor increase there as well.

**Comment by Hinaichigo** [comment]
So, nerf slots a bit and buff lotto tickets a bit?

**Comment by Hinaichigo** [comment]
Since clovers can be mass produced I'll probably also take a look at amping up the effects of the curses and rabbits foot in comparison.

**Comment by Blithering** [comment]
Is there a way to cap luck from a single source? So you'd need a variety rather than 100 clovers or 100 feet

**Comment by Hinaichigo** [comment]
Not currently... unless picking up the item was to give a blessing rather than "raw luck", since you can only have one type of each blessing.

**Comment by Hinaichigo** [comment]
I kind of want to avoid doing that if we can, preferring to get nice balance with the values.
Or maybe yeah.. diminishing returns on stacking.

As a benchmark, does having 1 luckiest clover on your pocket leading to an EV of around $10,000 per 10 phazon fortunes seem reasonable?

**Comment by Eneocho** [comment]
> I'd prefer it this way, rather than just speedrunning botany to cap out luck, you gotta find rabbits feet and the like as well.

Doesn't work like that.
Rabbit feet give 50 luck, you can get the same luck with 2 4-leaf clovers. And it's not speedrunning. It has taken me a decent 40 mins to get the 7 leaf clovers. That's half a standard round right there.

**Comment by Hinaichigo** [comment]
Yeah that's why I'm thinking to buff them in comparison.

**Comment by Eneocho** [comment]
>As a benchmark, does having 1 luckiest clover on your pocket leading to an EV of around $10,000 per 10 phazon fortunes seem reasonable?

It does as long as there's a decent chance to get the higher winnings . Making it so having the literal luckiest clover but only ever getting around 10K still feels weird to me.

>Yeah that's why I'm thinking to buff them in comparison.

The same issue happens. You can just farm bunnies and chop off their feet.

>make lucky clovers a minor increase there as well

There's no point in having a complex luck system if most uses for luck get nerfed to the ground because muh balance. If you took your time and actually got a max level clover, you more than earned the max level effects. Specially now that they're harder to find.

**Comment by Eneocho** [comment]
By the way, the slots winnings weren't on the first roll, it took a while to hit the jackpot.
