### ISSUE TITLE
Negative power as pulse demon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32693]
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
c598c167831449d3d9c694e73cdfed32dc0f1445

# Description
when upgrading my cable jump I went into the negatives and was unable to even turn on my power draining ability to regain power
# Steps to Reproduce
I'm not sure it's never happened before when I upgraded cable hop?
# What you Expected
to have a better cable hop
# What Actually Happened
no power forever

**Comment by pedr69** [comment]
can reproduce by spamming upgrade ability while charging in an SMES
no idea how it's happening though

**Comment by pedr69** [comment]
nvm, found it
first the charge check happens
then the charge cost gets multiplied
then the increased cost gets deducted, resulting in negative power
