### ISSUE TITLE
[suggestion]Warning if an MoMMI attempts to synthesize more materials than its power cell can hold

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3269]
title, could really suck if you accidentally end your round by synthesizing to much

**Comment by ComicIronic** [comment]
This is already in place unless someone removed it.
Can you do this?

**Comment by PJB3005** [comment]
oh, it is, nevermind then, I was thinking about this

**Comment by ComicIronic** [comment]
In the future, please test ideas before suggesting them.
Sometimes coders have brains.
