### ISSUE TITLE
Feature Request: Greased-Up Feral Space Hogs

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#32699]
This is the official design document for feral space hogs, as originally envisioned by the great chicken, and the first of my code bounties.

The code bounty is currently $100 CAD for each approved contributor, please contact me on Discord @kernikov#8048 if you would like to discuss contributing to this effort.

### What they are
![image](https://user-images.githubusercontent.com/5549060/170820459-1d8b5863-0507-4e0b-8a06-84bb3d3fab3a.png)

- Multiple variants
- Space immune
- Skittish
- Hostile when hungry, trapped, or have nearby piglets
- Greased-up, making them space immune. Also can slip through airlocks.
- Nest in maintenance
- Attempt to kidnap nearby crew (prioritizing jobbies or assistants?), possibly a chance to headbutt KO them and drag them to the nest when unconscious, KOed or dead
- Give birth to piglets to reproduce
- Trappable with beartraps?

### Steps to produce (TBA)

- [x] Spritework (greased up space hog, space hog, piglet)
- [x] AI/pathing/whatever
- [x] Code

###Future expansion content

- Is this the origin of space lube, does authentic hog grease last longer/slip farther/provide greater TEG bonuses?
- Domestication of hogs (dropping the 'feral') prefix
- Bacon

[controversial]
[discussion]
[featurerequest]
[help]
[needspritework]
[qol]
[sanity]
-->

**Comment by KingofHONK** [comment]
dont forget that they can be distracted/pacified with corn. very important addition

**Comment by Eneocho** [comment]
Just use the current hog icon, scale it down for piglets and add a colour matrix effect for greased up hogs, no spritework required.

**Comment by kernikov** [comment]
Kurfursten has been paid for all his work for pigkind.
