### ISSUE TITLE
Camera Bugs Stop Ventcrawling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32702]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
f635e7af3aa6daa28cc874a1c532afface7fdb4f

# Description
See title. In this situation, a slime was applied a camera bug directly preventing it from ventcrawling. Does it stop people if they got a contortionist suit or if someone is carrying a bugged item? Further testing required.
# Steps to Reproduce
Apply vent bug to slime directly
Have it ventcrawl
It somehow can't crawl through the vent
# What you Expected
Slime to ventcrawl and let me stalk it on cams
# What Actually Happened
Slime somehow couldn't squeeze in with the added width of a camera bug.

**Comment by ExpulsionSnooper** [comment]
I'll fix this in a minute, it only requires 1 added line.
