### ISSUE TITLE
A few more parts of botany needs fixing

### ISSUE THREAD

**Issue by Killette3** [d3athrow/vgstation13#32714]
Grew some nova flowers because there was a blob
Plant had it's own custom plant stats, harvest was always the default nova flower with not the right stats
Yesterday could not turn a tower cap log back into seeds. I think something is fucky with the non edible plant stuff still

**Comment by adacovsk** [comment]
@hinaichigo is this related to luck PR?

**Comment by Killette3** [comment]
Nettles do not have acid when scanned, seem to be unable to act as a container. When you grind them you get nothing, same harvesting issue as the nova flowers. Also could not seed extract nettles or nova flowers.
