### ISSUE TITLE
Viral Horse Masks are unremovable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32732]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
7773219fd29cc5bf9f751429195d79803e43008e

# Description
Get a horse mask through viral symptoms, splash acid on yourself and take damage, the mask stays behind
# Steps to Reproduce
get a horse mask through viral symptoms
# What you Expected
to splash acid on my mask and get it off 
# What Actually Happened
I melted my face through the mask I had on

**Comment by Kharkov72** [comment]
you need to splash it on the actual mask itself, not your face, this was probably broken by some retard but you can still get rid of them

**Comment by RedrobotAnnie** [comment]
I completely forgot to include that, my fault

**Comment by Kurfursten** [comment]
I believe this is from @Kane-f 's target reagent PR from April 30 #32424

What I am seeing is that it does successfully complete the splash and damage with no runtime, including the "you splash the solution onto target's mouth" message, but it seems that the sacid reaction_mob is for whatever reason not noticing that masks should cover the face
