### ISSUE TITLE
Superfart: Sound File

### ISSUE THREAD

**Issue by Fox-McCloud** [d3athrow/vgstation13#3273]
Dunno if this is intentional or not, but the genetic power superfart has a sound when it's utilized; this sound is in the sound files, but commented out in the code. Intentional?

**Comment by SkowronX** [comment]
Arse nath?

**Comment by Konater** [comment]
*fart

**Comment by wwjnc** [comment]
Pfft.

**Comment by PJB3005** [comment]
This can be closed, it isn't commented out anymore.
