### ISSUE TITLE
mommi MMI nullspaced on death

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32735]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
7773219fd29cc5bf9f751429195d79803e43008e

# Description

# Steps to Reproduce
be crab
do crab stuff
get killed

# What you Expected
ded, MMI drops on floor
# What Actually Happened
your MMI is now a phantom, it's not under the floor tile, disposals tube or in the alt click menu
can still talk normally and taunt my murderer, until he rigs a welderbomb on top of my tile, at which point i ded for real

**Comment by Eneocho** [comment]
This happened to me multiple times on roundstart MoMMIs but not on midround MoMMIs, probably an issue with MMI crabs?

**Comment by pedr69** [comment]
i'll add that i was a midround mommi(made from a roundstart borg)

**Comment by Eneocho** [comment]
I vaguely remember having smashed a MMI crab I had made midround (started attacking me) and the brain went invisible.

**Comment by pedr69** [comment]
it may be that constructed mommis get nullspaced on death
roundstart spawns don't

this round i got killed once, recrabbed and killed again which is when i got nullspaced
