### ISSUE TITLE
Feature Request: Food Replicator

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#32731]
This is the official design document for the food replicator and the second of my code bounties.

As this is just a concept, please vote on this PR.
If im not the only person amused by this, I will be putting another bounty on this content.

### What it is
A machine (with stock parts providing different effects/improving quality) that you can use to scan/destructively eat-lyze to copy it to the internal database.
Using an internal resource buffer (energy stored SMES style?/biomass or raw nutriment added by beaker?) the machine can attempt to re-create it, giving the chef mass catering/a more laid back cooking experience while still being able to provide a large menu.
Balance provided by sorting food into tiers based on required stock parts, or resource cost.
As with microwaves, a chance to fail printing and make a mess which would require cleaning. 
There could also be a diminishing chance, based on stock part quality, for a replication to consume/corrupt a saved meal, requiring the chef to cook and rescan another one.

- Either one machine or two (separate scanner/ gastronomic eatlyzer and replicator)
- Basic stock parts > can only print soy products (pre-saved, a large Rimworld paste dispenser)
- T4 parts > any food inc. poutine ocean components, borg burgers, etc
- Chance to gunk and req. cleaning

### Steps to produce (TBA)

- [ ] Github emote vote

- [ ] Code
- [ ] Interfaces
- [ ] Sprites (recolor destructive analyzer, recolor microwaves heh)
- [ ] Give food tiers/resource costs

[controversial]
[discussion]
[featurerequest]
[help]
[needspritework]
[qol]
[sanity]

**Comment by Blithering** [comment]
The spessmart sample bots might help, since they can already dispense food via verbal commands

**Comment by adacovsk** [comment]
Don't we already have enough kitchen appliances that are unused? Maybe rework the old ones into something new

**Comment by Eneocho** [comment]
Only if there's a 5-10% chance to give the guy a "this tastes like replicated food" message.

**Comment by kernikov** [comment]
> Don't we already have enough kitchen appliances that are unused? Maybe rework the old ones into something new

This isn't intended to be stuffed into the existing kitchens, but as a to-be-introduced machine build able by science with appropriate research, as a step in linking the kitchen and R&D beyond fast microwaves

**Comment by jwhitak** [comment]
Alternative options could involve assigning a credit cost to each in addition to the tiers, and require payment... 

If you wanted to go all out, you could just turn it into some form of fast food vending machine. It takes a skilled chef to give the computer the 'meals' to make, and it requires certain tiers of parts for certain meals. Could do a formal writeup of what each food should be at. Chef can then either set it to be free dispense or pay-for-meal. It could be able to dispense based on internal energy like a dispenser.

Ideas guy here.

**Comment by Hinaichigo** [comment]
Kind of powercreep for the chef and makes obtaining rare ingredients (the main challenge of the chef) less significant. By making rare ingredients essentially interchangeable with nutriment, etc., this would flatten the dynamics of the chef's round. What you listed as a positive:

> giving the chef mass catering/a more laid back cooking experience while still being able to provide a large menu.

Seems kind of like a negative to me. For example instead of having to scale up the aquaculture farm to make a lot of sushi, you'd just need to get one fish for each type, make one piece of sushi, then scan it in the replicator to make essentially as much as you wanted.

If you really want a lot of easy to make food as the chef the options are already there. Fries, burgers, etc.

**Comment by Eneocho** [comment]
Clearly the solution is for replicator food to have a negative side effect so people still prefer the non replicated food but can consume the replicator one in a hurry. 
There could be a Dan's Sauce style chem force added to all replicator meals that causes some damage, makes you vomit, blinds you temporarily, etc if you eat a lot of replicated food at once.

**Comment by ManopolisJones** [comment]
I dunno, don't really like the idea of a 'food replicator' and would rather see something along the lines of a Rimworld nutrient paste dispenser that could mass produce paste when filling it with plant bags of produce.

**Comment by Eneocho** [comment]
> I dunno, don't really like the idea of a 'food replicator' and would rather see something along the lines of a Rimworld nutrient paste dispenser that could mass produce paste when filling it with plant bags of produce.

There's not really a point to that when the produce is far more nutritious than needed with even mediocre botanywork, or when you can make cheese wheels that have more than enough nutritment.

**Comment by Eneocho** [comment]
I kinda liked the idea of being able to replicate food but filled with discount dan's special sauce.
