### ISSUE TITLE
Warden and Detective do not open Assistant Slots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32749]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
cc75c1d055c54a6ff2b29c9b422c45040b7dcb69

# Description
Security roles Detective and Warden do not open new assistant slots while filled. 

# What you Expected
to play assistant
# What Actually Happened
there are 2 security members and yet only 2 assistants allowed max

**Comment by Servalfang** [comment]
good

**Comment by Eneocho** [comment]
>good

secbrain hands typed this post
