### ISSUE TITLE
Pen&paper writing formatting tags don't close, eat the rest of the line instead.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3275]
To reproduce: Copypaste the following into a piece of paper in-game.

[small]This text is small.[/small] 
This text is also small, even though we just closed the tag.
[b]This text is bold AND small.[/b] This text doesn't even show on the paper because the tag eats it.
[center]This text is centered.[/center]
Now the rest of the paper will be centered since there's no [left] tag, good job idiot.

**Comment by frangi** [comment]
Can confirm, just tried, doesn't work.

**Comment by NigglyWiggly** [comment]
This has been around for quite a while now, I sort of assumed I was just doing it wrong

**Comment by ririchiyo** [comment]
This should probably not be an issue anymore.

**Comment by 9600bauds** [comment]
It is still an issue, actually.

**Comment by clusterfack** [comment]
Well I mean technically riri did fix it by adding markup but then we switched back to regular so yeah
