### ISSUE TITLE
Invisible Sprayed Simplemobs Cannot Be Revealed

### ISSUE THREAD

**Issue by Armadingus** [d3athrow/vgstation13#32764]
#### Description of issue
I had the unfortunate circumstance of being antagonized by an invisible great white goliath on deadpop. One message to the syndicate mime: I lived bitch.
So, normally you can spray humans and objects with water from an extinguisher or some other way of splashing water, but simplemobs ignore this completely. This makes it very difficult to counteract being murdered without having a certain attack animation setting enabled and a trap/projectile weapon, you can't hit the thing in melee, you can't even see if there's a corpse when you've killed the thing.
Figure 1: spraying an invisible human and Ian the corgi with an extinguisher, the result speaks for itself.
![image](https://user-images.githubusercontent.com/55976761/172609956-0f2a4a2d-9a7d-46cf-8887-1ca2529591b2.png)

#### Difference between expected and actual behavior
I expect to be able to wash away the invisible paintjob with water but it appears that is not the case. The simplemob is unaffected by any splashing.

#### Steps to reproduce

1. Spawn "/obj/item/weapon/invisible_spray/permanent
2. Apply spray to any simplemob
3. Spawn "/obj/item/weapon/extinguisher
4. Spray extinguisher in general direction of where the simplemob is
5. 🤔

#### Server revision

b5df4461aaf6e3b42f6693efc6944ccde16084a5

**Comment by adacovsk** [comment]
I'll fix it, I think this was a previous issue before made changes
