### ISSUE TITLE
Ghosts can bully xenoarchs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32770]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
f09e2ee4925457339d9196fd826de7cf3203d23c

# Description
Ghosts can halt anomaly scanner scanning process (and launch it)
# Steps to Reproduce
be ghost, click anomaly scanner
# What you Expected
nothing
# What Actually Happened
I made a scientist believe his machines were only scanning when he wasn't looking. Quotes from xenoarch: "I hate living", "I'm gonna scream"

**Comment by Eneocho** [comment]
What the fuck based, unholy based.

**Comment by luigil101** [comment]
working as intended
