### ISSUE TITLE
moar pulse demon issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32788]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
having the camera you are in(while in an APC) destroyed, you straight up get deleted

**Comment by ghost** [comment]
feature

**Comment by pedr69** [comment]
the loud electrical sound you hear from the malf explode ability doesn't actually happen until after the thing explodes

**Comment by pedr69** [comment]
this can be closed @Kurfursten
