### ISSUE TITLE
Slimepeople are hard, if not impossible to revive

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32786]
(WEB REPORT BY: volttekka REMOTE: 206.221.180.138:7777)
# Revision
84ac0b5be48debe90c59c634a564d0c074343858

# Description
Cloner scanner cannot scan slime puddles
# Steps to Reproduce
Kill a slimeperson, drag them to genetics
# What you Expected
slimeperson is scanned and able to be cloned
# What Actually Happened
cloner console spits out an error message

**Comment by DrSnips** [comment]
Likely a literal brainlet issue

**Comment by Servalfang** [comment]
skill issue in life

**Comment by Hinaichigo** [comment]
What was the error message?
