### ISSUE TITLE
Handheld scythes dont aoe clear kudzu.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#32789]
#### Description of issue
Scythes used to clear in a 3x3 tile of whatever tile you clicked, now they're no different than a pair of wirecutters

#### Difference between expected and actual behavior
Expected Kudzu removal tool be remove kudzu,
Got oversized wirecutters

#### Steps to reproduce
Spawn kudzu, click tiles near kudzu hoping to clear them and see nothing happen.

**Comment by pedr69** [comment]
you are attacking the floor right?

**Comment by Dacendeth** [comment]
Yeah

**Comment by adacovsk** [comment]
```/obj/item/weapon/scythe/afterattack(atom/A, mob/user as mob, proximity)
	if(!proximity)
		return
	if(istype(A, /obj/effect/plantsegment) || istype(A, /turf/simulated/floor) || istype(A, /obj/effect/biomass) || istype(A, /obj/structure/cable/powercreeper))
		for(var/obj/effect/plantsegment/B in range(user,1))
			B.take_damage(src)
		for(var/obj/effect/biomass/BM in range(user,1))
			BM.adjust_health(rand(15,45))
		for(var/obj/structure/cable/powercreeper/C in range(user,1))
			C.die()
		user.delayNextAttack(10)

**Comment by adacovsk** [comment]
seems like it should work, I'll look into it

**Comment by adacovsk** [comment]
`/obj/proc/take_damage(incoming_damage, damage_type = BRUTE, skip_break = FALSE, mute = TRUE)
	var/thisdmg = (incoming_damage > max(damage_armor, damage_resist)) * (incoming_damage - damage_resist) //damage is 0 if the incoming damage is less than either damage_armor or damage_resist, to prevent negative damage by weak attacks`

Exception has occurred: type mismatch: cannot compare the scythe (/obj/item/weapon/scythe) to 0

**Comment by adacovsk** [comment]
@Hinaichigo
