### ISSUE TITLE
the PDA terminal on Waystation has no available downloads

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32804]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
b8c8106f269381203b8c349207c48c0e27227ede

# Description
Wanted to buy a flashlight upgrade, but didn't have the option to buy anything. Tried it with and without my ID in the PDA
# Steps to Reproduce
Put PDA in PDA Terminal to buy some programs
# What you Expected
To be able to buy programs
# What Actually Happened
No programs!!!

**Comment by nervere** [comment]
I can't replicate this and I also don't see any PDA-related runtimes for the day this happened so I'm gonna close.
