### ISSUE TITLE
NT football suits are invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32817]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
af65ffff0f474035b17e1e6b094929cd5de532d4

# Description
no sprite when they're on the floor
# Steps to Reproduce
get one from a suit vendor
# What you Expected
a sprite
# What Actually Happened
no sprite!!!

**Comment by DrSnips** [comment]
100% tested moment

**Comment by Eneocho** [comment]
Issue is that the uniform is calling for an icon in suits.dmi while the uniform was added to uniforms.dmi, so no icon is found. This issue does not happen to the helmets, but the syndie helmet is broken too.
