### ISSUE TITLE
Mirrors ruin muh immersion

### ISSUE THREAD

**Issue by jewishneocon** [d3athrow/vgstation13#3282]
right now you can be bald and magically grow a pink afro by using a magic mirror in bathroom 

i dont really think its that well known but if possible itd be cool to have a barbers razor in maint to cut hair kinda like goone

**Comment by TermedClepe** [comment]
Nanomachine mirrors.

Or just change the examine description to include "has an assortment of barber tools including hair growth gel" etc.

Removing the mirror functionality and making it hidden / less accessible is fun removal.

**Comment by ConkerDev** [comment]
Fixed. Can be closed

**Comment by PJB3005** [comment]
Er, that PR wasn't ever merged though...
