### ISSUE TITLE
Black Tajaran Skin Gene

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32826]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
88e7105dd43b50a7fff33632524ff738c5e3ee2a

# Description
It seems black tajarans are unavailable to be made through genetic fuckery. Despite this, the black tajaran ears are available as a hairstyle choice
# Steps to Reproduce
Try to change the skin color of a catbeast with genetics.
# What you Expected
Confusion with fake black catbeasts
# What Actually Happened
Stuck with vanilla flavoring

**Comment by Kurfursten** [comment]
It's a design choice, black ones are the ones that generate threat
