### ISSUE TITLE
Cuffing one handed players

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#3283]
It is currently impossible to cuff a one handed player without a straightjacket, people are realizing this and purposefully removing their hands at character creation.

It would be nice if cuffing a one handed player resulted in cuffing his hand to his leg, forcing him to crawl and otherwise behave as if cuffed normally.

**Comment by Probe1** [comment]
beat them with a stun stick like the rest of us.   you can attach cuffs to shoes to keep them from running.
