### ISSUE TITLE
Synergy Execution Room Vent Access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32847]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
88e7105dd43b50a7fff33632524ff738c5e3ee2a

# Description
Synergy execution room vent button requires HOS access instead of security officer which implies a lot more micromanaging then seems necessary

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
Considering execution is a Warden/HoS/Captain level punishment, it makes sense regular redshirts don't have access to said button.

**Comment by west3436** [comment]
> Considering execution is a Warden/HoS/Captain level punishment, it makes sense regular redshirts don't have access to said button.

Regular redshirts have access to everything related to execution on Box, I don't see why we need to have an inconsistency here. They can get into the execution room and chamber on Synergy, they just can't vent the chamber after the deed is done.

**Comment by nervere** [comment]
I'm gonna close this one as a non-issue since Synergy is the only map that has a fiery incinerator for an execution chamber instead of just something you can pump N2O into. It's a design choice and probably a smart one given the setup.
