### ISSUE TITLE
Telekinesis free gun teleportation

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3284]
Step one: Get telekinesis
Step two: See a gun and a recharger or a gun in a recharger. Skip step three if the ladder
Step three: Put gun in recharger
Step four: click recharger
Step five: Suddenly gun in your hand and not outside the recharger
You now know how to get guns through windows or even walls. Works better with xray

**Comment by Ephx1** [comment]
I'm pretty sure this is general to everything that has another thing in it when dealing with telekinesis. Eject ID from an HoP console yields an ID card in your hand, much like the gun issue.

**Comment by ComicIronic** [comment]
Lazycode.
