### ISSUE TITLE
Derelict & Abandoned Ship mass drivers don't work

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3285]
As far as I can tell, only mass drivers in the main station will actually fire. Any combination of inputs on the other two will not produce any result. The outer doors will open, but the driver itself will never fire.

**Comment by wwjnc** [comment]
I think the Derelict one is intended behaviour. We could make them fixable, though.

**Comment by 9600bauds** [comment]
That'd be just grand, nothing hurts my soul so like not being able to mass driver junk.

**Comment by AutismSpider** [comment]
Pointless for the Derelict one. 

Derelict mommis are hard-code like the nuke disk they get push back on that Z level.

**Comment by wwjnc** [comment]
MoMMIs aren't the only playable thing on the game, you know.

**Comment by 9600bauds** [comment]
Come think of it, there's also a mass driver on the Research Outpost, but I don't know if that one works since I never go there.

**Comment by AutismSpider** [comment]
outpost one works

**Comment by clusterfack** [comment]
I think deity fulfilled all this
