### ISSUE TITLE
Pulse Demons STILL can get stuck in cameras

### ISSUE THREAD

**Issue by west3436** [d3athrow/vgstation13#32859]
#### Description of issue
Pulse demons can get stuck in a camera by bouncing to one which does not have the source camera/APC in its field of view. See below.
![image](https://user-images.githubusercontent.com/66280799/176508896-204876bd-ac47-45d8-93cf-86337344eea3.png)

#### Difference between expected and actual behavior
cancel-camera-view or a verb to return to your APC need to be created to prevent this.

#### Steps to reproduce
1. Get in APC
2. Click a camera in view
3. Click another camera which doesn't have any other cameras in its field of view
4. Get stuck permanently

#### Server revision

[bugfix]

**Comment by pedr69** [comment]
fixed by #32809
happened to me too, bro

**Comment by west3436** [comment]
> fixed by #32809 happened to me too, bro

In what way does that fix it? It just happened to me.

**Comment by pedr69** [comment]
because the PR isn't merged yet :)

**Comment by west3436** [comment]
closed via #32809
