### ISSUE TITLE
pocketed items dissapearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32867]
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
0ca11f4e464c48ca81fd7ad29d53cd784bdbd043

# Description
when taking your clothes off in a space pod the items in your pockets and PDA slot are destroyed
# Steps to Reproduce
get into a space pod and take your clothes off
# What you Expected
to be naked
# What Actually Happened
I was naked and had no ID

**Comment by Kurfursten** [comment]
You can crowbar them out with the hatch open
