### ISSUE TITLE
Holyjuke Single Mode does not keep the same song

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32868]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
cf5883bc634318dffd4d0729179e7b48b633842f

# Description
>play unga song on holy juke
>set to single so it keep play
>it switches to other song after one loop finishes!!!

UNGAwaw

**Comment by jwhitak** [comment]
Found it.

```
if(!current_song || (song && world.time >= media_start_time + song.length - fadeout_time))
	current_song=1
```
Then later...
```
if(JUKEMODE_REPEAT_SONG)
	current_song=current_song
```
