### ISSUE TITLE
[Feature Request] Bioreactor

### ISSUE THREAD

**Issue by wiredhuman** [d3athrow/vgstation13#3287]
Role: Power generator

Fuel: its people

Cryo-like cells with bodies in them. Could be braindead players, mobs, antags.
The less integrity in the body without being dead - the more power generated. The idea is to maintain the subject in crit through medication without it dying. Cultists, lings, some slimes etc generate more energy.
Subjects could be soylent-greened for further procession on demand.

The purpose: 
1. Unnessesary cruelty.
2. Braindead disposal, with the ability to revive if not braindead anymore
3. A fate worse than death for greyshitters
4. Constant source of biomass
5. Possibility to generate power with blown/eaten/non-existing engineering.
6. Giving antags a slight chance of survival instead of being LOLHUSKED

The Drawbacks:
Needs non-Asimov AI
Needs living bodies

**Comment by CptWad** [comment]
>5. Possibility to generate power with blown/eaten/non-existing engineering.


Oh no no no. It should have some crazy drawback
Idea: When someone is dead inside their for too long they get converted into CHUD mobs that are super robust and break through walls and shit. see https://www.youtube.com/watch?v=OR-ddHPcqYo for what a chud is
Also a shitty movie watch it if you want to get mad

**Comment by wiredhuman** [comment]
inhabitants get zambied if emagged or some shit like that
