### ISSUE TITLE
Being gibbed destroys the eyes in your head

### ISSUE THREAD

**Issue by adacovsk** [d3athrow/vgstation13#32875]
#### Description of issue
Being gibbed destroys the eyes in your head

#### Difference between expected and actual behavior
Expected eyes to remain in the head

#### Steps to reproduce
1. Get gibbed
2. Reattach head
3. No eyes

#### Length of time in which bug has been known to occur
Couple months?

**Comment by Eneocho** [comment]
It's been an issue for at least a year.
