### ISSUE TITLE
Green Pipeline is a trap on Lowfat Bagel

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32880]
(WEB REPORT BY: valkyrieskies REMOTE: 206.221.180.138:7777)
# Revision
f2df14bc85868cd6686794d47bae11a99fa69faa

# Description
Ventcrawl through the green pipeline in lowfat bagel and you'll get trapped once you hit the heater-connector part of the line.

**Comment by nervere** [comment]
I tested this and it doesn't seem like whatever issue there was has been resolved.
