### ISSUE TITLE
You can't SoC a pulse demon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32891]
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
a4eb3c94fdde52c95aee3d8cfd3a258d150bd821

# Description
You can't BTFO an annoying ass pulse demon by turning it into a person
# Steps to Reproduce
>Be wizard
>Pick gunk staff
>go gunking
>change borg
>change AI
>change random mobs
>Pulse demon immune
>shocks you to death when you hit him with the SOC
# What you Expected
>magic supremacy
>BTFO'ed pulse demon
# What Actually Happened
>Btfo wizard
>demon supremacy

**Comment by pedr69** [comment]
demons can only die to loss of power, EMP's and simple mobs

**Comment by Kurfursten** [comment]
This is intended, from the latest change. They are no longer be hit by thrown projectiles.

**Comment by Eneocho** [comment]
I'd make it an exception so they CAN get hit by the _magical_ bolt.
