### ISSUE TITLE
Boxstation Derelict DJ Sat Radio Transmitter Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32908]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
b6830325574dd89a4c2f60a5086c8c57c4033e77

# Description
DJ Sat Radio Transmitter does not have a cable knot under it and even if placed, will immediately turn off.

**Comment by pedr69** [comment]
the radio transmitter wire connection is kinda wonky
when messing them and not wiring them right i recall
>making rads but not music
>making music but no rads
>making rads and music
>shutting off as you've reported here

i don't understand why they need a wireknot anyway, is high power machinery supposed to be directwired? why does the 10MW starscreen draw from the APC then?
