### ISSUE TITLE
Groin Surgery is Fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32901]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
a4eb3c94fdde52c95aee3d8cfd3a258d150bd821

# Description
No matter what I tried, I could not prep a groin for reattachment(butt?). This left me unable to continue and attach new legs.
# Steps to Reproduce
Have someone lose their groin.
Do every possible order of surgery tool to no success.
# What you Expected
Attach a new groin(butt)
# What Actually Happened
Poor man without a groin.

**Comment by Eneocho** [comment]
Did it say he was missing a groin on examine/health analyze? There's no surgery to reattach a missing groin as far as I know (there is one for reattaching asses), and it's not really common to find someone survive something that would separate the groin.

**Comment by luigil101** [comment]
iirc missing groin is irrecoverable and you need to kill and clone
