### ISSUE TITLE
[Feature Request]More genetic power sorta/emulating equipment/machinery

### ISSUE THREAD

**Issue by wiredhuman** [d3athrow/vgstation13#3291]
The idea: piece of non-biological equipment emulates a power when equipped/mounted

The purpose:
Purely technological measures to induce power-like effects without dirty needles
Allowing selective, on demand usage of powers
Not 100% identical with actual powers its supposed to emulate, for example no robustness buff with hulk-like strengh

Possible examples:
Bioimplants
Clothing
Sleeper-like contraptions

Some of the powers have mechanical sorta-equivalents, like remote view has advances camera controls,
More shit like refraction/invisibility cloaks and power enhancing exoskeletons etc would be pretty swell.

**Comment by CptWad** [comment]
![xrayspecs](https://cloud.githubusercontent.com/assets/3959840/6455066/54af893a-c104-11e4-9b37-af60abb06879.jpg)
I can see it now
Xray specs
Give xray
But you only see people as naked skeletons.
Cant identify them or see what they are wearing.
Just skeleton people

**Comment by gbasood** [comment]
DEUS
EX
