### ISSUE TITLE
Instruments stop mid-song for weird reason

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32917]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
03c4248195374c74b2b8d3a37b55422882dfa0f0

# Description
if there's a blank (denoted by a comma) at the end of a line, the instrument just stops there instead of continuing to play
# Steps to Reproduce
Play a song, add a comma to the end of one of the lines
# What you Expected
the song would play
# What Actually Happened
it stops at the end of the line that contained the space

**Comment by Eneocho** [comment]
They tend to stop if there's a comma and an empty line. Perhaps you copypasted the song wrong?
