### ISSUE TITLE
Security Borg mapping on waystation is busted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32913]
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
b6830325574dd89a4c2f60a5086c8c57c4033e77

# Description
I tried robot army and they won't walk
# Steps to Reproduce
>Make EDs
>Make BEepskys
>Make Cheapskie
>they won't patrol on patrol mode
>Be on waystation
# What you Expected
>RISE MY CHILDREN RIIIIIISE
# What Actually Happened
>Absolutely nothing

**Comment by nervere** [comment]
I know for a fact that ED's are broken. The rest may be due to a lack of robot waypoints mapped into the station.
