### ISSUE TITLE
Can't *suicide with a lit welding tool

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32912]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
b6830325574dd89a4c2f60a5086c8c57c4033e77

# Description
Suicide with a lit welding tool didn't kill me
# Steps to Reproduce
*suicide with a lit welding tool
# What you Expected
to die
# What Actually Happened
severely maimed but alive

**Comment by Eneocho** [comment]
Same can happen if you suicide with a bottom tier powercell.
In both cases the suicideflag gets set but you live, which means you get a constant O2 damage tick and can't be revived in any way after death (though you can still be cloned if you got scanned before fake-suiciding).
