### ISSUE TITLE
spirit breaker toxin not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32920]
(WEB REPORT BY: ribeira REMOTE: 206.221.180.138:7777)
# Revision
169f18f49865b0efdfc15eeda1dc310b8e34f4db

# Description
Spirit breaker toxin does not seem to be working, smoked ambrosia cruciatus, did nothing, extracted a pill with the purified substance and took it and it did nothing, after ahelping it twice and confirming it should have kicked in by now, I was instructed to bugreport.
# Steps to Reproduce
Adminbus a traitor role, use your TCs to get ambrosia cruciatus packets from the service category, plant it, make a blunt with it and smoke it or extract the pure substance and take the pill.
# What you Expected
To trip fucking balls
# What Actually Happened
I was sober

**Comment by Killette3** [comment]
I had a feeling about this but wasn't sure for certain, never bug tested on myself extensively but I assumed you waited over 10 minutes?

**Comment by pedr69** [comment]
spiritbreaker needs to be in your system 165 ticks(~5 minutes) to take effect
you'll need a dose larger than 8.25u which might require multiple leaves/blunts

**Comment by nervere** [comment]
@pedr69's explanation is correct, it works fine. I just tested it to make sure.
