### ISSUE TITLE
Add a unique beep for centcomm messages to let admins know someones contacting centcomm

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3292]
Kinda fucks over IAA as a whole doesn't it?  Admins have to be reading the logs carefully, or else players are pissing into the wind.  This has been brought up tons of times in the thread and it's high time someone takes the 30 seconds to copy the bwoink code and fits it into the centcomm message code.

**Comment by IratePirate** [comment]
You should do the same with prayers.

**Comment by Kurfursten** [comment]
Filled by https://github.com/d3athrow/vgstation13/pull/3335

**Comment by Probe1** [comment]
Like the man says.
