### ISSUE TITLE
Mothership Lab Z12 is a Fax Destination

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32936]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
70591c188f8d54a325d7bd7662bb8ee5665d3406

# Description
Some sort of Mothership lab vault must have a fax machine on it, as you can send faxes to it
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by SacredAtom** [comment]
feature

**Comment by Eneocho** [comment]
Feature for those "send this message to the mothership" faxes.

**Comment by Optimism333** [comment]
Working as intended. The fax destination should hopefully show up as "???".

**Comment by nervere** [comment]
Author of the map says it's intended. Seems he even went so far as assigning "Mothership Lab Z12" as the fax machine's department. I can only see good interactions coming from someone sending a fax to aliens.

**Comment by wotisjanitor** [comment]
> Author of the map says it's intended. Seems he even went so far as assigning "Mothership Lab Z12" as the fax machine's department. I can only see good interactions coming from someone sending a fax to aliens.

THANKS!!
