### ISSUE TITLE
Spawning Mr Clean causes same shit as nar sie

### ISSUE THREAD

**Issue by jewishneocon** [d3athrow/vgstation13#3294]
what mr clean is supposted to do according to pomf: be a nar sie that cleans everything it touches 
what it does right now: be narsie jebediahsmith ruined a round not knowing this

how to replicate: spawn mr clean

**Comment by 9600bauds** [comment]
change his name to Mr. Cleanse, problem solved

**Comment by AutismSpider** [comment]
If its going be Mr. Cleanse it meeds new face.
![face of hope](https://cloud.githubusercontent.com/assets/10268342/6458542/313ba588-c14a-11e4-830c-b43f3463ca42.jpg)

**Comment by clusterfack** [comment]
picnic

**Comment by wild-billy** [comment]
If it's a child of nar-sie, should be moved up to child of singulo.
