### ISSUE TITLE
Grue light overlays become a violently bright red

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#32940]
This probably happens when too many light sources intersect or maybe it's a problem with the red from flares being accentuated by their vision in some circumstances, causing a light that can barely be seen through.

**Comment by nervere** [comment]
I've noticed this happening for any sort of red lights, be it red light tiles or flares.

**Comment by west3436** [comment]
@boy2mantwicethefam's solution was rejected and not merged. Since he reported this issue, this will be closed as not implemented
