### ISSUE TITLE
Biomass traitor packet does nothing

### ISSUE THREAD

**Issue by Killette3** [d3athrow/vgstation13#32958]
What it says on the tin. Bought 2 of them and got the vibrating weirdly message after use, then the packet disappears and nothing happens

**Comment by Eneocho** [comment]
Weird. I tested them extensively on localhost when making them and they worked fine.

**Comment by Eneocho** [comment]
It doesn't work on the current test. Weirder still.

**Comment by Eneocho** [comment]
Found the issue. I added the packet_override var to the global spawn item, but biomass doesn't have a packet override, so it runtimed and deleted.
