### ISSUE TITLE
Test serb's health scanner occasionally scans "the floor"

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#3296]
I can't seem to reproduce the results! It happened when I was modifying the genes of a humanized monkey and tried to scan it to see the damage.

**Comment by DrLeprikon** [comment]
It works fine now even though I don't think there's been a merge in the last thirty minutes!

**Comment by Konater** [comment]
Clumsy gene makes you do it, were you a clown?

**Comment by DrLeprikon** [comment]
I was not, but I did mess with my genes a fair bit. That must've been it, sorry I panicked. Shall I close the issue?

**Comment by Konater** [comment]
Sure why not

**Comment by DrLeprikon** [comment]
I'm closing it then!

**Comment by DrLeprikon** [comment]
How do I close it..?

**Comment by DrLeprikon** [comment]
Wait, found it!
