### ISSUE TITLE
Vampires hearing deadchat is a bad feature

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32971]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
821b34fc36cd569c7994eff8f27028478be93c1e

# Description
why is this a thing
you can't even tell the difference between dchat and normal chat
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by luigil101** [comment]
feature

**Comment by Eneocho** [comment]
Make vamp-deadchat purple so you have a clear indication it's an otherworldly sound and it's perfect.

**Comment by west3436** [comment]
Removed via #34679
