### ISSUE TITLE
Protolathes sometimes hang while ingesting materials

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#32990]
(WEB REPORT BY: iestere REMOTE: 206.221.180.138:7777)
# Revision
f839452895187cdf64c2996df53002bbcb35f050

# Steps to Reproduce
Alt-click a protolathe with a stack of plasteel

# What you Expected
The plasteel to be accepted or rejected

# What Actually Happened
> The Protolathe is busy. Please wait for completion of previous operation.

Forever

**Comment by pedr69** [comment]
yeah you cant put plasteel into protolathes

**Comment by WindowsErrors** [comment]
it's sort of like how the spade in the autolathe requires wood but you can only put metal and glass in an autolathe

**Comment by nervere** [comment]
It shouldn't give this message but prolathes don't take plasteel or use it for anything.

**Comment by ebakai** [comment]
> you cant put plasteel into protolathes

>  prolathes don't take plasteel

You _can_ add plasteel to a protolathe if you alt-click, which results in:
> **Runtime in rdmachines.dm, line 206: Cannot read 0.cc_per_sheet**
> proc name: AltClick (/obj/machinery/r_n_d/AltClick)

And since the protolathe's busy var doesn't get reset, it becomes completely unusable.

**Comment by jwhitak** [comment]
Tested, this actually has been fixed since it no longer runtimes
