### ISSUE TITLE
[Metaclub] minor mapping issue in EVA

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3300]
![ss 2015-03-03 at 05 27 04](https://cloud.githubusercontent.com/assets/8550416/6477916/f9623246-c1f6-11e4-965b-b1c4280bff0f.png)

The table the radios are resting on should be an rtable for consistency purposes.  really serious stuff here.

**Comment by 9600bauds** [comment]
LITERALLY
UNPLAYABLE

**Comment by Probe1** [comment]
I just don't know how I can continue living in a world like this.

**Comment by Probe1** [comment]
finally I can sleep at night without living in fear of a world with mismatched tables.
