### ISSUE TITLE
Error in construction of a borer chamber in Synergy Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33008]
(WEB REPORT BY: memdic REMOTE: 206.221.180.138:7777)
# Revision
82af9cd6b8845a16cc88cbb0304f9d1bec4081bd

# Description
The plasma tank fails to pump plasma into the borer chamber at it's starting position, so unless the scientist knows about the problem even if he throws the egg into the chamber, it will not hatch. 
# Steps to Reproduce
Load into Synergy station
# What you Expected
To have plasma in the chamber
# What Actually Happened
I see a plasma tank connected to the wrong tube. And the unability to spawn as a borer, even though the egg was thrown into the chamber.

**Comment by pedr69** [comment]
>throw egg into room without plasma
>expect it to hatch

what?
just wrench the tank nigga
a couple other maps don't have roundstart functional borer chambers either so this might be intentional

**Comment by Eneocho** [comment]
On the topic of borer chambers why the FUCK is that one chamber in I think defficiency so fucking big.

**Comment by pedr69** [comment]
in case the scientist decides to rob the vault fridge and buy 70 borer eggs from cargo?

**Comment by Eneocho** [comment]
You only need 1 tile to have plasma to grow all the eggs you want simultaneously. It's how ghetto borerfarming is done.

**Comment by nervere** [comment]
> > throw egg into room without plasma
> > expect it to hatch
> 
> what? just wrench the tank nigga a couple other maps don't have roundstart functional borer chambers either so this might be intentional

I took a look, the issue is that the plasma tank is on the "drain the plasma" pipe loop instead of the one that injects it into the chamber. It's a pretty easy fix.
