### ISSUE TITLE
synergy telecomms shitmapping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33009]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
82af9cd6b8845a16cc88cbb0304f9d1bec4081bd

missing a HE junction, the coldroom and the freezer aren't connected 
it's got a straight pipe adjacent to a HE pipe without a junction

there's a way to make them connect without a junction(#32019) but apparently the mapper couldn't do that right either

**Comment by pedr69** [comment]
this will cause the comms to overheat 2 hours into the round, and trying to fix it will release the plasma from the tube
[synergy]

**Comment by Eneocho** [comment]
mappers: not even once

**Comment by pedr69** [comment]
oh wow synergy doesn't even have a tag
[general]

**Comment by Eneocho** [comment]
The bot's really outdated since pjb hasn't been here for a good while (and even then it didn't get updated). But we do have a manual tag for Synergy (that a collab has to set up for you), you can use "Mapping (Synergy ☯️)" to look for it or press on the labels button and write synergy.
