### ISSUE TITLE
UN Helmets don't fucking work

### ISSUE THREAD

**Issue by ValkyrieSkies** [d3athrow/vgstation13#33022]
The helmets introduced in #32742 as /obj/item/clothing/head/helmet/tactical/antichrist display without a sprite when spawned.

![image](https://user-images.githubusercontent.com/19687076/183329167-13d9fe47-ca7c-4e6d-969d-e2365f4fc4cb.png)

**Comment by KingofHONK** [comment]
antichrist magic at work.....

**Comment by Eneocho** [comment]
Seems there's no antichrist icon at all. There is one for the worn sprite, but I saw none for the itemsprite.

**Comment by pedr69** [comment]
wtf they used to work

**Comment by Eneocho** [comment]
@nervere or @ValkyrieSkies close this one, I forgot to relink the issue when remaking the broken bugfix PR.

**Comment by Exxion** [comment]
nah

**Comment by Eneocho** [comment]
That works too I guess.
