### ISSUE TITLE
Staff of Change On self removes you from round

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33027]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
4e29ac0ce6d6dcd1281a140a5fd593414cff5acf

# Description
>get wiz midround after getting sharted
>decide since the round has a cat theme I'll turn people into furries and I've never used SOC before
>get bind, smoke, blink
>whip out the SOC , bind it
>oh hey I should be one too
>use staff of change on self get kicked out of body
:(
# Steps to Reproduce
hit yourself with staff of change set on furry
# What you Expected
to stay in my body 
# What Actually Happened
I got sent to death chat

**Comment by adacovsk** [comment]
tested and could not reproduce

**Comment by Dacendeth** [comment]
Tested and reproduced, got sharded, got polled for wizard, spawned on arrivals shuttle for some reason???, staff of changed myself and it made a catbeast and I was ghosted from the catbeast.

**Comment by adacovsk** [comment]
so it's specific to midround wizard

**Comment by DeityLink** [comment]
The actual problem here was not the SoC, but the fact that the makeBody() proc creates a borked mind datum.
