### ISSUE TITLE
Alcohol is far too deadly

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#3303]
To test:
Drink large quantities of alcohol
die

Alcohol is far too deadly. You die well too fast from drinking it. It should take a lot more to even hurt you then it currently does. Its totally out of whack and is really immersion breaking.

**Comment by Boxe** [comment]
fix it fix it fix it fix it make it like it was before pls

**Comment by omeno** [comment]
Agreed. Damage needs to be decreased a lot, as if being drunk didn't already have enough disadvantages.

**Comment by 9600bauds** [comment]
While we're at it, could we please make Ambrosia Deus not cause your liver to instantly shrivel up and die shortly after you are wracked with the agony of obscene levels of toxicity?

**Comment by Probe1** [comment]
I think reducing, without removing, the organ damage is a good point to start for alcohol.  Toxin damage is alright, alcohol should have some.  It's having your liver absolutely fried that causes so many issues.  Instead of a quick trip to the chemist it's finding a surgeon to do a lengthy operation, then a chemist.

**Comment by Arthurdentist** [comment]
Im not even sure it should have any toxin damage really. Either way in its current iteration its basically 'Drink a bottle of rum and die', this really needs to be re-addressed.

**Comment by Probe1** [comment]
it's a pretty good way of giving medbay work

**Comment by Arthurdentist** [comment]
Im not really sure medbay needs anymore busy work. Its absolutely daft.

**Comment by Killette2** [comment]
>Drink a whole bottle of tequila in under a minute and die

WOW

This is what shots are for ya dingusses

**Comment by Senaat1** [comment]
I agree, alcohol isn't fun to drink anymore. I took one sip of a black russian and spent the next 45 minutes with the shakes.

**Comment by Kurfursten** [comment]
Addressed by https://github.com/d3athrow/vgstation13/pull/3337

**Comment by clusterfack** [comment]
^
