### ISSUE TITLE
Infinite materials from Station Tube Frame

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33038]
(WEB REPORT BY: kettuthefox REMOTE: 206.221.180.138:7777)
# Revision
4e29ac0ce6d6dcd1281a140a5fd593414cff5acf

# Description
Unable to disassemble the Station Tube Frame on Synergy station, and attempting to do so creates infinite frames and reinforced glass on the first step of dismantling
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by pedr69** [comment]
do the premapped tubes even work?
i also couldn't find a way to assemble the stations and pods, even with the rnd printable circuitboards

**Comment by nervere** [comment]
The tubes on Meta and Synergy are still busted completely, can't even be entered.
I think it's less of an issue with the mapping and more with the tubes themselves.

**Comment by Exxion** [comment]
Transit tubes have been fucked since approximately the beginning of time and they don't even have an excuse for it

**Comment by pedr69** [comment]
the tubes worked at one point.
i remember because i used them
currently, when you clickdrag people inside you get "access denied" no matter your access

**Comment by Exxion** [comment]
They've worked before, but they've always been buggy in various ways for no good reason
