### ISSUE TITLE
cyborgs die to pacid smoke now

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33039]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
4e29ac0ce6d6dcd1281a140a5fd593414cff5acf

when the FUCK was this changed?

**Comment by pedr69** [comment]
since #32424 pretty sure

**Comment by Dacendeth** [comment]
feature.

**Comment by pedr69** [comment]
oh? because the PR doesn't mention borgs instantly dying to acid anywhere

**Comment by Eneocho** [comment]
"feature" he means. It's a "feature" in the same way lag is a "feature".

**Comment by nervere** [comment]
Kanef's dead off GitHub and Discord so he can't be reached, but given the amount of issues that PR has caused this is likely a bug.
