### ISSUE TITLE
LineStation's CE office has a regular RCD.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33040]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
4e29ac0ce6d6dcd1281a140a5fd593414cff5acf

# Description
Title.
# Steps to Reproduce
Linestation.
CE.
See RCD.
# What you Expected
The fancy ass RCD.
# What Actually Happened
Regular RCD.

**Comment by adacovsk** [comment]
this item is new

note to self: alarm under break room shutter

**Comment by Eneocho** [comment]
>this item is new

I know, I was just reporting it for consistency.
