### ISSUE TITLE
suit storage units problems

### ISSUE THREAD

**Issue by xevonix** [d3athrow/vgstation13#3305]
Suit Storage Units don't have a sprite when the supermatter begins cascade and I'm not completely sure if it does if the station fails power.
I also couldn't remove the contents from the containers for some reason, I stood there crowbaring it and after a minute or so nothing came out. I could just be dumb though.

**Comment by clusterfack** [comment]
I think that was the machines being physically destroyed. Also the supermatter cascade had a few bugs that were fixed and just not into the game yet at the time we spawned it on the live server.

**Comment by clusterfack** [comment]
Oh wow actually their sprite does fuck up now.
