### ISSUE TITLE
Fish net black hole

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33068]
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
15e8ff2efd5f3e8c73ace1e8f70414c7f6f7852a

# Description
Fish nets are a black hole
# Steps to Reproduce
Use a fish net on an aquarium with fish inside
# What you Expected
To get fish
# What Actually Happened
Boko No fish

**Comment by adacovsk** [comment]
Can't reproduce bug

**Comment by nervere** [comment]
If anyone has more info on this, that'd be appreciated.

**Comment by adacovsk** [comment]
yeah the dude said that he was retarded and he's going to try again

**Comment by adacovsk** [comment]
@nervere you can close this now
