### ISSUE TITLE
pulse demon movement

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33065]
(WEB REPORT BY: robocopreb REMOTE: 206.221.180.138:7777)
# Revision
15e8ff2efd5f3e8c73ace1e8f70414c7f6f7852a

# Description
While traveling on wires in maint, got tagbled by vines as a power demon
# Steps to Reproduce
Travel as a pulse demon, on a non covered tile with vines on it.
# What you Expected
to move freely 
# What Actually Happened
"The vines wind around you!"

**Comment by pedr69** [comment]
yeah i [tried](https://github.com/vgstation-coders/vgstation13/pull/32844#issuecomment-1166703004) to fix that and decided i won't touch kudzu code
