### ISSUE TITLE
Jukebox music will not play

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33076]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
b01e2822aa68e4d50b7710bf945d83bd90397d5f

music cannot be heard, multiple people are having the same issue

**Comment by nervere** [comment]
Likely related to #32918

**Comment by adacovsk** [comment]
"You have no media datum to change, if you're not in the lobby tell an admin"
