### ISSUE TITLE
Chloral Syringe Stab doesn't seem to work right/inject full payload

### ISSUE THREAD

**Issue by stormcloud23** [d3athrow/vgstation13#33080]
#### Description of issue
Playing as a cultie today I chloralstabbed a fellow doctor, Ragnar Thunderfist. He dropped after about a second or so, and I dragged him off to convert him, but then about 5 seconds later he got back up. I asked him after the round and he hadn't taken antitox or coffee, so I'm thinking it's either a bug or maybe a change to syringe stabbing that I missed.

#### Difference between expected and actual behavior
15u of chloral should have kept him asleep for significantly longer than 5 seconds. 

#### Steps to reproduce
Fill syringe with chloral, harm intent, click on someone else.

**Comment by boy2mantwicethefam** [comment]
Harm-syringing someone IIRC injects anywhere between 1 and 5 units.

**Comment by djkramer123** [comment]
skill issue

**Comment by stormcloud23** [comment]
> Harm-syringing someone IIRC injects anywhere between 1 and 5 units.

Is that a recent-ish change? I thought it used to inject the full syringe

**Comment by adacovsk** [comment]
Learn the rag trick

**Comment by djkramer123** [comment]
Harm syringing got buffed back in 2018 to inject a minimum of 2 units, max has always, as far as I've known, been 5 units. #18800

Or to summarize, skill issue, not a bug.

**Comment by nervere** [comment]
I wish there were better logging in `attack.log` for how much ended up being injected, but that's a different topic entirely.
This isn't a bug for the reasons Barry and DJ have stated above.
