### ISSUE TITLE
Swiss Army Knife Butchering

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33082]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
56dcf439d0a85c6a1804faf0797a7e57d0fc27eb

# Description
Can't butcher with the swiss knife.

# Reproduction
1. Kill monkey
2. Whip out swiss knife to, say, knife.
3. Try to butcher
4. Be told you can't butcher with that.

**Comment by Eneocho** [comment]
You have to take the knife off. It's a known issue #29020.

**Comment by nervere** [comment]
Closing as the duplicate issue covers this + much more
