### ISSUE TITLE
Metal rods from powered crossbow unstackable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33084]
(WEB REPORT BY: kettuthefox REMOTE: 206.221.180.138:7777)
# Revision
56dcf439d0a85c6a1804faf0797a7e57d0fc27eb

# Description
I am not sure if this is a bug, but when a metal rod is added to a Crossbow, when it is fired or unloaded in any way, it no longer behaves like a normal rod, unable to stack them with normal rods or themselves, and also no longer count for cooking recipes. I assume this is because they become a projectile instead of the normal construction Rods, but since they don't stack they quickly take up inventory space if picked up a second time to fire again.
# Steps to Reproduce
Load a metal rod into a Powered Crossbow and either fire it or unload the rod by dropping/backpacking the Crossbow.
# What you Expected
Expected rods to stack on themselves or collection of metal rods currently in backpack.
# What Actually Happened
Rods did not stack as planned, had to leave them on the ground and craft new Rods from metal sheets.

**Comment by Eneocho** [comment]
Not a bug but could afford to be better. It indeed stops being a metal rod and becomes a projectile.

**Comment by nervere** [comment]
The projectiles should probably become stackable or become normal rods outside of the crossbow.
I feel like this just hadn't gotten that much love because you don't see the crossbow much outside of the vox outpost.

**Comment by Eneocho** [comment]
You DON'T see them outside the outpost though, it is an exclusive vox weapon (vaults don't count). For reference, they were craftable stationside but got removed (#16222) for muh balance and the attempt at restoring them (#21328) was abandoned.
