### ISSUE TITLE
Windoors teleport cargo carts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33099]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
d20448ab87144374cf046296b9a09ed10d3260ae

# Description
After going through a windoor on a tractor, when the windoor automatically closes, it will teleport the cargo cart next to itself. This happens even if you move very far away from the windoor.
# Steps to Reproduce
Be on tractor
Have one(?) connected cargo cart
Go through windoor
Let windoor close automatically
# What you Expected
Nothing to happen
# What Actually Happened
My cart got yoinked away

**Comment by Eneocho** [comment]
Same happens with regular chairs and I think when dragging stuff.
