### ISSUE TITLE
Issues with the new library stuff

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#3310]
Alrighty, just noticed the new library stuff is in, and was checking it out.
Seems like you can only access the first page of stuff, there's only 1 page available to choose and clicking the '1' does nothing. 
I would try out the new delete thing, but I would prefer to delete something I know is garbage/broken, but I can't get to those without the pages working. 
You can't wrench up the new library computer either, not sure if that's an intended thing or not, because I didn't know that the ability to wrench up the visitor computer had been added until right now. Considering you still can't wrench up the book binder, it's probably intended, so I dunno about that one.
This one is just a bit of a complaint on my end, not really a technical issue at all; The menus for the main menu, arcane tome printer, book checkout, and possibly more are really small.  The ones for the main archive and most of the others are fine, but the ones I mentioned are noticeably smaller in size. 
![ss 2015-03-05 at 01 35 16](https://cloud.githubusercontent.com/assets/9064611/6500339/8c54ca6e-c2d8-11e4-945e-3949372bd816.png)

![ss 2015-03-05 at 01 46 14](https://cloud.githubusercontent.com/assets/9064611/6500422/7a11833c-c2d9-11e4-8491-bb0c050a7157.png)

**Comment by frangi** [comment]
while you're at it, adding filtering by category would be nice.

another good thing would be a search function for book titles/authors, but it might be too costly.

**Comment by NigglyWiggly** [comment]
Actually, the visitor computer now has a search with filters, so that's a nice addition

**Comment by d3athrow** [comment]
@N3X15-Jenkins @n3x15

**Comment by Kurfursten** [comment]
Do these issues still persist?

**Comment by NigglyWiggly** [comment]
These should all be fixed.
