### ISSUE TITLE
You the beaker with the beaker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33115]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
fc3bbbf012ed3808801a3f6e3449af97468e95f5

# Description
If you try to pour a beaker into another beaker on a table in harm mode...
>You the beaker with the beaker, but it glances off!
The reagent still pours, but... bop!

**Comment by SECBATON-GRIFFON** [comment]
attack_verb is missing for beakers it seems
