### ISSUE TITLE
Voracious plants don't seem to be eating pests

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33117]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
fc3bbbf012ed3808801a3f6e3449af97468e95f5

# Description
Voracious plant (pest + weed eating), pest light keeps blinking, is it not eating pests?
# Steps to Reproduce
get voracious plant, wait for pests
# What you Expected
plant eat bugz and be happy
# What Actually Happened
plant no eat ze bugz

**Comment by Eneocho** [comment]
I think the pest-eating rate is too slow.

**Comment by adacovsk** [comment]
> I think the pest-eating rate is too slow.

you're probably right
