### ISSUE TITLE
Plague mice get their memory notes spammed until full

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33128]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
fc3bbbf012ed3808801a3f6e3449af97468e95f5

# Description
be plague mouse. 
Your memory, however hazy, is full.x2
# Steps to Reproduce
find another cute plague mouse and make plague mouse babies
# What you Expected
nothing
# What Actually Happened
Your memory, however hazy, is full.x2
Your memory, however hazy, is full.
Your memory, however hazy, is full.
My memory, however hazy, is filled with identical description of disease I carry x69

**Comment by nervere** [comment]
I've had this happen every time I've played plague mouse. I think it's constantly updating the people who are infected and it makes a new giant note every time. Just going off memory though, I haven't checked the code for it.
