### ISSUE TITLE
Borers can inject radium, very harmful

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33129]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
fc3bbbf012ed3808801a3f6e3449af97468e95f5

# Description
Borers can inject radium into hosts, despite being all about never harming their host. I believe this is remnant of past, when virology wasn't reworked yet and viruses were cured by drinking copious amounts of radium. As such, radium in borers should be replaced with spaceacillin.
# Steps to Reproduce
be borer, inject host with radium, harm host, bad borer.
# What you Expected
no harmful chems
# What Actually Happened
harmful chems in my chem list goading me into irradiating my host.

**Comment by ghost** [comment]
borers can be made traitors so this is a feature(tm)
