### ISSUE TITLE
AI "track with camera" stops working on certain people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33126]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
fc3bbbf012ed3808801a3f6e3449af97468e95f5

i am unable to see some people in the tracking list.
they are near a camera, wearing an ID and everything - they just don't show up on the list

**Comment by nervere** [comment]
Were they wearing tinfoil hats? Were they changelings with the mutation that disables AI tracking?
Not enough info to pinpoint this issue.

**Comment by pedr69** [comment]
no tinfoil, changeling maybe
i had it happen to three people, and the round in question only had one ling. it's possible that he disguised three times
they also probably weren't wearing agent ID's - none of the traitors bought an agent card

**Comment by nervere** [comment]
I checked the href's for the round in question. Seems the changeling in question did indeed have digital camouflage.
I think this sufficiently explains what happens, so this likely isn't a bug.

`16:32:49 ApotheoticOrder (usr:Arnie Styles) || /datum/power_holder/changeling src=[0x2102d07d];P=Digital%20Camouflage`
