### ISSUE TITLE
Toggle Gun Mode doesn't work on cap gun anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33132]
(WEB REPORT BY: vladorf REMOTE: 206.221.180.138:7777)
# Revision
fc3bbbf012ed3808801a3f6e3449af97468e95f5

# Description
You can't point toy guns at people anymore, when you try it just fires / makes the click sound as if it's trying to fire. 

# Steps to Reproduce

Get cap gun
click toggle gun mode
click on another player

# What you Expected

You shoul aim the gun at them, the red targeting circle thing should appear and it should only fire when they move or however you have the fire mode set. 

# What Actually Happened

The cap gun tries to fire.

**Comment by nervere** [comment]
I find it somewhat hard to believe it ever had this functionality because it's in the code as a toy that makes a sound, not a gun.
Maybe you're thinking of pranking people by targeting them with an empty russian revolver. That said, making it a gun that simply fires blanks would be cool, and it'd make this work pretty easily.

**Comment by Dacendeth** [comment]
Yeah, this never worked that way.

**Comment by Eneocho** [comment]
>That said, making it a gun that simply fires blanks would be cool, and it'd make this work pretty easily.

I can already see the clown aiming his capgun at people only for beepsky to shit its figurative pants and cuff him for having guns without a permit.

**Comment by WindowsErrors** [comment]
yea the securitron weapons code is pretty funny to metagame, I can bring one to the medbay and it'll handcuff people for having pill bottles and defibrillators, meanwhile not even britsky will mind me walking the halls with my anarchist black fuse bombs

**Comment by Eneocho** [comment]
rip kanef he died too young
