### ISSUE TITLE
Glowshrooms don't work

### ISSUE THREAD

**Issue by Fermented** [d3athrow/vgstation13#3314]
Glowshrooms glow when they're an item.
They don't glow when they're attached to a wall or floor, like they should.

**Comment by CptWad** [comment]
What was your potency?
I know having shit potency can be ONE reason
Another reason can be the continued lighting issues. I know after you plant glowshrooms it takes a while for them to actually work. Around two or ten minutes.

**Comment by d3athrow** [comment]
If your potency is below 10 it will not have any luminosity due to how round works.

**Comment by ConkerDev** [comment]
Can be closed?

**Comment by Probe1** [comment]
@N3X15 glowshrooms currently work as intended, good to close
