### ISSUE TITLE
. taps the frog with the lazarus injector.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33154]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
38ba53bf765b5073c64231e82fe6b00b23912d3d

# Description
Tried resurrecting a frog I had as a hat with a lazarus. Got that instead of the reviving.
# Steps to Reproduce
Froghat.
Froghat dead.
Lazarus.
# What you Expected
Frog revival
# What Actually Happened
. taps the frog with the lazarus injector.

**Comment by Eneocho** [comment]
When I eventually dropped the frog and tried reviving it it revived properly by the way. But it still had that weird ". taps the frog with the lazarus injector." thing

**Comment by Dacendeth** [comment]
frogs/mice/nymphs are items when held, and not mobs, laz injector only works on mobs, the other thing is uhh who knows.

**Comment by nervere** [comment]
The message needs to be fixed, but ya as Dacendeth said you really can't revive held/worn mobs with a lazarus as it stands.

**Comment by jwhitak** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/69739118/7d7298ef-d646-4421-bd4e-b0e87700aa2e)

Still a thing, whee!

**Comment by SECBATON-GRIFFON** [comment]
for whatever reason handle_attack sets the shown name to "." as a fallback
