### ISSUE TITLE
Seed potency seems to be capped at 198

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33169]
(WEB REPORT BY: saulmyers REMOTE: 206.221.180.138:7777)
# Revision
fd808d68d314904b39ca913c8f692e1c5eba8f72

# Description
After buckets of both type mutagens, seed potency does not go above 198 (cap is 200). I guess this is due to diminishing results and seed potency formula.
# Steps to Reproduce
pour ungodly amounts of mutagens in plant tray, wait
# What you Expected
200 potency (nice, round number)
# What Actually Happened
198 potency (ugly looking number)

**Comment by west3436** [comment]
Closed via #35820.
