### ISSUE TITLE
media streaming resets when you leave and enter a room.

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#3316]
OS: Win 7
Media streamer: WMP

How to duplicate
\>Turn on jukebox
\>Wait t'ill song starts playing
\>Walk out the room
\>Walk back in
\>Song is playing from the beginning again

**Comment by BestName** [comment]
It's a problem with WMP, use VLC instead.

**Comment by d3athrow** [comment]
This is why we switched to VLC, either downgrade WMP to 10 or lower OR use VLC.
The cause of the bug is newer versions of WMP will not seek to an unbuffered part of streamed media.
