### ISSUE TITLE
spawned naked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33175]
(WEB REPORT BY: assmops REMOTE: 206.221.180.138:7777)
# Revision
fd808d68d314904b39ca913c8f692e1c5eba8f72

# Description
My game froze at roundstart, even getting the "connection closed" warning in the chatbox. After I closed my game and reconnected manually, my character had no clothes, no ID, and no name in LOOC, but still appeared as Spessman (as Unknown) when I talked in-game.
# Steps to Reproduce
Lag at roundstart I guess

# What you Expected
Funny atmos sim 
# What Actually Happened
Nudity and bullying for being naked and unnamed

**Comment by ShiftyRail** [comment]
thanks Adam
