### ISSUE TITLE
Duplicate bodies (?) by hookshotting them out of cryo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33183]
(WEB REPORT BY: poales REMOTE: 206.221.180.138:7777)
# Revision
fd808d68d314904b39ca913c8f692e1c5eba8f72

# Description
if you hookshot someone, put them in a cryo tube, then pull them out with the hookshot their body gets visually duplicated, while their spirit gets (apparently) sent to gay baby jail

# Steps to Reproduce
Hookshot
put in toob
walk away
put the second body in the second toob
walk away
have a third body

# What you Expected
I thought going into cryo would break the hookshot

# What Actually Happened
admins had to teleport his ghost back into the world of the living

**Comment by poales** [comment]
supplementary video for your entertainment
https://user-images.githubusercontent.com/38336601/187826316-82ae94c7-779a-4999-8082-3e26d6cbe6ed.mp4

**Comment by DeityLink** [comment]
Funnily enough, not even a hookshot-specific bug. Can also occur by teleporting out of Cryo.
