### ISSUE TITLE
You can't milk the ayy polyps.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33189]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
fd808d68d314904b39ca913c8f692e1c5eba8f72

# Description
Title.
# Steps to Reproduce
Use bucket on polyp.
# What you Expected
Gelatin.
# What Actually Happened
Chiyatayichayikaha collects gelatin from Burns's tendrils using the bucket.

You splash the solution onto Burns.

**Comment by Optimism333** [comment]
Yeah, for some reason you can't milk them properly unless you put the lid on the bucket first. I'll look into it when I can.

**Comment by Kurfursten** [comment]
This is super weird. It does not happen on goats or cows where the code is pasted from. And it also does not happen when feeding them meat or giving notraisins. Attackby is getting called twice but only by reagent containers.

**Comment by Hinaichigo** [comment]
Also when you try to drink from a beaker as a monkey, you simultaneously splash it on yourself. It may be related.

**Comment by Optimism333** [comment]
> Also when you try to drink from a beaker as a monkey, you simultaneously splash it on yourself. It may be related.

Can't guarantee that my fix addressed that monkey business. However, polyp splashing should be fixed now.
