### ISSUE TITLE
trader outpost on box has an infinite SMES

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33196]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
4970ae7b90823dba176f7e37ef0bfe0e0356630c

[box][consistency]
superior bird engineering or power creep?
the science and mining outposts have normal SMES that run out after a 12 hour shift

**Comment by Servalfang** [comment]
superior bird engineering

**Comment by Eneocho** [comment]
powercreep, FUCK birds

**Comment by pedr69** [comment]
i have not seen a trader go around advertising their cool warez for a good couple months now
what happened to the vox metaclub

**Comment by Eneocho** [comment]
It died down when [INSERT CKEY] got banned or other. In general most metaclubs (which curiously tended to share players) have disappeared. The sec and vox metaclubs have all but banished.
