### ISSUE TITLE
Jukeboxes continue to play after you toggle it off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33205]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
6e5c4d239cd04d10bc6296602319c39be86e9b15

# Description
fuck you adacovsk fuck you fuck you
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Not happening anymore
