### ISSUE TITLE
Death of a Salesman: Cargo consoles and custom vending machines no longer recognize IDs

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#33227]
#### Description of issue
[adacovsk](https://github.com/adacovsk)

**Comment by adacovsk** [comment]
working on it, account number not assigned to ID

**Comment by nervere** [comment]
Shifty reverted Adam's PR due to the tremendous amount of issues it has caused so I'm gonna close this.
See: https://github.com/vgstation-coders/vgstation13/pull/33229
