### ISSUE TITLE
Mime Name change isn't working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33228]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
02361cb81bca4e25365dc781554d987070b6f9e2

# Description
joined in round start as mime bug and didn't get a mime name pick
# Steps to Reproduce
join in round start as mime bug and didn't get a name pick
# What you Expected
To give myself a silly name
# What Actually Happened
I had to stick with my original silly name

**Comment by nervere** [comment]
Shifty reverted Adam's PR due to the tremendous amount of issues it has caused so I'm gonna close this.
See: https://github.com/vgstation-coders/vgstation13/pull/33229
