### ISSUE TITLE
ADAM YOU FUCKER

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33230]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
02361cb81bca4e25365dc781554d987070b6f9e2

# Description
Adam's fuckery has caused me to load into the round without an account on the accounts database
# Steps to Reproduce
Join the game
# What you Expected
To have an account with money
# What Actually Happened
No account

**Comment by nervere** [comment]
Shifty reverted Adam's PR due to the tremendous amount of issues it has caused so I'm gonna close this.
See: https://github.com/vgstation-coders/vgstation13/pull/33229
