### ISSUE TITLE
Polyp Milking with Bucket Splashes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33239]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
462772ebd455a989882c30f3a6bd5ffb3805099f

# Description
When using a bucket on help intent on Burns to collect Gelatin, very likely it's calling ..() AFTER doing the milking, which causes it to splash the freshly harvested gelatin on Burns.

**Comment by Optimism333** [comment]
Trying to address this in #33208

**Comment by nervere** [comment]
Closing as duplicate of #33189
