### ISSUE TITLE
Another Amorphous mask bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33231]
(WEB REPORT BY: jormungand REMOTE: 206.221.180.138:7777)
# Revision
53e4bafd005f441ce06e8be4d2133142b22fa1e4

# Description
Another story where turning into rabid slime will instantly kill your and not revert you back to your body
# Steps to Reproduce
get rabid slime mask somehow
# What you Expected
not to die immediately and my body gone forever
# What Actually Happened
the opposite

Blacklisting it is the way to go, I think

**Comment by nervere** [comment]
Rabid slimes seem to cause a lot of issues, might have to just blacklist them from the mask.
