### ISSUE TITLE
Deff Has No Beepskys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33256]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
37726685cc5aceb733efbeef1a9c4275bd5d53cc

# Description
not a single beepsky on deff what's a warden to do
not one in the armory not one in the halls

**Comment by djkramer123** [comment]
It's almost like it's deficient

**Comment by Theophrastus1** [comment]
FUCK YOU DUNY

**Comment by nervere** [comment]
It's trivial to add them, but there's no point right now with robot pathing broken. :frowning_face:

**Comment by pedr69** [comment]
robot pathing works, it's just that beepskies will disable autopatrol after they arrest someone

**Comment by Theophrastus1** [comment]
> robot pathing works, it's just that beepskies will disable autopatrol after they arrest someone

"robot pathing works except when it doesn't"
