### ISSUE TITLE
Impossible plant demands, 11 lumens

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#3327]
![11lumens](https://cloud.githubusercontent.com/assets/5169310/6522716/0beca7fa-c3b6-11e4-97da-23fa10840e99.png)

When mutating plants, it can mutate to want 11 lumens. The maximum lighting no matter how bright you can make things is 10 lumens. Please settle the plants down.

**Comment by 9600bauds** [comment]
Plants still have a light resistance threshold, 11 lumen is only the ideal number. That plant's fine at 6-16 lumen or something around that.

**Comment by DrCelt** [comment]
Now I want an item for a botanist that can go to 25 lumens but requires a welding mask to use and blinds anyone nearby who looks at it for too long

**Comment by Hoshi-chan** [comment]
Botanist traitor item: solar ray. Needs to be charged by bright lights or being on the exterior of the station.

**Comment by Killette2** [comment]
As a frequent botanist player (which is obvious), I do agree that they could use another specialty traitor item. Ambrosia C is nice, but sometimes it isn't the route you're going for, and funny enough you can get Ambrosia C in alien form already too.

**Comment by 9600bauds** [comment]
[Not A Bug] [Needs Final Decision]
