### ISSUE TITLE
Player made airshields cannot be taken apart, they lack machine flags

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#33287]
#### Description of issue
The airshields that players can make lack the proper flags to be taken apart.
flatpacked airshields also cannot be mechanic scanned again by another mechanic.

#### Difference between expected and actual behavior
Stand inside airshield and screwdriver it to begin taking it apart, no feedback or anything

#### Steps to reproduce

Make one normally, scan it with a mechanics scanner and print it, attempt to take it apart by screwdriving it while inside of it.

**Comment by pedr69** [comment]
i couldn't deconstruct normally built airshields either

**Comment by Dacendeth** [comment]
I made one and I could, using t1 parts, but after scanning it and printing it I couldnt.

**Comment by Dacendeth** [comment]
Okay I made one normally again the exact same way as before and I cant take it apart now, not sure what is going on here.

**Comment by Dacendeth** [comment]
Turns out I might taken apart one I spawned in confusion instead while testing, you cant take any apart you make or print from the flatpack.

**Comment by jwhitak** [comment]
Working on fixes
