### ISSUE TITLE
Airshields cant be taken apart or moved

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#33282]
Now that airshields can be made I feel like construction steps to be able to take them apart should also be added.

**Comment by Kurfursten** [comment]
Wait I coded deconstruction on these myself when I made them originally

**Comment by adacovsk** [comment]
is it in the wiki?

**Comment by Kurfursten** [comment]
No, until now you'd only rarely encounter them anyway, only off of the pocket satellite or bus
There's definitely a case to put construction/deconstruction on some page of the wiki, maybe Guide to Construction
