### ISSUE TITLE
Diona node pod bug finally solved!

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#3328]
It seems since bees can make the trays overflow in nutrament with 11/10, this doesn't affect any plants except for diona nodes. For some reason if the nutrament levels go above 10, the pod instantly vanishes. I figured out the cause to this when every time I grew diona pods around my bees they vanished, but I grew one in the back and it finally was successful. My partner also grew them before I planted the bees and they work, so bees are what is breaking the pods.

**Comment by TermedClepe** [comment]
https://github.com/d3athrow/vgstation13/issues/3182
