### ISSUE TITLE
Neither AAC works properly for me

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33292]
(WEB REPORT BY: wootikins REMOTE: 206.221.180.138:7777)
# Revision
4a0cf7ef5e6dfe2bdb954395016f579ea73b5645

# Description
Whenever I try to use the AAC, and I try to click "STOPPED" to get the process rolling, it SHOULD switch to "RUNNING" but it almost never does. I have no idea why. eventually if I sit there and click it enough and try a million different things it will work but i have no idea how to get it working consistently without taking half the damn round. 

# Steps to Reproduce
No steps to reproduce. I literally juse interact with teh AAC, both the one in atmos and the one near the TEG, and neither ever works for me. I can do everything from the pop up but click the buttons "STOPPED" and "RUN ONCE". I can click them but they do nothing 99% of the time. 

# What you Expected
Expected AAC to switch to "RUNNING" once I clicked Stopped. Instead does nothing. 

# What Actually Happened
Does nothing.

**Comment by Kurfursten** [comment]
Unable to reproduce on live
