### ISSUE TITLE
All travis subtasks are ONLY building box

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3331]
~~Yes, the meta, defficiency and taxi subtasks on travis are all including boxstation in the compile.~~

Oh great, now it's **only** building box, none of the other maps get checked.

**Comment by dylanstrategie** [comment]
No longer happening, Travis does says its including tgstation.dmm in all of its builds, but by intentionally fucking up the other maps by changing a path and only updating Box, you'll clearly see it's compiling the other maps too

**Comment by PJB3005** [comment]
\>Implying

Now it's ONLY building box, it's even worse.

**Comment by ConkerDev** [comment]
Acording to the IRC bot, this is no longer an issue. Can @PJB3005 or @N3X15 confirm?

**Comment by PJB3005** [comment]
The IRC bot doesn't tell which maps are compiled, we're talking about the Travis CI which checks the PRs, not the watchdog which compiles the serer.

And yes, it's still broken.
