### ISSUE TITLE
The Jukebox Tune "Spamton Toilet Paper" opens a VLC media window

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33313]
(WEB REPORT BY: jazzstringz REMOTE: 206.221.180.138:7777)
I'm serious. Someone was piping that tune over the sound system, I think, and every time I would enter the gym, where it was playing, the VLC media window would pop up and play the video with music on it

**Comment by west3436** [comment]
you are now mining bitcoins for pomf

**Comment by Exxion** [comment]
It's bus. The classic video juke trick.

**Comment by SECBATON-GRIFFON** [comment]
[[ Suppository supplies for him and her ]] SO GOOD I'LL [[ *%^"£&£ ]] MY SELF !!
