### ISSUE TITLE
Box - Missing tile under Bridge - CQ airlock

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33318]
(WEB REPORT BY: kernikov REMOTE: 206.221.180.138:7777)
Plating, not floor tiles or wood.
Make this wood for consistency with bridge - meeting room.

**Comment by nervere** [comment]
Someone must have pried up the floor tile with a crowbar when trying to hack in Captain's Quarters from the Bridge.
There is definitely a wood floor tile there, I just checked.
