### ISSUE TITLE
Golden Gloves don't heal at all.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33311]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
a3aaae8dcc80069a49f500dce015fd06536e5909

# Description
The activated golden gloves consume electrical shocks to heal the user, but they don't work anymore.
# Steps to Reproduce
Wear golden gloves. Activate them by touching the SM. Cut a live wire, don't get shocked. Shock an airlock, don't get shocked. Shock a vendor, don't get shocked.
# What you Expected
To get shocked and heal.
# What Actually Happened
Nothing happened. Essentially blingier insulos without the special effect.

**Comment by Kurfursten** [comment]
Cannot reproduce on live
![image](https://user-images.githubusercontent.com/9782036/190876354-7fb08acd-4012-43f2-b563-3b104c3101f4.png)
![image](https://user-images.githubusercontent.com/9782036/190876356-0b21f72c-e567-47f0-9ad7-cbaa786f671e.png)

after recut
![image](https://user-images.githubusercontent.com/9782036/190876369-87efe8a5-305f-47af-a244-f55c2ac95087.png)

**Comment by Kurfursten** [comment]
@Eneocho Confusion maybe caused by a lack of animation/feedback message

**Comment by Eneocho** [comment]
No, I literally didn't ever heal. I was burnt big time by entering the burn chamber without hardsuit. 
I then tried shocking myself and I never healed.

**Comment by Kurfursten** [comment]
Unpowered wire?

**Comment by Eneocho** [comment]
It was linked to the active engine, so powered. I then tried shocking doors and vendors and nothing.

**Comment by Kurfursten** [comment]
See if you can reproduce it

**Comment by Eneocho** [comment]
I tried to reproduce it on localhost and can't reproduce. Was it an issue of that particular round?

**Comment by Kurfursten** [comment]
We may never know. Let me know and I will reopen if you see it again.

**Comment by pedr69** [comment]
were you wearing a hardsuit while not healing?
it might be because hardsuits make stungloves not work, maybe the golden gloves too?

**Comment by Eneocho** [comment]
No, I was wearing regular clothing. I had built the prototype airshield TEG on Roid atmos and didn't wear a hardsuit.
