### ISSUE TITLE
Alien Issue

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3333]
I played an alien queen during a round, and began consuming monkeys so that I could take them back to my nest and safely infect them. I consumed 5 monkeys in total.

But by the time I got back to my nest I regurgitated all the monkeys, only one monkey came out of my stomach contents, and it was already  deceased. Used VV to check and all the other monkeys weren't in my stomach contents either.

Considering the way the ability to hold mobs in your stomach is described, this all doesn't seem like intended behavior for the ability.

**Comment by CptWad** [comment]
Described where?
I know that devouring things will slowly eat them and give you health for eating them
Also it might just be that holding two things at a time will cancel one of them out.

**Comment by clusterfack** [comment]
The wiki for example describes bringing mobs to infect back to the nest by devouring and then regurgitating them.

**Comment by 9600bauds** [comment]
You digested 'em

**Comment by ihadtoregisterforthis** [comment]
To see if it was digestion you could see if they get deleted and ghosted or if they are sent to nullspace.

**Comment by 9600bauds** [comment]
Preliminary tagging Not a Bug until it's confirmed that you didn't just digest them

**Comment by gbasood** [comment]
Wait what
If it's been confirmed that you didn't digest them then HOW IS IT NOT A BUG

**Comment by 9600bauds** [comment]
Where was it confirmed that it wasn't digestion?

**Comment by gbasood** [comment]
Misread your comment nevermind

**Comment by CptWad** [comment]
Tested some stuff
\>Digestion is incredibly fast
\>You CAN regurgitate two, probably more mobs, meaning they dont delete the other

**Comment by Intigracy** [comment]
#6566

**Comment by gbasood** [comment]
So both these issues are full of stupid shit so I'll just start discussing it, again, here, because it's a smaller issue thread.

We could drastically reduce damage done to digested mobs
OR
Remove digestion damage

**Comment by Intigracy** [comment]
We should keep digestion damage in, but it shouldn't delete the mob.

We should also restrict you to only eating one mob at a time. This isn't voooore.

**Comment by 9600bauds** [comment]
It's literally vore tho

**Comment by Intigracy** [comment]
We can have vore without it being insane vore.

Maybe xenos are like snakes and can reasonably fit a mob inside their stomach, but I doubt they could fit multiples.

**Comment by gbasood** [comment]
Honestly I'm not a fan of the mechanic as it is, anyway.
