### ISSUE TITLE
Medical Reviving problem

### ISSUE THREAD

**Issue by Beroya** [d3athrow/vgstation13#3334]
You can't heal a body below the 200%+ damage line above it to defibrulate them in any way shape or form
There needs to be a way to do this, like cryo or normal medicine, while they're dead or remove the lower limit for defibrulation

**Comment by dylanstrategie** [comment]
I have already added the ability to bandage dead bodies, but in theory a body that was more than 199 points worth of non-oxy damage is beyond saving and needs to be cloned

200 brute/burn is massive mutilation

**Comment by gbasood** [comment]
Okay but what if I find a person whose external limbs are the only reason they can't be revived
200 damage to someone's legs and arms should be fixable without cloning, just chop them off and you're good to go
