### ISSUE TITLE
Airshield Projector fields are not blocking atmos.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33344]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
8e973264cd88c7341c72f87e934ea42e3fb30520

# Description
Used an airshield projector to block n2o flow, it expanded anyway.
# Steps to Reproduce
Flood plasma/n2o, use the airshield projector to block atmos flow.
It fails.
# What you Expected
Airshield Projector to project airshields.
# What Actually Happened
Accidental flood.

**Comment by Eneocho** [comment]
Reopen this one, @Kurfursten. This was a report on the handheld airshield projectors, the one the traders sell, not the airshield machinery.
