### ISSUE TITLE
No Labor Administration Console on Castle Map

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33355]
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
21201cf7a84c8b78696857ad25c0276a14092423

# Description
Head of Personell office on CastleStation does not have a Labor Administration Console to set jobs as high priority

**Comment by Eneocho** [comment]
It kinda fits lorewise since Castle is an independent station, so they wouldn't have a central command to request specific jobs to.

**Comment by kernikov** [comment]
Not a bug

**Comment by nervere** [comment]
The labor administration console actually came after Castle (#20847 vs. #21451), so that explains why it's not there.
However, I think most people would agree that the map should not have it, and it was probably a design choice that @I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE did not add it to the map.
