### ISSUE TITLE
AME control unit typo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33353]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
9dc2d84ba44adc17485e2ff9438e67e9ada65009

# Description
This the antimatter control unit cannot be controlled by ghosts.
# Steps to Reproduce
be ghost
find the NT AME vault
try using the control unit
perhaps it works with regular control units as well
# What you Expected
The antimatter control unit cannot be controlled by ghosts.
Alternatively:
This antimatter control unit cannot be controlled by ghosts.
# What Actually Happened
This the antimatter control unit cannot be controlled by ghosts.

**Comment by angryturnip** [comment]
Alternative:
This the antimatter control unit. It cannot be controlled by ghosts.
