### ISSUE TITLE
New pipes layering under pre-placed disposals

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#33366]
title

**Comment by nervere** [comment]
@kernikov What sort of pipes were you wrenching over the disposals pipes? I assume you mean roundstart disposals pipes by "pre-placed disposals". I'm testing this right now and I can't replicate the issue. New basic pipes from an RPD seem to be layering above the disposals pipes as they should.

**Comment by kernikov** [comment]
It was newly placed and secured layered pipes, layering under neither mapped disposal pipes.
I couldn't reproduce this issue.
