### ISSUE TITLE
Clothing stays facing forward in booth photos

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33363]
(WEB REPORT BY: confusedcactus REMOTE: 206.221.180.138:7777)
# Revision
206b1b3d19ee84d5c99ab03f52645a42ea561af4

# Description
The photo booth doesn't rotate clothes in the photos while the person rotates.
https://cdn.discordapp.com/attachments/1021568625951375413/1022979496791507015/unknown.png
# Steps to Reproduce
take a photo in the booth
# What you Expected
clothes to face the same direction as the person in the photo
# What Actually Happened
clothes still oriented directly forward

**Comment by djkramer123** [comment]
Possibly caused by #33309

**Comment by nervere** [comment]
Just tested it since the image linked doesn't include all clothing items/etc.
It seems #33309 is changing the icon states of __everything__ in an image. All clothing, stuff like floor tiles, machines, etc.
Example below, with my character facing east. Note the disfigured floor tiles, camera, light fixture, etc.

![jVWVJwHCzM](https://user-images.githubusercontent.com/26285377/192060296-3f51ba4d-8d5f-40b4-8aba-42502409e02e.png)

@DeityLink How do you feel this problem should be approached?

**Comment by DeityLink** [comment]
I'm gonna try a few things and if it doesn't work we'll just have to deal with invisible bees again. First of all I'll check if my proc that gives the direction count still works as intended.

**Comment by DeityLink** [comment]
It's pretty ironic that at some point the exact inverse problem occured with humans facing south while their clothes rotated properly. For years we hacked around this problem by forcing their clothes to face south as well.

**Comment by Kurfursten** [comment]
It's not clear to me that bees need to ever face any direction *but* south. Why not just have them reset their facing direction to south right after moving? It's a cloud of bees, it faces all directions.

**Comment by DeityLink** [comment]
that would solve the problem for bees but not other animated single-direction sprites with a non-south dir. I'd rather not do single case band-aids.

**Comment by DeityLink** [comment]
that being said.... after wasting over two hour on the matter, I've concluded that my proc was ultimately unreliable when it came to animated icons (and even many 4-direction icons don't fit the pattern I found which caused the present issue).

Looks like it'll have to be a band aid after all.
