### ISSUE TITLE
vending/lotto shoot piles of paper, without message, when shooting inventory

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#33374]
[bugfix]
vending/lotto shoot piles of paper, without message, when shooting inventory.
Appears to be about 11 pieces per volley, and I'd assume it's from the Grandslam Lotto event inventory.
![image](https://user-images.githubusercontent.com/5549060/192137512-f32b6a13-c75b-4ed5-bffd-f858847a6312.png)

**Comment by pedr69** [comment]
i thought that was intentional, instead of throwing free scratchoff tickets
it happened before the lottery was updated to be in the ticketvend

**Comment by west3436** [comment]
Feature meant to prevent free money

**Comment by kernikov** [comment]
Bloating shit loads of paper isn't a feature, and considering each volley is like 11 sheets and Pun Pun can be targeted can mean that this is just a ZAS bomb waiting to happen... shit code

**Comment by west3436** [comment]
> Bloating shit loads of paper isn't a feature, and considering each volley is like 11 sheets and Pun Pun can be targeted can mean that this is just a ZAS bomb waiting to happen... shit code

It is a feature, I made it shoot paper on purpose otherwise every vendor will just be hacked immediately. I'll look into making sprites for unprinted tickets to make it look nicer.

**Comment by Eneocho** [comment]
Keep the random paper shit please. It works great for ashing engines. Just put 3 or 4 of these aiming at a buckled monkeyman with a radsuit. The fucktons of paper get you niggawatts without the complex and overly autistic autolathe setups.
