### ISSUE TITLE
Fax Machines cannot be unwrenched when unpowered

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33379]
(WEB REPORT BY: dackjaniels REMOTE: 206.221.180.138:7777)
# Revision
95ba354dd195f2af0b7d68ccc9238255ff2fab44

# Description
Bottom Text
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by nervere** [comment]
Most of the fax machine code is pretty bad... it's using none of the machine flags and hasn't been touched in 7 years.
I took a stab at fixing it but I actually fell asleep at my desk trying to figure out how to rework the way it does power. 😊
