### ISSUE TITLE
AI eye is missing from the Haunt list

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33377]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
95ba354dd195f2af0b7d68ccc9238255ff2fab44

# Description
Looks like the Haunt list update PR didn't account for the AI.
Only the AI unit shows up on the list, not the AI eye.

**Comment by nervere** [comment]
I'll fix this once I figure out why MoMMI's and Cyborgs (or maybe something else...) are creating null / unnamed pointers in the mob list.
