### ISSUE TITLE
Screen freeze

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33385]
(WEB REPORT BY: luzha REMOTE: 206.221.180.138:7777)
# Revision
95ba354dd195f2af0b7d68ccc9238255ff2fab44

# Description
Sometimes in-game screen fails to update in time
# Steps to Reproduce
No idea
# What you Expected
Going near a locker, opening it and see it open
# What Actually Happened
Going near a locker, opening and then waiting a few seconds/moving in any direction to actually see it open. You can see it opens properly if your right click on it, seeing what's inside via menu but still seing a closed locker on your screen if those few seconds didn't pass from the moment you clicked on the locker.

**Comment by nervere** [comment]
Was the space outside the station white as well? This might just be an issue with you needing to restart BYOND and clear cache.
