### ISSUE TITLE
Pulse Demon - Black Screen after attempting to hop into a charging weapon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33391]
(WEB REPORT BY: lemonthefruit REMOTE: 206.221.180.138:7777)
# Revision
aa81ba0a5985a696425d2438f6dd034bc0d46984

# Description
As a pulse demon, if you attempt to hop into a firearm while it is on a charger, and the firearm is removed midway through the process, your screen goes black and you are unable to interact with anything.
# Steps to Reproduce
be pulse demon
enter a charging weapon
while you are taking over that weapon, have the weapon removed from the charger
# What you Expected
to get kicked out of the charger

# What Actually Happened
my screen went black and I was unable to interact with anything, basically dead

**Comment by pedr69** [comment]
kanef....
i think i tried to fix this in my pulsedemon PR but couldn't get the gun to fire

**Comment by nervere** [comment]
Fixing kanef code: **DEMON DIFFICULTY**

**Comment by nervere** [comment]
Also, I checked for runtime logs, and as you might expect he got nullspaced. Not going to add the runtime label though, since... it's just due to null values from being nullspaced.
http://game.ss13.moe/logs/2022/runtime/2022-09-27-runtime.log
