### ISSUE TITLE
Mimes can use project mind again

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#33399]
#### Description of issue
Mimes were forbidden from using project mind a few years ago, they can use it again

#### Difference between expected and actual behavior
project mind not working as a vowed mime
it works.

#### Steps to reproduce
be mime, project mind.

#### Length of time in which bug has been known to occur

Probably since whats his face changed mind shit recently.

**Comment by RedrobotAnnie** [comment]
it's true I was the culprit using it I got it via a rad storm.

**Comment by Eneocho** [comment]
Keep it in so you have a schizo reason to kill the mime ("HE SPOKE TO ME IN MY MIND!").

**Comment by adacovsk** [comment]
@Dacendeth link the PR where mimes couldn't use it

**Comment by Dacendeth** [comment]
@adacovsk https://github.com/vgstation-coders/vgstation13/pull/23180

**Comment by adacovsk** [comment]
can't reproduce this bug,

```
	if(user.mind.miming)
		to_chat(user, "<span class = 'warning'>You find yourself unable to convey your thoughts outside of gestures.</span>")
		return
```

still prevents it

**Comment by Dacendeth** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/26881007/781312b0-e9c0-4216-a3b8-820b314043f8)
STILL works.
