### ISSUE TITLE
Ghosts can let out briefcase bees!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33396]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
620cb0e8cecdd5d50478272f973333cd53fce3aa

# Description
Bee Briefcase traitor item lets the bees loose when you look inside
# Steps to Reproduce
look in the bee briefcase as a ghost
# What you Expected
nothing really
# What Actually Happened
bees got let loose ruining the punchline

**Comment by Exxion** [comment]
What do you think are the odds they also set off mousetrap assemblies? Good thing nobody has ever used those at all

**Comment by nervere** [comment]
> What do you think are the odds they also set off mousetrap assemblies? Good thing nobody has ever used those at all

Seems like it has checks for if you're either a human or a mouse. I tested it as a dead guy and as a ghost and neither worked.
Would be funny though.
https://github.com/vgstation-coders/vgstation13/blob/8641aa91af77882fe91fdfc52758b13fea66c5f3/code/modules/assembly/mousetrap.dm#L25

**Comment by Theophrastus1** [comment]
oh god not the bees
