### ISSUE TITLE
Bhangmeter crashes game

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33395]
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
620cb0e8cecdd5d50478272f973333cd53fce3aa

# Description
Not sure if its just on my end but opening the Bhangmeter caused my BYOND to go non-responsive and forced me to close and re-log. Same thing happened multiple times trying to use the console. 
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
The bhangmeter is a known client crasher, it tries loading the current map for all the valid Z-levels at once, which nukes the shitcode client.
If you do survive the ordeal (about 2-3 minutes of "crashed" client), you get a decent quality map of the area, which can be used to find some vaults/ships.
It didn't cause hell lag before (like a year or so ago), but shit happened at some point and now it's nigh unusable.

**Comment by nervere** [comment]
Personally it "works" for me, without lag, but maybe it's because it loads a zoomed in version of the map that cannot be panned or zoomed out of. (i.e. it's mostly unusable)
