### ISSUE TITLE
Fish nets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33405]
(WEB REPORT BY: autonomousgm REMOTE: 206.221.180.138:7777)
# Revision
27ea482a965dc2c47ac01aea6992b19020d0e0ec

# Description
Fish nets DO. NOT. WORK. 
# Steps to Reproduce
Use a fish net on fish tank (with lid open or closed) with fish 
# What you Expected
get fish
# What Actually Happened
No fish. i was right adam!

**Comment by adacovsk** [comment]
See #33324
