### ISSUE TITLE
Prolonged Energetic Interactions BROKEN

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33411]
(WEB REPORT BY: heroinehero007 REMOTE: 206.221.180.138:7777)
# Revision
0a6bf586f84cca1b145e82451b6c808be61cedcb

# Description
Large artifacts with the tag 'prolonged energetic interactions' do not work.  They're supposed to turn on if you put them on top of a wire with 7,500 watts (not even kw) according to the wiki.  Tried this with 2-3 and NONE OF THEM TURNED ON I AM SEEETHING HOLY FUCK.
# Steps to Reproduce
Get large artifact with this requirement.  Put it on a wire.  Watch as nothing happens.
# What you Expected
The artifact to turn on.
# What Actually Happened
Nothing.

**Comment by kacurasuo** [comment]
skill issue

**Comment by Theophrastus1** [comment]
get fucked xenoarchs
