### ISSUE TITLE
Putting a lit match into a matchbox deletes them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33421]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
0a6bf586f84cca1b145e82451b6c808be61cedcb

# Description
Putting a lit match into a matchbox deletes them
# Steps to Reproduce
light a match
put it inside the matchbox
# What you Expected
matchbox gets set on fire like norma
# What Actually Happened
atom gets deleted

**Comment by nervere** [comment]
Just tested and confirmed this. No runtime logs, but in all likelihood related to @west3436's changes to fire.

**Comment by west3436** [comment]
Matchbox probably has some snowflake code for ignition, I'll take a look at this today
