### ISSUE TITLE
AI nukeops.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#33423]
![image](https://user-images.githubusercontent.com/67024428/193428696-cf58fc79-1ce5-4d5a-8fcd-497e5489c9e8.png)

**Comment by adacovsk** [comment]
Did you still spawn as a nukeop?

**Comment by Eneocho** [comment]
I did. I am the nukeop next to the vendor. (the leader killed us with a rocket launcher)

**Comment by adacovsk** [comment]
lol, okay so no actual issues, just the message

**Comment by adacovsk** [comment]
This must be a weird edge case, where AI was already taken or something, and it reverted you to another job role, then maybe changed you to nuke op... I couldn't reproduce this issue.

**Comment by Eneocho** [comment]
> lol, okay so no actual issues, just the message

Ye. I wanted to play AI that round (had it on high priority with botanist on medium), but rolled into a nukeop.

**Comment by adacovsk** [comment]
I can only say that this does not occur with my roundstart PR

**Comment by pedr69** [comment]
what do you mean
your fucking roundstart PRs caused this
