### ISSUE TITLE
Can't get onto a Medical Malpratice that's been invisible sprayed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33420]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
0a6bf586f84cca1b145e82451b6c808be61cedcb

# Description
See title
# Steps to Reproduce
Invisible Spray a medical malpractice that you aren't currently on
# What you Expected
Click drag myself onto the space it's occupying to get onto it
# What Actually Happened
Did not get on (but I can still push it around)

**Comment by adacovsk** [comment]
try spraying it after you sit down dummy

**Comment by Eneocho** [comment]
Alt click the tile to see the invisible chair and clickdrag.

**Comment by nervere** [comment]
This isn't a bug, you're best off doing what Eneocho said. Clickdragging doesn't work with invisible stuff.
