### ISSUE TITLE
Can't superglue a toolbox, even if it's full

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33432]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
1a077b4100fc4dcc93fd4351ae939e56ce047345

# Description
it just says "The toolbox is full, make some space."

**Comment by Hinaichigo** [comment]
How should this work ideally? There are similar issues with other items that will do two actions at once.
