### ISSUE TITLE
Ninja midround spawning with actual job's stuff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33438]
(WEB REPORT BY: securitymain REMOTE: 206.221.180.138:7777)
# Revision
ddcb123be2878bd214011c0901febafdf0da936a

# Description

Pick HoS, asked to be a ninja, hit yes after a few seconds of hesitation, spawn with ID and PDA in the backpack and a sechud

No idea why

# Steps to Reproduce
Midround join as ninja

# What you Expected
Being a ninja
# What Actually Happened
Being security ninja

**Comment by Eneocho** [comment]
Security from the shadows...
