### ISSUE TITLE
Can't speak on the test serb

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#3343]
![image](https://cloud.githubusercontent.com/assets/10002997/6542059/eba5e508-c4fd-11e4-949f-75f9736d264d.png)

**Comment by dylanstrategie** [comment]
Well, the test server is dead, for one

**Comment by DrLeprikon** [comment]
Too soon, man. Too soon.

**Comment by clusterfack** [comment]
Perhaps it was a tcomms script or something? We don't really have any basis at all to fix this with absolutely no knowledge of how it ocurred nor even one step to reproduce (not to mention it wasn't even necessary running the code we are using now).

So you may want to close this.

**Comment by DrLeprikon** [comment]
I will close it, sorry I didn't earlier, but it definitely wasn't a tcomms script: the words didn't come out of my mouth at all.

**Comment by clusterfack** [comment]
No problem, thanks for the report anyway
