### ISSUE TITLE
Matchboxes turn into a pile of ash when putting a lit match inside instead of being set on fire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33447]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
db00a3872604d8751d0fa74274b13a072c96d352

# Description
Whoever """"""""fixed""""""""" the previous issue is a total retard.
The matchbox is supposed to get set on fire and burn, not instantly become ashes.

**Comment by tinysaturn** [comment]
turns out I got confused and the issue hasn't been touched yet
though I wonder how the behavior managed to change

**Comment by west3436** [comment]
#33440 fixes this already retard thanks for the double report

**Comment by nervere** [comment]
Closing as duplicate of #33421
