### ISSUE TITLE
Hologram Projector with pAIs is now broken in new and exciting ways

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33451]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
02dc0660b2225619e9886295d6cc4993555b1816

# Description
-Hologram properly inherits the pAI name BUT if the holder turns it off, the pAI reverts and goes back into the pAI device and its name becomes "pAI"
-pAI no longer has a revert button like it did before
-Going outside the projector's range just straight up kills you for good instead of going back into the pAI device
Didn't test this but I assume dying as a holoman will also kill you

**Comment by adacovsk** [comment]
Die as a hologram, die in real life
