### ISSUE TITLE
Tweak Request: Change Trader Job Outfit (in Character Select)

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#33455]
Currently when you preview a trader slot you see the default grey jumpsuit. They should be in alien robes or something similar. This also matters for the merchant license because they are in a grey jumpsuit, so it looks odd.

This doesn't affect inventories in game at all, no relation to that.

**Comment by adacovsk** [comment]
has it always been this way or is this something new?

**Comment by Kurfursten** [comment]
It has always been this way (the guy who made traders just halfassed it)

**Comment by pedr69** [comment]
same goes for silicons, you're just a guy in grey in the preview if you have AI/borg/crab set to high
