### ISSUE TITLE
NanoUI has unexpectedly stopped working

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#3347]
Gene modifiers window suddenly lost all its features and was but a blank box with the usual NanoUI background. The other modifier remained operational, thus I suspect I have treated the two machines differently. You see, at the time my personal computer was connected to a television set and the modifier's window happened to slide past the bounds of the primary screen, where the rest of Byond was working, so a portion of the gene machine's interface found itself on a completly different screen, which, I assume, might have caused it to loose its contents. Disconnecting the modifier's screen and reattaching it did help to fix the problem, so it is not a big one.

**Comment by ComicIronic** [comment]
Did you also try resending resources?

**Comment by DrLeprikon** [comment]
As in relogging? I tried that, but it didn't help

**Comment by DrLeprikon** [comment]
Oh, I didn't know about that! I'll try it if I can make it happen again!

**Comment by gbasood** [comment]
No new notes or activity or related issues afaik since march so
