### ISSUE TITLE
holo projector issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33489]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
312e12fa226036de29910d874f154c21fdcbd01c

# Description
I got inserted inside a holo projector. Mime took me out right after then tried to put me back in. It worked fine the first time, but the second time the hologram appeared but my mind was still on the card, not the hologram.
# Steps to Reproduce
Get active pAI card.
Get Holographic projector.
Slot the active pAI on the holo projector.
Take the pAI out without unsummoning the hologram.
Put the pAI inside again.
The hologram will appear but the pAI mind will still be on the pAI card.
# What you Expected
Seamless transition between holo and card.
# What Actually Happened
hologram stuCK! pAI worked fine otherwise, but couldn't hologram again.

**Comment by adacovsk** [comment]
never touching pAIs again

**Comment by pedr69** [comment]
mime here, it broke when i put you into the projector while it was in my hand
it seemed to spawn the holoman only if it got inserted into a floorprojector, or maybe something else fucked up
it didnt work even with fresh projectors
