### ISSUE TITLE
Can't access freshly purchased TraderVend as latejoin Merchant

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33492]
(WEB REPORT BY: angryturnip REMOTE: 206.221.180.138:7777)
# Revision
6bdd132a9ef1e72280013f6bb1857588fa0a8b59

# Description
I purchased a TraderVend after latejoining, and upon swiping my ID to set it up I got this message: "Access denied. Your ID doesn't match the vending machine's connected account." I'm not sure if it has to do with late joining, the fact that I'm a skeleton Vox, or something else entirely.
# Steps to Reproduce
Latejoin as a Trader and purchase a TraderVend (possibly as a skeleton vox specifically)
# What you Expected
To be able to set up the TraderVend in with my account
# What Actually Happened
Couldn't access it at all

**Comment by Kurfursten** [comment]
NAB

You must use the debit card
