### ISSUE TITLE
Toxins Launch Room Access camera is wrong

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#3350]
Camera has a bad ID. Selecting it brings you to south escape.

**Comment by Lokiamis** [comment]
while you're doing this #2380

**Comment by clusterfack** [comment]
Which map

**Comment by d3athrow** [comment]
Looks fine to me.

**Comment by d3athrow** [comment]
![toxins mass driver access](http://i.imgur.com/POhSXm8.png)
![toxins mass driver](http://i.imgur.com/VeNWnos.png)
