### ISSUE TITLE
Fire is a bit strong.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33507]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
54def9f0766fe2cd8079a19fe067073509372aaf

# Description
Set myself on fire, died like 3 seconds after.
# Steps to Reproduce
Set yeself on fire
# What you Expected
to live for longer than 3 seconds
# What Actually Happened
*deathgasp

**Comment by west3436** [comment]
set yourself on fire irl and see what happens motherfucker

**Comment by Eneocho** [comment]
I'd suffer for about 2 minutes before dying horribly. At least 2 minutes, not 3 seconds.

**Comment by west3436** [comment]
What were you wearing and how did you set yourself on fire?

**Comment by Eneocho** [comment]
Clown suit, mask and shoes. I lit a cigarette. Dropped it, lit another, dropped it. This set the tile I was on fire. I died 3 or 4 seconds later.

**Comment by west3436** [comment]
Were you standing on the fire tile or did you catch on fire, step out of it, then die? Standing on a fire tile absolutely fucks you up now as it should. If you're standing in an actual fire you will die after a few seconds. You should have a minute or so of being on fire before you die in normal clothing as long as you're not on a fire tile.

**Comment by Eneocho** [comment]
I stood in the tile for about 2 seconds, managed to get out of the tile, died instantly after.

**Comment by BomberBro** [comment]
With the way fire is buffed it's kind of dumb that a pie tin or a cigarette butt can turn you crispy.

**Comment by west3436** [comment]
> With the way fire is buffed it's kind of dumb that a pie tin or a cigarette butt can turn you crispy.

The sources of fire certainly need to be reworked entierly as do the fire heating mechanics, but I don't think that is necessarily tied to this.

**Comment by Eneocho** [comment]
Forgot to mention that the first cigarette was out, so the second one lit it as it would lit garbage.
