### ISSUE TITLE
Occasional Hangs/Crashes

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#33514]
#### Description of issue
It seems like in the last month or so I've been getting occasional freezes which either resolve in about 10 seconds or I have to restart the client. It doesn't seem to happen in any particular situation that I'm aware of, but seems somewhat random.
I'm not sure if this is happening to anyone else or if it's just my particular Wine setup or something, but I figured I'd make an issue and see if it's happening to anyone else.

#### Length of time in which bug has been known to occur
Two or three weeks at least.

#### Server revision

[bugfix]

**Comment by jwhitak** [comment]
Try to catch the bugs with the profiler if you can, just for more info. I've not had this issue myself, but I'm rollin' windows.

**Comment by Hinaichigo** [comment]
How can I do that?

**Comment by jwhitak** [comment]
Local server unfortunately...

**Comment by adacovsk** [comment]
You should be able to see your client profiler

**Comment by adacovsk** [comment]
it would be nice to have access to it for the server for us lowly peons too though since we're the ones that could fix issues

**Comment by Hinaichigo** [comment]
This might just be me using up my RAM.
