### ISSUE TITLE
Castle Station Setup Character not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33517]
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
3a65018cd7c03a75cf34870b2e664d9bd567ced4

# Description
When in the pre-round lobby for Castle Station you cannot select Setup Character, the character window does simply not appear at all.

**Comment by ValkyrieSkies** [comment]
I believe this issue has something to do with having security set as your highest priority job (or possibly at all). Was this the case with your default slot?

**Comment by pedr69** [comment]
it's security or silicons
probably has something to do with the fact there's no security nor silicons on castle
