### ISSUE TITLE
Halligan issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33516]
(WEB REPORT BY: poales REMOTE: 206.221.180.138:7777)
# Revision
3a65018cd7c03a75cf34870b2e664d9bd567ced4

# Description

1. You can use the halligan on doors that have been hacked open, and it will try to open them again
2. If you halligan a door with no power, it still says it's struggling with the motors, like using a crowbar on a powered airlock. It really should just open it like a normal crowbar

**Comment by west3436** [comment]
1. I'll add this to the open PR.
2. This is fixed in #33503.
