### ISSUE TITLE
Syndicate Walls (like on the pocket sat) Have icon_state = null

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#33518]
Makes them solid black. What broke it?

**Comment by Kurfursten** [comment]
Tested this a bit more and they seem to be a wall smoothing issue. If you place new walls nearby it fixes the sprites

**Comment by WindowsErrors** [comment]
[yea but i like it](https://github.com/vgstation-coders/vgstation13/issues/32129)

**Comment by nervere** [comment]
Gonna close this one in favor of #32129 as that one has screenshots. I've noted in the older issue that this seems to be a wall smoothing issue.
