### ISSUE TITLE
being on fire causes agony/pain even when in a hardsuit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33511]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
d470ad71272d70468ddffbcb9b5cbd0e3e5521ef

title

**Comment by west3436** [comment]
Figured this might happen - will fix tomorrow

**Comment by jwhitak** [comment]
What hardsuits specifically? Not all hardsuits are immune to fire/heat. In fact, even the Atmos hardsuit isn't immune to extremes.

**Comment by pedr69** [comment]
good.
let the rig babies cook
