### ISSUE TITLE
No kill like overkill.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#33525]
![image](https://user-images.githubusercontent.com/67024428/195957086-be5d8a30-916b-4ef8-a16e-e86cf819b129.png)
No idea how this came to be.

**Comment by Exxion** [comment]
Did you get someone to VV it?

**Comment by Eneocho** [comment]
Nope. My first guess was that the brute damage was actually 202.1230000000(1) but the crew monitor simply didn't show the period.

**Comment by Eneocho** [comment]
> Nope. My first guess was that the brute damage was actually 202.1230000000(1) but the crew monitor simply didn't show the period.

Tested this. It aint it. The machine does not display decimal values at all.

**Comment by nervere** [comment]
Not really any way to determine what caused this and from what you said, it seems like this reading on damage was accurate (?) anyway.
