### ISSUE TITLE
A different pAI hologram death bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33526]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
f1449b01ab0df1f477df3664e23b0bd9b8ec0192

# Description
Dying as a pAI hologram doesn't seem to drop your equipped items, so if you're carrying yourself in a bag or some other container, dying will get your items deleted including the hologram projector with the pAI device inside.

**Comment by adacovsk** [comment]
@nervere you can close this now
