### ISSUE TITLE
Hologram Projector dying as pAI hologram bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33524]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
f1449b01ab0df1f477df3664e23b0bd9b8ec0192

# Description
Dying or running out of range as a pAI in a projector makes it impossible to become a hologram again.
If someone tries to make you a holoman again, the projector will spawn an empty holoman with you staying in the pAI device instead of being put inside the holoman

**Comment by Eneocho** [comment]
Duplicate of #33489.

**Comment by nervere** [comment]
Closed as duplicate per Eneocho's comment.
