### ISSUE TITLE
Scythe robot waits for death animations on powercreep

### ISSUE THREAD

**Issue by kacurasuo** [d3athrow/vgstation13#33533]
[consistency]

#### Description of issue
just fucking annoying cutting powercreep with the scythe robot because it stalls for the full death animation of the powercreep for each tile that it cuts before continuing, while every other vine it just slices it

i'm certain it's because there's a sleep or something similar in the powercreep death, can probably fix it with some flag

#### Difference between expected and actual behavior
should really just cut it the same way that it cuts every other vine
I'm pretty sure this is unintended behavior

#### Steps to reproduce

just grow a big field of powercreep and stand in the middle with your scythe ripley and fire it off, it starts off amusingly slow but then you gaze upon the fucking field left to cut

**Comment by pedr69** [comment]
the powercreepers are the only thing that's easy to clean up without a scythe
since you only need one wirecutter hit to cut them

but yeah, encouraging ripleys not used exclusively to drill lockboxes is good, someone pls fix

**Comment by Dacendeth** [comment]
I tested this and it is so bad how slow it is.
