### ISSUE TITLE
Tertiary Language Missing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33534]
(WEB REPORT BY: sootybear42 REMOTE: 206.221.180.138:7777)
# Revision
818655be802930da64d449b860d46051cfa34cc4

# Description
Unable to use selected Teriary language.
# Steps to Reproduce
Try to speak Tradeband, Can't.
# What you Expected
To speak Tradeband.
# What Actually Happened
Said ":2"shit."

**Comment by Eneocho** [comment]
I've had this issue too. I was unable to speak tradeband, but did know galcom and solcom.

**Comment by kernikov** [comment]
Did you check the in game "Known languages" button?

**Comment by Eneocho** [comment]
I did. It was not there. I was not a clone (if that matters).
I blame one of the recent code reworks.
