### ISSUE TITLE
toggle darkness hides ghosts again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33558]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
f95717219b11a8c213df3cba84c2746a2e5e6f41

just thought you all should kno

**Comment by pedr69** [comment]
all ghosts?
couldnt test because lowpop but it didn't hide my sprite

**Comment by Exxion** [comment]
Apparently, toggling darkness to fully off hides all ghosts except your own. They're perfectly visible with darkness either partially or fully on.

**Comment by pedr69** [comment]
mmm, nothing like some unforeseen consequences #33052
