### ISSUE TITLE
Pull Request: Cricket Meat Food

### ISSUE THREAD

**Issue by pulserider** [d3athrow/vgstation13#33553]
i buy a cricket farm for the price of 80 credits from a vox trader
i then set it up in my backroom. the flour is nice, and the meat is neat, but
i can't use cricket meat for any recipes. it doesn't work with normal meat recipes. as far as i know, it has no recipes attached to it

please.. let me become the gunk chef i always dreamed of..

**Comment by Eneocho** [comment]
Weird. It should work. The path is /obj/item/weapon/reagent_containers/food/snacks/meat/cricket, so it should inherit from meat and work on meat-based recipes.

**Comment by pulserider** [comment]
> Weird. It should work. The path is /obj/item/weapon/reagent_containers/food/snacks/meat/cricket, so it should inherit from meat and work on meat-based recipes.

I also could've just fucked up the complicated recipe of 5 flour and 1 meat. Which, is very possible, with me.

**Comment by Eneocho** [comment]
Tested it. The 5 flour 1 meat recipe does not work properly, but other recipes such as the sliders, meat pie, donut burger or big bite burger do work as intended.
Issue is that the recipe calls for /obj/item/weapon/reagent_containers/food/snacks/meat/animal, but cricket meat (and roach meat) are not children of meat/animal, so the recipe fails. Easy fix, honestly.
You can either make a new recipe for cricket/roach burgers or change it so their meat is under meat/animal.
