### ISSUE TITLE
arcane tampered doors dont open

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33566]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
e786e3d6719b42fd0cf806c1403ce535b76fd7bc

they just make a really loud opening sound.
Also why the hell can't this spell's cooldown be upgraded past 20 seconds? Its nigh useless.

**Comment by SECBATON-GRIFFON** [comment]
is it really that useless? i'm always open for more stuff to add to it

**Comment by Eneocho** [comment]
It's less about the effects and more about the delay. One tamper every 20 seconds is extremely slow if you go full Tamperwizard since you barely have enough points to get a utility spell for survival, which means no secondary combat spells while you wait for ye tamper to recharge.
