### ISSUE TITLE
scrubbers STILL broken on roid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33565]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
e786e3d6719b42fd0cf806c1403ce535b76fd7bc

#33426 dindu nuffin

**Comment by kernikov** [comment]
What and where

**Comment by pedr69** [comment]
the pipenet is perpetually on 0kpa, 0 kelvin
the scrubbers turn red when they try to suck any gas, so by the end of the round half of the station's scrubbers were red
