### ISSUE TITLE
Gallons of PCP come empty by default

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33570]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
e786e3d6719b42fd0cf806c1403ce535b76fd7bc

# Description
>order contraband
>get many gallons of PCP to sell for profit
>THE GALLONS ARE EMPTY EGGMAN

**Comment by pedr69** [comment]
that's odd, bottle.dm didn't get updated recently
and it works on my (slightly outdated) copy of the repo

**Comment by jwhitak** [comment]
Not sure why. It happened ingame after ordering 3 contraband crates. All the PCP jugs inside were empty... though, we didn't notice until they were put into a custom vending machine. That might be related....

**Comment by Eneocho** [comment]
That's most likely it.

**Comment by Eneocho** [comment]
Tested it. That's exactly what happened. @nervere, you can close this one.

**Comment by jwhitak** [comment]
Yeah, that would do it. The bug still exists, but it's a "you can't load custom vendors with open splashable containers" and not a "Gallons of PCP are empty".

**Comment by pedr69** [comment]
containers have lids, so it seems like a skill issue to me

**Comment by jwhitak** [comment]
Needs a splashable() return false proc to the vending machine. Most machines have this flag.
