### ISSUE TITLE
Plants with 'self harvesting' trait, don't self harvest

### ISSUE THREAD

**Issue by kernikov** [d3athrow/vgstation13#33597]
[bugfix]

**Comment by adacovsk** [comment]
@Eneocho please confirm

**Comment by Eneocho** [comment]
Can confirm, tested with gelthi and it didn't self harvest.

**Comment by adacovsk** [comment]
So not a problem with mutations...

**Comment by Eneocho** [comment]
You can't mutate self harvest as far as I can remember, you can only splice it.

**Comment by adacovsk** [comment]
Ahh probably right
 Any runtime?

**Comment by Eneocho** [comment]
Seems not.

**Comment by Eneocho** [comment]
@adacovsk 
Recompiled my localhost, it works. There's a considerable delay however. You must wait a full production cycle for the self-harvest to happen, which can be a lot for certain splices, during which you can manually harvest the plant.
Before the reworks, if a plant had self-harvest it would harvest automatically the moment it could produce. In effect you could never manually harvest it.

**Comment by kernikov** [comment]
So the bug exists still, because that's effectively useless compared to "it just harvests when it's ready" which is the intended behavior
