### ISSUE TITLE
Bagulooses are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33608]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
ceabfa45754a49f4c8bfe158c89192a0a6e8a23e

# Description
they don't happen anymore
# Steps to Reproduce
* get bag of holding
* put into another
# What you Expected
singulo
# What Actually Happened
infinite bag nesting

**Comment by Eneocho** [comment]
Where did you bagulo?

**Comment by Theophrastus1** [comment]
I wonder who could be behind this
