### ISSUE TITLE
Setup Special Roles doesn't work

### ISSUE THREAD

**Issue by chainsauce** [d3athrow/vgstation13#3360]
In the preference tab, the command setup special roles doesn't seem to work. It can open and change options correctly, but the submit button does nothing, essentially making the whole thing worthless. This makes it so that you can't change your antag options in game, sort of annoying if you normally have, say, alien turned off and then want to be an alien for a round.

**Comment by CptWad** [comment]
In round or during set up?
I know the way around it is just clicking on the object you want to turn into (Xeno, runes, posi, dioane)

**Comment by chainsauce** [comment]
Huh, it works now. Well I guess that's case closed? Also, it was during the round.
