### ISSUE TITLE
New Scrubbers and Unary Vents not linking to air alarms

### ISSUE THREAD

**Issue by AnonymouxRex** [d3athrow/vgstation13#3361]
While trying to rebuild the derelict's atmospherics system, I attempted to add an air alarm, unary vents and scrubbers to Derelict Atmospherics and the air alarm didn't recognize the new vents and scrubbers.  Even attempting to change the order the system is constructed (whether air alarm first or scrubbers/vents first) doesn't fix the issue.

**Comment by CptWad** [comment]
I had this happen on station but I think it had something to do with the fact that I turned a few rooms into one. Areas tend to fuck up if you don't do them properly.

**Comment by SkowronX** [comment]
This is an apc problem likely.

**Comment by SkowronX** [comment]
Zoning/apc problem?

**Comment by CptWad** [comment]
@SkowronX It might be either or both.

**Comment by AnonymouxRex** [comment]
I didn't modify the layout of Derelict Atmospherics except to make it airtight so I could pump air into it...  The unary/scrubber problem didn't kick in until recently.

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/commit/12a9afe02269dfa6a7257b6e2a03cb22d1243f55
