### ISSUE TITLE
[Feature Request] Creatine Crickets

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#33618]
I was showing off my pet cricket to an assistant and she asked if you could creatine the cricket like you can with mice. This spawned the idea of Creatine Crickets, essentially, the cricket version of mutated cockroaches, made by exposing crickets to Creatine, which BUFFS THEM HARD, maybe with some special "JUMP" mechanics to compensate for the complete lack of breeding.
[featurerequest]

**Comment by SECBATON-GRIFFON** [comment]
still more of a fan of using radium on them like cockroaches

**Comment by Eneocho** [comment]
<s>You can use radium on your roaches? I've always used mutagen.</s>
Checked, you can only mutagen.
