### ISSUE TITLE
Unable to Remove Frequency Names with Special Characters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33622]
(WEB REPORT BY: wentafk REMOTE: 206.221.180.138:7777)
# Revision
232bf6be18242e194192fb796df92aad9632715f

# Description
What it says on the tin. Add a frequency name to a radio server such as zalgo text(tried) and possibly other text
# Steps to Reproduce
Add zalgo frequency name
# What you Expected
It to apply
It to work
Be able to remove it without complicating it
# What Actually Happened
It says the frequency name is removed but it stays there clogging up the server menu. It otherwise works perfectly fine and can be changed through messing around the frequency list. DO NOT REMOVE THE ABILITY TO DO THIS CODERS, I'LL COME TO YOUR HOUSE.

**Comment by nervere** [comment]
pretty sure i fixed/limited the scope of this issue in [33819]
