### ISSUE TITLE
fulltile windows no longer connect when anchored

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33623]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
232bf6be18242e194192fb796df92aad9632715f

directional ones still connect, and the premapped fulltiles are connected
building two fulltile windows and anchoring them won't link them together though

**Comment by pedr69** [comment]
un-anchoring a premapped, window will unlink it and its neighbors, as it should
re-anchoring it however, will connect the other premapped windows to itself, but not itself to the other windows

**Comment by SECBATON-GRIFFON** [comment]
i have no idea why it's doing that, been looking at the code and it SHOULD work
