### ISSUE TITLE
Science fabricators break sometimes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33624]
(WEB REPORT BY: assmops REMOTE: 206.221.180.138:7777)
# Revision
232bf6be18242e194192fb796df92aad9632715f

# Description
A player ahelped stating that the protolathe and robotics fabricator in RND stopped producing things despite having the resources availabe. Tried manually printing a powercell as an adminghost, and it seemed like it was stuck producing something without actually making anything. The player tried both wrenching and unscrewing it, but couldn't, due to it technically making something. I deleted the protolathe and resynced, which seemed to fix it.
# Steps to Reproduce
They queued 40 of each high end part; bluespace bins, super capacitors, ultra lasers, pico manipulators, and phasic scanners
# What you Expected
To have 40 of each part
# What Actually Happened
The protolathe stopped producing parts partway through the scanning modules

**Comment by DorainGrey** [comment]
Can confirm I had this issue recently as well, seems like something recent.
@gurfan managed to fix it somehow.

**Comment by NigglyWiggly** [comment]
I’ve also had this happen; I tried to print a quick Durand queue, and it just refused to actually start printing despite having all the materials, I printed a quick Odysseus, and after that I went to try again and the Durand parts printed just fine.
Possibly an entirely unrelated issue, but who knows

**Comment by Eneocho** [comment]
Had this issue as well. It fixed itself when I manually printed something and reset the queue. Kicking the thing fixed it as well (had it happen more than once).

**Comment by pedr69** [comment]
i think it's separate from the queue breaking
his protolathe refuses to print, can't insert any mats, can't screw it open, and unlinking and relinking it through the console does nothing

it also only seems to happen to one guy so he should probably make a bugreport and explain just what exactly he's doing wrong
