### ISSUE TITLE
Roid's cold AI casket

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33627]
(WEB REPORT BY: valkyrieskies REMOTE: 206.221.180.138:7777)
# Revision
232bf6be18242e194192fb796df92aad9632715f

# Description
VEERS THE AI LOCKDOWN BUTTON ON NEW ROID AI CHAMBER DOESN'T WORK

**Comment by nervere** [comment]
I wrote this down last time I played Roid AI and forgot to fix it. I'll get to it now.

**Comment by nervere** [comment]
w...t...f....
