### ISSUE TITLE
Quick Equip and held storage items.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#33628]
It's really makes holding a toolbox suck. I like everything else #33579 did but that little addition just isnt enjoyable, I know at least two other people said they didnt like it but i'm not sure if we're in the minority here or not.

**Comment by Kurfursten** [comment]
I don't like it either. When you start shift as CE and want to move tools to your CE belt you have to drop your old belt on the ground so that items will go into your belt belt instead.

**Comment by pedr69** [comment]
yeah it needs some tweaks
it should prioritise clothing slots if they're empty over the inhand container

**Comment by Kromkar** [comment]
Please just remove the items into container part entirely it's very unenjoyable

**Comment by Dacendeth** [comment]
I feel like if it was moved to the priority just above a backpack it would be perfect, so it would try to go everywhere else first and then a held container if possible, and backback if it cant go there.

**Comment by SECBATON-GRIFFON** [comment]
> I feel like if it was moved to the priority just above a backpack it would be perfect, so it would try to go everywhere else first and then a held container if possible, and backback if it cant go there.

noting the feedback here, will probably make it like this. thanks
