### ISSUE TITLE
bugs cant bite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33630]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
232bf6be18242e194192fb796df92aad9632715f

i turn on bite intent, but it just keeps turning off automatically!

**Comment by nervere** [comment]
@gurfan what kind of bug were you for this

**Comment by gurfan** [comment]
Probably just me not realizing I had a mask. Id close this
