### ISSUE TITLE
Screwsolder doesn't work when building mechs (or atleast the ripley)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33641]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
1010faef3bf6f4aa21de6a2f4a22fe3ab4057b63

# Description
Screwsolder CE tool doesnt work to screwdrive the mech when building it
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by kernikov** [comment]
Duplicate of : #33410
