### ISSUE TITLE
Drink "Pintpointer" pouring spawns extra glasses for each ingredient, generally buggy behavior

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33643]
(WEB REPORT BY: securitymain REMOTE: 206.221.180.138:7777)
# Revision
1010faef3bf6f4aa21de6a2f4a22fe3ab4057b63

# Description
I mixed a bunch of drinks in a cauldron to eventually reach the pintpointer, when I then removed the mixture (which was like 90% pintpointer and random junk) to pour it into drinks, pouring it into a glass spawned EACH ingredient in the right amount in a glass under my feet.
JUST pouring the pure pintpointer into another glass also drops both the pintpointer and the glass at my feet.

# Steps to Reproduce
Pour pintpointer into anything. To pour pintpointer into a glass together with other ingredients you may have to use a cauldron like I did

# What you Expected
Getting some pintpointer to drink and behave like other drinks when pouring

# What Actually Happened
Glass duplication glitch, free chem splitting

**Comment by Eneocho** [comment]
Duplicate of #24099 and #25260.
