### ISSUE TITLE
Upgraded microwaves say "Food Spawner" when making sushi.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#33656]
Affects all food spawner subtypes, such as candy hearts.
![image](https://user-images.githubusercontent.com/67024428/200232764-108e5a53-1e44-445e-b636-17b50b55a8f5.png)

**Comment by pedr69** [comment]
dear god your font rendering

**Comment by Eneocho** [comment]
> dear god your font rendering

Its the default config on localhost.

**Comment by pedr69** [comment]
well uhh it seems my default config looks less shit
![image](https://user-images.githubusercontent.com/18052467/200458963-a1f8bb1a-3b5d-4994-8d69-0763e3d56649.png)
