### ISSUE TITLE
wizard arcane tamper'd doors make nervegas

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33655]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
739cc912c452e0015fc86d44a604fe8e96a34fc7
some of them straight up refused to open
and somehow the shuttle got delayed for 4 minutes

keep the across-zlevel teleport though it's funny

**Comment by NigglyWiggly** [comment]
The shuttle got delayed because the arcane tamper broke the Master Controller and we had to manually move the shuttles

**Comment by Eneocho** [comment]
>wizard so powerful the round can't end
based

**Comment by DorainGrey** [comment]
Important to note, that this spell also regularly teleports you out into space randomly, also into the bridge walls. There should be a whitelist of airlocks types to prevent this. 
Also some indication that the door is tampered would go a long way.

I don't believe the blessing with holy water worked either, I sprayed some on the door and nothing changed.

**Comment by Killette2** [comment]
The magic that round was so powerful that it stopped kudzu from growing
