### ISSUE TITLE
frying pan does not update when removing an item via inhand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33660]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
739cc912c452e0015fc86d44a604fe8e96a34fc7

# Description
title
# Steps to Reproduce
cook something (5u flour will do)
use pan in hand
# What you Expected
icon updated to empty pan
# What Actually Happened
ghost spaghetti

**Comment by Hinaichigo** [comment]
I'm guessing this occurs when you have full hands and it goes onto the floor right?

**Comment by Eneocho** [comment]
ye
