### ISSUE TITLE
Microwave eats ingrediants while cooking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33671]
(WEB REPORT BY: knife28 REMOTE: 206.221.180.138:7777)
# Revision
a6c103ac98140c889bdda64fe406463c67ddba9c

# Description
Items can still be placed in microwaves while they are activated and 'cooking'. These items then disappear.
# Steps to Reproduce
Turn microwave on, put in food, watch it disappear
# What you Expected
Either have it pre-load food in the microwave like it used to, or not allow food to go in while its cooking
# What Actually Happened

**Comment by Hinaichigo** [comment]
How long has this been occuring?
