### ISSUE TITLE
[Bug] Emitters don't require power once turned on.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3368]
This is bad.  Once an emitter has been powered on, it will stay on forever until it's turned off or destroyed.  

Get a wire with power and set up an emitter like it should be done.  Cut the wires leading to it and even directly underneath it.  Watch as it laughs at you.

![ss 2015-03-09 at 02 26 47](https://cloud.githubusercontent.com/assets/8550416/6561689/91c2b8f0-c669-11e4-8050-d6694a60d8c3.png)

You can even turn it on and off without it caring about needing a power source.  http://a.pomf.se/yzqayz.webm

@PJB3005 suggests its a powernet issue and not one inherent to emitters.  I don't know the reason why this happens, but I do know it's a pretty bad oversight.   

N3X15 agrees its a powernet issue.

**Comment by PJB3005** [comment]
yes, probably related to powernets directly, see #3266

**Comment by utilitas-** [comment]
Doesn't it have an internal battery? I assumed so when I set down emitters on the Derelict without any power sources nearby, just a single wire. The emitters would turn off after about 15 minutes.

**Comment by PJB3005** [comment]
it doesn't, must be the powernet updating or something, but i'm 100% sure they don't have internal batteries

**Comment by Probe1** [comment]
@dylanstrategie said in irc that the little blurb on the wiki about having 'internal batteries' was handwaving the bug, and it's been fucked for a very very long time.
