### ISSUE TITLE
(Discussion) Reincarnating with another character slot

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#33696]
[discussion]
I've been thinking it might be nice if you could rejoin the round as another one of your characters if a certain amount of time had passed since you first joined, say 4 hours or so. It could also be based on time since you were last alive as one of your previous characters (so as to not count midrounds and stuff, or maybe it should also count midrounds or any form of incarnation) to prevent simply suiciding and getting a new body right away. I was thinking this being on-or-off as well as the timer could be configurable, and maybe it would only be an option during dynamic (or maybe that could be a config option too). I was thinking of also making the option unavailable to observers, but maybe that could be addressed in a more suitable way. What do people think of this concept?

**Comment by Kromkar** [comment]
I have seen this done on other servers. Usually the timer is 20-40 minutes. 

How would players using ghost knowledge best be handled? I know that is an administrative issue and not a feature issue, but it should be considered when discussing this.

**Comment by Kurfursten** [comment]
I believe that if you are fully offline for 30 minutes (completely disconnected), when you return, it should return you to the lobby screen. I feel that after one half hour you essentially have no idea what the current state of the shift is like. If your old body is still alive, you could have an option to rejoin as that body instead.

This would not be so much for getting observers back into the shift as a way for people to rejoin a shift if they died 15 minutes in, left to do something else, and found the round still going 45 minutes later. Or in omega-length deadpop hours shifts mid night.

**Comment by Eneocho** [comment]
Rejoin as the same body. Could be RP'd as centcomm sending a clone to the same station by mistake.

**Comment by tinysaturn** [comment]
the traitor he kills me but i respawn

**Comment by Exxion** [comment]
>Rejoin as the same body. Could be RP'd as centcomm sending a clone to the same station by mistake.

The game definitely shouldn't let you rejoin with the same character slot, but I guess there's nothing stopping you from copying the same character to another slot. I guess this is OK as long as you don't use metaknowledge? I don't like it, but I don't think it breaks any rules?

**Comment by adacovsk** [comment]
> > Rejoin as the same body. Could be RP'd as centcomm sending a clone to the same station by mistake.
> 
> The game definitely shouldn't let you rejoin with the same character slot, but I guess there's nothing stopping you from copying the same character to another slot. I guess this is OK as long as you don't use metaknowledge? I don't like it, but I don't think it breaks any rules?

You can't join with the same name anyway

**Comment by Exxion** [comment]
>You can't join with the same name anyway

What do you mean? We're not talking about a feature that currently exists

**Comment by SonixApache** [comment]
> > You can't join with the same name anyway
> 
> What do you mean? We're not talking about a feature that currently exists

https://github.com/vgstation-coders/vgstation13/blob/84cfef43cbbc6937a8e930c16c56e56f5cb47056/code/modules/mob/mob.dm#L1266

**Comment by Exxion** [comment]
OK I knew the respawn verb existed but I thought we were talking about a new feature rather than just enabling and tweaking it for some reason

**Comment by ManopolisJones** [comment]
I don't know, I figure with the advent of space hobos, diona and the like, we got enough ways to get players into the round without resulting to player re-spawns of all things.

**Comment by west3436** [comment]
Discussion was held, merry times were had, and Hina left the server
