### ISSUE TITLE
Shift-end shuttle can't be recalled

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33691]
(WEB REPORT BY: cartlord REMOTE: 206.221.180.138:7777)
# Revision
2265716742e126c8a45e4a7c78381c38e51fa6df

# Description
The emergency can't be recalled if it auto-calls at shift end
[bugfix]
# Steps to Reproduce
Spend eight hours in a round, have the shuttle autocall, push the recall button
# What you Expected
Shuttle recall
# What Actually Happened
Shuttle did not recall, timer kept going, no feedback. Shifty_rail had to recall it.

**Comment by Eneocho** [comment]
Requesting that you get paid extra per quarter if the crew stays after the shift end.

**Comment by ShiftyRail** [comment]
Cannot even get it recall by admins, you need to move it to centcom without triggering the countdown.

**Comment by nervere** [comment]
Closing this as the "feature" has been reverted.
