### ISSUE TITLE
[Feature Request] Temperature valves? Conditional valves?

### ISSUE THREAD

**Issue by jellyveggie2** [d3athrow/vgstation13#33709]
[featurerequest][discussion]

I'll start by relaying this feature request I saw on the forums:
>"_I would love some temperature valves similar to the pressure ones that would allow it to open or close once the connected pipe exceeds or drops below a certain temperature._" - falcon2346

For starters I'd like to gauge how much interest there is in temperature valves and potentially other kinds of conditional valves. I'd like to keep the number of conditional valve types to a minimum (something like a gas type valve can be done already without too much fuss using a pressure valve and a gas filter) but still, suggestions welcome.

That said, my main concern is implementation: Should there be entirely new conditional valve devices bloating the RPD's list, or should the pressure valve become an universal "conditional valve" instead, where you can set what parameter to check against through the valve's menu?
The later would mean figuring out ways to visually determine what mode (pressure, temperature, whatever else) a conditional valve has been set to, probably through relatively minor sprite differences, while the former option would allow for visually distinct sprites at the cost of bloating the RPD's list. 
...Which might not be that much of an issue if it's just the temperature valves for now, I suppose?

I don't know. Any ideas on this whole thing are welcome.

-- 

New points of discussion raised so far:
* In relation to RPD bloat concerns, the RPD's list could use some TLC, such as  tidying up the categories or creating dropdows.
* Possible additions to conditional valve behaviour in general. Suggestions so far: Ability to compare the control against the input pipe, rather than just the constant.

**Comment by CrazyAmphibian** [comment]
the automation console just refuses to work for me, so being able to have conditionals without a dice roll on weather or not the console will work is definitely good
i don't really see a use for checking anything other than a pipe's pressure and temperature (maybe mols?), so keeping them as two separate objects woud probably be fine
i could see either implementation working just fine. muscle memory can adapt to the new list.

**Comment by Kurfursten** [comment]
Are you sure you can't use it now? You should have been able to use the automations console for a month now (the console can't be used by new players). Check again if you are still having issues.

**Comment by Eneocho** [comment]
While you can replicate that behaviour with pipe meters and digital valves, dedicated temperature and conditional valves would be awesome.

**Comment by falcon2346** [comment]
I personally hate using the automation computers since it takes ages to do things if you're not building your scripts in advance so I'm all for this (obviously, I requested it). I don't see further bloat to the RPD really being an issue since there are already 44 pipe pieces, I seriously doubt a 45th is going to cause problems.

Conditional pipes would be much neater though. I imagine you could effectively communicate the setting it's on with an extra light on the valve. Yellow for heat, blue for pressure, black for if it's operating like a standard valve, something else for whatever might get added in the future.

**Comment by CrazyAmphibian** [comment]
i think another addition to conditional valves that would be good is to allow comparison between the control pipe (the one that is used for the conditional check) and input pipe (the one that is opened to the other side) instead of just between the control pipe and a constant.

**Comment by Eneocho** [comment]
On the meantime you can hook that up with scripts. Once you learn scriptomancy you can do nearly anything.
Off the top of my head it'd be: Pipe meter on control pipe, pipe meter on input pipe, digital valve on the input pipe.
IF variable
Pressure/temperature/ on METER 2 
above pressure/temperature on METER 1
THEN
digital valve OFF

**Comment by jellyveggie2** [comment]
Quoting some of the thread's replies so they're not forgotten about:

[No. 407841627](https://arch.b4k.co/vg/thread/407572364/#407841627)
>[>>407832253]()
>these sound neat
>AAC can already do this, but to make new scripts it's absolute hell
since you can read sensors via AAC and compare them to stuff, but not actually see the value you read
>
>and yeah, the RPD menu is very cluttered already, i'm not sure how it could even be fixed?
([image](https://arch-img.b4k.co/vg/1668806469412.png), image suggests moving valves into a category of their won, and thermal plates into the Heat Exchange category)


[No. 407842149](https://arch.b4k.co/vg/thread/407572364/#407842149)
>[>>407841627]()
>Can devices not use drop-down menus or whatever? I vaguely recall a few menus with them.

(I do believe [No. 407833592](https://arch.b4k.co/vg/thread/407572364/#407833592)'s reply is CrazyAmphibian's, so no need to repeat it here in full unless he claims otherwise).

**Comment by falcon2346** [comment]
Having a drop down to select a specific category (devices, pipes, HE) would be wonderful since I typically only find myself working with one type at a time anyways. That would definitely reduce the amount of scrolling necessary, especially for HE.

**Comment by Eneocho** [comment]
> Having a drop down to select a specific category (devices, pipes, HE) would be wonderful since I typically only find myself working with one type at a time anyways. That would definitely reduce the amount of scrolling necessary, especially for HE.

I could whip up a couple AAC scripts for the wiki now that I think about it. Mostly utility for quick copypaste.

**Comment by pedr69** [comment]
![image](https://user-images.githubusercontent.com/18052467/203088066-371873cc-0796-4900-9300-cd8d6c2c42ad.png)

gas-powered circuits when?
would a mommi piping down a CPU and running an AI on it break its non-interaction law?

**Comment by Kurfursten** [comment]
In the universe of our game, an AI is a being because it runs on a brain or posibrain, which are more sophisticated than a simple CPU because they run on soul tech. MoMMIs are allowed to use soulless computers.
