### ISSUE TITLE
Black box screen overlay after self-deleting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33711]
(WEB REPORT BY: confusedcactus REMOTE: 206.221.180.138:7777)
# Revision
7e36d84767d0cd0c3ab9df2d94b7751ca352e16a

# Description
After deleting a mob you were in control of, you have a black overlay not unlike wearing a welding helmet that doesn't go away unless you toggle darkness on and keep it that way. It lasts until I relog.
# Steps to Reproduce
Control person, delete person while still in them
# What you Expected
to be able to see shit
# What Actually Happened
weird black overlay

**Comment by adacovsk** [comment]
can't reproduce

**Comment by Exxion** [comment]
What client version? If 515, don't use 515

**Comment by ConfusedCactus** [comment]
To elaborate further after further testing, the black box overlay first appears when I use the spawn myself as a test dummy button. I don't know why it happens in the first place, but it also still doesn't go away if I ghost out or delete the mob. My byond version is 514.1581

**Comment by adacovsk** [comment]
Still can't reproduce. I'm using 514.1589

**Comment by Hinaichigo** [comment]
What OS/VM setup are you using?

**Comment by west3436** [comment]
Unable to reproduce.
