### ISSUE TITLE
Derelict Gas Miners are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33717]
(WEB REPORT BY: luzha REMOTE: 206.221.180.138:7777)
# Revision
7e36d84767d0cd0c3ab9df2d94b7751ca352e16a

# Description
C*ders fixing what wasn't broken: Gas Miners on Derelicts are not producing gas anymore.
# Steps to Reproduce
Play Derelict MoMMI and head straight to Derelict Atmos.
# What you Expected
Gas being produced.
# What Actually Happened
It wasn't, despite being functional and operating at rates higher than 0 kPa when examined.

**Comment by Kromkar** [comment]
Repoban adacovsk when

**Comment by Eneocho** [comment]
> Repoban adacovsk when

WYCI
