### ISSUE TITLE
paroxetine doesn't prevent *dab

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33728]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
79b8dc3e557b0860e373b25b99323ea18c830341
good news, you are not dying! you are going to live fore-

**Comment by DrSnips** [comment]
FEATURES

**Comment by Eneocho** [comment]
You're not suiciding, you're dabbing. It just so happens that dabbing shatters your arms in such a brutal way you die instants after.
