### ISSUE TITLE
Sudden borer death

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33759]
(WEB REPORT BY: memdic REMOTE: 206.221.180.138:7777)
# Revision
d7a5758db797b4ecd3a7b6510c67f6bc311e0984

# Description
Sometimes as a borer, you just die with no reason while within a host, and without even a warning. I remember one time I also died right after leaving a host, so there's that.
# Steps to Reproduce
1 - Play borer
2 - ???
3 - Die
# What you Expected
To not die unless my host gets gibbed
# What Actually Happened
I died

**Comment by Killette2** [comment]
Things like pressure, temperature, and your host consuming salt can hurt you. Did either of these happen?

**Comment by pedr69** [comment]
pressure doesnt hurt the borer as long as he's inside a host, i'm pretty sure

**Comment by west3436** [comment]
Not enough information here to reproduce this.
