### ISSUE TITLE
Hulks cannot pick up anvils

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#33761]
I got hulk and it wouldn't let me lift anvil. I could pull anvil, that part still works. Things I tried
1. Left click anvil
2. Right click pick up anvil
3. Click drag anvil onto me
4. The previous 3 steps on both help and grab intent
I did account for the 2 handed nature, both hands were empty during these test

**Comment by SacredAtom** [comment]
They need to drink one of the sports drinks before they can do it im pretty sure

**Comment by Killette2** [comment]
You are correct, tested with brawndo and it worked.

**Comment by Eneocho** [comment]
Kinda weird that you need extra steroids when going hulk amounts to overdosing on 'em.

**Comment by Killette2** [comment]
It's what hulks crave

**Comment by Eneocho** [comment]
Yeah yeah, we all know that reference, but the point still stands.
