### ISSUE TITLE
[Bug] Gender constantly changing or vanishing

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#3376]
![ss 2015-03-09 at 06 35 00](https://cloud.githubusercontent.com/assets/8556111/6567113/b92f3966-c698-11e4-87e5-841572b271ea.png)

This was literally moments after roundstart. Before I took the mining shuttle to the asteroid, my character was female. I arrived on the asteroid, boom, null-gender.This happens EVERY ROUND, consistently.

**Comment by Zuhayr** [comment]
What.

**Comment by SkowronX** [comment]
Not caused by z level changing. Like has to do with your character settings.

**Comment by clusterfack** [comment]
Ahelp so we can view variable you when this occurs. Sometimes this is caused by plural gender and other shit. Also post your character settings.

**Comment by Hoshi-chan** [comment]
Skow said my gender was set to plural. It happened when I went to the asteroid, which Skow fixed, and then when I came back from posting in the thread, it had reset back to plural again just while I was standing around.

Could it have something to do with breath masks, or the mining hardsuit? That's the only thing that changed between my going afk and my gender fudging up again. I put my hardsuit and helmet on from storage, went to go out to mine, heard some fuss on the radio, stripped down to go back to the station, and saw that my gender was gone again.

Also, character setup:
![ss 2015-03-10 at 12 10 08](https://cloud.githubusercontent.com/assets/8556111/6569092/daf1af40-c6b9-11e4-8f9b-1f5cbc77bb72.png)

**Comment by frangi** [comment]
wearing an hardsuit hides your gender iircs

**Comment by Hoshi-chan** [comment]
I thought so too, so maybe when it hides gender, it's failing to correctly restore it when removed.

**Comment by d3athrow** [comment]
This isnt the obscured pronoun change, gender shouldn't be changing like this.

**Comment by clusterfack** [comment]
Someone managed to change their gender to neuter today

**Comment by d3athrow** [comment]
well theres shit in place now that should prevent it from occuring and force a stacktrace if it does.

**Comment by Hoshi-chan** [comment]
Last round, I arrived as female, for SECONDS, then immediately became neuter. I later became male, then neuter, several more times, before settling on neuter.

Most of the rest of the crew also became neuter throughout the round.

**Comment by d3athrow** [comment]
Holy shit hoshi get ahold of yourself and see a doctor about that gender dysphoria, we only allow cisgenders here.

**Comment by Hoshi-chan** [comment]
It's happening to everyone, Pomf, not just women, and not just humans.

**Comment by Hoshi-chan** [comment]
Was the update to resolve this pushed to the server? I don't see a closed PR, and I don't see anything in the server's changelog.

**Comment by 9600bauds** [comment]
This should be fixed now, isn't it?

**Comment by Hoshi-chan** [comment]
Yup, fixed.
