### ISSUE TITLE
[Box] Lots of trading post problems

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#3377]
Given that last time I opened an issue about the trading post, nobody responded for a few days and I ended up fixing it myself, it seems unlikely anyone else will bother with these. This is more of a to-do list for myself and also to find out if any of these are intentional.
- Though my fix to the trading floor/trade processing room fixed the *vox* being gassed by using it, it didn't fix the issue of nitrogen slowly building up on the *human*, etc. side of the wall until it pushed out all the oxygen. This only happens if the door between the sides is used excessively, but it should still be fixed. Not sure how, though.
- No air alarm in the hallway, so the scrubbers and vents cannot be reconfigured. This is most of the station.
- I'm not entirely sure about this, but I think one room in the trading post has two APCs. I don't have the file in front of me at the moment, though, so I could be wrong.
- The storage room is full of air rather than pure nitrogen. There is no way to scrub it out without opening the door and flooding the hallways, which can't scrub oxygen due to the air alarm issue and the next one.
  - This may actually be intentional, but it's annoying. Not sure if this should actually be changed.
- The air alarms correctly all default to Vox mode, but the scrubbers do not default to scrubbing oxygen.
- The access requirements on the emergency airlock are fucked beyond my comprehension due to  improper reuse of instances.

Probably more, but this is what I can think of off the top of my head.

**Comment by ComicIronic** [comment]
Which map?

**Comment by 9600bauds** [comment]
I'm assuming Box since Meta doesn't even have a trading outpost

**Comment by Exxion** [comment]
Yeah, Box. Sorry, forgot to say.

**Comment by clusterfack** [comment]
People have been redoing the outpost for awhile, this likely contains outdated information
