### ISSUE TITLE
cant see text

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33775]
(WEB REPORT BY: dibbit REMOTE: 206.221.180.138:7777)
still cant see chat

**Comment by Servalfang** [comment]
very helpful!

**Comment by Eneocho** [comment]
I assume he means runechat, which means he either doesn't have the runechat option enabled or the recent runechat update broke things for some people.
That or he meant an adminhelp instead of a bug report.

**Comment by Exxion** [comment]
IIRC Goonchat tells you to make a bug report or something if it takes too long to load. It really shouldn't say this because the solution 100% of the time is to just relog

**Comment by pedr69** [comment]
if you're on windows 7, the solution is to actually update internet explorer 
it took me like 4 different .msi's to actually get the version that works, thanks microsoft

**Comment by Eneocho** [comment]
> if you're on windows 7, the solution is to actually update internet explorer it took me like 4 different .msi's to actually get the version that works, thanks microsoft

Post/link the correct MSI then, for future reference.

**Comment by Exxion** [comment]
Are you saying it's easier to get IE working with BYOND on Linux than on a slightly outdated version of Windows?
Maybe someday Lummox will finally switch to CEF or WebView 2 or something similarly sensible
