### ISSUE TITLE
ops are still being forced human

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33789]
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
bb3ecf3ac4f1fb2b3faa091acaac9099b0e0a547

# Description
bro i thought we fixed this almost a YEAR ago

https://github.com/vgstation-coders/vgstation13/pull/31874

https://github.com/vgstation-coders/vgstation13/pull/33103

**Comment by pedr69** [comment]
tajaran ops WHEN

**Comment by adacovsk** [comment]
Just realized gurfan's PR is actually handling creating antag mobs with `humanize`. it's actually taking new_player ghosts.

 I'll work on it
