### ISSUE TITLE
halligan bar makes you run faster

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33788]
(WEB REPORT BY: adacovsk REMOTE: 206.221.180.138:7777)
# Revision
bb3ecf3ac4f1fb2b3faa091acaac9099b0e0a547

# Description
axe is slow
with halligan its fast
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kurfursten** [comment]
I think this is intended(?). When combined with the halligan it becomes the "set of irons" which does not have the same deadly force nor can you wield it or use EITHER component for its purpose. Think of it like packing up the fireaxe so it's less cumbersome.

**Comment by west3436** [comment]
Correct, it's meant to be a way to easily carry the tools together in exchange for losing nearly all of the brute force.
