### ISSUE TITLE
Nerf Arcane Tampering in regards to door teleporting

### ISSUE THREAD

**Issue by Jacknife28** [d3athrow/vgstation13#33797]
Walking through an airlock in arrivals only to be teleported dick deep into a vault is the exact opposite of fun and engaging gameplay. The spell should be limited to linking doors on the **SAME** v-level, at least unless the wizard dumps literally _all_ of their points into the spell and nothing else

**Comment by SECBATON-GRIFFON** [comment]
i'd actually fix this if this issue wasn't downboated, not sure what that says about support for it
