### ISSUE TITLE
Feature Request: Space Should Not Gib Limbs

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#33791]
Space causes brute damage. For most, this is its least noteworthy effect. Cold and lack of air are bigger threats.

The problem is when a body sits on a space tile. It continues to tick up brute damage constantly, and the limbs begin to explode into gibs. This also means that brains can be lost if a body is pulled onto the space tile of a breach.

I don't feel this is particularly realistic, and it could be easily counteracted by setting a brute damage cap that space can deal to each limb.

**Comment by pedr69** [comment]
do they really explode into gibs?
i remember seeing 800 damage spaced bodies with all their limbs still there(albeit broken)

**Comment by Kurfursten** [comment]
Yes, saw it yesterday while adminned and it happens frequently on test server. For example space vaults often send admin warnings over brainings by space.

**Comment by west3436** [comment]
Feature rejected in #33792
