### ISSUE TITLE
Empty Welding Fuel Tank still explodes from laser

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33806]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
824b0579ddf3a544103e08eeaad902197caf38df

# Description
There was an incident where a player drank all the fuel from a fuel tank and another played decided to shoot it to spook him. Fuel tank still exploded. It is in my opinion and theirs that the empty fuel tank should not have exploded.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kromkar** [comment]
Fumes

**Comment by Kurfursten** [comment]
#24166

**Comment by Theophrastus1** [comment]
I like the idea that a welding tank can still pop, albeit not as severe as if it were full, when empty. It should definitely be something that sticks around.

**Comment by nervere** [comment]
Closing as duplicate of #24166
