### ISSUE TITLE
Nutriment freezes the character.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33812]
(WEB REPORT BY: ezudiko REMOTE: 206.221.180.138:7777)
# Revision
c5d2df28ee81ca4c7d57f4a2a3dd548a7995c084

# Description
Eating food at chemtemp 293.15 will cause the character to be too cold. Binge eating will freeze and make you collapse.

# Steps to Reproduce
Spawn 4noraisins. Eat the whole packet. Get the "too cold" debuff and collapse.

# What you Expected
Not to die eating raisins.
# What Actually Happened
Getting hypothermia from raisins.

**Comment by adacovsk** [comment]
Some kinda heat capacity issue between the raisins and body causing a overestimate in thermal transfer. @Hinaichigo

**Comment by Exxion** [comment]
It's probably just the intentionally-included 20x multiplier to the heat contribution of added reagents. That multiplier really shouldn't exist for multiple reasons. In particular, it makes it not equivalent to add 10 units 10 times vs 100 units at once, etc.

EDIT: Also helps that nutriment in particular has both high density and high specific heat
