### ISSUE TITLE
Can't cook Roaches on a stick with Frying Pans.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#33816]
You can't use a metal rods on the pan so you can't cook it. Haven't tested it, but I assume this happens as well to corn dogs, corny dogs, buttersticks, kebabs and gunk kebabs.
@Hinaichigo 
[oversight][bugfix]

**Comment by Hinaichigo** [comment]
I've been a little out of the loop but I can take a look at this. Could be that rods have custom logic or something related to crafting?

**Comment by Eneocho** [comment]
Dunno. But you can totally cook rod food on the microwave. Probably an exception in there somewhere you didn't know about when making the frying pans, cause they do accept cardboard.

**Comment by Hinaichigo** [comment]
Does it say 'You have no idea what you can cook with the rods.' or just nothing?

**Comment by Eneocho** [comment]
I can't quite remember, but I think it just didn't let me use the rod on the pan even with all the other ingredients in place.
