### ISSUE TITLE
[Request] Click on matter cartridge with Material Synthetizer to auto-load all matter cartridges on the floor

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3384]
As it is right now you have to pick each cartridge off the floor and stuff it in the synthesizer manually, which is awfully annoying and mortally tedious when you're trying to synthesize phazon. Doesn't help that the cartridges themselves are also small and hard to click.

**Comment by Probe1** [comment]
that's a good one.  it'll still stop at 5 though since that's the max for a mat synth.
