### ISSUE TITLE
Waystation: mysterious string of frying pans

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33841]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
7ef933480a26ed3bb812583aca4dec378cd4d34b

# Description
There is a string of frying pans south of aft starboard solar on Waystation

**Comment by tinysaturn** [comment]
![image](https://user-images.githubusercontent.com/78547984/208265820-d2fc68f0-711f-4145-9c98-d640912f46b3.png)

**Comment by pedr69** [comment]
way also has a random posibrain in space
it's soul

**Comment by Eneocho** [comment]
It was a sabotage attempt by the Microwave Lobbies after the cooking revolution of 2561 caused by the introduction of pan cooking. Keep it, it's our history.

**Comment by Hinaichigo** [comment]
Oops...
