### ISSUE TITLE
Prisoner Autoclother is fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33851]
(WEB REPORT BY: korthe REMOTE: 206.221.180.138:7777)
# Revision
47f3f79da37e614437b1d77e133aa21348bcaa67

# Description
While in it's flatpack, the Prisoner Autoclother actually works, causing anyone beside it to be stripped of their gear and thrown in a prison outfit
# Steps to Reproduce
get the Prisoner Autoclother flatpack from the Alcatrz IV crate
# What you Expected
it to do nothing since it's just a flatpack
# What Actually Happened
it acts like it's not in a flatpack

**Comment by Eneocho** [comment]
This is a ((FEATURE)) with most flatpacks. The flatpack just makes it moveable and shit, all the internal functions still apply.
I remember one round I was a making a plasmasheet shitting automatic setup and got 20 hydrotray flatpacks. I had to get medical treatment and when I returned and unpacked the flatpacks almost all the trays had weeds, grass, shrooms, etc. growing on them.

**Comment by nervere** [comment]
There are a lot of issues with it as well as the autoprocessor machines. I'll have a PR up sometime today. Not an issue w/ flatpacks.
