### ISSUE TITLE
Ling Self-Sting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33859]
(WEB REPORT BY: kinler101 REMOTE: 206.221.180.138:7777)
# Revision
a2d89bc3fb9cafbf0d764f88d40c281990d2bffd

# Description
Ability to sting yourself as a ling while in horror form
# Steps to Reproduce
1) Be ling with paralyzing sting
2) Have Horror Form
3) Sting yourself
# What you Expected
Not to sting myself (immune to stuns)
# What Actually Happened
Paralyzed myself

**Comment by pedr69** [comment]
[ided]

**Comment by ShiftyRail** [comment]
Inteneed
