### ISSUE TITLE
Hacked MULEbots cannot pick up humans

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33854]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
47f3f79da37e614437b1d77e133aa21348bcaa67

# Description
A hacked MULE with its platform lowered cannot pick up a human as cargo.

**Comment by Eneocho** [comment]
I could swear it could before.

**Comment by dinnerwoerror** [comment]
i told you fun was more important
#32419

**Comment by Eneocho** [comment]
new account? is that you windows?
