### ISSUE TITLE
getting sent to crit potentially entombs you in a personal airbag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33880]
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
934267d70190cc8ea53d63ad982fa98037140d3d

# Description
i get hurt by spider queen and i shoot the window to quickly suck them out of the room with zas and a bunch of stuff hits me on the way out, deploying my airbag and keeping me safe in the room as the spider flies out, but i go into crit because of le funny venom toxin as well as damage tick delay and then i die and i remain trapped in the cocoon until the end of the round
# Steps to Reproduce
get damaged by some kind of delayed damage, like poison or being on fire or something, and then activate your personal airbag by getting hit by a bunch of flying cargo crates or something
# Possible Solution
make some kind of way to break open a personal airbag from the outside like a knife or something, sort of like how cocoons work

**Comment by dinnerwoerror** [comment]
or maybe it was me dying in the airbag, 5 seconds can be quite a bit longer than you'd think
