### ISSUE TITLE
False wall overlays are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33885]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
Shadows don't parse over them

**Comment by Exxion** [comment]
What false wall overlays? What does this mean?
The only false wall overlays I know about are those involved with mesons, but you don't see shadows when wearing mesons.

**Comment by dinnerwoerror** [comment]
maybe it's something to do with how light doesn't get stopped by a false wall and if you look at a false walled room from the outside you'll see a part of the room that's leaking more light than the rest of the perimeter? This could also be how you can hide items such as lockers under false walls (it's a feature) which you can't do with normal walls
