### ISSUE TITLE
Cutting cables doesn't disconnect neighbours from network

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3388]
Isolate a cable by cutting 2 neighbour cables, use multitool on it and be amazed as it still has juice flowing through it.

**Comment by PJB3005** [comment]
#3266

Same issue, effecting all power machinery too

**Comment by Cutelilduck** [comment]
Re-running 'make powernets' in the Debug menu seems to correct it. But that's the lag starting shitstorm at round start.

Make powernets deletes all the old powernets, and runs
for(var/obj/structure/cable/PC in cable_list)
		if(!PC.powernet)
			var/datum/powernet/NewPN = new()
			NewPN.add_cable(PC)
			propagate_network(PC, PC.powernet)

The answer may lie somewhere around power.dm or cable.dm, perhaps the cut_cable_from_powernet() proc, but I have been unable to see anything obvious from a first look.
