### ISSUE TITLE
DABBING BROKEN/RUINED?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33894]
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
934267d70190cc8ea53d63ad982fa98037140d3d

# Description
When queueing up many dab windows it used to be it would gib your head, and your arms stay intact and keep slamming against the head no matter how many dab windows were queued. now the arms gib first, and you cannot dab without arms. shit is fucking ruined PLEASE fix it PLEASE
# Steps to Reproduce
queue up multiple dab windows. at least 5.
# What you Expected
for my head to explode and for my arms to keep dabbing even after death
# What Actually Happened
arms exploded. head intact. BORING AND UNFUNNY

**Comment by Eneocho** [comment]
Absolutely ruined. I can't do the Insane in the Mem clown gimmick (you suicide so it gibs your head and you get Insane in the Mem's Brain)

**Comment by Eneocho** [comment]
Probably caused by #33783

**Comment by adacovsk** [comment]
maybe just make dab gib everything including head rather than queing windows

**Comment by pedr69** [comment]
do people really find "lol i explode into paste" funny?
i hate it, especially the debraining part since it looks identical to a murder scene
and i think that's fucking stupid, i think you should eat waterpotass if you want to explode, not do it on demand whenever

**Comment by tinysaturn** [comment]
> do people really find "lol i explode into paste" funny? i hate it, especially the debraining part since it looks identical to a murder scene and i think that's fucking stupid, i think you should eat waterpotass if you want to explode, not do it on demand whenever

don't make me depict you as a soyjak

**Comment by dinnerwoerror** [comment]
look at this individual removing things from the code because they personally dislike it

**Comment by Eneocho** [comment]
> don't make me depict you as a soyjak

I gotchu king
![soi](https://user-images.githubusercontent.com/67024428/209478478-98287751-b03b-4579-be00-3822ed6585f7.png)

**Comment by pedr69** [comment]
well i guess i'm owned

**Comment by Exxion** [comment]
I agree about *dab but >he doesn't know about rubber ducks

**Comment by Eneocho** [comment]
It's not the same. *dab is a trueborn greytide warrior. rubber duck is a seccie demoted to greyshirt.

**Comment by Exxion** [comment]
Rubber duck has been in the game far longer

**Comment by Eneocho** [comment]
I know, but that's irrelevant.

**Comment by pedr69** [comment]
i dont mind the rubber ducks
just dont think dabbing without arms to explode your head is funny

**Comment by nervere** [comment]
not sure what broke this but i just tested it and it works again
