### ISSUE TITLE
Pipe Manifold Layer Issue

### ISSUE THREAD

**Issue by gurfan** [d3athrow/vgstation13#33899]
@Exxion 

![dreamseeker_zzQJGpTRki](https://user-images.githubusercontent.com/51427771/209588734-64bc6ac8-909a-4d5a-85cf-e43393015ce2.png)
![dreamseeker_bwOYiMfm86](https://user-images.githubusercontent.com/51427771/209588738-1c6c9571-ab16-4c04-be02-83645ed2ca0c.png)

**Comment by Exxion** [comment]
That's a weird one
