### ISSUE TITLE
doing *help sends a prompt asking if you're sure that you want to dab

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33897]
(WEB REPORT BY: windowserrors REMOTE: 206.221.180.138:7777)
# Revision
c502e818ac9ffd24831b4e1279fcae17635477eb

# Description
title

*help still works normally, it just sends the prompt, I just need to close the prompts

**Comment by pedr69** [comment]
fuck i have no idea how to fix this without also removing *dab being in the *help list

**Comment by pedr69** [comment]
nvm thats what the status_check is for, i think
