### ISSUE TITLE
inflateable shelters appear open

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33896]
(WEB REPORT BY: silent3 REMOTE: 206.221.180.138:7777)
# Revision
934267d70190cc8ea53d63ad982fa98037140d3d

# Description
they look open when they got people in em,cages do the same thing it looks bad
# Steps to Reproduce
put something in a shelter
# What you Expected
it to have an overlay making it look closed
# What Actually Happened
it looks open!

**Comment by Kurfursten** [comment]
Were you alive or a ghost when you saw this? I believe ghosts see them open due to invisiblity or something

**Comment by Exxion** [comment]
No, it's more plane stuff. Also, it's very painful to fix for inflatable shelters specifically due to their use of `vis_contents`. Our plane system is fucked. `PLANE_MOBJECT` when?
