### ISSUE TITLE
[Request] Replace borg surgical tools with high-tech variants when medical module upgrade is applied

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#3389]
The new surgical tools capable of performing the functions of several tools in one could go a long way towards cleaning up the medical cyborg's currently overwhelming number of tools.

If I still had everything set up to code it myself, I would, but I don't. Besides, I'd like to know what other people think of this.

**Comment by Imagebard** [comment]
I tought that having to switch tools and dealing with a clonky UI was part of the artificial difficulty of being a Cyborg, Hoshi-chan.

**Comment by SkowronX** [comment]
Please think of the other borg modules

**Comment by Probe1** [comment]
I think it's a great idea.

**Comment by Ephx1** [comment]
I'm not sure, Medical Borgs that are upgraded are already one of the most overpowered things in the entire game. Their only downside is that they can't put chems in cryo, or bloodpacks on IV drips.

**Comment by Hoshi-chan** [comment]
Upgrade just gives them an upgraded hypospray and a defib.

**Comment by Ephx1** [comment]
No, we're not balancing for PvP, but Borgs have always had a sense of "Balance" when it came to human counterparts, Medical Cyborgs can bring someone back from life by themselves and their chemicals regenerate, and with this their surgery times are shortened even moreso.
Where's the point in playing main medical as a carbon now? Take a look at other upgrades for other Cyborgs, they have little to none and it works that way, Engineering borgs get slightly more build options that don't change much, Miner borgs get a jetpack which practically has no use on the Asteroid itself, Secborg gets a taser cooler. They all are balanced out to their human counterparts.

That's my view, I mean, I'd love the new surgical tools, but please separate them to their own upgrade.

**Comment by Hoshi-chan** [comment]
Having hands, being capable of doing virology, being able to utilize all-in-one grinders, not having to constantly eject and store your LONE BEAKER to be able to do chemistry, moving faster, being able to rapidly switch tools rather than store and hunt for them in your overcrowded list of modules...

I can think of a lot of reasons to play human medbay, though the main reason not to is that you need access to just about everything to do the job right, which requires either a generous, trusting HoP, or competent, friendly coworkers. Neither is common.

I've tried a handful of times since starting to play again, and each time I'm either spending an inordinate amount of time breaking windows and hacking doors to get where I need to be because it's lowpop and nobody can give me access, or I'm being told by the HoP that if I want chemistry access I need to get a full-on job change, and lose my existing access, or I'm being bitched at by my coworkers for being in their workplace, when their idea of a good cryo mix is a 50u small beaker of clonexadone, and they've accidentally wasted all of the plasma.

**Comment by Ephx1** [comment]
I'm still not certain what makes them crude by any sense of the word, I suppose chemistry is slow with one beaker, yes, but other than that, they are the masters of the Medical Bay. The only hassle I've ever felt running it was IV bags or Transplanting organs.
But that's my opinion.

Regardless, Medical Doctors have access to Chemistry and Genetics now.

**Comment by ComicIronic** [comment]
Doctors have chemistry access now, actually.

**Comment by Hoshi-chan** [comment]
Oh, I usually play paramedic as a human when I do medbay, for, you know, retrieving bodies off the exterior of the station. Nobody thinks of the paramedic's cryo when doing mixes, and if anyone needs access to chemistry, it's the paramedic.

Carrying a bunch of medkits taken from storage is a really ghetto way to have access to the drugs you need to save the guy in the brig from bleeding out because security harmbatonned him into crit.

**Comment by Hoshi-chan** [comment]
All that shit aside, again, I don't see what's overpowered about cleaning their inventory up with the upgraded surgical tools when the upgrade is applied.

You failed to explain that.

**Comment by Ephx1** [comment]
It's not overpowered itself, but with a Medical Upgrade it just feels like too much.
You get one upgrade and you can run medical bay faster than any other organic can because research will never ever bother to give them anything good.
Besides, Medical Upgrade board is only 3 Biology, and 3 Engineering, while the one Manager Scalpel requires  Materials 5, Engineering 4, and Biology 5. It feels like way too much just to add tools with that research in a board that costs research way less than it does.

It's really all a matter of opinion though, I still like play Mediborg, and how easy it is to cure everyone. I recall at one point they had to get an entire surgical theatre installed, and that felt like it made sense.

**Comment by Probe1** [comment]
The discussion ran its course and anyone motivated to make changes did so.  Open a new issue to discuss the current state of the game.
