### ISSUE TITLE
When you have a seizure your turret shoots you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33929]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
81690891b56df80bd11d3b3384a7ca298a2e0c08

# Description

this is funny enough to be a future. but when you have a seizure your turret decides that you're not a human and starts blasting. 
# Steps to Reproduce

# What you Expected

not to get shot 
# What Actually Happened

got shot

**Comment by Eneocho** [comment]
no mercy for epileptics 
FEATURE(TM(TM(TM)))

**Comment by pedr69** [comment]
this might be a thing because stun turrets dont shoot stunned people
and kill turrets dont shoot dead/critted people

probably some funkiness with those checks
you might be able to game the lethal AI upload turrets if you go to sleep on command, might test that out
