### ISSUE TITLE
Xenomorph thermals are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33938]
(WEB REPORT BY: casualbro REMOTE: 206.221.180.138:7777)
There are black tiles all over the normal sprites that should have been revealed by xeno thermals.

**Comment by Exxion** [comment]
Probably thermals in general, too, because I'm stupid. I'll fix this tomorrow

**Comment by adacovsk** [comment]
it's because see_in_dark is not set high enough to see all tiles. People expect them to work like mesons but it don't be like that, but I guess it should @Exxion

**Comment by Exxion** [comment]
That doesn't seem right, but it's occurred to me that it also doesn't seem right that it would be my fault, since you don't have `SEE_BLACKNESS` when you have thermals on

**Comment by Exxion** [comment]
OK, you're not *supposed* to have `SEE_BLACKNESS` when you have thermal vision, but the code to remove it wasn't actually working correctly
