### ISSUE TITLE
donk pocket has a plate in it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33931]
(WEB REPORT BY: silent3 REMOTE: 206.221.180.138:7777)
# Revision
81690891b56df80bd11d3b3384a7ca298a2e0c08

# Description
made some donk pockets out of pengpeng (sorry pengpeng) and then deepfried them, upon consuming said donks you are given a dirty plate, but no plates were used in the creation of the donk
# Steps to Reproduce
make donk out of pengpeng and deepfry it
# What you Expected
empty hand when i eat donk
# What Actually Happened
dirty plate

**Comment by Eneocho** [comment]
Pengpeng is actually made of ceramic, so the donk pocket was a ceramic donk.

**Comment by Hinaichigo** [comment]
A microwave recipe donkpocket or a food-press donkpocket?
