### ISSUE TITLE
Need gooneish clickdrag physics, but better

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#3393]
You could probably group and pool the objects or something.

Case 1: Standing amongst a pile of random crap, click drag one item to another tile, game takes all objects of specific type and moves them to the target tile

Examples: Standing in a pile of ore, click drag all the iron to a location, standing in a pile of paper, clickdrag all paper to that location, standing in a pile of various produce, clickdrag all carrots to that location.

Case 2: Clickdragging an object to a container will attempt to load that container with similar types. It will first check if the destination is full or if that destination cannot hold the objects involved. If the container is a locker or a closet, it will become more specific then just a worn/carrable container. If the target is actually a machine or a weapon, it will check if the target can be loaded with the source before proceeding. If the device can only hold one object, it will attempt to load the first thing click dragged instead of everything similar.

Examples: Standing in a pile of jumpsuits, clickdrag to backpack, backpack gets loaded with jumpsuits until full. Standing in a pile of produce and seeds, clickdrag seed to produce satchel to load produce satchel with seeds until full. Standing in a pile of various ore, click dragging to an ore box will load all nearby ore into the ore box.  Standing in a pile of paper, click dragging to a paper bin will attempt to load the paperbin.  Standing in a pile of various ore, click dragging an iron ore to a locker or a closet will load all iron ore. Standing in a pile of various metals, click dragging to a protolathe or an autolathe or such will attempt to load all nearby gold into the machine until full. Standing in a pile of matter cartidges, click dragging to an RCD will attempt to load cartridges into the RCD until full. Standing in a pile of various ammos, click dragging the correct ammo to a weapon will attempt to load it at least once depending on the kind of ammo (Most guns just need to be loaded once to be full). Click dragging a beaker into a cryo tube to load dat beaker.

Case 3: Click dragging can enhance stacking. Click dragging a target to a source that is stackable and the same kind will attempt to stack until stack limit.

Examples: Holding a sheet of metal, click dragging a sheet of metal off the ground onto the sheet you're holding will attempt to stack all nearby sheets of metal into your hand metal until maximum stack reached.  Click dragging a tile onto another tile will attempt to stack all nearby tiles onto that one until maximum stack reached. 

Case 4: Click dragging a container onto a surface will attempt to unload the container onto the surface. If the target is another container or machine, it will attempt to load that container instead.

Examples: Click dragging a backpack onto a table will allow you to attempt to dump the contents onto the table. Click dragging a produce satchel onto the ground in-front of the kitchen will attempt to make the chef cry. Click dragging an unloadable weapon to the ground will attempt to unload the weapon to that spot. Click dragging a backpack to another backpack will attempt to dump into that backpack. Click dragging a backpack full of metal to a fabricator will attempt to load that fabricator with any of the backpacks contents that are loadable, and ignore/skip the rest.

Case 5: Click dragging an object to a mob will attempt to give that specific object to the target via the GIVE command.

Examples: Dragging a blunt to the clown will attempt to give the clown the blunt. Dragging the space lube sprayer to the mime will attempt to make the clown jealous.

Case 6: a verb or command or something that can be toggled on and off, that will attempt to make any of the above done by the player that involve multiple tiles only target one tile instead. 

Example: Standing in a pile of ore. click dragging the iron ore to another tile, will only grab iron ore from the tile that was dragged from.

**Comment by gbasood** [comment]
I think this is mostly fulfilled by dragging stacks of items over eachother but hey
