### ISSUE TITLE
AI can track Pulse Demons with cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#33976]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
eca84ad974cce4cc5a2753c461dae03ba1f3e854

# Description

# Steps to Reproduce
go to the tracking screen for AI and you can sometimes see Pulse Demon as an option

# What you Expected

# What Actually Happened

**Comment by Killette2** [comment]
Same for grue and grinch

**Comment by pedr69** [comment]
yeah the AI can track anything with a ckey(provided they arent wearing an agent ID or the ninja mask)

**Comment by west3436** [comment]
I get that for humans or human-like entities but things like a pulse demon or grue don't really make sense

**Comment by dinnerwoerror** [comment]
so does this mean that grues and pulse demons are people while syndicate agents and ninjers aren't

**Comment by Exxion** [comment]
Can the AI track a pulse demon that's in a machine or wire or whatever? If not, I don't really see a problem

**Comment by pedr69** [comment]
i think you only hide from the AI while in a gun charger/beepsky/borg
since those are the ones that move you inside the object, the rest move you onto the turf

**Comment by west3436** [comment]
PR to close this was rejected
