### ISSUE TITLE
Solar panel autotracking does not work

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#3398]
When tracking is set to automatic the solar panels will not turn.
Manual tracking still works.

**Comment by Probe1** [comment]
What map

**Comment by BestName** [comment]
Box and meta though I doubt it's a map issue.

**Comment by Exxion** [comment]
You sure? I'm pretty sure I just saw it working.

**Comment by BestName** [comment]
I'm pretty sure.

**Comment by Probe1** [comment]
I joined the current round and confirmed it's bugged.

**Comment by Midaychi** [comment]
It works but sometimes it stops working. I've had this issue as a mommi on the derelict before, no idea why it happens or what causes it. It'll just suddenly get out of synch or give up 4 no raisin as the round progresses. I've found its easier to just set it up manually.

**Comment by Probe1** [comment]
it does not work at round start and this is a recent bug.

**Comment by Midaychi** [comment]
Then we're talking about two different bugs because the thing I described has been around for a while.

**Comment by Probe1** [comment]
yeah this is a new one, automatic trackings taken a dump.

**Comment by Hoshi-chan** [comment]
Can confirm this.

Set up the solars as temporary power on meatclub during a 3-person(!) lowpop round the other day, automatic tracking absolutely would not work.

**Comment by Probe1** [comment]
Careful about 'the other day' because 48 hours ago automatic tracking absolutely worked.

**Comment by dylanstrategie** [comment]
Ever since my change to solars, automatic tracking has been extremely wonky. Sometimes it works, sometimes it doesn't. Sometimes it doesn't work immediately but if you wait a bit it sorts itself out, sometimes it's working and suddenly it fucks up

I have no idea what causes it. When in doubt, use manual, but it's not COMPLETELY broken either

**Comment by clusterfack** [comment]
I think its an issue with solar trackers requiring power to start tracking, or something to that effect.

**Comment by SarahJohnson489** [comment]
I can confirm that it's not that. We had power in the grid a good 20 minute by the time I went to figure out what was wrong, Array orientation was still at 0 degrees, default, for all 4 arrays so I had to manually rotate them. Even after they started producing power automatic refused to track.

Is there a problem with the track speed being more than the solars can move so it does nothing?
