### ISSUE TITLE
Infinite Grilling

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3399]
The code for grilling and deep-frying checks the name of the food to see if it contains "grilled" or "fried" rather than actually using a variable.
Which lets you just rename the food with a pen and keep grilling it forever, or use a hand labeler to name it "burger (TOTES GRILLED)" and the machine will think it's actually grilled.

**Comment by Kurfursten** [comment]
While I think the first (infinite grilling) should be fixed, the second is pretty funny.

**Comment by 9600bauds** [comment]
Also, grilling the same item a lot causes it to

![ss 2015-03-12 at 09 43 46](https://cloud.githubusercontent.com/assets/6526157/6631194/e713cd28-c900-11e4-9346-2bda6769e11b.png)

uh

**Comment by Midaychi** [comment]
That second post's a feature.

**Comment by SangriaMonkey** [comment]
I miss fried garbage

**Comment by Exxion** [comment]
So if you grilled something hundreds of times
Enough times that the pixel_y places the sprite off the screen of someone standing one tile north of the actual object
And somehow placed said object in a large room or north-south hall
Would you have an object that could be seen but not interacted with?

Well, someone could use a verb on it from the verb menus, but who uses those?

**Comment by 9600bauds** [comment]
You could alt+click on the tile that the item is in, but good luck knowing which tile that is.

**Comment by ConkerDev** [comment]
This is aparently intended, isnt it?

**Comment by Probe1** [comment]
@N3X15 close
