### ISSUE TITLE
[Request] Make Genetics powers only manifest on their own block

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#3401]
I ran into this problem last night. If A power is on block 1, it could manifest when I inject B power from block 3. It makes it difficult to isolate which block is which so when you hand out powers, you aren't giving Assistants Hulk. I understand disabilities already work this way.

**Comment by Midaychi** [comment]
In plainer language, the chance to mutate is proc'd every time mutate is called, not when mutate is called on that specific power block, so everything runs the slot machine rather than just that block you radiated and any others that got random radiated with it.

**Comment by sonime** [comment]
That's not really plainer in my opinion, but here's what I'm asking. Instead of powers manifesting whenever an SE is injected, why not only have that chance to manifest if the SE includes the power's block?

**Comment by TermedClepe** [comment]
That would nerf genetics immensely. Once powers manifest, they are manifested until the power block gets too low. Currently this means you can keep testing individual block injectors while having each test have a chance to also manifest already discovered powers.

With this change you would have to spam injectors for each individual power to manifest, taking hours, or you would first isolate all power blocks without manifesting them and then spam injectors hoping shuttle doesn't arrive in the next 5 minutes.

**Comment by sonime** [comment]
I just try to see which block is which so if I hand out powers like people expect 5 minutes into the round (no joke) then I dont give out Hulk to people who are going to griff.

**Comment by Probe1** [comment]
Jab yourself 50 times until you get the power or move on and accept the mess.

**Comment by Probe1** [comment]
Or refactor genetics god knows we need it.

**Comment by sonime** [comment]
pfft
