### ISSUE TITLE
Authentication swiping requirements lower capped at number of people with access to it

### ISSUE THREAD

**Issue by SECBATON-GRIFFON** [d3athrow/vgstation13#34026]
[featurerequest]
because sometimes calling code red is just not possible on lowpop
a simpler check would be to see who's head of staff in the manifest, but the access thing seems more complete. whichever works. (maybe make it so that the id with access actually has to be on a person)

**Comment by pedr69** [comment]
i for one support not having to do stupid shit with the teleporter to call code red

**Comment by Eneocho** [comment]
lame cause you would not be able to call code rainbow for muh clowns if the swiping requirement scales with people with access (which usually means everyone on lowpop)

**Comment by SECBATON-GRIFFON** [comment]
> lame cause you would not be able to call code rainbow for muh clowns if the swiping requirement scales with people with access (which usually means everyone on lowpop)

i should be more specfic, it would cap at the normal amount we know in rounds today.

**Comment by Eneocho** [comment]
That's ok then, but I'm with pedr on this one. Teleporter bullshit is raw SOVL.

**Comment by SECBATON-GRIFFON** [comment]
> That's ok then, but I'm with pedr on this one. Teleporter bullshit is raw SOVL.

he wants it gone actually if you read again

**Comment by pedr69** [comment]
> I'm with pedr on this one. Teleporter bullshit is raw SOVL.

am i the ESL or are you

**Comment by Eneocho** [comment]
My brain skipped the "NOT", I thought you were in favour of the teleporter bullshit sovl.

**Comment by SECBATON-GRIFFON** [comment]
lack of support
