### ISSUE TITLE
RCD walling is unlogged (ban request autism edition)

### ISSUE THREAD

**Issue by KingofHONK** [d3athrow/vgstation13#34021]
We had a [ban request](https://ss13.moe/forum/viewtopic.php?f=20&t=6458) recently dealing with someone who was stripped, cuffed, buckled to a chair and said bucklecuffed person was then cuck cubed by someone using the RCDs walling function. This ultimately resulted in us being unable to determine who was responsible for the round removal. hrefs were combed through and nothing came up as well.

**Comment by ErrorsWindows** [comment]
> stripped, cuffed, buckled to a chair and said bucklecuffed person was then cuck cubed by someone using the RCDs walling function ...

> ... unable to determine who was responsible for the round removal

![Capture3](https://user-images.githubusercontent.com/122955989/213599429-660d24fb-4136-418e-8401-d1f1cc8fd487.PNG)

**Comment by SECBATON-GRIFFON** [comment]
if a jobbie is cuckcubed and nobody is around to hear him, does he make a sound
