### ISSUE TITLE
someone fucked up and chill bugs are now bees

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34044]
(WEB REPORT BY: dakkanob REMOTE: 206.221.180.138:7777)
# Revision
56730fb49162e5fc35eb22a4b7277bfe225b17d9

# Description
lol
# Steps to Reproduce
set up a chill bug apiary (most trader posts have everything ready for setup)
# What you Expected
chill bugs
# What Actually Happened
angery bees who not produce no chill wax

**Comment by DeityLink** [comment]
Borked by the init proc shuffle of #32918
