### ISSUE TITLE
[Bug] Removing items from the holodeck

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3404]
Use the holodeck control computer to select a program with items (thunderdome for example).  Head to the APC that powers the holodeck (Fitness Room on Box) and turn off the equipment power.  Items can now be removed from the holodeck without a check and taken anywhere on the station.

Suggestion for fix:  Take the check that sees if the holodeck computer isn't destroyed and apply it to powered off.

**Comment by dylanstrategie** [comment]
Sounds like a plan
