### ISSUE TITLE
No increase Power Capacity for Pulse Demon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34051]
(WEB REPORT BY: loveender REMOTE: 206.221.180.138:7777)
# Revision
afc77becd5a8f9ee3dce07c13c57574363de47dc

# Description
There is no option to upgrade the power capacity as a pulse demon. This was verified by Admin BoHaynes
# Steps to Reproduce
I guess become a pulse demon and have a look yourself, maybe its to do with the map, we're on waystation
# What you Expected
FUN TIMES AS A PULSE DEMON
# What Actually Happened
SADNESS DESPAIR

**Comment by pedr69** [comment]
intentional, done in #33690
i felt the capacity upgrade was dogshit

you increase capacity by sucking power out of APC's now

**Comment by nervere** [comment]
not a bug as pointed out by janez

**Comment by pedr69** [comment]
i dunno cause i'm not a collab but i think you should "mark as duplicate" instead of completed
