### ISSUE TITLE
Prescription glasses deletion

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34050]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
afc77becd5a8f9ee3dce07c13c57574363de47dc

# Description
If you're wear prescription glasses, you're able to put opticals mesons over them to gain the benefit of both.
However if you equip-swap welding goggles, the prescription glasses undearneath will get deleted.

Bug probably affects swapping other kinds of eyewear too

**Comment by Eneocho** [comment]
I swear the prescription glasses get slotted into the mesons and swapping drops the glasses on the floor.

**Comment by pedr69** [comment]
seems to be a feature?
![image](https://user-images.githubusercontent.com/18052467/214993393-e6d8d37b-e3f2-4f64-b20a-4fe72a307a05.png)
but it isn't working right, the prescriptions get all fucked up
in my testing they don't get deleted, instead becoming ghostlike - VVing yourself the prescriptions are still in your eyes slot despite the fact you don't have any glasses on
they also don't do their prescription thing anymore

**Comment by Eneocho** [comment]
The prescription ones get dropped to the floor if you hotswap, I'm telling you.

**Comment by pedr69** [comment]
this seems to be producing some sort of nervegas

https://github.com/vgstation-coders/vgstation13/blob/9acc7d98c6fc7605a7b36e5be0ad511b04d16f76/code/modules/clothing/glasses/glasses.dm#L42

**Comment by Exxion** [comment]
That code is painfully moronic but I'm not sure what in there is actually causing this bug

**Comment by DeityLink** [comment]
Upon testing it seems that swapping out mesons that are currently covering some prescription glasses causes the glasses to pop-out on the floor. So I assume someone fixed it at some point.
