### ISSUE TITLE
Mechatronic Engineer's Jumpsuit Sprite Error

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3406]
![jumpsuit](https://cloud.githubusercontent.com/assets/3991927/6633314/7563c7b4-c914-11e4-89c1-b2ad6184e0db.PNG)

The sprite for the jumpsuit appears to be rotated 90 degrees clockwise.
It wasn't just the one I spawned with either, the one in the locker had the same problem. The roboticist jumpsuits were fine.

**Comment by SkowronX** [comment]
Mislabeled state.
