### ISSUE TITLE
Buff roach farms

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#34060]
Roaches are capped at 50 alive per world or z-level, before they stop hatching from eggs. 50 is pretty low on the scale of fun. I get why there can only be 50 space carp in the world for carp farms but 50 roaches feels a bit restrictive.

**Comment by Kromkar** [comment]
Fuck off bugfucker

**Comment by Killette2** [comment]
Adding that the roach restaurant made it so I couldn't hatch a single roach last round today. I had to get admin intervention even though the roachcap was on another z-level
