### ISSUE TITLE
Heating Chems is Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34075]
(WEB REPORT BY: xeroxemnas REMOTE: 206.221.180.138:7777)
Trying to heat chems with a laser scalpel or bunsen burner or laser heater or whatever does not cause a reaction in the chemicals.

**Comment by Eneocho** [comment]
Some chem reactions are silent, such as lube to chem waste. Also, some chems have very high thermal masses (like leporazine).
What chem/chemmix were you trying to heat up?
I do remember a handful of times where chem reactions simply didn't want to happen, apparently cause the controller for chem reactions froze or something.

**Comment by Killette2** [comment]
What quantity of chems were you trying to heat?
I was able to make 10u degenerate calcium the other day with a welder

**Comment by xeroxemnas** [comment]
didnt work for alcycosine and bleach I think, I'll have to try it again.

**Comment by Eneocho** [comment]
Alkycosine is kinda hard to cook manually in my experience, you either need the strong fuels or the laser scalpel.

**Comment by xeroxemnas** [comment]
yeah I used the laser scalpel though no dice.

**Comment by Eneocho** [comment]
Must've been that "chem reactions controller died" issue I mentioned then, cause I've also have had issues specifically with making alkycosine.

**Comment by xeroxemnas** [comment]
I tested it with nervere and used an electric thermometer. The chems do heat up but so fucking slowly that it takes forever. 
When they do heat up they do react however so it's heating the chems that's borked, not the reactions themselves.

**Comment by Exxion** [comment]
This is probably just because bleach has both a high density and an absurd specific heat

**Comment by xeroxemnas** [comment]
> This is probably just because bleach has both a high density and an absurd specific heat

Don't think so it didn't work with degenerate calcium either. I had to have an admin manually change the heat of the chems since they were heating up slowly as hell even with plasma fueled bunsen burner

**Comment by Exxion** [comment]
Mutagen has a lower density than bleach but an even more absurd specific heat. How much were you trying to make?

**Comment by xeroxemnas** [comment]
> Mutagen has a lower density than bleach but an even more absurd specific heat. How much were you trying to make?

Only about 30 units or so, it was heating up super slowly at only like 1 Kelvin at a time. The laser scalpel that is supposed to bypass the specific heat didn't work either

**Comment by Exxion** [comment]
AFAIK the laser scalpel is not meant to bypass specific heat, and it would be expected to heat very slowly due to the ridiculous specific heat involved. A comment in the code recommends making no more than 10u degenerate calcium at a time due to how hard it is to heat mutagen.
However, it looks like there *is* a bug here. It's also old as shit. It's been here since chem heating was added six years ago. When calculating how much to heat reagents, the volume is counted twice. So if you double the volume of reagent in a beaker, it will be *four* times as hard to heat. This was actually fixed by the mob heating PR, but that was reverted after like one day due to it breaking other things.

**Comment by xeroxemnas** [comment]
I tried making only 10 units of degenerate calcium with 5 units of mutagen and 5 units of milk and it still didnt work with the laser scalpel. Something definitely got broken.

**Comment by Killette2** [comment]
Have you tried like 200 clicks? That's what I usually do
