### ISSUE TITLE
you can shoot yourself with your own buckshot without aiming at yourself somehow

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34072]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
afc77becd5a8f9ee3dce07c13c57574363de47dc

You fire the shotgun!

The projectile sticks in the wound!x6

**Comment by Servalfang** [comment]
skill issue but I don't like it either

**Comment by pedr69** [comment]
walk slower so you don't outrun your own bullets

**Comment by Eneocho** [comment]
> walk slower so you don't outrun your own bullets

This. Skill issue.

**Comment by ErrorsWindows** [comment]
it's true, you can improve your accuracy 100% by just walking into the bullets, i don't know why everybody doesn't do it
