### ISSUE TITLE
Moving Chairs have some issues

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3408]
![chair](https://cloud.githubusercontent.com/assets/3991927/6636147/46aae66a-c93b-11e4-9f1d-86b8127e69af.PNG)
![chair2](https://cloud.githubusercontent.com/assets/3991927/6636149/484ef1b4-c93b-11e4-98cc-470540b92550.PNG)
![chair3](https://cloud.githubusercontent.com/assets/3991927/6636151/49af373a-c93b-11e4-93f5-0232ce40025d.PNG)

When I move myself via rolling chair+fire extinguisher, the chair sprite does not want to stay attached to my sprite, even when I stop moving. In all 3 of these screencaps, I was still technically "in" the chair, despite not touching it. Also, when someone dragged a chair with me in it, I would be dragged a tile behind the chair. An admin who was on says this isn't normal/supposed to happen.

**Comment by Kurfursten** [comment]
May be related to this fix https://github.com/d3athrow/vgstation13/commit/19ac7737770f9bf8f6471f745ab96ebb4398c23b

**Comment by Exxion** [comment]
It's also impossible to unbuckle yourself if the chair is more than 1 tile away from you. Very annoying if your extinguisher is empty.

**Comment by Shadowmech88** [comment]
Possibly no longer relevant.
