### ISSUE TITLE
Shrimps won'

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34096]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
4b2a8df50bceaa36325497295839fad47c1369aa

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Kammerjunk** [comment]
not like this fishbros

**Comment by Kromkar** [comment]
fishbros its it over?

**Comment by Theophrastus1** [comment]
oh no no no fishbros we got too cocky...

**Comment by west3436** [comment]
shrimpchads, it's our time

**Comment by SECBATON-GRIFFON** [comment]
coal

**Comment by BomberBro** [comment]
Fishcels... our response?

**Comment by SonixApache** [comment]
i can't believe this

**Comment by Eneocho** [comment]
it's over....
