### ISSUE TITLE
Please Notify Ghosts/Admins When a Player Latejoins

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#34099]
A pet peeve I've had for ages, ghosts don't wear headsets and so they never get the message from the arrivals computer. Annoying.

**Comment by pedr69** [comment]
uhh works on my machine?
![image](https://user-images.githubusercontent.com/18052467/219712066-61462bc3-8178-4f07-a63a-8829f2c96d0d.png)

the arrivals announcer doesn't go through comms anyway, it works even if you're offstation/the comms are down

**Comment by Exxion** [comment]
Sorry this isn't related to the issue at hand, but do you play the game with a fucking microscope?

**Comment by pedr69** [comment]
no, i just use 1x integer scaling, because 2x makes the chat too small and all the stretch/blur settings looks disgusting

**Comment by Kurfursten** [comment]
You got me, I didn't realize this was toggled off on my end
