### ISSUE TITLE
Delayed Replacing Glass in Solars

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34110]
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
08c4ccdebf1f3180094820b24a3dbe30cc9ed873

# Description
When putting new glass into a solar it will take somewhere around 1 o 3 seconds to do it again with a seperate solar panel
# Steps to Reproduce
take the glass out of a solar panel and put new glass into it. It might have ot be reinforced plasma glass since that's all I use
# What you Expected
to be able to quicly put the glass into the next panel since there is no loading bar
# What Actually Happened
it took 5-10 miniutes to upgrade one solar wing on box

**Comment by nervere** [comment]
Can't replicate this after testing.
