### ISSUE TITLE
Swiss army knife's Zippo lighter and match emit no light

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34125]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
d776b3a2fd4a8a847a9f52c9630af610d21c5635

# Description
Unlike normal matches and zippo lighters, the swiss army knife's lighter and match emit no light when they're the active tool.

**Comment by DeityLink** [comment]
Fixed by #34287
