### ISSUE TITLE
Exotic Seeds have no biomolecules.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#34120]
#### Description of issue
Scanned a few and none of them had biomolecules inside.
#### Difference between expected and actual behavior
Expected biomolecules, got nothing.
#### Steps to reproduce
Get exotic seeds, scan, see that it has no biomolecules.
#### Length of time in which bug has been known to occur
Since #33985 got merged.
[oversight] @twirling-jesters

**Comment by nervere** [comment]
content is reverted
