### ISSUE TITLE
MetaClub station, Full windows untouchable

### ISSUE THREAD

**Issue by The-Whargoul** [d3athrow/vgstation13#3412]
Unsure if it has been addressed. 
But the Full windows on Metastation cannot be shot out, Dismantled, nor Hit. They're virtually indestructible short of a Ripley Drill or Explosion.

**Comment by dylanstrategie** [comment]
This sounds extremely weird. I might sound a bit condescending, but are you sure about this ?
Where were the indestructible windows you noticed, if not everywhere ?
Did you get hit messages ?
Does this happens on other maps ?

I cannot see a direct reason as to why that would be happening

**Comment by ComicIronic** [comment]
>I cannot see a direct reason as to why that would be happening.

Full window + 4 one-way windows = stack of unremovable horror.

**Comment by dylanstrategie** [comment]
I'm aware of that, which is why I advocate to stop using full reinforced windows

I think alt-clicking works, but it's so fucking clunky for such a weak result (if the intruder knows about the alt-click trick, that's just one extra thing to unanchor and move)

**Comment by ComicIronic** [comment]
Altclicking requires you to be able to click on the turf.

**Comment by clusterfack** [comment]
It's been this way since it was first ported. It's some sort of issue with the windows blocking each other I think, if you delete the full window you can activate the other ones.

**Comment by IratePirate** [comment]
I didn't know this was crippling gameplay so badly since I haven't had a chance to play, i'll try to get around to at some point but i'm away from my PC so it might be some time.

**Comment by IratePirate** [comment]
Well it seems to be because they're window/reinforced instead of window/full/reinforced which has caused all the glitches. All 165 windows have been replaced.
