### ISSUE TITLE
Seed extractor doesn't display what kind of biomolecules the seed has.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#34121]
#### Description of issue
Title.
#### Difference between expected and actual behavior
Expected to see the biomolecules.
#### Steps to reproduce
Get any seed, put in extractor, don't get any biomolecule reading.
[oversight]

**Comment by Killette2** [comment]
What's a good way to do this without clutter? Maybe an icon instead of a text
(the reason I bring up clutter is because it is easy to splice all 5 biomolecules onto a single plant)

**Comment by Eneocho** [comment]
Could just shorten the names. GLCS for glucose, CHTN for chitin, STRCH for starch, CLLS for cellulose, PRTN for protein, XNPHL for xenophyll, even further could be GC, CH, ST, CL, PR, XN. I'd take a look at how the plant traits are displayed.
Icons could work, but they'd need to be implemented on all biomolecule locations to reinforce their meaning. If the extractor shows a bunch of white powder without context, it's hard to see what that means. It would only work If the plant scanner and biogenerator show the same icon next to GLUCOSE (for example), but that clashes with the text.

**Comment by Eneocho** [comment]
Biomolecules got reverted
