### ISSUE TITLE
deff theater has a light without a fixture

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34144]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
8f5ebc80422efe9dd4d9f6adfcef843761c7db2e
[deff]

**Comment by pedr69** [comment]
![image](https://user-images.githubusercontent.com/18052467/223322128-d4b4d294-996d-4ea2-b320-8fdc73eb718c.png)
huh, apparently it's a different type of light
one that can't be fixed once broken, because "large light tubes" aren't obtainable?
