### ISSUE TITLE
Library Computers looks like books during a power outage

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#3415]
The powernet shutdown event triggered earlier today. When it happened, the library computers looked like books. Maybe an issue with icon_state?
![home port xiii 2015-03-13 191026](https://cloud.githubusercontent.com/assets/10756088/6650033/680d3b30-c9ba-11e4-86d7-5fddacdd0b53.png)

**Comment by Killette2** [comment]
So what's the problem? A book is a computer without power or connection to the internet.

**Comment by Probe1** [comment]
card catalog sprites when @skowron

**Comment by Exxion** [comment]
Too tired to look at the actual code now, but I did look at the sprite files. It would appear that only the powered library computer sprite was copied from computers.dmi to library.dmi. That book is the first unnamed icon_state in library.dmi. Fix... should be simple.

**Comment by Skowron** [comment]
have no idea what are u talking about , sory

2015-03-20 7:59 GMT+01:00 d3athrow <notifications@github.com>:
