### ISSUE TITLE
Can't play instruments anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34158]
(WEB REPORT BY: confusedcactus REMOTE: 206.221.180.138:7777)
# Revision
a50eb832e5fa0f538208d061cd267c94696f07b9

# Description
Using instruments in hand doesn't bring up the music-playing interface
# Steps to Reproduce
Hold an instrument in your hand and use it inhand
# What you Expected
Music interface to come up
# What Actually Happened
Nothing

Tested with bongos and a shakashuri (as a soul rambler).

**Comment by Kammerjunk** [comment]
[34112]

**Comment by Kammerjunk** [comment]
whoops lol
#34112
#34160
