### ISSUE TITLE
Advanced welding goggles no longer provide full vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34152]
(WEB REPORT BY: juanototo2 REMOTE: 206.221.180.138:7777)
# Revision
bad457429b41d2fb397d8063be69f96d71ba04b7

# Description
See above
# Steps to Reproduce
Wear advanced welding goggles
# What you Expected
Perfect vision across all tiles of screen, like how it was before
# What Actually Happened
"Dithering" around the edges because fuck you

**Comment by xeroxemnas** [comment]
Feature, sorry kid :^)
https://github.com/vgstation-coders/vgstation13/pull/34035

**Comment by Servalfang** [comment]
dithering is based and also perish sciman

**Comment by pedr69** [comment]
oh yeah i forgot to change that to 0 after testing
dont worry im working on an alternative that will make everyone happy

**Comment by pedr69** [comment]
fixed in #34220
