### ISSUE TITLE
Can't clone people from backup if their body was destroyed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34169]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
c19080349e9fa02cd6cce1a6412013dd1e590c06

# Steps to Reproduce
scan someone in the cloner
grind them to death in the food processor
attempt to clone

**Comment by pedr69** [comment]
wait really?
is this why noone gets cloner pre-scans
because they don't fucking work?

**Comment by Exxion** [comment]
Well, that's *one* of the reasons, at least.
IIRC this bug is about ten million years old, but since nobody pre-scans, people only notice it occasionally

**Comment by Eneocho** [comment]
Ain't it cause the cloning system needs a mob to hold the mind to clone? 
It's also the reason for that occasional bug where the guy reincarnated as a mouse/diona/pai/space hobo/etc but was clonescanned beforehand, so he gets cloned and the mind gets transferred.

**Comment by Theophrastus1** [comment]
It works for eimplants, I have used this fairly recently.
