### ISSUE TITLE
Jukebox broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34167]
(WEB REPORT BY: dangitmaster REMOTE: 206.221.180.138:7777)
# Revision
c19080349e9fa02cd6cce1a6412013dd1e590c06

# Description
Juke broke, no playlists on the juke, and i've checked every round for the past 5 rounds now
# Steps to Reproduce
>Turn on juke
>Nothing plays
>Go to selectable playlists
>No playlist
# What you Expected
>Music
# What Actually Happened
>Ambient noise and no sweet tunes

**Comment by Kurfursten** [comment]
Cannot reproduce, check your settings

**Comment by d3athrow** [comment]
it was broken but i fix @Kurfursten

**Comment by Theophrastus1** [comment]
Huh, I wonder if this is why escape music wasn't playing yesterday
