### ISSUE TITLE
[BOX] Borked disposals north of fitness

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3416]
![2015-03-14_11-27-58](https://cloud.githubusercontent.com/assets/4788171/6651300/397da894-ca3d-11e4-8436-da373595814f.png)

**Comment by dylanstrategie** [comment]
I did map changes to that area, but this is rather odd, the disposal connections looked fine when i wrapped up

I'll look into this asap. It seems like the disposals pipe is simply going under the wall, but I need to make sure

**Comment by frangi** [comment]
it's actually missing.

**Comment by dylanstrategie** [comment]
Then I'll look into it asap, just need to set up my workspace again because holy crap all those issues

**Comment by dylanstrategie** [comment]
I just checked, and I am absolutely certain no pipe is missing here, there is a corner in mapmaker

Try using a T-ray scanner
