### ISSUE TITLE
Heavy Disintegrator costs more for non greys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34162]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
c19080349e9fa02cd6cce1a6412013dd1e590c06

# Description

the Heavy Disintegrator costs 16 for non grey and 12 for grey 

# Steps to Reproduce

buy a Heavy Disintegrator

# What you Expected
it to cost the same 

# What Actually Happened
it costs more

**Comment by wotisjanitor** [comment]
feature

**Comment by Dacendeth** [comment]
Not an bug, race specific discount.

**Comment by angryturnip** [comment]
We will get our top men on this immediately sir

**Comment by Kurfursten** [comment]
This was explicitly a design choice

**Comment by xeroxemnas** [comment]
Embarrassing ESL moment
