### ISSUE TITLE
Body Archive Failing

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#34178]
The WHOLE POINT of the body archive is to have a backup in case someone gets gibbed or sharded and yet if this happens it spawns them as a brain mob instead. Disaster!

Also keep clothes seems to do nothing all(?) of the time
Also, SPAWN+TRANSFER often doesn't seem to actually transfer their mind

**Comment by Theophrastus1** [comment]
how much you wanna bet an adam or kanef pr did this

**Comment by DeityLink** [comment]
> how much you wanna bet an adam or kanef pr did this

My money on #31840 since that's the only PR that touched the feature after I left. Barely two months later.

edit: it was so much worse than I anticipated, also both.
