### ISSUE TITLE
Power alerts persist for too long

### ISSUE THREAD

**Issue by frangi** [d3athrow/vgstation13#3417]
Even if the APC is 50%+ and charging, the area still gives a power alert.

Maybe alerts should go away as soon as the equipment thresold is reached (the same thing that triggers the alert)

**Comment by dylanstrategie** [comment]
Ideally, the alert lifting threshold should still have a small difference to avoid overlapping or spamming, 5 % should do it

**Comment by Kurfursten** [comment]
@clusterfack This is a FR not a bug, remove bug tag

**Comment by Probe1** [comment]
👌

**Comment by Exxion** [comment]
Guess what bitch
(#13299)
