### ISSUE TITLE
emagged wrapping machine doesn't wrap people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34182]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
da765799ff2c8970f8afdca50bf657d52ab2c561

# Description
it just fucks with your vision and spits out an empty crate lmao
i will fix this

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Hands moved faster than my brain here - this isn't the emagged machine behavior but instead the machine with syndie wrapping paper in it. It also didn't wrap packages normally using it, so I assume this has something to do with the use of syndie wrap.
