### ISSUE TITLE
Transit Tube Station deconstruction dupes parts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34209]
(WEB REPORT BY: kettuthefox REMOTE: 206.221.180.138:7777)
# Revision
110eeb7446d0ebb14a7a50fdf8b5c4a635c34170

# Description
Disassembling a Transit Tube Station leaves a functional copy of it behind, while the glassless frame can be unwrenched and dragged away
# Steps to Reproduce
Cut the glass off of a transit tube station at the R&D outpost on Box Station's asteroid, unwrench it and move the frame via dragging, leaving behind a functioning station and a glassless frame. Performed twice.
# What you Expected
The station to be deconstructed
# What Actually Happened
The station continued to function as normal, despite creating a disassembled station on the same tile

**Comment by pedr69** [comment]
someone really oughtta fix the tubes

**Comment by Eneocho** [comment]
I could swear this was fixed already.
