### ISSUE TITLE
make bunsen burners actually useful

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34204]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
110eeb7446d0ebb14a7a50fdf8b5c4a635c34170

# Description
make bunsen burners actually useful. theyre cool i like addin the fuel to them n stuff n turning them on but theyre fuckin usless
# Steps to Reproduce

# What you Expected
bunsen burners always fuckin sucked u shouldnt have to use cauterys n shit to heat shit up 
# What Actually Happened

**Comment by anaxosa** [comment]
dont make me have to heat up chemicals please i cant take it

**Comment by west3436** [comment]
elaborate

**Comment by tinysaturn** [comment]
it would be nice if they started pre-filled with welding fuel at least
