### ISSUE TITLE
*whistle does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34219]
(WEB REPORT BY: gallywix4 REMOTE: 206.221.180.138:7777)
# Revision
9106c7e23d9d71f5e453fba894e4a1bb85521a5a

# Description
the whistle emote does not show up in chat
# Steps to Reproduce
say *whistle
# What you Expected
anon whistles
# What Actually Happened
nothing

**Comment by Securitymain** [comment]
Confirmed on the test server
Funny thing is that the shorthand *whis works, other than that none of the code is any different from the other emotes

What the fuck
