### ISSUE TITLE
solar panel assembly

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#3422]
Can't pick them up any more as a mommi not sure if its the same thing as a human mob.

**Comment by dylanstrategie** [comment]
If I'm not mistaken, I changed solar panel assembly type to machinery to cut out on lazy pathing, so this is intended

This is a non-issue really, unless this creates other problems

**Comment by clusterfack** [comment]
You can drag them around or drag them around in crates now too, this should be fine the way it is.
