### ISSUE TITLE
cuffing a briefcase to yourself(and removing it) makes the cuffs permanently glued

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34221]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
9106c7e23d9d71f5e453fba894e4a1bb85521a5a

That's some handcuffs. They are small
It's stuck to your hands!

**Comment by kacurasuo** [comment]
duplicate of #33442
