### ISSUE TITLE
cant throw under max range anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34234]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
0c89bb4a2c328e88e773c3b5e3a1ffc2d3f786db

@SECBATON-GRIFFON

literally what the fuck did you do

**Comment by SECBATON-GRIFFON** [comment]
i did actually test throwing for this PR, just mainly with the buildmode tool
