### ISSUE TITLE
Grinding Death Nettles is broken

### ISSUE THREAD

**Issue by Pastamadness** [d3athrow/vgstation13#34237]
Death nettles with modified phytochemistry genes seem to be incredibly fucked up.
I just witnessed a botanist creating nettles with 8.2 units of valerenic acid and 40.8 units of plasticide.
Grinding those samples in the all-in-one-grinder net NOTHING, not a single reagent. It was simply gone.
Grinding those samples with a mortar net 10 phenol, the reagents of generic death nettles, despite those samples not having the reagent at all!

Sadly I couldn't do further testing with other chemicals or regular nettles.

**Comment by Killette2** [comment]
This sounds familiar but I can't put my finger on it
