### ISSUE TITLE
ANFO chem grenades didn't go KABOOOM

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#34257]
#### Description of issue
Was on LampreyStation and made a 560+40 ANFO EX-Grenade, heated by hot phalanximine. Once detonated the anfo reaction (the fuckyou explosion) didn't happen, only a puny 1 tile breach.
```
[03:26:13]DEBUG: Runtime in <b>chem_grenade.dm</b>, line <b>300</b>: <b>Cannot read null.total_volume</b> <a href='?_src_=holder;viewruntime=[0x2108a0bb]'>[view]</a>
[03:26:13]DEBUG: Runtime in <b>holder.dm</b>, line <b>251</b>: <b>Cannot execute null.pulsed().</b> <a href='?_src_=holder;viewruntime=[0x2108a796]'>[view]</a>
```
Another player then repeated the same reaction with less volume and the explosion was equally underwhelming.
I suspect it's an issue cause the recipe check for fuel explosions is earlier on the reagent_recipes.dm than the check for the ANFO reaction, so the system never detects the ANFO reaction, as the conditions for ANFO bombs also meet the conditions for Fuel bombs.
#### Difference between expected and actual behavior
Expected a sizeable KABOOM.
Got babby shit explosion that barely breached.
#### Steps to reproduce
Be on lamprey. (I suspect this is irrelevant)
Make ANFO grenade.
Detonate said grenade.
Be disappointed you wasted time making the wacky kaboom reaction instead of the classic waterpot or nitro.
#### Length of time in which bug has been known to occur
No earlier than #34165.
[consistency][bugfix]

**Comment by Eneocho** [comment]
Checked, the reaction is working correctly-ish, but the explosions are ridiculously underpowered. Plasma, ANFO and fuel bombs all barely explode with this.

**Comment by Eneocho** [comment]
@SECBATON-GRIFFON

**Comment by SECBATON-GRIFFON** [comment]
i only really tested this with actual heating from the likes of the cautery and bunsen burner

**Comment by SECBATON-GRIFFON** [comment]
> Checked, the reaction is working correctly-ish, but the explosions are ridiculously underpowered. Plasma, ANFO and fuel bombs all barely explode with this.

i tested the grenades myself (300 units 20C fuel 300 units 999C phalanx and the same with a plasma one instead of fuel) and they both caused a 0,1,3 and 1,2,4 breach as intended for each, but ANFO was only 0,1,3

**Comment by Eneocho** [comment]
Odd. I tested them all on 515 on localhost and they all were barely exploding.
