### ISSUE TITLE
ingame changelog is 2 months out of date

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34269]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
i thought it updated when the serb got recompiled but apparently not
does a highly paid janitor have to manually update the changelog?

**Comment by Exxion** [comment]
There's a bot that does it but I guess it broke again

**Comment by SonixApache** [comment]
ping @PJB3005

**Comment by nervere** [comment]
this has been fixed and the stuff that wasnt on the changelog has been added manually
