### ISSUE TITLE
Being cloned removes wizwar minion status

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34267]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
3cc34a3b27e1586785d3984548a1d80140eb3dea

# Description
Feature or bug?
You decide!

**Comment by SECBATON-GRIFFON** [comment]
probably balances it a bit for all we know

**Comment by nervere** [comment]
Wizwar minions are removed now, thankfully.
