### ISSUE TITLE
Colored wizard civil war members aren't logged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34266]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
3cc34a3b27e1586785d3984548a1d80140eb3dea

# Description
the civil war of casters that wizards can purchase which colors the crew doesn't show the members of each team in the round end screen
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by SECBATON-GRIFFON** [comment]
was the wizard alive at the end of that round? it wipes the members list when they die, though i'm not so sure how clear it is to converts when that happens

**Comment by nervere** [comment]
Wizwar minions are removed now, thankfully.
