### ISSUE TITLE
Reinforced walls can be used to create infinite metal

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#3427]
1.Find an rwall
2.Deconstruct it into a reinforced girder
3.Use the 1 plasteel you got from deconstructing it onto said girder (You now have a brand new rwall and two metal rods)
4.Repeat steps 1-3 until you have an assload of metal rods and then weld them into sheets.

**Comment by BestName** [comment]
And here's a needlessly long .gif for your amusement.
![a totally feasible method of duping metal](https://cloud.githubusercontent.com/assets/3892856/6658894/47c0802c-cb80-11e4-9567-ed233be74044.gif)

**Comment by Kurfursten** [comment]
While troubling from a realism perspective, this is so slow compared to just mining or ordering loads of metal sheets that there is no balance issue.

**Comment by BestName** [comment]
Yeah I know it's not exactly feasible but it's still a bug.

**Comment by Shaska-** [comment]
Believe it works with grilles as well.
Kick grilles till it breaks and gives you a rod.
Use wirecutter on broken grilles to recieve 2 more rods
Use rods to create new grille and repeat.

**Comment by Exxion** [comment]
@Shaska- Yep. I was about to mention that.
I was really confused once when I broke a window to get into an area then rebuilt it and had leftover rods.

**Comment by AutismSpider** [comment]
Nah it can be set to not drop rods

**Comment by dylanstrategie** [comment]
The rwall deconstruction should likely be set to not drop rods, OR the rwall construction steps could use rods. But it has to be one of them

As for the grilles, that's most likely an oversight
