### ISSUE TITLE
Ruskie DJ Station's Radio Transmitter is not wired roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34278]
(WEB REPORT BY: makagame REMOTE: 206.221.180.138:7777)
# Revision
66e3f972de6fbe5ceaffb551813b6475dd665db6

# Description
Ruskie DJ Station's Radio Transmitter is not wired roundstart
# Steps to Reproduce
Visit Ruskie DJ Station and try to enable Radio Transmitter
# What you Expected
Radio Transmitter
# What Actually Happened
It demanded to be connected to a power source, I had to manually wire it to the station's SMES.

**Comment by pedr69** [comment]
#32908
