### ISSUE TITLE
you can't dip cookeis in milk

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34283]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
66e3f972de6fbe5ceaffb551813b6475dd665db6

# Description
wanted to dip cookies in milk
# Steps to Reproduce
try to dip a cookie 
# What you Expected
dip it 

# What Actually Happened
no dip

**Comment by Eneocho** [comment]
https://www.youtube.com/watch?v=4IdzM1kmP_A

**Comment by Eneocho** [comment]
Requesting for cookies dipped in a jar with milk to dissolve into mush like materials do when dunked in sacid.
