### ISSUE TITLE
Metaclub - mechanics have no access to minisat tubes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34284]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
66e3f972de6fbe5ceaffb551813b6475dd665db6

# Description
Mechanics need access to the minisat tubes since telecomms is over there (telecomms tech is an alt title for mechanic we are very valuable)

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by pedr69** [comment]
yeah the transit tubes are fucked something fierce, you get "access denied" everytime, even with a captain ID
somehow there isn't an issue about it and noone seems to care much
