### ISSUE TITLE
Advanced Security Cameras

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#3429]
After building it and trying to use it i got nothing no UI for it etc
![advanced cameras](https://cloud.githubusercontent.com/assets/10268342/6660489/82066174-cb68-11e4-903f-c4de2b9c96e0.PNG)

**Comment by Kurfursten** [comment]
Were you attempting to use it as a human or silicon?

**Comment by dylanstrategie** [comment]
NanoUI interfaces are ridiculously wonky. Humans and silicons alike risk dropping the ball at some random point during the shift. At that point, nothing but prayer will make the NanoUI come back

This seems to happen with all NanoUI interfaces, and might even happen for everyone once it's broken for someone (had it once as Medical Cyborg on Crew Monitor, Nurse couldn't access it too)

**Comment by ComicIronic** [comment]
Did you Resend Resources?

**Comment by AutismSpider** [comment]
Using it as a mommi at the time and i did resend resources.

**Comment by Kurfursten** [comment]
@AutismSpider Is this still happening?

**Comment by AutismSpider** [comment]
Hold i test it
