### ISSUE TITLE
Why is there plastic on rwindows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34312]
(WEB REPORT BY: inorien REMOTE: 206.221.180.138:7777)
# Revision
c9830afd36a3223589265e1db302ea1f8051558d

# Description
You pry the reinforced window from its frame.

You unfasten the reinforced window's frame from the floor.

You fasten the reinforced window's frame to the floor.

You can't pry the sheet of plastic off from this side of the reinforced window!

You pry the reinforced window into its frame.

You fasten the reinforced window to its frame.

# Steps to Reproduce
Just construct rwindows

# What you Expected
For my construction of glass and metal to not speak of plastic

# What Actually Happened
It spoke of plastic

**Comment by DeityLink** [comment]
Already fixed by #34310
