### ISSUE TITLE
you can run into your own buckshot that you shoot, hitting yourself

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34316]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
e1311a5d8450c523a5d51b9e0ec2a5794d0e64f6

**Comment by anaxosa** [comment]
maybe ur just walking too fast. give the slugs some time...

**Comment by pedr69** [comment]
duplicate of  #34072
use the search next time. and no necrobumping. locked and banned.
