### ISSUE TITLE
Agent ID card removes Sec HuD

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34327]
(WEB REPORT BY: calzilla1 REMOTE: 206.221.180.138:7777)
# Revision
6dde500ce254d492226844f7b578dfdcf87511f4

# Description
>Be flukie
>Want to SLETH it
>Change name to Kevin Smith, head to locker room and change clothes, jumpsuit, bag, everything. No witnesses
>Nukies go loud, head to the bridge to check for an opening
>GET IMMEDIATELY LIT UP BY SEC
>Die
>deadchat salt incident of 2023
>Seethe at the homosexual security birds on why they lit up some seemingly random assistant
>No HuD

This is gay and retarded and I demand the choder who broke this to be valided by shitcurity for a thousand years
# Steps to Reproduce
Buy agent ID card
Set a name
Have gay bird sec see you
Cry and die
# What you Expected
For my character to have a HuD
# What Actually Happened
No HuD and no nuke disk

**Comment by ErrorsWindows** [comment]
i think this is because the security hud corroborates with the security records rather than just relying on the card itself, maybe try it again on the testing server but fill out each detail completely instead of just the name and occupation

then again it could also just be a feature of the agent ID, for example one of its often forgotten features is that the AI cannot quick-jump to your name using the cameras and will have to find and follow you manually

**Comment by SacredAtom** [comment]
skill issue

**Comment by pedr69** [comment]
feature
agent ID's also prevent AI's from seeing you in the "track with camera" list
they also also prevent medhuds from showing your healthbar which is why the medhud in the nukie ship's basically useless for a medic

**Comment by calzilla1** [comment]
If this is a "feet-chur" then wouldn't this make the agent ID all but useless except for RP shenanigans. Why not just save the TC and slap two pie tins together for a free "fuck you AI and sechud" hat?

**Comment by pedr69** [comment]
actually i have no idea why it hides the huds, i don't see any checks for a syndicate ID
from the little i've fiddled with the files i've discovered there's two separate hud things, one that gets shown to living people with glasses on and a different one for ghosts

**Comment by pedr69** [comment]
turns out it's this
https://github.com/vgstation-coders/vgstation13/blob/6dde500ce254d492226844f7b578dfdcf87511f4/code/modules/mob/mob.dm#LL2221C1-L2221C1
turns out it's the ninja GLOVES that stop them from being tracked by the AI, not the mask

**Comment by Theophrastus1** [comment]
skill issue

**Comment by Hinaichigo** [comment]
So there's no HUD marker or there's a ? marker. Seems like it should maybe be the latter.
