### ISSUE TITLE
Swiss Army Knife: Zippo lighter can no longer be used in surgery steps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34321]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
6dde500ce254d492226844f7b578dfdcf87511f4

# Description
The swiss army knife's zippo lighter module used to be able to be used to cauterize incisions but now it doesn't work anymore

**Comment by SonixApache** [comment]
can't light cigs with it either
probably can't do anything with it anymore
@DeityLink

**Comment by tinysaturn** [comment]
probably result of https://github.com/vgstation-coders/vgstation13/pull/34287

**Comment by DeityLink** [comment]
What in the goddamn, well I'll fix that tonight. I found the cause.
