### ISSUE TITLE
Cult sacrificing causes ZAS deathtraps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34332]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
c69e5e7ba583a1d49673d57b292e19c137ac7679

# Description
1. offer a sacrifice trade deal to NarSie
2. NarSie offers instant total ZAS annihilation since the walls got removed
3. die!
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Doesn't happen anymore since bloodstones don't spawn without admin intervention
