### ISSUE TITLE
The Tesla Gun Is Very Broken

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#34334]
I have no idea how it could be in this state if it was tested.
* Doesn't work if capacitor is inserted
* Does work if no capacitor inserted
* No cooldown 
* Spams admins with ADMIN LOG: UNKNOWN/(no longer exists) shot UNKNOWN/(no longer exists) with a /obj/item/projectile/beam/lightning. Wait what the fuck?

**Comment by Exxion** [comment]
I do happen to be on Ambien right now but I don't see anything glaringly wrong with the code, or anything that would at all explain it firing with no capacitor inserted

**Comment by Exxion** [comment]
* Can reproduce gun not firing with valid capacitor inserted
* Cannot reproduce gun firing without a capacitor inserted
* Cannot *attempt* to reproduce the other ones because I can't get it to fire at all

**Comment by Exxion** [comment]
Wow, that was fucking confusing to diagnose.
The issue is that the tesla *projectile* (intentionally) initiates an infinite loop in `New()`, so its `New()` never completes, and all the code waiting for the projectile to finish spawning just gets held up forever

**Comment by Kurfursten** [comment]
I never got it to fire myself, but the guy in game who DID get it to fire told me he did so by removing the capacitor.

**Comment by Exxion** [comment]
My best guess as to what happened was that the blocking loop got killed at some point by BYOND's recursion limit and the initial attempt to fire went through right as the guy was fucking around with it, or something

**Comment by Exxion** [comment]
Oh wait I know
The blocking loop got killed and the projectile got loaded into the chamber. At this point, it no longer matters whether or not the capacitor is inserted; if a round is in the chamber, it fires regardless
I'm not sure about why it wouldn't fire immediately upon the blocking loop being killed though

**Comment by pedr69** [comment]
yeah i spammed fire and nothing happened, not even a click
removed the capacitor and spammed some more and it fired
i also fed 2 capacitors inside and one of them got deleted

**Comment by Exxion** [comment]
#33060 broke it by the way
