### ISSUE TITLE
Arcane Temper Does Not Remove Upon Wizard Death

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34339]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
4cc493adcbdf8032ba30a5406b14219feec03a65

# Description
I'm 100% certain it was supposed to but I'm still getting teleported via untracable invisible doors
thanks kanef

**Comment by nervere** [comment]
Seems this was meant to be a feature. Kanef is repo-banned so...
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/64dd661a-0bbf-4f43-99d5-415cace7fe90)

**Comment by jwhitak** [comment]
Fixed by #34428 according to @nervere
