### ISSUE TITLE
Giant Spider: Spiderling growth level UI element is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34331]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
6dde500ce254d492226844f7b578dfdcf87511f4

# Description
Spiderling growth % UI element does not update and is always stuck at 1% despite the growth stat properly increasing.

**Comment by tinysaturn** [comment]
@DeityLink
