### ISSUE TITLE
Spiderlings are strong

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#3433]
![spiders](https://cloud.githubusercontent.com/assets/3892856/6677589/1cf994ea-cc3a-11e4-98a1-f434d196a83e.PNG)
Holy shit, are they supposed to do that?

**Comment by Zth--** [comment]
They shouldn't

**Comment by dylanstrategie** [comment]
Spiderlings are just spiders without an attack or aggro proc (among other things), but mobs are set to hulk smash shit in their way regardless

Most likely a return missing somewhere

**Comment by ConkerDev** [comment]
Any progress?

**Comment by Killette2** [comment]
Closable. A prime example of how issues get ignored and forgotten, or solved and the issues never get closed properly.

**Comment by BestName** [comment]
So which one is this?

**Comment by ConkerDev** [comment]
Can be closed?

**Comment by BestName** [comment]
![mystery](https://cloud.githubusercontent.com/assets/3892856/14611145/7db9defe-0599-11e6-98fc-54ec42500557.gif)

**Comment by Zth--** [comment]
I'm almost sure this was fixed long long ago

**Comment by BestName** [comment]
Alright
