### ISSUE TITLE
Rad Storms on Box Showing Medbay as Safe

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34340]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
4cc493adcbdf8032ba30a5406b14219feec03a65

# Description
Similar to [18798], there's no flashing green lights in Medbay Box during a radstorm, but you get murdered by radiation all the same.

**Comment by Inorien** [comment]
Related to #34289 perhaps

**Comment by pedr69** [comment]
yeah radstorms are fucked, the green glow doesn't appear in some rooms at all and doesn't vanish when the storm ends

**Comment by nervere** [comment]
Closing this as it's the same as #34289
