### ISSUE TITLE
Linking Cloning Pod to the Cloning Console seems impossible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34342]
(WEB REPORT BY: sugarbone REMOTE: 206.221.180.138:7777)
# Revision
4cc493adcbdf8032ba30a5406b14219feec03a65

# Description
Can't link the console to the pod properly.

# Steps to Reproduce
Attempt to connect the cloning pod to the console (freshly built).

# What you Expected
To have some way to actually link it.

# What Actually Happened
Neither the pod nor the console were viable for linking. The pod summons another menu when clicked with the multitool (machine output). The console doesn't have the ID tag necessary to make the connection from its side.

**Comment by Inorien** [comment]
open multitool on pod
add machine to buffer
click console

**Comment by Kurfursten** [comment]
You need to screw it open
