### ISSUE TITLE
Mindswap is broken as hell

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#34347]
Just had a round where:

1. I mindswapped into people and only _I_ would fall asleep, meaning I'd be toolboxed to death moments later. (Happened twice)

2. Most of my spells would be lost upon swapping, I had conversion, norobes, and mindswap and I'd lose everything except conversion every time I swapped, with the rest not coming back until I had cast conversion a few times if they came back at all.

3. Weirdest of all, there was a point where I mindswapped into another wizard, then I was taken to surgery and my brain remove. A weird ghost head item popped off when the minion used surgery to cut my head off and apparently he took 2 brains out. When my brain was put into a new body and I used mindswap, instead of being put in the CE next to me it put me in a generic invisible "living" mob that could punch and cast spells. About 5 minutes later I was thrown into the CE body with no mindswap spell and that's where the story ends. 

What the hell happened to this spell, I recall it working alright a few months ago.

**Comment by Exxion** [comment]
Wow. What the fuck?
The invisible mob named "living" makes me suspect someone made a typo in the code, but there are other possibilities
Also this is almost certainly multiple distinct bugs
