### ISSUE TITLE
Bagel: Waste line defaults to recycling line, which is bad

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34373]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
3e0804048d6433b5c940928404e757602a2b6027

# Description
We just had the air line freeze over because supercooled waste was being pushed right back into the air tanks. Bad design.

**Comment by Inorien** [comment]
[bagel]
