### ISSUE TITLE
Wizard Conversion Spell SUCKS!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34391]
(WEB REPORT BY: west3436 REMOTE: 206.221.180.138:7777)
# Revision
62635ef2fcd070eeaa6b51eeeb27ca64c274e4e7

# Description
The spell must not give converted minions a message as both wizards on a team with fellow red crewmembers were deliberately teamkilled. Haven't tested it, but I presume converted crewmembers receive no message telling them "DON'T KILL THE WIZARD THAT IS THE SAME COLOR AS YOU"
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by nervere** [comment]
Feature has been removed. #34660
