### ISSUE TITLE
Screwdriver quickswap defaults to wallet over toolbelts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34406]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
e7e8bc77248c37512b0d154cdfe1365bb502c551

# Description
Pressing equip hotkey 'e' while a screwdriver is in your hands will prioritize sending it into your wallet instead of your toolbelt. This is annoying.

# Steps to Reproduce
Place screwdriver in hand with toolbelt and wallet equipped. Press e.

# What you Expected
Screwdriver goes where it should.

# What Actually Happened
Very minor irritation and reduced qol.

**Comment by west3436** [comment]
>he doesn't keep an entire screwdriver in his wallet, just in case

**Comment by Eneocho** [comment]
ngmi

**Comment by pedr69** [comment]
damn the wallet can hold all sorts of wacky shit

https://github.com/vgstation-coders/vgstation13/blob/3ecd284acad01a551a4c7eb6908c1b2b18cb58d5/code/game/objects/items/weapons/storage/wallets.dm#L23
it can also hold 20 wads of cash as opposed to a briefcase which can only do 14
