### ISSUE TITLE
Orange Hard Hat on Bugs is Cursed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34412]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
3ecd284acad01a551a4c7eb6908c1b2b18cb58d5

# Description
Image incoming.

**Comment by jwhitak** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/69739118/7d5b87e8-dc9f-4e24-aa0e-fed68ed4cc45)
Behold. The powered-on hat is OK, but the unpowered one... yeesh.

**Comment by pedr69** [comment]
wait, orange hardhat???
i know there's a blue one in the derelict vendor but where do you get the orange one?
