### ISSUE TITLE
The reason why wizards dying don't bless arcane tampered doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34422]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
3ecd284acad01a551a4c7eb6908c1b2b18cb58d5

# Description
It's caused by the door's bless() proc calling the linked door's bless() proc inside, stopping the death blesses on that door in the list of a mob's arcane tampered atoms, fixed by just setting arcanetampered to FALSE on the other door in bless() along with arcane_linked_door to null

**Comment by nervere** [comment]
This doesn't explain why it doesn't work for all other atoms and why 3-5 death calls are needed for the entire list to be cleared.

**Comment by nervere** [comment]
The actual explanation as Kanef told me is that the arcane-linked doors get stuck in a loop blessing each other and so it never finishes blessing everything else. The fix as presented in #34428 was tested and now the removal of arcane tampering works without any hitch.
