### ISSUE TITLE
I DID BUT CAN RESPAWN PART 2

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34425]
(WEB REPORT BY: loveender REMOTE: 206.221.180.138:7777)
# Revision
684c5eb98f4006c575b52cd61003e0c32bce99ed

# Description
Follow up from previous bug report
# Steps to Reproduce
So I obsed instead of joining after I had the option to rejoin the game from the previous crash.
I took a gamble and clicked the red xenoarch stone that spits out clones of whoever touches it.
Anyway clicked it, game crashed again.
Reloaded and I'm able to rejoin the game again

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
This and the previous one both sound like what happens when your mob gets deleted before you get moved to a new one

**Comment by nervere** [comment]
Tested this extensively locally, replicating all conditions as described by the players that round. No luck with replication. LoveEnder did mention he's on 514, though. Being on 515 may prevent me from experiencing the crash, I don't know.

**Comment by Exxion** [comment]
It's some obscure bug with mind transfers causing `active` to stay on in a mind it shouldn't be. Fix is known. I'll do it later if somebody else doesn't beat me to it.
This should be rare.

**Comment by Killette2** [comment]
This has happened to me as well many months ago, same exact bug
