### ISSUE TITLE
Quantum Camera Film 

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#34447]
#### Description of issue
Camera film can go into the negatives.
![image](https://github.com/vgstation-coders/vgstation13/assets/15067109/885296da-cdd5-4741-9674-8398e8d338b9)

#### Difference between expected and actual behavior
Expected film to run out when photos left hit zero. Instead could keep taking pictures as counter got increasingly negative.

#### Steps to reproduce
Take camera (sepia specific possibly)
Take lots of pictures

#### Length of time in which bug has been known to occur

No clue.

**Comment by Servalfang** [comment]
honestly just let cameras be infinite

**Comment by Exxion** [comment]
I'm not sure how this happened. While the code does exhibit the ancient programming mistake of checking if the value is equal to zero instead of less than or equal to zero, it should still stop at zero.
