### ISSUE TITLE
Lighting is really slow right now

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34476]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
9bbc953ff111d2fa0e9929396fbe26be78fbb82f

# Description
we're on roid, no idea what or why, but every lighting update takes upwards of ten seconds

**Comment by SonixApache** [comment]
this was just a master controller failure so this can be closed
