### ISSUE TITLE
If You Put A Bodybag With a Person Inside It Through A Recycling Furnace It's Deleted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34484]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
9bbc953ff111d2fa0e9929396fbe26be78fbb82f

# Description
if you put a bodybag full of people through the recycling furnace it deletes all the bodies with no gore remains etc

**Comment by Eneocho** [comment]
Is this a gruesome way to qdel someone or does it only work with dead bodies?

**Comment by pedr69** [comment]
with how the title's capitalised it sounds like something out of the ingame spam event/PDA newscast

**Comment by Eneocho** [comment]
lmao yeah I can see that
"YOU WON'T BELIEVE WHAT HAPPENS IF YOU TRY TO RECYCLE A BODYBAG WITH SOMEONE INSIDE, JUST FOLLOW THESE STEPS! STEP 5 WILL BLOW YOUR MIND!!!"

**Comment by kacurasuo** [comment]
did we ever fix the bug where turning a bodybag into a morgue tray qdels people either
edit: yes we did

**Comment by DeityLink** [comment]
It should leave some ashes on the conveyor belt maybe

**Comment by kacurasuo** [comment]
revising my previous comment, you can still qdel people by closing the morgue tray on them during the interaction time of deconstructing it

**Comment by pedr69** [comment]
yeah `do_after()` and `alert()` release nervegas in a lot of situations if you hit them multiple times or do other stuff at the same time

**Comment by DeityLink** [comment]
which is why you should always sanity check, people.
