### ISSUE TITLE
Additions to Clown's Sound Synthesizer

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3448]
I think it should have a laughtrack and a rimshot. Possibly other sound effects you'd find in comedy/cartoon media like slide whistles.
Just something to make it useful to the clown for more than making people think there's trouble when there isn't.

**Comment by CptWad** [comment]
Just copy down all the sound effects from ed edd and eddy

**Comment by Cutelilduck** [comment]
I like the sitcom laugh track and rimshot idea.
