### ISSUE TITLE
H.O.N.K. Can't be Built

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3449]
Using a bike horn on an assembled H.O.N.K. chassis does nothing, and no other parts can be attached.

**Comment by ComicIronic** [comment]
Works fine locally.
![Honk](http://puu.sh/gDNE1/58ee15fb55.png)

You need to submit more detailed bug reports, because I can't tell if this is a code issue - which it doesn't seem to be - or if you just fudged construction.

**Comment by CptWad** [comment]
Its something with improper asseblies
I had a round where we could not do anything to a ripley and had to build it again from scratch its a rare bug but worth a title change and a look out for

**Comment by Shadowmech88** [comment]
> Its something with improper assemblies

Do we know what causes it, exactly? How do we find out?

**Comment by CptWad** [comment]
I think the assembiles become another item if something happens to them
When examining the bugged honk today I read "it is an  item" so I guess shit is just breaking there.

**Comment by Exxion** [comment]
Yeah, I've been unable to wire spacepod frames twice now. There was a time between those two times when it worked perfectly, though.

**Comment by ComicIronic** [comment]
Alright, I've found the issue: using the incorrect first step in construction fires a runtime, meaning that the busy check is started but never stops, since the stack trace blocks any further code.

**Comment by SkowronX** [comment]
This seems to happen with regular mechs when you fully assemble it on the chassis.
