### ISSUE TITLE
War Ops cannot make announcements due to Bluespace Blocking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34494]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
0593a00132f3333fb530cdc471a43b237fe2eceb

# Description
Due to blocking the shuttle/bluespace, War Ops cannot send taunting messages to the Station as they get scrambled by the mentioned blocking.

**Comment by DorainGrey** [comment]
Hmm not sure how easily I can fix this one to be honest, need to go back to custom event code which people complained about.
