### ISSUE TITLE
Cloak of Cloaking + Staff of Change

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#34491]
what's the counter?

**Comment by west3436** [comment]
[I ded]
T-ray scanners and flashbangs, as always

**Comment by GreatBigFailure** [comment]
Firing wildly in every direction

**Comment by DeityLink** [comment]
T-Ray Scanners show cloaked wizards?

**Comment by Kurfursten** [comment]
does the cloak of cloaking not require 2 hands to wield anymore?

EDIT: it does... how are you getting a third arm to use the staff?

**Comment by angryturnip** [comment]
As for staff of change, pacid or anything that makes you drop what you're holding

**Comment by DorainGrey** [comment]
You cannot use these at same time. You can't even cast a lot of spells under cloak.

**Comment by DeityLink** [comment]
> You cannot use these at same time. You can't even cast a lot of spells under cloak.

He made himself a martian to use both

**Comment by Kurfursten** [comment]
Doesn't that come at a huge tradeoff of losing most of your slots, including suit, exosuit, id, belt, pockets, backpack, gloves, shoes, and mask? Counter it by asking the AI to lock him down and shock the doors.

**Comment by DeityLink** [comment]
I learned post round about the hand limitations on the cloak (and thus the deduction that they had turned themselves into a martian) and the abilities of the p-ray scanner. I failed the meta knowledge check, but now I know, and knowing is half the battle.

**Comment by SonixApache** [comment]
fill the halls with buckshot
maybe get in a mech so you're staff-proof too
