### ISSUE TITLE
(WEB REPORT BY: qbertnorf REMOTE: 198.245.63.50:7777) 'Unbuildable' Atmospherics computers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3450]
&gt;Revision (Should be above if you're viewing this from ingame!)
77d015a158f233462ac2654536df8997c1e88228 
&gt;General description of the issue
Unscrewing and rescrewing atmospherics computers turns them into useless 'computers'

&gt;What you expected to happen

&gt;What actually happened

&gt;Steps to reproduce if possible

**Comment by PJB3005** [comment]
I'm pretty sure this is not an issue, if you're talking about the sensor viewing atmos computers, add new sensors with a multitool menu, if it's the tank control computers, reset the ID tags, and add the sensor

**Comment by clusterfack** [comment]
This isn't an actual issue besides the name of the computer being lost, as PJB said you can fix everything with a mutltiool
