### ISSUE TITLE
Occasionally you cannot examine someone to tell if they are alive or not

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3451]
happened to two different people on two different corpses
A specifically terrible round but I examined someone and received none of the purple "He has no pulse..." text. Same happened again with someone else when examining my body and they thought that I was alive.
Strangely in both cases I think the text said that the corpses were "Braindead" rather than dead. Braindead because our ghosts were not in our corpses I imagine. This resulted in me putting the HoS dead in the captains office with a note saying to keep him alive and my corpse being put in perma thinking I will get punished in there.
Obviously needs more testing but if it happens twice in a round than it is something,

**Comment by ComicIronic** [comment]
This shouldn't be possible.
The text for braindead bodies only occurs if the person isn't dead.

**Comment by clusterfack** [comment]
How to reproduce: a mystery that lives to this day

**Comment by CptWad** [comment]
Aight I will close and try to see if it happens anymore. I am pro cleaning up issues.
