### ISSUE TITLE
Custom Turrets Set to Shoot non-Command will Shoot RD

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34511]
(WEB REPORT BY: dovemite REMOTE: 206.221.180.138:7777)
# Revision
0593a00132f3333fb530cdc471a43b237fe2eceb

# Description
What it says in the title
# Steps to Reproduce
Put energy crossbow in custom turret
Set to shoot non-security/non-command
Be RD
Get shot to death
# What you Expected
It to shoot everyone else
# What Actually Happened
Be shot as command staff with the shoot non-command option enabled. Not sure if it applies to oher lesser Command such as CMO and CE

**Comment by Servalfang** [comment]
Ideal.

**Comment by Inorien** [comment]
> lesser Command such as CMO and CE

not lesser command

the RD is lesser because he is a scientist

**Comment by Eneocho** [comment]
Feature. No mercy for nerds.
