### ISSUE TITLE
Spacesuit modification station animation broke

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#34524]
#### Description of issue
It used to have an animation of closing and covering you up while it did things

#### Difference between expected and actual behavior
To have an animation of being covered while worked in
Instead you stand there unable to move for a non visible reason while it works on you.

#### Steps to reproduce
Be a plasmeme and repaint your suit or spawn a hardsuit and a rig_module of your choice to go in it and try to install it.

#### Length of time in which bug has been known to occur

I'm not sure, best I can guess is sometime this year it broke.

**Comment by DrSnips** [comment]
Here's something I came across. The animation does play on the items icon stay if you Alt click the tile you're on to see all the things on there and watch it there.
