### ISSUE TITLE
Beach Playlist does not work

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#3453]
No tracks appear.

**Comment by ConkerDev** [comment]
sound has been changed since. Can you test?

**Comment by Kurfursten** [comment]
Does the Beach Playlist still exist?

**Comment by clusterfack** [comment]
Playlist for the cascade beach iirc, but I imagine this report is about one of the superjukes which it would probably appear on. Probably worth asking an admin to check ingame

**Comment by FudgePucker** [comment]
Has anyone checked yet?

Also this is a bug with Pomfs media server most likely and not related to the code base.

**Comment by gbasood** [comment]
This playlist doesn't appear on any of the predefined superjukes.
