### ISSUE TITLE
You can't see implants of someone whose face is hidden

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34543]
(WEB REPORT BY: shiftyrail REMOTE: 206.221.180.138:7777)
# Revision
0560e402fd0a1ce0d3d2bf340ca95902e59afe10

# Description

See title. This is definitively new, and not sure if it makes sense.

**Comment by nervere** [comment]
@ShiftyRail Was it a gas mask? Could be a voice changer gas mask. Also, see this (unmerged as of writing): #34485

**Comment by ShiftyRail** [comment]
It was the detective mustache, so yes, a voice changer.
Not seen the issue with gas masks if the guy's ID is visible. It's terribly inconsistent.

**Comment by pedr69** [comment]
*arrests the detective four separate times for being in the brig

**Comment by nervere** [comment]
Fixed by my PR. #34485
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/983d1e52-8dfa-4b44-af9c-9a7b9a781af3)
