### ISSUE TITLE
Grapplin' hooks

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#3454]
Foreward: Yes I know this would probably be kind of hard to code, but I wanted to suggest it anyways.

Syndie/special forces variant: A reel with an automatic grappling hook, counts as a weapon, has two modes of operation.

Mode A: fully automatic: Works like a weapon, uses battery charge to launch a grappling hook at a target. Has a limited range.
If it connects with a surface, it latches on, and any natural momentum gets transferred into swinging a circular arc around the hit point.
Using the device in your hands after a connection will cause the grappling hook to release and reel in.

Ideal use for fully automatic would either be

1.  launching yourself to land on another distant surface using the circular arc caused by the taut rope

2. Reeling yourself into a location,

3. or using this in conjunction with an existing momentum as a means of travel

Mode B:  Using the object puts a grappling hook in your other hand, which you can throw. It ideally connects with a surface you throw it at, and works like above. The advantage is that it doesn't use cell, disadvantage is that it's not as easy to use.

You can also just use it on a wall to stick it instead of throwing, if you happen to be next to the wall in question.

These can probably be used as a bolas-like weapon as well, but would probably work in low pressure a lot better.

Ghetto variant.

Variant 1: Two Rsds, a lot of cable coil, some plasteel and a makeshift shotgun-like mechanism.

This device basically acts like the special forces variant, with both mode A and Mode B. This is what most players can get their hands on. The difference being that the device has to be powered by shotgun shells in mode A and causes a lot of noise (not much of an issue in space). It also probably has failure chances.

Variant 2: Like the above, but using a cyborg arm a battery and a bit of a crossbow construction in it instead of the shotgun.

Works like the powered version, but harder to get parts.

Variant 3. A bunch of cable coil, some metal, and some more cable to make an unlocking mechanism.

A really on the cheap but very unreliable version that can only operate in unpowered mode B. This is something you'd want to make when you have little in the way of materials

**Comment by Probe1** [comment]
that'd make a neat ass miner toy.

**Comment by Midaychi** [comment]
In low gravity you could also use them as super-bolas. Get really lucky and/or have really good aim and hit some stupid jetpacker mid flight, trip them over and reel them in before they can dislodge themselves.

**Comment by PJB3005** [comment]
this sound amazing

-ly hard to code

**Comment by DeityLink** [comment]
Maybe we can close this, since it's actually been added.

**Comment by Probe1** [comment]
my god, one of midaychis feature requests actually got filled.

**Comment by Midaychi** [comment]
1 out of inf ain't bad
