### ISSUE TITLE
(WEB REPORT BY: mystry REMOTE: 198.245.63.50:7777) Stuck on chair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3455]
&gt;Revision (Should be above if you're viewing this from ingame!)
1f140e9bce83b38639ed7e2b81e4dfd383263106

&gt;General description of the issue
When you're buckled to a chair, and lord singuloth eats the chair, or the chair is destroyed in some other fashion while you live, you can't unbuckle yourself and so are stuck there for eternity.

&gt;What you expected to happen
Expected to be free to move around after chair went into lord singuloths hungry maw

&gt;What actually happened

&gt;Steps to reproduce if possible
Strap yourself to chair, allow lord singuloth near enough to eat chair but not near enough to eat you, and get stuck.

**Comment by PJB3005** [comment]
how do you get lord singuloth close enough to you to eat the chair but not the person IN the chair?

should be a very easy fix though

**Comment by dylanstrategie** [comment]
Missing a few obvious sanity checks indeed

**Comment by PJB3005** [comment]
Fixed with atom locking.
