### ISSUE TITLE
mints take two bites to eat

### ISSUE THREAD

**Issue by PrimeDSS13** [d3athrow/vgstation13#34569]
#### Description of issue
mints take two bites to finish instead of one and theres 30 in a pack and they're 1 pixel wide what the hell man
who eats a mint in two bites do you just nibble on it and say "ahh that was a good half a tic tac" makes NO sense
I mean really consider the mess that would make jesus

#### Difference between expected and actual behavior
1 mint 1 bite
1 mint 2 bite

#### Steps to reproduce
anyone who eats mints like that doesn't reproduce

**Comment by Eneocho** [comment]
Should've been fixed in #34480, did this happen after that got merged?

**Comment by PrimeDSS13** [comment]
I thought it took two bites yesterday but let me double check

**Comment by PrimeDSS13** [comment]
yeah still acts that way on live

**Comment by Eneocho** [comment]
what the fuck

**Comment by Securitymain** [comment]
bitesize = 2

dumbo
