### ISSUE TITLE
kicking is bugged for certain objects

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34564]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
ea78098b0d0c858a98bdede560a6a4ec91db6c83

# Description
you can kick em but they dont move its weird

**Comment by west3436** [comment]
elaborate??

**Comment by pedr69** [comment]
paper bin
taser gun
toolbelt
cardboard box
backpack
armor vest
jumpsuit
headset

it seems really random yeah

**Comment by pedr69** [comment]
no clothing item seems to be kickable(apart from shoes which jump onto your feet when you kick em)

**Comment by PrimeDSS13** [comment]
sorry I didnt elaborate but yeah it's really freaky I'll test more in a bit but this is a newish thing
changing w_class seems to fix it in some cases but it's not reliable?

**Comment by Eneocho** [comment]
This should directly caused by hinaichigo's breakable objects PR, as when the first version got merged (and then reverted), you couldn't kick air tanks for some reason. I asked if that could be fixed on the V2 PR and it did, but only for the air tanks.

**Comment by Hinaichigo** [comment]
For a given kicker strength, an item will only be propelled by a kick if it's at or below a certain weight threshold. It was like this before the breakable objects. See my comment in #34615.
