### ISSUE TITLE
(Feature Request) Let MoMMi's harvest plants by plant bag

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#3457]
For the mommi who wants to make plastic etc.

**Comment by dylanstrategie** [comment]
Directly related to #3456

I would wager for simply allowing MoMMIs to rip out goods with their claws. Believe it or not, MoMMIs actually use Botany if they have nothing else to do, either to grow plastic and wood or to try out their latest Xenobotany ideas

**Comment by AutismSpider** [comment]
If any thing code in a block to stop mommis form using kudzu seed packs.

**Comment by dylanstrategie** [comment]
This issue was basically solved since MoMMIs can now harvest from hydroponic trays outright
