### ISSUE TITLE
Random Spawn Binary Comms doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34578]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
430076f37b9ff42e959d7986765f1a9edc34c0cd

# Description
There's a chance for binary communications to spawn in various places in maintenance as a standard encryption key, the past few times I've found it does nothing when slotted in headsets
# Steps to Reproduce
Slot a maintence spawned binary communication in your headset
# What you Expected
To speak to the robots
# What Actually Happened
nothing

**Comment by SonixApache** [comment]
ask an admeme to VV if it's actually binary comms next time, usually what you find is just a normal blank encryption key

**Comment by nervere** [comment]
Both a standard encryption key and a standard encryption key (binary) can spawn. From the loot pool:
```		
		/obj/item/device/encryptionkey,
		/obj/item/device/encryptionkey/binary,
```
This isn't a bug, you're just getting unlucky.
