### ISSUE TITLE
The Carp Have Forsaken Us

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34570]
(WEB REPORT BY: beelzewax REMOTE: 206.221.180.138:7777)
# Revision
430076f37b9ff42e959d7986765f1a9edc34c0cd

# Description
Baby friendly carp are no longer friendly once they grow up.

# Steps to Reproduce
>get baby carp
>feed baby carp meat until it displays friendly message
>keep feeding carp

# What you Expected
big friendly carp

# What Actually Happened
big angry carp

# Other Info
I've had it happen twice, both times while the carp was in my backpack, feeding it synthmeat

**Comment by Securitymain** [comment]
confirming this is a bug rn, tried to carpfarm the other day and its not haplening
