### ISSUE TITLE
Cargo Forwarding Diamonds

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34587]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
430076f37b9ff42e959d7986765f1a9edc34c0cd

# Description
>Get 108 diamonds needing to forward
>Crate only has 100 diamonds
>???
>no profit

**Comment by Eneocho** [comment]
2 crates, one with 100 diamonds, one with 8.

**Comment by ManopolisJones** [comment]
I wonder if the crate was opened, or if he just got straight penis game'd and it didn't spawn with all the diamonds
