### ISSUE TITLE
Packed Cargo - Minor Change

### ISSUE THREAD

**Issue by CorinJace** [d3athrow/vgstation13#34586]
#### Description of issue

Just a minor swap out I'd like to see with Packed Cargo. On the table in the provided picture is an RCS with several deployable telepads given that Packed does not have a shipping system for the tubes. However, one thing that is missing is the recharger for the RCS. Indicated in the picture provided, on the table you will see a cell charger. Is it possible to have that cell charger replaced with a gun charger to that Cargo can easily recharge the RCS without having to wait for sci to build one or hijack one from either mining or sec?

#### Specific information for locating

Packed Cargo, table shown in attached photo.

![Packed Cargo - Charger](https://github.com/vgstation-coders/vgstation13/assets/66094105/b6f3a2ff-13d9-44c2-978f-9d8827a26830)

#### Server revision
Game: 430076f37b9ff42e959d7986765f1a9edc34c0cd 
Patches: 45084ae38cc9f68891184351e906b395e62066f4

**Comment by Irradiation** [comment]
This issue is obsolete, RCS guns use a (detachable & rechargeable) cell, so there's no need to add a gun recharger in its place.
