### ISSUE TITLE
Creatable Flora Disks

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#3460]
Those fancy disks that hardly anyone uses? You can't make any. The box in botany is literally the only place to get them, making any off-station or non larceny-involving attempt at plant shenanigans can't benefit from targeted GMO seed generation. 

Autolathe, protolathe, whatever. Need a way to obtain another box, preferably without too much oversight. This combined with Mommis being able to harvest plants with plant bags would allow derelict or bored station mommis to create the ultimate resource farms. Build a stealth disposal launcher that targets the kitchen, deliver all dat crazy produce.

**Comment by Zuhayr** [comment]
You should be able to order from from Cargo if /vg/ took the entire set of changes for xenoflora.

**Comment by 9600bauds** [comment]
Correct, the cargo option wasn't ported.
