### ISSUE TITLE
some of the snaxi treadmills don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34610]
(WEB REPORT BY: poales REMOTE: 206.221.180.138:7777)
# Revision
beef675b67b304c13828255def6318a93a40546c

# Description
the ones where you have to face to the right don't seem to work, south of hydroponics

**Comment by Kurfursten** [comment]
This is a really interesting quirk of how bumping treadmills works, it's because two sets of treadmills are facing inward. If you remove the right (left-facing) treadmill it works. Obviously this should be remapped (trivial).
