### ISSUE TITLE
The Detective Revolver can fire 357 without a chance of breaking

### ISSUE THREAD

**Issue by BomberBro** [d3athrow/vgstation13#34628]
In the code, screwdriving the detective revolver to accept 357 ammo is supposed to give it a chance of exploding. This, to my knowledge, does not happen and as far as my google skills can tell you can't fire 357 out of a 38 anyway. 

More importantly though, there's a detective conversion kit for this item to make it 357 without a chance of failure that's flat out useless due to the fact that you can get an identical item from a toolvend. It also lets seccies get the equivalent of a traitor revolver pretty damn fast but the det revolver is already pretty strong so I'm not sure how much difference it'd make in a combat scenario. 

[bugfix]

**Comment by kacurasuo** [comment]
you can definitely fire 38 out of a .357
firing .357 out of a 38 is a little bit more questionable but I think you could still get away with it

**Comment by Exxion** [comment]
Apparently, you can load it with .357 ammo *without* screwdrivering it, and in this case, it does indeed have a chance to explode. I honestly can't tell from the code what they were going for with the screwdriver thing.

**Comment by SonixApache** [comment]
man, even i didn't report this one
sad
