### ISSUE TITLE
Barrels can't get reagents transferred via beakers anymore.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34631]
(WEB REPORT BY: eneocho REMOTE: 206.221.180.138:7777)
# Revision
beef675b67b304c13828255def6318a93a40546c

# Description
Title.
# Steps to Reproduce
Make metal barrel.
Fill beaker with fuel.
Try to transfer to barrel.
The metal barrel has been splashed with fuel!
# What you Expected
To fill my barrel with fuel for my cool ghetto kitchen.
# What Actually Happened
The eternal c*der got me again.

**Comment by Eneocho** [comment]
Can't fill 'em with syringes either. What the fuck.
