### ISSUE TITLE
(WEB REPORT BY: buttbot REMOTE: 198.245.63.50:7777) Suicide with RPG

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3464]
Revision: 1f140e9bce83b38639ed7e2b81e4dfd383263106 

Committing suicide with an RPG just performs the standard suicide with a large amount of brute damage. There is no explosion. In addition, the RPG sprite after being used for a suicide is the 'loaded' sprite, with the warhead still attached, despite not actually being loaded with anything.

1) Acquire RPG
2) Aim at mouth
3) Pull the trigger, pussy

**Comment by d3athrow** [comment]
haha

**Comment by AnonymouxRex** [comment]
Relevant:

https://youtu.be/s9OM1m0XPf8?t=31s

**Comment by dylanstrategie** [comment]
RPG lacks a specific suicide proc, shouldn't take long, two options : 

- Explode (after all it's a syndie RPG, who the fuck wants a safety on that)
- Rip head off (would take a bit to code correctly, but satisfying)
