### ISSUE TITLE
Multitool Cloning Mode Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34642]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
beef675b67b304c13828255def6318a93a40546c

# Description
-take multitool
-attempt to use in-hands to activate cloning mode
-it doesn't work

**Comment by Exxion** [comment]
Works On My Machine
Are you sure you copied a machine to the buffer first?

**Comment by jwhitak** [comment]
Instuctions unclear, did not say to copy a machine in the buffer first. Close issue!
