### ISSUE TITLE
AI's can see the blood droplets from cult teleportation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34656]
(WEB REPORT BY: gallywix4 REMOTE: 206.221.180.138:7777)
# Description
I was playing AI and i saw one of those blood droplets fly by.

**Comment by Eneocho** [comment]
No reason for AIs to not be able to see it, the guy literally turns into spooky immaterial blood whatever and is visible to anyone within field of view. AI has cameras, so it sees the same (within the camera view).

**Comment by DeityLink** [comment]
It's not what the issue is talking about

**Comment by DeityLink** [comment]
oh boy, him again
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/5d3eadd8-54f8-45ce-9cb1-5f2496cb91a4)

**Comment by Eneocho** [comment]
The adacovsk revolution and its consequences have been a disaster for the spessman race-

**Comment by DeityLink** [comment]
I'll investigate exactly when or why the AI eye has this flag. Ada actually reduced its see_invisible there.

**Comment by DeityLink** [comment]
actually the blood jaunts are SEE_INVISIBLE_LEVEL_TWO so it makes no sense the AI could even see them

**Comment by DeityLink** [comment]
unless

**Comment by DeityLink** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/36c3f86c-92ea-4330-bbd4-df2e8b225507)
These ones are supposed to be visible. We'd need to know if the rune was destroyed using salt.

**Comment by DeityLink** [comment]
oh wait I see the problem
