### ISSUE TITLE
During Malf, Pinpointer Does Not Point To Shunted AI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34654]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
ccac5ffcc0ba01b7482a57ce274fe9e71fdd2583

# Description
when the malf AI shunts the pinpointer should point to it's APC
currently it points to the nuke disk, meaning something broke that behavior and shunted AIs are near impossible to find
# Steps to Reproduce
1. have an AI go malf and shunt
2. look at a pinpointer
# What you Expected
the pinpointer to point at the malf APC
# What Actually Happened
the pinpointer pointed at the nuke disk

**Comment by Dacendeth** [comment]
Kill whoever is responsible for this.

**Comment by nervere** [comment]
Just tested and it works fine. Can you give more details please?
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/88eae376-ad31-44e9-8ccd-d2af0a51714e)

**Comment by nervere** [comment]
Nevermind, figured it out with the help of the Discord + logs.
