### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Click_Delayer controller no longer works

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3465]
&gt;Revision (Should be above if you're viewing this from ingame!)
1f140e9bce83b38639ed7e2b81e4dfd383263106

&gt;General description of the issue
Click_Delayer variable for admins where you can control the max and min click delays (allowing for things like punching at the speed of light) doesn't seem to change anything anymore. Maybe it's just me though...

&gt;What you expected to happen
Changed min_delay and max_delay to 0, 0.1,and 1

&gt;What actually happened
No changes occurred in punching speed on any of the changed settings

&gt;Steps to reproduce if possible
View Variables -&gt; Click_Delayer -&gt; min_delay/max_delay

**Comment by d3athrow** [comment]
Not a bug, you need to modify the attack delayer controller. ![rei is dumb](http://puu.sh/gHiOW/8dc005a48f.png)
