### ISSUE TITLE
library computer preview button does not works

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34682]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
c8e2cdcc9dee3ab6c889ad01d5d6fc25e0b6afb4

see title, clicking the button does nothing

**Comment by nervere** [comment]
@Kurfursten @ShiftyRail Any ideas? Feature was added in the new library computer rework.
https://github.com/vgstation-coders/vgstation13/pull/34413
https://github.com/vgstation-coders/vgstation13/blob/c8e2cdcc9dee3ab6c889ad01d5d6fc25e0b6afb4/code/modules/library/computers/checkout.dm#L508-L518

**Comment by Kurfursten** [comment]
Yeah unfortunately since it's not something we can test, I'm inclined to just remove it again. It was purely theoretical anyway.
