### ISSUE TITLE
[Bug?] Bear traps (and other items) remain overtop of hidden wall and door sprites

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#3469]
The other day I was booby trapping a hidden wall with one of the new IED bear traps, only to realize that once closed, the bear trap's sprite is just sitting there on top of the wall sprite. I believe this happens with door sprites, as well, rendering boobytrapping entrances impossible. Nobody's going to be stupid enough to stand there staring at a trap for 5 seconds while the door animation plays, and then walk right onto it.

The wall/door should really cover anything underneath of it, or at least hidden walls, seeing as they're intended to be opened like doors.

**Comment by dylanstrategie** [comment]
Almost certainly an issue with layers. I'm going to guess items are always set to show over walls, since it's expected atoms placed over walls would always be "on the wall"

It would be a bitch to fix too, which is fun

**Comment by gbasood** [comment]
Still an issue?

**Comment by unid15** [comment]
I think so
