### ISSUE TITLE
Vox Trader Outpost (Box) - Airlock Design Tweaks

### ISSUE THREAD

**Issue by CorinJace** [d3athrow/vgstation13#34702]
#### Description of issue
One thing I've noticed on the occasions I stop by the Vox trading outpost, at least on Box, is when I open the outer airlock on the roid side, every single item in the airlock (O2 lockers and medical kits) come flying out and trying to turn me into paste. In the attached pictures, one of the Vox Trader Post airlock and one of the RnD outpost airlock, I'd like to propose a change if possible. 

It appears that Deff and Packed Trader Posts have them already.

If possible, can the airlock cycling switch from the RnD outpost be added to the Vox Trading Post to allow the airlock to be properly cycled, depressurized and repressurized to keep the heavy objects from flying out to greet you with a bruising?

If any other tags or details are needed, let me know.

![Box Research Outpost Airlock](https://github.com/vgstation-coders/vgstation13/assets/66094105/48cd767b-cfa9-42c6-945a-ead184feeef2)
![Box Trader Outpost Airlock](https://github.com/vgstation-coders/vgstation13/assets/66094105/d38e0d47-a558-4905-ab36-a6d422f4b250)

#### Steps to reproduce
Open Vox Trading Post airlock, become the punching bag of O2 lockers and medical kits.

#### Specific information for locating

Vox Trading Post. See attached pictures.

#### Length of time in which bug has been known to occur
Probably since the outpost was made?
-->

#### Server revision

Game: 78d8e7bb25390b17bd723fc9ce3d298a14ffbe29 
Patches: 45084ae38cc9f68891184351e906b395e62066f4

**Comment by Kurfursten** [comment]
Honestly that trade floor zone never ever gets used, it could use a total redesign
