### ISSUE TITLE
RCD Showing Bhangmeter

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34719]
(WEB REPORT BY: sidgilm REMOTE: 206.221.180.138:7777)
# Revision
ed35b9475e616965274065701c44b15f4de825ce

# Description
After going to the doors section, the RCD (advanced RCD if that matters) will show the bhangmeter instead of the menu for either door access or allowing you to go back to pick another thing to construct. Webm posted in the thread https://boards.4channel.org/vg/thread/438195105#p438446051

# Steps to Reproduce
Get advanced RCD
Choose to construct a door
Might've looked at the Bhangmeter at some point after this I don't remember but I could choose access earlier in the round for sure
Try to hit the X
get Bhangmeter brought up
# What you Expected
To be able to choose what to construct
# What Actually Happened
Bhangmeter

**Comment by DeityLink** [comment]
The button might have somehow remained active since it's in that exact location, I'll try and reproduce the issue.

![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/84e6e911-4568-4261-9daa-8dfe1a553f82)
