### ISSUE TITLE
(WEB REPORT BY: merkurlicht REMOTE: 198.245.63.50:7777) Prosthesis&gt;Flesh Regeneration

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3471]
Revision: 110a86ae707512152f09ea15632c2914f5c62929 

&gt;General description of the issue
Having prosthetic limbs and eating the cores of those tentacles monsters apparently turns them to normal human limbs again.

&gt;What you expected to happen
Keeping the prosthetics, duh

&gt;What actually happened
Have prosthetics, eat tentacle core, ????, MIRACLE!

&gt;Steps to reproduce if possible

**Comment by SkowronX** [comment]
Intended I think.
