### ISSUE TITLE
The kitchen shutters button on Snow is hidden behind a monitor

### ISSUE THREAD

**Issue by TrashFiend** [d3athrow/vgstation13#34724]
#### Description of issue
![image](https://github.com/vgstation-coders/vgstation13/assets/5272978/0a382648-1eae-487c-8ecc-a9c9108813b9)
shits hidden, need to alt click to use it

[snowmap][oversight]

**Comment by Kurfursten** [comment]
@SonixApache

**Comment by SonixApache** [comment]
huh, i must've fucked up the pixels, it was supposed to be on the north wall
