### ISSUE TITLE
You can eat Dangles(tm) without opening them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34721]
(WEB REPORT BY: tinysaturn REMOTE: 206.221.180.138:7777)
# Revision
ed35b9475e616965274065701c44b15f4de825ce

# Steps to Reproduce
obtain dangles
bite intent
click on dangles
# What you Expected
nothing
# What Actually Happened
i ate the dangles (through the can?)

**Comment by Theophrastus1** [comment]
i bet you didnt know you could unroll pringles cans either
