### ISSUE TITLE
Advanced Pinpointer not working properly.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34725]
(WEB REPORT BY: makagame REMOTE: 206.221.180.138:7777)
# Revision
ed35b9475e616965274065701c44b15f4de825ce

# Description
Advanced Pinpointer, when used to locate a hypospray item, locates an autoinjector instead.
# Steps to Reproduce
Turn on AP, choost Other - Item - hypospray and follow it.
# What you Expected
To find a hypospray
# What Actually Happened
I found an autoinjector. Jectie failed?..

**Comment by Eneocho** [comment]
Duplicate of #34639

**Comment by nervere** [comment]
Closing as duplicate
