### ISSUE TITLE
Getting ripped off by lotto tickets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34745]
(WEB REPORT BY: blithering REMOTE: 206.221.180.138:7777)
# Revision
53ed0ac186346646179fe36ac77ac710dddacae0

# Description
Supermatter surprise tickets are supposedly a guaranteed win at the cost of a hand, but they can crop up no winners
# Steps to Reproduce
have hands to spare, scratch off supermatter surprise card
# What you Expected
money no hand
# What Actually Happened
no money no hand

**Comment by Blithering** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/15067109/7a1aa142-966b-4da0-9bf8-d0b8f7ae7125)

**Comment by ghost** [comment]
@west3436

**Comment by west3436** [comment]
Either an issue from the luck additions or my (likely) improper use of prob(). I'll fix this next week

**Comment by ghost** [comment]
> Either an issue from the luck additions or my (likely) improper use of prob(). I'll fix this next week

I tested the base luck procs and they work fine so it seems to be an issue with the values that you're passing them and the way that prize value is tied to probability. Also, what's up with the 1/12000 magic number for luckfactor? That's making any luck influence astronomically small.

**Comment by west3436** [comment]
Luck stuff was added after these were implemented and I had no hand in that change. Don't remember who added luck. I've been wanting to redactor these tickets anyways so I'll sort that portion out too.

**Comment by Eneocho** [comment]
>Don't remember who added luck.

You want @Hinaichigo, he added the luck system. There is an explanation on luck mechanics on the wiki page for Luck.

**Comment by Hinaichigo** [comment]
I misunderstood the supermatter surprise code when I did the luck stuff. I'll see if I can fix it.

**Comment by Hinaichigo** [comment]
> Also, what's up with the 1/12000 magic number for luckfactor? That's making any luck influence astronomically small.

When luck was merged it was initially considered way too easy to make lots of credits with scratchcards and clovers so it was nerfed a lot.

**Comment by west3436** [comment]
Fixed via #35287
