### ISSUE TITLE
(WEB REPORT BY: theeliminator16 REMOTE: 198.245.63.50:7777) Buildmode HUD Not Disappearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3474]
&gt;Revision (Should be above if you're viewing this from ingame!)

&gt;General description of the issue
After pressing the &quot;buildquit&quot; button to exit buildmode, the HUD remains on screen. Buildmode is turned off, however.

&gt;What you expected to happen
Buildmode turns off and the HUD disappears.

&gt;What actually happened
Buildmode turns off and the HUD remains.

&gt;Steps to reproduce if possible
Turn on build mode, try to turn it off with the X in the top left.

**Comment by SkowronX** [comment]
Ghosting seems to fix this, but it's rather annoying.
