### ISSUE TITLE
Advanced Graffiti Unable to be Photographed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34753]
(WEB REPORT BY: dovemite REMOTE: 206.221.180.138:7777)
# Revision
53ed0ac186346646179fe36ac77ac710dddacae0

# Description
What it says on the title, if you try to take a picture of any drawings around you'll get a picture with a bunch of different rune circles instead.
# Steps to Reproduce
Tag the wall/floor with your custom crayon drawings. Take a picture
# What you Expected
Photo of my beautiful masterpiece that I can upload to a newsfeed.
# What Actually Happened
A photo of rune gibberish.

**Comment by Eneocho** [comment]
it's so joever...
