### ISSUE TITLE
Confusion Rune Does Not Wear Off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34761]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
c1aece31bbdc1dc329e82a3576acdaa5732ff8f6

# Description
after being hit with a confusion rune (I think via talisman?), maybe even twice in a row, I was permenantly in "cult confusion" mode. This happened to another individual as well, it just never wore off and the Nar-Sie Overlay was stuck on my screen.

**Comment by DeityLink** [comment]
Should be fixed by #34838
