### ISSUE TITLE
weird toolbox inhand

### ISSUE THREAD

**Issue by nervere** [d3athrow/vgstation13#34770]
is it just me or does the toolbox inhand when facing this way look blurry now?
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/a40ab853-1253-40c9-9df0-ef4bbfaafa91)

**Comment by gurfan** [comment]
Is it the satchel you're wearing?

**Comment by Dacendeth** [comment]
yeah that's totally it, just the satchel

**Comment by nervere** [comment]
I'm dumb.
