### ISSUE TITLE
Full Speed Peg Limbs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34776]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
8078c3eb86f3ead0ad27b4cf389352c38e991149

# Description
In certain conditions, you can go full speed despite having peg limbs. Getting chemical healing and getting hugged seems to influence this. Needs additional testing.

**Comment by SacredAtom** [comment]
Don't look into this or the pirate metaclub will make you walk the plank

**Comment by jwhitak** [comment]
Not a bug - things that eliminate slowdown or give pain tolerance can eliminate peg limb slowdown. The more you know!
