### ISSUE TITLE
Couche sprites are layered above railings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34782]
(WEB REPORT BY: loppu REMOTE: 206.221.180.138:7777)
# Revision
8078c3eb86f3ead0ad27b4cf389352c38e991149

# Description
Couch segment sprites are layered over railing sprites
# Steps to Reproduce
Place a couch, place a railing, spin the couch to check directionals
# What you Expected
Railing visible
# What Actually Happened
Couch visible

**Comment by Inorien** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/16082007/cc4d7404-b678-4e58-a91f-f103e810e23a)

look at what it did to him
