### ISSUE TITLE
The Strange Coffee Machine doesn't make medical nanobots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34783]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
8078c3eb86f3ead0ad27b4cf389352c38e991149

# Description
Ask the coffee machine for medical nanobots

# Steps to Reproduce

# What you Expected
get medical nanobots

# What Actually Happened

get NONE

**Comment by ghost** [comment]
Not a bug, mednanos and xenomicrobes are emag-only reagents: https://github.com/vgstation-coders/vgstation13/blob/8078c3eb86f3ead0ad27b4cf389352c38e991149/code/game/machinery/scp_294.dm#L20

**Comment by pedr69** [comment]
so you can make adminordrazine and autist nanites? wew

**Comment by Exxion** [comment]
No and yes, respectively
