### ISSUE TITLE
Screwsolder cannot be used to make a Hand Crank Cell Charger

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#34799]
[consistency]
[oversight]

#### Description of issue
The screwsolder cannot be used to construct a Hand Crank Cell Charger.

#### Difference between expected and actual behavior
Expected: To be able to adjust the cables with a screwsolder
Actual: The wires can only be adjusted using a screwdriver

#### Steps to reproduce
Get screwsolder, attempt to make Hand Crank Cell Charger.

**Comment by wotisjanitor** [comment]
Why was this item even added

**Comment by falcon2346** [comment]
It's one of the CE items, so probably just to give them a convenient toy at round start. It does also store more acid than the standard soldering iron though, so it has that going for it.
