### ISSUE TITLE
Rolling Pin KO's Make No Sound

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34804]
(WEB REPORT BY: dovemite REMOTE: 206.221.180.138:7777)
# Revision
8078c3eb86f3ead0ad27b4cf389352c38e991149

# Description
See title. Was knocking a funny man out with a rolling pin but it did not make a sound until he fell into crit and I just started beating him.
# Steps to Reproduce
Hit man with rolling pin
Knock him out
# What you Expected
Normal rolling pin beating sound or maybe something special for a KO
# What Actually Happened
I beat a man unconscious without a sound. Until he started dying, then it was quite audible

**Comment by Inorien** [comment]
https://www.youtube.com/watch?v=6TP0abZdRXg
