### ISSUE TITLE
Street alchemy's pill is unique in world

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34811]
(WEB REPORT BY: securitymain REMOTE: 206.221.180.138:7777)
# Revision
8078c3eb86f3ead0ad27b4cf389352c38e991149

# Description
The wizard spell street alchemy creates a pill from reagents in a container. Making a second one replaces the first one, no matter where it is. It's just gone.

# Steps to Reproduce
Street alchemy twice

# What you Expected
Making 1000u pills

# What Actually Happened
Making a single 1000u pill

**Comment by Exxion** [comment]
This is apparently intentional.
https://github.com/vgstation-coders/vgstation13/blob/8078c3eb86f3ead0ad27b4cf389352c38e991149/code/modules/spells/targeted/street_alchemy.dm#L94-L97

**Comment by Eneocho** [comment]
that limit sounds kinda lame honestly

**Comment by Exxion** [comment]
I assume the point is to prevent you from carrying around a bag full of 1000u fix-everything pills, but I'm not sure how big an issue that would be given that the wizard would first have to spend the spell points and then spend half the round in chemistry to actually get the chems
