### ISSUE TITLE
(WEB REPORT BY: thewhargoul REMOTE: 198.245.63.50:7777) Forced Catatonic

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3482]
&gt;Revision (Should be above if you're viewing this from ingame!)

&gt;General description of the issue
Virus made me a monkey, I had the Geneticist give me a human SE, When I was made back into a human it kicked me from my body and forced me to go Catatonic, The body was alive, it just force ghosted me. 

&gt;What you expected to happen

&gt;What actually happened

&gt;Steps to reproduce if possible

**Comment by The-Whargoul** [comment]
oops. Guess I need to finish this

**Comment by Ephx1** [comment]
Almost sounds related to the Monkey gamemode that does the same thing.

**Comment by clusterfack** [comment]
If you had monkism (they monkey virus) it should have gibbed you.

**Comment by The-Whargoul** [comment]
I remember the virus causing me to hallucinate, then I was made into a monkey while in a Ripley then was injected with the cure while I was monkey then injected with a SE that made my body human, but kicked me out of the body and made me catatonic.

**Comment by gbasood** [comment]
Closing this since it's so old and hasnt had any activity
