### ISSUE TITLE
Pitbulls Attack Apprentices

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34823]
(WEB REPORT BY: dovemite REMOTE: 206.221.180.138:7777)
# Revision
2ed77b956079e049287979ce3c110ba1691b545b

# Description
See title, pitbulls will attack apprentices summoned by their master
# Steps to Reproduce
Be apprentice summoned by pitbull wiz
Get mauled
# What you Expected
To not get mauled like a baby
# What Actually Happened
Pitbulls came after me to valiantly defend our shared wizard master

**Comment by Securitymain** [comment]
They also attacked the other wizards even though the spell says it won't.

**Comment by Hinaichigo** [comment]
9 times out of 10 this is a problem with the owner
