### ISSUE TITLE
Energy Shotgun Lost it's spread

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34843]
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
3fd5a26381828cb0cef6639c0afe206d45761173

# Description
I sold the energy shotgun as a trader and it didn't do the spread fire taser shots, maybe I am remembering it wrong
# Steps to Reproduce
shoot it
# What you Expected
A spread fire of 4 taser bolts
# What Actually Happened
a single shot

**Comment by RedrobotAnnie** [comment]
I'm retarded, I forgot you can swap firing please ignore

**Comment by nervere** [comment]
It's okay, we all have our moments.
