### ISSUE TITLE
Self Implanting Inconsistency

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#34846]
If a player somehow gets an unused greytide implant and implants themselves, they are properly given no role and showed as failed to convert on logs, but the implanter itself sends a message about how they have been shown the greytide and must protect themselves. This is confusing and should be fixed.

**Comment by wotisjanitor** [comment]
How should it work though? Just a useless implant?

**Comment by Kurfursten** [comment]
Yes, that's how it already works, it just sends an incorrect message

**Comment by Eneocho** [comment]
Make them turn into a survivor for shit and giggles.
