### ISSUE TITLE
Snackbar machine nonfuctionality

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34849]
(WEB REPORT BY: thathazmatyoukilledinsof REMOTE: 206.221.180.138:7777)
# Revision
3fd5a26381828cb0cef6639c0afe206d45761173

# Description

When a snackbar machine is unwrenched and wrenched back in, it becomes non functional. This goes further beyond that, we're I've seen an instance of making a new snackbar machine with the mechanics office yeilding a broken snackbar machine. I have tested this with water and space polyp, with glass cups and beakers, it does not produce snackbar. Finally, I've also tried reassembly of the snackbar machine in an attempt to make it work, and yet it upon assembly it is STILL nonfunctional. Stranger still, when I de-assembled the roundstart snackbar machine, it was missing a micromanipulator for some strange reason, I had to print a new one.

# Steps to Reproduce
Unwrench the snackbar machine, wrench it back in, and attempt to make a dessicated bar of something.

# What you Expected

Dessicated Polyp Gelatin bars.

# What Actually Happened

Clicking the button, "Make Snackbar" only to have nothing happen.

**Comment by Kurfursten** [comment]
seems entirely broken even at roundstart
