### ISSUE TITLE
Cannot clear buffer on ChemMasters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34840]
(WEB REPORT BY: kanef REMOTE: 206.221.180.138:7777)
# Revision
3fd5a26381828cb0cef6639c0afe206d45761173
[bugfix]
# Steps to Reproduce
* Put 100u water in chemmaster beaker
* Transfer all to beaker
* Eject beaker and clear buffer
# What you Expected
Empty beaker and buffer
# What Actually Happened
Full beaker

**Comment by SonixApache** [comment]
i caused this

**Comment by jwhitak** [comment]
\>transfer all to beaker
\>it's still in the beaker

I think he meant transfer to buffer here lmao

**Comment by Inorien** [comment]
> >transfer all to beaker >it's still in the beaker
> 
> I think he meant transfer to buffer here lmao

nope,if you click all to transfer beaker to buffer then attempt to transfer from the buffer back to the beaker, the chems are destroyed

**Comment by SonixApache** [comment]
cannot reproduce

**Comment by Exxion** [comment]
I can

**Comment by Exxion** [comment]
Or rather you *can* clear the buffer, but it doesn't automatically clear when removing the beaker unless you first set it to dump contents to disposal

**Comment by Exxion** [comment]
And I have now noticed that it was an intentional change you made in your PR
It did not get broken when slurping was added. It always worked like that. It's not supposed to automatically put reagents back into the beaker when ejected. Hence why the button says "and Clear Buffer."
