### ISSUE TITLE
Couches and chairs overlay on top of railings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34853]
(WEB REPORT BY: bungofungo REMOTE: 206.221.180.138:7777)
# Revision
3fd5a26381828cb0cef6639c0afe206d45761173

# Description
Couches and chairs appear over railing sprites at certain angles, particularly facing downwards, 6 o clock, south, however you wanna label it.
# Steps to Reproduce
Build railing for decoration, build couch or chair on same tile
# What you Expected
Railing takes priority and covers furniture like it does for machines 
# What Actually Happened
Ugly looking situation where a chair or couch is phasing through a railing

**Comment by Hinaichigo** [comment]
Duplicate of #34782.
