### ISSUE TITLE
I hate arcane tamper.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#34854]
Remove it.

**Comment by Dacendeth** [comment]
I really thought people would emoji this instantly, oh well.

**Comment by DeityLink** [comment]
wtf, why would you close this after 12 hours?

**Comment by Dacendeth** [comment]
I pressed the wrong button when making the second comment.

**Comment by DeityLink** [comment]
So shouldn't we re-open this then?
