### ISSUE TITLE
(WEB REPORT BY: ekkosangen REMOTE: 198.245.63.50:7777) MoMMIs and Tables

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3486]
>Revision 1a15f3afe7ad97eb8379b57690ecd5db3ddc2abb

>General description of the issue
MoMMIs cannot place objects on tables.

>What you expected to happen
Click with object on table, object is placed on table

>What actually happened
Object stays in hand

>Steps to reproduce if possible
Pick up object as a MoMMI, click on table.

**Comment by Ephx1** [comment]
I don't see how this is an issue, MoMMI's can climb tables, just climb up and drop it on the table.

**Comment by 9600bauds** [comment]
Well first of all that's less than ideal, second it forbids MoMMIs from using the new functionality that lets you center your item's sprite on where you click when you place it on a table.

**Comment by PJB3005** [comment]
Indeed bauds, I want muh table organizing!
