### ISSUE TITLE
Remove Arcane Tamper

### ISSUE THREAD

**Issue by wotisjanitor** [d3athrow/vgstation13#34877]
It appears this garbage feature was accidentally ported from another server that makes everything terrible on purpose.

[bugfix]

**Comment by Pastamadness** [comment]
How does that effect you personally?

**Comment by Blithering** [comment]
I'd say make the door fuckery wear off after being triggered, other than that I've never noticed any tampering.

**Comment by wotisjanitor** [comment]
> I'd say make the door fuckery wear off after being triggered, other than that I've never noticed any tampering.

Wow so the only time you've noticed this spell is when the most annoying shit ever happens?

**Comment by angryturnip** [comment]
the other stuff must not be very annoying if he only noticed the most annoying thing!

**Comment by NigglyWiggly** [comment]
The fact that Tamper has other uses beyond the insanely bad door shit is sort of wild in itself.
The door tamper is so debilitating

**Comment by SonixApache** [comment]
> It appears this garbage feature makes everything terrible on purpose.

yes, that's the idea behind wizards

**Comment by Kurfursten** [comment]
If door tamper is that strong, maybe it should just be its own spell, whereas all other tamper effects are a value pack together?

**Comment by wotisjanitor** [comment]
> If door tamper is that strong, maybe it should just be its own spell, whereas all other tamper effects are a value pack together?
 
It teleports you to locations with no possible way of escape like the mothership lab vault. Whenever a wizard uses this spell the round has basically ended

**Comment by gallywix4** [comment]
> > If door tamper is that strong, maybe it should just be its own spell, whereas all other tamper effects are a value pack together?
> 
> It teleports you to locations with no possible way of escape like the mothership lab vault. Whenever a wizard uses this spell the round has basically ended

The teleport work both ways, if try using the door you got teleported you will return to your previous location, with that said it's also common teleporting into a vault filled with lasers and instantly dying and that's quite silly. 
Maybe change the effect from teleporting doors to reverse the acess required forcing people to remove their ID if they want to enter the airlock

**Comment by wotisjanitor** [comment]
> The teleport work both ways, if try using the door you got teleported you will return to your previous location

And then you don't have access to the door or any means of hacking out, nor a spacesuit.

**Comment by SECBATON-GRIFFON** [comment]
i have no idea what server this man is on about
meds
