### ISSUE TITLE
Mouser pistol feeder bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#34888]
![Screenshot 2023-08-10 205114](https://github.com/vgstation-coders/vgstation13/assets/5169310/ee126b3b-03fa-4c76-acb8-fa0796c0a40f)

Be op who mouser pistols self
Need a way to kill myself in captains room to transform back so eat donuts until 1000 nutrition
Gib and turn into ghost, did not turn back into op
Item not as advertised, got ACME mouser pistol because all that remained was a mouse meat on an agent ID

**Comment by kilozombie** [comment]
Ludonarrative

**Comment by Eneocho** [comment]
seems like a pretty big oversight
also, you could've gotten into the scrubber until you died from oxyloss (that's the usual thing people do when they get mouser'd)

**Comment by pedr69** [comment]
kino
