### ISSUE TITLE
Trying to print a manual from the library computer just prints a book from the database instead

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#34906]
![dreamseeker_MoBrrNXxpN](https://github.com/vgstation-coders/vgstation13/assets/6062247/26e76341-4cf6-4794-832d-e4847bee536f)

It's consistent which manual picks which book. I think these are books from the database but they aren't the manuals. And some of them never work.

Also usually it's gay porn or Moby Dick.

[bugfix]

**Comment by Eneocho** [comment]
feature(TM)
