### ISSUE TITLE
make so animals cant get past raillings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34911]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
9e32cd263de90541cf23651273be707f8492d280

# Description
railings are cool feature and you can make chicken coups and stuff but the animals dont give a fuck and just walk through them. if humans have to drag click to go over a railing then animals shouldnt be able to just warp through# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
It's the same mobs that can walk through tables. This particular report is probably about chickens.
