### ISSUE TITLE
Missing uniform sprites

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#3491]
- Mechatronic Engineer standing directional sprites are missing. If someone can find them again, that's neat, otherwise they need to be found again or recreated
- The new biker and jacket uniform sprites lack lying states

Exclusively a sprite issue

**Comment by Arthurdentist** [comment]
Biker and Jacket uniform are both acting fine when I test then on the server. Mechatronic Engineer sprites are indeed broken however.

**Comment by NigglyWiggly** [comment]
I was pretty sure the lying down sprites were completely unnecessary at this point, and just served to take up space on the .dmis

**Comment by Arthurdentist** [comment]
This issue has been fixed
