### ISSUE TITLE
glass floor doesnt parallax anymore??

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34913]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
9e32cd263de90541cf23651273be707f8492d280

# Description
i swear it used to be now the stars under glass floor are static
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Exxion** [comment]
#34865
So this was the reason glass floors were on `SPACE_BACKGROUND_PLANE`. I had assumed that would have been tested.
