### ISSUE TITLE
Should the roulette revolver be able to shoot immovable rods, immovable pillars, and immovable monoliths?

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#34925]
Since we are seeing both nonantags shooting it for fun, and antags shooting it trying to roll these extremely devastating projectiles which can singlehandedly guarantee a shuttle call, is this an okay thing to put on the revolver? I suppose I'm kind of value neutral on it but it is quite intense.

My memory may be failing me but I was under the impression it could not shoot rods, and the worst it could shoot was meteors. Maybe shooting rods has always been a thing, but it feels like a recent phenomenon that I haven't seen discussion on.

**Comment by angryturnip** [comment]
yes it should

**Comment by Exxion** [comment]
Looks like the only projectiles it's coded to be unable to shoot are ones that would cause obvious technical problems, and this seems to have always been the case.

**Comment by djkramer123** [comment]
isn't it supposed to exclude meteors, yet it still shoots meteor subtypes

**Comment by SonixApache** [comment]
no, it should not

**Comment by DorainGrey** [comment]
I think the current behaviour is fine & can lead to funny situations. However it should either get the warping claws treatment & be turned into a large find or up the rarity & remove the self charge.

The main problem with them, is you can easily grind out multiple every round, not their specific behaviour IMO

**Comment by Eneocho** [comment]
It has always fired rods and meteors, and it should keep firing all projectiles, except the broken (in the server crashing sense) ones. Don't try to fix what ain't broke, man.
>remove the self charge

They self charge?

**Comment by kilozombie** [comment]
Yeah, roulette revolvers recharge ammo. You could, if so inclined, sit out 100 tiles away from the station on a lattice and shoot at the station all day

**Comment by west3436** [comment]
Closed via #35752

**Comment by Eneocho** [comment]
REMEMBER WHAT THEY TOOK FROM YOU
