### ISSUE TITLE
Two things about Cult

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#34947]
- Let us convert as many people as we want

- Let the round end without a shuttle call or admin intervention

It doesn't have to be a straightforward Nar Nar summon where it hangs around a while. If it worked like the nuke where it instantly ended the round when Nar Nar was summoned that could work just fine. Victory lap was dumb.

**Comment by angryturnip** [comment]
I miss Nar Nar

**Comment by Optimism333** [comment]
I don't particularly want the conversion limit to go, but I would very much agree that there needs to be an endgame trigger for the mode. Whether it's summoning Nar Nar or something else.

**Comment by pedr69** [comment]
could probably add the "i am valid" red halos and remove the conversion cap

**Comment by wotisjanitor** [comment]
No to both, NEXT!

**Comment by Hinaichigo** [comment]
Opening a portal to the warp maybe letting demons in and turning everything into that dark hallucination mode that sometimes happens and also summoning Nar'sie would be cool.

I think a PR to re-add summoning Nar'sie would have a decent amount of support.
