### ISSUE TITLE
(WEB REPORT BY: grill3dch33z REMOTE: 198.245.63.50:7777) Mechatronic Engineer Suit fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3496]
>Revision (Should be above if you're viewing this from ingame!)
caad61890768687d09a88d9fbfd80e964b10f31b 

>General description of the issue
The mechatronic engineer's jumpsuit looks all sorts of fucked when looking to the left or right.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Exxion** [comment]
Duplicate of part of #3491.
