### ISSUE TITLE
Emagging a Pod Breaks Shuttle Panel

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#34961]
Emagging a pod breaks the emergency shuttle panel after they crash into the shuttle. Literally antagging the admins!

![image](https://github.com/vgstation-coders/vgstation13/assets/9782036/b54a911f-dc02-419a-984a-90b2c6f4007f)

No one probably noticed before now because it's so rare to need to use that panel after the shuttle gets owned - round is ending in 60 seconds anyway.

**Comment by Eneocho** [comment]
>Literally antagging the admins!

Feature. Keep it.

**Comment by Kurfursten** [comment]
I know you mean to be funny but this just prevents bussing
