### ISSUE TITLE
wrong room name?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34973]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
42d0f9afe96b5d887bc7f1bd83e74bc47b5b569f
[box][boxstation]
the little room at the left of the upload where the AI integrity restorer is is called "Messaging Server Room"
there are no messaging servers in sight

**Comment by Eneocho** [comment]
they stole the messaging servers???
can't have shit on nanotrasen

**Comment by toomykins** [comment]
it's been like this for so long lol
