### ISSUE TITLE
invisible positronic gygax

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34978]
(WEB REPORT BY: w2ngpiwerngpiowj4grki REMOTE: 206.221.180.138:7777)
when a gygax has a positronic brain in it, it turns invisible. the gygax was also painted.

**Comment by pedr69** [comment]
https://github.com/vgstation-coders/vgstation13/blob/f50f58e093be7d81c113c9e40c8908bce89088bf/code/game/mecha/mecha.dm#L1290

this is null
