### ISSUE TITLE
Waystation Engineering Camera console has no cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34970]
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
42d0f9afe96b5d887bc7f1bd83e74bc47b5b569f

# Description
The engineering camera console in the engineering lobby of waystation has no cameras linked to it.
# Steps to Reproduce

# What you Expected
Cameras in engineering should be tagged to be shown on the engineering camera console.
# What Actually Happened
The console is currently just a decoration by default.

**Comment by pedr69** [comment]
engineering cameras only show cameras in areas with atmos/power issues
and mommis, they always show on the computer
