### ISSUE TITLE
(WEB REPORT BY: docttj REMOTE: 198.245.63.50:7777) Chair bug known as snake train

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3498]
>Revision (Should be above if you're viewing this from ingame!)

caad61890768687d09a88d9fbfd80e964b10f31b 

>General description of the issue
Buckled clown into a wheelie chair. You can see everything in this webm. If the link no longer works then bwoink me whenever I get on again. Ckey: Docttj

Basically, I buckled him in and his model was BEHIND the chair. Dragging the chair also dragged him. Then mime bumped into me, he got unbuckled, and could not be moved, pulled, or grabbed. 

Webm: http://a.pomf.se/tmumcb.webm

>What you expected to happen
I was just gonna wheel him around a bit, then the snake train happened and I had to show everyone

>What actually happened
You can see here, I ahelped too. Talked to nuklearcellphoneg about it. Admins came in, tried to fix it with cutting his legs off. Didnt work. Setting his uckled status to 0 also didnt work. 
http://a.pomf.se/tmumcb.webm

>Steps to reproduce if possible
Not sure how to reproduce. I did reproduce it though. I buckled the mime to the chair and the same thing happened, though he was able to move. http://a.pomf.se/tmumcb.webm

**Comment by ririchiyo** [comment]
This bug has been around for years in many different forms.

**Comment by ComicIronic** [comment]
Why is buckled even a boolean instead of a ref to the chair/bed/whatever is being used?

**Comment by PJB3005** [comment]
Fixed with atom locking.
