### ISSUE TITLE
Frying Pans Can't Be Taken Off Metal Barrels

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#34996]
(WEB REPORT BY: pulserider REMOTE: 206.221.180.138:7777)
# Revision
aeb6c2115e779aeb31b1cf77c5fa4300103e8679

# Description
if you put a frying pan on a burning metal barrel, the frying pan won't come off

this makes cooking impossible
# Steps to Reproduce
get a frying pan
place it on a burning metal barrel with welding fuel
try to take it off of the barrel
can't
# What you Expected
to be able to retrieve my food
# What Actually Happened
burned mess

**Comment by Hinaichigo** [comment]
Caused by #34103 breaking the supercall chain for `attack_hand()` so the event doesn't get evoked.
https://github.com/vgstation-coders/vgstation13/blob/3c144e015c4d7c52ab8d522d0a1fabc73d8274bc/code/modules/reagents/reagent_dispenser.dm#L38-L47
