### ISSUE TITLE
[Feature Request] Egg carton picks up all eggs

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3499]
Like a plant bag does with eggs, or a pill collector would with pills.

Let me tell you, I'll tell my kids one day about how much fun I had individually placing each egg into an egg carton then walking one tile from the plant fridge to the microwaves and putting each egg into the microwave.  But I think it'd be better in the long run if we didn't have to do that.

**Comment by dylanstrategie** [comment]
Since all "fancy" storages collect one type of object and one type only, I'll forward a PR that modifies all of them to have these properties, so that one week from now someone doesn't go "I really wish I didn't have to put the donuts I cooked/vended into that donut box one by one"
