### ISSUE TITLE
[Bug] Farsight power overlays are a mess.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3500]
Going unconscious  results in this business, the overlay or whatever it is only reaches a portion of your screen.  While you're at it, please have the icons properly adjust to the corners of the screen when you get farsight.  It looks pretty bad when it's off center instead of aligned with the corners of the screen.  We can do better than this and farsight is a really cool idea.

![farsight](https://cloud.githubusercontent.com/assets/8550416/6751524/2a88e658-cedb-11e4-95e0-a6dbb969be6a.png)

**Comment by ririchiyo** [comment]
this was likely because the screen size was set to 15x15 by default I believe and no-one thought at the time it might be increased/decreased.
