### ISSUE TITLE
Cluwne ban bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35006]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
db7af92398efece818ad5e61b7f1735da341ebfd

# Description

cluwne banned sec main

# Steps to Reproduce

cluwne ban someone

# What you Expected
them being cluwne banned
# What Actually Happened
they just play as normal.

**Comment by pedr69** [comment]
the banpage shows a securitymain is serverbanned too
having a space in his username probably broke some shit

**Comment by ghost** [comment]
This still doesn't actually work on the ss13.moe ban page, pretty sure.
