### ISSUE TITLE
[Meta] Condimaster layering issues

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3502]
The renamed Condimasters in Meta's botany and kitchen seem to have some weird stuff going on with their layering.
Any items ejected from them are hidden under the machine, and if you walk away both start z-fighting.
Doesn't happen with Box's condimaster.
![ss 2015-03-20 at 01 43 20](https://cloud.githubusercontent.com/assets/6526157/6756338/f24bf35c-cf07-11e4-82dd-235698ba86d6.png)

**Comment by dylanstrategie** [comment]
What the fuck is this "CondiMaster Neo" supposed to do ?

**Comment by CptWad** [comment]
@dylanstrategie Is a chef version of the chem master. You can separate chems in it.

**Comment by 9600bauds** [comment]
It also gives you condiment bottles and changes their sprite to what they have inside them.

**Comment by dylanstrategie** [comment]
I am fairly certain the items being hidden under machine and Z-fighting problems also happen in Boxstation

**Comment by 9600bauds** [comment]
Haven't been able to reproduce this in Box, strangely enough

**Comment by Probe1** [comment]
Still able to produce not sure of cause

![2](https://cloud.githubusercontent.com/assets/8550416/10095422/c35cc43a-6337-11e5-8e4c-80c9f1250bf8.gif)

**Comment by dylanstrategie** [comment]
Since there's Z-fighting, it looks like they have the same layer

**Comment by Probe1** [comment]
Thank you goofball.

**Comment by Probe1** [comment]
The machines pixel offset was varedited, making this happen
