### ISSUE TITLE
Can't clap while buckled in a seat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35037]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
3c144e015c4d7c52ab8d522d0a1fabc73d8274bc

# Description
been like this forever, make it so you can clap while buckled
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by wankov** [comment]
this is a great idea
