### ISSUE TITLE
Grue Shadow Shunt in Cages

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35042]
(WEB REPORT BY: comicthunder REMOTE: 206.221.180.138:7777)
# Revision
91411347ac7ff71d3ce5309281c4c52489d57464

# Description
While as a grue you can shadow shunt inside a cage while the cover is open, however, you cannot move from your new location and you shortly after return to where your cage is
# Steps to Reproduce
Shadow Shunt as a grue inside a cage while the cover is open
# What you Expected
I would escape
# What Actually Happened
I teleported to another room, couldn't move. Teleported right back to the cage

**Comment by pedr69** [comment]
that happened when i bumped the cage
because you're locked to the cage, whenever it updates you get sent back to it

**Comment by DorainGrey** [comment]
How is this a bug?

I'm not aware of any other antag that can escape a cage, why should Grue be special?
I guess it'd be better to prevent it teleporting in the first place.

**Comment by Killette2** [comment]
can't wizards escape?

**Comment by Hinaichigo** [comment]
Maybe `forceMove()` should have some kind of logic related to `locked_to`.

**Comment by pedr69** [comment]
then it wouldn't be much of a forcemove anymore, would it?

**Comment by Hinaichigo** [comment]
Maybe it could release `locked_to` or something, or have flags related to doing that optionally.
