### ISSUE TITLE
Vox can breath plasma gas with no problem

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#35047]
#### Description of issue
Vox can breathe a plasma and nitrogen mix with no issue. They can even breathe just a plasma mix without suffering toxicity, though they will suffocate due to not getting nitrogen.

#### Difference between expected and actual behavior
Vox should probably suffer the same toxicity as humans as plasma should be toxic to breathe unless you're a plasmaman.

#### Steps to reproduce
![image](https://github.com/vgstation-coders/vgstation13/assets/145183032/b5848aa4-226f-4f93-b29c-065b8b85adb4)
Thanks to @falcon2346 for the test and image.

#### Length of time in which bug has been known to occur

Probably since vox have been added.

**Comment by pedr69** [comment]
lol

**Comment by Exxion** [comment]
> Probably since vox have been added.

It's since lungs were reworked. Still a long time.
