### ISSUE TITLE
Fix railing furniture clipping

### ISSUE THREAD

**Issue by wankov** [d3athrow/vgstation13#35044]
#### Description of issue
Furniture clipping through raillings depending on direction, typically back and right side of couchs and sofas. Forward facing furniture doesn't clip through.

depiction below

![railings](https://github.com/vgstation-coders/vgstation13/assets/127535873/61f643d2-f85d-45db-8897-9dddcb49bbc3)

**Comment by pedr69** [comment]
>steps to reproduce empty

sorry buddy but we're gonna have to close this [wontfix][unable to reproduce]

**Comment by ghost** [comment]
So the code that seems relevant to this is:

[/obj/structure/bed/chair/comfy/New()](https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/game/objects/structures/stool_bed_chair_nest/chairs.dm#L286)
```dm
/obj/structure/bed/chair/comfy/New()
	..()
	buckle_overlay = image("icons/obj/objects.dmi", "[icon_state]_armrest", CHAIR_ARMREST_LAYER)
	buckle_overlay.plane = relative_plane(ABOVE_HUMAN_PLANE)
	legs = image("icons/obj/objects.dmi", "[icon_state]_legs", CHAIR_LEG_LAYER)
	legs.plane = FLOAT_PLANE
	legs.appearance_flags = RESET_COLOR
	overlays += legs
	..()
	overlays += buckle_overlay

/obj/structure/bed/chair/comfy/turn/handle_layer()
	layer = OBJ_LAYER
	plane = OBJ_PLANE
```

[/obj/structure/railing/update_dir()](https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/game/objects/structures/railings.dm#L176C2-L176C36)
```dm
/obj/structure/railing/update_dir()
	..()
	switch(dir)
		if(1)
			layer = RAILING_BACK_LAYER
		if(2)
			layer = RAILING_FRONT_LAYER
		if(4, 8)
			layer = RAILING_MID_LAYER
```

As well as all the layer stuff in [__DEFINES/planes+layers.dm](https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/__DEFINES/planes%2Blayers.dm) Changing

```dm
#define ABOVE_HUMAN_PLANE 		(10 + FLOAT_PLANE)			// For things that should appear above humans.

	#define SHADOW_LAYER				0
	#define VEHICLE_LAYER 				0
	#define CHAIR_ARMREST_LAYER 		0
	#define DISPOSALS_CHUTE_LAYER 		0
	#define RAILING_BACK_LAYER 			0.1
	#define RAILING_MID_LAYER 			0.2
	#define RAILING_FRONT_LAYER 		0.3
	#define WINDOOR_LAYER 				1
	#define OPEN_CURTAIN_LAYER			2
	#define CLOSED_CURTAIN_LAYER		3
	#define CLOSED_FIREDOOR_LAYER		4
	#define POTTED_PLANT_LAYER			5
	#define LIGHT_FIXTURE_LAYER			6
	#define CHAT_LAYER					7
```
to
```dm
#define ABOVE_HUMAN_PLANE 		(10 + FLOAT_PLANE)			// For things that should appear above humans.

	#define SHADOW_LAYER				0
	#define VEHICLE_LAYER 				0
	#define CHAIR_ARMREST_LAYER 		0
	#define DISPOSALS_CHUTE_LAYER 		0
	#define WINDOOR_LAYER 				1
	#define RAILING_BACK_LAYER 			2.1
	#define RAILING_MID_LAYER 			2.2
	#define RAILING_FRONT_LAYER 		2.3
	#define OPEN_CURTAIN_LAYER			2.4
	#define CLOSED_CURTAIN_LAYER		3
	#define CLOSED_FIREDOOR_LAYER		4
	#define POTTED_PLANT_LAYER			5
	#define LIGHT_FIXTURE_LAYER			6
	#define CHAT_LAYER					7
```

Seems to provide improvement on my end (pictured) but I'm not sure if it's the optimal approach and it needs more testing. I don't understand how the overlay plane/layers are getting set this way as view variables shows me plane values that would appear to cause the railing to always be displayed above chair parts, even without my changes. Perhaps I will open a draft PR for this.
![image](https://github.com/vgstation-coders/vgstation13/assets/145183032/c69ea420-85ce-4595-beda-e78796be0ee8)

EDIT: It's also super confusing why my change even works. You would think setting the RAILING_{THING}_LAYER values to anything above CHAIR_ARMREST_LAYER (0) would work, but for me it was only working when I set them to at least 2. Very odd.
