### ISSUE TITLE
Advanced Lungs do not filter gasses

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#35046]
#### Description of issue
Advanced lungs don't properly filter 

#### Difference between expected and actual behavior
Advanced lungs do not filter gasses as intended, so you still take toxin damage even if the air contains enough breathable gasses to otherwise be fine. Example pictured below:
![dreamseeker_uzON8AYrh6](https://github.com/vgstation-coders/vgstation13/assets/111808553/ddf837b3-50a2-4957-b60e-6182d4d55132)

#### Steps to reproduce
Get advanced lungs, walk into an area with toxic gasses, attempt to breathe.

#### Length of time in which bug has been known to occur
No idea, but a trialmin I spoke with knew the lungs didn't work properly. Quite a while, apparently.

**Comment by ghost** [comment]
This appears to be due to advanced lungs not providing a total immunity to toxins, but an increased ability to tolerate them. We see the default values for human lungs in [/datum/organ/internal/lungs](https://github.com/Inorien/vgstation13/blob/a380d8a905edbbbcccf624dffd38c475f7a31785/code/modules/organs/internal/lungs/lung.dm#L18):
```dm
// DEFAULTS FOR HUMAN LUNGS:
var/list/datum/lung_gas/gasses = list(
	new /datum/lung_gas/metabolizable(GAS_OXYGEN,            min_pp=16, max_pp=140),
	new /datum/lung_gas/waste(GAS_CARBON,            max_pp=10),
	new /datum/lung_gas/toxic(GAS_PLASMA,                    max_pp=0.5, max_pp_mask=5, reagent_id=PLASMA, reagent_mult=0.1),
	new /datum/lung_gas/sleep_agent(GAS_SLEEPING, min_giggle_pp=0.15, min_para_pp=1, min_sleep_pp=5),
)
```
And the values for advanced lungs in [/datum/organ/internal/lungs/filter](https://github.com/Inorien/vgstation13/blob/a380d8a905edbbbcccf624dffd38c475f7a31785/code/modules/organs/internal/lungs/filter.dm#L11):
```dm
var/list/intake_settings=list(
	GAS_OXYGEN = list(
		new /datum/lung_gas/metabolizable(GAS_OXYGEN,            min_pp=16, max_pp=280),
		new /datum/lung_gas/waste(GAS_CARBON,            max_pp=10),
		new /datum/lung_gas/toxic(GAS_PLASMA,                    max_pp=5, max_pp_mask=0, reagent_id="plasma", reagent_mult=0.1),
		new /datum/lung_gas/sleep_agent(GAS_SLEEPING, min_giggle_pp=1, min_para_pp=5, min_sleep_pp=10),
	),
	GAS_NITROGEN = list(
		new /datum/lung_gas/metabolizable(GAS_NITROGEN,          min_pp=16, max_pp=280),
		new /datum/lung_gas/waste(GAS_CARBON,            	max_pp=10), // I guess? Ideally it'd be some sort of nitrogen compound.  Maybe N2O?
		new /datum/lung_gas/toxic(GAS_OXYGEN,                    max_pp=0.5, max_pp_mask=0, reagent_id=GAS_OXYGEN, reagent_mult=0.1),
		new /datum/lung_gas/sleep_agent(GAS_SLEEPING, min_giggle_pp=1, min_para_pp=5, min_sleep_pp=10),
	),
	GAS_PLASMA = list(
		new /datum/lung_gas/metabolizable(GAS_PLASMA, min_pp=16, max_pp=280),
		new /datum/lung_gas/waste(GAS_OXYGEN,         max_pp=10),
		new /datum/lung_gas/sleep_agent(GAS_SLEEPING, min_giggle_pp=1, min_para_pp=5, min_sleep_pp=10),
	)
)
```
With `GAS_OXYGEN` for humans, `GAS_NITROGEN` for vox, etc. The max_pp values for advanced lungs do not provide total immunity.

So I think we need to decide how we want advanced lungs to work. Do we just want them to provide a total immunity to waste, toxic, and sleep_agent lung gasses, for all races, or is how they are now how we want them to function?

**Comment by pedr69** [comment]
are those nitrous values in parts per million? or percent?
because i was definitely sent to sleep with 1% nitrous in the air instead of >10

**Comment by falcon2346** [comment]
> So I think we need to decide how we want advanced lungs to work. Do we just want them to provide a total immunity to waste, toxic, and sleep_agent lung gasses, for all races, or is how they are now how we want them to function?

I honestly cannot imagine going to the roboticist for the privilege of taking a bit less toxic damage in the event of a plasma flood. Even less so in the case of a vox where you're constantly on internals and checking your pressure anyways so actually breathing oxygen is pretty rare. I think it should probably filter out the damaging gas entirely.

**Comment by Hinaichigo** [comment]
Maybe they should pull more of the breathable gas out of the air, so you can tolerate lower oxygen environments as a human and lower nitrogen environments as a vox. So lowering the `min_pp` values a bit to 8 or something.

**Comment by ghost** [comment]
@Hinaichigo I think that sounds good. 

So do we all agree on letting advanced lungs filter out all the toxins and sleep gasses? In that case I think all we have to do is just remove the `/datum/lung_gas/toxic` and `/datum/lung_gas/sleep_agent` datums from the advanced lung lists.

**Comment by pedr69** [comment]
could probably buff the rest of the robotic organs a ton, too
