### ISSUE TITLE
Meat in plantbag doesn't empty into grinder

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3505]
Fill plantbag with meat (this is valid functionality and should not be removed), use plantbag on grinder, meat remains in plantbag.

**Comment by Arthurdentist** [comment]
by grinder you are referring to the biogenerator correct?

**Comment by TermedClepe** [comment]
I mean the All in One Grinder.

Not sure about how it interacts with biogenerator.

**Comment by Iamgoofball** [comment]
technically it could be removed as I added it with Synthmeat, but @d3athrow still hasn't brought synthmeat back in when he accidentally'd it with xenobotany.

**Comment by dylanstrategie** [comment]
I can confirm from testing that this is no longer an issue in any form. Slapping a plant bag with meat on a grinder just werks
