### ISSUE TITLE
Too hot/cold air that you breath messages to player are not visible

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#35069]
#### Description of issue
If the air people breathe is really hot or cold, in [lung.dm](https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/modules/organs/internal/lungs/lung.dm#L36), there is code like `H << "<span class='warning'>You feel your face burning and a searing heat in your lungs!</span>"`, but in my testing, it never seems to actually visible by me, and it's not due to the code somehow not reaching the execution point. Even just adding a test `H << "whatever"` line to handle_breath (which fires every 4 seconds or something), I was never able to see that message.

#### Difference between expected and actual behavior
You should see those messages but do not.

To be clear, this is not a problem with the temperature specific code in the handle_breath proc. What I'm encountering is ANY `H << "asdfasdf"` kind of line in that method just not being visible.

#### Steps to reproduce
Go to [lung.dm](https://github.com/vgstation-coders/vgstation13/blob/7e1d1d7d4f83545f664e08bfbe36462bb6c39b29/code/modules/organs/internal/lungs/lung.dm#L36) on your local, add in a `H << "I should be visible, but I'm not"` line, and see that you are not able to see it after compiling/running/entering game.

**Comment by Exxion** [comment]
That should be `to_chat()`. I don't know how it got missed.

**Comment by ghost** [comment]
@Exxion Thank you, pr will be created momentarily.
