### ISSUE TITLE
Cooked food nutriment values are too low

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#3507]
Eating raw food / grinded food into nutriment bars is both faster and more efficient than spending time cooking food, makes chef an artist instead of a cook.

**Comment by 9600bauds** [comment]
Hey, if the only thing you care about is nutriment, Botany with exotic seeds can make more nutriment bars than the entire station will need in minutes. Not to mention the ice cream machine dispenses literally infinite nutriment with zero effort.

Giving more nutriment to cooked food won't solve these, the only thing it will is make people become stuffed after only one burger.

**Comment by TermedClepe** [comment]
Is this a thing where you literally repeat what was said in OP and add nothing?

**Comment by 9600bauds** [comment]
I'm saying I don't think your suggestion solves anything.
That thing about the ice cream machine is also pretty important by the way.

**Comment by dylanstrategie** [comment]
Goofball's machines are nice on paper but they are broken as fuck, both code-wise and gameplay-wise. Hunger is a ridiculously important part of the game

As for cooked food losing nutrients, it's a known problem. Cooked food should inherit all the reagents from its ingredients and add in reagents as seen fit (if any) and raw food should have less starting nutrients

**Comment by Probe1** [comment]
what would happen if the cumulative reagent value exceeded 50, which I thought was the maximum a cooked recipe/snack could have?

also I agree with bauds but the counter solution, lower nutriment values of raw foods, is equally shitty because it fucks up the biogenerator hard.

**Comment by dylanstrategie** [comment]
If the cumulative reagent value is over 50, I'm pretty sure it simply crunches down all overflowing nutriments

**Comment by Cutelilduck** [comment]
If you really want to give the Chef / Cargo pizzas importance, remove some/all Getmore Chocoloate Corps. Discount Dan's for people who skirt player interaction to see just how big the Chef becomes.

**Comment by ComicIronic** [comment]
Except that's been discussed, and the conclusion was that it would cripple lowpop by adding yet another required job.
