### ISSUE TITLE
(WEB REPORT BY: zalo1302 REMOTE: 198.245.63.50:7777) Message from material synthesizer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3508]
>Revision (Should be above if you're viewing this from ingame!)
a3d8d26835ddf904da2046864f5d9f71d1e939d6 

>General description of the issue
The message you get when you create a material with the material synthesizer is kinda ugly

>What you expected to happen
if i create 1 metal should say
"Added 1 of metal sheet to the stack."

>What actually happened
"Added 1 of /obj/item/stack/sheet/metal to the stack."

>Steps to reproduce if possible
create any material with material synth.

**Comment by dylanstrategie** [comment]
Most likely referencing the wrong thing in the message

I also noticed that the material synthetizer seems to create one less sheet than asked, unless you create 1 sheet. If you create 50 sheets, it gives you 49, and then you have to create one more

Someone needs to do a sweep to see what the fuck is going on with it

**Comment by 9600bauds** [comment]
This only happens with silicons.
Yeah, the material synth has a big block of impenetrable "what the fuck" code for silicon inventory handling. I looked at it briefly and decided this just wasn't for me, especially since I don't play engiborg/MoMMI and don't know how it's supposed to work.

**Comment by clusterfack** [comment]
Sending the reference to the player instead of the reference.name
