### ISSUE TITLE
Player age limit on AAC console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35081]
(WEB REPORT BY: bohaynes REMOTE: 206.221.180.138:7777)
# Revision
b9255acba76025241b263509736641c77ae2254e

# Description
ADMIN LOG: PowerHedgehog/(Malcolm Roberts) attempted to toggle an AAC script despite their player age of 14.

Guy was trying to figure out why he couldn't get the AAC to work for the TEG. Seems unecessary to have an age limit on the console. There's nothing someone can fuck up with the AAC that they can't do with basic hand tools.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by pedr69** [comment]
this is from the hubert era, pretty sure
the script autorun updated every station vent and scrubber and lagged the server to a halt

**Comment by DorainGrey** [comment]
There's definitely things you can do with AAC that can lag the server to bits, mass toggling linked scrubbers etc.

Just easier, to give an ingame IC reason, "You haven't completed your Centcomm Training or something"

**Comment by pedr69** [comment]
or better yet, add a limit to how long the automation scripts can get

**Comment by ValkyrieSkies** [comment]
Pedr is correct, this was quietly added during the Hubert/Nord raid era via a secret repo update to de-fang their AAC based server crashes. It can probably just safely be removed at this stage.

**Comment by Hinaichigo** [comment]
Does player age mean the byond account age or the character's age?

**Comment by Securitymain** [comment]
the age on your id

**Comment by Hinaichigo** [comment]
The in-game ID card?

**Comment by pedr69** [comment]
i'm guessing it's days since your byond account was made

**Comment by ValkyrieSkies** [comment]
> Does player age mean the byond account age or the character's age?

It's days since your account was first seen on the server.

**Comment by jwhitak** [comment]
Unfortunately, this is a feature... This might be able to be changed but the correct avenue would be with the specific server host.
