### ISSUE TITLE
Shooting a window next to you shoots you instead

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35084]
(WEB REPORT BY: calzilla1 REMOTE: 206.221.180.138:7777)
# Revision
f40bd5f75074f0e6b9d2631a138a9d7ba6fc1884

# Description
I know this has already been issued but I've died twice to this bug. Literally game breaking shit. Please stop nerfing vampire into the ground for one second and fix the bugs thanks :)
# Steps to Reproduce
shoot window next to you
Die
# What you Expected
shoot window next to you
Die
# What Actually Happened
Shoot window next to you
Not die

**Comment by boy2mantwicethefam** [comment]
What gun did you use? What type of window was it?

**Comment by Dacendeth** [comment]
#34661 has some more info you want to look into it
