### ISSUE TITLE
Strong potency on plants can ignore the no reactions trait

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35096]
(WEB REPORT BY: doctorsergius REMOTE: 206.221.180.138:7777)
# Revision
f40bd5f75074f0e6b9d2631a138a9d7ba6fc1884

# Description
Plants with the no reactions trait still seem to allow reactions to happen, at least under certain circunstances
# Steps to Reproduce
Got blood tomato seeds, spliced them with no reactions and clonexadone production genes from fossil seeds, spliced together they grow tomatoes that contain clonex and blood in a stable manner past the amounts where they would make meat on harvest, but the no reactions trait seems to stop working past 110 potency or so
# What you Expected
Tomatoes that make 10+ units of synthmeat when eaten/ thrown
# What Actually Happened
Tomatoes that make that amount of meat on harvest as if they didn't have the trait, despite it working at lower potency

**Comment by Doctor-Sergius** [comment]
OP here, just tried increasing the potency of Amauri stalks (the plant meant to showcase the no reaction trait) and the trait stopped working when at 160+ potency, bug probably starts at around 120 potency
New test: 128.3 potency triggered the bug on blood tomatoes
Edit 2: It seems like the trait stopped working anywhere during the round after the first instance of the bug, tried with normal potency Amauri, which are normally very stable, and those didn't work either

**Comment by Hinaichigo** [comment]
Maybe one of these is the cause?
[http://game.ss13.moe/logs/2023/runtime/2023-09-29-runtime.log](url):

```
[12:56:45] Runtime in code/modules/hydroponics/seed_datums.dm,394: list index out of bounds
  proc name: apply gene (/datum/seed/proc/apply_gene)
  usr: Dean Davison (doctorsergius) (/mob/living/carbon/human)
  usr.loc: The floor (275, 256, 1) (/turf/simulated/floor)
  src: new line (/datum/seed)
  call stack:
  new line (/datum/seed): apply gene(/datum/plantgene (/datum/plantgene), 1, Dean Davison (/mob/living/carbon/human))
  the bioballistic delivery syst... (/obj/machinery/botany/editor): Topic("src=\[0x210344f8];apply_gene=1", /list (/list))
  /datum/nanoui (/datum/nanoui): Topic("src=\[0x210344f8];apply_gene=1", /list (/list))
  Doctor_Sergius (/client): Topic("src=\[0x210344f8];apply_gene=1", /list (/list), /datum/nanoui (/datum/nanoui))
```
or
```
[19:23:50] Runtime in code/modules/hydroponics/seed_datums.dm,218: bad index
  proc name: add random chemical (/datum/seed/proc/add_random_chemical)
  src: new line (/datum/seed)
  call stack:
  new line (/datum/seed): add random chemical()
  the modified grass (/obj/machinery/portable_atmospherics/hydroponics): mutate("phytochemistry")
  Unstable Mutagen (/datum/reagent/mutagen): on plant life(the modified grass (/obj/machinery/portable_atmospherics/hydroponics))
  the modified grass (/obj/machinery/portable_atmospherics/hydroponics): process reagents()
  the modified grass (/obj/machinery/portable_atmospherics/hydroponics): process()
  Machinery (/datum/subsystem/machinery): fire(1)
  Machinery (/datum/subsystem/machinery): ignite(1)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing()
```

**Comment by Eneocho** [comment]
You can test it on localhost without mutationwork if you manually add the reagents and the noreact var to the seed, see if it breaks.
I remember being able to make 198 pot no-react plants that behaved as expected, something might have broken recently.

**Comment by Exxion** [comment]
It appears that a seed's `noreact` value just isn't copied over to the new version when it's modified, ever
So splicing it onto an existing plant works, but modifying any other genes in a plant that already has it will remove it

EDIT: #32853 inexplicably removed the line that copied it over, even though it didn't actually change how the var worked

**Comment by Inorien** [comment]
> It appears that a seed's `noreact` value just isn't copied over to the new version when it's modified, ever So splicing it onto an existing plant works, but modifying any other genes in a plant that already has it will remove it
> 
> EDIT: #32853 inexplicably removed the line that copied it over, even though it didn't actually change how the var worked

Adam code introduced a bug??????
