### ISSUE TITLE
(WEB REPORT BY: puglife REMOTE: 198.245.63.50:7777) Incorrect alcohol from still error

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3509]
>Revision (Should be above if you're viewing this from ingame!)
a3d8d26835ddf904da2046864f5d9f71d1e939d6

>General description of the issue
Placing wheat in the still and selecting Ale produces an Ale container filled with wine. I'm guessing this isn't right.

>What you expected to happen
Well I expected it to be full of ale

>What actually happened
I got wine

>Steps to reproduce if possible
Take 1 wheat, insert into still, when prompted select Ale, wait.

**Comment by dylanstrategie** [comment]
Sounds like the index is bumped up one value, or something along those lines
