### ISSUE TITLE
Jittery lighting when moving through a dark space while holding a light

### ISSUE THREAD

**Issue by Hinaichigo** [d3athrow/vgstation13#35095]
#### Description of issue
When moving through a dark space like maintenance while holding a light source like a flashlight, the light appears jittery in that it "jumps" out in front of where you're moving instead of moving with you. I'm pretty sure this used to not be the case, and that the light would move smoothly with you.
I think it was caused by some of the darkness/plane changes @adacovsk did. Someone suggested it was caused by #32890. @ShiftyRail maybe you might know what is going wrong?

#### Difference between expected and actual behavior
Expect light source moving smoothly with the bearer of the light source.
Instead, light source moves out in front of the bearer in a series of jumps.

#### Steps to reproduce
Obtain flashlight.
Turn flashlight on.
Walk through an otherwise-unlit section of maintenance.

#### Length of time in which bug has been known to occur
Possibly since the darkness refactoring around the time of #32890.
[bugfix]

**Comment by Exxion** [comment]
Pretty sure this has always been the case. I don't even know how else it *could* work under our current lighting system.

**Comment by Hinaichigo** [comment]
I can't remember exactly if this was just in comparison to europa lights on the test server or something? I guess I'll try running some older versions and seeing if it was the same.

**Comment by Exxion** [comment]
This is indeed something that Europa specifically fixes.

**Comment by Dacendeth** [comment]
Light system always feels like the first to go when server performance starts having trouble. You see this shit every grue round as there's tons of lights to combat grues then lights start lagging behind because there's so many.

**Comment by Hinaichigo** [comment]
Okay I did a test:
Here's f1449b01ab0df1f477df3664e23b0bd9b8ec0192 (right before #33052):
https://github.com/vgstation-coders/vgstation13/assets/7112773/0a5607c3-12e5-4c84-88e1-4a3785db0c0a
And here's the current behavior:
https://github.com/vgstation-coders/vgstation13/assets/7112773/631b5586-c8ee-4e76-8711-2e7eb06fa060
I guess they're super similar looking so maybe yeah it was comparing to the europa lights.
