### ISSUE TITLE
(WEB REPORT BY: rounders REMOTE: 198.245.63.50:7777) signaller bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3510]
monkeys no longer randomly use remote signallers in their hands

**Comment by ihadtoregisterforthis** [comment]
> [Honk]

**Comment by CptWad** [comment]
I dunno man, admins wont like having to figure out who gave the monkey the signaler in the first place. griff aint fun yo

**Comment by Zth--** [comment]
Make it so they also pick up signalers from the floor (yeah fuck admins)

**Comment by Probe1** [comment]
It's been a year and a half I don't think this is missed enough but you are absolutely welcome to code it.
