### ISSUE TITLE
Allow the multitool to be used on the RPD to determine what frequency new devices appear at

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#35123]
#### Description of issue
It would be extremely convenient if there was a way to set frequencies and ID tags for what devices such as vents or injectors spawned at from the RPD. You rarely actually want things spawned at the default frequency if you're doing something autistic, and if this is possible it would cut down on a lot of multitooling when you're using a setup that involves an AAC.

**Comment by pedr69** [comment]
while you're at it allow multitool copy/paste to digital valves and shit

**Comment by pedr69** [comment]
can probably close this

**Comment by CrazyAmphibian** [comment]
you never closed this issue man
