### ISSUE TITLE
Plasma Cabbage sprite not working properly

### ISSUE THREAD

**Issue by joaomarcosh** [d3athrow/vgstation13#35134]
#### Description of issue
Plasma cabbages are looking like lemons and potatos
![](https://i.imgur.com/8FinA9Z.png)

#### Difference between expected and actual behavior
I expected plasma cabbages to look like purple cabbages

#### Steps to reproduce
Plant cabbages and mutate until you get plasma cabbages

**Comment by joaomarcosh** [comment]
```
/obj/item/weapon/reagent_containers/food/snacks/grown/plasmacabbage
	name = "plasma cabbage"
	desc = "Not to be confused with red cabbage."
	icon = 'icons/obj/hydroponics/cabbageplasma.dmi'
	potency = 25
	filling_color = "#99335C"
	plantname = "plasmacabbage"
```

I commited the icon line, which i shouldnt have, and i think thats what may be causing the issues. However there is no way for me to test it because it works fine on my fork 🤡

**Comment by Kurfursten** [comment]
cannot reproduce on live

**Comment by kacurasuo** [comment]
were you mutating it with radium? (I know you were, you said it on discord)
radium causes targeted mutations in the morphology trait, which will include changing the type of harvest you get
