### ISSUE TITLE
ALL gloves are invisible on Vox

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#35157]
#### Description of issue
It seems like every type of glove is currently invisible on vox. Aside from the other issue mentioning [White Gloves](https://github.com/vgstation-coders/vgstation13/issues/35137) and [Black Gloves](https://github.com/vgstation-coders/vgstation13/issues/35136) I can also confirm that, at the very least, insulated and stun gloves are not visible, so it isn't a stretch to assume that all gloves are simply not visible on Vox currently.

#### Steps to reproduce
Be vox, wear gloves

#### Length of time in which bug has been known to occur
A week or two, I don't know exactly.

#### Server revision
https://github.com/vgstation-coders/vgstation13/commit/108e5d6953abcd9161441a8cc6533e85619e6daf

**Comment by toomykins** [comment]
unable to reproduce
![image](https://github.com/vgstation-coders/vgstation13/assets/29069174/02b8bd87-ee15-4f10-a67f-7033cac7378c)

edit; post outdated, was able to reproduce.

**Comment by falcon2346** [comment]
Just tested it locally and it's still not working on my end. Maybe it's a version thing, I'm running on 515.1608, what are you on?

**Comment by toomykins** [comment]
> Just tested it locally and it's still not working on my end. Maybe it's a version thing, I'm running on 515.1608, what are you on?

the latest. 515.1617

**Comment by Hinaichigo** [comment]
For me it seems like certain gloves are visible, but most aren't.
