### ISSUE TITLE
If you put a full turkey on a plate first you can't cut it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35158]
(WEB REPORT BY: sacredatom REMOTE: 206.221.180.138:7777)
# Revision
451d8149a2227d286a46e7159edb2f61437801d8

# Description
If you put a full turkey on a plate first you can't cut it
# Steps to Reproduce
If you put a full turkey on a plate first you can't cut it
# What you Expected

# What Actually Happened

**Comment by pedr69** [comment]
you can eat monkeycubes on plates safely too
