### ISSUE TITLE
(WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) Can't pull windows in the direction they're facing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3515]
>Revision a3d8d26835ddf904da2046864f5d9f71d1e939d6 

>General description of the issue
Title

>What you expected to happen
the window would be pulled just fine

>What actually happened
it didn't get pulled

>Steps to reproduce if possible
1. make a loose (1 dir)window
2. attempt to pull it into the direction it's facing

**Comment by Exxion** [comment]
Oh, this has been the case so long, I thought it was intentional

**Comment by PJB3005** [comment]
I dunno, it could be, it's a real big nuisance though, since you can just rotate it to pull it

**Comment by Exxion** [comment]
Yeah, I hate it. Very bothersome, especially in space.

**Comment by clusterfack** [comment]
No this is a bug, they didn't always do this. You can also only bump move windows from only 1 of the two directions.

**Comment by Exxion** [comment]
I'm almost certain that window pulling works on tg. Maybe we can steal their code.

**Comment by clusterfack** [comment]
I'm 75% sure it started as a RESULT of porting tg code

**Comment by ComicIronic** [comment]
Not actually fixed, just an error in the Github system.
