### ISSUE TITLE
(WEB REPORT BY: failcakes REMOTE: 198.245.63.50:7777) Spacepod status menu breaks when you change out the power cell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3517]
Revision: a3d8d26835ddf904da2046864f5d9f71d1e939d6 

>General description of the issue
The remaining charge display displays "power cell not found" after swapping cells

>What you expected to happen
A display of remaining charge

>What actually happened
Power cell not found, tossed a super capacity cell from the fabricator in there.

>Steps to reproduce if possible
Swap the cell.

**Comment by PJB3005** [comment]
Unable to reproduce locally

**Comment by clusterfack** [comment]
I managed to reproduce this
