### ISSUE TITLE
New reinforced stuff is nice but!

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#3518]
I can make inf plasteel doing this.

![derpy durr doo](https://cloud.githubusercontent.com/assets/10268342/6768168/641af9c0-d029-11e4-831a-0d7a65044f32.PNG)

happens at the rod step too.

![derpy durr doo part rod](https://cloud.githubusercontent.com/assets/10268342/6768171/c98e4708-d029-11e4-86bc-3a057d28c006.PNG)

**Comment by 9600bauds** [comment]
I'm assuming this is the lack of a busycheck?
Steps to reproduce?

**Comment by AutismSpider** [comment]
no busy check
just mash the same step over and over and that happens
