### ISSUE TITLE
(WEB REPORT BY: thataxxguy REMOTE: 198.245.63.50:7777) Minor graphical error on Gambling Tables

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3519]
2x2 Gambling Tables top and bottom halves do not connect properly graphically, looks wonky due to this..

Minor graphical error.

**Comment by dylanstrategie** [comment]
Would benefit from an actual screenshot so we can pinpoint which sprites exactly need tweaking

**Comment by ComicIronic** [comment]
Found this issue, I'll see about a fix.

**Comment by gbasood** [comment]
This is still an issue.

![imghonk](http://i.imgur.com/U7oa313.png)
