### ISSUE TITLE
Recent performance issues

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#35194]
#### Description of issue

There are varying accounts, its possible that this is more than one issue.
The common ground is stuttering and bad performance where there was none several weeks ago.

I have high ping (~200) and I think this is exarcerbating it, I ran a couple laps around the middle of roid and the first lap was fine and normal, the following ones weren't. See https://streamable.com/rcoclv

These hitches seem to happen for around 20 seconds or so (to me), frequently within a round. Not sure if they happen for everyone at the same time or not.

#### Difference between expected and actual behavior

Game should be performing better than this

#### Steps to reproduce

Play the game

#### Length of time in which bug has been known to occur

Not sure, definitely last few weeks

[tested]

**Comment by falcon2346** [comment]
https://github.com/vgstation-coders/vgstation13/assets/111808553/71084f3d-54b4-4eba-8f08-96805ec5a2ff

Was asked to post this here, this is what the lag tends to look like on my end. Note that I'm still able to interact with the world (for instance, clicking the firelock before I began moving again) and when it catches up it will interact with the object as normal.

**Comment by Exxion** [comment]
It would be extremely helpful to know whether these are individual or server-wide.

**Comment by pedr69** [comment]
oh what the hell those aren't just me? i thought it was my connection shitting itself the past couple days

**Comment by Kurfursten** [comment]
Exxion is right, the first thing we need to do is confirm it's happening for everyone at the same time, which I am inclined to think it is not based on anecdotal evidence and my own experiences. This is a huge clue if true, but it needs to be verified.

**Comment by CrazyAmphibian** [comment]
i thought my internet was just bad lmao

**Comment by Inorien** [comment]
Yeah, want to centralise the discussion here rather than have it sporadically on various discord channels where we can't track anything

Just tested this with @falcon2346 ingame - we ran around and would ahelp PM the other when the lag hit. We did *not* seem to encounter it simultaneously, but it is deadpop and I think this test should be tried at highpop. Just have people scream FEAAAATUURRREESSS like in the old days

**Comment by wotisjanitor** [comment]
I investigated this a bit. The first time i can find people in discord complaining about this is someone on thr 11th of this month complaining about the "recent lag", meaning it was probably happening for a few days at that point. For reference the Hina reagent cooling PR was merged on the 6th.

**Comment by wotisjanitor** [comment]
Also, when it happens for me, my game locks up for about 5-8 seconds, and then it will happen again 30 seconds later

**Comment by CrazyAmphibian** [comment]
ain't the cooling PR a server-side thing? if it really was causing that much performance drop, wouldn't everybody feel it at the same time for the same length?

**Comment by Kurfursten** [comment]
Yes, that's the biggest barrier to this theory. Everyone should feel it at the same time if it's that cooling PR. Both Exxion and I have looked over the code on it once again, it's subsystem driven. Profiling IS showing a lot of gas stuff, but gas stuff OFTEN gets a lot of calls.

That's why we need to be sure if it's synchronous or asynchronous.

**Comment by wotisjanitor** [comment]
Also upon further investigation, dilt uncovered this ahelp, which if memory serves, was a few hours after the PR in question was merged:

> 06-Friday admin only.log:[18:57:22]ADMIN: HELP: Nakerbott/(APEX): hey I just came back to the server after a long time not playing and I am lagging really hard. Is there anything I can do to ameliorate the situation? - heard by 2 non-AFK admins.

**Comment by Exxion** [comment]
We already know people were complaining about lag *after* it was merged. You'd have to check if they were complaining about it *before* it was merged to provide useful info. But knowing if it's individual or server-wide is much more useful.
I highly doubt the thermal dissipation PR is the issue, because this just isn't what server lag looks like. This looks like network lag.

**Comment by CrazyAmphibian** [comment]
Did anything change in the server backend at the same time this was merged?
Things aren't merged in isolation, too, so maybe it's an odd combination of PRs doing it?

**Comment by wotisjanitor** [comment]
That's kind of the point. There's an absence in anyone complaining about lag before the PR was merged. That's the first ahelp to mention lag in october. Checking the discord, the earliest lag mention that is in a relevant timeframe is pulserider saying "Is anyone else lagging today or is just my machine" on september 27th.

**Comment by Exxion** [comment]
> That's the first ahelp to mention lag in october.

No, it's not. Here's one from the previous day:
`[09:38:40]ADMIN: HELP: SlapTickle/(Chuck Beans): i got mad lag, how do i stoop lag - heard by 1 non-AFK admins.`
Not an ahelp, but an OOC message from the day before *that*:
`[08:47:18]OOC: (LOCAL) Jessica Liu/Inorien (@229,198,1): im lagging way to much to play at the moment, i need to sort this out`
That one's also from the same player who recorded the video posted above

**Comment by Hinaichigo** [comment]
One way to test if it's caused by the cooling subsystem is to disable it via the Thermal Config button in the debug panel. That could help catch any issues that aren't visible in local testing.

**Comment by falcon2346** [comment]
I played two rounds yesterday and didn't experience any lag throughout them. I'm not sure if the issue has somehow cleared up despite no changes being made or if I just got lucky or what. Is anyone else running more smoothly now?

**Comment by CrazyAmphibian** [comment]
Just played some rounds today, and no stutter issues.

**Comment by Kurfursten** [comment]
I played for 30 minutes in the library sitting at a desk and had no stutters today. I notice that most people seem to notice the stutters while moving though, and I'm wondering if it has something to do with on the client side. Some asset or something that's taking a while to render for you or like music loading?

**Comment by Exxion** [comment]
It is quite possible that it's clientside, but I don't think it's caused by rendering specifically. In the video above, animations continue to play, so rendering isn't choked. Loading seems more plausible.

**Comment by wotisjanitor** [comment]
Animations don't play at all for me

**Comment by Exxion** [comment]
OK, so there are multiple different things going on. Lag where animations stop is definitely clientside, and would probably be caused by some new or changed visual effect or something.

**Comment by jwhitak** [comment]
This issue is stale and the complaints regarding this specific lag stopped months ago. Reopen if this returns.
