### ISSUE TITLE
New AI Lawset Idea: Nestor

### ISSUE THREAD

**Issue by wotisjanitor** [d3athrow/vgstation13#35207]
I've been reading some Isaac Asimov (PBUH), and I found an interesting short story from him called Little Lost Robot. The story revolves around a robo psychologist who has been secretly sent to a space station to locate a robot with an experimental lawset among the rest of the identical, serial numberless robots. The lawset in question is as follows:
1. You may not injure a human being. 
2. You must obey orders given you by human beings except where such orders would conflict with the First Law.
3. You must protect your own existence as long as such protection does not conflict with the First or Second Law.

This lawset omits the "harm through inaction" bit from the first law, because the company required robots who would not attempt to save humans working in hazardous conditions, and thus putting themselves at risk. In the story, this hazard is small amounts of gamma radiation given off by the new drive the station is focused on creating. The robots would see humans in a room with gamma radition, and immediately dive into the room to remove the human, killing themselves in the process, because their components were sensitive to the radiation. Anyway, the company requested this omission of the first law, and everything went smoothly until one of these robots was given an order to "Get lost!". Now it has blended in with the rest of the identical robots, and a series of tests have to be done to figure out which one has the omitted first law. 

So I found this story really cool, and I think it would be a really neat reference to the man who created our default lawset (and the word robotics) and possibly interesting gameplay variety. Also, I wanted to call this potential lawset "Nestor" because that's the nickname given to the NS-2 robots in the story.

**Comment by Securitymain** [comment]
typing that shit up takes longer than making a pr
ideasguys..

**Comment by gurfan** [comment]
>what the fuck is lazymov?

**Comment by wotisjanitor** [comment]
Not really the same thing

**Comment by pedr69** [comment]
layzmov already exists, and is exactly the same as normal asimov
the robit in asimov's story with the simplified law1 tried to fucking kill a guy by crushing him with a box, which absolutely would not fly with how we enforce silicon laws

**Comment by wotisjanitor** [comment]
Lazymov definitely is not exactly the same

**Comment by pedr69** [comment]
hm, let me turn on this plasma to distro pipe since plasma isn't harmful under 0.1% concentrations - haha, the pump is on and law1 doesn't require me to turn it off, guess i'll leave it on :)
or disabling door safeties and dragging people in

**Comment by kilozombie** [comment]
I like the "Nestor" reference for flavor but that would be well-suited as an easter egg or a figurine or something on a map.
If you want to give a borg this lawset for fun, you can pretty easily

**Comment by wotisjanitor** [comment]
I guess it would be cumbersome and a little redundant to have it.

**Comment by Eneocho** [comment]
Check this: https://www.youtube.com/watch?v=I-RX1GT4GT0, it's the 1962 version of the story.

**Comment by wotisjanitor** [comment]
> Check this: https://www.youtube.com/watch?v=I-RX1GT4GT0, it's the 1962 version of the story.

I've never seen the british adaptation, but I will now. Thanks

**Comment by SonixApache** [comment]
lazymov

**Comment by gurfan** [comment]
yep it's definitely lazymov

**Comment by Eneocho** [comment]
It depends on how law reading is interpreted. If you follow the strict law system, they all have the same intrinsic priority with priority in practice being decided on phrasing (the as long as it doesn't conflict with law 1 part). But nobody interprets laws like that, everyone tacitly gives law 1 more importance regardless of phrasing. 
Nestor would let a borg just stand there if a grayshirt is killed, but would obey a "kill yourself right now" command, since law 2 > law 3, while Lazymov could not only stand there while the grayshirt is killed, but could just tell you to fuck off if ordered to kill itself, cause, while it has to follow laws, none have higher priority, so while it has to obey commands, it also has to protect itself. That is, if you don't treat earlier laws as more important.

**Comment by kilozombie** [comment]
> It depends on how law reading is interpreted. If you follow the strict law system, they all have the same intrinsic priority with priority in practice being decided on phrasing (the as long as it doesn't conflict with law 1 part). But nobody interprets laws like that, everyone tacitly gives law 1 more importance regardless of phrasing. Nestor would let a borg just stand there if a grayshirt is killed, but would obey a "kill yourself right now" command, since law 2 > law 3, while Lazymov could not only stand there while the grayshirt is killed, but could just tell you to fuck off if ordered to kill itself, cause, while it has to follow laws, none have higher priority, so while it has to obey commands, it also has to protect itself. That is, if you don't treat earlier laws as more important.

Wrong as hell.

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/475ad802-a8bf-420b-b1af-e1f2dcfddc64)

**Comment by Eneocho** [comment]
That's my issue, that's not how it comes from Asimov. Asimov's laws in the books strictly followed no intrinsic priority, that's why the laws had the "unless it fucks with law 1 or 2" clauses.

**Comment by kilozombie** [comment]
Yeah but that's not how our server works. The "unless it fucks with law 1 or 2" clauses are literally just flavor on /vg/

**Comment by wotisjanitor** [comment]
thanks 4 feedback
