### ISSUE TITLE
(WEB REPORT BY: fireice2k8 REMOTE: 198.245.63.50:7777) remote stacking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3521]
>94ff538c9bd460af5b064ad642b6adb100a4d121 

>can add stackable objects to a stack from any point, as long as they're on-screen

>not being able to add fucking bruisepacks to the stack in my hand from 4 tiles away and through a window

>being able to add fucking bruisepacks to my hand from 4 tiles away and through a window

>get stackable item (cable coil, bruise packs, floortiles, any sheets)
click stackable item on stackable item of the same type
marvel at your magnetic fingers

**Comment by ComicIronic** [comment]
#3522
