### ISSUE TITLE
Some department lights dont turn on at roundstart even if theyre manned

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#35228]
#### Description of issue

eg. tool storage light never turns on despite roundstart assistants 
not sure which other jobs are affected

#### Difference between expected and actual behavior

Lights should be on

#### Steps to reproduce

Be assistant at rounstart, observe the lights are off

#### Length of time in which bug has been known to occur

Since #35198

**Comment by boy2mantwicethefam** [comment]
I tried to get rid of it altogether but...
