### ISSUE TITLE
Chimps Chewing Chumps

### ISSUE THREAD

**Issue by SangriaMonkey** [d3athrow/vgstation13#3524]
So as it turns out, hadcuffed monkeys can still attack you. And at Kenshiro speeds too. Try it out it's pretty funny.

**Comment by d3athrow** [comment]
I dont see how monkeys being able to bite yourshit while cuffed is a bug, but not being delayed surely is.

**Comment by Killette2** [comment]
This means hulked out monkeys can easily wreck shit, and yes monkeys can be hulks.
