### ISSUE TITLE
Request: Toggle Solo Antag Objectives to "Standard" by Default

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35269]
(WEB REPORT BY: gimmick1 REMOTE: 206.221.180.138:7777)
# Revision
82f4f828834c96888027eb85546657b5782360e7

# Description
Make Solo Antag Objectives option in General Settings tab be set to "Standard" by Default. 
# Further Explanation
"Freeform" (aka "go do whatever lol") objective is uninspiring cancer that leaves you scratching your head and wondering what to do next while the normal, classic objectives more or less define what you'll be doing this shift. If you get an objective you don't like or reasonably don't care about doing objectives in the first place you are free to ignore them or to set the option to "Freeform".
# Why it's good
New players will have easier time playing solo antags, especially if they've migrated from other SS13 servers.

DISCUSS and feel free to make a pull request if any of you coders are interested.

**Comment by kilozombie** [comment]
Years ago I advocated for what is now the current system (freeform and attack animations off by default). Now I'm in favor of the opposite.

Return us to the era of shitty jecties
