### ISSUE TITLE
AI cores being tased scream

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35278]
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
82f4f828834c96888027eb85546657b5782360e7

Justin Thyme fires the energy gun!

Emma-2 is hit by the electrode in the chest!

Unusable emote 'screams'. Say *help for a list.

**Comment by Killette2** [comment]
Does stun batoning an AI make them spit out their sentence mid typing too while we're at it?

**Comment by juanototo2** [comment]
Clearly someone needs to add in the R2D2 scream as a audible scream for silicons.
