### ISSUE TITLE
Survivor status not appearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35281]
(WEB REPORT BY: comicthunder REMOTE: 206.221.180.138:7777)
# Revision
82f4f828834c96888027eb85546657b5782360e7

# Description
was given wizard robes, magic, and a gun roundstart. however apparently i was not given survivor status. Yvvel said it's most likely due to wizard changes
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DorainGrey** [comment]
Not a bug, neverplayer detected.

**Comment by kilozombie** [comment]
Yvvel is being silly, Survivor only has a chance to be applied to any individual crewmember per Summon Robes/Guns etc
