### ISSUE TITLE
code delta doesn't count as code red for combat borg unlocking

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#35292]
#### Description of issue
>code red
>combat borgs unlock
>AI goes delta
>combat borgs lock back up

#### Specific information for locating

https://github.com/vgstation-coders/vgstation13/blob/01d7633b7e470c0fe937dc9918ff7a337e2a3f4e/__DEFINES/silicon.dm#L55

#### Server revision
0c05bb67acc816af4ecfd9554dd68ed18f416ffa

**Comment by nervere** [comment]
I've made a PR to change this but fixing this inconsistency will also significantly buff Malf AI so it may be closed. I'll see what people think.
