### ISSUE TITLE
Roulette revolver is not in the create a turret options for badmins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35302]
(WEB REPORT BY: manylo REMOTE: 206.221.180.138:7777)
# Revision
07384d885be8e82149920349bf12c5a090bcb3b2

# Description

wanted to create a roulette revolver turret (for centcomm) 

# Steps to Reproduce

can't do it 

# What you Expected

# What Actually Happened

**Comment by nervere** [comment]
The turret creation button (in secrets menu) only looks for energy weapons as that's all that turrets work with, apparently. Not a bug so I've marked this as a feature request.

**Comment by GreatBigFailure** [comment]
The idea of turrets working with anything but energy weapons is terrifying. If done at all it should be in an extremely limited way, like case-by-case allow certain guns. There's already some goofy turrets you can make with just energy weapons.
Alternatively, make it all guns for the giggles

**Comment by west3436** [comment]
Closed via #35807.
