### ISSUE TITLE
Cable coil placement blocked by floor tile in adjacent tile under the player

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35319]
(WEB REPORT BY: superflybox REMOTE: 206.221.180.138:7777)
# Revision
65af56430968cb6b28fe6878c62903be346e45f8

# Description
Attempting to complete a cable knot into a smooth cable will sometimes give the message, "You can't place cables there."
# Steps to Reproduce
It will occur when the direction the new cable will face touches a tiled floor.  Removing the floor tile enables the cable knot to be completed into a cable.
# What you Expected
I expected to be able to place a cable on an open flooring spot.
# What Actually Happened
It blocks this placement due to a floor tile in a tile other than the targetted cable tile.

**Comment by DeityLink** [comment]
Ah yes I see the problem
