### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Project mind being treated like wizard spell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3531]
http://puu.sh/gL3qu/31dba796cc.png

The genetic ability Project Mind is showing up as a wizard spell for some reason.
I am unable to project mind without a wizard outfit.

**Comment by ComicIronic** [comment]
Could someone say WOOOOPS
