### ISSUE TITLE
infinite kitchen gibber

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35323]
(WEB REPORT BY: hornylevel2 REMOTE: 206.221.180.138:7777)
# Revision
65af56430968cb6b28fe6878c62903be346e45f8

# Description

# Steps to Reproduce

# What you Expected
to not be able to leave the gibber mid grind
# What Actually Happened
you can exit the gibber and get your meatinfinite times

**Comment by nervere** [comment]
This is my bad, when I fixed the autogibber for silicons it seems I introduced this bug. I'll make a fix now.
