### ISSUE TITLE
Wierd turret targetting behavior

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35320]
(WEB REPORT BY: realestestate REMOTE: 206.221.180.138:7777)
# Revision
65af56430968cb6b28fe6878c62903be346e45f8

made a custom smartlaser turret set to target non-ID lifeforms only (no on all other types).
whenever someone was prone in sight it would start shooting them as if they didn't have an ID.

**Comment by pedr69** [comment]
related turret targeting PR's
#34511
#34456
#33929
