### ISSUE TITLE
gloves are invisible on vox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35334]
(WEB REPORT BY: gurfan REMOTE: 206.221.180.138:7777)
# Revision
aa36ddd57e1fcbae4274c8622620f67370904035

**Comment by pedr69** [comment]
#35136
#35137
#35157
#35220

**Comment by MercuriusGH** [comment]
>[Hinaichigo commented [Oct 22, 2023]
>I'll try to fix it. Thanks for finding it. I'm going to be busy irl for the next few days but after that I can.

it's over
