### ISSUE TITLE
Engicoffee recipe is impossible.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35339]
(WEB REPORT BY: armadingus REMOTE: 206.221.180.138:7777)
# Revision
aa36ddd57e1fcbae4274c8622620f67370904035

# Description
The recipe for NT Standard Battery Acid, the coffee for prioritised engineers, requires 5u coffee + 1u welder fuel + 5u sulfuric. The sulfuric reagent in the recipe does not exist and I can only assume that it's meant to be SACID instead of SULFURIC.

# Steps to Reproduce
1) Acquire coffee, welding fuel and sulphuric acid
2) Mix together in whatever container
3) observe lack of ingestible fuel

# What you Expected
Coffee that staves off radiation

# What Actually Happened
Liver failure and face melting drink

**Comment by Exxion** [comment]
I fucking hate the BYOND feature that makes this kind of mistake possible
This would be an example of a very useful unit test, but it's also kind of a pain in the ass to do it properly

This particular bug is indeed caused by exactly what the OP says
