### ISSUE TITLE
Wheel: Medbay doors don't auto-open from the inside

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35346]
(WEB REPORT BY: sonixapache REMOTE: 206.221.180.138:7777)
# Revision
012b0fbb315ca27c0a151bb266f0be9301ea1e34

They don't have the thing where you can open them without access from one side.

**Comment by brndd** [comment]
They're right there

![2023-11-07T04:22:03](https://github.com/vgstation-coders/vgstation13/assets/5822375/ab55560f-0941-4eae-8609-0abe59fcc28e)

edit: Oh, I see what you mean, there's a new req_access_dir variable. Thanks.
