### ISSUE TITLE
(WEB REPORT BY: shomek REMOTE: 198.245.63.50:7777) Solar Control not showing generated power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3535]
Revision: 68131129ef7f6930123c1167daa09bff889f5bdc

The Solars console doesn't show the generated power anymore (it used to).

>Steps to reproduce if possible
Wire solars. Set console to AUTOMATIC.
Use multitool to check the power in the wires, so you can confirm everything is actually working
Notice the station actually has power &APC are being charged.
Consoles still say you generate 0 power.

**Comment by dylanstrategie** [comment]
Seems related to the general fuckedness of powernets, could be related to the recent transition of catwalks which forced some bargains to have cable coils able to be laid "in space" on catwalks

Try to check in a controlled environment where all the tiles of the solar are solid plating, if it still happens then it's the powernet in general that is fucked

**Comment by ComicIronic** [comment]
Doesn't look like a powernet issue if multitool testing still registers power.

**Comment by clusterfack** [comment]
I can confirm this is working now
