### ISSUE TITLE
radium from radium smoke grenades are gray, not green

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35353]
(WEB REPORT BY: primed REMOTE: 206.221.180.138:7777)
# Revision
9ca01ed00ae6469ffde0ffd627a557e994eb7663

# Description
they dont glow either

**Comment by Eneocho** [comment]
IRL radium is silver white-metallic so feature(TM).

**Comment by nervere** [comment]
Gonna be fixed in #35451
