### ISSUE TITLE
Air alarms in space???

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35369]
(WEB REPORT BY: adacovsk REMOTE: 206.221.180.138:7777)
# Revision
893c7b4867e1e86c07b9873bc15591367d0418c1

# Description
https://imgur.com/u2qM94Z.jpg
# Steps to Reproduce

# What you Expected
no air alarms
# What Actually Happened

**Comment by nervere** [comment]
This issue does not have nearly enough info to be reproduced or fixed.
