### ISSUE TITLE
Air alarms in space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35379]
(WEB REPORT BY: adacovsk REMOTE: 206.221.180.138:7777)
# Revision
893c7b4867e1e86c07b9873bc15591367d0418c1

# Description
https://i.imgur.com/u2qM94Z.jpg
# Steps to Reproduce
go out into space and find rows and columns of air alarms
# What you Expected
no alarms
# What Actually Happened
found air alarms

might be related to a fault and a mapper fat fingering (re: frying pan incident)

**Comment by pedr69** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/18052467/94f25eb1-feba-424b-ac75-82f5198d6fac)
map is box

**Comment by Eneocho** [comment]
feature(TM)

**Comment by pedr69** [comment]
if only THE FUCKING MAPDIFF BOT WERENT BROKEN
