### ISSUE TITLE
screaming while dead, an agony without end. I have no life and I must scream.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35370]
(WEB REPORT BY: hornylevel2 REMOTE: 206.221.180.138:7777)
# Revision
893c7b4867e1e86c07b9873bc15591367d0418c1

# Description

# Steps to Reproduce

# What you Expected
for my dead lifeless corpse to not feel eternal agony
# What Actually Happened
when stepping on glass as a dead person you still try to mote

Unusable emote 'screams'. Say *help for a list.x2

**Comment by Eneocho** [comment]
Similar issue happens when you superfart. Immediately after the superfart, you get an "Unusable emote "*fart". Say *help for a list" blurb.

**Comment by Securitymain** [comment]
Yeah I know... I'll revert my PR (it was my first one ever) eventually or fix it.
