### ISSUE TITLE
Grue can't see in dark

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35381]
(WEB REPORT BY: adacovsk REMOTE: 206.221.180.138:7777)
# Revision
893c7b4867e1e86c07b9873bc15591367d0418c1

# Description
messed up overlays
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by nervere** [comment]
Tested it and works fine for me.
This issue does not have nearly enough info to be reproduced or fixed.
