### ISSUE TITLE
Diona can't be controlled after taking monkey SE

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3538]
I evolved into a full-grown Diona, and wanted to turn back into a nymph, so I injected myself with a monkey SE. It worked, but I was unable to move, and when I tried throwing items, I dropped them instead. No idea what happened.

**Comment by Shadowmech88** [comment]
This also happened when I injected myself with a monkey injector as a human. I became a monkey, but I couldn't move and thrown items didn't move off my tile.

**Comment by dylanstrategie** [comment]
Seems directly related to about every single issue with monkey SEs ejecting people from their bodies, or general fuckery with monkey to human and human to monkey transitions

**Comment by MercuryDoll** [comment]
Can confirm, however the bug is "fixed" once you're pulled or your mob gets otherwise moved it seems, at least in my case.
