### ISSUE TITLE
Wheelstation Cargo - Shuttle Conveyors are Backwards

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35395]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
fe539d65f43db559f03d28d7c9bdd1f2be5616a4

# Description
The conveyor belts on the cargo shuttle point in the wrong direction.

**Comment by jwhitak** [comment]
![wrongway](https://github.com/vgstation-coders/vgstation13/assets/69739118/7b21c330-2971-4877-810a-370b30a86ee5)
Ruh roe!
