### ISSUE TITLE
Wheelstation Cargo - Mining has a Nanomed Plus

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35396]
(WEB REPORT BY: dilt REMOTE: 206.221.180.138:7777)
# Revision
fe539d65f43db559f03d28d7c9bdd1f2be5616a4

# Description
On the Roid, the mining medical room has a Nanomed Plus instead of a standard Nanomed. The Nanomed Plus requires Medical access to use. There's no standard one available... Miners who get hurt will be in trouble.

**Comment by jwhitak** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/69739118/23c47994-60e5-4ebe-bca5-7c1f3f92f541)
