### ISSUE TITLE
Recycling Room Death Trap

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#35417]
![dreamseeker_EVsQDa1fsG](https://github.com/vgstation-coders/vgstation13/assets/111808553/83278c4b-fdff-4fec-aa40-8f8b4f3f1b20)
This particular room in Box station has 0 atmosphere at round start, and I'm not sure it's intentional. In practice this means tossing someone into the trash who's unconscious or otherwise unable to stand up is going to die if the conveyers are on, even if they're not shot out of the mass driver.
[oversight]

**Comment by Kurfursten** [comment]
That's definitely intended, that's why there are flaps on both sides and it has a door to space. Yeah they'll die if the shutter to final disposal is left open, so don't do that!! People should be less careless with bodies.

**Comment by Blithering** [comment]
I recommend adding an airless environment warning sign to that antechamber, surely proper signage will save lives.

**Comment by falcon2346** [comment]
In that case there's no issue here then
