### ISSUE TITLE
(WEB REPORT BY: fudgepucker REMOTE: 198.245.63.50:7777) Atmos fucked up on dierlect.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3542]
>Revision (Should be above if you're viewing this from ingame!)
-4add6d

>General description of the issue
SHITS FUCKED, SHITS FUCKED.
A cold loop connected to the plasma vent in the atmospherics room in dierlect is room tempature and at 100 kPa. When attempting to unwrench a canister from a connector it didn't. IT JUST DIDN'T.
IT JUST DIDN'T
IT JUST FUCKING DIDN'T

O2 vent also fucked up.
Simple volume pump to connector with a canister on top of it.
No gasses detected in canister.

EVERYTHING IS FUCKED UP.
GOD HELP US ALL. THE UNIVERSE IS AS BROKEN AS A RAPE VICTIM.
AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

>What you expected to happen
Cold plasma and a canister at 9000 kPa of O2

>What actually happened
A magical unattachable canister.
An empty canister.
And I think the universe is crying in pain.
Existance is on fire.
Run.

>Steps to reproduce if possible
Do anything relating to atmospherics.
Panic.
PANIC.

**Comment by dylanstrategie** [comment]
Please do more testing, with more controls, because this would imply a lot of shit is broken, at once, and in a critical fashion

**Comment by DrCelt** [comment]
I encourage you to log in, dylan.

**Comment by DrCelt** [comment]
Is not fixed. Reopen.

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/pull/3550
