### ISSUE TITLE
[Feature Request] Re-add puddles but with some tweaks.

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#35423]
I figure most of the puddles are uncleanable issues could be resolved with a squeegee and dedicated drain holes on certain rooms. Using the thing would push the entirety of the puddle to the tile in front of itself (maybe add a bluespace one that immediately teleports it to a drain). If a tile had a drain or was one of the 4 cardinal tiles around it, the liquid would quickly (but not immediately) be removed. 
I feel that THAT, alongside some evaporation mechanic, a change to how smoke generates puddles, working sodium poly and a tweaked lube (so a 5u spray makes a puddle that lasts as long as it does pre-puddles, but you can dump tons in an area to make it last longer) would make puddles much more functional. It could even work alongside the new(ish) heat mechanics, hotter rooms drying faster and cold rooms freezing the puddle into ice. I miss the puddles (the halls did run brown with coffee).
[featurerequest]

**Comment by brndd** [comment]
Easy solution for drain holes: make scrubbers work as drain holes. It might not really make sense if you think about it too hard, but it's close enough.

**Comment by DorainGrey** [comment]
Even SS14 struggles with performant puddles, I just don't think it's viable in a balanced and actually fun to use way.

**Comment by SacredAtom** [comment]
if we bring any kanef puddle code back ill drive a car through your bedroom

**Comment by Eneocho** [comment]
i miss making the halls run brown with coffee puddles, guess now it's the paint meta
