### ISSUE TITLE
NRV Horizon: Cargo Conveyor Belts Are Screwed Up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35473]
(WEB REPORT BY: gimmick1 REMOTE: 209.222.101.3:7777)
# Revision
17ab49ba93f974ba8bcfddf3de8800b84d31aefb

# Description
Cargo Shuttle has its conveyors facing the opposite direction of the station's conveyors. The upper-most station's conveyor belt going away from the Cargo Shuttle is also connected to the wrong switch.
# Steps to Reproduce
Sign up as Cargo Tech on NRV Horizon.
# What you Expected
For everything to be work properly.
# What Actually Happened
Ditto.

**Comment by GreatBigFailure** [comment]
Specifically it's just a few of them going in the wrong direction. If I remember right it was 3-4 of them, mostly on the shuttle side of the belt.
