### ISSUE TITLE
Medical Records Are Missing Images For The Roundstart Crew

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35471]
(WEB REPORT BY: gimmick1 REMOTE: 209.222.101.3:7777)
# Revision
17ab49ba93f974ba8bcfddf3de8800b84d31aefb

# Description
Medical Records miss images for those that have declared ready. Latejoiners have their images intact.
# Steps to Reproduce
Open a Medical Records console.
# What you Expected
For the images to be there.
# What Actually Happened
Blank rectangles.

**Comment by DeityLink** [comment]
Definitely caused by #35408
