### ISSUE TITLE
[Meta] Missing kitchen items

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3548]
Meta's kitchen doesn't have a Chef's plant bag, or any mint.
It also only has 1 free table tile which results in everything being cramped into the same table, which looks godawful honestly.

**Comment by Probe1** [comment]
if I remember correctly there are additional tables in the kitchen backroom.

**Comment by 9600bauds** [comment]
There are, but all the starter items are forced into one tile.
Also, since the kitchen is 5 tiles tall, you can't make a 2-tall set of tables since it obstructs your way.

**Comment by Probe1** [comment]
I agree it is messy.  I was offering food for thought.  I don't think they're existence dismisses the lack of tables in the kitchen.  

Expanding the kitchen I feel like can only come at the cost of another area and I believe that kitchens on all maps are already large enough.

**Comment by 9600bauds** [comment]
They are large enough... after you unwrench Goof's machines and mothball them in the backroom with Pete.

**Comment by IratePirate** [comment]
I'll see what I can do about this.
