### ISSUE TITLE
Horizon R&D has no stock parts roundstart among other things

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35486]
(WEB REPORT BY: wotisjanitor REMOTE: 209.222.101.3:7777)
# Revision
3dbc4b2464a7a04e7304d4df12b69379f562192d

# Description
the typical stock parts that every r&d has such as console screens, scanning modules, micro-manipulators, capacitors, power cells, and so on are missing on horizon. Also, no welding fuel tank, a light fixture is missing in the surgery area, and there is no robotics cell charger.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by DorainGrey** [comment]
Fixed by #35493
