### ISSUE TITLE
pretty sure horizon is missing a research archive library computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35487]
(WEB REPORT BY: wotisjanitor REMOTE: 209.222.101.3:7777)
# Revision
3dbc4b2464a7a04e7304d4df12b69379f562192d

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by nervere** [comment]
They all are, I'm in the process of adding this and several more new computers to all maps.
