### ISSUE TITLE
NRV Horizon: Trade Port is Missing Most Essentials

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#35494]
#### Description of issue
The trader dock on Horizon does not have the trade outfitter or trade window so you're not able to get any of the unique trader items. Additionally the SMES on the trade port has unlimited energy, and the port does not have the parts to construct a fish tank engine or any other power source.

#### Difference between expected and actual behavior
Expected: Join as trader and be able to purchase and sell crates as normal, as well as items to help facilitate trades
Actual: The only unique items you have access to are Vox plants.

#### Steps to reproduce
Join as trader

**Comment by Eneocho** [comment]
feature
no mercy for birds
