### ISSUE TITLE
Plates are flammable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35490]
(WEB REPORT BY: vampirebat74 REMOTE: 209.222.101.3:7777)
# Revision
3dbc4b2464a7a04e7304d4df12b69379f562192d

# Description
What it says on the tin

# Steps to Reproduce
Set the kitchen on fire

# What you Expected
Flammable things flammed

# What Actually Happened
What the fuck where are my plates

**Comment by jwhitak** [comment]
Plates, even fine bone china, can crack and shatter in high temperatures. Just a thought to keep in mind
