### ISSUE TITLE
NRV Horizon Technical Storage Mapping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35500]
(WEB REPORT BY: superflybox REMOTE: 209.222.101.3:7777)
# Revision
cd3fa45fc8c586d26c5c67fb409bd2b07e9d3e36

# Description
The technical storage on Horizon has a reinforced wall as well as a reinforced plasma glass window overlayed on top of each other, causing clipping.
# What you Expected
One or the other to be there.
# What Actually Happened
As you walk by, you see a window phase into existence then disappear under the rwalls.

**Comment by DorainGrey** [comment]
This is by design, similar to how deff perma works & the perma beside it.
What kinda clipping are you seeing?
