### ISSUE TITLE
Pulse Demon Gun Hijack Sucks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35510]
(WEB REPORT BY: dovemite REMOTE: 209.222.101.3:7777)
# Revision
89f7b1d376c2349a70e8e5cd838e032e242ce3bd

# Description
See title, hijacking a gun sucks despite how it most likely would never occur normally. You cannot shoot the gun like a pAI slot gun could. Despite being in the gun, you'll die from lack of atmos. I don't think you can even get out of it if you leave the area where you do it
# Steps to Reproduce
Be Pulse Demon
Hijack a gun in a recharger

# What you Expected
Firing off lasers to cause mischief
Hitch hiking a ride
Being safe from atmos since I'm in a fucking gun
# What Actually Happened
Die from lack of pressure
No discernable way to leave the gun, can't wire hop or just walk out with the leave wire ability
No way to fire the gun

**Comment by boy2mantwicethefam** [comment]
This could have been prevented.

**Comment by DorainGrey** [comment]
Nobody is ever going to fix this but the terminal github users won't allow it to be disabled either.
