### ISSUE TITLE
Plant harvests don't combust

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35520]
(WEB REPORT BY: adacovsk REMOTE: 209.222.101.3:7777)
# Revision
bca2f9235e00ef6ad79d22b6b094c3ec80cd5f86

# Description
I made a hot room filled with plants and harvested them and they didn't combust
# Steps to Reproduce
Make lots of plant products through botany and superheat the room
# What you Expected
lots of fire and combustion and smoke
# What Actually Happened
hot air

**Comment by DeityLink** [comment]
Plants, just like all snacks don't have set ignition temperature or amount of fuel. #35516 fixes half of that by giving them a fuel amount. Now they just also need an ignition temperature.

**Comment by west3436** [comment]
Just slap an AUTOIGNITION_FABRIC or AUTOIGNITION_PAPER on the produce parent item tbh
