### ISSUE TITLE
(WEB REPORT BY: merkurlicht REMOTE: 198.245.63.50:7777) Can't wet mop with regular bucket

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3553]
Like seriously, why was this left out? Same as sinks and water container

**Comment by dylanstrategie** [comment]
Did you fill the mop bucket with water ?

**Comment by MercuryDoll** [comment]
You should be able to make the mop wet with other means than the janitor's special mop bucket. Only makes sense.
