### ISSUE TITLE
MULE, you are broken - let me count the ways

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#35545]
1. Could not deliver to a further navbeacon (medbay) but could to janitor
2. Then janitor stopped working too, so it's clearly not a problem with the beacon
3. All MULEs, if on, will try to go to the laser pointer, causing collision issues
4. All MULEs seem to queue up laser pointer orders, so if you turn one off to avoid the above, next time you turn it on it will hurry to go to every place you've ever pinged before any package orders
5. They never stop flashing! Even if power is off or status is not moving, they stay flashing!
6. Pinpointing crates to pick them up doesn't work anymore
7. Auto unload didn't work when it arrived at flaps
8. Auto return didn't work either
9. Auto pickup crate isn't working - crates will instead interrupt pathfinding
10. Cell power never drains? Unsure since it was such a pain to get them to move at all, but even moving back and forth and leaving it online, the cell charge didn't seem to deplete. Nothing in mulebot code seems to reduce it.

**Comment by jwhitak** [comment]
#31944 did some massive damage. This will take a good while to fix. It likely needs a rewrite.
