### ISSUE TITLE
Kudzu + acid vines breach tray lid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35551]
(WEB REPORT BY: adacovsk REMOTE: 209.222.101.3:7777)
# Revision
396f60545760f86a458c7939d77e65a9d66c3d4b

# Description
I dumped some left4zed into a tray with a plant. I set up pipes and connectors, scrubbers, tray lids, etc. for the plants for containment.
# Steps to Reproduce
1. Kudzu + acid in the plants
2. Tray with lid on
3. Wait until floor is breached and hydroponics tray destroyed
# What you Expected
proper containment by the lid and not melt the hydroponics tray and destroy the entire station
# What Actually Happened
station destroyed

**Comment by SECBATON-GRIFFON** [comment]
feature
