### ISSUE TITLE
Europa Lights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35572]
(WEB REPORT BY: adacovsk REMOTE: 209.222.101.3:7777)
# Revision

# Description
Diona invincible
Grue instantly dead
racial spells.dm shouldn't exist

Should separate out kill_lights and flashlights into one PR to make it easier to review Europa lights
# Steps to Reproduce
Europa lights
# What you Expected
No problems
# What Actually Happened
Problems

**Comment by ShiftyRail** [comment]
All these are fixed on the latest version currently being PR'D.
