### ISSUE TITLE
NRV Horizon Atmospherics default configuration broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35580]
(WEB REPORT BY: superflybox REMOTE: 209.222.101.3:7777)
# Revision
c6bb199ffea47f86d5cdc6259d341fe3625167fc

# Description
The gas tanks on NRV Horizon have shared the ID tag name 'tox_sensor', which makes them not show up properly on the gas tank monitoring console.
The pipe meters for distro, waste, and air_out were not configured for the Distribution and Waste monitor, leaving the Distribution and Waste monitor completely unused by default.
# What you Expected
n2_sensor, o2_sensor, tox_sensor
frequency: 144.1, ID Tag: distro_loop or something
# What Actually Happened
tox_sensor, tox_sensor, tox_sensor
frequency: 0.0, ID Tag: _______

**Comment by DorainGrey** [comment]
The content of this bug and its name do not seem to match.

How is the default configuration broken?
It functions perfectly, not appearing on the almost entirely useless distribution and waste monitor does not mean atmospherics iis "Broken"
