### ISSUE TITLE
Paintings are broken again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35588]
(WEB REPORT BY: tinysaturn REMOTE: 209.222.101.3:7777)
# Revision
c06a646a936811bdc5da4ba98c03b1ef485eb607

# Description
Paintings printed from the database are 100% black until you update them via the save changes button

**Comment by DeityLink** [comment]
https://www.youtube.com/watch?v=3tyvvUas6G0
