### ISSUE TITLE
Hydroponic tray lids don't work

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3558]
Steps to reproduce:
1) Spawn exotic seeds until one exudes gas
2) Close the lid of a hydroponics tray and plant the seeds
3) AAAA
4) God please no
5) WHY
6) Just Awful
7)
![ss 2015-03-24 at 01 56 50](https://cloud.githubusercontent.com/assets/6526157/6796023/8b548992-d1c9-11e4-9354-d6e666945de9.png)
8)
![ss 2015-03-24 at 02 14 53](https://cloud.githubusercontent.com/assets/6526157/6796118/9282abf2-d1cb-11e4-8724-a682f2c3e654.jpg)
9) The tray's sensor suite is reporting a light level of 10 lumens and a temperature of 12781.2K.

**Comment by Zuhayr** [comment]
:+1:

**Comment by ComicIronic** [comment]
Did you wrench it to a connector?

**Comment by Probe1** [comment]
I never knew that was part of the process.  Since there's a distinct lack of connectors in hydroponics it makes me wonder if that's really how it should be.  

Wouldn't it be better to have the gas just pile up inside the tray and you had to get a connector to empty it?

**Comment by Midaychi** [comment]
Its supposed to trap it and allow you to equalize the gas with a connector port, but yeah I guess zuh coded it so the tray environment isolation thing wouldn't work unless it was connected to one.

**Comment by 9600bauds** [comment]
Upon wrenching the tray to a connector, the incessant plasma deathspew does indeed cease, however you can't actually do anything with the plant. It won't transfer it's gases to a canister or as far as I can see, do anything. You can't even use an atmospheric analyzer on the tray to tell what kind of gas it exudes.
The tray lid is heavily implied to be a closed environment, and given that you don't have any connectors in botany it really oughta be so. This thing needs a lot of work and a lot of love.

**Comment by Kurfursten** [comment]
@clusterfack fixed by #6044
