### ISSUE TITLE
invisible wire glass sheets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35592]
(WEB REPORT BY: irishmaniac REMOTE: 209.222.101.3:7777)
# Revision
c5edbfd7179288080f081e2b8ac2496b7e4455db

# Description
wired glass sheets are invisible, they appear on the sprite when holding them but otherwise cannot be seen. Also cannot be made into light tiles. However they can be applied to windows to make smart glass.
# Steps to Reproduce
Make wire glass tiles
# What you Expected
wired glass sheets
# What Actually Happened
invisible wire glass sheets

**Comment by DeityLink** [comment]
Fixed by #35598
