### ISSUE TITLE
Europa Lights: ghost gliding is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35601]
(WEB REPORT BY: shiftyrail REMOTE: 209.222.101.3:7777)
# Revision
3585e55479c58f67fa0552e3d29115db22e112e7

# Description

You lag behind/don't glide with your target if you, as a ghost, haunt another ghost.

**Comment by west3436** [comment]
Europa Lights are neither currently nor planned to be implemented.
