### ISSUE TITLE
Light Tile Colors Broken with New Lighting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35607]
(WEB REPORT BY: dovemite REMOTE: 209.222.101.3:7777)
# Revision
3585e55479c58f67fa0552e3d29115db22e112e7

# Description
Setting a light tile color with a multitool or a light tile remote(in an assembly in this case) does not color the actual lighting. It's just the standard light/white color
# Steps to Reproduce
Set light tile with multitool or remote
# What you Expected
Colored lighting
# What Actually Happened
Regular lighting

**Comment by ShiftyRail** [comment]
It actually works, you just need to remove it and update it again -- let me fix it now.
