### ISSUE TITLE
Light Lag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35602]
(WEB REPORT BY: cobraroast REMOTE: 209.222.101.3:7777)
# Revision
3585e55479c58f67fa0552e3d29115db22e112e7

# Description
The game runs like shit. The new lights fucked it!

# Steps to Reproduce
Walk by the bridge on Box Station or move around as a ghost.

# What you Expected
Coming home from the oil rig and expecting my computer being able to run a game that nearly predates the war on terror.

# What Actually Happened
Coming home from the oil rig and seeing my computer not being able to run a game that nearly predates the war on terror.

**Comment by ghost** [comment]
https://www.pcworld.com/article/2058969/trouble-running-starfield-todd-howard-says-upgrade-your-pc.html

**Comment by Cobraroast** [comment]
Shut the fuck up you dumb irrelevant grape holy shit I hate you, you are a waste of space

**Comment by jwhitak** [comment]
Rip shiftylights
