### ISSUE TITLE
Autoignited items can't be patted out or have their fire stopped

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35616]
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
b4aeae87e0d23cc92c0c45dfc8ecd54cdc424030

# Description
>use rcd next to a folder
>folder lights on fire
>no way to unlight it

**Comment by west3436** [comment]
Did you try a fire extinguisher??

**Comment by DeityLink** [comment]
Fire extinguishers can be surprisingly hard to find especially on maps other than box, especially considering they've been little more than flavor items for years.
