### ISSUE TITLE
Europa Lights - Noticable clipping effect when moving

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35615]
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
1345ab364e4732cd35f89ec929f2897343b79082

# Description
Often when moving on 1620, the lights will refresh 2 or more times, leading to a blinking/strobing effect when moving. This is disorientating and has even managed to jump scare me a few times. I'll upload a few examples after the round.

**Comment by west3436** [comment]
Europa Lights are neither currently nor planned to be implemented.
