### ISSUE TITLE
Horizon - No gold atmos suit conversion kit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35619]
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
b4aeae87e0d23cc92c0c45dfc8ecd54cdc424030

# Description
While not every map has everything, Horizon lacks the gold atmos suit conversion kit available on most maps.

**Comment by jwhitak** [comment]
Nevermind, close this issue. It's there.
