### ISSUE TITLE
You dip the cable restraints in...

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35620]
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
b4aeae87e0d23cc92c0c45dfc8ecd54cdc424030

# Description
>play round
>try to restrain someone
>Personname needs at least two wrists before you can cuff them together!
>You dip the cable restraints in Personname.

**Comment by west3436** [comment]
you WHAT

**Comment by Eneocho** [comment]
The question of the century is WHERE did he dip the thing.

**Comment by DeityLink** [comment]
Ohfuck that one's on me
