### ISSUE TITLE
europa emergency lights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35623]
(WEB REPORT BY: pomf123 REMOTE: 209.222.101.3:7777)
them lights don't pulsate they look like shit with undulating shadows.

**Comment by DeityLink** [comment]
they do pulsate but their color doesn't shift. And also it's really RED. Should be just ever so slightly more orange imo, or oscillate between orange and red.
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/b85dddca-6ae6-4496-bf0a-41c5dd776369)

**Comment by west3436** [comment]
Europa Lights are neither currently nor planned to be implemented again.
