### ISSUE TITLE
New Lights(?) + Vampire Vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35624]
(WEB REPORT BY: rubylips REMOTE: 209.222.101.3:7777)
Vampire vision, as in the upgrade that gives you full xray vision, causes very similar lag to what people describe when ghosting. 
I haven't been experiencing much of the ghost lag, but some. The vampire lag was extremely noticable though. I -think- it got worse after the shuttle was called too.

**Comment by ShiftyRail** [comment]
Mobs with XRAYS are getting affected the most by this. You can have a verb you can toggle but yeah, it's the same.

**Comment by jwhitak** [comment]
Rip shiftylights
