### ISSUE TITLE
Spell Icon Bug

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3562]
As an admin I used the player panel to give someone a genetics power (hulk). It changed my boo! spell icon into the hulk icon for some reason, and when I clicked on the spell icon I got the message "you shouldn't have this, something's wrong".

**Comment by SkowronX** [comment]
Same here, gave someone an eat power earlier and I got the hud icon for some reason?

**Comment by ComicIronic** [comment]
It's to do with how usr is being passed to the proc.
