### ISSUE TITLE
the the roid rat

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#35651]
![image](https://github.com/vgstation-coders/vgstation13/assets/67024428/cd49f9fd-a988-4bf8-b665-13f4c68b2d8c)
happens when you help intent a roid rat

**Comment by Dacendeth** [comment]
response_help  = "massages the"
	response_disarm = "stares jealously at the"
	response_harm   = "angrily kicks the"`
Seems intended.
