### ISSUE TITLE
overlays are fucked up hard, can't see shit

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#35660]
![image](https://github.com/vgstation-coders/vgstation13/assets/67024428/f3c01274-ccca-48c7-9c23-dd2324487874)
It got worse when a light flickered, or a new light appeared in my field of view.
![image](https://github.com/vgstation-coders/vgstation13/assets/67024428/4339c16d-7013-43d0-b316-13c09072a160)
It improved when I ghosted, and the issue disappeared for an instant after a bomb nuked the shuttle and destroyed all light sources. It then returned when I assume sparks lit a fire, which I couldn't see.
#### Difference between expected and actual behavior
Expected to see.
Got cursed by Nar'Sie herself.
#### Steps to reproduce
get cursed by the gods
[bugfix] @ShiftyRail

**Comment by ShiftyRail** [comment]
You seem to have HW acceleration off.

**Comment by Eneocho** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/67024428/6f98b387-a395-4914-a218-8a914bf96d35)
this? it's on

**Comment by ShiftyRail** [comment]
Are you on linux/a VM or something similar

**Comment by Eneocho** [comment]
nope, windows user, running byond stable

**Comment by ShiftyRail** [comment]
Well that's weird then. The image is a telltale signature of HW accel being off, since space is white and the lights overlays are just stacked on the bottom left instead of being saved as pre-rendered images.

Try to update your gpu's drivers, directX, and/or reinstall BYOND. This bug can only happen if your HW Accel isn't working properly.

**Comment by Eneocho** [comment]
I did play a few days ago and it worked fine and dandy, only today it is broken. I believe it is the HUD Datums PR that's causing issues. I'll try to reinstall byond to see what's going on, though.

**Comment by Eneocho** [comment]
I disabled HW accel, closed byond, opened byond and reenabled HW accel, it seems to be working properly now. Thought it might break again if I close the thing once more.

**Comment by Eneocho** [comment]
Restarted and it didn't break, seems to be fixed, Still unsure what caused it.

**Comment by Dacendeth** [comment]
You were probably playing another fullscreen game that fucked with byonds ability to render hardware acceleration properly.

**Comment by Eneocho** [comment]
nope, spess was the first game I opened today
