### ISSUE TITLE
Plated Food does not Steam

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35664]
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
37fe9d03a91ce7acd84acce4f8d82c74c0e3d7f8

# Description
If you put steaming hot food on a plate, it will stop being hot and steamy.

**Comment by DeityLink** [comment]
Works fine with me, it stops steaming at the same rate as it does without a plate, which is a few seconds.
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/cc4a242d-65f7-4fe2-a88d-da6a288d25de)

**Comment by DeityLink** [comment]
wait nevermind it DOES cool down a bit right when you put it on a plate
