### ISSUE TITLE
Gym/Roid Rats + Animal Recycler = Mustard Gas

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#35661]
This one is weird and complicated. There's multiple layers here.
In a post-Christmas drunken haze I read through the gym/roid rat and recycler code a few times last night and couldn't find why this would happen.

1.
Both gym and roid rats do not fit in the animal recycler. It has nothing to do with any of the upgrade features (tested this plenty) and no message is given. You drag + drop them and seemingly nothing happens. This is true for both alive and dead, and regardless of upgrade amounts. I haven't tried using grab.

2.
When you do attempt to do this from that point onward the rat will just sort of shut down. It won't attempt to move, it won't seek out treadmills like they normally do, nothing. It's similar to putting mobs in cryo. I actually got mind machined into one that had this happen to it and not only could I not attack anything, I didn't have the roid rat's punch spell and couldn't interact with the world in any way other than dragging/squeaking.

3.
When I tried putting a roid rat into the recycler via conveyor, it """""worked""""", the machine started rapidly getting loaded with roid rats.. because the one on the belt didn't actually enter it. When I tried to produce the cubes **the roid rats inside the cubes ate the cubes they were in, deleting themselves**, this is something normal mice do but there's two differences: Mice nibble, the roid rats ate themselves in one bite, and more importantly **this is new behavior for roid rats, they don't normally seek out food like mice do**. Even stranger is that after a certain amount of cubes produced, the conveyor stopped working to put the rat in the recycler. Normal mobs still worked on the same machine and same belt, and I even built a new recycler but it didn't work either. I have no idea what changed. 

4.
Some combination of events seems to have made this specific roid rat immortal. It would not die.
![Ohgodno](https://github.com/vgstation-coders/vgstation13/assets/64218965/373eed7f-889a-4d28-818f-fc461fab310e)

Please ignore the infinity lasers, still figuring that one out and it's a separate issue. 
This is the roid rat I had previously mind machined into. Meaning it was also broken by the animal recycler prior to that. At first I thought the recycler is what made it immortal but I tested it and it doesn't. The emitter beam here is also very high damage (2 prisms worth, so 5 emitters), I doubt it's the "bulkBlock()" proc somehow blocking burn damage instead of brute, especially since lasers killed a different one just fine. I watched this one long enough to be sure it wasn't just surviving a long time, it just wasn't going to die period. 

I just wanted a portable rat engine

**Comment by west3436** [comment]
@SECBATON-GRIFFON does #36207 fix this?

**Comment by SECBATON-GRIFFON** [comment]
no, because processors aren't animal recyclers
