### ISSUE TITLE
NRV Horizon has no dungeon zone + trade shuttle is goofy

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#35678]
[general] [bug]

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/16d6eab4-1b4d-438f-8bc4-dcf61b4a4259)

After some testing with Kurfursten, we found out why the Trade Probe wasn't spawning on Horizon: the Dungeon Zone didn't spawn on z2, leading things like sokoban, the probe, and some antag stuff to be broken.

Also also:

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/92eaa6de-8680-40f2-a13a-4ae61359062f)

**Comment by Kurfursten** [comment]
@DorainGrey just add dungeon to z2
