### ISSUE TITLE
The smoke smacks into the Supermatter Shard and rapidly flashes to ash.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35688]
(WEB REPORT BY: west3436 REMOTE: 209.222.101.3:7777)
# Revision
de4255ca088a93f11083d4c51fb7a9a9fc5a8326

# Description
The smoke smacks into the Supermatter Shard and rapidly flashes to ash.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by SECBATON-GRIFFON** [comment]
high impact engineering, feature
