### ISSUE TITLE
bad behavior with multiple choice polls

### ISSUE THREAD

**Issue by nervere** [d3athrow/vgstation13#35682]
Got this in chat when voting on the recent multiple choice art poll:
`Vote successful.x10`
`You already have more than 10 logged votes on this poll. Enough is enough. Contact the database admin if this is an error.x3`

![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/b82e309b-c20f-4c08-8d4d-39cf6426938f)

Basically, I voted for every single choice except the first one and #14 (because i misclicked, that one's pretty good). As you can see, the stuff I voted for is in bold... except for 12, 13, and 15, which seems to indicate that my votes for them did not go through.

Poll votes that exceed the maximum number of choices should not vote for the first X choices and discard the rest - it should reject the submission of the vote entirely.

**Comment by kilozombie** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/d17223a6-54a0-4502-b450-4207811c2dbb)
Not a bug

**Comment by nervere** [comment]
I misread this bit of code before I made the issue, my bad.
https://github.com/vgstation-coders/vgstation13/blob/0878bdd79d931314ed82dc0f3e6c9b2cc3279740/code/modules/admin/create_poll.dm#L61-L71

However, as Kilo pointed out to me, this is still bad since if you choose more than the allowed number of options, your vote should be rejected instead of voting for your first X choices. I'll remake this issue accordingly.
