### ISSUE TITLE
heating food on a plate with a scalpel duplicates it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35698]
(WEB REPORT BY: blinz2 REMOTE: 209.222.101.3:7777)
# Revision
8c8a19fd160fab6154b1b82292f40e8c61347ec6

# Description

when heating food on a plate with a laser scalpel i created a duplicate of the item
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
it's the age old duplicate thing when cutting plated food, you cut the "real" foodstuff out of the plate, instead of heating it

**Comment by west3436** [comment]
just need to add a check if the item is hot in attack_by and do that action instead

**Comment by SECBATON-GRIFFON** [comment]
but then how will i use my 1000 degree knives for video content
