### ISSUE TITLE
Swiss Army Knife Wrench not Working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35690]
(WEB REPORT BY: punishedpajeet REMOTE: 209.222.101.3:7777)
# Revision
de4255ca088a93f11083d4c51fb7a9a9fc5a8326

# Description
The wrench pops out, but does not do stuff. Have using on tables and a jukebox. Normal wrenches work

**Comment by Kurfursten** [comment]
Think this was caused by me adjusting the preattack() of wrenches in a recent PR, need to look into how switchtools work
