### ISSUE TITLE
swiss tool nerf?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35709]
(WEB REPORT BY: silent3 REMOTE: 209.222.101.3:7777)
# Revision
57073393c5024465b8cf2094b7cbd305e92a4f7d

# Description
swiss army wrench no longer works
# Steps to Reproduce
wrench a thing with the go go gadget swiss army knife
# What you Expected
you unwrenched thing!
# What Actually Happened
nothing

**Comment by Kurfursten** [comment]
Duplicate
