### ISSUE TITLE
"Valuable Asteroid" Mechanic Priority Item Works in Protolathe but not Recycler

### ISSUE THREAD

**Issue by GreatBigFailure** [d3athrow/vgstation13#35701]
The "valuable asteroid" item mechanics get for being a prioritized role doesn't actually recycle when tossed into the recycler. Don't know if it works in the protolathe.

**Comment by Kurfursten** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/9782036/bda69fc7-439d-47c0-94b3-4e3f241cfb1c)
Works fine in protolathe

It does NOT work in the recycler because it has w_type NOT_RECYCLABLE but could easily be made RECYK_METAL

**Comment by Kurfursten** [comment]
Apparently it's mechanic scannable too!

**Comment by GreatBigFailure** [comment]
> Apparently it's mechanic scannable too!

I swear I've tried that. It's basically my default response to things I've never seen, but it didn't work. I am guessing off vague memory though so I'm likely wrong
