### ISSUE TITLE
(WEB REPORT BY: failcakes REMOTE: 198.245.63.50:7777) You can't, Daniel K. Mann is closed.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3572]
>Revision 5576fac943996a7f72b51a252227bd4cb3b3191d 

>General description of the issue

Drank from a syndicate bomb, got a chat message that's re-listed in the title. Apparently it considers my internal reagent container to be a closed beaker.
>What you expected to happen
Drink ye booze.

>What actually happened
The dankman is closed for business.

>Steps to reproduce if possible

Drink ye booze.

**Comment by Probe1** [comment]
I just got the same message today when trying to put a glass on a table.  Weird.  I can't remember the exact circumstances.

**Comment by dylanstrategie** [comment]
Recent work on beakers and food. Please list any more occurrences, I'm going to glance over mob code

**Comment by d3athrow** [comment]
Fixed with https://github.com/d3athrow/vgstation13/commit/3644d8f62efbe4a77a702b38dfea0e7fe8f050ee
