### ISSUE TITLE
Food Smart Fridge rejects Pizza

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35748]
(WEB REPORT BY: dilt REMOTE: 209.222.101.3:7777)
# Revision
cee1c1fac9d9508df9eab072ed6e830c41c3a3cd

# Description
>Order pizza
>Try to put it in the chef's smart fridge
>It doesn't accept the pizza
>Cut the pizza
>The Foodstuff & Seeds Storage smartly refuses Margherita slice.

I just wanted to keep my food fresh bros...

**Comment by jwhitak** [comment]
The general chemical fridge accepts pizza, @Kurfursten, so this is likely a bug. Or the chemical smartfridge accepts unintended items, which would be a bug.

**Comment by Kurfursten** [comment]
It's hardcoded not to accept all food types intentionally - to try to just get ingredients + seeds
The normal chemical smartfridge just accepts all reagent containers, which contains all food
This was intended, but feel free to call it dumb

**Comment by MercuriusGH** [comment]
I think pizza is medicine
