### ISSUE TITLE
(WEB REPORT BY: tubbywatch REMOTE: 198.245.63.50:7777) Invisible gloves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3574]
>Revision

5576fac943996a7f72b51a252227bd4cb3b3191d 
>General description of the issue

When Captain's armor is equipped equipped gloves cannot be seen

>What you expected to happen

Gloves to be seen

>What actually happened

No gloves to be found

>Steps to reproduce if possible

Equip Captain's armor and gloves Order doesn't appear to matter

**Comment by ComicIronic** [comment]
Bad flags inherited from spacesuits, it seems.

**Comment by clusterfack** [comment]
When you put on bio suit it shows your bare feet
