### ISSUE TITLE
Swiss army knife wrench

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35747]
(WEB REPORT BY: irishmaniac REMOTE: 209.222.101.3:7777)
# Revision
d4cdbbfebced5a09c5bd83172b186e8114671da1

# Description
wrench does not work
# Steps to Reproduce
try to use wrench
# What you Expected
wrench
# What Actually Happened
wrench does nothing

**Comment by Kurfursten** [comment]
Duplicate
