### ISSUE TITLE
Shading after being deculted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35756]
(WEB REPORT BY: mastercasual REMOTE: 209.222.101.3:7777)
# Revision
cee1c1fac9d9508df9eab072ed6e830c41c3a3cd

# Description
Keep shade menu open after being deconverted shade and get melted
# Steps to Reproduce
see previous
# What you Expected
not to die I just wanted to close the menu
# What Actually Happened

**Comment by DeityLink** [comment]
I'll argue that you should have clicked "Stay in body" though
