### ISSUE TITLE
AME Lab becomes way more haunted if rotated

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35763]
(WEB REPORT BY: rubylips REMOTE: 209.222.101.3:7777)
# Description

The AME lab, when rotated, distorts oddly and stops being able to be interacted with properly. The visuals don't match the actual location of things, etc

**Comment by ValkyrieSkies** [comment]
Isn't that one supposed to not rotate?

**Comment by DeityLink** [comment]
Fixed by #35735
