### ISSUE TITLE
Painting Frames only Properly Fit Smallest Canvas

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#35762]
![image](https://github.com/vgstation-coders/vgstation13/assets/9782036/38393bc0-27b7-4526-8efe-418a848208f4)

Probably predate customs

**Comment by falcon2346** [comment]
This only applies to printed paintings. I seem to recall that when the painting archive was originally produced, printed paintings would originally display in the smallest possible size (and blank) until edited. Perhaps it's related to that?
