### ISSUE TITLE
Wrapping Machine "Set Output Location" Doesn't Work

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#35760]
@west3436 

It just stays under the machine, very inconvenient

**Comment by west3436** [comment]
~~Probably broken whenever kanef converted these into autoprocessors.~~ I'll take a look

**Comment by west3436** [comment]
Not sure if it was affected by the move to autoprocessors actually - the intended functionality is for this to be placed on a conveyor belt. That being said, the machine outputting the wrapped item onto the output tile makes more sense, so I will PR this shortly.

**Comment by Kurfursten** [comment]
Yes, being able to output to an output tile is very useful because it allows you to have a single wrapper machine in the mail room that you use to process crates ONTO the belt from the side, and it won't hold up trash
