### ISSUE TITLE
condiment packet overlays broke - they go blank, then properly update, then go blank again

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35779]
(WEB REPORT BY: sonixapache REMOTE: 209.222.101.3:7777)
# Revision
495358dc7a0365c8219087feb20ef986a2380352

# Description
>make condiment packet
>it's transparent
>then gets the right overlay
>then goes transparent again

i don't think anyone touched this so it's probably some kinda update_icon() / overlay fuckery?

**Comment by falcon2346** [comment]
This exact same problem was happening before with drinking glasses, I think it started right after the paint update.

**Comment by DeityLink** [comment]
I did touch the way update_overlay works for all food items with the thermal entropy update, and I've been fixing instances of this bug one at a time since.
