### ISSUE TITLE
Cyborg Recharging Station Robotifier doesn't check for adjacency at the end of the action bar

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35778]
(WEB REPORT BY: realestestate REMOTE: 209.222.101.3:7777)
# Revision
495358dc7a0365c8219087feb20ef986a2380352
the cyborg recharger machine that becomes an robotifier in the case of a rogue AI. yeah that one.

once you start stuffing someone in, if they stand up and start running away as long as you finish the stuffing time it will just teleport them inside regardless of how far away they were.

**Comment by kilozombie** [comment]
this is an IT'S LOOSE tier bug, oh god oh fuck
