### ISSUE TITLE
(WEB REPORT BY: awsmnamedude REMOTE: 198.245.63.50:7777) spiderbots unable to ventcrawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3578]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
when i try to vent crawl as a spiderbot it sais i cannot do so while holding items. i have no items held. 

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by clusterfack** [comment]
I cannot reproduce this. I think you mistakenly believed you were not holding something because spiderbots do not have an overlay for held objects.

**Comment by PJB3005** [comment]
might've been some sort of ghosted material stack (if that bug still happens, it's related to the autolathe eating your stack)

**Comment by DrCelt** [comment]
I've VVd people reporting this glitch and it appeared they were holding their own posibrain in their non existent hand. Unsure if still occurring.

**Comment by clusterfack** [comment]
I was about to fix this before my computer broke the acceptable held items needs to have posbrain and mmi added to the list for spider bots
