### ISSUE TITLE
you eat sundays with a fork instead of a spoon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35781]
(WEB REPORT BY: sonixapache REMOTE: 209.222.101.3:7777)
# Revision
495358dc7a0365c8219087feb20ef986a2380352

# Description
you eat it with a fork even though it's ice cream, what the hell
one line change, [first] and whatever

**Comment by Eneocho** [comment]
it's cold enough for chunks of sundae to be forkable
feature(TM(TM(TM)))
