### ISSUE TITLE
Horizon brig only has 1 pepperspray dispenser and it's in the secure armory

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35798]
(WEB REPORT BY: dakkanob REMOTE: 209.222.101.3:7777)
# Revision
52456e70d5a69f5d9f25b3ccd06ca9bb6108a969

# Description
fail
# Steps to Reproduce
map of horizon
# What you Expected
peeper spray in a few places in brig
# What Actually Happened
no

**Comment by DorainGrey** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/102815299/56b3c317-2af3-4bac-9488-7745c4fc00e8)
There is one down on the wall by perma.
