### ISSUE TITLE
Chemmaster bottles can't be directly picked up by pill collectors/plastic bags

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3580]
Chemmaster bottles do indeed fit inside pill collectors and plastic bags. However you can't actually click the bottle to load it, like you can do with pills (and pretty much any other small item in the case of the plastic bag)
What you can do, however. is place a pill in the same tile as the bottles and click it with the pill collector. It will ~indirectly~ swallow all the bottles, and you can later get rid of the pill.

**Comment by dylanstrategie** [comment]
Might be caused by a too restrictive typecheck
