### ISSUE TITLE
chairs are kinda fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35810]
(WEB REPORT BY: eneocho REMOTE: 209.222.101.3:7777)
# Revision
8b7f7df63522f2c4dd3cb3f103522d0b474eb6f9

# Description
Sat on the cargo chair, did my stuff, once it was over, I clicked the buckled UI element and got a "[spessman name] struggles in vain trying to pull themselves off the chair." message, and it turns out I was never buckled to the chair. 
What the fuck
# Steps to Reproduce
do what I just described
# What you Expected
to be buckled to the chair
# What Actually Happened
space chair is haunted

**Comment by Eneocho** [comment]
The 4 chairs I sat on were the chair by cargo lobby (This was in NRV Horizon), and the 3 chairs by the computer in the shuttle.
I literally walked out of the office and sat on the chair, made a bunch of cargo requests then, when trying to leave, it said that line, and I could move fine, as if I had never been buckled to the chair.
The "Buckled" UI Element never disappeared, it just changed to whichever chair I last used.

**Comment by ErrorsWindows** [comment]
were you glued to the chair

**Comment by Eneocho** [comment]
No, and I could move as normal. It happened with all 4 chairs I used. I doubt someone somehow managed to glue the cargo lobby chair in the 2s it took me to leave the QM office after spawning. (I was the only cargo worker that shift besides a kinda late join bird miner).
