### ISSUE TITLE
Unconscious overlay borked

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3583]
It seemed that, after a while of being unconscious in surgery, the layer that covers the screen would just disappear. I was still unconscious and still had the "You think you can hear someone talking" message.
It may have something to do with being shaken while unconscious, but I don't know.

**Comment by SkowronX** [comment]
Did you do use the sleep verb rather than use anesthetic?

**Comment by Ephx1** [comment]
Now that I recall, yes, but halfway through the first operation I woke up with anesthetic on, and went back to sleep.
Then the overlay disappeared again.

**Comment by d3athrow** [comment]
Did you have the farsight power?

**Comment by Ephx1** [comment]
Only power I had at the time was Project Mind (thx 4 fix) as I was a Grey.

**Comment by 9600bauds** [comment]
Had this happen to me as well, at the time I used *faint to go to sleep and presumably the anesthetic took effect while I was already sleeping.

**Comment by Shadowmech88** [comment]
I've also had this happen.
It's inconvenient because there's no longer any indication that you're unconscious, until you attempt to do something and find out that you cannot.

**Comment by gbasood** [comment]
Should no longer be an issue with overlay_fullscreen
