### ISSUE TITLE
Box Barber airlock titled "art storage"

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#35835]
#### Description of issue
The lightswitch is in the bottom right corner, and there being a vendor on the right side, you cannot use the lightswitch. You gotta disassemble or flip the table to use the lightswitch.
Also the door still says art storage.
(On that note I dislike where new art storage is, I liked my library double airlocked and comfy, now it feels somehow sterile).

#### Difference between expected and actual behavior
Expected the airlock to say Hair Salon or something, and for the switch to be usable.
Got a misnamed airlock and a switch that requires a wrench to reach.
#### Steps to reproduce
Just walk into boxstation.

**Comment by Dacendeth** [comment]
> you cannot use the lightswitch. You gotta disassemble or flip the table to use the lightswitch.


https://github.com/vgstation-coders/vgstation13/assets/26881007/232048b5-88cf-4df4-9dfe-ba606887d838

**Comment by Eneocho** [comment]
on the round I played that prompted me to make this issue the button was not reachable at all, i had to disassemble the table to reach it.

**Comment by Kurfursten** [comment]
Dac is right, there's nothing that blocks the lightswitch at roundstart. However, you are completely right about the door, and I will fix it.
