### ISSUE TITLE
Feature Request: Pimp out your Hardsuits

### ISSUE THREAD

**Issue by RealestEstate** [d3athrow/vgstation13#35838]
Requesting a better way to paint hardsuits that isn't just slapping a color matrix over the whole thing but rather recoloring it piece by piece. I have done the legwork dividing the engineering hardsuit sprites into what I think are the key zones for recoloring:
- The visors and sensors
- Primary Shell
- Inner Shell

I don't know how to code this myself hence this feature request.
if it shows promise then I'm fully on board with doing the sprite separation for the other hardsuits.

I think the mechpainter could be a good candidate for painting hardsuits (and could possibly rename it to exoshell-painter or something).

[spriteworkdone]
[featurerequest]

![image](https://github.com/vgstation-coders/vgstation13/assets/25192877/1d2a59b9-9824-460c-b637-455980136246)

Link to the above DMI:
https://cdn.discordapp.com/attachments/1084300577862856857/1198854429944860742/engi-OVerlays.dmi?ex=65c06b31&is=65adf631&hm=ba45d050f7671b20c5fe1a324e4a20179cde8c6c70392924d462b39a6bf9c1d0&

**Comment by Eneocho** [comment]
Cool shit. If there's a way to add a sheet of material to plate it in that colour it'd be awesome. Pimp your suit with literal gold and diamonds.

**Comment by DeityLink** [comment]
Ok you gotta make the secondary layers much, _much_ whiter. Think of each layer as if it was covered in white paint.

This is how it looks like with red paint primary and white paint secondary: 
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/5883a21e-e79e-4893-8717-647564c1fd15)
