### ISSUE TITLE
Library QoL List

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#35832]
- [x] And queue up library printing instead of one at a time clicking
- [x] icon and sfx for book printing
- [x] Bookbag can't be used on bookcase to quickload it
- [x] Bookbag can also not hold nanodicts
- [x] Bookbag can't hold Bibles (complicated because they are same-size storage items)
- [x] Need a way to make a new barcode scanner if the old one is destroyed or lost
- [x] Ace reporter dynamic paper should update icon after roundstart to make it not appear blank
- [x] scanner should have a desc
- [x] fix leaks in the barcode scanner and checkout computer
- [x] fix a bug where the library computer cannot be used on the shuttle 
- [x] Reporter gear locker should just be turned into a proper job locker so it's standard across all, and possibly use smartboxes for outfits because there are a lot
- [x] Also it would be nice if you could set up a template for your favorite books at the library  - SS13BN should be DISPLAYED on the list so that it can be used for this!

**Comment by NigglyWiggly** [comment]
I’ll be honest I don’t think I’ve ever seen anyone actually scanning books or properly checking them out. There’s no reason to ever manage where they are or who has them because you can just immediately print a replacement copy
It’s like the various cash registers around the maps, a relic from the before times

**Comment by Kurfursten** [comment]
Yeah, I've never seen it used. I'm thinking of simplifying it to simple automatic check-in check-out but if you have a better idea of what purpose it could serve, I'm open to it.

**Comment by NigglyWiggly** [comment]
I don’t know if it’d even be possible, but it would be sort of neat if you could scan every book you print, and have it recorded in the computer, and then if one of them is removed from the library area, it could show that on the computer, just to keep track of what’s still in stock.

**Comment by Kurfursten** [comment]
Yeah, it would be trivial to display a status for each book, though it's hard to imagine someone taking a book without the librarian coaxing them

**Comment by NigglyWiggly** [comment]
_Back in the day_ people would do that all the time
Usually they’d actually come and ask for a specific book or something, but a lot of people would just take a book and try to slip out without mentioning it, probably because it was pornography
