### ISSUE TITLE
(WEB REPORT BY: aurx REMOTE: 198.245.63.50:7777) Pills do NOT cancel forcefeed for any reason

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3584]
>Revision (Should be above if you're viewing this from ingame!)
3d0c132ab922e8db71efb885532ce1cca6a87613

>General description of the issue
Forcefeeding a pill cannot be interrupted.  Also gives the pill -> beaker message.  

>What you expected to happen
Not to shove a pill down somebody's throat from ten meters away while dead.  

>What actually happened
Shoved a pill down somebody's throat from ten meters away.  While dead.  

>Steps to reproduce if possible
Apply pill to target, note that anything they do to prevent it short of gibbing you does not work.

**Comment by Aurx** [comment]
ALSO BREAKS LOGGING

**Comment by Aurx** [comment]
Appears to be caused by humans being open containers, and pill's afterattack() triggering.
