### ISSUE TITLE
I was nullspaced in a pocket airbag

### ISSUE THREAD

**Issue by ErrorsWindows** [d3athrow/vgstation13#35846]
#### Description of issue
I was in a pocket airbag getting pushed away by a fire I set in the bar when after a couple seconds I got nullspaced

#### Difference between expected and actual behavior

generally i expect to stay in the airbag until i'm done, maybe the fire ignited the airbag? maybe somebody pulled my airbag to pull me out? idk

#### Steps to reproduce
trigger a pocket airbag
get sucked away
wait multiple seconds, even after the initial zas stun wears off
then die

#### Specific information for locating
pocket airbag, fire

#### Length of time in which bug has been known to occur
since i set the bar on fire at 3:25 pm PDT jan 16 2024

#### Server revision
Game: 5bc9468b6cf516cda77c4aa9359a87ded9bbf954 
Patches: 5eccbc7929ffb81f3058d3993f5f27c814dafb72 
Current Infomational Settings: 
BYOND version of server: 515.1620
Protect Authority Roles From Tratior: 1

**Comment by ErrorsWindows** [comment]
also it wouldn't let me make a bug report with the ingame function on the top bar

**Comment by RealestEstate** [comment]
My guess is on the airbag getting melted

**Comment by ErrorsWindows** [comment]
the thing is that it seemed so instant

**Comment by Dacendeth** [comment]
I could not get an airbag to melt in a plasmafire but on admin deleting the airbag all contents inside of it were deleted instead of dropped on the turf.
