### ISSUE TITLE
Feverfew is a death sentence 

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#35862]
#### Description of issue
Feverfew chemical  lasts so long and does so much brute damage over time, even breaking bones and giving IB, I don't think this should be like that.

#### Difference between expected and actual behavior
A cactus prick to not be lethal unless treated
I almost died if not for interventions.

#### Steps to reproduce
Walk into the cacti that inject feverfew and slowly die without treatment

**Comment by Kurfursten** [comment]
Treat with charcoal to remove, skill issue
I myself dealt with an annoying hallway cactus bussed by someone and fixed 3 people with simple charcoal

It's also feverfew

**Comment by Dacendeth** [comment]
I just think walking over a cactus giving you 300 ticks of damage over 10 minutes is a bit silly, assuming you only walk over it once and feels wrong based on the comment near the code of it
`L.reagents.add_reagent(FEVERFEW,3) //This will take 15 ticks to clear, doing about 22 brute (but brute regens easily)`

**Comment by Kurfursten** [comment]
Probably unintentionally inherits metabolism rate from other virus-curatives

**Comment by SacredAtom** [comment]
He was a plasmaman so they might have something to do with it
