### ISSUE TITLE
A donut hoard started burning at 5000°C

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#35874]
#### Description of issue
Sec had been given a hoard of about 150-200 donuts that they had all spread around in sec lobby, and a couple pies. Apparently a seccie shot a flare round in sec lobby, which ignited the pies(?), which then heated the room. This autoignited the donuts, and they started burning incredibly hard, quickly killing a seccie.
It was then reported that the donut fire burnt at 5000°C, and several people noted that plasma has been outclassed by the mighty donut, one even suggesting that perhaps a donutfire engine would be pertinent.
#### Difference between expected and actual behavior
Expected ignited food to burn at a reasonable temperature.
Got 50 degrees of security bacon.
#### Steps to reproduce
Hoard 200 donuts in sec lobby.
Start a fire, such that the donuts self ignite.
Observe the 5000°C.
#### Specific information for locating
[17:38:09]SAY: -----/(Pink Sherman) has made a Comms Console announcement: i feel it is pertinent to this situation to inform you all the donut fire in the security lobby is 5285.63°C
[17:37:22]SAY: -----/(Pox) has made an announcement from Head of Security RC: SEND THE FIRE DEPARTMENT! The donuts in the brig lobby self igniteed and burned Willy to death! HELP!
[17:35:56]ADMIN: HELP: -----/(Pox): WHY DO DONUTS BURN AT 1000000000° - heard by 0 non-AFK admins.

@west3436 here you go

**Comment by west3436** [comment]
Lmao you made this sound like a single box of donuts set the room on fire. A stack of 200 donuts is probably going to generate a lot of heat even if burnt in a small room irl. I don't see this as an issue unless you propose how the feature should be changed to deal with this.

**Comment by Eneocho** [comment]
I did say "a hoard of donuts" on your PR, never implying it was a single box. Lemme download the latest and test just how many donuts you need for a 50 degrees of station bacon fire.

**Comment by Theophrastus1** [comment]
i think it was my cigarette that started the fire

**Comment by DeityLink** [comment]
imo a pile of burnable items should reach thermal equilibrium much sooner and not reach the temperature of the sun. The way heat is generated from burning items should be reworked and not depend only on the air mixture.

**Comment by DorainGrey** [comment]
Note, this was probably the hardest non plasma fire I've fought in space.
Even when it was extinguished by spacing the room, as soon as the air starting rushing back into the room the heat of the remaining 4 donuts & all the burning mess reignited it 3 times.

The only way I could put it out, was lockering all the burnt mess, then spacing room. 

I think all food is probably impacted by it, sec lobby on roid is rather big so it's shocking a 100 food can turn it into the temp of the sun.

**Comment by DeityLink** [comment]
It's a vicious cycle, items burn at autoignition temperature, driving the temperature even higher, Solution would be to vacuum the room, use foam extinguisher to cool what air remains in the room, then inject some cool air.

Space stations being a closed systems also means that temperature can rise much higher that we're used to in real life.

**Comment by Eneocho** [comment]
I tested it with only 1 donutbox's worth of donuts, the same room (sec lobby on box) heated up to 865°C
