### ISSUE TITLE
AI Holopad Sprite Layering Error

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3587]
![holopad](https://cloud.githubusercontent.com/assets/3991927/6847894/cf972ec8-d397-11e4-87e4-110aee9fdc4e.PNG)

Someone wrenched an autodrobe down over a holopad, and this happened. I don't know if this is an issue with autodrobes or with holopads, but it's an issue.

**Comment by d3athrow** [comment]
That layering is intended so people can't prevent an AI or player from using the holopad. Not pretty but essential for gameplay.
