### ISSUE TITLE
Obese Sprites for Jumpsuits Broken

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3588]
![big momma2](https://cloud.githubusercontent.com/assets/3991927/6848103/47518386-d399-11e4-8bb9-70079967f2e5.png)

An admin told me that standard jumpsuits have special sprites for obese characters, but on my character the jumpsuit retained the regular sprite, leading to the character's bare belly protruding from the jumpsuit whenever I turned to the side.

**Comment by d3athrow** [comment]
weird.

**Comment by clusterfack** [comment]
I just cant find the specific commits, but could have been a result of the changes to prevent skeleton fat icon problems?
