### ISSUE TITLE
Food delivery bags from merch can't hold sauce packs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35889]
(WEB REPORT BY: yclat REMOTE: 172.93.101.77:7777)
# Revision
46ed236038a88475a77941e82033654d703b4078

# Description
Go to a McMerch:tm: computer, buy food on lowpop, try and keep shit clean by stuffing the garbage back on the bag, somehow the thing can hold a big burger, fries soda and cutlery but not the sauce packets back which it came with.
# Steps to Reproduce
Buy McMerch:tm: and take out sauces and try to put em back in after you used them, won't let you
# What you Expected
Enviorementally clean slop consumption
# What Actually Happened
I threw all my shit on the floor because the box won't keep the trash. Clean it up Janny.

**Comment by SECBATON-GRIFFON** [comment]
it's because they turn into objects of type /obj/item/trash when used
