### ISSUE TITLE
Some Boomerang Throws cause you to IMMEDIATELY catch boomerang before it leaves your tile

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#35907]
At first I thought the boomerang was completely broken - I need to test this more to find the angles

EDIT: Seems to be only(?) from throwing directly up

**Comment by Eneocho** [comment]
There was a screenshot where a guy stood on the center of the chess board holodeck and tested all boomerang angles to see if they worked or not, but I can't find it.

**Comment by DeityLink** [comment]
Boomerang got reworked.
Fixed by #36993
