### ISSUE TITLE
wearing mesons(while turned off) no longer prevents shart hallucinations

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35908]
(WEB REPORT BY: janez420ivan REMOTE: 172.93.101.77:7777)
# Revision
8d579d2c0867517e4f896f9da79ccde62e713cec
caused by #35633

https://github.com/vgstation-coders/vgstation13/blob/8d579d2c0867517e4f896f9da79ccde62e713cec/code/modules/supermatter/supermatter.dm#L347

**Comment by west3436** [comment]
Feature - wearing a welding mask doesn't prevent eye damage unless you pull it down.

**Comment by DorainGrey** [comment]
What how is this a feature?
It was this way since the introduction of mesons, mesons always cover your eyes.

This was an accidental change, with the vision datums and something I've been meaning to bug fix.
