### ISSUE TITLE
Human Missle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35918]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
8d579d2c0867517e4f896f9da79ccde62e713cec

# Description
I shot a nikita missle using the nikita. All my clothes fell off in a pile where I shot it and I got attached to the missile.
# Steps to Reproduce
shoot the nikita
# What you Expected
not be attached to the missle and kill myself
# What Actually Happened
I killed myself because I was attached to the missile

**Comment by west3436** [comment]
Emagging a Nikita will make you ride the missile naked (with cowboy boots and a hat)
