### ISSUE TITLE
Lit Cigarettes light fires, but can't be put out with fire extinguishers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35917]
(WEB REPORT BY: primed REMOTE: 172.93.101.77:7777)
# Revision
8d579d2c0867517e4f896f9da79ccde62e713cec

# Description
if someone dumps a bunch of lit cigarettes on the ground there's no way to put them out even if they're starting fires

**Comment by DeityLink** [comment]
simply extinguishing cigarettes, candles, or matches on clean_act() would do the trick, since water from fire extinguishers calls clean_act(1)
