### ISSUE TITLE
Cap smoke clouds per area

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35928]
(WEB REPORT BY: west3436 REMOTE: 172.93.101.77:7777)
# Revision
aaabf3ce60ee66469fc41131549354472233c93c

# Description
need to add a limit to the number of smoke effects that spawn in any given area because lag

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
Can confirm they can be massively laggy.
I had made a candy engine that burned mints for heat. The amount of smoke they made gave you very strong lag, to the point of taking a full second between any action input and the action happening.
Though, to be fair, my engine burnt well over 1000 candy simultaneously, so that's something to be considered.

**Comment by west3436** [comment]
> Can confirm they can be massively laggy. I had made a candy engine that burned mints for heat. The amount of smoke they made gave you very strong lag, to the point of taking a full second between any action input and the action happening. Though, to be fair, my engine burnt well over 1000 candy simultaneously, so that's something to be considered.

Yeah when you deliberately do shit like this knowing it's buggy don't act surprised when it results in bugs

![Bike-Fall](https://github.com/vgstation-coders/vgstation13/assets/66280799/dd3fc1e0-6b5d-4083-acb0-6caa9bea3848)

**Comment by Eneocho** [comment]
It wasn't deliberate lagging. I was genuinely trying to make a TEG powered by candy, so I just dumped a fuckton of candy and lit it up. Didn't expect so much smoke and lag, though.

**Comment by hacker-on-steroids** [comment]
solution? don't make smoke when temperature or the oxygen partial pressure get high enough
cuuurently, a room that gets welderbombed will have stuff burn despite being open to space(real fires don't usually burn in vacuum) so the partial pressure needs to get implemented anyway

**Comment by west3436** [comment]
> solution? don't make smoke when temperature or the oxygen partial pressure get high enough cuuurently, a room that gets welderbombed will have stuff burn despite being open to space(real fires don't usually burn in vacuum) so the partial pressure needs to get implemented anyway

Good idea Hina, I'll also include that in the PR

**Comment by hacker-on-steroids** [comment]
>quoted my typo before i could proofread

it's fucking over

**Comment by DeityLink** [comment]
shouldn't they just not overlap on a single turf? or is that what you meant @west3436 ? because capping per area would lead to very strange results.

**Comment by Eneocho** [comment]
They should overlap but only to a degree (maybe 5 smoke puffs per turf max?), so heavy smoke takes longer to dissipate, and hotter fires should make less smoke, so it self-regulates that way. Plasmafire induced fire on a room filled with stuff? Makes very little smoke since the burn is so hot. Welderfuel fire? Smoke for days.

**Comment by west3436** [comment]
> shouldn't they just not overlap on a single turf? or is that what you meant @west3436 ? because capping per area would lead to very strange results.

I seem to recall all effects absorb each other if they're on the same tile already, but that could be an option to help with performance.


> They should overlap but only to a degree (maybe 5 smoke puffs per turf max?), so heavy smoke takes longer to dissipate, and hotter fires should make less smoke, so it self-regulates that way. Plasmafire induced fire on a room filled with stuff? Makes very little smoke since the burn is so hot. Welderfuel fire? Smoke for days.

I don't want to overcomplicate it for the sake of realism. If anything I am just going to disable smoke if either the oxygen % or the mols of oxygen in a room are too low and put an upper limit on the number of smoke effects present in a given area.
