### ISSUE TITLE
Feature request, inspecting something on fire should tell you the shortcut to put it out.

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#35923]
#### Description of issue
Right now in order to put something that is on fire out you have to either know by someone telling you beforehand or reading it on the wiki, I think a more in game way to learn this is appropriate.

#### Request

Add an inspect description to items that only appears when an item is currently on fire that tells the player the hotkey they need to perform to put it out.

**Comment by jwhitak** [comment]
In addition this should also be done to reagent containers that are suitably hot.

**Comment by Inorien** [comment]
is everyone still going to need the extra text in a couple of months?

do we not have a quick hotkey reference in-game

**Comment by west3436** [comment]
Actually going to close this one as we don't display shortcuts anywhere else in game so this is inconsistent. The wiki has been updated with this shortcut.
