### ISSUE TITLE
Constructed lightswitches

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35924]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
aaabf3ce60ee66469fc41131549354472233c93c

# Description
I constructed a lightswitch inside a new area that I built with a construction permit, and it doesn't work.
# Steps to Reproduce
Build an area in space, build lights, and build a lightswitch
# What you Expected
lightswitch green or red and able to power lights on
# What Actually Happened
lightswitch dead and lights off

**Comment by Dacendeth** [comment]
There is no bug here he just fucked up, the lightswitch works when you do everything right.

**Comment by ConfusedCactus** [comment]
I've done this multiple times and it works fine, he just messed up somewhere. Maybe he forgot to wire it or something, or he forgot you need the area to actually have an APC.

**Comment by Dacendeth** [comment]
Yes he forgot to turn the breaker on after constructing his apc.
