### ISSUE TITLE
Cable ties icon stuck after refusing cult conversion and being released

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#35934]
#### Description of issue

If you get cable cuffed, then refuse cult conversion and get the cult cuffs applied, when the cult cuffs are removed by a cultist then the cable tie icon remains on the UI and is examinable etc. but does not hinder usage of hands. They can't be dropped or thrown and other picked up items appear over that icon. The cable ties item doesn't appear on examining the mob

#### Difference between expected and actual behavior

Shouldn't be any weird invalid cuffs being stuck on the UI

#### Steps to reproduce

> Get cable tied
> Refuse cult conversion
> Cultist removes the cult manacles
> You should now have cable ties stuck on your hands in the UI but your hands wont actually be tied

[oversight]

**Comment by Theophrastus1** [comment]
I do not know if this is of any help for this, but I also had a bunch of UI errors after the cult cuffs were removed from me. Was seeing stuff in the immediate area in my hands slot but my hands were empty.

**Comment by DeityLink** [comment]
@Theophrastus1 if you've got a screenshot of it that'd help a lot. did you pick up those items at any point before/after getting cult cuffed?
