### ISSUE TITLE
You can see the loyalty implant even if someone is wearing a tinfoil hat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35932]
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
09927af122d13c7f6af8f1dc646652a97bb96b28

# Description
Tinfoil hat used to hide this I'm pretty sure

# What you Expected

# What Actually Happened

**Comment by hacker-on-steroids** [comment]
it shows the wanted status too
by the look of it only the job icon gets hidden by the foil
