### ISSUE TITLE
Cannot set arrest status as PAI

### ISSUE THREAD

**Issue by FoggyDayWindyCay** [d3athrow/vgstation13#35945]
When playing a pai with security package installed, cannot set the arrest status of someone. The ' [none] ' field is unclickable. Everything else like viewing security comments or changing medical status works, however.

**Comment by Eneocho** [comment]
i think you can but only if you use the chat buttons on examine

**Comment by jwhitak** [comment]
This is a bug that I accidently introduced later on after testing new HUDs with the pAIs. It'll be fixed with the HUD general fixes I'm making soon.
