### ISSUE TITLE
Curb Your Enthusiasm credits music isn't working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35954]
(WEB REPORT BY: angryturnip REMOTE: 172.93.101.77:7777)
# Revision
b8c32cd8e8c9e33dbaac7635d7d278c693dba520

# Description
don't know when it stopped working but I've noticed it hasn't worked once since a few days ago
# Steps to Reproduce
watch the credits
# What you Expected
music
# What Actually Happened
silence

**Comment by ghost** [comment]
same.

**Comment by west3436** [comment]
Fixed by pomf
