### ISSUE TITLE
Headset Earmuffs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35952]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
b8c32cd8e8c9e33dbaac7635d7d278c693dba520

# Description
1. Hold primed flashbang with headset earmuffs on
2. "Your ears start to ring!"
# Steps to Reproduce
1. Hold primed flashbang with headset earmuffs on
2. "Your ears start to ring!"
# What you Expected
My ears not ringing
# What Actually Happened
Your ears start to ring!

**Comment by Kurfursten** [comment]
Earmuffs and headset earmuffs only provide 1 level of ear safety, not a bug
