### ISSUE TITLE
TOXIN FILTERS DON'T WORK

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35955]
(WEB REPORT BY: pulserider REMOTE: 172.93.101.77:7777)
# Revision
b8c32cd8e8c9e33dbaac7635d7d278c693dba520

# Description
i put in a toxin filter and the patient still takes toxin damage
# Steps to Reproduce
get a toxin filter
remove the kidneys
place the toxin filter in

# What you Expected
no toxin damage
# What Actually Happened
slowly increasing toxin damage, like he has no kidney

**Comment by Dacendeth** [comment]
There is no bug here.

Not having kidneys fills you with the toxin reagent, after kidney replacement you need to flush them with charcoal or give them antitoxin during the transfer process.

**Comment by jwhitak** [comment]
Confirmed not a bug.
