### ISSUE TITLE
Extinguisher cabinets refill extinguishers

### ISSUE THREAD

**Issue by west3436** [d3athrow/vgstation13#35953]
#### Description of issue
Requested by many - this will help with fighting fires

**Comment by Eneocho** [comment]
Would absolutely neuter the classic "filling the extinguishers with fuel then starting a fire" trick.

**Comment by Dacendeth** [comment]
Cabinets should just start with a container of water that it pulls from to refill extinguishers, and allow you to empty it and refill it with another chemical to keep that then.
