### ISSUE TITLE
Borg icon previews

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#3595]
With increasing amount of borg skins, it would be a lot easier and visually more appealing if the icon selection had previews next to the selection. Will make a mockup later.

**Comment by dylanstrategie** [comment]
The problem is that we can't realistically do this with a normal menu

In that case, the most attractive option would be a HUD gizmo to preview the skins, in which case we could use the same code we use to show and equip modules

**Comment by SkowronX** [comment]
With the new hud system, I believe it's a very possible yes.

**Comment by ComicIronic** [comment]
>can't realistically do this with a normal menu

I don't see why not.
Plenty of game menus are capable of using simple embedded images from dmi files. The RPD does it, for example.

**Comment by gbasood** [comment]
Wait, why can't we just do an HTML window when a borg picks its module with all the skins available to it?

**Comment by PJB3005** [comment]
Won't be able to do perfect responsiveness due to BYOND.

**Comment by gbasood** [comment]
So?
