### ISSUE TITLE
Combined health and security HUD is a mess

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35968]
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
7ad14ac207cae7c63679d3a7e280b2cd2fa44430

# Description
Job AR element keeps constantly switching between random jobs at random intervals
(lol)

**Comment by jwhitak** [comment]
Could I get any more details on this? Is the icon mess up happening to multiple people's jobs? Just your own job?

**Comment by jwhitak** [comment]
Got images on discord. Issue is that jobs from other nearby people appear on top of your own person instead of them. Already see the fix.
