### ISSUE TITLE
HUD update broke Metabuddy UI element

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35970]
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
7ad14ac207cae7c63679d3a7e280b2cd2fa44430

# Description
Metabuddy no longer gives people the metabuddy UI element when you drink it making the drink completely pointless
thanks dilt

**Comment by jwhitak** [comment]
Caught it in the blanket HUD/image subtype bug fix by mistake. The metabuddy hud element is meant to be permanent. Will fix when I get off of work in uhhhh 12 hours.......

**Comment by Eneocho** [comment]
10 hours remain
