### ISSUE TITLE
Multitools need plastic to print???

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35972]
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
4efe527154944ccadb51dee5ab72ca30c76b2c3e

# Description
Someone definitely sneaky coded this in

# What Actually Happened

**Comment by Eneocho** [comment]
If you were printing via mechanics, all mechanic prints (via the mechanic machines) have plastic added to the cost, regardless of source.
https://github.com/vgstation-coders/vgstation13/blob/4efe527154944ccadb51dee5ab72ca30c76b2c3e/code/game/objects/items/devices/multitool.dm#L23
This is the actual cost of a multitool

**Comment by MercuriusGH** [comment]
This was in an Autolathe

**Comment by Eneocho** [comment]
According to the coderchat on the d*scord, apparently it's an issue of the child (autolathe) receiving the "updated" cost (with plastic) from the parent (mechfab).

**Comment by hacker-on-steroids** [comment]
happens to compressed matter carts too

**Comment by RealestEstate** [comment]
I have seen this happen to assembly parts as well
