### ISSUE TITLE
Cryo Level 3 Upgrade Should Do Something

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3597]
As it stands right now, apparently upgrading the cryo tubes with level 3 R&D parts doesn't improve their functioning at all. I think it should somehow drain the beakers more slowly (without slowing down the delivery of the contents to the patient.)

The upgrade should at least improve the cryo tubes in some way.

**Comment by dylanstrategie** [comment]
I could most likely do the same thing as I did with cloning and nerf default functionality to very slow recovery, then make upgrades turn it into a much better way of healing people than just actually walking up to them and treating them

**Comment by 9600bauds** [comment]
Problem with this is that Cryo's healing is almost entirely due to Cryox+Clonex acting on themselves, so you can't really change the healing rate.

**Comment by ComicIronic** [comment]
Some suggestions from the thread included:
 - Adding a toggleable full health alarm
 - Decreasing internal ejection time
 - Synthesizing chems over time - with a toggle

**Comment by Shadowmech88** [comment]
>Adding a toggleable full health alarm

It could function the same way that medibots alerting doctors of critical patients already does.

**Comment by Shadowmech88** [comment]
Possibly no longer applicable.
