### ISSUE TITLE
vamp hud don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35973]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
4efe527154944ccadb51dee5ab72ca30c76b2c3e

# Description
jwhitak broke it
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Dacendeth** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/26881007/261e2184-f04c-4c06-9ee5-93b7026fd44a)
seems to work to me?

**Comment by west3436** [comment]
@adacovsk more info, please

**Comment by jwhitak** [comment]
Can't reproduce, and our best guy had at it. Vision modifiers at blood levels work, thrall vision works, null rod vision works... Please fully fill out the bug reports so that we have enough information to know what you even mean by this.
