### ISSUE TITLE
Fire is too fucking hot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35978]
(WEB REPORT BY: irishmaniac REMOTE: 172.93.101.77:7777)
# Revision
4efe527154944ccadb51dee5ab72ca30c76b2c3e

# Description
A rod hits the station can causes air to heat up so much most of the crew is burned to a crisp
# Steps to Reproduce
light anything on fire
# What you Expected
a functioning system
# What Actually Happened
lmao fire kills everyone, fix this shit

**Comment by west3436** [comment]
Low-quality issue report - please provide specific details on how a rod started a fire. There is nothing in the code for immovable rods which could start a fire, so more details are needed to replicate.

**Comment by Inorien** [comment]
>be station
>get a rod thrown at you
>fire in its wake on flammable objects

**Comment by west3436** [comment]
Update: rods call ex_act on all floor tiles they pass which results in numerous fires. This is solved in #35965
