### ISSUE TITLE
PCP does not wear off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35985]
(WEB REPORT BY: falcon2346 REMOTE: 172.93.101.77:7777)
# Revision
320d688bd636ec9ace1b6a41c838df9843c334e8

# Description
The hallucinations and text descriptions of PCP never wear off, and persist well after being purged from your system
# Steps to Reproduce
take pcp, take charcoal, continue to hallucinate for the remainder of the round
# What you Expected

# What Actually Happened

**Comment by jwhitak** [comment]
```
	if(M)
		M.a_intent = I_HURT
		if(M?.hud_used?.action_intent)
			M.hud_used.action_intent.icon_state = "intent_hurt"
		M.hallucination += 10
```

You get 10 hallucination per tick. If PCP is in your body long enough, you can get a MASSIVE AMOUNT of hallucination that takes a considerable amount of time to go away. Also, apparently the PCP this round was laced with Spiritbreaker too so, yeah. Not a bug.

**Comment by Eneocho** [comment]
PCP is literally zine with mindbreaker so yea
