### ISSUE TITLE
autolathe sometimes asks for plastic?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#35994]
(WEB REPORT BY: realestestate REMOTE: 172.93.101.77:7777)
# Revision
958bd1e21948e6a9d3659687e7b0d8250d9efca4
sometimes the autolathe will require plastic for a recipe that it didn't previously.

**Comment by DeityLink** [comment]
which recipe @RealestEstate ?

**Comment by DeityLink** [comment]
right now only plastic buckets should require it, and the autolathe can also make metal buckets.

**Comment by RealestEstate** [comment]
I can attest that I've had it happen for assemblies, i remember failing to print a remote signaller due to this. I think it might be tied with some machine upgrades. Possibly tier 4 parts?

**Comment by RealestEstate** [comment]
The same issue as #35972
Can close this as duplicate

**Comment by Kurfursten** [comment]
This is a dupe and we have diagnosed the issue
