### ISSUE TITLE
Ethereal Grilles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36002]
(WEB REPORT BY: gimmick1 REMOTE: 172.93.101.77:7777)
# Revision
d281543e2c31ec84ba4d0d5909b6b056cb7c5f41

# Description
You can walk right through the repaired grilles.
# Steps to Reproduce
Break a grille and repair it by clicking on it with a metal rod.
# What you Expected
To bump into a grille
# What Actually Happened
I have walked right through it.

**Comment by Dacendeth** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/26881007/e8ed0ca8-c355-4026-b045-2e5ff2002025)
confirmed
