### ISSUE TITLE
You can paint glass tiles making them not-transparent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36001]
(WEB REPORT BY: blinz2 REMOTE: 172.93.101.77:7777)
# Revision
2346934e74b2c2d5c6ecb98ef529ee34fcb34a96

# Description
I painted a regular glass tile. Now its ruined. Cannot see space
# Steps to Reproduce
Paint a glass tile
# What you Expected
My glass being glass
# wha' happun?
It looks like regular floor tile now

**Comment by angryturnip** [comment]
Isn't that how it should behave? If you paint glass it's gonna be opaque irl

**Comment by DeityLink** [comment]
It's as angryturnip said. If you don't want the coat of paint to be fully opaque, then use low alpha flax oil.

**Comment by DeityLink** [comment]
this is where I'd insert a "not a bug" label if I had one.

**Comment by Eneocho** [comment]
I think he meant that partially painting a glass tile makes it opaque, despite you only covering the tile partially.

**Comment by DeityLink** [comment]
which is...not the case?
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/d123982f-52b6-4380-a249-0f6eb1d85f1b)

![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/c074531b-53db-4f64-b52d-8b1e4f4d7909)

**Comment by DeityLink** [comment]
Alternatively, here's how it looks when using flax oil 
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/436c53a8-132e-4ff0-969a-313f6262718d)

**Comment by DeityLink** [comment]
Alternatively, adding a low opacity non-pigment in your bucket will dilute the paint's opacity without affecting the color. (If you're using water, remember that it cannot make up most of the mix or it will just clean your roller)
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/09180057-56e9-4b4e-8b89-4033d9fb726d)
