### ISSUE TITLE
waystation maint tunnels arent actually protected from rads

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36013]
(WEB REPORT BY: nervere REMOTE: 172.93.101.77:7777)
# Revision
cc37f9eade63f43f619a17f002a075511dc1fcea

specifically the tunnel south of medbay but it seems everyone got owned

**Comment by Eneocho** [comment]
Traitor manually removed maintenance with the blueprints. Usermade, not a map issue.
