### ISSUE TITLE
Who made this SHITTY fucking MAP

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36012]
(WEB REPORT BY: dackjaniels REMOTE: 172.93.101.77:7777)
# Revision
cc37f9eade63f43f619a17f002a075511dc1fcea

# Description
waystation backroom near the holodeck is NOT safe from radiation despite there being no green flashing lights inside.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
Traitor manually removed maintenance with the blueprints. Usermade, not a map issue.
