### ISSUE TITLE
waystation maintenance wasn't radproof

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36011]
(WEB REPORT BY: eneocho REMOTE: 172.93.101.77:7777)
# Revision
cc37f9eade63f43f619a17f002a075511dc1fcea

# Description
title
# Steps to Reproduce
radstorm
way maint
# What you Expected
shield
# What Actually Happened
rads

**Comment by Eneocho** [comment]
Traitor manually removed maintenance with the blueprints. Usermade, not a map issue.
