### ISSUE TITLE
phantom meson triangles

### ISSUE THREAD

**Issue by hacker-on-steroids** [d3athrow/vgstation13#36042]
meson on
![image](https://github.com/vgstation-coders/vgstation13/assets/159179330/43e0e2c6-2dee-4a0a-9ce8-87c6a038ed34)
meson off
![image](https://github.com/vgstation-coders/vgstation13/assets/159179330/7a887a30-36bd-442e-9f81-f608c2093a86)

#### Steps to reproduce
have mesons on the asteroid station

**Comment by Exxion** [comment]
These sprites were also visible to me in the round this was reported, but they're not present on local. It must be caused by something that happened earlier in the round.
