### ISSUE TITLE
Feeding people drinks is screwy

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3605]
Instead of how it was before, where you would feed someone beer or some shit and it would give "X is trying to feed Y beer!" and then "X feeds beer to y!" it's now "X tries to feed you something" even if you're not the one being fed, and then it gives "You transfer ten units of beer to X".
![untitled](https://cloud.githubusercontent.com/assets/6224074/6874258/3958e564-d48c-11e4-916f-43540a136623.png)
Even though I was the one feeding in this scenario, I still got "You" as the message.

**Comment by dylanstrategie** [comment]
God fucking damnit
