### ISSUE TITLE
PAI Nutrition Synth and Chemical synth are broken

### ISSUE THREAD

**Issue by FoggyDayWindyCay** [d3athrow/vgstation13#36058]
Pai nutrition synth now brings up the chemical supplement menu, and the chemical supplement menu - either the real one or the now reskinned nutrition one - cannot dispense chems because a 'charge interrupted' error the instant you click a chemical. Uninstalling the software in question, disconnect/reconnecting, or being wiped do not fix the issue.

**Comment by Eneocho** [comment]
@RealestEstate

**Comment by jwhitak** [comment]
Related to #35865

**Comment by RealestEstate** [comment]
am troubleshooting. hotfix soon
