### ISSUE TITLE
(WEB REPORT BY: probe1 REMOTE: 198.245.63.50:7777) Flatpacks don't require welder to be on to assemble

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3608]
>Revision (Should be above if you're viewing this from ingame!)
badca894f7b42c1c32627f8b9d7a2fe126d2bd62 

>General description of the issue
Flatpacks can be welded without turning on the welder

>What you expected to happen
Welder required to turn on, fuel required to be used

>What actually happened
Did not require welder ot turn on

>Steps to reproduce if possible
build flatpack
apply welder on correct step without turning it on

add a sanity check

**Comment by dylanstrategie** [comment]
Nothing to do with a sanity check, it needs snowflake coding instead, sadly enough
