### ISSUE TITLE
Moving a Red Telephone breaks the phone feature

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36106]
(WEB REPORT BY: west3436 REMOTE: 172.93.101.77:7777)
# Revision
e6fcc79ebc6a923d6079e728819feea62b548ae0

# Description
dragging a red phone elsewhere prevents the phone function from working
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by hacker-on-steroids** [comment]
unable to reproduce
the cord doesn't update when the base is moved, though
