### ISSUE TITLE
A Lot Of The Landline Stuff Is Formatted Very Poorly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36108]
(WEB REPORT BY: primed REMOTE: 172.93.101.77:7777)
# Revision
1c0ed7af588436b8f89ea3c08d5f366eacd0a5f6

# Description
a lot of lacking capitalisation etc
"the landline cord stretches dangerouslyx2"

"the cord snaps!"
-other section in the menu is lowercase

Also in another issue there's a lot of identical named phones that makes it hard to tell where you're calling!

**Comment by MercuriusGH** [comment]
Probably mainly a mapping issue
On Box there are 3 phones in security all called "Security"
on Horizon medbay only has phones in viro and CMO, nothing in chemistry or anywhere else

**Comment by hacker-on-steroids** [comment]
the names are a mapping issue
i could probably """fix""" it by just naming each RC the same as the APC area it's in

**Comment by Eneocho** [comment]
> the names are a mapping issue i could probably """fix""" it by just naming each RC the same as the APC area it's in

`>medbay still gets 3 RCs named "MEDBAY"`

**Comment by PrimeDSS13** [comment]
I think a decent bandaid fix could be to just label duplicates "medbay 1" "medbay 2" "medbay 3"?
Maybe it just lists a single "Medbay" and calls all three, free to be picked up at any of them?
That, or some remapping.

**Comment by hacker-on-steroids** [comment]
real fix for the identical phones would be implementing multi-phonecalls
ie you ring "medbay" and all 5 of the medbay phones ring - that's how the RC message feature works currently
multi-phonecalls will fix one of the switchboard bugs too but it's an undertaking
