### ISSUE TITLE
Ghetto surgery specifically requires welders to be off

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3610]
You can use welders, lighters and I think a third thing as a cautery replacement in ghetto surgery.
However it won't work if the welder is on. This one puzzled me for an entire shift and left the station asspie-less.

**Comment by dylanstrategie** [comment]
Most likely fucked up the WT.IsOn() check

**Comment by dylanstrategie** [comment]
Completely lacking any place to put checks into, blame whoever refactored surgery

**Comment by clusterfack** [comment]
Manually modify the can_use procs to check tool.is_on() and remove fuel.

**Comment by ComicIronic** [comment]
Actually caused by a lack of an amount requirement in the construction check. There is deliberate functionality to allow you to use a non-lit welder unless otherwise specified.

**Comment by clusterfack** [comment]
Construction check? Are you sure you aren't talking about something else here?

**Comment by ComicIronic** [comment]
WOOOOOOOOOOOOPS
