### ISSUE TITLE
Wizard Shot A Fireball At Me After I Removed His Ass

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36114]
(WEB REPORT BY: primed REMOTE: 172.93.101.77:7777)
# Revision
7c36f7fb44976beb03f99d581961a8e31a649adf

# Description
>take off wizards ass
>remove his muzzle
>he instantly casts 2 fireballs at me killing me
magic... is NOT stored in the ass.

**Comment by Dacendeth** [comment]
After some testing magic is stored in the ass, however ass removal surgery does not properly remove spells but other methods seem to work as expected.
