### ISSUE TITLE
All suits prevent tails from showing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36119]
(WEB REPORT BY: falcon2346 REMOTE: 172.93.101.77:7777)
# Revision
5a72a3f89ae4b535bc5ab77e67f2e854dfc89470

# Description
All suits, including things like lab coats and vests, prevent tails from showing
# Steps to Reproduce
Be tailed race, equip anything in suit slot
# What you Expected
Tail to be visible past the vest
# What Actually Happened
Tail disappeared

**Comment by jwhitak** [comment]
Calling @13spacemen, this is confirmed. Hazard vests, lab coats, and generally anything in the suit slot will hide the tails.

**Comment by hacker-on-steroids** [comment]
#35430 is sorta related
