### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Pill Bottles not working correctly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3611]
Pill bottles are not picking up groups of pills like they should.
You have to place them in by hand which is very annoying, please fix.

**Comment by Probe1** [comment]
temporary bandaid is to insert the pill bottle inside the chemmaster so the pills are automatically placed within.  

I encounter this bug every time I assemble a chemmaster as a mechanic.  Very strange and very recent 2-3 days at the most.
