### ISSUE TITLE
Vox eye colors are always green

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36113]
(WEB REPORT BY: bungofungo REMOTE: 172.93.101.77:7777)
# Revision
7c36f7fb44976beb03f99d581961a8e31a649adf

# Description
despite setting my characters eye colors to a pinkish sort of color, they appear lime green in game, other vox seem to have this issue too
# Steps to Reproduce
make a vox character, set eye color, spawn in
# What you Expected
eyes to be correct color that you picked
# What Actually Happened
its GREEN!! ITS GREEEN!!

**Comment by 13spacemen** [comment]
the vox eyes have 2 parts, the inner part is user colorable but the outer part has always been green

my pr didn't touch vox eyes or their sprites so not sure why the entire eye is green for you

![Screenshot 2024-02-29 102820](https://github.com/vgstation-coders/vgstation13/assets/46101244/9a9036df-5cfb-428e-b986-aaa97d1181fa)

**Comment by falcon2346** [comment]
I knew I wasn't crazy! My Vox's eyes are supposed to be indigo but showed up as bright blue yesterday. Something has definitely changed.
