### ISSUE TITLE
Wizard refund bug allows for endless casts from the den

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#36120]
#### Description of issue

![image](https://github.com/vgstation-coders/vgstation13/assets/16082007/bdc53c76-9c9b-4454-a1e0-b5e989e3aefd)

#### Difference between expected and actual behavior

This is gay

**Comment by nervere** [comment]
It's being fixed in #36078, it's to do with the static list in spellbooks' `New()`, not refunding.
(and yes, Barry is extremely lame for doing this)

**Comment by hacker-on-steroids** [comment]
more like extremely incentivising the collabs to step up their game
