### ISSUE TITLE
Can no longer "Quick Robot" with 50 metal sheets because "Robot Tail" is wastefully made

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36121]
(WEB REPORT BY: inorien REMOTE: 172.93.101.77:7777)
# Revision
5a72a3f89ae4b535bc5ab77e67f2e854dfc89470

# Description

Non-essential robot part in quick robot queue

# Steps to Reproduce

Put 50 sheets in exo fabricator, click Quick Robot and go

# What you Expected

Robot left leg
Robot right leg
Robot left arm
Robot right arm
Robot chassis
Robot torso
Robot head

# What Actually Happened

Robot left leg
Robot right leg
Robot left arm
Robot right arm
Robot chassis
Robot torso
Robot tail

**Comment by Eneocho** [comment]
Robot tail really should be under misc, rather than robot parts.

**Comment by jwhitak** [comment]
Quick Robot shoudn't print it in any case (unless borgs can get cybertails, which is a feature request you might want to ask @13spacemen for...)

**Comment by Eneocho** [comment]
I checked, quickrobot just prints anything on the Robot tab, and since robot tail was moved there, it gets added to the quickrobot list. It should be moved to misc or similar.
