### ISSUE TITLE
Color-changing fires are putting massive stress on the light system

### ISSUE THREAD

**Issue by boy2mantwicethefam** [d3athrow/vgstation13#36128]
Normally fires wouldn't update the light overlays that much because the light source remained static and there's code during light processing to see if there's any difference compared to before, and thus it wouldn't be tough.
However, #35127 added color changes to the fires based on how hot they are, which is a really cool visual effect but that also causes the fires to overwhelm the light system with light updates constantly because the colors are different, causing lights across the whole game to start lagging badly for as long as the fires continue.

**Comment by Eneocho** [comment]
could just make the fires themselves change colour but the light they emit stay a constant white
would be a patch solution until a better way to have the fires do fancy lights is found

**Comment by MercuriusGH** [comment]
they also look kinda bad imo especially lower heat ones
