### ISSUE TITLE
STUPID ASS WHEELSTATION DOESNT HAVE A FORENSIC SCANNER (THE KEY ITEM TO PLAY DETECTIVE) IN THE DETECTIVES OFFICE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36122]
(WEB REPORT BY: nervere REMOTE: 172.93.101.77:7777)
# Revision
5a72a3f89ae4b535bc5ab77e67f2e854dfc89470

# Description
WHY
# Steps to Reproduce
Don't be the guy that made this map, for one.
# What you Expected
burneddi to maintain this piece of shit
# What Actually Happened
he's gone

**Comment by jwhitak** [comment]
Specifically it's the computer, and @nervere confirms that they will be adding it in after the round is over.
