### ISSUE TITLE
giftwrapping a beartrapped guy will qdelete him

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36131]
(WEB REPORT BY: janez420ivan REMOTE: 172.93.101.77:7777)
# Revision
973ba5d108ec6fe857e094177c3b4a6eb7041688

[ided]

**Comment by GreatBigFailure** [comment]
I thought this was fixed ages ago but apparently not. 
If that's the case then some (possibly outdated no longer true) detail:
- Gift wrap and package wrap work differently. One of them deletes the person if you open it, the other doesn't. I THINK gift wrap doesn't delete them, but I might have it backwards. 
- You can pick up and carry the package/present with the person inside as if it's just a wrapped bear trap, the person can speak and what not from inside
- You can even do weird stuff like put the present in a vending machine which ~~was hilarious~~ is potentially abusable and should not be done ever
- Suspension field generators do the same thing if the person in the bear trap is in the field when it's activated, and is then qdel'd when it's deactivated. This part might be what was fixed though
