### ISSUE TITLE
(WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Wizard Horse mask not removing other masks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3613]
>Revision (Should be above if you're viewing this from ingame!)
19ba1e9dce61b14d0df890f45b8537061a88d5bc

>General description of the issue
People wearing internals from round start makes this spall obsolete

>What you expected to happen
Breath mask would be replaced by horse mask

>What actually happened
Spell did not affec that person

>Steps to reproduce if possible
Look above.

**Comment by dylanstrategie** [comment]
Spell should most likely use a homemade proc to empty the mask slot and put the horse mask in instead of trying to create one, which always fails if something is on the face slot

**Comment by d3athrow** [comment]
Can't reproduce as I was able to put a mask on a dummy and horsehead him.
