### ISSUE TITLE
Galo tanning bed sprite broken?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36142]
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
5d9cdf465e3ce2849044558d4c945d66ddc90fa8

# Description
an admin tried spawning the tanning bed and it ended up being invisible
the sprite might be broke or something

**Comment by nervere** [comment]
Probably an admin error? It works fine for me.
Typepath is `/obj/machinery/sleeper/mancrowave/galo`
![image](https://github.com/vgstation-coders/vgstation13/assets/26285377/6d2e64e1-48b1-4d4c-a929-3a286b6bbb5b)
