### ISSUE TITLE
Being turned into a Ghoul permanently blinds you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36143]
(WEB REPORT BY: higitus REMOTE: 172.93.101.77:7777)
# Revision
5d9cdf465e3ce2849044558d4c945d66ddc90fa8

# Description
As the issue says, Lanny smith turned me into a ghoul but after I became one no chem or even surgery to replace my eyes fixed my vision. I was told to report it.
LOOC: Lanny Smith: bug report it

LOOC: Lanny Smith: nervere fucked it up I think

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
The other one has a bit more info, closing in favour of #36144
