### ISSUE TITLE
Blind after ghoulified, nothing fixes it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36144]
(WEB REPORT BY: angryturnip REMOTE: 172.93.101.77:7777)
# Revision
5d9cdf465e3ce2849044558d4c945d66ddc90fa8

# Description
Someone turned me into a ghoul. My vision is as if I'm blind, but eye medicine squirted into the eyes and even giving new eyes via surgery doesn't remove the blindness
# Steps to Reproduce
turn into a ghoul (via cryo maybe. I don't know if that specifically is what caused it)
# What you Expected
To be a non-blind ghoul
# What Actually Happened
Couldn't see!!!!!

**Comment by Eneocho** [comment]
did you try Rye? you very likely got genetic blindness due to the standard chem-ghoulification using mutagen and shit

**Comment by angryturnip** [comment]
Yes

**Comment by angryturnip** [comment]
Cloning fixed it. Everything from rye to eye meds to surgery didn't.
