### ISSUE TITLE
genetics block injector gives all S.E. genes, not just from the block

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36147]
(WEB REPORT BY: nervere REMOTE: 172.93.101.77:7777)
# Revision
5d9cdf465e3ce2849044558d4c945d66ddc90fa8

# Description
took an SE injector for a power and it gave me 20 disabilities instead

# Reproduction
i did the mutagen chamber method to get all of the disabilities/powers on the monkey

**Comment by nervere** [comment]
i realized i was wrong immediately after posting this
(this isnt a bug im just dumb, my latent genetics from getting dosed on mutagen earlier were reactivating after rye masking)

**Comment by Eneocho** [comment]
closing
