### ISSUE TITLE
Vampire Shapeshift heals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36152]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
190628293482bf30079650e1f6f04a5d39c812fe

# Description
be a vampire
# Steps to Reproduce
press shapeshift and heal
# What you Expected
not heal
# What Actually Happened
healed to 100

**Comment by boy2mantwicethefam** [comment]
It happens because it changes the species to "vampire" and in the process of changing species it re-generates all of the user's organs, basically creating brand new limbs to replace the old damaged ones.

**Comment by hacker-on-steroids** [comment]
removes any IB's or missing limbs or tracking implants and whatnot, too

**Comment by toomykins** [comment]
This bug is pretty much the only feature to make vampires fun imo
