### ISSUE TITLE
couldn't shade as cultist, only ghost

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#36167]
#### Description of issue
roundstart cultist
got husked by headshot lasers
couldn't shade, only ghost
#### Difference between expected and actual behavior
expected to shade and shit
forced to obsgang
#### Steps to reproduce
do the steps in the description
#### Length of time in which bug has been known to occur
fuck if I know
#### Server revision
[bugfix]

**Comment by DeityLink** [comment]
Did you try to shade right away or wait over a minute after your death?

**Comment by Eneocho** [comment]
died, another cultist tried to clone me but then meandered and left me abandoned by medbay, i then tried to shade and failed

**Comment by DeityLink** [comment]
Not a bug then, there is a 60 seconds limit for being able to shade after dying as a cultist. Making a note to have this limit better communicated, maybe with a visible timer.

**Comment by Eneocho** [comment]
that would be good to have yes, thanks for the clarification
