### ISSUE TITLE
Cult path runes can send you AAAANYWHERE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36183]
(WEB REPORT BY: spacedgod REMOTE: 172.93.101.77:7777)
# Revision
824b87f904a8418de4621c8e0a578014bb99679a

# Description
you can stick one on a cargo shuttle and go to centcomm which is probably not intentional
# Steps to Reproduce
be cult, slap path rune down, sent to centcomm, get scolded by admin
# What you Expected

# What Actually Happened

**Comment by Eneocho** [comment]
>get scolded by admin

once again the men on top trample on the hard working cargonian

**Comment by DeityLink** [comment]
alright fine
