### ISSUE TITLE
Issues with Greytide Implanting a Traitor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36186]
(WEB REPORT BY: theophrastus REMOTE: 172.93.101.77:7777)
# Revision
824b87f904a8418de4621c8e0a578014bb99679a

# Description
Observed a traitor try to implant another traitor with a greytide implant. It resulted in the implant being refused, but the implantee being slaved to the implanter. Apparently the implant dropped to the floor as well.

# Steps to Reproduce
Be a traitor and implant another traitor with a greytide implant

# What you Expected
Either refusal of the implant or implantation properly

# What Actually Happened
Both happened, implant was refused and traitor was greytided

**Comment by hacker-on-steroids** [comment]
happens if you implant a mouse, too

**Comment by Theophrastus1** [comment]
I'd like to update that this also occurs when you try to implant a player that is already loyalty implanted. The implant will not be placed into them, they will "resist" the implant, and then they will be given greytided antag status despite their loyalty implant. Re implanting them with a loyalty implant does not fix this either to my knowledge

**Comment by hacker-on-steroids** [comment]
is that update before or after #34803?

**Comment by Theophrastus1** [comment]
Yeah, this occurred in a round the day of me posting this, so it is still currently borked despite that PR
