### ISSUE TITLE
Revs music does not trigger when they go loud

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36182]
(WEB REPORT BY: theophrastus REMOTE: 172.93.101.77:7777)
# Revision
0d7e1eccef1a3909779918b893ca04023b77b08b

# Description
Music that is supposed to start once the revs go loud does not start playing once the union message comes out.

# Steps to Reproduce
Go loud as revs

# What you Expected
Sick tunes and beats

# What Actually Happened
Dead silence

**Comment by hacker-on-steroids** [comment]
i know absolutely nothing about the subject and i blame #34504 or some other similar PR

**Comment by Theophrastus1** [comment]
I would assume that if revs isn't working, that the other antags that would call music to play are probably not working either, like nukies. Only an assumption though

**Comment by Eneocho** [comment]
i played nukies a few days ago and don't remember hearing any music (though i'm not sure if I'm misremembering)

**Comment by Theophrastus1** [comment]
> i played nukies a few days ago and don't remember hearing any music (though i'm not sure if I'm misremembering)

With nukies to my understanding they actually have to hit a button to go loud, which I find stupid because you can end up with rounds where they get outed and there's no theme setting music. But I haven't gotten nukies to try it for some time now, so I'm not certain. Might be worth lookin into

**Comment by Eneocho** [comment]
Wasn't the "nukies go loud, get the music and more TC" button reverted?

**Comment by Theophrastus1** [comment]
> Wasn't the "nukies go loud, get the music and more TC" button reverted?

even before that they have a button the commander can press to "go loud" otherwise they are stealth. It's so that >stealthops dont get outed or something. So far as I know the nukies commander still has the button he can press to start the music and go "loud". What you're thinking about was just the war declaration that forewarned the station. This is just to start the music for the game mode

**Comment by Theophrastus1** [comment]
I just confirmed that pressing the go loud button on nuke commander during ops triggers the message, but does NOT start the syndicate assault playlist
