### ISSUE TITLE
Ian eats brains

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36208]
(WEB REPORT BY: apotheoticorder REMOTE: 172.93.101.77:7777)
# Revision
2624657e5bd5627cb3ac36794337f042eb225b7a

This should probably be changed. Also, I think after he took a bite out of one it was unable to be put into an MMI, although I'm not 100% sure.

**Comment by toomykins** [comment]
haven't tested but don't see how it's possible considering ian only goes after food-categorized items
brains aren't that

**Comment by Dacendeth** [comment]
Ian only eats brains after someone else has taken a bite out of them, as doing so changes the brain from `/organ/internal/brain` into `/food/snacks/organ` and at that point from a mechanical perspective it doesn't matter if Ian eat's the brain as it's irreversibly fucked anyways in terms of reviving the person in any form.

**Comment by jwhitak** [comment]
This has been tested by our boy here and it's confirmed that Ian only goes after the pre-chewed brains. They're already past saving at that point.
