### ISSUE TITLE
Game panel "Force Dynamic Rulesets" does not work as expected

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#36201]
[bugfix]

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/403de763-e55a-435b-91c1-55887e06e7f5)

This one here? Before one round, I clicked "Extended" and added it to the list of rulesets, hoping it would do something. I didn't remember the proper method to force Extended and thought this might work.

It did nothing, the round had 95 threat and two vampires to start. Dynamic did not seem affected whatosever and did not list Extended as a ruleset.

**Comment by toomykins** [comment]
>[14:16:32]ADMIN: Kilozombie/(Kilozombie) set Extended to be a forced roundstart ruleset.
>[14:20:56]ADMIN: DYNAMIC MODE: 1 rulesets being forced. Will now attempt to draft players for them.
>[14:20:56]ADMIN: DYNAMIC MODE: Extended has 0 valid candidates out of 13 players (2 disconnected, 11 didn't want the role, )
>[14:20:56]ADMIN: DYNAMIC MODE: Not a single forced ruleset could be executed. Sad! Will now start a regular round of dynamic.


odd
