### ISSUE TITLE
"You need to take that off before cleaning it" - even though it's in your hand

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3622]
Apparently the game thinks you're still wearing that hardsuit even after you take it off and hold it in your hand, so you have to drop it to the ground, clean it, then pick it back up. Pretty silly.
Also goes for items you can't even wear: You need to take off that book.

**Comment by CptWad** [comment]
Usually I would put it on the floor to clean it but yeah :+1:

**Comment by ComicIronic** [comment]
Probably does a check in mob, rather than a check in mob's equipped items.

**Comment by d3athrow** [comment]
for soap or what?

**Comment by 9600bauds** [comment]
Yeah with soap, sorry.
