### ISSUE TITLE
Salvage ship doesn't work anymore

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3623]
Even having the correct ID, the computer doesn't actually move the ship when selecting any of the destinations.
Happens even when testing in a local server.
I am 100% sure it worked yesterday at this time.
EDIT: Can confirm it was broken by https://github.com/d3athrow/vgstation13/commit/5d9c06c880ee46a4d57e9e9da58b6e9aedc36390

**Comment by clusterfack** [comment]
Fixed via daae3baf6f9446d5f8c3e63079cf45781bddde04
