### ISSUE TITLE
Mob attack messages don't show up to the person being attacked

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3624]
To reproduce: Get wailed on by a Goliath/Giant Spider/Carp/etc. Health decreases with no messages.
Have that mob attack anybody else, messages will appear.
Messages about your bones breaking and special mob attacks (like spiders injecting venom) do still work and display properly, it's just basic melee attacks that don't display anything.

**Comment by CptWad** [comment]
Confirming :+1:
