### ISSUE TITLE
Comprehensive guide to the Greytide implant bug

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#36255]
[bugfix] [help]
LOOSE

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/ec514d60-6c34-4530-8784-df209c5efd41)

If you implant someone with a Greytide implant, it works as expected. They are a slaved antagonist to you. If the implant is removed, they are no longer an antagonist. This seems to be the original intended behavior of the implant.
Serious problems arise if you implant someone who has **literally any other implant**. This could be a loyalty implant, tracking implant, et cetera.

1. The implant will pop out of the syringe onto the victim's tile intact. This means it can be reused after the process by slotting it into an empty glass case.
2. The victim will appear to "resist the implant", and retain their old implant (loyalty, tracking, whatever.)
3. The victim will become a Greytider slaved to whoever tried to inject them. **This becomes permanent** and they can never be deconverted.

This means that you could pretty easily Greytide the entire crew regardless of implants. Actually it becomes *much easier* if they already have a loyalty implant, but you could also just grab a case of tracking implants and easily have infinite conversions.

LOOSE. FIX IMMEDIATELY.

**Comment by kilozombie** [comment]
Duplicate of, like, a half-dozen issues, but hopefully this is the best collation of how it works

**Comment by hacker-on-steroids** [comment]
#35618 #34846 #36186
and i assume #34620 and #34256 which were closed aren't actually fixed
