### ISSUE TITLE
"Faint brainwaves detected. Subject may be revivable." yet MIF on cloning and "nerve trauma" on defib

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36260]
(WEB REPORT BY: nervere REMOTE: 172.93.101.77:7777)
# Revision
c9c36c71b8c0627a90cd5ba3a3e5e341e1caa774

pretty sure this guy mustve been put in a new body or something but it shouldnt say revivable if the target actually cant be revived lol

**Comment by hacker-on-steroids** [comment]
health analyzer doesnt check suicides
examine the body with your eyeballs
