### ISSUE TITLE
MoMMIs Can't Use Regular Material Synthesizers

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3629]
My mounted material synthesizer couldn't scan additional materials, which isn't really that big a deal. So I build a normal material synthesizer, scanned silver and gold and whatnot, loaded it with matter cartridges and attempted to replicate the materials. When I tried to create any amount of anything using the normal material synthesizer, I got the message "You can't make that much [mineral] without shutting down!" which to me makes it seem like it was trying to use my mounted synthesizer, and my energy, instead of using the synthesizer I had in my hand and its matter cartridges. Despite the message, the matter cartridges were drained, though no materials spawned. Additionally, I could continue draining the matter cartridges into the negative numbers.

![material](https://cloud.githubusercontent.com/assets/3991927/6886848/b9abc39a-d611-11e4-9cfc-21471eccdc4d.PNG)

Anyway, this effectively means MoMMIs are incapable of using standard material synthesizers at all, which is a problem if one wishes to scan and replicate something not in the MoMMI's synthesizer's data, or something which would normally have too high an energy cost.

**Comment by clusterfack** [comment]
You actually shouldn't even be able to pick one up as a mommi, due to the fact you have a material synthesizer in your inventory.

**Comment by Shadowmech88** [comment]
So how are you supposed to replicate rare materials as a MoMMI if your own synthesizer can't scan other minerals?

**Comment by clusterfack** [comment]
Replicating rare resources as a mommi was removed due to balance concerns considering how preposterously easy it was to do so due to what mommis have the ability to do. (all access, infinite cargo account, rapidly exchanging batteries, etc)

**Comment by ComicIronic** [comment]
A larger issue was also MoMMIs subtly breaking their laws by scanning and spawning large amounts of rare materials, since their cost was essentially free.

**Comment by clusterfack** [comment]
That is what I just said

**Comment by 9600bauds** [comment]
Code assumes the synthetizer is the built-in module if the user is a robot. Which of course fucks everything up.
The entire code for borg synthetizer is a mess. I could try fixing this, but how is it meant to work? Are MoMMIs meant to use handheld synthetizers or not? (obviously using cartridges, not their battery)

**Comment by clusterfack** [comment]
Mommis cant pick up any tool that they have already built in, that's how all their modules are meant to work right now.

**Comment by PJB3005** [comment]
Actually, MoMMIs CAN pick up tools they already have (but can't, for example, recycle them in an autolathe)

**Comment by clusterfack** [comment]
I noticed that recently, it did not work this way for a LONG time and I'm somewhat curious as to who changed it.

**Comment by Shadowmech88** [comment]
Apparently by design.
