### ISSUE TITLE
Transfering flour to microwave just got very fucky

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#3630]
Floursacks won't transfer flour to microwave, milk cartons won't transfer flour to microwave. Kitchen got a large beaker but you can't set the transfer amount to five and some recipes require you to go five by five units. Small beakers can be set to transfer five units but you gotta ask chemist or cargo for that so good luck getting it. Please fix.

**Comment by d3athrow** [comment]
this is dylans doing

**Comment by MusgardTiger** [comment]
Aight I am closing this then.

**Comment by ComicIronic** [comment]
Don't close it, it's not fixed.

**Comment by MusgardTiger** [comment]
Aight, github still a mystery to me.
