### ISSUE TITLE
Blob spawned in as a "midround" at 12:05

### ISSUE THREAD

**Issue by KingofHONK** [d3athrow/vgstation13#36300]
Pretty much what it says on the tin, blobs spawned in almost immediately into a new round as a midround. Not sure if this was intentional or a bug, so wanted to report it. Log is for ended 8:43pm EST, Mar 31, 2024. Don't have much else info to go off of other than that, sorry!

**Comment by jwhitak** [comment]
Fun fact - this is the earliest a midround antag can fire off! If this is considered too early, the value could be tweaked, but currently this is right at the intended limit.
