### ISSUE TITLE
Add Parts to Machine Frame Directly From Gadget Bag

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3631]
I'd like to be able to pick up a pile of components with the gadget back, click on a machine frame with a circuit board in it, and have it empty all the compatible parts directly out of the bag into the machine frame, instead of having to empty them on the floor and place them in one-by-one.

I'd imagine such a feature would function identically to how emptying plant bags into the SmartFridge or grinder already does.

**Comment by dylanstrategie** [comment]
I have thought about this for a bit, but maybe with another tool

It could even be a new function for the Mechanic

**Comment by clusterfack** [comment]
Rapid part exchanger, it already exists on /tg/ for example, and I would like to see it here but I wouldn't want it to instantly outclass everything else including gadget bags, like RPDs did.

**Comment by ComicIronic** [comment]
There's no need for it to "outclass" anything, we can simply add the functionality to gadget bags. I don't foresee any major balance issues, and it's a good enough QoL improvement.

**Comment by clusterfack** [comment]
If someone were to do that they had better make sure gadget bags are buildable too

**Comment by 9600bauds** [comment]
I made them a possible product from the biogenerator.

As for the change, I'm not sure. Building a machine frame should take at least a little bit of doing, and it's not like it's any difficult or time-consuming right now as jamming in each part is instantaneous and you get a quick message telling you exactly what's missing after each part.
What if you have different tiers of manipulators in your gadget bag? Should the higher tier ones be used first?

**Comment by Shadowmech88** [comment]
>What if you have different tiers of manipulators in your gadget bag? Should the higher tier ones be used first?

I think so.

**Comment by Probe1** [comment]
Add it to gadget bags please!  Please!  That would be a huge QoL improvement that I've wanted for a long time.  

Also some way to get additional gadget bags like a Mechanics Crate that comes with a device analyzer and gadget bag!

**Comment by clusterfack** [comment]
We have the rapid part thingy now

**Comment by Probe1** [comment]
It was a very different idea @clusterfack than what we got.  We said yes to letting gadget bags tip their parts into a machine frame.  The RCMP is a mouthful of stuff, but not that.

**Comment by Shadowmech88** [comment]
I was actually planning on making an issue about the RCMP once I gather some data on it. I have a feeling it's not much more effective than using gadget bags considering its extra steps, and may even be less effective.

**Comment by Probe1** [comment]
I try to use it when I can and its effectiveness comes from not having to disassemble machines that have to be set up.

1.  Cloner etc.  You don't want to make the medbay players lose all their biomass so the component exchanger is great for that.

2.  RnD/Robotics.  You don't want them to have to resync and relink so the component exchanger is great for that.  

Otherwise it's still faster to just disassemble the fucker and do it by hand.

**Comment by Shadowmech88** [comment]
Not to mention you have to manually empty the inferior components once you make the upgrade, whereas using a gadget bag and disassembling you're able to pick up all of the old components at once and dump them in a disposal chute in a couple seconds.

**Comment by Probe1** [comment]
exactly.  there is a very high maintenance cost of using the component exchanger that isn't present with gadget bags.  you originally asked to just add parts akin to the plant bag to the fridge, which I think is fucking great.  it's simple.  it's direct.  It's EXTREMELY limited since there are only 6 gadget bags on the station.
