### ISSUE TITLE
(WEB REPORT BY: probe1 REMOTE: 198.245.63.50:7777) Headset channels are totally cocked up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3632]
>Revision (Should be above if you're viewing this from ingame!)
f936c9a44a7fef1bd99ecf85011fe6604b937f9a 

>General description of the issue
Mechanics no longer have access to the science radio channel.  Shaft miners no longer have access to supply channel.

>What you expected to happen
Self explanatory, at round start they should have those channels keyed to their headsets

>What actually happened
They weren't

>Steps to reproduce if possible
Start game as either job or probably more

**Comment by CptWad** [comment]
:+1: Confirmed. Cannot fix with telecomms console.

**Comment by Probe1** [comment]
this has been fixed today but I cannot find the commit that fixed it

**Comment by ComicIronic** [comment]
It was on the secret repo, as I understand it.

**Comment by ComicIronic** [comment]
Not fixed. Most recent report in #3659.

**Comment by Probe1** [comment]
It was broken, it was fixed, it was broken again.

Either jews or ghosts or sarca is behind this.

**Comment by Probe1** [comment]
It was fixed, but will it be fixed for good?  I laughed, I cried, Tom from Byond offhandedly stated they changed something that might be related.  A tale of learning and hope.

**Comment by clusterfack** [comment]
You can track some more of our efforts and confusion here 
http://www.byond.com/forum/?post=1822135

**Comment by ComicIronic** [comment]
Alright, is this fixed now?

**Comment by Probe1** [comment]
Yes, this is fixed.
