### ISSUE TITLE
Nu RPD UI issue

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#36325]
#### Description of issue
If you have the multilayer mode on the RPD activated and build some pipes/devices, eventually the thing will break and disable the layers for the latest object selected (it has happened to me with unary vents and heat pipes), other objects layer properly, but the bugged one will only ever build on the center layer.
I also had the autowrench mode enabled, but I'm not sure that would cause this.
#### Difference between expected and actual behavior
Expected it to work properly.
Was broken.
#### Steps to reproduce
Enable multilayer and autowrench mode on the RPD, build pipes until ti breaks.
#### Length of time in which bug has been known to occur
Since nu-RPD UI.
[bugfix]

**Comment by CrazyAmphibian** [comment]
this probably has to do with how i implemented it storing which layer you had selected in #36066
i didn't actually test rapid-firing of it so uhh... my bad.
i'll look into it
