### ISSUE TITLE
Station alerts pager gives alerts not about the station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36326]
(WEB REPORT BY: crazyamphibian REMOTE: 172.93.101.77:7777)
# Revision
15b93c5006ac87d39cf7754cbf2f5e0e93bebdf1

# Description
the station alerts pager will read out alerts from places like the derelict and vox trading port
# Steps to Reproduce
turn on pager and wait
# What you Expected
to not see the alert
# What Actually Happened
i saw the alert

**Comment by Inorien** [comment]
i wish the station alerts computer also wouldnt give alerts about random off-station shit
its a pain walking past, seeing a red light only to learn about a power issue on the derelict
