### ISSUE TITLE
Camera Bug Cigarette Pack Cannot Access Inventory by Dragging Onto Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36338]
(WEB REPORT BY: slashbolt REMOTE: 172.93.101.77:7777)
# Revision
f57689d896d169b31af3b3efdcc47710628283b2

# Description
Cannot access inventory of Detective's Camera Bug Cigarette Pack by dragging onto the Player Sprite

# Steps to Reproduce
Attempt to access inventory of Dromed Co. Packet by clicking on it and dragging onto self.

# What you Expected
To access container similar to boxes, bags, and other containers.

# What Actually Happened
Cannot access Dromed co. packet inventory in manner described. Very inconvenient for inconspicuous access when attempting to plant bugs.

**Comment by west3436** [comment]
You can access the inventory by either clicking the packet with your offhand. It can be discretely accessed by alt-clicking it. I don't want to make disabling the speaker any less intuitive than it already is.
