### ISSUE TITLE
Cryotheum gas doesn't firelocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36344]
(WEB REPORT BY: skeletonsteve REMOTE: 172.93.101.77:7777)
# Revision
d76e75a35896c2d0bdcb27aa940decc70d5014ba

# Description
like, the cryotheum gas or whatevs? It like, totes doesn't cause firelocks to come down when it floods and junk!
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by ghost** [comment]
Probably cause I used the central atmospherics console to change the danger thresholds hun

**Comment by hacker-on-steroids** [comment]
doesn't firelocks what?

**Comment by SonixApache** [comment]
did you really have to make this report in-character

**Comment by west3436** [comment]
Bad issue report + IC issue + skill issue

**Comment by SECBATON-GRIFFON** [comment]
> did you really have to make this report in-character

muh immulsions
