### ISSUE TITLE
(WEB REPORT BY: kismywaifu REMOTE: 198.245.63.50:7777) DEPARTMENT CHAT

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3634]
DEPARTMENT CHAT IS BROKEN.
NOT SHOWING UP AS AN OPTION TO ENABLE ON HEADSETS

ANY TIME YOU TRY TO TALK INTO A DEPARTMENT IT ANNOUNCES IT OVER COMMON

DON'T KNOW ABOUT SYNDIE OR BINARY

PS. FUCK YOU DYLAN

**Comment by ComicIronic** [comment]
Duplicate of #3632
