### ISSUE TITLE
Trader shuttle security vendor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36346]
(WEB REPORT BY: leon454 REMOTE: 172.93.101.77:7777)
# Revision
d76e75a35896c2d0bdcb27aa940decc70d5014ba

# Description
the trader security vendor is inaccesable to traders
# Steps to Reproduce
play trader
# What you Expected
self defense
# What Actually Happened

**Comment by west3436** [comment]
Feature; the crate is for selling to Security and was not made as a free armory for the b*rdmen
