### ISSUE TITLE
Run faster with helmet off on security hardsuit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36368]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
d76e75a35896c2d0bdcb27aa940decc70d5014ba

# Description
I have my sec hardsuit on. I run around slowly. I put the helmet on and I'm faster
# Steps to Reproduce
wear hardsuit
# What you Expected
run equally fast with or without helmet on
# What Actually Happened
ran faster with helmet on

**Comment by Dacendeth** [comment]
https://github.com/vgstation-coders/vgstation13/assets/26881007/ea4b0c79-3f00-4725-9f25-cc4c285eaa23

You likely just had a hardsuit that was upgraded with a speed module, which only functions while the helmet is worn.

No bug here probably.
