### ISSUE TITLE
Vox hairstyles broken or something

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36377]
(WEB REPORT BY: bungofungo REMOTE: 172.93.101.77:7777)
# Revision
6a0dd8b91bc48ab1fd277de3df7e6b75f91666ca

# Description
Possibly more testing required, I am continously unable to spawn in with my character slot hairstyle and unable to change it once in game either
# Steps to Reproduce
Make a Vox character with brown coloration, and green-brown ruffhawk hair style
# What you Expected
To have the cool ruffhawk
# What Actually Happened
Bald, forever, I cannot stop being bald, please help

**Comment by west3436** [comment]
@13spacemen

**Comment by MercuriusGH** [comment]
just an FYI but these bugs existed before @13spacemen 's PRs
