### ISSUE TITLE
R&D is no Longer Self Sufficient

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3637]
For a time it was possible to effectively finish R&D with only items printed in R&D, but as of right now it is necessary to retrieve an outside item in order to move Engineering research from 1 to 2, as there is nothing R&D can produce that has a tech origin level of 1 Engineering.

I'm not sure if this is intentional or what, but it stuck out to me.

**Comment by ComicIronic** [comment]
You can deconstruct a welding tool in one of the toolboxes for Engineering 1. Some of the other tools also give it.

**Comment by Killette2** [comment]
Did you try a wrench or the analyzer that is often abandoned in toolboxes? I remember analyzer gives 2 types of levels that are very useful, despite the tool being made pointless by PDAs.

**Comment by Shadowmech88** [comment]
Yep, looks like the analyzer is what you deconstruct. I've been doing both Toxins and R&D lately so I've been pocketing it instead of deconstructing it.
Case closed, I'm a dummy.
