### ISSUE TITLE
food and drink consumation delay issues

### ISSUE THREAD

**Issue by SECBATON-GRIFFON** [d3athrow/vgstation13#36386]
[bugfix][consistency]

#### Description of issue
using food or drink in hand consumes it without delay, while clicking yourself with it does. making an issue instead of fixing it because i don't know if people don't like the delay

#### Difference between expected and actual behavior
delays for both

#### Steps to reproduce
z hotkey for former, click self for latter

#### Specific information for locating
attack_self

#### Server revision
9ef6ed0b1150b989ef04755459d4313d34bef47a

**Comment by DeityLink** [comment]
I can assure you that people don't like the delay and I myself always use the keybind to quickly down food. If I want to eat slowly I'll use a fork. Some may argue that learning the most efficient way of eating food is part of the learning process of spess but there is also value in behaviours being more consistent across the board so removing the delay when clicking yourself seems like a viable option.

**Comment by hacker-on-steroids** [comment]
#15962

**Comment by Theophrastus1** [comment]
the duality of man

**Comment by SECBATON-GRIFFON** [comment]
goofball ideas need not apply after all
