### ISSUE TITLE
Could not stop being blind

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36409]
(WEB REPORT BY: dacendeth REMOTE: 172.93.101.77:7777)
# Revision
3b1de8b1f91875659fabd0ecdac26090440de326

# Description
I welded too much, I took eye meds, rye, alky, all the things that could account for blindness and nothing fixed it
# Steps to Reproduce
Weld too much, possibly as a plasmaman?
# What you Expected
To be able to see again when my eye damage hit 0
# What Actually Happened
The blurry thing went away but the giant black overlay did not and I could not inspect anything or see further than my tile.

**Comment by Dacendeth** [comment]
highly likely this was related to the server taking a shit that round, many things seemed fucky including the shuttle not working right.

**Comment by jwhitak** [comment]
Closed at request of Dacendeth.
