### ISSUE TITLE
Pulse demon escaping from a cage is cursed

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#36410]
#### Description of issue

>remove floor tiles to access wiring
>pick up pulse demon
>place in cage
>pulse demon jumps to nearby wire
>pulse demon seems unable to move from that new tile
>can't pick it up
the pulse demon then detonated and EMP'd the area
>go to retrieve crate
>can't pick it up
>click it
>chat window is printing messages about picking up the pulse demon

it looks like it wasn't a player-controlled pulse demon

#### Difference between expected and actual behavior

pulse demon shouldn't shift into the fifth dimension just because it got caged

[bugfix]

**Comment by SECBATON-GRIFFON** [comment]
i think it's finally time to patch out letting them be caged
maybe someone could code a "faraday" subtype of those animal cages that keep them in, made in research out of uranium or something i don't know

**Comment by hacker-on-steroids** [comment]
did you try bumping the cage around after he jumped out? 
cages are fucked in general, #35042 sort of related
