### ISSUE TITLE
STATION TIME IS BROKEN

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36417]
(WEB REPORT BY: angryturnip REMOTE: 172.93.101.77:7777)
# Revision
d4972dc7f07a152012893dab931d6b5c5ddc1d74

# Description
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# Steps to Reproduce
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# What you Expected
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
# What Actually Happened
Station Time: 12:3

**Comment by Inorien** [comment]
what the **FUCK**
