### ISSUE TITLE
Lobby screen player count is WRONG

### ISSUE THREAD

**Issue by Inorien** [d3athrow/vgstation13#36419]
#### Description of issue

LOOK

![image](https://github.com/vgstation-coders/vgstation13/assets/16082007/a205e976-88a2-437f-939f-6f108fbbcb32)

>yesterday
>lobby screen
>players: 23
>type who
>total players: 24

pancakemines wasn't showing up in the lobby player list on my screen

[byond] [bugfix]

**Comment by mentgah** [comment]
he was just observing man

**Comment by Inorien** [comment]
in that case wouldn't it show up as (Playing)

**Comment by mentgah** [comment]
if you observe in the lobby you disappear from the list

**Comment by Inorien** [comment]
non-issue then, thanks
