### ISSUE TITLE
drinking any liquid extinguishes cigarettes.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36414]
(WEB REPORT BY: yvvel REMOTE: 172.93.101.77:7777)
# Revision
febb5580f5f3d492db6f15b04aa642ce9f8f8971

# Description
drinking any liquid extinguishes cigarettes.
# Steps to Reproduce
1. smoke
2. drink something while smoking
3. get upset that your cigarette is gone
# What you Expected
it to not fucking extinguish itself
# What Actually Happened
it got extinguished.

**Comment by DeityLink** [comment]
is it truly any liquid? or just not water?
