### ISSUE TITLE
damage overlays on windows look wrong

### ISSUE THREAD

**Issue by nervere** [d3athrow/vgstation13#36421]
#### Description of issue

this damage overlay is supposed to be a damage underlay
https://files.catbox.moe/bdzj6a.png

#### Server revision
22992c947b560656ab2fde9c24eaa1a3136c6f27

**Comment by DeityLink** [comment]
I knew it didn't look like it used to

**Comment by SECBATON-GRIFFON** [comment]
oh wait really? could i get a better before/after image

**Comment by DeityLink** [comment]
![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/6b7f90e1-05f4-4229-aaa1-786c583b3632)
here's a comparison to 1 year ago, back then glass floor also seemingly didn't take visible damage from mechas until it broke

**Comment by DeityLink** [comment]
Also as a test I gave the damage overlay blend_mode = 2 (~~BLEND_MULTIPLY~~ BLEND_ADD) and it looks much nicer, we should use that

![image](https://github.com/vgstation-coders/vgstation13/assets/7573912/bc52c84b-7656-4d11-a4d0-3fb0614bc8c2)

**Comment by SECBATON-GRIFFON** [comment]
> Also as a test I gave the damage overlay blend_mode = 2 (BLEND_MULTIPLY I believe) and it looks much nicer, we should use that
> 
> ![image](https://private-user-images.githubusercontent.com/7573912/326557968-bc52c84b-7656-4d11-a4d0-3fb0614bc8c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MjQxMjEsIm5iZiI6MTcxNDQyMzgyMSwicGF0aCI6Ii83NTczOTEyLzMyNjU1Nzk2OC1iYzUyYzg0Yi03NjU2LTRkMTEtYTRkMC0zZmIwNjE0YmM4YzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMjA1MDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJkYzZlMjlhNThhM2RmZjc0YjM1ZDRmMzkxZmVlZTU3ZDBiMzU2YjMyZTc1NTJiMjc0NzhjOTc5NzgzZmExMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Tzw4m5isoiFSFpEIh1aqb3Yx96YxmbpnnIZolTPWpao)

on the before or after?

**Comment by DeityLink** [comment]
on the before, but I think the overlay was applied on top since I added it to overlays through varedit.

blend_multiply makes the white cracks more visible while the dark parts on the extremities remain dark

**Comment by DeityLink** [comment]
hm, doing the same on the after looks bad on the other hand, what the heck? maybe there was something else going on there
