### ISSUE TITLE
Using a screwdriver on a false walls deletes it

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#36422]
#### Description of issue
Using a screwdriver on a false walls deletes it

#### Difference between expected and actual behavior
Turn false wall into real wall
it vanished into nothingness

#### Steps to reproduce
make false wall, close it, apply screwdriver

#### Specific information for locating

[#36630](https://github.com/vgstation-coders/vgstation13/pull/36330)
@SECBATON-GRIFFON 

#### Length of time in which bug has been known to occur

[#36630](https://github.com/vgstation-coders/vgstation13/pull/36330)

**Comment by jwhitak** [comment]
Fix is related to ``T.ChangeTurf(text2path("/turf/simulated/wall/[reinforced ? "r_wall" : ""]"))``

text2path can't handle ``/turf/simulated/wall/``, that ending / must be removed.
