### ISSUE TITLE
(WEB REPORT BY: nevillbamshoot REMOTE: 198.245.63.50:7777) Vampire Xray Vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3643]
>Xray Vision as a vampire does not work when you have enough blood.

>When I had the amount of blood needed for Xray Vision I expected it to work

>It didn't work

>Steps to reproduce if possible

**Comment by Intigracy** [comment]
Just tested and was working fine. Upon getting the correct blood amount my vision changed.
