### ISSUE TITLE
station holomap doesn't update when haunting a singulo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36439]
(WEB REPORT BY: kanef REMOTE: 172.93.101.77:7777)
# Revision
e40d7ff5d46f43c647b52f6cb51c43688f4eb0f6

# Description
and probably other stuff too (check how atom locking works on it, maybe move vs forcemove etc)

**Comment by DeityLink** [comment]
It's kind of a known issue, but I consider it too minor of a bug for the time that would be spent pinpointing where you'd have to fix it.

**Comment by SECBATON-GRIFFON** [comment]
but i like to know where the singulo ended up without having to close and open it again

**Comment by DeityLink** [comment]
You can update the map by just moving once as a ghost then double clicking the singulo to follow it again.

**Comment by SECBATON-GRIFFON** [comment]
> It's kind of a known issue, but I consider it too minor of a bug for the time that would be spent pinpointing where you'd have to fix it.

wasn't as hard as i thought it'd be
