### ISSUE TITLE
(WEB REPORT BY: greatvalue REMOTE: 198.245.63.50:7777) Book HTML broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3645]
>Revision (Should be above if you're viewing this from ingame!)
0d087120618f6e1516284edc37fe4b3fa94b0a42 

>General description of the issue
Can't use HTML to write new books

>What you expected to happen
Books are formatted correctly according to html

>What actually happened
the html code appears on paper

>Steps to reproduce if possible
Try to write a book

**Comment by Probe1** [comment]
from what I hear, @ririchiyo 'fixed' it but now no one knows how it works.

**Comment by clusterfack** [comment]
Did pomf's papercode fixes fix this as well?

**Comment by clusterfack** [comment]
Wow, old and irrelevant.
