### ISSUE TITLE
Smarter mouse opacity

### ISSUE THREAD

**Issue by kilozombie** [d3athrow/vgstation13#36454]
![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/f3989abc-22c8-4eaa-9c3e-56501bb686c2)
Let's take this image as an example. These are airshields, which block airflow on a whole tile and are pretty incredible for building projects. Unfortunately, because they are an overlay, they actually make it impossible to easily click on objects below. There are several objects and tiles like this--big fully-enclosing objects which block your mouse despite being transparent. Water tiles are another example.

Well, what we can do is turn their `mouse_opacity` to `0`, which makes it so that your mouse *always* ignores them. This means you can click on the objects below, and the turf below. However, you *can't* click on the airshield itself, nor can you mouse over it to see what it even is.

So this seems like a problem without a perfect solution, right? Either we can't click on anything below the overlay, or we can't click on the overlay at all. Barring right clicks and alt clicks to see what's on the tile, of course.

What if there was a more sophisticated system for mouse opacity? 

For instance, we could make only the outside of the airshield's sprite have mouse opacity, since that's the part that isn't actually *transparent*.

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/944ab0c4-6b8d-48ca-8915-f4382365596b)

We could also dream up an instance where mouse opacity has a priority system. For instance, water tiles overlay over objects to give the impression that the objects are submerged, but that means you can't click on them. If you give the tiles `mouse_opacity 0`, that means you can't even examine the water or click on it. What if your mouse always ignored the tile when aiming at objects or mobs on top of it, but if your mouse goes through everything and only overlaps the tile, you could see that it was water and click on it?

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/f4713e7f-5c4f-43ed-9dea-987a47e60567)

That latter method could work on airshields too--being able to click on the airshield when it only has turf below, but allowing you to click on items below.

![image](https://github.com/vgstation-coders/vgstation13/assets/6062247/c5e80237-d0b1-48b2-8f93-17fdff8a538a)

Here's a final example that always gets my goat. I think that plastic flaps would be a prime candidate to have `mouse_opacity 0` on certain parts of the sprite, so that you can properly trade and put down items in circumstances where they're placed on top of tables. If only the exterior had mouse opacity, it would make moving them around or deconstructing them a little harder, but it would make general use (including crawling under them) really easy.

Thanks for coming to my girthhub talk

[featurerequest] [qol]

**Comment by nervere** [comment]
The answer to the first two problems is overlays with their mouse opacity turned off. The last one doesn't really have a good solution, and it would be better to make a subtype of plastic flaps (or a new item entirely) for traders.

**Comment by jwhitak** [comment]
Mouse opacity has no effect on overlays in my HUD testing, leading to this mess.

**Comment by Exxion** [comment]
You can't change `mouse_opacity` on an overlay, but you can change it for something in `vis_contents`
