### ISSUE TITLE
outpost finder

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36468]
(WEB REPORT BY: leon454 REMOTE: 172.93.101.77:7777)
# Revision
f4e5e26c13de5c2c18adca8a8a44d6a2a1f04a84

# Description
i thought it was a one-off issue but it's been happening consistently. the trader outpost pinpointer does not spawn in the trader's pocket anymore. on late join it just spawns in space
# Steps to Reproduce
latejoin as a trader
# What you Expected
to have the outpost pinpointer
# What Actually Happened
did not have the outpost pinpointer

**Comment by Dacendeth** [comment]
It spawned previously in your hands, I tested a repo I had from april 28th and it worked, and one from may 3rd and it is spawning on the ground instead of in your hand.

**Comment by jwhitak** [comment]
@SECBATON-GRIFFON 

https://github.com/vgstation-coders/vgstation13/blob/f4e5e26c13de5c2c18adca8a8a44d6a2a1f04a84/code/modules/mob/inventory.dm#L223

This line fails if someone is inside of a locker/airbag/etc. Missed it in my review, but here's the problem.
