### ISSUE TITLE
Telekinesis-built Items Teleport to Your Hands

### ISSUE THREAD

**Issue by jwhitak** [d3athrow/vgstation13#36470]
#### Description of issue
When building an item at range using TK, items will still teleport to your hand despite #36469 attempting to fix this.

#### Difference between expected and actual behavior
Expected: items built remain where they are built
Actual: items built teleport to your hand, and the previously held item isn't removed from your TK grasp, forcing you to drop it.

#### Steps to reproduce
1) spawn buildable items, such as brig medic huds or rods+cable coils for a spear
2) grab them at a range with TK
3) attempt to combine them
4) they teleport to your hand

#### Length of time in which bug has been known to occur

A long time but the latest PR didn't fix it.

**Comment by jwhitak** [comment]
Calling @SECBATON-GRIFFON again...

**Comment by SECBATON-GRIFFON** [comment]
i swore they worked when i tested them, but at the same time i'm finding a few i didn't quite catch. dunno what to make of it
