### ISSUE TITLE
Blob weak as heck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36480]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
17bf3cc12865d3c92a8b510bdc8f828e79b0834d

# Description
played as blob several times now, and it's so weak and I have to click so fast I've getting carpal tunnel. needs a serious rebalance
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by angryturnip** [comment]
I won the last time I played blob. Skill issue

**Comment by kilozombie** [comment]
Not a bug

**Comment by Theophrastus1** [comment]
it should be, everyone unfairly treats blob...

**Comment by west3436** [comment]
Low-quality issue report; please provide more specific details on the issue and resubmit.
