### ISSUE TITLE
Join game shift duration timer uses decimals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36488]
(WEB REPORT BY: crazyamphibian REMOTE: 172.93.101.77:7777)
# Revision
e8e4deae45e78a2e53bcff57ae1109be49343452

# Description
muh integers

# Steps to Reproduce
step 1: log in
step 2: press join game
step 3: see the decimal

# What you Expected
no decimal

# What Actually Happened
decimal, VG is so over

**Comment by SonixApache** [comment]
@nervere 
![4VJqT10c2p](https://github.com/vgstation-coders/vgstation13/assets/8468269/e201b5a5-67b6-4ae3-995e-6fc60f934f04)
