### ISSUE TITLE
horrorform gets nullspaced if inside a container

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36483]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
17bf3cc12865d3c92a8b510bdc8f828e79b0834d

# Description
hid in disposals when as horrorform
# Steps to Reproduce
horrorform in disposals
# What you Expected
to transform back into human after 2 minutes
# What Actually Happened
no body. gone and dead

**Comment by SECBATON-GRIFFON** [comment]
ling lost
