### ISSUE TITLE
(WEB REPORT BY: gamblorez REMOTE: 198.245.63.50:7777) Captains uniform Jacket

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3648]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When I put on the jacket it gets rid of the jumpsuit sprite and makes me look naked underneath the jacket. It also removes the jumpsuit from the examine text.

>What you expected to happen
Well I mean, I wanted the jacket to go on top of my jumpsuit.

>What actually happened
See above

>Steps to reproduce if possible
see above?

**Comment by ComicIronic** [comment]
Hide flags issue.
