### ISSUE TITLE
Any room with carpet spontaneously combusts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36504]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
434ac40c7ae7dce482c5ee30020eb76db1ea1775

# Description
Any sparks can instantly light all carpet on fire
# Steps to Reproduce
You can use telescience to just light every room with carpet on fire

# What you Expected
Just a normal day using telescience
# What Actually Happened
Hell on the station

**Comment by SECBATON-GRIFFON** [comment]
nt needs to do asbestos removals
