### ISSUE TITLE
Can't steal DNA of dead crew and gone crew

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36533]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
07d7864f024ef5f06ad5f1e207f9c1a66764cc4b

# Description
In the past you could absorb dead and gone crew (but not monkeymen)
# Steps to Reproduce
try absorbing a corpse of someone who is MIF
# What you Expected
absorb dead crew bodies
# What Actually Happened
have to absorb crew that can be revived

**Comment by kilozombie** [comment]
Adam requested this closed, it was apparently a misunderstanding

**Comment by Eneocho** [comment]
> Adam requested this closed, it was apparently a misunderstanding

closing, then
