### ISSUE TITLE
(WEB REPORT BY: tersr REMOTE: 198.245.63.50:7777) Mensons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3653]
>Revision (Should be above if you're viewing this from ingame!)
0d087120618f6e1516284edc37fe4b3fa94b0a42

>General description of the issue
Mensons in miner lockers and on the entire station are replaced with a no graphic glasses item.

>What you expected to happen
Mensons to exist

>What actually happened
They don't exist and instead are iconless glasses that do nothing

>Steps to reproduce if possible
I did nothing, this is just what happened.

**Comment by ComicIronic** [comment]
Fixed by #3654.
