### ISSUE TITLE
Fire feature requests

### ISSUE THREAD

**Issue by west3436** [d3athrow/vgstation13#36542]
Making a list here since I have no access to Projects. List of planned additional features for fire after all major bugs have been addressed:
- [ ] Firebot: Fire helmet + manipulator + extinguisher + power cell. Paths to and puts out fires in its area. Sprays welding fuel if emagged.
- [ ] Extinguisher types: Class A/B/C/K extinguishers to be used with different fire types.
- [x] Autonomous Supression System (A.S.S.): Science upgrade which can be installed on fire alarms to surpress all fires in a room.
- [x] Air Alarm Fire Supression Mode: Air alarm mode which disables vents while scrubbing oxygen if a fire is detected; default OFF at roundstart.
- [ ] Manual ignition: Using a hot object on a flammable object can ignite it after a do_after.
- [ ] Random fire event: a random flammable item on the station ignites.
- [ ] Cryotheum fire??

Comment with any thoughts on the above or suggestions of your own.

**Comment by Dacendeth** [comment]
Tackling someone who is on fire having a chance to put them out or make you on fire as well on a failure

**Comment by Eneocho** [comment]
cryotheum fires should be anomalous and cool down the room instead, so now you have to set off a regular fire to compensate
also, there was someone complaining that you can't mop away the ash from burns, so maybe add that?

**Comment by SonixApache** [comment]
turn the 'sprays welding fuel' bit into 'sprays foam' so that it over-cools rooms and makes them celtic deathtraps instead

**Comment by Blithering** [comment]
Maybe have the emagged firebot spray whatever you put in it's extinguisher, like an emagged medibot beaker, and have it consider all flammable objects as on fire all the time.

**Comment by SonixApache** [comment]
take inspiration from rimworld's firefoam for your suppression ideas
different class fires/extinguishers sound like a pain in the ass to code and deal with with very little gain

**Comment by west3436** [comment]
> take inspiration from rimworld's firefoam for your suppression ideas 

I had thought about this before and it sounds like a fun idea; plus it gives Science something else to print for Engineering.


> different class fires/extinguishers sound like a pain in the ass to code and deal with with very little gain

I let lots of hooks in the system keeping this idea in mind so it wouldn't be hard to code but yeah it could cause some pain which I'm trying to avoid. The main thing I've had in mind for this is the deep fryer catching on fire since water's not gonna help, but I can just force people to use foam extinguishers on it or something if I ever implement it.

**Comment by Blithering** [comment]
Have you got a sprite for firebot yet? If not I could give it a go.

**Comment by west3436** [comment]
> Have you got a sprite for firebot yet? If not I could give it a go.

I do not; that'd be greatly appreciated!

**Comment by SonixApache** [comment]
just lift the paramedic sprite from rimworld while we're at it
