### ISSUE TITLE
Can't extinguish bookcases

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36559]
(WEB REPORT BY: west3436 REMOTE: 172.93.101.77:7777)
# Revision
10e39a564e4da9f39b06f8d6e28e7449561daae0

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Inorien** [comment]
also easels and paintings (object)
I noticed that burning items didn't extinguish when just sitting in space, this would be a nice feature and make sense given no oxygen
