### ISSUE TITLE
Shrapnel

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36577]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
31ffcfd9eccf65c62f6cc49e36e8d2b74d0f5d28

# Description
I died from shrapnel from 22 tiles away. I guess it's possible irl, but is it fun? I have no idea why this is possible
# Steps to Reproduce
fire RPGs from space into the station
# What you Expected
not dying instantly
# What Actually Happened
died instantly

**Comment by clownisrogue** [comment]
skill issue

**Comment by nervere** [comment]
not a bug

**Comment by SECBATON-GRIFFON** [comment]
this is never getting fixed sorry, consensus seems to be that

**Comment by west3436** [comment]
We've tried to change shrapnel several times to no avail. Regardless, this is a duplicate of #24936.
