### ISSUE TITLE
Welding Fuel won't light.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36589]
(WEB REPORT BY: germansanta REMOTE: 172.93.101.77:7777)
# Revision
5e90694c61feea7ee115593004b275f8db20fd09

# Description. 

# Steps to Reproduce

1.Put welding fuel on the floor.
2. Put fire over it. Nothing happens.

# What you Expected

Fire

# What Actually Happened

Nothing

**Comment by west3436** [comment]
Need more context here. How were you trying to light the welder fuel? Was the tile recently sprayed with a fire extinguisher?

**Comment by west3436** [comment]
Follow up with GermanSanta on Discord - he attempted to ignite welding fuel with a lit welder and didn't have any success after 20 seconds. It's a 1% chance per second to ignite something with a welding tool and testing confirmed it still works, so he was just unlucky.
