### ISSUE TITLE
(WEB REPORT BY: galaxygryphon REMOTE: 198.245.63.50:7777) Radios fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3659]
>Revision (Should be above if you're viewing this from ingame!)
6c7ecf57508cfcefefc1616f05e4f6265420b427 

>General description of the issue

radios seem to not have the ability to talk over anything but common

>What you expected to happen
to be able to communicate with my department

>What actually happened
everything is gteen

>Steps to reproduce if possible

"say :S hey guys"

**Comment by ComicIronic** [comment]
Duplicate of #3652.
