### ISSUE TITLE
Booze-o-mat and Jukebox from Ghetto Bar not working in other rooms

### ISSUE THREAD

**Issue by Skullyton** [d3athrow/vgstation13#3663]
I was told to submit an Issue statement by Celt, so here it goes.

After being asked by the QM to 'grab us some drinks' I went on a raid on the Ghetto Bar, grabbed the jukebox and Booze-o-mat, and took them to cargo store room.

I then wrenched them down, and they still remained off.

I tried in the lobby, the office, and the main large room and still nothing.

The way it was fixed was by turning the APC off and back on, Celt told me to make an issue statement on it, and now we're here.

**Comment by Probe1** [comment]
I've had a couple people ask me about this in the last few weeks.  I think it comes from the apc the booze-o-mat is originally tied to (ghetto bar) being shut off at the time it is moved and the check to see if its in a currently powered area fails.  Just a guess.

**Comment by AutismSpider** [comment]
Got power the apc so the juke box and booze o mat turns on.(ghetto bar)

or pull them into room with power and ask the AI or cyborg turn the apc on and off.

**Comment by ComicIronic** [comment]
I'll see what can be done about making machines re-link to APCs once they get wrenched down.
