### ISSUE TITLE
can eat without hands, but not without arms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36649]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
60861a421750069bb5bd1ba4e72c55d0294f8cae

# Description
re #36648 you can eat without hands, but not without arms AND hands. You can also drag and interact with machines
# Steps to Reproduce
no hands
# What you Expected
act like no arms
# What Actually Happened
can eat with no hands

[inconsistency]

**Comment by Dacendeth** [comment]
https://github.com/vgstation-coders/vgstation13/assets/26881007/bb563c18-f99f-4c1b-a6b2-97e887adb14d

Also tested with arms but no hands just because your issue report was confusing, that also worked.

**Comment by west3436** [comment]
Looks like it's another skill issue.
