### ISSUE TITLE
Can't vv animals into large crates like you can with objects

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36646]
(WEB REPORT BY: sacredatom REMOTE: 172.93.101.77:7777)
# Revision
60861a421750069bb5bd1ba4e72c55d0294f8cae

# Description
If you vv an animal/mob into a large crate, via marked datum to contents, the mob will disappear upon after opening the crate with a crowbar. Unlike if you were to vv a random object like a jukebox into said crate, it would not disappear upon open

# What you Expected
Animal to plop out
# What Actually Happened
voided the poor beast

**Comment by Eneocho** [comment]
I believe large crates just call for the mobs to be created on the crate opening call, and the mobs were never there until you opened the crate. And according to the thing, it would also work like this for machinery, the anomaly container isn't on the crate until you pop it open.
https://github.com/vgstation-coders/vgstation13/blob/60861a421750069bb5bd1ba4e72c55d0294f8cae/code/game/objects/structures/crates_lockers/largecrate.dm#L50-L57

**Comment by Exxion** [comment]
https://github.com/vgstation-coders/vgstation13/blob/60861a421750069bb5bd1ba4e72c55d0294f8cae/code/game/objects/structures/crates_lockers/largecrate.dm#L17
It only dumps `/obj`s when opened. This can be fixed easily by just changing this type to `/atom/movable`
