### ISSUE TITLE
can't eat without hands

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36648]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
60861a421750069bb5bd1ba4e72c55d0294f8cae

# Description
try help, harm, etc to bite food without arms... Can't eat without hands
# Steps to Reproduce
have no arms
# What you Expected
eat
# What Actually Happened
no eat

**Comment by angryturnip** [comment]
Don't think this is a bug, but it would be a neat feature addition to be able to eat food directly on bite intent

**Comment by hacker-on-steroids** [comment]
unable to reproduce?
use bite+harm intent

![image](https://github.com/vgstation-coders/vgstation13/assets/159179330/adebf4ad-7afd-42af-b034-87d2ecb3862c)

**Comment by west3436** [comment]
The bug, allegedly, is that you can't eat without arms as you can eat without hands. I'll keep #36649 open until I can test it, but this one is a duplicate/skill issue
