### ISSUE TITLE
Exotic artifacts ideas

### ISSUE THREAD

**Issue by joaomarcosh** [d3athrow/vgstation13#36657]
[discussion]

Current xenoarch sucks because the random artifacts effects sucks so i need ideas of what new effects to add.

**Comment by angryturnip** [comment]
Peggify aura

**Comment by Eneocho** [comment]
In practice, most effects will be so niche as to be pointless.
Having said that:
-Forced species effect that takes the species sample of the last person to touch it while inactive and forces everyone within the radius to that species.
-Universal Translator that will translate everything to a universally understandable language (like how borgs will be understandable to any species). Either by itself if it hears a message in a non-galcom language or being wrenchable on top of the telecomms receiver so all messages are translated.
-Pseudo language teaching, such that you can speak any language but only if you're within its effect radius.
-Slowly fills all nearby containers (including mobs) with a random reagent. 3 Variants, one that adds a good reagent (like peptobismol), one that adds a neutral reagent (salt) and one that adds bad reagents (toxin, acids, etc).
-Pouring a reagent on top of it will duplicate it, comes with an alien beaker already that must be removed to access the duplicate chems.
-Resonates if smashed against supermatter, equal to 3 SM splinters.
-Forced hostility within its area of influence (can't exit harm mode).
-Forced pacifism within its area of influence (chill wax bro).
-Randomized stats like phazon salts (including the recolor).
-Turns your sprite upside down on exposure. Effect lasts until the next exposure, which would flip you back to normal. 
-All tiles within its area of influence get lubed.
-All mobs within its area of influence get injected with colorful reagent and smoke, constantly.
-Activates 3 good genes at random then refuses to function for (You). Can be used by multiple people to map out all the good genes.
-Ditto, but only bad genes.
-Changes your ID and clothing to another job and that job to yours. So a clown touches it and turns into a seccie (still clumsy) and a seccie touches it and turns into a clown (not clumsy).
-Reverse force field that can be entered but not exited.
-Edge airshield, all tiles at the "edge" of the area of effect are airshielded.
-Area airshield, ALL tiles within the area of effect are airshielded.
-Just blast cannons in the opposite direction of the guy activating it, potency of the blasts decided at spawn.
-Stuns any and all people that approach with access that matches/doesn't match the last ID scanned.
-Constant time reversal effect within its area. Fires once a minute.
-Instantly heals all fractures but burns the limb.
-Refills all gas containers nearby to their maximum regular pressure rating (so an almost empty gas tank in your belt refills to 1013kpa).

**Comment by Blithering** [comment]
I think the issue of random artifact effects being bad can't be fixed by throwing in more, I'd say first step should be to move some effects to fixed artifacts so the pool is smaller and people are more likely to know what they're getting.
