### ISSUE TITLE
RnD Console Is of the Shit Fucked saaaaars.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36653]
(WEB REPORT BY: gekresonn REMOTE: 172.93.101.77:7777)
# Revision
60861a421750069bb5bd1ba4e72c55d0294f8cae

# Description
When trying to open the RnD console with the Circuit Imprinter open, the client will freeze. Opening the Circuit Imprinter from the menu will also do this. This bug, assuming it is not some weird one round only occurence, makes doing science impossible. This is universal and was also experienced by an admin when tested.  
# Steps to Reproduce
Assuming this isn't some one round thing, try to open the Circuit Imprinter; the game client will freeze. 
# What you Expected
For the Circuit Imprinter to function properly. 
# What Actually Happened
I don't know. I'm not autistic enough to now how these things work.

**Comment by Eneocho** [comment]
Cosmos itself conspiring against science. Perhaps we should listen.

**Comment by west3436** [comment]
Unable to replicate in testing. Tagging @SECBATON-GRIFFON since he touched this last in case more info is provided.
