### ISSUE TITLE
Can't bite without arms when character starts without arms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36654]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
d1291bcab300bbe769efcc08fe3f0759201ff24f

# Description
#36649
# Steps to Reproduce
1. start without arms (you have to spawn from the arrivals shuttle). I got the red X on the hands.
2. maybe have a mask on? I don't know
# What you Expected
eat
# What Actually Happened
can't eat or do anything. Harm intent bite does not work

**Comment by Dacendeth** [comment]
You cant bite with masks on, everything that requires you to be able to bite can't be done with a mask on.

**Comment by west3436** [comment]
Once again, it seems that this is a skill issue
