### ISSUE TITLE
make DNA injectors have no delay when injecting yourself

### ISSUE THREAD

**Issue by SECBATON-GRIFFON** [d3athrow/vgstation13#36666]
[featurerequest][consistency]
it works like this with regular injectors, thats why... it also makes testing powers a lot faster.

**Comment by boy2mantwicethefam** [comment]
I tried.
#25379 
I could try again.

**Comment by SECBATON-GRIFFON** [comment]
nah its fine i had a small hunch itd have a lack of support anyways
