### ISSUE TITLE
bullets from guns point blank can "narrowly miss"

### ISSUE THREAD

**Issue by SECBATON-GRIFFON** [d3athrow/vgstation13#36665]
[oversight]

#### Difference between expected and actual behavior
an exception if it's like this

#### Steps to reproduce
harm intent, shoot something adjacent

#### Specific information for locating
/obj/item/weapon/gun

#### Length of time in which bug has been known to occur
as long as narrowly missing bullets have been a thing

#### Server revision
10e71ac9703a98168ae36ca4de499aa6059e27f6

**Comment by Dacendeth** [comment]
Just pretend its an xcom reference

**Comment by SECBATON-GRIFFON** [comment]
> Just pretend its an xcom reference

well, we do have the guns from it

**Comment by SacredAtom** [comment]
Just dont miss bro
