### ISSUE TITLE
FIRE FIRE BURNS MUCH BRIGHTER

### ISSUE THREAD

**Issue by hacker-on-steroids** [d3athrow/vgstation13#36667]
WHEN VACUUM IS THE SUPPLIER
![image](https://github.com/vgstation-coders/vgstation13/assets/159179330/d22b8605-95a7-42a2-b585-1374373117f8)

**Comment by west3436** [comment]
Fire can burn in a vacuum if it is supplied with oxygen and fuel (how do you think rocket engines work?). That being said, it looks weird in a zone-based system like ours since there's just 0.7mol of oxygen in that entire zone yet plenty of fire. I can out a lower limit on oxy mols I guess.

**Comment by hacker-on-steroids** [comment]
here's a second pic with even less air
![image](https://github.com/vgstation-coders/vgstation13/assets/159179330/84b2462d-fe2c-45a6-a9dc-07acdfac80ef)
don't think stuff would actually burn at such low pressures but have no proof whatsoever
i'd need a vacuum burn chamber and tanks of n2, co2 and oxygen in the garage to test this shit myself because all the low-pressure burning research i've seen so far came to different conclusions

**Comment by west3436** [comment]
> here's a second pic with even less air ![image](https://private-user-images.githubusercontent.com/159179330/339011548-84b2462d-fe2c-45a6-a9dc-07acdfac80ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDQ1MjIsIm5iZiI6MTcxODIwNDIyMiwicGF0aCI6Ii8xNTkxNzkzMzAvMzM5MDExNTQ4LTg0YjI0NjJkLWZlMmMtNDVhNi1hOWRjLTA3YWNkZmFjODBlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQxNDU3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDk0YjA1NGM1YzRlZjkyMjljZTdlY2YzMmJmNmY5YTcwZDY2NmYzYWFmYTA0ZTNmYTBiZWUzZmEwMzFmNjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9qAXRhd8WpAQuK-7U0-OObkIWd12Asn33ujq_3zhj78) don't think stuff would actually burn at such low pressures but have no proof whatsoever i'd need a vacuum burn chamber and tanks of n2, co2 and oxygen in the garage to test this shit myself because all the low-pressure burning research i've seen so far came to different conclusions

_Pressure_ isn't important; the number of mols available to burn is. Zone-based atmos makes this weird but I've got an evil PR cooking up which will interpolate the number of mols of oxygen per tile and will extinguish fires if that value is below 1.
