### ISSUE TITLE
where singularity

### ISSUE THREAD

**Issue by cloutcode** [d3athrow/vgstation13#36674]
where
![dreamseeker_yxENTtc9TB](https://github.com/vgstation-coders/vgstation13/assets/51810865/75aab95c-2536-4a09-aeac-ab30fc3ba342)
![dreamseeker_wuSRKHJaYE](https://github.com/vgstation-coders/vgstation13/assets/51810865/a7061b8c-9152-4b2e-867c-2b1d3f26409a)
![dreamseeker_WzsOTIa5jh](https://github.com/vgstation-coders/vgstation13/assets/51810865/24ddef69-b303-4aea-b12a-e01d78ba6987)
![dreamseeker_BfJGanRoHa](https://github.com/vgstation-coders/vgstation13/assets/51810865/408ed502-aaad-4b9c-8ea8-77c4ffb3064c)

**Comment by west3436** [comment]
@SECBATON-GRIFFON re: #36219

**Comment by Eneocho** [comment]
the ultimate covert bagulo
you store the bag in the bag
you get to the shuttle
you take the bag out of the bag
you put it into the bag
singulo
???
