### ISSUE TITLE
Bhangmeter Doesn't Seem to Register Toxins Test Site

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3667]
In the bhangmeter's map screen, I've seen stuff like meteor impacts recorded before, and when I test bombs the bhangmeter announces the location and intensity, but I've never been able to view past explosions that happened in the Toxins Test Site using the bhangmeter. They're totally absent from both the map and the list.

**Comment by d3athrow** [comment]
Works for me ![toxins yes](http://i.imgur.com/SFXBpdt.png)
