### ISSUE TITLE
(WEB REPORT BY: 2edgy REMOTE: 198.245.63.50:7777) Dissapeared

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3668]
1b832866d36c61bc5abe8fcb59d54d9ec4e10586
Was running around surgery, ran into a person who was about to enter Body Scanner and i suddenly got dragged into the Body Scanner tile and dissapeared

Not dissapearing

Dissapeared

Reffer to issue description

**Comment by dylanstrategie** [comment]
If you somehow manage to get shoved into body scanners in quick enough succession that you dodge sanity checks, you end up in the body's scanners REAL contents, aka inside the body scanner but not in the scanning unit

Best fix is to ask an admin

**Comment by 9600bauds** [comment]
Added some sanity for these cases
