### ISSUE TITLE
Golems start with no gravity?

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3670]
Spawn a golem
Watch as they start to complain that they cant move
Seems the only way for them to walk on their own is to stimulate walking
The ingame fix is to drag the golem behind you and have him mimic the movements you make as he walks (You are pulling him up he holds down the :arrow_up: key)
When it fixes a message appears to the golem with just "Gravity!"
Then golem falls over and can walk.
It baffles me.

**Comment by dylanstrategie** [comment]
Most likely oldcode

**Comment by NigglyWiggly** [comment]
Just claim you have to teach the golems how to walk and pass it off as a feature!

**Comment by ComicIronic** [comment]
The message is caused by the thump() proc, which happens whenever the area undergoes a gravity change.

I think this is caused by the mob not entering the area where it spawns properly, and so not getting gravity properly.
