### ISSUE TITLE
Clowncart can hold infinite alcohol

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36708]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
05e5fe4b1316c513157d0c690940cc63b0a0e41a

# Description
240 units of B-52

140 units of Changeling Sting

60 units of Latte

30 units of Creamy Hot Chocolate

125 units of Beer

50 units of Pan-Galactic Gargle Blaster

5 units of Slime Jelly

50 units of White Russian

45 units of Black Russian

20 units of Apple Juice

30 units of Irish Car Bomb

400 units of Vodka

2701 units of Banana Juice

300 units of Whiskey

200 units of Rum

100 units of Gin
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by angryturnip** [comment]
Those finite amounts sure don't look infinite to me

**Comment by west3436** [comment]
Not sure what the bug is here so please try again with more information

**Comment by boy2mantwicethefam** [comment]
The clown cart has a limit of 5000 reagent units.
