### ISSUE TITLE
ieds disappear when making them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36726]
(WEB REPORT BY: pulserider REMOTE: 172.93.101.77:7777)
# Revision
a800ca4ae2a2f540eff77aacebf26da3bd0efdcd

# Description
i put an igniter in a can of soda, it just disappears, stops existing
# Steps to Reproduce
buy a soda
open it
stuff an igniter in it
it's gone
# What you Expected
to be able to make an IED
# What Actually Happened
oops! no ied!

**Comment by jwhitak** [comment]
Reproducable by attempting to make an IED on the ground. If it's in hands, it works. If it's on the ground, it fails. @SECBATON-GRIFFON

**Comment by hacker-on-steroids** [comment]
i'd expect the exact opposite - packagewrap for example doesn't work on held items but works in backpacks/the ground
