### ISSUE TITLE
Landmark human mobs process life()

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3674]
The three clowns, the clown pilot, and the dead russian at the nukeops base all process life() ticks. Which is just fantastic because they are all in 0 atmosphere environments and thus go through handle_environment() and organ/create_wounds(), procs which are currently a chain of the most cpu abusive processing procs in the game.

If someone could point out where in the code the landmarks for these mobs are defined we can take them out of the mob lists so they don't bother processing.

**Comment by PJB3005** [comment]
don't these landmarks simply spawn clown gear-equipped corpses? fixing this would probably involve making life() cancelable on certain mobs(if it can't already be done)

**Comment by clusterfack** [comment]
You can already stop mobs from doing their form of "process()" which is life() for mobs just by removing them from the mob list, which is the list of all mobs that need processing that is gone through every tick. The same could be done for any processing object if you find their appropriate list (I'm moving each list inside the file with the process it is used by in one of my recent pulls)
