### ISSUE TITLE
Grinding wheat yields no flour

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36760]
(WEB REPORT BY: corncolonel145 REMOTE: 172.93.101.77:7777)
# Revision
dab5527b35bfa6ef8393f1789cb7896fcbf2dc6a

# Description
Grinding wheat in an all purpose grinder never yields wheat.
# Steps to Reproduce
Grind wheat
# What you Expected
Some flour to be produced along with nutriment proportional to plant potency.
#What Actually Happened
Only nutriment is produced.

**Comment by Eneocho** [comment]
@SECBATON-GRIFFON @jwhitak

**Comment by west3436** [comment]
Haven't tested this yet but just to cover all bases - please confirm you didn't modify the wheat beforehand. If you PURGE'd another plant's Phytochemistry into the wheat instead of SPLICE'ing it, this can happen.

**Comment by jwhitak** [comment]
With #36761 this is technically closed
