### ISSUE TITLE
Powers refuse to leave the body

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#3676]
I wanted to be less ostentatious as a geneticist and didn't want those neon lights that heat resistance comes with, so I injected myself with the unactivated block for it. Nothing happened at first, no new power, no new disability and the lightshow kept on surrounding me, but after what seemed to be a random number of injections to change other blocks the resistance disappeared, red text and all. I still hold true to my theory that block injectors occupy The Cursed Zones of the code and that they cannot be trusted. Possibly the powers have a chance to be disabled, just like they have a chance to manifest. Is there any way for me to add those neat little tag thingies to my issue? Or do I need some sort of fancy permit to do that?

**Comment by Kurfursten** [comment]
@clusterfack Ryetalyn removes powers now, so this one can be clsoed. I think that's what he was asking for, it's kind hard to tell.
