### ISSUE TITLE
Togglable passive not neccessarily beneficial often annoying and hindering genetic powers: a request

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#3677]
Powers like chameleon, cold resistance and farsightedness, especially farsightedness, are not neccessarily benefitial and the possibility of disabling those would help a great deal! Especially since, like I stated in #3676, powers don't go away with a one hundred percent success rate, so identifying which power block has which power is a grand pain in the back.

**Comment by PJB3005** [comment]
I like this, both of the three examples are valid (chameleon is ugly, cold resist breaks cryo, and farsightedness is VERY UGLY)
