### ISSUE TITLE
[Discussion/Ideas] New botany mutation system?

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3678]
After a combination of personal experience, talk in the thread and IRC, and @Zuhayr's comment in #3216, I became convinced that our current botany mutation system is a bit flawed and in need of a re-doing.
I can try my hand at coding this myself, but first I'm opening a discussion so everyone can contribute with ideas or feedback on how the system should be. I want to sit down and think it through before I start doing anything, and I want to make something balanced and agreeable of course.

-Problems with the current system:
Increasing a specific stat (like Potency or Yield) is extremely time-consuming and random. The chance of getting a positive gain in the specific stat you want is less than 1 in 22, and by the time you get it, other stats of your plant are practically guaranteed to have been heavily altered (more often than not, in a negative way, since there are more possible negative effects than positive ones).
You cannot practically mutate a plant's stats without having it mutate into a different species. You need to have multiple seed backups of the plant, nuke it every time it mutates, and replant. Trying to get high-potency chili is currently one of the most infuriating and time-consuming game experiences possible.
"Crazy" mutations are extremely rare, which really has no reason to be when you consider how available exotic seeds are (and leaves botany with little surprises). In all my time as botanist I have never had a plant randomly mutate into Kudzu. Why? There's a 1 in 11 chance to roll the right category, then a 5-10% check to even roll for kudzu-ing, then a 33% chance to actually become kudzu. This also causes mutations to do nothing a big portion of the time, due to rolling for rare mutation but failing, thus returning nothing.
There is very little difference on how much mutagen you use. The idea kind of is there but the functionality doesn't do it justice. You still get the same types of mutations, only that you get two mutations at the same time sometimes and have a slightly higher chance of the previously mentioned "crazy" mutations (which are still minuscule).
Many traits of exotic seeds aren't obtainable through mutations, making them somewhat mandatory. That is, without counting how hard it is to mutate the ones that /are/ obtainable.

-Proposed new system:
Have three different mutation possibility lists, to be used dependent on how much mutagen is used. Through careful dosage of mutagen, a botanist can mutate their plants based on what they want.

-When small amounts of mutagen are used:
Have negative effects from mutations not be permanent stat loss, but rather, effects a botanist can deal with and don't require autismal amounts of plantbgone+replant. Examples: Add toxin damage to the plant so that it requires antitox/cryo, make it suddenly grow weeds/get pests, make it unable to produce fruits for a little while, etc. In return, beneficial effects are mild stat gain and the plant can't mutate species or do anything crazy.
The idea is to allow a gradual and reliable way to improve a practical-use plant, as well as a way to do so without accidentally mutating it's species.

-When medium amounts of mutagen are used:
Have mutations work similarly to what they work like currently, but rework the rarer mutations to be part of a weighed list so that they don't cause the plant to do nothing when the roll fails (as well as increase their chances a little). Maybe to make mutations more interesting, job dependencies with other departments could be added, such as slime extracts allowing you to guarantee mutations of a certain type, or diethylamine/plasma/whatever increasing your chances of success.

-When large amounts of mutagen are used:
Clearly the user is past the need of high yield wheat and is instead answering to the call of mad scientists. Currently, weird&alien plants are easily obtained through exotic seeds, so there's little reason to keep weird&alien mutations rare. I think a punishment->reward scheme would be !!FUN!! and reward sticking to the same plant rather than replanting, where instead of having said mutations be a set chance, your plant has to go through a period of adaptation to mutagen where you have to deal with a couple of bad effects before guaranteed "good" ones.
That said, nuke the everloping shit out of their plant. Give it massive gradual toxic damage, have it spawn spiderlings if the tray is not de-pested quickly, give it plant cancer. Have the botanist require all their tools at hand and react quickly. Then, if the plant is still alive, dump another big dose of mutagen and it will start glowing or become extremely carnivorous or breathe plasma or something. Whether that cycle repeats after each good mutation or you can easily get a shitton of weird mutations depends on what people think the availability of those effects should be.

-Other stuff:
Fertilizers will make a comeback, right now none of them work.
I'm planning on re-adding Koibeans, Moonflowers and Ghost chili, since they got taken out when Baybotany got ported. I might steal I mean port over tobacco or some other /tg/ plant as well, obviously making sure I don't rape the licensing and blow up the repo and go to jail.
The Floral Somatoray will be locked to the equivalent of a small dose of mutagen, but can be emagged to work as bigger doses. I'd like to make their "increase yield" option actually mutate the plant's yield stat rather than work as plant-b-gone, but we'll see how that speaks about balance.

-Stuff to Solve and Discuss:
How should mutations on fertilizers work? EZ-Nutriment used to mutate your plant once when harvesting it, Left 4 Zed used to mutate it twice at the cost of producing no fruits for 1 cycle. Should the default nutriment cause mutations (thus making them unavoidable)? Should mutations from these fertilizers allow for negative effects (given them being extremely slow-acting)?
How easily available should "crazy" mutations be, given that they're not very beneficial? What about adding chemicals to plants through mutations, so that exotic seeds crates aren't as mandatory?
Should the Somatoray's yield function act as instant-robustharvest and increase your yield for one harvesting cycle, or should it cause yield stat mutations instead?
What possible negative effects could be added to mutations?
Should Kudzu be touched to act more like Bay's, or left as-is?

**Comment by DrLeprikon** [comment]
I'm absolutely no good at botany, but this sounds good! Kudzu works fine as is, as today's kudzu round has shown, there should be one fertilizer that's won't mutate your plants and I love the idea of the somatoray increasing the yield stat! Adding some negative mutations that could put the botanist in danger would be nice: "A bulging sickly-looking sack has grown on Blue-space tomatoe!" "The sack on Blue-space tomatoe bursts open and a dark green gas leaks out!" "You inhale the toxic gas!" for example, or maybe a fruit could fall off a plant's branch and squash on impact with the floor and activate any special ability the fruit might have or release its chemicals. Mutating blue-space tomatoes could lead to being teleported to a random beacon accidentally, Death Nettles could drop their leaves and get damaged by the acid that spills, Egg-plant could randomly produce a chick because one of the eggs hit the floor and split apart and so on.

**Comment by Zuhayr** [comment]
http://vignette4.wikia.nocookie.net/dragcave/images/7/7f/I-am-monitoring-this-thread.jpg

Couple of PRs regarding Bay xenoflora which may be of interest:
https://github.com/Baystation12/Baystation12/pull/8567
https://github.com/Baystation12/Baystation12/pull/8038

**Comment by Probe1** [comment]
I agreed with the idea in irc and am stating I agree with this here.  I agree.

**Comment by 9600bauds** [comment]
If anyone's wondering what became of this, I've been working on and off but had a little (a lot) of issues with git and trying to rebase due to ten thousand conflicts from the spanpocalypse and dropitem changes, and me being a dumbass and moving stuff to new files. It's pretty much unsalvageable at this point, I'll try again after the feature freeze.

**Comment by Probe1** [comment]
That's a shame I was looking forward to it.
