### ISSUE TITLE
Runes and Cult Objects can be planted directly in space

### ISSUE THREAD

**Issue by falcon2346** [d3athrow/vgstation13#36780]
#### Description of issue
As name, you can form runes and create cult objects directly in space. I can't imagine this is intentional
![dreamseeker_EG4YM8slwq](https://github.com/user-attachments/assets/4668e38b-67d9-42ce-b885-d6b82f863645)

#### Difference between expected and actual behavior
Expected: For the cult to at least have to take the time to put down a floor. 
Actual: You can just make everything hidden away in some unfindable corner of Z-1 without any preparation

#### Steps to reproduce
I didn't play this round, I assume you just make the runes as normal.

#### Server revision
Game: 5644ef931cf4dfcd9ae6b15cf38954414a3872f0 
Patches: d8654a220f43623d87abc7fd8669f2ffd17dff57 
Current Infomational Settings: 
BYOND version of server: 515.1620
Protect Authority Roles From Traitor: 1

[Oversight]

**Comment by DeityLink** [comment]
That's cursed
