### ISSUE TITLE
Grue Abilities Would not Work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36812]
(WEB REPORT BY: corncolonel145 REMOTE: 172.93.101.77:7777)
# Revision
b5d6279551342c506888028e710d9fccb4df16ac

# Byond Version
515.1641

# Description
Joined game as grue, managed to down a player, upon trying to eat them eat function would not initiate.  Message would pop up saying "You are already doing something".  Later when trying to evade others Shadow Shunt also displayed the same error and would not function.

# Steps to Reproduce
Unknown I do not know if I did something to bug things out.  I did pull a monkey around but stopped pulling it shortly after.

# What you Expected
To either be able to eat or shadow shunt so I could play Grue.

# What Actually Happened
No abilities functioned after the initial moult.

**Comment by west3436** [comment]
Closed via #36813.
