### ISSUE TITLE
(WEB REPORT BY: greatvalue REMOTE: 198.245.63.50:7777) html - closing brackets not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3684]
>Revision (Should be above if you're viewing this from ingame!)
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

>General description of the issue
closing commands , [ /b], [ /i], etc not working. 

>What you expected to happen
A specific set of text to be bold or italic or centered.

>What actually happened
All of it becoming centered or multiple commands wrecking the format.

>Steps to reproduce if possible
Test out html of books.

(P.S. Thank you so much for making it work again! I'm already formatting books. :] )

**Comment by ComicIronic** [comment]
Wait, is this fixed or isn't it?

**Comment by GreatValue** [comment]
Somewhat fixed. The html doesn't appear on paper anymore, but most commands aren't functional.

**Comment by PJB3005** [comment]
*cough BBcode *cough not HTML

**Comment by 9600bauds** [comment]
Works fine now
