### ISSUE TITLE
Greyshit ID is enough to kick people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36874]
(WEB REPORT BY: kereanil REMOTE: 172.93.101.77:7777)
# Revision
0b6fb6e34800362a6b2ee71dbb014a80f269561b

# Byond Version
515.1642

# Description
Greyshit ID can be used to start up maintenance protocols and eject occupants

# Steps to Reproduce
Use an ID, kick a secoff out of a gygax, no weapons needed

# What you Expected
Not be able to do that

# What Actually Happened
He got kick'd

**Comment by Dacendeth** [comment]
Skill issue, lock your mech properly.

**Comment by west3436** [comment]
Any ID can start maintenance protocols if the mech isn't locked.
