### ISSUE TITLE
(WEB REPORT BY: greatvalue REMOTE: 198.245.63.50:7777) Can't upload to external archive

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3688]
>Revision (Should be above if you're viewing this from ingame!)
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

>General description of the issue
Attempt to upload binded and locally scanned book to external archive. Book shows up, and it even gives an executable confirm or abort option, but no book appears in archive. 

>What you expected to happen
Book uploads to external archive

>What actually happened
Book doesn't.

>Steps to reproduce if possible
Attempt to upload book.

**Comment by Kurfursten** [comment]
@nigglywiggly @d3athrow Did Pomf's library fix months ago fix this?

**Comment by NigglyWiggly** [comment]
From what I can tell, Yep
