### ISSUE TITLE
Spacepod Construction Alternate Screwdivers Interaction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36899]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
The "adjusting wiring" step in spacepod construction doesn't work with the screwsolder set to screw mode, nor with a coin in harm intent. If there are other screwdriver analogues I assume they won't work either.

**Comment by DrSnips** [comment]
Well if anyone wants to tale a crack at it, here's the exact spot in the code that would give it issues.
https://github.com/vgstation-coders/vgstation13/blob/43c624c4e3020c678bfe77e0fdee1878a615c4a2/code/modules/spacepods/construction.dm#L136
