### ISSUE TITLE
Bodybags not in Box Station Robotics

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3690]
I like to move my corpses with black bags instead of shoving them down disposals or bleeding all over the halls

**Comment by ComicIronic** [comment]
Are you sure they're not just under the table by the surgery table where they normally are?

**Comment by Ephx1** [comment]
Unless I'm incredibly blind and have a horrible memory I'm pretty sure they're not there at all.
Also that new mechbay rework map screenshot doesn't have it either, so unless they're using an old map or just removed it for that screenshot, it must be gone.

**Comment by eswordthecat** [comment]
It's under the table it seems, guessing it's a layer issue.

**Comment by Ephx1** [comment]
I didn't even know that was possible. I should have alt clicked, sorry.
