### ISSUE TITLE
[Box] tank storage unit items appear underneath tank storage unit

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3691]
Tank storage units are the containers that hold large oxygen tanks and plasma tanks.  In the case of every single other tank storage unit an item that is removed from it appears on top of the storage unit.  In this single tank storage unit in telecomms, they appear underneath it and you have to either alt click or pixel hunt to find them.

Weird right?

![image](https://cloud.githubusercontent.com/assets/8550416/6955524/cdb55d36-d8ac-11e4-98d6-33dc660e18bc.png)

**Comment by Probe1** [comment]
I've since tried replicated the bug on a test server but it didn't occur.  Recommend someone discretely tries it on the live server.

**Comment by SkowronX** [comment]
Does it have anything to do with the light next to it?

**Comment by Probe1** [comment]
I couldn't tell you, I've only seen it happen twice now and it was accompanied by that bug where if something is underneath a machine and you walk away it suddenly appears on top of the machine.  So from like 6-7 tiles away the plasma tank and o2 tanks were on top but when I got closer they were underneath.  

Dodgy stuff to try and describe, I wish I had a better report.

**Comment by ComicIronic** [comment]
The layerswapping is a Byond bug, but this would seem to be a layer issue as well, and I can't imagine why someone would edit the machine's layer.

**Comment by Probe1** [comment]
Still present.
