### ISSUE TITLE
Engineering Cameras, cameras in general

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36939]
(WEB REPORT BY: adacovsk REMOTE: 172.93.101.77:7777)
# Revision
341909e2198b77354e7d7d1a4c21c1d49dfaf539

# Byond Version
515.1641

# Description
Mappers have to make lists of cameras that are used by specific consoles, for example, the engineering cameras console on Box has no cameras.
# Steps to Reproduce
Look at the Engineering Cameras Console.
# What you Expected
see cameras
# What Actually Happened
no cameras

I'm thinking that the best way to go about this is finding whether the camera is in an area, then on initialization, build the lists of cameras for the consoles. I think this would be much better than having mappers update the list manually.

**Comment by Dacendeth** [comment]
There's nothing wrong here, engineering cameras show only areas where there are engineering problems, and mommis . Here I have bombed atmospherics causing atmospheric alarms to prove this.
![image](https://github.com/user-attachments/assets/aa12d396-3bb0-46c8-92f3-336ac76820ad)

**Comment by hacker-on-steroids** [comment]
the nukie cameras are what's actually broken
