### ISSUE TITLE
Airlock Electronics are no Longer in the Circuit Imprinter

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3693]
According to someone else in the round they used to be, and R&D had maxed research at the time of checking the circuit imprinter.
The only two "airlock" boards in the imprinter were for wall-mounted airlock controls.

**Comment by MercuryDoll** [comment]
Just noticed this too so a bump from here. Needing to steal from engineers is unacceptable (according to MoMMI law, so eh)
