### ISSUE TITLE
Inhands for gold, silver and diamond look weird

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#36941]
![image](https://github.com/user-attachments/assets/6909176a-ad83-4143-a2ba-af5260200f3c) ![image](https://github.com/user-attachments/assets/6c594d7d-ff74-4d82-b68d-56463c273c95) ![image](https://github.com/user-attachments/assets/3e7c1b08-5780-4f10-983e-5e838d969e10) ![image](https://github.com/user-attachments/assets/8332e4d8-84d9-4d9f-81ae-56fd4c574b18)
The gold and silver ones are a bit too high up, the diamond one layers wrong. Bananium is a bit too high too but it's less noticeable.
[sprites]

**Comment by DeityLink** [comment]
Ingots and bananium are meant to look like you're holding them in the palm of your hand, face up.

The diamond one like many other in-hands isn't truncated when in the away-hand while looking sideways so it's easier to identify.

**Comment by Eneocho** [comment]
I guess I can see it.
Still, the diamond looks wrong, it SHOULD be truncated.
