### ISSUE TITLE
Bluespace Crystal Teleporter Functionality

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36957]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
Inserting bluespace crystals into the teleporter doesn't seem to do anything: it certainly doesn't do as the wiki states and allow you to pull from vaults, and it still shows the same "The telepad control console turns on and the lights dim. You can see a faint shape, but it loses focus and the telepad shuts off with a buzz. Perhaps you need more signal strength?" with or without a cystal. This behaviour is the same for artificial, natural, or flawless crystals.

**Comment by Eneocho** [comment]
It lets you pull from /the/ vault, brig and bridge, as those are teleporter blocked, not sure if space vaults are allowed in any scenario.

**Comment by hacker-on-steroids** [comment]
telescience, not teleporter

**Comment by Eneocho** [comment]
that's what I meant, yeah, those three areas are telescience blocked
