### ISSUE TITLE
Odysseus Syringe Gun Not Functioning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#36965]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
The syringe gun can't actually fire syringes - instead, it places them down on the tile adjacent to the mech.

**Comment by SECBATON-GRIFFON** [comment]
turns out it doesnt even fire the syringe projectiles like syringe guns do but uses its own shitcode to step a syringe towards a mob and then transfer reagents. thanks old coders
