### ISSUE TITLE
Wizards can go lmao2⁶⁴fireball!11

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#3697]
Some wizard last round put Velard's button pressing record to shame using fireball at a rate faster than 1.855×10⁴³ Hz. Michael Bay would be proud of him.

Please fix or I call the Task Force 88.

**Comment by ComicIronic** [comment]
You need to be more clear.
Was the spell going on cooldown, had the spell been upgraded at all, did they only have one copy of the spell?

**Comment by wwjnc** [comment]
This is a picture of the habbeningsgs1!: http://i.imgur.com/Hj9ARWb.png (I had no direct LoS because of the sudden lag).

It seems like the wizard was lagging and pressed the spell a gorillion times (are commands queued for sending on the client?), then a bunch of fireball-related messages showed up on the chat, cue ~10 seconds of lag, him and other body being gibbed and loads of fireballs created.

The guy sent this log through deadchat, too: http://puu.sh/gYPwh/27b55cd731.htm

**Comment by ComicIronic** [comment]
Well, that is bizarre. The check on charge should prevent it from being cast immediately, though I did test setting the spell's chargemax to 0 and it does let you stream out fireballs like there's no tomorrow.
If it's just a lag spike, there's nothing much to be done.

**Comment by wwjnc** [comment]
There are some shenanigans happening when a fireball hits a mob and a zombie. It seems to split into two/three fireballs and fun things happen.

I hope someone recorded that spooky shit on the thunderdome, because you'll see clearly what killed the server.

**Comment by AutismSpider** [comment]
It was endless fire ball split  is what kill the wiz man (ball hit the zombie then back to him making it split like crazy)

What crazy the serb was the fire ball hitting zombie and god mode test dummy

**Comment by ComicIronic** [comment]
Oh yeah
I see it now.
