### ISSUE TITLE
(WEB REPORT BY: deadpoolj REMOTE: 198.245.63.50:7777) Fireball can be cast multiple times

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3698]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Fireball was cast multiple times.

>What you expected to happen
To see it cast once, then go on cooldown.

>What actually happened
ONI SOMA times 1000

>Steps to reproduce if possible

**Comment by ComicIronic** [comment]
Was this during a particularly laggy moment?

**Comment by ComicIronic** [comment]
Duplicate of #3697.
