### ISSUE TITLE
Can't add a 7th item into a belt clearly with 7 slots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37003]
(WEB REPORT BY: gamarjoba REMOTE: 172.93.101.77:7777)
# Revision
a10c9feeea80ef52dcdc5bdf851fa871cc44be06

# Byond Version
515.1641

# Description
This was the issue with my botany belt at least.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Belt capacity varies by the size of the objects contained rather than by the number of items inside.
