### ISSUE TITLE
weird disposals/window behaviour

### ISSUE THREAD

**Issue by Eneocho** [d3athrow/vgstation13#37001]
![image](https://github.com/user-attachments/assets/8d571492-b056-4068-900e-59d4d3c145ee)
throwing an object south will make it phase through the window and land on disposals, rather than hitting the window

**Comment by west3436** [comment]
May be related to #37011 @DeityLink

**Comment by DeityLink** [comment]
@west3436 no it's not.

Edit: but I already know why it's happening. Will whip up a fix when I get home.
