### ISSUE TITLE
Also please make items actually STOP SMOTHERING once it's not hot anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37005]
(WEB REPORT BY: gamarjoba REMOTE: 172.93.101.77:7777)
# Revision
966df4e36995b7cc082880b55b06a45d49139b45

# Byond Version
515.1641

# Description
Coders are should be kept in check.
# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by west3436** [comment]
Things only emit smoke particles if they're in a hot room. If you see them smoking at ambient temperature please get a screenshot and gather any evidence you can help to diagnose the issue.

**Comment by DeityLink** [comment]
I definitely observed that myself during my hydroponics tests. Empty plastic buckets would still emit puffs of black smoke after the room was back to 20°C.

**Comment by DeityLink** [comment]
Ok here comes the pro QA tester 
![image](https://github.com/user-attachments/assets/8d645729-9015-492f-ad87-8d58174390a1)

I put a plastic bucket in a small room and changed the temperature of the air zone manually through varedit. At 2657°C the bucket smokes a lot and will dust if left like that for too long.

Should you then reset the temperature to 20°C, there's a 50% chance that the bucket will NOT stop smoking, and further temperature manipulation will no longer seemingly alterate the spawn rate of its particles.

It's not guaranteed it seems. On my first attempt at resetting the temperature, the bucket DID properly stop smoking, so there might be some missing proc calls at play here.

**Comment by DeityLink** [comment]
The smoke's spawnrate went down when I raised the temperature again, but this time only to 226°C

![image](https://github.com/user-attachments/assets/e43446d6-47e3-47eb-9b18-8e3e1fbd13d8)

Basically what I'm deducing is going on here is that you only update the bucket's particle spawnrate if it's in a room hot enough to emit smoke. What you should do is have objects remember that they're smoking, and keep checking their update procs for as long as they're smoking, until they stop smoking (or turn to dust), regardless of the current room's temperature.
