### ISSUE TITLE
Merch Computer cage typos

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37013]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
small cage

60 credits

A cage where to keep tiny animals safe. Fit with a drinking bottle that can be refilled..

No capitalisation on the name and a double full stop. Shameful!

**Comment by jwhitak** [comment]
It's cursed that I didn't notice this...

**Comment by angryturnip** [comment]
It's a small cage so the letters are all small. Makes sense to me. It's not a Large Cage or a HUGE CAGE.

**Comment by SECBATON-GRIFFON** [comment]
holy ESL description

**Comment by DeityLink** [comment]
What does ESL even mean in that context? Are you commenting on the fact that I wrote the description despite english not being my primary language. Is it weird to write "something where to keep"?

**Comment by SECBATON-GRIFFON** [comment]
i didnt know you wrote it honestly, and uh... yeah it is. not even sure how "where" is used like that in french

**Comment by DeityLink** [comment]
"A cage **where** to keep tiny animals safe." <=> "Une cage **où** garder de petits animaux en sécurité"

"A cage that keeps tiny animals safe." <=> "Une cage qui garde les petits animaux en sécurité"

These are how the sentences translate literally to french, they both work but don't have exactly the same meaning. And in french "un endroit **où** garder quelque chose" (someplace where to keep something) is commonly used. But if your correction makes more sense in english by all means use that one.

**Comment by SECBATON-GRIFFON** [comment]
news to me, was only familiar with the qui form which is why i asked
