### ISSUE TITLE
Smoking lights you on fire, what the actual

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37022]
(WEB REPORT BY: horzbor REMOTE: 172.93.101.77:7777)
# Revision
Revisionist history hurts my soul

# Byond Version
lol.lmao

# Description
Smoking a fat doobie, small cigarillo, thick log, enjoyable cigar, lights you on fire and kills you without even a notice that you're on fire aside from the fire sprite.

# Steps to Reproduce
Smoke.

# What you Expected
Not catching on fire due to a tiny little smoldering ember hanging out of my mouth.

# What Actually Happened
Instant firey death.

**Comment by DeityLink** [comment]
This is discrimination against smokers!

**Comment by Eneocho** [comment]
They did warn you that smoking kills with all those PSAs.

**Comment by west3436** [comment]
Closed via #37035
