### ISSUE TITLE
Thermometers don't fit inside medical belts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37034]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
1ad1cf58cdb3879fcda0e23b94dbedb1d214eafe

# Byond Version
515.1643

# Description

As the title says, they don't go inside them, despite being tiny and obviously medical items. This goes for normal ones and the electronic ones R&D can make

**Comment by SonixApache** [comment]
there's a lot of things medbelts should carry and don't

**Comment by SECBATON-GRIFFON** [comment]
> there's a lot of things medbelts should carry and don't

 name some

**Comment by SonixApache** [comment]
i don't play (medbay) enough to tell you outright, but just walk around medbay picking up random medical stuff and try to put it in your belt.
