### ISSUE TITLE
Cup Ramen issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37030]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
a210ab8b23bba0c155be511a5553cdcbe6f91e6b

# Byond Version
515.1643

# Description

The description for the ramen asks for 12ml water, even though we use units instead. Giving it 5u activates 9u of hot ramen,heats it, and leaves 2u calcium hydroxide and 21u dry ramen. Adding any more water does nothing.

**Comment by SonixApache** [comment]
i have complained about this since the addition of the stupid chemical needed to heat it
we should really just make the heating an integral part of the cup instead of whatever it is now

**Comment by SECBATON-GRIFFON** [comment]
if you do it fast enough it works, tested it with a beaker transferring 10u of water each time
