### ISSUE TITLE
Packed bridge wing windows have extra panes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37040]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
868a1105e78bb47c2234b60ce17af1bc77453640

# Byond Version
515.1643

# Description

The 1x2 windows on the port and starboard of the bridge on packed are made up of a full tile window and one-direction windows in all directions, including internally. The bottom ones shouldn't have the north-facing ones, the top ones shouldn't have the south-facing ones.

**Comment by SECBATON-GRIFFON** [comment]
someone should really either expand the mapping verbs to detect these or even write a unit test that checks the map files for this stuff
