### ISSUE TITLE
mining satchel screws up ore processing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37041]
(WEB REPORT BY: spacedgod REMOTE: 172.93.101.77:7777)
# Revision
868a1105e78bb47c2234b60ce17af1bc77453640

# Byond Version
514.1569

# Description
dropping ores off to the smelter directly from a mining satchel yields only 1 ore's worth of mineral
# Steps to Reproduce
dump satchel in front of ore processor
# What you Expected
MOST OF MY GODDAMN MATERIALS
# What Actually Happened
one fucking stack of 5 of everything

**Comment by west3436** [comment]
@SECBATON-GRIFFON all you

**Comment by SECBATON-GRIFFON** [comment]
and this is why you use add() proc on stacks instead of adding just the amount, didnt call update_materials()
