### ISSUE TITLE
Synergy double air alarms in brig

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37059]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
5689586c9f468923e5e26323cbf2b618d56e17de

# Byond Version
515.1643

# Description
there's an extra air alarm in the secure armoury at the top left in a pile of armour, and one in the HoS office coincidentally also at the top left, sitting on the table

**Comment by SECBATON-GRIFFON** [comment]
i don't see em on the map
