### ISSUE TITLE
Gas mixer sprite alignment is off

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3705]
![](http://i.imgur.com/QsH4WwX.png)

it hertz

**Comment by clusterfack** [comment]
Its a problem with the fact it isn't 100% centered, so the fact we flipped the image to create the alternate images made it not perfect. Happy autism awareness day.

**Comment by ComicIronic** [comment]
Who wants to redo all pipes to be 6 tiles wide?

Nobody?

**Comment by PJB3005** [comment]
It's actually not that big of a thing to do, as long as you know where all pipe sprites are

**Comment by ComicIronic** [comment]
I estimate that there are roughly 107 sprites that would need to be replaced.

And that's not including the fact that several pipes have animations, which add about 16 extra sprites each.

Nor including the pipe item sprites.

**Comment by PJB3005** [comment]
just seems better to make it so the inverted filter/mixer just uses a different icon state, as the shadow on the sprite can't be fixed anyways, even if you made the sprites 6 px thick

**Comment by PJB3005** [comment]
This was fixed as a result of celtpipes, wasn't it?

**Comment by ihadtoregisterforthis** [comment]
Not really

**Comment by gbasood** [comment]
Works fine.
![oldissue](http://i.imgur.com/q9tUpyn.png)
