### ISSUE TITLE
Box Virology airlock water cooler spawns unsecured

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37057]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
5689586c9f468923e5e26323cbf2b618d56e17de

# Byond Version
515.1643

# Description

help i keep pushing it around

**Comment by SECBATON-GRIFFON** [comment]
well yes code label, it is literally loose from the floor (inb4 thatsthejoke)

**Comment by SECBATON-GRIFFON** [comment]
also they're like this by default

**Comment by west3436** [comment]
> well yes code label, it is literally loose from the floor (inb4 thatsthejoke)

That WAS the joke!

Closing as this is intended functionality. Make a new issue report as a feature request if you'd like to change it.
