### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Eat (Power)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3706]
So with the Eat Power you are capable of eating the station intercom ,basically

**Comment by PJB3005** [comment]
Who coded intercomms to be /obj/item again? /obj/machinery makes way more sense

**Comment by clusterfack** [comment]
They needed to be that way to inherit from radio code, which overall is much larger than machinery code's inheritance.

**Comment by Kurfursten** [comment]
@clusterfack Not a bug, close this. Seriously, it's a power that lets you eat wirecutters, shards, arms, and plasma sheets, radios, and we're worried about eating intercoms?
