### ISSUE TITLE
(WEB REPORT BY: myroc REMOTE: 198.245.63.50:7777) Welding protection doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3707]
>Revision (Should be above if you're viewing this from ingame!)
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba

>General description of the issue
Welding protection doesn't seem to work, regardless of source.

>What you expected to happen
Being protected from eye damage caused by welding.

>What actually happened
My eyes were damaged despite wearing a hardsuit helmet, and later a welding mask.

>Steps to reproduce if possible
1. Put on a welding mask/hardsuit helmet/other welding protection.
2. Weld something.
3. Enjoy your eye damage.

**Comment by Probe1** [comment]
I noticed this occurring yesterday on a private test server and did not know what to make of it.  I'd put the timeframe for the bug around the last 24-48 hours.

**Comment by ComicIronic** [comment]
Is this still happening?

**Comment by Probe1** [comment]
no.
