### ISSUE TITLE
Wizards can use guns.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3712]
This is an issue.

**Comment by Ephx1** [comment]
So what you're saying is, Wizards should also be FIST Wizards?
I'm down with it.

**Comment by Probe1** [comment]
what if wizards couldn't use spells while holding a gun?  it could be in their backpack or belt slot sure, but "Your magical energy drains!" when you put a gun in your hands and you are a mere murderboning mortal without access to your potential arsenal of spells unless you holster that gun.

**Comment by PJB3005** [comment]
I agree, wizards shouldn't be able to use guns without side effect, getting into the armoury as wizard isn't hard, if a wizard can't use guns (without side effect atleast), it levels the playing field for sec atleast a little

**Comment by clusterfack** [comment]
So what, would something like make having a gun on you violate your spell clothes requirement work. 

So you can only effectively use them + spells if you take no clothes.
