### ISSUE TITLE
"Be assistant if pref. unavailable" while having assistant in prefs. makes you randomjob in some cases?

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#3713]
Selected assistant with "join as assistant if preferences unavailable", ended up joining as borg on one round and as a MoMMI on the next.

"Join as assistant [...]" should be disabled when selecting assistant, or at least make it so the game boots you back to the lobby when that happens.

**EDIT: Looks like the assistant toggle is borked. I had to set every job to 'off' and then toggle it to join as one.**

**Comment by Probe1** [comment]
You can change "Be assistant if prefs are unavailable" to "return to lobby if prefs are unavailable" 

![2](https://cloud.githubusercontent.com/assets/8550416/6977002/c8faf1cc-d981-11e4-9840-e3584631edaa.gif)

The latter half of the gif has assistant toggled on and you can see the preference is still there.

**Comment by wwjnc** [comment]
I know how to change it you nerd, the problem is that it isn't doing what the labels says. If you intend to play as assistant, why would it randomjob you?

Honk.

**Comment by Probe1** [comment]
Yeah I get what you're saying, I was offering a working solution until someone codes it.

**Comment by wwjnc** [comment]
Even setting it to 'return to lobby if pref. unavailable' makes me random job.

**Comment by wwjnc** [comment]
So yeah, I've played 5 rounds in a row and got randomcucked into MoMMI on every single one, even though the assistant slots weren't full.

**Comment by PJB3005** [comment]
but why would being MoMMI be bad?

seriously though this could use a fix.

**Comment by wwjnc** [comment]
Looks like the assistant toggle is borked. I had to set every job to 'off' and then toggle it to join as one.

**Comment by clusterfack** [comment]
I think @d3athrow fixed this

**Comment by Intigracy** [comment]
yes

**Comment by Intigracy** [comment]
yes as in he did fix this
