### ISSUE TITLE
(WEB REPORT BY: rounders REMOTE: 198.245.63.50:7777) gateway

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3715]
gateway doesnt work =^(

**Comment by eswordthecat** [comment]
I cri errytime.

**Comment by dylanstrategie** [comment]
Gateway has been turned off for a long fucking time because of how fucking bad away missions have gotten

I might just take a good look at it, though most of it is mapping work

**Comment by NigglyWiggly** [comment]
Wouldn't it be relatively simple to make some small away mission areas on the centcomm Z-level?

**Comment by dylanstrategie** [comment]
Pretty sure the CODE is functional (though being old, it can likely see improvement)

The problem is the quality of the away missions, some of them are bad, to say the least

**Comment by 9600bauds** [comment]
this werks now
