### ISSUE TITLE
hyperzine slows down slime people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37175]
(WEB REPORT BY: jesture REMOTE: 172.93.101.77:7777)
# Revision
6b314ffdb3be26af5994c72c5f90c1802a223901

# Byond Version
515.1619

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by Dacendeth** [comment]
https://github.com/vgstation-coders/vgstation13/blob/6b314ffdb3be26af5994c72c5f90c1802a223901/code/modules/mob/living/carbon/human/human_movement.dm#L79-L81
Intended

**Comment by Eneocho** [comment]
Intended indeed, though kinda lame.

**Comment by Eneocho** [comment]
wrong label whoops

**Comment by cloutcode** [comment]
For what purpose
