### ISSUE TITLE
AI camera tracking doesn't kick back in if the subject returns to cameras anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37193]
(WEB REPORT BY: sonixapache REMOTE: 172.93.101.77:7777)
# Revision
377cf81ce2671f9084c0cdeba3b5f7766bff269e

# Byond Version
515.1620

# Description
Used to be, if someone walked into the static you'd lose them up until they stepped back into the camera zones. 
Now, especially with the upgraded tracking, if someone walks into a single square of static you lose them 5ever and that sucks.

**Comment by SECBATON-GRIFFON** [comment]
natural consequence of it changing to the instant system instead of checking every second. could add a small window for retracking?

**Comment by SonixApache** [comment]
i don't see why it wouldn't just re-establish tracking when possible, can't be too expensive to have one check for that every machinery tick or whatever

**Comment by SECBATON-GRIFFON** [comment]
> i don't see why it wouldn't just re-establish tracking when possible

caused downvotes in the first run at the PR

**Comment by SonixApache** [comment]
try it again
