### ISSUE TITLE
cigarette melted every item on the same tile to ash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37191]
(WEB REPORT BY: dackjaniels REMOTE: 172.93.101.77:7777)
# Revision
377cf81ce2671f9084c0cdeba3b5f7766bff269e

# Byond Version
515.1643

removed a lit cigarette from a mouth as well as everything on the persons body. Lit cigarette lit more cigarettes on fire, making it hot enough to ash every item on the floor

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by angryturnip** [comment]
[https://youtu.be/Uikd6WW9jpU](url)

**Comment by angryturnip** [comment]
[How could this fire have started?](https://youtu.be/Uikd6WW9jpU)

**Comment by west3436** [comment]
Tested this and replicated it only by letting the cigarette sit on the floor for several minutes. The lit cigarette has a 2% chance to ignite things on its tile every 3 seconds so you just had an incredibly unlucky roll.
