### ISSUE TITLE
Screwsolder doesn't work on space pod build step

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37206]
(WEB REPORT BY: kernikov REMOTE: 172.93.101.77:7777)
# Revision
01d78a7e709fa532a844b2cc48339850d3671e07

# Byond Version
515.1643

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by jwhitak** [comment]
Duplicate of #36899
