### ISSUE TITLE
Shards shock you

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#3722]
https://github.com/d3athrow/vgstation13/pull/3660/files#diff-31166bc4a338f1486377504beb5c5c36R198

**Comment by ComicIronic** [comment]
I told him.

**Comment by PJB3005** [comment]
why is this bad?

**Comment by CptWad** [comment]
Used to be that you could break into places using the broken glass. Glass does not conduct electricity well so its logical for it to be used to break into places.
Thats how it was before.

**Comment by PJB3005** [comment]
yeah, and it makes electrified grilles a joke, and how the fuck are you supposed to smash through a heavy steel grille with a goddamn glass shard in the first place.

**Comment by ComicIronic** [comment]
>heavy

It's made from two rods.

**Comment by ComicIronic** [comment]
Fixed in #3724.
