### ISSUE TITLE
Arcane Tampered airlocks are too powerful

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37238]
(WEB REPORT BY: kernikov REMOTE: 172.93.101.77:7777)
# Revision
1e2b9a41f986cd356f453c14380fc273b33f0f90

# Byond Version
515.1643

# Description
>randomly spaced >sent to a vault
>ejected off emergency shuttle
# Steps to Reproduce
Take busted spell
Profit
# What you Expected
Balanced
# What Actually Happened
Retarded

**Comment by Kromkar** [comment]
Laugh at this user

**Comment by Killette2** [comment]
Happened to me too, I want to keep this because we only went to the gingerbread vault. Save for a mothership vault tamper. Not annoying enough yet to change, joke's still funny

**Comment by angryturnip** [comment]
Owned

**Comment by Dacendeth** [comment]
I just hate that it prevents messing with the airlocks wires to fix it

**Comment by kernikov** [comment]
Kudzu can spread through tamper airlocks!! BTW!

**Comment by SECBATON-GRIFFON** [comment]
once again, i think the best solution would be to simply limit them to the same z-level or any connected ones but it still seems too unpopular to bother trying

**Comment by SonixApache** [comment]
if the push spell got tuned down to not send people to random Z-levels, so should this

**Comment by Eneocho** [comment]
On my way to build several dozen airlocks in space every shift to skew the odds towards getting spaced.
