### ISSUE TITLE
1 TC cost items can be discounted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37231]
(WEB REPORT BY: mastercasual REMOTE: 172.93.101.77:7777)
# Revision
1e2b9a41f986cd356f453c14380fc273b33f0f90

# Byond Version
514.1589

# Description
Sometimes one cost TC items can be discounted but there is no real discount, it's just lame.
# Steps to Reproduce
get unlucky on your sale rolls
# What you Expected
Eh, nothing really.
# What Actually Happened
I got unlocky

**Comment by angryturnip** [comment]
Should probably just be blacklisted from possible discounts

**Comment by Eneocho** [comment]
> Should probably just be blacklisted from possible discounts

Free but only one per tator would be better in my opinion.
