### ISSUE TITLE
Shoe Snatching Upgraded is a Scam

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37241]
(WEB REPORT BY: kirbythewizard101 REMOTE: 172.93.101.77:1337)
# Revision
da765799ff2c8970f8afdca50bf657d52ab2c561

# Byond Version
515.1635

# Description
Shoe Snatch Upgraded states the following:
"Make the spell summon glass shards around targets who aren't wearing any shoes."
However when upgraded it doesn't spawn the glass shards around anyone and just drops the shoes at their feet instead of having it go into your hand.

# Steps to Reproduce
>Get wiz spellbook
>Humanize a monkey give it shoes
>Take the shoe snatching spell
>Upgrade it
>Cry when you see your hopes and dreams die with this spell and how you just wasted 40 points

# What you Expected
For the spell to spawn glass shards like advertised

# What Actually Happened
I got scammed harder than a crypto bro

**Comment by Dacendeth** [comment]
the upgrade is working as intended, but the base spell isnt putting the shoes in hand at all.
