### ISSUE TITLE
mob loyalty broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37240]
(WEB REPORT BY: spacedgod REMOTE: 172.93.101.77:7777)
# Revision
1e2b9a41f986cd356f453c14380fc273b33f0f90

# Byond Version
514.1569

# Description
pokeball monsters, arcane golems, etc. will attack you

# Steps to Reproduce
lazarus monster (it'll be loyal), ball and unball it. Or just summon a golem and have it break your leg smdh
# What you Expected

# What Actually Happened

**Comment by SacredAtom** [comment]
I have also experienced this, on lamprey I had tossed down two goliaths to fight syndie mobs, and just had the goliaths turn around and obliterate me shortly after. I figured it was due to the map but it seems there might be an actual problem
