### ISSUE TITLE
Pickpocketing progress bar for ID/pockets

### ISSUE THREAD

**Issue by Dacendeth** [d3athrow/vgstation13#37250]
#### Description of issue
When stripping someones ID or items in pockets, or putting an ID back on their ID slot or putting an item in their pocket the target sees a progress bar, these actions are innately stealthy and only tell the target in chat if the action fails normally and thus shouldn't have a progress bar.

#### Difference between expected and actual behavior
No progress bar on target for having ID or pockets messed with ever
They see progress bars

#### Steps to reproduce
Get two clients, have one pickpocket the id or try to put something in the targets pocket
the target observes a progess bar despite no chat message about these events.

#### Length of time in which bug has been known to occur

#37217

**Comment by angryturnip** [comment]
Shouldn't show up for people at all if you're on harm intent imo as I said on his PR

**Comment by SECBATON-GRIFFON** [comment]
does this involve the gloves or not? because i tested it with them and it still hid them
that aside, i always viewed them not giving a message as an unintended "feature" inconsistency and left this alone, but if people prefer it like that (didnt even know they did) i can hide the bars there too, preferably for the pocket slots.

**Comment by Dacendeth** [comment]
antag Gloves hide it, the problem is interacting with the id and pocket slots are coded to not show the target any messages even without the gloves unless your progress bar gets only then do they get a message you're stealing their id or messing with your pocket.
