### ISSUE TITLE
Plastic crates can't be dragged into disposal bins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37255]
(WEB REPORT BY: riekland REMOTE: 172.93.101.77:7777)
# Revision
074c6b032edc470c0788d6db7449fa6c25da73d4

# Byond Version
515.1643

# Description
As per the title, no progress bar and it doesnt go in after a while so it's not just invisible

**Comment by Dacendeth** [comment]
its cuz plastic crates are a not a crate and are a locker.

**Comment by SECBATON-GRIFFON** [comment]
> its cuz plastic crates are a not a crate and are a locker.

consistency issue
