### ISSUE TITLE
Music Server Borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37274]
(WEB REPORT BY: blitzikaze REMOTE: 172.93.101.77:7777)
# Revision
b8d7eaa6664117dcaf43cb216ed33b15177a0e41

# Byond Version
514.1589

# Description
Music no load
# Steps to Reproduce
Turn on jukebox
# What you Expected
Music turn on
# What Actually Happened
Music didn't turn on

**Comment by west3436** [comment]
Fixed by @d3athrow
