### ISSUE TITLE
It's impossible to emag cyborgs and MoMMIs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37280]
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
e0f81a5e1eaede62ea7cd9488403f02f882015b6

# Byond Version
515.1627

# Description
IT DOESN'T WORK IT'S LOOOSE

**Comment by jwhitak** [comment]
More specific case of #37281 where emagging does not work on any mob at all.
