### ISSUE TITLE
pAI slots are broken on bots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37282]
(WEB REPORT BY: tinysaturn REMOTE: 172.93.101.77:7777)
# Revision
e0f81a5e1eaede62ea7cd9488403f02f882015b6

# Byond Version
515.1627

# Description
You can't slot pAIs into bots
tested with MULE and medibot

pAI can be slotted into hologram projectors
didn't test smartguns

**Comment by jwhitak** [comment]
You did try this when there was a player in the pAI, yes?

**Comment by MercuriusGH** [comment]
yes

**Comment by jwhitak** [comment]
Confirmed issue, likely related to emag issue #37281

**Comment by jwhitak** [comment]
Likely related to line https://github.com/vgstation-coders/vgstation13/blob/e0f81a5e1eaede62ea7cd9488403f02f882015b6/code/game/machinery/bots/bots.dm#L719
