### ISSUE TITLE
vox raider shuttle has no proper windows

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37287]
(WEB REPORT BY: yvvel REMOTE: 172.93.101.77:7777)
# Revision
e0f81a5e1eaede62ea7cd9488403f02f882015b6

# Byond Version
515.1636

# Description
see title
# Steps to Reproduce
spawn as a midround vox trader
# What you Expected
to not immediately get zas'd
# What Actually Happened
windows were non-existent. [37159] probably unintentionally broke it but thats my guess.

**Comment by SECBATON-GRIFFON** [comment]
i dont see how a PR that touched null rods and blessing is related to this
