### ISSUE TITLE
Blue Portapump Pipenet Pressurization

### ISSUE THREAD

**Issue by Squird5** [d3athrow/vgstation13#37302]
#### Description of issue
Related to #37300

Portable Pumps seem to passively increase the distro pressure over time, by about 2 kPa per second.

#### Difference between expected and actual behavior

Porta pumps should not be altering the pipenet when powered off

#### Steps to reproduce

Wrench a portable pump to a connector on the main distro loop

#### Specific information for locating

Can be found with the portapumps connected to the distro connectors in MetaStation Dorms
https://github.com/vgstation-coders/vgstation13/blame/Bleeding-Edge/code/game/machinery/atmoalter/pump.dm
It may be related to an unexpected interaction between #37277 and #36989 

#### Length of time in which bug has been known to occur

I heard about it today, seen it in testing

#### Server revision

10d9fff912f6e6b6bdb6888c61353c5b0ebf6163

**Comment by hacker-on-steroids** [comment]
actually this one might be me? the update_pipenet in the portapumps happens even when they're off
why did i do it like that

**Comment by hacker-on-steroids** [comment]
i bet this is caused by the combined waste-distro pipe(which was fixed by #37303) and the pumps updating the pipenet only accelerated it somehow

**Comment by Squird5** [comment]
I was testing this on a build where I had fixed that part of the pipenet

**Comment by hacker-on-steroids** [comment]
does manually setting a pipenet's update var to 1 also generate some gas?

**Comment by west3436** [comment]
Fixed via #37306
