### ISSUE TITLE
CRYPTO WONT WORK ON SHARD CATES AHHHHHHHHHHHHHHH

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#37307]
(WEB REPORT BY: kirbythewizard101 REMOTE: 172.93.101.77:7777)
# Revision
d4de3e23c357765b2e7b8d83cc13de900b785319

# Byond Version
514.1566

# Description

# Steps to Reproduce

# What you Expected

# What Actually Happened

**Comment by angryturnip** [comment]
**SELL SELL SELL**
![PngItem_2964915](https://github.com/user-attachments/assets/17c5ab6a-3e58-4e35-8032-17eb6daf90f6)

**Comment by SECBATON-GRIFFON** [comment]
i naturally guessed you meant cryptographic sequencers
