### ISSUE TITLE
(WEB REPORT BY: drleprikon REMOTE: 198.245.63.50:7777) Taking eye damage with a mining helmet or a welding helmet equipped

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3730]
Crab Suffix Eta 

Took eye damage when welding walls and a camera while equipped with a welding helmet/mining helmet and mesons. Is it intended? Do mesons negate eye protection? I was cult too, if that means anything

**Comment by 9600bauds** [comment]
I think the cause here is mesons, but I haven't tested it.

**Comment by PJB3005** [comment]
it's caused by mesons, can confirm.

**Comment by dylanstrategie** [comment]
This might have been fixed, please confirm this is still an issue

**Comment by ComicIronic** [comment]
As with #3707, I believe this was fixed.
