### ISSUE TITLE
Plasmamen combust inside cloners, forever

### ISSUE THREAD

**Issue by Cartlord** [d3athrow/vgstation13#37323]
#### Description of issue
If you clone a Plasmaman without an active shower over the cloner (such as on WayStation), the plasmaman will catch fire inside the cloner due to not having their suit, causing them to take damage about as fast as the cloner heals them - leaving them stuck inside unless someone intervenes, such as by forcing them out.

#### Difference between expected and actual behavior
You shouldn't combust inside cloners, because there is no air for your body to react with.

#### Steps to reproduce
-Be Plasmaman
-Die
-Get cloned
-Your body reacts with the atmosphere and bursts into flames!
-Cloner's now essentially fucked, because it won't clone anyone else until you're out of it and you're never coming out unless something forces your incomplete clone out

#### Length of time in which bug has been known to occur

My first and only experience with it has been today.

#### Server revision

9da1d99254f28cc63d2e42fca717b95ce1d50d59 Current Infomational Settings: 
BYOND version of server: 515.1620
Protect Authority Roles From Tratior: 1

**Comment by Dacendeth** [comment]
Confirmed, something changed and now you catch fire while inside atoms now, where previously this didn't happen.

Previously while inside a cloner, or a locker, or some other structure you'd get spammed with "Your body reacts with the atmosphere and bursts into flame!" every few ticks or so but you would not actually ignite.
