### ISSUE TITLE
(WEB REPORT BY: rounders REMOTE: 198.245.63.50:7777) glass shard and wire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3732]
>Revision  3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

>used a glass shard to attack a wire

>since shards were made to not be shocked by grills I figured I would see if that extended to wires

>instantly died

>glass shard to wire

**Comment by dylanstrategie** [comment]
Glass shards have snowflake code that makes them not shock people on grilles, and ONLY on grilles. Literally anything else will turn you into a superconductor

Blame the faggot who thought it was too hard to steal insulated gloves and added literally the easiest way to bypass electrified grilles

**Comment by DrCelt** [comment]
Dylan added this 'feature' and it was removed later. Close this
