### ISSUE TITLE
Protolathe doesn't require any access, Destructive Analyzer does.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3733]
This works a little weird because then you can just break a window and get an advanced egun/stun revolver/bag of holding/whatever you want without any access, or better still, break into the MoMMI nest so noone sees you.
But God help you if you're a miner just 1 power research level shy of your diamond drill, because the DA is the only access restricted thing in the room.
Also you can add items to the DA without access, but then it's held hostage by the ever impenetrable glass case since ejecting the item does require access.

**Comment by 9600bauds** [comment]
This is discussion more than anything: Should it be this way y/n?

**Comment by Probe1** [comment]
no
and gun cases should require a weapon permit to open again

**Comment by ComicIronic** [comment]
>there needs to be some line where you have to ask the hop for access 

My issue with this is that lockboxes were removed because this was never the case.
People broke open lockboxes. Removing the access requirement didn't magically make them easier to access, it just took out an ultimately pointless non-secure item, and replaced it with something of mild utility.

Restoring lockboxes, and making them EMP/bullet-proof, is a whole other dicusssion.

**Comment by Probe1** [comment]
They did, but it made it firmly illegal and against spess law.  Removing the need to do something shady to get shady RnD stuff removed securities willingness to police it.  

You're right that this is a different discussion but I think it's tied to not making RnD even more any-access friendly.  I cited that as a reason.  Right now the destructive analyzer access requirement being tied to the "X" console requirement is all there is left.  I think it should go in the opposite direction and be more restricted.

**Comment by ComicIronic** [comment]
Restricting the fabricators carries its own risks, however.
Some items from the protolathe and imprinter are highly critical in an emergency, and locking them behind an access requirement is what the console lock is for, not limiting the machines themselves.

**Comment by dylanstrategie** [comment]
I very honestly believe that R&D machinery should be usable by anyone when set up and ready, but the settings should -obviously- not be usable by anyone without access

**Comment by Probe1** [comment]
add a function to the RDs card swiper that repeals DA and protolathe access then.  we shouldn't cater to emergency situations by removing access all the time

**Comment by 9600bauds** [comment]
What if semi-secure lockboxes notified the Warden/HoP/whoever's console when opened by any means?

Something like "semi-secure lockbox (advanced energy gun) was opened in toxins storage". Just a message at the console, like PDA messaging logging.

**Comment by ComicIronic** [comment]
>add a function to the RDs card swiper that repeals DA and protolathe access then. we shouldn't cater to emergency situations by removing access all the time

The functionality you've just described is just the console lock. If you don't want just anyone to use the machines, lock the console.

**Comment by Probe1** [comment]
well there you go.  add another option that lets you unrestrict machines linked to a console.  that way in an special circumstances anyone can use the DA, protolathe, circuit imprinter, exosuit fabricator, and so on.  but under normal circumstances people couldn't smash in and print assault rifles in a flash.  win win?
 
![capture](https://cloud.githubusercontent.com/assets/8550416/6993035/c078c4a0-dab4-11e4-8db7-1b40d9b3d191.JPG)

**Comment by ComicIronic** [comment]
You're missing the point.
Such a button would not only remove the need for the console lock, but it wouldn't preserve the functionality of being able to use the Science machines in an emergency without a Scientist present.

If you don't want people to break in and make anything, lock the console. That is what the button is for.

**Comment by Probe1** [comment]
It has just come to my attention that pomf merged gun lockboxes once again having an ID requirement to open.  My opinion was based on the state of RnD before that recent change and this alters my opinion on this subject.  I still think that protolathes should be more restricted, not less, but I care much less about it than I did a few minutes ago when I thought you could open a laser cannon lockbox with a janitor ID.

**Comment by 9600bauds** [comment]
I'd Just Like To Interject For A Moment and state again that, regardless of the Protolathe being access-restricted or not, the DA requiring access doesn't make much sense and is a huge cockblock sometimes

**Comment by 9600bauds** [comment]
Another thing this causes: You can't up research at the Derelict research station unless you have main station Science access. Ideally you should be able to at least make yourself a tracking beacon or something, since guns are ID-restricted now.

**Comment by Probe1** [comment]
gun boxes are not ID restricted despite the changelog from 4/2/15.

**Comment by 9600bauds** [comment]
If you care enough to get materials and uranium, go to the Derelict and do R&D all by yourself just because you wanted a gun you could get from so many other sources, my god man, you earned it

**Comment by Probe1** [comment]
After talking with pomf gun boxes now work properly and cannot be unlocked willy nilly.

**Comment by ConkerDev** [comment]
Should be closable

**Comment by 9600bauds** [comment]
It's still an issue but w/e
