### ISSUE TITLE
(WEB REPORT BY: kilkun REMOTE: 198.245.63.50:7777) Can't swap monkey brains

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3735]
> Revision (Should be above if you're viewing this from ingame!)

3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

> General description of the issue

Surgery on Monkeys is impossible.

> What you expected to happen

The ability to extract a monkey's brain and put a human brain inside.

> What actually happened

I hit the monkey with some surgery tools despite it being unconscious.

> Steps to reproduce if possible

Lay monkey on table

Make it go unconscious

Hit it's head with surgery tools on help intent

**Comment by Ephx1** [comment]
Has surgery on normal Monkeys ever worked?

**Comment by dylanstrategie** [comment]
Are we certain the surgery didn't fail simply because of the mob being tabled on not on a surgery table ?

Also, the way to go is usually humanizing monkeys for brain transfers in case of mob destruction where the head has been recovered

**Comment by d3athrow** [comment]
monkeys dont have limbs or organs.

**Comment by Zuhayr** [comment]
There's a PR on Baydev that converts monkeys into a human species, might be worth grabbing that if you need them to act like this.

**Comment by d3athrow** [comment]
for what porpoise

**Comment by ComicIronic** [comment]
That sounds like a good idea.
It would certainly remove a lot of the monkey snowflake.
And we do need a way to integrate species into genetics.
