### ISSUE TITLE
The fuck is narsie deleting

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3736]
![](http://puu.sh/h0xcl/b87d1a2e09.png)
Normal del() (excludes qdel and hard del) profiling during narsie endgame. There was relatively few hard deletes but massive lag from all these regular deletions. So what the fuck kind of deletes are these? I'm guessing client screen objects or something? Or perhaps the flash objects that are on every tile, if those can even be deleted.

Side Note for people who dont know: qdels only collect during narsie endgame so they dont affect the performance through their "deletions".

**Comment by SkowronX** [comment]
Check the procs that where narsie turns everything in vicinity to cult floors/walls.
