### ISSUE TITLE
(WEB REPORT BY: Iamgoofball REMOTE: Unknown) Pomf123 keeps shilling his server at /tg/station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3741]
>Revision 
whatever version of phpbb the forums at tg are on

>General description of the issue
well he showed up in my bug report thread to shill the fuck out of vg, this cannot be tolerated

>What you expected to happen
thread to go unshilled

>What actually happened
intense chickenman shilling action

>Steps to reproduce if possible
1. make thread on tg about bug reporting and tutorials
2. watch the coop master shill /vg/ in the replies
3. cry

**Comment by d3athrow** [comment]
i demand reparations

**Comment by ComicIronic** [comment]
Wontfix.
