### ISSUE TITLE
No inventory manipulation when put on rollerbed/surg-table

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#3743]
laying someone on the surgery table or lifting them with a rollerbed renders inventory manipulation (when you drag their body sprite on yours) useless for most things.
Can't even set internals on/off when they're on the table.

**Comment by ComicIronic** [comment]
Have not had this experience myself.
I've set plenty of internals on patients on the surgery table.

**Comment by wwjnc** [comment]
I've had this happen too even on top of regular tables. Sometimes nothing works, sometimes only half the buttons work.

I blame Duny.

**Comment by Kurfursten** [comment]
@clusterfack I don't believe this happens anymore. Definitely not with surgical tables anyway.
