### ISSUE TITLE
[Box] Duplicate apc in Fore Primary Hallway

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3749]
One must go.  Probably the one closest to the bridge.  If either apc is destroyed the other must have its main breaker toggled on and off for anything to work, and the apc that was broken cannot be restored as there is already an apc in the area.  This is horribly counterintuitive and nowhere else on the station are there two apcs for a single area.

An alternative idea is to create a new room for one of the apcs but that seems superfluous.  
 
![image](https://cloud.githubusercontent.com/assets/8550416/6992356/0e592d04-da97-11e4-8113-91a80b99e38c.png)

**Comment by dylanstrategie** [comment]
I'll take a third option, weed out one APC and move the other to a more central position
