### ISSUE TITLE
[Bug] Invisible grilles

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3750]
occasionally when building on a tile that has a broken grille already and you don't remove said broken grille, the new grille is invisible. 

![ss 2015-04-04 at 05 42 01](https://cloud.githubusercontent.com/assets/8550416/6992361/906dd6be-da97-11e4-8d56-41533ec547f2.png)

**Comment by Probe1** [comment]
there's a joke to be made about my dating prospects as well.

**Comment by clusterfack** [comment]
Grilles just want to have fun

**Comment by dylanstrategie** [comment]
Might have missed a variable somewhere, I'll look into it
