### ISSUE TITLE
(WEB REPORT BY: conker327 REMOTE: 198.245.63.50:7777) Teleporting Lazarus Capsules to remote Trainer Belts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3752]
>Revision (Should be above if you're viewing this from ingame!)
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba

>General description of the issue
1. Pick up trainer belt, and open its contents
2. Throw it. Menu doesnt close.
3. Put Capsule inside
4. The capsule is now inside a belt several tiles far

**Comment by Kurfursten** [comment]
This is a very common bug that I think all bags suffer from.

**Comment by clusterfack** [comment]
Its a simple fix
