### ISSUE TITLE
Disposal mail: medbay etc unreachable

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#3754]
I know few probably use it as cargo never does anything but order weapon crates and declare war on heads, but it might be good to fix disposal mail system.
Specifically, Medbay (and possibly more places) isn't reachable and the tagger lacks the new departments.

**Comment by CptWad** [comment]
I think Engineering destinations are borked too

**Comment by dylanstrategie** [comment]
If I'm not mistaken, Disposal Mail has been fucked for almost a year now, even since Duny reworked Cargo

Plus, no-one dares to check disposal code, there's a weird bug that has been in for a while that breaks floor tiles on disposals when stuff is mailed through, and no-one really knows what is going on

**Comment by Probe1** [comment]
@dylanstrategie the floor isn't actually broken.  someone half fixed it a month or two ago but somehow left a spriting issue in so it looks like the floor tile is missing but it's really there and can be crowbarred up and replaced.

i've had people ask me in game to fix disposals citing medbay and engineering but found it to work fine when I looked at it.  There must be something going on.

**Comment by Kurfursten** [comment]
@clusterfack I fixed this myself ages ago

**Comment by ihadtoregisterforthis** [comment]
Send one crate at a time dammit. If you put ten different tags together on the belt they're all sent to the same place. If you just send them in turns, this is wait for the flush sound to play

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis This issue was created a long time ago when mail actually  WAS broken.
