### ISSUE TITLE
Doctor's Delight is alcoholic

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3755]
For some horrible reason it is.
Tomato Juice
Lime Juice
Orange Juice
Milk Cream
And Tricordrazine
None of those should really make it alcoholic.
It completely negates the purpose of healing, instead fucking over people's livers.

**Comment by dylanstrategie** [comment]
Override missing somewhere for the Doctor's Delight contents

**Comment by dylanstrategie** [comment]
Nevermind, it's a inheritance issue. Forwarding a fix
