### ISSUE TITLE
Switch lawset from asimov to crewsimov

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3757]
seriously asimov is racist against non humans, I've already seen borgs bully vox because they're allowed to, purely.

**Comment by Ephx1** [comment]
No, no, no, no, no.
NO.
Its one of their downsides for picking an alien.

**Comment by 9600bauds** [comment]
Server rules override Asimov, so aliens are still protected from serious 4noraisin unless specifically ordered to by an antag.

That said, it is a little annoying when silicons ignore even reports of human harm because lol ur a diona i don't have to listen to you, but that's entirely an IC issue.

**Comment by BestName** [comment]
Gas the vox, race war now!

**Comment by NigglyWiggly** [comment]
No
Asimov protecting non humans is dumb.

**Comment by PJB3005** [comment]
so, you're just gonna screw over other races?

that's fair

not.

**Comment by BestName** [comment]
The other races have no rights.

**Comment by NigglyWiggly** [comment]
Yep.
Asimov being made to protect non-humans is dumb.

**Comment by PJB3005** [comment]
why is it dumb

**Comment by NigglyWiggly** [comment]
Because it wouldn't be Asimov if it was made to protect a 'crew' instead of 'humans' and that would be dumb, it would also enable the AI and borgs to validhunt human wizards/nukeops like crazy

**Comment by Ephx1** [comment]
Again, it's a downside of them picking their alien race.
Lore wise you could just say that NT gives 0 fucks, works just fine with their track record.

**Comment by VelardAmakar** [comment]
gas the vox
drown the grey
powderize the skeletal
burn the diona
human pride stationwide

**Comment by dylanstrategie** [comment]
>Silicons should only kill non-humans when ordered to and when they are harming humans or trying to destroy them, and silicons can ignore non-human orders at their discretion

My only position on the matter

**Comment by Boxe** [comment]
no

**Comment by d3athrow** [comment]
no

**Comment by 9600bauds** [comment]
Although I'll say "no" because changing Asimov would make it not-Asimov, alien races could seriously use some better thought-out rebalancing, currently.

**Comment by Senaat1** [comment]
Nah, it's a downside to being an alien. Nanotrasen is a humans-first company that hates their cheap immigrant labour and doesn't mind them dying, apparently. It's a perk of being human.

**Comment by Probe1** [comment]
obligatory no

**Comment by ComicIronic** [comment]
There's an interesting case in That Thou Art Mindful Of Him of a robot bird eating a load of midge flies, but it's part of its design. Since robots lack any reason to do things for fun or just because, it never happens.

**Comment by Probe1** [comment]
That was a very knowledgeable and impressive response.

**Comment by clusterfack** [comment]
gas the vox
