### ISSUE TITLE
(WEB REPORT BY: volfgarix REMOTE: 198.245.63.50:7777) Egg-Plant-tomato mix

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3759]
So, as we know Egg-plants can't have seeds, so I tried to mix Eggplant with tomato for multiple types of fruits (think wheat-tomato combo), then mutate it into modified Egg-Plant, so it would grow eggs as main resource and tomatoes as seed source, but after species change, it reverts back to growing only one type of fruit-eggs

**Comment by 9600bauds** [comment]
Egg-plants can have seeds, just use wirecutters on them.
Did you try harvesting the plant multiple times? The fruiting results are random, sometimes you'll only get one type of fruit per batch.

**Comment by ComicIronic** [comment]
Is it a bug, or isn't it?

**Comment by 9600bauds** [comment]
It works as intended, it just disallows you from splicing the plant before mutating it to another species. But that's fairly minor and would require a rework of species mutations.

**Comment by Kurfursten** [comment]
@clusterfack WAD, please close
