### ISSUE TITLE
Harm-Telescopic Baton triggers clown defect when using it on a clown to a clown

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3762]
Appears to have the chance of knocking you out for a good 30 seconds, A feature that regular batons dont.

**Comment by dylanstrategie** [comment]
I'll give it a check

**Comment by dylanstrategie** [comment]
If you are clumsy, you risk hitting yourself for a lucridious 45 seconds stun and 30 damage. Taken directly from the code

**Comment by CptWad** [comment]
Oh god I think when you are a clown the clumsy affects OTHER peoples use of it
I was hit with a baton from the HoS and it caused the 45 second stun and massive head trauma

**Comment by dylanstrategie** [comment]
It fires on afterattack, which is suspicious

If that's true though, you can knock the Clown out for almost a full minute with the telescopic baton
