### ISSUE TITLE
(WEB REPORT BY: drcelt REMOTE: 198.245.63.50:7777) Off instead of of

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3766]
That's some metal. They are a normal-sized item.
Sheets made out off metal. It has been dubbed Metal Sheets.

"made out off"
"off"

**Comment by MercuryDoll** [comment]
kind of a minor typo. what irks me more is "You put the the screwdriver into the satchel", works with every tool
