### ISSUE TITLE
(WEB REPORT BY: drcelt REMOTE: 198.245.63.50:7777) PANIC, SINGULARITY RELEASED ITSELF FOR NO GOOD REASON

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3770]
>Revision (Should be above if you're viewing this from ingame!)
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba

>General description of the issue
0x2003422] (104,56,1) || Emitter lost power and turned off
[0x2003434] (122,56,1) || Emitter lost power and turned off
 [0x20035be] (104,64,1) || Emitter lost power and turned off

>What you expected to happen

The singularity not to have a technological singularity and gain the ability to free itself 

>What actually happened

ADMIN LOG: A singulo exists and a containment field has failed.

>Steps to reproduce if possible

Not a clue

**Comment by clusterfack** [comment]
Emitters without enough power to supply themselves turn off, there really needs to be something more to this to actually think this is a "bug"

**Comment by dylanstrategie** [comment]
Now that we actually fixed shit magically working without power, we should consider giving Emitters internal batteries or something

Otherwise, this is going to happen again and again

**Comment by clusterfack** [comment]
Well I guess part of the problem here is that emitters dont turn back on after they lose power and turn themselves off, and engineers have no way of knowing that it occurred because they dont just stay and watch the singularity. Even with internal batteries nobody gives enough of a shit to look at the emitters.

**Comment by dylanstrategie** [comment]
Then it's a problem with Engineers. We could always add more monitoring apparatus, but the Engineers will learn to actually check the tenth time in a row where a singularity goes loose because the Engineering power shat itself

**Comment by clusterfack** [comment]
Well you may need to remap it so the left SMES only powers the engineering APC and the emitters. Then have both the left SMES and the right SMES fed from a second powernet that comes from the rad collectors. That should solve this issue pretty well.

**Comment by clusterfack** [comment]
I did some testing on the test server.
(YAY TEST SERVER)

Apparently the emp from lord singulo is turning off emitters. I'll investigate why and fix the issue.

**Comment by ComicIronic** [comment]
Supposedly fixed, but might need to be left open.

**Comment by clusterfack** [comment]
So yeah I confirmed the issue was just the singularities EMP in engineering disabling power for one tick, emitters repower after one fire delay now so the issue is null.
