### ISSUE TITLE
While pulling things you can sometimes slip.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3771]
Pull something
Click around you while moving
occasionally you will get a You slipped! message
As if you are in space
Which would be weird since you are in the middle of the hallway

**Comment by Probe1** [comment]
if you move a locker under your feet you'll slip.  it's kinda funny.

**Comment by CptWad** [comment]
Its still a bug. Usually works when pulling things underfoot of you or rapidly around you.

**Comment by clusterfack** [comment]
I've found all the relevant things to fix this, I'll probably do so soon
