### ISSUE TITLE
(WEB REPORT BY: deadpoolj REMOTE: 198.245.63.50:7777) Cannot pick Assistant at all.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3777]
>Revision (Should be above if you're viewing this from ingame!)
3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

>General description of the issue
I cannot play Assistant, even though I am not jobbanned from it at all. I set my job prefs to Assistant only, and Assistant when no jobs are available.

>What you expected to happen
To be a fucking assistant.

>What actually happened
I'm a barkeep or a Roboticist or something.

>Steps to reproduce if possiible
I set my job prefs to Assistant only, and Assistant when no jobs are available.

**Comment by BestName** [comment]
What's the issue? :^)

**Comment by Ephx1** [comment]
This is a great feature

**Comment by PJB3005** [comment]
#3713

**Comment by clusterfack** [comment]
I think @d3athrow fixed this already
