### ISSUE TITLE
(WEB REPORT BY: eldorado12345 REMOTE: 198.245.63.50:7777) Hold item then restrained and hold another item with first then uncuffed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3782]
>I was restrained, someone puted clown backpack at my hand, then i was unrestrained i can't took off backpack, but can hold items in bugged hand.

>I don't exept anything.

>This bug.

>
1. Be a clown.
2. Restrain themselves with cable.
3. Put clown backpack at right hand.
4. Uncuff.
5. ????
6. PROFIT

**Comment by CptWad** [comment]
similar to #3739

**Comment by clusterfack** [comment]
Fixed along with #3739
