### ISSUE TITLE
Wizard nerfs not based on reality.

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#3786]
There has recently (?) been a massive nerf to magic missile.
Magic missile is necessary for wizards who do not wish to use cheap tricks like raiding the armoury or using the captain's laser; there is no other spell that only stuns people, and as the game's combat is all about getting stuns in, the only alternative is for a wizard to use tasers.
I stood next to someone and casted magic missile, and it didn't stun them; I'd like this change to be reversed and instead for spells
You can't nerf magic missile, the bread and butter of wizards, and not nerf disintegrate, generally considered to be one of the most overpowered wizard spells.

**Comment by DrLeprikon** [comment]
Wizard spells in general seem to encourage shittery: fireball and Ei Nath are the two most boring and yet most powerful spells. While previously non-lethal Magic Missile now deals damage and Mind Transfer, which is good for gimmicks, gives you a chance to loose your spells. It's no wonder people murderbone as wizard.

**Comment by ComicIronic** [comment]
This is actually a bug, not an intended nerf.
I'll look into it.

**Comment by clusterfack** [comment]
Perhaps the projectiles aren't spawning when targets are adjacent

**Comment by ComicIronic** [comment]
No, the odd thing is that the message still seems to be playing for the projectile going off, but I think the targets is empty for whatever reason.

**Comment by CptWad** [comment]
Hold on was this nerf the "The magic missle pops with a flash!" stuff?
It was added in response to a bug where magic missiles would bug out and kill anyone in a 3x3 square instantly and stay in one spot. It was both hilarious and strange.

**Comment by ComicIronic** [comment]
>Hold on was this nerf the "The magic missle pops with a flash!" stuff?

No, what the issue was referring to was a bug where if you cast MM next to a target, the flash message would appear but they wouldn't be stunned.
