### ISSUE TITLE
Emitters don't kill people if the person is in the way of the emitter when it's turned on

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#3787]
Apparantely emitters only harm people when they move into an emitter laser, rather than if an emitter is turned onto them.

**Comment by ComicIronic** [comment]
Beams are bizarre as hell.
If only we still had the baldman to bugfix them.

**Comment by DrCelt** [comment]
RIP

**Comment by clusterfack** [comment]
If you could turn on a beam and harm someone, wouldn't that result in being able to turn on and off a beam several times in a second and do INSANE damage?

**Comment by ComicIronic** [comment]
That could be solved by giving emitters a setup time.
Beams should still damage what they hit.

**Comment by PJB3005** [comment]
beams damage stuff over a period of time, not even once every process(), so it wouldn't matter if you spammed reactivating emitters

**Comment by clusterfack** [comment]
What you guys are saying doesn't seem relevant to what I said, is this report supposed to be that emitters -never- damage objects its turned on to?

**Comment by Kurfursten** [comment]
I believe that clusterfack and DrCelt are right. As I recall, I was attempting to kill someone with the emitters recently and I thought I had done something wrong because they weren't dying. I suggest we do a formal test, but for now treat this as no one taking damage from emitters.

**Comment by ConkerDev** [comment]
Not an issue anymore, aparently

**Comment by clusterfack** [comment]
Yeah this works fine now
