### ISSUE TITLE
(WEB REPORT BY: megamaw REMOTE: 198.245.63.50:7777) I can't print manuals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3791]
>Revision 3400f3967657bb4753aa33ba3c4eb2aa2fd200ba 

>General description of the issue
I literally can't print manuals. I've tried time after time. Something must have broken it.

>What you expected to happen
A manual to be printed.

>What actually happened
No manual.

>Steps to reproduce if possible
Click on a manual name. Watch as it doesn't print!

**Comment by NigglyWiggly** [comment]
https://github.com/d3athrow/vgstation13/issues/3655
Library stuff is still a bit wonky after the big overhaul thing

**Comment by clusterfack** [comment]
Duplicate of #3655
