### ISSUE TITLE
(WEB REPORT BY: manfreed REMOTE: 198.245.63.50:7777) dropping flashlight from broken hand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3796]
>Revision (Should be above if you're viewing this from ingame!)
_nothing_

>General description of the issue
dropping a flashlight from a broken hand doesn't stop it's effect, it can be picked up again and again for maximum brightness

>What you expected to happen
That the light goes off

>What actually happened
It didn't

>Steps to reproduce if possible
-break hand
-pick up flashflight
-wait untill it gets dropped
(repeat if you want)
-go to a dark place

**Comment by ComicIronic** [comment]
I believe this is to do with using u_equip, which doesn't call dropped.

**Comment by 9600bauds** [comment]
I'm also fairly sure you can drop the "fireaxe 2-handed icon" dummy item by breaking one hand and dualwielding a fireaxe with the other.

**Comment by ComicIronic** [comment]
It all falls under the same issue.

**Comment by dylanstrategie** [comment]
This was fixed, but incorrect formatting. Close this
