### ISSUE TITLE
[Box, probably others] Vox storage room has non vox flooring, thus the atmos alarm at round start.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3799]

**Comment by Exxion** [comment]
I don't think the other maps even *have* Vox storage rooms (or trading outposts at all, for that matter). Also, if I remember correctly, it is Vox flooring, but for some reason it still has air rather than pure N2 because of inheritance fuckery or something

**Comment by PJB3005** [comment]
I checked, it aint vox flooring, and I think taxi also has a trading post, and it looks like just a copy paste, so it might affect taxi too.

**Comment by Exxion** [comment]
Huh. You're right. What the hell was I thinking of, then?
Anyway, easy fix which I'm too tired to do right now but will probably do tomorrow if nobody else does first
I was going to fix it a while ago, but I wasn't entirely certain whether it was intended or not.
