### ISSUE TITLE
what the hell was this

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#3802]
OOC: Gontran: OH JESUS WHAT HAPPENED TO THE CHARACTER MAKER?
OOC: Dr. Explosion: i just saw it too

Current Admins (1):
	DrCelt is a A Legend That Lost His Cause - Lobby

Current Moderators (0):

OOC: DrCelt: what do you mean
OOC: Stairmaster: OH GODDDDDDDDDDDD
OOC: Gontran: Check Setup Character
OOC: Gontran: PANIC
OOC: DrCelt: WHAT'S GOING ON IT HASN'T LOADED YET
OOC: Oliver Klohsoff: Sitill better than original.
OOC: Dr. Explosion: can't set occupation preferences
OOC: Oliver Klohsoff: You guys are spoiled
Job setup complete
OOC: DrCelt: >still won't load
OOC: Jewishneocon: we broken
OOC: Stairmaster: I can't see the lobby
Processing Geometry...
Geometry initialized in 1.7 seconds.
Total Simulated Turfs: 24834
Total Zones: 1139
Total Unsimulated Turfs: 365316
Searching for away missions...
No away missions found.
Initializing objects
OOC: Stairmaster: I don't think we connected properly
OOC: DrCelt: WHAT THE FUCK
Welcome to the pre-game lobby!
Please, setup your character and select ready. Game will start in 300 seconds
Initializing pipe networks
Initializing atmos machinery.
Initializations complete.
Caching Jukebox playlists...
OOC: Saronsen: who was the admin or whatever talking about singuloth with me
OOC: DrCelt: HOLD UP
OOC: DrCelt: IT JUST
OOC: Dr. Explosion: ITS HABBENING
OOC: DrCelt: IT JUST LOADED SHIT THERE
OOC: Gontran: Daym son

**Comment by DrCelt** [comment]
http://i.imgur.com/kfXWIUK.png?1

**Comment by DrCelt** [comment]
http://i.imgur.com/Czk6Ia5.png

**Comment by eswordthecat** [comment]
Bad compile.

**Comment by clusterfack** [comment]
^
