### ISSUE TITLE
Everyone is Bald on Round Start

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3815]
I'm concerned about the radioactivity of the station.

**Comment by CptWad** [comment]
Its not everyoe but sometimes hair does not load.
Think it might have something to do with job selection, maybe hair gets its second best option and since its null you go bald or something

**Comment by MercuryDoll** [comment]
Weren't additional hairstyles recently added? Think i remember a PR about animu hair, maybe that broke it.

**Comment by Probe1** [comment]
feels like it only happens when people join before the round start initialization has occurred, which has been happening frequently due to recent changes I suspect.

**Comment by ComicIronic** [comment]
Has this ever happened since?

**Comment by clusterfack** [comment]
I never saw this happen in the first place and not since

**Comment by Ephx1** [comment]
I've seen it sometimes happen as miner, and when Taxi station first rolled out.

**Comment by clusterfack** [comment]
Didn't it happen as a miner due to being a dwarf? Also wasn't that removed?

**Comment by Ephx1** [comment]
I couldn't tell you about that, if they were dorfs they were severely lacking beards.

**Comment by clusterfack** [comment]
Well I'm just saying that if one role is bald its very different than everyone spawning bald in terms of the  bug report so I'd imagine there's another reason for it unrelated.

**Comment by ComicIronic** [comment]
The issue with Taxistation the very first time was the lack of an accounts database breaking character creation, and for miners it was the dwarf gene start which was removed.
