### ISSUE TITLE
(WEB REPORT BY: rounders REMOTE: 198.245.63.50:7777) new hairs bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3825]
new hairs give a text error on the character and dont show up, the text error is F_Style ERROR

**Comment by PJB3005** [comment]
I've seen this, and can confirm something's up

**Comment by MercuryDoll** [comment]
this should be known by now since right after this was found out we had someone gimmick complete with the name F Style ERROR and just that "hair", amongst others.

**Comment by Intigracy** [comment]
I've seen nothing of the sort in recent memory, fixed?

**Comment by PJB3005** [comment]
I think this was a BYOND issue fixed by updating the server?

**Comment by clusterfack** [comment]
Fixed apparently
