### ISSUE TITLE
Magic Missile

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3826]
You can apparently hit yourself with your magic missile projectiles now.

Saw: A wizard using magic missile, 3 missiles were apparently spawned but none of them were spawned visibly, apparently they all hit the wizard. He was in the line at the HoP's office when it occurred.

**Comment by ComicIronic** [comment]
I specifically recall coding against this, and it not happening in testing.

**Comment by clusterfack** [comment]
Yeah it just gave a message of the magic missile pops with a flash and the wizard got knocked down, I didn't even see any magic missiles in the first place after he cast the spell.

**Comment by dylanstrategie** [comment]
Might be caused by the magic missiles popping on the same tile as the Wizard (if he was in line at the HoP and surrounded by other players)

**Comment by ComicIronic** [comment]
Cannot reproduce.

**Comment by CptWad** [comment]
I think this was fixed with another MM bug or something
