### ISSUE TITLE
Stripping people (or using that menu in general) is broken for people on tables

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3828]
Morgue slabs included too

**Comment by MercuryDoll** [comment]
refer to https://github.com/d3athrow/vgstation13/issues/3743 which is probably the same

**Comment by Killette2** [comment]
To be honest, not stripping people on tables would be good balance. When is the last time you found it easy to take someone's entire outfit off while they are laying down on a table? Standing up cuffed I could understand, but tablescrubbing has got to go.

**Comment by MercuryDoll** [comment]
No, don't. At least not for surgery tables. Make it take longer when on a table etc if you want it "realistic", but it should still be working. Especially toggling internals.

**Comment by ComicIronic** [comment]
DUPLICATE OF #3743
