### ISSUE TITLE
Missing & Broken span endings.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#3834]
If you log your chat window, you will notice deterioration of the consistency of things like color and font, as seen in the picture, that is not how chat like that should look, I'm gonna assume this is cuased by span endings being incorrect, I recommend trying to track these down in something like chrome's inspect element, one example of this (that I could quickly see) is a "You feel nauseous..." message, after this, all text was italic, and upon further examination, the warning span in indeed not being ended

![](http://i.imgur.com/coh0bZ5.png)

**Comment by dylanstrategie** [comment]
I'll forward a fix. For further reference, an admin can fix this by global narrating "</B></I></span>"
