### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) RPD No Dual Port Vent

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3839]
So to make an airlock system like the xenoarchelogy (pressure chambers regulation for in/out) i need the Dual Port Vent so i can pressure/depressure the room,but the RPD doesn't have that one

**Comment by Probe1** [comment]
dual port vent is  missing sprites when unwrenched

**Comment by clusterfack** [comment]
Hey he added it!
