### ISSUE TITLE
Silicons can't use the Pill Vendor

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3841]
I don't even know why this is still a thing. You can't interact with it in any way if you're a silicon, save for dumping pills into it using a pill collector if you have the medical module.

**Comment by MercuryDoll** [comment]
Neither can they use the artificial organ fabricators.

**Comment by ririchiyo** [comment]
I intentionally made it so they couldn't use the organ fabricators since they cannot actually pick them up.

**Comment by MercuryDoll** [comment]
ah, okay. Probably makes sense to balance human surgeons, but silicons should be able to vend pills from the medicabinet i guess. awful when the chemist actually did its job and packed the fridge with drugs that won't be used.
