### ISSUE TITLE
(WEB REPORT BY: megamaw REMOTE: 198.245.63.50:7777) Certain actions cannot be performed on a Janicart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3842]
>Revision (Should be above if you're viewing this from ingame!)
1848d2572f8381a5cd825f4c5aeb8a3f31cfd215 

>General description of the issue
Okay, so you can't use *emotes (*salute, *nod, etc) while on the janicart. In addition, you cannot take books from bookshelves. I feel like the two issues may be related. Also, you can't pull things while on the janicart but I'm not sure if that's working as intended.

>What you expected to happen
These things work.

>What actually happened
They didn't!

>Steps to reproduce if possible
>get on janicart
>try pulling things/taking books from bookshelves/using *emotes
>???
>Failure!

**Comment by dylanstrategie** [comment]
- Emotes have been tested and work as intended
- Taking items from bookshelves indeed doesn't work. I'll give it a check in a moment
- I am almost certain that not being able to pull things while mounted on a vehicle is intended
