### ISSUE TITLE
(WEB REPORT BY: fudgepucker REMOTE: 198.245.63.50:7777) Tvalve in outpost still fucked (box)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3843]
>Revision (Should be above if you're viewing this from ingame!)
cfd215

>General description of the issue
The Tvalve in the outposts atmos is still fucked up.
This bug also effected atmospherics back on station and the ininerator. But was fixed.

>What you expected to happen
It to not be fucked up

>What actually happened
Its fucked up

>Steps to reproduce if possible
Look at it. See its fucked up.

**Comment by ComicIronic** [comment]
Apparently fixed.
