### ISSUE TITLE
(WEB REPORT BY: iconleap REMOTE: 198.245.63.50:7777) Bar box

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3844]
Entertainment monitor is missing
PANIC!!111

**Comment by dylanstrategie** [comment]
There are two entertainment monitors, one behind the counter, and another near the toilets inside the Bar

Not an issue

**Comment by clusterfack** [comment]
>Esword using ingame bug report.

Whyyyyy
