### ISSUE TITLE
(WEB REPORT BY: nevillbamshoot REMOTE: 198.245.63.50:7777) bomb not gibbing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3845]
When I strapped c4 to myself it didnt gib me when it exploded, it just moved me a little bit. I then made a larger bomb and blew it and the same thing happened.

**Comment by d3athrow** [comment]
c4 worked for me, normal bombs will only gib if mob is in devestation range, or in heavy range if they're dead.
