### ISSUE TITLE
double double agent

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#3846]
you can have both of the double agent traitors be the same person.

**Comment by Probe1** [comment]
https://www.youtube.com/watch?v=6iaR3WO71j4

**Comment by dylanstrategie** [comment]
I don't see where this could happen, code-wise. That's odd

**Comment by ComicIronic** [comment]
This should have been fixed, but I'm leaving it open in case someone reports it again.

**Comment by DrCelt** [comment]
Haven't seen this reported again and it's been more than a month
