### ISSUE TITLE
Can't pour contents of chem bottles into bluespace beaker.

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#3849]
If you have chemicals in a bottle (chemmaster bottles) and try to transfer it into bluespace beakers it just splashes them on it. Beaker was unlid.

**Comment by d3athrow** [comment]
im able to transfer fine. ![asdf](https://a.pomf.se/axfxbp.png)

**Comment by MercuryDoll** [comment]
might have been a one-time glitch, couldn't reproduce either.
