### ISSUE TITLE
[bug] Borgs handing metal to people with alt click causes issues

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3850]
Borg gets metal in its hand -> borg alt click hands metal to player -> wat

It winds up in your backpack slot somehow and if another is handed it ends up in your hand but invisible
![ss 2015-04-09 at 01 12 05](https://cloud.githubusercontent.com/assets/8550416/7073753/a93d246c-dec3-11e4-9c22-aaa9249f7a1b.png)

**Comment by d3athrow** [comment]
silicons dont even have access to this proc.
