### ISSUE TITLE
(WEB REPORT BY: drleprikon REMOTE: 198.245.63.50:7777) No gibtonite on Metaclub roid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3853]
> Revision 
> ddb513324170127e69a318feddc4ba47be2e83a3 
> 
> General description of the issue
> Gibtonite doesn't seem to spawn on Metaclub, just diamonds.
> 
> What you expected to happen
> Get exploded, upset, bleed out and never get cloned
> 
> What actually happened
> I got a sack of diamonds ten minutes in, all the girls were mine and life was wonderful. Please fix.
> 
> Steps to reproduce if possible

**Comment by ComicIronic** [comment]
Weird.
Maybe you went mining in the high-yield zones?

Maybe it's all high-yield zones.

**Comment by DrLeprikon** [comment]
It was the east part of the roid, literally right out the outpost's door. I got over fifty diamonds, I never had that many diamonds before. The yield was much lower over on the west roid, but still higher than usual.

**Comment by Probe1** [comment]
@ComicIronic this isn't the first time this has happened.  The first time we played metaclub it was this way.  Weird that its back to how it was.  ~~Don't fix it, moneymoneydollarbillyall~~

**Comment by Probe1** [comment]
the east side of the roid is all HIGH YIELD that doesn't contain gibtonite.  the west side is normal and will have gibtonite.  reworking the roid is on my to-do list so i'll get around to closing this eventually.

![dreammaker_2016-04-10_14-07-42](https://cloud.githubusercontent.com/assets/8550416/14412001/aa6743da-ff25-11e5-819e-abe338e70cbc.png)

**Comment by Probe1** [comment]
Can close.  The issue was a misunderstanding by the user on how mining works from a code/mapping perspective.

**Comment by Probe1** [comment]
@DrLeprikon <3
