### ISSUE TITLE
Mediborg beaker unusuable

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#3855]
When you activate the beaker module, insert it into the chem dispenser, then "store" the beaker module again while the beaker is still in the machine, you can't reactivate the beaker module.
Any changes to the physical beaker is displayed in the borg's module HUD, but you can't pick it up again.
Perhaps not allowing to store the module while the beaker is in use?

**Comment by ComicIronic** [comment]
The storage button needs a check on loc.
