### ISSUE TITLE
The mutant plump helmet mushrooms's flowers <font=#00FF00>changes colour!

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#3857]
pretty self explanatory

**Comment by MercuryDoll** [comment]
It's funny because i don't think flowers are even implemented yet.

**Comment by ComicIronic** [comment]
Should be <font color =#00FF00>, I believe.

**Comment by PJB3005** [comment]
or it should be a span

**Comment by ririchiyo** [comment]
It should be a <span> if we're going to follow the HTML5 specifications because <font> is defined as non-conforming element: http://www.w3.org/TR/html5/obsolete.html#non-conforming-features

**Comment by 9600bauds** [comment]
Since flowers are unimplemented (and I don't think anyone has any plans of implementing them), would anyone be against commenting the flower mutations out entirely?
