### ISSUE TITLE
(WEB REPORT BY: 1pirateguy REMOTE: 198.245.63.50:7777) Ian eats hats he can't wear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3859]
>Revision (Should be above if you're viewing this from ingame!)
5610615fb3920d22cefabbbe28720197b1b67792 

>General description of the issue
if you put a hat on Ian that he can't wear, it disappears entirely as if it was deleted

>What you expected to happen
Ian to not eat the fucking hat

>What actually happened
he ate it

>Steps to reproduce if possible
put a hat Ian can't wear on his hat, such as the HoP cap or Captain's alt hat

**Comment by ComicIronic** [comment]
I swear this was fixed.

**Comment by clusterfack** [comment]
Looks like numerous people fucked up in thinking drop_item actually makes you drop an item from your hand, and never set its location to the floor.

**Comment by ComicIronic** [comment]
No,, as in I swear Sanade made a fix for this. I recall the PR. #3753.

**Comment by clusterfack** [comment]
That is part of what I'm talking about too, he made the same mistake

**Comment by ComicIronic** [comment]
drop_item does make you drop the item, though. The arg sets its location.
That code is the correct use of it.

**Comment by d3athrow** [comment]
Fixed with #3876
