### ISSUE TITLE
(WEB REPORT BY: arachnidgrip REMOTE: 198.245.63.50:7777) Intercoms cannot be deconstructed or constructed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3864]
>Revision

bba111625fa3428f37c068d63533268cb1047a9f 
>General description of the issue

I'm a librarian trying to make intercoms, but for the life of me I could not figure out how to construct them. I tried every tool and even used some out of the box options, but I couldn't get it to work. I tried to deconstruct one to figure out if I was missing something, but after cutting all the wires, I was stumped as to how to continue. I don't think a way to construct or deconstruct them has been programmed.

>What you expected to happen

To be able to construct an intercom that works just as well as the intercoms around the station.

>What actually happened

Unable to construct any intercoms, or deconstruct them.

>Steps to reproduce if possible

Spawn an intercom frame and place it on the wall. From there there is nothing you can do. To deconstruct, screwdriver the intercom and cut all the wires. From there, the process comes to a halt.

**Comment by clusterfack** [comment]
Intercom electronics

**Comment by PJB3005** [comment]
yep, intercom electronics, this isn't a bug
