### ISSUE TITLE
[Feat Req] Energy weapons light plasma

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#3866]
Laser guns, tazers and energy swords should logically light plasma on fire, no? Discuss.

**Comment by CptWad** [comment]
Energy swords are swords of pure energy.
Hence forth, like a lightsaber, cannot light things on fire because it disintegrates them
Due to this, any plasma that would interact with an esword would go poof rather catch fire

**Comment by ComicIronic** [comment]
>go poof rather than catch fire

Except releasing energy causes things to heat up and catch fire.
Not to mention the idea that an energy sword instantly annihilates the matter around it would make it hotter than the sun.

**Comment by CptWad** [comment]
this is videogames.
Also the thought of someone waving around an esword to catch the air on fire is silly. just imagine some dork waving around a glowing dildo in a room filled with purple dots

**Comment by Shadowmech88** [comment]
It's already possible to light a cigarette using an esword. Why not anything else flammable?

**Comment by Kurfursten** [comment]
@deitylink did your gun revamp touch on this?

**Comment by DeityLink** [comment]
@Kurfursten it didn't. I thought I shouldn't touch it for balance reasons. Such a change deserves its own PR for people to discuss it.
