### ISSUE TITLE
[Bug] Pocketing light sources then picking up new light sources cancel the pocketed ones.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3867]
Interesting bug and I think its related to multiple issues that have been reported on hardsuit helmets and lanterns failing to work after a random duration https://github.com/d3athrow/vgstation13/issues/3111

Spawn some flashlights.  Turn them on.  Put them in your pocket.  Now pick up two more and turn them on.  The original flashlights in your pocket no longer produce light.  If you turn off the flashlights in your hands you're left with no light.

here's a webm of it in depth
http://a.pomf.se/rhbuxr.webm

**Comment by ComicIronic** [comment]
Maximum luminosity, yay!
I believe this is to do with the lighting overflow bug Byond had a while ago.

**Comment by clusterfack** [comment]
Well pomf did cap luminosity at 7, didn't he? Perhaps you are right that could be the issue.

**Comment by ComicIronic** [comment]
>Well pomf did cap luminosity at 7, didn't he?

No, it's a Byond thing. Pomf only capped it at 7 because otherwise the extra bit overflows into the gender var, contributing to TG's infamous spontaneous dixel.

Luminosity is only 3 bits, for whatever reason, but I think they fixed the overflow in the newest Byond version.

**Comment by clusterfack** [comment]
Yes he capped it at 7 because of the luminosity issue, which is what I am saying could be the cause of this.

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/commit/993599dfd33e0ce8d8ea90498bff56c2ea5522c5
^ see

**Comment by CptWad** [comment]
When pocketing flashlights I still lose the light.
