### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) pAI cancel Camera view

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3878]
>Revision (Should be above if you're viewing this from ingame!)
b7081790c4b29efaff2303810955a04d89c6224e 

>General description of the issue
AI tab has a cancel camera view and I decided to click it

>What you expected to happen
I don't know

>What actually happened
Got sent to centcom for no raisin

>Steps to reproduce if possible
Click the cancel camera view option in pAI command tab

**Comment by d3athrow** [comment]
cant reproduce.

**Comment by Kurfursten** [comment]
@clusterfack Can't reproduce, close
