### ISSUE TITLE
(WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) MoMMIs can't open packaged crates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3879]
>Revision b7081790c4b29efaff2303810955a04d89c6224e

>General description of the issue
Title

>What you expected to happen
The crate would be unwrapped

>What actually happened
Nothing

>Steps to reproduce if possible
1.Be MoMMI
2.Wrap a crate with package wrap
3.Click on the wrapped crate.
4.Be pissed because you can't get whatever you put in the crate back.

**Comment by ComicIronic** [comment]
The default for MoMMI behaviour should be the same as human behaviour, but welcome to click-code.

**Comment by PJB3005** [comment]
probably some outdated check so borgs can't open them.

**Comment by CptWad** [comment]
I have not played borg for at least a week but I know for a fact you can open close and lock lockers but not unwrap them
Its really a trick but also really weird how it all works. I think originally robots could not use closets as some balance thing but at this rate every person with maint access who does not open every container they see is a waste of access. Never understood why robots just cant into locker

**Comment by PJB3005** [comment]
I think borgs can with a crowbar, but it's still annoying.
