### ISSUE TITLE
[Feature Request] Add buildable Mr. V.A.L.I.D. Portable Threat Detectors

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3880]
I was making a checkpoint and couldn't construct them.  Fuck that.  Add em, they're benign enough.   
@Kurfurst you're keen on dorfmode additions and this wouldn't go awry.

**Comment by ComicIronic** [comment]
>benign enough
>able to spot a ling with no tells at all

Dear god, the horror.

**Comment by Probe1** [comment]
okay scouts honor i was the one that was saying you could spy a ling with them in the thread on more than one occasion and I started to question what I had said.  so I did some testing and actually you can't.  it's a feature on other servers but not ours.  mr valids only do no IDs, hidden guns, and so on.  everything on the tin and nothing more.

**Comment by Probe1** [comment]
If you can make a valid detector buzz because a ling passed by, I'd love to see how.

**Comment by clusterfack** [comment]
Mr valids do not actually give you your valids, I thought the name was meant to be ironic.

**Comment by ComicIronic** [comment]
I remember Mr Valids actually providing Valids detection at one point, before someone decided it was a correctly terrible idea.

**Comment by Kurfursten** [comment]
Probe1 Yeah I can add it to my con/decon list, though as a mobile item it seems more appropriate to be ordered from Cargo if I'm honest with you.
