### ISSUE TITLE
[Spriting] Large Bluespace Beakers still don't have a sprite for the lid

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3881]
I personally hold @skowron accountable because i mentioned this in passing to him once several months ago.  However I think its time to get on it and make a proper issue.  No lid no peace.

![image](https://cloud.githubusercontent.com/assets/8550416/7105906/d698dcc6-e0fd-11e4-9bb7-69a67a858e43.png)

**Comment by clusterfack** [comment]
I like how the lid for the regular bluespace beaker looks like the lid you would expect to see on a large bluespace beaker

**Comment by Skowron** [comment]
Stop sending a message to me

-----Wiadomość oryginalna-----
Od: "clusterfack" <notifications@github.com>
Wysłano: ‎2015-‎04-‎12 16:39
Do: "d3athrow/vgstation13" <vgstation13@noreply.github.com>
DW: "Skowron" <skomat21@gmail.com>
Temat: Re: [vgstation13] [Spriting] Large Bluespace Beakers still don't havea sprite for the lid (#3881)

I like how the lid for the regular bluespace beaker looks like the lid you would expect to see on a large bluespace beaker

**Comment by SkowronX** [comment]
@Skowron fug

**Comment by Probe1** [comment]
awkward

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/7196154/b8d97542-e49a-11e4-8edd-fab980fb2498.png)


YA BLEW IT

**Comment by Probe1** [comment]
@dylanstrategie

**Comment by ComicIronic** [comment]
I'm genuinely worried about the implications this has of how much the fix PR was actually tested.
