### ISSUE TITLE
[BOMBERMAN] Can't remove suit or any eyewear while wearing helmet

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3884]
![bomberman_2](https://cloud.githubusercontent.com/assets/8550416/7107159/0cedf600-e129-11e4-818a-03e287c1df31.jpg)

**Comment by Probe1** [comment]
Also bombs destroy the bomb device you hold which is kinda an issue.

**Comment by DeityLink** [comment]
>working as intended
>working as intended

**Comment by Probe1** [comment]
fair enough, but having the bombs destroy the bomb device before killing the player is awkward.

**Comment by DeityLink** [comment]
the bombs are non-lethal by default though.

**Comment by Probe1** [comment]
That makes sense but it takes away the competitive luster if the player is still in the arena but disarmed and forced to wander around looking like a competitor but being unable to act.

**Comment by DeityLink** [comment]
unable to act? this is SS13 for crying out loud, disarming other players and stealing their BBD is a valid move :>

**Comment by Probe1** [comment]
THATS DIRTY and i'd do it if no one was watching
