### ISSUE TITLE
You cant shoot in the dark

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3885]
2spooky :ghost:

**Comment by d3athrow** [comment]
I dont understand

**Comment by clusterfack** [comment]
You cant click the tiles that are totally blacked out to shoot at them, I think

**Comment by CptWad** [comment]
Yeah thats pretty much it.
You also cant throw things in the dark meaning that if you are in a situation in the dark you can get dunked even if you are way outgunning them because you cant shoot the one tile in frount of you

**Comment by d3athrow** [comment]
If its so dark that the tile next to you reveals nothing when right clicked then theres no way to fix that.

**Comment by clusterfack** [comment]
Cant we make it so obj/screen is clickable?

**Comment by PJB3005** [comment]
Don't think so

This is BYOND we're talking about, you know

**Comment by CptWad** [comment]
Aight so no shots in the dark. I dont feel upset by this anymore after some nukeops rounds.
