### ISSUE TITLE
Empty vendors can't be stocked.

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#3889]
Vendors have three issues:
1.  deconstructed vendors do not drop a package with their contents. (not sure if they can be filled with only what was left in the vendor, so balance might ignore this)
2. deconstructed vendors always spawn a coin box, but don't need one to be constructed. Ends up with unlimited coinbox works
3. The most glaring one: after (re)constructing the vendor, it can't be filled with a recharge pack. Hence it stays being a useless empty vendor.

**Comment by Probe1** [comment]
i tried it out myself and 3. is indeed fucked up.  I can't find a way to add vending packs to empty vends.

**Comment by Boxe** [comment]
i managed to create a new vendor after deconning one, are you sure about 3.?
