### ISSUE TITLE
[Feature Request] Tie amount of biomass in a cloner to the console and not the machines

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3894]
Here's the problem.  You're a mechanic.  You want to replace Medbays cloner with Tier 3 parts so they can clone super fast.  So you disassemble the two machines and now all that biomass they added is GONE.  

If there was a way to disassemble the cloning pod and cloning scanner machines without losing the added biomass it would make me soo happy.

**Comment by dylanstrategie** [comment]
Not an issue anymore, unless you want to move the machine

I would say, add some sort of biomass container or the like, but it'd take quite a bit of coding to avoid snowflakes

**Comment by Probe1** [comment]
What do you mean by "Not an issue anymore"?

**Comment by ComicIronic** [comment]
>want to clone a body
>put the corpse in the scanner
>start typing to access records
>monkey meat starts squeezing out from under the keys

As an alternative suggestion, disassembling the cloner should just eject the biomass as meat slabs.

**Comment by Probe1** [comment]
that works too.  anything except losing biomass which is worth more to medbay players than upgrades.

**Comment by clusterfack** [comment]
So if someone could get around to making cloners not start with 150 biomass, only map placed cloners (like chem dispensers do) starting with 150, that would be great. I put this here so I dont forget about doing it in the future.
