### ISSUE TITLE
(WEB REPORT BY: redun REMOTE: 198.245.63.50:7777) Borers a shit.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3895]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Popped out of a person without clicking to do so.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible
Possibly because I clicked more then once with the previous host? I don't know sorry.

**Comment by ComicIronic** [comment]
This is possible with sugar, isn't it?
Are we sure this wasn't done using sugar?

**Comment by Kurfursten** [comment]
@clusterfack Not relevant anymore with the significant changes to borer by @N3X15 

That being said, it was probably WAD in the first place
