### ISSUE TITLE
(WEB REPORT BY: tersr REMOTE: 198.245.63.50:7777) Recorder bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3896]
>Revision (Should be above if you're viewing this from ingame!)
2f600cb374d7764a86aa1c20d83b02ab8f9cb915

>General description of the issue
When deaf, can still here playback on a recorder

>What you expected to happen
To not hear shit

>What actually happened
Heard a recorders playback.

>Steps to reproduce if possible
Become Deaf, hit record, hit playback, here what you missed.

**Comment by ComicIronic** [comment]
SANITY!
