### ISSUE TITLE
Plasmamen Take Toxin Damage From Plasma in Their Clothes

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3897]
This is according to an anecdote from another player. I'd test it myself on the test serb, but when I was on there yesterday it was painfully laggy.

Anyway, the guy made a plasma-filled room so he could take his suit off without bursting into flames, and apparently he started gaining a ton of toxin damage from the plasma soaking into his clothes. This doesn't make sense for plasmamen, because they BREATHE plasma. Why would plasma soaked into their clothes hurt them?

**Comment by Exxion** [comment]
Also, why can plasma contaminate clothes through space suits? Aren't space suits supposed to be airtight?

**Comment by Probe1** [comment]
[plasmaguard] tag is notoriously dodgy.  lots of suits *should* prevent plasma contamination but do not.

**Comment by ComicIronic** [comment]
The issue with plasmaguard is that nobody can break it consistently. The common response to "test it" is that it never happens twice.
