### ISSUE TITLE
(WEB REPORT BY: morriak REMOTE: 198.245.63.50:7777) Mech Bay Recharge Station parts vanished upon disassembly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3898]
>Revision (Should be above if you're viewing this from ingame!)
2f600cb374d7765a86aa1c20d83b02ab8f9cb915 

>General description of the issue
All the parts and circuit board disappeared a tenth of a second after prying the board out

>What you expected to happen
I would be able to check what board it used and upgrade parts

>What actually happened
Everything Vanished except the frame

>Steps to reproduce if possible
Disassemble a Mech recharge station

**Comment by dylanstrategie** [comment]
Odd. It could have been caused by an incorrect use of machinery component code. Someone will need to check more in-depth

Would help to know if it's a starting recharger or if it was built from scratch

**Comment by Morriak** [comment]
It was the top starting recharger pad on box. I didn't think to try a built one.

**Comment by ComicIronic** [comment]
It is possible the lack of a newlist for component_parts means that some machines, if spawned directly, don't start off with the right parts.

**Comment by Morriak** [comment]
Well like I said, the parts did appear for about a tenth of a second before vanishing. It was very peculiar.
