### ISSUE TITLE
(WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Antibodies not working correctly/Wonky viruses

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3900]
>Revision (Should be above if you're viewing this from ingame!)
17ad09b11b949d9234b8d4c41b567dd86484a43d 

>General description of the issue
Antibodies not stopping virus

>What you expected to happen
Stopping the virus stops it form developing further symptoms

>What actually happened
It doesnt

>Steps to reproduce if possible
Got a virus with waiting, wheezing, horse throat, fagile bones, got antibodies before any symptoms manifested, still got a horse mask that came back after removing it for the first time

**Comment by Kurfursten** [comment]
@clusterfack As there has been no elaboration on this, and it can't be reproduced, I'd say close
