### ISSUE TITLE
/obj/item (Maybe?)

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#3902]
![2015-04-13_23-24-02](https://cloud.githubusercontent.com/assets/9827785/7132213/346d1062-e255-11e4-90b1-e9e9e1ff9930.png)
![2015-04-13_23-24-12](https://cloud.githubusercontent.com/assets/9827785/7132214/36cff19e-e255-11e4-9d67-ee9ea8104f86.png)
This is a mess.

Just found it on the main server in a pile of trash on top of a disposal chute. No idea how it got there. It had no sprite or characteristics of any kind.

**Comment by CptWad** [comment]
might be the missing floortile
Also the Bar's Bar disposals lead there for whatever fucking reason
Only fun part about it is saying you will meet sec at recycling and end up in dorms so you just count to five then return to the bar while anyone hunting you goes to cargo

**Comment by clusterfack** [comment]
Not much we can do about this explicitly, please try to bwoink admins to view the variables of objects that have broken sprites or weird names like this. They can at the very least tell us the typepath of the object and possibly find out more about where it came from.
