### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Derelic MoMMI can leave derelic Z-level

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3903]
>Revision (Should be above if you're viewing this from ingame!)
17ad09b11b949d9234b8d4c41b567dd86484a43d

>General description of the issue
Went to space with a station MoMMI in a locker and got to the roid Z-level

>What you expected to happen
Get stuck at Z-level edge

>What actually happened
Changed Z-level

>Steps to reproduce if possible
Build a locker get in mass drive yourself and change Z-level.

**Comment by CptWad** [comment]
Nuke disk checks are great examples 4 fix

**Comment by PJB3005** [comment]
This was fixed.
