### ISSUE TITLE
Window smashing people is way too hardcore

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3904]
You can grab people to the neck then smash them into windows
Before It took a bunch, maybe seven or more to deal internal or lots of damage
Now in one windowsmash you can FUCK someone. Bleeding plus victims tend to loose a shitload of blood magically causing more than one or two hits to knock someone the fuck out
It is terrifying

**Comment by dylanstrategie** [comment]
If someone grabbed you by the neck (which basically means they are about to throw your entire body, head first) and sent you straight into a window, it would be pretty nasty. Plus, balance-wise, a neck grab is at LEAST 3 whole grabs, so if you are ever put into that state, you're in a bad situation

**Comment by CptWad** [comment]
I got bleeding + internalbleeding from one windowsmash
Maybe even a broken bone
That is way too robust
You can spam grab someone and windowsmash them even if they get out of range if you are fast enough
That is some shit
