### ISSUE TITLE
You can disarm Bombermen to acquire their BBDs

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#3909]
Robust at SS13 but not Bomberman? Worry not! You can just push your enemy down and steal *their* life!

**Comment by d3athrow** [comment]
Should be a UI element like spells.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/3884#issuecomment-92141499

**Comment by DeityLink** [comment]
close this
