### ISSUE TITLE
Security cameras are stupid

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#3914]
I mean the way they're coded. I'm... pretty sure the way they work with the AI is logical and makes use of all their variables and stuff, but the way they work with camera monitors/computers/viewers/etc. is not. They just move the viewer's eye to the location of the camera. This means that the camera's view_range variable is totally ignored (probably along with others) and that any vision flags the user has are preserved when viewing the camera (probably; I haven't tested this, but I have tested the view_range part and I have looked at the code).
Since cameras almost always have view_range equal to the player, this is generally irrelevant, but I need it to be fixed for a feature I want to add

**Comment by dylanstrategie** [comment]
We're fully aware of cameras basically just moving the mob's view, which creates other problems like cameras being unusable by buckled mobs

I don't know if it's an even reasonably easy fix

**Comment by Exxion** [comment]
All of this that was not also part of #3492 was fixed
