### ISSUE TITLE
(WEB REPORT BY: sikras REMOTE: 198.245.63.50:7777) Cyborg Modules Sticking

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3915]
>Revision 9c2b08c24e792e1708e5bc6148e409e823737283

>General description of the issue
Upon using up all of the metal and glass I had synthesized by placing it into the Roboticist's Exosuit Fabricator, I became unable to remove the metal and glass selections from my three available modules, limiting me to one open module and two useless ones.

>What you expected to happen
The metal and glass to be put back into my module selection board.

>What actually happened
Got the message "Can't store something you're not holding!", couldn't remove it from my module list. A cyborg reset fixed it, but I figured I'd bug report it anyway.

>Steps to reproduce if possible
As an engineering cyborg, synthesize some metal or glass and then put it all into the robotics Exosuit Fabricator. Then try to store the metal or glass from your module selection. Additionally, I've noticed that medical cyborgs are having the same difficulty when they use their beaker module in a chem dispenser.

**Comment by clusterfack** [comment]
Almost certain this has been fixed in various ways in the long period since then
