### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Wizard Hat Icon Doesn't Show Up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3917]
>Revision (Should be above if you're viewing this from ingame!)

560353ed37d3505bd2c0ef3bf9363380cd075465

>General description of the issue

Wizard Hat Icon doesn't show up on player

**Comment by ComicIronic** [comment]
NIGGLYYYYYYYYYYYYYYY
