### ISSUE TITLE
(WEB REPORT BY: amidaychi REMOTE: 198.245.63.50:7777) 2 nuke disk related issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3918]
>Revision d2b95c949a53c4194728882075579ce1d2984f39 

>General description of the issue
1. Nuke disks can go in garbage bags if the nuke disk is on the same tile as something valid you pick up. 
2. combining mass driver with nuke disk z-level prevention causes player to get stuck at very edge of level.

>What you expected to happen
Garbage bag not to pick up disk, and to get bounced back in the direction of the station on zlevel attempted transition.

>What actually happened
Janitorborg picks up nuke disk in garbage bag during nuke ops round, stores garbage, bag, shoots self out of mass driver and is unreachable due to space buffer.

>Steps to reproduce if possible
Use garbage bag on valid baggable object on same tile as nuke disk to pick both up.

Shoot self out of mass driver afterwards, hug the blank nothingness till crew attritions the nuke ops away.

**Comment by clusterfack** [comment]
Whoever coded things hitting the end of a zlevel and stopping gets two thumbs :-1: down from me, it should just have the same zlevel transition but without an actual change in z.

**Comment by Midaychi** [comment]
Well normally you get pushed in the opposite direction but if you shoot out the massdriver, the massdriver push out-pushes the zlevel pushes.
