### ISSUE TITLE
(WEB REPORT BY: sarahjohnson REMOTE: 198.245.63.50:7777) Xenos Helmet isn't displaying.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3920]
>Revision d2b95c949a53c4194728882075579ce1d2984f39 

Equipped the xenos costume to have a giggle as a maint monster but the helmet wouldn't display. HideMask, HidesHair works but the helmet doesn't show.

>What you expected to happen
Xenos helmet on head

>What actually happened
Just hid mask and hair showing a bald face

>Steps to reproduce if possible
Go to autodrobe, vend xenos suit and xenos helmet then put them on

Doesn't appear to be from changing the icon/iconstate in https://github.com/d3athrow/vgstation13/blame/Bleeding-Edge/code/modules/clothing/head/misc.dm
So it's probably in head.dmi

**Comment by ComicIronic** [comment]
NIGGLYYYYYYYYY
