### ISSUE TITLE
(WEB REPORT BY: amidaychi REMOTE: 198.245.63.50:7777) Another nuke disk related bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3921]
>Revision d2b95c949a53c4194728882075579ce1d2984f39 

>General description of the issue
Nuke disk can be taken across zlevels if carrier is inside of a closet.

>What you expected to happen
Same as trying to cross without a closet.

>What actually happened
Was janiborg, picked disk up in garbage bag, got someone to close a closet on me while standing on the mass driver, pushed button, flew to mining zlevel in closet.

>Steps to reproduce if possible
1. be in locker
2. have nuke disk
3. whee.

**Comment by Midaychi** [comment]
Actually nevermind. Looks like the disk deletes itself if it finds itself in a container on another zlevel.

**Comment by clusterfack** [comment]
^see
