### ISSUE TITLE
You can almost hear (yourself) talking.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3925]
While in unconscious, people's messages and emotes are replaced by "You can almost hear someone talking..."
The issue is that most of the time you're unconscious you also involuntarily make a lot of emotes yourself, which results in a constant "You can almost hear someone talking" from your own emotes, even when you are the only person in the room or the only person alive in the universe.

**Comment by dylanstrategie** [comment]
Emotes shouldn't trigger this message. Don't know how hard that would be to implement

Right now, every time you go crit it sounds like there's a constant mass panic, but it's just you gasping. That sucks

**Comment by clusterfack** [comment]
Hilarious
