### ISSUE TITLE
Polyacid damage inconsistency: deadly as smoke, very tame as reagent

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3928]
Dump 200 units of polyacid on someone's unprotected face, they get less than 10 brute damage.
Feed them 20u of polyacid in a pill, they will veeeery slowly take 50 toxin damage. Even welder fluid is deadlier.
But put that polyacid in a spray bottle and puff 5 units onto the same person, they get whooping 30 brute and serious bleeding.
And jesus christ, polyacid smoke grenades near damn instantly fucking kill you if you stand anywhere near them.

**Comment by Iamgoofball** [comment]
This is because smoke literally applies the reagent on touch effects /50 times a second/

**Comment by 9600bauds** [comment]
fucking magical

**Comment by dylanstrategie** [comment]
Reagents are magic, also yeah, smoke literally multiplies all reagents effect by 50

This is why a polyacid smoke leaves nothing, absolutely NOTHING

**Comment by 9600bauds** [comment]
Does the spraybottle also multiply the reagent's effects?
