### ISSUE TITLE
Electrified Grilles are a joke, and it would only require removing four lines of code to fix

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#3939]
Electrified grilles being cut up by grilles. Yes, we've been through this already, which is why I opened an issue ticket instead of directly changing it again

The problem ? This is snowflake coding, and the bad kind of snowflake coding too. There's no reason for glass shards, literally the first item you obtain when breaking through electrified grilles (since they almost always translate into electrified windows) to protect you from the grille shocking you. And I'm not even talking from a realism perspective (for some reason no-one has ever thought that siemens coefficients could be anything but 0 or 1)

>But glass shards are fucking insulated

No they aren't, read the code. If you can't read the code, log into the game, break a window, pick up a shard, find some exposed wiring and start cutting away at it with the glass shard. Case in point

The problem is that this allows any unprepared smuck, even prisoners, which says a lot, to break through electrified grilles. Electrified grilles are supposed to have "Stay the fuck out" written all over them, and only someone with yellow gloves or some craftmanship should be able to punch through

>But then how the hell will I break into that place

- Insulated Gloves. They aren't rare. Cargo, that Cyborg Charging Station in Maintenance, etc
- Throwing shit at the grille. It works, it really does, it just takes a lot of time. Throwing people at the grille works much faster and allows you to deal with another problem
- Shoot at it. Guns aren't that common, but it works mang
- Blow it up. IEDs anyone ?
- Hoping that the voltage is low enough to not turn you into roast, packing medicine and hitting it, over and over again, preferably with the biggest and meanest tool you have at your disposal
- Going around it. No insulated gloves but a welder and eye protection ? Burn through the wall. Time to spare ? Rwall. Know door wires ? Just break through the door

**Comment by Midaychi** [comment]
Not as gamebreaking a change as it sounds. You can still break out of prison with glass shards even if you change this; you just have to use throwing instead of hitting.

**Comment by 9600bauds** [comment]
I don't really care so much about breaking out of perma, what's really baffling is broken glass shards being the only item in the universe that won't shock you when hitting an electrified grille. Yep, that fireaxe with a wooden handle will shock you, so will that energy sword, no you can't even use non-broken glass.
Not even insulated gloves protect you, which is awful.

**Comment by dylanstrategie** [comment]
Hold on a second, insulated gloves don't protect you from electrified grilles ?

**Comment by ComicIronic** [comment]
>No they aren't, read the code

This is an oversight in the code, it's not proof that glass shards aren't meant to conduct. The behaviour of glass against grilles is deliberate.

**Comment by dylanstrategie** [comment]
Well, if it is an oversight, it's a HUGE oversight, because using glass shards against literally anything else that happens to be electrified will make you more fried than Pomf

**Comment by 9600bauds** [comment]
My bad, insulated gloves do protect you.

**Comment by 9600bauds** [comment]
You can't damage grilles by throwing shit at them you nerds
