### ISSUE TITLE
Todo: Modify Ventcrawl do_afters

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#3943]
Do_after has a fourth argument that allows a user to modify things in their active hand without breaking the do_after check. 
(It checks periodically that you are holding the same active hand object or not in the standard form)

More things need to use that argument when the object inhand isn't actually required to do the action, such as ventcrawling and many other actions that honestly I haven't even thought of until now. I'll probably get to this eventually unless someone else takes it up first.

**Comment by ComicIronic** [comment]
This got done, right?
