### ISSUE TITLE
Observing at any time makes you bald

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#3948]
What's the point of being spoopy if you can't look good while at it ?

Find whatever makes people ditch their facial hair setups and plsfix

**Comment by 9600bauds** [comment]
this is part of nexis' in memoriam

**Comment by PJB3005** [comment]
I'm unable to reproduce this locally

**Comment by clusterfack** [comment]
I dont see it on the live server either (at the moment)
