### ISSUE TITLE
[Bug] MoMMIs can eat pills and drink drinks

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3950]
panic

**Comment by ComicIronic** [comment]
Wontfix.

**Comment by AutismSpider** [comment]
chems do nothing to mommis/cyborgs so they can eat and drink any thing but acid that burns them same for cyborgs.

a mommi can eat 50 units plasma pill and nothing happens.

**Comment by clusterfack** [comment]
Haven't they been this way forever?

**Comment by PJB3005** [comment]
IT'S A FEEEATUUURE

Drinking welding fuel is the shit

**Comment by AutismSpider** [comment]
Yes it has clusterfack.
