### ISSUE TITLE
(WEB REPORT BY: theophrastus REMOTE: 198.245.63.50:7777) wielding fireaxe with one arm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3951]
> Revision 4ac9846a9f9e017442accfa2dfebb72c277edd09 
> 
> General description of the issue
> Blew my robotic limb off with an emp grenade, was still able to wield fireaxe as if i still had two arms.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by clusterfack** [comment]
Mommis could wield the fireaxe with only one hand as well, make sure to modify pomfs modification to them wielding it when this gets fixed

**Comment by ComicIronic** [comment]
That shouldn't be possible.
Wielding has a check for the user being human.

**Comment by CptWad** [comment]
![one hand](https://cloud.githubusercontent.com/assets/3959840/13660575/2df17bc0-e640-11e5-9439-f594bcd93562.png)
Heres me and my left hand dual weilding this axe here
methinks the needs more testing is for something not related to this issue specifically but to mommis

**Comment by 9600bauds** [comment]
![dreamseeker_2016-12-14_12-36-39](https://cloud.githubusercontent.com/assets/6526157/21188389/06b06db4-c1fa-11e6-9bfb-66bb0a75c708.png)
fixed at some point
