### ISSUE TITLE
(WEB REPORT BY: fozzington REMOTE: 198.245.63.50:7777) Twitch/Tourette's gene disabling mobility/actions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3954]
>Revision (Should be above if you're viewing this from ingame!)

Application of the Tourette's/Twitch disability occasionally (unsure if frequently) causing an inability to move or access any functions for a particularily long period of time, presumably unexpected (this has occurred before, although it was harder to track)

>Expected

Regular disability symptoms

>What actually happened
Crippling inability to move/perform vital activities such as pick up items/access consoles

>Steps to reproduce if possible

Activate the Tourette's/Twitch disability
Continue going about activities until you are unable to perform said activities (not really sure on activators other than that)

**Comment by BestName** [comment]
It's the twitching. Every time you twitch due to tourettes you get stunned for a while.

**Comment by BestName** [comment]
if (disabilities & TOURETTES)
		if ((prob(10) && paralysis <= 1))
			Stun(10)
			switch(rand(1, 3))
				if(1)
					emote("twitch")
				if(2 to 3)
					say("[prob(50) ? ";" : ""][pick("SHIT", "PISS", "FUCK", "CUNT", "COCKSUCKER", "MOTHERFUCKER", "TITS")]")
			var/x_offset = pixel_x + rand(-2,2)
			var/y_offset = pixel_y + rand(-1,1)
			animate(src, pixel_x = x_offset, pixel_y = y_offset, time = 1)
			animate(pixel_x = pixel_x, pixel_y = pixel_y, time = 1)
I can't claim to understand code but this doesn't seem like a bug to me

**Comment by clusterfack** [comment]
That is a pretty long stun though, isn't it? About every ~10 ticks you get stunned for 10 ticks?

You'll spend 50% of your time stunned

**Comment by clusterfack** [comment]
This is really a balance concern about how often you are stunned by these afflictions, this really hasn't been changed at all to my knowledge
