### ISSUE TITLE
[Bug] Rapid machinery component exchanger issue

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3955]
Filling up parts to the RMCE with a gadget bag doesn't remove the parts from the gadget bag so you get two copies of each part, one in the RMCE and one in the bag.

The delays for the RMCE working need to be shortened if possible.

**Comment by Probe1** [comment]
The RMCE doesn't work with the DNA modifier

![ss 2015-04-16 at 11 44 59](https://cloud.githubusercontent.com/assets/8550416/7196143/70435abe-e49a-11e4-928f-0ce91cbb61e8.png)

**Comment by dylanstrategie** [comment]
The first bug seems rather obvious, i'll look into it asap. Bit busy at the moment, but I'll try to be fast

As for the second, are you sure you opened the hatch ?

**Comment by 9600bauds** [comment]
I'd look into making the RMCE a container like a gadget bag, so you can quickly remove individual parts from it. Getting rid of the 5 tier 1 parts after you upgrade something by having to use a menu for each individual part is mortally tedious.

**Comment by Probe1** [comment]
please fucking do.  @dylanstrategie I love you for doing this but this is so unnecessarily clunky.
