### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Lockboxes Security

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3957]
So i don't know who can open those on Science (probably RD i think) but any lockboxes can be just opened with a floral somatoray or any laser gun even toy,i don't think changing the access change the fact that anyone can open it,still can be abused by powergaming.

**Comment by ComicIronic** [comment]
Honk.

**Comment by Manaony** [comment]
You can also shoot them with a laser and drill them with a ripley to open them, infinite possibility.

**Comment by Exxion** [comment]
OK, they should probably be possible to break into with lasers, but not the somatoray or laser tag guns. Those are a bit *too* easy to get.

**Comment by Starnightx** [comment]
Yeah i think only lethal lasers are enough,since it can break lockers and shit.

**Comment by 9600bauds** [comment]
So that's why there were two somatorays lying around in R&D last shift.

**Comment by Kurfursten** [comment]
@clusterfack Not relevant anymore, close it
