### ISSUE TITLE
Custom Job Title in ID Computer No Longer Works

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3958]
When I click it, the window to enter the title never pops up, it just closes the job selection menu.

**Comment by clusterfack** [comment]
I can't reproduce this on the test server

**Comment by clusterfack** [comment]
This is on the live server, but not test/local servers

**Comment by Kurfursten** [comment]
Also unable to reproduce, will try to get some testing done on live

**Comment by d3athrow** [comment]
Can't reproduce.

**Comment by clusterfack** [comment]
Try it on the live server and not local and see what happens

**Comment by d3athrow** [comment]
well then i guess live server doesn't like nested inputs anymore.
