### ISSUE TITLE
[Feauture request] Smelting ores with high temperature

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#3962]
Ores left in a high temperature atmos would turn in to smelted bars. Yes even plasma. It's science!

**Comment by clusterfack** [comment]
We'll probably have to uncomment fire act to do so

**Comment by ComicIronic** [comment]
That's not how smelting WORKS

**Comment by clusterfack** [comment]
Shhh our ore redemption machines just magically turn ores into sheet without even needing fire

**Comment by ComicIronic** [comment]
There is clearly a fire inside the machine.

Though that makes me wonder if you could smelt ores using only electrolytes.
