### ISSUE TITLE
(WEB REPORT BY: sherrax REMOTE: 198.245.63.50:7777) Vampire Plasmamen can't suck blood through helmets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3965]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
If you're rolled a vampire while playing plasmaman, you cannot suck blood through your helmet and mask.

>What you expected to happen
Biting people's neck, sucking their blood, getting mad powers.

>What actually happened
'Remove your mask!'

>Steps to reproduce if possible
1. Be plasma and vampire
2. Try to suck blood

**Comment by Arthurdentist** [comment]
This isn't the only antag type plasmamen have issues with. The other notable case is Wizard where a plasmaman will immediately burst into flames at round start. Currently the only work arounds for both of these issues are admin intervention. One day we will get a round without admins and full of plasmamen vampires, and it will be awful.

**Comment by ComicIronic** [comment]
There needs to be species-blacklisting/whitelisting for certain antags.
Though I'm not so sure about how to handle the whole plasmen wizard scenario, especially since a spacesuit is meant to be a bought item.

**Comment by PJB3005** [comment]
Vox have this issue too, though atleast for vox it's not the worst

**Comment by Intigracy** [comment]
Partly fixed in the wizard case because wizards are human only now, but the vampire one is still an issue afaik.

**Comment by CptWad** [comment]
Wasn't this fixed? I see plasmen suckin blood

**Comment by Intigracy** [comment]
maybe idk
