### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) R-wall sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3967]
>Revision (Should be above if you're viewing this from ingame!)
gingersockman

>General description of the issue
Unfinished R-wall sprite update when building a R-wall next to it even though it's unfinished

>What you expected to happen
Unfinished R-wall sprite to to stay

>What actually happened
R-Wall sprite status update even if it's missing a plasteel sheet

>Steps to reproduce if possible
Build R-wall one next to another
Thank you Dylan

**Comment by ComicIronic** [comment]
So the rwall smooths even if it's been deconstructed?

**Comment by PJB3005** [comment]
Think so, comic, an uncompleted Rwall will look completed if it connects with others

**Comment by dylanstrategie** [comment]
When finishing a rwall, it calls relativewall_neighbours() on its neighbours

I'll try to see if I can address this quickly
