### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Warn command issues no query as to why the person's being warned, nothing shows up in a players notes when they're warned either

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3970]
>Revision (Should be above if you're viewing this from ingame!)

be9c4429354e7ecb214dbde929dc7a2ae0e56534 
>General description of the issue

IM high as fuck and mostly just wanted to go to Ririchiyo about this issue but I cant find him so whatever.

Basically how we have the warning system on the server works is, I can give some clown a warning, then they have two warnings left until a 90 minute ban or some shit. However, these warnings don't even give you a pop-up or anything for you to explain why they're getting a warning. There's no proper documentation. You literally have to go into the person's notes and make up a new note that basically just says WARNING 1 - Warned for (blahblahblah).

The way warnings are handled by admins needs to better tool-wise. When hitting the warn button it shouldn't just auto-give them a warning, should work a bit like a ban in that it asks you for a reason, you put down the reason, then the person's warned, and Adminbot automatically puts the warning in the player's notes.

This makes it easier to track warnings across accounts and makes more admins inclined to use them and go a bit less harsh on people rather then jumpin all the way to that ban lane.

**Comment by d3athrow** [comment]
when i got to them warnings didnt even work properly.

**Comment by Imagebard** [comment]
Did you know you can ban Pomf123( That's you, @d3athrow ) with so much as simple access to the warn system?
Just give them 3 warnings and he will be warn-banned.

**Comment by gbasood** [comment]
chickenban

**Comment by ghost** [comment]
This is fixed as far as I'm aware

**Comment by gbasood** [comment]
Wait nevermind
Why the fuck are bugs or things that need fixing feature requests thanks comic
