### ISSUE TITLE
How 2 machine stack

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3979]
So you want to stack some machines on the same tile but you dont know how? Easy fix!
Build a table a tile below where you want the many machines
Build disposal junction and outlet FACING the table. 
Build disposal junction and inlet next to your contsruction, place window between the two disposal junctions
Push machinery into disposal inlet
Wrench machinery down
Viola! stack anything onto one tile! Works with collectors, computers and anything else you can think of!

How 2 fix: Make a check If a same type machine is already present on the tile so you cannot wrench another machine down. :information_desk_person:

**Comment by CptWad** [comment]
Oh man you can also do emitters. Wonder what happens when more than one emitter beam is on the same tile? Would some ten make a instant death ray?

**Comment by dylanstrategie** [comment]
The fix you suggest would have no serious effect. If there's already two machines on the same tile, it's one machine too much

The main problem with this is that we're talking about disposal machinery. Does anyone even know how those work anymore ?

**Comment by CptWad** [comment]
Code wise or game wise?
I mean the same machine, so if you try to wrench a collector on the same tile as another collector it wont let you.

**Comment by clusterfack** [comment]
Lots of machines must be anchored before working, those are primarily the machines you dont want to be stacked on one tile anyway.
