### ISSUE TITLE
Some airlocks are !!!REALLY LOUD!!!

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#3982]
There's a very obvious volume difference between some types of airlocks, particularly hallway clear/white airlocks. They're obnoxiously loud, while department-specific airlocks are a lot more toned down.

**Comment by Exxion** [comment]
This isn't even some bizarre quirk
For some reason, specifically departmentless glass airlocks are set to be louder than the others
Other than the basic airlock object all others inherit their variables from, the glass airlock is the only one that even has pitch specifically defined. The rest all inherit pitch=30 from the base airlock.
Glass airlocks have pitch=100 for some reason.
One of the easiest fixes I have ever seen, but why is it set that way? Maybe there's a reason.
