### ISSUE TITLE
Smooth Pulling doesn't work for some items

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3983]
You know, that smooth movement between tiles for mobs, items, and such. Pulling certain items will not trigger a smooth transition, Metal Stacks, Reinforced Glass Stacks, and Metal rods when pulled will snap to the tile it's moving into instead of smoothly dragging along.

**Comment by PJB3005** [comment]
Pipes too

**Comment by ComicIronic** [comment]
Chances are more than anything that this is a Byond issue.

**Comment by clusterfack** [comment]
We fixed this, it was a problem with animate_movement. As it turns out the initial value for animate movement comes up as 0 for SOME REASON. 

It has since been added to the global exclusion list, thank you and have a good night.
