### ISSUE TITLE
Can't Print Isolation Centrifuge Board

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#3987]
The board listed as "isolation centrifuge" comes out as a "disease splicer" board, and it won't even go in a machine frame. The board listed as "lysis-isolation centrifuge" does come out as that, but when I build the machine, It's got some strange GUI that isn't on the regular isolation centrifuge, and I couldn't even get it to take a vial of blood.

**Comment by ComicIronic** [comment]
That's because the lysis centrifuge is used in botany.

**Comment by PJB3005** [comment]
The disease splicer is a computer, IIRC, the fact that it shows up as a centrifuge is indeed a bug

**Comment by clusterfack** [comment]
This if fixed, making a PR soon
