### ISSUE TITLE
Genetic powers stay with player even after curing or rye usage. Works with defects AND power.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#3988]
Also genetics seems fucked beyond that but I cant pin it on much else but the title.
Oh and spell powers (like hulk) get removed but the ones that stay (like small stature) are there even if clean SE

**Comment by PJB3005** [comment]
yeah, can confirm that the effects of small size stays even after getting rid of the actual mutation

**Comment by clusterfack** [comment]
>putting oh god its loose in your title

Now it wouldn't be any fun to add that as a tag

**Comment by ComicIronic** [comment]
Stop title-tagging things, guys. That's what actual tags are for.

**Comment by ComicIronic** [comment]
Small stature is actually an issue unrelated to ryetalin deactivation, because the tablepass flag is never removed.

**Comment by ComicIronic** [comment]
So as it turns out, this wasn't a rye issue at all, because rye works fine on every power.
It was just an issue with the short gene, which wasn't deactivating properly.

Why did you think rye was broken?

**Comment by CptWad** [comment]
For a while defects were not deactivating however I think the issue has been fixed or it was a small time thing. 
Reopen if it returns from the grave
