### ISSUE TITLE
Crew Monitor doesn't track the Asteroid

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#3997]
Apparently the crew monitor is also supposed to extend its range to the mining asteroid as well, at least, that's what pomf said.

**Comment by ComicIronic** [comment]
I don't think it is.
That's why GPS for miners exist.

**Comment by Probe1** [comment]
pretty sure @d3athrow fixed it himself so it did a month or two back after hearing it didn't track people on the roid.  up until now it has.

**Comment by d3athrow** [comment]
Code looks sound, unsure whats up
