### ISSUE TITLE
(WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Metaclub Access Buttons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#3998]
>Revision (Should be above if you're viewing this from ingame!)
36d41067a9269a882cc2805fe1b0434bb0ad7258

>General description of the issue
They dont work.

>What you expected to happen
Viro doors would open

>What actually happened
They didnt. Acceess button blinked but doors sayed closed

>Steps to reproduce if possible

**Comment by PJB3005** [comment]
IIRC, there's not even an airlock controller
