### ISSUE TITLE
[Feature Request] Sorting for the protolathe

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#3999]
I've had this idea in the back of my head for the last month.  The protolathe menu has so many items and it's so unwieldy.  It's a game of memorizing key words so you can ctrl-f faster, like knowing that management only comes up once so you can quickly jump to incision management devices or precision for high-precision scalpels (and just why the hell do we need 3 super scalpels to begin with)

What would really be beneficial is to have a sorting button that hides the things you're not looking for.  Something like this image attached at the end.  That way if you just want tier 2 parts you don't have to tab past advanced mass spectrometers and three other things to get to advanced matter bins.  And so on.  Having some sorting options would be the bees fucking knees.

 
![ss 2015-04-19 at 02 36 12](https://cloud.githubusercontent.com/assets/8550416/7220789/5d41f916-e6a2-11e4-9d1e-2f9b325aebaa.png)

I considered the autolathe as well but since its a much shorter list its not as big of a problem.

**Comment by 9600bauds** [comment]
Ideally it would use NanoUI, but I ain't touching that

**Comment by clusterfack** [comment]
Might help with some latency issues
