### ISSUE TITLE
Mining hidden complexes suck

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4001]
Most of the time, they have mid-tier R&D items. Like scanning modules and advanced mass-spectrometers. Not only you have no use for it, and noone has any use for it, but if you really wanted them, Science can make them 5 minutes into the shift!
There are some half-decent rewards, like the mysterious medbot and the legendary Firebird that is almost never there. But for the most part they are really underwhelming.

Ideally they should have exclusive stuff, not overly good, but not easily obtained elsewhere. For example, we have a Swiss Army Knife in the code currently unused.

**Comment by Arthurdentist** [comment]
I've long since wanted to add more unique artifacts and other such things to find. I agree, there should be more unique things to find out there.

**Comment by Probe1** [comment]
agreed, the majority of the items are terrible.  wow, some hydroponic trays.  I feel truly blessed to have found this bounty of machines that would take 20 minutes to drag to hydro from the roid and be ignored by a botanist who doesn't need them.  

I'd say at LEAST 50% of the stuff needs taken right out and replaced with items of real value.

**Comment by CptWad** [comment]
Some are fine. The cult rooms are good because theres a risk reward of creatures and soul stones which are real cool

**Comment by NigglyWiggly** [comment]
What if you could find some more wizard items in the wizard ruins?
Maybe a Mental Focus or wizard hardsuit. The firebird is kind of pointless for miners now as it's basically just a jetpack that doesn't run out since it lost its ability to go through walls. So I'd say either replace it or make it its own thing with the ability to go through walls, maybe with a new sprite and name so we could pass it off as a different version of the wizard car.

**Comment by Probe1** [comment]
the firebird is a glamor item, for the same reason you catch pokemon or go hunting for hidden rooms to begin with.  you look ballin af riding it.

**Comment by 9600bauds** [comment]
Maybe if you want to keep the "co-op with Science" aspect the research stock parts tried, we could have design disks loaded with exclusive designs not obtainable through regular research?

**Comment by ComicIronic** [comment]
That's certainly a good idea.

**Comment by Probe1** [comment]
yeah having unique protolathe items would be excellent and a great mid-late game thing for miners to realistically bring.

**Comment by CptWad** [comment]
>design disks loaded with exclusive designs not obtainable through regular research?

Oh man we could have that rapid part exchanger thing as one
We could also have other fun things like unique items IE dual airtanks, galoshes, Janicarts, clown carts...
Oh god that is best idea props to @9600bauds

**Comment by Probe1** [comment]
nah think rarer.  like the list of unique items.  blueprints for the general fab too!

**Comment by MercuryDoll** [comment]
We could add Bomberman stuff to it, like a Bomb Dispenser that works on the roid rocks. Perhaps a chance to spawn a large artifact?

**Comment by Probe1** [comment]
dunno, bombermans a little too 'adminbus' ish.  keep it in lore, even if our lore is haphazard.

**Comment by NigglyWiggly** [comment]
If we really wanted to incorporate the bomberman stuff, we could probably try to work it in, like the Lazarus capsules which totally aren't pokeballs

**Comment by SECBATON-GRIFFON** [comment]
aparently space hobos really like those hydroponic trays
