### ISSUE TITLE
-1 kPa

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4003]
Someone dragged an air canister into an area low on air and opened it on full blast. It filled up the area as expected. However, when I went to shut off the valve, the pressure reading was -1 kPa.
Not really a big deal, but odd, especially considering it's usually hard to even get it all the way to 0 kPa.

**Comment by CptWad** [comment]
I like -1kpa. It tells me when there is absolutely no air inside a tank. Usually theres some 0.00something pressure left in something if you drain it and theres only a few ways to empty tanks totally.

**Comment by Exxion** [comment]
You could just have it display 0.00 if there's something in it but too little to display and 0 if it's totally empty

**Comment by CptWad** [comment]
Or better yet "None"

**Comment by Exxion** [comment]
Fixing it to just say "none" should be very easy. I can go do that later. It would be nice to know (and maybe fix) the root cause, though.
It's probably some obscure quirk of whatever function is used to display the pressure.

**Comment by clusterfack** [comment]
It could be technically 'solved' simply by adding sanity to make it set the contents to 0 if they go below, but the real question is how badly are canisters coded that they can even GO BELOW 0KPA in the first place.
