### ISSUE TITLE
Can't Make Virus Food

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4005]
The commonly-though recipe for virus food, water and milk, doesn't work. And it's not possible to build a virus food dispenser like can be found in Virology.
This means it's not possible to build Virology from scratch/completely fix it if it gets damaged and the virus food dispenser is destroyed.

Either add a recipe for making virus food, or add a board for building a virus food dispenser.

**Comment by Exxion** [comment]
The recipe is definitely present in the code and it definitely is 1 water plus 1 milk for 5 virus food (for some reason). I just looked. Feature request doesn't seem like the best label.
As for why it isn't working, I don't know. I can't see anything wrong in the code from a quick glance, at least.

**Comment by ComicIronic** [comment]
It's double-defined, one recipe is 1 water 1 milk for 5 virusfood, the other is 5 water 5 milk 5 oxy for 15 virusfood.

**Comment by Exxion** [comment]
So I guess all that really needs to be done is to decide on which recipe to keep and delete the other, then.

**Comment by MercuryDoll** [comment]
Guide to Chemistry's recipe lists 1 Milk + 1 Water = 5 Diluted Milk/Virus Food, but honestly the 5+5=15 would make more sense.
