### ISSUE TITLE
Airlock controller buttons suck sometimes

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4007]
Sometimes, airlocks get really weird. Vents always appear to be draining air when they should be, but it seems that sometimes, they are actually pumping air both in and out. I don't know why this happens. It happens seemingly randomly, but it's not that uncommon. When it happens, the air pressure in the room fluctuates a bit, but doesn't significantly drop. Pressing the button a couple more times sometimes fixes it.
The actual airlock controller generally seems to work, just not the buttons linked to it.
It's most easily observable in the pod bay due to the pressure monitor on the wall and the two big vents. It usually drains very quickly for such a big room, so you know something's up when the pressure is almost normal after several seconds.

**Comment by PJB3005** [comment]
The buttons not working flat out is a mapping issue

The vents' icon states being weird is strange considering airlock controllers just use radio connections like they should

**Comment by Exxion** [comment]
But the same button sometimes works and sometimes doesn't

**Comment by Kurfursten** [comment]
@clusterfack Not relevant anymore, close it
