### ISSUE TITLE
Borg Stacks Borked

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4010]
I swear I saw an issue about this a while ago, but I can't find it.

If, as a borg, you run out of items in a "module" that is actually a material stack, this empty stack "module" becomes unusable (except for eating items of the same type) and, more importantly, impossible to put away, thus permanently taking up an active module slot.
Furthermore, adding items to these stacks (with material synthesizer or by picking them up) does not fix this. (Well, it *sort of* fixes metal rods in that grilles can be constructed by clicking them in the module equip panel, but only rods, and they still can't be put away.)

**Comment by Exxion** [comment]
Out of curiosity, is there a particular reason the borg material stack modules don't just delete themselves when empty? You know, like stacks under all other circumstances? It's not like they're irreplaceable. You just have to use the material synthesizer again.

**Comment by ComicIronic** [comment]
The stacks are pooled, so you're seeing a stack that is effectively del'd but actually sits in null space, which is why it can't be stored - since it isn't technically "in" the cyborg.

It doesn't disappear because pooling doesn't have the ref list Byond dels do.

**Comment by Exxion** [comment]
Huh.
Works perfectly fine for MoMMIs.
If possible, maybe the code handling their stack modules should be copied to borgs.

**Comment by PJB3005** [comment]
God this needs fixing, like, badly
