### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Disposal Parcel Sending Problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4011]
It takes the trash with it too to the destination

**Comment by Exxion** [comment]
How much trash follows them?
If it's all trash in the system or all trash following it until the destination is changed, that's not great
But if it's only other things very close to the tagged item in the disposals tubes, I'd argue that it should work that way. At the speed at which things pass through the junctions, it's not like every individual item could realistically be sorted.
Of course, that would cause problems if two items tagged for different locations were flushed at the same time.
It would also let you send yourself anywhere by hopping into a disposal chute right after putting a tagged package into it.
I don't know. Anyone else have thoughts on the matter?

**Comment by Probe1** [comment]
its basically what was on the conveyer belt at the time I believe.

**Comment by Starnightx** [comment]
I don't know but it's the second time i see all the trash coming with a parcel,before i never seen trash coming with the parcel

**Comment by wwjnc** [comment]
Chutes process items every X seconds. Everything inside the chute when it activates (see: when the *chuting* animation plays) moves through disposals at the same time in a wrapper atom. When the wrapper finds a labeled junction, it'll branch the wrapper if something inside is tagged with its label.

Putting efficiency reasons aside, I'd argue this is a good thing and it makes sense the way junctions are designed. The chute just takes a couple of seconds to reactivate and send in the next batch. Stop pulling the lever at the delivery office and making all the trash go through. ADD go away.

**Comment by Kurfursten** [comment]
@clusterfack WAD, close it
