### ISSUE TITLE
More hydroponic tray problems

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4013]
Being a machine and portable_atmospheric at the same time, the "you unwrench x from the fixture" attackby overwrites the portable_atmospherics wrench attackby for connecting to a port.
Removing the WRENCHMOVE | FIXED2WORK tags reveals more problems as none of the portable_atmospherics attackby return 1 when successful, which renders "if(..()) return 1" pointless and causes the action to be performed anyways.

**Comment by clusterfack** [comment]
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFUCK
