### ISSUE TITLE
Add smoke effects and wall destruction to Deathsquad teleports

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4018]
(obviously for after feature freeze) When the mechs show up have a moderate smoke cloud and whatever tile they land on the walls or windows break.  It will sell the fear of squid by making it all the more dramatic.

**Comment by DeityLink** [comment]
It's not a teleport, it's mostly a mass driver landing, and the update hasn't been merged yet even. Once I code it any mech sent from a mass driver at sufficient speed will burst through regular walls and windows.

**Comment by Probe1** [comment]
dis gon be so gud.  I think it really sells the fear of deathsquad, more than them being there themselves.  Like Hitchcock said half a century ago, “There is no terror in the bang, only in the anticipation of it.”

**Comment by Probe1** [comment]
also an explosion sound.  not an explosion itself but think of hearing 5 boom boom boom boom booms.  panic.jpg
