### ISSUE TITLE
(WEB REPORT BY: exxion REMOTE: 198.245.63.50:7777) You CAN make out the photo from here

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4019]
>Revision (Should be above if you're viewing this from ingame!)
a3da7b07bffbdbadf47ea8fb130e892fc4537ba7

>General description of the issue
Inspecting photos gives the list of people on it and what they are holding from any range. It just doesn't show the image itself.

>What you expected to happen
Not make out the photo

>What actually happened
Made out the photo

>Steps to reproduce if possible
1. Find photo
2. Inspect it from any range
3. Be amazed at your super sharp vision

**Comment by clusterfack** [comment]
Someone made it add everything to the description instead of another variable, FUCK
