### ISSUE TITLE
Allow device analyzers to scan camera assemblies

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4021]
(yeah, feature freeze it'll wait)

Being unable to scan camera assemblies makes it prohibitively difficult for all but the most autistic workers to get the AI camera coverage in maint.  Being able to scan them and produce them at the general fabricator would mean a lot.

**Comment by Manaony** [comment]
Just add a queue system to the autolathe.

**Comment by Probe1** [comment]
its kinda the autolathes gimmick that its shitty like that but that is an option.

**Comment by clusterfack** [comment]
Upgrade an autolathe = ultra fast camera assemblies

**Comment by Probe1** [comment]
doesn't matter

I don't want to stand there clicking, ctrl f'ing, waiting, and repeating.  I want to spam queue and do something better with my time.

**Comment by PJB3005** [comment]
autolathe needs a better UI, in general
