### ISSUE TITLE
(WEB REPORT BY: horsemanofconquest REMOTE: 198.245.63.50:7777) MOMMI CAN'T UNWRENCH

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4023]
>Revision (Should be above if you're viewing this from ingame!)
7cdc5cbd229151a2e9c14aad980e692ef4545163 

>General description of the issue
MoMMI cannot unanchor things with the wrench

>What you expected to happen
For things to be unwrenched

>What actually happened
Things were not unwrenched

>Steps to reproduce if possible
Wrench anchored things, proceed to not unwrench things

**Comment by Exxion** [comment]
Probably the same as #4024
