### ISSUE TITLE
Events and Gamemodes consider beings on centcomm as available

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#4026]
Events such as appendicitus, or gamemodes such as autotraitor consider beings on the centcomm zlevel as viable targets to traitor or give diseases to or what have you. We need to put some real sanity into procs that get_active_candidates or whatever to ignore a mob if he is on the centcomm zlevel.

**Comment by CptWad** [comment]
I think it also counts messes for the janitor.
Janitor can try his best wiping station clean but it counts every tile on all zlevels meaning he has to space travel just to clean places like the pirate shuttle and shit.
And if admins were dicking around at centcomm its another count against him
