### ISSUE TITLE
Firelocks adding themselves inappropriately to areas

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#4027]
Basically firelocks get the area of the turf they are on, and then check the area of the adjacent turfs to see what other areas are around them, and then assign themselves to those areas. 

However walls are also assigned to areas, and the firelock isn't actually checking if the adjacent tiles are ones that block air or not, so if a firelock is beside a wall separating two areas, it will add itself to both areas.

Simplified example: The firelocks that touch the walls of chemistry are assigning themselves to chemistry as one of their areas and will drop when chemistry has a fire. Despite every one of these firelocks being entirely outside of chemistry and touching its walls only.

**Comment by ComicIronic** [comment]
Pretty interesting catch for behaviour.

Would be fixed by a correct application of c_air_pass at some point in the code.

**Comment by clusterfack** [comment]
Cant fix this until sanade either gets his firelock thing fixed and merged or closes it

**Comment by clusterfack** [comment]
Still exists because I'm lazy!

![oh wow what the fuck is this are you some kind of faggot](http://puu.sh/l0iw6/a861d1718b.png)
