### ISSUE TITLE
Catwalks hold atmosphere

### ISSUE THREAD

**Issue by Lokiamis** [d3athrow/vgstation13#403]
They probably shouldn't considering that you can see space through them

**Comment by wwjnc** [comment]
The bug strikes back. Seems like catwalks were moved back to simulated turfs. Now it's even worse since airflow pushes things around with hilarious results. 

![Based ZAS]
(http://i.imgur.com/6HBoxFL.png)

**Comment by d3athrow** [comment]
Fix I did was have catwalks added to the same list space turfs are in.

**Comment by clusterfack** [comment]
I tried a few things but the little shits absolutely refuse to not be assigned to zones.
