### ISSUE TITLE
Let's fix bloodbags.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4031]
Actual Bug: Bloodbags that are supposed to spawn empty instead spawn as "Murky Bloodpack" containing 200 units of typeless blood, which effectively works as O-. This means the bloodbags that are supposed to spawn empty in Medbay, and alarmingly enough, bloodbags created from plastic sheets (yes, you can make blood from plastic).

Balance/Discussion/Feature Request/Whatever: As of right now, Medbay spawns with about 5 "universal" bloodbags. I feel like this is what it SHOULD be like, as otherwise you run out of blood extremely quickly and your only other options for O- blood are to powergame and set yourself to O- in character creation, or humanify all the monkeys in Genetics and test them all manually.
Blood loss is already hardcore as fuck, blood transfusions are already tricky. If you add bloodbag shortage on top, it just ends up in doctors letting bloodless people die and cloning them.

Addendum: You can technically also make typeless blood from blood tomatoes, but it's extremely unviable to do so since you can't put that blood in an IV drip.

**Comment by Probe1** [comment]
>it just ends up in doctors letting bloodless people die and cloning
don't forget you can order more from cargo

**Comment by 9600bauds** [comment]
You can, but it's, well... Cargo. I never see blood bags ordered when I play MD, personally. They also only come with one O-.

Also this is not a mapping issue, this is an issue with the "empty bloodbag" item, specifically.

**Comment by Probe1** [comment]
While I wish my feature request to have blood types added to advanced scanners had come through, you can still access a patients medical records via PDA or console and give them their blood type.  Taking 10 seconds to do it right means you have blood bags to spare and aren't dependent on using O-.

**Comment by Kurfursten** [comment]
@Probe1 My medical construction/deconstruction PR includes an upgrade for FBS to determine blood type. Feature freeze has started, though.

**Comment by 9600bauds** [comment]
O- blood is extremely important to have since a lot of people intentionally set themselves to O- blood in character creaction.
Myself included, so I can draw blood from myself as MD for antibodies and bloodbags. Which is kind of shitty and would like to stop doing it.

**Comment by Kurfursten** [comment]
Bug fixes addressed by the PR
>Plastic now creates EMPTY blood bags
>Empty blood bags are now properly empty
>Monkeys now have random blood type, so feel free to drain them

Balance
>Nanomed Plus now stocks 2 O- Blood Packs

**Comment by 9600bauds** [comment]
>Nanomed Plus now stocks 2 O- Blood Packs
Per machine? Two for the department seems just enough to not be naked at roundstart, but four might be a little too generous. There's also still one phalanximine bloodpack in the CMO's office, which ends up being typeless blood as well, now that I notice.
