### ISSUE TITLE
(WEB REPORT BY: kilkun REMOTE: 198.245.63.50:7777) SWAT helmet spaceproofing bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4037]
>Revision (Should be above if you're viewing this from ingame!)
64474a4df758a148de7a4337b654954bbbff91c6 

>General description of the issue
SWAT helmet no longer protects from lack of pressure

>What you expected to happen
To be able to space walk in a SWAT helmet as intended

>What actually happened
Slowly died from lack of pressure

>Steps to reproduce if possible
1.) Put on SWAT helmet
2.) Walk into space
3.) Die because no pressure protection

**Comment by clusterfack** [comment]
Pretty sure this used to be pressure protected only because it was the deathsquad's helmet. But that is no longer the case, @d3athrow may need to make a ruling on this one.

**Comment by d3athrow** [comment]
it was intended to be space worthy
