### ISSUE TITLE
(WEB REPORT BY: fudgepucker REMOTE: 198.245.63.50:7777) Rags do not clean floors.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4038]
>Revision (Should be above if you're viewing this from ingame!)
bff91c6

>General description of the issue
Rags do not clean floors with water or space cleaner.

>What you expected to happen
Clean floors

>What actually happened
Not clean floors

>Steps to reproduce if possible
Try to use rags to clean floors.
Fail horribly.

**Comment by ConkerDev** [comment]
Doesnt happen anymore, rags can clean floors.
