### ISSUE TITLE
(WEB REPORT BY: tersr REMOTE: 198.245.63.50:7777) Yellow Cap spriteless

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4043]
>Revision (Should be above if you're viewing this from ingame!)
69e63c296fbd258024bd6b566ffde75fd4caa544

>General description of the issue
The yellow Cap does not show on the charater when you equip it.

>What you expected to happen
A little yellow cap to appear on my character

>What actually happened
Character appears to not be wearing any hat

>Steps to reproduce if possible
Get a yellow cap and put it on

**Comment by BestName** [comment]
The sprites were still in before #3378 so blame @SkowronX
