### ISSUE TITLE
Braindead people getting autoborged

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#4044]
Braindeads can be borged using an autoborger, not exactly a bug, but it tends to waste a lot of time given the cooldown for the machine

**Comment by PJB3005** [comment]
...then don't put  braindead people on the autoborger?

**Comment by ComicIronic** [comment]
Why would you put a braindead in the autoborger?
Not a bug.

**Comment by AutismSpider** [comment]
Eh if people ghost when toss in the autoborger just give them temp ban etc.

**Comment by Intigracy** [comment]
close it up fam
