### ISSUE TITLE
Surgery messages for sleeping patients

### ISSUE THREAD

**Issue by Sikras** [d3athrow/vgstation13#4046]
RIght now, going into surgery for a lot of people is pretty much just "Hit sleep, alt tab out to do something else, check back in ten minutes." Unless you know beforehand that your doctor is a quick surgeon, you've got no indication at all for when, if ever, they'll be done your surgery, so a lot of times people are unresponsive for a few minutes even after their operations are done and they're standing, perfectly healthy, in the middle of medbay. On the other hand, sticking around for a quick surgery only to watch, bored out of your mind, as your doctor operates on the wrong limb or body part six or seven times before finally getting around to actually fixing you is just time spent staring at two stationary figures and a darkened screen.

I propose adding little messages that you, as a character, can feel through your anesthetized sleep. Something like "You feel a slight stinging sensation on your (bodypart being operated on)" for scalpels, "There's a small pinching on your (bodypart being operated on)" for the hemostat, et cetera. Not only would this give players experienced with surgery a rough indication of how their surgery is going and when they can expect to get back into the round, it would also serve to give players who aren't familiar with surgery a basic introduction to how any surgeries they go through are meant to proceed. Or, it could build a sense of horror as you realize that the traitor surgeon who has you helpless is lopping off your limbs.

The only thing I can think of that this detracts from is the possibility of stealthily implanting something in another player's body, but to be honest it's a tactic I've never seen used and I wouldn't notice it being gone. However, I'm interested to hear if other people would dislike this addition, and their reasoning for it.

**Comment by Ephx1** [comment]
Most traitors don't even implant things into people because the small unconscious view clearly shows things in people's hands. So once the patients are out of surgery they'll just scream about what the surgeon just did.

**Comment by PJB3005** [comment]
Well but that's the same level of metagaming as using info you got whilst ghost

**Comment by MercuryDoll** [comment]
Once the MoMMI's carbon-static is working, perhaps we could port that to unconsciousness too? Make people who are unconscious only see static people.

**Comment by Unfit** [comment]
The camera should jump to the beach while sleeping. Maybe add hallucinations in there too, to make it look like a dream.
