### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Solar still not working properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4055]
>Revision (Should be above if you're viewing this from ingame!)
f644dddb05942ea37dbd2c20817d8f580e41c139

>General description of the issue
Solar automated control not working when solar aren't producing power, might be because space isn't powered or something.

>What you expected to happen
Solar automated control to work properly as long as there is power

>What actually happened
Solar automated control stop working when the station is blocking the 'sun'

>Steps to reproduce if possible
Set solar to automated when the solar can't produce power watch as it doesn't work

**Comment by wwjnc** [comment]
This might be related to emitters not working when they're standing on a powered wire but outside of an area with an APC.

**Comment by clusterfack** [comment]
I fixed it, and yes it was. (You should have made an issue for that so I could have fixed all this faster)
