### ISSUE TITLE
MoMMI blank overlay has incorrect sprites

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4059]
For the Blank overlay that MoMMIs can select, Chickens will instead look like Cows.
Haven't tried it with anything else.

**Comment by ComicIronic** [comment]
Is it happening with the static overlay as well?
Is the letter overlay generating properly?

**Comment by AutismSpider** [comment]
it happens with both overlays

mobs fail to update when they are laying down on the floor or missing limbs

**Comment by ComicIronic** [comment]
The second one is not an issue, since MoMMIs shouldn't get that information anyways.
The first is due to the point at which the icon generation proc is called, which is before chickens get their icons sorted out.
