### ISSUE TITLE
Lockbox access negated by somatoray

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4062]
The addition of required access for lockboxes is completely negated by a single somatoray, since it takes one hit to destroy the whole lockbox and pop the goodies inside.

In fact it's even worse now than it was before since when people swiped their ID you occasionally at least found the lockbox saying who opened it, now everyone just destroys them.

**Comment by Probe1** [comment]
the somatory breaking lockboxes is a bug since it shoots radiation.. or something.  whatever it shoots its not ballistic or thermal.  
 
if it can't be used to hurt a player how can it destroy a lockbox

**Comment by ComicIronic** [comment]
Well, 'bug'...

The thread loves it, and won't stand to see it removed.

**Comment by Exxion** [comment]
So why even use lockboxes, then? Just removing them would skip the step that shouldn't logically work  but everyone takes anyway. It's basically the same final effect.

**Comment by clusterfack** [comment]
The same reason you don't remove access requirements from the stations airlocks, despite the fact that anyone with three tools and knowledge of one wire can open literally any door they want to on the station.

**Comment by Exxion** [comment]
But there's a substantial difference between having to find the wire and carry all those tools and just shooting a somatoray.
Personally, I just think that the somatoray and laser tag equipment shouldn't break lockboxes, but I am apparently outvoted.

**Comment by TermedClepe** [comment]
>thread
>consensus
Who cares, there's no rational explanation why it should be so easy to spam guns and combat mech weapons. Give security science access if this is intentional so there's at least some semblance of balance.

**Comment by Ephx1** [comment]
I thought this was already fixed in #1575?

**Comment by AutismSpider** [comment]
Nope its back.

Hell you can even open the lock boxes with the laser tag guns and stun guns.

**Comment by Ephx1** [comment]
Well if it was fixed then, I don't see why it shouldn't be fixed again.

**Comment by MercuryDoll** [comment]
Just in case someone's wondering: Somatoray doesn't work on lockers.

**Comment by 9600bauds** [comment]
Somatoray doesn't work on Cargo crates, either.

**Comment by AutismSpider** [comment]
nor do laser tag guns or stun guns work on cargo crates

but somatoray laser tag and stun gun can open a lock box fine

**Comment by Probe1** [comment]
I really don't see what's controversial about it @ComicIronic .  Might as well remove lockbox access requirement entirely (again)
