### ISSUE TITLE
[BOX] Waste loop disconnected from Service + medbay-sci

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4064]
With the new ventcrawl system it was very easy to find out what places are not traversable by knowing what was not connected.
Most of the bar, the kitchen, medbay, science, hydro library chapel and the hallway between them all **Are not connected to the main waste loop and therefore all waste scrubbers eat do not go back to atmos and stay in the closed pipe loop**
Thats why its so fucking hard to clean those areas up. They aint connected to shit

**Comment by CptWad** [comment]
Add sec to that list. Scrubbers also disconnected there from main loop

**Comment by CptWad** [comment]
And add arrival hallway

**Comment by ComicIronic** [comment]
Sec is deliberate. It runs on its own atmos.

**Comment by PJB3005** [comment]
are you sure about scrubbers, comic? I know sec's vents are disconnected (with only a valve)

**Comment by CptWad** [comment]
@ComicIronic If sec gets full of gasses and has to siphon and its waste loop is disconnected from everything then when the loop gets full they are fucked
If you want to keep sec being separate I recommend connecting a vent to space where all the waste goes

**Comment by Exxion** [comment]
Oh god atmos is such a pile of shit
I can't even tell what is connected and what isn't
It almost looks easier just to completely rebuild it from scratch
Don't quote me on this because I'm not finished looking yet, but it looks like most of the station starboard of the bridge is disconnected from the waste system at first glance.

**Comment by AutismSpider** [comment]
It's fine Exxion

Wast loop and the air loop are like spaghetti and it needs to be redone over all.

**Comment by CptWad** [comment]
Well with the new vent system it may be better to make pipes more based on rules
For my map thats getting done Soon(tm) when the pipes go down I have it in my head that the main line of pipes travels through the hallways and waste goes through maintenance.
It would be simple to set up and you could have a **real** loop for both pipelines that travels through the station as that would be much easier to traverse than what kind of pipes we have now.

**Comment by PJB3005** [comment]
yeah, we really need redundancy in the piping, knocking out a single pipe in REALLY hard to track down locations can disconnect a station from the loop entirely

**Comment by AutismSpider** [comment]
After using the new vent craw for a two days

We have three pipes you can take off form the loop to fuck over the station.All three of them are in the ass end of no were too.

**Comment by CptWad** [comment]
@PJB3005 Not to mention when greyshirt Mcfuckface blows an IED he ends up breaking pipes that are never fixed

**Comment by AutismSpider** [comment]
Best part when it happens to pipes under R-Walls about 10 or so pipes under R-Walls

Yes IEDs/C4 can damage pipes under R-walls and any cables.

**Comment by PJB3005** [comment]
Use a map to see where the pipes are, most of the time a greyshirt blowing shit up will result in damaged flooring nobody but engineering can be bothered to fix

**Comment by CptWad** [comment]
![full-0](https://cloud.githubusercontent.com/assets/3959840/7354368/ed84a2de-eccf-11e4-92d2-b9a5e388d970.png)
Aight I made a scrubbers pipe highlight map in about 30 minutes
Red is all pipes connected to atmos
Green are adjustments to be made to either connect loops together or make loops for the ventcrawlers and to noid breakage
Purple is connections that should be discussed before we touch them (Viro and xenobio)
Blue is the fuckhuge scrubber loop that is most of medbay + Sci + service
Black is the sec loop
Pink is the tiny unconnected arrivals loop

**Comment by AutismSpider** [comment]
Viro should have its own air line and wast line (like how it is now)

Not like it matters for xenobio 

Xenos will use space get out or scrubber line to move and player slime will just use the scrubbers/vent combo to move in and out

**Comment by CptWad** [comment]
I'd agree but I had the strange feeling someone wanted it changed

**Comment by Kurfursten** [comment]
While we're on the subject of fixing air lines, it kind of misses the point to have the air in Xenobiology fed from the main loop because vents can be ventcrawled.

It should get its air from the nearby air tanks, so that it is truly vent-isolated.

**Comment by CptWad** [comment]
Like viro?

**Comment by Shadowmech88** [comment]
>Not to mention when greyshirt Mcfuckface blows an IED he ends up breaking pipes that are never fixed because we did not know there was a pipe there

What about adding a device that functions like a T-ray scanner mixed with station blueprints, where it shows an overlay of pipes in an area based on how they were at round start, rather than showing the pipes that are there currently? It would be handy for Engineers fixing a breach to just take a device like that with them instead of having to tab back and forth to look at the station map to see where the pipes originally were.

**Comment by CptWad** [comment]
Make a separatefeature request. Pomfret has answered my prayers.

**Comment by CptWad** [comment]
>Pomfret 

Thanks auto correct
