### ISSUE TITLE
maint between captain's quarters and teleporter not radiation safe

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#4069]
Is the hallway between the captain's room and the teleporter considered a maint tunnel? I'm pretty sure it is.

Stand in it during a radiation storm and you get royally fucked up. If it "is" a maint tunnel, I dont think that should be happening.

**Comment by MercuryDoll** [comment]
Aren't the turfs that are going to be affected by the radiation storm blinking green? Is it still working for recent map changes (eg. custodial and mechanics rework)?
Also the message tells you to go into the *shielded* maintenance tunnels. Guess cap/tele tunnel isn't shielded.

**Comment by mrpain666** [comment]
When I get some spare time I'll have to fire up a test server and see for myself, I cant remember if that hall was blinking or not.

**Comment by mrpain666** [comment]
Pretty sure I saw it blinking a few days ago. Meaning it was probably unshielded by choice. If someone feels it should be shielded or it happened in error, go ahead and reopen this.
