### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Deadchat Mouse

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4071]
>Revision (Should be above if you're viewing this from ingame!)
97def510dad25382c72197b89728ee1dd95b4b8b

>General description of the issue
Dead mouses have no way to be differencied

>What you expected to happen
Being able to tell one mouse from another while they were dead

>What actually happened
Who know who was mouse

>Steps to reproduce if possible
Have more than one mouse in deadchat

**Comment by ComicIronic** [comment]
Mice need numbers.

**Comment by DrCelt** [comment]
Then who was mouse?
