### ISSUE TITLE
Cable bolas can't bola the same person twice

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4074]
Throw cable bolas on someone
Remove bolas from his legs
He is now forever immune to bolas

**Comment by ComicIronic** [comment]
If someone is successfully bola'd, they are forced to walk, not run.
Walking people are deliberately immune to getting tangled.
Unless there are any further details to this, you just didn't get the target's movement intent back to run, and this isn't a bug.

**Comment by Probe1** [comment]
@N3X15 close?
