### ISSUE TITLE
SMES' UI output level isn't nulled when it runs out of electricity

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#4076]
If a SMES completely drains, the output meter will not reset to 0, so they display whatever the drain was before going out. Not a critical bug but it's annoying as hell.

e.g. the SMES at engineering (capacity was 0 for each of them)
![help smes griffin me](http://i.imgur.com/rSuhEGf.png)

**Comment by Probe1** [comment]
agreed, I wouldn't call it a feature request I'd call it a bug.  the smes UI is unreliable and when there's a power issue I usually multi tool a wire to see how much is in the grid on both sides of the smes.
