### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Cannot exit golden space pods

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4077]
Revision: 97def510dad25382c72197b89728ee1dd95b4b8b 
Can't exit golden space pod found near astroids while mining

Admin had to pop me out

**Comment by Exxion** [comment]
I'm guessing you know the exit verb is in the spacepod tab rather than any other tab where it really should be. There was another issue a while ago that just turned out to be a failure to find the exit verb.

**Comment by 9600bauds** [comment]
Yeah, the verb is just very unintuitive.

**Comment by clusterfack** [comment]
I guess I'l change the verb to enter/exit but this really isn't a bug
