### ISSUE TITLE
HE pipes are stupid and broken and stupid again and I blame Duny

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#4078]
Currently, HE pipes (and by extent, thermal plates) radiate heat assymetrically when the environment has less than 10 total moles of gas. This is roughly 10 kPa of air (or any other gas, for that matter) at 20 ℃ in a regular turf (V = 2500 L).

This could be all fine and dandy if the radiated heat actually did something to the environment instead of being dissipated to bluespace and never seen again. In short, HE pipes in a room with less than ~10 kPa of gases will keep cooling the gas, which will in turn cool the environment if you repressurize the room and don't purge the pipes **completely**.

It doesn't help that the heat radiation speed is fucking stupid—you can cool down hundreds of MPa of gas close to absolute zero in just a couple of minutes. With just a couple of plates. There's no reason whatsoever to have these cool (no pun intended), giant, snakey radiator loops because with only a couple of thermal plates you're set!

You must be thinking now, "oh boy, it surely can't get worse!". **But it does!** Airless turfs have no gas in them (simulated ones at least by default). If you put a HE pipe in one, instead of not doing anything (which would be the SANE thing considering the above), they'll radiate heat at sanic speeds every `process()` tick.

Guess why the TEG/burn chamber at engineering never worked for you, or if it did, it worked poorly and it'd end up cooling down both loop and chamber to 10 K by some kind of space magic ooga booga shenanigans? The AAC script by default doesn't inject more than 10 moles of gas before shutting down, and even better, **the HE junctions connecting the hot loop are under the window, which are on top of airless turfs**! (*I've opened a PR to fix this*)

![mappers in charge of not breaking things](http://i.imgur.com/f7FQs6J.png)

This is something between a balance change and a bug report. Please discuss.

**Comment by PJB3005** [comment]
this is pretty fucked up

I want to TeG autism one day so this REALLY needs a fix

**Comment by Exxion** [comment]
That's too bad, because TEG's a pretty great generator.
Though I'm not sure why the thing only injects 10 moles of gas. The one on Ministation (shut up) just used the full contents of three canisters at once and, other than the ludicrous fuel consumption, worked like a charm.

**Comment by wwjnc** [comment]
It injects less than 10 moles of gas because the default AAC script is shit (and it doesn't even start unless you change the first script's temperature threshold)

**Comment by AutismSpider** [comment]
Some thing eggman did to HE pipes code.

HE pipes and thermal pads use the same code for cooling and heating gas

**Comment by wwjnc** [comment]
HE pipes are slightly better than pads for cooling since their radiation coefficient is higher. I'd change HE pipes to only exchange heat and make a new pipe thing or whatever to only radiate heat (which would affect the environment if there's one)
