### ISSUE TITLE
Add lock button and Fix access one

### ISSUE THREAD

**Issue by Starnightx** [d3athrow/vgstation13#4080]
Add the lock button like the dorms one to toggle door bolts and fix the acess button not being able to link or doing anything when clicked

**Comment by ComicIronic** [comment]
Where?
To what?
Fix what?

**Comment by Starnightx** [comment]
I'm sorry let me be more specific , Lock button maybe with Metal Sheets so you can make your own ,and fix all the access buttons you make with Metal Sheets,they basically do nothing when you click and there is no multitool panel to link it with a door or something

**Comment by PJB3005** [comment]
If you want a lock button rig up a signaller assembly to the airlock's bolt wire

Access buttons are indeed broken, but you can use airlock sensors as a replacement (fully)

**Comment by Starnightx** [comment]
I was looking for something that can bolt/unbolt the door

**Comment by ComicIronic** [comment]
A signaller  assembly can indeed bolt and unbolt a door.
The real thing to have would be to make attaching a signaller assembly to a wall possible, similar to the igniter-welding system already in place.

**Comment by d3athrow** [comment]
You can make a button and have it control various aspects of an airlock using a multitool

**Comment by Intigracy** [comment]
What pomf said is true, you can already do this with buttons.

close please
