### ISSUE TITLE
(WEB REPORT BY: fudgepucker REMOTE: 198.245.63.50:7777) Engineering Cameras in Atmospherics Monitoring has weird choices for cameras to list.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4082]
>Revision (Should be above if you're viewing this from ingame!)
45dc4

>General description of the issue
The cameras listed on the computer include: The SMES room on telecom sat, the ghetto bar, the production line in mining, a bunch of dark areas I assume are also on telecom sat, and recycling. There isn't any camera feeds for the solars, or even any parts of engineering itself. But oh man, having telecom sat is 10 times more important.

>What you expected to happen
Being able to view engineering from the atmos office

>What actually happened
Seeing that ghetto bar was still in a mess.

>Steps to reproduce if possible
Go to atmospherics monitoring. Look at engineering cameras.

**Comment by BestName** [comment]
Not a bug. The console shows areas with power alerts.
Why would you even want to look at engineering when it's right next to you and you've got access there?

**Comment by Kurfursten** [comment]
@clusterfack Not a bug, close
