### ISSUE TITLE
MoMMIs act as cameras again for AI

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4083]
Before it was MoMMIs couldn't be seen through for the AI as a way to curb them finding antags, but it seems they can be seen through again as shown by trying to track a Derelict MoMMI.

**Comment by AutismSpider** [comment]
Does this mean the Ai can track xenos like the old days?

**Comment by BestName** [comment]
Before? Before what?
They've acted as cameras for months.

**Comment by Ephx1** [comment]
Are you certain? I could've sworn that they were no longer viewable through cameras in areas without cameras.

**Comment by BestName** [comment]
Well at one point you couldn't click their name on the chat window to track them but they were still on the camera list and could be tracked with the track command.

**Comment by dylanstrategie** [comment]
The MoMMI static camera was a very, VERY old PR, and while obvious conflicts were solved it likely overwrote a significant amount of shit

If the fix to the AI tracking MoMMI bug was recent, that's where it went

**Comment by dylanstrategie** [comment]
Also for the record, I remember tracking a MoMMI on Security Cameras yesterday as a MoMMI. It's basically confirmed, even a basic check should prove it

**Comment by Starnightx** [comment]
Well AI and Security Cameras computer can trackdown any borg/MoMMI even russian station one

**Comment by Ephx1** [comment]
I'm uncertain if this holds true anymore, it seems to be wonky as hell if it does or doesn't work. Closing for now.
