### ISSUE TITLE
material synthesizer for mommis

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#4084]
This happens when i use the non mommi/engi borg material synthesizer

![error](https://cloud.githubusercontent.com/assets/10268342/7310103/31865c70-e9ec-11e4-88ec-eb5f568aa30b.PNG)

**Comment by 9600bauds** [comment]
Apparently MoMMIs aren't supposed to be able to pick up non-module material synthetizers, it'd be wise not to since the code assumes you're using the module if you're a borg.

**Comment by BarneyGumball** [comment]
MoMMIs picking up normal Mat Synths was removed in #5066
