### ISSUE TITLE
(WEB REPORT BY: 1pirateguy REMOTE: 198.245.63.50:7777) Clown mask doesn't toggle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4085]
>Revision (Should be above if you're viewing this from ingame!)
3dc5c33ab14e473fd0d938557b2ff145fd7dd6f1 

>General description of the issue
Trying to push clown mask up results in a missing sprite error

>What you expected to happen
Expected to have a clown mask above my face

>What actually happened
Sprite error

>Steps to reproduce if possible
Try to push clown mask up

**Comment by gbasood** [comment]
This still occurs. Clown mask literally disappears from your mob's sprite if you push it out of the way

**Comment by 9600bauds** [comment]
Why would a clown remove their mask anyways
