### ISSUE TITLE
ID/PDA Roundstart Fuckery

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4086]
If your ID is not in your ID slot when the game loads properly (character sprites finish loading), it is an unnamed ID with no connection to its holder other than having the same job. This also causes the holder's PDA to not be registered to a name. You cannot swipe the nameless ID to give the PDA a name because the ID has none. The PDA is therefore useless.
The official server is too fast for this to be an issue or something. I have never had it happen on the official server. I can regularly get it to happen when I run a server for testing, though.

**Comment by eswordthecat** [comment]
Because you don't have prefs for a character at local testing.

**Comment by Exxion** [comment]
But it works fine if the ID is in the ID slot when the round loads
That's a rather odd thing to happen

**Comment by eswordthecat** [comment]
Did you try to join as not a clown?

**Comment by Exxion** [comment]
I didn't even try a clown at all. Assistant and atmos tech because they were the most related to what I was testing.

**Comment by clusterfack** [comment]
This also happens on my local test server, I noticed it a few days ago but didn't really think anything of it. It may not be a live server issue but it is a codebase issue.

**Comment by PJB3005** [comment]
It's almost certainly an issue related to not having a name, which is probably related to not having a players database

**Comment by Exxion** [comment]
Yeah, it appears not to happen if I manually set a name
But then why does it usually work as it's supposed to?

**Comment by Exxion** [comment]
Never happened again in local testing after I made sure to hit random name each time

**Comment by clusterfack** [comment]
I think I fixed this issue at some point, it was a runtime in client/New in generating a random name when theres no database for a person.
