### ISSUE TITLE
(WEB REPORT BY: paragonofevil REMOTE: 198.245.63.50:7777) Crawl Through Vent bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4087]
>Revision 3dc5c33ab14e473fd0d938557b2ff145fd7dd6f1

>General description of the issue
Holy hell I can't crawl through vents, instead of listing room names it's listing a bunch of random room items. Fueltank? grille? My MMI? Where do those go? Why are no rooms listed?

>What you expected to happen
A list of rooms to crawl to should have appeared

>What actually happened
I got a list of random items. Lattice. Catwalk. Power Cell. Space. I think Disposal Access might be a room? The rest of this isn't. I also see my name on this list. And my MMI. I'm a Mommi, what is this.

>Steps to reproduce if possible
Be a mommi. Go to the vent in the mommi nest. Try to vent crawl. A window will pop up saying "Crawl-through-Vent mob|obj|area". I wonder where these will take me.

**Comment by Exxion** [comment]
Wait. Wasn't ventcrawl overhaul merged? Why is there even a window at all?

**Comment by AutismSpider** [comment]
pop up window giving you list of all the stuff in the room+shit you can see

When crawl through vent verb should make you crawl into nearest vent
