### ISSUE TITLE
Add taxistation to the map voting rotation

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4090]

**Comment by ComicIronic** [comment]
I believe it's missing an accounts database.

**Comment by clusterfack** [comment]
It really does need more testing though

**Comment by NigglyWiggly** [comment]
The shuttles are still fucked, aren't they?

**Comment by ComicIronic** [comment]
No.
Shuttles have been fixed for a while now - since before Christmas, if I remember right.

**Comment by NigglyWiggly** [comment]
No shit? That's rad, we could could probably force it a few times after Med RP week ends to do a bit of testing with a bunch of actual players, last time we did everyone seemed to enjoy it

**Comment by ComicIronic** [comment]
IT'S IN
