### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Derelict SMES (Maybe station too) problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4094]
Basically it generates power from nithing,i think if you make a loop with its output and input (connecting then together) you can set the charge to Max and it will still charge even without power on grid at start and after that you can set output to max making it self chargeable,a little weird but i think it's probably a bug

**Comment by ComicIronic** [comment]
See #4095
