### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Derelict SMES Problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4095]
Basically it generates power from nithing,i think if you make a loop with its output and input (connecting then together) you can set the charge to Max and it will still charge even without power on grid at start and after that you can set output to max making it self chargeable,a little weird but i think it's probably a bug,i think it works the station SMES too,i'll check

**Comment by Starnightx** [comment]
By accident i double posted the issue,you can delete this one.

**Comment by wwjnc** [comment]
How to reproduce:
* Form a closed loop with a SMES.
* Set it up to it recharges from itself (e.g. input = 90, output = 100)
* When it starts to charge, crank the input to MAX.
* ???
* It prints electricity!
* Turn off the output.
* Watch as all the petrocurrencies crash, Saudi Arabia is no more and Tesla Motors takes over the universe!

**Comment by clusterfack** [comment]
It doesn't actually make electricity, it just happens to put electricity into the powernet, and eat it back up if its available.

**Comment by Starnightx** [comment]
Also the Science APC Sometimes doesn't charge from the output coming from the SMES
