### ISSUE TITLE
Machines that require high powered micro-lasers will not take ultra powered micro lasers

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4097]
What it says on the tin.  Machines that need T2 parts (telecomms machines, the chicken gibber comes to mind) will not accept T3 equivalents.

**Comment by clusterfack** [comment]
I've noticed that for Tcomms machines, thought it was because tcomms is such special snowflake that it doesn't work properly. I wasn't aware that it also occurred on other machines.

**Comment by Probe1** [comment]
I believe it works for everything that requires tier 2 parts.

**Comment by clusterfack** [comment]
Oh that makes sense, somewhat

**Comment by Probe1** [comment]
I didn't write that as clearly as I should have.  I meant that the bug applies to machines that specifically call on tier 2 parts, like high-powered micro-lasers for example will not take ultra-powered micro-lasers (T2 requirement, T3 will not work).  I've found across any machine that calls for T2 parts they will not accept T3 ones.  

Which is a damn shame, but it's the tip of a lot of problems with machine part code (disjointed/inconsistent part affects, missing effects from upgrading parts on most machines, and this issue)

**Comment by clusterfack** [comment]
In that case it should be requiring the base part, (which is a parent and all other tier types fall under it), but also requiring that the rating be above a certain level. I think.

**Comment by Manaony** [comment]
Mecha that require tier 2 part will also refuse their tier 3 equiv if I recall correctly

**Comment by MercuryDoll** [comment]
If you mean mechs like the gygax and phazon, that is correct.

**Comment by clusterfack** [comment]
Ahhhhhh fuck fixing this normally, I'll just have me or comic add the functionality to construction datums and then switch the machine frame over to that system.

**Comment by Probe1** [comment]
fix it fix it fix it fix it fix it fix it fix it

**Comment by Probe1** [comment]
fib et

**Comment by clusterfack** [comment]
Incidentally fixed by #6684
