### ISSUE TITLE
Food/Chicken Processor layer bug

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4098]
When you build a chicken processor or food processor on top of an AI holopad it ends up beneath the holopad instead of on top of it.  I've tested this with a chemistry dispenser, chicken processor and food processor.  The chemistry dispenser was correctly on the top layer, blocking sight of the AI holopad.  The other two machines were underneath it.

Chicken Processor
![dreamseeker 2015-04-24 21-06-40-395](https://cloud.githubusercontent.com/assets/8550416/7330878/87f67eac-eac6-11e4-9074-0d54fbdfd8de.png)
Food Processor
![dreamseeker 2015-04-24 21-11-54-362](https://cloud.githubusercontent.com/assets/8550416/7330880/94bee8e0-eac6-11e4-8b23-0fb375aecf58.png)
Chem dispenser
![dreamseeker 2015-04-24 21-11-59-588](https://cloud.githubusercontent.com/assets/8550416/7330881/9784a20e-eac6-11e4-98da-6d6004748979.png)

**Comment by PJB3005** [comment]
layering is fucked
