### ISSUE TITLE
(WEB REPORT BY: buxus REMOTE: 198.245.63.50:7777) Alien Hunters can burn plasma without actually laying weeds

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4100]
>Revision (Should be above if you're viewing this from ingame!)

95f96d37c982ab1fec0f39af5f5491b653a66e07 

>General description of the issue
If you click Plant Weeds (50) while floating over space, it still burns your plasma without laying weeds.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Buxus** [comment]
Close this, I'm just dumb and didn't realized being in stalk burned plasma

**Comment by clusterfack** [comment]
DELETE THIS
