### ISSUE TITLE
(WEB REPORT BY: gespacho REMOTE: 198.245.63.50:7777) Spiderbots unable to ventcrawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4104]
>Revision 
06f03792ed42419c6e62a556a73b06300ee8128f

>General description of the issue
Spiderbots seem unable to ventcrawl, probably because of the shock arm or whatever it is they come equipped with.

>What you expected to happen
Vent crawling

>What actually happened
Unable to ventcrawl due to equipped item

>Steps to reproduce if possible
>Be spiderbot
>ventcrawl
>No trebajo

**Comment by clusterfack** [comment]
NEEDS MOAR TESTING. There's already an issue open about this same thing, (admittedly before comic's ventcrawling changes were merged), and I could not reproduce this.

**Comment by Ephx1** [comment]
![spiderbot](https://cloud.githubusercontent.com/assets/6224074/7666932/f0ce9864-fbc5-11e4-955d-63c8351e0966.png)
Alright, I finally got to be a spiderbot in a round.
This is what happened when trying to ventcrawl.

**Comment by clusterfack** [comment]
Constructed spiderbots must be having some issue different than spawned ones. Perhaps it is counting the spiderbot's mmi or posibrain.

**Comment by SarahJohnson489** [comment]
Bumping

![untitled](https://cloud.githubusercontent.com/assets/5564796/8147997/eb34ca44-1232-11e5-8169-79ff78537601.png)
