### ISSUE TITLE
Emitters wont connect to powernet on nonturfs

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#4119]
So since space becamee a valid target for wiring, and since catwalks were converted to not be a turf anymore, the connect_to_network proc which has sanity against power machines not being on a turf will fail to connect the power machine to the powernet on the tile. 

So we need to modify either the checks in some way to allow catwalk emitters or take some other option. One of the issues with the way they work now is if you created a plating under them, they still wouldn't connect to powernets until they are rewelded because it is only called the one time.

**Comment by ComicIronic** [comment]
But space is a turf.

**Comment by clusterfack** [comment]
Well thats just dandy for space but it still wont connect to a powernet on a catwalk
