### ISSUE TITLE
You can no longer place items in bags that are inside a bag of holding

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4123]
Take something that will fit in a bag, open your bag of holding.  Try to put that item from your hands to the bag inside the bag of holding.  No dice, won't work. 

Edit - you can still take things OUT of bags that are inside bags.  For example if I wanted to take something out of a cardboard box that was inside my bag I could open my backpack, shift drag the box to open that, then remove any items from it without removing the cardboard box from the bag first.

**Comment by clusterfack** [comment]
It's always something

**Comment by Probe1** [comment]
the day we stop getting new bugs is the day we stop getting new features.

**Comment by ComicIronic** [comment]
This is to do with the attackby Adjacent check for items not setting the right recursiveness level for storage items, which is MAX_ITEM_DEPTH. That's what allowed storage items to be opened in other storage items in the first place.

**Comment by clusterfack** [comment]
You could remove the attackby check if it cant be fixed in this case. I fixed the 'real' issue that you could keep a storage menu open when thrown, however if someone finds another way to abuse it like this, it would be troublesome and we may not hear about it for a long time.

**Comment by Probe1** [comment]
Thank you.
