### ISSUE TITLE
Scoreboard mining and botany harvest score needs reduced

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4125]
I'm yet to see any shift with miners and botanists NOT get the highest possible score.  Reduce it to like 0.5 points per ore mined and item harvested.  I know, it's not the biggest deal.

![image](https://cloud.githubusercontent.com/assets/8550416/7335886/f832a5d0-ebaa-11e4-9add-543962e7b9ce.png)

**Comment by clusterfack** [comment]
Ahhh just let us tag them

**Comment by Probe1** [comment]
I'll move it to the text itself instead of the title.  I like people having an idea of what I'm about to talk about from the get go so it's not a mystery novel with twists and turns before the surprise ending that it was a feature request.

**Comment by ComicIronic** [comment]
That just seems like a really clean round.

**Comment by Probe1** [comment]
@ComicIronic since it was added almost every round ends up with 10000 + score
