### ISSUE TITLE
(WEB REPORT BY: shomek REMOTE: 198.245.63.50:7777) Being able to shoot from inside a cyborg recharging station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4129]
>Revision 45fb495c6613e14ce6c61e914a39f1bb71acb60f 

>General description of the issue
You can shoot from inside (while recharging, obviously) a cyborg recharging station

>What you expected to happen
Being unable to do anything.

>What actually happened
You can perform actions such as use ranged weapons.

>Steps to reproduce if possible

**Comment by ShoMek** [comment]
You can shoot forever with your gun. Yeah, not really balanced.

**Comment by clusterfack** [comment]
Shit is OP yo

**Comment by 9600bauds** [comment]
You can also shoot from inside locked welders IIRC

**Comment by ComicIronic** [comment]
It's do to with the fact that guns use get_turf(user), when they should really use user.loc.
