### ISSUE TITLE
Transit tubes cause pressure damage

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#4130]
I managed to fix this briefly somehow but now it seems to be causing damage again. It injures anyone trying to get to the AI satellite.

Maybe someone could code it so you cannot take pressure damage when inside a tube?

**Comment by ComicIronic** [comment]
Could start the tubes with a regular air mix, or have them mingle with the environment when they open.

**Comment by wwjnc** [comment]
Is having them mingle a good idea? There are some exits on (probably) depressurized turfs, like the one SW of the research station.
