### ISSUE TITLE
(WEB REPORT BY: shomek REMOTE: 198.245.63.50:7777) "Custom" button not working on ID computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4131]
>Revision 45fb495c6613e14ce6c61e914a39f1bb71acb60f 

>General description of the issue
You can not change "custom jobs/ranks". You click the button and nothing happens.
>What you expected to happen
A window pops out when you click the button and you type in the custom rank, your ID card has a new job/rank name.

>What actually happened
No window pops out.

>Steps to reproduce if possible
Approach an ID computer and...try to select a custom rank.

**Comment by clusterfack** [comment]
Also a duplicate
