### ISSUE TITLE
Custom job names in ID console don't work

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4145]
Clicking custom job doesn't do anything.

**Comment by clusterfack** [comment]
DUPLICATE AGAIN. THANK YOU.

**Comment by DrCelt** [comment]
@clusterfack
Better a duplicate than never being reported because "someone has probably
already reported this"

Plus it's good for the open/close ratio!

**Comment by clusterfack** [comment]
He could have taken 10 seconds to search 'custom' or anything else. He already made one duplicate report under an hour ago.

**Comment by ComicIronic** [comment]
> it's good for the open/close ratio!

It's bad for the open/close ratio!
1/2 open/close is far better than 101/102 open/close with duplicates.

**Comment by TermedClepe** [comment]
>caring about ratios
