### ISSUE TITLE
Clown and mime name issues/inconveniences

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#4148]
It isn't clear how much time you have to pick a name when joining as a clown/mime. If you can't think of a name right away, when you finally type it in it may not change at all.
If you're a clown/meme ling then you can't fully change into your initial form, as it will have the name of your character (e.g. you have a character named Dick Johnson -> join as a clown ling, get name Candy -> transform into somebody -> transform back - your name will be Dick Johnson)

Also being able to confirm your name choice would be great, because if you make a mistake in your name then your only hope of fixing it are admins.

**Comment by 9600bauds** [comment]
>meme ling
fuck this meme game and it's meme antags
