### ISSUE TITLE
(WEB REPORT BY: saronsen REMOTE: 198.245.63.50:7777) Mining cyborg satchel spam

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4150]
>Revision: 9f10dc411b9f5b9436f76adb8f9f7f4288c75837 

>General description of the issue:
Miner cyborgs spam YOU FAIL TO PICK ANYTHING UP WITH THE MINING SATCHEL if you run over disposal pipes, lights, and various other built items with the mining satchel in your toolbar.

>What you expected to happen
Nothing.

>What actually happened

http://puu.sh/hrFvk/c73bc78485.png

>Steps to reproduce if possible
Step 1: Be miner cyborg
Step 2: Put drill, satchel, and accelerator in toolbar
Step 3: Run over disposal pipe on mining asteroid
Step 4: ???
Step 5: Profit

**Comment by clusterfack** [comment]
Kek

**Comment by ComicIronic** [comment]
Woooops.
I thought checking contents would be cheaper, but I'll just use locate() (or for(), since it's cheaper) to do it.
