### ISSUE TITLE
(WEB REPORT BY: exxion REMOTE: 198.245.63.50:7777) Nullspace is accessible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4151]
>Revision (Should be above if you're viewing this from ingame!)

9f10dc411b9f5b9436f76adb8f9f7f4288c75837
>General description of the issue

I walked off the edge of the Z-level into nullspace.
>What you expected to happen

Nothing.
>What actually happened

[13:08:18] Fruity Vegetomato PM from-Mustardtiger: nigga you are lost in void
>Steps to reproduce if possible

1. Be ghost in space (mass-drivering yourself while carrying the nukedisk might also work, alarmingly)
2. Use click movement to get to the very edge of the Z-level (or don't, in the nukedisk-mass-driver case)
3. Step off the edge of the Z-level
4. Become world-renowned magician

**Comment by ComicIronic** [comment]
Ghosts in space still isn't fixed.
