### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) Glass Sprite ISsue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4153]
>Revision (Should be above if you're viewing this from ingame!)
9f10dc411b9f5b9436f76adb8f9f7f4288c75837 

>General description of the issue
Lifeline does not properly display a sprite when put in a glass, instead becomes Glass of What

**Comment by AutismSpider** [comment]
if its for the new coffee base drinks you need put it in a mug not glass

**Comment by Kurfursten** [comment]
Issue should be changed to "Mugs are not obtainable", then.

**Comment by Kurfursten** [comment]
@clusterfack Close this, WAD
