### ISSUE TITLE
(WEB REPORT BY: exxion REMOTE: 198.245.63.50:7777) Oil equals blood

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4157]
>Revision (Should be above if you're viewing this from ingame!)

b9d3323b4ebf3d0fe0348c52a58fac24cf4e540c
>General description of the issue

Stepping in oil marks your shoes as "blood-stained"
>What you expected to happen

Something like "oil-covered" or "dirty"
>What actually happened

"blood-stained"
>Steps to reproduce if possible

1. Wear shoes
2. Step in oil
3. Cyborg blood???

**Comment by clusterfack** [comment]
I don't see how
![](http://puu.sh/lgEiu/2dfbd5449d.png)

The oil would have to have DNA which I'm not sure how that can happen anyway

**Comment by Exxion** [comment]
I don't know when this was fixed, but it was fixed.

**Comment by clusterfack** [comment]
ok
