### ISSUE TITLE
Head Problems

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4158]
![image](https://cloud.githubusercontent.com/assets/9827785/7340032/c1b1a00e-ec51-11e4-832a-a5c2df973b03.png)

1. I really shouldn't know anything about any expression on his face.
2. "He has had his brain removed" is a bit redundant.

**Comment by DrCelt** [comment]
>he can't tell someone's facial expression by the neural messages in his
spine
Wow.

**Comment by clusterfack** [comment]
Has brain damage, with no head, and it makes him look like an idiot. Classic.

**Comment by ComicIronic** [comment]
>Nurse, I'm going to perform a lobotomy!
>*drags patient over to guillotine*
>After this, he definitely won't have a brain!
