### ISSUE TITLE
Fire Axe TOO Robust

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4159]
Unless it deals extra self-damage, this is too much. I accidentally hit myself with it once when at full health, fell down, and died of blood loss maybe 30 seconds later.
If it does deal extra self-damage, then this issue is badly named, but... why?

**Comment by 9600bauds** [comment]
It's far from robust, it just has very high melee damage.
The problem being that your melee damage matters jack fucking squat because it's entirely trumped by anything with even the slightest stunning capabilites. The guy with the Fireaxe and full armor will always get shat on by the guy with a telebaton.

**Comment by Exxion** [comment]
OK, but my point is that it is a one-hit kill, which is entirely too much damage.

**Comment by AutismSpider** [comment]
24 damage when you two hand the fire axe on top of making you bleed on the 1st or 2nd hit this not counting lucky stun you can get form it

**Comment by 9600bauds** [comment]
It's not a one-hit kill either, I've tested this a few times and haven't been able to reproduce. It's 25.8 brute and I couldn't even get myself to bleed unless I whacked myself twice in a row.
Not even that much more damage than an energy sword (19.8 brute), with the downsides of not blocking projectiles, needing to be dualwielded and not fitting in your backpack. I'd still take anything with a stun or an esword over a fireaxe any day.

**Comment by Exxion** [comment]
Huh. Odd. Maybe it's just a one-hit kill on a REALLY lucky hit or something.
That or there's something fishy going on, but I doubt that.

**Comment by clusterfack** [comment]
Depends on the armor you are wearing, yeah?

**Comment by Exxion** [comment]
Apparently I was just very unlucky
