### ISSUE TITLE
(WEB REPORT BY: jidders REMOTE: 198.245.63.50:7777) Genetics bugged?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4161]
Seems like the DNA modifiers and DNA is a bit wonky? When doing a clean SE it doesnt get rid of some changes (like small) and even doing small radiation pulses can cause huge SE changes (like 4 blocks changing) Is this intentional?

**Comment by MercuryDoll** [comment]
"small stature" is currently being fixed. SE changes don't always trigger abilities/defects, just as ryetalin doesn't clean your SE, it just supresses mutations. #4120
what do you mean with small radiation pulses?

**Comment by CptWad** [comment]
He means when you have the modifier blast at the lowest range
I agree genetics is wonky and its most visible with some language related powers
Sometimes when you get something, say swedish, you never bork until a while later, then if you cure it it does not go away until a while later
Additionally before when you pulsed someone the less radiation the person had the less likely a false pulse would happen and another block would be affected.
Now when you first pulse your monkey to make them human what used to be a 99% chance of making a human monkey is a 40% chance of human monkey and 60% chance of pulsing another block leading your first clean SE to be fucked if you use that monkey and you force yourself to pull another monkey out just to get the perfect clean SE
I guess the best way to put it is that some how genetics is lagging on its own. Powers manifest a while after they tell you they did.
**It is not SE changes not manifesting at all it is them manifesting after they should have**
