### ISSUE TITLE
(WEB REPORT BY: bobby177 REMOTE: 198.245.63.50:7777) Gas Mask + Welding Helmet intermittent bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4169]
>Revision 138abdc0dccc5f6a4e64c40109916cb13f65c3d5 

>You used to be able to 1) put on gas mask, 2) put on welding helmet, 3) flip up welding helmet. This would result in your face showing but your character still receiving the effects of a gas mask being on. Skowron told me to report it even though it seems like it was fixed. Or maybe it's an intermittent thing.

**Comment by ComicIronic** [comment]
This was bugged behaviour.

**Comment by 9600bauds** [comment]
Pretty sure this is fixed
