### ISSUE TITLE
Cult Constructs retain spells when Staff of Change'd

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#4170]
Title sums it up, to test
Step 1: Be a cult construct
Step 2: Get staff of changed
Step 3: Enjoy using your old spells to fuck with people

This is a significant issue because when a wizard is staff of changed, they also retain their spells. That makes sense and should remain the case, but its weird that you can still shit out soulstones as a human because some wizzard dickhead turned you into an artificer and then staff of changed you back.

**Comment by Exxion** [comment]
Stealth Juggernaut?

**Comment by Arthurdentist** [comment]
Well the only spell Juggernauts actually have is being able to create cult forcewalls, the worst offender is definitely wraiths and artificers.

**Comment by CptWad** [comment]
Wizards should keep spells. I always found EI NATH slimes hilarious

**Comment by ComicIronic** [comment]
I think this was fixed.

**Comment by ComicIronic** [comment]
Unless someone can confirm this is still an issue, it's getting closed.

**Comment by Arthurdentist** [comment]
Cult constructs no longer retain spells, they do retain construct language though.
