### ISSUE TITLE
(WEB REPORT BY: pomf123 REMOTE: 198.245.63.50:7777) conveyors in pictures

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4171]
they always appear going north to south.

**Comment by PJB3005** [comment]
I blame BYOND.

The code for the camera is probably hacky enough as is.

Thanks BYOND for having a proper way to do screenshots that aren't clientsided.

/s

**Comment by ComicIronic** [comment]
Another thing that needs to be added to the directional list.
