### ISSUE TITLE
Rework upgrading cameras

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4172]
To upgrade a camera you have to disassemble it completely then rebuild it and add the carrot/uranium/whatever to upgrade it.  Instead, let players upgrade them by screwdriver opening the maint hatch and inserting the upgrade object there without having to disassemble the entire thing first.

**Comment by CptWad** [comment]
:+1:

**Comment by clusterfack** [comment]
Lots of old code that needs refactoring in these files

**Comment by 9600bauds** [comment]
Technically have this done since it's a super simple addition, but holding out until someone with a better idea than me looks over #4592 or the camera code in general since it's widely renowned for being bad.
