### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Meta Club map issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4173]
>Revision (Should be above if you're viewing this from ingame!)
b8d9f808405d2f6f3c3d82ef1ba4e01afb6681ba

>General description of the issue
Bad wiring for the northern emiters on meta

>What you expected to happen
Emitter to start when turned on

>What actually happened
I had to rewire hidden cable before being able to start singuloth safely

>Steps to reproduce if possible
Play Meta

**Comment by IratePirate** [comment]
Damn this was bad. Fixing now.
