### ISSUE TITLE
(WEB REPORT BY: saronsen REMOTE: 198.245.63.50:7777) Heat Gun massacring cyborgs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4179]
> Revision: 6cfe75ea46e08ac6753d1a4d2389a2a40460a6c0 
> 
> General description of the issue

A temperature gun seems to do OBSCENE amounts of damage to a cyborg, as well as doing completely unrepairable damage (Nothing to fix here!). Not only that, it will continuously count down a cyborgs integrity for an unknown duration. 

> What you expected to happen
> A cyborg that can stand in gorillion degrees plasma fires to not evaporate to a temperature gun.
> 
> What actually happened
> ZSHOOM ZSHOOM DEAD CYBORG. Huge chunks of health removed in single shots, and a constant decay of integrity.
> 
> Steps to reproduce if possible
> Become Engie/any cyborg. Get shot with a max heat temperature gun. Try to fix self with welding tool. Try to survive your heat-induced death similar to humans/vox/etc

**Comment by AutismSpider** [comment]
i think the temp gun is setting the cyborg on fire.

This is what emag temp gun does sets mobs on fire.

**Comment by CptWad** [comment]
To repair I think you have to repair wires and replace components
But noice find

**Comment by ComicIronic** [comment]
It seems that borgs don't have protection against manually editing their body temperatures.

**Comment by AutismSpider** [comment]
happens to borg/mommis.

Why does the temp gun manually edited the temp?

**Comment by ComicIronic** [comment]
I assume it was just the best way of doing it at the time.
Really, it should be done using a mob proc, but that's basically SS13.
