### ISSUE TITLE
(WEB REPORT BY: saronsen REMOTE: 198.245.63.50:7777) Mediborg Trauma/Burn kits jamming

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4180]
>Revision 6cfe75ea46e08ac6753d1a4d2389a2a40460a6c0

>General description of the issue
When using a trauma or burn kit rapidly on a wounded players limbs, you can use all of the charges up, and it will jam in the toolbar (in a manner similar to the cyborg beaker) and become unremoveable.

>What you expected to happen
Trauma/Burn kits to be removeable even after all 'charges' are used up

>What actually happened
SHITS STUCK. Can't get it out of your toolbar, and from my experiences, won't be able to until you receive a reset module.

>Steps to reproduce if possible
Become mediborg. Find target with damage on all body parts. Use trauma kit quickly on all body parts like you're trying to save a life. Run out of charges and panic.

**Comment by MercuryDoll** [comment]
A lot of mediborg's tools are fucked up. The unstorable beaker, someone dropped his hypospray recently, kits bugging out and sometimes the tools from the upgrade are simply not usable at all.

**Comment by Exxion** [comment]
Also sounds a lot like material stacks on engiborgs.

**Comment by FudgePucker** [comment]
Yea I had the material stack bug on engiborg as well a few days ago.
It was when I put metal and glass into the exosuit fab.
I think maybe it has to do with them being used up but still existing, you can't store it, but it still uses up one of your module slots.
I remember it being bugged for MoMMIs as well. As was the cable coils, but that was just cable coils sprite disappearing after being used up and not updating after recharging.
Maybe there's some check failure or some shit.
I don't know silicon code.

**Comment by clusterfack** [comment]
Unid fixed stacks for silicons, he must have missed this bug when he was closing them all.

In off chance that it WASN'T fixed with all the other stacks somehow please reopen this or a new issue.
