### ISSUE TITLE
Chair cuffed dead people face the wrong way

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4182]
Get a dead person under a east/west facing chair
Cuff them to the chair
They will not face in the direction of the chair but rather north/south

This ruins the immersions.

**Comment by CptWad** [comment]
Works with beds too. I cant choose which way I face when buckling to a bed

**Comment by Zth--** [comment]
I have never seen such a thing. I really doubt it still happens. Close it?

**Comment by PJB3005** [comment]
Yeah probably fixed with atom locking.
