### ISSUE TITLE
(WEB REPORT BY: morriak REMOTE: 198.245.63.50:7777) Setting fireaxe on table while holding with both hands places the off-hand sign on the table

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4183]
>Revision (Should be above if you're viewing this from ingame!)
f008d26ef7afc6ffe785a405ee77b72f66ad7e78 

>General description of the issue
Holding the fire axe with both hands and placing it on the table puts the axe and the off-hand sign on the table as seperate items

>What you expected to happen
Just the axe would be placed.

>What actually happened
An off-hand sign was also placed on the table

>Steps to reproduce if possible
Hold a fire axe with both hands
Click on a table

**Comment by Morriak** [comment]
Upon further review, this only happens if the off-hand sign is your current selected hand, I should have checked that first. Shits still busted though.
