### ISSUE TITLE
(WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) [box] 2 broken singularity shutters to the left of the PA.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4184]
>Revision (Should be above if you're viewing this from ingame!)
20e6a78ac5adba2da89de18b42218b4ca55aae66 

>General description of the issue
There's 2 singularity shutters that are called 'podlock' and aren't controlled by the button

>What you expected to happen
ALL of the shutters would close.

>What actually happened
2 to the left of the PA didn't

>Steps to reproduce if possible
go to engineering
press the singulo shutters button
watch as 2 don't close

**Comment by clusterfack** [comment]
It happened due to an ingame thing and admin intervention
