### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Alien Robes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4185]
Revision: 20e6a78ac5adba2da89de18b42218b4ca55aae66 
Alien robes have no suit sensors, is that a bug or a FEATURE?

**Comment by clusterfack** [comment]
I think its a feature?

**Comment by Ephx1** [comment]
Well, considering the Vox raiders start with their own crew monitor computer that doesn't seem to track anything at all, I don't know. I think at first they were supposed to have suit sensors so that other raiders could track one another.

**Comment by clusterfack** [comment]
Well you definitely DONT want them being tracked by the crew

**Comment by Ephx1** [comment]
I mean like, the Crew Monitor on their ship was supposed to only track raiders for retrieval.
I haven't seen it track anything else, so my only guess is that it was made for raiders only.

**Comment by clusterfack** [comment]
Yes but did it -ever- even have the functionality to start with

**Comment by Ephx1** [comment]
Nope, I guess it was never actually finished. I wonder why?
If we still had the kidnap objectives, it could've been useful as a normal crew monitor.
