### ISSUE TITLE
Mesons amplify weld blind like thermals

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4187]
That's Optical Meson Scanner. It is a small item.
Your thermals intensify the welder's glow. Your eyes itch and burn severely.
You go blind!

**Comment by Probe1** [comment]
Were you wearing a hardsuit helmet or welding helmet?  The rig helmet is supposed to protect you but just wearing them alone isn't enough.  Without protection its working as intended.

**Comment by ComicIronic** [comment]
I don't know what to tag this.
Balance? Feature loss?
It's not a bug, it's intended code behaviour.

**Comment by clusterfack** [comment]
>Your thermals intensify the welder's glow

^See "thermals"

**Comment by TermedClepe** [comment]
It's a bug because mesons don't intensify welding, thermals do. Mesons are not thermals, thermals are the syndicate item.

Thermal = temperature related, as in welding being very hot makes you blind, mesons have nothing to do with heat.

Reread the message.

**Comment by ComicIronic** [comment]
It is intended code behaviour.

The message is incorrect, but that was not the original bug reported.
Mesons deliberately cause eye damage.

**Comment by TermedClepe** [comment]
It can't be intended behavior because the message was clearly meant only for thermals since implementation.

**Comment by Delimusca** [comment]
[tools.dm#L443](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/objects/items/weapons/tools.dm#L443) it gives that message for any negative eye protection.

**Comment by ComicIronic** [comment]
>It can't be intended behavior because the message was clearly meant only for thermals since implementation.

That's what's called an "oversight".
Mesons actually reducing welder protection is a deliberate part of the code.

**Comment by Probe1** [comment]
does anyone know how mesons are supposed to work?  like the 'lore' behind them.

**Comment by MercuryDoll** [comment]
http://en.wikipedia.org/wiki/Meson
my guess is they scan the area on a sub-molecular level radar style and visualize it to the wearer by rendering a 3D scene with [transparent walls](http://i.imgur.com/5y52Qew.jpg).

**Comment by 9600bauds** [comment]
I believe this is not an issue anymore, at least not with a miner rig + mesons.
