### ISSUE TITLE
Mass Drivers no longer work

### ISSUE THREAD

**Issue by Dr-Explosion** [d3athrow/vgstation13#4188]
Something has broken mass drivers such that pushing the button no longer makes them fire.

It may be a mapping rather than coding issue, please check buttons.

**Comment by ComicIronic** [comment]
@DeityLink

**Comment by clusterfack** [comment]
To be specific its the mass driver button in research outpost atmospherics on box

**Comment by PJB3005** [comment]
that driver has been broken from before deity's PR

**Comment by DeityLink** [comment]
OH SHIT I KNEW I HAD TO FORGET ONE, wait, it shouldn't have broken, I didn't touch the way buttons interact with drivers, let's see...

**Comment by DeityLink** [comment]
Wait, I just tested the button and it works perfectly fine, did you reproduce the bug at all?

**Comment by clusterfack** [comment]
I saw it happen so... yeah

**Comment by DeityLink** [comment]
Next time you see it happen, check the id_tag of both the button and the mass driver.

**Comment by clusterfack** [comment]
Their ID tag are the same, however it does not launch on the live server

![](http://puu.sh/hw5Xz/e64a222f37.png)

**Comment by clusterfack** [comment]
It seems the issue is stat = 2 on that mass driver, now which was that broken or unpowered I can never remember, but that's the problem

**Comment by DeityLink** [comment]
It's NOPOWER indeed. I just checked on the server. I'll think of a proper fix later today.

**Comment by PsiOmegaDelta** [comment]
One way to 'cheat' is to map in the same area over the mass driver that powers the button.

**Comment by DeityLink** [comment]
oh don't worry, I know of many ways to fix that, I'll just decide on which is the most appropriate

**Comment by DeityLink** [comment]
The problem is much larger than that, it's not just mass drivers but all the bulb lamps that used to light up the path from the research outpost to the mining station that are now power deprived. Looks like some snowflakes for the asteroid are in order.

**Comment by PsiOmegaDelta** [comment]
Power the explored parts of the asteroid with a single APC? :P

**Comment by DeityLink** [comment]
That's actually the solution I'm leaning to right now, I'm doing some test on the main server. I'll probably add a small room on the asteroid with an SMES and an APC that'll power the asteroid.

**Comment by clusterfack** [comment]
Er, I think someone intentionally DE powered the asteroid.

**Comment by DeityLink** [comment]
nope clusterfack, we found the problem in there #4207

**Comment by clusterfack** [comment]
The other issue is more relevant at this point and encompasses this
