### ISSUE TITLE
Genetic defects cannot be cured.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4193]
When you gain a defect, it can stick with you regardless of what you attempt.
Rye does not fix it
Clean SE does not fix it
This is a clearer version of my last issue.

**Comment by ComicIronic** [comment]
Can you name some specific defects this applies to?

**Comment by CptWad** [comment]
Mostly speech impediments. Maybe its a saycode issue and not genetic?

**Comment by ComicIronic** [comment]
Recent changes to rye appear to have ruined everything.
