### ISSUE TITLE
[Box] Pod bay could seriously use plastic flaps

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4195]
~~Two-fold issue:
A) Spacepod fabrication used to need plasteel, but was changed to not need it. The stack of plasteel in the pod bay remains, and if it doesn't go unused the whole shift, it's snagged by Robotics. 
If you want to actually build a spacepod, though, you'll find that it requires about 8-12 sheets of glass, which is not available at podbay and not really readily available to civilians. So it ends up with arrivals windows being welded down into sheets.~~

B) Box uses a system of 2-wide airlocks for pod launching. This causes a few problems: Number one, you can only reach the "cycle to exterior" button from inside, which means you'd need someone ELSE to start the cycle for you. Number two, even with two large vent pumps, the depressurization cycle needed for the outer airlocks to open takes FOREVER. Both of these compounded end up in just "FORCE EXTERIOR DOOR" and since you can only do that from inside it ends up in the podbay being depressurized to launch the pod, 100% of the time. Come think of it I don't even think it's possible to dock with a pod while the exterior doors are open, since you can't reach the controls.
Meta solved both of these wonderfully well and in a wonderfully simple way.
![ss 2015-04-29 at 11 35 41](https://cloud.githubusercontent.com/assets/6526157/7405781/23ab939a-eece-11e4-9592-978d15eb594f.png)
Yes, it works. Yes, it's instant. Yes, we NEED this.

**Comment by Exxion** [comment]
There's a button in the pod bay airlock to cycle the doors and it doesn't take that long unless #4007 rears its ugly head (which it often does), but the flaps thing is much simpler.

**Comment by MercuryDoll** [comment]
spacepods can fly through plastic flaps? genius!

**Comment by FudgePucker** [comment]
So can exosuits.
Plastic flaps are the most magical and amazing thing in the game.

**Comment by 9600bauds** [comment]
Partially addressed by #4604
