### ISSUE TITLE
Power issues on the asteroid (outside, in the mining area)

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#4207]
![real_issue](https://cloud.githubusercontent.com/assets/7573912/7415651/a63933f8-ef5a-11e4-9a00-2bdbc227010b.png)

At some point in the round, all the machines on the asteroid suddenly realize that they have no power and shut themselves off, which creates issues such as #4188 (mass driver not working, mech recharge station not working, none of the light bulbs on the paths between the outposts working)

A fix is to create an APC on the asteroid, so this'll be a mapping issue, maybe add a small room between the outposts with an SMES and an APC, and maybe a PACMAN generator so miners can refuel it.

![fix](https://cloud.githubusercontent.com/assets/7573912/7415725/14a801ac-ef5b-11e4-9bab-d52277f887cc.png)

**Comment by Exxion** [comment]
Honestly, one APC really shouldn't be able to power the entire asteroid, but I've yet to see anyone come up with a reasonable way to prevent it from doing so without ruining absolutely everything.

**Comment by DeityLink** [comment]
from doing what? without ruining what?

**Comment by Exxion** [comment]
To prevent one APC from powering the entire asteroid. But never mind, that's a separate issue. I definitely remember seeing an APC on the asteroid intended to power the explored area. Maybe it's not charging up.

**Comment by Exxion** [comment]
Yeah, there's an APC in the explored mining area at (140, 68). It has a power cable attached to it, too. Not sure why it's failing mid-round.

**Comment by Probe1** [comment]
do xenoarchs need power and lights out on the roid for any particular reason?  i've never played it.  from the miners side you could remove all the lights and exterior apcs its just fluff.  the only purpose it serves is to let you drag around a weapon recharger and recharge your PKA on the spot through the magic of poorcoding

**Comment by DeityLink** [comment]
Damn you're right Exxion, it seems that APC is not charging for some reason, I'll investigate that.

**Comment by DeityLink** [comment]
Alright, so it seems to be a mapping issue indeed, for some reason that APC (X=140,Y=68,Z=5)'s terminal is not connected for the powernet, aka the wires on its tile. I VAREDIT'ed its powernet on the main server to test and now the APC is slowly charging up.

Will be fixed soonish. (once Kurf gets his own map changes done and merged)

**Comment by Intigracy** [comment]
Fixed at some point, please close.
