### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Virology Type 2 Drop Chance LOW AS F*

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4217]
So basically the Type 2 or Stage 2 virus mutation is reeeeally really hard to get one beneficial taking years to get one.

**Comment by Lancemaker** [comment]
Yeah i was trying it with 3 virus dishes. i got none. mutating, and creating new dishes. i ran out of virus food. now im on a round with 2 virus crates. and the same process mutating and creating new dishes. its not working. i can never get type 2 viruses.

**Comment by Intigracy** [comment]
this is fixu
