### ISSUE TITLE
Re-add Optical Material Scanners and rebalance them

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4219]
I was browsing the object pages on the wiki and came across these.  How cool would it be to have a T-ray scanner that works like mesons?  Remove the other aspects of it and replace it with being able to see pipes (disposal/atmos) and wires through walls and floors.  It would be really neat.  

You could replace the Mesons in the engi vend with them since they never get used.

![image](https://cloud.githubusercontent.com/assets/8550416/7428362/66a291f4-efbd-11e4-83e7-80d5ef37d9b3.png)

**Comment by AutismSpider** [comment]
Upgraded mesons scanners then.

Add  this for engiborg and mommis to then

**Comment by Probe1** [comment]
I was thinking they only show pipes and wires, not walls so it wouldn't be a straight up material > meson.

**Comment by BestName** [comment]
How do you re-add something that hasn't been removed?

**Comment by Probe1** [comment]
"Add optical material scanners to the realm of player accessible items"

**Comment by BestName** [comment]
That's better but still wrong as they are already player accessible with enough pomf coins or convincing praying.

**Comment by clusterfack** [comment]
It doesn't actually let you see pipes and disposals and wires through the floor. Those come from invisibility being modified when they are covered, these just adds the see_objs vision flag just like thermals gives see_mobs so you see objects through all walls.

**Comment by PJB3005** [comment]
Having these as upgraded T-rays would be cool
