### ISSUE TITLE
Tile painter UI is a laggy piece of garbage

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4223]
Seriously it takes like 1 second to switch screen inside of it.

**Comment by SkowronX** [comment]
Also takes a more than a few seconds to load the decals page.

**Comment by Probe1** [comment]
yep.  it's trash.

**Comment by PJB3005** [comment]
I think I found out why it is like this:

Every image used in that fucking UI is resend to the client every time you switch screen.

**Comment by d3athrow** [comment]
The only way to fix this would be to preload the raw images into the cache when using the painter for the first time which would cause some bloating eventually.

**Comment by ComicIronic** [comment]
What about something like the RPD UI?
That's pretty responsive.

**Comment by d3athrow** [comment]
seems they both do the same thing

**Comment by clusterfack** [comment]
I'd estimate the RPD UI would only be sending ~144 images if it sent every image in the UI. The tile painter has far more.

**Comment by PJB3005** [comment]
Well this is an old issue that's been fixed since.
