### ISSUE TITLE
Mousetrap assemblies don't work on grenades

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4227]
They work by themselves when dropped on the floor, but when attached to a grenade they won't trigger anymore.
Untested on bombs

**Comment by ComicIronic** [comment]
Simple fix: apply 00ca65e6d7d to grenades.
Bombs work, for the record.

**Comment by MercuryDoll** [comment]
mousetrap grenades have a hilarious mechanism. When you prime them, they never go off. BUT, if you try to defuse them with a screwdriver they trigger 100% of the time. So basically it's a boobytrapped dud.
