### ISSUE TITLE
(WEB REPORT BY: tidium REMOTE: 198.245.63.50:7777) Spelling error

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4228]
>Revision 32a7db78a474c93f6451c063fcc56a9488b5e3cc

>Description
https://a.pomf.se/xcwxql.png - see the image. Extra "s" on the end of pieces when adding a piece of cable to a cable coil.

>What you expected to happen
I expected pieces.

>What actually happened
I got piecess.

>Steps to reproduce if possible
Pick up a cable piece with a cable coil. Really, just a minor error.

**Comment by clusterfack** [comment]
lack of \s?
