### ISSUE TITLE
You can get rid of an SM crystal by drilling it with a mech.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4229]
inb4 IT'S A FEEEEAAAAATUUUUURE

**Comment by AutismSpider** [comment]
Keep it

But if you drill it the shard blows up on the spot

**Comment by clusterfack** [comment]
MY DRILL IS THE DRILL THAT WILL PIERCE THE SUPERMATTER

**Comment by Probe1** [comment]
>densest material imaginable, found at the core of super gas giants
 >you can just break it with a ripley
