### ISSUE TITLE
[Meta] Surgery privacy shutters too private

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4231]
they uh

![ss 2015-05-01 at 08 12 09](https://cloud.githubusercontent.com/assets/6526157/7438681/859fc58c-f03e-11e4-9de4-2e2bb728a4a5.png)

you uh

![ss 2015-05-01 at 08 12 34](https://cloud.githubusercontent.com/assets/6526157/7438683/8ccdec3a-f03e-11e4-88f8-b51c98521b2d.png)

you kind of can't reach the button to open them anymore

**Comment by ComicIronic** [comment]
>buttons under windows

**Comment by IratePirate** [comment]
It's a feature.

I'll get on all these fixes shortly.

**Comment by 9600bauds** [comment]
While you're at it, see about removing the Phalanximine bloodbags in Medbay and giving the front desk a sorely-needed paper bin.
