### ISSUE TITLE
CONSTRUCTION DATUMS

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4233]
Use them
It's much easier to just use them when first adding construction to an object than it is to convert it from whatever variation of snowflake construction code you used to construction datums.
Plus, it makes adding general construction-based features much easier.

If you'll excuse me, I'm just going to go stare at airlock construction code and weep.
(I know that probably predates construction datums and is thus excusable, but it's still a great example of why you should use them now)

**Comment by clusterfack** [comment]
Still no guide 2 them in our wiki, for shame

**Comment by ComicIronic** [comment]
https://github.com/d3athrow/vgstation13/wiki/Construction-Datums:-%3F%3F%3F-and-a-How-To

**Comment by Exxion** [comment]
Awesome!
Now I can actually start on my porting crusade

**Comment by Exxion** [comment]
Hm.
Is there a way to skip steps/have different keys move construction to dfferent steps in a reversible construction datum, sort of like how you can choose to either install glass in an airlock or skip that step?

**Comment by ComicIronic** [comment]
Not currently, no.

**Comment by Exxion** [comment]
Honestly there's not a very good reason to leave this issue open any longer
