### ISSUE TITLE
Give Mass Spectrometers the Ability to Take Blood

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4246]
I use advanced mass spectrometers frequently, and it's always a minor annoyance to have to get rid of the 10u of blood that's left over in the syringe. Blood samples can only be taken in 15u amounts, and the mass spectrometer can only hold 5u at a time. Which means to clean out your syringe you need to use the mass spec two more times, or inject it back into the patient, or into yourself, or a beaker and splash it on the floor, and it just irks me. I'd much rather mass spectrometers be able to take blood samples by themselves similar to those fancy diabetes monitors that flick the little pin out to take your blood. It removes a step which only serves as an annoyance and not even an obstacle (Who's going to have access to a mass spectrometer that's not also going to have access to a syringe?). You can even make it for advanced mass spectrometers only, that's the only kind anyone ever uses since the research for them isn't much farther than the research for regular mass spectrometers.

**Comment by FudgePucker** [comment]
Shit it shouldn't be that hard.
Maybe just forgo the blood requirement and just have it in flavor text and use the reagent scanner code, only add the exact number of units in a person.

**Comment by 9600bauds** [comment]
I can agree 100% with this. The extra syringe step also makes it so that you have to juggle around your health analyzer, the syringe, the mass-spectrometer, then put the mass-spectrometer in your hand to use it, then get rid of the 10u blood... all of that compared to the PDA reagent scanner's functionality, which is just clicking once.

**Comment by Probe1** [comment]
agreed, adv mass specs are pretty clunky.
