### ISSUE TITLE
Make the Flatpack Fabricator [Wrenchmove] 

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4249]
Problem:  You want to print more than one flatpack?  Yea enjoy walking all the way to where you want to go, coming all the way back, and repeating the process.  Every single time except for vending machines I'm going to just print the parts and build the machine myself.

Solution:  Make the Flatpack Fabricator wrenchable so it can be dragged without disassembly and losing the nanoprints/materials.  Like an atmos pipe dispenser, you take it to where you need it, print off flatpacks, and you're in business.  Suddenly that huge ass trip time is gone and flatpacks are a little more likely to be used!

**Comment by PJB3005** [comment]
issue being, if you move the flatpack fab you're gonna need to also move the mechanics console, because the flatpack fab needs that (for whatever stupid reason)

then again I don't think that's checked if you were to move it.

**Comment by Probe1** [comment]
code it 
code it 
code it 

I can't stop thinking about it now that I've realized how much it would improve things.  50% of the suck of flatpacks is you can only move one at a time and it's a huge hassle.  The other half being their exorbitant cost.  Which can be mitigated by making them easier to use.  Which can be done.. with [Wrenchmove]!

**Comment by FudgePucker** [comment]
Flatpacks are based upon a real thing.
They are flat so that you can pack them ontop of each other.
Gee wiz, I wonder how we would solve the issue of having to drag them one by one.

A better solution to having to move around an entire machine, would to just be able to stack the flatpacks into packs of stacks.

**Comment by clusterfack** [comment]
I don't really like the idea of moving around the fabricator. 

I like the idea of them being stackable or perhaps not dense so they can be carried around in crates like solar assemblies can be. The latter would also be quite easy to code.

**Comment by Probe1** [comment]
You're gonna have to give on something because flatpacks are useless unless you want vending machines or you don't have bio 5 research to print a board for a chem dispenser.  merge that idea and see where it takes us.  I'm happy with either direction.

**Comment by FudgePucker** [comment]
Bio 5 isn't the hardest level to get for the chemical dispenser.
Its 100 times easier than data and engineering research.
Ointment, health hud, MMI, Radio MMI, done.

**Comment by Probe1** [comment]
It's not difficulty, it's time.  It's more time efficient for a mechanic to grab a scan and print a chem dispenser rather than build a DAnalyzer and print those things.  

Like I said, right now the Flatpack Fab is only in the realm of 1. Round time convenience 2. Vending machines that come fully stocked.  Why else would I burn 2-3 times the cost on something that produces a unwieldy flatpack that I can only carry one of?  Damn.

**Comment by ComicIronic** [comment]
I'm working on flatpack stacking to hopefully make moving them around a lot easier.

**Comment by Probe1** [comment]
I'll take it.  It's not the upgrade I want but I'll take it.  It doesn't remove the travel time cost that helps make flatpacks the poorer relations.  It will reduce the travel time by whatever the max stack is but I'm still going to lose time waiting for the maximum/total of flatpacks I want to take to print first then haul them all at once.  

What I really want is to not have to haul multiples at all and just be able to print them on the scene after going through the trouble of scanning stuff. Especially when I can just load up gadget bags and build machines with better parts, less materials and faster build time.  

But I'll take it.

**Comment by FudgePucker** [comment]
>travel time cost

Guys. Best fucking idea ever.
Forklift.
You can joust with the janiter on his janicart with his mop using the prongs on your forklift.

Also carry flatpacks I guess.
