### ISSUE TITLE
Make Morgue a bit more secure

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4252]
As it is right now, the Morgue is just one maint door away from looting everything off of everyone, and free blood/DNA/whatever. And I mean, that's a legitimate strategy, yeah.
But currently it's so easy to break in and loot that even assistants often do it, and walk away with Sec/Engineering IDs and whatnot.
The Morgue holders really oughta have Medical access requirement, but be hackable/emaggable so actual antags can still have their way with them.

**Comment by MercuryDoll** [comment]
that's a problem with Medbay not securing the IDs. I always put unclonable people's stuff in a backpack and store their IDs and PDAs in a separate pack to give them to HoPcurity for wiping. How about having a safe in the morgue for that kinda stuff though?

**Comment by PJB3005** [comment]
yeah, this really is just people being dumb and leaving high risk shit unsecured, not a mapping issue

**Comment by 9600bauds** [comment]
I'd appreciate a safe for this purpose, at least, there's a shitton of things on dead bodies and I'm generally too busy to even search the bodies, much less turn everything they had of value. Stripping corpses also generates a lot of clutter that's very annoying to move, since not even all of it fits in a backpack.
