### ISSUE TITLE
Z-Wiggling

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4259]
![2015-05-02_01-46-31](https://cloud.githubusercontent.com/assets/9827785/7443778/3106603a-f133-11e4-896c-3fb49e285137.gif)

**Comment by 9600bauds** [comment]
he's just very excited

**Comment by FudgePucker** [comment]
This image is pretty much /vg/station in a nutshell.
Dionaea in a fire suit and fire helmet on the janicart.
Some guy vibrating up and down like a spaz.
And there's an atmospheric alarm that will be going forever because people can't keep from opening firelocks.

**Comment by PJB3005** [comment]
This is basically a BYON issue, another example of Z fighting like this is stacks of items: moving around sometimes causes them to appear in a different order

**Comment by MercuryDoll** [comment]
That it affects playermobs is new though. i've only noticed this happening this weekend. Not that it's gamebreaking but it can make observing weird, as it affects ghosts hovering over players when following.

**Comment by ConkerDev** [comment]
Does this still happen? BYOND's rendering has changed since.

**Comment by PJB3005** [comment]
Definetly still does.
