### ISSUE TITLE
Item handed to laying down player deleted?

### ISSUE THREAD

**Issue by Dr-Explosion** [d3athrow/vgstation13#4267]
I was handed an item (pAI to be exact) while laying on the ground. I accepted it, but instead of going to my hand, or falling onto the floor, it seems to have completely deleted. Not sure if it can be replicated as I haven't tried yet.

**Comment by Dr-Explosion** [comment]
I wasn't able to replicate it with a different item, but someone can look into it if they'd like. Thanks!

**Comment by clusterfack** [comment]
Probably fixed by comic ages ago
