### ISSUE TITLE
Ghosts can step on broken glass

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#4270]
2SPOOKY

**Comment by Probe1** [comment]
so add "you hear a faint crunching sound" to living players within 1 tile of the glass when ghosts walk over it.

**Comment by clusterfack** [comment]
forcemove why

**Comment by CptWad** [comment]
oh god it lags so much please fix

**Comment by clusterfack** [comment]
lags?

**Comment by ComicIronic** [comment]
Caused by no isliving() check in the code.

**Comment by Exxion** [comment]
Wasn't this fixed weeks ago?
I remember trying to do it and failing quite a while ago

**Comment by clusterfack** [comment]
Forgot to close the issue with my PR I guess
