### ISSUE TITLE
(WEB REPORT BY: jewishneocon REMOTE: 198.245.63.50:7777) BALANCE ISSUE WITH DEFFICIENCY

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4271]
there are 5 banana cream pies in theater
you can get pregnant 
its op nerf it

**Comment by clusterfack** [comment]
Oh yeah? I couldn't get pregnant so I guess I'm unable to reproduce

**Comment by Probe1** [comment]
for fucks sake I can't stop laughing

**Comment by NigglyWiggly** [comment]
God dammit why am I laughing
