### ISSUE TITLE
Well, it's not exactly wrong...

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4272]
![image](https://cloud.githubusercontent.com/assets/9827785/7448900/e5727970-f1f4-11e4-9803-6bbc68ecf7d4.png)

**Comment by Iamgoofball** [comment]
It is menacing with spikes of blood.

**Comment by clusterfack** [comment]
That's a blood!

**Comment by ComicIronic** [comment]
Should be PLURAL gender.

**Comment by Exxion** [comment]
It might be worth noting that this was the blood left by the "write in blood" verb

**Comment by gbasood** [comment]
Couldn't reproduce this by gibbing monkeys over the writing.

Can someone else think of a way to reproduce this and let me know what happens when they try it?

**Comment by Exxion** [comment]
At the time, all I had to do was write it. There was no other blood involved, other than that used to write it. If it didn't happen, it was probably fixed. Someone can reopen it if it happens again.
