### ISSUE TITLE
Fireaxe cabinet is bugged

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#4278]
When building a fire axe cabinet with Plasteel it comes with a axe inside.

tank storage unit works fine no tanks in it

**Comment by PJB3005** [comment]
IT'S A FEEEAAAATUUUURE

**Comment by clusterfack** [comment]
OP

**Comment by 9600bauds** [comment]
Speaking of the fireaxe cabinet, can you fix the glass after breaking it?

**Comment by AutismSpider** [comment]
Just try that and you can't fix it

just gos invisible

**Comment by Exxion** [comment]
This shouldn't be that hard a fix
Annoying, but not hard
Make standard fireaxe cabinets start empty and replace the roundstart ones with a subtype that comes with an axe
Or make a subtype that deletes the fireaxe in its New() and have plasteel build those
The latter would be slightly easier, but also worse

**Comment by clusterfack** [comment]
They should be mounted frames as well building them on the ground is stupid.

**Comment by Exxion** [comment]
I like how still nobody has been assed to fix this

**Comment by clusterfack** [comment]
Doesn't fix the issue of them just being built on the ground, why would you build a cabinet on the ground. HOW could you build a cabinet on the ground.

**Comment by Exxion** [comment]
Yeah, that's stupid
But I don't think it would be much harder to do that than just fix this

**Comment by clusterfack** [comment]
Just needs a sprite

**Comment by Exxion** [comment]
I'm about to work on it if Git ever finishes the pull
I'll probably be a lazy fuck and just... scale down the sprite for the open cabinet or something.

**Comment by Exxion** [comment]
Oh look there's already a fireaxecabinet/empty
This is even easier than I had expected

**Comment by AutismSpider** [comment]
Take it out or fix it for real.

You can flood the station with axes cheap as a miner.

**Comment by Exxion** [comment]
Yes
That's what my PR does
It fixes it for real
Did you read it?
