### ISSUE TITLE
(WEB REPORT BY: doctorscott REMOTE: 198.245.63.50:7777) Biogenerator won't dispense nutrients

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4279]
>Revision (Should be above if you're viewing this from ingame!)
8be957dd8d851bb6fd45b6b37c13d37a22acc463 
>General description of the issue
Biogenerator won't dispense nutrients except for BeezEez. It will use biomass, but won't dispense the nutrients.

>What you expected to happen

biogenerator dispensing nutrient bottles as usual

>What actually happened

No nutrient bottles dispensed, biomass spent.

>Steps to reproduce if possible

No idea. It always used to work as expected.

**Comment by AutismSpider** [comment]
the nutrients are dispense in the beaker now

Same with milk etc

**Comment by 9600bauds** [comment]
Yep, BeezEz is the only exception since it's a snowflakey item that isn't even actually a reagent.
This means you can print 100 units of robust harvest and have it all in a single beaker rather than in 10 bottles.
