### ISSUE TITLE
Golem "Suits" no longer pressure proof

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4280]
The suits that Golems have no longer protect them from the space and its lack of pressure, although oddly enough it protects them from the cold.

**Comment by FudgePucker** [comment]
Did you have an O2 tank and internals on?
You still need to breathe.

**Comment by Ephx1** [comment]
Yes, I had them on. Only pressure damage was applied, not oxygen damage.

**Comment by Ephx1** [comment]
This still holds true, Golem suits are no longer space suits. Is this a feature or not, who knows?

**Comment by Ephx1** [comment]
Closed because there's a better written issue.
