### ISSUE TITLE
Gas Datums are slow

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#4287]
Oh god please save us I never asked for this

![](http://puu.sh/hBLKa/750f408939.png)

**Comment by clusterfack** [comment]
Note pretty much all of this is coming directly from update values, if we continue with gas datums we need to totally rethink the way we handle combining the gases and updating them.

**Comment by ComicIronic** [comment]
It might be that the code which updates oxidiser and fuel numbers is a lot slower than I anticipated, rather than speeding anything up. I'll make a PR to remove it and see how much that affects performance.

**Comment by d3athrow** [comment]
1.5~e-5 isn't that bad

**Comment by clusterfack** [comment]
It used to be 2.39e-6. Unfortunately its bringing what used to be about 20-30% per tick cpu usage to 50-60+%

**Comment by clusterfack** [comment]
I think from this point our goal should be to phase out update_values as a proc entirely. And making total_moles and pressure from unstable values (not guaranteed to be consistent with gases) into stable values.

Update_values may have been useful when trace gases existed and the amount of overall gases was small, but doing 5+ calculations while also calling those other procs to recalculate it (which occurs more often than not), will end up being more expensive than simply combining it when merging gases or adjusting gases.

**Comment by d3athrow** [comment]
Could just have update_values only run on xth tick unless its flagged as important to defer uninteresting updates.

**Comment by clusterfack** [comment]
>Theres not much to do to optimize it with having a modular system because you're going to have to loop through a list of something to get your shit done

That's precisely why I'm saying we should keep total_moles as a stable variable instead of being forced up to loop through a list of all gas_ids, get the moles, and add them every time something needs updating.

Deferring it, wouldn't help. Because these calculations NEED to be done at some point, this isn't a problem of scope. And no matter how much you smooth them out the server isn't going to be able to support update values being 10 times more costly.


Think of it from this perspective, say you have 10 gases, you can either have pressure and total moles calculated during the merge which is probably worth about 3 operations compared to the 10 you did combining the two gas datums.

Now say instead you want to use update_values, now you are also going to loop through those 10 gases and do 10 more operations to get the total moles and add them together, its bloat that's not feasible.

**Comment by clusterfack** [comment]
So to sum up my plan to optimize gas datums,
1. Remove update_values
2. Have total_moles added/subtracted during merge/remove/etc instead of update_values
3. Have heat_capacity be var instead of being proc-ed, for the exact same reason as update_values is, it loops through the gases to create the heat_capacity
4. Have pressure calculated just after finishing using total moles and the ideal gas law

**Comment by ComicIronic** [comment]
It would be doable, but there would have to be a proc for setting volume. adjust_gas could also not be removed.

**Comment by clusterfack** [comment]
Well volume is manually set from the outside as it is currently already, right?

**Comment by 9600bauds** [comment]
Weren't gas datums slain anyways

**Comment by clusterfack** [comment]
Dead as fuck
