### ISSUE TITLE
Slow framerate on personal testing server

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4288]
This is more of a question than an issue, as it doesn't really matter (at least to me), but I have been curious about this for a while.
For some reason, when I run and connect to a testing server on my computer, the framerate is about half what it is when I connect to an online server.
However, Dream Daemon and Dream Seeker *combined* use about 2-3% of my CPU (when shit isn't going down, at least), not much RAM (forgot to check exactly how much, but a small enough amount that I didn't notice it on the bar because Google Chrome dwarfs it completely), and basically 0% of my GPU.
So if hardware isn't limiting the framerate, what is?

**Comment by clusterfack** [comment]
Thats because our code's standard ticklag is twice the ticklag of the prime server.

Debug verbs -> set ticklag -> .55

The standard is .9

**Comment by Exxion** [comment]
Ah, I see
Time to be a fucking idiot and try .01
