### ISSUE TITLE
Tick compensation at extremely low ticklag is fucking terrible

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4289]
I can think of no reasonable case in which this would actually pose a problem, but I guess its root cause might cause other issues.
At a ticklag of 0.01, enabling tick compensation makes it so that the game refuses to accept any inputs for a few seconds after accepting an input. The game works surprisingly well at that ticklag without tick compensation. (That isn't saying much, as I expected it to instantly crash.)
I'm... not actually sure what tick compensation is, but it may have to be looked at.

EDIT: It might actually just be movement inputs.

**Comment by clusterfack** [comment]
Yeah, that's why I always turn tick compensation off at extremely low ticklags, I believe its a rounding issue or something to that effect.

**Comment by clusterfack** [comment]
Well here is the relevant code

http://puu.sh/hBOqk/855e95a473.png

**Comment by d3athrow** [comment]
Well you wouldn't ever run the game at 0.01 ticklag because that's 1000fps, and ss13 barely keeps up usually at the 20fps we run at

**Comment by Exxion** [comment]
That would be the reason for the first half of the first sentence of the initial post.
But if the second half is false, go ahead and close the issue if you want.

**Comment by clusterfack** [comment]
Before gas datums I could change the ticklag to .3 or .25 without any problem at all on the live server

**Comment by clusterfack** [comment]
The problem is obviously that it takes the reciprocal of the ticklag and subtracts by a constant number only.
