### ISSUE TITLE
WHO FUCKED UP

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4290]
All air/N2/gas of any kind tanks on the station are now empty.
This includes ones given to Vox, so they die.
It also includes adminspawned ones, as I adminhelped it and another empty tank appeared at my feet.

**Comment by Ephx1** [comment]
The un-gassing of the vox begins, truly these are the good times

**Comment by RogerWilcoBeep** [comment]
As hilarious as this sounds, it seems like it should be fixed soon-ish
