### ISSUE TITLE
Booze Dispenser doesn't construct correctly.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4291]
In my PR  #4276 I added circuit boards for the other dispensers.
Brewer, worked perfectly.
Soda Dispenser, worked perfectly.
Booze Dispenser, deconstructed perfectly, constructed perfectly... up until the last step.
When the machine frame says it needs nothing else, and you use a screwdriver on it, the screwdriver sound plays, but nothing else happens.
You can spam the screwdriver all you want but nothing happens.

I have no idea why it fucked up. But it did.
I looked back over the code, if the booze dispenser is broken, then the soda dispenser and the brewer should be too, but they aren't.

Oh god please help me I have no idea even anymore.

**Comment by clusterfack** [comment]
Did you use construction datums? I believe your code is runtiming with list index out of bounds

**Comment by FudgePucker** [comment]
>build_path = " /obj/machinery/chem_dispenser/booze_dispenser"

That space before the first / is the only difference between the other dispensers.
I am guessing that because everything else works, what it is doing is that after putting in the circuit board and all the parts, when I screwdriver it goes,
>playsound(get_turf(src), 'sound/items/Screwdriver.ogg', 50, 1)
Okay everything is going great, all parts are in, we are set to go make the...
var/obj/machinery/new_machine = new src.circuit.build_path(src.loc)
Wait a fucking second, there is no " /obj/machinery/chem_dispenser/booze_dispenser". AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

That's all I can pretty much guess what went wrong with it.

**Comment by Exxion** [comment]
So try taking out the space
Though I'll give you a hint: What you just said is almost definitely it.

**Comment by NigglyWiggly** [comment]
If I make supply crates with these dispensers in them, this change won't make require me to go back and rename them or anything, right?

**Comment by FudgePucker** [comment]
It shouldn't.
Even better, you can have supply crates just come with circuit boards instead of the machines to require some assembly, also prevents you from  deconstructing one and reconstructing to get a chem dispenser.

**Comment by FudgePucker** [comment]
Also, we (I am planing on attempting to make a cargo crate later maybe tonight or tomorow) might have to change the research levels for the non chem dispenser boards.
The research levels are too high for being something that can be ordered from cargo, there are only three chem dispensers at round start because they are very powerful.
Although this isn't that big of a deal because the RD has access to four device analisers and tcom parts that can get you over the hump.

The most important thing is that cargo can't just order one of the machines and deconstruct it and reconstruct it to get a full chem dispenser. Cargonia might be annoying now, imagine if they could mass produce polyacid smoke gernades.

I am thinking a brewer board, a kettle, and 10 mugs. Does that seem like a good crate?

**Comment by NigglyWiggly** [comment]
That's actually the exact thing setup I had for the crate, also threw together an 'advanced bartending' one that comes with the booze and soda dispenser boards, 10 drinking glasses, and a shaker, might make a PR here in a couple minutes if they all work out alright

**Comment by FudgePucker** [comment]
Alright I guess I can close this issue instead of waiting on someone with access to do it.
This issue was fixed with my PR #4276.
I have tested it and the booze dispenser does construct correctly now.
Closing issue. First bug busted by me, even though I made the bug, and reported it.
