### ISSUE TITLE
Autocalled ERT is useless without admin intervention

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#4292]
1. The blast door to the main area (suits and equipment for the most part) is impossible to open by players.
2. The shuttle can't be sent, shit still doesn't work.
3. An admin has to be present to make sure everything goes without a hitch, which is completely counter intuitive to the intended purpose.

Whoever added in auto ERT, ya done goofed. Pls fix.

**Comment by clusterfack** [comment]
The second is a code issue that's pretty easy to fix, the first is a map issue. Deity plans to fix that with a centcomm revamp.

**Comment by Probe1** [comment]
What situation is autocalled ERT even applicable?
