### ISSUE TITLE
Circuit imprinters don't show how much glass they contain

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4296]
Materials menu of UI is always empty, Materials Amount on primary screen never displays anything except 0.

![2](https://cloud.githubusercontent.com/assets/8550416/7472672/ec592a4a-f302-11e4-962c-5f2e6aa95313.gif)

**Comment by PJB3005** [comment]
The protolathe doesn't either

**Comment by CptWad** [comment]
Nano UI for protolathe and Circut imprinters when?

**Comment by PJB3005** [comment]
That'll take ages for a sane human being to do

**Comment by CptWad** [comment]
Too bad theres no nexis left for that.
We need a new madman
