### ISSUE TITLE
(WEB REPORT BY: redun REMOTE: 198.245.63.50:7777) Jukeboxes don't work on the DJ station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4298]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The jukebox on the DJ station didn't work, even after being replaced with a super jukebox.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by FudgePucker** [comment]
The jukebox on the DJ station should be connected using the multitools buffer to the radio transmitter in the back room, causing the jukebox to not output sound, the sound in the DJ station comes from the soundsystem on the table.

Did you make sure the radio transmitter and the sound system were on and to the right frenq?

**Comment by CptWad** [comment]
Whats weird is that the jukebox on DJ when wrenched and moved elsewhere makes no noise but plays perfectly in the dj station. Meaning you could move the juke to the captains office, never hear what its playing but go to DJ and still hear it.
If what fudge said is true how it works thats a bit of a strange oversight.

**Comment by FudgePucker** [comment]
@CptWad
It is what I said.
The sound isn't coming from the jukebox, its coming from the sound system linked to the radio transmitter that the jukebox is linked to.

Think about it like this, the output of the jukebox isn't the jukebox when multitooled, the output of the jukebox on the DJ station goes into the input of the radio transmitter, the output of the radio transmitter is the sound systems.

It's not an oversight, its working as intended.
Also you should just loot the boom box from the captians room or the CEs room.
Best item in the game.

**Comment by clusterfack** [comment]
Fixed
