### ISSUE TITLE
(WEB REPORT BY: manfreed REMOTE: 198.245.63.50:7777) unable to use emergency oxigen tank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4300]
>Revision (Should be above if you're viewing this from ingame!)
_nothing_

>General description of the issue
Breatmask is equipped. Cant switch on internals. "You don't have an oxygen tank." have one right in my hand. Take out another one. Still doesn't work.

>What you expected to happen
To be able to switch on internals.

>What actually happened
>You don't have an oxygen tank.

>Steps to reproduce if possible
equip breath mask and hold emergency oxigen tank. Try to turn on internals.
Might be some recent change. It used to work for me in the past.

**Comment by CptWad** [comment]
Actually the tanks start empty at the start of the round now.
If tank is empty there cant be a tank attached to the mask
Also >oxigen
