### ISSUE TITLE
Botanist access is broken on the test serb

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#4301]
The HoP computer claims that hydroponics access is availible to the botanist, yet the doors won't open, not a single door to botany. Morgue, however opens just fine. Kitchen and bar access are missing too.
![image](https://cloud.githubusercontent.com/assets/10002997/7477012/de59c844-f359-11e4-919b-cde3bff2a33d.png)

**Comment by DrLeprikon** [comment]
That was so quick, thank you

**Comment by ComicIronic** [comment]
WHAT TEST SERB

**Comment by DrLeprikon** [comment]
Too soon
