### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Nitrogen tanks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4303]
a847b58facc9deaa3810b43dc6e1c9e6e9f59cde 

All nitrogen tanks (or tanks ive seen) have 0 nitrogen in said tanks. Even ones spawned by admins have 0

**Comment by PJB3005** [comment]
Dupe of #4290,
Which was fixed by #4293

**Comment by ComicIronic** [comment]
Is this definitely fixed?

**Comment by clusterfack** [comment]
Apparently not?

**Comment by CptWad** [comment]
Dunno related to #4300
