### ISSUE TITLE
(WEB REPORT BY: exxion REMOTE: 198.245.63.50:7777) Who needs lanterns?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4310]
>Revision (Should be above if you're viewing this from ingame!)

beda8e4e49346c29bc6ff00c2cc32219a949d561
>General description of the issue

The PDA's flashlight can be stacked infinitely by taking off your jumpsuit while it is on.
>What you expected to happen

Body to stop glowing, dropped PDA to glow
>What actually happened

Dropped PDA stopped glowing, body glowed, body glowed brighter when PDA was picked up
>Steps to reproduce if possible

1. Turn on PDA flashlight
2. Put PDA in ID slot (belt or pocket would probably also work)
3. Take jumpsuit off
4. Put jumpsuit on
5. Pick up PDA and notice your now brighter light
6. Rinse and repeat for arbitrary brightness
7 (Optional). Cry if you attempt stealth because you cannot turn off the glow

**Comment by CptWad** [comment]
![sun](https://cloud.githubusercontent.com/assets/3959840/7484327/10e712f8-f33c-11e4-80bf-0539e6839a27.jpg)

**Comment by d3athrow** [comment]
fookin prawns
