### ISSUE TITLE
People With One Hand Can't Wear Gloves

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4311]
There's no reason they shouldn't be able to put just one glove on.

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.

**Comment by gbasood** [comment]
is this
even a thing still

**Comment by Shadowmech88** [comment]
I haven't seen any PRs changing it since the issue was made.
It'd be easy enough to test, anyway.

**Comment by ghost** [comment]
You'd have to split the glove sprites for every single gloves if you "fixed" this by the way

**Comment by Shadowmech88** [comment]
Right, Byond doesn't have masking or any way to "remove" a portion of an existing sprite, does it?

I guess give this the [Sprites] tag, then.

**Comment by ComicIronic** [comment]
We could do sprite editing on the fly, yeah, it just risks breaking a lot harder than one-handed glove sprites do. Maybe we should do the same for shoes.
