### ISSUE TITLE
Feature Request: Allow Surgeons to Graft Items Onto Arm Stumps

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4312]
Functionally, it'd be like that hand was holding the item, except you're incapable of dropping it or it being disarmed or taken from you in any way, save severing it. So if your opponent doesn't have a bladed weapon, they're unable to take it from you.
Plus it'd be awesome to attach a gun to your arm and become a cyborg in a sense that actually means something.

**Comment by Ephx1** [comment]
I'll get behind this as long as I can remove the clown's hands and replace them with bikehorns.

**Comment by CptWad** [comment]
REPLACE PEOPLES ARMS WITH SWOOOORDS. 
Just like Galvarino.

**Comment by NigglyWiggly** [comment]
Replace your hand with a revolver
You won't be able to fire it unless you use your other hand, but I guess it might look neat

**Comment by Shadowmech88** [comment]
I was thinking guns/devices and the like would be usable as if you were holding them in that hand, so you wouldn't need the other hand to fire the revolver. RP explanation could be that it's wired to your nerves or something.

**Comment by TermedClepe** [comment]
How about replacing entire arms with mech attachments?

**Comment by MercuryDoll** [comment]
>mech limbs usable prosthetics
>mech armor convertable for humans to wear
>mech attachment can be attached to the back

pls make it happen, i want to become a phazon powered supersoldier
![happyjensen](http://i.imgur.com/jivPjua.png)

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.

**Comment by Megamaw** [comment]
okay this needs to be a thing. people would actually do surgery if this was added.

**Comment by 9600bauds** [comment]
People don't do surgery now?
