### ISSUE TITLE
(WEB REPORT BY: 1pirateguy REMOTE: 198.245.63.50:7777) light toggle on gold atmos helmet not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4313]
>Revision (Should be above if you're viewing this from ingame!)
beda8e4e49346c29bc6ff00c2cc32219a949d561 

>General description of the issue
can't turn lights on golden atmos helmet on or off

>What you expected to happen
the lights to turn on

>What actually happened
nothing

>Steps to reproduce if possible
turn it gold, put it on, try to turn the lights on

**Comment by CptWad** [comment]
I don't think ever it had one. I thought it was a side effect of being a bling motherfucker.

**Comment by ComicIronic** [comment]
Not a bug: this is intended behaviour, since the gold suit has higher resistance.
