### ISSUE TITLE
Oxygen does not ignite

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4316]
![fireballs](https://cloud.githubusercontent.com/assets/3959840/7486803/9a8ffc5e-f35f-11e4-8c88-97de7d58caf1.png)
So wile dicking around on the test serb I decided to figure out how to do antag pure oxygen fires and found out that oxygen does not ignite.
This room had some n2 and I thought that maybe it was problematic. Turns out pure o2 also does not ignite after further testing
Tested with welders, sparks and lighters.

**Comment by clusterfack** [comment]
Why'd you think pure oxygen ignites? It real life it does make fires expand extremely quickly but it doesn't ignite without fuel.

**Comment by CptWad** [comment]
Fuck me that would be right, Never mind
