### ISSUE TITLE
Obfuscating map coordinates

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4319]
Currently all coordinates on each z level are always the same, this leads to telescience spreadsheets or coordinate hunting loot with GPS and a jetpack.

The player can see coordinates ingame using various tools like the GPS or crew monitor.

What I propose is that there would be a random offset generated each round for each z level that only visually affects the coordinates player sees / inputs, that is internally as far as game is concerned all coordinates would remain as they are now.

However displaying coordinates or inputing them ingame from the players perspective would always be with the added offset. Same concept could be applied to z level numbers.

This would mean that at the very least a player would have to first explore a z level to know where he is, find a point of reference for his spreadsheet and figure out the rest.

**Comment by clusterfack** [comment]
Done

**Comment by TermedClepe** [comment]
Holy shit really?

Noice.

**Comment by TermedClepe** [comment]
Can you add randomizing the displayed z level number too?

The entire idea was to force people to explore if they want to know what's where, does it prevent figuring out the specific drift using telescience without leaving the station?

Like some bright anon said, telesciencing a gps at coordinates and seeing different coordinates broadcasted by the gps, difference being the z level shift.

**Comment by FudgePucker** [comment]
Randomized zlevels is what goon does and it could work here.
They also only have 2 accessible zlevels (And another only for telescience. BOY IS THAT FUN TIMES.)

**Comment by clusterfack** [comment]
Termed, I couldn't because the crew monitoring console already displays every zlevel map and its zlevel value.

**Comment by FudgePucker** [comment]
Oh yea that's right the crew monitor does do that.
Never mind.

**Comment by clusterfack** [comment]
It mostly just prevents stealing everything from every zlevel at roundstart
