### ISSUE TITLE
(WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) Golems show up as unknown

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4321]
>Revision 
e189fd67fdca1e979447ca69d6197141e2e7078e

>General description of the issue
Title

>What you expected to happen
TO be able to see their face

>What actually happened
Face covered up by the golem mask

>Steps to reproduce if possible
Make golem
Be dissapointed because they're 'unknown'

**Comment by Exxion** [comment]
Give unremovable golem ID
There is no way this could cause problems
