### ISSUE TITLE
Siphoning an area will set every gas to be scrubbed

### ISSUE THREAD

**Issue by wwjnc** [d3athrow/vgstation13#4323]
If you siphon an area, the scrub preferences will be set to scrub everything, with the obvious results when you cancel the siphoning.

**Comment by clusterfack** [comment]
Gas datums @ComicIronic

**Comment by ComicIronic** [comment]
I actually can't see why this would be the case.

**Comment by wwjnc** [comment]
I've noticed it only happens sometimes. Also when pressing the 'turn off siphoning' button sometimes the area gets stuck with panic mode.
