### ISSUE TITLE
(WEB REPORT BY: fireice2k8 REMOTE: 198.245.63.50:7777) Open Airlocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4324]
Revision: e189fd67fdca1e979447ca69d6197141e2e7078e

just came across this while wandering maint, http://i.imgur.com/GwLrpjd.png
atmospherics isn't pushing air through any of these doors, and i can freely step in and out of them - it's also possible for me to step into space, start taking damage and become freezing, and then step back onto the door's tile and start breathing/warming up again
opening an oxygen canister in this room worked as if it were an ordinary, sealed room.
clicking on the doors themselves makes them flash their 'no-access' state (because i don't have access) but funnily enough, they flash the -closed- state for that.
nothing i've done has changed the doors so far.

> What you expected to happen
> maintenance vented
> 
> What actually happened
> magic
> 
> Steps to reproduce if possible
> i have no fucking clue how this happened - it was like this when i got there.

**Comment by PJB3005** [comment]
This is intentional, because we don't have cycling airlocks.

**Comment by ComicIronic** [comment]
But it's moronic and I hate it.

And we do have cycling airlocks.

**Comment by PJB3005** [comment]
Well, we do, but they're only used in Tcomms, the engineering burn chamber, the pod bay and xenoarch

**Comment by Ephx1** [comment]
Yeah, we have cycling airlocks but people would just charge through regardless so they were removed.

**Comment by PJB3005** [comment]
IMO doing shit like that warrants the same kind of reaction from other players/admins as if they just breached escape.

**Comment by Exxion** [comment]
It doesn't help that the cycling airlocks break like half the time
*cough*#4007*cough*

**Comment by Probe1** [comment]
REMOVE

ALL

VAREDITED

BULLSHIT

**Comment by Probe1** [comment]
Basically at this point there's more exterior airlocks that don't let air pass through than not.

**Comment by wwjnc** [comment]
Busta ZAS should slip and fling whoever doesn't close the airlock behind him to the next z-level.

**Comment by PJB3005** [comment]
enough velocity and a big enough stun to ACTUALLY shoot them to abother Z-level would be amazing
