### ISSUE TITLE
Absorbed victims have unusable blood

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#4325]
A victim that's been drained by a changeling still has blood according to the medical analyzer, but you can't actually drain it via IV.

![image](http://i.imgur.com/OE4ezrg.png)

Also notable the the IV drip and the empty empty bloodpack

**Comment by clusterfack** [comment]
Considering it's a 'husk' and has had its 'fluids drained' this is probably intentional right? Except for the part where blood shows up I mean.

**Comment by MercuryDoll** [comment]
That's what i assumed. Ling-drained husks shouldn't have blood left in them.
