### ISSUE TITLE
Replace magic air blocking airlocks with cycling airlocks.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4327]
Also port shuttle docking & docking ports from bay to go along with that.

**Comment by Exxion** [comment]
Should probably make cycling airlocks fail to actually cycle less often first

**Comment by Probe1** [comment]
Basically at this point there's more exterior airlocks that don't let air pass through than not. Someone needs to go through and un"fix" all of them.   I think it's a healthy and correct choice to remove the varediting shit that plagues box and other maps.  

Don't coddle players.  Space is supposed to be horrible and dangerous.

**Comment by Exxion** [comment]
Something that works surprisingly well is just having the timing wire start cut
Which... is still varediting, but less egregious

**Comment by FudgePucker** [comment]
The problem with cycling air locks is that they are a pain in the ass.
Miner leaving the base, all he has to do is charge out of there.
Xenoarch leaving his base, wait for it to cycle to interior, walk in, wait for it to cycle to exterior, wait, wait, wait, wait, wait, wait, walk out, realise you forgot something, walk in, wait for it to cycle to interior.

Really fucking tedius for things that should just take a few seconds that you would have to do over and over again.

**Comment by IratePirate** [comment]
>Something that works surprisingly well is just having the timing wires of external airlocks start cut
Which... is still varediting, but less egregious

That's actually a pretty great idea. I think i'll do this.
