### ISSUE TITLE
Languages Stuff

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#4330]
Not sure if this happens with cyborgs or the Ai for that matter

Turn back to normal after the admin added languages for me
![dear god why](https://cloud.githubusercontent.com/assets/10268342/7509394/a4dc5652-f455-11e4-885d-2143b76059d4.PNG)

**Comment by d3athrow** [comment]
This is a pretty bad report, make it a bit more specific next time please.

**Comment by ComicIronic** [comment]
MoMMIs don't start with languages, looks like.
They need at least Sol Common to be orderable.
