### ISSUE TITLE
Allow admins to change mob clothing sprites via VV

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#4331]
Muh bus.

**Comment by SkowronX** [comment]
Please

**Comment by DrCelt** [comment]
+1000

**Comment by Intigracy** [comment]
Best way to do this would be to add an update_icon verb to the dropdown menu on vv, different from regenerate icons in that it just updates the icon without overwriting back to the default icon var.

This would allow you to edit the corresponding overlay's icon variable to a dmi with icon_states named after the clothing you're editing, then dropdown > update_icon. Regenerate icons sadly overwrites any changes back to the default for the item.

**Comment by Intigracy** [comment]
Will fix this and #5153 sometime this week.

**Comment by NigglyWiggly** [comment]
You actually can change em if the sprites are already in the right clothing .dmi and shit

**Comment by Intigracy** [comment]
That's because regenerate_icons() doesn't reset the icon_state value on overlays, just the icon variable.

**Comment by Intigracy** [comment]
Alright my friends, you will be happy to know that you can ALREADY change the overlays on clothing, as long as the person isn't a nonhuman who has a seperate sprite for that overlay (aka vox pox, also can't do monkeys currently.)

How to:
Go to the ---item--- you want to edit the overlay for
make sure you have the icon_states in your icon file named after the ones for the item to save yourself time varediting
on the item, edit the "override_icon" variable to your icon
tell them to take the item off and put it back on again, or just use the dropdown menu to regenerate icons
