### ISSUE TITLE
(WEB REPORT BY: kinggrimlock REMOTE: 198.245.63.50:7777) Voice Changer Not Concealing Identity

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4336]
>Revision (Should be above if you're viewing this from ingame!)

>I was a traitor and bought the voice changer for some secret informant shenanigans, only to find out that it wasn't rendering my voice unrecognizable.

>I expected the voice changer to actually conceal my identity.

>It didn't conceal my identity.

>1. Be a traitor
 2. Buy a voice  changer
 3. Don't wear ANY identification.
 4. Speak
 5. Watch in amazement as it does exactly jackshit

**Comment by d3athrow** [comment]
well this was broken but got fixed for no apparent reason.
