### ISSUE TITLE
(WEB REPORT BY: gespacho REMOTE: 198.245.63.50:7777) Dionae nymph mask bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4337]
>Revision 
f1d013e33a9b438a5917d1290247e529e8fa239a

>General description of the issue

I found a clown mask and slapped it on as a nymph, now there is no mask sprite in my mask slot so I can't remove it my self.  Haven't tested with other masks or by trying to get someone to take it off of me.

>What you expected to happen
Mask go, mask go off

>What actually happened
The opposite of the latter half of the above sentence.

>Steps to reproduce if possible

See the above

**Comment by d3athrow** [comment]
1f4abeae16d864b6bda5b6da35ffb24ccb30cd3a should fix

**Comment by clusterfack** [comment]
It hasn't been reported since so must be fixed
