### ISSUE TITLE
(WEB REPORT BY: gentlemansir REMOTE: 198.245.63.50:7777) No Exosuit tab while in Gygax

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4338]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Well I hopped in a Gygax and when I wanted to get out realized that there's no tab TO get out. There's no mech tab at all.

>What you expected to happen
Find a Mech tab

>What actually happened
No Mech Tab

>Steps to reproduce if possible
I was, am, in a gygax.
Maybe it's just on my end but there's nothing here

**Comment by ComicIronic** [comment]
Maybe just missed the tab, or it didn't update verbs because they weren't in a loc?

**Comment by wwjnc** [comment]
It happened to me with a Phazon, it might be related to lag. I had to relog to get the verbs correctly.

**Comment by ComicIronic** [comment]
How I hate verbs.
Hopefully mechs will eventually be able to use their own HUD.

**Comment by clusterfack** [comment]
Spring cleaning
