### ISSUE TITLE
Suit Storage Units have two maintenance panels, one can't be opened

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4339]
Apparently they have unique functionality that allows you to hack them and disable safeties, so you can cram someone inside and toast them. Or something. Problem being, they also have the maintenance panel common to all machines, and the attackby gets overriden. Or something. I'm not sure.
Also they can't be deconstructed.

**Comment by Exxion** [comment]
Looks like SSUs had the panel before the generic machine panel was added, or at least before it was in major use. Nobody bothered to port it properly.

**Comment by Intigracy** [comment]
Fixed, I open the panels all the time and disable the safeties.

**Comment by clusterfack** [comment]
Jesus people when you fix a bug autoclose the issue
