### ISSUE TITLE
Dropping your plasma tank as a plasmaman fucks you out of breathing 5ever

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#4341]
Be a plasmaman, put your tank in your hand, and either have it knocked out of your hand or drop it. Try to put it back on and turn your internals back on. The game tells you you dont have a plasma tank. Watch as you suffocate to death.

**Comment by PJB3005** [comment]
You can probably circumvent this by opening the tank's UI and opening the valve from there

**Comment by d3athrow** [comment]
interesting

**Comment by d3athrow** [comment]
this happens because the system is literally the worst ever
