### ISSUE TITLE
Spacepod weapon balance kind of bonkers

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4344]
Spacepods only have three weapons: tasers, burst tasers, and lasers.
Tasers fire pretty quick, burst tasers fire just as fast AND fire 3 taser projectiles one after the other. You can pretty much make a constant stream of yellow balls. Their only downside compared to normal tasers is that they consume 25 power rather than 10, which is negligible.
Lasers, on the other hand, are a bit too slow to be of much use, but are otherwise fine I guess.

**Comment by Exxion** [comment]
The lasers can shoot through windows, though, which is pretty nice
Burst tasers should definitely either be substantially weaker than the standard taser or use more power than they do. They should also be slower to fire.
Not sure why the laser is so much slower than the others. I guess it's supposed to be for balance, but each projectile is only as powerful as a normal laser gun anyway.

**Comment by 9600bauds** [comment]
I consider this fixed by now
