### ISSUE TITLE
Rapid Piping Device Can't Paint Bent and Straight Insulated Pipes

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4345]
Possibly others as well, those two were all I tested because I was in the middle of something else. It can paint insulated pipe manifolds just fine, but when I tried to paint a straight or bent insulated pipe, it acted as if the thing I was clicking on wasn't a pipe.

**Comment by Probe1** [comment]
I ran into this two months ago but I guess the report didn't go anywhere.  It can't paint insulated bent pipes, straight pipes, or 4 way manifolds.  It can paint regular 3 way manifolds.

**Comment by Shadowmech88** [comment]
Moved to Gitlab.
