### ISSUE TITLE
(WEB REPORT BY: kilkun REMOTE: 198.245.63.50:7777) Aliens can speak Sol Common

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4352]
>Revision (Should be above if you're viewing this from ingame!)
4c0fe90ecafda384b8d6819c7ccab5b28d333d67 

>General description of the issue
Aliens can understand what is supposed to be the human only language

>What you expected to happen
Dirty vox scum to not be able to speak sol common.

>What actually happened
Dirty vox actually understanding sol common

>Steps to reproduce if possible
say ":1 Vox are pox"

**Comment by CptWad** [comment]
inb4 deaf the vox language war now.

**Comment by ComicIronic** [comment]
>human only language
>sol common

**Comment by Exxion** [comment]
It's Sol Common, named after *our* sun, Sol
The fluff calls it the human language
But then SS13 is a human-owned vessel, so maybe all employees would know it

**Comment by ComicIronic** [comment]
I don't understand why people think all the races on a space station would be unable to communicate with each other. Of course the Vox know Sol Common: how else are you expecting them to be functional members of the crew?
"Hey Ytytytytktch, can I get a multitool?"
"chk dck ik bak"

**Comment by Ephx1** [comment]
The AI having all language packages is CLEARLY supposed to mean that they have to translate everything for everyone.

**Comment by Exxion** [comment]
It would make sense for raiders to not understand Common, but then planning would be difficult because they couldn't listen in on the crew very well
Or is that how it already works? I've never seen raiders, before or after the languages update.

**Comment by Ephx1** [comment]
No, Raiders are just standard vox, sol common and all. Although with the language update they can actually talk secretly on their secret channel if the validhunters find their headset.

**Comment by ComicIronic** [comment]
I believe Vox Raiders are only unique among Vox for not speaking in Sol Common automatically. They speak Vox Pidgin by default, and have to manually speak Common.

**Comment by d3athrow** [comment]
Assuming you're not talking about xenos this is not a bug.

**Comment by kilkun** [comment]
The thing is sol common was the human only language, nobody but humans could speak it.

As opposed to the common language, which everybody could speak and had no :[#] to use.

It's maybe a pedantic naming issue, but humans not having a species language is pretty stupid when everybody else has one. Even the unusable tajaran.

**Comment by ComicIronic** [comment]
>The thing is sol common was the human only language, nobody but humans could speak it.

No, it's the common language. This is why it has "common" in the name.
When humans speak, they are default speaking in Sol Common. They aren't speaking in no language at all. However, there also needs to be a language that all the crew can understand i.e. a 'common' one, which, funnily enough, happens to be Sol Common.
