### ISSUE TITLE
Diona Nymphs do not absorb languages

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4355]
This was a feature originally... I think. And you could steal blood and suddenly learn a new language from whatever race it was, pretty cool.

**Comment by AutismSpider** [comment]
It was a feature.

Take a blood form X race and you could copy the language.

**Comment by Zuhayr** [comment]
It was removed on Bay because their lore was changed, maybe you lost it in an update.

**Comment by gbasood** [comment]
Is this even a feature people care about anymore? I mean it's cool but is it cool enough to actually re-implement

**Comment by ihadtoregisterforthis** [comment]
Yes, but only on several blood samples.
Even more, make it mandatory. Learning a fusion of chinese and english by taking blood samples out of stillborn nymphs doesn't make sense.
