### ISSUE TITLE
Diona Nymph sign up is terrible

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4356]
It's not like Positronic Brain or pAI where you could select yes or no if you wanna be a Nymph, it's just pop you're a Diona now so I hope you weren't dead and awaiting cloning or anything.
I know, I know, "Just turn it off", but that's silly, if Posibrain and pAI both get prompts, Nymph should too.

**Comment by AutismSpider** [comment]
It did have a prompt

Not sure what happen to it.

**Comment by ComicIronic** [comment]
Do posibrains give prompts if set to Always?

**Comment by Ephx1** [comment]
You'll get a little text notice saying "You are eligible for a Positronic Brain, Get ready" then get a teleport or retract option next to it.

**Comment by d3athrow** [comment]
If you dont want to always be a diona then dont click always or set the preference to always dumbass

**Comment by Ephx1** [comment]
But there's no prompt, no nothing, if you have no clue Botanists were even growing Diona you're now one.
Most people have it on just in case, Posibrains tell you "HEY, GET READY", so I'm prepared to be one.
Now you just pop into one, I don't even think "Yes" option changes anything.

**Comment by PJB3005** [comment]
Yep, pretty shitty, seriously, imagine being about to be cloned and then BING you're a diona

**Comment by ComicIronic** [comment]
As was pointed out before, this is what happens if you set something to "Always". If you can confirm it happens even when set to "Yes", then this is a bug, but otherwise don't set a role to Always if you don't intend to, yknow, always say yes to it.

**Comment by Probe1** [comment]
@N3X15 don't think there's anything left to discuss, close
