### ISSUE TITLE
(WEB REPORT BY: ghlor REMOTE: 198.245.63.50:7777) Wardens battering ram instantly breaking doors.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4357]
I've noticed that sometimes if you just walk away while it's battering, it just busts the airlock right away instead of cancelling the action.

**Comment by Exxion** [comment]
If I'm not mistaken, tabbing is fucked up and there's stuff that should be in the if(do_after(...)) that is instead right after it
@Kurfursten

**Comment by Kurfursten** [comment]
@ghlor @Exxion I know about this issue, it's on a list of fixes to my PRs that will be handled this weekend. Thanks for reporting it anyway.

**Comment by Exxion** [comment]
Yeah that weekend came and went long ago
I think maybe it's time for someone to handle this

**Comment by Kurfursten** [comment]
@Exxion Finals and overseas travel happened, I'll write it today, but I certainly won't mind if someone fixes it in the mean time.
