### ISSUE TITLE
Both syringe guns use same in-hand sprite

### ISSUE THREAD

**Issue by wild-billy** [d3athrow/vgstation13#436]
The in-hand sprites for both the regular and rapid syringe guns are identical (both look like the rapid).
I'm ~70% sure they were different before this last update, since it immediately jumped out at me.
If they weren't, maybe they should be for clarity.

![2014-01-17 08_05_51-battle factory 35](https://f.cloud.github.com/assets/6355724/1947651/783b4852-8060-11e3-909a-45dd59ef46b5.png)
(main and test server as of now)

**Comment by ririchiyo** [comment]
Going to close this and leave the other one open with a list of all the sprites.
