### ISSUE TITLE
Magic missiles still do unexplained tremendous damage to anyone touching them

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4360]
Its strange but occasionally magic missiles do SHITLOADS of damage to people next to them. Ususally happens if you are next to the wizard when he casts the spell.
I think what tried to fix it was "The magic missile pops with a flash!" message but that did not fix the main issue as to where this damage was coming from.
Revival of #2996

**Comment by DeityLink** [comment]
Isn't that what happens when wizards staff of animation their magic missile bolts?

**Comment by ComicIronic** [comment]
You need to be more clear.
Can you give an example of when this happened?
Did the message still appear? Did it appear repeatedly?

**Comment by CptWad** [comment]
What happens is that when you are next to a MM missile you take damage. Its strange but it happens

**Comment by d3athrow** [comment]
Most likely the missile is trying to bump into you but failing but is still dealing the damage.

**Comment by CptWad** [comment]
This is still happening
why is this still happening
Oh god you can get put in crit and it still does more damage than fireball

**Comment by ComicIronic** [comment]
>why is this still happening

Because your bug report isn't useful enough or specific enough to determine what the bug is or in what situations it happens.

**Comment by CptWad** [comment]
The magic missile creates an area of effect around it. Like a collision or some shit
When you stand next to a MM you take damage
if a wizard is right next to you when he casts MM it deals a shitload of damage

**Comment by ComicIronic** [comment]
Testing it on a local server has not produced this result.

And you don't have to tell me how the projectile works, I coded it. That's why I can't figure out where this error is coming from.

**Comment by CptWad** [comment]
Happened again tonight.
The action usually happens when a player is next to the wizard when he MMs. Also it tends to knock the player out. 
Try casting MM next to some windows with a player next to the wizard and the windows. That should fire it

**Comment by CptWad** [comment]
ARISE BUG
ARISE

**Comment by Arthurdentist** [comment]
when I test this I do about ten damage. I am standing next to a window as wizard with another person standing next to me. That person takes ten burn damage or so when they get hit. Not sure that constitutes shitloads but its still a not-insignificant amount.

**Comment by 9600bauds** [comment]
I have for sure gone from max health to instadead from magic missile alone. This happened in the emergency shuttle medbay, which a rather cramped space, if it helps. Pretty sure I was up against a window or wall.

**Comment by Arthurdentist** [comment]
I've seen this happen in the HoP queue come to think of it, when I get the time I'll try it there. or somewhere else similar. Tight spaces seem to be the key.

**Comment by CptWad** [comment]
A "Shitload" is usually caused when there is a lot of mobs in range of the wizard. And all the missles pop next to you
Thats 10 burn per missle, meaning you go into crit if you are unlucky and theres 10 people.

**Comment by CptWad** [comment]
Still broken send help

**Comment by 9600bauds** [comment]
idunno lol

**Comment by Iamgoofball** [comment]
yeah this is probably because all the missiles start on one tile

it goes like this
P = Person
W = Wizard
M = Magic Missile

P
P
P
P
P <--- this motherfucker takes it up the ass 5 times from Magic Missile
Mx5
W

missiles go up, and all 5 missiles hit the marked out P

fix this by making missile spawn spread out and/or path AROUND shit that isn't their target
