### ISSUE TITLE
(WEB REPORT BY: eldorado12345 REMOTE: 198.245.63.50:7777) Pressure in vents/scrubber system

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4364]
>(Should be above if you're viewing this from ingame!)

>General description of the issue
Tonight i was become monkey as changeling, climbed to vents system and then... Went to red health, then i climbed to scrubbers, and went to crit, and died.

>Just use vent system, and don't die?

>I died.

>Steps to reproduce if possible
1.Become changeling.
2. Become monkey from lesser form ability.
3.Climb to scrubbers/vents system.
4. Enjoy.

**Comment by AutismSpider** [comment]
scrubbers most of the time have zero to very little pressure in it

Zero pressure = death

if its to high = death

**Comment by d3athrow** [comment]
RIP

**Comment by FudgePucker** [comment]
|>oh hey let me just vent crawl into the pipe system that sucks up all the shit on the station like plasma and CO2 and crawl around it it as anything other than a autistic skittering robot.

No shit scrubbers kill you.
Also, isn't the new vent crawling make the usual over loading of distro to help with depressurization meta gaming now?

**Comment by clusterfack** [comment]
Theres a message now that tells you whats going on inside the pipe
