### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) Disappearing mob

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4365]
>Revision (Should be above if you're viewing this from ingame!)
8e87db5c4f57e80f5eaef1ac5144401d8b888cf5

>General description of the issue
Immediately after summoning someone with a Summon Cultist rune, I vanished, unable to see anything, total black. Could still toggle internals but nothing else. Administrator said "Mob doesn't exist"

**Comment by nuklearcellphoneg** [comment]
Was the admin on this. Tried JMP to mob, said mob did not exist. Get mob successfully retrieved his mod.

**Comment by Exxion** [comment]
Extremely similar to what happens if you somehow manage to walk off the edge of a Z-level, though I have no idea why it would happen in this case.

**Comment by d3athrow** [comment]
loc got set to 0,0,0

**Comment by clusterfack** [comment]
He got nullspaced but this is insufficient information to fix and happened long enough ago it may have already been fixed
