### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Clown name issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4367]
When the Clown is cloned his "voice" or name on chat turns into the saved setup name, (like if i would join as Walter,my voice will change back to Walter not to the clown name) so this problem works for changeling clown too,if you try to turn back to your form,your voice changes to the "real" name

**Comment by d3athrow** [comment]
Well its properly changing the dna name so i dont know whats up.

**Comment by d3athrow** [comment]
Yeah its working fine for me.
