### ISSUE TITLE
Monkey Languages Staff of Change

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#4368]
If you are staff of changed into a monkey then things get weird.

1. You can understand Humans but humans can't understand you
2. Borgs can't understand you but you can understand them
3. Slimes can understand you and you can understand them
4. A brain in an MMI cannot understand you and you cannot understand it

Previously being monkied via staff of change meant you still spoke human and anyone who could understand human understood you.

**Comment by DeityLink** [comment]
something something saycode, something something languages

**Comment by Arthurdentist** [comment]
Yeah I know there are a lot of issues still, but its best to get these reports made so it can be dealt with
