### ISSUE TITLE
(WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) Muteness stayed even after deactivating it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4373]
>Revision b075f8bb5a15a13e6ae04d26fa2c4fd0c8f49a3d

>General description of the issue
I got the muteness defect, deactivated it, but I was still mute

>What you expected to happen
No longer being mute

>What actually happened
I stayed mute

>Steps to reproduce if possible
inject yourself with muteness
clean SE
cry because you can't speak

**Comment by PJB3005** [comment]
Ryetalyn fixed this, still annoying

**Comment by d3athrow** [comment]
Probably stems from disability/deactivate never returning anything but null.
