### ISSUE TITLE
No mechanics airlock assembly

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4375]

**Comment by Probe1** [comment]
do we really need one?  we're part of engineering and research.  either or should be fine to me.  genetics don't get their own airlock assembly but are part of medbay and research right?

**Comment by ComicIronic** [comment]
The Mechanics door is a different shade of purple to the regular science door, for whatever reason.

**Comment by Xikes** [comment]
Sorry for the necro, but noticed this a couple days ago and this bugs me. Genetics is inside medbay and is not accessible from the main hallway. The workshop typically is. If you build extensions or need to replace airlocks in the workshop it would logically make sense to add workshop doors to new assemblies.

Although personally I think any type of airlock on the station should be buildable with assemblies, genetics included.

**Comment by 9600bauds** [comment]
comic why

**Comment by 9600bauds** [comment]
`/obj/machinery/door/airlock/engineering{icon = 'icons/obj/doors/Doorsci.dmi'; name = "Mechanics Workshop"; req_access_txt = "501"}`

**Comment by 9600bauds** [comment]
why comic
