### ISSUE TITLE
Sulphur is ULTRA RARE

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4376]
I've been playing around with ghettochem and I noticed something.
Hacked Groans machines are the only places outside of chemistry to get sulphur/sulphuric acid. You obviously don't want it to be super easy to get because sulphuric acid is dangerous, but it is currently easier to acquire polytrinic acid than it is to acquire sulphuric acid outside of chem. One of the banned Groans sodas contains polytrinic acid, and the only way to get sulphuric acid/sulphur is to electrolyze that.
I don't know where sulphur should come from outside of chemistry, but it's way too rare right now.

**Comment by TermedClepe** [comment]
It's not rare, flares are literally everywhere:

Grind flares for sulphur
Electrolyze water for oxygen
Combine water, oxygen and sulphur and get acid.

**Comment by Exxion** [comment]
Oh
I didn't know flares contained sulphur
The Wiki does not say that
