### ISSUE TITLE
Make AI radio built-in

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4380]
Someone in thread asked for this.
Main problem is constantly fiddling with intercomms just to answer people, and should function more similarly to a Captain's headset allowing the AI to use the radio keys like :m or :s to easily respond and listen.

**Comment by Zuhayr** [comment]
Could port this from Bay if you're up to resolving the saycode differences.

**Comment by SkowronX** [comment]
There was a recent port of language code. Might not be as bad thanks to that.

**Comment by clusterfack** [comment]
Cyborgs already have built in radio so this isn't really hard at all

**Comment by IratePirate** [comment]
This would make playing as AI much less lonely, and as a result, more fun. AI should be able to respond on any channel.

**Comment by Ephx1** [comment]
Decided never to be merged, RIP big brother
