### ISSUE TITLE
(WEB REPORT BY: fozzington REMOTE: 198.245.63.50:7777) Vampire Sight Interfering with Eyewear Functions

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4382]
http://i.imgur.com/JCZnYtZ.jpg

Hopefully the above screenshot shows enough of my claim to be understood and dealt with

**Comment by ComicIronic** [comment]
Mobs really need a sight controller, rather than trying to set things manually.

**Comment by FudgePucker** [comment]
The weird thing is that normal xray from genetics works with mesons and NVGs.

**Comment by gbasood** [comment]
Can't reproduce with antag madness'd vampire

Possible didn't have vampire sight either through bug or misunderstanding

Given that I know antag genetics are super fucking buggy, going to go with genetic bugs

**Comment by CptWad** [comment]
I think this was fixed with later updates, I made an issue about xray not working at all which was fixed. I also never have issues as vamp with vision any more since.

**Comment by gbasood** [comment]
Closing until it pops up again then
