### ISSUE TITLE
Something's Wrong With Gases

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4383]
Looked at a MoMMI's SME setup earlier, nothing seemed visibly wrong with it. But the canister they were using to supply the O2 had six million kPa of -150C oxygen, with the extra oxygen coming from seemingly nowhere. Someone else that round was doing a burn chamber, and according to them, it seemed to be producing oxygen and plasma, and they couldn't get the reaction to go out.

I don't know, it just seems like something got messed up.

**Comment by d3athrow** [comment]
Just remove gasses holy shit

**Comment by Exxion** [comment]
Might want to check if this is still happening now that the gas datums update was reverted. My guess is no.

**Comment by clusterfack** [comment]
Hearsay, anyway gas datums was reverted and under heavy construction so this is relevant anymore
