### ISSUE TITLE
Allow forcing map rotations

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4384]
Seriously you never get to see meta/deff with all the box fags who aren't willing to see change.

Maybe is meta/deff was enforced more the fags who can't live with change wil get used/like the other maps.

**Comment by ComicIronic** [comment]
I'm on a firm no.

**Comment by Probe1** [comment]
add a random map button instead.  also no.

**Comment by IratePirate** [comment]
I don't think it should be up to the admins to force a map change. It should just be a weighted percentage chance system, like maybe an 80% chance of Box.

**Comment by ririchiyo** [comment]
I'd rather just see a system where another map is forced on players after x many times of the same map being played.

**Comment by ComicIronic** [comment]
I firmly believe any system that forces the map to change, no matter how, is a bad idea.

**Comment by TermedClepe** [comment]
Make a map worth playing and players will vote for it.

**Comment by IratePirate** [comment]
>Make a map worth playing and players will vote for it.

That isn't how video games have ever worked.

Karkand, Dust, 2fort, Metro, Gridlock. People will always vote for the same thing, not out of a genuine belief that it is better, but because they don't like playing anything else. Even if someone made a truly fantastic map for /vg/ it wouldn't get played more than once in a blue moon.

**Comment by ComicIronic** [comment]
Untrue.

**Comment by PJB3005** [comment]
>Untrue.

the fact that box still get players most confirms that IS true

**Comment by ComicIronic** [comment]
No.
The fact that Box still gets the most players is a sign that the other maps aren't considered good enough to play, not that people just want Box for the hell of it.
Going back to the previous example of all those game maps, none of them are the only maps played, nor are the other maps played only through rotation.

**Comment by PJB3005** [comment]
The reason box is most played is because idiots don't accept change

**Comment by Probe1** [comment]
Calling people idiots for disagreeing with you is only insightful of your own beliefs.  People like Box for a number of reasons.  It's tried and tested, well made and a number of other reasons.  

Something we could change without controversy is mixing up the order of the maps on the vote screen.

  That will reduce the "reflex" vote to get rid of the map voting screen.  It also will not remove the decision from anyone as forcing the change, weighting the vote, and hiding the vote screen unless you type/click Vote would do.

**Comment by FudgePucker** [comment]
I think having a map be randomized once in a while might be nice...
Once we implement a way to que map merges so that map changes aren't a cluster fuck like they are right now.
There are so many map errors (Even on box there is still some fucked up places) that will never get fixed because of the system we have now.

**Comment by 9600bauds** [comment]
There's a very important factor to consider here, when people vote for a map, they don't always do it in a conscious, thought out decision.
When the round ends you suddenly get the voting pop-up in the middle of the screen, people just vote the first thing on the list without really thinking so they can watch the shuttlegriff or whatever. This is a problem that has existed in pretty much any game with votemap.

**Comment by FudgePucker** [comment]
Yea, shuttle griff is the most important thing to people who have boring rounds.
If you do not get out of the pop up screens fast enough you will be stunned and harm batoned by a sec borg.
Not even being sarcastic here, if you do not get those screens out of the way you will die a horrible death.

**Comment by CptWad** [comment]
Im for random map places on the menu or a system that weights the needed number of votes based on how many times the map has been played. So if all maps have been played once its 33% each. If box is three times and other two are one then its 60% of the votes for box and 20%/20% for the other two and so on

**Comment by DrCelt** [comment]
Don't take democracy away from the process. I am against this in entirety.

**Comment by 9600bauds** [comment]
That's a given. But maybe making it so that you have to type down "vote 1/2/3" to vote, rather than having the window pop up?

**Comment by clusterfack** [comment]
Most people vote within 5 seconds, the current map voting system is shit

**Comment by Probe1** [comment]
@PJB3005 What do you think of it now?

**Comment by PJB3005** [comment]
Well, considering meta got instantly voted on with the positions scrambled, it sorta shows that the current voting system is kinda crap, Maybe make it so that the maps are random, but the amount of votes a map gets increase the chance for that map

**Comment by ihadtoregisterforthis** [comment]
Adressed for some time, then reverted

**Comment by Probe1** [comment]
we did this with weighted map voting

**Comment by 9600bauds** [comment]
ye this can get closed
