### ISSUE TITLE
(WEB REPORT BY: letsgoplaces REMOTE: 198.245.63.50:7777) C4 did not gib body

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4385]
>Revision (Should be above if you're viewing this from ingame!)

>Placed C4 on the body of Claudios it detonated, and his body remained intact.

>Body would be destroyed.

>Warden was still alive, with the bomb strapped to his chest after it exploded.

>Used sleepy pen, dragged the warden to a safe area in between doors and strapped c4 to him. I heard it go off, but came back and his body was still there with the bomb on him.

**Comment by CptWad** [comment]
Some armors are bomb resistant. Includes HoS jacket, bomb suits, RIG suits, captains suit and wardens suit maybe. I would have to check
Either way its probably working as intended.

**Comment by Exxion** [comment]
Except the bomb should have at least disappeared.
