### ISSUE TITLE
MoMMIes can't be locked down at robotics control console

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4386]
MoMMIEs are immune to any lock down.

**Comment by PJB3005** [comment]
What.

Are you insane?

This is a retarded idea.

**Comment by d3athrow** [comment]
This is intended.

**Comment by TermedClepe** [comment]
Why?

We can lockdown borgs, MoMMIes are way more capable than borgs.

**Comment by ComicIronic** [comment]
MoMMIs are easily disabled and have no real reason to be lockdown-able, because they're also not that dangerous.

**Comment by PJB3005** [comment]
how to kill an MoMMI:
1. get floor tile
2. throw floor tile
3. ...
4. profit!

**Comment by CptWad** [comment]
Mommis were removed from the robotics control because retards would  BLOW ALL THE BORGS!!1! which would include mommis because they feel they dont have time to check which are not borgs

**Comment by IratePirate** [comment]
Honestly the giant "kill all borgs" button should be removed completely. It only takes 5 seconds extra to blow each borg individually and it means people actually have to think about who they're destroying, i.e. if only one borg has actually been displaying rogue behaviour.

**Comment by FudgePucker** [comment]
Also rouge MoMMIs are easier to tell, they have red eyes.
Borgs can be more stealthy with their emagyness.
