### ISSUE TITLE
Tvalve in vox outpost is still flipped.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4391]
A while back ago the tvalves on the station were fucked up and flipped, this effected the incinerator and the one in atmospherics.
The tvalve over here in the vox outpost is still flipped.
![shitsbroke](https://cloud.githubusercontent.com/assets/12202731/7555587/ffbeb4a0-f71d-11e4-8c87-75815246b726.png)

**Comment by ComicIronic** [comment]
Just needs its dir flipped 180

**Comment by PJB3005** [comment]
to add to this, the injector for the tank isn't properly connected

**Comment by FudgePucker** [comment]
That too.
![fixed](https://cloud.githubusercontent.com/assets/12202731/7555625/1fa34fe6-f71f-11e4-8b2b-cbaa84e1b8c9.png)
A single bent pipe would fix it too.

**Comment by IratePirate** [comment]
Will fix.

**Comment by FudgePucker** [comment]
Awesome, reference your PR and when it merges I will close this.

**Comment by PJB3005** [comment]
or if he says 'fixes #X' it'll autoclose
