### ISSUE TITLE
Changeling monkey absorbing promotes passive gameplay

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4393]
Changelings being able to gain genomes from monkeys just the same as if absorbing humans promotes changelings camping until well fed on monkey cubes.

Vampires have to at least humanize monkeys to gain anything from them, preventing feeding on npcs outside genetics range.

**Comment by CptWad** [comment]
Imo There should be a limit on mobs without players attached to them. Like six max then theres a "This DNA is too weak for us" message preventing lings from getting swole and deathsting then proceeding to kill people left and right till they die.
Most people dislike silentparasting but that is what changeling is all about. Slowly earning your right to become a shambling mass of death.

**Comment by AutismSpider** [comment]
it should not count as a useable genome if its form a monkey or monkey human

**Comment by TermedClepe** [comment]
It should require the body to have been a player at one point to gain genomes.

**Comment by IratePirate** [comment]
Changelings are dull as fuck, this only adds to it.

**Comment by ComicIronic** [comment]
I agree, though a player requirement wouldn't fix chef ling, it would encourage lings in genetics to get something done, as they too often don't do.

**Comment by FudgePucker** [comment]
Genetics lings just sitting in genetics is a god send, they have science access and chemistry access, all the have to do is get a rapid fire syringe gun, some chloral, and then drag victims to science outpost.

**Comment by gbasood** [comment]
done
