### ISSUE TITLE
(WEB REPORT BY: discotau REMOTE: 198.245.63.50:7777) Changeling regen not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4394]
Got hurt so I use regenerate, waited around 15 miniutes or so and the 'ready to regenerate' command wouldn't update or appear in the Changeling tab. I had to be regened by and admin in the end.
Damage was just a popped lung.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by TermedClepe** [comment]
I think reconnecting fixes that.

I managed to regen as a decapitated ling. It made me unable to talk or interact with anything, just seen as if I was still alive. Even ghost had that confirmation about going catatonic.

**Comment by Shadowmech88** [comment]
I've had this happen to me before, reconnecting fixed it.
But is it a code issue, or a "Byond is shit" issue?

**Comment by ComicIronic** [comment]
It's a "why are we still using byond verbs dear god" issue.
