### ISSUE TITLE
Non-vox can speak Vox-Pidgin

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4395]
The fluff states that special mouth structures not present in humans are required to speak it.

IMERSOIN

**Comment by Zuhayr** [comment]
That was literally just to keep dickhead Bay players from getting whitelisted to speak it as hyoomans.

**Comment by Exxion** [comment]
So why not use it to keep dickhead /vg/ players from speaking it as hyoomans?

**Comment by Zuhayr** [comment]
Dunno. Was just chipping in with some context.

**Comment by dylanstrategie** [comment]
Secondary languages are not an issue

**Comment by Exxion** [comment]
Not in general
Specifically this one
Also the Skellington and Diona racial languages should be restricted to their respective races, though those may or may not already be

**Comment by 9600bauds** [comment]
I don't think there's any way to actually learn the language besides being Vox or sillycone though

**Comment by Exxion** [comment]
There used to be, at least
Not sure if it still is but it used to be available as a secondary language, if I'm not mistaken
If it isn't then this can be closed

**Comment by gbasood** [comment]
It's not. Only gutter and tradeband are learnable languages
