### ISSUE TITLE
(WEB REPORT BY: gutlesscoward REMOTE: 198.245.63.50:7777) Telecomms Won't Notice New Servers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4396]
> Revision 
> d558c0274f486a299f111c59b83448422aad2e25
> General description of the issue
> Telecomms has several channels, like common, engineering, science, etc. Each of these channels is represented by its own server in the telecomms room. Telecomms servers are actually constructable machines, suggesting that if one were to break, or if you wanted to add a new one, you would be able to by building a new server and linking it correctly. I tried this, and it does not seem to work.
> 
> What you expected to happen
> I expected my server to act like any other server; a message at whatever frequency it is gets played back with the server name on it. For example "Person Name[Department] says, 'DONGS!'". Failing that, I at least expected the telecomms computers to notice the server.
> 
> What actually happened
> Nothing; when I made the server and set it at its frequency, then tried to radio it, I got nothing back. The computers noticed the server, but gave no response when I tried to click on it for more info, unlike the other servers (with notable exception of the mining server, which is off-station.)
> 
> Steps to reproduce if possible
> Make a Telecomms server in the Telecomms Coldroom. Click on it with a multitool to open up its menu. For Identification string, put in whatever you want; I called mine "Meryl Server". for Network, type "tcommsat" like the other machines. use your multitool to link the server first to a bus mainframe (I used #3), then to the telecommunication hub. Add a filtering frequency to the server that isn't already being used (I used 140.1), then
> add the same frequency to the bus you linked the server to. Finally, try to radio your frequency and be amazed and disappointed!

**Comment by Gutlesscoward** [comment]
Okay, no, I figured it out later. The reason why I wasn't getting a radio channel was because I didn't add the frequency to the filter on one of the subspace recievers. Unfortunately, any created radio channel can't be as detailed as the department ones; you don't get to make your own name for them, and they're the same color as the common channel. Oh well!

**Comment by ComicIronic** [comment]
So fixed, or do you want this labeled as a request for customisable channels?

**Comment by Gutlesscoward** [comment]
You might as well, I guess, although I don't really know of anyone who would care too much about this other than me.

**Comment by gbasood** [comment]
First comment is basically the feature request now, the OP is (apparently?) not a thing
