### ISSUE TITLE
Mech Bay Recharge Station slams into a wall!

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4399]
![ss 2015-05-10 at 01 48 16](https://cloud.githubusercontent.com/assets/6526157/7565867/cd20b636-f7c9-11e4-89b0-edfcf3c8f3bf.png)
Mech Bay Recharge Station slams into Zas - Hellish!

**Comment by Exxion** [comment]
Why aren't they anchored?
Actually, why aren't they turfs? They appear to be embedded in the floor.

**Comment by ComicIronic** [comment]
They used to be turfs, but that was bad hardcode. They are now buildable machines.

**Comment by dylanstrategie** [comment]
They should obviously start anchored, and not be unanchorable at all unless we're going to make a special unanchor sequence (it being a big machine embedded into the floor)
