### ISSUE TITLE
Gold atmos helmet shows disfunctional toggle icon

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4401]
Wear a gold atmos helmet, see light toggle top left, click it for no results.

According to @ComicIronic https://github.com/d3athrow/vgstation13/issues/4313 helmet not giving light is intended.

However this is questionable since 
a) we still see the toggle light icon 
b) gold upgrade kit does neither visually nor in description remove lights from helmet

**Comment by Exxion** [comment]
It's definitely intended not to have light, as it has the line "no_light=1" in its definition
But that really should remove the light toggle verb and button rather than just make it not work

**Comment by dylanstrategie** [comment]
Most likely missing a check somewhere in the HUD, or it's an inheritance/hardcoding problem, which is sensibly worse
