### ISSUE TITLE
Impedrezene is shit

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4403]
Impedrezene has an 80% chance to cause 0.5 brain damage per tick.
This is actually less than the sum of it's components: Mercury has a 100% chance to cause 2 brain damage, and Impedrezene needs Mercury to be made. The end result is that you're literally better off just using mercury by itself and never ever making Impedrezene.

But none of that probably matters, since Alkysine is so good, your victim can just shoot up 5u and be 100% good to go anyways. Brain damage in general is pretty half-baked.

**Comment by PJB3005** [comment]
Yeah, alkysine is fucking OP.

A 5 u alkysine pill can easily heal 150% brain damage.

**Comment by Probe1** [comment]
>A 5 u alkysine pill can easily heal 150% brain damage.

can you demonstrate that

**Comment by dylanstrategie** [comment]
Actually, a 5u Alkysine will fix all but the most serious lolbraindead cases, and will do amply for cloning (which usually do 60-ish brain damage)

Brain damage is pretty gimmicky as is. Unlike in real life, having your brain turned into a rotting pile of shit will just make you say dumb things and headbutt airlocks. I'd prefer a Goon-like system where your brain turning into mincemeat is the real trigger for death, but holy shit all the recoding that would need

**Comment by FudgePucker** [comment]
Perhaps causing the same effects as extreme drunkenness with abnormal movement and slurred speech, at higher levels also add organ damage. At the current way the game works, just chloraling someone and choking them to death is a better option, and simpler to do (three buttons for the greatest toxin in the game)
Shit, why are the super dangerous compounds easer to make than useful ones? Spacelube is simple to make, and actually produces more volume than the chemicals in it, as compared to space cleaner that is more complex.

**Comment by 9600bauds** [comment]
Sleep toxin requires chloral to make, just let that sink in.

**Comment by PJB3005** [comment]
Sleep toxin is a thinner version of chloral

**Comment by ComicIronic** [comment]
>Sleep toxin requires chloral to make, just let that sink in.

It's diluted chloral.

**Comment by FudgePucker** [comment]
No really, why is space lube so easy to make but space cleaner so hard?
Lube in the stun based gameplay is super powerful, if someone is charging at you with an esword, all you have to do is spray some space lube in front of you and they slide right into you so you can beat them to death with a bike horn.
Space cleaner requires you to make ammonia first, and isn't as game changing as lube.
Polyacid is super powerful and is just three buttons on the dispenser.
It kinda ruins the point of chemistry (and made goofchem a joke) having the best destructive chemicals be so easy and simple to make.

**Comment by 9600bauds** [comment]
I know it's diluted chloral, just saying that a dangerous chemical is easier to make than a significantly less dangerous, downgraded version of the same chemical.

**Comment by FudgePucker** [comment]
New idea, chemical implants for security and heads that inject antitoxin if chloraled or any toxin is found in blood stream.
That way you can't harm syringe the captain and loot his id.

**Comment by Zth--** [comment]
I'm pretty sure I fixed this like a year ago

**Comment by ghost** [comment]
Have you ?

**Comment by Zth--** [comment]
http://hastebin.com/emuyosihaj.coffee
yes, fuck. It's OP as fuck and no one noticed

**Comment by Sprok0** [comment]
No one noticed because chloral exists, and there's no reason to ever use anything else
