### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Incision Management System

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4409]
So it basically it doesn't work,not as hemostat,not as a retractor,i don't know if there is a third tool,but i would think it wouldn't work too,i would like to suggest to a change tool option,like when you activate it you change the tool type

**Comment by Exxion** [comment]
At some point, tool code should probably be cleaned up to use object variables or procs rather than istype
That would make Swiss Army tools far easier to implement
But there would be a colossal amount of code to change and it would merge conflict everything

**Comment by 9600bauds** [comment]
It's not a "swiss knife" type tool where it replaces the scalpel, retractor and hemostat. It does the "scalpel-hemostat-retractor" combo at the start of most operations in one go, but doesn't act as any of the tools beyond that point.
So to fix internal bleeding, rather than scalpel-hemostat-retractor-fixovein-cautery it's incision management system-fixovein-cautery.

**Comment by dylanstrategie** [comment]
If you are beyond the scalpel step, the Incision Management System is useless. It just works that way. If that is not the problem, please update us on the situation

**Comment by Starnightx** [comment]
Hmm.. i see,because there is this tool and the laser augmented scalpel so i though both were a combo

**Comment by 9600bauds** [comment]
Laser scalpel is just scalpel+hemostat without retractor, and it even has a chance of failure because whoever made it is a dick. You can't even use it for regular scalpel uses. Avoid at all costs

**Comment by 9600bauds** [comment]
I believe this has since been mostly addressed

**Comment by PJB3005** [comment]
So, shall I close it?

**Comment by 9600bauds** [comment]
Yeh
