### ISSUE TITLE
(WEB REPORT BY: chickenzness REMOTE: 198.245.63.50:7777) Mining credits unclaimable.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4411]
Revision: ddbbaa3d30eba2f52f6da7d5391bc15a6088e96b 
>The credits in the ore redemption machine were unclaimable "Failed to be claim credits."

>Get rich

>Got the message "Failed to claim credits."

>Not sure if it will happen every round but two people couldn't redeam the credits.

**Comment by PJB3005** [comment]
Might not be a bug, this could probably happen if something's up with the accounts dabatabase

**Comment by Intigracy** [comment]
ore redemption machine is kill, no longer applies
