### ISSUE TITLE
Status display AI overlay blocks cargo timer

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4415]
Can't tell when the shuttle is going to arrive or if it will be delayed.

![image](https://cloud.githubusercontent.com/assets/8550416/7594601/d98f3a64-f8af-11e4-97f7-22c2a0426f1c.png)

**Comment by CptWad** [comment]
same with shuttle eta. Each console should have a network its set to

**Comment by PsiOmegaDelta** [comment]
Assuming your code is still the same as on Bay AI status is normally only applied to the AI screens, with the explicit exception of Friendly AI which deliberately covers all status screens including cargo and the station status screens.

**Comment by Exxion** [comment]
But... why?

**Comment by CptWad** [comment]
I am with @Exxion remove snowflake code code wars now

**Comment by dylanstrategie** [comment]
I doubt we modified status screen code at all

Make sure ALL status screens compatible with the Cargo ordering console show the cargo shuttle ETA, and only it
