### ISSUE TITLE
(WEB REPORT BY: drcelt REMOTE: 198.245.63.50:7777) Magic Missiles STILL nerfed.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4416]
I thought you said you fixed it.
They disappear seconds after casting.

**Comment by clusterfack** [comment]
https://www.youtube.com/watch?v=8oWAb5NVALw&oref=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D8oWAb5NVALw&has_verified=1
