### ISSUE TITLE
Xenomorph languages all wonky

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4420]
Not sure about as an adult, but as Larvae you can understand humans and Reset your xeno language so you can speak normal Sol Common.
This might be cool for like, Queen, but not so much for a larva.

**Comment by d3athrow** [comment]
Larvas understanding common is intended since they just came out of a human, they shouldn't be able to speak it though.

**Comment by d3athrow** [comment]
If you reset your default language you speak the language of the stupid animals and your message appears to be ************ to humans unless you or them have universal_speak/understand

**Comment by Ephx1** [comment]
Oh neat, well thank you pomfe
