### ISSUE TITLE
Facehugger usage is fucked

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4421]
I can't really explain it, but somehow I think Facehuggers are latching onto you as a Xeno without showing it, but you don't have a mask slot.
So like you pick up the Hugger, and then click on it again and you'll get something along the lines of pushing the hugger away from your face but it looking silly so you push it back.
You can't put them in your pockets, and dropping them doesn't always seem to drop them, so you can drop them again and they'll teleport to you. Sometimes they'll still be in your hands without a sprite, so you having no huggers on hand will sometimes get you "You hit the X with the Alien" when trying to do certain things like break a window or slash a table.

**Comment by d3athrow** [comment]
how could dis happen
