### ISSUE TITLE
(WEB REPORT BY: manaony REMOTE: 198.245.63.50:7777) Telecom is fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4422]
>Revision (Should be above if you're viewing this from ingame!)
bfbf840dba607c1e8758e3542d58e134cbe2557f

>General description of the issue
Telecoms door sprite, wiring and goonecode room are fucked holy shit

>What you expected to happen
Having to shoot my way through shit

>What actually happened
Dead power, dead game, dead powerbase

>Steps to reproduce if possible
Go look at telecom sat right now

**Comment by Manaony** [comment]
I'm a retard I mean the telecom sat, not the station telecom.

**Comment by Exxion** [comment]
Probably has to do with the reversion of gas datums. Git and the map cleaner apparently don't get along well when things get reverted after other map changes. Station telecomms and disposals had tiles rearranged, but Pomf fixed those.
I'll fix this if nobody else gets to it first.
I'll also look through the changes in the reversion to see if there are any other places this could have happened.
