### ISSUE TITLE
Request: Make ctrl+click eject sleepers/scanners

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4424]
Would save a lot of time and make body scanners less clunky to use.
Do we even use ctrl+click for anything?

**Comment by clusterfack** [comment]
Dragging

**Comment by clusterfack** [comment]
I prefer the idea that if you mouse drop out of the machine it would eject them out, same concept as going in

**Comment by 9600bauds** [comment]
That works too. Anything but a verb.

**Comment by ririchiyo** [comment]
You can actually make a macro for this if you really wanted because it is a verb.

**Comment by Kurfursten** [comment]
@clusterfack While not strictly atomic, wouldn't be too hard to just throw into #4238.

Otherwise you're just going to add more conflicts and I'm already waiting on my turn with the map to resolve THOSE conflicts.

**Comment by clusterfack** [comment]
I'm neither modifying the map nor any code that was already there
