### ISSUE TITLE
Security Officers can't unlock weapon lockboxes

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4426]
naturally they just break them open because that's retarded and no one is going to tell sec no, you can't have guns.  it should open for weapon permit and not whatever it is now.

Adding on a bit to this - I don't know what the discussion or thoughts on setting the access requirement were.  But they aren't realistic.  Security is going to get guns.  They're carrying tasers at least.  And they can easily break open the lockboxes. 

 So can anyone on the station but the issues with laser tag guns and floral somatories are for a different Issue. 

 As it stands, lockboxes withhold weapons from people authorized to carry weapons.  This creates an environment where no one takes a lockbox seriously and will quickly acquire something to break it open so they can get the weapon.  Other sec officers aren't going to arrest them.  The HoS and all but the most anal retentive Warden won't care.  

The lockboxes are a stick in the mud that gets pulled out and tossed aside.  Whatever the logic was behind making security officers unable to open the lockboxes, it was faulty.  It does not work in game when players will readily go around it without any qualms.

**Comment by dylanstrategie** [comment]
Technically, only Research, Heads and Sec should open normal lockboxes, and only Heads should open ultra-secure lockboxes (guns and experimental gear)

In reality, lockboxes are fucked

**Comment by PJB3005** [comment]
Yep, floral somatoray being able to break them open is OP

#4062

**Comment by TermedClepe** [comment]
Good luck getting anything done about it, science is hilariously over equipped and any attempt to bring it in line is met with "controversial" "discussion" "never merge".

**Comment by Exxion** [comment]
I'd say make the access requirements reasonable, fix the laser tag/somatoray issue, and make it so that breaking the lockbox damages the thing inside so it has to be repaired (maybe another use for the soldering iron).
That would encourage R&D to get someone to open them correctly while still allowing traitors/people defending against traitors to open them without access.

**Comment by ComicIronic** [comment]
This is only an issue when lockboxes are not so easily broken.
Also, I don't think any officer should be able to open all lockboxes. Some of them, like heavy lasers, are very dangerous.

**Comment by Probe1** [comment]
This isn't controversial at all Comic.  No one in game respects them when they can easily be broken into and it's something that's part of their job anyways.

**Comment by Probe1** [comment]
Watch it and tell me how this makes any sense.
 
![2](https://cloud.githubusercontent.com/assets/8550416/7620058/214051c8-f98b-11e4-84e5-d70b9c044d70.gif)

**Comment by ComicIronic** [comment]
It's not a bug, because there's no loss of intended behaviour. It's not an oversight, because the lockbox access is deliberate.

It's still fundamentally an issue with lockboxes themselves being piss-weak, and I'm tempted to close this issue because it won't bring much new discussion beyond that point.

**Comment by Probe1** [comment]
I want to discuss what I've stated.  That security officers have a right to weapons.  You say that some weapons should be off limits and that is fine.  But I have demonstrated that the current method is extremely poorly done.  Security can open lockboxes with the weapons they start the round with.  

That makes no sense.  It makes no sense to treat a stun revolver (which is unremarkable except that its cell size is improved) the same as a plasma cannon.  

Having lockboxes be beyond securities hands only means one thing:  Lockboxes are undermined and treated like a joke.  Even security itself will not respect them.  The entire idea of bringing them back was to make having guns without access/permission meaningfully illegal.  The issue was there was absolutely no incentive to enforce it when anyone could open a lockbox.  Now, only the warden, HoS, and Captain can (I may be wrong).  So we've reached the exact opposite end.  No one can open them so everyone breaks them open and no one cares that they exist because there is no meaningful way to open them.

We've gone from one pole to the opposite.

**Comment by ComicIronic** [comment]
>Security can open lockboxes with the weapons they start the round with. 

Which is, again, an issue with lockboxes themselves, not with Sec access. You shouldn't really be acting as though it's a separate issue to address.

>That security officers have a right to weapons.

They really don't. The Armory is controlled-access for a reason. They have a right to a taser.

**Comment by Probe1** [comment]
I'm willing to limit my points and discussion to just the stun revolver then.  But it still drives me to point out that because officers can't unlock any lockboxes, no matter how reasonable, they will freely break into any lockbox because the logic is deeply flawed.

**Comment by d3athrow** [comment]
Weapon lockboxes, weapon crates and closets always had the access_armory requirement to my knowledge.

**Comment by Probe1** [comment]
Tactfully change certain ones to weapon permit then.

**Comment by Probe1** [comment]
To be honest with the most egregious methods of opening lockboxes gone, it removes most of my ire.  

I still feel that certain items should not have armory access required.  I will make a new issue at a later date if I feel strongly enough about it.
