### ISSUE TITLE
Exosuit Fab or Protolathe output more than inserted

### ISSUE THREAD

**Issue by Manaony** [d3athrow/vgstation13#4427]
Welp let's try that again. So either one or both the exofab or protolathe can give you more sheet than you input in them through some magical shenanigans. I'd have to test out the ratio and if upgrading matters but I was able to go from 3 diamond sheet to 9 in several operation some day ago.

**Comment by dylanstrategie** [comment]
Sounds like a faulty multiplier

**Comment by 9600bauds** [comment]
99$ sure this was fixed, reopen if not
