### ISSUE TITLE
(WEB REPORT BY: chickenzness REMOTE: 198.245.63.50:7777) Diona bag issues.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4430]
>Revision: 3ba32f7cffa33a17202ff0eb79c6b0066f46fb4f

>When you pick up a bag an invisible bag is put on. You have to get someone to take it off and put a bag on you.

>Pick up and put on a bag.

>You couldn't also after getting someone to put the pack on and take one off my bag dissappeared.

>Be a little Diona and put a backpack on.

**Comment by ComicIronic** [comment]
Annoying-ass snowflake UI code.

**Comment by clusterfack** [comment]
Unable to reproduce, may have been fixed already
