### ISSUE TITLE
SQL schema is broke

### ISSUE THREAD

**Issue by abcdicks** [d3athrow/vgstation13#4431]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/SQL/players2.sql

Using MySQL 5.5. When I try to insert it  to the database it returns syntax errors for every table.

**Comment by PJB3005** [comment]
That SQL table isn't for MySQL, it's the table used to built players2_empty.sqlite.

To setup the players2 database, rename players2_empty.sqlite to players2.sqlite

**Comment by abcdicks** [comment]
Got it. Thanks!
