### ISSUE TITLE
(WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) Upgrading a sec cameras board with a soldering iron doesn't delete the old board

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4432]
>Revision 3ba32f7cffa33a17202ff0eb79c6b0066f46fb4f
>General description of the issue
Title.
>What you expected to happen
Old board'd be deleted.

>What actually happened
I got a second security camera board!

>Steps to reproduce if possible
Get security camera board
use soldering iron on it

**Comment by 9600bauds** [comment]
This can be closed
