### ISSUE TITLE
[Request/Help Me Do This] Improve messages for Cloner console

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4433]
The cloner console is a little user-unfriendly because most of the failure causes give you the same error, "Mental interface failure". This results in people mistakenly thinking a corpse that gives "Mental interface failure" will never be cloneable, but it can be the case that it's just a guy that had ghosted and didn't get in his corpse quick enough when he got the "get back in your corpse if you want to be cloned" message.
The Defib gives you a different message in the "ghosted player" case, telling you try again in 5 seconds. The Morgue trays also have a different color for that case. I wanted to change the Cloner to work similarly, but then I realized I have no way of testing if it works, since I do my testing in singleplayer hosting my own server!

**Comment by PJB3005** [comment]
I can help you with this.

Or just ask anybody on IRC, people are friendly enough.

**Comment by 9600bauds** [comment]
For whatever god-forsaken reason the thought that people could actually join my hosted server never came to my mind
I'm serious
