### ISSUE TITLE
More Language Fuckery Cyborg Edition

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#4437]
Starting out as a Default borg has some interesting problems with languages. Until you pick a module you can't understand other people, and it seems that your default language is something you yourself can't even understand. So to talk normally you have to go into your language list and set to default, then when that's done you can talk normally, but everyone else still speaks incomprehensibly.
Until you pick a module there is no way of knowing what other people are saying save for PDA.

**Comment by d3athrow** [comment]
Then how about you pick a fucking module dumbass

**Comment by Ephx1** [comment]
Pomf... why would a borg be unable to understand people as default anyways? It's very useful to ask people what they would like you to be.
