### ISSUE TITLE
(WEB REPORT BY: banon13 REMOTE: 198.245.63.50:7777) Engineering rig sprites

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4438]
Revision: 1b69e046a85508887f48ffc28b22523ae6799411 

Vox can wear human engineering rigsuits. The helmet shows as a the human sprite but the bodysuit makes the vox look naked.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by dylanstrategie** [comment]
Missing species_can_wear argument, most likely

**Comment by dylanstrategie** [comment]
Just checked, Voxes are tagged as able to wear this for some reason. I'll remove it as soon as my helmet light PR is through (otherwise I get conflicts)
