### ISSUE TITLE
(WEB REPORT BY: somhuan REMOTE: 198.245.63.50:7777) Diona nymph bags

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4440]
>Revision (Should be above if you're viewing this from ingame!)
1f4abeae16d864b6bda5b6da35ffb24ccb30cd3a 

>General description of the issue
Diona nymphs can't equip backpacks or satchels, but get one on their back icon-wise when they try.

>What you expected to happen
Either the bag being worn and shown on the icon, or the bag not being worn or shown on the icon.

>What actually happened
I tried to wear the bag, it failed, but it still showed on the icon.

>Steps to reproduce if possible
Be a diona nymph, try to put on a satchel or backpack.

**Comment by d3athrow** [comment]
duplicate
