### ISSUE TITLE
(WEB REPORT BY: kilkun REMOTE: 198.245.63.50:7777) spiderbots can't ventcrawl

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4441]
>Revision (Should be above if you're viewing this from ingame!)
9777b0782bf4b21c4629bd6025fc9229f734e916 

>General description of the issue
spiderbots cannot ventcrawl, game thinks they are holding shit.

>What you expected to happen
cute bots ventcrawling cutely

>What actually happened
byond taking a shit

>Steps to reproduce if possible
try to ventcrawl as a cute spiderbot

**Comment by clusterfack** [comment]
Duplicate, and unable to reproduce.

Seriously there needs to be SOME other factor for this to be a bug.
