### ISSUE TITLE
(WEB REPORT BY: jakedb REMOTE: 198.245.63.50:7777) Janicart teleporter weirdness

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4448]
>Revision (Should be above if you're viewing this from ingame!)
9777b0782bf4b21c4629bd6025fc9229f734e916

>General description of the issue
when going through a teleporter on a janicart(may work the same on other vehicles)only the cart through but you're still buckled to it, meaning you can't move. when dropping the keys you get the error message even when seemingly not connected.

>What you expected to happen
either go I go through the teleporter with the cart or it would go through first and I could follow.

>What actually happened
Janicart was sent through and I couldn't move, when dropping keys it showed that I was still technically connected to the cart can drop a screenshot if you want.

>Steps to reproduce if possible
>on a janicart
>set teleporter to satelite
>try to go through

**Comment by CptWad** [comment]
Yeah whenever I teleport w/ janicart it goes first then I have to follow on it.
probably byond issue. Trying to teleport someone and an object they are not holding at the same time would require an entire teleport rewrite methinks
