### ISSUE TITLE
(WEB REPORT BY: pjb3005 REMOTE: 198.245.63.50:7777) Can't fix broken armour plating on borgs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4451]
>Revision: 9777b0782bf4b21c4629bd6025fc9229f734e916

>General description of the issue
My armour plating was broken, the roboticist couldn't fix it, tried nanopaste & replacing, had to reassemble me in the end.

>What you expected to happen
That I would have non broken armour plating

>What actually happened
I was reassembled

>Steps to reproduce if possible
Be borg
Get armour plating broken
try to replace it
cry because you need to be reassembled to get fixed

**Comment by CptWad** [comment]
What DOES nanopaste do? I only ever use borg scanners to find what parts I have to replace then replace them.

**Comment by AutismSpider** [comment]
nano paste has two uses.

use to fix up robo organs and limbs.

other use is to fix both damage types cyborgs/mommis get.

if the borgs armour plating is broken he/she has to crowbar out the old one 1st put the new one in then welding tool/nano paste the left over damage.

**Comment by ComicIronic** [comment]
Was the nanopaste used before or after replacement?

**Comment by dylanstrategie** [comment]
Normally, you do indeed need to completely replace broken organs. I don't see why a full reassembly was needed at any stage

As for nanopaste, I personally can't confirm. It would however seem obvious you'd at least need to open the borg's panel and expose his internals when applying it to fix internal damage

**Comment by AutismSpider** [comment]
internal damage is burn for borgs.

need to use cables after opening it up or nano paste on a open or close up borg this is after you take out the damage organs and put new ones in.

**Comment by ComicIronic** [comment]
Unless someone can confirm this was happening with nanopaste applied BEFORE component switching, it's not a bug.

**Comment by PJB3005** [comment]
I think nanopaste WAS applied before component switching

**Comment by ComicIronic** [comment]
Woops, I meant AFTER.

Nanopaste before has this intended behaviour, because it can't fix a completely broken component.

**Comment by PJB3005** [comment]
Well, the issue was that it was unreplaceable, it could have been something related to nanopaste, but the roboticist couldn't replace my parts, they staid damaged

**Comment by ComicIronic** [comment]
Parts stay damaged if components get broken before they are replaced, you have to replace a component and then bring it back up to full health with nanopaste to truly remove damage.

**Comment by PJB3005** [comment]
Hm, well I recall having the roboticist use nanopaste on me after replacing the component

**Comment by gbasood** [comment]
Can't reproduce anymore
