### ISSUE TITLE
Reset AI board wrong description

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4452]
"A 'reset' AI module: 'Clears all laws except for the core three.'"

This does not take into account a previously purged AI, in which case this board will cause the AI to have no laws, or an AI with other than 3 core laws.

**Comment by dylanstrategie** [comment]
This description is dumb as bricks. It should read "Purges all non-core laws" (if not mistaken, I'm pretty sure Reset never defaults to Asimov core laws)
