### ISSUE TITLE
Would it be better to have a spell for ghosts to return to their bodies?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4453]
I'm not sure if it's the best idea because there's already a notification in textchat when you've been defibbed to return to body.  But it'd be a lot nicer for ghosts to have a easy to hit button next to Boo ot return to their corpse rather than digging though the ghost menu with 20 different verbs.  

That in itself is adding more stuff to the spell menu and could be doing the same thing.  But I like the idea and want to float it here on github.  Would that be nice to have to so you can instantly leap back to corpse without any fumbling around?  On one hand ghosts have less need for screen space since they won't be manipulating any of the usual UI a living person would like their backpack or paperdoll slots.  But on the other hand it does add to clutter.

**Comment by dylanstrategie** [comment]
The message should provide a link that automatically fires that verb when clicked, cluttering the spell list is not a good idea, especially since I wish for ghosts to have more spook powers in the future

**Comment by 9600bauds** [comment]
Capital idea Dylan, working on it

**Comment by Probe1** [comment]
See this is why I self label @clusterfack it was an idea, not a request.  YOU SUCK.

kidding, this has run its course.

**Comment by 9600bauds** [comment]
Acknowledging this in PR soon(tm)
