### ISSUE TITLE
(WEB REPORT BY: fireice2k8 REMOTE: 198.245.63.50:7777) Destination tagger typo?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4454]
Revision: 9467860a201b1c31d38e83ffbcfcd91cb6f57e83
>General description of the issue
Destination tagger has some bugged text when you first(?) use it

>What you expected to happen
'*HYDROPONICS*' coming up when I tag an item

>What actually happened
<span class='notice'>*HYDROPONICS*

>Steps to reproduce if possible
pick up destitagger, set to a destination, tag something.
doesn't seem to happen on repeat attempts, seems really inconsistent.

**Comment by d3athrow** [comment]
Tested several different ones locally and could not reproduce.

**Comment by Zth--** [comment]
Well, this one should be closed already
