### ISSUE TITLE
Expand cortical stacks to the crew

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#4457]
Cortical stacks are something that are in-game but not universally understood by the playerbase. You mostly find them when digging around in Vox heads, are a legacy feature from Bay, and despite their existence are made redundant by the incredible powers of the cloning machine.

(basically just 1 2 and 3, the rest are just ideas for future expansion)
What I'm wondering though, is how unbalanced/ridiculous would it be to:

**1)**  - Make cortical stacks contain the ghost (May already be entirely coded and implemented at this very moment), but be ignored by cloners. Cloners would simply look at the meat brain and go "Nothin' there"

Brain damage would still affect the person, but it would be the completely capable and fine ghost trying to communicate through the damaged brain, so essentially similar to being a meatbrain, and functionally the same result.

Since cortical stacks are shielded and based around magic diamond tech or whatever, EMPs wouldn't affect them directly. (as is the case now)

**2)** - Have cortical stacks a thing that science can make with enough materials and research, with them having a built in SPS that can be disabled/enabled. 

**3)** - Have a machine that handles the implantation/uploading, functionally like a cloning scanner. Built by science. Step into machine, have someone fiddle with a nearby console and upload a backup to (Vulnerable) servers (Ostensibly R&D). You would separately also be able to insert just a cortical stack that contains a ghost to achieve the same thing.

Through quantum space magic, the device can then tell if that person gets dead-ed, and would allow you to insert an empty cortical stack and a living being of some sort into the machine, and POP goes the stack.

This device can also remove cortical stacks painlessly from organics.
## 

4)  _(Optional and a bit silly)_ - Still retain the meat brain's ability to contain a ghost, in situations where a ghost containing stack is installed into a ghost-containing organic. (so you can have a situation where two ghosts exist in one mob. Probably a byond nightmare. )  Additionally having cloners only pick up on the meatbrain ghost.

5) _(Optional)_ - Have stacks able to be put into/removed from almost any neurologically compatible living host. Ie: Ian, a chicken, a Catbeast, Someone's Mom, etc.

6) _(Optional)_ - Have the potential for even higher science allowing for a built-in radio functionality, super high science could have short range machinery operation (though still respecting ID levels)

7)  _(Optional)_ - Have surgery no longer work for implanting cortical stacks. Something about the fine nano and picoscale wiring that surgical startrek hands just can't do. 

The cortical stack can be put in; just won't have any control over the mob. Useful for smuggling.

 Removing them works just fine though.

8) _(Optional)_ - Uploading someone, killing them, downloading them into a cortical stack, and stuffing them in your pockets counts for abduction and/or killing objectives for the syndicate

9)  _(Optional)_ - Cortical stacks can be loaded/unloaded into/from empty ai cores, but ai cards don't work for these individuals (The ai card tells you to pop the stack rather than swipe, if you try). Ostensibly the action would be about as difficult/easy as using an ai card. Laws would also apply the same as legacy methods of making AI.

10)  _(Optional)_ - Ability to do as 9, but for mechs and cyborgs as well.

11)  _(Optional?)_ - Some sort of identity md5-like Hash and tools/a database for assisting the detective in adapting to these new transhuman times.

12)  _(Super Optional)_ - Super high level science ability to make an enhanced version of the bioprinter. This device can do all of the bioprinter things, but can also accept biomass and chemicals and output a customized living body to your specifications (Though, printing/growing takes some time). Can also have a cortical stack inserted so the printed being comes out with one implanted if a suitable ghost in the database that is available and chosen.

13)  _(Super optional addon to 12)_ - A device analyzer-like tool that works for scanning lifeforms into the upgraded bioprinter to expand its available morphs.  Also the ability to set the printer to automated mode (off by default), so ghosts can print their own morphs out (if there's material and free stacks left in the printer, anyways.)     Note to clear confusion: Only ghosts that are already stored in the database. Stacks are not posibrains.

This one sounds kind of powerful until you count that someone will have to actually build the machine in the first place, set it up, turn it onto automated mode, keep it operational and safe from dangerous hands/clowns that might want to print out catbeasts instead, and restock the machine with materials and expensive stacks.

14)  _(Optional)_ - Lore and future expansion/adoption of this to Nanotrasen. Safeguard its cheap labour further by keeping/transmitting their ghosts digitally, and have them built/unbuilt on site rather than spending resources shipping them around.  Turn permabrig into a ghost server.

15)  _(Ultra optional addon to 14)_ - Ghost space for uploaded ghosts with no presence in meatspace. They could have a simulated zlevel all to themselves to dick around on. Permabrig could have a virtual component.

**Comment by Ephx1** [comment]
![dizzy](https://cloud.githubusercontent.com/assets/6224074/7645383/699d23f4-fa82-11e4-9a0b-169e32b359ea.gif)
I thought Cortical Stacks were just the magical vox brains that were made from science.

**Comment by Midaychi** [comment]
Well, I was going from your wiki lore page for Vox, which was sort of a summarized tl;dr version of bay lore for them.

In there, the Vox bodies themselves are grown and have cortical stacks implanted into them, and the actual memories and consiousness is imparted via bluspace link to their tree things.

In the case of this, I was just trying to phrase it in a 'you can accomplish this as a crew member' way. 

Another way you could possibly do it is to have basic cortical stacks be an optional round start thing, have upgraded versions through science, and just have them as an alternative to cloning.

**Comment by Midaychi** [comment]
General gist is that this'd be an opportunity to implement/involve digitization of crew and the various scifi elements and ramifications involved.

**Comment by Ephx1** [comment]
Yeah I know all that, but I'm not entirely certain why cortical stacks need to be put into everything else.
I mean, they're really REALLY neat ideas don't get me wrong, but this seems like just an odd form of cloning plus positronic brains. And a creature that can flawlessly move from machine to creature is incredibly frightening.

**Comment by Midaychi** [comment]
It should be frightening, as that is the point. 

That said, you still require help to do so, so it's not exactly "Flawless."
 
The only part of the stack-being suggestions above that you could do entirely by yourself is the advanced bioprinter part, and even then you'd need help from someone or something to push the upload button, and you'd need to keep the machine stocked and set up and powered and safe.

Most of the steps require outside help to transfer from one medium to another, to upload, to download, to create. A number of them require some effort put into science and materials as well.

It'd be a lot different if it were done more digitally. (like for instance, the Vox in bay lore) This is sort of the analogue early-adoption era method of doing this that Nanotrasen would be struggling with. (even in bay lore)

**Comment by Midaychi** [comment]
It's the next sci-fi step, a deepening of the paranoia in an encroaching age, and I dunno it'd be super fun to implant the mime into a xenomorph.

**Comment by Ephx1** [comment]
Oh I see, this is leaning a bit more to the RP side of things. (insert /vg/ roleplaying joke here)
Aside from the obvious backstory and situations that arise from it we can accomplish this all with just normal MMI trickery. But I think I'm starting to like it more.
I would love your optional ideas put in, which are great. Like upgrading yourself would be interesting and something else to work towards with your short range machine usage and ghost z-level idea.

Three questions though:
Roundstart stack machine thing somewhere on station?
Will cortical stacks be able to just pluck a ghost from anyone like a posibrain?
What would the electronic z-level contain?

**Comment by Midaychi** [comment]
There probably wouldn't be a roundstart stack machine, but if there were I'd replace cloning with it. Probably have the basic cortical stack the standard edition (with meatbrains being an optional choice at character gen) with fancy ones makeable by science.

You'd have to actually upload someone into the servers first before you can download them into a stack, so no, you'd still have to use a posibrain for ghost joining.

The last one is interesting. I'd guess it's up to what the mappers want to put into it, but I'd assume it'd be a lot like goon's virtual reality. Could get fancy with it and make it some sort of digital representation of <insert favorite livable planet here>, or some sort of science-oriented datamining endeavor, or just a really big gokart track.

**Comment by Ephx1** [comment]
Ah good, I was worried about the second one, Posibrains are already very limited and being able to make an entirely new creature with exchangeable brain would completely phase them out.

On the electronic z-level bit, perhaps if they are there, and there is a suitable bioprinter, they could use it as a sort of teleport with an in z-level console to get them a new body. It would be fairly interesting to see an antag escape into cyberspace just to make a new body elsewhere and run away.

**Comment by Midaychi** [comment]
Well yeah that would be pretty cool, but you'd need an actual functioning meatspace printer to do it to. Also, possibility of escaping via hacking commsat to beam yourself to the syndicate if your objectives are completed and support that. Probably wouldn't work with physical retrieval missions like steal magboots though.

**Comment by Midaychi** [comment]
16) _(Optional)_ Ability to build a semi-modular robot form and install a cortical stack to it. Something similar to IPCs from bay/paradise but less snowflake and more chainsaws.

**Comment by PJB3005** [comment]
Vox lore YAAAAAY

**Comment by Exxion** [comment]
As far as I can tell, /vg/'s cortical stacks currently do nothing whatsoever
They consist of three lines of code

**Comment by Midaychi** [comment]
That explains a lot, actually.

**Comment by ihadtoregisterforthis** [comment]
![heh](https://cloud.githubusercontent.com/assets/13305885/12130543/03162668-b3ea-11e5-8464-3db3292d761a.jpg)
