### ISSUE TITLE
Vox/syndicate need ion-type guns that fit in backpacks.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4459]
At the moment ion rifles are very large and NEVER used by syndies or vox because they have to haul that shit everywhere and its a pain in the ass. Honestly I would prefer if flashes were given over ion rifles because a flash would be much more helpful for an already gun toting space invader.

**Comment by Midaychi** [comment]
Telescopic ion rifle?

**Comment by Ephx1** [comment]
No no no, give them a radical rolled up Ion Whip with like, 4 tile range that fits on a belt or pocket.

**Comment by dylanstrategie** [comment]
Give them some sort of ion pistol. Either that or a shitload of EMP grenades, the second being much easier to introduce because it already exists

**Comment by PJB3005** [comment]
Yeah, I agree, the ion rifle is too bulky for nuke ops/vox

**Comment by CptWad** [comment]
Like a sec taser gun but fro borgs? Yeah seems perfect, four shots is plenty.
Also is it just me or are stuns for borgs shorter than stuns for carbons? Its barely enough time to pop borgs open before they are ready to slap you with whatever weapons they have.

**Comment by Ephx1** [comment]
They are, the usual affair is to stun them with say, an Ion, then spam flashes on them while repeatedly being beaten or opened up.

**Comment by CptWad** [comment]
Yeah but voxraiders/syndies dont get flashes, which sucks.

**Comment by Ephx1** [comment]
Really? That's odd, if no Mini-ion is going to be made, then Flashes certainly need to be given to both.
Especially Vox, because of their Inviolate rules.

**Comment by Skullyton** [comment]
Ion pistols when?
