### ISSUE TITLE
Clicking a downed person with help intent on while holding a pickaxe robusts them

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#4460]
Pretty self explanatory. Not sure if this was intended or not but it would be nice if I wasn't accidentally killing people I was trying to help.

**Comment by Ephx1** [comment]
I'm not entirely sure what you expected.
Any item that doesn't have an effect on people usually defaults to just hitting them, Paper, Backpacks, Shoes.

**Comment by mrpain666** [comment]
I did it with the intent of shaking them up.

But if it really isnt a bug I'll just close it.

**Comment by Ephx1** [comment]
This could still be a feature request though, with the change of intent changing if items hit or not.
It would certainly help with what you experienced when trying to assist.
