### ISSUE TITLE
Vox raiders have no welding protection available in their ship

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4469]
You would say "You could use a welding helmet!" but that dont help in space.

**Comment by dylanstrategie** [comment]
Many rig helmets are very oddly not welder protected (for instance the Captain's RIG Helmet)

I would recommend putting the eyeproc values directly on the base RIG and Vox Pressure Suit helmets and only modifying childrens when needed, to avoid major oversights like those

**Comment by CptWad** [comment]
>Captains RIG

Its not a rig. Its a space helmet. The reason captains armor/gloves are not tuned with engineering is because the captain should simply look fabulous and be armor protected but not to engineers job. Also prevents greyshirt McBeat from stealing more overpowered shit at the start of the round.

**Comment by ComicIronic** [comment]
You could use welding goggles.

**Comment by PJB3005** [comment]
Welding goggles are way to rare for that, what, there's a couple in mechanics and a pair in robotics?

**Comment by ComicIronic** [comment]
And the infinite ones RnD can push out for something like Materials 2. With no tint.

NO TINT.

**Comment by CptWad** [comment]
Yeah but I am talking about vox raiders

**Comment by PJB3005** [comment]
oh, yeah, those, right.

**Comment by ComicIronic** [comment]
Add welding goggles to the raider locker or somewhere on the Skipjack, don't give station Vox more free stuff.

**Comment by CptWad** [comment]
Updated title because its been a while and weldin protection dont need to be the pressure suits
