### ISSUE TITLE
??Posi brains can hear and speak sol common around them but not over raidos??

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4477]
dude what

**Comment by dylanstrategie** [comment]
Can they not understand the radio, can they not speak on radios at all or is it just that they don't have a radio ?

**Comment by clusterfack** [comment]
Posibrains don't have radios

**Comment by PJB3005** [comment]
Well, I was an MMI once, and I could speak sol common, but I couldn't understand the radio

**Comment by Ephx1** [comment]
Basically as a Positronic Brain, you can understand those around you.
But, usually someone near you will have a headset that you can hear the radio on.
All speech on that radio will be gibberish to them.

**Comment by CptWad** [comment]
Yeah what @PJB3005 and @Ephx1 said. as a posibrain you cannot understand anything over the raido.
