### ISSUE TITLE
Object say() causing language runtimes

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#4487]
runtime error: undefined variable /obj/machinery/vending/snack/var/universal_speak
proc name: receive information (/obj/machinery/telecomms/server/receive_information)
  source file: telecomunications.dm,572
  usr: null
  src: Common Server (/obj/machinery/telecomms/server/presets/common)
  call stack:
Common Server (/obj/machinery/telecomms/server/presets/common): receive information(/datum/signal (/datum/signal), Bus Mainframe (/obj/machinery/telecomms/bus/preset_four))
Bus Mainframe (/obj/machinery/telecomms/bus/preset_four): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/serve...", null, 20)
Bus Mainframe (/obj/machinery/telecomms/bus/preset_four): receive information(/datum/signal (/datum/signal), Processor Unit (/obj/machinery/telecomms/processor/preset_four))
Processor Unit (/obj/machinery/telecomms/processor/preset_four): relay direct information(/datum/signal (/datum/signal), Bus Mainframe (/obj/machinery/telecomms/bus/preset_four))
Processor Unit (/obj/machinery/telecomms/processor/preset_four): receive information(/datum/signal (/datum/signal), Bus Mainframe (/obj/machinery/telecomms/bus/preset_four))
Bus Mainframe (/obj/machinery/telecomms/bus/preset_four): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/proce...", null, 20)
Bus Mainframe (/obj/machinery/telecomms/bus/preset_four): receive information(/datum/signal (/datum/signal), Telecommunication Hub (/obj/machinery/telecomms/hub/preset))
Telecommunication Hub (/obj/machinery/telecomms/hub/preset): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/bus", 1, 20)
Telecommunication Hub (/obj/machinery/telecomms/hub/preset): receive information(/datum/signal (/datum/signal), Subspace Receiver (/obj/machinery/telecomms/receiver/preset_right))
Subspace Receiver (/obj/machinery/telecomms/receiver/preset_right): relay information(/datum/signal (/datum/signal), "/obj/machinery/telecomms/hub", null, 20)
Subspace Receiver (/obj/machinery/telecomms/receiver/preset_right): receive signal(/datum/signal (/datum/signal))
Station Intercom (General) (/obj/item/device/radio/intercom): talk into(Getmore Chocolate Corp (/obj/machinery/vending/snack), "It\'s better then Dan\'s!", null, null)
Station Intercom (General) (/obj/item/device/radio/intercom): Hear("<span class=\'game say\'><span...", Getmore Chocolate Corp (/obj/machinery/vending/snack), null, "It\'s better then Dan\'s!", null)
Station Intercom (General) (/obj/item/device/radio/intercom): Hear("<span class=\'game say\'><span...", Getmore Chocolate Corp (/obj/machinery/vending/snack), null, "It\'s better then Dan\'s!", null)
Getmore Chocolate Corp (/obj/machinery/vending/snack): send speech("It\'s better then Dan\'s!", 7, null)
Getmore Chocolate Corp (/obj/machinery/vending/snack): say("It\'s better then Dan\'s!", null)
Getmore Chocolate Corp (/obj/machinery/vending/snack): speak("It\'s better then Dan\'s!")
Getmore Chocolate Corp (/obj/machinery/vending/snack): process()
machinery (/datum/controller/process/machinery): doWork()
machinery (/datum/controller/process/machinery): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(machinery (/datum/controller/process/machinery))

This applies to things like bhangmeter, newscaster, etc etc. It seems like all objects have the issue so its probably in the

**Comment by ComicIronic** [comment]
If this is caused by :, I will be pissed.

**Comment by clusterfack** [comment]
Also that stacktrace is why I've said in the past that telecomms/relay_information is double counted or more within total cpu and is thus not a reliable estimate of cpu cost for telecomms machines

**Comment by clusterfack** [comment]
Pomf fixed
