### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Socket Wrench for MoMMI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4491]
Not a bug but a feature request,since MoMMI can't unwrench pressurized pipes,since they don't have socket wrench

**Comment by FudgePucker** [comment]
MoMMI's can pick up socket wrenches, there's two in atmospherics and one if you hack the vender in derelict (I MADE THAT PR :D).
Socket wrenches are OP, but maybe if they get an engineering upgrade they can get it (like normal engineering borgs do) and a RCD (that might be a little overpowered to give the skittering autistic crabs that can upgrade themselves)..

**Comment by PJB3005** [comment]
Yeah, this isn't really needed, it's too powerfull

**Comment by AutismSpider** [comment]
>to powerful
>engineering borg can dope any mat it likes some thing the mommis could do in past.

Socket wrench would be fine if they ate the upgrade for it. 

no to RCD.

**Comment by Starnightx** [comment]
Sometimes i forget to add an Manifold but there is already air flowing through the pipe,so it sucks i can't unwrench the pipe to add a manifold and extend the line to another room

**Comment by FudgePucker** [comment]
A: There's a reason why distro only has about 300~ pressure in them. Its this exact reason.
B: There's socket wrenches on the station that you are.

**Comment by Shadowmech88** [comment]
There are only two on the station, which isn't enough to go around if you've got multiple MoMMIs and atmos techs.
Socket wrenches are certainly powerful, but does that matter in the context of MoMMIs? It isn't like borgs where one has to worry about a malf borg now being able to go around fucking up the station pressure just by unwrenching pipes or deconstructing firelocks, MoMMIs exist only to improve the station.
I suppose it could do quite a bit of damage in the hands of an emagged MoMMI, but they could accomplish the same thing by just grabbing the socket wrench from Atmos.
This is more of a convenience thing than anything. Sure MoMMIs have access to socket wrenches, but it's a hassle having to carry them around separately or go retrieve one if you discover you need one while in the middle of repairs. A MoMMI's ability to carry toolboxes doesn't mean it doesn't get built-in wrenches and whatnot, so why would a MoMMI's ability to retrieve the socket wrenches from Atmos (which are intended for atmos techs, by the way) mean it shouldn't get a built-in socket wrench?

**Comment by dylanstrategie** [comment]
You should be able to obtain socket wrenches in some manner that isn't trying to grab the limited supply in Atmospherics or praying to the gods

Also gas leaking out of open pipes should be implemented

**Comment by TermedClepe** [comment]
I never understood this problem with socket wrenches being too op.

You can already deconstruct vents/scrubbers by just hacking the air alarm and link anything directly into any air loop.

Cargo can on roundstart absolutely fuck up the entire station air, it takes less than 10 minutes and just access to an autolathe.

**Comment by PJB3005** [comment]
How would cargo be able to fully fuck up the station's air in 10 minutes?

**Comment by TermedClepe** [comment]
You can filter pure oxygen from air loop into a tiny room, throw a lighter in, dump entire fuel tank worth of fuel in it with a fire extinguisher while scrubbing the hot co2 back into the air loop.

I said cargo because they can print an RPD right away.

**Comment by FudgePucker** [comment]
Don't forget the two plasma canisters in vox outpost you can walk to and bring back.
Also, plasma large canister below cargo.
In fact that right there is a good reason to not have socket wrenches from autolathes or order able from cargo.

**Comment by TermedClepe** [comment]
@FudgePucker 

You can wire them directly to distro without a socket wrench already, it wont even take longer.
