### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Spess Atmos Pressure/Toxins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4492]
I don't know why but some closed rooms without Air Alarm (like derelict) or new ones you made with blueprints,when closed starts to generate pressure and when you some type of ignition occurs like when RPD Flicks it get caught on fire,and the fire doesn't cease until you open a breach,but it start over again when you close the breach,i can't explain exactly you must try it yourself

**Comment by clusterfack** [comment]
Cant garner any useful information from this to fix it, 
>i can't explain exactly you must try it yourself

Is right
