### ISSUE TITLE
There are no donuts left in the box

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#4493]
![](http://puu.sh/hPR17/afbd343daf.png)

**Comment by Probe1** [comment]
Well?  Were there any donuts in there?  

(probably related to https://github.com/d3athrow/vgstation13/pull/4412)

**Comment by NigglyWiggly** [comment]
>All matchboxes are now fancy storages and contain 21 matches to start with (I'm aware it's nowhere near a real matchbox's contents, but 100-ish matches is pure overkill)

Yep, that's probably it.

**Comment by ComicIronic** [comment]
It's not wrong.

Not wrong at all.

**Comment by clusterfack** [comment]
Phew I was worried you meant Box had no donuts, now that would have been a travesty

**Comment by 9600bauds** [comment]
Well it's technically true

**Comment by Exxion** [comment]
Yep, #4412
Dylan forgot to specify an icon_type (no idea why it has such a misleading name) for matchboxes so they inherit "donut"

**Comment by dylanstrategie** [comment]
Goddamnit, alright, give me a bit
