### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Defficiency needs a Crew Monitoring Computer in the lobby

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4494]
Medbay currently has only medical records computer in their lobby. The only location of a crew monitoring computer is in the Paramedic's room.

Paramedics never do their fucking job in the first place. As someone who has played several months of nothing but medbay, the first people to fuck off is always the paramedics because its a job that people who dont know/care about medbay always flock to.

There needs to be another in the lobby, and theres a perfectly good spot right there in the lobby. http://a.pomf.se/xosenj.PNG
FUCK YOU DUNY

**Comment by Probe1** [comment]
I asked Duny for this 5 months ago so uh, if any prospective mappers want to step up and take a swing  this is a great opportunity because I feel like it's not happening from him.

**Comment by dylanstrategie** [comment]
>Modifying Duny's map without his permission for anything but compatibility fixes

It's like you got tired of life
