### ISSUE TITLE
Is there a "how to" for making the Jukebox work?

### ISSUE THREAD

**Issue by abcdicks** [d3athrow/vgstation13#4495]
I think I may need an index.php, but it's nowhere to be found.

**Comment by CptWad** [comment]
Oh for your own server?
Its more of a contact pomf and solve your woes sort of thing

**Comment by PJB3005** [comment]
The media server used is in some repo on N3X15' account, I'll get it for ya

**Comment by abcdicks** [comment]
Thanks! Thing is, I'm quite stupid.

>https://github.com/N3X15/SS13-media/blob/master/playlists.json
This is where I must make the playlist? How should I do it? Can you make an example? 

And where should I upload the musics?

**Comment by PJB3005** [comment]
I do not know, ask pomf about that.

@d3athrow

**Comment by d3athrow** [comment]
https://github.com/d3athrow/ss13-media-converter

**Comment by PJB3005** [comment]
Closing because this really isn't an issue. And technically has been resolved.
