### ISSUE TITLE
(WEB REPORT BY: anacondawarriorsupercommando REMOTE: 198.245.63.50:7777) Burn chamber gasses dissapearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4497]
I expected the gas chamber to be filled with the plasma/oxy mixture i made but the gasses just dissapeared and it wouldnt burn. Gasses have been buggy for awhile now

**Comment by PJB3005** [comment]
Is it the burn chamber in engineering?

see #4243
