### ISSUE TITLE
vgstation13.dme when.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4504]

**Comment by dylanstrategie** [comment]
I don't know, ask Pomf. But the thing is, that would need a significant effort to implement, and a feature freeze

**Comment by clusterfack** [comment]
At the base level its just replacing baystation12.dme with vgstation13.dme in the watchdog, how much else actually uses the .dme name as reference.

**Comment by PJB3005** [comment]
Travis, watchdog, ...can't think of anything else

**Comment by PJB3005** [comment]
Why is this labelled as t-thanks BYOND? Doesn't sound like BYOND's fault to me

**Comment by clusterfack** [comment]
it happened
