### ISSUE TITLE
Vote order is shuffled, shuffle hotkeys, menus and all tabs/buttons for consistency

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4507]
It is important to be consistent in UI design, now that some parts are randomized and others aren't, it's very unintuitive.

We wouldn't want players metagaming UI from roundstart, would we?

https://github.com/d3athrow/vgstation13/commit/6db380332c9fba726597e304aafd291b7af3a8b8

**Comment by clusterfack** [comment]
That rage

**Comment by TermedClepe** [comment]
@clusterfack 
Great argument, let me get back to you on that.

**Comment by PJB3005** [comment]
Yeah, you have to do research on what verb does what.

Maybe eject sleeper is suicide? who knows?

**Comment by Exxion** [comment]
Am I missing something?
Why are you pissed about vote order being shuffled?

**Comment by TermedClepe** [comment]
@Exxion

Because the only reason it was changed was to trick people for a few rounds to vote another map unwillingly. That's shit coding.

**Comment by PJB3005** [comment]
Yes, but it worked, which shows the issue with the current voting system: nobody thinks before clicking

**Comment by Probe1** [comment]
not an issue to me.  if you want box vote for box.  don't make everyone play box every single round because people reflex vote the first thing to close the window.

**Comment by ComicIronic** [comment]
>Because the only reason it was changed was to trick people for a few rounds to vote another map unwillingly. That's shit coding.

No, it was changed to encourage people to engage with the voting process.
Sure, it had the side effect of boosting another map to the top when nobody was looking, but people now actually have to spend 2 seconds choosing a map if they care about it, and people who don't care can still just click the first option to close the window and watch griff.

**Comment by TermedClepe** [comment]
You're missing the point, people didn't vote for box automatically because it was first in the menu, they voted for it because they wanted to play box. What this did was trick them to vote for something they didn't want because of randomizing buttons. Everyone is voting box still, the only time they voted something else was when they didn't realize they voted for something else.

**Comment by Probe1** [comment]
I don't agree with that.

If they want to vote Box then nothing is there to trick them into voting for Metaclub.  The options are clearly labeled.  Their order switches each time, that's all.

**Comment by Exxion** [comment]
Agree with everyone except TermedClepe
If someone just hits a button immediately without reading what it says, they don't deserve a real vote

**Comment by dylanstrategie** [comment]
Shuffling vote options is perfectly fine. Most players know what they are voting for, and since Boxstation is what they are most familiar with, it's what they'll vote for unless they want a fuck miscellaneous round

We don't need any more things to try and force the other maps on players. If they're clearly not voting for them even after the map options are shuffled, that clearly means they're not hitting the first button in the row. Make the other maps better or give us a break

**Comment by DrCelt** [comment]
Close this. People are still voting box station, they just have to think for a second before doing so.
