### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Staff of Change can turn people into Krampus

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4510]
>Revision (Should be above if you're viewing this from ingame!)

cfcdb487cf500ec2cdf32ffb29ed986a6200a354 
>General description of the issue

Don't know if this is really intended, but apparently you can staff of change people into Krampus mobs. If I remember correctly, Krampus is basically like a test dummy, immune to everything.

**Comment by Shadowmech88** [comment]
What's the likelyhood? Personally I've never seen a Krampus transformation from a staff of change, and I don't think it's necessarily a bad thing if it's also incredibly rare to compensate.
Or maybe make a separate Krampus mob for the staff of change that isn't completely invincible, just very strong.
