### ISSUE TITLE
"Unable to connect to accounts database." in any selling machine

### ISSUE THREAD

**Issue by abcdicks** [d3athrow/vgstation13#4513]
Happens on my server.  Both the MySQL database and players2.sqlite are working fine.

**Comment by PJB3005** [comment]
Is there an accounts database on both the main station AND on centcomm?

**Comment by abcdicks** [comment]
I put it on the map and now it's returning "Unable to access account. Check security settings and try again." for any ID.

**Comment by PJB3005** [comment]
Well, check security settings and try again?

**Comment by Shadowmech88** [comment]
You're just spawning the cards in, right? Are you sure they have an account number on them?

**Comment by abcdicks** [comment]
@PJB3005 
I'm not sure how to do that.
@Shadowmech88
Both the cards I spawn or that the characters start with return that. I don't think they have. Check:
http://i.imgur.com/Y1HEKJ6.jpg

**Comment by PJB3005** [comment]
go to an ATM, you can set stuff like that there

**Comment by abcdicks** [comment]
I think the problem is that accounts aren't being created in the database. See http://i.imgur.com/Y1HEKJ6.jpg.

**Comment by PJB3005** [comment]
Do you have an accounts DB on CC?

**Comment by abcdicks** [comment]
CC?

**Comment by ComicIronic** [comment]
CentCom

**Comment by abcdicks** [comment]
Where is it .dmm file? Can't find it in maps folder.

**Comment by PJB3005** [comment]
z 2 on any map

**Comment by abcdicks** [comment]
Thanks, everyone! It works now. I thought the centcomm map was in another DMM and already had an account database on it.
