### ISSUE TITLE
Circuit imprinter bugged out, won't take acid

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4516]
>You splash the solution onto Circuit Imprinter.

worry.jpg

you just splash acid on it doesn't add it.

**Comment by 9600bauds** [comment]
what?
What container were you using?

**Comment by Probe1** [comment]
a bluespace beaker, others reported identical problems with non bluespace beakers.

**Comment by wwjnc** [comment]
I BLEW IT

**Comment by d3athrow** [comment]
ya blew it
