### ISSUE TITLE
Allow the sun to illuminate the station

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#4519]
To break it down : 
- The sun currently rotates around the station, but it's just a datum with some basic position calculation to be used by the -very- physical solar panels
- As we all know, suns have a tendency to illuminate what is in the way of their light rays
- But strangely enough, if you blow every single light on station, the entire station will be pitch dark, even the areas with huge window bays "facing the sun" (where solars would output)

Suggestion : 
- Make it so that the sun outputs light, so that if a window bay is facing directly to the sun's current position it gets illuminated
- If Vampires bathe into sunlight, fuck their shit up. Remove generic "hurt in space" and replace it with "specifically exposed by sunlight", give them an ample warning to tell them to get the fuck out of here before shit gets really bad

Since the sun is a pure datum, that might be a tad hard, but on the paper this idea seems pretty fantastic. I would personally suggest this method for coding it in : 
- Assign an obj/sun to the sun itself, that is moved with the sun itself, is always on the world borders and is completely invisible (might be a bit hard and hacky)
- Code in a very special light that uses the sun's coordinates (more advanced, and allows one to tune it to hurt vampires)
- Just make the light something like 500 luminosity (would make everything in sunlight fullbright, but it would work fine. And normally not lag since the sun updates slowly)
- Use more advanced pathfinding and fall-off so that sunlight penetrates a few tiles through the window bays (10 or so) until fully fading out. More beautiful and less lighting-controller expensive if coded properly, but complicated

**Comment by Probe1** [comment]
Seems like a very good idea.

**Comment by ComicIronic** [comment]
>constant lighting updates for a huge swathe of the station

I predict lag.

**Comment by dylanstrategie** [comment]
The sun, if I'm not mistaken, updates periodically. Besides, it's one lighting entity. In theory, it can't do that much damage

The old floodlight had a luminosity of 100 and behaved, let's say correctly

**Comment by clusterfack** [comment]
Yeah I wanted this too, but it better not start lagging us up

**Comment by Exxion** [comment]
Not sure how lighting works and therefore if this would be possible, but the sun should illuminate along parallel lines rather than lines radiating out from the center of a circle

**Comment by gbasood** [comment]
Could pre-calculate sun-affected areas of the station and only update when a tile that was previously affected changes (wall on outside of the station goes away, for instance)

It'd be cool to have this but I think that no matter what's done to implement it, it will be more lag than it's worth.

**Comment by Exxion** [comment]
I'm pretty sure that pre-calculating thing is how cameras work
There's already code present that determines which tiles a camera can see
Maybe the same code can be repurposed to find which tiles the sun illuminates

**Comment by Midaychi** [comment]
If the bay lighting system gets implemented, implementing this should become a lot easier.

**Comment by IratePirate** [comment]
I want a Sunshine event.
