### ISSUE TITLE
Central Primary Hallway Air Scrubber #7 is off at round start

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4520]
how did such a thing even happen 
 
![ss 2015-05-17 at 05 53 20](https://cloud.githubusercontent.com/assets/8550416/7672534/d100fa64-fcc3-11e4-9043-176cd9534af9.png)

**Comment by dylanstrategie** [comment]
Unlinked at roundstart, my map PR fixes that at #4490

**Comment by Exxion** [comment]
Scrubber in vox trading post hallway is also off at roundstart and NONE of them are set to filter oxygen

**Comment by PJB3005** [comment]
^

Yep, none.
