### ISSUE TITLE
OH GOD IT'S LOOSE - PANIC: Donut Boxes can have no donuts in them but have the sprite of a box with 4 (FOUR) donuts in them

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#4522]
THIS IS BROKEN

HOTFIX ASAP BEFORE IT'S ABUSED

**Comment by dylanstrategie** [comment]
What

**Comment by SangriaMonkey** [comment]
Cig packs gain a cigarette when you put a lighter in there.

**Comment by Probe1** [comment]
how does this keep happening?

**Comment by d3athrow** [comment]
how could dis happen

**Comment by 9600bauds** [comment]
how is hapen

**Comment by clusterfack** [comment]
HOLY SHIT SOMEONE DID REALLY REMOVE THE DONUTS FROM BOX, THIS IS A TRAVESTY

**Comment by Probe1** [comment]
that's as many as four ones.  and that's terrible.

**Comment by Exxion** [comment]
I kind of expected to see some stupid and glaring cause in the code, but I can't
The cigarette box magically transmuting a lighter to a cigarette in the icon is easy to figure out, but the four donuts issue isn't.

**Comment by clusterfack** [comment]
Well it would be easier if the reporter included any steps to reproduce instead of just saying 'this happened once'

**Comment by DrCelt** [comment]
This happened once, sorry. Might be to do with the Diona which took donuts out but otherwise I've no clue. Guess this is to be closed then.

**Comment by Exxion** [comment]
How quickly were the donuts removed? Maybe BYOND just decided not to cooperate and properly update the icon.
Wait, aren't you an admin, @DrCelt? Couldn't you have viewed the variables?

**Comment by Probe1** [comment]
He's a leader, not a reader.

**Comment by DrCelt** [comment]
I was a captain so I was deadminned.
