### ISSUE TITLE
Circuit Imprinter

### ISSUE THREAD

**Issue by Starnightx** [d3athrow/vgstation13#4524]
I don't know who,but i know someone fucked the code,and the circuit imprinter isn't accepting any sulphuric acid anymore,if you try to load it you simply splash the contents of the beaker on it .

Try loading it with sulphuric acid is the only way to reproduce

**Comment by Exxion** [comment]
This was allegedly fixed two hours ago by 590848fe822a3cfd5ca56a1c3701175e1fdf985e

**Comment by d3athrow** [comment]
This is fixed.
