### ISSUE TITLE
There Should be More Than One Font Choice For Writing on Paper

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4526]
I had this thought while writing a book for the server. Quite frankly, the default font for paper is ugly for large bodies of text., and the font size is much larger than necessary. I noticed while fiddling with books that the font used for the "content" option while writing into an already-bound book looks pretty nice for a large book, but you can't use any formatting in it, even something as simple as line breaks, and I don't know if that was intentional or an oversight or whatever but it's simpler to just ask for this.
Additional fonts also have applications for things like if people want to write/sign in cursive, since cursive fonts exist.
If I'm not mistaken, HTML already has support for changing the font of text based on what tag you surround it with, so it wouldn't be difficult to give that functionality to paper since it uses HTML, right?

Also Niggly suggested that the clown be unable to write in anything other than comic sans.

**Comment by mrpain666** [comment]
Yes.

YES.

Clowns should be forced to speak and write in comic sans.

**Comment by Exxion** [comment]
Make handwriting a gene stored in the UE or whatever and, similarly to the clumsy SE, force that to be comic sans in clowns
Or something

**Comment by Probe1** [comment]
:+1:

**Comment by Shadowmech88** [comment]
This was fixed.
