### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Jester ID and PDA not spawning correctly at round start

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4527]
76c1de7bae1092182fe4457cd6071c2ff0943d3f

Spawning as jester instead of clown spawns you with an ID that works but with no name just says ID (jester)and a pda that just says jester and doesn't allow you to use your ID on it. I had to get an admin to fix my ID.

Test it out by playing as a jester instead of clown

**Comment by d3athrow** [comment]
Not seeing anything that should  cause this

**Comment by d3athrow** [comment]
Can't reproduce locally.

**Comment by Exxion** [comment]
Probably some obscure issue with the players database file being weird, because this sounds *exactly* like what happens if you manage not to give your character a name
I was under the impression that that could only happen locally, though

**Comment by clusterfack** [comment]
Yeah something to do with the first time a client connects with no name or some shit? Ah well, I think that runtime was fixed anyway (by me or pomf)
