### ISSUE TITLE
High tickrate makes it impossible to move properly

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4528]
Since fucking with tick rate is the newest epic thing to do that can't be done on test server:

Too high tick rate makes me unable to move less than 2 tiles, meaning it's impossible to turn corners while space walking around station, or to actually reenter station if the airlock is on an odd tile.

**Comment by IratePirate** [comment]
High tickrate is good, but there should be a slight decrease in movement speed to compensate.

**Comment by clusterfack** [comment]
There already is a system in place for that, theres a bug where it doesn't work for ghosts however due to the fact someone put ghost move before movement delay check
