### ISSUE TITLE
Stun Prods (at least) still stun even if they fail the dodge check (X misses !)

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#4533]
Honk

**Comment by Shadowmech88** [comment]
If I remember correctly, they only make the dodge check on harm intent. If you miss, you won't deal any damage, but you'll still stun them.
It wouldn't really make any sense for you to never be able to miss a stun on help, disarm, or grab intent, but then suddenly become capable of missing stuns on harm intent.

**Comment by ComicIronic** [comment]
The dodge chance is for harmbaton, not for the stun itself.

**Comment by dylanstrategie** [comment]
Then maybe extend the miss to the stun baton's regular function ?

**Comment by 9600bauds** [comment]
I don't think this is much of a balance question and moreof a clear bug

**Comment by Exxion** [comment]
Isn't there already an issue about this?
