### ISSUE TITLE
Can't Make Paragraphs When Writing in Books

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4537]
More specifically, one cannot make line breaks. I was originally just going to bear with this but I've been testing it more and it's bugging me too much now. HTML isn't registered so [br] just shows up in the book instead of breaking the line, and enter, Alt+010, and Alt+013 all turn into # when reading the book, despite showing up as a line break in the input window. The alt codes in particular are curious because Alt+255 registers and shows up fine in the book, as do other alt code characters, it's just alt codes that cause line breaks that don't work.
Pictures for your viewing pleasure.
![books 1](https://cloud.githubusercontent.com/assets/3991927/7692439/2821e7b0-fd8a-11e4-8e1c-7dfb243d3079.PNG)
![books 2](https://cloud.githubusercontent.com/assets/3991927/7692442/2b4e8204-fd8a-11e4-971b-e041b218f2a3.PNG)
![books 3](https://cloud.githubusercontent.com/assets/3991927/7692446/2d3e96da-fd8a-11e4-9ed5-f61b478e4f30.PNG)
In which I test enter, Alt+010, Alt+013, a number of spaces between two words, and a number of Alt+255 characters between two words.
Pomf said that text written in books doesn't get passed through the paper parser for reasons related to people putting malicious code in books, and in the code for library items the sanitize command is used on whatever text is entered which is likely what causes the breaks to be converted into pound symbols.

Anyway, I definitely think something should be fixed so that books at least have the ability to break lines. They don't need all the fancy formatting paper has with large and small text and horizontal rules and whatnot, but the ability to make paragraphs is pretty much a necessity for books.
Actually now that I think about it, there also isn't any way to insert tabs other than just using four or five Alt+255 characters as a replacement, so tab functionality would also be nice. But that's all that writing in books really needs.

**Comment by gbasood** [comment]
>Pomf said that text written in books doesn't get passed through the paper parser for reasons related to people putting malicious code in books, and in the code for library items the sanitize command is used on whatever text is entered which is likely what causes the breaks to be converted into pound symbols.

So an entirely new parser would need to be made? If the only feature that's required is newlines and tabs, it'd be fairly simple. But if you're looking for HTML-style paragraphs that's going to be a bit more complicated.

**Comment by Shadowmech88** [comment]
No longer relevant with the new font capability.
