### ISSUE TITLE
(WEB REPORT BY: curver REMOTE: 198.245.63.50:7777) Vox dart gun

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4538]
32cdaf2bcf12128af06a667b5da03582d3e6c06c 
Starting as Vox raider and using a Vox dart gun, you have no indication that you have to set the gun to either chloral or sleep tox. Result: entire rounds are completely fucked up by shooting empty syringes at people.

Thank you very much.

**Comment by CptWad** [comment]
Dartguns were always cool but they function very poorly. They are made to be buffed syringe guns that fire chemicals of your choosing. However I never had the time to really test the limits of it. not to mention I dont think you can and beakers to it even after you have ejected them.
Either they need to be simplified or streamlined and functional. They are powerful if you mix the chemicals. Not many people get to play vox raiders so its another thing that makes failure easy for them.
