### ISSUE TITLE
On The Pointlessness Of All But The Most Select Of Mining Equipment

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4540]
The precious metal pickaxes are terrible. Gold&silver are only found in mining complexes, which means you already have something better than them by the time you find them.
The diamond pickaxe is a special mention in that it can be made in a Protolathe, which might trick some none-the-wiser scientist into making it... But it's twice as slow as a diamond drill and cannot dig walls or soil. It doesn't even do more damage. Why?
The plasma cutter: Now this is a weird one. It's just as fast as a jackhammer, but that means if you can get the plasma to make R&D construct one, you could instead skip the middleman and redeem the plasma to buy a jackhammer. The weird part is that it also welds walls at half the speed of a welder. I'm struggling to think what use could I give that, since I can just get a welder or a diamond drill instead. Disappointingly, it's not even good at cutting limbs.

The resonator is way too tricky and risky to use (requires getting up close and careful timing) when you can just get a gun that does the killing better, and it's too unwieldy to use as pickaxe replacement when you can get a jackhammer instead. It'd be half-decent if it triggered when something walks over it, but then it'd be absolutely obscene against players.
Nanotrasen Minebot: This guy seems good on paper, but he's dumb. Really dumb. He takes a good while to realize anything is going on, loves to freeze in place for a few seconds, and is bad at following you. The best use I can give him is drag him behind myself and try to get him to pick up what I tunnel into, but I have to stop constantly for him to slowly realize he's standing over dug ores and he loves to wander off and break your grip.

Ripleys. God, Ripleys. I'm silently glad roboticists very rarely make one of these for you unless you ask them to, because I don't have the heart to tell them that it sucks. I mean, it's an awesome giant digging mech with a drill for an arm, I want to love it. But for actually mining, it's so bad. He's clunky and slow to move, sure, he's a mech, but he's also so slow to DRILL.
Here's a comparison between a Ripley with a diamond drill and a guy on foot, no hyperzine, with a diamond drill.
http://puu.sh/hSB7U/a1e4ae6106.webm
This is, not showing the time it takes to actually get your mech from and to the 'roid.
The 3 wide digging isn't even that useful, because you never need to mass-dig like the 'roid was a quarry. Most of the time you shaft mine, and when you need to clear, you have Gibtonite. I'm sorry, but even if I get a Ripley handed to me, I won't use it, because it's that bad.

What Does All Of This End Up In?
Go out, don't even bother getting a basic mining drill because it's only 33% faster than a pickaxe, strike the miniasteroid field until you have diamond, get diamond drill, if diamond drill is not available, get sonic jackhammer. That's about it, because everything else sucks.

**Comment by Probe1** [comment]
I always intended to learn coding and fix the mining bot.  I did a really neat trick with it that I'll explain.

You know how when you get kudzu and some goats, the goats eat kudzu?  Well you can also drag them and they'll eat a path of kudzu behind you.  

I took that code out and gave it to the mining bot so when you dragged them they hoovered up all the ore.  No stopping and clicking with your bag, just drill baby drill and the mining bot does the rest.

The problem I encountered which led to me never making a PR was I couldn't stop it from also picking up ore from an area around it and not just the path it was being pulled on.  So instead of a nice treat, it was OP as fuck.

**Comment by Probe1** [comment]
**Ripleys** are easy to fix, it's another thing I just never had the willingness to learn coding to do.

1.  Add a new mech item only ripleys can use.  It functions identically to the Gygax's speed mode except it's something that has to be added.  Make it cost diamonds to build to secure its place in the mid game.  It changed the ripleys step_on speed from 6 to 4.  This is a hugely significant increase.  It's limiting because of material cost, item slot limitation cost, and it doesn't do anything to save on power.  It also can't be used while mining to mine SUPER FUCKING FAST.

2.  Increase the mining speed of drills and diamond  drills which is frankly, god awful.

An added bonus idea I had written down was to let ripleys pick up canisters of gas, lockers, crates, and other large objects since that's long been a request of atmos techs and gives roboticists a reason to build mechs for engineering and cargo.  

I'd like to see it coded but I'd rather someone beat me to it and fixed those terrible hunks of shit today rather in the weeks it would take me.

**Comment by Shadowmech88** [comment]
>plasma cutter

My understanding was that it was supposed to function as a welding tool that didn't need fuel or eye protection to operate, at the cost of lower deconstructing speed. They're great for dealing with kudzu.

**Comment by CptWad** [comment]
Shadowmech is right plasmacutter has its virtues but is rarely used. Some unique buffs would be cool.
IMO pickaxes should stay for their novelty.

**Comment by dylanstrategie** [comment]
I want to overhaul Mining somewhere down the line to fix that horrible mess of Baystation base and random loot, /tg/station hostile mobs and bonus items and miscellaneous Goon stuff that has been building up for so long

**Comment by NigglyWiggly** [comment]
A big mining overhaul would finally give me an excuse to work on my megaman legends mobs and stuff, they're sort of fitting for the whole 'ancient ruins' sorta deal

**Comment by FudgePucker** [comment]
I had an idea, but it is probably just way too stupidly overpowered.
A lazarious autoinjector. You buy an empty one for 5000 credits, and you use a hivelords remains on it. You get a hivelords remains that can fit in your pocket and never goes bad.
This would be stupidly overpowered.

That's the problem with shaft miner, its a very thin rope of balance we are dealing with. They already have so much great stuff, that all the other stuff they have is just worthless. You can cut out the worthless stuff, and fill it with more important stuff, but it already has that nice strong structure. If you remove some of that important stuff, then it collapses and no one plays shaft miner.

**Comment by Probe1** [comment]
you already have that fudgepacker just pokeball a hivelord, kill it, eat the remains, laz it again, pokeball it and repeat.

**Comment by FudgePucker** [comment]
Yes, but can you do that when going into shock with a broken hand?
This would be just take the autoinjecter, click on yourself, full health instantly.

**Comment by Shadowmech88** [comment]
I'd like to see more monsters get added to the asteroid. As it stands now, even if you catch all three and a carp and a spider from the pirate ship, you still aren't able to have six unique pokemon. Cult creature doesn't count since for whatever reason it dies when you summon again.

**Comment by FudgePucker** [comment]
Actually there's 4 pokemon on the asteroid.
You are forgetting the most rare of the pokemans.

More pokemon would make it so you can give more goddies to the miners, shit it would make the job just that much more fun.
Make more monsters and make the amount larger.

**Comment by Probe1** [comment]
I would like that as well but good work went into the original 3 monsters.  They all have unique aspects that you have to deal with and are interesting, especially when you're inexperienced.  The goliath is particularly cool.  It would be nice to see more but I hope they are equally as interesting.

@FudgePucker Goldgrubs are basically flora though.  They drop nothing, they do nothing (except run).    All they're there for is to run away so you can chase them like a little kid running through a field.  Except in a cavern.  On an asteroid.  In space.  Surrounded by hideous monsters.  Basically the same thing as chasing buttflies.

**Comment by Shadowmech88** [comment]
Not to mention goldgrubs are armored to all fuck and don't even function as a good fighting tool once you capture one.
I spent probably five minutes straight lasering a goldgrub with an aegun before I got fed up and used 0-timer gibtonite on it, which finally brought it down. It was wholly unfulfilling.

**Comment by FudgePucker** [comment]
@Probe1 Yea it is going to be hard to come up with better pokemans than the ones on the asteriod.
They even work together, hivelords soak up lasers, basklisks slow you down, and goliaths kick your shit in to the next round.

**Comment by ComicIronic** [comment]
Don't goldgrubs drop ores?

**Comment by FudgePucker** [comment]
ores that they eat they multiply.
So if you do catch one you can use it to duplicate phazon and diamonds (or bananium you psychopath.)

**Comment by Shadowmech88** [comment]
Like that's remotely useful for the difficulty of catching one when you can build a duping machine in five minutes with Science access.

**Comment by NigglyWiggly** [comment]
>I would like that as well but good work went into the original 3 monsters.

This is what's keeping me from trying too hard with the megaman mobs, you can really tell that a lot was built around the original three, you get chili to combat the freezing stare of a basilisk, you can use the goliath's plates to armor your hardsuit, and the hivelords will heal you up all the way

**Comment by FudgePucker** [comment]
I mean if you try hard enough they might fit.
Just try even harder.

**Comment by ComicIronic** [comment]
Please, this is a Christian repository.

**Comment by NigglyWiggly** [comment]
Christian side hugs when

**Comment by Probe1** [comment]
When you code it, heathen.

**Comment by Probe1** [comment]
The discussion ran its course and anyone motivated to make changes did so.  Open a new issue to discuss the current state of the game.

Also @unid15 and I are about to redo the mining rooms.
