### ISSUE TITLE
(WEB REPORT BY: drcelt REMOTE: 198.245.63.50:7777) Vox cannot be French Cursed.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4557]
Self explanatory. Reproduce by using french curse on vox.

**Comment by DrCelt** [comment]
@arthurdentist

**Comment by Arthurdentist** [comment]
this is false, tested it just now myself.

**Comment by DrCelt** [comment]
@ArthurDentist Odd. Did you try talking as the vox? I used it on an RD and he was more than capable of talking straight after.

**Comment by Arthurdentist** [comment]
Tested and not at all reproducible.
