### ISSUE TITLE
(WEB REPORT BY: anonymousrex REMOTE: 198.245.63.50:7777) [Boxstation]Arrival air alarms not set properly on roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4558]
Revision: ee6043e4589fb82b2063e624bab3bb49691401d2

Arrivals vent pressures are set too high on map start, resulting in hilarity when the atmospherics distribution line is overpressurized.  Best way to reproduce this problem is to just start Boxstation up and take a peek at the air alarm's vent settings.

**Comment by Exxion** [comment]
Didn't I just fix this?
I definitely fixed one vent, but I checked for others being weird and didn't see any
I'll look again

**Comment by Exxion** [comment]
What the fuck? My fix somehow got undone.
