### ISSUE TITLE
Feature Request: Surrender Stance

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4560]
Something to make it a bit easier for Sec to trust you to not lay into them the second they drop their guard, if you decide to surrender for whatever reason.
How I envision it'd work is this:
Controlled by a verb which toggles the state
Instant to enter, requires five seconds to return to normal
Accompanied by a visual sprite change, alert in the text box, and unique inspection text when the person surrenders (I was thinking the hands-in-the-air type)
Cuffing a person who's in surrender stance is instant
While in surrender stance a person is unable to hold or use items, open bags, containers, or lockers, or use buttons. They can still use airlocks.
Text box updates with a notification if the person begins lowering their hands
Stunning doesn't interrupt the process of leaving surrender, and you can enter surrender state while stunned as a show of good faith to Sec
Forces walking to prevent yakkity sax
That's about all I can think of for now.

The goal of this is to give criminals a nicer recourse for surrender besides telling Sec on the radio and then waiting for the flashbang through the door because Sec obviously can't trust you enough to just walk in and cuff you. But if you had your hands up, and Sec had insurance that you couldn't try anything for at least five seconds AND they'd be notified if you started to, they might be more likely to be somewhat cordial with you. It'd also serve, in general use, as a way to convey the fact that you surrender to your attacker that's faster than typing, works for mute people, and provides insurance to the person you're surrendering to that you won't just pull a gun out and blow them away the second the stun wears off.

**Comment by Probe1** [comment]
Rest verb?  I like the rest verb for this situation.  It takes about 5 seconds to return to normal, changes the sprite, and other good stuff.  

It isn't theorycrafting either I've gotten other players to do it as sec.  But in all honesty I prefer holding them captive and telling them to step back.  They never see the stun coming.

**Comment by Shadowmech88** [comment]
It's true that I didn't think of the rest verb, but this would allow you to move around and open doors so you could be escorted in some manner other than with cuffs on, and could come out of places instead of forcing Sec to go in and get you. Besides, the notification that you're leaving the state is useful because it lets Sec have a couple seconds to get ready for a fight, instead of you popping up from rest stance and stunning them without them being able to see it coming. There's also the fact that it'd be visually different from just collapsing, when rest isn't, so you wouldn't need explanation that what you're doing is surrendering when you do it using this verb.

**Comment by Probe1** [comment]
Yes, that's true.  Your idea is much more encompassing than just telling them to rest.  

I think that rest is workable but it isn't as nice as yours.
