### ISSUE TITLE
(WEB REPORT BY: kylefiredemon REMOTE: 198.245.63.50:7777) Destrutive Analyzer.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4568]
73922e9be1830c714ef4209304512b32ca41f3fl

>Destrutive analyzer is jammed and the rest of the machines won't work.

>I expected that the machine would take the battery right after it was done.

>It got jammed with please wait, tried to fix it by deconning the screen, made things worst. I can't even take apart the machine to fix it.

>1. Decon something 2. Immediatly put something in the machine when it's reading the data (I used a high cap cell.) 3. remove computer screen place computer screen back in. 4.???? 5.profit.

**Comment by Probe1** [comment]
Tested it locally by putting an atmospheric analyzer into the DA, clicking deconstruct, then immediately trying to jam a high cap cell in there.  It was able to reproduce the bug.

ADMIN LOG: Process 'machinery' is probably hung.
ADMIN LOG: Process 'machinery' is HUNG.
Log: [debug] machinery process hung at tick #0. Process was unresponsive for 90.1 seconds and was restarted. Last task: 0. Last Object Type: null
Diary: [debug:diary] machinery process hung at tick #0. Process was unresponsive for 90.1 seconds and was restarted. Last task: 0. Last Object Type: null
ADMIN LOG: machinery process hung at tick #0. Process was unresponsive for 90.1 seconds and was restarted. Last task: 0. Last Object Type: null
Log: [debug] machinery process was killed at tick #0.
Diary: [debug:diary] machinery process was killed at tick #0.
ADMIN LOG: Process 'machinery' is maybe hung.
ADMIN LOG: Process 'machinery' is probably hung.

**Comment by 9600bauds** [comment]
what the fuck, I hope I didn't cause this
