### ISSUE TITLE
(WEB REPORT BY: conker327 REMOTE: 198.245.63.50:7777) Security circuit board duplicates when upgrading

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4576]
>Revision (Should be above if you're viewing this from ingame!)
c0708eeeaab3b0e4f40e013a6dc850194d27a7e7

>General description of the issue
When upgrading a Security circuit to Advanced Security circuitboard via soldering iron, the original Security board doesnt get deleted, causing duplication.

>What you expected to happen
Original board becomes Adv.Sec, only one board after upgrading.

>Steps to reproduce if possible
1-Take board
2-Use soldering iron on it
3-Observe how now there is two boards

**Comment by ComicIronic** [comment]
Duplicate of #4432
