### ISSUE TITLE
Make protolathe printed batteries start at 0 charge

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4580]
Currently all batteries once printed start at full charge, making battery chargers useless when you can just spam dozens of cells in the time it takes to charge one.

I suggest speeding up charging of batteries and making all built batteries start at 0 charge.

Borg chargers are also useless for MoMMIes since it takes less time to exchange a cell for a new fully charged one than it takes to charge at a borg charger.

**Comment by ComicIronic** [comment]
I support this.

You can actually keep RnD going forever because charge is free.
The engines are defunct, replace all cells with your infinite CentCom materials and recycling.

**Comment by 9600bauds** [comment]
Disagree with the part about MoMMIs, borg cell chargers can be upgraded to very significantly improve their charging time (MoMMIs being able to upgrade them and all) AND borg chargers are already 50% more effective on MoMMIs.
Upgraded borg chargers also have buffered energy, meaning if you have 2-3 of them you can just surf them to instantly recharge a large chunk of your battery without printing shit.

**Comment by Probe1** [comment]
oh i thought i commented on this.

The idea that you're going to replace the engines with changing power cells is infeasible because you'd need access to open apcs and there are like 5 dozen apcs on Box Station.  It would be a full time job to replace their batteries.  Yes you could get infinite power from printing power cells and replacing the one in the room you printed them.  

The solution is not to make power cells spawn empty.  The solution is to make protolathes (preferably only when printing power cells) drain much more energy than they do.

**Comment by 9600bauds** [comment]
That's not really a solution either, because then R&D would get a complete lights-out any time someone tries to print a power cell bigger than that with which the APC spawns with.

**Comment by Probe1** [comment]
only if the power was off

**Comment by 9600bauds** [comment]
My understanding was that the room APCs always recharge at a relatively slow rate, don't they? You still have a bottleneck in the form of the physical battery inside the APC

**Comment by TermedClepe** [comment]
I don't see the issue with cell chargers being made a lot faster. They have no use as it is outside of recharging ghetto stun prods once in a blue moon, and even that is better done at a regular weapon charger.

A hyper cell should take some fraction of a minute to fully charge, draining equivalent power from the network as it charges. Given the time scale the rest of the game is in, it would fit right in.

**Comment by Probe1** [comment]
I don't know how the code works but I've never seen an apc drain because there were too many machines/power draw in it.
