### ISSUE TITLE
AI can be paralyzed by using a paper on camera

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4582]
There needs to be some long delay check or at least making it less annoying for the AI when someone decides to spam paper on camera.

Ideally AI should be able to ignore such communication.

**Comment by ComicIronic** [comment]
I thought a delay was added.

**Comment by CptWad** [comment]
A delay was added. This is not a feature request but needs more testing

**Comment by dylanstrategie** [comment]
If there is a working delay, it might be far too small. The time needed to move your mouse and close a window is significant. I'd rather have the window NOT show up automatically but turn it into a chat link, like Holopad calls or PDA messages

**Comment by ihadtoregisterforthis** [comment]
This should be closeable too
