### ISSUE TITLE
Emagging cell chargers just kind of leaves sparks around

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4583]
![ss 2015-05-21 at 09 09 31](https://cloud.githubusercontent.com/assets/6526157/7761579/c2f477b0-fffd-11e4-8c9c-31d4dc9e6058.png)
they don't go away or anything, even after you move the charger

**Comment by ComicIronic** [comment]
If this doesn't use the spark setup datum, we lynch dylan.

**Comment by dylanstrategie** [comment]
The spark setup datum ? Is that new ? Did I forget the spark setup instruction ?

**Comment by ComicIronic** [comment]
Works fine locally.
