### ISSUE TITLE
Smart Fridges won't hold raw chicken and plant bags won't pick it up

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4586]
I know, it's called a plant bag not a raw chicken bag. But it picks up meat and it's an inconsistent approach.  Same with the smart fridge.  It'll gladly store meat but not chicken.

I'm mainly making the issue for myself because I'm really eager to learn some basic coding and I believe this will only take a few lines to change.

**Comment by ComicIronic** [comment]
Pomf clearly had a hand in this.

**Comment by dylanstrategie** [comment]
Raw Chicken should obviously be compatible with Smart Fridges and Plant Bags

I'm fairly sure meat slabs have an exception in both cases, as they otherwise aren't pathed to be compatible. Try to look for that and drop raw chicken in

**Comment by Probe1** [comment]
I'm very tempted to go balls deep and make all uncooked meat into a single /obj/item/weapon/reagent_containers/food/snacks/uncookedmeat category so we can plant bag up xeno meat, carp meat, bear meat, eggs, meat meat, raw chicken and the like without having to make a large list of additions.  Is that wise?

**Comment by Probe1** [comment]
Talked  with comic, gonna migrate raw meats of all types and eggs to [meat.dm] instead of having them all scattered about in [snacks.dm]

**Comment by Probe1** [comment]
I DID SOMETHING
