### ISSUE TITLE
Devouring impregnated humans as a xeno can result in the babby being born inside you and not be able to leave.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4588]
How to do

>Be xeno
>Facehug someone
>Allow enough time to pass (or have them be something that heals really quick like a horror form changeling)
>Devour them
>The babby inside gibbs them inside you
>Babby stuck inside
>Wake me up inside
>CANT WAKE UP

**Comment by Shadowmech88** [comment]
Can the baby evolve inside the xeno?
If the xeno gibs itself with water+potassium, will the baby survive and be freed?

Could a single xeno devour many humans this way and act as a troop transport vehicle for the new xenos, purposefully gibbing itself to release ten adult xenos into a room at once when the people inside only thought they were fighting one?

**Comment by ComicIronic** [comment]
I'd wonder if this is a bug at all.
We could make it so that xeno are told not to eat facehuggered humans.

**Comment by dylanstrategie** [comment]
Technically speaking, the alien larva is spawned inside the alien, isn't it ?

I'm pretty sure the Alien can Regurgitate (or whatever that verb is) to get its stomach contents out, or am I missing something ?

**Comment by Shadowmech88** [comment]
The person who posted this in the thread said they tried to regurgitate them and couldn't.

**Comment by ComicIronic** [comment]
They likely have to be added to the stomach var to be regurgitated, saying that without looking at the code.

**Comment by CptWad** [comment]
>Can the baby evolve inside the xeno?

Yes

>If the xeno gibs itself with water+potassium, will the baby survive and be freed?

No idea

>I'm pretty sure the Alien can Regurgitate (or whatever that verb is) to get its stomach contents out, or am I missing something ?

I am that person from the thread and yeah since it was the human body inside me that was deleted the xeno babby probably was not counted for the regurgitate.

**Comment by Exxion** [comment]
Everybody loves src.loc = [container].loc

**Comment by PJB3005** [comment]
@Exxion, a movable atom can only be in another atom's contents list, you can't put it in other lists and have it behave as if it's in contents.

**Comment by Exxion** [comment]
Damn
Is there anything else the xenos use their contents list for? If not, could they just devour things right into their contents list?

**Comment by PJB3005** [comment]
things in hand are in the contents list, for example

**Comment by Exxion** [comment]
Damn
Can a datum have a contents list?
Can the stomach be an atom in the xeno and thus have its own contents list?

**Comment by PJB3005** [comment]
don't think so

**Comment by clusterfack** [comment]
This can be solved with the simple application of get_turf(src) as the loc for the xeno pop transformation. I thought I replaced all transformations with this but apparently I missed this one?

**Comment by ComicIronic** [comment]
That wouldn't be realistic behaviour, though.

>pop in a locker
>larva magically appears outside of it

It's more of an issue with the stomach not being handled correctly. The stomach should be a storage atom within the alien.

**Comment by clusterfack** [comment]
No thats not the problem comic, it happens with anything that is within something elses content. 

For example sleepers dna scanners adv scanners would pop a xeno into the machine and they would never ever get out. In this case realism doesnt mean jack shit compared to a situation ehere even a single oversight can get you stuck inside stuff forever.

**Comment by Exxion** [comment]
That doesn't make sense
Use a solution that is more stable but worse gameplay-wise in case the code somewhere else is shitty and breaks if presented with the better gameplay solution? Why not just fix the code that breaks?

**Comment by clusterfack** [comment]
If you lay a shitty foundation to start with you are going to end up with shitty structures on top of it. There is no way to manage who contributes the code and if even one of them adds a method by which a mob is held in contents it can and will break so there is little reason to leave stupid little traps like that in the code.

Also there are practically no situations in which this is actually useful compared to situations in which it breaks, so coding in snowflake ways to fix for every single object is just plain stupid.

**Comment by Exxion** [comment]
But objects such as those shouldn't usually be putting things, especially mobs, straight into their own contents anyway. It's just asking for trouble. It's expected that doing something you shouldn't do will cause issues.
There's a difference between a pointless complication and a feature. If you can never add something that would break if someone misuses it, you could never add something interesting. You just have to make sure people don't fuck it up and fix it if they do. This is something that is done constantly here.

**Comment by clusterfack** [comment]
That's a terrible way to design a game, where every newcomer has to have intimate knowledge of every system he may break before he even touches the code or they simply break everything. It's not feasible for a large scale project like ours.

**Comment by Exxion** [comment]
So call destroy on the storage atom in the destroy of the machine or whatever it is.
And I wouldn't call "use common sense" intimate knowledge. If you put a mob directly into something's contents list and you don't intend to at some point dump the entire contents list, anything that the mob drops, voluntarily or not, irrecoverably enters nullspace.

**Comment by CptWad** [comment]
I think you both should fix the bug your way then test it. The one that works gets merged by the chicken god.
