### ISSUE TITLE
Changelings Take Physical Damage When Leaving Monkey Form

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4590]
Bleeding, bone breakage, the works. Same as what happens when a monkey'd person is turned back into a human.
I don't know if this is intentional or not, but it seems odd to penalize lings so heavily for using one of the handiest abilities.

**Comment by Exxion** [comment]
Last time I was a ling and used Lesser Form, this didn't happen
Granted, that was a long while ago, but still
I don't think it's intentional

**Comment by Shadowmech88** [comment]
Yeah, it didn't used to happen. I noticed it just yesterday.
