### ISSUE TITLE
(WEB REPORT BY: smed REMOTE: 198.245.63.50:7777) Infrared Emitters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4593]
>Revision (Should be above if you're viewing this from ingame!)
7128895b919ec3fc15f046d92b01ca653c2f46e3

>General description of the issue
Infrared emitters don't seem to trigger remote signallers properly. Invisible lasers seem to be visible. Rotate verb does not seem to function with infrared emitters.

>What you expected to happen
Invisible, directible beam triggered signaller when person went in armory.

>What actually happened
Visible beam was on top of person, but signaller did not send. I confirmed the code and frequency several times.

>Steps to reproduce if possible
Attempt to use a remote signaller infrared emitter assembly to trigger.

**Comment by dylanstrategie** [comment]
Infrared Emitters and everything that branches from them have obviously been left completely without support for a long while now. Might need as much as a full recoding

**Comment by clusterfack** [comment]
There's another bug about infrared emitters
