### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#4594]
So as much fun as using puny strength to forge table parts using your bare hands is, the crafting system has always been a bit unrealistic, even if it works well in a pinch. With more and more complex items either coming out of a vending machine or getting spat out by RnD, I was thinking on how we could make crafting more complex.

On thinking of ways this could change, I came up with a couple of ideas
### Hallway crafters

Machines dotted around the station in public-access places, you slide in one or more materials and it lists the stuff you can make out of them. This allows crafting out of multiple materials instead of just one, and lets us put available items behind public material or machine walls to separate hand-craftable items and machine-craftable ones
### Score tool

Item that lets you cut out shapes from sheets. It would open up a wider choice of crafting recipes and lower the cost of recipes that you can make without the tool. The tool would have to be widely available - or not, engineers could control it - but it would control making complex items.

Both of these would keep handcrafting in a basic sense. It would be expensive, you wouldn't have as many recipes, but you'd be able to make, say, a wall girder if you needed it.

**Comment by Probe1** [comment]
Sure.  Are you going to code it?  We accept some things because we're not gonna do anything better.  If you want to make something awesome then by all means.

**Comment by ComicIronic** [comment]
>It sounds fantastic but then when I think about it, it just won't work. "I'm sorry little Johnny, you can't patch that breach. You need to go build girders and drag them to escape." Which would mean no one fixes anything.

Obviously some stuff would be kept in basic crafting because of necessity, but I'm more interested in expanding it to include more possibilities than changing what we currently have available.

**Comment by CptWad** [comment]
For a moment I thought you stole my textile industry idea I have been sitting on.
Then I read everything and I got kinda dissapointed
Having the ability to make stuff on the fly is great for the jobs that need or want it. When I play bartender I will tear up the wood and replace it with muh nostalgia metal red&white tile bar. It takes a good ten-fifteen minutes to pull off if I don't get interrupted.
I know you are working on the material datum stuff but you probably should not be coding on top of something that is neither implemented or tested.

**Comment by MercuryDoll** [comment]
what if you need tools to create girders and tables etc? Welding torch to cut out metal sheets, screwdriver to assemble table parts.

**Comment by Probe1** [comment]
Then I would mug people for autolathe access so I could get an rcd and non engineers would be fucked hard.

**Comment by 9600bauds** [comment]
Sure the crafting system is unrealistic, the question is, is it an issue?
I don't think the game is improved by having to jump through hoops to build a couple chairs, or that a bartender should engage in an autismal crusade of getting access and tools and taking fourty minutes for his bar remodeling. In fact, if the crafting system is made any harder or more obtuse, I doubt we'd be seeing bar remodeling.
Don't fix what ain't broke.

**Comment by Probe1** [comment]
The discussion ran its course and anyone motivated to make changes did so.  Open a new issue to discuss the current state of the game.
