### ISSUE TITLE
Xenomorphs dying to pressure inside atmospherics pipes.

### ISSUE THREAD

**Issue by Ragnasal** [d3athrow/vgstation13#4595]
Not sure if this is intended or not, considering Xenos can survive the vacuum of space.
If it is intended, I suggest a 'high pressure' indicator for the Xenos be added to the HUD. They currently have no idea what happens when they just randomly die inside a pipe.

**Comment by SkowronX** [comment]
It also happens to other non silicon mobs that can vent crawl.

**Comment by dylanstrategie** [comment]
Most certainly intended. Fire warnings are VERY wonky for Xenos currently (if there even is one) and pressure warnings are absent. Both need to be added

**Comment by Probe1** [comment]
The fire warning is part of the xeno hud but is hard to read because of the clutter and decor.

There should be a warning BEFORE they enter the pipe altogether.

**Comment by AutismSpider** [comment]
Xeno hud has a warning for fire/heat and when you walk into zone that has plasma.

Top right crap glows purple when in plasma glows red/orange when in the heat/fire

**Comment by gbasood** [comment]
>There should be a warning BEFORE they enter the pipe altogether. It's very easy to enter one then before you realize it you're at half health and already too far away to get back out alive.

This. Crawling into a vent as ANY mob can get you instantly killed due to pressure/heat in many situations as it is, and you would have no way of knowing it would do that before entering as it is.

**Comment by ComicIronic** [comment]
So one thing that was bugging me about this (and you may have seen me talk about it in the IRC) is that I couldn't at all find the code for aliens taking pressure damage.

So I did some testing.
Turns out they don't.
In a waste loop cranked up to 2000kPa, both a xeno larva and a xeno hunter took 0 damage.
What kills xeno in pipes is heat, which is entirely intended.

**Comment by AutismSpider** [comment]
Xeno needs to get a note when venting into pipes with high heat.

**Comment by Ephx1** [comment]
There is a heat symbol on the HUD I believe, but like dylan said, they're wonky as fuck.
Sometimes it seems that heat will even affect xenos in the vacuum of space.
