### ISSUE TITLE
Spider Queen gamemode.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4596]
The problem with adding new game modes is that you have to add in entire new concepts and hope everyone just goes along with it, and most of the time it will just be newcops or ling in a new flavor.
What if I told you that there already exists a powerful force in the universe, that can take down death squads and send fear into everyone on the station? How many stations have been lost to spiders?

The spider queen was genetically created in a NT research lab to make cheap, strong, and light super armor from silk. They made a spider that produced an amazing amount of super strong web, it would even reflect lasers. Only problem being that the genes that they thought they spliced in wasn't passivity, it was knowledge. The spider queen produced its silk, waiting, hatred growing more and more for humans that contained her, until she managed to break out and kill her captives, laying eggs all over the research station. She sent out on the escape pods eggs containing new spider queens to spread all over the universe.

This gamemode would be like blob and changeling, the spider is obvious once seen, but is still a very dangerous foe, and it grows in power every time it eats someone to take their knowledge. It can only eat monkeys once for power, any other monkeys ate will do nothing for her. She starts with a limited ability to lay eggs, spread web around her, pry open airlocks, and has a bite that deals a substantial amount of brute damage and injects sleep toxin. As she eats more, she can choose what to upgrade next, basically having a flowchart style of leveling up. Improving web lets it spread automatically, improving egg laying ability gives it the power to lay more eggs, when you improve both web and eggs you can have web nodes that lay eggs for you. Some power ups might give you cyanide bites, web armor letting you take less damage from lasers and reflect them sometimes, or even be able to choose what spider comes out of the eggs you lay. Also having chemical powers, excreting some chemicals you can cause effects, like emps or polyacid smoke. You also get smarter with the more people you eat, eat a person and you can understand their language, eventually being able to talk and use machines.

The late game abilities are horrifying, the beginning of the end is when you learn the true nature of the forces beyond, you looked into narsie and he was scared of you. Before they were rushing into maintenance areas to hunt you down in teams, at this level you taunt them to go ahead and call in the death squad, they can't uneat you. You learn the true nature of souls, being able to lay a large egg so that you can rehatch if you are killed. You learn the pathetic cult magics, being able to phaze though walls and other horrifying things. Intercepting telecommunications, meaning you can recall the shuttle and call it at will.

The rounds win conditions are as follows.
Spider Queen dies: major crew victory
Nuke goes off: draw
Crew escapes on shuttle: minor crew victory
Spider Queen escapes on shuttle: Spider Queen minor victory
No more living crew members on station: Spider Queen minor victory
Spider Queen fully evolves into a godlike state: Spider Queen major victory

**Comment by ComicIronic** [comment]
So Wiz, but with progression.
Sounds like Evolve, but might fall into Evolve's pitfalls.

Also risks falling into Wiz's pitfalls, which is that the round just stops when the single antag is revealed.

**Comment by FudgePucker** [comment]
Wizzy man can be cholraled and feels pain.
If he gets shot with a syringe gun or shotgun shell he is dead.
Spider Queen will regenerate health and be immune to chemicals.
Also wizards don't have an army of HOLY SHIT FUCKING GIANT SPIDERS

**Comment by Exxion** [comment]
The problem I see is the Spider Queen being too powerful.
Giant spiders are already pretty horrifying. I don't know about anyone else, but I have trouble killing even two or three with anything short of a fire axe.
Of course, cargo can order guns, etc., but it would be pretty difficult even then unless the Spider Queen player is entirely inept at hiding and planning.
Even if the Spider Queen is not absurdly OP in early- and mid-game, there would be a point of progression past which the station is entirely fucked unless the Spider Queen goes braindead, but the round would continue until the entire crew is exterminated (because none of the other ending cases will occur if the Spider Queen gets to that point). And more than likely, that point would be quite a while before whatever is considered a "godlike state."

Not that these problems are impossible to get around. They'd just be hard to get around. But if we can manage it, it would probably be a pretty cool gamemode.

**Comment by Shadowmech88** [comment]
It'd need some more adjusting but overall, I'm for it.

**Comment by FudgePucker** [comment]
@Exxion Well I mean, blob has a point of "there is nothing the crew can do to stop it" as well.
Early game they would be hunting for it so it would have to pick off players one at a time, meaning that the crew would have to work in pairs and be careful. Shit crew means death in nuke ops and blob as well.
Spider Queen isn't that OP in early game, it would destroy some assistant valid hunting in maintenance who decided to only take some cable cuffs and stun gloves, but fighting a group of three armed players or a cyborg would be suicide. This as compared to wizard who is death incarnate in the beginning but can be killed by a single valid hunter, or aliums where they just storm virology round start. The round would continue on normally if traitors or lings went brain dead, and they have the benefit of just sitting in an escape pod after getting their objective then going brain dead, spider doesn't have that benefit.
God like state might be when all power ups are obtained. The entire crew might be dead by then.

Gameplay progression would be, hide around in areas laying eggs and hoping to pick off a crew member walking alone, he screams out before the toxin knocks him out about you so you have to vent crawl around to hope to pick up more targets and also make some egg nests. Once you are somewhat powerful enough, you can start attacking alone players out in the open more. Slowly picking them off one by one until you finally become unstoppable.

A low level power up could be web walk, where for a constant drain on your webs when moving, you lay webs where you walk, meaning you can retreat better from laser fire, also lets you space walk.

**Comment by AutismSpider** [comment]
I think we have left over spider hud in the code.

Could use that?

**Comment by gbasood** [comment]
Spider Queen might actually be more suited to an event like alien infestation. Although maybe it could be both.
