### ISSUE TITLE
!!PANIC!! waste and distro loops connected between telesci and medbay break room

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4598]
![panic](https://cloud.githubusercontent.com/assets/3959840/7781664/1a178294-00a8-11e5-98b5-355432ad68a0.png)
Oh god send help

**Comment by ComicIronic** [comment]
Nice work, dylan.

**Comment by Probe1** [comment]
oh god

to anyone that doesn't understand, any bad gas in the air like plasma is sent right back into the air.  its scrubbed out of the air, put into the clean air pipes, then pushed back out.

**Comment by AutismSpider** [comment]
best part is if you make the wast loop freezing cold air loop gets cold too.

**Comment by dylanstrategie** [comment]
I'm going to throw that out there, but the chances of it being me are pretty damn low. I wouldn't be that bad at piping

I'm now throwing the blame at anyone, but I remember seeing a double Waste-Distro at 7000°C a week or two ago before I got to both of my recent map PRs. Maybe a recent pipe mapping project had a fuck-up

**Comment by Probe1** [comment]
Yeah it'd be a GOOD IDEA to make sure all your waste cooling loops are implemented in the atmospherics pipe net and not the station pipe net for the time being so it's protected by the waste volume pump in atmos.

**Comment by AutismSpider** [comment]
Sure this not Dylan doing any way

About 2/3 weeks a go some dip shit try make burn room in atmos it failed 5 mins later all of the station air was 7000 to 8000 C and full of hot Plasma CO2 and O2

**Comment by Exxion** [comment]
And Git blame doesn't work because of the map patcher.
Oh well. Guess it's a mystery.

**Comment by Manaony** [comment]
I actually went and deconed the thing, I have a good and a bad news, the good news is I THINK they aren't connected, the bad one is there's actually two set of pipe one over the other

**Comment by AutismSpider** [comment]
i don't know man.

better look over the map make sure.

**Comment by PJB3005** [comment]
bloody hell

I thought this was some fucking troll that interconnected them!

**Comment by IratePirate** [comment]
This may have been me. I changed that area like 8 months ago. I don't believe I fucked with the piping however.

**Comment by PJB3005** [comment]
8 months? highly doubt that

**Comment by IratePirate** [comment]
https://cloud.githubusercontent.com/assets/6830971/5889678/7772fa9c-a42b-11e4-9814-654c6687e32e.png

Doesn't seem like it was mine after all.

**Comment by AutismSpider** [comment]
yeah some one derp up the map.
![fix it man](https://cloud.githubusercontent.com/assets/10268342/7785676/89dc862a-0160-11e5-95ee-c97519c44b35.PNG)
