### ISSUE TITLE
(WEB REPORT BY: smed REMOTE: 198.245.63.50:7777) Cloning Scanner Board

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4599]
>Revision (Should be above if you're viewing this from ingame!)
8876203960787873ccec147c4fc850c9c52255ac 

>General description of the issue
Cloning Scanner Board can't be made

>What you expected to happen
Unlocking the ability to make it in a circuit imprinter after reaching Data 3 and Biotech 2

>What actually happened
I maxed out my tech fully and was unable to create the board on any circuit imprinter. I double-checked the board name and went through the list.

>Steps to reproduce if possible
Attempt to produce a Cloning Scanner board.

**Comment by PJB3005** [comment]
I think it's the same board as the DNA modifer

**Comment by 9600bauds** [comment]
Pretty sure the name of the board starts with "cloner" too, there's one of them in Tech storage. Can't check right now.

**Comment by 9600bauds** [comment]
Can confirm the design unlocks correctly
![ss 2015-06-04 at 01 30 58](https://cloud.githubusercontent.com/assets/6526157/7976923/657a1304-0a59-11e5-8b27-b3dc6d83c3ef.png)
Cloning console circuitboard is simply named "cloner", which could be improved but that's an unrelated problem.

**Comment by clusterfack** [comment]
Just works
