### ISSUE TITLE
(WEB REPORT BY: eldzen REMOTE: 198.245.63.50:7777) Phantom Bag Inventory

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4605]
When you open a bag, but drop the bag without closing the inventory of the bag, this happens 
http://puu.sh/hXDdD/d3df8464d2.png
The clown bag I had opened still had its inventory shown for the rest of the round. It is not just the clown bag either, belts do it too. Anything with an inventory.

>Steps to reproduce if possible
Open a bag, drop the bag without closing the inventory window.

**Comment by clusterfack** [comment]
Clearly this happened from the image but the steps to reproduce must be wrong. It just doesn't happen  when you drop a storage item while its open.
