### ISSUE TITLE
Taxi Station Atmos

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#4610]
The air injector and Uvent are set up wrong here or its the pipes
![pipe autism](https://cloud.githubusercontent.com/assets/10268342/7785899/1e52d21a-016f-11e5-857d-0cee0df2b837.PNG)

Zero gas flow in them.

**Comment by AutismSpider** [comment]
Most of the Gas mixers are not set up right on the other stations

**Comment by justsmith** [comment]
engi station needed the gas injector rebuilding/relinking before working

**Comment by ComicIronic** [comment]
The vent works, but the injector is broken.

**Comment by 9600bauds** [comment]
Is this still an issue?

**Comment by xpcybic** [comment]
Looks like it's working
From his screenshot it looks like the injectors were facing the wrong way at some point but they aren't anymore
![screenshot 2016-02-17 18 33 49](https://cloud.githubusercontent.com/assets/15971146/13130939/9c8f39a6-d5a5-11e5-9760-866e4ee1a11f.png)
