### ISSUE TITLE
(WEB REPORT BY: sentientcloud REMOTE: 198.245.63.50:7777) Flaming B52 glasses still glow after being emptied

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4611]
>Revision (Should be above if you're viewing this from ingame!)

d366050df9ffdbc95dbe8f652866198c24e91dac 

>General description of the issue

After someone drinks a flaming b52, the empty glass continues to glow blue.

>What you expected to happen

The glass should not glow when it's empty, obviously.

>What actually happened

The glass still glows blue after the flaming B52 is drank.

>Steps to reproduce if possible

Make a b52, light it, and then drink it.

**Comment by ComicIronic** [comment]
@Deity_Link

**Comment by DeityLink** [comment]
aaaaaaah
