### ISSUE TITLE
Vox outpost has antag vox pressure suits with redonkadonk protection values

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4616]
Don't remember the exact numbers right now, but something crazy like 60% melee, 50% bullet and 25% laser protection. Which is a fuckton more than even Sec hardsuits, and these are readily available with no access requirement to non-raider vox at the low low cost of taking a hike.

**Comment by 9600bauds** [comment]
![ss 2015-06-14 at 04 17 17](https://cloud.githubusercontent.com/assets/6526157/8147649/6da4a68e-124c-11e5-8e5d-9cd077a78677.png)

**Comment by Exxion** [comment]
Having _some_ obtainable armor for vox is nice, but yes, those protection values are patently absurd
Either lower them or only put one on the trading post rather than four

**Comment by WeinerMaster69** [comment]
Seriously. I tried to murder a vox wearing one of these and they had enough time to yell out over comms my exact location, down to the centimetre, my name, my address, favourite colour, most deeply repressed childhood memory, my eye colour, my fingerprints, and my height before he even fell over.

nerf now

**Comment by 9600bauds** [comment]
People forget that these have the same protection values as syndicate softsuits, which are also available to non-antags by just going to the Derelict. Though they're still better in terms of being in a relatively safe path and not raising a few eyebrows, it's worth mentioning that Vox can't wear any type of armor except these.

**Comment by WeinerMaster69** [comment]
Wait, the red syndicate suits? Those softsuits?

**Comment by 9600bauds** [comment]
Yes, they're also one of the best armors in the game.

**Comment by WeinerMaster69** [comment]
I always assumed they were just the grey ones you get in science, but with a big "FUCK ME" red paintjob

**Comment by 9600bauds** [comment]
Nope, they are the ultimate monster huntan suit. Enjoy

**Comment by Exxion** [comment]
> Vox can't wear any type of armor except these

That's... not true. Vox can wear many softsuits, including the syndie ones, in fact, if I'm not mistaken. These are, however, the only ones they can use and have a free back slot.

**Comment by 9600bauds** [comment]
This was nuked at some point
