### ISSUE TITLE
(WEB REPORT BY: beroya REMOTE: 198.245.63.50:7777) No wrench for the warden in brig

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4623]
>Revision 242476a4140272aef78fa5fd68bf604e5bb734f9
 no wrench for warden in brig

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by ComicIronic** [comment]
Nice map.
I'm going to assume this is Taxi.

**Comment by PJB3005** [comment]
It's not taxi only, I recall having this issue on other maps too
