### ISSUE TITLE
(WEB REPORT BY: brorman REMOTE: 198.245.63.50:7777) air injectors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4626]
Revision: 242476a4140272aef78fa5fd68bf604e5bb734f9

several air injectors on several maps are broken.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by PJB3005** [comment]
Descriptive issue/10

**Comment by ComicIronic** [comment]
There appears to be an issue with roundstart injectors.

**Comment by 9600bauds** [comment]
That's it, I'm forcing this label.

**Comment by clusterfack** [comment]
Just close it you fucking nerd, I already said to do that with shut web reports

**Comment by 9600bauds** [comment]
I will still use the label before closing

**Comment by PJB3005** [comment]
Wow I managed to hit reopen whilst scrolling up on mobile.
