### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Backpacks inner texture changes to something weird

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4628]
Occasionally the texture inside the backpack will change to this weird texture I can only describe as a metal wall of some sort, and you will be unable to place items back into the backpack by simply clicking on the inside backpack's texture. You have to place items directly onto your backpack sprite. I dont know what triggers it to happen.

**Comment by PJB3005** [comment]
![](http://i.imgur.com/5GqAXme.png)

Can confirm

**Comment by ComicIronic** [comment]
That is odd.
How did you manage to reproduce it?

**Comment by PJB3005** [comment]
No idea, Just opened that backpack and there was that sprite.

**Comment by clusterfack** [comment]
Pooling is spooky, its almost certainly a pooling issue along with the other inventory issue.

**Comment by DrCelt** [comment]
I'm getting this bug from time to time too. I also can't put items in storage items by clicking the slot anymore, or occasionally the items will be there but with no background slot overlay. Is this all the same pooling issue?

**Comment by clusterfack** [comment]
Likely

**Comment by clusterfack** [comment]
So I looked into it and it seems at first glance this is a pooling issue, this is the blank icon_state for screen objects, which is what these boxes get their variables reset to when pooled. So we understand how this happened, but not why. There shouldn't be any method by which something else is telling these boxes to return to pool that I can think of.

**Comment by clusterfack** [comment]
Whelp I figured it out in my most recent pull, reset_screen() tends to do this when mob/login is called or a new hud is created for a player if they had this bag open.
