### ISSUE TITLE
[Taxi] Map issues

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#4629]
-taxi caller buttons being reliant on APC power seems like it could be open to abuses
-HoP sunglasses and armoured suit at the bottom of locker
-doors are below firelocks all over the place
-accounts database cannot be reached due to dense objects (damn it Deity), room generally needs to be made bigger
-recharger should be on the wall if there's no room for it on the table
-shutters in bar area on top of the tables look silly
-disposals is fucked south of disposals on Engi-Cargo station, holes where there should be pipes
-gas sensors above vents in mini-atmos'
-virology access button underneath a newscaster
-light switch in surgery on the table
-sink above window just north west of medbay entrance
-no intercom in genetics
-maintenance east of chemistry randomly has a shit load of first aid kits in it
-missing wall in virology north east of the disposals
-incorrectly placed cobweb in Medbay station disposals
-too many poorly placed windows all over the place, shit looks structurally unsound
-no bells
-medical break room door called Surgery
-botany backroom vent is visible
-intercom on top of APC in science entrance
-pipe under rwall in east genetics
-pipe under rwall north of mini atmos room
-ugly windows in server room
-custodial closet is incredibly small and in maintenance
-ugly window east of custodial closet
-visible vents all over engineering
-atmos has non-visible vents while every other pipe is visible
-toxins lab floor under central door is not white like it should be
-telescience igniter switch on the table
-wiring under windows generally is fucked up, needs to be like it is on the other stations
-three doors at medbay entrance looks hideously ugly, needs the central one replaced with a wall or window, plus the windows to the east and west look ugly
-medbay entrance APC is cramped onto the wall alongside the door button
-captain's office door has incorrect floor under it
-double layered bridge windows - what
-sec entrance poster is on the floor and not on the wall

**Comment by PJB3005** [comment]
Well, that's a lot of issues

**Comment by ComicIronic** [comment]
>shuttles relying on power

They don't.

>solars need to be fixed before they can be a main source of power

In what way, because they aren't intended to be the main source of power at roundstart, the portable batteries are.

>bridge is hilariously cramped with only one entrance jesus god what the fuck

The main bridge is only slightly smaller than the one on box, but I could split the doors apart. It wouldn't have much effect, though, because they both lead to the same hallway.

**Comment by ComicIronic** [comment]
> -engineering sign above window

All the signs are above windows, this is intentional.

>pipe under rwall in east genetics

This is hardly an issue. The occasional pipe under an rwall can't be avoided, the stations are only so big. It's not a row of pipes.

**Comment by IratePirate** [comment]
This is just stuff I jotted down as I played. I thought that the power controlled the shuttles but it was just the buttons.

**Comment by ComicIronic** [comment]
Check as many of these again as you can.

**Comment by Duny-** [comment]
Just played a round, was coming here to complain about doors being below firelocks when I saw it listed here. It's still the case.
Very much an issue especially for silicons. Makes closing a door you just opened impossible with the shortkeys, as it's unclickable.
