### ISSUE TITLE
(WEB REPORT BY: dragonbro REMOTE: 198.245.63.50:7777) Taxi Station - Miners

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4632]
On Taxi Station, Miners do not have access to the Hardsuits, or the Airlock access to the mining asteroid. Also there's no immediate access to an Air Tank dispensary.

>What you expected to happen
When I went to open the doors, they would open because they're for mining

>What actually happened
Doors blinked red

>Steps to reproduce if possible
Be a Miner, and push against a door.

**Comment by Skullyton** [comment]
Another thing; The consoles at the mining station are both for the Research Shuttle, preventing miners from getting back.

**Comment by ComicIronic** [comment]
The mining shuttle is the research shuttle.

**Comment by Skullyton** [comment]
Both of the consoles Mining-station side are Research Shuttle

**Comment by ComicIronic** [comment]
Is that an access issue, or just a name one?

**Comment by Skullyton** [comment]
Access, Miners can't use Research Shuttle consoles, only Mining Shuttle consoles.
