### ISSUE TITLE
Taxi engines are on cooldown for the next -255.21 seconds. Please wait before trying again.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4638]

**Comment by ComicIronic** [comment]
I thought I fixed this. It happens when you hit the button but the Taxi is already there, no?

**Comment by PJB3005** [comment]
Er, no, in that case the taxi wasn't there

**Comment by ComicIronic** [comment]
You'll have to come up with a more detailed issue report, then, because this doesn't help me at all.

**Comment by PJB3005** [comment]
I don't know what caused it, but it happened
