### ISSUE TITLE
(WEB REPORT BY: donalddawkins REMOTE: 198.245.63.50:7777) no solid plasma in engineering taxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4645]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

right now engineering has no solid plasma for it's PACMANS, due to the nature of taxi station and the increased likelyness of power failure arguably there should be more solid plasma distributed around the already abundant PACMANS

no point having PACMANS if you can't use them

**Comment by ComicIronic** [comment]
While true, I'm not sure I want to invalidate mining for no big reason.

**Comment by 9600bauds** [comment]
Was addressed
