### ISSUE TITLE
[TAXI] Sleeper?

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4651]
![image](https://cloud.githubusercontent.com/assets/9827785/7789712/a3b8b432-0238-11e5-9f5c-761e74f82e34.png)

On abandoned mining station or whatever it's called

**Comment by ComicIronic** [comment]
Very odd.

**Comment by Exxion** [comment]
Someone set that sleeper's icon_state to "sleeper_open" and, for some reason, set its dir to 8

**Comment by IratePirate** [comment]
It's the same thing with the Nuke Ops shuttle I believe.
