### ISSUE TITLE
(WEB REPORT BY: nigglywiggly REMOTE: 198.245.63.50:7777) Stools are borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4655]
>Revision: bad0c0d281caa3de49e36c1b6a4acb21978e5624 
>General description of the issue
Cannot wrench apart stools, if you pick up a stool and 'use' it, it says you put it down, but then it disappears entirely.

**Comment by ComicIronic** [comment]
Yeah, I've not had this happen at all.

**Comment by PJB3005** [comment]
Actually, I think I had this happen once, pick up a stool by dragging it onto you, then drop it, you can't unwrench it then.

**Comment by Intigracy** [comment]
#4655

**Comment by Intigracy** [comment]
#5300

**Comment by clusterfack** [comment]
^
