### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Mechanics Airlock Problems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4656]
Basically mechanics is not an access you can set on airlock electronics,making hard to make new doors for it

**Comment by wwjnc** [comment]
Actually it is, mechanics access is "Workshop". It's a bit misleading but eh.

**Comment by ComicIronic** [comment]
I should rename the area, it annoys me now that it's called Mechanics.

**Comment by gbasood** [comment]
Does anyone give a shit about this

**Comment by 9600bauds** [comment]
Yeah kind of, it's anti-quality

**Comment by Zth--** [comment]
Someone should rename Mechanics to workshop

**Comment by Probe1** [comment]
Somebody just did a PR on this.  https://github.com/d3athrow/vgstation13/pull/12805
