### ISSUE TITLE
[Taxi] Brig issues

### ISSUE THREAD

**Issue by IratePirate** [d3athrow/vgstation13#4661]
-The cells are 2x2 which makes putting people into them, buckling them to the bed and uncuffing them while flashed rather difficult.
-Middle brig timer can only be accessed from the tile to its immediate left
-Right brig timer cannot be accessed from in the room, is visible from the courtroom and can only be accessed from the courtroom. Brig timers generally have awful code so all this is unsurprising, Defficiency and Meta both had major issues with them.
-Armory is tiny, contains no shotguns, barriers, flashes and Mr VALIDs might need another storeroom somewhere perhaps

**Comment by Probe1** [comment]
Maybe you could just put the MR VALIDS, flashes, and barriers all in a crate to conserve space?

**Comment by ComicIronic** [comment]
Check this again.
