### ISSUE TITLE
(WEB REPORT BY: curver REMOTE: 198.245.63.50:7777) Cool O2 canister very quickly becomes warm on a heater

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4662]
Revision: bad0c0d281caa3de49e36c1b6a4acb21978e5624

Using the standard heater in atmospherics, a cool O2 canister very quickly became somewhat hot. It went from:

 Pressure: 2272.6 kPa
 Oxygen: 1539.8 mol, 100%
 Temperature: -96°C

To:

 Pressure: 103948 kPa
 Oxygen: 1110.4 mol, 52%
 CO2: 1024 mol, 47%
 Temperature: 5582°C

Steps:

I saw the cooled O2 canister, wanted to heat it to 20C and used the standard heater. Instead of slowly warming, it jumped to the measured values when I checked it, 30 seconds after I had put it on the heater.

**Comment by MasterofNothing** [comment]
I have to add:

If I put a 16C canister with 100% O2 on the heater, it becomes 704C in one second (and it stays that way for at least another 10 second). When I put that canister on the cooler, it first becomes warmer (to about 3600C) and then gradually starts to cool.

**Comment by Exxion** [comment]
Where did the CO2 come from?

**Comment by MasterofNothing** [comment]
Out of nowhere. I didn't add it and nothing happened to the canister in the meantime.

**Comment by Shadowmech88** [comment]
Someone may have used the heater to heat a plasma canister. When you connected the oxygen canister, the leftover hot plasma in the heater's pipe mixed with the oxygen and reacted, producing CO2 and heat inside the canister.

Freezers/heaters have their own gas reservoirs, so if you don't deconstruct them before putting a different gas on there, whatever's left inside the pipe will flow into the new canister and pollute it.

**Comment by MasterofNothing** [comment]
Oh right, I hadn't taken that into account. Likely what happened. Thanks.

Closed.
