### ISSUE TITLE
Shield generators do not turn off if the power in the room is off.

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#4663]
I am 200% mad right now, gah

**Comment by ComicIronic** [comment]
Shield generators run on cable power, I believe.

**Comment by DrCelt** [comment]
But then what's the point of having a power failure if there's still power in the cables?

**Comment by ComicIronic** [comment]
1. Most machinery in the game doesn't run on cable power. Shield gens do because it's a limiter on usefulness.
2. It would singuloose every time the event happened.

**Comment by PJB3005** [comment]
I think he might not be talking about the singularity's generators, but those other ones

**Comment by ComicIronic** [comment]
I know, but these are also cable powered.

**Comment by clusterfack** [comment]
Yeah this is intentional. Also the generators have a cooldown time from power stored in them so they wouldnt turn off durning a power failure event immediatel, thats all intentional

**Comment by Intigracy** [comment]
close please
