### ISSUE TITLE
(WEB REPORT BY: exxion REMOTE: 198.245.63.50:7777) Counter bell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4666]
>Revision (Should be above if you're viewing this from ingame!)

bad0c0d281caa3de49e36c1b6a4acb21978e5624
>General description of the issue

Counter bells can be picked up with plastic bags. They cannot be removed except by emptying the bag onto the floor because clicking on them in the inventory just rings them.
>What you expected to happen

Nothing at all
>What actually happened

Picked up bolted-down counter bell with plastic bag.
>Steps to reproduce if possible

1. Obtain plastic bag
2. Hold in active hand
3. Click bell on a desk
4. Frantically attempt to put it back
5. Fail to do so

**Comment by PJB3005** [comment]
Why. are. bells. items.

**Comment by ComicIronic** [comment]
For funsies.

**Comment by Exxion** [comment]
Quick! Give it w_class 5 and hope nobody notices!

**Comment by clusterfack** [comment]
You cant do this anymore so I guess it was fixed

**Comment by Exxion** [comment]
Well I mean I just did

![](http://i.imgur.com/lxMmTE7.gif)

EDIT: AND THEN I TRIED AGAIN WITH A DIFFERENT BELL AND IT DIDN'T WORK
PANIC
