### ISSUE TITLE
(WEB REPORT BY: exxion REMOTE: 198.245.63.50:7777) [Taxi] Engineering and Cargo Station's disposals is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4668]
>Revision (Should be above if you're viewing this from ingame!)

bad0c0d281caa3de49e36c1b6a4acb21978e5624
>General description of the issue

Two of the conveyors in the disposals for Engneering and Cargo Station are backwards.
>What you expected to happen

All the conveyors to be forwards.
>What actually happened

Two were backwards.
>Steps to reproduce if possible

1. Exist

**Comment by PJB3005** [comment]
>Steps to reproduce if possible
Exist

Honk.

Can confirm this though
