### ISSUE TITLE
(WEB REPORT BY: smed REMOTE: 198.245.63.50:7777) Taxistation doors...?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4669]
>Revision (Should be above if you're viewing this from ingame!)
bad0c0d281caa3de49e36c1b6a4acb21978e5624 

>General description of the issue
Firelocks are above doors (at least in the medbay), so you can't close doors after walking through them unless you alt+click, which has ostensibly also been nerfed.

>What you expected to happen
To be able to close doors behind me in sensitive areas like chemistry

>What actually happened
Grey tide

>Steps to reproduce if possible
Attempt to be a doctor

**Comment by gbasood** [comment]
I'm not so sure this is the case, however I can say it's annoying as fuck trying not to click on firelocks instead of airlocks on ANY station.
