### ISSUE TITLE
Rollerbeds require some pixel sniping to use

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4670]
![ss 2015-05-25 at 03 22 59](https://cloud.githubusercontent.com/assets/6526157/7800838/05c96982-02f2-11e5-959c-6ba8ad3b0cda.jpg)
After buckling someone to a rollerbed, you need to click the rollerbed itself to drag the person or to unbuckle them. Since the rollerbed sprite is obscured by the person, you need to click the rollerbed's  thin af legs, which is needlessly tricky (especially since you're rather busy trying to doctor the shit out of that person).
End result, people just get dragged around over the floor.
A way to fix this would be making it so that trying to drag someone buckled to something causes you to drag the thing they're buckled to instead.

**Comment by Probe1** [comment]
There's a lot of pixel sniping.  Open firelocks and airlocks are notoriously annoying to click just right.  I just use the alt click floor tab rather than fuss with it.  An improvement would be nice.
