### ISSUE TITLE
[Taxi] Cable missing under airlock to captains office

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4671]
Txi is worst map remove txai

**Comment by ComicIronic** [comment]
I swear I fixed this.

**Comment by TermedClepe** [comment]
Maybe you did I have not been tracking fixes.

**Comment by ComicIronic** [comment]
Most recent version of the map does have this fixed.
It helps me if you check if an issue is actually still an issue before reporting it.

**Comment by clusterfack** [comment]
Tch lazy
