### ISSUE TITLE
Its time to add torture devices to interrogations.

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#4674]
Hello everyone.

I'm trying to teach myself coding, and I've decided that shitcurity is in dire need of new toys to play with.  Specifically they lack the critical ability of waterboarding an assistant. And I'd like to help with that.

I'd like to add some form of waterboarding device that you could strap a shitter to, maybe drape a cloth over his face to obscure his vision, and then pour water over his face, to waterboard him. The vict-I mean, suspect in questioning, would receive big bold "medical flavor text" such as "OH GOD JUST MAKE IT STOP" and "YOU FEEL AS IF YOU WILL DROWN AT ANY MOMENT", while taking a bit of suffocation damage. The machine would have an on/off switch or something, to question between pours.

Thoughts? And how would I go about coding such a delightful contraption?

**Comment by Probe1** [comment]
no one cares about medical text that doesn't have an effect like the majority of our chem overdose stuff and all of our pain related stuff.

it's just text and we're not a heavy rp server so no one gives it any time.

**Comment by mrpain666** [comment]
That's what the suffocation damage is for.

**Comment by Probe1** [comment]
yeaaah but if security wants to kill me, they'll kill me.  having temporary damage isn't going to motivate me to talk.

now removing parts of my mobs body that won't kill me but will ruin me.  that's something I'm worried about.

**Comment by nuklearcellphoneg** [comment]
Mmm

Pain does have an effect in game. However, it's largely tied to damage, so you mostly only notice it if you're also damaged to a degree. Pain makes you move more slowly, pass out, fall over, blurry vision, et cetera.

If you get down to it, really, nothing is going to really get someone to talk on here, unless they themselves feel like speaking or RPing in kind.  Sure, you can literally chop their arm off, but they can get a roboarm- and it's not like they're really attached(lol) to the arm anyway.

**Comment by Probe1** [comment]
By all means, add it.  But I don't think it's going to loosen any tongues.

**Comment by mrpain666** [comment]
well, worse case scenario, it becomes a fun execution toy
