### ISSUE TITLE
this fucking faggot ass airlock holy shit

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4676]
http://puu.sh/i0Lvj/667abe4953.webm
it's rendered under the firelock at round start and it's a bitch to close
telecomms also does it

**Comment by Zuhayr** [comment]
Alt-click..?

**Comment by Exxion** [comment]
I don't know about  anyone else, but alt+click breaks like half the time for me
It is not a valid replacement for proper layering

**Comment by 9600bauds** [comment]
sure you can alt-click
or you could fix that fucking airlock's layering to work like every other airlock in the game which were deliberately layered to avoid this issue

**Comment by mrpain666** [comment]
Glad to know I'm not the only one being driven completely batshit fucking crazy over this ONE FUCKING DOOR JESUS TAPDANCING CHRIST

**Comment by PsiOmegaDelta** [comment]
Ah, yes. Recall fixing this for Bay by giving the emergency shutters more appropriate layering, rather than rely on mapping order (due to same layer). Most annoying both for AIs and people wanting to hack broken open doors.

**Comment by IratePirate** [comment]
Affects most of the doors on Taxi, and quite a lot on Metaclub too. Should probably be fixed in the code instead of the map editor.

**Comment by Probe1** [comment]
fuck that airlock in particular.  i hate that airlock.  god damnit i've closed that airlock so many times trying to shut the door to a tailgater trying to drift in so he can steal shit.
