### ISSUE TITLE
Improved Player Notes

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#4677]
Currently, player notes are listed alphabetically and by page number. There are 37 pages of notes.

Is there a way to switch it to alphabetical listing?

Another nice thing would be to be able to associate players. For example, if X player has CID alts under H, J, K, and L, instead of having to hunt down each set of notes, to be able to cross populate the notes so that they appear under each instance of the player via a button press, or automatically.

B-but the alphabetical thing would be really nice.

**Comment by ComicIronic** [comment]
So the pages are listed alphabetically, and you want them to be listed alphabetically? I don't understand.

**Comment by Shadowmech88** [comment]
I think he means that the pages are listed alphabetically per-page, so that each individual page goes from A-Z. I believe he is asking for them to be listed completely alphabetically, with the A's on page 1 and the Z's on the last page.
I don't know for sure though, since I can't look at the pages to see whether they are this way.

**Comment by nuklearcellphoneg** [comment]
Yes.

Names are listed alphabetically. However, they are numbered 1,2,3,4,5,6 etc

So if you want to look at names under Q, you go to page...

Er... Well... let's go to page 12... no, not here... page 15? No, not here either... 13? Nope. 14!!

**Comment by nuklearcellphoneg** [comment]
Alphanumerically would be I guess the technical term, because we do have usernames with digits.

**Comment by nuklearcellphoneg** [comment]
![image](https://cloud.githubusercontent.com/assets/6540760/9020997/ffdc5a82-37fa-11e5-8f91-f302dbf6289a.png)

I-instead of the 12345... etc, I would like an A B C D E... etc.

**Comment by nuklearcellphoneg** [comment]
To be honest I didn't realize at the time Show player info brings up a specific player's notes. So this is basically a waste of time and effort
