### ISSUE TITLE
Logs broke since 25th may

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4678]
There are no logs since when there were those massive bugs on 25th.

**Comment by 9600bauds** [comment]
Picnic

**Comment by TermedClepe** [comment]
Logs are still not working.

**Comment by DrCelt** [comment]
@TermedClepe
>logs are still not working
Hence the issue still being open

**Comment by TermedClepe** [comment]
Logs are working.

Ayy.

**Comment by TermedClepe** [comment]
And logs are broken again. Seems every time server crashes too hard logs stop working.
