### ISSUE TITLE
(WEB REPORT BY: themegagoat REMOTE: 198.245.63.50:7777) Remote canister use by AIs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4679]
> Revision a3da7b07bffbdbadf47ea8fb130e892fc4537ba7
> 
> You can manipulate canisters as an AI
> 
> The AI can't use gas canisters
> 
> The AI can use canisters
> 
> Be AI, open canister

**Comment by CptWad** [comment]
I never quite got that
Are they digital? If they are than sure why not.
But I always sorta thought they were industrial and manual like so an AI could not use them.
It does have atmos anyways.

**Comment by ComicIronic** [comment]
When canisters were moved over to use the general machinery topic, they gained the ability to be used by the AI.

**Comment by Ephx1** [comment]
Their specific ability to use them doesn't always seem to work.
Usually I can get a menu, but am unable to open the canister proper, and have only been able to open it once after a round.

**Comment by PJB3005** [comment]
Well, that was a side effect of #4141

**Comment by clusterfack** [comment]
Change ther attackrobot or attackai to prevent AI usage. Of course be careful not to prevent ghost viewership as ghosts use that proc to view the canister.

**Comment by PJB3005** [comment]
That'd still be circumventable, probably better to add some universal var AI_allowed to objects, and have Topic() not allow AIs if that's false
