### ISSUE TITLE
Missing on-hit sound effects

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4683]
The following items have no on hit sound effects:

Energy sword
Toolbox

Will add more as I come by them.

**Comment by IratePirate** [comment]
Esword has never had them here. I've always liked the TG sound though so i could port it or add a new one.

I added a bunch of sounds a year or so ago but i dont think it ever struck me tat striking someone with a toolbox made no sound.

Honestly toolbox damage should be buffed to how it used to be. Its not like you ever see people running around with them.

**Comment by TermedClepe** [comment]
Porting sounds would be nice, I believe they also have a toolbox sound.

Soundless weapons are quite overpowered for stealthy antags.
