### ISSUE TITLE
Autolathe can't print multitools anymore

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4686]
This is a massive balance issue.

**Comment by 9600bauds** [comment]
How the fuck

**Comment by TermedClepe** [comment]
You tell me, this is the autolathe list:

http://pastebin.com/464B1kPy

**Comment by Shadowmech88** [comment]
Have you tried hacking it?
I mean, it's still stupid that it can't print it by default, but I'd at least like to know if it was intentional and someone moved it to the hacked list.

**Comment by BestName** [comment]
![what](https://cloud.githubusercontent.com/assets/3892856/7820018/4a7f9b58-03ee-11e5-954c-d2402e237dff.PNG)

**Comment by ComicIronic** [comment]
I have no idea what to tag this.

**Comment by TermedClepe** [comment]
How could this happen.

**Comment by 9600bauds** [comment]
Couldn't reproduce earlier today
