### ISSUE TITLE
(WEB REPORT BY: miniaturebigfoot REMOTE: 198.245.63.50:7777) Soldering iron not working on Cargo boards

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4687]
I wanted to see the new contraband crates, so I got a soldering iron, filled it up, and took apart the console in th Qm's office on box to get to the board. I used the iron on the board, checked to see it was working and using up acid, and then put the console back together only to find it did not work. Did I mess it up somehow or is it bugged?

**Comment by PJB3005** [comment]
@kurfurst
