### ISSUE TITLE
[TAXI] Security Bell inaccessible, rendering it useless & No ERT/adminbus port

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#4690]
What's the point of a bell you can ring to attract security's attention if it requires security access to open the windoor to get to it? 
Also add ERT functionality, please.

**Comment by ComicIronic** [comment]
ERT functionality will get added when and if Deity finishes a rewrite of it.

**Comment by DrCelt** [comment]
Is @DeityLink doing a rewrite of ERT code? Niiice

**Comment by DeityLink** [comment]
Yes, I've been waiting for other map PRs to get merged first but I guess I just might as well go ahead and do it.

The rework will feature a revamp of centcomm on all 4 maps. It shouldn't cause conflicts if I use the maptools and only change centcomm's zLevel right?
