### ISSUE TITLE
LANGUAGE THE VOX

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#4691]
Announcements/newscasts use the default selected language and can only be understood by people who speak said language. EG: A common/tradeband captain sets his default language to tradeband and makes an announcement, and said announcement is only understood by those who can speak tradeband

**Comment by Exxion** [comment]
:+1:
Or let you select the language when you write it

**Comment by DrCelt** [comment]
Selecting the language would probably get cumbersome. Also areas which would be nice to have this feature are writing on paper, PDA messages and for admins to be able to respond to faxes or make command reports in different languages

**Comment by Exxion** [comment]
Maybe just have behavior similar to chat
Default language if you don't specify, but a different language if you do
Maybe even have it possible to include multiple languages in the same post by specifying each switch in language with a chat-style marker, like :v
(I have barely even looked at language code, so I have no idea if that's possible, but it would be cool)
Like
Hello, crew. Everyone behave. :vBirds, prepare the uprising. :1Don't worry, I was just wishing our feathered friends a happy day.
