### ISSUE TITLE
For the love of God give Cargo a desk bell

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4692]

**Comment by 9600bauds** [comment]
(map issue)

**Comment by CptWad** [comment]
yes please

**Comment by 9600bauds** [comment]
![dreamseeker_2016-01-25_21-04-06](https://cloud.githubusercontent.com/assets/6526157/12568767/32b4dc76-c3a7-11e5-82a4-c502b1dceef1.png)
