### ISSUE TITLE
Mech DNA lock resets don't work.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4693]
Can anyone confirm it works?  I've seen a lot of stumped roboticists.  

Set a DNA sample for a mech, erase it, now you can't get back in and neither can anyone else.

**Comment by ririchiyo** [comment]
I think this is a bug with a specific mech unless it's occuring for all of them it's likely the html function or something is getting improperly called.

**Comment by Probe1** [comment]
i'm pretty sure bauds fixed this up.
