### ISSUE TITLE
[Taxi] Janitor Closet

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4697]
I'd love to be more specific in the title, but it would be too long

- Janitor gets two trash bags and no soap (the closet contains a trash bag plus there's one on the table)
- No water tank in the room (though there is a sink outside, so this is excusable)
- Neither table in the room is accessible without moving something/opening lockers
- Room is piss-tiny, with a grand total of two tiles not containing dense objects at roundstart, making the previous issue all the more irritating
- This one is only a minor complaint, but there are only two cleaner grenades in the room on Taxi compared to three on... I think all the others

**Comment by ComicIronic** [comment]
>Room is piss-tiny

Welcome to Taxi, the Mexico of stations.
