### ISSUE TITLE
(WEB REPORT BY: entya REMOTE: 198.245.63.50:7777) Pumpkins Dissapear when Carving masks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4700]
>Revision (Should be above if you're viewing this from ingame!)
a3da7b07bffbdbadf47ea8fb130e892fc4537ba7

>General description of the issue
Pumpkins dissapear when you try carving with both hatchets and knives

>What you expected to happen
To get a pumpkin mask

>What actually happened
The pumpkin dissapears

>Steps to reproduce if possible
1. Get knife or hatchet
2. Click on pumpkin
3. ???
4. Dissapear into the void

**Comment by 9600bauds** [comment]
I fixed this a while ago
