### ISSUE TITLE
(WEB REPORT BY: icycharm REMOTE: 198.245.63.50:7777) Protolathe printing blanks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4704]
>Revision a3da7b07bffbdbadf47ea8fb130e892fc4537ba7

>General description of the issue
Machine claims to be printing the objects, raw materials are being consumed, but nothing is actually appearing from the machine

>What you expected to happen
Objects to be printed

>What actually happened
Nothing

>Steps to reproduce if possible
Try to print objects, they don't

**Comment by PJB3005** [comment]
Yeah, I had this too.

**Comment by Exxion** [comment]
If I'm not mistaken, ba6848c4e9e70cc0ead0f0ea2d0c8ec12ab1edc4 fixed this
