### ISSUE TITLE
(WEB REPORT BY: icycharm REMOTE: 198.245.63.50:7777) Infinite blueprint printer printing time

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4705]
>Revision a3da7b07bffbdbadf47ea8fb130e892fc4537ba7

>General description of the issue
Blueprint printer enters an eternal printing animation when ordered to print a blueprint (on nanopaper or paper), not printing out the actual product

>What you expected to happen
I expected a usable blueprint to load into my general fabricator

>What actually happened
Nothing

>Steps to reproduce if possible
???

**Comment by Zth--** [comment]
This doesnt happen anymore.
