### ISSUE TITLE
(WEB REPORT BY: pseudonym REMOTE: 198.245.63.50:7777) Miners dont have access to mining station toilet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4706]
how

**Comment by CptWad** [comment]
Something something exorcism needs to be done on toilets. Fix now.

**Comment by ComicIronic** [comment]
Time to hunt through mining toilets.

**Comment by PJB3005** [comment]
muh immulsions are ruined now that I can't poop.

**Comment by Probe1** [comment]
Whatever was going on was an in game issue.  All mining toilet doors access are null.  Close @clusterfack
