### ISSUE TITLE
Farting on a bible doesn't gib you

### ISSUE THREAD

**Issue by kilkun** [d3athrow/vgstation13#4707]
using the *fart emote when standing on the same tile as the bible should gib the player doing it.

**Comment by BestName** [comment]
Why?

**Comment by PJB3005** [comment]
Because it's a goon thing.

**Comment by Unfit** [comment]
>kidnap the clown
>forcefeed him hamburgers
>put him on top of a bible and hug him until he farts
fund it

**Comment by CptWad** [comment]
:+1: We need more goon tier crazyness. Be it original or stolen.

**Comment by ComicIronic** [comment]
>it's a goon thing

A quick reminder that the reason to desire Goon content is because it's good content, not because it's from Gooncode.
This is a baaaaad idea.

**Comment by DrCelt** [comment]
Eh. I don't like it. It's too "lelsorandumb xD"

**Comment by Iamgoofball** [comment]
if you were a god @DrCelt and someone sat down and let one rip on your holy book intentionally wouldn't you want to smite them, too?

also this is less lelsorandumb xD so much as punishing people for going lelsorandumb xD

ps. there's probably some reference the bible fart gib makes, 99% of goon's stuff is references to sci-fi movies and shows
