### ISSUE TITLE
Waffle recipe makes a box of sliders

### ISSUE THREAD

**Issue by Del1m** [d3athrow/vgstation13#4709]
10 flour+2 eggs=![](http://i.gyazo.com/b0b9604e51b552edbda28a01041da5af.png)

**Comment by Shadowmech88** [comment]
A fix that would make sense would be for the slider recipe to include a cardboard box, since they pop out inside a slider box.

**Comment by SarahJohnson489** [comment]
Seconding this. Went to make a waffle cafe and got an unpleasant surprise.

**Comment by Arthurdentist** [comment]
I cannot reproduce this. Waffle recipe is working fine for me.
