### ISSUE TITLE
(WEB REPORT BY: starnightx REMOTE: 198.245.63.50:7777) Syncing Bug RD

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4710]
Well it seens that if i desync somehow any machine from the RD Console or any other Console,you'll need to screwdriver it first to Sync,it doesn't recognize if you Desync and try to Sync again,as if the machines isn't there,but the main problem is if it's the Destructive Analyzer,if there is a item loaded on it and it's desynced you can't eject the item,and to screwdriver item to make it syncable again,you need to eject the item,but for that it have to be synced with the console

**Comment by clusterfack** [comment]
As far as I can tell this has been fixed. I can't reproduce this issue.

I did the following:
Went to derelict R&D.
Went to device linkage menu and pressed disconnect on all of them.
Used resync with nearby devices.

They desynced and resynced perfectly well.
