### ISSUE TITLE
Random Option on Mapvote?

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#4712]
It'd be nice to have an option to vote for RNGesus to take the wheel and choose the map for us

**Comment by Exxion** [comment]
Since the vote order is now shuffled, just clicking the first (or any other, as long as you choose it beforehand) button regardless of what it says has the same effect as clicking a hypothetical random button.

**Comment by DrCelt** [comment]
I mean voting for a random option as in 
Random/ - 12 votes wins! Result: Defficiency/

**Comment by 9600bauds** [comment]
I believe this was somewhat addressed by the faux-random voting, do you think it's still an issue?
