### ISSUE TITLE
(WEB REPORT BY: sentientcloud REMOTE: 198.245.63.50:7777) Mass driver layers above windoor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4717]
> Revision (Should be above if you're viewing this from ingame!)

a3da7b07bffbdbadf47ea8fb130e892fc4537ba7

> General description of the issue

The mass driver appears above the windoor, covering most of the windoor up. Makes it hard to tell whether the door is closed or open.

**Comment by ghost** [comment]
This was fixed by the planes PR it seems
