### ISSUE TITLE
[Taxi] these fucking faggot ass airlocks holy shit

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4723]
~~the thing that makes coins, unless the Chef's mint is also missing~~

additionally:
![ss 2015-05-27 at 10 37 44](https://cloud.githubusercontent.com/assets/6526157/7851124/4758e910-04c1-11e5-8aa1-45bafdb2a030.png)
this thing is NOT a replacement for a cycling external airlock, it's always depressurized and always causes air alarms in Mining lobby even when you are extremely careful. Besides being ugly and blocky as sin it makes your life as Miner a ZAS kind of hell, and is a huge kick in the dick whenever you forget your magboots, because there's no way to open it without getting your shit pushed to the ground.

**Comment by Exxion** [comment]
Frinedl Remninder that cycling airlocks still fucking suck and need to be fixed before anyone could be reasonably expected to use them anyway
But yeah that looks even worse

**Comment by CptWad** [comment]
> cycling airlocks still fucking suck and need to be fixed

Honestly some sort of special atmos machinery that vents air to space then fills up a room 3x faster would work. That way the airlocks could cycle in moments

**Comment by Exxion** [comment]
The sensors or something are borked, too, though, and sometimes the vents don't pump the right way and the airlock just locks down without really pumping anything

**Comment by ComicIronic** [comment]
There is a mint, it's on the mining station.

**Comment by 9600bauds** [comment]
my mistake, I assumed that was the research outpost since you need to take the research shuttle and pretty much is the research outpost but also with a mint
