### ISSUE TITLE
[Taxi] All of the disposals systems are woefully lacking

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4724]
There are no recyclers. All trash is just launched into space.
For some reason, I get great joy from tending to the disposals on Box and selling the honestly rather impressive quantities of recycled materials the recycler spits out.

(Also, the disposals mass drivers on Taxi are totally useless because the disposal outlets are placed incorrectly and launch the trash into space themselves rather than placing it on the mass drivers and allowing them to launch it)

I have three possible solutions:

1. The easiest but least interesting:
  * Add a recycler to each station. Their disposals systems remain just as individual as they are now, but would be less shitty.

2. The middle in both ease to implement and level of coolness, but the most likely to have stuff go horribly wrong:
  * Use disposal outlets and/or mass drivers to launch the trash from two stations to the third and put processing machinery only on that one. If things are built in space, though, this could cause issues.

3. The coolest but hardest to implement:
  * Add a cargo bay to at least one of the taxis. Have trash automatically loaded into this bay while the taxi is docked at two of the stations and automatically unloaded while it's docked at the third. Place processing machinery on the station on which the trash is unloaded. A cargo bay could also be added to the other taxi for another purpose, like mail.

**Comment by clusterfack** [comment]
Mass drivering them all to the recycling station would be neat as fuck

**Comment by FudgePucker** [comment]
We could also have mass drivers leading out of cargo into disposals, meaning a working disposals mail system.

**Comment by Exxion** [comment]
Getting a mail system working on Taxi would be nightmarish, but not impossible with a setup like either of the latter two I proposed
The minimum number of mass drivers/disposal outlets with which that could be done is four, I think, but it would be really slow with fewer than five.

**Comment by PJB3005** [comment]
We need goon style belt hell for taxi

Instantly makes deliveries for cargo more easy too
