### ISSUE TITLE
[Taxi] Botany oh fucking why

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4725]
There are no xenobotany disks at botany.
There are no plantclippers in lockers.
There is only one shovel.
Backroom has no table for the non-existent disks and is too small.

Tray count is fine since you can just spam dirt trays by shoveling grass and planting in hallways.

**Comment by 9600bauds** [comment]
>Tray count is fine since you can just spam dirt trays by shoveling grass and planting in hallways.

I wouldn't say that makes it fine, if the room is cramped as fuck and has so little trays that everyone is forced to make dirt plots, it's a big issue.

**Comment by TermedClepe** [comment]
@9600bauds

Was very bad sarcasm, there's no redeeming quality about taxi botany.
