### ISSUE TITLE
[Taxi] Taxi cabs are silent killers

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4726]
There should be a check whether all airlocks to taxi are closed before movment, including the red ones, to prevent people getting spaced because taxi teleported moment before they stepped on it.

**Comment by ComicIronic** [comment]
I think it would end in people complaining about how slow it is to close a door behind themselves, because they already do that.

Not to mention people could abuse opening the doors on a taxi to annoy the people trying to leave on it.

**Comment by d3athrow** [comment]
Make the taxi forceclose the door when it leaves, regardless of whats in the way.

**Comment by wwjnc** [comment]
I think adding a lattice surrounding the taxi area (just like the R&D/cargo shuttles in box) is the way to go.
