### ISSUE TITLE
[taxi] [Needs more testing?]Pipes broken on placement on taxi send help

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4727]
Okay so while using the rpd I made some pipes to connect shit and when wrenched they cease to exist.
I did it over tiled floor
Untiled revealed no pipes
also no pipes could be placed becuase there were already pipes there

**Comment by Exxion** [comment]
Notably, in a round a few days ago, trash was mysteriously appearing in maint on top of an apparently unbroken length of disposal piping for much of the round
Not sure if it was broken at roundstart or not

**Comment by clusterfack** [comment]
This was from the machinery initialize() bug that was fixed, I missed it because it has a weird name/desc
