### ISSUE TITLE
Can't wrench pipes down as MoMMI

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4728]
This might need more testing.
I went derelict MoMMI and headed over to ghetto station on taxi station, found a place missing pipes, hit up the RPD and laid some pipes like ususal, poped out the wrench, and then, nothing, it didn't work.
I don't know if this is just me or if we should all be running around screaming at the top of our lungs panicking.

**Comment by Exxion** [comment]
No failure message or anything?

**Comment by FudgePucker** [comment]
Nope.
I think the other MoMMI last round gave up as well because there was a bunch of pipes just laying around outside the SME in space unwrenched and he was making a cat walk to heaven.

**Comment by PJB3005** [comment]
...I don't even think this is MoMMI related, I'm having the same issue as carbon.

**Comment by clusterfack** [comment]
Looks like someone broke pipe wrenching about 13+ hours ago

**Comment by clusterfack** [comment]
It's almost certainly this commit https://github.com/d3athrow/vgstation13/commit/45c898f46a406a870c2205f33a74c41a04f41585

**Comment by clusterfack** [comment]
Initialize serves a double purpose with atmospherics 'machinery' i.e. pipes, it is different from normal machines as pipes use initialize to create networks during the actual round initialization. But wrenching pipes also uses initialize IIRC, so having pipes call initialize on creation would cause this erroneous behavior.

**Comment by d3athrow** [comment]
well fuck shit

**Comment by FudgePucker** [comment]
So should I remove the MoMMI part sense everything is fucked?
Also panic.
AAAAAAAAAAA

**Comment by clusterfack** [comment]
Fixed by pomf
