### ISSUE TITLE
(WEB REPORT BY: gravelordsmaug REMOTE: 198.245.63.50:7777) Stuck inside a wall

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4730]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Was crawling through the vents as an alien and got stuck in the wall behind botany on taxi station.

>What you expected to happen
I expected to get out of the fucking vent. I had an amazing run and it really pissed me off.

>What actually happened
Everybody ganged up on me while I couldn't move and killed me.

>Steps to reproduce if possible
Go be an alien and try to exit above botany on Taxi. Absolute bullshit.

**Comment by Exxion** [comment]
I can't see why this would be the case, but there's definitely something fishy going on with pipes on Taxi.

**Comment by Exxion** [comment]
Oh, I found it. There's no pipe under Hydro's ChemMaster.
