### ISSUE TITLE
[All maps, I think] If you're going to copy and paste windows, at least be sober

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4733]
At least Box and Taxi (and probably the others) have a few instances of windows that were obviously copied and pasted badly from other places. This is characterized by:

1. Windows in the middles of long window+grill structures
2. A number of tiles together, each with two directional windows facing the same direction

On Box, this is most visible in the Vox Trading Post. On Taxi, Atmos and Bridge areas are the worst offenders.

**Comment by Exxion** [comment]
Hey
This isn't fixed

**Comment by clusterfack** [comment]
Okay then, reopen it and post some pictures of where so someone fixes it

**Comment by Exxion** [comment]
Vox trading post on Box:
![image](https://cloud.githubusercontent.com/assets/9827785/10419819/2038a6d0-7051-11e5-87eb-66e6849b5570.png)
There are also many double-stacked windows all over the asteroid

Taxi Atmos:
![image](https://cloud.githubusercontent.com/assets/9827785/10419821/6619fd02-7051-11e5-9ff3-0c78e8abf467.png)

Taxi bridge:
![image](https://cloud.githubusercontent.com/assets/9827785/10419833/9aa8669e-7051-11e5-951f-7da46eff8e8a.png)

As well as some double-stacked windows on the port halves of all three mini-stations

All double-stacked windows I can see face south

**Comment by gbasood** [comment]
I don't know of any current stupid window setups. If no one mentions any I'll close this

**Comment by Exxion** [comment]
I posted screencaps
Unless all of those were fixed it's still an issue

I'll try to search the map files to see if I can find any others if those were fixed

**Comment by PJB3005** [comment]
Erm...

That issue you're seeing is dylan's fuckup of window code (IIRC it was dylan, right?) which caused all **full-tile** windows to appear as directional ones facing south **in the mapper and map renderers.**

Which was fixed.

**Comment by Exxion** [comment]
Ah.
I see

There were (almost) definitely some that were actually duplicated somewhere but the problem is I don't remember where

I guess I'll try to figure out regex just enough to find if there still are any such duplicated windows

**Comment by Exxion** [comment]
Unless I fucked up my regex, there aren't any duplicated windows, at least anymore
