### ISSUE TITLE
Diona nymphs can resist, but lack a resist button in the HUD

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4734]
You can resist by using the verb, you just lack a convenient button.

**Comment by clusterfack** [comment]
Wait, there's a resist button?

**Comment by PJB3005** [comment]
honk

![](http://i.imgur.com/gcncWWG.png)

**Comment by clusterfack** [comment]
Surely thats the no hugging button. But anyways it ought to have hotkey just like the drop shit button next to it.
