### ISSUE TITLE
(WEB REPORT BY: badasswafflez REMOTE: 198.245.63.50:7777) Lit premium cigar sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4736]
>Revision 
2186332d230ca210671b154388a056b33b161261 

>General description of the issue
Lit premium cigars don't show up on the player sprite

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by dylanstrategie** [comment]
Most likely an error with the linked sprite, I will check
