### ISSUE TITLE
Diona can wear only certain hardsuits

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4739]
It says their species can't wear an engineering hardsuit, but they can wear an atmos hardsuit without problems.

**Comment by FudgePucker** [comment]
It is pretty confusing.
You don't even need a hardsuit as a diona, a fire suit and fire fighting helmet will actually make you space worthy.

**Comment by Exxion** [comment]
I think just internals will make a Diona space-worthy, or at least nearly so
Unless someone nerfed Dionae, which is quite possible and not a bad idea.

**Comment by AutismSpider** [comment]
They take burn damage in space.

Funny really they can use Sec Atmos Miner hard suits.

But not the Engin nuke ops and most of the soft space suits.

**Comment by Exxion** [comment]
I thought Dionae were immune to cold damage and it was just pressure that gave them issues in space

**Comment by AutismSpider** [comment]
they take cold damage form space in the end burns them.

the pressure part they heal form.

**Comment by dylanstrategie** [comment]
Caused by the way species exclusions are done, most likely
