### ISSUE TITLE
You can use the staff of change on objects brought to life with the staff of animation

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4740]
Creates mindless mobs but this should be taken note of

**Comment by ComicIronic** [comment]
Cool.

**Comment by SkowronX** [comment]
Should be kept.

**Comment by CptWad** [comment]
I will close this is a while but I just wanted to make sure we know this can happen in case of later bugs

**Comment by Arthurdentist** [comment]
two things I'd like to know, can you staff of change an inanimate player statute and what happens if you staff of change a player statue that is animated?
