### ISSUE TITLE
Buildable sound systems when.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4746]

**Comment by 9600bauds** [comment]
What do these even do?

**Comment by PJB3005** [comment]
1. Link jukebox to the radio transmitter in maint/ruskie DJ station
2. Turn on radio transmitter
3. Set sound systems to correct frequency
4. MUSIC EVERYWHERE WITH A SOUND SYSTEM

**Comment by Shadowmech88** [comment]
Please this, it sucks that we have the technology to have music everywhere but only get it in the hallways. Boomboxes exist, but I don't believe they're buildable.

**Comment by Probe1** [comment]
kurfurst mentioned he'd add them when I brought it up in the thread before his end of school vacation.  if no one else does, he'll add it.

**Comment by dylanstrategie** [comment]
The station radio should likely be a tad harder to set up and involve actually setting up the radio transmitter. And also the volume on sound systems should be fixed. 25 % volume is nice, but in reality the music plays at 100 % and becomes a massive pain in the ass after a bit

**Comment by Probe1** [comment]
dylan no.  this is one of your "lets nerf things people rarely use because I'm an asshole" moods

**Comment by PJB3005** [comment]
Yeah, I rarely see it setup, on every shift I'm engineer and remembered to do it, it was NOT setup.

**Comment by Kurfursten** [comment]
This was filled ages ago
