### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Mime breaks his vows (?)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4747]
ec3073efc7759801daa51b26c703bb4d14fda35b 

Mime no longer has the option to break his vow and speak. Only dying and being cloned allows you to speakk

**Comment by Intigracy** [comment]
someone assign me

**Comment by Intigracy** [comment]
will test/fix

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/commit/04e895865eb05141c100fb5614363becb45e7c72

This is unintuitive as fuck, jesus.
