### ISSUE TITLE
Alarm wire on air alarms & APCs

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4750]
Basically, add a wire to APCs/Air alarms which, when cut, will disable the APC/air alarm in question from showing up on alarm monitors (if there's an issue)

**Comment by 9600bauds** [comment]
There's already an alarm wire on air alarms, but I don't think it does anything

**Comment by clusterfack** [comment]
That's meant to make it show as alarming to mommis/ais/cyborgs
