### ISSUE TITLE
(WEB REPORT BY: a4brogan REMOTE: 198.245.63.50:7777) MoMMIs can take pills

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4752]
>Revision (ec3073efc7759801daa51b26c703bb4d14fda35b)

>I was goofing with chems during a round as a MoMMI (was staying out of the main station, as there was an emagged unit with one letter off of my name) And I misclicked with a pill in my claw

>I thought I would have bashed myself in the face with it.

>I somehow ate it.

>Grab a pill as a MoMMI and click yourself.

**Comment by ComicIronic** [comment]
Duplicate of #3950
