### ISSUE TITLE
Emagged MoMMIs should have their camera disabled.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4755]
Seriously, it's really shit the AI can just fuck with the MoMMIs in every one of their steps when emagged

**Comment by BestName** [comment]
Then kill the fucking AI.
It's defenseless, just ventcrawl in there and fuck its shit up.

**Comment by dylanstrategie** [comment]
Emagged MoMMIs should have their camera disabled full-stop. It's pretty ridiculous when you can casually check on the Advanced Cameras console to see where the emagged MoMMI is and what its doing
