### ISSUE TITLE
(WEB REPORT BY: sarahjohnson REMOTE: 198.245.63.50:7777) [mapping] [Box station] Nuke ops shuttle vox gear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4756]
>Revision: ec3073efc7759801daa51b26c703bb4d14fda35b 

Needs:
Emergency Nitrogen tank
Vox pressure suit/enable vox if not vox nuke op suit. You take ~20 burn even on a short jump and hack to get inside because you can't wear the exiting

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by dylanstrategie** [comment]
Not a map issue. That's a code issue. Vox aren't getting what they need to survive on spawn
