### ISSUE TITLE
(WEB REPORT BY: balkahar REMOTE: 198.245.63.50:7777) Genetics fucking broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4757]
>Revision (Should be above if you're viewing this from ingame!)
ec3073efc7759801daa51b26c703bb4d14fda35b

>General description of the issue
Can't get sick powers because Taxi apparently doesn't like genes

>What you expected to happen
Injected myself with a high block 1 injector, got weird vision, injected a low block 1 injector expecting the problem to go away

>What actually happened
nothing happened, had to take Ryetalyn to reset the gene, but then when I moved on to block 2 I got weird vision from injecting a high block too

>Steps to reproduce if possible
Play geneticist on Taxi and get unlucky, fuck I dunno

**Comment by ComicIronic** [comment]
This is not a bug: Ryetalyn doesn't reset blocks, just deactivates them, and block injectors aren't necessarily 100% effective.

**Comment by Shadowmech88** [comment]
Furthermore, the weird vision was likely a different block that mutated randomly in addition to the block you took the injector for, which happens sometimes when taking injectors. Not nearly as much as it does when pulsing a block with radiation, but it does happen.

**Comment by Probe1** [comment]
@N3X15 close
