### ISSUE TITLE
Remove airlock from RCD

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#4759]
Add in an airlock control board as a tool for silicons instead.

Now silicons can construct airlocks with proper access set and airlock spam is as annoying to build as it is to deal with.

**Comment by d3athrow** [comment]
100% silly

**Comment by 9600bauds** [comment]
200% sillycon

**Comment by NigglyWiggly** [comment]
I'm not really in any position to be giving an answer to this, but no

**Comment by TermedClepe** [comment]
Silicons can construct airlock frames with metal they can synth, this would not remove their ability to construct airlocks.

**Comment by Manaony** [comment]
Silicon can construct wall and floor easily with any material they can synth too. I don't get what your point is.

**Comment by DrCelt** [comment]
What about human RPDs? 
Is this really the best way to go about fixing the AI door issue? Are there no other alternatives?

**Comment by TermedClepe** [comment]
@Manaony
The point is that RCD airlock construction is used purely for airlock spam.

**Comment by DrCelt** [comment]
@TermedClepe I saw an engineering Borg spruce up the station with new airlocks just this morning. It's not used 'purely' for airlock spam.

**Comment by TermedClepe** [comment]
@DrCelt
The only solutions to airlock spam are to slow down airlock construction, remove airlock construction or add limits as to how airlocks can be positioned.

I'm pretty sure only one of these is logical.

**Comment by BestName** [comment]
>Silicons can construct airlock frames with metal they can synth, this would not remove their ability to construct airlocks.

Unless you're exclusively talking about MoMMIs then yes it will remove their ability to construct airlocks as they lack hands and won't be able to install the electronics.

**Comment by Probe1** [comment]
this balance suggestion didn't happen to come right after a malf round did it

**Comment by ComicIronic** [comment]
>as they lack hands and won't be able to install the electronics.

That is rather the point of including it as a module.

**Comment by BestName** [comment]
Aww shit that's what I get for only reading the title.

**Comment by dylanstrategie** [comment]
At some point down the line, Engineer Borgs would just benefit from being given an "utility arm" module that allows them to handle shit like a real human boi

Right now playing Engiborg feels like a punishment. Even Station Engineer is better, and Station Engineers are big walking targets for antagonists due to their hardsuit and the fact they are authorized almost everywhere

**Comment by ComicIronic** [comment]
Borgs will never get hands.

**Comment by Probe1** [comment]
each one of the three does something better than others.

**Comment by 9600bauds** [comment]
Really late to the party but I agree with this 100%. Borgs can currently only make access-less airlocks which is shit, and since it costs nothing and is near instant OH LOOK K.I.L.L.H.U.M.A.N.S.2000 JUST FILLED THE ENTIRE MALF AI CORE WITH BOLTED AIRLOCKS ISN'T THAT WONDERFUL
No, everything about RCD airlocks just doesn't work.

**Comment by ihadtoregisterforthis** [comment]
Wasn't the RCD made better months ago?

**Comment by PJB3005** [comment]
I made borgs not be able to set airlock access because muh airlock spawn, changing it is incredibly easy.

**Comment by gbasood** [comment]
I don't know that this has been an issue recently.

**Comment by SysadminJeroen** [comment]
Why not make the RCD use more matter when placing airlocks as a human?
Why not make the RCD use more power when placing airlocks as a borg?
Hacking bolted doors isn't really that difficult compared to removing walls, at least in my opinion.

**Comment by PJB3005** [comment]
@Jeroen52 pretty sure it already uses the most amount of matter of all the RCD schematics.

Also a depowered (on the APC) bolted door is impossible to open without RCDs or explosives (need power to raise bolts).

**Comment by SysadminJeroen** [comment]
@PJB3005 I forgot that you need power to raise bolts, my bad.
Isn't it possible to thermite the door since a few weeks? I haven't tested that code but I think that it works for walls and doors.

**Comment by 9600bauds** [comment]
Non-silicon RCD airlocks aren't an issue since matter cartridges are actually expensive as hell.

**Comment by SysadminJeroen** [comment]
@9600bauds When I used the RCD a few months ago you didn't need to, there was a way to set access in the RCD.

**Comment by 9600bauds** [comment]
Yes my bad

**Comment by Probe1** [comment]
discussions that didn't go anywhere but were never closed.
