### ISSUE TITLE
Admin Verb Quality of Life improvements

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#4760]
Some items cannot be deleted in buildmode such as centcomm walls or shuttle floors.Keep the thing stopping you from deleting people, but remove this restriction please 
I cannot mass modify datums, this would be cool to use.
I cannot mass modify a variable to be a reference to a marked object. This is depressing.
I cannot mass modify a list to add a marked object. Equally depressing.
All of these are things that have irked me as an admin and rectifying this issue would help me do cool shit

**Comment by CptWad** [comment]
>Mass modifcation
I remember one time where an admin replaced a bunch of shit with something at it quite literally broke the game.
Shits scary, yo.

**Comment by ghost** [comment]
Probably all possible with SDQL now
