### ISSUE TITLE
Canister pressure indicator doesn't go away when the canister gets destroyed.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4761]
Probably caused by #4503.

Example: 

![](http://i.imgur.com/BQf1f6u.png)

**Comment by dylanstrategie** [comment]
Clearly the icon does update since it shows a destroyed canister, but it looks like the overlay isn't removed

**Comment by clusterfack** [comment]
Yes it needs to set overlays.len = 0 when it updates to the destroyed canister icon_state
