### ISSUE TITLE
RMCE does NOT like being used on 2 machines at the same time.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4766]
Fucking hell when are we porting the RPED?

<PJB3005> I made 3 super matter bins to upgrade the protolathe and imprinte in R&D
<PJB3005> imprinter has 1
<PJB3005> protolathe has 2
<PJB3005> when I finished upgrading them
<PJB3005> there were 3 normal matter bins in the RMCE's inventory
<PJB3005> and 1 super one

@dylanstrategie

**Comment by dylanstrategie** [comment]
The RMCE is fine, it just needs to have all its problems fixed

The solution to this one is obvious, you shouldn't be able to use the RMCE on multiple machines at a time. It breaks shit

**Comment by PJB3005** [comment]
OR you can make the RMCE not take time

**Comment by PJB3005** [comment]
This can be reopened, dylan's fix didn't work completely.
