### ISSUE TITLE
When an admin plays a .midi./ogg, the filename should be displayed to every player.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4771]
Could save on everybody saying 'what song is this'

**Comment by ComicIronic** [comment]
Might break immulsions, though

**Comment by PJB3005** [comment]
Allow it to be disabled then?

**Comment by Exxion** [comment]
>Now playing: sad.midi
>Now playing: WELCOME_TO_HELL.ogg
