### ISSUE TITLE
[taxi] Vox outpost has shit mapping

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4772]
* The windows above atmospherics have no glass, only griles
* Valve on the scrubbers loop is fucked
* No lights in atmos
* No air alarm in EVA
* magic floating double air alarm in atmos
* Better airlock needed between the O2 and N2 areas
* Scrubbers set to meatbag mode
* External cycling airlock has no controller
* ALL THE WINDOWS have no grilles
* No APC in the main hallway
* No youtool

**Comment by Exxion** [comment]
A few of these are also present on the Box one
The scrubbers and the missing EVA air alarm, as well as general window fuckery

Also the trading floor area is almost (if not totally) identical to how the Box one was before #3057, so it *should* be possible to pretty much just copy that changed area over to Taxi.
It's worth noting that the airlock setup now present on Box is not perfect, but it is much better than before
Now, the O2 area very slowly builds up N2 with enough airlock use, but the N2 area stays below 1% O2
