### ISSUE TITLE
(WEB REPORT BY: grizdale REMOTE: 198.245.63.50:7777) salvage ship forever in hyperspace

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4775]
salvage ship stays in hyperspace untill a new location is choosen if you attempt to go to clown asteriod on taxi station

**Comment by 9600bauds** [comment]
Also happens with the Derelict button.

**Comment by FudgePucker** [comment]
The Derelict not working seems pretty fucking silly considering that there is even a dock for it.
Also taxis being able to go to derelict station if it has enough power put into it and buttons fixed when? I want to make a ghetto station for people to go to relax when the stations go to shit as an autistic crab robot.

**Comment by 9600bauds** [comment]
Still an issue?

**Comment by clusterfack** [comment]
No
