### ISSUE TITLE
(WEB REPORT BY: chickenzness REMOTE: 198.245.63.50:7777) PDA with ID vanished.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4785]
>Revision: 0718abc0c741591caf9cc432612eead45dbeb87e 
>PDA with ID disappeared.

>Send a message to the AI then put my PDA back on my ID slot.

>I sent the message then clicked the ID slot and PDA wasn't in my ID slot or my right hand.

>Not sure. Was in cargo bay at the time. No Admins on at the time also.

**Comment by Imagebard** [comment]
Why do old as fuck issues with the "Needs Moar Testing" label stay open, anyways? Not like they're going to help.
