### ISSUE TITLE
Bluespace crystals can be used on z-level 2

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#4787]
Allows you to get to centcomm using the salvage ship, and from centcomm to many other places (wizard's den, syndie base etc)

**Comment by PJB3005** [comment]
IT'S A FEAAAAAATUUUURE

**Comment by clusterfack** [comment]
Panic

**Comment by 9600bauds** [comment]
how the fuck did nobody notice this until now?

**Comment by PJB3005** [comment]
I did think of it, I was fully aware this was possible.

# HONK

**Comment by Exxion** [comment]
Maybe keep them usable, but have them send you to Z-level 6 if used on Z-level 2 or something
Z-level 6 is entirely empty except for a tiny circle and the salvage ship (if it hasn't been moved)
