### ISSUE TITLE
(WEB REPORT BY: chickenzness REMOTE: 198.245.63.50:7777) Check in/out computer couldn't find books.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4789]
> Revision: 5d930fa379b877820d2da514ffedcdaeeb749ec8 
> 
> Couldn't find any books after searching and couldn't reset after searching
> 
> To be able to search and print books.
> 
> There were no books and when making the search empty you couldn't get back to the list.
> 
> Use the computer, I'll have a look next round if it does it again.

**Comment by ComicIronic** [comment]
That's odd.
But was this the main computer, or one of the computers that just logs the books in the library itself?

**Comment by 9600bauds** [comment]
Needs Reproducing

**Comment by 9600bauds** [comment]
Seems to work, reopen if issue persists
