### ISSUE TITLE
Mech fabricators have their queue on top, which is weird and annoying

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4791]
Let's say we want six borg left arms
http://puu.sh/i7uKF/a722dd9035.webm
needlessly tricky

**Comment by PJB3005** [comment]
IMO, we shoul use the same UI layout as the old exosuit fab had, materials on top, selection of what to build in the middle, queue on the right

**Comment by Probe1** [comment]
I mentioned that to comic while looking over his autolathe buff.  Putting the queue at the bottom solves all the woes.

**Comment by clusterfack** [comment]
Or putting it on the left/right even? I don't understand why people keep putting things at the top or bottom other than its piss easy to code.

**Comment by ComicIronic** [comment]
If you can figure out a way to do it on the right, by all means, do.
But nanoUI is an undocumented monstrosity at the best of times.

**Comment by Probe1** [comment]
having designs on the left and the queue on the right for all nanoui fabricators would be terrific.  

just having the queue at the bottom of everything would be an immediately achievable improvement.  the only one that really chafes people is the exofab.  and my god is it annoying.  oh you want four robot arms?  click move cursor click move cursor click move cursor suicide click move cursor succumb

**Comment by PJB3005** [comment]
@ComicIronic, it isn't that poorly documented.
