### ISSUE TITLE
(WEB REPORT BY: yred REMOTE: 198.245.63.50:7777) Thrown items travel perpendicular to throw direction and grant no propulsion.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4794]
>Revision 19f8657d318a56fc983453fb1e46f62ea7efa7af 

Can replicate consistently currently, but there seems to be some special conditions because it was working properly about ten minutes ago.

**Comment by Exxion** [comment]
Dammit
Too bad this is a web report. It makes asking the reporter about specifics much harder.

In case anyone else has seen it, in which directions does it happen? Does it, by chance, happen only when the click to throw is on the same tile as the thrower?

**Comment by clusterfack** [comment]
There's been a whole physics update between now and then
