### ISSUE TITLE
Give the Chef a Dropper

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#4795]
I know there are ways to isolate 1u of things using existing kitchen equipment, but they're all hacky or roundabout and I think it would just be easier to put a dropper in the chef's backroom. It isn't even a sensitive item.

**Comment by ComicIronic** [comment]
What would a chef need 1u for?

**Comment by 9600bauds** [comment]
Turkey

**Comment by FudgePucker** [comment]
Chef has infinate dropers because of the condiment bottles.
Can't droppers be used as a hypospray on people with no masks on or does it have a "Someone is trying to blablabla" message pop up?

**Comment by 9600bauds** [comment]
Considering the Chef has access to Botany, and the Botany dispenser has syringes, I wouldn't say eyedropper squirting is a big deal (if it even works as hypospray, I haven't tested it)

**Comment by FudgePucker** [comment]
Syringes have a pop up unless you harm intent them.
A dropper in kitchen would be useful for boatany traitors if it does act like a hypospray.

**Comment by 9600bauds** [comment]
You could use a dropper which will completely fail if the user has anything on their eye slot, or a harm syringe.

You do the math.

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.
