### ISSUE TITLE
DJ Station Sleeper has a console

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4796]
It's supposed to be a non-functional sleeper, after the medcondecon update it now has a console that is inside the window it's against.
Happened in Taxi, untested in others

**Comment by clusterfack** [comment]
Panic

**Comment by 9600bauds** [comment]
Picnic

**Comment by FudgePucker** [comment]
Whats wrong with having a working sleeper all the way out there in space?
You are in the middle of space, it would be a little help if you could have a buddy heal you up.

**Comment by 9600bauds** [comment]
I think it's supposed to be like a cryostasis type of deal, purely for flavor. Regardless it's clearly supposed to not have a console since it's right up against the window

**Comment by FudgePucker** [comment]
Can't you just flip it?
Kinda hard to have it be cryostasis with no sleeptox.

**Comment by 9600bauds** [comment]
[map issue (Taxi)]

**Comment by Exxion** [comment]
Is it really just Taxi? I'd expect all of the maps to have this issue, given that the medcondecon update you're referring to made sleepers automatically create their consoles.

**Comment by 9600bauds** [comment]
Most likely, I didn't check tho

**Comment by Probe1** [comment]
is this really a bug?

**Comment by PJB3005** [comment]
All maps have this.

**Comment by gbasood** [comment]
This issue could be resolved by adding a boolean to individual sleepers to prevent auto-generation for intentionally broken sleepers.

**Comment by Imagebard** [comment]
It seems like people would love to have a sleeper in space, so consider if you really want to remove it.

**Comment by Exxion** [comment]
There are sleepers in space
Abandoned medical ship
It even has cryo

**Comment by ghost** [comment]
@gbasood Not a bug

**Comment by gbasood** [comment]
No, it is a bug.

The sleeper console literally spawns **INSIDE WINDOWS AND A GRILLE**

**Comment by 9600bauds** [comment]
![dreamseeker_2016-02-05_20-15-54](https://cloud.githubusercontent.com/assets/6526157/12861883/593389be-cc45-11e5-9439-6f9dd7dd7918.png)
Verily it be a bug
