### ISSUE TITLE
Feature loss? Summon guns is kill

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#4797]

**Comment by Probe1** [comment]
add details you bog wench

**Comment by ComicIronic** [comment]
Need more information. 

Was this during a wizard round, or Ragin Mages?

**Comment by Probe1** [comment]
It was during Ragin Mages but that's the limit of what I know

**Comment by ComicIronic** [comment]
THEN IT IS NOT A BUG, HAHA

**Comment by PJB3005** [comment]
I like this, I hate summon guns because everybody takes it as a warrant to grief.

**Comment by DrCelt** [comment]
>can't use summon guns in raging mages
since when?

**Comment by PJB3005** [comment]
Maybe make this into a "summon guns in ragin' mages Y/N" discussion, then?

**Comment by DrCelt** [comment]
yes but since when was it disabled?

**Comment by ComicIronic** [comment]
Since Pomf removed it in March last year, in 9e160449b457f5bea6396356c9d68066572a3bb0

**Comment by DrCelt** [comment]
;-;
