### ISSUE TITLE
Bees still kill off diona pods from from invalid fertilization

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4799]
If you have bees and diona pods in the same room they get deleted.  I forget the exact reason it was something like they fertilize them over the maximum limit a plant can be fertilized and they disappear.  Fix pls.

https://github.com/d3athrow/vgstation13/issues/3328

https://github.com/d3athrow/vgstation13/issues/4127
https://github.com/d3athrow/vgstation13/issues/3182

**Comment by Ephx1** [comment]
Who needs greentide when you have your good buddy bees?

**Comment by Exxion** [comment]
[BEEEEEEEEEEEEEES] label when

**Comment by clusterfack** [comment]
When this stops being a duplicate issue somehow, also the only reason I haven't fixed this is I dont know where in the code its treated and my waifu cntrl f isn't helping.

**Comment by Probe1** [comment]
I just want it fixed.  It's been 2 months and diona pods have since been nerfed to result in less seeds so the effects of losing one to bees are even more costly than before.
