### ISSUE TITLE
(WEB REPORT BY: entya REMOTE: 198.245.63.50:7777) Power and Spell tabs bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4801]
>Revision (Should be above if you're viewing this from ingame!)
19f8657d318a56fc983453fb1e46f62ea7efa7af

>General description of the issue
Spell and Mutant Powers tab just shows the cooldown of the spell or power without the name, also unable to use powers from them

>What you expected to happen
To be able to use powers from that tab

>What actually happened
Nothing

>Steps to reproduce if possible
Try using powers from the tabs

**Comment by ComicIronic** [comment]
This happened when I made them datums, because you can't click a datum and that was the system they were using in Byond's inbuilt tab system. It was actually why they were objects in the first place before the spell HUD buttons came along.

**Comment by clusterfack** [comment]
Why are the cooldowns still in the tabs is the actual question I'm wondering about
