### ISSUE TITLE
(WEB REPORT BY: nmsct699 REMOTE: 198.245.63.50:7777) Empty suit storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4804]
>Revision (Should be above if you're viewing this from ingame!)
19f8657d318a56fc983453fb1e46f62ea7efa7af 

>General description of the issue
suit storage always looks empty when open

>What you expected to happen
sprites showing things in the suit storage unit when opened and containing things

>What actually happened
nothing appears to be inside even when full with helmet/suit/mask/boots

>Steps to reproduce if possible
open full suit storage unit

**Comment by Probe1** [comment]
its tied to when power goes out.  the SSU's pop open when power fails but the sprites don't update what's inside.  it'll just show an empty SSU.

i think it fails to update all the time now but that was an older (and still existant) issue.
