### ISSUE TITLE
Plastic walls disappear upon construction

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4810]
Build wall girder, add plastic, wall girder is gone.

**Comment by Exxion** [comment]
That would be because they don't exist, I do believe, but there's no sanity to keep the game from trying to build them anyway

And #3152

**Comment by CptWad** [comment]
>Plastic walls 

Oh please let it be see-through

**Comment by clusterfack** [comment]
That's actually really easy to do

**Comment by Exxion** [comment]
Is this fixed? Looks like the PR to fix it may or may not have been migrated to Gitlab and merged there.

**Comment by PJB3005** [comment]
I don't think it was merged on GitLab.
