### ISSUE TITLE
After deconstructing the derelict teleporter machines the parts and boards did not appear

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4811]
I was left with a few sheets of metal and wires but nothing else.  No parts, no boards.  Just a machine frame with wires added.

![ss 2015-06-02 at 11 40 46](https://cloud.githubusercontent.com/assets/8550416/7940089/a40f4938-091c-11e5-9565-a99570f9d8b0.png)

**Comment by ComicIronic** [comment]
An issue with the components not being set in New()

**Comment by 9600bauds** [comment]
Dynamic resource adjustment for asshole MoMMIs breaking the teleporter
It's a feature

**Comment by clusterfack** [comment]
But comic deconstructing this has worked in the past unless either someone changed it explicitly, or its that phantom bug where components are mysteriously disappearing when machines are deconned.

**Comment by ComicIronic** [comment]
Then did someone RCME all the components out?

**Comment by Probe1** [comment]
no, the machines were working perfectly fine before I deconned them.
