### ISSUE TITLE
Mommi tools are stuck in hand slot but unable to function

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4812]
I don't even know how to explain this.  I set the RPD to Unary vent, clicked twice on a tile to place two and it said building pipes but never completed.  When I investigated I found I was able to add any number of tools to my hand slot but could not use any of them.  On closing the item container UI they returned to their normal positions but were still unusable.  

![ss 2015-06-02 at 12 21 16](https://cloud.githubusercontent.com/assets/8550416/7940975/3fa350a6-0922-11e5-89a8-b9c5fd4f5c4c.png)

![ss 2015-06-02 at 12 22 48](https://cloud.githubusercontent.com/assets/8550416/7940977/414e9226-0922-11e5-8923-f68ed1ad29a4.png)

**Comment by Unfit** [comment]
I've experienced the same bug before, I believe it happens when you're low on power

**Comment by Probe1** [comment]
I ghosted and got a new mommi shell and it did indeed make the bug go away.

**Comment by clusterfack** [comment]
Yeah it's a literally decrepit bug from low power mode for mommis that doesn't store objects and allows you to take objects into your hand as well

**Comment by clusterfack** [comment]
This bug has existed forever it is probably as old as mommis
