### ISSUE TITLE
Wizard spell bugs

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4813]
After doing mindswap, getting muzzled and injected with a mute SE, then unmuzzled and injected with a clean SE:

No spell icons were visible, I seen a spell tab and in it were only spell cooldowns without names that I couldn't click, 60/60 10/10 etc.

I was unable to read single spell books for the spells I already had.

After monkeying myself with a clean monkey SE, I was able to read the very same spell books, I lost all my spells except the 2 I read as monkey. Afterwards I mindswapped into another human and became identically bugged as before being a monkey.

I tried reconnecting multiple times, it never helped.

**Comment by ComicIronic** [comment]
I believe transforming making you lose your spells is a deliberate thing Pomf added to stop the Staff of Change giving people construct spells and never taking them away.

**Comment by TermedClepe** [comment]
@ComicIronic
Problem is that I didn't transform and still 'lost' all spells, I got injected by human SE with mute gene, then injected with clean human SE and it completely bugged everything, I still seen the spells in spell tab without names.

**Comment by clusterfack** [comment]
That would be a spell master hud issue I've been trying to fix. Which unfortunately was compounded by the fact that spells were made unclickable in the spell tab.

**Comment by ComicIronic** [comment]
I was talking about the monkeying.
