### ISSUE TITLE
(WEB REPORT BY: senaat1 REMOTE: 198.245.63.50:7777) Mining treasure rooms can be generated inside the Vox Outpost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4814]
Revision: 8390b446fc8a2a110c22abc234e01686eddfb801 

It's possible for the randomly generated room on the asteroid to get superimposed over the Vox outpost, see image: http://i.imgur.com/ZE9IPqC.png

**Comment by 9600bauds** [comment]
#4776

**Comment by ComicIronic** [comment]
Damn you, web reporter. Duplicate.
