### ISSUE TITLE
No ghetto alternative for debraining severed heads

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4815]
You can debrain a guy with a hatchet, a knife and a lighter.
But if his head was already off, you're shit out of luck because only a bonesaw and a scalpel will work.
Most often seen with chefs trying to make braincake and needing kosher surgery tools to do so.

**Comment by Probe1** [comment]
is there an alternative for the surgical saw?

**Comment by 9600bauds** [comment]
Yes for normal surgery, no for severed heads
