### ISSUE TITLE
TV monitor in engineering is rotated improperly.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4816]
should be twisted 90 degrees to the left, right?

![ss 2015-06-02 at 06 20 42](https://cloud.githubusercontent.com/assets/8550416/7950068/b7fca7dc-0963-11e5-9403-0f800bfb6103.png)

**Comment by IratePirate** [comment]
The .dir must have been varedited in the map editor to 8 from 1 despite there previously not being dir. sprites for telescreens. Odd.

**Comment by Probe1** [comment]
binary strikes fear into the hearts of mappers

**Comment by clusterfack** [comment]
Git blame when

**Comment by Probe1** [comment]
There are multiple monitors with issues I've found, it's not just limited to this one.  All the same issue though.
