### ISSUE TITLE
(WEB REPORT BY: chickenzness REMOTE: 198.245.63.50:7777) Vox outpost is not safe for vox. (Taxi station)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4817]
>Revision: 9ab63cbd151069ddd9a1ee089a57a3519f583817 
>Vox outpost has oxygen in it.

>To be able to take off the internals as a vox.

>Recieved damage from toxins.

>Analyze air in the outpost on Taxi station.

**Comment by Exxion** [comment]
Someone probably entered through the trading floor. The door between them was made by a complete idiot.

Unless this was the case at roundstart, almost certainly caused by part of #4772.

**Comment by PJB3005** [comment]
Nah, I don't think there's any O2 floors
