### ISSUE TITLE
Storage atoms

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#4821]
Many objects meant to have mobs placed inside simply place the mob into contents and keep a variable with a reference to that mob. The problem is, mobs are complicated and sometimes drop things. If they drop something while in such an object, they can kiss it goodbye, because it's forever lost to nullspace.
This could be remedied by instead placing the mob into a storage atom within the object and dumping that storage atom's contents when the mob is removed.

Objects that need to be fixed:
- [ ] Xeno stomachs
- [ ] Mechas
- [ ] Sleepers
- [ ] Spacepods
- [ ] Body scanners

Some of those (at least mechas and probably some others) actually work and don't nullspace items dropped in them, but _how_ they work is not like this. Maybe they should be set up this way or maybe they should be left as-is; I'm not really sure.

Tell me if I missed anything so I can add it to that list.

**Comment by clusterfack** [comment]
Most of those already have those behaviors, on mob exit dna scanners, sleepers, adv scanners, and mechs already drop the rest of the contents dropped.

**Comment by Exxion** [comment]
See the two sentences after the list

**Comment by ComicIronic** [comment]
The mecha system isn't ideal.
For example, if you're carrying a piece of mech equipment and you accidentally drop it in the mech, it won't be ejected.
