### ISSUE TITLE
Move a shitton of 1 line helper procs to #defines

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4822]
Seriously, it's _slightly_ faster (probably could make a difference in the case of something VERY common like Clamp() too)

Then again compile time & possible binary size might be a little bigger

**Comment by Exxion** [comment]
Who cares about compile time? Starting up the server takes several times longer than compiling anyway

**Comment by ComicIronic** [comment]
If anyone is interested in doing this, the place to put them is the _macros file, which specifically comes as close to the top of the build order as possible.
