### ISSUE TITLE
BUTTBOTTS BROKEN

### ISSUE THREAD

**Issue by kilkun** [d3athrow/vgstation13#4825]
THEY NO LONGER REPLACE YOUR WORDS WITH BUTT

THEY NO LONGER SAY BUTT ON THEIR OWN

Literally why? It's like if you removed beepsky's baton, or the Captain's all access.

**Comment by clusterfack** [comment]
Possibly broken by languages?

**Comment by kilkun** [comment]
Code was removed, according to bumbling

**Comment by clusterfack** [comment]
I highly doubt that

**Comment by clusterfack** [comment]
![](http://puu.sh/ibGoM/8d4b341e11.png)

**Comment by kilkun** [comment]
then is bug and the report is super justified now.

pls fix

**Comment by AutismSpider** [comment]
Bug with the new say code then.

Butt bots are not up to-date then.

**Comment by clusterfack** [comment]
I think it was languages they have definitely been working since TG say code

**Comment by ConkerDev** [comment]
weren't virtual speakers fixed?

**Comment by clusterfack** [comment]
Oh yes I fixed this with virtualhearers, did I not close the issue?
