### ISSUE TITLE
The Bhangmeter still reports explosions if broken

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#4828]
Can't tell if that is fully intended or an oversight. While it makes sense that a broken screen wouldn't stop the Bhangmeter from broadcasting information, the broken screen with a BSOD heavily implies that broken computers have more things broken than their screen

**Comment by ComicIronic** [comment]
You can fix any computer by removing the broken glass and putting a new screen in, so perhaps not.

**Comment by PJB3005** [comment]
Let's be honest the only reason it's so easy to repair is that needing to get a new fucking circuit from R&D/mechanics/tech storage to fix computers is a PAIN

**Comment by ComicIronic** [comment]
But now we have the magic of the soldering iron, so we can make it break the circuit!
