### ISSUE TITLE
(WEB REPORT BY: grizdale REMOTE: 198.245.63.50:7777) cryokenesis

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4831]
>cryokenesis not working when I have a lot of powers

>I assume it's one power knocking it out but it appears on my magic bar just does nothing

>I expected it to work

>it didn't work

>give yourself lots of genetic powers till cryokenesis doesn't work it looks to be easily replicable as this has happened a few times to me

**Comment by ComicIronic** [comment]
Duplicate
