### ISSUE TITLE
Research Director has very little access to the Communication Console and its features

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#4832]
The Research Director, the man who directs research on a research vessel, which was created to have research conducted aboard it, can't send CentComm messages to report the science team's findings, can't call an ERT to extinguish toxins, can't raise the alarm once the slimes break out, he can only call the shuttle or change the status display's contents. 
![image](https://cloud.githubusercontent.com/assets/10002997/7989943/04da5822-0af6-11e5-87eb-291341077059.png)

**Comment by ComicIronic** [comment]
>can't call an ERT to extinguish toxins,

Because that is atmos' job. All the necessary emergency services are conveniently located on the station.
Also why would an RD be able to change the alert level? They don't have any sec clearance.

**Comment by Probe1** [comment]
Yea you need a captain to do it.  Or if the situation warrants it two heads and skip to red.

**Comment by DrLeprikon** [comment]
That was an oversight on my part, it is atmos' job to extinguish toxins, but I feel it would still be reasonable to allow the RD to call an ERT. The access I miss the most is that needed to message CentComm and make public announcements, I've seen the HoS, the CMO and even the HoP make announcements, but maybe I'm missing something and they have some special console for that. But right now the Communication Console is pretty much useless for the RD, except when the shuttle needs to be called, which I think shouldn't be the case. It also encourages people to steal the gold spare when they're the only head since the RD has no reasonable way to declare to the station that he will be taking on the role of the acting captain.

**Comment by Probe1** [comment]
the other heads have a personal announcement console in their offices.  the rd misses out, though i'm not sure why.  it doesn't have to do with the communications console or alert levels.

**Comment by DrLeprikon** [comment]
Is that worth fixing? Should I keep the issue open? I feel like I've been too rash with my decision about opening an issue...

**Comment by Probe1** [comment]
sure, leave it open.  if someones interested in coding (copying and pasting and changing CE to RD) a console for the RD they will.
