### ISSUE TITLE
Mindswaping causes all your spells to be bugged

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4836]
Mindswap to anyone, preferably someone with a mutant ability, all your spells will be unusable.

**Comment by Shadowmech88** [comment]
I know that there is a chance to lose your spells when you mindswap, but I'm not sure if that's what happened here.

**Comment by TermedClepe** [comment]
@Shadowmech88
There is no code that makes you intentionally lose spells on mindswap.

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/spells/targeted/mind_transfer.dm

**Comment by Shadowmech88** [comment]
Oh. I've always heard it did, and then there's that flavor text about memory loss in the spell book:
![mindswap](https://cloud.githubusercontent.com/assets/3991927/7998321/120c20b6-0b00-11e5-96df-d81b225eff7a.PNG)
Not sure what's causing it in your case then.

**Comment by clusterfack** [comment]
Well, spell_masters are mob based not mind based.

**Comment by ComicIronic** [comment]
It's because it doesn't add_spell

**Comment by TermedClepe** [comment]
@Shadowmech88
It wouldn't make sense to randomly lose spells, there's already much stronger spells that don't cripple you with paralysis on use. If it paralyzed you AND removed spells then it would be near useless.

**Comment by ComicIronic** [comment]
This should no longer be an issue.
