### ISSUE TITLE
(WEB REPORT BY: teaiofj REMOTE: 198.245.63.50:7777) Ghetto Surgery atmos not simulating

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4841]
All the tiles in the ghetto surgery do not interact with other tiles, including the others in ghetto surgery. Syphoning one tile only syphons that one tile, venting only vents the one tile etc.

**Comment by Exxion** [comment]
For some unfathomable reason, the floors in ghetto surgery are varedited to blocks_air = 1

**Comment by clusterfack** [comment]
That actually is in fact literally unfathomable. If someone fixes that it'll get map priority just after comic's firelock changes go through

**Comment by Exxion** [comment]
Can easily be fixed in the text editor, which would be unlikely (though not impossible because the map merger does some weird shit occasionally) to conflict with the firelock changes

**Comment by Duny-** [comment]
Is this fixed?
