### ISSUE TITLE
cham-projector deactivates when put in pocket

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4842]
used to be that you could put it in your pocket for max mobility. But now, no.

**Comment by Shadowmech88** [comment]
My guess would be that it's intentional.

**Comment by Probe1** [comment]
It wasn't always so and I'm surprised if it was intentional.

**Comment by dylanstrategie** [comment]
This is fully intended, you need to hold the thing to be cloaked, so that you can get disarmed/airflowed and decloaked

Either way, putting things in your inventory fires Dropped() I believe, so that would be an extremely annoying fix
