### ISSUE TITLE
MoMMI using material synth

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#4845]
Related to an old forgotten issue https://github.com/d3athrow/vgstation13/issues/4084

Trying to synth materials says "You can't make that much plastic without shutting down!"
It doesn't produce any sheets.
It still drains the synth charge, resulting even in negative charge on the material synth.

**Comment by PJB3005** [comment]
I don't even think you're supposed to be able to use the non-MoMMI math synth as an MoMMI.

**Comment by 9600bauds** [comment]
You're not, borgs aren't even supposed to be able to scan new types of materials.
