### ISSUE TITLE
Placing a lit flare in the autolathe leaves an infinite light effect on the player

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#4848]
Light a flare
Toss it in the autolathe (it counts as glass?)
Revel in the light

Effect goes away when another flare is picked up, lit or otherwise.

**Comment by Exxion** [comment]
Oh not again
Light bugs like this are bizarrely common

**Comment by 9600bauds** [comment]
IT NEVER ENDS

**Comment by ComicIronic** [comment]
Should use drop_item

**Comment by SonixApache** [comment]
Found that if you let enough time between picking up a new flare, the light effect can stack.
Problem does not persist with new lighting system.

**Comment by dylanstrategie** [comment]
Most likely does not fire Dropped(), that's a problem with the Autolathe code

**Comment by ComicIronic** [comment]
Still an issue?

**Comment by dylanstrategie** [comment]
This has been tested and no longer occurs, placing a lit flare in an Autolathe doesn't give such an artifact anymore
