### ISSUE TITLE
Latejoining as a Vox during Heist [Language Issue]

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#4850]
If you late join the game as a vox during the heist game mode, you arrive at the station unable to speak any language other then Vox Pidgin. This does not apply to regular station vox who started from the beginning.

To test:
1. Wait until its heist
2. Late join as a vox 
3. Walk around screeching at everyone because you can't understand them and they can't understand you.

**Comment by PJB3005** [comment]
I can confirm this.

**Comment by ghost** [comment]
@d3athrow , this has been fixed can we leave the feature freeze now?

**Comment by gbasood** [comment]
Duplicate issue of this was literally JUST closed
