### ISSUE TITLE
Robotic / Prosphetic Butts

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#4851]
Once you have lost your Butt either to surgery or the butt bot spell, there is no way to receive a new butt. You cannot surgery the old one back on and so you are forever cursed to be unable to sit down. 

We need robotic butts for replacement surgery.

**Comment by TermedClepe** [comment]
>He has a peg butt.
Needs wood alternatives.

**Comment by Arthurdentist** [comment]
Wooden butts should occasionally fail when you try and sit down

**Comment by PJB3005** [comment]
Butts are just dumb in general.

**Comment by Arthurdentist** [comment]
PJB3005 is dumb in general

But seriously so long as we do have butts then there needs to be a way to reattach them at the very least. The only fix is cloning.
