### ISSUE TITLE
(WEB REPORT BY: kurfurst REMOTE: 198.245.63.50:7777) General Sprite Issues

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4856]
>Revision
f31d8eba00c3fcd865ac4467e62b73601f8c5c1f

>General description of the issue
Sprite issues were noticed after admins bussed in noir-darkened station

* RPD would display in hand even when put away
* Clipboard also shows this behavior
* Hardsuit would appear to be worn even when removed (and even at the same time as other things, like flashlighthelmet)
* Xenoarcheologist reported his excavation suit sticking as well
* Advanced hardsuit helmet darkened with station, becoming a different tint than advanced hardsuit, which remained brighter
* Police tape did not properly change sprite when raised and lowered

**Comment by ComicIronic** [comment]
The hell did they do to the icons?

**Comment by PJB3005** [comment]
I blame adminbus

**Comment by Intigracy** [comment]
Can't fix something we can't reproduce.
