### ISSUE TITLE
Every single scrubber set itself to remove o2 and n2 simultaneously.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4857]
[Box, Panic?] 

About 20 minutes into the round every single scrubber simultaneously started removing O2 and N2 on the main z level of Box.  There were two exceptions:  Telecomms and the RD server room.

The asteroid z level was different.  Almost all the scrubbers in the Research Outpost were set to remove O2 and N2 but the Mining Outpost was unaffected.

**Comment by Probe1** [comment]
This also occurred during the previous round.

**Comment by PJB3005** [comment]
100 % sure this is somebody using a GIGANTIC script with the AAC

**Comment by Probe1** [comment]
I'll be shocked.

**Comment by PJB3005** [comment]
Hey, I've done it before, though that was setting all vents on the station to 400 kPa external pressure, and I only got to the first ~150 because I didn't prepare and make something beforehand.

**Comment by Probe1** [comment]
I'll reopen this after further testing, PJB's explanation is reasonable.

**Comment by Probe1** [comment]
@PJB3005 was completely correct in his assessment, it was the AAC.
