### ISSUE TITLE
Hard to tell when someone is speaking inside a mech

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4858]
There is no speech bubble, the chatbox displays only the pilot's name with no indication that they are inside a mech, and the mech doesn't let you see who's inside. I more often than not have to clarify "i'm the guy in the big robot" while people look for me.
When using the mech radio, the message actually shows an icon of the mech and the mech's name, this really oughta get applied to normal chat messages as well.

**Comment by Unfit** [comment]
Same with brains in MMIs as well

**Comment by 9600bauds** [comment]
Doesn't the MMI say whose brain it is, though?

**Comment by PJB3005** [comment]
Yes

**Comment by 9600bauds** [comment]
Maybe display the MMI icon before the brain's name,then. I have no idea how to make the speech bubble work though.

**Comment by 9600bauds** [comment]
Closing this since I consider the bubble to be sufficient
