### ISSUE TITLE
(WEB REPORT BY: tersr REMOTE: 198.245.63.50:7777) Red X called "Flash" replace tiles.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4862]
>Revision (Should be above if you're viewing this from ingame!)
b1cf0b6121dca8a3f65a272bd69bf8aff5f8

>General description of the issue
Screen replaced with red Xs

>What you expected to happen

>What actually happened

>Steps to reproduce if possible
No idea

**Comment by PJB3005** [comment]
Er, UI pooling again?

the "flash" atom is used in the UIs, I think

**Comment by clusterfack** [comment]
Oh pooling, you so silly
