### ISSUE TITLE
(WEB REPORT BY: askaris REMOTE: 198.245.63.50:7777) Hearing Changeling chat as borg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4863]
>Revision (Should be above if you're viewing this from ingame!)

83552647a5f2a27128bffdeab1f74b8dd2d47bff 

>General description of the issue

Began as roundstart cyborg. Destroyed and ghosted, later resurrected by robotics. Could hear Changeling chat after resurrection.

>What you expected to happen

After resurrection, expected to no longer be able to hear changeling chat (had ghosted in the meantime).

>What actually happened

Could hear changelings conversing despite not being a ling at any point.

>Steps to reproduce if possible

Be borg, be totally destroyed by rabid slimes, have subspace broadcasting turned off on radio on death, ghost while dead, be repaired rather than receive a whole new chassis.

**Comment by ComicIronic** [comment]
I'm going to guess that mobs aren't being removed from Observers.

**Comment by gbasood** [comment]
Has anyone encountered this issue recently?
