### ISSUE TITLE
Space can be renamed

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#4869]
I can call it "lelfaggetz" or some other shit. Occurred after the new lighting merge.

**Comment by 9600bauds** [comment]
How tho

**Comment by SkowronX** [comment]
Via blueprints

**Comment by 9600bauds** [comment]
Hilarious

**Comment by SkowronX** [comment]
You don't understand though. New areas can't be made because of this.

**Comment by Probe1** [comment]
That makes it much more hilarious.

Also you should have gotten a message *The new area must be completely airtight!*  Where specifically were you and on what map?

**Comment by SkowronX** [comment]
Further information. Usually when you open the blueprints in space it shows a message such as "According to the blueprints, you are in outer space. Hold your breath!" Opening it as of now just shows a regular message like you are in a room on the station.

**Comment by PJB3005** [comment]
hm, whoops, I'll see what caused this.

**Comment by FudgePucker** [comment]
So now I can not only rename every room on the station "benis" but I can rename the whole UNIVERSE?

**Comment by ComicIronic** [comment]
The benis quadrant

**Comment by PJB3005** [comment]
Found the source of the issues: the blueprint code would only assume space as space if it had a tag, for some reason.

Working on a fix.
