### ISSUE TITLE
(WEB REPORT BY: tersr REMOTE: 198.245.63.50:7777) Cargo shuttle broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4870]
>Revision (Should be above if you're viewing this from ingame!)
12acc8411451d61216c36f288d3db75cf1ce984e

>General description of the issue
Cargo shuttle is broken

>What you expected to happen
Cargo shuttle to be therre when it says it's docked

>What actually happened
Nothing happened when shuttle is docked

>Steps to reproduce if possible
Send shuttle.

**Comment by clusterfack** [comment]
I've never seen this occur

**Comment by Zth--** [comment]
Supply shuttle code has changed since. Close it
