### ISSUE TITLE
New lights are fucked for me

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#4872]
![neckbear death-trap lima 2015-06-07 000824](https://cloud.githubusercontent.com/assets/9064611/8022951/73cc1a38-0cc0-11e5-865e-77785adce6ad.png)
![neckbear death-trap lima 2015-06-07 001410](https://cloud.githubusercontent.com/assets/9064611/8022952/73cf8894-0cc0-11e5-8d28-443b124532c7.png)
![neckbear death-trap lima 2015-06-07 000810](https://cloud.githubusercontent.com/assets/9064611/8022953/73cfc534-0cc0-11e5-8ad9-3f0c8078bb04.png)

Pomf said to disable the "use graphics hardware for displaying maps" thing, and I did, but it didn't change anything.

**Comment by clusterfack** [comment]
RIP

**Comment by PsiOmegaDelta** [comment]
Are you sure he didn't mean Enable?

**Comment by PJB3005** [comment]
Yeah, are you sure it's enabled?

This isuse can be bypassed by getting mesons/nvgs, or lowering your mob's see_in_dark

**Comment by NigglyWiggly** [comment]
I usually have it enabled, so I doubt that would do much at this point

**Comment by clusterfack** [comment]
What kind of hardware are you using?

I mean at some level it might be worth a byond bug report.

**Comment by NigglyWiggly** [comment]
Oh wait, they're working for me now.
Strange, I'll close this for now, I guess.
