### ISSUE TITLE
its too dark

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4873]
Light can only project itself three tiles from the player, as the max.
IF you were to stack as many lit items as you could on yourself, IE fire helmet flashlights etc you can only see 3 tiles ahead in complete darkness
Maint is really spooky now but it should be like that if you just have one flashlight, Not when you radiate like the sun

**Comment by PJB3005** [comment]
Yeah, with the old engine, turning on things like flashlights would increase your mob's luminosity, which was annoying, with the new one, it gets calculated via seperate datums individually and just added together

**Comment by CptWad** [comment]
I did not get any of that
However I dumbed it down for myself
Are you saying that the lights are stacking on top of eachother, so that the light that shines the farthest is the one that shines over the other ones? Instead of the old adding brightness expands light way?

**Comment by PJB3005** [comment]
No, old lighting: luminosity stacks (only var in calculations)

New: light_power stacks

**Comment by CptWad** [comment]
ok then how do i become brighter than the sun?

**Comment by PJB3005** [comment]
Cry at the admins to give you an OP flashlight?

**Comment by Probe1** [comment]
In game people have consistently complained about the light values of handheld items. 

Bump em up, probably across the entire board except for things like zippos.  A good example is I can't even see the back of the gas mixing chamber in atmos with a hardsuit helmet light.

**Comment by dylanstrategie** [comment]
I have personally reviewed most lighting values on the old engine, I'll likely take a look for the new engine
