### ISSUE TITLE
(WEB REPORT BY: drleprikon REMOTE: 198.245.63.50:7777) Turret control panel in TeleComms does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4874]
Revision: f433a252461e41b78055469ee5f89d6cf7ac2350 
 The turret control panel in tcomms does not work: it can't be used to either turn off or change the turrets to stun.

 Easily reproduced by attempting to use the turret control panel. Manaony says it is a map issue.

**Comment by ComicIronic** [comment]
>says its a map issue
>doesnt include the map

I wish people who used the web reporter just followed the web reporter, it guides you through making a sensible bug report.

**Comment by PJB3005** [comment]
It's not a map issue, it's related to area changes due to lighting, working on a fix right now.
