### ISSUE TITLE
Re-entering a corpse refreshes ghost abilities

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#4876]
This allows making areas near your corpse (be it human or mouse) EXTREMELY SPOOKY with up to 60 boos per minute. With a light switch present, you can turn it off infinitely as well

**Comment by 9600bauds** [comment]
Just magical

**Comment by PJB3005** [comment]
IT's A FEEEAAAAATUUUURE

Don't leave dead people around, it becomes extra spooky
