### ISSUE TITLE
Innocent Larson exclaims, "<SPAN!!"

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#4877]
Guy inside a DNA modifier who I assume was afflicted with tourettes kept spewing shit like:
Innocent Larson says, "CLASS='SANS'>!!"
Innocent Larson says, "CLASS='SANS'>THHIT!!"
Innocent Larson says, "CLASS='SANS'>TH-TH-THH-H-HIT-T!!
Innocent Larson says, "BORK!! CLASS='SANS'>C-CUN-NT-T-T-T BORK,!!"

**Comment by Shadowmech88** [comment]
He had the comic sans disability, but it looks like one of his other speech impediments broke the comic sans tag so he just says the tag out loud. I feel like it might be the shouting that did it.

**Comment by clusterfack** [comment]
The stuttering or whatever removes shit randomly but doesn't try searching for spans to take out first

**Comment by Probe1** [comment]
Stuttering Swedish Tourettes.

That's intense.

**Comment by Exxion** [comment]
This has been around for a long time
I forgot about it

**Comment by dylanstrategie** [comment]
Most likely needs some sort of failsafe

**Comment by N3X15** [comment]
I'm working on a recode of saycode that'll fix it.

**Comment by PJB3005** [comment]
Fixed by saycode 2015
