### ISSUE TITLE
Feature Request: pAI smart tanks/mechas

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4878]
One of the biggest problems with using mechs is that they are so cumbersome and slow.
You wouldn't want to take one out of robotics to go get something to eat, but then you don't have one when a group of grayshits are mugging you.

NOW HERE'S A SIMPLE SOLUTION!

Introducing a slot that you can put your pAI into!
Yes you too can put your little digital pal into an empty unlocked mech to make him into a big metal buddy!
It can open and close the door, control the air pressure lights and radio, and when it is closed, can walk around.
It can however, not use attachments, such as weapons, sleepers, and drills.

It solves all the problems of being a pAI.
Not being able to interact with a radio or intercom to change freq to chat with your master or other people? Now you get one built into your KICK ASS METAL BODY!
Not being able to walk around?
NOW YOU GET TO STOMP AROUND IN YOUR KICK ASS METAL BODY!

It also solves some of the problems of mechs.
Having giant robot buddies was a pain before, MMI's usually are from demented ex felons who can't be trusted with a death machine, possibrains are boring and their law set is law 1 be as boring as possible law 2 be boring until put into borg or MoMMI law 3 you are uninteresting.
NOW YOUR GIANT ROBOT THAT YOU CAN CALL OVER RADIO ONLY LISTENS TO YOU! It can even open up to let you inside of it.
Another problem with mechs is the access requirements are silly. You can't have departmental mechs. You can't save someone by giving them your mech because its DNA locked. Now your buddy is your DNA lock! You want to share a mech with your department? Just install a pAI to open up for anybody who needs it in your department! Need to save someone in the pressure less hallway? Have your giant robotic pal pick them up and get them to safety! Need to murder everyone in an area? Just emag your friendly robot pal and le-
Whoh lets not go into that right now, all we need to worry about is station safety.

**Comment by Kurfursten** [comment]
>Not being able to interact with a radio or intercom

The pAI has a built in radio

>Share a mech with the department

This would be much better handled by adding a feature to the mech, not making it a human's job to play doorkeeper for a single mech.

Also, I really don't like the idea of giving pAIs a large amount of autonomous power, for the same reason you mention: it only listens to you.

**Comment by SonixApache** [comment]
Slot a pAI in a mech to let it control and monitor the stats for you while you operate the mech?

**Comment by FudgePucker** [comment]
It wouldn't have the power to do anything offensively, just walk around and open doors. (The real question being is if you should be able to emag the safety protocols to give them the power to have access to punching and using weapons.)
I just thought the idea of having a giant robot pal would be funny.
Like the smart tanks from GitS.
Cute robotic pals that wave to everyone and say hello as they walk to their masters, just to have their masters use the mech to murder everyone.

**Comment by clusterfack** [comment]
Just make a posibrain

**Comment by ComicIronic** [comment]
A posibrain isn't a pAI.
The point is to expand pAI utility.

**Comment by Shadowmech88** [comment]
Not only that, but a posibrain would mean you couldn't pilot the mech yourself.

**Comment by Ephx1** [comment]
Also a Positronic Brain/MMI piloted mech cannot eject it without it being destroyed, ruining the example he gave of mech sharing.

**Comment by Shadowmech88** [comment]
Though that really deserves its own issue, there should be a way to eject an MMI/posibrain from a mech without blowing the mech up, in case it wants to be a different kind of mech or goes braindead and renders the mech useless.

**Comment by Kurfursten** [comment]
Seconded Shadowmech
