### ISSUE TITLE
Can't put pills in beakers or any reagent_containers

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#4879]
Previously you could do this.

Now when you try you get 'the [src] is full'.

**Comment by clusterfack** [comment]
I tried that and it worked

**Comment by Kurfursten** [comment]
Unable to reproduce now myself. It's possible that it was just bugging out due to some other code at the time. I think this is safe to close.

**Comment by Kurfursten** [comment]
@clusterfack @ComicIronic After months, I finally figured out the mystery of what caused this. If you try to drop an EMPTY PILL into a beaker, you get "the [container] is full!"

If only someone had VV at the time!
