### ISSUE TITLE
Old firelock sprites on box that weren't changed

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4881]
![ss 2015-06-07 at 01 59 50](https://cloud.githubusercontent.com/assets/8550416/8025901/50e43c9e-0d33-11e5-96a5-76ce69d74055.png)
![ss 2015-06-07 at 02 06 43](https://cloud.githubusercontent.com/assets/8550416/8025900/50e39cf8-0d33-11e5-835b-ebd499108ca1.png)
![ss 2015-06-07 at 04 20 40](https://cloud.githubusercontent.com/assets/8550416/8025899/50e32c8c-0d33-11e5-8bd1-ae5423b0dcbe.png)

@ComicIronic

**Comment by dylanstrategie** [comment]
This should have been partially fixed, but I'm keeping this here to keep it in mind of any other mappers

Please update with new screens if you spot full firelocks
