### ISSUE TITLE
(WEB REPORT BY: notmog REMOTE: 198.245.63.50:7777) AI Upload Turrent Controls Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4882]
>Revision (Should be above if you're viewing this from ingame!)
4e6d381df0ee0f356ce39a870fb7f679575d8cd0

>General description of the issue
AI Upload turrets do not deactivate when they are disabled on the turret control.

>What you expected to happen
Turrets disabled.

>What actually happened
Turrets were actually still active.

>Steps to reproduce if possible
Try using the AI Upload turret control.

**Comment by Probe1** [comment]
same deal with telecomms turrets

**Comment by PJB3005** [comment]
I should've fixed this (tested it, worked locally) in #4875
