### ISSUE TITLE
(WEB REPORT BY: kirtasheks REMOTE: 198.245.63.50:7777) pitch black

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4883]
>4e6d381df0ee0f356ce39a870fb7f679575d8cd0 

>General description of the issue
the new lighting system is bugging out, sometimes there are pich blaack spaces that cant be lit, this spaces become black(only see the floor) when wearing a meson scanner.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Kurfursten** [comment]
In your image provided in the thread, all the lights are smashed out. Do you think that this might be causing the darkness, or is it different kind of darkness? It's hard to tell with the mesons on.
