### ISSUE TITLE
(WEB REPORT BY: tersr REMOTE: 198.245.63.50:7777) Lighting not lighting tiles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4885]
>Revision (Should be above if you're viewing this from ingame!)
4e6d381df0ee0f356ce39a870fb7f679575d8cd0

>General description of the issue
Lighting not working

>What you expected to happen
Light to lihgt up tiles

>What actually happened
certain tiles remain black regardless of ligh touching the tile

>Steps to reproduce if possible
Head to cargo because cargo seems to be hit hard by it.

**Comment by PJB3005** [comment]
Dupe of #4883
