### ISSUE TITLE
Hotwire heating units

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#4896]
This is a feature request for the space heaters, and the ability to hotwire or jury rig them somehow so they can accept at least big blue tanks. Then, having a tank in would allow you to slowly heat the tank contents directly from the heater.  This ghetto method would make generating high mole density gas concentrations inside of tanks much easier.

Additionally, if you could hotwire some sort of sensor to a space heater (rsd, laser, motion, whatever), you could have it activate. That way you could prepare a heater with a mix inside the inserted tank that would ignite once it hit 100 centigrade. 
One of two options could occur:
Using a blue tank, it'd process normally (Ie explode once it breached about 3.7k pressure)
Using a plasma tank, you could have it spew the contents of the tank instead due to the plasma tank's "safety" release valve, thus creating fire.

**Comment by FudgePucker** [comment]
That seems like it would be over powered.
There is a bomb making lab in maintenance, all you would need is to get a RPD, some metal, and some O2 tanks, and then you can make toxin level bombs.

**Comment by Midaychi** [comment]
You'd need the tank transfer valves to accomplish anything major though. I doubt you could fit enough moles of oxygen and plasma in a single tank to come close to the explosion radius of a transfer valve bomb because its based on tank rupturing. If you tried heating 1013 kpa of 2 moles of plasma to 1 mole of oxygen to 100 centigrade, the tank would rupture from pressure before it even got to the ignition point.

**Comment by FudgePucker** [comment]
All you would have to do is get the temperature in the tank just below ignition point, also using a portapump to get rid of some of the pressure if it gets too high, then setting it up to blow where you want.

**Comment by 9600bauds** [comment]
Adding balance because holy shit you can make devcap bombs with just freezers and heaters.
