### ISSUE TITLE
Weird visual bugs

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4898]
![ss 2015-06-08 at 06 25 04](https://cloud.githubusercontent.com/assets/8550416/8048551/e88254d0-0e20-11e5-9c33-aef2765b57cf.png)

Skowron couldn't see these weird black squares with gray horizontal stripes but I could.  I only saw them around the vicinity of cargo.  With and without mesons on.

**Comment by clusterfack** [comment]
This is a byond issue, your RSC mixes up two different icons. Relogging fixes it.
