### ISSUE TITLE
Racial Changes

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#4899]
Remove Skeletons, give meaning to Halloween

Remove Dionae's ability to be affected by Hyperzine

pls

**Comment by utilitas-** [comment]
Remove Vox, fucking furry bait race

**Comment by Probe1** [comment]
Skeletons are shit.  Diona on hyperzine are alright but being a roundstart, character selection race is questionable.

I don't get this discussion though.  If you want to put up a poll in game I think you could get people to take it seriously but it's going to be a lot of back and forth over WHO IS WORST RACE and joke replies I fear.

**Comment by Boxe** [comment]
remove skeletons remove skeleton skeleton worst race

**Comment by Ephx1** [comment]
My only real gripe is skeletons.
Probably out of them all, the only one I truly dislike because they were added in during the "Skellington" craze and it's just been one big joke from there.
Now if they were say, robots built off the skeletons of people with technology jutting out of them, that would be super cool, but I doubt that'll happen.

**Comment by SangriaMonkey** [comment]
I like skeletons but for real we should just get rid of races. They're a point of needless contention.

**Comment by Probe1** [comment]
Most races are alright.  Well, all races except skeletons.  They're the odd man out of having absolutely no lore or attempt to explain what they are.  They just are.  Inexplicable, walking skeletons with organs and normal humanity.  Except for the caveat that they're skeletons.

**Comment by nuklearcellphoneg** [comment]
1) Skeletons are just silly. They have an advantage over humans and make no sense(they are a spooky halloween bus).

2) I'm okay with the other races, but again, if the dionae are going to be super powerful, they need to be super slow, and they shouldn't be able to just circumvent that with massive hyperzine.

pls no hijack

I'm okay with races, I'm not okay with clear powergame races.

**Comment by SangriaMonkey** [comment]
Pretty much every race has some sort of an advantage. Greys are the only straight downgrade.

**Comment by Probe1** [comment]
A diona wizard is a tough pill to swallow.  I think a permanently slow diona would be too disadvantageous.  No one would be interested in evolving.  Rebalancing hyperzine to damage them so they can't ingest 1000 units and forget about it for the rest of the round would be tolerable.  Removing them from roundstart races to reduce the chance of dealing with an antag that can lel off almost anything except a lucky knockout hit would be nice.

I really don't have anything to say about skeletons, they're all around shitty.

@SangriaMonkey don't write off silent telepathic communication.  That's a big advantage of grays.

**Comment by Boxe** [comment]
just make diona a little faster

**Comment by SarahJohnson489** [comment]
Oh god that feeling when greys snappily tell the HoS where they are while silent stung and stun gloved.

**Comment by nuklearcellphoneg** [comment]
Into the shower they go.

**Comment by SangriaMonkey** [comment]
If you do make hyperzine not metabolize for them at least buff the base movement speed. Lasers exist after all.

@Probe1 
I've been ignored so many times it's not even funny. It's a lot more situational than a free space suit to say the least.

**Comment by Probe1** [comment]
Oh yeah.  Everyone has their own story of warning some latejoin telepathically only to be ignored, or call for help and no one comes.  But it's still strong.

**Comment by FudgePucker** [comment]
Having to rush for hyperzine is the only way to actually play as a diona outside of a gimmick.
No really, their run speed with no exosuit or boots slowing them is slower than humans walk speed.
It's too slow, it takes a min to even walk to chemistry to get the hyperzine.
Only diona I have pretty much seen go with out hyperzine is groot.

Plasmamen and skeletons are worse in my opinion. They both also don't bleed, so brute damage isn't as devastating for them, and we all damn know for a god damn fact that there are more shitter skeletons than round start diona. I had to deal with a shitter skeleton that round start as mechanic, upload a spam script to tcoms. I have never seen a skeleton that I have remembered except for shitters. Not bleeding is really really over powered, I shot a plasmaman 4 times with a scattershot, a human would have gone into crit in 2, he got up and laser'd me to death.
Plasmamen and skeletons don't move at a snails pace either.

**Comment by AutismSpider** [comment]
Up Dionae's move speed to shoeless human speed/mag boots speed.

Dionae's ODing on Hyperzine will slowly heat up and take burn damage form it.(even a little bit of heat is deadly to a dionae they take Xeno levels of burn damage)

Take Skeletons out and have them as a bus race/event stuff.

**Comment by Probe1** [comment]
I like what autismspider said.

**Comment by 9600bauds** [comment]
Don't greys have 5 tiles nightvision too?

What are their downsides again? Water and lower unarmed damage?

**Comment by ComicIronic** [comment]
Don't forget no Asimov protection.

**Comment by CptWad** [comment]
down with the skeleton. let them rot in adminbus. Or have a use for the dissolve ability

**Comment by FudgePucker** [comment]
I fucking hate skeletons, just remove them.

**Comment by VelardAmakar** [comment]
MY SUGGESTIONS
>**Skeletons**

- Permanently reduced health
- Unaffected by low pressure
- Very resistant to high pressure
- High temperature resistance
- Helpless vs atmos effects
- Does not need to breathe
- Bloodless, but unaffected by chems whatsoever
- Cannot use genetic powers
- Cannot be revived or borged on death, brain is lost on death
- Can be roundstart, but can also be made in genetics by pulling a guy out too early in a cloner

>**Dionae**

- Increase base movement speed by a tiny bit
- Vulnerable to hyperzine addiction, if they stop taking it after getting a taste they develop HZ addiction which has a myriad of nasty withdrawal syndromes
- More stuff to give them extra purpose and fluff

>**Grays**

- Same as they are now, except...
- Higher radiation tolerance
- Faster metabolism, making chems exit the system faster(they'll need larger doses to get the same effect out of things)
- High chance to start with good genetic powers, but start with a neural inhibition implant, negating any use of powers aside from telepathy

>**Vox**

- Make them roundstart, but as traders unaffiliated w/NT on a fixed up version of the vox asteroid outpost
- *wait for velard to start working on pods so we can get vox raiders 2 electric boogaloo*

>**Plasmamen**

- Just keep adding more content.

**Comment by FudgePucker** [comment]
Just a quick question, how many problems have you guys had with round start Dionae?
I am not talking about greentide nymphs, I am talking about on crew manifest round start plantbros.
Skeletons have given me so much fucking shit in the past.

**Comment by VelardAmakar** [comment]
@FudgePucker 
Not much. They tend to mind their own business.

**Comment by NigglyWiggly** [comment]
>Can be roundstart, but can also be made in genetics by pulling a guy out too early in a cloner

So if you're killed and you get cloned, and some asshat pulls you out too early, you're stuck as a skeleton that can never be cloned/revived if you get killed again?

**Comment by VelardAmakar** [comment]
@NigglyWiggly
OH OH OH
instead of that, why not just limit it to the dissolve power
but allow Dissolve to be used when you're dead

**Comment by Ephx1** [comment]
@FudgePucker
Rarely if ever seen a roundstart Dionae, I believe, as a majority, people usually pick Diona to play as the little thieves and then when they've amassed enough wealth, they'll go Sanic Tree.

**Comment by SangriaMonkey** [comment]
Being unrevivable is a bit much.

**Comment by VelardAmakar** [comment]
@SangriaMonkey 
Given how much utility they have I'd say it's not too bad a downside.
I mean, they're fucking skeletons.

**Comment by FudgePucker** [comment]
@Ephx1 So the problem is with nymphs?
Why not just have Dionae evolved from nymphs not have developed their kidneys enough to process hyperzine.
They can still handle meds, but hyperzine just doesn't do anything for them.
That way greentide is cut down on, but round start dionae aren't nerfed to hell.
Being able to get back into the round as a dionae is a privilege not a right.

**Comment by VelardAmakar** [comment]
@FudgePucker 
That's not bad. I like this.

**Comment by SangriaMonkey** [comment]
Being unable to process chems seems bad enough to me.

**Comment by FudgePucker** [comment]
@SangriaMonkey 
They get to get back into the round after being killed and spaced.
Other options are possibrains and derelict MoMMI.

**Comment by YertBogan** [comment]
All the vox together on the trading post every shift would cement their place as outsiders and special snowflakes to some people. Stolen goods from station will probably double. Gassing of vox will probably triple. Not that I'm not ok with any of this.

**Comment by Ephx1** [comment]
@YertBogan 
The gassing room will finally have a use! QUICKLY CODERS!

**Comment by 9600bauds** [comment]
Can we please stop throwing around the words "special snowflake"?
Either vox are reskinned humans and are muh special snowflake because of their skin, or are something new and different and are muh special snowflake because they're not reskinned humans.

**Comment by DrCelt** [comment]
Velard's suggestions seem like the right way to go here.

**Comment by VelardAmakar** [comment]
@DrCelt 
:ok_hand: :ok_hand: :ok_hand:

**Comment by SonixApache** [comment]
Why / how do skeletons even have organs?

**Comment by FudgePucker** [comment]
If skeletons become bus only then they should have becoming a giant spider as their monkey form.
2spooky4me

**Comment by Ephx1** [comment]
I heard someone once suggest that the devolved form of Greys should be humans, I thought that was funny.
I don't know how you could devolve a science monster and a skeleton, though.

**Comment by NigglyWiggly** [comment]
Deformed Greys could be little green men, deformed skeletons could be monkey skeletons, deformed plasmamen could be stacks of plasma that scream constantly.

**Comment by nuklearcellphoneg** [comment]
Dionae

In terms of round start dionae, I've seen a few: They have a tendency to start in Chemistry or Science and are quite irritable to kill. Not everyone uses them to powergame, but it's definitely there; just because it doesn't occur all the time or consistently doesn't mean it happens. Attach three flashlights to yourself and load up on Hyperzine and you're perfect.

I think that because it's such an obvious powergaming choice, it doesn't get chosen that often, but I have seen it before. If there were a way to separate lights attached to the station from lamps, flashlights, and so on to make them not affect Dionae that would be nicer(it's not like the Diona has set up each of the lights on their belt and suit to face their face the whole time anyway).

I like them. I like their slow speed. I like their endurance and it being related to light. A dionae hyperzined up with ten flashlights attached running through maintenance can be a scary thing.

The endurance is okay when balanced by the speed. A dionae can pull out a taser/laser combo just as fast as anyone else though.

Skeletons

Yes, put them in the admin bus closet.

Greys

Are they immune to polyacid? I forget. If they are, that's coo'. The lower punch damage is cool too, but could it be spread across the board to all forms of melee? 

The telepathy is a big thing, which also holds a possibility to be useless. To counteract that, I mean, you could just remove 10 or so HP and maybe add a little extra blood- say it's thicker or some such. Quicker to kill them and all but to be honest, in killing a grey, that should just be something you expect and plan for as a good antag.

Vox

I like Vox. I've never had anything against them. Sure, you can reskin them or whatever, but they're still whatever it is they are.

I like the idea of starting out on the Vox Outpost doing their own thing; give them a little extra so they can create things to trade with the crew. You could even further this idea by giving them a few unique things they can create, but only through trading with the crew for select items. They already have that bolt thing and the syringe gun, and so it could make a nice neutral traitor trading post as well for an enterprising traitor.

Further, if all the Vox start out on the outpost, it could strengthen the raiders in the sense that "Oh the Vox Outpost alarms are going off- RAIDERS" would be a bit nonexistent

Plasmamen

Plasmamen are suffering. Good..

**Comment by Ephx1** [comment]
I've always seen the Vox outpost air alarms go off even when it's not raiders. Usually from some vox who wants the Clawboots and Strong vox suit. Or a miner snatching a quick jetpack.
But anyways, I've always wanted outpost vox, hell, the outpost was created with the thought in mind that's how the non-antag vox would be handled, off station.

**Comment by FudgePucker** [comment]
Dionias only having some sources of light working would be interesting, but at least give them some fall back in case they need to get into maintainance or power outages.
I was thinking maybe flares,  they aren't a permanent solution and their are some in every o2 locker.

**Comment by ihadtoregisterforthis** [comment]
This is absolutely terrible but can be closed now, there are other diona discussions.

**Comment by CptWad** [comment]
thanks for the necro
i am a skeleton now
[clatters]

**Comment by nuklearcellphoneg** [comment]
Since this is still open:

NERF PLASMAMAN LASER RESISTANCE

**Comment by Probe1** [comment]
jesus we've 

1.  Removed skeletons

2.  Re-added skeletons

3.  Circled the sun nearly twice now.

**Comment by 9600bauds** [comment]
This can't be closed until we remove skeletons again

**Comment by Probe1** [comment]
![capture](https://cloud.githubusercontent.com/assets/8550416/21373272/8a7da760-c6eb-11e6-8c79-b051cb33e125.PNG)
