### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Lighting System

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4904]
>Revision  2dd0ce348838cc4a2009ce51d7577a6126617a73 

>General description of the issue
PDA lights or flashlights have no effect while riding and moving on the Janicart

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by CptWad** [comment]
actually it does work
if you put a light in your pocket then put it in your hand, repeat repeat etc, you slowly become brighter and brighter. once you move the light goes out however

**Comment by PJB3005** [comment]
@CptWad, I adressed that in #4892.

**Comment by CptWad** [comment]
aight

**Comment by PJB3005** [comment]
Somebody close this, it was fixed.
