### ISSUE TITLE
Lighting level "smoothing" causes light to perceivably lag behind you when moving with a light source

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4907]
Under the new lighting system, when you shine a flashlight, it takes a second or so to light up the area around it.
However this also happens when you move: your old location takes about a second to stop being lit, and your new location takes a second or so to light up. Of course, by the time that second passes, you're already elsewhere. Which results in your flashlight failing to keep up with you at all, congratulations, you're now faster than light.
Sure the smoothing is fancy but I appreciate it a lot less when I can't see where the fuck I'm going. Look at how you can't see the wall at all until you're face-first into it.
http://puu.sh/iiGsJ/ac589ed34a.webm

To clarify: This issue is not from the lighting waiting for the next tick to update, that has always been a problem before. The problem is that the new light level smoothing exacerbates the "delay" even more.

**Comment by PJB3005** [comment]
This CAN be helped by lowering a value in the code, I'll drop it by 1/10th of a second
