### ISSUE TITLE
[Lighting] Bluespace anomaly caused perma-darkness

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#4913]
The bluespace teleport thingy reported it teleported the mommi nest. This resulting in solid blackness all over mechanics and part of atmos where it landed. Bringing in lights didn't help. Toggling helmet lights didn't help. Relogging didn't help. aAdmins and other players confirmed they couldn't see

![untitled](https://cloud.githubusercontent.com/assets/5564796/8077054/d41e6cd4-0efe-11e5-9fa1-8bca532ba851.png)

Steps to reproduce, force a bluespace anomaly then find where it landed.

**Comment by Midaychi** [comment]
Maybe it bluespace anomalied the overlays away?

**Comment by PJB3005** [comment]
@Midaychi, almost certainly what happened.

You would probably be able to light atmos up if you went to the old MoMMI nest and put down a couple lights there.

**Comment by PJB3005** [comment]
Whoops, I fixed this, but I forgot to put fixes # in the PR description after squashing, this can be closed

**Comment by ComicIronic** [comment]
Name the PR and I'll close it.

**Comment by PJB3005** [comment]
#4908
