### ISSUE TITLE
Ian can eat things from a distance

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4914]
get a fat pile of food on the floor
build a wall of machines or tables or some shit between the food and ian
Ian will eat the food from a distance
Is he part giraffe? We need to update the sprite.

**Comment by Exxion** [comment]
Where in the code is this even handled? I can't find any code to make corgis eat food from the floor.
Can non-corgis do this?

**Comment by CptWad** [comment]
I've only ever seen ian do it
Check Ians exclusive code

**Comment by Exxion** [comment]
Yep, there it is.
There are no checks performed at all to see if Ian can reach the food. It just finds a food item Ian can see within three tiles of him, makes him step towards it three times, and makes him eat it.

**Comment by Kurfursten** [comment]
Not sure if this is a bug fix issue or sprite issue. I for one welcome our long-necked overlord.

**Comment by Exxion** [comment]
Honestly, most of the Ian-specific code looks like badly-planned shit.
