### ISSUE TITLE
Vampires cannot see in the dark

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4915]
>Be vampire
>Cant see in the dark at even the highest level
>Have to rely on light to fucking see anything after you fucked the lights

**Comment by Kurfursten** [comment]
Confirming this report. Amusingly it makes the lower-level thermal vision better than the later X-Ray Vision because you can spot targets in the dark very easily.

**Comment by PJB3005** [comment]
I fixed this, but because I forgot to put fixed #4915 in the PR description after squashing, it didn't autoclose

**Comment by ComicIronic** [comment]
Name the PR and I'll close it.

**Comment by PJB3005** [comment]
#4908
