### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Decloner does no clone damage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4916]
>Revision (Should be above if you're viewing this from ingame!)
a29d5035cc42ef51293392e5af017b0606bf1401

>General description of the issue
Decloner only irradiate, it does no clone damage

>What you expected to happen
That my test target get clone damage

>What actually happened
Radiation

>Steps to reproduce if possible
Use a decloner

**Comment by FudgePucker** [comment]
Doesn't this mean it is working as intended? Maybe have the radiation from the gun have more uses and higher damage? I had an idea about the decloner being able to mutate viruses like being sick in a rad storm.

**Comment by Manaony** [comment]
We already have a rad gun though, not that it's buildable or anything

**Comment by clusterfack** [comment]
Rad gun is a geneticist traitor weapon, and holy fuck the rad gun is so overpowered. Decloner was always a piece of shit for some reason, this could be why.
