### ISSUE TITLE
Sleep overlay disappearing before waking up

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#4919]
not sure if feature
how to reproduce

1) sleep
2) wait

**Comment by CptWad** [comment]
Actually what I think happens is that you do wake up visually and logically but you do not get the ability to hear back until you stand back up. Its weird as shit

**Comment by Probe1** [comment]
It's happened to me a few times going back months.

**Comment by clusterfack** [comment]
I couldn't reproduce it, I assume I've fixed it from numerous changes to obj/screen unless someone has seen it recently
