### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Lighting on Janicart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4922]
>General description of the issue
Lighting doesn't follow the player while on the janicart. It activates when you turn on a light source but the light stays still on the activated tile as the player moves.

>What you expected to happen
Drive through dark maint and see where I'm going.

>What actually happened
Shit was dark. Had to keep turning my flashlight on and off to see where I was going.

>Steps to reproduce if possible
Get on Janicart and ride into the dark.

**Comment by Exxion** [comment]
Duplicate of #4904
