### ISSUE TITLE
Map vote picks boxstation even if another station wins

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4924]
If taxi or something else wins box is the next map always.
Rip in piece

**Comment by clusterfack** [comment]
boxbabbies rigged the vote

**Comment by Ephx1** [comment]
Gas the box, mapwar now

**Comment by Kurfursten** [comment]
Confirmed this as a bug, saw it in action today

**Comment by PJB3005** [comment]
HIGH PRIORITY

**Comment by dylanstrategie** [comment]
This can naturally wait

**Comment by PJB3005** [comment]
@dylanstrategie We all know you're a box baby.

**Comment by ComicIronic** [comment]
Still an issue?

**Comment by clusterfack** [comment]
No I have not seen this happen in a long time, and it has been working properly
