### ISSUE TITLE
Monkeys get "Gravity!" message spam when moving around.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#4925]
I think this also causes another bug but that needs some fuckery to figure out but fixing this would most likely fix that bug too

**Comment by ComicIronic** [comment]
Every movement, or just some?
Because this would mean their areas aren't being set properly.

**Comment by CptWad** [comment]
Every few
Its pretty consistent. Just monkey yourself and walk around.

**Comment by ComicIronic** [comment]
Closed in favour of #4938
