### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Cannot use cyborg medical upgrade equipment

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4926]
Revision a29d5035cc42ef51293392e5af017b0606bf1401 
On two consecutive rounds, I acquired the medical upgrade. However, I cannot put the advanced hypospray or the defibrillator into my hand slots.

**Comment by BestName** [comment]
Works for me :^)
![asd2](https://cloud.githubusercontent.com/assets/3892856/8110304/269a16dc-1064-11e5-8ad4-10f47216dbf8.gif)

**Comment by PJB3005** [comment]
It's definetly a glitch though, you need to use the text menu to get it the first time.
