### ISSUE TITLE
Space bears have no attack message and I can't figure out why

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4928]
There's no attack message in game.  I was using bear code for a related project and noticed.  It should be here but it isn't working properly.  Does anyone know why?

    /mob/living/simple_animal/hostile/bear/AttackingTarget()
	emote( pick( list("slashes at [target]", "bites [target]") ) )

	var/damage = rand(20,30)

	if(ishuman(target))
		var/mob/living/carbon/human/H = target
		var/dam_zone = pick("chest", "l_hand", "r_hand", "l_leg", "r_leg")
		var/datum/organ/external/affecting = H.get_organ(ran_zone(dam_zone))
		H.apply_damage(damage, BRUTE, affecting, H.run_armor_check(affecting, "melee"))
		return H
	else if(isliving(target))
		var/mob/living/L = target
		L.adjustBruteLoss(damage)
		return L
	else if(istype(target,/obj/mecha))
		var/obj/mecha/M = target
		M.attack_animal(src)
		return M

Comparatively, space carp have much simpler code and uses the var attacktext instead of this emote( pick( list) ) ) business.  They just use attacktext and it seems to work.

    /mob/living/simple_animal/hostile/carp
	name = "space carp"
	desc = "A ferocious, fang-bearing creature that resembles a fish."
	icon_state = "carp"
	icon_living = "carp"
	icon_dead = "carp_dead"
	icon_gib = "carp_gib"
	speak_chance = 0
	turns_per_move = 5
	meat_type = /obj/item/weapon/reagent_containers/food/snacks/meat/carpmeat
	response_help = "pets"
	response_disarm = "gently pushes aside"
	response_harm = "hits"
	speed = -1
	maxHealth = 25
	health = 25

	harm_intent_damage = 8
	melee_damage_lower = 15
	melee_damage_upper = 15
	attacktext = "bites"
	attack_sound = 'sound/weapons/bite.ogg'

**Comment by 9600bauds** [comment]
Possibly bears replacing AttackingTarget() without calling the parent, and emotes on mobs being broken by new saycode
This is why snowflake is bad, kids

**Comment by Probe1** [comment]
How would you call the parent?  
    . = ..()

?

**Comment by 9600bauds** [comment]
..(), I'm not 100% sure how to handle the . return

**Comment by Probe1** [comment]
/mob/living/simple_animal/hostile/necromorph/AttackingTarget()
	. = ..()
		emote( pick( list("slashes at [target]", "bites [target]") ) )

That fixed it yep.
