### ISSUE TITLE
Ghetto Jetpack

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#4929]
A feature request for a ghetto jetpack.

Possible construction steps (subject to balance):
1. Empty out a paperbin.
2. Use wire on the empty paperbin to tie mechanism and launching framework
3. Create some springs clamps and a trigger somehow and attach+fasten them with a screwdriver. (Idk sheet of metal or something)
4. Use some wood or plastic to form a hopper

Tadah. Ghetto jetpack. You insert small or moderately small objects in the hopper for storage, hold the mechanism in your hand, point in a direction and fire the object crossbow style. The opposite force gets applied on spessman and they fly in the opposite direction from the fired direction.

For extra cool points, use plasteel and plasma instead of metal to make springs that can be adjusted post-construction with a screwdriver. You can adjust to a varying level of launch speeds. This would not only allow you to launch yourself in a direction faster (and far more dangerously!) but would make the mechanism a serviceable pneumatic cannon in low gravity (of course with the downside of launching you in the opposite direction just as hard if you're not braced)

**Comment by BestName** [comment]
There's already a ghetto jetpack. They are called fire extinguishers.

**Comment by CptWad** [comment]
Yeah what BestName said. If a back mount is what you need then we can make one out of fire extingushers. However they will only last a small time so its pretty pointless

**Comment by PJB3005** [comment]
@Midaychi clarified in IRC that this should be essentially a pneumatic cannon that propels you backwards.

**Comment by Midaychi** [comment]
It'd probably be better to just make pnematic canons also propel you opposite of shot direction with a force similar to the force you shot the object out at, if you're in a low grav situation.

**Comment by Probe1** [comment]
what bestname said

**Comment by FudgePucker** [comment]
What about all projectile weapons, ie firearms, cause movement in no gravity situations? I want to recreate that scene from cowboy bebop where spike goes ship to ship by holding his breath and using his pistol.
