### ISSUE TITLE
Add a bandage to the starter box

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#4932]
What kind of corporation sends people in with a tank full of oxygen in case there's no air, but not a single medical item in case they stub their toe?

Having a single bandage on board would help people not bleed out all the time.

**Comment by 9600bauds** [comment]
What if you could rip up your jumpsuit to make rags (which work as bandages) instead?

**Comment by CptWad** [comment]
:+1: @9600bauds

**Comment by Kurfursten** [comment]
What a coincidence #4934

**Comment by SonixApache** [comment]
@Kurfursten well that's perfect, close this one up then

**Comment by 9600bauds** [comment]
External bleeding has since been nerfed, is this still an issue?

**Comment by CptWad** [comment]
Actually no. Though we should keep the idea of more survival things in your box.
