### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Genfabs dont take syndie nanoprints

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4933]
>Revision (Should be above if you're viewing this from ingame!)
a29d5035cc42ef51293392e5af017b0606bf1401

Title says it all. Clicking on Genfab with a syndie nanoprint results in nothing happening.

>Steps to reproduce if possible

**Comment by clusterfack** [comment]
The fuck is syndie nanoprint

**Comment by PJB3005** [comment]
I think nanoprints made for designs that can only be gotten with the syndicate device analyzer?
