### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Monkey players spammed with Gravity! every pass of a firelock

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4938]
>Revision a29d5035cc42ef51293392e5af017b0606bf1401 

>General description of the issue
Gravity!
Gravity!
Gravity!
Gravity!
Gravity!
Gravity!
Gravity!
Gravity!
Gravity!
Gravity!
Gravity!

After getting assistance to monkify myself in the dna modifiers I noticed that as a monkified human I got the message, Gravity!, every time I passed a firelock

>What you expected to happen
Not get Gravity! every time I passed a firelock as a monkified human

>What actually happened
Got the message, Gravity!, every time I passed a firelock

>Steps to reproduce if possible
Monkify yourself, walk past firelocks

**Comment by Ephx1** [comment]
Same applies to Golems. Every single firelock would trigger that response.

**Comment by ComicIronic** [comment]
I believe this is not actually to do with firelocks, it's a coincidence of how areas are bordered by firelocks.
Area changing isn't working properly.

I blame the lighting changes.

**Comment by ComicIronic** [comment]
So, I figured out the main cause of this:
Stuff not using forceMove.

Certain mobs (namely ones spawned in a place that isn't a turf, like humanised monkeys) don't start with areaMaster set properly, which means that when they change area - passing through a firelock boundary, normally - they get the thunk() proc called to force a gravity change on them.

However, this gravity change also throws a runtime if the mob's areaMaster is null (thanks, no sanity) so the areaMaster is never changed. Hence, every single area change procs the gravity change effects on the mob.

**Comment by PJB3005** [comment]
>Lack of forceMove()

My bain, because that causes the lighting engine to not properly move around shit, really annoying.

**Comment by 9600bauds** [comment]
Definitely not an issue anymore
