### ISSUE TITLE
CE the mommi lord

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#4941]
I heard this was the place to stuff all inane feature requests for vgstation.

I suggest an alteration to KEEPER lawset, to change the first part of the law to:

You may not involve yourself in the matters of another being, even if such matters conflict with Law Two or Law Three, unless the other being is another MoMMI in KEEPER mode OR has the designation of 'Chief Engineer'.

and to add a damage control encryption key to the CE's headset.

**Comment by ririchiyo** [comment]
no.

**Comment by FudgePucker** [comment]
|>CE is being arrested for being a traitor
|>screams over his headset "COME FOWARD MY AUTISTIC ARMY"
|>scittering and buzzing can be heard from the vents.
PR when?

**Comment by clusterfack** [comment]
Mommi upload board when

**Comment by FudgePucker** [comment]
Make it a CE only traitor item that comes with a damage control card.

**Comment by FudgePucker** [comment]
Its not like I want  to force them to throw me a tea party, wear silly hats, and wiggle.

**Comment by AutismSpider** [comment]
Make it some thing Malf Ai/Traitor CE can do

For Malf Ai use some points to Hack a Mommi forcing its malf ways on it.

eyes turn green or keep it red for this and all the safety locks come off can pick up and use Ai law boards and guns two hand melee weapons and so on.

For the CE traitor  only item one use mommi upload board and damage control key.

**Comment by Probe1** [comment]
if you want them go emag them and give them PDAs.

**Comment by Midaychi** [comment]
Malf/traitor is fine.

**Comment by Kurfursten** [comment]
I think the amusing part of this wording is that it doesn't even imply that they should listen to the CE, just that they're allowed to meddle in his affairs

Queue MoMMIs following the CE around and bolting doors, making fun, general harassment

**Comment by Midaychi** [comment]
Yeah that's the point. It's entirely optional and doesn't really mess the crew or round up but still allows the mommis a new dimension of things to do. I'm pretty sure CE can detonate mommis on vgstation right? If not he might need a console in his room or something.

**Comment by Kurfursten** [comment]
There is no MoMMI lockdown/detonation on /vg/

**Comment by Shaska-** [comment]
"designation" is incredibly vague, meaning it can be interpreted very creatively. 
On the other hand, I guess watching MoMMIs using the labelling device to designate everything as the chief engineer would be amusing.

**Comment by Midaychi** [comment]
Clever, but for the most part changing something to be designated as Chief Engineer would either not matter anyways or be mettling in/with stuff that wasn't priorly designated as Chief Engineer.  If the crew wants to designate things or objects or people Chief Engineer then that's their problem.
