### ISSUE TITLE
Telecomms machines don't show wired machine frames when deconstructed

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4942]
![image](https://cloud.githubusercontent.com/assets/8550416/8139802/74805d6e-1124-11e5-8e2a-ef337d0fd1a4.png)

Although it looks like the wires are gone they are still in the machine.  You can clip them out like normal but there's no indication the machine is still wired.

**Comment by Kurfursten** [comment]
I've run into the very same issue.
