### ISSUE TITLE
I need a progress bar for cycling airlocks.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4943]
I've been going through these for the last few hours and I've decided what makes them so annoying to me and probably to other people.  There's no way to tell when it's going to open the next door.  If we could get a progress bar, kinda like cryo but not, somewhere then that would be so much better.  It'd still take the same amount of time but I wouldn't sit there thinking it was broken or get annoyed.  I could say "right its got 75% left time to fuck around with my PDA for a while" or "it's ok it's almost done".  Instead its a annoyance chamber.

![image](https://cloud.githubusercontent.com/assets/8550416/8141383/00c94a10-1134-11e5-8b1c-8d59f2f37f4c.png)

**Comment by ComicIronic** [comment]
There is a progress bar on the main controller UI, it should be possible to replace the buttons with those.

Or to add a related machine that you can link by id tag and would show generic progress: cargo wait time, etc.

**Comment by Probe1** [comment]
either way works for me.  I don't need something amazing I just need a little something to make it less annoying.

I think xenoarcheologists feel the same way.

**Comment by Shadowmech88** [comment]
Xenoarch has a main controller inside the chamber, so we've got the progress bar in there. But yeah, the inside and outside buttons have no way to tell you how long until it opens.

**Comment by FudgePucker** [comment]
I just came up with the best idea ever, the best solution to cycling airlocks.
Double/triple the vents.
SME not transferring gasses fast enough?
More vents.
Cycling airlocks too slow to the point of just breaking a window is better?
More vents.

I will take my medal for being the greatest engineer now.

**Comment by Shadowmech88** [comment]
Either more vents, or replace the standard vent with a scrubber/injector combo.

**Comment by FudgePucker** [comment]
You can fit four uniary atmos devices on the same place. Fuck realism, make it so it cycles super fast

**Comment by Probe1** [comment]
In cycling airlocks those are Dual-Port Vents which are an entirely different beast than unary vents.
![image](https://cloud.githubusercontent.com/assets/8550416/8143135/2b3cde6a-116b-11e5-9273-424e4afea22f.png)

**Comment by PJB3005** [comment]
Yeah, just put the controller INSIDE the chamber.

**Comment by ComicIronic** [comment]
But then you wouldn't have progress bars on either side, which can surely be just as frustrating.

**Comment by Shadowmech88** [comment]
What about having the buttons display the room's pressure when examined?

**Comment by FudgePucker** [comment]
Just put atmos automations computers in every cycling airlock.
Problem solved.
