### ISSUE TITLE
Click+drag doesn't eject people from body scanners

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4946]
"[you] removes unknown from the body scanner."
But...
>runtime error: Cannot read null.occupant
>proc name: go out (/obj/machinery/bodyscanner/proc/go_out)
>  source file: adv_med.dm,212

Rightclick+eject still works, only click+drag doesn't.

**Comment by clusterfack** [comment]
Yeah so it's an old byond bug that resurfaced, but people say its fixable by putting src.occupant in go_out.

**Comment by 9600bauds** [comment]
so it is
what the actual fuck BYOND
