### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Cyborg rechargers don't reload MoMMI cable coil

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4948]
>Revision (Should be above if you're viewing this from ingame!)
0bb8b9f45d34c5a76ee6a8c6486b799550365f7b 

>General description of the issue
rechargers no longer slowly replenish the cable coils of MoMMI, as tested by the status screen and the actual coil

>What you expected to happen
cable coil number in status screen to go up as coil is replenished

>What actually happened
The cable coil: number in status stays the same in the charger and does not increase, and when tested has the same amonut of coil as before entering
The coil itself can still be replenished from other segments being added so I think its a charger problem

>Steps to reproduce if possible
be mommi
have less than 50 cable
get in charger

**Comment by AutismSpider** [comment]
Happens with Engi borg cable coil too.

**Comment by PJB3005** [comment]
#4844 could've caused this
