### ISSUE TITLE
AAC turns off vents with the same tag as scrubbers and vice versa

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4951]
Similar to https://github.com/d3athrow/vgstation13/issues/2415

If I shut off a scrubber, it also shuts off a vent with the same tag.
![image](https://cloud.githubusercontent.com/assets/8550416/8143605/17e3df26-1184-11e5-8eee-89bdc03d1808.png)

While it initially seemed like a fun idea to be able to shut off every vent in an emergency, this is a problematic outcome.  Caveat is it has to be on the same frequency.  Interestingly, I don't think it works the same for injectors but I have not tested that.

**Comment by PJB3005** [comment]
This is because the AAC (just like air alarms and tank control computers) sends a signal on that frequency, any machine with the same id_tag will receive that signal, and the signal data to toggle a vent on/off is the same as that for a scrubber (possibly air injector too)
