### ISSUE TITLE
Ideas for items/treasure inside mining hidden complexes?

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4959]
Continuation of #4001
What prizes could be added to mining rooms, that...
- Would be fun or useful to someone in the station? (Doesn't have to be the miner)
- Wouldn't be broken as all shit or threaten the validity of a job back at the station?
- Fit with SS13's theme? (Pokeymans is already toeing the line)
- Could possibly open up options for antags?

Some ideas that were thrown around:
- Swiss army tools for Engineers
- Design disks with designs not normally available through research (suggest ideas for these)
- Double airtanks, galoshes, Janicarts, clown carts
- Bomberman stuff?

For wishmins: What are minor things that people sometimes wish for?

**Comment by Ephx1** [comment]
WATER BALOONS

**Comment by FudgePucker** [comment]
HF katana
Pulse rifle
Okay time for the real suggestions
Nazivend/sovietvend/magivend refill packs.
Space carp protecting a bottle of carpotoxin.
A toy mommi surrounded by pipes and silly hats.
One of those portable SMES's with full charge, also all three pacman boards and a stack of plasma.
A bottle marked as adminzine that really just has 50u tricord pills in.
A space worthy cardborg suit.
A damage control radio encryption key.
Banana and blue tomato seeds with some bananium coins and a bike horn. Honk.
A syndicate device scanner and a clocking device.
Water balloons
Gokarts.
A room filled with nothing but happy giga pudis.
A cluster bang, but with polyacid grenades.
A room plated with gold and has gold bars and gold coins.

A super rare room filled with space bears guarding a safe that holds a piece of paper with a picture of dickbutt, or death squad suit, HF katana, and a pulse rifle.

**Comment by SonixApache** [comment]
Toys.

**Comment by ComicIronic** [comment]
>HF katana

It is never getting into the game legitimately.
120 force when wielded.
2stronk.

**Comment by FudgePucker** [comment]
That's the point, you still have to break into the safe for a large chance for a useless image.

**Comment by Exxion** [comment]
ULTRA SPEED tools once more things are ported to construction datums so that's possible

**Comment by Probe1** [comment]
yeah no we're not doing the energy axe things fudgepacker, we've been down that road.

**Comment by Probe1** [comment]
Remember that whatever gets dug up will primarily end up in the hands of miners.  If there's a swiss army knife then it'll be the miners swiss army knife, he's not giving that shit up.  I don't think that's a problem.  But we should remember how generous players are in game with cool things they found.  

I'll post a list of stuff I'd like to see and think would fit with mining spawners in a bit.

**Comment by FudgePucker** [comment]
Its a 1 in a 100 chance of it showing up.
Then you have to fight an army of bears.
Then you have to get a stelthoscope.
Then you have to crack it.
Then its a 999 in 1000 chance of it just being a picture.

**Comment by SarahJohnson489** [comment]
Oh god yes. Picture of a pulse rifle/HF blade/Energy axe when? I can feel the despair.

**Comment by Manaony** [comment]
I'd like the magic room floor safe to have either a gem encrusted armor or a one use spellbook, it's rather shit that it has nothing right now.

**Comment by Iamgoofball** [comment]
Alien Stock Parts, rating 4 or 5

**Comment by 9600bauds** [comment]
go away goof

**Comment by FudgePucker** [comment]
@Manaony
A one use spellbook would be too OP or pointless because you have no robes.

Maybe put a staff of change in it for maximum non antag madness.

**Comment by ComicIronic** [comment]
I think all the one-use spells don't require robes.

**Comment by FudgePucker** [comment]
Oh yea I forgot about the oneuse spells.
Then that might be fine for the safe.
I thought it was going to be a spell book with just one spell, and everyone would pick EI NATH to be a shitter.
