### ISSUE TITLE
Ripleys don't pick up sand when they drill the roid

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#4960]
Pretty annoying.

**Comment by 9600bauds** [comment]
Was tremendously broken to the point where I couldn't even tell what they were supposed to do, the code was that obtuse.
How is the clamp for picking up ore, by the way?

**Comment by Probe1** [comment]
I did not realize it worked that way.  I learned that I was supposed to pick up an ore box and realized it scooped ore for me so I never experimented.
