### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Industrial Droppers duping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4965]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

As a service borg, if you click the Smart Chemical Storage whilest having an Industrial Dropper 'in hand', you place an Industrial Dropper into the Smart Chemical Storage, but retain your own Industrial Dropper.

**Comment by ComicIronic** [comment]
It's not using drop_item?

**Comment by Shadowmech88** [comment]
Have you confirmed that it can be removed and used? Or that you can insert more than one?
I remember similar behavior where as a borg I could deposit my beaker into an IV while still retaining it in my module slot, however once the beaker was ejected and ended up on the floor, it simultaneously disappeared from my module slot, preventing actual duplication of my beaker.

**Comment by clusterfack** [comment]
No longer accepts such objects from what I can tell

**Comment by PJB3005** [comment]
IIRC I fixed this.
