### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Cyborg recharger bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4967]
>Revision (Should be above if you're viewing this from ingame!)
No idea what goes here.

>General description of the issue
As engineering borg I was unable to refill my cablecoils using the borgchargers

>What you expected to happen

Expected to recharge my cable coils in the rechargers
>What actually happened
Nothing

>Steps to reproduce if possible
Use up some cable coil and enter the recharger?

**Comment by ComicIronic** [comment]
Duplicate
