### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Clicking a bolted open door causes the door to flash the sprite of it being closed and bolted.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4968]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
If you click a bolted open door, the sprite of it being bolted shut will appear for a few seconds.

>What you expected to happen
Nothing

>What actually happened
The bolted shut sprite appeared for a few seconds.

>Steps to reproduce if possible
Bolt a door open, click it.

**Comment by SkowronX** [comment]
It's playing the "Access Denied" animation.

**Comment by Exxion** [comment]
Access denied animation shouldn't play when the door is open or unpowered, but it does in both cases

**Comment by dylanstrategie** [comment]
Airlock code has basically stopped being maintained a while ago. Almost everything airlock-related has some sort of issues, from door wires to bolted airlock interaction

**Comment by clusterfack** [comment]
If you aren't part of the solution you're part of the problem @dylanstrategie
