### ISSUE TITLE
No busycheck for picking rocky debris

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#4970]
To reproduce: Wield pick/drill, walk into rocky debris a lot.
You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.You start picking the rocky debris.

Especially jarring now with the progress bars, since it gets reset every time you "bump" into it.

**Comment by ComicIronic** [comment]
Stop walking into the debris, then!

**Comment by 9600bauds** [comment]
When you mine, you just hold a key.
Mining asteroid walls does have a buycheck.

**Comment by ComicIronic** [comment]
Well, truthfully, no it doesn't.
It just suppresses messages if you've dug recently enough.
