### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Light Replacer does not implement high-efficiency bulbs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4972]
>Revision (Should be above if you're viewing this from ingame!)
1767fa9a160eab35f2b32313ec05cf0b9956517e 

>General description of the issue
When an empty light replacer is filled with high efficiency bulbs, the replacer still inserts regular tubes into light fixtures
though its probably just the way the replacer works, it is quite annoying and weird to have regular bulbs be inserted after all that

>What you expected to happen
the high efficiency bulbs to be inserted
>What actually happened
a normal bulb

>Steps to reproduce if possible
fill empty replacer with HE bulbs, replace an empty light fixture

**Comment by Exxion** [comment]
Fixed in #4800, assuming I ever get around to finishing it

**Comment by Exxion** [comment]
Until then, though, install an HE bulb once into the socket by hand and the replacer will fill that socket with HE bulbs. I think.

**Comment by Exxion** [comment]
HAHAHA SOME DAY I WILL FINISH THAT I SWEAR

It's actually almost done but I don't currently have the time or motivation to finish it
But honestly it's only a couple more hours of work total, at most, so whenever I DO have the time and motivation, it should be finished promptly
