### ISSUE TITLE
map errors

### ISSUE THREAD

**Issue by kylefiredemons** [d3athrow/vgstation13#4973]
Whenever I try and open a map, I only get a black screen and this message: Compliation errors present (CTRL+K) and correct them in order to use the object and edit trees.

**Comment by ComicIronic** [comment]
Are you on the latest version of the code?
Which map are you trying to edit?

**Comment by kylefiredemons** [comment]
Yea, I'm on the latest version bleeding edge, downloaded it in a .zip file and tried to open tgstation.dmm

**Comment by clusterfack** [comment]
You have to compile before opening a map, I think that's the issue here

**Comment by kylefiredemons** [comment]
Oh, I'll try that.

**Comment by PJB3005** [comment]
Compiling beforehand shouldn't matter, most likely a corrupt download if I had to guess.

**Comment by ComicIronic** [comment]
It would be easier if we knew the compile errors you were getting.

**Comment by clusterfack** [comment]
You guys have never opened a map and gotten compilation errors present? Happens all the time if you cancel a compile at the least

**Comment by PJB3005** [comment]
>Compiling in DM

**Comment by ComicIronic** [comment]
I have never gotten the latest version of the code and opened a map with compilation errors.

**Comment by clusterfack** [comment]
>trying to use meme arrows on github

**Comment by PJB3005** [comment]
\>Making me fix my meme arrows.
