### ISSUE TITLE
Can't emag sec barricades properly

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#4981]
You can emag the thing, it'll give you the [two messages] (http://puu.sh/iqoTV/cae0709703.png)  that the barrier has been unlocked, and it'll prevent people from using their ID on it. But it's still locked in place.
You can (instantly) repair it with a wrench to regain the ability to use an ID to unlock it.

**Comment by Zth--** [comment]
I fixed this one on gitlab
