### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Taxi Station Lights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#4982]
>Revision cea4e4e00c872066c76afc5c12adeba8accf83e4 
>General description of the issue
Lights (tubes and bulbs) with the unbroken sprite are not giving light, presumably after being BOO'ed. Replacing them either breaks them or fixes them.

>What you expected to happen
Inserting the lightbulb into the fixture should turn it back on.

>What actually happened
Half the time the lights broke, half the time they were relit.

>Steps to reproduce if possible
Fire up taxi station, have a few ghosts boo the lights, and watch for lights to turn off while they have the unbroken state. Attempt to replace light.

**Comment by clusterfack** [comment]
Not sure if the problwm is supposed to be lights are not getting relit after boo, or that there's a problem with replacing lights instead.

**Comment by 9600bauds** [comment]
Vague as fuck, old as fuck, prolly sounds like the shuttle lights bug
