### ISSUE TITLE
Fucked up firelock in toxins storage

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4984]
![iturnmybackforaweekandthisshithappens](https://cloud.githubusercontent.com/assets/12202731/8174847/dd61c09c-13af-11e5-83b1-2ff0b432249f.png)
This picture is worth a thousand words.
Also where the hell is the PR for the new firelocks?
I didn't see one.

**Comment by Exxion** [comment]
#4753

**Comment by FudgePucker** [comment]
Ah overlooked that one.

**Comment by 9600bauds** [comment]
![dreamseeker_2016-01-25_21-15-03](https://cloud.githubusercontent.com/assets/6526157/12568917/b967d268-c3a8-11e5-85aa-297f9c5d2e0a.png)

Seems like it got fixed at some point
