### ISSUE TITLE
The SME chamber is STILL FUCKED UP

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#4985]
I KNOW THAT THIS IS THE 5th OR 6th ISSUE REPORT ON THIS, BUT THAT FUCKING SME VAR EDIT STILL FUCKS IT UP. GOD DAMN IT.
![tenthtimethisshift](https://cloud.githubusercontent.com/assets/12202731/8175805/5caae258-13be-11e5-868a-076c2fe18034.png)
GOD DAMN IT NOW I'M ON FIRE.
THANKS GITHUB.

**Comment by clusterfack** [comment]
Where is your mapper go now?!

**Comment by CptWad** [comment]
He go to mystical end death where all is lost.

**Comment by AutismSpider** [comment]
Make the floor unsim like it was

**Comment by ComicIronic** [comment]
No the floor will not go back to being unsimulated.

**Comment by AutismSpider** [comment]
that or unfuck it for like the 10th god damn time

**Comment by PJB3005** [comment]
OH GOD IT'S LOOSE

**Comment by IratePirate** [comment]
How is this still a thing?

**Comment by FudgePucker** [comment]
@IratePirate 
HAHAHAHAHAHHAHAHA
NOBODY FUCKING KNOWS!

**Comment by Intigracy** [comment]
close, we have two other issues on this
