### ISSUE TITLE
Mailing shit through disposals tears up the floor tile of the receiving bin

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4995]
Might be related to a runtime on disposalholder transfer() that happens when they reach the end of the line

**Comment by ComicIronic** [comment]
A reopening of #1557.

**Comment by PJB3005** [comment]
Ah, I did a quick search of open ones but didn't look at closed ones

**Comment by PJB3005** [comment]
Also, it turns out that when this happens, a base ´/obj/item/stack/tile´ gets created, which has no sprite and the name is "item".
