### ISSUE TITLE
Way to see where a teleporter is going

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#4997]
we need one, the one that's not a telescience teleporter, by the way

**Comment by ComicIronic** [comment]
Should add it to the console.
What else is it good for?

**Comment by PJB3005** [comment]
What do you mean?

**Comment by ComicIronic** [comment]
The teleporter console machine. I actually can't think what it does.

**Comment by PJB3005** [comment]
ah, well, allow the user to set the destination
