### ISSUE TITLE
Rust Gyrotron computer not working.

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#5004]
I tried building a rust. So far I got the core to produce a field, and fuel injectors to almost work. I dont know if its just something I did wrong on my part, but I couldn't get fuel for the fuel injector. But one thing that defiantly didnt work was the gyrotron computer. I was unable to pull up a menu, and when I did there was nothing on it. I looked it up online and some branches said you need admin to access their console. Using AdvProcCall (which I dont know nothing about).

Here are the guide I used:
https://www.reddit.com/r/SS13/comments/2r7rwo/building_your_rust_from_scratch_experience_notes/
http://baystation12.net/forums/viewtopic.php?f=1&t=8886

I am aware these are different branches with different code, but I think the code for the rust is similar since I ran into similar problems with the Gyrotron computer.

**Comment by 9600bauds** [comment]
Could be related to #2958

**Comment by Probe1** [comment]
Someone please fix it. It's time.  

Time for R-UST.

**Comment by clusterfack** [comment]
By fix you surely mean build from scratch

**Comment by Probe1** [comment]
Don't care how.  Just care when.   The Summer of R-UST

**Comment by PJB3005** [comment]
Fuel injectors and gyrotrons for the RUST are broken due to a lack of specfic proc calls in the firing code, 1 line fix for each.

Gyrotron controllers simply aren't buildable.

**Comment by FudgePucker** [comment]
Why not just replace RUST with a new atmos based engine anyways?
How does R-UST work again?
Does high pressure and heat still melt walls?
PLASMAFIRES CAN'T MELT WALLS, WAKE UP SHEEPLE.

Also TEG needs to be fixed up, I don't even understand how it works (I don't think anybody does), hot air on one side and cold air on the other didn't work.

**Comment by PJB3005** [comment]
Fudge, it does work, I've set it up multiple times, you're doing something wrong.

**Comment by FudgePucker** [comment]
The R-UST or the TEG?
The first and only time I tried to set up the R-UST the admins even spawned as players to try to help me and still didn't know how to do it.
When I tired to make my own TEG, I had it super hot on one side and super cold on the other but it produced as much power as me pissing into a turbine.
People complain about learning how to make a SME requiring a master who knows how the super matter works to teach you, TEG and R-UST are both 100 times more complecated in their functioning and require a master to teach you, but there are none.
TEG and R-UST also are very hard to learn by looking at code. Glancing at the super matter code you can understand it easily, the effects that pressure heat have on it, the effects of N2, and other things. TEG and R-UST code is in hieroglyphs. How does pressure effect the TEG? How does R-UST work again?

**Comment by PJB3005** [comment]
Fudge, the TeG works, it's not that hard.

Both loops need less pressure at the output than the input to work, it's not that hard.

oh, and dumping an entire can of plasma into the hot loop is guaranteed to fuck up.

**Comment by AutismSpider** [comment]
The R-UST needs full rework

Gyrotons controller is broken and you need admin power to force them on.

The injector ports to make full rods can not be feed compressed matter so you need to use admin powers to do that..

Sadly the monitoring computer doesn't work, so i had to use the Variables on the EM Field to see how the reaction was going. You should see "Energy" increasing from gyrotons, and the amount of reagents increasing, then diminushing as they are fusionned to make more energy. Once the reaction is started, you can stop the Gyrotons.

can go on and on about this.

**Comment by PJB3005** [comment]
I am working on fixing bits of the R-UST, Already fixed the gyrotrons, including their control computer.

Fixed fuel injectors too.

**Comment by AutismSpider** [comment]
wait let me look over my notes

**Comment by AutismSpider** [comment]
Yup rust fuel compressor for the matter

The fuel ports are missing icons for facing left right etc  (you can 'rotate' it in variables screen and use that to see it)

got make sure its facing the matching injector and two tiles away

**Comment by FudgePucker** [comment]
No really, am I the only one who thinks that the R-UST is way too over compicated?
It requires like, what, 4 specific computers that are only used for it?
FOUR?
Singulo and AME have none.
SME and TEG have one or two if set up right, the Atmos automations computer, and it has uses outside of the engines.
R-UST has 4 of them, all of them overly complex, all of them worthless outside of the engine.

**Comment by 9600bauds** [comment]
doesn't the singulo use the PA computer

**Comment by AutismSpider** [comment]
4 computers and only two of them work. 

Gyrotron Controller (they need to be in the room with the core and other stuff is full of hot plasma etc)

RUST Fuel Injection Control computer (do we really need this?)

RUST Core Control computer (this is used to turn on the RUST Core)

monitoring computer (does not work at all)

Singulo as the PA computer man

**Comment by PJB3005** [comment]
The file for the monitoring computer is *COMPLETELY* empty too, thanks cael!

**Comment by AutismSpider** [comment]
Sadly the monitoring computer doesn't work, so i had to use the Variables on the EM Field to see how the reaction was going. You should see "Energy" increasing from gyrotons, and the amount of reagents increasing, then diminushing as they are fusionned to make more energy. Once the reaction is started, you can stop the Gyrotons

**Comment by FudgePucker** [comment]
On a scale of 1-10 how fucked is the station if you put an output from the rust into distro?

**Comment by AutismSpider** [comment]
hotter then sun.

that's how hot the RUST makes plasma on top of making more plasma as it powers stuff and all the rads it gives off.

**Comment by AlphaBuffalo** [comment]
So what else needs to be fixed for the RUST?

**Comment by AlphaBuffalo** [comment]
So what else needs to be fixed for the RUST

Wrong button

**Comment by AlphaBuffalo** [comment]
Wrong button

**Comment by AutismSpider** [comment]
The computers need to be look at for the RUST to make sure they work.

**Comment by PJB3005** [comment]
Okay, the R-UST monitoring computer doesn't even exist, there's a "radiation monitor", but that's nothing but a sprite and name, because radiation isn't even implemented.

**Comment by PJB3005** [comment]
@FudgePucker, the R-UST Mk. 7 isn't overcomplicated, you just can't handle the autism :^)
