### ISSUE TITLE
RMCE spelling and formatting error

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5007]
Says "finsihed remplacing protolathe]'s components.

I'll prob fix it myself unless someone beats me to it.

![ss 2015-06-17 at 01 29 28](https://cloud.githubusercontent.com/assets/8550416/8200685/9d86513a-1496-11e5-97ca-f78604f43cef.png)

**Comment by clusterfack** [comment]
He really likes remplace

[i]http://puu.sh/irXbL/7733473a45.png[/i]

**Comment by Probe1** [comment]
It's part of the charm.

**Comment by PJB3005** [comment]
Shitty tools have shitty spelling, amirite?
