### ISSUE TITLE
Taxi Station: Medbay Needs Two Roundstart Cryoxadone Beakers

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5010]
The other stations have it, and it's convenient not having to make cryox in addition to clonex. There is one beaker in the paramedic's area (despite the Taxi paramedic not having their own cryo tube) but there should be two regardless.

**Comment by FudgePucker** [comment]
I haven't played medbay in a while but those round start beakers of cyrox are super useful.
Clonex is easy to make... if you have cyrox.
Its just three or two chemicals added to cyrox to make clonex, making cyrox requires more and also requires plasma.
Of course I am just lazy and always try to find a way around having to grind up my roundstart plasma and having to deal with managing it, I also 'borrow' the O2 first aid kits to make dex+ from.
