### ISSUE TITLE
Admin "Jump to Area" lists areas that don't exist

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#5011]
like "Mars", "Where Am I?", "Prison Podbay" and "Nanotrasen Cruiser".
I'm sure there must be some esoteric reason so as to WHY but I'd really like it if it just didn't.

**Comment by ComicIronic** [comment]
It goes through typesof and then uses locate, which is a sensibly better method than going through world, or some such.

**Comment by dylanstrategie** [comment]
I'm going to suppose it loops through the list of areas in the code, instead of the existing areas in-game

**Comment by clusterfack** [comment]
I made a global list of areas created by new(), it just needs to use that instead

**Comment by 9600bauds** [comment]
What's the name of such list

**Comment by gbasood** [comment]
> You can check the variable area.x to see if a given area is on the map or not.

http://www.byond.com/docs/ref/info.html#/area/room
