### ISSUE TITLE
PDA atm app and transaction logging

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5014]
Yet another terrible feature request.

First change, have all digital transactions logged, so the captain or whoever can look through them. Excuse to use physical credits for payment for illicit things.

Second.
Have an app you can download onto your pda/buy/whatever from the pda thing. The ATM app.
To use this app, you must have an id card inserted. Opening the program prompts you for a pin and account number, and if you enter them correctly for that ID, from then on the PDA is authorized.

Wearing the authorized pda lets you use vending machines without asking for a pin, atms without asking for account numbers and pins, and allows you to do player transactions without entering account numbers or pins. Just swipe and go. 

Ejecting the id card automatically de-authorizes the pda though, and you can manually de-authorize in the pda interface. The app might also have an option to view transaction logs of the linked account.

It'd also be neat if somehow this also worked the other way as well, ie: depositing into your account from a transaction from another player.

As a possible extra, heads could have secure accounts that'd require a DNA sample in addition to authorize. Of course, how you get this DNA sample is up to you I'm sure.

This would make digital transactions easier to manage between players, and maybe allow for easier implementation of economy in the future.

**Comment by ComicIronic** [comment]
Transaction logs are already created for a lot of things on the vendor account.
