### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Taxi Station Mining

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5020]
>f71d09ba60133d4854d98147a820968a084a4933 

>Taxi station's mining area needs improvements. The area needs that no atmos-sucking area like in boxstation's engineering area. 
There is no console for the stacking machine for the ores smelted outside.
The ore redemption machine does not credit user for any ore placed in. Simply deletes the ore without anything to show for it.

>Do it how it is suppose to do and you can't

:^)

**Comment by ComicIronic** [comment]
>The area needs that no atmos-sucking area like in boxstation's engineering area. 

Absolutely no.
