### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Ore Redemption Machine keeps eating my shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5023]
>1c23d3d8b8f0714342d0ccea2aafa1403991ac2c 

>Be a miner
>Go mine shit
>Go back to reap your awards
>Happily put your ores into the ore redemption machine
>Cry as your ores go the next plane of existence

t-thanks

**Comment by clusterfack** [comment]
Dupe #5022
