### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Handheld light sources are getting "stuck"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5024]
>1c23d3d8b8f0714342d0ccea2aafa1403991ac2c 

>General description of the issue
Lightsources like PDAs, Flares, and Flashlights are getting "stuck on a tile when players are moving, leaving the holder with an activated, albeit useless light.

**Comment by PJB3005** [comment]
I sense lack of forceMove
