### ISSUE TITLE
MoMMIs Can No Longer Put Their Flashlight in Their "Pocket"

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5025]
Used to be that a MoMMI could equip its flashlight, turn it on, then put it back in its equipment slots and it'd still light up the surrounding area, giving the MoMMI a hands-free light. This doesn't seem to work any more, with the light now disappearing as soon as you unequip it.

**Comment by FudgePucker** [comment]
I think you can still wear hardhats.
Just nab the white one the CE will drop and become the REAL CE.

**Comment by Shadowmech88** [comment]
You can, but MoMMIs shouldn't have to choose between being able to see in the dark and getting to wear a fun hat. Also now you can't combine the hardhat light and the flashlight light for more light.

**Comment by AutismSpider** [comment]
it happens with cyborgs too not just mommis.

turn the light on and store it save up slots.

**Comment by CptWad** [comment]
Come now this was the bug we never wanted to report or get fixed.
Though now its fixed, unfixing it would make me feel dirty.

**Comment by Shadowmech88** [comment]
Well, if you don't want to make something that seems like a bug, we could always add a silicon headlight that functioned exactly like a hardsuit helmet light, toggleable via a screen icon instead of it being a module. It's not like any borgs ever DIDN'T have their flashlight active at all times anyway if their model had one available.

**Comment by PJB3005** [comment]
Yeah, this was a bug of lack of forceMove(), which I fixed, because lack of forceMove() in DAL has different effects than lack of forceMove() in bay lights

**Comment by CptWad** [comment]
Im ok with a function like that.
