### ISSUE TITLE
Recycler produces absurd amounts of material

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#5033]
The recycler at the end of disposals produces way too many materials. For example; one igniter is worth 75 sheets of iron and 75 sheets of sand.

**Comment by PJB3005** [comment]
@ComicIronic

**Comment by ComicIronic** [comment]
Henk henk henk henk who coded this

**Comment by PJB3005** [comment]
@ComicIronic, it was N3X15

**Comment by ComicIronic** [comment]
Oddly, the smelter works in the same way.
That is dumb.
