### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Robotic modules can be put inside various containers with bad results.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5034]
Revision 9ca1158533c2a8c0bb9bce5d4550ca0c867e4126 
Two examples: Cyborg hypospray into the Smart Chemical Storage, flashlight into potted plant. Both of them become permanently bound to one of your hand slots, and the hypospray stops recharging.

Reproduce: Activate hypospray, click on fridge.

**Comment by Exxion** [comment]
It's stacks all over again!
