### ISSUE TITLE
Autolathe hacking inconsistency

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#5037]
Multitool toggles wires permanently rather than for a minute or so, meaning if you pulse the shock wire, it's shocked forever and so you're fucked if you didn't have gloves (important for scientists who can't order gloves from the supply shuttle)
Hacking the autolathe has to be done with a multitool, cutting the contraband wire does nothing. This is unlike the previous hacking method, where pulsing the contraband wire toggled contraband for a minute and cutting the wire toggled contraband forever.
Since pulsing toggles the wire, you can pulse the main power wire to turn the machine off, and then cut the wire to turn the machine back on despite the wire being cut (???) (same with the shock wire)

**Comment by PJB3005** [comment]
A lot of this shit was from before @ComicIronic's material datums PR.

**Comment by 9600bauds** [comment]
I don't recall any of this happening before

**Comment by PJB3005** [comment]
I do

**Comment by 9600bauds** [comment]
I just tested this in a build from before Comic's material datums PR.
Pulsing the contraband wire only toggled contraband for a short while, cutting it was permanent.
Pulsing the shock wire only shocked for a short while, cutting it was permanent.
Indeed these issues weren't there before

**Comment by Probe1** [comment]
what bauds said.  previously you had to clip the wire to keep contraband on. now clipping wires doesn't toggle the blue light at all and pulsing them keeps them toggled forever.

**Comment by Kurfursten** [comment]
@clusterfack @PJB3005 Oh, neat. I actually fixed this one a while back with "wire holder stuff" PR
