### ISSUE TITLE
That's a material synthesizer. It currently holds 1e+007/60 matter-units.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#5041]
1) acquire matsynth
2) try to make metal
3) you will be prompted to input the amount you want to make 3 times
4) put 1 (or any amount you can legitimately make) the first time
5) put any crazy negative amount in the following two
6) That's some metal. They are a normal-sized item. There are -1000 metal sheets in the stack.
7) title
8) now use those mad matter units to make whatever you want
9) whatever you want

**Comment by ComicIronic** [comment]
> you will be prompted to input the amount you want to make 3 times

What
WHAT

**Comment by 9600bauds** [comment]
![2015-06-18_19-07-48](https://cloud.githubusercontent.com/assets/6526157/8243426/51a63502-15ed-11e5-9b7d-58f900f59508.png)

**Comment by Exxion** [comment]
What in the ungodly fuck

**Comment by FudgePucker** [comment]
OH SHIET
ADD HONK AND ITS LOOSE TAGS.
ITS HABBENING

**Comment by PJB3005** [comment]
I couldn't reproduce this locally

**Comment by Exxion** [comment]
I will punch myself and everyone in sight in the goddamn face if this still happens

**Comment by Kurfursten** [comment]
@clusterfack I do not believe this happens anymore
