### ISSUE TITLE
Material Datums are slow

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#5044]
Oh god please save us I never asked for this

![](http://puu.sh/itECA/626c7459db.png)

**Comment by 9600bauds** [comment]
can we fix it???

**Comment by clusterfack** [comment]
No we're fucked!

**Comment by Iamgoofball** [comment]
how do we know this is because of material datums and not some other retarded crap

**Comment by clusterfack** [comment]
1. I bisected it and materials datums caused it
2. I looked at the code and material datums caused it
3. I tested changes to it and material datums caused it

**Comment by 9600bauds** [comment]
but can we fix it???

**Comment by clusterfack** [comment]
Yes

**Comment by clusterfack** [comment]
But I have no idea how to pool material datums correctly, comic will have to fix that part for me

**Comment by PJB3005** [comment]
qdel for datums when.

Oh, when we fix @eswordthecat's shit and get rid of all deletions of datums via directly calling Destroy()

**Comment by ComicIronic** [comment]
Who even puts a hard del in the default behaviour of a ref cleanup proc

**Comment by PJB3005** [comment]
@ComicIronic, @eswordthecat does
