### ISSUE TITLE
People Walking With One or No Legs

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5051]
I'm not sure if this was an isolated incident or not, but I had one person last round able to walk despite not having any legs, he was just a floating torso. And then another was unable to walk without legs, but became able to walk when I had given him just one leg, when it used to be that missing any legs or feet caused a person to have to crawl. Furthermore, before I gave him the leg he was unable to crawl, and I know that legless people used to be able to crawl.

**Comment by Shadowmech88** [comment]
I just tested this on an up-to-date local server and, despite moving slowly, a legless human was able to "walk" by levitating across the ground, completely upright.

**Comment by dylanstrategie** [comment]
Clear, functional reproduction steps would be useful, otherwise we basically have to stab in the dark until we figure out which proc is fucked

**Comment by Shadowmech88** [comment]
@dylanstrategie 
Have genetic eating power.
Eat both of a person's legs.
That person can still walk.

Put person on surgery table.
Cut off both of their legs.
That person can still walk.

When I cut a person's legs off with an energy sword they were unable to walk after I fixed them up, so that works at least.
