### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Ghosts cannot use see detailed list on crew monitor/bhangmeter

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5052]
> Revision ee940b391c22fbcc8525b6d6168a77915983e925 
> 
> General description of the issue
> Ghost's cannot see the detailed list of crew/blast list. It just greys out
> 
> What you expected to happen
> To work
> 
> What actually happened
> Nothing
> 
> Steps to reproduce if possible
> Be a ghost, try to view the detailed list

**Comment by Shadowmech88** [comment]
I think that's because it's actually a button your character has to press. Ghosts can view things, but can't interact with anything besides lightswitches and lights.

**Comment by PJB3005** [comment]
This is why we need better Jscript UIs, so ghosts can open that menu without actually effecting the computer.

**Comment by dylanstrategie** [comment]
I would rather have the computer open on the crew monitor list by default
