### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Entrall Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5055]
>Revision (Should be above if you're viewing this from ingame!)
862ff2aac25c0822a7e22e64187919b889da022a

>General description of the issue
entrall is not working

>What you expected to happen
Being able to entrall people to enslave them

>What actually happened
When entralling someone I lose no blood and the other player gets a message of somekind but nothing more

>Steps to reproduce if possible
get blood, entrall someone

**Comment by CptWad** [comment]
Yeah I noticed that enthralling was weird. I tend to ignore it since I never find it reliable or easy to do.

**Comment by Shadowmech88** [comment]
Enthrall doesn't cost blood, it just has a minimum blood requirement. Once you reach the threshold, you can use it for free as many times as you like as long as you have that much blood in your system.
Also, enthralling is a strictly RP thing, there isn't any measurable effect on the other player. If you enthrall someone and they don't do what you tell them, ahelp it.

Though I do think that enthralled people should be given some kind of icon like cultists and revs to really drive home the point that they HAVE to listen to the vampire.
