### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Ore box contents disappearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5056]
>Revision (Should be above if you're viewing this from ingame!)
862ff2aac25c0822a7e22e64187919b889da022a 

>General description of the issue
When loading ore boxes with mining stachels, the box will eat all of the ores but stay empty.

>What you expected to happen
Ores to go into the box

>What actually happened
Ores disappeared into nothingness

>Steps to reproduce if possible
Mined ant detonated 0-chain gibotine, collected various materials, "loaded" the ore box only to find it empty when I checked

**Comment by ComicIronic** [comment]
Someone do me a favour and test this on-server when it restarts.

**Comment by Intigracy** [comment]
No longer happens, please close.
