### ISSUE TITLE
Telecommunication doesn't works on Ministation

### ISSUE THREAD

**Issue by abcdicks** [d3athrow/vgstation13#5057]
It works with station bounced radios, but not with headsets.

**Comment by Exxion** [comment]
I don't think Ministation is really supported anymore

**Comment by abcdicks** [comment]
That sucks. But I'd appreciate if someone could take a look and see if they can fix it.

**Comment by Exxion** [comment]
I might take a look at it, but I'm busy for the next couple days, so someone else can go ahead and fix it if they want to.

**Comment by 9600bauds** [comment]
There's not even a tag for this map

**Comment by Exxion** [comment]
I'm pretty sure Ministation doesn't even compile anymore
