### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Spiderbot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5058]
>Revision eada012498db1d70aa5dfbf13c246d1670abec93 

>Why cant SpiderBot ventcrawl??

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Exxion** [comment]
Thanks. How descriptive.
But this should have been fixed a few hours ago in #5046, so this should be looked into.
