### ISSUE TITLE
play-local-sound is broken and has been for a while

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#5062]
It doesn't work, there isn't much to explain.

**Comment by clusterfack** [comment]
This is news to me. Play local sound is a very simple proc, so it is likely from a modification to playsound itself, last person I know modified that is @ComicIronic 

![](http://puu.sh/ivNLP/d220fbefa9.png)

**Comment by dylanstrategie** [comment]
Testing shows that this work as intended with a variety of sounds, even ones that are usually dodgy like the health analyzer sound

**Comment by NigglyWiggly** [comment]
The health analyzer shit isn't what I'm talking about, I mean the specific admin verb

**Comment by dylanstrategie** [comment]
The verb should work, I've tested locally

Can someone else test it ? play-local-sound and pick a sound

**Comment by NigglyWiggly** [comment]
You're right, it's all good now.

Gonna close this.
