### ISSUE TITLE
Dionae accidentally inherit monkey inventory

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#5063]
This leads to a few oddities. You can't wear hats and anything you wear is shown as floating because it's trying to align with a monkey sprite

Someone competent in sprites will need to fix this

**Comment by SpaceOracle** [comment]
>You can't wear hats
I finally managed to figure out how to possess a Dionae and noticed the UI doesn't have a slot for hats, only masks. Is there a reason they should be able to equip hats?

**Comment by clusterfack** [comment]
Did you try quick equipping a hat?

**Comment by SpaceOracle** [comment]
If by that you mean pressing 'e' as a keyboard shortcut it doesn't respond. It does throw a "you can't equip this" message if you try putting it on your mask or back slot.

**Comment by gbasood** [comment]
I need to be able to put butts on my own head
I need to be the butt nymph
