### ISSUE TITLE
Add the Ability to Turn Off Antag For Specific Jobs

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5065]
Like if there's a certain job where someone dislikes being antag, then they won't get antag status ever if they get that job, but will get it normally otherwise.

**Comment by clusterfack** [comment]
I'm not sure I agree with this, either way it would require a pretty big rewrite of how job/antag assignment works at the moment.

**Comment by Shadowmech88** [comment]
One has to be assigned before the other, right? Could you not just have it run a check so that either being assigned the job excludes them from antag, or being assigned antag excludes them from that job?

**Comment by ComicIronic** [comment]
The issue comes from setting it up in the character database.
It might require adding a set of rules that people can edit and add to for their own slots.

Or they can just copy a slot and edit the job and antag preferences.

**Comment by Probe1** [comment]
On the topic of roles and priorities, it would be nice if head roles were weighted more during selection.  I don't always want to play a head role but I'm willing to take it if no one else wants it.  Currently using low head roles and medium other roles the chance of getting a head role is very low.  

Hell, the chance of getting a job that is understaffed is fucky.  Everyone has a recent story of putting 3 jobs to medium and ending up in a slot with three coworkers, and their other job choices have no players.
