### ISSUE TITLE
Eating Someone's Groin is Lethal

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5069]
I got a monkeyman and matter eater, and proceeded to eat all of their appendages. They remained at 100% health throughout, and then suddenly dropped dead when I ate their groin (the last edible part of them).
Stranger still, they dropped dead despite having 100% health at the time of death.
![100 dead](https://cloud.githubusercontent.com/assets/3991927/8266894/5f828b7e-170c-11e5-86bc-0e8c06a386b0.PNG)

**Comment by dylanstrategie** [comment]
I am pretty sure losing your groin, torso or head is an instant kill condition because these cannot be amputed currently

**Comment by Shadowmech88** [comment]
Realistically, you should be able to live without your groin for a little bit since all of your most important organs are in your chest.

**Comment by ComicIronic** [comment]
Remember the rule of 3: 3 minutes without air, 3 days without water, 3 weeks without food, 3 microseconds without your wang.

As for the health thing, you aren't actually taking organ damage when you lose limbs. You can be at 100% health with no arms and no legs, because you haven't necessarily been hurt.

And the groin is a vital organ, so losing it kills you. I might deem this closeable.

**Comment by Shadowmech88** [comment]
Why is the groin a vital organ?
Also, losing other vital organs such as the lungs or liver doesn't immediately kill you, it just causes damage which eventually kills you.

**Comment by ComicIronic** [comment]
Losing an external vital organ is different to losing an internal vital organ.

And the groin is a vital organ because it just is. It's the lower half of your torso, you couldn't lose it and survive without some pretty major surgery.

**Comment by Shadowmech88** [comment]
>It's the lower half of your torso, you couldn't lose it and survive without some pretty major surgery
It contains your kidneys, pancreas, spleen, and intestines. None of these are immediately fatal when lost, and blood loss isn't a factor since eating extremities doesn't cause blood loss.
Sure, you might die from infection or sepsis or blood sugar buildup or the like, but you'd be good for at least an hour.

**Comment by Iamgoofball** [comment]
@Shadowmech88 from a sprite standpoint the groin is also your hips

you look extra dumb if your mob has legs but no groin

**Comment by Shadowmech88** [comment]
@Iamgoofball 
When you eat someone's groin their legs fly off as well, so having legs but no groin isn't an issue.

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.

**Comment by gbasood** [comment]
Eating someone's groin with matter eater is currently prevented in code, as well as their head, eyes, mouth and their torso. Tested just now and confirmed working. Should only be possible to eat ACTUAL appendages. If someone figures out how to eat vital body areas they can open a new issue or re-open this one.
