### ISSUE TITLE
Most Autolathe designs build literally instantly

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#5072]
I mean don't get me wrong it's nice but it's a little bit tooooo fast
Maybe cap the lowest build time to 1 second or so?

**Comment by ComicIronic** [comment]
It's not actually 0 time, but it's small enough to seem it because some designs have very low cost, like 50 metal or 30 glass.

I could add a min time, since it already has a max time.

**Comment by 9600bauds** [comment]
I believe it's actually 0 time since the build time function rounds down
