### ISSUE TITLE
Cut() vs len = 0 Memory Leak

### ISSUE THREAD

**Issue by Fox-McCloud** [d3athrow/vgstation13#5073]
Right, so, Len = 0 does generally outperform cut() (barely), but there's one major issue: len = 0 blanks out the list, but the original list continues to exist--thus resulting in a memory leak.

Either case, until this BYOND issue is fixed, utilizing len = 0 over cut() may not be the best idea.

**Comment by ComicIronic** [comment]
>the original list continues to exist

WHAT

**Comment by gbasood** [comment]
So I just tested this with both len=0 and Cut()

~~The memory usage of Dream Daemon steadily increases, along with expected wibbly-wobblying, using either Cut() or len = 0~~

Nevermind both of them don't leak at all.

**Comment by MrsTonedOne** [comment]
http://www.byond.com/forum/?post=1854520

It was resolved

**Comment by 9600bauds** [comment]
ty mr. lummox
