### ISSUE TITLE
Neurotoxin still needs you to use a menu or right-click

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#5074]
Who is the retard that coded this ? Who thinks that binding a combat action to either right-click or selecting your opponent in a list is a good idea ?

All you had to do is rip off the dozens of guns that use stun bolts or even the Wizard's magic missiles, but of course you couldn't do that

**Comment by Exxion** [comment]
Gotta warm up those neurotoxin emitters

**Comment by AutismSpider** [comment]
nothing to warm up though

only thing that should have a warm up is when the ling uses range booster for the stings

**Comment by Exxion** [comment]
I was making a joke
Never mind

**Comment by PJB3005** [comment]
yeah he was referencing portal

**Comment by AutismSpider** [comment]
take look at xenos neurotoxin too then
