### ISSUE TITLE
[Vox] Every N2 Tank and Emergency N2 Tank

### ISSUE THREAD

**Issue by Drag3ndz** [d3athrow/vgstation13#5079]
As of this update, the mask release pressure on every emergency nitrogen tank designed for the Vox always start off at 104kPa whereas the emergency oxygen tank always start their mask release pressure at 21kPa. The nitrogen tank holding 303 kPa compared to the oxygen tank holding 607 kPa is a bit odd, and going to atmospherics in every round as a Vox can be a little annoying. Can you match the normal nitrogen tank pressure and fix the emergency nitrogen tank mask release pressure? Thanks in advance.

**Comment by 9600bauds** [comment]
This has since been fixed
