### ISSUE TITLE
Can't Reattach Flesh Legs

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5080]
Even if you salvage the limb, the only option is a robot or peg leg. I assume this is true for all sever-able extremities.

**Comment by AutismSpider** [comment]
all body parts - the head.

no way put salvage butts hands legs foot back on.

**Comment by ComicIronic** [comment]
You can replace the lost limb by using meat, if you didn't know that.

I'm not sure if it has to be synthmeat specifically, but you can do it.

**Comment by AutismSpider** [comment]
bit silly i got say 

using slab of raw meat for a new limb and not the limb they lost etc.

**Comment by Probe1** [comment]
>You can replace the lost limb by using meat, if you didn't know that.

>I'm not sure if it has to be synthmeat specifically, but you can do it.

this is why when you change something you add it to the wiki.

**Comment by AutismSpider** [comment]
Any meat work even corgi meat?

**Comment by Probe1** [comment]
I tried in game and was unable to create limbs with any type of meat following the limb reattachment procedure.
