### ISSUE TITLE
Forcemove is making the code lag

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#5083]
![](http://puu.sh/ixKDR/00ed0df4cb.png)
Note the turf/entered() call in the 4th highest proc call space.
This is due to the fact forcemove() is now used throughout the code which forcibly calls turf entered whenever a loc changes. 

![](http://puu.sh/ixKJg/a6e81d4631.png)
Specifically, this comes from the up to 100 loop of hasproximity for every time forcemove() is called and proceeds to call turf/entered. This is particularly prominent when, say miners for example, fill their conveyor belt with minerals which call forcemove being moved to the next turf, they have proximity with 100 objects every time.

Either
Someone needs to rewrite the hasproximity system to use another method like invoke events perhaps
Or forcemove needs to stop being used so often when it isn't important for hasproximity (this seems unlikely to me)
Or some other solution some creative person needs to think up

**Comment by ComicIronic** [comment]
God, what an old and stupid code segment.

    if(Obj.flags & PROXMOVE)
        for(var/atom/movable/A in range(1))
            if(A.flags & PROXMOVE)
                A.HasProximity(Obj, 1)

**Comment by clusterfack** [comment]
Hasproximity is preposterously old, it's used for infrared emitters I believe but I have no idea what else.

**Comment by Zuhayr** [comment]
It would probably be faster to just have objects that need proximity check for it in process() at this point.

**Comment by PJB3005** [comment]
`forceMove()` being used less often is a no-go, because shit like lighting bugs out otherwise

**Comment by clusterfack** [comment]
That was pretty much what I figured, so make a workaround or replace hasproximity (which is old as FUCK anyway and probably should be removed)
