### ISSUE TITLE
Fucking fix vamp

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#5089]
The fact that they can get up after death in two secs in dumb fix the timing or take off that power

**Comment by Shadowmech88** [comment]
Fix default vampire sure, but I think there should be an adminbus way or a way via crazy amounts of blood to get the 2 second regen, I like the idea of an Alucard vampire.
I think it should be left in the code somehow.

**Comment by AutismSpider** [comment]
Add like admin verb to fuck with the timer for it then.
