### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Windoor deconstruction improper return

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5095]
Welding a plasma windoor results in reinforced glass instead of reinforced plasma glass.

**Comment by dylanstrategie** [comment]
Most likely an inheritance problem or an oversight, I will check asap

**Comment by dylanstrategie** [comment]
Oh wait, a windoor. Right, I'll give it a look if no-one else does, but it'll most likely end up into a code rework
