### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) [Ghetto Chem]

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5100]
> Revision 27295b13dc8f12c774720dedb2faee2b8b084e5f 
> Electrolyzer's don't accept coffee cups

**Comment by Kurfursten** [comment]
Not a bug

**Comment by Kurfursten** [comment]
This isn't an oversight, this was intentional. The electrolyzer has a list inside of it that explicitly defines what can be used with it.

**Comment by FudgePucker** [comment]
What would be the balance of allowing something besides bottles and beakers in it?
