### ISSUE TITLE
Allow the AI core to be pushed

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#5107]
As of now, placing an AI into its core location is a hassle, not many people know that you have to pull and click around to shift it into place properly. I think it would be best if it were allowed to be just pushed into place instead of pull trickery.

EDIT: Picture very related.
![ohgodkillme](https://cloud.githubusercontent.com/assets/6224074/8315034/91c64592-19bb-11e5-9c4a-53e6e864c108.png)

**Comment by Ephx1** [comment]
Closing feature requests

**Comment by PJB3005** [comment]
Why are you closing feature requests.

If you're doing it to JUST get out of the freeze then that's just cheating.

You know we can filter on issues EXCEPT feature requests, right?

**Comment by Ephx1** [comment]
Hey they said it was a good idea, besides, absolutely no one will ever do this because it's a minor inconvenience solved by being smart.
The other two, I think one is just flat out false, and the other is also one that no one will ever look at.

**Comment by Ephx1** [comment]
Nah fuck this, it's dumb as hell.

**Comment by PsiOmegaDelta** [comment]
Assuming the code bases still are somewhat similar, simply add `|CANPUSH` here.
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/silicon/ai/ai.dm#L21
