### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Telesci shield gens don't have req_access set to 55 instead of 0

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5110]
>Revision 70a954d31ad5ca0aa1b5a41e116f29ffa4957a97 
Can't unlock the telesci shield gens as a scientist on taxistation.

**Comment by ComicIronic** [comment]
Who makes these detailed anonymous reports?

**Comment by Probe1** [comment]
Good momey on a debug mommi
