### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Plasmamen speech gimmick

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5111]
>Revision 70a954d31ad5ca0aa1b5a41e116f29ffa4957a97 

>General description of the issue
It's-s-s-s-s-s-s-s-s s-s-s-s-s-s-shit let's-s-s-s-s-s-s-s- face it. It's-s-s-s-s-s-s-s annoying for both the plas-s-s-s-s-s-s-s-smamen an the people who are hearing it

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by 9600bauds** [comment]
Agreed honestly, it's-s-s-s-s-s-s-s s-s-s-s-s-s-s-shit.

**Comment by Ephx1** [comment]
S-s-s-s-stop oppres-s-s-s-s-sing me

**Comment by Shadowmech88** [comment]
What if instead of the hissing, every time a plasmaman talked they had a chance to also scream, both audibly and in chat?
The audible screaming would continue for several seconds, and cause any plasmamen nearby to begin screaming as well.

**Comment by ComicIronic** [comment]
>all screaming, all the time
>plasmen spamming speaking to scream

No.

**Comment by NigglyWiggly** [comment]
>The audible screaming would continue for several seconds, and cause any plasmamen nearby to begin screaming as well.

Please god I want this so bad now

**Comment by Intigracy** [comment]
Did this ever get changed? I haven't seen s-s-s-s-s spam lately.

**Comment by NigglyWiggly** [comment]
Unfortunately not
