### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Got a Boo! Spell form fucking around with genetics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5112]
>Revision (Should be above if you're viewing this from ingame!)
70a954d31ad5ca0aa1b5a41e116f29ffa4957a97 

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by ComicIronic** [comment]
Great, very helpful.
This is so informative for what might help me test this bug.

**Comment by clusterfack** [comment]
Fixed in one of my obj/screen PRs
