### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Wrong usage of Have in the cocoon.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5114]
>Revision (Should be above if you're viewing this from ingame!)
70a954d31ad5ca0aa1b5a41e116f29ffa4957a97

>General description of the issue
Wrong use of have/has.

>What you expected to happen
It should have said, "The cocoon has been,"

>What actually happened
It said;
The cocoon have been diced with the claymore by Salvatore Risso.

>Steps to reproduce if possible
Hit a cocoon with something.

**Comment by Exxion** [comment]
I am definitely not an authority on BYOND text macros, but maybe it's some kind of [src] vs. [src.name] fuckery
That or someone set the gender to plural when it shouldn't be.

**Comment by 9600bauds** [comment]
Commenting to fix later
