### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Metaclub cargo mail

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5116]
>Revision (Should be above if you're viewing this from ingame!)
206d4433700d08cd52e6c4ac5b3cf2ff37b1f0cf 

>General description of the issue
Metaclub disposal pipes at brig make you stuck. Sent two crates and later myself to engineering

>What you expected to happen
Getting to engineering through cargo mail system

>What actually happened
Stuck in a two-tile loop

>Steps to reproduce if possible
Send yourself to engineering through cargo (and probably any other location, needs testing)

**Comment by Jorister** [comment]
![dem pipes](https://cloud.githubusercontent.com/assets/12684020/8338044/1958ad64-1ab7-11e5-851c-0ec9c717e0e9.png)
Pipes in question
