### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Dissapearing pumpkins

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5117]
>Revision (Should be above if you're viewing this from ingame!)
206d4433700d08cd52e6c4ac5b3cf2ff37b1f0cf

>General description of the issue
Carving a deep fried pumpkin causes it to dissapear.

>What you expected to happen
a deep fried pumpkin that was also carved.

>What actually happened
apon using the knife on the deep fried pumpkin, it dissapears.

>Steps to reproduce if possible
1. Deep fry a pumpkin in the deep fryer.
2. Carve it with the kitchen knife.

**Comment by clusterfack** [comment]
Unable to reproduce
