### ISSUE TITLE
Who fucked with the cable code!

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#5119]
So when Alt clicking the floor and clicking a cable knot with some coils just stacks them in one spot.
![what did you do](https://cloud.githubusercontent.com/assets/10268342/8341883/d724d324-1a8d-11e5-9630-b81cd72172aa.PNG)

not only that can't do "continuous" wire.(click a wire and puts knot under you etc) all you get There's already a cable at that position when there no cable under you.

This what should be happening 
![cable stuff](https://cloud.githubusercontent.com/assets/10268342/8341897/f1f0807c-1a8d-11e5-8757-4e0a157dfd1a.gif)

What we get is that hunk of shit up top

**Comment by ComicIronic** [comment]
Kurfurst breaks everything.

**Comment by FudgePucker** [comment]
|>wireing to grid the long way instead of the short way so they don't check for it
I see what you did ther

**Comment by Probe1** [comment]
Hotfix soon please

**Comment by AutismSpider** [comment]
Fudge i even do that as antag engi tech.

Got get that crazy power out put for muh power gloves zap

**Comment by FudgePucker** [comment]
I know, you even did it as non malf MoMMI in the image.
POWER'S ALL THAT MATERS BABY.

**Comment by AutismSpider** [comment]
SMES are gay load all the power into main power line.

**Comment by NigglyWiggly** [comment]
>Those windows

How old is that .gif mang

**Comment by AutismSpider** [comment]
goon old this is when hive bots were a icon for engi borgs and other fun stuff.

**Comment by Kurfursten** [comment]
@ComicIronic
>Breaks everything
This isn't nearly as bad as gas datums

@AutismSpider 
I overloaded turf_place with an extra variable, which is normally a good thing, but I must've reversed the directional variable for placement by mistake, it's an easy hotfix

**Comment by Kurfursten** [comment]
Unable to produce on local, able to reproduce on live. All tests conducted on attackby with cables in hand

**CASE 1**
Dir 1 = 0
Dir 2 = Direction of player (opposite player.dir)
Description: This is a knot node, where one piece smoothly faces the player.

LOCAL: Attackby causes new node to appear in player's tile (Dir 1 = 0, Dir 2 = player.dir) -- THIS IS IDEAL, AKA "continuous wire"
LIVE: Attackby causes new node to move in the CABLE NODE'S tile (Dir 1 = 0, Dir 2 = player.dir)

VERDICT: Live issue

**CASE 2**
Dir 1 = player.dir
Dir 2 = Direction of player (opposite player.dir)
Description: This a power cable segment which forms a straight line

LOCAL: Attackby causes new node to appear in player's tile (Dir 1 = 0, Dir 2 = player.dir) -- THIS IS IDEAL, AKA "continuous wire"
LIVE: Attackby causes new node to move in the CABLE SEGMENT'S tile (Dir 1 = 0, Dir 2 = player.dir)

VERDICT: Live issue

**CASE  3**
Dir 1 = 1 (SOUTH)
Dir 2 = Direction of player (opposite player.dir)
Description: This is a smooth curve which faces the player and south; use for example

LOCAL: Attackby causes new node to appear in player's tile (Dir 1 = 0, Dir 2 = player.dir) -- THIS IS IDEAL, AKA "continuous wire"
LIVE: Attackby causes new node to move in the CABLE SEGMENT'S tile (Dir 1 = 0, Dir 2 = player.dir)

VERDICT: Live issue

**CASE  4**
Dir 1 = 0
Dir 2 = 1 (SOUTH)
Description: This is a knot node which faces SOUTH, when SOUTH is understood to not be the direction the player is standing in. This is applicable to anything except case 1

LOCAL: Attackby causes a smooth wire to appear pointing toward the player - this is ideal behavior, cable join
LIVE: Attackby causes a smooth wire to appear pointing toward the player - this is ideal behavior, cable join

VERDICT: No bug
