### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Whiskey bottles are empty

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5120]
>Revision (Should be above if you're viewing this from ingame!)
615d402edc2f2fac55992f903250517c85edea6a 

>General description of the issue
Whiskey bottles, when dispensed, are empty. There are no contents.
Might be the case for other bar bottles as well.

>What you expected to happen
Bottles of whiskey with whiskey in them.

>What actually happened
Bottles of whiskey with no whiskey in them.

>Steps to reproduce if possible
Dispense whiskey from the cargo machine or bar machines.

**Comment by dylanstrategie** [comment]
Most likely forgot to add contents on New(), but it's likely an isolated case because Bartenders tend to do fine otherwise

**Comment by dylanstrategie** [comment]
Nevermind, it's dispensing contents on New()

Please do more investigation on this, notably to see if other bottles do this

**Comment by Probe1** [comment]
THEY'RE ALL EMPTY

EVERYTHINGS EMPTY.
