### ISSUE TITLE
You can hold paper bins with no hands

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#5121]
Dragging a paper bin onto your character will put it in your hand, even if it's gone

![](http://puu.sh/iCgYC/42617496b0.png)

**Comment by dylanstrategie** [comment]
Missing check somewhere

**Comment by PJB3005** [comment]
or shit oldcode that's hardcoded to hell and back and doesn't utilise the correct procs

**Comment by ComicIronic** [comment]
A henkehknehknehknehknek shitcode
