### ISSUE TITLE
Optical Meson Scanner toggle option

### ISSUE THREAD

**Issue by Mawootad** [d3athrow/vgstation13#5123]
Optical Meson Scanners can only be turned off by removing them, as the effect can get annoying when not needed it would be nice to have a hud toggle option similar to flashlights and oxygen masks.

**Comment by Probe1** [comment]
take them off then?

**Comment by PJB3005** [comment]
@Probe1, you can't if you're near the SME or something, being able to see muh fancy lights is nice

**Comment by dylanstrategie** [comment]
Turning the mesons off would still remove the protection

I'd be fine with turning them off with an action button, along with other active HUD items like Med, Sec and NVGs, but it should remove all their functionality full-stop (outside of Sec Sunglasses which should still be sunglasses)

**Comment by Exxion** [comment]
But... why?
Nobody would design a device that has both safety and utility systems and attach them to the same switch, so there's no reason for it to be that way for realism.
I can't think of any reason it would have to be that way for game balance, either.

**Comment by ComicIronic** [comment]
>Nobody would design a device that has both safety and utility systems and attach them to the same switch

You assume the safety isn't from the utility. Meson scanning bypassing typical vision is the exact reason meson scanners are the only way to watch stuff like the Singulo or the Supermatter.

**Comment by Exxion** [comment]
Presumably, the meson scanners have a special camera on the outside and a screen on the inside, like NVGs, etc. As long as they are on your face and not fried, you'd be bypassing normal vision. The ability to see station structures through walls would be more like a visual filter than something necessary for the device's function all the time.
I *guess* you could say that the camera mounted on the scanners is meson vision only and turning off the meson vision would require flipping the scanners up or something, but that would make no sense from a design standpoint, given how cheap standard visual-light cameras are.

**Comment by FudgePucker** [comment]
Being able to appreciate the light produced from the SME without tripping balls as a carbon would be nice.

**Comment by Probe1** [comment]
look at it through a camera console then.  you can't really have it both ways.  it's either on and protects you or its off and doesn't protect you.

**Comment by Kurfursten** [comment]
This was filled @PJB3005 close
