### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) medbay door buttons

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5129]
>Revision 271ee545e5885b206bd72b823a9a6cab3638b9f0

>General description of the issue
Medbat buttons are no longer in the right place.  I blame dylan.

>What you expected to happen
Mapping not to get fucked up

>What actually happened

Got fucked up
>Steps to reproduce if possible

Load box station

**Comment by PJB3005** [comment]
> I blame dylan.

henkehnekhekene
