### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Suit Storage sprite never full

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5131]
>Revision (Should be above if you're viewing this from ingame!)
d07511d04db77d06fbdb7c2e1ec9d718ed63c8bc 

>General description of the issue
The suit storage unit, when opened, always appears empty even when all compartments are full

>What you expected to happen
There were sprites for the suit and helmet at least before, when the unit was open and those things were not yet taken out

>What actually happened
The storage unit always appears empty when open

>Steps to reproduce if possible
open full Suit Storage Unit

**Comment by Probe1** [comment]
been fucked for about 3 months now
