### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Can no longer click on power cable ends to extend them to the next tile

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5135]
>Revision (Should be above if you're viewing this from ingame!)
d07511d04db77d06fbdb7c2e1ec9d718ed63c8bc

>General description of the issue
Clicking a cable on a segment that does not end in a knot while on the tile it leads to no longer extends it to the tile it leads to which you are on, causing great inconvenience when laying wire by hand
Instead, the cable is added as if you were not clicking on the leading cable at all

>What you expected to happen
previously, when you clicked a cable end that did not end in a knot, and which faced toward you on an adjacent tile, the cable would be extended to the adjacent tile you are on
[U ][--] before click
[Uo-][--] after click
U being your character and o representing a cable knot

>What actually happened
The cable is now placed as if you were not clicking on the already-laid cable at all, and instead like you were clicking on the empty part of the tile
[u ][--] before click
[u ][-o-] after click

again causing cable to be lain in a place it already had been as if you were not clicking the cable end at all

this results in laying cable by hand being far more tedious

>Steps to reproduce if possible
cable does not end in knot but ends connecting to an adjacent tile
stand on that adjacent tile and click the cable end
the cable is not conveniently extended to a knot on your adjacent tile, but another segment is laid on top of the 
cable on tile you clicked as if you did not click the cable

**Comment by clusterfack** [comment]
Just fixed
