### ISSUE TITLE
Hanging lanterns can only face south

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#5137]
Dylan what the fuck man
There doesn't even have to be a wall there it just appears to the south of you for no goddamn reason

**Comment by ComicIronic** [comment]
Is this the hook or the resulting lantern?

**Comment by NigglyWiggly** [comment]
Both.
The hook always goes south, and you can varedit it to face another direction, but when you put a lantern on it, it resets back to being south
