### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Can no longer eject self from cryo cell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5138]
>Revision (Should be above if you're viewing this from ingame!)
2d465966417c9203b8fafb8b677fa6f6213fa9aa 

>General description of the issue
eject occupant no longer shows a countdown message or ejects you when in the cryo cell

>What you expected to happen
some kind of message for a countdown and eventual ejection from the cryo cell when inside

>What actually happened
nothing, and you're stuck in the cell

>Steps to reproduce if possible
put self in cryo cell, try to get out susing eject occupant, resist, or toggle open

**Comment by Kurfursten** [comment]
Unable to reproduce on live

Got message and successfully ejected
