### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Autolathe eats multitool

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5140]
>Revision
8cbc8772267242aa6dbef089773c2a0e2c3eb45e

>General description of the issue
Autolathe eats multitool after using the config menu

>What you expected to happen
Not that

>What actually happened
That

>Steps to reproduce if possible
Click autolathe with multitool

**Comment by Probe1** [comment]
it was never a feature.  use your empty hand.

**Comment by ComicIronic** [comment]
It was a feature after someone reported this same thing a small while ago, and I made the autolathe not eat the multitool.

**Comment by Probe1** [comment]
neat.

**Comment by PJB3005** [comment]
uh, why isn't this closed then?

**Comment by Probe1** [comment]
definitely should be, it's not eating multi tools.
