### ISSUE TITLE
Have turrets inherit weapon projectiles

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#5141]
The way they're set up now, inserting an energy weapon such as a plasma weapon just defaults it to stun weaponry.

**Comment by Exxion** [comment]
Now usually when I say this, I turn out to be exceptionally wrong, but that sounds like a pretty easy fix
Easy enough that I have to wonder why they weren't set up that way in the first place

**Comment by Konater** [comment]
staff of change turrets soon
