### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) There's an area named "Derlict Gasminer acess"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5146]
>Revision (Should be above if you're viewing this from ingame!)
8cbc8772267242aa6dbef089773c2a0e2c3eb45e

>General description of the issue
http://puu.sh/iDmnM/7b96117708.png

>What you expected to happen
Derelict gas miner access

>What actually happened
derlict gasminer acess hur dur

>Steps to reproduce if possible

**Comment by PJB3005** [comment]
I'm gonna be *that guy* and say some MoMMI made an area in game and fucked up the name

**Comment by PJB3005** [comment]
A quick git grep through the repo came up with nothing

**Comment by ComicIronic** [comment]
Henk henk henk
