### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Ghost edditing computers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5148]
>Revision (Should be above if you're viewing this from ingame!)
6b63a2286c331945cecd82cbd81c491c773127b7

>General description of the issue
ghost can edit atmos automations computers

>What you expected to happen
Ghost couldnt access computer

>What actually happened
I can access and edit variables on the computer

>Steps to reproduce if possible
Prevent this from happening

**Comment by PJB3005** [comment]
shit sanity in a few of the automations, should be an easy fix.

>Steps to reproduce if possible
Prevent this from happening

kek

**Comment by FudgePucker** [comment]
Oh god why?
Why not just tell pomf that this shit is broken?
Now ghosts will abuse the AAC to do shit like turn off injectors.
