### ISSUE TITLE
Hair selection arrows are bugged

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#5152]
Using the hair selection arrows can have some strange effects.

Go to the "Fujuyabashi" hairstyle as a female then click the right arrow a few times, you'll be able to select skrell hairstyles.

![sdfsdf](https://cloud.githubusercontent.com/assets/13045735/8389817/43f949b6-1c2e-11e5-8ec2-7fe745612fd4.jpg)

**Comment by Intigracy** [comment]
When you go ingame, if the hairstyle isn't of your race then it won't give it to you.

Can also be done by switching to gray and then using the arrows (only one direction, switching directions resets you until you switch back and forth on species) to get human hairs.
