### ISSUE TITLE
Cannot edit mutantrace icons

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#5153]
Specifically the golem icon. I wanted to change how a golem looked by changing their icon, and when I went into the mutantrace overlays variables, I changed the .dmi to my own, and nothing happened.
The .dmi was changed and all, and it even showed the right icon on the top left, but no change ingame at all, no matter what we did.

**Comment by Intigracy** [comment]
Did you try changing its icon variable?

**Comment by Intigracy** [comment]
wow you never answered my question

**Comment by NigglyWiggly** [comment]
Yes, Inti.
Yes I did.

**Comment by Intigracy** [comment]
You said you changed the mutantrace overlay icon.

I mean did you change the mob's icon variable without going into overlays.

**Comment by Zth--** [comment]
_9 months later..._

**Comment by Intigracy** [comment]
Will fix this and #4331 sometime this week.

**Comment by Shadowmech88** [comment]
This can be closed since golems are no longer mutantraces, and now follow the same rules as every other race regarding icon changing.
