### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Darkness while wearing Optical Meson Scanner

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5162]
Revision: ba9a98637814a402d1e4bcf4d3978d41aab81455

>Can see darkness while wearing Optical Meson Scanner. (I was a vampire at the time)

>To not see darkness

>I could see both light and dark squares though I could see all the object behind as per normal.

>Not sure, might have to do with being a vampire.

**Comment by PJB3005** [comment]
visibility flag, life code, IT ALL NEEDS TO BE TORN UP AND KILLED

**Comment by clusterfack** [comment]
It's not a bug you have xray vision, of course you can see darkness. The only reason meson vision doesn't show you darkness is because it doesn't show objects. And if we were to TRY to fix that (I don't think we should) we'd run into a big ole t-thanks byond.
