### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) AMR Doesn't explode when pulled appart by sing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5172]
>Revision (Should be above if you're viewing this from ingame!)
cf24a5bc1d4626513d98157fd6cbbe81d3b4d22f

>General description of the issue
When pulled appart by the singularity passing near the AMR seperated into seperate chunks that did nothing.

>What you expected to happen
AMR to explode like it does if you give it too much antimatter.

>What actually happened
Nothing, it just got pulled appart.

>Steps to reproduce if possible
Build AMR (in this case 8 core), have 9x9 sing fly pass and have a near miss.

**Comment by bloxgate** [comment]
Whoops, appear to have posted this twice due to a UI bug in game. Sorry.
