### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Toxins wiring

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5175]
>Revision cf24a5bc1d4626513d98157fd6cbbe81d3b4d22f 

>General description of the issue

Looks as though the wiring to toxins is screwed up and the power is off

>What you expected to happen
Power to work properly

>What actually happened
Toxins is dark and without power and lighting

>Steps to reproduce if possible
Happens every single round so far as I have seen, just launch a round and it should be there

**Comment by therealbenny** [comment]
ah sorry didn't know. Thanks for looking though
