### ISSUE TITLE
Info for Mappers

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#5177]
I assume this means something for mappers, information from box station map camera debugging
![](http://puu.sh/iFAAs/e87478e86b.png)
![](http://puu.sh/iFABy/22347e44be.png)

**Comment by dylanstrategie** [comment]
This does mean something, indeed. Some of those are intentional though, I'll run though them

**Comment by dylanstrategie** [comment]
The complaints about overlapping cameras and networks are mostly incorrect, but the rest indeeds next to be checked, I'll bundle it in my current map PR
