### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Lantern hooks don't stick to the wall they're placed on.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5179]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Once you create a hook, and place it on a wall, it doesn't go flush with the wall, and defaults to facing north.

>What you expected to happen
The hook to actually go on the wall

>What actually happened
It defaulted to facing north, see pic related http://i.imgur.com/9NTcblr.png

>Steps to reproduce if possible
Create a hook, place it on a wall, not sure if it matters if it's an Rwall or not.

**Comment by PJB3005** [comment]
Fixed in #5126
