### ISSUE TITLE
Box dorms wire missing.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5180]
A mapper in their infinite wisdom deleted a wire under a door to the dorms apc.  It isolates the dorms from the net.

![ss 2015-06-28 at 10 04 58](https://cloud.githubusercontent.com/assets/8550416/8396664/49fbe09e-1d7d-11e5-944f-4b5da95ccc15.png)

**Comment by FudgePucker** [comment]
SO THATS WHY DORMS HAD POWER ALARMS WITH A GIGA WATT OF POWER IN GRID!

**Comment by clusterfack** [comment]
What is with these motherfucking wires
