### ISSUE TITLE
Flashlights may be a little fucked up.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5186]
http://puu.sh/iGmsF/a240e32fc2.webm

It illuminates where you turned the light on..

..and continues to illuminate that place until you move through a door or toggle off/on the flashlight again.

**Comment by Probe1** [comment]
- pomf could not replicate it in testing.

**Comment by Kurfursten** [comment]
@Probe1 I've seen this myself, I believe it's related to the janicart because that's how I reproduced it

**Comment by PJB3005** [comment]
lack of forceMove() in vehicle code, easy fix.

**Comment by Probe1** [comment]
[5186] resolved it.
