### ISSUE TITLE
infinite loop caused by emitter beams crashing the serb with no survivors

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#5194]
>runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
>To avoid this safety check, set world.loop_checks=0.
>proc name: Destroy (/obj/effect/beam/Destroy)
>runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
>To avoid this safety check, set world.loop_checks=0.
>proc name: 
>runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
>To avoid this safety check, set world.loop_checks=0.
>proc name: New (/event/New)
>runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
>To avoid this safety check, set world.loop_checks=0.
>proc name: Destroy (/obj/effect/beam/Destroy)
>runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
>To avoid this safety check, set world.loop_checks=0.
>proc name: Destroy (/obj/effect/beam/Destroy)
>runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
>To avoid this safety check, set world.loop_checks=0.
>proc name: 
>Shutting down after encountering too many critical errors
>runtime error: Maximum recursion level reached (perhaps there is an infinite loop)
>To avoid this safety check, set world.loop_checks=0.
>proc name: New (/event/New)
>Shutting down after encountering too many critical errors

unable to reproduce so far

**Comment by dylanstrategie** [comment]
I know how it's done, but I have no idea how to fix it

**Comment by Unfit** [comment]
Can you please share? Maybe I'll think of something

**Comment by dylanstrategie** [comment]
Alright, for your eyes only or something : 

- Have two prisms face each other, feed an emitter beam into the contraption
- Turn the emitter off, you should be getting a beam between the two prisms
- Unwrench and move the prism that wasn't getting the emitter feed, the beam should now extend
- Shove the prism back into the ghost beam

Your server should now crash due to infinite looping
