### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Bar Changes Destroy Meteor Mode Even Worse

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5195]
>Revision (Should be above if you're viewing this from ingame!)
49ef86201cbc74a1fcfa0ec9eca6b8f2c7f4c15b

>General description of the issue
Since the rearrangement of the Bar, Meteor Mode has not been updated to properly spawn supplies there.

>What you expected to happen
Plasma glass, suits, oxygen tanks, etc should spawn in Bar upon announcement of meteors incoming during the Meteor Mode

>What actually happened
The supplies failed to appear

>Steps to reproduce if possible
Set server to Meteor mode, wait until automated announcement, view bar

**Comment by dylanstrategie** [comment]
Blame whoever retooled the Bar for wiping the board with Meteors spawn points

I'll likely get to it, but it's not urgent compared to literally anything else I could do with the map, given that Meteors is basically never coming back live unless I managed to do something good with it

**Comment by FudgePucker** [comment]
Maybe make Meteors a very short and violent round.
With out warning a giant meteor wave hits the station (or also have a random chance of it being two of those poles that destroy everything in their path or someshit.) pretty much the entire exterior of the station is destroyed, no warning, about 5 or 10 mins into the round (enough time that people will let their guard down but short enough for it to not feel like extended.).
Command sends a message saying pretty much 'Oh fuck, you were in a black area on our radars, fuck tons of more waves are coming, we are sending a shuttle but it will take a little longer this time, we have teleported supplys to bar, good luck', and then the crew has to survive for 15 mins as the station is fucked sideways by the rocks, some people will become survivers to make it intresting, and the station is fucked sideways.

This prevents people from metagaming by turtling in AI core and just waiting it out, everything gets fucked super fast. And even if you get removed from the round/have a bad time, it only lasts half an hour.

**Comment by dylanstrategie** [comment]
I think hitting hard and finishing the round quickly is really the best outcome for the gamemode, but there still needs to be some time for the crew to set up defenses

My guess would be an extremely early warning (most likely around the time the crew manifest appears) and a 5-10 minutes window to build. But that's mostly theorical

If explosions are well optimized, I can likely crank up the meteor count to insane levels to do damage quickly

**Comment by clusterfack** [comment]
I'm still waiting on ghosts having a launch meteor spell. The mode needs real antagonists to feel fun.

**Comment by d3athrow** [comment]
Closed by request of @dylanstrategie

**Comment by dylanstrategie** [comment]
For clarification, this was fixed by #5974
