### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Missing wires in Toxins mixing room

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5196]
>Revision (Should be above if you're viewing this from ingame!)

Revision: 71b0b35fca55a99b25fd3a8858fe7af16b79fcbd 
>General description of the issue

http://puu.sh/iHJIj/7690154b5b.png

>What you expected to happen

A wire to spawn there

>What actually happened

NO WIRE!

>Steps to reproduce if possible

Just remove the tile and it's not there

**Comment by clusterfack** [comment]
Dupe #5175
