### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Can't get up after being stunned

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5200]
>General description of the issue
After getting stunned on the firebird I could never get up

>What you expected to happen
after outrobusting sec being able to get back to my sweet sweet ride

>What actually happened
But then I never go up like as if I had no limbs

>Steps to reproduce if possible
Get stunned on a firebird I guess

**Comment by PJB3005** [comment]
rest maybe?
