### ISSUE TITLE
Process Scheduler Freezes

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#5204]
The process scheduler has frozen on two occasions now, the first incident took place yesterday iirc. I really have no idea what causes it, it merely stops its processing. Debugging it I've seen the datums it is processing at the current time don't change.

Since this is the second incident that I've personally seen I'm going to make this report to keep track of timing of this. It will be trouble if it keeps occurring.

**Comment by 9600bauds** [comment]
Wasn't this the thing with the shuttles
