### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Can no longer multitool the supply shuttle console circuit board for the contraband crate.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5210]
>Revision c2df591938fe1995e2088360906d76489aab04b6 

Normally you deconstruct the supply shuttle console to get the circuit board out then you use a multitool on it. This brings up a menu where you select standard/broad spectrum. Broad spectrum unlocks the contraband crate.

Something happened and now when you multitool it the menu is no longer brought up.

**Comment by Unfit** [comment]
Not a bug
Use a soldering iron

**Comment by Probe1** [comment]
Was the wiki updated?

**Comment by PJB3005** [comment]
probably not
