### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Stools in Boxstation locker room/ Weapon stools are broken?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5211]
Rather than being the usual structure/stools like in the bar, they are the weapon/stools, which means you can't sit on them nor deconstruct them.

Part 2 is that Weapon stools appear to be a bit bugged, when setting them back down by clicking on them in-hand, they disappear entirely rather than be set back down, not sure if this is an oversight or a genuine bug.

>How to reproduce

Go to Boxstation locker room, and try to sit on a stool.

Pick up said stool, and try to put it back down.

**Comment by dylanstrategie** [comment]
A better question would likely be, why are there are stool objects in the locker room instead of regular stools
