### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) "implantpad" lets you add an implant to it, but not remove

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5212]
>Revision (Should be above if you're viewing this from ingame!)
c2df591938fe1995e2088360906d76489aab04b6

>General description of the issue
the implantpad modification thing in the tracking implant box that lets you modify tracking implant id's doesn't let you actually remove the implant (that I can see) from the pad, whether through a verb, clicking it with the syringe thing, or clicking it in hand.

>What you expected to happen
be able to remove implant once put in

>What actually happened
it fuckin ate my implant man

>Steps to reproduce if possible
really need this info?

**Comment by dylanstrategie** [comment]
Snowflake that was never finished

**Comment by Intigracy** [comment]
I tested, you can remove it by clicking it with your other hand.
