### ISSUE TITLE
(WEB REPORT BY: Anonymous REMOTE: ) Ckey field on ingame issue reporter doesn't appear until after you already click submit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5216]
>Revision (Should be above if you're viewing this from ingame!)
c2df591938fe1995e2088360906d76489aab04b6

>General description of the issue
http://puu.sh/iKV6A/cc36ee1460.png

>What you expected to happen
you to see my sexy name

>What actually happened
you didn't ;_;

>Steps to reproduce if possible
open bugreporter

**Comment by Intigracy** [comment]
![](http://puu.sh/iKVag/5490887544.png)
