### ISSUE TITLE
(WEB REPORT BY: 13gome0220 REMOTE: 198.245.63.50:7777) Device Analyzers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5220]
>The Device Analyzers broke after a while and PDA Device Analyzer broke after scanning a few items. Which can't be put in Reverse Engine. I scanned the Intelicard and AI Reset module.

**Comment by 9600bauds** [comment]
Was caused by some hubbub about designs that could be made in other fabricators, whatever I fixed it
