### ISSUE TITLE
(WEB REPORT BY: corncolonel REMOTE: 198.245.63.50:7777) Coin removal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5224]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Cannot remove coins from a coin bag

>What you expected to happen
Able to remove individual coins from a bag when after clicking it

>What actually happened
Just shows total money value in bag with no option to take out coins

>Steps to reproduce if possible
Print coins into bag, click bag,

**Comment by Probe1** [comment]
duplicate? https://github.com/d3athrow/vgstation13/issues/5199
