### ISSUE TITLE
(WEB REPORT BY: corncolonel REMOTE: 198.245.63.50:7777) Clown cart bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5225]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
When driving over a banana peel with a clown cart, the pilot is slipped and falls off the cart thus preventing high speed clown shenanigans

>What you expected to happen
Drive over the peel with no problem

>What actually happened
Drove over a peel, and slipped on it despite being in the cart

>Steps to reproduce if possible
1: Drive clown cart over peel 2: ?????3: slip

**Comment by ComicIronic** [comment]
Entered calls Crossed.

**Comment by ComicIronic** [comment]
I'll have a look at a fix for this that edits walking().
