### ISSUE TITLE
Water-Coolers can't be deconstructed

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5227]
lack deconstruction code

all hail our watercooler walls, they're the hardest you've ever seen.

**Comment by Probe1** [comment]
its an oversight not a feature request.  you can construct them and they require bombs to remove.

**Comment by ComicIronic** [comment]
It's a feature request, because it's not the failure of interaction with a system.

One could push to call it an oversight, but I feel that's redundant tagging.

**Comment by Probe1** [comment]
it was added as a constructible object and proper deconstruction datums were not added.

**Comment by IratePirate** [comment]
Is this going to be the photocopier/Malf AI murder tool all over again?

**Comment by Probe1** [comment]
nah kurfurst will fix it shortly he's a good man.
