### ISSUE TITLE
(WEB REPORT BY: fatbaldbastard REMOTE: 198.245.63.50:7777) Bolas don't fly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5229]
>Revision: 2e0b4240143faa181025c3de5f87d85e600cecb6 

>When thrown, bolas land on the same tile as the person throwing them.

>Bolas to fly onward, preferably in the direction of another spessman.

>They drop under your feet, do not fly.

>1) Take bolas 2) Press Throw icon on your HUD 3) Click somewhere in the distance 4) ??? 5)Video games

**Comment by Intigracy** [comment]
Can confirm, was having this issue yesterday.

**Comment by ComicIronic** [comment]
Pomf ruins everything, more at 10.

**Comment by Intigracy** [comment]
Pomf fixed this.
