### ISSUE TITLE
(WEB REPORT BY: intigracy REMOTE: 198.245.63.50:7777) Putting something in a bandolier (equipped) opens it on top of your bag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5230]
> Revision (Should be above if you're viewing this from ingame!)
> 2e0b4240143faa181025c3de5f87d85e600cecb6
> 
> General description of the issue
> http://puu.sh/iMcvr/ec91b7a714.jpg
> 
> What you expected to happen
> To be able to easily move my shells from my bag to my bando
> 
> What actually happened
> I have some fucking two inventory shit and have my shells overlayed on one another
> 
> Steps to reproduce if possible
> put on bandolier
> open bag
> grab shell
> put in bandolier

**Comment by PJB3005** [comment]
Tested, can confirm this happens

**Comment by 9600bauds** [comment]
No longer happens since the bandolier rewrite
