### ISSUE TITLE
PDA based device analyzer breaks the reverse engine

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5231]
I scanned a number of designs with the pda, and then with a normal device analyzer until they were full from tech storage.
I then went to the reverse engine and used the pda on it. I got "   The device analyzer flashes a message on-screen: "Too many designs loaded."
Sucessfully transferred 0 designs."

And only the circuit board "station alerts" got transferred into the reverse engine.

From then on, using the pda or using the normal device analyzers only gives me  "Successfully transferred 0 designs." and won't let me upload any more besides that one.

Edit: I deconned and reconstructed the reverse engine, then tried loading designs off of a full normal device analyzer. 
Sucessfully transferred 0 designs.
then made sure by trying to scan something with it,
   The device analyzer flashes a message on-screen: "Too many designs loaded."
and then
Sucessfully transferred 0 designs.

Nope.

Edit 2: For some reason I'm able to scan in the RCL, but I can't load a print or a nanoprint into the fabricator. It just doesn't give a message or register that I'm trying to do it.

**Comment by Probe1** [comment]
Oddly enough I think I came in that same round after you.  The device analyzer said it was full of designs and could not scan anything more but the reverse engine would not accept any of them.

However. I used my PDA with the DA Mode toggled on and successfully scanned the compressed matter cartridge, printed it and loaded it into the general fabricator.

**Comment by Midaychi** [comment]
Yeah. I found out that some designs would work but most wouldn't. Maybe it uses a list to track what was scanned and I somehow accidentally filled that list with junk without actually uploading anything?

**Comment by PJB3005** [comment]
My best guess (never looked at the code though) is that some list is getting polluted with shit and then runtimes happen every time something else happens on the engine.

**Comment by Exxion** [comment]
It may or may not be worth noting that, at least last time I checked (which was quite a while ago), the reverse engine itself can be scanned with the standalone device analyzer but *not* the PDA one

**Comment by clusterfack** [comment]
Marked unable to reproduce and no one has contested this yet
