### ISSUE TITLE
You can only load 7 components into a RMCE by hand

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5233]
[bug]

They hold 21 if loaded with a gadget bag.  They hold 7 when inserted manually.  Says its full when it has more than 7  components in it and you use your hand but will load normally if a gadget bag is used.

[aside] 

it's still clunky AS FUCK to use.  It should hold twice as many parts, the unnecessary UI with the unnecessary wait times for it to work should be redone, and the readouts are almost junk since they consider console screens to be tier 1 so whatever the reading at the end, it's often times erroneous.  If I had made it, I would have made it automatically tell you the existing components when you first insert it instead of making it an extra button.  Just all around clunk.

**Comment by Shadowmech88** [comment]
I'm still not convinced that it's even faster than using just a gadget bag, overall, when you factor in having to manually empty it and the fact that it replaces the parts slower than you can put them in by hand.
It definitely needs a buff.

**Comment by Iamgoofball** [comment]
Replace with /tg/ RPED when?

**Comment by PJB3005** [comment]
#4782 is my RPED PR.

Merge #4782 when

**Comment by Probe1** [comment]
its for the best.  the next issue was the RMCE inserts component parts INTO the microwave instead of swapping them out of the machine.  

tasty tasty microwaved phasic scanners.

**Comment by PJB3005** [comment]
@Probe1 blame microwave code.
