### ISSUE TITLE
(WEB REPORT BY: izayachan REMOTE: 198.245.63.50:7777) Monkeys can't heal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5234]
> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Monkeys can't be healed damage.Got stuck in low temperature
> What you expected to happen
> Recovery of toxin damage and for body temperature to rise
> 
> What actually happened
> I needed to become human to recover toxin damage and return to normal temperature
> 
> Steps to reproduce if possible
> Become a monkey and take toxin damage.
> Go into a function cryo and come out. The temperature won't go back up even if you go near a heater.

**Comment by 9600bauds** [comment]
Cannot reproduce, probably is caused by the thing with DD not working on monkeys and this guy tried to use DD (I made the same report pretty much)
