### ISSUE TITLE
(WEB REPORT BY: zushakon REMOTE: 198.245.63.50:7777) Wheelchair spawning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5241]
Revision: be5b4da7c8a2c971587d6d7d0c25b1fce5e6dd3c 

>If you round join or late join with no legs you get put in a wheelchair.
The wheelchair then sends you to the title screen area. You can't escape.

>To be able to spawn in a wheelchair with no legs on the station

>You spawn in the shuttle then get teleported to the holding area where you can't escape.

>Join round with no legs.

**Comment by clusterfack** [comment]
Fixed fully by https://github.com/d3athrow/vgstation13/commit/ae94302278ddd5314cc207d6d278361589866fbc
