### ISSUE TITLE
This slutty recycling machine just ate my materials

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5242]
Added 70 glass and 100 plasma sheets.

They disappeared but didn't show up on the screen and they are gooone.  Recyk - PRO THIEF 

![unique_nettle_monitor_iii_2015-07-04_22-18-00](https://cloud.githubusercontent.com/assets/8550416/8510050/a6ad61e2-229a-11e5-8ca9-b315871413fd.png)

**Comment by PJB3005** [comment]
I recall whilst testing #4285 that I had the same issue, I think the material for plasma sheets is "plasma" instead of "$plasma"

**Comment by Probe1** [comment]
Glass still is not counted.  Any glass that enters the Recyk PRO-1000 is not added to the count.

**Comment by PJB3005** [comment]
oh damnit, glass isn't in minerals.dm so I missed them
