### ISSUE TITLE
(WEB REPORT BY: drcelt REMOTE: 198.245.63.50:7777) The monkey (59) laugh

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5243]
>Revision (Should be above if you're viewing this from ingame!)
5f2992c55f7d4c42990bd14c0568380104b5b2f6

>General description of the issue

"The monkey (59) laugh"

>What you expected to happen

The monkey (59) laughs

>What actually happened

The monkey (59) laugh

>Steps to reproduce if possible

1.be a monkey
2.*laugh
OR
1.have a normal no-ckey monkey
2.gas it with n2o

**Comment by PJB3005** [comment]
This could be related to this issue:
When using emotes through say: "*X", using say say: *boop will be "MoMMI Boop", I assume this is because it's directly outputting that instead of the related emote, and if there isn't one still outputting it whilst it shouldn't

**Comment by ghost** [comment]
@gbasood this was fixed, pretty sure.

**Comment by ghost** [comment]
@gbasood damn it sood
