### ISSUE TITLE
(WEB REPORT BY: nukas REMOTE: 198.245.63.50:7777) Ghost Boo! Power after radiation storm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5247]
>Revision (Should be above if you're viewing this from ingame!)
61934f9a927a6d8b24b542255a0b7c550f29e70c 

>General description of the issue
After a radiation storm I got a bunch of disabilities and the CMO cured me by restoring the genetic crap and stuff. Now I have the ghost's Boo! power icon on the top right of my screen, but clicking it yields the message: You shouldn't have this spell! Something's wrong.

So basically it's harmless.

>What you expected to happen
Not to gain the ghost power?

>What actually happened
Gained the ghost power.

>Steps to reproduce if possible

**Comment by Probe1** [comment]
After a radiation storm I got a bunch of shit powers.  I took ryetalyn and the powers green box thing stayed there.  Later, after not being exposed to any radiation or any causes, I got Boo randomly

![widdershins_roost_nineteen_2015-07-18_11-41-29](https://cloud.githubusercontent.com/assets/8550416/8762567/eec603d4-2d4a-11e5-94c6-18d79a03fde6.png)

**Comment by PJB3005** [comment]
I can confirm this, got the exact same thing!

**Comment by Intigracy** [comment]
https://github.com/d3athrow/vgstation13/issues/5801#issuecomment-155459673 close
