### ISSUE TITLE
Washing shoes does nothing

### ISSUE THREAD

**Issue by chainsauce** [d3athrow/vgstation13#5249]
If you step in something and then try to wash your shoes, it only changes the sprite in your inventory and nothing else. Picture taken after washing it with shower, sink and washing machine. In addition, if you step in say a blood puddle, then instantly take your shoes off, wash them, and put them back on, your next steps will make bloody footprints still, so it's more than just the boots on your character not changing appearance.

Also, even if it was vomit you stepped in, it says blood stained. Haven't tested with other things like oil

![boots](https://cloud.githubusercontent.com/assets/6082418/8513231/d81084ae-232f-11e5-944c-d7b740b7bd41.png)

**Comment by ComicIronic** [comment]
Washing machines are awful.

**Comment by Exxion** [comment]
Yes, oil also counts as blood-stained
#4157
