### ISSUE TITLE
(WEB REPORT BY: banditsuit REMOTE: 198.245.63.50:7777) Cannot view security terminals from a wheelchair, possibly others

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5254]
Tried to access the advanced security cameras in sec on taxi and I can't use it

>What you expected to happen
For it to let me use the advanced security cameras

>What actually happened

>Steps to reproduce if possible

**Comment by ComicIronic** [comment]
restrained() has to be edited.

**Comment by 9600bauds** [comment]
Not restrained(), I believe it's the canmove check
