### ISSUE TITLE
(WEB REPORT BY: banditsuit REMOTE: 198.245.63.50:7777) Ability to grab while in wheelchair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5255]
> General description of the issue
> Inability to grab others while in wheelchair (not a bug perse but it makes being a handicapped sec officer a nightmare)
> 
> What you expected to happen
> Ability to drag people from a wheelchair
> 
> What actually happened
> Nothing
> 
> Steps to reproduce if possible
> Attempt to drag someone from a wheelchair

**Comment by clusterfack** [comment]
Uh, are they motor wheelchairs? Can you imagine a wheelchaired person dragging someone?

**Comment by PJB3005** [comment]
@clusterfack, don't think so because having less/full hands = lower speed
