### ISSUE TITLE
(WEB REPORT BY: banditsuit REMOTE: 198.245.63.50:7777) Cannot take items off of others from a wheelchair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5256]
>Revision (Should be above if you're viewing this from ingame!)
c8b370ba3ecb11bc2760ab27db3ad4e58be517c9

>General description of the issue
Inability to take items off of others from wheelchair

>What you expected to happen
Take items off of others from wheelchair

>What actually happened
The inability to do so

>Steps to reproduce if possible
Try to take items off of someone from a wheelchair

**Comment by gbasood** [comment]
Still a bug

**Comment by 9600bauds** [comment]
Same cause as #7153
