### ISSUE TITLE
Welder damage gave me the wrong HUD element

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5265]
I had mesons and just mesons on.  I welded a door open.  I went blind and weirdly enough it gave me a silicons o2 hud element.  Had it with me for the rest of the round.  Weirdest bug.

![scaredy_hangar_16_2015-07-06_05-55-45](https://cloud.githubusercontent.com/assets/8550416/8520836/1b217358-23ac-11e5-8e63-c3ed88d8b066.png)

**Comment by clusterfack** [comment]
Now that one is certainly interesting. Which screen element is that normally?

**Comment by Probe1** [comment]
That's the funny thing.  It is where the carbon oxygen meter should go but maint was pressurized and had normal air levels.  I should not have taken any oxygen damage to make the indicator appear.


Here's an added bonus from the 4th of July that I didn't report because it was too inexplicable.  An admin started up an ogg, I got a bit of lag on my end and before my client updated I walked myself into gibtonite and it was on its last cycle when I got my update from the server.  Boom.  Look at the top right, a second health hud.


![unique_nettle_monitor_iii_2015-07-04_22-36-23](https://cloud.githubusercontent.com/assets/8550416/8521070/48489954-23ae-11e5-8a91-96b15a88fafb.png)

**Comment by Probe1** [comment]
migrated to github

**Comment by Probe1** [comment]
Still present.  Note how you can see the critical hp hud element underneath the full health hud element

![communist_fortress_xx_2015-10-10_16-15-27](https://cloud.githubusercontent.com/assets/8550416/10413050/51e118d0-6f6a-11e5-8b37-fe6578b46401.png)

**Comment by Probe1** [comment]
Duplicate of https://github.com/d3athrow/vgstation13/issues/4738
