### ISSUE TITLE
People in Wheelchairs Can't Build Chairs or Beds

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5266]
"There is another chair here!"
Not sure if it's fixable or not, but I don't think it's intentional.

**Comment by Exxion** [comment]
Well yes. There is another chair there. The wheelchair.
It's probably fixable, but the question is if it should be fixed.

**Comment by Shadowmech88** [comment]
But wheelchairs, though technically chairs, serve more as vehicles than they do as furniture. You can also push wheelchairs around and can't move through them, whereas regular chairs are stationary and can be walked over. Wheelchairs, as far as their attributes go, are chairs in name only.
Plus I don't really see a reason balance-wise why people in wheelchairs shouldn't be allowed to build regular chairs.

**Comment by ComicIronic** [comment]
How would you put a chair under the chair you're on?

**Comment by Shadowmech88** [comment]
How would you build a chair "under" you when you build it while standing? Or a table? Or a machine frame?
It's just the way building works in the game.

Also, wheelchairs are able to roll right over both chairs and stools that are already built.

**Comment by Probe1** [comment]
that makes two issues now, this and the security one, where I question whether or not it should be like that.

you're a cripple.

**Comment by Exxion** [comment]
On the other hand, you still have arms.
Unless you don't, but that's unrelated.
You build things with your arms, not your legs.
Being in a wheelchair would make constructing something more difficult, but, in most cases, not impossible.
Though maybe it should put it on the tile in front of you rather than your current tile if you're in a wheelchair.

**Comment by Probe1** [comment]
flop out the chair and crawl around on the ground building shit and arresting people.

**Comment by Shadowmech88** [comment]
See, that'd work, if you could do ANYTHING while on the ground.
Being on the ground as a result of being footless/legless is effectively the same as being stunned, minus the inability to move.
Legless people can't even hold things or buckle themselves into regular chairs while they're on the ground.

**Comment by Probe1** [comment]
true.

**Comment by PJB3005** [comment]
This is because vehicles (and as such the wheelchair) are `/obj/structure/stool/bed/chair/vehicle`

Which is just fucking retarded

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.

Also I've discovered that people in wheelchairs can construct stools, office chairs, and every kind of comfy chair, but still not regular chairs and beds.

**Comment by PJB3005** [comment]
Side effect of me moving some types around, @Shadowmech88
