### ISSUE TITLE
Add Generic Mounted Signaler Buttons

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5268]
Despite all the different kinds of mounted assemblies we can build, we don't have one that functions essentially as a mounted remote signalling device. It would be very handy for being able to trigger multiple signaler-oriented devices without having to carry a bunch of signalers on you, or needing to constantly configure one signaler to each device's code.

Essentially, it'd be the same as the current remote signaling device, except you'd change the code/frequency with a multitool, and pressing the button would send the signal.

**Comment by ComicIronic** [comment]
It would be better to be able to attach a signaller, in the same way you can weld igniters.
