### ISSUE TITLE
Kitchen trays expanding backpack size

### ISSUE THREAD

**Issue by chainsauce** [d3athrow/vgstation13#5270]
So I read that trying to put a tray into your bag sometimes makes it drop everything, so I wanted to see it. So I spammed click on my bag with the tray and it actually went in, along with a message of 'God dammit!' I was a bit confused, so I tried taking it out again. This somehow made me take just the tray, leaving all the things on it in my bag. I tried to put more stuff in it afterwards, but it said it was too full, so I couldn't keep making more rows sadly, and create the ultimate bag of pizza holding.
![uh oh](https://cloud.githubusercontent.com/assets/6082418/8532418/ecd9921e-23fb-11e5-8774-7c00ba6d0682.png)

**Comment by clusterfack** [comment]
Bluespace

**Comment by Kurfursten** [comment]
I had seen the line in the code that does this, and I wondered why it existed. It's like a 5% chance. Someone did it on purpose.

**Comment by greywarlock** [comment]
My guess is that the tray and its contents are supposed to fall to the floor in one big mess instead of going into the backpack.

**Comment by Exxion** [comment]
>Either still not fixed or fixed but still open

**Comment by Exxion** [comment]
> EITHER STILL NOT FIXED OR FIXED BUT STILL OPEN

**Comment by PJB3005** [comment]
Can we confirm it's fixed or not?

**Comment by Exxion** [comment]
Now we probably can try to now that trays actually work again

**Comment by 9600bauds** [comment]
Oh hey I actually fixed this
