### ISSUE TITLE
Cannot clean blood off of clothes/hands

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#5271]
It don't work

**Comment by Probe1** [comment]
I've had the same issue in a round with a hardsuit that was cleaned but the sprites still displayed blood.
Also https://github.com/d3athrow/vgstation13/issues/5249

**Comment by NigglyWiggly** [comment]
Yes, you can clean the items but the icon doesn't update at all.

**Comment by DrCelt** [comment]
Out, damned spot! Out, I say!—One, two. Why, then, ’tis time to do ’t. Hell is murky!—Fie, my lord, fie! A soldier, and afeard? What need we fear who knows it, when none can call our power to account?—Yet who would have thought the old man to have had so much blood in him. 

The thane of Fife had a wife. Where is she now?—What, will these hands ne'er be clean?
