### ISSUE TITLE
(WEB REPORT BY: blarghargin123 REMOTE: 198.245.63.50:7777) Gyrotron cant be rotated

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5272]
>Revision 436e36750b7d5e10d03f1fe970ec02a43624609c

>General description of the issue
Gyrotron cant be rotated unless its pulled into the direction you want

>What you expected to happen
I would be able to rotate the damn thing

>What actually happened
I couldnt rotate it

>Steps to reproduce if possible
Fix yo shit Cael Aislinn. Oh wait, your dead.

**Comment by AutismSpider** [comment]
Can we hook the gyrotrons to the emitter code or some shit?

**Comment by PJB3005** [comment]
Gah I'll see about it

**Comment by ComicIronic** [comment]
Make "rotate thing" a mob verb to apply to objects.

**Comment by PJB3005** [comment]
Well, thing is, it'd show up even on objects that shouldn't have it, which is kinda a pain

**Comment by ComicIronic** [comment]
That's fine.
It would make using the verb faster, and there's no reason you can't rotate everything in the game.
Some stuff just does nothing when you rotate it.
