### ISSUE TITLE
Feature Request Update the pressure gauges

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#5274]
So pressure gauges are bare bone when it comes to telling us what gas is in the pipes how many mols etc.

Can we update them so it works like the atmospheric analyzer?

**Comment by Probe1** [comment]
that'd be pretty sweet.  shame pipes don't really have 'upgrades'.  everything is on the RPD.  definitely worth an update though, there's so much information that only ghosts have or you have to construct a gas chamber, use a sensor, use a computer .. ..

**Comment by PJB3005** [comment]
I'm for this, you can even read gas composition with atmos sensor monitors linked to pressure meters

**Comment by Kurfursten** [comment]
#5322 semi related
