### ISSUE TITLE
(WEB REPORT BY: jyxpe REMOTE: 198.245.63.50:7777) Infinite Power Cells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5278]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The telepad console creates a basic power cell when the monitor is connected.

>What you expected to happen
No power cell.

>What actually happened
Power cell.

>Steps to reproduce if possible
Disconnect/Reconnect the telepad console

**Comment by clusterfack** [comment]
-Panic-

**Comment by PJB3005** [comment]
@9600bauds
