### ISSUE TITLE
[box] 2 cameras on the same tile in telescience

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5280]
![](http://i.imgur.com/3XGMfSF.png)

**Comment by ComicIronic** [comment]
WHAT
MAP

**Comment by PJB3005** [comment]
whoops

**Comment by Ephx1** [comment]
I had always assumed it was there for coverage.
It seemed like cameras were always finicky.
![untitled](https://cloud.githubusercontent.com/assets/6224074/8550816/edb8a6e8-24a0-11e5-936a-13502669f582.png)
Same is true for perma in box.

**Comment by dylanstrategie** [comment]
I am pretty much certain this is intended for use with camera networks

R&D duplicates are used for the Research network, most of the Engine is under the Engineering network and Security has its own network

**Comment by ComicIronic** [comment]
So not an issue?

**Comment by PJB3005** [comment]
uh, can't you assign cameras to multiple networks?

**Comment by ComicIronic** [comment]
It might be done by id_tag.

**Comment by PJB3005** [comment]
during camera construction it asks you for the networks, and you can seperate them via ,

**Comment by Exxion** [comment]
I know there was a lot of camera duping during The Great Gas Datums Reversion Switched Tile Catastrophe, but any duped cameras outside of telecomms and possibly atmos are not artifacts of that. They could be artifacts of a similar error, though. Perhaps even the same unknowable shit that caused all the bizarre window fuckery that plagues Taxi and parts of Box.

**Comment by Intigracy** [comment]
They're on seperate networks, in the case of all duped cameras I could find.

Perma / Science wing / engineering

I actually can't find any cameras with two networks on the same camera.
