### ISSUE TITLE
Implement radiation via the lighting engine.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5283]
Essentially, radiation gets handled via light sources, the light sources will have another "colour" spectrum alongside rgb, that doesn't get rendered, but DOES have some !!FUN!! side effects for mobs in lighting overlays with that spectrum

why? shit like geiger counters

**Comment by dylanstrategie** [comment]
Well, you have things like UV and gamma rays that have some potent and potentially dangerous effects on people, then infrared for heat, and microwaves, even radar

It should be relatively easy to include, especially since they would all be invisible unless you are wearing the correct gear

**Comment by ComicIronic** [comment]
Some issues with that in regards to penetration, though.

**Comment by PJB3005** [comment]
radiation doesn't go through walls, except for the SME's rads.

though the SME's radiation math works in such a way the distance is a complete joke so

**Comment by ComicIronic** [comment]
I think the singulo also goes through walls.

**Comment by PJB3005** [comment]
it doesn't IIRC

**Comment by ComicIronic** [comment]
It does for the rad collectors.

**Comment by PJB3005** [comment]
We all know rad collector code is non OOP trash
