### ISSUE TITLE
Alt clicking doesn't automatically focus on the floor tab

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5284]
Previously, when you alt clicked it would bring up the tab to see what was on the floor.  Very smooth.  Very convenient.  About 1 to 1 1/2 months ago this feature stopped working.  It would be good to fix it.

**Comment by d3athrow** [comment]
Still focuses for me

**Comment by AlphaBuffalo** [comment]
You have to alt click the tile itself, if you alt click something on the tile, like lets say a tool box, it would bring up the menu.
