### ISSUE TITLE
The less-easymode alden saraspova counter

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5285]
Currently, VG doesn't use the alden saraspova counter, because it was broken as fuck. Cael semi-fixed it later for bay, and someone in bay fixed it better, but now it's an easymode tasergun-looking doodad.

What I am suggestings: Make an alden saraspova counter for vg, and use the super sci-ency coder art sprite we currently have for it instead of the.. taser..thing that bay has. However, not with the same functionality.

What vg would need:
Alden saraspova counter
A core sample database machine.

How it would work:
Everything as normal for large artifact hunting, as is now. With a caveat: Once you run the sample tray through the FFT and the Hyperspect at least once and successfully get a range and a signal,  you can then use that tray in the registry machine.

This would register the core sample in the machine, sorted under the signal source with its distance and coordinates cored from.

The alden saraspova counter would have an interface, and these signal sources would show up as options in the interface once you scan them into the database. You can select the signal you want to track.

You can then use the alden saraspova counter like it works in bay, but specifically for that source, and the accuracy of the reading gets more accurate the more unique core samples you have of that specific signal you're tracking in the database.  (though if you want to do an improved interface that doesn't involve in-hand click click click click and instead had some sort of .js compass dodad that'd be swank)

You would need at least three samples to get within ~20 tiles, six samples to get within ~5 tiles, etc, and each core sample must be at least 5 tiles away from eachother and not in the same x plane.

This way: it's still difficult and takes ss13 pseudoscience to do, but makes actually going out and finding the large artifact easier.

**Comment by clusterfack** [comment]
I like this idea. The alden saraspova counter was something in the code that I saw and thought it would be great to have an object to improve artifact hunting. But an implementation that was just an ultra efficient method of analysis would ruin the effort/reward of xenoarch.

I'll have to look into this and toy around with the particulars of how it might be done.

**Comment by Midaychi** [comment]
Alternatively, you could probably abuse the html module map to draw approximate areas on the generic asteroid map, and shrink them as you refine the data. Just using the alden saraspova counter as a portable map viewer.

**Comment by Midaychi** [comment]
Alternative to the above that might be a lot easier to implement: Take alden saraspova counter from bay, give it vg's current alden saraspova counter sprite, and make it printable from R&D at a med-low level. 

Just enough to make sure on low pop rounds that xenoarchs do R&D but not high enough/material requirement enough that it's not going to happen if no miners.

With this caveat:
The alden saraspova counter does not function unless you slot into it a sample tray with 1 unit of analysis fluid and one unit of the correct carrier fluid. Using incorrect fluid will give wildly inaccurate/inconsistent results.
Once you do, you can use the alden saraspova counter to measure the distance to the analysis liquid's signature, with the accuracy variance being affected by the range var stored on the analysis liquid.

Less than 40 meters is super accurate, less than 60 meters would be pretty accurate, less than 120 meters would be moderately accurate, and higher than 120 would be probably wildly inaccurate.
