### ISSUE TITLE
Brig physician

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5287]
http://nanotrasen.se/wiki/index.php/Brig_Physician

They work a lot better and are played a lot more often than one might think.

They're basically the warden's helper, and responsible for keeping officers/prisoners from dying when they can. They get a small little under-equipped med closet with a few beds and a sleeper, and a closet with a few kits and some basic security gear. 

They also can keep the rowdy prisoners complacent with sleep toxins from the sleeper and such, and occasionally fill the roll of brig janitor when the officers are busy. 

Since they have medical access, when the brig is empty and they're not needed, they can head to medbay to temp fill in any vacancies.

They're also theoretically responsible for overseeing executions (not performing them, just making sure they're done right), but in practice the HOS usually enjoys performing executions without notifying anyone.

**Comment by Probe1** [comment]
there's been plenty of people that successfully ran gimmicks by asking the hop

**Comment by IratePirate** [comment]
We don't get enough Security players as it is, why waste the slot at all? Just go to the HoP and request an implant.

**Comment by Midaychi** [comment]
Well ok, what if: This job only existed on highpop?
As in, if players are > 40 or 50 then it'd randomly check for someone who was picked for basic medical doctor who also has security on their options and spawn them as a BP in the security medical along with a closet of stuff?

**Comment by ComicIronic** [comment]
It could be made an alt title.
Though I don't quite like the way it's handled.
A security officer with medical access would be more desirable, simply because they would be available for sec work and it would drain the departments less.
