### ISSUE TITLE
(WEB REPORT BY: dragonbro REMOTE: 198.245.63.50:7777) Ore Redemption Machines not present at roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5289]
Had a few reports of it now, firstly on Meta, then twice on box. Just so happens that this time I got pictures.

http://i.imgur.com/QmIyy0y.png

Right clicking shows that it isn't invisible, it's just not there at all.

**Comment by PJB3005** [comment]
not a bug, it's even in the changelog!
