### ISSUE TITLE
Make all atmospheric devices sync their colors with nearby pipes

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#5296]
In short, valves, pumps, connectors and generally all atmospheric devices with inlets or outlets would have their pipes colored depending on what they are linked to

Because the small junction of gray pipe looks weird

**Comment by ComicIronic** [comment]
I find it nicer-looking that the TG system.
Though maybe I'm just used to it from playing a lot of atmospherics.

**Comment by Intigracy** [comment]
Celt did this, can close.

**Comment by clusterfack** [comment]
Indeed
