### ISSUE TITLE
Crew Monitoring Console optimization stripped key features that need returned.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5297]
Just all around wtf.  It's not worth saving the lag if you remove the game.

1.  I can't copy SHIT.  Want GPS coordinates?  Fuck you have optimization instead!

2.  Doesn't tell me the health until I hover over it.  Rubbish

3.  Map is now for ants and isn't usable.  

![crew_monitoring_2015-07-08_17-12-51](https://cloud.githubusercontent.com/assets/8550416/8582410/9f14430e-2594-11e5-95c8-59f1f97f4591.png)

In every single area the consoles have been made complete shit.  It's a game.  It will lag.  Find a way to fix it without killing features.

**Comment by PJB3005** [comment]
UGH THAT ugly UI, seriously, port the current UI to tge HTML interface module but DON'T FUCKING use that UI it's TERRIBLE

**Comment by Midaychi** [comment]
*whine
But seriously unless @nullquery helps or clusterfack suddenly learns js, this is how its gotta be.

**Comment by Probe1** [comment]
Comparing the old CMC

![2015-07-08_17-31-55](https://cloud.githubusercontent.com/assets/8550416/8582860/54c42154-2597-11e5-8f8e-9ee24ecf95c7.png)

I can easily see where people are and look at their health at a glance.  

![2015-07-08_17-32-08](https://cloud.githubusercontent.com/assets/8550416/8582876/686450b2-2597-11e5-9287-f3e86ee99342.png)

I can zoom in, go figure that'd be important.  Also I can change z levels.  

![2015-07-08_17-31-42](https://cloud.githubusercontent.com/assets/8550416/8582885/7487a826-2597-11e5-8d8c-5b4f54a46c7a.png)

Want a list of everyones health?  Here you go.  Health, gps, there done no problem.  If someone has increasing oxygen damage I can tell immediately instead of having a green square that will slowly change.  

The CMC was a good console and an example of a more modern feature in space.  This current attempt meets none of the criteria the previous iteration did and isn't an optimization it's a flat out nerf in every way.

**Comment by clusterfack** [comment]
>UGH THAT ugly UI, seriously, port the current UI to tge HTML interface module but DON'T FUCKING use that UI it's TERRIBLE

If you actually have all the know how to do that, feel free

**Comment by Probe1** [comment]
That title wasn't very conducive to discussion.

**Comment by Probe1** [comment]
I believe Comic is actually a bot that parses issues for keywords.  I didn't literally mean it's a discussion, I meant I was being an insufferable cunt and needed to change the title to something less pissy.

**Comment by Ephx1** [comment]
It's still a discussion regardless of the feature itself and how it may be altered.
I personally believe the original was better, the list was perfect for easily noting hurt persons and if you need a more specific representation you could see their marker on the map option.

This new one both has a terribly small map and list smushed together, needing to go over each option (as mentioned above) is tedious and annoying. I think the map if enlarged, would be much better, the blinking is very handy, and at times the original markers would blend into certain areas such as the asteroid, and if teleportation was unavailable, it was a small game of "Where's Waldo's corpse?".

Main points:

This new list is terrible, use the old one.
Map is good, make it bigger.
Also allow for z-level changing.
If possible also make the map and list two separate settings.

**Comment by nullquery** [comment]
@Probe1 Let's take a look:

> I can't copy SHIT. Want GPS coordinates? Fuck you have optimization instead!

Why do you need to copy the coordinates?

> Doesn't tell me the health until I hover over it. Rubbish

This was partially deliberate to avoid the AI from becoming too powerful and instantly responding to players' health. There's also the indicator which does a good job on its own of showing what the health is.

> Map is now for ants and isn't usable.

Smaller monitors wouldn't be able to display the map and the table, hence why the map was fixed to a 480x480 size. I don't see how the map has become useless, it's just something you have to get used to.

> It's a game. It will lag.

With that attitude it will, yeah.

> In every single area the consoles have been made complete shit.
> Find a way to fix it without killing features.

Moments when I'm glad I'm not the one behind this PR. I made a good move ditching Baystation(-based) codebases, what with all the whining.

If you'd be constructive and actually provide suggestions to improve what's already there I may opt to do so in /tg/ and it could be ported right along with my existing fixes.

All you're doing now is telling me _not_ to help /vg/ because my work will only get insulted. :angry:

**Comment by Probe1** [comment]
I don't want help I want it reverted because it gutted the machine and only two coders were complaining about it.

**Comment by nullquery** [comment]
Then revert it. Don't have me summoned me here just to complain.

**Comment by ComicIronic** [comment]
>Smaller monitors wouldn't be able to display the map and the table, hence why the map was fixed to a 480x480 size. I don't see how the map has become useless, it's just something you have to get used to.

But the solution to that is to maintain the original functionality, of having the list and map separate.

Does the new CMC include GPS at all?

**Comment by Probe1** [comment]
@nullquery I didn't summon you, Midaychi who had no part in any of it did.  I apologize for the inconvenience and wasting your time.

**Comment by Probe1** [comment]
GPS and exact health stats are retained but are now mouse hover Comic.  So there's no way to copy gps coordinates without typing them out.  There's no way to know someone is being injured until they're injured enough to trigger a color state change.  All around not what people wanted at all and it got merged before anyone knew it was up.

**Comment by acepie413** [comment]
completely agreed
it's literally shit-tier, the previous CMC was infinitely better, this one is a mess and is absolutely garbage and unusable, may as well remove suit sensors as a whole if this is what it's going to be
revert it, i have noticed absolutely no shift in lag from when it was ported to now

**Comment by Ephx1** [comment]
I'm not entirely certain if the color state change function even works properly.
It seemed like people with no damage were green, but some of the others with no damage and suit sensors at max were white.

**Comment by nullquery** [comment]
AI only sees white and has to hover over the health icon manually to see damage.

This was done to nerf the AI's ability to be omnipresent and making rounds boring.

I'm willing to look into making this configurable if there is a concrete list of changes, but you'll all have to help me pitch the resulting PR to the /tg/ developers.

**Comment by Ephx1** [comment]
While as an AI I saw green as well, it showed them at maximum health, same as those with white.

**Comment by d3athrow** [comment]
@nullquery 
>All you're doing now is telling me not to help /vg/ because my work will only get insulted.

If you're that sensitive that you can't handle somebody not wholeheartedly praising something you've done then you'd probably be best to stay away from 4chan then, but if you can be an adult about things instead of making threats then you're free to help or not.

**Comment by PJB3005** [comment]
Here's some constructive criticism: port the NanoUI CMC to the HTML interface module

**Comment by Iamgoofball** [comment]
This is pretty fucking hostile though
What you might wanna do is set up a new version of the zoom buttons and having the separate menus for health and the map for the CMC and set it up in HTML
also replace the squares with nanoui edition's job icons, and color them based on shizzles.

That way we've got the better UI backbone but with the better parts of the nanoui one merged in

**Comment by PJB3005** [comment]
Yeah, I agree this is kinda hostile,

**Comment by clusterfack** [comment]
I think we can all agree here that the real problem is was merged far far before it was ready for the public, within about ~7 minutes of being opened. Well that and the extreme overreaction of people who were told that this was in fact a WIP.

**Comment by SangriaMonkey** [comment]
>no coordinates, limited to one z level

Those are the biggest problems here. Zoom or not the coords are fucking invaluable to recovering bodies and locating people.

**Comment by Midaychi** [comment]
"kinda hostile"

>"this is shit teir garbage that's completely unusable and ugly"

Yeah no shit. I just wanted to ask Null if he could help us port with some changes and now they're getting hoisted on the burning effigy for designing something specifically for ANOTHER STATION by a pair of retards who can't get over the temporary loss of their convenience features and a whiner who can't get over a stupid fucking button.

I really don't think the quick merge caused this though. The same reaction probably would have happened from the *same people* on the pr if it waited a day.

**Comment by Ephx1** [comment]
It's almost as if changing a core feature to a job with a 7 minute notice and lack of communication was a thing no one liked. 

It's like if suddenly wiring worked a completely different way, and engineering got mad. Sure, it's WIP, but why would you change a core feature like that so soon if it is a WIP and nowhere near as good as the original? I'll accept that it has several bonuses like a less taxing CPU, but couldn't that wait until it was specifically redesigned for this server?

**Comment by clusterfack** [comment]
I made the PR, I did not merge it.

**Comment by nullquery** [comment]
See https://github.com/tgstation/-tg-station/issues/10498

**Comment by Ephx1** [comment]
That fixes all gripes I had with it. Thank you.

**Comment by optimumtact** [comment]
>Vg coders can't code

ayy lmao

**Comment by d3athrow** [comment]
3ff52cdd3d76691ddc73907e763b9be2d97084a5

**Comment by d3athrow** [comment]
this resolved??

**Comment by Probe1** [comment]
90% of the buttons are covered by the map.  the only way to see the map is to click and hold.

http://puu.sh/iWAJ8/911200773b.webm

![crew_monitoring_2015-07-12_14-03-49](https://cloud.githubusercontent.com/assets/8550416/8639154/dd30c114-289e-11e5-83d8-76a0d1a85a7c.png)


Some text in text only is unreadable from being covered by multiple entries.  

![crew_monitoring_2015-07-12_14-02-34](https://cloud.githubusercontent.com/assets/8550416/8639152/bed5360a-289e-11e5-8967-879550ea10b8.png)

**Comment by Ephx1** [comment]
Also on this, the Station z-level map shows some areas as having space tiles.
Like the kitchen, RD office, server room, and then some.

**Comment by PJB3005** [comment]
@Ephx1 probably fucked up nanomaps

**Comment by d3athrow** [comment]
@Ephx1 this happened with nano too for a time being, issue is the fucking tiles in the nonspace-but-space-looking parts have a direction the map gen cant handle

**Comment by Ephx1** [comment]
Oh I see. Well the only other bug I've noticed is that the color for damages on the map screen don't display, only the brute one.

**Comment by Probe1** [comment]
It has been returned to equivalent levels and now functions satisfactory.  Thank you to everyone that worked to correct it.
