### ISSUE TITLE
(WEB REPORT BY: zushakon REMOTE: 198.245.63.50:7777) Teleporter beacon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5298]
>Revision (Should be above if you're viewing this from ingame!)
Revision: f9568b862d73bdd0f81360828561aef1b59f4022 

>General description of the issue
There is no sprite for them

>What you expected to happen
There to be a sprite

>What actually happened

There is no sprite so it is invisible
>Steps to reproduce if possible

Look with your eyes

**Comment by ComicIronic** [comment]
Is this still an issue?
