### ISSUE TITLE
Melting walls

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#5299]
If the RUST is on its way to being a viable engine, it should have something to make it more challenging. Why not melting wall??? Idk make walls melt when the temperature of the room is around... 10,000 K? Obviously it will need balancing discussions, and whether or not it should even be added, but hey, I think it will be fun

**Comment by Probe1** [comment]
note that the rust reaches temperatures of 500,000K so
uh

**Comment by PJB3005** [comment]
@Probe1, it actually reaches high enough temps to cause variable rollbacks in BYOND.

**Comment by Probe1** [comment]
based R-UST

**Comment by AutismSpider** [comment]
R-UST during its operation it broke the atmospherics completely, eventually causing rounding errors to hard-set the temperature to 1 Kelvin. Which is anything but hot.

**Comment by AlphaBuffalo** [comment]
Is it possible to fix the rounding errors? Also, didnt know it gets that HAWT
