### ISSUE TITLE
After Being Picked Up and Put Back Down, Stools Can No Longer Be Deconstructed

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5300]
Additionally, while you must click+drag the stool onto yourself to pick it up the first time, picking it up subsequent times requires only clicking on it, as if it was a normal item.

**Comment by clusterfack** [comment]
I think that's because it's getting converted into a normal stool item that can be picked up but not back to a stool upon dropped

**Comment by ComicIronic** [comment]
If you're dropping them, you're doing it wrong.
You have to click the stool in your hand to put it back down as a stool structure.

**Comment by PJB3005** [comment]
I'm working on a PR to rework chairs & buckling, because stools do exactly nothing, I'm just gonna remove the structure version

@ComicIronic it's shit code nontheless

**Comment by Shadowmech88** [comment]
Being fixed by #5378.
