### ISSUE TITLE
ATM, requests console, and newscaster construction is fucking retarded.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5301]
1. It gets put UNDER you, THEY'RE WALL MOUNTED FFS.
2. They require no circuits or wiring. what?
3. Newscasters are in the engie-vend, which is just redundant, make their frame from the metal construction menu.

@kurfursten

**Comment by Probe1** [comment]
I agree and was thinking about this yesterday but forgot to make an issue.  I suggest we look at air alarm and apc code.  Hold the item.  Click the wall.  It attaches to the wall.  Simple, functional, works as expected.

**Comment by Kurfursten** [comment]
Yeah, probably better to trash the construction process entirely; adding construction/deconstruction for those three was something I half-assed five months ago.

Directional code can be lifted from intercom as opposed to APC or air alarm because it doesn't need an icon state change.

**Comment by ririchiyo** [comment]
if only there were wall mounted datums to use
