### ISSUE TITLE
Power Monitoring Console is broken

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5303]
It no longer displays total power, total load, or whether the apc is charging or not.  They all say 90% and not charging.  Oops.  @clusterfack wasn't it part of the html thing?

![north_hut_five_2015-07-09_07-55-59](https://cloud.githubusercontent.com/assets/8550416/8594791/5564f892-2612-11e5-957b-c41457a15dfc.png)

**Comment by PJB3005** [comment]
the HTML interface module is FUCKED for silicons, and ghosts use the silicon code for interacting with computers

**Comment by clusterfack** [comment]
That's strange, must be a side effect of something I changed so I'll look into it.
