### ISSUE TITLE
Airlock button in disposals room

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#5307]
Im getting sick and tired having to leave to take care of IRL shit, and coming back to see I've been stuck in disposals with no way of getting out and having to ask cargo to open the door. Why not skip a step and just add an airlock button to open the door from the inside to let yourself out, WHY HASNT THIS BEEN ADDED BEFORE????

**Comment by Probe1** [comment]
>WHY HASNT THIS BEEN ADDED BEFORE

most people go afk in the dorms, medbay, their department inside a locker, or other places that they can't get joked on by random passerbys.

**Comment by Exxion** [comment]
Protip: Lie down on the conveyor belt to send yourself to actual disposals, the door to which (almost) everyone on the station has access to.

**Comment by AlphaBuffalo** [comment]
Thats the thing, sometimes people will take your ID if your afk long enough. But also its more of a convenience thing anyways.

**Comment by Exxion** [comment]
Protip #2: Assuming PJB successfully fixed the sorting machinery so it doesn't fail all the time, you can use the wrapping paper and destination tagger on something and throw it on the conveyor belt in front of you. As long as you and it are flushed at the same time, you'll end up at the same place as it. It's far from an optimal solution, but it works... in theory
Yes, sometimes someone takes the wrapping paper and/or tagger, but it's really uncommon.
