### ISSUE TITLE
make RCL fit in hazard vest storage slot

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5309]
PLZ.
Currently the only way to store the RCL is to put it in a backpack, which isn't always an option in certain loadouts.

**Comment by Probe1** [comment]
don't forget the CE belt and bags of holding.

**Comment by Midaychi** [comment]
Just the RCL would be fine.

**Comment by Probe1** [comment]
no, the RCL fits in those things.  It fits in backpacks, the CE belt and bags of holding.  It's the same size as an RCL.
