### ISSUE TITLE
Cyborg charger upgrades result in part duplication

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5312]
Upgrading a cyborg charger with an rapid machine component exchanger, adding a power cell, and having a cyborg move into the charger results in the parts you added being ejected while the machine still retains the parts, duplicating them.  So you end up with piles o super capacitors laying about.

**Comment by clusterfack** [comment]
>RMCE

Do we need a tag for this

**Comment by Probe1** [comment]
The machines in testing were properly closed.  I've also seen phasic scanners laying in medbay on top of advanced scanners that I had upgraded.

**Comment by PJB3005** [comment]
*[WHOOOOOOOOOOOOSH](https://github.com/d3athrow/vgstation13/pull/4782)*

**Comment by Probe1** [comment]
no we must do this the hard way.
