### ISSUE TITLE
Invisible Cloner Console

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5313]
After the DNA scanner was destroyed and presumably the console was damaged, it became invisible.  I'm not sure how this occurred (bomb, deconstruction, etc) but I know a vampire did it and he had shrieked breaking glass in the surrounding area northwest of the cloner, primarily in the paramedics station.

I do know that I couldn't move to where the console was when I went to repair the missing Scanner and Console and found that the console was still there but without an icon.  I could still interact with it with tools (wrench and pulling it).  I had it taken away and built a new one.

![death_alium_death-trap_88_2015-07-09_21-10-17](https://cloud.githubusercontent.com/assets/8550416/8611015/81ca8066-2688-11e5-8029-9b7450168a80.png)

**Comment by ComicIronic** [comment]
You should have screwdrivered the glass out, it's missing the broken state.
