### ISSUE TITLE
Give Borers the Ability to See Whether Humans Have Borers in Them

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5316]
Like the cultist icon or something. It'd make it easier for borers to cooperate if they knew which humans they could trust without having to constantly update each other on their host names via mind link.

**Comment by AutismSpider** [comment]
Did some one fuck up the borer hud?

Green Dot over people who have borers in them.

**Comment by Shadowmech88** [comment]
Oh, I didn't realize. I wasn't watching that closely, it may have been there. I just didn't know the feature existed.

**Comment by Probe1** [comment]
I don't even remember that feature.  I remember when sugar killed borers but I don't remember that.  Mite have been broken for a long time.

**Comment by AutismSpider** [comment]
sugar poison to borers/acts as sleep toxin to them.

other borers can tell if a human has one by green/yellow dot over them.

**Comment by Shadowmech88** [comment]
This is apparently already a thing.
