### ISSUE TITLE
Eggsploding

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5319]
If any of the below features exist already, then disregard adding them:

It'd be neat if if there was at least 1 unit of frostoil in a chicken egg, then any reagents put inside wouldn't react. it'd gain a noreact flag

Throwing the egg sufficiently well or shooting the egg sufficiently fast should splatter when it hits a target.

When the egg splatters, it would be neat if the egg reacted its contained chemicals together, and any remaining chemicals were applied to the surface of the thing hit. So, if it hit a wall it'd splash the wall, if it hit people it'd hit people.

You could use the above to: Turn eggs into half-size small chem grenades, or use them in pneumatic canons as chem rounds.

**Comment by 9600bauds** [comment]
This is the weirdest, most specific feature request I've read.

**Comment by PJB3005** [comment]
:+1:
