### ISSUE TITLE
Recycling Furnace Can't Make Plasteel

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5320]
When you set plasteel to highest priority and feed it metal and plasma, it eats the metal and just spits the plasma back out.

**Comment by Midaychi** [comment]
rip @PJB3005

**Comment by PJB3005** [comment]
Unable to reproduce this myself

**Comment by PJB3005** [comment]
Alright shadowmech told me on IRC what the actual problem was, it's caused by the fact that the sheets don't recycle properly
