### ISSUE TITLE
"airtight" plastic flaps

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5323]
the plastic flaps used in the routing areas on taxistation are "airtight", but for some reason they don't actually block air, so the areas vent at round start

**Comment by FudgePucker** [comment]
I think they are 'air tight' the issue is hacky var editing (or some shit I have no idea) where it is simulated then unstimulated and then simulated until it can't make up its mind and just goes 'fuck it' and dumps out the air.

SME chambers on box and meta had the same issue on and off.

**Comment by PJB3005** [comment]
no, they're the /obj/structure/flaps/mining, no var editing

**Comment by FudgePucker** [comment]
What about the turf?

**Comment by clusterfack** [comment]
That's strange, I modified the Canpass proc so that it should make a zone to block air with.

**Comment by ComicIronic** [comment]
Is it not because they don't start anchored?

**Comment by clusterfack** [comment]
The mining flaps start anchored/airtight, but apparently they aren't actually blocking air

**Comment by FudgePucker** [comment]
This should be easy enough to test, just go into the test server and see if air tight flaps can block air, if it blocks air then its a turf issue, if it doesn't than the issue is with the flaps.
I will do it later tonight if you guys don't do it.
