### ISSUE TITLE
Lag makes vg almost unplayable

### ISSUE THREAD

**Issue by optimumtact** [d3athrow/vgstation13#5324]
Seriously how do you guys even manage to do things?

I lagged clear across the server before I could even register change

**Comment by Iamgoofball** [comment]
posting in a meme issue

**Comment by PJB3005** [comment]
obvious troll is obvious

REMOVE ORANGES WHEN

**Comment by optimumtact** [comment]
Excuse me? please treat this issue seriously

**Comment by duncathan** [comment]
:+1:

**Comment by ComicIronic** [comment]
That's you, not the issue, for the record.

**Comment by optimumtact** [comment]
Pshoooom, hard to reproduce when I lag out of the bedroom when trying to get out of my clothes

**Comment by IratePirate** [comment]
In my experience /vg/ was always one of the least laggy servers aside from that 8 month period where it was absolutely godawful, i.e. The Featuring.

**Comment by PJB3005** [comment]
@IratePirate @optimumtact is trolling here, he basically confirmed it on IRC too.

**Comment by SkowronX** [comment]
Oranges make good chicken.
