### ISSUE TITLE
Progress bars are affected by an atom's color var.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5326]
@iamgoofball

**Comment by Shadowmech88** [comment]
Can confirm, it's especially noticeable when working with colored pipes.

**Comment by FudgePucker** [comment]
Can comfirm, colored pipes have retarded progress bars.

**Comment by Iamgoofball** [comment]
i think its impossible to fix

**Comment by PJB3005** [comment]
@Iamgoofball it definetly isn't

**Comment by Iamgoofball** [comment]
I dunno, the thing is the way we're doing it(client_images) is something we can't fuck with too much.

Someone in the /tg/ issue report for this brought it up.

If you say "remove" as the fix method I will gut you alive.

**Comment by clusterfack** [comment]
I'm sure there's a byond proc to get the height of an icon_state. If so we could do the progress bars as an animation of a screen object put into the client's screen and with a screen loc of the objects turf offset by the pixel height of the icon_state.

**Comment by PJB3005** [comment]
@Iamgoofball nerd 509 is out fixitfixitfixit

**Comment by clusterfack** [comment]
Yay we have a way to fix it

**Comment by 9600bauds** [comment]
woo
