### ISSUE TITLE
Station Time: 25:05 

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5329]
If a round goes on for too long...

**Comment by ComicIronic** [comment]
IF MAN IS STILL ALIIIIIIIIIVE
I don't see what's wrong with it.

**Comment by clusterfack** [comment]
No midnight rollover

**Comment by CptWad** [comment]
Its on military time, as in shift starts at noon
Supposed to roll over once it hits 24, then goes 0:01, 0:10, etc down till 1 in the morning is 1:00

**Comment by Probe1** [comment]
hush its an easter egg

**Comment by Exxion** [comment]
But what's the point of fixing a bug that will never ever occur in actual gameplay ever (I hope)?
On the other hand, fixing it would take like five characters

**Comment by Probe1** [comment]
its occurred on a local server I forgot to close and had muted.  only time i've seen it. 

Also Y2K

**Comment by FudgePucker** [comment]
Maybe its not what time it is but how many hours have passed in that shift, you spend a few hours setting up and having safety lectures from the captian about sexual harrasment and plasma containment and shit for a few hours before finaly getting to sit down at your chair to work/ go to tool storage to arm up to destroy the station.
