### ISSUE TITLE
Make vines produce fruit more often or 100% of the time

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#5334]
I have a complaint about botany where vines seem useless. You can make them glow in the dark and grow 20 different types of fruit, but unless luck is on your side the results will be nothing due to this one line of code at: https://github.com/d3athrow/vgstation13/blob/master/code/modules/hydroponics/vines.dm

overlays.Cut()
	if(age >= seed.maturation)
		if(prob(20) && seed.products && seed.products.len && !harvest && ((age-lastproduce) > seed.production))
			harvest = 1
			lastproduce = age

This means you only have a 20% chance of your vines growing fruit, otherwise they just spread and do nothing. This drastically drops the use of vines and I would like to see that change.

**Comment by Killette2** [comment]
Or at least make it related to potency like bioluminocity, shit's annoying getting nowhere

**Comment by Zuhayr** [comment]
That's a 20% probability per update() call per vine, not a flat 20% period for the entire vine network.

**Comment by Killette2** [comment]
The update isn't very often for the generic vines then, because I've released vines a lot with no result.

**Comment by Ikarean** [comment]
Absolutely agreed - Give vines something to be usefull.

**Comment by Killette2** [comment]
I still believe that Zuhayr is wrong, and that the 20% chance is a check that only happens once for the entire vine network, my proof being how many times I have made vines, and modified stats where the 20% chance would happen at least 20 times but didn't happen any.

That said this needs to be looked into further/
