### ISSUE TITLE
(WEB REPORT BY: nmsct699 REMOTE: 198.245.63.50:7777) Recycling furnace popup jumps around

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5335]
> Revision (Should be above if you're viewing this from ingame!)
> abf4f304dcfcd51a2f80666613af0e642cd3b764 
> 
> General description of the issue
> recycling furnace (and stacking machine) skip back to the top if you scroll down
> 
> What you expected to happen
> not skip back up
> 
> What actually happened
> the scroll bar on the gui jumps up to the top for half a second, then back down, once or twice every few seconds, which is really annoying
> 
> Steps to reproduce if possible
> bring up recycling furnace gui, and scroll down a bit (resize window down if necessary)

**Comment by PJB3005** [comment]
BYOND issue, really, the onenway to fix this would be to use nanoUI or the HTML interface module

**Comment by Probe1** [comment]
It wasn't a byond issue last week before we had our ore redemption machine removed.

**Comment by PJB3005** [comment]
You can get around it by extending the window

**Comment by PJB3005** [comment]
It's caused by the UI being updated, which causes that flickering, I can probably do some HTML stuff to make it not jump around the place as much though
