### ISSUE TITLE
(WEB REPORT BY: sonixapache REMOTE: 198.245.63.50:7777) Can't crowbar open firelocks over windoors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5339]
>Revision (Should be above if you're viewing this from ingame!)
dd0374060d3cd9c5d711078df9bfccee28f7b34a 

>General description of the issue
Atmos got fucked up again, tried to crowbar open the firelock over the kitchen

>What you expected to happen
Expected the firelock to open.

>What actually happened
Absolutely nothing. Can't bump into the windoor to open it, can't open the firelock in any way.

>Steps to reproduce if possible
Cause an atmos alarm, then try to open the firelocks in the kitchen.

**Comment by ComicIronic** [comment]
2manyborderitems.

**Comment by PJB3005** [comment]
says the person that ADDED a border item

**Comment by ComicIronic** [comment]
Added a border item for balance and QoL reasons!
The firelock just needs canreach set to 1.

**Comment by Exxion** [comment]
Wait
This shouldn't even be happening
Adjacent() always returns 1 if the object being checked (Firelock, in this case) is a border object facing the turf that called it and they are within one tile of each other (because otherwise, border objects would block access to themselves, which was fucking stupid)
Or is Adjacent() not even used for that?

**Comment by PJB3005** [comment]
@Exxion Adjacent might differ from obj to mob

**Comment by Exxion** [comment]
It's a turf proc

**Comment by PJB3005** [comment]
no, it's an atom level proc and it might differ from atom to atom.

**Comment by Exxion** [comment]
For mob, it just calls src.loc.Adjacent(), if memory serves
Regardless, I know Adjacent() works with mobs because I was the one who added that return 1 thing I mentioned two posts ago in order to make it so that you could pull windows in the direction they were facing

**Comment by Intigracy** [comment]
1 + 1 = 2 though.

I say this jokingly, but I'm going to be greatly amused if it turns out to be an issue related to both returning 1.

**Comment by Intigracy** [comment]
commenting for easier find, had a potential fix

**Comment by Exxion** [comment]
I'm pretty sure I crowbar open the _specific firelock_ mentioned in this request all the time

**Comment by Intigracy** [comment]
I had a fix but forgot what it was so w/e

**Comment by Shadowmech88** [comment]
This was fixed by #5936.
