### ISSUE TITLE
Character Limit for Writing on Paper is Too Low

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5341]
In a quick test, writing on paper seemed to cut me off at 29650 characters, which is less than half of what one can fit even in a Facebook status.
Such a low character limit makes writing or transcribing actual books rather difficult.

**Comment by Exxion** [comment]
Transcribing an actual book onto a single sheet of paper would be quite difficult in reality, at least for most books.
With default settings, exactly 3872 of the lowercase letter "a" (a rather average letter, in terms of width) will fit on one page in Microsoft Word 2013
Sure, you can write very small on the whole page in reality, but the current limit is over seven times a reasonably average page of text.

**Comment by Iamgoofball** [comment]
who cares about realism

i want to write my novel about how hitler did nothing wrong

**Comment by Shadowmech88** [comment]
@Exxion True, but I'm only opting for the paper limit to be increased because currently books are bound from single sheets of paper, which means that the text limit of a book is also the text limit of a single sheet of paper. Additionally, using the "content" option to write in an already bound book (which is ass by the way since it doesn't allow formatting) has the same character limit, which makes no sense.

Also, it appears that the character limit only applies to each writing. That is, you can write the maximum 29650 characters on the paper, submit it, then immediately write 29650 more characters.
In light of that, the limit is really nothing more than a nuisance, and has all the more reason to be increased or removed.

**Comment by Exxion** [comment]
...Character limit only works *per writing session*? What the fuck?

Also, good point.

**Comment by PJB3005** [comment]
I'm gonna assume the input sanitizer isn't counting already written things

**Comment by Probe1** [comment]
>who cares about realism

>i want to write my novel about how hitler did nothing wrong

I'm surprised I have to ask this question but is Mein Kampf in the library ?  

The library needs a lot of QoL improvements.

**Comment by Ephx1** [comment]
Mein Kampf is in the library, or at least a shortened version is.
Someone specifically asked me to get it for them once.

**Comment by Probe1** [comment]
Thank you Spess, never change.

**Comment by PJB3005** [comment]
Is this actually a BYOND issue or is this the input limiter

**Comment by ririchiyo** [comment]
It's limited in many ways because it can potentially cause a server crash if it isn't properly paginated for the information and keep in mind that some books get stored to a database and there may be a max size limit for them to be. It's to keep things to run smooth and load quickly so it doesn't slow down the game.

**Comment by Exxion** [comment]
~30k characters is ~30 KB, which is basically nothing by modern standards
But that doesn't even matter right now, because the limiter doesn't actually work correctly

**Comment by Wizardcrying** [comment]
The problem will not lie with storage, but with everyone uploading the full Mein Kampf, Nineteen Eighty-Four, and other complete books that the server will have to load every single round.
