### ISSUE TITLE
Post feedback on machine components

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5345]
Example - The microwave requires more fukken parts than the exosuit fabricator.  Same parts, requires twice as many of them to cook a weed salad as it does to create a combat mech.

I'm probably going to fix up the microwave to be less ridiculous.  If you have any similar complaints post em.

**Comment by PJB3005** [comment]
The SMES should require power cells of some kind IMO, TG has this too.

And with #4782 you can actually replace cells with the RPED

**Comment by Zth--** [comment]
Upgradable SMES. Raises its maximum input/output.
I tried to upgrade this one, but the code for SMES is really shitty and I didn't want to touch it

**Comment by Zth--** [comment]
We should start with the wiki though, we don't know what features we have or miss because it's OUTDATED AS FUCK

**Comment by Skullyton** [comment]
As told to in the thread.

"Why do Prism's require Capacitors, but SMES's do not?"

Don't SMES's require lasers or something silly too?

**Comment by clusterfack** [comment]
Magnets

**Comment by Probe1** [comment]
[01:02:05] [01:02:05] <Zth> >a superpacman, an engine, only requires 1 Matter Bin, 1 Micro-Laser, and 1 Capacito

**Comment by Probe1** [comment]
@Skullyton like clusterfack said https://en.wikipedia.org/wiki/Superconducting_magnetic_energy_storage

Fun fact, my university has a working SMES and one of the most advanced magnet labratories in the world https://en.wikipedia.org/wiki/National_High_Magnetic_Field_Laboratory.  When at peak usage, it uses 10% of the city of 200,000 inhabitants power.

**Comment by Probe1** [comment]
I haven't checked the code yet but virology, wow.  Virology machines need speed upgrades.
