### ISSUE TITLE
(WEB REPORT BY: nmsct699 REMOTE: 198.245.63.50:7777) The asspie cannot be cut into 2 cheek slices

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5346]
> Revision (Should be above if you're viewing this from ingame!)
> 8068683f81778067e22ed536f91e4905a4f6b72d 
> 
> General description of the issue
> Whats the point of baking asses if you can't share them with your butt-buddy?

**Comment by Wizardcrying** [comment]
You can't cut the puzzle into two pieces!
That's cheating!
