### ISSUE TITLE
Add Library Categories Video and Music

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5347]
For use with the nanopaper [video] tag.

**Comment by PJB3005** [comment]
...is there actually a [video] tag?

okay that makes 0 sense

**Comment by Shadowmech88** [comment]
[video] tags can be used on nanopaper only, and embeds a video in .wmv format with rudimentary controls.

**Comment by PJB3005** [comment]
ah

**Comment by Probe1** [comment]
i never knew that was in the game.  is that entirely safe?

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.
