### ISSUE TITLE
(WEB REPORT BY: sonixapache REMOTE: 198.245.63.50:7777) Dirty (bloody) glove and shoe sprites remain dirty even after cleaning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5354]
>Revision (Should be above if you're viewing this from ingame!)
ad2781aebacdfdb8a8273a2987d8cca2abe0d98e

>General description of the issue
Stepping in puke or operating on someone will dirty your shoes or gloves. You can wash them at a sink or get sprayed with space cleaner to clean it. The items will be clean in your inventory, but remain dirty on your character.

>What you expected to happen
Clean sprite.

>What actually happened
Unclean sprite.

>Steps to reproduce if possible
Spray yourself with some blood, then try to wash.

**Comment by Exxion** [comment]
I thought someone fixed this

**Comment by clusterfack** [comment]
I guess I fixed the examine text, but the same fix needs to be applied to sprites.
