### ISSUE TITLE
(WEB REPORT BY: joemother0 REMOTE: 198.245.63.50:7777) Mining jaunter not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5358]
>Revision  f18f105ce077331e58f3f2e3ddbaa5bd7240145d 

>General description of the issue
Jaunter buyable at miner prize console is kill

>What you expected to happen
Single use tool, making a vortex teleporting to a random location (toxins test area lately) on the station z-level

>What actually happened
Infinite uses, tool stays in hand, vortex dissapears on contact with player mob.
Happened twice in non-consecutive rounds.

>Steps to reproduce if possible
Get two hundred an fiddy , buy jaunter, use on the asteroid.

**Comment by Intigracy** [comment]
Has been fixed, please close.
