### ISSUE TITLE
Convenience ui buttons

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5359]
Need a preference option to make these verbs show up in a collapsible movable hud ui button or wasd shortcuts added for: Remove id/pen/accessory, show held item, toggle suit sensors, give, resist, sleep, note, and add note.

Bonus if you can implement #5206 and add it to give, and add it to ui buttons for:
Examine, pick up, pull, move to top, flip table, rotate chair/window, point to, and check pull.

Super extra awesome bonus if you can figure out how to have objects that add new verbs add generic 'special function' buttons, and have click targetting if they have a target requirement.

**Comment by ririchiyo** [comment]
Ideally the entire UI needs to be completely redone along with how inventory works.

**Comment by Kurfursten** [comment]
Eject pen should honestly be on the PDA menu to reduce verb clutter

**Comment by Midaychi** [comment]
Bluh but then you'd have to actually keep the pda window open and have it stealing focus all the time or getting in the way. What if you just want a convenient id/pen holder. It's not like pocket protectors are a thing.

**Comment by Kurfursten** [comment]
Labcoats store your pen in their storage slot (which is a "pocket protector")

**Comment by Midaychi** [comment]
Who bothers wearing a labcoat?

**Comment by Kurfursten** [comment]
People who want a pocket protector
