### ISSUE TITLE
(WEB REPORT BY: cumoverme REMOTE: 198.245.63.50:7777) Tomatoes are fruits and not vegetables

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5363]
>Revision (Should be above if you're viewing this from ingame!)
What

>General description of the issue
At the megaseed servitor, tomatoes are listed as vegetables. They are fruits.

>What you expected to happen
To see tomatoes on the fruit section.

>What actually happened
It is on the vegetables section.

>Steps to reproduce if possible
Click on a MegaSeed Servitor.

**Comment by Exxion** [comment]
Biologically, even pumpkins are fruits. Fruit and vegetable are not mutually exclusive as botanical terms.
Tomatoes are vegetables culinarily. Do you want a tomato-based fruit salad?

**Comment by Intigracy** [comment]
A smart man knows a tomato is a fruit. A wise man doesn't put a tomato in a fruit salad.

Exxion put it best.

**Comment by Intigracy** [comment]
Can we close this one?
