### ISSUE TITLE
Ticklag Formula reversed?

### ISSUE THREAD

**Issue by Fox-McCloud** [d3athrow/vgstation13#5366]
In the process scheduler it defers for 1/10th of a second, regularly---a change was made by @d3athrow to adjust this based on ticklag--the formula is as follows:

#define calculateticks(x) x / world.tick_lag

When this formula is used, it's always has an input of 1...

Doesn't this end up making things sleep for *longer* than they need to? That is to say, if you had ticklag of 0.5, then it would defer for 1/0.5 or...well, 2 deciseconds...meaning...well, wasted processing power.

Wouldn't you want this to sleep (or in updatequeues instances spawn) for world.tick_lag?

**Comment by clusterfack** [comment]
It's very possible

**Comment by PJB3005** [comment]
Oi vey we finally got around to fixing it.

Only 6 months late!

a9c7b6bb7cf7172f3170c2493b426eaeff095baa
