### ISSUE TITLE
Mommi wires and mmi popping

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5367]
I was on a round earliere where a roboticist managed to get ahold of a mommi, and had it opened and batteryless. You can use a screwdriver to reveal the wires, but you can't use a multitool or a wirecutter to open the interface.

I guess not as much of a problem normally, except in order to pop a positron or mmi out of a cyborg, you have to cut all their wires first and then crowbar it out.

If that feature doesn't actually exist on vg, could it get added?

**Comment by Ephx1** [comment]
It is a feature on /vg/, but for MoMMIs wire interaction is messed with.
