### ISSUE TITLE
(WEB REPORT BY: myroc REMOTE: 198.245.63.50:7777) Can't finish Space Pod Construction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5372]
>Revision (Should be above if you're viewing this from ingame!)
e08b54ced34d31987ace376f3bad692617849c99

>General description of the issue
You can't finish the construction of space pods as the last step (welding the armor to the pod) doesn't work.

>What you expected to happen
Being able to weld the pod to finish it.

>What actually happened
I hit the pod with my welder like a retard.

>Steps to reproduce if possible
Follow all the steps of building pods. Step 19 (welding the armor to the pod) should not work.

I've also been told that H.O.N.K construction is also similarly broken (can't finish the last step), though I don't have any personal experience with this.

**Comment by PJB3005** [comment]
I can confirm this doesn't work, I've tested it but I can't figure out why it's broken.

**Comment by Intigracy** [comment]
Fixed

**Comment by clusterfack** [comment]
Are you sure?

**Comment by 9600bauds** [comment]
Fixed
