### ISSUE TITLE
pAIs post-wiping have invisible ghosts

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#5373]
I wiped myself after checking the DNA of a newer carrier and finding to to be false, but then I found my ghost to be completely invisible except when my tile is right-clicked. Is it because there isn't any sprite to transfer to the ghost?

**Comment by clusterfack** [comment]
I think it uses getflaticon to make a ghost sprite, but the mob/living/silicon/pai doesn't even have an image I believe. The only thing you see ingame is the device.

**Comment by Wizardcrying** [comment]
Is it fixable with how a pAI works?

**Comment by clusterfack** [comment]
Yeah I think so

**Comment by PJB3005** [comment]
Everything is fixable.

How hard that could be is a different story.

**Comment by Kurfursten** [comment]
I'll fix this in the next revision of #4866
