### ISSUE TITLE
(WEB REPORT BY: intigracy REMOTE: 198.245.63.50:7777) Misplaced plastic flaps (box)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5374]
Revision: 0ab3a1198908b99f15d98e4b0a4b7f05f2b17978

![](http://puu.sh/j0N1M/83d84ce9fa.png)

**Comment by Intigracy** [comment]
Nevermind, apparently you can move plastic flaps.

I'm dumb.
