### ISSUE TITLE
(WEB REPORT BY: maddoscientisto REMOTE: 198.245.63.50:7777) Device analyzer can't unload items in the reverse engine

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5377]
Revision: 0ab3a1198908b99f15d98e4b0a4b7f05f2b17978 

>General description of the issue
I can't unload scanned items on the reverse engine neither from an analyzer nor from a pda, machine designs work fine but for example circuits don't.
Also the queue is empty and it's not doing any reversing.

>What you expected to happen
I expected the designs to unload in the machines and be available for printing

>What actually happened
nothing

>Steps to reproduce if possible
scan a circuit and try to load it in the reverse engine

**Comment by PJB3005** [comment]
related to #5345 possibly?

**Comment by Probe1** [comment]
I'm not sure how.  I've seen this reported several times but been in the same round as one of the reports and personally used the reverse engine successfully.  I have never run into the problem people report here and elsewhere.

**Comment by Exxion** [comment]
I don't think that's the issue you meant to link, PJB

**Comment by PJB3005** [comment]
whoops

**Comment by MaddoScientisto** [comment]
I thought it got fixed because it didn't happen again.

Anyway the reverse engine always had everything fully researched so there was no full queue, I'm sure of that

**Comment by 9600bauds** [comment]
Was caused by some hubbub about the Reverse Engine having a heart attack when presented with designs that could be made at another fabricator, I fixed it already
