### ISSUE TITLE
Destroying something that's smoothwalling with something else doesn't make the other thing update it's sprite.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5384]

**Comment by Exxion** [comment]
Isn't there already an issue about this somewhere in the depths of Github?

Personally, I think it should stay that way for violent disassembly (explosions, drills, acid, etc.), but should update if the wall is deconstructed, but that would probably be much harder to implement than it sounds

**Comment by clusterfack** [comment]
It's very easy to have it smoothwall, but it's doing it efficiently and without needing many many updates during an apocalypse event like a singuloose or cascade or bomb that's difficult.

**Comment by d3athrow** [comment]
most likely intentional to reduce lag during singuloose and whatnot.

**Comment by Exxion** [comment]
But if it only updates adjacent walls when a wall is manually deconstructed, then singuloose, etc. wouldn't cause (more) lag.

**Comment by Zuhayr** [comment]
Couldn't you just pass it an arg to skip smoothing if it's being eaten during the apocalypse?

**Comment by Intigracy** [comment]
#4788 dupe, but this one includes that it's all smoothing objects instead of just walls.
