### ISSUE TITLE
(WEB REPORT BY: intigracy REMOTE: 198.245.63.50:7777) Removing a lantern from the wall rotates the lantern holder

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5393]
>Revision (Should be above if you're viewing this from ingame!)
70de6fd986f0ee7b1dc5af54d080743fa1a9334c

>General description of the issue
See title

>What you expected to happen
The wall mount to stay still

>What actually happened
It rotated

>Steps to reproduce if possible
Click wall mounted lantern with empty hand

1) http://puu.sh/j2kLD/6796bb115e.jpg
2) http://puu.sh/j2kMp/acd30315c7.jpg

**Comment by PJB3005** [comment]
Found the issue, the code for removing a lantern passes a dir onto the new empty lantern hook's new...

But the lantern hook/New() isn't coded to handle the dir passed down...

Damnit @dylanstrategie
