### ISSUE TITLE
Upon relogging I could see pipes underneath floor tiles while unconscious inside cryo

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5395]
Again with a picture.  This was tied to https://github.com/d3athrow/vgstation13/issues/5394 .  

![crab_office_lambda_2015-07-17_05-05-13](https://cloud.githubusercontent.com/assets/8550416/8744684/0dff7bc2-2c47-11e5-9846-ab948f2c5c63.png)

When I attempted for the second time to relog and upon rejoining I found that I could see the insulated pipes that make up cryo while unconscious inside of cryo.  

[05:06:37] <clusterfack> @ComicIronic  may have some kind of
[05:06:40] <clusterfack> weird ventcrawling code
[05:06:44] <clusterfack> since cryo is a type of pipe

**Comment by ComicIronic** [comment]
This would be that, yes.
It comes from the login code, that readds the ventcrawling images when you start in a pipe.
I'll see of a way of fixing it, but it might be messy.
