### ISSUE TITLE
Crewcut hair sprite is incredibly inconsistent

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#5398]
It's east sprite is different from its west sprite, and the east and west sprites have the hair being TALLER than its south sprite.
So basically, East sprite has the hair on the forehead, West sprite has the hair just slightly behind the forehead, South sprite has it being shorter than both East and West.
EDIT: 
![horribad](https://cloud.githubusercontent.com/assets/6224074/8758897/3a979ffe-2cb8-11e5-9348-2801b784dc03.png)
A terrible screenshot to go with my terrible explanation

**Comment by Unfit** [comment]
JUST
