### ISSUE TITLE
Medborg dropper bug

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#5400]
If a medborg uses a dropper on you, not sure where they targeted but I'd assume it's the eye but this bug may be if you are targeted otherwise, it injects the chemicals no matter what.

I was wearing both a hardsuit helmet and a gas mask and got the message 

"Cyrridven tries to squirt something into Unknown's eyes, but fails!"

and seconds later, I was unconscious

Fix bug aboose post haste

**Comment by Kurfursten** [comment]
Yeah, the mediborg beamer needs fixing too. The AI can fill the beaker remotely if the borg leaves it in the chemmaster
