### ISSUE TITLE
(WEB REPORT BY: alone REMOTE: 198.245.63.50:7777) Xenoarch Strange Rocks are empty

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5402]
>Revision (Should be above if you're viewing this from ingame!)
dbd28d4f05b5ab370dde99694fc24f6f167a210b

>General description of the issue
When you open a strange rock with a welding tool, it says it reveals something, but the item is gone.

>What you expected to happen
When the lit welder is used on the strange rock, it should reveal a small artifact.

>What actually happened
Nothing was revealed, despite text saying it revealed an item.

>Steps to reproduce if possible
Use a welder on a strange rock from Xenoarch

**Comment by AutismSpider** [comment]
some items that don't have icons.
