### ISSUE TITLE
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 198.245.63.50:7777) Hivelord remains

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5406]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

Killed a hivelord it didn't "die" and spawned hivelord remains constantly

>What you expected to happen
It dies and spawns one remain not stay alive and spawn a new set of remains every step.

>What actually happened

Its remains kept moving even when the sprite changed to dead and spawned a remains until I notified the admins.
>Steps to reproduce if possible

Not sure but I killed it in a 1tile wide tunnel with a diamond drill

**Comment by clusterfack** [comment]
Oh boy, that's fun
