### ISSUE TITLE
(WEB REPORT BY: shiggypiggy REMOTE: 198.245.63.50:7777) Broken glass affects people in wheelchairs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5407]
>Revision (Should be above if you're viewing this from ingame!)

41d7df01fd9184f38eeb3d57fbd17bcdd95f706b

>General description of the issue

People without shoes can still get hurt while driving over broken glass shards in wheelchairs.
>What you expected to happen

For that not to happen, of course.
>What actually happened
Brute damage like the damage you get from walking over glass/being dragged over glass
>Steps to reproduce if possible

Get a wheelchair
Take off your shoes
Break a window
Drive over the glass shards

**Comment by Unfit** [comment]
Extension of #5225
