### ISSUE TITLE
Someone fucked up canisters

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5411]
![2015-07-18_06-29-44](https://cloud.githubusercontent.com/assets/8550416/8761273/6f80fc3e-2d16-11e5-9e76-3a23b96c20fc.png)

>undefined kPa 
>can't be changed

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/machinery/atmoalter/canister.dm#L311

**Comment by PsiOmegaDelta** [comment]
Your NanoUI canister.tmpl file uses "releasePressure" for that particular value (note the capital P). Unsure if Nano is actually case-sensitive but if so that would explain it.

**Comment by PJB3005** [comment]
Nano is case sensitive, but I can't think of anything that would change this and cause this.

**Comment by Probe1** [comment]
JUST
