### ISSUE TITLE
(WEB REPORT BY: sonixapache REMOTE: 198.245.63.50:7777) Radio-enabled MMIs have an incorrect itemname after use

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5412]
>Revision (Should be above if you're viewing this from ingame!)
c0be34f456787d35f7d09b542f2bb4531966a062 

>General description of the issue
When a brain is taken out of a radio-enabled MMI, the name of that MMI reverts to 'Man-machine interface' rather than 'Radio-enabled man-machine interface'. The description of the item is not affected.

>Steps to reproduce if possible
Put a brain in a radio mmi and pull it back out

**Comment by clusterfack** [comment]
See now this is one of the times when you use initial!
