### ISSUE TITLE
Newscasters on box are no longer on walls

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#5413]
>Revision (Should be above if you're viewing this from ingame!)
c0be34f456787d35f7d09b542f2bb4531966a062 

>General description of the issue
![dreamseeker 2015-07-18 14-14-10-988](https://cloud.githubusercontent.com/assets/8468269/8761680/51e60032-2d5e-11e5-97ec-575375b59cd4.jpg)

**Comment by PJB3005** [comment]
#5389

**Comment by ComicIronic** [comment]
Kurfurst too lazy to map.

**Comment by Kurfursten** [comment]
@ComicIronic I just did two PRs to fix Taxi, the map you gave up on fixing, Mr. Lazy.

Needs to be more specific though, as in which Newscasters are floating

**Comment by AutismSpider** [comment]
just fix box no one gives shit about defic and meta is rarely played

**Comment by ComicIronic** [comment]
>give maps which aren't played a reason to not be played

Not such great logic.

**Comment by AutismSpider** [comment]
two maps that are barely play one of them is meme at this point

**Comment by Probe1** [comment]
not a spider bringing the truth
