### ISSUE TITLE
Fabricators should grey out things that can't be made.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5414]

**Comment by Probe1** [comment]
That would be very slick.

**Comment by ririchiyo** [comment]
This could actually be done pretty easily using javascript I believe since all the information needed is passed along via JSON.

**Comment by PJB3005** [comment]
Well yeah but then we need somebody which knows jscript...

**Comment by ComicIronic** [comment]
>2015
>not knowing jscript

**Comment by clusterfack** [comment]
The first step to wisdom is acknowledging that you know nothing

**Comment by d3athrow** [comment]
the only info that's passed about cost is a preformatted string. you'd have to send the construction coefficient and actual cost of each plan to the client to do the calculations on whether its buildable.

**Comment by PJB3005** [comment]
Passing down another thing to set if it's buildable would be possible.

Though in reality kill fab nanoUI because fuck the lag.

**Comment by ComicIronic** [comment]
Why make the client do the calc? Just have the fab check if the design is buildable, and then send that binary.

**Comment by clusterfack** [comment]
How about instead, we remove nano from this because it's laggy

**Comment by Imagebard** [comment]
This is already in isn't it

**Comment by PJB3005** [comment]
Nope.
