### ISSUE TITLE
(WEB REPORT BY: tomatolicense REMOTE: 198.245.63.50:7777) Exosuit Beacon not attaching

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5415]
>Revision (Should be above if you're viewing this from ingame!)
c0be34f456787d35f7d09b542f2bb4531966a062

>General description of the issue
Exosuit beacon will not attach to finished Ripley mech

>What you expected to happen
Attaching the beacon successfully

>What actually happened
Nothing

>Steps to reproduce if possible
1. Make full Ripley (using Diamond Mining Drill in this case)
2. Make Exosuit beacon to be best roboticist
3. Try to attach beacon onto finished mech

**Comment by ComicIronic** [comment]
Doesn't it start with one built in?

**Comment by SonixApache** [comment]
It does. Think he also didn't know that you have to open up maintenance mode first.

**Comment by Chronakai** [comment]
That was me, and yeah, I had no idea that Ripleys started with one or that you needed maint mode enabled. I'm not sure that the wiki covers exosuit beacon attachment for other mechs, but you guys can close this one.
