### ISSUE TITLE
(WEB REPORT BY: manfreed REMOTE: 198.245.63.50:7777) Squeek!

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5417]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Driving a janicart against a wall while ontop of a mouse results in Squeek! spam

>What you expected to happen
One squeek

>What actually happened
Many squeeks

>Steps to reproduce if possible
See description

**Comment by ComicIronic** [comment]
Is this really an issue?

**Comment by PJB3005** [comment]
There is a very real probability that #5378 fixed this.
