### ISSUE TITLE
Removal of rocky debris and strange rocks, xenoarch fixes

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5420]
Preface: We don't need them, and here's why:

**--Strange rocks**

When you excavate, the goal is to reach the exact center while the field is active at the right setting. This produces the small artifact without having to go through a strange rock. If you fuck up and miss, the small artifact either breaks or comes out as a strange rock.

Making 'it breaks' the only outcome would not detriment xenoarchaeology, because properly digging small artifacts out does not produce strange rocks, strange rocks have a failure break chance of the object inside, and strange rocks have no other use in xenoarchaeology besides some minor research levels and the ability to abuse a minor bug with them to locate large artifacts. (the bug is that the signal and range of a large artifact is set on the rock core when you core it, and you can carry strange rocks around and rock core them at will.)

And before you chime in, no you can rock core anywhere to locate large artifacts. You don't need to rock core strange rocks. The carrier fluid for a non digsite is silicon or something.

**--proposal for removing the rocky debris tile.**

Option 1, the 'maintain functionality' method:
Remove rocky debris, and instead make large artifacts come out of the mining tile when rocky debris would normally show up. Just require that the actual destruction of the mining tile be done through excavation tools, or it breaks the large artifacts. 
And no, mining with normal mining tools and getting rocky debris is and always has been 100% trolling people.

Option 2, the 'enhance consistency and difficulty' method:
Remove rocky debris, and instead make large artifacts consistent with small artifacts. That is, make excavating them work exactly like small artifacts. (As opposed to currently, where you just wail on the tile with a small mining pick till it pops out)

How excavating large artifacts would work with option 2:

Step 1: You find the unknown signature, but this time it actually has a depth and a material type and a radius.

Step 2: Now you need to figure out what the stats are, and then dig it out.

--- Sub-Option 1: The stats are hidden by interference from the depth scanner as they are now. You would have to get to the point where depth scanner is picking up an unknown artifact, then core the tile.

You then take this core sample back, prep it into a sample tray, You choose what sort of carrier fluid you think it might be, and add 1 unit analysis liquid and 1 unit carrier fluid into the sample tray.

You then run it through the ion mobility machine to see if you were right about the carrier fluid; if wrong, then go try another carrier fluid by removing the existing one with the chem master and adding a new one, if right, then proceed to the Fourier Transform spectroscope.

You then run the sample tray through the Fourier Transform spectroscope, which would have a special operating mode for when you take a core sample from the exact tile a large artifact is in; if the carrier fluid is correct it will tell you the core depth and the radius instead of the range.

Now, armed with both the carrier fluid and the core depth + radius, you can set up the field generator on the dig site, and dig the large artifact out as if it were a small artifact.

-- Sub-Option 2: The stats are no longer hidden by interference, and you can just get the information you need to dig it out via the depth scanner.

**--Fixes**

 Remove the chance to spawn huge stacks of materials when you break a small artifact, and make destroying digsites have a 75% chance to apply the effects of a random unknown artifact on the breaker. (especially if the effect is negative)
Blame it on residual xenoradiological energy. They're basically acting like anomaly batteries, but the charging took decades or centuries or more.

If sub-option 1 is too hard/tedious, could balance it out by making it easier to find artifacts, re: the first and second suggestions on #5285

**Comment by Probe1** [comment]
Old discussion.
