### ISSUE TITLE
Cannot construct ATMs anymore

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#5421]
> Revision (Should be above if you're viewing this from ingame!)
> 7b07afb3fc61b4da3b1813c23a25e88f432fc771 
> 
> General description of the issue
> You used to be able to construct ATMs with metal. This is no longer the case.
> Meaning that if some jackass deconstructs all the ATMs it's over for the QM.

**Comment by ComicIronic** [comment]
This is deliberate.

**Comment by Probe1** [comment]
Why was it removed?  It was useful.

**Comment by PJB3005** [comment]
because it was shit.

**Comment by ComicIronic** [comment]
The way it was done was lacking.

**Comment by Probe1** [comment]
That's okay then.  They got built more often than other mountables though.

**Comment by 9600bauds** [comment]
Removing this from the milestone seeing as it's just feature request at this point
