### ISSUE TITLE
Feature request: Put headsets on posibrains

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#5422]
Being a posibrain and not having access to radios is suffering. Biological brains can be put into a radio-enabled MMI, it's kind of a bitch that there's no way for posibrains to get that kind of ability.

**Comment by Probe1** [comment]
How about encryption keys from headsets?  That way you can cobble together a few channels.

**Comment by SonixApache** [comment]
@Probe1 That'd actually add a use for standard encryption keys.

**Comment by AutismSpider** [comment]
Well you can stick encryption keys into cyborgs

could do same thing with posibrains make them start with normal encryption key or put one in them later etc.

**Comment by ririchiyo** [comment]
Only if these are items that have to be researched and developed by science but not found in common-place headsets. There's a lot of problems with allowing people immediately back into a round with the ability to talk over the radio. pAIs are already bad enough.

**Comment by AutismSpider** [comment]
posbrains can't talk about past lives you know.
