### ISSUE TITLE
(WEB REPORT BY: theeliminator16 REMOTE: 198.245.63.50:7777) Newly Designated Area Lighting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5426]
>Revision (Should be above if you're viewing this from ingame!)
63d1c07ffc35d4427fed7145d0edacdcac216612

>General description of the issue
Areas designated from outer space using blueprints no longer automatically switch to simulated lighting.

>What you expected to happen
A room, made in space, and designated with blueprints, should go dark until a light source is brought in.

>What actually happened
Rooms designated from space are automatically lit, and light sources have no effect on this

>Steps to reproduce if possible
Make a room in space, designate it with blueprints.

**Comment by clusterfack** [comment]
"Thanks for letting me know, I'll try to fix it when possible", he said to the unhearing uncaring web reporter

**Comment by PJB3005** [comment]
This is sorta a weird one, I have had it happen where the lighting doesn't go dynamic, and I have had it happen where it didn't.

I'll look into it but I think the blueprints should be calling `lighting_build_overlays()` on the turfs that get added.

**Comment by d3athrow** [comment]
damn right i did @PJB3005

**Comment by PJB3005** [comment]
@d3athrow and I DID, except you reverted on a REALLY shit basis.

**Comment by d3athrow** [comment]
imblying

**Comment by PJB3005** [comment]
it's not implying.

Do you even UNDERSTAND baylights?

no you don't

did you do a proper profile?

no you didn't.

**Comment by d3athrow** [comment]
I know that with baylights with 25 people cpu usage was typically 60% of a core and with dal typical usage is ~20% of a core
