### ISSUE TITLE
(WEB REPORT BY: therealmrbillybob REMOTE: 198.245.63.50:7777) Janitor Closet Door

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5427]
> Revision (Should be above if you're viewing this from ingame!)
> Janitor Closet Door
> 
> General description of the issue
> The door is not purple
> 
> What you expected to happen
> The door to be purple
> 
> What actually happened
> The door is green
> 
> Steps to reproduce if possible
> Look at the janitor closet door
> 
> What to do
> Make the janitor closet door purple pls

**Comment by ComicIronic** [comment]
WHAT
FUCKING
MAP

**Comment by SonixApache** [comment]
box

**Comment by TheRealMrBillyBob** [comment]
Box, sorry.

Also, I expected it to be purple because I remember the days when the janitor closet used to be where mechanic's closet was.

**Comment by PJB3005** [comment]
AFAIK there is no purple airlock sprite.

There IS the one mechanics uses but that's purple on white and IMO the janitor closet should have a door with a dark background.

**Comment by TheRealMrBillyBob** [comment]
I was just saying it should happen because when the janitor's closet used to be where the mechanic's closet was, the door was purple.

**Comment by Intigracy** [comment]
I don't remember the janitor closet ever having a purple sprite, it's always used the current green one.

The only purple ones are the purple on white ones that science/mechanics uses.
