### ISSUE TITLE
Megaphones Bypass Silence

### ISSUE THREAD

**Issue by the-socks** [d3athrow/vgstation13#5430]
You can use a megaphone, like the one in the clown room to speak while silenced. Earlier today an evil wizard named "Mime Fuhrer" was terrorizing the station turning everyone into mimes with unremoveable mime masks! Thankfully I, Honk Master Flash, found that we we're able to communicate by speaking through a megaphone! 

I don't know shit but I think maybe the silence effect stops you from talking, but not "broadcasting", because when using the megaphone it says "X broadcasts:" instead a do of "X says:"

**Comment by Intigracy** [comment]
Caused because the mime spell doesn't currently set the miming var, it sets the muted var. And the megaphone doesn't check for the muted var, it checks for the miming and silent vars.

Hooray. Anyway I fixed it.
