### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Asteroid Lanterns [Box Station]

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5436]
Asteroid lanterns that are mounted on the wall dont light up the asteroid for some reason. When you try and put them back in the holders and take them out they're always turned to off. Please fix, thanks.

**Comment by PJB3005** [comment]
Thanks pomf with your revert

**Comment by d3athrow** [comment]
if only you had heeded my warnings

**Comment by PJB3005** [comment]
pomf, I did profiling, DAL IS A LOT more expensive than baylights, @clusterfack has my back on this.
