### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Unable to use beakers on monkey cubes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5437]
It is really fucking annoying and I would like to be able to do that so I dont have to go through the trouble of finding a fire extinguisher everytime I want to make a monkey.

**Comment by PJB3005** [comment]
I think a sink can be used but this should be possible nontheless

**Comment by Ephx1** [comment]
I wouldn't call this a feature request, you used to be able to do it, and now you can't apparently.

**Comment by 9600bauds** [comment]
Closing in favor of #6575
