### ISSUE TITLE
(WEB REPORT BY: iratepirate REMOTE: 198.245.63.50:7777) Energy sword has invisible in hand sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5439]
2867574f4774b4cf95b8dcf74b695a63c0cc42b3

The sword sprite cannot be seen when held in one's hands.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Probe1** [comment]
Metal and Glass in hand sprites are also missing.

**Comment by NigglyWiggly** [comment]
The syndi balloon inhand is missing too

**Comment by Probe1** [comment]
As are diamonds and uranium when wearing a hardsuit.

What the fuck happened

**Comment by Intigracy** [comment]
Did overlays get played with?
It may be that the suits are overlaying on top of the inhands if the problem only appears when wearing a hardsuit.

**Comment by clusterfack** [comment]
The PR that caused this was just reverted
