### ISSUE TITLE
(WEB REPORT BY: aceedex REMOTE: 198.245.63.50:7777) Can't stop pulling objects

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5440]
>Revision (Should be above if you're viewing this from ingame!)
2867574f4774b4cf95b8dcf74b695a63c0cc42b3 

>General description of the issue
If I pull anything, It doesn't stop following me

>What you expected to happen
I be able to stop pulling something by pressing the let go button

>What actually happened
After I decide to pull something the let go button never appears

>Steps to reproduce if possible
No idea

**Comment by Exxion** [comment]
Just press the delete key like a normal person

**Comment by Kurfursten** [comment]
Unless someone can reproduce this, I would say let's close it? @clusterfack @PJB3005

**Comment by clusterfack** [comment]
Yeah it's also really old and I've never heard of anyone else with this issue
