### ISSUE TITLE
(WEB REPORT BY: buxus REMOTE: 198.245.63.50:7777) Neurotoxin does literally nothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5445]
>Revision (Should be above if you're viewing this from ingame!)
54a563cb0df1e76337ebae4745114cef7488fad9

>General description of the issue
As an alien sentinel, when I spit neurotoxin at humans without a helmet or mask it would not take effect.  I tried on four separate targets with the following strategy - 1. spam disarm and remove helmet/mask if necessary, 2. spit neurotoxin, 3. disarm to knock down again, 4. begin to eat target, 5. target gets up and picks up his laser gun and shoots me.  

>What you expected to happen
Humans get rekt

>What actually happened
Aliens get rekt, neurotoxin does literally nothing.

>Steps to reproduce if possible
(try to) use neurotoxin

**Comment by BestName** [comment]
What the fuck are you on about? Neurotoxin literally does do something and seems to literally work just as intended.
![you are literally retarded](https://cloud.githubusercontent.com/assets/3892856/8812623/e06776f2-3005-11e5-96e9-a49a761cfd84.gif)

I think you might literally have brain problems.

**Comment by AutismSpider** [comment]
it stunned longer then that

**Comment by BestName** [comment]
You can't see the duration of the stun in that GIF since it cuts off before the mime gets up.

**Comment by Intigracy** [comment]
Works fine.
