### ISSUE TITLE
Borers issues

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#5448]
# The good
* Not being able to hear/speak in borer chat while assuming direct control over someone gives you a reason to not 100% of the time be assuming direct control, and adds a drawback to doing so.
* Taking a few seconds to be able to insert yourself into people is fine, it shouldn't be instantaneous.
* Being able to kill your host and give them a reason for killing them is great.

# The bad
- [ ] Borers start the round already assuming direct control over their host. 
   * Generally this leads to players believing their borer is a shitter and yelling over the radio the first chance they get.
- [ ] Borers have no objectives / antagonist status, so don't even appear on round end report.
- [ ] The host cannot understand the borer's speaking if they are assuming direct control over the body. 
   * This probably has to do with language crap.
- [ ] You cannot see emotes of the body you are in.
- [ ] There is no HUD for infected people. The icon appears for yourself when you're assuming direct control, but beyond that there's nothing.
- [ ] Reproducing has no cost nor cooldown
- [ ] There is no obvious feedback that you have to use ; to talk on borer hivemind chat.

# The eh
* Borers being able to synthesize chemicals in their host is a great idea, I just think that they should be able to synthesize more chemicals if they come into contact with them in borer form.
   * E.G. a borer finds a beaker with tricord in it, pops out of its human form to dip its tentacle shit into the beaker, tada, it can synthesize tricord now.
   * Maybe have a max number of chemicals.
* It seems way too easy to be able to get a borer out of you. 
   * I think we should go with the sugar route or the surgery route, but not both. 
   * Trying to do borer removal surgery on someone with a borer assuming direct control should kill them in the process as a downside.
* The feedback for borers trying to reproduce without any available ghosts is really vague.
* Whether or not your host is damaged when you reproduce is not explained.
* Borers should be able to retain the ability to infest nonhuman mobs, but should only be able to reproduce using humans.

**Comment by AutismSpider** [comment]
boeres can infest monkey mobs and its sub types.

massive risk of death using a baby diona you get push out on there evolution.

**Comment by SonixApache** [comment]
someone said make borers a ling power
that'd be pretty cool

**Comment by Livewire2440** [comment]
I say remove direct control altogether, make the dynamic be that the borer could easily kill the host at any time (perhaps leaving uncloneable remains like a husk?) but have it be more favourable for the borer to keep the host alive so its in the hosts favour to listen to the borers commands and in the borers favour to keep the host alive. Perhaps award points to the borer for the length of time they remain inside a host allowing them to upgrade new abilities that could benefit both the host and the borer? Also allow the host to communicate with the borer by 'thinking' to get around the issue of a mime being borerered.

**Comment by Intigracy** [comment]
https://gitlab.com/vgstation/vgstation/issues/49
