### ISSUE TITLE
(WEB REPORT BY: blarghargin123 REMOTE: 198.245.63.50:7777) Firebird not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5451]
>Revision (Should be above if you're viewing this from ingame!)
506f971ae6a5316782fe8bbd8f486b4c1716d80c

>General description of the issue
Wizard's Firebird not properly phasing through walls

>What you expected to happen
Wizard to phase through walls

>What actually happened
He didnt

>Steps to reproduce if possible
Test your shit before a merg

Also, I was observing the wizard when this happened, so this could be a one time event.

**Comment by Shadowmech88** [comment]
Firebirds no longer phase through walls, haven't for a long time.
Firebird's new thing is that it can pass through airlocks instantly without waiting for them to fully open, assuming you have access to the airlock.

**Comment by NigglyWiggly** [comment]
>assuming you have access

Then what the hell is the point

**Comment by Shadowmech88** [comment]
@NigglyWiggly 
It gives you a straight speed upgrade when being chased by people in areas such as the hallways, since they have to wait for the airlocks to fully open and you don't.

**Comment by clusterfack** [comment]
Well this was fun
