### ISSUE TITLE
Cyborgs Unable to Use Microwaves

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5453]
In particular I'd like this for Service Borgs, since it would enable them to cook simple dishes that don't require solid reagents, such as bread.

**Comment by AutismSpider** [comment]
Give the service borg a bag to grab food reagents or a claw so they can grab food items to cook with.

**Comment by Shadowmech88** [comment]
I wouldn't be opposed to that, but that would allow them to completely replace the chef, which would be an issue for discussion. They've already got the ability to completely replace the bartender.
Maybe give borgs the ability to use microwaves in general, and then add an upgrade module to Robotics that gives them a plant bag and a knife.
