### ISSUE TITLE
Alt+Click Doesn't Work Correctly For Silicons

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5459]
As a vox/diona/human/skeleton, if you alt+click an object, it pulls up the list of everything that's on that tile.
As a silicon, it only pulls up the list if you alt+click on the floor. Alt+clicking an object does nothing. This means that if the tile has a 32x32 object, it's impossible to click on the floor, and so impossible to get the list for that tile. In general, it just makes things more difficult on cluttered spaces because you have to pixel hunt.

**Comment by Intigracy** [comment]
This is because silicons have the alt click to shock for airlocks, which are an object.

**Comment by Shadowmech88** [comment]
Would it be possible to just have a check for whether the thing they're alt+clicking is an airlock or not?
MoMMIs are able to use alt+click to ventcrawl despite also being able to shock doors.

**Comment by clusterfack** [comment]
Yes it would

**Comment by ComicIronic** [comment]
This is fixed in #5332, and is to do with sillycones not inheriting alt-click behaviour, I believe.
