### ISSUE TITLE
(WEB REPORT BY: sarahjohnson REMOTE: 198.245.63.50:7777) Blind overlay is offset

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5467]
>Revision 4359258f6892b9b4a97a22054e9371f6ae6ad97c 
Blind overlay is offset. Pici n a sec

**Comment by SarahJohnson489** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5564796/8827358/c1a78fa8-3038-11e5-8a9b-ff11bf716d3d.png)

**Comment by ComicIronic** [comment]
Do you have farsight?

**Comment by PJB3005** [comment]
@ComicIronic, it looks like it

**Comment by ComicIronic** [comment]
Then this is a duplicate issue, I believe

**Comment by Exxion** [comment]
Yes, but the other issue has fallen back so far that it might make more sense to leave this one open and close the old one

**Comment by ComicIronic** [comment]
That's not how issues work, and it makes older issues harder to track.
