### ISSUE TITLE
(WEB REPORT BY: sonixapache REMOTE: 198.245.63.50:7777) Jetpacks don't work when equipped in suit storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5468]
>Revision (Should be above if you're viewing this from ingame!)
4359258f6892b9b4a97a22054e9371f6ae6ad97c

>General description of the issue
A carbon dioxide jetpack placed in the suit storage of a miner hardsuit does not function as a jetpack. It shows the particles when turned on, but doesn't provide any thrust.

**Comment by PJB3005** [comment]
Doesn work on any slot except backpack.

Also, the particles still appear when the jetpack is inside a backpack or such.

**Comment by Probe1** [comment]
I'm surprised he didn't gas himself by trying this.

**Comment by Intigracy** [comment]
close please
