### ISSUE TITLE
(WEB REPORT BY: sonixapache REMOTE: 198.245.63.50:7777) Safe cracking is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5469]
>Revision (Should be above if you're viewing this from ingame!)
4359258f6892b9b4a97a22054e9371f6ae6ad97c

>General description of the issue
Trying to crask a floor safe with can bug out when you fuck up, causing the safe to make a noise every time you move the dials.

>What you expected to happen
The safe to make a noise at the right dial

>What actually happened
The safe made one noises per turn, then two noises per turn

>Steps to reproduce if possible
Attempt to crack a safe (with a stethoscope) - try to open the lock when on the right dial, then turn the lock some more and try to open it again.

**Comment by 9600bauds** [comment]
Judging from the description, it's working as intended. Will test tomorrow.

**Comment by PJB3005** [comment]
Yeah I looked at safe code trying to crack one I found on the asteroid once (it was apparently empty).

IIRC there's code so that it makes a sound even on non-dials, they're different sounds though.

**Comment by 9600bauds** [comment]
I can confirm safecracking is working as intended.
I won't say how to do it, though.
