### ISSUE TITLE
Requests and Cargo Console Quality of Life Changes

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#5471]
So, the idea is to change the printouts from the Requests Console and Cargo Computer. I have the code changes ready on a older build, but essentially what it does is change the title of the Request paper (Request of [Crate X]) to include the requester's name and title (if applicable) (Request of [Crate X] for [Person Y, Title Z]), so when it's attached to a clipboard or filing cabinet, you can see at a glance what is for who without having to take them out of their container and read them individually. It's a real pain when you have large orders from multiple people, and don't have time to sift through all the requests to see who's getting what. And of course, it gives Sec easy evidence when someone is running around, forcefeeding people monkey cubes.

Also, the Shipment Manifests that spawn in the containers would be altered to show the requester's name, for cases when there's several shipments of similar items for multiple people, and replacing the flavour text of (Shipment of [Crate X] for [Station XYZ]) with something more relevant: (Shipment Manifest of [Crate X] for [Person Y]). 

I left out the Title field in the Shipment Manifest because it gets long winded, but it's easy to put back in if that's not an issue. I will get screenshots posted of the differences tonight once I've pulled a more recent version of the codebase. The changes only affect Supply.dm.

**Comment by PJB3005** [comment]
Don't see why you'd need to make an issue for your code changes, you can just make a PR with the description.

**Comment by Cyadox** [comment]
Oh. I was told to make an issue when I posted on the forums. Should I move this, or...?

**Comment by PJB3005** [comment]
Well, I guess whoever said that on the forums didn't catch that you already coded the changes.

also you can't change an issue into a PR so just close this and then make a PR.

**Comment by Cyadox** [comment]
Done and done. I'll have the PR up once I've figured out how to make my own branch.

**Comment by PJB3005** [comment]
If you need help just ask on the IRC channel.
