### ISSUE TITLE
(WEB REPORT BY: konater REMOTE: 198.245.63.50:7777) Taxistation robotics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5472]
Currently missing a cautery, disposal bin, proximity sensors, paper bin, bodybags, medkits for medibots. Only contains one stack of metal when it's the department that arguably eats the most of it during a round. Roboticists cannot enter the maintenance tunnel behind it either and have no very easy access to a fuel tank as a result

**Comment by ComicIronic** [comment]
Are you sure the bodybags aren't just under the table like normal, and what do they need cautery for?

**Comment by Konater** [comment]
Cautery is for limb replacement, butt removal and brain transplants

**Comment by ComicIronic** [comment]
So,  surgery's job?

**Comment by Konater** [comment]
Sure I guess
