### ISSUE TITLE
(WEB REPORT BY: awsmnamedude REMOTE: 198.245.63.50:7777) crew monitor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5474]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
when the "new" crew monitor changes Z levels a few times it completly stops working. 

>What you expected to happen
the Z levels to transition smoothly

>What actually happened
after about 3 changes in Zlevels the window closed and I cannot view the monitor anymore.

>Steps to reproduce if possible
check the crew monitor and try to change Z levels repeatidly

**Comment by Ephx1** [comment]
What a serious issue, reported four whole times!
