### ISSUE TITLE
Ore belt in taxistation doesn't work properly

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#5478]
The conveyor corner leading to the unloader from outside is inverted. This is, if a crate comes from the start of the line, it gets pushed back when it reaches the corner.
The unloader still manages get the ores from it.

![10 hours in paint](https://cloud.githubusercontent.com/assets/13305885/8842501/5d3a0f0c-30d1-11e5-8b96-01b6eb56a997.png)

Now inside, the conveyor under the plastic flaps doesn't move at all, and it's needed to move a crate under the flaps or remove them to get the ores.

![100 hours in paint](https://cloud.githubusercontent.com/assets/13305885/8842520/934893e8-30d1-11e5-8ece-b2a5a8664155.png)

It might be late for the big taxi-fix, but taxi never wins the vote and the ore ~~processor~~ redemption machine wasn't kill back then.

**Comment by Intigracy** [comment]
Yes it was, nobody used it because we had the ore redemption machine though.

**Comment by ihadtoregisterforthis** [comment]
Oops, name mistake, I meant the redemption machine.
