### ISSUE TITLE
Update travis.yml to use the new container based infrastructure. 

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5480]
Who doesn't want sanic travis times?

**Comment by 9600bauds** [comment]
Needs Moar Info

**Comment by PsiOmegaDelta** [comment]
https://docs.travis-ci.com/user/workers/container-based-infrastructure/
The first paragraph basically summarizes what it's about:
- Faster startup times.
- You can cache files and folders (like the BYOND installation).
- The price is that you lose the ability to use sudo and related features.

You can find a container-based example here: https://github.com/Baystation12/Baystation12/blob/dev/.travis.yml

**Comment by PJB3005** [comment]
#7823
