### ISSUE TITLE
spawned targeted injectors don't work.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5489]
I'm talking ones like `/obj/item/weapon/injector/runfast`

They don't give you the correct block.

**Comment by clusterfack** [comment]
Is this real life

**Comment by ComicIronic** [comment]
They do work, the issue is in block activation chance and the slim mutation chance.

**Comment by Shadowmech88** [comment]
Would it be possible to just make the spawned ones be guaranteed to give the power and never randomly mutate?
