### ISSUE TITLE
Floating Newscaster Reporting

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#5490]
I recently pushed a PR that makes newscasters place properly on a wall instead of float when created. This is generally a good thing, except that our existing maps had very hacky newscaster placement -- meaning that some of them did not play nice with this new code and are now floating.

In order to hit them all in one go, I need a list of which newscasters are floating, because they won't be easily visible in the map editor. Please be specific. In the mean time, you can simply fix newscasters in-round with a screwdriver.

Known floating casters:
**Box**
* Escape (south wall)
* R&D (west wall)
* Bridge (south wall)

**Comment by Probe1** [comment]
[15:37:57] <probe1> kurfurst just hit observe right now and you'll see the newscasters that are fucked up
[15:38:02] <probe1> they're hard to miss
[15:38:12] <probe1> research medbay dorms hydroponics off the top of my head
[15:38:16] <probe1> RnD*
[15:38:59] <probe1> o he quit

**Comment by Kurfursten** [comment]
Need more detail on locations, those are pretty vague

**Comment by Probe1** [comment]
.. i'm not sure if you're serious.

http://imgur.com/a/Vkv50  misaligned newscasters on box.  3 minutes of going around in game and hitting print screen.

**Comment by Kurfursten** [comment]
I'll leave the issue open a while to see if any other floaters get found

**Comment by Intigracy** [comment]
Well here's an issue with mapping them in the first place:

![](http://puu.sh/jaoox/93984dd9a1.png)

![](http://puu.sh/jaoqV/ea590adaf7.png)

**Comment by Kurfursten** [comment]
Yeah, you can't fix it like that because it gets its positioning from New()

If you want to fix it mid-shift you should use a screwdriver and put it on the wall again, so it calls New()

**Comment by Intigracy** [comment]
Why does New() flip its dir from what's already on the map?

Because that's what's happening.

**Comment by Kurfursten** [comment]
Because if it didn't flip the dir more newscasters would be floating

All of the newscasters that aren't floating right now (hallways, bar, etc) use an inverted dir

**Comment by Intigracy** [comment]
Why didn't you just fix the issue by making the newscasters work the same as intercomms / request consoles / fire alarms / apc's / air alarms / light switches / buttons / most everything else that's wall mounted?

**Comment by Kurfursten** [comment]
I did, that's what broke them, because the ancient mappers didn't anticipate that I would be adding construction code for them later

**Comment by Intigracy** [comment]
So if I put a newscaster on a wall north of a tile via placing it on the floor, editing the pixel y to 28 and the dir to 1, will it be in the right place?

Because that's how everything I just described works, except shit like buttons don't have the dir var set.

**Comment by Kurfursten** [comment]
We just discussed how the dir is inverted, if you want to ask me rhetorical questions you can do so over Byond or reach me via IRC.

**Comment by Intigracy** [comment]
>Because if it didn't flip the dir more newscasters would be floating

Please find me one newscaster that isn't floating (that isn't the warden's that is edited to be in a corner originally) as a result of this much needed dir flip.

**Comment by Kurfursten** [comment]
I'll give you two, the bar and the hallway near tool storage. That's just off the top of my head without even looking.

**Comment by Intigracy** [comment]
I see.

Are you going to reverse the dir flipping when you get around to fixing the map?

Why didn't you just add a newscaster assembly item to not have this problem in the first place, and to keep it in line with all the other wall mountables?

**Comment by Kurfursten** [comment]
Newscasters are a copyrighted design, if we build them on station it infringes on the patent. You have to order them in from Cargo then screw them onto the wall.

**Comment by Intigracy** [comment]
I still don't see how you couldn't make it its own small item to slap onto the wall / screwdriver to avoid this whole snowflake issue it's having.

Deconstructing would be as simple as screwdriver + crowbar.

**Comment by Kurfursten** [comment]
You could, there's nothing stopping someone from coding that.

**Comment by clusterfack** [comment]
If you are going to change them make them consistent with all the other wall mounted ones otherwise there is literally no point

**Comment by Kurfursten** [comment]
I thought the point was to make them stop floating, but if you really think I shouldn't fix it, I won't.

**Comment by Probe1** [comment]
Is everything okay?
