### ISSUE TITLE
MoMMI taxi nest isn't hooked up to the grid

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#5492]
Literally one wire off, in the middle of the two windoors that lead to space.
I also had an issue with a nameless item slamming into walls, but I don't know what caused that.

**Comment by Intigracy** [comment]
Which map?

**Comment by Ephx1** [comment]
"MoMMI taxi nest isn't hooked up to the grid".
T-taxi?

**Comment by Intigracy** [comment]
I'm dumb, disregard.
