### ISSUE TITLE
Taxi telecomms isn't hooked up to the grid

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#5493]
This one is weird, it uses a SMES but it doesn't seem to be useable with at all.  So we have the one APC in the room hooked up to a dead SMES and nothing else, naturally it stops power flow. I don't think the SMES is hooked up to anything else regardless.

**Comment by PJB3005** [comment]
I think this was JUST fixed, also it's a dupe, I already reported it

**Comment by Ephx1** [comment]
Really? My bad then.
