### ISSUE TITLE
[Taxi] Tcoms

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#5495]
SMES doesn't appear to be interactable, might start with 0 charge? Also needs a suit so you can do maintenance without freezing.

**Comment by Ephx1** [comment]
I reported this in #5493. And supposedly PJB reported it before that. I'm so confused, is it fixed or not?

**Comment by Kurfursten** [comment]
The issue of it "not being hooked up" is fixed

The SMES is now hooked up, it's just glitched. No one -- admin or player -- could actually click it and get an interface.

**Comment by PJB3005** [comment]
Does it have a correctly connected terminal?

**Comment by PJB3005** [comment]
@Kurfursten does it have a terminal connection and everything?

@Ephx1 I assumed @Kurfursten properly fixed it but I guess that wasn't the case.

**Comment by Kurfursten** [comment]
@PJB3005 The issue is not with the SMES being hooked up, that was fixed properly.

The SMES itself is glitchy which is the source of the issue, it starts with 0 charge and you can't click it as an admin or a player. This wasn't reported by @PJB3005 or @Ephx1 .

**Comment by PJB3005** [comment]
@Kurfursten that's exactly what a disconnected SMES looks like.

**Comment by Kurfursten** [comment]
"Disconnected" means to me "not on any power grid", which it wasn't; no wires running to or from it at all. Please be more specific in your reporting.

**Comment by PJB3005** [comment]
Does it have a properly mapped terminal AND knotted wire underneath it?

**Comment by Kurfursten** [comment]
It currently a knotted wire but no terminal, I assumed there was one linked up to nothing under one of the machines because the reporting implied the only issue with the room was a lack of wiring to the APC, which I added

It has a terminal in the new revision I'm working on now, but this could've been fixed last revision with more specific reporting -- "I can't click the SMES at all" wasn't in any of the reports

**Comment by PJB3005** [comment]
SMES don't work if they don't have a terminal, I assume the people that reported it knew this.

That "person" is me btw

**Comment by Kurfursten** [comment]
I know that you know, the purpose of a report is to communicate that information to the person that doesn't know (e.g.: the person fixing the bug). We're veering off topic though, message received on what needs to be fixed.
