### ISSUE TITLE
Floating/misplaced newscasters

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#5501]
If this is a duplicate issue close it, and yes I know it's very obvious, but I'm going to say it anyways just because of how retarded it looks.

PLEASE FIX THE FLOATING NEWSCASTERS.

**Comment by mrpain666** [comment]
I didnt feel like going through nearly 30 pages of issues to find a duplicate. If you would prefer I will make an exact list of which ones need to be fixed, tomorrow.

**Comment by Intigracy** [comment]
It's fixed already.

**Comment by ComicIronic** [comment]
Github has an issue searcher.

**Comment by mrpain666** [comment]
Why yes it is fixed now. At the time of me posting this I dont think it was.
