### ISSUE TITLE
(WEB REPORT BY: evod REMOTE: 198.245.63.50:7777) Infinite E. Jaunt - Wizard

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5517]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
 Infinite Etheral Jaunt

>What you expected to happen
A timed, Shorter jaunt

>What actually happened
After Jaunting, I never came out of it, Making it last forever.

>Steps to reproduce if possible
I don't know if it will work, But how it happened was I stunned myself with my own fireball, Jaunted, and then it broke.

**Comment by clusterfack** [comment]
So yeah, apparently if you have a jaunt with a cooldown lower than the jaunt time, it goes into infini-jaunt.

**Comment by Ephx1** [comment]
Spectral Wizard. He jaunted so hard he ascended into a higher plane.

**Comment by Intigracy** [comment]
@Clusterfack didn't your jaunt adjustment fix this?

**Comment by clusterfack** [comment]
Some time ago, yes
