### ISSUE TITLE
New Etheral Jaunt.

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#5518]
So you can cast spells and do stuff mid jaunt.

with two/three points in jaunt lets say one  Ei Nath can jaunt all day and gib people nothing the crew can do to stop you they can't hit you as you jaunt all over into walls and you can keep casting jaunt over and over.

**Comment by Shadowmech88** [comment]
I also think the decision to change it was strange. If I remember correctly, jaunting used to prevent you from doing anything except moving.
Now you can run right through a room, steal whatever you want, and be gone before the jaunt even wears off, nothing anyone in the room can do.

**Comment by clusterfack** [comment]
Hm, well I can work to replicate that behavior

**Comment by AutismSpider** [comment]
old just was just you moving same thing with vamp jaunt.

means vamps can just and do stuff mid jaunt

**Comment by Intigracy** [comment]
Fixed
