### ISSUE TITLE
Kill nanoUIs built in click delayer.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5523]
nanoUI automatically ignores clicks if the click was too close to another.

This is on the javascript UI level because buttons in nanoUI aren't conventional `<a href=""></a>` buttons, they're the following:

``` HTML
<div unselectable="on" class="link linkActive hasIcon" data-href="">
  <div class="uiLinkPendingIcon"></div>
  <div class="uiIcon16 icon-power"></div>
  test
</div>
```

Now I don't look down on people who leak plasma anymore.

**Comment by ComicIronic** [comment]
I still look down on them.

**Comment by ihadtoregisterforthis** [comment]
Did #7208 look into this?
