### ISSUE TITLE
AME isn't properly connecting

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#5533]
Usually when you use a multi-tool on an AME bit, it'll connect albeit a bit slow.
It seems now that the AME doesn't always connect, even if the part it's supposed to be connecting to is already set up.
Although if you add more parts on it, sometimes it will update and the old unconnected parts are then snapped in place.

**Comment by Cyadox** [comment]
I can confirm this issue. There's a very noticeable lag after connecting more than 5-6 components. Sometimes if I used the multitool after the initial setup it'd connect them, other times I had to wait 30 or more seconds before they would finally registered as connected.

They will EVENTUALLY connect always, but beyond just a few takes forever it seems.

**Comment by Ephx1** [comment]
Fairly certain this is fixed now.
