### ISSUE TITLE
(WEB REPORT BY: crnibombarder REMOTE: 198.245.63.50:7777) tazers too op

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5534]
>Revision tazers too op

>General description of the issue
tazers one hit anyone, armor dosen't mean shit, they have an infinite range,

>What you expected to happen
not fucking fall over and get arrested and stripped while not being able to do anything

>What actually happened
downed and got stripped with no chance of getting back up

>Steps to reproduce if possible
1. get shot

**Comment by Ephx1** [comment]
ahahahahahahahahahahahahahahahahahahahaaaaaaaaaaaaaaaaaaaaaaaaahahaha

**Comment by mrpain666** [comment]
he must be from tg, they can't one shot you over there

**Comment by Probe1** [comment]
reminder that tg players are super robust and vg players are ERP and underage and not robust.

**Comment by Probe1** [comment]
@N3X15 close

**Comment by Exxion** [comment]
Someday this issue will be closed

**Comment by clusterfack** [comment]
I thought it was pretty funny but fine

**Comment by Exxion** [comment]
You can still see it by browsing [Honk]
