### ISSUE TITLE
(WEB REPORT BY: kammerjunk REMOTE: 198.245.63.50:7777) Mining external airlocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5535]
>Revision (Should be above if you're viewing this from ingame!)
Mining external airlocks

>General description of the issue
Mining airlocks keep bolting randomly (with or without AI)

>What you expected to happen
Being able to walk through unbolted airlocks

>What actually happened
Unable to walk through bolted airlocks

>Steps to reproduce if possible
Not sure. Walk through unbolted airlocks, mine, come back to bolted airlocks.

**Comment by Probe1** [comment]
this has been happening for a long time and i've never been able to wrap my head around why

**Comment by Ephx1** [comment]
Could it have something to do with the science outpost having cycling airlocks?

**Comment by Probe1** [comment]
beats me.

**Comment by Kurfursten** [comment]
It's possible that someone got lazy doing mapping and forgot to separate the id_tags on research outpost and mining, meaning that the research outpost's cycler would cause mining to close/lock

Needs more research/testing

**Comment by Intigracy** [comment]
That's exactly what happened.
