### ISSUE TITLE
pAI update issues

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#5538]
The new medical records + HUD doesn't include the host scan

Medical records are inaccesible, only show a blank screen after a name is selected

Smoke function injects smoke in the host, who reported LSD effects and sounded retarded afterwards

**Comment by Kurfursten** [comment]
Third needs more testing

**Comment by ihadtoregisterforthis** [comment]
Well, it was on Research, I pressed smoke, some sparks appeared and then host went strange.
He had coffee in the bloodstream already, and maybe tricordrazine.

Smoke also asks to be carried in order to inject with chemicals.

**Comment by Kurfursten** [comment]
All of them ask to be carried, you can't use the chem synth without a host

**Comment by Kurfursten** [comment]
These were fixed

**Comment by ihadtoregisterforthis** [comment]
I choose to believe that somehow the smoke chems mixed with something already in the host before the smoke, and used up one of the components so no smoke came out.
Whatever it was it didn't happen again.

**Comment by Kurfursten** [comment]
It is possible based on the way things work that if the person in question had both mercury (causing the brain damage) and lithium in his system, the smoke could theoretically become space drugs instead of smoke.
