### ISSUE TITLE
Idea for PAIs

### ISSUE THREAD

**Issue by Soldierofallah911** [d3athrow/vgstation13#5539]
The robotocist should be able to make PAI bodies, which allow PAIs to move on their own and perform certain functions. I specifically had Metal Gear Mark 2 from Snatcher in mind, and was thinking that it could have the detective's scanner, a health scanner, the ability to consume food, a flashlight, and a built in intercom, along with whatever upgrades the inserted PAI chooses. I would be willing to sprite this.

**Comment by PJB3005** [comment]
I don't think this is such a good idea because pAIs aren't really supposed to be able to interface with the world, they're not another life.

**Comment by clusterfack** [comment]
This seems like a mommi that can interfere
