### ISSUE TITLE
Unable to leave the cyborg recharging stations

### ISSUE THREAD

**Issue by Petnavi** [d3athrow/vgstation13#5543]
Seems that if a cyborg enters crit and then proceeds to go into a recharging station they'll be unable to exit it unless they get help via admins.

**Comment by PJB3005** [comment]
I can confirm this.

**Comment by Probe1** [comment]
Cyborgs still can't leave advanced scanners or cyrogenics without admin intervention.  It happens infrequently when nanites are popular and someone turns into a cyborg while inside cryo or a scanner/sleeper.

**Comment by Kurfursten** [comment]
@Probe1 Someone should add a check to the cyborg transformation virus so that it will only fire if you are on a turf.

I'm not too worried about people being kept from transforming by stashing them in cryo until the virus fades.

**Comment by clusterfack** [comment]
For that exact reason the transformation procs all use get_turf(src)
