### ISSUE TITLE
Reagents synth

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5544]
A request for a device, printable at the same tech and material requirements as the material synth.
It is a handheld device, and it is functionally the same as the Odysseus syringe gun/synth but without the shooting part.
You insert a battery and a container, sample a reagent or reagents by attacking a beaker in sample mode, then set the synth to output chemicals using battery.
It inherits the containers attack action if in use mode. It can accept a syringe, any beaker, or a drinking glass. If you put a beaker in it, you can insert the whole assembly into a medbot for extreme shinanegans.

**Comment by PJB3005** [comment]
inb4 somebody find adminorazine

**Comment by Iamgoofball** [comment]
@PJB3005 

i think adminord qualifies as a solid because of this :^)

PS remove the retarded state checking, nothing uses states in ANY version of chemistry ANYWHERE.

Goonchem doesnt use it
Baychem doesn't use it
Goofchem doesn't use it
VGchem doesn't use it
Trekchem doesn't use it

no one uses it
