### ISSUE TITLE
(WEB REPORT BY: crnibombarder REMOTE: 198.245.63.50:7777) Yellows gloves not the right color

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5546]
>Revision Yellows gloves not the right color

>General description of the issue
The inhand sprite for gloves is a different color than actually wearing it.

>What you expected to happen
Same shade of yellow

>What actually happened
Not the same shade of yellow

>Steps to reproduce if possible
Take off yellow gloves, look at sprite in hand, put on gloves, look at char sprite.

**Comment by Intigracy** [comment]
All of the glove items have different shades for the item sprite than they do when worn.
idk
