### ISSUE TITLE
Botanists seed extractor in meta club station.

### ISSUE THREAD

**Issue by Atticus34** [d3athrow/vgstation13#5548]
General description of the issue
Seed extractor doesn't dispense seeds

What you expected to happen
Seeds to pop out of the machine

What actually happened
Seeds dissapeared when dispensed.

Steps to reproduce if possible
Put seeds inside the seed extractor and then vend them.

**Comment by Kurfursten** [comment]
Needs more testing, botanists on meta seemed to have no issues with this two days ago

Can anyone reproduce?

**Comment by FudgePucker** [comment]
I think I remember there being a glitch like this.
Maybe its vending the seeds under the extractor itself.
Did you try right clicking on it to see what was on the turf?

**Comment by Atticus34** [comment]
Yes i did, I couldn't find them. It was one time. I don't get the chance to play botanist on meta club often. I thought they were getting vended in a wall or something.

**Comment by Probe1** [comment]
Can't reproduce.

Also I miss Atticus.

**Comment by gbasood** [comment]
Holy shit this is old
and before botany3 even
