### ISSUE TITLE
Increase efficency of apcs

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5550]
This is a suggestion to add an extra wire to apcs, or reuse an existing one. 
Cutting this wire will shock the user (need insulated gloves), and bypass the lossy fuses on the apc.
AI/cyborgs/mommis can also push a button to bypass fuses through the interface, but not normal users. (similar to overload lights)

Upside: This causes power usage of the equipment around the apc to drop by a noticeable percent, as it bypasses the hefty lossy  overcharge and safety fuses of the apc.

Downside: If the powergrid the apc is on goes above a certain amount of wattage/kwattage, the apc no longer has fuses to protect people, and thus will occasionally lightning bolt things and people nearby.

The strength and range of the lightning bolt is based on how far over the safe limit the powergrid is.

Causing a lightning bolt will drain the powergrid an amount of energy and use it to reach out to strike a mob and electrocute it, or strike a flammable object and set it on fire, or strike a metal object and electrocute anyone on the same tile as the metal object.

**Comment by PJB3005** [comment]
10/10 would MoMMI again

**Comment by FudgePucker** [comment]
TIME TO IMPROVE THE SHIT OUT OF THE STAITON. 10 DELORIANS IN THE GRID, ALL APCS SET TO KIL- I mean at the most effecent setting, THIS STATION WILL BE RUNNING AT MAX OPIMIZATION.
