### ISSUE TITLE
(WEB REPORT BY: kammerjunk REMOTE: 198.245.63.50:7777) Meta Club z-level 7

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5553]
>Revision (Should be above if you're viewing this from ingame!)
Meta Club z-level 7

>General description of the issue
z-level 7 inescapable without admin intervention.

>What you expected to happen
The ability to leave z-level 7

>What actually happened
Hit a black wall of nothing

>Steps to reproduce if possible
Go to z-level 7, fly to the edge.

**Comment by clusterfack** [comment]
Oh fuck I forgot to fix this

**Comment by Intigracy** [comment]
Fixed by pomf.
