### ISSUE TITLE
(WEB REPORT BY: alone REMOTE: 198.245.63.50:7777) Cannot leave Z level 7 on Metaclub

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5558]
>Revision (Should be above if you're viewing this from ingame!)
b62a51998dc390190c35c81b9c8969267737534c 

>General description of the issue
Stuck on Z level 7 on Metaclub

>What you expected to happen
to get off of Z level 7 on Metaclub

>What actually happened
Perpetually stuck on Z level 7 on Metaclub

>Steps to reproduce if possible
Drift off any edge of a Z level, end up on Z level 7 on the edge of the map

**Comment by Intigracy** [comment]
Fixed by pomf.
