### ISSUE TITLE
Photocopied Nanopaper Has Regular Paper Sprite

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5561]
When you copy nanopaper in a photocopier, the copy is still nanopaper, but it has the sprite for regular paper.

**Comment by Exxion** [comment]
Photocopying nanopaper should really just not work
Or it should spit out some horribly corrupted still picture of the media like actually happens if you photocopy something moving

**Comment by Shadowmech88** [comment]
Moved to Gitlab.
