### ISSUE TITLE
(WEB REPORT BY: velas REMOTE: 198.245.63.50:7777) Z lvl 0 med-track

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5563]
>Revision 202e56832a55d3dfa98135f48e743ad6ffd7b3a9 

>General description of the issue

Enter Z level 0 on crew monitor, crew monitor display disappears and never reappears when reusing PC / moving / anything.

>What you expected to happen

For it to work and display Z level 0

>What actually happened

Displayed nothing and I could never track the crew again.

>Steps to reproduce if possible

Use Crew mintor in CMO office, select change z level, enter "0", hit enter.

**Comment by Shadowmech88** [comment]
This is a bug, but

>For it to work and display Z level 0

There is no Z-level 0. The station Z-level is 1. Most likely the monitor broke because you entered a Z-level that didn't exist.

**Comment by clusterfack** [comment]
I would say it's more accurate that the problem is that zlevel 0 does exist, but its where things inside containers are (0,0,0)

**Comment by clusterfack** [comment]
I've reproduced this but the following js line SHOULD have prevented it, can anyone tell me why not?

var newZ = parseInt(Math.min(Math.max(prompt("View which Z-Level?", z), 1), 6));

**Comment by clusterfack** [comment]
Ah it may be checking a string since it does parseint last

**Comment by clusterfack** [comment]
Nevermind it seems the bug is when you input the same zlevel that you are currently on
