### ISSUE TITLE
Radio Transmitter doubles as an extremely potent improvised weapon

### ISSUE THREAD

**Issue by Shaska-** [d3athrow/vgstation13#5565]
The radio transmitter fires out an extremely large amount of radiation and heat when turned on, and is able to be moved around at will while doing so. The damage done by it quickly stuns and kills anyone in a fairly large radius around it.
This allows anyone with suitable protection to use it as a potent mobile weapon against anyone who isn't wearing a rad suit (Read: Everyone).
I suggest making it automatically turn off when not bolted to the floor.

**Comment by Exxion** [comment]
If it's such a high-powered machine, maybe it should even require a direct wire, like emitters and a few other machines.

**Comment by Kurfursten** [comment]
It's nerfed by 33% in #5171

66% if some brave engineer went ahead and disabled one of the rad wires earlier while setting up the station's music.

**Comment by PJB3005** [comment]
@Exxion issue is th

**Comment by Kurfursten** [comment]
@clusterfack This was patched
