### ISSUE TITLE
Add a stripe on disposal pipes to show what direction they go

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5568]
I have no idea.  I have never had any idea.  When I replace broken disposal pipes I'm just guessing and hoping that I'm building a new one in the correct direction.

This can be resolved by adding a stripe like a volume pump has to show what direction they are facing.  

Like this, but not done in 5 seconds and with pink to make it more obvious for explanation.

![s-disp](https://cloud.githubusercontent.com/assets/8550416/8914008/9c1a4f24-346a-11e5-90f7-e1b7876c941d.png)

This way, when shit gets blown up, I can look at a disposal pipe and know hey they go this way I should make pipes that have the same direction!.  Right now I just have to guess.

**Comment by PJB3005** [comment]
...

Disposal pipes are non directional...

**Comment by Shadowmech88** [comment]
I believe disposal pipes have no direction, same as atmos pipes.
The direction something moves through the disposal pipe depends entirely on which end it entered from, which is why the Cargo mailing system works and why packages can move out through the same pipes that trash moves in through.

**Comment by Probe1** [comment]
Then why are there directional straight disposal pipes?

**Comment by Intigracy** [comment]
Shrug.

What they've said is true.

**Comment by Probe1** [comment]
Good enough for me I guess!

**Comment by PJB3005** [comment]
@Probe1, you mean in the RPD?

Shit RPD code.
