### ISSUE TITLE
(WEB REPORT BY: iratepirate REMOTE: 198.245.63.50:7777) Metaclub Warden Office power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5570]
>Revision bfa7f32809d7094453788997a745f102c39922e1

>General description of the issue

Runs out of power 4 minutes into the round

>What you expected to happen

This not to happen.

>What actually happened

>Steps to reproduce if possible

**Comment by Probe1** [comment]
I think because of the design, the Warden APC is powering 3 rooms and it's just too much for one little apcs heart to handle.

![image](https://cloud.githubusercontent.com/assets/8550416/10095533/847c967c-6338-11e5-881e-b1bc44c6e18a.png)
