### ISSUE TITLE
(WEB REPORT BY: crnibombarder REMOTE: 198.245.63.50:7777) Vent crawling through passive vents

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5573]
>Revision Vent crawling through passive vents

>General description of the issue
you can't vent crawl through passive vents

>What you expected to happen
vent crawl

>What actually happened
didn't vent crawl

>Steps to reproduce if possible
attempt to vent crawl
nothing happens

**Comment by ConkerDev** [comment]
Nice revision there
