### ISSUE TITLE
Exile implants no longer work

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5575]
what it says on the tin.  you can leave the asteroid z level via shuttle or z level change just fine.  the in game message "Your hair raises on end as you feel a weak bluespace void surround you." successfully triggers when implanted but the player can freely travel between z levels and it is not reflected on the prisoner management control console.

**Comment by Probe1** [comment]
In addition, I think the code is problematic.  

code\game\objects\items\weapons\implants\exile2.dm
``` 	implanted(mob/M)
		if(!istype(M, /mob/living/carbon/human))	return 0
		var/mob/living/carbon/human/H = M
		H << "<span class='notice'>Your hair raises on end as you feel a weak bluespace void surround you.</span>"
		H.locked_to_z = ASTEROID_Z
		return 1

ASTEROID_Z is defined in code\setup.dm

``` // Moved from machine_interactions.dm
#define STATION_Z  1
#define CENTCOMM_Z 2
#define TELECOMM_Z 3
#define ASTEROID_Z 5

This was written when we only had one map.  Now we have several.

**Comment by PJB3005** [comment]
o-oh.

I think the checks for locked to z only happen for MoMMis

**Comment by Intigracy** [comment]
All the maps have z5 as the asteroid though, so the fact there's multiple maps shouldn't be an issue.

**Comment by Shadowmech88** [comment]
Taxi's kraken-roid is on Z-level 6.

**Comment by Probe1** [comment]
I was thinking about taxis roid being on z 1 with main station when I wrote that but yeah you're right.

**Comment by Intigracy** [comment]
Why the shit was taxi made special snowflake then?

**Comment by ComicIronic** [comment]
No reason at all, the define system for zlevels was just insufficiently thought out for extension.

**Comment by Probe1** [comment]
migrated to gitlab
