### ISSUE TITLE
(WEB REPORT BY: brokenboundarie REMOTE: 198.245.63.50:7777) Borer Becomes Monkey

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5581]
>Revision  (Should be above if you're viewing this from ingame!)
c8dad8500b5d923af3e311a4ba8ba501294f8639 

>General description of the issue
I infested Pun-Pun and used him to make lots of borer babbies. Later caught and tried to assume control and then to abandon body. The first task finished before the second and so I became Pun-Pun himself, and was unable to access borer abilities.

>What you expected to happen
To remain a borer in control of Pun-Pun and not literally become Pun-Pun.

>What actually happened
I was presumably no longer a borer.

>Steps to reproduce if possible
1) Infest a monkey (or a human?)
2) Release control
3) Now start assuming control
4) Now start to abandon body

**Comment by Probe1** [comment]
Just curious, I arrested you (Pun Pun) and had you turned into a human so we could use the advanced scanner to see if you had a borer controlling you.

What effects, if any, did being transformed into a human with genetics have on your borer status?  Was it already past the point it wigged out on you?

**Comment by Zth--** [comment]
Borer has changed a lot since this report. Does it still happen?

**Comment by clusterfack** [comment]
This is almost certainly fixed since the borer rework. Someone should remake it if it happens again.
