### ISSUE TITLE
(WEB REPORT BY: acedick REMOTE: 198.245.63.50:7777) New pAI flashlight doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5582]
>Revision c8dad8500b5d923af3e311a4ba8ba501294f8639 

>General description of the issue
pAI flashlight doesn't produce light.

>What you expected to happen
Light to be produced as the description describes

>What actually happened
With no lights on, the area stayed pitch black even turning it on and off.

>Steps to reproduce if possible
>Buy pAI flashlight app
>activate said app
>light doesn't increase regardless of where it's put, even if in hand

**Comment by PJB3005** [comment]
It's possible the pAI in question was in a backpack or something.
