### ISSUE TITLE
(WEB REPORT BY: shiggypiggy REMOTE: 198.245.63.50:7777) Detective Hat & Haircuts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5585]
>Revision (Should be above if you're viewing this from ingame!)

09f185b68a28bf49031a7bb23176e62d01c1ea7b

>General description of the issue

Mentalist haircut clips through the detective's hat

>What you expected to happen

For it not to clip

>What actually happened

It clipped

>Steps to reproduce if possible

Get the mentalist haircut
Wear detective's hat

P.S. I know it's a minor shit bug but it's really frustrating

**Comment by Shadowmech88** [comment]
There was a similar hair-clipping problem when wearing helmets with certain hairstyles, and the fix someone made was simply to make hair non-visible while wearing a helmet.
If at all possible, I think that should be avoided with this problem. Tucking all of one's hair underneath a helmet for mobility reasons is plausible, but the same can't reasonably be applied to a hat.

**Comment by Intigracy** [comment]
Just use a different hairstyle you baby.

**Comment by ghost** [comment]
This is impossible to fix, @gbasood . Please remove from the freeze.

**Comment by Intigracy** [comment]
Actually please close.

If you don't want your hair to be too big for hats, get a different hairstyle.

**Comment by 9600bauds** [comment]
w/e lol

**Comment by Intigracy** [comment]
The alternative is spriting overlays for every hat that chop off excess hair

Yeah nty
