### ISSUE TITLE
(WEB REPORT BY: mcgstyle REMOTE: 198.245.63.50:7777) Voice changer disappearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5586]
>Revision (Should be above if you're viewing this from ingame!)
09f185b68a28bf49031a7bb23176e62d01c1ea7b

>General description of the issue
Voice changer not having a clickable symbol after being changed to facehugger form and pushed out of ones face

>What you expected to happen
Have the mask in hand or something

>What actually happened
I have an "empty" slot in my backpack which I cannot click but is blocking space.

>Steps to reproduce if possible

**Comment by Intigracy** [comment]
Definitely caused by the toggling of the facehugger mask not having an up icon.
