### ISSUE TITLE
Uh, something's up with the cloning console sprite.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5595]
![](http://i.imgur.com/5PbNVrv.png)

@deitylink

Yes the console was properly powered.

**Comment by Probe1** [comment]
definitely haven't seen this before and worked fine 12 hours ago.  

was it persistent over a round, multiple rounds, or was it a temporary bug during one round that went away?

**Comment by PJB3005** [comment]
Uh, I just saw it last round, near round end, don't think it was persistant.

**Comment by Shadowmech88** [comment]
I saw something like this last round as well, but I remember the icon being orange and being on the right side of the console's screen. It went away after I cycled the power in Genetics.

**Comment by DeityLink** [comment]
boop
