### ISSUE TITLE
(WEB REPORT BY: myroc REMOTE: 198.245.63.50:7777) Dismantled APCs still give power alarms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5598]
> Revision (Should be above if you're viewing this from ingame!)
> a9a69af8aedf5238e9a266db8bfda729c9247466
> 
> General description of the issue
> If you dismantle an APC, that APC will continue to display a power alarm on the Station Alert Computer despite it no longer existing, or even if it is replaced.
> 
> What you expected to happen
> The power alarm to be cleared.
> 
> What actually happened
> Rebuilding an APC three times gave me three power alarms in one area that I could never fix.
> 
> Steps to reproduce if possible
> 1. Find an APC (it may need to already be displaying a power alarm, not sure)
> 2. Dismantle it
> 3. Rebuild it in the same spot
> 4. You should still have a power alarm in the area.

**Comment by PJB3005** [comment]
>power alarm code.

Ideally power alarms should be handle by the APCs THEMSELVES rather than the area.
