### ISSUE TITLE
THE DETECTIVE SOMETIMES FEELS LIKE SHOUTING!!!

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#5600]
Detective has a chance of spawning with the sobriety gene but also has a rare chance of spawning with the shouting gene for some reason.
I'm unsure if the bartender is also affected by this.

**Comment by Shadowmech88** [comment]
I played a round where the bartender randomly spawned with the morph power, SJW disability, and another disability that we weren't able to distinguish.

**Comment by Probe1** [comment]
as Shadowmech alluded to, genetic disabilities and powers have a random chance of occurring.  did you get sobriety multiple times in a row?

**Comment by clusterfack** [comment]
Well everyone has a small chance of getting abilities/disabilities, and some jobs always get them like clown (clumsy) and detective/bartender (sobriety)

**Comment by Konater** [comment]
I did not know getting blocks toggled beyond sobriety/clumsy/telepathy was intentional sorry, kind of unfair though

**Comment by Intigracy** [comment]
RNGesus is completely fair.

**Comment by Intigracy** [comment]
you can close this, there was another issue about this recently that was also closed
