### ISSUE TITLE
Give Mediborgs a Tool For Manipulating Pills

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5602]
By which I mean individual pills, not the same thing the pill collector does.
Given that 99% of the time the chemists stock the chemfridge with medicine pills, not bottles, there is no way for a medical borg to administer the medicine from the fridge to a patient if they're incapacitated or otherwise unable to take it themselves. The borg can make the medicine themselves in a chem dispenser and then inject it, but that wastes valuable time during which the patient draws closer to death.

**Comment by PJB3005** [comment]
how to manipulate single pills!

pull pill from stack

use pill collector

**Comment by Shadowmech88** [comment]
@PJB3005 Will that allow you to force-feed that pill to your patient, or to put it into your beaker so that you can inject them with it?

**Comment by PJB3005** [comment]
Oh, sorry, not really.

**Comment by FudgePucker** [comment]
What about a medi borg upgrade that adds a smart regent storage system, or what the cool kids will call it, S.R.S.S.
It can pick up pills and dissolve them into a tank.
It and also pick up the contents of breakers and bottles.
Then it can select chemicals it has stored with its hypospray to chlora- I mean, treat patents.

**Comment by Shadowmech88** [comment]
Moved to Gitlab.

**Comment by Shadowmech88** [comment]
Moved back to Github.
