### ISSUE TITLE
(WEB REPORT BY: headless1 REMOTE: 198.245.63.50:7777) Detective coat suit storage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5605]
> Revision (Should be above if you're viewing this from ingame!)
> 84a4ea3edbf290fc561e677b9b04a19a678d51c1
> 
> General description of the issue
> The detective's coat can't hold his flask. This seems like an oversight more than anything else.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by BestName** [comment]
Are you talking about the suit storage slot or the two actual pockets the coat has? Because the flask should fit inside the coat.

**Comment by ihadtoregisterforthis** [comment]
You can put it in the coat's inventory though.
