### ISSUE TITLE
(WEB REPORT BY: headless1 REMOTE: 198.245.63.50:7777) PAI sec package

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5607]
>Revision (Should be above if you're viewing this from ingame!)
84a4ea3edbf290fc561e677b9b04a19a678d51c1

>General description of the issue
The Security Package for PAI's doesn't appear to work.

>What you expected to happen
When I click on the name of a person in the sec package menu, I expect to see their sec records page.

>What actually happened
The page is blank, devoid of useful information.

>Steps to reproduce if possible
Be a PAI with a security package and try clicking on a person's name in the package menu.

**Comment by Probe1** [comment]
I was the master and can confirm its borked.

**Comment by Probe1** [comment]
bug still present
