### ISSUE TITLE
General Fabricators working like shit

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#5608]
If you build a General Fabricator with the Flatpack Fabricator, no matters where you set up it, the items will spawn there, in the red circle. (I had to tell the other mechanic that god wanted us to be terrorists((HE SAID "I ALREADY DISPOSALED 4 BUT THEY KEEP SPAWNING"))
![8ff3be61e6](https://cloud.githubusercontent.com/assets/11085293/9000385/fd7e0d32-371c-11e5-8673-b9b33eab1e28.png)
![1438313094078](https://cloud.githubusercontent.com/assets/11085293/9000388/0110888a-371d-11e5-8d5b-cd0aae367c40.png)

**Comment by ComicIronic** [comment]
Known issue.
