### ISSUE TITLE
(WEB REPORT BY: probe1 REMOTE: 198.245.63.50:7777) SSUs don't spit out contents when power is lost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5609]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
http://i.imgur.com/YvEmGfE.png
there should be hardsuits.  there is no power.  hardsuits cannot be used.
>What you expected to happen
hardsuits to pop out like they did before someone fixed SSUs

>What actually happened
THEY DIDNT POP OUT

>Steps to reproduce if possible
turn off power and go to a SSU

**Comment by clusterfack** [comment]
You crowbar the stuff out

**Comment by Kurfursten** [comment]
Clusterfack is right, as someone who recently worked with the SSU code and tested it thoroughly when I fixed it, this feature is still WAD -- use a crowbar
