### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Can't complete building of space pods, gives weird admin error

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5610]
>Revision (Should be above if you're viewing this from ingame!)

84a4ea3edbf290fc561e677b9b04a19a678d51c1

>General description of the issue

ADMIN LOG: Holy shit /datum/construction/reversible/pod/(/datum/construction/reversible/pod) is trying to set its new index to 0! how the fuck did this happen? I don't know, our direction is forward old index was 1. User is vahalian, itemused the welding tool, step /list
>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by PJB3005** [comment]
Fixes in 4ab5e5d15ae485fd89bd938fe6b206737c9f8d90.
