### ISSUE TITLE
Ghosts can toggle emergency flood lights

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#5611]
As a ghost, go into atmos and interact with the flood light. No I don't mean with the Boo! verb, I mean actually click on it as you were turning it on and off as if you were alive.

You can!

**Comment by Exxion** [comment]
They can also interact with lightswitches, albeit much more slowly than the living
I'm pretty sure that's intentional, but I don't know about the floodlights

**Comment by Probe1** [comment]
i think all lights are supposed to be ghosthand interactive for SPOOKINESS

**Comment by ComicIronic** [comment]
Deliberate.

**Comment by PJB3005** [comment]
It should probably check for poltergeist though (if it doesn't)
