### ISSUE TITLE
Bees kill diona pods.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5613]
bee watch enters its 4th month

https://github.com/d3athrow/vgstation13/issues/4127
https://github.com/d3athrow/vgstation13/issues/3328
https://github.com/d3athrow/vgstation13/issues/3182
https://github.com/d3athrow/vgstation13/issues/4799

fix it *please*

**Comment by ComicIronic** [comment]
It's an open repo, why don't you try to fix it?

**Comment by Probe1** [comment]
I have tried.

**Comment by PJB3005** [comment]
NOT THE BEES

**Comment by FudgePucker** [comment]
THE PAIN traitor item for botanist when?
The normal ambrosia strains are better at killing than the antag strain.

**Comment by PJB3005** [comment]
@FudgePucker how does that relate to this issue.

**Comment by Probe1** [comment]
Both things are never going to happen so its tangentially related ;_;

**Comment by FudgePucker** [comment]
@PBJ3005
Absolutely nothing. :^)

The problem is the way bees fertalize plants right?
