### ISSUE TITLE
don't cross the streams

### ISSUE THREAD

**Issue by DrCelt** [d3athrow/vgstation13#5619]
![http://i.imgur.com/YmWeRdS.png](http://i.imgur.com/YmWeRdS.png)
@N3x15
https://www.youtube.com/watch?v=jyaLZHiJJnE

**Comment by FudgePucker** [comment]
Fucking lasers, how do they work?

**Comment by 9600bauds** [comment]
Is this still an issue?

**Comment by PJB3005** [comment]
I know that due to a feature request on the BYOND forums I made, BYOND doesn't kill the server anymore if there's been 3 infinite loops.

Also N3X15 hardcapped beams, so I doubt it.

**Comment by gbasood** [comment]
I can't seem to duplicate this myself. Closing until someone else manages to reproduce.
