### ISSUE TITLE
(WEB REPORT BY: aceedex REMOTE: 198.245.63.50:7777) Crew Monitoring computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5625]
>Revision (Should be above if you're viewing this from ingame!)
edf4be5c0b5434b168a4ffe495324de9e7be00f9 

>General description of the issue
Crew monitoring computer shows only space when viewed. When using text only it shows nothing

>What you expected to happen
For the crew monitoring computer to show the station as well as the people with maxed sensors

>What actually happened
The monitor only showed space tiles. Not even the outline of the station

>Steps to reproduce if possible
I am not sure. I joined a round where the paramedic's monitor had been moved to the entrance of virology. I moved it back and it was like that when I checked it. It remained like that in subsequent rounds

**Comment by Probe1** [comment]
This happens to me too.  Clicking both left and right mouse button at the same time helps..

**Comment by Petnavi** [comment]
Can confirm. Used to be able to open both Z-1 and Z-5 at the same time, now it'll just crash and burn, forcing me to relog if I want to use it.

**Comment by Zth--** [comment]
Same issue here, I thought I was the only one
