### ISSUE TITLE
(WEB REPORT BY: charmstruck REMOTE: 198.245.63.50:7777) General Fabricator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5626]
> Revision (Should be above if you're viewing this from ingame!)
> edf4be5c0b5434b168a4ffe495324de9e7be00f9 
> 
> General description of the issue
> The general fabricator was severely nerfed a while ago, with both its printspeed massively decreased and the costs inflated drastically.
> 
> What you expected to happen
> I expect to be able to print an item in a reasonable time. It is no exaggeration that the print time for a single item can reach over 10 minutes in an upgraded machine, where it would previously take seconds.
> I was told that the revision would be reversed a day or two after the nerf, but it has been at least a month now and the machine is largely useless now.
> 
> Steps to reproduce if possible
> Use the general fabricator, cry

**Comment by Kurfursten** [comment]
The general fab uses a formula based on the amount of materials in the item you want to create. This means that making compressed matter cartridges with it is really bad -- better just using an autolathe, which has a more linear creation time. I thought the same as you at first, but this differentiation of advantages struck me as good design after I stopped to consider it.

I believe that at 45,000 materials, compressed matter cartridge takes the longest of any item in the general fab. It takes around 6 minutes a piece (fully upgraded), not over 10.

**Comment by ComicIronic** [comment]
>I was told that the revision would be reversed a day or two after the nerf

By who?
