### ISSUE TITLE
(WEB REPORT BY: charmstruck REMOTE: 198.245.63.50:7777) Rapid Part Exchange Device and the Bag of Holding

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5627]
>Revision
edf4be5c0b5434b168a4ffe495324de9e7be00f9 

>General description of the issue
The RPED does not fit in the Bag of Holding, it gives the message that the RPED is too big (like it would with a regular backpack)

>What you expected to happen
I expected it to fit because the Bag of Holding can fit anything

>What actually happened
It didn't fit

>Steps to reproduce if possible
Try to stuff the machine in a BoH

I'm not sure if this is just an oversight or intentional, but it's rather inconvenient. I can understand it not fitting in regular bags but the 
BoH was made for these kinda things

**Comment by Kurfursten** [comment]
This is pretty clearly intentional. It was given w_class = 5, and the BoH holds up to w_class 4.

Some other w_class 5 items are the movable apiary, electropack, energy axe, and stool.

**Comment by Shadowmech88** [comment]
But why is it intentional? Is it that bad to be able to put the RPED in a backpack?

**Comment by Kurfursten** [comment]
I think that it was PJB's compromise for having the RPED hold 50 items. Personally, I'd rather have it back at 21 slots and able to fit in a backpack.

**Comment by PJB3005** [comment]
Eh it's how the TG RPED is, which I just stole

**Comment by Probe1** [comment]
21 item limit was impractical.  i'm one of the few people autistic enough to micromanage the 21 limit http://i.imgur.com/4Ddi98c.png  

50 is fine.

**Comment by Kurfursten** [comment]
I disagree completely with the 90% of that post that wasn't relevant to this Issue, but I'm not going to engage it because it is so painfully off topic and I don't want to encourage distraction from what this Issue is about.

If someone makes it fit in the bag of holding you should probably delete the gadget bag in the same PR, since mechanics will always have access to a BoH and there will be no reason for the gadget bag to exist now that the RPED is so large. At least right now it has the sole advantage of fitting in bags and pockets.

**Comment by Shadowmech88** [comment]
Doesn't the RPED require research? The gadget bags at least have the advantage of being immediately available.
Also, how many parts does a gadget bag hold?

**Comment by Kurfursten** [comment]
21, like the old RMCE. So now the RPED holds 2.5x as much and has all the special interactions.

>Immediately available
It's not like anyone's delivering parts before the first mineral shipment anyway.

**Comment by Shadowmech88** [comment]
Less for part delivery, more for part theft/transfer.
It's a lot easier to steal a machine if you can put its pieces in a gadget bag.

**Comment by Kurfursten** [comment]
Again, currently true, won't be true if there's a PR to make the RPED fit in BoH. It would be better to steal the parts inside an RPED if you can hide it in a bag, since the RPED works on empty frames.

**Comment by Shadowmech88** [comment]
It'd be better if you can GET an RPED. What if you need to steal the parts to a machine and R&D/mining haven't done their jobs yet?

**Comment by Kurfursten** [comment]
You're better off deconning a machine because if R&D and mining haven't done their jobs yet, there are no loose parts in the workshop to steal. The mechanic hasn't printed anything because he has no research or materials.

**Comment by Shadowmech88** [comment]
>loose parts in the workshop

No no, I mean using a bag in order to steal machines by pocketing them.
Deconstruct it, put the parts in the bag, put the bag and circuit board in your backpack.
Now you only use up two inventory slots to steal what would've taken 7 or 8 for all the components, or more for multiple machines.

**Comment by Kurfursten** [comment]
You can do that with a plastic bag. Besides, you're already breaking into R&D or the workshop because those are the only places gadget bags exist. This train of thought has been humored too long. The gadget bag, which cannot be obtained outside the workshop, does not exist to be a more useful part theft bag. If it was, it would be available in tool storage or the youtool.

**Comment by Probe1** [comment]
Gadget bags hold 25 parts Kurfurst.

**Comment by Kurfursten** [comment]
Okay, fair enough: it holds 25. The point stands. I really, strongly disagree with making one of the easiest jobs on the station even easier.

**Comment by Zth--** [comment]
This was fixed by me on gitlab. Close it already

**Comment by clusterfack** [comment]
lame zth
