### ISSUE TITLE
(WEB REPORT BY: maddoscientisto REMOTE: 198.245.63.50:7777) Built sound system does not play music

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5628]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
I built a sound system and mounted it in the mechanic's room on one of the walls and then set the correct frequency, music doesn't play.

>What you expected to happen
Music should have played, in the hallways it's playing and the frequency is correct

>What actually happened
Music didn't play

>Steps to reproduce if possible
mount a sound system in the mechanic's room

**Comment by PJB3005** [comment]
Since when can you BUILD sound systems?

**Comment by PJB3005** [comment]
@kurfursten

**Comment by Kurfursten** [comment]
You can fix this by turning the sound system off then on once. It's a little buggy like how you sometimes need to turn a juke off then on.

**Comment by MaddoScientisto** [comment]
I tried that but it didn't seem to work, although in that round something went wrong soon after and it wasn't working even in hallways anymore so I'll have to test again

**Comment by Kurfursten** [comment]
I wasn't able to reproduce on live. Same place, mechanic workshop. I had Deity listen in too.

**Comment by clusterfack** [comment]
This was unable to be reproduced, if you do find a way to reproduce it maddo let us know

**Comment by MaddoScientisto** [comment]
wow man this was forever ago

If I remember correctly in the end I just had to make sure to toggle the sound system off and then back on after each new installation and then it worked all the time, it was probably that or it was fixed somewhere else I don't know
