### ISSUE TITLE
(WEB REPORT BY: lorkhatosh REMOTE: 198.245.63.50:7777) Cryokinesis doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5633]
Cryokinesis simply does not work, when you click cryokinesis mutation button it does nothing.

**Comment by clusterfack** [comment]
I can confirm that this DOES work, but it doesn't work on centcomm. I think the z2nocast is unnecessary so I'll remove that I guess.
