### ISSUE TITLE
Tiles that were destroyed in an explosion will have lighting issues when repaired

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#5634]
exactly what it says on the tin

![](http://i.imgur.com/MgyLURU.png)

**Comment by Angelite191** [comment]
I suspect it may be a thing when the new tile is set, it's initialized to 0, ignoring all light that was on the tile.

**Comment by PJB3005** [comment]
Know the cause, when a tile gets fixed like this the new overlay doesn't get light from affecting light sources.

Fix should be relatively simple, as a list of affecting lights is already kept on the turf.

**Comment by Angelite191** [comment]
S-so that means you'll fix it, right?

**Comment by PJB3005** [comment]
yes

**Comment by PJB3005** [comment]
https://gitlab.com/vgstation/vgstation/merge_requests/10

**Comment by Angelite191** [comment]
Resolved.
