### ISSUE TITLE
Vox sprites need to be smaller and more human-like (body and head, excluding beak)

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#5635]
The Richard/Biker clothing is a perfect example of this. The tail and beak sticking out is fine, but the head is huge compared to human sprites, and the body has extra pixels on the outside. The red behind me is my N2 tank.
![why](https://puu.sh/jmQ2X/2f3b130d9b.png)

**Comment by PJB3005** [comment]
It's more that if somebody sprites something they forget a goddamn vox sprite.

We just need to make more vox sprites

**Comment by clusterfack** [comment]
That or remove vox

**Comment by PJB3005** [comment]
FORMER

**Comment by Wizardcrying** [comment]
Why make spriters have to make vox sprites of EVERYTHING when you can mod the vox sprite itself?

**Comment by d3athrow** [comment]
because theres a reason for having sprites that aren't just human with tail or beak

**Comment by Arthurdentist** [comment]
the proper thing to do is prevent vox wearing clothes that look silly on them.

**Comment by d3athrow** [comment]
nah

**Comment by Exxion** [comment]
I don't have a screenshot, but sec helmets on vox are almost as fucked as that suit.

**Comment by Intigracy** [comment]
I'm considering replacing vox with the little blue guys in the image below. That, or making the current vox smaller so they look shorter than humans as is intended, instead of towering monsters.

It'd just be a lot of work respriting everything.

![](http://i.imgur.com/uaJMSi9.png)

**Comment by Exxion** [comment]
I don't think replacing them with those blue guys there would go over well, as vox are birds, not insects
You could make the current ones smaller, but it seems like a lot of work for such a minor difference

**Comment by FudgePucker** [comment]
Just gib vox that wear anything that doesn't fit them.

**Comment by Ephx1** [comment]
What if
Now hear me out
What if
...
What if we could make something humanoid that ISN'T an animal?

**Comment by Exxion** [comment]
Like Dionae or Plasmamen or Skellingtons?

**Comment by Ephx1** [comment]
Yeah, and we could have them in place of Vox if someone finds their sprites so offensive.

Remove skeletons 2559

**Comment by Exxion** [comment]
The problem with vox sprites is that clothes that don't have special vox sprites should be set to not fit them, but often aren't

**Comment by Ephx1** [comment]
Well, there are often complaints of the Vox being an animal in space. I don't personally care, I like their ideologies directly.
And if we have issues with their sprites, it seems like we could replace them with something else.
Just a suggestion though. We do also have an entire .dmi of Vox clothes, so it would be somewhat of a waste to throw it all away.

**Comment by Intigracy** [comment]
Anyone got a list of all the things vox can wear that don't have the right sprites?

**Comment by PJB3005** [comment]
Not really.

I know a lot of job alt title jumpsuits are screwed (engine tech, xenoarch jumpsuit, etc...).

Oh and another one just jumped to mind: xenoarchaeology suits in general.
