### ISSUE TITLE
The AI can see what's under static when double-clicking any object

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#5636]
It then can see anything and interact with anything as if there was a camera there

How to reproduce:
1) be AI
2) jump to permabrig
3) double click a window
4) you can now see the execution room

I'll add more information and screenshots once the round ends

**Comment by d3athrow** [comment]
watafak

**Comment by Unfit** [comment]
![image](https://cloud.githubusercontent.com/assets/9512290/9028337/0c8bbf30-3976-11e5-96ba-0576486b1d86.png)
![image](http://puu.sh/jmY3k/f285e2573e.png)

**Comment by DrCelt** [comment]
PANIC
