### ISSUE TITLE
Advanced Security Console has difficulty selecting a new camera after already selecting one.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5638]
So you cancel out of a camera but you've still got the UI for the advanced sec console up.  Click on a new camera.  Nothing happens!  

I have to close the UI, reopen it, hit cancel camera view button, and then select a new camera.  While its still better than a regular security camera console except if you want to view borgs then the regular one is a good choice.

**Comment by Exxion** [comment]
Camera console code is a bit of a mess
Fun Fact: There was, until pretty recently, a file containing only a duplicate definition of the camera console. It was not in the dme and did nothing except confuse me when I was trying to fix something.

**Comment by d3athrow** [comment]
http://ss13.pomf.se/uploads/2015-08-05_12-12-34.mp4
works for me

**Comment by Probe1** [comment]
resolved
