### ISSUE TITLE
(WEB REPORT BY: intigracy REMOTE: 198.245.63.50:7777) Radio transmitter can be on while not anchored

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5639]
>Revision (Should be above if you're viewing this from ingame!)
0bc1057d264d04343779de69b169cc001e348e64

>General description of the issue
See below

>What you expected to happen
Transmitter to turn off if not anchored

>What actually happened
A borg murdered the whole crew with a transmitter

>Steps to reproduce if possible
Turn on transmitter
Unanchor
Drag around

If that doesn't work, try unanchoring first, then turning on.

Why it's bad:
![](http://puu.sh/jnb2h/5a1265fa9c.png)
![](http://puu.sh/jnb5l/2161be9f27.png)

**Comment by Wizardcrying** [comment]
Thanks, Cyrridven

**Comment by Intigracy** [comment]
:cry:

**Comment by clusterfack** [comment]
Fixed apparently
