### ISSUE TITLE
Requesting two new sprites for scanner components

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5642]
![image](https://cloud.githubusercontent.com/assets/8550416/9031091/e533ddc8-397a-11e5-8b33-ec963ecd0168.png)

Can't tell them apart.  After looking into it I found they are identical.  Scanner components are a five frame animation that every scanner type uses.  Ideally, I would prefer to get matching sprites.  That's two new sprites that each consist of ten frames.  However we can use the existing sprite as the tier 3 phasic sprite, and have the other two less advanced tiers be single sprites without any animation.

**Comment by PJB3005** [comment]
TG has different sprites for them, can probably steal those.
