### ISSUE TITLE
RPED does no damage when swung at other players

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5643]
What it says on the tin.  Hefty thing like that?  Too big to fit in a backpack?  You'd think it'd do more than a pillow of hurt.

**Comment by FudgePucker** [comment]
Considering it is a jumbled mess of overly complicated hardware, capable of switching out highly fradgle parts, the machines it switches parts with come from different corprerations, meaning the REPD has to be able to switch parts from a cloning machine that they paid over one million credits for designs and licensing for, and a 20 credit microwave.

The second you hit something with it it would shatter into a thousand parts.

**Comment by Probe1** [comment]
theorycrafting aside it's either a bug or an overside fudgepacker.

**Comment by FudgePucker** [comment]
Bulkyer=/=better weapon.
Its center of mass would be off, the handle wouldn't support you swinging it at someone's face, and most of the bulkyness comes from integrate electronics, it wouldn't be that heavy, just really bulky, as compared to a tool box that is designed to be tossed around and abused made out of assistant blood, engineer tears, the life oil essense of 100 mommis, and steel. The REPD is probably mostly plastic and silicon.

**Comment by Exxion** [comment]
But it should still deal *some* damage. Not necessarily a lot, but some.

**Comment by AutismSpider** [comment]
so 5 damage at most
