### ISSUE TITLE
(WEB REPORT BY: brokenboundarie REMOTE: 198.245.63.50:7777) No Pipe Animation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5644]
>Revision (Should be above if you're viewing this from ingame!)
4a4e58bcb54b536f954c62b428d9d8f73add62b9 

>General description of the issue
Detective's smoking pipe (found on left side of desk in Box) has no lit animation displayed on the character sprite.

>What you expected to happen
Smoke animation similar to that of the object sprite.

>What actually happened
No change in sprite displayed on character.

>Steps to reproduce if possible
Light the smoking pipe and equip it.

**Comment by PJB3005** [comment]
RPEDs are child of gadget bags and uh, I never set a force on them.

**Comment by Zth--** [comment]
If you drop it and equip it again (while lit) the sprite then properly updates. Yeah, the animation exists, but it's not properly updating
