### ISSUE TITLE
metastation - mechanics can't enter engineering to obtain supplies

### ISSUE THREAD

**Issue by MaddoScientisto** [d3athrow/vgstation13#5645]
On metastation the mechanics can't access the tool machines and other stuff that is easily obtainable on boxstation.

I request that either mechanics get access to the engineers-only lobby or that the tool machines are moved to the common lobby, along with the lockers, as well as the glass and iron cache

**Comment by FudgePucker** [comment]
The glass and iron cache in engineering is for fixing holes in the station, not for assault rifles and hand teleporters for every assistant.

**Comment by MaddoScientisto** [comment]
you need phazon for hand teleporters anyway
