### ISSUE TITLE
BLINDED BY MY HATE FOR OXYGEN-BREATHERS

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#5647]
AFTER BEING BOMBED BY AN OXYGEN BREATHER I WAS CLONED. DURING THE TIME I WAS BEING CLONED I BECAME BLINDED BY MY HATE FOR THOSE WHO BREATHE TOXINS

OFF THE O2
![OFFTHEO2](http://puu.sh/jnXta/797303086b.png)

**Comment by Intigracy** [comment]
I'm confused.

What caused this?

**Comment by PJB3005** [comment]
OKAY.

N2 INTERNALS HUD BUTTON WHEN.

RED TANK TOO.

**Comment by Wizardcrying** [comment]
@Intigracy It may have something to do with cloning/having air during cloning. The issue was fixed for me after relogging.

**Comment by NigglyWiggly** [comment]
This happens in a lot of different scenarios and I'm not sure if anyone really knows why, happens a lot when going from ghost to alive though, if that helps narrow it down, and it doesn't always use a certain icon

**Comment by Wizardcrying** [comment]
The overlay, when hovered over, had the name "flash".
Could have to do with overlays?

**Comment by d3athrow** [comment]
some pooling issue, person who implemented it hasnt bothered to fix.

**Comment by PJB3005** [comment]
@clusterfack

**Comment by PJB3005** [comment]
I haven't seen any HUD pooling issues recently, this might need to be retested.

**Comment by clusterfack** [comment]
As far as I've seen, all hud pooling issues have been fixed for some time now. If someone experiences one again they should open a new issue
