### ISSUE TITLE
AI's may start with a "funky" default name

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#5648]
Joined as an AI and got a really funky default name. The bast part is that I didn't change it fast enough so I was stuck with it until an admin changed it for me.
![165e1c3580](https://cloud.githubusercontent.com/assets/3892856/9045358/3dd29072-3a2b-11e5-803f-73f3385127b3.png)

**Comment by FudgePucker** [comment]
That would be a great AI gimmick.
Just have a random hash as your name and only reply to requests when called by your name and not ones where they ask for an AI.

**Comment by Ephx1** [comment]
I'm fairly certain it's written like that in the code too.

**Comment by BestName** [comment]
Yeah that's the one. Unless your locale is russian you'll get gibberish instead of the proper name.
