### ISSUE TITLE
Skrek the Vox

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#5649]
Proposal for VG lore change and a slight mechanical change.

VG lore wise, the reason Vox are on the crew could be because Sol GOV managed to crack a deal between them and the Vox to provide materials and supplies in exchange for skilled labour and ancient technology. Some groups of Vox disagree or there's some dissention, whatever, so some raids still do happen. (Much more infrequently than they used to)

This can explain why there's some new odd technologies being developed by and for NT, and why there are crew onboard in all sorts of positions.

Mechanics wise, I propose giving all crew vox the same Inviolate blurb that Vox raiders get, and putting it in their notes. You could even give them arkship-related crew objectives if you want, or flavour traitors as working for the Arkships through the Syndicate.

**Comment by Ephx1** [comment]
I don't know. Giving /vg/ lore sounds like a bad idea, forcing an ideal on people also sounds bad too.
People should play as they want when picking a race, it's lite-rp.

**Comment by FudgePucker** [comment]
I think having vox traders starting in outpost (along with the odd human/gray/plasma man working along) would be interesting.
Have the mining shuttle also be able to dock with the vox outpost.
They get their own cargo with different supply's and prices, meaning both the traders and cargo will have to barter with each other to maximize profits and supply's.
A more gray area is how they would deal with vox raiders, maybe neutral between them and the station, but you know how hungry for valids everyone is.

**Comment by NigglyWiggly** [comment]
>Making Greys work with dirty bird people

Greys are our humanity's friend though, we wouldn't force them to work the birdcage

**Comment by Midaychi** [comment]
Well there's an idea. Neutral-tagonists? Indifferents?
A highpop midround system that chooses instead of antags, people who come from a different company or organization. They spawn nuke ops style with goals that aren't nessicairly antagonistic or protagonistic to the crew, and can sidle their ship over to accomplish it however they feel fits within the intentions of their organization, with SolGOV stepping in if things get out of hand.
