### ISSUE TITLE
Facehugger kebabs

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#5654]
We have human kebabs
tofu kebabs
meat kebabs
synthemeat kebabs
corgi kebabs
xeno kebabs
spider kebabs
not sure about bear kebabs, add those too

So why not be able to throw some metal rods and facehuggers in the microwave for a delicious treat?

**Comment by MaddoScientisto** [comment]
If you eat one does an alien burst out of your chest?

**Comment by Killette2** [comment]
I think they'd die in the microwave and preferably you'd use dead ones anyways.
