### ISSUE TITLE
[BOX] Objects get stuck inside display cases

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#5655]
I dont know exactly how it happened as I was observing at the time, but a player told me that their detective scanner got stuck in the captain's display case as they were scanning it, and sure enough, theres a scanner INSIDE the display case as if it had spawned inside it. They broke it open and took it out like they would have an energy gun.

**Comment by clusterfack** [comment]
Well you can put objects inside display cases, that's sort of what it is for so I'm not sure what the problem is.

**Comment by mrpain666** [comment]
This is hard to report on as I didnt see the whole thing go down but it doesnt sound like they put it in there  intentionally.

**Comment by mrpain666** [comment]
I'll just close this for now and reopen it if I see it happen again.
