### ISSUE TITLE
The Station Has No Roof

### ISSUE THREAD

**Issue by the-socks** [d3athrow/vgstation13#5656]
General description of the issue
The station has no roof

What you expected to happen
For the station to have a roof

What actually happened
The station didn't have a roof

Steps to reproduce if possible
Join the game and look around. It's a birdseye view, why can't I see the roof? Must mean there is no roof.

**Comment by Shadowmech88** [comment]
The roof is actually a solid sheet of incredibly clean Plexiglas.

**Comment by Ephx1** [comment]
Your character is being controlled by an orbiting drone equipped with x-ray cameras.

**Comment by clusterfack** [comment]
The station's roof is thousands of feet high so its far above your head

**Comment by Exxion** [comment]
[Honk] [OH GOD IT'S LOOSE]

**Comment by the-socks** [comment]
>Clean plexiglass
Then it should be listed when you mouse over anything

>Controlled by X ray drone
Possible

>Thousands of feet high
Then there's thousands of cubic feet of vacuum above your player and we should all be dead

**Comment by Ephx1** [comment]
If the roof is thousands of feet high, how can a spacemen not climb a table?
That means the roof must be reaaaaaaally low, so you can't squeeze through the small space between the two!

**Comment by Shadowmech88** [comment]
But you can stand on tables if someone puts you on one.

**Comment by the-socks** [comment]
The roof isn't a sheet of plexiglass or it would appear as an object when you put your mouse anywhere. 

The roof can't be thousands of feet high, because that would mean the walls are thousands of feet high, and your character is able to build and dismantle walls very quickly. 

Surely we are dealing with a classic case of drones equipped with x-ray cameras

**Comment by clusterfack** [comment]
If the drones had xray cameras why cant you see through walls, and if it was plexiglass why would maint be protected from radiation

**Comment by Ephx1** [comment]
Selective post process video editing to make your spessmen's mulshions authentic and prevents mental breakdowns in 78% of spessmen.

**Comment by Boxe** [comment]
the roof is your screen

**Comment by clusterfack** [comment]
The roof being extremely high up is clearly the only rational reason
