### ISSUE TITLE
More camera issues

### ISSUE THREAD

**Issue by Unfit** [d3athrow/vgstation13#5658]
- using the 'AI core' button as an AI will teleport you to your core AND remove static overlay, allowing you to see and interact with things you can't normalyl see (most noticeable on taxistation)

- using the advanced camera computer, jumping to the AI core and waiting will remove the black overlay after a short delay. After jumping to another camera, black overlay only returns after a few seconds, allowing you to see through walls during that time

**Comment by Exxion** [comment]
Ah fuck
The second one is quite possibly my fault, though I don't know exactly what's wrong

I mean
I know why the overlay doesn't reappear for a moment and that's an easy fix, but I don't know why it goes away in the first place (unless the AI core camera is X-ray)

**Comment by d3athrow** [comment]
https://gitlab.com/vgstation/vgstation/commit/40bd11ec4e853b63721876898fb15b7371fcdf51

**Comment by Intigracy** [comment]
fixed
