### ISSUE TITLE
[Schedule Processor Issues] WOAAAAAAH WHAT THE HELL?!

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#5660]
Based on my own and the observations of anons in the thread, the changes to the schedule processor has fluxed the general flow of game-play and creates huge mishaps of retardation that just removes fun.
-Stuns last much, MUCH longer (minutes instead of seconds)
-Light takes up to 4 seconds to illuminate tiles, very crippling in emergency situations
-Chem dispenser takes much longer to recharge
-The sleep verb may take 100,000,000,000 years to awake from if no one wakes you up first
-Blood takes waaaay longer to regenerate (which is bad enough since a paper cut can cause all of your blood to fall out of your body)
-Chemicals are processed slower
-It takes longer to get hungry (feature request soon)
-Spess Pets take much longer to hatch (CRITICAL GAME BREAKING BUG, FIX IMMEDIATELY!)

considering that these are changes in the Schedule Processor, these results may have been expected. By compiling a list, I hope that if we keep this new scheduler, we'll fix these issues one by one.

**Comment by clusterfack** [comment]
Yeah it's the same scheduler, just all rates at which each process were accidentally all set to 5 seconds instead of the standard 2 and .5 for lighting

**Comment by IratePirate** [comment]
You can't make this shit up.

**Comment by Skullyton** [comment]
Grenades take a fair bit longer than 5 seconds to activate, few tests showed it was more along the lines of 8 seconds during mid/high pop.
