### ISSUE TITLE
Connecting from wiki link takes you to a different server

### ISSUE THREAD

**Issue by naldon** [d3athrow/vgstation13#5662]
I use replay to join the server so I don't experience this issue myself, but when a few of my mates have tried to join the main server using the wiki link it puts them in a station that runs the exact same but we can't see each other in the round and there are different people on. No idea what's happening or where to begin on getting around it. If there is already a work around any help would be appreciated.

**Comment by Ephx1** [comment]
![panobunker](https://cloud.githubusercontent.com/assets/6224074/9100541/1a0ab388-3baa-11e5-928a-c2a31b860292.jpg)
We have one of these sending your friends to a different server, direct your friend to be whitelisted by an admin, or ask them to turn it off.

**Comment by PJB3005** [comment]
just sayin' but we moved to gitlab.

**Comment by Probe1** [comment]
https://gitlab.com/vgstation/vgstation/issues

**Comment by Intigracy** [comment]
panic bunker, working as intended, pls close.
