### ISSUE TITLE
Mommis picking up paper

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#5663]
Its not a serious issue to me, but its kinda of annoying. As a mommi, when you click to pick up a sheet of paper, it opens the paper so you can read it. In order to pick up the paper you have to right click it. Like I said, this isnt really important, but kinda annoying

**Comment by Probe1** [comment]
we have moved to gitlab https://gitlab.com/vgstation/vgstation/issues
