### ISSUE TITLE
Mechanics R&D console unable to re-link to machinery

### ISSUE THREAD

**Issue by DamagedEngine** [d3athrow/vgstation13#5664]
After moving my R&D console via unbolting and rebolting, it could not connect to the machinery again. I tried everything, rebuilding it from scratch, moving it closer or further, connecting and disconnecting to the database, but with no result. In this case the problem was with the mechanics console, but it could also apply to all other R&D consoles.

**Comment by Probe1** [comment]
We have moved to a new site https://gitlab.com/vgstation/vgstation/issues

**Comment by PJB3005** [comment]
This might've been fixed as a result of https://gitlab.com/vgstation/vgstation/merge_requests/77

**Comment by clusterfack** [comment]
Seems that it was fixed
