### ISSUE TITLE
Plasmamen Burn infinitely while in CE Hardsuit

### ISSUE THREAD

**Issue by Firestorm4594** [d3athrow/vgstation13#5665]
take no damage, looks cool but is a visual bug that should be fixed

**Comment by PJB3005** [comment]
We have moved: https://gitlab.com/vgstation/vgstation

**Comment by BestName** [comment]
How is that a bug? They are supposed to catch fire if they take off their containment suit.

**Comment by AutismSpider** [comment]
This happens with the atmospherics hardsuit too

**Comment by dylanstrategie** [comment]
Hardsuits which isolate the plasmaman from the environment should not make him combust, obviously enough

**Comment by AutismSpider** [comment]
Not like it hurts when its the CE hard suit or the atmos one.

They take burn damage if they put on Miner suit sec or engi suit though

**Comment by PJB3005** [comment]
What's happening is that even though the plasmamen is on fire, their CE or atmos hardsuit is protecting them for the heat, yes it makes fuckall sense.

**Comment by clusterfack** [comment]
I remember an age when putting on your hardsuit stopped fires, or at least I think I do, it's been so long that I can barely remember
