### ISSUE TITLE
Cargo shuttle console pop up glitch & Shuttle lung damage

### ISSUE THREAD

**Issue by dopaper** [d3athrow/vgstation13#5666]
The mining shuttle console pops up whenever it's used after one use. It also seem that sometimes (rarely) your lungs have a chance of popping in the shuttle.

**Comment by PJB3005** [comment]
WE HAVE MOVED http://gitlab.com/vgstation/vgstation

**Comment by Zuhayr** [comment]
Have you considered deleting the repo?

**Comment by PJB3005** [comment]
@Zuhayr There's still a lot of old issues and PRs here, that'd be a bad idea.

**Comment by Unfit** [comment]
>The mining shuttle console pops up whenever it's used after one use

this has been fixed unless i fucked up somehow

**Comment by clusterfack** [comment]
This is fixed
