### ISSUE TITLE
Can't Pull Gun Out of De-Powered Charger

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5677]
Not sure if it's relevant, but the power cut out while the gun was already charging.

**Comment by Zth--** [comment]
Yeah, it's an old bug and can be really annoying

**Comment by Probe1** [comment]
gross, https://github.com/d3athrow/vgstation13/pull/5587 was supposed to have fixed the bad behavior with rechargers but I guess that one wasn't addressed.

**Comment by dylanstrategie** [comment]
If the power turns off DURING charging, the gun is stuck in here, which makes little sense

Just needs to have item removal prioritized before the power check

**Comment by Intigracy** [comment]
Commenting for self reminder.
