### ISSUE TITLE
Explosive Implant is Too Weak

### ISSUE THREAD

**Issue by grink** [d3athrow/vgstation13#5681]
the explosive implant is incredibly underwhelming and weak for the price of 6tc. i propose reducing the price to just 5tc

**Comment by dylanstrategie** [comment]
The explosive implant should work like the Nuke Ops one, if it doesn't already, and should actually explode and do damage instead of just gibbing you, which it used to do

**Comment by clusterfack** [comment]
It has like a 1,2,3,4 explosion. Bigger than nukeops from what I've seen.
