### ISSUE TITLE
Add a "WYCI" tag for github

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5689]
lets face it half the feature requests could stand to use a healthy dose of reality.

**Comment by ConkerDev** [comment]
+1

**Comment by BestName** [comment]
Help a guy out.
![5db5d182f1](https://cloud.githubusercontent.com/assets/3892856/9910078/ea60a71c-5ca3-11e5-8567-1e8fdc4e30eb.png)
![6b31021003](https://cloud.githubusercontent.com/assets/3892856/9910082/ec703716-5ca3-11e5-97e2-95f38b6976cf.png)

**Comment by dylanstrategie** [comment]
When You Code It

**Comment by Intigracy** [comment]
We'll have a WYCI tag WYCI.

**Comment by Probe1** [comment]
I knew that was coming
