### ISSUE TITLE
(WEB REPORT BY: deadpoolj REMOTE: 198.245.63.50:7777) Multiple people can ride in a wheelchair.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5694]
>Revision (Should be above if you're viewing this from ingame!)
497bf564a6bf764f4a81cff18982d6177ac931db 

>General description of the issue
Multiple people can ride in a wheelchair at once.

>What you expected to happen
Rambling to bust into my office via AI.

>What actually happened
5 shitters busted into my office.

>Steps to reproduce if possible
Have one nigga in a wheelchair. Have another person stand by it and drag themselves onto the wheelchair. Try stopping the wheelchair tide. Try not to cry. Cry some more.

**Comment by Probe1** [comment]
double the fun, they can't be stunned.  or maybe they can be stunned but another person can keep moving the wheelchair.

messy as fuck.

**Comment by Rei1226** [comment]
Absolutely fucking hilarious. I wish this could stay in the game as long as the retarded shit with stunning them gets fixed. I'd even love to see people pixel_x and pixel_y coordinates be shifted a bit so you can really see how many people are on the wheelchair.

**Comment by Zth--** [comment]
This is fun, really. The other day we were like 8 people using fire ext as turbo. God damn, dont remove it

**Comment by clusterfack** [comment]
It sounds awful and removing fun is what gets me up in the morning
