### ISSUE TITLE
Magic missile knocking people out instead of stunning

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#5702]
The projectiles seem a little funky too especially when there are several people

**Comment by Shadowmech88** [comment]
It's done this for as long as I can remember.

**Comment by dylanstrategie** [comment]
I honestly can't remember if magic missiles paralyzed or stunned you. I remember facing a Wizard at least once and being downed by a MM like I would be downed by a taser bolt

**Comment by 9600bauds** [comment]
There's like five issues on this already, and I'm too lazy to link those
