### ISSUE TITLE
Destroying a cult wall leaves behind remains and blood

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#5704]
why would you give artificers a quality of life change to calm their autism by allowing the conversion of walls and floors they can't stand over but then make it so destroying a wall which is their way of getting about leave behind blood and remains RUINING EVERYTHING
if it's about leaving behind a trail the cult walls and lack of regular wall kind of do that already

![can_remains_even_be_removed_without_deleting_them](https://cloud.githubusercontent.com/assets/7538670/9946055/e4b7bdd8-5d88-11e5-8904-5a245e312a78.png)

please no working as intended tag

**Comment by Unfit** [comment]
I'm working on making remains removable if that's what's bothering you

**Comment by DeityLink** [comment]
I'd argue that blood and remains look pretty in cult bases. It's also a reliable way to create blood splatters for blood spreading objectives.
