### ISSUE TITLE
can't take people hostage with the crossbow and obrez

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#5706]
if there are other weapons that should but shouldn't I don't know about them

**Comment by Shadowmech88** [comment]
Elaborate on this. Do you mean you aim at them but nothing happens when they move, or that you can't even aim at them?
Hostage taking in general is broken with respect to the former.

**Comment by Konater** [comment]
can't aim at all, trying to instead makes you shoot them with the deadly weapons

**Comment by Zth--** [comment]
Wasnt this fixed by unid?

**Comment by FudgePucker** [comment]
YOU SEE COMRAD, YOU DONT NEED TO POINT OBREZ, HOLDING CRAZY HAND CANNON OF SOVIET REVOLUTONARY HOLDS THE COUNTRY HOSTAGE.

**Comment by Intigracy** [comment]
Are they not children of /gun/?
