### ISSUE TITLE
(WEB REPORT BY: iamgoofball REMOTE: 72.5.195.193:12345) i can report bugs to /vg/ from NoX

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5710]
>Revision (Should be above if you're viewing this from ingame!)
Revision: Unable to load revision info from HEAD 

>General description of the issue
i can report bugs to /vg/ from NoX

>What you expected to happen
to not be able to call pomf a faggot from the safety of NoX servers

>What actually happened
i got to call pomf a faggot from the safety of NoX servers

>Steps to reproduce if possible
1. go to nox
2. hit BugReport
3. call pomf a faggot

**Comment by clusterfack** [comment]
I mean if they are using our code it is technically relevant, but whatevs

**Comment by dylanstrategie** [comment]
That's Nox's problem really. They just have to either change the issue report pointer to their own Github address (wherever it is hosted) or just can it out

**Comment by Unfit** [comment]
ayy

**Comment by Intigracy** [comment]
close

**Comment by Iamgoofball** [comment]
open

**Comment by Intigracy** [comment]
lock :^)

**Comment by Iamgoofball** [comment]
cock (^:
