### ISSUE TITLE
Can we remove the screwdriver step from assembling a light?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5739]
It takes so long and its such a bother.  I can make a light tile by mindlessly clicking some things together and have 60 per stack in my backpack.  To make a proper light I have to take out metal, make the assembly (which won't stack), attach it to the wall, wire it, screwdriver it, then put in a light bulb.

Compare it to a light tile.  Add wires to glass (results in a stack of wired tiles).  Add metal to wired tiles (results in a stack).  Walk around plopping them down at your leisure without having to stop each time and assemble a new light.

I say we nix the screwdriver step and make it a LITTLE faster.  Does anyone disagree or feel strongly?

**Comment by clusterfack** [comment]
I somewhat agree, clicking the thing with a screwdriver while it is on a wall is actually really annoying due to its size

**Comment by PJB3005** [comment]
agree

**Comment by Shadowmech88** [comment]
I wouldn't mind having it removed.
