### ISSUE TITLE
Experimental weapons animation

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#5746]
One of the weapons has a turf animation that doesn't go away after the explosion. I assume its the stickybomb launcher

**Comment by DeityLink** [comment]
Haven't been able to reliably reproduce that one. I've seen the explosion animation briefly appears on turfs where stickies had exploded before, but when I can't find what seems to cause it.

**Comment by clusterfack** [comment]
Because the turf animation is still there you dingdong!

**Comment by clusterfack** [comment]
When you leave a single loop animation somewhere with repeat set to off, and then stop viewing it for some time and then go back to viewing it, it replays the animation. That part is a byond thing.

But it occurs because your turf animation isn't going away after the animation ends.

**Comment by DeityLink** [comment]
>When you leave a single loop animation somewhere with repeat set to off, and then stop viewing it for some time and then go back to viewing it, it replays the animation. That part is a byond thing.

so this explains that.

>But it occurs because your turf animation isn't going away after the animation ends.

but whyyyyy? I blame returnToPool.

**Comment by clusterfack** [comment]
Considering all the others work its badcode

**Comment by Shadowmech88** [comment]
This may have to do with explosion code moreso than the sticky bomb code.
I viewed this same kind of "phantom explosion" phenomenon while using the gyrojet pistol.

**Comment by clusterfack** [comment]
That would be 2 objects out of every single thing that uses animations, which means its far more likely those specific objects are fucked up

**Comment by DeityLink** [comment]
@clusterfack in case you don't know, every explosion under 1 dev uses that animation.

**Comment by Shadowmech88** [comment]
Just last round I observed this same phenomenon as the result of meteor impacts.

**Comment by clusterfack** [comment]
Deity your silly turf animation proc checks if(c_animation) which is set to null when the turf gets changed to something else, say with an explosion with any dev

**Comment by clusterfack** [comment]
Still occurring
