### ISSUE TITLE
(WEB REPORT BY: yred REMOTE: 198.245.63.50:7777) Roundstart borgs are treated like humans.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5748]
Revision b76a0399126142ae47cd1c25446937cc5f752535

They get an account number and PIN, a headset spawns in AI charging under them, and at least once a traitor received an objective to kill a roundstart borg.

**Comment by DeityLink** [comment]
>at least once a traitor received an objective to kill a roundstart borg.

honk

**Comment by clusterfack** [comment]
When did this start? I've never heard of this before and nothing has touched this to my knowledge.

**Comment by clusterfack** [comment]
Ah I see it was caused byhttps://github.com/d3athrow/vgstation13/commit/9b578b8f375eb11fc208d01565f78092d7eea9a2

**Comment by Intigracy** [comment]
Oh no.

Will get to tomorrow.
