### ISSUE TITLE
Add a viral symptom that makes you emit smoke intermittently

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5752]
WOULD BE FUN.  Once in a while you emit smoke.

I might code it myself later but if someone beats me to it I'll be very happy.

**Comment by clusterfack** [comment]
Smoking is bad for you

**Comment by Zth--** [comment]
Smoke out all the chems inside you. I love it

**Comment by Probe1** [comment]
i still want this and failed miserably at coding it myself.
