### ISSUE TITLE
Make Cuffed Players Unable to Move While Bound by Hookshot

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5755]
Hookshots are a neat tool for Security. Much in the same way that they can allow a cargo tech to move two crates at once, they can allow an officer to transport two prisoners at once. However, as it is now an uncooperative prisoner can run away from the officer, resulting in a tug-of-war with the hookshot and the inevitable snapping of the chain.

If a player who is cuffed is not able to move or escape while being pulled by hand, should they not then also be unable to move or escape while being pulled by hookshot?
Obviously though if the hookshot is disarmed or dropped the prisoner could run off, pulling it behind them.

**Comment by PJB3005** [comment]
@DeityLink
