### ISSUE TITLE
Crew monitor

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#5772]
Some of us see this http://puu.sh/kiAnH/7091572bd7.jpg instead of the station
Bhangmeter works fine
Advanced security cameras don't.
I believe this issue has been reported several times, please PLEASE fix it

**Comment by SangriaMonkey** [comment]
Yeah I haven't been able to use crew monitors for a while either. Don't know what the problem is.

**Comment by PJB3005** [comment]
Have you tried updating IE?

**Comment by Zth--** [comment]
Updating IE fixed it, thanks PJB
