### ISSUE TITLE
Post round freezing

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5776]
At a consistent time right after the map vote results are announced the server freezes for 20-30 seconds then unfreezes and another 10-30 seconds pass and the server shuts down.

There shouldn't be a hard freeze there.  This has been going on for 12-24 hours now.

Right there after the vote.  Happens consistently. 

![nettle_relay_zeta_2015-09-21_02-07-33](https://cloud.githubusercontent.com/assets/8550416/9986075/992d1ef6-6005-11e5-87e5-dcde8ab30dad.png)

**Comment by Probe1** [comment]
Still exists after revert.

**Comment by clusterfack** [comment]
It's caused solely by this proc

![](http://puu.sh/kljO5/d337f1ed2f.png)

**Comment by Probe1** [comment]
LYNCH

**Comment by Probe1** [comment]
fixed
