### ISSUE TITLE
(WEB REPORT BY: furbeh REMOTE: 198.245.63.50:7777) Mr. V.A.L.I.D. Portable Threat Detector UI update

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5780]
>Revision (Should be above if you're viewing this from ingame!)
3d42a60efc3fdb4c46feb8f9282f22da12b413ee

>General description of the issue
The ui to enable certain features of V.A.L.I.D. doesn't seem to work.

>What you expected to happen
The UI lets me change the settings of V.A.L.I.D.

>What actually happened
Trying to hit the buttons to turn on the settings doesn't turn them on, nor change them to say "Turn off"

>Steps to reproduce if possible
Try and change the settings of V.A.L.I.D. in game

**Comment by Probe1** [comment]
I've noticed this issue for quite some time, 4+ months.  UI needs an update badly.

**Comment by Probe1** [comment]
@PJB3005 try to tackle this for us?  You're great with UIs.

**Comment by PJB3005** [comment]
ugh I honestly haven't been coding for SS13 for a while, but I'll look into it.

**Comment by clusterfack** [comment]
This werks though. 

The only case in which I could reproduce something similar to this report was when it was unanchored, which is intended!
