### ISSUE TITLE
Replace changeling lesser form monkey with crab/Norris

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5782]
why a monkey when this already exists in the code and just needs to be given ventcrawl 

https://www.youtube.com/watch?v=15hHUK1lIgk&feature=youtu.be&t=85

**Comment by Probe1** [comment]
/mob/living/simple_animal/crab/norris
	name = "Norris"
	desc = "Some weird Thing that makes a neat pet. Screams a lot."
	icon_state = "norris"
	icon_living = "norris"
	icon_dead = "norris_dead"
	speak_emote = list("screams")
	emote_hear = list("screams")
	emote_see = list("screams")
	friendly = "bites"

**Comment by NigglyWiggly** [comment]
Skowron has made better sprites for this sort of thing, Norris was just intended to be a goofy looking joke 


![](http://i.imgur.com/fRNWo2B.png)

**Comment by Probe1** [comment]
Yours matches the movie better, which I think is inexorably linked to our 'changelings'.  Take that skowron!
