### ISSUE TITLE
You can't send away the cargo shuttle

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#5788]
The option never appears, but you can order ANOTHER shuttle even though there's already one docked.

**Comment by Probe1** [comment]
What map

**Comment by Zth--** [comment]
taxi

**Comment by Zth--** [comment]
#5784 causing it

**Comment by Probe1** [comment]
fix or revert @N3X15

**Comment by Unfit** [comment]
I'm fixing it

**Comment by Unfit** [comment]
@Zth-- this has been fixed

**Comment by Zth--** [comment]
:+1:
