### ISSUE TITLE
External airlocks should start with their timers lowered

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#5790]
Because it makes sense

**Comment by clusterfack** [comment]
What timer are you talking about? Please try to be specific with these

**Comment by Zth--** [comment]
The one you can override as a silicon.

**Comment by Zth--** [comment]
It makes the airlock to close pretty fast. Sorry about the doble post, cant edit from phone

**Comment by AutismSpider** [comment]
air lock timing that can be shorten by cutting the wire as a human or over riding it as a silicon/ai

**Comment by Intigracy** [comment]
This is actually a great idea.

:+1: will do tomorrow if nobody else has.
