### ISSUE TITLE
(WEB REPORT BY: jonnathan002 REMOTE: 198.245.63.50:7777) BUG

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5792]
SPACE POD A SHIT GOING THROUGH R WALLS

**Comment by PJB3005** [comment]
Goddamnit make some fucking descriptive issue names gee.

**Comment by Exxion** [comment]
Wow what a bullshit report
It does happen though
I've noticed it mostly on the research outpost
I think it's a transport tube thing
I'll make a less shitty report sometime after I do more research
