### ISSUE TITLE
(WEB REPORT BY: conker327 REMOTE: 198.245.63.50:7777) MoMMIs cant interfce with a microwave despite having hands

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5798]
>Revision (Should be above if you're viewing this from ingame!)
8ab9672a79089acba08fe858d79f96781c554d96 

>General description of the issue
MoMMIs cant interfce with a microwave despite having hands

>What you expected to happen
The microwave to work

>What actually happened
It didnt

>Steps to reproduce if possible

Play as Chef du MoMMI
Try to be chef
You cant

**Comment by Zth--** [comment]
This is intended

**Comment by ConkerDev** [comment]
And its shit, and makes no sense. Someone put the CONTROVERSIAL tag and so on

**Comment by clusterfack** [comment]
>Play as Chef du MoMMI


This is where you went wrong

**Comment by Shadowmech88** [comment]
It was implemented this way in order to keep MoMMIs from manning the kitchen instead of repairing the station.
It's the same reason why they can no longer use the advanced bartending equipment.

Not saying I agree with it, but that's the reason why.
