### ISSUE TITLE
[Box Station] Armory lockers typo

### ISSUE THREAD

**Issue by chainsauce** [d3athrow/vgstation13#5802]
Both lockers are spelled 'Amory Locker'. As you can see this is missing an R.

**Comment by Zth--** [comment]
>Armory
>Not armoury

**Comment by Probe1** [comment]
ARMORY

![b70710caac70cf2f14e7e4b5df94e7c4](https://cloud.githubusercontent.com/assets/8550416/10042715/1dadf482-61bb-11e5-9cf3-efa39c4edf7e.jpg)

**Comment by PJB3005** [comment]
ARMOURY
