### ISSUE TITLE
Clicking the wizard spell 'Mutate' does nothing

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5806]
I expected lasery eyes.

I instead got a button with no return when clicked.

- Tested with another player.  Its fucky.

**Comment by AutismSpider** [comment]
Did you hulk out?

Mutate hulks you out+get text about eye beams

**Comment by Shadowmech88** [comment]
Did you make sure you were on harm intent?
Laser eyes only shoot if you're on harm intent.

**Comment by Konater** [comment]
and mutate doesn't give you green skin

**Comment by Probe1** [comment]
Yes, Yred and I both tested it pretty thoroughly.  The spell did not work.  The icon and verb is there but clicking it does nothing.

**Comment by FudgePucker** [comment]
How did wizzy man spells break? What change caused it?

**Comment by Unfit** [comment]
can't reproduce w

**Comment by Probe1** [comment]
List the steps you took please @Unfit

**Comment by Unfit** [comment]
- spawned a spellbook

- bought "Mutate"

- clicked on the "Mutate" button on GUI

- became hulk with laser eyes

**Comment by Probe1** [comment]
I followed those exact steps on live, then asked an observer to do the same after stuffing them into a test dummy and doing the same.

Could it be a test dummy is somehow fucky?  Who knows.  The important thing is you tested it.  Thanks, sorry my report was inaccurate.
