### ISSUE TITLE
Progress Bars show up on Items instead of Mobs

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#5807]
Progress bars show on the HUD element for an item (for example, using a metal sheet with itself) instead of the mob using it.

Can be replicated by constructing anything with metal - girders, beds, wall fixtures, etc, though I imagine this encompasses anything that is 'used' on itself to build something.

Edit:
![immoral space-hulk xviii 2015-09-23 105430](https://cloud.githubusercontent.com/assets/13457856/10048600/b677c924-61e1-11e5-979e-c354e787326d.png)

**Comment by ConkerDev** [comment]
I noticed. I thought it was intended, but yeah, makes more sense the other way.

**Comment by dylanstrategie** [comment]
I honestly wonder if we can't keep it this way. It declutters the interface

Otherwise I guess it's just a casting problem

**Comment by PJB3005** [comment]
@dylanstrategie wat, it isn't casting at all.

it's a missing `get_turf()`
