### ISSUE TITLE
(WEB REPORT BY: commradjon REMOTE: 198.245.63.50:7777) Cargo Shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5809]
>Revision (Should be above if you're viewing this from ingame!)
3373040e06d40c759c870cde3a98bf5e6584d4c9 

>General description of the issue
Cargo Shuttle is completely black inside, light sources make no difference.

>What you expected to happen
Have light?

>What actually happened
No light.

>Steps to reproduce if possible
View the cargo shuttle

**Comment by Intigracy** [comment]
@unid

**Comment by Intigracy** [comment]
@Unfit
