### ISSUE TITLE
Walls accidentally left under airlocks in defficiency

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#5821]
I know of two so far, one is the entrance into science and the other is in west maintenance beside the maint/derelict boxing ring.
![derelict](https://cloud.githubusercontent.com/assets/7538670/10064661/c68e5c38-6272-11e5-918a-af983f808e7d.png)
ps the science entrance looks awkward and could just be replaced with the 3x3 entrance we have on box
also if you moved the rd's office two squares to the left you could have a science shuttle that isn't one tile wide and put the door to the north

**Comment by Shadowmech88** [comment]
Maybe it's a feature.
![image](https://cloud.githubusercontent.com/assets/3991927/10065501/af8f3f1e-624c-11e5-8834-c57eab894ea5.png)

**Comment by clusterfack** [comment]
If someone puts a "FUCK YOU" decal on the wall sounds good to me

**Comment by dylanstrategie** [comment]
Oh christ, my barricade PR already modifies the map

FUCK YOU DUNY

**Comment by Probe1** [comment]
I cannot find this second one you mention that isn't screenshotted.  Saying west maint in DEFF is a hinderance.

**Comment by Probe1** [comment]
I looked at this pretty hard, studying the surrounding area and it looks intentional.  @Duny will be able to shed more light.

I recommend replacing them with False Walls.  It bridges the sadistic, horrible DunyStyle with something players can enjoy.

**Comment by Konater** [comment]
Since there was a wall blocking everyone from leaving the science department I doubt it

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/10100707/9c90f54a-6361-11e5-97a5-a7c9a75f647f.png)

This is the door in your screenshot.  It leads to nowhere and is in the middle of maint.  Maybe I can re-find this other door.

**Comment by Probe1** [comment]
![vgstation13_ mapsdefficiency dmm _-_dream_maker_2015-09-25_08-45-11](https://cloud.githubusercontent.com/assets/8550416/10100748/d1baf6bc-6361-11e5-9089-e0e54905cf02.png)

There she is, like you said but I can't find shit on deff even in game.  Wow Dony an R-Wall.
