### ISSUE TITLE
(WEB REPORT BY: gadeladriel REMOTE: 198.245.63.50:7777) Autolathe from Flatpack Spawns Items/Parts in wrong area

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5822]
Revision: 2e61ba3dfd3a368c0ca29756e73e80d2356a89d5 

Any items created by the autolathe spawn at the location where the autolathe flatpack spawned (above the flatpack fabricator) instead of in front of the autolathe.

Autolathe to spawn items 1 tile below autolathe.

Autolathe spawns items 1 tile above flatpack fabricator.

Create autolathe flatpack from flatpack fabricator, build it anywhere but above the flatpack fabricator, manufacture any item.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/5086
https://github.com/d3athrow/vgstation13/issues/5087
https://github.com/d3athrow/vgstation13/issues/5088

related
