### ISSUE TITLE
(WEB REPORT BY: probe1 REMOTE: 198.245.63.50:7777) Metaclub power monitor console on bridge does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5825]
>Revision (Should be above if you're viewing this from ingame!)
6ad4c1b03de85aa8c258546e0663e56439c5e94e 

>General description of the issue
Power monitor on Metaclubs bridge doesn't work
http://i.imgur.com/RSsG7iK.png

>What you expected to happen
See graph power and all that good stuff

>What actually happened
X's where power load demand should be then no connection displayed

>Steps to reproduce if possible
Fire up metaclub and go to the bridge

**Comment by PJB3005** [comment]
Map issue, whoever mapped that monitor didn't put a wire under it.
