### ISSUE TITLE
(WEB REPORT BY: senaat1 REMOTE: 198.245.63.50:7777) It's possible to get cyborgs as traitor targets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5831]
Revision: 6dbab903e221204841d4c9a8072b44470c6e8df7 
Rolled traitor, got a cyborg as assassinate objective. Name displayed is (obviously) the character's name, not the borg's.

**Comment by AutismSpider** [comment]
Just silly being a cyborg/mommi = he/she is dead for that type of objective 

You could turn this into some thing fun like target cyborg/ai/mommi would make a useful tool for the Syndicate so forces he/she emag it and keep it safe until the end of the round
