### ISSUE TITLE
Pipes Drawing Color from Wrong Layer

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#5832]
![image](https://cloud.githubusercontent.com/assets/11482753/10088822/a5819b3a-62eb-11e5-8525-425b7a13f5e1.png)
The connector is taking red color from a (spawned) pipe on the underfloor layer, in the middle row. The filter is above that, on the second top layer, and so are the red connectors.

**Comment by clusterfack** [comment]
@DrCelt

**Comment by ghost** [comment]
@clusterfack This actually isn't a bug - He thinks it's drawing the red colour from the pipe but it's drawing it from the filter which by default is red.
