### ISSUE TITLE
Turrets still have sprite/overlay/something issues where the laser persists after it stops firing

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5835]
Can be consistently reproduced in two ways.  1st, shoot any beam weapon (laser/admin for example) at a turret that exists at round start.  Results in a permanent beam icon.  

2nd, stand between two turrets so one shoots the other (notably done with user constructed laser tag turrets).  Again it produces a beam that does not disappear.

Bug has existed for over a month now, around the Deity Gun update but may not be related.

**Comment by Probe1** [comment]
![gentleman_object_xviii_2015-09-24_22-13-55](https://cloud.githubusercontent.com/assets/8550416/10091900/ce72cb2c-630e-11e5-8af7-31a0bfb342f0.png)

**Comment by PJB3005** [comment]
@DeityLink

**Comment by DeityLink** [comment]
I gave it a try a while ago but while I can reproduce the bug I'm really at a loss when it comes to fixing it.
