### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 198.245.63.50:7777) Tile Painter Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5843]
http://puu.sh/knPFy/1333f218a7.jpg
I am unable to see any of the options on Tile Painters, unsure if it is just fucked this round or only for me. Figured I'd make an issue.

**Comment by PJB3005** [comment]
Reopen the UI if this happens.

**Comment by Probe1** [comment]
this really needs addressed.  the current solution is shit.
