### ISSUE TITLE
Can't Crowbar Open Firelocks if They're On Top of Another Edge Object

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5849]
So far I've seen this in single reinforced window panes and in windoors. When the firelock occupies the same tile and faces the same direction as the other object, the firelock can no longer be crowbarred open.
This is especially noticeable on the kitchen windoor and the Brig Medbay entrance.

This only applies if you're on the outside of them. If you're on the side where you can stand on the same tile as the firelock, crowbarring it works.

**Comment by MaddoScientisto** [comment]
This also happened in the tcomms room on box
