### ISSUE TITLE
Items on the right hand are invisible

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#5852]
I'm talking about the mob sprite. Who the fuck broke it? Lynch plz
![ss 2015-09-25 at 09 22 04](https://cloud.githubusercontent.com/assets/11085293/10114705/fe00656c-63cb-11e5-884f-b2223be24a45.jpg)

**Comment by Shadowmech88** [comment]
Not all items. My egun still showed up.

**Comment by dylanstrategie** [comment]
Still occurring as of current

**Comment by dylanstrategie** [comment]
Someone didn't compile in_hand icons
