### ISSUE TITLE
RPDs windows need work

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#5853]
![fix this shit](https://cloud.githubusercontent.com/assets/5303834/10115872/c9bc36a2-63e7-11e5-8d24-aacd9d745dcb.png)

Layer selector sprites won't load sometimes and the pipe orientation sprites almost NEVER load without having to close the damn window. Also the window is way too large, there's no reason for it's to be that large. Shrink that shit, PLEASE!

**Comment by Probe1** [comment]
When the issue first presented, PJB told me in irc it was a BYOND issue.

I'm calling bullshit.  This came up when pipe coloration, baypipe, and layer manifolds were added.  It is insanely annoying to deal with.  Fix it or make a thread on byonds forums to fix it and crosslink it here.  

This slays me.

**Comment by PJB3005** [comment]
@Probe1 I already made a thread on the BYOND forums asking for a way to fix it, it made Lummox realise `browse_rsc()` is shit, which is our only hope.

The only way to fix it is to either cause a shitload of login lag (like previously) OR create artificial lag for the RPD.

Though the layer selector not rendering correctly without selecting the basic pipe first is an issue.

**Comment by Cisrox** [comment]
>can't resize a window
also I asked in IRC and someone said it was because they switched to html, and because there is no way to ensure the icons arrived in time

**Comment by Angelite191** [comment]
If I resize the damn window, when I close it to reload the damn sprites or put it in my bag the window will reappear at default size but at the position where I closed it, resulting in that little cheeky close button being about 400 pixels off of my monitor. I don't know if the window resolution is hardcoded or not but "resize the window" doesn't justify the massive waste of space of the whole window. Absolutely nothing you can select in any of the menus will ever stretch to even 1/6th of the window's resolution.

**Comment by PJB3005** [comment]
I'm thinking of a way to fix it, but it'll be really fucking annoying and a big hack.

**Comment by Probe1** [comment]
its pretty much dogshit and I'd rather have the lag than this so whatever works

**Comment by PJB3005** [comment]
#6361 and #6377 fixed this, I just didn't put an autoclose incase they weren't merged together.
