### ISSUE TITLE
Mindbreaker should change client dir

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#5854]
For some navigational mindfutzery.

**Comment by Probe1** [comment]
YES

**Comment by clusterfack** [comment]
Have you guys seen the state the map is in when changing client dir? This just isn't possible right now

**Comment by Shadowmech88** [comment]
It's okay if it looks fucked up. It's mindbreaker.

As long as it returns to normal when the effect wears off, what's the problem?

**Comment by Imagebard** [comment]
Oh wow look at that someone had the same idea as it became possible.
FEATURE FULFILLED
@PJB3005
