### ISSUE TITLE
Gas Filter Orientation Bug

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#5857]
Wrenching reversed orientation filters and or mixers flips the sprite in a confusing direction, still function as intended. Please fix.

![one](https://cloud.githubusercontent.com/assets/5303834/10117679/25c77764-642d-11e5-9b82-5a28c53156cf.png)
![two](https://cloud.githubusercontent.com/assets/5303834/10117680/25c9ef44-642d-11e5-8e37-e193505c940d.png)

**Comment by PJB3005** [comment]
@DrCelt

**Comment by FudgePucker** [comment]
I have encountered this bug as well.
Got shit talked by an atmostech because of it.
Pls fix it before I get my feelings hurt more ;_; *buzz

**Comment by Rei1226** [comment]
Probably an issue with switching some of the icon_state's around by accident. Shouldn't be too bad of a fix.

**Comment by PJB3005** [comment]
If the icon states were switched up the RPD would be fucked too.
