### ISSUE TITLE
(WEB REPORT BY: ashdemai REMOTE: 198.245.63.50:7777) Toolboxes are not showing on sprites right hand when equipped

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5858]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Same as the title

>What you expected to happen

The toolbox should be shown like on the left hand
>What actually happened

It was like I held nothing
>Steps to reproduce if possible
Try to equip a toolbox with the right hand

**Comment by unid15** [comment]
Fixed!
