### ISSUE TITLE
(WEB REPORT BY: edie REMOTE: 198.245.63.50:7777) check in out computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5860]
>Revision (Should be above if you're viewing this from ingame!)
 2a9a4dbb6763797cf87275746b962dcea1295a34 

>General description of the issue

Pop up error when I try to use the computer
>What you expected to happen
I was going to page 50 something on the catalouge of books. A page of books should have showed up

>What actually happened
I crashed, the message "Encountered invalid argument" appeared

>Steps to reproduce if possible

Go to the last page of books on the catalouge of books on the computer I think

**Comment by clusterfack** [comment]
This has been fixed it seems
