### ISSUE TITLE
Add Chemical Pack+Chemical Mask Combo as Chemist-Specific Traitor Item

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5861]
These are excellent weapons for a chemist, but I don't like that the chemist has to rely on mining/R&D to do their jobs to get it.

**Comment by FudgePucker** [comment]
Chemist gets kinda shafted on the traitor part.
Science gets bluespace beakers, stasis beakers, no telecrystal cost chemsprayers (the chemist specific traitor item), chem desp off staiton so you won't get checked up on if you are making buckets of chloral, make able chem desps, and THE REST OF SCIENCE INCLUDING TOXINS.
Maybe make a chemical pack+chemical mask combo that also comes with a bane outfit, that way when you get arrested by security and they ask you whats the next step of your master plan you can tell them "Crashing this station, WITH NO SURVIVORS." as the 20 polyacid, plasma, flash powder, smoke voice assembly grenades go off around the station.

**Comment by AutismSpider** [comment]
Make the chem sprayer cheaper for traitor chemist or take it out of R&D list or let him buy one that can hold 800 or 900 units of chems.

Add in chemical pack+bane like outfit for the chemist that comes with combat cocktail mix of chems if the chemical pack comes off it kill him/her or gib.

**Comment by Kurfursten** [comment]
@Shadowmech88 This seems like a better place to discuss it than chemistry fun. If people are interested in making this a traitor pack for the chemist, I can move over hug explosions to a general MD traitor item.

What do you think it's worth? I haven't played with it very much but it seems pretty decently strong.

**Comment by 9600bauds** [comment]
Was 1:1 added
