### ISSUE TITLE
You can talk in a split second before cloning begins

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#5862]
Consciousness slowly creeps over you as your body regenerates.
So this is what cloning feels like?
[DATA EXPUNGED] exclaims, "[REDACTED]"
You can almost hear someone talking.

Basically, you could communicate with people the second before cloning crits you.

**Comment by PJB3005** [comment]
Can confirm.

**Comment by Cisrox** [comment]
http://pastebin.com/YBzUmACy

Appears to be caused by byond lag. I don't think anything can fix this unless you could make it spawn with clone damage.

**Comment by clusterfack** [comment]
That's not actually where its happening. The issue is that your status isn't updated until the next life() tick, so for that 0-2 seconds you have 150 clone damage but aren't unconscious.

**Comment by Iamgoofball** [comment]
a shitty snowflake way could be to set the human mob's mute to 1 and then set it to 0 after all the other memery is done
