### ISSUE TITLE
Clean away disused branches?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5863]
FF seems like as good of a time as any.  

>GasMathsStrip
Last commit **May 14** by ComicIronic

>experimental
Last commit **March 4th** by d3athrow

>experimentalweapons
Last commit **July 25** by clusterfack (this one I know, it's dietys gun work and they've all been merged, he's finished his project, and he's moved on from it.  No need to keep it around)

>gasdatums
Last commit **May 10** by d3athrow

>hardsuit_port
Last commit **February 14** by ririchiyo

>idbantweak
Last commit **February 7** by Angelite191

>machinery_adjustments
Last commit **February 4th** by ririchiyo

3 of these haven't been touched in 7 months.  1 in six months.  None of them are more recent than two months ago.

![capture](https://cloud.githubusercontent.com/assets/8550416/10122027/d7da1868-64d6-11e5-8bb8-a90e2e802285.JPG)

@d3athrow @N3X15

**Comment by PJB3005** [comment]
I agree most of those need to be killed, but DO keep one of the gas datum branches.
