### ISSUE TITLE
You cant light people on fire directly

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#5868]
Not sure if this is a bug or a feature request. 

It seems people either had (or want) a way to light someone on fire directly by dousing them with flammable liquids and then using something hot on them. This may already exist in some form and be broken.

**Comment by Shadowmech88** [comment]
I seem to remember it being a thing some time ago to smash a bottle filled with welding fuel on someone and then slap them with a lighter to light them on fire.
