### ISSUE TITLE
(WEB REPORT BY: intigracy REMOTE: 198.245.63.50:7777) Block injectors (genetics) do not allow you to pick a block past 13

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5872]
>Revision (Should be above if you're viewing this from ingame!)
625835ee25b99dabb7f1c6c542efa043855efe96

>General description of the issue
read

>What you expected to happen
To make an injector for any block

>What actually happened
Only could make for up to block 13

>Steps to reproduce if possible
Be geneticist
Work genetics

**Comment by Shadowmech88** [comment]
Are you sure you were making a block injector from an SE and not from a UI/UI+UE?

**Comment by Intigracy** [comment]
Close this, I reported it.
