### ISSUE TITLE
SME chamber is leaking on box... A-FUCKING-GIN GOD DAMN IT

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#5873]
HOLY SHIT YOU HAVE GOT TO BE FUCKING SHITTING ME.
![aflap](https://cloud.githubusercontent.com/assets/12202731/10127394/0dbae852-656f-11e5-9278-16e4bed3268f.png)
THIS IS GETTING REALLY FUCKING OLD
EDIT: I should explain what the bug is, even though I have already explained it in THREE OTHER ISSUE REPORTS IN THE PAST.
The turf leaks air for some unknown reason, maybe its a unsimulated turf next to two simulated turfs causing it to just pass though the airlock, maybe someone make it simulated after it was unsimulated fucking it up, I don't know, all that I do know is, FUCKING FUCK THIS FUCKING SHIT HOLY FUCK HOW MANY FUCKING TIMES IS THIS SHIT GOING TO FUCK UP GOD DAMN IT? Also no, it isn't one of the windows being not properly secured, already checked that THE LAST THREE TIMES, the issue is with that one fucking turf, everytime I play I engineer or MoMMI, setting up the SME, I think to myself 'oh they have to have fixed this dumb shit by now, I don't need to put in a window or window airlock and bolt open the chambers airlock.' I am wrong everytime  because this shit is still not fixed.

**Comment by FudgePucker** [comment]
YOU KNOW WHAT I LOVE ABOUT ALL THE PICTURES I TAKE OF THIS?
HOW THE ENTIRE OUTSIDE OF THE CHAMBER IS ON FIRE BUT THE CHAMBER IS PERFECTLY FINE.
ITS SO FUCKING FUNNY, ITS THE TOTAL INVERSE OF WHAT YOU THINK WOULD GO WRONG.

**Comment by AutismSpider** [comment]
some thing some thing time to make it unsim like the singuo air locks this is like 7th or some time this has happen.

**Comment by Probe1** [comment]
what if i just delete the entire sme room and remap it from scratch without any varedited windows, tiles, or fuckery.  

would that do it

**Comment by FudgePucker** [comment]
@Probe1 Yea, until it gets reverted for some fucking retarded reason and it starts leaking again, and again, and again, and again, and again, until the end of time.

**Comment by Probe1** [comment]
(I can't reproduce this)

**Comment by Intigracy** [comment]
close, we have two other issues on this
