### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) No door at mining to enter rest of station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5874]
625835ee25b99dabb7f1c6c542efa043855efe96 

There is no door on Berlin station to enter the rest of the station. How someone forget to add a door?

**Comment by PJB3005** [comment]
Closing because @N3X15 doesn't give a fuck about berlin anymore.
