### ISSUE TITLE
Game Freezes When Admins Delay the Round End

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5877]
Reconnecting fixes it, sometimes.

**Comment by Rei1226** [comment]
Can confirm, think this may have something to do with the black box saving.

**Comment by Intigracy** [comment]
Did you delay before or after map voting started?

**Comment by Intigracy** [comment]
pretty sure this isn't an issue anymore since an admin delayed two days ago.

close
