### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Voting for Metastation puts the map on Berlin Station

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5878]
>Revision (Should be above if you're viewing this from ingame!)
625835ee25b99dabb7f1c6c542efa043855efe96 

>General description of the issue
Voting for meta at the end of the round makes the next round start up on Berlin Station, which is literally so horrific that people were screaming in the thread for someone to come in and nuke the entire thing so they could get to a new map

**Comment by PJB3005** [comment]
feature
