### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Admin midi's/oggs don't cancel out jukebox/streamed audio

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5879]
> Revision (Should be above if you're viewing this from ingame!)
> 625835ee25b99dabb7f1c6c542efa043855efe96 
> 
> General description of the issue

Less of a bug and more of a feature request. Would be nice to those who have both preferences turned on not having to hear the clusterfuck that is both of the songs at the same time. I think the admin midi/ogg should override the juke/sound speakers

**Comment by Probe1** [comment]
^  

I'd like a way to stop the automatic shuttle music.  Maybe there's something that really fits the theme of the round or maybe just we don't want to hear the same 8 songs and want to play something new.  

It'd be really great to have a stop music verb.

**Comment by Rei1226** [comment]
A stop music verb would be great if it could only work for in-game music and not admin played music.

The automatic shuttle music is just horrendously annoying and unfitting almost 80% of the time, and I pretty much straight up delete it most of the time to keep the atmosphere back to what it was before they boarded the shuttle.
