### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) In-game sounds completely stop admin oggs/midis for those who hear it

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5880]
> Revision (Should be above if you're viewing this from ingame!)

625835ee25b99dabb7f1c6c542efa043855efe96 

> General description of the issue

When listening to an ogg or midi, if some sort of sound goes off (for me it was a taser shot, for Deadpool it was a PDA beep)the ogg/midi completely stops for you, although still plays for everyone else

**Comment by ghost** [comment]
It doesn't stop outright, but it seems like the sound bloats out the other enough to reach 0/negative values, which interrupts the audio

Make this a BYOND issue unless someone knows how to fix Dreammaker sound

**Comment by Intigracy** [comment]
#8928
#8502
