### ISSUE TITLE
The SCP can go through walls, teleports, DOES walk when you look at it....

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5882]
THANKS CAEL

**Comment by dylanstrategie** [comment]
SCP has been borked for a while, but it's as low at it can get on my priority list of things I can change

**Comment by caelaislinn** [comment]
np

**Comment by Zth--** [comment]
check this out https://github.com/HippieStationCode/HippieStation13/blob/7e8e4e70be2bf67c1be5800ef7fd0f66ff50efd6/code/modules/mob/living/simple_animal/hostile/statue.dm . They have a can_be_seen check that works flawlessly
