### ISSUE TITLE
Shuttles Engulfed in Advanced Darkness

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#5890]
It's not possible to see anything that's not on your tile.
This happens on the pirate ship as well as the escape shuttle.

**Comment by Zth--** [comment]
supply shuttle too

**Comment by ConkerDev** [comment]
Can confirm on supply shuttle, you can only see adjacent tiles.

**Comment by PJB3005** [comment]
This SHOULD have been fixed by #5889
