### ISSUE TITLE
(WEB REPORT BY: gringonius REMOTE: 198.245.63.50:7777) Contortionist's Suit nor working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5891]
>Revision fd2d7f76e3aad858b5ab535103a18e162b3c32b5 

Quite simply, the contortionist's suit does not work at all. Even after stripping all items but it your character does not get the ability to crawl through vents.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Intigracy** [comment]
alt click vent

**Comment by Kurfursten** [comment]
Verified as not a bug, unable to reproduce, alt clicking works fine
