### ISSUE TITLE
Protolathe material duping

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5893]
Insert a sheet of diamond or phazon.  Eject it.  500 is left over in the protolathe.  Repeat ejecting diamond or phazon until you have the amount you desire.

Other materials checked, only exists for those two.

**Comment by Exxion** [comment]
It... only works for those two?
I don't even want to know why that could be

**Comment by clusterfack** [comment]
Materials used to have a different value from the sheet -> cc conversion, the rest as they say, is bad coders
