### ISSUE TITLE
Mining Station Needs Scrubber Loop

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#5894]
The mining station on box has no scrubbers and the air supply line has no N2. Easily fixed by adding an N2 miner and gas mixer to provide proper atmos mix for mining station distro and scrubber line with a passive vent out in space for scrubber

**Comment by dylanstrategie** [comment]
Needs a fully integrated atmospherics room. I'm thinking about making it a substation and just running pipes over to all the outposts

**Comment by AlphaBuffalo** [comment]
That sounds cool
