### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Metaclub Medbay needs more lights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5896]
>Revision (Should be above if you're viewing this from ingame!)

cd6734ae955158b842b7be1fa48fbec890871007 
>General description of the issue

It's incredibly dark in a lot of areas of medbay, such as the paramedic's office, chemistry, supply area, etc.

**Comment by Rei1226** [comment]
Most likely synonymous with https://github.com/d3athrow/vgstation13/issues/5915
