### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Ticklag is .65? Default should be .55

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5898]
>Revision (Should be above if you're viewing this from ingame!)

b825178e11235dc78944d46b5df9cef3d4b69397 
>General description of the issue

I'm guessing this was done intentionally? If not, it's pretty choppy.

**Comment by PJB3005** [comment]
This is in the config of pomf's server

**Comment by Intigracy** [comment]
close please
