### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Superfart genetic power farts on ghosts and also doesn't people back anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5899]
>Revision (Should be above if you're viewing this from ingame!)

b825178e11235dc78944d46b5df9cef3d4b69397 

>General description of the issue
Seems to be completely broken. Doesn't knock anyone back or stun them anymore, and can also fart on ghosts

**Comment by Rei1226** [comment]
When testing this in the thunderdome, the ability seemed to work fine.

With this diona geneticist, no matter what we tried, including raising hunger to max, turning the gene off and on again, giving him a bigger area to superfart in next to people. Tried people not next to walls, etc. etc. nothing was working. Might be hard to re-produce I'm guessing?

**Comment by clusterfack** [comment]
Both of these issues have been fixed
