### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 198.245.63.50:7777) Borers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5902]
22b5a00bd5ecce1bf36b9ffdc46cd1fbe143b685

Can't cancel out of borer secrete chemicals screen. Have to use something when clicked.

**Comment by Repth1** [comment]
Isn't this technically a feature request?

**Comment by NigglyWiggly** [comment]
Not really?
