### ISSUE TITLE
Let .357 revolvers use .38 rounds, realism.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#5904]
The only real diffrence between .357 rounds and .38 rounds is the length of the brass, preventing you from loading .357 rounds in a .38 revolver, this was because people were blowing off their hands shooting hot loaded .38 rounds.

The main balance concern this has is that detectives will have no reason not to unload their revolver and screwdriver it to shoot .357 rounds, just keep a box of .357 rounds in your jacket if shit hits the fan.

**Comment by dylanstrategie** [comment]
Someone needs to check guns again to make them less shit

We were supposed to get all sorts of cool stuff like automatic fire, but then that kinda just slipped under the radar

**Comment by FudgePucker** [comment]
I got tons of ideas and no coding skills.

Make bandilears not worthless and collecting dust by either letting them be attached to armor and other exosuits or being able to fit into exosuit slots. The choice between having shotgun shell storage or armor is silly. Also, let them hold more than just shotgun shells, let them hold any ammo type and magazines. Imagine a bad ass CE wearing his rigsuit and loaded up on matter carts like a god damn space cowboy. (Shit adding ammo storage shouldn't even be that hard.)

Give the HoS a carbine revolver (like the good has in the good the bad and the ugly had to shoot ropes with) in a nice fancy glass case like the captains laser. No reason other than it looking cool as shit.
