### ISSUE TITLE
(WEB REPORT BY: probe1 REMOTE: 198.245.63.50:7777) incorrect camera name

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5909]
>Revision (Should be above if you're viewing this from ingame!)
EVA East camera is in the bathrooms, next to the dorms.  NE corner next to urinals

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by dylanstrategie** [comment]
What map ?

**Comment by Probe1** [comment]
I'm sorry it was on Box, I was in a rush because nuke ops in muh station.
