### ISSUE TITLE
(WEB REPORT BY: kernikov REMOTE: 198.245.63.50:7777) Boxing gloves + crayon = coloured gloves instead of coloured boxing gloves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5912]
> Revision: 387e5a096f248a3a9d5dd849672a13c7c9b37a8a 
> 
> General description of the issue
> Red boxing gloves + green crayon = green standard gloves
> 
> What you expected to happen
> Green boxing gloves
> 
> What actually happened
> The gloves lost their robust boxing powers
> 
> Steps to reproduce if possible
> Put boxing gloves and a crayon in a washing machine and turn it on.

**Comment by PJB3005** [comment]
Same thing happens with magboots/galoshes -> shoes (although they still function),

**Comment by dylanstrategie** [comment]
Problem with subtypes. Boxing gloves are a subtype of gloves, galoshes are a subtype of regular shoes

Needs exception, unless you are going to add colored variants to them, in which case they'll need separate checks

**Comment by PJB3005** [comment]
> in which case they'll need separate checks

Dylan once again has no idea how to do OOP.
