### ISSUE TITLE
PICTURE MESSAGES!!!

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#5913]
Take and send picture with PDA? Sounds like a fun gimmick. Possibly scan picture with pda to send also??

**Comment by dylanstrategie** [comment]
Taking photos with PDA seems a bit much, PDAs aren't cellphones, they don't have any camera. Though scanning pictures and sending seems fine.

Maybe allow the PDA to take very shitty pictures (monochrome with a "PDA background/foreground" gradient) and send that. And if you want glorious full color pictures, find a camera

Talking of which, cameras should have a bigger focus, but that's another request altogether
