### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Tons of lights taken out of the maps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5915]
>Revision (Should be above if you're viewing this from ingame!)

f984750814e7b34029d1a6dd34ca77612b31af5a 
>General description of the issue

Not sure if somebody fucked about with the maps or if there waas some sorta coding error, but at least on metaclub and boxstation there are a ton of dark spots in hallways, rooms, etc. where there weren't before. It's not that lights are broken, its that they were completely removed from the map.

**Comment by Zth--** [comment]
IIRC lighting code was touched, that would explain everything

**Comment by dylanstrategie** [comment]
Check if this is still an issue

If it is, someone fucked up the lighting engine again

**Comment by PJB3005** [comment]
Lights removed from the map aren't on the lighting engine itself.

That said, I DID drop the light power of lights, to accomodate for us not using lambertian.

**Comment by Rei1226** [comment]
Yes, it's still an issue. Seems prevalent on almost every map. Whoever touched lighting code completely fucked shit up. I'm guessing lights may not have been removed, but all of them were lowered in power or range or whatever for...some reason? What exactly is Iambertian?

**Comment by PJB3005** [comment]
Basically, when we first had baylights, we used lambertian shading instead of linear shading, it looked a lot fancier, but was (IIRC) 33% slower than linear, also it was a lot dimmer, to accomodate for that we increased the light power of lights, this wasn't dropped again when pomf disabled lambertian, and I recently dropped it.

I dropped it because lights were unreasonably strong.

**Comment by Rei1226** [comment]
Interesting, theoretically though all we would need to do is just to raise the lights back up a little bit, correct? Not to be "Unreasonably strong" but just enough so there's no dark spots?

**Comment by Probe1** [comment]
I upped the lighting values to pre-levels and still found plenty of dead spots.  These are the things I'm focusing on, not the hallways being slightly too dim to be pleasantly lit.

**Comment by Probe1** [comment]
35 lights have been added to cover complete dark spots.  I think this covers it pretty good but need some feedback.

**Comment by Rei1226** [comment]
I mean it's just odd when the rest of the hallway is absolutely fine then you reach a spot that's dim and then it's fine again. Just doesn't look...natural? I guess is the word?
