### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Skellingtons are literally immortal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5918]
>Revision (Should be above if you're viewing this from ingame!)

bae39e3dc9192af0a322fafb9e5bdf2cae0036c0 

>General description of the issue
Nothing can kill them. We had a skellington round for halloween and someone was trying to ERP with a borg, so the sexual harrassment bear force was spawned on top of him. They de-limbed this fucker over 100 times, INCLUDING mauling off his head over 100 times, spawning over 100 heads, and he was still alive and screaming for someone to help him. Hilarious, but obviously needs fixing.

**Comment by Exxion** [comment]
![](http://vignette1.wikia.nocookie.net/undertale/images/b/be/Sans.PNG)

**Comment by Repth1** [comment]
Could not reproduce.

Spawned various flavours of skellingtons, spawned various flavours of bears. Skellingtongs ripped to shreads.

Rip.

**Comment by Exxion** [comment]
So that means we have to figure out what caused THIS one to be indestructible.
That may not be possible unless it happens again and an admin VVs it, though

**Comment by AlphaBuffalo** [comment]
Did you try using a skeleton from the dissolve mutation, that's how the dude became a skeleton in the first place

**Comment by Rei1226** [comment]
I tried using both Melt mutation and regular spawning skellington, putting myself in it. Also used bears. Tried buckling myself to a chair like this guy was, tried having a hardsuit on like this guy did, absolutely nothing no matter what I did, I still died. Don't understand how the hell this happened with this guy. Absolutely fucking hilarious to watch though, but very, very strange.
