### ISSUE TITLE
(WEB REPORT BY: anonymousrex REMOTE: 198.245.63.50:7777) Automatic Robotic Factory 5000 bypasses Silicon Job Bans

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5920]
>Revision 

7a0aa2617dc18c4bb52a11381f57acdc4423d5d6 
>General description of the issue

Was jobbanned for 3 days starting yesterday (ban still in place) and was successfully converted into a functional cyborg.

>What you expected to happen

That the job ban would've prevented the automatic borging, I guess?

>What actually happened

The machine bypassed the ban.

>Steps to reproduce if possible

Get jobbanned from silicons, fight a cyborg with a sonic jackhammer and lose, then get forcibly borged by the Automatic Robotic Factory 5000 (or you can just skip most of that, apply a job ban to a test subject and feed them in).

**Comment by dylanstrategie** [comment]
Missing a check, classic

**Comment by PJB3005** [comment]
Should *definetly* completely delete the corpse though.
