### ISSUE TITLE
(WEB REPORT BY: scribnibblers REMOTE: 198.245.63.50:7777) air to distro gas pump sprite when off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5921]
>Revision (Should be above if you're viewing this from ingame!)

the gas pump in taxi station atmosia tht is a gas pump called "air to distro pump" looks like it is still on when i turn it off
>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Probe1** [comment]
Can't reproduce, whatever was going on was not mapping related I think.

![2](https://cloud.githubusercontent.com/assets/8550416/11163414/eaf250a6-8a9b-11e5-8f37-27a872621264.gif)

**Comment by clusterfack** [comment]
Cant gather more information due to web report

**Comment by PJB3005** [comment]
IIRC this is reported elsewhere (might even be on GitLab), the issue is that the pump appears on when off, and vise versa.
