### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 198.245.63.50:7777) Hole to space in Metaclub escape shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5925]
>Revision (Should be above if you're viewing this from ingame!)
7f084802cc8462a4252bf47c1a8713bb9d4276b4 
seems to be a hole in space in the maint section of the shuttle? as soon as the door was opened a bunch of people started slamming into walls for literally no reason over and over, and wound up dying. There seems to be a corner section that's opened to space in there, maybe that's it? Or it's using some sorta different tiles, I dunno. Either way, killed like 4 people due to ZAS

**Comment by unid15** [comment]
the corner is a visual glitch, something else must've caused it

**Comment by unid15** [comment]
can't reproduce, smoething probably depressurized the shuttle or idk

**Comment by Repth1** [comment]
Can't reproduce, called and waited for the shuttle a few time, opened maint, then nothing. Even tried on centcomm.

There's an oxygen tank in there, so maybe that was the problem?
