### ISSUE TITLE
General borer feedback

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5927]
When a borer is spawned, any ghost with their preferences set will be put immediately in.  

This is sticky.  What if they're waiting to be cloned, they're tired and just want to observe or any other reason?

Positronic brains, diona pods, xenomorph larva, and anything else all have a check that lets players teleport to where it is spawned and sign up or retract.  This is something borers need as well.

```/datum/seed/proc/request_player(var/mob/living/host)
	//writepanic("[__FILE__].[__LINE__] ([src.type])([usr ? usr.ckey : ""])  \\/datum/seed/proc/request_player() called tick#: [world.time]")
	if(!host)
		return

	searching = 1
	var/list/active_candidates = get_active_candidates(ROLE_PLANT)

	for(var/mob/dead/observer/O in active_candidates)
		if(!check_observer(O))
			continue

		currently_querying |= O
		O << "<span class='recruit'>Someone is harvesting [display_name]. You have been added to the list of potential ghosts. (<a href='?src=\ref[O];jump=\ref[host]'>Teleport</a> | <a href='?src=\ref[src];signup=\ref[O]'>retract</a>)</span>"

	for(var/mob/dead/observer/O in dead_mob_list - active_candidates)
		if(!check_observer(O))
			continue

		O << "<span class='recruit'>Someone is harvesting [display_name]. (<a href='?src=\ref[O];jump=\ref[host]'>Teleport</a> | <a href='?src=\ref[src];signup=\ref[O]'>Sign up</a>)</span>" 

```

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/seed_mobs.dm 

This is how it looks for diona pods.  This is well done.

@N3X15

**Comment by clusterfack** [comment]
Is this with yes or always enabled

**Comment by Probe1** [comment]
It would function the same way.

```

	for(var/mob/dead/observer/O in active_candidates)
		if(!check_observer(O))
			continue

		currently_querying |= O
		O << "<span class='recruit'>Someone is harvesting [display_name]. You have been added to the list of potential ghosts. (<a href='?src=\ref[O];jump=\ref[host]'>Teleport</a> | <a href='?src=\ref[src];signup=\ref[O]'>retract</a>)</span>"

	for(var/mob/dead/observer/O in dead_mob_list - active_candidates)
		if(!check_observer(O))
			continue

		O << "<span class='recruit'>Someone is harvesting [display_name]. (<a href='?src=\ref[O];jump=\ref[host]'>Teleport</a> | <a href='?src=\ref[src];signup=\ref[O]'>Sign up</a>)</span>"

```

**Comment by Probe1** [comment]
And personally, this makes testing them in rounds difficult since you get about a 50% ratio of players that wanted to be borers and players that had borer enabled but don't feel like it right this second, or are AFK, and have suddenly become a borer without warning.

**Comment by Probe1** [comment]
Thread Feedback: 

[quote]borers needs some serious TLC if they're going from antags to Chem-pAIs

>Some way to see the health of your host
>Some way to see the reagents currently in your host

Maybe even throw in a universal translation Babelfish style to boot.[/quote]

**Comment by N3X15** [comment]
The borer non-antagifying will take time.  I'll work on this.

**Comment by Probe1** [comment]
No rush, I just don't want to lose feedback after hounding the players that I spawn in as borers for it.
