### ISSUE TITLE
Big trouble in Little Borer..China.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5937]
1.  When a borer evolves a new chem, every existing borer gets the chem.  This creates a big problem.  Any borer that is spawned after something is evolved will never be able to get that chem or ability.  I have not tested farsight but I suspect if a borer is not in a host when it is researched, it will likewise never be able to bestow this on someone.  

2.  During the testing, the other player tried to evolve kelotane directly after evolving inaprovaline so we could test 1. but it did not complete and he was unable to perform any other actions (secrete chemicals, leave host, etc).  I cannot  reproduce that.

3.  Rezadone and Peridaxon are the two rarest chems in the game and available at roundstart for a borer.  Meanwhile, inaprovaline and kelotane which can be found in multiple places at round start must be evolved.  The chemical secretion evolution tree has some work to be done.  For now, it's best if rezadone and peridaxon is either immediately balanced to be end game super unlocks or they're commented out entirely.

4.  Hatching a borer egg in plasma does not seem to work.  I built the gas feeder pipes myself and the xenobiologist said the egg was sitting in the chamber for over 45 minutes with no effect.  I deadminned, set my antag preferences to always, and still it did not grab me from the list of possible observers.
![safety_stopover_fifteen_2015-10-03_10-41-59](https://cloud.githubusercontent.com/assets/8550416/10263453/8e61bf74-69bd-11e5-901b-7ecd392feb6a.png)

@N3X15

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/10263512/2783f2e8-69bf-11e5-8bd9-dad27d53847a.png)

**Comment by N3X15** [comment]
Working on this at the Indie Support Group

**Comment by Probe1** [comment]
You're the best bby
