### ISSUE TITLE
ERT shenanigans

### ISSUE THREAD

**Issue by Skullyton** [d3athrow/vgstation13#5940]
They spawn in the deathsquad prep room (The one with the mechs next door and no way out) so require admin intervention to get them to the proper shuttle, as the deathsquad ferry only works IRC if an admin's called in a deathsquad. This also leads them to think that they ARE deathsquad in power ranger armor so some need telling off.

Their IDs can't be used to transfer the centcomm ferry, so still require admin intervention to get to the station.

A bit of a feature request, but if an ERT is called, it might be a good idea to give them an objective set by whoever called them like deathsquad get, save them being 'clueless' as to the situation on board.

**Comment by Probe1** [comment]
Step ahead of you DB I just changed their landmark to ERT and added new ERT landmarks in the ready room.

I can't do the rest though, that's beyond me.

**Comment by Skullyton** [comment]
Nice

**Comment by Hoshi-chan** [comment]
ERTs need all access. Their access is really spotty and weird, just give them access to the whole goddamn station already, because you shouldn't have to break into chemistry as an ERT.

**Comment by ghost** [comment]
@PJB3005 This one can be closed for the most part, ERT spawning was changed to the ERT resupply room

**Comment by 9600bauds** [comment]
>This one can be closed
