### ISSUE TITLE
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777) Ghosthands on machinery/replicator artifact

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5953]
>Revision (Should be above if you're viewing this from ingame!)
3ebabfface561244ee32a539f90602955b567c52 

>General description of the issue
http://i.imgur.com/fLk57EW.png

no check to stop ghosts from pressing every button

**Comment by Probe1** [comment]
WebM of the effects in action http://puu.sh/ky60U/5a97187162.webm

**Comment by PJB3005** [comment]
feature

**Comment by Angelite191** [comment]
Idea: Instead of removing it. Make the messages only visible from 2 tiles away. That way, you have'd have to be interested in it to see the message spam. I wouldn't want to see this removed honestly.

**Comment by clusterfack** [comment]
Deity """""fixed"""" this
