### ISSUE TITLE
(WEB REPORT BY: weinermaster69 REMOTE: 158.69.55.2:7777) Antags who die and come back as borers reaqquire their objectives.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5958]
>Revision 3ebabfface561244ee32a539f90602955b567c52 

If you die as an antag and are chosen to become a cortial borer, you are informed of your objectives again. This does not happen for other 'rebirth' events such as xenos and diona.

I expected to become a borer, and not be a syndicate agent. 

However, I did come back as a boredyicate and was told my uplink code and objectives.

How 2 Reproduce:
1.Become antag
2.Die
3.Become borer
gratz

**Comment by PJB3005** [comment]
@N3X15
