### ISSUE TITLE
MoMMI alt-clicking plating

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5967]
(WEB REPORT BY: blarghargin123 REMOTE: 158.69.55.2:7777)

>Revision (Should be above if you're viewing this from ingame!)
3ebabfface561244ee32a539f90602955b567c52

>General description of the issue
MoMMI cant alt-click on the floor. I tried alt-clicking on plating but it doesnt work, but it works when I alt-click on the SMES to see under it.

>What you expected to happen
Alt-clicking work

>What actually happened
it didnt

>Steps to reproduce if possible
check your code please

**Comment by Shadowmech88** [comment]
This has existed for a while and is true for all silicons. Alt-clicking works if you click on an object, but not on a turf.
I believe the bug appeared as a result of a PR designed to fix the fact that silicons could alt-click turfs, but not alt-click objects.
