### ISSUE TITLE
Bugs with shield generators

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#5970]
I wanted to set up some shield generators in the event of meteors, and in the process I set up the two shield generators in engineering, those worked great. Then I ordered two more generators and capacitors from cargo, this is where the problem started...
I build the first generator in RnD and it doesn't turn on, I ahelp it, we cant find out what is wrong.
I build another one in tcomms and it doesn't work as well.
I then go back to the two engineering generators and they don't work.

It could be a broken proc, or maybe something more. I don't know, I ain't a coder, but I will never be able to live out my dream of having meteors bombard the station while everyone inside lives peacefully knowing that none of the meteors will ever damage the station. Until some asshole antag power sinks everything, but thats a different story

**Comment by Zth--** [comment]
I believe they have to be perfectly rotated to turn it on, even though there's no rotation sprite. Did you check that?

**Comment by AlphaBuffalo** [comment]
Like the shield capacitor being rotated on the generator? Because I did that. But that also doesn't explain why the generators from engineering didn't work.

**Comment by PJB3005** [comment]
These field gens (the ones with capacitors) are unmaintained caelcode *shudder

**Comment by PsiOmegaDelta** [comment]
If you haven't updated shield generators in forever you may still have the id tagged variants, where both parts need to have the same id to at all connect with each other. This means that newly constructed capacitors/shields (or ones mapped without ids set) may be unable to connect at all, if blank ids are never checked for equality for whatever reason.
