### ISSUE TITLE
Adminghosts can't use APCs

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#5971]
>"You don't have the dexterity to use this the Toxins Mixing Room APC!"

**Comment by Kurfursten** [comment]
Any context? Did you happen to be the ghost of a monkey or animal, for instance?

**Comment by dylanstrategie** [comment]
Nah, just observed at roundstart with Host flags while testing something locally, and tried to turn off lighting on an APC to not have something I was working on turn off

**Comment by clusterfack** [comment]
Just need to modify the dexterity check to always work for ghosts, regular ghosts have other methods to block usage anyway
