### ISSUE TITLE
Discussion: Solars

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#5972]
Solars are an old, reliable power source. They can't power the station alone, even wired to the grid, though. They need to be supplemented with an Antimatter Engine, or some other power source, to reach that level. Part of the problem is that they are too close to the station, making much of their rotational period non-exposed.

![solar angles](https://cloud.githubusercontent.com/assets/9782036/10273518/4b0f15ba-6af7-11e5-87c4-bf85e96827d1.png)

Boxstation is sadly not a box, but rather more of a +. This means that they would have to be moved very far from the station to gain a 75% exposure period. 50% is much more reachable, which I think we should shoot for. If we could move the solars out that far, it would guarantee a minimum of 180KW for wiring the solars at all times (compared to the much easier AME at 160KW).

I'm also considering a flat buff to solar output in the form of changing the glass bonuses. As they are currently, these are the multipliers:
- Glass: .5
- R Glass: 1
- P Glass: 1.15
- R P Glass: 1.3

I was thinking a progression of 1, 1.3, 1.6, 2 would make the Solars a more appetizing prospect for Engineers, and more competitive with other power options, given their setup time. What this would mean is that the default solars would each produce about 27,000 more watts when fully exposed, and 90,000 more if fully upgraded. A +30% bonus is too small for the amount of time it takes to replace every solar with reinforced plasma glass.

**Comment by Zth--** [comment]
:+1: Buff them

**Comment by Hoshi-chan** [comment]
Sounds great. Finally, wiring the solars will be worthwhile.

**Comment by PJB3005** [comment]
Agreed.

**Comment by clusterfack** [comment]
Fine except for the implied 30% straight buff to solars at roundstart I'd say, or you could make them start with regular glass which would also be fine.

**Comment by Probe1** [comment]
Ambivalent.

Don't move a solar to the bomb test range though that's madness.

**Comment by Kurfursten** [comment]
@Probe1 I was thinking more like moving them each around ten tiles out rather than a dramatic change. This would give them a considerably higher exposure period (especially the fore port solars, which have the smallest)

**Comment by Probe1** [comment]
Yeah sure, go for it.  I'm not really too fussed about solars to be honest.  They're the old reliable standbys that take a long time to do but are dependable.  Making them 30% more worthwhile would be nice, but as long as they meet the stations needs when they are all done then hey, they've done their job.

**Comment by Kurfursten** [comment]
They don't meet the station's needs right now. Most of the solars right now have an exposure period very close to 25%, which means we're probably sitting around 120KW with all solars wired into the grid. Moving them out as I suggest would nearly double that output on its own, simply because each solar would have much less downtime.

**Comment by PsiOmegaDelta** [comment]
If it makes relocation any easier, last I checked solars look for opaque objects in a 20 turf range rather than all the way to the edge of the Z-level.

**Comment by Kurfursten** [comment]
@PsiOmegaDelta I appreciate your helpful attitude, but our branch checks 256 turfs (of course, in practice, it never reaches 256 without hitting the edge or an opaque turf).
