### ISSUE TITLE
Converted but Banned from Cult

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#5976]
iirc, converting someone banned from Cult is a real oh shit moment for both parties.

Let's rectify this pls.

Personally, I think it should just work as a gib, or perhaps as a sacrifice rune in a case such as this.

I think there was a similar thing with  Malf, except it borged them anyway- now I believe it just prevents the borging.

I think in all these cases(including Rev, Borer, etc etc) the conversion process should gib rather than fail.

It's a bit unfair perhaps but prevents the ousting of players being stealthy in the early parts of a round to an extent(then again, gibbing leaves a lot of evidence).

**Comment by PJB3005** [comment]
Agreed, I mentioned this on the PR for the borger too.

**Comment by Probe1** [comment]
sac rune yes.

**Comment by Ephx1** [comment]
If it's not stealthy enough to gib, why not just have the mob be deleted and shove some flavor text about the bastard being sent to Nar'Sie's pain dimension or whatever.

**Comment by PJB3005** [comment]
@Ephx1 could work too.

**Comment by nuklearcellphoneg** [comment]
Yeah, see, if they're successful in subduing the person and getting them to the cult rune, I would like for them to have a reward, in the form of a sacrifice.

iirc, sacrifice gibs, however, and that can draw a lot of attention if found and not cleaned up.

**Comment by clusterfack** [comment]
Perhaps give them a chance to learn a word such as with a sacrifice rune (that can only be performed once obviously)

Also I'd give both of them text about not interfering with each other instead of gibbing, but both solutions work really.

**Comment by Hoshi-chan** [comment]
Please gib people going through the autoborger who have a silicon jobban, and have it reset the autoborger's cooldown afterwards, so you don't waste a precious 30-60 seconds on some silicon jobbanned asshole who gibbed instead of turning into a new borg.

As for the cult thing, you need to somehow consider that a stealth conversion isn't just going to waste the cultist's time, but possibly one of a precious few stun talismans, especially early in the round. Maybe have the person produce the blank talisman that cultists start with on gib, with a single use, to replace any resources lost in the attempt?

**Comment by Shadowmech88** [comment]
What about making it standard sacrifice them, but making sacrifices in general bestow a random cult word on those who take part in it?
As far as I know, there's currently no reason whatsoever to perform sacrifices outside of sacrificing a target.

Also the autoborger should 100% gib. The inside of it even sounds like a wood chipper.

**Comment by PJB3005** [comment]
@Shadowmech88 uh, I'm pretty sure it already gives them words.

**Comment by Shadowmech88** [comment]
@PJB3005 I wouldn't really know. I've never actually once seen a cult sacrifice someone who wasn't their target.

**Comment by Kurfursten** [comment]
:+1:

**Comment by nuklearcellphoneg** [comment]
hello i'm late but

THANKS EVERY1 4 input
