### ISSUE TITLE
sound system

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5977]
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777) 

So im at the sound system in the main hallway right north of the mechanics shop thats by the air and fire alarms and atm its telling me im not seeing anything when i try and interact with the sound system

**Comment by Shadowmech88** [comment]
>atm its telling me im not seeing anything

Could you elaborate as to what exactly the message is?

**Comment by Kurfursten** [comment]
It sounds like he's not getting a UI at all, which happens occasionally but is specific to no particular machinery.

**Comment by PJB3005** [comment]
Found it: the fucking thing is depowered.

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/media/broadcast/receivers/radio.dm#L17
