### ISSUE TITLE
Straitjackets are inescapable.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5978]
Feature request 

In every other instance I can think of when a player is restricted by an item (opposed to being walled in "The Cask of Amontillado" style) they can escape after time.  The straitjacket should be double standard cuffs and have a very high probability of breaking one or both arms.  Harry Houdini style.  Dislocate your shoulders.

**Comment by Probe1** [comment]
I was wrong about morgue trays.

**Comment by FudgePucker** [comment]
Give wizards an ability for a spell slot that let's them escape handcuffs and straight jackets. Amaze the crew with your magic skills.

**Comment by Arthurdentist** [comment]
Harry Houdini was a small fucker and he didn't dislocate his arms to escape from straight jackets.

In fact no magician in the history of ever would actually dislocate an arm to do that trick.

**Comment by Probe1** [comment]
I'm getting a strong vibe that I'm the only one that thought this was fun
