### ISSUE TITLE
Allow ghosts to fuck with EVERYTHING after the shuttle docks.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#5979]
:^)

**Comment by Hoshi-chan** [comment]
I'm sure there are reasons not to do this but I can't think of any right now.

**Comment by FudgePucker** [comment]
WEW LAD, POST SHUTTLE GRIFF.
BRING A BUNCH OF BOMBS ONTO THE SHUTTLE AND JUST LEAVE THEM LAYING AROUND, NOTHING BAD WILL HAPPEN IF THEY DON'T HAVE A TRIGGER :^)
:+1:

**Comment by clusterfack** [comment]
We can check this with any non-snowflake ghost code by modifying the ..() check in the top level of machinery/attack_hand to allow ghost touching by checking against the value of the ticker which I think is 3 after round end.

**Comment by PJB3005** [comment]
@clusterfack I already have the code done, I need to make a PR, but first test it.

**Comment by clusterfack** [comment]
*Fulfilling your own requests*

Need them codervalids huh

**Comment by PJB3005** [comment]
:^)
