### ISSUE TITLE
CATBEAST DISCONNECTION

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5982]
(WEB REPORT BY: supersofaking REMOTE: 158.69.55.2:7777)

bc8032d3b8a128694301e3b41c521a75c12d1e64 

>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
If you're a catbeast and you die, re-entering your corpse will cause your client to lag horrifically.  Eventually, you'll get a 'connection closed'.  If you try to rejoin, you'll be sent straight to the 'join game' page, as if nothing ever happened.  You can then join the game AGAIN.  I rejoined as a different character, but I think it's probably possible to rejoine as the SAME character.

>What you expected to happen
I expected to just be put back into my dead catbeast corpse.

>What actually happened
See general description.  I died, tried to go back into my corpse, got disconnected, and then was able to rejoin the game as if nothing ever happened.

>Steps to reproduce if possible
Die as a catbeast, then re-enter your corpse.  Wait until you get 'connection closed', then reconnect.  You should be at the lobby screen.  Hit 'join game'.

**Comment by FudgePucker** [comment]
Oh god, this has a chance to be really really bad.
Can someone test this? If it happens again then this needs the HONK, OH GOD ITS LOOSE, and what other silly tags attached because this is really broken.
Someone who gets cat beasted as a punishment can rejoin the game, someone who died while having the cat beast virus can rejoin, put on internals, and robust the shit out of the virologist.

**Comment by Rei1226** [comment]
Can't reproduce. I'm guessing this is some one time random BYOND bug rather than something specific with bipedal felinefags.

**Comment by clusterfack** [comment]
Rei's test showing nothing is consistent with my prediction it would be nothing. 'Species' alone would have no effect on this. And if there was a catbeast sounds like adminning which can both catbeast and allow someone to respawn.
