### ISSUE TITLE
(WEB REPORT BY: yred REMOTE: 158.69.55.2:7777) Borers and beheaded hosts.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5987]
Revision bc8032d3b8a128694301e3b41c521a75c12d1e64 

Borers die when their host is beheaded, but not when they are gibbed. Seems like they should either die in both circumstances, or live through both.

**Comment by dylanstrategie** [comment]
I'd say the borer should live through both
