### ISSUE TITLE
Holy shit negative oxygen mols

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#5988]
Can you explain what ungodly hell has visited space station 13?  The atmos tech could not explain how it happened and found the air alarm with -59% oxygen.  I analyzed it and found that the mols were **negative**

![system_hut_ii_2015-10-05_20-22-29](https://cloud.githubusercontent.com/assets/8550416/10297313/3d99613a-6b9f-11e5-865f-090ccf9a995e.png)

just

**Comment by clusterfack** [comment]
gonna venture a guess here and say badmins

**Comment by PJB3005** [comment]
Sounds like adminbus to me, never seen this before and nothing recently touched this.

**Comment by Probe1** [comment]
http://pastebin.com/yA6ieKCs

 I see nothing in the logs.

**Comment by PJB3005** [comment]
Weird

**Comment by Probe1** [comment]
I just checked the admin log http://ss13.pomf.se/logs/2015/10-October/

nada.  zip.  nothing.  punic.  pernic.  picnic.

**Comment by Shadowmech88** [comment]
What happened when you pumped oxygen into the room? Did it get closer to 0 mols?

**Comment by Probe1** [comment]
Yes, it repeatedly hit 0 mols and the O2 in the room became CO2.  The person that reported it said they were uploading a video of the round and I was hoping they would show up and flesh out the issue.

**Comment by Angelite191** [comment]
CROPPING THE VIDEO NOW! PLEASE HOLD!

**Comment by Angelite191** [comment]
https://www.youtube.com/watch?v=LCY_S0T2zbM&feature=youtu.be

From the moment it was relatively safe, to the moment I stopped bothering.

**Comment by Shadowmech88** [comment]
>this video is private

**Comment by Angelite191** [comment]
It's unlisted now.

**Comment by mrpain666** [comment]
If this happens again it really needs the OH GOD ITS LOOSE tag.

**Comment by Exxion** [comment]
It probably deserves the tag even if it never happens again

In other news, what in the ungodly fuck?

**Comment by 9600bauds** [comment]
This could happen from exotic seeds but was fixed, not sure what on earth could possibly cause it besides that.

**Comment by ghost** [comment]
@gbasood - I've not seen this reported in a while, we can probaaaaaably assume it's fixed

**Comment by Exxion** [comment]
Wait did you just stretch out the a rather than the o

**Comment by ihadtoregisterforthis** [comment]
_Irish lads_
