### ISSUE TITLE
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777) New Med HUD Problem

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5990]
It occasionally will not show the damage bar for some reason.
example picture: http://puu.sh/kA4ad/2e14b4d376.png

**Comment by Shadowmech88** [comment]
Not a bug, #5931 made it so that the health bar does not show up for people who are at 100% health.

**Comment by clusterfack** [comment]
Mmmm someone make a changelog entry about this feature and I'll close the issue
