### ISSUE TITLE
(WEB REPORT BY: orangerush REMOTE: 158.69.55.2:7777) UI issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#5994]
fc34cfdad8f528fb02a632c56f7d29c849875144

Had a round where a borer gave me enhanced sight and round after that my icons ere all fucked, the spells/ mutant powers looped down when activated. The icons to toggle magboots/ push masks are cutt off, barely on screen. Restarted my game multiple times reinstalled byond. I was playing as a grey both times if that helps. Here's a screenshot.

https://puu.sh/kAjoi/5c4d22cbcc.jpg
Makes the game literally unplayable for me.

**Comment by Shadowmech88** [comment]
Possibly related to #5984.

**Comment by PsiOmegaDelta** [comment]
I saw a similar artifact during the port of that when I accidentally wrote "South - 1", making the element trying to go off-screen.
Not immediately seeing any such typos here tho.

**Comment by clusterfack** [comment]
I'll have to see if I can replicate this and how

**Comment by clusterfack** [comment]
Well the magboots thing is easy, the action buttons need to be shifted down 1 space. I'm not sure about the looping spell objects as that has its own movable screen elements system which I didn't really try to modify.

**Comment by clusterfack** [comment]
Ah I checked and the screen loc system reverse engineers the screen loc by converting the screen loc of the spellmaster back into coordinates and then adjusting it. Since the new system uses text forms I'm fairly sure that's what went wrong.
