### ISSUE TITLE
UI is fucked

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#5995]
Equipment icons in the top left are missing, borg "backpack" is covered up by their three module icons and therefore inaccessible, and the spell HUD as wizzyman cannot be moved or adjusted.

There seems to be a missing equipment slot too, but I could just be imagining that.

**Comment by Probe1** [comment]
@clusterfack could it be related https://github.com/d3athrow/vgstation13/pull/5984

**Comment by clusterfack** [comment]
Yes, already fixed most of the issues but they still exist because it was after roundstart
