### ISSUE TITLE
Bugs with shield generators Part II

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6009]
This is stuff I am recently finding, to keep it simple Im going to list a few of the more important ones.
1. You cant deconstruct shield emitters after building them.
2. The menu will keep opening even if you do not open it yourself if the generator gets a block update (don't know if that's what doing it, but it seems to be so)
3. Newly built shield generators do not work. (already an issue, I know, just felt it would be best to move the conversation here since this is a new issue)

**Comment by Zth--** [comment]
Close the other one and make only one big issue

**Comment by AlphaBuffalo** [comment]
I thought I did, but its close now
