### ISSUE TITLE
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777) Make it possible to buckle chickens to chairs again already.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6018]
>Revision a8f3ccec43af4997c5e8f914b8f94c9991f3691d 
In days long past, botanists, botany hobbyists, and chicken worshippers could buckle chickens to chairs. This allowed for pseudo-chicken coops and you no longer had a bunch of chickens being underfoot and it as easy to tell at a glance who needed more wheat when.

**Comment by Hoshi-chan** [comment]
Please, Pomf is never going to agree to the enslavement of his people by chairs.

**Comment by Probe1** [comment]
grow wood

build wooden barriers

build wooden doors

have coop

**Comment by clusterfack** [comment]
I thought we already brought this back? 

Thought unid did it while preventing them from the very small animals from being buckled too.

**Comment by unid15** [comment]
Yeah, raising size of chickens to SIZE_SMALL (2) will make them buckleable
