### ISSUE TITLE
Silicons can't *fart

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6019]
Fix this.

**Comment by PJB3005** [comment]
No.

**Comment by AutismSpider** [comment]
Silicons don't have butts so fats.

**Comment by Cyadox** [comment]
@AutismSpider 
what about buttbots

**Comment by PJB3005** [comment]
@Cyadox they are made from a butt...

**Comment by AutismSpider** [comment]
butt bots are made form butts though

unless you want slap or put a butt on cyborg/mommi some how and it can make fart sounds with that.

**Comment by Cyadox** [comment]
>they are made from a butt...

That's the point. They ARE a butt. They should fart like a butt, __*god*__.

**Comment by DeityLink** [comment]
buttbots aren't silicons. /debate

**Comment by ihadtoregisterforthis** [comment]
You can't even fart as a carbon without a butt.
You could add a special emote for silicons, but never a true fart.

**Comment by AutismSpider** [comment]
@DeityLink buttbots are just passive robot mobs

**Comment by DeityLink** [comment]
@AutismSpider They're NOT EVEN MOBS.
