### ISSUE TITLE
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777) misaligned firelock on meta

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6022]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
http://i.imgur.com/E36V6z7.png  arrivals firelock dir is like 6 and should be 8

I'll fix it

**Comment by PJB3005** [comment]
Correction, it's dir 8 and should be 4
