### ISSUE TITLE
(WEB REPORT BY: hurr REMOTE: 158.69.55.2:7777) Identification Computer bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6023]
>Revision (Should be above if you're viewing this from ingame!)
38a6ba9be99e91b148dd67bcbd689cc586ead170

>General description of the issue
some of the accesses that you set on an ID with the Identification Computer are wrong.

>What you expected to happen
+
>What actually happened
for example, if you activate the access for "EVA" it doesn't give you the access to EVA; on the other hand, if you activate the access to "power equipment" it gives the access to EVA. i only tried EVA so i dont know how many accesses are wrong.

>Steps to reproduce if possible
use a blank ID and try to activate an access each time, then try to open the related door.

**Comment by Probe1** [comment]
What map was this on @Hurr

**Comment by uazuaz** [comment]
sorry, it's on box station.

**Comment by Kurfursten** [comment]
Last time I checked, the EVA doors don't use EVA access, and instead use medical+engineering+security, which is why IAAs steal med suits all the time.

Map issue.
