### ISSUE TITLE
Bleeding is far too overpowered

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6026]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

38a6ba9be99e91b148dd67bcbd689cc586ead170 
I think just about anyone can confirm how ridiculous bleeding is. If you're bleeding internally and externally, you're pretty much dead within the next 30 seconds no matter what you do. 

Blood loss needs to slow the fuck down and not kill you as fast. Shotguns are probably the most lethal weapons, and it doesn't even matter what range they're fired at, or what limb they're targetting, you basically will always die. But thats just the extreme example, even minor examples like a fire extinguisher hit to the chest causing something to rupture and you to start bleeding is enough to kill you in less then a minute.

**Comment by PJB3005** [comment]
Definetly.

**Comment by Shadowmech88** [comment]
I think blood loss should remain powerful overall, but whether a particular bullet kills you or not would be based on chance. If you get shot in a major artery, bleeding to death within a minute is fairly realistic.
However, I don't think all bloodloss ever should act as though you just had your jugular sliced. It definitely needs reworking.

**Comment by clusterfack** [comment]
But that's how deadly blood loss is in real life? What do you think kills most people when getting shot?

**Comment by FudgePucker** [comment]
Make a way to make ghetto bandages from jumpsuits so you can save yourself from external bleeding. Nerf internal bleeding. If someone comes into medbay you have to perform a lengthy surgery then have to replenish blood, that takes a long time with no O- bags around. Might be faster to just saw them in the face and throw them into the cloner.

**Comment by Shadowmech88** [comment]
@clusterfack The point is that ALL of our blood loss is that deadly.
No one dies in two minutes in real life from a bullet to the hand or foot.

**Comment by FudgePucker** [comment]
@Shadowmech88 maybe reduce blood loss from limbs?

**Comment by Shadowmech88** [comment]
@FudgePucker 
It's not about just whether it's a limb. You could get shot in the side of the torso and survive, and yet a shot to the leg could kill you if it hits the femoral artery.
I think each individual shot should have a certain chance to cause a certain amount of blood loss, based on how many major and minor arteries and veins exist in that part of the body, and how large they are in comparison to the size of the body part itself.

**Comment by dylanstrategie** [comment]
From what I've seen, humans have a bit too much blood (which means you're wasting more blood pockets on them that you should be), but at the same time they bleed like a stuck pig for the smallest wounds

The other problems is that the last time I tried to work on wounds, I broke everything. Someone should look at it, even just to unfuck that code

**Comment by SarahJohnson489** [comment]
Just don't tone it down too much so it's like the old days and you can just eat some bustanuts to walk it off. Let's not forget the guy that ruptures his lung at the start of a shift and 3 hours later it's done fuckall.

**Comment by CptWad** [comment]
reviving discussion
im all for a nerf
either reduce amount of blood lost per tick, because losing 15% of your blood from a nasty shard wound, is logical but 40% is bullshit
A time reduction should be needed for the longer bleedings
:+1:

**Comment by Probe1** [comment]
Discussion ran its course.
