### ISSUE TITLE
"related accounts fingerprint" what the actual FUCK?

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6027]
http://imgur.com/UHScDQM

I've either found an odd bug or BLOWN THE CONSPIRACY WIDE OPEN

**Comment by Probe1** [comment]
What the hell does it even mean

**Comment by Shadowmech88** [comment]
Maybe it's accounts who are frequently on when they're on, in case that player's being looked at for metagaming?

**Comment by Rei1226** [comment]
Can a coder please comment as to what the fuck this new addition is supposed to mean? It's listing over 100 players like, every time, for everyone. Even brand new players.

**Comment by clusterfack** [comment]
Pomf did it and told no one what it is, I have no idea.

**Comment by mrpain666** [comment]
It makes the panel a fucking clusterfuck of what is more than likely just useless information.

**Comment by Probe1** [comment]
@d3athrow how do we utilize this information?

**Comment by Wizardcrying** [comment]
what are these magicks

**Comment by N3X15** [comment]
This is some secret repo shit, no idea what it is.

/cc @d3athrow

**Comment by mrpain666** [comment]
http://ss13.pomf.se/forum/viewtopic.php?f=26&p=7284#p7284
