### ISSUE TITLE
came out of cryo and couldnt stand up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6029]
(WEB REPORT BY: spacestation1000 REMOTE: 158.69.55.2:7777)

>Revision whats that

>General description of the issue
couldnt stand up after cryo, but i could slide around on the floor.
when someone attacked me, the character suddenly jumped up, then i got hacked to pieces.

>What you expected to happen
that i can stand up after cryo.

>What actually happened
i got ejected, lay down. someone tried to wake me up,didnt work. i could slide around on the ground until someone attacked me.

>Steps to reproduce if possible
i got haunted by some bats, i could walk into medbay and then i fell flat.someone stripped me naked, put me into genetic sequenzer and cloned me.
got put in cryo and couldnt stand up.

**Comment by mrpain666** [comment]
What chemicals were present in the cyro tube you were in? Do you know?

**Comment by Kurfursten** [comment]
@clusterfack @N3X15 Maybe doesn't happen anymore http://strawpoll.me/6065432/r

**Comment by ghost** [comment]
I've had this happen with vampires. Not sure if it's fixed.

**Comment by 9600bauds** [comment]
This happened to one of my patients just this week.
He was able to move just fine, but was gliding around. He punched himself to fix it.
Was recently cloned if it helps, might possibly be related to brain damage?

**Comment by clusterfack** [comment]
I've coded some things that are useful that let me know whats wrong with this.

It lacks 'update_canmove()'.

So what it must be doing is somewhere in cryo code it is setting lying to 0 or stunned to 0 or what have you without calling update_canmove(), so the icons are not being corrected for the sprite.

**Comment by Exxion** [comment]
I'm pretty sure it has to do  with clone damage because here are the things we _know_ can cause it:
1. Cloning
2. Slimes
3. Vampires

All of these cause clone damage.

**Comment by 9600bauds** [comment]
Clone damage does nothing though, it doesn't make your legs fail or anything, it's very bizarre

**Comment by Kurfursten** [comment]
Clone damage can make your leg misshapen which causes you to collapse

**Comment by 9600bauds** [comment]
Are you sure that's general clone damage and not some special effect?

**Comment by Kurfursten** [comment]
The slimes do it and I am pretty sure the cloner does too, but someone would have to read the code
