### ISSUE TITLE
Defficiency map issues

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6030]
I'm not totally sure if it was someone being a shitter or what, but there are a few doors in robotics and mech bay with walls underneath of them on defficiency.

Also, robotics lacks the radiation overlay, so it doesn't flash green even though it is definitely NOT a shielded area.

**Comment by Shadowmech88** [comment]
The fake doors are a feature, hence the "fuck you" written on the wall underneath.

**Comment by Hoshi-chan** [comment]
I laughed every time someone asked me to open that door.

**Comment by Ephx1** [comment]
![fallout4neu](https://cloud.githubusercontent.com/assets/6224074/10377955/352982c8-6dd4-11e5-8a6d-25b5fed6509c.PNG)

**Comment by Duny-** [comment]
I modified robotics so many times that day I forgot to remove the wall under the mechbay door I had moved for the 20th time. Will be fixed soon.

**Comment by unid15** [comment]
b-but it's a feature
