### ISSUE TITLE
Put an actual damn fax machine at Centcomm 

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6033]
I wanna go back and look over the faxes but I can't.  I don't know how to do this and ensure admins see the message AND it gets delivered.

**Comment by DeityLink** [comment]
I'm going to revamp the fax system. It's really REALLY bad right now and I say it all the time.
Admins will have a button to check received faxes, (with buttons to jump to the sender fax/player)
and their replies won't anymore be sent to EVERY SINGLE FAX on the station.

**Comment by Probe1** [comment]
this will be nice.

I don't think that last thing happens though.
