### ISSUE TITLE
(WEB REPORT BY: kernikov REMOTE: 158.69.55.2:7777) MOMMIs lack a soldering iron

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6034]
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Title

>What you expected to happen
Mommis having an iron to fix emagged doors.

>What actually happened
Mommis did not have a soldering iron.

>Steps to reproduce if possible

**Comment by Ephx1** [comment]
Then grab one.

**Comment by AutismSpider** [comment]
mommis can build and grab a soldering iron. 

As a mommi use a plastic bag as a hat and stick the soldering iron and other tiny tools in it

**Comment by PJB3005** [comment]
wow @AutismSpider that's really clever

**Comment by AutismSpider** [comment]
Wish mommis had bag slot so i can hold rods and shit but plastic bag to hold cables and the soldering iron is fine too.

**Comment by clusterfack** [comment]
Not broken
