### ISSUE TITLE
The great cryo vanishing act

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6037]
(WEB REPORT BY: orangerush REMOTE: 158.69.55.2:7777) 

a3b460ccca267959b4ffa244a74ca8627e9247b2 
I was a diona nymph and I told a doctor to put me in a cryo cell, he did but i started to take damage so I told him to turn it off. after he turned it off I tried to get out of the tube but I wasn't in it anymore but I was still taking damage. Another little diona was around and he jumped in the same tube I was in but he was able to get out of it. I moved aroud with wasd, the arrow keys and i even hit the eject button on the objects tab. Not sure how you could replicate the event though.

**Comment by DeityLink** [comment]
The player was probably sent into nullspace with its client.eye still on the cryo.

**Comment by ghost** [comment]
Negative, the player was sent into the cryo's contents, happens with sleepers too

**Comment by 9600bauds** [comment]
I believe this should be fixed since I made medical equipment eject bad contents

**Comment by ghost** [comment]
@gbasood - @9600bauds fixed this.
