### ISSUE TITLE
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777) AI's cannot import settings to the AAC (Atmospheric automations console) console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6041]
>Revision 2c537a1714820d173a1889ffbbc4482267503273

AI's can't import configs to the AAC. Apparently there's an adjacent check?

You can do it as a person, dunno if you can do it at range as a borg/mommi. It's valuable for us to update things like scrub N2O quickly

**Comment by PJB3005** [comment]
The issue is caused by the input code, it has an adjacency check to make sure the user is still next to the AAC (though no `stat` checks...), and, chances are the AI isn't gonna be adjacent to the AAC.
