### ISSUE TITLE
Monkey chemical circulation is broken.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6042]
(WEB REPORT BY: weinermaster69 REMOTE: 158.69.55.2:7777) 

> Revision 2c537a1714820d173a1889ffbbc4482267503273 
> Simple mobs like monkies won't process chemicals like they should be.

I expected the monkey to swallow 100u of radium in 10u intervals and produce some antibodies at some point. 

Instead it only accrued toxin damage, no antibodies were produced.
1. Infect a monkey with a virus
2. Inject radium
3. Watch nothing happen

**Comment by dylanstrategie** [comment]
Are you sure this isn't simply because antibodies are generated on RNG ?

**Comment by DeityLink** [comment]
Working as intended. simple animals are "simple" because their Life() isn't as complexe as carbons/silicons'. It's a sacrifice so we can have many of them without affecting performance too much.

**Comment by clusterfack** [comment]
Monkeys aren't simple mobs, they're carbons

**Comment by DeityLink** [comment]
oh, right, title was misleading.

**Comment by despotate** [comment]
Definitely working as intended. Antibodies are RNG-based.

**Comment by Probe1** [comment]
And its definitely not broken.
