### ISSUE TITLE
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777) Portals and chairs.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6047]
>Revision (Should be above if you're viewing this from ingame!)
776facf6e47126ce247e0dbd9a15a38aec60a067

>General description of the issue
You can touch portals while buckled and be teleported, but you'll be permanently buckled and unable to move.

>What you expected to happen
Chair buckling being removed in such a case.

>What actually happened
It didn't.

**Comment by PJB3005** [comment]
@DeityLink

**Comment by dylanstrategie** [comment]
Leaving on DeityLink to fix since he's working on portals currently

Ideally, non_anchored locked_to atoms should go through the portal, and anchored locked_to atoms should prevent portal usage. Or something like that

**Comment by DeityLink** [comment]
aye I'll fix that when I get back home. Tomorrow hopefully.
