### ISSUE TITLE
(WEB REPORT BY: cyadox REMOTE: 158.69.55.2:7777) Custom Grenade Won't Go Off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6048]
>Revision (Should be above if you're viewing this from ingame!)
776facf6e47126ce247e0dbd9a15a38aec60a067

>General description of the issue
Created a custom grenade consisting of Space Cleaner 50u and Foaming Agent 50u beakers. Screwed together, icon shows okay. Clicking on it shows me text that it's primed, but never flashes or goes off when thrown. Subsequent armings produce exact same results.

>Steps to reproduce if possible
I was using the premade casings in Chemistry if that makes a difference, otherwise made as a typical grenade.

**Comment by ihadtoregisterforthis** [comment]
Was there a fuse mechanism?

**Comment by Cyadox** [comment]
I authored this. They appear to be pre-fused, since examining them showed it had a timer of 5s prefer I put the reagants in, and I couldn't add a timer/fuse mechanism even after removing the reagants and rebuilding it several times.

**Comment by SarahJohnson489** [comment]
Casing's don't have a build in igniter assembly. It's a poorly thought out desc line that was probably left in from when they were first made constructable. 

You likely didn't ready the assembly. Next time you're playing, screwdriver the timer and igniter to make sure they're set to attachable.Stick them together to make a timer-igniter assembly, screwdriver the assembly to make it ready, then set the settings to what you want. Use it on the grenade. Not putting an igniter assembly on the grenade so when you chucked it in the brig it'd always be flashing was a fun clown thing.

**Comment by Cyadox** [comment]
There was no message, though if I recall I didn't screwdriver the igniter/timer assembly after assembling it. Might be worth noting that the chemist's guide to grenade making is severely lacking if that's the case. I'll try it again with Chemistry's parts, and update the wiki if it's just my own stupidity.

**Comment by Cyadox** [comment]
Turns out it was just me. I'll update the wiki accordingly.

**Comment by Probe1** [comment]
@clusterfack good 4 close 2 me 1 2 4 8
