### ISSUE TITLE
Players are getting crippled after getting out of cryo

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6049]
so I dont know what exactly is going on, I am seeing a spike of players enter cryo through normal means (getting killed, cloned, then cryo'd) then literally not being able to move after getting spit out of cryo.

**Comment by N3X15** [comment]
```
<dylanstrategie> N3X15, there's a serious problem with all medical scanners and cryo, where you can shove a mob straight into the machine's content if you try to put two at once
<dylanstrategie> Which causes people to disappear inside cryo or the sleeper
<dylanstrategie> I honestly don't know how to fix it, because it happens so quickly the machine can't check properly for if(occupant)
```

**Comment by mrpain666** [comment]
SHIT

**Comment by N3X15** [comment]
We're discussing it in IRC

**Comment by Probe1** [comment]
Issue was first reported here, same day it first occurred to my knowledge
https://github.com/d3athrow/vgstation13/issues/6029

**Comment by clusterfack** [comment]
pfff "it happens so quickly the machine can't check properly for if(occupant)"

someone doesn't know how single threaded programs work

**Comment by PJB3005** [comment]
My thoughts exactly @clusterfack, seriously shouldn't be hard to fix.

**Comment by mrpain666** [comment]
Havent seen this happen lately. Was it fixed?

**Comment by dylanstrategie** [comment]
Needs rechecking and/or reproduction steps

The general idea is that it was a problem with limbs, but it appears to have kinda fizzled out

**Comment by Probe1** [comment]
saw it 3 minutes ago on the shuttle.

**Comment by N3X15** [comment]
```
<dylanstrategie> Either way, issues like [6049] should be closed since the last report was 25 days ago
```

**Comment by mrpain666** [comment]
Here let me help you
