### ISSUE TITLE
Ghosts can trigger proximity sensors

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#6051]
Revision: 56751dda5a51e47843b6c15cd06eec49146e4291

Ghosts are able to trigger proximity sensors - or at the very least, proximity sensors as in the proximity sensor-speaker assembly shown below.

![ghosts can trigger prox sensors](https://cloud.githubusercontent.com/assets/5942183/10409221/1377489c-6f17-11e5-98ae-1ea431b0517b.png)

When ghosting into the proximity sensor's trigger area (in this case, a 3x3 area around the sensor) or moving inside this area as a ghost, the proximity sensor triggers (which in this case means activating the speaker).

**Comment by dylanstrategie** [comment]
Was already reported somewhere else

**Comment by Probe1** [comment]
I reported it on gitlab but didnt' bother crossposting all my issues from there.  We're good.
