### ISSUE TITLE
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777) Poison Berries From Exotic Seeds Crate Spam Logs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6063]
>Revision (Should be above if you're viewing this from ingame!)
69c350919b8e4961b791b5cafe42d6c8f2d2b38f 

>General description of the issue
Not sure if this person was harvesting the berries or eating them or what, but every single time he would do it, 6 admin log messages of ADMIN LOG: A water/potassium explosion reaction has occured in Vox Hydroponics - 161,136,1. (VV) - Last Fingerprint: N/A would pop up every single time. Started to get very spammy very fast.

**Comment by FudgePucker** [comment]
Most likely reason is that there is an exotic plant that has water and potassium as two of its products, meaning every time it was harvested it sets off a water potassium reaction.

I am guessing a possible solution would be to prevent there from being chemicals that have special reactions like that, so you don't get flash powder plants, smoke plants, foam plants, or exploding plants.

**Comment by clusterfack** [comment]
Yeah we've known about this for awhile

**Comment by FudgePucker** [comment]
@clusterfack Would it even be possible to make it so that some chemicals won't be picked if another chemical is picked with byond? (IE: if it picks at random to have potassium, it won't pick water.)

An easier way to do this might be to just remove the chemicals that might cause an reaction.
Remove potassium, uranium, foaming agent, plasma, and glycerol from exotic seeds and there won't be any bad reactions upon harvesting.

**Comment by clusterfack** [comment]
Yes there should be a number of varying ways to fix this ranging from very hardcoded to slightly more complex and softcoded. But I'm not familiar with hydroponics code at all to attempt it.

**Comment by FudgePucker** [comment]
@clusterfack The exotic seeds doesn't seem that complex. https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/seed_datums.dm#L224

Heck just removing the chemicals that cause instant reactions would be so easy even I could do it. Its a nice simple list right there.
