### ISSUE TITLE
Borer ckey related issues

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#6073]
A player who died during the round became a borer from a laid egg. The player's old body was found but someone cut out the brain and put in an mmi. Said player was immediately taken out of his borer form and put back into his brain as the mmi.

**Comment by Shadowmech88** [comment]
I feel like this should be a preference setting for all things. As in, a person can choose whether to jump back to their real body if it gets cloned/MMI'd and their ckey is inside a borer/nymph/what have you.
