### ISSUE TITLE
Bhangmeter menu closes if you open it from a distance as observers

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#6079]
Don't know what is up with that

**Comment by ihadtoregisterforthis** [comment]
Standing
On the edge
Of the console
Makes it werk just okay

**Comment by dylanstrategie** [comment]
Seems to be a problem with the UI aggressively closing itself if you get out of range, which is obviously not intended. NanoUI and affiliates has a thing for being too far to see the computer's contents

**Comment by 9600bauds** [comment]
c tag
