### ISSUE TITLE
Sprays are borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6083]
(WEB REPORT BY: kernikov REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
7f6b8df611bee9fc76d07b3ae89a6f1357da56f6 

>General description of the issue
Fire extinguisher sprays go over tables but spray bottle spray does not.

>What you expected to happen
I expected to be able to spray my bottle over a table.

>What actually happened
The table had a magic wall stopping it from spraying my monkey cubes.

>Steps to reproduce if possible
Put monkey cubes on the table in xenobio, attempt to spray them with a spray bottle of water.

**Comment by Kurfursten** [comment]
Technically a feature request, since sprays have never gone over tables, and extinguishing over tables is recent.

**Comment by DeityLink** [comment]
I guess it DOES already work on some servers: https://www.youtube.com/watch?v=ZME1pabq4lI
