### ISSUE TITLE
Disabling GhostEars does not show only speech from nearby mobs

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#6089]
Revision: 91fa1f4ed136d2766e78852edae912cbe9560fd7

Although GhostEars is disabled (checked by toggling it to enable it and then toggling it again one minute later), speech from all mobs are shown in the chatbox.
Mildly inconvenient on lowpop, impossible to follow what's happening on highpop.

Possibly not the easiest thing to reproduce on a test server, but self-evident on the main server.

![ghostears disabled all speech shown](https://cloud.githubusercontent.com/assets/5942183/10433902/13fcdbc8-7116-11e5-8e0a-20c5a934e433.JPG)
You'll notice that most of the chatter is not bolded as it would be if they were all nearby mobs (although with the silicon font, only the text before their dialogue is obviously bolded, e.g. "**T.S.U.N.D.E.R.E. states**" as opposed to "**T.S.U.N.D.E.R.E.** states").

**Comment by ihadtoregisterforthis** [comment]
IIRC disabling such option makes it so you only hear things near your body. Thus, as an observer, this would easily be broken. Or not

**Comment by N3X15** [comment]
Tested reproduction locally by toggling GHOSTEARS off and waiting for poly or runtime to yell something.  Seems to work properly.
