### ISSUE TITLE
Treadmills bugs

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#6090]
They can't be rotated or unwrenched

>Collin Bennet secures the the treadmill generator to the floor.
>Collin Bennet secures the the treadmill generator to the floor.
>Collin Bennet secures the the treadmill generator to the floor.
>Collin Bennet secures the the treadmill generator to the floor.

**Comment by Kurfursten** [comment]
They can be unwrenched, the message is just wrong. I'll hotfix it.

**Comment by Kurfursten** [comment]
@N3X15 This can be closed, it was fixed in the hotfix
