### ISSUE TITLE
Plasmaman suits are ridiculously powerful

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6093]
As if spawning with snowflake EVA gear wasn't bad enough, they can't be properly searched by security due to the suit obscuring most of their gear, and you can't remove it since they'll burst into flames. ~~Also, ALL plasmaman suits are immune to flashes and flashbangs, which is some hot bullshit.~~ not anymore

I have no idea how this can or should be addressed, but after trying to fight a greytider plasmaman the other round, it's definitely a fucking issue.

**Comment by Exxion** [comment]
They... they block flashes and flashbangs? *Why?*

**Comment by Hoshi-chan** [comment]
Because it makes sense from a logical standpoint, I'd assume, even though it's fucking overpowered as all hell. I'm willing to bet it also acts as a welding mask and head protection.

**Comment by Exxion** [comment]
It would make sense for engineering ones to work that way, but *all* seems a bit excessive

**Comment by Hoshi-chan** [comment]
See, the problem with only certain plasmaman hardsuits doing certain things is that it makes them changing job a pain in the ass. It means that in addition to everything else a department has, it'd have to have a stock of plasmaman suits just in case, and that's NOT the ideal way to deal with this.

**Comment by Exxion** [comment]
If I'm not mistaken, Vox hardsuits are already like that.

**Comment by Hoshi-chan** [comment]
Are you sure? I don't think I've ever seen spare vox hardsuits lying around.

**Comment by Exxion** [comment]
What I meant was that the different Vox hardsuits act differently. They definitely have different defense stats and I think the engineering ones have welding protection.

**Comment by Hoshi-chan** [comment]
Well, it makes sense. It should probably function that way, but it doesn't.

**Comment by ihadtoregisterforthis** [comment]
~~_if we had skeletons this wouldn't happen_~~

It's a feature of course.
Close this before certain French coder comes and either changes them so oxygen can pass through or completely revamps plasmamen into purple vox.

**Comment by Hoshi-chan** [comment]
I booted a local server up just to confirm what I've said, since I've never actually BEEN a plasmaman. A plasmaman assistant, right out of the gate with what he's wearing, is immune to both flashes and flashbangs, but his suit does not protect his eyes from welding, and offers no protection against blows, the way that a helmet would.

**Comment by Probe1** [comment]
clearly this was not intended and the result of lazy coding.

**Comment by ihadtoregisterforthis** [comment]
Plasmamen don't have hardsuits by the way. They are softsuits: heat and hits go through. You could make flashes affect them as an exception.

~~_**bring back the ack already no one would play plasmamen and no one would abuse this**_~~

**Comment by icantthinkofanameritenow** [comment]
Addressed in #8630

**Comment by ihadtoregisterforthis** [comment]
Closeable
:high_brightness::sparkles:      :fire:‪:skull:‪:fire:

**Comment by ihadtoregisterforthis** [comment]
Well as long as this is not closeable how about a transparent softsuit for problematic flaming subject?
You give this to sec and they force a suspect to wear a futuristic bodysuit so they can't hide if they're muggling the CMO jumpsuit on themselves, while not combusting in the act.

![prisoner of visibility](https://cloud.githubusercontent.com/assets/13305885/14262714/334c6c7c-fa8d-11e5-81c1-613582fdd009.png)
![transparent](https://cloud.githubusercontent.com/assets/13305885/14262728/43446f44-fa8d-11e5-8ef0-d64bca486a53.png)
I yet have to come up with some helmet.

**Comment by 9600bauds** [comment]
I think this is mostly closeable now

**Comment by Imagebard** [comment]
You can still hide a CMO jumpsuit under your suit and NOBODY WILL KNOW
ITS A TRAITOR OBJECTIVE CHRIST

**Comment by 9600bauds** [comment]
That's why I gave their suits infinite extinguishes
You can search them for whatever, then tell them to suck up the 3 burn damage they'll take or give them sleeper dermaline if they whine
