### ISSUE TITLE
Vine fruit production chance is too low

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6096]
(WEB REPORT BY: killette2 REMOTE: 158.69.55.2:7777)
In the code, once a vine reaches maturation rate, no matter what it only has a 20% chance to produce fruit once or not at all. Please raise or make this 100% so effort making 26 fruit vines is not wasted.

**Comment by Killette2** [comment]
This is still an issue.

**Comment by 9600bauds** [comment]
No longer
