### ISSUE TITLE
AI holopad speaking/hearing is broken

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6099]
The AI can no longer hear itself speaking when it uses a holopad, and additionally, the formatting is broken when other people speak, in the format of:

>Holopad received, Anne Tagg says, "Anne Tagg says, "Hello!""

**Comment by Hoshi-chan** [comment]
Correction: The AI cannot speak out of its holopads anymore, PERIOD. Using :h does nothing.

**Comment by Ephx1** [comment]
Holopads work now, but instead of being unable to use them, you can't use them privately.
As in, what you say on the holopad will also be spoken by your core, which is usually right next to your radio and broadcasts it all.

**Comment by SangriaMonkey** [comment]
That sucks.
