### ISSUE TITLE
Treadmill sounds are awful

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6100]
CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK CLICK

**Comment by N3X15** [comment]
Seriously awful

**Comment by AutismSpider** [comment]
give it a vrrrrr sound for the love of fuck click sound is fucking awful

**Comment by Kurfursten** [comment]
That's not a bug, it's a feature request!

**Comment by Zth--** [comment]
Clickity click

**Comment by Rei1226** [comment]
I think the bikehorn sound might be a good placeholder until we get a real treadmill sound.

**Comment by Kurfursten** [comment]
It's either that or we use the emagged hailer sound effect. You know, "I'll fuck your shit up you shiteating abortion..."

For every single step

**Comment by Rei1226** [comment]
Better yet, do away with the bike horn, introduce the air horn, and then combine the angry beepsky and airhorn sounds into one.

This way it's like there's a very angry robot behind you constantly airhorning in your ear and cursing at you, telling you to run faster.

Maybe then that SMES will one day reach 100% in that gym.

**Comment by ihadtoregisterforthis** [comment]
CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP CLAP
