### ISSUE TITLE
Terrible change to "Make Pills" buton.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6102]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
It is now autoset to 20 instead of 10, please revert back to 10. I usually never need to press 20 excpet on the occasions when ryetalyn or dex+ is needed. It is unneccisary compaired to the other chems that dont even have the ability to go that high at once.
Please revert with haste.

**Comment by Iamgoofball** [comment]
nice
# BUG
report

**Comment by Probe1** [comment]
@kurfurst

**Comment by Probe1** [comment]
also shutup goofball you're a goof

**Comment by Kurfursten** [comment]
It's not actually set to 20, it's set to max_pill_count, meaning if you upgrade it, it'll default to 30

**Comment by Probe1** [comment]
Why was it set to 10 before then?

**Comment by Kurfursten** [comment]
It was a magic number

**Comment by 9600bauds** [comment]
Not a bug, but a valid complaint. 10 is kind of what you'll be using most of the time. I'd rather let magic numbers work their magic.

**Comment by ihadtoregisterforthis** [comment]
Easy fix and quality for some
