### ISSUE TITLE
Silicons can receive money transfers, which is pointless and annoying

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6103]
Spaceman sends you $1!
Spaceman sends you $1!
Spaceman sends you $1!

**Comment by Probe1** [comment]
@deitylink

**Comment by Zth--** [comment]
God fucking damn Hoshi, every time I see your avatar I think it's from an old local band http://puu.sh/kIwVx/706f8c8c60.jpg

**Comment by DeityLink** [comment]
hhhhehehe. I'll make it so you can't send money to silicon PDAs.

**Comment by Probe1** [comment]
@Zth-- blame rainicorn

![1423966066231](https://cloud.githubusercontent.com/assets/8550416/10451111/2819bd64-716c-11e5-8299-6f4b7667b5cc.jpg)
