### ISSUE TITLE
Saycode broke everything

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6104]
Languages are broken
Monkey talk is broken
Vox talk is broken

And now deadchat is broken.

TUUUMBLING DOWWNNNNNNNNNN

**Comment by Hoshi-chan** [comment]
What&#34;re you talking about? Everything&#34;s fine!

**Comment by clusterfack** [comment]
Crack a few eggs and all that

**Comment by Probe1** [comment]
The specifics are monkeys can communicate over sol common by setting their default language to none.  I assume this is for multiple things.

**Comment by Probe1** [comment]
deadchat does not process apostraphes correctly.

>(Follow) DEAD: Test Dummy complains, test it&#39;s

**Comment by N3X15** [comment]
That's already fixed.

**Comment by N3X15** [comment]
Okay, I think I addressed all these issues.  I can't honestly tell since they're so vague, but I fixed things that may be what you nerds are talking about.

Next time, make seperate issue reports for each problem so they can be tracked and properly documented.
