### ISSUE TITLE
Show/Hide GhostEars doesn't work since saycode update

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6112]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
ee03680028b638895dfce159ca65b73bba86f791 

No matter how many times I turn it to set local only or set it so i can hear everything in the world, it will still only let me hear locally when observing. Other people seem to have the same issue, but reversed.

**Comment by PJB3005** [comment]
See #6179
