### ISSUE TITLE
Welding fuel spills don't ignite

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#6116]
![ishimura port romeo 2015-10-14 001814](https://cloud.githubusercontent.com/assets/5303834/10474791/31d2e66c-7209-11e5-85ba-199a28b26a1f.png)

Pic related.

**Comment by Angelite191** [comment]
![ishimura port romeo 2015-10-14 002124](https://cloud.githubusercontent.com/assets/5303834/10474815/87b3715a-7209-11e5-9ebd-874f9907a84e.png)

BURNING PLASMA DEFINITELY STILL WORKS!

**Comment by Zth--** [comment]
I can confirm. It doesnt lit even when you're smoking. Somebody broke this because I remember this worked long time ago

**Comment by clusterfack** [comment]
Candidate numero uno
https://github.com/d3athrow/vgstation13/commit/860a0cda2eb9863b41ca9abe1dd90faccc833803

**Comment by SarahJohnson489** [comment]
Thirding this. threw a lit cheap lighter on some fuel and nothin'. Needed that distraction too.
