### ISSUE TITLE
Becoming fat.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6126]
Let's be honest, the fatness mechanic is retarded, you eat a BIT too much and you're obese for the rest of the game (not literally but it takes SO long to go away)

it's fucking dumb.

**Comment by Zth--** [comment]
I once had the exact opposite problem, it was too easy to become normal again (only by running). 
But yeah, to become fat you literally have to inject yourself with nutriments. There's no way to become fat only by eating.
Swole update when?

**Comment by Shadowmech88** [comment]
Lipozine can cure fatness almost instantly.
However I also think it's too easy to get rid of fatness just by running. It can make it challenging to maintain your fatness if you're playing an intentionally obese character.

**Comment by PJB3005** [comment]
@Shadowmech88 I've had a case where I used lipozine, fatness gone, now, after the lipozine went away, I BECAME FAT AGAIN.

**Comment by DeityLink** [comment]
Lipozine, treadmills.

@PJB3005 by any chance did you consume large quantities of honey?

**Comment by Kurfursten** [comment]
Treadmills burn fat really fast.

**Comment by Probe1** [comment]
sounds like a disease if you became fat again

**Comment by PJB3005** [comment]
@Probe1 nope

**Comment by clusterfack** [comment]
That's how being fat works in real life tho

**Comment by Kurfursten** [comment]
@PJB3005 Are you sure? I looked at the fatness code today and it does seem to work with the mob's nutrition level.

Also, as a note of trivia: as an experiment, I tested fatness with a treadmill on the test server today. It was actually laughable how fast you can burn it off by working on a treadmill. It may actually be TOO EASY to burn off fat if we ever add a treadmill by default to the fitness room.

**Comment by chatsonf** [comment]
Fat is easily removed by lipozine, treadmills should now be available in game, and if neither work then you probably have some sort of disease that causes you to be fat, due to how lipozine works.

Also @Kurfursten Fatness runs off of M_FAT, which is controlled by overeatduration, which is controlled by nutrition, which is controlled by nutriment_factor which comes from reagents such as nutriment.

**Comment by Kurfursten** [comment]
@Furbeh I am pretty sure I know that because I was the one who told you that in the irc this week. Remember?

**Comment by chatsonf** [comment]
Well I was telling your past self about it :eggplant:
