### ISSUE TITLE
Carps have mouse_opacity 2.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6127]
It's not hard to click on them at all, it can be argued for the babies but NOT for the big ones.

**Comment by Zth--** [comment]
So.... Whats the issue?

**Comment by PJB3005** [comment]
@Zth-- you always click on the carp, you cannot click on say the floor its on.

**Comment by Zth--** [comment]
Well, it's clearly intentional. Maybe lower the mouse opacity when it dies

**Comment by PJB3005** [comment]
@Zth-- that already happens, I'm making this issue because they REALLY shouldn't have mouse_opacity 2, they're huge sprites, they're easier to hit that humans.

**Comment by FudgePucker** [comment]
I guess this would be important if someone drops their weapon and a carp flys over it. Who can't click on a giant fucking space fish anyways?

**Comment by DeityLink** [comment]
This fucking sucks when controlling carps and trying to hit things on your tile (such as one-sided windows) as you end up killing yourself

**Comment by Ephx1** [comment]
I'm fairly certain this applies to all simple mobs, or at least simple hostile mobs. I believe Hivebots have it too.
