### ISSUE TITLE
I made a chem bomb once. It was awful.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6128]
(WEB REPORT BY: killette2 REMOTE: 158.69.55.2:7777)
So one round I made a 300 unit bomb of 100 glycerin, 100 s acid, and 100 p acid. The explosion was very underwhelming gibbing nobody, even though I was right beside it, and only seriously injuring but outright killing nobody either.

Chemical bombs are severely underpowered for the work put in, but there is several ways to make chemical bombs more powerful without making that power too easy to get. Current chemical science is "let's see how much shit we can put into smoke" when it could also be about explosions. Perhaps make bigger explosions, but costing more ingredients such as welder fuel, liquid plasma, or some other refined reagent made from a comination of things.

I do not believe any feature should be nerfed to the point where there's little to no reason to use it compared to other features.

**Comment by Zth--** [comment]
You're not making a good mix. There are ways to make instakill smoke grenades

**Comment by Shadowmech88** [comment]
Any explosion coming out of a grenade is currently capped at 1 dev.
1 dev explosions are dogshit, which is why currently no one bothers to make grenades that actually explode rather than just releasing acid smoke or napalm.

**Comment by FudgePucker** [comment]
Chemical bombs should not have high dev.

There's a reason why toxins only has 6 valves.

Also, in my opinion, fire bombs are tons better than a small chemical bomb.
Instead of just patching that small area of space with some floor tiles, the entire area is now fire.

Best chemical grenades are polysmoke, plasma smoke, and just a beaker of plasma.

**Comment by dylanstrategie** [comment]
Ideally, bombs would be a hard labor with multiple ways of going around to it (atmospheric bombs, chemical bombs, IEDs, combat gear). The problem is that atmospherics bombs aren't hard at all to make. Get Science access and get rolling

That would be a long term goal. In the short term, I think uncapping the grenades is fine. If an antag (I hope) Chemist bothers to obtain nitroglycerin, he should be rewarded for it

**Comment by FudgePucker** [comment]
@dylanstrategie Yea the glycerin grenades need to be buffed.
You need assistance from a botanist to make them, and the chemical only has one use so you can't play it off as 'oh I'm making some super meds, can you give me some corn?' he would know that you are planning on blowing shit up.

But not buffed too much, they can still find a way to make more than 6 grenades.

**Comment by Killette2** [comment]
a 900 unit grenade is the max you can get, and it required 300 units of corn oil. Where is a chemist going to get 1800 units of corn oil to out bomb science? And in my opinion if they even get that much corn oil they should be able to use a decent bomb 6 times instead of the crap that exist now.

**Comment by SarahJohnson489** [comment]
Before botany2 made better potency/production/yield a bitch you could break into botany and grab the seeds or just make the glycerol from slimes. It wasn't particularly hard to get this and a grab bag of other goodies either route you went.

![400 nitro](https://cloud.githubusercontent.com/assets/5564796/10554266/66bf25aa-740e-11e5-9638-98096de82fec.png)

This was the explosion recipe
![600 explosion](https://cloud.githubusercontent.com/assets/5564796/10554293/a501fdb0-740e-11e5-888d-36ef69db7e6a.png)

**Comment by Killette2** [comment]
So with my mathematical argument of getting mass corn oil being very difficult, should chem bombs be buffed back to their previous state? If anything, should the recipes be more complex to make up for the power? I understand that science bombs are limited to only 6 in existence but keep in mind 1800 units of corn oil is what is needed to match that cap of 6 bombs.
