### ISSUE TITLE
Defficiency posibrain is buried under sheets of metal at roundstart

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6130]
This is terrible. You ping it like crazy and people just go, "WHERE THE HELL IS THAT COMING FROM?" and maybe look for it, but usually just walk away.

**Comment by Duny-** [comment]
Will fix

**Comment by Hoshi-chan** [comment]
Thank you!

**Comment by Duny-** [comment]
Thank you for the constructive feedback fam, hard to come by these days.
