### ISSUE TITLE
Medical analyzers can be heard by those standing nearby

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6135]
I was standing near Ginger Beach when this happened. It was weird.

![analyzer](https://cloud.githubusercontent.com/assets/8556111/10489741/440dbd94-726c-11e5-9543-09c5ece99a7e.png)

**Comment by dylanstrategie** [comment]
The medical analyzer has issues. Another issue I have noticed is someone hitting the floor, and literally trying to analyze the floor's vitals

**Comment by Ephx1** [comment]
That's a clumsy thing, isn't it Dylan?

**Comment by dylanstrategie** [comment]
Maybe

**Comment by unid15** [comment]
The floor thing is literally a feature

**Comment by AutismSpider** [comment]
Floor thing is clumsy/brain damage stuff

**Comment by PJB3005** [comment]
Yeah honestly if the floor thing weren't a feature it'd runtime out of the butt.

**Comment by clusterfack** [comment]
I probably used the wrong verb for visible message
