### ISSUE TITLE
Crew Monitoring Map bug [Defficency]

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6140]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Minimap on Crew Monitoring Computers is Box's map.

**Comment by Ephx1** [comment]
This applies to any map switching, see #5945.

**Comment by clusterfack** [comment]
How is that even possible, it generates its own minimap at roundstart

**Comment by Ephx1** [comment]
Here, got a picture for it. Previous round was Meta, then it was box. It seems this also applies to the Bhangometer.
![fug](https://cloud.githubusercontent.com/assets/6224074/10553032/f0523110-7425-11e5-96b1-4da6302ec169.png)

**Comment by clusterfack** [comment]
Still a dupe of #5945, ephx1 is right
