### ISSUE TITLE
Unable to teleport to bomberman arena

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6142]
when an admin makes a bomberman arena, it says you can teleport to it, but you cant. It says that its only reserved for admins

**Comment by clusterfack** [comment]
Maybe deity used the jump to admin proc?

**Comment by Hoshi-chan** [comment]
I think you mistyped this bug report.

It should say, "There isn't always a bomberman arena around for ghosts to fuck around in."

**Comment by clusterfack** [comment]
Can confirm this isn't an issue
