### ISSUE TITLE
Protolathe material values

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6143]
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
5deba95d8d29dd6afc6d4041a3232c2d33458eca 

>General description of the issue
The amount of units shown in the material storage tab of the protolathe don't correspond to the values used in the design selection.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by dylanstrategie** [comment]
I have also noticed oddities, notably with diamond where I add 4k-ish and it refused to print a 3750 diamond design with all other materials maxed

**Comment by PJB3005** [comment]
I think this was fixed in #6263

**Comment by clusterfack** [comment]
Yes it was, didn't even realize this report existed
