### ISSUE TITLE
Gamemode Broken - Nuke Ops. Nuke disk doesn't respawn if bombed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6144]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
5deba95d8d29dd6afc6d4041a3232c2d33458eca

Pretty sure this has been reported before but if not this game mode is basically completely broken due to the fact that any kind of explosion sends the nuke disc to 0,0,0. Doesn't respawn, spawning a new nuke disc doesn't allow the pinpointers to point to the new one. Hence, nuke ops pretty much almost never win

**Comment by mrpain666** [comment]
I saw the game make a new one just now just fine, during a traitor round.

I dont know if this issue is just limited to nuke ops rounds or not, but it could be working fine now.

**Comment by dylanstrategie** [comment]
This is extremely concerning indeed. Someone should doublecheck all nuke disk safety procs, notably Destroy()

I'm pretty sure this might be caused by returnToPool(), since returnToPool() sends items to nullspace and resets their variables

**Comment by clusterfack** [comment]
Pooling calls destroy on the object. I find it more likely there is some kind of storage object, like mobs for example which aren't deleting the objects they have on them when they themselves are being deleted.

**Comment by PsiOmegaDelta** [comment]
If your nuclear disc Destroy() proc is the same as on Bay, then the disc isn't removed from a list of nuclear discs. However, in Destroy() there is a check run to see whether this list is populated or not, and because it will still be a new disc won't be created.

**Comment by Rei1226** [comment]
I definitely have noticed that the majority of times I have seen this bug, it has been when the nuke disc has been either on a person, or surgically inside them. So Cluster may be right.

This could also be similar code to the Melt/Dissolve deleting most of your items you were wearing when you gib and transform into a skeleton, although i've no idea.
