### ISSUE TITLE
Brains cannot be put into MMIs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6146]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/REWBswS.png

Day 2 of this bug.  Despite them having a spark of life the MMI says otherwise when you try to put them in.  FIX IT.

**Comment by Ephx1** [comment]
Another duplicate.

**Comment by N3X15** [comment]
Closing as duplicate.
