### ISSUE TITLE
Mindbreaker effects don't wear off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6147]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
Mindbreaker has a chance to turn you into a bowl of cookies or other things.  This effect NEVER WEARS OFF AND YOU REMAIN SPAGHETTI FOREVER.

**Comment by Probe1** [comment]
![ss 2015-10-14 at 11 23 13](https://cloud.githubusercontent.com/assets/8550416/10504246/3f2e06c0-72cc-11e5-83b7-1fea9f82454b.png)

**Comment by Probe1** [comment]
It turned out it was actually spirit breaker but it may be inheriting from parent.
