### ISSUE TITLE
Sweet machines are not constructable

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#6148]

**Comment by Kurfursten** [comment]
Do they need to be? Do there need to be two of them by default on Box at all? Would they be better off as vending machines that give the sweets in question when inserting a coin, as many vending machines have premium products? (And thus can have the coins retrieved through coinbox). Could sweets be folded into a different, existing snack machine?

I've always thought a coin is a high price to pay for 3 nutriment, especially when bustanuts have 6 nutriment.

**Comment by Zth--** [comment]
1 coin should give you 4/5 sweets on a box or something like that, nobody will spend a coin for a stupid sweet. Someone made a really good sprite ans I like the machine, but it should be buildable like most of the machinery

**Comment by FudgePucker** [comment]
Maybe have there be random medical chems in sweets?
That coin might get you three nutrient and 10 DD, or maybe even something more exotic.
