### ISSUE TITLE
Alien seed are eaten by the seed dispenser

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6150]
(WEB REPORT BY: manaony REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7b07fe58687ec61d9d2c251bb05b6924ddf8afdf 
> 
> General description of the issue
> Put xenoarch plant seed in the dispenser and they never came back
> 
> What you expected to happen
> Getting the seed to eject normally
> 
> What actually happened
> They never did and disapeared when I tried to destroy the machine

**Comment by DeityLink** [comment]
alien seeds were not meant to be put back into the seed dispenser.

I'm of the opinion that the random alien plants/seed packets/fruits/names really should have custom sprites that don't look like those of existing plants.

**Comment by Kurfursten** [comment]
All plant seeds should be able to be stored in the dispenser, it's snow flakey otherwise.

I also agree though that they should have some spritework done though.

**Comment by 9600bauds** [comment]
Related to #7684

**Comment by 9600bauds** [comment]
Related to #6551

**Comment by 9600bauds** [comment]
Fixed by #12402
