### ISSUE TITLE
Protolathe/ Circuit Imprinter Material Requirement Bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6152]
(WEB REPORT BY: fozzington REMOTE: 158.69.55.2:7777)
>General description of the issue

Protolathe and Circuit Imprinter are not able to produce an item when the materials stored in the units are equal or close to the values needed for printing

http://imgur.com/zqKM0Hy - Protolathe (comparison of RPED value vs materials stored)

http://imgur.com/rRmlnGy - Circuit Imprinter (Note the 20 Sulphuric Acid in the chemical storage)

**Comment by PJB3005** [comment]
I can definetly confirm this.

**Comment by clusterfack** [comment]
I have already looked into this, its some form of ceiling issue with the material requirement check. It's cancelling out one tier above and failing the check if it has precisely equal amounts.

**Comment by Kurfursten** [comment]
I believe this is related to the fabricator rework done by @ComicIronic

**Comment by clusterfack** [comment]
Oh yes I fixed this
