### ISSUE TITLE
MMIs are still busted (maybe)

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6154]
Saw two debrainings today, both from willing participants, and neither could be placed into an MMI. Could be that they changed their minds and stayed ghosted or something, but both had the "spark of life" message on their brains.

**Comment by Probe1** [comment]
Wasn't this more or less fixed

**Comment by Hoshi-chan** [comment]
This was made before the second MMI update went through. Nexis closed all the old ones after pushing something to do with brain messages being misleading, so I opened a new one after seeing MMIs still being broken.
