### ISSUE TITLE
Discussion: Chef, Kitchen, and Food

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6158]
People have been asking for attention to be paid to the Kitchen and food production. I'm open to that, but before any sweeping changes are made, I will lay out my perceptions of what I believe Chefs have told me they would like to see changed. I'm not going to assume that I am correct before I start, so I'd like to see if these sound like they match your concerns:
**Core Issues**
- Not enough differentiation between subtypes of similar food. (e.g.: Meat pie vs Cherry pie)
- Harder / exotic recipes are not rewarding (e.g.: ALL fish dishes and spider dishes are toxic in spite of their rarity)

**Subsidiary Issues**
- Chefs are not properly informed about the advantages of one food over another without tedious experimental grinding to measure the nutriment in each.
- Too much reliance on microwave for all cooking, should involve other machines (even if that requires re-writing Goofkitchen) and tools.

---

**Possible Solutions**

-Rewrite of food contents: scale difficulty of food to nutriment (or other) rewards.
-Better wiki documentation of reagents contained in each food
-Better version of the reagent scanner for the chef that details specific amounts of each reagent inside food for nutriment comparison
-Introduce generic datum-type steps to food recipes, in the same way that surgery is implemented, so that it is easy to path a recipe with multiple machines/tools (rolling pen, sink, oven, etc.) for more variety -- similar to how we implement generic surgery steps.

These are just my thoughts. I invite you to tell me how you feel about the kitchen. This Issue was prompted by @Rei1226

**Comment by PJB3005** [comment]
:+1: to this thread, I agree with all of it.

**Comment by ihadtoregisterforthis** [comment]
Absolutely, but keep a low-work-low-reward for the more casul scrubs.

The current system works as fast food everything, so changing to gourmet everything would be negative in the short term.

Rework might be compulsory.
Keep in mind also the economy revamp in the works and how it could affect the chef's pain.

**Comment by Killette2** [comment]
Meet hanger for making beef jerky when?

**Comment by Kurfursten** [comment]
@ihadtoregisterforthis I think that [there should be easy, low nutriment food] goes without saying.

**Comment by Probe1** [comment]
> (even if that requires re-writing Goofkitchen) 

goofkitchen is the exact opposite side of the spectrum of wrongness and SHOULD be re-written.

free nutriment/effortless foods, making complex recipes like putting a tomato into an oven and now you have a waffle (???), all the goddamn superfluous machines like having a grill AND a deepfryer or a snackbar AND a condiment master instead of combining both machines.. 

Imagine if the chemmaster was the pillmaster and there was also a bottlemaster.  That shit needs a rewrite from someone sane.

**Comment by Probe1** [comment]
Its good to keep in mind though that if you don't make a system that is fun for the player you will get what you see right now - the chef deep fries a bunch of meat and grills flour and slams it down on the counter.

If it's too tedious then people will serve raw eggplants instead of take part in it.

**Comment by ihadtoregisterforthis** [comment]
Before anything drastic happens, I cast vote on keeping the condimaster and custom topping pizzas

**Comment by Kurfursten** [comment]
@Probe1 Actually, the Condimaster, Snackbar Machine, and Chemmaster seem to be suspiciously close to what you describe!

@ihadtoregisterforthis I don't think the Condimaster or custom-foods are going anywhere. At least not as part of the first steps.

**Comment by Iamgoofball** [comment]
it's already BEEN rewritten once, it's not even goofkitchen anymore

**Comment by Probe1** [comment]
The wretched parts still are and that's what counts.

**Comment by Iamgoofball** [comment]
just make ice cream not have any nutrient at all and make it purely the chem it's made of then

**Comment by Rei1226** [comment]
hell yes

i have wanted step by step food production for awhile now, i feel like it'd be a lot better then just throwing everything into a microwave and hitting on. like roll the dough, cut the cheese, fuck the lasagna, etc.

i like all possible solutions. get some sounds for each machine while its cooking for the unique cookin' experience and its muy caliente 10/10

**Comment by FudgePucker** [comment]
I posted an idea on one of Deity's PRs before, but what if there was fertilizers to improve traits in plants like yield, potency, and endurance?

I tried looking at the code to do it myself but it is byond my level of understanding.

**Comment by Kurfursten** [comment]
@FudgePucker That's not really within the scope of this issue. We're talking about the chef side, not the botanist side.

**Comment by Rei1226** [comment]
also something that was brought up in the thread was the ability to integrate chems directly into the food, renaming them stuff like "anti-toxin burrito" or "inaprovaline spaghetti". how this would work without turning the chef into a glorified chemist with a chem dispenser, i dunno.

**Comment by dylanstrategie** [comment]
I already have something planned. Hopefully I can get it working as soon as I have time

**Comment by Probe1** [comment]
New year make a new discussion issue.
