### ISSUE TITLE
Metaclub research outpost cycling airlocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6159]
(WEB REPORT BY: manaony REMOTE: 158.69.55.2:7777)
They don't work sa intended

**Comment by Probe1** [comment]
can you be more explicit

**Comment by PJB3005** [comment]
@Probe1 I can confirm this, the vent doesn't get controlled by the airlock controller (thanks mappers), and the airlocks start unbolted.
