### ISSUE TITLE
Aliens can hear and understand radio chatter

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6164]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
be67a2d084ea21df854c0fa3ab9455c099a89e4d 
Basically as the title says, aliens can hear and understand humans on the radio

**Comment by Probe1** [comment]
@N3X15 [Saycoooooooooooooooooooooooooooode]

**Comment by N3X15** [comment]
I'm going to screw around with this today and see if I can reproduce it.  May not be very productive since I'm at an indie gamedev meetup.

**Comment by N3X15** [comment]
![6164 fixed](https://cloud.githubusercontent.com/assets/110073/11023857/69cc4958-8638-11e5-8b94-4177abd3fc39.png)
This was fixed.  The screaming candle speaks in Sol Common, and screams a random English curseword.
