### ISSUE TITLE
Vote panel fails to pop up frequently

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6165]
![image](https://cloud.githubusercontent.com/assets/8550416/10533306/5083193c-7395-11e5-81e8-e992adb4ac70.png)

Half the time the vote panel doesn't come up on round end

50 players.

1 vote.

Edit:  Sorry, SIXTY players.
#vgstation- AUTOMATIC ANNOUNCEMENT: [vg-status] A round of changeling has ended - 35 survivors, 25 ghosts.

The vote panel came up for ONE of them.

**Comment by Zth--** [comment]
No, it didn't come up. He inserted the vote command because he knows the vote is running. I usually do it without even seeing the announcement

**Comment by ihadtoregisterforthis** [comment]
OR, someone in sixty players cared enough to click the vote button. I did it once but the mapvote was broken.

This seems to happen most during highest pop.
Maybe byond's doing?

**Comment by Probe1** [comment]
``` 04:08:15 Runtime detected
Cannot read null.sending at global cache.dm:49
 proc name: send asset (/proc/send_asset)
  source file: global cache.dm,49
  usr: null
  src: null
  call stack:
send asset(null, "bootstrap.min.css", 1)
/datum/html_interface/nanotras... (/datum/html_interface/nanotrasen/vote): sendAssets(null)
/datum/html_interface/nanotras... (/datum/html_interface/nanotrasen/vote): sendAssets(null)
/datum/html_interface/nanotras... (/datum/html_interface/nanotrasen/vote): sendAssets(null)
send html resources()
send resources()

```

**Comment by PJB3005** [comment]
aaaaaaaaaaaaah

Though even then this bug has been present from long before the global cache was introduced, I doubt this runtime is the only cause.

**Comment by ghost** [comment]
It keeps happening.

**Comment by ihadtoregisterforthis** [comment]
Guess this won't be an issue for some time :^)

**Comment by Intigracy** [comment]
:^)

**Comment by Intigracy** [comment]
I haven't seen this happen lately, is it still happening?
