### ISSUE TITLE
Firecode is shit.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6166]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/AuImD2m.png

wheres the fire

why does plasma fire burn at -266 centigrade

why are flamethrowers either broken or cause a room to instantly turn into the sun

send help.

**Comment by ihadtoregisterforthis** [comment]
Hyper cold plasma fires are very interesting, with the room becoming ice just after the flames die.
Even funnier for oxygen. Maybe a feature?

The rest are broken, flamethrowers are known for their bad code.
No idea what could make the fuel and plasma not catch fire. 

There is an issue for this already

**Comment by clusterfack** [comment]
Dont know why he wouldn't use his account.

Also I'm pretty sure hes made this same issue before.

Either way I've tested what happens if you make fire go out below a certain temperature and it isn't pretty.
