### ISSUE TITLE
Revamp the box Toxin's lab. [Discussion] & [Feature Requests]

### ISSUE THREAD

**Issue by SarahJohnson489** [d3athrow/vgstation13#6167]
Didn't feel up to playing sphess so I made a shitty mockup of a thing. Moves SE solars and Xenobio down 4ish tiles. Why we need it is that having to keep rebuilding the lab is a drag. Especially with a nigrillion pipes in the way. To the people that will complain that oh no everything is megabombs now! It already is. You dip your head in you know where, flip a pump, collect your cool gas. Flip the other, collect your hot gas. Go jam it into a valve and bombcap ahoy. A better lab makes legitimate plasma research far less painful when you have more time to tweak and test rather than setting up whatever pieces of a better lab you need to work on whatever you wanted to research. Such as 2 dev one-tank bombs.

Goal was increase roundstart toxins capabilities without moving Xenobio and SE solars south of viro and essentially bolting a second atmos on the side of sci. So yeah, it's crampt I know. It'll all get labels and the pipes named. Yes, I know a bunch of stuff is missing. I need some fresh eyes to look at it to get some feedback. I might be able to color code one pipe network better, probably waste, since apparently we have blue insulated pipes now.

Features:

> Retains the raw Plasma-CO2  burn chamber output for people who like that thing or just want a quick n simple bombcap bomb
> Retains the 3-connector ghetto mixer but adds a drain to waste and an outlet to suck up the last dregs into a canister.
> Retains the one connector input to the burn chamber for ezpz no fuss fueling
> 
> Adds a mixer. Hooked up to the burn chamber inlet but has an outlet to fill a canister with any desired mix.
> Adds a filter for picking out hot gasses. Provides Hot CO2/Oxygen/Plasma/N2O for various experiments when learning bombs and researching advanced bombs
> Adds one container to waste connector to drain undesired mix into waste
> Filter output feeds a tweaker which will allow you to use the 3 gas pumps to modify the temp up, down, and composition without having to replace parts to minimize contamination. Has an output to empty it into a canister and an output to dump the contents into waste
> 1 Heater setup. Has an inlet, outlet, and a drain. Does NOT have a circulator thanks to space constraints. If it glitches you gotta cycle canisters. Tough titties.
> 1 Cooler setup to chill a mix with an inlet, outlet, drain and portapump for using low quantities of gas so it doesn't take forever but retaining the ability to fill tanks to full
> 1 Cooler setup with an inlet and outlet. Missing a drain unless I run a pump under the door or in the hall to the sci primary waste. This lets you compare performance of different ratios with less down time
> 1 Thermal plate chiller for working with gas mixes below 73K. Has an inlet, outlet, and drain to waste
> 1 Tweaker setup for your cold mix. While it is missing a heat exchanger link to a burn chamber/waste pen/heater to warm it up you'll still be able to use canisters of warmermix to slowly bring it up. Has an outlet and drain
> Provides a mixing station with everything in arms reach for adjusting stock gas volume and emptying tanks. Room for two custom mixes available
> Plasma research vendor with 30 igniters, 30 signallers, and biosuits to facilitate less painful one-tank bomb reseaarch
> An additional two tank dispensers to assist with one-tank bomb research and maintaining a small reserve of clean oxygen tanks for when you're researching tank compositions
> 3 Additional portapumps to store 3 additional ratios past the first two for composition and ratio research
> 2 stacks of metal for providing additional empty canisters to hold mixtures
> RPD for building heat exhangers, additional mixers in the sci primary hallway, tearing up the lab, and additional tweaker setups.
> Biosuits available for spill survival in low temp situations. Firesuits available for when handling hot gasses, and bombsuits when working on mix and composition research where there's a risk of instantaneous explosive tank fracture if you aren't careful and overshoot your margins

This allows toxins to conduct serious research into 2 dev+ one-tank bombs, one tank firebombs, one-tank gas bombs, explosive tank fracture bombs, and >13 dev tank transfer bombs without a 50+ minute warm-up stealing, hacking, and installing all your bits. More than that, it allows you to work additional mixes, ratios, and compositions for more research than shoot off your best idea then spend 40 minutes refitting. I could do more a lot better with more space but that'll tear up a lot more of the station worse.

![fix me early tox 2 0 prototype 3 1](https://cloud.githubusercontent.com/assets/5564796/10533835/46ad39ac-737b-11e5-8b6d-6d00a1702ba1.png)

Fishing for feature requests and more things I missed before I update it now that we have pipe layers and more colors.

**Comment by Zth--** [comment]
I really really hate the design, it doesn't feel good at all

**Comment by SarahJohnson489** [comment]
Anything more specific than that? The goal was functionality without having to uproot viro, xenobio, and SE solars a lot.

**Comment by dylanstrategie** [comment]
I'd be fine with making the Toxins Lab larger to support ambitious research projects, but a mess of pipes like this is just going to terminally confuse anyone who isn't an Atmospherics Technician without a ton of hours on their hands

Also atmos devices don't usually stack (notably pipes/pumps and connectors/filters)

In that case, the bomb testing range can be pushed further eastwards (which would have the extra perk of minimizing the risk of station damage for good bombs) and Xenobio can either be pushed straight downwards or tweaked in some fashion that allows Sci East Maint to be lowered without problems

**Comment by Kurfursten** [comment]
There are plans to move the solars down more than four tiles. I should get on that so you can get map priority if people agree to this.

**Comment by FudgePucker** [comment]
Just add a freezer, heater, cold loop in space, reroute some of the distro and waste pipes for ease of laying down new pipes, and a RPD.

This seems way too overkill. Hell I understand autmos and I can't make out what half of those pipes are for.

**Comment by PJB3005** [comment]
@dylanstrategie the mess of pipes can be fixed with pipe layers, somewhat.

Also connectors don't work cross tile.

**Comment by AutismSpider** [comment]
Just add a freezer and heater in that one room that toxins has.

add set of pipes to space near the dump zone for cooling gas etc.

**Comment by SarahJohnson489** [comment]
@dylan, Do you mean the roundstart pipes setup can choke? They work fine when you place them like that in the round. Most of the snarl you can ignore. Fuel input is still very direct as is the output. With more space I can unsnag that nasty snarl in the center. Might be able to fix it a bit with layers and the additional colors we have for insulated pipes iirc. Wanted to future proof it in case anyone turns pipe bursts back on.

@Fudge, I liked the idea of wide, nearly blank toxins with an RPD too but it still ends up that round after round you have to build however many pieces of it you need for that specific bomb mix you wanted to test that round. A blank slate and an RPD helps tons but depending on what you want to do and what you need you lose time building the fuel mixer to save canisters of gas, you lose time building the space chiller cause the freezer can't chill cold enough, need more portapumps cause using canister quantities takes too long and then *boom**boom**boom*, singuloose it's time to go home 6 times in a row.

I wish it was but it's not. If anything it's still missing more stuff. Most of the space is for being able to drain stuff into waste to reset so you can test multiple compositions against each other in a single round with less time lost having to fuss with pipes and tweakers to let you slide up and down the temp scale without having to re-make them.

@PJB, You mean the roundstart pipes setup chokes on them?

@AutismSpider, Many of us still make a filter when we need warm pure plasma. Running a splurt of dirty mix through the burn chamber then a filter gets it to you faster and let you have accuracy to the tenth of a kelvin without risking a jam in a heater/freezer. Then once you have it, you can add stock or more warm plasma to slide its temp all over the place without needing to have a freezer on the same line to take forever beyond a couple tanks worth of gas and doubling your jam risk. Having a mixer lets you use less gas so you have more to put in the cold mixes so you have more than 1 or 2 tests at a close temp. 

If solars gets moved down like kurfurst says, there'll be a lot more space so it's not all falling over itself. Being able to just walk into the lab then work on figuring out 2 dev one-tanks or the falloff's at extremes without over and over and over and over and over and over of 20-40 minutes+ of piping everything first then more time cleaning out the freezer or repiping cause while you thought xX:yY:zZ ratio would have worked you were wrong and then you realize gosh darnit you're out of portapumps again so you have to hopefully teleport more in or worse, go pull+bump 2 at a time accross the whole station from lockers/atmos. Can't even jack the derelict ones without spending more time than it's worth anymore.

**Comment by PJB3005** [comment]
@SarahJohnson489 use full names if you @mention somebody as to not annoy other people on accident.

**Comment by SarahJohnson489** [comment]
Oh that's fine, don't have any of those
