### ISSUE TITLE
Lawgiver

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#6168]
The lawgiver doesn't seem to work.
It's basically just a 5 shot taser right now, because it doesn't change with voice commands and it doesn't explode when someone else tries to use it.
Also it seems like there's no delay for firing it, so you can just rapid fire stuns and shit

**Comment by Probe1** [comment]
Yeah we tested it and although the no delay is sweeeet that's about all it does. 

Its desc says its a gun with a 25 round magazine.  In game it's a taser without an attack delay that has five taser bolts worth of energy.

**Comment by Shadowmech88** [comment]
Inability to switch mode might be due to the saycode update. Not sure why it wouldn't recognize DNA, though. I'll test it out.

**Comment by clusterfack** [comment]
Did you gear it the HEAR flag nerd?

**Comment by Shadowmech88** [comment]
Yep.
And to be clear, it did work perfectly a week or so ago.

**Comment by 9600bauds** [comment]
I unknowingly fixed this already
