### ISSUE TITLE
cant access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6169]
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)
cant access my genetics machines

**Comment by Probe1** [comment]
I helped him fix the issue in game by unscrewing the consoles and turning them back on.  I think the DNA machines were moved somehow, maybe power maybe something, I have a feeling it was an IC issue.

**Comment by clusterfack** [comment]
Bad bug report
