### ISSUE TITLE
cant access

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6170]
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)
from previous report one more step would be that i turned on hotkey toggle

**Comment by Probe1** [comment]
I helped him fix the issue in game by unscrewing the consoles and turning them back on.  I think the DNA machines were moved somehow, maybe power maybe something, I have a feeling it was an IC issue.

**Comment by PJB3005** [comment]
Considering #6169 got closed because well, no info, and this is even less descriptive on its own, I'll close this.

If you want to rereport it properly go ahead
