### ISSUE TITLE
buggy walk

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6173]
(WEB REPORT BY: scribnibblers REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
be67a2d084ea21df854c0fa3ab9455c099a89e4d 

>General description of the issue
walking through wate disposals when i pass from west to east through the windoor it glitches out.>What you expected to happen
walking

>What actually happened
blew me back super fast like ZAS does but faster

>Steps to reproduce if possible
walk through waste disposals windoor?

**Comment by dylanstrategie** [comment]
Needs confirming, it might just be ZAS

**Comment by clusterfack** [comment]
What is this even trying to report really? Whatever it is I couldn't reproduce it that's for sure.

**Comment by clusterfack** [comment]
Unclear report
