### ISSUE TITLE
Sometimes, the game freezes for minutes when clicking a "follow" link as an observer

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#6174]
Using the verb, however, doesn't do that

**Comment by ihadtoregisterforthis** [comment]
Somewhat related to 'follow', but not the link, is that it freezes the game when scrolling in the name list.

**Comment by Ephx1** [comment]
I believe this applies to clicking anything in the chatbox at all. For me it'll crash BYOND directly if I click on anything in the box sometimes.
Other people have this issue too, but not everyone, there doesn't seem to be any consistency to it.

**Comment by MaddoScientisto** [comment]
I remember having this issue in august but not some months earlier

**Comment by clusterfack** [comment]
I've never had this issue in particular, though I do have a separate issue in which if a follow link is highlighted in my chat from clicking it whenever that same follow link is reprinted (when the guy talks) it scrolls my chat down to the bottom.
