### ISSUE TITLE
Spray Bottle Sprays No Longer Slip

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#6175]
Wasn't wearing magboots, was perfectly capable of slipping on banana peels and such. Yet when I fill a spray bottle with water and spray it, running over it does nothing.

**Comment by clusterfack** [comment]
Works for me

**Comment by Shadowmech88** [comment]
Oh I'd forgotten about this.
Yeah, apparently it only slips if you've got the nozzle set to spray 10u. I thought it used to still slip on 5u sprays, but that's another issue altogether. Point is that this isn't broken.
