### ISSUE TITLE
When Put Into Odysseus Mounted Sleeper While Holding Item, Item Disappears

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#6176]
My guess is that it's dropped into the contents of the mech.

**Comment by FudgePucker** [comment]
Mounted sleeper is the most bullshit thing in the game.

Its fucking stupid and needs to be fixed.

Let me tell you a story.
I was a sec officer with a battle mech, and I wanted to arrest someone.
I can't load people into the portable cell with out them being cuffed.
The only way to cuff people is to leg cuff them.
The only way to leg cuff people is if they are unstunned.
You only get so many bolas.

Boy this is already sounding retarded isn't it?
Guess what?

YOU CAN BREAK OUT OF THE PORTABLE CELL

GUESS WHAT?

I COULDN'T EVEN MAKE IT DOWN THE GOD DAMN HALLWAY BEFORE HE COULD DO IT.
So I had to punch the guy to death.

Oh but the medical mecha has a GOD DAMN SLEEP TOX SYRINGE GUN.

ANNNDDD THE FUCKING GOD DAMN SLEEPER CAN FUCKING HOLD THEM FOREVER AND EVER AND EVER AND EVER AND EVER UNTIL THE END OF THE UNIVERSE.

Why the hell is the odysseus's medical use sleeper better at holding people captive than a cell designed to hold people captive?

**Comment by clusterfack** [comment]
Its OP
