### ISSUE TITLE
Make Laptops More Portable and Functional

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#6178]
Paraphrasing from thread and IRC.

The idea is to change the existing laptops that you'd find in medbay and sec to not only ACTUALLY be portable (as of now you can only drag them around which is beyond retarded looking), but to also make them more usable and buildable (if they're aren't already?).

I propose changing their functionality to not only mimic a buildable console, but also be programmable to be used with ANY console on station.

What this means:
- Allows people to monitor AND access a console remotely. Any changes on one reflects on the other, effectively making them identical.
- Gives antags more options and freedom to cause havoc. Imagine being able to change the Atmos AAC from the other side of the station.
- Gives more stuff for science to build - and it won't be cheap
- Easy to stuff in bag so it's discreet and convenient
- Access to only one console at any time. Maybe be upgradeable to manage multiple. Must have access to the original console, of course.

Consequently there should also be a way of tracking them much like mechs and suit sensors, but I haven't thought of a way of easily implementing that yet. I don't want this to be rushed every round, but it should be convenient for both players and antags.

**Comment by dylanstrategie** [comment]
The way I see it : 

- Laptops are basically portable computers
- You can put them in your hands by dragging their sprites onto you, they run on battery if they can't run off the current area's APC
- You can fold it to turn it into a backpack-able item
- You can put any board that would fit in a normal computer, from bhangmeters to security cameras
- They need heavy research however, and can't be produced very easily. I guess, otherwise no reason to not use laptops over regular computers

**Comment by Cyadox** [comment]
@dylanstrategie 
Personally I'd rather have it just link to an existing machine so it makes it more challenging to get high risk machines. In theory that would let you make any sort of console so long as you had the board - but having to use an existing machine means that not only is it easier to check for tampering (because you can see it in action if you're on the original console) but it also means that you'd need the respective access (or an emag) just to program the laptop.

Leaving a trail of evidence to use high-risk machines that's easy to follow makes it so Sec isn't tearing their hair out trying to figure out why everyone is set to arrest, or why the AI keeps getting new laws all the time, because you either need to build and sync the console first or break into the area it exists in.

**Comment by PJB3005** [comment]
I always wanted to make modular computers like goon, I just never got around to it due to clockcult.
