### ISSUE TITLE
Current problems I have noticed with Telecommunications

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#6179]
- [x] The Arrivals Announcement computer has a job title under the form of AAC (as AAC), which makes the message long and annoying
- [x] Vending machines broadcast on channel ".7" for some reason
- [x] Simple mobs have no vocalizing verbs
- [ ] I have noticed the Bhangmeter not being able to broadcast into a radio despite having one within one tile. It might not even be vocalizing, but I can't confirm that since I wasn't physically here when the oddity happened
- [x] Potentially unrelated, but GHOSTRADIO and GHOSTEAR(S) no longer work at all, ghosts hear all radio chatter and chatter in the world by default

**Comment by Cyadox** [comment]
Plasmaman speech no longer has the s-s-stutter.

**Comment by N3X15** [comment]
GHOSTRADIO and GHOSTEARS is a bug with BYOND's XOR operator.

**Comment by ihadtoregisterforthis** [comment]
PLASMAMEN STUTTER GONE
FEATURE LOSS

MAYBE FOR A DIFFERENT ISSUE?

**Comment by Ephx1** [comment]
* Potentially unrelated, but GHOSTRADIO and GHOSTEAR(S) no longer work at all, ghosts hear all radio chatter and chatter in the world by default

Really? It's the opposite for me, I can't hear anything as ghost unless I'm at the source directly.

**Comment by N3X15** [comment]
509.1307 fixes GHOSTEARS.  

http://www.byond.com/forum/?post=1959790

**Comment by Probe1** [comment]
I have a really good fix for the arrivals computer.

Revert whoevers nonsense idea it was to automatically integrate the job script into telecomms.  That is the players job.  It is for the players to do.

**Comment by dylanstrategie** [comment]
The job script should stay, it's really annoying to go to Tcomms every single round to install the same copy-pasted script manually on every single server

Either way, N3X already found the solution

**Comment by Probe1** [comment]
yeah its really annoying having to play the game.

**Comment by Rei1226** [comment]
dont fix the plasmaman. just leave it this way.

**Comment by dylanstrategie** [comment]
I can confirm the bhangmeter vocalizes, but I can't confirm it can broadcast on the comms properly. Should be a quick check though

**Comment by dylanstrategie** [comment]
Closing because I have seen the Bhangmeter vocalize on intercom, which crosses out the last item on that issues list
