### ISSUE TITLE
Borer eggs are unusable after first ghost draft

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#6182]
Supposedly after a borer egg is exposed to plasma, and there are no ghosts, the egg will become unusable. This is very silly, considering you get one, and the only way to get more is cross your fingers for the borer event or adminbus. One suggestion in the thread was to allow the egg another retry if the plasma is replaced with new plasma.

**Comment by AutismSpider** [comment]
Teleport to X borer Egg does nothing.

The borer event is bug it spawns in brain dead borers.

**Comment by Ephx1** [comment]
Really? It does? Then it must be adminbus for additional borers, unless there's some other way to get eggs. A few times in rounds there were more borers even though I was the only hatched one on station.

**Comment by N3X15** [comment]
It's supposed to try again, but I probably butterfingered the logic.

**Comment by N3X15** [comment]
Out of curiosity, do you get any message when it fails to find a ghost?

**Comment by Ephx1** [comment]
From what I'm told you get a message that the egg calms down.
