### ISSUE TITLE
Automatically ghosted and unable to re-enter corpse.

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#6187]
Revision: fc9a1f08eb72a54f4da29fe5e25fc9a36793ce4e

>General description of the issue
I died being chopped to death in the head(?) with a broken bottle. When I entered crit, I succumbed. Before I typed "ghost," I noticed I was already a ghost.
When I got dragged to medbay, I found that I couldn't re-enter my corpse, and that any attempt to do so came back with "You have no body." This happened both with the Re-enter-Corpse verb and with the link in the "someone is trying to clone you" message. My head was on the body still. My brain was not removed, or even damaged.

>What you expected to happen
Re-entering my body.

>What actually happened
Couldn't re-enter my body, message was "You have no body."

>Steps to reproduce if possible
Not sure.

**Comment by Probe1** [comment]
@PBJ3005 @N3X15

**Comment by PJB3005** [comment]
No idea @Probe1

**Comment by clusterfack** [comment]
Ahhh why did we touched mind_can_reenter(), tumbling down

**Comment by PJB3005** [comment]
I didn't touch `mind_can_reenter()`

**Comment by Intigracy** [comment]
Assuming this is fixed.

**Comment by Intigracy** [comment]
I haven't been able to reproduce this.
