### ISSUE TITLE
Xenomorphs cannot ventcrawl with someone inside of them

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6191]
This breaks hunters. It just makes them fast sentinels who can't spit or melt walls.

EDIT: Also, to clarify, they used to be able to with old ventcrawling.

**Comment by Probe1** [comment]
Carrying is absolutely intended but with someone in the belly, probably not.

**Comment by clusterfack** [comment]
How do these things even break seriously

**Comment by Kurfursten** [comment]
@clusterfack I would assume it was broken by Comic's ventcrawl refactor a while back, but Xenos get played so rarely that no one noticed until now.

**Comment by clusterfack** [comment]
Pretty sure I've played as xeno since then and didn't encounter this

**Comment by Hoshi-chan** [comment]
I was a xeno yesterday, and did encounter this. I was a hunter, and the whole reason I even chose it was so that I could go out, devour monkeys/people, and ventcrawl them back to our nest in disposals. You can't. It gives the, "You can't be carrying something" message.

**Comment by Probe1** [comment]
I'm not saying its right or wrong but carrying things was intended since you can do all manner of cheesy shit that way with relative ease.

Being blocked when someone is in your belly absolutely has to be fixed though, xenos are hurting enough as is.
