### ISSUE TITLE
Posi brain sound

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6194]
Because there are asshole roboticist who dont turn it on when I click it as a ghost. Maybe by spamming a BWOINK sound they'll pay attention.

Well... maybe not a BWOINK but something that will tell the roboticist someone is trying to use the brain. And maybe put a time on it so it cant be spammed too much.

**Comment by ihadtoregisterforthis** [comment]
Feature request.

In the meantime get along with other ghosts and spam it together. Anyone near will run to activate it.
~~Also something about secret macros~~ There is no such thing as a cow level.

**Comment by PJB3005** [comment]
I'd be down for the same sound as if you emote "ping" as silicon, though with a delay to prevent spam.

**Comment by AlphaBuffalo** [comment]
Im up for a non-spamable sound. But keep the positronic brain pings softly message spamable since its slightly less intrusive.

**Comment by Hoshi-chan** [comment]
Both the ping and the message should be on a delay. As it is, trying to politely get the roboticist's attention by pinging a few times can be sabotaged by assholes coming by and spam-clicking it to the point where the roboticist just disposals it or throws it out an airlock.
