### ISSUE TITLE
Emitters are a bit too powerful on Blob

### ISSUE THREAD

**Issue by Rei1226** [d3athrow/vgstation13#6199]
Ever since the emitter rework waaayy back, emitters have just been way too powerful against Blobs, to the point where it's basically game over if its even pointing at its core, and even if it isn't it still completely destroys an entire section of the blob, letting people easily laser near the core

**Comment by Hoshi-chan** [comment]
Emitters have always been the Blob destroyer.

**Comment by Rei1226** [comment]
True, but how they were before was a pulse every couple of seconds, giving the blob time to react or place some stuff there.

Now it's just an orbital laser beam of death that never stops, and can literally cut a blob completely in half and prevent him from building on the other side of it

**Comment by SarahJohnson489** [comment]
Strong blob wall essentially negates it from what I saw from a couple previous rounds of it. That regen is too strong.

**Comment by Rei1226** [comment]
Not even. Strong wall still gets obliterated by it

**Comment by FudgePucker** [comment]
The emitter is not easy to install properly.
Risk VS reward.
If the blob pops somewere where they can not get to it easily like in maintanance then they can not set up an emitter far away from it, if they try to set up an emitter close to it then they run the risk of the blob eating it.
Emitters require teamwork to deploy in most situations, if a bunch of idiots are getting in the way then you can't really set it up in time.

If you had thermite, rig suits, and a good team then you could set it up anywhere, but good fucking luck doing that.

**Comment by ihadtoregisterforthis** [comment]
As engineer
* find floor
* tear plating
* put a few wires
* wrench and weld
* smell what the rock is cooking

As anyone else
* locate blob
* weld if you can
* laser if hopcurity
* flamethrower if new or clown
* die trying to light it or punch it
* wait for the emitter

As observer
* see the emitter be placed
* see someone die trying to punch the blob
* become a blob if Duny is on


Blob is a short round and almost always ends with emitters, when it isn't sniped early by HoP/cap/warden ~~or the fucker doesn't erupt in space because muh box~~

**Comment by Ephx1** [comment]
You forgot as observer, see as everyone walks into the emitter beams and complain about someone turning on the emitters.

**Comment by FudgePucker** [comment]
Blob is one sided anyways. In order for emitters to get set up aiming at the core requires a good crew and a dumb blob.

If the blob loses to an emitter it would have likely lost anyways. Either they are organized enough to get a clear shot on the blob or everyone gets in the way.

One of the few times I was an engineer on a blob round I tried to get an emitter to the blob, have you tried dragging an emitter though science mainanace past 10 assistants?

**Comment by Manaony** [comment]
My  only problem with emitters is that they more or less have an infinite range as far as the blob is concerned, if it's centered in it's core it doesn't matter if it's ten or twenty tiles in space he'll die. On another note, fix borg being able to fire from their charger holy shit.

**Comment by gbasood** [comment]
Honestly, I'm not too sure this is much of an issue. A late-game blob can ONLY be destroyed by emitters or a very, very lucky bomb.

**Comment by Probe1** [comment]
Massive rework on blob in the years since this issue.
