### ISSUE TITLE
Requesting more solidification

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#6202]
In the chemistry code there is a recipe that is almost never used, and for a good reason. Other than xenobotany, you almost never encounter plasma in the liquid form naturally, but there is plasma solidification. Here is that code.

``` DM
plasmasolidification
            name = "Solid Plasma"
            id = "solidplasma"
            result = null
            required_reagents = list("iron" = 5, "frostoil" = 5, "plasma" = 20)
            result_amount = 1
            on_reaction(var/datum/reagents/holder, var/created_volume)
                var/location = get_turf(holder.my_atom)
                new /obj/item/stack/sheet/mineral/plasma(location)
                return
```

In this request, I am requesting more things being able to be solidified. Liquid gold can come from golden apples, liquid uranium can come from glow berries. Why not let all of the liquid forms of ores be solidifiable?

**Comment by Zth--** [comment]
>almost never used
Because it's not on the wiki. Features get lost when they're not properly documented

**Comment by ghost** [comment]
Aight, hang on a minute while I sort this out, shouldn't be that hard should it?

**Comment by ghost** [comment]
Assuming you're still here, what would you want the recipes to be like?

**Comment by Killette2** [comment]
I would say the exact same including iron and frost oil, but that leads to the question about turning iron into metal. Should we make a substitute for iron and why is iron included?

That also brings the question if you should be able to solidify iron into metal sheets, while they are cheap from cargo and common on the roid, should they be able to be producable through chemistry with the aid of lots of frost oil?

**Comment by ghost** [comment]
I guess iron's included so the material has something to bind to properly.

Could have it go in stages

> Iron - needs no binding (50u iron 5u frost oil = X sheets of iron)
> Plasma - needs iron binding (10u iron, 5u frost oil, 20u plasma = X sheets of plasma)
> Uranium - needs plasma binding (10u plasma, 5u frost oil, 20u uranium = X sheets of uranium)
> Silver - needs uranium binding (10u uranium, 5u frost oil, 20u silver = X sheets of silver)
> Gold - needs silver binding (10u silver, 5u frost oil, 20u gold = X sheets of gold)
> Diamond - call me when you make liquid diamond, because that shouldn't be possible
> Phazon - Oh shit nigger how did this happen?
> Bananium - needs banana essence binding (10u banana essence, 5u frost oil, 20u bananium = X sheets of bananium)

But you're the ideas guy here, so fire away

**Comment by Killette2** [comment]
The tier suggestion strikes as a bit weird since that's not really how metals work. Maybe we can replace the iron in solidification with aluminum as the new binder, or any other chem instead of a metal that sounds like it's good for binding. Plastic uses polyacid, so what would be all around the best chemical for metals?

**Comment by Killette2** [comment]
Also this brings into thought, the chemical called nothing. Should there be nothing solidification? Will mimes finally have their metal for mechs? Or building invisible things such as chairs. Why haven't we thought of this before?

**Comment by ghost** [comment]
I have a feeling structural invisible walls would prove to be a pain and something interesting as well, but what happens if you drop the material itself?

**Comment by Killette2** [comment]
Well if you look at the walls mimes make, they aren't completely invisible but very difficult to see with a brownish tint. Should that be what we base it off of? I mean it shouldn't be completely invisible because that would be stupid, but a lot of transparency would be advised. And if there was said mime mech, would you or would you not be able to see the pilot?

**Comment by PJB3005** [comment]
Yeah @Skullyton I don't believe this tiering system is a good idea either.

**Comment by ghost** [comment]
Then we could have it as just a generic solidification recipe

> 10u iron, 5u frost oil, 20u [whatever material you wish to solidify]

That'd make adding it to the wiki a whole lot easier

**Comment by Killette2** [comment]
Well we can just look at the examine info of every chemical, or hell, even use something simple as silicate, to decide which would be best.

The thing I didn't like about tiering though is it feels 'gamey' and acts as if the ores go in a linear order such as in a game like minecraft or runescape, which they completely do not.

So how does silicate sound + frost oil sound or is there a better option?

**Comment by ghost** [comment]
10u silicate, 5u frost oil, 20u material, sounds pretty good

**Comment by Exxion** [comment]
INFINITE METAL FROM CHEMISTRY

**Comment by ghost** [comment]
Not entirely infinite, as it'd take frost oil which only has a few sources, only one of which is absolutely infinite (being botany)

**Comment by Exxion** [comment]
Xenobio

**Comment by ghost** [comment]
Xenobio can already make its own metal in a much easier process (only needing 5u of a certain chemical depending on the wanted metal, and a metal/gold/adamantium core) whereas the blue slime that gives frost oil only gives 10 units.

So, you would need a blue slime core to make 10 units of frost oil, and then you would need the powdered form of the metal (I'm assuming you mean metal as in iron in this case) which you wouldn't gain more than grinding it up would give you.

**Comment by ghost** [comment]
An adamantium core can make

- 5 sheets of diamond when injected with 5u carbon
- 5 sheets of bananium when injected with 5u silver
- 5 sheets of phazon when injected with 5u gold

A metal core can make

- 5 sheets of silver when injected with 5u tungsten
- 5 sheets of gold when injected with 5u copper
- 5 sheets of uranium when injected with 5u radium
- 2 sheets of diamond when injected with 5u carbon

A silver core can make

- 2 stacks of either 5 sheets of (Metal, Plasma, Plasteel, Silver, Gold, or Uranium) when injected with 5u carbon

**Comment by Exxion** [comment]
Impractical is my middle name
