### ISSUE TITLE
I'm 90% sure that killer tomatoes are bugged.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#6204]
For a long time since I've only played botany, ever since botany2 was introduced I have yet to obtain killer tomatoes as a mutation. The chance proc for each tomato is 33%, with each being blood tomato, killer tomato, and blue tomato (which later mutates into bluespace tomato). With that being said, in such a long time and even on rounds where I'm solely mutating tomatoes, I have yet to see a killer tomato plant outside of xenobotany. Please fix so I can have cuddly killer tomato pets.

**Comment by Shadowmech88** [comment]
It's still possible, because I've personally seen killer tomatoes grown within the last couple of months, at least.

**Comment by Killette2** [comment]
I said they can be grown with xenobotany (can either be the plant that produces a different fruit, or a differant plant that produces the fruit as xenobotany poses as other plants and fruits), but those are not real killer tomatoes. It's only confirmed if you've actually seen them mutate.

**Comment by FudgePucker** [comment]
Well heres your problem, killer tomatos aren't a tomato mutation they are a blood tomato mutation.
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/hydroponics/seed_datums.dm#L862

**Comment by Killette2** [comment]
Well shiet. That change was unexpected. Will test, because I am certain it said somewhere in the code at one point, that it was a 33% chance each.

**Comment by Killette2** [comment]
else if ( istype(myseed, /obj/item/seeds/tomatoseed ))
		del(myseed)
		switch(rand(1,100))
			if(1 to 35)
				myseed = new /obj/item/seeds/bluetomatoseed
			if(36 to 70)
				myseed = new /obj/item/seeds/bloodtomatoseed
			if(71 to 100)
				myseed = new /obj/item/seeds/killertomatoseed

YOU'RE WRONG. YOU'RE FUCKING WRONG.

However I did look at blood tomatoes and they are supposed to mutate now when you plant analyze them, so there is conflicting code somewhere.

I spent an entire 1 hour round mutating all trays with blood tomatoes and got no further mutations, please fix post haste.

**Comment by FudgePucker** [comment]
@Killette2 
It might be a conflict then.
A: That code looks like a fucking mess.
Lets say someone makes a new seed. With the seed datums as they are all you have to do is "mutants = list", not have to do a giant wall of text to have a mutation.
B: No other plant has three mutations, it is always two. Tomatos can mutate into blue tomatos or blood tomatos, blue tomatos mutate into bluespace tomatos and blood tomatos mutate into killer tomatos.

**Comment by Killette2** [comment]
If you are adamant that this is not broken, I would encourage you to try to reproduce it by mutating blood tomatoes into killer tomatoes yourself. Believe me, I've tried hard.

**Comment by FudgePucker** [comment]
@Killette2 I'm not saying its not broken, its just something seems really off with this whole situation.
What I was saying is that it makes more sense for it to be a blood tomato mutation than a normal tomato mutation.

**Comment by clusterfack** [comment]
It's a conspiracy

**Comment by Killette2** [comment]
I don't really mind what it mutates from, I just want the mutation to actually work and be fixed. Seeing as it seems to be changed from the previous 1/3 chance of mutation, we might as well make it so now killer tomatoes mutate from blood tomatoes.

**Comment by 9600bauds** [comment]
The hydroponics.dm file you guys were looking at hasn't been included in the .dme for years

**Comment by FudgePucker** [comment]
I was looking in the right place then.

**Comment by 9600bauds** [comment]
My bad, you were, I only read killette's code snippet

**Comment by ihadtoregisterforthis** [comment]
Change title to "100% sure"
