### ISSUE TITLE
Cannot build optical prisms

### ISSUE THREAD

**Issue by Faptastic** [d3athrow/vgstation13#6209]
The prism claims to need 3 high powered lasers and 6 capacitors to be built, it rejects both.
It doesn't matter which version of these parts are used it will simply reject all of them from stock to high end meaning you can't build one.
You can assemble a machine frame, wire it and add the board but go no further.

**Comment by FudgePucker** [comment]
Why does a prism require capacitors anyways?
Why the hell does it require 6?

I remember that it only takes tier two lasers not tier three or one, but I don't know if someone broke capacitors.
