### ISSUE TITLE
Xenoarch Artifact wtih no Sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6212]
(WEB REPORT BY: kinggrimlock REMOTE: 158.69.55.2:7777)
>Revision 8a541b54f8e962bfaed095196db0e7e345f33086 

>General description of the issue
Found an artifact (smooth red crystal) which had no sprite.

>What you expected to happen
For it to have a sprite.

>What actually happened
It didn't have a sprite.

>Steps to reproduce if possible
Play Xenoarch
Hope you find a smooth red crystal.

**Comment by Skullyton** [comment]
Found what's causing this: Xenoarchaeology/finds/finds.dm, line 268, one of the objects has its icon state set to "ore" where there isn't an icon called "ore" in xenoarchaeology.dmi. So, either we need an icon for "ore", or change the icon for smooth red stone, or delete it completely.
