### ISSUE TITLE
My life as a body scanner

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6216]
(WEB REPORT BY: harsetheef REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
I became the body scanner when trying to exit the body scanner.

>What you expected to happen
I expected to exit the body scanner.

>What actually happened
I became the body scanner.

>Steps to reproduce if possible
Have someone eject you from the body scanner at the same time you eject yourself.

**Comment by IAGFPRMF** [comment]
This guy was sent to the "abyss" because of the reason above. Turned into a talking body scanner and gave me a very hearty chuckle.

Easy to fix as an admin by simply using the "get mob" verb.

**Comment by DeityLink** [comment]
Actually he wasn't sent into nullspace. His location became the body scanner, hence why people could hear him talk.

**Comment by clusterfack** [comment]
I've combed through the code really heavily and cant find any way this can occur at all and my testing reveals nothing at all.

Nothing could cause this outsight of varediting occupant to null or undergoing a transformation while inside the machine.

Anyway this report does not give any information necessary to solve such an issue.
