### ISSUE TITLE
Prisoner Maintenance Console breaks when Changeling morphs with implant. Implant changer not ejecting.

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#6220]
Other night we had caught a changling an permabrigged him (not knowing of ling status of course) and implanted him with a tracker. After he monkey morphed and escaped the Prisoner Management Console no longer worked, as it wouldnt bring up the dialog window at all. It would normally do so even if there were no trackers working.

*DISREGARD IMPLANTPAD I SUCK DICKS*

**Comment by Wizardcrying** [comment]
>Also Tracker implant editor would not eject the implants
You mean the implantpad? You click on it with the other (empty) hand.

**Comment by Dizor** [comment]
Updated.
