### ISSUE TITLE
Changes to Gibber and butchering

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#6221]
Wanted to recommend updating the meat yield on human/vox/diona/plasmaman. I feel like the gibber gives too little meat, as a fully grown human will yield the same amount of meat as a butchered monkey, despite being reasonably larger than monkeys.
I also feel that Vox meat should either be replaced with chicken -or- should produce a blue meat slab that acts as poultry in dishes, if possible.
I'll look into coding it myself but I have no idea what assets to begin with to try and start changing these sort of things.

**Comment by AutismSpider** [comment]
Do some thing with the parts of the gibber better parts = more meat

T2 parts = 5 meat

T3 parts = 8 meat

**Comment by Kurfursten** [comment]
I like @AutismSpider 's idea. More RefreshParts() work is always good.

@Dizor The amount of meat output is under gibber.dm and is a function of mob size (line 253). If you want to increase output by size, you need to override RefreshParts() and look for the .rating on stock parts.

If you want to create a blue meat that functions exactly like chicken, create a child of raw chicken in meat.dm along these lines: /obj/item/weapon/reagent_containers/food/snacks/meat/rawchicken/vox, then override the name and icon.

**Comment by ihadtoregisterforthis** [comment]
Vox meat should be chicken over all, but blue chicken is more consistent.

I don't know what kind of meat can you obtain from a simmering flammable/inflammable draugr tough. Well done steak?

**Comment by Kurfursten** [comment]
Instead of meat, just output teeth. They're skeletons, not zombies.

**Comment by ihadtoregisterforthis** [comment]
They have visible muscles though

**Comment by AutismSpider** [comment]
burn meat or some thing?

**Comment by Kurfursten** [comment]
We have burned mess. You could output that. Useless, but amusing.

**Comment by Dizor** [comment]
@Kurfursten Thanks for the tips! I'll see about messing around with it on private, I'll come back with results sometime in the future.
