### ISSUE TITLE
EMP Stun

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6222]
(WEB REPORT BY: blarghargin123 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 224ce2e671f70e2368c6c4ba551134a0056beca9 
> 
> General description of the issue
> EMPing a borg a point blank stuns the borg for a total of 1 second.
> 
> What you expected to happen
> Point blank EMP to stun for 20 seconds
> 
> What actually happened
> Got 1 second stun
> 
> Steps to reproduce if possible

**Comment by Probe1** [comment]
Rei and I commented in deadchat when it happened.  Either something is broken or its so bad that it is indistinguishable from being broken.

**Comment by Kurfursten** [comment]
Highest severity of emp_act for silicons appears to add 5-10 stunned. Severity 2 results in 1-5 stun and lower damage. Severity 3 results in no stun or damage.

**Comment by Probe1** [comment]
That confirms it's uselessness.

**Comment by SarahJohnson489** [comment]
A flash applies weaken 5,10, emp is stun 5,10 in heavy, 1,5 in light, and at the border of heavy/light it's 50% heavy or light. Quick fix would be to see if swapping stun to weaken would work,  I dunno enough about what the difference between them is though.

**Comment by Kurfursten** [comment]
I think the broader issue is that EMPs are harder to come by than flashes on the station.

**Comment by AlphaBuffalo** [comment]
You can order then by emagging cargo's console

**Comment by Kurfursten** [comment]
I'm not saying it's impossible to get EMPs, but to your point, two of the easiest ways are locked behind being a traitor, meaning inaccessible in Malfunctioning AI for the crew.

**Comment by Probe1** [comment]
bumping EMP grenades isn't going to result in a proliferation against the silicons.

lord knows they're nigh unbeatable head on when controlled by an experienced guy.
