### ISSUE TITLE
Remove False Delta Alert

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#6224]
I believe for admins this is associated with +FUN and is under the Secrets menu.

All it ever does is make a bunch of people  go kill the AI, then some inexperienced admin gets huffy because it was a fake alert, ban people who are in the dark about it, and it's just a bunch of bullshit, there's no good use for it, fake meteors and rad alerts are much better, pls remove.

**Comment by clusterfack** [comment]
Good point really. It's not exactly something you can punish someone for 'metagaming' for when it really is meant to be the final alert to tell the crew that a malf AI is about to win.

**Comment by unid15** [comment]
>removing features because badmins abuse them

no, why

**Comment by SkowronX** [comment]
>no, why
-Admin triggers fake delta alert.
-Admin 90% follows up with "ITS FAKE ITS FAKE" immediately afterwards. 
It serves no real purpose.

**Comment by nuklearcellphoneg** [comment]
-Admin triggers fake alert
-Someone kills the AI
-Admin bans said someone

-Admin triggers fake alert
-It's fake!!
-Well, I don't know the round type, but I know what it isn't

Someone will inevitably press the button.

**Comment by PJB3005** [comment]
I can confirm this happened, somebody said "law 2 AI go delta".

Then the AI adminhelped.
The admins made a fake delta.
AI got wiped.

**Comment by clusterfack** [comment]
That sort of thing happens every time, the exception normally being when the players have confirmed admins have sent multiple fake alerts already.

**Comment by Shadowmech88** [comment]
I played a round once where a malf AI won because the admins kept making fake delta alerts so that when the real delta alert came, no one was sure whether the AI was really malf or it was just another fake.
I can't imagine any actual FUN could ever come from using this power.

**Comment by PJB3005** [comment]
I find it dumb that people can't just look at the status panel and see the remaining time...

**Comment by dylanstrategie** [comment]
I added those fake alerts with the main purpose of allowing admins to easily fire fake event alerts for any reason, instead of having to do a very close Global-Narrate + Global-Sound

The warning once the event is chosen VERY CLEARLY states Delta status, specifically, is likely to lead to AI destruction, and that the admin should only proceed if he's either ready to babysit and protect the AI with admin powers, or accept that a non-rogue AI is going to get blown 4noraisin

**Comment by Hoshi-chan** [comment]
No.

The Centcomm update that reads something like, "YOUR AI IS MALFUNCTIONING AND YOU SHOULD DESTROY IT IMMEDIATELY" part of the fake delta button should be removed. The fake delta itself is fantastic. Everyone but the biggest comdoms and absolute shitcurity will handle it rationally if the AI is willing to cooperate. It's like a shitter safari button.

**Comment by Cyadox** [comment]
I say keep it, but make the message just slightly telling that's it fake. That way at a glance it's not obvious, but if you actually read it carefully you'll know it's fake.

That's just my opinion though. I'd be happy with what Hoshi's suggested.

**Comment by dylanstrategie** [comment]
For reference, the admin chooses wherever to include the actual Hostile Runtimes warning or not, and is very clearly told the later message will likely lead to AI destruction

**Comment by Shadowmech88** [comment]
@Hoshi-chan 
>you can't card a malfunctioning AI

Is that a recent change? I believe at least within the last couple of months I've personally won a malf round by carding and wiping the AI.

**Comment by clusterfack** [comment]
I've seen people card malf AIs numerous times. And in fact, if you couldn't, that would be need to be fixed RIGHT away because it would allow such an extreme form of metagaming.

**Comment by Hoshi-chan** [comment]
Maybe I've completely lost my mind, but I could've sworn I saw someone try to card a malfunctioning AI recently and fail to do so.

**Comment by Probe1** [comment]
That did happen.

**Comment by PJB3005** [comment]
@Probe1 if you're thinking of the same ban as me the guy was a captain too...

**Comment by Rei1226** [comment]
:+1: 

Please get rid of it. Or at least make them distinguishable from actual delta alerts, and not literally the SAME EXACT MESSAGE AND SOUND.

Terrible shit that only serves to either kill the AI or banbait someone.

**Comment by PJB3005** [comment]
@Rei1226 making them not 100% similar won't help, people are idiots, even with enough red flags (AI not protecting itself, no countdown timer...), people will still wipe the AI.

**Comment by Probe1** [comment]
It mostly stems from people not paying attention and the delta alert jerking their head out of the clouds, to which they promptly focus on completely.

You know why don't you just.. add some generic malfunctioning garbage text to the real malf delta?
I mean there IS a real delta alert when the nuke has been activated etc.

**Comment by ihadtoregisterforthis** [comment]
Move the button further down in the panel, near the "FLOOR IS LAVA" one, and add a warning label

**Comment by Shadowmech88** [comment]
>THE FLOOR IS LAVA

Why have I never seen this button pushed?

**Comment by SkowronX** [comment]
Because it's lame. It even says so right next to it.

**Comment by Probe1** [comment]
The novelty of having to table yourself or jump inside the nearest locker wears off in a microsecond then everyone starts posting in OOC.

**Comment by Rei1226** [comment]
@PJB3005 That is true, but overall this button simply should not exist. There is no reason for it to exist. It only serves to either grief the AI or ban bait someone who wipes the AI.

**Comment by unid15** [comment]
Just ban shitmins who abuse it then, why would you remove an actual feature
because it's being abused by inexperienced admins

Putting some bold red text next to it with a warning is also an option

**Comment by Probe1** [comment]
It's listed under +Fun and if you have that flag you're not inexperienced.  You may be shit though if you abuse it.

**Comment by Probe1** [comment]
I thought it over.

Someone just said it should be buried down by floor is lava.  Thats a good example of a button that just shouldn't ever be pressed.  It literally makes the floor lava.  Its function is to make 10-60 players instantly start icking in ooc.  It has no value and yet it is there.

After thinking about it, I can recall two admin fired fake delta events since I have been an admin.  The first time resulted in Konater catbeasting a mechanic who instantly ran to the RDs office, broke in, and blew the borgs well after Centcomm announcements saying the alert was fake, subtle messages to the player and a just in time admin PM to the player to hold up.  It ended up causing a minor tiff and Konater caught some shit over it.

The second time I can recall is the recent one tied to a head ban where someone carded and wiped the AI because they thought it was real, ignoring all signs that it was not like the complete absence of hacked APCs, the AI allowing him entrance and allowing itself to be carded, no silicons committing any acts against their laws et cetera.

I've concluded that if you want to remove it then go ahead.  I will not say no.  But it's one of like a dozen or even two dozen buttons that cause nothing but trouble.. and also can make a dull round more interesting.  You are not going to idiot proof SS13 by removing this or them and ultimately removing the delta alert button is just a reactionary action in response to a single event.

**Comment by PJB3005** [comment]
@Probe1 I have +FUN and I became codermod a week ago.

**Comment by Probe1** [comment]
I have no idea what's going on with nuke and flags and that's not representative of normal.  He didn't give you flags that were useful for a coder and did give you flags that people usually wait an age for.  

I wouldn't think of it as an example.

**Comment by nuklearcellphoneg** [comment]
Floor is Lava and This Is Just Like One of My Japanese Animes are like low-pop buttons.

If someone manages to plasma flood the entirety of the station, floor is lava could be okay- if literally everyone is dead. Neither leads to a situation where an admin has to take further action to intervene to bring the round back to normalcy.

As a side note, Codermin get a good chunk of flags because they're already coding for the server, they're either going to abuse them or not: With an admin, you see if they have good judgment in banning: Then, can they resist playing sounds? Okay can they resist spamming meteors? Et cetera.

Admins get lots of chances. Codermin do not get many chances.

**Comment by Probe1** [comment]
Codermins need spawn.  Not adminbus flags.  That aside, I've said how I think it is here.  You can try to idiot proof the game but we'll still have idiots.

**Comment by N3X15** [comment]
# TIME TO BREAK SOME HEARTS

**Comment by Imagebard** [comment]
>Everyone but the biggest comdoms and absolute shitcurity will handle it rationally if the AI is willing to cooperate. It's like a shitter safari button.
>I was the AI that got wiped, and the captain who led the charge on my core and wiped me was a complete fucking idiot with a validboner.

I don't know why the fuck people liked Hoshi so much, the first time I met him in-game he spurted the same borderline retarded shit form when I saw him.
Either way, as Probe1 said, bury it beneath "THE FLOOR IS LAVA" button at very least.

**Comment by ghost** [comment]
:-1:

**Comment by Probe1** [comment]
Time has shown that while it is a stupid button, the real reaction was to an admin using it in a stupid way.  

We cannot code smart humans.  If we could I would not be a collaborator.
