### ISSUE TITLE
Russian Alphabet Makes You Valid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6229]
(WEB REPORT BY: blarghargin123 REMOTE: 158.69.55.2:7777)
This address two things, possibly adding Russian letters so when the commis speak in game we dont get a bunch of random accented letters, we get beautiful Cryillic letters. And to prevent people from using in game it makes them valid by the Anti Commi task force sent from centcom.

Some guys in deadchat said this would be a good idea when I brought it up.

**Comment by PJB3005** [comment]
Thanks to BYOND, using Cyrillic is impossible, as it only shows up correctly for people with their locale set to Russian.

The rest of this idea is retarded.

**Comment by Zth--** [comment]
This is stupid

**Comment by SkowronX** [comment]
It is. Get out of my country, commies

**Comment by clusterfack** [comment]
Cyka blyat
