### ISSUE TITLE
Bloody footsteps no longer appear and cleaning blood sometimes fail outright

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#6232]
Pretty much the title

Bloody footsteps no longer work at all, even on new and large blood splatters. Also from time to time, stepping into multiple layers of filth (oil, blood, vomit) can cause shoes to only wash one layer at a time (notably when soap is applied) or not wash at all, in which case they are permanently stained

**Comment by clusterfack** [comment]
So we're back to the original issue + bloody footprints no longer exist
