### ISSUE TITLE
Play a sound for silicons when their laws are updated

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6237]
It's pretty easy to miss your laws changing in the constant flood of text. It'd have to be a unique sound though, or else it'd be just as easy to miss for different reasons.

**Comment by Zth--** [comment]
I'm working on a sounds update. I'm busy on the week so I'll try to add it this weekend

**Comment by Probe1** [comment]
:+1:

**Comment by PJB3005** [comment]
:+1:

**Comment by dylanstrategie** [comment]
I'm pretty sure such a sound already exists, or can easily be edited

**Comment by Intigracy** [comment]
gonna use msn.ogg

**Comment by ghost** [comment]
Are you certain there's no law update announcements in the sound files ?

I remember a few voice pieces for silicons and mechs

**Comment by Intigracy** [comment]
I didn't find one from a quick glance over, if you can find one let me know.
