### ISSUE TITLE
Adamantine Golems can't even be made into slime people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6242]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
bf7481cbf3a22f490c1377e8a781fdf094e9ecc4

Seems Adamantine Golems can't be made into slime people, which means they can't ever help the xenobiologist in xenobiology if the xenobiologist is already slimed and has slimes running around.

**Comment by Shadowmech88** [comment]
Adamantine golems are made of rock, so I don't think syringes work on them at all.
However, being made of rock, I think they should be immune to slime attacks by default just like slime people are.

**Comment by Ephx1** [comment]
They're not resistant to slimes.
Golems are literally humans with a stupid irremovable suit slapped onto them and really need a rework.

**Comment by AutismSpider** [comment]
Golems need to be turn into a mob that can use tools or some shit.

**Comment by Rei1226** [comment]
They're made of rock, but they also bleed, they also can have blood samples taken, they can be thrown into cryo, they have a hunger meter which can slow them down, etc. etc.

It's very ancient code. In that it's barely code at all and it's literally a human with an invisible irremovable hard suit. Yet for whatever reason, they can't be made into slime people, or even have the slimes be non-hostile to them by default.

**Comment by AutismSpider** [comment]
I think you can poly acid the golem suit/face off

**Comment by Ephx1** [comment]
You can also just straight up clone them and watch as they "turn" human, or turn them into a proper slime with a black core. Sliming them makes them drop all of their items.

**Comment by Rei1226** [comment]
When I was cloned as a golem I still came out with the armor on.

**Comment by Ephx1** [comment]
Well I guess that was fixed after the species cloning fix. I remember that being a thing quite some time ago.
