### ISSUE TITLE
Missing Sprite: Dwarven Mining Vendor

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6248]
The mining vending machine is missing a sprite for the broken state. I know that @dylanstrategie was behind the change and seems to have an interest in spriting now, so I think he might have fun with this one.

For the uninitiated, vending machines can be broken by an EMP, blob, bomb, or 2% chance on kick.

**Comment by dylanstrategie** [comment]
Noted, I might have forgotten. The old Mining Vendor couldn't be broken at all

I'll try to see what I can do

**Comment by Probe1** [comment]
I choose to believe that I simply kicked that mining vend out of existence this morning.
