### ISSUE TITLE
Holopads Pls (Bug Report)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6250]
(WEB REPORT BY: fozzington REMOTE: 158.69.55.2:7777)
>General description of the issue

Currently noted bugs:

-Using :h still transmits the holopad message over active intercoms
-Holopad received is a little janky

Photo Evidence:

http://imgur.com/gzQ0IXy

**Comment by Hoshi-chan** [comment]
Oh, so holopads actually transmit now? They weren't transmitting when I reported it before.
