### ISSUE TITLE
Cult antagbans, solution

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6252]
(WEB REPORT BY: alandemarest REMOTE: 158.69.55.2:7777)
Issue, change of how cultbans work

Right now cult antagbans makes the person immune to being converted, this is bad because it might fuck over future cults. When they will try to convert said person, they won't be able to, this means that they have wasted their time, effort and are at a serious risk of being ousted, because of an antag ban.

I have a solution.

Make it so that people banned from cult are drawn into the realms of Nar-Sie, removing them 100% from the round. No gibs, no remains, just completely removed from the round.

If they are so shit that they get cultbanned, this is what they deserve. It's THEIR punishment and it shouldn't punish OTHER players, such as future cultists who try to convert them.

**Comment by Rei1226** [comment]
:+1:

**Comment by IAGFPRMF** [comment]
Seconded. Prevents hotheads from using their immunity to utter "CULT IN _____ HALP"

Any solution would be nice. Maybe it could put them to sleep, telling the converter to just give blood to the blood god instead.

**Comment by IAGFPRMF** [comment]
Seconded. Prevents hotheads from using their immunity to utter "CULT IN _____ HALP"

Any solution would be nice. Maybe it could put them to sleep, telling the converter to just give blood to the blood god instead.

**Comment by Ephx1** [comment]
#5976 Related
