### ISSUE TITLE
Rev antagban

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6254]
(WEB REPORT BY: alandemarest REMOTE: 158.69.55.2:7777)
Same shit as report 6252

https://github.com/d3athrow/vgstation13/issues/6252

Make it so that future rev players aren't punished for some cunt being revbanned.

I suggest that you make them teleport to communist hell if someone tries to flash/convert them, without a trace on the station.

**Comment by Ephx1** [comment]
Make them ghost. The flash containing their propaganda was too much for their mind, they've become catatonic in the process.

**Comment by PJB3005** [comment]
Paralyse them for 30 seconds, enough time to 'dispose' of them.

**Comment by Hoshi-chan** [comment]
Make them to explode the way that farting on a bible does. Same thing could be applied to cultist jobbans.

**Comment by PJB3005** [comment]
@Hoshi-chan that's incredibly obvious.

**Comment by Hoshi-chan** [comment]
@PJB3005 It's a crater on a tile with a pile of remains. There's no damage to the station and no gibs. If you're that worried about someone investigating it, you leave a bible on top.
