### ISSUE TITLE
bug report sometimes doesn't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6256]
(WEB REPORT BY: nmsct699 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

5ac8d445fc3d77e469d768e7f66dd980bb2d7c04 
8a541b54f8e962bfaed095196db0e7e345f33086 

bug report sometimes doesn't work, tried restarting client

**Comment by sockpuppet325435409325432543** [comment]
*,didn't work

shows error

 Notice: Use of undefined constant e - assumed 'e' in C:\xampp2\htdocs\baka\issues\index.php on line 148
e

**Comment by PJB3005** [comment]
@d3athrow has to fix it, it's on his server.

**Comment by Intigracy** [comment]
Close.
