### ISSUE TITLE
You can still complete your objectives as an antag if you die and come back as a borer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6258]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

905e321cb2f3502f643f8dd198035c7c1178a5f3 
I believe they're still marked as antags

**Comment by Killette2** [comment]
It's like greentext doesn't actually matter.

Yes this is a bug, but it should be obvious that if they're a borer even if they get greentext, that they lost.
