### ISSUE TITLE
Agent IDs are totally broken

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6259]
They don't scan access, and maybe it was because I scanned access with mine, but it even lost its ability to open up maint tunnels.

**Comment by PJB3005** [comment]
Uh, IIRC they can only scan access once.

**Comment by Hoshi-chan** [comment]
@PJB3005 Even if that were the case, that's not intended functionality, and even that didn't work. After scanning my own ID, it lost all access.

Agent ID is supposed to be cumulative, allowing you to scan increasingly better (or different) IDs until you have all access.

**Comment by unid15** [comment]
Just tested this on a local server and I couldn't reproduce this

1) Non-antag with agent ID and spare ID, hitting the spare with the agent ID: Nothing happens, no access is gained or lost (working as intended)

2) Antag with agent ID and spare ID, hitting the spare with the agent ID: agent ID gained all access, no access removed from the spare or the agent ID (working as intended)
