### ISSUE TITLE
Supermatter shards vaporize other shards

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#6265]
wah

**Comment by Ephx1** [comment]
Does that mean they vaporize one another?

**Comment by PJB3005** [comment]
How about merging 2 shards gives one a SHITLOAD of energy.

**Comment by Hoshi-chan** [comment]
Two shards colliding should create a supermatter cascade event.

**Comment by PJB3005** [comment]
@Hoshi-chan no, do you know how easy it is to get a second shard?

**Comment by Hoshi-chan** [comment]
@PJB3005 O-oh. Right.

How about two colliding creates a crystal, then? Or has a chance at creating a crystal?

**Comment by PJB3005** [comment]
It'd have to be a >1% chance then.

**Comment by Hoshi-chan** [comment]
@PJB3005 Going through the trouble of creating mass drivers and ordering a second supermatter shard, then successfully having them collide while vaporizing NO ONE in the process is sort of a feat.

**Comment by PJB3005** [comment]
Colliding 2 SM crystals is easy as shit, pull on, click on the tile under the other one (both need to be in cardinal to eachother) boom.

**Comment by Hoshi-chan** [comment]
@PJB3005 That's dumb. I was imagining like, synchronized mass drivers causing them to collide at high speeds.

**Comment by PJB3005** [comment]
I doubt that you're able to fuse 2 shards of what's PROBABLY the most dense material in SS13 (except singulo) with mass drivers...

if you want to make crystals how about you need an R-UST to do it.

**Comment by Hoshi-chan** [comment]
@PJB3005 I dunno. I'm no engineering expert, but having witnessed the construction of many R-UST engines as an AI, it always takes 2-3 hours, and never works out.

**Comment by PJB3005** [comment]
@Hoshi-chan it's not very hard, people are just dorks.

**Comment by Hoshi-chan** [comment]
@PJB3005 Well, I dunno then.

**Comment by clusterfack** [comment]
Colliding 2 supermatter shards? That sounds like howd you make a nuclear detonation to me.

https://en.wikipedia.org/wiki/Gun-type_fission_weapon

**Comment by FudgePucker** [comment]
Two shards merging should cause a max cap bomb, two crystals merging should cause a gravitational MoMMIally :^)
