### ISSUE TITLE
Health Analyzers have obvious broken spans

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6266]
(WEB REPORT BY: dylanstrategie REMOTE: 158.69.55.2:7777)
Having a condition that makes you not use health analyzers properly seems to add a broken span class

Sometimes a "<span" shows up

Check the health analyzer code thoroughly to find the broken span tags

**Comment by clusterfack** [comment]
You can make a real report, embarassing dylan

**Comment by dylanstrategie** [comment]
Solving it myself, just wanted a self-reminder

**Comment by clusterfack** [comment]
Naughty!

**Comment by PJB3005** [comment]
gotta get them coder valids :^)
