### ISSUE TITLE
Make Wizard Spell Target Menu a Preference

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#6267]
Personally, I would MUCH rather my spells select a random target than have to interact with a menu while in the heat of battle. I don't think I'm alone in this opinion, either.

**Comment by PJB3005** [comment]
I think this is more an issue with verbs really, though it should be fixable.

Realistically we kill verbs altogether.

**Comment by clusterfack** [comment]
No its an issue of some people want it to show a menu of choices and others want it to not. I was in the 'not' camp personally.
