### ISSUE TITLE
Remove slowdown from xenoarch suit.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6270]
Seriously we don't need more reasons for xenoarch to suck.

**Comment by FudgePucker** [comment]
It is both space proof and 100% radiation proof.

Break a window in escape and make uranium walls and you become unstoppable.

**Comment by dylanstrategie** [comment]
It should be less slow, it's ridiculously slow compared to even the mining hardsuits

**Comment by PJB3005** [comment]
@dylanstrategie I'm pretty sure the mining ones have NO speed slowdown.

**Comment by FudgePucker** [comment]
@dylanstrategie and mining hardsuits are just space proof and have brute resist after putting on plates.
We are talking about 100% radiation proof, space proof, and some xenoarch field resistant suits.

The least slowdown it should have is perhaps radsuit slowdown.

**Comment by PJB3005** [comment]
I think the idea behind the suits is that they protect from 'exotic particles', but because Cael was lazy he just made it work with rads.

**Comment by FudgePucker** [comment]
I mean shit, there isn't a spaceproof radsuit, so engineering might want to have one of those if they make a radio transmitter or need to space the supermatter.
