### ISSUE TITLE
IAA False-Bottom Suitcase eats items

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6271]
Once you have the false bottom open, you can keep sticking items into the false bottom, but only the last item inserted can be retrieved. Everything else is gone forever.

**Comment by dylanstrategie** [comment]
Most likely a missing check, or outright sanity. The false-bottom suitcase is intended for a single item

**Comment by Wizardcrying** [comment]
Eugh, the code for putting something in seems to be made of the shittiest pastacode.
