### ISSUE TITLE
Map issue box: Tcoms waste and cold loop lines are both connected

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#6272]
![onefuckingturftotheright](https://cloud.githubusercontent.com/assets/12202731/10681455/6b034856-78f7-11e5-99c0-1f359974a19c.png)

These two pipes are on the same layer in an impossible way, making them both in the same loop.

I tested this by attaching a canister of N2 to the waste line, then scanned the cold loop line. There was N2 in the cold loop line.

**Comment by clusterfack** [comment]
And this would be why the cooling line heats up for no reason

**Comment by FudgePucker** [comment]
@clusterfack Probably, when I went on the test server the pressure was at 0kpa, the waste line has a vent out into space.

**Comment by clusterfack** [comment]
Somebody done fucked up

**Comment by ihadtoregisterforthis** [comment]
> ˃coolent

**Comment by FudgePucker** [comment]
@clusterfack funny thing is how long this has been over looked. I only noticed it after dylan wanted the vent and scrubber fixed even though they weren't broken because the pipe crossed them, when one turf over the laws of the universe were being broken.

@ihadtoregisterforthis fine then, let me edit the whole entire thing then.

**Comment by Kurfursten** [comment]
I knew something strange was up. This explains why the airlock was opening so quickly for me: it's just staying at a constant middle temperature
