### ISSUE TITLE
Ryetalyn doesn't work on non-monkey monkeys

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6275]
Or farwas, at least. 

With monkeys, it turns them into a monkey-human. Farwas turn into catbeasts, and then immediately revert back. Over time, this causes horrific injuries, which is awful if you're trying to use them as test subjects for medical experiments.

**Comment by Probe1** [comment]
ok no one else has said it so I guess I will

why the fuck does ryetalyn turn monkeys into humans?  is that really working as intended?

**Comment by clusterfack** [comment]
Because all genetic abnormalities occur above 802 or whatever. So it's probably naively setting every block to what it would be if you were below 802, which is human.

**Comment by PJB3005** [comment]
Should probably just ignore block 42.

**Comment by clusterfack** [comment]
It's the last block, not block 42

**Comment by Probe1** [comment]
Block 54

**Comment by PJB3005** [comment]
Damnit I thought there were only 42 off memory.

**Comment by clusterfack** [comment]
Even then whatever way fixes it should be softcoded to use the last block, which is coded to be the monkey block no matter what.
