### ISSUE TITLE
You can slip on water/lube when you're on janicart/firebird/etc. now

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6276]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
d9c770ee2f7efd5ac074daee2617503c5839f0a4 
Pretty much as the title says. Seems like all mounted "vehicles" will cause you to slip right off of them if you go over a lubed/wet floor tile.

**Comment by dylanstrategie** [comment]
Interesting. I had fixed peel slipping and shard stepping, guess we have even more missing checks then
