### ISSUE TITLE
Alien larva can still understand humans

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6277]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

d9c770ee2f7efd5ac074daee2617503c5839f0a4

**Comment by Ephx1** [comment]
I was told by pomf that this is a feature.
#4420

**Comment by Rei1226** [comment]
That seems...rather odd and has the high potential for meta I feel like, but alright.

**Comment by PJB3005** [comment]
IMO it makes no sense but eh @d3athrow says so.

**Comment by Zth--** [comment]
Guys, IIRC it worked like this before the saycode rework. I remember playing as larva while hearing PANIC ALIENS AT XXX through tcomms

**Comment by gbasood** [comment]
No longer a thing I think

**Comment by PJB3005** [comment]
Can confirm this isn't an issue anymore.
