### ISSUE TITLE
Xenos are shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6278]
(WEB REPORT BY: victorem REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d9c770ee2f7efd5ac074daee2617503c5839f0a4 
> 
> General description of the issue
> Some faggot nerfed xenos to oblivion
> 
> What you expected to happen
> A fucking xeno that could take up a to a fist fight with a ripley
> 
> What actually happened
> Lasers
> 
> Steps to reproduce if possible
> be xeno
> red alert
> combat borgs can't stun em
> thermals and laser cannons

**Comment by Ephx1** [comment]
#6223 
You can stun combat borgs via the magic of neurotoxin and resin nests.
Also I'm pretty sure you can just flat out "knock over" a silicon as xeno.

**Comment by AutismSpider** [comment]
pray to disarm rng to knock over combat cyborgs if you win the cyborg is dead if you fail you take 120 laser burn damage

**Comment by Rei1226** [comment]
http://ss13.pomf.se/forum/viewtopic.php?f=10&p=7477&sid=3cb4a0f7432cea49f83ed20c005826d4

They're in desperate need of buffs. Although it'd probably be a big undertaking since these fuckers really just need to be revamped
