### ISSUE TITLE
Impossible to remove someone from a mech without destroying the mech

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6280]
So if someone suffocates, dies, falls asleep, or goes braindead inside of a mech, your only option is to destroy it if you want them out of it.

How about a right click eject option on the mech that takes a good 15 seconds or more and provides a combat log message? That way you can forcibly eject someone without destroying the mech, but only if they're stationary for a good long time (meaning they're probably dead or whatever). Or something else, I don't know, I don't use mechs,

I just had the second round this week where I had to get someone out of a mech to help them, but couldn't, because destroying a mech hurts the pilot and human harm is a no-no.

**Comment by clusterfack** [comment]
Maybe with a crowbar or something

**Comment by ihadtoregisterforthis** [comment]
Maybe an eject option from the mech console

**Comment by Hoshi-chan** [comment]
Maybe a combination of the two? You lock it down (forcing maintenance protocols from the console), and then crowbar the locked-down mech?

**Comment by dylanstrategie** [comment]
There should be a remote eject option from the mech console, and a manual option with a crowbar for emergencies. I don't know if the remote eject option should have a delay, since I'm not sure if there's any "safeties" then, but crowbar can most likely take like 10 seconds with a danger span and a crowbar sound on start (the one for ripping tiles off or something)

**Comment by Imagebard** [comment]
>How about a right click eject option on the mech that takes a good 15 seconds or more and provides a combat log message?

1 second is longer than you think, and 15 seconds is shorter than you think.
With that being said nobody seems to be having a problem with this issue, who is making this "controversial" again?
