### ISSUE TITLE
Borer teleport

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6283]
(WEB REPORT BY: sjbenster REMOTE: 158.69.55.2:7777)
>Revision: 0a65da02d0238543c2bdf9752a8fbece8cf12df3 

Basically when the purple text comes up saying the borer egg is ready to hatch and you click to teleport to it, you get: "teleporting to..." and you sit there. pls fix

**Comment by Kurfursten** [comment]
Was it during the first polling or a later one?

**Comment by DeityLink** [comment]
most likely a runtime. maybe the egg didn't exist anymore when you clicked on it.

**Comment by Kurfursten** [comment]
Can anyone reproduce this?
