### ISSUE TITLE
Why are explosive bear traps not a job specific antag item?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6289]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

0a65da02d0238543c2bdf9752a8fbece8cf12df3

I'm a bit confused as to what the thought logic was behind the janitor being able to have the exact same thing as his job-specific antag item, only you don't have to be an antag to make it, and can just attatch an IED to a bear trap, making it essentially an insta-kill to anyone who walks over it (literally an IED on the same tile as you, guaranteed to blow off at least one limb and make you bleed out).

**Comment by Killette2** [comment]
Nobody purposely runs into a bear trap, everyone ignores wet floor signs.

**Comment by Kurfursten** [comment]
It's also worth mentioning that you only have to run NEAR the prox signs, and they guarantee both legs are blown off with unique code.

**Comment by unid15** [comment]
IED beartraps are probably too strong

You know the clown's signature move that involves dropping his PDA on the floor and pulling a dude onto it, stunning him instantly? I've done the same thing yesterday with a rigged beartrap (which blew the dude's legs away and left him bleeding on the ground). 

My ideas: armed beartraps can't be put into backpacks and arming a beartrap produces a visible message, and perhaps rigged beartraps are destroyed after blowing up.
