### ISSUE TITLE
Allow aliens to build resin floors in space.

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6291]
As the title suggest. Make it so aliens are able to build off station nest so they don't get murder boned by the guys with laser cannons and flame throwers.

**Comment by Ephx1** [comment]
Oh boy, can't wait to link the plasma chamber to the station with this!

**Comment by AlphaBuffalo** [comment]
That's stupid you're killing all the possible larva you can make and making the station in habitable for aliens

**Comment by Ephx1** [comment]
Not really. If you're flooding engineering + atmos, someone is probably going to be inside, and if they're silly enough to light themselves up they've harmed themselves and others fighting you.
Also facehuggers just need to infect someone while alive, so you can just slap a hugger on them while in crit and you're good to go.

**Comment by AlphaBuffalo** [comment]
You dont want to kill everyone though, you need them alive to reproduce, if anything flood N2O, and have facehuggers give internals so they dont die from suffocation. Maybe, to help counter it, let facehuggers heal they're target, so they dont go past crit, but not enough to heal to 100%

**Comment by Rei1226** [comment]
yes please. getting floortiled while chasing someone is fucking retarded and i've seen it happen to a lot of aliens.

**Comment by FudgePucker** [comment]
@AlphaBuffalo if you connect ANY scrubber directly to the station it is always going to be lethal, you have NO idea how much pressure those things produce. Plasma is just the closest tank to the station.
