### ISSUE TITLE
Placing money on table gives odd message

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6293]
(WEB REPORT BY: nmsct699 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
0a65da02d0238543c2bdf9752a8fbece8cf12df3 
Placed a 10 credit chip on a reinforced table (the bar), and it displayed

>You add 1 credit chip to your stack of cash.

I suspect there are related issues with credit chips

**Comment by Cyadox** [comment]
/obj/item/weapon/spacecash/afterattack is responsible, though I'm not sure why. Supposedly the for loop iterates for each cash object on the turf - I can only assume it always runs at least once regardless of the credits actually existing or not.
