### ISSUE TITLE
Inaprovaline and Space Drugs Overdose Bug

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#6294]
Looking at reagents.dm, the on_mob_life() of inaprovaline and space drugs don't seem to call the parent function like all the other reagents with overdose thresholds do. I believe this would mean that it is not possible to overdose on them, despite overdose being intended as evidenced by the declaration of an overdose threshold for these two reagents.

**Comment by dylanstrategie** [comment]
Good catch, I'll hotfix a parent call in

**Comment by Probe1** [comment]
>i'll hotfix a parent call in

>reworks chemistry-reagents

what a mad man

**Comment by PJB3005** [comment]
\> And made the PR into a balance changer so it couldn't get merged too.

**Comment by clusterfack** [comment]
Just count this bug as closed for the official count
