### ISSUE TITLE
Hydroponics doors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6297]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

0a65da02d0238543c2bdf9752a8fbece8cf12df3 
>General description of the issue
Doors to hydroponics do not open to people with Hydroponics access. They require bar access for some reason.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by dylanstrategie** [comment]
What map
