### ISSUE TITLE
Noslip shoes chameleoned as clown shoes do not squeak.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#6299]
Title.

**Comment by d3athrow** [comment]
they already do

**Comment by SkowronX** [comment]
The clown shoe skin needs the squeekin.

**Comment by Killette2** [comment]
Also let me throw this in here.

When you use the voice changer and change it clown wig and mask, it uses the wizard one with purple hair, instead of the original clown wig and mask with orange hair.

**Comment by 9600bauds** [comment]
Re-purposing this issue to reflect the part that's not fixed

**Comment by 9600bauds** [comment]
theoretically speaking which would be worse

copypasting the clown shoe squeaking part, or make syndigaloshes a child of clown_shoes

**Comment by Intigracy** [comment]
Do neither.

Put the step sound on the parent shoe, and just have it null except for the ones that need it.

This allows for cool shit™ like boots with a step sound.
