### ISSUE TITLE
Spacepod wiring

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6305]
(WEB REPORT BY: tnepr REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0a65da02d0238543c2bdf9752a8fbece8cf12df3 
> 
> General description of the issue
> Could only wire spacepod with red wire coil
> 
> What you expected to happen
> Cable colour shouldn't matter
> 
> What actually happened
> Nothing
> 
> Steps to reproduce if possible
> Wirring the spacepod with a different coloured cable coil

**Comment by PJB3005** [comment]
Hrm, [this line](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/WorkInProgress/pomf/spacepods/construction.dm#L183) says it's looking for the base cable coil type, not anything specific.

[This line](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/datums/helper_datums/construction_datum.dm#L69) in construction datum code is doing a regular `istype()`, and not a `type ==`, very strange.

Uh, just to be sure, if you're reading this, your cable coil had more than 10 lengths of cable, right? If it didn't and the next coil you tried was red, then, well...

Though if that was the source of the issue, I'd say we should add a message like "this is not enough cable!".

**Comment by Shadowmech88** [comment]
Are you sure you were wiring the same spot both times?
A quirk of spacepods is that you can only interact with them on the same tile where you initially wrenched the frame together.

**Comment by clusterfack** [comment]
Likely a bug with adjacency

**Comment by 9600bauds** [comment]
I believe this is fixed.

**Comment by 9600bauds** [comment]
Fixed, both the adjacency thing and the color thing (which probably never existed)
