### ISSUE TITLE
Space tile sprite bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6306]
(WEB REPORT BY: blarghargin123 REMOTE: 158.69.55.2:7777)
https://gyazo.com/876d6499da711c3c522f0615cd2faae3

I dont know what is causing it, or how to reproduce it, but when Im a ghost, the space tile sprite changes. My best guess is when I become visable as a ghost the bug shows up, but it hasnt happened enough time to be conclusive.

**Comment by PJB3005** [comment]
Something is causing lighting overlays to not be removed.

**Comment by AlphaBuffalo** [comment]
No, the singulo was loose and I was over atmos. nothing with lighting

**Comment by PJB3005** [comment]
What do you mean with it changed, is it the darkness? That's lighting overlays failing to be removed.

**Comment by AlphaBuffalo** [comment]
the ammo thing, those are space tiles. And atmos was destroyed so the space tiles were in simulated lighting areas, I think thats what its called. Nothing is wrong with lighting

**Comment by PJB3005** [comment]
The overlays should've been deleted because space tiles itself has nondynamic lighting.

The thing with ammo... Uh, that's very weird.

**Comment by AlphaBuffalo** [comment]
Its not only ammo, this is the second time it happened. First time I saw thermal plates in place of space tiles, and the sec borgs

**Comment by PJB3005** [comment]
This... is really starting to sound like a BYOND issue.

**Comment by AlphaBuffalo** [comment]
So, just deal with it till BYOND fixes their shit?

**Comment by clusterfack** [comment]
Known byond bug
