### ISSUE TITLE
Missing paintings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6312]
(WEB REPORT BY: yeaggar REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: ef326cf2f99bfa86d92a4927bd13c6474cf1d3b2

>General description of the issue

Placed 'Singing' Mounted Carp and Pretencious Mime Painting on wall and nothing materialized, alt-clicked wall where placed and only the wall appeared on the window. Path toward the Sunset painting had no such problem and was placed and picked up were the other painting were "placed".

>What you expected to happen

Paintings to show up on the walls.

>What actually happened

Messagelog says painting was placed, nothing appeared in the world.

>Steps to reproduce if possible

Buy said painting, place on wall under the mining shuttle console on Box Station.

**Comment by PJB3005** [comment]
@DeityLink

**Comment by ihadtoregisterforthis** [comment]
Can confirm. Happens for the new wave of paintings, the original ones still appear.
Also happened in Taxi so doesn't look like a weird map problem.
