### ISSUE TITLE
Plasma man plasma tank doesn't fit in the back slot like they would for oxygen tanks.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6313]
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777)
>Revision ef326cf2f99bfa86d92a4927bd13c6474cf1d3b2 
Plasma man plasma tank doesn't fit in the back slot like they would for oxygen tanks.

**Comment by PJB3005** [comment]
Which clothes, it's dependant on which exosuit you're wearing, if it's a plasmamen suit then uh oh, else, meh.

**Comment by Ephx1** [comment]
They probably mean that plasma tanks can't be worn on your back like backpacks.
You can do that with large oxygen tanks.

**Comment by PJB3005** [comment]
Oh, yeah that's weird.

**Comment by FudgePucker** [comment]
I am going to guess its because plasmamen plasma tanks parent is plasma tank instead of O2 tank, meaning that it doesn't fit on the back like O2 and N2 tanks.

**Comment by PJB3005** [comment]
Spot on @FudgePucker
