### ISSUE TITLE
Something fucked with robotics emergency destruct

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6314]
The emergency full destruct now requires robotics access.  I can't find anything in blame or history that changed it so something else must have changed.

Anyway there was no mention of this in a changelog or PR so I'm going with "bug".

**Comment by d3athrow** [comment]
robotics access requirement hasn't been changed in 3 years. https://github.com/d3athrow/vgstation13/blame/Bleeding-Edge/code/game/machinery/computer/robot.dm#L9

**Comment by Probe1** [comment]
The only explanation is we've all gone crazy, even if that's crazy.

**Comment by unid15** [comment]
it's berenstein bears all over again

**Comment by ihadtoregisterforthis** [comment]
You mean Berenstain bears?
