### ISSUE TITLE
I want to be a ghost.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#6315]
You can put a bedsheet on Ian to make him a ghost.

However you cannot wear bedsheets on your own head as a human to also be a pretend ghost. Feature when?

**Comment by PJB3005** [comment]
Uh, a bedsheet isn't really big enough for that.

**Comment by Killette2** [comment]
What are you talking about? Do you sleep in a bed for midgets? If you put a bed sheet on your head, it will cover your whole body, maybe with the exception of your shoes.

**Comment by PJB3005** [comment]
@Killette2 what kind of huge bedsheets do you use?

**Comment by Killette2** [comment]
I sleep in a queen. You know, bedsheets where they're kind of supposed to cover your whole body. Sorry if your feet stick out of the end of the bed leaving them cold, but I like to be warm in my sleep.

**Comment by ihadtoregisterforthis** [comment]
PJB confirmed for medieval german

I would add the requisite of cutting holes on the bedsheet

**Comment by Rei1226** [comment]
you using bedsheets made for a dog bed, PJB? i think even twin bedsheets cover your whole body.

**Comment by NigglyWiggly** [comment]
>There are people here who use bedsheets

Sleep on a futon like a real man

**Comment by Shadowmech88** [comment]
>I would add the requisite of cutting eyeholes on the bedsheet

Make it so that you can wear it without the eyeholes, but it blinds you.

**Comment by DeityLink** [comment]
I'm pretty sure there's already an unused sprite for that.

**Comment by Wizardcrying** [comment]
There's some server (Hippie/TG?) that allowed you to wear bedsheets as capes, where it would replace your backpack slot. It would be pretty cool if it replaced your exosuit instead (a la the Gurren Lagann capes), or functioned for both.
