### ISSUE TITLE
Obese Nukeops

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#6324]
If your character is obese and is made a nukeop, you spawn in without your jumpsuit, Cr-20, or ID card. You can't even put on the jumpsuits that are on the ship, let alone the hardsuit necessary to get to the station safely.

Either add plus-size nukeop gear, or have it check for obese characters and slim them down before making them nukeops.

**Comment by dylanstrategie** [comment]
Second option seems better

**Comment by ihadtoregisterforthis** [comment]
First option has a better ring to it.

**Comment by dylanstrategie** [comment]
I've always seen the Syndicate as the "extremely serious tryhard organization" in our version of the Backstory. Despite SS13 being a wreck and the crew always managing to blow themselves up or let the station get destroyed, they always bother to send elite forces and undercover agents to do that themselves

So even with the laid-back nature of our server, it'd make sense for the Nuke Ops to all be slim and fit. Gotta operate

And also, I'm pretty sure you cannot wear hardsuits at all while fat. Might be wrong though

**Comment by ihadtoregisterforthis** [comment]
I can't recall, but if the cripple ops didn't get removed, fat ones should stay too.
If they did get magical legs, liposuction would be coherent to this.
