### ISSUE TITLE
Ling stuck in regen mode

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6325]
(WEB REPORT BY: dafuza REMOTE: 158.69.55.2:7777)
Got robusted in bar, and was dead, but still had the ling options available, tried regenerative stasis, and started the timer, then was quickly beheaded and brained, put into a robot brain interface or whatever, and tried regenerative stasis again, now all emotes and speech result in "this would give us away!" or somthing similar.
resulting in the crew assuming I'm braindead for not speaking, and just being carried around instead of borged. 

>What you expected to happen
being able to speak and emote as a brain in a machine shell

>What actually happened
regenative stasis mode is permantly on and no emotes or speech is possible

>Steps to reproduce if possible
probably just trying regenerative stasis while in a brain machine shell form.
alterntively spamming the spell while in different stages like just a head or just a brain.

**Comment by PJB3005** [comment]
I reproduced this, it's that damn verbs don't update except if you're on a turf bug from BYOND, ugh.

**Comment by PJB3005** [comment]
And this is why verbs are a fucking piece of shit.
