### ISSUE TITLE
Saycode, say me, say us together

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6330]
1. Most languages can be understood by anyone, should them know said language or not. I.e. a plasmamen clacking on common is understood by a fleshy human.

2. Borers can't read their host's vitals. The message about listening to discordant notes appears but no diagnosis. Not 100% sure if this is saycode.

**Comment by d3athrow** [comment]
partially fixed https://github.com/d3athrow/vgstation13/commit/118e27fd7025904a74c51b47fa5394f0212a4ef6

**Comment by ihadtoregisterforthis** [comment]
Looks like the borer part is not fixed yet
