### ISSUE TITLE
Spray Grenades Don't Function Properly Inside Containers

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#6331]
I'm not sure if this is working as intended, but when a grenade that's made to spray something (like a space lube grenade) goes off inside a container that's on the ground, the visual effect happens, but none of the reagent is actually spread across the floor.

**Comment by Rei1226** [comment]
Can't get to reproduce. Put a space lube grenade in a crate, closed it, visual effect happened, and then after walking there was indeed space lube on the floor where the visual effect took place.

**Comment by Shadowmech88** [comment]
Sorry, by "container" I meant an inventory one. At the time, I was using a gift-wrapped internals box.

**Comment by Kurfursten** [comment]
Reproduced successfully with a backpack

**Comment by Shadowmech88** [comment]
But grenades spray successfully when inside a pocket, why would that work and not this? Isn't the grenade's loc still the player when it's in their pocket?

**Comment by Kurfursten** [comment]
Grenade in pocket loc = player, player's loc = turf
Grenade in bag in hand, loc = backpack, backpack's loc = player
