### ISSUE TITLE
Medical Scanner displays 100% blood always

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6332]
(WEB REPORT BY: acedick REMOTE: 158.69.55.2:7777)
>Revision 96874c752ecc178602a4043dc993fa92ad6cafb0

>General description of the issue
The new fixed medical scanners display blood level as 100% fine, but this is innaccurate, taken to a body scanner it showed it was actually less than that.

>What you expected to happen
Scanner would display the correct blood amount.

>What actually happened
Displayed 100%, person was taking oxy damage so taken to a body scanner for blood volume which was actually 70%.

>Steps to reproduce if possible
Use new scanner on person with blood loss
Check blood display to see if it changes

**Comment by dylanstrategie** [comment]
Problem with the rounding I tried to introduce, will check asap

**Comment by dylanstrategie** [comment]
Odd. I'm having trouble figuring out if it's the round proc fucking up for some reason (which it shouldn't, even the most cursory look-up shows the args should be correct) or if something isn't getting updated
