### ISSUE TITLE
Diamonds kill protolathes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6334]
(WEB REPORT BY: mrpain666 REMOTE: 158.69.55.2:7777)
Putting a diamond sheet in a protolathe completely fucks it. It doesnt register the fact that there's diamond in it and it just refuses to work. Thanks!

**Comment by Exxion** [comment]
Does it only happen with diamond?

**Comment by Kurfursten** [comment]
Reproduce-able? I got diamond-based goods from mechanics no problem today.

**Comment by Exxion** [comment]
Sounds like a runtime to me, so it is probably highly dependent upon other conditions

**Comment by mrpain666** [comment]
I've only seen it happen with diamond.

Havent gotten any reports of it happening lately. I'll close this and reopen it if I see it happen again, other things probably happened to cause this that I am not aware of.

**Comment by mrpain666** [comment]
Oh I can't close it. Honk.

**Comment by PJB3005** [comment]
I can close it.

**Comment by clusterfack** [comment]
>Oh I can't close it. Honk.

BUG REPORT BUTTON STRIKES AGAIN

**Comment by Kurfursten** [comment]
So why wasn't it closed?
