### ISSUE TITLE
Ghosts getting stuck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6336]
(WEB REPORT BY: shiggypiggy REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
Revision: 790326205857943b5106264e871e3afde1d6a076

>General description of the issue
As a ghost, you are unable to leave the confession booth in the chapel

>What you expected to happen
Nothing

>What actually happened
My ghost became visible, as per the spookening, and visible ghosts cannot travel around the chapel. All neighbouring tiles are chapel grounds. Voila, ghost is stuck.

>Steps to reproduce if possible
>be ghost
>get into confession booth
>realise you are a stale meme

**Comment by Shadowmech88** [comment]
Use the follow verb to follow someone.
Click the (follow) link of anyone in the chat box.
Double-click any turf outside the chapel.

All of these things will teleport you outside the chapel, freeing you.

**Comment by Rei1226** [comment]
Still incredibly annoying, most likely due to the new changes with ghosts being visible in the dark.

**Comment by d3athrow** [comment]
Fixed in closed source repo
