### ISSUE TITLE
Vampires are rolling Chaplains and dying at round start

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6338]
Earlier today I saw some poor sap get chosen by RNG to be both a chaplain AND a vampire. He burned to death and was fucked out of his antag round.

This hilarious issue really ought to be corrected if possible.

**Comment by d3athrow** [comment]
Can't reproduce, restricted jobs check is working as intended. Only way i can see this happening is their job didnt get assigned until after antag rolls which makes no sense as it sets occupation before calling the pre_setup anyways

**Comment by Killette2** [comment]
I was pretty sure chaplains couldn't be vampires.

**Comment by mrpain666** [comment]
If I see it happen or hear of it happening again I'll reopen it.
