### ISSUE TITLE
Request: Agent ID should be able to alter PDAs

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#6340]
Since it is a fake/hacked ID, it should be able to modify the PDA's owner, and possibly other things so you can assume a fake identity easier AND keep your antag PDA.

**Comment by dylanstrategie** [comment]
The main problem is that you can only update your PDA's job with an ID currently. Once a name is swiped in, it's locked forever, which is stupid

**Comment by 9600bauds** [comment]
While we're at it, should agent IDs be chameleonable?

**Comment by dylanstrategie** [comment]
They should be, absolutely. Just need to include that in the package

**Comment by Probe1** [comment]
holy shit its bauds

**Comment by PJB3005** [comment]
What @Probe1 have you not been in IRC for 2 days?
