### ISSUE TITLE
Continuous Beams

### ISSUE THREAD

**Issue by clusterfack** [d3athrow/vgstation13#6350]
Why are the beams not continuous yet?

What kind of beam ceases to exist for random intervals?

**Comment by Probe1** [comment]
what bothers me more than the steady intervals is when they shut off for that random, indeterminate period of time.  this is the number one cause of panic in my life as I watch and decide whether it's shut off or it's just resting.

I figure the regular intervals are just hold overs from the style of the older emitters.  

I could take it or leave it I'm not too fussed.  But when they shut off for a while and I don't know if they're working or not working.  That's when panic sets in.

**Comment by clusterfack** [comment]
Emitters! Haha I'm talking about **lasers**

**Comment by Probe1** [comment]
doh

in that cause its style I GUESS

**Comment by clusterfack** [comment]
Instead of being continuous they stop randomly and inconsistently depending on orientation

**Comment by PJB3005** [comment]
@DeityLink just used matrix transforms on the actual beam sprites, and the sprite is too short for that too actually fully fill the tile.

(same reason a 1x1 m square has a diagonal of sqrt(2))

**Comment by DeityLink** [comment]
Beams not being continuous is just a sprite issue.

If you want continuous beams then sure, I just need the following things:
* 40x40 sprites for every beams instead of 32x32
* beginning, middle and end sprites for every beams.(just like the righteous bison or the lighting bolts have)
* If someone takes the time to make those I'll do the code for them.

**Comment by Zuhayr** [comment]
https://github.com/Baystation12/Baystation12/pull/7752

Might be worth porting.

**Comment by Probe1** [comment]
those sprites give me cold sweats, even if they do provide easy to read information.

**Comment by clusterfack** [comment]
Cold sweats as in you are sweating with anticipation I hope

**Comment by Probe1** [comment]
no the sprites are turrible.  ours are much cleaner are laser-y

**Comment by SkowronX** [comment]
You know thats a lie probe. The segmenty sprites are remnants of projectile code and look like poop as a continuous beam.

**Comment by ihadtoregisterforthis** [comment]
The beams look segmentated because of the frquency of the light of something.
Stop porting stuff from servers the players hate in open secrecy.

**Comment by clusterfack** [comment]
Stop hoisting your opinions of a server onto the whole playerbase, and liking shit just because its YOUR shit and not THEIR shit

**Comment by ihadtoregisterforthis** [comment]
It's just an opinion bro

We can always make a poll or ask in the thread, but that's the reaction that I see when someone asks to port anything in public.

**Comment by Probe1** [comment]
I liked the old emitter beams better too!

**Comment by DeityLink** [comment]
In this issue: People claiming other people's taste suck.

**Comment by FudgePucker** [comment]
I don't like the sprites of bays lasers either.

I like most of the older sprites, because they go together. The old laser fits in with the old floor tiles. The new laser looks out of place and high red.

**Comment by DeityLink** [comment]
Hey guys, here's a compromise: sprite and code new laser rifles that use new linear sprites, and have the old laser guns still use the ones we're used too. Just like the retro laser gun/captain gun still uses non linear lasers.

In fact, we could use those for the xcom laser pistol/rifle

**Comment by clusterfack** [comment]
I don't think anyone really wants the disjointed ones, they just don't want to put in the effort to make sprites
