### ISSUE TITLE
Old firelocks in use on deff roid research outpost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6351]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
I'll update them.

**Comment by clusterfack** [comment]
web report

triggered

**Comment by Probe1** [comment]
why what'd I do?

**Comment by clusterfack** [comment]
Web Reports vs real reports

Web report
 - does not let us contact the user for more information
 - does not let the user close it
 - does not let the user search to see if its duplicate

**Comment by Probe1** [comment]
all good points.  and the test is concluded, I can't close a remote repo by merging a PR on my own repo.
