### ISSUE TITLE
Using the verb 'Drop Everything' removes implants

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6352]
This verb is accessible in the View Variables dropdown menu for admins.  It causes a mob to drop everything, including loyalty implants.  

These loyalty implants are correctly removed from the mob.  However the loyalty implant itself is not updated and still reports its location in the mob it was dropped from.  @clusterfack says this will cause some nasty runtimes and drop-everything should lose its ability to drop ..everything.

**Comment by Killette2** [comment]
Have you considered asking them politely to drop everything?

**Comment by Probe1** [comment]
honestly I've only seen it used like, once, on a living player who was connected and not an admin.

still good to fix it though.

**Comment by Cyadox** [comment]
I've partially fixed this is #6346 by simply not dropping anything that isn't wearable, however if it's intended to drop everything inside the mob then I'll have to change it.

Personally I don't see any reason to eject things out of people aside from debugging, but we can always make another verb for that, like drop_guts or something.
