### ISSUE TITLE
Hyperspace issue on Defficiency

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#6354]
The hyperspace around the escape pods on Deff pulls players southward instead of westward.

![space](https://cloud.githubusercontent.com/assets/7573912/10779493/008db17a-7d32-11e5-9c2d-15858df6e907.png)

**Comment by ihadtoregisterforthis** [comment]
Might happen on the main shuttle too, as a ghost it pulled me south instead of west.
Testing again left me on the middle, able to move like in regular space

**Comment by Duny-** [comment]
Ayyy, will fix.

**Comment by Duny-** [comment]
Actually, can't fix because nothing seems broke.

**Comment by unid15** [comment]
![](http://puu.sh/lcMMA/401ceab2dc.png) @Duny- pls

**Comment by Duny-** [comment]
Can't fix a value I don't know exist fam, guess I'll take another look

**Comment by PJB3005** [comment]
\>Those movers aren't even using the `dir` var.
`:|`
