### ISSUE TITLE
MoMMIs can't understand xenomorph hisses

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6359]
Either an issue or a feature request.

**Comment by SkowronX** [comment]
Intended as per how silicons language understanding is coded.

**Comment by ihadtoregisterforthis** [comment]
I'm convinced that the AI can understand xenomorph, and unsure about the pAI.

Understanding xeno can help to limit situations where the only way to tell a MoMMI to stop fixing or to stay away is by slashing them up.

**Comment by NigglyWiggly** [comment]
AI and borgs can't understand Xeno by default

**Comment by Kurfursten** [comment]
@N3X15 @clusterfack Close this? Why should MoMMIs have snowflake behavior for Xenos? At least take it off the freeze.
