### ISSUE TITLE
The "Special" button should flash if there's a new message/ahelp.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#6362]
Too many people saying "Uhh I heard message but no ahelp". This will help both admins and players.

**Comment by Probe1** [comment]
that would be sweet.

**Comment by PJB3005** [comment]
I was one of those people when I first joined /vg/, an admin has to subtle message me.

**Comment by clusterfack** [comment]
Why does everyone have special on seemingly all the time without knowing it

**Comment by PJB3005** [comment]
@clusterfack how the fuck do you even turn it off.

Also, it's on by default.

**Comment by clusterfack** [comment]
To be honest I don't even know how to toggle it, and its always been off for me

**Comment by PJB3005** [comment]
I know you can toggle it but I have NO IDEA where.

**Comment by Probe1** [comment]
It's in preferences. 

Go to Setup Character -> Preferences -> left panel near bottom Use Special Window

**Comment by PJB3005** [comment]
Aaaaaaaaaaaaaah.

**Comment by Probe1** [comment]
We got through this a few weeks out of the month with new players.

**Comment by Zth--** [comment]
I never ever knew what was special for. Interesting
