### ISSUE TITLE
Leather shoes sprite shows a pixel of skin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6365]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

ea0f3a8343449f1efca6f7ed0051037117d15d80 
Has one pixel that still shows part of your foot. Kinda annoying

**Comment by ShiggyPiggy** [comment]
Whoo, time for more changes no one notices. I'll try to fix this.
