### ISSUE TITLE
No cancel option for Cyborg name prompt and choose borg module prompt.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6370]
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777)
>Revision 038130b573642fd5381de8c7ed5e1fb1db82b04b 
Like it says in the title, can't Cancel the cyborg name prompt, choose cyborg module prompt, and probably the choose sprite menu as well.

**Comment by Zth--** [comment]
It's more of an annoying feature loss than request
