### ISSUE TITLE
The recycling furnace fucks up hard when it tries to accept plasma sheets

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6374]
It will just sit there if you involve plasma sheets at all.  It won't process any recycled materials inside the furnace and turn them into sheets.  It won't accept any new objects to be recycled.  It just sits there.  Removing the offending plasma sheets fixes it.

This worked fine less than a week ago so something recent has fucked it up.

![2](https://cloud.githubusercontent.com/assets/8550416/10825190/3f96f620-7e3a-11e5-96fa-b4e5a9ad4dee.gif)

**Comment by PJB3005** [comment]
Almost certainly a runtime.

**Comment by Probe1** [comment]
runtime error: code/game/objects/items/stacks/stack.dm:47:Assertion Failed: isnum(amount)
proc name: list recipes (/obj/item/stack/proc/list_recipes)
  source file: stack.dm,47
  usr: Securi-Clown (/mob/living/carbon/human)
  src: the solid plasma (/obj/item/stack/sheet/mineral/plasma)
  call stack:
the solid plasma (/obj/item/stack/sheet/mineral/plasma): list recipes(Securi-Clown (/mob/living/carbon/human), null)
the solid plasma (/obj/item/stack/sheet/mineral/plasma): attack self(Securi-Clown (/mob/living/carbon/human), "icon-x=18;icon-y=14;left=1;scr...")
Securi-Clown (/mob/living/carbon/human): ClickOn(the solid plasma (/obj/item/stack/sheet/mineral/plasma), "icon-x=18;icon-y=14;left=1;scr...")
the solid plasma (/obj/item/stack/sheet/mineral/plasma): Click(null, "mapwindow.map", "icon-x=18;icon-y=14;left=1;scr...")

**Comment by Probe1** [comment]
11:41:19 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:21 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:23 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:26 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:28 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:30 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:33 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:35 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:37 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:40 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:42 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"
11:41:44 Runtime detected
type mismatch: 0 + "50" at materials.dm:61
 
runtime error: type mismatch: 0 + "50"

**Comment by PJB3005** [comment]
I'm gonna need a call stack.

**Comment by SkowronX** [comment]
This happens when the amount of a sheet is a string and not an integer.

**Comment by PJB3005** [comment]
Oh fuck I realised, then how is that ending up as a string...

**Comment by SkowronX** [comment]
VV and build mode edit with the wrong typing can do that.

**Comment by PJB3005** [comment]
Skowron confirmed he fucked up his adminbus.

**Comment by SkowronX** [comment]
sorry <:V
