### ISSUE TITLE
Drinking Silcate

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6376]
(WEB REPORT BY: blarghargin123 REMOTE: 158.69.55.2:7777)
Nothing happens. Was nothing suppose to happen because the guy who added it didnt think an assistant would drink it, or is it because thats the idea. I dont know, but what if when you drink silcate your body becomes brittle like glass and 1 brute damage shatters you?

**Comment by unid15** [comment]
Sounds balanced

**Comment by AlphaBuffalo** [comment]
Well, drinking an entire tank of welder fuel gives you an insane amount of toxin damage that require the person to have an IV of anti-toxin at all time in order to not die. If drinking an entire tank of silcate does nothing, then whats the point?

**Comment by Exxion** [comment]
Definitely needs to do something, but the one here is an awful idea

**Comment by clusterfack** [comment]
Don't use the bug report button to suggest features

**Comment by Kurfursten** [comment]
Like everything else, give it an overdose of 30 so that it toxifies you at higher doses. Like drinking straight silicon, it's poison.
