### ISSUE TITLE
You can still whisper and turn while under FAKEDEATH

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6378]
By "turn", I mean when you click a turf and your character turns to face it: you can effectively roll around in place.
I suspect FAKEDEATH is rather poorly implemented and you can do a lotta more things, I just haven't tested it very much

**Comment by Killette2** [comment]
You're not faking it very well then.

**Comment by 9600bauds** [comment]
I'd rather the guy I stab with zombiepowder fake it better than that tho
