### ISSUE TITLE
Supply shuttle console gives access denied as a ghost

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#6380]
Congrats

**Comment by Rei1226** [comment]
Reproduced successfully, although its not that big of a bug. I also don't quite think it's a feature loss? Ghosts were never able to interact with the supply shuttle console before, no?

**Comment by PJB3005** [comment]
Eh look at what the mortals are ordering BEFORE it arrives I guess?

**Comment by eswordthecat** [comment]
Found the peeping ghosts!

**Comment by clusterfack** [comment]
Works for adminghosts so :ok_hand:
