### ISSUE TITLE
Chemmaster/Condimaster menu

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6381]
(WEB REPORT BY: vonzippenstein REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
6c8fd2961c2c88f756e86028b79da4e0bcb935ae

>General description of the issue
ChemMaster 3000 menu turns to Condimaster menu when you open the SnackBar menu.

>What you expected to happen
ChemMaster menu to stay as the ChemMaster menu.

>What actually happened
It turned to the Condimaster menu.

>Steps to reproduce if possible
Open the ChemMaster menu then open the SnackBar Machine menu.

**Comment by PJB3005** [comment]
Wait why is there even a snackbar menu...

**Comment by Faptastic** [comment]
:+1: This is a fun one to watch in action, you can actually make condiment bottles from the snackbar machine as well if both menus are on-screen, the reagents exist in both machines at the same time in some sort of quantum entanglement wibbly wobbly nonsense.
