### ISSUE TITLE
cache asset browser stuff

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6382]
"Unable to access asset cache browser, if you are using a custom skin file, please allow DS to download the updated version, if you are not, then make a bug report. This is not a critical issue but can cause issues with resource downloading, as it is impossible to know when extra resources arrived to you."

Its all tumbling down now.

**Comment by uazuaz** [comment]
same message for me.

**Comment by PJB3005** [comment]
Hrm, weird.

**Comment by N3X15** [comment]
Fixed in secret repo.
