### ISSUE TITLE
Radiation storm theatre

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6383]
(WEB REPORT BY: frankiethed REMOTE: 158.69.55.2:7777)
Inside the theatre on box it doesn't glow when entering a radiation storm, but you still take the damage

**Comment by Wizardcrying** [comment]
Is this a map issue?

**Comment by clusterfack** [comment]
Yes

**Comment by DeityLink** [comment]
Unable to reproduce. Might be due to multiple alerts canceling each others or something.
