### ISSUE TITLE
Using a compression implant on a Positronic Brain

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6384]
(WEB REPORT BY: sandvichman REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
89253ac0bfbd8500b8021feec901c76e0c2f037f 

>General description of the issue
You can use a Compression implant on a positronic brain. Whil it doesn't dissapear, you can use the gesture to teleport it into your hands at any time

>What you expected to happen
I would have a positronic brain inside me

>What actually happened
The Positronic brain stayed intact. I placed it somewhere, moved away, and then chuckled and the brain appeared in my hands

>Steps to reproduce if possible
Use a compression implant on a Positronic Brain, inject yourself, throw it to the other side of the room and then use the gesture for the implant

**Comment by Exxion** [comment]
That's
Um
What the fuck? I can't imagine what problem there could be with simply setting something's loc.

**Comment by Shadowmech88** [comment]
I remember hearing similar behavior about using compression implants on things that are inside containers.
Where was the positronic brain when you used the implant on it?

**Comment by clusterfack** [comment]
06:56:26 Runtime detected
Cannot modify null.imp_in. at implanter.dm:44
 proc name: attack (/obj/item/weapon/implanter/attack)
  source file: implanter.dm,44
  usr: Damian Hill (/mob/living/carbon/human)
  src: the implanter (C) (/obj/item/weapon/implanter/compressed)
  call stack:
the implanter (C) (/obj/item/weapon/implanter/compressed): attack(ARMA-314 (/mob/living/carbon/brain), Damian Hill (/mob/living/carbon/human))
the implanter (C) (/obj/item/weapon/implanter/compressed): attack(ARMA-314 (/mob/living/carbon/brain), Damian Hill (/mob/living/carbon/human))
the positronic brain (ARMA-314... (/obj/item/device/mmi/posibrain): attackby(the implanter (C) (/obj/item/weapon/implanter/compressed), Damian Hill (/mob/living/carbon/human), "icon-x=15;icon-y=15;left=1;scr...")
the positronic brain (ARMA-314... (/obj/item/device/mmi/posibrain): attackby(the implanter (C) (/obj/item/weapon/implanter/compressed), Damian Hill (/mob/living/carbon/human), "icon-x=15;icon-y=15;left=1;scr...")
Damian Hill (/mob/living/carbon/human): ClickOn(the positronic brain (ARMA-314... (/obj/item/device/mmi/posibrain), "icon-x=15;icon-y=15;left=1;scr...")
the positronic brain (ARMA-314... (/obj/item/device/mmi/posibrain): Click(null, "mapwindow.map", "icon-x=15;icon-y=15;left=1;scr...")

**Comment by Rei1226** [comment]
Reproduced successfully
