### ISSUE TITLE
Ghosts can toggle shield generators

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6385]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Shield generators that have been properly callibrated can be toggled by ghosts on and off. Tested it with myself and Yred

>What you expected to happen
To not be able to interact with something physical as a ghost

>What actually happened
It turned off and let loose the slimes of war

>Steps to reproduce if possible
Have some poor shmuk think it's a good idea to grab the shield generators from telesci and set them up. Be a ghost, click the shield generator when it isn't locked. Laugh as you unleash whatever the heck was being blocked by said telesci shield generators.

**Comment by N3X15** [comment]
Were you an admin at the time this happened?
