### ISSUE TITLE
BUCKETS FROM MONKEYS 2 :SLIMELECTRIC BOOGLAOO

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6391]
(WEB REPORT BY: puglife REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
fe046f6454ae2ac1edcaaecf1327a739f7044348

>General description of the issue
Accidentaly placed a monkey in the Slime Extractor with hilarious results(!)

>What you expected to happen
I expected not to make this critical error in the first place.

>What actually happened
Monkey went in, bucket came out

>Steps to reproduce if possible
1. drag monkey into slime extractor 2. activate extractor and wait for it to finish 3. enjoy your new bucket!

**Comment by Exxion** [comment]
I know I say this relatively frequently, but this time takes the cake:
What the fuck? I have legitimately no idea how this could possibly happen.

**Comment by PJB3005** [comment]
Putting a monkey in the processor makes a bucket of blood.

**Comment by Exxion** [comment]
Well that explains it
But where does the bucket come from?

**Comment by ihadtoregisterforthis** [comment]
Bones and fat, hair and skin.
