### ISSUE TITLE
Create mugs for cafe drinks with the rapid service fabricator

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6394]
So you don't have to keep ordering cafe crates for more mugs.

It'd also be nice if you could create new rapid service fabricators with an autolathe or something, unless you already can, and I'm just being stupid.

**Comment by AutismSpider** [comment]
need hack it i think for a service fab.

Add mugs/drinking glass to the damn auto-lathe

**Comment by Probe1** [comment]
yes to all three

**Comment by Exxion** [comment]
#6721 failed to autoclose this but it did what this asked for
