### ISSUE TITLE
Juicing Watermelon

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6396]
You can't, it does nothing. Instead of juice nothing happens at all. Watermelons aren't even consumed.

**Comment by Killette2** [comment]
Same thing happened to apples I believe, but may have been fixed. Watermelon juice used to be an item, and is confirmed by the fact that it is in some recipes.

**Comment by Kurfursten** [comment]
@PJB3005 I believe this is feature loss, since watermelonjuice exists already (line 3369)

**Comment by PJB3005** [comment]
Yes but is there code to actually make watermelons produce watermelon juice?

If yes, then feature loss, if not, then feature request.

**Comment by PJB3005** [comment]
whoops wrong button.

**Comment by Killette2** [comment]
Fuck it, we have bluespace beakers AND it fits in there anyways. No reason to have to chop them up then put them all in, so how about them apples? Haven't tested in a while.

**Comment by Kurfursten** [comment]
The whole melon actually fits in the grinder, it just does nothing when you press juice.

**Comment by PJB3005** [comment]
I actually just realised you can't put things into a grinder if there's nothing to refine it to, I can't see the explicit path for it though.

**Comment by Kurfursten** [comment]
Grinder is really confusingly written: I don't blame you for missing it, because it's not clear. The snowflake paths are not the only way that the grinder works: anything grown can be inserted because that can be ground into nutriment. So it lets you put in a full watermelon expecting you to grind for nutriment, and then it has no behavior for juicing.

**Comment by DeityLink** [comment]
Working as intended. You're supposed to juice the slices, not the whole watermelon. DUH

**Comment by Kurfursten** [comment]
The watermelon fits in the grinder, though!

**Comment by DeityLink** [comment]
Of course, you can grind it for nutriments.

**Comment by Kurfursten** [comment]
It should be juiceable as well, though. We've just completely repeated the above discussion.

**Comment by DeityLink** [comment]
Geez fine
