### ISSUE TITLE
Another dumb idea from Angelite everyone should ignore!

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#6400]
Remove the station alert when xenos arrive. If the xenos become super populated and difficult to stop, then it's a direct result of the crew's ignorance. That fixes the 10 minute viro curb stomping problem xenos are facing right now. Let's discuss this here.

**Comment by Ephx1** [comment]
That doesn't change anything really.
Most times xenos are already found before the big alert goes out.

**Comment by Probe1** [comment]
what ephx said

i've moved from:

spawning larva
to
spawning drones and hunters directly
to
spawning a fucking queen and the whole shebang 

players still kill the xenos before the alert even pops up most days.

**Comment by Angelite191** [comment]
alright, makes sense. Back to the whiteboard.
