### ISSUE TITLE
What if we improved xenos with these moderately significant changes?

### ISSUE THREAD

**Issue by Angelite191** [d3athrow/vgstation13#6401]
-Xenos are made faster

-Xenos don't slow down from pain

-Xenos hit harder, pressing towards xenos just fucking your shit up than stun lock weld spacing you all the way across the galaxy (with current 2 table spoons of blood carbons this might be problematic)

-Xeno nests now stabilize carbon occupants so after you fuck someone's shit up, you can play time trial (If you can get there before the carbon dies because you took 2 of their 5 teaspoons of blood in their entire body) to the nearest nest and face hugger combination, strap them in, and facehug them so they don't die on the embryo and two lives are wasted

-Xeno larva hatching no longer gib the fucking victim. It's lazy coding and it's also fucking stupid. This also leaves behind a valuable and edible human corpse a xeno can eat for recovery in a pinch (and for humans to fucking clone if xenos get dunked)

-Xenos can grab silicons to immobilize itself and the silicon, and reinforce the grab to disable the silicon from doing anything at all (attacking that is, it can still buzz and scream) encouraging team play and not rambo xenos trying to robust the entire station.

-Xeno blood actually acts like acid. Carbons stepping in it will take damage, hardsuited carbons will take less damage, silicons will also take damage, and mechs will take a bit of damage too, but much less so. Can be cleaned with space cleaner but it will take some time, so no walk in, spray and dunk. Encourages the concept of sacrifice and team play, coating your nest entries with your own blood to keep baddies out.

-Xeno spitting acid at objects works much faster and can be spat at mechs to seriously damage them over time. Acid globs on walls are only visible from the side it was spat on.

-Xeno hunters do much more damage than the rest of the xenos are much faster. Drones are the weakest in all areas and have the largest plasma storage pools, used for bleeding themselves, nest and queen maintenance and giving other xenos plasma which they metabolize to heal. Sentinels have a lot of HP and do benchmark amount of damage, meant for constructing and defending the nest. Xeno queens are slightly sped up (sub diona speeds are not cool) and have the largest fucking HP pool out of all of them. Supposed to be the goddamn flagship and the responsibility of progressing the population, not the candy in the center of the nest shaped pinata.

-Disarm left as means of removing the weapon from your opponent and not stun locking the

-Face huggers will damage hardsuit helmets after a period of time and continue as normal after the helmet is breached. (attach itself to the helmet as accesory if helmet slot is occupied)

-Face huggers blind the person it's attached to

-Face huggers will crawl towards and jump on to people that's near it (but jesus, they won't fight each other over it)

Feel free to yell at me for suggesting to change things. Discussion, feedback, and other ideas are also very welcome.

(I might code this myself, but knowing me, I'll never ever finish it, because I'm a terrible person that never finishes anything.)

**Comment by Ephx1** [comment]
We do already have an idea Discussion for this, you know.
#6223

**Comment by Angelite191** [comment]
T-thanks...

**Comment by PJB3005** [comment]
It'll be forgotten in 1 day, guaranteed.

**Comment by gbasood** [comment]
I just realized I assigned this to me so I'd find it later
and here we are, 5 months later

**Comment by clusterfack** [comment]
-Xeno nests now stabilize carbon occupants so after you fuck someone's shit up, you can play time trial (If you can get there before the carbon dies because you took 2 of their 5 teaspoons of blood in their entire body) to the nearest nest and face hugger combination, strap them in, and facehug them so they don't die on the embryo and two lives are wasted

This one was done actually

**Comment by Probe1** [comment]
Old discussion.
