### ISSUE TITLE
Custom foods cause clients to crash

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6402]
![star_waystation_xii_2015-11-01_14-36-09](https://cloud.githubusercontent.com/assets/8550416/10870931/8de23718-80a6-11e5-9463-ac9249a69b91.png)

shit like this.  
the server lags.  the clients crash when they get even remotely near it.  get rid of it or fix it, its been a week and I assumed coders knew but I think I'm wrong about that.

**Comment by FudgePucker** [comment]
HEY FAM, HOW MANY PLATES DO YOU WANT?

JUST PLATE MY SHIT UP

**Comment by PJB3005** [comment]
We need to cap custom food names, I recall hearing of this issue on paradise.

**Comment by FudgePucker** [comment]
Then how will I make deep fried deep fried faggot cake cake cake cake cake cake cake cake?

**Comment by PJB3005** [comment]
@FudgePucker you won't, if you want it make a bug report on the BYOND forums that's "very long atom names = crash".

**Comment by 9600bauds** [comment]
Food names ARE capped, customfood in theory should also be but I'm not sure if the cap affects the "x on a plate" dish.
Any more info on this? Does it happen any time a customfood item is made, or only when stacked heinously high?

**Comment by Probe1** [comment]
For the last 7-14 days that I've been aware of.

I don't know the exact circumstances because we've encountered it in multiple areas.  Once it was a cheese on a plate on a plate on a plate, once it was spaghetti stacked on top of 15 plates.  I would start there.

**Comment by 9600bauds** [comment]
I should have known
If goofball had commented it out
It must have been for a reason
I have unleashed the Goofball on this realm

**Comment by clusterfack** [comment]
We can't know what is causing this until someone takes the error outputted when the client crashes and puts it into a real debugger, or forces lummox to do it because afaik no one else has any idea how

**Comment by Probe1** [comment]
It's definitely plate on a plate stuff.  It's the link between all rounds, there are fresh crashes from this round.  They only started occurring when the plate on a plate meal was made.

![automated_unidentified_depot_zulu_2015-11-02_22-20-03](https://cloud.githubusercontent.com/assets/8550416/10900612/4395d880-81b0-11e5-8973-c36986e0b1b9.png)

**Comment by Iamgoofball** [comment]
simple, blacklist on-a-plates from being used in on-a-plates

**Comment by Probe1** [comment]
![automated_unidentified_depot_zulu_2015-11-02_22-27-39](https://cloud.githubusercontent.com/assets/8550416/10900714/1536d768-81b1-11e5-97e8-b403bebeddb9.png)
again, as soon as someone combines plates crashes happen.
It's definitely when a plate on a plate is made.  When two plates touch everything cocks up.

**Comment by 9600bauds** [comment]
Please update this issue if shit still crashes.
Particularly, please do test if "x on a plate" still crashes peeps even when not stacked on top of itself.

**Comment by Probe1** [comment]
I will I promise that.
