### ISSUE TITLE
Silicate Sprayer Feedback

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6405]
Just general stuff I've run into
- Weirdly much larger than it needs to be. Holds 50 silicate compared to 30 for the toolbelt size extinguisher or 20 for the toolbelt size welder. Moreover, the silicate consumed is extremely small. Fixing a half-damage window only costs .75 silicate, and a window 1-hit away from destruction only costs 1.50 silicate.
- The Adv sprayer holds a staggering 100 silicate and only costs 1 to upgrade a window
- Upgrading a window shows no change in the description or icon. There's no way to know if a window has been upgraded other than trying to destroy it or reinforce it with the sprayer again. Even just an overlay would help with this.
- Not following naming conventions. Needs to be lowercase.

Otherwise, handy.

@PJB3005

**Comment by PJB3005** [comment]
> Not following naming conventions. Needs to be lowercase.
Since when is there a naming convention for lowercase?

**Comment by Kurfursten** [comment]
What? It's not a proper noun. I'm pretty sure you yourself have told me to change this before.

For example, go open the YouTool and look at the capitalization

**Comment by PJB3005** [comment]
I put `\improper` on it though.

**Comment by Kurfursten** [comment]
It's not lower case in the vendor or when examined.

**Comment by PJB3005** [comment]
Wait what?

Okay the vendor's obviously making it lowercase.

But I've got no clue as to why examining it turns out as lowercase?

**Comment by Kurfursten** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9782036/10883303/a4a921e2-8136-11e5-8878-3fe80c8df997.png)
Why are you making a big deal out of this? Just change it to lowercase like every other non-proper noun.

**Comment by PJB3005** [comment]
There's a ton of things in SS13 that are capitalised and improper though.

The reason I'm making a deal out of it is because IMO it looks better.

**Comment by Kurfursten** [comment]
Nah, it's not a proper noun. It sticks out like a sore thumb in the YouTool because its capitalization is wrong - it looks bad. Keep a consistent style.

**Comment by PJB3005** [comment]
Okay at this point we need

**Comment by PJB3005** [comment]
Okay at this point we need a proper poll or something whether things should be capitalised or not.

**Comment by Zth--** [comment]
We don't need a poll. This capitalization is simply wrong. You don't add a capital letter to every noun when you type, then why are you trying to put it ingame?

**Comment by PJB3005** [comment]
There's a lot of things in SS13 already that are capitalised, do you want to change them all?

**Comment by Kurfursten** [comment]
It would be wonderful if someone would - or even if they would just compile a list of such things. But until then, the best we can do is fix the problems where we find them, like here.

**Comment by clusterfack** [comment]
Just fix it nerd its triggering autisms

**Comment by FudgePucker** [comment]
The sprayer isn't that big of an issue balance wise.
I still think the big problem that is a big suprise it hasn't been abused yet is the fact that there are now silicate tanks in easy to access areas. Silicate has two componints of thermite, all you need is iron and you can burn holes into secure areas.

Shit I think having tanks of sulf. acid for soldering irons would cause less mayhem.

**Comment by Kurfursten** [comment]
What's the point of having tanks in the first place if you only have to fill up a sprayer once? I've never filled a sprayer except when it was freshly printed.

You could probably safely remove the tanks from every map, since the only time someone will visit a chemist for a refill is when it's made.

**Comment by FudgePucker** [comment]
@Kurfursten Or have tanks avaliable from cargo, and one in engineering and have the sprayers start filled.

**Comment by Kurfursten** [comment]
It also may not have happened because it's not possible. Ghetto chemistry uses a white list of reactions to prevent this kind of thing. It's kinda badcode though - mostly done because months ago we didn't really know what the implications of ghettochem would be once it was in game. After the FF ends I'll PR a change to use every reaction datum without an explicit whitelist.

**Comment by FudgePucker** [comment]
Oh wait so you added every chemical by hand to the list of reactions?
Wowzers thats some dedication.

I could always make a bug issue about silicate not being able to be used in ghetto chemistry and then you can always fix the bug :^).

**Comment by Probe1** [comment]
Everything that was urgent has had its time to be addressed and everything that wasn't I put to you.  To either code it or reopen a new issue in 2016 (god nearly 2017).
