### ISSUE TITLE
Raging mages might be a bit broken.

### ISSUE THREAD

**Issue by Skullyton** [d3athrow/vgstation13#6406]
It seems that raging mages is checking if it can end early when all the wizards are dead, regardless of whether there are any remaining "Wizard tokens".

About 3 rounds it's gone "Smelelelel" while some poor sap's just gotten wizard, or the previous round where the wizard died before a new wizard was even selected.

**Comment by Ephx1** [comment]
It's been this way for quite some time, I'm not sure it's actually a bug.

**Comment by Killette2** [comment]
It's a sign of git gud I believe. Living as a wizard isn't even that hard. If you really doubt yourself, just ditch the wizrobes and buy norobe and try to disguise yourself as a normal human to avoid the lynching.

But aside from this issue, It has been this way forever, if the wizards are alive more keep coming. If they all die, the wiz feds just stop sending them.

**Comment by Skullyton** [comment]
So the other players who wanted to play wizard have to suffer because the active wizard died?

Doesn't it say when a new wizard is summoned "SF is still pissed, sending another wizard... [wizard token] amount left."
