### ISSUE TITLE
Bug with Pizzas

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6408]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
They are both invisible and inedible.
They are visible in the opened box but when you try to take them out they just disapear, even if you try to put them on a table.

**Comment by Exxion** [comment]
Beat you
#6407
Though this is more concise

**Comment by Exxion** [comment]
At least vegetable pizza.
And they don't disappear until you drop them or put them down. They're just invisible in your hand.

**Comment by Zth--** [comment]
May I ask how this stuff breaks if nobody touched that code?

**Comment by Kurfursten** [comment]
It's possible the icon existed in a commonly edited dmi file and it got deleted carelessly by someone

**Comment by clusterfack** [comment]
Typically, spriters love to save dmis over the max limit byond can hold without using our special tool that prevents byond from automatically erasing enough to bring you under the limit erasing our sprites from existence

**Comment by Shadowmech88** [comment]
There needs to be some kind of readme placed into the icons folder that tells coders what it means when a .dmi is read-only.
I fucked up some icons on one of my first PRs as well because I didn't know the icon limit was a thing.

**Comment by PJB3005** [comment]
@Shadowmech88 even then people will be idiot enough for it to happen.

And yes, I'm 100% certain the food dmi files were saturated.

**Comment by Exxion** [comment]
But why does the hotkey not work to eat it and why does it completely vanish when dropped?

**Comment by FudgePucker** [comment]
@Exxion 
Okay that is a big issue then.
Did you right click to see if the item was still there on the turf you dropped it but invisable because it doesn't have an icon? Or did it totaly get removed from existance?

This really needs more testing then, we need to test pizzas from cargo and the pizzas made from the microwave.

**Comment by Exxion** [comment]
Yes, I did
Alt+click, too
The pizza is simply gone when dropped or placed down

**Comment by FudgePucker** [comment]
Okay this is more than an icon error.

If there was an icon error then the obj would still function as normal, its just missing its icon.

I have no idea what the fuck went wrong, but this needs the OH GOD ITS LOOSE tag, because this is fucking major bug.

If it was something simple then it would be just missing its icon and function the same (Icon fuck up), if it was a fuck up with object paths it would be an invisible object called weapon.

This is something major.

**Comment by Exxion** [comment]
It's also worth noting that there is no issue with putting it back in the pizza box
That is the only thing that works correctly

**Comment by clusterfack** [comment]
If it was that bad you should have contacted an admin to VV it for its typepath

**Comment by Exxion** [comment]
I should have. No idea why I didn't. I'll go do that on local.

It's also not a sprite issue because the pizza shows up just fine in the box and that uses the same sprite.

**Comment by Exxion** [comment]
...I cannot reproduce it locally with adminspawned ones and the supply shuttle on my local server for some reason refuses to actually appear, so I can't test it locally

**Comment by Faptastic** [comment]
Local tests reveal no issues with any of the pizzas, i spawned some, ordered some in and even made some, all are fine. Might be my imagination but I could swear the supply shuttle is getting later and later.

**Comment by Exxion** [comment]
Very strange, considering two individual people saw it happen with at least three pizzas. All in one round, though. I guess something weird happened.

**Comment by Wizardcrying** [comment]
This may share the issue with runes; correctly-written runes have been sometimes disappearing (still visible by alt-clicking, but showing no sprite some of the time). This could be due to some of the animation's frames being deleted.

**Comment by Rei1226** [comment]
I believe pizzas seem to be working fine. Guess this might have just been a very weird one time thing? Probably not necessary for the Feature Freeze milestone.

**Comment by Kurfursten** [comment]
I think I remember there being adminbus going on at the time, could've caused it
