### ISSUE TITLE
Put fire on top of soot

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6409]
basically the title, fire look weird when there is soot on top of them.

**Comment by PJB3005** [comment]
I agree, we need to make soot be underneath the fire, and then get fire that changes colour according to heat.

**Comment by FudgePucker** [comment]
@PJB3005 
>Fire that changes color according to heat.

AWW SHIT NIGGA MY FAVORITE FEATURE FROM GOON.

**Comment by PJB3005** [comment]
Bay actually has that too, and it looks pretty fucking good.
