### ISSUE TITLE
Defficiency Maint "Lines" Can Be Moved With Crates

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6415]
You can't pick them up by hand, but you can scoop them up with a locker or crate to reposition them. Whoops!

**Comment by wwjnc** [comment]
it's a feeeeeature

**Comment by clusterfack** [comment]
You mean defficiency "maint" lines?

Because if you call it maint three times someone might appear

**Comment by Wizardcrying** [comment]
Defficiency maintenance
Defficiency maintenance

**Comment by Duny-** [comment]
That's hilarious, it's because they're effects rather than decals.
