### ISSUE TITLE
Paperbin in backpack: Have to remove all the papers one by one

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6417]
You can click+drag a paperbin to yourself, which puts it in your hand. You can then carry it around and put it in your backpack.
If you put it in your backpack, though, you can't put it back in your hand. Clicking it inside your backpack only takes one paper from it. You can't click+drag it to your hand slot like you can do with a backpack, either.

And that's awful

**Comment by Cyadox** [comment]
I propose that we change the pickup from dragging to just plain clicking. Hardly anyone ever uses them, and they can go through the trouble of right-clicking to grab a page.

It'd probably reduce origami spam too.

**Comment by PJB3005** [comment]
\>Right click

\>>>RIGHT CLICK

PLS NO.

**Comment by Cyadox** [comment]
What's so bad about right-clicking on the bin itself? You do that with plenty of things.

Because click-dragging out of your inventory is fucking awful and I don't even know if we can get that functionality.

**Comment by PJB3005** [comment]
Click dragging is a million times better than using right click.

We should be killing verbs altogether, not using more of them.

Verbs are complete SHIT and anything, they would work if they didn't lock up your client SO BADLY.

**Comment by Zth--** [comment]
Well, right click works flawlessly on other servers. And once in a while works smooth for me too.

Right-click verbs should stay for some things that are rarely used. Like this one

**Comment by Shadowmech88** [comment]
Did you try click+dragging it from your backpack to your sprite instead of to your hand?

**Comment by 9600bauds** [comment]
It does work if you drag it to your player character sprite instead of your hand slot, my bad.

That's really unintuitive though. It should work when dragged into your hand slot, as well.

**Comment by Probe1** [comment]
it works perfectly fine you goon, you click drag it onto your mob not your hand

**Comment by 9600bauds** [comment]
Yeah but that's unintuitive
why not both?
