### ISSUE TITLE
MoMMIs that use an illegal weapons module get red eyes

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6421]
banbait **OUT**.  mommis have no in hand sprites, cannot communicate and the only way to tell if one is emagged is the eyes.  

if an innocent mommi takes an illegal weapons module and gets red eyes, then predictably gets killed then what do we do?  some of us let it all slide, some of ban people over it, and it's a mess.  that's what.

get that shit out.

**Comment by Ephx1** [comment]
Wait.
What purpose would a KEEPER MoMMI have in installing an illegal weapons module?

**Comment by Probe1** [comment]
Good question.  While I was writing up the issue one of the two mommis that printed and installed the modules started stunning people.

**Comment by Ephx1** [comment]
Yeah ok, I think there should be free lynchings on idiotic MoMMIs installing a weapons module that completely goes against their lawset that is not able to be modified ingame by any means other than an emag,

**Comment by Probe1** [comment]
I'm resolute that this needs to go.  It isn't even *logged*.  A MoMMI could easily engineer a situation where admins don't know it had given itself an illegal weapon module, turned its eyes red, gotten killed and then ahelped it.

**Comment by Shadowmech88** [comment]
Just prevent non-emagged MoMMIs from picking weapons modules up. The modules can only be used to affect beings, it would violate a KEEPER MoMMI's laws to use it on another borg, and a KEEPER MoMMI itself has no use for it.
KEEPER MoMMIs are already unable to pick up law boards, or at least some of them.

**Comment by AutismSpider** [comment]
mommis cant pick up law boards at all unless they use a tool to do so.

Should be the same for the illegal weapons module unless it happens to be emag its not link to the keeper law set and cant talk to other mommis when emag any way.

**Comment by Ephx1** [comment]
Either what those other two said, or just get a log for it.
I still think any MoMMI attempting to install an illegal weapons module onto itself should be bashed to bits.

**Comment by FudgePucker** [comment]
MoMMIs should be able to use red crayons to color eachothers eyes red *ping
