### ISSUE TITLE
(stupid) Feature Request: Glass in blenders

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#6426]
When you put stacks of glass sheets in blenders, they should give you glass shards depending on how many sheets were in the stack.

There is no way to easily get glass shards.

**Comment by PJB3005** [comment]
I like the idea.

**Comment by FudgePucker** [comment]
It should also play a VERY LOUD sound of glass in a blender, meaning that everyone in the surounding area knows that you put glass into a blender and hate you.

**Comment by Kurfursten** [comment]
The problem is that blinders produce reagents, not items. It would have to be snowflaked in.

Might make more sense to make it a property of the food processor/slime extractor (which are the same thing just renamed). It has a more friendly behavior for spitting out objects, even throwing them.

**Comment by FudgePucker** [comment]
Holy shit I just came up with the best idea ever.
Make two new reagents, shards of glass and shards of plasma glass.
When dumped onto a turf they create shards of glass per reagent amount (might break if you dump a large blue space beaker full of it on the ground.)

BUT WAIT I'M NOT DONE YET.
The shards of glass keep their force speed, so if you put some in a sprayer, it shoots shards of glass at people, acting like a shotgun. Put some in a chemical grenade and it acts like a fragmentation grenade. Yea that's right, motha fuckin fragmentation grenades.

Also make it so that it deals brute damage when put into someones blood stream, because you know, you are putting shards of glass into their veins.

I AM THE GOD DAMN IDEA MASTER HOLY SHIT.

**Comment by ihadtoregisterforthis** [comment]
Why not liquid glass? I mean, there's already liquid hydrogen in beakers.
Sprayed could do brute or respiratory damage, if splashed make shards, if made into a reaction create entire sheets.

**Comment by Kurfursten** [comment]
According to the description of windows, they're actually made out of silicate, not glass, which makes one wonder why you build them from glass. One imagines that if you ground up glass sheets you would get silicate.
