### ISSUE TITLE
We need new (and the return of old) random events.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6428]
1.  Where's biomass.  I haven't seen biomass taking over the station in like half a year!
2.  Vines?
3.  Blobs?
4.  New stuff?  When was the last new random event added? 

This is an area we could really impact the game in a positive way with.  It's not seen much action as of late.  The only bits I've noticed are @N3X15 and @unid15 adding borers and mimics/otherthingsofmaybequestionablechoice, and dylan reworking meteors.  Which for the record, is great.  They could even stand to be a little stronger.  But they're once again an event that is significant enough to acknowledge.

That last line is the heart of my issue.  Most of our events are stale and insignificant.  They're old.  They haven't been touched in a while. And they've gotten easier via coding or gotten easier via players discovering effective techniques to counter them.

We need more!  And luckily, there's 2-3 that should be happening right now but aren't because of bugs!

**Comment by Skullyton** [comment]
Looking at the code for events today, and noted some peculiarities.

1. Meteor event has 2 different form of projectile attacks, Meaty attacks (Throws limbs, monkey, and carp meat at the station) and Sausage Fest (Throws Sausages and Faggots at the station), that I have no idea how they're triggered.

2. The Borer infestation event is gameplay-wise broken, as there's no longer a check to see if the borer has a host or not because debug reasons, this means that there's just a whole lot of braindead borers dropped in a random room.

Infestation events could do with a bit of a rework, like for instance the amount of mobs in question scaling with the size of the room so placement somewhat mattered more.

**Comment by Kurfursten** [comment]
It  seems half the time that a breeding/infestation event pops, nothing actually appears at that location

**Comment by clusterfack** [comment]
That could be a result of misnamed areas

**Comment by Kurfursten** [comment]
Could we resolve that by adding a sanity check to ensure the area exists, as with the adminverb jump to area? Then, if it doesn't exist, fire again with a new location.

**Comment by mrpain666** [comment]
I want to see more Ion storms. Most of the time that shit is hilarious.

**Comment by clusterfack** [comment]
Yes we could add an error check an adminlog to check for broken areas

**Comment by 9600bauds** [comment]
add maint bears as random event

**Comment by Zth--** [comment]
Add an event where angry mobs keep spawning from a random portal

**Comment by Kurfursten** [comment]
@9600bauds If you add maint bears, you have to add an announcement from centcomm denying that there are maint bears because "that part of the station isn't technically 'maintenance' per se"

**Comment by Probe1** [comment]
> If you add maint bears, you have to add an announcement from centcomm denying that there are maint bears because "that part of the station isn't technically 'maintenance' per se"

oh god yes

**Comment by Probe1** [comment]
Spitball ideas:

Fire in a random location
Explosive depressurization in a random location or breach.

Hard mode random events that are the same as current events but more challenging and have higher requirements to occur 

Doubling the amount of events by having two fire side by side.

**Comment by Skullyton** [comment]
Space lube interstellar cloud?

modified Meaty ore storms that shoot clowns, bananas, cream pies, and bananium at the station?

**Comment by ihadtoregisterforthis** [comment]
What's the deal with the current ones? Wallrot is negligible, infestation is a nuisance at best should it actually happen, the greytide message does nothing, the rogue drone barely gets close the station, ion storms aren't random, no biomass.

Mimics are great and I saw an extermination team think it was over when it became a cigarette butt. 100% deceiving. Carps mating is a real problem if left untreated.

**Comment by Kurfursten** [comment]
Greytide doesn't work anymore? It worked last time I saw it

It's supposed to open every brig cell and bolt it open

**Comment by Probe1** [comment]
Graytide definitely works and comes up frequently.

**Comment by Probe1** [comment]
>Vermin infestation

>Bioscans indicate that slimes have been breeding in Technical Storage. Clear them out, before this starts to affect productivity.

A good way to kick this up is to make them *actually breed*.  For every X ticks there are still mobs in the area, they spawn more and move to new adjacent areas.  Ignoring those slimes could quickly turn into a station threatening infestation.

**Comment by ihadtoregisterforthis** [comment]
Biomass happens successfully on the test server, Elim added some new monster spawns, Carps are getting attention.
Borers as vermin infestation are less worthless, but they still mark the slugs as a menace.

What does the malignant trojan do?

**Comment by PJB3005** [comment]
Breaks all lights in the brig and bolts open all airlock from perma to the exit.

**Comment by Probe1** [comment]
I feel like we got some good ones now!  There's always room for improvement but this is outdated.
