### ISSUE TITLE
Diona Shoulder Evolution destroys inventory

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6429]
(WEB REPORT BY: ruskalon REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
Evolving from a Diona Nymph while being carried by another player, while equipped with a backpack and carrying a radio headset resulted in the carried and worn items disappearing.

>What you expected to happen
I had expected the backpack and radio headset to remain in my Diona's posession, or at least fall to the floor.

>What actually happened
The worn backpack and held radio headset disappeared.

>Steps to reproduce if possible
Prepare a diona for Evolution. Equip the diona nymph with a backpack or other back-slot item, and have it hold a radio headset. Next, have another player pick up the diona nymph. While being held by the other player, the nymph should then evolve.

**Comment by PJB3005** [comment]
Definetly a missing `get_turf()`

**Comment by Probe1** [comment]
As a side note, dionas can evolve while dead and come back to life if they had met the prerequisite to evolve.
