### ISSUE TITLE
If you lose power as AI, sight might not return

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#6435]
So if you lose power, get carded, your sight won't return.
If you're put back in the core, sight won't return even with power.
You have to relog before sight actually does return.

**Comment by d3athrow** [comment]
Can't reproduce.

>Lose power, get carded, sight returns after the emergency backup shit finishes

>lose power, get carded, put back in, sight returns

>lose power, get carded, power returned, put back in, sight returns.

**Comment by Ephx1** [comment]
Very interesting, the scenario happened like this. Core battery removed, power lost, then I went through the searching process for the APC, it connected to the APC with no power, I was carded, then power was given back to the APC, then placed back in.
