### ISSUE TITLE
Supply Shuttle Ordering/Requests Consoles Need Love

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6436]
These things are ancient, clunky, and look awful -- worst yet, an entire department pretty much revolves around its use. Wouldn't it be nice if you could approve orders without navigating 3 screens in between each approval?

Here's a mockup I threw together pretty quickly in MSPaint based off of the jsview template of @9600bauds 's Autolathe. But as @N3X15 @PJB3005 and @clusterfack have mentioned, we're shifting (I believe?) toward the use of .js/.css-based browser datums such as PJB's power monitor and @d3athrow 's crew monitor (and interactive map in general).

![console mockup](https://cloud.githubusercontent.com/assets/9782036/10952389/131601cc-8308-11e5-9fa2-50bcb2f8af21.png)

I'm terrible with interfaces, so maybe someone with a little more skill will pick this up.

**Comment by Probe1** [comment]
Scott Taylor did this on gitlab but I told him nanoUI wasn't acceptable.
https://gitlab.com/vgstation/vgstation/merge_requests/140

**Comment by PJB3005** [comment]
I would do it, but the issue is I'm working on Clockcult and this time I'm not gonna sidestep until it's done.

**Comment by Kurfursten** [comment]
@Probe1 That looks pretty good. Pity about the format.
