### ISSUE TITLE
WEIRD VISION

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6439]
(WEB REPORT BY: sjbenster REMOTE: 158.69.55.2:7777)
744abd88f09ac89383d40b4c2e197c412414e3d6 
Several rounds in a row I die or go into crit and for some reason my vision gets stuck in one place while my body moves around.

**Comment by d3athrow** [comment]
I can't get this to happen to me.

**Comment by Skullyton** [comment]
I remember this happening around the time explosion screen shake was brought in, the way you'd get out of this screen lock was by pressing "Cancel Camera View". Not sure if that was fixed or not.

**Comment by ghost** [comment]
This has been fixed, pretty sure.
