### ISSUE TITLE
Using a pda reagent scanner on a piece of the goofkitchen bread puts the pda inside

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6442]
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777)
>Revision 744abd88f09ac89383d40b4c2e197c412414e3d6 
As the title says

**Comment by Zth--** [comment]
That bread must be hard to swallow

**Comment by 9600bauds** [comment]
I won't be available to look into this come Monday or so, if noone has done so by then though I'll see about it

**Comment by Kurfursten** [comment]
Would anyone object to bread insertion getting the same restrictions as frying? e.g.: it has to be edible

**Comment by 9600bauds** [comment]
Absolutely, the point of bread insertion is largely to smuggle or hide things, not to hide people's dessert inside their bread because ???

**Comment by Kurfursten** [comment]
If the whole point of an item is to smuggle something, it is usually bad at smuggling. E.g.: If bread only exists to smuggle, it should be the first thing searched on a chef. The reason a person might want to put food in bread is the same reason you do anything else as a chef, like putting food in a burger or food on a custom pizza.

I see your point and I won't press the issue, but I just think you articulated it in a silly way.
