### ISSUE TITLE
Master Trainer Belt Loyalty w/ Full Hands

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6444]
If you buy a Master Trainer Belt when you have no free hands (e.g.: if you try to buy two in a row), it instead drops the belt at your feet and immediately spawns all six mobs - hostile to you instead of friendly.

**Comment by Cyadox** [comment]
Kek

Is the belt supposed to spawn all 6 when dropped or something? That sounds like unusual behaviour.
Regardless, I think a simple fix would be a sanity check for items in hand, and producing an error message.

**Comment by Wizardcrying** [comment]
Kind of funny, looking at the New() code.
```dm
/obj/item/weapon/storage/belt/lazarus/antag/New(loc, mob/user)
	var/list/critters = typesof(/mob/living/simple_animal/hostile) - /mob/living/simple_animal/hostile
	critters = shuffle(critters)
	while(contents.len < 6)
		var/obj/item/device/mobcapsule/MC = new /obj/item/device/mobcapsule(src)
		var/chosen = pick(critters)
		critters -= chosen
		var/mob/living/simple_animal/hostile/NM = new chosen(MC)
		NM.faction = "lazarus \ref[user]"
		NM.friends += user
		MC.contained_mob = NM
	..()
```
It seems that the mobs are trying to make friends with the floor and not you, but the part of them being all immediately spawned I can see in the code, but I don't quite know why it does that.

**Comment by Probe1** [comment]
Can't reproduce.  Clusterfack couldn't either.
