### ISSUE TITLE
proc/hex2num going apeshit and runtiming 2400 times in a few hours.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6447]
http://ss13.undo.it/logs/Dev/runtime/2015-11-05-runtime.log

 runtime error: hex2num given non-hexadecimal string (user error)
proc name: hex2num (/proc/hex2num)
  source file: hexadecimal.dm,44
  usr: null
  src: null
  call stack:
hex2num("w")
GetBluePart("yellow")
/datum/light_source (/datum/light_source): parse light color()
/datum/light_source (/datum/light_source): check()
lighting (/datum/controller/process/lighting): doWork()
lighting (/datum/controller/process/lighting): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(lighting (/datum/controller/process/lighting))
19:06:43 Runtime detected
hex2num given non-hexadecimal string (user error) at hexadecimal.dm:44
 proc name: hex2num (/proc/hex2num)
  source file: hexadecimal.dm,44
  usr: null
  src: null
  call stack:
hex2num("el")
GetRedPart("yellow")
/datum/light_source (/datum/light_source): parse light color()
/datum/light_source (/datum/light_source): check()
lighting (/datum/controller/process/lighting): doWork()
lighting (/datum/controller/process/lighting): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(lighting (/datum/controller/process/lighting))

**Comment by Probe1** [comment]
It started at 19:06:43 and was not present in any logs from the previous week.

**Comment by Probe1** [comment]
Might be admins changing the color of a light without inputting a correct hex value.  Could be resolved by running a check?

**Comment by N3X15** [comment]
> GetRedPart("yellow")
Yep

**Comment by clusterfack** [comment]
Nice one

**Comment by Probe1** [comment]
Since this is one off and I've told the admin not to do it I don't think it's a code issue.  And adding sanity to a VV edit seems difficult.

**Comment by PJB3005** [comment]
Sanity for VV wouldn't be very difficult, if we were to refactor VV to be OOP.

It's just a matter of adding enough sanity.
