### ISSUE TITLE
0, 0, 0 explosions still cause screen shake, stationwide audible booms, and bhangometer responses

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6450]
Do you think we should have a check against at least the bhangometer and zlevel ogg if the explosion doesn't surpass 0, 0, 0 yield?

The thing that had me wonder was a player repeatedly lighting a cigarette dipped in welder fluid with no delay so he could spam explosions pretty effectively.  Explosions that didn't really happen.  Or they happened, but they had no effect on the world.

I'm not sure how people feel about it.  After observing for an entire round of it I think it's pretty annoying but it could be one of those ITS A FEAAAAAAAAATURE things for others.

**Comment by Zth--** [comment]
Screenshake should start with dev 4 bombs

**Comment by PJB3005** [comment]
Agreed
