### ISSUE TITLE
DNA Modifier interface not opening

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6451]
(WEB REPORT BY: kbcy REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0bc99ee56c79820ed82f77d8d9e7e2cb0a514aa5 
> 
> General description of the issue
> After putting the disk i was not able to open the interface
> 
> What you expected to happen
> Interface to show up
> 
> What actually happened
> Interface not opened
> 
> Steps to reproduce if possible
> Put a monkey in
> Make it a human with clean SE
> Put in a Disk
> Profit?

**Comment by PJB3005** [comment]
Hrm, something tells me a runtime's causing this, since maybe the disk has corrupted data?

**Comment by Hoshi-chan** [comment]
This happens randomly with the DNA Modifiers in genetics, not just under the circumstances the OP described. I experienced it a LOT during the week or so that I played genetics almost exclusively. They're real messed up.

**Comment by PJB3005** [comment]
Wait, so first the chem dispenser, then the DNA modifier?

NanoUI what the fuck are you doing?

**Comment by 9600bauds** [comment]
nondescript "nano doesn't open" issue
