### ISSUE TITLE
Cyborg losing sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6453]
(WEB REPORT BY: gamblorez REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
Cyborg losing its sprite

>General description of the issue
Chose wrong module and after clicking the cancel button on the sprite chooser menu sprite disappears

>What you expected to happen
Hitting cancel of the sprite choosing menu to go back to choosing module

>What actually happened
After clicking cancel the menu closed and my sprite disappeared

>Steps to reproduce if possible
Choose the service module(Thats the one I chose don't know if its just that one or not) and when it asks you to choose a sprite hit the cancel button. Thats it.

**Comment by Wizardcrying** [comment]
We need to start tagging these kinds of issues as [T-Thanks BYOND] because these are issues with DMIs.

**Comment by Hoshi-chan** [comment]
Since when can you cancel out of a selected module? It used to be that once you picked your module and went on to sprite selection, you were stuck with that module.

**Comment by PJB3005** [comment]
@Wizardcrying these aren't BYOND issues, at all.

**Comment by clusterfack** [comment]
Someone 'fixed' an issue but didn't add a return clause for null (the default response for cancel) I would suppose

**Comment by Wizardcrying** [comment]
@PJB3005 Ah, nevermind then.

**Comment by Probe1** [comment]
tag it as thanks coders

**Comment by PJB3005** [comment]
Sorry that tag doesn't exist, I mean I could make it but people would get mad at me.

**Comment by clusterfack** [comment]
Don't bully the newbies

**Comment by PJB3005** [comment]
They obviously didn't test it for shit though.

**Comment by Zth--** [comment]
Oh shit. I tested all but that one, thinking that it should work. Gonna revert soon
