### ISSUE TITLE
Borer Deafness

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#6454]
As a borer I could not:
* Hear my host
* Hear other humans
* Hear any sound other than emergency shuttle dock and call
* See any emotes

But I could see emotes from my host, like nodding, or smiling.
Before I was in a host, I could hear other people.
Also of note I was a spawned in borer via adminbus.

**Comment by chainsauce** [comment]
The exact same thing happened to me a couple hours ago. Also similarly, admins were involved in that I was teleported by an admin at one point, so not really spawned by one. Unless maybe they did it by creating another borer and then putting me in it and then deleting the old one?

**Comment by N3X15** [comment]
It should just work[tm]. Login() instantiates the virtual listener.  If that's not called, I can see it happening, but I can't reproduce this easily on a local server with SAY_DEBUG turned on.

**Comment by clusterfack** [comment]
Well you guys may want to specify where you were when you had these issues, say if you were inside a host you shouldn't be able to see emotes outside of your hosts, simply from the mechanics of the game/code.

Not being able to hear other humans/hosts is troubling. I haven't heard explicitly of any problem with virtualhearers in many months, so I'm inclined to think it is a runtime but I'm unsure.

**Comment by Ephx1** [comment]
Inside a host = Completely deaf, no emotes other than host
Outside = Normal

I swear I got emotes and messages like laser firing before this but oh well.

**Comment by clusterfack** [comment]
Emotes have never been recursive, you cant hear them within anything and sounds are likely the same. You should be able to hear spoken words inside however.

**Comment by N3X15** [comment]
I'm going to add in a hook for the host Hear()ing messages.  Should fix it.
