### ISSUE TITLE
Xenos can't slash open canisters

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6455]
I'm almost 100% sure that they used to be able to do this. Now they can't. It just opens up the menu, which gives you, "YOU DON'T HAVE THE DEXTERITY TO DO THAT" anytime you press something on it.

Using acid on a canister just deletes it. If you (or someone else) depressurizes your nest, there's no fixing it, whereas you used to be able to slash an air canister open to restore the atmos.

**Comment by clusterfack** [comment]
That should be covered by attack_animal, why would attack animal be checking for dexterity, baka desu senpai

**Comment by PJB3005** [comment]
@clusterfack I think they mean that any UI buttons on the canister say you don't have dexterity.

**Comment by Hoshi-chan** [comment]
@clusterfack What @PJB3005 said.

**Comment by clusterfack** [comment]
Yes but attack animal should be damaging the canister and then preventing the menu from opening at all

**Comment by Hoshi-chan** [comment]
Well, it's not. You click it on harm intent and it just opens the canister menu, then the interface buttons tell you, "YOU DON'T HAVE THE DEXTERITY TO DO THAT".

**Comment by clusterfack** [comment]
And thus the bug tag

**Comment by PJB3005** [comment]
I'm unable to find an override for `attack_animal()` in canister code.

**Comment by clusterfack** [comment]
picnic!

**Comment by DeityLink** [comment]
Xenos were never meant to slash open canisters. Are you mad?

**Comment by clusterfack** [comment]
What are you talking about, xenos could always slash open canisters

**Comment by DeityLink** [comment]
@clusterfack citation needed

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/machinery/atmoalter/canister.dm

Find me a single version of canister.dm that had an attack_alien()

**Comment by PJB3005** [comment]
I can too remember aliens being able to slash open canisters.

**Comment by DeityLink** [comment]
Never seen it happen in 2 years.

**Comment by Duny-** [comment]
I also remember slashing canisters open as alium, and I played quite a bunch of alium in my time

**Comment by DeityLink** [comment]
Well just because I don't remember it happening doesn't mean you guys can't code it back. I just think it'll make the xenos even more overpowered than they currently are. Geez the other day Yred was even complaining that tackle isn't a guaranteed permastun anymore.

**Comment by Duny-** [comment]
>xenos
>overpowered
Did I miss like ten buffs?

You're overestimating this ability in any case.

**Comment by clusterfack** [comment]
It lets xenos use that secret passive they have that plasma in the air also recharges their plasma stores

**Comment by Duny-** [comment]
And then they die to the plasmafire that inevitably happens.
Tested, approved.
