### ISSUE TITLE
Def Mass Driver Chute Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6456]
(WEB REPORT BY: orzorn REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
37c0b9a61d5d67ffe4539401a346d0b6219915da

>General description of the issue
On Defficiency station, in the toxin's test mass driver room, the glass directly behind the mass driver can be broken by the chute from the disposal when running things other than bombs through it, such as bodies. This spaces the atmosphere in the room.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Duny-** [comment]
Will fix
