### ISSUE TITLE
Security on Deff

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6458]
- No sec hardsuits.  None.
- No sink in the bathroom.  The only bathroom is in the perma/cells area and the HoS office, both of which can be inaccessible to security depending on the occupancy of either place.
- The whole kitchen and botany thing just does not work.  I'm pretty sure the public botany area has ID restricted doors.  The kitchen definitely does.  No one uses it or goes there.
- Armory protection in general is incredibly weak and being highly visible does not offset that.  One door or one rwall is all that protects it.

**Comment by Duny-** [comment]
>The whole kitchen and botany thing just does not work. I'm pretty sure the public botany area has ID restricted doors. The kitchen definitely does. No one uses it or goes there.

No harm in leaving them here though. Who knows, maybe one day eating will become mandatory or it'll be part of some chef's gimmick or whatever. Adds a possible escape route with external help at any rate and deff's jail needs one.

>Armory protection in general is incredibly weak and being highly visible does not offset that. One door or one rwall is all that protects it.

I can add viscerators in the back if you want :^)
There's not much room for additional protection and honestly I don't much see the need for it, I rarely see people rob it but I could be wrong about that. What do you suggest?

**Comment by Probe1** [comment]
I have no suggestions on this one, I'm just floating my thoughts after playing sec on deff 3 rounds in a row.  People just hacked into sec and laughed off that one door protecting the armory and took what they wanted.  

The bulletpoints are in descending order.  No hardsuits is a HUGE problem for security.  They have to travel a long way to EVA and even then, they get a crummy space suit.  That's the one thing that needs helped.

The washroom is the second priority so you can figure from there how important I think "redesigning half the brig" is.  It can wait.  But I think it eventually needs to happen because the entire kitchen/botany area is dead space no one ever uses and the rest of the brig is cramped or missing creature comforts to make up for it.
