### ISSUE TITLE
Deff issues

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6459]
**Science**
* R&D has no gadget bags.
* There's a major blind spot in the AI's cameras between robotics and R&D. Essentially, the main science entrance is off-camera.
* Not sure how it could be improved, but the science shuttle entrance is terrible. Break a window or two, or emag the doors, and you depressurize all of science, maybe even killing the monkeys/slimes in xenobio and genetics if they open the door or force the airlock without thinking.
* No easy access to plastic due to no plastic flaps just outside of R&D. Do what the box mappers are afraid to do and just give science 10 sheets of plastic at roundstart or something.

**Medbay**
* Medbay has no general access crew monitoring computer, which everyone is used to thanks to Box.
* Cloning in medbay is C R A M P E D. I'm not sure how it can be improved due to limited space, but I always wind up removing everything in the room except for the cloner itself (table, wardrobe, etc.).
* As mentioned in other issues, there's a distinct lack of spray bottles. A bar of soap could be nice, too.

**Cargo**
* There are six mining hardsuits but only one mining vendor, which is on-station. Please add a second mining vendor and put them both on the asteroid station, seeing as the miners straight-up spawn there, and there is no real mining office in cargo.
* An ATM on the asteroid mining station would be super nice, too, due to the changes to accounts requiring miners to change their account security every round or transfer money to their virtual wallet every time they're paid.

**Comment by Duny-** [comment]
>Not sure how it could be improved, but the science shuttle entrance is terrible. Break a window or two, or emag the doors, and you depressurize all of science, maybe even killing the monkeys/slimes in xenobio and genetics if they open the door or force the airlock without thinking.

Yeah the place is really cramped I'm not really sure how I could fix that, the only place in science I could shrink is xenobiology and I kind of like it the way it is. Any ideas?

>No easy access to plastic due to no plastic flaps just outside of R&D. Do what the box mappers are afraid to do and just give science 10 sheets of plastic at roundstart or something.

Why does science want plastic and why can't it be made at botany?

>Medbay has no general access crew monitoring computer, which everyone is used to thanks to Box.

Intended, just because Rei ruined paramed on the other maps doesn't mean I'll let Deff fall to this design oversight too. The silicons, paramedics and CMO should be the one consulting these computers regularly. All other heads and the captain also have access to one on the bridge. That's more than enough.

>Cloning in medbay is C R A M P E D. I'm not sure how it can be improved due to limited space, but I always wind up removing everything in the room except for the cloner itself (table, wardrobe, etc.).

Yeah I was told to reduce cloning's size to give medbay itself more room, everything on this map is so tightly put together finding more room is always at the expense of something else. 
I guess I could move the bodybags in genetics and remove the closet altogether for more breathing room.

Nothing to say about the rest of the issues, I'll look into fixing them. Thanks for the feedback fam.

**Comment by Hoshi-chan** [comment]
>Why does science want plastic and why can't it be made at botany?

Science can't even research diamond mining drills without plastic anymore. They can no longer produce pico manipulators for materials research 6 without plastic. So either the miners show up with enough diamond with two sheets to spare for materials 6 and 7, or somebody's not getting their drill. This can be bypassed on Box by deconstructing the plastic flaps outside of R&D for 10 sheets of plastic, which any scientist worth their salt does.

Science shouldn't be reliant upon botany to function at basic capacity.

>Yeah the place is really cramped I'm not really sure how I could fix that, the only place in science I could shrink is xenobiology and I kind of like it the way it is. Any ideas?

Maybe turn the research shuttle the other way, horizontally instead of vertically? Or make it a lot smaller, like a two-seater with two empty tiles behind it. Just enough room to bring an object and another person back without getting stuck.

You could also maybe just repurpose the mining shuttle, since it's centrally located on the station, to be an all-purpose asteroid shuttle that can dock at either station by selecting a different destination on its console before launch. You could then expand science's various departments, and maybe even genetics/cloning, to be a little more roomy, without the big shuttle squatting right in the middle of the department.

>Intended, just because Rei ruined paramed on the other maps doesn't mean I'll let Deff fall to this design oversight too. The silicons, paramedics and CMO should be the one consulting these computers regularly. All other heads and the captain also have access to one on the bridge. That's more than enough.

I actually kind of agree with this, I was just passing the criticism along from others playing Deff today. Paramedics were already marginalized by the removal of dragging causing internal injuries; taking their CMC access away made them ENTIRELY redundant.

**Comment by Duny-** [comment]
Fair enough, I'll add just enough plastic to R&D.
I'll see what I can do with the shuttle too, thanks for the ideas fam.
