### ISSUE TITLE
Hivebot meat

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6460]
I was under the impression they were robots.  When killed (gibbed more accurately) they drop hivebot meat.

**Comment by clusterfack** [comment]
What has science done

**Comment by Kurfursten** [comment]
Hivebots give organic meat
TRUE or FALSE?

78% of respondents get this question wrong

**Comment by Probe1** [comment]
Further testing - constructs produce meat when gibbed in addition to ectoplasm.

**Comment by AutismSpider** [comment]
even the SCP gibs into meat when hit by the shuttle constructs hive bots and other mobs

Cyborgs/mommis gib like normal
