### ISSUE TITLE
Character setup occasionally makes you bald without warning

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6463]
Been having to check character setup before joining or observing for so long that I'd forgotten this was an issue, not a feature.

This issue probably already exists somewhere deep within the pile of open issues, but I think it's worth reposting again, especially due to feature freeze.

**Comment by Probe1** [comment]
oh yeah that's an old one going all the way back to when the character setup page was redone.

**Comment by gbasood** [comment]
#7015 related

**Comment by Intigracy** [comment]
#7015 close one of these
