### ISSUE TITLE
Can't use APCs

### ISSUE THREAD

**Issue by Duny-** [d3athrow/vgstation13#6465]
![ss 2015-11-07 at 03 23 13](https://cloud.githubusercontent.com/assets/5224390/11015648/478bb144-8566-11e5-8934-e9655787057a.png)
Every single time. Resending resources does nothing.

**Comment by PJB3005** [comment]
THANKS NANOUI.

**Comment by Rei1226** [comment]
This has also been extending to security cameras. NanoUI has been REALLY bad lately and just not updating whatsoever.

**Comment by clusterfack** [comment]
Security cameras don't use nano

**Comment by Cisrox** [comment]
this can be closed now ^^^^^^^^
