### ISSUE TITLE
Superconducting-Magnetic-Energy-Storage Power Storage Unit.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6467]
Somebody discovered PIN number syndrome.

(it says this on the UI of the SMES: "SMES Power Storage Unit")

**Comment by Kurfursten** [comment]
But energy and power are different, so it's not exactly like "PIN number". Power Distribution Unit (PDU) might be more apt, since it performs both storage and work.

**Comment by Exxion** [comment]
The term "Power Storage Unit" doesn't even make any sense on its own. But SMESes manage it anyway because, as I recall, their storage levels are measured in Watts, a unit of power.

**Comment by PJB3005** [comment]
@Exxion actually might be watt-ticks come to think of it.

I can't actually find a reference to Watts being used anywhere for energy storage in the code.

**Comment by Exxion** [comment]
JUST FUCKING SAY JOULES

**Comment by PJB3005** [comment]
NO BECAUSE A TICK ISN'T SECONDS.

**Comment by Exxion** [comment]
GOD FUCK
