### ISSUE TITLE
Can't see the map on Crew monitoring computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6469]
(WEB REPORT BY: sacidepatinete REMOTE: 158.69.55.2:7777)
Like the Issue said, I just can see stars, no maps.

/\

See the map

Only see stars

Going to crew monitoring computer

**Comment by Probe1** [comment]
same bug as always that people have had since we switched to html

**Comment by PJB3005** [comment]
Update to IE 11 if you haven't already.

**Comment by clusterfack** [comment]
Is there a way to detect what IE a client has and tell them to update in a messageif they don't have a version supportive of html?

**Comment by PJB3005** [comment]
@clusterfack conditional comments?

**Comment by FudgePucker** [comment]
Is this really a bug then?
The problem is with external software not the game itself.
If someone hasn't installed and set up VLC, is them not hearing the jukebox a bug?
