### ISSUE TITLE
SMES and powernet as a whole have been very inconsistent over the last couple months.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6475]
![image](https://cloud.githubusercontent.com/assets/8550416/11018649/96ca50a4-85a1-11e5-9952-34058cf38bce.png)

This is the engineering experience.  2 megawatts in the grid, SMES won't charge.  Then they charge an unpredictable time later and stop charging.  They have been fucking up.  APCs have been too.  Even when there is plenty of juice, they just won't charge sometimes.  

Basically, they update really badly.

**Comment by clusterfack** [comment]
You have VV, check some variables and bring some real numbers

**Comment by PJB3005** [comment]
@clusterfack the power monitor is that source, go to the SME power monitor and use that, you'll see it has a shitton of power, yet the SMES don't charge.

**Comment by PJB3005** [comment]
Oh and there's also that issue that's extremely obvious from watching the power monitor chart for a while: the grid suddenly *dies* only to next tick come back at double power

**Comment by PJB3005** [comment]
Oh, found the issue.

The SMES needs 3 to 6 ticks of having sufficient power before they start charging, if a spike like above happens, they'll die for 3-6 ticks.

**Comment by Probe1** [comment]
I'd VV it if I had the slightest idea what was going on that caused it.  Anyway the SMES have been staying off for longer than 6 ticks.  More like 30 seconds.  Whatever that is in ticks.

**Comment by clusterfack** [comment]
6 ticks is 24 seconds in powernet time

**Comment by clusterfack** [comment]
The double power bug I believe is a result of the fact they have different controller datums set to the same process time. In my theory one can occasionally process 2 or 0 times before the other one does if it gets unlucky.

That would be fixable just by putting them within the same scheduler process.

**Comment by PJB3005** [comment]
@clusterfack yeah IIRC paradise did that.

**Comment by PJB3005** [comment]
Oh, and APCs need 10 WHOPPING TICKS of power before they start charging.

**Comment by clusterfack** [comment]
This wouldn't have been as noticeable until d3athrow changed the powernet to process every 4 seconds instead of 2

**Comment by PJB3005** [comment]
@clusterfack I ment machinery processes though, not powernet processes, for the APCs and SMES.

So for the SMES that's 6 to 12 seconds, for the APCs 20 seconds.

**Comment by clusterfack** [comment]
Power machinery, which process the same speed as powernets

**Comment by PJB3005** [comment]
Ah, I thought they process at the same speed as machines.

**Comment by clusterfack** [comment]
They used to

**Comment by Rei1226** [comment]
Is it intentional for SMES' to be charging for a few ticks, then not charge for a few ticks, then charge again, etc.?

**Comment by PJB3005** [comment]
@Rei1226 no not really, it's caused by a sudden desynchronisation between the powernet and power machines, which'll cause the power in the net to die, then double to what it used to be next tick, SMES stop charging when this happens, and need 3-6 ticks before they start charging again (this is intentional).

**Comment by dylanstrategie** [comment]
The powernet as a whole is worse than Hitler currently

Generally, the only valid way to run it is to set up an engine properly (absolute minimum plasma cooling on the Singulo, atmos tank hooked TEG or maintained AME) and then wire that shit directly to the grid

Not bypassing the SMES cells is a terrible idea because of how unstable they are. If they are even a single W under the charge threshold, everything collapses

**Comment by clusterfack** [comment]
I have fixed this, but in the case this happens again you can reopen this issue
