### ISSUE TITLE
Bucket Watering Sounds Are Gone

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6476]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

37c0b9a61d5d67ffe4539401a346d0b6219915da

**Comment by clusterfack** [comment]
Can you make a good bug report for once rei

**Comment by PJB3005** [comment]
@clusterfack they used to make a sound when you used them for certain things, like for watering hydro trays.
