### ISSUE TITLE
Security no longer has EVA access

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6477]
What it says on the tin.

**Comment by Probe1** [comment]
Neither does medical.  @Faptastic 
https://github.com/d3athrow/vgstation13/pull/6443

**Comment by PJB3005** [comment]
I think it was because EVA didn't use EVA access, but sec + engie + medical or something ridiculous, those jobs need to get EVA access.

**Comment by Faptastic** [comment]
I did say I revoked the access and replaced it with EVA, I ensured those jobs could get into their respective sections of EVA once inside the room however, that part is untouched.
It was indeed using engie/med/sec before, it's a restricted area they really shouldn't be able to just waltz in without EVA access or the doors being bolted open.

While you're changing access levels you may want to inspect the indentification computer, lawyer for example doesn't actually work.

**Comment by Hoshi-chan** [comment]
Going to the HoP's desk every round for EVA access is not the solution here. Either all affected jobs need EVA access added on, or the access on the doors needs to be changed back.

Why was this even something that needed to be changed? It makes sense. You either have general EVA access, or your specific departmental access opens the appropriate doors.

**Comment by Probe1** [comment]
It was changed because the EVA doors did not have EVA access, and instead had an amalgamation of different department accesses.  Who knows how the fuck that happened.  

Anyway the problem was the HOP would give johnny joe EVA access and he'd come back and say wait man I can't get in.  

Easy fix.  Just give some people EVA access.

**Comment by Hoshi-chan** [comment]
They really don't need EVA access, but it would be nice if they did, in case of emergency, like medbay being blown up and their office being gone.

Also, I had assumed that what you meant was that the EVA doors were all EVA, with the added access of medbay, science, engineering, atmos, etc., meaning that someone with EVA access could access everything, while someone with departmental access could only access EVA, the O2 storage, and their department's hardsuits.

**Comment by Probe1** [comment]
Honestly for a LOT LESS WORK we could just change the doors access from ALL to ONE and add EVA, medical, engineering, security to the doors.

I don't know which is better.  On one hand, if we give certain jobs EVA access then we can be more selective and not every random guy in the dep gets a hardsuit.  On the other hand, that takes way more work to maintain.

**Comment by Hoshi-chan** [comment]
If not every guy, then who? In terms of medbay, for example, the CMO is the only one who should ABSOLUTELY be getting one of the hardsuits, assuming he's not dead, but in that case, shouldn't he just get one in his office? Who would the other person with special privilege be? For sec, it'd be the HoS and Warden, but both of them have access to the armory hardsuits, and for engineering, they already have 7 hardsuits between them, plus the CE's hardsuit.

Speaking of the armory hardsuits, why don't they have O2 tanks with them? Why aren't they in hardsuit storage lockers? That always bothered me.

**Comment by Probe1** [comment]
The CMO is really how we came to this point.  Metaclub was ported.  There was a medical hardsuit in the CMOs office.  Someone said "We have an empty room in EVA and medical hardsuits!  Perfect!".

I suppose the security hardsuits are there because it hasn't been changed in a very long time and it still has the old style (that you still find on other servers) from before SSUs existed of using a rack.  

Well, it's a sticky issue with a lot of questions and discussions and since it was just a bug fix that went sour I'll fix it now and we can (never but lets pretend) figure out in the future how to balance it.

**Comment by Hoshi-chan** [comment]
Honestly, compared to deff and meatclub, Box EVA is garbage. Why would the general access EVA area have DEPARTMENTAL hardsuits? And only hardsuits. No softsuits to speak of.

Each department should just have their own pair of hardsuits somewhere. Remove the 4 extra engineering/atmos suits entirely, give sec a fourth hardsuit in the armory, stick the two med hardsuits in med storage or put one in the CMO's office. Fill EVA with regular-ass spacesuits. Any joe schmo that hacks a door off the primary hallway shouldn't get full protection from cold and pressure, plus armor against melee, plus close-to-full runspeed.

**Comment by Probe1** [comment]
Deff only has softsuits, and meta has no medical or security suits.  

That's a cool idea though and probably something we should do in the future.  For now I'll just add eva access to however goddamn many jobs there are in sec and medical.

**Comment by Faptastic** [comment]
I would agree EVA is a glorified storage room for departmental suits and could stand to gain from a row of standard space suits.
I would say I regret changing it were it not for dem codervalids, gotta fight the freeze etc. etc.
