### ISSUE TITLE
N2O not a real gas

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6481]
Basically, if N2O floods a room, the air alarm picks it up as "other". Not only that, but the distribution and waste monitor doesn't even recognize it as a separate gas, but as just Oxygen and Nitrogen. I dont know if this affect scrubbers from filtering out the gas from rooms, but this is more about the computers and air alarm not being able to differentiate it from the other gases

**Comment by clusterfack** [comment]
Yes, in ZAS it is known as a 'trace gas'

**Comment by AlphaBuffalo** [comment]
Oh so it was like that by design?

**Comment by clusterfack** [comment]
To reduce processing time for uncommon or rarely seen gases yes

In a perfect world we could implement a relatively efficient 'datum gas' system, which can treat any single kind of gas individually but the last time one was made it was too inefficient and got removed.

**Comment by AlphaBuffalo** [comment]
Oh, so we could never see a situation where combining two gases in atmos will create a new gas, like mixing O and N to make N2O
