### ISSUE TITLE
Janicart Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6491]
(WEB REPORT BY: orntoo REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
82da52e0443da19444e800b56d7bd390819c6444 

>General description of the issue
Putting 2 bags on a janicart is bugged.

>What you expected to happen
Either it wouldn't let me put a second one on the cart or both would be hooked on.

>What actually happened
Had a bag on my cart, put a second one from maintenance on it and the first one disappeared completely along with everything inside it.

>Steps to reproduce if possible
Put 2 bags on cart.

**Comment by Wizardcrying** [comment]
Fixed, will put in a PR soon.
