### ISSUE TITLE
Animated Objects Indistinguishable Alive from Dead

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6494]
This may be intended, but an overlay - like, angry eyes on animated targets or a red glow - would be really helpful in knowing when to stop beating. Staff of Animation is a strong enough item without the need for no way to tell when to move on to the next target.

**Comment by Hoshi-chan** [comment]
Or when to stop firing on an animated welder tank.

**Comment by DeityLink** [comment]
Can be done.

**Comment by DeityLink** [comment]
It is done. #6553
