### ISSUE TITLE
Cargo shipping via disposals is fucked again

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6496]
I havent the chance to check what goes where with what tags yet, but I'm getting a lot of feedback that shit gets shipped incorrectly again.

**Comment by mrpain666** [comment]
Oh and it happened on box.

**Comment by dylanstrategie** [comment]
Make sure that only one crate is sent at a time

If you send all of them in one flush, it all goes to the same spot

**Comment by Probe1** [comment]
there are 28 destinations and it takes 30 seconds to test each one.

**Comment by Probe1** [comment]
It took me 39 minutes but I tested all 28 locations.  They all worked fine.  39 minutes damnit.  

Unable to reproduce.

**Comment by uazuaz** [comment]
most people misunderstand how disposal mailing system works; items are sent in bunches, not individually.
here a little guide:

-when an item enters in the delivery chute inside delivery office, a countdown starts; it's about 10 seconds;
-if another item enters the delivery chute before the countdown ends, the countdown resets and starts again;
-if the countdown expires, you can hear the faint noise of a piston and ALL the items inside the delivery chute will be sent AT THE SAME DESTINATION
-if there are no items tagged, the items will be sent to the recycling/disposals room; if there is 1 item wrapped+tagged, ALL the items, even the unwrapped/untagged ones, will be sent at the destination of the tagged item;
-if there are multiple wrapped+tagged items at the same time inside the delivery chute, only the last one sets the destination.

examples:
-you need to send 4 crates to engineering; just put all 4 on the conveyor belt and wrap+tag as "engineering" only 1 of them, all of them will reach engineering;
-you need to send a goat crate to hydroponics but the goat crate is unwrappable/untaggable; just take any other item, for example a piece of paper, wrap+tag it as "hydroponics", put the wrapped paper and the goat crate both on the conveior belt and let them go togheter; both of them will reach hydroponics;
-you put 3 parcels on the conveyor belt, one tagged "bar", one tagged "theatre" and the last one tagged "medbay"; all 3 parcels will be sent to medbay.

sorry my poor english. by the way i hope this helps, would be nice if this will be added on the wiki.

**Comment by mrpain666** [comment]
ok
