### ISSUE TITLE
Amputating a damaged limb and replacing it with a new one somehow retains the damage of the amputated limb

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6500]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
First issue: Taking off somebodies damaged limb, say an arm, surgically, and then replacing it with a different limb (In my case, a robotic one) kept the damage, despite the damaged arm being on the floor of the surgery room.

> How to recreate this

Find somebody with a bad arm (Any points of damage to it) (Might also have to be a corpse). Go through the surgical steps to remove the damaged limb. Go through the surgical steps to prep the area where the limb should be. Put in a new arm. Wonder why the new arm is damaged now.

**Comment by ihadtoregisterforthis** [comment]
>draws back the plunger and gets... nothing?

Confirmed skeleton inside you, seek help set it free.

**Comment by Kammerjunk** [comment]
CLUSTEEER

**Comment by clusterfack** [comment]
What

**Comment by clusterfack** [comment]
Oh I already fixed the blood thing

**Comment by FudgePucker** [comment]
@clusterfack Yes but instead of getting limitless bugged blood he gets nothing.

**Comment by clusterfack** [comment]
Yes and then I fixed that you nerd

**Comment by FudgePucker** [comment]
oh... needs testing tag then?

My guess for the limbs issue is that the limb damage isn't connected to the limb you removed but the mob itself, meaning when you put on an entirely new limb it keeps the damage. Did you try just fixing the brute and burn damage instead of replacing the entire limb? Thats probobly why this hasn't been noticed, it is easier to fix a limb than replace it, so if someone has some treatable damage you would try to just pill them up instead of dragging them to surgury.

**Comment by Kurfursten** [comment]
On the subject of the first issue, the same thing is true of robots. I still think it's odd I can print an entirely new camera for a cyborg, take out the old broken one, stick in the new one, and still have to repair the camera.

**Comment by Hoshi-chan** [comment]
Cyborg repair has always been fucked up like that.

**Comment by Probe1** [comment]
@Skullyton are any of these still active bugs?

**Comment by Skullyton** [comment]
@Probe1 The no-blood's fixed, gonna check on the surgery.

**Comment by Skullyton** [comment]
@Probe1 The limb thing's still there

http://i.imgur.com/CSd0v7D.png

**Comment by Probe1** [comment]
okay that's terrible.  and maybe some rounding for wounds goddamn

**Comment by Skullyton** [comment]
@FudgePucker The reason I was doing it was because the guy was at -110 health, so assumedly cutting off his highly damaged arm would make it possible to then defibrilate and treat him on the wild ride extended edition
