### ISSUE TITLE
Floral somatorays still don't work

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6504]
Just a reminder. They were kind of key to botany, as I remember it.

**Comment by 9600bauds** [comment]
Can you elaborate on "don't work"? As far as I remember, they do work, they're just ass.

Related to this, I'm working on a rather large hydroponics PR that will see the light of day after feature freeze, which covers the snoreatoray.

**Comment by Hoshi-chan** [comment]
I don't know enough about botany to elaborate.

I know that during the past two weeks, in chef/bartender roles, I've seen botanists use them, unsuccessfully, for the better part of two minutes with no results, before tossing them away in frustration, and as a scientist, I've offered them to botany on several occasions, as used to be custom, only for them to turn them down claiming that they're broken.

Either they're so weak that their effects are completely unnoticeable, or they're just plain broken.

**Comment by wwjnc** [comment]
Not a bug. You're probably complaining about somatorays not mutating the *plant species*, which they can't since alpha somatorays call the tray's `mutate()` with a severity of 1. Plant species mutation only happens when severity is greater than 1.

Is it intended? No. Is it bullshit? Yes. Advanced somatorays when?

**Comment by 9600bauds** [comment]
coming soon after this feature freeze ;^)

**Comment by Probe1** [comment]
:+1: 

doesn't work

**Comment by 9600bauds** [comment]
it doesn't increase the yield STAT, it increases the yield_mod, which (unintuitively&almost imperceptibly) causes the plant to give more fruits when harvested

likewise the mutation mode has a really dumb chance to work, something like 10-20%

like I said, coming soon :^)
