### ISSUE TITLE
You can't shoot in the dark

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6508]
(WEB REPORT BY: cumoverme REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
a928ee32814e5ac78c3e14ede83fdc0aea2954e0

>General description of the issue
You can't shoot in the dark.

>What you expected to happen
To be able to shoot in the dark.

>What actually happened
It does nothing.

>Steps to reproduce if possible
Get a gun, click at a dark tile.

**Comment by Wizardcrying** [comment]
Same issue as #6493

**Comment by clusterfack** [comment]
A conspiracy to make duplicates?
![](http://i270.photobucket.com/albums/jj81/GnayDrawoh/Okabe%20Rintarou/okabephone.jpg)
