### ISSUE TITLE
The wild and wacky world of firelocks around the Bar on Deff

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6513]
![hats_relay_94_2015-11-10_01-30-18](https://cloud.githubusercontent.com/assets/8550416/11056045/945226ca-874b-11e5-9a89-efb7b7f2ed3e.png)

Firelocks should be on doors.

**Comment by Duny-** [comment]
I don't see the point of putting firelocks on doors, excepted for causing intense frustration (and arguably even more atmos leakage) when you have to open both and go through before one of them closes.

**Comment by Probe1** [comment]
>go through before one of them closes.

butt thats the point.  you open one, close it behind you, and then open the other so only a small amount of backwash gets through.

at the time I took the picture the halls were superfucked and the lack of firelocks around doors made it worse.

I did make it an issue and didn't change it myself though because I'm arguing design and not bug reporting.

**Comment by Duny-** [comment]
>on doors
>on

Probe pls

The double set in the hallway is meant to be used the way you describe. The doors add an additional layer of protection, that's all.
