### ISSUE TITLE
Standardized special role notifications for ghosts/observers

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6518]
Currently, they're all over the place. Diona and borers, for example, will notify you that a diona is being harvested or a borer egg is being hatched, and offer you the opportunity to teleport to the location, sign up, or retract (if you opt-in by default). This is done regardless of your preferences.

Positronic brains, pAIs, and aliens, however, do not. They give you a teleport/retract message if you're opted into them by default, but they don't tell you that anything has been activated if your preference is disabled.

On a more controversial note, I'd really like to see this for other special roles that have NEVER had this feature, such as admins pressing the wizard button, the nuke ops button, or summoning a response team. I think that the wizard spawn might even use the ancient pop-up method of notification that posibrains and the like used to use, where you'd accidentally trigger "Yes" when it pops up as you're typing. You might wind up with more interesting admin-spawn antags this way if everyone observing knew that the roles were being put up on offer, rather than someone suddenly just getting wizard and naming themseves, "Well, okay then."

**Comment by PJB3005** [comment]
Definetly, if anything I'll probably include them in clockcult unless somebody makes them before that's done.
