### ISSUE TITLE
When you hack a vend and it runs out of inventory it freaks the fuck out

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6521]
Kept forgetting to report this one.  The bug showed up right after https://github.com/d3athrow/vgstation13/pull/6084

![2015-11-10_10-15-02](https://cloud.githubusercontent.com/assets/8550416/11066016/544abd64-8794-11e5-806c-3deaec8b9559.png)

**Comment by FudgePucker** [comment]
It might be because it picks a random item to throw, even if the item is sold out, then freaks out. Maybe have it check for >0 to put in the list to pick from?

**Comment by Probe1** [comment]
Probably a sound move.
