### ISSUE TITLE
Glass doesn't protect from Containment Field

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6537]
Made a singularity containment with a thin glass pane to avoid accidental cuddles with the field, but looks like it didn't work at all.

![i m not misbehaving](https://cloud.githubusercontent.com/assets/13305885/11083771/06af5d3e-8812-11e5-80c9-733dec5b042c.png)

Kinda counter intuitive for the field to affect through materials, unless that's how they work.

**Comment by 9600bauds** [comment]
HasProximity() doesn't check for windows in the way
honk honk
