### ISSUE TITLE
Megaseed Servitor seed names vanushed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6538]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Probe1** [comment]
The only thing I can think of is https://github.com/d3athrow/vgstation13/pull/6533

![corrogated_station_ten_2015-11-10_23-38-47](https://cloud.githubusercontent.com/assets/8550416/11084039/6a813be2-8804-11e5-88ec-738530128d32.png)
