### ISSUE TITLE
Megaseed Servitor seed names vanushed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6539]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
The seed names in the megaseed servitor are gone. 

>What you expected to happen
The seeds have normal names.

>What actually happened
They're all called "packet of seeds".

>Steps to reproduce if possible
n/a, it was that way from roundstart

**Comment by Probe1** [comment]
duplicate
