### ISSUE TITLE
Missing RIG suit from Engineering

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6540]
(WEB REPORT BY: kaizo45 REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
 071c19886ca5cb816cd1238d1231362955d7a865

>General description of the issue
there's nothing in the leftmost hardsuit case in box engineering at roundstart

>What you expected to happen
a rig suit to be inside

>What actually happened
nothing was inside at all

>Steps to reproduce if possible
start round check space suit box

**Comment by Probe1** [comment]
verified on a local server.  will fix.
