### ISSUE TITLE
Permabrig on Box needs to have its own APC and Area

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6542]
This is a feature request.  I'm making a note for myself.

The Prison area always runs out of power every shift because there are like 8 rooms being powered by one APC.  It needs to be broken up between permabrig itself, and the halls/solitary/execution.

**Comment by FudgePucker** [comment]
Brig running out of power is a bug :^)

You should fix it anyways

**Comment by Rei1226** [comment]
Last I checked didn't the permabrig have the SPACE BAR area? I feel like I remember seeing that when I was re-designing the bar eons ago and going "what the fuck?"

**Comment by FudgePucker** [comment]
Permabrig needs a space bar then with a mini podbay using plastic flaps.

**Comment by Probe1** [comment]
um
