### ISSUE TITLE
MegaSeed Servitor bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6551]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
# Bug 1: Second generation and above seeds (Ones that have been extracted from the seed extractor) lose their icon once put into the megaseed servitor and retrieved.
# Bug 1.5: Possibly related to bug 1, some seeds that come out as question marks, when planted, yield no plant at all.
# Bug 2: Upon putting in an extracted seed into the Servitor, all other seeds lose their name besides the ones that are listed as 'out of stock'

**Comment by Probe1** [comment]
partially but not completely a duplicate of 
https://github.com/d3athrow/vgstation13/issues/6538

**Comment by ghost** [comment]
Check if it still happens with Botany3

**Comment by 9600bauds** [comment]
Still happens, haven't looked into it yet, I don't like this vending machine storage business

**Comment by 9600bauds** [comment]
Related to #7684

**Comment by gbasood** [comment]
Botanist put some potato seeds into the vendor and apparently it added to the total count of tomato seeds.

But when he ejected them, the packet was empty.

![](http://i.imgur.com/gAfQs51.png)
???

**Comment by 9600bauds** [comment]
Deity needs to look into this

**Comment by 9600bauds** [comment]
I'm just gonna link all the related issues here @DeityLink

**Comment by Exxion** [comment]
Easy solution: Just remove the ability to put seeds back in the MegaSeed Servitor
Normally I don't advocate for removing features in order to fix bugs, but this is a special case because there are two other machines _right there in hydroponics_ that do a better job of storing seeds than the Servitor ever will

**Comment by 9600bauds** [comment]
A lot of people don't know the Seed Extractor works too
How to make it more intuitive?
