### ISSUE TITLE
EMPs should disable suit sensors

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6552]
Makes sense right?  I was surprised it wasn't already in the game.  It adds a whole new dimension to it.

**Comment by Shadowmech88** [comment]
Makes EMPs somewhat dangerous even to non-augmented humans.
I like it.

**Comment by dylanstrategie** [comment]
It would be better if it randomly scrambled them

Either way, this will have very few, if any practical uses. You can still disable suit sensors instantly by stripping

**Comment by Probe1** [comment]
Yea but it would mean you could open with an EMP, shutting off headsets and such

**Comment by Wizardcrying** [comment]
Not quite instantly @dylanstrategie because worst case scenario is where the guy has a hardsuit on, so you have to wait out the delay on him and even then you have to strip off the jumpsuit too. Being able to EMP a room with your target can give you some assurance that you won't get a stun baton up the ass while you try to take a guy out.

**Comment by PJB3005** [comment]
I like it.

**Comment by Kurfursten** [comment]
Maybe needs a message. I can't imagine ever remembering to turn mine back on if I walk by the singularity.

**Comment by Hoshi-chan** [comment]
Wait, it doesn't??

**Comment by dylanstrategie** [comment]
Headset EMP is silent, hell the whole Singularity EMP is silent

It's very common for Engineers to be off radio if they worked on the Singularity recently

**Comment by Kurfursten** [comment]
Yeah, but I notice my headset is off as soon as I try to talk on the radio. I could literally go an entire shift and not notice my sensors.

**Comment by SonixApache** [comment]
I always forget about the sensors till the medbay nerds bitch about them on the radio. Don't think having it silent is an issue.

**Comment by Zth--** [comment]
You hear a beep from your suit

**Comment by Probe1** [comment]
Might as well go direct and tell em. << Your suit sensor shorts out!

Theres no reason to obfuscate it.  Its not like EMPs are stealthy.  Except for the aforementioned singlo.
