### ISSUE TITLE
[Trigger Warning] [Autism]

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#6559]
![aaah](https://cloud.githubusercontent.com/assets/7573912/11107658/4eeeabd0-88e0-11e5-9cda-365a90ad6457.png)

MY AUTISM, IT BURNS

**Comment by clusterfack** [comment]
Triggered

**Comment by PJB3005** [comment]
JESUS CHRIST NOBODY NEEDED TO SEE THAT

**Comment by Probe1** [comment]
Checked.
