### ISSUE TITLE
Defficiency Power Feedback

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6562]
I know that a lot of people pressed for @Duny- to make it easier, but now it's just ridiculous. We observed a shift where power was not set up until past fifty minutes and the SMES were still powered. This is too much, especially because you don't need to do any setup to the SME on Deff. As Lenny Webb demonstrated to us, one can of nitrogen and no changes to the piping resulted in the chamber never getting hot enough to take damage (evened out at 450K, well below 800K). @PJB3005 expressed concerns that the default setup would not work, but I have now observed it working first hand.

On the otherhand, default SMES output is still too low. The cause of Atmosia turning off so fast is NOT that there is not enough power in the SMES, it is that you have be knowledgeable enough about the map to turn up the SMES output before you start work. If you do not increase the output, Atmosia will never charge at all, meaning it will turn off a few minutes into the round.

**Comment by Probe1** [comment]
Yeah we observed the same thing.

I think the answer here is to break up rooms that are too big into multiple APCs and lower the SMES starting #

**Comment by Duny-** [comment]
I can lower the starting charge of the SMES cells, I may have overdone it a bit.
However, I have no idea how to turn up the SMES output from mapping, if it's even possible. (not like it's hard to do it yourself in-game anyway)
Also, I always said the default SME setup was good enough, but the people wanted it to be easier anyway, and N3X15 provided a casual setup when he remade the room. Am I supposed to make it less baby-mode again? This is becoming the AI core all over again.

**Comment by Kurfursten** [comment]
Maybe Probe can do some polling

**Comment by FudgePucker** [comment]
I think having a simple SME isn't that bad considering that there isn't a singluarity I think (right? Its been a while sense I played def and last time was when ghosts ruined everything on halloween.).

Can't the SME on box also work with out any modifications if you set it up correctly? (As in don't set the scrubbers to syphon and let them filter, insert chilled N2 into the chamber, and don't over pressure the chamber so that it properly chills using the coolers and properly extanges air between the vents.)

**Comment by Kurfursten** [comment]
Deff SME has changed since you've seen it, it has windows and the piping is different now, but yeah, it's easy.

That's not really what we're discussing though. The SMES (Power Storage Units) have too much power by default because people harassed Duny to make it easier.

**Comment by FudgePucker** [comment]
@Kurfursten Ah I understand now.
Still, its debatable on if you should lower it too much.
Some engineers don't know how to set up the SME, some engineers can't set it up fast enough.
They need more time than box, but probably not as much time as it is now.
