### ISSUE TITLE
Alium Regurgitate is busted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6566]
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
f1ec4a92f99a9f5d4b39822a7a3ac5c9c8625db9

>General description of the issue
Can eat whatever you want, but you can barely regurgitate anything. I ate a guy, but couldn't spit him out. Ate three monkeys, one came back out. Ate another guy after that, and again he was stuck.

>What you expected to happen
People to come out of my stomach

>What actually happened
People stayed in my stomach. This is some Vore shit.

>Steps to reproduce if possible
Eat a nigga then try to spit him out again.

**Comment by Probe1** [comment]
For what its' worth it worked fine for me and I think what happened was the player didn't find the regurgitate verb then devoured a monkey.

This is a problem.  There needs to be a check to see if an alium has something in its stomach already, or else the previous mob they devoured gets deleted.

**Comment by Exxion** [comment]
And again I must say:
We need fucking storage atoms
Not that that in itself would entirely fix the issue, but it would make it easier to fix

**Comment by clusterfack** [comment]
...It's called a list exxion

**Comment by Exxion** [comment]
But that still doesn't fix the problem of people dropping things while in the stomach

**Comment by PJB3005** [comment]
@Exxion except it does.

**Comment by Exxion** [comment]
How so? Unless you specifically code it to add dropped items to the list, which would be substantially harder and less reliable than just putting the devoured mob in a storage atom.

**Comment by PJB3005** [comment]
And then you suddenly regurigate the storage atom.

**Comment by Exxion** [comment]
What? No, you regurgitate its contents. I don't mean just throw it in haphazardly with no edits to the code. I mean give xenos a stomach storage atom into which devoured mobs are placed and dump its contents when regurgitate is used.

**Comment by PJB3005** [comment]
@Exxion your argument for why we need storage atoms is entirely because of shit oldcode, and even with storage atoms you would have shit oldcode, so it doesn't matter.

What we need to do is keep a list of things in the xeno's stomach, and then regurgitate the things in that list.

**Comment by Exxion** [comment]
But then every single way an object could possibly leave a mob would have to be manually coded to add the dropped item to the list, whereas a simple move to the parent's loc puts it properly in the storage atom.

**Comment by PJB3005** [comment]
At this point I've got no fucking clue what you're on about anymore.

**Comment by Exxion** [comment]
Could you be a bit more specific as to what I have to clarify?

**Comment by PJB3005** [comment]
Everything.

**Comment by Exxion** [comment]
Say a mob that is devoured drops something. Unless that item is added to the list of things to regurgitate, it will remain permanently inaccessible within the xeno. OK, so make it so that dropped items are added to the regurgitate list. But then a different devoured mob is gibbed somehow while inside the xeno. The gibs magically appear on the turf because they for some reason are coded to no matter what and all the items the mob had on it are now forever in the xeno. Every way an item can be dropped form a mob or even appear at a mob's location would have to be coded to add it to the regurgitate list. If the stomach is a storage atom, though, only the code for the xeno would have to be changed and all of that (except the gibs because get_turf) would magically work just fine with no complex manual adding to lists.

**Comment by PJB3005** [comment]
...Okay I get it now and that makes sense.

**Comment by 9600bauds** [comment]
When you eat people they start taking damage from being fucking digested
If they die from it they are qdel'd

**Comment by Intigracy** [comment]
easy fix fam

var/devoured = null

(when eating someone)

```
if(!devoured)
 target.forceMove(src)
 devoured = target
 visible_message("fat fucker [src] ate [target]")
else
 to_chat(src, "you greedy fat fuck you already have something in your stomach")
```

(when spitting them out)

```
if(devoured)
 devoured.forceMove(src.loc)
 devoured = null
for(obj/O in src)
 O.forceMove(src.loc)
new (whatever path for vomit is)(src.loc)
visible_message("[src] vomits its stomach contents on the ground.")
```

this assuming objects dropped inside of a xeno behave correctly and go into its contents

Could even keep people taking damage while inside of a xeno, just remove the qdel

**Comment by Exxion** [comment]
> `for(obj/o in src)`

The problem is that works only if there are NO other objects in the xeno that should be ejected when you regurgitate
I'm not sure whether or not that is the case, but it likely isn't
Which is why a stomach storage atom is a good idea, as it would work exactly the same way you just suggested except `for(o in src.stomach)` and it would be guaranteed to not make big bad problems

**Comment by Intigracy** [comment]
What are we, vore?

```
for(obj/O in src)
 if (O in (organs|whatever other lists))
  continue
```

**Comment by Exxion** [comment]
What
No, mobs are just very complex things and there are lots of things that can go wrong with haphazardly throwing all objects out of their contents lists
Not to mention that what you just suggested would still have any mobs dropped by the devoured person (such as an ejected borer, an animal they were holding and dropped while inside, a xeno larva that burst from them, etc.) trapped within the xeno, as `mob` is not a child if `obj`

**Comment by Intigracy** [comment]
```
for /mob/M in src
 if(isborer(M))
  var/borerpath/B = M
  if(M.host = src) continue
 M.forceMove(src.loc)
```

**Comment by Exxion** [comment]
What if the xeno has a borer in their brain?
I'm pretty sure that's possible at least

**Comment by Intigracy** [comment]
updated

**Comment by Exxion** [comment]
That is a bad and dumb snowflake "fix" and you know it
Why is everyone afraid of storage atoms?

**Comment by Intigracy** [comment]
effort involved

**Comment by Exxion** [comment]
*sigh

Fine, I'll do it, then

**Comment by clusterfack** [comment]
I think storage atoms are a bad idea that'll probably just increase GC issues

**Comment by Exxion** [comment]
Not if done correctly
And nobody has mentioned a different way to do it that doesn't involve snowflaking in every possible exception to things that should be dropped

**Comment by clusterfack** [comment]
Yeah and we handle things in a case by case basis to decrease GC issues

**Comment by Exxion** [comment]
The GC shouldn't have any problems with storage atoms if their Destroy() procs and those of their holders are written properly

**Comment by clusterfack** [comment]
And thus we come first circle

>that doesn't involve snowflaking in every possible exception to things that should be dropped

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/13902977/b344ea3a-ee3a-11e5-8e1f-64f100035885.png)

The whole purpose of the storage atom is that EVERYTHING in it is supposed to be dropped

**Comment by clusterfack** [comment]
Storage atoms will simplify nothing, anything we need to do to preserve sanity for the regular holder would also need to be done on the 'storage atom'. It's a retarded concept.

**Comment by Exxion** [comment]
Why? _Everything_ in the storage atom is dropped. There's nothing in it that is supposed to stay in it. No sanity is required to keep certain things from being dropped when it's emptied because there _are_ no such things.

**Comment by clusterfack** [comment]
Where's the BENEFIT in your storage atom? Are borers going to not be stored in it?

**Comment by Exxion** [comment]
Of course not

**Comment by clusterfack** [comment]
See all your doing is just shit that can be done with lists, thats all your storage atoms are fucking accomplishing.

**Comment by Exxion** [comment]
Scroll up and read the discussion I had with PJB on this exact topic.

**Comment by clusterfack** [comment]
Its the same amount of fucking code either way you moron. Except this way we're introducing overhead in the form of another fucking atom/movable for this shit.

**Comment by Exxion** [comment]
How much overhead is one `atom/movable` per carbon (not even simple animal) xeno? Almost none, comparatively.
And please show me how to do it with just lists in the same amount of code.

**Comment by clusterfack** [comment]
Now I will be the reasonable one and say that in this instance, a atom for storing the stomach contents is a sensible way of solving the problem.

But 'storage atoms' as a general idea (when literally every atom is already implicitly a 'storage atom')? No thank you.

**Comment by Exxion** [comment]
I didn't mean in every instance
I meant in things like xeno stomachs, spacepod/mech cockpits, and sleeper/body scanner chambers
It's unnecessary for things that don't store mobs as well as things that store mobs but at some point dump their entire contents list, which is... nearly everything I didn't just list

**Comment by Intigracy** [comment]
#3333
