### ISSUE TITLE
Turning off a welder while removing glass from a airlock breaks the airlock

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6569]
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
f1ec4a92f99a9f5d4b39822a7a3ac5c9c8625db9

>General description of the issue
If you shut off your welder while removing glass from an airlock, the door completey fucks up and you can't continue constructing or de-constructing it.

>What you expected to happen
The glass to be removable after I turned my welder back on

>What actually happened
Couldn't use a single tool on the damn thing.

>Steps to reproduce if possible
Go up to a door, cut all the wires but the bolt one, crowbar the controller out, then turn off your welder while removing the glass pane.

**Comment by PJB3005** [comment]
I can confirm this.

**Comment by Probe1** [comment]
As can I, sorry I lost track of things and meant to say so.
