### ISSUE TITLE
PROBE WANT TEARGAS.  PROBE MAKE ISSUE.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6571]
Another one for the itd be cool list.  Paradise has em.  Bays porting em.  Are we being left behind in the malodorous arms race?

**Comment by Probe1** [comment]
```
obj/item/weapon/grenade/chem_grenade/teargas
	payload_name = "teargas"
	desc = "Used for nonlethal riot control. Contents under pressure. Do not directly inhale contents."
	stage = READY
	New()
		..()
		var/obj/item/weapon/reagent_containers/glass/beaker/B1 = new(src)
		var/obj/item/weapon/reagent_containers/glass/beaker/B2 = new(src)
		B1.reagents.add_reagent("condensedcapsaicin", 25)
		B1.reagents.add_reagent("potassium", 25)
		B2.reagents.add_reagent("phosphorus", 25)
		B2.reagents.add_reagent("sugar", 25)
		beakers += B1
		beakers += B2
		update_icon()
```

https://github.com/ParadiseSS13/Paradise/blob/master/code/game/objects/items/weapons/grenades/chem_grenade.dm#L468

**Comment by Probe1** [comment]
Mite be fun to add ultra capsicum instead and have that cause oxyloss, blindness, and other funstuff

**Comment by DeityLink** [comment]
Isn't condensed capsicum already teargas?

**Comment by Probe1** [comment]
yes but we do not have premade grenades and assuming chemists will at some point in the future break from all history and make grenades for security is wishful thinking.

**Comment by DeityLink** [comment]
Point taken

**Comment by Probe1** [comment]
```
/obj/item/weapon/grenade/chem_grenade/teargas
	name = "Teargas Grenade"
	desc = "Used for annoying everyone."
	path = 1
	stage = 2

/obj/item/weapon/grenade/chem_grenade/teargas/New()
	..()
	var/obj/item/weapon/reagent_containers/glass/beaker/B1 = new(src)
	var/obj/item/weapon/reagent_containers/glass/beaker/B2 = new(src)

	B1.reagents.add_reagent("condensedcapsaicin", 25)
	B1.reagents.add_reagent("potassium",25)
	B2.reagents.add_reagent("phosphorus", 25)
	B2.reagents.add_reagent("sugar", 25)
	

	detonator = new/obj/item/device/assembly_holder/timer_igniter(src)

	beakers += B1
	beakers += B2
	icon_state = initial(icon_state) +"_locked"	
```
thupid shit when

**Comment by 9600bauds** [comment]
when you map it

**Comment by Probe1** [comment]
Oh no I already coded it during last feature freeze as some practice before I tackled a bug.  It's easy to do, just replace a few ingredients in the flashbang, add it to a vend and a crate..

I've been playing DF lately but when I come back I'll bang this out.

**Comment by Probe1** [comment]
I could never make this balanced fwiw, it was a huge fucking stunner move against anyone without a gas mask.

**Comment by SysadminJeroen** [comment]
Maybe have some sort of stun integer? It it reaches a certain threshold
you'll be stunned?
It could be 0.5 seconds, gives those who are at the edge of the teargas
cloud the chance to run away but prevents players from running through it.

2016-04-08 15:05 GMT+02:00 Probe1 notifications@github.com:

**Comment by Probe1** [comment]
Yeah but I don't know how to code that and I'm not putting the time in to learn so why clog up the github with personal requests.

**Comment by WindowsErrors** [comment]
balance and equilibrium is being restored to this world as i type
