### ISSUE TITLE
Dead wizards can cast spells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6573]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
Somehow, a wizard who had died could stay in their body, reportedly "It still says I'm alive", and they could press their spells buttons while dead.

He could use Ethereal Jaunt, MM, but not disable tech, if that's anything. Magic Missile could only affect one tile around the teleporting cadaver.

http://i.imgur.com/xRs2nGH.png

[13:43:21] What PM to-Victorem/(Martin Pratt): Okay, is that spell casting while dead legit?
[13:43:30] Player PM from-Victorem/(Martin Pratt): I have no fucking clue
[13:43:31] What PM to-Victorem/(Martin Pratt): As in, are you actually doing it?
[13:43:35] Player PM from-Victorem/(Martin Pratt): it says I'M STILL ALIVE
[13:43:40] What PM to-Victorem/(Martin Pratt): AAAAAAAAH
[13:43:41] Player PM from-Victorem/(Martin Pratt): Like 100% health
[13:43:56] Player PM from-Victorem/(Martin Pratt): But yes i'm pressing the buttons

**Comment by SonixApache** [comment]
A quick summary of what happened that round;
Wizard had Jaunt, Magic Missile, EMP and Scrying Orb
Wizard was clowned by other wizard (me) and killed
Other wizard took his orb and used it
Wizard was then cloned 
Then, at some point, he became an invincible magical husk

**Comment by Kurfursten** [comment]
Scrying Orb plays with death in weird ways, might be relevant

**Comment by DeityLink** [comment]
We might have more of a clue on how to fix this issue if we knew exactly how he died.

**Comment by Skullyton** [comment]
@DeityLink lasers

**Comment by DeityLink** [comment]
Was he using a spell? I read that he had etheral jaunt.

**Comment by clusterfack** [comment]
Its hard to say whether the bug here is that it thinks he is still alive or whether the dead checks for standard wizard spells have been broken. Testing and confirming or denying the second possibility would be a good start.

**Comment by Rei1226** [comment]
I feel like I've seen this same bug before when a wizard mindswapped with a doctor while still in the cloner. I could have sworn I saw him yelling spells in dead chat while attacking people.

**Comment by clusterfack** [comment]
I can confirm it works with mindswap because the code for moving the spells over to the new body is just... just awful
