### ISSUE TITLE
Taxi: Just Cargo Things

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6580]
Taxi Cargo is neat, but it could use a little bit of work.
* No cargo bell
* No cargo window (people can just hookshot right in)
* No conveyor to get things off the cargo shuttle combines really poorly with the default 2-second double airlocks
* No MULEs at all (maybe intentional because they would only be useful on one station?)
* No coins for the QM

**Comment by PJB3005** [comment]
We should probably make the external airlocks at cargo NOT be fast.

**Comment by Zth--** [comment]
Mules with jetpack would be hilarious in taxi

**Comment by PJB3005** [comment]
Would be hell to map the end points for the MULEs though, taxi is cramped enough as is, mapping the extra disposal bins for belt hell was a PAIN.

**Comment by Kurfursten** [comment]
Is there a way to make MULE beacons presently? If not MULEs would be totally useless even if you bought them mid-shift as QM.

**Comment by PJB3005** [comment]
Nope, MULE beacons are regular bot beacons (beepsky and stuff use them too).

**Comment by Zth--** [comment]
I always thought they should be buildable
