### ISSUE TITLE
R&D levels are nonsense

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6584]
Advanced mass-spectrometers only offer biological technology 2 now. Previously, they offered more, and were key to advanced biotech research. I assume that this has something to do with the surgeon's switchtool.

High-precision laser scalpels are materials 1, biotech 1, despite requiring far greater levels to create. Defibrillators require biotech 4 to create, but only offer biotech 3 when deconstructed.

These are only a few examples.

**Comment by DeityLink** [comment]
>were key to advanced biotech research.
You've mispelled "Mech Syringe Guns"

**Comment by clusterfack** [comment]
I'm prett sure you mean know and radio enabled know deity

**Comment by clusterfack** [comment]
*I'm pretty sure you mean mmis and radio enabled mmis

**Comment by DeityLink** [comment]
Well you get my point @clusterfack which is that there still are multiple ways to progress through the biotech tree.

**Comment by FudgePucker** [comment]
Well its still nice to have more options. For example, mechanics don't have access to the exosuit fab if they need to do research. Scientists don't have plastic (aside from deconing plastic flaps) to make tier 3 parts to research.

**Comment by Hoshi-chan** [comment]
No Deity, you used to use advanced mass spectrometers to get to the point where you could produce MMIs through R&D. Now you can't, because their research level has been changed. Without robotics, you can't do basic R&D now.

Who changed this, and when?

**Comment by DeityLink** [comment]
No idea. But I agree R&D tech levels could use some balancing. (but that's not the kind of issue I'd like to work on during the feature freeze)

**Comment by Arthurdentist** [comment]
R&D needs a lot of work. There are a lot of items that wont give you any levels in anything, despite taking quite high levels to manufacture. I think a lot of components in particular fall foul of this.

**Comment by DeityLink** [comment]
@Arthurdentist This is partially intended, so you need specific items to get through tech level "floors". Otherwise you could max out R&D without leaving the lab in 5 minutes without needing minerals.

**Comment by Arthurdentist** [comment]
to some extent you can already 'almost but not entirely' max out R&D without leaving the science department. If you are a bad RD you can also loot telecomms to accomplish the same thing. Not that I would advocate looting telecomms.

**Comment by DeityLink** [comment]
meh, all tcomms brings you is some bluespace tech that you can also get by deconstructing some boards, but people always forget that they can also get tech levels by deconstructing machine circuitboards.

**Comment by Hoshi-chan** [comment]
Making R&D into a multi-departmental scavenger hunt is bullshit. It was never that way, and you shouldn't be trying to change it to be that way, at least not without an involved discussion in the thread and OOC where a majority of the players can voice their opinions on it.

R&D also shouldn't require a specific set of items to max out. There are plenty of items produced at different tech levels, why SHOULDN'T they all offer a way through to the next level. R&D isn't some challenging struggle to level up; the real job of R&D comes in actually capping the levels beyond the point where they're useful, and producing all of the various shit that all of the other departments are going to want.

**Comment by Arthurdentist** [comment]
I don't think anyone has suggested making R&D into a multi-departmental scavenger hunt.

**Comment by Hoshi-chan** [comment]
That seemed to be what the two of you were bringing up, that R&D shouldn't be able to be "maxed" within 5 minutes without leaving the department, and clearly someone tampered with the R&D levels provided by deconstruction in the code.

**Comment by Arthurdentist** [comment]
No, I just pointed out that you can max R&D quite easily already. I'd rather have more higher level items added instead of adding pointless busy work to the mix.

**Comment by Hoshi-chan** [comment]
Then my bad, I misinterpreted it.

**Comment by YakumoChen** [comment]
Hi. I wrote the Scientist's Research Lab Only Guide To Research.

Uh, Advanced Spectrometers ALWAYS had Bio 2. The main use they had for research was that they also had Electromag 4, which was mostly crucial for most of the important circuit boards, I believe. Actually the main items for higher Biotech levels are the MMIs. 
Advanced Specs are primarily useful for Biotech research because you can print it out for the Electromag research and you don't have to waste time making an Advanced Burn or Brute kit for Bio 2 as well.

**Comment by DeityLink** [comment]
What that settles it.
