### ISSUE TITLE
Recipe bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6591]
(WEB REPORT BY: merani REMOTE: :7777)
>4854216fdaf0077d6664c4ff1b7ab4f493450a80

>Angry Giga Puddi recipe bugged

>Followed recipe for Giga Puddi - Anger as outlined by the wiki (15 milk, 2 eggs, 1 chocolate bar, 5 salt). Expected Giga Puddi - Anger

> Recieved 1 Burned Mess and a pile of soybeans instead

>put 15 milk, 2 eggs, 1 chocolate bar, 5 salt in the microwave and turn it on

**Comment by clusterfack** [comment]
Dupe
