### ISSUE TITLE
Recipe bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6592]
(WEB REPORT BY: merani REMOTE: 158.69.55.2:7777)
>4854216fdaf0077d6664c4ff1b7ab4f493450a80

>Angry Giga Puddi recipe bugged

>Followed recipe for Giga Puddi - Anger as outlined by the wiki (15 milk, 2 eggs, 1 chocolate bar, 5 salt). Expected Giga Puddi - Anger

> Recieved 1 Burned Mess and a pile of soybeans instead

>put 15 milk, 2 eggs, 1 chocolate bar, 5 salt in the microwave and turn it on

**Comment by Zth--** [comment]
'''/datum/recipe/gigapuddi/anger
	reagents = list("milk" = 15, "sodiumchloride" = 5)'''

**Comment by Arthurdentist** [comment]
I cannot reproduce this bug. I followed the recipe you gave in the bug report and I created two angry giga puddi's just fine.

**Comment by Kurfursten** [comment]
The default pour amount for salt is 1 instead of 5 unlike every other condiment, he may have just used the wrong recipe by mistake.

**Comment by Arthurdentist** [comment]
It'd be good if someone else could test this just to confirm

**Comment by Kurfursten** [comment]
Tested, unable to reproduce

**Comment by PJB3005** [comment]
Unable to reproduce
