### ISSUE TITLE
Energy Artifact

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6596]
(WEB REPORT BY: sageoflight REMOTE: 158.69.55.2:7777)
If you're a cyborg and there's an energy boosting artifact on the station...

SYSTEM ALERT: Energy boost detected!
SYSTEM ALERT: Energy boost detected!
SYSTEM ALERT: Energy boost detected!
SYSTEM ALERT: Energy boost detected!
SYSTEM ALERT: Energy boost detected!
SYSTEM ALERT: Energy boost detected!
SYSTEM ALERT: Energy boost detected!
SYSTEM ALERT: Energy boost detected!

Ya dig?

**Comment by clusterfack** [comment]
Yeah not to mention that they lag like hell

**Comment by AutismSpider** [comment]
Happens with both energy boost and drain

Cyborg/mommi chat will be nothing but system alert
