### ISSUE TITLE
Playsound runtimes

### ISSUE THREAD

**Issue by dylanstrategie** [d3athrow/vgstation13#6600]
I added this runtime hook because a bunch of sounds aren't playing properly. Usually it's because the linked atom is incorrect, so a bit of reverse engineering will need to be done for this one

```
## ERROR: Warning :  trying to play sound 'sound/effects/bubbles.ogg', but turf could not be found.
## ERROR: Warning :  trying to play sound 'sound/weapons/spur_hitwall.ogg', but turf could not be found.
## ERROR: Warning :  trying to play sound 'sound/weapons/spur_hitmob.ogg', but turf could not be found.
## ERROR: Warning :  trying to play sound 'sound/effects/glass_step.ogg', but turf could not be found.
## ERROR: Warning :  trying to play sound 'sound/machines/click.ogg', but turf could not be found.
```

**Comment by clusterfack** [comment]
That's why I told you to have it call a stack trace dumbass

**Comment by PJB3005** [comment]
Bug report / 10.

Seriously, people that throw an error without info like this into `world.log` deserve a fucking slap, this helps nobody and only spams the logs.

**Comment by PJB3005** [comment]
Also:

`## ERROR: Warning :`

You really have brain damage, don't you dylan?

**Comment by 9600bauds** [comment]
Happens from explosions happening from pills and such

**Comment by ghost** [comment]
cluster added his fancy trace, and yeah this still happens a lot, needs a new thread
