### ISSUE TITLE
Let derelict MoMMIs pick their names again

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#6601]
Why was this taken away from them? I don't get it.

Also, to clarify, the namepick verb does nothing.

**Comment by N3X15** [comment]
This was by design, since they were using names that were using in-round information.  It also lets me give them russian-ish names in the future.

**Comment by Hoshi-chan** [comment]
Why take that away from all MoMMIs? Why not just ban the shitters violating server rules?

**Comment by PJB3005** [comment]
Personally I don't think it's a good idea either.
