### ISSUE TITLE
Cloning when ghosted

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6606]
(WEB REPORT BY: tamassran REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
588c164d2c90c323deb3a7eb9df1b3e655beeddc

>General description of the issue
BWOINKED for cloner when I ghosted because like fuck am I gonna play a rev round

>What you expected to happen
Not get bwoinked when I was ghosted in a cloner and ineligable to resurrect/clone

>What actually happened
Got bwoinked yo

>Steps to reproduce if possible
Ghost -> Cloner -> Bwoink

**Comment by 9600bauds** [comment]
What?
Do you mean you ghosted out of your living body?

**Comment by Probe1** [comment]
I

Hey fuck you Mr. 26 seconds ago new PR.

I logged into the serb and reproduced it successfully.
