### ISSUE TITLE
SMES Charging

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6608]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
588c164d2c90c323deb3a7eb9df1b3e655beeddc 

>General description of the issue
SMES do not charge if multiple engines are set up. Reproduce-ability of the issue is sketchy

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Kurfursten** [comment]
Couldn't reproduce, need more details

**Comment by PJB3005** [comment]
This is certainly either due to #6475 and / or the creator not realising (and I don't blame them) that SMES need 12-24 seconds of power before they start charging.
