### ISSUE TITLE
Camera upgrade

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6611]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
2148960ff95e0433e0312997bc750d3da263a152 

>General description of the issue
Upgrading cameras with carrots makes the cameras be permanently listed under station alerts as MOMMI.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by 9600bauds** [comment]
I believe this is actually caused by #4749
