### ISSUE TITLE
Once you lock a tator tot PDA uplink you cannot open it again

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#6612]
Had a player just now roll tator, unlock his pda, close it without buying anything, and then tried opening it again with no luck.

Tried it myself and it wouldnt work either. Shit is BROKE, son.

**Comment by Faptastic** [comment]
I tested this just now locally and it seems to let me lock and re-enter the menu just fine?
Perhaps it only applies to naturally rolled tators?

**Comment by mrpain666** [comment]
The guy it happened to was a round start tator.

**Comment by ghost** [comment]
Not an issue, he was rolled as a traitor twice, which is the issue, and we have tickets open for that

**Comment by clusterfack** [comment]
Yes this is a part of a larger issue that is already reported
