### ISSUE TITLE
Should we fix the double agent getting themself as a target bug?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6613]
It's been left in because it's funny.  Should we fix it?  

As a side idea, should we add a heavyweight operative that gets 20 telecrystals in exchange for being the only syndicate on the station?  That is how double agents getting themselves as a target plays out now.

**Comment by Hoshi-chan** [comment]
You should remove double agents as a mode, and simply make it a type of objective during regular autotraitor and traitor+ling rounds.

You can't polish a turd.

**Comment by clusterfack** [comment]
It's not been left in because it's funny, but because people are simply too incompetent to fix it.

**Comment by FudgePucker** [comment]
@clusterfack how hard would it even be to fix it?
Wouldn't it be easy to add to the pick list an exception for the player?

**Comment by Probe1** [comment]
its more like no one reported it or made a big enough fuss - i'm pretty sure this is the first issue on it.

**Comment by Probe1** [comment]
After some investigation, I'm pretty sure it's linked to https://github.com/d3athrow/vgstation13/issues/6612 and needs fixed.

**Comment by Intigracy** [comment]
fixing this is literally as easy as adding a "- src" somewhere in the code.
