### ISSUE TITLE
People not dying after losing their chest post-necrosis

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6616]
(WEB REPORT BY: kammerjunk REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
2148960ff95e0433e0312997bc750d3da263a152

>General description of the issue
A patient lost his chest after a Necrosis virus. After giving him his missing *limbs* back (left leg, right foot, left foot), I woke him up and he was alive and unharmed.

>What you expected to happen
I expected the patient to die and his limbs to explode off the body.

>What actually happened
The patient turned out fine. I don't know if he could have put his suit back on after taking it off.

>Steps to reproduce if possible
Get Necrosis and don't die? I'm not sure.

**Comment by dylanstrategie** [comment]
Patients shouldn't be able to lose their chests, it fucks with the game big time because "chest removal" cannot be handled by the game currently

If someone wants to add proper chest removal, you go ahead after the freeze, but I'll just remove the ability for the chest to gib off in this case
