### ISSUE TITLE
Feature Request: Forced to put an arrest reason whenever you set someone to arrest

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6621]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2148960ff95e0433e0312997bc750d3da263a152 
> Would be nice to have this. This way people can stop asking why someone's being arrested and getting no response. Printing out a report after being set to arrest would be good too for even more clarity.

**Comment by SonixApache** [comment]
Just tell people to make a habit of adding a comment when they arrest people. Easily done by shift-clicking, same way as you set someone to arrest.

**Comment by Probe1** [comment]
lmao no

but I do want WHO set someone to arrest logged.

**Comment by clusterfack** [comment]
*Making a feature request using the BUG REPORTER*

That's too far, man so tempted to close this

**Comment by FudgePucker** [comment]
I don't think that this is a good idea.

One of my fav tactics as a traitor is to snag a sec HUD then in the heat of the moment set people to arrest before being killed or arrested.

Nothing is better than almost getting lasered to death by the HoS then seeing beepsky stun and handcuff him.

**Comment by Arthurdentist** [comment]
I feel like this'd be a bit obtuse if you are in the middle of chasing someone down.

**Comment by Killette2** [comment]
I also don't like the idea for the reason Fudge said. Snagging a HUD and making everyone arrest is great.

**Comment by Rei1226** [comment]
Sorry, I'll clarify. I meant this as a means to when you're setting someone to arrest via the security records console, not the HUD. Probe's idea of it automatically saying who set someone to arrest in the records or something when they do it is also a great idea.

Also I don't see why making a feature request using the in-game bug reporter function is an issue if the title is literally Feature Request.

**Comment by Probe1** [comment]
I have absolutely no problem with a dialogue box popping up when you use the security console and asking you to input the crime and whether it's major or minor.  

That would be a QoL improvement straight up.

**Comment by TNepr** [comment]
What if there was an automatic broadcast for security when somebody gets set to arrest status?

**Comment by FudgePucker** [comment]
I think having a dialog box show up when setting someone to arrest would be great. Have it come up with minor/major/cancel and then have a text box for putting in the reason.
