### ISSUE TITLE
You can handcuff positronic brains

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6628]
Well.

I really don't know what else to say.  They're cubes.  You can handcuff them.  There is no corresponding sprite for it and they have no mob inventory for players to open so the cuffs are lost.  Works with and without a player occupying it.

![image](https://cloud.githubusercontent.com/assets/8550416/11200910/88230b60-8ca7-11e5-94d5-54675ccaaadf.png)

**Comment by Zth--** [comment]
Hilarious

**Comment by clusterfack** [comment]
I'm starting to think they shouldn't have attack() in their attackby

**Comment by AutismSpider** [comment]
Happens with mmis to

**Comment by Midaychi** [comment]
Make it a feature, complete with tiny handcuffs. Sometimes security needs to detain those dangerous brains.

**Comment by PJB3005** [comment]
Something tells me MMIs/Posibrains have the `attackby()` call the `attackby()` on the brainmob.

**Comment by PJB3005** [comment]
[Candidato numero 1:](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/carbon/brain/MMI.dm#L153)
``` DM
/obj/item/device/mmi/attackby(var/obj/item/O as obj, var/mob/user as mob)
```

**Comment by PJB3005** [comment]
whoops

**Comment by Probe1** [comment]
b u l l y

**Comment by gbasood** [comment]
handcuffs instantly drop to floor when doing this so it actually does nothing
