### ISSUE TITLE
Request: Covert pill upgrade for traitor chemists

### ISSUE THREAD

**Issue by Midaychi** [d3athrow/vgstation13#6632]
It's a little circuit board you get from an up-link, unscrew a chem master stuff it in and close the chem master back up.

From then on, any pill created in that dispenser has a hidden 50 unit reservoir, which you can only put chemicals in by injecting the pill with a syringe. The pill is no-react, and the only way to tell is to either watch a chemist do it or scan the pill with a reagent scanner.

Ingesting the pill will mix the chemicals after the life digestion delay.

**Comment by Ephx1** [comment]
You do realize that Chemistry dispensers are in one of the highest traffic areas, right?

**Comment by Kurfursten** [comment]
>Hm, this dispenser is really low on charge
>The only things that cause that are being disassembled or making a bunch of chloral (at 1/5 output it has the lowest chemical efficiency of anything short of zombie powder), both super criminal

Valids. Also this doesn't add much to chemist play (since reagents are hidden anyway) besides making one-pill bombs. And you could already do that in a stealthier way with the hug explosive chemical.

That being said, @shadowmech88 has been itching for the chemical mask/tank to be a chemist traitor set, which is something I could get behind more, too.

**Comment by FudgePucker** [comment]
@Kurfursten
>chem master

When did the chem master have a charge :^)

PS my phone auto corrects chem into Chen.  It knows too much, I have to burn it before it becomes self awar- honk honk

**Comment by Ephx1** [comment]
@FudgePucker 
I think Midaychi mixed up the two as they reference both as the same thing
> close the chem master back up.
and then
> any pill created in that dispenser

**Comment by Kurfursten** [comment]
Oh, true, I was thinking of the dispenser.

Point still stands that I'm not sure it brings much to the role.

**Comment by 9600bauds** [comment]
Was kind of addressed by giving NOREACT to time release pills, is this still an issue?

**Comment by Midaychi** [comment]
Time release no react pills are literally this suggestion, so no.

**Comment by 9600bauds** [comment]
Another satisfied customer
