### ISSUE TITLE
/obj/machinery/atmospherics/miner/air spawns CO2 instead of air.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6640]
one job.

**Comment by Zth--** [comment]
Wait, there's an air miner?

**Comment by PJB3005** [comment]
@Zth-- adminbus central

**Comment by FudgePucker** [comment]
Oh wow, this is pretty fucking funny.
Is it because the parent of miners is the CO2 miner?

**Comment by FudgePucker** [comment]
Nope, someone just put CO2 instead of O2+N2.

How do you even fuck up this bad?

**Comment by Probe1** [comment]
¯\_(ツ)_/¯

Imagine my surprise.

**Comment by FudgePucker** [comment]
I might be stupid and can't find it, but is there an 'air' air type?
Maybe someone just went 'eh fuck it' and made it CO2 because he didn't know or want to have to make it have the right balance of O2 and N2.
