### ISSUE TITLE
You can be cloned while you are alive..

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6641]
Player backed up his DNA with the cloner as Isaac Clark.  He was also a changeling and became a new player (the captain and the HoP, two separate DNA entities).  Someone walked to the cloner and hit clone on his back up and what do you know, the player was yanked out of his current body and cloned.

![beard_town_3_2015-11-17_19-57-07](https://cloud.githubusercontent.com/assets/8550416/11229644/860b8348-8d65-11e5-94ad-cbb7739a03e5.png)

**Comment by 9600bauds** [comment]
Haha shit, this is just rich. I only touched how cloning records are made for already dead people, this is a bug with the cloner itself. I wonder how old this bug is, and noone found it simply because noone seems to scan themselves while alive for some reason.

**Comment by d3athrow** [comment]
yeah backups are wonky but was reported 2 years ago by riri
