### ISSUE TITLE
Sleeper upgrade requires 1 scanning module

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6642]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)
>Revision (Should be above if you're viewing this from ingame!)
2c376492abf6663ec0bc3fc0ccbf851bbcf5d744 

>General description of the issue
When you insert the circuit board to build a sleeper it says it requires two scanning modules but it is complete when only one is inserted.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Kurfursten** [comment]
This is actually a typo in the description, it is supposed to be 1 scanning module but instead says 2
