### ISSUE TITLE
This happened, laser shots didnt go away

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6644]
https://gyazo.com/84dd23cab03b291c92292d69f09e381e

**Comment by DeityLink** [comment]
What fired those lasers? what did they hit?

**Comment by AlphaBuffalo** [comment]
maruders shot them, and I dont know what they hit, and it happened on pomf server

**Comment by Rei1226** [comment]
oh yeah, this has happened for a long, long while. it's only with pulse rifle beams i believe, or marauder shots.

**Comment by unid15** [comment]
That bug happened because projectiles got del()'d when they hit a turret

**Comment by PJB3005** [comment]
As @unid15 pointed out, the projectile got `del()`.

[It happens in the following section of code:](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/mecha/equipment/weapons/weapons.dm#L84)

``` DM
/obj/item/projectile/beam/pulse/heavy/Bump(atom/A) //this is just awful
	A.bullet_act(src, def_zone)
	src.life -= 10
	if(ismob(A))
		var/mob/M = A
		add_logs(firer, M, "shot", object="[src]")
	if(life <= 0)
		del(src)
```

I agree with you comment.

**Comment by d3athrow** [comment]
No runtimes causing it

**Comment by DeityLink** [comment]
Oh god, now I get it. Basically Marauder pulse rifles have their own awful implementation of a "penetration system". I thought something was wrong when I noticed that they had their own Bump(), thanks @PJB3005

**Comment by DeityLink** [comment]
That won't fix it @d3athrow I'm working on it right now.

**Comment by d3athrow** [comment]
@DeityLink works fine for me, http://ss13.pomf.se/uploads/2015-11-19_17-28-49.webm

**Comment by DeityLink** [comment]
Just read the code in https://github.com/d3athrow/vgstation13/issues/6644#issuecomment-158154190 again. Read it carefully. Isn't anything ticking you off?

**Comment by d3athrow** [comment]
nope. tested the bug and the projectile overlays stuck, did the fix and now they don't

**Comment by DeityLink** [comment]
saying it again, here I'm implying that the laser shots not going away was but a symptom of a bigger issue. namely:

* these projectiles have their own snowflake Bump() proc that does literally nothing, to the point it was even commented by its creator to be awful.

**Comment by d3athrow** [comment]
yup its a snowflake proc alright but that isn't what the issue report was about.

**Comment by PJB3005** [comment]
@d3athrow that's literally the definition of band-aid.

**Comment by d3athrow** [comment]
shrug
