### ISSUE TITLE
Unable to Move after being grabbed by Kudzu

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6662]
(WEB REPORT BY: kinggrimlock REMOTE: 158.69.55.2:7777)
>Revision 3b156061082903d0f6dda5e4593d7f80745e7e5d 

>Can't move after being grabbed by Kudzu

>What you expected to happen
Being able to move after Kudzu was gone

>What actually happened
Couldn't move, had to be grabbed to move away

>Steps to reproduce if possible
Have Kudzu vines tighten around you
Try to move
can't

**Comment by Probe1** [comment]
Mobs are being set to anchored and not unset *ever*.

**Comment by PJB3005** [comment]
Here's how you fix this:

Move kudzu to atom locking.

**Comment by unid15** [comment]
I'm looking at it and it looks like they're already using atom locking

**Comment by clusterfack** [comment]
Yes they are they just aren't using it properly it seems, someone fixed the runtime that was previously stopping them from locking anything at all

**Comment by Probe1** [comment]
They need a check to see if the player is still in vines.  The vines were being cleared so the player couldn't resist out anymore, and they were stuck anchored without a way out.

**Comment by PJB3005** [comment]
Atoms should be unlocked on `qdel()` though...
