### ISSUE TITLE
Plasma igniting in the air at less than a visible concentration

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#6667]
Revision: a42bcc700bef4fd58e11024b4a7610809b166054

At 2015.10.07, Pomf updated "Fix plasma from igniting before it's reached MOLES_PLASMA_VISIBLE concentration." After some "testing," it does not appear to be the case.
![plasma igniting before visible](https://cloud.githubusercontent.com/assets/5942183/11290254/822a4792-8f35-11e5-9014-4f64f08a9412.png)
I was a little bit late to grab a screenshot, but I managed to catch a few unlit tiles. The plasma was not at a visible concentration.

**Comment by PJB3005** [comment]
I can confirm that this happens.

Also pomf broke welding fuel fires with that shitty fix.

**Comment by Zth--** [comment]
I don't know why but this makes me laugh. Guys you're ruining my mind

**Comment by PJB3005** [comment]
Pomfcode<sup>tm</sup>

**Comment by clusterfack** [comment]
We undid that change to fix welder fuels, could be readded by modifying the .toxins check to check for moles_visible_plasma or whatever
