### ISSUE TITLE
Powergrid is broken at round start

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6668]
(WEB REPORT BY: manaony REMOTE: 158.69.55.2:7777)
You fucker need to learn to map really

**Comment by clusterfack** [comment]
WOW GREAT JOB WRITING WHICH MAP ITS ON

**Comment by PJB3005** [comment]
Manaony confirmed in IRC that this is about box.

**Comment by FudgePucker** [comment]
11/10
Best issue ever
So in depth and descriptive

**Comment by Probe1** [comment]
@Manaony please come back and describe it in more detail.
