### ISSUE TITLE
Admin-teleporting pAIs break them

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#6669]
Revision: a42bcc700bef4fd58e11024b4a7610809b166054 

>General description of the issue

I had become the pAI for the RD, Bob Johnson. After a while, he had to go braindead. I prayed to be sent to a table in medbay so I wouldn't have to pAI suicide (because that feels dirty). After being obliged (thanks, goodmin), the entire pAI code just sort of unravelled and I became a broken, human-sized pAI on a medbay table.

>What you expected to happen

Happy medbay funtimes after a successful God-supported teleport

>What actually happened

After being teleported, I got split into two: The pAI object(?) still in the RD's pocket and the pAI mob(?) on the medbay counter. The pAI mob was called ZX Spectrum after my pAI name (as opposed to normal pAIs, which are just called 'personal AI device'.
My view was still in at the RD. I fixed this via Cancel-Camera-View.
I could not be picked up by people and attempting to move to the same tile as I was on resulted in them pushing me.
By dragging the sprite of the ZX Spectrum one onto themselves and clicking on one of the equipment button ("Left hand," "Right hand," so on), people were able to access my interface (download new software, use existing software, et cetera).
I could also now see things pAIs normally aren't able to - combat text, emotes, that sort of thing.

>Steps to reproduce if possible

Might possibly need two people to test it - I don't know how teleporting as admin with the fancy "bwoomf" sound works. One in a pAI body, one to teleport the pAI, then teleport the AI. Can probably be tested on the live server with a willing ghost.

**Comment by PJB3005** [comment]
Sounds like an admin fuckup, they teleported the pAI mob instead of the item that holds it.

**Comment by clusterfack** [comment]
That's because they used get mob which teleports the incorrect thing, same thing with any mob that exists within a container. Needs a mob/proc that returns the container for such mobs so that our teleport procs work correctly.
