### ISSUE TITLE
Always Random Body in lobby doesn't work

### ISSUE THREAD

**Issue by TermedClepe** [d3athrow/vgstation13#6670]
Clicking Always Random Body in character creation doesn't change anything, it stays at "No".

**Comment by Probe1** [comment]
dup https://github.com/d3athrow/vgstation13/issues/4974
sadly.

**Comment by clusterfack** [comment]
This actually told me something the other report didn't, I didn't realize the text option wasn't changing just that it wasn't working

**Comment by Probe1** [comment]
Coulda found that out yourself if you tested it at any time in the last 5 months desu senpai baka

**Comment by clusterfack** [comment]
I only play silicon so I don't setup my special snowflake body anyway
