### ISSUE TITLE
Monkeyman appearance

### ISSUE THREAD

**Issue by TNepr** [d3athrow/vgstation13#6677]
Monkeys that are turned into humans always come out with the exact same hair and beard. Female monkeymen also have a beard. This makes monkeymen really easy to spot apart from regular humans just by their appearance. Monkey that are turned into humans should all get randomized hairstyles of their own.
![image](https://cloud.githubusercontent.com/assets/5472923/11317227/883f974e-8ff4-11e5-8eea-d8ae3af67788.png)

**Comment by 9600bauds** [comment]
Confirmed, what the fuck

**Comment by gbasood** [comment]
Do they all have the same UI?

**Comment by 9600bauds** [comment]
Not sure but they all have the same hairstyle and moustache. Hair color varied

**Comment by gbasood** [comment]
![](http://i.imgur.com/fxPmqGs.png)
This is the UIs of two manned monkeys. I don't think that's the problem but hey

**Comment by Killette2** [comment]
Got this weird shit linked to me, still exist
