### ISSUE TITLE
DYLAN TOUCHED MY LIBRARY.

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#6678]
#6525
THIS IS THE ISSUE.

Why the fuck would you make Bookshelves be disassembled by a fucking crowbar, do you just take things apart by smashing them in France or some shit? Why not just change the wiki article, wrench made sense, this is just silly.

**Comment by PJB3005** [comment]
Dylan is a fucking retard, we all know that.

**Comment by 9600bauds** [comment]
that last comment is a little uncalled for

**Comment by Kurfursten** [comment]
Crowbar makes sense if they're nailed together.

My question is... why do you think bookcases were deconstructed with a wrench? They were deconstructed with a **screwdriver** before.

**Comment by FudgePucker** [comment]
So are book cases made with nails, screws, or bolts?

There are no hammers in space so its bolts or screws.

FEATURE REQUEST, hammers, I want to throw hammers at peoples faces while screaming, 'STOP, hammer time'

**Comment by Kurfursten** [comment]
Hammers would be interesting if construction was ever expanded to be more than "click an item on the list". Short of that though, it's not like you hammer girders or delicate electronics.

**Comment by FudgePucker** [comment]
Some dcon things could use a hammer, for one example, floor plating.

The only way to remove floor plating is to have a RCD or drill. A possible way to remove them might be to use a hammer to dislodge it (use a hammer to realign it to undo), then weld the supports off.

This would let you make a cold loop in station with out needing an RCD or drill.

**Comment by PJB3005** [comment]
Hammers are dumb, we have more than enough tools in the code already.

**Comment by Kurfursten** [comment]
Agreed, I really don't see a **need** for hammers, unless you just want a sledge as a weapon.

Toolbelts are getting crowded again.

**Comment by FudgePucker** [comment]
Just make it limited to a few in engineering, you don't need to carry around a socket wrench, but it is handy to have.

**Comment by NigglyWiggly** [comment]
Screwdriver was the old way, it made sense because you can just assume the shelves are screwed together. Changing that to a wrench didn't exactly make too much sense, but at least it prevented you from somehow accidentally unscrewing your floor tiles if you weren't paying attention.
Changing it to a crowbar is just silly, I'd honestly prefer if it was just back to the screwdriver because that way it's more in line with every other thing in the game, but the change from screwdriver to wrench didn't bother me nearly as much as this one.

**Comment by Kurfursten** [comment]
It was screwdriver as of the Dylan PR (you can see the change in his file)

**Comment by NigglyWiggly** [comment]
Wait what
OH
Oh god I had the order mixed up, that makes sense.

**Comment by Zth--** [comment]
Yeah I changed the wrench to screwdriver on gitlab because it had more sense(along some bugfixes) but I completely forgot about the wiki

**Comment by 9600bauds** [comment]
I think it's a matter of keeping things consistent, rather than what makes more sense for every individual case.
Most machines and furniture are deconstructed with a wrench, thus, a player who hasn't deconstructed a bookcase before will likely try a wrench first.

**Comment by clusterfack** [comment]
![](http://i.kinja-img.com/gawker-media/image/upload/aoz8kgx8pzknypz7z38n.jpg)

**Comment by Kurfursten** [comment]
While we're talking about deconstruction, am I the only one who goes nuts over the fact that deconstructing a shower is 2 steps now instead of 1? Twice the hassle when the clown decides it's time for water sports.

**Comment by Zth--** [comment]
>Most machines and furniture are deconstructed with a wrench, thus, a player who hasn't deconstructed a bookcase before will likely try a wrench first.
This is not true, I added the feature to unanchor the bookshelve with a wrench, so I had to change the wrench with a screwdriver for decon.

**Comment by 9600bauds** [comment]
Meant for furniture moreso than machinery, but heck you're right. Maybe the player will try opening the bookcase's panel or something.
I think we can rule out crowbar at the very least.

**Comment by dylanstrategie** [comment]
Wrench was used for unanchoring

Screwdriver felt weird since you were pulling the entire bookcase apart in one action

Crowbar somewhat makes sense since it's SPESS and you can just rip the bookcase shelves apart with a crowbar

**Comment by NigglyWiggly** [comment]
But that's dumb.
What kind of heathen just rips a bookshelf apart and has all the books pop out

**Comment by dylanstrategie** [comment]
Your average crewman ?

**Comment by NigglyWiggly** [comment]
That's dumb, though.
