### ISSUE TITLE
Borer Eye

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6696]
(WEB REPORT BY: gooza3 REMOTE: 158.69.55.2:7777)
>Borer fixed my eyes and my GUI got fucked up

>Borer would make my eyes better

>My GUI became shit and close up

>Have a borer fix your eyes

**Comment by clusterfack** [comment]
This is what passes for a bug report these days

**Comment by PJB3005** [comment]
Is this related to far sight?

**Comment by clusterfack** [comment]
Probably? I mean we know that's broken. If it isn't far sight I have literally zero idea what the report is about.

**Comment by PJB3005** [comment]
I know that somebody in ahelp had an issue with farsight:

If you're on a screen size that isn't stretch, you'll have the total size of the screen increase, which'll end up being invisible.

And coincidentally, 64x64 fits almost perfectly on a 1080p display.

**Comment by clusterfack** [comment]
64x64 actually fits literally perfectly with 1 more tile than the normal view range on a 1080p display with even a bit of extra space if you've auto-hid your taskbar (or whatever you have on linux)

**Comment by PJB3005** [comment]
Yeah that's possible.

PS: on Linux Mint atleast it's called "the panel", because it's more than a task bar.

**Comment by Intigracy** [comment]
I don't even know what this issue is, close it?

Also 64x64 fits on my 1920x1080 display except cuts one pixel off of the top, but I haven't disabled my taskbar so.

**Comment by Shadowmech88** [comment]
This issue is poorly-explained and nearly a year old. I think it can be closed.
