### ISSUE TITLE
emagged hop id computer wont authorize

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6701]
(WEB REPORT BY: 420africanamerican REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> dd634d27ebb33f64765287964d34c321bd024891
> General description of the issue
> when emagged the id computer doesnt let you change with any id
> 
> What you expected to happen
> emag
> let me use any id
> 
> What actually happened
> emag
> nothing
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
Is this actually a bug?

I'm unsure if emagging an ID console should actually allow you to get all access.

**Comment by Ephx1** [comment]
Cryptographic Sequencer, your one stop shop to all things Traitorous

**Comment by FudgePucker** [comment]
EMags shouldn't let you hack ID consoles.

There is one near arrivals, so all you would have to do is emag from maint, drag it into maint, hack it, get all access.

Whats next, emag not being able to give you a blowjob?

**Comment by PJB3005** [comment]
Unable to find any reference to emagging in [`card.dm`](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/machinery/computer/card.dm), definetly not a bug.

**Comment by Probe1** [comment]
Old discussion.
