### ISSUE TITLE
Cannot upgrade xenoarch computers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6717]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> dd634d27ebb33f64765287964d34c321bd024891 
> 
> General description of the issue
> No way to open hatch of xenoarch computers with screwdriver hence no method for upgrading.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
Er, which xenoarch computers?

Xenoarch has no explicit computers, except maybe the analyzer or the anomaly battery machine.
