### ISSUE TITLE
Taxy station system alerts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6718]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> dd634d27ebb33f64765287964d34c321bd024891 
> 
> General description of the issue
> Constant large energy drain system alerts.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
Not related to taxi: a scientist dug up an artifact with the energy drain effect.
