### ISSUE TITLE
You know I'm not sure if this deserves a descriptive name because it would detract from the description

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6719]
![image](https://cloud.githubusercontent.com/assets/9827785/11325059/ca3a6c00-9111-11e5-8948-08263efaaf2f.png)

**Comment by 9600bauds** [comment]
A+ titling and formatting

**Comment by FudgePucker** [comment]
Its a feature not an oversight.

**Comment by Exxion** [comment]
Unfortunately, the [IT'S A FEATUREEEEEEEEEEEEEE] or however it went tag was replaced with [Oversight]
I think
It's not there anymore at least

**Comment by PJB3005** [comment]
It was replaced with [Performance].

Ask @N3X15

**Comment by Exxion** [comment]
Ah
The colors are so close
