### ISSUE TITLE
(stupid) feature request: no glubs mode (Also known as no glubs, assistant only, final destination)

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#6720]
A option on the fun pannel to replace yellow insulated gloves everywhere with insulated wire cutters, meaning you can still fix power cables.

Watch as the entire station crumbles to pieces as soon as something as simple as yellow glubs are removed.

**Comment by FudgePucker** [comment]
Also add a warning to not push this button if the round is malf

**Comment by 9600bauds** [comment]
1- acquire insulatedwirecutters
2- find the wires using the insulatedwirecutters
3- utilize your newfound knowledge to hack with a multitool just like regular

**Comment by FudgePucker** [comment]
Okay, how about it being a all new gamemode in itself and everybody is an assistant, they get a pin pointer to the captains spare id, the objective is to leave on the emergency shuttle with the spare in your possession, and there is a group of antags dressed up in safari gear who have to hunt down and bag as many assistants as they can.

Call it, shitter safari and replace it with extended.
