### ISSUE TITLE
Unusual layout

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6727]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)
Revision: 11b668b83e83e01ec4abbd306fc9521034576d5e 

> General description of the issue
> Text overlapping the health indicator
> 
> What you expected to happen
> Normal game experience
> 
> What actually happened
> See above. It appears to be the plasma counter used by xenomorphs.
> 
> Steps to reproduce if possible
> n/a/, present when I began the game.

**Comment by Wizardcrying** [comment]
D E S C R I P T I V E

**Comment by PJB3005** [comment]
I actually remember something like this happening to me once, I think it was when I was de-vamped, the counter for blood and such stayed.

**Comment by DamianX** [comment]
I think removing pooling fixed this.
