### ISSUE TITLE
[Box] BORER CHAMBER SUCKS ASS

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6728]
If I'm not mistaken, the other stations all have six slime chambers plus one dedicated isolation chamber for xenos, borers, etc. Box has five standard slime chambers and one former slime chamber that was lazily modified to accommodate the borer. It's the same except it has plasma glass, a pipe to let in plasma, and a vent that can be opened to space (which was present before it was modified). So what's the problem, you ask? It has a woefully inadequate airlock and, more importantly, it has a scrubber and air alarm. These default to standard atmospheric parameters. So if you fill the chamber with plasma without first getting someone with air alarm access to change it, the plasma is siphoned out in a few minutes.

**Comment by Exxion** [comment]
Also, I think the other codebases' Boxstations have these dedicated containment cells (not specifically for borers, but better for it than what we have), but it was removed in our version to make room for something else.

**Comment by FudgePucker** [comment]
Isn't there a xenobio air alarm control computer in xenobio?

Also telescience has a good set up.

**Comment by Exxion** [comment]
There... might be. I forget.

If memory serves, our Telescience containment room is almost identical to the big containment room that used to be in Xenobiology.

**Comment by Ephx1** [comment]
![labeled](https://cloud.githubusercontent.com/assets/6224074/11339708/d72be51c-91c8-11e5-9700-26b22d7b77c1.png)
honk

**Comment by FudgePucker** [comment]
Oh yea its right fucking there.

**Comment by Exxion** [comment]
Still, Box has one slime room less than the other stations because the borer chamber now takes up one of those rooms.

**Comment by Probe1** [comment]
Do you have any suggestions?  Xenobios pretty tight and well made as is, I didn't realize it was a problem.  It'd help to hear some more specific ideas on how to improve it.

**Comment by Exxion** [comment]
South of Xenobio is just space, so it could easily be expanded that way if necessary.
Meta's Xenobio is great. Modeling Box's off that except with the seventh cell at the bottom rather than the top seems like it could work.

EDIT: I apparently remembered Meta's incorrectly and it already is at the bottom.

**Comment by Probe1** [comment]
quick slap up of the other maps in one place for consideration.  I'm still not sure how to re-do xenobio cause I think its really good as-is.

![vgstation13_ mapstgstation dmm _-_dream_maker_2015-12-01_21-00-24](https://cloud.githubusercontent.com/assets/8550416/11520182/030754e4-986f-11e5-81e6-7409f4fa2bc0.png)

**Comment by Ephx1** [comment]
While you're looking at those can you check if the xenobio meta atmos computer links up to the injector in the pen? I can't recall if it's linked properly.

**Comment by PJB3005** [comment]
@Ephx1 isn't that the one that allows you to control air alarms, because if so, no way to make it control the injector.

**Comment by FudgePucker** [comment]
Oh shit why would they have an injector instead of a vent?

**Comment by Ephx1** [comment]
@PJB3005 Then that specifically needs to be reworked, otherwise the entire pen is useless for putting gasses in.

**Comment by FudgePucker** [comment]
Yo check out my feature request that would help fix this with out major mapping, (#6837).
Incase you would rather make a giant confusing new atmos machine than deal with having to deal with the hair pulling head ache of getting a mapping change merged.

**Comment by sonime** [comment]
I think just changing the air alarm to not giving a fucking atoms alert when there's plasma in pen 6 would help.

**Comment by sonime** [comment]
And by atoms I mean atmos

**Comment by FudgePucker** [comment]
There is the air alarm computer right there for you to do it your self.

**Comment by sonime** [comment]
It triggers my atoms autism to see it as an alert every time I look at the alarms.

MUST BE ALARM FREE **[angry spider noises]**

**Comment by FudgePucker** [comment]
Eh I guess someone can edit it then. Your on your phone and it autocorrects right?

**Comment by sonime** [comment]
Yep. Damn thing pisses me off.

**Comment by SysadminJeroen** [comment]
You know, you can disable the atmos alerts at the air alarm computer in
Xenobio.

2015-12-26 18:57 GMT+01:00 sonime notifications@github.com:
