### ISSUE TITLE
Cortical Borers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6729]
(WEB REPORT BY: redun REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> When you enter a pipe or a host from an area of dangerous atmospherics, such as fire, you will continue to take damage from said source even if you are in a safe host/pipe and out of the area.
> 
> What you expected to happen
> Not to take damage when I make it to fucking safety.
> 
> What actually happened
> The negative effects follow you until you get out of your host/pipe in somewhere with regular atmos, even if the host is safe and the pipe is empty.
> 
> Steps to reproduce if possible
> Should be pretty obvious at this point.

**Comment by Kurfursten** [comment]
Are we sure that's what's happening? Here's what I suspect happened.

> Crawled into a waste line
> Waste line was scrubbing out hot air
> Same atmos as before

**Comment by ihadtoregisterforthis** [comment]
I happened to try to exit xenobio as borer right after the surprise repiping, and ended up in space. I quickly got into the pipe again, but kept taking damage until dead, inside the pipe.
There were no borers that round.

**Comment by Kurfursten** [comment]
> I... as borer
> There were no borers that round?

Then who was phone?

**Comment by ihadtoregisterforthis** [comment]
If I change it into "No one had borers that round", will you rest easy?

**Comment by Kurfursten** [comment]
I'm still too spooked because of your avatar

**Comment by ihadtoregisterforthis** [comment]
It gets better, it has transparency

**Comment by gbasood** [comment]
I've noticed  that exiting a pipe shortly after taking lethal damage from the pipe's atmos as borer/other mobs will kill you even when you've been safe for a bit, possibly the same as what the issue's describing?

**Comment by ihadtoregisterforthis** [comment]
Borers aren't affected by pipe pressure, but they don't end the atmos damage when they ventcrawl.

**Comment by Shadowmech88** [comment]
Tested on a local server. While inside the pipe, the damage seems to continue forever. I rejuvenated myself 5 or 6 times and it still kept going. Interestingly, the damage also persists outside of the pipe, but only for a short time. I had to rejuvenate myself twice, but it did eventually stop.
I wonder if, somehow, the damage gets accumulated while in the bad atmosphere, and is only "used up" once you're on a turf with good atmosphere, so it persists forever while in a pipe and longer than it should once you get back onto a turf.

**Comment by DamianX** [comment]
This is because the body temperature of borers rises, then keeps doing damage while it's decreasing, as long it's still over `maxbodytemp`. It's especially unlikely for borers to survive this because they have such low max HP. It could be argued this is a feature but maybe we can alleviate the problem by making borers' body temperature equalize with the environment's more quickly. Thoughts?

**Comment by Shadowmech88** [comment]
That would also have the side effect of making them start dying more quickly though, as their body temperature would also rise more quickly in a fire.

**Comment by DamianX** [comment]
Increased resistance to temperature damage, then?

**Comment by Shadowmech88** [comment]
That could work.

**Comment by Shadowmech88** [comment]
Also, maybe some high-body-temperature damage messages or indicator for all mobs, since I doubt borers are the only ones who take damage from being overheated. A human getting out of a burning room and continuing to take damage would be similarly confusing, no?

**Comment by DamianX** [comment]
Makes sense.

**Comment by PaulRitter** [comment]
there already is a hud element to show body temp if im not mistaken?

**Comment by Shadowmech88** [comment]
I could be wrong, but I feel like the HUD element shows environmental temperature rather than body temperature.
