### ISSUE TITLE
Meta's cell lockers don't seem to link with the timer

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#6732]
![unlocked](http://puu.sh/lvTEB/637021194c.png)
This could be with the other lockers or this is just an oversight.

**Comment by Probe1** [comment]
I have no idea how these work.  If anyone wants to explain it I'll fix it but..

**Comment by PJB3005** [comment]
@Probe1 stupid shitty hardcode, I think.

**Comment by Probe1** [comment]
Well I can reproduce it.  cell locker 1 and 2 work normally.  Turn on the timer, the locker locks itself and when the timer expires it unlocks.  Cell Locker 3 on the other hand UNLOCKS when the timer is started and remains unlocked when it expires.

**Comment by Probe1** [comment]
Tested on Box, problem is localized to meta.

**Comment by Probe1** [comment]
Got it, there are two instances of Cell Locker 3.  It says here the second instance was used and it's all fucked up and its shits all retarded.  Replaced with the first instance.
