### ISSUE TITLE
Plants modified to receive bioluminescence don't glow; unless they spawn with it.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6733]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 443acf6575241b1e1f3f0b79f0149787bfb79941
> 
> General description of the issue
> Plants with bioluminescence trait don't normally glow; unless it's something like glowshrooms
> 
> What you expected to happen
> The plants should glow
> 
> What actually happened
> The plants didn't glow
> 
> Steps to reproduce if possible
> Use xenobotany to put bioluminescence on a plant; watch as it doesn't glow.

**Comment by Cisrox** [comment]
I have a screenshot of the issue.
![proof](https://cloud.githubusercontent.com/assets/11482753/11351874/0cc3da66-9207-11e5-9fc0-f462854372cb.PNG)

**Comment by clusterfack** [comment]
They probably aren't setting light or something

**Comment by PJB3005** [comment]
I actually remember when I initially ported lighting that I couldn't fully understand some parts of bioluminescence, might be my fuckup.

**Comment by Cisrox** [comment]
Glowshrooms work;
![glowshrooms](https://cloud.githubusercontent.com/assets/11482753/11352245/3f9fa5c6-9209-11e5-811a-88af057bd7ef.PNG)
But when modified to not light up;
![modified](https://cloud.githubusercontent.com/assets/11482753/11352252/4b4a501a-9209-11e5-9b14-2238164faedd.PNG)

**Comment by Killette2** [comment]
Potency is also a factor, keep in mind

**Comment by Cisrox** [comment]
Yes though even in complete darkness the plant did not glow. At 15 potency AT LEAST the tile the tray is on would be lit.

**Comment by Killette2** [comment]
Biolum is weird at stage 1, you usually need 20 potency for it to work properly
