### ISSUE TITLE
Combat borg "Light Amplification" viewmode does not work

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#6738]
> Revision (Should be above if you're viewing this from ingame!)
> 2f77597bd6fd4648d9df706bcfcc0367ad64f638 
> 
> General description of the issue
> Combat borgs have access to a "Light Amplification" viewmode, but it doesn't work.
> 
> What you expected to happen
> Switching to the right mode after selecting the mode.
> 
> What actually happened
> Nothing. Selecting the mode just closes the prompt.
> 
> Steps to reproduce if possible
> Become a combat borg, set sensor augmentation to Light Amplification.

**Comment by PJB3005** [comment]
Welp, somebody finally reported `see_in_dark` being broken.

This has been broken since the lighting engine was ported, back in the beginning of June.

**Comment by FudgePucker** [comment]
Why not just give combat borgs cyborg messons vision?

It pretty much is night vision, only you can see all turfs in the background

**Comment by clusterfack** [comment]
Light amplification? I'm not sure I've EVER heard of this

**Comment by SonixApache** [comment]
Combat borgs get mesons and thermals, just that this is also an option and it doesn't work.
@cluster it's probably supposed to be the same effect as the NVGs

**Comment by FudgePucker** [comment]
Is there a point to having it then if mesons do the exact same thing for a cyborg?

**Comment by SonixApache** [comment]
I think the difference is that NVGs remove all darkness but don't you see through walls, whereas mesons let you see through walls but fuck you over if there's no light.

**Comment by FudgePucker** [comment]
Play mining borg engine borg or MoMMI 
Its night vision for objects that aren't blocked by walls. I hunt goliaths better than fleshbag miners because of it.

**Comment by PJB3005** [comment]
@FudgePucker it's not, the range of a mining lantern is just so fucking huge it LOOKS that way.

**Comment by FudgePucker** [comment]
I didn't have my flashlight module on.

**Comment by PJB3005** [comment]
Then that is a bug.
