### ISSUE TITLE
R&D has shittons of guns and not one melee weapon

### ISSUE THREAD

**Issue by assdad211** [d3athrow/vgstation13#6743]
There's a full suite of plasma weapons and lasers and a ricochet gun and a gravity well gun and stuff, but there aren't any melee weapons at all.

Most of the likely candidates for high-end R&D melee weapons, like the high-frequency blade or energy axe, are 1hit kills and kinda retarded so they would need to be adjusted if you're gonna add those to the protolathe. Also it's worth noting that mechs have no melee-related modules either.

/tg/ has a singularity hammer that drags people toward the user when it's turned on, that could be good

**Comment by FudgePucker** [comment]
Oh boy let's give science MORE weapons.

Hell they already get ebows, why not just give them e swords, that way they don't need to be a traitor to murderbone

**Comment by assdad211** [comment]
You could remove one of the two-dozen guns if you think science can't deal with having one more weapon, but there should be at least a single melee weapon. It's not like infinite ammo for the hypothetical melee is a big deal when R&D already has advanced eguns that recharge themselves and first-hit stun from long distance.

**Comment by PJB3005** [comment]
> like the high-frequency blade or energy axe

Never, those weapons are adminbus ONLY for a GOOD reason.

And adjusting them will ruin them for the badmins.

**Comment by WeinerMaster69** [comment]
PJB, you could always have them be like the admin wheelchair, which retained the ability to carry the whole station after the wheelchair bug was fixed.

IMO, science needs less weapons, or at least have them harder to come by.

**Comment by ihadtoregisterforthis** [comment]
All stun weapons stun at first hit.

HF blade and energy axe are overpowered by design.

Mechs have melee weapons, except for the Odyseus. Combat mechs have melee armor modules.

Singularity hammer sounds ungood.

Science can get the most melee weapons via xenoarch.

**Comment by assdad211** [comment]
You could add energy axes to r&d and they still wouldn't be as powerful as the numerous long-ranged 1-hit-stun (aka instant kill) things R&D can make currently. There's no balance problem with adding melee to R&D because the ranged options are way better than any melee weapon.

**Comment by SonixApache** [comment]
advanced batons "for security", just like the stun revolvers?
