### ISSUE TITLE
Crew monitors not properly showing alt job titles in correct color

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6744]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Alternate job titles such as "nurse" and "surgeon" does not appear under the blue coloring of medbay staff on the text-based version of the Crew Monitoring Computer. Instead, all alternate job titles seem to show up under the civilian brown color.
This is difficult if you are looking down a list for coworkers or people in specific job titles and their names do not match for the corrisponding job color.

**Comment by clusterfack** [comment]
Should probably send both their alt title and their actual job (I hope to god those are stored separately), then sort by actual job and apply the alt title for the name
