### ISSUE TITLE
AutoTraitor Can't Find Any Volunteers To Be Traitor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6746]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 0f87ded8b3229daa514c62ad23413966f2c61bca 
> 
> General description of the issue
> When the lobby gives an error when the round is about to start, it says this:
> ADMIN LOG: Failed to set-up a round of AutoTraitor. Couldn't find any volunteers to be traitor.
> Error setting up secret. Reverting to pre-game lobby.

This is in a lobby full of about 40 people. It's saying not a single one of them has traitor checked. That can't be right.

> What you expected to happen
> The round to start
> 
> What actually happened
> Error setting up secret
> 
> Steps to reproduce if possible
> Have autotraitor be in the rotation

**Comment by Probe1** [comment]
Ive seen this come up during lowpop.  It leads to a lotta double traitor
