### ISSUE TITLE
Remove some of the xenoarch fluff machines to give more room for other things

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6755]
Not necessarily a bug, more of a feature request/discussion

![Xenoarch](http://imgur.com/m8QE4Wi.png)

Basic Machines
- Gas Chromatography - This machine is a great baseline when you want to use all the anomalist machines. It allows one to test the compatibility of carrier fluids against the sample fluid. It also identifies types of tests that are applicable when using that carrier fluid. Try using the common carrier fluids such as the one applicable to the material type (field type), carbon, or iron.
- Ion Mobility- This machine is used to identify what quantity of the carrier fluid is present. Basically, the higher the number, the more likely that’s the material your anomaly is made out of, but this device can only test one carrier fluid and will give no results if there is none of that reactive agent present.
- Accelerator - Used to examine the age of the material, only works on the billions of years scale.
- Isotope Ratio - Used to examine the age of the material, only accurate up to a billion years.

So, the functions of these machines can be effectively replaced by keeping notes on where you took the strange rock sample from, or is just lore fluff.

There's been a bit of discussion on removing these and instead replacing it with Xenobotany (Giving it more room to breathe and actually being useful) which would also free up the current area that xenobotany currently takes up for a break room (Basically somewhere to put a washing machine, something that xenoarch needs if it needs to use plasma to test large artifacts)

Putting this here for more of a easier way to log the discussion for ideas and such, save it disappearing into the void of SS13 logs

**Comment by 9600bauds** [comment]
Seems like these machines could easily be combined all into one, too.

**Comment by Probe1** [comment]
bump

**Comment by 9600bauds** [comment]
Closing in favor of #9249 since this one is pretty old
