### ISSUE TITLE
Turrets with temperature guns in them shoot tasers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6756]
(WEB REPORT BY: assdad211 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

a1b634749dde3189124b81c49d13c4d86e73a843

> General description of the issue

If you make a turret (use metal > make turret frame > etc > add energy gun > etc > finished) and add a temperature gun, it shoots tasers.

> What you expected to happen

That it would shoot temperature beams or not allow me to add the temperature gun to the turret.

> What actually happened

It shot tasers.

> Steps to reproduce if possible

Make a turret with a temperature gun ya fuck

**Comment by PJB3005** [comment]
Turrets give the least of a fuck what gun you put in them, sadly.

**Comment by assdad211** [comment]
They work just fine with decloners, the righteous bison, etc. and shoot those guns' projectiles.

It's only guns with select-fire that screw them up. I just tested the staff of animation and mental focus, both caused it to shoot tasers.

Actually, just looked and it seems guns that aren't defined in portable_turret.dm just default to tasing, so it's nothing to do with selectfire specifically.

**Comment by Zth--** [comment]
@PJB3005 deity added this feature on his weapons overhaul

**Comment by PJB3005** [comment]
Oh
