### ISSUE TITLE
temperature gun lock boxes are stupid

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#6759]
temp guns are mostly harmless. their only use would being killing slimes, but xenobio can't get them.

you know whats not in a lock box? rapid fire syringe guns.

**Comment by FudgePucker** [comment]
also i am in pain from getting my wisdomteeth ripped out and am posting this on a wiiu gamepad

**Comment by PJB3005** [comment]
I agree they should not be in a lockbox.

**Comment by 9600bauds** [comment]
I agree about his wisdom teeth.

**Comment by Zth--** [comment]
I agree with both

**Comment by FudgePucker** [comment]
Just make it so that temp guns can't shoot open lock boxes like floral sotrnomotro rays.

They can't even fit in back packs, you know what fits in back packs? Rapid fire syringe guns.
