### ISSUE TITLE
/obj/machinery/computer/forensic_scanning cannot be repaired

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6760]
It's a forensic console.  When damaged it gets the standard broken screen that everyone is familiar with.  
![image](https://cloud.githubusercontent.com/assets/8550416/11409356/4ab0ffac-938d-11e5-85a4-df4f58e87f94.png)

Trouble is, the broken glass can't be removed.  Take for example obj/machinery/computer/telecomms/monitor.  If it is lasered a few times or EMP'd it changes to stat == 3.  If the player then uses a screwdriver, it removes the broken glass, and he can add new glass and screwdriver it again to repair it.

Either the forensic console has no such code, its code is not functioning, or it does not properly inherit from obj/machinery/computer.

**Comment by PJB3005** [comment]
The console doesn't have a circuit defined, so it isn't repairable.

If it did, every time you rebuilt it it would spawn a new book.

**Comment by 9600bauds** [comment]
Same fix as #4990

**Comment by Probe1** [comment]
Yeah I noticed that.. when I spawned a new one in it came with another book.

Sloppy
as 
fuck.

**Comment by PJB3005** [comment]
Welcome to oldcode<sup>tm</sup>.

**Comment by Probe1** [comment]
As an extra bonus, when the machine is damaged, any object inserted into it does not pop out, locking it in there 5ever until its repaired.  And this console can't
be
repaired

**Comment by Zth--** [comment]
Insert the nuke disk
Break the console
???
Profit

**Comment by PJB3005** [comment]
Yes, exactly.

**Comment by 9600bauds** [comment]
this can be closed
