### ISSUE TITLE
Weird/Unknown HUD element

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6762]
(WEB REPORT BY: cyadox REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 1709a73bdc6abd9f34226e682770357271f0ae46
> 
> General description of the issue
> C: 50
> G: 0
> Never seen them on my HUD before IAGFPRMF never heard of them. Not sure what it is. http://snag.gy/ZnwqH.jpg
> 
> Steps to reproduce if possible
> Not sure. Normal login mid-round as cargo tech. Nothing unusual.

**Comment by Probe1** [comment]
chemicals/genomes

probably a ling round.  same issue as always, inappropriate huds.

**Comment by Cyadox** [comment]
Yup, was a Ling round. I think this has already been reported, so feel free to merge the two or whatever if it has.

**Comment by Probe1** [comment]
Its happened to me, getting a vamp blood counter during a vamp round.
