### ISSUE TITLE
Vox Turned Into Chickens Cannot Be Put Back

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6767]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 1709a73bdc6abd9f34226e682770357271f0ae46 
> 
> General description of the issue
> Vox turned into a chicken cannot get turned back.
> 
> What you expected to happen
> I expected them to turn into a vox when injected with the right SE.
> 
> What actually happened
> The injector disappeared, and the vox remained a chicken.
> 
> Steps to reproduce if possible
> Turn vox into chicken.
> Get SE to turn it back into a vox.
> Click chicken with SE
> SE disappears, no message, vox is still chicken.

**Comment by PJB3005** [comment]
Unsure if this is [feature request] or [bug] [feature loss].

**Comment by ihadtoregisterforthis** [comment]
Bug and feature loss until proven otherwise.

**Comment by Ephx1** [comment]
I think this is just a really good feature

**Comment by 9600bauds** [comment]
massassive griff

**Comment by Arthurdentist** [comment]
this wasn't a feature loss, I am pretty sure it has always been this way.

**Comment by ihadtoregisterforthis** [comment]
How about making vox become turkeys? This way there's a possibility for a new monkey subtype for them and there's no need to make chickens become vox via SE injection.
Plus they stay as domestic birds for meals.
Plus plus the turkey dish can make more sense.

**Comment by Allspice** [comment]
Vox can already be turned into green chikin and be turned from chikin to vox like humans and monkeys, issue resolved I guess.

**Comment by Exxion** [comment]
Yes. Resolved ever since vox got proper monkey forms.
(Vox green chickens are a subtype of monkeys, but they used to just turn into regular chickens. And since genetics is a carbon thing and simple_animals aren't carbons, everything broke.)
