### ISSUE TITLE
Blowing diks

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6768]
Happened again, the nuclear disk got bombed and teleported safely into the void (0,0,0). In Box, if that matters.

The admin in patrol, Rei, spawned a new one, then removed both, then spawned another one. What changed is that the original got respawned a few seconds before the round end

> [18:54:42]GAME: /obj/item/weapon/disk/nuclear has been destroyed. Creating one at Fore Port Maintenance - 69,152,1
> [18:54:42]ADMINWARN: <span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">/obj/item/weapon/disk/nuclear has been destroyed. Creating one at <A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=69;Y=152;Z=1'>Fore Port Maintenance - 69,152,1</a></span></span>
> ...
> [18:55:02]GAME: Antagonists at round end were...

**Comment by PJB3005** [comment]
That's... weird, the only thing I can think of is something keeping a reference to the original, and then later at round end it being removed, causing BYOND's GC to kick in and delete the original one.

**Comment by clusterfack** [comment]
This results from a confluence of factors that I have identified, I will make a fix for all of them soon enough
