### ISSUE TITLE
Gasses flow through secret walls?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6770]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 06c3047ebe1c2773f797a2abb17e490cc48c3e7e 
> 
> General description of the issue
> Gasses flow through secret walls
> 
> What you expected to happen
> Gas shouldn't flow through
> 
> What actually happened
> Gas flowed through
> 
> Steps to reproduce if possible
> Make a secret wall, put plasma on one side and watch it cross to the other

**Comment by PJB3005** [comment]
This is 100% intended.

**Comment by Cisrox** [comment]
but why?

**Comment by Probe1** [comment]
I think it even says so on examine, or at least the wiki.

**Comment by Killette2** [comment]
It's intended, and the reason why you're not able to make secret walls to space

**Comment by Exxion** [comment]
They're makeshift doors. Doors don't block airflow, so why should makeshift doors?

To clarify, doors are distinct from airlocks, even though the terms are generally used interchangeably
