### ISSUE TITLE
After using the verb Sleep, your dude will never wake up.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6772]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 06c3047ebe1c2773f797a2abb17e490cc48c3e7e 
> 
> General description of the issue
> When sleeping you go unconcious, then after like 5 minutes you gain vision, but you're still asleep and will NEVER wake up.
> 
> What you expected to happen
> I would wake up eventually
> 
> What actually happened
> I stayed asleep forever
> 
> Steps to reproduce if possible
> Use sleep, leave computer on for a while, watch as you never wake up without help.

**Comment by 9600bauds** [comment]
requesting (CAN'T WAKE UP) tag

**Comment by clusterfack** [comment]
The sleep, OF DEATH

**Comment by 9600bauds** [comment]
Does anyone have any idea of how long did sleep use to take before this bug?

**Comment by Zth--** [comment]
Actually it should be like rest. I mean, sleep until you decide to wake up instead of some random timer

**Comment by 9600bauds** [comment]
I think the bug here is that if you use the rest verb while asleep, you go into this half-awake-but-still-asleep state when you would wake up, and have to unrest to wake up 5real

**Comment by MadmanMartian** [comment]
I can not seem to be able to reproduce this
