### ISSUE TITLE
[Bleeding-Edge] Shuttles on custom map suddenly not working?

### ISSUE THREAD

**Issue by butthatswrongyoufuckingspiral** [d3athrow/vgstation13#6773]
Hey guys, so I've been working on a small custom map over the last couple of days. Have a supply and mining shuttle which both worked perfectly until late in the evening yesterday when I updated to a new version of BYOND.

Now suddenly, every time I start up my server I get the error message (3 shuttles initialized, of them 0 were initialized properly with errors that there aren't docking ports for them, even though there are) Anyone encounter this issue? I triple-checked to see if I removed a docking_port by accident or something, nope. Reverted to an older version of the dmm where I know for certain everything was working, again nothing.

**Comment by PJB3005** [comment]
@unid15

**Comment by unid15** [comment]
Send me the map to unvidel@gmail.com and I'll take a look

**Comment by clusterfack** [comment]
Hi egg

**Comment by butthatswrongyoufuckingspiral** [comment]
Bit late with sending the map but I have emailed it to unid15, also, hello Clusterfack!
