### ISSUE TITLE
While cuffed, you can still move around if you're grabbed by somebody.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6775]
This goes completely against the logic that you can pull somebody who's cuffed to prevent them fro walking.

**Comment by BestName** [comment]
What exactly do you mean? If a third party grabs someone who is being pulled, they can break free of the pull?

**Comment by Ephx1** [comment]
I think he means being grabbed should have the same effect of being pulled where you can't move.

**Comment by BestName** [comment]
Oh yeah that's reasonable. The current system doesn't make much sense.

**Comment by Shadowmech88** [comment]
I agree. As a changeling, it's a nuisance to have someone cuffed and have taken their radio, start absorbing them, and they're able to just walk away.

**Comment by 9600bauds** [comment]
nevermind I'm a dolt and misread the title
