### ISSUE TITLE
Staff of Change Selection doesn't work properly.

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#6778]
It doesn't matter what your staff of change is set too, your victim will be changed into any random monstrosity. Previously when you changed your staff's settings then your victims would predominantly turn into whatever you set them to turn into; now no matter what you setting you have enabled, the outcome will be entirely random.

To test:
- Spawn staff of change
- Go through each setting
- Notice how it makes sod all difference anymore.

**Comment by Shadowmech88** [comment]
It hasn't for a long time.
Is there not already a bug report about this?

**Comment by clusterfack** [comment]
No, there wasn't

**Comment by clusterfack** [comment]
You guys should really report these things when you first encounter them
