### ISSUE TITLE
Rapid Cable Layer won't work as MOMMI?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6786]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7359d40a94d03cfb890e0b2264186414cbf01eee 
> 
> General description of the issue
> Cable layer just doesn't want to work. I switch it on and it doesn't lay cable Sometimes lays one strand then has to be toggled on and off again.
> 
> What you expected to happen
> For it to work.
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
Can confirm, it's broken.

**Comment by clusterfack** [comment]
This is due to the fact the rcl's movement laying only functions through human/move() code
