### ISSUE TITLE
Alien reproduction rework please

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#6788]
Basically, allow the queen to use plasma to make 2 or 3 larvas without the need of monkeys, and if she wants to make larva after those 2 or 3 she would require bio mass which can be obtained from eating humans, monkeys, and so on?

Lets face it, aliens have the worst starting phase ever, after they get a few to help, they become a decent threat

**Comment by ihadtoregisterforthis** [comment]
˃birthed aliums
![sddefault](https://cloud.githubusercontent.com/assets/13305885/11460965/7a2b90e2-96d7-11e5-859c-7e93a85646ef.jpg)

Let's not, please.

**Comment by AlphaBuffalo** [comment]
then aliens will never be a viable round type

**Comment by Ephx1** [comment]
They're not really viable as a roundtype as is. Other than on defficiency which has some maint monkeys.
You want to actually breed on any other map? Get your ass to virology, or space yourself to the research outpost.
Otherwise do nothing.
