### ISSUE TITLE
Nuke Ops quality of life improvements

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6798]
Add objectives including nuke code into notes, they are currently blank. Could add a short note about properly setting up nuke and the purpose of pinpointers.

Disable all but syndicate channel for syndicate radios and headsets, until turned on manually. This will help a lot with team communication as the amount of chat lines can be overwhelming for new guys, often not even realizing they are being spoken to.

Put pinpointers into lockers with hardsuits.

Make agent PDAs start without a registered name.

**Comment by Probe1** [comment]
all nice suggestions.

**Comment by ihadtoregisterforthis** [comment]
The chat color is not very distinguishable from the rest. The dim brown gets lost between the talking, even as observer. A better color would be great, and maybe enough to keep the earpiece as it is.
