### ISSUE TITLE
Fat mechanic spawns naked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6799]
(WEB REPORT BY: pedonymous REMOTE: 158.69.55.2:7777)

> 5203a27df75b69c1dbc89ceffe01b99302970bd3 
> 
> A fat mechanic spawns nude, all their clothing in their pack. The mechanics outfit is too small.
> 
> Placeholder fatsuit skin
> 
> Spawned naked
> 
> Join game with a fat character as mechanic

**Comment by Intigracy** [comment]
haha stupid fatty
