### ISSUE TITLE
disposal mailing system guide

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#6800]
EDIT: HTML version here, with different formatting:
http://www.w3schools.com/code/tryit.asp?filename=FBQIMSZU2OEH
___
it seems that almost no one knows how the mailing system actually works, so i think would be useful if you add a guide in-game as a manual inside delivery office, and another guide on the wiki too.

i tried to do a book with a guide but i'm not an english speaker, so feel free to add/modify it as you prefere, if you want:

> title: Guide to disposal mailing system
> vvvvvv ----- manual start ----- vvvvvvv

[center][large]Guide to disposal mailing system[/large][/center]

Most people misunderstand how disposal mailing system works; items are sent in bunches, not individually.

[large]So, how it works?[/large]

When an item enters in the delivery chute inside delivery office, a countdown starts, it's about 10 seconds;

If another item enters the delivery chute before the countdown ends, the countdown resets and starts again;

If the countdown expires, you can hear the faint noise of a piston and [b]all[/b] the items inside the delivery chute will be sent [b]at the same destination[/b].

[large]What will be the destination?[/large]

If there are no tagged items, all the items will be sent to the recycling room;

if there is one item wrapped+tagged, [b]all[/b] the items, even the unwrapped/untagged ones and garbage, will be sent at the destination of the tagged item;

If there are multiple wrapped+tagged items at the same time inside the delivery chute, the last one sets the destination;

If there is a living person or animal inside the delivery chute, all the stuff with it will be sent to the recycling room anyway, ignoring tags; however, you can send living people or animals at a destination if they are inside a container (closets, coffins, animal crates); for living people, it works only if the container is wrapped.
Anyway, corpses and dead animals will reach a parcel's destination.

[large]Examples[/large]

[b][i]You need to send 4 crates to engineering:[/i][/b]
just put all 4 of them on the conveyor belt and wrap+tag as "Engineering" only 1 of them, then send them together; all of them will reach engineering.

[b][i]You need to send a goat crate to hydroponics but the goat crate is unwrappable/untaggable:[/i][/b]
just take any other item, for example a piece of paper, wrap+tag it as "Hydroponics", put the wrapped paper and the goat crate both on the conveior belt and let them go togheter; both of them will reach hydroponics.

[b][i]You send 3 parcels in the same shipment, one tagged "Bar", one tagged "Theatre" and the last one tagged "Medbay":[/i][/b]
all 3 parcels will be sent to medbay (this is the case when people see parcels reaching the wrong destination).

[large]Mail outlet[/large]

Inside the delivery office, there is a also a mail outlet that has the purpose of filtering untagged parcels from trash; this in intended to be used by all crew outside cargo to let them use the mailing service without the need to go to cargo.
Example:
[list][*]a scientist needs to send an item to medbay
[*]he uses package wrap to wrap the item (there is some package wrap in many department and also in the tool storage room, more package wrap can be bought from cargo too)
[*]the scientist can use a pen to add a note to the parcel, for example "send to medbay"
[*]the scientist places the parcel inside a disposal bin
[*](optional but advised: the scientist could contact cargo staff telling them that he sent a parcel)
[*]the parcel will reach cargo and pop out from the mail outlet instead of the trash outlet
[*]cargo tech will see the parcel, read the note on it, tag it as "medbay" and just use the mailing system as usual[/list]

**Comment by uazuaz** [comment]
updated. added:

> If there is a living person or animal inside the delivery chute, all the stuff with it will be sent to the recycling room anyway, ignoring tags; this means that you can't trick the mailing system to send someone or yourself somewhere.
> However, corpses and dead animals will reach the parcel's destination.

**Comment by uazuaz** [comment]
updated formatting.

**Comment by 9600bauds** [comment]
This is really informative and should be on the wiki if it isn't already. If polished up to sound corporate-like it could even be in-game as a premade book in cargo.

**Comment by uazuaz** [comment]
thanks @9600bauds , the wiki is a bit superficial on this matter, that's the reason i created this guide.
if someone wants to add it in game and/or on the wiki, feel free to modify it as you prefere.

**Comment by uazuaz** [comment]
updated:
replaced

> If there is a living person or animal inside the delivery chute, all the stuff with it will be sent to the recycling room anyway, ignoring tags; this means that you can't trick the mailing system to send someone or yourself somewhere.

with

> If there is a living person or animal inside the delivery chute, all the stuff with it will be sent to the recycling room anyway, ignoring tags; anyway, you can send living people or animals if they are inside a container (closets, coffins, animal crates).

**Comment by Zth--** [comment]
:+1: I wish I had this guide when I first started with cargo

**Comment by uazuaz** [comment]
thanks @Zth-- 

updated some minor stuff.

**Comment by uazuaz** [comment]
updated again, about sending living people i added

> for living people, it works only if the container is wrapped+tagged.

should i add the book using the library scanner in-game?

**Comment by 9600bauds** [comment]
I really think this deserves to be added in the map somehow.

**Comment by gbasood** [comment]
At the VERY least, it should be added to the wiki in its current state.

:+1:

**Comment by uazuaz** [comment]
just a reminder, i saw that there was the intention of adding this guide in-game as a book
https://github.com/d3athrow/vgstation13/pull/8285#issuecomment-186291499
and someone added a page on the backup wiki: http://game.ss13.moe/wiki/index.php?title=Disposal_Mail
but the book was never added, maybe because of the server issues at the time.

**Comment by uazuaz** [comment]
upated to explain the mail outlet, just in case.
note that the bullet list in-game is obtained using [*] but it breaks here on github, if you can use the edit function on the OP you'll see it as it should be.

**Comment by Probe1** [comment]
honest to god man you should just code this.  all it takes is looking at an engineering book or something and copying that code.

**Comment by uazuaz** [comment]
it's formatted already, what else could i code? can't understand, sorry.

**Comment by Probe1** [comment]
Putting it in the appropriate .dm file as an object and making a pull request.

**Comment by uazuaz** [comment]
ok, i'll try.

**Comment by uazuaz** [comment]
i used existing manuals as a template and changed the guide to HTML, also changed some formatting, but i can't understand how to open a PR.
the HTML version is here by the way:
http://www.w3schools.com/code/tryit.asp?filename=FBQIMSZU2OEH

**Comment by Probe1** [comment]
https://cdn.discordapp.com/attachments/239823463802470400/241442060958171136/startingcodingwithsmartgit.png

CHeck this easy guide out for PRs.

**Comment by uazuaz** [comment]
sorry, i never coded and i think i'm not gonna do it again, so i'm not installing anything on my pc to do it (making the HTML version of this guide took me about 3 hours, go figure), by the way i linked this guide on the 4chan thread a couple of days ago and someone answered
![1](https://cloud.githubusercontent.com/assets/6170726/21961463/68f31ff2-db0a-11e6-9df0-090fbe23ac30.jpg)
so i hope someone more experienced will add it.
by the way it's just a copy paste now.

**Comment by Probe1** [comment]
Yeah that was me.  I'll grab what you did in the OP and try to finagle it.
