### ISSUE TITLE
Mindswap is still a mess

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6804]
Mindswapping causes your spells to only produce the spell chat lines like "ARSE NATH" but doesn't actually cast the spell. This was with having robeless spell and trying to cast knock/arsenath after mindswap.

According to thread it also gives your victims your spells.

Related https://github.com/d3athrow/vgstation13/issues/4836

Regardless of what the fluff description says, mindswap never did or should have caused spells to be forgotten or unusable, as that makes it absolutely pointless combined with the obvious mechanics giving away that a mindswap is in progress.

**Comment by clusterfack** [comment]
Yes related to another issue additionally, it is due to the fact that there is no 100% proper code to transfer spells from one mob to another at the moment. The current way is hacked in and has led to this as well as one or two other bugs.
