### ISSUE TITLE
Taxi has no medbay bells

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6805]
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> beaf44dc5b21d3830d7b08de07dee32a53b15ffe 
> 
> General description of the issue
> Taxi has no medbay bells and no reception apart from the paramedics, so on lowpop there's a reasonable chance you'll miss people needing help.

**Comment by Probe1** [comment]
@PJB3005 didn't autoclose, desk bell was added.
