### ISSUE TITLE
Ghost (Follow) prompt broken

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#6808]
> Revision (Should be above if you're viewing this from ingame!)
> beaf44dc5b21d3830d7b08de07dee32a53b15ffe 
> 
> General description of the issue
> The [Follow] prompt for ghosts doesn't work. Clicking it doe snothing, it is merely text.
> 
> What you expected to happen
> When I click [Follow], it should follow.
> 
> What actually happened
> Clicking [Follow] doesn't actually do anything. It's just text.
> 
> Steps to reproduce if possible
> Be ghost, try to follow.

Probably related to #6795

**Comment by clusterfack** [comment]
As far as I am aware this is actually a byond bug where href links in chat are not working properly. I believe there is a bug report on their forums about it

**Comment by ihadtoregisterforthis** [comment]
Works_on_my_machine.png

I know this doesn't work when decapitated, as the ghost stays on the head until properly going /ghost.
Doesn't work for nonexisting mobs either. As in if a mob gets deleted or a ghost gets a body.

**Comment by clusterfack** [comment]
Yes, as an href link it checks the topic for the mob you are in and follow only exists for ghosts.

**Comment by SonixApache** [comment]
In this situation I can follow stuff just fine by using the Follow verb, it's just the links that don't work.

**Comment by SonixApache** [comment]
Oh, update; Apparently if I click the ( in (Follow) it does work. Odd.

**Comment by PJB3005** [comment]
@SonixApache er, did you download the 509 stable version right as it went stable, because that version had a bug where they were unclickable, Lummox re-released the version, just redownload.

**Comment by SonixApache** [comment]
Welp, that was it. You can close this and #6795 then.

**Comment by clusterfack** [comment]
I told you, it was a byond bug. Does nobody believe me?
