### ISSUE TITLE
Wheelchair over blood leaves FOOT prints

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6812]
I'd like some tracks instead

**Comment by Inorien** [comment]
![blood_track](https://cloud.githubusercontent.com/assets/16082007/11499912/6b6f1b0a-9821-11e5-878d-276ce17e2143.png)
![blood_track2](https://cloud.githubusercontent.com/assets/16082007/11499911/6b50bae8-9821-11e5-985b-c9d143642371.png)

?

**Comment by Kurfursten** [comment]
Looks good. While we're thinking about it, what else should leave tracks?

MULEs, other children of chair (un-upgraded Janicart, Clowncart, office chair) maybe. Anything else?

**Comment by ghost** [comment]
Basically all vehicles, and the MULE already sort of leaves tracks when it runs people over

Also, those tracks are a bit dumb for the MULE, doesn't it have tracks ?

**Comment by ihadtoregisterforthis** [comment]
There are already blood wheel trails and the mulebot has wheels, if that's what you are talking about.

![muleblood](https://cloud.githubusercontent.com/assets/13305885/11510124/ca23b1be-9840-11e5-95bc-2eb37c311f76.png)

**Comment by Kurfursten** [comment]
Perfect then. It's so rare to see a MULE run someone over I didn't realize.

**Comment by FudgePucker** [comment]
Make flame trails if you put welding fuel/plasma on the weeks.

Hallways? Were we're going we won't need hallways.

**Comment by FudgePucker** [comment]
Fuck auto correct I ment wheels
