### ISSUE TITLE
Telepathy for greys is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6830]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Even at round start, when I try to access the telepathy power I get:
"You shouldn't have this spell! Something's wrong."

Also the tab that usually holds superpowers is missing from the Info bar at the top.

**Comment by ihadtoregisterforthis** [comment]
Known issue with solution at #6829

Calm your minmaxing

**Comment by clusterfack** [comment]
It should be fixed by the next round
