### ISSUE TITLE
Shiggy your waifu crate is fucked

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#6831]
It don't work 
Can't give a reason for the order, can't receive waifu shit

**Comment by FudgePucker** [comment]
Just looked real quick at the code, nothing is misplaced.

What could have caused it?
Can you test it again?
Could you order any other crates?

**Comment by Kurfursten** [comment]
I have tested this and reproduced it. I've looked over the code countless times (and actually prompted Shiggy's first fix to the code, there was originally something wrong with it). I've tried lowering the number of items in the crate. I'm going to get to the bottom of this.
