### ISSUE TITLE
Feature Request: Advance air alarms

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#6837]
This is going to be a feature request that 50% of you will not see the point of and 50% of you will understand that this will lead to a atmospherics dystopia that will result in non engineering staff with soldering tools and RPDs being shot on sight.

The problem with some of the set ups in xenobio and other areas (#6728) have injectors that can only be turned on and off and changed from atmos automation computers, something that you don't want to give easy access to because of the ability to destroy the station from a hide away hidden in maintenance.

So a possible solution to this is the ability to change the settings of devices other than unary vents and scrubbers from an air alarm.

Using a soldering iron on an air alarm board will make it into an advance air alarm board (you connect the part that controls the other devices to the rest of the board with a quick solder that was separated for safety reasons, or some shit.), then just construct the air alarm like normal, make the advance air alarm look different to show that it is not a normal air alarm.

The advance air alarm would be able to turn on injectors in the same room and turn them off once the air alarm detects a specific pressure, meaning that you would be able to use injectors to quickly repressurize areas like escape that get breached often. This would give more of a reason for engineers to carry a soldering iron other than emag crazy antags, instead of carrying around a air pump to connect to distro to help quickly repressurize, you can just upgrade the air alarm and pop down an injector to get it to a safe pressure super fast.

This would fix #6728 by just changing one turf instead of having to rework an entire department, the injector in the borer chamber would be able to be turned on and off from the computer already in there.

The problem with this is that, well, this is a very DANGEROUS AND POWERFUL TOOL TO LET GET INTO THE HANDS OF ANTAGS (and idiots)! Vents have sensors and a maximum pressure, a room filled with 1000 kpa isn't that bad, a single room of it wouldn't be bad enough to cause a shuttle call. Just getting a  multi tool, a soldering iron, four sheets of glass, and a RPD you would be able to make a small glass cage filled with injectors, turn on the injectors, and then run like hell. Now a room is up to 'HOT DAMN IS THAT A LOT OF FUCKIN PRESSURE' instead of 'eh its just 1000 kpa don't call the shuttle over that'.

This would be a great tool/toy for autmosians, but a very harmful and chaotic tool in the hands of someone who has two braincells to rub together and antag rule one immunity.

The question is if advance air alarms should also be able to be able to control other devices such as; pumps, duel vents, and digital valves. Also if they should also be able to have other gas sensors and meters linked too it to be able to have a more safe with more effort system, for example, you can upgrade the air alarms in medbay and the main hallways and link a meter hidden in maintenance on a distro pipe to shut off vents if it detects plasma, CO2, or N2O/ Freezing or Hot temperatures. Meaning that you would be able to prevent major parts of the station from being destroyed. This would be balanced, because good luck explaining that you want to just upgrade someplace for safety before getting chloral'd, stripped, and disposaled.

**Comment by FudgePucker** [comment]
Maybe also include a little sentence above the settings when changing injectors and other devices besides vents and scrubbers that they need to KNOW WHAT THE HELL THEY ARE DOING before changing anything. Maybe make it funny yet not immersion breaking by having it be "Warning: Please do not change advance settings with out having read and understood 'Atmospherics: volume one edition three.'" It's funny because understanding atmospherics is about as hard as having to read an entire high level science text book. Seriously, it would be very convenient to have injectors being able to be simply controlled from an air alarm with out having to deal with setting ID tags and freqs from a AAC, but it would also mean giving the power to control injectors to people who use the emergency siphon command, 'oh hey this area is under pressured, better set this bad boy to maximum volume and maximum pressure to speed it along.'

**Comment by PJB3005** [comment]
You can use injectors with the atmospheric tank control computers...

Also, you can EASILY disable the pressure limit on a vent, so I don't think this would be OP at all.

**Comment by FudgePucker** [comment]
Don't vents have a maximum of 1000 somethin kpa?
Injectors have an absurd mol limit and no pressure limit, like I said, glass cage and a bunch of injectors hidden in maintenance can cause a super (not 'oh just set the air alarms to replace air and make sure the area is closed off to stabilize it' level of pressure, more like 'OH GOD AI CALL THE SHUTTLE EVERYONES DEAD' level of pressure) high area of pressure.

EDIT: Also atmospheric tank control computers is another thing that is overkill for most situations when having a nice air alarm do all the inputting IDing and tagging for you. Seriously, having to ID tag and set frequencies is one of the most tedious and boring things ever. The thing that takes the most time (or feels like it) when I set up an SME is setting up the injectors because using multi tools is a bore.
EDIT2: It would also add more use for a soldering iron for engineers besides fixing emag'd airlocks, I haven't actually used a soldering iron yet, I use the socket wrench of all things more than it.

**Comment by 9600bauds** [comment]
Maybe have a physical dongle in Atmos that turns air alarms into advanced air alarms while it's plugged in? 

Effectively, Atmos access, but in a way that lolcaptainsspare doesn't defeat.

**Comment by FudgePucker** [comment]
@9600bauds
That would also work, but you forgot about the situation in xenobio.
Maybe both so that you can quickly upgrade an airalarm to set it up then remove it to prevent someone from just pulsing a wire or having access somehow (or that fucking stupid AI who doesn't fucking understand fucking atmospherics that fucking fucks up fucking everything.), and also being able to permanently upgrade an air alarm by just overwriting it with a soldering iron, (AIs and cyborgs can't do this.) meaning if you want to use an advance air alarm for a little autmos burn chamber but don't feel like putting in your dongle in and out of the air alarm and also for toxins (maybe) and xenobio chamber.

Give engineering borgs a dongle as well that requires them to stand right by the air alarm to use it and it turns back to normal if they walk away (side effects include engineering borgs being able to ERP with their 'dongle', BOY AM I MATURE.).

**Comment by 9600bauds** [comment]
Easy, have the xenobio air alarm already start off as permanently advanced :^)

**Comment by FudgePucker** [comment]
Maybe also have some permanently upgraded air alarm frames in the engivend then? That way derelict MoMMIs would also have access to them.

**Comment by ghost** [comment]
You can drain the entire air network into a single canister with just a volume pump, passive vent, scrubber and a connector.

**Comment by FudgePucker** [comment]
Yes I know, that's because you are using scrubbers.
Scrubbers have no pressure limit and an absurd mol maximum.

Why would you need a volume pump anyways? The vent and the scrubber already act like pumps and don't volume pumps have a limit of around 4000~ kpa as compared to scrubbers (insert number here)*10^1000? Wouldn't it be as simple as vent into glass cage, scrubber siphoning out of glass cage, connector connected directly to scrubber?

I guess you would be able to do the same thing technically with just scrubbers and vents instead of injectors, it would be just easier.

**Comment by ghost** [comment]
Volume pump to speed up transfer of gas into the vent itself, surrounded by glass. Scrub gas from vent directly into connector.

Passive vents dumb their content onto the tile, so the faster you fill the vent the faster you dump it.

**Comment by FudgePucker** [comment]
Ohhhhhh you said passive vent not unary vent, my bad. Still, it might be faster to just use a unary vent because it is one way instead of merging the pipe network with the environment like the passive vent.

**Comment by ghost** [comment]
> instead of merging the pipe network with the environment like the passive vent.

That's not what it does. Unary vents are passive vents, and pump vents. Neither merges pipe network with a tile.

``` DM
var/datum/gas_mixture/removed = air_contents.remove(volume)
loc.assume_air(removed)
```

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/ATMOSPHERICS/components/unary/vent.dm

**Comment by FudgePucker** [comment]
oh okay then.
