### ISSUE TITLE
Probes big gay ideas for small xenoarch finds

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6844]
1.  Code fossils to give a genetic power/defect at a 50/50 chance.  Use a needle on a fossil to turn it into an injector and make the fossil useless.  Genetics are already on research's radio and quasi researchers.  Xenoarchs delivering a crate of fossils for geneticists to play with sounds way more fun than a shitty skeleton you can assemble that doesn't do anything.
2.  Make one of the more useless things like ancient statuettes point towards large artifacts.  Either once from the location they were dug up on or continuously (but that would be a significant balancing issue)

**Comment by Cisrox** [comment]
1.) Sure
2.) Maybe have ancient statuettes have their own effects like spawning things in long intervals such as corgis or space carp, hostile mobs being at a low chance, and maybe the cooldown being like 5 minutes
3.) I have another suggestion too; maybe having trace organics include alien organs you can put in somebody for random effects such as improved blood generation, tricord generation, poly acid generation, poly acid filtering, burn damage creation, etc.

**Comment by icantthinkofanameritenow** [comment]
1.) Could work. Alternately, like Bay we could make the resulting skeleton reviveable into a new creature for the xenobiologists to mess with. We'd need some sprites for that though, and possibly a new AI if they aren't just going to be recolors of simple mobs.
2.) Agreed. Half the stuff that appears is either identical to/inferior to its normally made counterparts or is outright useless. The statuette idea might work (not CisRox's- it's too similar to the autocloner that already exists). Similarly, the tools might work faster than regular tools, or the swords may sometimes deal a different damage type other than brute damage.
3. ) In addition to what CisRox came up with, I think some more "unique" artifacts are in order as well as tweaking of the old ones. At the very least, the Giga Drill should dig at the rate of a diamond drill and the Hover Pod should not be slower than a Diona. I'm open to new ideas for unique large artifacts, though.

**Comment by Cisrox** [comment]
Also there's a broken artifact named object that has no sprite and does absolutely nothing

**Comment by ihadtoregisterforthis** [comment]
DINOWARS
DINOWARS
![dinowars](https://cloud.githubusercontent.com/assets/13305885/11578532/4cf29f90-9a05-11e5-9a48-f14de277afbd.jpg)

**Comment by Probe1** [comment]
Thought of something nice while digging.

You know those resprited beacons?  You can set their frequency but they don't do anything else other than act like a normal boring beacon?

Better idea:  They're teleporters that work on frequency.  When activated, they open a portal to a random teleporter beacon that has the same frequency.  If you found two you could have your own little network.  If you found a lot you could set up a complex network.

**Comment by Probe1** [comment]
RnD item, mid level research, works like a mining analyzer and highlights tiles with shit in them.  Would save a lot of low enjoyment clicks.

**Comment by Probe1** [comment]
Attunement crystal for small xenoarch finds that locates things

Use once, can locate a large artifact or a PDA or something else nice. Gives players a chat output about it vibrating when it gets close and changes color from dull black to blue to vibrant green like a PDA pinpointers dot. Maybe aligns in the direction. Can only be set once.
