### ISSUE TITLE
Yellow Dress from Formal Feminine clothing crate has no sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6846]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
I put it on, and it had no sprite when I tried to wear it.

**Comment by 9600bauds** [comment]
was ANY of this tested

**Comment by NigglyWiggly** [comment]
Of course not.

**Comment by Probe1** [comment]
The players are testing it right now :v)

**Comment by Probe1** [comment]
under/wedding/bride_white is named orange wedding dress.  Its desc and sprite are a white dress.

**Comment by Probe1** [comment]
well the icon is there time to find the snag.

**Comment by Probe1** [comment]
I have absolutely no idea what is wrong.

```
/obj/item/clothing/under/dress/dress_yellow
    name = "yellow dress"
    desc = "A flirty, little yellow dress."
    icon_state = "dress_yellow"
    _color = "dress_yellow"
```

Points to the right place.  There's an icon for it.  It all looks right, but it still says J SUIT
![image](https://cloud.githubusercontent.com/assets/8550416/11560259/43700bce-998d-11e5-864a-97278e9d745c.png)
