### ISSUE TITLE
Allow derelict MoMMIes to name themselves again

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6848]
Why was this even removed, how is this any different than diona or station built MoMMIes/Borgs.

Really now.

**Comment by Probe1** [comment]
:+1:

**Comment by Ephx1** [comment]
Nexxy said it was bad
#6601

**Comment by Shadowmech88** [comment]
This is akin to removing OOC chat because a few players tend to IC in OOC.

All MoMMIs shouldn't be punished for what a few do.

**Comment by Probe1** [comment]
@N3X15 I don't foresee any problems with admins handling people using names to metagame.    Forced-borgings are much worse, players usually pick a name that toes the line like "I never asked for this"

**Comment by ghost** [comment]
@Ephx1
That's not an argument, anyone at any moment can write into chat any information they know, this doesn't mean chat is restricted to random words.

Anyone can also kill anyone for no reason,  that doesn't mean damage is removed.

This is just punishing all players because someone someday on the rare occasion that N3X1S was actually ingame made some bad name.

**Comment by Ephx1** [comment]
Just posting it here.
I'm sure N3X15 will change it or explain further here.

**Comment by FudgePucker** [comment]
pAIs, posibrains, and dionae nymphs can do the same thing, only they get to start on the station. So pAI 'AIISROUGE' is not worse than a derelict MoMMI 'AIISROUGE'? Only the AI and cyborgs will know about it. What is stopping a derelict MoMMI from talking over binary round sensitive information obtained OOC?

JUST BAN THE RULE VIOLATORS. Do we have a shortage of admins on or something? Because you just removed some for there being too many.

**Comment by AutismSpider** [comment]
Man have people forgotten about the metamouse?

This happen way more then it should with faggots using mouses to point out were the milf ais jump to etc.

**Comment by ghost** [comment]
Why is there a discussion tag when there was no discussion about removing something that nobody ever asked to be removed?

For all intents and purposes this is a feature loss.

> N3X15 is now in charge of merges.

Last time this was reported he outright closed the issue for no reason.

**Comment by 9600bauds** [comment]
I say go for it, clearly this hasn't stopped incidents such as TERREL IS TRAIT, and I doubt it ever will.

**Comment by gbasood** [comment]
If we really care we could just make the names pick from a list of russian shit

**Comment by ihadtoregisterforthis** [comment]
Russian letters don't work and translated makes no sense, like "usherp" currently for derelict crabchat.

**Comment by ghost** [comment]
Force everyone to random name or nobody at all. There's no reason to press it only on subgroups of certain jobs.

**Comment by FudgePucker** [comment]
No really, eggman left, again, so why not just revert it?
