### ISSUE TITLE
Box Research Outpost needs way more disposal bins

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#6851]
A lot of rooms lack them and trash piles up when players do xenoarch/research botany
After further investigation, the only garbage bin on the whole roid is the one in mining in the lounge that leads to the deathtrap.

**Comment by ihadtoregisterforthis** [comment]
> ˃![most unused disposals](https://cloud.githubusercontent.com/assets/13305885/11561405/082a0bbe-99a6-11e5-89c6-4d17d18d787d.png)

There isn't a lot of space in the roid for disposals. The one in the mining station is all you'll need in there.
I always thought one of the pipes at the entrance of the outpost was for disposals. Those things need better tagging.
I also thought that the narrow cave behind the vox outpost was meant for trash launching seeing the paper tube in there. That cave is a dead end.

**Comment by Probe1** [comment]
It wouldn't be that much work tbqh, I just did it in under 5 minutes with a really, really ghetto solution of having the disposal line end under the conveyor.  When trash exits it, it will poop out onto the conveyor and be ready to be shot into space when someone flips the switch.  This puts bins in the 3 highest waste areas easily.  If I wasn't half asleep and was trying my best I could do a much nicer job without too much more time.

The problem is that damn research outpost is either JAM PACKED in the rooms that need a bin or it's way too big in the rooms that don't.

![capture](https://cloud.githubusercontent.com/assets/8550416/11562258/e2058d24-999a-11e5-8894-006a631dc131.png)

**Comment by Kurfursten** [comment]
No lightswitch in xenobot room, when light tweaking is a thing for plants

Ban probe
