### ISSUE TITLE
Wrapping paper used as an unescapable way to ruin your round

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6852]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Currently when a player is wrapped in wrapping paper there is no possible way to escape it unless another player uses wirecutters on said wrapped player.
I feel this needs a way to be able to resist out of because its rediculously easy to get a hold of and has been used as a big griefing tool for the past two days where people would wrap multiple players up, causing a lot of annoying bullshit.
All it really takes is for someone to disarm a player and remove their headset, then stunlock them with more disarming and wrap them then the player is unable to escape and pretty much taken out of the round.
Needs a nerf so you can resist out of it like a welded locker.

**Comment by ihadtoregisterforthis** [comment]
Known issue, already reported in #6835 , >using bug reporter for feature request

**Comment by Exxion** [comment]
I bet the reason it's been used so much in the past couple days is that #6835 informed people of it
