### ISSUE TITLE
Metaclub Issues

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6854]
- No wires under the Xenobio shield generators
- Borer plasma injector defaults off with no way to enable it, no AAC
- No latex gloves in Xenobio
- R-Botany room is worse than the pre-fix one on Box
- Southern emitter in the SME room is not wrenched/welded
- No nearby oxy tanks for SME room (mostly just convenience, this is optional)

@probe1

**Comment by Exxion** [comment]
I don't think it's just that the Xenobio plasma injector's off. The plasma actually fails to flow through the pipes to even _reach_ the injector. Or at least it did last time I tried. An admin was unable to fix it and told me to just get a plasma can and open it in there.

EDIT: It flows through most of the piping there, but not the two pipes leading to the injector

**Comment by Probe1** [comment]
thanks bby
