### ISSUE TITLE
Unstable goo throws don't seem to be logged

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6855]
Checking mob attack logs and those "Mouse (497) was hit by book" admin logs, and nothing's shown.

Would help, considering this stuff seems to be a guaranteed kill in a single throw.

**Comment by ghost** [comment]
> Labelled within a minute of posting

PJB's on the ball today

**Comment by PJB3005** [comment]
No I just suck at focusing on anything and check the repo every 2 minutes.
