### ISSUE TITLE
Atmospheric devices round start in atmospherics are broken

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#6858]
To be more precise they are really fucked up.

Go ahead and try to use a multi tool on distro to waste.
Yup, broken as hell.
BUT WAIT IT GETS EVEN BETTER.
Wrench it up and wrench it down.
Yea, that's fucking right.
ITS STILL FUCKING BROKEN

**Comment by FudgePucker** [comment]
Wait a second, can't you multitool pumps or am I retarded?

**Comment by FudgePucker** [comment]
Still, it retains its name even after being wrenched up, its silly.

**Comment by Kurfursten** [comment]
Only thing with MULTITOOL_MENU can use multitools

e.g.: digital valves, scrubbers

Not a bug

**Comment by FudgePucker** [comment]
Eh but the label on the pump still sticks around when wrenched up. Meaning that you wrench it up it becomes just "volume pump fitting" then wrench it down in a different location it goes back to 'distro-to-waste'

**Comment by 9600bauds** [comment]
Is this still an issue

**Comment by Kurfursten** [comment]
It's not a bug, but yeah no one filled it as a feature

**Comment by PJB3005** [comment]
You can't control pumps with multitools.

**Comment by 9600bauds** [comment]
Looks like some comments were deleted here, I'm not even sure what the feature request here would be

**Comment by PJB3005** [comment]
@9600bauds for pumps to be controllable by the AAC and such.

**Comment by Kurfursten** [comment]
is everyone on the repo a collab now? that's like 3 in the span of 2 months

@9600bauds he wants two things:
- When you unwrench an instanced pipe (such as a specially named device like "air to distro" or "hot-cold bypass" it loses its special instanced name permanently)
- To be able to multitool link pumps to the AAC

**Comment by FudgePucker** [comment]
Its mainly the first one, I thought you could multitool pumps like an idiot
