### ISSUE TITLE
Deathnettle in tray sprite is nonexistant.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6862]

**Comment by 9600bauds** [comment]
how is this hapen

**Comment by PJB3005** [comment]
I don't know, somebody adminhelped it in game, and I VV'd the seed datum. The `icon_state` it's looking for was "deathnettle".

I should note that the DMI file containing the sprites, [`hydroponics.dmi`](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/icons/obj/hydroponics.dmi), is saturated.

**Comment by 9600bauds** [comment]
Couldn't reproduce in botany3 branch

**Comment by PJB3005** [comment]
Er, maybe it's related to the fact that it was in one of those soil trays?

**Comment by 9600bauds** [comment]
Could still not reproduce, untested in bleeding-edge, consider it fixed in botany3 ;^)

**Comment by PJB3005** [comment]
;^)
