### ISSUE TITLE
Really fucking weird singularity field on meta.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6864]
![](http://i.imgur.com/yeqUpBa.png)

Compared to box:

![](http://i.imgur.com/eqxHXGG.png)

Where the side field gens aren't on the same x or y axis.

**Comment by FudgePucker** [comment]
Hahahaha oh wow.

How did they miss this?

**Comment by Cisrox** [comment]
Dude that's fucking awesome because you could have 3 singularities

**Comment by FudgePucker** [comment]
Nah man you could have FOUR SINGULARITYS

How would that scale anyways?
What would produce more energy? Four stage three singularitys or one stage four or five singularity?

**Comment by clusterfack** [comment]
It's all fun and games till your singularity grows to 5x5 and eats a field generator

**Comment by FudgePucker** [comment]
> The emergency shuttle has been called. Reason: OH GOD FOUR SINGULOOSES OH SWEET MERCIFUL JESUS WHY?

STILL WORTH IT

**Comment by Probe1** [comment]
The real question is why hasn't this come up soooner

**Comment by BestName** [comment]
Because not everyone is a dumbass who can't figure out how to set that up properly.
Fun fact: that's how it used to be on box as well but newbies kept fucking up the setup and the coders changed it to make it easier.

**Comment by Probe1** [comment]
Well, at least I can mess with this instead of fixing bugs on Taxi.
