### ISSUE TITLE
Meta escape shuttle is BROKEN

### ISSUE THREAD

**Issue by CyberTropic** [d3athrow/vgstation13#6866]
That one corner tile doesn't change to blurry starts when the shuttle goes into hyperspace, like every other corner tile!
![image](https://cloud.githubusercontent.com/assets/5472923/11602403/0a1937e4-9aa8-11e5-8f36-0d5d950ce69d.png)

**Comment by Probe1** [comment]
can we fix it?

no its fucked!

**Comment by 9600bauds** [comment]
That's it
Shut it down

**Comment by unid15** [comment]
![](http://puu.sh/lK3F7/bc74c59b90.png)

Here's the issue

The turf at the bottom (the gray one) is added to the white one's underlays list, and shuttle corners don't update if there's a shuttle floor/wall in their underlays. Deleting the gray one will fix this immulsion devouring bug

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/11607318/57a455c2-9b0f-11e5-9b63-d804464711f3.png)
