### ISSUE TITLE
contortionist jumpsuit and plasmamen don't mix

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6867]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)
hey can you guys make it so us plasmamen can use the contortionist jumpsuit without having to remove our suit and everything and dying

**Comment by FudgePucker** [comment]
The plasma man suits for atmos techs act like atmospheric rig suits right?

There's a reason why you have to take off your exosuit, you have to have the proper pressure in the pipes you are crawling though or you take damage.

**Comment by ghost** [comment]
plasmamen have no rights
