### ISSUE TITLE
Attention New Command Report Created - FUCKING EAR BLASTING

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6868]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision dee5cb7b250b0f88e0fde862b2bb8472d38e485c 
> 
> General description of the issue
> The command report is
> Loud.
> As.
> Your.
> Mum.
> 
> What you expected to happen
> Reasonable volume command report
> 
> What actually happened
> My ears got fucking assblasted
> 
> Steps to reproduce if possible
> START ROUND
> GO DEAF

**Comment by ihadtoregisterforthis** [comment]
Can confirm

**Comment by Wizardcrying** [comment]
I might do a sound PR soon with adjustments and new sounds.

**Comment by ihadtoregisterforthis** [comment]
A theory was that this happens because the sound plays once for every comms console.

**Comment by 9600bauds** [comment]
QUALITY

**Comment by clusterfack** [comment]
It is very loud
