### ISSUE TITLE
Borer host got borged, borer stil alive in null loc hell

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6870]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> dee5cb7b250b0f88e0fde862b2bb8472d38e485c 
> 
> General description of the issue
> Was playing a borer. Was inside a host that got borged. I was still alive. I hit 'Abandon Host', and it succeeded, but I had no location
> 
> What you expected to happen
> Would expect that the borer would die, or that it would be ejected on the host's gibbing/borging
> 
> What actually happened
> Null loc hell
> 
> Steps to reproduce if possible
> Be a borer
> Get a host
> Have host be borged
> Leave host, check location.

**Comment by Probe1** [comment]
There are a list of ways that this can occur.  If a mob is in the contents of another mob and their parent mob is destroyed then they get sent to null.  

Another notable example is if a diona nymph is on someones head or in their pack and the person is gibbed through whatever means (usually bombs) then the nymph is sent to null.

**Comment by Shadowmech88** [comment]
Why can't we do something like have those functions first check the mob's contents, and if the mob contains a mob, move that mob's loc to the floor before the first mob is destroyed?

**Comment by gbasood** [comment]
Agreed, but I feel like this specific instance would cause the borer to die, rather than go to the floor.

**Comment by ihadtoregisterforthis** [comment]
> Infested a slime, it evolved, got sent straight to null hell.
> Infested a monkey, it got spiked, got sent straight to null hell.
> All in the same round

Did you know that borers can infest slimes? They show as 150% healthy.
