### ISSUE TITLE
Dylan's done it

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6878]
![hahahahahaha](http://i.imgur.com/FtpLzyR.png)
polyacid only works 10% of the time, but now it can melt ANYTHING
A N Y T H I N G

INCLUDING ITSELF

**Comment by ghost** [comment]
"no balance changes I promise"
fuck you dylan

**Comment by SonixApache** [comment]
Is this where we express our hate for the 'polyacid melts doors' joke?

**Comment by FudgePucker** [comment]
And this is why we should test dylans changes more.
Sneaky bastard is putting in balance changes under our noses.

**Comment by 9600bauds** [comment]
![smoke](http://i.imgur.com/9hHLIar.png)

pacid smoke

**Comment by SonixApache** [comment]
Could always just make a new, more potent, MUCH harder to make acid that does actually melt everything.

**Comment by 9600bauds** [comment]
fixed by https://github.com/d3athrow/vgstation13/commit/e07443bdb0a5c96b3287e7c6fb2dd1802e58c2d5
some people are too good for autoclose
I'm too good for close&comment

**Comment by FudgePucker** [comment]
I just can't help but feel disappointed in dylan for this one.

Did he even mention the acid changes in his PR? Because then this might have been avoidable.

**Comment by 9600bauds** [comment]
I'm thinking that this one could have been a honest-to-god mistake. Maybe he was experimenting with re-balances and accidentally staged a change he didn't mean to include in the PR.

I mean shit, I'd hope so.

**Comment by PJB3005** [comment]
Dylan. Not even once.

**Comment by Exxion** [comment]
Did it fucking melt an _area_ in that screenshot?

**Comment by PJB3005** [comment]
@Exxion nah I think it melted the airlock.

**Comment by Exxion** [comment]
OK good
That would have been horrifying
