### ISSUE TITLE
Test serbian is shit for testan

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6879]
Can't view variables
Can't add reagents
Random events always on
Power runs out immediately
You basically have to call the shuttle and wait 15 minutes to test anything because the map is bombed to all shit and singuloosed every time you join

**Comment by Shadowmech88** [comment]
Why not just give basic wishmin powers to everyone on the test server? VV and spawn and all that?

**Comment by FudgePucker** [comment]
The main problem is if you are trying to test something then someone shows up to fuck up everything.

Its already annoying enough having someone spawn themselves two spell books, imagine if they had ALL powers.

**Comment by 9600bauds** [comment]
If that's the case, you're gimping the whole server and making it an extremely inferior option to hosting it yourself, all because of the possibility of one person abusing powers (when they can already abuse powers!)

That's dumb, but that's just me.

**Comment by FudgePucker** [comment]
Eh I guess I agree

**Comment by Shadowmech88** [comment]
Besides, banning people from the test server for being an ass is already a thing. If they're causing trouble, go into the IRC and get an admin to handle it.
