### ISSUE TITLE
Mulebot running over Vox creates two (2) colors of blood

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6880]
![image](https://cloud.githubusercontent.com/assets/9827785/11609164/f58df2a6-9b4c-11e5-871f-5c44022ab500.png)

**Comment by PJB3005** [comment]
I think what's happening is that the MULE bot is creating blood when it runs over somebody, which is the red blood.

Then the vox bleeds because, well, obvious reasons, which causes the sky blue blood.

**Comment by Exxion** [comment]
Interestingly, I wasn't bleeding. Or at least if I was, I healed quickly enough that I only bled on that tile.
It wasn't a hacked Mulebot. I just wanted to see what would happen if I lied down right in front of it.

**Comment by Probe1** [comment]
That's the spirit of a true spessman.
