### ISSUE TITLE
Chisel is fuckening

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6882]
It opens up a dialog box asking you to enter what the image depicts. After you enter something, it adds a period to the end of whatever you entered and asks again, then appends the two messages together and puts them on the wall. It does not punctuate the second one.

It's probably supposed to behave approximately that way, but it's dumb.

![image](https://cloud.githubusercontent.com/assets/9827785/11609277/aa8e5cd8-9b50-11e5-9e6a-7fac235524f9.png)
![image](https://cloud.githubusercontent.com/assets/9827785/11609274/a005a8e8-9b50-11e5-9708-c161796aaeb7.png)
![image](https://cloud.githubusercontent.com/assets/9827785/11609273/93f70a1a-9b50-11e5-861d-f5c033bb666c.png)

**Comment by ihadtoregisterforthis** [comment]
To add to this being able to choose what icon will the engraving have would be nice.
If not I could open a new issue.

**Comment by Probe1** [comment]
I know what this needs.

A cancel button

**Comment by PJB3005** [comment]
_Dun dun duuuuuuuuun._

**Comment by Probe1** [comment]
When a man spends 3 hours learning how to add a cancel button the whole world starts looking like it needs it.

Anyway I'll take a crack at this now.  It looks like a really good learning experience.

**Comment by gbasood** [comment]
If you want to worry about punctuation, you could check if the inputted message contains a period, too.

If I input "A coder." I'd get two periods, that's just plain silly.
