### ISSUE TITLE
Holodeck creates infinite plasma and thus infinite pressure

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#6883]
Holodeck when set to atmospheric burn simulator creates infinite plasma, killing the station and serb.

**Comment by Exxion** [comment]
> 200MPa (yes, MPa, not kPa) in Arrivals before the firelocks managed to close

The worst part is that I've seen much, much worse
I've actually seen 13-digit pressures
(In scientific notation, of course)

**Comment by AutismSpider** [comment]
Did some one unnerf the burn sim? use to have a cap on much plasma it made then stop making any

**Comment by 9600bauds** [comment]
Couldn't reproduce, it did this thing instead
![dreamseeker_2016-01-25_22-02-24](https://cloud.githubusercontent.com/assets/6526157/12569656/9a5a0876-c3af-11e5-8d6d-238503188efc.png)
It says oxygen instead of plasma which is weird, but it's definitely not infinite pressure

**Comment by PJB3005** [comment]
Wasn't this confirmed to be a lack of changeTurf(),  causing ZAS to glitch out?

**Comment by SonixApache** [comment]
Doesn't appear to be an issue anymore.
