### ISSUE TITLE
Can't wrench down singulo shit on catwalks

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#6887]
**Revision**
990f33084a6df74907e12b10d1d7ab95b95efd63 

**General description of the issue**
If you unwrench a field generator or the singularity generator (and probably a bunch of other shit) loose from a catwalk, you cannot wrench it back.

**Comment by PJB3005** [comment]
This is all @dylanstrategie's fault.

Also, dupe of #6243
