### ISSUE TITLE
Voice changer doesn't hide identity when chameleonized as other mask slot item that also doesn't hide identity

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6890]
Disguising voicechanger as a cigarette will now still show your real identity on examine, making the disguise feature nearly useless as there are only few of the available choices that hide your identity.

**Comment by Probe1** [comment]
i don't get it.  it's a cigarette.  how would it conceal your identity?

**Comment by ghost** [comment]
Space magic, just like everything else.

**Comment by Kurfursten** [comment]
No, this is a bug fix, this is intentional. We just fixed this from the previous state, you can't BOTH call it a bug for opposite conditions.

Before people were upset because the cigarette form did hide your face, now you're upset because the cigarette form doesn't hide your face?

Not a bug

**Comment by ghost** [comment]
People were upset it hid the glasses sprite, not that it hid identity.

**Comment by Kurfursten** [comment]
It hid glasses as a function of covering the face (which is what hides your identity)

**Comment by ghost** [comment]
Then perhaps those two functions should be separate.

**Comment by 9600bauds** [comment]
Re-purposing issue to be more clear. For the time being you can get a cigar to hide your identity by setting the voice changer to something that does hide identity, putting it on, and then chameleonizing it to a cigar without taking it off, honk.
