### ISSUE TITLE
Impossible to upgrade freezers with the RPED

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6893]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d92f5eb71670182435eb5b129633ebdddd527f25 
> 
> General description of the issue
> In order to use the RPE on a freezer the freezer must be anchored, however you can't open the maintenance hatch if the freezer is anchored. Meaning it's impossible to upgrade a freezer with RPE.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Probe1** [comment]
it was never a feature to begin with @PJB3005

**Comment by Kurfursten** [comment]
Note that you CAN upgrade freezers the manual way

So you know, title accuracy
