### ISSUE TITLE
Round Start Spawn Not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6894]
(WEB REPORT BY: infoman567 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> At the start of the round, even though set ready. Was not spawned into the game. This has happened more than once.
> 
> What you expected to happen
> Spawn at Roundstart
> 
> What actually happened
> Did not spawn at roundstart and forced to pick unwanted roles
> 
> Steps to reproduce if possible

**Comment by SonixApache** [comment]
You sure you don't have 'return to lobby if preference unavailable' enabled?
![Occuption preferences](http://puu.sh/lLXcO/1c684c1ba9.png)

**Comment by PJB3005** [comment]
Chances are a response isn't gonna happen because it's a web report, sadly.

**Comment by clusterfack** [comment]
If this is a bug this gives none of the information required to fix it since this closely parallels a feature that does exist and is working CORRECTLY.

**Comment by ghost** [comment]
@clusterfack

I can confirm this happening to me a few times, it must have something to do with "declare ready" button displaying you're ready even when you're not.

I'm pretty sure the UI window doesn't refresh itself correctly.

**Comment by SonixApache** [comment]
still a thing, #6913
