### ISSUE TITLE
Biomass Issues

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#6904]
- Still spreads to windows, in the annoying way that space vines once did. You have to painstakingly smash out the window from under the big sprite to get at it.
- Has no bullet_act, the mighty gatling gun is laid low by biomass

**Comment by Ephx1** [comment]
Considering their only gimmick is to block off, I think the window spreading should be kept.
Otherwise they're just shittier vines.

**Comment by 9600bauds** [comment]
They ARE shittier vines pretty much

**Comment by nuklearcellphoneg** [comment]
Remove biomass entirely, it's silly.
