### ISSUE TITLE
Chaplain meme titles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6906]
(WEB REPORT BY: harsetheef REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Upon choosing one of the meme religions for the job title (Syndicate), I was updated in the crew manifest, but not my ID and pda.
> 
> What you expected to happen
> To be a Syndicate Agent
> 
> What actually happened
> I was just a sad Chaplain without a gimmick
> 
> Steps to reproduce if possible
> Enter religion as Syndicate upon start as chaplain

**Comment by PJB3005** [comment]
I blame dylan.

**Comment by Faptastic** [comment]
Seems to be working fine if you latejoin, just tried it. ID & pda are correct & I'm properly attired.
Is it normal to be listed as both the chaplain under civ and 'Syndicate Agent' under misc at the same time?

**Comment by ihadtoregisterforthis** [comment]
˃meme titles

**Comment by ghost** [comment]
Changing job titles after the round started is pretty uppity, might need more sanities

**Comment by 9600bauds** [comment]
Works correctly on my end
