### ISSUE TITLE
Deathnettle examine spacing

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6909]
![image](https://cloud.githubusercontent.com/assets/9827785/11637370/ec5ed0bc-9cee-11e5-8a0d-a63bdbfa0857.png)

The **glowingnettle incites _ragein you just from looking at it!_**

**Comment by Probe1** [comment]
what a goofy description.

**Comment by 9600bauds** [comment]
ugh I need to axe deathnettles and re-make them entirely so as to not be so horrible
