### ISSUE TITLE
PDA menu takes seventeen years to open

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6910]
OK fine it's more like 2-3 seconds, but it's still annoying.
It responds just fine once open, but opening it takes forever.

**Comment by PJB3005** [comment]
It's this or lag on the login screen.

**Comment by Exxion** [comment]
As in the screen when logging onto the server? I don't think an extra 2-3 seconds would be noticed on top of the minute or so that already lags.

**Comment by PJB3005** [comment]
@Exxion right now login lag is like, 20 seconds, and we'll probably cut it down to 0 at some point.

**Comment by ihadtoregisterforthis** [comment]
Yes, the login screen lag is back.
When it got fixed, the first days it was instant. That quick reaction faded back into the original state. At least _on my machine_.

**Comment by Kurfursten** [comment]
Mine takes a long time to open but only the first time. After that it responds normally.

**Comment by Exxion** [comment]
Yeah, same
I just didn't notice that because I usually only open it once

**Comment by ihadtoregisterforthis** [comment]
Did a quick test on the test server, and got twenty seconds to character setup and forty for PDA. That's as much as four tens. _Again, on my machine_

**Comment by Exxion** [comment]
Wait
Forty to open the PDA?

**Comment by ghost** [comment]
I believe, and @PJB3005 can correct me if I'm wrong here, but this is because instead of rendering each PDA screen when it is clicked, it instead pre-loads it when you first open it, so it's the fault of your internet to receive those icons rather than anything server-side.

**Comment by PJB3005** [comment]
@DrCelt nope, not even close.

What happens is that to fix login lag, we send clients things like javascript scripts, css style sheets and such when they're first needed, not all at login (like it used to be).

So obviously when you first open your PDA (it's on a round per round basis, FYI), the files get sent, and it takes a while (thanks BYOND).

Also @ihadtoregisterforthis are you serious? **Forty** seconds? Holy shit something's up.

**Comment by ghost** [comment]
@PJB3005 

> nope not even close

b-but that's exactly what I said! (kinda)

**Comment by PJB3005** [comment]
@DrCelt no, it's not, at all, what you said is that before I changed it was better, and it was more specific on asset sending (it wasn't)

Also it's not that big of a fault of people's internet, BYOND is shit and slow at sending assets.

**Comment by 9600bauds** [comment]
The template is 49kb, is there no way to make it download with the ~69mb of resources? Alternatively, since everyone has a PDA and anyone can use it, what about sending the template 30 seconds before the game starts?

**Comment by clusterfack** [comment]
Kek bauds why do you think we started using an asset cache in the first place? Downloading an asset doesn't let you interact with any menus until it completes. We ended up with a full 3 minutes of asset downloading before roundstart and no one could set up characters.

**Comment by 9600bauds** [comment]
And isn't there any way to just make it download once per update rather than every round? I mean shit, literally any way

**Comment by clusterfack** [comment]
The system we have now is the best of a bad list of choices

**Comment by 9600bauds** [comment]
Technically, the least bad choice would be Not Nano
Still though, no way to make the templates download with the rest of the resources?

**Comment by PJB3005** [comment]
But it's not nano

**Comment by 9600bauds** [comment]
![explorer_2016-03-04_15-31-22](https://cloud.githubusercontent.com/assets/6526157/13536356/35a8f6de-e21e-11e5-8624-963bb280e9a2.png)
I believe this file is the problem

**Comment by PJB3005** [comment]
Hah not really don't even know why we have that file, probably something somebody copied from Bay without thought.

**Comment by 9600bauds** [comment]
what

**Comment by clusterfack** [comment]
Look at pda games if you want a clue as to why it takes forever to download the resources

**Comment by PJB3005** [comment]
@9600bauds the PDA isn't nanoUI, it's string builder.

**Comment by Zth--** [comment]
Remove those stupid games if they're laggy

**Comment by PJB3005** [comment]
They are actually fucking terrible on the server's CPU but the assets for the game only get sent when you open the games themselves so they don't contribute to the PDA issue. 

There's some optimization to be done though, a client never needs all assets at once (unless they're like, Captain), and even the PDA maps get sent always.
