### ISSUE TITLE
Occasionally when readying up you won't get put in the game

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6913]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision bd2781b86b7997f1e011b4821dbe9b0424d64609
> 
> General description of the issue
> On rare occasions after readying up im not put in the game and remain in lobby
> 
> What you expected to happen
> Go into the game, get my traitor rolls
> 
> What actually happened
> I'm still in the lobby
> 
> Steps to reproduce if possible
> hope you get random chance for this to happen
> 
> ALSO
> i do not have return to lobby if prefs unavailable is on

**Comment by Shadowmech88** [comment]
I assume you have "Become assistant if prefs unavailable" active?
There are a maximum number of assistants allowed on the station, scaling with the number of active Security members.
If your job prefs are unavailable, and all the assistant slots are filled up, it would leave you in the lobby.

**Comment by Kurfursten** [comment]
I have the opposite problem. Sometimes I select 'return to lobby if job pref unavailable' and don't get bounced back, instead stuck with random job.
