### ISSUE TITLE
Diona Bluespace Wheelchair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6915]
(WEB REPORT BY: assdad211 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

bd2781b86b7997f1e011b4821dbe9b0424d64609

> General description of the issue

If you're a diona nymph and you buckle in to a wheelchair, and someone picks you up, as soon as you move out of their grasp you'll teleport back to the wheelchair.

> What you expected to happen

To be placed on the floor as normal

> What actually happened

I teleported back to the wheelchair

> Steps to reproduce if possible

Be diona, buckle in wheelchair, be picked up, have him move away, resist out of his grasp

**Comment by PJB3005** [comment]
Shitcoder didn't assume dionaes could be buckled to shit, typical.
