### ISSUE TITLE
Changelings get disability on transform

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6920]
Transform seems to cause disabilities even when your victim didn't have any.

**Comment by PJB3005** [comment]
I haven't checked the code thoroughly yet, but this sort of sounds like something that'd be intended.

However, it might be possible that some shitty hardcode in DNA code has a chance to mess with your genes any time your DNA changes.

Also, I can confirm this myself.

**Comment by ghost** [comment]
I would question the reasoning behind implementing mandatory regeneration after each transform just so you don't get a seizure or something worse.

**Comment by gbasood** [comment]
Reminds me of DNA fuckery that happened to me when I was playing vampire once (#4601). Maybe DNAcode is just fucky.

**Comment by DeityLink** [comment]
Dormant gene awakening made explicit by #29901
