### ISSUE TITLE
You can almost hear (yourself) talking (again).

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6921]
Return of #3925
While unconscious, people's messages and emotes are replaced by "You can almost hear someone talking..."
The issue is that most of the time you're unconscious you also involuntarily make a lot of emotes yourself (gasping in crit, mostly), which results in a constant "You can almost hear someone talking" from your own emotes, even when you are the only person in the room or the only person alive in the universe.

**Comment by Zth--** [comment]
Spooky

**Comment by ghost** [comment]
can whoever fixes this fix the admin deadchat appearing as "you can almost hear someone talking" too?

**Comment by 9600bauds** [comment]
This was tagged as a bug last time.
