### ISSUE TITLE
Wrapper destroys janicart upgrade

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6922]
(WEB REPORT BY: pedonymous REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 30a721a4c7d2df303c8d732bc24067ce65e7dfce 
> 
> General description of the issue
> Janicart upgrade disappears when attempting to wrap
> 
> What you expected to happen
> Wrapped item
> 
> What actually happened
> FUCKING GONE MAN
> 
> Steps to reproduce if possible
> Try to wrap a janicart upgrade

**Comment by Exxion** [comment]
Sounds like you suck at wrapping
