### ISSUE TITLE
cargo's conveyor switches

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#6923]
on box station, a couple of conveyor switches inside cargo are now set as bidirectional by default and they are troublesome to use this way, so you need to change the conveyor switches behaviour using a multitool at the start of the shift; would be better if the are set by default on one direction as before.

the affected switches are the one inside the delivery office and the ones tagged as QMLoad2 and QMLoad3 near the supply shuttle dock.

EDIT: i want to specify that the other conveyor switches near dock, the ones tagged QMLoad, are set by default at one direction, as it must be.

**Comment by PJB3005** [comment]
Goddamnit @probe1 I even asked you in IRC why the one directional subtype had no special code anymore.

**Comment by Probe1** [comment]
Not really sure how I could have done it @PJB3005.  I made a conveyor switch the active object and gave it a new id tag.

**Comment by PJB3005** [comment]
@Probe1 your "oneway" mapping subtype had no specific code; it was indentical to the normal type, as such any previously oneway ones are now multi-directional.

So basically you blew it.

**Comment by uazuaz** [comment]
i want to specify that the other conveyor switches near dock, the ones tagged QMLoad, are set by default at one direction, as it must be.

**Comment by Probe1** [comment]
¯\_(ツ)_/¯ maybe our code shouldn't catastrophically fail if someone places a conveyor switch.  It's not like it said anywhere, ever, not to do that and I didn't think that placing one would cause the end of the world.

**Comment by 9600bauds** [comment]
Caused by the switches not having convdir set in mapping
Set to -1 to restrict lever to only left pulling, +1 to only right pulling

**Comment by PJB3005** [comment]
> in mapping

Nice meme, fix the subtypes or gtfo, no instances.

**Comment by 9600bauds** [comment]
Literally every single part of conveyors is done in mapping and all of it is shit.

**Comment by PJB3005** [comment]
@9600bauds why do you think I tell EVERYBODY TO STOP USING INSTANCES?
