### ISSUE TITLE
Round-start light fixtures are fucked.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6924]
This includes the tubes that come out of them.

The path to their light tube type they have is completely ignored, so the fixtures are resorting to their default path.

It gets even more shitty because light tubes you take out of a fixture get their strength variables set to that of the light.

So the station's dim as shit.

**Comment by Exxion** [comment]
Light fixtures need to be remade to use an internal light rather than just a copy of all of a light's variables

**Comment by PJB3005** [comment]
@Exxion the roundstart ones don't even copy the variables, which is even worse.

**Comment by Intigracy** [comment]
haha oldcode
