### ISSUE TITLE
Attempting to put baggies back into a core sampler, makes both dissapear.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#6925]
Goddamnit.

**Comment by clusterfack** [comment]
??? Really?

How, why?

I've been hearing about lots of things disappearing mysteriously recently, like an Mimi that just disappear ed from someone's backpack.

**Comment by PJB3005** [comment]
@clusterfack I think this is due to @gbasood's qdel thing (I don't blame him for breaking this, xenoarch's fault for shitcode), he fixed a `del` in the core sampler's baggie insertion code, so the baggie doesn't get deleted instantly anymore. As such, the baggie's `afterattack()` runs (lack of return 1 on the sampler), and the baggie, which is in nullspace from being `qdel()`'d, captures the sampler...

THANKS CAEL.

**Comment by gbasood** [comment]
So basically, the best solution to this would be to do a 'return' after `qdel`'ing the baggie to prevent `afterattack()` from being called, right?

**Comment by PJB3005** [comment]
@gbasood a `return 1`, yes.
