### ISSUE TITLE
Sleep is too hardcore

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6926]
Sleeping makes you knocked out so good it takes a full minute of hugs to wake up.

**Comment by clusterfack** [comment]
Strange, could be that something is wrong with sleep, or perhaps wrong with the mob process

**Comment by ghost** [comment]
Sleep has always been strange. If you're not careful, you can end up stuck in sleep for the rest of the round

I wish we had toggle sleep + forced sleep, but at that point it seems like arcane magic

**Comment by 9600bauds** [comment]
Not a bug, the verb is just very hardcore. I looked into this previously and apparently it seemed to always have been that way.
