### ISSUE TITLE
PDA pinpointer doesn't update its direction/distance without having to spam on/off/on to get updates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6928]
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777)

> Revision 82fae97d2167d57f1dc35477edb97570d84e7df3 
> Alright so if you're running around with the nuke disc pinpointer and it's to the east, if you run far enough N/S/E for it to change direction the pinpointer's arrow will change. But the pda pinpointer's arrow will not change for near/far or firection without being turned off/on. checked in hand, pocket, and bag. Unlike the nuke pinpointer.It also doesn't update when somebody leaves the z-level leading to a wild goose chase across asteroids until you realize it doesn't update.

**Comment by clusterfack** [comment]
I'll look at this too, probably just an inheritance issue

**Comment by Intigracy** [comment]
close
