### ISSUE TITLE
rainbow

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6930]
![rainbow](https://cloud.githubusercontent.com/assets/13305885/11664891/f1b44766-9dc2-11e5-9923-e767e82b7a45.png)

Misleading information? Lousy work? Unreasonable oversight?

**Comment by PJB3005** [comment]
Erm...

So, if you don't set a name on an atom, BYOND defaults to the last part of the type path.

So...

I would not be suprised if the jumpsuit just has no name at all, and the type path ends in `.../rainbow`

**Comment by Shadowmech88** [comment]
I thought if you don't set a name, it inherits the name of its parent?

**Comment by PJB3005** [comment]
@Shadowmech88 and what if the parent has no name?

Continue said logic ad infinitum.

**Comment by ghost** [comment]
rainbow jumpsuit

Whatever rainbow-related meme comes up

Simple fix, now to implement it

**Comment by Shadowmech88** [comment]
@PJB3005 I assume jumpsuits are a child of `/obj/item`?
`/obj/item` Has the name "item."

**Comment by FudgePucker** [comment]
Are the holodeck items the items themselves, but just some type of vareditting to make them disappear after leaving the holodeck, or are they entirely new items?

**Comment by PJB3005** [comment]
@FudgePucker I don't know how holodeck items work, but it's almost certainly shitcode.

**Comment by Exxion** [comment]
Considering holodeck windows take up their whole tile as far as contact is concerned and you can't put things on holodeck tables, I'd say yes, it's probably shitcode.

However, if memory serves, the CentComm beach rainbow jumpsuit also has this issue, so it's not that

**Comment by ihadtoregisterforthis** [comment]
The one hidden in cargo is the same. Other rainbow colored items have their own description and name.
