### ISSUE TITLE
Plasmaman's sprite has a head, when they're beheaded

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6931]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 82fae97d2167d57f1dc35477edb97570d84e7df3 
> Plasmaman need an updated - headless - sprite
> 
> Steps to reproduce if possible
> be a plasmaman and get beheaded see your sprite still has a head

**Comment by ihadtoregisterforthis** [comment]
Adding to plasmamen sprites, you can see a part of the leg poking from the suit on east and west directions.

![plasma on plasma](https://cloud.githubusercontent.com/assets/13305885/11726171/367b760e-9f5c-11e5-9225-fcabefed4bc1.png)
<sub><sup>Unless that's not the leg *wink *wink </sup></sub>

**Comment by TheEliminator16** [comment]
Just tested this. Turns out that NO limbs actually display as being removed on the sprite. I took one look at plasmaman code and noped the fuck out.

**Comment by ihadtoregisterforthis** [comment]
I believe extirpating the `whole` state on `r_plasmamen_sb.dmi`, the first of the file, can fix this.

For the leg sticking out either resprite the leg or resprite all suits. I'd go for the suits.
