### ISSUE TITLE
You cannot stack disposal pipes and regular pipes anymore

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6932]
(WEB REPORT BY: dylanstrategie REMOTE: 158.69.55.2:7777)
Simply tells you that there is already a pipe at that location

**Comment by PJB3005** [comment]
I highly doubt it's disposals pipes and normal pipes causing conflicts.

**Comment by clusterfack** [comment]
This definitely didn't happen to me in testing
