### ISSUE TITLE
Disappearing machine components on deconstruction

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6933]
(WEB REPORT BY: puglife REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 82fae97d2167d57f1dc35477edb97570d84e7df3
> 
> General description of the issue
> I tried to crowbar out the reverse engine's console screen to make an autolathe. Like an idiot I crowbared more than once before the operation completed.
> 
> What you expected to happen
> Nothing bad
> 
> What actually happened
> When the second operation completed, all the components disappeared/despawn/whatever you call it, leaving just a wired frame.
> 
> Steps to reproduce if possible
> screwdriver machine, crowbar electronics and crowbar again before operation completes

**Comment by gbasood** [comment]
oh look another thing probably introduced by the qdel change

**Comment by BarneyGumball** [comment]
Could not reproduce.  Likely been fixed.
