### ISSUE TITLE
Make OOC not accept messages starting with ;

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6935]
Cut down accidental ick ock
Cut down "accidental" ick ock
Profit

**Comment by ghost** [comment]
A bit harsh. Maybe a confirmation message

**Comment by 9600bauds** [comment]
That too

**Comment by Iamgoofball** [comment]
we did this at tg

very good shit

**Comment by ghost** [comment]
What about ;-;

**Comment by 9600bauds** [comment]
You can stutter like a faggot before the ";_;" emoticon and it conveys the message more clearly

: also needs to go, to get rid of ":g absorbing pomf in dorms" both ironically and not

**Comment by ghost** [comment]
I think this is an idiotic idea.

Prompt (with a setting for no prompt) would indeed be much better.

**Comment by ihadtoregisterforthis** [comment]
I suggest making `;` redirect to `/say ;` instead, if possible, both for OOC and /me. This can go with a prompt.

**Comment by Probe1** [comment]
do it and ignore termedclepe because

**Comment by nuklearcellphoneg** [comment]
C o d e    i t   p l s

**Comment by clusterfack** [comment]
;^)

**Comment by nuklearcellphoneg** [comment]
As a side note, I have seen a legitimate OOC :G Message.

I mean, people kind of automatically instantly make the :G Absorbing dorms etc jokes, but you know, wouldn't hurt to associate : as well.

**Comment by 9600bauds** [comment]
![firefox_2016-02-04_17-17-54](https://cloud.githubusercontent.com/assets/6526157/12828388/47ec8f58-cb63-11e5-899e-1654de3d4812.png)
when
