### ISSUE TITLE
Problem with (advanced) toolbelts

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6936]
This might potentially affect things all the way up to base storage items

"You put the the something into the storage item"

**Comment by 9600bauds** [comment]
What?

**Comment by PJB3005** [comment]
I think dylan in all his baguette-ness is trying to say that instead of you getting the message "you put the X into the toolbelt", you get "you put something into the toolbelt."

**Comment by Zth--** [comment]
No. He's getting duped "the"

**Comment by PJB3005** [comment]
Oh.
