### ISSUE TITLE
Mech syringe guns don't stop trying to make reagents after the mech is destroyed.

### ISSUE THREAD

**Issue by Faptastic** [d3athrow/vgstation13#6944]
17:17:28 Runtime detected
Cannot read null.total_volume at medical_tools.dm:660
 proc name: process (/datum/global_iterator/mech_synth/process)
  source file: medical_tools.dm,660

If a mech with a syringe gun is set to constantly produce reagents, even after the mech is wrecked  the gun will still try to make more, resulting in the above error message every 10 seconds or so.

Steps to reproduce:
Make an Odysseus, equip it with syringe gun, set the gun to produce reagents constantly.
Proceed to have the mech destroyed and turned into wreckage, experience the above error.

I even deleted the wreckage and it carried on.

**Comment by 9600bauds** [comment]
spoopy

**Comment by 9600bauds** [comment]
Add an if(!chassis) return check on the synthetizing, also probably qdel contents when the wreckage is qdel'd

**Comment by ghost** [comment]
Seems to already have an if(!chassis) check. Probably need to qdel contents.
