### ISSUE TITLE
Emitters not working properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6946]
(WEB REPORT BY: golfer45 REMOTE: 158.69.55.2:7777)
A couple of emitter issues
1. Emitters do not charge feild generators unluss, the emitter is first turned on, then the field fenerator is moved in the way of the beam and welded to the floor and turned on. It seems emitters for the singularity are not effected by this and only thoose that are place by a player. This lead to an issue in which a singularity and field was set up using the workround however power turned off for half a second cuasing the emmiters to no longer power the field, which of course led to the singularity escaping.
2. Emitter beam doesnt update when a field generator is moved out of the beam. If a feild generator is unwelded from the floor and moved while the beam is still on the beam will stop in midair where the feild generator used to be.
3. Emitter beam doesnt update when blob is killed. A emitter beam pointed at a blob will stop in midiar where the last blob was after the bean kills it.

**Comment by PJB3005** [comment]
Wait if this can cause **_field generators to stop working**_, then this is some serious shit.

**Comment by ihadtoregisterforthis** [comment]
[OH GOD IT'S LOOSE] more literal than ever

**Comment by FudgePucker** [comment]
Does this also effect the SME?
I would imagine so because the problem is the beam not hitting the field gen and the beam not updating

**Comment by Intigracy** [comment]
Singulo field gens get charged but don't update their icon until turned on.

Haven't tested other parts of this.

**Comment by Kurfursten** [comment]
@Exxion None of these bugs are still things
