### ISSUE TITLE
Cant attach exosuit beacons to mechs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6948]
(WEB REPORT BY: cptwad REMOTE: 158.69.55.2:7777)

> Revision: cb4533a42198f2c94c687bcaab66677a43128332 

Built gyjax would not accept tracking beacons being attached to it. That is terrible because you can use them to stop shitters in mechs at a distance.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by 9600bauds** [comment]
You need to open the panel before you can attach an exosuit beacon now.

**Comment by PJB3005** [comment]
Unless @CptWad can be more specific about it it'll stay as not a bug.

**Comment by CptWad** [comment]
Oops. Well then shut her down.
