### ISSUE TITLE
Smelelele and map vote announcement is delayed long after round end

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6949]
You can vote immediately (the panel sometimes pops up on its own, and sometimes doesn't) and see round score, but the smelelele and the actual message announcing the map vote is pushed back anywhere from a few dozen seconds to way after round end

Might have something to do with the smelelele being accidentally queued after another sound (maybe the round-end radio, which replays when the shuttle docks to Centcomm) and only firing the rest of the procs once it's fired

**Comment by 9600bauds** [comment]
SMELELE is urgent please fix

**Comment by gbasood** [comment]
The sound is currently played after everybody gets their vote popups I think.
So it SHOULD be playing immediately after:

``` DM
to_chat(world, "<font color='purple'><b>[text]</b><br>Type vote to place your votes.<br>You have [ismapvote && ismapvote.len ? "60" : config.vote_period/10] seconds to vote.</font>")
```

fires

**Comment by 9600bauds** [comment]
SMELELE is urgent please fix

**Comment by gbasood** [comment]
Seriously why the fuck is this happening
This is pretty important

**Comment by 9600bauds** [comment]
Let's try what you said

**Comment by clusterfack** [comment]
Someone post some gameticker code for ending the round

**Comment by gbasood** [comment]
all round ends are handled on per-gamemode basis
scoreboard code handles delivery of round end report on a per-client basis as well as, in theory, the SMELELELE

**Comment by ghost** [comment]
After testing due to web server being dead, I can confirm that the smelelele plays on time if, and only if, all media instances are deleted at any point (includes Jukeboxes and Radio Transmitters)

**Comment by 9600bauds** [comment]
SMELELE is urgent please fix

**Comment by PJB3005** [comment]
I HAVE A FIX UP NERD

**Comment by 9600bauds** [comment]
Thank you

**Comment by clusterfack** [comment]
Think this is fixed, someone make a new issue otherwise.
