### ISSUE TITLE
You can break the AME if you assemble it 2fast

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6952]
![bug_report_ame](https://cloud.githubusercontent.com/assets/6137403/11704326/2ac19b38-9ee7-11e5-92da-064d519ac540.png)

**Comment by 9600bauds** [comment]
2fast2quick

**Comment by clusterfack** [comment]
There's a report on this from like 2 days ago smh

**Comment by PJB3005** [comment]
Closing because dupe of #6916

**Comment by Zth--** [comment]
2fast4u

**Comment by PJB3005** [comment]
Wow I never closed this.
