### ISSUE TITLE
AI Eye moves around at Mach 10 and Observers are slow as dicks

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6953]
@clusterfack 

This is caused by the recent tickrate changes and missing tickrate compensation for the AI, and observers not being given a special speed

**Comment by clusterfack** [comment]
Yes AIs need some tick compensation, also by observers being slow do you mean generally or after the tick lag change

**Comment by ghost** [comment]
to be fair right can we make this a setting for both AIs and observers? some people may prefer slow and steady others prefer gottagofast and there's no reason why you can't have either

**Comment by ghost** [comment]
Generally clusterfack

**Comment by ghost** [comment]
This was fixed as far as I am concerned, observers can now pick a speed, open a new issue if AIs still go too fast
