### ISSUE TITLE
Borer QOL improvements

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#6955]
- Remove the message shown on climb attempt for the host. It removes any stealth brain tunneling.
  `<span class='sinister'>You feel something slithering up your leg...</span>`
- Allow borers to control monkeys, and maybe debrained _carbons_
- A simple message to check if a borer on the floor is braindead would be the nicest

pls

**Comment by Shadowmech88** [comment]
> It removes any stealth brain tunneling.

Borers are meant to be fleshy pAIs now, so I think the reasoning here is that you shouldn't need to stealth tunnel, seeing as you should only have good intentions for your host.

**Comment by Ephx1** [comment]
Most people don't know borers are nice now, and immediately back away with the force of one thousand metas. It's not as though you could explain that you're nice either.

**Comment by ihadtoregisterforthis** [comment]
Stealth borers are fun for situations like
- Confusion over sudden voices in your head
- Silent guardian brain angel
- Surprise communist propaganda right into your gray matter
- Screaming remorse to improve petty RP about war sequelae before CisRox starts spamming in LOOC

Besides is a healthy way of training for other stealth missions.
<sub>At the very least don't make it sinister purple.</sub>

**Comment by Kurfursten** [comment]
I don't like the idea of removing the text. Some people don't want to play with borers and it can be a huge hassle to stop a borer if you don't even know it's entering. 

Borers should find someone who wants a borer instead of trying to sneak into someone who doesn't want one. Removing the text will only add to paranoia surrounding them, especially because we still have the occasional borer player that ODs their host on hyperzine.

**Comment by gbasood** [comment]
> Borers should find someone who wants a borer instead of trying to sneak into someone who doesn't want one. Removing the text will only add to paranoia surrounding them, especially because we still have the occasional borer player that ODs their host on hyperzine.

Problem being that borers have no way to communicate, and people still thing they're antags, and will murder them on sight because they act EXACTLY like the antag borers until they're actually infesting you
