### ISSUE TITLE
Surgeons witchtools and display cases

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6957]
(WEB REPORT BY: golfer45 REMOTE: 158.69.55.2:7777)
Putting one in a display case turns it into the active tool.

**Comment by 9600bauds** [comment]
~~The active tool also comes out if you accidentally click the surgery table.~~ not anymore
They're kind of shit

**Comment by BarneyGumball** [comment]
I couldn't put activated switch tools in display cases when testing.  Was probably fixed.
