### ISSUE TITLE
Add Taps to the sound synthesizer

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6958]
![image](https://cloud.githubusercontent.com/assets/9827785/11708463/7f33eae0-9edd-11e5-8db6-e23ef6a13828.png)

**Comment by CyberTropic** [comment]
The way you select sounds from the synthesizer needs to be reworked, maybe into a popup window where they are all listed together. It's a pain in the ass to sit there scrolling through all the sounds to get to trombone, and then scroll back over to laughter, meanwhile everybody already walked off and the comedic timing is COMPLETELY RUINED! Please fix!

**Comment by Exxion** [comment]
That too
But Taps is also very important
