### ISSUE TITLE
Free Roburgers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6959]
(WEB REPORT BY: assdad211 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

666678ecda4be02cff456ff778ab632ad8c705e7 

> General description of the issue

Robotic Transformation virus is broken. If you eat a roburger or whatever and get the robotic transformation disease, it never progresses beyond stage 1, thus you never become a borg.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by FudgePucker** [comment]
People were getting borged after eating one last night. Needs more testing

**Comment by assdad211** [comment]
I ate one as craptain accidentally and it was at 1/5 stage for an hour or more yesterday, I ate it alongside an enormous amount of other food if that matters.

**Comment by Kurfursten** [comment]
Unable to reproduce on test server. Very rapidly transformed into a borg.

The only thing I can think of is that maybe you got very lucky dice rolls for progression or you unwittingly also ate some spaceacillin at some point, and that stuff hangs around like glitter.

**Comment by clusterfack** [comment]
Fixed at some point
