### ISSUE TITLE
"Stay alive until the end" objective failed while alive

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#6961]
Revision: 666678ecda4be02cff456ff778ab632ad8c705e7 

> General description of the issue

I failed my "Stay alive until the end" objective as a AutoTraitor'd AI (made traitor during the round), even though I was alive. I had never been damaged. I was made an AI during the round.
![stay alive until the end](https://cloud.githubusercontent.com/assets/5942183/11716746/5570673c-9f4c-11e5-9b9f-edb17c6c80e8.JPG)
As it shows, I survived, but the objective success did not trigger.

> What you expected to happen

Sweet, sweet greentext.

> What actually happened

My other objective - kill the HoS - was completed, but the "stay alive" objective was not.

> Steps to reproduce if possible.

Become a traitor AI (mid-round?) with the "stay alive until the end" objective and stay alive until the end.

**Comment by Ephx1** [comment]
I think there's some fuckery when it comes to silicon antags specifically with the stay alive objective

**Comment by clusterfack** [comment]
Without looking at the code I would guess that Nexis broke it preventing antags who become borers from having that kbjective succeeded

**Comment by Arthurdentist** [comment]
silly cons don't count as alive for 'stay alive until the end' and other objective purposes. If you have an objective to kill someone you can alternatively de-brain them and turn them into an AI or silicon to collect your greentext. 

this is the likely cause.

**Comment by AutismSpider** [comment]
@Arthurdentist Yes that work and when the Ai was Traitor or Cyborg (round start or later on traitor) it work fine and counted.

**Comment by Intigracy** [comment]
someone assign me

**Comment by 9600bauds** [comment]
you can only assign collaborators

**Comment by Intigracy** [comment]
i cry

**Comment by Intigracy** [comment]
make me a collab then :^)
