### ISSUE TITLE
"\icon[src]" macro doesn't account for overlays, underlays, color, or anything else

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6966]
It should be using getFlatIcon() instead, though I'm not sure what kind of performance hit that would put on the server

**Comment by clusterfack** [comment]
NO

**Comment by 9600bauds** [comment]
no what
there's a lot of shit that you examine and you only get the base icon, some things even show only a white rectangle because of this

**Comment by PJB3005** [comment]
Also, this macro won't work when I refactor chat.
