### ISSUE TITLE
ckeyless alium larvae

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6968]
(WEB REPORT BY: socachaca REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> cba81a4e189020eecb7b104d4e62bb6903f5a886 
> 
> General description of the issue
> Alium larva created in the "create antagonist" panel spawn with no ckeys.
> 
> What you expected to happen
> That writhing larvae of justice swarm the station everytime I push the "create alium" button.
> 
> What actually happened
> A bunch of sad observers and dead players hovering over their ckeyless larva bodies.
> 
> Steps to reproduce if possible
> As admin bring up create antagonist panel, press create alien as many times as desired. Observe result.

**Comment by nuklearcellphoneg** [comment]
pls fix

**Comment by 9600bauds** [comment]
k

**Comment by nuklearcellphoneg** [comment]
we did it
