### ISSUE TITLE
No Prompt for Wiz Apprentice

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#6970]
Title says it all. This results in brain dead apprentices or people just not interested in being one.

We have prompts for almost all else(aliens, diona, etc). If something like this happens, it definitely sucks for the Wizard.

In fact, using the spell produces a nonrefundable scroll to summon with. If there are no admins on, and a player uses this, they now have a worthless scroll if there are no applicants, so it would be better if this spell worked straight from the book, like for example, summon guns.

**Comment by unid15** [comment]
Same with borers

**Comment by ghost** [comment]
Borers have a "sign up for borer egg".

**Comment by ihadtoregisterforthis** [comment]
If the scroll stays, the prompt should appear at the moment it's bought, so the apprentice is still instant on use. Besides you avoid stuff like the way Dionas now work, where a mob spawns and it's AI controlled for some moments until it gets manned, or dies and drops seeds.
All (working) prompts have some time for confirmation between the roll and the spawn. Xenos fun button is the exception.

**Comment by ihadtoregisterforthis** [comment]
Also the scroll is actually refundable, you can put it back into the spellbook to reclaim the point.
