### ISSUE TITLE
Vox issues

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#6971]
1- ~~as a vox miner, you have an extended-capacity emergency oxygen tank + human mask in your starting box, instead of vox internals.~~
EDIT: Plasmamen have this too, but unlike vox this happens with every job. Oxygen tanks instead of plasma. (thanks @ihadtoregisterforthis) //needs verifying, old issue

2- vox pressure suit and helmet have the same in-hand sprite (see picture)
EDIT: Furthermore the east-west sprites are inverted. A suit on the left hand doesn't appear when looking to the west and it is on top of everything when looking to the east. (thanks @ihadtoregisterforthis)
![sprites](https://cloud.githubusercontent.com/assets/6170726/11747485/c3dc5744-a023-11e5-9b1a-99e3c620509c.png)

3- ~~all emergency nitrogen tanks on the station, both the ones in emergency closets and the ones in starting boxes, have Mask Release Pressure set to 101 kPa by default instead of 21 kPa as their oxygen counterparts (pointed out in #5079 too)~~

4- ~~i saw that there are specific vox magboots inside the vox trader outpost; by the way vox can use normal human magboots too (is this intended?)~~ --- intended

5- ~~it seems to me that you walk at the same speed either if you have vox magboots enabled or disabled, but i'm not 100% sure about this (if yes, is this intended?)~~ --- intended

6- differently than normal magboots, vox magboots have no visual hints to show if they're enabled or disabled, it would be better if they do it

7- as a vox, i only played as miner, janitor, librarian and quartermaster; i saw that janitor, miner and quartermaster use vox assistant pressure suit + helmet, so i can assume that many jobs as a vox start with the same assistant suit; because of this, it's impossible to spot a vox's job simply seeing them like you do with humans and you need to examine them everytime. it would be better if any job has their specific suit like humans do, but i think you already know this and you're already on it.
furthermore, you lose specific suit bonuses: for example, as a vox miner you can't reinforce your suit using goliath's skin like human miners do.

8- ~~when in the setup character window, if you browse vox hairstyles and facial hair using the arrows, you can choose human hairstyles and facial hair too; by the way if you choose a human hairstyle it will not appear ingame and your vox will be "bald".
UPDATE: this seems to affect all other species too.~~

EDIT
9- on the vox trader outpost there are some "vox emergency closets", their description is "It's full of life-saving equipment. Assuming, that is, that you breathe nitrogen" and their content is vox masks and nitrogen tanks; but their appearance is the same as normal emergency closets, blue with the O2 symbol, and this doesn't make sense to me. red with the N2 symbol maybe? (because muh immershun)

10- #4616 (thanks @9600bauds)

**Comment by Exxion** [comment]
The vox boots in the outpost are found _only_ there (and on the skipjack) and do not have the slowdown associated with magboots, so it is presumably intended that vox can wear either.
Also, as they lack slowdown, there's no real reason to ever disable them.

Oh, and I believe _all_ vox outerwear has the same in-hand sprite

**Comment by ihadtoregisterforthis** [comment]
1. Plasmamen have this too, but unlike vox this happens with every job. Oxygen tanks instead of plasma.
2. Furthermore the east-west sprites are inverted. A suit on the left hand doesn't appear when looking to the west and it is on top of everything when looking to the east.

(FOUR). The outpost must have some lore, but since it's meant for birds it has bird specific equipment. Vox using regular magboots is surely intended.

VII. Missing suits might only be for janitor, cargo and miner actually.

b8. Vox and humans are the only two races with hair.

PS: had to change the numbers in the numeration because _blessed_ Markdown was changing them to 1 2 3 4 5.

**Comment by 9600bauds** [comment]
a-cough cough #4616

**Comment by uazuaz** [comment]
thanks for answers, OP updated and added a new issue (no. 9)

@ihadtoregisterforthis 
>VII. Missing suits might only be for janitor, cargo and miner actually.

tried quartermaster, it uses an assistant suit as well

**Comment by uazuaz** [comment]
thanks for answers, OP updated and added a new issue (no. 9)

@ihadtoregisterforthis

> VII. Missing suits might only be for janitor, cargo and miner actually.

just tried quartermaster, he also uses an assistant suit

> b8. Vox and humans are the only two races with hair.

well, this doesn't matter, it's still a bug.

**EDIT: closed by mistake, reopened.**

**Comment by ihadtoregisterforthis** [comment]
Quartermaster doesn't have a specific suit, he's a cargo tech with sunglasses.
Mime and clown don't have pressure suits either.

**Comment by uazuaz** [comment]
@ihadtoregisterforthis that's what i mean, they need specific job suits or you need to examine them everytime to know who they are and what job they do. even the librarian vox has its specific vox librarian suit.

~~added a new issue, no. 11~~ --- removed

**Comment by 9600bauds** [comment]
all bugs here have been fixed

only sprite issues and sprite requests remain
