### ISSUE TITLE
Hiding in engines on shuttle prevents valids

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#6973]
It is impossible to kill people hiding in escape shuttle engines, like vampires or wizards.

Not counting explosions.

**Comment by CptWad** [comment]
Just have the engines no longer be deconstructible
Then have them generate shittons of damage because hiding in an active engine is silly

**Comment by AutismSpider** [comment]
Have the engines do mass burn/fire damage for sitting on them or being near them.

**Comment by 9600bauds** [comment]
Well this is the same issue with hiding inside walls, just that in this case they are indestructible walls...

**Comment by AutismSpider** [comment]
It hurts them or they get push out the wall.

**Comment by ghost** [comment]
Ideally you shouldn't be able to teleport into a wall, but an easier fix would be to deny escape objectives if a mob isn't on flooring

**Comment by CptWad** [comment]
There is plating under the engines I think

**Comment by 9600bauds** [comment]
>okay, if you're not a syndie then hide in this locker until the shuttle docks
