### ISSUE TITLE
I'm fairly sure Poly's parroting is broken

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#6974]
I would stand next to him and keep yelling shit, he would never speak anything except his default lines.

**Comment by Zth--** [comment]
He repeats stuff like 30 minutes later

**Comment by 9600bauds** [comment]
Using viewvariables seemed to show nothing being added to his speech_buffer variable, either, which is what led me to think this was just broken

**Comment by clusterfack** [comment]
Hm, does he have the hear flag?
