### ISSUE TITLE
Borer has unlocks unavailable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#6976]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> cba81a4e189020eecb7b104d4e62bb6903f5a886
> 
> General description of the issue
> Borer is unable to unlock genes some genes that are in its unlocks.dm, specifically 
> 
> What you expected to happen
> After evolving telephoto vision, I would be able to unlock X-Ray vision. Same with Dexalin+ secretion and Enhanced Metabolism after their respective prerequisites.
> 
> What actually happened
> Was unable to unlock Dexalin+ secretion, X-Ray Vision or Enhanced Metabolism even with 300 chems and all other unlocks evolved.
> 
> Steps to reproduce if possible
> Be a borer
> Unlock everything
> Notice that you never get the choice to unlock Dexalin+ secretion, X-Ray Vision or Enhanced Metabolism

**Comment by gbasood** [comment]
The unlocks are, specifically:
`/datum/unlockable/borer/chem_unlock/dexalinp`
`/datum/unlockable/borer/gene_unlock/run`
`/datum/unlockable/borer/gene_unlock/xray`
They are also, incidentally, the only genes for borer that have unlock prerequisites. Seems like prereq unlocks were never handled in code.

**Comment by Intigracy** [comment]
When I open the evolve menu it's always blank.

**Comment by ihadtoregisterforthis** [comment]
You need at least 50 chems to start seeing options
