### ISSUE TITLE
Should people suck at the piano when they are drunk, have low dexterity, etc.?

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6977]
I think so because it's fucking hilarious.
If people agree, I'll probably end up coding it, as I've already written something that fucks up the import code to make it sound like the player is drunk. That's in JavaScript, so I'd have to rewrite it, but I could do it much better as a built-in feature anyway.

**Comment by Ephx1** [comment]
The piano already sounds like a drunkard playing it because it ALWAYS sounds fucking abysmal.

**Comment by Exxion** [comment]
I mean missing notes and shit

EDIT: Maybe I should include a sample of my prototype version to show a somewhat worse version of what I mean

**Comment by 9600bauds** [comment]
Let's think about the positives and negatives of a monkey or alium or whatever being able to walk up the piano and play a masterpiece:
- Pros: It's hilarious and silly
- Cons:

**Comment by ghost** [comment]
I see nothing wrong with that, pianos usually aren't a point of contention either way

**Comment by Exxion** [comment]
@9600bauds OK then, drunk only

**Comment by PJB3005** [comment]
Let's do it.

**Comment by Exxion** [comment]
I'll probably code this soon, but should it apply to violins too? I only ask because violins already sound so bad that adding this to them would probably make people lynch anyone playing a violin while drunk

**Comment by ghost** [comment]
Whatever you want fam, literally no-one will be upset if you nerf playing instruments while drunk, unless you fuck it up and it breaks shit
