### ISSUE TITLE
Monkey-bitten vox become useless stupid worthless chickens

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#6992]
Yes, monkey mode actually happened
Vox, when monkeyed, become chickens, which cannot ventcrawl, open firelocks, or even bite people.

**Comment by Imagebard** [comment]
>Vox become uselss stupid worthless chickens

Working as intended.

**Comment by 9600bauds** [comment]
Idunno, it's kind of grifftastic, especially considering they can't EVER come back.

**Comment by PJB3005** [comment]
@9600bauds if monkey is actually the gamemode, then there's more shit to worry about than 1% of the server population being put out of the round.

Also, this is not technically a bug.

**Comment by 9600bauds** [comment]
I would append [Balance] to further "vox turn into chickens" issues

**Comment by Imagebard** [comment]
Seriously though, Chickened Voxes should work like Monkeyed Humans.
Or maybe give them a different gameplay style, only thing is that they should be able to monkey/chicken people like monkeyed humans can.

**Comment by Exxion** [comment]
STUNPECK

**Comment by Ephx1** [comment]
> Not a bug

P E R F E C T

**Comment by 9600bauds** [comment]
It IS not a bug, just a very questionable feature

**Comment by clusterfack** [comment]
Gas the vox race war now

**Comment by PJB3005** [comment]
GAS THE EVERYTHING BUT THE VOX RACE WAR NOW.

Vox atmosphere is objectively superior `:^)`, no fires.

**Comment by gbasood** [comment]
It's definitely not a bug, just a balance issue. If your captain is a Vox, which is dumb in and of itself, you can permanently remove him from the crew, even with cloning, this way.

I wonder if this counts towards the assassinate antag objective?

**Comment by Ephx1** [comment]
I don't believe it does. In the same way that changing via a staff of change doesn't count you as dead.

**Comment by 9600bauds** [comment]
I can do it myself now
My influence grows

**Comment by ihadtoregisterforthis** [comment]
"Fixed"
