### ISSUE TITLE
Vampires can revive and regen in space while on fire

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#6993]
As the title says.
A vampire player that has harvested shitton of blood can do bullshit like reviving and regenerating in the middle of space, then mist forming back to the station to haunt people at *full power*.
I don't know how exactly this worked since I wasn't a vampire, but somehow that person was able to avoid turning to dust while in space and do exactly what I said at least 3 times, coming back at full power each time.

**Comment by dylanstrategie** [comment]
Mature Vampires are notoriously overpowered. Basically nothing short of a bomb will kill them

**Comment by AutismSpider** [comment]
@dylanstrategie  not just over power takes very little work to hit that mature point one or two monkey humans and grab two blood bags form medbay+food items will give you all the blood you need to hit max power.

**Comment by Kurfursten** [comment]
I think we should just revert Kilkun's balance change to vampires, honestly. #2583

Vampires used to be all about banking useable blood, but now they're more like changelings in that you get permanent spells forever once you reach certain blood amounts.

**Comment by AutismSpider** [comment]
@Kurfursten Ling has to put in work to get that dna one husk body+the sounds lings make when eating people are dead give away to one zero sucking sounds or bite sound when vamp feeding on some one on top of this vamp powers are better then lings over all.

**Comment by Kurfursten** [comment]
I don't disagree with you. Vamp powers are supposed to be better because you were supposed to use up your blood bank every time you used one. Kilkun made them all free.

**Comment by Imagebard** [comment]
They added blood cost back to a couple of spells, a long time ago, buy it seems they forgot to close this one.
Shutting it down.
