### ISSUE TITLE
Port some Xeno shit form Colonial Marines

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7000]
The xeno castes might be too overpowered depending on the status of the station, but some other shit might be interesting.

1. Humans don't gib when larva spawns, it only creates a bloody hole on the person's belly, telling people it bursted
2. SSD larva, ghosts can choose to "Spawn as Larva" to scan for any SSD larvae.
3. Alien Queens can call the shuttle and try to get into CentComm for complete dominatus of the star system, Alien Major Victory.

Alternatively port fucking everything, humans are slowly getting more power as coders change shit and Colonial Marine xenos might be a fresh experience.

**Comment by Imagebard** [comment]
Also *also*
#7000 get.

**Comment by assdad211** [comment]
>Alternatively port fucking everything, humans are slowly getting more power as coders change shit and Colonial Marine xenos might be a fresh experience.

The Colonial Marines xenos are actually probably slightly weaker than what we have now, although changing that would just be a matter of adjusting some numbers

By the way I don't think colonial marines is open source

**Comment by Imagebard** [comment]
>I don't think colonial marines is open source

Oh fuck what.
Are the sprites open source, at least? They look better than our current extremely blatant purple ones.

**Comment by Ephx1** [comment]
> Purple

Uhm
![untitled](https://cloud.githubusercontent.com/assets/6224074/11767815/4df0a646-a188-11e5-8a04-04af580ead6f.png)

**Comment by clusterfack** [comment]
Port from colonial marines the closed source codebase BAKA DESU

**Comment by Imagebard** [comment]
Yes I am talking about the weeds.
Urrr.

**Comment by Ephx1** [comment]
Considering you didn't mention them at all, it seemed as though you were only talking about xenos, but whatever.

**Comment by Ephx1** [comment]
Here's the evolution system that Colonial marines uses for anyone curious.
![evolution](https://cloud.githubusercontent.com/assets/6224074/11768066/a91b47f4-a18f-11e5-8925-2f0fd248319a.png)

**Comment by CptWad** [comment]
Id like an overhaul but an outright port would probably make whoever is doing thier shit upset that we just took it. We probably should ask first if it is not open source
Also a lot of that seems like fluff. There a wiki page so we can see exactly what were porting?

**Comment by Ephx1** [comment]
http://www.colonial-marines.com/wiki/Aliens
A lot of it looks interesting but I agree, I'd rather have a good overhaul made here rather than porting it.

**Comment by Imagebard** [comment]
Ah yes "port shit form a closed source code" a old trick of mine

**Comment by ComicIronic** [comment]
Was there a get you people DIDN'T waste?
