### ISSUE TITLE
Borgs become unable to do anything if you hit "cancel" while choosing your appearance

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7001]
My legs aren't OK

1.Step into a recharger
2.Choose a module
3.Don't chose how you look like, instead cancel
4.Try to walk

**Comment by clusterfack** [comment]
You're missing a lot of useful info here

**Comment by gbasood** [comment]
I'm assuming steps to reproduce whatever the fuck this bug may be (assuming he just can't walk) are:
 - Become a borg on roundstart
 - Do not pick your module
 - Enter a recharger
 - NOW pick your module
 - Hit cancel when given the choice to select appearance
 - Attempt to exit the recharger and walk around

Not sure if I'm helping

**Comment by Imagebard** [comment]
I'd rewrite the OP but gbasood nailed it.

**Comment by gbasood** [comment]
It'd also be useful to know what module you picked, in case that somehow has anything to do with it. Probably not, but hey.

**Comment by clusterfack** [comment]
Okay so this is what I meant:

Does it occur if you pick a module? 
Or if you cancel out of module picking? 
Or only if you cancel out of appearance picking?

When you say 'My legs aren't OK', do you mean you cant move after exiting? 
Or does it mean you cant move while still inside the charger?

Specificity on what does/doesn't cause it is literally the key to most fixes

**Comment by Imagebard** [comment]
I only tested it during appearance picking, its possible it might also happen by canceling out of module picking.

You can't move at all. All you can do is enter/exit the charger with a right click, trying to move doesn't do anything and you can't grab/use any of your modules.

**Comment by SonixApache** [comment]
possibly related; #6736

**Comment by PJB3005** [comment]
Definetly related, I'd say.

**Comment by clusterfack** [comment]
I thought I fixed that bug

**Comment by Imagebard** [comment]
It happened today.
Today.

Take a guess, probably not.

**Comment by Kitfox88** [comment]
Happened to me today and yesterday as well, as well as happening out in a hallway. Both times it happened after I had selected my module, but before I had selected any sprite, so I was still the default one.

**Comment by gbasood** [comment]
Picking module while your loc is anything but a turf is probably buggy, but happening in hallways is a new one

**Comment by 9600bauds** [comment]
Needs descriptive title

**Comment by 9600bauds** [comment]
Thank you

**Comment by PJB3005** [comment]
I have found the cause: during module select the `lockcharge` variable on the borg gets set to 1, which locks it in place, but when the borg cancels it doesn't get reset.

**Comment by CptWad** [comment]
A prayer for fixing this bug :pray:

**Comment by Imagebard** [comment]
> on 13 Dec 2015
