### ISSUE TITLE
Make the jukebox, etc. start playing the song at the right time when someone enters the room

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7005]
Currently, whenever you enter a room playing a song, it starts playing for you from the beginning, regardless of how long it has been playing. It stops at the same time for everyone, though. It should start playing at the point in the song it would be at for someone who has been in the room since it started when someone enters a room. Not sure if that's feasible, but it would be very nice.

**Comment by SonixApache** [comment]
Isn't this already a thing if you use the VLC addon or whatever?

**Comment by Exxion** [comment]
Is it? I don't know because VLC never actually plays things properly for me. I probably didn't set it up properly.

**Comment by Ephx1** [comment]
Fairly certain this is a Windows Media Player issue only.

**Comment by Exxion** [comment]
Well then fuck me

**Comment by Imagebard** [comment]
Someone should make a guide on how to make this VLC shit work, because its broken for me too.

**Comment by clusterfack** [comment]
It's an issue with WMP, literally the entire reason we added VLC. 

You have to install VLC with the activex plugin if you want VLC to work.

**Comment by Exxion** [comment]
Ah, ActiveX
Thanks

**Comment by Exxion** [comment]
OK I just reinstalled VLC with the ActiveX plugin and everything
Still doesn't work
Help

**Comment by Imagebard** [comment]
(Reopen the issue)

**Comment by Exxion** [comment]
PSSSSSSSSSSSSSST
GIVE US A GUIDE ON HOW TO MAKE VLC ACTUALLY WORK
BECAUSE JUST "Install with ActiveX" DID NOT WORK FOR ME
