### ISSUE TITLE
[META] No merch computer in cargo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7006]
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> fff91a99b2aac407acaf80f898f014ea0823b9ee 
> 
> General description of the issue
> Box (and taxi?) have a merch computer for cargo, but Meta doesn't. My burgers!

**Comment by gbasood** [comment]
probably already resolved

**Comment by Probe1** [comment]
I hate that console.  It's 100% magic.  

 >unlimited inventory
 >has food, clothing, beach balls
 >It has a console sprite

**Comment by SysadminJeroen** [comment]
@Probe1 I suggested in #9073 that the Traders would need to trade items for different items.

**Comment by Probe1** [comment]
Yeah I believe I echoed what I said here, having a vox trader would be a useful place to shoe horn in things that make no sense and are generally poor ideas.

**Comment by SysadminJeroen** [comment]
@Probe1 Remove merch computer and add a job to do for Vox Traders, two problems solved?

**Comment by Probe1** [comment]
I was talking about giving the merch computer TO  the vox traders where an outrageous machine is less of an issue since it lends itself to the jobs nature.

**Comment by ihadtoregisterforthis** [comment]
And what if there are no traders that round?

**Comment by Probe1** [comment]
I think there might be a kitchen you can get food from.

**Comment by SysadminJeroen** [comment]
@Probe1 Putting the computer there at the Vox Traders might work as well, forces players to get out of the station to get luxurious items and burgers.
