### ISSUE TITLE
AI's can take the powercells out of APC's

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7009]
How to test
*Be AI
*Have someone open your APC that is right next to you, so the powercell can be removed if you have hands
*Click APC
*Congradulations, you have just killed yourself and you cant put the cell back in

**Comment by Ephx1** [comment]
Cyborgs can do this too, I hadn't tried it as AI and thought it was a feature for borgs.

**Comment by Kurfursten** [comment]
attack_ai calls attack_hand which leads to OVERSIGHTS

**Comment by clusterfack** [comment]
When did you test this because I can't reproduce it

**Comment by CptWad** [comment]
I posted this the day it happened
someone opened my APC (On box) and I clicked it like an idiot which caused me to remove the powercell, killing myself as the result

**Comment by clusterfack** [comment]
Oh THATS what you meant. Yes that's a feature for Borgs, I thought you were saying it put the cell in your hands which is something that can actually happen in certain cases of bad code.
