### ISSUE TITLE
Pods are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7010]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
The escape pods aren't leaving the station when the emergency shuttle leaves.

Noticed on both Meta, and Box station so far.

**Comment by ghost** [comment]
@clusterfack 

Haha https://github.com/d3athrow/vgstation13/commit/0d1c2af69b6499e5520b2fba8fbe7b2e96930aec

**Comment by clusterfack** [comment]
Related? 

runtime error: Cannot read null.x
proc name: calc turf (/datum/light_source/proc/calc_turf)
  source file: light_source.dm,275
  usr: Nipples (/mob/living/carbon/human)
  src: /datum/light_source (/datum/light_source)
  call stack:
/datum/light_source (/datum/light_source): calc turf(space (183,169,1) (/turf/space))
space (183,169,1) (/turf/space): lighting build overlays()
space (183,169,1) (/turf/space): change area(Space (/area), Taxi A (/area/shuttle/taxi_a/engineering_cargo_station))
taxi A (/datum/shuttle/taxi/a): move area to(the floor (64,143,1) (/turf/simulated/shuttle/floor), space (182,174,1) (/turf/space), 0)
taxi A (/datum/shuttle/taxi/a): move to dock(the docking port (/obj/structure/docking_port/destination/taxi/a/medbay_silicon), 0)
taxi A (/datum/shuttle/taxi/a): pre flight()
taxi A (/datum/shuttle/taxi/a): travel to(the docking port (/obj/structure/docking_port/destination/taxi/a/medbay_silicon), null, null)

**Comment by ghost** [comment]
I'm guessing that fix broke this.

**Comment by ihadtoregisterforthis** [comment]
[OH GOD IT'S LOOSE]

**Comment by PJB3005** [comment]
Actually they stay attached.

**Comment by ihadtoregisterforthis** [comment]
[Needs unfixing]
[Port]

**Comment by clusterfack** [comment]
To be honest it's really weird that this broke, it should have broken all shuttles or none of them. Not 1/10th of them.

**Comment by clusterfack** [comment]
Oh I see, they weren't converted to shuttles, they're still some ancient hack code to accomplish the same thing
