### ISSUE TITLE
Hairstyle occasionally gets reverted to bald

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7015]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 666a1f5d0e1cb8292c9f5faf33cd8b026b2dfe50 
> 
> General description of the issue
> I have the bedhead 2 hairstyle saved. Occasionally, around once a day or so, my hairstyle will be reverted to bald, for no apparent reason.
> 
> What you expected to happen
> Hairstyle would remain bedhead 2
> 
> What actually happened
> Hairstyle rarely reverted to bald
> 
> Steps to reproduce if possible
> Set hairstyle to bedhead 2
> Play game for a while, eventually it will turn into bald again.

**Comment by Kurfursten** [comment]
Did you end the previous shift bald (e.g.: due to radiation or a mirror)?

**Comment by 9600bauds** [comment]
Observing will occasionally do this
