### ISSUE TITLE
[METACLUB] Pods bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7019]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
When the shuttle finally counts down to zero, the arrivals pod in Metaclub does not leave with the other pods/shuttle.

**Comment by Exxion** [comment]
God damn it
This is not Meta exclusive and another duplicate of #7010

**Comment by clusterfack** [comment]
Dupe
