### ISSUE TITLE
Being glomped by a playerslime makes you crawl until you punch yourself

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7021]
It may only happen under certain circumstances. It happened twice that round, but I only know _exactly_ what happened one of those times.
1. Get glomped by playerslime
2. Run around for a while and try to resist out
3. Give up, switch to harm intent, and blow the slime off with a beanbag from the double barrel
4. Fall down
5. Continue to move at full speed while sideways and unable to pick anything up
6. Go to cryo to fix clone damage
7. Continue crawling around at ultra speed but continue being unable to pick anything up
8. Listen to slime jokingly suggest you punch yourself
9. Do so
10. Amaze yourself and the slime when you do, in fact, get up

The other time it happened, I didn't see it happen, but I saw the person speedcrawling in medbay and told them to punch themselves. It worked again.

**Comment by Kurfursten** [comment]
This isn't specifically related to slimes, it happens at odd times, like coming out of cryo or cloning

**Comment by Exxion** [comment]
Maybe it has to do with changing clone damage values, then
