### ISSUE TITLE
Grills shocking even when covered with a window

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7023]
(WEB REPORT BY: golfer45 REMOTE: 158.69.55.2:7777)
To reporduce this, break one of the grills above the bridge on box, walk to where the grill used to be. Now walk into the grills next to it, it will shock you even while covered in glass

**Comment by ghost** [comment]
Full tile windows don't prevent you from making contact with the grille for some reason

**Comment by Intigracy** [comment]
Possible fix would be to adjust adjacent() to check for objects on the same tile, and ones with a higher layer and density == 1 would cause adjacent to fail.

**Comment by Intigracy** [comment]
window code sucks camel dick

**Comment by Intigracy** [comment]
@gbasood re-open this
