### ISSUE TITLE
Double Agent's objectives fucking suck ass and break the mode

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#7024]
Lately I keep seeing shit like this:

http://imgur.com/p9Vf8t0

Ideally they'd both want to stay ALIVE, right?

**Comment by Exxion** [comment]
I once got someone who had a die objective as my target
We both succeeded and I didn't have to do anything

**Comment by ihadtoregisterforthis** [comment]
This won't happen anymore I guess

**Comment by 9600bauds** [comment]
This objective has since been removed
