### ISSUE TITLE
Defibrillator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7026]
(WEB REPORT BY: bexus REMOTE: 158.69.55.2:7777)

> General description of the issue
> Defibrillator "Patients condition does not allow reviving" on patients that have died to burn damage it seems, even if the damage is below 200% (including suffocation damage so it can't be that)
> 
> What you expected to happen
> He should be able to be revived so we don't have to clone him.
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
I bet you the brute + burn + toxins was bigger than 200.

**Comment by DrLeprikon** [comment]
It wasn't, the overall health was -67%

**Comment by 9600bauds** [comment]
This can happen if the patient's ghost was put into a borer or something. Were you able to clone him afterwards?

**Comment by DrLeprikon** [comment]
I do think that was the cause: cloning was not possible due to Mental Interface Failure

**Comment by 9600bauds** [comment]
Then either he ghosted out of his living body, or his ghost was unavailable because he reincarnated into a Diona or something (and thus he can't ever come back to his body anymore).

**Comment by ghost** [comment]
The defibrillator messages aren't really extremely clear, and it's made only worse by the fact someone else took a pass at them after me

Generally, if the crewman is in the defibrillator zone but has a clear error message (not "try again in five seconds"), that means that he can't be revived. Can be anything from suicide and husking to ghosting or respawning
