### ISSUE TITLE
Onward to Centcomm Via Cargo Stowaway

### ISSUE THREAD

**Issue by assdad211** [d3athrow/vgstation13#7028]
Step 1: Get ye telebeacon

Step 2: Set teleporter to ye telebeacon

Step 3: Place ye telebeacon on cargo shuttle

Step 4: Go up to cargo shuttle console and use the hand tele, activating a portal to the cargo shuttle

Step 5: Step through portal, retrieve ye telebeacon (cargo shuttle will not move with a beacon onboard)

Step 6: Go back through portal, send shuttle

Step 7: Portal now leads to centcomm. Throw telebeacon through portal and go through yourself.

Step 8: Use a welderbomb or c4 or some other explosive to break the shuttle windows to get out of it, or use RPD to tunnel though

Step 9: Use rapid piping device to create a pipe on the riveted wall, use contortionist jumpsuit, monkey SE or be a MoMMi or Diona to ventcrawl to freedom

Step 10: Grab the telebeacon and take it into centcomm proper. Grab the nearby centcomm ID and you now have freedom to take the seraph, energy axes, ERT gear, donk pockets, whatever.

Step 11: Send the ERT shuttle to arrivals or use the teleporter to go back to the station. You can of course hand tele back to the telebeacon now, or ferry people to centcomm with the shuttle.

The destination of centcomm will not appear in the teleporter's destination selection list, but if it was previously set to the beacon it'll remain set to the beacon.

This does not work with holodeck. 

http://i.imgur.com/ngGzWc9.png

**Comment by ghost** [comment]
Two ways to handle this. Prevent the cargo shuttle from leaving when a portal is open on it, or auto-close portals on moving shuttles. You could also make a specific snowflake for the cargo shuttle, I suppose

**Comment by Kurfursten** [comment]
The more fundamental problem, to me, seems to be the ability to RPD a riveted wall.

**Comment by ghost** [comment]
Nice title.

**Comment by clusterfack** [comment]
You can make teleporters not detect centcomm beacons

**Comment by assdad211** [comment]
@clusterfack They don't detect them already, they don't appear in the list at all. You get around this by setting the tele to the beacon before you put it on centcomm.

The telebeacon going to centcomm isn't even necessary, it's just quality of life for teleporting lots of people to centcomm. You can go on centcomm by just making the portal on the shuttle.

@kurfursten Even if RPD tunneling was removed you could do this with phazon still, and probably something else I'm not thinking of.

**Comment by Kurfursten** [comment]
I'm not saying 'don't fix the shuttle thing', but RPDing riveted walls is obviously an oversight.

**Comment by assdad211** [comment]
If you change it keep it so you can RPD normal walls please, it makes repiping bombed areas actually possible in a reasonable time span.

**Comment by Kurfursten** [comment]
Oh yeah of course, that goes without saying.

**Comment by assdad211** [comment]
Another possibility for getting through riveted walls on centcomm is making a portal to centcomm, casting Etheral Jaunt or the vampire equivalent, then going through the portal and passing through the wall before the spell elapses (you can't cast spells on centcomm)

Nevermind, tested and you can't go through portals or static teleporter while ethereal

You can probably make a singularity on centcomm to eat the walls

**Comment by clusterfack** [comment]
You cant cast those spells on centcomm, you can mail a singularity to centcomm though, that's been done a few times

**Comment by PJB3005** [comment]
I don't think we should fix singulo mailing to CentComm.

**Comment by Killette2** [comment]
Mailing a singulo to centcomm is way too fun to fix.

**Comment by Intigracy** [comment]
Funfact, at one point someone did fix being able to singulo centcomm.

Then someone fixed not being able to singulo centcomm.
