### ISSUE TITLE
Large Artifacts become anchored

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7029]
(WEB REPORT BY: alone REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 644acd3fcda003588b11e434f2574f51644671f6 
> 
> General description of the issue
> Large artifactss become unmoveable
> 
> What you expected to happen
> Artifacts are able to move
> 
> What actually happened
> Artifacts get anchored and unmoveable after a certain time
> 
> Steps to reproduce if possible
> Find a large artifact
> Leave it inside an area
> Don't touch or move it, leave it alone in a room for a while
> It becomes anchored and unable to move

**Comment by PJB3005** [comment]
I can 100% confirm this.

Also Paradise fixed this so steal the fix?

**Comment by jknpj** [comment]
It becomes anchored after another artifact is scanned. This is really annoying.

**Comment by 9600bauds** [comment]
Why was this tagged hotfix
