### ISSUE TITLE
Deconstructing walls doesn't give you enough metal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7030]
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 644acd3fcda003588b11e434f2574f51644671f6 
> 
> General description of the issue
> Deconstructing a wall leaves you with 3 metal rather than 4. You can't reconstruct the wall after deconstructing it.
> 
> What you expected to happen
> Deconstruct wall, get 4 metal.
> 
> What actually happened
> Deconstruct wall, get 3 metal.

**Comment by Kurfursten** [comment]
I think @ComicIronic was a proponent of the "you can't recycle with perfect efficiency", although I always thought it was silly that a bomb gives you 4 metal but careful deconstruction only 3.

**Comment by Imagebard** [comment]
@Kurfursten

Same for Grilles, snipping it will give less rods than just kicking it down.
Shouldn't it be the other way around?

**Comment by WeinerMaster69** [comment]
It should be flipped, destructive deconstruction (bombs, beating it down rather than wirecuttering) should give 3, and welder should give 4.

**Comment by Exxion** [comment]
@Imagebard I thought that was fixed

**Comment by Kurfursten** [comment]
I'm pretty certain that snipping gives the correct amount of rods now.

**Comment by ComicIronic** [comment]
Willing to close this because Kurfurst was very astute in pointing out that I hate 100% efficiency.

**Comment by Exxion** [comment]
Well at least make it so that bombs don't return 4
