### ISSUE TITLE
Sent back to the Lobby

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7031]
(WEB REPORT BY: ricklaus REMOTE: 158.69.55.2:7777)
If you have a re-entereable body as a ghost and click "become mommi" and then re-enter your body, it will close your connection and send you back to the lobby.

**Comment by 9600bauds** [comment]
Wasn't this fixed?

**Comment by clusterfack** [comment]
Yes maybe

**Comment by gbasood** [comment]
Yes
