### ISSUE TITLE
Reinforced girders lose their reinforced status if finished with normal metal

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7032]
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 644acd3fcda003588b11e434f2574f51644671f6 
> 
> General description of the issue
> If you build a wall girder and add metal rods, you reinforce it. Normally you're supposed to secure them and whatever to make it into an RWALL, but if you just add metal it becomes a normal wall. However, welding the metal out then reveals a normal girder.
> 
> What you expected to happen
> The girder to remain reinforced after completing the wall.
> 
> What actually happened
> The girder reverted to a normal girder after completion and deconstruction of the wall.
> 
> Steps to reproduce if possible
> Place wall girders
> Add rods
> (secure rods with screwdriver)
> Add metal sheets
> Weld down wall

**Comment by Exxion** [comment]
Probably inheritance issues

**Comment by ghost** [comment]
Technically, the reinforced girder is a child of the girder, just like the reinforced wall is a child of the wall

There should be a reinforced variable and/or state variable that I can use to make sure you can't plate a reinforced girder with regular metal, I'll look into it asap
