### ISSUE TITLE
Protolathe does not allow console screen fabrication

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7033]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 644acd3fcda003588b11e434f2574f51644671f6
> 
> General description of the issue
> After syncing with R&D server (and possibly before), console screens are not able to be fabricated from protolathe.
> 
> What you expected to happen
> Be able to see and click on console screen in protolathe menu
> 
> What actually happened
> Could not see console screen in protolathe menu
> 
> Steps to reproduce if possible
> Sync R&D server
> ctrl+f screen
> find nothing

**Comment by SonixApache** [comment]
you never could, that's why there's an autolathe right next to it
