### ISSUE TITLE
No sounds

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7040]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
>  644acd3fcda003588b11e434f2574f51644671f6 
> 
> General description of the issue
> Can't hear jack shit. All sound-related preferences are on. 
> 
> What you expected to happen
> I can hear everything.
> 
> What actually happened
> The game is completely silent.
> 
> Steps to reproduce if possible
> n/a, happened when I logged in

**Comment by uazuaz** [comment]
start the game, then try to check your operative system audio option for Space Station 13 (volume control or mixer volume maybe)

**Comment by ghost** [comment]
@gbasood likely PEBCAK. Close please.
