### ISSUE TITLE
DOUBLETRAITOR

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7042]
I got two sets of traitor objectives. It gave me the "You are now a traitor!" text and all associated text and the sound twice in a row. The sets of objectives were the same, but weird (four objectives, including both escape alive and escape alone). The only difference between the two walls of text was the access code for the uplink, and only the second one worked.

**Comment by Exxion** [comment]
I also had two sets of traitor notes in my notes

**Comment by Exxion** [comment]
It was apparently a traitorling round, if that matters

**Comment by gbasood** [comment]
This absolutely occurs for me almost all the time when I get antag.

Possibly related to #3701 as well?

**Comment by Exxion** [comment]
I've seen someone roll changeling AND two traitors once
Presumably yes, it's related
I assume the system choosing antags isn't excluding those already chosen
