### ISSUE TITLE
0 wooden planks in stack

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7045]
(WEB REPORT BY: assfaget REMOTE: 158.69.55.2:7777)
That's some wooden planks. They are a normal-sized item.
One can only guess that this is a bunch of wood.
There are 0 wood planks in the stack.

**Comment by Kurfursten** [comment]
Wood planks also have the annoying habit of not auto-stacking when cut from logs.

**Comment by Imagebard** [comment]
They used to stack normally. We should return that behavior.
