### ISSUE TITLE
Odysseus energy cost is prohibitively high

### ISSUE THREAD

**Issue by assdad211** [d3athrow/vgstation13#7047]
This seems to be a pretty overlooked thing because no one uses odysseuses. Odysseuses use a lot of cell charge per step, and an enormous amount of cell charge when manufacturing chemicals with their syringegun or when holding people in their sleeper. If you walk from arrivals to escape on box in an odysseus it costs like 15% of your cell charge, which is not ideal for a paramedic mech which will be running all across the station saving people in crit and whatnot.

I think the energy step cost should be free and the syringe gun's chemsynth energy usage should be reduced. Right now you're just permanently on the exosuit charger or swapping out cells as new ones get drained.

It would also be swell if odysseuses had a built-in crew health monitor.

**Comment by ihadtoregisterforthis** [comment]
There are many ways to overcome this. 
- Upgrade the cell
- Get an energy relay
- Get a reactor
- Put a mech recharger on the medbay
- Get a load of batteries
- Any combination of the above

If anything, it's not prohibitively high, just high.
The odysseus is not exclusive for the paramedic, so built-in monitor would be easy abuse.

**Comment by assdad211** [comment]
The mech is never going to see use as it is, it just isn't worth the trouble. It's a wad of neat content gated behind unviably shitty values that would take thirty seconds to adjust.
