### ISSUE TITLE
Station Map for sec cameras does not update on meta[METACLUB]

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7051]
And possibly others.

Image:

https://imgur.com/YflTdzk

Those cameras in space on the east are AI Sat cameras.

**Comment by Ephx1** [comment]
This is an issue with the previous map being different from what the current map is on any minimap console.
See #6140, #5945, #6617.

**Comment by PJB3005** [comment]
Closing because dupe.
