### ISSUE TITLE
VLC Win64 doesn't work with SS13

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7053]
Not a huge deal, but only 32-bit VLC actually works with Windows
Fixing this would be nice, but not exactly high-priority, as VLC Win32 works on 64-bit systems, of course

**Comment by Exxion** [comment]
According to the eggman, BYOND itself is only 32-bit, so this may not be fixable

**Comment by gbasood** [comment]
Yeah, this has been a long-standing issue that can't be resolved really. It has everything to do with the IE plugin that VLC installs, so if it can't be loaded by 32-bit IE, it can't be loaded by BYOND.

**Comment by Intigracy** [comment]
Can we close this since we can't do anything about it?

**Comment by Exxion** [comment]
Huh. Could have sworn I DID close this.
