### ISSUE TITLE
[OH GOD IT'S LOOSE] SPRITES DYING SEND HELP

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7055]
![](http://i.imgur.com/Bjz5IBg.gif)

In case it isn't clear, I turned invisible whenever I was facing south. Not sure when or why this occurred.

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/11824007/482bb570-a345-11e5-8820-694eeca2c016.png)

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/11824143/f98a989a-a345-11e5-83a1-28975f7a8659.png)
![image](https://cloud.githubusercontent.com/assets/9827785/11824149/033b281e-a346-11e5-8c5b-73fd911bec4a.png)

![](http://i.imgur.com/qHWZQGm.gif)

**Comment by Imagebard** [comment]
Needs the "Not a Bug" tag.

**Comment by Exxion** [comment]
It definitely looks like a bug

**Comment by ihadtoregisterforthis** [comment]
Looks more like a bat though

Whatever it was it gave me a good scare
![delivery suffix five 2015-12-15 173614 twice as big](https://cloud.githubusercontent.com/assets/13305885/11825184/53ed2c38-a35c-11e5-91f4-8b2a2c8f5843.png)

**Comment by Exxion** [comment]
@PJB3005 Look it got worse
Extra panic

**Comment by ghost** [comment]
@ihadtoregisterforthis

I see that quite often with random sprites, thought it was bus.

**Comment by Exxion** [comment]
Considering the icon_states were still correct, I wonder if it's a memory issue
It's worth noting that the round my screenshots were taken in was over two hours long at the time I took them and it only got (a bit) worse with more time.

**Comment by PJB3005** [comment]
The preview on the top left of VV was showing correctly, this is definetly a BYOND issue.

**Comment by Exxion** [comment]
It's an unfixable BYOND thing and I'm not sure why it's still open
