### ISSUE TITLE
Captain cannot remove his jumpsuit

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7058]
I'm guessing it's because of the medal of captaincy that he also cannot remove.

**Comment by Ephx1** [comment]
Fairly certain this is intended.
Unless this is an ancient bug.

**Comment by ghost** [comment]
How could this possibly be intended?

**Comment by Ephx1** [comment]
A majority of other codebases have the same thing, so like I said, either intended or some ancient bug.

**Comment by 9600bauds** [comment]
I was able to remove my jumpsuit by rightclick -> remove accessory, which removed the medal of captaincy. I was then able to remove my jumpsuit. I have no idea where the medal went, it seemingly just disappeared.

**Comment by MistakeNot4892** [comment]
Try dragging the jumpsuit onto your hand.

**Comment by PJB3005** [comment]
Yeah other codebases have it like @Zuhayr said.

**Comment by ghost** [comment]
This is one ooolllld bug.

**Comment by Intigracy** [comment]
Still an issue?

**Comment by 9600bauds** [comment]
Closing in favor of #7058

**Comment by 9600bauds** [comment]
UHHH I MEAN IN FAVOR OF #10121
