### ISSUE TITLE
Chat occasionally fails to actually go through

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7064]
I haven't noticed any specific circumstances that cause it, but sometimes the speech bubble will pop up but the message will not actually send.

**Comment by gbasood** [comment]
~~This happens with mice, for instance, due to a runtime~~ nevermind

**Comment by 9600bauds** [comment]
I know it's happened to me quite a few times with completely normal speech by completely normal humans

**Comment by Exxion** [comment]
Playing primarily bartender, I see it all the fucking time. At least once every round or two just that I notice.

**Comment by gbasood** [comment]
Actually, thinking about it, I've seen this happen as a MoMMI, even when I've spoken it myself. No blank line output or anything, it's just like I've never spoken, but peopel still respond as if I have.

**Comment by Exxion** [comment]
I also saw the blank line thing for a while from a borg, but then it stopped
But it consistently happened for every message from that borg for a few seconds
...At least I think it was a borg
It was several days ago and I don't remember

**Comment by ghost** [comment]
This can happen with ahelps/admin pm too, hilarity ensues.

**Comment by 9600bauds** [comment]
henk

**Comment by gbasood** [comment]
So, something with to_chat is fucked?

Which is odd considering to_chat is just thing << output

No other possible way for ahelps/admin pm to also fuck up, though.

**Comment by Intigracy** [comment]
This happens with ooc too, it's a byond bug that's been around since the dawn of time.

You don't see it go through, but others do.

**Comment by clusterfack** [comment]
This bug has been around since I started playing and much much longer before then

**Comment by Exxion** [comment]
I never noticed it before a few days ago, but that might be for an entirely different reason than it having only existed for a few days/being much more common for a few days.

**Comment by Intigracy** [comment]
Usually when byond updates we update the server too, versus other servers waiting 5ever to update.

**Comment by Exxion** [comment]
Wait a second

> You don't see it go through, but others do.

I've seen it happen where someone _else_ says something and _I_ don't see it
I've seen both happen
I know because their chat bubble comes up and they might say something afterward that is a continuation

**Comment by Intigracy** [comment]
Oh, then there's two instances of it.

You say something, you don't see it but others do.
Someone else says something, you don't see it but others do.

Still a byond bug, it also happens with OOC chatter like I said above.

**Comment by PJB3005** [comment]
Yes I can confirm this, and I'm pretty sure it's BYOND.

**Comment by PsiOmegaDelta** [comment]
Can confirm that this occurs on Bay as well (and we certainly don't have the chat_to refactor) and I also highly suspect it's a BYOND issue.

**Comment by Zth--** [comment]
It happens really often for me. Specially when ooc chat is quiet and suddenly people start answering to a non-existant question. I even checked the logs to see if I had that person muted or something.
Maybe it has to do with lag/packet loss? I play with ~200ms because I'm from Argentina and I see this every single round

**Comment by SonixApache** [comment]
I've got a very low ping and it happens to me often, so it's probably not a connection issue.

**Comment by Exxion** [comment]
After looking at some logs, I think that the issue where others send but I don't receive happens far more often than I thought, just usually with radio or OOC messages so I have no in-game indication it happened.

**Comment by Exxion** [comment]
Uh... why was this closed?
Goonchat may or may not have just fixed it, though

**Comment by Exxion** [comment]
Nope, not fixed

**Comment by PJB3005** [comment]
If that's the case BYOND is literally dropping the `output()` packet or something.

Still not gonna reopen as it's basically purely a BYOND issue, unless somebody else can prove it.
