### ISSUE TITLE
You know what I don't even know anymore

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7066]
![image](https://cloud.githubusercontent.com/assets/9827785/11828269/3c0122d2-a361-11e5-93eb-c6e86369795a.png)

I think it incorrectly let me scroll out while I was in crit even though scrolling out SHOULD only be possible while dead
It fixed itself in the time it took me to crop the screenshot (maybe 5 or 10 seconds, if that), but luckily ShareX freezes the screen as soon as you hit the hotkey, before you crop it.

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/11828450/d888bc36-a362-11e5-9869-0912a30cfca6.png)

(ckey FonedSky)
GOODCODERS HELP

**Comment by ghost** [comment]
This has been fixed.
