### ISSUE TITLE
Botany3 - Bioballistic Delivery bugs

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7067]
@9600bauds
Interface for machine shows no disk, on trying to insert disk it says "There is already a data disk loaded."

Caused  by wiping a disk that is inside the machine. Pickup filled disk, use it in hand to display prompt, put it inside machine, click yes on prompt. You have just wiped a disk that was inside the machine, making the machine useless until reconstructed.

Upon deconstruction, machine will provide one excess manipulator, but lacks 1 scanning module. The empty disk will be gone, so will the seed if there was any inside before deconstruction.

**Comment by 9600bauds** [comment]
ty 4 bugreporten will fix soon
