### ISSUE TITLE
Being high as fuck will still make you say shit while dead, into deadchat

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7069]
Common to see ghosts spouting "beep... bop" against their will if someone poisoned them with Spiritbreaker

**Comment by Imagebard** [comment]
>Spiritbreaker

Shhh
Not a Bug

**Comment by Intigracy** [comment]
It's honestly pretty amusing when it happens.

**Comment by ghost** [comment]
Getting so stoned your ghost is high is a feature, isn't it?

**Comment by ghost** [comment]
"So, Patrick, how'd you die?"
"dude weed lmao"

**Comment by Intigracy** [comment]
Too funny to fix.

**Comment by Intigracy** [comment]
Do we have to fix this one, or can we close it?

**Comment by Imagebard** [comment]
Yeah, this should have been closed some time ago.

**Comment by Imagebard** [comment]
Spiritbreaker breaks spirits
Why is this issue still open

**Comment by Probe1** [comment]
Don't do drugs you filthy hippie.
