### ISSUE TITLE
When being smited by farting on a bible, re-entering your corpse sends you to nullspace

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#7072]
https://my.mixtape.moe/gefqjw.mp4
I was even able to back out of and return to nullspace, each time I did I was sent to arrivals.
I ended up sitting in Hell for what I did long enough to get kicked back to lobby, too.
The only output was ![connection ded pls restart](https://my.mixtape.moe/kgkmbm.png)
My only click on the video was return to corpse.

**Comment by Wizardcrying** [comment]
The proc for biblefarting calls dust(). Perhaps the qdel causes this?

```
/mob/living/carbon/human/dust()
    death(1)
    monkeyizing = 1
    canmove = 0
    icon = null
    invisibility = 101

    //If we have brain worms, dump 'em.
    var/mob/living/simple_animal/borer/B=has_brain_worms()
    if(B)
        B.detach()

    if(istype(src, /mob/living/carbon/human/manifested))
        anim(target = src, a_icon = 'icons/mob/mob.dmi', flick_anim = "dust-hm", sleeptime = 15)
    else
        anim(target = src, a_icon = 'icons/mob/mob.dmi', flick_anim = "dust-h", sleeptime = 15)

    new /obj/effect/decal/remains/human(loc)
    qdel(src)
```

**Comment by PJB3005** [comment]
Sounds like the corpse isn't correctly being seen as "gone".

**Comment by clusterfack** [comment]
I guess the re_enter corpse thing needs a protection against mobs in the garbage collector

**Comment by PJB3005** [comment]
@clusterfack or the mob needs to be correctly dereferenced from the mind datum or something.

**Comment by FudgePucker** [comment]
Find a way to set the background for nullspace to a gif of a spookie scary boneman dancing with a caption welcome to the ~~null space~~ bone zone.

There I fixed all the nullspace bugs.

**Comment by BarneyGumball** [comment]
Can't reproduce, was likely fixed at some point.
