### ISSUE TITLE
Stormtrooper hardsuit modification kit doesn't work on helmets

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7077]
(WEB REPORT BY: sonixapache REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7bb2614063c55865595853c3a42ea8d568e249 
> 
> General description of the issue
> Stormtrooper hardsuit modification kit doesn't work on helmets. You can use it, but no helmet actually pops out.
> 
> What you expected to happen
> Use kit on sec hardsuit helmet -> stormtrooper helmet pops out
> 
> What actually happened
> Use kit on sec hardsuit helmet -> nothing pops out
> 
> Steps to reproduce if possible
> Use modification kit on sec hardsuit helmet.

**Comment by 9600bauds** [comment]
Can you lose that which you never had?

**Comment by Imagebard** [comment]
The helmet does work, it just that the sprites aren't here/are invisible.
