### ISSUE TITLE
"Mental interface failure" displaying on non-catatonic corpses

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#7078]
Revision: db7bb2614063c55865595853c3a42ea8d568e249

> General description of the issue

A botanist had come in with around 800 damage total (not counting oxygen damage). Upon attempting to clone, I was given the message "Mental interface failure," which to my knowledge means "there is no soul to clone and there won't be one either" - as opposed to "brain not responding to scanning stimuli, please try again." Later, his chair started spinning (and he had to tell me that he wasn't catatonic in LOOC). When I brought him back to the cloning pod, he scanned fine and I was able to clone him without a problem. For the remainder of that shift, I didn't see a single corpse that said "try again," only "mental interface failure."

> What you expected to happen

This message in the cloner:
![mental interface failure 1](https://cloud.githubusercontent.com/assets/5942183/11845489/70bf180e-a414-11e5-81c5-d63d36cd3fb3.JPG)

> What actually happened

This message in the cloner:
![mental interface failure 2](https://cloud.githubusercontent.com/assets/5942183/11845493/746d22ca-a414-11e5-9cdb-b4d8dc24b5cc.JPG)

> Steps to reproduce if possible

Have a corpse with a soul (ckey?) still attached, but the soul outside of the body. Aghosting won't work, as it seems this registers as "mental interface failure" anyway.

**Comment by 9600bauds** [comment]
Does this still happen? If so this is a pretty big deal

**Comment by PJB3005** [comment]
Wait, isn't mental interface failiure the one that's "guy's not in his corpse but he might re-enter"

**Comment by Kammerjunk** [comment]
@PJB3005 To my understanding and best guess (since I can't really ask them what's up when I scan them and get an error), the error you get when the body _can_ be cloned but they're floating about as a ghost is the first message shown. I think I've also been told that the "please try again" line was specifically added for that reason, but I can't confirm that.

**Comment by 9600bauds** [comment]
It's supposed to work like this:
If they meet all the conditions for cloning but their ghost isn't in their body, then it bwoinks them and tells you to try again in 5 seconds.
If any of the conditions for cloning is not met (ghost put in a different mob, they suicided, or some other shit), you get mental interface failure.

**Comment by Kammerjunk** [comment]
In future rounds, I haven't been able to replicate this. I don't know if it was isolated or if I messed up (guessing the latter). Either way, go ahead and close this.

**Comment by 9600bauds** [comment]
I am so good I fix shit without even fixing it

**Comment by 9600bauds** [comment]
Re-open or make a new issue if it happens again
