### ISSUE TITLE
[BOX] HoS doesn't have an SPS in his locker

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#7079]
> Revision
> db7bb2614063c55865595853c3a42ea8d568e249 
> 
> General description of the issue
> All the officers get a SPS in their locker, but the HoS doesn't. You'd think it'd be slightly more important for him to get one.
> Same for the captain, for that matter.

**Comment by 9600bauds** [comment]
[Map Issue (Box)]

**Comment by PJB3005** [comment]
@9600bauds this is a code issue: he should get one in his locker via the locker definition, not via the map.
