### ISSUE TITLE
Circuit Imprinter cost is 30 Sulphuric acid, which is prohibitively high for no good reason

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7083]
Let's assume two types of Scientist/Mechanic/Derelict MoMMI, the one that builds their own chemdispenser, and the one that asks Chemistry for acid (hah)

If you ask Chemistry for acid:
A large beaker's worth of acid will only last you 3 prints. You're looking at pretty constant refills, unless you can convince the Chemist to make you 600 units in pills or something (which is far from a given). Inbetween refills, chances are you're just gonna make a chemdispenser anyways.

If you build your own chemdispenser:
You absolutely HAVE to make the chemdispenser first thing, because you only have enough starter acid for ONE print. As if both the tedium of R&D being so rigid and the tedium of having to build the chemdispenser practically every shift weren't both repetitive enough, this limitation forces even less variation and even less flexibility into R&D by making it so that you can't just print that thing you need and build the chemdispenser later, you HAVE to build it first. This is especially bad for Derelict MoMMIs, if you want a printed circuit you gotta get the chemdispenser first, even though you already have R&D maxed anyways.

There's no real gameplay or balance argument for this type of rigidness.
If you wanted to encourage Scientists to ask for acid instead of making a chemdispenser, you could lower circuit costs AND lower the starting acid, to make it a more appealing option.
If you think Scientists making a chemdispenser is fine, then there's still no reason they should have to make it first thing, let them print 2-3 things before having to make one.

If nothing else, please just give derelict MoMMIs a little bit more acid, damn

**Comment by clusterfack** [comment]
If you upgrade the circuit imprinter, it uses less acid per circuit by alot.

**Comment by Kurfursten** [comment]
That's not perfectly true, you can just increase the reservoir. So for instance raise it from 100u to 600u with large bluespace beakers. Or if you don't want to shell out the diamond, 400u still isn't bad.

The acid question is a weird one, and symptomatic of the fact that the science department gets everyone else's stuff. What purpose does the acid serve anymore? A dispenser gets built every shift just as part of routine R&D and it doesn't encourage inter-department play or put any form of cap on production.

Just throwing this out there, but here's a suggestion to solve the meta of scientists building a new chem department every shift.
- Remove acid from R&D and the chem dispenser from the roid (add a few bottles of pre-mixed Sodium Lithium Tungstate and Unstable Mutagen in place of the dispenser)
- Remove the sulphuric acid requirement from all robotics, machine, and computer boards except for a selection of 'advanced' boards (e.g.: robotics control board, AI upload board, upload modules, chem dispenser board, fabricator boards, crew monitor board)

This would mean that to build a second chemistry, science would have to at least interact with chemistry once (maybe trading some larger beakers?) - but they could also do all basic robotics and R&D without having to build their own dispenser.

**Comment by PJB3005** [comment]
@clusterfack it doesn't, it should, but there's a missing `..()` in `refreshParts()`.

**Comment by clusterfack** [comment]
Someone had ought to fix that then

**Comment by Kurfursten** [comment]
@PJB3005 Circuit printers are not built with micro lasers, which is the component that improves production cost (this is the same reason autolathes do not get cheaper with upgrades)

**Comment by PJB3005** [comment]
oh, well I guess I was wrong then.
