### ISSUE TITLE
WEEABOO MODE DOESN'T WORK

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7084]
WHERE IS MY SUOGI FANTASYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY???????

In a more serious note, weeaboo mode on admin panel doesn't actually seem to work properly, it only changes some clothes on maint(And according to some other reports, it only works if you remove your jumpsuit and put it back again).

**Comment by Exxion** [comment]
Ah fuck I wish I'd saved "This doesn't feel like alien clothing. This feels like schoolgirl."
