### ISSUE TITLE
Vampires can use hypnotise on themselves.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7090]
(WEB REPORT BY: orzorn REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7bb2614063c55865595853c3a42ea8d568e249 
> 
> General description of the issue
> Hypnotise brings up a menu with yourself included on the list. You then stare into your own eyes if you select yourself, though you are immune to your own powers.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Kurfursten** [comment]
Unrelated - and I've hassled people in the past for doing this exact thing, so I am a hypocrite here - but I'd like it if Glare/Hypnotize checked eye protection. Getting glared through sunglasses and stuff is frustrating. Besides, they still have Screech and Bat Form for escapes!

But yeah, someone should definitely fix the issue you bring up. :+1:

**Comment by Kurfursten** [comment]
@Exxion Tested, no longer appears to be a thing
