### ISSUE TITLE
Feature Request: Let scientists open exotic seed crates.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#7091]
Why can't research botanists be able to open exotic seed crates?
I mean, they already have all the gear needed to do it with the fancy air connected trays and all, why not let them open the crate?

Also before you say 'oh but it should be made exclusive to botanists, they need something over science'.
![scrnshot1](https://cloud.githubusercontent.com/assets/12202731/11860941/e3f697d2-a448-11e5-89c5-c58b0d53050b.png)

It doesn't prevent anything, it is just really annoying.

**Comment by Kurfursten** [comment]
I kinda agree with @Probe1 on this matter: I don't really like the research botanist as a role especially now that chemistry is much more important to botany, but as long as it's in the game there's no reason for it to be pointlessly annoying to work with.

I recommended polling as to whether or not we should keep the job but I don't remember if we had results.

**Comment by 9600bauds** [comment]
I kind of made chemistry less important for botany, minus the sole case of diethylamine...

**Comment by Kurfursten** [comment]
I guess it depends on your viewpoint. Before, dicerolls were so random that it felt like a botanist with tons of mutagen wasn't really going to be able to do much with it anyway. Now it's guaranteed dank stats.

**Comment by 9600bauds** [comment]
Ye but I made it so that you need less mutagen overall, and there's ways to use even less

**Comment by Probe1** [comment]
>It felt like tons of mutagen wasn't going to help anyway
but thats wrong.  that's completely wrong.

if you wanted a mutation easily you just slammed down 8 seeds and dropped 5 or 10 mutagen in each tray.  Within 2 minutes and 3-4 cycles of mutagen treatment you'd get your mutant ice peppers.

**Comment by Kurfursten** [comment]
That's not really what I was talking about. It was very easy to get subspecies but I'm talking about positive stat mutations.

If you don't care about coldsauce (used in only one recipe) or the other subspecies, stat-ups were hellish to the point of nearly pointlessness. Getting a subspecies was trivial though, and you could get it from 5-10u radium from glowshrooms.

**Comment by FudgePucker** [comment]
My thoughts on the job is that, its really convenient for if you want to do botany off station to figure out how exotic seeds and xenohydrophonics work. No chef to deal with, no bombs going off in primary hallway killing you and your plants, and no clown smashing your window for bananas. Just peace and quiet out in the middle of spees, until the xenoarch finds a death artifact.

I mean, its also convenient, because you would be able to set up a hydrophonics lab anyways, you got a circuit printer and a small walk to the west is the vox outpost with all the gear you need, all that remains is the xenohydrophonics machines and disks, and those are so fucking stupid and snowflaky I don't think the circuit boards and disks are obtainable anywhere.

**Comment by 9600bauds** [comment]
Yes they are, the disks you need to get from cargo though.

**Comment by FudgePucker** [comment]
Oh yea I guess they did get added, my bad.
But still, I think the job isn't that bad, I mean, its science, if you wanted it to be balanced with the rest of the station, then you should have reevaluated its balance once it got a fucking rapid fire syringe gun, one of the two guns not in a lock box for some fucking reason.

I love how all my arguments for science being over powered involves 'rapid fire syringe gun'.
