### ISSUE TITLE
Just having Hulk unlocked makes your throws stronger, but they go back to normal when you actually activate Hulk

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7092]
Testing showed floortiling to be significantly weaker while under the effects of Hulk than without
Hulk DOES, however, make your throws go through people, so there's that

**Comment by 9600bauds** [comment]
Tested this some more:
It turns out that just having Hulk in your mutations makes your throws stronger, however, your throws temporarily return to normal WHILE YOU'RE HULKED OUT.

**Comment by PJB3005** [comment]
That actually makes Hulk much more useful!

**Comment by 9600bauds** [comment]
I think this could be the case for other things that check for Hulk, but I haven't tested
