### ISSUE TITLE
Light Replacer can't fabricate HE lights

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7095]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7bb2614063c55865595853c3a42ea8d568e249 
> 
> General description of the issue
> Changelog makes it sound like you can use light replacers to make high efficiency lights out of glass, however this is not the case.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
Intentional. The borg one can.

**Comment by Intigracy** [comment]
This should have been done in the opposite manner tbh.

**Comment by Exxion** [comment]
Why? You can load lights into the not-borg one, but not the borg one, so the borg one is better at fabricating them

**Comment by Intigracy** [comment]
Because borgs are supposed to be inferior to meatbags.

**Comment by Exxion** [comment]
Since when?

**Comment by ComicIronic** [comment]
different*

Borgs are meant to be different to meatbags. Their lack of hands makes them inferior, which they make up for by having other strengths.
