### ISSUE TITLE
Power Alarms not clearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7097]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> db7bb2614063c55865595853c3a42ea8d568e249 
> 
> General description of the issue
> Power alarms don't seem to clear even after the specific APC reaches 100% charge.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
I can confirm this, power alarms need to just be handled in a less shit way.

**Comment by 9600bauds** [comment]
needs steps to reproduce

**Comment by 9600bauds** [comment]
closing by virtue of extremely old webreporter issue with no real info
