### ISSUE TITLE
12mm ammo impossible to acquire

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7098]
(WEB REPORT BY: pedonymous REMOTE: 158.69.55.2:7777)
db7bb2614063c55865595853c3a42ea8d568e249 

> General description of the issue
> 12mm ammo needed for assault rifles cannot be made in a lathe, it only comes in premade assault rifles

**Comment by SonixApache** [comment]
Someone suggested an ammolathe, I like the idea.

**Comment by 9600bauds** [comment]
Then we could kill off the genfab for good, after removing the one thing it still did (and extremely poorly, too)

**Comment by Kurfursten** [comment]
Adding an ammolathe would involve fixing the thing that makes the general fab suck at making ammo, which is that someone in the ancient past decided to make most forms of ammo cost an insane amount of metal.

**Comment by SonixApache** [comment]
Does anyone ever use the genfab?

**Comment by Zth--** [comment]
No. Because it's shit. That thing needs a buff

**Comment by 9600bauds** [comment]
Comic slayed it
