### ISSUE TITLE
Comic's material datums do not account for floortile/metal rod stacks and nobody noticed in months

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7099]
This means that recycling 50 floor tiles at an Autolathe gives the same amount of metal as just one.
I would fix it but it's not a superficial fix at ALL and I want to sleep

**Comment by 9600bauds** [comment]
@Kurfursten Did you get any progress on fixing this? If you're not working on it anymore, I could get on it too

**Comment by Kurfursten** [comment]
I know the solution I just didn't want to jump away from my current branch

Autolathe uses removeFrom instead of Recycle, it's an easy fix, you can hit it if you want

**Comment by 9600bauds** [comment]
Haha wow.
It's not just that one line change, ALL of Comic's material datums DO NOT WORK WITH ANYTHING STACKABLE.
For example, the check to see if the Autolathe can even hold the amount of metal that the rods would give it.

**Comment by Kurfursten** [comment]
It's because stacks don't account for amount when calculating their materials and removefrom just pulls out their material count

**Comment by 9600bauds** [comment]
They also don't account for amount in stack for the purpose of getting the material amount in them, or basically anything.
And since material datums are the same datum in all items the fix ain't that easy

**Comment by PJB3005** [comment]
the recycle proc does account for amounts if the stack correctly has it implemented (most do)

**Comment by 9600bauds** [comment]
Yes but nothing else does as far as I can see
So if you make the Autolathe use recycle() it still will think 20 floortiles give the same amount of metal as one for the purpose of calculating whether it can fit the amount of metal that the stack would give it, etc
