### ISSUE TITLE
Stormtrooper Helmet Lacks Image

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7102]
(WEB REPORT BY: rhimrifer REMOTE: 158.69.55.2:7777)
Revision: db7bb2614063c55865595853c3a42ea8d568e249

Stormtrooper helmet obtained from stormtrooper conversion kit on a security hardsuit helmet has no image so it results in a bald head.

To get a stormtrooper helmet with an image

I got a stormtrooper helmet without graphics

Use stormtrooper upgrade kit on security hardsuit helmet.

**Comment by PJB3005** [comment]
Dupe of #7077?

**Comment by ghost** [comment]
yes
