### ISSUE TITLE
Parapens are not logged

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#7104]
Is this a joke?
Are you having a chuckle?
Haha, very funny.

**Comment by Probe1** [comment]
the thing is stabbing people with pens is logged.

`ADMIN LOG: Bryant Wood (probe1) Used the pen to stab unknown () (JMP)`

`M.attack_log += text("\[[time_stamp()]\] <font color='orange'>Has been stabbed with [name]  by [user.name] ([user.ckey])</font>")`
