### ISSUE TITLE
Wall-mounted machines

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7107]
We need this fucking shit in here

 >No wall mounted chemistry dispensers
 >No wall mounted AI turrets

WHAT ARE YOU WAITING FOR?

**Comment by Kurfursten** [comment]
Wall mounted turrets seem like they would be extremely unintuitive for aiming at based on the way mountables work

**Comment by Imagebard** [comment]
Oh whatever the hell I was thinking
Doesn't really matter.

**Comment by Kurfursten** [comment]
Funny enough your dreams of wall mounted chem dispensers came true

In the form of some maps having wall mounted booze dispensers.

**Comment by Imagebard** [comment]
Oh that.
Guess not everything es horrible.
