### ISSUE TITLE
Girder sprite is on the layer under pipe sprite

### ISSUE THREAD

**Issue by invoid9** [d3athrow/vgstation13#7108]
![isthataguuurderunderpoiips](https://cloud.githubusercontent.com/assets/10618215/11878853/2a887932-a54c-11e5-804f-52a99c89429b.PNG)
![lookathatguuurder](https://cloud.githubusercontent.com/assets/10618215/11878858/31a849d6-a54c-11e5-9762-4fc5559e1e1b.PNG)
I don't know how many other items act like, but girders shouldn't look like they're under pipes.

**Comment by Intigracy** [comment]
Displaced girder*
