### ISSUE TITLE
Transport Pipes don't understand Space Pods

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7111]
Space pod can fly through the pipe right into a wall.

![transortbug](https://cloud.githubusercontent.com/assets/11136045/11879678/10b251ee-a4fd-11e5-85ed-5b564fc0dc61.png)

**Comment by 9600bauds** [comment]
they're just really good at transporting

**Comment by Kurfursten** [comment]
Can we just do away with these tubes entirely?
- They act as a perfectly safe zone, nothing can ever harm you inside one or force you out
- You can load bodies in but not take them out, meaning they're lost forever in the void of the tube
- They have all kinds of weird behavior like this

The one thing I'll grant is that meta uses them in a nice way.

**Comment by ihadtoregisterforthis** [comment]
Not really good at transporting either since they don't protect from pressure.

**Comment by Exxion** [comment]
Fixed by #15266
