### ISSUE TITLE
Medical Cyborg Syringe

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#7112]
If you switch to harm intent and jab someone with a syringe, it breaks and you have to find a new one.

If you do it with the mediborg one, it also breaks.

You cannot fix the syringe for the mediborg via charging or any other means other than getting a module reset.

**Comment by Kurfursten** [comment]
Would be nice if it worked like the switchtool: dump an old item and pick up a new one for that slot

Or just take out syringe jabbing for cyborgs HARM HARM
