### ISSUE TITLE
Alcohol is extremely toxic

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7115]
(WEB REPORT BY: senaat1 REMOTE: 158.69.55.2:7777)
Revision: b562e7a976a28f0bf87ae206f550ce51c9ea2c84

After drinking three sips from a fresh, untouched bottle of rum i dispensed from the ghetto bar's booze-o-mat my health quickly dropped into orange/dark orange territory and i got VERY drunk. Can we just remove alcohol doing any damage whatsoever? This is almost as bad as Leroy_Lightyear's cancer was.

**Comment by Senaat1** [comment]
Added info: By the time i got to medical i had 44 toxin damage and i fell into unconciousness which lasted a good 5 minutes soon after. All from three sips of rum.

**Comment by Exxion** [comment]
Fun Fact: One glass of Black Russian will get you vomiting, and I hear (though this may not be true) that one glass of Driest Martini will almost kill you.

**Comment by Killette2** [comment]
It's a feature

**Comment by Senaat1** [comment]
I used to always carry a Black Russian around but whatever chucklefuck made alcohol toxic ruined that. Revert it, i say!

**Comment by Exxion** [comment]
It should probably be toxic, but _way_ less so.

**Comment by Arthurdentist** [comment]
it shouldn't be toxic at all and I also hate fixing peoples livers after they smoke a single joint; it ruins my emulsions.

**Comment by Exxion** [comment]
I mean if you drink two bottles of whiskey in reality you're not going to have a fun time
You won't be dead, but you'll probably wish you were

**Comment by Kurfursten** [comment]
How much is 3 sips? 45u? Needs more info

**Comment by Senaat1** [comment]
3 sips as in, i grabbed a bottle and pressed z (the hotkey for use it) three times.

**Comment by Senaat1** [comment]
Which, after testing, comes down to 48 (no idea why it's 48 units but it went from 100 to 52). That's more than i expected it to be but still, i really don't think alcohol should deal any damage at all. It makes  Bartender a useless job because on top of making you drunk it also fucks you up and potentially means you have to get your liver fixed/replaced. Alcohol doesn't need damage to balance it because it doesn't do anything positive in the first place.

**Comment by ghost** [comment]
1 bottle of rum = death

**Comment by SangriaMonkey** [comment]
The toxicity killed bartending. Now people just play for the shotgun or use the big empty space as a construction area. I don't know who was trying to prove what with this silly shit but it sure didn't work.

**Comment by Senaat1** [comment]
After further research it seems like Rum is an especially potent killer for some reason. I'm pretty sure a bottle of rum will kill you quicker than lexorin will, which is a bit silly. A bottle of gin didn't do shit, three bottles of beer didn't do shit, rum fucked me up big time and vodka had a similar effect. 

Who thought this was a good idea.

**Comment by d3athrow** [comment]
i bet dylan did this

**Comment by Arthurdentist** [comment]
#7129

**Comment by Killette2** [comment]
I still like drinking myself to death, will it still damage your liver if done in excess?
