### ISSUE TITLE
fat Chemist has no spawning clothes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7116]
(WEB REPORT BY: pedonymous REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b562e7a976a28f0bf87ae206f550ce51c9ea2c84 
> 
> General description of the issue
> Spawning naked as a fat chemist
> 
> What you expected to happen
> CLOTHES
> 
> What actually happened
> NO CLOTHES
> 
> Steps to reproduce if possible
> Join game as a chemist with a fat character

**Comment by Kurfursten** [comment]
Related to  #6799

**Comment by Intigracy** [comment]
haha stupid fatty

**Comment by chatsonf** [comment]
>We still have naked fat chemists at roundstart

**Comment by 9600bauds** [comment]
Fixed by #10788
