### ISSUE TITLE
The way lights burn out is dumb and gimmicky and Bad

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7117]
Lights have a chance to burn out whenever they are switched on, with this chance increasing every time they are switched. If a light is simply left on forever and not switched, it won't burn out, but a light switched as rapidly as one can switch it will probably burn out in a matter of seconds, or a few minutes at most.
This means that persistent ghosts can burn out a few lights each in a round and powersink toggling can burn out lights in MASSIVE numbers.
However, making lights burn out after a random time spent on would either require spawn()s with random time intervals (BAD PLEASE DON'T DO IT THIS WAY) or adding something to process() for lights (which is scary but probably could be done without problems) unless someone else can think of another way, so I'm not really sure how this could be fixed.

**Comment by FudgePucker** [comment]
New idea for traitor item, power surger, it blows out all the lights on the powernet.

Maybe make it bundle only with NVGs and agent card

**Comment by Probe1** [comment]
Discussions burnt itself out 🥇 

Also code this it sounds very cool.
