### ISSUE TITLE
Someone please update the parapen info

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7118]
The in-game description of the parapen and the Wiki's description differ greatly and I'm pretty sure neither is correct. I don't know its function well enough to update them, but someone who actually uses it surely could.

**Comment by Kurfursten** [comment]
The Mark-2 Reagent-Compatible Concealable Pen (colloquially, "Paralysis Pen") is an illegal concealable stealth weapon and stylish writing object. Indistinguishable from a regular pen, upon stabbing with harmful intent, the pen transfers all of its contained reagents, and is free to be reloaded as any other container. The default pen upon purchase contains 10 units of Zombie Powder, 25 units of Impredrezine, and 15 units of Cryptobiolin. The Zombie Powder causes instant knockout and the appearance of death to casual examination. This lasts about one hundred seconds, in which time the Impredrezine will have caused so much brain damage that the subject will be unable to stand or speak coherently. Over its life, the chemical will cause 200 brain damage, leaving the victim completely helpless.

**Comment by Intigracy** [comment]
pen/sleepy used to be refillable, there's one on the nuke shuttle iirc

parapen was never refillable

**Comment by Exxion** [comment]
Fixed.
