### ISSUE TITLE
New gun-suicide songs are a bit too quiet

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7119]
"Heres to you" was so incredibly quiet I had to turn up my volume.
Also if other people kill themselves the new song overwrites the old one and the old one stops playing
That second part might be a feature but whatever

**Comment by DrCelt** [comment]
Second part is on purpose, though I could change it. Just didn't think it was a good idea to have them stack.
A bit too quiet? Eh. Maybe, but I'd need more opinions on that one

**Comment by CptWad** [comment]
add like 10% more volume
thats all it needs

**Comment by DrCelt** [comment]
10% more in what way? It's currently at 10%, should it be made to go 11% or 20%?

**Comment by CptWad** [comment]
like 20%

**Comment by ihadtoregisterforthis** [comment]
This is a serious issue right now. People suiciding are not getting mourned with a sad song because it can't be heard by anyone nearby.

**Comment by CptWad** [comment]
Eh I think I hear them better, but I dont think someone actually touched it. ill close this. Yell at me if you still want it up
