### ISSUE TITLE
Plant health not tracked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7120]
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b562e7a976a28f0bf87ae206f550ce51c9ea2c84 
> 
> General description of the issue
> Diona pods die mysteriously with no warning of ill health
> 
> What you expected to happen
> I clip diona pods, they either die or do not die on the spot, and I can plant more seeds
> 
> What actually happened
> I clip diona pods, they either die or do not die like normal, but then large amounts die later on with no warning of ill health. they just jump to death.
> 
> Steps to reproduce if possible
> plant diona seeds and use clippers to recover extra seeds and replant. Normally, you can fill many trays with only a few dead plants at the outset. Now, over 90% of plants die during the process. Combined with the new robust harvest method, this has almost entirely gimped dionas, making it even harder to get people back into the round.

**Comment by ihadtoregisterforthis** [comment]
I saw this and they were potency 35, if that changes anything.

**Comment by 9600bauds** [comment]
You shouldn't ever be able to successfully use clippers on diona seeds, what

**Comment by ghost** [comment]
Another unwanted nerf that only prevents people from playing.

We were always able to spam dionas and it was never a problem, but now you decide it must go. I call bullshit.

**Comment by ghost** [comment]
Check if this still happens with Botany3

**Comment by 9600bauds** [comment]
Will fix soon

**Comment by 9600bauds** [comment]
I hope you meant 30 potency because I have no idea how'd you manage to get it up to 35
