### ISSUE TITLE
Stun baton fails to Stun when use on Harm

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7122]
(WEB REPORT BY: abumblingidiot REMOTE: 158.69.55.2:7777)
How is this not fucking fix yet?

**Comment by 9600bauds** [comment]
bcuz it wasn't reported

**Comment by AutismSpider** [comment]
@9600bauds  this is 3rd time have reported not 1st when engi borg/mommi stun arm did nothing on harm later on emag defib doing jack shit when use on harm.
