### ISSUE TITLE
The sudden rush of air knocks you over in a few seconds!

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7125]
I've noticed that recently, the message appears several seconds before it actually happens. If you're quick, this gives you time to put away things you're holding. Also, at least once, the message appeared, but I failed to fall over (but everyone else nearby did).

**Comment by PJB3005** [comment]
I fucking bet ZAS code sets the weakened var directly, instead of using the procs, so it waits on `Life()`.

**Comment by Killette2** [comment]
You mean when falling in real life, you don't quickly put your things away neatly while stumbling?
