### ISSUE TITLE
Buttbots hear and repeat speech before players hear the original

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7126]
This is usually not a big problem, just weird. Buttbots repeat what you say immediately _before_ you say it. If there are lots of buttbots fucking up, though, this can lag speech several seconds.

**Comment by 9600bauds** [comment]
Hear() in general always executes BEFORE the message goes to the chatbox, which is weird and stupid

**Comment by Exxion** [comment]
I had guessed that was the case, but
1. Why?

EDIT: It also appears that Hear() has to FINISH executing before the text hits the chatbox, as I saw a bunch of buttbots repeat something like 20 times in 10 seconds THEN the chat went through
Fuckening
