### ISSUE TITLE
Putting anything on fire on a wooden table causes the table to burn

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7133]
(WEB REPORT BY: senaat1 REMOTE: 158.69.55.2:7777)
Revision: 24aa27ca72d4c257585c02a8919b061652f25ca7 
Title says it all, put anything burning (match, cigar, etcetera) on a wooden table and it catches fire. Surely this is a bug.

Tell me it's a bug.

**Comment by ihadtoregisterforthis** [comment]
# #7123

# It's a feature

# But why

Also pie tins were great as they were

**Comment by Intigracy** [comment]
Did you know you could burn pie tins before my change, I was just fixing a nonfunctioning check and keeping the feature.

Anyway will fix.
