### ISSUE TITLE
Sprite issue when fat with first responders jacket

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7134]
(WEB REPORT BY: lavoss REMOTE: 158.69.55.2:7777)
Sprite issue when fat with first responders jacket: Toggle buttons on and then become fat, side view is fat front view is skinny with jacket closed. Should be jacket open for both.

**Comment by Intigracy** [comment]
lol stupid fatty

**Comment by chatsonf** [comment]
Should be fixed by #10554, unwearable by fat people, and if changed a fat sprite can be added.

**Comment by 9600bauds** [comment]
>Should be fixed by #10554
