### ISSUE TITLE
Plant produce chems disappear at high potency

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7137]
Since plant products have a maximum amount of chems in them (100), only the first few chems carry onto the plant with high enough potency since there is no room for the rest.

Each chem should make up a weighted fraction of the maximum chem amount allowed. They should also be capped at 1 minimum per chem.

This plant is supposed to have 2 other chems after radium, notice how little radium there is.

![plant](https://cloud.githubusercontent.com/assets/11136045/11910217/81808904-a5f2-11e5-891a-c9b40fb21e2c.png)

**Comment by 9600bauds** [comment]
>that entire plant analyzer report

![nervous](https://cloud.githubusercontent.com/assets/6526157/11910661/d9383434-a5da-11e5-8ec9-bf2048723525.png)

**Comment by ghost** [comment]
It may seem awesome but the kudzu was really underwhelming, it spreads way too slow even at those stats. Though it does kill anyone it actually manages to sting/pull due to cyanide stingers stunning.

**Comment by 9600bauds** [comment]
I can't think of any way to fix this beside give plants room for more reagents, really
Still, 200u reagents in one plant is pretty ridiculous

**Comment by PJB3005** [comment]
@9600bauds check how much the total reagents would be, then divide the amount of each individual reagent by (total volume / container volume).

**Comment by Killette2** [comment]
Kudzu spread should be related to stats. You can work for hours on plants and the kudzu will always be underwhelming.

**Comment by 9600bauds** [comment]
It IS related to stats

**Comment by Killette2** [comment]
Which particularly?

**Comment by 9600bauds** [comment]
Maturation (usually overlooked since Production is the important stat for most) and Potency.
