### ISSUE TITLE
You can telekinetically kick vending machines and it hurts your leg

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7138]
In case it's not clear, this only works if you actually have telekinesis. The issue is that it hurts your leg and says you KICKED the machine.

**Comment by CptWad** [comment]
You can also punch down walls at range if you have hulk/gains pills

**Comment by Kurfursten** [comment]
Adjacency!

**Comment by Exxion** [comment]
I think telekinetically thumping vending machines makes sense, but it shouldn't say you kicked it or hurt your leg.

**Comment by Kurfursten** [comment]
Oh you literally meant if you have telekinesis

**Comment by Exxion** [comment]
Yes
And only if

**Comment by Kurfursten** [comment]
Maybe edit the OP to make sure that's clear

Not like you're using that description field for anything

**Comment by Shadowmech88** [comment]
Keep the ability to "kick" the machines, but change the message and make it deal brute damage to your head.

**Comment by clusterfack** [comment]
#7178
