### ISSUE TITLE
Can't teleport while stunned anymore, but cooldown

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7144]
No message or anything, just can't tp and the cooldown happens. what a shitty change with no reason.

How to reproduce: Get flashed, try to TP to genetics lab, can't.

**Comment by PJB3005** [comment]
Er, for the wizard power?

**Comment by ghost** [comment]
ye

**Comment by Steelcap** [comment]
so is the resolution that the cooldown not trigger if it fails? Or that you be allowed to tp while stunned?

**Comment by clusterfack** [comment]
Not even reproduceable

**Comment by gbasood** [comment]
Old enough to close
