### ISSUE TITLE
Allow CentComm to send in a specialist

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7147]
So currently, there are two ways stationwide disasters can be dealt with: Deathsquad or ERT. What if they could also send in a single individual with extremely powerful equipment if they chose to? Could be interesting.
Although more highly-powerful equipment _to_ give them might be necessary first.

**Comment by PJB3005** [comment]
So, basically CC-side ninja?

**Comment by Exxion** [comment]
Yes, with different equipment, sort of
I was thinking that instead of getting a lot of quite powerful powers, they get one very tough set of armor (perhaps even with initially-customizable stats, or at least selected from a few armors) and one or two _very_ powerful weapons, selected from several available.

I have an idea for what one of these weapons might be but it will be a _bitch_ to code
I guess I should get on that someday

**Comment by Imagebard** [comment]
Okay so lets review the idea
ERT/Deathsquad teams are usually sent in when the station is fucked and tons of people are dead
Your new idea will make it so only one(1(one)) dead person is chosen instead, and everybody else has to watch him.

Please tell me, what is the benefit of doing that.

**Comment by FudgePucker** [comment]
What if it is a situation where an ERT would be over kill?
Last time I was ERT I was the only member, it would have been nice to have better gear.

Also for situations where noone is dead but you still need some intervention, for example, the only two engineers just fucked off into space, you gotta send in an engine tech to set up power before 'shuttle has been called: no power.'

**Comment by mrpain666** [comment]
I can already do that manually.

Are you asking for a button to streamline it like the Deathsquad or ERT buttons do? That would be nice.
