### ISSUE TITLE
Spacepods can mostly only be interacted with when you are adjacent to their bottom left tile

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7150]
I'm almost certain this has not always been the case. If you are adjacent to the spacepod but not specifically the bottom left of it, you cannot
1. Perform construction steps on it while building it
2. Open, close, or use its maintenance hatch (I think)
3. Click-drag yourself onto it to enter it (though the verb still works for some reason)

Furthermore, the whole thing is invisible if its bottom left square is blocked from your view. This _has_ always been the case, though.

If you hadn't guessed, its bottom left is its "root" square.

**Comment by clusterfack** [comment]
Literally all the fault of byond, we could probably take some steps that may mitigate it like changing the adjacency proc to account for the fact it is multiple tiles in size

**Comment by Exxion** [comment]
But I'm like 90% sure the interaction used to work
OK maybe 80%
But I'm still pretty sure
Which is weird because nobody has fucked with adjacent.dm in any way that would affect this since I thought it worked
See now I'm wondering if I'm just crazy

**Comment by FudgePucker** [comment]
This is probably a problem that is unsolvable, goon pods have the exact same problems.

**Comment by PJB3005** [comment]
@FudgePucker well goon only cares about the big flashy features, small bugs like that be damned.
