### ISSUE TITLE
Rightclick>Pickup not working while on janicart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7153]
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Picking up items via RMB diesn't work while in the janicart. Same with pointing at things &maybe other stuff
> 
> What you expected to happen
> To be able ti pick stuff up via the RMB menue
> 
> What actually happened
> Nothing
> 
> Steps to reproduce if possible
> Sit on janicart try to pick something up or point at something via the right mouse button menue

**Comment by CptWad** [comment]
You also cannot point, which makes janicart mopping an even bigger waste of time

**Comment by Exxion** [comment]
[Feature Loss] implies this ever worked, which I do not believe is the case.

**Comment by 9600bauds** [comment]
Caused because the verb checks for canmove.
Actually it looks like a shitton of verbs check for canmove, such as opening a locker, even though their attack_hand doesn't

**Comment by Exxion** [comment]
Now opening a locker while inside it DID work before

**Comment by 9600bauds** [comment]
So the thing to do here is to go through all the verbs that check for canmove to see if they should be doing it or not.
...what even is canmove?

**Comment by Exxion** [comment]
canmove is false if you are lying down or locked to something and I think that's it.

**Comment by 9600bauds** [comment]
Okay, so, nearly all of these should be checking for lying instead of canmove, then, except for point which should be checking neither.
