### ISSUE TITLE
Blob and Nuke ops have no greentext

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7154]
There is no round end green/red information about objectives for these traitors.

**Comment by Ephx1** [comment]
@PJB3005
Wait this isn't a feature request, Nuke Ops used to actually have round end report, same with blob I'm certain.

**Comment by SonixApache** [comment]
Isn't this fixed now?

**Comment by SGuivenne** [comment]
This has sat undiscussed for 9 months, should prolly be closed or resolved or whatever.

**Comment by MadmanMartian** [comment]
Fixed by datums
