### ISSUE TITLE
Cult Antag Icon didn't appear

### ISSUE THREAD

**Issue by Rhydens** [d3athrow/vgstation13#7157]
On 19/12/2015 at around 23:40 GMT I, Rhydens Method/Wraith (90) killed Adolph Ewing who was a cultist. In this instince AE did not have the cult antagonist icon above their head and there was thus no way to differentiate them from the rest of the crew.

**Comment by CptWad** [comment]
Weird
One round as HoS I brigged a miner for stealing shit way early in the round found his cult paper and over looc the guy said he did not even know he was a cultist, meaning the icons are probably fucked

**Comment by Aurx** [comment]
Can confirm this to be happening serverside, since it's causing runtime errors

proc name: update cult icons added (/datum/game_mode/proc/update_cult_icons_added)
usr: Russel Kepplinger (ch0c0latem00se) (/mob/living/carbon/human)
usr.loc: space (288, 214, 1) (/turf/space)
src: cult (/datum/game_mode/cult)
call stack:
cult (/datum/game_mode/cult): update cult icons added(Jimmy Rattles (/datum/mind))

**Comment by ComicIronic** [comment]
What's the line number for that error?

**Comment by Aurx** [comment]
It's line 497 as of current revision.

**Comment by ComicIronic** [comment]
```
    for(var/datum/mind/cultist in cult)
        if(cultist.current)
            if(cultist.current.client)
                var/imageloc = cult_mind.current
                if(istype(cult_mind.current.loc,/obj/mecha))
                    imageloc = cult_mind.current.loc
                var/I = image('icons/mob/mob.dmi', loc = imageloc, icon_state = "cult", layer = 13)
                cultist.current.client.images += I
        if(cult_mind.current)
            if(cult_mind.current.client)
                var/imageloc = cultist.current
                if(istype(cultist.current.loc,/obj/mecha))
                    imageloc = cultist.current.loc //line 497
                var/image/J = image('icons/mob/mob.dmi', loc = imageloc, icon_state = "cult", layer = 13)
                cult_mind.current.client.images += J
```

Looks like bad sanity on the line to me. It seems to assume that every cult mind has corresponding body, which if it's causing a runtime, will stop the icon adding.
