### ISSUE TITLE
Hypothermia & Human Heat Transfer

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7158]
## TO BEGIN, OUR AIM IS TO:

make cold deadly in form of hypothermia when completely unprotected
BUT
don't pull a cancer, rather buff deadliness later than have it be too deadly now.
Please give your input/ideas.
exceptions may need to be made for cryo & space
### Two issues need to be addressed to make hypothermia real.

First: Heat transfer 
Second: Hypothermia
## Heat Transfer
- currently the average player drifts towards room temperature way way way too quickly. We must remember that in real life, the body temperature is 37, and any deviation from that even by a couple degrees brings you into hypo(or hyper)-thermia. 

My intention is fairly simple with this one, as opposed to playing with lots of different flags and other such things right now, simply focus on these aims right now.
### Aims
- check covered areas of worn clothes
- for now, simply assume all covered limbs are equally covered.
- also assume all limbs are equal
- any time when nutriment would be used, also heat up body.
- double covering = 2*2 less heat transfer, stacks. (air trapped between two layers is good!)
- heat up by shivering when getting too cold

That's fairly simple to code, I think (though likely I will be editing this sentence out later), as all of the flags and variables required for this are already in the game (I hope)
## Hypothermia

I've been researching all around for any information on this I can find, and while I will not bore you with everything I've discovered, I will warn you I'm not a biologist (or a doctor) so I've not a fucking clue what I'm doing on this, though I found http://www.nhs.uk/Conditions/Hypothermia/Pages/Symptoms.aspx to be fairly well presented, and have used this to come up with how I believe it should be implemented
#### 35-32C mild

-shivering (release energy)
-nutriment goes down way faster, make more energy
#### 32-28C moderate
- stop shivering
- effects of alcohol - dizziness, making wrong move, etc.
- slooowww movement
- forget how to use machines sometimes
- final stage: !!HOT!!
#### <28C severe
- unconcious
- pulse stops/slows
- breathing stops
- take organ damage
- die

**Comment by ihadtoregisterforthis** [comment]
- Be sure that mass hugging doesn't roast people in the act
- Be sure that the treadmills use the new behaviour once finished
- Genetic powers about fire and cold could expand the threshold

**Comment by FudgePucker** [comment]
Oh boy cold loop to distro traitor here I come!

**Comment by ghost** [comment]
so, I read into life code. Did you know, even at absolute 0, so long as you wear a helmet and have internals (no need for ANYTHING else) you won't take damage

**Comment by Killette2** [comment]
Can this make cuddling a feature?

**Comment by FudgePucker** [comment]
L-lude
You know erp is banned
What's next, hand holding?
You disgust me degenerate.

**Comment by Killette2** [comment]
It's for survival I swear!

**Comment by ghost** [comment]
here have something I found when researching: 

> When rewarming the body of a hypothermic person with the body of another person, first-aid experts often recommend that both the victim and the "rewarmer" be naked or barely dressed. This facilitates the transfer of heat from the warm person to the person with hypothermia.

**Comment by clusterfack** [comment]
No :erp:

**Comment by PJB3005** [comment]
:+1: for more realistic spess

**Comment by ghost** [comment]
Hello friends. I'm digging through life code to work on this. Don't worry, I've got a harness and shouldn't get lost. Here, have a little something I found.

``` DM
    if(loc_temp < 310.15) // a cold place
        bodytemperature += adjust_body_temperature(bodytemperature, loc_temp, 1)
    else // a hot place
        bodytemperature += adjust_body_temperature(bodytemperature, loc_temp, 1)
```

**Comment by ghost** [comment]
When you hug somebody, the warmer shares heat with the colder, but not an increase of temperature between the two or have an upper limit else you'll have assistants hugging each other till they set themselves on fire

**Comment by FudgePucker** [comment]
Upper limit should be the temp of the hotter person

**Comment by NigglyWiggly** [comment]
> He doesn't want to hug people until they burst into flames

**Comment by FudgePucker** [comment]
You can still hug someone to catch them on fire, you just have to be on fire.

**Comment by Senaat1** [comment]
Things you need to keep in mind:
Heat generated by fires or hot gas
Temperature guns 
Hot peppers/ice peppers
Plasmamen taking off their suits
Cold showers and hot showers
Cryo in general
Virus effects that affect temperatures

**Comment by Senaat1** [comment]
Frost oil in general

**Comment by ghost** [comment]
love you senaat

**Comment by Senaat1** [comment]
cryo beams from genetics

self-ignition from genetics

**Comment by ghost** [comment]
Basilisk stares

**Comment by NigglyWiggly** [comment]
Chili, coffee, and various other warm foods/drinks.

Reminder that drinking alcohol will make you feel warmer as your blood flows more or whatever, but it'll end up killing you quicker!

**Comment by TheEliminator16** [comment]
https://www.mediafire.com/?n8scagfdkfkhmiw
![mancrowave](https://cloud.githubusercontent.com/assets/8118771/12073371/7788489a-b0da-11e5-8eda-4503655d8dcf.png)
Here's my contribution. Celt asked me for a sprite of a man sized microwave that will quickly warm you up after coming out of cryo.
I give you: THE MANCROWAVE

**Comment by Killette2** [comment]
Will there be a version for women?

**Comment by ghost** [comment]
Why not just an electric heat blanket and a cup of coffee, instead of adding new container machines?

**Comment by icantthinkofanameritenow** [comment]
Now we need a third issue which I mentioned in the pull request but has yet to be memtioned here: Frostbite. 

The average unprotected person who dies in a cold environment only succumbs to hypothermia if the temperature drop is relatively gradual, but in SS13 very little that has to do with temperature is gradual. As a result, hypothermia proper should be relatively rare even when it is cold, perhaps due to only being partially protected from cold.

We're more likely to see sudden temperature changes, which in the real world would be much more likely to lead to death by gangrene as a complication of frostbite. Obviously limb damage would be the main way of working this in, and for obvious reasons cryo or medicine.should be unable to fix it in its late stages (given that there's no living tissue in the frostbitten limb left to rejuvenate). 

Instead, amputation will have to be performed or the person's life will be in danger even after they're properly warmed (constant high toxin damage as long as the limb is not removed, maybe?).

**Comment by ihadtoregisterforthis** [comment]
Warned you about the treadmills bro!!!!

I told you, dog!

**Comment by ghost** [comment]
this should've been closed, feature fulfilled.

**Comment by Killette2** [comment]
Wait

<28c = death?

I though the standard stations temp was 20c

**Comment by ghost** [comment]
you're a buck eejit, @Killette2, body temperature =/= ambient temperature, or you'd die every time you walked outside.

**Comment by clusterfack** [comment]
Humans arent cold blooded

**Comment by Killette2** [comment]
Well explain why if you go in a 20c vent @DrCelt and die/suffer 3rd degree hypothermia. Why is this a thing?

**Comment by ghost** [comment]
Christ, how behind are you?

**Comment by Killette2** [comment]
Very, but after it's been so long I will always have my doubts that everything is fixed in spaghetti code.

**Comment by ghost** [comment]
Hey man there's been a fair few months since I left and only two outstanding bugs had to be fixed after I returned: when dealing with lifecode, that's an achievement.
