### ISSUE TITLE
Soda can suggestion

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7160]
You can currently smash bottles on peoples heads with harm intent.

My suggestion is to be able to do the same with all cans.

**Comment by Exxion** [comment]
Crush them on someone's forehead?

**Comment by Killette2** [comment]
Why not? They could have had a V8, can style.

**Comment by Exxion** [comment]
Oh I wasn't disagreeing

**Comment by Kurfursten** [comment]
Unless you remove the stun, I feel like this adds too many casually accessed stuns. Boozeomat is bartender restricted (sans hack) for this reason.

**Comment by Exxion** [comment]
I was thinking the can one would just be more silly than actually useful
Like give a huge bruise and a huge chat message saying "OH GOD OH JESUS FUCK THAT HURT" but doing trivial damage and an only slightly higher than unarmed disarm chance to disarm

**Comment by Killette2** [comment]
I wasn't intending a stun at all. Getting hit with a soda can is a lot different than a glass bottle, even if the can is full.

**Comment by Intigracy** [comment]
Only if it makes you shout "CRUSH A CAN FOR JAY OWENS"

**Comment by Killette2** [comment]
RIP, cans will be forever uncrushed
