### ISSUE TITLE
Niggly's bartending dispenser and tea set are missing from the bar at round start.

### ISSUE THREAD

**Issue by Senaat1** [d3athrow/vgstation13#7162]
One of the only innovations for bartending in the past three years is missing from the bar. Surely this is an oversight.

**Comment by Exxion** [comment]
The booze dispenser completely outmodes the Booze-O-Mat
That's probably why it's in the _advanced_ bartending crate
There's no other (viable) way to get the teas/coffee though so the brewer should be there at roundstart

**Comment by Kurfursten** [comment]
The teas and coffee can be obtained by hacking the Boozeomat as per recent update

**Comment by Exxion** [comment]
Only one kind of tea per Booze-O-Mat though

**Comment by Kurfursten** [comment]
No, as of the recent update you can get all three kinds of tea at both a hot drinks machine or boozeomat

**Comment by Exxion** [comment]
Unless it was changed yet again, each machine sells one tea, picked at random. That or I'm misunderstanding how the thing works. Only one shows up on the menu, at least, unless it was changed since like two days ago.

**Comment by Kurfursten** [comment]
It only displays the name of one kind of tea but when you choose it, it picks randomly from the three. This is how all randomized food and drink options work at a vending machine (e.g.: burrito flavors, filk flavors, groan's banned soda flavors).
