### ISSUE TITLE
You should be able to experiment with antags on the test server

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7167]
People always light it on fire or blow it to shit/vine it anyways while never setting up power.

Why not make it so you can do unique things such as be a nuke ops, or turn yourself into a blob where if you eat enough of the station the round restarts.

Reasoning for this is general antag inexperience, and so more people actually have a reason to use a test server, because god forbid newbies setting up their own server and doing this themselves.

**Comment by CptWad** [comment]
Yes please :+1: 
I have wanted to test vampire shit forever

**Comment by Killette2** [comment]
I don't think vampire shit has any magical properties, or if vampires even use the bathroom at all.

**Comment by CptWad** [comment]
u cheeky cunt
