### ISSUE TITLE
Picking up an item while transforming to a monkey caused it to disappear

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7169]
Monkey self, pick up item as you're becoming monkey, item goes poof.

Bonus points if that item is a Methylin pill.

**Comment by Exxion** [comment]
Nuke disk time

**Comment by Intigracy** [comment]
How did you transform into a monkey? Were you a changeling, injected with a syringe, or did it happen in the machine?

**Comment by Kurfursten** [comment]
Most of the stuff you're wearing disappears iirc. That's what happens with the dssolve power anyway. It's an oversight.

**Comment by Intigracy** [comment]
What dissolve power? Also the issue is that he's picking up the item after his items were dropped but before his mob is deleted.

**Comment by Kurfursten** [comment]
@Intigracy I was talking about the loosely related genetics power that turns you into a skeleton. The mob change there makes a bunch of your worn items disappear permanently, probably something similar with monkeying.
