### ISSUE TITLE
Unable to fix vending machines

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7171]
(WEB REPORT BY: orzorn REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 53b0e23ac115a749876e3ef3abb5756069f46fda 
> 
> General description of the issue
> Attempting to fix a vending machine, in this case the Autodrobe will return "The Autodrobe is broken! Fix it first." no matter what tool you attempt to use.
> 
> What you expected to happen
> I would be able to fix the machine using some tool.
> 
> What actually happened
> All the tools in a standard engineer toolbelt failed to begin any sort of repair process, so the Autodrobe had to be replaced by an admin.
> 
> Steps to reproduce if possible
> Break autodrobe, then attempt to repair using a wrench, screwdriver, wirecutter, etc. They will all fail to begin and sort of deconstructing process so the machine can be fixed.

**Comment by 9600bauds** [comment]
I think you gotta use glass

**Comment by PJB3005** [comment]
Closing unless the OP can give some clarification.
