### ISSUE TITLE
Remote view can be used for claiming valids easily

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7174]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
But not in the way you think

CodenameB brought this to my attention "I noticed something that might be a serious bug. I was given remote view by the genetics team, and I noticed a confirmed changeling was at the top of the list. I then started following the second person on the list, and they also turned out to be a ling. I then noticed the list is in order of people who joined the round. I think remote view might be bugged so you can see who the traitors are because they are chosen first"

Seems that when a ling changes form, they end up at the top of the list, same would probably happen for people who have recently joined, but still it seems a bit off.

Any way to make it sort alphabetically instead?

**Comment by clusterfack** [comment]
AHHHHHHHHH holy shit is this for real

**Comment by Exxion** [comment]
WHAT A FUCK

**Comment by Intigracy** [comment]
alphabetize list when

**Comment by 9600bauds** [comment]
Hahhahahahahahahaaahaaahah

**Comment by FudgePucker** [comment]
Top kek.
Forget xray vision, this is the new power gaming power

**Comment by ghost** [comment]
Jesus, that's hilarious.

**Comment by Exxion** [comment]
So is nobody going to fix this? Because, if I'm not mistaken, the hardest part of this fix is deciding what sorting algorithm to use.

**Comment by clusterfack** [comment]
We have yet to discover if this is actually a reproduceable bug, I haven't been able to reproduce it as of yet

**Comment by Exxion** [comment]
It should be alphabetized anyway though

**Comment by CptWad** [comment]
True, alphabetical makes best sense, its how ghost follow works because I think at first ghosts had the same issue where those that joined first (Being traitors, the AI then the head of staff pick) so that was forcechanged

**Comment by Exxion** [comment]
Ghost follow is still weird. It's only partially alphabetical.

**Comment by clusterfack** [comment]
Hasn't been reproduceable desu senpais
