### ISSUE TITLE
No borer egg in deffic xenobio

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7177]
Also the map is shit.

**Comment by CptWad** [comment]
Some rooms are 2small but that's the aesthetic of the map

**Comment by Imagebard** [comment]
Someone check meta and taxi while you're at it.

**Comment by Exxion** [comment]
I'd hope Meta has a borer egg because it actually has a suitable borer pen, unlike Box

**Comment by AutismSpider** [comment]
Meta has a egg and the room is most suitable for holding broers and xenos Taxi does not have a egg or room for Borer stuff

**Comment by Duny-** [comment]
Someone told me a while ago but I've been busy with stuff since, I'll take a look at the whole new friendly borers and xenobio thing.
Also ur shit faggot
