### ISSUE TITLE
Syndicate .357 speedloaders don't actually add ammo to Syndicate .357 revolvers

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#7184]
> Revision 
> e6000b37ec0a18f9d9030891f5fb7e68052e88a4 
> 
> General description of the issue
> Attempting to load .357 speedloaders into revolvers does not actually add ammo - it empties the speedloader, but that's it.
> 
> What you expected to happen
> Apply .357 box to speedloader, apply .357 speedloader to empty revolver, acquire loaded revolver
> 
> What actually happened
> Apply .357 box to speedloader, apply .357 speedloader to empty revolver, retain empty revolver
> 
> Steps to reproduce if possible
> see above

**Comment by Steelcap** [comment]
Couldn't reproduce

**Comment by SonixApache** [comment]
Just reproduced on my own server as follows;
- Made myself a syndicate agent
- Bought a Fully Loaded Revolver package
- Bought two Ammo-357 packages
- Fired the revolver 7 times
- Grabbed a speedloader from one of the ammo boxes
- Used the speedloader on the revolver

Issue persists.

**Comment by SonixApache** [comment]
Ah, found out what's most likely the cause; the package gives you /obj/item/ammo_storage
/speedloader/a357/empty. So maybe that's why loading it doesn't work.

**Comment by SonixApache** [comment]
Actually, I can't reproduce it either now. I must've fucked something up myself.
