### ISSUE TITLE
The The Periodic Table has been hit by Admin with the electrical toolbox.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7188]
The The Periodic Table has been hit by Admin with the electrical toolbox.

**Comment by Exxion** [comment]
I've been seeing **_A LOT_** of things like this lately. Enough to make me worry that something deep within the chat system has gotten fucked up.
"a **blood-stained** the backpack"
"a the rag" And others I can't remember

EDIT: Although after actually giving this even the slightest bit of thought, I think what I mentioned is an entirely separate issue from this
This is just like an \improper that shouldn't be there
I hope

**Comment by clusterfack** [comment]
Yeah thats all it is
