### ISSUE TITLE
Polyacid in spray/smoke causes brute damage rather than burn, which breaks bones and shit, but instead does very mild toxin damage when injected (???)

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7192]
Not to mention it will make you bleed your fucking dick off.

**Comment by ghost** [comment]
Why would acid cause just burn? It dissolves your body, it makes sense it causes massive bleeding.

**Comment by Exxion** [comment]
It sure as shit shouldn't cause brute damage though
Maybe ludicrously-high burn damage should be able to bleed like brute

**Comment by 9600bauds** [comment]
> Why would acid cause just burn?

Because it BREAKS YOUR BONES NIGGA

Besides, to add to the original issue: It does toxin damage when injected, which seems to go very against both the idea that it dissolves your body, and against any logic really

**Comment by ghost** [comment]
The only issue here I see is that the metabolism damage type is wrong.

**Comment by 9600bauds** [comment]
Fun fact: Thermite does burn damage when injected :^)
