### ISSUE TITLE
All (or at least most) shuttles have light fixtures despite the fact that light fixtures do not actually work on shuttles

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7194]
The only reason the lights on shuttles are ever on is that they start on and don't update or something. I don't really know. All I know is that if you replace a light on a shuttle, it will be off and impossible to turn on. This is mildly annoying for most shuttles and mildly catastrophic for the salvage shuttle, as its spiders immediately break almost all of its lights so it can never be lit again without admin intervention or dumb things like leaving lanterns around.

Wizardcrying wanted me to explicitly mention that this also applies to the escape pods.

Also, oddly, ghosts can blink the lights on shuttles without them permanently turning off, but only once on each light. After that, they don't respond to clicks.

**Comment by clusterfack** [comment]
Fix it you mapper shits

**Comment by clusterfack** [comment]
Edit the _on variables to 1, like power_on, light_on etc

**Comment by gbasood** [comment]
#8209 should fix
