### ISSUE TITLE
vampire screech does NOT work in a mech

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7196]
died due to this this is awful

**Comment by PJB3005** [comment]
Is this even a bug, really?

It should make you deaf like that scene in the beginning of The Walking Dead, IMO.

In a mech you talk to other people through a radio.

**Comment by ghost** [comment]
not true, or how would you be able to talk to people when you're in a mech that's off?

**Comment by PJB3005** [comment]
How can mechs be atmospherically sealed then?

Also, how do you TURN OFF a mech? Drain the cell? Backup battery I suppose.

**Comment by ghost** [comment]
Sound can travel through atmospherically sealed things, nerd.

**Comment by Zth--** [comment]
Yeah but you would heard something like "nmmph nmm mph" in the best of cases

**Comment by ghost** [comment]
People can hear you scream in space, if anything screech working in mech would be consistent with the (lack of) physics this game has.

**Comment by AutismSpider** [comment]
Fine the way it is with how bull shit a vamp is right now better off on foot as a vamp then in a mech unless its a phaz.
