### ISSUE TITLE
Can't upgrade freezers with RPED

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7197]
(WEB REPORT BY: myroc REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5c3d50ac32a702f83ff00e01e257e4f2d8b2fd62 
> 
> General description of the issue
> Freezers can't be upgraded with the RPED. Trying to open the maintenance panel requires the freezer to be unanchored, but replacing the parts requires the freezer to be anchored. The freezer cannot be anchored while the maintenance panel is open or vice versa. This probably also applies to heaters, but I haven't been able to test those.
> 
> Steps to reproduce if possible
> Find freezer, unanchor it, open the panel, and try replacing the parts with an RPED.

**Comment by ihadtoregisterforthis** [comment]
I've seen this before, #6893 #6716
