### ISSUE TITLE
Vox raiders need a dedicated console to end their mission

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7199]
Shuttle movement based round end is absolute shite in every way.

**Comment by clusterfack** [comment]
Why? It seems pretty clear to everyone how it works

**Comment by ghost** [comment]
> it seems pretty clear

Seems not, since nearly all vox rounds I remember and even the most recent one ended in someone accidentally sending shuttle and round ending abruptly.

**Comment by clusterfack** [comment]
It literally prompts you with a message that says it will end the round. You cannot idiot proof it harder than this.

**Comment by ghost** [comment]
How about making it able to leave only after all their objectives are complete.

**Comment by Intigracy** [comment]
Or you can just not be an idiot and end the round prematurely.

Before clusterfack's merge yesterday the round was actually broken to where it ended when it was moving in space. Now it's fixed.

**Comment by Intigracy** [comment]
Please close.

Another example of TermedClepe being an idiot.
