### ISSUE TITLE
Monkeys and ventcrawling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7201]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
Seems they can't ventcrawl if they've got an implant somehow, or have a borer in their brain.

It's an odd one.

> How to reproduce
> Be a monkey, summon forth a borer, have borer crawl in your monkey head, try to ventcrawl, realize your head's too big to fit anymore

**Comment by Intigracy** [comment]
oh noooooo

**Comment by ghost** [comment]
On top of this, a bit of a feature request.

Borers have lipozine, which doesn't work via borer injection but works on consumption, but do not have methylin and ethylredox, which would be more useful than a chem to make you thin that doesn't work in the context

**Comment by Intigracy** [comment]
wut

**Comment by Killette2** [comment]
I second borers making Methylin, for monkeys

**Comment by Intigracy** [comment]
Are you sure it doesn't work when implanted?

I know it doesn't for borers, but are you sure on the fact that implants stop you?

**Comment by Killette2** [comment]
Uhhh what about the meth, is that in too?

**Comment by Intigracy** [comment]
Make a feature request seperately please.
