### ISSUE TITLE
Let borers produce methylin

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7213]
For those odd situations when a borer is infested in a monkey. Because why not?

**Comment by Killette2** [comment]
Bump. Same applies to helping xenos, if borers can enter xenos.

**Comment by sonime** [comment]
Borers can enter xenos, but methylin does nothing to them.

At a friend's suggestion, I'm thinking of handling this with a certain chemical that borers can make that reacts with nutriment to make the methylin. Not sure though just yet.
