### ISSUE TITLE
Manifested ghosts pushing summoner off of rune

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7214]
Manifested ghosts should be unable to push or pull the summoner off of the rune. It is not logged at all and is used just to griff and kill all ghosts by a butthurt ghost.

**Comment by CptWad** [comment]
*You cannot push this being as your manifestation is too weak.*
*You cannot pull this being as your manifestation is too weak.*

**Comment by AutismSpider** [comment]
or make manifested ghost work like the name intents summons a ghost and not half ass god mode human mob

**Comment by Imagebard** [comment]
@AutismSpider Are you trying to hijack someone's else feature request
Just make your own

**Comment by clusterfack** [comment]
Or you know we could prevent noncultists from becoming manifested ghosts

**Comment by Allspice** [comment]
Cultists are usually forced into the cult, so that wouldn't solve ghost griff. Hell, a roundstart cultist deliberately tried to fuck with Tear Reality a couple days ago.

**Comment by clusterfack** [comment]
If you were able to identify a roundstart cultist doing that why didn't you tell an admin?

**Comment by Allspice** [comment]
Someone else ahelped, Keymouser got month-long cultban for it. Point still stands, anti-cult griff isn't exclusive to noncultists. Be better to weld Tear Reality invokers to the ground, name ghosts (Manifested Ghost 123), shit like that.
