### ISSUE TITLE
Power not working for uncharged borgs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7215]
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f02a048fd9e6d26bc6cd5f2233366f01973496ae 
> 
> General description of the issue
> A borg with an uncharged cell cannot get into a charger
> 
> What you expected to happen
> To get into the charger and charge
> 
> What actually happened
> I got into the charger and was spit out
> 
> Steps to reproduce if possible
> Let your battery drain to 0 and get in a charger

**Comment by Shadowmech88** [comment]
Were you holding a directional button?
Movement in any direction causes the charger to eject you, so if you were holding the button down, you would've gotten out.
