### ISSUE TITLE
Power's nowhere to be found on the escape pods; the only light gets depowered if you replace it.

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#7216]
Why
![Tony Kornheiser enters an escape pod](http://b.1339.cf/oemroxh.png)
![whyyyyyyy](http://b.1339.cf/euonwme.png)
![whyyyyyyyyyyyyyyyyyyyyyyyyyyyyy](http://b.1339.cf/zqcjzjb.png)

**Comment by Exxion** [comment]
Duplicate of #7194

**Comment by Wizardcrying** [comment]
@Exxion Could you include escape pod somewhere in your issue?

**Comment by Exxion** [comment]
They are technically shuttles, but sure, I can mention them by name

**Comment by Wizardcrying** [comment]
@Exxion I couldn't find an issue like this when searching "escape pod" so that makes it easier for searching
![yup](http://b.1339.cf/rueefxd.png)

**Comment by Exxion** [comment]
I see
