### ISSUE TITLE
Cleaning clothing seems to preserve the blood sprite of the first blood-like entity it came in contact with

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#7218]
![a](http://b.1339.cf/kadefmi.png)
![b](http://b.1339.cf/krmgyke.png)
There was blood on it before, but the vomit never came off

**Comment by Exxion** [comment]
Only sometimes
I have no idea why or exactly when it happens, but it only sometimes does

**Comment by Shadowmech88** [comment]
Image links are dead, so I'm not exactly sure what this is describing. On top of that, it's been three years, it might not even exist anymore.
