### ISSUE TITLE
mice can do unmicelike things

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7221]
(WEB REPORT BY: msdd REMOTE: 158.69.55.2:7777)
Revision: 39460c0514aecb3a64c8ef4ceac5440d0e3d4b2d 
Mice can:
-Rotate chairs
~~-Check for pulse~~
I imagine its inhereted from carbon.

Too minor to bother with. Merely reporting for completeness' sake. 
Please have a nice day!

**Comment by Exxion** [comment]
Also, universal recorders still translate them, I believe
I was in the middle of testing this when a snake came and killed the mouse I was testing with.

**Comment by uazuaz** [comment]
another couple of things i noticed about mice:

1- if you're a dead mouse and your ghost is still inside your body, if someone pulls your body around, your chat is spammed with the message "you are too small to pull anything"

2- if you're a dead mouse and your ghost is still inside your body, you can still use the "hide" command to hide and unhide your corpse

3- as a mouse, you can push emergency floodlights ![fl](https://cloud.githubusercontent.com/assets/6170726/11953464/b5a352ce-a8a0-11e5-94c0-9dc7ec72bce5.jpg). this could sometimes be used to annoy people that are using them (is this intended?)

**Comment by Killette2** [comment]
Mice can push any objects, but I kind of like this. I used this to go under people who were dragging jukeboxes and push them in the opposite direction, because being dead makes anyone salty.

**Comment by 9600bauds** [comment]
Mice can't check pulse anymore

**Comment by Killette2** [comment]
There goes my dream of being Doctor Mouse
