### ISSUE TITLE
Meta's Recycling has flaps that serve no purpose but block people if they have no wrench/the lever isn't on

### ISSUE THREAD

**Issue by Wizardcrying** [d3athrow/vgstation13#7226]
There are flaps right in front of the chute that don't do anything at all. Why?
![whyyy](http://b.1339.cf/xyqjfcp.png)

**Comment by BestName** [comment]
They keep shitters in check.

**Comment by PJB3005** [comment]
There's always the roboburger `:^)`

**Comment by Exxion** [comment]
I hate those flaps with the burning passion of ten thousand suns.

**Comment by BestName** [comment]
I love them and hate whoever removed them from Box's mailing room.

**Comment by Exxion** [comment]
All they do is remove people from the round for no good reason
Of all the times I've gotten stuck behind them (3 times or so), my cries for help have only been heeded in a reasonable amount of time once.

**Comment by BestName** [comment]
Protip: Lay down when you get disposaled

**Comment by SonixApache** [comment]
Laying down won't help when the lever isn't on.
Anyway, if you get disposaled, maybe you should stay in the trash where you belong?

**Comment by BestName** [comment]
If you lay down inside the pipes the chute will launch you under the flaps even if the conveyor belt is off.

**Comment by Exxion** [comment]
Yes, but you get fucked for no good reason if you forget that.

**Comment by BestName** [comment]
No good reason? The reason is that you're an unrobust scrub who got flushed and forgot to rest.

**Comment by Wizardcrying** [comment]
Stop. Your toxicity is cancerous.
