### ISSUE TITLE
Butchering mice is extremely gruesome

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7229]
Thats a lot of gibs for one small rodent
Like holy christ im covered in blood and the floor has chunks of bloody meat the size of my leg where the hell did that come from

**Comment by Exxion** [comment]
Fun Fact: An actual mouse contains only a few milliliters of blood. Like 1-2.

**Comment by Kurfursten** [comment]
The easy way to fix this would be to scale gore based on size, the same way the amount of meat output works.

**Comment by unid15** [comment]
Fixed by #7257
