### ISSUE TITLE
Exiting a broken pipe while vent crawling as a slime prevents you from vent crawling again.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7230]
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777)

> Revision b113d6ff2bc16be0cb5405e7bedb14fb34d5b458

Was zipping around maint when I exited pipes because of a broken segment of distro near atmos. Later, when  found more vents I was unable to vent crawl back into the pipes. Progress bar starts then cancels. Tried multiple vents, scrubbers, nothing worked anymore

You feel a rushing draw pulling you into the vent!
You begin climbing into the ventilation system...
You feel a rushing draw pulling you into the vent!
Nicolas Fleming forces the Emergency Shutter open with a crowbar!
You begin climbing into the ventilation system...
You feel a rushing draw pulling you into the vent!
This vent is not connected to anything.
You begin climbing into the ventilation system...
You feel a rushing draw pulling you into the vent!
You begin climbing into the ventilation system...
You feel a rushing draw pulling you into the vent!
You begin climbing into the ventilation system...
You feel a rushing draw pulling you into the vent!

**Comment by ghost** [comment]
It seems you also keep the stuff can't hear you flag as well. Couldn't use intercomms with :i like I usually do

**Comment by clusterfack** [comment]
Exiting via broken pipe must not be using the standard proc to end ventcrawling which handles all of this

**Comment by 9600bauds** [comment]
No longer happens
