### ISSUE TITLE
The way campfires/stoves warm you up is weird

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7232]
Wearing a pressure suit (at least a vox one) while near a campfire will make you REALLY REALLY warm. Almost burning. I think being right beside a fully-burning stove while in a pressure suit _will_ burn you. But the same pressure suits protect you against upwards of 150 degree Celsius temperatures with no trouble. So what the fuck?

**Comment by Kurfursten** [comment]
Without looking at the code, I'm guessing it warms by directly increasing body temperature without checking for what you're wearing. Then the suit slows or prevents heat transfers out.

**Comment by ghost** [comment]
Yeah, that's about right, @Kurfursten . I'll code a fix when I'm working on hypothermia.

**Comment by Exxion** [comment]
Fixed, I'm almost certain
