### ISSUE TITLE
Can't seem to re-enter corpse as Positronic Brain Android

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#7234]
Died as Robit, can't re-enter corpse when I ghosted, I know I was completely dead because I had the pretty BSOD on the side and could see through walls. After being retrieved I couldn't re-enter my corpse as it told me I had no body. Then when the brain that I was inhabiting was taken out, I couldn't re-enter that. All happened as Positronic Brain.

**Comment by AutismSpider** [comment]
This happens with pos brains to you died it auto boots you out the body and you cant go back in.

**Comment by Ephx1** [comment]
Posibrains only then? I was a posibrain, alright then.

**Comment by AutismSpider** [comment]
not sure about mmi cyborgs needs to be test but with androids it boots you out if you die as one
