### ISSUE TITLE
pAI Display Screen

### ISSUE THREAD

**Issue by Rhydens** [d3athrow/vgstation13#7235]
When you try and change the pAI's display screen it just goes black. You can't get it to go back to the smiley face, it just remainds black the entire round as if the pAI hasn't been activated.

**Comment by clusterfack** [comment]
Didn't we fix the runtime causing this? It's possible it was left unfixed

**Comment by Rhydens** [comment]
I was just on and it doesn't seem to be fixed. It hasn't worked in a while.

**Comment by clusterfack** [comment]
Yes I've made a fix for it
