### ISSUE TITLE
You slipped! You slipped! You slipped! You slipped! You slipped!

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7238]
Everyone keeps slipping walking through hallways at start.

It says in chat "You slipped!" each time.

**Comment by ghost** [comment]
Oh God I think this is my fault.

**Comment by clusterfack** [comment]
Fucking celt amirite

**Comment by Arthurdentist** [comment]
Fucking celt wouldn't be a good idea Cluster

**Comment by ghost** [comment]
fixed
