### ISSUE TITLE
Dionas untargettable by AI core turrets

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7240]
Evolving into mature diona inside AI core caused turrets to ignore me and another diona that did the same.

**Comment by PJB3005** [comment]
Something tells me the way the turret code works is shit and it doesn't register the new mob since it never called `area/Enter()`

**Comment by Exxion** [comment]
This will presumably be fixed by #6897 but we should probably at least bandaid it until then

**Comment by FudgePucker** [comment]
So does this mean I should plant nymph pods if ai is malf so they can vent crawl then bash the ai to death?
