### ISSUE TITLE
Stupid issue but I'ma post it anyways. Spiky givings don't hurt

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7241]
When you give a spiked fruit, it doesn't check for gloves.

When you are picking up a spiked fruit/nettles, if you don't have gloves you get pricked and drop it. It does not happen when you use the give function, meaning people without gloves can hold spiky things. MUH IMMULSIONS!

**Comment by Imagebard** [comment]
>Spiky givings don't hurt

Lewd

**Comment by ghost** [comment]
@9600bauds

**Comment by 9600bauds** [comment]
tis the season for giving
