### ISSUE TITLE
Snow stuff bugs

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7242]
listo I made
>Cant shovel several tiles at once like you can with sand

>Theres some weird air issues when making the flooring with wood, sometimes it just suddenly activates zas and zoop you go flying, maybe confused if its space or not

>If you use the last amount of wood to make girders or plating for walls, the wood deconstructs, sometimes into a stack of ZERO wood

If you found any others put them below

**Comment by DrCelt** [comment]
>Cant shovel several tiles at once like you can with sand

Intentional.

>Theres some weird air issues when making the flooring with wood, sometimes it just suddenly activates zas and zoop you go flying, maybe confused if its space or not

Gah, alright, I'll fix this

>If you use the last amount of wood to make girders or plating for walls, the wood deconstructs, sometimes into a stack of ZERO wood

rip

**Comment by PJB3005** [comment]
> Cant shovel several tiles at once like you can with sand

Shitty design / 10

**Comment by clusterfack** [comment]
>>Theres some weird air issues when making the flooring with wood, sometimes it just suddenly activates zas and zoop you go flying, maybe confused if its space or not
>Gah, alright, I'll fix this


I told you not to use airless tiles

**Comment by DrCelt** [comment]
@clusterfack  I KNEW you'd gloat about that, damn it.
