### ISSUE TITLE
Open more scientist slots

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7245]
Getting roundstart scientist can be a pain in the ass

There's maybe 5 slots tops not counting robotofags and the RD but look how many jobs there are. Also the shitty way job placement works, if you have sci on high, it can make you not a scientist even if there's still an available slot where you could be a scientist where you join after the round.

RnD (lol)
toxins testing
xenobio
telescience
xenobotany
xenoarch

and half the time these assholes aren't even doing any job. Sci is never too crowded and has more coverage than engineering if you count the satellite. More scientist per round!

**Comment by Kurfursten** [comment]
There are 5 slots. I've always thought we'd be better off splitting up the science roles into two jobs, so that we have a separate slot for people working mostly on the outpost (xenoarch, anomalist, research bot).
