### ISSUE TITLE
Cowboy Hat on-character sprite is invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7246]
(WEB REPORT BY: orzorn REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

e2f98b5ccdeac08c45c4fc65241ee47e7c6a17e4 

> General description of the issue

Cowboy hat does not appear on your sprite.

> What you expected to happen

Cowboy hat to appear on my head when I equipped it.

> What actually happened

It was invisible.

> Steps to reproduce if possible

Buy cowboy hat from AutoDrobe, equip, see that it is invisible.

**Comment by Kurfursten** [comment]
Feature loss? This wasn't invisible in the past for sure. Anyone else test this?
