### ISSUE TITLE
Cleanbots don't clean sand stains from thrown sand.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7247]
People add new shit and don't give a fuck.

**Comment by 9600bauds** [comment]
Looking into this, it also doesn't seem to clean the following obj/effect/decal/cleanable:
- tomato smudges
- egg smudges
- pie smudges
- flour
- ashes
- grey gooey mass
- burnt out campfire
- broken clay pots

So this is more of a feature request than a "people adding new shit without giving a fuck" oversight. Luckily for you, I seem to give a fuck :^)

**Comment by 9600bauds** [comment]
pr tomorrow
