### ISSUE TITLE
Hacking a camera down fucks up all the other ones in the Advanced Camera Viewer

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7249]
http://s9.postimg.org/u2ggt1s65/000.png

It was a late screenshot, by the way. I could only use deactivated ones instead of only the activated ones, and only if I was in the computer when they were deactivated.

**Comment by 9600bauds** [comment]
I think the advanced cameras thing is nano, right?

**Comment by clusterfack** [comment]
NO ITS NOT, LEARN THE FUCKING DIFFERENCE

**Comment by clusterfack** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by 9600bauds** [comment]
I have never used it but I assumed it worked like the CMC which has a lot of the same issues

**Comment by 9600bauds** [comment]
At least I asked

**Comment by clusterfack** [comment]
THE CMC IS ALSO NOT NANO

**Comment by 9600bauds** [comment]
If it's not white and blue with default text formatting it's nano

**Comment by 9600bauds** [comment]
![dreamseeker_2016-02-05_02-31-19](https://cloud.githubusercontent.com/assets/6526157/12838756/90ec9ffc-cbb0-11e5-887f-8020a8d30420.png)
Dude are you sure it's not nano? It has the nanoUI logo and everything

**Comment by clusterfack** [comment]
Quite literally not nano

**Comment by 9600bauds** [comment]
Why would someone code not-nano and make it look like nano anyways????????????

**Comment by clusterfack** [comment]
So that no one would notice when it replaces nano

**Comment by 9600bauds** [comment]
Okay, it's not nano then

**Comment by gbasood** [comment]
I didn't realize that this was the bug causing cameras to disappear

**Comment by Imagebard** [comment]
Actually as of recent rounds instead of waiting for someone to fuck up a camera every camera simply disappears to save them the trouble.

**Comment by Intigracy** [comment]
Nano has the eye symbol iirc.

This is html.

**Comment by gbasood** [comment]
Error is in code not nanoui
