### ISSUE TITLE
Celt blew the salvage shuttle.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#7250]
Due to @DrCelt's recent PR, #7223, the salvage shuttle is fucking broken, as soon as it enters transit, the docking port gets moved to somewhere else on the map because it's too close to the edge of the map.

This then causes the shuttle to be unable to leave transit.

Good job @DrCelt.

**Comment by Exxion** [comment]
> 100% TESTED
> I GUARANTEE IT

**Comment by ghost** [comment]
IT WAS TESTED.
FOR THE FEATURES I INTENDED IT TO CHANGE
IT'S NOT MY FAULT THERE WERE OTHER FEATURES

**Comment by Exxion** [comment]
100%, MAN

**Comment by ghost** [comment]
shaddup

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=KUDjRZ30SNo

I'M SORRY. I SHOULDN'T HAVE MADE A PROMISE I WASN'T ABSOLUTELY SURE I COULD DELIVER

**Comment by clusterfack** [comment]
Woooow

**Comment by ghost** [comment]
I'll fix it.
