### ISSUE TITLE
Salvage shuttle can't transport spacepods

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7251]
I'm almost certain it used to be able to, but it eventually mysteriously stopped. If there is a pod on the ship when it leaves, the pod does not stay on the ship when it enters transit. I'm not sure whether it stays in place or simply vanishes.

**Comment by Ephx1** [comment]
It was definitely possible, I recall several times parking the pods in with the double doors.

**Comment by PJB3005** [comment]
It didn't happen to be put in the top doors, right?

**Comment by ghost** [comment]
shut up @PJB3005 [spoiler] he talks about the shuttle going places, which wouldn't happen [/spoiler]

**Comment by Exxion** [comment]
@PJB3005 What do you mean?

@DrCelt This has been an issue for a while but I just now reported it

**Comment by Senaat1** [comment]
I recall something similar happening to me. I parked a pod in the bottom doors while i was still in it, the shuttle moved and my screen just went black. Apparently i just stopped existing.

I had to have an admin bring me back to the shuttle.

**Comment by clusterfack** [comment]
It moves them to nullspace now, I don't know why

**Comment by Exxion** [comment]
Anyone know how long this has been an issue? Maybe it's a bug with shuttle datums/standardization.

**Comment by unid15** [comment]
It's a bug with shuttles that happens with all multi-tile objects unless their shuttle_act() is overridden to not destroy them. A quick and dirty fix would be putting this in spacepod code

```
/obj/spacepod/shuttle_act()
    return
```

but it would make spacepods unable to be destroyed by shuttles at all
