### ISSUE TITLE
Insulated pipes have the same colour as regular scrubbers pipes.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#7252]
@DrCelt.

**Comment by ihadtoregisterforthis** [comment]
I would go for a distinctive sprite rather than a different color or colour. This should also allow recoloring or recolouring them.

**Comment by PJB3005** [comment]
@ihadtoregisterforthis they used to have a distinct sprite, but @DrCelt made them use the same (the insulated one was way better, it was more white: it shaded better with custom pipe colours, the sprite also didn't have dark spots on the end of it which made regular pipelines look UGLY AS SHIT).

Because he changed the sprite, he had to tweak all the pipe colours so they remained (almost the same), but he forgot to give insulated pipes a distinct colour.

**Comment by Shadowmech88** [comment]
Since pipe painting is a thing now, I don't really think this is an issue anymore.
