### ISSUE TITLE
Better sprite for when vines are harvestable

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7258]
Right now the way vine sprites work is shitty. Could you put colored circles that somewhat resemble fruit on vines when they are ready to produce so you can easier see rather than it just being thick vines?

**Comment by 9600bauds** [comment]
when u sprite it

**Comment by Killette2** [comment]
![vines](https://cloud.githubusercontent.com/assets/5169310/11986374/d5baa75e-a99c-11e5-9447-53df92518e15.png)

Done

**Comment by 9600bauds** [comment]
now code it

**Comment by Killette2** [comment]
if harvestable = true then
new.sprite = vines.png

**Comment by 9600bauds** [comment]
code\modules\hydroponics\spreading\spreading.dm:99:error: missing condition
code\modules\hydroponics\spreading\spreading.dm:99:error: then: expected end of statement

**Comment by Killette2** [comment]
function fruit
    if harvestable = true then
            new.sprite = vines.png
end
fruit()

**Comment by 9600bauds** [comment]
returned "Killette2"

aw you edited your post
this only made sense when your post was just "function fruit"
(the joke is that you are a fruit)

**Comment by ihadtoregisterforthis** [comment]
Coding RPG: a text adventure
