### ISSUE TITLE
Can speak completely clearly while being strangled to death

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7261]
this is an issue

**Comment by PJB3005** [comment]
You know I'm unsure if this is a bug or a feature request.

**Comment by 9600bauds** [comment]
Strangle literally just applies the "in crit" var that makes you take oxyloss and is not used by anything else.
It really should make you stutter too, at least.

**Comment by clusterfack** [comment]
You can have it set the mute var or silenced var, one of those two

**Comment by AutismSpider** [comment]
Stutter for 1st 5 or 10 secs later on mute/silenced
