### ISSUE TITLE
MOTD links to Gitlab

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7275]
Gitlab is shit

**Comment by clusterfack** [comment]
You could have just said this in IRC

**Comment by 9600bauds** [comment]
???
Since when is the IRC preferable to Github for reports

**Comment by clusterfack** [comment]
When it has nothing to do with the code and can't be set by coders

**Comment by 9600bauds** [comment]
We might as well close all issues related to jukebox playlists and esoteric, unfixable BYOND bugs, then

Quit being a dork, pomf/N3X still check Github and this wasn't even fixed before being closed

**Comment by clusterfack** [comment]
Except pond rarely reads the issues to my knowledge and almost always reads irc thus my statement, stop being dramatic
