### ISSUE TITLE
Make borer to host chat more noticable

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7276]
It sucks

**Comment by sonime** [comment]
Well, how exactly does it suck?

**Comment by Ephx1** [comment]
It's a line of text, no "Your mind says:" or "Cortical borer:" it's literally just text with no specific defining feature, unlike practically everything else, so it gets lost in the mix of chat.

**Comment by sonime** [comment]
I can agree with that. I think adding "Your mind says: " would really help, especially if that prefix was bolded. I'll look around when I get home and see what I can do.

**Comment by sonime** [comment]
So now the question is exactly HOW to make it more noticeable. I like the idea of adding the message, "Your mind says: " but should it be bold? Different color?
