### ISSUE TITLE
Not getting pAI requests as Ghost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7277]
(WEB REPORT BY: necrogeek REMOTE: 158.69.55.2:7777)

> Revision  feeecb7ad6e5e589f227c1ddda90f4b3f3b4bbe9 
> 
> General description of the issue
> I receive all other requests but pAI when ghost form.  Have reset preferences and reconfigured.
> 
> What you expected to happen
> pAI request to come.  Confirmed with other ghosts that they receive them.
> 
> What actually happened
> No pAI requests come.
> 
> Steps to reproduce if possible
> Ghost formed from Borg start

**Comment by ihadtoregisterforthis** [comment]
I have the same issue for posibrains. I can click them to ping and to get on the list when active, but no chat message at all.
