### ISSUE TITLE
Computer z-level switching is fucked

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7278]
Suit sensor z-level switching is absolutely fucked.
The window to do so constantly focuses and unfocuses so you can't put in a number, and it takes like twenty tries to do so. If you're lucky to get even that working, sometimes it won't even show proper suit sensors for that area.

**Comment by Ephx1** [comment]
Yeah... wew #5945

**Comment by PJB3005** [comment]
Fucking damnit pomf.
