### ISSUE TITLE
"Observe" Function for ghosts (like observing the nuke disk) cannot be cancelled unless you rejoin.

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7279]
Lets say I want to track the nuke disk
I used "Observe"->Nuclear disk
Now I ignore the fact that my ghost body is now free from my view and can explore without me
Lets say I want to instead follow or have the camera view something else
I am now stuck in observe mode
I cannot observe anything but whats in the menu unless I rejoin
Also I guess the other bug is the ghost of you can hover around shit while your camera view does not move with it, which is weird

**Comment by Ephx1** [comment]
Did you try "Cancel Camera View"?

**Comment by CptWad** [comment]
Oh right
