### ISSUE TITLE
Taxistation - Cthulhu Brain starts with dead mobs

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7280]
The creature mobs(Huge blobs with huge mouths on them) are hostile to normal asteroid monsters, so they die off quickly during roundstart.

**Comment by FudgePucker** [comment]
That's funny, a mostly bus only mob gets its shit wrecked by astroid mobs. Goliaths don't fuckin care bout your bullshit.

**Comment by Skullyton** [comment]
They're not the same faction, so you'd have to edit this specifically for those mobs.

I guess that's why the creatures are usually contained within cult walls and asteroid blocks, but goliaths don't care about walls or what they can see, they'll tentacle slap you regardless.
