### ISSUE TITLE
Knight Armor crate breaks the cargo shuttle

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7283]
Github PR said it should be in security, but it was in the supplies section instead.

Also? 
**The cargo shuttle seems to break after Knight Crates are ordered, no more crates come through**
There's an extra listing that costs 0$ to buy on the supply menu, but it has no name to click on and therefore can't be ordered.

**Comment by 9600bauds** [comment]
This isn't the first time a crate breaks the shuttle, perhaps a notice on how to properly add crates should be added

**Comment by Imagebard** [comment]
Ahem

@doobiedoo23 
Are you here? You aren't a normal coder around here, so I think you might be missing this report.

**Comment by doobiedoo23** [comment]
I'll get right on this

**Comment by doobiedoo23** [comment]
Fixed in #7292
