### ISSUE TITLE
When making a new area with blueprints, the tile where the user is standing while making the area does not update with lighting

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7291]
title

**Comment by clusterfack** [comment]
Does it also not become part of the area then?

**Comment by ghost** [comment]
No, It's part of the area.

**Comment by ghost** [comment]
example: ![noupdate](https://cloud.githubusercontent.com/assets/7193289/12004291/536591ce-ab45-11e5-80c1-ecc97c4c9ce4.png)

**Comment by ihadtoregisterforthis** [comment]
Have you tried turning it off and on again?

**Comment by clusterfack** [comment]
It has an overlay but the overlay isn't being activated

**Comment by ghost** [comment]
@PJB3005 FIX THIS

**Comment by PJB3005** [comment]
SURE

**Comment by 9600bauds** [comment]
Stabbin' Cabin - For Sale

**Comment by ghost** [comment]
seems fixed @gbasood
