### ISSUE TITLE
Medborg Industrial Dropper does not work properly

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#7293]
You can use it to transfer stuff between containers but when used on a mob you get the message about squirting something into someones eyes but nothing is actually happening. No reagents are transferred and the dropper stays at full capacity.

This might affect other droppers as well but I've only tried it with medborgs.

**Comment by BestName** [comment]
Pleeeeease! Don't just ignore meeeeee!

**Comment by clusterfack** [comment]
Pretty sure I fixed it here
https://github.com/d3athrow/vgstation13/pull/7483
I cant reproduce it

**Comment by clusterfack** [comment]
Ah wait I see this is about the robodropper instead
