### ISSUE TITLE
Crusader helmet doesn't block hair

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#7295]
Looks kinda silly with bigger hair.

**Comment by Imagebard** [comment]
With that being said, it also makes you look smaller when you're looking to east/west and looks kinda off-place when looking north.

**Comment by Imagebard** [comment]
@doobiedoo23

**Comment by SGuivenne** [comment]
I don't think this is still a thing.

**Comment by Kurfursten** [comment]
@Exxion This is no longer a bug
