### ISSUE TITLE
Runtime error with egg.dm

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#7296]
runtime error: Cannot execute null.return air().
16:15:04 Runtime detected
Cannot execute null.return air(). at egg.dm:76

No idea what that does but it's something.

**Comment by Exxion** [comment]
Are you sure this happened _after_ Wizardcrying's fix? The line this mentions is what it would have been before that fix.

**Comment by sonime** [comment]
Yeah, I saw it in Dream Daemon when hosting local Serbia.

**Comment by Exxion** [comment]
And you updated your local server within the last two days?

**Comment by sonime** [comment]
Yes.

**Comment by 9600bauds** [comment]
Don't think this is happening anymore

**Comment by gbasood** [comment]
Don't see it in the runtime logs
