### ISSUE TITLE
"Manifested Ghost: BAN ALL THOSE WHO DRAG THE SPAWNING PERSON"

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7297]
Now, the problem here is multiple.

Every ghost that becomes manifested, then dies, is called manifested ghost in deadchat, even though when they are manifested, they have their names, either provided to them at random or their real name, it's hard to tell.

So when people are calling for the head of one of them, either because they stood around doing something else while the ghosts needed to be summoning narsie, or pushing/harming the summoner in some way that unsummons all the ghosts, it becomes hard for both parties (players and admins) to identify the troublemaker, firstly because nobody seems to keep track of the manifested ghosts names, the fact that when whoever's casting the manifest ghost moves they become ash with no traits to tell whose they were, and as mentioned above, everybody who was manifested becomes "Manifested ghost" in deadchat.

So, here's the feature request (TL;DR)
1. Remove the "Manifested ghost" nonsense, or replace it in some more sensible way, from deadchat, unless you can justify why the dead lose their identities when the summoning is broken and they lose contact with the living world, and regain them when resummoned.
2. Have some easier way to log whoever pushes, or in any way interacts with the summoner.

**Comment by AutismSpider** [comment]
#6833
