### ISSUE TITLE
Allow antibody scanner to fit on medical belts.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7298]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

It should go on the medical belt but does not. Whats up with that ?

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by FudgePucker** [comment]
Oh man you need a better title for this issue, I thought it was a major issue involving it not giving the right results, not something this minor
