### ISSUE TITLE
the command delay isn't given to trialmins

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7301]
probably a flag issue, they should definitely get it.

**Comment by sonime** [comment]
Ah, really should be part of +ADMIN or something. I get that it has to do with the server but it REALLY is useful for each admin to be able to delay round end if needed.

**Comment by Intigracy** [comment]
So they should be able to delay without being able to end after the delay?

**Comment by sonime** [comment]
That seems like a big too, seeing as how undelaying says the round will end but it never does.

**Comment by Intigracy** [comment]
It ends normally if you undelay before the round end proc is called.

i.e. before it's even delayed to begin with

**Comment by sonime** [comment]
Even after the proc is called it still says it'll end soon.

Maybe check to see of the proc was called and have it call again after the undelay is sent?
