### ISSUE TITLE
objectives issues

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7302]
something weird happened yesterday.
![111](https://cloud.githubusercontent.com/assets/6170726/12005975/6700f478-abc0-11e5-9e44-80691f074387.jpg)

**Comment by clusterfack** [comment]
B a d m i n s

**Comment by PJB3005** [comment]
Unless we can confirm it wasn't badmins...

**Comment by Imagebard** [comment]
It was admin shit, ignore it.
