### ISSUE TITLE
For some fucking reason, everyone who has multiple words in their name has TWO spaces between the first and second ones over the radio even if they only have one space between them everywhere else

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7311]
panic

**Comment by Exxion** [comment]
Actually, just the first space in any name on the radio is doubled

**Comment by Exxion** [comment]
Actually, a space is just inserted after the first word in the name on the radio. This doubles spaces on multi-word names (including essentially all human names) and just puts a space after single-word names.

**Comment by PJB3005** [comment]
@N3X15 caused this in his saycode rewrite.

**Comment by clusterfack** [comment]
Also your dying whisper can be displayed over the radio

**Comment by PJB3005** [comment]
Er, if you're next to an intercom or just if you put ; before your message, @clusterfack?

**Comment by clusterfack** [comment]
I think I saw it with a handheld radio but there may be other cases as well

**Comment by PJB3005** [comment]
Well with something like a radio it sort of makes sense, if it's close enough.

**Comment by Intigracy** [comment]
We have two of these, close one.

**Comment by Intigracy** [comment]
pls

**Comment by Intigracy** [comment]
Alright, the other issue was wrong.

It's only happening on radio chatter.

**Comment by Intigracy** [comment]
@Clusterfack do you have any idea why this would be happening?

It doesn't happen for anything except radio chatter, not even alien/changeling chat.

**Comment by clusterfack** [comment]
Nothing comes to mind, I don't know how this could occur without someone putting a replacetext to make one space two spaces for the name in radio code somewhere. And I can't imagine why someone would do that, though its possible.

**Comment by Exxion** [comment]
It's just the first space anywhere in any radio message is doubled, but this is usually in the name and otherwise just after it

**Comment by Exxion** [comment]
Actually I remembered incorrectly. Ignore that last comment and instead refer to the very first one.

**Comment by Intigracy** [comment]
I have 0 clue why this is happening.

**Comment by Intigracy** [comment]
this is fixed by the chat rewrite
who woulda guessed

**Comment by Exxion** [comment]
Is it?
There are definitely still some wacky spacing issues but I didn't check for this one specifically

**Comment by Intigracy** [comment]
Still fixed.
