### ISSUE TITLE
Cowboy Hat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7312]
(WEB REPORT BY: ekkosangen REMOTE: 158.69.55.2:7777)

> Revision: f3a9da06e13a60c8ab64754477ea75ff35693730
> 
> General description of the issue
> Cowboy hat from ranching crate does not show on character
> 
> What you expected to happen
> Character wearing a sweet cowboy hat
> 
> What actually happened
> Sadness, disappointment, and a lack of cowboy hat
> 
> Steps to reproduce if possible
> Wear cowboy hat, be sad.

**Comment by Ephx1** [comment]
#7246
