### ISSUE TITLE
Reinforced walls can't be built

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7315]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)

> Revision 
> f3a9da06e13a60c8ab64754477ea75ff35693730
> 
> General description of the issue
> Using metal rods on a wall girder has no effect, making the creation of reinforced walls impossible.
> 
> What you expected to happen
> The rods would be used to reinforce the girder.
> 
> What actually happened
> "The girder has been hit by Romeo Andreev with the metal rod."
> 
> Steps to reproduce if possible
> Just try to build a reinforced wall.

**Comment by ihadtoregisterforthis** [comment]
Try again with more rods

**Comment by clusterfack** [comment]
Either dylan
https://github.com/d3athrow/vgstation13/commit/b68f65df5a57b7ea64984f5feb6dd629799f23b3
or celt
https://github.com/d3athrow/vgstation13/commit/97797f5885bd64ec5c279f7b32d7573528ca5da1

broke this I think
