### ISSUE TITLE
Allow methylin to work on xenos

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7319]
Xenos are like monkeys, in the sense they don't have dexterity/brains to use computers. What if smart xenos?

For those odd times you are an xeno and get a borer (once they're able to produce methylin)
or when your crewmember gets staff of changed and the wizard dies 2 minutes later due to polyacid smoke, which also melts the staff.
Or when you're an xeno and the crew doesn't decide to lase- ok that one's a stretch

**Comment by clusterfack** [comment]
Who said methylin doesn't work on xenos

**Comment by PJB3005** [comment]
@clusterfack, @sonime did right [here](https://github.com/d3athrow/vgstation13/issues/7213#issuecomment-167269306).
