### ISSUE TITLE
Food items don't leave trash behind

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7328]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)

> Revision fb1bdb678cc7b01379d978887afe8c9424b61b38
> 
> General description of the issue
> No food items leave behind the trash associated with them. Bananas don't drop peels, chips from Getmore don't leave behind empty bags, etc.
> 
> What you expected to happen
> Trash would be left behind.
> 
> What actually happened
> No trash is produced.
> 
> Steps to reproduce if possible

**Comment by CptWad** [comment]
How else am I supposed to breed cockroaches in maint!

**Comment by icantthinkofanameritenow** [comment]
And think of the poor clowns who now have no way of getting banana peels.
