### ISSUE TITLE
AI Radio keys disengaging

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#7332]
After a certain amount of time in the round your AI Radio keys will disengage, specifically those that are not toggled on at roundstart. No amount of toggling or relogging will fix this. It _may_ have something to do with the AI radio being essentially a Captain's headset as this issue has happened to me as a Captain once.

**Comment by CptWad** [comment]
can confirm that it happens

**Comment by fitrandiddle** [comment]
Something weird I can add to this is that I oftentimes -continue- receiving radio channels that are disengaged on my AI comm.
It gives me something of a workaround, but seems pretty obviously bugged.

**Comment by SysadminJeroen** [comment]
I have also noticed that the AI radio is bugged, but I wasn't sure if it was a bug or a feature when I encountered it.

**Comment by Ephx1** [comment]
Now it's about a few minutes after roundstart, after hearing a few snippets from medbay it immediately shut off. This was at 12:06, goddammit.

**Comment by d3athrow** [comment]
say code a shit more news at 11

**Comment by d3athrow** [comment]
can't reproduce this locally

**Comment by CptWad** [comment]
I double dog dare you to play AI one shift to see what we mean
and because we would all love to see pomf play

**Comment by Ephx1** [comment]
Interesting, it does seem to work now but the keys themselves will be noted as disengaged if you close the menu and come back to it.
What a weird fucking bug.
