### ISSUE TITLE
Nazi Coat German doesn't translate

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#7333]
That's Soldier's Coat. It is a normal-sized item.
Ein Mantel gemacht, um die VerbÃ¼ndeten zu zerstÃ¶ren.

Real minor shit.

/obj/item/clothing/suit/soldiercoat

**Comment by ghost** [comment]
BYOND doesn't do german accents, make it "Ein Mantel gematch, um die Verbundeten zu zerstoren" (respectively ü and ö breaking)

**Comment by PJB3005** [comment]
BYOND just doesn't do Unicode, we're stuck with ASCII for all text.

**Comment by unid15** [comment]
Where's the T-thanks BYOND tag

**Comment by Kurfursten** [comment]
"ue" and "oe" you mean
