### ISSUE TITLE
Testserb crashes when picking occupation as AI.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7334]
(WEB REPORT BY: jeroen52 REMOTE: 74.63.243.98:1336)

> Revision (Should be above if you're viewing this from ingame!)
> 27fe97d
> 
> General description of the issue
> The test serb crashes when setting your occupation as AI, the server crashes not a second later after spawning as AI.
> 
> What you expected to happen
> To play as AI on the test server.
> 
> What actually happened
> Reconnecting in 10 seconds... and then the server going back online after a few minutes back at the pre-game screen.
> 
> Steps to reproduce if possible
> 1. Join the test server while it is still in the pre-game screen.
> 2. Select your occupation to be an AI.
> 3. Declare ready and wait for the game to start.
> 4. Server crashed.

**Comment by Shadowmech88** [comment]
I was able to both set my job as AI and start the game as one, the test server was fine.
