### ISSUE TITLE
Wizard powers while dead

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7335]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
>  You can still use wizard spells when dead , I was trying to clone a wizard but he would fireball as a ghost 
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by NigglyWiggly** [comment]
Can't reproduce this one.

**Comment by PJB3005** [comment]
Might be specific ones.

**Comment by NigglyWiggly** [comment]
I had fireball, time stop, lightning, jaunt, blink, and magic missile.
None of the icons appeared and none of the verbs worked

**Comment by clusterfack** [comment]
Well web report doesn't give the info necessary to reproduce this at all
