### ISSUE TITLE
Rabid slimes have gone more rabid!

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#7336]
Big slimes are splitting into Rabid slimes out of no were  on top of this rabid keep on being rabid when spray or hit by temp gun set to cold.

**Comment by gbasood** [comment]
The 'staying rabid' part was just fixed by #7758

**Comment by Imagebard** [comment]
@gbasood are you unable to close issues or something

**Comment by gbasood** [comment]
I could have sworn I saw more than one actual bug described in this issue

**Comment by ihadtoregisterforthis** [comment]
Yes, the other part is big slimes splitting into rabids "out of no were"
