### ISSUE TITLE
Buff tinfoil hat

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7340]
It should have radiation protection
Also prevent people from remote viewing you and possibly using telepathy on you.

**Comment by Intigracy** [comment]
The second two are already true.

**Comment by Kurfursten** [comment]
Yeah, it blocks most mental powers, including mind swap. It also blocks medihud and sechud.

Tinfoil hat is in a really secure spot in terms of strength, I don't think it needs rad resistance.

**Comment by ihadtoregisterforthis** [comment]
Does it block the powers of the user?

**Comment by Kurfursten** [comment]
Yes, so if you get a tinfoil hat on a cuffed mind-swap wiz apprentice, you can consider him disarmed

**Comment by Killette2** [comment]
> Wizard boards the station and anyone not wearing a tinfoil hat is now valid

**Comment by Kurfursten** [comment]
It'd be neat if the crew had that kind of coordination, but I'll put that one up there with "Chemist actually makes Ethylredox to counter Subjugate Wizard/Imidazoline to counter Blind Wizard"

**Comment by Intigracy** [comment]
Can we close this one?

**Comment by Killette2** [comment]
I don't see why not. I was thinking of closing it myself the other day when someone complained I made too many issues. In fact, since there isn't one, I might as well close it myself
