### ISSUE TITLE
Light tile remote aren't sending signals to timers

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#7346]
I'm not sure if they send a signal at all, but i'm 100% sure they are not sending to timers

**Comment by unid15** [comment]
They don't send signals, only receive them

**Comment by Zth--** [comment]
Oh... why not? I can think of some cool stuff with it.

**Comment by unid15** [comment]
When exactly should they send them?

**Comment by Zth--** [comment]
Every time it activates

**Comment by PJB3005** [comment]
@Zth-- just connect the thing activating the remote instead?

**Comment by unid15** [comment]
Yeah, try doing something like this

![](http://puu.sh/mclf5/d67f5a0ca2.png)

**Comment by Zth--** [comment]
Sure, but I think the other way it's faster and less bloat
