### ISSUE TITLE
Thermite isn't working anymore.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7348]
> Revision cd4b33f65562e199018e7ee4616743d4e8093029

Thermite no longer works on walls. splashed 5u, 10u thermite from a small beaker on regular walls and it only deconstructed normally from the welder, tried 25u on an rwall. It appears that it's either not showing up in the walls vv, the welder/wall lost its attackby, or the chem rewrite broke a var.

Failed to play the welding thermited wall message from walls/simulated/wall.dm

``` DM
user.visible_message("<span class='warning'>[user] applies \the [W] to the thermite coating \the [src] and waits</span>", \
```

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm

``` DM
/datum/reagent/thermite/reaction_turf(var/turf/simulated/T, var/volume)
    if(..()) return 1
    if(volume >= 5 && T.can_thermite)
        T.thermite = 1
        T.overlays.len = 0
        T.overlays = image('icons/effects/effects.dmi', icon_state = "thermite")
```

Normal steps to thermite a wall or rwall is to splash 5u thermite, then use al it welder, it plays the special thermitting a wall message, then after a long delay it deletes the wall and puts the thermitted wall sprite

Here's pictures showing the lack of thermiting a wall in progress and the complete lack of a response on rwalls

![thermite is broke](https://cloud.githubusercontent.com/assets/5564796/12030110/dc6e6b1e-ada5-11e5-852c-19ec76082fae.png)

**Comment by ghost** [comment]
The thermite code from chem reagents in older versions is this for reference. I don't think there's much of a difference but eh.

``` DM
/datum/reagent/thermite/reaction_turf(var/turf/T, var/volume)
    src = null
    if(volume >= 5)
        if(istype(T, /turf/simulated/wall) && T:can_thermite)
            T:thermite = 1
            T.overlays.len = 0
            T.overlays = image('icons/effects/effects.dmi',icon_state = "thermite")
    return
```

**Comment by 9600bauds** [comment]
Literally ALL reagents are broken when splashed from a beaker
 H O N K
It appears they don't have a "holder" var @dylanstrategie
