### ISSUE TITLE
Glass doors on deff derelict aren't dense

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7349]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8b0340418ac0eb1e421ff3fe200472b4f4ac5770
> 
> General description of the issue
> Glass doors on defficiency aren't dense.
> 
> What you expected to happen
> Walk into door and have it open or be stopped by it
> 
> What actually happened
> Walk through door, sometimes open it instead of walking through it
> 
> Steps to reproduce if possible
> Be on derelict
> Walk through the door
> Possibly be a MoMMI?

**Comment by PJB3005** [comment]
Age old bug: the `dir` of the windoors is fucked up.

Whatever fixed it on box: fuck you for ignoring other maps.

**Comment by Duny-** [comment]
Faggots and meaty whores breaking shit again, will fix.
