### ISSUE TITLE
[OH GOD IT'S LOOSE] Bear Traps don't work on bears.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7356]

**Comment by Imagebard** [comment]
>Feature Request

Are you serious

**Comment by Ephx1** [comment]
Yeah I'm fairly certain that was actually an implemented feature.

**Comment by ihadtoregisterforthis** [comment]
#5246 and #5519 are related and closed.

Bear traps should be of complete use against bears, not a deterrent or a little damage.

**Comment by 9600bauds** [comment]
[Feature Loss]
