### ISSUE TITLE
Trash generated by eating duplicates

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7360]
(WEB REPORT BY: orzorn REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 3aeac0b76a79799f3f1776060cef42f467ec7be8
> 
> General description of the issue
> Trash that is generated from eating food from the food vendors creates duplicates.
> 
> What you expected to happen
> Only one piece of trash to be generated.
> 
> What actually happened
> I bought Beef Jerky from a Getmore machine. Upon eating it, it produced a piece of trash in both of my hands.

I ordered a second one and it produced a piece of trash for both hands and then another one on the ground.

A third jerky did not produce any extra trash.

> Steps to reproduce if possible
> Purchase Jerky from Getmore Chocolate machine.

Eat Jerky until it produces trash.

See if Jerky produces extra trash.

**Comment by Exxion** [comment]
#7354
