### ISSUE TITLE
Objectives

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7363]
If your objective is a mime or clown, you will be asked to assassinate someone who isn't on the station, as their stage name is often different than their character name.

**Comment by Intigracy** [comment]
Still not sure how to fix this.

**Comment by clusterfack** [comment]
Fairly sure there is a proc that updates the real name, it needs to find antags with that person as their objective and change the objective name to their new real name

**Comment by ihadtoregisterforthis** [comment]
Adding the job to the objectives description could work too unless the mistery is part of the charm of doubloons, which I doubt since you can check the PDA for the crew manifest anyways.

**Comment by gbasood** [comment]
Traitor objectives are stored as datums inside mind datums.

You could loop through all traitors, check if they have a mission with them as a target, and change the description text to the new name, when clowns and mimes finish renaming themselves.
