### ISSUE TITLE
IED's cannot be made

### ISSUE THREAD

**Issue by golfer45** [d3athrow/vgstation13#7364]
The fill IED with welding fuel phase of construction does not work.

**Comment by Killette2** [comment]
I noticed this the other day while being a shi- I mean trying to stop some uhh... xenos but thought it was just the can of soda I was using. Was too lazy to report.

**Comment by clusterfack** [comment]
What? I just fixed this like 2 days ago

**Comment by Imagebard** [comment]
@clusterfack 
And it worked normally for me just today

**Comment by clusterfack** [comment]
@golfer45 @Killette2 when did you last test it?

**Comment by clusterfack** [comment]
Please reopen if you do experience this again
