### ISSUE TITLE
Recycling Furnace Constantly Moving People

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7366]
(WEB REPORT BY: platinumlobster REMOTE: 158.69.55.2:7777)
Revision: 8157db0d6e1564e95d09b4ffd827a73b47ab1425

Recycling Furnace, at least in Meta Club, will always try to take a human on one side and put them on its opposite side.

Especially with the conveyor belts off and not moving, I expected to be able to stand beside/walk by the machine with nothing happening

Standing below the machine will have the machine at its first opportunity/check toss you onto its other side

Just stand underneath it/on the intake side and it will plop on the other end of itself.  No moving conveyor belt, no buttons being pushed.

**Comment by PJB3005** [comment]
This is by design, although a way to turn it off would be good I guess.
