### ISSUE TITLE
living puddi missing its mob icon

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#7368]
Giga Puddi - Anger and Happy and normal are missing its mob icon when you cook one up with the grey slime core

**Comment by NigglyWiggly** [comment]
SOMEBODY FUCKED MY PUDDING

The icon states are all fucked up and even the right ones aren't working.

**Comment by NigglyWiggly** [comment]
IT WAS ELIM.
HIS UPDATE FUCKED ALL THE ANIMALS

**Comment by 9600bauds** [comment]
Still an issue?

**Comment by AutismSpider** [comment]
Not any more the sprite is back for all three pudding mobs

**Comment by ihadtoregisterforthis** [comment]
Must have been #7341, fixed later by #7369

**Comment by 9600bauds** [comment]
Closing this then
