### ISSUE TITLE
Lack of utilities on AI sattelite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7374]
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d30cbc334c114203f71bb30d0434beb005e2a932 
> 
> General description of the issue
> Meta station has a lack of amenities for the AI on the sattelite. It has to pick through the station to use vital consoles, scanners, or newscasters. 
> 
> What you expected to happen
> The AI is placed in some proximity to important consoles so that it can quickly use them after snapping to core
> 
> What actually happened
> Being forced to use department specific consoles, drastically increasing information gathering and search time
> 
> Steps to reproduce if possible
> It's a mapping concern, so play metastation

**Comment by ghost** [comment]
The same could be said of box, with the AI being half the station away from the RDs office
