### ISSUE TITLE
Taxi needs to be converted into a snow map

### ISSUE THREAD

**Issue by N3X15** [d3athrow/vgstation13#7376]
Taxi works far better as a terrestrial map, since it gets rid of the shuttle issue entirely and would let us have a permanent ice survival world.

Suggested by some guy in OOC.

**Comment by fitrandiddle** [comment]
I am for any and all changes adding more snow maps.

Also, taxistation's multiple parts on a snowy map would create a lot of interesting outdoor encounters, which hits me deep. I want it.

**Comment by ihadtoregisterforthis** [comment]
Gamemodes aside one of the biggest issues with game mechanics is the pipe cooling. We need snow environments fully functional before anything drastic. It is unlikely but possible that taxi won't be fit for outside snow if and when it's complete.

**Comment by icantthinkofanameritenow** [comment]
Snow map? Why not a lava map, or a desert map, or any other kind of terrestrial map?
Hell, I'd be fine with it being a swamp or even a grassland map, DrCelt's pet project already has snow covered.

**Comment by AutismSpider** [comment]
Lava normally = inst death to any thing that walks on it.

Desert or Snow map would be fine give sand stone more use for stuff.

**Comment by d3athrow** [comment]
Tundra outpost 13!

**Comment by Imagebard** [comment]
This is a pretty good idea. Just make wooden, warm walkways to other stations and it'll be fine.

**Comment by icantthinkofanameritenow** [comment]
Seriously, what is with the snow obsession? Every time we do a terrestrial map, it's fucking snow! 

DESERT 
STATION
NOW

**Comment by Imagebard** [comment]
We have no tools to protect form heat except atmospheric hardsuits and the occasional cooler on maintenance.

**Comment by icantthinkofanameritenow** [comment]
@Imagebard

Have you forgotten that firesuits are a thing? It's only worn by every other assistant who scrounges through maint, you know. 

If that doesn't work, make it a swamp or something, anything but snow.

**Comment by 9600bauds** [comment]
This is a rather solid idea honestly. It begs the question though of "why wouldn't the stations be wired together"?

**Comment by ghost** [comment]
#7158 & #6789 need to be done before this is feasible.

**Comment by ghost** [comment]
This might actually make taxi into a decent map.

The entire delivery system would have to be remade as it relies on space traveling packages.

**Comment by icantthinkofanameritenow** [comment]
@DrCelt

Hence the request to make it a different kind of terrestrial map.

**Comment by NigglyWiggly** [comment]
Honestly, this sounds like a great idea.
Should we change Centcom to be a terrestrial base too? Or is it gonna be a shuttle landing and leaving?

**Comment by Zth--** [comment]
Oh god imagine mulebots going from station to station on a desert. It's fucking great

**Comment by Blithering** [comment]
The warm suits that are on the research outpost would work. Maybe make a new locker with 2-3 of them in and dot them about the place. Delete the taxi shuttles, make pre-dug paths from station to station, and if possible replace carp swarms with bears.

**Comment by AutismSpider** [comment]
bears are way stronger then carp takes like 4 to 5 for carp to crit you a bear will do it in three tops

**Comment by Blithering** [comment]
Perhaps counter it with smaller numbers then? Have 1 or 2 spawn instead, or make it a meteor style survival event with bears forever.

**Comment by Zth--** [comment]
Random event: sandstorm with darude-sandstorm at the background

**Comment by AutismSpider** [comment]
if we use a Tundra look give the space worm mob a use for a rare event turn it into sand worm (Alitta virens) or snow worm

**Comment by ghost** [comment]
Working on it.

**Comment by ghost** [comment]
Worked on it

**Comment by ghost** [comment]
Worked more on it

**Comment by kol1th** [comment]
i helped

**Comment by ghost** [comment]
Also helping

**Comment by ghost** [comment]
close this
