### ISSUE TITLE
Fat wizards can't fit into robes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7377]
(WEB REPORT BY: yred REMOTE: 158.69.55.2:7777)

> Revision d30cbc334c114203f71bb30d0434beb005e2a932
> 
> What you expected to happen
> A fat wizard would fit into the blue wizard robes.
> 
> What actually happened
> They did not.

**Comment by Kurfursten** [comment]
Might be fun to have an alternate fatwiz set

**Comment by Arthurdentist** [comment]
Something like this?

![patriot wiz big](https://cloud.githubusercontent.com/assets/6353372/12753465/1e66c568-c9bf-11e5-8716-c2d652910661.png)

His wizmobile would be a mobility scooter as well I imagine.

**Comment by chatsonf** [comment]
Due to the addition of #10554 fat versions of currently existing wizard suits are now possible, so if anyone feels like spriting then we can have Lardinous the Bulbous or something.
