### ISSUE TITLE
Taxistation crew monitoring computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7378]
(WEB REPORT BY: kungfury REMOTE: 158.69.55.2:7777)

> General description of the issue
> Using the crew monitoring computer on taxistation displays a metaclub map instead of taxistation. Also, lack of map voting.
> 
> What you expected to happen
> Map voting. Also, seeing a taxistation map.
> 
> What actually happened
> Forced map rotation. Also, a metaclub map instead of a taxistation.
> 
> Steps to reproduce if possible
> Use the crew monitoring computer in taxi medbay. Also, re-enable mapvoting and I'll bother bugreporting more.

**Comment by 9600bauds** [comment]
> Also, re-enable mapvoting and I'll bother bugreporting more.

there's a reason why the term "boxbabbies" was coined

**Comment by MemeFury** [comment]
@9600bauds 

Well, for better or worse, this whole thing got me to join github and start seriously looking at issues in the other maps. I also put in a few things I'd change in deff at https://github.com/d3athrow/vgstation13/issues/7380

**Comment by Ephx1** [comment]
This isn't a taxistation issue, #5945.
It's an issue with the previous map being different than the current one, if you do not reconnect between the change, it'll keep the Minimap for any device with one, it would happen with Sec Cameras and the Bhangmeter.
And pomf will probably never fix it.

**Comment by PJB3005** [comment]
closing because dupe
