### ISSUE TITLE
Same Symptom twice

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7379]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

GNAv2 based virus lifeform - stamm #1555, #1555
Infection rate : 600
Spread form : Airborne
Progress Speed : 100
Effect:Full Glass Syndrome. Strength : 8. Verosity : 30. Type : 4.
Effect:Refridgerator Syndrome. Strength : 8. Verosity : 90. Type : 3.
Effect:Shutdown Syndrome. Strength : 8. Verosity : 75. Type : 2.
Effect:Shutdown Syndrome. Strength : 8. Verosity : 75. Type : 1.
Antigen pattern: A

Just figured this was a bug. Nothing big

> What you expected to happen
> Nothing
> 
> What actually happened
> That
> 
> Steps to reproduce if possible

**Comment by clusterfack** [comment]
That definitely is a bug it shouldn't be rolling a type 1 for type 2

**Comment by PJB3005** [comment]
Couldn't this cause gibbingtons (whatever the name of that symptom is) to be a stage 1 virus?

Sounds pretty [OH GOD IT'S LOOSE] to me.

**Comment by clusterfack** [comment]
Can't find anything in the code to suggest this is possible, I'm 90% sure it was badmin fuckery

**Comment by Exxion** [comment]
Knowing the reporter, that is extremely possible
