### ISSUE TITLE
Deff medbay quality of life changes

### ISSUE THREAD

**Issue by MemeFury** [d3athrow/vgstation13#7380]
Hey, this is my first issue submission, so go easy on me. Defficiency medbay currently has a few issues that could be changed to better help medbay. I don't know these issues are intended for the map, but these changes would be very nice.

**Change 1:**

> Deff does not have a crew monitoring computer accessible to medical staff without paramedic or CMO access. A potential fix is to add one between the Medbay desk requests console and medical records computer. All other stations have a monitoring computer at the desk and available to all medbay staff.

**Change 2:**

> Morgue layout is abysmally awful and has a lot of open, unused space. I made an image as to what I would change. If the morgue bed in front of the maint airlock is open, it blocks the entrance. No other map has a morgue bed potentially blocking an airlock. 
> http://i.imgur.com/xmpR6bG.png

**Change 3:**

> Weird mix of reinforced walls and normal walls in the walls shared by genetics, toxins, and science. Not a huge gripe, but it's very odd making me wonder why there were ever reinforced walls in those spots at all.
> http://i.imgur.com/LaDtaQg.png

**Comment by ghost** [comment]
@Duny

**Comment by Zth--** [comment]
About number 2, there's no reason to have double doors at the entrance. Having only one and adding more trays should do the trick

**Comment by MemeFury** [comment]
@Zth-- I agree that would be another thing to fix since deff morgue is never busy enough to justify double doors.

**Comment by Duny-** [comment]
1 is intended.

I'll take a look at 2 and 3.

**Comment by ihadtoregisterforthis** [comment]
Could 1 kindly be changed?

**Comment by Duny-** [comment]
I don't plan on changing it as long as paramedics are a thing.

**Comment by ihadtoregisterforthis** [comment]
Not all the time paramedics are a thing and not all time they are at the screen. With a more public one you reduce situations of people dead with no salvation, and "Fuck you Duny"s.

**Comment by Duny-** [comment]
It's okay I'll just tell them to play paramedic, CMO or silicon to show them how it's done.

**Comment by MemeFury** [comment]
Yours is the only map without an available console for other medical personnel in the main medbay or main desk accessible by the department. If you want the server to take your map seriously, consider changing it.

**Comment by Duny-** [comment]
Box didn't use to obsolete paramedics, it was Rei's decision when he changed medbay on Box to add a public one. I didn't agree with that decision back then, and I still don't.
The computer was always used by paramedics, the CMO, silicons, and heads; and that's plenty enough. There is a real reason to play paramedic on Deff, with the huge desert parts people tend to die in and no public computer to make their whole existence redundant.
I'm not going to make Deff into Box 2, just like Meta is just "Box with parts switched around and modified a little, oh and the AI is on a satellite like old times".

**Comment by Duny-** [comment]
How is this?
![ss 2016-01-03 at 02 39 06](https://cloud.githubusercontent.com/assets/5224390/12078977/cf563b1a-b227-11e5-9564-b8caa1d71347.png)
