### ISSUE TITLE
[Botany3] Plants that consume plasma triggered air alarms

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7382]
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777)

> Revision 9d043b85aa802adec1b29c6499931dc4b55e3757 
> Mutated a plant with "It will consume plasma from the environment." Firelocks went down and the air alarms had -2% plasma. Neither plants had produces plasma and after they were removed, the alerts ceased. Needs a sanity check I'm guessing?

**Comment by ghost** [comment]
![-2 plasma](https://cloud.githubusercontent.com/assets/5564796/12049456/adabd0ca-ae93-11e5-9b09-007c2908c72c.png)

**Comment by PJB3005** [comment]
Brilliant, NEGATIVE moles.

**Comment by FudgePucker** [comment]
OH GOD ITS LOOSE

**Comment by ihadtoregisterforthis** [comment]
This has two parts, negative plasma and the alarm activating on any nonzero amounts of plasma.

**Comment by PJB3005** [comment]
@9600bauds can you take a look at this?

**Comment by 9600bauds** [comment]
Strongly considering removing gas dependencies on plants altogether, the fact that nobody noticed this before speaks volumes of the shittiness of this mutation

**Comment by FudgePucker** [comment]
Plasma absorbing plants seem interesting, but maybe a little pointless.

Maybe make it so that if it absorbs plasma and there is plasma it mutates rapidly as it absorbs it, beyond normal mutations. Maybe let it form new chemicals from the exotic seed list, rapidly improve potency, or get plasma as a regent.

**Comment by 9600bauds** [comment]
> 138 units of mutagen

WHY
