### ISSUE TITLE
Metastation RD's office is prone to be fucked by bomb plasma

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7384]
Maybe the same for taxistation and defficiency too.

**Comment by Imagebard** [comment]
The RD Office windows used to look into toxins are also normal and instead of plasma.

**Comment by FudgePucker** [comment]
Normal pipes don't burst anymore.
If they did then you could crash the server by putting a burn chamber into distro with 100% O2, turning the station into a bomb.

**Comment by Imagebard** [comment]
Okay, I'll leave this issue up because of the 2nd part and make a new issue.
