### ISSUE TITLE
[METACLUB] Completely useless Sleeper in shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7386]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
http://puu.sh/mdBkw/73018b21cf.png
The sleeper in the shuttle's medbay which faces the wall with the defib case on it is inoperable and serves no purpose besides taking up space.
The only way for sleepers to be operated is by another party on the opposite side to inject chemicals into the person inside the sleeper.
With the injector side facing the wall it completely defeats the purpose of having a sleeper there.

**Comment by 9600bauds** [comment]
AKA it's missing a goddamn console
