### ISSUE TITLE
[TAXI] Air mix for all stations is incorrect

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7387]
It reads 20% oxygen, 80% nitrogen 20 C when it's supposed to be 1/3 oxygen 2/3 plasma at 400 C.

I'm also going to say good job on repeatedly abusing your position to force your changes without any discussion or even as much as a pull request or issue report.

> /obj/item/clothing/under/golem/coal

**Comment by PJB3005** [comment]
Ahem, 60% ~~phoron~~ plasma and 40% O<sub>2</sub> burns better.

Also [nice meme](http://niceme.me).

And I personally believe that we should disallow contributors to directly push commits unless it's bugfixes, OH GOD things or minor changes.

**Comment by FudgePucker** [comment]
Oh man this is a major issue guys.

But really, taxi should be redesigned for high pop before you force it on the players. Fuck singuloth being three feet from plasma air tank, fucking cold loop is impossible.
