### ISSUE TITLE
We have shit server startup times.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#7389]
Let's face it, we're very optimized, but server startup times are atrocious, a paradise server easily starts in a quarter of the time we do, if that.

**Comment by Exxion** [comment]
At least on my machine, I'm pretty sure the server takes longer to start than the code takes to compile.

**Comment by NigglyWiggly** [comment]
> we're very optimized

**Comment by Zth--** [comment]
Why is ours so laggy and slow? What can we do about it?

**Comment by Intigracy** [comment]
On the plus side, at least people are given plenty of time to change their preferences and to ready up.

**Comment by Zth--** [comment]
Actually not. If you join with 60 seconds left to start, not even magic will help you when trying to change your preferences

**Comment by Intigracy** [comment]
Join faster scrub.

**Comment by PJB3005** [comment]
@NigglyWiggly compared to other codebases, we're by far the best (@clusterfack will agree with this).

For things we can do about it:
- Minimap generation needs to be killed and done via BYONDtools.
- Asteroids use a SHITLOAD of server startup time, I even went so far as to think a map made of asteroid only wasn't starting at all due to how slow asteroids are for server startup.

**Comment by ghost** [comment]
@PJB3005 , @N3X15 - could we have travis do minimap generation when a new map PR is made?

**Comment by PJB3005** [comment]
@DrCelt that's no what Travis is for, at all. Travis is for checking if PRs compile so idiots don't PR broken code.

What we could (should) do is make whatever is doing the automatic changelog generation do it too.

**Comment by Intigracy** [comment]
Asteroid secret room generation code could be optimized some, couldn't it?

**Comment by PJB3005** [comment]
It's not that, I'm pretty sure it's in the edges you see around asteroids.

Also the reason caves have fucked up edges all over the place.

**Comment by ghost** [comment]
@PJB3005 I-I thought travis was what did the changelog generation

**Comment by Exxion** [comment]
Reopen

**Comment by clusterfack** [comment]
It wont matter since I already have a new PR to fix it again
