### ISSUE TITLE
There is something wrong with rabid slimes

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7392]
https://i.imgur.com/g42emFU.png

Okay, lets see what we can gleam form this image. Two fire extinguishers, and a DURAND with a SOLARIS cannon with a roboticist running off.
Certainly, there must have been some outside influence here, right? No way a rabid slime killed a sec officer and made a DURAND useless.

Except it just did.
Wasn't there an PR on this earlier? What happened to that?

**Comment by ihadtoregisterforthis** [comment]
Kill? They just might
Resist lasers? Maybe
Fire extinguishers? Not easy to hit
All of them together doesn't sound right.

Next time use foam ones if you can prepare

**Comment by Imagebard** [comment]
>Next time use foam ones if you can prepare

So, basically, if you find a rabid slime and you have no foam extinguishers you should just drop dead?

**Comment by Intigracy** [comment]
Rabid slimes are easy to handle if you aren't using lasers. Lasers are beneficial to them iirc.

**Comment by PJB3005** [comment]
IIRC: slimes die from cold temperature.

Water cools them down.

Lasers warm them up...

Though rabid slimes SHOULD go normal if sprayed with water.

**Comment by Imagebard** [comment]
By the way, the DURAND came over AFTER the security officer died.
The problem is that a slime can damage a exosuit. Aren't they supposed to "drain life force" instead of dealing brute/burn damage?

**Comment by Imagebard** [comment]
@PJB3005 at least give me a "balance" tag

**Comment by gbasood** [comment]
Water now de-rabids slimes.

**Comment by Imagebard** [comment]
I guess that's it then
