### ISSUE TITLE
Airlock is rather disfunctional

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7393]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9d043b85aa802adec1b29c6499931dc4b55e3757
> 
> General description of the issue
> Once air is out of the airlock, you can not open the door because of firelocks.
> http://puu.sh/mdRVS/b980da47aa.png
> 
> What you expected to happen
> Me still being able to open the firelocks.
> 
> What actually happened
> Yellow firelocks man, blocking me from opening the mining airlocks at Taxi.
> 
> Steps to reproduce if possible
> Go on taxi and be a shaft miner, have the external airlock open for a bit too long and you can't go back for several minutes until the air is back in the room. Shaft miners can't override the yellow airlocks.

**Comment by Exxion** [comment]
Alright which fuck put an air alarm there?

**Comment by ihadtoregisterforthis** [comment]
Shaft miners start with a crowbar on their backpacks. A solution until this gets addressed.

**Comment by FudgePucker** [comment]
And this is why it needs unsimulated airlocks or cycling airlocks.

**Comment by Exxion** [comment]
> unsimulated airlocks

NO

**Comment by FudgePucker** [comment]
No one makes issues on box's mining outpost airlocks

**Comment by SysadminJeroen** [comment]
@FudgePucker
Isn't that just two normal airlocks without any firelocks?

2015-12-30 21:13 GMT+01:00 FudgePucker notifications@github.com:

**Comment by Exxion** [comment]
A cycling airlock? No, we have actual cycling airlocks that close all doors and empty or fill the room before opening the appropriate door.

**Comment by ihadtoregisterforthis** [comment]
Taking as example the only set of cycling airlocks on Box, at the outpost, it gets bypassed with the conveyors or forced open for hard ZAS slamming. It takes to long for the fast paced action of mining.

**Comment by Exxion** [comment]
Yeah, cycling airlocks aren't fun. But unsimulated airlocks are just all-round bad. With enough vents in the intervening room, just quickly-closing airlocks work fine.

**Comment by Intigracy** [comment]
I like the cycling airlocks in viro on box. They don't bother emptying or filling the room, they just close and bolt the other door before opening the one you want.

Immediate and intelligent.

**Comment by Exxion** [comment]
Yes, but those aren't for areas with a pressure difference.

**Comment by Intigracy** [comment]
Why does a pressure difference matter if it's bolting the other door?

**Comment by PJB3005** [comment]
@Intigracy those are bolting the other door for realism reasons.

**Comment by Intigracy** [comment]
That's not what I'm saying.

If it bolts the door leading to the station, you can open the door leading outside and drain the air all you want, it'll only affect that tiny room.

If it bolts the door leading outside, you can open the door leading to the station all you want and it'll just refill from the pipes.

vs unsimulated doors where even if you bolt open both doors intentionally you can't drain any air.

**Comment by ihadtoregisterforthis** [comment]
> The sudden rush of air knocks you over!
> The sudden rush of air knocks you over!
> The sudden rush of air knocks you over!
> You slam into the wall!
> The sudden rush of air knocks you over!

Does the mining in box really have unsimulated airlocks?

**Comment by Intigracy** [comment]
no

**Comment by 9600bauds** [comment]
Replace airlocks with an elaborate contraption of conveyor belts, mass drivers, disposals piping, and plasticflaps. Guarantee no slips.
