### ISSUE TITLE
[Mapping] Taxi botany needs light switches.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7394]
Need to be able to turn your lights off so you can use other light sources for low light plants so they aren't slow as heck and possibly losing health. No black gloves and smashing lights can shock you badly.

Taxi botany lacks a grinder making it harder to radium mutate for a no-chemistry/disp flatpack mutating

**Comment by 9600bauds** [comment]
this is also important for ghosts to annoy botanists so they plant diona

**Comment by invoid9** [comment]
Light switch for the main medbay room is in the patient room. This is very silly!!

**Comment by Duny-** [comment]
Will add

**Comment by 9600bauds** [comment]
Deff portion was since addressed
