### ISSUE TITLE
Fireball is so shit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7395]
(WEB REPORT BY: yred REMOTE: 158.69.55.2:7777)

> Revision 9d043b85aa802adec1b29c6499931dc4b55e375 
> 
> General description of the issue
> Fireball exploded on a floating laser gun
> 
> What you expected to happen
> Fireball to pass over things that are not mobs and can be walked over.
> 
> What actually happened
> Fireball blew up on the laser gun and I died.

**Comment by Imagebard** [comment]
Possibly related to bug that causes objects flung around by ZAS to become solid.

**Comment by CptWad** [comment]
^^^

**Comment by ghost** [comment]
Fireball has a ton of problems. It's very likely to accidentally hit loose items or mobs, you can misfire into a nearby wall if you get airflowed, all the air ends up gone and it usually fails to one-hit incapacitate which means your tag gets the time to warn everyone

**Comment by gbasood** [comment]
Tested, does not hit on-ground non-dense items normally. Can't think of a good way to test for ZAS making things dense and fireballs though

**Comment by clusterfack** [comment]
Honestly why does airflow make things dense anyway

**Comment by PsiOmegaDelta** [comment]
IIRC airflow simply uses the same throw code that mobs do, and the throw code in turn makes objects dense for the duration of the flight to allow them to bump things.

**Comment by clusterfack** [comment]
Ours at least use totally separate code for throwing and airflow, and throwing doesn't make objects dense at all here

**Comment by 9600bauds** [comment]
Probably caused by esoteric Zany Atmospheric Shenanigans, haven't heard of this in a while, reopen this if it happens again
