### ISSUE TITLE
Slimes get hit by fire extinguisher through the sliding door on taxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7398]
(WEB REPORT BY: ch0c0latem00se REMOTE: 158.69.55.2:7777)
on taxi, if you bring a slime into the 1x2 doorway where you enter the chamber, and there is a slime right outside the door, they will also get hit by the fire extinguisher. Killed a couple slimes on accident, pretty annoying.

**Comment by ihadtoregisterforthis** [comment]
Misnamed issue

**Comment by Intigracy** [comment]
Related to #7349

**Comment by xpcybic** [comment]
Tried this earlier and it seems to happen on Box and Meta as well, probably also Deff. Stand on one side of the windoor and spray toward a slime directly on the other side and it dies.

**Comment by DamianX** [comment]
I assume this isn't a thing anymore?

**Comment by Exxion** [comment]
This was probably an issue with movecode, which has since been changed. Reopen if this *does* still happen.
