### ISSUE TITLE
medbay lights on taxi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7399]
(WEB REPORT BY: tornader REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b7e1acb378bbf85b21915ccc8de412ce409aea5e 
> 
> General description of the issue
> the lightswitch that controls medbay as a whole are in the patient rooms, buth lightswitch control the whole main area
> 
> What you expected to happen
> not that
> 
> What actually happened
> just that
> 
> Steps to reproduce if possible
> click the lightswitch in the patient room, enjoy darkness and confusion as they try to figure out how to turn the lights back on

**Comment by Exxion** [comment]
#7105

**Comment by N3X15** [comment]
Duplicate, closed.
