### ISSUE TITLE
mining

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7400]
(WEB REPORT BY: tornader REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b7e1acb378bbf85b21915ccc8de412ce409aea5e 
> 
> General description of the issue
> mining exits don't have vents and scrubbers on the science station, it would be nice for it to be able to keep pressure regular and not always being knocked down by a sudden rush of air

also on security/science the exit to the roid isn't double red airlock which would be better

> What you expected to happen
> not get knocked down by a sudden rush of air each time I go out
> 
> What actually happened
> that
> 
> Steps to reproduce if possible
> be 3 miners at round start and scutter around to get outside, it will happen to you too

**Comment by Imagebard** [comment]
Is it that hard to turn on your magboots

**Comment by 9600bauds** [comment]
I think it would be even easier to simply have the airlocks work better

**Comment by N3X15** [comment]
Which map?

**Comment by sonime** [comment]
> science station

Sounds like Taxi.
