### ISSUE TITLE
Pathogenic Incubator - virus growth level has no upper limit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7402]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
Not entirely sure if it is a feature or not, but if you leave the Pathogenic Incubator on with excess food for a prolonged amount of time, the Growth level shown never stops going up.

I assumed it was a feature as if you could force it to the latter stages, but it's currently at 585 and doesn't show signs of stopping.

> How to get this bug

Put a virus dish and about 2 small beakers worth of food into the pathogenic incubator. Turn it on and leave it. Come back and find that the virus is now larger than you.

**Comment by Kurfursten** [comment]
After it reaches useable size, size doesn't matter

Maybe an oversight but it also just doesn't matter

**Comment by 9600bauds** [comment]
Not sure what to tag this, given that it literally doesn't matter

**Comment by CptWad** [comment]
[Who cares] tag when.

**Comment by 9600bauds** [comment]
Potential hurt feelings, cannot add due to law 1
