### ISSUE TITLE
MoMMI repairs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7403]
(WEB REPORT BY: tornader REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b7e1acb378bbf85b21915ccc8de412ce409aea5e 
> 
> General description of the issue
> MoMMIs can fix themselves indefinitely even if they don't have any damage
> 
> What you expected to happen
> I expected a "there is nothing to fix" message
> 
> What actually happened
> you can just keep repairing yourself
> 
> Steps to reproduce if possible
> just spawn as a mommi and use a welder on yourself

**Comment by AutismSpider** [comment]
This happens with cyborgs too.
