### ISSUE TITLE
Mechanics Vent Pump #1

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7404]
(WEB REPORT BY: ekkosangen REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: b7e1acb378bbf85b21915ccc8de412ce409aea5e 
> 
> General description of the issue
> Ventcrawling into Mechanics Vent Pump #1 on Defficiency doesn't work, saying it isn't connected to anything.
> 
> What you expected to happen
> Able to crawl into vent
> 
> What actually happened
> "This vent is not connected to anything."
> 
> Steps to reproduce if possible
> Attempt to crawl into vent as a Diona or whatever. Maybe specific to Diona? I've only tried Diona.

**Comment by Duny-** [comment]
Will take a look

**Comment by Duny-** [comment]
BLAME FUCKING CELT
