### ISSUE TITLE
No cable coil in autolathe menu

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7416]
~~It used to, which was great~~
It never was but I have belived it should have been for so long I want to stop lying to myself

**Comment by Kurfursten** [comment]
I went through 5 years of commits and could find no time when cable coils were available at the autolathe. Maybe I missed it, though.

You could always order a tool vendor recharge pack though.

**Comment by ihadtoregisterforthis** [comment]
This is something the fabricator can do, not that anyone ever thinks of using it.

**Comment by sonime** [comment]
I totally remember coils being on there.

**Comment by CptWad** [comment]
I could have sworn I could make cable coil in autolathes

**Comment by Kurfursten** [comment]
Like I said, maybe I missed it, or maybe cable coils got renamed at some point, since I was doing ctrl+f

**Comment by CptWad** [comment]
Well its mostly for scientists/roboticists and cargo
Yeah, I can go walk all the fucking way to arrivals and grab the coil there, but on maps like taxi where theres no fucking cable coil in rnd and only one yellow toolbox in robotics that means we have to travel just to get one coil once it all runs out

**Comment by Zth--** [comment]
Do we have copper in chemistry? If we do, make cable coils buildable with it somehow

**Comment by PJB3005** [comment]
@Kurfursten I'm 100% sure they were renamed to be a subtype of `/stack` (they weren't) at some point.

**Comment by CptWad** [comment]
wow it really has never BEEN in the code
well I guess we can tag it a proper feature request then
