### ISSUE TITLE
Chem Sprayer and safty overidden chem pack.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7417]
(WEB REPORT BY: golfer45 REMOTE: 158.69.55.2:7777)

> Revision 636687c2a83b23b7efc3a052c68c16a6ced66ca8
> 
> General description of the issue
> If the chem packs safties are overided. Chemical sprayers will be unable to draw chemicals from them.
> 
> What you expected to happen
> Chemical sprayers would draw chemicals from chem packs.
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Kurfursten** [comment]
@shadowmech88

**Comment by Exxion** [comment]
If memory serves, this was intentional

**Comment by PJB3005** [comment]
Alright if @shadowmech88 can respond to this, I'll tag it appropriately.

**Comment by Shadowmech88** [comment]
Was intentional. I believe the entry for the device on the wiki's medical items page states this.

**Comment by PJB3005** [comment]
Alright then.
