### ISSUE TITLE
Map Vote Doesn't Exist

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#7418]
Map voting doesn't exist. Can we have a discussion to fix it/put it back in.

**Comment by 9600bauds** [comment]
We already do

**Comment by CptWad** [comment]
@9600bauds dude what

**Comment by 9600bauds** [comment]
have a discussion for it

**Comment by CptWad** [comment]
okay then we can close this

**Comment by Cisrox** [comment]
Can someone link the discussion please.

**Comment by 9600bauds** [comment]
https://github.com/d3athrow/vgstation13/issues/7353
