### ISSUE TITLE
Digital payment

### ISSUE THREAD

**Issue by fitrandiddle** [d3athrow/vgstation13#7425]
Hey, I'm not quite sure how feature requests work here and all, but I've got one I'd like to see.
Can AIs get the ability to send people money with their PDA functions? It comes relatively standard with crew PDAs, and would be a handy tool for herding the crew around. Money is kind of funbucks right now, but people are sometimes willing to do a lot for it.

**Comment by clusterfack** [comment]
Doesn't seem wise considering AIs start on Asimov. The first person to ask for all the AI's cash gets it.

**Comment by FudgePucker** [comment]
As a MoMMI, god fuck everything if AI can hand out my autism bux for six core SMEs on some grayshit who wants to be a millionaire.
