### ISSUE TITLE
Floating Camera in Deff Xenobio. not attached to wall

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7426]
(WEB REPORT BY: realestestate REMOTE: 158.69.55.2:7777)

> Revision 
> Attach to wall
> 
> General description of the issue
> Camera is floating a tile away from the nearest wll
> 
> What you expected to happen
> camera be on the wall
> 
> What actually happened
> 
> Steps to reproduce if possible
> walk into xenobio

**Comment by Duny-** [comment]
Disgusting

**Comment by Exxion** [comment]
> Revision
> Attach to wall
