### ISSUE TITLE
device analyzer / reverse engine issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7428]
on the wiki, the [Guide to Mechanic](http://ss13.pomf.se/wiki/index.php/Guide_to_Mechanic) says that you can scan health analyzers, advanced trauma kits, advanced burn kits, emergency defibrillators and Health Scanner HUDs, if you try to scan any of these items it says

> You successfully scan [item's name]

but when you use the analyzer on the reverse engine it says

> Sucessfully transferred 0 designs.

therefore you're unable to obtain blueprints for such items. i don't know if there are other items with the same issue.

**Comment by 9600bauds** [comment]
I believe this happens literally randomly, I haven't been able to find the cause of it

**Comment by 9600bauds** [comment]
Caused by some loaded designs being datum/design and some being datum/design/mechanic_design (which I can't find a reason for existing). Will look into this more tomorrow.

**Comment by icantthinkofanameritenow** [comment]
Can't you just remove datum/design/mechanic_design then? If it doesn't have a good reason to exist it shouldn't be in the code, and its removal and replacement with datum/design would fix the issue immediately.

I've noted intellicards have the same problem, among other items.

**Comment by 9600bauds** [comment]
Everything that can be made at the Protolathe has this issue. Will work on it some more, but in all honesty this is awful

**Comment by PJB3005** [comment]
I want to say that the design system is fucking terrible for usage within mechanics.

BUT GUESS WHY IT'S NEEDED?

Comic is a fucking idiot and made all of fabricator code terrible and dependant on designs.

**Comment by icantthinkofanameritenow** [comment]
So how do we fix THAT, then?

**Comment by 9600bauds** [comment]
I'm trying to, but I hate it

Edit: I'm about 90% done trying to fix this bullshit, but I ran into the worst kind of issues

NanoUI issues

Things are looking grim, people
