### ISSUE TITLE
Body which is bleeding stops bleeding on death.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7433]
Leading to doctors letting patients bleed out, feeding them blood and defibbing them.

**Comment by ghost** [comment]
> feature request

**Comment by 9600bauds** [comment]
Well, I mean, it's not exactly a bug.

But to really address this we need to give blood loss a facelift in general.

**Comment by ghost** [comment]
It's clearly a bug if someone's got 2 million lacerations all across their body but so long as you kill them they don't lose any blood

**Comment by 9600bauds** [comment]
It's not a "bug" in the sense that it's not a programming error, the system is just shit, it's just working as intended. Also, bleedings stop on their own after a while, doctors don't give blood to their dead patients because they want to prevent further blood loss, they do so so as to not deal with the blood loss symptoms.

**Comment by ihadtoregisterforthis** [comment]
When the heart stops pumping blood doesn't keep jetting out with the same strenght. Bleeding doesn't stop magically but it's not as extreme. The heart doesn't stop inmediately on death.
_irl_

**Comment by Exxion** [comment]
Yeah but if the heart starts again they would begin bleeding again

**Comment by Intigracy** [comment]
by the time it started again the clotting takes over, duh

**Comment by Kurfursten** [comment]
Just to be clear here, I am pretty sure if you don't patch the bleeds and defib someone, they will continue bleeding

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/21373119/40b225b2-c6ea-11e6-9f10-f45be38cb64e.png)

You're dead and the reason, other than obviously gravity, for the body to lose fluids has ceased pumping blood.  

WYCI and GET ME GRAVITY TOO.

**Comment by Exxion** [comment]
If you're going to make the realism argument, then you should also bleed way more slowly while in crit, and still bleed while dead, just VERY slowly.

**Comment by Probe1** [comment]
Realism is a gradient and we don't need to always go for the whole hog.  He's ded, he's not bleeding as fast  anymore, it improves gameplay by letting doctors treat ded people with blood.  It can be abused in edge cases I have never seen in my life.  Theoretically.

**Comment by ComicIronic** [comment]
Do you start bleeding again if you come back to life?

**Comment by Kurfursten** [comment]
Yeah. Bleeding is called as part of Life() but a big swathe of procs are skipped if the mob is dead. Another example is reagent processing.

**Comment by ComicIronic** [comment]
Then I don't really care and this seems fine.
