### ISSUE TITLE
Crew monitoring map not working right

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7436]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> After a map change the crew monitor keeps the old maps map
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible
> Switch maps a few times and look at the monitor , same thing with cameras sometimes

**Comment by ihadtoregisterforthis** [comment]
#5945
