### ISSUE TITLE
silicons and round end infos

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7437]
round end informations doen't show player's name for silicons anymore.

also, i was the emagged MoMMi MSX this round; someone destroyed me leaving just debris and i was still alive and capable of talking, then i ghosted but, as you can see, round end infos say that i survived.

![111](https://cloud.githubusercontent.com/assets/6170726/12068074/e44cac08-b005-11e5-8569-778127acc69e.jpg)

**Comment by BestName** [comment]
I'm fairly sure this only happens when the player ghosts.

**Comment by CptWad** [comment]
Its if they leave their body, it happens. Dead people who leave their robot shells or just catatonics dont show up on hte round end

**Comment by uazuaz** [comment]
@BestName  @CptWad 
you're right, this explains why names aren't shown. by the way it's still weird that someone destroyed me, there were only debris (no MMI) and i was still capable of talking.

**Comment by SGuivenne** [comment]
This is definitely fixed now.

**Comment by DamianX** [comment]
definitely not

**Comment by DamianX** [comment]
now it is, though
