### ISSUE TITLE
Disposals bins still explode the floor plating when receiving an item (calling ex_act for some reason?)

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7440]
I don't know what the fuck this is but I'm pretty sure it should NOT be happening. Been going on for as long as I remember.

**Comment by ihadtoregisterforthis** [comment]
#6627
Looks like a feature that noone knows why it exists. Not really a bug

**Comment by 9600bauds** [comment]
but WHY?

**Comment by Exxion** [comment]
I blame Bay

**Comment by Zth--** [comment]
Not a bug. No one will complain if this feature gets removed tho

**Comment by 9600bauds** [comment]
I mean, it makes absolutely no sense since the bin sticks out from the floor. It's not like the package is physically bursting through the floor in order to be mailed or anything.

**Comment by ghost** [comment]
Just remove it, it makes no sense and triggers everyone's autism when Cargo starts mailing shit

**Comment by clusterfack** [comment]
I'm pretty sure it's supposed to work such that if you're in like a normal disposal pipe and it pops you out it should break the floor tile. 

But it works on ALL disposal pipes, including the ones that have holes normally. The trash bin one and the type in the mailing office that expels stuff normally should not be breaking tiles, but any other disposal pipe that needs to expel contents should.

**Comment by ghost** [comment]
In theory, the only time disposal pipes expel things outside of disposal bins is pretty much when the pipe was cut/exploded, which is another case where it doesn't make sense

Given the disposal pipes are basically trash disposal circuits, it would make sense that they are big enough to carry virtually anything anyways

**Comment by clusterfack** [comment]
Why is that a case that doesn't make sense dylan? Explosions can damage pipes underneath floor tiles when they occur which I'm fairly sure is what this code segment is exactly for
