### ISSUE TITLE
Ghosts can't read books

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7444]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> eefe5147fd2e19ed776d4a7d7a9af32a55fc4a79 
> 
> General description of the issue
> Ghosts can not read books
> 
> What you expected to happen
> Being able to read an awful porn novel that was laid on medbay's desk while observing
> 
> What actually happened
> Dindu shit
> 
> Steps to reproduce if possible
> Be ghost
> Try to read
> Fail to read 
> Miss out on porn
> Earth shattering bug

**Comment by clusterfack** [comment]
Steps to fix

Step 1 - Become living in some way
Step 2 - Read book

**Comment by Ephx1** [comment]
Only two of the six normal ways to get back into the round can read books! Dionae and Golems, pAIs, borers, mice, and positronic brains cannot.
Funny, the most advanced combination of machine and man, and they can't read books.

**Comment by clusterfack** [comment]
Posibrains can become mommis which can

**Comment by 9600bauds** [comment]
Let's think about this logically.

Why should observers not be able to read books, which are purely flavor?

**Comment by clusterfack** [comment]
Because having more living players around reading books adds even more flavor

**Comment by ghost** [comment]
Should just allow observers to read books

**Comment by 9600bauds** [comment]
I'd just like to say that the "just like become living" reasoning is completely asinine, because it relies on the conditions that 1) "People are ghosts just because they want to", and 2) "They can just stop being ghosts and join the round whenever they want to".

Needless to say that both are completely detached from reality.

**Comment by clusterfack** [comment]
Being a ghost isn't meant to be a state in which you are rewarded for being in

**Comment by 9600bauds** [comment]
I don't think ghosts will refuse joining the round just because they can read a fucking book in the time while they were dead.
Guess we fucked up when we gave ghosts set view range too, why give spectators any spectating capabilities? Remove toggle darkness when?

**Comment by clusterfack** [comment]
You underestimate the number of people who already just observe 24/7
