### ISSUE TITLE
Can't reply to a centcomm message made by a cyborg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7445]
(WEB REPORT BY: rei1226 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> eefe5147fd2e19ed776d4a7d7a9af32a55fc4a79 
> 
> General description of the issue
> When a cyborg messages centcomm, you are unable to reply back. You just get the error message:

This can only be used on instances of type /mob/living/carbon/human

> What you expected to happen
> Being able to give a snarky reply to a cyborg
> 
> What actually happened
> Can only reply to humans
> 
> Steps to reproduce if possible
> Have a cyborg message Centcomm
> Try to respond to them

**Comment by kilkun** [comment]
Probably because silicons aren't supposed to be able to use the comms console for obvious reasons.
