### ISSUE TITLE
Metaclub has no Vox Station

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#7446]
Played Vox Raiders on Metaclub. We tried to go to the Vox trading station or whatever. It was just empty space.

Possibly extends to Deff and Taxi?

**Comment by mrpain666** [comment]
wew lad

**Comment by Exxion** [comment]
Taxi does have a vox station, but it is impressively bad
Deff does not

**Comment by Duny-** [comment]
You won't have this problem on Deff since I'm pretty sure Vox Raiders can't happen (https://github.com/d3athrow/vgstation13/issues/5434). Guess I know what I'm doing next time I have a good chunk of free time ahead of me. That and making centcomm less shit.
