### ISSUE TITLE
Make combat log attacks that hit you italicized or otherwise distinct from attacks towards other people

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7450]
It's important info, and if there are more than two people fighting at once you have to try to find your name in the sea of red to get it. This is really bad for people who randomname.

**Comment by ghost** [comment]
It would be quite hard to do properly, since combat messages are already visible_messages cast to the attacker and all surrounding mobs. Otherwise we'd just change the name of your character into "you"

**Comment by ihadtoregisterforthis** [comment]
Animations are out of the question.

**Comment by Exxion** [comment]
@dylanstrategie Now I'm tired and might just be stupid at the moment, but doesn't visible_message() send a different message to the user from everyone else if provided with two args? So wouldn't it just require adding a second message with different style?

**Comment by ghost** [comment]
Yes, but we're talking about sending a different message to the user, the target and all mobs in view, visible_message can't handle that currently

**Comment by 9600bauds** [comment]
It seems that this is LITERALLY A THING THAT ALREADY IS CODED IN, BUT FOR WHATEVER REASON THERE'S NO USERDANGER SPAN
