### ISSUE TITLE
Died but also not dead as mommi

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7451]
![strange ass bug](https://cloud.githubusercontent.com/assets/3959840/12070446/c3a3001e-b029-11e5-8ca2-c76ec0fd7414.png)
As a mommi, got caught in a SME blast after the CE was terrible
regardless of my self sacrifice, I managed to both be dead and not dead
I could ghost, but it would act as if I was still alive
I could open doors and turn different directions, but I could not move
I was still solid, and had my little eye lights, a miner could push me around
I could still talk in chats and could *beep *ping and *buzz
its a mystery

**Comment by ihadtoregisterforthis** [comment]
Does it say -100% integrity or is that the regular format?

**Comment by CptWad** [comment]
it was -100%

**Comment by Zth--** [comment]
Maybe an EMP related bug?

**Comment by CptWad** [comment]
That would do it

**Comment by CptWad** [comment]
#7468 has better idea. links for refrence if needed. Uncluttering the issues today!
