### ISSUE TITLE
Unable to smell(elelelele) what Dwayne Johnson is preparing

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7453]
Now that map voting is gone, we cannot longer SMELLLLELELELELE
Please add it back as a normal shuttle docking/round end sound

**Comment by ghost** [comment]
Map voting's back

**Comment by 9600bauds** [comment]
For whatever god-forsaken reason the sound hiccups and doesn't play until over 10 seconds after roundend, though I think that has it's own separate issue

**Comment by 9600bauds** [comment]
Closing this in favor of #6949
