### ISSUE TITLE
Portals aren't logged

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7455]
I got on today to see that somebody had left the crew a dozen portal guns, as well as about 50 ahelps that are basically "So and so spaced me with a portal gun, I didn't get his name".

So, this is why we can't have nice things.

While it may bloat mob attack logs, it would be nice to have something akin to the thrown attack log but for portals, something like 

> [player 1] entered a portal made by [player 2] at [entering portal co-ordinates], exiting at [exit portal co-ordinates]

Just something so we can know which dipshit with a portal gun/hand teleporter is sending people into space during extended

**Comment by ghost** [comment]
Easy fix, but dead for 2 months

**Comment by clusterfack** [comment]
Anyone COULD do it, which is why nobody WILL do it

**Comment by ghost** [comment]
Thanks @JustSumBody , now we can give out the portal gun more often
