### ISSUE TITLE
Module switching as borg leaves old hud on top of new hud

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7458]
(WEB REPORT BY: apelsinsaft REMOTE: 158.69.55.2:7777)

> Revision
>  d1c6f45702c0a3b6984466fdce3b5aa0d8f5bea9
> 
> General description of the issue
> Was switched from janiborg to engiborg while the janiborg module menu was open, got stuck with the janiborg hud element on top of the engiborg hud with no way of removing it.
> 
> What you expected to happen
> no janiborg hud, yes engiborg hud
> 
> What actually happened
> got both
> 
> Steps to reproduce if possible
> be janiborg(not sure if this applies to other classes), have module hud open, get switched to engiborg(again not sure if this applies), hud now contains janiborg module select on top of engiborg hud

**Comment by jknpj** [comment]
Unable to reproduce, i think i fixed it at some point.
