### ISSUE TITLE
Medical belts

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7459]
Besides the ones at roundstart, there is no other way to get them I don't think, and there's been a few complaints about this during higher pop rounds when people want said belts and they're all being used or otherwise unavailable.

Current ideas on how to get more are:

Add them to the medical crate

Add them to the biogenerator in botany along with other things that could do with being in the biogenerator

Or change cows in some way, make them skinnable for leather that can then be shaped with something sharp into something else, like the mentioned belts.

**Comment by Kurfursten** [comment]
:+1: for Biogenerator. Biogenerator is for belts.

**Comment by uazuaz** [comment]
there are 3 medical belts inside medbay storage. did you mean those as "the ones at roundstart"?

**Comment by ghost** [comment]
Yup, those are the ones I'm talking about @uazuaz

@Kurfursten I'll get onto it then

**Comment by ghost** [comment]
@PJB3005 This can be closed, it's sorted
