### ISSUE TITLE
3

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7460]
Sometimes while dead or ghosted you will hear "3".
Literally just "3" pops up in your chatbox.
I have no idea what causes it. I have no idea what could it mean. It only happens while ghosted or dead.
Just... "3".

**Comment by unid15** [comment]
sp:ghost:ky

**Comment by PsiOmegaDelta** [comment]
I've heard rumors of this spooky 3 happening on Bay as well. It is most peculiar.

**Comment by clusterfack** [comment]
Sounds like someone left in a debug message

**Comment by 9600bauds** [comment]
Whatever they were debugging, it's ALWAYS 3

**Comment by gbasood** [comment]
Searched through all the code for these RegExp's:
`(src|usr|world) <<`
`to_chat\((src|usr|world),`
Didn't find anything that might output an arbitrary number. Someone else might have better luck find it than me so I thought I'd put those regexps up, hopefully they'll help

That second one in particular has a lot of results, so maybe I just missed something.

**Comment by FudgePucker** [comment]
Maybe there was a gateway to hell coded into the original?

**Comment by CptWad** [comment]
Gateway to hell accessible by singlo generators when

**Comment by 9600bauds** [comment]
The most horrifying thing would be if it suddenly started saying "2" instead.

**Comment by gbasood** [comment]
And then a month later it'll start saying "1"

**Comment by 9600bauds** [comment]
Opportunity for greatest April fools prank right there @d3athrow

**Comment by d3athrow** [comment]
watafak

**Comment by ghost** [comment]
I've had this randomly happen to me when I was alive.

**Comment by 9600bauds** [comment]
Maybe you were dead and just didn't know it yet

**Comment by Kurfursten** [comment]
Half Life 3 confirmed

**Comment by NigglyWiggly** [comment]
3

**Comment by gbasood** [comment]
space station 3 when

**Comment by Zth--** [comment]
this is somehow related to gaster

**Comment by gbasood** [comment]
Apparently bay also has this occur.

**Comment by NigglyWiggly** [comment]
https://www.youtube.com/watch?v=D5p8YhhaVlA

**Comment by gbasood** [comment]
@NigglyWiggly new antag when

**Comment by 9600bauds** [comment]
Regex search to find all to_chat for any user, containing only one bracketed argument: 
`to_chat\(.*, "\[[^\[]*]"\)`

Still couldn't find anything. 3spooky

**Comment by PJB3005** [comment]
@9600bauds you can send numbers directly.

**Comment by 9600bauds** [comment]
Obviously there was no to_chat that sent just 3.

**Comment by PJB3005** [comment]
We can add code to to_chat so it runtimes SPECIFICALLY when it gets passed "3" or 3.

**Comment by 9600bauds** [comment]
But then the magic would be gone

**Comment by Zth--** [comment]
Maybe Gabe is trying to say something. Let's send him an email

**Comment by FudgePucker** [comment]
@Zth-- 
Great idea, alright I will start it

Dear

**Comment by clusterfack** [comment]
@PJB3005 I think we should do your suggestion. Not because finding 3 is particularly critical but it makes me giggle thinking of someone forgetting to remove that code and then in some far flung future a coder looks at it and says 'what the FUCK did they have against the number 3'.

**Comment by unid15** [comment]
![](http://puu.sh/mqPzp/9c1a0747f0.png)

Just got a 2

:sos: **HAPPENING** :sos:

**Comment by Zth--** [comment]
Oh my god, panic. This shit is in the secret repo

**Comment by unid15** [comment]
Requesting [IT'S LOOSE]

**Comment by FudgePucker** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by CptWad** [comment]
Maybe its a countdown for when nex gets back
then he fixes it

**Comment by gbasood** [comment]
Why haven't we done PJB's suggestion yet

**Comment by unid15** [comment]
still getting the twos

whats going on

**Comment by Imagebard** [comment]
>gbasood modified the milestone: Feature Freeze 2016 Best day of my life

You can say goodbye to doing anything *but* fixing the code now because that isn't ever going to happen now.

**Comment by ghost** [comment]
https://en.wikipedia.org/wiki/Cause_and_Effect_(Star_Trek:_The_Next_Generation)

Guys, we're caught in a temporal causality loop and we sent ourselves a message from another loop...  Quick, who was wearing 3 pips but now only wears 2?

**Comment by gbasood** [comment]
> We can add code to to_chat so it runtimes SPECIFICALLY when it gets passed "3" or 3.

why haven't we done this yet holy shit

**Comment by clusterfack** [comment]
Because we already found what causes it people are just leaving it in to be shits

**Comment by gbasood** [comment]
okay but what is it actually, I'll fix it right now

**Comment by clusterfack** [comment]
It's a visible message thing iirc, in medical code. Pretty sure it was supposed to denote the kind of message to send to the players like blind/etc but it ended up being the actual message

**Comment by PJB3005** [comment]
CLUSTERFACK YOU FUCKING RUINED IT.
