### ISSUE TITLE
Newscasters eating photos?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7461]
(WEB REPORT BY: puglife REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d1c6f45702c0a3b6984466fdce3b5aa0d8f5bea9
> 
> General description of the issue
> So I was writing a witty and fulfilling news story to cheer up the station and had just the right photo for it. I attached the photo and submitted the story, but when I looked at the feed no picture was available.
> 
> What you expected to happen
> I expected the picture to be on my fantastic, well thought out news article.
> 
> What actually happened
> My painstakingly put together prose was missing its photo. Also, once "attached" the photo cannot be retrieved.
> 
> Steps to reproduce if possible
> take photo, create a new story, attach photo,submit.

**Comment by clusterfack** [comment]
@unid15 #7385
