### ISSUE TITLE
Light Tiles Don't Give Off Colored Light

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7465]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 1ec784de1ab1d43973efc9d80284c04cf29702ac 
> 
> General description of the issue
> Light tiles give off general light, not colored light.
> 
> What you expected to happen
> Light from the light tile would be colored
> 
> What actually happened
> Light from the light tile was generically white.
> 
> Steps to reproduce if possible
> Make colored light tiles, put on floor, The room isn't the color of the tiles, it's only regular.

Extra note, this probably isn't a bug but it should be, in any case you might need to classify it as feature request.

**Comment by AutismSpider** [comment]
Light tiles never got the upgrade for the new light code and stuff

**Comment by Imagebard** [comment]
Well, they should.

**Comment by Intigracy** [comment]
#7342
