### ISSUE TITLE
There's an extra space between the first and last name in all chatter

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7467]
I told N3X15 to fix this but he's gone

Someone try to figure out what's wrong here

**Comment by Cisrox** [comment]
nexis fix this bull shit instead of removing map vote

**Comment by Exxion** [comment]
#7311

**Comment by Exxion** [comment]
Also there's something really mysterious and esoteric wrong with at least the \icon macro and possibly other ones
I'll report that after I figure out what the fuck is even going on
It may or may not be related to this

**Comment by 9600bauds** [comment]
@Exxion could it be #6966?

**Comment by Exxion** [comment]
The one I'm referring to is that it appears to sometimes delete the character immediately before it and also may possibly somehow fuck up spacing.

**Comment by Intigracy** [comment]
Still an issue?

**Comment by Exxion** [comment]
Yes

**Comment by Intigracy** [comment]
I don't see the doublespaced radio chatter anymore, so what's the issue?

**Comment by Exxion** [comment]
Are you sure it's not still there?
I haven't played in a few days so maybe it is fixed now

**Comment by Intigracy** [comment]
I was playing today and didn't see it once, nor yesterday.

**Comment by ghost** [comment]
It's still here, you can spot it by highlighting the space between first and last name

**Comment by Intigracy** [comment]
#7311
