### ISSUE TITLE
Issues related to explosions

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7468]
- Explosions (excessive or not) reset the AI eye to the core
- Explosions (possibly other things) can nullspace MoMMIs when they get hit and destroyed, might be the MMIs too

**Comment by CptWad** [comment]
>Explosions (possibly other things) can nullspace MoMMIs when they get hit and destroyed, might be the MMIs too

so its #7451
Since you seem to have an idea of whats going on then ill close mine down for a more informed issue

**Comment by gbasood** [comment]
I'm assuming that this is explosions shaking the camera and moving the eye to do it?

**Comment by ghost** [comment]
Most likely

**Comment by clusterfack** [comment]
Funny you should mention that because ironically I was just reading this proc and I was thinking, how bad could it be if AIs eyes got shaken

![](http://puu.sh/mkG1e/5a61c0b170.png)
