### ISSUE TITLE
Meteor gamemode shakes the screen too much

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7469]
OH SHIT AM I HAVING AN SEIZURE?

**Comment by dylanstrategie** [comment]
The problem is that the shaking is too strong compared to the explosive power, and a meteor strikes roughly every half second

The message spam is also pretty bad

@Deity_Link

**Comment by 9600bauds** [comment]
Considering this one fixed given the PR linked, re-open or open a new one if it's still an issue
