### ISSUE TITLE
Remove "Die a glorious death" from the objective pool for Double Agents

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7470]
Come on, it's just dumb. If your target has a die objective, you can get greentext without doing anything at all. If you have a die objective, you can use stupid cheap piss tactics such as the tactic I should really stop using in this situation, parapen and self-explosive implant (or just the implant if you are confident enough in your robustness) to accomplish both your objectives within five seconds. I mean I guess you could do the latter on a normal Traitor round, but the die objective is so rare in Traitor rounds it doesn't matter.

Honestly, Double Agents needs a lot more than just this to be any good, but this is the most glaring issue I have with it.

**Comment by Ephx1** [comment]
Just rename double tater to "Suicide pact"!

**Comment by AutismSpider** [comment]
Double agents more like suicide race

**Comment by 9600bauds** [comment]
:+1:

**Comment by uazuaz** [comment]
or maybe, the "die a glorious death" objective will be accomplished only if you explode yourself inside the escape shuttle during the flight to centcomm (not when it's still docked to the station)

**Comment by 9600bauds** [comment]
That's fairly shit. You're just making sure that no one ever gets creative with their suicide, if they ever were going to.

**Comment by AutismSpider** [comment]
@9600bauds >creative 

same old fucking C-4/implant rarely do they use other stuff to get creative  last time some one did get creative they emag mommi and suicide via super singo when that was a thing years ago

**Comment by clusterfack** [comment]
There's really only 2 ways to try to force people to be creative.

1. Make a list of every possible creative way and try to code detection for it to make them win (basically impossible)
2. Make a list of every possible uncreative way and try to code detection for it to make them fail

Both things are difficult but if someone wants to attempt the second and makes a PR for it I will accept it.

**Comment by PJB3005** [comment]
I'm not sure if I should tag this [Feature Request] because you're asking to remove a feature.

_Although:_ the code for assigning objectives to double agents is _probably_ the same, so in that case you're asking for an exception for Double Agent.

Also :+1: from me.

**Comment by Zth--** [comment]
:+1: for removing it from double agents

**Comment by Imagebard** [comment]
:+1:
Mainly because ritual suicide sucks

But also because lore states that you're wedding out the weaker traitors.

**Comment by AutismSpider** [comment]
job of double agents to kill off the weaker ones not fucking do suicide race

**Comment by Imagebard** [comment]
You already said that twice AutismSpider
