### ISSUE TITLE
Rejoined after death as new character

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7473]
(WEB REPORT BY: realestestate REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> So I was playing the round like normal. got killed and spaced with no hope of being cloned. I respawn as a mouse and soon get killed by a cat. I wait out the 5 minutes before I can respawn, and this time I try respawning as a mommi on the derelicit. I press the button a few times, and up comes the UI for me to choose my spawn location. I pick the only option(derilicit), and press ok. it prompts me the same thing again immediately after. I fill it out again. then it asks for confirmation. I answer yes. asks me again immediately after if I want to confirm, again. yes again. I spawn as a MOMMI, get the MOMMI general info message twice, and immediately I get the message "closed Connection". I right-click client reconnect to the game and it takes me to lobby. I clicked join game and it asks me for proffesion (I had the same character set as default).clicked engineer and bam I respawned. same round that I died. same character.
> 
> What you expected to happen
> I expected to be warped back into the MOMMI body rather than allowing me to rejoin the game as a new character.
> 
> What actually happened
> I joned the game anew after I already played it and died
> 
> Steps to reproduce if possible
> 1.died
> 2.ghosted
> 3.respawned as mouse(?)
> 4.died as mouse(?)
> 5.Tried respawning as MOMMI, but might've clicked it twice or something cuz I was lagging.
> 6.press ok to MOMMI prompt
> 7.should get the same exact prompt a second time
> 8.game closes connection right as you spawn.
> 9.right-click client: reconnect
> 10.late join game

I don't know if becoming a mouse had anything to do with it. it did give me a 5 minute delay before respawning, and I clicked respawn as MOMMI a few times as it was running out

I think the double input on the MOMMI spawn screen caused the hiccup.

**Comment by gbasood** [comment]
Sounds like a runtime

**Comment by gbasood** [comment]
Okay, it definitely is tied to trying to become a MoMMI twice before spawning as one.
