### ISSUE TITLE
working lights stopped emmiting light

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7475]
(WEB REPORT BY: realestestate REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> lights in hall turn off. I check the APC. it seems to be working perfectly.. the output load on lighting is sufficent and everything is on. I use a flashlight on the lights. it has the fuzzy glowing sprite that indicates it is on. I examine them, it says: A lighting fixture. It is turned on.
> they are turned on but not emmitting light. can't remove them without the black gloves. everything is showing that they are indeed turned on, but not emitting light.
> 
> What you expected to happen
> working lights to emit light
> 
> What actually happened
> no light
> 
> Steps to reproduce if possible
> I didn't see what caused it

**Comment by Ephx1** [comment]
Maybe ghost fuckery. They can turn "off" lights like this with light flickering.

**Comment by Exxion** [comment]
I've seen this happen before when the lights were flipped several times very quickly

**Comment by uazuaz** [comment]
this happens everytime you join an already started game on the testing server, there switching lights off then on, or removing them then putting them back, "fixes" it.

**Comment by gbasood** [comment]
The issues reads like it was more than one light in the same location that was 'on' but not emitting light.

Might be that it was failed round setup/pre-round setup thing, like @uazuaz described.
