### ISSUE TITLE
Can't Splash Polyacid on heads to melt them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7479]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 1aab67da680dec4b662faebe5e536a49cc61d022 
> 
> General description of the issue
> i dare you, splash polyacid on a head and see what happens
> 
> What you expected to happen
> the head to melt
> 
> What actually happened
> nothing
> 
> Steps to reproduce if possible
> 1. get a head
> 2. get polyacid
> 3. splash

**Comment by 9600bauds** [comment]
oh yeah, didn't pomf revert dylan's PR?
