### ISSUE TITLE
Slime soup from meat crate invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7487]
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> The slime soup I got in a trophy meats crate is invisible
> 
> What you expected to happen
> To see something that reassembles a slime soup
> 
> What actually happened
> The Item is invisible
> 
> Steps to reproduce if possible
> Order trophy meat crates hope for RNG

**Comment by AutismSpider** [comment]
I think the slime soup missing a icon like ton of other old food stuff

**Comment by Kurfursten** [comment]
What you were actually seeing was mimic meat

**Comment by ghost** [comment]
![Slime soup](http://i.imgur.com/bIaWKLy.png)

Couldn't find any traces of the old icon, so mocked one up. Posting it here so I can get to it later when I'm back home

**Comment by ihadtoregisterforthis** [comment]
Fixed I guess
