### ISSUE TITLE
Improvised Centrifuge - active container bug

### ISSUE THREAD

**Issue by Volk101st** [d3athrow/vgstation13#7488]
When you try to insert an active container into the improvised centrifuge, the game registers the fact that it's inside but it doesn't remove it from your hand which is a minor annoyance and prevents you from using that hand.

![1](https://cloud.githubusercontent.com/assets/16519065/12075710/4964f77c-b181-11e5-8002-6e539a086f76.PNG)
In this screenshot you can see that I tried to insert an active container from my right hand but it still remained in my hand, I also inserted 2 passive containers which worked as intended.

![2](https://cloud.githubusercontent.com/assets/16519065/12075725/9ab8b92e-b181-11e5-8881-aac74dc29c2a.PNG)
In the second screenshot, I flushed the centrifuge, it ejected 3 containers and in theory I now have 4 containers instead of the 3 I had in the beginning. I say "4 in theory" because when I attempted to drop the container in my right hand, it magically vanished.

**Comment by ghost** [comment]
@Kurfurst

**Comment by 9600bauds** [comment]
Whoah, I stumbled into this 30 minutes ago too
Will make a PR about this in a little while
