### ISSUE TITLE
Vamp nerf when

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7493]
(WEB REPORT BY: yred REMOTE: 158.69.55.2:7777)

> Revision 4db65315c85735e08816f0f31ca87424d2b7cdfd 
> Thrall costs no blood and can enslave the entire station if the vamp is so inclined, jaunt costs no blood, they can cheat death infinitely in 30 seconds, they don't ash in space at max power (which they can get in 5 minutes sucking off monkeys)

w h y

**Comment by Imagebard** [comment]
We already have a issue about this
#6993
