### ISSUE TITLE
News Caster eats photos

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7497]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 61e14a93231df6613da3e00051274dd8435111bb 
> 
> General description of the issue
> News Casters don't accept or use photos you insert, they like eat them it's terrible.
> 
> What you expected to happen
> my sick photo to show up on my news story
> 
> What actually happened
> the photo was destroyed I guess and no photo showed up
> 
> Steps to reproduce if possible
> 1. make a news channel
> 2. submit image
> 3. wish it'd come back to you as it is now gone

**Comment by ihadtoregisterforthis** [comment]
Same as #7461
