### ISSUE TITLE
Flamethrower Bug report

### ISSUE THREAD

**Issue by Smisser** [d3athrow/vgstation13#7498]
The Flamethrower makeshift weapon is unable to be lit, making it unusable. You can assemble and attach a plasma tank to it, but when attempting to light it nothing will happen.

**Comment by Kurfursten** [comment]
I saw someone use the flamethrower yesterday, so needs more testing

**Comment by Cisrox** [comment]
This isn't a bug.

To light the flamethrower, put the plasma tank on, now get an igniter. Screwdrive it to make it attachable, click on the flamethrower with it, then screwdrive the flamethrower again. It's now lightable.

Unfortunately this is not made clear so half of the crew is unable to use this.

**Comment by Smisser** [comment]
I know how to make a flamethrower, this one just wouldn't light when you pressed the Unlit text in the menu. Senaat himself spawned himself in and attempted to light it and could not, so he told me to make a bug report here.

**Comment by gbasood** [comment]
Tested. Made a flamethrower from a weldingtool by screwing the tool, adding rods, followed Cisrox's steps. Worked fine. You missed a step or the tool runtime'd somewhere. I checked the logs around when you opened this issue and couldn't find any log entries, so I'm going with the former.
