### ISSUE TITLE
Inaccesible console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7499]
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Cant access HoP console i was using it and got stunned pulled away then after i couldnt use the console i closed the screen
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ghost** [comment]
@gbasood I'm requesting a nano you why tag honestly

**Comment by 9600bauds** [comment]
shitty old nondescript nanoUI issue
