### ISSUE TITLE
Spare Plasmaman/Vox Softsuits

### ISSUE THREAD

**Issue by Cyadox** [d3athrow/vgstation13#7500]
This is more of a feature request and isn't entirely necessary, but what I feel is vital if we are going to continue to let people play other, and more importantly, gimped races.

I propose we make some way for Cargo to order a set of generic suits for either Vox or Plasmamen for a minimal price, since it is very easy for an antag (or shitter) to pull a plasmaman out of the round if they hide the suit. Vox less so, since it's just a specific hardsuit they can wear since normal suits won't fit and isn't vital to their survival, but it should still be available all the same.

Also, I find it's difficult to switch jobs as a Plasmaman since you can't just recolour your softsuit, you're stuck with your roundstart one, unless another plasmaman dies who so happens to be in your role. While people can still see in comms and examination that you are at your job, at a glance it's very confusing (or suspicious) to see an assistant running around with Sec or Engineering gear.

I think we should either add some way to easily switch colours on the suit itself, or someway of ordering more through Cargo or the suit vendor.

**Comment by AutismSpider** [comment]
We have a pda painter why not generic suit painter for plasma men? can make it work for bio suits and other stuff?

**Comment by Cyadox** [comment]
@AutismSpider As much as I don't like snowflake machines, that'd be an easier way to do it. The only problem is you'd have to juggle two suits around while it's being painted. I was thinking maybe something that you could walk into (like a stall of some sort) in front of the HoP's desk that does that.

**Comment by AutismSpider** [comment]
Should be little tube you walk into for vox/plasman suit repaint.

for like 100$ or 50$ form cargo can order some cheap back up suits for them 50 for the plasma man bit more for the vox

**Comment by Cyadox** [comment]
I'm dredging this back up because someone had a good suggestion from the thread about making a Ayylium Vending machine for spare nitrogen and plasma tanks, and figured this might be an easy solution to this problem by selling the suits there too.

**Comment by ihadtoregisterforthis** [comment]
Who would have the vendor?
I would keep unique suits out of this machine, such as departament heads, clown, mime, and maybe chaplain.

**Comment by Cyadox** [comment]
@ihadtoregisterforthis 

> I would keep unique suits out of this machine, such as departament heads, clown, mime, and maybe chaplain.

That's the idea, actually. It should only hold generic or assistant suits, and spare tanks with 300kpa like your roundstart one.

**Comment by ihadtoregisterforthis** [comment]
Also, to-be-coded premium extinguisher refills for plasmamen suits, either for a vendor or crate from cargo. Accidents happen.

**Comment by Cyadox** [comment]
I also meant to mention that it would be a public vendor like the food/soda machines. Extinguisher refills could be another item available too.

**Comment by 9600bauds** [comment]
This got fulfilled
