### ISSUE TITLE
You can access "restricted" channels by any radio or Intercomm

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7503]
This might just seem like a fun little issue but THINK for a minute.

You can know that security is chasing you, *without any special work required other than finding an red toolbox*.
**You can know if the round type is Nuclear Operatives at a few clicks, by setting that same radio to 121.3**
We need a way to protect Security, Command, ERT, Deathsquad, and Syndie channels.
Maybe a ban will suffice for people that check for Syndicate Operative channels, but the rest can't be fucking banned. What is the plan?

**Comment by gbasood** [comment]
Radio encryption keys.

**Comment by PJB3005** [comment]
I'm 99.9% sure that radios aren't supposed to be able to reach the lower frequencies.

**Comment by Imagebard** [comment]
Can't close an issue on 99%, PJB3005.
Even if radios can't, intercomms can. I could go down to 121.3 as an AI, by the way.

@gbasood 
They don't actually encrypt shit

**Comment by gbasood** [comment]
@Imagebard but they could, if it were implemented.

**Comment by PJB3005** [comment]
@Imagebard I never closed the issue, did I?

**Comment by Kurfursten** [comment]
I would say definitely fix it for secure channels like deafsquid or new cops, but I don't see any problem with leaving department radios open to eavesdropping. They've been that way for as long as I've been here, AI radios and the librarian's backroom even count on it. Eavesdropping on security is a neat gameplay dynamic and encourages whispering, PDA messages, etc.

**Comment by TermedClepe** [comment]
Radios being able to listen in on encrypted frequencies like security is a bug. They are called encryption keys in headsets for a reason.

**Comment by uazuaz** [comment]
i think that syndicate channel is unaccessible from normal devices anyway.
if you set any headset, intercomm or bounced radio to the right frequency you can _**talk**_ on any channel, but if you set them on 121.3 you can't talk on the syndicate channel, so i can assume that it doesn't work from normal devices.
of course, the fact that an assistant can hear the private AI channel, command, security, deathsquad, ERT channels just setting the right frequency on a basic headset is weird.

**Comment by Kurfursten** [comment]
They're not actually encrypted though. If your issue is purely semantic, they can always be renamed to 'radio expansion card'. Call it a bug or a feature - it has been around a long time and I think it adds a good dynamic to play. They keys are still useful because they let you dial in a headset to an extra channel and talk without fumbling to turn the microphone on and off. Plus a normal headset with alternate keys loaded is way less conspicuous than a radio on search. Obviously the truly secure channels like syndicate need to be inaccessible, but I don't see the harm in the rest.

Since it's purely down to difference of opinion [for department radio] at this point, I suppose a server vote is in order, though. If most people want to kill radio tuning, then I won't object.

**Comment by PJB3005** [comment]
@TermedClepe, as @Kurfursten said: they don't actually encrypt.

Although, I know Bay fixed this (or one of their contributors said they wanted to, at the very least).

**Comment by gbasood** [comment]
I don't think we need to kill tuning.

I think certain channels (syndicate) should be out of all on-station device's listening range, which is apparently how it should be but it's bugged for intercoms or something.

Encrypting syndicate radios just prevents people from hearing what they're saying. They can still meta the shit out of it at the round start and tune to their channel to see if they're using it and predict the gamemode.

**Comment by 9600bauds** [comment]
I absolutely agree with department channels being left open to eavesdropping and talking. Syndicate channel, obviously not, but department channels, please do leave in.

**Comment by AutismSpider** [comment]
ebin that fucking ops round was awful

>Journalist fag listened in on syndie comms, and caused shit storm the ai was no better 

just make it so radios and intercoms dont pick up syndicate ert and deathsquad

**Comment by ihadtoregisterforthis** [comment]
Couldn't it work like the binary encryption key? There should be no way to talk through these channels unless you have the specific headset.
On-station channels would stay open for those willing to spam the minus and plus buttons.

**Comment by uazuaz** [comment]
@AutismSpider 
>Journalist fag listened in on syndie comms

are you sure? i done some test on the testing server, you can set the intercomms at the 121.3 frequency but the syndicate channel seems unaccessible from any intercomm anyway, even the ones inside the library private study. as far as i know, the only way to access the syndie channel is to use a syndicate headset (specifically, inside the headset there is a special encryption key that gives you access to the channel).

**Comment by Imagebard** [comment]
>added to feature freeze
not fixed

Wake me up insiiiiideeeeeeee

Also I'm getting reports you can't slip into syndie comms so bye
