### ISSUE TITLE
Beepsky considers non-sentient monkeys as criminals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7505]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

61e14a93231df6613da3e00051274dd8435111bb

> General description of the issue

Beepsky will consider monkeys in view to be criminals and chase them. Even if they aren't sentient.

In this case Beepsky saw a monkey through the window of Genetics on Meta and got stuck on the windows and walls trying to chase them.

> What you expected to happen

Beepsky would keep walking past genetics window.

> What actually happened

Beepsky got stuck on the window, pointing and screaming at a monkey.

> Steps to reproduce if possible

Play on Meta, wait for Beepsky to pass by genetics or bring him there yourself.

**Comment by Cisrox** [comment]
Beepsky was set to ARREST FOR NO ID, not a bug. The monkeys didn't have an ID

**Comment by Exxion** [comment]
Do monkeys even have ID slots?

**Comment by Cisrox** [comment]
No, which is why he needs to ignore monkeys, but technically it is working as intended.

**Comment by ihadtoregisterforthis** [comment]
It hates nymphs too
