### ISSUE TITLE
Changelings can't changeling speak during regen stasis

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7506]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

61e14a93231df6613da3e00051274dd8435111bb

> General description of the issue

Changelings can't changeling speak during regen stasis. Was a monkey faking death and couldn't use :g

> What you expected to happen

Able to speak through changeling speak

> What actually happened

"Talking right now would give us away!"

> Steps to reproduce if possible

Regen stasis as changeling, try using :g

**Comment by TermedClepe** [comment]
Related https://github.com/d3athrow/vgstation13/issues/6920
