### ISSUE TITLE
Changelings can lose some of their abilities

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7507]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

Changelings can lose some of their abilities. Unsure of cause, either by a failed regen stasis or a buggy transform

> What you expected to happen

Not losing shit on transform/regen

> What actually happened

Lost my previous human form and lesser form

> Steps to reproduce if possible

Be a changeling, get paralysis sting and lesser form
Absorb someone
Regen stasis as monkey
Transform into other person while in regen state
Possibly have your foot wounded? (this happened to me too)
You will be missing your previous form as well as your paralysis sting.

**Comment by ghost** [comment]
Related https://github.com/d3athrow/vgstation13/issues/6920
