### ISSUE TITLE
Lower horrorform gene cost

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7510]
Current cost is 30 genes I believe, being generous and assuming it takes 2 minutes to get one gene, that's still 50 minutes at minimum required for a stronger version of hulk. Not to mention the cost completely defeats the point of becoming a horror form since assuming genes were from players, everyone is already dead.

Horrorform may seem strong, but it's really not in practice. The only times it's seen currently is when a ling farms genes for nearly entire round on monkey people, then he makes an entry and dies in 5 minutes to a floortile, chloral or pretty much anything with 2 functioning legs and 1 arm. Personally I have never seen a successful horror form.

This way we'll hopefully see something other than extended until sneak lings screw up or monkey farmer ling ends his harvest.

**Comment by Exxion** [comment]
The cost is 30 evolution points, but (according to the Wiki, at least) you get two per absorption
So a minimum of 26 minutes spent absorbing

Also, I rarely see _unsuccessful_ horror forms. Well, I rarely see horror forms at all, but the few I have seen were almost all successful.

**Comment by TermedClepe** [comment]
The wiki is wrong.

**Comment by ghost** [comment]
You're right, it's 2 points per absorb. In that case 20 evo points cost sounds more reasonable.
