### ISSUE TITLE
Botany3: Nettles, deathnettles, novaflowers can't be grinded

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7511]
Putting them into grinder and grinding them results in 0 chems.
Novaflowers have to be put in using a plantbag.

**Comment by 9600bauds** [comment]
That's weird, I specifically didn't touch those. I'll look into it

**Comment by Kurfursten** [comment]
@deitylink

**Comment by DeityLink** [comment]
Eh, I didn't touch nettles nor deathnettles. It COULD be because those three are inedible grown, and as such not part of an allowed type path.

**Comment by 9600bauds** [comment]
Cannot reproduce nettle or deathnettle issue
![space_station_13_2016-01-09_22-13-11](https://cloud.githubusercontent.com/assets/6526157/12219339/3d7b5760-b71e-11e5-867b-836b8b3b7dff.png)

**Comment by 9600bauds** [comment]
Should be fixed in #7739
