### ISSUE TITLE
Running at hyper speed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7524]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Oh my god how has this not been abused yet. If you hold a pair of white shoes while wearing another pair you run light speed
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
Oh fuck I thought that was badmins last night

**Comment by Exxion** [comment]
It actually appears to be _all shoes_. How long has this been broken?

**Comment by Exxion** [comment]
SHOES FUCKING SPEED YOU UP EQUALLY REGARDLESS OF WHETHER YOU ARE HOLDING OR WEARING THEM AND IT STACKS
JESUS FUCKING CHRIST

**Comment by 9600bauds** [comment]
This is magical

**Comment by ghost** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Arthurdentist** [comment]
Shoe Snatch confirmed for new wizard meta

**Comment by Imagebard** [comment]
[Honk]

**Comment by Exxion** [comment]
It's very unfortunate the [IT'S A FEATUREEEEEEE] tag was removed

**Comment by Exxion** [comment]
Works with anything that has slowdown.
I guess items with slowdown should be given flags for the slots they can slow from
Because we might want heavy items that can slow just when held, but holding shoes shouldn't magically speed you up.

I want to know how nobody noticed this before

**Comment by ghost** [comment]
How the fuck did this go unnoticed for so long

Jesus fucking christ

**Comment by clusterfack** [comment]
It hasn't gone unnoticed

**Comment by PJB3005** [comment]
Guys @N3X15 left again so we can bring [IT'S A FEATUREEEEEEE] back!

**Comment by 9600bauds** [comment]
> clusterfack removed the Usain Bolt label an hour ago

**Comment by clusterfack** [comment]
Memes

**Comment by d3athrow** [comment]
literally no fun allowed
