### ISSUE TITLE
Mini Hoes have blood on them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7533]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9538cbeb835b35f6b1989a910ccaf86317909205 
> 
> General description of the issue
> The sprite for mini hoes have blood on them.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
![how](https://cloud.githubusercontent.com/assets/8107459/12092207/e82c1540-b2fb-11e5-8d25-567cf32efdef.png)

Nothing wrong here.

**Comment by clusterfack** [comment]
For shame

**Comment by 9600bauds** [comment]
Apparently he later said in the general that hoes become bloody when a MoMMI picks them up

**Comment by clusterfack** [comment]
Or the hoe was just always bloody
