### ISSUE TITLE
[Deff] No Autolathe in Research & Development

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7535]
(WEB REPORT BY: myroc REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f0d192e03f12243b1d70fcdbb102bbc87567a19d 
> 
> General description of the issue
> Deff RnD does not have an autolathe.
> 
> What you expected to happen
> An autolathe in RnD.
> 
> What actually happened
> There was no autolathe in RnD.
> 
> Steps to reproduce if possible
> Wait 50 rounds for deff to win the vote. Enter RnD.

**Comment by Duny-** [comment]
![ss 2016-01-04 at 08 29 01](https://cloud.githubusercontent.com/assets/5224390/12098325/e6058866-b321-11e5-97e7-862b225a64a7.png)

**Comment by PJB3005** [comment]
>Effort

**Comment by Duny-** [comment]
FUCKING NORMIES AND THEIR CASUAL GAMES DID THIS REEEEEEEEEEEEEEEEEEEEEE

**Comment by ghost** [comment]
But duny, there's an autolathe in all the other research departments on the other maps

**Comment by CptWad** [comment]
not taxi

**Comment by Kurfursten** [comment]
Taxi has a circuit board which is not very different than deff. It just saves you the sulphuric acid.

**Comment by Duny-** [comment]
@Skullyton NORMIE GET OUT OF MY FACE

**Comment by Zth--** [comment]
I only ask to add console screens to mechanics and engineering
