### ISSUE TITLE
Most coin machines don't have any special interactions for strings

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7536]
Any machine that uses coins but isn't an Vending Machine(EX: HatLord 9000 or PietyVends) just ignores the presence of a string instead of giving the 1/3 chance of returning the coin.

Examples:
Sweet Machines(close to Boxstation's Kitchen)
Gashapon Machines(Taxistation cargo)

**Comment by Cisrox** [comment]
Maybe you're unlucky? Also this is not a feature request, its a bug PJB. He means that in some dispensers, having the string on your coin doesn't actually give you the chance of getting it back.

**Comment by Kurfursten** [comment]
The terms you're searching for are "vending machines", "sweet machines", and "gashapon machines".

@Cisrox Sweet machines and gashapon machines aren't a type of vending machine at all. It's an oversight if anything.

**Comment by PJB3005** [comment]
@Cisrox it is, they have no code to make the strings work, you're asking for them to get codefor it.
