### ISSUE TITLE
New ghost "haunting"

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#7540]
1. Double clicking to teleport away from the hauntee doesn't unlink the ghost from the victim, making you jump inmediately when said mob moves.
2. The ghost adquires the direction of the mob it's haunting, bit of a bother.
3. The "you are no longer haunting" message is not really needed, along with the purple sinister warning.

Other than that it is more responsive than before

**Comment by ghost** [comment]
Noted, I'll fix the first. The rest feels fine to me

**Comment by unid15** [comment]
Also when your victim swaps places with another mob, you aren't moved together with the victim
