### ISSUE TITLE
Vermin infestation Borer event

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#7541]
Spawns in Ckey less borers fix it or take it out of the spawn event

**Comment by TermedClepe** [comment]
Borers need a cute smiley on their sprite so people don't valid them.

**Comment by Ephx1** [comment]
Rename them to sillybugs too

**Comment by Killette2** [comment]
Make borers sqeeee a really cute noise like when you walk over mice, but cuter while we're at it.

**Comment by Ephx1** [comment]
I think we're getting ahead of ourselves here.
@PJB3005 this is a legitimate bug, AutismSpider's report is factual.

**Comment by ihadtoregisterforthis** [comment]
I vote to get them removed from infestation. Makes them sound like a threat and incites valids, confusion and "didn't know they weren't antags".

**Comment by gbasood** [comment]
Well, a separate issue can be opened for that if need be.
