### ISSUE TITLE
Near Permanent Cable Cuff Display

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7546]
(WEB REPORT BY: chucklemonger REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 41e991eaa0e56634735e5e42558bcb6947fde812 
> 
> General description of the issue
> After escaping from cable cuffs using Resist, the icon would stay there for a very long time. The hand would still be usable, however. For the purposes of reproduction, there had already been two failed Resist attempts.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by robintime** [comment]
tested locally and could not reproduce, even with the provided steps. none of the avid cable cuff enjoyers i asked about this issue had ever encountered it before, so i think it's safe to say it no longer occurs.
