### ISSUE TITLE
Universal translator bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7547]
(WEB REPORT BY: icefistthunderdick REMOTE: 158.69.55.2:7777)

> Bug with universal translator
> 
> General description of the issue
> When I installed the universal translator on my pAI, it crashed my client
> 
> What you expected to happen
> I expected it to do whatever the universal translator does
> 
> What actually happened
> Crashes my game, giving me an Invalid Arguement error.
> 
> Steps to reproduce if possible
> Honestly I think the only difference I might have is having Jap locale installed

**Comment by Ephx1** [comment]
What kind of scrub doesn't use AppLocale?

**Comment by PJB3005** [comment]
@Ephx1 AppLocale doesn't work anymore on Windows 10, which might be the reason.

We can't really do anything about crashes like these, you're best of going to the BYOND forums.

**Comment by Killette2** [comment]
> windows 10

**Comment by Intigracy** [comment]
There's an applocale copycat that works for Windows10, I forgot what it's called but I've got it installed for all them totally appropriate vidya playing.
