### ISSUE TITLE
Mint bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7550]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
While operating the Mint in mining, you are unable to close the panel even when you move away. The page refreshes everytime it makes a coin, which also brings the menu back up if you close it.

**Comment by Imagebard** [comment]
You need to click the "close" button so it stops updating. Someone should update the menu to include that.

**Comment by PJB3005** [comment]
Fixing this is incredibly easy to fix too:

Needs an `onclose()` after the `browse()`.
