### ISSUE TITLE
You can put lit Premium Havanian Cigars in wallets.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7551]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 41e991eaa0e56634735e5e42558bcb6947fde812
> 
> General description of the issue
> I don't think that you can put lit cigars in wallets.
> 
> What you expected to happen
> An error message.
> 
> What actually happened
> A lit cigar in my wallet.
> 
> Steps to reproduce if possible
> Obtain a wallet and a lit Havanian Cigar, and put it in the wallet.

**Comment by Imagebard** [comment]
[Oh god who cares]
[Not a bug]
[Honk]

**Comment by Killette2** [comment]
You don't put lit cigars in your wallet when you want to smoke it later?

**Comment by ghost** [comment]
For that matter, you can put lit items in most storage items

Not really a bug. If it really triggers you, you can make it so you risk catching on fire doing so

**Comment by 9600bauds** [comment]
Won't fix
