### ISSUE TITLE
Strike-anywhere matchbox contains seven more matches than it can take.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7552]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 41e991eaa0e56634735e5e42558bcb6947fde812
> 
> General description of the issue
> Whenever you purchase a strike-anywhere matchbox and empty it, and then fill it again, it is full but there are seven matches on the ground as it can not put it in the matchbox.
> 
> What you expected to happen
> All matches in the matchbox.
> 
> What actually happened
> Seven matches on the ground.
> 
> Steps to reproduce if possible
> Purchase a strike-anywhere matchbox and empty it, then try to fill it again (protip: You can't).

**Comment by ghost** [comment]
Only thing I can think of is container size being hardcoded to 14 maximum ?
