### ISSUE TITLE
Kitchien broken on crew monitoring screen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7554]
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> When using the crwe monitoring computer the kitchien looks like a massive breach
> 
> What you expected to happen
> I want to see the actual kitchien
> 
> What actually happened
> I see a hole
> 
> Steps to reproduce if possible
> -Use the crew monitoring computer
> -look for the kitchien

**Comment by ShiftyRail** [comment]
New CMC fixed this most likely
