### ISSUE TITLE
Unable to move as borg

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7555]
(WEB REPORT BY: chucklemonger REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 41e991eaa0e56634735e5e42558bcb6947fde812 
> 
> General description of the issue
> Got tazed and forcibly converted to borg. Could not move at all, even when teleported by admin, and could not equip Modules without using the panel.
> 
> What you expected to happen
> To be able to continue to play normally
> 
> What actually happened
> Become locked in place immediately after selecting model. Able to rotate, but only by using right click to examine an object in that direction.
> 
> Steps to reproduce if possible
> Select security and red knight after being borged

**Comment by PJB3005** [comment]
Almost certainly caused by #7001
