### ISSUE TITLE
No Module out of borgifyer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7556]
(WEB REPORT BY: ysn013 REMOTE: 158.69.55.2:7777)

> Revision 41e991eaa0e56634735e5e42558bcb6947fde812 
> 
> General description of the issue

I came out the borgifyer without being able to choose a module, and couldn't choose a module afterwards either.

> What you expected to happen
> 
> What actually happened

It didn't give me a chance to choose a module and just made me a standard borg without anything to do

> Steps to reproduce if possible

No idea

**Comment by clusterfack** [comment]
Don't think this is a bug, the borgs can set what module comes out of the autoborger
