### ISSUE TITLE
Newscaster photos vanish

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7558]
(WEB REPORT BY: apelsinsaft REMOTE: 158.69.55.2:7777)

> Revision 

23352aecb17b236e7d70090c6a9617e1519175d3 

> General description of the issue

Newscaster eats photos when "Attach Photo" is used, but the photo vanishes and is not used.

> What you expected to happen

Newscaster takes photo, "Remove photo" appears, when post is made the photo appears in feed

> What actually happened

Newscaster takes photo, "Attach Photo" still in the UI, when post is made the photo is not included in feed. Photo vanishes.

> Steps to reproduce if possible

I did this on the newscaster at the librarian desk on boxstation. I made a channel, switched ID title, made a new channel, and tried to make a post on the new channel with a photo attached.

**Comment by ihadtoregisterforthis** [comment]
Duplicate and fixed by minutes

**Comment by clusterfack** [comment]
There's been an issue about it for days, I pinged unid about it
