### ISSUE TITLE
NanoUI: the fancification.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#7559]
So TG got a NanoUI update, made by @neersighted:

![](https://cloud.githubusercontent.com/assets/1049222/12069188/ab1a07f4-afe8-11e5-8971-faa53ca052a9.gif)

But there's a reason it is shit:
- It's made entirely in Stylus and Coffeescript, both are web 2.0 <sup><sup><sup>wait aren't we on web 4.0 yet?</sup></sup></sup> preprocessors for CSS and Javascript respectively and Jesus Christ is Coffeescript so fucking ugly of a syntax, I don't know why people think it's better than Javascript.

So for one thing we're **not** porting it, but I do want something like this (I've hit a dead end on how to make a decent UI framework).

Now it uses [Ractive.js](http://www.ractivejs.org/), which people may very much disagree with, but we **need** a better UI framework and I can't think of anything other than this for it.

So yay / nay?

**Comment by clusterfack** [comment]
Sure

**Comment by Zth--** [comment]
Yes. We need it

**Comment by 9600bauds** [comment]
Why is there a cell charger in the middle of Cryo

**Comment by ihadtoregisterforthis** [comment]
Yes as long as we don't end up yelling **NANOUI** more than we do now.

**Comment by neersighted** [comment]
tgstation/-tg-station#14528

**Comment by neersighted** [comment]
Also stylus can be easily swapped for LESS or SASS if you don't like it. Hell, you could swap in CSS4 if you want.

**Comment by Probe1** [comment]
🔫

**Comment by PJB3005** [comment]
Good riddance.
