### ISSUE TITLE
Shuttle's lights won't turn on again after a ghost flicks them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7560]
(WEB REPORT BY: cumoverme REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f19f14c977e6b65a48e0562769e0b8d21a4b423e
> 
> Steps to reproduce if possible
> Be a ghost, click on a shuttle's light.

**Comment by Exxion** [comment]
It's weird. Sometimes they work perfectly, sometimes they flicker once then never again respond to clicks, and I guess sometimes this, though I've never seen it

**Comment by clusterfack** [comment]
That's because mappers have manually set the lights to on, but left the area's power_light = 0. Power light is determines whether light is on in an area and thus lights reset to them once turned off.

The area needs to be have power_light = 1.

**Comment by gbasood** [comment]
#8209 should fix
