### ISSUE TITLE
Messages form grabbing a item are repeated.

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7570]
>The obsidian rod is teeming with divine power. You feel like you could pulverize a horde of undead with this.
The obsidian rod is teeming with divine power. You feel like you could pulverize a horde of undead with this.
The obsidian rod is teeming with divine power. You feel like you could pulverize a horde of undead with this.

Calm down.
Also seen in the bible and apparently the Cursed Dice

**Comment by Kurfursten** [comment]
Weird. This didn't happen to me previously. Do you happen to be using hotkeys? This would make it cycle through multiple slots - failing until it finds a valid one, thus spamming you.

**Comment by 9600bauds** [comment]
I think I know why this happens, will look into it tomorrow

**Comment by Imagebard** [comment]
@Kurfursten 
Nope, I merely click them while they're on the ground/table and this happens.
