### ISSUE TITLE
I don't think players should be able to construct showers, or at least, not as easily as can be done right now

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7573]
It allows you to completely clean yourself of blood anywhere at any time, provided you brought metal sheets (I personally never am without at least some metal sheets in my backpack)
It also has massive griff potential by letting you construct a shitton of slipathon machines everywhere and generally be A Huge Pain In The Ass
Lastly, it also lets you completely fucking calcinate Diona and Grey alike with jet streams of IMPOSSIBLY HOT AND ORDINARILY SLIPPERY WATER (WHY)

**Comment by ihadtoregisterforthis** [comment]
Make them need to be filled with water to work, pipe waterworks are not very viable.

**Comment by 9600bauds** [comment]
Could work. Have the starting showers replenish water constantly until unwrenched.

**Comment by Exxion** [comment]
> ROUNDSTART OBJECT SNOWFLAKING

:-1:

**Comment by 9600bauds** [comment]
fine u nerd
place "Waterworks Outlet" under the plating of the roundstart showers
the waterworks outlet can't be constructed, can't be interacted with in any way except maybe unwrench it to splash water everywhere, but it replenishes showers in the same tile
The bottom line is that hallway showers need to be not so spammable, and you shouldn't be able to clean yourself from 2 metal sheets anywhere on or off the station

**Comment by Exxion** [comment]
I do agree that something should be done about showers
Maybe make them cargo-ordered only or something
But having objects that cannot be replaced properly in the event of an explosion or something is Bad

**Comment by Imagebard** [comment]
>But having objects that cannot be replaced properly in the event of an explosion or something is Bad
Wall flashers

**Comment by Exxion** [comment]
Did I fucking stutter?

**Comment by Imagebard** [comment]
>Did I fucking stutter

Wall flashers

**Comment by Exxion** [comment]
I was going to complain that that post wasn't very helpful, but mine wasn't either

I didn't say everything _is_ possible to replace, just that it _should_ be
Make it difficult to replace powerful things, sure, but possible

**Comment by ihadtoregisterforthis** [comment]
Radio Beacons
Shutters
Sinks

**Comment by 9600bauds** [comment]
toilets?

**Comment by 9600bauds** [comment]
What if showers need a live cable under them
Just make some shit up about them using the same technology as chemdispensers to synthetize water out of energy

**Comment by Zth--** [comment]
Sinks and toilets are orderable from cargo. Showers should be orderable too.

**Comment by Kurfursten** [comment]
Griff constructing showers used to not be such a big deal until SOMEONE decided to make deconstruction of showers take 2 steps instead of just one, so now it's a pain to take apart.

That being said I don't really care what is done with showers as long as they are obtainable somehow. Cargo sounds like the best answer so far - I really don't like the idea of 'you can only have a shower in mapper-approved areas'.

**Comment by 9600bauds** [comment]
Yeah probably

**Comment by clusterfack** [comment]
Constructible showers was always a pretty sketchy idea to be honest

**Comment by ghost** [comment]
Going the way of chem dispensers would be consistent.

Make showers, sinks and toilets require APC power to function. They slowly replenish their water supply, they only function with enough water and use water to function. Sprites would get some technological doodad slapped onto them. Showers/sinks/toilets now require a circuit board to construct, obtainable from soldering iron/cargo/science.

Basically make them machines.

**Comment by Intigracy** [comment]
I like the cargo idea
