### ISSUE TITLE
Disposal tubing issues

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7574]
- ~~De-constructing a disposals bin will temporarily make it look like a regular disposals tube~~ unable to reprojews
  ![2016-01-05_23-07-48](https://cloud.githubusercontent.com/assets/6526157/12133154/3c1b6b6e-b401-11e5-80e3-218cd5194741.png)
  until it's unwrenched from the floor
  ![2016-01-05_23-08-54](https://cloud.githubusercontent.com/assets/6526157/12133163/54a90af6-b401-11e5-9920-8bdb7c668e03.png)
- Trying to unwrench an unwelded disposals tube section that is on the same tile as floortiled plating (i.e. firstmost picture) will result in this message: "You can only attach the disposal bin if the floor plating is removed."
  Makes little sense since you're trying to unattach the pipe, not attach it, and it should logically let you unwrench the pipe without having to crowbar the floortile loose anyways.
- The following results in you having a wrenched pipe that you can't unwrench until you get rid of the other pipe first (massive annoyance, illogical, can happen accidentally):
  ![2016-01-05_23-13-19](https://cloud.githubusercontent.com/assets/6526157/12133226/fd77cce4-b401-11e5-8a37-33eb3b917f60.png)
  1) Have a bent and straight pipe both wrenched to the underfloor (can happen when trying to replace a straight pipe with a bent pipe, for example)
  2) Weld one of them
  3) Now you can't unwrench the other one, as it tells you "There is already a pipe at that location", even though you're trying to get rid of it, not construct it
  4) To remove the non-welded pipe you have to get rid of the welded one.
- Examining a pipe should tell you if it's wrenched to the underfloor or not.

**Comment by Zth--** [comment]
I can't believe this issue didn't exist before. I mean, this bug has been there for ages

**Comment by 9600bauds** [comment]
I clearly remember deconstructing a disposals bin before without it turning into a tube.

**Comment by 9600bauds** [comment]
To add to this, it seems that welding disposal tubes to slice them doesn't use do_after but some snowflake version of it, thus not displaying a progress bar
