### ISSUE TITLE
throwing people does not work

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7576]
Heres looking at
#7562
wait no it IS all mobs
people included

**Comment by CptWad** [comment]
okay
#7575 @9600bauds
#7563 @unid15
okay one of you could have fixed it, but who?

**Comment by 9600bauds** [comment]
Clusterfack did

**Comment by 9600bauds** [comment]
You sure it's broken and your branch is up to date? I tested this a little while ago and my fix was identical

**Comment by CptWad** [comment]
I tried throwing people the round after the pull
I would just doublecheck it on serverside. If it works than ill close, just the round I was in when I made the issue was not one to work for it

**Comment by clusterfack** [comment]
Definitely works, next time wait a little longer maybe
