### ISSUE TITLE
Feature request: Teeth

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7577]
Putting teeth under a blanket (since we don't have pillows) replaces it with a silver coin.

**Comment by SysadminJeroen** [comment]
I can already see it, people bashing out their teeth to replace it with an Havanian Cigar.

**Comment by 9600bauds** [comment]
This is so dumb, I almost want to do it

**Comment by SysadminJeroen** [comment]
@9600bauds MAKE IT HAPPEN

**Comment by uazuaz** [comment]
pillows and pillow fights when.

**Comment by Killette2** [comment]
Only when we also add spin the bottle

**Comment by Exxion** [comment]
Make it so that you also have to sleep on it

**Comment by ihadtoregisterforthis** [comment]
![img_20160106_142614](https://cloud.githubusercontent.com/assets/13305885/12149267/9c08e620-b481-11e5-8b13-d1881e6b114a.jpg)

**Comment by Kurfursten** [comment]
Seems like it should be a random chance or something, since getting teeth is so easy. Otherwise, clever idea.

**Comment by Exxion** [comment]
Require someone to sleep on it for a minimum of two minutes or something
That way, powergamers have the chance to get both coins on roundstart Box before one tooth can be made into a coin

**Comment by Kurfursten** [comment]
If you're going to make it sleep instead of just rest, make it "sleep at all". Waking up from sleep without someone to shake you or a latte from the bar is painfully long.

**Comment by Exxion** [comment]
Yeah, but two people could do it pretty quickly by having one sleep and the other shake

**Comment by Killette2** [comment]
Let's add toothbrushes while we're at it

**Comment by Killette2** [comment]
I still want this
