### ISSUE TITLE
>Vote result: Metaclub with 2 votes!

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7578]
Hey man, I love playing other maps but what the fuck

**Comment by 9600bauds** [comment]
It's a weighed diceroll depending on how many people vote each map.

If 10% of people want meta, they get 10% of server time.

**Comment by Kurfursten** [comment]
Perhaps a more constructive reply: the voting system could be a little more verbose about how it works for the many players who don't follow github or changelogs or all that jazz

**Comment by CptWad** [comment]
What @Kurfursten said, there was a fucking riot once meta won with 2vote.
Though 10% of players meaning two players is incredible, Lets just hope we dont end up with successful votes at 1 vote because it would be nuts

**Comment by Exxion** [comment]
@CptWad It is basically guaranteed that we eventually will have a vote won with 1 vote. It just won't happen very often.

**Comment by CptWad** [comment]
well rip
lets hope it does not be too common or end up like that weird test server bug

**Comment by CptWad** [comment]
![hello darkness my old friend](https://cloud.githubusercontent.com/assets/3959840/12161500/31c083de-b4ab-11e5-9df9-2d9acf9cb7b2.png)

**Comment by Exxion** [comment]
That will happen
It's just not likely
Such is the nature of weighted random selection
