### ISSUE TITLE
Using a syringe on bread slices the bread

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7579]
(WEB REPORT BY: apelsinsaft REMOTE: 158.69.55.2:7777)

> Revision 33fccc16807af278cd9828b4ce9c072927976397
> 
> General description of the issue

Syringes set to inject don't inject bread, but rather slice it.

> What you expected to happen

I expected to be able to inject shit in the bread

> What actually happened

Bread got sliced

> Steps to reproduce if possible

Inject bread, receive slices

**Comment by Killette2** [comment]
You don't cut your bread with syringes?

**Comment by AutismSpider** [comment]
look at this nerd cant cut his bread with syringes

**Comment by 9600bauds** [comment]
Instructions unclear, hid syringe inside of bread.

**Comment by Kurfursten** [comment]
You inserted the syringe into the syringe bread loaf

**Comment by ghost** [comment]
You can cut down tower caps (trees) with syringes.

**Comment by CptWad** [comment]
shhh termed, xenobotony does not start with hatchets, how else am I supposed to harvest my 100 potency weed

**Comment by ghost** [comment]
@CptWad
Did you try opening the green crate next to trays? There's a shovel and a hatchet in it. (on box)

**Comment by Kurfursten** [comment]
Until someone fixes this, use something not sharp, like a baster.

**Comment by Exxion** [comment]
Why not just
Lower syringe sharpness

**Comment by 9600bauds** [comment]
Because then you couldn't pop a balloon with it, extremely important

**Comment by Kurfursten** [comment]
Or blind someone by stabbing their eyes with the syringe

**Comment by Exxion** [comment]
No, don't get rid of its sharpness, just lower it
If I'm not mistaken, syringes are sharper than fire axes

**Comment by gbasood** [comment]
If you lower the sharpness it still does silly things it shouldn't, I think
