### ISSUE TITLE
possible weighted vote issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7582]
**NOTE: this just happened on the testing server, so i don't know if it affects the regular server too**

i was on the testing server, then i called the shuttle to restart it; when tha map vote popped up i choose boxstation.
i was alone on the server, so this means that 100% of votes gone to box, but it was chosen metaclub instead. additionally, defficiency appeared two times (one with a typo)

![vote](https://cloud.githubusercontent.com/assets/6170726/12143728/54afa730-b483-11e5-9f56-a47a23deeeae.jpg)

**Comment by PJB3005** [comment]
Hrm, that's weird.

The / and typo are probably N3X15' config of the test server though.

**Comment by Killette2** [comment]
That's because this shit's RIGGED. OOC does not lie, box should always be supreme!

**Comment by CptWad** [comment]
That happened to me too, only it picked deff

**Comment by clusterfack** [comment]
```
	for (item in L)
		if (!L[item])
			L[item] = 1
		total += L[item]
```

```
		if (!L[item])
			L[item] = 1
```

**Comment by Exxion** [comment]
> unintentional

I dunno that looks pretty intentional
