### ISSUE TITLE
Power Net Shutdown Event fucks with SMES settings

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7583]
(WEB REPORT BY: myroc REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e2057fdcf88c4e3bf4fdc16ab9e7b32a2b3a95d8
> 
> General description of the issue
> During a powernet shutdown event, the output and stored charge of all SMES cells are set to 0. This is all well and good, except that after power returns, instead of returning to the SMES' original settings, all SMES cells are instead fully charged and have their output turned on and set to 200,000W. Auto-charge also appears to turn off. On box, this means among other things all the solar SMES cells, which in addition to the three main engineering cells means that there's a guaranteed 1.4 megawatts going into the grid after each shutdown.
> 
> What you expected to happen
> SMES cells to return to their original settings and charge after a powernet shutdown.
> 
> What actually happened
> All SMES cells were instead fully charged and had their output maxed and turned on, ignoring whatever settings they had before.
> 
> Steps to reproduce if possible
> Setup your SMES cells of choice. Wait for a powernet shutdown. When power returns, examine your SMES cell's settings.

**Comment by PJB3005** [comment]
Whoever coded power shutdown is a fucking moron.

**Comment by 9600bauds** [comment]
Oh fucking wow

**Comment by 9600bauds** [comment]
[OH GOD IT'S LOOSE]

**Comment by LordMyroc** [comment]
Six months later, this has still not been fixed.

**Comment by clusterfack** [comment]
Fix it then it's not particularly complex
