### ISSUE TITLE
Ctrl-Click things

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7584]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Not sure if it works with everything added in the update but now you can pull bolted down things like hte Centrifuge
> 
> What you expected to happen
>  It not
> 
> What actually happened
> 
> Steps to reproduce if possible
> Ctrl-click a centrifuge and take a walk

**Comment by 9600bauds** [comment]
?????????

**Comment by Ephx1** [comment]
What I can scrape from this is that you can pull bolted down things apparently?

**Comment by 9600bauds** [comment]
Unable to reproduce, centrifuge can't be dragged, centrifuge won't become draggable even after alt-click (which really shouldn't do anything), can't drag anything else that I added alt-click functionality to like washing machines, you can't even unwrench a centrifuge so I'm not sure what happened there

**Comment by ihadtoregisterforthis** [comment]
The toilet however can be unwrenched
