### ISSUE TITLE
workshop's fabricators and blueprints issues

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7585]
~~1- using a device analyzer, you can scan power cells, load their design on the reverse engine and obtain blueprints, but such blueprints can't be used neither on general fabricator nor flatpack fabricator.
i dont know if there are other items with the same behaviour.~~ ---FIXED

~~2- using a device analyzer, you can scan circuit boards and modules and their blueprints are accepted by the general fabricator, but they have sulphuric acid as an ingredient and there is no way to load acid in the general fabricator; by the way, you can print such boards and modules using just all the other ingredients (glass, plastic, gold) ignoring sulphuric acid.~~ ---FIXED

3- wiki says that the difference between regular blueprints and nanoprints is that blueprints have limited uses and nanoprints unlimited uses. actually, you have unlimited uses using either blueprints or nanoprints; the only difference is that if you use a regular blueprint it will be consumed, if you use a nanoprint it will remain in your hand and this is pointless, because you already have unlimited uses in your fabricator, so the spare nanoprint is useless.
nanoprint could give unlimited uses, blueprints just 1 single use, so for example:

-people could need flashlights, you print a nanoprint and load it on the genfab, so anyone can have how many flashlights they need (assuming there is enough material)

-a security officer needs a flash, you give them a blueprint to print just 1 single flash so noone else will get it.

and nanoprints could be consumed upon use, like blueprints.

**Comment by uazuaz** [comment]
updated.

**Comment by 9600bauds** [comment]
1- christ

2- christ, how even, I tested this too and it wasn't happening before

3- Yeah, by "unlimited uses" it means that it can be loaded into unlimited genfabs. I'm not sure how did Comic think this was a good idea.

**Comment by uazuaz** [comment]
@9600bauds 

> it means that it can be loaded into unlimited genfabs

seems pointless to me. how many general fabricator could you have on the station? i think that the actual intention was to give a limit to the number of copies that you can print with 1 single blueprint.

for example:
-people could need flashlights, you print a nanoprint and load it on the genfab, so anyone can have how many flashlights they need (assuming there is enough material)

-a security officer needs a flash, you give them a blueprint to print just 1 single flash so noone else will get it.

**Comment by 9600bauds** [comment]
I know, it's pointless. Even if it limited the designs, you have a nanopaper dispenser right there. Beats me what Comic was thinking of.

**Comment by uazuaz** [comment]
@9600bauds 
updated my previous comment for a better explanation.

**Comment by 9600bauds** [comment]
I think that's how it worked originally, but it was removed because it was pointless. You can purge blueprints from your own genfab.

**Comment by uazuaz** [comment]
not so pointless. the genfab can be operated from outside workshop by anyone, so if you're a mechanic printing 1 copy of the item, they can queue as many copies they want and you can't do anything to stop them.

**Comment by gbasood** [comment]
The difference between nanoprints and blueprints was, once upon a time, that one would give you one fabrication and then be removed from the designs list, and the other would let you make as many fabrications of that device as you wanted.

**Comment by gbasood** [comment]
Point 3 of this issue is still relevant. Should we make a new issue for it or re-open this one?

**Comment by 9600bauds** [comment]
Probably make a new one, since it's (without trying to sound like a dick) kind of a feature request.

**Comment by uazuaz** [comment]
what if you add the "feature request" tag and reopen this? updated the OP.
EDIT: just saw the new thread.

**Comment by PJB3005** [comment]
and I clicked reopen before I saw the edit on @uazuaz' comment
