### ISSUE TITLE
Stormtrooper accuracy

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7586]
![stormtrooper](https://cloud.githubusercontent.com/assets/5169310/12147526/67ddb52a-b467-11e5-884c-6bf7c79157e5.png)

**Comment by CptWad** [comment]
Was lily a clown?
If so that was intended, clowns/clumsy mutation have good chance to dodge projectiles, I have dodged bullets, staff of change bolts and taser shots as a clown.

**Comment by Imagebard** [comment]
Nope, CMO.

**Comment by Exxion** [comment]
I believe it's a joke about Stormtroopers always being awful shots

**Comment by Killette2** [comment]
Yes, it is a joke but how the fuck do you miss a point blank shot?

**Comment by Exxion** [comment]
OK fair point I just woke up and can't read

**Comment by clusterfack** [comment]
>Yes, it is a joke but how the fuck do you miss a point blank shot?


Narrowly

**Comment by AutismSpider** [comment]
NARROWLY M8
