### ISSUE TITLE
Matter Eater power lets you eat people parts, but not borgs

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7588]
Why shouldn't I be able to eat robots if I can eat people?

This is a feature request, to be clear. I can eat people's individual limbs (besides the head) but I can't do anything against borgs with it, since they're not in the allowed mobs list. If it were changed by just adding them to the allowed mobs list, you'd eat borgs whole, which is also bullshit.

Current code prevents eating heads to allow for people to be cloned again. If Matter Eater functionality were added for AIs somehow, it should prevent people from using it on MMIs (and possibly posibrains) and also eject the MMI or posibrain, assuming the ability would destroy the borg.

**Comment by Ephx1** [comment]
Because robots don't have a limb system.

**Comment by gbasood** [comment]
Well it's really more that they aren't in the allowed mobs list for the spell.

I reworded the issue to be a feature request, though.

**Comment by Kurfursten** [comment]
You could maybe eat out parts of the robot, like devouring their radio, actuator, etc. It would be easier than coding eating off a robot arm since robot arms don't actually have any gameplay analogue.

**Comment by Ephx1** [comment]
I wouldn't suggest that in the slightest without the Robot being open first.
Eating one of those instantly makes the entire thing next to useless, especially actuator.

**Comment by Kurfursten** [comment]
Isn't eating out the actuator analogous to eating off someone's legs? Although I suppose bots can't crawl.

**Comment by Ephx1** [comment]
You're a hunk of junk if your actuator goes. At that point you're a wall with some tools attached.

**Comment by Kurfursten** [comment]
Good point then.

**Comment by AutismSpider** [comment]
Actuator = cyborgs movement at 30 damage the cyborg slows down at max damage the borg is more or less a wall with tools.

Matter eatter power is dumb as shit if you eat some one groin they die on the spot.

**Comment by gbasood** [comment]
@AutismSpider The code is supposed to prevent you from eating groins, torsos, and heads, as it is now.

```
if(istype(limb, /datum/organ/external/head))
            //Bullshit, but prevents being unable to clone someone.
            to_chat(user, "<span class='warning'>You try to put [the_item]'s [limb.display_name] in your mouth, but \his ears tickle your throat!</span>")
            return 0
        if(istype(limb, /datum/organ/external/chest))
            //Bullshit, but you cannot break it anyways
            to_chat(user, "<span class='warning'>You try to put [the_item]'s [limb.display_name] in your mouth, but it's too big to fit!</span>")
            return 0
        if(istype(limb, /datum/organ/external/groin))
            //Bullshit, but you cannot break it anyways
            to_chat(user, "<span class='warning'>You try to put [the_item]'s [limb.display_name] in your mouth, but it feels far too inappropriate!</span>")
            return 0
```

**Comment by AutismSpider** [comment]
code must be fucked last time i got matter i ate some monkey humans groins
