### ISSUE TITLE
Whispering while in cloner and under last whisper threshold kills you

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7589]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

e2057fdcf88c4e3bf4fdc16ab9e7b32a2b3a95d8 

> General description of the issue
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

fuck whispers

**Comment by Imagebard** [comment]
Well, what you expected to happen?

**Comment by ghost** [comment]
I find it handy to tell enthusiastic geneticists to stop clone bwoinking me, but I guess one could just ghost at that point to become unclonable.
