### ISSUE TITLE
Make the Nuke-Ops shuttle console require an agent ID to use

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#7591]
Banning people for stealing the shuttle is stupid, but if there's an issue with people being able to steal it, let's make it more of a challenge to do so.
The console could be made DNA-dependent, removing the possibility of a crewmember using it, but that's no fun at all.

**Comment by Kurfursten** [comment]
Wasn't it emagged in that particular situation?

**Comment by NigglyWiggly** [comment]
Was it? I have no idea. If that's the case and it already requires an ID or emag then what's the issue?

I mean you could make it not require an emag, say the Syndicate built their shit to be non emag-able because they make the emag or something, but that's not really necessary either

**Comment by Exxion** [comment]
Yeah the guy in the thread who was complaining about this said he found an emag in the shuttle and used that to steal it

**Comment by ghost** [comment]
It was emagged.

**Comment by Exxion** [comment]
The only problem I saw with that scenario was that he got banned

**Comment by 9600bauds** [comment]
Well it shouldn't be emaggable, then

**Comment by Zth--** [comment]
Why the fuck would you get banned for this. Remove admins

**Comment by ghost** [comment]
I'm of the opinion it shouldn't be emagged either.

**Comment by AutismSpider** [comment]
Emag on the shuttle what he use to move the ship and got ban for it the fact you can emag the bloody shuttle comp is dumb make it work by dna or agent ID or both.

**Comment by 9600bauds** [comment]
Well I mean according to the guy in the thread, he immediately took a lap around the outside of the station searching for the ship as soon as newcops were confirmed, which is kind of iffy. But still, this is something that can definitely be and should be handled in the code rather than after it happens.

**Comment by AutismSpider** [comment]
thing is the shuttle has the same 6 docking spots same with vox rider ship hell its even mark in space with the arrows any one can see the docking ports.

**Comment by ghost** [comment]
I think only ghosts see docking ports.

Nuke ops already see eachother at all times marked with a syndicate icon, make only those with such icon capable of flying the shuttle.

**Comment by vonzippenstein** [comment]
If it's gonna be unable to be emagged/used by non-ops then someone should probably make it unable to be moved or dismantled as well, like the shuttle consoles on Taxi. Not sure if this is already the case.

**Comment by SangriaMonkey** [comment]
Since when is stealing the shuttle bannable?

**Comment by 9600bauds** [comment]
I somewhat agree with it to be honest, you're kind of fucking up the antag's round no matter how well they were doing.

Ideally it wouldn't be bannable so much as it would be simply not possible. This is like leaving a bowl of candy on the floor and shooting any kid that tries to take some.

**Comment by AutismSpider** [comment]
@vonzippenstein you can dismantled it i think.

@SangriaMonkey Funny really we had round were some one found the shuttle space the nuke and bomb it no ban engi tech finds it with emag in it emags the shuttles runs off with it
