### ISSUE TITLE
Suicidals on suicide watch

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#7595]
1. Many suicide sounds are too quiet to be heard most of the time. An example of one that is just fine is the excerpt from Suicidal Thoughts
~~2. The lawgiver doesn't play a sad song. Who knows why would you suicide having that weapon, but it's a silent death~~ 
3. You can't blow your head with the gravity well. The shot leaves you very weak, the gravity field doesn't appear and the only charge is consumed.

**Comment by Exxion** [comment]
Also, suiciding while holding the double barrel just performs one of the default suicide actions
You can't kill yourself with it
At least not if it's loaded with beanbags, but I bet it doesn't actually check for that

**Comment by 9600bauds** [comment]
The lawgiver does the thing that it does because it's an OOP crime.

**Comment by AutismSpider** [comment]
Shotgun suicide needs to be the  Kurt Cobain

**Comment by Killette2** [comment]
Too soon spider, too soon

**Comment by AutismSpider** [comment]
22 years man

**Comment by gbasood** [comment]
literally older than the majority of our playerbase

**Comment by Shadowmech88** [comment]
>suiciding while holding the double barrel just performs one of the default suicide actions

Suiciding while holding *any* gun performs a default suicide action. You have to target your mouth and then click yourself to suicide using a gun. Suiciding with a shotgun both works and is lethal even with beanbag rounds.
Suiciding with the gravity well gun doesn't kill you because the projectile deals no damage, and the code accounts for this. Even if it did kill you, it still wouldn't spawn the gravity well effect.

**Comment by Exxion** [comment]
Well yes, I know that now
Though unless it was changed, I'm pretty sure the projectile dealing no damage isn't sufficient to cause it not to kill you if you gun-suicide with it
Do laser tag guns still kill you?

**Comment by Shadowmech88** [comment]
I looked at the code; guns that fire projectiles that have `nodamage = 1` only apply agony and give you an "Ow..." message.

**Comment by Exxion** [comment]
Ah, but not all projectiles that deal 0 damage have `nodamage`
Or at least they didn't
