### ISSUE TITLE
Can no longer interact with newscasters while ghosting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7597]
(WEB REPORT BY: cyadox REMOTE: 158.69.55.2:7777)

> Revision e2057fdcf88c4e3bf4fdc16ab9e7b32a2b3a95d8
> 
> General description of the issue
> Left-clicking on newscasters while a ghost does nothing. No interface pops up, no verb to open it, nuffin. Was working in prior rounds.
> 
> Steps to reproduce if possible
> Become a ghost mid-round and try to use a newscaster.

**Comment by PJB3005** [comment]
Closing because there's a more descriptive bug report for this.

**Comment by 9600bauds** [comment]
> wasn't closed
