### ISSUE TITLE
Nano paper and blueprints do not function differently

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7598]
> 3- wiki says that the difference between regular blueprints and nanoprints is that blueprints have limited uses and nanoprints unlimited uses. actually, you have unlimited uses using either blueprints or nanoprints; the only difference is that if you use a regular blueprint it will be consumed, if you use a nanoprint it will remain in your hand and this is pointless, because you already have unlimited uses in your fabricator, so the spare nanoprint is useless.

What it used to be:

> The difference between nanoprints and blueprints was, once upon a time, that one would give you one fabrication and then be removed from the designs list, and the other would let you make as many fabrications of that device as you wanted.
#7585 original issue has some more info now.

While it is very rarely useful to allow for one-time design fabrication, it is almost never used, not sure if it's necessary to keep the separate papers.

**Comment by uazuaz** [comment]
at least we can say that is pointless to have both blueprints and nanoprints, if they do the same exact thing. if you're not going to change it you could just remove paper blueprints.

the examples i added on the original issue:

> nanoprint could give unlimited uses, blueprints just 1 single use, so for example:
> 
> -people could need flashlights, you print a nanoprint and load it on the genfab, so anyone can have how many flashlights they need (assuming there is enough material)
> 
> -a security officer needs a flash, you give them a blueprint to print just 1 single flash so noone else will get it.
> 
> and nanoprints could be consumed upon use, like blueprints.
