### ISSUE TITLE
Footstepps still dirty after washing shoes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7599]
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Washed shoes still make dirty footstepps for a while
> 
> What you expected to happen
> clean shoes to not make footstepps
> 
> What actually happened
> shoes still produced footstepps for a while
> 
> Steps to reproduce if possible
> -make shoes dirty
> -take shoes in hand
> -walk to next sink and wash shoes
> -put shoes on and walk
> -watch in awe as freshly washed shoes produce dirty footstepps

**Comment by ghost** [comment]
Probably doesn't reset blood_step or something

**Comment by ghost** [comment]
Okay, the variable is track_blood
