### ISSUE TITLE
Rabid slimes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7605]
(WEB REPORT BY: denkouz REMOTE: 158.69.55.2:7777)

> Revision d2f2bae98f971619a669eabe31c98eab5c834d8e 
> 
> Rabid slimes not taking much cold damage and/or not being killed or calmed when sprayed.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by AutismSpider** [comment]
this will be issue number five about this now.

Temp gun or any type of cold water not calming down rabid slimes so your force to kill this thing that moves fast as lighting and has 125 hp

**Comment by CptWad** [comment]
confirming this is still an issue. I think rabid slimes resist anything from fire extinguishers, because it sure seemed like a whole extinguisher was not enough to kill one measly baby slime that was rabid
