### ISSUE TITLE
Ghost newscaster lost functionality

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7606]
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d2f2bae98f971619a669eabe31c98eab5c834d8e 
> 
> General description of the issue
> Ghosts and immaterial mobs sometimes cannot use newscasters
> 
> What you expected to happen
> Ghosts can open and read newscasts as is normal
> 
> What actually happened
> Both me and the admin ghost were unable to open or read the newscaster. A third admin ghost, however, was.
> 
> Steps to reproduce if possible
> Be a ghost, try to use a newscaster. Apparently 2/3 times, it won't work. I don't actually know how this happens or why, or I'd have a 100% repeatability for you.

It's important to note that those 2/3 attempts that failed were 1 tile from the newscaster, so that workaround isn't working around.

**Comment by Intigracy** [comment]
Ever fixed?
