### ISSUE TITLE
AI camera issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7607]
(WEB REPORT BY: somhuan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d2f2bae98f971619a669eabe31c98eab5c834d8e 
> 
> General description of the issue
> AIs cannot take pictures of people or animals, only objects
> 
> What you expected to happen
> Use active camera on a person, take a picture of that person
> 
> What actually happened
> Active camera refuses to work on any type of human or animal, and only works on objects.
> 
> Steps to reproduce if possible
> Be AI, attempt to make portraits.

The workaround I use for this is taking pictures of objects near people, but ghost chat brought up to me that this might actually be a bug and not a feature, so here you go.

**Comment by 9600bauds** [comment]
What

**Comment by ihadtoregisterforthis** [comment]
Might be that clicking a mob doesn't take the picture. Perhaps related to the way AIs can't interact with mobs.

On cameras, I've noticed that any carbon on a photo always faces south. Is that a bug or a "not gonna code that"?

**Comment by gbasood** [comment]
@ihadtoregisterforthis It's a bug that's documented in other issues already filed, for a long time now.

In fact, the recent updates to BYOND probably made a way to fix that bug easy.
