### ISSUE TITLE
Frostoil makes monkeys chill below absolute zero temperature

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7611]
Feeding monkeys sufficient frost oil can make them reach hundreds of degrees below absolute zero.

Oddly they are perfectly healthy.

**Comment by Exxion** [comment]
Does this only work with monkeys?
If not, frost oil smoke new meta

**Comment by 9600bauds** [comment]
thermodynamics are only a theory anyways

**Comment by ghost** [comment]
Missing sanity obviously, though that sanity should be handled by the respective mob's procs, and the frost oil should call a proc instead of directly altering body temperature

**Comment by ghost** [comment]
Probably should do that in my PR, eh, Dylan?

**Comment by dudemanofdoom** [comment]
Iirc. Both frost oil and showers directly modify your body temperature. However this doesn't work on humans because the ambient temperatures heat them up faster than the frost oil cools you. If this isn't happening to monkeys it might have something to do with ambient temperature code

**Comment by PJB3005** [comment]
@dudemanofdoom monkeys probably don't have ambient temperature code at all.

**Comment by ghost** [comment]
I got this, kinda.

**Comment by dudemanofdoom** [comment]
The frostoil code itself doesn't seem to have any kind of range limits for temperatures. 
M.bodytemperature += 15 \* TEMPERATURE_DAMAGE_COEFFICIENT
Not sure if bodytemperature itself has some kind of sanity checking or not. I'm pretty sure I tested this on myself while wearing a hardsuit and I was unable to drop below absolute zero
