### ISSUE TITLE
Ghetto Surgury Screwdriver

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7612]
(WEB REPORT BY: golfer45 REMOTE: 158.69.55.2:7777)

> Revision d2f2bae98f971619a669eabe31c98eab5c834d8e 
> 
> Attempting to use a screwdriver on a broek skull stabs paitent in eye.
> 
> Screwdriver is smeared on skull
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by PJB3005** [comment]
Poor bug report aside: I just tested it and yes screwdrivers are broken for ghetto surgery.

**Comment by 9600bauds** [comment]
Can you state which surgeries it this broken for? What did you test it with?

**Comment by PJB3005** [comment]
@9600bauds ghetto bone repair surgery on the head. Screwdrivers are the only tools that can replace bone gel, and you stab the person in the eyes instead of using the screwdriver as bone gel.
