### ISSUE TITLE
Lighting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7613]
(WEB REPORT BY: desertstriker REMOTE: 173.35.175.236:9959)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
Literally the worst bug report I have ever seen

**Comment by ihadtoregisterforthis** [comment]
And this concludes the first week of the year.
