### ISSUE TITLE
Mending Broken Bones is fucked again

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#7615]
Twice, once with a skull and once with a hand when I was mending the bones the final step always causes the bone to rebreak. Its  Incision -> lift skin -> gel -> setter ->gel -> cautery but the second gel use will break the bone.

**Comment by ghost** [comment]
How much damage was on the limb? If it's greater than 30 brute it'll rebreak

**Comment by Ephx1** [comment]
Yeah you've gotta patch the limb's brute before treating any bones within.

**Comment by 9600bauds** [comment]
You know, ideally you wouldn't be able to fix the bone if the limb is damaged, because the bone shattering again as soon as the incision is closed is pretty dumb. Either that or clear brute damage when fixing the bone.

**Comment by Dizor** [comment]
Probably excess of damage then. Something I wasnt aware with, though I treat any damage I can before hand, might have had to wait longer for healing to set in before bone repair was possible. I'll close this for now if its just a feature I wasnt aware of.

**Comment by 9600bauds** [comment]
This really sounds like unintended behavior honestly, it makes no sense and could probably use being tweaked (like I said above, repair the limb when fixing the bone or not letting you fix the bone while the limb is damaged).
It's not a bug but it's still a valid issue.
