### ISSUE TITLE
"APC zapped me, but dealt little to no damage as there was no wire leading to it, and no charge in the APC cell"

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7619]
(WEB REPORT BY: dongilardoni REMOTE: 158.69.55.2:7777)
APC's that have no external power (not supplied electricity externally) without any battery inside it shouldn't zap the user no matter what hand protection they wear.

**Comment by 9600bauds** [comment]
Well it kind of sounds like a bug

**Comment by Zth--** [comment]
It sounds like hardcoding
