### ISSUE TITLE
Make boxing gloves give the "low dexterity" debuff

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7622]
As it stands, anyone can get boxing gloves from Dorms. Boxing gloves are literally just gloves with a silly sprite. This causes a few minor problems because:
- It means anyone can hide their fingerprints easily
- It means anyone can get 50% protection from shocks easily
- It looks really really fucking silly.

I am myself guilty of getting them every shift as Assistant or any other role without starting gloves. In fact I paint them with a crayon at the washing machines just so they don't look so silly.
It makes sense that they would not let you use consoles or pull a trigger or do anything complex, since they're, well, boxing gloves. You're not going to need that dexterity for boxing, anyways.

**Comment by CptWad** [comment]
This is an OK nerf.
I would be fine with this
Sometimes, I already assume thats how they work anyways

**Comment by Killette2** [comment]
They should have a buff in exchange with an increased knockout or knockdown chance when punching, but still where any weapon would be more viable for killing.

**Comment by uazuaz** [comment]
i thought about this same thing some day ago. dropping any object that you hold when wearing them would be ok in my opinion, so you can't use them to hack stuff.

**Comment by FudgePucker** [comment]
Dear strong bad,
How do you type with boxing gloves on?

**Comment by ghost** [comment]
> It means anyone can get 50% protection from shocks easily

You could just get latex for 75% protection, all it takes is someone to open medbay doors for a second.

**Comment by Killette2** [comment]
Imo latex gloves should be nerfed since they have biohazard protection, and black gloves should have more protection than them since they are fire resistant.

Fuck they're rubber, it's thin as shit and won't help you that much.

Also buff botany gloves.
