### ISSUE TITLE
Firesuits no longer provide anti-plasma protection

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7623]
(WEB REPORT BY: cptwad REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

91c351200027f8bb0bca28fc5872a115223d88d4 

> General description of the issue
> Fire suits do not protect against plasma (IE in a plasma fire). They were supposed to since before hardsuits, and before atmos hardsuits. They are supposed to be used to protect people from plasma fires.
> 
> What you expected to happen
> To not get my jumpsuit and shoes infested with plasma
> 
> What actually happened
> Firesuit did nothing outside prevent fire damage
> 
> Steps to reproduce if possible
> Wear firesuit
> Release plasma

**Comment by ghost** [comment]
Clothes contamination is a terrible unintuitive mechanic. Your clothes are perfectly safe on the ground or in a backpack, just not on your body. The contamination sprite is badly visible and there's no feedback that it's the clothes causing you damage. Only way to counter it is washing machines.

Plasma even goes through air tight space suits. I know plasma it's some magical pixie dust but it's still silly with how other gases behave.

**Comment by FudgePucker** [comment]
No really, I agree with termed here.
Biosuits that are air tight and designed to prevent contamination gets contaminated.

Plasma is a double fuck you to people not in atmospheric hardsuits, not only are you on fire and dying from high pressure, you also take escalating toxin damage

**Comment by FudgePucker** [comment]
Just make breathing plasma kill off your lungs and all your internal organs, make direct contact more toxic, and remove contamination.
Now plasma is more deadly to be in the same room as, but not an annoyance after you get out.

**Comment by Exxion** [comment]
You know the best part about plasma-space suit interaction? When wearing a suit, plasma can contaminate your clothes, but deals no direct damage. So _any_ space suit is plasma-tight as long as you aren't wearing a jumpsuit or shoes.

**Comment by ghost** [comment]
Sleek coding.

**Comment by 9600bauds** [comment]
This isn't even a coding problem, this is what I like to call a "Please take a shower before designing this, so that you may think about it for at least 10 minutes" problem.

**Comment by FudgePucker** [comment]
Why not make contamination even more deadly then?
If you get contaminated then you have to go take a shower, the entire area exposed to plasma is now toxic and needs people in spaceproof suits or biosuits to come and clean it.

Or just remove contamination because its stupid and dumb.

**Comment by Exxion** [comment]
Remove contamination
It's stupid and, at least in its current implementation, makes no sense for the reason I gave above

**Comment by PJB3005** [comment]
Pretty sure I made an issue about this on GitLab, but anyways.

Contamination is a stupid mechanic, and if it doesn't get removed it needs to get fixed at the very least.

**Comment by FudgePucker** [comment]
Make everything have contamination including objects laying on the floors the walls the floors and everything else in the area, requiring cleaning (Would make the janitor much more useful)

Or just fucking remove it because its stupid.

**Comment by Arthurdentist** [comment]
contamination is stupid but I doubt I could fix it.

I did change the sprite to hopefully be more visible and I could throw up a PR real quick. This would address one issue pretty quickly. 

![new sprite](https://cloud.githubusercontent.com/assets/6353372/12398111/6e5c1242-be09-11e5-9523-1f1d05bad7dc.png)

**Comment by gbasood** [comment]
@Arthurdentist :+1: but honestly, the mechanic as a whole is still incredibly stupid

**Comment by CptWad** [comment]
woah shit I forgot I put this up because this is a serverside issue report

I guess removing plasma contamination is okay. Solves most of its issues.

**Comment by Exxion** [comment]
Someday I'll test if you take damage by walking around in plasma naked except for internals

**Comment by Imagebard** [comment]
@Exxion 
You'll go blind since plasma burns your eyes.

**Comment by ghost** [comment]
This has been fixed by myself.
