### ISSUE TITLE
Minimize casualties objective always is successful. Even if the traitor releases plasma and runs down the hall with the cap laser killing people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7624]
(WEB REPORT BY: cptwad REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 91c351200027f8bb0bca28fc5872a115223d88d4 
> 
> General description of the issue
> I just watched someone plasmaflood and then go about killing what crew was left with the caplaser
> 
> What you expected to happen
> The traitor to fail his minimize casualties
> 
> What actually happened
> Greentexted. Shitposted about how he "Doesnt care" about objectives
> 
> Steps to reproduce if possible

**Comment by Imagebard** [comment]
Needs [How the fuck are we going to fix this] tag.

**Comment by 9600bauds** [comment]
Missing steps to reproduce

**Comment by Imagebard** [comment]
9600bauds is a smart contributor

In a unrelated note
>Get "Minimize Casualties"
>Kill everyone
>Get greentext anyways

**Comment by PJB3005** [comment]
Literally unfixable with how SS13 works.

Could make it so admins can make it fail if they feel the traitor has been a bit loud.

**Comment by CptWad** [comment]
Replace it with the "ensure 80% of the crew escapes on the shuttle" one. 
its one way

**Comment by clusterfack** [comment]
Code a failure if less than 60% of the crew survives?

My problem with this solution has always been that it merely encourages a traitor to force a benign shuttle call just to get his greentext which is boring.

**Comment by ihadtoregisterforthis** [comment]
Also with the surviving crew system other traitors might get an opposite objective, and the stealth operator that went for a no-kill completion can still fail. Or just greytiding, or a ragecage, or engineering hazards, or random events. Doesn't Vox raiders work like that already?

**Comment by ghost** [comment]
Question is, do we want friendly antags that protect the crew because of greentext?

Personally I think minimize casualties is bad objective that promotes passive play, creates needless drama and ooc whining about antag ban requests because people ignore it since nobody wants to be antag with hands tied when they finally get their roll.

It should be removed, even from vox raiders.

**Comment by Kurfursten** [comment]
It IS possible to fail Minimize Casualties - Deadpool failed it mere hours ago. You just have to personally murder six or more people. Indirect stuff like silicon subversion and plasmafloods don't count. I'm guessing bombs or grenades don't either.

**Comment by Exxion** [comment]
Oh, I figured it was a flavor thing where an admin had to manually fail it
Checking for kills from bombs and chemical reactions would be pretty easy, but checking for kills by plasmafloods would be... probably not impossible, but nightmarishly hard. I don't really see why the Syndicate, a terrorist organization, would want to minimize casualties, though. I have no problem with it being removed.
Don't remove it from Raiders, though. Come on. That's the only thing separating it from Nuke Ops: Thievery Edition.

**Comment by ghost** [comment]
We could fix it, but it would need special coding in a ton of things. Register who threw bombs, who's been opening the plasma valve (which would need some pretty serious dynamic coding), who subverted the cyborgs who killed who, who cooked that poisonous shit, who left cyanide pills everywhere, etc. It just seems hard to get it to actually work, and there will always be ways around it
