### ISSUE TITLE
Cyborg Health Status on HUD while human

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#7628]
![north frontier eta 2016-01-09 172424](https://cloud.githubusercontent.com/assets/16625342/12217201/98afec9c-b6f9-11e5-96b4-0f6044731e91.png)
I have no idea how this happened, all I did was do some accidental welding without welder protection. It stayed there for the rest of the round.

**Comment by unid15** [comment]
Happened to me too, during the same round. The icon appeared when I fell unconscious from lack of air

**Comment by Exxion** [comment]
How long had the round been going when this happened?

**Comment by ghost** [comment]
I read people complaining they got vampire hud when they reentered body as normal humans, it was a vamp round.

**Comment by Exxion** [comment]
But how long was the round? In long rounds, BYOND seems to experience some kind of memory error and just switch sprites at random even though the icon_state is correct.

**Comment by unid15** [comment]
1 hour 35 minutes in for me (so 13:40 game time)

**Comment by Exxion** [comment]
I think it typically starts around two hours in, so that might be the culprit
But then again it also might not be
I assume VV can see HUD objects, but I haven't tried it
Next time something like that happens, see if an admin can VV it and see why it's there

**Comment by PJB3005** [comment]
@Exxion HUD issues have been around for a while, it's probaby not BYOND shitting itself.

**Comment by LordMyroc** [comment]
Hey guess what, it happened again.

![bowie village xix 2016-01-11 204333](https://cloud.githubusercontent.com/assets/16625342/12244920/2e2785ca-b8a6-11e5-8099-1fb6008087fb.png)
![bowie village xix 2016-01-11 204354](https://cloud.githubusercontent.com/assets/16625342/12244967/629b3798-b8a6-11e5-8056-9f522757a676.png)

This time it happened shortly after I was knocked down by airflow for a very long time. This one was a bit more serious an issue since I couldn't open my belt with it in the way. Fortunately it disappeared a few minutes later.

**Comment by DamianX** [comment]
Hasn't happened in quite a long time.
