### ISSUE TITLE
Nice job on the Hivebot description

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7630]
![image](https://cloud.githubusercontent.com/assets/9827785/12218162/2561a488-b6e5-11e5-97f0-8a71ff61d98c.png)

**Comment by CptWad** [comment]
Those things are old as fuck
due for a remake
I forget what they were even for

**Comment by Killette2** [comment]
Maybe it's big, but small for a robot? Like saying a small elephant is still big.

**Comment by CptWad** [comment]
Like dwarf fortress descriptions? Yeah that makes sense.
