### ISSUE TITLE
Wording of weighted random map selection causes rampant misunderstandings

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7634]
Rather than saying "Weighted vote result," say something like "Weighted random selection." People in the thread seem to constantly think it means something it doesn't.

**Comment by ghost** [comment]
It should show the % chance each map had.

**Comment by Exxion** [comment]
That would probably help a lot.

**Comment by clusterfack** [comment]
What else could you possibly think a 'weighted vote' is?

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/12219179/b2bb642a-b705-11e5-8355-e841c3554cee.png)

To be honest it's probably how I would interpret the phrase too if I didn't use GitHub

**Comment by clusterfack** [comment]
The solution to it not being clear is for it to be increasingly convoluted?

**Comment by Exxion** [comment]
What I suggested is exactly the same number of words as what we already have

**Comment by clusterfack** [comment]
Fine I'll modify it for the brain damaged among us

**Comment by ihadtoregisterforthis** [comment]
For the misunderstanding, add that it's random **and** weighed.
People seem to be expecting an average of the votes that, as long as maps can't be played fractionally, is not possible.

**Comment by 9600bauds** [comment]
Showing the percentages would clear this up real quick

**Comment by clusterfack** [comment]
That was my plan
