### ISSUE TITLE
Laser Weapon Cauterization

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7638]
I think it would be a neat alternative to powergaming gauze every round if it were made possible to field-dress a bleeding wound by shooting yourself in the affected limb with an energy weapon to cauterize the wound.

In more general terms, make being hit by an energy weapon stop the bleeding from all wounds on the body part that was hit.

**Comment by CptWad** [comment]
>Get delt enough damage to start bleeding
>Decide to laser self to stop bleeding
>Now have 50-80 brute and however much shooting myself with a laser would do
Good idea, but it has some glaring flaws that would have to be addressed.

**Comment by PJB3005** [comment]
@CptWad it'd be nice if you'd state those flaws then.

Personally I like this idea, and I think the idea of a tradeoff of extra burn to slow bleeding is a cool idea.

**Comment by AutismSpider** [comment]
Add it to Esword for Cauterization

**Comment by CptWad** [comment]
Well would it damage the player?
Usually blood loss comes with a lot of brute damage. Though the brute damage may be staved off, dealing burn to yourself might put idiots into crit.

**Comment by Shadowmech88** [comment]
Yes, it would damage the player.
This isn't intended to be an ideal alternative. But if a person doesn't have gauze and the laser shot won't put them into crit, it would at least give them an option to take the damage in exchange for not bleeding to death.

**Comment by AutismSpider** [comment]
Better then bleeding to death in like five secs just form one open wound

**Comment by NigglyWiggly** [comment]
Can't you already use an E-sword to cauterize wounds in surgery?

**Comment by AutismSpider** [comment]
yes in surgery to cut people open and cauterize wounds with the esword

**Comment by Konater** [comment]
Why not welding tools too while we're at it

**Comment by AutismSpider** [comment]
welding tools can be use to cauterize m8 they do it badly though
