### ISSUE TITLE
Golem Issues

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7642]
- Need oxygen (also, can have internals without any mask, presumably due to invisible golem mask)
- Lack pressure protection, so die to a breach
- Lack temperature protection, probably discussion but hey, they're golems. Got slowly roasted from heat while not being able to get out.
- Always have pockets. I don't know.

**Comment by Exxion** [comment]
Some masochist needs to remake them as an actual race rather than just humans with snowflake gear

**Comment by Ephx1** [comment]
I had a pressure issue up, but oh well.
As far as I'm aware they always needed oxygen, but pressure protection was a thing they had via their suits.

**Comment by Imagebard** [comment]
Shhh
Copy of #6998

**Comment by 9600bauds** [comment]
well I mean, there's actual info on what's wrong here

**Comment by Imagebard** [comment]
Right back at you 9600 bauds, your issue has no actual info on how to fix it.

If we just made golems an actual race instead of a human with a special suit, all of the above would be fixed.

**Comment by 9600bauds** [comment]
I mean, pressure protection is not a default var in a race. If you don't know you're fixing, you'd make golems their own race, but they'd still take pressure damage because you didn't know that was broken

 ¯\_(ツ)_/¯
