### ISSUE TITLE
Telecomms servers & disconnecting them.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#7643]
So the wiki and the code both say that servers are optional for a telecomms network.

They are, but there's a slight quirk.

If you disconnect the common server from its bus, the common channel will break.

Why? Because the bus sends the signal to every server connected, if it fails that to every hub, if THAT fails to every broadcaster.

It stills sends the signal to a connected server: the engineering one, which obviously discards it, but the bus still stops giving a shit and never sends to the hub / broadcasters.

**Comment by Cisrox** [comment]
I am telecoms expert will check this out in a round in a while

**Comment by Cisrox** [comment]
Yeah he's right. Disabling both engi and common servers allows the signal to go through.

**Comment by PJB3005** [comment]
I don't think this has ever been fixed?

**Comment by Kurfursten** [comment]
A few years ago I coded a tracert function that lets you see which machine is causing your telecoms server setup to be broken allowing you to pinpoint when this happens, so now it's a feature of subtle ways to sabotage tcomms.
