### ISSUE TITLE
Allow silicons to state fake laws

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#7645]
Currently the only way for a silicone to state their laws is the state-laws verb as manually typing them out will get you lynched. While the verb allows you to omit laws it doesn't allow you to state made-up ones. This means that if you, for example, are an emagged cyborg and a human orders you to state your laws, you are royally fucked.

**Comment by 9600bauds** [comment]
This kind of makes asking for laws worthless except to loosely confirm a benign full lawset change.

Given that you need into the upload to check laws I say ehhh, let's not

**Comment by Shadowmech88** [comment]
Perhaps give emagged borgs verbs that let them state a few of the stock lawsets so they can pretend to not be emagged?

**Comment by BestName** [comment]
@9600bauds How do you justify using meta-knowledge of badly designed game mechanics to call an AI/Cyborg out on lying?

**Comment by 9600bauds** [comment]
I think it's OK that they can't lie, only hide it. Trying to bluff out of it is wonky, but giving them the ability to lie is too much.

**Comment by BestName** [comment]
They can already lie, it's just that people will use their knowledge of the game mechanics to call them out on it and I don't understand how anyone can think that's acceptable.
I mean you're using knowledge of the game mechanics aka metagaming to call someone out on lying and possibly getting some valids. How is that ok?

**Comment by uazuaz** [comment]
in the "state laws" window it could be a "state laws you had before being hacked" option or something.

**Comment by Zth--** [comment]
I say no. Some people are just too paranoid and a lot of rounds will be ruined.

**Comment by ghost** [comment]
I see no issue in allowing them to state fake laws, you can already do it with byond macros and everyone has access to those.

**Comment by Exxion** [comment]
Or at least let them change the numbers on the laws so skipping one doesn't activate Level 83 Validhunting in all station personnel.

**Comment by Imagebard** [comment]
:+1:

**Comment by Apelsinsaft** [comment]
There's a roundabout way to do this already. Using hotkeys, press T to get a Say " window. type ";Current Active Laws:", put that say-window away without pressing OK, open another say window, type ";1. You may never etc etc", repeat for every law. Stack the windows so you can easily click OK from top to bottom. repeat entire procedure for extra law-statings. do this for every lawset if you're hardcore. include a ";4. Captain is the only human." for fun framing.

**Comment by Shadowmech88** [comment]
It's true you can bluff it by manually typing out the laws, but if someone asks you to state your laws and you just stand there for 20 seconds while you're typing out your bluff, they're going to assume you're emagged.

**Comment by ghost** [comment]
:+1:

**Comment by Intigracy** [comment]
I think how it works now is fine, it shouldn't be EASY to lie as an AI.

**Comment by Probe1** [comment]
just copy and paste

**Comment by BestName** [comment]
Alright this was probably a really bad idea.
