### ISSUE TITLE
Let's thank mappers in the credits.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7646]
Because we thank coders, spriters, and sounds. Mappers deserve it too.

**Comment by ghost** [comment]
Thank you Duny.

**Comment by Exxion** [comment]
((Duny's already in the code credits))

**Comment by Cisrox** [comment]
f'k u d'ny

**Comment by Kurfursten** [comment]
The only thing this would change as far as I can tell would be to add Wiggle-Bot to the credits for Taxi

**Comment by 9600bauds** [comment]
Probe1 also did mapping for Box and Meta

**Comment by 9600bauds** [comment]
Dun
