### ISSUE TITLE
suggestion: filter for large menus

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7647]
there are interface menus with a lot of listed elements, for example the protolathe menu;
it would be nice if you add a field where you can type the name of the item you're searching for and the list changes dynamically to show only the items with the partial name you typed; for example, typing "manip" would show all the manipulators only.

this could be applied to all these machines with big menus, like protolathe, circuit imprinter, jukebox, etc.

**Comment by Shadowmech88** [comment]
Menus like the protolathe menu use HTML.
I don't think it'd be easy to make an HTML menu live-update as you typed.

A basic search function might be doable, though.

**Comment by Exxion** [comment]
It _should_ be quite possible to make it update as you type
I say should because I have no idea how archaic the implementation of HTML BYOND uses is or if script tags are blocked, etc.

**Comment by BestName** [comment]
Well in the meantime, use ctrl+f

**Comment by uazuaz** [comment]
@BestName 
thanks for the tip, it helps.
if nothing else can be done, an option inside the menu window to open the ctrl+f window maybe?

**Comment by Shadowmech88** [comment]
> an option inside the menu window to open the ctrl+f window maybe

How would this be more convenient than opening the ctrl+f window by just pressing ctrl+f?

**Comment by uazuaz** [comment]
because there are people that don't know that shortcut. for example, i didn't.

**Comment by Shadowmech88** [comment]
Ctrl+f is a standard keyboard shortcut in any web browser or word processor, has been for years. I don't understand how you could have not known about it.

**Comment by Zth--** [comment]
He has a point. Some people don't know some menus are html. What we need are a list of useful tips every roundstart

**Comment by clusterfack** [comment]
If you saw VV you would know this is 100% possible with javascript, which is what HTML menus use.

**Comment by d3athrow** [comment]
javascript will set you free, also lag your client like hell
