### ISSUE TITLE
The thread is claiming that it is possible somehow to hold the wrenched-down version of pipes which is horrifying because they have force 20 for some unknowable fucking reason

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7648]
I think they may be trying to pull one over on me but **why the fuck do wrenched-down pipes have force 20 anyway?** Outside of this bug that may or may not actually exist, their force should be totally meaningless, right?

Anyway they said it had something to do with how the pipes interact with explosions

**Comment by ghost** [comment]
I did a search in attack logs and found no indication that they were used as a weapon.

**Comment by clusterfack** [comment]
Wrenched pipes aren't an item. They cannot be held down.

**Comment by clusterfack** [comment]
Also *listening to the thread*

**Comment by Exxion** [comment]
OK but why the fuck do they have force 20?

**Comment by clusterfack** [comment]
Why shouldn't they

**Comment by Exxion** [comment]
Does force have some secondary use I'm not aware of?

**Comment by PJB3005** [comment]
Do non `/obj/item` things even have a `force` variable?

**Comment by Exxion** [comment]
It's a variable of /obj for some reason

**Comment by Exxion** [comment]
I'll close this, but I would still like to know who the fuck put force = 20 on a fucking machinery
