### ISSUE TITLE
Mist walk being odd

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7652]
(WEB REPORT BY: carshalash REMOTE: 158.69.55.2:7777)
For some reason mist walk is actually bat form, took me a moment to realize it. Probably should have a name change to be more accurate since bats cant fly through walls

**Comment by Kurfursten** [comment]
Mist also cannot penetrate walls

**Comment by clusterfack** [comment]
>mist walk is actually bat form
>Mist walk being odd


What did he mean by this
