### ISSUE TITLE
R-UST is horribly broken.

### ISSUE THREAD

**Issue by sonime** [d3athrow/vgstation13#7655]
1. It does not produce radiation, even though radiating reactions occur.
2. The EM field does not destabilze, even when subjected to temperatures of almost 1 million degrees.
3. Even if the field were to destabilize, it should blow out and make a permanent radstorm, which cannot be tested as to if it will or not.

Right now, all it does is make gas that's too hot for the TEG.

**Comment by sonime** [comment]
@PJB3005, according to @dylanstrategie, you should be the one hearing about it.

**Comment by AutismSpider** [comment]
Chernobyl in space sounds horribly yet funny and should never happen.

Rust code needs ton of work any way.

**Comment by PJB3005** [comment]
Technically all a feature request because it was never implemented to produce radiation.

It never got finished.

**Comment by sonime** [comment]
Is the meltdown cascade a FR too?

**Comment by PJB3005** [comment]
Yes, I don't know why the hell N3X15 put it on the wiki (the entire wiki page before I added construction was a lie), but it sure as hell is nowhere in the code.

**Comment by sonime** [comment]
Looking at the folder, there's some stuff commented out in core_field.dm that seems like it would work. How do you quote on here?

**Comment by ghost** [comment]
The radiation stuff is commented out. You can figure out why it was or read over its files and make a clunky one cribbing the sme code

There's a dozen ways to deal with the hot plasma including but not limited to not injecting 15 whole fuel rods when it originally run on small fractions of one after you got it up to one megaenergy.

**Comment by AutismSpider** [comment]
were the fun in that sarah?

mean yeah can get good fuel mix to shit out rads none stop and get safe hot plasma

**Comment by sonime** [comment]
Yeah, I kinda wanna just have a basic system to radiate nearby mobs and allow collectors to pick up radiation for power.

There REALLY needs to be a standardized system for radiation, maybe have turfs be able to be "radiated" or not, and have mobs pick up radiation if they're on that tile.

But that's above my level of skill.

**Comment by sonime** [comment]
Well, the way I have it right now, 6 rad collectors with full room temp tanks will produce 100 megawatts to LITERALLY 1.21 gigawatts.

So the question is: is that balanced? Should it's power production be nerfed?

Then comes the questions of how much it should radiate nearby mobs, and then the 64,000 thousand dollar question.

What should be the drawback?

Seeing as how the R-UST is a nuclear reactor, I was thinking of having the EM field blowout if it gets too hot. But the R-UST can easily produce temperatures of 20 million Kelvin. So if the blowout conditions are high temperatures, a blowout would occur every other round that it gets set up.

So I was thinking of requiring the Tokamak to be emagged, otherwise the field would shut down and need to be restarted. This would mean that it would either get emagged at the start by a traitor engineer, or a traitor would have to sneak in, shut down the field, somehow get the atmosphere in the code to not raise alarms, meat the Tokamak, then restart the while engine.

This is, of course, assuming that the blowout would be a round ender in the vein of a supermatter cascade. From what I hear, the original plan for a blowout was an ETERNAL RADSTORM. If this remains the case, it would have to end the round like the cascade does, otherwise it would be nigh-impossible to call the shuttle.

Anyway, I'm asking for feedback on all this. What should the power output be like, how ducked up should people get if they're in rad range, and what should the trigger and conditions of a blowout be?

**Comment by kilkun** [comment]
> There REALLY needs to be a standardized system for radiation, maybe have turfs be able to be "radiated" or not, and have mobs pick up radiation if they're on that tile.

That should probably be done before this gets put in. Radiation has been snowflake as fuck since mport introduced the singulo and it's been in dire need of roundup for ages.

**Comment by sonime** [comment]
Wonder how easy/difficult it would be.

Right now, what produces radiation? The singu/PA, the supermatter, humans with the RADIATE block, radio transmitters, uranium turfs, and eventually the EM Field.

All that stuff will need to be standardized with rad levels and ranges. Furthermore, uranium turfs and RADIATE humans probably shouldn't radiate through walls, much like the Singularity currently works, whereas the Supermatter and what I plan for the EM field is to go through walls. Perhaps implementing some strength or penetrate var?

**Comment by kilkun** [comment]
Don't forget the radiation event.

**Comment by sonime** [comment]
Right! Although that would be somewhat easy to rework, just have all turfs in affected areas fan radiation status.

This seems like far too much for me right now though, due to my low level of experience. Furthermore, I can see issues with RADIATE humans causing radiates tiffs everywhere, since we already have issues with lighting and air sometimes not working as intended.

**Comment by ghost** [comment]
Just sayin, if you only have trace plasma that's not being sucked into the donut and you're throwing fuel rods into the core like hotcakes then yeah it's gonna cause problems.

**Comment by ghost** [comment]
So here's the thing. The R-UST was made by Cael from bay. There, their rwalls melt at around 6000C-8000C or so, so what'd happen if you were just jamming whole fuel rods into the core for gorillions of rads and kelvin is suddenly your walls begin to melt and everything tumbled down until it melted into space. This was the check on people that just jam rod after rod into the core.

Edit for the questions:
Output doesn't matter. Everything but solars trivially accomplishes 4,5+ times the station load for minimal effort. Even 2 minutes of chilling plasma for the sing.

For rads, I'd figure you scale it with the strength of the output. I'm not sure it'd be a good idea to go radio transmitter strong as there's only a few radsuits and virtually the entirety of the server is bad with anything radiation if the dj sat deaths have been any indication. Long as he has time to notice his health is in orange and can scream it's good.

For the trigger and effect, I liked how it was modeled in bay with the office melting down but we obv don't have that. Don't really have any good replacement ideas as you can rad it to hell and back, a radsuit is immune. As our walls don't melt and windows don't check adj it wont break containment and make the office too hot to service.

**Comment by sonime** [comment]
That's why I intend on making the field shut down if it gets too hot. Keeps that limit on there while not having to make some bullshit to emulate what Bay has.

I'd like to point out that with 2 rods I reached constant reactions and 20 million kelvin, and climbing.

**Comment by ghost** [comment]
How much plasma did you put into the core chamber? Edit: And what field strength.

**Comment by sonime** [comment]
10 gyrotrons, MAXIMUM STRENGTH. Injected about half a plasma canister, it all got sucked up by the field.

**Comment by ghost** [comment]
Well yeah, you hit a gorillion kelvin cause you had barely any plasma taking all that energy being produced. It's the same with sequential burn chambers or skimming in the incinerator.

**Comment by sonime** [comment]
Exactly! That's part of the design and balance we (I'm assuming it was you) talked about in the thread. You have a basic setup available that requires work to get it functioning properly. Part of that is having a handful of plasma containers for the rad collectors and for injection into the core. It would require more plasma to soak up the heat and get it to not blowout.

**Comment by PJB3005** [comment]
@caelaislinn (original author)

Also: Cael fixed that wall melting issue by instead of making it produce SHITTONS OF HEAT FOR THE TEG, it now makes bluespace particles or some shit that can get captured by a special machine to make the power instead, I don't personally agree with it but on Bay it's needed, sadly.

**Comment by sonime** [comment]
Yeah, I don't like it either. I love how the R-UST breaks every law of thermodynamics by making gas many times hotter than the core of the sun, and that it doesn't rely so much on bluespace magic.

**Comment by caelaislinn** [comment]
My mechanics overhaul still produces significant amounts of heat, it's just that leakage from the field into the core is no longer the primary method of heat generation. I deliberately kept it as a mechanic (heat leakage from the field) because it was !!fun!! and allows for different power production setups. 

2.0 also introduces semi-realistic radiation simulation. I haven't really put any thought into how "blowouts" would function, but it definitely wouldn't be a round ending catastrophe. Just a super !!fun!! random event if you're running the reactor above a certain level. 

Also temps at 20mil K is sort of intended, proficient engineers just need to make sure survivable amounts of heat leave the EM field.

**Comment by AutismSpider** [comment]
Rarely our human engineers set this up its our six to four legged autism spider bots who do this.Last time i set this up and hook it to the TEG the TEG bug out form how hot it got broke the atmospherics completely, eventually causing rounding errors to hard-set the temperature to 1 Kelvin.

**Comment by caelaislinn** [comment]
Yeah that's part of the reason I'm making TEG generation a secondary method. It's fun and all, but it's easier and a lot more controllable to just setup a burn chamber. With the new method I'm using (phasing) it's basically a funky interdimensional equivalent of the singulo rad collectors but with power gen rate actually tied in to the reaction rate in the field and a few other factors.

**Comment by sonime** [comment]
The main issue I'm having aside from actually coding a blowout (not every blowout would end a round, by the way, only traitor things could do so, I'll elaborate more on that later if you want) is by trying to find a way to balance the temperature gain. Right now, my idea to syphon out the oxygen and nitrogen and have only plasma in the chamber, hooked to a space-cooling line. I haven't tried it yet, partially due to laziness, partially due to inexperience with cooling and engineering.

**Comment by ihadtoregisterforthis** [comment]
So instead of "horribly broken" it's "horribly unimplemented"?

**Comment by sonime** [comment]
Apparently. One could say though that it's now broken in that it puts out power like your mom puts out pussy and it radiates the living fuck out of you if you're in range.

I need to redo the test map though, so I can test cooling procedures and find some "safe" levels to let the EM field run at.

**Comment by AutismSpider** [comment]
Making a cooling loop is easy part with a good set of layer pipes can turn the hottest room cold
