### ISSUE TITLE
Breaking a windoor only drops a glass shard and wires

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7657]
It should also drop airlock electronics, or at least broken airlock electronics.

**Comment by Exxion** [comment]
Reopen. This isn't fixed.

**Comment by clusterfack** [comment]
I actually see why, its two bugs in one, I only fixed the first

**Comment by clusterfack** [comment]
Try it after that gets in

**Comment by Exxion** [comment]
Thanks
I haven't actually tested it yet but I assume it works
