### ISSUE TITLE
Remove imidazoline overdose

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7659]
Currently it's possible to OD on fucking carrots. This is stupid. I also do not see a balance issue.

**Comment by ihadtoregisterforthis** [comment]
Also the wiki lists said chemical as not having OD limit. But it do

**Comment by FudgePucker** [comment]
> overdosing on carrots but not inprov, a stimulent for people with failing hearts

OD is really silly isn't it?

**Comment by PJB3005** [comment]
Why do carrots even fix your eyes...

THEY DON'T IMPROVE EYESIGHT AT ALL.

**Comment by ghost** [comment]
Same reason brain cake fixes your brain instead of giving you disease.

**Comment by Zth--** [comment]
(Because of balance and fun)
