### ISSUE TITLE
feature request: new atmostec/scientist traitor item, the water gun.

### ISSUE THREAD

**Issue by FudgePucker** [d3athrow/vgstation13#7660]
Yes you read that title right, a water gun.
A regent tank that can only be filled with hydrogen and a slot for an O2 tank.

With room temp o2 it acts like a Chen sprayer filled with water, use it to slip people or give it to the clown.

With cold o2 it makes snow. Be the funtag you always wanted to be and bring white powdery joy (not cocaine) to the station, or give it to the clown.

With hot o2 it produces steam, acting like polyacid dealing burn damage to people that aren't protected. Take down your target in a more subtle and unique way besides ebow esword, or give it to the clown.

With HOLY SHIT THATS FUCKING HOT atmos wizard o2 it just spits out hot o2 and hydrogen gas, causing the area to become fire. Go around making the flame thrower look like child's play as you watch the station burn to the ground... Or give it to the clown.

It uses mols of o2 every use and some hydrogen, meaning the hot and HOTTER setting use up more fuel.

It would provide a non bus way to make snow.

**Comment by Shadowmech88** [comment]
Perhaps to add a non-bus and non-tator way to make snow, add a civilian watergun that won't accept tanks with hot O2 in them, so all it can do is slip people and make snow.

**Comment by FudgePucker** [comment]
That would work too, and also add a traitor version as well
