### ISSUE TITLE
Rotate chair verb just picks a chair to rotate if all available chairs have the same name but opens a window to pick a chair if there are multiple names

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7662]
Also for some reason some of the chairs in the escape pod shuttle are named "Defense"

**Comment by Kurfursten** [comment]
The mapper used the chair instance from the courtroom instead of checking the name properly

**Comment by PJB3005** [comment]
Verbs killed when?

**Comment by Exxion** [comment]
It's also worth noting that it doesn't pick a chair very _well_. The way it picks the chair should be made more predictable. Though I'm not sure how possible that is, given the way BYOND handles verbs.

**Comment by Kurfursten** [comment]
You could just always look for a chair on your own tile instead of within 1 tile.

**Comment by PJB3005** [comment]
@Exxion literally nothing we can do other than provide a non verb-based alternative.

**Comment by d3athrow** [comment]
can't really have a list of same named things to pick from using the input proc as it combines them into one.
