### ISSUE TITLE
Artifact Lighters reset names

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7665]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 48128950c9eeee69fccfb8ec45b97c3a7a5ab723 
> 
> General description of the issue
> Artifact lighers from xenoarch change names back to cheap lighter after being turned off.
> 
> What you expected to happen
> It would remain an ancient cylinder or etc.
> 
> What actually happened
> It's name swapped to a fucking cheap lighter.
> 
> Steps to reproduce if possible
> Get an ancient lighter or etc from xenoarch, turn it on and off again. Voila, it is now named Cheap Lighter.

**Comment by Exxion** [comment]
I love hardcode
Is real_name a mob variable only?
