### ISSUE TITLE
Mime traitor item: Invisibility cloak

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7666]
Mime is invisible when wearing this on their head or exosuit, whichever. Things bigger than anything you can fit in your pocket (activated e-sword, stun baton, guns) appears outside the cloak as it would be difficult to hold under. Anything smaller (crowbar, emag, health anaylzer) is hidden by the cloak. Hides identity upon examination. cost 10 telecrystals or some high ass price.

You will be seen by anyone with thermals, and med/sec HUDs will show someone is there.

**Comment by FudgePucker** [comment]
Medical HUD showing up would be unique but having sechud show them would make it worthless, as security and power gamers, the two fucking groups you would want to hide from, would see it and scream over radio, MIME IS TRAITOR.
Also ebows and sleepy pens would be able to be used with out breaking cloak.

**Comment by Killette2** [comment]
I considered that they would be able to be combod with the e-bow, but if the cloak is expensive enough they won't be affordable unless you get 14 crystals or mug another tator. I did not consider the pen or a hypo, this would definitely be a powerful item.

Maybe it would balance out by not wearing it all the time as a mime? That way people wouldn't able to see you wearing it with their HUDs and not know you're a traitor, as you would hide most other traitor items.

Maybe it could be a jumpsuit with a toggle.

**Comment by FudgePucker** [comment]
Maybe give it the ability to not show up on thermals and huds if the wearer is dead, that you can murder someone and cover them with it and drag their body to dispose of, also maybe an implant for the mime or whoever puts it on to see the cloak itself.

**Comment by Killette2** [comment]
What if it was cell powered? You're completely invisible with exceptions. 50% and under HUDs and thermals will pick you up, 25% and under the cloak flickers, when it's dead it's useless.

**Comment by jknpj** [comment]
Already exists
