### ISSUE TITLE
OOC Bans Don't Wear Off

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7667]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 48128950c9eeee69fccfb8ec45b97c3a7a5ab723 
> 
> General description of the issue
> Ooc bans don't wear off.
> 
> What you expected to happen
> Ban would wear off after 20 minutes
> 
> What actually happened
> I was never unooc banned until next round
> 
> Steps to reproduce if possible
> OOC ban someone for some time, ban will not wear off until next round. I suspect even if its permanent it will unban you after the round ends.

**Comment by PJB3005** [comment]
Did you try to reconnect when the ban should've ended?

**Comment by Imagebard** [comment]
>Feature Request

This feature clearly isn't working as intended PJB3005
Are you serious

**Comment by PJB3005** [comment]
Yes, I'm serious, what he's requesting is code that checks if an OOC ban wore off yet.

The issue is that these bans and stuff are only checked when the client logs in (in most cases), for NORMAL bans this isn't an issue normally.

OOC bans however?

**Comment by 9600bauds** [comment]
this is not a feature request
