### ISSUE TITLE
Coin bags, an ode to terrible code

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#7668]
These bags are the result of another piece of bad and hard code machinery named "coin press".
- Money bags are accessed to take coins by clicking on them, and can be picked up by dragging the sprite onto oneself.
- Once on-hand, clicking on it with one's free hand will allow the person owning that hand to enter the menu, but nothing if one uses the same hand that holds the bag.

Now this is when it gets tricky
To change the bag from one hand to another, one can
- Drop it and get it with the other hand
- _If and only If it_ is on the **Left hand**, the bag can be dragged into the character's sprite
  - If it is on **the Right** hand the bag will simply drop to the floor

Not so bad huh?
- After dragging the bag onto self from any hand slot, _the bag stays on the original hand, and wherever the bag is, if the user uses the drop command on a hand, the bag **teleports back to the character**_
  - Passing the bag from Left to Right and dropping it _still leaves the bag in the Left hand, being able to recall it at any time with drop_
  - If the bag falls to the floor after dragging it from the Right hand, one can _drop from this hand to phase it into self, and **repeat it with the left hand afterwards.**_
### And the player can't interact with anything as long as the invisible bag stays on the hand

![death via moneybags](https://cloud.githubusercontent.com/assets/13305885/12252607/8ba382e2-b8b7-11e5-9fce-acabcebd5fee.jpg)

Also they don't have a sprite on hand so I can't look like a cartoon bank robber or Doctor Octopus on Spiderman 2

**Comment by ghost** [comment]
This is the best issue I've read. :+1:

**Comment by PJB3005** [comment]
99% sure N3X15 made them...

**Comment by FudgePucker** [comment]
They are haunted by their greed

**Comment by Exxion** [comment]
HEY GUYS GUESS WHAT
MOST OF THE BUGS LISTED IN THE OP APPLY TO **_ALL_** ITEMS YOU CLICKDRAG TO YOUR SPRITE TO PICK UP

**Comment by 9600bauds** [comment]
woo
