### ISSUE TITLE
Please update the drag/pull icon as soon as you start or stop drag/pulling, not in the next Life() tick

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7669]
Going into throw intent updates the icon instantly, drag/pull should do it too

**Comment by Exxion** [comment]
Why are these things updated in Life() at all? Almost all HUD updates could be just "event" based.

**Comment by clusterfack** [comment]
Well a good reason for that is due to the fact huds aren't continuous structures and will be reset upon relogging. And frankly to change them that much would be a total rewrite of the system, not that huds aren't due one.

**Comment by Exxion** [comment]
Yeah, so update when changed or when you log in. No need to update every tick.
Also, the internals button needs to do that. It always appears off when you log in.

**Comment by 9600bauds** [comment]
Just like do the thing throwing does

**Comment by d3athrow** [comment]
Should make use of event system
