### ISSUE TITLE
Make the smooth movement speed of locked atoms equal the smooth movement speed of the atom they are locked to

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7671]
Janicart riders lag behind the janicart and ghosts "lag" IN FRONT of the person they're haunting, in addition to many other things

**Comment by clusterfack** [comment]
This is a smaller part of a larger system that needs to be put into place to manually force glide sizes for specific delays.

i.e.:
-[] Singularity Pulling things (smoothed with power scheduler)
-[] Singularity movement (smoothed with power scheduler)
-[] Locked atoms (smoothed with their locked_to)

And more stuff that tbh I cant think of at the moment but feel free to put more examples
