### ISSUE TITLE
Deffiency Maint Medbay is just named 'Medbay'

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#7674]
On Defficiency, most abandoned maintenance areas are named in the vein of 'Abandoned Library', 'Abandoned Diner', and so on and so forth. The abandoned maintenance medbay, however, is simply named 'Medbay'. Since the APC in this area starts without a power cell, many confused engineers head to the actual medbay to investigate the resulting power alarm when the real issue lies on the other side of the station.

**Comment by CptWad** [comment]
Also I think theres a dorms APC in the HoP office meaning that it stays powered/unpowered in weird situations

**Comment by ghost** [comment]
[It's not maintenance]
