### ISSUE TITLE
Bedhead hairstyle inconsistency.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#7676]
https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/01/2016-01-12_19-24-45.webm

**Comment by CptWad** [comment]
I thought its supposed to look messy

**Comment by Ephx1** [comment]
I think it's that logically you would be able to see a hair sticking up on one side on the opposite side.
So like the top of the hair seems to grow and retract.

**Comment by ihadtoregisterforthis** [comment]
It flips up and down because the wind generated when spinning. But it works on a vacuum too.
