### ISSUE TITLE
Fully grown dionae cannot understand diona nymph speak

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7678]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 48128950c9eeee69fccfb8ec45b97c3a7a5ab723
> 
> General description of the issue
> Big Strong Oak chimpers, "*****\* s****"
> 
> What you expected to happen
> Big Strong Oak chimpers, "*****\* s****"
> 
> What actually happened
> Big Strong Oak chimpers, "fuck you slut"
> 
> Steps to reproduce if possible
> Be a diona
> evolve
> talk to a nymph

**Comment by Ephx1** [comment]
I think this is because Dionae nymphs just speak monkey as a default, they should speak rootspeak by default until they stab enough people.
