### ISSUE TITLE
Can't save special role preferences.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7686]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e69e9243ef3ee2894ef0a867d224ecd06fd85d17
> 
> General description of the issue
> I can't save special role settings.
> 
> What you expected to happen
> My special roles to be saved.
> 
> What actually happened
> They were not saved.
> 
> Steps to reproduce if possible
> Try to change your special roles and then save it.

**Comment by Exxion** [comment]
Yeah, it's fucked and has been for quite a while, but I guess no one reported it

**Comment by ghost** [comment]
REEEE

**Comment by Killette2** [comment]
It's pretty silly to mention dupes @clusterfack since the people in charge have been going on closing spree repeatedly of old issues rather than addressing them

**Comment by Exxion** [comment]
That's just Probe, and he seems to have stopped doing that

Also, I don't see the connection
We've always closed dupes

**Comment by Killette2** [comment]
Good

**Comment by Exxion** [comment]
Pretty sure this was fixed quite a while ago
