### ISSUE TITLE
Washing machine

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7687]
(WEB REPORT BY: rain7x REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e69e9243ef3ee2894ef0a867d224ecd06fd85d17 
> 
> General description of the issue
> The washing machine when clicked on while it is washing clothing says "The the washing machine is busy."
> 
> What you expected to happen
> It to say "The washing machine is busy."
> 
> What actually happened
> It says "The the washing machine is busy."
> 
> Steps to reproduce if possible
> Put clothes in washing machine, left click while it is still washing

**Comment by Kurfursten** [comment]
@9600bauds
