### ISSUE TITLE
Reducing combat log clutter

### ISSUE THREAD

**Issue by invoid9** [d3athrow/vgstation13#7690]
I'm not sure if it's better to have the whole message log filled with attacks, but what if all repeated messages just have an added 'times x' thingo?

Instead of:
"x honks y"
"x honks y"
"x honks y"
"x honks y"

Have something like
"x honks y" x4

Maybe if it had a slight animation when the number goes up or something, maybe the text gets silghtly bigger?

Dunno, just a thought.

**Comment by Exxion** [comment]
If we get our own game engine, that would be great. I don't think it's possible under BYOND though.

**Comment by PJB3005** [comment]
Should be possible with chat 2.0 though!

**Comment by Exxion** [comment]
Well hey would you look at that
This is possible now

**Comment by nuklearcellphoneg** [comment]
Wait, is it? If so that would be... pretty cool.

**Comment by Exxion** [comment]
Yep. Goonchat, being browser-based rather than just text output like we had before, allows for changing things that have already been put in the chat box.
Example: The new connection lost alert.

**Comment by nuklearcellphoneg** [comment]
W o w

What a time to be alive!!
