### ISSUE TITLE
Surgeon's Switchtool doesn't fit in medical belt

### ISSUE THREAD

**Issue by invoid9** [d3athrow/vgstation13#7691]
Seems like an oversight

**Comment by Kurfursten** [comment]
More like a feature request, surgeon's switchtool was made literal years after the medical belt

**Comment by invoid9** [comment]
My bad, I meant as an oversight to not code the surgeons switchtool to fit in the belt in the first place. Maybe it's not good for balance, I don't know.

**Comment by 9600bauds** [comment]
Don't you know? EVERYTHING is a feature request.

**Comment by Intigracy** [comment]
definitely an oversight
