### ISSUE TITLE
Trays have a double-defined throwforce and no defined force

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7694]
![image](https://cloud.githubusercontent.com/assets/9827785/12289096/5fc0cd6a-b9a7-11e5-9fe2-733f6d4e14f4.png)

I bet the first one is supposed to just say force
But if trays are really as robust as I have been told, should they even have 12 force?

**Comment by 9600bauds** [comment]
Yeh. Glass shards have 15 and they are not robust. It also takes a high throwspeed.

**Comment by Exxion** [comment]
I was asking if they should have 12 force, not 12 throwforce
Right now they have neither
...Actually, they have zero force and deal damage only due to their hardcoded organ damage I guess

**Comment by 9600bauds** [comment]
Magical

**Comment by Exxion** [comment]
I also like the thing at the end of their attack()
It amounts to:

```
if(prob(50))
  do a thing
else
  do exactly the same thing
```

EDIT: Wait no I misread that
The sound is actually different
It could be clearer though
