### ISSUE TITLE
Diona nymphs and dna modification

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7697]
Trying to scan their identity results in them being scanned as "unknown" even if they have a name.

Monkeying adult/nymph dionas renames them to generic "diona nymph (420)".

**Comment by 9600bauds** [comment]
dude weed lamaow

**Comment by ghost** [comment]
:^^^^^^^^^^^^^^^^^^)

**Comment by gbasood** [comment]
Additionally, ghost dionae will have their ghost name be "Fucker (as diona nymph (342))"

Probably a variable not  being properly set or something

**Comment by 9600bauds** [comment]
I really don't understand this issue sadly

**Comment by 9600bauds** [comment]
I whacked at this for a while and had no idea what was even going on.
