### ISSUE TITLE
Apply new haunting system to AI tracking

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#7698]
i maek feechur rekwest

New haunting system is super neat, I like being able to be exactly on someone without trailing behind and the screen stuttering to keep up. You know what would be cooler? Applying that system to a job that is practically solely tracking people. I think the only drawback to this is that antags would be more easily caught, seeing as how if one is zooming across station the AI stutters to keep up if they're not trying to predict their movements.

**Comment by ghost** [comment]
:+1:

**Comment by ihadtoregisterforthis** [comment]
plos gib

**Comment by gbasood** [comment]
> antags would be more easily caught

We could maybe make AI follow haunt work differently in order to make this harder. ID swapping with a mask, specifically, should make it harder for an AI to find you.

**Comment by Ephx1** [comment]
Actually if you do that now as AI you'll continue tracking.
What I mean is now, as an AI if you're tracking someone the game stutters behind making it hard to bolt doors, if we use the new haunting system then trapping someone would become quite trivial.
