### ISSUE TITLE
Invisible Grille Traps

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7701]
(WEB REPORT BY: dongilardoni REMOTE: 158.69.55.2:7777)
You can hide electrified grilles if you build a table on bottom of the grille's tile and then alt click on tile, placing items on the floor tab on the tabs bar, thus achieving invisible electrifying grille, very volatile at autistic engineer rounds.

**Comment by 9600bauds** [comment]
b-but muh 20MW in grid stops greytide u guis
