### ISSUE TITLE
Container-within-a-container inventory closes when you move

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7702]
To reproduce: Put box in backpack, open backpack, click+drag box into yourself to open the box without having to remove it from the backpack. Everything works fine and dandy, except that the box's inventory will close as soon as you move. This doesn't happen with the backpack's inventory, only nested inventories.

**Comment by Kurfursten** [comment]
iirc this was to fix an issue with distantly putting objects into/out of containers (e.g.: opening a bag and walking away, then putting an item into the still-open UI).

Objects that are inside your backpack aren't contained within you (they're contained within something contained within you) so I'm guessing that's what the check looks for

**Comment by 9600bauds** [comment]
Could be solved using getholder
