### ISSUE TITLE
Lubed outpost mining shuttles somehow gib you on docking

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7706]
I heard a miner saying they got gibbed too.

Steps to reproduce:
Lube the outpost shuttle
Slip your way over to the console
Send it to the outpost
Get gibbed

![lubed outpost shuttle](https://cloud.githubusercontent.com/assets/5564796/12311610/c173fe58-ba04-11e5-966a-7109fd375111.png)

**Comment by Sordine** [comment]
Oh jesus it's real, just tested it.

**Comment by AutismSpider** [comment]
Bet it happen with the taxi shuttles

**Comment by Exxion** [comment]
The taxi shuttles never gib you under any circumstances

**Comment by FudgePucker** [comment]
Needs HONK tag

**Comment by clusterfack** [comment]
Basically this https://youtu.be/mk7VWcuVOf0?t=2m26s

**Comment by PJB3005** [comment]
That Spaceballs video demonstrates it perfectly.

[IT'S A FEAAAATUUUUREEEEEEEEE]

**Comment by gbasood** [comment]
So basically a clown with all access can screw over an entire department in one lucky go
That's not a problem or anything

**Comment by clusterfack** [comment]
If anyone didn't realize at first glance it occurs because it slips you into the tile where its building the next shuttle component after it builds the tile you are on and forcemoves you into it
