### ISSUE TITLE
Broken bottles are broken

### ISSUE THREAD

**Issue by Sordine** [d3athrow/vgstation13#7707]
Broken bottles no longer do any damage.

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/12331143/4a62d7fa-bab6-11e5-83ca-b4c793caf8cd.png)

![image](https://cloud.githubusercontent.com/assets/9827785/12331153/54bc5f6e-bab6-11e5-936a-3970bba25029.png)

What the fuck
Who did that? Why?

**Comment by Exxion** [comment]
AAAAAAAAAAAAAH FUCKING WHY
THIS MEANS THAT BOTTLES BROKEN BY THROWING DEAL NO DAMAGE BUT BOTTLES SMASHED OVER SOMEONE'S HEAD CONTINUE TO DEAL AS MUCH AS A MEAT CLEAVER

**Comment by 9600bauds** [comment]
I thought everyone knew that broken bottles were circsaw tier

**Comment by Exxion** [comment]
But they're SUPPOSED to have force 9

**Comment by AutismSpider** [comment]
so fix it

**Comment by FudgePucker** [comment]
So you are telling me bottles are a one hit stun that becomes a high damage weapon? Why isn't ghetto bar looted every round?

**Comment by 9600bauds** [comment]
It was by me
