### ISSUE TITLE
Bug with Laser Scalpels and Incision Management Systems

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7709]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
For some reason, in surgerys where you do not require steps such as hemostats or retractors these two tools can no longer function as scalpels.

I was preforming a limb repair surgery to attatch limbs to a patient without limbs and the Laser Scalpel refused to work and would repeatedly give me the message that appears when you try to use an unrelated surgical tool in the middle of a surgery. The only reason I could figure it was giving me this message is that because the limb reattachment surgery doesn't require hemostat (Scalpel>Retractor>Cautery) it was trying to also behave as a hemostat, so it wouldn't preform the scalpel function.

This also happens if you try to use the Incision Management system in a surgery without hemostat or retractor.

Honestly this bug has been around for a really long time but I never got around to reporting it because I am lazy.

**Comment by Kurfursten** [comment]
This is because the laser scalpel and IMS do not actually do the normal steps, they have special snowflake steps

**Comment by 9600bauds** [comment]
Yes they do, the incision manager works as a retractor and the laser scalpel can work as either a scalpel or a cautery (toggle it in your hand). Neither works as a hemostat.

The wiki already explains this, including a notice literally saying "laser scalpels don't replace your hemostat", though I've added a notice on how to toggle mode in your laser scalpel.

**Comment by PJB3005** [comment]
So is this a bug or user error?

**Comment by 9600bauds** [comment]
PEBKAC

**Comment by 9600bauds** [comment]
Close me
