### ISSUE TITLE
MAP LITERALLY UNPLAYABLE

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7712]
(WEB REPORT BY: vuoristo REMOTE: 158.69.55.2:7777)

> Revision: 43c4b7b1544b482865b2f6cb7d1caa6472bc9fc 
> 
> General description of the issue: The warehouse shutters in Cargo close the wrong angle. http://puu.sh/mvIFZ/6c9846bf7e.png

Please fix.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Kurfursten** [comment]
Clusterfack was able to determine this was a screenshot from Defficiency

**Comment by Zth--** [comment]
What map
