### ISSUE TITLE
You can't resist out of package wrapped lockers anymore

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7715]
You get fucked.

**Comment by Arthurdentist** [comment]
as far as I am aware this has always been the case.

**Comment by gbasood** [comment]
Doesn't mean it should be the case

**Comment by Arthurdentist** [comment]
does mean its not a 'feature loss'

**Comment by Killette2** [comment]
It has not always been like this, I remember mailing myself as a clown and bursting out of the package as a surprise
