### ISSUE TITLE
Make sillycons only get alarms from their z-level

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7716]
because every time there's an atmos alarm in the Vox outpost, every sillycon leaps to those valids

**Comment by Ephx1** [comment]
Why would they leap to valids? Station vox and Miners go there all the time, sounds like someone needs a smack on the hand.

But really this would be nice for said Vox station and when derelict MoMMIs  set up atmospherics.

**Comment by 9600bauds** [comment]
By "leap to valids" I mean "quickly verify or discard Vox raiders to posteriorly leap to valids"

**Comment by CptWad** [comment]
what you think just the vox reason is good for this?
Derelict mommis would benefit more from this. fuck hearing how shit the other station is going, ditto when I am a station mommi and some fucker on derelict is dicking around with atmos and I get alerts to places that I don't care about

**Comment by Exxion** [comment]
I can attest from experience that borgs immediately attempt to secure valids upon the first atmos alarm on the trading post
