### ISSUE TITLE
Glass Shard Throwforce

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7718]
Is there any reason why glass shards have such a high throwforce? At w_class 1, they've got a throwforce of 15. A wrench, at w_class 2, only has a throwforce of 7. I'd expect throwforce to roughly scale with weight.

Among the items that have a throwforce of 15 are the spear, harpoon, hatchet, and battering ram. It doesn't make sense for glass shards, which can be found literally everywhere and are the lightest weight class, to have a comparable throwforce. Floor tiles have the same throwforce, but they're at least w_class 3 so the higher force makes some sense.

**Comment by gbasood** [comment]
The idea is that throwing glass shards at someone's face is probably going to hurt at least as bad as throwing a wrench at their face.

Not saying that the values of either of those things are necessarily good, but hey

**Comment by Shadowmech88** [comment]
I can guarantee that throwing a glass shard at a person's face would not hurt them more than throwing a wrench would.
A glass shard may be sharp, but that wrench would crack the front of their skull.

**Comment by AutismSpider** [comment]
Wrench would bust you fucking open/crack

Shard may or may not cut you.

**Comment by 9600bauds** [comment]
The actual damage something does on throw is roughly throwforce \* throwspeed.
Tiles are great throwing weapons because they have a high throwforce AND throwspeed. Glass shards don't. But I guess they hurt more than a pen.

**Comment by Shadowmech88** [comment]
Maybe not by hand, but in the pneumatic cannon for example, a glass shard will instakill someone if you use a large tank and set it to max pressure. Not even instacrit, I'm talking like 230 damage, if I remember my test right.
This is because the cannon applies its own speed. It divides this speed by w_class, meaning most items with high throwforce have their damage mitigated by also having a high w_class. But a glass shard having 15 throwforce and w_class 1 means it's a fucking monster when shot out of a pneumatic cannon.
The fact that glass shards are both so powerful and are literally everywhere seems like a problem to me.

**Comment by Cisrox** [comment]
Don't remember if this is true but I think I heard a myth somewhere about how they only do that much damage on the first throw and after that they have var changed which lowers the damage

[might not be true]

**Comment by Killette2** [comment]
Reminder that glass shards need to be sharpened to unlock their true damage, not sure if this applies to throwing but it damn sure can break bones in melee combat

**Comment by gbasood** [comment]
@Cisrox  not seeing anything in the source that modifies default throwforce for ANYTHING aside from rods in crossbows.

@Killette2 Sharpened how? (because I'm a scrub and can't find code for it anywhere.)

Glass shards inherit the base `/obj/item/weapon` throw_speed var, which is 1.
By comparison, a wrench has a throwforce of 7, and ALSO a throw_speed of 1.

ALSO, spears are the same as glass shards in terms of throw damage. Which is odd, because you'd think they extra weight would add some damage to the throw.
