### ISSUE TITLE
Greys not spawning with telepathy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7719]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
Several rounds in a row I spawned in without telepathy as a grey.
Dont know if it was purposefully removed or not.

**Comment by ghost** [comment]
It always has been a random chance to get the power, and a chance for a disability.

**Comment by ghost** [comment]
This one can be closed, seems it's just a random chance of it forming or not. (Rolled grey 4 rounds in a row, got telepathy twice)

**Comment by ihadtoregisterforthis** [comment]
They should get it all the time, it's their racial bonus for the minmaxing.
Also I thought random disabilities were for anyone, I got illnesses a few times at roundstart (as non grey).

**Comment by gbasood** [comment]
I honestly think genetics as a whole is just super duper fucked, considering issues related to vampires and changelings

**Comment by clusterfack** [comment]
More like someone just broke it, AGAIN

**Comment by gbasood** [comment]
@clusterfack The issues I'm talking about have been that way all of 2015 though????

**Comment by clusterfack** [comment]
Nah I fixed it at one point

**Comment by ghost** [comment]
Well, if we're gonna talk about on spawn mandatory mutations, what ever happened to the muton?

It's apparently supposed to spawn with strong and loud

**Comment by carshalash** [comment]
So uh, anything happening with this?
