### ISSUE TITLE
More suggestions for Alt-clickable machines like the chemmaster (and unrelated money printing)

### ISSUE THREAD

**Issue by invoid9** [d3athrow/vgstation13#7721]
More suggestions for allt
-Alt clicking unlocked cloning pods to eject
-Alt clicking sleeper and body scanner to eject, maybe the same for cryo patients
-Alt clicking microwaves to turn them on, maybe same with grinders to start grinding

Also, unrelated, maybe make printed currency from PDA go straight to your empty hand like when ejecting IDs from machines. If multiple types of credits are being printed at the same time, maybe have the rest spill or make a new item like a stack of rubber banded credits that can hold any credit type, and examining shows total or something.

**Comment by 9600bauds** [comment]
You can already click drag people in and out of sleepers and Cryo. A lot of people have requested the same thing so I am not sure how to make it more apparent that you can do so.
I like the microwave idea.

**Comment by Shadowmech88** [comment]
Would adding this functionality remove the ability to view the items on the machine's tile via alt+clicking the machine?

**Comment by 9600bauds** [comment]
Just like click the turf

**Comment by 9600bauds** [comment]
Leaving this here to remind myself to do this with the chemmaster
