### ISSUE TITLE
Mimewall emote text was written by someone who doesn't actually speak English

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7723]
![image](https://cloud.githubusercontent.com/assets/9827785/12369254/5ef54da8-bbc2-11e5-903e-d76fdd449911.png)

**Comment by Shadowmech88** [comment]
[Subject] mimes (the action of) "placing their(Subject's) hands on a flat surface, and pushing against it."
"Mimes" acting as a present-tense verb in this case.

The sentence may read awkwardly, but I don't think it's incorrect aside from the fact that "surfacing" should be "surface."

**Comment by Exxion** [comment]
Yes, that's it, but it seems so much worse

**Comment by 9600bauds** [comment]
I bet the Vox did this

**Comment by Kurfursten** [comment]
Gendered pronouns would be better

**Comment by 9600bauds** [comment]
let's not pretend that this isn't an absolutely atrocious message, and let's not hide the "surfacing" under the rug either

**Comment by Exxion** [comment]
> Closing an issue before the fix is merged

**Comment by gbasood** [comment]
Whoops
