### ISSUE TITLE
You can be a fat vox if you have a human character with the fat disability and roll Raider antag

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7725]
Since vox aren't supposed to be able to be fat, this obviously fucks everything up.
Also it doesn't appear possible to become un-fat as a vox.

**Comment by Shadowmech88** [comment]
Is there even a sprite for a fat vox?

**Comment by Exxion** [comment]
Nope
They look normal, but they can't wear exosuits
