### ISSUE TITLE
Sweet sundae ramen.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7727]
(WEB REPORT BY: carshalash REMOTE: 158.69.55.2:7777)
Recipe can not be made, the sundae can not be inserted into the microwave

**Comment by ghost** [comment]
``` DM
/datum/recipe/sweetsundaeramen
    items = list(/obj/item/weapon/reagent_containers/food/snacks/sundaeramen, /obj/item/weapon/reagent_containers/food/snacks/ricepudding, /obj/item/weapon/reagent_containers/food/snacks/gigapuddi, /obj/item/weapon/reagent_containers/food/snacks/donkpocket)
```

**Comment by Kurfursten** [comment]
I see what his mistake was now

The wiki reads confusingly, it says the recipe calls for "1 sweet sundae" when instead it should read it needs "1 sundae ramen"

He tried adding a sundae instead of a sundae ramen

**Comment by PJB3005** [comment]
So wiki issue?

**Comment by Kurfursten** [comment]
Yeah, I fixed it
