### ISSUE TITLE
Broken graphics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7728]
(WEB REPORT BY: wenter1138 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!) f2ed22a049f4492abbaaba12b6b264f466b70be6 
> General description of the issue
> http://imgur.com/tvBNOqR
> this is what my game screen currently looks like. This screenshot was taken in the engineering hallyway, but everywhere looks like this. There is a fire alarm going off I think, otherwise everything would be shades of white and gray. The red is flashing as it should due to the fire alarm.
> 
> What you expected to happen
> To be able to see anything in game, rather than just black, red, white, and gray squares. 
> 
> What actually happened
> All the textures are black, red, white, or gray squares. They do match up with normal areas for things, the black is generally shadows or areas that I can't see, the red in this picture is the hallway, and the white spots are the wals.
> 
> Steps to reproduce if possible
> Dunno, it started happening a while ago, before the last Byond update. I haven't played in a while, and I hoped maybe the update would fix the issue.

**Comment by SysadminJeroen** [comment]
That is a problem with lighting.
Can you toggle hardware accelerated graphics and then restart the game?
If that doesn't work, clear your BYOND Cache and restart the game.
If that doesn't work, restart your computer, clear your BYOND Cache again (just to be sure) and start the game.
If that doesn't work, I might have something else up my sleeve that fixed my problem recently.

**Comment by PJB3005** [comment]
As @Jeroen52 said, hardware acceleration is off in BYOND.

Make sure your drivers are up to date and such, since this is a BYOND issue there's nothing we can do here. If all fails ask on the BYOND forums.

**Comment by SysadminJeroen** [comment]
@PJB3005 I once fixed it by updating my Windows and restarting, I don't know how it got fixed but it was just fixed somehow.

**Comment by PJB3005** [comment]
Well Windows is truly magic.
