### ISSUE TITLE
No intercom units on Defficiency

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7729]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)

> Revision  f2ed22a049f4492abbaaba12b6b264f466b70be6 
> 
> General description of the issue
> Exactly what it sounds like. There are no intercom units on the Defficiency map.
> 
> What you expected to happen
> Intercoms being present. 
> 
> What actually happened
> No intercoms.
> 
> Steps to reproduce if possible

**Comment by gbasood** [comment]
There are intercom units, but there's so few that it's a huge issue I think. Glancing at the map render, I see about 10 units total.

**Comment by Duny-** [comment]
More than 100 actually (it stops counting after that), I'm going to gradually add some all over the map to fill the gaps.
