### ISSUE TITLE
Flatpack stack issues

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7731]
Two issues

>When un-stacking stacks, the sprites dont update properly, if you unstack a stack of five, you get 3 flatpacks, two with invisible flatpacks on top of them

>Mommis cant unstack flatpacks

**Comment by Zth--** [comment]
I found exactly how this bug reproduces. It depends on **where** you click.
If you unstack always clicking the bottom flatpack, you get no bug.
But if you unstack clicking on any of the above flatpacks, then you get invisible flatpacks.
I'm trying to get a fix but it's weirdly coded

**Comment by PJB3005** [comment]
Comiccode, not even once.

**Comment by CptWad** [comment]
@clusterfack Wait Mommis can unstack stacks now?

**Comment by Zth--** [comment]
No. I think it should be its own issue though.

**Comment by CptWad** [comment]
aight
