### ISSUE TITLE
No airlock button outside the science outpost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7732]
(WEB REPORT BY: tornader REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f2ed22a049f4492abbaaba12b6b264f466b70be6
> 
> General description of the issue
> Metaclub's scientific outpost doesn't have a button outside of the airlock, so you can't open it if it's closed or someone closed it
> 
> What you expected to happen
> there to be a button
> 
> What actually happened
> there wasn't
> 
> Steps to reproduce if possible
> go outside the scientific outpost on meta and you'll see

**Comment by gbasood** [comment]
fix when

**Comment by PJB3005** [comment]
wymi
