### ISSUE TITLE
Haunting doesn't always stick

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7736]
(WEB REPORT BY: krookodilehunter REMOTE: 158.69.55.2:7777)

> Revision: 9abe138c4b87a9498ee0bc380a022aec452acb22
> 
> General description of the issue: Haunting doesn't stick when someone is being dragged in a locker, or (when following a pet) when they're picked up and held.
> 
> What you expected to happen: Haunting to follow a mob no matter what.
> 
> What actually happened: Haunting doesn't always stick on a mob (see reasons above).
> 
> Steps to reproduce if possible: Haunt someone and wait for them to be put in a locker and dragged off somewhere. Or haunt a pet and wait for them to picked picked up.

**Comment by ghost** [comment]
Haunting doesn't transfer when they're shoved into any other object's contents. That's a problem with locked_atom techniques

**Comment by PJB3005** [comment]
@dylanstrategie more like shitily coded objects that don't have `forceMove()`

**Comment by ghost** [comment]
@dylanstrategie pls

**Comment by Shadowmech88** [comment]
Tested locally. I was able to keep haunting someone even after they were put into a locker and the locker was dragged around.
