### ISSUE TITLE
Radio transmitter isn't lethal

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7741]
I tried to murder with it, didn't work. 0/10, probably my fault

**Comment by Killette2** [comment]
Also I will note that the illumination lights were on, so the power wasn't cut.

**Comment by ghost** [comment]
It needs to be wrenched down I believe.

**Comment by PJB3005** [comment]
Pretty sure it was nerfed AND it was fixed so it needs to be wrenched down.

**Comment by Kurfursten** [comment]
Not just wrenched down but also wrenched over a wire

Radiation was lowered by 33% (66% if you cut a radiation wire), but that's still pretty lethal.

**Comment by Exxion** [comment]
Fucking good.
It used to be far too powerful.

[Not A Bug]

**Comment by gbasood** [comment]
Someone confirm it's not fucked completely and just working at nerfed values

**Comment by Killette2** [comment]
Wait it has to be wrenched down too? Fuck that's what I was doing wrong, I was used to mobile radio transmitter funtimes.

**Comment by gbasood** [comment]
Well then

**Comment by Killette2** [comment]
Also to note, it still gives the turning on and whirr messages while being pulsed, it just doesn't do anything.

**Comment by gbasood** [comment]
Well then I guess there's still an issue here

**Comment by Exxion** [comment]
There is still an issue here but it isn't the one the title suggests it is and the tags aren't really appropriate anymore

**Comment by gbasood** [comment]
NEW ISSUE
