### ISSUE TITLE
SLIDER BOXES AREN'T REAL BOXES

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7743]
They're children of `/obj/item/weapon/storage/fancy/food_box` DESPITE LOOKING LIKE CARDBOARD BOXES AND NOT EVEN USING ANY OF THE FEATURES YOU GET FROM USING FANCY STORAGE

The main issue here is that you can't collapse them into cardboard
Either resprite it to not plainly look like a cardboard box (and preferably use the icon updating features of fancy storage) or just make it an actual cardboard box.

**Comment by 9600bauds** [comment]
Why do they even come in a box

**Comment by ihadtoregisterforthis** [comment]
Make cardboard needed for slider boxes too then. The chicken bucket already does that.

**Comment by Kurfursten** [comment]
@9600bauds The microwave doesn't have any way of handling getting more than 1 product out of a recipe, so the boxes are a way to make 4 sliders at once

**Comment by 9600bauds** [comment]
obj/item/cocksucker

obj/item/cocksucker/New()
  for 1 to 4
    new(slider, src.loc)
  qdel(src)

make slider recipe return cocksucker

**Comment by Kurfursten** [comment]
> Syntax
