### ISSUE TITLE
Please add a paperbin to Box chemistry

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7745]
this is important for my autism

**Comment by Kurfursten** [comment]
While we're on notes about chemistry

> You can't use the hand labeler on pills

Why is there even one in chemistry?

**Comment by 9600bauds** [comment]
To label pillbottles
Why can't you label pillbottles with a pen?

**Comment by Exxion** [comment]
Wait
You can't use the hand labeler on pills?
I thought I removed all the snowflake no label allowed shit except for mobs

**Comment by Kurfursten** [comment]
I tried it last shift, no reaction

**Comment by Exxion** [comment]
OK hand labeler overhaul was something I did before I really knew what I was doing and I should clean up my shitcode anyway
I'll take a look at that later

**Comment by ghost** [comment]
> he doesn't use the colour coded pill bottle feature

I worked hard on that, damn it.

**Comment by 9600bauds** [comment]
Color coded pill bottles?

**Comment by ghost** [comment]
@9600bauds no, colour coded pill bottles. Right click them.

**Comment by 9600bauds** [comment]
> Right click them.

do you see the issue now
