### ISSUE TITLE
Bugs with Hypothermia

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7746]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7770)
For celt.

> Basilisks, something to do with min being max or whatever so you're instantly dropped to 20 C core temperature no matter what (Hardsuit doesn't help, chilli only reheats you after the blast rather than acting as a preventative to the cooldown, etc.)
> 
> Foam extinguishers don't change ambient room temperature or core temperature at all
> 
> Too much of a power difference between frost oil and capsaicin. 5u capsaicin put me to above 100 C core temperature, whereas 5u frost oil barely took me down 2 or 3 degrees core temperature.
> 
> Mancrowave, when emagged, fluctuates the poor sod insides core temperature between positive and negative of the next temperature (I.E 3000 C, -4000 C, 5000 C, -6000 C) and normalizing temperature once emagged drops their temperature into the negative, then resets them once they're "done"
> 
> emagged mancrowave sprite is way too obvious (Unemagged doesn't have the mancrowave logo on the side, whereas the emagged version does)
> 
> Cold doesn't affect carbon mobs such as monkeys, Pun Pun's been in the snow for an hour with just a top hat, and is still chilling as I'm typing this. Intended or no?

**Comment by PJB3005** [comment]
Tagging as [Not A Bug] because it's technically not in the code, _yet_.

**Comment by ghost** [comment]
@PJB3005 yet!

**Comment by ghost** [comment]
Other than the highly visible sprite these issues have been fixed, hopefully.
