### ISSUE TITLE
[Box] This one single conveyor belt switch is multidirectional, needs to be /onedir

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7747]
Related to #6923 
![space_station_13_2016-01-17_19-39-06](https://cloud.githubusercontent.com/assets/6526157/12380452/04a9d63e-bd52-11e5-8668-9365f23ec71a.png)
What's happening there is that when the lever is first touched, it will cause the conveyor to send the ores AWAY from where they're supposed to go.
This switch needs to have convdir set to -1

**Comment by ihadtoregisterforthis** [comment]
As in they pull and push? I take it as a feature, get the crates in and after unloading flip it and take them out.
This was like this long before the switch update.

**Comment by 9600bauds** [comment]
They're supposed to be locked in one mode only. Regardless you're not supposed to put the whole crate in, you empty it on top of the conveyor, and in any case you can drag it out of the plastic flaps
As it is right now, if you put ores on top of the belt and then flip the lever, your shit gets spilled on the ground. That's bad.

**Comment by Exxion** [comment]
I believe the cargo one needs this as well

**Comment by uazuaz** [comment]
i think that the bidirectional switch could have a modified sprite and functionality, check the picture:
clicking on the left side could move the switch to the left, clicking on the right side could move it to the right, center to stop it.

![04a9d63e-bd52-11e5-8668-9365f23ec71a](https://cloud.githubusercontent.com/assets/6170726/12400816/9ff0fbec-be22-11e5-8e75-874f33fae0dc.png)

**Comment by 9600bauds** [comment]
Edited to make the issue only about that one switch which is not onedir, unlike the rest of the mining station ones

**Comment by 9600bauds** [comment]
This somehow got autoclosed when it wasn't meant to, still is an issue

**Comment by Exxion** [comment]
Because any phrase containing any form of "fix," "close," or "address" followed by an issue reference autocloses the issue, including "Does NOT fix #7747"

**Comment by 9600bauds** [comment]
amazing

fucking computers always doing what I tell them to

**Comment by ihadtoregisterforthis** [comment]
PC rogue blow it

**Comment by Exxion** [comment]
I mean
Technically speaking, it did exactly what you told it to, as documented... somewhere. I forget where.
You just didn't mean to tell it to do that.
