### ISSUE TITLE
Smashed walls may not update atmos properly

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7757]
I guess that title is a bit misleading but I can't come up with a better one that isn't ridiculously long. Smashed walls are definitely _capable_ of not updating atmos properly but I don't know under what circumstances they do and don't. All I know is that earlier there was a very clear hole open to space (it was in maint above sec but that's not important because I already checked if it was something weird about that particular turf) that had been smashed open by (I think) a xeno and not a single molecule of air leaked out. 101.3kPa inside, 0 outside.
I can't confirm this at the moment, but I THINK it also happens when asteroid mobs smash walls.

**Comment by gbasood** [comment]
If someone can reproduce this I'll add it to the feature freeze milestone

**Comment by Exxion** [comment]
I _think_ I've seen it happen twice, but the other time was quite a while ago and I was too busy being spooked by another bug to notice for sure.
I'll try to reproduce it on local later

**Comment by Exxion** [comment]
Alright, now this is mysterious.
I cannot reproduce it on local. I tried both player-controlled and standard mobs and I even tried the very same turf that I saw the issue with earlier. I didn't test the exact kind of mob that broke the wall when the bug occurred, but they use the same code to break walls.
I should probably mention that I ahelped it when it happened and the admin didn't know what was going on either.

I'd look at the code to see if I could figure out what happened but I sure as fuck don't understand ZAS code.
Does anybody?

**Comment by Imagebard** [comment]
Related to #3204 maybe

**Comment by Exxion** [comment]
No, space was the only unsimulated turf involved and space usually works

**Comment by Intigracy** [comment]
Ever able to reproduce?

**Comment by Imagebard** [comment]
Well, there's issue #8711
What do you think?

**Comment by Exxion** [comment]
Other people have encountered it, but no, I don't think anyone has ever been able to reliably reproduce it. It just... happens occasionally, usually when a mob breaks a wall.

**Comment by Intigracy** [comment]
Was it laggy at all when you've encountered it?

**Comment by Exxion** [comment]
I've only _definitely_ seen it once, and the server was fine at that time, but I don't know whether or not it was fine at the time the wall was smashed.

**Comment by Exxion** [comment]
This still happens (more often than when this was opened, in fact), but some much newer issues have more info
