### ISSUE TITLE
set_light(1) Isn't Bright Enough to Do Anything

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7759]
With soft lighting, things with a light level of 1 aren't bright enough to increase the amount of visibility you have.
I think 1 should be the mid-point between the brightness of set_light(2) and the default soft lighting brightness in complete darkness.

**Comment by 9600bauds** [comment]
I have no idea what to tag this.

**Comment by ghost** [comment]
Not really a bug? I don't see how this is a problem.

**Comment by Shadowmech88** [comment]
It's a problem because things that previously provided a small amount of light now effectively provide none at all.

**Comment by PJB3005** [comment]
They never did though.

**Comment by 9600bauds** [comment]
Yes they did, for example biolum fruits. I even asked you in the IRC and ended up just giving them set_light(2).

**Comment by PJB3005** [comment]
Was that pre-baylights though?

If so: erm.

@Mloc you got any idea?

**Comment by 9600bauds** [comment]
Previously, set_light(1) items would glow faintly. Now they don't do anything because set_light(1) doesn't work anymore. I don't really know at which point it broke, but that's the bug report.

**Comment by Shadowmech88** [comment]
@PJB3005 I spoke with you at length in IRC about this.
Previously darkness was pitch-black, and set_light(1) items would give off a faint glow.
Now with soft lighting, set_light(1) items aren't bright enough to have any measurable change on visibility.
Cigarettes, for example, used to provide a small amount of light in the dark. There's even a comment in the cigarette code that suggests such, yet they provide no additional light since soft lighting was added.

I believe you told me that there was some lighting calculation proc that dislikes being fed a 1.

**Comment by PJB3005** [comment]
The issue isn't related to soft lighting, it's the fall-off formula breaking at a size of 1

**Comment by Shadowmech88** [comment]
Alright, well then that's the bug.

**Comment by Shadowmech88** [comment]
This bug still exists.

**Comment by PsiOmegaDelta** [comment]
Any value strictly larger than 1 will do, for example set_light(1.01)

**Comment by Shadowmech88** [comment]
I guess that's better than them _not_ working, but it feels like a really hacky solution as opposed to fixing the fall-off formula to accept 1s.

**Comment by Shadowmech88** [comment]
Also I just tested it, and the smallest number that seems to generate an actual visible change in the lighting is 1.3.

**Comment by PsiOmegaDelta** [comment]
Well, have to admit I based my answer on Bay's current lighting system.
