### ISSUE TITLE
Stripping someone often displays messages saying you're trying to put your held item on said person

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7760]
Attempt to remove belt from person with stun baton in hand, "Urist McGit is trying to put a stun baton on Locker Weldspace"
As far as I know, this is only for other people, not you.

**Comment by Exxion** [comment]
As in it only shows up for other people?
No, it shows up for you, too. Or at least it does when I do it.

**Comment by gbasood** [comment]
The textual bug that's existed for as long as the ability to strip people has

**Comment by PJB3005** [comment]
I think the issue is that the code sees "this guy is using the stripping menu AND holding something in his hand: therefore he must be trying to place it _on_ the target"

Oldcode. Not even once.

**Comment by 9600bauds** [comment]
Yeah it also displays the wrong message to you, not just other people.

**Comment by 9600bauds** [comment]
holy SHIT, I thought this would be easy to fix
I don't know why people talk about lifecode when inventorycode is even worse
The code for stripping people is genuinely the worst thing I have seen in the whole repo

**Comment by clusterfack** [comment]
Because it's legitimately old as hell

**Comment by PJB3005** [comment]
Bay rewrote stripping IIRC, port when?

**Comment by clusterfack** [comment]
ERP ALERT

**Comment by 9600bauds** [comment]
Fucking hell yes I'd rather try porting something than unfucking THIS MESS
![atom_2016-05-31_13-13-33](https://cloud.githubusercontent.com/assets/6526157/15688650/774a95c0-2751-11e6-8b01-8a0ebc7625ea.png)
Why is stripping even tied to effects? Efects that qdel themselves? What the fuck is going on? What's this about "syringe", "pill", "drink", "dnainjector" and "fuel" stripping slots? What?

**Comment by 9600bauds** [comment]
Trying to port from Bay was a mistake
The good news is that I have ascended and will soon remove hitler from the code

**Comment by ghost** [comment]
@9600bauds how does it feel knowing this was tagged with "easy fix"

**Comment by 9600bauds** [comment]
Well, fixing JUST the message would be an easy fix
http://www.dailymotion.com/video/x2gp98t
