### ISSUE TITLE
Radio transmitter still acts like it's being turned on when it's not wrenched down

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7761]
Originally #7741 

> Also to note, it still gives the turning on and whirr messages while being pulsed, it just doesn't do anything.

**Comment by ghost** [comment]
May just be me having no idea what to do to reproduce this, but I couldn't.

**Comment by gbasood** [comment]
To reproduce don't wrench it down and try to turn it on I guess
If it doesn't reproduce that way then it's closable

**Comment by BarneyGumball** [comment]
Could not reproduce.  Tried leaving the multitool menu open, unwrenching it and then trying to turn it on but it did nothing.

**Comment by Zth--** [comment]
Need moar testing? Close it? Honk?
