### ISSUE TITLE
Doubletraitor

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7762]
You can be traitored twice
meaning two sets of objectives
>Kill someone
>Escape on the shuttle or an escape pod alive and free.
>Kill some other person
>Die a glorious death!

Along with two pda codes, one that does not work

**Comment by Exxion** [comment]
#7042 
Come on now it's even the same issue name

**Comment by CptWad** [comment]
I was told that it was not reported after I adminhelped.
Closing
