### ISSUE TITLE
Mommi's with the parking break on can get out of flashes

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7763]
I tried to flash a mommi but it could still move, after much effort and repeated (failing) flashes I managed to emag it
It told me that its parking break would let it out of flashes
I saw the parking break lights on the mommi so I imagine it DOES work like that
would require two people to test properly

**Comment by Kurfursten** [comment]
You can test it with one person by spawning in as a MoMMI (or player panel for transformation to MoMMI) and then aghost + secrets (spawn in as a test dummy) after you've set the parking break

**Comment by Imagebard** [comment]
What part of "properly" do you not understand.

**Comment by AutismSpider** [comment]
Oh this is funny parking break taking them out of the stun state  for bit then they go back into it

**Comment by Kurfursten** [comment]
@Imagebard The word you're looking for is "easily", not "properly"
