### ISSUE TITLE
Ripley can tell the difference between diamond and gibtonite but not very well

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7765]
1. If you try to drill gibtonite ore by walking directly into it, you just get a message saying that safety features prevent that action or something. This is good. The only problem is that your chat window is spammed with this message a dozen or so times per second while you are walking into the gibtonite ore.
2. This is (as far as I know) the only way to tell gibtonite apart from diamond while in a Ripley (other than mining it, of course). You can't use your mining scanner even if it's in your hand unless you get out.
3. While you can't accidentally drill gibtonite by walking directly into it, the Ripley has no qualms with mining that gibtonite ore directly _adjacent_ to the tile you accidentally walked into.

**Comment by Ephx1** [comment]
Why not just make it so that Ripleys automatically disable gibtonite and mine it out?
It's not as though miners actually use them, and it's an incentive to use it overall.

**Comment by gbasood** [comment]
Making ripleys good is good

**Comment by Exxion** [comment]
I don't understand why so few people like mining with Ripleys because it's the best
Mechs in general need a little overhaul though
That stats window is too obnoxious because doing anything with it unfocuses the main BYOND window

**Comment by Ephx1** [comment]
The Ripley is a walking coffin with monsters. As I recall they instantly target mechs over all other things.
And I imagine after the initial mining delivery Miners don't do anything else but kill monsters.

> Mechs in general need a little overhaul though

Good luck finding ANYONE to do that.

**Comment by Exxion** [comment]
I haven't tried fighting anything other than a space carp in a Ripley but a space carp managed a whopping 6% of the Ripley's integrity before I killed it

**Comment by Ephx1** [comment]
Considering they only have 50 health that's not too much.
Compared to say, a Goliath.

**Comment by Exxion** [comment]
By my math, based on the health and damage of a space carp compared to those of a goliath, a goliath could deal about 20% of a Ripley's integrity before being killed

**Comment by Exxion** [comment]
Fuck I fucked up I shouldn't do math when tired
It's 120%
You're right

**Comment by PsiOmegaDelta** [comment]
As for why you likely get super-spammed with messages:
The mechs only set the movement delay on successful movement. If they fail to move, you can immediately try again the next tick.

**Comment by PJB3005** [comment]
@Ephx1 @Zuhayr rewrote mechs for Yonaguni, they're FANCY AS SHIT.

**Comment by Ephx1** [comment]
Then just steal that, whatever "Yonaguni" is.

**Comment by MistakeNot4892** [comment]
They're not finished.

**Comment by Shadowmech88** [comment]
@Zuhayr out of curiosity, did you end up finishing that mech rework?

**Comment by MistakeNot4892** [comment]
Nope!
