### ISSUE TITLE
Make Vox Toxin Damage For Oxygen Based on %

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7767]
Apparently vox take a flat damage rate if there's any amount of oxygen in the air. This doesn't really make sense, more oxygen in the air should be more poison should be more damage.

I think we should change it so that vox take the same damage they do now at 80% O2 air, then scale it back from that based on the percentage of O2 in the air so that you take less damage from 1% oxygen 99% nitrogen than you do from normal air.

**Comment by gbasood** [comment]
How do humans handle similar situations?

**Comment by Shadowmech88** [comment]
What, like breathing plasma?
I'm pretty sure plasma toxin damage scales with % in the room. At low percentages plasma isn't even visible in the air, so I doubt it starts poisoning you before that point.

**Comment by 9600bauds** [comment]
Related thing I would really appreciate: Have Vox gasp when they're taking oxygen poisoning. It's not entirely obvious, especially not to people that could disable their internals by accident, like Sec and Medbay.

**Comment by Shadowmech88** [comment]
Or make a different breathing-related emote and have them do that instead, so they can tell the difference between suffocation and breathing O2.
Has to be something besides coughing and wheezing since those are already taken by virus symptoms.

**Comment by 9600bauds** [comment]
Maybe they retch at the horrible scent of this poison gas that these wackos sniff all day and precariously stuff their stations with, even if it means making them a fire hazard

**Comment by 9600bauds** [comment]
Uh also

>80% O2 air

air does NOT have 80% oxygen content unless you're about to be surprise plasmaflodded by a particularly crafty and sneaky tator atmostech

**Comment by Shadowmech88** [comment]
Oh, I got that mixed up. Normal air is 20% O2 80% N2, right?
Might affect balance considering if they get normal damage in a 20% O2 environment, with this they'd get crazy insane toxin damage in a 99% O2 environment.

**Comment by 9600bauds** [comment]
Just like cap it, but then again the only real common scenario that I can foresee a 100% O2 environment is either a deliberate GAS THE VOX cage or a misguided oxygen tank set to internals, which would still only be 21kPa unless you tuned it up.

**Comment by Shadowmech88** [comment]
When trying to quickly repressurize an area, atmos techs usually use gas canisters because they're portable and fast.
In my experience, most hook such a canister directly up to the O2 miner for filling instead of bothering to get a proper mix of air.
