### ISSUE TITLE
Shot Gun Darts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7768]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Just sort of peeves me. Shotgun darts are called 'Shotgun Darts' but they are only a single dart
> 
> What you expected to happen
> Be multiple darts, a box maybe. Or it just say ' Shotgun Dart'
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by 9600bauds** [comment]
They're also shit.

**Comment by Exxion** [comment]
They also don't actually work. They don't hold or inject reagents like their description claims.

**Comment by Shadowmech88** [comment]
If they did, wouldn't it make shotguns essentially a syringe gun with a larger magazine?

**Comment by 9600bauds** [comment]
Well, yes, but the syringe gun becomes a little bit less of a syringe gun when it's not right next to a chloral dispenser.

**Comment by Shadowmech88** [comment]
Unless you want to fill the darts with alcohol, I can't think of anything useful you can put in them that wouldn't require access to a chem dispenser.
And if you've got access to a chem dispenser, you've got access to chloral.

**Comment by Exxion** [comment]
Only combat shotguns have a larger magazine than syringe guns
Double barrel holds 2 shells, standard shotgun 5, combat shotgun 9, counting the chambered shells for the latter two.
Also darts are harder to get a hold of than syringes

**Comment by gbasood** [comment]
Sounds like eventually we'll want to make shotgun darts not shit but for now the PR fixes the issue this was created for
