### ISSUE TITLE
Make Electrical Arcs Form With High Enough Power in the Grid

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7770]
I think it'd be neat if electricity would arc between sufficiently close wire knots/electrified grilles/shocked doors if there was enough power in the grid.

**Comment by Exxion** [comment]
We don't have positive and negative terminals, which is too bad because with then there would be some super ultra cool things you could do with a feature like that

**Comment by AutismSpider** [comment]
if its going Arc should be form APCs/Airlocks that been screwdriver open etc.

**Comment by Kurfursten** [comment]
I don't like it because there are a lot of wires and if they are even checking for things within 1 tile of them that is a very large number of tiles to check per tick

**Comment by Shadowmech88** [comment]
Even if only knotted wires make the check?

**Comment by Kurfursten** [comment]
That would definitely be less wires, but most of the arcing would be happening on the solars

**Comment by AutismSpider** [comment]
solars are rarely set up when you can jerk off with one hand use the other to set the TEG for easy  5 to 10 MWs of power!

**Comment by Shadowmech88** [comment]
Make it so only knotted wires with no other wires on their tile make the check, so that nonsmooth wiring doesn't lead to arcing, only disconnected wiring.

As far as the disconnected knots on the solars, if the solars aren't set up then those wires wouldn't be hooked up to the power grid.

**Comment by FudgePucker** [comment]
Also knots under APCs and other devices like emitters.

**Comment by gbasood** [comment]
Don't especially like this idea myself. The potential for an engineer to make the whole station a safety hazard just by increasing energy output is ridiculous.

**Comment by Exxion** [comment]
I would like the idea if we had a more realistic electricity system, but with our current one, I have to agree with Sood.

**Comment by PJB3005** [comment]
Yeah I agree, if we had voltages and amps and such it'd be a cool idea, but not in the current state.
