### ISSUE TITLE
Ya fuckin broke Double Agents again

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#7771]
http://imgur.com/7QWZL1C

I'll just leave this here

**Comment by ghost** [comment]
Last I checked, this was considered a feature because it allows people in lowpop to get on with their shenanigans.

At least, that was the reason given for closing it last time.

**Comment by gbasood** [comment]
There's zero reason that an objective should ever be duplicated.

Should do a simple logic check:

``` DM
// When adding an escape objective
for (objective/O in objectives)
    if(istype(O, escape))
        DO NOTHING
```

**Comment by MadmanMartian** [comment]
they no longer exist
