### ISSUE TITLE
Corgi Hardsuits are broken

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#7773]
Only works for Engineering hardsuits, and the icons don't show up correctly.

Someone fix my mistakes for me pls

**Comment by Kurfursten** [comment]
How does a human hardsuit that can't fit on a humanoid alien manage to fit on a Corgi?

**Comment by Exxion** [comment]
Why must you abuse the [Honk] tag like this?

**Comment by clusterfack** [comment]
100% Tested

**Comment by gbasood** [comment]
I only honk tag things that:
- Don't matter
- Are funny
- Probably some other variation of 'shit that doesn't matter'

**Comment by ihadtoregisterforthis** [comment]
Collaborator abuse and rude, remove [honk]

**Comment by Killette2** [comment]
> Not powergaming hard by putting a hardsuit on Ian then picking him up and carrying him with you
