### ISSUE TITLE
no advice when a posibrain is activated

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7774]
if someone is harvesting dionaea, you have an advice in chat asking you if you want to teleport or sign up to be the diona; it would be nice if the same thing happens when someone activates a positronic brain.

**Comment by CptWad** [comment]
How posis work is that you have to click on the posibrain(s) you want to be
which means some older roboticists sometimes keep them fuckers in their backpacks and wonder why the lights keep flashing when the posibrain does not work

**Comment by Ephx1** [comment]
> it would be nice if the same thing happens when someone activates a positronic brain. 

Fairly certain this is already a thing, although interestingly I got an option to be one, signing me up automatically, but the posibrain picked absolutely no one.

**Comment by uazuaz** [comment]
@CptWad 
i know that, but this way you need to camper the robotics room to see if someone activates it, and if someone moves the posibrain around you need to search for it; it would be a lot easier with an advice.

@Ephx1 
only if you set the "be positronic brain" option in the antagonists settings as "yes", and it signs you up to be one automatically, like you just said.
there is no reason to not have the same advice when someone sets it as "no", like it happens for the diona setting.
