### ISSUE TITLE
Upgrading freezers

### ISSUE THREAD

**Issue by Chronakai** [d3athrow/vgstation13#7775]
When you try to open a freezer's maintenance panel with a screwdriver to shove better parts in it, it says it has to be unanchored with a wrench.
Unanchor it and try it again, and it says it has to be anchored to do that.

What the fuck.

**Comment by CptWad** [comment]
Not like its worth it
Ive managed to upgrade them before, and you may as well use an RPD since upgrading it is marginal, but still worse than a regular cooling loop.

**Comment by Zth--** [comment]
Couldn't reproduce.

 ![honk](http://puu.sh/mCmJI/e882e91e3f.png)

**Comment by gbasood** [comment]
Pretty sure I haven't had this issue myself actually and I've upgraded freezers several times in the last few weeks
