### ISSUE TITLE
Facehugger (toys?) can sometimes leap off a face they're already on, without being removed from the face slot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7780]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 486bf3c1417b633cca6c2a88d71bf61b673a197b
> 
> General description of the issue

Facehugger toys (I think they're standard toys) can sometimes leap off a person's face, but sitll remain in a person's clothing. It will bug out on that person's hud until picked up again, and then immediately show up in the mask slot again. If at all.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

fuck

**Comment by CptWad** [comment]
AAAAAAAAAAAAA
#7073

**Comment by gbasood** [comment]
This SHOULD be fixed now, please let me know
