### ISSUE TITLE
You know how everyone says we need a bottle rack to hold the bartender's bottles? Yeah there's actually already a drinks smartfridge in the code.

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7784]
IT'S JUST NOT ON ANY MAP AND ITS CIRCUITBOARD ISN'T IN THE LIST OF CONSTRUCTIBLE DESIGNS
WHY?

**Comment by AutismSpider** [comment]
Does it have its own icon or does it look like any other smartfirdge?

**Comment by Exxion** [comment]
I think it looks like any of the others, but anyone who can sprite worth half a shit can fix that

**Comment by 9600bauds** [comment]
The smartfridge, with it's stark white menu that bundles similar items together, was clearly intended for the Kitchen/Medbay where you need to hold hundreds of different items and have them categorized.
I have a better idea for a bottle rack, why not just make it a dense and anchored storage item that opens on click? It would be like a big big backpack that you can't move. I feel like that would be a lot more satisfying to use and would look a lot more rustic than using the same UI we use for pills and wheat. Besides I don't think a bartender needs to hold more than 30 bottles at the same time, right?

**Comment by Exxion** [comment]
That wouldn't solve the problem of having to Alt+click/right click on the tile to be able to grab the bottle you want though
Because you have to do that with anything more than like seven bottles

**Comment by ihadtoregisterforthis** [comment]
Use a tray

**Comment by Exxion** [comment]
OH I misunderstood what you were saying, Bauds
Yeah, that would work
...Actually, that sounds perfect
If someone will get sprites for it I'll code it
