### ISSUE TITLE
You add the monkey meat to the Smart Chemical Storage

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7785]
The chemistry smartfridge has the base reagent_container in its list of things it can hold, which means it can hold literally any food, drink, condiment, etc.

**Comment by ghost** [comment]
Isn't it identical in everything to the kitchen storage? I thought it was just a var edited name on a regular storage.

**Comment by Exxion** [comment]
Nope
Every smartfridge type has a different list of things it can hold
However, the chemistry one specifically can hold anything any other smartfridge can hold except seeds and slime extracts because all food and drinks are children of `/obj/item/weapon/reagent_containers`

**Comment by Iamgoofball** [comment]
why is this a problem exactly?

**Comment by gbasood** [comment]
Good question, actually.

**Comment by Exxion** [comment]
The Smart Chemical Storage completely outmodes all other smartfridges except the seed and slime ones for no good reason. It has the same parts and one circuitboard but is a direct upgrade over all other smartfridges except those two.

The secure medbay storage has a much more reasonable accepted types list that still encompasses everything the Smart Chemical Storage is actually used for. I vote we just copy that list to the Smart Chemical Storage.
(It holds pill bottles, reagent_containers/glass, and pills, as opposed to pill bottles and all reagent_containers.)

**Comment by Iamgoofball** [comment]
why does that matter, is the smart fridge metagame a crucial part of the station vs traitor experience? is putting monkey meat into the smartfridge in medbay going to cause problems? what if a botanist wants to give the chemistry department a lot of plants to grind down?

+

why not just make the "hold all reagent_containers" shit the default for all smart-fridges instead?

**Comment by 9600bauds** [comment]
Hear this goof for he speaks the truth

**Comment by gbasood** [comment]
I don't see a problem with making all fridges hold all the shit. Worst case, bartender can hide chloral in a innocent-looking smart fridge.

**Comment by ghost** [comment]
See no problem with that, it's a fridge, it holds all sorts of fun stuff. If Medical wants to use it as a food fridge, it's for them to see

**Comment by gbasood** [comment]
It's a lot more silly that other fridges wouldn't be able to hold the same things I think

**Comment by Exxion** [comment]
Sure, works for me

**Comment by Exxion** [comment]
Wrong button fuck

**Comment by ghost** [comment]
Meat should be in the medical fridge for biomass. This is not a bug pls remove from freeze @gbasood

**Comment by Exxion** [comment]
The standard medical fridge (as opposed to Smart Chemical Storage) (I'm not sure if it actually appears on any maps but whatever) can't hold meat

**Comment by ghost** [comment]
NOT A BUG

DELETE THIS

**Comment by gbasood** [comment]
whoops

I'll leave it open because it brings up an interesting point about smart fridges in general though
