### ISSUE TITLE
Hover Pod Speed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7787]
(WEB REPORT BY: gunosaguki REMOTE: 158.69.55.2:7777)
Not a bug. just a suggestion. For how rare it is, it could stand getting a speed increase, at least in space since its basically an ancient space pod mech

**Comment by Shadowmech88** [comment]
I think it should move at the same speed as the space pod and just essentially be a space pod that only takes up one tile.
I mean, literally anyone can build a spacepod in the pod bay, yet this is a rare xenoarch find. It should be at least as good as a space pod.

**Comment by AutismSpider** [comment]
it should move at space pod speed in zero kpa zones slow as dirt at normal kpa zones

**Comment by ghost** [comment]
Considering it's a reference to 2001: Space Odyssey, could do with some extra features like it being able to grab things in space with maybe some sort of built in hydraulic clamp

**Comment by Gunosaguki** [comment]
I actually did try to put a clamp on it after placing a drill. it would be nice.

**Comment by gbasood** [comment]
Pretty sure hover pod buffs have been requested repeatedly, surprised it hasnt been buffed yet

**Comment by ghost** [comment]
There's something odd about hoverpods. I was trying to varedit one yesterday, and not only would it keep resetting to 10, but also add the number I was trying to change it to (It ended up at 10443 before I gave up)

**Comment by FudgePucker** [comment]
I made a relevant feature request. #6891

**Comment by Exxion** [comment]
#12288
