### ISSUE TITLE
Bunsen burner

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7789]
(WEB REPORT BY: gunosaguki REMOTE: 158.69.55.2:7777)
Holy Shit Please make the bunsen burner its own table so you dont have to carefully aim to not fucking spill your beaker on the floor or place it on the table.

Or at least make it so alt clicking the burner turns it on. its the most annoying peace of simple machinery left

**Comment by Intigracy** [comment]
tbh it just needs a better sprite

**Comment by clusterfack** [comment]
I've had like 3 separate people say they would resprite it after begging them, and pretty sure none of them ever did it.
