### ISSUE TITLE
Contaminated clothing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7793]
(WEB REPORT BY: blithering REMOTE: 158.69.55.2:7777)

> Revision 06bc0a586f7aa1ffb0b7d8c82428f9bf46051057 
> 
> General description of the issue
> Clothes become contaminated through hardsuits and biosuits. (Specifically security hardsuits and science biosuits)
> 
> What you expected to happen
> No contamination if suit is worn.
> 
> What actually happened
> All items contaminate.
> 
> Steps to reproduce if possible
> Put on hardsuit or biosuit, stand in plasma.

**Comment by Exxion** [comment]
Not a bug, but stupid and idiotic nonetheless.

**Comment by gbasood** [comment]
REMOVE CONTAM
remove contam

**Comment by Kurfursten** [comment]
A poll conducted about a month and a half ago on most frustrating cause of death was more than half (from a list of many choices) "plasmaflood". Just trivia related to this not-bug.

**Comment by Exxion** [comment]
I especially love the fact that, because most outer suits, even space-worthy ones, don't protect from contamination but DO protect from direct plasma damage, you can just take off your jumpsuit, shoes, and gloves and you're magically fine in any space suit.

**Comment by gbasood** [comment]
Honestly, plasma floods are bullshit enough. We don't need to encourage them by making them even better with contamination.

**Comment by ghost** [comment]
@Exxion I found a proc, /mob/living/carbon/human/proc/pl_suit_protected() which indicates this actually isn't intended behaviour.

**Comment by Exxion** [comment]
I noticed after posting that that you still get the "Your skin burns!" message, but take no damage
