### ISSUE TITLE
Jukebox playlists prevent server from starting if host has no internet connection / Please add a config to disable jukeboxes

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7794]
My PC has no internet for a while and I noticed I couldn't host a testing server at all. Took me a while to realize that the issue were jukebox playlists hanging if the serb has no internet connection.
I commented out the playlist generating calls and it not only fixed it, but massively sped up the initialization speed of my listen server. Please add a config for this, holy shit it's so good

Posted from my Nokia N-Gage

**Comment by ghost** [comment]
This config should be off by default. Who tests jukeboxes on a local server, anyway? Same with map renders, honestly.

**Comment by 9600bauds** [comment]
After removing minimap generation, my listen serb boots so fast, the "Machinery started in 1.4 seconds" messages are displayed in system font from resources not loading yet
