### ISSUE TITLE
Auto-Cloner Possible Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7797]
(WEB REPORT BY: gunosaguki REMOTE: 158.69.55.2:7777)
Unsure if the autocloner is meant to be random, assuming so based off the info on the wiki for it. Its supposed to spawn a random mob repeatedly, but of the two times i've found it, both times its been pet slimes

**Comment by AutismSpider** [comment]
Just bad RNG

**Comment by Gunosaguki** [comment]
alright. thats why i did say possible

**Comment by AutismSpider** [comment]
Happy it was pet slimes could get  god damn xenos or god help you space bears form that thing

**Comment by gbasood** [comment]
Not a bug honk
