### ISSUE TITLE
Make sound synthesizer attachable to a signaling device

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7800]
Because we already have radio spam why not sound spam

**Comment by 9600bauds** [comment]
haha look at me I put proximity signaler next to dead monkey in maint. BOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOMBOOM

**Comment by CptWad** [comment]
>"wow this is just like my japanese animes" x 4 times a second

oh god

**Comment by gbasood** [comment]
@CptWad sound synth already has a cooldown so
@9600bauds We can already flood comms with speakers every time someone says something, or with buttbots. I consider sound spam less annoying than comms spam.

**Comment by CptWad** [comment]
The animes sound plays over itself if its played repeatedly. Its gonna be awful
or great
or both

**Comment by FudgePucker** [comment]
:+1:
Needs honk tag.
It wouldn't be as bad as comm spam anyways. :^)

**Comment by gbasood** [comment]
the only time I will use that label and have it be relevant

**Comment by ihadtoregisterforthis** [comment]
Going back in time here
https://gitlab.com/vgstation/vgstation/merge_requests/24

Paging doctor @unid15
