### ISSUE TITLE
It would appear that the on_moved event is fired twice every time you take a step

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7801]
Once before moving whatever it is you're pulling and once after. May or may not apply to things other than playermobs and  being moved in ways other than walking.
Maybe it's intentional, but it's weird.

**Comment by 9600bauds** [comment]
Also, dropped() fires at least twice when dropping something, even when putting it on a table and I couldn't figure out why.

**Comment by Exxion** [comment]
So here's what my testing has so far revealed:
1. on_moved is fired twice every time you take a step or you are pulled by something, and exactly one of these times is before the object you're pulling is moved, if you're pulling something.
2. However, it only fires once if you are locked to something that is being pulled.
3. It fires once when you are put into a locker but zero times when you are taken out.
4. If someone is gripping you by the neck and moves one tile then waits for you to catch up, it does not fire. However, it fires twice (I think) per tile if they keep moving without waiting for you to catch up.

**Comment by gbasood** [comment]
> Called twice every time

Probably called before and after entering a new tile/location.

**Comment by Exxion** [comment]
No, they're both after you enter the new location, but one is before whatever you're pulling enters its new location, at least it appears from my testing.

**Comment by gbasood** [comment]
So if I'm not pulling anything it fires once?

**Comment by Exxion** [comment]
It fires twice anyway, but one of them is before what you were pulling would move if you were pulling something.

**Comment by gbasood** [comment]
Well alright, let's see. The event is invoked in five places in code total:
- /mob/living/proc/Move()
- /atom/movable/proc/forceMove()
- /atom/movable/proc/Move()
- /mob/camera/blob/Move() (twice, one inside an if, one outside)

**Comment by gbasood** [comment]
Okay yeah both mob and obj inherit from /atom/movable
So maybe that's why.
Throw some debug output after /atom/movable fires the event and some other, different output in the mob proc after firing the event see if just walking around triggers it.
