### ISSUE TITLE
Carrying plasma looks retarded.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7802]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e7883dc177180d11b831d26ff615044ed8627dd0
> 
> General description of the issue
> It just looks silly.
> http://puu.sh/mEJvf/e81c88443a.png
> http://puu.sh/mEJwK/c9ae4bbbc8.png
> 
> What you expected to happen
> Nothing silly.
> 
> What actually happened
> Silly spriting.
> 
> Steps to reproduce if possible
> Grab two cans of plasma, I did it as a plasmaman, and face south and then north, you'll see it.

**Comment by Skullyton** [comment]
Yaay placeholder sprites

**Comment by gbasood** [comment]
That is pretty silly.
