### ISSUE TITLE
Building a normal metal chair takes one metal sheet but deconstructing it gives two

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7803]
picnic

**Comment by 9600bauds** [comment]
Ehhhh
If you care enough to painstakingly dupe a stack of sheets from this rather than ask AI to let you into EVA...

**Comment by Exxion** [comment]
Sure, it's not _much_ of a bug, but it is a bug. With a sufficiently loose definition of "bug," anyway.

**Comment by ihadtoregisterforthis** [comment]
Last year things like this were automatic [OH GOD IT'S LOOSE]

**Comment by gbasood** [comment]
This makes it incredibly easy for people like greytiders or cultists in isolation to set up things with only a little bit of starting metal, so it's kinda important. Even if it would take them forever.

**Comment by PJB3005** [comment]
Chair deconstruction is instant and you can build multiple at the same time (as long as there's none on the tile yet).

Definetly does matter.
