### ISSUE TITLE
There is no way to unthrall people

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7804]
>Thrall sec
>Even if the chaplain knows about it, there is nothing he can do, even if the vampire dies.

**Comment by Imagebard** [comment]
Yeah, there should be some way around enthralling. Its overpowered enough as is.

**Comment by gbasood** [comment]
Holy water.

**Comment by CptWad** [comment]
Does it do that?

**Comment by gbasood** [comment]
Not that I'm aware of.

**Comment by CptWad** [comment]
so that was a suggestion. I agree
