### ISSUE TITLE
failing to emag a mommi weird ass bug

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7805]
Lets say you emag a mommi
but the mommi gets away after you get a failed message
that mommi will be able to speak outside of damage control
while also not being emagged (as in red eye MOMMI ROUGE HALP DORMS emagged)
happened on the shuttle, me being the mommi and suddenly realizing that some fucker was emagging me while I was wiggling, got away, but never was told that I was emagged, but could talk.
weird shit

**Comment by CptWad** [comment]
title was bad hold on

**Comment by AutismSpider** [comment]
You get in tiny black text some one trying hack you when this happens.

1st time emag unlocking the cover over and over as they try to emag you.

**Comment by AutismSpider** [comment]
Not only that trying emag a mommi is pain in ass it can fail some how had it fail three times in a row yes the cover was open.
