### ISSUE TITLE
handcuffs and regenerative stasis

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7806]
(WEB REPORT BY: oberoth REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e7883dc177180d11b831d26ff615044ed8627dd0
> 
> General description of the issue
> If you relog while regenerating in a locker while handcuffed, you can use your hands after returning to life despite being handcuffed. The cuffs remain in one hand, cant be removed but you can still use both hands (still unable to fire guns).
> 
> What you expected to happen
> Less lag
> 
> What actually happened
> Was able to use hands despite being cuffed
> 
> Steps to reproduce if possible
> Be a ling, Get sucked off by a vampire, enter stasis when hes also critted you, Get handcuffed and shoved in an o2 closet, return to life, relog.

**Comment by gbasood** [comment]
~~Related to #1705 #4394~~

NEVERMIND

**Comment by PJB3005** [comment]
Nope, neither are related.
