### ISSUE TITLE
Mixed mode cult blood objective bugged

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7807]
I covered 1/2 of the central hallway, all of the bar, all of dorms, all of the fitness room, some maint behind it and some of the hallway between bar and medbay
I only needed 160 tiles covered
The objective never completed and we culted the janitor before he was a problem
also I guess the shuttle was coated in blood too, but the objective never completed.

**Comment by Kurfursten** [comment]
@deitylink

**Comment by DeityLink** [comment]
Wait mixed mode is a thing again? Oh boy.
