### ISSUE TITLE
Nerf adult Dionaea, somewhat.

### ISSUE THREAD

**Issue by SysadminJeroen** [d3athrow/vgstation13#7809]
So I was reading through some code looking to fix some typos or something, and I noticed that no race is breathing carbon dioxide.
What about nerfing the Dionaea's regenerative power a little bit.
Make them able to consume carbon dioxide when it is dark or badly lit, they'll slowly produce pure oxygen from said carbon dioxide.

Edit: Sauce that no race uses CO2: https://github.com/d3athrow/vgstation13/blob/157b46a6dae069337ebd8bf65bc2f756be0cae70/code/_onclick/hud/screen_objects.dm#L369

**Comment by SysadminJeroen** [comment]
[suggestion]

**Comment by Cyadox** [comment]
While it makes sense from a racial point of view, it's practically worthless because the only source of CO2 on the station is from fires, so the only time it'd come in handy is after a fire had died down and the room isn't being scrubbed.

Now before you consider saying 'Well why not just have them do it all the time then', consider this: the only time a fire dies out is when there's no oxygen in the air. You'd make fires last infinitely longer if a Diona was standing in it.

**Comment by SysadminJeroen** [comment]
@Cyadox Could also ask Atmos to make a burn chamber where oxygen + a small amount of plasma is getting injected to, then ignited, and then the rest put in a canister.

**Comment by gbasood** [comment]
Yeah, we'd have to set up atmos shit just to keep the Dionaeaeaeaea alive.
While I like the idea of the plant fuckers actually BEING plants, making them depend on CO2 is a bit much.
It'd be cool if their regenerative abilities were nerfed slightly unless they had CO2 to process though

**Comment by Cyadox** [comment]
@Jeroen52 The problem is that breathing takes into account the atmosphere you stand in without a mask. You'd either have to limit it to mask-only applications (which is silly), or perhaps more like @gbasood is suggesting.

**Comment by SysadminJeroen** [comment]
@gbasood That was my original plan was, not to make it be required or else they'll die, but to make it optional for either regenerative or oxygen reasons.

@Cyadox What about, if you want beter regeneration you grab your (carbon dioxide) internals and put it on?

**Comment by Cyadox** [comment]
@Jeroen52 That wouldn't be too bad. It'd give a use for it at least. I don't even think CO2 has a use.

**Comment by SysadminJeroen** [comment]
@Cyadox Oh wait, I forgot to link to a comment in the sauce code that actually says that there is no use for CO2.
https://github.com/d3athrow/vgstation13/blob/157b46a6dae069337ebd8bf65bc2f756be0cae70/code/_onclick/hud/screen_objects.dm#L369

**Comment by gbasood** [comment]
Oldcode comments

**Comment by SysadminJeroen** [comment]
@gbasood Is it still true?

**Comment by gbasood** [comment]
As far as I'm aware yes.

**Comment by Shadowmech88** [comment]
CO2's current only "use" is being the product of the reaction between oxygen and plasma. In tank transfer bombs, the CO2 created is what contributes to the increased pressure, allowing the bomb to explode.

Once you have the CO2 gas, though, there's nothing else you can do with it.

**Comment by gbasood** [comment]
Actually since @Shadowmech88 mentioned it, CO2 causing Dionae to regenerate might be a problem if they're running around in fires.

**Comment by Exxion** [comment]
Dionae don't regenerate burn damage.

**Comment by SysadminJeroen** [comment]
@gbasood I have read the wiki before posting this and @Exxion is correct.

**Comment by Exxion** [comment]
Also, even if they required CO2 to regenerate, they would still be too strong to brute damage. By my math, a goliath can easily kill a Ripley, but a diona can pretty easily punch a goliath to death and walk away unscathed. (I regularly kill goliaths as a diona with just a pickaxe and their unarmed attack deals like a third the damage of a pickaxe, so it would take a while but is totally possible.)
On the other hand, it takes like three shots from a laser to kill a diona, so maybe that makes up for it. Basically, dionae are absurdly strong against monsters and pretty weak against players with even moderately good equipment.

**Comment by SysadminJeroen** [comment]
@Exxion: A couple days ago there was a rage cage with 3 Dionaea in it constantly attacking eachother with toolboxes for several minutes and other robust crap they could lay their hands on. I don't think that any of them died at all. However any other race that stepped in the cage went into crit very fast.

**Comment by Exxion** [comment]
Yeah, brute damage is worthless against them, but burn damage (like, say, from a welding tool) annihilates them.
A diona can take a full mag of assault rifle ammo to the face and get up ten seconds later but one shot from a laser can put them into dark orange health.

**Comment by SysadminJeroen** [comment]
@Exxion All races have their strengths and weaknesses, I think that it is a fair balance when they are very strong against brute to do something like slowly dying due to lack of light and loads of fire damage + no fire regen.

**Comment by FudgePucker** [comment]
Yea considering everything dionia aren't too op.
Sure they get super regeneration, toxin immunity, and increased punch damage, but they have to take hyperzine or move slower than someone walking in an advance EOD suit with mag boots on, and take much higher burn damage.
Most forms of damage inflicted is burn damage. You egun taser then laser laser laser till well done.

If they really were that overpowered then there would be more round start plantbros

**Comment by Exxion** [comment]
They make incredible miners though due to the fact that all asteroid mobs deal brute

**Comment by SysadminJeroen** [comment]
@Exxion How do they stay alive without the light? Don't they slowly wither without light?

**Comment by Exxion** [comment]
Miners always carry lanterns
Plus the mining helmet has a flashlight on it

**Comment by FudgePucker** [comment]
You still have to crawl slowly to science or medbay for hyperzine though.

Mining borgs are the best miners anyways.
I can get diamonds/all other asteroid mats, get a polar star and spur parts, and kill a goliath, all before the miners can get on their rig suits (I have done it before.)

**Comment by Exxion** [comment]
In one round, I killed two goliaths, two basilisks, and a hivelord with nothing but a pickaxe and never dropped below yellow health while fighting any of them
And once you get the hyperzine you move at lightning speed

**Comment by FudgePucker** [comment]
That takes all the thrill out of the hunt.
Goliaths are easy to kill once you know how to deal with them anyways, just play DDR when the tenticals come up.

**Comment by AutismSpider** [comment]
>Tree people

>over power when you can grab a god damn flare out of the red tool box and put them in crit in five hits Three if its welding tool

Half the time station full of people with E Guns or Adv E Guns will drop in two to three hits Cannon/Caps gun in two
