### ISSUE TITLE
Pretencious Mime Painting

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7817]
![pretencious](https://cloud.githubusercontent.com/assets/3991927/12529646/cd15deac-c184-11e5-9b76-79145ad64825.PNG)

Should be "pretentious."

**Comment by BestName** [comment]
But "discribe" is fine?

**Comment by Shadowmech88** [comment]
I actually didn't notice that.
That should be corrected as well.

**Comment by gbasood** [comment]
I vote we do the opposite and intentionally fuck up the spelling more

**Comment by 9600bauds** [comment]
A solid idea

**Comment by Intigracy** [comment]
Should have been closed by #8909, oops.
