### ISSUE TITLE
"Telekinesis is not tele, when it comes to shocked doors" or "How doors shock when they shouldn't"

### ISSUE THREAD

**Issue by DrLeprikon** [d3athrow/vgstation13#7818]
Attempting to open a shocked door with telekinesis is a sure way to get shocked, even when one is a good distance away, as I've figured out just now. Is this one of them "fee choors" I keep hearing about? Or is it a bug?

**Comment by Imagebard** [comment]
How do you even open a door with telekinesis
Are you throwing your ID at it telepathically ?

**Comment by uazuaz** [comment]
i noticed that, as a MoMMI, i can't interact with doors or other devices at a distance if i'm holding a tool or an item; it seems that interacting at a distance is just the same as interact at an adjacent tile.

**Comment by DrLeprikon** [comment]
Yup, that's what I clumsily attempted to convey in my travesty of a title: the telekinetic interractions differ in no way from the ordinary ones, you can even take items from machines in another room using telekinesis
