### ISSUE TITLE
Mr VALID portable threat detector

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7821]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)

> General description of the issue
> When wrenched down, does not respond to access requirements or toggling the settings on them when clicking them
> 
> What you expected to happen
> Applying ID would lock or unlock its controls, pressing one of the "Turn on" buttons to do something
> 
> What actually happened
> No prompt given to imply that hitting it with your ID does anything, pressing "Turn on" does not turn on the setting given or change anything in the menu to imply that setting is turned on
> 
> Steps to reproduce if possible
> Take a V.A.L.I.D from storage, move it to the front of medical in this case, wrench it down, attempt to apply ID, find that it does not accept ID, click on it for the menu to come up, press a button to "Turn on" a setting, find it doesn't turn on, or at least change in the menu.

**Comment by Exxion** [comment]
Didn't I fix this last year? How'd it break again?

Also it isn't supposed to do anything when you hit it with your ID
You wear an ID with access to use it
But the buttons should definitely work

**Comment by SonixApache** [comment]
I've done a bit of testing. 

**Roundstart** detectors:
- The UI buttons don't do anything -- they don't change the values.
- UI updates when the function values are changed through VV.
- It's functionality to look inside backpacks doesn't seem to work.
- It plays sounds less than half the time
- It appears to get confused and ignore you every now and then, hard to reproduce.
- Cannot be emagged.

For **post-roundstart** detectors, the first two issues disappear, but the rest persist.

Paging doctor @Exxion

**Comment by Exxion** [comment]
Christ.
I'll take a look on Monday.

**Comment by clusterfack** [comment]
Didn't someone redo these recently?

**Comment by Exxion** [comment]
Guess what I forgot to do

**Comment by 9600bauds** [comment]
What did you forget to do?

**Comment by Exxion** [comment]
Great question
I forget

**Comment by Exxion** [comment]
Is this still an issue?

**Comment by Probe1** [comment]
🤷‍♂️

**Comment by SonixApache** [comment]
i'll take a look

**Comment by Exxion** [comment]
I can't reproduce the first or second points in @SonixApache's post, so those were probably fixed at some point. I'm not seeing the fifth, either, but it has a cooldown, so that could potentially be what he meant. Fix incoming for the other three.

**Comment by SonixApache** [comment]
@Exxion the fifth is that cooldown, but also the fact that it will only scan one person at a time.

**Comment by Exxion** [comment]
Ah
I'm pretty sure only scanning one at a time was a bug, and potentially the same bug that was causing it to never play sounds
