### ISSUE TITLE
Cant Implant Animals inside of people

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7826]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> adc2be2af24da969d53d35e8c09ace38c7b0c33e 
> 
> General description of the issue
> Cant implant small animals inside of body
> 
> What you expected to happen
> to be able to put Poly into my skull
> 
> What actually happened
> it didnt work
> 
> Steps to reproduce if possible
> get poly
> try to insert him in a cavity
> it doesnt work

**Comment by Shadowmech88** [comment]
Did you try all the cavities?
I believe most animals require two hands to hold. I'd guess that would make them large enough to fit only in the chest cavity, if anywhere.

**Comment by 9600bauds** [comment]
It's filthy in there.

**Comment by Ephx1** [comment]
I keep my internal organs very clean, thank you.

**Comment by 9600bauds** [comment]
You scoop up Poly. 

You start putting Poly inside the unknown's cranial cavity. 

You put Poly inside the unknown's cranial cavity.
