### ISSUE TITLE
Level 4 Singularity + Lighting Overlays = Massive lag and dead schedulers

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7834]
It appears the Singularity Engine creates a huge amount of lighting overlay updates every processor tick, lagging everything to hell and even bricking the controller if it moves in a straight line through the station

**Comment by Kurfursten** [comment]
Could improve efficiency by disabling any wall light pulled by the singularity. It's not really realistic that a light fixture stays on after being jerked off the wall anyway.

**Comment by FudgePucker** [comment]
> singularity moving in a straight line though the station causing lag

Well I mean its the singularity moving though the station, pulling hundreds of turfs around along with hundreds of objects and causing hundreds of atmospheric changes, every tick.

**Comment by PJB3005** [comment]
Just an FYI but the lighting process isn't gonna cause lag itself, due to `scheck()`

**Comment by gbasood** [comment]
I really don't know that there's much that could be improved on as far as singularity performance goes
Light fixtures could be disassembled into frames when the singularity pulls them, the lightbulbs could break, but @PJB3005 says it's not lighting's fault so

**Comment by clusterfack** [comment]
???

Where is the profile of this

**Comment by clusterfack** [comment]
Here is mine

Self Cpu
![](http://puu.sh/mIlnE/81756a129c.png)

Total Cpu
![](http://puu.sh/mIlpU/18125b51a7.png)

I find no evidence that lighting is contributing anything to the lag.

It is entirely
- zas remaking zones
- our move code being bloated slow shit
- celtpipes
- pipenets/powernet rebuilds (the initial cause of lag early in the stations destruction)

**Comment by ghost** [comment]
This is no longer relevant. And if it is, needs a new issue ticket
