### ISSUE TITLE
Table Parts

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7840]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> I took apart a table and it only gave me 1 metal instead of the 2 needed to make a table
> 
> General description of the issue
> A table held out the metal on me
> 
> What you expected to happen
> More metal
> 
> What actually happened
> It gave me 1 metal
> 
> Steps to reproduce if possible
> Take apart a table and count on your fingers how much metal you get back

**Comment by Zth--** [comment]
I believe this is intended behaviour by old coders

**Comment by ghost** [comment]
It is lame that a sheet just disappears.

I can't think of any balance reasoning behind it aside from added tedium.

**Comment by gbasood** [comment]
I seem to remember that in **old**code, people just used to run around the station and undo all the non-essential tables to get the metal from them. Every round. But we haven't had that problem ever, so

**Comment by Kurfursten** [comment]
Comic was a big proponent of getting back less than you built with (like deconning walls, etc)

**Comment by Exxion** [comment]
Honestly, I don't see the sense in losing material in anything that doesn't require a welder to either construct or deconstruct
Or at least not losing _this much_ material

Also, related to this issue, making a reinforced table takes four rods but deconstructing it gives you one

**Comment by beesil** [comment]
Fixed in #22422
