### ISSUE TITLE
[Feature Request] Having a monkeyed human eat a roburger turn them into mommis instead of borgs

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7841]
Deadchat had an idea that roburgers can turn monkeys into mommis instead of borgs, which is great

**Comment by Imagebard** [comment]
What happens to Feature Requests during a feature freeze
Do they join the ever-increasing amount of "feature requests" backlog that will never be completed?

**Comment by CptWad** [comment]
yep

**Comment by AutismSpider** [comment]
mommi stuff should be its own food item.like of bowl of spaghetti.

Bowl of MoMMI Spaghetti is just pipes/black/grey spaghetti with bits of plasma sticking out of it.

**Comment by FudgePucker** [comment]
@AutismSpider
Recipe could be H/E pipe/ 5 water/ sheet of plasma

**Comment by FudgePucker** [comment]
@AutismSpider
New regent name should just be 'autism' or 'micro machines'

**Comment by Zth--** [comment]
I love spider's idea. If no one takes this one, then I'll do it when FF ends

**Comment by Intigracy** [comment]
close please, spergetti got added for the spergs

**Comment by 9600bauds** [comment]
yeh
