### ISSUE TITLE
Ready up is fuck

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7842]
(WEB REPORT BY: cowboybuttsdrivemenuts REMOTE: 158.69.55.2:7777)
Revision: beef6e87e1be5b38f2f5354170935a7ab23a0f69 

General description of the issue: The last couple rounds I've been readied up at roundstart, preferences set to none for everything except AI. Every time roundstart rolls around, I'm left on the lobby screen with the window saying that I'm still readied up. Pls help.

What you expected to happen:
For the round to start as normal with me actually in game

What actually happened:
I'm left on the lobby screen with the window saying that I'm still readied up.

Steps to reproduce if possible:
Be in lobby screen, job preferences all set to none except AI, all antags enabled except cult, ready up, wait for roundstart.

**Comment by clusterfack** [comment]
Sounds like someone didn't get picked for his role then

**Comment by Exxion** [comment]
Yeah, that
Though maybe you should get a message explaining that

**Comment by clusterfack** [comment]
That sounds like a good idea, I hadn't thought of it before

**Comment by PsiOmegaDelta** [comment]
You may also wish to refresh the lobby screen window for players who are still in the lobby at round start, mainly to make it say "Join Game" instead of "Ready|Unready".

**Comment by Exxion** [comment]
No, this is still relevant
