### ISSUE TITLE
Death Squad does not have access to its own shuttle console

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#7844]
As Deathsquad Commander, I wasn't able to send the death shuttle. Also according to DragonBro it can't be sent back when done even by admins.

I've also heard of this happening to other deathsquads in the past.

**Comment by Shadowmech88** [comment]
I remember someone was working on a big deathsquad/ERT revamp some months ago. Don't remember who.
It was supposed to fix these kinds of problems.

**Comment by SysadminJeroen** [comment]
ERT has the same problem.

**Comment by PJB3005** [comment]
@Shadowmech88 that was @DeityLink

**Comment by DeityLink** [comment]
Deathsquad's shuttle is due for an overhaul. In fact I've already spent quite some time working on one. Maybe I'll even finish it one day.

**Comment by Kurfursten** [comment]
Almost certain this was fixed in Deity's squid overhaul

**Comment by DeityLink** [comment]
Can confirm.
Was fixed in #15480 . Only took me almost 2 years.
