### ISSUE TITLE
Ban valids cannot be secured

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7847]
(WEB REPORT BY: socachaca REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> beef6e87e1be5b38f2f5354170935a7ab23a0f69
> 
> General description of the issue
> I cannot jobban people from mime OR clown. 
> 
> What you expected to happen
> I open the player panel, click the jobban button with the hopes of being able to cuck people from their valid griff roles but i leave disappointed whem both the options to jobban from mime and clown are missing.
> 
> What actually happened
> NO BAN NO JOBBAN MAKE SOCACHACA GO CRAZY
> 
> Steps to reproduce if possible
> Open player panel. Click jobban button. Wonder if you got sight issues for a moment because you can't find mime/clown at first. Sigh in relief that for once the game is in the wrong and is not just you.

**Comment by mrpain666** [comment]
If you had to do it you could probably do it with the web ban page, for now until this is fixed.

**Comment by ghost** [comment]
Coincidentally there is no mime/clown job option on ID console.

**Comment by Kurfursten** [comment]
@Exxion This isn't a thing anymore as we can definitely clown/mime ban now and those jobs do exist on the ID console
