### ISSUE TITLE
Biogenerators are kill

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7849]
Twice I have seen that biogenerators with biomass in them don't actually work. 
Fill them with biomass and they wont print anyting
Rip

**Comment by PJB3005** [comment]
Oh fuck me

**Comment by gbasood** [comment]
@PJB3005 :+1: :+1: :+1: :+1: :+1: :clap: :clap: :circus_tent: :space_invader:

**Comment by CptWad** [comment]
They still dont work mate

**Comment by CptWad** [comment]
Okay they were fixed, don't reopen.
