### ISSUE TITLE
No holopad in HoS or CMO offices

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#7853]
This is on Box.
All the other heads have one, heck even the QM has one.

**Comment by CptWad** [comment]
Theres also a lack of holopads in the security area. I would be great if there was one in range of the wardens office/interrogation

**Comment by gbasood** [comment]
As if the CMO is actually important or a respected head of the station
Why the QM has one is beyond me

**Comment by CptWad** [comment]
Long ago I felt like people were on the fence about the QM being his own head but it never really got traction. He is a *Head* of the Cargo *Department* but not nessisarly a head of staff, worthy to have bridge access and what not. Would make the HoP more useless. Not that the HoP ever keeps an eye on cargo till sec tells him to

**Comment by Zth--** [comment]
Holopads can't be built or deconstructed. I think this is a bigger issue. Remember that even if you know the AI is malf, you can't do shit about them and they are an easy hole to space

**Comment by Ephx1** [comment]
> you can't do shit about them and they are an easy hole to space

Ermm, you mean like deconstructing the floor under them? You can still replace something under a holopad.
