### ISSUE TITLE
Add a ZAS computer

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#7855]
Basically admin spawn only, and used for debugging purposes as well as other things.

It should do a few things, manually change the size of the ZAS room.
Change the variables of the room.
Anything else anyone wants to add.

**Comment by PJB3005** [comment]
Er, I heard there's this thing called VV.

Wow.

**Comment by AlphaBuffalo** [comment]
Eh, it would be good for ingame server glitches that just appear out of nowhere

**Comment by AlphaBuffalo** [comment]
Like having a plasma fire in a box that doesnt spread to the rest of the room

**Comment by PJB3005** [comment]
The issue is, the only people that would have any sort of fucking clue what buttons to press would know what to do in VV too, so it wouldn't matter.

And a computer that needs spawning in is just extremely clunky / fourth wall nuking for admin purposes.

**Comment by AlphaBuffalo** [comment]
Welp, shut it down, close this issue, I can not argue with that logic
