### ISSUE TITLE
Buff wizard

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7856]
Balance/discussion:
Wizards suck
The only time a wizard can win is if hes using non-wizard shit(IE he looted the armory and is robust) or the crew is terrible.
Most spells can be really good but you have to invest points in them now, such as Time stop, where you need to invest 3-4 points for it to be good enough to use, just to have a spell that you can cast every 3 minutes in byond time
Then you are down 3 spells out of five and two spells to be used for say, a mobility and an offensive spell
Most mobility spells are good. Blink is fair, jaunt is a good spell, if you invest two points into it to cast it faster, and teleport may as well not be updated since its not truely worth it as you only ever want to spend one point on mobility. Then theres knock which is underused bus still robust.
For offensive, You have fireball. Which is great for killing yourself. Lightning, which is the current useful offensive spell. Mutate is fun, makes using knock obsolete. Its more balanced than it was before.
So on and so forth
Really there are some solid spells and a good few combinations, but the main issue is that wizards have been getting more expansive spells but not the ability to use them. I see that we could bolster up the amount of spells the wizard can pick.
For Regular wizard rounds, to make them less shit, we could have the wizard start with someting like 10-14 spells, then for ragin mages have those wizards have 8-10.
The exact amount would be up for debate, I dont feel like we lack in diversity in spells as we actually lack in diversity of choice since if you are going to pick a gimmick you are pretty restrained in your possiblities. Someone who wants to put all their points into timestop will end up dead in seconds.

**Comment by Kurfursten** [comment]
I don't know about that. Some spells are still way too good - like the fact that subjugate still works through walls and completely incapacitates someone who isn't ready with an ethyl pill. Statue still lasts 10 minutes and dusts anyone you catch with it. It's seriously dumb how long it lasts and if you statue someone in an airlock you have effectively created a wall there unless people are willing to non-antag murder a crewmate just to valid you. Staff of animation has no actual cap on the number of space carp-tier minions you can have and I have seen wizards ravage an entire crew with that one point skill: sit in the library and build an army of paper, or take over any supply room like medical storage or cargo. There is a lot of robustness to go around.

I think if you want to seriously double (even triple?) the number of spells a wizard gets you need to do away with the non-magical means you mention. Forbid wizards from using guns or something if you want to give them that much of a buff to their spell lists.

And finally, something we can all agree on: someone needs to rework the spellbook to be less clunky, it's a pain to navigate. It would be nice if it had an expandable list like the uplink.

**Comment by Shadowmech88** [comment]
Don't animated objects return to normal on their own after a few minutes?

**Comment by Kurfursten** [comment]
If they do, it's a long number of minutes. I have seen more than one shift where the wizard just keeps retreating to his lair of animated minions to make new ones. The staff recharges pretty fast either way so it's no big hassle. I'd definitely put it up there as one of the strongest choices (next to mutate apprentices)

**Comment by Shadowmech88** [comment]
Not sure if it still works, but you used to be able to use the staff of change on animated objects to create permanent minions, though slimes are the only ones that aren't braindead, I believe.

**Comment by AutismSpider** [comment]
Animated is on a timer so they turn back to normal after like three/five mins

**Comment by Imagebard** [comment]
Form my experience with it the animation staff actually lasts a very short time span and I have to go animate everything again in a few minutes.

**Comment by AutismSpider** [comment]
Animation is bad like force staff.

Like it should be turn into normal spell that works in aoe with 30 sec cool down

Same with force staff turn into normal spell that you charge up for a bigger beam etc

**Comment by TermedClepe** [comment]
Wizard needs a self healing spell. The most likely place to meet a wizard is medbay storage.

**Comment by clusterfack** [comment]
I'll probably do some ideas I have for wizard spells that increase survivability after the freeze

**Comment by Ephx1** [comment]
And since ninja has absolutely zero chance of coming back more stealth spells too.

**Comment by 9600bauds** [comment]
Inb4 wiz gets rejuv and everyone uses it with jaunt

**Comment by FudgePucker** [comment]
Maybe if statue spell is needed along with a few other op spells, and also giving the wizard permanent clumbsy it would be fair to give him more points

**Comment by Kurfursten** [comment]
@9600bauds That's called Vampire

**Comment by gbasood** [comment]
I've wanted to see a wizard run around in people clothes, with an orb of scrying, horsemasking the crew through walls in his spare time.

Actually I think that's 100% possible as it is, hm

**Comment by CptWad** [comment]
@gbasood Id be cool if wizards were given a cirtain spell to start with, say horse mask, and select their other five spells, so long as they were forced to use said spell.
Example new objectives:
>Kill x
>Steal x
>Horse head seven people
>Escape objective

Then the wizard is given his spellbook and the horse head spell.
Could be any spell, though some spells might not really work in that scenario, like Magic missile or time stop. Guess those can be spells you pick to make your objectives easier.

**Comment by clusterfack** [comment]
If I had my way using guns would require a spellpoint. Non raging wizards would get more spell points. You can buy a number if random spells at a small discount. And wizards would have some spells to increase survivability.

**Comment by AutismSpider** [comment]
well you have to recode all the staffs if you do that clusterfack.

staff is sub type of a gun even has power cell in it when you decon them

**Comment by CptWad** [comment]
@clusterfack 
>guns would require a spellpoint.

This is good. Also what autism said is true too, though clowns can use staffs still tho.
>Non raging wizards would get more spell points. 

I want this.
>You can buy a number of random spells at a small discount.

Also good. 2 is a good number but 3 would mean 5 spells get you 15 which is insayain 
>wizards would have some spells to increase survivability.

Just as long as its not vampire-tier then were cool.
Maybe a mend wounds spell that fills the wizard up with blood and stops bleeding but does not directly heal brute damage. Or maybe a straight stoneflesh mage armor spell that allows you to cast damage resistances on yourself for a short time, like a magical bulletproof/ablative vest.

**Comment by FudgePucker** [comment]
Are staffs effected by clumbsy trait?

**Comment by CptWad** [comment]
I dont think so

**Comment by FudgePucker** [comment]
Then there's an easy way to prevent wizards from using guns, also nerfing them a bit.
But more spell points would make up for it.
Just make it so they can't cure it.

**Comment by CptWad** [comment]
>Wizards rushing genetics to use guns

hue
also clumsy trait has a bonus: chance to dodge projectiles.

**Comment by Shadowmech88** [comment]
Staves are children of /obj/item/weapon/gun, and so should inherit its Fire().
Clumsy would cause staves to blow up unless there's a staff-specific exemption coded into gun code somewhere.

**Comment by gbasood** [comment]
I re-opened the old bug issue so that we don't lose the bug you brought up in the sea of suggestions

**Comment by CptWad** [comment]
As such I will now remove the bug part of the issue.

**Comment by Ephx1** [comment]
Invisible man spell that requires no clothes to work.
No weapons able to be used without uncloaking.
Gimme, gimme, gimme.

**Comment by CptWad** [comment]
On the topic of rebalance, Summon guns is notorious for only giving the crew guns then the survivors ignore their antag status till the wizard is lynched.
How bout give the guns to the people who get survivor, that way you can cast more than one summon guns to make a shitton of people tator and incentive to keep their guns (Since there will people left out)

**Comment by Shadowmech88** [comment]
@Ephx1 Even simpler, an invisible spell that only turns your body invisible.
If you wear clothes, they'll just look like floating clothes.

**Comment by Ephx1** [comment]
Yeah that's what I had in mind. Even better with the item sprites showing up on someone invisible, so many shenanigans.

**Comment by CptWad** [comment]
>No clothes
>Invisible
>Run around naked

This might get called out as bad in some circles but the prospect of a wizard walking amongst the crew and never being noticed because he was naked is hilarious

**Comment by Kurfursten** [comment]
@CptWad The survivor message isn't super clear that you're an antag anyway

**Comment by Arthurdentist** [comment]
biggest issue with summon guns is that people don't realise they are antags. Giving the survivors traitor objectives might be a good idea as it would make it more explicit. That shouldn't be a hard thing to throw together either.

I personally think the biggest issue with wizard is the 'round ends on wizard death' rule. In encourages people to secure their valids in order to end the round. There is no point in engaging or doing anything interesting because one welder bomb is going to secure the valids and end the round for good.

**Comment by CptWad** [comment]
>I personally think the biggest issue with wizard is the 'round ends on wizard death' rule. In encourages people to secure their valids in order to end the round. There is no point in engaging or doing anything interesting because one welder bomb is going to secure the valids and end the round for good.

We cant have basic wizard rounds not end with all their death because then they secure valids->extended. But extended where silly shit can happen like in the case of summon guns or staffs of change/animation
I watched one round where it did not end because the wizard just summoned guns.
The wizard quickly died and it turned into extended, only with guns, long story short the shuttle turned into a bloodbath and there were a lot of angry adminhelps by people going "IS X AN ANTAG?" "x JUST SHOT ME!" and other horrible confusion.

**Comment by gbasood** [comment]
We can absolutely change wizard to not end on wiz death. People will be assholes and SECURE THE VALIDS until they realize the change.

Add the change to the changelog and you take care of a good chunk of people who would secure valids

**Comment by Intigracy** [comment]
Why not give wizards bundles of spells that are worth more than 5 points for the bundle, but balanced accordingly. They can still choose individual spells if they like a certain build better, or they can pick a bundle and have slightly more power.

**Comment by Probe1** [comment]
Discussion ran its course.
