### ISSUE TITLE
The admin player panel menu sometimes does not accurately list antags, thus making the banning of antags for doing antag things very possible

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#7864]
-Bomb goes off
-oh shit
-hit F6 and hover over his name
-dont see antag
-bing bong bannu
-use check antagonists later
-he was a fucking antagonist
-OH SHIT

This is entirely possible now that the most important and ROBUST admin menu is now broken. When this is working correctly it will ALWAYS have ANTAGONIST in red font below the name in their place on the menu. Yes we should be in the habit of using check antagonists FIRST but sometimes a round is moving fast, the ahelps are being rapid fired at us, multiple things require our attention at once, and we have to move in a hurry, and we dont think to do that or have time. 

Please fix this, I'd hate to see an antag get accidentally banned for doing antag things.

**Comment by ghost** [comment]
From the copious amounts of logs I read you must the only admin that doesn't spam check antags literally every single round.

**Comment by mrpain666** [comment]
@TermedClepe well when that menu worked, I really didnt need to spam it, but I still use it a lot.

**Comment by gbasood** [comment]
solution:

ANTAG DATUMS THAT NEVER GET DELETED
Stored in a global list, too

**Comment by Intigracy** [comment]
solution:

actually check antagonists or the who menu or the traitor panel

**Comment by mrpain666** [comment]
I've yet to encounter this in a good while so Im just going to close it. Reopen it if you see a need to.
