### ISSUE TITLE
Broken Badmin Secrets buttons

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#7865]
I have not tested all of the buttons, only some of them.

The following buttons, listed in the secrets tab, do not do anything.

Spawn an Immovable rod (the logs say this does something, Im not sure it does do anything though)
Toggle a lights out event
Toggle a wave of PDA spam

That is all for now. I may find more and add them later.

**Comment by CptWad** [comment]
I have not seen the immoveable rod for a LONG time
rip

**Comment by Ephx1** [comment]
I remember when one of those tore straight through the AI core, smacking me directly in my monitor, good times.
This is a top priority feature, just the sudden unstoppable rod tearing through everything is great.

**Comment by ghost** [comment]
Immovable rod either doesn't move (go figure) or deletes itself once it hits something, genuine bug.

Lights out event breaks the lights in a random department, it works it's just usually a bit subtle.

PDA spams are no longer shown during live because they'd spam ghosts

**Comment by clusterfack** [comment]
I'm fixing the immovable rod at the moment

**Comment by mrpain666** [comment]
@Skullyton Last I checked the PDA spam button didnt work at all

**Comment by clusterfack** [comment]
How did you know though

**Comment by mrpain666** [comment]
Its easy.

Have multiple admins adminned up, have them playing doing menial stupid irrelevant shit like assistant or janitor, and have one of them hit the button. Nothing happened.

Granted its been a while since I've tried that, ill try again.

EDIT: Can confirm. Does nothing.

EDIT AGAIN: Ok I guess it DOES do something, just might be a bit of a delay. Does only one message get set out per recipient per button press?

**Comment by 9600bauds** [comment]
Literally all of these work
