### ISSUE TITLE
Mancrowave cannot be deconstructed or moved

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7867]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 158.69.55.2:7777)

> Revision 
> 3dac30468799e03170a3e17e86ac3edd0f3179cd 
> 
> General description of the issue
> Exactly what it sounds like. Screwdrivering the console automatically closes the hatch as soon as it's opened.
> 
> What you expected to happen
> The hatch stays open.
> 
> What actually happened
> It doesn't stay open.
> 
> Steps to reproduce if possible
> Screwdriver on mancrowave.

**Comment by gbasood** [comment]
@DrCelt FFFFFFFF
