### ISSUE TITLE
Any spicy food murders people

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#7869]
Consuming a full unit of the eggplant sushi roll and enchilada has resulted in death from overheating. Have yet to test on other foods involving chili's.

**Comment by AutismSpider** [comment]
Capsaicin Oil 5 to 10 with the old temp code is harmless with this new one its deadly now

**Comment by ghost** [comment]
Whoops!

**Comment by FudgePucker** [comment]
100% tested

**Comment by gbasood** [comment]
@DrCelt :facepunch:

**Comment by 9600bauds** [comment]
*on expected differences resulting from change only
