### ISSUE TITLE
Marble statue kill isnt actually a kill

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7871]
(WEB REPORT BY: h0l3m4k3r REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Turn To Stone statue destruction doesnt count as kill in objective terms
> 
> What you expected to happen
> Gibbed marble statues counted as killed
> 
> Steps to reproduce if possible:
> Turn someone to stone (Kill objective)
> Gib it from marble form with any gun
> Get redtext, even if he is as dead as his head in your backpack

**Comment by ghost** [comment]
Wasn't @Intigracy working on something that fixed this?

**Comment by Intigracy** [comment]
not that I was aware lmao

**Comment by Intigracy** [comment]
it's probably an easy fix I'll let you know

**Comment by ghost** [comment]
Huh. Coulda sworn you were making statues gib into tiny statue pieces instead. Guess that was someone else

**Comment by Intigracy** [comment]
#7310

**Comment by ghost** [comment]
Knew it. This is your bug to fix

**Comment by Intigracy** [comment]
close please, captain probably had a backup or someshit in medbay.

![](https://camo.githubusercontent.com/860622ada609324fcd8b7c90041d4a496acfd9da/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f6b78346f74753235626b64717962762f323031362d30322d31385f31332d32392d34392e706e673f646c3d30)
