### ISSUE TITLE
Permanent handheld talisman for cultists to communicate with

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7876]
- Earned via special sacrifice rune (possibly? not sure)
- Handheld only
- Same usage as communication rune, only it wouldn't go away on use, unlike a paper communication talisman
- Would require knowledge of communication words

Pros: 
- Better cultist coordination
- Another option in place of convert/sacrifice to nar-nar, which encourages more than just CONVERT EVERYONE
- Yet another item that could be used to identify cultists

Cons:
- Better cultist coordination
- Not sure how to implement, don't think that a new three-word rune is the best way to go about it considering that most runes wouldn't require you know ALL the words of another rune

Considering the cost of creating the thing would be at LEAST risking revealing yourself, I think the risk/reward is pretty okay. Cultists having a hard time communicating is somewhat a key part of the mode, but the thing is that any cultist who can get off the main station will never have a communication problem, since they can just research words and write communication runes whenever they want in relative secrecy. A permanent communication item sort of makes up for station-bound cultist's inability to go as undetected as someone who lives on the asteroid/gets EVA stuff and leaves to DJ/hacks into teleporter and goes to DJ

I also think that it sort of makes up for the sacrifice rune being fairly garbage in most cases. I haven't seen a cultist use sacrifice in order to learn runes EVER

**Comment by Shadowmech88** [comment]
> which encourages more than just CONVERT EVERYONE

On the other hand, this is worse for the victim. Instead of getting to play as a cultist now, the cult has incentive to just make them dead.

**Comment by gbasood** [comment]
Honestly, if people used sacrifice or if it were a worthwhile rune, that'd be exactly what they'd have to deal with anyway

Plus they'd all be dead eventually if the cultists win. It's not any worse than what traitors usually aim for.

**Comment by FudgePucker** [comment]
Maybe make it have to be a rune that glows blood red that acts like a server, then you can make talismans to communicate. Can not be hidden, can not be erased by cultists, and only works on a single zlevel (no secret jerk off base on ghetto shuttle for you)

Pros: easy communication
Cons: easily detected, and you can't get rid of evidence, once placed there will be a giant CULT IS ON THE STATION, GO CODE RED SET AI TO NT DEFAULT AND LETS GO GET SUM VALIDS sign it also glows an obvious color that can't be concealed

**Comment by Exxion** [comment]
But Fudge
You can already make communicate talismans without needing a server rune

**Comment by gbasood** [comment]
@Exxion PERMANENT talismans, not one-use

**Comment by Exxion** [comment]
I knew that was what you were saying but for some reason I'm a stupid idiot who didn't think Fudge was saying that

**Comment by ghost** [comment]
Why not just communicate a radio frequency with your talisman, set your headsets to it and you can communicate forever.

**Comment by FudgePucker** [comment]
Because if security gets the frequency you are now speaking all of the identities and actions of cult members into their ears. By the time you realise your communications are compromised you have a baton stuck up your ass.

**Comment by Probe1** [comment]
Cult got updated, a year passed by, and this will happen when you code it.
