### ISSUE TITLE
Holopad repeats names

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#7878]
Holopad should be like this:
"Captain Execute, Holopad received: "AI FUCK YOU""
Instead it's
"Captain Execute Captain Execute, Holopad received: "AI FUCK YOU""

**Comment by clusterfack** [comment]
Is captain execute the name of the theoretical AI here?

**Comment by clusterfack** [comment]
I guess I'd like to know what are the parts of this message

Is it
"[AI Name], Holopad transmitted: "[message]""
?

**Comment by CptWad** [comment]
No its
"Greyshirt Mcgriff Greyshirt Mcgriff, Holopad transmitteed: "halp cap executin me law 1"
AI's name shows up normal

**Comment by clusterfack** [comment]
Are you sure that shouldn't say holopad received then?

The only place I find 'holopad transmitted' in the code is in the AI talking

```
//For holopads only. Usable by AI.
/mob/living/silicon/ai/proc/holopad_talk(var/datum/speech/speech)
	say_testing(src, "[type]/holopad_talk()")
	var/turf/turf = get_turf(src)
	log_say("[key_name(src)] (@[turf.x],[turf.y],[turf.z]) Holopad: [speech.message]")

	speech.message = trim(speech.message)

	if (!speech.message)
		return

	var/obj/machinery/hologram/holopad/T = current
	if(istype(T) && T.hologram && T.master == src)//If there is a hologram and its master is the user.
		T.send_speech(speech, 7, "R")
		to_chat(src, "<i><span class='[speech.render_wrapper_classes()]'>Holopad transmitted, <span class='name'>[real_name]</span> [speech.render_message()]</span></i>")//The AI can "hear" its own message.

	else
		to_chat(src, "No holopad connected.")
```

**Comment by CptWad** [comment]
Oh well "recieved" would be proper then, I was just copying what the OP posted. RIP

**Comment by clusterfack** [comment]
Well it's either the transmitting or receiving, it'd be the AI name if it was transmitting and person name if it was received

**Comment by Ephx1** [comment]
Right right, my bad it's received.

**Comment by clusterfack** [comment]
"easy fix" he says
