### ISSUE TITLE
Manifested ghosts who are manifested after narsie spawn can be nullspaced

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7880]
(WEB REPORT BY: pseudonym REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> af655086f8daa5dc0ecfc034559e608cf9342b8f 
> I have no idea how but okay

**Comment by 9600bauds** [comment]
I am THIS close to making a "Needs Usable Info" tag

**Comment by gbasood** [comment]
The title is pretty descriptive I think
To be more precise it might be caused by Nar'Sie converting a tile that previously contained a manifest ghost rune, and then a construct activating it while a ghost is on top.

**Comment by ihadtoregisterforthis** [comment]
Not a problem anymore
