### ISSUE TITLE
Emergency nitrogen tank attached to transfer valve

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7881]
When attached it looks as if a second transfer valve was attached to it.

**Comment by 9600bauds** [comment]
Out of morbid curiosity, what was an emergency nitrogen tank doing in a tank transfer valve

**Comment by Exxion** [comment]
Probably ruining the tank transfer valve

**Comment by ghost** [comment]
I was doing experiments with using lower capacity tanks combined with high capacity ones, hoping for shitcode making all gas focus inside the smaller after the valve gets opened.

**Comment by 9600bauds** [comment]
A noble endeavor
