### ISSUE TITLE
When making a new area with blueprints, the tiles on the corner edges do not update lighting

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7883]
@PJB3005 might be related to #7291 but specifically the corner edges this time

**Comment by PJB3005** [comment]
Er, isn't the actual issue that those tiles aren't part of the new area?

**Comment by ghost** [comment]
@PJB3005 aren't they? I mean even if they aren't this is still technically correct.

**Comment by clusterfack** [comment]
That's because corner edges aren't counted as part of the room detection because the other two edges constitute an airproof room

**Comment by ghost** [comment]
Fix this.
