### ISSUE TITLE
How to turn snow into wood and wood into metal

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7889]
If I made an educated guess, the first part is because snow barracades are childs of wooden ones

How to do
1. Make a snow barricade
2. Beat it with a welder
3. Magically wood spawns where the snow was

Next for wood to metal
1. Make a wooden wall with wooden girder
1a.This also works with just the wood girder then applying metal making it a metal wall
2. Welder the wall
3. You now have a metal girder under the wall

Snow? More like free metal.

All tested by some nice derelict mommi who was kind enough to ahelp while he was having fun

**Comment by 9600bauds** [comment]
H A R D C O D E

**Comment by Exxion** [comment]
Beauty

**Comment by DrCelt** [comment]
Ahahahhaa 10/0

**Comment by clusterfack** [comment]
Do you test ANY of your celt stuff

**Comment by DrCelt** [comment]
Half of this isn't my fault.

**Comment by PJB3005** [comment]
Pretty sure snow barricades were from before @DrCelt's mess.

**Comment by DrCelt** [comment]
@PJB3005 is right, aye. I intend to change the way snow barricades work later, but that long outdates mr. Technically the bug that IS my fault (wood) Isn't a bug but an oversight as there's no way in the code yet to differentiate between a wood girder wall and a normal girder wall.

**Comment by Zth--** [comment]
snow2diamond when
