### ISSUE TITLE
Hypothermia was a mistake

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7890]
Went out in the cold, got slow, passed out, eventually died. Then realized.

How is one supposed to space walk from perma to safety? It's impossible due to hypothermia.

**Comment by clusterfack** [comment]
Hm, I agree.

Space shouldn't be cold

**Comment by ghost** [comment]
Damned if I do, Damned if I don't

**Comment by Shadowmech88** [comment]
Was there ever an actual counted vote on whether space should be cold or not?
For the record, I also think that space should not be cold.

**Comment by ghost** [comment]
If you want to make space not cold in term of hypothermia, change IS_SPACE_COLD in setup.dm. I can't be arsed dealing with this issue.

**Comment by ihadtoregisterforthis** [comment]
Make space increase the heat loss instead of plain cold.

**Comment by 9600bauds** [comment]
This is an issue I brought up during testing.
Hypothermia does basically nothing until it puts you unconscious and kills you.
By adding practical instacrit as the peak effect of a symptom you've effectively added a second health bar to every spessman, and the health bar is an invisible one that's also rather nuanced and not as interactive as your actual, main health bar.
To be quite frank this is shit my man and it's exactly why radiation needs a re-do

**Comment by ghost** [comment]
@9600bauds that has literally nothing to do with this issue
I can up the effects of hypothermia :^), but my motif when balancing it was I'd rather it be underpowered and buffed over time than overpowered and have to quickly nerf it.

**Comment by 9600bauds** [comment]
The "passed out, eventually died" part spoke to me

**Comment by ghost** [comment]
Hypothermia just changing your can_stand to 0, so you can still crawl when?

Prolonged exposure to the cold start to damage external limbs that aren't robotic a-la frostbite, when?

Extended exposure to said cold causing said damage making said damaged limbs fall off when?

**Comment by ghost** [comment]
@Skullyton when you code it :^)

**Comment by ghost** [comment]
But yeah, I can see myself coding that in the future, aye.

**Comment by Iamgoofball** [comment]
> How is one supposed to space walk from perma to safety?

why is this a problem?

**Comment by ghost** [comment]
@Iamgoofball I believe he is memeing you.

**Comment by Iamgoofball** [comment]
knowing ss13 players I doubt it

**Comment by Imagebard** [comment]
@Iamgoofball

Once again you show why you're a bad player.
You could always escape form perma, there is no reason to change that.

**Comment by Iamgoofball** [comment]
whats the point of perma if you can escape from it

why dont i just kill you and space your body instead of permaing you if there's a chance of escape

**Comment by 9600bauds** [comment]
You see, perma being escapable is the perfect bait
When they try to break out, you have justification to execute them :^)

**Comment by Imagebard** [comment]
>Why don't I just kill all antags and plunge the game into extended

I'd rather you keep quiet

**Comment by Iamgoofball** [comment]
if i have you arrested as a security officer and I've found traitor gear on you

and my choices are
1. put you in a cell you can break out of easily and then come back and kill me/get killed, effectively making it pointless
2. kill you and prevent you from ever breaking the law again this round

what do you think I'll pick

**Comment by Shadowmech88** [comment]
If you always kill traitors instead of using the permabrig, what does it matter whether people can break out of it or not?

**Comment by Killette2** [comment]
You're supposed to try to loosely keep antags in the round for the sake of fun. That is why there are so many modes besides extended. No you don't slap them on the wrist and set them free, but you try and keep an eye on them, if they're in jail do routinely checkups and such.

**Comment by Iamgoofball** [comment]
Time spent doing that is time not stopping assistant shitlery.
