### ISSUE TITLE
Derelict MoMMI can't select name

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7893]
The used to be able to, there were no problems with it and it was changed only because a single person decided so without any sort of discussion.

Now they all have some shitty name with a number.

**Comment by Shadowmech88** [comment]
I agree that name selection should be brought back.

The change was committed without even a proper PR in which people could voice their opinions.
If people really wanted to communicate metainformation to people on the station, there are a lot easier avenues than becoming a MoMMI that can't even leave the Derelict Z-level.

**Comment by ihadtoregisterforthis** [comment]
Why close #6848?

**Comment by 9600bauds** [comment]
I'm on the verge of closing this and reopening the other issue, seeing as this one doesn't have any of the discussion and shittily points fingers in the OP.

**Comment by Shadowmech88** [comment]
I believe the other one was closed due to the belief that its age had caused discussion to stall.

**Comment by ghost** [comment]
Ah yes the need to flex new powers.

**Comment by Ephx1** [comment]
#6601
Although considering Nesquik is gone for now, might as well change it back.

**Comment by 9600bauds** [comment]
Was told to close this in favor of #6848, please don't close issues just to reopen them
