### ISSUE TITLE
New Grilles in medbay Invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7895]
(WEB REPORT BY: gunosaguki REMOTE: 158.69.55.2:7777)
Unsure if this applies anywhere but medbay, but making grilles in medbay made them invisible.

**Comment by 9600bauds** [comment]
??????

**Comment by Exxion** [comment]
I'd bet money that this is actually just that BYOND bug where sprites get fucked up clientside in long rounds

**Comment by ghost** [comment]
[Can't reproduce]

**Comment by Exxion** [comment]
In other words yeah it's just that unfixable BYOND bug that shits up sprites
Once my ghost turned into bats when I faced south

**Comment by DamianX** [comment]
close this

**Comment by Intigracy** [comment]
this is that old issue where getting grilles from pool gave them the incorrect icon

**Comment by Exxion** [comment]
It's not the icon, but close enough

Unless there are multiple grille pooling issues
