### ISSUE TITLE
taking a UI from a changeling husk and injecting makes people "Unknown"

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#7900]
How the fuck do you even take UIs form husks anyways

**Comment by 9600bauds** [comment]
This is a dupe of an already existing issue but I'm too lazy to find it

**Comment by TermedClepe** [comment]
https://github.com/d3athrow/vgstation13/issues/4387

**Comment by Imagebard** [comment]
Well great

**Comment by TermedClepe** [comment]
That feel when the bug will never get fixed because it's a year down the issue list.

**Comment by 9600bauds** [comment]
Fear not my man, it's part of the feachur frees
