### ISSUE TITLE
Greys gaining toxins infinitely until death after exposed to water

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7904]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
I volunteerly exposed myself to water under a shower for a length of time to get me from green to orange health, and after I kept gaining toxins.
Doesn't sound too weird, but the thing is that even after I got all the burns and the small amount of toxins I had removed I kept gaining toxins.
I probably had enough toxins in me to kill me 5 times over that round.
I left medbay 3 times and had to return due to the toxins shit and ate through god knows how much antitox and tricord.
Not sure if this was intended or not.

**Comment by ihadtoregisterforthis** [comment]
We can classify this as LOOSE, pretty sure

**Comment by ghost** [comment]
Sounds like your liver got fucked from toxins and the neanderthals in medbay didn't fix it and just doped you up with anti toxin. Liver damage causes toxin damage which causes more liver damage.

Still better than that one dexalin addicted patient I had constantly suffocating until I figured out a doctor forgot to reconnect his lungs.

**Comment by ghost** [comment]
I think xevonix has played enough medbay to know whether or not his liver's fucked though I may be wrong.

**Comment by PJB3005** [comment]
Doesn't water have a stupidly low metabolism rate?

**Comment by 9600bauds** [comment]
I'm fairly sure it was made 0.2 or something with the specific comment //so it doesn't fuck up greys

**Comment by PJB3005** [comment]
Oh right I did that but I forgot if it was actually merged on GitLab ever.

**Comment by SonixApache** [comment]
showers inject you with a lot of fucking water, maybe there was just still more water in his system?

**Comment by Shadowmech88** [comment]
After exposing a grey to a shower for 10 seconds, he had 150u water in his system. Given the metabolism of water, this is enough to last about 25 minutes.
I think the issue was probably just that he had stockpiled a ton of water.
