### ISSUE TITLE
Grievous Chemmaster Inconsistency which causes me great harm

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7905]
When making pills, you are first asked how many pills to make, and then what to name the pills.

When making bottles, you are first asked what to name the bottles, and then how many bottles to make.

This often results in Clonexadone bottles accidentally named "3".

**Comment by Shadowmech88** [comment]
Since pills are made more often than bottles, I vote that the bottle menu be changed to match the pills menu.

**Comment by 9600bauds** [comment]
If the name of the pill came before the amount, then it wouldn't auto-name itself after the units per pill

**Comment by ihadtoregisterforthis** [comment]
Yes to all
Quality of Life PRs are allowed under the Feature Freeze
