### ISSUE TITLE
Cancelling borg selection

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7908]
(WEB REPORT BY: sluko REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7cfd646417b169241f3a237a3808c6eb6fabea36
> 
> General description of the issue
> When selecting a module and clicking cancel will prevent the borg/player from moving or doing anything.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by SonixApache** [comment]
dupe of #6736, #7001
