### ISSUE TITLE
Splashing Is Little Different From Injecting

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7911]
Splashing someone with a beaker full of reagents appears to be no different from injecting said reagents, with the exception that only half of the beaker's volume gets injected.
This makes sense for some reagents, like acid or mutagen, since their effects would logically be much the same whether injected or splashed on the skin.

With stuff like chloral hydrate or anti-toxin, it doesn't make much sense that applying it to the skin would be almost just as effective as injecting it directly into the bloodstream.

**Comment by 9600bauds** [comment]
Not quite. Splashing someone with a beaker full of reagents would do what you describe, but only if said person doesn't have any gloves or mask or hat OR you're exceptionally lucky.
Main issue here #7786

**Comment by Kurfursten** [comment]
I guess I'll refactor reagent metabolization and permeability this weekend since no one else seems interested.

**Comment by 9600bauds** [comment]
It's mostly a nightmare to think about because how are you going to determine what bodypart did a sprayer puff hit? And there's also the factor that if you don't balance right, people could come up with whatever kind of weird overpowered shit like chloral beakersprays on mouth being the new meta.

**Comment by Shadowmech88** [comment]
> but only if said person doesn't have any gloves or mask or hat

So if they do have those things, nothing gets injected at all? Would splashing someone's torso with polyacid not do anything if they're wearing a hat?

**Comment by Kurfursten** [comment]
@9600bauds Yeah. It's something to think about. Of course, there is already a sort of semirandom damage we have (which part of you got shocked? which part of you was damaged by slamming into the wall? which part of you was burned by that laser that wasn't being shot at you? etc)
