### ISSUE TITLE
There's no way to get "Alpha-Amanatin"

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#7915]
It's a type of toxin you'd expect to find in the fly amanita family, hence the name, but you can't. Even in it's mutation, the destroying angel, you cannot get it there either. Here are the chemical stats of the 2 plants in their basic form (spawned on the test server)

Fly Amanita

This sample contains: 
- nutriment, 1 unit(s)
- amatoxin, 6 unit(s)
- psilocybin, 1 unit(s)

Destroying Angel

This sample contains: 
- nutriment, 1 unit(s)
- amatoxin, 24 unit(s)
- psilocybin, 2 unit(s)

I want muh deadlier version of the toxin, not just more normal toxin.

**Comment by ghost** [comment]
There's no chemical causing bleeding, it could fill that niche.

**Comment by Zth--** [comment]
That's a good idea

**Comment by Killette2** [comment]
What? No I want this chemical, it's already in the code there's just no way to get it. Here is part of it I saved.

---

``` DM
/datum/reagent/amanatin
    name = "Alpha-Amanatin"
    id = "amanatin"
    description = "A deadly poison derived from certain species of Amanita. Sits in the victim's system for a long period of time, then ravages the body."
    color = "#792300" //rgb: 121, 35, 0
    custom_metabolism = 0.01
    data = 1 //Used as a tally
    var/activated = 0
/datum/reagent/amanatin/on_mob_life(var/mob/living/M)
    if(..()) return 1
    if(volume <= 3 && data >= 60 && !activated) //Minimum of 1 minute required to be useful
        activated = 1
    if(activated)
        if(ishuman(M))
            var/mob/living/carbon/human/H = M
            if(prob(8))
                H << "<span class='warning'>You feel violently ill.</span>"
            if(prob(min(data / 10, 100)))
                H.vomit()
            var/datum/organ/internal/liver/L = H.internal_organs_by_name["liver"]
            if(istype(L) && !L.is_broken())
                L.take_damage(data * 0.01, 0)
                H.adjustToxLoss(round(data / 20, 1))
            else
                H.adjustToxLoss(round(data / 10, 1))
                data += 4
    switch(data)
        if(1 to 30)
            M.druggy = max(M.druggy, 10)
        if(540 to 600)  //Start barfing violently after 9 minutes
            if(ishuman(M))
                var/mob/living/carbon/human/H = M
                if(prob(12))
                    H << "<span class='warning'>You feel violently ill.</span>"
                H.adjustToxLoss(0.1)
                if(prob(8))
                    H.vomit()
        if(600 to INFINITY) //Ded in 10 minutes with a minimum of 6 units
            if(ishuman(M))
                var/mob/living/carbon/human/H = M
                if(prob(20))
                    H << "<span class='sinister'>You feel deathly ill.</span>"
                var/datum/organ/internal/liver/L = H.internal_organs_by_name["liver"]
                if(istype(L) && !L.is_broken())
                    L.take_damage(10, 0)
                else
                    H.adjustToxLoss(60)

```

**Comment by Imagebard** [comment]
>It's already in the code

Well that's nifty
>FEATURE REQUEST

REALLY NOW

**Comment by PJB3005** [comment]
@Imagebard he is requesting the ability to get the toxin in-game without admins.

**Comment by 9600bauds** [comment]
This IS a feature request and not an oversight

**Comment by Imagebard** [comment]
>not an oversight

>Chemical coded in but not able to be found in any way other than adminbus even tough it logically should be placed in one of the items that already exist

**Comment by ghost** [comment]
I remember making a comment about it in the thread while I was chewing through Chemistry-Reagents.dm

I didn't expect it wasn't in the game, it seemed like it was literally the one thing you couldn't forget with destroying angels

**Comment by Killette2** [comment]
So why shouldn't Destroying Angels get this chemical? They are basically the upgrade from Fly Amanita

**Comment by Myrios** [comment]
In case anyone is interested the basic effect of Alpha-Amanatin poisoning in real life is to bind to your DNA into a clump and render it useless and unable to replicate. It would be interesting perhaps as an antag poison that has mild effects at first followed by liver failure and your hair falling out but the real sticker would be that upon death you are immediately husked because your DNA is fucked.
What does the Alpha-amatoxin do in the code we have right now?

**Comment by Killette2** [comment]
The toxin does exactly what is stated in the code written above

**Comment by Killette2** [comment]
``` DM
/obj/item/weapon/reagent_containers/food/snacks/grown/mushroom/angel
    name = "destroying angel"
    desc = "<I>Amanita Virosa</I>: Deadly poisonous basidiomycete fungus filled with alpha amatoxins."
    icon_state = "angel"
    potency = 35
    filling_color = "#FFDEDE"
    plantname = "destroyingangel"
```

more code supporting that THIS should be a feature. Source is
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/reagents/reagent_containers/food/snacks/grown.dm

**Comment by ghost** [comment]
Then someone fucked it up real bad

The reagent should be referenced in the seed and the pre-spawned grown good

**Comment by Killette2** [comment]
Why the seed? The seeds almost never have useful examine info.
