### ISSUE TITLE
Make mechanical organs actually do something beyond being made out of rhetorical glass

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7918]
As it is now they basically just sit there and get EMP'd and kill you

**Comment by AutismSpider** [comment]
one emp does like 10 to 20 fucking damage to mech organs all it takes is two emp blast to fuck you over.

**Comment by Shadowmech88** [comment]
N3X15 was working on a big Deus Ex update that would've buffed all manner of mechanical organs, but never finished it.

Personally I think that as a starting point, mechanical limbs should be immune to pain, deal slightly more brute damage, and take slightly less brute damage.

**Comment by ghost** [comment]
If the mechanical parts become superior to flesh parts then they need to be limited at lobby character select screen or we'll have borg station 13.

**Comment by Shadowmech88** [comment]
We could make a separate line of beefed-up mechanical parts that need to be manually attached by the roboticist during the round, and leave the stock lobby parts as they are.

**Comment by Imagebard** [comment]
We could go with that idea in the /vg/station thread where you could order mechanical organs on cargo/roundstart and they had special effects such as EMP Immunity(Or extra EMP weakness).
I need to find the idea poll for it again.

**Comment by Kurfursten** [comment]
I do know at least a few players explicitly use one robotic limb because they can be healed easily (welder + cable coil and no bleeding) which are actually big benefits. I think robotic limbs are in a good place for balance.

Conversely there's not any benefit at all for having robotic internal organs, which is where I think any change should be focused.

**Comment by gbasood** [comment]
> EMP immunity for mechanical organs

nope bad idea
Upgradable eyes would be cool. Organs that you nee to break someone's ribs to replace to upgrade would be cumbersome for this though, you'd just have a line of people waiting for non-life-saving surgery all day.

I think that the standard parts for things like mechanical lungs should just do something more interesting to begin with. For instance, ideas for lungs:
- Works with lower concentrations of essential gasses
- Keeps a small cache of essential gasses for emergencies
- Filters out a certain percentage of harmful toxins

Literally any of those would be a considerable improvement over how they work currently.

For reference, though, #5669 is the Deus Ex PR that got abandoned when N3X left again

**Comment by gbasood** [comment]
Closing in favor of #7627
