### ISSUE TITLE
Lava Map Project Discussion (?)

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7919]
A disclaimer: I will not work on this until the current project, crash landing, has been completed.

A large amount of ground work has been done for any terrestrial map in my previous PRs for the Crash Landing project. Given this, and my understanding of my own code, if there's another terrestrial project, especially one which has extreme temperatures due to my rehaul of heat transfer, I'm more than happy to work on a lava map which should be comparatively less work considering groundwork already having been done.

The purpose of setting up this issue now is that it allows for any discussion about a lava map to take place here and any ideas to be ironed out. 

Here's a post on the thread that I particularly liked, so it can start discussion.
![screenshot_2016-01-28-10-07-52](https://cloud.githubusercontent.com/assets/7193289/12641705/e1ea9f70-c5a8-11e5-811d-f4f820491372.png)

**Comment by ghost** [comment]
@icantthinkofanameritenow Perhaps you may want to help out in this project?

**Comment by Shadowmech88** [comment]
I think the biggest obstacle if we want a "lava" map, and not just a hot volcanic crater map, is that we need to have working flowing liquid, unless the lava is just going to be static turfs that burn you.

**Comment by ghost** [comment]
How do you want your lava?

**Comment by ghost** [comment]
Just burn my skin up fam

**Comment by ghost** [comment]
Not like that, as in do you want a static texture like we already have for "oh shit the floor is lava", or do you want some flow to it, like /turf/unsimulated/floor/lava/flowing, also throw in some directional sprites for it?

**Comment by CptWad** [comment]
So at this point this is only a reminder to yourself
Ill put my mind on it when it can be worked on.
Also seastation when?

**Comment by Ephx1** [comment]
Zuhayr is working on Seastation, @CptWad.

**Comment by CptWad** [comment]
gib link

**Comment by Ephx1** [comment]
http://wetskrell.org/water/index.php
https://github.com/Yonaguni/EuropaStation

Mostly just this, aside from the Patreon

**Comment by Kurfursten** [comment]
I've investigated Europa's public test server. It has interesting trams, water mechanics, and sprites, but that's about it. It's just a pet project now: they should've waited to hype it until after it was closer to done, but I get why they did it. It was a gamble in hopes that the spike of interest would attract more contributors to the project.

**Comment by NigglyWiggly** [comment]
@Ephx1 

> http://wetskrell.org

![](http://puu.sh/mgzfn/4e94655113.png)

**Comment by Ephx1** [comment]
For real.

**Comment by jknpj** [comment]
Dead (and stolen) project.
