### ISSUE TITLE
Getting hungry too fast burns you to death

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7920]
I went from no hunger indicator to starving and started taking burn damage as if on fire.
1. Eat a lot of hyperizine
2. Drink it down with a lot of anti toxin
3. Marvel as you start burning up after a few minutes when you get hungry from it

**Comment by ghost** [comment]
That is hilarious. Also totally my fault.

**Comment by clusterfack** [comment]
I warned you bro. I wanted you about the CALORIES bro

**Comment by ghost** [comment]
To be fair where ELSE is the heat gained from burning calories going to go

**Comment by Killette2** [comment]
Is this hyperthermia code? What have you done celt?

**Comment by Allspice** [comment]
More noticeable with Mutate for whatever that's worth; I started heating up a fair bit after two casts for eyelasers.

**Comment by clusterfack** [comment]
Celt you idiot the energy from the calories is being used to fuel the spell/action not heat the goddamn body

**Comment by Kurfursten** [comment]
Does walking on a treadmill or running while fat also hurt you?

**Comment by 9600bauds** [comment]
I'm gonna be fair and label this as oversight

**Comment by Exxion** [comment]
The body is powered by (essentially) combustion so of course burning calories will heat you up. That said, you should be able to cool off quickly enough to not overheat, and if you do overheat you'd pass out long before you would start burning.

**Comment by ghost** [comment]
@Exxion see, usually you do cool off quickly, I have a somewhat jury-rigged sweat() proc. However, when someone burns calories too quickly in an unexpected manner it's hard to balance.

**Comment by ghost** [comment]
@Kurfursten probably.

**Comment by ghost** [comment]
Wasn't able to reproduce the main issue, strangely enough, but all other problems with burn_calories mentioned in this issue have been amended.

Trace Chemicals Found:
hyperzine (497.21 units)
anti_toxin (282.399 units)
