### ISSUE TITLE
Safes Are Worthless

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7925]
I'm talking about the safes that spawn on the asteroid. They're very tough to crack, and yet there's never anything worthwhile inside them. They should at least have something good, preferably something better than what you'd find just on the floor of a wizard room.

**Comment by Zth--** [comment]
I completely agree with this. The vault should have better stuff while we're on it

**Comment by PJB3005** [comment]
I once spent half an hour attempting to comprehend the code for safes trying to open one (I had a stethoscope!),  only to have Probe tell me on the shuttle it was empty anyways.

**Comment by Shadowmech88** [comment]
I don't agree about the vault. It's only protected by one layer of rwalls.
If it had anything _actually_ useful, people would break into it every shift.

Unless you mean the safe that's in the vault, which I guess would be fine.

**Comment by Zth--** [comment]
Yeah and that's the purpose of the vault. I mean, it's there to be broken into. And that never happens, it's just only one more empty room on the station.
That doesn't mean adding 3 alien artifacts would  be ok, but it should at least have _something_

**Comment by CptWad** [comment]
Deffs safe has an energy axe

**Comment by AutismSpider** [comment]
meta and box have a katana (30 damage what real katanas and claymores hit for) and yellow jump suit. 

Deff is Energy axe and binary radio-key

not sure about taxi

**Comment by 9600bauds** [comment]
The katana is a replica

**Comment by Exxion** [comment]
Energy axe should _really_ be adminbus only
What, 150 damage? One hit to kill, two to be undefibbable. Come on now.

**Comment by 9600bauds** [comment]
150 damage = massive bone fractures and internal bleeding = undefibbable to any medbay except one in an alternate universe where cloners don't exist

**Comment by clusterfack** [comment]
Force =/= damage

**Comment by ghost** [comment]
@Exxion perhaps it's testament to how hard safes are to crack that nobody powergames the deff safe round start. - the cost of cracking it is seen as far more than the benefits of having an energy axe and a binary radio key.
