### ISSUE TITLE
Lung Surgery

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7926]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Lungs dont fix during surgery sometimes
> 
> General description of the issue
> It does not happen every single time
> but when I do surgery on a ruptured lung, I will use the advanced kit, it will make me take off his exosuit, then it will start using it. The bar will go down saying the action was completed, but no text states if I mened the lung tissue or if I ripped something.
> 
> What you expected to happen
>  Not this
> 
> What actually happened
>  This
> 
> Steps to reproduce if possible
>  Surgery on exosuit wearing person with ruptured lung. Dont take off the suit until it tells you it has to be off to operate

**Comment by Exxion** [comment]
Despite sounding similar to #7924, I asked and she specifically said the lungs weren't mechanical

**Comment by 9600bauds** [comment]
It really really really sounds like mechanical lungs, I can't think of any other reason for this very specific behavior other than the "gauze on mechaorgans" bug that caused this very specific behavior

Tempted to chalk this up to user error

**Comment by Exxion** [comment]
Probably just user error, as you said
Even if it isn't, if it shows up again, someone can open a new one. I haven't heard anything about this other than this issue, though, so [shrugging emoticon]
