### ISSUE TITLE
Cant light newspapers on fire

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7927]
Using a lighter on newspapers or putting newspapers in fire does nothing. How else am I to burn this trash?

**Comment by Zth--** [comment]
Does it work with paper? Sounds like a new system has to be made

**Comment by CptWad** [comment]
![1347580062025](https://cloud.githubusercontent.com/assets/3959840/12665810/634a5ed4-c5ef-11e5-94d3-1c51004aa861.jpg)
