### ISSUE TITLE
Flaming B-52 fucking obliterates people

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7932]
One god damn sip will almost overheat you.

**Comment by clusterfack** [comment]
Let me guess, you vomited

**Comment by Exxion** [comment]
No, but I took one sip (not even the first and therefore biggest) and my heat bar almost went into the burn zone.

The guy who took the first sip (maybe a few sips, I'm not sure) had to be dragged to medbay and almost died

**Comment by ghost** [comment]
I'll take a look.

**Comment by Zth--** [comment]
Hilarious
