### ISSUE TITLE
Lots of bugs with diona nymphs and maybe monkeys/low dexterity in general

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7935]
- ~As a Diona Nymph, I was unaffected by light. Low light wouldn't harm me, and light wouldn't heal me.~ c #11025
- ~At some point I got 12 brute damage. I was not able to hear this brute damage for the rest of the entire shift. I stole several first aid kits and stabbed myself with the autoinjectors: My body would metabolize the Doctor's Delight, but I wasn't healing from it.~ #12823
- ~At one point I was shocked by a door and went into instacrit. I somehow REGAINED HEALTH AND GOT BACK TO ORANGE HEALTH. Later I was able to confirm that I was indeed slowly healing from burn damage, AS A DIONA NYMPH~ c #11025
- Intents seemed to not work at all. I tried to disarm someone and it resulted in "You bite X!". Trying to grab someone resulted in no effect.
- ~~Throughout the entire shift, my body temperature was slowly going up and would never go down, I had no ill effect until I was at ONE HUNDRED FUCKING DEGREES CELSIUS at which point I got the wiz subjugate effect. Conveniently enough there was a bottle of frost oil in the Kitchen, swallowing all 30 units of it brought me back to around 31 celsius. @DrCelt~~
- Even though I didn't have the dexterity to do pretty much fucking anything, I was able to perform a head transplant with no issues.
  ![mspaint_2016-01-29_05-46-18](https://cloud.githubusercontent.com/assets/6526157/12671103/2f2e0328-c64c-11e5-940b-2ce0c9986ae3.png)
  I have no reason to believe I couldn't have performed any surgery at that point.
- Couldn't clickdrag people into Medbay machinery. Couldn't clickdrag person onto surgery table (and since grab was bugged I couldn't get them on it at all). Couldn't clickdrag myself into the microwave to fix my 100c internal temp, but using the "Enter Sleeper" verb worked.
- ~For some unknowable fucking reason, clicking a surgery table as a diona nymph lowers your layer and emits the message "The monkey hides under the table!". I was then able to hide under tables by running under them for the rest of the round, much like a mouse. This does not work with any other tables.~
- ~I found an ID and tried to use it in the HoP's console. The end result was that the ID was inserted and immediately I got the usual "You don't have the dexterity to do this!" message. Now the ID was in the console and I didn't have the dexterity to use the "Eject ID" verb. Great. However I was able to get the ID back by unscrewdrivering the monitor.~ fix'd by #12903
- ~I tried to pick up a battering ram, which gave me a message along the lines of "you need both hands free to do this". Even though my hands were free, I couldn't pick it up. Untested with a fireaxe/2handed weapon.~

All of these happened in one single round by the way.

**Comment by ghost** [comment]
What a mess. I'll fix temperature behaviour.

**Comment by AutismSpider** [comment]
other stuff is normal for most monkey mobs they can feed people pills/do surgery but can't  two weapons to heavy etc.

**Comment by 9600bauds** [comment]
Should I make this into many different issues?

**Comment by Shadowmech88** [comment]
The fourth issue no longer exists, as monkeys are limited to help and harm intent.
The sixth issue may or may not be a FEEAATUUREEE, but regardless I think it should go in its own issue: #19998.
I'm not really sure the sixth issue is a bug at all. Monkeys and the children of monkeys are all pretty small, so it kind of makes sense to me that they wouldn't be able to manhandle people in and out of machinery. They're lucky they can drag things.
