### ISSUE TITLE
Speech bubbles from ventcrawling mobs inherit the color of the piping

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7937]
I believe @clusterfack did a fix on this for progress bars.

**Comment by clusterfack** [comment]
Bauds why aren't you on IRC so I can ask you things

**Comment by clusterfack** [comment]
Whats the typepath of speech bubbles

**Comment by clusterfack** [comment]
Er rather where in the code was it, ah well I've found it

**Comment by 9600bauds** [comment]
I'm not in the IRC because I'm in my phone like a normie

**Comment by clusterfack** [comment]
What you don't have andchat installed?

**Comment by 9600bauds** [comment]
Because I am a huge casual
