### ISSUE TITLE
Minor cosmetic BYOND member benefits.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#7945]
At this point, I believe Lummox deserves getting some donations for the amazing work he's put into BYOND (we have exceptions, colour matrices and FUCKING PLANE MASTERS???)

Let's give back to BYOND and add things like a member icon next to somebody's name in OOC, small, not gameplay-affecting stuff like that.

**Comment by ghost** [comment]
t. lummox

**Comment by ghost** [comment]
:-1: 

I don't think we should really have people able to stand out. We don't even have "member icons" for people who donate to pomf. (something I would also oppose, for the record) If there IS to be some bonus to BYOND members, make it more subtle than that.

**Comment by Zth--** [comment]
:-1:

**Comment by Shadowmech88** [comment]
Are you kidding me with this?
:-1:

**Comment by SysadminJeroen** [comment]
:-1:

2016-01-29 22:48 GMT+01:00 Shadowmech88 notifications@github.com:

**Comment by gbasood** [comment]
I'm not against the concept, but all the cosmetic benefits I can think of would be obnoxious within our game at best.

**Comment by NigglyWiggly** [comment]
![1405148582401](https://cloud.githubusercontent.com/assets/9064611/12689473/175aeaf4-c6ab-11e5-9a8f-53ef0cb5042a.png)

**Comment by Iamgoofball** [comment]
:+1:

**Comment by d3athrow** [comment]
long ago there was an idea of giving flavor items to people who donated but the idea is annoying to implement properly and would end up obnoxious anyways.

I vote server donators get this tag next to their name in OOC ![made you look](http://i.imgur.com/EY0sQAA.png)

**Comment by NigglyWiggly** [comment]
> Cockerel Lover

No Pomf this wasn't about people donating to the server
This was about people donating to byond

Also we could just have the sprite of a faggot next to their name for server donators

**Comment by Probe1** [comment]
April 1st isn't for another 2 months you crazy waffle.

**Comment by gbasood** [comment]
> sprite of a faggot

or a chicken
chicken sprites are fine

**Comment by clusterfack** [comment]
OPEN SOURCE WHEN?

**Comment by Kurfursten** [comment]
@probe1 maybe the proposal was just an elaborate ruse to lure you back

**Comment by Imagebard** [comment]
![1453731672370](https://cloud.githubusercontent.com/assets/7571238/12694007/de4582e0-c6fc-11e5-8f3f-48abae129852.jpg)

**Comment by Intigracy** [comment]
:-1:

**Comment by 9600bauds** [comment]
With the scheduler optimizations Lummox is obliging I think we owe him a couple bucks

**Comment by Intigracy** [comment]
Also he broke wall objects, that's a negative to cancel out that positive.

**Comment by PJB3005** [comment]
@intigracy maybe you should report it to the BYOND forums then?

**Comment by Probe1** [comment]
are you going to leave this open until april fools does come

**Comment by Intigracy** [comment]
I'd rather code something that byond members CAN'T use.

**Comment by SonixApache** [comment]
i thought goof was repobanned
