### ISSUE TITLE
GODDAMN IT DUNY

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7947]
You fucked with the step_x step_y didn't you duny
oh god its like were back in 2004 what have you done to your map

**Comment by CptWad** [comment]
@Duny

**Comment by Exxion** [comment]
Wait what are you sure it's just that map?
How would it only happen on one map?

**Comment by CptWad** [comment]
We loaded deff and the movement got fucked
I dunno, probably because deffs step_x step_y was fucked and not the other maps

**Comment by Exxion** [comment]
Right, I forgot about that
Beautiful BYOND shit where something only defaults to on if it's used

**Comment by PJB3005** [comment]
![](http://i.imgur.com/KVxVcTI.png)
Yup

**Comment by CptWad** [comment]
he did do it the absolute madman

**Comment by ihadtoregisterforthis** [comment]
For future reference it's @Duny-, notice the hyphen at the end.
