### ISSUE TITLE
Hallway is now space [deff]

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#7950]
![fuck](https://cloud.githubusercontent.com/assets/3959840/12690589/7e82617e-c699-11e5-95ed-2c0454b1a448.png)
@Duny

**Comment by CptWad** [comment]
fuck
@Duny-

**Comment by Duny-** [comment]
>he doesn't like space
>he plays spessmen 2D

**Comment by CptWad** [comment]
You lucky I didn't pick the image with "Fuck You" written on the square by the chaplain there
