### ISSUE TITLE
The problem with meteor mode

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#7951]
It isn't fun.
Despite the more interesting dynamics of it since the rework (different meteor types, etc) the core problem of meteor mode still exists, and that problem is that it's a "sit and wait for the apocalypse" simulator.
Most players have nothing to do during this other than sit and wait.
Engineers get to try to frantically set up shields. That's it.
Medical gets to try to keep people alive in vain because if the meteors are hitting someone close enough to you that you can retrieve them, the station is already doomed.

There is no interesting gameplay in this mode. Even if players had time to setup defenses beforehand (for instance, if you gave them a fuckton of supply crates and told them "MAKE SOME GRILLES IN SPACE BEFORE THE STORM COMES"), once the meteors show up, the only thing anyone can do is sit and wait.

I don't think this is a problem that will ever change, and I don't think meteors should be a part of secret rotation (or even be a gamemode at all anymore) because of it.

**Comment by clusterfack** [comment]
Because we need antag observers who can direct meteors

**Comment by gbasood** [comment]
That'd only make fun happen for the antags. Crew would still be sit-and-wait-to-die-sim

**Comment by MusgardTiger** [comment]
+1

**Comment by clusterfack** [comment]
@gbasood You could take that same attitude for ANY gamemode with antags

**Comment by gbasood** [comment]
@clusterfack No, because in any other mode, you can go around the station and participate in the shittery. And really, you can even engage the antags and try to kill them.

In Meteor you have to hole up with the other shitters in a confined space and yell at each other until your inevitable death.

**Comment by clusterfack** [comment]
You have a choice bro, the meteors come in waves with a time in between the waves arriving, and it is also announced which direction they are coming from so you can fortify the other directions

**Comment by gbasood** [comment]
Take meteor mode to a poll, then, and ask the players if they think it's fun.

**Comment by mrpain666** [comment]
Add a few antags to the mode with the objectives "sabotage the crew's escape efforts as best as possible, ensure no one escapes alive" with red text if anyone leaves on a pod or the shuttle, and a "die a glorious death" objective. There ya go game mode fixed.

**Comment by gbasood** [comment]
In its current state I don't think antags are in its best interest although I do like the concept.

I really need to get statistics up and running so I can see how the average meteor round ends

**Comment by mrpain666** [comment]
Did it get effected by the meteor buff? I think it did.

I'm seeing the bar open up on box station 5 minutes into the waves.

Maybe nerf the waves that spawn during the mode a bit.

**Comment by vonzippenstein** [comment]
Just can't take the screen shaking. Can it be reduced based on the distance to the player?

**Comment by gbasood** [comment]
Screen shakes are pretty dumb in meteor yeah.

Top thing to do, though, is to reduce the amount of damage ALL meteors do by at least half. Considering that most of the time, the station is a complete wreck before the halfway point in the round, I think that's a good starting point.

Also, antags in meteor is pretty alright.

**Comment by FudgePucker** [comment]
Oh man antags in meatty whores would be awful.
Oh man what do you repair from first? The bombs or the meteor?
Oh boy, plasma floods would be funny, can't excape to space due to meteors.
Buy red space suit and revolver for green text as you murder everyone making grills in space.

**Comment by mrpain666** [comment]
Yeah I tested antags in a meteor mode once and it was fucking awful. Nope. Dont do that ever.

**Comment by clusterfack** [comment]
Meteor blob went great, don't listen to him
