### ISSUE TITLE
The limit to the rate at which you can open and close the Zippo only applies to clicking it and not hotkeys

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7954]
![](http://i.imgur.com/S69FmgY.gif)

**Comment by Zth--** [comment]
(This applies to food and by extension all the items that are usable with hotkeys)

**Comment by Exxion** [comment]
So then is delaynextattack() or whatever it's called just a click thing? How silly.

**Comment by clusterfack** [comment]
It's primarily that attack self has a bug where its supposed to delay but it doesn't ever do so

**Comment by Exxion** [comment]
But it does do so if you click on the sprite to call it
Only hotkeys don't
