### ISSUE TITLE
Atmos pipes weird at one-tile-join location atmospherics entrance

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7955]
(WEB REPORT BY: curver REMOTE: 158.69.55.2:7777)
The problem is that the atmospherics pipes are all in one tile now. That doesn't work well if you want to alter them for whatever reason (e.g. disposals) near the point that mix, distro and disposals pipes occupy one tile.

Picture showing the issue: http://oi67.tinypic.com/nwhoo0.jpg

**Comment by ghost** [comment]
You click the one you want to alter.

**Comment by ihadtoregisterforthis** [comment]
Someone's not thinking with layers, but those three are only for the machines and ports outside atmos anyways.

**Comment by PJB3005** [comment]
Yeah I think the issue here is OP not thinking with layers.

**Comment by gbasood** [comment]
I assumed so but they seemed pretty convinced in the ahelps that something was TERRIBLE about this.

**Comment by clusterfack** [comment]
None of us can find an issue with this so

**Comment by MasterofNothing** [comment]
Well, apparently it's 'new'...

Good to know.
