### ISSUE TITLE
CLICKING DOORS NO LONGER WORKS

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7956]
PANIC

**Comment by 9600bauds** [comment]
This was tested, right?

**Comment by Exxion** [comment]
If you mean the bug, yes. You cannot open or close doors by clicking them. Everyone in the server reported this and it happens for me too.
If you mean whatever PR caused this, then obviously not.

**Comment by 9600bauds** [comment]
@clusterfack picnic

**Comment by Exxion** [comment]
See I thought it was him but last time I blamed him for something I was wrong and I didn't want to test my luck

**Comment by clusterfack** [comment]
Pretty sppooky, I'll check it out
