### ISSUE TITLE
MaMIs Need Attention

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#7957]
![image](https://cloud.githubusercontent.com/assets/3991927/12693366/77182d40-c6cd-11e5-9376-a19945582f62.png)

Pic related, Machine-Man Interfaces. Put a posibrain in them and put it into an organic body, it functions like a brain.

These are in the code, can be spawned by admins and, last I checked, worked at least sometimes.
But there's currently no way to get one without admin intervention, and they're probably buggy.

I'm not sure whether this is a feature request or a bugfix request since MaMIs are in the code, but not in the game proper.

**Comment by CptWad** [comment]
its half bug half feature
Its a cool idea that someone will run with

**Comment by Kurfursten** [comment]
It has a mother-lode of bugs

**Comment by AutismSpider** [comment]
Buggy.So buggy that you can stick a MaMI into MMI to turn into a real brain with no name.

If any thing this should be use to make new mob type when used on a cyborg shell  like a Synth etc

**Comment by ihadtoregisterforthis** [comment]
I heard that left in the open a MaMI will decay and die, just like a biological organ.

**Comment by Shadowmech88** [comment]
It will, and I believe that this is intended.

**Comment by Ephx1** [comment]
@ihadtoregisterforthis 
Kurfurst actually made it so they didn't, but that was reverted.
No one has bothered to fix them as of that revert.
What's terrible about that is that MaMIs had no note for them being dead, I recall a specific round where admins were trying desperately to figure it out while I laughed at them.

**Comment by PJB3005** [comment]
As others have said: bugs.

Also balance since this allows you to revive ghosts to more than just silicons / dionas.

**Comment by Ephx1** [comment]
Do they need balance? Logically they are silicons with two laws
Do no harm, which is pretty vague but you get the picture
And serve the crew and AI

I mean, if someone is getting back into the round just to fuck with people as posibrain they're probably breaking those guidelines. And I recall specifically that they were coded with a message that reminds you of your positronic guidelines when put into a MaMI.

It's kind of like a fleshy golem, that serves everyone instead of a bitter xenobiologist.

Although to expand on that previous thought, people probably won't use posibrains to be anything other than a human now, other than maybe an AI. That's my only issue, why play a robot with no hands that serves people when you can play one that needs no energy WITH hands? So instead of robotics it'll be a human slave factory.

**Comment by PJB3005** [comment]
@Ephx1 brains only have laws inside a silicon body, MMIs or posibrains don't have any laws at all.

**Comment by Ephx1** [comment]
ACKSHUALLY positronic brains DO have laws but not explicitly called laws, you get it in the fucking posibrain text when you're shoved into one.
It flat out fucking says "Do no harm", and "Serve the crew and AI". Goddamn no one seems to know this, not even the coders.

**Comment by PJB3005** [comment]
Well that is true (and I am aware of it), but I'm unsure about how admins count that, as it's definetly a lot less black-on-white.

@nuklearcellphoneg @DrCelt @MustardTiger

**Comment by Ephx1** [comment]
Well they should bother to count it, especially with a Positronic brain in a mech.
I swear every time I see them they always try screaming about how they don't have any laws or similar.

**Comment by PJB3005** [comment]
Well if you do believe that I guess adminhelp is in order.

**Comment by Zth--** [comment]
What if MaMis had mommi's laws? They would be literally autists humans

**Comment by Ephx1** [comment]
Then there would be no real point to them, just a really shitty engineer with no distinguishing features.

**Comment by AutismSpider** [comment]
@Zth--  it be real bad engineer unless it had build in tools+ two hands ti make it better then mommi some how

**Comment by Zth--** [comment]
Maybe without law 3?

**Comment by Ephx1** [comment]
Law 3 is the one about maintaining and improving the station. So a worse aimless MoMMI?

**Comment by ihadtoregisterforthis** [comment]
Less than a floorbot.

**Comment by PJB3005** [comment]
@DrCelt just confirmed in IRC that yes that little popup is basically laws to posibrains, ignoring it = ban.

**Comment by Ephx1** [comment]
Wonderful then. What other balance issues might they have other than no one wanting to be a posibrain for android?

**Comment by ihadtoregisterforthis** [comment]
Other roundabout is slaving them to the AI and the cyborg console.

**Comment by Ephx1** [comment]
No thank you. The one drawback to silicons is their lack of hands. Now enter hands into the equation for a malf/traitor/subverted AI.
It's not pretty.

**Comment by nuklearcellphoneg** [comment]
I love the idea, but not the two law execution. I think it's neato though. 

I think it'd be better to be able to sync them to whatever lawset or AI. The big advantage Humans and Mommis have over Silicons are their hands, and this gives Silicons hands, but...

They don't really have any advantages. Just another way to get back into the round really slightly geared towards being able to metagame, but no more so than most other means.

**Comment by ghost** [comment]
They have to speak with the monospaced font and be able to be remotely blown up if they can be synced up.

**Comment by Shadowmech88** [comment]
Putting it under AI control would be an interesting prospect.
Is there currently anything that an AI or borg cannot do (even in some roundabout way) that would be unbalanced if it suddenly could do via the android?
Operation of AI-disabled equipment doesn't even qualify since an Engineering borg could repair the cut wires anyway.

Additionally it'd add another dynamic to malf by allowing the AI's agents to infiltrate the ranks of the humans, provided they did not speak and give themselves away.

**Comment by AutismSpider** [comment]
Just use the faceless grey/pink skin Synth sprites some one made for this.

**Comment by Ephx1** [comment]
@Shadowmech88 
Imagine it's a malf round.
Now imagine this specific android got a hold of LOTS of Metal, and LOTS of cables and Power Cells. Now they can speed up the malf process quite a bit with some new APCs in a place no one will check.

But let's say the AI wants to get away. The MaMI could then, snag some plasteel, an AI core board, assemble the thing somewhere else. Then card the AI and then put it in the inactive core. Now you have the AI completely moved with almost zero chance of being caught.

**Comment by ghost** [comment]
@ephx1 you can only have one APC per room.

**Comment by Ephx1** [comment]
That doesn't mean there aren't several areas without APCs.

**Comment by ghost** [comment]
Enlighten me

**Comment by Shadowmech88** [comment]
@Ephx1 
Something else I didn't think about, the android would be the only silicon agent capable of constructing more silicons.

Of course, a way around this would be to give them software limitations on what they're allowed to pick up, in the same way that MoMMIs are disallowed from picking up AI modules.

**Comment by Ephx1** [comment]
@DrCelt 
Pop over to the derelict, install a camera or two, add more APCs.
Most of them are already labelled as a room, so that's easily like five more APCs you can get.
Most of maintenance is already labelled so you can add APCs to those.
Or even the rooms on the mining station, there are a few there I think that should be allowed to install some APCs.

@Shadowmech88 
Don't most AIs just pick the borgifier as a default anyways?

**Comment by Shadowmech88** [comment]
It would allow subverted AIs to increase their numbers as well. Malf AIs would be able to do so without needing to spend their points on an autoborger.

**Comment by ihadtoregisterforthis** [comment]
And what about them being not part of the AI network, but with individually assigned lawsets? A different faction but still enslaved to the crew and it's laws.
There needs to be a way to distinguish humans from androids too.
pls yes no gynoids

**Comment by Shadowmech88** [comment]
That could work, but they'd all need to be bound to a single console that's locked behind some security, like in the AI upload.

**Comment by Ephx1** [comment]
> There needs to be a way to distinguish humans from androids too.

Just make them speak with the same typeface that Normal silicons do.
Although Posibrains don't do that for some reason, they speak normally.

**Comment by AutismSpider** [comment]
@Ephx1 That can be done with rouge mommi+rouge Ai combo is rare but it does happen look fishy as shit if the Synth was building apcs in the ass end of no were.

**Comment by Kurfursten** [comment]
@Ephx1 IIRC off-Z level don't count toward the timer. Also Box maint is fully APC'd, if it was missing an APC, doors and lights in maint wouldn't work (all segments of Box maint have at least one light)

**Comment by Ephx1** [comment]
Unless it specifically counts for mining asteroid then I don't think that's true.
And what of all the rooms inbetween? I was certain you could build APCs in those. Oh well if not, I think the one issue about the core is still absolutely terrible, a teleporting rogue AI on a different z-level would just break the game.
Heck, you could put the AI on the center of the Tcomsat every time and win most likely.

**Comment by Shadowmech88** [comment]
It's possible even now for an Engineering borg to drag the core to the Tcomms sat via the teleporter next to the upload.

**Comment by Ephx1** [comment]
Well no, actually it isn't.
Cores can't be pushed, and Borgs cannot click around them to move something while dragging it.
It's why you need a humanoid to retrieve corpses off z-level if you don't have telescience up and running.

I think the best you could do as a borg is get telescience up and running, unwrench the AI and then try and zap it there. But even then I'm not sure if you can telescience an AI core, just like how you can't telescience a mech.

**Comment by Shadowmech88** [comment]
I've literally seen it done before. The core was taken to the telecomms sat and buried in the wall.

Not sure how they did it, but the silicons were able to get the AI to the satellite without any human assistance.

**Comment by Ephx1** [comment]
Then that must have required some very extreme work around. Because you cannot drag things through the teleporter with you.
And I don't think that can compare to simply carding the AI and hopping over. Moving the entire core would be incredibly risky, it's a gigantic monitor.

**Comment by ghost** [comment]
So, what the fuck do?

**Comment by Shadowmech88** [comment]
Fix all the bugs so that it can at least be used for bus, *then* decide how best to implement it into the actual game.

**Comment by ghost** [comment]
I checked, there's no bugs reported

**Comment by Shadowmech88** [comment]
Of course there's no bugs reported, because MaMIs are *unobtainable*.
No one's played with them enough to even discover bugs, but it's almost certain that there are some simply due to the fact that they haven't been widely tested.

**Comment by SonixApache** [comment]
Originally thought MaMIs were those weird robot arms you could slot a brain into. Now that I actually know their wonders, I'll try to find a place to put them so we can actually start using them. They're neat-o.

**Comment by Shadowmech88** [comment]
You were thinking of SAMMIs, which were reverted.
