### ISSUE TITLE
Monkey in slime extractor makes a bucket.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7958]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2ed979bd5ad42f9522243562bd1f1cded0f45329
> 
> General description of the issue
> Monkey in slime extractor makes a bucket.
> 
> What you expected to happen
> Being able to eject it, or it getting ejected.
> 
> What actually happened
> A bucket was made.
> 
> Steps to reproduce if possible
> Put a dead monkey in the slime extractor.

**Comment by 9600bauds** [comment]
Yeah, it's a bucket of blood. 100% intended

**Comment by clusterfack** [comment]
Why is everyone so bothered by this? There's been past issues about the same thing

**Comment by SysadminJeroen** [comment]
@9600bauds A bucket of blood? I didn't notice the blood.
Probably didn't inspect it correctly and thought that it was empty.

**Comment by SysadminJeroen** [comment]
Oh yeah, just tested it and just noticed.
I should have inspected it before opening this issue.
You can close it.

**Comment by Shadowmech88** [comment]
@Jeroen52 You're able to close issues yourself if you were the one who made them, you know.

**Comment by SysadminJeroen** [comment]
I used the ingame bug reporting tool, can't close it.

2016-01-30 5:16 GMT+01:00 Shadowmech88 notifications@github.com:
