### ISSUE TITLE
[Taxi] Bar maint door is the worst fucking door ever fucking conceived

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7962]
Who has access to the door: Everyone with maint access
Who doesn't have maint access: The bartender
This means that anyone on the station except scientists can just walk behind the bar and steal all the bartender's shit, while the door doesn't benefit the bartender in any way

**Comment by Kurfursten** [comment]
@xpcybic

**Comment by xpcybic** [comment]
I was literally observing Yahir as he showed you this
So yeah I saw, it'll be in with the next batch of fixes
