### ISSUE TITLE
What the fuck even happened to glide speed?

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#7963]
Around the time hypothermia was merged, glide speeds got even stupider than they were. When you push someone by bumping them on an intent other than help, they glide at a ludicrously slow rate. Drifting through space is even choppier than it used to be. There's some other stuff, but i can't remember it off the top of my head.

**Comment by PJB3005** [comment]
Pretty sure glide speed gets updated when somebody moves, and things like being pushed don't reset it.

Welcome to mob code.

**Comment by clusterfack** [comment]
Not sure what you mean

This code has always controlled glide_size for months
```
	glide_size = Ceiling(32 / move_delay * world.tick_lag) - 1 //We always split up movements into cardinals for issues with diagonal movements.
```
and it's in atom/movable/move like it's always been

**Comment by PJB3005** [comment]
Oh, I thought it was like that.

**Comment by Exxion** [comment]
Pushing people wasn't wacky like that before a short while ago though
Now it is
It's a minor issue at worst but it's really weird

**Comment by ghost** [comment]
Still a problem?

**Comment by DamianX** [comment]
Fixed
mostly
