### ISSUE TITLE
Toxin damage on joining

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7966]
(WEB REPORT BY: jeanvoerman REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2ed979bd5ad42f9522243562bd1f1cded0f45329
> 
> General description of the issue
> Joined game with toxin damage
> 
> What you expected to happen
> Not taking any damage?
> 
> What actually happened
> I joined the game with 3.63768toxin damage. I was a Vox so "Probably huffed some oxygen before my equipment was generated"
> 
> Steps to reproduce if possible
> Joining game as Vox

**Comment by Exxion** [comment]
I've had this happen at least once. It isn't very common, but it definitely happens occasionally. No idea what causes it.

**Comment by gbasood** [comment]
I don't know what to do to fix this, really. Issue with equipment not generating fast enough, not lungcode

**Comment by Shadowmech88** [comment]
Given the age of the report, how uncommon and difficult to test it was even then, the fact that it only affects vox, and how minor the effects are, I think we can close this. If it still exists, someone will report it again.
