### ISSUE TITLE
Injecting plasma into blue slime does not give frost oil

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7968]
(WEB REPORT BY: falafox REMOTE: 158.69.55.2:7777)

> Revision 2ed979bd5ad42f9522243562bd1f1cded0f45329 
> 
> General description of the issue
> Injecting plasma into the blue slime does not give frost oil, as stated in the wiki, it should
> 
> What you expected to happen
> to get frost oil by injecting plasma
> 
> What actually happened
> jack SHIT, the extract became used and nothing happened
> 
> Steps to reproduce if possible
> 1. Get blue slime core
> 2. Inject plasma into it
> 3. ????
> 4. Nothing!

**Comment by Gunosaguki** [comment]
You have to draw it with syringe

**Comment by 9600bauds** [comment]
Tested and works
![dreamseeker_2016-02-01_01-29-31](https://cloud.githubusercontent.com/assets/6526157/12708833/44b09894-c883-11e5-9f1d-caedbdcd11cb.png)
