### ISSUE TITLE
Power Sink causes constant light flickering = massassassive lag

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#7969]
Not sure if this is intended behavior but the previous times I've experienced a power sink, it just kept the station dark rather than flicker the lights constantly.
Unfortunately can't comment on what the state of power was at the time, maybe we had 20MW wired to grid and that was the cause.

**Comment by PJB3005** [comment]
Light flickering shouldn't be causing actual lag, due to `scheck()`.

**Comment by 9600bauds** [comment]
I'm not sure what this fabled scheck() is, what was happening is that the lights would turn on for 2 seconds, then turn off again.
By the time the power sink exploded (for reference, this was Meta and the sink was placed in Virology, apparently), every single light in Medbay was burnt out and it was absolute hell the entire time.

**Comment by Exxion** [comment]
Also it burns out a good half the lights on the station because shit fuck damn light burn out code is gimmicky

**Comment by clusterfack** [comment]
This is the one @dylanstrategie rewrote right? Or am I thinknig of the singularity beacon

**Comment by Exxion** [comment]
He rewrote the beacon

**Comment by ihadtoregisterforthis** [comment]
Flickering the lights is by my knowledge an antag strategy to do this. I'd test it before discarding it being a bug though.

**Comment by Exxion** [comment]
I guess the extra ass was necessary

**Comment by 9600bauds** [comment]
More ass more good
