### ISSUE TITLE
Lights on Vox Raider Ship

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7971]
(WEB REPORT BY: publicenemymaipai REMOTE: 158.69.55.2:7777)
Ghosts can turn off the lights on the Vox Raider ship, but there is no way for ghosts or vox to turn the lights back on. So once a ghost clicks on the light it's off forever. Maybe make the lights holy or add a switch to prevent this?

**Comment by Exxion** [comment]
#7560 
#7194

**Comment by 9600bauds** [comment]
Closing in favor of #7560 which has more info.
