### ISSUE TITLE
Box Chem dispensers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7972]
(WEB REPORT BY: amikawaii REMOTE: 158.69.55.2:7777)

> Revision (2ed979bd5ad42f9522243562bd1f1cded0f45329

Chem dispensers on box start at 50 not 100 units, i think this is an issue from when default machines started at 50.

**Comment by ghost** [comment]
Sounds like hardcode. Mapping Chem Dispensers should start at the maximum amount of power

**Comment by clusterfack** [comment]
Fixed by changing the 'mapping' chem dispenser to 100 energy

**Comment by 9600bauds** [comment]
What the fuck I thought for sure that was already done
The bug report said specifically Box too so I thought it was something else

**Comment by 9600bauds** [comment]
Other maps do start with 100 energy
I think this is specifically a Box issue

**Comment by PJB3005** [comment]
`"bsR" = (/obj/machinery/chem_dispenser/mapping{energy = 50; max_energy = 50},/turf/simulated/floor{icon_state = "white"},/area/medical/chemistry)`

Technically intended but shit design either way.

**Comment by 9600bauds** [comment]
What the actual fuck?
