### ISSUE TITLE
You can VERY easily metagame Malf AIs by checking if 'emagged APCs are locked'

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7973]
Emags short the APC lock, this means the APC can't lock anymore

For some inexplicable reason, hacking an APC doesn't do the same thing

This means that if you happen upon an emagged APC that is also locked, the AI is Malf

I would also wager that you can check further if the AI is trying to be crafty by trying to lock the APC. It would only work with hacked APCs

**Comment by 9600bauds** [comment]
This is 100% intended. The AI is hacking the APC, the Emag is just breaking it.

**Comment by ghost** [comment]
I doubt this is intended, and even if it was it's pretty shitty design

Hacking an APC via network should break it in the same way than hacking it via emag swap realistically

**Comment by 9600bauds** [comment]
How so? When you swipe the Emag you're frying the front cover lock.
An AI can only hack the APC, not physically alter it.
Same goes for emagging an airlock, where you're literally destroying the circuit.

**Comment by ghost** [comment]
In both cases, the electronics card ends up fried, which would fuck up quite a few things

**Comment by 9600bauds** [comment]
My understanding of Malf is that it's taking over the station systems, not fucking frying the electronics.

**Comment by ghost** [comment]
Right. Honestly, it would be better if Malf AI hacking destroyed the cover lock for two reasons : 
- This prevents metagaming completely and forces players to use their brain
- Keeping the APC locked has no practical use ever

**Comment by 9600bauds** [comment]
Maybe the AI player should use their brain when hacking APCs, because blue APCs are meant to be the thing it has to keep hidden.

**Comment by LordMyroc** [comment]
I thought the entire point behind emags bluescreening APCs were so that someone seeing a blue APC doesn't instantly give away the roundtype.

**Comment by 9600bauds** [comment]
You can still use emagged APCs for mass panic, take a picture of the APC and spread it around, people will take it 100% for granted. I've done this as Assistant and NOBODY asked to see it for themselves, just armed up against the malf AI. Besides, not everyone knows about the cover lock thing.

**Comment by sonime** [comment]
Pretty sure that emagging an APC and making it go blue serves a similar purpose to snagging the library computer and making it spit out a time: it's meant for misdirection and mass panic, and to draw attention away from the traitor.

Maybe the bluescreened APC was a thing before the Malf game mode was added. But right now, over time, bluescreening an APC serves to make players think the AI is malf. And the cover lock not being broken serves as an idiot filter, I guess.

Either way, it's not a bug and is the result of emergent behavior, I guess.

**Comment by 9600bauds** [comment]
Speaking of that, I've tried to emag the library computer and I could never get a tome, is that broken or is it just a myth?

**Comment by sonime** [comment]
Must be broken, I've done it before.

**Comment by Kurfursten** [comment]
@9600bauds It does work, I've done it

**Comment by ghost** [comment]
AI can permanently unlock hacked APCs.

And it's not metagaming since everyone on station has knowledge of antag abilities and items.

> bay
