### ISSUE TITLE
Virology

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7974]
(WEB REPORT BY: kolith REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!) 
> 2ed979bd5ad42f9522243562bd1f1cded0f45329 
> 
> General description of the issue

Pathogenic Incubator buttons stopped working

> What you expected to happen
> the buttons to work
> 
> What actually happened
> the buttons stopped working
> 
> Steps to reproduce if possible
> I was operating normally, but it just stopped

**Comment by 9600bauds** [comment]
Maybe the power to equipment cut out?

**Comment by clusterfack** [comment]
Shitty bug report is shitty, come on you fucks we made it impossibly easy to report bugs you think saying 'not working' is a bug report?
