### ISSUE TITLE
Randomly dissapearing virus sample

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7975]
(WEB REPORT BY: lavoss REMOTE: 158.69.55.2:7777)
Analyzer ate my virus earlier today randomly after scanning it, gave me the paper and I remember it had the cockroach thing

**Comment by despotate** [comment]
- This has never happened to me or anyone I know, and I've played a shit ton of virologist
- I've gone through all of virus2 and nothing indicates the scanner would ever "eat" a virus
- This person probably picked up the virus and accidentally loaded it back into the scanner, and doesn't realize that it stores the dishes. There are a lot of people who think that the analyzer's only function is to spit out the dish and paper after a few seconds.
