### ISSUE TITLE
Moving Sleepers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7983]
(WEB REPORT BY: tnepr REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> You can unwrench the sleeper to move it to a new location, but you can't move the sleeper console which is dumb
> 
> What you expected to happen
> Use a tool to un-anchor the sleeper console and move it to a new location
> 
> What actually happened
> Can't use any tools at all on the sleeper console
> 
> Steps to reproduce if possible
> 1. Try to move the sleeper console
> 2. Be unable to do anything

**Comment by 9600bauds** [comment]
magix

**Comment by CptWad** [comment]
fun fact: You can also use the console from a distance, meaning you can make mobile sleeper units if someone else mans the console while you drag it to patients
I say fix that and make a seperate machine like that, which can be made via mechanics or rnd

**Comment by Exxion** [comment]
Or just make stoxin2 actually obtainable and you wouldn't need field sleepers

**Comment by 9600bauds** [comment]
![dreamseeker_2016-12-17_03-35-47](https://cloud.githubusercontent.com/assets/6526157/21284965/ea0ce8ba-c409-11e6-840d-9116b0092cd7.png)

**Comment by DamianX** [comment]
fixed by removing the sleeper console
