### ISSUE TITLE
Make AMEs deconstructable

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#7984]
Basically, prevent this 
![scrnshot1](https://cloud.githubusercontent.com/assets/5650556/12700002/79e84cf8-c79f-11e5-9df8-c060f298667d.png)
I was thinking about just making it so you can unwrench the control unit which would destroy all the reactor parts.

**Comment by Shadowmech88** [comment]
This exact thing was a problem a couple of weeks ago and I could've sworn someone fixed it.

**Comment by ihadtoregisterforthis** [comment]
![the gray blob](https://cloud.githubusercontent.com/assets/13305885/12700030/f58550d4-c7b0-11e5-9d28-fd03b841f328.png)

**Comment by AlphaBuffalo** [comment]
atleast cargo kept it somewhat out of the way...

**Comment by ghost** [comment]
Pretty sure you can smash through them with fireaxes.

**Comment by Exxion** [comment]
If people in-game are to be believed, the **_only_** way to break them is with polyacid.

**Comment by ghost** [comment]
I've seen a guy smash through with a fireaxe though

**Comment by AlphaBuffalo** [comment]
But not everyone has a fireaxe to destroy it, what if the grey tider stole the one from atmos, and bridge?

**Comment by Shadowmech88** [comment]
You used to be able to make more fireaxes by constructing fireaxe cabinets with plasteel, but I believe it was changed so that the cabinets spawned empty.

If so, where is a person even supposed to get a new fireaxe?

**Comment by AlphaBuffalo** [comment]
I say if the AME is off, and there is no fuel can inside the console, you can unwrench it to break everything

**Comment by Shadowmech88** [comment]
It should turn the AME parts back into the item variant though instead of just making them vanish.

**Comment by AlphaBuffalo** [comment]
What about a decon tool to put everything back in the box? like using metal on an AME part without the console attached will put the reactor part back in a box

**Comment by Exxion** [comment]
Maybe they should also not be totally invincible to meteors

**Comment by PJB3005** [comment]
Make the shielding be deconstructible with a wrench if it's not attached to a control unit.
