### ISSUE TITLE
space pod nullspace

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7985]
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> get sent to nullspace
> 
> What you expected to happen
> 
> What actually happened
> the escape shuttle ran over my space pod and it sent me into nullspace
> 
> Steps to reproduce if possible
> get run over while in a space pod and moving

**Comment by Exxion** [comment]
Oh boy
Looks like this was only fixed for escape pods _in_ shuttles, not escape pods _run over by_ shuttles

**Comment by unid15** [comment]
unrelated to shuttles, most likely pod's Destroy() doesn't eject the pilot
