### ISSUE TITLE
Boxstation SME Chamber Vents

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7986]
(WEB REPORT BY: 2edgy REMOTE: 158.69.55.2:7777)
Revision: 08ca26d11f1552790c713fad9e5d29104c13a0da 
The SME vacuum chamber's vents aren't showing on the Room Air Alarm, so can't turn em off

> What you expected to happen
> 
> > > To actually show on the Room Air Alarm.
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Kurfursten** [comment]
Not a bug, use the AAC like a real engineer. They're on default freq.

**Comment by clusterfack** [comment]
^Hes right you know
