### ISSUE TITLE
Change Emagged Jukeboxes to be permanently on when wrenched down and play Syndie Mix only

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#7987]
It's annoying to go through the trouble of getting your jukebox emagged or spawning one in for a request and just hearing it play the same old boring songs because some turbonerd can't handle the Syndie Mix

**Comment by Ephx1** [comment]
Just make it play Galo Sengen on all sound systems constantly at 101% volume.

**Comment by clusterfack** [comment]
GG baby

**Comment by Exxion** [comment]
But the emagged jukebox IS always on and IS always on the shit playlist
You can't turn it off except by unwrenching it and you can't change the playlist
So you're asking for it to be how it already is

I usually just space it if someone emags it

**Comment by Kurfursten** [comment]
@Exxion No need to space it, you can un-emag it by performing the same hack as usual to toggle syndie mode. I've done this for bartenders twice.

@dylanstrategie Sounds like someone cut the power wire.

**Comment by 9600bauds** [comment]
But jukeboxes are the hardest item in the game to hack, and they can randomly spew horrific deathradiation

**Comment by Kurfursten** [comment]
Clusterfack wanted the hack to be non-trivial so that it wouldn't get hacked every shift

It's not hard once you figure out how, probably more people can do the hack than know how to properly cool an SME

**Comment by CptWad** [comment]
properly is subjective, I see plenty of people who know how to cool it, but few who can make it ICE COLD :snowflake: :snowman: :snowflake:

**Comment by Kurfursten** [comment]
With the way that people complain about setting up the engine on defficiency I have waning faith in our engineering corps.

But in seriousness, no bug here as mentioned, this one can be closed.
