### ISSUE TITLE
suggestion: brains and MMI

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#7998]
if you die and want to be borged, you need to camper robotics hoping that someone uses your brain on a MMI; it would be better if you receive an advice when someone tries to put your brain on a MMI, similar to the advice you get when someone is trying to revive your body with a defibrillator, something like

> Someone is trying to put your brain on a MMI; if you're sure that you want this, re-enter your corpse (Verbs -> Ghost -> Re-enter corpse, or **_click here**_)

the guy who's trying to use your brain on the MMI could receive a message that tell him if the player is still online, something like

> The brain still has a sparkle of life, but fails to connect to the MMI. Should you try again in few seconds?

this, of course, only if the player is still online and observing, and the brain still alive; otherwise, they should receive the usual "the brain is unresponsive" message.

**Comment by Kitfox88** [comment]
As a fucker who both borgs and is borged I support this
