### ISSUE TITLE
Advanced security camera not showin map, only background space

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#7999]
(WEB REPORT BY: ashdemai REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> like the issue title
> 
> What you expected to happen

to see the map of the station

> What actually happened
> only the background is showing
> 
> Steps to reproduce if possible
> took out the normal security circuit board and replaced with an advanced one, with the detective's monitor

**Comment by Gunosaguki** [comment]
it's been this way for a while. please fix ;_;

**Comment by gbasood** [comment]
It showed the map last I checked, but still, related to crew monitor's map image issues

**Comment by Exxion** [comment]
I think it's a client thing
Works for some people but not others
Probably because BYOND's HTML renderer is from, if I'm not mistaken, the end of the bronze age

**Comment by Gunosaguki** [comment]
well regular crew monitor maps work fine for me. just adv sec.

**Comment by Exxion** [comment]
The crew monitor has some of its own bugs, but does seem to be _somewhat_ more reliable than advanced security camera consoles.
