### ISSUE TITLE
Blob needs a more noticeable message for the Blob, might be dropping the message altogether?

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#8009]
-shaft miner blob
-goes out to the roid, doesnt know what the fuck is going on
-no blob notification on his end
-just mines and shit on the roid
-gibs
-no blob spawn
-YEAH THERE WE GO APC DESTROYED MISSION ACCOMPLISHED

Yeah cut miners from blob like you do chaplains from vampire and look into the notification thing please.

**Comment by CptWad** [comment]
:+1: I witnessed it, it was terrible

**Comment by clusterfack** [comment]
"No Blob notification"

He lied. Ban em

**Comment by Kurfursten** [comment]
Miners should probably be barred from Blob anyway just in case they don't notice the message.

**Comment by Probe1** [comment]
That's a bad way of handling it when you can just as easily stop a player who is already infected with blob-itis from popping on any z level but 1

**Comment by mrpain666** [comment]
Any one of those solutions would work, something needs to be done though, it cant be left in its current state.

**Comment by gbasood** [comment]
If a player with blob-itis leaves z-level 1 he should be autogibbed and have a new person get picked to blob.

**Comment by AlphaBuffalo** [comment]
What about blob spawn points? If player gets gibbed on roid while blob he spawns on station at one of the spawn points?

**Comment by gbasood** [comment]
I mean, if they notice it and go off station they obviously didn't want to be blob anyways.
We could prevent more people from not noticing it by adding a sound effect or something?

**Comment by Jalleo** [comment]
This is a byond bug there is another issue like this on TG

**Comment by uazuaz** [comment]
a pop-up window when you're chosen as a special role maybe?
just a little window that tells you

> you're the blob! check the chat window for further informations.

**Comment by Exxion** [comment]
Blob is gone for now, so this is obviously also gone
