### ISSUE TITLE
Cult talisman creation can leave permanent overlays on turf

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8011]
[01:19:05]ADMIN: PM: Gringonius/(Randome Namyo)->Pseudonym/(Nestachack): Just like to say that it happened from inbuing ten talismans in a short period of time

Steps to reproduce: (I think)
- Be cultist
- Make a shitton of talismans quickly on the same turf
- Alt-click/right-click turf to see the leftover /atom/movable/overlays named "cultification" which **NEVER GO AWAY**

Can be used to meta the shit out of a round to confirm cultists if you think

**Comment by 9600bauds** [comment]
Fixed by #12792 maybe?

**Comment by ghost** [comment]
This has indeed been fixed by #12792

**Comment by 9600bauds** [comment]
Then change the autoclose u nerd
