### ISSUE TITLE
Clown curse can be learned twice, and doing so prevents using either instance of the spell

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8012]
Learned clown curse, then ethereal jaunt, then efficient jaunt, then clown curse AGAIN, then lightning.

Clown curse never worked. I tried removing the second instance of clown curse from my spells list. Did not try updating icons, but clicking did NOTHING. The only time it DID do something is when I was incapacitated, and then it just told me I can't cast while incapacitated.

can be reproduced by learning clown curse, NOT CASTING, then learning again
Neither of them will be castable
However if you cast before learning it a second time it will work properly and both spells can be cast independently

**Comment by 9600bauds** [comment]
The rare and majestic properly used [Honk] tag

**Comment by clusterfack** [comment]
>makes prevents


Triggered

**Comment by gbasood** [comment]
I just tested it and couldn't reproduce
Going to wait for runtime logs and pray

**Comment by 9600bauds** [comment]
It's Vox roleplay Clusterfack you just don't understand

**Comment by gbasood** [comment]
RUNTIME LOGS HAVE NOTHING
FUCK

**Comment by gbasood** [comment]
can be reproduced by learning clown curse, NOT CASTING, then learning again
Neither of them will be castable
However if you cast before learning it a second time it will work properly and both spells can be cast independently

**Comment by 9600bauds** [comment]
Literally magic

**Comment by gbasood** [comment]
I'd also like to mention that this bug does not seem to occur with french curse

ALSO apparently if clown curse is not your last spell learned then they both work fine

**Comment by gbasood** [comment]
So in order to fix this, all you'd need to implement is code preventing certain spells from being double-learned.

Or figure out what the fuck is special about clown curse I don't know

**Comment by Shadowmech88** [comment]
Just tested. Learning the clown curse once moved it out of my Unknown Spells list, preventing me from learning it a second time.
