### ISSUE TITLE
"Cultification" leftovers from imbue talisman runes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8013]
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d07d8b303c57f411d9eceea3f857507c89d5bc88 
> 
> General description of the issue
> Several, permanent and invisible entities named "cultification" remaining in a spot after mass use of Imbue Talisman
> 
> What you expected to happen
> Them to go away since I assume they are to be the animation sprites.
> 
> What actually happened
> Several "cultification" entities remained in that tile when examined, invisible but could be an issue against lucky powergames.
> 
> Steps to reproduce if possible
> In my case, place an imbue talisman rune at the bottom-left corner of a dorms room and use it 10 times with papers and 10 other runes such a stun as fast as possible.

**Comment by Shadowmech88** [comment]
Duplicate of #8011.

**Comment by gbasood** [comment]
This report is by the guy who actually noticed the problem, I think it should be kept open until the problem is resolved in case we have trouble reproducing the issue

**Comment by 9600bauds** [comment]
Fixed by #12792 maybe?

**Comment by ghost** [comment]
What bauds said ^
