### ISSUE TITLE
Some Plasmaman suits make you move slower

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8014]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> d07d8b303c57f411d9eceea3f857507c89d5bc88 
> 
> General description of the issue
> im pretty sure the Librarian and some other plasmaman suits make you move slower, in comparison to the assistant suit
> 
> What you expected to happen
> going fast
> 
> What actually happened
> moving slow
> 
> Steps to reproduce if possible
> play plasmaguy
> pick librarian
> pick assistant
> notice the speed difference

**Comment by SysadminJeroen** [comment]
Same with Engineer vs. Atmos.
The Atmos plasmamen hardsuit is slower.

I tried looking in the code a week or two ago but I couldn't find the problem straight away and forgot about it.

**Comment by FudgePucker** [comment]
Atmos plasmaman suit moving slower makes sense, isn't it a full atmos suit? You know, the suit making you immune to pressure? You know, the suit that's fire space proof?

**Comment by SysadminJeroen** [comment]
@FudgePucker Wouldn't the Engineering plasma hardsuit be heavier? if I'm correct it has good protection against radiation.

**Comment by FudgePucker** [comment]
The thing about engineering rig suit is that it only mildly protects you from some radiation, and even then not fully. So you still black out and die from radio transmitters. The atmospheric rigsuit gives you almost total protection from pressure and tempature, you have to be having a tea party in a gas miner chamber to take damage, even then it isn't enough to kill you, you can get into the miner room to do your business in there and get out.

What's better? The suit that in too high radiation, even though it protects you from it, you blackout and die, or the suit that in too high pressure you take damage, you can still find a way to survive.

**Comment by SysadminJeroen** [comment]
@FudgePucker I don't think that plasmamen have any damage from radiation.

**Comment by Imagebard** [comment]
Considering that a Atmospheric Tech job means they often jump into plasmafires to save people, it would make sense if they were faster than normal engineer suits.

**Comment by ihadtoregisterforthis** [comment]
@Jeroen52 Yes they do

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis I'll try it out next time I'm a plasmaman and in Engineering. I'll just stand in front of a Singuloth or the SME and AFK a minute or so.
