### ISSUE TITLE
GUEST_BAN config does not work

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8016]
```
## Uncomment this to stop people connecting to your server without a registered ckey. (i.e. guest-* are all blocked from connecting)
#GUEST_BAN
```

Even though it's commented out, I still can't join my own testing serbian as guest.
This is useful to me because sometimes I need to multikey 2 accounts in the same test serbian at once, which can be accomplished by joining with your ckey, then closing BYOND to join as a guest. The way I accomplish that with this broken config is by just making /proc/IsGuestKey(key) always return 0.

**Comment by ghost** [comment]
> Even though it's commented out, I still can't join

It says uncomment to enable quest ban. So when it's commented out it should enable guest ban, according to the comment above it.

**Comment by 9600bauds** [comment]
No commentu = No guest
Commentu = Guest but actually no guest

The config example starts uncommented, which correctly blocked guest accounts. I commented it out, still won't allow guest accounts.

**Comment by ghost** [comment]
Brain fart here.

**Comment by 9600bauds** [comment]
Happens to the best of us
