### ISSUE TITLE
You can mass-produce teleportation scrolls through the general fabricator

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#8021]
Seems like an oversight.

More accurately, this was the Lesser Scroll of Teleportation (the ones apprentices get with only one use), not sure if it works for default teleport scrolls or not.

**Comment by ghost** [comment]
Ahahahahahahaha

**Comment by Exxion** [comment]
WHO THE FUCK GAVE IT TECH LEVELS

**Comment by ghost** [comment]
@Exxion if it has tech levels does this technically mean it's intended and not a bug? :^)

**Comment by Exxion** [comment]
I don't even fucking know in this case

**Comment by 9600bauds** [comment]
Was probably given tech levels under the assumption that they only worked for R&D, likely predating the device analyzer at all
This my friends is what we call an

**Comment by ghost** [comment]
Reading through the tech code, there was originally gonna be an occult and magic tech branches, probably for cult and wizard rounds/xenoarch.

Scroll of teleporting was probably given tech levels around the time these lost tech branches were conceived

**Comment by SonixApache** [comment]
Magilathe when?

**Comment by gbasood** [comment]
Okay, wait, actually, I need some more details.
Like a step-by-step process on how to go from having a scroll to printing one.
Because I have no idea how mechanics works anymore

**Comment by PJB3005** [comment]
@gbasood:
1. Get scroll
2. Get mechanics scanner
3. Apply mechanics scanner to scroll
4. Go to the mechanics lab
5. Apply mechanics scanner to reverse engine (the thing that looks like a destructive analyzer)
6. Open UI of reverse engine and make it research the scroll blueprint.
7. Print blueprint (nano or not is irrelevant)
8. Apply blueprint to genfab
9. Build scroll in genfab.
