### ISSUE TITLE
Wizards don't understand constructs they create.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8023]
(WEB REPORT BY: yred REMOTE: 158.69.55.2:7777)

> Revision d07d8b303c57f411d9eceea3f857507c89d5bc88 
> 
> General description of the issue
> Wizards don't get cultchat. Constructs only speak cultchat. Wizard can't understand them.
> 
> Steps to reproduce if possible
> Become a wizard, take Artificer, stone and construct a player, ask them to speak.

**Comment by ghost** [comment]
Give wizards cult chat what is the worst that could happen

**Comment by Shadowmech88** [comment]
Wizards start to team up with cultists during mixed mode.
I'd like to see that.

**Comment by ghost** [comment]
I mean it kind of makes sense from a lore point of view. The wizard even has an experimental cult mob and a cultist dagger.

**Comment by Kitfox88** [comment]
But what's the lore reason for wizards having those :^)

**Comment by ghost** [comment]
Summoning research, they decided to see how blood summoning went, accidentally opened a whole into whatever hell Narnar lives in, and Experiment 30b (Is that the name?) was what came from that.

**Comment by Kitfox88** [comment]
Oh, I was just being pedantic I didn't know there was actual lore. Neato.

**Comment by ghost** [comment]
Neither did I, I just pulled that outta nowhere

**Comment by Kitfox88** [comment]
OH SHIT I GOT PLAYED

**Comment by Arthurdentist** [comment]
better solution then giving all wizards cult chat. Taking the construct spell should grant wizzard cult chat. I can probably make a PR for that later today. Spellbook already gives the wizzard X-ray vision when they take the scrying orb so it isn't without precedent either.

**Comment by clusterfack** [comment]
This is ridiculous, constructs constructed this way should already just speak regular galactic common and not construct chat

**Comment by Imagebard** [comment]
@clusterfack

There is no difference between a Cultist Construct and a Wizard Construct.
And I see no problem with giving Wizards cult chat if they choose the construct spell.
