### ISSUE TITLE
Long term idea: abandon heat_protection_temperature in favour of a materials flags for clothing

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8024]
Memo to self, really, again, but this totally needs discussion. How come someone can head into a burning fire of a bajillion degrees and die, but their labcoat remains perfectly intact? I'm of the opinion that instead of having a maximum temperature an article of clothing can protect you from (which barely makes sense anyway), that instead clothing should protect you so long as you are wearing it and is not on fire/ashed up. 

Another note: being able to be set on fire when not wearing any clothes or doused in petrol is silly. That probably needs to have a look at (and to be honest, considering the mess that being set on fire code is, I'd say that needs a look at too)

Also hyperthermia I guess but again long way away, not until crash landing is complete.

**Comment by Shadowmech88** [comment]
I like the idea, however clothes shouldn't protect you from heat just because they're not on fire.
Wool doesn't ignite until it reaches more than 550°C, yet an air temperature of just 120°C is where humans start to enter heatstroke territory.

**Comment by ghost** [comment]
Aye, @Shadowmech88 , I agree. I apologise for not being specific enough; I meant that it would protect from heat in the way thermal conductivity for heat transfer from hypothermia works (ie, it doesn't completely prevent heat transfer, but it's better than being naked)

Also, you sure you're right on that 120°C figure? I'm pretty sure that temperature would kill you stone dead. For reference, ~55°C is death valley temperature, I'm pretty certain.

**Comment by Shadowmech88** [comment]
I'm talking about air temperature, not core temperature.

**Comment by ghost** [comment]
As am I, and 120°C is more than double the heat of the hottest place on earth.

**Comment by Shadowmech88** [comment]
https://en.m.wikipedia.org/wiki/World_Sauna_Championships

And yet a sauna can still manage such a temperature.

**Comment by ghost** [comment]
Christ, humans are stupid.

**Comment by 9600bauds** [comment]
Yeah I have no idea what humans are thinking most of the time

**Comment by FudgePucker** [comment]
Pthhhhh didn't you read the lore? All of the clothing on SS13 is made out of abethos to save money and prevent fires.

**Comment by Exxion** [comment]
> abethos

Did you even try?
