### ISSUE TITLE
Cult Identification

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8029]
(WEB REPORT BY: icefistthunderdick REMOTE: 158.69.55.2:7777)

> Cult Identification
> 
> Cultists not being able to identify other cultists
> 
> I expected a juggernaut to know I was a cultist, he was unable to and smacked my shit up
> 
> I got my shit pushed in until another cultist told him to stop
> 
> I don't know what caused this bug, so I can't say how to reproduce

**Comment by 9600bauds** [comment]
Closing in favor of #6679

**Comment by Exxion** [comment]
Did you... forget to actually close this?

**Comment by 9600bauds** [comment]
Yes.
