### ISSUE TITLE
blindness off center with expanded vision

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8034]
(WEB REPORT BY: vonzippenstein REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a20af6f32a6e4d5c94539281007601db46273ba3
> 
> General description of the issue
> Got the expanded vision genetic enchancement and then later went blind. This normally wouldn't be a problem but the blindness had the center of my vision off the center of my character. It was down one tile and to the left one tile making it not possible to inject myself with the cure for blindess.

**Comment by Exxion** [comment]
I believe that overlay is actually click transparent so you still could inject yourself if you aimed properly but this should definitely still be fixed

I'm pretty sure there is already another issue open for this but it's _old_ and I'm too tired to go looking for it

**Comment by 9600bauds** [comment]
Not sure what to tag

**Comment by ghost** [comment]
The overlay doesn't scale, it's the exact size of the default screen

**Comment by Zth--** [comment]
Fixed in #24454

**Comment by robintime** [comment]
this was not closed for some reason
