### ISSUE TITLE
[Taxi] Scrubber connected to the distro

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#8035]
Are you even trying ?!?!?
http://puu.sh/mTmlN/21a31f9e8e.png

**Comment by PJB3005** [comment]
That's a fucking stacked pipe too!

**Comment by 9600bauds** [comment]
Really, the worst part of this screenshot is the braindead CE

**Comment by Killette2** [comment]
If the CE has to breath it, EVERYONE has to breath it

**Comment by Zth--** [comment]
And that vent is not connected :100: / :100:

**Comment by xpcybic** [comment]
i swear it wasn't me

**Comment by FudgePucker** [comment]
Well look on the bright side, if they are that close to the CEs desk, they can just plasma flood from atmos anyways.
(And you wonder why people would rather play box)
