### ISSUE TITLE
add this spear into the game

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8036]
![mspaint_2016-02-02_16-41-26](https://cloud.githubusercontent.com/assets/6526157/12761946/d85af73a-c9cb-11e5-97ee-c80756fd6dcb.png)
someone sprited it and it's good
we need a non-ghetto spear somewhere for use with the roman shield
![speer](https://cloud.githubusercontent.com/assets/6526157/12761955/ec2a9e0a-c9cb-11e5-8fb7-8d70c9d7837f.png)

**Comment by Imagebard** [comment]
Do you have a in-hand sprite?

**Comment by 9600bauds** [comment]
no

**Comment by Imagebard** [comment]
![1445557891867](https://cloud.githubusercontent.com/assets/7571238/12762224/fdf2f564-c9cc-11e5-9318-c4afb24e2d33.png)

So you're telling me that you want to allow people to prance around with a *invisible* weapon?

**Comment by 9600bauds** [comment]
Well there's already a shitton of invisible in-hands, such as invisible BOMBS and I'm fairly sure a few invisible weapons
If you really must just give it the ghetto spear inhand or something

**Comment by Imagebard** [comment]
>I'm fairly sure a few invisible weapons

Open a issue with all their names later on, please.

**Comment by 9600bauds** [comment]
When I find them again
I'm fairly sure at least a couple surgery items are invis

**Comment by AutismSpider** [comment]
the Drill is invi i think the TTV lacks a in hand same with one tank bombs

**Comment by ghost** [comment]
> Black outlines

**Comment by 9600bauds** [comment]
flashes also don't have in-hands but anyways we have a spear so I don't want this anymore
