### ISSUE TITLE
Lower inventory delay

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8038]
The delay for putting items into backpack / toolbox / any hand held container is too long. It could be halved.

To illustrate: put item into a belt, then try to put another one in it as fast as you can. You'll notice there's an odd period where your clicks don't do anything

**Comment by 9600bauds** [comment]
Yeah this

**Comment by Zth--** [comment]
why nobody ported this one yet https://gitlab.com/vgstation/vgstation/merge_requests/201 ?
(related). Also yes, fuck that delay

**Comment by Exxion** [comment]
Please lower that delay. It makes xenobiology hellish if you actually want to stay organized. Takes forever to load the slime cores into the smartfridge.

**Comment by gbasood** [comment]
:+1:
