### ISSUE TITLE
Robotic limb repair

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8039]
(WEB REPORT BY: herrytheafroheadcrab REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Unable to repair robotic left arm and hand
> 
> General description of the issue
> Hop came in with busted robot left arm and hand trying to repair with welder/cable did not work
> 
> What you expected to happen
> I repair the arm and hand and all is good
> 
> What actually happened
> NOTHING I HAD TO AMPUTATE AND HOP ALMOST DIED OH GOD OH PLZ NO just kidding it took a long time to fix
> 
> Steps to reproduce if possible
> No idea

**Comment by AutismSpider** [comment]
Try nano paste to?

**Comment by clusterfack** [comment]
Oh it just 'didn't work' you say, well that's going to be really helpful

**Comment by 9600bauds** [comment]
Sorry for the dumb question but you never know. You WERE aiming for their limb, right?

**Comment by 9600bauds** [comment]
cannot reproduce!
