### ISSUE TITLE
Ghost/hauting borked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8040]
(WEB REPORT BY: krookodilehunter REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c4b3cce7f6bd1fa854c9ece2f7bc9c90e087a449
> 
> General description of the issue
> Sometimes when you haunt someone, your ghost gets borked and moves slowly (similar to how people move when being dragged now)
> 
> What you expected to happen
> Ghosts always moving normally
> 
> What actually happened
> Broken ghost that doesn't move right until the next round
> 
> Steps to reproduce if possible
> Haunt someone, and then have them go on a disposals ride.

I believe it started happening after hypothermia and junk was introduced!

**Comment by Shadowmech88** [comment]
There was a similar issue regarding ghost following someone that's in a locker.
I believe the problem has to do with attempting to follow someone whose loc isn't a turf.

**Comment by gbasood** [comment]
Yeah there's issues with haunting but the one you're talking about appears to be different.
Ghosts moving slowly isn't the same as haunting breaking from its target

**Comment by ghost** [comment]
I can't think of any particular reason why this would be to do with hypothermia, sorry.

**Comment by jknpj** [comment]
Was fixed a long time ago
