### ISSUE TITLE
Can kick wall-mounted vending machines, which breaks their offset, effectively making them fall to the ground (feature???)

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8042]
kick nanomed in surgery
it fall 2 floor

**Comment by Kurfursten** [comment]
I've seen this, it's mostly because the offset 'animation' doesn't account for the starting pixel offset.

**Comment by Kitfox88** [comment]
nanomed need kick to evoluate?

**Comment by 9600bauds** [comment]
I think animate () got an update that makes this not happen but I have not checked

**Comment by unid15** [comment]
This is fixed
