### ISSUE TITLE
Window focus is almost always fucky

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8044]
Some of the issues are probably not fixable because window shit is largely internally handled by BYOND, I think, but it would be really nice if certain windows would immediately refocus the game after being interacted with. For example, the exosuit interface. Or really any window that doesn't have text entry. But especially the exosuit interface.
The ones that might not be fixable are where focus shifts weirdly on auto-updating windows sometimes. This is very bothersome if they have text entry.

**Comment by clusterfack** [comment]
How do you even code in a way to set focus on different windows? winset()?

**Comment by Exxion** [comment]
`winset((user), (window name), "focus=1")` I think
