### ISSUE TITLE
Alien larva should be forced to evolve into drones if no drone/queen exists

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8045]
Because facehuggers are important

**Comment by 9600bauds** [comment]
I disagree with this on the grounds that a full-scale ayylium invasion is not what you want all of the time. Maybe you want just a single hunter going around, without a blob-scale situation.
Besides, in the initial adminbus spawn where there are multiple larva, nobody could evolve until the designated drone does it first.

**Comment by ghost** [comment]
But playing queen is boring.

**Comment by clusterfack** [comment]
Sounds like you need to git gud then

**Comment by 9600bauds** [comment]
The two are not always related

**Comment by ghost** [comment]
:+1:

**Comment by NigglyWiggly** [comment]
How about no
Forcing people to play a certain way is never a fun idea, and forcing them to take a role they don't want isn't fun either.
Forcing new aliens to be a drone is really heavy handed and unnecessary, especially when, like @9600bauds said, you don't always want a full-scale xeno infestation.

**Comment by ihadtoregisterforthis** [comment]
:-1: for trying to nerf Darwinian fitness

**Comment by clusterfack** [comment]
I also think it is shit when spawned aliens go hunter just to get valids but leading to literally no infestation.

**Comment by 9600bauds** [comment]
Probably try adding just a message unless this happens every single time. I don't think any antags have this level of forced hand-holding, even other team antags.

**Comment by clusterfack** [comment]
Most antags don't reproduce and have mechanics that rely on such

**Comment by 9600bauds** [comment]
I'd argue that antags have lots of ways to mechanically fuck up, I.E. cult and blob. It's up to the players to not fuck up. Plus ayys are kind of adminbus shuttlecaller, the round's antagonization force doesn't hinge on them alone.

**Comment by gbasood** [comment]
Yeah I think that it's fine how it is actually.
