### ISSUE TITLE
Plans to remove/replace the Mancrowave

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8047]
I already spoken out in #7909 why I think the Mancrowave is not a good addition to Medbay. I wanted to wait a little bit and get some more experience with it before raising another point.

I think that, at it's very concept, there's no reason for Medbay to have a Mancrowave. You could divide what it does into three things:
- Unthaw Cryo patients: This is absolutely unnecessary. Cryo has never needed special care before and I'm fully against it. In truth, I think this was only put in place to try to justify the Mancrowave's addition in the first place. If your immulsions ache so bad that you need an explanation for Cryo ejecting people at a convenient temperature, then integrate the thermo-regulation process into Cryo. Make it take 5 seconds to eject someone and display some fancy text about it (which makes more sense to me, personally). But I believe I have already gone to great lengths to explain why special care Cryo is a bad change.
- Wake up people: This is a detail that some people liked a lot. One of the arguments for the Mancrowave was that using it is faster than shaking people up. In truth, though, there's no reason for the Mancrowave to be the thing that does it (in fact, it makes no sense to me). If people want this feature, it could easily be moved into the Sleepers, which are already woefully underused for what they are and are pretty much the same distance away from Cryo anyways.
- Thermo-regulate: This is icky. Besides Hypothermia bugs, which should be fixed soon, there's almost no opportunities where this comes up for Medbay, save for fires or 1000u chili. However, let's take a look at what Medbay already has: Cryo would perfectly fine for cooling people down, and it already essentially brings frozen people back to OK temps. Cryo ALREADY THERMO-REGULATES. There's also Leporazine, which kind of has no use except powergaming and unprotected EVA anymore.

So, we've already outlined a perfectly viable plan to replace the Mancrowave.
- [x] Move Thermo-regulation into Cryo itself
- [x] Add a "Waker-Upper" functionality to Sleepers
- [ ] REMOVE MANCROWAVE remove mancrowave. you are worst snowflake. you are the snowflake idiot you are the snowflake smell.

**Comment by ihadtoregisterforthis** [comment]
The cryo only autoregulates explicitly to avoid Mancrowave dependency if I follow the development right.

**Comment by 9600bauds** [comment]
It already auto-regulated before. A patient ejected from Cryo required 0 treatment except shaking up before the Mancrowave.
Besides, even if the thermo-regulation process was actually necessary, it would still make a ton more sense to make it built-into the cryotube, wouldn't it?

**Comment by ghost** [comment]
:-1: 
Should Cryo also automatically perform surgery on you too?

**Comment by ihadtoregisterforthis** [comment]
If, again, I understand correctly cryo ejected people at inhuman temperatures.

**Comment by 9600bauds** [comment]
The inhuman temperatures actually did nothing with the previous temperature system, though. To claim that thermo-regulation is necessary with the new temperature system is just dishonest when that's not the way it used to work.

@DrCelt I already elaborated in #7909 why adding an extra step to Cryo is a terrible addition, and I'm even willing to compromise on this. Nobody was complaining about Cryo not requiring special treatment for the years it worked fine before hypothermia. Also, that slippery slope exaggeration doesn't help anyone.

**Comment by ghost** [comment]
I've talked with people who play doctors before and after this change, and many of them have said "Actually, yeah, I've found the ride easier after this". If you can bring me evidence that the majority of people who play doctor hate this change absolutely, then yaknow, I'll personally do everything in this issue myself.

**Comment by 9600bauds** [comment]
I reckon they probably meant the waker-upper part, which I addressed too. That said though I'm not sure who have you been speaking to, my in-game experience differed, besides of course people finding the instant-wake-up-with-one-click handy, which I addressed too.

**Comment by 9600bauds** [comment]
> "Actually, yeah, I've found the ride easier after this".

#8052

**Comment by Kitfox88** [comment]
I'm a manager on the wild ride semi-often and I think the mancrowave is neat

**Comment by Duny-** [comment]
I don't care either way (though I find it to be a very unnecessary addition) but the mancrowave is as ugly as orange hair and doesn't look like it belongs in the game so if it stays IT NEEDS ANOTHER SPRITE. Way too massive-looking too compared to the sleepers.
Also I'm not for making cryo even better, but obsolete equipment like sleepers should be changed to accomodate new features rather than adding new unnecessary equipment only useful for one snowflake purpose and making medbay even more cramped than it always is.

**Comment by Shadowmech88** [comment]
I feel like, at the very least, it needs to not be called the mancrowave if it also cools people down and wakes up sleeping people.

**Comment by ghost** [comment]
Medical nuked when?

medkits, basic surgical equipment, pestle and mortar and electrolyzer at roundstart only, no sleepers or scanners or cryo or genetics or virology, make mechanics and science have something to do if they want the station to actually survive.

**Comment by ghost** [comment]
@Shadowmech88 it ISN'T called the Mancrowave unless it's emagged.

**Comment by Duny-** [comment]
It is in the code tho which makes me mad like everything else in the code that is called a different way than in the game REEEEE

**Comment by ghost** [comment]
Could add Leporazine to sleepers once they've received an upgrade, that helps regulate temperature.

The sprite does need a bit of poking.

Also, something odd, if you resist out of cryo, your temperature will be set to normal because "They've suffered enough" so it does sorta handle itself

@Duny- Autolathe in deff R&D when?

**Comment by Duny-** [comment]
@Skullyton I'm removing all the materials and adding an autolathe instead next update like I said

**Comment by ghost** [comment]
@Duny- pls

**Comment by 9600bauds** [comment]
@Skullyton this is a bad idea because Medbay machines very rarely get upgraded, even when you beg, yell at, or actively threaten Science and Mechanics

**Comment by AutismSpider** [comment]
not like Leporazine hard to make.

**Comment by FudgePucker** [comment]
Why not just let sleepers regulate tempature?
Bam, I removed a pointless device having no reason to be in the game

**Comment by 9600bauds** [comment]
Entirely possible since the Mancrowave is a modified sleeper, but the elephant in the room here is that Cryo already regulates temperature nearly perfectly well

**Comment by icantthinkofanameritenow** [comment]
@9600bauds
If you want to argue that point, be my guest. I've done it enough before the thing got added and I'm sick of fighting a battle I personally can't win.

**Comment by 9600bauds** [comment]
which point are we talking about

**Comment by icantthinkofanameritenow** [comment]
@9600bauds
All of them.

**Comment by 9600bauds** [comment]
could you please be a little more specific because I'm really confused so as to what you're trying to say here

**Comment by icantthinkofanameritenow** [comment]
@9600bauds
Mainly, that DrCelt really doesn't want to get rid of the Mancrowave.

**Comment by 9600bauds** [comment]
I don't blame him for that, honestly if I made an addition of that magnitude I wouldn't want to get rid of it either.

**Comment by Shadowmech88** [comment]
The hypothermia update was huge, but how large was the Mancrowave itself, really?

**Comment by 9600bauds** [comment]
About two tiles

**Comment by NigglyWiggly** [comment]
If the mancrowave was upright and took up only one tile, would that be better?
it'd make the fact that you get out standing up actually make sense, at least.

**Comment by 9600bauds** [comment]
Size was never the issue here desu

**Comment by AutismSpider** [comment]
@NigglyWiggly if some one going do that why not mix it with the god damn cyro with a toggle to it when body done healing the cyro heats up a bit then spits them out.

**Comment by icantthinkofanameritenow** [comment]
@AutismSpider
We've been through this, it's because...well, honestly Celt hasn't really explained it all that well.

**Comment by Duny-** [comment]
So if I understand correctly this is pretty much done. So why is the mancrowave still visually polluting the maps and why is this not closed? 🤔
