### ISSUE TITLE
Some computers work while APC power for equipment is off if they're unwrenched

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8048]
Specifically DNA consoles
So to reiterate the title:
Unwrenched DNA consoles can be used in areas where equipment is unpowered as long as they're unwrenched.

**Comment by Kurfursten** [comment]
Cameras also work when the power is off, when they really should at least be an environmental thing.

**Comment by 9600bauds** [comment]
As far as I can tell this ONLY affects the DNA console
