### ISSUE TITLE
IMMOVABLE RODS CAN SCRAPE GHOSTS AND CRASH CLIENTS

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8049]
PANIC
@clusterfack

**Comment by clusterfack** [comment]
Crash a client? That's pretty unbelievable, but yeah the scrape ghost thing alright.

**Comment by Exxion** [comment]
Well, I teleported to the immovable rod, got scraped by it and watched several other ghosts get scraped by it, and crashed before graphics even loaded

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/12770949/08f466e8-c9f3-11e5-8e70-5ce5189e75c5.png)

![image](https://cloud.githubusercontent.com/assets/9827785/12771031/a6e48414-c9f3-11e5-98ff-a0202a2c7c3f.png)

**Comment by clusterfack** [comment]
Probably just from chat spam I'd expect if enough ghosts follow it, there's nothing that would inherent cause a client to crash there otherwise. Anyway I've already made a fix.
