### ISSUE TITLE
Galactic Common and Sol Common both use the default text color/font making them indistinguishable if you understand both

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8050]
Somebody diddly darn fucked up

**Comment by ghost** [comment]
@gbasood

**Comment by ihadtoregisterforthis** [comment]
Also, if you don't understand one, the speaker appears to be talking gibberish on purpose.

**Comment by Exxion** [comment]
Yeah, that was what really confused me when I saw it and didn't know the thing had been merged yet

**Comment by Imagebard** [comment]
They used to have a smooth font for Sol Common, you know. Are things like that saved on BYOND? Can we "revert" to some patches before the saycode update and see what font it was?

**Comment by Exxion** [comment]
Honestly, having a different color is much nicer than having a different font. Both is good too though.

**Comment by gbasood** [comment]
@Imagebard Easier to look at another repo with both languages still intact and see what they use
I was looking into this earlier, and I couldn't find which part of saycode decorated text with fonts and colors. I'll keep looking.

**Comment by Imagebard** [comment]
What color would sol common even be, Exxion?

**Comment by Exxion** [comment]
Anything other than the default black local/green comms or any that's taken
A shade of blue somewhere between OOC and the skrell language might be good
Earth is blue, after all

**Comment by Imagebard** [comment]
Its the common language of all of Sol, not just Earth.

**Comment by Exxion** [comment]
Humans are from Earth
You could  make it orange or something if you wanted though
There are plenty of open colors

**Comment by Imagebard** [comment]
I was actually considering before you posted that you piece of shit

But all things considered different colors should be for races that speak strangely. Dionas make tree sounds, I think Plasmamen are internally combusting or clacking their skeletons. When you consider that, Sol Common and Galactic Common aren't so different.

**Comment by Exxion** [comment]
But they need to be differentiated.

**Comment by Imagebard** [comment]
I don't even support different colors for racial speech.

And besides a different font is plenty enough. People asked if I was okay whenever I spoke in Sol Common.

**Comment by CptWad** [comment]
What fonts does byond support?

**Comment by gbasood** [comment]
I think our chat uses CSS to specify fonts, so I'd assume anything that the embedded IE windows could display, the chat could display.

I think a different styling is probably important here, but we don't need yet another color in chat for no good reason.

Alternatively I could just change the syllables to be single words instead of collections of actual gibberish syllables.

**Comment by Exxion** [comment]
Then you'd just make it even more confusing

**Comment by uazuaz** [comment]
side note: i think that the description for Galactic common

> A bastardized hybrid of informal English and elements of Mandarin Chinese [..]

should be applied back for Sol common instead; there is no reason to think that other species beside humans know a language that originates from English and Chinese.

**Comment by Killette2** [comment]
Let's try yellow

**Comment by Imagebard** [comment]
@Killette2 
Are you one of those people that think that using your donator/moderator benefit of changing your OOC color to spam pisstext is funny?
Are you?
