### ISSUE TITLE
CELT FUCKED UP CRYO AND I CAN'T BELIEVE I DIDN'T NOTICE SOONER

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8052]
So, when @DrCelt said "nerfed everything that caused cold", he meant it.
# THE RATE AT WHICH CRYO COOLS PEOPLE WAS ALSO SEVERELY NERFED, WHICH MEANS THAT CRYO TAKES A SIGNIFICANT AMOUNT OF TIME BEFORE CRYOX AND CLONEX (MAIN COMPONENTS OF CRYO) TAKE ANY EFFECT.

I had a creeping suspicion that Cryo seemed to not work very good lately, but I didn't suspect this. Yep, it's fucked up ladies and gentlemen.

Comparison .webm's soon.

Some quotes to live by:

> I don't think it's fair to blame the wild ride on the thermal homeostasis regulator.
> 
> I've talked with people who play doctors before and after this change, and many of them have said "Actually, yeah, I've found the ride easier after this"

**Comment by gbasood** [comment]
:warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: 

# @DrCelt YOU RUINED IT

:warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning: :warning:

**Comment by Zth--** [comment]
:+1: for the quotes

**Comment by Iamgoofball** [comment]
Why not try using actual medicine and doctoring?

**Comment by 9600bauds** [comment]
Because clone damage is only healed by Cryo and Rezadone, and even though I make Rezadone every shift it's not fast enough.

**Comment by optimumtact** [comment]
**USE GOOFCHEM**

**Comment by gbasood** [comment]
> use goofchem

pls no

**Comment by 9600bauds** [comment]
Goof please for the love of God port goofchem OVERDOSING ONLY WITHOUT ANY CHEMICALS already

**Comment by Iamgoofball** [comment]
if anything addiction is the ugliest part of the code

i refuse to port any goonchem parts without porting the overdose code so that you can get rid of hardcoded checks in life

**Comment by Kitfox88** [comment]
goonchem a shit

**Comment by 9600bauds** [comment]
I meant overdosing, sorry

**Comment by Iamgoofball** [comment]
@kitfox88 says the guy who probably hasn't used it ever

**Comment by 9600bauds** [comment]
let's please not make this about goofchem unless we're discussing porting goofchem overdose code

**Comment by 9600bauds** [comment]
also please port goofchem overdose minus the goofchem

**Comment by ghost** [comment]
Cryo nerfed ?

Perfect

**Comment by 9600bauds** [comment]
That'd maybe be a good thing if it was nerfed for general healing, but this massively fucks over the INTENDED use for it, that being clones.

**Comment by Kurfursten** [comment]
Just throwing this out there, but what if fresh clones pop out of the cloning pod at a frosty temperature, all prepped for cryo?

I mean, why wouldn't they? They're already floating in some sort of clone-damage-repairing liquid in the pod.

**Comment by ghost** [comment]
As far as I can remember, I didn't change any formula for cooling in cryo. That may however be the problem. I'll take a closer look later today.

**Comment by 9600bauds** [comment]
Because the cloning pod is not cold and not connected to the freezer. And you'd kill clones that plop out of the cloner without anyone to help them.

**Comment by 9600bauds** [comment]
Besides, this entire business of "high-tech cryogenic process involves just booting out frozen person to be dragged across the floor" is just fucking dumb, no way around it

**Comment by Kurfursten** [comment]
@9600bauds Behead those that allow clones to plop out unattended

**Comment by 9600bauds** [comment]
It Is Sometimes Beyond Their Control, Especially In A Game With Antagonists And Stuff

**Comment by Kurfursten** [comment]
You mean Byond their control

**Comment by optimumtact** [comment]
I regret my comment

**Comment by ghost** [comment]
Huh. That's pretty cool actually.
Turns out the reason wasn't because of me nerfing anything that does cold damage, but rather nerfing heat loss to the environment, and cryo is effectively just a fancy environment apparantely. Luckily there's already code in here to pick up the pace when cryo's environment isn't up to scratch.
