### ISSUE TITLE
Screwdrivering a cloning pod while a clone is inside replaces the cloning sprite with the inactive sprite (cloning process not interrupted)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8053]
(WEB REPORT BY: archsunder REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e2ab9f9c7dbaab2d5bcdc9eb95f21b03226a92ac 
> 
> General description of the issue
> Opened maint hatch for cloning pod, someone started getting cloned, closed pod, they vanished
> 
> What you expected to happen
> for them not to vanish
> 
> What actually happened
> they vanished
> 
> Steps to reproduce if possible
> start cloning someone, open and close the maint hatch

**Comment by 9600bauds** [comment]
wuhat

**Comment by 9600bauds** [comment]
Loosing this until confirmed or denied

**Comment by Kurfursten** [comment]
This is just due to a sprite update change associated with SCREWTOGGLE I'm sure, can you confirm they actually stopped cloning and it didn't just LOOK like they did?

**Comment by 9600bauds** [comment]
this is indeed what Kurfursten said, the clone is still safe&sound&there

still a bug, but un-loosing this
