### ISSUE TITLE
Send Specialist panel/verb for admins

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8054]
> a nice feature would be a bussable 'send specialist' option actually
> for instance, combat, medical, engineering
> I know a few rounds ago they wanted us to send  them a virologist to fix some shit
>  ideally you'd just have a panel to spawn a dude with the right gear and a randomized name
> and he'd show up in arrivals or osmething
> either manually set or recruited from the ghosts

**Comment by ihadtoregisterforthis** [comment]
So a one man ERT?

**Comment by Exxion** [comment]
#7147 nerd
