### ISSUE TITLE
Created SmartFridges cannot contain anything but crops

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8055]
(WEB REPORT BY: brokenboundarie REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 3044bff41ba3b4990ea803c60852a5bf6ecb4237
> 
> General description of the issue
> There is only one type of circuit for the SmartFridge, and when built into a machine it makes a fridge as configured in hydroponics, which refuses all items except for crops. There is no apparent way to reconfigure the board or the machine to to function the same as the fridges in chemistry or xenobiology to store chemicals or slime extracts, and so these modes of the machine can never be reproduced.
> 
> What you expected to happen
> The board could be modified with the soldering iron to switch between configurations. The machine could be configurable with some tool while the maintenance hatch is open. There could be separate circuit boards for each configuration of the machine.

**Comment by Imagebard** [comment]
Did he try modifying it with a multitool?

**Comment by Exxion** [comment]
No. It's a totally different board for the other smartfridges. Only the hydroponics one is constructible, but fixing that would just entail adding the other smartfridge boards to the designs list.

**Comment by Zth--** [comment]
Having different circuits for the same machine is kind of stupid. The multitool thing is a good idea

**Comment by 9600bauds** [comment]
Tagging this as oversight because arguably the chemistry chemfridge circuit is missing as-is, though we really should unify the fridges already
