### ISSUE TITLE
People take burn damage in the cryo

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#8056]
People take burn damage in the cryo and this damage outdamages the healing done by cryoxadone.
![cryoxadone](https://cloud.githubusercontent.com/assets/3892856/12781661/773489d6-ca7e-11e5-8599-26fa82007b76.gif)

**Comment by ghost** [comment]
This is not my fault, by the way! I actively tried to find out how to fix it but I literally couldn't figure it out

**Comment by BestName** [comment]
I'm blaming you anyway.

**Comment by Shadowmech88** [comment]
It kind of is your fault if you knew it was a problem, yet said it was ready to be merged anyway.

**Comment by ghost** [comment]
@Shadowmech88 It was a problem before my PR and was a problem after. I attempted to look for a fix to it in my PR, but couldn't.

**Comment by ghost** [comment]
See #6664 for proofs

**Comment by Shadowmech88** [comment]
What the fuck, this has been an issue for two months?
That's crazy.

**Comment by ghost** [comment]
I have literally no idea what caused it and I had a good hard look at cryo code.

**Comment by 9600bauds** [comment]
It doesn't actually outheal the cryoxadone, it's just that the cryoxadone takes like 40 fucking seconds to start working due to #8052. Once it does work, it's a tiny amount of burn damage and it gets outhealed easily.

**Comment by BestName** [comment]
@9600bauds the .gif I attached is 3:52 minutes long (the guy actually spent more than that in the cryo as I started recording when I noticed him taking damage) now last I checked 3:52 minutes is longer than "40 fucking seconds" so mind explaining to me how he died?

Anyways this isn't about whether or not cryoxadone is able to outheal the burns. This is about people receiving burns in cryo. Don't get stuck in the details.

**Comment by 9600bauds** [comment]
What did the mix consist of in this case?

**Comment by BestName** [comment]
It was the roundstart beaker of cryoxadone.

**Comment by 9600bauds** [comment]
Oh, yeah
It might actually outdamage pure cryoxadone in that case
I thought you meant clonexadone

Anyways, we literally don't fucking know what causes this burn damage. In fact, Celt removed burn damage from low temperature, so we have even less of an idea

**Comment by BestName** [comment]
Yeah, I added some clonexadone into the beaker and that was enough to keep the patient alive.
Well everyone always said cryoxadone was shit but surely it's not meant to be this bad.

**Comment by 9600bauds** [comment]
autoclose why
