### ISSUE TITLE
Humans retain their body heat a bit too well

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#8057]
If you let your temperature get to dangerous levels you will keep taking burn damage long after moving away from the source of heat because it takes forever for your temperature to go down.
If you for example walk through a campfire and then extinguish yourself you're still going to burn to death.

**Comment by ghost** [comment]
This is not an issue with retaining heat but rather gaining it, I'd argue.

**Comment by Killette2** [comment]
Also temperature guns set on cold do jack shit

**Comment by ghost** [comment]
@Killette2 they never did. If you want to make a PR buffing them, be my guest though.

**Comment by BestName** [comment]
Fixed, probably.
