### ISSUE TITLE
Infinite blood bucket

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8059]
Putting a monkey into a slime processor produces an infinite blood bucket.

The only way to empty it is splashing it on the ground.

**Comment by Killette2** [comment]
Isn't it supposed to contain 70 blood? You sure it's infinite?

**Comment by clusterfack** [comment]
Shitty oldcode causing more blood runtimes by not using reagent holders properly

08:26:07 Runtime detected
undefined variable /obj/item/weapon/reagent_containers/glass/bucket/var/my_atom at Chemistry-Reagents.dm:275
 proc name: on removal (/datum/reagent/blood/on_removal)
  source file: Chemistry-Reagents.dm,275
  usr: Kade Powers (/mob/living/carbon/human)
  src: Blood (/datum/reagent/blood)
  usr.loc: the floor (188,83,1) (/turf/simulated/floor)
  call stack:
Blood (/datum/reagent/blood): on removal(5)
/datum/reagents (/datum/reagents): remove reagent("blood", 5, null)
/datum/reagents (/datum/reagents): trans to(the syringe (/obj/item/weapon/reagent_containers/syringe), 5, 1, 1)
transfer sub(the bucket (/obj/item/weapon/reagent_containers/glass/bucket), the syringe (/obj/item/weapon/reagent_containers/syringe), 5, Kade Powers (/mob/living/carbon/human))
the syringe (/obj/item/weapon/reagent_containers/syringe): handle draw(the bucket (/obj/item/weapon/reagent_containers/glass/bucket), Kade Powers (/mob/living/carbon/human))
the syringe (/obj/item/weapon/reagent_containers/syringe): afterattack(the bucket (/obj/item/weapon/reagent_containers/glass/bucket), Kade Powers (/mob/living/carbon/human), 1, "icon-x=14;icon-y=15;left=1;scr...")
Kade Powers (/mob/living/carbon/human): ClickOn(the bucket (/obj/item/weapon/reagent_containers/glass/bucket), "icon-x=14;icon-y=15;left=1;scr...")
the bucket (/obj/item/weapon/reagent_containers/glass/bucket): Click(the floor (189,82,1) (/turf/simulated/floor), "mapwindow.map", "icon-x=14;icon-y=15;left=1;scr...")

**Comment by FudgePucker** [comment]
Hey man infinite blood bucket could be a slime product.

**Comment by Killette2** [comment]
*Monkey product

**Comment by Killette2** [comment]
And speaking of, DO monkeys have infinite blood before they become monkeymen? I've never bothered to check.

**Comment by clusterfack** [comment]
No they should have the same standard blood
