### ISSUE TITLE
Babies should be orderable from cargo

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8060]
This is how box babies would work

They are in the medical or hydroponics section called box babies
The crate contains a box which contains X amount of baby capsules, with embryos inside
When someone uses a capsule, it has a timer of them twisting it open, which pings ghost a box baby is being made
Once chosen a baby comes out and a greenish yellow stain such as puke, or red like blood, is splattered on the floor. If no ghost want to be the baby, baby is kill. Recommend deep frying.
Baby is given a chance to choose a name, like diona nymphs
Baby must eat a lot of nutriment until it can evolve into a man
Babies have the dexterity of monkeys so they're too dumb to use guns and computers, and can crawl on tables.
Babies are valid like monkeys,nymphs, and borers, they also speak their own baby language like the Rugrats
Let's throw in baby clothes crates existing too for the hell of it, monkeys need more clothes anyways so they also get to wear baby clothes.

**Comment by CptWad** [comment]
NO

**Comment by Imagebard** [comment]
![1443825016832](https://cloud.githubusercontent.com/assets/7571238/12794785/9854deba-ca95-11e5-9f58-81d2536f4acc.jpg)

**Comment by clusterfack** [comment]
For real tho, are you the guy who always posted about BABIES in the thread?

**Comment by Zth--** [comment]
How long have you been thinking of this?

**Comment by SangriaMonkey** [comment]
That boy ain't right

**Comment by Ephx1** [comment]
Can't you leave shitposting to the thread?
Go on, post about the vox eggs too.

**Comment by NigglyWiggly** [comment]
Haha guys do you think Vox get embarrassed when they poo out eggs in front of the crew
sorry if this offends anyone but I thought it was a funny thing haha
What do you think the eggs would smell like haha im just curious for laughs haha

**Comment by Killette2** [comment]
There is literally nothing wrong with a sexless production of babies

**Comment by clusterfack** [comment]
Well I had to close it or else Celt might get on board with the idea and make them edible.

**Comment by 9600bauds** [comment]
ahhhahahahhhah shit 10/10

**Comment by Killette2** [comment]
STEM CELL GAINS
