### ISSUE TITLE
Bullet shrapnel has no sprite

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8066]
Specifically bullet shrapnel removed via surgery

**Comment by ghost** [comment]
To be more specific, they once had a sprite (View variables shows that they had icons with names such as shrapnelmedium) but said sprites are currently lacking from shards.dmi

**Comment by Exxion** [comment]
Shattered rods from powered crossbows also have no sprites

**Comment by gbasood** [comment]
@Exxion Separate issue, make a new issue for it

**Comment by Exxion** [comment]
Is it? Wow. OK I'll do that later

**Comment by ghost** [comment]
Hold on, bullets cause bullet shrapnel ? I always thought that was some old feature that was stripped from Baycode

**Comment by Ephx1** [comment]
Yeah, has bullet shrapnel been a thing all this time?
I haven't seen it since "Remove embedded object" was removed.

**Comment by ghost** [comment]
It has been a feature, and it can eventually cause internal bleeding if left unchecked, assuming the poor shot sod hasn't died straight away.
