### ISSUE TITLE
slots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8068]
(WEB REPORT BY: talux00 REMOTE: 158.69.55.2:7777)

> 77520459064c0945f3ea61969973a55966fb467b 
> 
> Whenever you equip an item in the suit storage, the sprite of said item stay on the hand but the item itself go to the storage and the only way to unequip it/use it, is to unequip your armor/suit.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ghost** [comment]
This was before #7929 was merged to the main server, by the way.

**Comment by Exxion** [comment]
Fucking magical
No fucking idea what happened but it was universal

![image](https://cloud.githubusercontent.com/assets/9827785/12803502/99e7d782-cab8-11e5-9ddf-c23734baa65f.png)

**Comment by ghost** [comment]
Never mind, this is due to #7929. I'll fix it.

**Comment by Exxion** [comment]
You're never going to live down the phrase "100% TESTED" by the way

**Comment by 9600bauds** [comment]
On the contrary
He's gonna live down by that phrase
