### ISSUE TITLE
Suit Slots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8070]
(WEB REPORT BY: xsdew REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Spawning in as a plasmaman, I had no plasma tank, yet I was able to use internals Like normal
> 
> What you expected to happen

Spawning in with a plasma tank on my suit slot as a plasmaman

> What actually happened
> Internals are on and running but no plasma tank on my persons
> 
> Steps to reproduce if possible
> Currently just spawning in, I dont know if its with late join or the suit slot specifically

**Comment by 9600bauds** [comment]
Probably caused by #8068 I think
