### ISSUE TITLE
Make Poly remember messages through rounds

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8071]
![](http://i.imgur.com/yOm4s1x.png)

**Comment by CptWad** [comment]
>allowing poly to become sentient

pls no we dont want 6GB of a superintelligent parrot that dies to a singlo every five shifts

**Comment by ghost** [comment]
> someone plays clown every round for 10 rounds
> abduct's CE's parrot
> consistently says "Vote Donald Trump, HONK!"
> Poly now says this forever

**Comment by 9600bauds** [comment]
Or do we?

**Comment by 9600bauds** [comment]
Also make it only remember lines from the last 24 hours or something obviously

**Comment by clusterfack** [comment]
Just replace poly with cleverbot with a parrotspeak converter

**Comment by 9600bauds** [comment]
If only

**Comment by ghost** [comment]
> play changeling one round
> CE screams over engineering "HELP X IS A LING"
> next round another ling round, but I'm no ling
> poly screams over radio "HELP X IS A LING"

**Comment by 9600bauds** [comment]
Can't wait for the day a Vox gets lynched because of a bird

**Comment by 9600bauds** [comment]
On a second thought it would probably end up less like silly metafuckery and more like https://www.youtube.com/watch?v=5hzfRJrYVVM

**Comment by Exxion** [comment]
It is nigh guaranteed that he would just fucking repeat WGW all the time

**Comment by Imagebard** [comment]
Nobody likes WGW anymore.

**Comment by gbasood** [comment]
I mean we could theorhetically do this with a limited string count of something like 600 strings? We'd avoid storing too much text that way

**Comment by 9600bauds** [comment]
This was a dumb idea

**Comment by Exxion** [comment]
Astonishingly so
