### ISSUE TITLE
Roller beds no  longer make you lie down when you are buckled to them

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8076]
And I think this applies to everything else, but _at least_ roller beds.

**Comment by 9600bauds** [comment]
@clusterfack

**Comment by 9600bauds** [comment]
Do you have any idea since when has this been happening?

**Comment by Exxion** [comment]
Today or yesterday.

**Comment by Exxion** [comment]
@clusterfack You could have autoclosed this too you know

**Comment by clusterfack** [comment]
Not my fault when you guys make dupes

**Comment by Exxion** [comment]
THIS ONE WAS MADE FIRST

**Comment by clusterfack** [comment]
That just means it was further down when I was looking for the issue to reference

**Comment by 9600bauds** [comment]
let us all be at ease for open issues are what make us whole
