### ISSUE TITLE
Excavation suits are not spaceworthy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8078]
(WEB REPORT BY: brokenboundarie REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 5b89b1e21cd7db1866da6e486219b73f5eaff405
> 
> General description of the issue
> Xenoarch's excavation suits are not spaceworthy. When leaving a pressurized environment they cause low pressure alarms and begin to wound the wearer despite ostensibly being a spacesuit. They should be spaceworthy.

**Comment by 9600bauds** [comment]
Were they spaceworthy before? I have no idea

**Comment by icantthinkofanameritenow** [comment]
Yes, they were. That was the whole point of xenoarchaeologists getting them.

**Comment by 9600bauds** [comment]
I got the excavation suit and anomaly suit mixed up
The only time I did xenoarch was as a bored miner and I did it in a mining hardsuit

**Comment by 9600bauds** [comment]
@DrCelt

**Comment by ghost** [comment]
Interesting.
