### ISSUE TITLE
Ideas For Client Color Features

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8079]
Since 509 lets us do all kinds of cool stuff with altering client colors, I think we should have one issue where everyone can post their ideas for specific client color features.

For example, adding actual types of colorblindness as disabilities.

**Comment by LordMyroc** [comment]
Plasmamen seeing everything through a purple tint when?

**Comment by ihadtoregisterforthis** [comment]
Thermals with a cool colorswitch
Mesons with a slight green tint
Something for some playable simple mobs

**Comment by Shadowmech88** [comment]
Oh you know what? Now we can tint NVG wearers' vision green.

**Comment by PJB3005** [comment]
Disability that changes RGB into BGR when

**Comment by NigglyWiggly** [comment]
Ian seeing in black and white when?

@PJB3005 I really want that as a 'color blind' gene

**Comment by clusterfack** [comment]
One of the issues we will run into is needing to use client images to make exceptions like blood for noir vjsion

**Comment by ghost** [comment]
@clusterfack PJB says it's possible in 510 with planemasters

**Comment by 9600bauds** [comment]
What is even a planemaster

Sounds pretty fly

**Comment by ghost** [comment]
I asked PJB and he said they're the guys in those air traffic control towers

**Comment by clusterfack** [comment]
@PJB3005 PLANE MASTERS, HOW DO THEY WORK?
