### ISSUE TITLE
Engineering hardsuits vulnerable to radiation

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8080]
Radiation permanently stunlocks and then kills a person.

It is stupid a non engineering job like xenoarcheologist gets a radiation immune space worthy suit while actual engineers get a useless resistance suit. I regularly see engineers rather use atmospheric hardsuits because those are actually useful in engineering work.

In fact there is absolutely no relevant advantage to using an engineering hardsuit, it might as well be a regular spacesuit.

Engineering hardsuits should be immune to radiation.

**Comment by ghost** [comment]
Radiation resistance needs a rework, right now it just decreases the chance of you getting a full dose, whereas it'd probably make more sense if it actually took a large amount off of the dosage so you could use something like hyronalin to take the edge off while doing work.

The fact it eventually knocks you out is also pretty bullshit, as it makes rad sources like transmitters guaranteed death. Why does it knock people out in the first place?

**Comment by 9600bauds** [comment]
Everything about radiation needs a rework.

**Comment by Ephx1** [comment]
Like making it so the radiation that Singularities, Radio Transmitters, and Rad storms are all one radiation?

**Comment by Kurfursten** [comment]
If you do that, you need to make radio transmitters consume a LOT more power otherwise people will power the station off the radio radiation

**Comment by 9600bauds** [comment]
Like making any radiation sources not stunlock, making radiation not completely inert 60 seconds after moving away from the source, making it do a little more than just toxin damage, making radiation medicine not nigh useless.

**Comment by ihadtoregisterforthis** [comment]
<sub><sup><sub><sup>tumors</sup></sub></sup></sub>

**Comment by Ephx1** [comment]
@Kurfursten 
Or you could just make radio transmitters not emit radiation.
I really don't see why they do, it's always just been used by silicons to fuck over carbons.
Is there a reason why it spews radiation?

**Comment by ghost** [comment]
@Ephx1 To make the DJ station a hazard

**Comment by Kurfursten** [comment]
@Ephx1 As far as I know it's supposed to model the dangers of high doses of radio waves, but turned up to 11 because it's IN SPACE and like the tcoms parts, apparently space radio requires some space magic due to distance.

**Comment by Ephx1** [comment]
@Skullyton 
The place isn't a hazard considering there's a rad suit right by the door.
Unless you're absolutely braindead retarded, you won't die from it.

@Kurfursten 
Well alright, it just seems really unnecessary when it kills you with in seconds of stepping near it.

**Comment by ghost** [comment]
@Ephx1 You'd be surprised how many people are caught out by it

**Comment by NigglyWiggly** [comment]
@Ephx1 I don't think you understand the sheer magnitude of ahelps we get about 'Dying 4noraisin on the DJ Sat is this a bug please fix'

**Comment by Ephx1** [comment]
Darwinism at its finest

**Comment by Kurfursten** [comment]
Given that there's a piece of paper that warns of the radiation I think this is a case of "illiteracy kills"

**Comment by AutismSpider** [comment]
warn about the radiation with the piece and floor markings and the haz mat locker.

Not only does the radio transmitters shit out rads it shit out heat means you need keep it cool or it just burn out and be useless.

**Comment by Kurfursten** [comment]
For reasons I have yet to explain the one in the DJ station never seems to get too hot

**Comment by AutismSpider** [comment]
two that never burn out one on the Centcom z level and the dj station one.

Station one will burn out if not set in a room with cold gas.

**Comment by Kurfursten** [comment]
Yeah, but that's as trivial as throwing an AC in there

**Comment by uazuaz** [comment]
> Yeah, but that's as trivial as throwing an AC in there

some time ago, i tried to activate the z1 radio transmitter and i put an air conditioner in the little room; the air temperature was about 18° C but the transmitter kept shutting off after some seconds every time.

**Comment by Kurfursten** [comment]
Did you make sure that it was wired properly? I've done the same without issue several times.

**Comment by uazuaz** [comment]
i wrenched it on top of a knot connected with the main power grid.
was about 4-6 weeks ago, i can't remember if i checked the power grid to see if there was power in it after a while, i should try it again.

**Comment by uazuaz** [comment]
i tried it again right now.

![rt](https://cloud.githubusercontent.com/assets/6170726/12858525/eb1ddbc6-cc50-11e5-929d-1bbfe04cfebd.jpg)
- the cable was powered and connected, knot under the transmitter;
- used 2 air conditioners set at the lowest temperature possible (15°C), obtaining a room temperature of 5°C;
- using a multitool i put the transmitter on, it goes off after some seconds;
- if i switch to the air analyzer very fast, i can see that the temperature goes around 40-45°C, maybe higher;
- when the transmitter goes off, it cools back to 5°C in few seconds

**Comment by clusterfack** [comment]
It got too hot and got damaged so it immediately shuts off when you try to turn it on

**Comment by ihadtoregisterforthis** [comment]
![uncanny alley](https://cloud.githubusercontent.com/assets/13305885/12859356/5f865690-cc34-11e5-913f-79e6dc1f2f18.png)
Try with foam next time

**Comment by uazuaz** [comment]
@clusterfack 

> got damaged

do you mean that the transmitter was broken, so even if i got a low temperature it didn't work properly?

@ihadtoregisterforthis 
eh, i hope i can find a way that don't oblige me to stand all the shift in that room

**Comment by clusterfack** [comment]
It was broken because it had already taken too much heat damage

**Comment by Kurfursten** [comment]
@uazuaz Yes that is exactly what happened, there is an internal damage counter

You can fix it with a solder

**Comment by uazuaz** [comment]
oh, i see now. many thanks for all the info.

**Comment by jknpj** [comment]
Radiation got reworked, times changed and it's time to let this issue go.
