### ISSUE TITLE
Possible optimization of atmos code

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8081]
In https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/ZAS/_gas_mixture.dm at line 454 there's a commented out del, I suggest changing it into an uncommented qdel.

Reasoning being, I'm assuming qdel is faster than relying on garbage collector.

**Comment by Exxion** [comment]
qdel actually works by relying on the garbage collector.

**Comment by clusterfack** [comment]
Come on now

**Comment by ghost** [comment]
Oh well. :^)
