### ISSUE TITLE
Fire alarms don't show code level properly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8082]
(WEB REPORT BY: mikecari REMOTE: 158.69.55.2:7777)
For example if it's code red the fire alarms all show up as green, so if some poor assistant arrives on station during code red he has no idea how fucked he is.

**Comment by Zth--** [comment]
I can confirm blue sprite is not working

**Comment by mikecari** [comment]
Should be an easy fix. ;(

R-right?
