### ISSUE TITLE
Attackspam bug is still present

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8083]
(WEB REPORT BY: mikecari REMOTE: 158.69.55.2:7777)
Why won't it go away? 

Ahh unsquishable bug

How to reproduce:
Grab guy, attackspam self with z

**Comment by ghost** [comment]
@clusterfack

**Comment by clusterfack** [comment]
Actually a bug with grab code as you can see here, it's not delaying the attack for all upgrade phases
![](http://puu.sh/mW98a/aa902fe068.png)

**Comment by 9600bauds** [comment]
Fixing this was kind of a huge deal and then everyone forgot I guess

**Comment by ghost** [comment]
So wait we took away mass eating food and didn't fix grabspam?

**Comment by clusterfack** [comment]
Pretty sure my fix for this went through
