### ISSUE TITLE
People remain prone when coming out of cryo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8084]
(WEB REPORT BY: mikecari REMOTE: 158.69.55.2:7777)

> put guy in cryo
> he comes out prone and can walk around while prone

**Comment by 9600bauds** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by Exxion** [comment]
Known issue, unknown cause
I am of the opinion it has to do with clone damage to the legs not updating properly but I can't be sure
Punch yourself to fix it

**Comment by 9600bauds** [comment]
I think it could be from the brain damage, rather, since it randomly makes you lie down

**Comment by Exxion** [comment]
It happens after you get attacked by slimes too though

**Comment by 9600bauds** [comment]
?????????

**Comment by 9600bauds** [comment]
Closing this in favor of #6029 which has more info including a possible fix

**Comment by clusterfack** [comment]
Honestly I don't know why punching yourself would fix it, I've never approached the bug from that angle but it might be an interesting way to investigate it from

**Comment by Exxion** [comment]
Punching yourself always fixes it on the next Life() tick as long as the problem that originally caused it (leg damage, or at least leg clone damage at least sometimes) was fixed.
