### ISSUE TITLE
Captain's space suit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8085]
(WEB REPORT BY: vikenz REMOTE: 158.69.55.2:7777)

> Revision 5b89b1e21cd7db1866da6e486219b73f5eaff405
> 
> General description of the issue
> Captain's armor isnt working in space
> 
> What you expected to happen
> To not get wrecked by space
> 
> What actually happened
> Got wrecked by space
> 
> Steps to reproduce if possible
> Walk out into space or depressurised areas

**Comment by Exxion** [comment]
@DrCelt

**Comment by ghost** [comment]
You know it'd be nice if all the space suits inherited from the actual space suit instead of snow flaking in space functionality.

**Comment by ghost** [comment]
As well as the fact the captain's hardsuit doesn't even cover the hands, I mean come on

**Comment by Killette2** [comment]
Funfact: The captains outfit is supposed to resemble Cpt. Crunch. Look at the hat and his jumpsuit.

**Comment by AutismSpider** [comment]
can we go back to using the old green one and not the blue?

**Comment by Zth--** [comment]
But blue is nice
