### ISSUE TITLE
If a medical cyborg uses up all of their advanced trauma/burn kits and steps into a recharger, their max amount will be increased

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#8087]
By default medical cyborgs are only able to hold a maximum of 10 advanced trauma kits and 10 advanced burn kits. But if they use them all up and then step into a recharger the maximum amount will be increased by 5.

**Comment by Kitfox88** [comment]
nice

**Comment by AutismSpider** [comment]
This is a bad thing?

**Comment by Zth--** [comment]
Why?

**Comment by BestName** [comment]
@AutismSpider Bugs are bad, m'kay.
