### ISSUE TITLE
False reinforced walls don't properly blend in with other reinforced walls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8091]
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> reinforced false wall doesnt blend in right with other reinforced walls
> 
> What you expected to happen
> a plain looking reinforced wall
> 
> What actually happened
> you can tell there is a false reinforced wall because the sprite for it has a line above and below and it doesnt connect properly with the wall
> 
> Steps to reproduce if possible
> make false reinforced wall

**Comment by 9600bauds** [comment]
I thought you couldn't make false reinforced walls anymore?
