### ISSUE TITLE
Ghosts can pull out people from cloning scanner

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8092]
Drag and drop scanner to a tile next to you while near it.

**Comment by 9600bauds** [comment]
ahhhhahahahaaahah

**Comment by 9600bauds** [comment]
I can't reproduce this, actually
http://a.pomf.cat/gfmcgv.webm
(yes I know it's the genetics console, they're the same machine, I tried it in the cloning scanner first)

**Comment by 9600bauds** [comment]
Actually the bug here is that you can do it while dead but not ghosted AND also adjacent to the machine
I wonder if any other machines also do the thing
