### ISSUE TITLE
Dirt trays can be dragged around

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8093]
Put a pipe connector under dirt tray, wrench it, unwrench it, marvel as you can drag it around.

Brought to you by taxi station outpost, where advanced xenobotany is done in dirt piles with connectors!

**Comment by 9600bauds** [comment]
ahhhhahahahaaahah

**Comment by 9600bauds** [comment]
How are you finding xenobotany by the way, I've never received ANY feedback on the whole thing

**Comment by ghost** [comment]
It's great, I already made my way around all your attempts at balance and am happily abusing it to it's maximum.

**Comment by 9600bauds** [comment]
Fantastic

**Comment by ghost** [comment]
Oh and, kudzu is useless as it's too slow to spread.

**Comment by 9600bauds** [comment]
Even if you plant a lot of it in multiple places?
The philosophy was that someone who wants roundending shuttlecall will do that, while the random event kudzu (just one hotspot) should be easily containable

**Comment by ghost** [comment]
I had it grown to 100+ potency endurance and basically godlike stats, it barely covered a room in quite a long time.
