### ISSUE TITLE
Standing up while buckled to a bed

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8094]
![0000](https://cloud.githubusercontent.com/assets/7571238/12833069/e58552ea-cb7c-11e5-9a44-2796a823124e.png)

Only information I have is that he was catatonic and was left over a table for a while. No idea how this happened.

**Comment by 9600bauds** [comment]
@clusterfack

**Comment by Exxion** [comment]
#8076 but neither issue has all the information

**Comment by DrCelt** [comment]
The real question here is how do you stand playing with that massive black outline

**Comment by clusterfack** [comment]
You guys are aware I get every single message put on this github to my email right?

**Comment by 9600bauds** [comment]
Yes but in this way people can see how much we care :)

**Comment by Exxion** [comment]
>Not turning off e-mail notifications

**Comment by clusterfack** [comment]
What do you think I'm actually going to browse this site for updates?

**Comment by Exxion** [comment]
Yes

**Comment by ihadtoregisterforthis** [comment]
Just in case you don't check your email.

**Comment by clusterfack** [comment]
If I didn't check my email I would literally never see it

**Comment by Imagebard** [comment]
THIS DOESN'T FIX STANDING UP WHILE BUCKLED TO BEDS, ONLY ROLLERBEDS
REOPEN

**Comment by clusterfack** [comment]
Which type of bed is it not working for?

**Comment by clusterfack** [comment]
I don't know what the fuck you are on about because I just checked and it clearly fixed standing up

**Comment by Imagebard** [comment]
Normal beds. Like in the dorms area or in the brig prisons.

Did the main server not update yet?

**Comment by Exxion** [comment]
Nope, just tested it. Normal beds work fine.

**Comment by Skullyton** [comment]
Why's this closed? It's still happening

![Standing](http://i.imgur.com/rkLaQYM.png)

Viewvar showed his can_stand = 1 if that helps in any way

**Comment by Skullyton** [comment]
@clusterfack

**Comment by clusterfack** [comment]
What object type is that, because this is literally fixed

**Comment by Skullyton** [comment]
/obj/structure/bed/roller, it's still happening!

**Comment by clusterfack** [comment]
Even with humans?

**Comment by Skullyton** [comment]
Yes

**Comment by clusterfack** [comment]
It very clearly works for me, so there must be something else at work entirely with canmove, a facet I did not touch.

**Comment by Imagebard** [comment]
Well, either way, it seems that something in the main server broke.
I request again, please **re-open this issueeeee**

**Comment by viniciuspetch** [comment]
Finally I found this issue:
@clusterfack , did you try with the subject already laying down (critical, sleeping, dead, whatever)? That might be the issue.

**Comment by clusterfack** [comment]
Alright, I found out why it occurs
