### ISSUE TITLE
Client fuckup

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#8098]
http://puu.sh/mWcwk/368b6c0f7b.png
this happened only after plasma got into my eyes. It got automatically fixed after I got into the shuttle (where there was no plasma in the air).

**Comment by 9600bauds** [comment]
I might just make a UI tag

**Comment by Exxion** [comment]
SOMEONE JUST CLOSED MY REPORT OF THE SAME BUG REEEEEEEEEEEEEEEEEEE

**Comment by 9600bauds** [comment]
Making UI tag since sprites and UI are completely different stuff, you could say UI is it's own beast really

**Comment by clusterfack** [comment]
It's not like any of them are fixable until the system is rewritten for better garbage collection

**Comment by 9600bauds** [comment]
When and if it's fixed, you'll be able to find them ez

**Comment by Zth--** [comment]
Note to myself: just use imgur
