### ISSUE TITLE
Test dummy admin spawns (presumably all invulnerable humans?) slowly lose body temperature forever

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8101]
let me guess, they don't exhaust nutrition so they don't burn calories so they never generate body heat even though they do lose body heat

I think at some point you're gonna have to tweak this burn_calories proc to allow for body heat generation to work independently from nutrient removal so throwing up doesn't cook you and shit

**Comment by clusterfack** [comment]
Fix it celt FIX IT

**Comment by Exxion** [comment]
Just make a use_nutrient() proc, make burn_calories() call it, make vomiting call it instead, and make it return on invulnerable mobs rather than making burn_calories() return
