### ISSUE TITLE
Treadmill husks you

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8104]
I don't care what you say, running on treadmill should never burn you to the point of becoming a husk.

It takes under 5 minutes to kill a man by running on it.

**Comment by Killette2** [comment]
Feel the burn, no pain no gain!

**Comment by unid15** [comment]
lol

**Comment by PJB3005** [comment]
Just so you know being husked by burn damage does not make you unclonable.

**Comment by FudgePucker** [comment]
100% tested

**Comment by 9600bauds** [comment]
Ahhahahaha what

**Comment by FudgePucker** [comment]
Hypothermia, where basklisks do no damage and are harmless and treadmills are lethal.
Also 100% tested :^)

**Comment by ghost** [comment]
> basilisks do no damage and are harmless

SEE THIS IS THE PROBLEM I HAVE PEOPLE TELLING ME THEY'RE TOO DAMN POWERFUL
WHO AM I TO BELIEVE

**Comment by Shadowmech88** [comment]
@DrCelt I believe it may be that the basilisks by themselves are harmless.
Their cold still puts you to sleep which means if a goliath or a hivelord is nearby they're going to fuck you up.

**Comment by ihadtoregisterforthis** [comment]
IIRC asteroid mobs don't attack people sleeping.

**Comment by Shadowmech88** [comment]
I'm just repeating what a guy in the thread said.

**Comment by ihadtoregisterforthis** [comment]
If it's from the thread then clusterfack can inmediately discard it.

I was mining recently and when confronted by a basilisk I got 0 effects. Maybe my cunning skills and stealth avoided any stare, maybe because I was a plasmaman, but it was as easy as shooting a monkey.

**Comment by ghost** [comment]
@ihadtoregisterforthis It was because you were a plasmaman. They've notoriously very good thermoregulation on account of the whole living in plasma thing

**Comment by AutismSpider** [comment]
basilisk are only deadly to humans diona vox and greys don't even try fight one as a slime type unless you like turning into ice burned mush in one or two hits easy kill for plasma men
