### ISSUE TITLE
Roller bed sprite broken?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8112]
(WEB REPORT BY: puglife REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9cb2cff81bce122c4596573433b45605e3d5e52e
> 
> General description of the issue
> When you buckle someone else into a roller bed, they remain upright. Seems okay when you buckle yourself in though.

**Comment by DrCelt** [comment]
@clusterfack

**Comment by Imagebard** [comment]
**I TOLD YOU IT WAS BROKEN**

**Comment by Exxion** [comment]
BUT ONLY SOMETIMES
WHAT THE FUCK

Anyway this is a duplicate and can be closed
