### ISSUE TITLE
You can collapse at-will

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8113]
Writing *collapse makes you asleep, and gives people that examine you the same text you get for examining a sleeping person.
For some reason, I don't think you should be able to become nearly comatose at will.

**Comment by 9600bauds** [comment]
Well, you can go asleep at will, and you can also *faint
I don't see the issue

**Comment by Imagebard** [comment]
At least make it so you're just pretending. You collapse and give off the sleep text, but still retain your 5 senses.

**Comment by Imagebard** [comment]
Well actually now that you mention it
