### ISSUE TITLE
[Discussion] Limb damage, dividing weapons into blunt and sharp, reworking bone fractures

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8114]
There's been a combination of stuff lately: Some people are clamoring that severed limbs basically never happen without the person dying, there's the long-standing bug where amputating someone's arms doesn't clear the damage from the limb, my recent change to bone fractures healing brute damage, and of course the always-present complaint that you can't break someone's legs without bleeding them to death in the process.

Some context on why this is the way it is:
- Bone fractures work like shit. Each limb has a threshold where if the limb surpasses that amount of damage from any means, the bone will immediately fracture.
- There's effectively no differentiation between sharp and blunt weapons. A toolbox will make you bleed just the same as a kitchen knife. The kitchen knife will break your bones just as well as a toolbox (when either of them reach the magic bone-break threshold).
- The only ways we have of treating brute damage are advanced trauma kits (which are rather limited) and fixing the bone to bring the limb back to the bone-break threshold (which is pretty shit of me honestly)

So, these are the changes I propose.
- [ ] Make bone fractures happen semi-randomly depending on the blunt force of the object, the damage the limb has, make them not happen from sharp objects unless the object is big enough to break it from blunt force alone (swords and shit)
- [ ] Make bleeding only happen from sharp weapons, or rarely from blunt weapons. A toolbox and a knife would both be deadly, but by different reasons.
- [ ] Fix limb amputation. Cutting off a damaged limb should clear the damage of said limb, which would allow the patient to be revived again. Make Deus Ex type of shit the new meta. Once that's done and bone fractures are reworked to not be so shit, remove my hacky code that makes bone fracture healing the current meta.

Sounds good?

**Comment by ghost** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Zth--** [comment]
Is there any proc that breaks bones without making any brute damage (or very little)? If not, that would be cool too

**Comment by AutismSpider** [comment]
oh good we can do some race base damage etc now dionas take less/no damage form blunt/stabbing but cutting hurts them a lot Skeletons/plasma men massive damage form blunt force cutting and stabbing does jack shit to them etc

**Comment by ghost** [comment]
Sounds good.

Now lets think about the energy sword, I think it should be very sharp but not cause bleeding.

**Comment by 9600bauds** [comment]
It's always been a mystery to me as to why it doesn't do burn damage since it's a lightsaber, but I guess it would be less robust that way

**Comment by Shadowmech88** [comment]
> Some people are clamoring that severed limbs basically never happen without the person dying

I disagree; losing a limb doesn't even kill you IRL, the biggest risk associated with it is bleeding out and that comes mostly with losing legs rather than arms.

> Cutting off a damaged limb should clear the damage of said limb

I think that not having a limb should carry either a set amount of damage or no damage, depending on whether or not the stump is cauterized.
I mean, what exactly are people dying of when they get 200 brute damage?
My guess would be shock induced by physical trauma. If that's the case, then an open severed limb would still cause the person some damage, though potentially less damage than they would've had when the limb wasn't severed, but it was broken in 30 places and flayed. A surgically removed limb, meanwhile, would be cauterized and so wouldn't damage the person at all.

**Comment by ihadtoregisterforthis** [comment]
Port Dwarf Fortress' wound system

**Comment by 9600bauds** [comment]
Closed source, I don't think anyone fully knows how it works

**Comment by Imagebard** [comment]
@9600bauds 
Yes, e-swords would be weaker.

Burn weapons are weaker than Brute, as a standard. They cause burns and that's it. An SAW machinegun form a syndie on other hand causes internal bleeding, broken bones, and other shit that just troubles medbay. The only upside is that ranged weapons that apply burns hit instantly unlike bullets which have a travel time like tasers.

**Comment by AutismSpider** [comment]
Can't you make the Esword do both burn and cut limbs off with no bleeding a esword can be use to light sigs and act as a cautery and scalpel for surgery stuff

**Comment by Kitfox88** [comment]
Make E-swords do no damage at all but instantly remove whatever limb they connect with if they connect with it :100:

**Comment by Shadowmech88** [comment]
Considering that people on the ground can't hold items or run, and if you lose a leg you instantly drop to the ground, that'd make the esword essentially a one-hit kill.
You'd slice their leg off and then be free to toolbox them to death as they slowly crawl away, unable to defend themselves.

**Comment by AutismSpider** [comment]
Why go for the leg Ebow and chop the head off in one hit.

**Comment by Imagebard** [comment]
How the hell did you focus on the "decapitating legs" part of the message?

As AutismSpider said, Ebow and chop off the head in one hit.
Better yet, unveil the esword right next to your target and cut his head off. No chance to scream.

**Comment by Shadowmech88** [comment]
The head didn't come to mind when I thought of "limbs."
But you are correct.

**Comment by Imagebard** [comment]
Okay, if we wish to merge this with the "is_bladed" idea they had in the PR stopping syringes form cutting bread...

It would be nice if bladed weapons caused more external bleeding, and less internal.
