### ISSUE TITLE
Ghosts can pull magazines out of guns

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8115]
![dreamseeker_2016-02-05_21-30-00](https://cloud.githubusercontent.com/assets/6526157/12863026/a9596e4a-cc4f-11e5-8549-7f0b1c9db9b3.png)

**Comment by Imagebard** [comment]
>Admin ghost

Did you test it as normal ghost

**Comment by 9600bauds** [comment]
Yes
![dreamseeker_2016-02-05_21-38-17](https://cloud.githubusercontent.com/assets/6526157/12863102/c9768680-cc50-11e5-91c4-7db01825e677.png)

**Comment by 9600bauds** [comment]
Works with other guns including assault rifles

**Comment by 9600bauds** [comment]
Also ghosts can open and close washing machines I guess

**Comment by ihadtoregisterforthis** [comment]
That last one is a feature
