### ISSUE TITLE
L6 SAW can still fire point-blank with its cover open

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8116]
![dreamseeker_2016-02-05_21-32-55](https://cloud.githubusercontent.com/assets/6526157/12863051/0aab044c-cc50-11e5-8a2c-b019cbef0422.png)

**Comment by Killette2** [comment]
This makes me wonder. Can you miss point blank when firing at yourself? Picture related, missing point blank at someone else.

![stormtrooper](https://cloud.githubusercontent.com/assets/5169310/12867656/79c1dcfe-ccc1-11e5-9ba0-49159de86643.png)
