### ISSUE TITLE
Ore boxes not working

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8117]
(WEB REPORT BY: archsunder REMOTE: 158.69.55.2:7777)
9cb2cff81bce122c4596573433b45605e3d5e52e 

> General description of the issue

Just seems to not be processing ore, doesnt come out of the crate onto the unloader

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ghost** [comment]
buncha runtimes in the logs

**Comment by Exxion** [comment]
If this got fucked, it got fucked in the past day or two.

**Comment by 9600bauds** [comment]
cannot reproduce anymore
