### ISSUE TITLE
Weird pressure value

### ISSUE THREAD

**Issue by viniciuspetch** [d3athrow/vgstation13#8118]
This happened after I screwed up the TEG, reset it and put CO2 on each loop.
![under pressure](https://cloud.githubusercontent.com/assets/4356629/12863176/caf17b18-cc51-11e5-923b-88d48a85103d.png)

**Comment by Exxion** [comment]
What the ungodly fuck

**Comment by 9600bauds** [comment]
picnic

**Comment by ghost** [comment]
Literally everything is fucked this round machinery wise. Take a look at the runtime logs to get a picture why.

**Comment by ghost** [comment]
Guess I'll report it here, a canister got so fucked it refused to transfer gases into tanks. Other canisters and tanks worked.

Was around [05/02/2016 [18:32:47]

**Comment by viniciuspetch** [comment]
I can't say much about "steps to reproduce". The only thing I did was open all valves and burn chamber's air escape, leave it for a while and then close everything and put 1 CO2 on each loop. I believe I put the canisters at the leftmost valves (near the burn chamber).

**Comment by FudgePucker** [comment]
Obviously it was a sign from the honk mother, giving you the okay to plasma flood

**Comment by 9600bauds** [comment]
chalking this up to "mysterious controller-breaking runtimes"
