### ISSUE TITLE
Chaplain hoodie sprite switched with something else.

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8119]
It now has a ugly, fleshy tie on it. And other changes, overall.

How did that happen?

**Comment by DrCelt** [comment]
I thiiink this is fixed by #8110 where I add the ignore_inv flag to it. If it persists after that, then we panic.

**Comment by Imagebard** [comment]
If you actually tested your code like anyone normal would you would actually know if it fixed the bug or not but since you already passed the hypothermia code as-is I guess its too late to tell you that.

**Comment by Kitfox88** [comment]
dayum

**Comment by DrCelt** [comment]
Wow rude
