### ISSUE TITLE
Advanced Silicate Sprayer reinforce/repair have weird interaction

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8120]
Step 1.Reinforce a window
Step 2.Repair that window normally
Step 3.Repeat(Only tested with multiple windows)

Now your Advanced Silicate Sprayer is currently holding more silicate than its max.

**Comment by Imagebard** [comment]
In a unrelated note, it would be nice if windows reinforced by the silicate sprayer had a different text when examined, like they have when damaged.

**Comment by AutismSpider** [comment]
Give it a glow/polished look for windows that been reinforced

**Comment by 9600bauds** [comment]
Cannot reproduce the bug part, the feature request was already in some other silicate sprayer issue
