### ISSUE TITLE
You can use a water cooler as a Xeno

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8121]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9cb2cff81bce122c4596573433b45605e3d5e52e
> 
> General description of the issue
> You can use a water cooler as a Xeno, and fill the cup.
> 
> What you expected to happen
> Muh dexterity.
> 
> What actually happened
> Cup with water.
> 
> Steps to reproduce if possible
> Become a Xeno (Sentinel) and go to a water-cooler. Click on it. TADA!

**Comment by SysadminJeroen** [comment]
You can also drink from the water cup.

**Comment by 9600bauds** [comment]
The real problem here is that you were a sentinel

**Comment by SysadminJeroen** [comment]
@9600bauds I know. I thought that it was a good choice but it was shit.

**Comment by AlphaBuffalo** [comment]
I think we should keep it for shits and giggles

**Comment by Killette2** [comment]
Another fun fact, xenos can pick up defibulators from the wall and put them in chargers. This brings more meaning to medbay is xenos.

**Comment by SonixApache** [comment]
should be left in in favor of medbay is xenos
take a break at the water cooler to talk about the humans you ate

**Comment by optimumtact** [comment]
Hey xenos need somewhere to unwind in the office too

**Comment by Probe1** [comment]
This is an assault not on xenomorph rights but what makes Space Station great.  

Make Spess Great Again.
