### ISSUE TITLE
Head rev flash

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8122]
(WEB REPORT BY: edwarus REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> flash doesnt change people
> 
> What you expected to happen
> for people to be subverted to my cause
> 
> What actually happened
> nothing
> 
> Steps to reproduce if possible
> not sure it just didnt work for me

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/12864837/e85ef1b0-cc67-11e5-8054-39c57a60588c.png)

![image](https://cloud.githubusercontent.com/assets/9827785/12864838/f379ca16-cc67-11e5-9b2a-44095a2aeb13.png)

[Honk]

**Comment by Exxion** [comment]
I have been notified that this specific person actually, legitimately cannot flash people for some reason
Sorry

**Comment by 9600bauds** [comment]
By any chance, did this happen in Mixed or in actual Rev?

**Comment by Exxion** [comment]
Rev
According to @CptWad, it's a thing with his client or some shit
He has a sec ban, but it has allegedly happened since before he got it

**Comment by 9600bauds** [comment]
Spoopy

**Comment by CptWad** [comment]
Ye can confirm
Heres what I saw
>Flash in perfect working order
>Other revs were operating just fine
>When he flashed somoene the sound would play but they would not get _flashed_ in the sense that their screen fades to white and they fall on the floor, followed by a lack of rev-izing

**Comment by 9600bauds** [comment]
> they would not get flashed in the sense that their screen fades to white and they fall on the floor, followed by a lack of rev-izing

When you say this, do you mean they DID get fade to white + stun, or not?

**Comment by CptWad** [comment]
There was no stun, no flash, no rev-ising just the sound clip playing

**Comment by Exxion** [comment]
And it didn't say that he failed to blind them?

**Comment by CptWad** [comment]
No message at all saying they flashed. All that played was the sound

**Comment by clusterfack** [comment]
Didn't that post just say they were wearing sunglasses or what

**Comment by CptWad** [comment]
Nah Even if they were wearing protection it did not even say that he failed to flash them. No message only sound played.

**Comment by ihadtoregisterforthis** [comment]
@clusterfack Since when do you trust the thread anyways?

**Comment by clusterfack** [comment]
Apparently I was wrong to

**Comment by DamianX** [comment]
Rev is no longer in rotation and if this DOES happen again it'd be best to open a new issue, since presumably the new rev implementation would be different.
