### ISSUE TITLE
Bomberman Sprites

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8126]
(WEB REPORT BY: kitfox88 REMOTE: 158.69.55.2:7777)

> Revision 9cb2cff81bce122c4596573433b45605e3d5e52e 
> General description of the issue
> Bomberman sprites vanish when you toggle off darkness as a ghost
> 
> What you expected to happen
> Them to remain
> 
> What actually happened
> They vanish spookily
> 
> Steps to reproduce if possible
> Toggle darkness as a ghost while spawn platforms and whatnot are active in the BOMBERMAN RAGE ZONE

**Comment by Exxion** [comment]
Not really fixable, unless 510 added something that would let us fix it
Which actually isn't out of the question
@PJB3005

**Comment by Kitfox88** [comment]
It's not exactly something super duper important anyway, I basically just reported it for notification's sake.

**Comment by Intigracy** [comment]
Why is their invisibility layer so high that it's on par with ghosts?

**Comment by Exxion** [comment]
So they can't be seen by non-ghosts

**Comment by Intigracy** [comment]
Why does that matter, considering all of the bomberman arena stuff is on centcomm's z level?

**Comment by Exxion** [comment]
The spawn pads would get in the way of and be visible to the Bombermen in the arena

**Comment by Intigracy** [comment]
You can make the spawn pads invisible without making the bombermen invisible.

**Comment by Intigracy** [comment]
Why isn't the invisiblity just set when the match begins?

**Comment by Exxion** [comment]
You know, that actually sounds like a good idea
