### ISSUE TITLE
You can add cyborg items to the medbay fridge

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8127]
(WEB REPORT BY: kitfox88 REMOTE: 158.69.55.2:7777)

> Revision be703dbcfc4c84afff9552b3e4154ae73235975a
> 
> General description of the issue
> Clicked on fridge with my upgraded hypospray as a medborg, added it to fridge. It didn't actually get taken from me, and the fridge didn't actually vend anything, but still.
> 
> What you expected to happen
> Nothing
> 
> What actually happened
> Silliness
> 
> Steps to reproduce if possible
> Click a fridge with your cyborg tools, it might eat em.

**Comment by DamianX** [comment]
doesn't happen anymore
