### ISSUE TITLE
Holodeck Issues

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8128]
- Can't put things on holo-tables.
- Holo-windows are full tile and don't let lasers pass and have no click delay on whacking them and are in general just awful
- Bottom Ready Declaration Device in Thunderdome Court simulation spawns inside the windows of the holodeck. Somehow, can still be interacted with.
- Snow Field simulation trees can be cut down, give very real and non-holographic wood.
- Theatre racks can be deconstructed with a wrench, give very real and non-holographic rack parts which can be deconstructed into very real and non-holographic metal.

**Comment by Exxion** [comment]
Holodeck is generally ass
I have a plan to reduce the suck but I'm not sure if it's feasible
In the mean time, these are all easy to fix

**Comment by Kitfox88** [comment]
holodeck sucks shit

can you still flood the station with retard plasma using an emag or was that removed ages ago

**Comment by Exxion** [comment]
13-digit pressures from the burn sim was fixed. The burn sim is still there though.

**Comment by AutismSpider** [comment]
don't even need emag for the burn sim or the carp spawn tell the emag borg to set it for you and bolt down all the air locks

**Comment by ghost** [comment]
The holodeck is awful.
