### ISSUE TITLE
Inconsistent paramedic access to morgue

### ISSUE THREAD

**Issue by viniciuspetch** [d3athrow/vgstation13#8129]
While paramedics can't access the morgue by the main door, there's still a valid non-hacking way to access it in Boxstation.

In Boxstation, they can access via the door between paramedic's room and morgue. However, in Taxi there's only one door to morgue (the main one), and so there's no access to paramedics.

I can't remember if there's such door in Defficiency.

**Comment by ghost** [comment]
How about make paramedics a subclass of medical doctor, just like surgeon/chemist. All medical personnel should be able to access entire medbay barring CMO office.

Plus medical would get maint access.

**Comment by Killette2** [comment]
Medbay + maint = greyshirts with access to chloral

**Comment by ghost** [comment]
> he doesn't make chloral from salt when greyshit

**Comment by 9600bauds** [comment]
Where do you get the ethanol?

**Comment by Killette2** [comment]
I know where to get the ethanol, it's close to the salt is your hint.

**Comment by viniciuspetch** [comment]
Well, this issue was initially only for morgue, but only today I found another inconsistence: paramedics can't access Taxi's medbay break room. That's an ultrage! What are they going to do during their entire shift? Save people?
