### ISSUE TITLE
Ingame bug reports not showing up on github?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8132]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)
Okay, if this gets through, disregard, if it doesn't, we've lost about 6 bug reports just from the previous hour if I'm seeing this right.

**Comment by ghost** [comment]
Apparently not, Odd

**Comment by clusterfack** [comment]
SMOOTH
