### ISSUE TITLE
Split General Antag preferences and in-round antag preferences

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8133]
It is starting to get really annoying to be picked as a Xenomorph, a Wizard apprentice or any other sort of antag spawned during the round simply because I have those roles enabled for roundstart on the one character I play with

Please change it so that I can answer yes to roundstart picks, but be actually polled without automatic pick when a Wizard tries to find an apprentice or a larva tries to spawn

**Comment by ghost** [comment]
Antag picker needs a rework, it should also first choose people at roundstart for antag rolls and only afterwards consider which regular jobs they can fill based on the antag rolls.

Currently you miss out on many antag rolls because you play protected/restricted jobs, with the above you'd get antag and get picked for non protected/restricted job. Of course still with a chance to get the protected job while also antag as it is now, but you'd be guaranteed to get antag as often as any other player regardless of job choices.

**Comment by FudgePucker** [comment]
What about a 'I am boned and not going to get cloned am board' button for late spawn antags.

Also can be used for bus faster.
