### ISSUE TITLE
Taxi salvage shuttle can't dock onto the derelict

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8134]
![Docking port highlight](http://i.imgur.com/C0FnzIT.png)

As the salvage shuttle does not have destroy_everything = 1, it can't dock at this docking port.

Seems whoever converted the taxis into the side-get-on forgot to take the salvage shuttle docking into account

On an unrelated note, this show-ship-highlight function is pretty neat

**Comment by xpcybic** [comment]
Oops that would be me
I'll try to get this and any other docking port related issue fixed since I think there's another one like this for the syndie shuttle
