### ISSUE TITLE
Lasers frozen in air

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8135]
Moving a shuttle like the one going to science outpost on box will cause all lasers fired from guns be frozen in air if they exist at the moment it moves.

I bet this works for all kinds of projectiles or other delayed effects like wetness.

**Comment by FudgePucker** [comment]
Lasers frozen in air is going to be my new band name. Once I get a band. Or musical skills. Or anything.

**Comment by Killette2** [comment]
My band name on Rockband was No Dykes Tonight

**Comment by SGuivenne** [comment]
Is this bug a thing and how did someone manage to discover it to begin with?

**Comment by DamianX** [comment]
Still a thing.

**Comment by Pathid** [comment]
Wetness was fixed by #16705 at least.

**Comment by Exxion** [comment]
For the record, this would happen with all *beam* projectiles, but not other ones.
Beam projectiles are rendered in a really weird way that seems bad until you realize there's no better way to do it

**Comment by Shadowmech88** [comment]
@Exxion 
What could potentially break if we made the shuttle move code clear all overlays on the turfs when the move happens? Or even just clear all the beam overlays?

**Comment by Exxion** [comment]
If you're just removing beam overlays, nothing significant could go wrong I can think of
