### ISSUE TITLE
When a ling goes horror form, literally the entire universe hears the sound and gets the message

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8137]
It's literally a to_chat(world
A spaced deaf guy hears it
New players who haven't joined yet also hear it

**Comment by ghost** [comment]
I'm pretty sure this is intentional.

**Comment by 9600bauds** [comment]
But why

**Comment by Shadowmech88** [comment]
That's just how loud the roar is.

**Comment by Ephx1** [comment]
So loud it breaks the boundaries of IC and OOC

**Comment by Zth--** [comment]
The horror form is not even THAT overpowered

**Comment by Killette2** [comment]
What happens when a plasmaman goes horrorform? A skeletal horrofrom while on fire would be amazing

**Comment by Exxion** [comment]
I like how new players in the lobby can see captain's announcements but not CentComm announcements, even though they can hear the notification

**Comment by ghost** [comment]
Horrorform is a joke, any bleeding will completely fuck it.

**Comment by ihadtoregisterforthis** [comment]
Do other races get to be lings or vampires?

**Comment by Exxion** [comment]
> Horrorforms can bleed
1. Why?

**Comment by ghost** [comment]
Because the prohibitive genome cost and time it takes to achieve it means nobody gives enough of a fuck to balance it.

@ihadtoregisterforthis

Yes.

**Comment by clusterfack** [comment]
It also isn't immune to chloral

**Comment by Exxion** [comment]
It should really have full chem immunity and no need for blood
But that discussion belongs on its own issue

**Comment by AutismSpider** [comment]
not immune to chems or xeno face fucking it to death+eating the body so its gone for good

**Comment by Shadowmech88** [comment]
Most living things aren't immune to chloral, I think.
Last time I played, even xenos could be chloral'd with a spray bottle.

**Comment by Killette2** [comment]
> not chugging infinite antitox to be immune to chloral in all situations

stay pleb

**Comment by 9600bauds** [comment]
it still sleeps you for a few ticks nerd

**Comment by ghost** [comment]
So I timed how long it takes to go horror form last round, I spend literally 45 minutes doing absolutely nothing but making and absorbing monkey humans from genetics. 45 fucking minutes for a lackcluster hulk that will forever give you away as valid on sight and only advantage is stun immunity. Which is made irrelevant by chems and bleeding.

**Comment by 9600bauds** [comment]
Speaking of chloral, an unconscious person hears the screech too

**Comment by ghost** [comment]
Also for comparison, it takes me about 45 minutes as a geneticist to get all existing powers.

**Comment by 9600bauds** [comment]
Good point, we should add more empty blocks

**Comment by ghost** [comment]
Ebin. :^)

**Comment by ghost** [comment]
Horror form should broadcast in a large range, but certainly not in world

Something huge like 50-100 ought to do it

**Comment by Intigracy** [comment]
;_;7

https://github.com/vgstation-coders/vgstation13/pull/18584

**Comment by DamianX** [comment]
It's still a `to_chat(world`

**Comment by Intigracy** [comment]
I misread this issue.

**Comment by DeityLink** [comment]
Honestly I see it as something akin to Pudge's ult in Dota. It's pretty much a feaaature.
