### ISSUE TITLE
AMAZING PDA SUGGESTION

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8139]
Nobody used PDA terminals right? PDAs are also like phones. What if you could buy the ability to use emojis on PDA? We could have our own custom space emojis like clown wig and mask (for honks), 4noraisins (when you get brigged), stethoscope (when you're telling a friend you're in medbay), chaplains bible, and other space related things.

Also who doesn't love the bragging privileges of having emojis? Centcomm would be rich if they implemented this in their PDA terminal stores. Not like anyone buys snake or minesweeper.

**Comment by WeinerMaster69** [comment]
Dumb but I like it.

**Comment by icantthinkofanameritenow** [comment]
That's retarded enough to work.

**Comment by xevonix** [comment]
🎆🎇please i need more emojis in my life🎉🙆 i vote yes ✨👽👌

**Comment by Exxion** [comment]
That is so fucking stupid but also fantastic :+1: :heavy_multiplication_x: :100:

**Comment by Killette2** [comment]
We also can't forget the grey alien emoji

**Comment by 9600bauds** [comment]
We have some neat PDA shit that nobody ever uses because you need to buy them.
Port Snake to the arcades when?

**Comment by ghost** [comment]
Why does a PDA game cost more than the supermatter shard.

**Comment by clusterfack** [comment]
Because you don't actually think any price in this fucking game is balanced do you?

**Comment by Imagebard** [comment]
Why the fuck do we even have baystation money if we don't have any way to support it in any way other than deducting miners money and giving it to other crewmembers?
We need some automated way to do it.

**Comment by Kitfox88** [comment]
I support this, spamming meme emojis at the AI would own :100: :100: :100: :100: :100: :100:

**Comment by BestName** [comment]
:ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy:

**Comment by xpcybic** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by PJB3005** [comment]
You know I'm unsure if adding this is even possible without being terrible and 100% java script dependant.

**Comment by ihadtoregisterforthis** [comment]
:hand: :expressionless: :ok_hand:

**Comment by Killette2** [comment]
Any progress fams?

**Comment by Probe1** [comment]
It's probably not possible and the only person who might have coded it is permabanned.
