### ISSUE TITLE
Killed MoMMIs delete their items

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8142]
Killed a MoMMI and the plastic bag that was on it's head with items I wanted got deleted once it blew up.

**Comment by clusterfack** [comment]
>Killed a MoMMI


You deserved it, you monster

**Comment by 9600bauds** [comment]
Fuck MoMMIs

**Comment by ghost** [comment]
He had my objective item, I told him I need it first. Fucker just ran.

**Comment by clusterfack** [comment]
If a mommi was carrying around an objective item that could be a cause for concern in itself

**Comment by 9600bauds** [comment]
I'm a bit concerned here about the plastic bag having items while worn, last time I tried as a human I couldn't put the plastic bag on my head unless it was completely empty

**Comment by clusterfack** [comment]
The mommi head slot isn't a real head slot

**Comment by ihadtoregisterforthis** [comment]
Don't remove the ghetto crab backpack, add a drop thing to them. I believe anything on their claws gets deleted too.

**Comment by AutismSpider** [comment]
when a mommi dies items in the claw slot or head poof into null void.

Should of ahelp to get the mommi job ban then killed it though.

**Comment by Exxion** [comment]
Also if a human gets exploded hard enough a lot of their shit gets nullspaced
I think everything except ID and some clothes

**Comment by Killette2** [comment]
The only objective object a MoMMI should have would be the blueprints, any other objective tier item it having is shit.

That and don't MoMMI blueprints already exist?

**Comment by ghost** [comment]
It had the hand teleporter, which in all fairness is fine if it actually made a blueprint and copied it then returned it.

**Comment by AutismSpider** [comment]
mommis cant use the CE blue prints any way only other thing it grab is the hypo or hand tele you can make copys of any way hand tele i mean

**Comment by Killette2** [comment]
Why would a MoMMI grab a hypo though?

**Comment by gbasood** [comment]
Most items can't be picked up by MoMMIs. This is mostly to prevent MoMMI's built-in tools from dropping on death. Could prob be easily fixed though
