### ISSUE TITLE
Soap cannot clean microwaves

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8144]
(WEB REPORT BY: skowron REMOTE: 158.69.55.2:7777)
This is a problem.

**Comment by SysadminJeroen** [comment]
[it's a featurrreeeeeee] [notabug]?

Whenever I try to clean a microwave with a bar of soap it says that it is too dirty.

**Comment by SysadminJeroen** [comment]
[honk]

**Comment by ghost** [comment]
No shit it's too dirty it's not got soap used on it yet, duh!

**Comment by Shadowmech88** [comment]
I'm going to guess that the microwave thinks you're trying to put the soap in as an ingredient, rather than clean it.

**Comment by 9600bauds** [comment]
No, the microwave is literally hardcoded to only accept space cleaner I think

**Comment by Shadowmech88** [comment]
Yeah but is it hardcoded to recognize that you're using a cleaning item that isn't space cleaner and specifically reject that cleaning item with a special message?
I think it's just trying to put the soap inside the microwave because of the fact that it's coded to only be cleanable with space cleaner.

**Comment by 9600bauds** [comment]
Well, yes, that

**Comment by ghost** [comment]
I mean this could be done with a simple or, but we should really have a proc or something for cleaning items.

**Comment by ghost** [comment]
Soap cake when?

**Comment by 9600bauds** [comment]
When you sprite it

**Comment by ghost** [comment]
Challenge accepted, but delayed as I don't have photoshop on this computer, paint only final destination

**Comment by ghost** [comment]
Also, what the heck would a soap cake look like? We've already got cakes that look like soap cakes

**Comment by 9600bauds** [comment]
When you sprite it

**Comment by ghost** [comment]
baudypls

**Comment by PJB3005** [comment]
The microwave rejects ANYTHING for cleaning EXCEPT SPRAY BOTTLES WITH THE NAME "Space Cleaner".

Whether the bottle has to even be filled might not even matter.

**Comment by 9600bauds** [comment]
No, that was fixed a while ago
