### ISSUE TITLE
Calling an ERT should be logged and given reason

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8145]
(WEB REPORT BY: cptwad REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

a764855d41dc6638fe9ddcc8507240dd87e11389 

> General description of the issue

Calling an ERT isn't logged, least it isn't in the chat. Additonally when calling in the ERT you should be able specify a reason, that way admins, or the ERT directly get told what they were called for

**Comment by ghost** [comment]
Makes sense :+1:

**Comment by CptWad** [comment]
@Cptwad so I can monitor the shit I make

**Comment by Shadowmech88** [comment]
Furthermore I think that ERT members, when they spawn, should receive a message that explicitly tells them that they don't magically know what's going on in the station outside of whatever's in the ERT Request message. If whoever calls the ERT doesn't mention a vampire on the station, then the ERT doesn't know there's a vampire until they see it.

**Comment by CptWad** [comment]
Exactly the idea
