### ISSUE TITLE
Defficiency's disposal mailing system

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8146]
it's pretty broken. (NOTE: i tested this on the test server)

when using a destination tagger on a parcel, using the following tags:

**_come back to cargo:**_
engineering
CE office
RD office
library
theatre
telecomms
mechanics
telescience

**_wrong destination:**_
cargo bay: goes to mechanics
chemistry: goes to CE office

all the rest seems ok.

side note: can't understand why there is a "Disposal" tag.

**Comment by CptWad** [comment]
@Duny-

**Comment by Duny-** [comment]
Fuck disposals it never works
I'll take a look, thanks for the thorough testing

**Comment by Kitfox88** [comment]
fuk 2 duny

**Comment by Kurfursten** [comment]
I was going to say "it probably isn't even Duny's fault with all these mappers who don't understand how disposals works" but his comment is making me suspicious that for once it actually is his fault.

BYOND message me if you need help

**Comment by ihadtoregisterforthis** [comment]
I don't think anyone but Duny has map priority over deff.

**Comment by PJB3005** [comment]
Add the janitor to that list.

**Comment by Duny-** [comment]
It's not my fault Kurfursten disposals as always had problems, I just thought I fixed them like 3 times now
