### ISSUE TITLE
Test server lags after a while

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8148]
After about half an hour into a round the test server starts lagging to the point of unplayability.

**Comment by ihadtoregisterforthis** [comment]
To add to the test server unplayability, all lights start on as usual but they don't emit any light. Complete darkness until the room bulbs are updated.

**Comment by clusterfack** [comment]
Something is wrong with btime on that server

**Comment by SysadminJeroen** [comment]
I have noticed the same.
Not sure if it is related, but whenever the Supermatter Crystal explodes, you'll see a lot of **BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES _Killing process..._ BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES BRILLIANT FLASHES** _connection failed_

I thought that it may have been related to the timing as it seems to either spawn too many so the server dies, or gets stuck in a loop.
