### ISSUE TITLE
Humans with less than two hands still show both hands in their sprite when laying down (maybe also requires being pulled?)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8149]
(WEB REPORT BY: pwirby REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> If somebody lost one/both hand, when he's been dragged while resting/being on the floor in side view, it sprite show he have hands.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by ghost** [comment]
Ah, I know what's causing this and I don't think it can be fixed without a complete re-do of all the existing sprites.

The hand is not sprited over on these clothes but when you lose the hand the torso is not sprited over either.

It's fixable but would be incredibly tedious and nobody would ever do it.

**Comment by clusterfack** [comment]
A lying down sprite is literally a rotated version of the standing sprite. This is pretty fixable. I'd just need to find the code that handles making a hand not show up.

**Comment by ghost** [comment]
No, clusterfack, you don't understand what I said.

**Comment by ghost** [comment]
If a hand is removed that removes the hand, sure, but the clothes are sprited with space for hands. What is seen as a hand is actually just a torso shaped like a hand in the clothing sprite.

**Comment by clusterfack** [comment]
Does it not work while standing?

**Comment by ghost** [comment]
Nope.

**Comment by nervere** [comment]
Unfortunately, this doesn't have any good solution unless someone's willing to resprite hundreds of jumpsuits.
