### ISSUE TITLE
Robot limbs are named incorrectly

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#8151]
The left arm is called "robot right arm" and the right arm is called "robot left arm".
Same applies to the legs.

**Comment by 9600bauds** [comment]
Just the items? Was this for a borg chassis construction, or giving someone a borg arm? Are you sure you didn't get THEIR right mixed up with YOUR right?

**Comment by BestName** [comment]
The items. For borg chassis construction, don't know if it affects prosthetic surgery and yes I'm sure.

**Comment by ihadtoregisterforthis** [comment]
Remember that the sides are relative to the character when it's looking south.

**Comment by BestName** [comment]
I'M SURE!

**Comment by gbasood** [comment]
Looks the same as it always has to me.

**Comment by BestName** [comment]
That's because it's always been wrong

**Comment by PJB3005** [comment]
Yes, this ALWAYS BOTHERED ME.

IRL "left" arm, "left" leg, ... are always from the subject's point of view, not the other way around.

**Comment by BestName** [comment]
But not enough to do something about it? :unamused:
