### ISSUE TITLE
Delivery chute

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8152]
(WEB REPORT BY: pwirby REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Delivery chute don't seems to work anymore
> 
> What you expected to happen
> To work normaly and send the crate where they are supposed to go
> 
> What actually happened
> Go in the recylcing room instead of the desired location
> 
> Steps to reproduce if possible
> Wrap a crate tag it, put it in the delivery chute thing and wait for it to not work

**Comment by ihadtoregisterforthis** [comment]
Needs information about the map

**Comment by Exxion** [comment]
Just yesterday I received crates through disposals

I mean only one of them was actually supposed to go to me but that's user error (putting multiple crates in at once)
