### ISSUE TITLE
After using the Dissolve power, players can understand Vox language (possibly other languages, too)

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8153]
(WEB REPORT BY: jeanvoerman REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8599c553d9640d7b87f615da578106d4ae746240
> 
> General description of the issue
> Gaining language after dissolving
> 
> What you expected to happen
> Turn into a skeleton
> 
> What actually happened
> After a human used Dissolve from genetics and turned into a skeleton he could understan vox. 
> 
> Steps to reproduce if possible
> Dissolving

**Comment by Exxion** [comment]
This is fixed
