### ISSUE TITLE
LOCAL AI EXPOSES FAXING SECRETS, TELESCIENTISTS HATE HIM

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8154]
(WEB REPORT BY: vikenz REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8599c553d9640d7b87f615da578106d4ae746240 
> 
> General description of the issue
> I removed paper from the fax as the AI and it teleported into the core
> 
> What you expected to happen
> For it to not teleport into the core
> 
> What actually happened
> The telescience guys cried
> 
> Steps to reproduce if possible
> Ruin people's faxes

**Comment by 9600bauds** [comment]
Reminds me of when AIs could harvest plants into their core

**Comment by ghost** [comment]
:+1: requesting it's a feature tag, AIs are capable of blue space teleportation

**Comment by Shadowmech88** [comment]
> malf AI
> much of the station is destroyed
> a dying IAA attempts to call an ERT via fax
> paper vanishes out of the fax machine
> plasmafire

Could be made into a very cheap malf module.
