### ISSUE TITLE
Cultist Teleport with black screen and no body

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8155]
(WEB REPORT BY: sluko REMOTE: 158.69.55.2:7777)

> Revision 1ad2552cc22207ebb8b0f00bd32b6c38f1b72cal
> 
> General description of the issue
> So I was arrested by a security officer, I believe still being pulled around by him while being a convert. The cultist then tried to teleport me somewhere and all I got was a black screen. After relogging multiple times all I could do was open my inventory, change intent and targetting and that was really it. Nothing from in-game could be interacted with; LOOC, say, etc. couldn't be used but I still heard a cultist portraying his/her voice into my head. After trying to get help I ghosted only to find out that I no longer have a body. I'm not sure if this is a bug or if the cultists fucked up and ripped my body into non-existence. Additionally, I assume they were trying to teleport me to their base.

**Comment by ghost** [comment]
Sounds like nullspace

**Comment by Exxion** [comment]
Nullspace, but how?
I seem to recall that long ago there was an issue just like this, but it got closed because they never managed to reproduce it. Spooky.

**Comment by gbasood** [comment]
``` DM
to_chat(T, visible_message("<span class='warning'>[cultist] suddenly disappears in a flash of red light!</span>"))
```

``` DM
to_chat(T, visible_message(
```

What the fuck is this code

**Comment by 9600bauds** [comment]
ahhhhahahahaaaahahhaa

**Comment by gbasood** [comment]
I mean it's not runtiming, somehow. But what the fuck

**Comment by clusterfack** [comment]
I guess if visible message doesn't have a return value it's technically not going to break everything

**Comment by gbasood** [comment]
What I'm wondering is this.
Currently, the code does `cultist.loc = src.loc` (src being the `/obj/effect/rune/`)
Is there a situation where the rune would be qdel'd before the cultsummon proc was executed?

**Comment by PJB3005** [comment]
Yes, that's possible if the qdel comes first.

**Comment by gbasood** [comment]
It doesn't
I have no idea why this happens
Someone needs to try to reproduce this.

**Comment by Exxion** [comment]
I have an idea
I'll look at it tomorrow

**Comment by MadmanMartian** [comment]
I believe this was fixed a few times over
