### ISSUE TITLE
Captains armor no longer counts as a hardsuit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8156]
(WEB REPORT BY: carshalash REMOTE: 158.69.55.2:7777)
When attempting to put on the captains armor along with the helmet I found out that it no longer counts as a hardsuit when it comes to being in space. I was taking pressure damage and tested a few times to see what was going on as to whether it was an issue with gloves/shoes as it was reported things would be happening with them soon. I can verify that it is 100% broken at this point and mostly just counts as armor.

**Comment by 9600bauds** [comment]
@DrCelt

**Comment by Exxion** [comment]
@DrCelt YOU SAID YOU FIXED THIS

**Comment by ihadtoregisterforthis** [comment]
:warning: this is loose :warning:

**Comment by mikecari** [comment]
Petition to remove celt 5ever where?

**Comment by ghost** [comment]
Remove tags HATE FUN

**Comment by ghost** [comment]
As far as I understand the bug, Technically the armour counts as a hardsuit, it's the helmet which causes the problem. Though I may be wrong on that score, don't quote me on it.

**Comment by AutismSpider** [comment]
both the suit and helmet count as a hard-suit for space use what did you do this time?

**Comment by ghost** [comment]
Ah see the helmet doesn't cover the face.

**Comment by AutismSpider** [comment]
better unfuck the SWAT helmet to then its part of red space suit set.

**Comment by PJB3005** [comment]
Isn't the real issue that the captain's spacesuit is a subtype of body armour snowflaked into being space-viable instead of a subtype of regular space suits?

**Comment by ghost** [comment]
That too

**Comment by Shadowmech88** [comment]
Why would someone even make it like that in the first place? Wouldn't it be easier to give a hardsuit damage resistances than it would be to make body armor space-worthy?

**Comment by Exxion** [comment]
Don't even bother questioning oldcode. You rarely get answers and when you do get them they usually just make you more confused.

**Comment by 9600bauds** [comment]
I hope you haven't had this fixed for 12 hours but are keeping us waiting for a non-atomic six fix PR

**Comment by ghost** [comment]
Nah I just couldn't get around to it.
