### ISSUE TITLE
Crew monitoring computers not working with larger map size

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8157]
(WEB REPORT BY: durgen REMOTE: 158.69.55.2:7777)
http://imgur.com/T7GGUWr

I expected the indicators on the crew monitoring computer to be alligned with the station map

But they are transposed down and to the left

Use a crew monitoring computer to replicate.

**Comment by clusterfack** [comment]
This is due to the fact the crew monitoring computer map's icon size is the the size of the old map

**Comment by 9600bauds** [comment]
I hope these tags are appropriate to describe the problem

**Comment by ghost** [comment]
They're not

**Comment by Ephx1** [comment]
We need a general "Crew Monitor" tag because of how broken it is.

**Comment by ihadtoregisterforthis** [comment]
We need a [other] tag.

**Comment by ghost** [comment]
It's an oversight, and an issue with box, but it's not a map issue with box.

**Comment by 9600bauds** [comment]
I guess the minimap images could be construed as sprites, and this is an issue with all maps, so I guess

**Comment by ihadtoregisterforthis** [comment]
Also this applies to various z-levels

![minimap_5](https://cloud.githubusercontent.com/assets/13305885/12903738/c51b8cd4-cea8-11e5-929e-d75d5f11cf2d.png)
![minimap_6](https://cloud.githubusercontent.com/assets/13305885/12903758/e5b6cf6c-cea8-11e5-81fc-6a55720973b0.png)

**Comment by ghost** [comment]
I'm going to guess the problem is that the minimap is trying to generate a 255x255 image

**Comment by gbasood** [comment]
``` DM
generateMiniMap(z)
/proc/generateMiniMap(z, x1 = 1, y1 = 1, x2 = world.maxx, y2 = world.maxy)
```

Not so sure about that

**Comment by clusterfack** [comment]
Silly silly people,

It's because of this file https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/html/mapbase1024.png

Someone needs to increase the map base from 1024x1024, to whatever x whatever with that pregenerated space background image for the new map size.

**Comment by 9600bauds** [comment]
Let's do it, I have a bet to win

**Comment by clusterfack** [comment]
Alright I'll try a few things, I was percolating on some ways to fix it

**Comment by 9600bauds** [comment]
You da bess

**Comment by 9600bauds** [comment]
Any luck on fixing it? Any way I could help?
