### ISSUE TITLE
DNA Injectors don't work on monkeys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8161]
(WEB REPORT BY: themegagoat REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8275f12992985d970ee3c664567976f13ba50d71
> 
> General description of the issue
> Monkeys don't become humans when injected with full DNA injectors taken from humans, or really any kind of DNA injector that should make them human.
> 
> What you expected to happen
> Inject monkey, monkey becomes human.
> 
> What actually happened
> The monkey stayed a monkey.
> 
> Steps to reproduce if possible
> Inject a monkey with a DNA injector you get from any old human

also celt's a fag

**Comment by Shadowmech88** [comment]
I would be remiss if I did not ask whether you made sure it was an SE injector and not a UI injector.
