### ISSUE TITLE
GENETIC INJECTORS ARE NOT WORKING PANIC

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#8163]
Closes #8161
All SE injectors are doing nothing it seems, last thing to touch genetics code was noirblock so rip

**Comment by LordMyroc** [comment]
I just used an SE injector an hour or two ago and it worked fine. Noirblock had already been merged by that point.

**Comment by DrCelt** [comment]
If this IS the fault of noirblock, which I won't rule out, it is likely to be more so a fault of oldcode going awry than the addition of a new feature

**Comment by 9600bauds** [comment]
Did you check an older PR to see all the accommodations done for a new Genetics block

**Comment by DrCelt** [comment]
@9600bauds Could you show me an example of one of those? I tried comparing to

**Comment by 9600bauds** [comment]
I would have cited that same one, actually, no clue what could be the issue though

**Comment by clusterfack** [comment]
That PR didn't even work though

**Comment by 9600bauds** [comment]
Oh

**Comment by gbasood** [comment]
Injectors don't work
Genetics consoles don't work
GENETICS DOESNT WORK

**Comment by CptWad** [comment]
![disstressed dolphin](https://cloud.githubusercontent.com/assets/3959840/12910132/7aed8b9e-cebc-11e5-90d6-c4d3e980d9a6.gif)

**Comment by CptWad** [comment]
Was it fixed?

**Comment by Zth--** [comment]
Noir effect was reverted so yes

**Comment by clusterfack** [comment]
Assuming of course the revert fixed it :wink:
