### ISSUE TITLE
You only need a helmet to not get fucked by kpa

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#8167]
Yeah, basically this. If you're wearing a suit helmet you won't receive any pressure damage (but coldness still works). I guess same happens if you have a suit but no helmet

**Comment by 9600bauds** [comment]
SOMEHOW, #6747 has returned

**Comment by Exxion** [comment]
I blame @DrCelt

**Comment by 9600bauds** [comment]
that's why I said SOMEHOW

**Comment by Zth--** [comment]
If I'm not wrong, celt touched cold code which is the one that is actually working.

**Comment by ghost** [comment]
... what

**Comment by ghost** [comment]
`  
var/obj/item/press_protect = get_body_part_coverage(FULL_HEAD)

```
if(press_protect)

    equip_difference += press_protect.pressure_resistance * PRESSURE_HEAD_REDUCTION_COEFFICIENT

press_protect = get_body_part_coverage(FULL_BODY)

if(press_protect)

    equip_difference += press_protect.pressure_resistance * PRESSURE_SUIT_REDUCTION_COEFFICIENT
```

`

**Comment by ghost** [comment]
I hate oldcode.

**Comment by ghost** [comment]
Although, this actually is what is causing #8156 - so pros and cons, I'd say.

**Comment by ghost** [comment]
or at least I think it is

**Comment by ghost** [comment]
okay this SEEMS to have been before my time. You can check an older repo to make sure but I don't think it's my fault. More than willing to take credit for it if it is though

**Comment by ghost** [comment]
As far as I understand it. If you have a helmet that covers the full head, such as the ERT medical one, with a pressure resistance of 20265, it would provide you, on its own, up to an 8106kpa difference.

Ironically, the suit does not provide you with this, as it is required to cover the entire body, including the head, which no suit covers.

**Comment by 9600bauds** [comment]
I thought it was fixed at some point though

**Comment by ghost** [comment]
*shrug, perhaps it was and something I did exposed it. You can check though, I guess. Come back to me please I want to know too because that means I'm not at fault here

**Comment by ghost** [comment]
Anyone test it?
