### ISSUE TITLE
You can staff of change mice

### ISSUE THREAD

**Issue by Arthurdentist** [d3athrow/vgstation13#8168]
Steps to reproduce:
Acquire Mouse
Shoot it with your mighty wizard staff
Admire your new squeaky catbeast

You didn't used to be able to do this but now that you can it has terrible and far-reaching consequences.

**Comment by Shadowmech88** [comment]
I don't see this as a bad thing. The staff of changed mice are no more likely to cooperate with the wizard than the crewmembers are, and if they tear him to pieces then it'd be his own fault for changing them.

**Comment by Killette2** [comment]
I like this. Don't you remember Cinderella where the mice became horses or something? Makes sense, it's magic.

**Comment by Arthurdentist** [comment]
![cinderella s_carriage_close](https://cloud.githubusercontent.com/assets/6353372/12903826/9aec3bba-cec2-11e5-8b21-95064d00ade4.jpg)

Replace the Carriage with a Firebird and the Horses with Xenomorphs and sure.

**Comment by AutismSpider** [comment]
the xenomorphs/slimes would face fuck the wiz to death

**Comment by ihadtoregisterforthis** [comment]
![wizard carriage](https://cloud.githubusercontent.com/assets/13305885/12905104/26de7d64-ceb3-11e5-9477-4524a15c6429.jpg)

**Comment by CptWad** [comment]
:100: / :100:

**Comment by d3athrow** [comment]
This is literally a feature, staff of change affects every mob type.
