### ISSUE TITLE
Borgs can't use sec camera console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8171]
(WEB REPORT BY: kavlax REMOTE: 158.69.55.2:7777)

> Revision 2d9b868dcfa2c9fab704634d5cd7090cdcc987a2 
> 
> General description of the issue
> Use the sec cam console as a borg, selecting a room from the dropdown doesn't change your perspective to that room.
> 
> What you expected to happen
> Start looking at that room.
> 
> What actually happened
> Viewpoint doesn't change.

**Comment by Shadowmech88** [comment]
Tested locally, worked fine for me.
