### ISSUE TITLE
[Box] Arrival Shuttle Hallway Vent Pump #2 starts off

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8174]
Arrival Shuttle Hallway Vent Pump #2 starts off
Description of the issue: Arrival Shuttle Hallway Vent Pump #2 starts off
To reproduce: go to Arrival Shuttle Hallway Vent Pump #2, it will start off

**Comment by Exxion** [comment]
What is with weird instances of atmos things in Box arrivals?

**Comment by CptWad** [comment]
its a mystery
I remember when it even was its own contained pipe system, unattached from the main system along with sci/med

**Comment by FudgePucker** [comment]
Having a separated air system for arrivals might be a good idea. People who late join would be able to access basic tools maint and pods if plasma is flooded

**Comment by Exxion** [comment]
If Arrivals is flooded the round is basically over anyway

**Comment by CptWad** [comment]
Usually arrivals gets depressurized, thats why it not being connected was bad, because it would never get fixed.
Thankfully when that pipe crawl update got merged mommis found most of the missing piping on their own and it got fixed

**Comment by ghost** [comment]
Arrivals behaves very oddly atmospherics-wise. Don't know what's up with that

Also we really need to do something about those offline vents and scrubbers. Maybe use a subtype instead of instances, because outside of copying existing vents and scrubbers it's impossible to tell which to pick

**Comment by ihadtoregisterforthis** [comment]
How many zones is arrivals? There are like four air alarms in there
