### ISSUE TITLE
The way the Mancrowave was mapped in

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8178]
is an issue

![mspaint_2016-02-09_01-23-22](https://cloud.githubusercontent.com/assets/6526157/12907578/c48e47b6-cecb-11e5-935e-c8a88b8bf250.png)
![mspaint_2016-02-09_01-23-09](https://cloud.githubusercontent.com/assets/6526157/12907579/c4acd938-cecb-11e5-9f6d-76c7f632c273.png)
![firefox_2016-02-09_01-24-28](https://cloud.githubusercontent.com/assets/6526157/12907594/e95e5a5e-cecb-11e5-9be6-f6b38d030c17.png)

**Comment by Exxion** [comment]
Also it's in a shitty and unintuitive place on Deff

**Comment by 9600bauds** [comment]
Also while we're at it that closet probably shouldn't go UNDER the pump

**Comment by 9600bauds** [comment]
I can't believe I didn't accidentally press that in mobile sooner

**Comment by Shadowmech88** [comment]
I believe the closet goes under the pump on purpose, so it's easy to access the pump with the closet there. Not like it matters, I haven't ever seen anyone use that pump.

Has cryo been affected by the fact that it's now only got one oxygen tank instead of two?

**Comment by PJB3005** [comment]
You can actually get that pump under the closet by pulling the closet and pushing it on again.

But really we should move that pump to a more intuitive place.

**Comment by ghost** [comment]
Why is literally everything besides blankets so shit about hypothermia.

**Comment by ghost** [comment]
Just change the T-pipe into a corner pipe

Unless you want to fix it by expanding Medbay again. In which case good luck
