### ISSUE TITLE
Alium larva is spawning without a ckey in it

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#8181]
Use create antagonists
make aliums
ghost around the station and see that there's larva on the ground but no ckey in it

**Comment by gbasood** [comment]
> Create Antagonists

Oh good there's no possible way this was my fault then, I didn't even touch that part of code :+1:

**Comment by CptWad** [comment]
![ckey](https://cloud.githubusercontent.com/assets/3959840/12909990/371dda00-cebb-11e5-94d1-6ab7a2d24aba.png)
I kept forgetting to make this issue, rip

**Comment by 9600bauds** [comment]
Dupe of #6968
