### ISSUE TITLE
Taxistation (Delivery System Bug "lost in space")

### ISSUE THREAD

**Issue by ziz11** [d3athrow/vgstation13#8183]
Taxi station
Delivery System -> Sending Untagged Mail/package -> Won't Return and Stuck here in space area.

[http://imgur.com/a/sS3Av](url) (mirror)

![explain](https://cloud.githubusercontent.com/assets/17143348/12918806/0e9d1310-cf52-11e5-811f-ce1a13df7dc8.jpg)
![View](https://cloud.githubusercontent.com/assets/17143348/12918805/0e971154-cf52-11e5-8982-57d6690da048.jpg)
![Place](https://cloud.githubusercontent.com/assets/17143348/12918839/54659994-cf52-11e5-8ea0-c8ad7420c476.jpg)

/////

Second one little thing - Admin shuttle has no docking port specified.

**Comment by 9600bauds** [comment]
That's hilarious.

**Comment by DamianX** [comment]
Taxi is ded.
