### ISSUE TITLE
Right clicking a job priority in the job preferences should lower said priority.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#8184]

**Comment by Exxion** [comment]
:+1:

**Comment by ihadtoregisterforthis** [comment]
I thought this was broken, not unimplemented

**Comment by d3athrow** [comment]
cant get it to work in byond, works fine in firefox and IE though

**Comment by clusterfack** [comment]
I thought you could do this currently with either control click or shift click or something

**Comment by d3athrow** [comment]
so it wasn't that the clicking wasn't working whoever set it up didnt make it use the defined levels, but now there's an issue of it not working at all. it will set to low but nothing else
