### ISSUE TITLE
Can we PLEASE steal TG's method of stingaling targeting?

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8185]
Selecting a target from an input window is just absolutely awful. The way it works on TG (or at least how it worked when I last played there long ago) is that you select a sting in advance then middle click your target to actually sting them. This is vastly less awful.

**Comment by Shadowmech88** [comment]
Doesn't middle click already do something different on our server?

**Comment by Exxion** [comment]
I don't know, but we can just use a different shortcut

**Comment by clusterfack** [comment]
It's weird we never had spell channeling in the first place desu

**Comment by BestName** [comment]
@Shadowmech88 middleclick switches hands

**Comment by mikecari** [comment]
@BestName 
Just use x to switch hands then.
Christ, I never even use middle click for hand swapping, its way too clunky.

**Comment by ihadtoregisterforthis** [comment]
Don't let this become a hotkeys/no-hotkeys argument, because moving with WASD is for fags.

**Comment by Exxion** [comment]
Who even cares what button/key/key combo it is? It could require half the keyboard at once and it would still be better than our current system.

**Comment by mikecari** [comment]
@ihadtoregisterforthis 

> moving with WASD is for fags

Clearly you've never played Doom then.

**Comment by gbasood** [comment]
moving with WASD in spess is awful, though

**Comment by clusterfack** [comment]
Hotkeys is objectively the best way to play ss13

**Comment by Shadowmech88** [comment]
Clearly we need a server vote to settle this.

**Comment by gbasood** [comment]
Vote on hotkey toggle usage
![](http://i.imgur.com/cTw9XIF.png)
Wow that's a lot more than I thought, maybe I need to git gud and use hotkeys

**Comment by Exxion** [comment]
Hotkeys are really good

**Comment by gbasood** [comment]
I always found that input windows got in the way of the game window which fucked me over more often than not, personally

**Comment by Exxion** [comment]
But you only leave the input window open briefly anyway.

**Comment by ihadtoregisterforthis** [comment]
> ![rigged vote](https://cloud.githubusercontent.com/assets/13305885/12964986/d7db12b0-d031-11e5-9941-6dd7d7feb491.png)

Don't remove middle click.

**Comment by gbasood** [comment]
This vote was for using middle click to switch hands a hotkey-using player.
![](http://i.imgur.com/b7o0Ps9.png)
Do remove middle click.

**Comment by mikecari** [comment]
ok so remove middle click, use x to switch hands, use middle click for stings.

Can we agree or?

**Comment by ihadtoregisterforthis** [comment]
I disagree

**Comment by Boxe** [comment]
why not us X for stings and leave M3 alone

**Comment by Exxion** [comment]
Because that's stupid

**Comment by ihadtoregisterforthis** [comment]
The game allows either using the arrows to move and typing enabled, or moving with WASD and tabbing to type.
Removing a hotkey for arrow users only because the WASD players can use X too, and only for a single gamemode doesn't seem like justified enough.

**Comment by Shadowmech88** [comment]
Why not make it hotkey-based? As in, if you've got hotkeys enabled, middleclick is the sting button. If you don't have hotkeys enabled, X is the sting button.

That way everyone gets to keep the hand-switching key that they're used to.

**Comment by Exxion** [comment]
That works
Or middle click could only be the sting button if you have a stinger prepared
Or both

**Comment by gbasood** [comment]
@Shadowmech88 's idea works best I think
