### ISSUE TITLE
Apparently pizzas can hold an unlimited number of items which are all released in a huge, ridiculous pile when the pizza is sliced

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8187]
I didn't think to screencap it but someone did personally show this to me so I know it happens

Also this:
![image](https://cloud.githubusercontent.com/assets/9827785/12924310/68c2b974-cf27-11e5-958e-71a79a6d5575.png)

**Comment by 9600bauds** [comment]
Splendid

**Comment by Exxion** [comment]
Fuck
I forgot to mention that she also told me she once hid the _FUCKING NUKE DISK_ in a pizza

Although now that I think about it that's not really a problem
But it is exceptionally silly

**Comment by CptWad** [comment]
Quantum storage pizzas

**Comment by Shadowmech88** [comment]
Of all the food items you can hide things in, pizza makes the least sense. It's less than half an inch thick.

**Comment by CptWad** [comment]
@Shadowmech88
https://www.youtube.com/watch?v=5M1zOnKpzFk

**Comment by ghost** [comment]
I think the best part is you can store a pizza inside a pizza.

**Comment by 9600bauds** [comment]
That's it, feature

**Comment by clusterfack** [comment]
Who puts in this stupid shit without the rest of us realizing?

**Comment by 9600bauds** [comment]
Oldcode, probably

**Comment by Shadowmech88** [comment]
I believe that any slicable is given the ability to hold items. Bread, cake, cheese wheels, etc.

**Comment by Imagebard** [comment]
I also believe they have the same issue described here. The only thing they can't hold is a item that will slice it.

**Comment by ghost** [comment]
@clusterfack 

You have no idea how much stupid shit is already in. I knew about this one for a long time but I don't report harmless fun bugs.

**Comment by clusterfack** [comment]
Thanks for your selectively useless help

**Comment by ghost** [comment]
There's so many actually important and reported bugs that haven't been fixed for ages.

**Comment by clusterfack** [comment]
Oh? I don't really think there are many bugs fitting that categorization at all.

**Comment by Shadowmech88** [comment]
I knew about putting food inside other food, but I didn't even think it was a bug. I thought it was common knowledge.

**Comment by clusterfack** [comment]
Not necessarily a bug just an extremely poorly thought out deature

**Comment by Exxion** [comment]
The issue here isn't putting things in food, because that's cool, etc.
The issue here is putting _an unlimited number of things_ in food
I was shown this using a pizza containing, among many other things, a flare, the entire contents of a Groans machine (I think), and what I believe was every spare bedsheet on the station.

**Comment by Shadowmech88** [comment]
What would be a good limit on the number of things that can be in one food item? Five?

**Comment by Exxion** [comment]
Probably max combined w_class of like... 3. So 3 tiny items, a small item and a tiny item, or a normal-sized item. No bulky or huge items.

**Comment by d3athrow** [comment]
rip cheesewheel gameshows

**Comment by ghost** [comment]
Simply use the storage code. If combined w_class is above something small like 10 to 20, no more items

It's a pizza, not a bluespace portal. Although no-one will mind if you had a bluespace tomato pizza recipe for the purpose of bluespace storage
