### ISSUE TITLE
Russian Revolver is broken

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#8188]
http://puu.sh/n1NQS/4f43dcaadb.png

then, after someone finally suicided with it (it took like 20 more attempts) I could shoot AGAIN even though It had no bullets http://puu.sh/n1O62/60ae97479b.png

**Comment by gbasood** [comment]
Honestly not sure why revolvers don't handle ammo in a different way than most guns.
How I'd like it to work (but am currently too tired to implement:
- Spinning places the 'active' chamber at a random point
- Firing increments the active chamber by 1 on either success or failure

Alternatively if you want to get crazy, just store all those bullets in a list and pop the first entry out and place it at the end when you fire

**Comment by Exxion** [comment]
`chambers.Add(chambers.Cut(1, 2))`

Actually that's pretty neat
Have a list of references/null variables and have it fire/attempt to fire whatever is in the first position of the list before cycling
And spinning the chamber would just be `chambers.Add(chambers.Cut(1, rand(1, chambers.len)))`
