### ISSUE TITLE
Durand becomes invisible while defense mode is activated

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8191]
(WEB REPORT BY: punishedchiot REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Durand is turning invisible when using the defence mode, only turns visible again when you leave the mech
> 
> What you expected to happen
> Not the thing
> 
> What actually happened
> The thing
> 
> Steps to reproduce if possible

**Comment by clusterfack** [comment]
Fag

**Comment by 9600bauds** [comment]
Is that a code word for fug or

**Comment by clusterfack** [comment]
>It to get fixed

**Comment by Exxion** [comment]
Bad bug report aside, this is 100% true, at least for that round. It was invisible to everyone.

**Comment by 9600bauds** [comment]
edited for the faint of heart

**Comment by clusterfack** [comment]
Its not a bug, it's a feature. Removing it would be a nerf to durands and their emergent cloaking mechanism.

**Comment by 9600bauds** [comment]
Clusterfack you are slowly going nuclear
Please have some tea

**Comment by 9600bauds** [comment]
Unable to reproduce
![dreamseeker_2016-02-10_01-52-34](https://cloud.githubusercontent.com/assets/6526157/12938966/fc8ed9be-cf98-11e5-94ca-0bab8f55aaab.png)

**Comment by clusterfack** [comment]
Try it at different damage levels?

Do they change their sprites when damaged? Pretty sure they do right

**Comment by 9600bauds** [comment]
Nada
![dreamseeker_2016-02-10_01-56-25](https://cloud.githubusercontent.com/assets/6526157/12939016/84240f5c-cf99-11e5-8352-89ee1d098127.png)

**Comment by Imagebard** [comment]
They only changes sprites when completely obliterated. Otherwise the only way to tell the difference is right clicking.

**Comment by CptWad** [comment]
Saw it myself, invisible durand. Maybe I shoulda VV'd though I was busy elsewhere

**Comment by Exxion** [comment]
I have no idea what happened, but at the very least the specific Durand the person who reported this had DID turn invisible when in defense mode.

**Comment by ihadtoregisterforthis** [comment]
Maybe one of those "rub times"?
Maybe it was like #7055 all over again?

**Comment by Exxion** [comment]
No, #7055 is clientside
This applied to everyone

**Comment by Shadowmech88** [comment]
This is still a thing, happened to me twice last round. It happened when I was spamming the "toggle defense mode" verb, and went away if I changed the direction I was facing.

![image](https://cloud.githubusercontent.com/assets/3991927/13646311/7c973f86-e5f4-11e5-939e-31f0e0b5cbad.png)

**Comment by clusterfack** [comment]
Did you ask an admin to VV the icon state ?

**Comment by Shadowmech88** [comment]
I did not, I probably should have.

**Comment by DeityLink** [comment]
Unable to reproduce, must have been fixed somehow.
