### ISSUE TITLE
CMC monitor maps broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8192]
(WEB REPORT BY: xevonix REMOTE: 158.69.55.2:7777)
http://puu.sh/n2pa4/655543fe83.jpg map shows up like this, not sure why, only does this on z level 1 and z level 6.

**Comment by 9600bauds** [comment]
Dupe of #8157

**Comment by PJB3005** [comment]
Dupe

**Comment by 9600bauds** [comment]
2slow

**Comment by PJB3005** [comment]
Wow we hit close at the exact same time.
