### ISSUE TITLE
New taser sound plays when hit by any projectile

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#8195]
>Shoot lasers, bullets or plasma at someone
>bzzzzzzzzzt

@Zth--

**Comment by Zth--** [comment]
Oh fuck I think I reverted a commit and completely forgot about it. I had this stupid bug when testing shit. Well I can't fix it right now, I'll do it tomorrow

**Comment by DrCelt** [comment]
BZZZZZTTT
