### ISSUE TITLE
health analyzer state normal body heat to be dangerous

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8198]
*100% tested*

@DrCelt , you changed the human body default temperature but you completely forgot to update the health analyzer's values, so now they'll report the usual body temperature in red text, and report cold temperatures as if they were okay.

**Comment by DrCelt** [comment]
@Imagebard that's interesting, I could've sworn I changed this.

**Comment by Imagebard** [comment]
I have scanned multiple people with health scanners on the main serbian, body temperature was always in red _italics_ . Should be just blue, like Sol Common.

Either way, I actually had some brain hemorrhage in the middle of trying to make this issue causing it to be delayed for 
Well
About a week or something
Before I remembered it and made a issue here.
If you fixed it since you implemented hypothermia then whoops.

**Comment by DrCelt** [comment]
How odd.

**Comment by Intigracy** [comment]
Nice work celt.

**Comment by Imagebard** [comment]
One day

**Comment by Intigracy** [comment]
One day

**Comment by PJB3005** [comment]
In the mean time Celt gets the tag of shame.

**Comment by DrCelt** [comment]
Still reproducible?

**Comment by Imagebard** [comment]
Just examine a room-temperature human with a health analyzer and see if the text is blue.
Its a cosmetic change but c'mon its a easy one.

**Comment by Imagebard** [comment]
Honk

**Comment by DrCelt** [comment]
I didn't even change any lines of code. You're an eejit

**Comment by Imagebard** [comment]
>I didn't even change any lines of code

Didn't work when I checked it 22 days ago(Yep, same time as that "One Day" comment)
I'm just going to guess the grudge ghosts fixed it.

**Comment by DrCelt** [comment]
pfft
