### ISSUE TITLE
Died as Lizardman for no raisin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8199]
(WEB REPORT BY: punishedchiot REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Heatening up inside hardsuit on the middle of the asteroid, later taking random damage until i died
> Tuesday around 20:32:30 i died
> 
> What you expected to happen
> It to be 100% tested
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Shadowmech88** [comment]
I think it'd be neat to make Unathi cold-blooded, but they're not even normally selectable so it'd be a lot of work for nothing.

**Comment by ghost** [comment]
Ironically, @Shadowmech88 , if I am correct, the reason why this occurs is my rudimentary attempt at making lizard men "cold blooded"

**Comment by CptWad** [comment]
Yeah, lizardmen are working opposite then how they are supposed to, getting cold when warm and warm when cold. shits wack yo

**Comment by d3athrow** [comment]
can confirm heating up slowly while in a hardsuit
