### ISSUE TITLE
Defficiency Random Item spawner needs to be changed

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8200]
As you should know, Defficiency has a random item spawner that randomly places items in maintenance.
Among those items are _traitor items_ and possibly _guns_.

Fun things are fine but directly antagonistic items should be removed.

**Comment by ihadtoregisterforthis** [comment]
>needs to be fixed
But it's not broken

**Comment by Imagebard** [comment]
Really now

**Comment by DrCelt** [comment]
Not a bug!

**Comment by Skullyton** [comment]
Once I was working R&D on deff, and somebody rolled in and passed us not one, but two powersinks!

It was wizard.

@Duny Autolathe in Deff R&D WHEN?

**Comment by 9600bauds** [comment]
Box has this spawner too you know

**Comment by Skullyton** [comment]
Yup, but they're in walls, and there's one, whereas on Deff they're everywhere and there's at least 6 IIRC

**Comment by CptWad** [comment]
@Skullyton its @Duny-
also he will only say no and git gud
I will just say git gud
As for the power sink its relatively rare and nonantags will only turn it in, hell even antags will turn it in for free shit.

**Comment by AutismSpider** [comment]
god damn Desert Eagle  spawn in Deff

**Comment by Skullyton** [comment]
@CptWad Well shit, sorry Dmitri

**Comment by gbasood** [comment]
I don't see a problem with it. If someone is a shitter with the random item they find, they were probably going to be a shitter to begin with.

**Comment by FudgePucker** [comment]
Its a feature.
Spice up rounds more.
Not every round has to be the same shit everytime.

**Comment by Killette2** [comment]
I've never seen a random antag item spawned on box, just the generic costumes and drill that spawn every round.

**Comment by AutismSpider** [comment]
two set spawns for the drill and costume. right side of the ghetto bar there wall with random spawn costume and stuff only antag thing you find in that wall is cam bug is useless with out the tv part for it

**Comment by 9600bauds** [comment]
A guy found a deagle brand deagle once in that spot in Box, that's for sure

**Comment by AutismSpider** [comment]
can find 357 speed loader in that spot to some times

**Comment by Duny-** [comment]
I get your concerns famjam I will change them by moving them to somewhere else on the station next update
![bluethumbsup](https://cloud.githubusercontent.com/assets/5224390/12970442/2f8acba6-d08f-11e5-9bf3-a352a786d9ee.png)

**Comment by CptWad** [comment]
more mobs confirmed

**Comment by AutismSpider** [comment]
So put the bears back in.

**Comment by Imagebard** [comment]
![1323885059111](https://cloud.githubusercontent.com/assets/7571238/12971358/0ef93ba4-d079-11e5-9377-0525f75772cd.jpg)

Here we go

**Comment by Skullyton** [comment]
@Duny- Hey, change the spider in the broken down medbay to a nurse spider, it'll be funny

**Comment by Imagebard** [comment]
>Nurse spiders spawning in the station by default

That would just be another issue with the "OH GOD IT'S LOOSE" label running around.

**Comment by Skullyton** [comment]
I take it you haven't seen the medical shuttle since the baby carp update then, because ho-ly shit

**Comment by AutismSpider** [comment]
like 30 baby carps in the medical shuttle

**Comment by Imagebard** [comment]
I have seen it.
Someone else made a issue about it, didn't they?

**Comment by Skullyton** [comment]
We need more proliferating mobs, rather than Maintbear Mc500health and the bat squad

**Comment by Duny-** [comment]
\>nurse spider on the map by default
Sure why not, let me also add the dylan version of SCP-173 in the bar at roundstart and see what happens

**Comment by Skullyton** [comment]
Hey, while you're at it, how's about an autolathe in R&D?

**Comment by Duny-** [comment]
I already told you I'm going to add one you disgusting casual now get out of my face I don't want to get infected with Icantbuildanautolatheitis

**Comment by 9600bauds** [comment]
This autolathe thing is the WORST FUCKING MEME
If you want to force Science to build something, make them build something they actually want/need and while you're at it don't give them a roundstart chemmaster which goes completely against your map gimmick

**Comment by Skullyton** [comment]
@Duny- Least it isn't one of the 3 classic viruses that spawn in deff maint that need to be cured with something silly like Orange juice or slipping on banana peels.

They don't even have the top on!

**Comment by Duny-** [comment]
@9600bauds clearly science REALLY FUCKING NEEDS an autolathe

**Comment by Imagebard** [comment]
So tell me why the fuck does Duny- saying no mean "no"
Can't other coders edit his map without his permission

**Comment by 9600bauds** [comment]
Nobody cares enough
You could also do it

**Comment by Imagebard** [comment]
>You could also do it

I wish.

**Comment by Duny-** [comment]
You want to remove something from the map that makes it more interesting because you don't like it, get bent

**Comment by Imagebard** [comment]
>because you don't like it

This isn't tagged with "OH GOD IT'S LOOSE" because of personal opinion.

**Comment by 9600bauds** [comment]
Who are you quoting

**Comment by Zth--** [comment]
Oh god its loose it's a meme right now. It doesn't mean shit. Also it makes deff a bit more uniqe and interesting

**Comment by Imagebard** [comment]
Are you seriously unable to think of something to make Defficiency unique and interesting that doesn't involve giving guns to assistants wandering around maintenance tunnels?

**Comment by Zth--** [comment]
It fits with the map. Big maintenance, fun stuff, random spawns. And what's more important is that it's rarely played, so people don't get uset to them easily. It would argue too if it was box, but it's not

**Comment by ihadtoregisterforthis** [comment]
Different meta for different maps. How would YOU make Deff unique and interesting?

**Comment by Duny-** [comment]
I'll tweak the spawners a bit (number and location). Now that I have a fuckhuge z-level to work with I can even extend the remnants of the former station :^) but I'll keep a few that can spawn interesting items. No point to random loot in a big-ass abandoned labyrinth of shit if all you can find is useless stuff.

What's that about carps though, do they reproduce now?

**Comment by CptWad** [comment]
Yeah they reproduce

**Comment by Duny-** [comment]
So that means the room with like 3 or 4 carps and the antique laser gun now has 30 carps by the time you get to it? Amazing

**Comment by CptWad** [comment]
I think they need to be female or something to have babies

**Comment by Imagebard** [comment]
When I check the white ship there are baby carps on every single tile.

**Comment by Duny-** [comment]
Now THAT'S something that needs fixing

**Comment by Killette2** [comment]
Why don't babies ever grow into adults?

**Comment by Imagebard** [comment]
There's already a PR up for that @Killette2

**Comment by Skullyton** [comment]
@Duny- They don't reproduce as in ohlawdinfinitespacecarp, but if a female carp is in proximity of a male carp, it'll explode into baby carp that don't age up to a regular space carp so you don't end up with ohlawdinfinitespacecarp

**Comment by dylanstrategie** [comment]
The idea of maintenance spawners is a really good one, but no-one uses them because it can spawn VERY DANGEROUS items

There needs to be a lot more grading in the spawners. Junk items, low risk like mesons, sunglasses or silver coins, medium risk like ghetto weapon materials and high risk like guns and all that only have small chance to give useful loot

And obviously, high-risk gear needs to be very hard to obtain. The problem with maint spawners is that it makes the spawning random, but Assistants still know where to rush to get their free loot

**Comment by Kitfox88** [comment]
fuk u duny

**Comment by NigglyWiggly** [comment]
This actually sounds like something that could make NotMaint fun.

**Comment by gbasood** [comment]
@PJB3005 why'd you tag this with LOOSE anyway

**Comment by ihadtoregisterforthis** [comment]
Antag items

**Comment by 9600bauds** [comment]
Fun was slain
