### ISSUE TITLE
We need VOLTRON

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8206]
To get this, a roboticist has to make all 5 mechs including phazon, the ripley can be normal or firefighter. All 5 mechs must then be near each other, and have their respective voltron module installed.

Dunno what it will do but it sounds cool

**Comment by ghost** [comment]
Code it

**Comment by Killette2** [comment]
I think there's nothing wrong with demanding this ridiculous request

**Comment by Imagebard** [comment]
Yeah, after you made that feature request for human babies/pregnant women most people figured out you had no self respect or any sense of shame.

**Comment by 9600bauds** [comment]
Will everyone please ease up

**Comment by Killette2** [comment]
I never said anything about pregnant women, the babies came from boxes in capsules orderable from cargo.

There was surprisingly nothing lewd about that so please stop shitposting. The github is for civilized request only.

**Comment by Imagebard** [comment]
>The github is for civilized request only

Your issue got locked for being horrible and cringe worthy. That was the *first time* I've seen a github issue on this fork get closed for that reason.

**Comment by Killette2** [comment]
Well you don't have to make things up like pregnant women, please keep your fetishes to yourself, bad idea or not.

**Comment by Shadowmech88** [comment]
Might as well post this here.
I've only got the south sprite done, and don't currently have the drive to do the other directions, but it's better than no sprite.
![spess voltron mk ii](https://cloud.githubusercontent.com/assets/3991927/13896052/1a6b2970-ed4d-11e5-82de-efb3127fec81.png)
Sawblade might need some work, too.

**Comment by ComicIronic** [comment]
That looks sick.
