### ISSUE TITLE
You can paint cryo tubes and some TEG parts with the RPD

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8207]
![](http://i.imgur.com/W3JBDk8.png)

**Comment by CptWad** [comment]
And TEG parts too

**Comment by gbasood** [comment]
ITS IN THE TITLE

**Comment by clusterfack** [comment]
Thanks doc

**Comment by AutismSpider** [comment]
Nothing wrong with this at all dont fix it

**Comment by Ephx1** [comment]
This is rad

**Comment by ihadtoregisterforthis** [comment]
Allow it to paint hydroponics trays and call it a full blown feature.

**Comment by Zth--** [comment]
Don't fix it, this is hilarious

**Comment by Killette2** [comment]
So what's the problem?

**Comment by gbasood** [comment]
no problem

**Comment by 9600bauds** [comment]
Hydro trays can prolly be painted too, can't they

**Comment by PJB3005** [comment]
Nah trays aren't subtype of `/obj/machinery/atmospherics`, they're `/obj/machinery/portable_atmospherics`

**Comment by ghost** [comment]
This is my fault but should I fix it?

**Comment by ihadtoregisterforthis** [comment]
Nothing to fix here

**Comment by ghost** [comment]
Notice the pump hidden under locker left of purple cryo tube, it was rotated to pump waste gases into cryo.

**Comment by 9600bauds** [comment]
AFAIK plasma in cryo doesn't even do anything if it's still cold

**Comment by CptWad** [comment]
>AFAIK plasma in cryo doesn't even do anything if it's still cold

Never thought about that
why the hell do we use O2 then? N2 seems like a better choice

**Comment by Killette2** [comment]
Vox detected

**Comment by 9600bauds** [comment]
A better choice in what regard? I think oxygen has the same heat rating as nitrogen

**Comment by CptWad** [comment]
O2 is flammable.

**Comment by 9600bauds** [comment]
God forbid Cryo catching on fire

**Comment by FudgePucker** [comment]
Plasma would be the best choice for cyro.
I mean, what could go wrong with having easy access to a canister of plasma :^)

**Comment by Kitfox88** [comment]
plasmamen coming into medbay to fill their fucking tanks!!!!

**Comment by 9600bauds** [comment]
>large tanks ever needing refills
What strange world do you come from

**Comment by AutismSpider** [comment]
the round would have to good on for good 5 hours be for they need reload large tanks last long ass time.

**Comment by Probe1** [comment]
Thanks Doc
