### ISSUE TITLE
Centrifuge/Suspicious Toilet not flushing

### ISSUE THREAD

**Issue by viniciuspetch** [d3athrow/vgstation13#8208]
The "flush" verb/action is not working on the centrifuge/suspicious toilet. I'm pretty sure I set up everything right because the toilet actually transformed into suspicious, and I could put the containers to separate. However, clicking flush once and waiting or spamming the button didn't work.

Steps taken: Open the toilet with hands, open with crowbar, put rods and put paper and it'll magically turn into a suspicious toilet. I tried with a 8uNitro/8uPotassium mix first and then with a 25uSodium/25uOxygen mix, both with 1 or 2 empty containers. Clicking flush at the top right menu, right-clicking or writing "flush". Nothing happened.

I seriously don't know who's wrong: me, the game or the wiki.

This is the thing I'm talking about: http://ss13.moe/wiki/index.php/Guide_to_Ghetto_Chemistry#Centrifuge

**Comment by 9600bauds** [comment]
Did any message pop up when you tried flushing?

**Comment by gbasood** [comment]
I thought we just fixed this problem a month or two ago
