### ISSUE TITLE
Motorized Wheelchair Immune to Emitter beams

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8211]
(WEB REPORT BY: gunosaguki REMOTE: 158.69.55.2:7777)
Unsure If bug or intended, but a motorized wheelchair can block emitterbeams with no negative downsides. Unsure if this also incldudes when RIDING it, since I found this while pushing the wheelchair as a cyborg.

If not a bug, feel free to remove this.

**Comment by Shadowmech88** [comment]
I'm not sure wheelchairs blocking emitters is explicitly unintended, it's probably just a natural result of them being dense. I'm not sure how much of an issue it is, plenty of dense things more common than wheelchairs can block emitter beams.
Wheelchairs do physically block emitter beams while you're riding them, but the emitter still damages you, so it's not a problem.
