### ISSUE TITLE
facehuggers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8214]
(WEB REPORT BY: mechamusume91 REMOTE: 158.69.55.2:7777)
A single facehugger attacked me and instnatly broke through my hardsuit helmet and infected me.

it would bounce off because its just one of them

in a second it bounced one and instantly jumped again through my helmet.

walking up to one with a hardsuit on

**Comment by Exxion** [comment]
Several people have said this happens in the thread
@gbasood

**Comment by ghost** [comment]
He made it have a 50% chance to plop off the helmet, on purpose. Like I said, terrible idea that makes an already overpowered antag even more overpowered.

**Comment by ghost** [comment]
The helmet health can't come soon enough. I can also see uses for it in the form of #8024
