### ISSUE TITLE
Ghosts Can Rotate Firebirds

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8218]
Since vehicles are children of `/obj/structure/bed/chair/` this probably applies to all vehicles.

**Comment by ihadtoregisterforthis** [comment]
Yes, the janicart is affected too. But not really a problem since the direction of the vehicle means nothing, except maybe for fireballs.

**Comment by Shadowmech88** [comment]
> except maybe for fireballs

According to the thread, it did screw with a wizard who was trying to do exactly that.

**Comment by ghost** [comment]
Heh.

**Comment by ihadtoregisterforthis** [comment]
Well trying to shoot fireballs from a vehicle isn't brilliant but it might be enough to remove spinning from Firebirds.

**Comment by clusterfack** [comment]
http://ss13.moe/forum/viewtopic.php?f=20&p=9042&sid=bfb7ce0761dfcd1bd86ae7fe2d448fce#p9042

**Comment by ghost** [comment]
Wait, what does he mean by "Wizard armour"?

As in the spacesuit?

**Comment by ghost** [comment]
No, he means the Magus gear.

**Comment by ghost** [comment]
Ah, alright

**Comment by Exxion** [comment]
Just specifically make the Firebird immune to ghostspin
I can do it in like 30 seconds if it is decided it's a good idea
I refuse to remove janicart spinning though

**Comment by ghost** [comment]
@Exxion Yeah, that's the solution I was thinking of too.

**Comment by ihadtoregisterforthis** [comment]
I vote for "it's a good idea", even if it means no longer spinning lucky miners.

**Comment by ghost** [comment]
Alright, got it.

**Comment by ghost** [comment]
You should not be able to ghost rotate vehicles. It's just dumb and fucks with shit, and if a bunch of ghosts haunt a vehicle driver they can fuck him up near permanently

**Comment by 9600bauds** [comment]
How can they fuck him up besides fireballs?

**Comment by ghost** [comment]
Literally anything that is aimed manually will be fucked by it due to his dir constantly changing

This also makes it look extremely stupid

**Comment by Shadowmech88** [comment]
What is aimed manually besides fireballs?

**Comment by BarneyGumball** [comment]
Fixed by #8244
