### ISSUE TITLE
Baby carps should grow up

### ISSUE THREAD

**Issue by unid15** [d3athrow/vgstation13#8221]
Right now baby carps never grow up

But what if they could grow up after biting somebody enough times? You'd also be able to feed them meat (by attacking them with it) to speed up their growth

**Comment by Shadowmech88** [comment]
They should also eat meat off of the ground so you can carp-farm without access to pheromones.

**Comment by Imagebard** [comment]
Why the fuck should this be a feature
Why

It just makes carps start growing at faster and faster rates as more carps grow up. Imagine going to escape and seeing 10 adult carps growing around. Imagine 20. Imagine 50. And every baby carp that grows up to be female makes them procreate faster. That would just be a carpocalypse.

**Comment by unid15** [comment]
Numbers can always be tweaked. Also carps don't attack dead people, so they won't grow exponentially unless they receive a steady supply of fresh food

Also there's a limit on the amount of animals that can exist, so there will almost never be more than 50 carps (in the whole world)

**Comment by PJB3005** [comment]
Carpsplosion anybody?

**Comment by Kitfox88** [comment]
lmao 2carp
