### ISSUE TITLE
Always show [Set Internals] option in strip menu

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#8222]
As-is the set internals button only shows up when your target has a tank on their back or in their suit storage. Doesn't show up if the tank is in their hands or pockets, which is pretty annoying.

Having a seperate option for it would be very useful.

**Comment by Imagebard** [comment]
>Hands

If they have something on their hands they're awake, so, why?

>pockets

You can't see what is on someone's pockets, so that makes no sense.

**Comment by ihadtoregisterforthis** [comment]
They can have something on their hands if buckled to a chair.

**Comment by SonixApache** [comment]
Pockets makes sense if you don't know what's in there, I guess.
It's mostly an issue with vox; you have to spend a lot of time fiddling with their tank if it isn't on their back or in their suit storage. You can cuff them and make them hold their tank.

I mean, I guess you could just tell them to turn it on themselves, but whatever.
