### ISSUE TITLE
Radiation-shielding clothing protects you from mutagen radiation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8223]
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 85441cb24f185c96e28a5b5d3e7db36324f2f21d 
> 
> General description of the issue
> Exactly what I named it.
> 
> What you expected to happen
> For mutagen radiation to bypass armor protection.
> 
> What actually happened
> radsuits make you completely immune to all damage and you can eat up 1000 units of mutagen just fine with the exception of a few genetic defects.
> 
> Steps to reproduce if possible
> Literally wear a radsuit or engineering/CE harsuit and eat mutagen like its lime candy.

**Comment by ghost** [comment]
I don't even know if this is actually my fault, and I don't believe it is. Lifecode is awful.

**Comment by Gringonius** [comment]
Just tested this in an old version before hypothermia and it's the same. Surprised no one noticed this until now.
