### ISSUE TITLE
[Deff] Vox raiders dont spawn

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#8228]
We had a vox raider round and all the players were stuck at lobby frozen still. Check antag said they were not even vox yet
@Duny-

**Comment by DrCelt** [comment]
while doing this you should add an autolathe @duny-

**Comment by 9600bauds** [comment]
Aaaaaahhh

**Comment by Duny-** [comment]
Vox raiders can't happen on deff has there is no shuttle yet, I'm aware of that already
I thought it just sent back everyone to the lobby though

**Comment by CptWad** [comment]
no no they were complaining in ooc about how their game froze, the vox raiders. Turned into a round where the antags just straight up did not spawn

**Comment by Duny-** [comment]
Yes I understood the first time
Sounds like good code

**Comment by Duny-** [comment]
This is fixed
