### ISSUE TITLE
Organs from the organic debris field do weird things when picked up

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8232]
1. Organs from the organic debris field cannot be picked up. You can click them and a sprite will appear in your hand, but the item will also remain on the ground. Dropping it will teleport it to you. They also start flying in whatever direction they were flying before even if they hit something.
2. ~~Despite being ostensibly from air supply contamination, mass drunkenness ignores internals and even space suits.~~

**Comment by Shadowmech88** [comment]
Does the organic debris field event still exist? And does this still happen?

**Comment by Shadowmech88** [comment]
Regardless, I manually triggered multiple organic debris field events, and the gibs spawned appear to no longer contain organs.
