### ISSUE TITLE
Permanently drunk Plasmamen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8234]
(WEB REPORT BY: contentinformsreality REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 29ea04e5dbc16043f63c1443173b59b885a03146
> 
> General description of the issue
> Drunkness (event) left plasmaman with permanent drunken movement. Unknown if this also effects speech (encountered as a mime).
> 
> What you expected to happen
> Drunkeness event would end after a minute. Confirmed with admin that nobody else was still drunk.
> 
> What actually happened
> I was drunk forever, unable to walk in a straight line.
> 
> Steps to reproduce if possible
> Be plasmaman.
> Get hit by drunkeness event.
> Be drunk 5evar.

May be related to other plasmaman issues (e.g. jittering)

**Comment by 9600bauds** [comment]
Closing in favor of #10485 which has more info
