### ISSUE TITLE
Occupation Preferences issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8235]
when you have a job set to "high", if you right-click any **_other**_ job the job on "high" goes to "medium".
example:
you have scientist to "medium" and roboticist to "high";
right-click scientist;
scientist goes to "low" and roboticist goes to "medium".

**Comment by mrpain666** [comment]
Are you trying to set multiple jobs to high? You can only have one job on high.

**Comment by PJB3005** [comment]
Thanks @D3athrow

**Comment by uazuaz** [comment]
@mrpain666 
nope, this happens when i lower another job from medium to low or from low to never.
am i the only one?

**Comment by Shadowmech88** [comment]
This still exists.

**Comment by d3athrow** [comment]
@PJB3005 
why am i assigned to this
i never touched job code that would cause this
fuck you pay me

**Comment by PJB3005** [comment]
Hey man I'm sure I had a reason at the time but I'll be damned if I'll know that almost 4 years later.

**Comment by Zth--** [comment]
I remember about this one. Right click wasn't working at all and pomf fixed it. This bug then emerged

**Comment by Shadowmech88** [comment]
Where are job preferences within the code?

**Comment by PJB3005** [comment]
It's all in `code/modules/client/preferences.dm`. I did some digging and `SetJob` is the proc that gets invoked when you  press one of the buttons in the occupations menu. `inc` appears to be zero when you decrease a job priority and 1 when you increase it.

**Comment by Shadowmech88** [comment]
I can't wrap my head far enough around the bitwise operations and whatnot in the job procs to understand what the problem is. However, I did find out that when you left-click a job, `SetJobDepartment()` is called once, but when you right-click a job, `SetJobDepartment()` is called three times. Maybe that's related.
