### ISSUE TITLE
Ejecting the miners id from the ore processing console as AI places it under your core.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8237]
(WEB REPORT BY: sarahjohnson REMOTE: 158.69.55.2:7777)

> Revision 29ea04e5dbc16043f63c1443173b59b885a03146 
> As the title says

Steps to reproduce:
Put an id in the ore processing console
Be AI
Hit claim points then eject id
Right click your ai core to see the id

**Comment by clusterfack** [comment]
Do we need to modify the put in hands proc or something for AIs?

**Comment by ghost** [comment]
Should adjacency sanity checks be on users or appliances?

I'm pretty sure they are all over the place at the moment.

**Comment by Intigracy** [comment]
haha
