### ISSUE TITLE
Drunkness event is shit.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8238]
It makes even less sense than power loss event, affects everyone regardless of status, protection, location, air presence or pretty fucking much anything at all.

Not only that, but it is the only event that without prior warning immediately fucks up players and there is absolutely nothing they can do aside from carrying anti drunkness pills at all times.

**Comment by gbasood** [comment]
Drunk event is pretty bad yeah.

**Comment by Zth--** [comment]
I say remove it, it's stupid.

**Comment by 9600bauds** [comment]
yup, it's shit even as a badmin button

**Comment by PJB3005** [comment]
I haven't seen it happen but it sounds pretty fucking retarded to be honest.

**Comment by ghost** [comment]
I don't like the idea of it personally. I can understand a mass hallucination event as a late-round event if you pair it with something like neurotoxin release or distant shard delamination, but mass drunkenness is just too randumb for random events

Maybe as an admin button, not as a random event

**Comment by Shadowmech88** [comment]
I'd like to re-open discussion on how terrible this event is, and ask that it be removed or fixed.

**Comment by TheEliminator16** [comment]
Yeah, fair enough. Would you all support just making it an admin button only?

**Comment by gbasood** [comment]
I honestly don't even think it should be that, but no matter what it should be taken out of random events.

**Comment by TheEliminator16** [comment]
The PR that I'm working on now removes it completely
