### ISSUE TITLE
Unghosting doesn't reset view size.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#8239]
So if somebody is zoomed out a shitload and he becomes a posibrain he now has a huge view size.

**Comment by clusterfack** [comment]
Only for admins, that's the way it was when the system was made originally

**Comment by Ephx1** [comment]
Yeah this doesn't apply to posibrains or other mid-round-entering roles as far as I know.
I tested it a few times already as posibrain and I believe once as borer.

**Comment by ihadtoregisterforthis** [comment]
Neither as mouse nor derelict MoMMI

**Comment by PJB3005** [comment]
It's happened multiple times for me, but I guess it has something to do with being admin like @clusterfack said.

**Comment by DamianX** [comment]
not a bug, not sure why it wasn't closed
