### ISSUE TITLE
Ghosts can smash into supermatter shard if they are propelled by build mode

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#8248]
Toggle build mode, select TH. Select a ghost, propel it into shard and it gets smashed into shard and shard moves backwards.

**Comment by Shadowmech88** [comment]
What happens if you're killed by the shard when you're already a ghost?

**Comment by clusterfack** [comment]
Okay but like, who cares? Admins can fuck up anything and everything at a whim

**Comment by Imagebard** [comment]
@Shadowmech88 Probably nullspaced.

How is being nullspaced like, anyways?

**Comment by Shadowmech88** [comment]
I'm pretty sure that if you get nullspaced, your camera eye is just stuck on wherever you were before being nullspaced.

**Comment by Ephx1** [comment]
nullspace is a screen of black

**Comment by AutismSpider** [comment]
nullspace is just black screen

**Comment by MusgardTiger** [comment]
Nothing happens, you just get the message saying "you are an adminghost blabla" BUT it deletes your ckey from your corpse if you have any. So it says that you don't have a corpse even if you have one.

**Comment by MusgardTiger** [comment]
By the way I know this isn't a worldshattering bug. I just wanted to let you code people know whatsup.

**Comment by Exxion** [comment]
Deleting your ckey from your corpse is a pretty significant bug though
It makes you unrevivable without admin intervention

**Comment by Imagebard** [comment]
You can't smash into the supermatter as a ghost without admin intervention in first place anyways.

**Comment by Exxion** [comment]
Yeah but can you really expect badmins who are throwing ghosts around to help you get unfucked?

**Comment by clusterfack** [comment]
Deleting a ghost makes a new ghost, its not an issue

**Comment by Exxion** [comment]
Shouldn't the new ghost at least get the old one's corpse?
And does slamming a ghost into the crystal provide power?

**Comment by clusterfack** [comment]
Get the old ones corpse? I'm not sure what you mean by this. You wouldn't even notice getting your corpse deleted in any way because you have an identical ghost replacing it.

**Comment by Exxion** [comment]
No, the actual corpse. So you can re-enter it.
Read the comment exactly six above my last one.

**Comment by clusterfack** [comment]
I have literally no idea why you think that would delete your ckey from your corpse. But if you had a problem it might be that the canreentercorpse flag is being reset.

**Comment by Exxion** [comment]
OK wait hold up if I'm reading the code correctly it doesn't even kill your ghost
It just bumps the shard backwards
So the only actual issue here is that ghosts can apparently bump things when buildmode thrown

**Comment by Exxion** [comment]
I'm too tired to decipher this shit right now but I think the cause of this is buried somewhere deep within `throw_at()`
I'll take a look at it later if someone else hasn't found it yet

**Comment by ghost** [comment]
Anything thrown by buildmode becomes "dense", you can smash windows with ghosts thrown by buildmode

**Comment by Exxion** [comment]
That's what I was worried about

**Comment by Probe1** [comment]
Well don't do it.
