### ISSUE TITLE
Items sometimes permanently become dense after ZAS fucks with them

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8252]
This has been happening for a long time and I kept meaning to report it but kept forgetting
Items are sometimes made temporarily dense when being pushed around by ZAS. I think this is intentional but I'm not sure. However, on rare occasions, they stay dense forever.

I'm pretty sure it's ZAS pushing that is the culprit, but not entirely sure. I have seen dense items before a few times, though. May or may not be worth noting that this seems to happen especially often with metal rods, though I've seen it happen with other items too.

Yes, they stay dense after you pick them up and drop them.

**Comment by Imagebard** [comment]
Wasn't this issue reported 3-4 times already?

All issues about this have been closed. When did it last happen to you?

**Comment by Exxion** [comment]
Few days ago
I forget exactly when

**Comment by Imagebard** [comment]
>Few days ago

*Here we go*
