### ISSUE TITLE
Remove borg model choice restrictions

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8254]
Currently borgs get 5 picks in their model selection dialog, which is not enough to even see all the choices available. There are way more than 5 models for certain borg types and it makes no sense that there should be a restriction for it in the first place, once you lock one in you're with it until reset anyway.

Should be easy enough since MoMMIs already have infinite choices in the same dialog.

**Comment by ihadtoregisterforthis** [comment]
Or this #3595

**Comment by gbasood** [comment]
Would prefer #3595 honestly

**Comment by ghost** [comment]
Why not both?

**Comment by clusterfack** [comment]
Pretty sure it cant be both because you'll break byond by logging out during an input when there's an infinite loop of inputs.
