### ISSUE TITLE
BYOND has a 30 FPS cap

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8258]
Bitch at Lummox so that we can get uncapped FPS

I want to see what 60 FPS spessmen action looks like

**Comment by PJB3005** [comment]
This is another level of shit issue report.

You obviously interpreted GitHub as the [BYOND feature request forum](http://www.byond.com/forum/?forum=6).

**Comment by clusterfack** [comment]
What, what in the world makes you think the FPS is capped? You can set it to any framerate dude.
