### ISSUE TITLE
Message spam after haunting an aghost

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#8259]
> Revision

Revision: 18eb47475c2566f1e026b554d2aa57da9903276c 

> General description of the issue

An admin had aghosted and said "COMFY" in deadchat (through say, not through dsay) before returning to their (alive) body. Upon attempting to haunt the person, I got the message "You are now haunting " (including the space). Asides from that, nothing happened. When I then ghosted around afterwards, every tile moved gave me the message "You are no longer haunting ."

> What you expected to happen

I expected to either jump to the player sending the message or have nothing happen (since IIRC, you used to just have nothing happen if you tried to follow a ghost that was no longer there).

> What actually happened

![haunting a ghost that doesn t exist](https://cloud.githubusercontent.com/assets/5942183/13029700/818f8ed6-d293-11e5-9c8e-f57444876166.PNG)
I don't know if that only happened because I tried to haunt an aghost that wasn't there anymore or if it would happen with any ghost that's not there anymore.

> Steps to reproduce if possible

Have one (admin) player aghost, speak in deadchat, and then return to their body.
Have another ghost attempt to haunt the now-gone aghost.

**Comment by Shadowmech88** [comment]
Tested locally, nothing happens upon clicking Follow.
