### ISSUE TITLE
Hypospray objective now near impossible

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8266]
Hypospray gets rushed and made into a sword now, which makes obtaining it for objective impossible as the item is gone and there is only one.

**Comment by Shadowmech88** [comment]
The sword can be deconstructed. Apply crowbar and then attackself with the sword.

**Comment by 9600bauds** [comment]
I doubt it will get rushed for very long after the hype dies down. The sword you get is pretty inferior to just the hypospray.

**Comment by clusterfack** [comment]
Did this happen to you termed? I somewhat doubt this has already happened to you.

**Comment by ghost** [comment]
It can be deconstructed.

Didn't happen to me, theorizing about.

**Comment by ghost** [comment]
> tagging a closed issue

**Comment by 9600bauds** [comment]
What if someone wants to look through all the closed bad issues?
