### ISSUE TITLE
Hive hand bug

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#8268]
So the hive hand can be made form a living or dead  Lamarr.

**Comment by Exxion** [comment]
Considering Lamarr has a tendency to kill herself this seems like a good thing

**Comment by clusterfack** [comment]
**>her**

**Comment by Exxion** [comment]
Lamarr in HL2 is referred to as female so I assumed that's what this one was too

**Comment by Shadowmech88** [comment]
How is Lamarr able to kill herself?

**Comment by AutismSpider** [comment]
Lamarr likes to jump at people with space helms A LOT even if you have her bagged or on your face

**Comment by Shadowmech88** [comment]
I think it should be changed so that sterile facehuggers don't die when they jump at helmets.
Once I do that, I'll make it so that only a living Lamarr can turn into a Hivehand.

**Comment by Exxion** [comment]
Well
Lamarr jumped straight *through* my helmet and went straight onto my face
But was dead when removed

**Comment by gbasood** [comment]
@Exxion Facehuggers currently only die if they bash into a helmet at all. If it goes through your helmet then it's still bashing against it.

**Comment by Exxion** [comment]
But how did it go through my helmet?

**Comment by gbasood** [comment]
Bug that I've already got a fix for.
