### ISSUE TITLE
Make Posibrain and Borer Prompts Opt-In Instead of Opt-Out

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8270]
Diona prompts are already like this.
I'd rather have to click to opt-in when I want to be a posibrain or borer than have to constantly click to opt-out when I'm just trying to observe.

**Comment by Exxion** [comment]
:+1:

**Comment by uazuaz** [comment]
related to this #7774 ?

**Comment by PJB3005** [comment]
:+1:

**Comment by Imagebard** [comment]
:+1:

**Comment by ihadtoregisterforthis** [comment]
Isn't this tied to your special preferences?

**Comment by ghost** [comment]
It is
