### ISSUE TITLE
Floor Tile Throwforce

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8271]
I'm not suggesting anything in particular be done right now. This is more for discussion than anything else.

I feel that the fact that floor tiles are literally everywhere, can be procured with only a crowbar, and do 15 damage per throw means that there is little reason to use anything else in battle.

**Comment by ghost** [comment]
:-1: those are my tiles dang it

**Comment by 9600bauds** [comment]
I don't know. Are they really a problem?

**Comment by clusterfack** [comment]
Nerf floor tiles, buff toolboxes

**Comment by 9600bauds** [comment]
Toolboxes are like 12 force already, aren't they?
Sure, 15 force might be cool considering they don't fit in your backpack

**Comment by clusterfack** [comment]
They also aren't ranged weapons like floor tiles are.

**Comment by ghost** [comment]
Would be cool if we could stuff toolboxes full of heavy things, weld them closed and make them deal more damage this way.

This is a metal toolbox menacing with spikes of glass. Engraved on it is a drawing of an assistant in blood. All craftsmanship of the highest quality.

**Comment by 9600bauds** [comment]
I think that was tried at one point and didn't work out

**Comment by 9600bauds** [comment]
Also why would welding it shut do more damage?

**Comment by ghost** [comment]
So the heavy things don't fall out when you hit people with it.

**Comment by 9600bauds** [comment]
I don't know what kinda toolbox you have at home but mine has clamps to hold it shut, otherwise it would open while grabbing it from the handle

**Comment by ghost** [comment]
15 force is too much for something you can get in massive amounts or near immediately with a crowbar

10 force seems like a maximum to me. Due to how easy it is to obtain, I'd even argue for 5 force. It's a metallic tile, sure, but unless you get hit in the head or with a perfect horizontal throw it's not deadly

**Comment by SangriaMonkey** [comment]
They're not a problem. Anyone can dodge them and they've got a pretty limited range. I'd rather run and find a toolbox or something.

**Comment by 9600bauds** [comment]
>Anyone can dodge them
Not a lot more that any other projectile in the game
>they've got a pretty limited range. 
Screen wide range
>I'd rather run and find a melee weapon that does less damage
I think floortiles are not a problem either but something just isn't right about this post

**Comment by Gringonius** [comment]
The solution is simple: nerf the tiles but add craftable throwing stars made from tiles with the same throwing behaviour as the current tiles.
Unrobust babies who want them needed get what they want but any greyshirts with a little effort can make something as good as they were.

**Comment by Gringonius** [comment]
want them nerfed*

**Comment by SangriaMonkey** [comment]
Yeah I'd rather just rush the guy down than play dodgeball like a chump. Don't see how anyone could mash hotkeys fast enough to be that much of a problem.

**Comment by ghost** [comment]
The floor tiles are fine as is for anyone can dodge worth a damn against many people who have godawful aim while these are a vital tool in the war on rogue borgs. Whether you pre-split or you got sanic fast there's still a delay while you ready the next to give you time to react. If you wanna bring up but muh oohh peee so is a slip strip and slicing them up, slip and table lock, slip and window slam to death, beepsky's baton, scrub glove bottling, eye gouging, light source blinding, ghetto chloral syringe jabs, and there's a billion other powerful items and methods in the game. Shit's plenty competitive

**Comment by clusterfack** [comment]
Yeah but floor tiles are stupid and toolboxes are great.

We need to make toolboxes great again.

**Comment by Shadowmech88** [comment]
If people don't want floortiles' throwforce nerfed, what about buffing the damage of other weapons to balance around it?
A hatchet has 15 throwforce, the same as a floortile. However, there are not many hatchets on the station at roundstart, while there are hundreds of floortiles. This being the case, why would anyone bother to use a hatchet as a throwing weapon when they could just use floortiles instead?
Would, for example, buffing the hatchet's throwforce to 30 or 40 be an acceptable approach to make people more likely to use actual weapons instead of defaulting to floortiles?

**Comment by 9600bauds** [comment]
> 30 or 40

Absolute
Fucking
Madman

**Comment by Shadowmech88** [comment]
Well, 30 is two thrown floortiles. Which are free and literally everywhere.

**Comment by 9600bauds** [comment]
Yeah and 60 or 80 would be two thrown hatchets

**Comment by Shadowmech88** [comment]
I'm just spitballing. But I do think _something_ needs to change. As it is, there's little reason to work to acquire some specific melee weapon when floortiles are just as good as, or even better than, most melee weapons.
I don't see any options besides lowering floortile damage or buffing the damage of everything else to compensate for how much more difficult literally everything else is to acquire by comparison to floor tiles.

**Comment by Shadowmech88** [comment]
This was resolved by the floortile nerf.
