### ISSUE TITLE
The Pipe Gun/Explosion Cannon deletes your head

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8272]
People on OOC agreed that it shouldn't delete your head once you shot it. Its a *kinda shitty* idea, but I'd recommend special code to make it so your head isn't deleted by blast cannon shots.

**Comment by Exxion** [comment]
Honestly mob ex_act() probably needs some work in general
I'm pretty sure getting completely annihilated by an explosion also nullspaces your backpack and everything in it
Including, I assume, the nukedisk

**Comment by Shadowmech88** [comment]
Should I just make it so that severed heads are immune to explosions in general?

**Comment by Shadowmech88** [comment]
So I've tested it, and heads get deleted by normal explosions if they're in the devastation range, whether or not they're attached to a body.

What is the reasoning for why a TTV shouldn't destroy heads when shot out of a blast cannon, despite the TTV by itself being perfectly capable of destroying heads?

**Comment by Imagebard** [comment]
Because otherwise holy shit its OP.

**Comment by Shadowmech88** [comment]
Alright, I'll make the blast cannon specifically exempt heads.

**Comment by Shadowmech88** [comment]
This was fixed by #8383, it just didn't auto-close.
