### ISSUE TITLE
Central Atmospherics Computer is bugged

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#8276]
![central atmospherics computer](https://cloud.githubusercontent.com/assets/16625342/13035257/5b7f0b78-d34b-11e5-8d03-a62cc4488c6d.png)
Presented without comment.

**Comment by clusterfack** [comment]
Clear your cache

**Comment by 9600bauds** [comment]
how is the thing done

**Comment by Gringonius** [comment]
Still bugged.

**Comment by Gringonius** [comment]
@clusterfack 
Still not fixed, cache cleared several time and all.
Crew Monitoring Console and Advanced Security Cameras console work fine.
Is this really a cache issue? Are there are particular instructions other than deleting the cache folder in My Documents?

**Comment by clusterfack** [comment]
Haha yeah this is a different type of computer than those two that I spent quite some time to fix. One day I intend to convert it to that same type of computer.
