### ISSUE TITLE
could understand vox language as a human

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8277]
i was a human scientist, after a while i saw that i could understand vox language, by the way i tried to talk it using :v but it didn't work.
this happened when a borer almost killed me using space drugs, i don't know if it's related.
happened in the round that just ended (if you need to check logs, the log time when the round ended was around 11:45, my name was Axel Ringer)

![vox](https://cloud.githubusercontent.com/assets/6170726/13035306/0ab6c2c4-d34d-11e5-9aa5-7e34456dde60.jpg)

**Comment by ihadtoregisterforthis** [comment]
Borers give you the ability to understand most languages, if not all. If you still had the borer this is intended, if you didn't then something else is borked.

**Comment by uazuaz** [comment]
at the moment i'm not sure if he still was in my head.
can they let you understand languages just with their presence? or must they do something to enable this ability?

**Comment by ihadtoregisterforthis** [comment]
Having the ~~boner~~ borer inside alone enables this.

**Comment by uazuaz** [comment]
well, it seems that it was just that then; i checked the logs, it seems that the borer was still inside my head.
closing the issue.
