### ISSUE TITLE
PDA Maps Are Broken

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#8278]
Because of the new 500x500 size, the locator on the map buyable for the PDA is off by a lot.
Since PDAs haven't been touched that I know of I assume this is true for all maps, but it was only tested on Deff.

**Comment by Kitfox88** [comment]
im a shitter who uses the pda maps a lot plz fix

**Comment by AlphaBuffalo** [comment]
Pda map is kind of important on deff, mainly for the maintenance

**Comment by clusterfack** [comment]
Yeah this works fine now
