### ISSUE TITLE
Facehuggers can jump diagonally through walls

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#8279]
Facehuggers can jump at victims diagonally through walls as long as there's no corner wall. I have no fancy screenshots about this but I did spend 2000 hours making a mockup in Paint.NET
![image3](https://cloud.githubusercontent.com/assets/16625342/13035366/beb435ee-d34e-11e5-8289-043a32497ea9.png)
This seems like an oversight, as having two walls adjacent like this usually prevents you from being able to interact with anything through the corner too.

**Comment by 9600bauds** [comment]
Wow, I'm really digging these new sprites

**Comment by gbasood** [comment]
Do we have code somewhere right now that can check for a case like this? Or would I have to write my own?

**Comment by 9600bauds** [comment]
Adjacent()
This sounds like it's using in range(1) or something
