### ISSUE TITLE
Fake windows smooth with riveted walls

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8280]
![window_smoothing](https://cloud.githubusercontent.com/assets/6137403/13035592/747a406c-d354-11e5-8fe5-24ac4d156cbf.png)

FYI, fake windows are technically walls. We could use real windows too, but this allows us to minimize atmos simulation on Z-level 2

**Comment by Shadowmech88** [comment]
This is no longer the case.
![image](https://user-images.githubusercontent.com/3991927/46569214-3c6ce380-c917-11e8-9de1-a699dcd698aa.png)
