### ISSUE TITLE
Any type of sword should fit in the plate armor's suit storage.

### ISSUE THREAD

**Issue by SysadminJeroen** [d3athrow/vgstation13#8287]
Just a feature request.

**Comment by gbasood** [comment]
Let's not put executioner swords there though

**Comment by Exxion** [comment]
Executioner's swords are probably not as good as people think they are anyway
They have a high chance of causing bleeding and can chop off limbs more easily, but a fire extinguisher will deal more damage in less time

**Comment by SysadminJeroen** [comment]
@gbasood Executioner's Swords are between 80 to 90 centimeters, I think that it would fit there somewhat realistically.

**Comment by AutismSpider** [comment]
Bloody spear is better then Executioner sword only thing the that sword good for is chopping limbs off when they hit the damage point.

**Comment by gbasood** [comment]
It took a wiz what might have been 3 executioner's sword chops to the head to get his head removed earlier today. So I'm somewhat against making them easier to lug around.

**Comment by Shadowmech88** [comment]
The executioner's sword also has two sharpness, which means that the damage threshold at which it becomes able to sever limbs is lower than average.

**Comment by Imagebard** [comment]
Really now, a wizard could easily avoid 1 executioner sword chop with his powers. How did he get 3? That thing swings slow as shit.

**Comment by gbasood** [comment]
Dude got tasered coming out of a blink and Sawbones just showed up and chopped his head off while he was down

**Comment by AutismSpider** [comment]
blink has two sec cool down unless he got knock out some how i don't see happening unless the wiz got bad rng on the sword hit.

**Comment by 9600bauds** [comment]
> Dude got tasered

**Comment by Shadowmech88** [comment]
You can blink away while tased.

**Comment by Imagebard** [comment]
>Dude got tasered

YOU'RE A FUCKING WIZARD TASERS DON'T MATTER

**Comment by gbasood** [comment]
well fuck man I don't know it was a long time ago

**Comment by Imagebard** [comment]
Long time ago but Executioner Swords still exist?

**Comment by Exxion** [comment]
> Long time ago
> "Earlier today" three days ago
