### ISSUE TITLE
I couldn't unbucklecuff myself during a round

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8288]
During one round when I was a clown, in multiple occurrences I was unable to uncuff myself on my own. One part was when I was bucklecuffed to a bed, whenever I tried to uncuff myself, while not on drugs or drunk, after 10-20 seconds it randomly said I was interrupted when alone. Same happened later when I was in the courtroom, buckled to a wooden chair. 10-20 seconds with nobody touching me and it randomly says I was interrupted.

I am sure there wasn't anything interrupting me, and this can be very abusable.

**Comment by Exxion** [comment]
Bucklecuff resisting is really buggy in general

Actually, any resisting with really long delays is
