### ISSUE TITLE
Librarian should have books to learn languages

### ISSUE THREAD

**Issue by MemeFury** [d3athrow/vgstation13#8289]
With multiple steps for each language to only translate part of what someone is saying at lower levels. It'd give a good use for the librarian and enable new communication that you don't have to select at roundstart.

**Comment by ghost** [comment]
DID SOMEONE SAY SKILLS ?

**Comment by Ephx1** [comment]
NO DYLAN, NO

**Comment by Kitfox88** [comment]
do it

**Comment by MemeFury** [comment]
@dylanstrategie 
I don't know about skills beyond languages, but tiered languages would be pretty neat. Pretty much adding a big use for the library beyond Woody's Got Wood is a plus in my book, it's one of a few jobs that haven't really got an update in a while.

**Comment by PJB3005** [comment]
:-1: :x: :100: no matter how you do it it is going to be powergamed hard.

**Comment by 9600bauds** [comment]
Powergame to what end? Language barrier is almost never a thing and already surpassed by any silicon, including PAIs, and also borers

**Comment by gbasood** [comment]
But currently players can rely on the fact that only those groups can eavesdrop.
I think learning languages so quickly should only be a prayer thing. No human being would be able to learn a language to a conversational level in the course of even a few weeks, if not months.

**Comment by ghost** [comment]
How about an earpiece that translates everything you hear so you can understand it, could only be set to one language at a time.

Since it's an earpiece, it already has a tradeoff that you can't have a headset and have to rely on station bounced radio.

**Comment by ihadtoregisterforthis** [comment]
`var/native                       // If set, non-native speakers will have trouble speaking.
`
This is on the languages code. Does it work?

**Comment by gbasood** [comment]
@TermedClepe you might as well have a pAI then
or a borer

**Comment by NigglyWiggly** [comment]
Oh man I can't wait to have all the languages 5 minutes into a round
Can we learn xenomorph and monkey too?

**Comment by ghost** [comment]
Babelfish when?

**Comment by Ephx1** [comment]
Borers are essentially Babelfish, the only difference is that this is a slug, not a fish.

**Comment by ghost** [comment]
Borer vending machine that requires solving an extremely strange puzzle to actually get the borer when?
