### ISSUE TITLE
Cuban pete arcade easily cheesed

### ISSUE THREAD

**Issue by Sordine** [d3athrow/vgstation13#8293]
Before to cheat you had to unscrew it and screw it back. Now all you have to do is emag it again and it resets. This means bombcap bombs can be easily gotten with only 3 tc (cost of an emag)

**Comment by ghost** [comment]
I would be more concerned about it being winnable 100% of the time.

**Comment by Gringonius** [comment]
This needs more priority. Anyone who knows how to beat the machine can destroy the round for 3TC.
