### ISSUE TITLE
Proposed alien rework

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8295]
As an alternative to #8261 
While I like where facehugger rework has led to in terms of balance, it's a rework that does not favor player agency, but instead favors facehugger spam. It's not how aliens should really be played. I'd rather see aliens themselves buffed.

Here's some ways I think we can approach this (presuming we just nerf facehuggers to not be able to rip off rig helmets):
- Make the aliens we have more resilient by increasing their maximum health (except maybe queenie)
- OR add third-stage aliens for hunter and sentinel

Not sure what a third stage hunter would do, but I'd like a third stage sentinel that acted primarily as a beefy bodyguard for the queen.

**Comment by CptWad** [comment]
Queen dont need more health and xenos can tank enough damage
third stages are cool. Giving them new abilities is hard on their own.

**Comment by gbasood** [comment]
I honestly don't think they CAN tank enough damage though
Most hunter players die so quickly it's ridiculous
If we implemented third stages, those third stages should be tankier regardless, I think

**Comment by ghost** [comment]
Nah I think xenos being buffed is a good thing. They're weak as get out as it stands especially compared to the movie. Give more health to xenos and cut back on amount of facehuggers.

**Comment by CptWad** [comment]
thats because anyone who picks hunter does not know how squishy they are. Point of hunter is to be quick not bulky.
If you want to nerf eggs make resin cost 50 and eggs cost 100

**Comment by gbasood** [comment]
Nerfing eggs could happen but I think that it should only happen if we make aliens themselves better
Doesn't resin already cost 50

**Comment by unid15** [comment]
> thats because anyone who picks hunter does not know how squishy they are

They have the most health out of all other castes (except for the queen). 250 versus drones' 100 and sentinels' 175

**Comment by CptWad** [comment]
Oh for real? That points to something else than.

@gbasood Resin costs 75 while weed nodes cost 50. Also could you remove the dropdown menu and just add them all as verbs on their own?

**Comment by gbasood** [comment]
@CptWad I'd actually like them to be HUD buttons or something but 510 fucks with the HUD so that can probably wait.

**Comment by CptWad** [comment]
yes hud buttons are better

**Comment by ghost** [comment]
Alien raw stats are fine, the problem is they can't efficiently employ what made them such a formidable opponent in movies - their mobility.

They take way too long to enter pipes, they can't slash open welded vents and scrubbers, they can't pounce and their acid is too slow to dissolve things and costs a lot, their queen is a slowpoke.

And most importantly, humanoid movement speed is too high. You can outrun them if your ping is good.

**Comment by unid15** [comment]
Also they can't melt rwalls

But a one handed man in a wheelchair can instantly destroy rwalls with one punch, after taking a creatine pill

**Comment by CptWad** [comment]
too swole to control
You know I would be fine if we removed the whole idea of keeping xenos contained because it never works in the first place. I think R-walls should melt at the speed regular walls do and let regular walls melt a tad faster. Machinery and doors and stuff can keep their current rate thats fine
Also melting should also melt all objects on the same tile so I dont have to spend 600 plasma melting 3 guns, or a pile of shards and rods I broke to pretty the nest up

**Comment by ghost** [comment]
I would also suggest making them able to switch between alien classes with an appropriate cooldown, i.e. a lone hunter that remained after all other aliens died could evolve to become a drone after being alive for long enough.

**Comment by ihadtoregisterforthis** [comment]
Aliens in other multiplayer games stay as weak beings that hit hard and fast.

For buffs there is the classics like acid blood, make it damage mobs or plating and wires. Make eggs open when hummies get near. Add the jump mutation to hunters and tag it "pounce".

**Comment by ghost** [comment]
> jump mutation

That thing is horribly overpowered, a shorter ranged version of it would do better.

> Make eggs open when hummies get near.

They already do, you just have to have your face exposed.

**Comment by ihadtoregisterforthis** [comment]
``	var/native                       // If set, non-native speakers will have trouble speaking.
``
Does this work properly?

**Comment by gbasood** [comment]
> a lone hunter that remained after all other aliens died could evolve to become a drone after being alive for long enough.

I like that specific circumstance, but I can also see it being abused potentially without a limitation (if he wasn't the only alien left)

**Comment by ghost** [comment]
I don't see how it would be abused if it takes 20 minutes or so between changes.

**Comment by gbasood** [comment]
> 20 minutes

jesus christ that's a huge delay

**Comment by ghost** [comment]
Also a channel time for the actual transformation, i.e. 10 seconds to morph into another class, then it goes on 20 min cooldown.

**Comment by ghost** [comment]
make it two minutes and it'd be fine

**Comment by ihadtoregisterforthis** [comment]
Allow transformation only into queen, not all xeno types. Evolution is lineal.

**Comment by ghost** [comment]
> Evolution is linear

Haaaaaaaa

**Comment by gbasood** [comment]
So since there's been no discussion from this, here's what I've got out of this:
- Make aliens more mobile by making their acid melt shit faster I guess
- Give them each a small health buff
- Make facehuggers not pull rig helmets off so we can go back to making aliens about aliens
- Give sentinels a fucking hotkey or something for spit holy shit old interaction methods

**Comment by uazuaz** [comment]
i don't like how the "spit neurotoxin" option works; choosing your target from a name list is awful, especially if you don't know who is who.
it could be something similar to the wizard's "lighting" spell: the "spit neurotoxin" option could appear as an icon on top of the screen, you click it to prepare it, then you click your target.
all other usual alien actions as plant weeds, corrode with acid, create resin wall, nests, etc, could be added as icons as well, the same way as mutant powers or wizard's spells.

**Comment by CptWad** [comment]
I am good with:
* Wizard lighting method
* Alt click method
or both
also remove aliens from the list of things you can spit neurotoxin at so I dont have to flip through a long menu

**Comment by clusterfack** [comment]
Make aliens not get fucked up by electricity because that shit is whack and fun for no one

**Comment by gbasood** [comment]
@clusterfack agreed

**Comment by Ephx1** [comment]
@gbasood You forgot @TermedClepe 's idea.
Xenos slashing open vents. Only from the outside of course, give it some sort of delay.
That way xenos can still claim territory to move about in, but allows humans to have some sort of semblance of a safe area.

**Comment by CptWad** [comment]
I dunno about that. Then the meta turns into just unwrenching the vents so the xenos can never use them. Pretty poinless

**Comment by Ephx1** [comment]
Oh well, it just makes half the station un-ventcrawlable leaving most of the xenos in the open which I feel doesn't mesh too well with them. Hunters are best popping out of vents fucking shit up as quick as they leave.

**Comment by PJB3005** [comment]
@CptWad issue is to unwrench them you need access to the air alarm which a lot of people can't be bothered to get.

**Comment by CptWad** [comment]
Or just hack the air alarm. Usually people who weld da vents are the assistant and engineer/atmostech folks who can get or have access

**Comment by gbasood** [comment]
Still, that makes cordoning off areas the station a LOT harder, which I think is an interesting thing to try.
