### ISSUE TITLE
Telepad missing circuit board

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8296]
The telescience telepad is missing a circuit board.

**Comment by 9600bauds** [comment]
As shitty as magic roundstart-only machines are, it would be a pretty big balance change if more telepads could be constructed

**Comment by ghost** [comment]
Why exactly?

The only department that could construct them would be science, which already has one. It's no more annoying than an off station comms console.

It's not like science can't already obliterate the entire station in 15 minutes without doing RND, toxins is a thing.

**Comment by 9600bauds** [comment]
salvage ship telepad

**Comment by Exxion** [comment]
Maybe make it so that only one can be in existence at a time

**Comment by 9600bauds** [comment]
deconstruct the only one in existence, rebuild it in salvage ship

**Comment by ghost** [comment]
@9600bauds
Again, what is wrong with that? Anyone can make any number of station controlling consoles on salvage ship, it doesn't even take a fraction of the effort and is incredibly strong.

**Comment by 9600bauds** [comment]
Deep space telecult gg

**Comment by Exxion** [comment]
If you manage to deconstruct the telepad you deserve to be able to steal it

**Comment by ghost** [comment]
> cult needs teleporting machinery

It's totally not like cult has fucking infinite teleport runes.

**Comment by 9600bauds** [comment]
I meant as in teleporting people from the station by using a CMC.

**Comment by ghost** [comment]
People would just turn off sensors after the first report.

**Comment by Shadowmech88** [comment]
You'd think that, but even now the cult still occasionally manages to make good use of the telepad despite it being anchored in Telescience.

**Comment by Ephx1** [comment]
The telepad is already a potent tool in telescience.
Now imagine that, but absolutely anywhere and without the prying eyes of the AI, warden, or other researchers.
It would make suit sensors a death sentence.

**Comment by AutismSpider** [comment]
if you could move the pad or build more people will never turn the sensors it be ebin teleport death trap into god fucking no's were.

**Comment by Zth--** [comment]
Other servers have them constructable and haven't ever heard of problems with it.
Actually it would add something new to be creative with, and some fun gimmicks

**Comment by ghost** [comment]
Imagine we had a console that could scrub all the air from entire station regardless of where it is. 
Imagine we could gib people in a 7 tile radius with few minutes into round.
Imagine we could destroy a canister and kill entire station.
Imagine we could print more guns than there are in the entire armory few minutes into round.
Imagine we could instacrit players using an no-lockbox gun that costs only metal, a tank and a floor tile.
Imagine if 5u of mutagen could kill a player.

You seeing a pattern here?

**Comment by 9600bauds** [comment]
I don't think any of those would work very well for Cult

**Comment by ghost** [comment]
I have literally never in the years I've played ss13 seen cult use a telepad to abduct people.

Must have something to do with them ALREADY HAVING TELEPORT RUNES.

**Comment by Shadowmech88** [comment]
I'm pretty sure teleport runes can't be used to transport non-cultists.

Telescience conversion is very easy. You just put a rune down over the telepad, start spamming it, and have a second guy teleport someone in. They're converted before they even know what's happening.

**Comment by Zth--** [comment]
Yeah but after the second convert, people realize that teleport room is full of cultistss. I've seen it happen. It happened to me once too

**Comment by Ephx1** [comment]
I don't think much of that compares to something that can move people off z-level completely silently into a deathbox. Sure you could have people talk about it, but it would take some time before everyone catches on.

**Comment by ghost** [comment]
They can convert someone on the spot and teleport away. Their stuns prevent speaking and leave enough time for everything.

Regardless of what you think of the balance aspect, it's a terrible inconsistency to have snowflake machines because muh potential ham.

In fact you could make every single item replicable IC and it would pose absolutely no problem, even transfer valves just sit unused in toxins most of the rounds.

**Comment by gbasood** [comment]
@TermedClepe You're right, let's let everyone set up singulo gens in dorms

**Comment by ghost** [comment]
They can literally do that, in fact I setup and released 3 singulos in various places simultaneously as a botanist just by asking hop for cargo access.

**Comment by AutismSpider** [comment]
@TermedClepe  We have two things for Air stuff and i only seen it use by rouge Ais who know how to work atmos/rouge mommis to flood in death mix faster/void all of the air in the station

**Comment by ghost** [comment]
Lately I find myself wondering why I even bother reasoning with people as ignorant as in this community.

**Comment by 9600bauds** [comment]
What did that post accomplish?

**Comment by clusterfack** [comment]
Why are you even here termed?

**Comment by robintime** [comment]
fixed by #27274
