### ISSUE TITLE
Make a Popup Window to Tell People They're Antags

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8310]
Sometimes people are AFK when the round starts, and when they get back, chat has scrolled up enough that they do not see their antag announcement, meaning they don't know they're antags at all.

This might be remedied with the inclusion of a popup window upon assignment as antag, since a popup window wouldn't go away until the player acknowledged it.

**Comment by Ephx1** [comment]
I like this idea.
If they don't acknowledge it in a minute they get gibbed؟

**Comment by ghost** [comment]
:+1:

**Comment by PJB3005** [comment]
@Ephx1 that's silly and it adds a shitload of metagame because 1 AFK can basically spoil the round type completely.

**Comment by Imagebard** [comment]
@PJB3005 
What?
What?
What?

How can someone who's afk spoil the round type? I don't follow.

**Comment by Ephx1** [comment]
He's referring to my joke about the gibbing.
As in, a braindead traitor would explode after some time.
EDIT: there, now with 100% authentic sarcasm punctuation

**Comment by Imagebard** [comment]
Oh, I ignored the @ mention, I came here to discover why this had a "QUALITY" tag.

**Comment by ihadtoregisterforthis** [comment]
"Antags" meaning "Traitors", right? Raiders, Wizard and Nuke ops should be really obvious, Lings and Vamps have different HUDs, Revs and Cult have the distinctive icon on top. Traitors, Double Agents, Blob and Malf are the only ones that could go unnoticed for long.

**Comment by Imagebard** [comment]
>Traitors, Double Agents, Blob and Malf are the only ones that could go unnoticed for long.

And is this not a problem?
Traitors are okay.
Double Agents have people gunning for them.
Not noticing that you're a blob can end the round quickly.
Malf can be noticed later, but you're wasting precious time.

**Comment by ihadtoregisterforthis** [comment]
Yes, it can be a problem but not for all types of antags.

**Comment by SonixApache** [comment]
This'd be nice, since I've actually gone rounds as a roundstart borg where I didn't realize it was malf till the AI told me.

**Comment by AlphaBuffalo** [comment]
How about a popup window that counts down from like 5 or so minutes making sure the player is there to acknowledge he is an antag and if he doesn't respond his antag will be moved to an active player

**Comment by gbasood** [comment]
:+1: to original suggestion
