### ISSUE TITLE
Nuke seconds appear to not be real-life seconds

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8311]
I have noticed this fairly often, but related to other "real" timers like the shuttle timer or the round time, the nuke appears to count down roughly every two seconds. In all cases, a 60s nuke countdown lasts much longer than 60s

**Comment by Shadowmech88** [comment]
The nuke probably counts down every tick rather than every second. I'd imagine many other time-based objects like the brig cell timer and the assembly timer do the same.
