### ISSUE TITLE
ERT has fuck-all access for some reason

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8313]
The access on the ERT crew is horrible, they can access only their armory (including the door that leads outside of it for some stupid reason)

They can't access their own shuttle to launch it, and apparently can't even access some parts of the station like the Command Complex

**Comment by SonixApache** [comment]
AFAIK admins are supposed to lead them off centcomm and edit the IDs to give them basic station access.

**Comment by Imagebard** [comment]
>admins are supposed to lead them off centcomm and edit the IDs to give them basic station access.

Holy fuck what.
You can try to call a ERT without admins online, so the ERT should work without admins.

**Comment by Shadowmech88** [comment]
This has been a problem for a long time.
See #7844 and probably earlier issues.

**Comment by ghost** [comment]
They also get no mag boots despite having a full engineering loadout.

**Comment by AutismSpider** [comment]
was that hest res/rad res shit fix on the ERT suits yet.

**Comment by Zth--** [comment]
Give them all access already

**Comment by Intigracy** [comment]
ERT's have all access as far as the station is concerned, unless that was something that only syndicate deathsquads have.

I don't think they have all access for centcomm.

**Comment by ihadtoregisterforthis** [comment]
I noticed before that as ERT I couldn't enter cargo. The explanation back then was that the power, bolts and ID check were all tampered, on all doors. That doesn't sound impossible really, but a double check doesn't harm.

**Comment by Intigracy** [comment]
I may be wrong, the only squad (there's 3, syndi deathsquad, deathsquad, and ERT) that I'm positive has all access is syndi deathsquad because I was in the code earlier this week.
