### ISSUE TITLE
Treadmills take less than a minute to bring you to 100Cº, at which point, they still give you massive burn damage and also exploding knees

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8314]
![stock-vector-rubber-stamp-with-text-one-hundred-percent-tested-confirmed-inside-vector-illustration-287448125](https://cloud.githubusercontent.com/assets/6526157/13089847/686db4b0-d4d1-11e5-9206-d878d48003df.jpg)

**Comment by ghost** [comment]
Why isn't there a 100% Tested tag yet.

**Comment by 9600bauds** [comment]
![dreamseeker_2016-02-16_17-24-26](https://cloud.githubusercontent.com/assets/6526157/13090014/2be2a1c6-d4d2-11e5-8bca-bc261a57f673.png)
Health analyzer report of sporting man

**Comment by Ephx1** [comment]
His fucking legs exploded, hot damn

**Comment by AutismSpider** [comment]
massive burn and exploding fucking kneecaps.

![knees](https://cloud.githubusercontent.com/assets/10268342/13090276/610b112a-d4ba-11e5-97e7-09dbdc43af80.png)

**Comment by Exxion** [comment]
Why hasn't anyone pinged @DrCelt yet?
@DrCelt @DrCelt @DrCelt @DrCelt @DrCelt

**Comment by ghost** [comment]
AAAAAAAAAA

**Comment by Shadowmech88** [comment]
@DrCelt 
Test your shit.
If you'd actually used a treadmill to verify that your fix to treadmills worked, you would've found out that the fix didn't work.

**Comment by ghost** [comment]
It did work it just didn't work as well as I hoped it would.

**Comment by Shadowmech88** [comment]
> I fixed treadmills, guys!
> Now instead of husking you, they just blow your legs off and burn you to death!

I wouldn't call it a fix.

**Comment by ghost** [comment]
There's room for improvement, yeah.

**Comment by Exxion** [comment]
No you really obviously didn't test your original fix though
_Two seconds._

**Comment by ghost** [comment]
A mistake was made.

**Comment by 9600bauds** [comment]
twice

**Comment by Exxion** [comment]
YOU DIDN'T TEST IT
EVEN I SOMETIMES TEST THINGS

**Comment by 9600bauds** [comment]
Also you can not-help-intent push people to FORCE them to walk on a treadmill

**Comment by Exxion** [comment]
In Celt's defense, that isn't his fault

**Comment by 9600bauds** [comment]
I know, but it's hilarious

**Comment by 9600bauds** [comment]
Make it so that emagged treadmills do this
New perma execution method for Sec if they confiscate an emag

**Comment by clusterfack** [comment]
All these spess nerds are dying on the treadmill because they skipped leg day too many times

**Comment by ghost** [comment]
Muscles do deteriorate in low gravity.

**Comment by Exxion** [comment]
Except we have a gravity generator that generates gravity so intense you can't even lift yourself onto a table

**Comment by gbasood** [comment]
Treadmills also give MoMMIs brute damage what

**Comment by Exxion** [comment]
They damage anything that can power them, yes

**Comment by Shadowmech88** [comment]
If anything, silicons should have their cell drained by running on a treadmill.

**Comment by NigglyWiggly** [comment]
![](http://puu.sh/naBu3/40ad3e3771.png)

This shit is insane and I love it.

**Comment by 9600bauds** [comment]
new meta

**Comment by Killette2** [comment]
Another fun thing THAT SHOULD NEVER BE FIXED is that you can put a conveyor belt under a treadmill to make it walk for you, EVEN IF YOU PASS OUT. Enjoy torturing people with treadmills!

**Comment by Arthurdentist** [comment]
this sounds like something an emagged treadmill should do. That might be fun.

**Comment by Kitfox88** [comment]
what are treadmills even for

besides making people burst into flames and have their legs explode after bucklecuffing them to a roller bed and sticking it on one

actually does that work, someone test that

does using a wheelchair make your arms explode instead? what about jani/clowncart

**Comment by Shadowmech88** [comment]
Originally treadmills were for meager power generation.

**Comment by NigglyWiggly** [comment]
@Arthurdentist 
Emagged Treadmills should function like the one i set up in my screenshot.
They should just continue to move regardless of if you are running on them

**Comment by Imagebard** [comment]
Holy shit did it really kill a Diona

**Comment by NigglyWiggly** [comment]
Yes. All of the bodies around there are from the treadmill.

Including the body currently on the treadmill, which is a regular human.
With invincibility toggled on.

**Comment by ghost** [comment]
He's not dead though at least

**Comment by Shadowmech88** [comment]
Treadmill, slayer of gods.

**Comment by Imagebard** [comment]
![1455012536325](https://cloud.githubusercontent.com/assets/7571238/13118869/10e0eb4a-d585-11e5-874d-eef6bc9b994e.png)

How do you fuck up that bad

**Comment by Exxion** [comment]
> With invincibility toggled on.

Celt what the fuck
Celt what the fuck
_Celt what the fuck_

**Comment by PJB3005** [comment]
**_Celt what the fuck**_

**Comment by Arthurdentist** [comment]
![i wasnt quite sure what i had just seen](https://cloud.githubusercontent.com/assets/6353372/13119223/f38e829e-d59f-11e5-82d7-f8b5bdb55448.jpg)

**Comment by ghost** [comment]
He was still alive, just his legs had exploded. That's how all damage works on invincible mobs.

**Comment by 9600bauds** [comment]
tis but a flesh wound

**Comment by Kitfox88** [comment]
I can't join the test serb to see how roller beds and wheelchairs act

abloo

**Comment by FudgePucker** [comment]
> Incapacitates god mode mobs, you know, the ones immune to stun and everything else

Yup

> 100% tested

**Comment by ghost** [comment]
@FudgePucker That's literally what all damage to god mode mobs does though

**Comment by NigglyWiggly** [comment]
Invincibility is fucky as hell, that's not a problem with Treadmills so much as it is one with invincibility
You can kill 'invincible' people relatively easily, but it seems like they're mostly immune to certain other types of damage, like bombs and pressure and stuff

**Comment by Arthurdentist** [comment]
Dear, 


I just wanted to  say Hello and  to show you that stuff, just  check  it out <http://dear.customdigitalscrapbooks.com/e7nhltpb>


Be well, dbaggley

**Comment by Shadowmech88** [comment]
?

**Comment by Exxion** [comment]
That's mildly troubling.

**Comment by ghost** [comment]
What is

**Comment by Exxion** [comment]
It got deleted, but there was a comment from @Arthurdentist that looked suspiciously like an account-hijacking (or something) spam post

**Comment by Shadowmech88** [comment]
It came from his email, so maybe some kind of bot that got his email password and was spamming replies to all his recent emails?

**Comment by NigglyWiggly** [comment]
His email got hacked or something, should be fixed now
