### ISSUE TITLE
Can't change job preferences with left mouse button

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8315]
Only works with right mouse button. Job preferences as in low/medium/high etc.

**Comment by uazuaz** [comment]
sorry for the dumb question, but this happens every time or only when you have readied up? because i think you can't change some options when you ready up.

**Comment by ghost** [comment]
Every time. It always works with right click, never with left click. There was a PR that added right click functionality a while ago.

**Comment by gbasood** [comment]
It was working fine for both clicks when it got added. I'll test it now on the serbian.

**Comment by gbasood** [comment]
Can't reproduce, works fine on serbian. It's possible you were trying to left click solely in time frame between accepted inputs where clicks do literally nothing though.

**Comment by ghost** [comment]
No that is not possible, because I am clicking at the same spot with both left and right click. Only right click registers.

This is the commit that causes it https://github.com/d3athrow/vgstation13/commit/caabfef1d249d594538533f61afd6173b1d32469  @d3athrow

**Comment by Exxion** [comment]
Works fine for me too, on local at least

**Comment by gbasood** [comment]
Are you running on non-Windows or something?

**Comment by ghost** [comment]
No, it's probably something to do with IE. Either way it shouldn't be happening as left click worked fine previously, so clearly there is a way to make left click work.

**Comment by gbasood** [comment]
Unless it's IE's fault because of terrible standards somehow
I'll leave it open for now

**Comment by ghost** [comment]
Further testing reveals left click is actually selecting the text of the button.

**Comment by brokenboundarie** [comment]
I am having the same problem. Right click will cycle through job prefs but left click does nothing. Running on Windows.

**Comment by Intigracy** [comment]
Have you tried updating IE?

**Comment by Shadowmech88** [comment]
Given the difficulty in reproducing this and the time since the report was created, I think this can be closed.
