### ISSUE TITLE
satchels

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8316]
scientists spawn with a regular gray satchel, but i saw that there are scientist satchels on metaclub; i don't know if this happens with other jobs, but if there are specific job satchels/backpacks people could spawn with them by default.

![satchel](https://cloud.githubusercontent.com/assets/6170726/13091330/e3ac8786-d4fa-11e5-8f56-5c8f67b2e74f.jpg)

**Comment by Exxion** [comment]
It happens with some other jobs, yes, but not all

**Comment by SonixApache** [comment]
I was actually thinking of doing this myself. Chemists also don't spawn with chemist satchels.

**Comment by PJB3005** [comment]
Scientists do get handed these...

If their job title is plasma researcher...

Oldcoders are bad at design.
