### ISSUE TITLE
Summon guns is awful

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8317]
Makes random, objective-less traitors and gives guns out like candy. Adminbus button level of stupid. Rounds with summon guns often end in a quick death for the wizard and a long round for everyone else.

remove summon gun

**Comment by ghost** [comment]
It's bad because it makes antags and it's bad because it kills wizard?

You can't complain about it making long rounds when the same thing already makes more antags. Maybe give them objectives, but it's fine as it is.

**Comment by ihadtoregisterforthis** [comment]
Based on other issues this is a feature request.

**Comment by gbasood** [comment]
@TermedClepe Would you in your vast metagaming knowledge ever pick summon guns as one of your spells

**Comment by ghost** [comment]
No because it makes my enemies stronger.

Some people like pain though. Or just want to make a round as chaotic as possible.

**Comment by Arthurdentist** [comment]
I believe survivors should get more explicit traitor objectives to make it clear they are traitors and can indeed do 'traitorous' things. 

Basically I agree with @TermedClepe

**Comment by Exxion** [comment]
I've never been in a round in which I'd say summon guns made it worse. In some rounds it made it better and in others it had little effect on the overall quality, but it's never made it worse. In my opinion, it's one of the better spells.
But yeah, maybe give the survivors objectives.

**Comment by Killette2** [comment]
What if summon guns did a forced shuttle call with a 30+ minute timer also? That way it won't turn into WIZARD DED IN 5 MINS, NOW WE EXTENDED + GUNS + A FEW PEOPLE CAN GRIFF IF THEY FEEL LIKE IT BUT PROB WON'T BECAUSE EVERYONE HAS GUNS

**Comment by ghost** [comment]
Why should rounds end when wizard is killed?

Rounds don't end when traitors are killed, or changelings, or nuke ops, or pretty much anything. I'm not so sure about vox because that is one fucking terribly coded mode.

Rounds are not just about antags, people do projects and they give up because they know round will end with wizard dying. I personally just drop everything and kill him to get it over with instead of playing with the thought it can be over at any moment because someone will valid wizard.

**Comment by Killette2** [comment]
It should because the wizard is the MAIN ANTAGONIST.

Throughout all your murderbones, you might forget that ss13 is a theater. Wizard is supposed to be the tension of the round, and when the tension's gone, the round stagnates. When all traitors die, admins at least usually have the decency to make new traitors if the station isn't fucked up enough for a shuttle call.

This is also why raging mages is shit, it takes 1 powerful antag, who usually should take the oportunity to roleplay instead of be traitor+magic, and makes multiple of them leading to a clusterfuck. The only redeeming part about raging mages is that it teaches people, minorly, how to be less shit of a wizard.

**Comment by CptWad** [comment]
My take was give the guns ONLY to survivors
that would definitely cause strife and making spamming the spell worth-wile

**Comment by ghost** [comment]
But the whole point is that it's referencing that one comic about wizards not knowing the difference between right and wrong by giving everyone a gun

**Comment by gbasood** [comment]
> This is also why raging mages is shit, it takes 1 powerful antag, who usually should take the oportunity to roleplay instead of be traitor+magic, and makes multiple of them leading to a clusterfuck. 

sounds like an ideal round to me honestly

**Comment by gbasood** [comment]
As for round ending when the wiz dies, if we manage to make survivors actually man up and do something instead of waiting for the round to end, then we should NOT make the round end when the wiz dies. Otherwise, maybe have the survivors be tied to the wizard being alive and remove their survivor status when he dies.

Actually that'd make survivors apprentices with no spells and guns instead, in metagame terms. Hm.

**Comment by AutismSpider** [comment]
Summon guns does shit job at making the round more chaotic use summon guns in round with 30+ or so people only 8 of them get antag that should be way higher like 70% or 65% crew should turn antag form it and only the antags get the guns

**Comment by CptWad** [comment]
70-65% is a bit much
30% who get guns and antag would definitely start enough chaos. That way you could summon 2 sets of guns and watch the mayhem

**Comment by gbasood** [comment]
So let's narrow this down a bit.

We seem to agree that survivors should have better objectives to drive them to create chaos, right? So what objectives should they get? Survive isn't enough, they'll just go about their shift and try not to get killed which is the opposite of chaos.

**Comment by CptWad** [comment]
How about a "Have 1-4 guns" objective?
That would be good should we not restrict the guns to the survivors

**Comment by AutismSpider** [comment]
Give them head hunt objective Wiz man could end up on this list of heads to

**Comment by Imagebard** [comment]
>Only traitored people getting guns

THAT DUDE HAD A GUN SPAWN UNDER HIM, LETS VALID HIM!

**Comment by CptWad** [comment]
Yeah thats the point
but he has a gun and you dont
I can have a guess as to what the turnout will usually be

**Comment by PJB3005** [comment]
@CptWad it depends what gun he got, if it's got stunning or he got the gatling gun he wins, else the other people will wreck him.

**Comment by gbasood** [comment]
Two secmans are talking to eachother.
Wizard summons guns.
One of them gets a gun. Any gun. The other immediately pulls out his taser because meta
Who wins

**Comment by CptWad** [comment]
The quickest draw obviously

**Comment by Intigracy** [comment]
no you're awful
:(

**Comment by clusterfack** [comment]
If someone wants to change the name/role/objective of the Survivor antagonist to resolve this, I'd be down for it

**Comment by Intigracy** [comment]
Why not remove the survive objective from survivors and give them a protect wizard objective, but with a much smaller amount of people getting survivor?

**Comment by Killette2** [comment]
The protect wizard idea is only good in theory. It will just lead to situations where someone who was supposed to protect the wiz didn't see the protect message or didn't care, and killing the wizard anyways just calling for more bans, bitching, and this round end has been delayed.

**Comment by Shadowmech88** [comment]
Perhaps the survivors should get objectives to kill other specific survivors, in order to create conflict.

**Comment by Intigracy** [comment]
We can make them able to see the wizard's HUD icon, which is a pretty big
indicator that they're on your team.

**Comment by Imagebard** [comment]
Remember that to actually have survivors work with the wizard, you'll need to get them classified as team antags by nuclearcellphoneg or whoever is the current headmin.

I'm fine with them not being forced to help the wizard, mind you. I just wanted to put this out here.

**Comment by Intigracy** [comment]
The idea to have them kill other survivors has merit too.

Turn them into "wizard's champion" fighting for the glory of the wizard by killing all of the other champions. They'd even have HUD icons to tell who else is one, considering magic is the one compelling them.

There can be only one.

**Comment by Killette2** [comment]
So summon guns creates a mini highlander for a few select people? I like that idea, people murdering others and the innocent crew caught in the middle trying to stop the fighting and the wizard.
