### ISSUE TITLE
You are unable to interact with anything when blind

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8323]
I want you to close your eyes, and attempt to open a box that you felt on the table in front of you. Impossible right?

NO.

**Comment by Ephx1** [comment]
I'm fairly certain this was a thing that you could do, as long as it was within your tiny Halo vision.
Why was it changed? I think it would be best if the whole screen was black and you had to 'feel' around with your cursor.

**Comment by Exxion** [comment]
You can interact with things on your own tile while blind. Just not on any other tiles.
But yes, it would be nice to be able to pick the imidazoline up from the table beside you so you could take it

**Comment by 9600bauds** [comment]
I think this fucked up at around the same time as darkness was made clickable

**Comment by SonixApache** [comment]
You can still rightclick stuff to interact with it, just can't leftclick.

**Comment by Shadowmech88** [comment]
It's now possible to click things without being able to see them, for example firing a gun in complete darkness.

Now that we have that capability, it might be better to make blindness a COMPLETELY black screen, and allow normal interaction with things except computers and other machinery.

**Comment by robintime** [comment]
tested locally, this bug no longer occurs (although it takes a few tries to get the container and not just part of the floor)
