### ISSUE TITLE
Multiple Borers in the Same Host

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8329]
Feature request/discussion.

I'd like it if borers could choose which region of the body to infest by targeting it and, based on the chosen region, confer different benefits to their host. Infesting an arm would give it the ability to temporarily buff the host's melee attack power, while infesting a leg might give it the ability to increase the host's base run speed for a short time. Infesting anything except the head would result in greatly reduced variety of chemicals that can be produced.
This capability would mean that a single host could acquire more than one borer, and each additional borer would make them that much stronger, though all of them would have to work in unison to maximize the host's potential.

**Comment by ghost** [comment]
> groin

**Comment by ghost** [comment]
We parasyte now?

**Comment by clusterfack** [comment]
What if we make a being that is entirely made up of borers

**Comment by Ephx1** [comment]
A writhing mass of hyperzine, kelotane, and a million other drugs?
Oh, so you mean a Diona?

**Comment by AutismSpider** [comment]
@clusterfack  call a diona man

**Comment by Intigracy** [comment]
still gross

**Comment by Shadowmech88** [comment]
This was completed.
