### ISSUE TITLE
Cyborgs can't speak Sol Common

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#8331]
They can understand it, but they can't SPEAK it? You're telling me humans didn't make their robots to speak their damned language, but they did for tradeband?

**Comment by gbasood** [comment]
Same with other race specific languages

**Comment by Ephx1** [comment]
Well yes, but these are robots made with the specific intent of serving humans.
That'd be like a vox-made robot that couldn't speak their gobbledygook.

**Comment by Imagebard** [comment]
It can serve humans just fine.

And they're not made for helping humans, otherwise they would just be locked to Asimov instead of having a "module upload console" for syndicate agents to mess with.

**Comment by Ephx1** [comment]
It just doesn't make sense when they get some tradeband language that very few people speak, but not the language of their creators that make up a majority of the station.

**Comment by Imagebard** [comment]
What is this about Borgs getting tradeband
Do you have tradeband set up by default, Ephx?

**Comment by Ephx1** [comment]
No, it's a thing borgs get for speech for some reason. They also had gutter but that was removed for some other reason.

**Comment by Imagebard** [comment]
>They also had gutter but that was removed for some other reason

I have a feeling its a oversight, bug, or something like that.
Why are you basing your argument on a oversight, bug, or something like that?

**Comment by Ephx1** [comment]
Because I don't know if it's an oversight, bug, or something like that.
Even still, I find it nonsensical. Is them getting tradeband also some sort of bug? A language maybe two people speak in-game?

**Comment by SonixApache** [comment]
Language modules when?
Tradeband/gutter is probably from character preferences.

**Comment by ihadtoregisterforthis** [comment]
[Feature request]

**Comment by clusterfack** [comment]
Yeah borgs should be able to speak the primary language of humans

**Comment by Ephx1** [comment]
I can also confirm now that the tradeband thing isn't due to preferences, my character had gutter as secondary.
