### ISSUE TITLE
Cloning pod can sometimes have more than one mob inside it, and will only empty one of them

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8336]
how the fuck that happened I'll never know

**Comment by ghost** [comment]
what

**Comment by gbasood** [comment]
A guy ahelped about someone else getting out of the cloning pod when they were still in it and walking off
But he was still in the cloning pod's contents
The icon state for hte pod was default, as if no one was in there, so I had to teleport them out

**Comment by ihadtoregisterforthis** [comment]
Something something storage atoms when

**Comment by ihadtoregisterforthis** [comment]
Is this what #12334 fixed?

**Comment by Exxion** [comment]
Yes
