### ISSUE TITLE
Defficiency Has No Spawn Area for ERT and Deathsquad

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8337]
The admins were completely unable to send either of them.

Thanks @Duny.

**Comment by 9600bauds** [comment]
@Duny-

**Comment by MrsTonedOne** [comment]
>Not making the centcom z level be forced common for all maps by making shuttles start on the station and moving them over during world init, and using different files for the z levels.

top kek mates.

**Comment by ghost** [comment]
Already addressed in #8297
