### ISSUE TITLE
Defficiency Goonecode Containment Doesn't Have Enough Security

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8338]
All you have to do is spacewalk around to the back, and then it's just a single rwall standing between you and the Goonecode, the spur, a ricochet rifle, a righteous bison, fairy wings, a spellbook of knock, and a hand tele.

For all that loot, the room seems a little bit too easy to get to.

**Comment by ghost** [comment]
@duny-

**Comment by FudgePucker** [comment]
I thought it was surrounded by an indestructible centcom wall?

**Comment by Shadowmech88** [comment]
I saw myself last round that it was not.
The vampire simply jaunted across the one-tile gap and grabbed all the loot.

**Comment by ghost** [comment]
I was certain Jaunting was disabled there. Blame vampire jaunt snowflake code

**Comment by Shadowmech88** [comment]
Regardless, it was still just an rwall. If they weren't a vampire they could've deconstructed the wall.

**Comment by Duny-** [comment]
The entire area is surrounded by super-reinforced walls, not reinforced, and if people would stop making snowflake ways of teleporting for one second ghosts and vampires wouldn't even be able to enter the space around it.

**Comment by Shadowmech88** [comment]
I'll make a new, more accurate issue then.
