### ISSUE TITLE
Give Borers the Ability to Control Monkeys

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8340]
Letting them control monkeymen would be a little excessively powerful I fear, but I see no reason why they shouldn't be able to control standard monkeys.

**Comment by ghost** [comment]
Just let them control any mob they crawl in and doesn't have a player controlling it.

**Comment by 9600bauds** [comment]
giant spider murderborer

**Comment by ghost** [comment]
Nothing is stopping from human non antags to go on murderboners, I don't see why that should change for other player controlled creatures. Administration problem.

**Comment by Zth--** [comment]
It's a good idea, but what would happen if the monkey's SE is changed to be human?

**Comment by Shadowmech88** [comment]
Remove the borer's control and take away the option for it. It'll just sit in the monkeyman's head until it gets bored and decides to leave.
