### ISSUE TITLE
Can no longer use a pen to label a beaker

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#8346]
Revision: b096f4a8fe2ae92e786f0103352258c27e795210 

Before, you could grab a pen (from your PDA) and hit the beaker with it to just name it. Ten character label limit or something. 
This functionality is now gone entirely; applying pen to beaker does jack shit.

**Comment by Intigracy** [comment]
someone assign me

**Comment by 9600bauds** [comment]
i cannot

**Comment by DamianX** [comment]
No longer true, pen works again. CLOSE IT
