### ISSUE TITLE
Rewriter drink description typo

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#8347]
Revision: 090bd47179bdfc32fc3c3e5cff3c6216138ee6f4 

![The secert of the sanctuary of the Libarian...](http://puu.sh/ncrPy/3fe632e6b1.png)
Is this on purpose?

**Comment by ihadtoregisterforthis** [comment]
˃makes a typo on a typo report

**Comment by SonixApache** [comment]
the irony is palpable
much like with the recent grammar fixes that had typos in their titles

**Comment by Shadowmech88** [comment]
Sounds like it needs to be rewritten.
