### ISSUE TITLE
Organic Debris limbs from event keep moving forever

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#8348]
Limbs from the Organic Debris Field event will keep on trying to move to their destination regardless of what's in their way. They will stop as normal as soon as they hit an obstacle but when that obstacle is removed it will continue to move again until it hits another obstacle (or presumably its destination).

It will do this EVEN IF YOU PICK IT UP AND THROW IT IN THE OPPOSITE DIRECTION. It will just boomerang back while attempting to return to its original destination. It will even move laterally (sideways) if it has to.

**Comment by Exxion** [comment]
And picking them up is fucked

**Comment by Kitfox88** [comment]
> It will do this EVEN IF YOU PICK IT UP AND THROW IT IN THE OPPOSITE DIRECTION. It will just boomerang back while attempting to return to its original destination.

requesting the IT'S A FEATTTTTUUUUUUUURRRRRRRRE tag

**Comment by Exxion** [comment]
To be honest, the fuckery involved with picking them up is worse
#8232 
If you click one, its sprite will appear in your hand, but it will also remain on the ground. Putting it in a storage item puts its sprite in, but this sprite doesn't actually take up a slot and cannot be interacted with. Dropping the sprite from your hand will teleport the limb/organ to your position. And, as mentioned here, it will NEVER STOP on its quest to reach wherever the hell it wants to go

Oh, and you can pick it up as many times as you want
You can have it in both hands and a fake one (but only one) in your backpack while watching the actual one sit/slide on the ground

**Comment by ihadtoregisterforthis** [comment]
Boomerangs when?

**Comment by Killette2** [comment]
Ghetto weapon boomerangs made with wood. Has a 5% chance to knockout, can attach sharp things to it to make it deadlier instead.

**Comment by 9600bauds** [comment]
Closing in favor of #8232
