### ISSUE TITLE
xenomorph language issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8349]
i was a human, a wizard turned me into a drone, then i evolved in a queen;
i could understand other xenomorphs only via hivemind chat, whit regular talking i couldn't understand anyone of them.
i can assume that other xenos were mutated humans too.

![xeno](https://cloud.githubusercontent.com/assets/6170726/13148063/f072b758-d65b-11e5-945a-a7292db51a64.jpg)

**Comment by ihadtoregisterforthis** [comment]
Those aliens aren't hissing

**Comment by ihadtoregisterforthis** [comment]
![polyglot xenos](https://cloud.githubusercontent.com/assets/13305885/13148887/e790aadc-d63d-11e5-98a0-a2b8d0dea215.png)

**Comment by Exxion** [comment]
They appear to be speaking Common

**Comment by ghost** [comment]
I'll guess the queen xeno is stripped of common when evolving

**Comment by Ephx1** [comment]
It's staff of change fuckery, Xenos made this way speak Common, but like Celt said, when they evolve into something else they lose it.

**Comment by Exxion** [comment]
This sounds similar to #8153 
I bet the SoC just makes a new mob and puts you in it rather than changing your mob
But I don't know if we have a proc for changing your mob to something other than some kind of `/mob/living/carbon/human`

**Comment by Shadowmech88** [comment]
No longer exists. All xenomorphs produced via staff of change appear to speak only Xenocommon, the same language as regular xenomorphs, and so they should all be able to understand each other.
