### ISSUE TITLE
Vampires don't heal organs in coffins

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8352]
Coffins heal vampires to 100% health but do not fix organ damage, meaning if you have ruptured lungs you have to suicide and cheat death to fix it.

**Comment by scrdest** [comment]
Feel free to steal my rewrite of coffinhealing for Urist, maybe strip it out of a togglable ability back to a sleeping check if you want to.

It does relatively slower healing over time, but heals the vamp to completely full health.
