### ISSUE TITLE
A few seconds under a hot shower will eventually burn you to death

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8358]
Wrench shower to hot setting, stand under it for a second or two. Marvel as you burn to death even after you leave.

**Comment by ghost** [comment]
What I'll do is have it deal burn damage more and heat you up less

**Comment by ghost** [comment]
Sounds good, just test it so it's not a death sentence from pain in few seconds under.

Same for cold setting.

**Comment by SkowronX** [comment]
This is pretty glaring and better be fixed soon.

**Comment by ghost** [comment]
Can confirm, stops at 300°C, but climbs ridiculously quickly

**Comment by Probe1** [comment]
el oh el

**Comment by ghost** [comment]
It's okay, I'm on the case now

**Comment by Probe1** [comment]
I'm recording this for posterity

> [17:32:03]ADMIN: MOD: Dylanstrategie/(Henry Alouette) : Oh god, I HUSKED under that shower

**Comment by gbasood** [comment]
why gas the vox when you can shower them
