### ISSUE TITLE
There are four hydroponics mutations that can be rolled for but can't be applied for various reasons

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8359]
The thorny, creeping spread, vine spread, and parasitic mutations cannot actually occur. The first three are trivial fixes; they are simply broken because the strings that `pick_mut()` returns that correspond to them are not the same ones `apply_mut()` looks for.
Parasitic is slightly more broken. `apply_mut()` doesn't seem to have code to apply it at all, no matter what string it is passed. It wouldn't really be hard to add, though.

I'd go ahead and fix them all except it might be a somewhat substantial balance change and I'm not sure if any of them were left out on purpose.

@9600bauds

**Comment by 9600bauds** [comment]
rip

**Comment by 9600bauds** [comment]
I was hoping the error would make this type of oversight immediately evident, even had a few people test it and they only reported one of such problems, in hindsight I should have just done this in a less shitty and more OOP way. I started to really hate botany3 by the end though so I just left it as is. Will fix now

**Comment by Exxion** [comment]
I've been looking at the runtime logs to patch some shit up
That's how I found it

**Comment by 9600bauds** [comment]
Holy fuck I really winged this code
I was so tired of looking at it
