### ISSUE TITLE
Universal enzyme has no recipe

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8360]
There is no recipe for obtaining the universal enzyme.

**Comment by Shadowmech88** [comment]
I don't believe there are any recipes that consume it, it only serves as a catalyst.
In the case that the bottle is somehow lost, is there no crate one can order from Cargo that contains it?

**Comment by 9600bauds** [comment]
Yeah, you can get more from Cargo

**Comment by AutismSpider** [comment]
enzyme just a catalyst for recipes can order food crate for new bottle of the stuff any way.

**Comment by ghost** [comment]
I know about the crate and enzyme being a catalyst, I'm thinking ahead here and suggesting a recipe for it mainly for survival situations like the snowmap where a cargo shuttle will most likely not dock.

It's used for cool things like making booze out of nutriment.

So perhaps mark it feature request to be more descriptive.

**Comment by 9600bauds** [comment]
Seemed like a botched bug report from the OP

**Comment by 9600bauds** [comment]
Since this is a feature request, might be worthwhile to throw around some ideas on what the recipe would be

**Comment by Shadowmech88** [comment]
Mixing the juice of multiple different fruits/vegetables?

**Comment by SonixApache** [comment]
grow it from virology

**Comment by AutismSpider** [comment]
mix the juice of multiple fruits and vegetables for it sounds fine 5 units of veg/fruit juice

**Comment by Kitfox88** [comment]
salt + sugar

**Comment by Shadowmech88** [comment]
Enzymes are proteins, it would make no sense to create it by mixing a mineral and a carbohydrate.

**Comment by ghost** [comment]
Nutriment, carbon, milk? Actually carbon is hard to get in ghetto way afaik, so something else. But nutriment makes sense.

**Comment by 9600bauds** [comment]
> carbon is hard to get in a ghetto way

5u water in ghettobar microwave
Ultimately though I'm not sure if universal enzyme should be ghettochemmable

**Comment by ghost** [comment]
Oh neat.

**Comment by Killette2** [comment]
Sugar + spice + everything nice?

**Comment by CptWad** [comment]
It used to be obtainable from vomit, you would scoop it up in a glass and do something else to it I don't remember. It was a long time ago
also *vomit when?

**Comment by Imagebard** [comment]
>It used to be obtainable from vomit

Really now.

**Comment by ghost** [comment]
> scooping up vomit

What could go wrong. Would be pretty neat.

**Comment by CptWad** [comment]
that was waaaay back ago
![r8uh3r](https://cloud.githubusercontent.com/assets/3959840/13184609/c16bfeba-d6f1-11e5-8684-dcdffd6f5fca.png)
Actually it might have been the recipie for cheese now that I think about it more, vomit + milk or something

**Comment by Intigracy** [comment]
sounds like tofu
