### ISSUE TITLE
Beepsky, by default, will arrest the bartender for holding their own shotgun in their own bar

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8363]
It seems rather silly to arrest someone for carrying something they are provided with

I have a feeling that making Beepsky only arrest certain accesses for certain weapons would not be trivial, though

**Comment by Shadowmech88** [comment]
SHALL NOT BE INFRINGED

Shouldn't be too bad to fix, I think. Just find the part where he checks people for weapons and insert an exception for people with bartender access holding double-barrel shotguns.

**Comment by Exxion** [comment]
OK sorry I meant fixing it _properly_ probably wouldn't be trivial
I'm sort of scared to look at Beepsky's code because something tells me it's probably class A oldcode

**Comment by ihadtoregisterforthis** [comment]
Give the bartender a gun permit at start

**Comment by Exxion** [comment]
Great idea no way anything could go wrong

**Comment by ihadtoregisterforthis** [comment]
If they start with a gun, why shouldn't it be legal?

**Comment by Exxion** [comment]
If I'm not mistaken, gun permit lets you open weapon lockboxes

**Comment by Killette2** [comment]
I thought that was armory access.

Also on the stupid side, shield generators need teleporter access.

**Comment by ghost** [comment]
It's armoury access for lockboxes. Anyway, seems like the only way around this is giving the bartender a gun permit

**Comment by Killette2** [comment]
It's really stupid not to give the bartender a gun permit, he has a multipurpose legal shotgun, is him getting a deadlier gun really much of an upgrade?

**Comment by Exxion** [comment]
OK, if gun permit doesn't open lockboxes, then I guess I don't see an issue with giving the bartender a roundstart gun permit
I mean technically the shotgun isn't supposed to be taken out of the bar but it doesn't really matter

**Comment by clusterfack** [comment]
Beepsky doesn't respect castle laws

**Comment by NigglyWiggly** [comment]
# **SHALL NOT BE INFRINGED**

**Comment by Imagebard** [comment]
>Shall not be infringed

Note to all "2nd amendment" people: I am coming for you.

**Comment by NigglyWiggly** [comment]
> Making a threat to people who have already stated that they are armed

# **𝐒𝐇𝐀𝐋𝐋 𝐍𝐎𝐓 𝐁𝐄 𝐈𝐍𝐅𝐑𝐈𝐍𝐆𝐄𝐃**

**Comment by Imagebard** [comment]
Is this a joke? You are under arrest for Possession of a Weapon and Mutiny.

**Comment by NigglyWiggly** [comment]
I plead 

# 𝐍𝐎𝐓 𝐈𝐍𝐅𝐑𝐈𝐍𝐆𝐄𝐃

**Comment by Imagebard** [comment]
I *knew* you'd say that.

Permanent Isolation on the isocubes!
