### ISSUE TITLE
You swallow a gulp of Paper Cup.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8367]
You swallow a gulp of Paper Cup.

**Comment by 9600bauds** [comment]
You also "swallow the contents of" a flour sack.

**Comment by Shadowmech88** [comment]
I really dislike the fact that powders are treated almost exactly the same as liquid reagents are.
You even get the drinking sound when you "drink" flour from the bag.

**Comment by ihadtoregisterforthis** [comment]
And pepper or salt from a shaker.

**Comment by gbasood** [comment]
Give these guys a var that defines their drink text output geez
