### ISSUE TITLE
Disable lighting on roid turf

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#8368]
Since lighting can be laggy, why not disable it on the roid where most miners take mesons to see ore anyways, the only real use light has on the roid is too see whats on the floor ahead of you. Imo I see it as disable lighting and mesons become useless on the roid, or keep it enabled and have extra cpu load

**Comment by AlphaBuffalo** [comment]
This also might be a problem on snow map where I plan on having an entire z-level made of roid turf which is 500x500 lighting simulation

**Comment by 9600bauds** [comment]
I thought it was lighting updates that were laggy, though

**Comment by Shadowmech88** [comment]
> disable lighting on roid turfs
> the only real use light has on the roid is too see whats on the floor ahead of you

So you suggest that miners become unable to see the raw minerals that get dropped to the ground when they mine an ore tile?

**Comment by AlphaBuffalo** [comment]
Make it like space tiles, constant level 10 light

**Comment by AlphaBuffalo** [comment]
Is it lighting updates? I remember pomf set space to be dark and it cause a lot of lag even though no one was in space

**Comment by Exxion** [comment]
You could just say that we're mining on the sun-facing side of the asteroid
As anyone sane would do, assuming you have some radiation shielding

**Comment by ghost** [comment]
This will make any sort of stalking on asteroid impossible as everyone will have nightvision, all mobs will be visible and miners will never need their lanterns again.

What pomf did if I remember correctly was make space to be simulated. Light updates cause lag not light emission, that is static. On another occasion some admin decided to change the color or intensity of space light, which caused millions of tiles to update at once and made the server unplayable.

> ruining literally all maps because of a single literal snowflake

Just make something else suitable for snow map ground. Can't you just make a new turf?

**Comment by clusterfack** [comment]
Lighting isn't laggy.

Nothing is laggy unless you profile it being laggy.

If you don't have profiling access there's literally no reason to say something is laggy.

If you want profiling access (and have the reputation to be responsible with it) ask @d3athrow.

Please stop the superstition.
