### ISSUE TITLE
Ghosts can remove R-UST fuel rods

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8369]
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9c34bda489ae38505db06c716116c562c36a47e4 
> 
> General description of the issue
> As titled.
> 
> What you expected to happen
> Nothing at all.
> 
> What actually happened
> Clicking on the Fuel Assembly Port as a ghost popped out the fuel rod, making the R-UST slow down to a crawl

**Comment by PJB3005** [comment]
THANKS CAEL

**Comment by Gringonius** [comment]
Nearly the end of the year and this still happens.

**Comment by Gringonius** [comment]
I have no idea if anyone ever sorts the issues by "most recently updated", so @PJB3005

**Comment by PJB3005** [comment]
> Nearly the end of the year and this still happens.

You seem to have a fundamental lack of understanding on how a bunch of volunteers decide what to code.

**Comment by Gringonius** [comment]
Just making sure to remind of the existence of a simple bug.
I'm also willing to pay pomfcoins for coding lessons.

**Comment by clusterfack** [comment]
Talk to me on discord or IRC any day
