### ISSUE TITLE
Lacking some xenobotany tools at Deff's science outpost

### ISSUE THREAD

**Issue by viniciuspetch** [d3athrow/vgstation13#8374]
_Even with doubts where and what is the problem, I'm posting this so you higher-beings can simply teleport there and check_

One of the science outposts has a xenobotany room lacking tools, with at least no plant analyzer (last time I had to pray for one), no gene modification machines and maybe even none of those closed-gas hydroponics (for plants with special environment). I'm not really sure if this is the only thing lacking, or if it was really lacking. About the map, I noticed Box shares his outpost with another station, so the one I'm refering to is the one who doesn't share with Box (pretty sure is Deff).

Edit: @Skullyton confirmed it's Deff's

**Comment by Ephx1** [comment]
Title reads xenobiology, not xenobotany

**Comment by viniciuspetch** [comment]
Not anymore. Just me being stupid and wanting to interchange biology with botany.

**Comment by ghost** [comment]
It's Deff. Meta has the same research outpost as box. Fixing this now.
