### ISSUE TITLE
You can perform surgery through hardsuits

### ISSUE THREAD

**Issue by LordMyroc** [d3athrow/vgstation13#8378]
Immulsions ruined.

**Comment by ghost** [comment]
Oh no someone reported it

**Comment by 9600bauds** [comment]
You can do it through any clothing as far as anyone's concerned
This is kind of important to operate on plasmamen

**Comment by Exxion** [comment]
If I'm not mistaken, you're supposed to be able to operate through plasmaman suits, but no others.

**Comment by Ephx1** [comment]
You can operate through any suit but I think aside from organ replacement you have to take it off.
Like when tending to bones or brute damage on organs.

**Comment by nervere** [comment]
No longer an issue. Testing done by @Inorien - thanks!
