### ISSUE TITLE
Thin man style wig and glasses for greys

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#8379]
Something silly that grey IA might like. github doesn't like .dmi files so link to the sprites is here: http://s000.tinyupload.com/?file_id=03792983215600658558

![genuine human](https://cloud.githubusercontent.com/assets/15067109/13187700/a3126776-d744-11e5-9949-0ab7d1847eba.png)

**Comment by Ephx1** [comment]
I THOUGHT THAT OFF PIXEL WAS FIXED

**Comment by PJB3005** [comment]
Nope it never got merged on GitLab.

**Comment by Ephx1** [comment]
FFFFFFFFFFFFFFUCK

**Comment by Kitfox88** [comment]
:+1:

**Comment by Ephx1** [comment]
Oh yeah :+1: I like it. 
It would be amazing if you could get a traitor version that makes you look human to silicons.
