### ISSUE TITLE
Megaman Legends References

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#8380]
WHO DID THIS

> That's a Kattelox Hospital.
> A painting depicting a compact but efficient hospital. The red really helps make the normally drab pallet pop.

![](http://puu.sh/nbeWw/aac488a6ee.png)

ᴬᶫˢᵒ ᵗʰᵉ ᵖʳᵒᵖᵉʳ ˢᵖᵉᶫᶫᶦᶰᵍ ʷᵒᵘᶫᵈ ᵇᵉ 'ᵖᵃᶫᵉᵗᵗᵉ' ᶦᶰ ᵗʰᶦˢ ᶜᵃˢᵉ

**Comment by Exxion** [comment]
> "Its said"
> monstrocity

**Comment by NigglyWiggly** [comment]
Also I only ask who did this because I need to know who my new favorite coder is, in case that wasn't clear

**Comment by clusterfack** [comment]
I like that game too, but it was not me, think it was Dizor?
