### ISSUE TITLE
Make PDA games cheaper, have them available by default, or add space piracy

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8385]
I almost never, ever see PDA games used simply because you need to go to a PDA terminal to get them, and once you get there it's not like they're even cheap. This means two hurdles: One of having to do it every shift you want to play Minesweeper, two because of the cost.
In practice, two hurdles for a completely harmless PDA game means nobody ever goes through them. Which is sad, because PDA games are neat.

**Comment by Imagebard** [comment]
Emagging PDA terminal when

**Comment by PJB3005** [comment]
:-1: 

Let's make sure nobody plays these lag inducing pieces of shit.

**Comment by Ephx1** [comment]
An emagging function that breaks the machine and not do some dumb thing? No way!

**Comment by NigglyWiggly** [comment]
Emagging a PDA should brick it and void the warranty

**Comment by Zth--** [comment]
This is the first time I hear someone complies about the cost of something. We're going places

**Comment by 9600bauds** [comment]
Is there a way to implement the PDA games in Javascript yet?

**Comment by clusterfack** [comment]
Pretty sure there always has been

**Comment by 9600bauds** [comment]
So, in theory that wouldn't cause any lag, would it?

**Comment by clusterfack** [comment]
In javascript? No if it wasn't in javascript it'd all be clientside and not cause any lag.

**Comment by 9600bauds** [comment]
Was Deity given a stern talking to about making the games in Javascript, or

**Comment by PJB3005** [comment]
Yes, but "muh scoreboard security"

**Comment by 9600bauds** [comment]
I wish I had been there to slap him
