### ISSUE TITLE
Advanced Eyes don't work as intended

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8390]
(WEB REPORT BY: lavoss REMOTE: 158.69.55.2:7777)
Issue: Advanced Eyes from the machine, ingame item called Visual Prosthesis, does not give enchanced nightvision (or nightvision at all) or welding goggles effect. Only act as eyes.

Steps to reproduce: get surgery to have the new eyes implemented, the rest should be obvious.

Expected result: ui change or effect added.
Actual result: no ui or effect changes.

**Comment by BarneyGumball** [comment]
"Visual Prosthesis" printed in medbay is just the robotic version of normal eyes.  You can print the advanced eyes with a Protolathe.

**Comment by 9600bauds** [comment]
notabug in big milestone
