### ISSUE TITLE
Plasma men don't  get up after being cyro tubed

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#8391]
heating them up with the thermal homeostasis regulator does nothing to get them out of it so blaming celt meme code on this.

**Comment by DrCelt** [comment]
@AutismSpider Don't blame me, blame @9600bauds

**Comment by AutismSpider** [comment]
some one fuck it so  some one better fix it

**Comment by AutismSpider** [comment]
add on  to this after i got feed coffee to get up i was perm blinded and deaf not even admin verbs could fix me

**Comment by Killette2** [comment]
Cryo isn't needed, use cold and warm showers if you're that big of a scrub.

**Comment by AutismSpider** [comment]
medbay was awful that round no one made pills to fix damage i had as a plasma man so they toss my ass into the cyro

**Comment by Killette2** [comment]
A bad medbay round is a round where you're better off just typing ghost.

**Comment by AutismSpider** [comment]
what should of done when i got toss in the cyro

**Comment by 9600bauds** [comment]
Can't reproduce, working perfectly fine in local testing
Could there have been anything else causing you to be unable to get up?

**Comment by AutismSpider** [comment]
i was in crit when put into cyro got heal up  plasma man suit put back on toss into the  thermal homeostasis regulator and it was 20+ mins of them touching me tossing me back in the fucking thing untill i ahelp about it

**Comment by 9600bauds** [comment]
Did you plasmaman combust at any point?

**Comment by DrCelt** [comment]
Is it possible the no breath thing didn't tick down, @9600bauds?

**Comment by 9600bauds** [comment]
I don't see why he would be blind or deaf, though, that's not an effect of neither hypothermia not oxyloss

**Comment by 9600bauds** [comment]
Was able to reproduce after getting the plasmaman into crit before throwing them into Cryo, something's REALLY fucked up here. The plasmaman stopped processing entirely, they wouldn't metabolize reagents or combust or anything. Seems like the Deus Ex update broke it, here are the relevant runtimes.

>runtime error: undefined variable /datum/gas_mixture/var/plasma
02:11:43 Runtime detected
undefined variable /datum/gas_mixture/var/plasma at lung_gasses.dm:20

@gbasood

**Comment by AutismSpider** [comment]
Some one test this on Vox see if it bugs out.

**Comment by gbasood** [comment]
[8429] will fix that runtime. Not sure if it'll fix this bug or not though

**Comment by gbasood** [comment]
No one has complained after the fix to me so I'll close tenatively
