### ISSUE TITLE
Engiborg Materials Synth Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8392]
(WEB REPORT BY: kitfox88 REMOTE: 158.69.55.2:7777)

> Revision 7a52c8089dace2561f54697a090ecc86b4358b44
> 
> General description of the issue
> Generated some uranium from my material synth, stuffed some of it into the chef's grinder for him and the bartender, then it wouldn't go away. I couldn't store it because I had nothing, I couldn't click it to make floor tiles because it wasn't there, and making more didn't make it appear.
> 
> What you expected to happen
> Be useful
> 
> What actually happened
> MY SLOTS
> 
> Steps to reproduce if possible
> Make mats, stuff them into grinders

**Comment by Kitfox88** [comment]
Getting a module reset from the robotics guy did fix the issue, but that's sorta overkill and it's technically still a bug anyway :whale:

**Comment by AutismSpider** [comment]
its a bug the slots are not updating right

**Comment by Exxion** [comment]
God _damn_ I thought this got fixed _months_ ago

**Comment by Kitfox88** [comment]
I'm glad I keep finding [s]new[/s]old and exciting ways to break borgs for you Exxion

**Comment by Kitfox88** [comment]
On that note, why the heck does the synth make materials new modules under your list instead of just farting the items out under you?

**Comment by Myrios** [comment]
Because since borgs have no hands then that material would be useless just sitting on the ground because they cannot interact with it aside from dragging it around.

**Comment by Exxion** [comment]
It's a shitty way to handle it but nobody's thought of a better one

**Comment by Kitfox88** [comment]
rip

**Comment by gbasood** [comment]
honk still an issue

**Comment by clusterfack** [comment]
I never really got how people fixed these weird bugs with the slots, so don't look at me

**Comment by jknpj** [comment]
Not an issue anymore but you can't feed the grinder without the sheet gripper anymore so i'm fixing that.
