### ISSUE TITLE
Ghost can touch and use telepad control console

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8393]
(WEB REPORT BY: abumblingidiot REMOTE: 158.69.55.2:7777)
Can touch and teleport shit as a ghost

**Comment by PJB3005** [comment]
OH

SHIT

**Comment by AutismSpider** [comment]
more shit ghost can touch but cant do much if any one set up the AAC with the ghost can fuck with it a bit to.

**Comment by uazuaz** [comment]
ghosts can also interact with the confession booth doors in the chapel;
they can open/close the regular confession booth door but they haven't access to the chaplain's confession booth door, therefore they can be annoying just clicking on it to spam the "denied" door sounds.

**Comment by PJB3005** [comment]
@AutismSpider I thought I fixed that ages ago.

**Comment by PJB3005** [comment]
Panic

**Comment by TheFriggenSawbones** [comment]
hi i got it to work and no one else in deadchat could idk if it'll help but I suicided as a posi-brain and could do it.
