### ISSUE TITLE
Shotguns should shot 2-3 bullets per round

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8394]
The big thing about shotguns in real life is that they're supposed to fire multiple projectiles to have a higher chance to hit people.

Lower the damage of just about every projectile(Lethals/Reds deal about 60 damage per shot, lower that to 30-20) and make them fire multiple bullets
Why? Its fun.

**Comment by Myrios** [comment]
How might this affect bleeding/broken bones?
The chance to break/bleed would have to be lowered accordingly otherwise to some antags, wizard springs to mind, the shotgun would be even more terrifyingly godly for the slow death route.

**Comment by Imagebard** [comment]
30 damage is the amount where bone breaking starts becoming likely.
Point blank shots should retain their 60 damage effect, its fun.

**Comment by Shadowmech88** [comment]
This has been addressed, no idea why it didn't autoclose.

**Comment by PsiOmegaDelta** [comment]
Valid auto-close prefixes are: close, closes, closed, fixes, fixed
Source: https://github.com/blog/1386-closing-issues-via-commit-messages

**Comment by Shadowmech88** [comment]
Thanks, noted.

**Comment by Imagebard** [comment]
Oh well, allow me.
