### ISSUE TITLE
Ablative armor not deflecting properly when on a vehicle

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8396]
![stunfuckery](https://cloud.githubusercontent.com/assets/5169310/13196236/9b288b60-d796-11e5-8af2-524354dc41b4.png)

**Comment by Killette2** [comment]
Borg fired taser once, it checks twice or something, read red text. I was in the malpractice traitor wheelchair when I got tased.

**Comment by AutismSpider** [comment]
i think it check twice due to you being on the malpractice it try  you or the malpractice for the stun/laser shot etc (this happens with jai cart and fire bird) if it hits the malpractice it shocks you = a stun.

so it hit the mapractice the vest try to reflected the shock in some way but you got hit by ghost shot

**Comment by 9600bauds** [comment]
> PM to- Admins: BUG

Fairly sure even the Wiki example for an "Absolutely Goddamn Terrible" ahelp is more descriptive than this

**Comment by ihadtoregisterforthis** [comment]
It's more of a "something is broken here and now, take a look, but I'm immersed in RP at the moment".

**Comment by BestName** [comment]
@ihadtoregisterforthis So an admin jumps in just in time to see a borg arrest the guy. What good does that do? There's nothing obviously wrong in the scene. There's no glaring bug in there. The admin isn't going to magically know what's going on.

**Comment by clusterfack** [comment]
It's literally not that, don't be a faggot @ihadtoregisterforthis

**Comment by Shadowmech88** [comment]
Tested locally, taser bolts seem to reflect off a monkeyman in a syndicate wheelchair wearing an ablative vest just fine.
