### ISSUE TITLE
chef's pet

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8397]
Dessert has a random number in his name, like regular mice but unlike other pets.

(side suggstion: what if you call him Remy, like the rat main character in Pixar's movie [Ratatouille](https://en.wikipedia.org/wiki/Ratatouille_%28film%29)?)

**Comment by Imagebard** [comment]
What pet? Do you mean Pete?

**Comment by BestName** [comment]
He's talking about the mouse

**Comment by Imagebard** [comment]
>Chef got another pet

This is heresy

**Comment by CptWad** [comment]
@Nigglywiggly

**Comment by gbasood** [comment]
@Imagebard flavor is harm

**Comment by Imagebard** [comment]
@gbasood Any good chef knows that mixing in the whole kitchen into a recipe probably isn't going to work.

**Comment by NigglyWiggly** [comment]
The numbers in his name are just like with Tom.
I'm not really sure if I could do anything about them (or if anything really needs to be done about them, honestly)
Also I thought of naming him Remy but I thought it'd be too obvious

**Comment by ihadtoregisterforthis** [comment]
References are hardly that direct. If anything, rename it something like Gusteau
