### ISSUE TITLE
Can't fire at a juggernaut construct that is close to you

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8400]
Trying to melee/point blank(I was unable to point blank) a juggernaut causes ineffective attacks, and trying to shoot at the tile past him will cause your attacks to fly over him.
Tried with a Laser Gun(Lethal only gun on the armory).

**Comment by Kitfox88** [comment]
Pistol whipping people point blank instead of shooting them is pretty annoying, yeah

**Comment by Ephx1** [comment]
Doesn't point-blank shooting require the harm intent? Or were you already doing that?

**Comment by Imagebard** [comment]
I had harm intent on, yes.

**Comment by ihadtoregisterforthis** [comment]
Juggernauts are inmune to weak attacks and deflect lasers, so this at least needs more testing.

**Comment by Imagebard** [comment]
>Immune to weak attacks

Yes, they're immune to pistol whipping

>And deflect lasers

They have a CHANCE to deflect lasers. So unless you mean to say that they deflected about 5 lasers, and all of them reflected to the same direction...

**Comment by Imagebard** [comment]
>Feature Request

Oh no wonder this isn't getting fixed
Pardon me.
