### ISSUE TITLE
Greys don't have their own monkey form

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#8403]
Monkifying a grey just makes a regular monkey. Missed opportunity for little green men in my opinion. 

Possible sprites to use for little green men:  http://s000.tinyupload.com/?file_id=20439507724043695414
![heylaughingmyarseoff](https://cloud.githubusercontent.com/assets/15067109/13197842/892a4f42-d7f1-11e5-9b23-5eb6de202852.png)
Now with less rage inducing off green outlines!

I also know Niggly has one that could be used instead.

**Comment by ihadtoregisterforthis** [comment]
Ayy
But don't use black outlines, it triggers people

**Comment by Kitfox88** [comment]
pectoid sprite for hulked greys when

**Comment by Brolaire** [comment]
Sorry for duplicate issue, revive this pls

**Comment by carshalash** [comment]
The absolute madman.
