### ISSUE TITLE
PDA bug?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8404]
(WEB REPORT BY: anunnamedplayer REMOTE: 158.69.55.2:7777)
When using the pda as a scientist, and enabling the gas scanner, if you put the pda on a table, or it gets knocked out of your hand, or put anywhere really other than in some time of storage device, it drops an atmos analyzer with the pda, can repeat endlessly

**Comment by Exxion** [comment]
Oh BOY

Why the fuck does it create a new atmos analyzer every time... something happens? Why not just put one in the cartridge in its `New()` and use that one?

**Comment by Zth--** [comment]
Are them recyclable?

**Comment by Exxion** [comment]
Yep!
I think

**Comment by clusterfack** [comment]
Should be fixed by https://github.com/d3athrow/vgstation13/pull/10662
