### ISSUE TITLE
Deff cryo is fucked.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#8406]
THANKS DUNY.

![](http://i.imgur.com/mcDfEgi.png)

**Comment by Duny-** [comment]
Don't look at me, thank that casual who couldn't wait to make Deff into Box.

**Comment by Kitfox88** [comment]
b a n 
d
u
n
y

**Comment by Duny-** [comment]
As if it wasn't clear enough, that wasn't my doing. The last update wasn't from me.

**Comment by CptWad** [comment]
@Skullyton

**Comment by ghost** [comment]
aaaaah
