### ISSUE TITLE
Plasmamen atmos fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8409]
(WEB REPORT BY: rebuildramiel REMOTE: 158.69.55.2:7777)
Revision 7a52c8089dace2561f54697a090ecc86b4358b44 
Plasmamen seem to be unaffected by their suits and the atmosphere anymore.

I took off my suit and expected to light on fire.

I did not light on fire, and could even breath the normal air mix.

Just take off your suit and tank to reproduce.

**Comment by Exxion** [comment]
@gbasood
