### ISSUE TITLE
Cage bugs

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#8411]
The Cages will some times bug out and turn solid means you cant put mobs in it.

Even if tthe cage is push away form you it open up if you were in the middle of doing it.

Borgs/Mommis can't open cages but they can lock the cover for them.

**Comment by unid15** [comment]
gonna fix this tomorrow

**Comment by 9600bauds** [comment]
How is this feature loss

**Comment by Blithering** [comment]
A wizard animated one in a round today, The person inside stayed on the same tile while the cage went scooting off to bite people. despite being visibly free, the caged person couldn't move. once the (now dead) cage was opened, they teleported to the cage's location.

**Comment by AutismSpider** [comment]
@Blithering  happens with lockers to
