### ISSUE TITLE
Chaplain Runes Researching

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8415]
Replace bashing people with a bible with something more like Nar-Sie cultist interactions.
This is still a idea under the works, if you have any questions with the runes or want different effects just ask or make your own pastebin.

http://pastebin.com/cScAvW9J

**Comment by LordMyroc** [comment]
:-1:

Supernatural things should be limited to antagonists, e.g wizards and cult. Having magic shit available every shift is a stupid thing to have on a sci-fi space station.

**Comment by AutismSpider** [comment]
if you don't want this add chaps anti wizards powers back

**Comment by PJB3005** [comment]
Yeah personally I think this is too 'whacky'. Most of the chaplain's current things are gimmicks about there really being a God. This is too blatant.

**Comment by DrCelt** [comment]
It's not that bad an idea. Eh.

**Comment by SangriaMonkey** [comment]
The role could really use something to make it more dynamic. If not this then something else.

**Comment by Imagebard** [comment]
.>Last time Pomf123 offered to code a feature this got a lot of votes
.>Now people don't like it

Why

**Comment by Shadowmech88** [comment]
How long ago was that?
The playerbase changes as old players stop playing and new players take their place.

**Comment by Imagebard** [comment]
Very, very long ago, I believe.

**Comment by Imagebard** [comment]
Well I'm just going to accept its not majority anymore

RIP Chaplain Runes
http://ss13.moe/index.php/poll/19
You were 2nd best.

**Comment by SangriaMonkey** [comment]
rip
