### ISSUE TITLE
blunderbuss loading

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8416]
(WEB REPORT BY: mrslippy REMOTE: 158.69.55.2:7777)
Loading the blunderbuss with "NanoTrasen brand beach ball" casues you to throw the ball in a random direction while also load the beachball. 
Beachball can still be picked up and used like a normal ball, but when shooting the blunderbust will teliport it to where ever it was shot as normal.

**Comment by Exxion** [comment]
Missing check

**Comment by gbasood** [comment]
@Shadowmech88

**Comment by Shadowmech88** [comment]
It's due to the ball's afterattack() getting called.

How do I make that not happen in this specific case?
