### ISSUE TITLE
Cult bans screw over cultist conversions

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8417]
There's quite a few self requested cult bans and other cult related bans.

Currently these bans prevent conversions and result in otherwise earned converts turning into people screaming over radio soon after they wake up, wasting all effort and resources while a confused cultist wonders why an assistant is 'implanted' 5 minutes in.

It makes no sense to punish or even give advantage to people against cult because someone is antag banned.

**Comment by Shadowmech88** [comment]
This has been talked about before, I'm not sure why nothing has been changed.
The convert rune should really just sacrifice people that are cultbanned.

**Comment by ihadtoregisterforthis** [comment]
#6587 because blowing them up would be too suspicious

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis: Because having them wake up and scream "CULT!" is
way more suspicious.
No sir, I'd rather clean up a messy spill than to get someone who gives out
all our names.

2016-02-21 2:59 GMT+01:00 ihadtoregisterforthis notifications@github.com:

**Comment by Shadowmech88** [comment]
Then just make them disappear instead of gibbing, say they got sucked into the void or something.
Anything would be better than the rune doing nothing at all.

**Comment by ihadtoregisterforthis** [comment]
It says right there the victims go to sleep and the cultist gets notified, and can do something else with the helpless body. Space, sacrifice, behead, whatever they want; it it were plain gibbing it could mean trouble for cultists that don't carry soap around.
Unless something doesn't work as intended and converting banned people does nothing.

**Comment by Exxion** [comment]
I like the idea of making convert runes stun+silence cultbanned people for quite a while.

**Comment by mrpain666** [comment]
Just gib the bastards. They've shown they clearly dont want to or are incapable of playing in cult rounds anyways.

**Comment by Exxion** [comment]
Yeah but then the cultists who tried to convert them get covered in blood and shit

**Comment by LordMyroc** [comment]
Doesn't trying to convert cultbanned people put them to sleep for a long time? I remember that being a change that was pushed through.

Sounds like it either isn't working, or it's not putting people to sleep for long enough.

**Comment by Imagebard** [comment]
That same PR was mentioned in ihadtoregisterforthis post. The 2nd one on this issue.

**Comment by mrpain666** [comment]
@Exxion Good point. Just delete the mob and give the cultist something nice then.

**Comment by Imagebard** [comment]
Suggestion:
Cultists should be able to see who's jobbanned form cult like they can see who's culted. Show maybe a cross or something that isn't the default cultist symbol.

**Comment by Allspice** [comment]
If being a cultist isn't their style then perhaps they would prefer the construct life. Replace their body with a stone containing their soul.

**Comment by Imagebard** [comment]
>Replace their body with a stone containing their soul

They're banned form being cultists. Would it really be safe to let them be cult constructs?

**Comment by mrpain666** [comment]
Pretty sure we've banned some people from cult for being shit with constructs.

**Comment by sonime** [comment]
Really should delete them like what @Shadowmech88 said. I'm also for having the indicator of cultbanned people too.
