### ISSUE TITLE
THANKS NOT NEXIS

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#8418]
Plasmamen don't burn up on oxygen, and don't need plasma to breathe.

![sawbones](https://cloud.githubusercontent.com/assets/13305885/13200713/0e1101e2-d833-11e5-8cd3-45fc72303ea8.png)
Skeletons reincarnated

**Comment by Ephx1** [comment]
#8409

**Comment by ihadtoregisterforthis** [comment]
Ok, but mine had a screenshot
