### ISSUE TITLE
Port /tg/ item stacking in special bags

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8424]
Certain bags like the plantbag or miningbag contain vast amounts of items, on /tg/ identical items stack and show a number next to the item icon.

So having 40 plumphelmets would result in a plumphelmet with number 40 over it.

**Comment by PJB3005** [comment]
Pretty sure we have this just nothing uses it.

EDIT: [yup](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/objects/items/weapons/storage/storage.dm#L24)

**Comment by uazuaz** [comment]
this could be useful for material stacks too

**Comment by ghost** [comment]
That sounds awful for immersion.

**Comment by PJB3005** [comment]
*cough syringes *cough engineering tape.

**Comment by SonixApache** [comment]
:+1:

**Comment by ghost** [comment]
[If I might interject](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/objects/items/weapons/storage/bags.dm#L20), it seems that it's not used by anything because it apparently crashes clients when used?

If that's the case, time to get to testing and seeing what /tg/ does differently if they've got it working without potential crashes.

EDIT - Tested it, and I didn't crash so that's good.

The number could do with being a bit "crisper" though

![Blurry numbers](http://i.imgur.com/mPDt6qs.png)

**Comment by ghost** [comment]
My immersion has been RUINED
RUINED

**Comment by ghost** [comment]
Hold on I could maybe make it so that it becomes like a multiple version of itself that wouldn't be as bad

**Comment by PJB3005** [comment]
@skullyton my guess is that it's from a time period where maptext was less stable.

**Comment by SonixApache** [comment]
oddly enough we have this for coins in the money bag
