### ISSUE TITLE
Feature Request: Spawned Borgs start with Radio MMIs

### ISSUE THREAD

**Issue by Kitfox88** [d3athrow/vgstation13#8427]
Getting blown 10 minutes into the round then having your brain hidden somewhere is really fucking boring. :tada:

**Comment by AutismSpider** [comment]
Add this to pos brains to.

**Comment by LordMyroc** [comment]
At that point you might as well just make all MMIs radio-enabled by default and remove the non-radio-enabled ones entirely.

Which, all things considered, isn't a **terrible** idea I guess.

**Comment by Ephx1** [comment]
I still believe that posibrains should be able to speak on binary, but not hear it.
Only so they can emergency broadcast to any other silicons.
Also MMIs appear on crew monitors now, it's a shame medbay can't even bother to retrieve them.

**Comment by Kitfox88** [comment]
@LordMyroc 
Yeah I considered and support that idea too, to be honest. Being a borg in some remote part of the station and getting blown is just a complete pain in the ass. It's not like dying, because then at least you have deadchat to pass the time, and can observe and whatnot.

**Comment by Imagebard** [comment]
>It's not like dying, because then at least you have deadchat to pass the time, and can observe and whatnot.

If you're already a brain can't you ghost and return to your body when you want to

**Comment by Kitfox88** [comment]
I thought brains in MMIs worked differently, and you had to suicide succumb like normal.

**Comment by Ephx1** [comment]
MMIs do not allow for re-entering if you ghosted as the MMI.
However if you are currently a ghosted brain THEN put in an MMI, you can hop back in.

**Comment by Kitfox88** [comment]
Okay, that's how I thought it worked, which still leaves the current problem.
