### ISSUE TITLE
Plasmamen burning in cryo

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8431]
(WEB REPORT BY: kungfury REMOTE: 158.69.55.2:7777)

> Revision d10df0fc9be90e524df9a21d46764f3a29c1382a
> 
> General description of the issue
> I am burning when I am in the cryo tubes. Even with my suit on.
> 
> What you expected to happen
> To be properly healed and not be on fire.
> 
> What actually happened
> I burned and died faster than I healed.
> 
> Steps to reproduce if possible
> Be a plasmaman. Die. Get cloned. Enter a cryo tube. Watch as the ride never ends and doctors give up on you.

**Comment by MemeFury** [comment]
Disregard the bulk of this, it's an issue with deff's main cryo tubes.

**Comment by ihadtoregisterforthis** [comment]
Thanks not Duny.

Merged as I was typing
#8407

**Comment by gbasood** [comment]
Seems like it's fixed, if not I'll re-open.
