### ISSUE TITLE
Unable to toggle Plasmaman's Tank on with hud internal button thingy

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8433]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f457088e60be0cc9d3bc088f87d773c482dc3b3e 
> 
> General description of the issue
> Whenever I click on the Internal Button to toggle my tank on or off, it tels me You don't have a toxins tank.
> 
> What you expected to happen
> My tank to open/close when i press the button
> 
> What actually happened
> It only closes, it doesn't open the tank.
> 
> Steps to reproduce if possible
> be plasmaman

mash the internal button

**Comment by MemeFury** [comment]
this got me killed today, definitely an issue

**Comment by 9600bauds** [comment]
No longer happens ever since stripcode refactor where I retouched internals toggling
