### ISSUE TITLE
Spiders can move cages and attack through them if the cover is open

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8434]
Also,

> [22:10:44] HELP: Lavoss/(Layla Rogers) (?) (PP) (VV) (SM) (JMP) (CA) : HE COOCOONED THE CAGE FROM WITHIN 
> [22:10:50] HELP: Lavoss/(Layla Rogers) (?) (PP) (VV) (SM) (JMP) (CA) : COCOONING HIMSELF 
> [22:10:53] HELP: Lavoss/(Layla Rogers) (?) (PP) (VV) (SM) (JMP) (CA) : AAAAAAAAAAAAAAAAAA

**Comment by unid15** [comment]
Attacking from a cage is a feature

Will fix cocooning when I'm home

**Comment by Imagebard** [comment]
You can do anything but move around if the cover is open. Its intentional.

**Comment by gbasood** [comment]
Except for the part where spiders inside a cage can move the cage, sure.

**Comment by Imagebard** [comment]
Edit the title so it mentions the bugs instead of things working as intended, then.
