### ISSUE TITLE
simple_animal Mobs Can Fly Through Space

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8438]
Specifically I noticed this with Russians. One was chasing me through space, and was able to course-correct his path when I changed directions, despite him not having a jetpack.
I remember spiders being able to do this as well.

**Comment by Exxion** [comment]
Spiders can sort of do it in that they both drift through space in the direction they were moving AND move toward their targets, at roughly the same rate, so they just sort of... curve towards their targets
It's really pretty wacky
It makes it much harder to throw the ones on the salvage shuttle into space

**Comment by Kitfox88** [comment]
You could argue spiders are shooting web or something akin to how you can throw your shoes but lol @ russians

**Comment by ghost** [comment]
How else did you think the soviets got the Soyuz into space?

**Comment by ghost** [comment]
Simple mobs need a bit of a rework in general when it comes to space travel.

For instance, simple mobs not controlled by a ckey won't randomslip, whereas simple mobs that are controlled by a ckey will randomslip

**Comment by MadmanMartian** [comment]
This looks fixed from what I can tell
