### ISSUE TITLE
Give Xenos a Clearer HUD Icon for Health

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8443]
Currently it is somewhat difficult to tell just how much health you have left.

**Comment by CptWad** [comment]
That and the heat/plasma warnings are not quite as flashy as the human one so players who are new to it wont know that the slightly glowing orange orb means shits on fire yo

**Comment by Imagebard** [comment]
Doubly so when the new player goes into a vent without knowing what the glowing orange orb means death.

**Comment by Kitfox88** [comment]
Honestly the entire xeno ui is kinda cluttery. I mean it's neat looking but :ok:

**Comment by gbasood** [comment]
Xeno UI a shit, I just complained about their heat indicator in #8442
