### ISSUE TITLE
Cuffed with one hand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8444]
(WEB REPORT BY: oatzandhoes REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Got cuffed while I was missing a hand that wasn't properly removed
> 
> What you expected to happen
> The cuffs to fall off
> 
> What actually happened
> The cuffs acted as they would if you got cuffed with two hands.
> 
> Steps to reproduce if possible
> Amputate your hand to just before the point of using the scalpal to remove flesh. Then get cuffed.

**Comment by Exxion** [comment]
Beepsky can cuff you while you are completely missing an entire arm, even if it is properly amputated, I believe

Well, I've seen it happen, but that time may have been weird

**Comment by CptWad** [comment]
The greatest question of all mankind, how do you cuff a one armed person?

**Comment by Ephx1** [comment]
To his legs.

**Comment by ihadtoregisterforthis** [comment]
To a belt

**Comment by clusterfack** [comment]
To his arm duh

**Comment by Exxion** [comment]
> Not cuffing the wrist to just above the elbow on the same arm

**Comment by Ephx1** [comment]
That's not as entertaining.

**Comment by Exxion** [comment]
For the record, the person I saw Beepsky cuff with only one arm also had no legs

**Comment by Ephx1** [comment]
Cripples are no fun

**Comment by Imagebard** [comment]
>IT'S A FEATUREEEEE and Oversight tags have the same color

This might as well be intentional.

**Comment by ghost** [comment]
This isn't an oversight. I remember distinctly about two years ago that people'd intentionally play one handed characters so they wouldn't get cuffed.

**Comment by Killette2** [comment]
Nice trips

**Comment by robintime** [comment]
beepsky can STILL cuff amputees, but the rest of the things surrounding one-handed cuffing was fixed. beepsky being able to do this is probably due to mobcode, which is a completely separate issue
