### ISSUE TITLE
End round display doesn't indicate who 'won' in most gamemodes

### ISSUE THREAD

**Issue by SonixApache** [d3athrow/vgstation13#8448]
So far I've noticed it for nuke ops, heist, and others. 
It tells you who the antags were, and what they bought, but not if they accomplished their task or not.

**Comment by CptWad** [comment]
this issue exists already
its somewhere lemme find it

**Comment by CptWad** [comment]
#7928

**Comment by SonixApache** [comment]
Oh, whoops.
