### ISSUE TITLE
Non-oxygen breathing races take as much oxygen damage as if they were in space (due to Deus Ex)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8449]
``` DM
H.adjustOxyLoss(HUMAN_MAX_OXYLOSS)
```

Which is 1.
I have no idea what this should be re-adjusted to, or if instead we should just change pressure damage to be higher so that space still acts the same

**Comment by ghost** [comment]
Pressure damage needs to be far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far far higher

There's no excuse; any old suit you can get are really effective at pressure resistance, and there are ghetto space suits.

**Comment by ghost** [comment]
> people will pop from pressure sooner than burn during a fire

What could go wrong.

**Comment by ghost** [comment]
@TermedClepe Sounds realistic to be honest

**Comment by gbasood** [comment]
It does actually take a much longer time to die to fire than you'd think

**Comment by ghost** [comment]
Deaths in fires are mostly due to inhaling toxic gases first and foremost, then people passing out due to violent hyperthermia

But our fire system is shit, and anything linked to ZAS and Atmos is behind ten safety barriers, so fucking wew

**Comment by ghost** [comment]
Hyperthermia WHEN

**Comment by FudgePucker** [comment]
Pressure overhaul when?
If you went from a 1000 kpa room to a 101 kpa room you should take massive amounts of damage. Divers have to come up slowly to prevent damage from changing pressure.

Its not like I want to murder everyone while relaxing in my atmos hardsuit :^)

**Comment by ghost** [comment]
I was thinking of doing that @fudgepacker but we're waiting on the 510 PR to go through first.

**Comment by gbasood** [comment]
@DrCelt Go ahead and do it, at this point.

**Comment by ghost** [comment]
Celt never went ahead and done it
