### ISSUE TITLE
Reduce w_class of Blunderbuss and Railgun

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8455]
[Discussion]

Initially I was thinking of them as shotgun-sized weapons, but from a balance perspective, I think it makes it a bit of a challenge to arm oneself with these when they can't fit in backpacks, considering they're still usually much less effective than a conventional egun.

**Comment by ghost** [comment]
Considering I've seen complaints that they're too common, they don't need buffed right now. Perhaps when they stop being so new this would be more wise

**Comment by Shadowmech88** [comment]
They may be common, but have they really been a large threat to anyone yet?

**Comment by AutismSpider** [comment]
Takes to long get a Railgun going on of it being to much work. Blunderbuss is the RNG gun over load it with fuel for max  damage and pray it does not blow up on you like IED

**Comment by ghost** [comment]
I highly doubt any real weapon should fit in a backpack, makes it too easy to have armory backpacks

The shotgun w_class is perfect here. Belt, back or exosuit slot. Not in an utility backpack

**Comment by Shadowmech88** [comment]
They can't fit on belts either, though.
Maybe that's the change that should be made.

**Comment by ghost** [comment]
Add in belt slot then

It roughly makes sense someone might try to attach it to their belt. It's not something like the rocket launcher or the Hecate which can really only go on your back

**Comment by Shadowmech88** [comment]
I added the ability for both of these to go in the belt slot quite some time ago.
