### ISSUE TITLE
Missing mini-meteor sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8456]
(WEB REPORT BY: sordine REMOTE: 158.69.55.2:7777)
Mini-Meteor that you get from the arcade is missing the sprite. Or maybe it's just REALLY small

**Comment by Exxion** [comment]
This started happening a few weeks ago
Putting the spriteless mini-meteor into a storage item renders a storage slot useless because you can never remove it

**Comment by CptWad** [comment]
It happened after @dylanstrategie 's new meteors

**Comment by ghost** [comment]
I changed all the sprite names, so it likely wasn't updated

I'll take a look at it soon

**Comment by Intigracy** [comment]
Was fixed.
