### ISSUE TITLE
Invisible "Shrapnel" coming from Crossbows

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#8457]
One round on Deff as raiders, I found myself stepping on Glass shards for no reason on the ship.
Alt+clicking showed an invisible item labelled "Shrapnel". If it isn't a roundstart thing, I have no clue where the hell it came from. It was in the cockpit of the ship, under one of the chairs I believe.

**Comment by Exxion** [comment]
It comes from the crossbows. If you try to unload one after charging the loaded rod, it just shatters the rod.

**Comment by Ephx1** [comment]
Then that's absolutely idiotic. It's a glass shard that's labelled shrapnel and is invisible.

**Comment by Exxion** [comment]
It's not supposed to be invisible. The sprite is just missing.
I think.

**Comment by LordMyroc** [comment]
The same also applies to bullet shrapnel removed during surgery, I believe.

**Comment by Kitfox88** [comment]
does it just not have a sprite because holy shit i'll make one if it finally removes this shit from the tracker

**Comment by Ephx1** [comment]
I vaguely remember there being a sprite, but that was long ago when the "Pull item out" verb was still a thing. It was just a black arrangement of things.

**Comment by Imagebard** [comment]
>⚠️ OH GOD IT'S LOOSE ⚠️

But why?

**Comment by gbasood** [comment]
Invisible harm

**Comment by Exxion** [comment]
Oh holy shit it probably has w_class 1 and throwforce 15 just like glass shards
Which means magical invisible one-hit kills with the pneumatic cannon

**Comment by ghost** [comment]
Oh no

**Comment by Kitfox88** [comment]
lol u fukken idjits

**Comment by Imagebard** [comment]
What's this, my brother became a Cultist and is going to die form a shrapnel enema at Space?

**Comment by ghost** [comment]
Okay, what did shrapnel look like?

I'm imagining something simple like a small black shard, multiple directions and locations could vary it up a bit too

**Comment by Ephx1** [comment]
Like I said

> It was just a black arrangement of things.

A vague arrangement of jagged things, colored black. Or at least I'm fairly certain that's what it was.
