### ISSUE TITLE
Oxygen Icon did not appear

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8458]
(WEB REPORT BY: lorkhatosh REMOTE: 158.69.55.2:7777)
Oxygen Icon did not appear when I was suffocating multiple times.

**Comment by gbasood** [comment]
Okay, some missing info here:
- What human-type race/non-human mob were you?
- What kind of atmosphere were you in when you were suffocating?

**Comment by Ephx1** [comment]
Had this occur a few times as human.
Once in a complete vacuum, the other in a depressurizing room with 60 kPa.

**Comment by gbasood** [comment]
Looks like I found it
