### ISSUE TITLE
Cannot dig up sand

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8459]
(WEB REPORT BY: cptwad REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

36ff1dd6450ecfde8363212f471e0982cbe59db4 

> General description of the issue

Shovels (and drills) dont dig up sand

> What you expected to happen

Them to dig up sand

> What actually happened

Nothing

> Steps to reproduce if possible

Use shovel/drill on sand
Wow nothing

**Comment by Exxion** [comment]
This broke sometime yesterday.
