### ISSUE TITLE
Parapen disappearing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8460]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> ce5a82256bbcd88f97bf112624142b6f9e608981
> 
> General description of the issue
> Parapen put into left pocket, disappeared from the HUD, later on during search, HoS pulled it OUT OF MY EYES-slot.
> 
> What you expected to happen
> Put parapen into right pocket, it goes in there.
> 
> What actually happened
> Parapen turns invisible and was apparently equipped to my glasses slot instead of pockets.
> 
> Steps to reproduce if possible
> -Get parapen
> -Put normal pen into LEFT pocket
> -PDA in LEFT hand, parapen in RIGHT hand
> -Active hand: RIGHT
> -Press E twice in hotkey-mode
> -Click with active RIGHT hand on RIGHT pocket.

**Comment by Zth--** [comment]
Yeah actually you can put a pen in your eyes slot instead of your EAR slot, which is stupid

**Comment by ghost** [comment]
Pffhaha

**Comment by Kitfox88** [comment]
That's some god damned slight of hand right there.

Doing it with coins when

**Comment by 9600bauds** [comment]
Oh yeah I fixed this
