### ISSUE TITLE
Clicking wires

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#8461]
If you click wires with your bare hands, nothing happens. But if you do it while holding any item, you get shocked. It's stupid and annoying

**Comment by Ephx1** [comment]
I agree, the only effect that should occur from wires is connecting them or trying to cut them without gloves.

**Comment by clusterfack** [comment]
It happens if you hit it with a conducting object

**Comment by 9600bauds** [comment]
Which tends to be all items pretty much
Like the floortile you were trying to put back on
Are all these cables stripped or what

**Comment by PJB3005** [comment]
@9600bauds you hit it with a weapon so you actually go through the extremely _shitty NT :tm: budget :tm: power cable :tm: insulation :tm:._

**Comment by Zth--** [comment]
Once I was chasing a ling in maintenance and guess what, I clicked the cable coil with the taser. This feature is stupid, remove it

**Comment by clusterfack** [comment]
This saved me from a changeling once, please do not remove.
