### ISSUE TITLE
Allow mid-round bussed malf to go delta

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8462]
Because as far as I know, the only malf that will show up mid-round is a bussed malf.

I think there was reason this was prevented a LONG time ago but I can't remember it.

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
Malfunction is surprisingly broken, you can notably not even fucking test it because the sanity is autistic and will forbid you from running it unless you have everything you need

**Comment by gbasood** [comment]
re-opening because WHY NOT

**Comment by ghost** [comment]
Malfunction is still one of the most autistic gamemodes on the server

If you don't run it as a roundstart gamemode, with an AI that has malf enabled (having an AI with malf disabled causes the infamous return to lobby error), it shits itself everywhere and cries

Rework is the only way I see out of this mess

**Comment by gbasood** [comment]
It's funny because most of the shit that breaks is literally just because it typechecks the mode itself to prevent malf things on non-malf

**Comment by gbasood** [comment]
ANTAG
DATUMS
