### ISSUE TITLE
AIs (and possibly roles such as clown and mime) can give themselves names that are entirely spaces

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8463]
Makes dealing with ahelps a pain in the ass

**Comment by Exxion** [comment]
Please oh please tell me they can take names with Unicode control characters

**Comment by ghost** [comment]
This needs to be fixed asap as it is abusable.

**Comment by SysadminJeroen** [comment]
‮This could be fun.

**Comment by Exxion** [comment]
Unfortunately, I don't think BYOND knows how to render Unicode control characters
I tried pasting one (U+202e, of course) into chat but it just came up as a question mark, even in the text entry box

**Comment by ihadtoregisterforthis** [comment]
I tried to (° ͜>°) on OOC before with no success, it comes as °?>°

**Comment by Kitfox88** [comment]
change this to feature request: unicode in names tia

**Comment by Exxion** [comment]
BYOND chat is even better

![image](https://cloud.githubusercontent.com/assets/9827785/13270307/374502be-da5b-11e5-9ed7-f2084bdee20f.png)

**Comment by ghost** [comment]
I don't think there's anything we can actually do to forbid whitespace fields, a space is a character after all

Maybe directly ask Lummox, OR use a sanitization proc

**Comment by Exxion** [comment]
BYOND supports regex now, doesn't it?
`\w+`

**Comment by Shadowmech88** [comment]
Tested locally. As a cyborg, setting your name to all spaces gives you a default name. Trying to do so as a clown or mime tells you that the name is inappropriate and makes you choose again, and gives you a default name if you try it three times.
I didn't try AI, but I suspect it is the same as the cyborg.
