### ISSUE TITLE
Hulk wizard LITERALLY invincible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8464]
(WEB REPORT BY: sordine REMOTE: 158.69.55.2:7777)
I was a wizard and took hulk twice and it made me unable to die.

**Comment by gbasood** [comment]
He was a bussed wizard as well (not through antag madness), so I might have fucked up bussing him and somehow he couldn't die because of me

**Comment by AutismSpider** [comment]
@gbasood did you spawn him as test dummy? they have god mode only way to kill a test dummy is to behead them.

Normal hulk spell/mut power lets you keep fighting even when in crit.

**Comment by ghost** [comment]
I just tested hulk. Being hulked makes you be completely fine until you die. That means you can function normally in crit.

**Comment by gbasood** [comment]
@AutismSpider No I didn't spawn him as a dummy. I rejuvenated him from a corpse.
It sounds like he might have been hulked out so long he just never died

**Comment by 9600bauds** [comment]
Couldn't reproduce, may have been caused by old buggy mindswap / adminbus, reopen this if we ever hear from it again
