### ISSUE TITLE
camera issue

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8465]
if you put a camera on a table it takes a photo.

**Comment by ghost** [comment]
It likely uses preattack. It's not different from other items with strange behavior like barricade kits bashing windows (worked hard to try and fix it, but shit man)

**Comment by ihadtoregisterforthis** [comment]
Also like security tape opening doors, or the unfixable placing wrenches on a table

**Comment by Killette2** [comment]
It's physically impossible to place a wrench on the table due to your inner engineer wanting to deconstruct it. The only way to fight those urges is to reinforce the table, or throw the wrench so nobody gets harmed.

**Comment by uazuaz** [comment]
about the wrench on the table: could it be possible to modify it to use it with "harm" intent to disassemble the table and using other intents to put it on the table? something like it happens when disassembling wood barricades with a crowbar (disassemble happens only when in harm intent, otherwise you will just smash the barricade).

**Comment by 9600bauds** [comment]
is fix
