### ISSUE TITLE
Brown Star Recipe Broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8468]
(WEB REPORT BY: kinggrimlock REMOTE: 158.69.55.2:7777)

> Revision ce5a82256bbcd88f97bf112624142b6f9e608981
> 
> General description of the issue
> Can't make Brown Stars, which you SHOULD be able to make via 1 unit of kahlua (Coffee Liqueor) and 4 units of Irish Cream.
> 
> What you expected to happen
> I expected the Irish Cream and Kahlua to mix and make a Brown Star.
> 
> What actually happened
> They did not. See: http://i.imgur.com/O4w7k7b.png
> 
> Steps to reproduce if possible
> Mix 40 units of Irish Cream and 10 units of Kahlua in a beaker of your choice.

**Comment by Exxion** [comment]
I noticed this the one time someone ordered one from me
The bizarre part is that it appears that the recipe is in the code, but simply doesn't actually mix

**Comment by Intigracy** [comment]
someone assign me

**Comment by 9600bauds** [comment]
i cannot
