### ISSUE TITLE
Can't Make Mead

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8469]
(WEB REPORT BY: kinggrimlock REMOTE: 158.69.55.2:7777)

> Revision ce5a82256bbcd88f97bf112624142b6f9e608981
> 
> General description of the issue
> Can't make mead (5 universal enzymes, 1 water, 1 sugar)
> 
> What you expected to happen
> That I would get mead.
> 
> What actually happened
> I got 50 universal enzymes, 10 water, 10 sprinkles.
> 
> Steps to reproduce if possible
> 1. Fill a shaker with 50 universal enzymes.
> 2. Fill a glass with 10 sugar, 10 water.
> 3. Change the glass's transfer rate to 25 units, so as to transfer all of the sugar and water at once.
> 4. Watch as the sugar turns into sprinkles.

**Comment by Killette2** [comment]
Sugar and enzymes turn into sprinkles? I never knew this.

**Comment by ihadtoregisterforthis** [comment]
Thanks grinder refactor

**Comment by 9600bauds** [comment]
The grinder refactor didn't even get merged yet

**Comment by robintime** [comment]
fixed by #14710
