### ISSUE TITLE
Exotic seeds randomized upon being put into the MegaSeed Servitor.

### ISSUE THREAD

**Issue by AI-Is-Rogue** [d3athrow/vgstation13#8475]
> Revision b0c687080e2c0ea657aa8519147a33c3577ab203
> 
> General description of the issue
> When an exotic seed packet is placed into the Servitor, and then taken out, the seeds are randomized
> 
> What you expected to happen
> For the seeds to not be randomized
> 
> What actually happened
> The seeds were randomized
> 
> Steps to reproduce if possible
> Get exotic seeds, put seeds into Servitor, take seeds out, scan for differences.

**Comment by 9600bauds** [comment]
Deity what the fuck

**Comment by 9600bauds** [comment]
Related to #6551

**Comment by ghost** [comment]
Vending machines are silly.

**Comment by PJB3005** [comment]
Yeah the megaseed is horribly broken. 

Seed management in the seed extractor is better anyways.

**Comment by Exxion** [comment]
But the Megaseed is a smartfridge, not a vending machine, unless I'm mistaken
Which is quite worrying

**Comment by Imagebard** [comment]
Why the fuck isn't the Megaseed a vending machine?

**Comment by Exxion** [comment]
You can't put things back in vending machines

**Comment by Imagebard** [comment]
You can already put seeds in the seed extractors, making that useless.

**Comment by PJB3005** [comment]
@Exxion it's a vending machine, just has snowflake code IIRC.

**Comment by Exxion** [comment]
Either it's a smartfridge or a smartfridge version exists in the code but is unused
I remember seeing a smartfridge version in the code when I was looking at smartfridges
