### ISSUE TITLE
Derelict mommi's no longer have ion laws

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#8477]
Spawn as a mommi on the derelict
Check your laws
You dont have to stay on the derelict anymore, and we're already seeing mommis mass driver themselves to the main station via the derelict chapel

**Comment by ghost** [comment]
They do still, it just adds the law after they get the announcement, I believe, unless a new bug has appeared.

**Comment by mrpain666** [comment]
Nope. We checked. Its broke.

**Comment by ghost** [comment]
RIP

**Comment by clusterfack** [comment]
Literally just checked this, it's not broke.

**Comment by AutismSpider** [comment]
@clusterfack  Check some more

**Comment by clusterfack** [comment]
Okay, I checked some more, and fucking wow. It worked. Again. 

Faggot.

**Comment by mrpain666** [comment]
Well I just checked too and it is indeed working again.

I swear up and down there was a round where it wasnt working last night.

Oh well. Im closing this for now.
