### ISSUE TITLE
Infinte Boomerang Spin

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8478]
(WEB REPORT BY: contentinformsreality REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 6c0b9d0d52fcf444885e0dc6cd6a0f6ec6bceefa
> 
> General description of the issue
> Boomerangs don't stop spinning
> 
> What you expected to happen
> Boomerangs to stop spinning
> 
> What actually happened
> It spins forever in my inventory and if I leave it on the ground
> 
> Steps to reproduce if possible
> Throw boomerang.
> Catch or pick up boomerang.
> Watch it do retarded half-spins forever.

**Comment by ghost** [comment]
Attach a power generator to it for infinite power.
