### ISSUE TITLE
Bucket bug abuse prepare for space lube

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8480]
I reported this to pomf himself over a fucking year ago and still no fix, time to report it.
1. Get a PAINT bucket from art supplies crate/slimes
2. Empty it, it empties at 5 unit intervals instead of ever splashing the whole bucket
3. You now realize the paint bucket has range of whatever's in your vision. Splash it 5 tiles away, use x-ray vision to splash through walls. Didn't droppers have a similar issue at one point?
4. Fill it with whatever, water, space lube, thermite. Pick your bug abuse poison
5. PANIC IT'S LOOSE
6. Enjoy assholes reading about this bug, and having people x-ray lube maint until it's fixed
7. Back to point 2, it will only use 5 units of lube/thermite/whatever's in the bucket. It's pretty much a spray bottle in mortar form

**Comment by CptWad** [comment]
holy fug

**Comment by FudgePucker** [comment]
Oh jeez. The condiment bottle had the same issue, only it was a no attack message infinite range hypospray.
I almost got the virologist lynched giving people 1u of chloral.

**Comment by AutismSpider** [comment]
@Killette2 old buggy Droppers and Condiment bottle did the same shit and would go past all eye gear mask hard suit helms

**Comment by Killette2** [comment]
If I remember correctly, once I got cyborg dropper chloraled as a wizard WHILE HAVING THE GEM HARDSUIT ON. Not sure if this was ever addressed.

**Comment by AutismSpider** [comment]
@Killette2 that was fix with the borg droper and normal one i bet you can toss shit in people face with the paint bucket past goggles gas mask and hard suit helm.

**Comment by Killette2** [comment]
FIX WHEN

**Comment by Boxe** [comment]
its a feature

**Comment by clusterfack** [comment]
Wouldn't want to nerf the bucket lube meta
