### ISSUE TITLE
Blunderbuss fires boomerangs exactly one tile

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8483]
The pneumatic cannon works, though
The boomerang even loops around, just at incredible speed

**Comment by AutismSpider** [comment]
Pneumatic fires stuff at max throw force.

Not sure about the blunderbuss

**Comment by FudgePucker** [comment]
What damage does it do? Might be a feature.
Although I think that a boomerang would not loop back when fired from pressure, you have to throw it a specific way to get it to loop back.

**Comment by Shadowmech88** [comment]
Could not reproduce. The boomerang made a full arc when I fired it from a blunderbuss.

**Comment by 9600bauds** [comment]
>Could not reproduce
