### ISSUE TITLE
Snow map base discussion 

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#8485]
Because this is a celt thing anyways, I decided to host a straw poll to see which map type people would want for snow map. Semi functional base won next to no base at all. How semi functional should the base be? My current snow map has it where a shuttle crashed into an abandoned base and the crew would work with what they have to make a safe environment. Should I change it so the mission is to reclaim the base and explore? What should be in the base, what should be on the shuttle? If anyone has any more ideas please share.

Here are the results of the straw poll
![39d99b64304108182099e76e760d9e7c](https://cloud.githubusercontent.com/assets/5650556/13301773/9624e5d8-db14-11e5-834c-1c5bae3ba759.png)

**Comment by clusterfack** [comment]
Why did you make a new issue for this

**Comment by AlphaBuffalo** [comment]
Because the other one is too cluttered and it covers the whole topic where I just want to discuss this

**Comment by CptWad** [comment]
well my two cents will be to be a bit of a better derelict set up
Power, atmos, RnD, an autolathe, chem dispenser and minerals you can mine/find
Though having a general area with some stuff to keep the greyshirts busy while they wait for their own space suits would be good too

**Comment by ihadtoregisterforthis** [comment]
This prebuilt start will surely allow more antag possibilities, and regular play. But the original idea of fun in other ways and has extra spice.

This could stay as the standard map and Celt's as a hardcore variant, if such variation can be handled in byond

**Comment by ghost** [comment]
Yeah, derelict base style is probably best if we don't have MAN MODE

**Comment by ghost** [comment]
Could take some ideas from away missions. One thing I've noticed on "abandoned base" style missions is that they have a bare-bones engineering room, usually with a single SMES and some sort of PACMAN, but with room to expand if needs be. 

Having players have to set up a cooling room for servers could prove interesting, considering on most maps they're built never to fail. 

Atmospherics wouldn't be entirely necessary if we're considering the atmosphere of the planet to be not too dissimilar from the regular mix, but some sort of room that would be built to intake air from the outside, heat it up, and then pump that into the station would make sense considering how cold it is going to be (and it would make a good target for if somebody wanted to ruin the entire outpost)

R&D itself could either be bare bones (Protolathe, destructive analyzer, circuit printer) extensive yet protected (multiple reinforced walls and unpowered bolted doors between regular access and the machines, akin to box) or just not built (Have the machine boards on the crashed shuttle).

As for chemistry, we could make use of ghettochem (There would need to be some real version of a centrifuge, perhaps hand-cranked) but there would need to be some better way of obtaining sulphuric acid outside of breaking down polyacid from dan drinks for early game, in case somebody dooms us all by pouring out the paltry amount. Simply having a chemistry machine already accessible would make the map a whole lot easier, so possibly have it in some form of guarded technical storage along with R&D machines/boards inside the base?

**Comment by Imagebard** [comment]
>Unbuilt R&D machines roundstart
Ghettochem

What will the crashed shuttle look like, anyways?

**Comment by AlphaBuffalo** [comment]
Someone is supposed to add sprites for that actually @imagebard

**Comment by PJB3005** [comment]
![](https://camo.githubusercontent.com/57617f493c3e6b835079e0a0ec5a80c9fa3422f7/687474703a2f2f692e696d6775722e636f6d2f4a4a565a6975332e706e676c)
