### ISSUE TITLE
Can't clean up cockroach gibs with mop

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8486]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision

a4029c0be7c16109864af35b6bc7056b80556276

I used water.

**Comment by ihadtoregisterforthis** [comment]
At least have the decency of deleting the empty fields

**Comment by SysadminJeroen** [comment]
@ihadtoregisterforthis In my defense, there was already a clown coming towards me.

**Comment by Ephx1** [comment]
I ruined a bug report, that's a first.

**Comment by 9600bauds** [comment]
it works it's just a little hard telling what tile the cockroach gibs belong to
