### ISSUE TITLE
Clown ID blank at roundstart

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8488]
(WEB REPORT BY: oatzandhoes REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Tried to choose my clown name and the ID and PDA were blank with no name, but my clown name was still chosen for my character
> 
> What you expected to happen
> For the ID and PDA to have my chosen clown name
> 
> What actually happened
> ID and PDA were blank with no name
> 
> Steps to reproduce if possible
> Try to choose a clownname at roundstart and see if it happens.

**Comment by Shadowmech88** [comment]
This happens if you wait too long to choose your clown name.
