### ISSUE TITLE
Welding firelocks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8491]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: f7fb8a3fa157d03616c37d39c1cc00b832e12b7a 
> 
> General description of the issue
> Welding a firelock does not notify, play a sound upon welding/unwelding or trying to open it. (Maybe just as a MoMMi
> 
> What you expected to happen
> "Autism crab welds the firelock shut!"
> 
> What actually happened
> Nothing. Could still try to open it as well.
> 
> Steps to reproduce if possible
> Weld firelock, try to open?

**Comment by AutismSpider** [comment]
Do the welded fire locks have icons now the old ones did+sound not sure about the new ones we have

**Comment by Brolaire** [comment]
Yeah they have slightly altered icons
