### ISSUE TITLE
Hivehand infinite ammo bug

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8492]
Get hivehand, switch to empty hand, click on hivehand. Repeat a dozen times.

Marvel as your hivehand now has infinite ammo.

**Comment by Shadowmech88** [comment]
First of all, the hivehand is capable of regenerating its own ammo.
Second, are you switching the hand that's wearing it?

**Comment by ihadtoregisterforthis** [comment]
It is made for infinite ammo, unless this is about fast reloading

**Comment by AutismSpider** [comment]
could be ghost reload in some way

**Comment by ghost** [comment]
> not a bug

It normally takes time to reload itself. When you do this it shoots forever. You know what fuck it I'll just abuse it since it's clearly not a bug.

**Comment by Shadowmech88** [comment]
It was labeled [Not A Bug] because you didn't initially provide enough information for us to know what exactly you were talking about.
Don't throw tantrums here. It's unbecoming.

**Comment by 9600bauds** [comment]
This is a bug tho
