### ISSUE TITLE
Chain Lightning is broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8496]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
Lightning level 1 works fine.  Lightning level 2/3 do not work.

**Comment by DamianX** [comment]
@DrCelt you fixed this?

**Comment by ghost** [comment]
@DamianX I assume so. I fixed the fact it didn't do damage, but not sure if this is the same bug.

**Comment by Probe1** [comment]
I can't remember this bug.

**Comment by Exxion** [comment]
What is this bug? We just don't know
