### ISSUE TITLE
Raincoat makes you naked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8497]
(WEB REPORT BY: shiggypiggy REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f7fb8a3fa157d03616c37d39c1cc00b832e12b7a 
> General description of the issue
> While wearing the raincoat, you look naked under it
> 
> What you expected to happen
> Not be naked
> 
> What actually happened
> I was naked
> 
> Steps to reproduce if possible
> Get a raincoat and put it on, enjoy exhibitionism

**Comment by Exxion** [comment]
This applies to a large number of exosuit slot clothes that it shouldn't
Most amusingly, the fairy wings

@DrCelt

**Comment by ghost** [comment]
Grand, thanks.
