### ISSUE TITLE
Pill icons are fucked up

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8503]
![2016-02-25_19-03-52](https://cloud.githubusercontent.com/assets/6526157/13336627/c0930ed0-dbf5-11e5-9f1c-bf2720fdc42f.png)

**Comment by gbasood** [comment]
I noticed this earlier too, what the hell

**Comment by Shadowmech88** [comment]
It looks like the sprites are aligned to the buttons, but being that the sprites look 32x32 and the buttons look 16x32, it seems the pills themselves aren't centered on the buttons.

**Comment by clusterfack** [comment]
It seems bauds fixed this with that one PR
