### ISSUE TITLE
Abandoned Crate can spawn WRENCHED DOWN hydroponics trays on eachother

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8504]
(WEB REPORT BY: lavoss REMOTE: 158.69.55.2:7777)
open abandoned crate, get the hydroponics trays, they will be 3 stacked on eachtoher and automatically wrench down when its open, all on eachother, regardless of terrain.

**Comment by Exxion** [comment]
They also can't be put back in the crate even if unwrenched, I think

**Comment by 9600bauds** [comment]
I believe if you input the wrong number too many times and the crate explodes, the component parts of the tray (stock parts and a couple beakers) also spill on the ground instead of being deleted

**Comment by ihadtoregisterforthis** [comment]
That last one sounds rad though
