### ISSUE TITLE
package wraps and boxes

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8509]
if you use a package wrap on a box, you will put the wrap inside the box instead of wrapping it, therefore you can't use boxes to be sent as parcels.
i think that it would be useful if you could wrap boxes; maybe you could put the wrap inside it with a specific intent? or with alt (or ctrl) + click?

**Comment by Shadowmech88** [comment]
You used to be able to wrap boxes, I'm not sure what changed it.

**Comment by ConkerDev** [comment]
You can wrap up boxes with package and gift wrap as of 27c61b851146f75ef8e5437567891aa749b953be

**Comment by nervere** [comment]
Tested, this is no longer an issue.
