### ISSUE TITLE
AMEs still shit a brick sometimes when they're made

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8510]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/fFq3Ekq.png

Stupid cores not working.  It's been broken for like six months at this point!

**Comment by ihadtoregisterforthis** [comment]
You are too slow. But there's a button on the controller to refresh them.

**Comment by AutismSpider** [comment]
Work faster dummy use the refresh button on the controller tofix it
