### ISSUE TITLE
Medbay has straightjackets and muzzles, but not blindfolds

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8511]
I'm not sure of how abusable this could be. In fact, I'm not sure if Medbay should even get a blindfold. But it's still a little weird.
I think wearing a blindfold also heals eye organ damage, so there could be at least one positive use for it. It's also the only way to stop a conscious vampire from glaring.

**Comment by Ephx1** [comment]
> I think wearing a blindfold also heals eye organ damage

wat

**Comment by 9600bauds** [comment]
I think the Wiki claims so, at least
I guess you're resting your eyes?

**Comment by Ephx1** [comment]
I swear I should get back to fixing the wiki, so much shit in there is rulings that have no basis in the rules, and myths carried over from other servers.

**Comment by 9600bauds** [comment]
I just looked it up in the code and it turns out that wearing a blindfold reduces eye blurriness faster, not heal eye organ damage. Which is much less useful.

**Comment by Shadowmech88** [comment]
Why does Medbay have straitjackets and muzzles?

**Comment by 9600bauds** [comment]
Presumably for antags
That is, to immobilize an antag, or for an antag to antag with
I was going to straightjacket a newcop since they explode when they die, but he died anyways

**Comment by Shadowmech88** [comment]
Ostensibly the justification for straitjackets and muzzles in a medical bay could be that their primary purpose is to prevent patients from harming themselves. However, I can't see any such justification for blindfolds in a medical bay.
I'm not saying they should or should not be added, but adding blindfolds to Medbay would not, I think, make sense from an in-universe perspective.

**Comment by 9600bauds** [comment]
Well, the muzzler is not preventing you from harming yourself either
The blindfold has at least one positive use, even if we just found out it's kind of useless

**Comment by Shadowmech88** [comment]
An un-muzzled patient could bite themselves or ingest non-food material. Not in-game of course, but then I'm speaking from a purely in-universe perspective.

**Comment by 9600bauds** [comment]
It has one worthless but legitimate use, kind of like the Stethoscope. I would also like a blindfold so you can actually hide shit inside people while doing surgery without them seeing all of it through their unconscious overlay. As antag, of course.

**Comment by Shadowmech88** [comment]
Even with the unconscious overlay, people could always see in one tile around them.

**Comment by 9600bauds** [comment]
Yes, that's the point, with a blindfold you can't see anything

**Comment by mikecari** [comment]
do muzzles prevent wiznerds from using their spells? Just a thought.

**Comment by 9600bauds** [comment]
~~I don't think so, given that Mime Curse doesn't prevent it~~
Actually they do, neat
