### ISSUE TITLE
Full vision while anaesthesized from surgery anaesthetic tank

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8512]
Couldn't move, couldn't speak, couldn't hear anything, but I could still see perfectly fine. I got to see four newcops come into Medbay through the Surgery Observation windows. It was pretty exciting, but still.

**Comment by Shadowmech88** [comment]
This is happening with unconsciousness in general, I noticed it while passed out from pain/blood loss, as well as when I used the *faint emote.

**Comment by Ephx1** [comment]
#3583
Might be related

**Comment by 9600bauds** [comment]
Closing in favor of #3583
