### ISSUE TITLE
Remove Blindness Circle of Sight and Update Blindfold

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8513]
I'm referring to that tiny circle in the center of the blindness/unconsciousness overlay that allows you to see portions of the eight tiles around you.

Now that it's possible to click on things through darkness (such as when firing a gun in complete darkness) I think the blindness overlay should be made exactly like the blindfold overlay, and have its restrictions on what you can click removed, though machinery should still be excluded somehow.

The blindfold overlay itself should also have these restrictions removed. There's no reason you should be able to fire a gun in complete darkness, but not while blindfolded.

In this way, you would be able to pick things up and use them as normal, you just wouldn't be able to see what's around you at all, like actually being blind.

**Comment by Killette2** [comment]
Funfact: It is solid black when you blindfold people. Nobody uses the blindfold though so this isn't common knowledge.

**Comment by ihadtoregisterforthis** [comment]
Blindness could be a lot more flavorful with stuff like being able to examine stuff on your hands and speech bubbles wherever someone speaks. 
The current overlay is terrible. Even without eyes you can see your surroundings and even get a glimpse of your entire line of sight every few seconds. But of course this is for gameplay, so a rework would need to still take into account stuff such as knowing if you are against a wall, or drifting in space.

**Comment by Shadowmech88** [comment]
If possible, I'd like the blindness overlay to completely obscure items, but still allow you to see what things are by mousing over them as long as you're adjacent to them. So you could "feel" what's around you using the mouse.
The unconsciousness overlay should have no such ability because you're unconscious.

**Comment by BestName** [comment]
49f3db9954ea41bcbb046457ff1db28d90f6c473
Go ahead and revert it :^)

**Comment by Shadowmech88** [comment]
@BestName 
I'm not sure what point you're trying to make.
Additionally, simply removing the circle wouldn't address any of my other requests, and I'd do it myself if I knew enough about HUD stuff.
