### ISSUE TITLE
library issues

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8514]
1- if you search books in the check in/out computer or the visitor computer and you choose a category, the option window appears 2 times, the first time with 6 options (any, fiction, non-fiction, adult, reference, religion), the second with 5 options only (all except "any"); the choose on the second window is ignored.

2- if you choose the "any" category it won't show any book, because the game thinks that "any" is a category itself; this means that if you choose a category you can't see the full list anymore.

3- the 'Ace Reporter Intercom manual' paper in the private study on boxstation have some outdated info (on a side note, the 'DJ Listening Outpost' paper on the dj satellite also has some wrong info).

![stuff](https://cloud.githubusercontent.com/assets/6170726/13367936/a9f35d14-dce6-11e5-9b56-ca6bb6d8bd56.jpg)

**Comment by uazuaz** [comment]
added a picture in the OP.

**Comment by PJB3005** [comment]
You know issues are a lot easier to manage to keep them focused on one thing...

**Comment by uazuaz** [comment]
well, 1 and 2 are on the same machine.
3 are just text files to modify slightly.
maybe I would have to open 2 separate issues, next time i will do it.
