### ISSUE TITLE
Lawgiver Balance

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8515]
As it stands, it's obvious that the Lawgiver is overpowered, but I don't know if everyone has the same reasoning for why they think it is. Once I'm done with my current project I'd like to update the lawgiver to make it, while powerful, still balanced enough for it to be obtainable outside adminbus somehow.

The current idea I'm running with is to replace the gyrojet rounds with ricochet bullets, but I don't know whether that alone would satisfy most people.

**Comment by Imagebard** [comment]
Its not supposed to be balanced.
You can create a balanced but not lore correction if you want tough, instead of completely replacing the old lawgiver. I can even help. Want it?

**Comment by Shadowmech88** [comment]
That's what I was planning to do in the first place. The current lawgiver is still going to remain spawnable. But I'd like to create a version of the lawgiver, with the five-ammo-types and rechargeable-magazine features intact, that is still balanced enough for it to be obtained in some way that doesn't require direct admin intervention.
The best solution for this, it seems to me, would be to give the new one different projectiles from the current one.

**Comment by Imagebard** [comment]
>with the five-ammo-types and rechargeable-magazine features intact

At this rate we're going to end up with the same problems that made the Lawgiver a shitty gun to give out to security.

**Comment by Shadowmech88** [comment]
What problems are those?
This is why I made this issue, to get an idea of _why_ each person thinks it's overpowered.

**Comment by Imagebard** [comment]
I think its bad for security because they get 5 stun shots and about 20 lethal shots. 1 being stun rounds, the other being the laser cannon, SMG bullets, the flare shot, and the gyrojet pistol.
CLEARLY the 12 interchangeable rounds idea is superior.

Or if you're going to change it without coding new shit, I guess you could make it use different bullets compared to the other one
OLD MATCHUP: Taser, Laser Cannon, SMG, Flare, and Gyrojet
NEW MATCHUP: Taser, Ricochet Bullets, Assault Rifle, non-Traitor Flaregun, [No idea what to put here now]

**Comment by Shadowmech88** [comment]
Actually the old matchup DID have the assault rifle, it was just its rapid-fire functionality instead of its single-fire functionality.
Non-traitor flaregun rounds are almost useless, I'd rather replace it with something else entirely if I'm removing the traitor flaregun rounds.

As far as being bad for Security, do you mean bad for general-purpose security due to how frequently they need to stun when making arrests? Because I intended this as more of an offensive weapon than an all-purpose weapon.
Or do you mean bad for combat-purpose security due to how heavily the current combat system relies upon stuns?
Or both?

**Comment by Imagebard** [comment]
When you said that you wanted admins to spawn the Lawgiver more, I assumed you meant that you wanted Security to use it more, not more people using it for combat. It would happen more often, anyways.
Can you specify what you want form it again?

*Also, the current lawgiver uses TRAITOR Flaregun rounds.*

**Comment by ihadtoregisterforthis** [comment]
@Imagebard stun cartridges?

**Comment by Shadowmech88** [comment]
I know what the current lawgiver uses, I'm the one that coded it. I made it use traitor flaregun rounds _because_ normal flaregun rounds are useless offensively.

Additionally, I never said I wanted admins to spawn it more. I said I wanted to create a version that would be balanced enough to be allowed to be obtained _outside_ admin intervention i.e. orderable from Cargo, requestable during code red like an ERT, et cetera.

**Comment by Imagebard** [comment]
>I'm the one that coded it

I wanted to remind you that you're an horrible person while we're here since I'm probably going to forget that you coded it next week.

>I made it use traitor flaregun rounds *because* normal flaregun rounds are useless offensively

It has tactical value if its dark, and I was thinking that not everything had to be combat, anyways.

>orderable from Cargo, requestable during code red like an ERT

Make sure to include Judge Outfits outside of admin intervention then, too.

**Comment by Blithering** [comment]
Replace gyrojet with a function like the tunneller weapon from the ghetto set, can store and fire exactly one beepsky.

**Comment by Shadowmech88** [comment]
I rebalanced the Lawgiver some time ago, so this can be closed.
