### ISSUE TITLE
Plasmamen: Have blood, don't bleed

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8516]
So this is a little weird, Plasmamen are stated to be skeletons that are on fire, and Skeletons don't have blood. By "don't have blood", they actually can't process any reagents because they don't have a bloodstream.
This is not the case for Plasmamen: They DO have blood, medicines work on them etc, they just don't bleed. If you scan them with a health analyzer, they even show a full 560cl of blood (which is fine since their sprite seems to still have flesh on it).

**Comment by mikecari** [comment]
Dionae can use chems too and they dont bleed either, right?

**Comment by 9600bauds** [comment]
Dionae are stated to always have 0% blood, I guess they have a different metabolism
In any case Dionae are extremely robust against brute damage anyways

**Comment by AutismSpider** [comment]
Magic dionae liver and kidneys  that let them intake chems.

Plasma men don't have blood but have a working heart liver kidney etc skeletons  don't

**Comment by 9600bauds** [comment]
but how chemical get 2 liver??

**Comment by AutismSpider** [comment]
Need ask why they can eat food and drink shit not even skeletons can do that.

**Comment by 9600bauds** [comment]
Seems like they're functionally closer to a zombie than a flaming skeleton, then

**Comment by AutismSpider** [comment]
well the icons for plasma men have bits of meat and skin on them all burn up.

**Comment by 9600bauds** [comment]
Having a playable race that can't process chemicals would be a pretty important change too, I guess
So this begs the question: Why don't they bleed?

**Comment by AutismSpider** [comment]
Pain in the ass to do surgery on them need take the suit off to fix organs Internal Bleeding etc

So if one happen to come in with internal bleeding the surgery would kill them

**Comment by 9600bauds** [comment]
You can do surgery through plasmamen hardsuits
It's how you fix their bones

**Comment by Exxion** [comment]
Pretty sure Skellingtons don't process reagents

**Comment by AutismSpider** [comment]
should be fix that they bleed plasma or some thing flameing skeleton made of plasma now and shit same with the all the organs they have now most of the organs.

@Exxion Skeletons can't eat most food (only meat) drink or take pills or any chems they have no skeleton or organs for that matter.

**Comment by Kitfox88** [comment]
plasmamen are just ghouls with the copyright removed so duh they have blood

**Comment by 9600bauds** [comment]
http://strawpoll.me/6986456/r

**Comment by Shadowmech88** [comment]
Bear in mind that reagents not working on them would be a serious nerf.

**Comment by 9600bauds** [comment]
I believe Plasmamen are in need of a nerf.

**Comment by Shadowmech88** [comment]
In what ways are they superior to vox, the other free-hardsuit race?

**Comment by 9600bauds** [comment]
NO BLEEDING, 0.5x burn damage, NO BLEEDING, Sec can't ever remove your suit to search you or for brigging, NO BLEEDING, No slowdown on their free suit, NO BLEEDING, Immune to plasma contamination, NO BLEEDING
I mean really I'm shocked you had to ask

**Comment by ihadtoregisterforthis** [comment]
All this racial balance for minmax that isn't happening should come to an end soon. It only got skeletons removed, and it will take more victims.

**Comment by AutismSpider** [comment]
even skeletons had down side when they were playable they took 200% more brute damage so tool box/floor tiles were deadly as shit.

**Comment by 9600bauds** [comment]
AFAIK Skeletons were removed due to playerbase, not due to minmax

**Comment by AutismSpider** [comment]
yes and the same awful player base it had has move to plasma man even Rei point out this would happen.

**Comment by Zth--** [comment]
I think that skeletons shouldn't have brute/burn/toxic damage. They should be immune to everything, but fragile. The only way to kill them would be to cut their limbs off

**Comment by Exxion** [comment]
OK but if they can't take damage their limbs can only be cut off with the HF blade
