### ISSUE TITLE
Make it so that you can't remove parts from a tank transfer valve if it's superglued to your hand

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8517]
A gimmick of this octane deserves some justice

**Comment by LordMyroc** [comment]
[Honk]

**Comment by Shadowmech88** [comment]
All superglue does is set can_drop to 0, right?
I think it'd be super easy to add a check for this.

**Comment by AutismSpider** [comment]
superglue is missing checks for two handed items.
