### ISSUE TITLE
New weapon idea: Gauss/magnetic weapons

### ISSUE THREAD

**Issue by icantthinkofanameritenow** [d3athrow/vgstation13#8519]
While I was working on tweaking the XCOM weapons, I had an idea to add Gauss weaponry as well. Let me know if this sounds like something you'd like to see and I'll try and code it all up. 

-High research requirements: minimum Combat 6, Materials 6, and Electromagnetic Spectrum 5 (so this means that RnD will need at least a combat shotgun to add to the DA)
-Projectile-based weapons that pierce objects similar to the PGM Hecate II, albeit not as effectively. 
-Each shot deals a considerable amount of damage, but they have small ammo capacities, no burst fire, and a long delay between shots. That said, even one shot with it should deal considerable damage. 
-Currently considering three types- a regular rifle, a heavy gun, and a mech-mounted version that would be a mech's answer to the Solaris. Because let's face it, the Scattershot isn't very good. 

Thoughts?

**Comment by ghost** [comment]
Why?

**Comment by Blithering** [comment]
So its a souped-up combat shotgun that also pierces and doesn't need to be manually pumped? Poor wizards.

**Comment by Shadowmech88** [comment]
Last I checked, it's possible to max combat research using only what can be manufactured in Science.

**Comment by icantthinkofanameritenow** [comment]
@Blithering
Combat shotguns fall off with range and can use different ammo, so it's not entirely a correct comparison. It would be a little more like the assault rifle. 

It would only be capable of piercing a single wall, that said. It would probably also have a fairly high materials cost too.

@Shadowmech88
I was sure it could only go up to 5 without using combat shotguns. Was that changed recently? If so, I guess I could pump the requirement to Combat 7.

**Comment by Shadowmech88** [comment]
@Icantthinkofanameritenow I believe it's chemical masks, with a combat tech of 5, that enable R&D to reach combat 6.

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88
Ah, right. 

Is it possible to reach Combat 7 in-game?

**Comment by AutismSpider** [comment]
@icantthinkofanameritenow combat 7 is with nuke ops weapons only and getting to five is a joke you can do it with mech boards are cheap to make.

**Comment by Shadowmech88** [comment]
I don't believe so.

**Comment by icantthinkofanameritenow** [comment]
@Autismspider
Combat 6 it is then. I'll just have to supplement it with Materials 7 and Electromagnetic Spectrum 5 or so. I know the latter is acquirable by deconstructing diamonds at least. 

And to clarify, I'll be the one coding this. Eventually, anyway. (On that note, if anyone wants to sprite it, be my guest. Otherwise I'll have to do that too- assuming I can find decent pics of the XCOM magnetic weapons for it.

**Comment by FudgePucker** [comment]
OH BOY MORE SCIENCE WEAPONS

**Comment by AutismSpider** [comment]
@FudgePucker more pointless weapons for Science you mean as they have long ass list of weapons they can make some of them being silly as shit and strong

**Comment by icantthinkofanameritenow** [comment]
Closing due to apparent lack of interest and lack of time on my part.
