### ISSUE TITLE
Easy simple genetic power idea

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8520]
The power is pain immunity. Self explanatory, you don't suffer from the effects of pain, such as from long lasting burns or broken bones. Makes logical sense and is even a real defect/power in real life, would be neat for the game fam.

**Comment by 9600bauds** [comment]
When has pain ever mattered

**Comment by NigglyWiggly** [comment]
As long as it's only the shit like where you can't get up because of pain.
Being able to properly use a broken limb would be silly
Just make sure there's never any change in your health HUD thing if you have it so you never actually know if you're injured unless you examine yourself

**Comment by Killette2** [comment]
That works niggly. The main focus was to remove pain blurry vision and pain stunlock/passing out. Also if you're a diona you can wheelchair around with every bone broken for fun, but not be able to use your arms effectively.

**Comment by AutismSpider** [comment]
@9600bauds As a plasma man got both my legs and arms busted by spider queen play dead to heal up a bit could not get up form massive pain+black out spam

**Comment by clusterfack** [comment]
I'd support this

On the condition your health HUD always appears at 100%

**Comment by Killette2** [comment]
That sounds like it would just lead to powergaming and being better off anyways due to constantly having a health analyzer/borer on you.

**Comment by 9600bauds** [comment]
Exactly
It's brilliant

**Comment by clusterfack** [comment]
You wanted pain immunity, seems like that would be something that pain immunity would entail

**Comment by 9600bauds** [comment]
Also gets rid of the messages that warn you when internal bleeding and such happen
Actually, Diona already have pain immunity...

**Comment by Zth--** [comment]
There's an unused health icon which shows a gray person with a "?" sign. This would be the perfect moment to add it

**Comment by ghost** [comment]
:+1:

**Comment by SangriaMonkey** [comment]
What about the stupid fucking Errorage jelly screens we still have? They kind of negate the downside.

**Comment by Killette2** [comment]
What does WYCI mean?

**Comment by Exxion** [comment]
# When You Code It®️

**Comment by Killette2** [comment]
I think a chemical does everything this feature request ask for now. All we would have to do is make a super power produce it, it's already coded

**Comment by Exxion** [comment]
(It's a meme tag)

**Comment by Shadowmech88** [comment]
>All we would have to do is make a super power produce it, it's already coded

Right, but I don't think anyone cares enough to do so.
*You* could do it, though.
