### ISSUE TITLE
Malf AI was carded AFTER being shunted

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8522]
AI later went on to win because the entire crew was incompetent except the guy who blew the shunt APC

**Comment by Ephx1** [comment]
I've had this happen once, a long time ago.
I was malf, people began to attack the core, shunted, then when I won I hopped back.
I immediately went straight back to the card instead of the core, netting the crew a neutral win.
I can only assume my core was carded during my time of shunting.

**Comment by gbasood** [comment]
#8523 should be fixed now
