### ISSUE TITLE
Biting and Kicking don't work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8524]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c10f8a4ec34abe8707f1c6839c8fd6acb7e00ac1 
> 
> General description of the issue
> they don't work, but you can't kick Vending Machines anymore so somethings working I guess??
> 
> What you expected to happen
> to kick or bite
> 
> What actually happened
> i just punch
> 
> Steps to reproduce if possible

<><

**Comment by Del1m** [comment]
Steps to reproduce:
1. It doesn't work.

**Comment by Exxion** [comment]
Nothing works
You can't switch to the intents at all
@unid15

**Comment by unid15** [comment]
Oh fuck

**Comment by Exxion** [comment]
100% tested<sup>®™</sup>

**Comment by unid15** [comment]
just launched a local server and it 100% works

it must be the secret repo

**Comment by Exxion** [comment]
Damn it
What's even IN there?

@d3athrow help

**Comment by Kitfox88** [comment]
oldcode™ a shi

**Comment by clusterfack** [comment]
Assumably fixed?

**Comment by Exxion** [comment]
Yes, but the hotkeys still don't work
