### ISSUE TITLE
Things can both bounce off a disposal bin's rim AND land in the bin

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8527]
![image](https://cloud.githubusercontent.com/assets/9827785/13372165/4db26046-dd08-11e5-93a0-1a13a85a8561.png)

`else if`, where you at?

**Comment by Zth--** [comment]
It bounces and then lands. Grammar issue?

**Comment by Exxion** [comment]
It's supposed to give one of those messages, not both

**Comment by Shadowmech88** [comment]
Even still, the messages still make sense. It's completely possible to bounce something off the rim of the container into the container itself. 
I don't think this really needs fixing.

**Comment by Ephx1** [comment]
Also an exclamation point and period.

**Comment by 9600bauds** [comment]
Trickshot

**Comment by PJB3005** [comment]
It's like basketball.

"ooooh-noo-ooooh YES"

**Comment by Probe1** [comment]
wait i should fix that grammar.
