### ISSUE TITLE
Heavy bags should slow you down.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8528]
Discuss.

**Comment by Exxion** [comment]
I've always found it silly that a backpack can always hold seven items, regardless of their size
I think we should make more use of `max_combined_w_class`

Also, without another change to how slowdown works, bags couldn't slow you down when held, only when worn

**Comment by Exxion** [comment]
A backpack can hold over a cubic meter of iron but only seven mice, pens, etc.
How big are these mice?

**Comment by LordMyroc** [comment]
Volume based backpacks when?

**Comment by CptWad** [comment]
@LordMyroc has a point. Similar to plastic bags only with much more space

**Comment by FudgePucker** [comment]
No.

**Comment by Kitfox88** [comment]
VOLUME BASED BACKPACKS WHEN.

**Comment by 9600bauds** [comment]
When storage code dynamically shows slots based on volume

**Comment by PJB3005** [comment]
@9600bauds bay has something like that

**Comment by AutismSpider** [comment]
@9600bauds Take the Bay one and rework it a bit

**Comment by PJB3005** [comment]
https://github.com/Baystation12/Baystation12/pull/10095

**Comment by Imagebard** [comment]
Eh, backpacks are fine as they are right now.
For reference, you still can't put w.class 4+ items in your backpack on that system, right?

**Comment by 9600bauds** [comment]
I don't think heavy backpacks should slow you down, but I think carrying my tools inside a box in order to get more storage slots is really stupid and I would like to stop doing it

**Comment by 9600bauds** [comment]
@PJB3005 As always, some player's mentality around changing the way backpacks work is "but if I can't carry exactly the same items I could carry before then you've nerfed bags FOR NO RAISIN"

I have seen this mentality many times before and I have no doubt that I would become the new Dylan if I even hinted towards working on this so I will pass.

**Comment by PJB3005** [comment]
The difference between doing that and becoming dylan is that dylan is shit at coding.

**Comment by Intigracy** [comment]
Celt hates fun.

**Comment by clusterfack** [comment]
If someone makes a PR to actually use ```max_combined_w_class```, I'll accept it
