### ISSUE TITLE
AI shuttle calling

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8529]
(WEB REPORT BY: harmlessbirdy REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> No button in AI ui to call shuttle.
> 
> What you expected to happen
> To find a button in AI ui to call shuttle.
> 
> What actually happened
> I couldn't call the damned shuttle.
> 
> Steps to reproduce if possible
> No clue, didn't show up during my time as AI.

**Comment by PJB3005** [comment]
Fuck.

Hud.

Code.

**Comment by Intigracy** [comment]
Was this fixed?

I see the hud button fine now.

**Comment by Allspice** [comment]
Werks fer me, and I haven't seen any additional complaints about this.

**Comment by 9600bauds** [comment]
werks
