### ISSUE TITLE
Grinding nettles in a mortar gives nothing

### ISSUE THREAD

**Issue by viniciuspetch** [d3athrow/vgstation13#8532]
Using the mortar to gind nettles results in dissapointment. Instead of receiving sulphuric acid (I believe it's 10u, because grinding 4 in a grinder gave me 40u), I got nothing, not even some sort of 'nettle juice'.

I tested with death-berries and fly amanitas, but those gave me their chemicals (nutrition, toxin, lexorin, amatoxin, psilocybin).

Is this really a bug or I'm missing something?

**Comment by 9600bauds** [comment]
Will be fixed in Kurfurst's grinder refactor
