### ISSUE TITLE
Buff non-borg RCDs.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#8534]
Let's face it they're shit.

They use WAY too much matter, the cost for cartridges is WAY too high.

**Comment by FudgePucker** [comment]
Reduce the charge cost on constructing.
Reducing the material cost on matter carts would buff the mat synth, fuck science

**Comment by Ephx1** [comment]
Pls don't forget mech RCDs.
#6745

**Comment by AutismSpider** [comment]
Lower the cost on making airlocks and walls

**Comment by ihadtoregisterforthis** [comment]
Increase maximum ammo

**Comment by PJB3005** [comment]
Give all engineers RCDs.

ID lock RCDs too if it's considered too high risk.

**Comment by AutismSpider** [comment]
ID lock not going do much when you can hack this one thing to shit out endless RCDS and RPDs both cost shit ton of iron and glass to make any way

**Comment by CptWad** [comment]
RCD's should be low on availability because they can deconstruct airlocks
thats a big deal
imagine, a clown who can deconstruct all the stations airlocks in 30 minutes

**Comment by clusterfack** [comment]
A traitor with an emag can do it in five, boom baby.

**Comment by CptWad** [comment]
You can repair emagged doors, there's plenty of ways.
The RCD makes it gone forever

**Comment by AutismSpider** [comment]
RCD make poof walls floors and airlocks and the sparks it makes good for setting off fires etc

**Comment by ghost** [comment]
RCD's are a huge combat tool because deconstruct in ZAS.
Classically only the QM really used the RCD for building shit, because only he had access to unlimited glass/metal.
tbh there's no problem with rcd atm
