### ISSUE TITLE
Vox miners have human internals gear in their starter internals box

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8537]
According to some guy

**Comment by clusterfack** [comment]
>According to some guy


That's not how this works, that's not how any of this works.

**Comment by Gringonius** [comment]
That's me.

**Comment by PJB3005** [comment]
They do for any jobs that spawn with an extended O2 tank, I can confirm it.

(miner, engineering are 2 that come to mind)

**Comment by uazuaz** [comment]
similar issue for plasmamen, they spawn with oxygen internal boxes; i know for sure that this affects assistant and cargo tech, a guy on the server said me that this affects all jobs.

**Comment by clusterfack** [comment]
It's very likely species code is handled before job code, thus overwritten

**Comment by Intigracy** [comment]
tbh plasmamen is harder to fix because there isn't a mini version of the plasma internals, only the big tank.

**Comment by PJB3005** [comment]
So I checked. 

The code for the emergency tanks is copy pasted into each job's equip proc.

**Comment by 9600bauds** [comment]
has been fix'd
