### ISSUE TITLE
Golden Atmos Suit

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8540]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 4e11d5568ded75a90d80a226b92a6311e2c32fb7 
> 
> General description of the issue
> Modified Atmos helmet does not have a lightsource
> 
> What you expected to happen
> Golden Atmos Helmet has a flashlight like regular one.
> 
> What actually happened
> It doesn't.
> 
> Steps to reproduce if possible
> Modkit

It's a feaatuure?

**Comment by AutismSpider** [comment]
it does have a light but it bugs the fuck out when mode kit is use on it

**Comment by Imagebard** [comment]
[Not A Bug]
Sorry lad, that's intentional.

**Comment by gbasood** [comment]
``` DM
/obj/item/clothing/head/helmet/space/rig/atmos/gold
no_light = 1
```

confirmed

**Comment by ghost** [comment]
I'm not sure it's not a bug in that it was intentional, I think they couldn't be arsed to sprite a light on.
