### ISSUE TITLE
Megaseed servitor seed storage

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8541]
> What's the problem?

When putting in seeds into the servitor by hand (For example, banana seeds), they'll appear on the list of objects to vend, but when you attempt to retrieve them from the machine, it'll spit out a blank seed packet with no type, potency, or anything. When this seed packet is applied to a tray or dirt, you get "The packet seems to be empty. You throw it away."

What's weird is that the smartfridge manages to store and retrieve the seed just fine.

**Comment by 9600bauds** [comment]
This is the fifth or so bug report we have on this thing @DeityLink
Until then just use the seed extractor

**Comment by 9600bauds** [comment]
Related to #6551
