### ISSUE TITLE
Gibbing a mob doesn't drop or delete the contents

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8542]
Was fiddling with adding things to mobs, and seeing if gibbing them would drop said added things, and came across something odd - contents of gibbed mobs stay with the mob

> How to reproduce

Add a marked object to a mob (In my case, a panda to a dead chicken), gib said mob to see if it drops its contents, objects aren't dropped, go into adminghost and go AFK, see that whatever you added made a noise (if it could), jump to it, be stuck in nullspace (watching a space panda try to maul its way out of a chicken)

> What you expected to happen

Either the object put in the contents variable of the mob have a chance of being left in the gibs when a mob is gibbed, or for the contents to be deleted (Could be not a bug in this case, I'm not too familiar with how qdel might work)

> What happened

Space panda stuck in purgatory

**Comment by Exxion** [comment]
It drops certain (probably) hardcoded items and that's it
I bet you can nullspace the nukedisk by putting it in someone's backpack and blowing them up

**Comment by ihadtoregisterforthis** [comment]
If that's true then filling a rooster with a hundred chicken breasts should drop them all on Gib, right?

**Comment by Exxion** [comment]
Should, but doesn't

**Comment by Shadowmech88** [comment]
`gib()` calls `qdel()` on the mob, right?
All you'd need to do is put a loop that drops everything in the mob's contents in `/mob/Destroy()`.

**Comment by PJB3005** [comment]
@Exxion you can and it's been reported multiple times in the past.

**Comment by ghost** [comment]
Now, the problem with adding a loop to drop everything, is that gibbing a human with that setup would drop all their clothing and worn objects, as that's set to contents.

Could do with some way of differentiating between internal and external contents, unless that's a thing already

**Comment by gbasood** [comment]
I think that contents should be handled on a case-by-case basis, like with borers, for instance.
If it isn't handled before mob/Destroy() gets called, qdel the contents. Bam done

**Comment by Shadowmech88** [comment]
Would it be a bad thing for mobs to drop their clothes when gibbed?

**Comment by clusterfack** [comment]
It deletes objects, it does not check for mobs. I'll generalize it to atom/movable instead.

This explains how borers got nullspaced all the time (instead of being murdered to death) when their host got destroyed.
