### ISSUE TITLE
Inactive AI Core can't be interacted with

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8543]
(WEB REPORT BY: jactually REMOTE: 158.69.55.2:7777)

> Revision 
> bef905aad65ed3da2ed3b0d1b185921b2013dd84
> 
> General description of the issue
> We built an AI core but forgot to put the brain in. After that we couldn't take it apart or pull it or anything. Examining it just prints "That's Inactive AI".
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Ephx1** [comment]
Inactive cores are made mostly to move around AIs more effectively, but there should seriously be a deconstruction process for them.
Forgetting to put the brain in happens way too many times.
