### ISSUE TITLE
You can kick paitings off walls.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8544]
(WEB REPORT BY: jeroen52 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> bef905aad65ed3da2ed3b0d1b185921b2013dd84
> 
> General description of the issue
> If you kick a painting, it will move 1 block. Do it correctly and you can kick one off a wall.
> 
> What you expected to happen
> My leg!
> 
> What actually happened
> Kicked a painting into the middle of a hallway.
> 
> Steps to reproduce if possible
> Harm intent, kick intent, kick the crap out of it.

**Comment by Kitfox88** [comment]
requesting feature tag
