### ISSUE TITLE
Can't bite fruits/veteables

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8546]
(WEB REPORT BY: gringonius REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> bef905aad65ed3da2ed3b0d1b185921b2013dd84 
> 
> General description of the issue
> Trying to bite said plants off the floor gives you the "You have been attacked in the chest with the eggplant by [your character name]! message.
> 
> What you expected to happen
> For you to eat the plant, like how it happens with actual food items such as getmore food and chef recipes.
> 
> What actually happened
> What I described.
> 
> Steps to reproduce if possible
> Just bite a vegetable.

**Comment by 9600bauds** [comment]
inb4 biting is calling attack(user) on food
were you in harm intent

**Comment by Gringonius** [comment]
Yes, considering I need to be on harm intent to even trigger biting.

**Comment by unid15** [comment]
Biting calls attack self, which calls attack

It's a mess
