### ISSUE TITLE
[Deff] No soap in Janitor's closet

### ISSUE THREAD

**Issue by Megamaw** [d3athrow/vgstation13#8547]
Okay, so I just started a round on Deff as janitor.

Duny, I can understand that not a lot of people play janitor, but I'm going to let you know that soap is a very important tool for us, and it can be a pain in the ass to clean up cobwebs and messes on walls without it. I've only checked one custodial closet, but if the second one doesn't have one either, could you consider giving each closet a bar of soap?

Thanks.

**Comment by Duny-** [comment]
No problem famjam

**Comment by uazuaz** [comment]
soap is "overpowered" for janitors, what's the point of using the mop?

**Comment by Duny-** [comment]
Making yakety-saxing retards slip of course
Also immersion
