### ISSUE TITLE
Hecate zooming issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8558]
(WEB REPORT BY: shiggypiggy REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8e41549598692a389f505653ab4144f5309dbd39
> 
> General description of the issue
> If you zoom out and then unzoom using the Hecate, your screen turns black
> 
> What you expected to happen
> To successfully see
> 
> What actually happened
> I couldn't see, neither relogging nor cancel-camera-view did anything
> 
> Steps to reproduce if possible
> Get a hecate, zoom in, zoom out

**Comment by ghost** [comment]
Hecate?

**Comment by ghost** [comment]
The big sniper rifle.

It's a problem with resizing the clients view window, it happens when scrolling out a lot, then rapidly scrolling back in as a ghost

**Comment by PJB3005** [comment]
Sounds like that viewport freezing issue.

**Comment by clusterfack** [comment]
I've made a bug report about this some time ago
http://www.byond.com/forum/?post=2025875

**Comment by robintime** [comment]
tested locally. i don't know what PR fixed this, but this bug no longer occurs.
