### ISSUE TITLE
We could technically remove target areas for melee combat.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8560]
Couldn't we? Wherever you click becomes where the weapon hits. I believe that's possible.

**Comment by Shadowmech88** [comment]
Having to click exactly on the sprite when firing a gun instead of just clicking behind them would be a nuisance.
If it is for melee combat only, then we'd have to keep the targeting HUD overlay for gun use. If we keep the targeting overlay anyway, why would it be better to use this approach rather than that?

**Comment by BestName** [comment]
I'm sure you could but the real question is: Should you?

**Comment by ghost** [comment]
@Shadowmech88 

> melee
> guns

**Comment by gbasood** [comment]
Yeah no I don't want to try for spess headshots with an axe.

**Comment by unid15** [comment]
sounds very fun

**Comment by ghost** [comment]
Why not ™

**Comment by AutismSpider** [comment]
better rework how clicking mobs work then right now its fucking awful

**Comment by clusterfack** [comment]
Well for one reason it blocks off half the body if theyre facing one way. 
Two it makes surgery fucking ANNOYING.

I mean so many things wrong with it need I go on?

**Comment by Exxion** [comment]
I just want hotkeys for zone selection

**Comment by clusterfack** [comment]
Well that would be a lot of of hotkeys, but how about a button that brings up a blown up version of the zone selection menu onto the middle of your screen

**Comment by Exxion** [comment]
In the middle of combat?
There are only 13 zones. The numpad area has easily enough keys.
Alternatively, you could have just a few buttons that each cycle between a few zones

**Comment by Kitfox88** [comment]
let's make it more difficult and stupid 4noraisen :-1:

**Comment by Blithering** [comment]
I see no reason why this would be an improvement to the current system.

**Comment by Shadowmech88** [comment]
I second the numpad hotkey idea.

**Comment by Exxion** [comment]
How's this?

8: Head
5: Chest
2: Groin
7: Mouth
9: Eyes
4: Right arm, press again for right hand
6: Left arm, press again for left hand
1: Right leg, press again for right foot
3: Left leg, press again for left foot

Assuming BYOND actually interprets numpad inputs separately from their "equivalent" keys, which may or may not be the case

**Comment by AutismSpider** [comment]
How is this an improvement? or do you want make it difficult for the sake of it?

**Comment by ihadtoregisterforthis** [comment]
Let's not remove target areas. The display size changes from person to person and players on native would suffer it more. Also clothes with distinctive limb separation might see a decrease in use.

@Exxion 
8 to toggle head, mouth and eyes, 5 for chest/groin. It gives it a cool person-like shape.
Or move them one down and you have them in a tidy rectangle with 7, 8 and 9 free together.

**Comment by ghost** [comment]
why possibly?

**Comment by 9600bauds** [comment]
I don't think anyone will mind if this idea gets canned

**Comment by Shadowmech88** [comment]
It should have the [Unfulfilled Feature Requests] tag, though.

**Comment by Exxion** [comment]
I still don't understand Celt's inability to understand the difference between "technically can" and "actually should"
