### ISSUE TITLE
PSA : Set Base Turf hangs the server

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8563]
This is almost exclusively due to having to replace a million turfs, since replacing the old base turf (Space) does that

This is obviously bad for snow rounds (we could create a snow version of all maps if players REALLY want their snow rounds, wouldn't take long in DM, but might be a pain in the ass to set up)

Otherwise, the ability to change the old turf should be commented or have a very big warning on it, because this shit hangs the server for five whole minutes

It is SLIGHTLY possible that the fix used to load 500x500 maps in the first place was not deployed to the Set Base Turf verb. It's also possible it's broken forever, will have to check

**Comment by ghost** [comment]
Think it's broke forever.

**Comment by ghost** [comment]
First review shows the fix was deployed

So it indeeds looks like changing a million turfs on the fly is not a good idea, which sucks. Or maybe ChangeTurf is more laggy than it has any right to be

**Comment by ghost** [comment]
RIP

**Comment by ghost** [comment]
For reference, this is the whole ChangeTurf proc

A lot more ugly than "Switch space with snow", for sure

http://pastebin.com/KYTNydFB

**Comment by gbasood** [comment]
Could do some waitfor=1 shit

**Comment by PJB3005** [comment]
@gbasood not what wait for is at all.

**Comment by clusterfack** [comment]
It's laggy due to smoothing

**Comment by clusterfack** [comment]
I could use waitfor to make it about 4 times cheaper I think

**Comment by clusterfack** [comment]
But I really don't know if I can ever really save more than that.

**Comment by ghost** [comment]
RIP

**Comment by DamianX** [comment]
I made it not lag years ago
