### ISSUE TITLE
Why the fuck do facehuggers insta KO you?

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8564]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
Jesus christ who let you people code. Fix it.

**Comment by gbasood** [comment]
Duplicate and also I've still got to fix it

**Comment by Imagebard** [comment]
[Not A Bug]

**Comment by gbasood** [comment]
They insta-stun. Notabug.
Also dude you were wearing a bandana what did you expect
