### ISSUE TITLE
Diona dexterity

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8565]
(WEB REPORT BY: lorkhatosh REMOTE: 158.69.55.2:7777)
Not sure if this is a bug or not but apparently grow diona don't have dexterity to bandage up people.

**Comment by Shadowmech88** [comment]
I believe grown dionae should have the same dexterity humans do.
Did you have brain damage or a virus?

**Comment by ihadtoregisterforthis** [comment]
Skills never

**Comment by 9600bauds** [comment]
Adult diona can bandage people

Nymphs cannot ever bandage people

I think this is pretty stupid but it's not a bug
