### ISSUE TITLE
Robotic transformation is incurable

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#8568]
Once contracted copper and spaceacillin don't do anything, the disease keeps progressing as normal. Impossible to escape from the transformation without killing the victim before it finishes its course. 

I'm guessing alien transformation might suffer from the same issue since it's another old disease but I couldn't get it to happen in my test server with xenomicrobes.

**Comment by Imagebard** [comment]
Okay, here we go...
I'm pretty sure this is Not A Bug unless other hardcoded diseases are meant to act like that too.

**Comment by 9600bauds** [comment]
Copper is absolutely meant to act as a cure

**Comment by Gringonius** [comment]
Copper is right there listed as a cure when you use a health analyzer on someone and it used to make the disease go remissive and get a chance to go down in stages until cured like how old diseases worked.

**Comment by Imagebard** [comment]
In which case, 
Bug / Fix

**Comment by 9600bauds** [comment]
![dreamseeker_2016-02-28_23-44-01](https://cloud.githubusercontent.com/assets/6526157/13384530/2ae32082-de75-11e5-80b2-ce1588f7e02f.png)

**Comment by Zth--** [comment]
I've been working with this code today and I saw this

> cure_chance = 5

maybe you were unlucky

**Comment by 9600bauds** [comment]
I tried this twice and couldn't cure it either
if it was actually that, shit's very low

**Comment by Intigracy** [comment]
commenting for easier find
