### ISSUE TITLE
HOW 2 EAT ANYTHING THAT FITS IN YOUR POCKET, ALMOST CERTAINLY INCLUDING THE NUKEDISK:

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#8574]
1. Obtain pizza
2. Insert item(s) (#8187)
3. Put pizza in oven
4. Cook it into something
5. Consume

**Comment by Imagebard** [comment]
Why do you people always include "THIS DELETES THE NUKE DISK" into your issue name?
Doesn't it just respawn?

**Comment by Exxion** [comment]
It doesn't delete the nukedisk
It nullspaces its container
So no, I don't think it does respawn

**Comment by Ephx1** [comment]
Bread, now pizza.
What's the next blackhole food?

**Comment by Exxion** [comment]
All sliceables can have stuff put in them, but I'm not sure how many other than pizza can be put into an oven and baked into something else

**Comment by clusterfack** [comment]
How should we handle what happens to food when it is devoured with items in it?

**Comment by unid15** [comment]
Put the items in the stomach obviously

**Comment by ihadtoregisterforthis** [comment]
Add a stomach organ and damage it until items are removed
Burp or vomit after a while to eject item
Poop
Biting food with a restricted item breaks a tooth and tells you you can't eat it

**Comment by Shadowmech88** [comment]
Make non-food items in the stomach cause toxin damage. The toxin damage will eventually cause them to throw up, thus removing the item from them.

**Comment by AutismSpider** [comment]
make eating the nuke disk rad you slowly+toxins

**Comment by clusterfack** [comment]
>the stomach

Haha that's not really a thing you know

**Comment by Exxion** [comment]
It would be more complex to implement than it immediately seems because, if memory serves, organs are datums, and datums don't have contents lists

**Comment by Kitfox88** [comment]
Can't you just have it reference the internal reagent storage or something?

**Comment by Exxion** [comment]
Reagent storage is also a datum because reagents are datums

**Comment by Shadowmech88** [comment]
Can you create a physical stomach object that exists in the contents of the mob, and assign it as a var to the stomach organ datum?

**Comment by Exxion** [comment]
Yes

**Comment by LordMyroc** [comment]
What if every time you take a bite out of food that has an item in it, you bite into the item, which then drops on your tile?

Seems silly that one should be able to eat things like solid metal pipes because someone put it into bread.

Also allows the chef to properly hide items within food. Smuggling emags into the permabrig, anyone?

**Comment by clusterfack** [comment]
Pizza delivery for permabrig, what am I playing Lego island?

**Comment by NigglyWiggly** [comment]
> Deliver a Pizza to permabrig with tons of hotsauce on it
> Prisoner melts the fucking airlocks by spitting the sauce on them

When are we going to ban that fucking Brickster guy, he's a huge shitter, after that he fucking subverted the borgs again

**Comment by gbasood** [comment]
@LordMyroc Sort of hard to hide things bigger than an ID card in a pizza. Cakes, though, are different
