### ISSUE TITLE
Venom Sword injects stuff even if the hit misses.

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#8576]
![u wut m8](https://cloud.githubusercontent.com/assets/10268342/13404561/cd7e46f4-dedf-11e5-910d-a519da7c505d.PNG)

So how are the reagents getting in the mob if both hits missed?

**Comment by DrCelt** [comment]
Because the sword swinging sprays magic targeted acid in their direction. The blade may not connect, but the acid locks on to its target.

Or because this is a bug. I prefer the first one honestly

**Comment by AutismSpider** [comment]
Well more then just acid in that stasis beaker poly acid and smoke mix

**Comment by Killette2** [comment]
So it only melted things because it was a poly acid smoke mix?

**Comment by AutismSpider** [comment]
smoke burns all the reagents in body/beaker the human body acts like xbox huge beaker for god knows what.

How much it put backs in am not sure with how goofy the smoke tick is.

**Comment by Killette2** [comment]
>1000 units
>huge

**Comment by Exxion** [comment]
Yes
That's over 3 times the size of the largest actual beaker

**Comment by Killette2** [comment]
Deepfriers hold up to 500 units IIRC

**Comment by Exxion** [comment]
And the keg holds 1000
But neither of those are beakers

**Comment by Killette2** [comment]
You can put stuff in a deepfrier, never forget the deep-fry-a-thon which turned out to be a chem bomb in disguise

**Comment by Exxion** [comment]
What happens if you put stuff in a grill, anyway? Because their examine text suggests they can hold reagents.

**Comment by Killette2** [comment]
Why wouldn't they?

**Comment by Exxion** [comment]
Because they're grills
You know
Metal bars over a gas or charcoal fire

**Comment by DrCelt** [comment]
Blame Goofball, Exxion.

**Comment by Kitfox88** [comment]
The sprite suggests they're fast food truck style flat grills rather than a bbq style setup actually.

**Comment by Iamgoofball** [comment]
yeah the grilles are supposed to be fast food "throw that shit on there and let it cook"

fun fact:

back when i did deep fryers at nt and when i ported them here, they didn't hold reagents

that was all u guys

**Comment by DrCelt** [comment]
go home @Iamgoofball

**Comment by Iamgoofball** [comment]
ok i'll see you at 8 let your mom know i'm up for tonight

**Comment by Killette2** [comment]
Why did I imply that grills could hold reagents? Why did anyone?
Why do we hate goofcode so much? He is the only coder I know that's been pushed out
