### ISSUE TITLE
You can card malf AIs now

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8577]
I don't recall this ever being the case, seems like an odd feature that has been brought around recently

> AI goes delta after being found out
> The head staff bust their way through the core
> Card the AI
> And wipe it

**Comment by AutismSpider** [comment]
some one touch some thing when try to card a malf ai it would give you funny ping sound+ red telling you it fail

**Comment by ghost** [comment]
@gbasood SOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by clusterfack** [comment]
Like I said before you should always have been able to card malf AIs, I even remember it being done on a few occasions. 

If you couldn't it'd be extremely easy to metagame malf.

**Comment by Ephx1** [comment]
You can card malf AIs, just not once it has declared so.

**Comment by Exxion** [comment]
I don't really see why you shouldn't be able to card a malf AI
If you can get to the AI in its core, it's doomed anyway, whether or not you have the card
The card makes it only marginally easier to kill

**Comment by Shadowmech88** [comment]
I remember personally carding a malf AI that had gone delta at least five months ago.

**Comment by IratePirate** [comment]
It used to be a metagaming way of checking whether an AI was malf, so I assume it was changed. I don't think this is a bug. If you want to destroy an AI you think is malf, kill it using the card.

**Comment by gbasood** [comment]
@DrCelt Literally all I did was prevent malf AIs that were TRANSFERRED from being carded

``` DM
if(M.mind && M.mind.current != M)
    return ..()
```

**Comment by Intigracy** [comment]
close please thanks fam
