### ISSUE TITLE
Spider queen generation doesn't seem to have a (sensible) upper limit

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8578]
> Queen is created in deff medbay, so the crew has something interesting to do for a change
> Go away for about 5 minutes, as said queen starts chowing down on the available monkeys
> Come back
> There's now 4 queens

Does it scale off spider population, player population, or is just what happens to nurse spiders after a while?

**Comment by AutismSpider** [comment]
no limit to spider queens yet or the spider population for that matter we had rounds were the station cover in spider 300+ in all

**Comment by Shadowmech88** [comment]
Is the spider population not limited by the amount of total allowed animals? It's what limits carp breeding.

**Comment by ghost** [comment]
Send help, it makes spiders a bit crazy.

**Comment by MercuryDoll** [comment]
Everything is spiders
![Everything is spiders](http://i.imgur.com/J4ycoo2.jpg)

**Comment by ghost** [comment]
Pic above started as 5 spiders, 2 nurses 3 hunters. Versus about 3 drones, 2 sentinels, and a xeno empress.

That line of cocoons in front of the conveyors are said aliens.

**Comment by AutismSpider** [comment]
Yup we need a cap on spider queens like two or three

**Comment by gbasood** [comment]
I'd say even 10 queen cap would be a huge improvement

**Comment by ghost** [comment]
Did a bit of research on this today.

It appear the transition is straight from spiderling -> queen courtesy of some evolution code in spiderlings.

Problem here is that it chooses typesof giant_spider, so not only does it choose spider queens, it also chooses a subtype of giant_spider/hunter which spawns dead.

**Comment by Exxion** [comment]
graet

**Comment by Probe1** [comment]
Yeah we should definitely cap it.

**Comment by ghost** [comment]
Almost done now with it

**Comment by ghost** [comment]
Fun thing that I wasn't sure I should fix or not, a spiderling could become Salk the ungrowable spiderling, so a spider hive could have pet tiny spiders
