### ISSUE TITLE
Cage allows you to disposals yourself while locked in

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8582]
(WEB REPORT BY: aceedex REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)8e41549598692a389f505653ab4144f5309dbd39 
> 
> General description of the issue
> being locked in a cage while adjacent to a disposals pipe allows you to disposal yourself, which then teleports you back to the cage once you exti disposals
> 
> What you expected to happen
> For a cage to work like a cage
> 
> What actually happened
> cage bars are made of ghost materials that only work when next to disposals
> 
> Steps to reproduce if possible
> 1. Be in a cage
> 2. be next to a chute
> 3. throw yourself in there
> 4. when you get out of there the cage gods warp you back to the cage

**Comment by Intigracy** [comment]
@unid15
