### ISSUE TITLE
Borgs immune to flashbangs

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8583]
Is this intended?

**Comment by Ephx1** [comment]
It must have been this way for absolutely EVER because I don't recall a time when that wasn't true.

**Comment by Shadowmech88** [comment]
If I remember from my brief look at flashbang code, they were never intended to stun borgs.
The question becomes then, should it be changed?

There's no logical reason why the flash from a flashbang wouldn't stun a borg, so this is a question of game balance.

**Comment by 9600bauds** [comment]
Unfortunately I haven't played enough Sec to be able to have a good judgement on flashbangs in this case
It's weird that they are stunned by flashes but not flashbangs, though.

**Comment by AutismSpider** [comment]
The delay on flash bangs are to long for stopping borgs any way emps would be better stun+draincell and any eng base weapons borg may have.

**Comment by Killette2** [comment]
I thought the judgement was that flash was a concentrated close range brightness and that's why it overrode the borg's sensors. That and flashbangs would become a bit strong.

**Comment by Ephx1** [comment]
I think this is going to need a poll of some sort, this would be a major change up in the list of stuns silicons get, and there's going to be asshurt from both sides.

**Comment by clusterfack** [comment]
Flash bangs would wreck malf borgs really really easily if this change were to be made, so I don't support it.

**Comment by 9600bauds** [comment]
It's not like Malf balance isn't extremely lopsided towards the AI anyways

**Comment by clusterfack** [comment]
Thanks to plasma and supercharged grids solely, you'd be nerfing the wrong thing entirely with this.

**Comment by 9600bauds** [comment]
Borgs having too few and too specific stuns that work against them is a common complaint honestly, then again this is more of a weird thing I noticed.

**Comment by Probe1** [comment]
There are way too many factors at play to say malf is or isn't balanced.  Will there be a lot of borgs or zero?  Does the crew KNOW how to deal with malf?  That's not a guarantee.  I've seen 10 minute timers beaten by a solo AI with no borgs because no one knew what he pinpointers significance was.  

You can only look at the small stuff and say is this too imbalanced or not.

**Comment by AutismSpider** [comment]
Smart malf Ai has the medborg or jani borg poof the pinpointer into space/greygoo

overloading the net with power is mommi thing at this point last time we had mommis link to malf ai was under eggman code or admin was hitting buttons to force link them round start to ai.

**Comment by 9600bauds** [comment]
Currently being voted on http://ss13.moe/index.php/poll/38

**Comment by Ephx1** [comment]
Based Pomf.

**Comment by clusterfack** [comment]
Polls are shit

**Comment by 9600bauds** [comment]
At least it's not biased

**Comment by clusterfack** [comment]
True but without any discussion a concern like the one I raised doesn't factor into it.
