### ISSUE TITLE
Nerf the rad gun.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8584]
(WEB REPORT BY: socachaca REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 8e41549598692a389f505653ab4144f5309dbd39 
> 
> General description of the issue
> The rad gun is retarded OP. Not only it will stun you 100% first shot, it will also deal a grand total of 33 toxic damage to you. Two more shots and you'll be in crit. Plus you will also be a retarded green haired nigger or some other magic from having your DNA completely scrambled to hell and back. 

The gun contains about 21 shots before it runs out of charge, which is enough to take down about 7 players or more or less the same amount as security+vigilantes on at any given time. Did I forget to mention that this recharges automatically?

> What you expected to happen
> Maybe give the crew to actually have the oportunity to fight back or defend themselves and not be like sitting ducks during open season when somebody gets their hands in one of these.
> 
> What actually happened
> Murderboner. Everybody victim of this gun nearly insta-dead. Not a single person could fight back.
> 
> Steps to reproduce if possible
> Be geneticist traitor
> Buy one
> Profit on your cheapass murderboner you faggot

**Comment by 9600bauds** [comment]
Why is the geneticist's unique tator item a GUN?

**Comment by Shadowmech88** [comment]
I think the biggest problem with it is the fact that it stuns on the first hit. But that is, I believe, due to the large dose of radiation rather than some property of the projectile itself. So how could it be fixed while still keeping the irradiating feature of the gun?

**Comment by 9600bauds** [comment]
No, it explicitly stuns, though the radiation probably would KO people anyways. Radiation and mutations are completely different things anyways, I don't see why the gun needs to irradiate.

**Comment by AutismSpider** [comment]
Rad gun can kill a diona in 4 hits (not even the emag flora-ray does that and it only has 6 shots then burns out)  don't get why it stuns on all hits on top of the massive fucking toxin+Rad and dna  scrambled (it only gives bad muts no good ones)

the emag flora ray just rads shit out of you+burns

**Comment by 9600bauds** [comment]
Worth noting that toxin damage means conventional armor doesn't do shit.

**Comment by AutismSpider** [comment]
Well with toxin damage over 40 or so = organ damage so if you some live or they failed to kill you massive toxins  and rads would turn your organs into mush any way.

**Comment by 9600bauds** [comment]
It's 60 toxloss for liver damage and it takes a long time before it starts to kill you

**Comment by AutismSpider** [comment]
forgot if it was fix or not the Rad doing burn damage to cyborgs and stuff.

**Comment by 9600bauds** [comment]
This thing shows it's colors again today. Who made it? What the hell?

**Comment by nuklearcellphoneg** [comment]
I think it'd be more neat if the gun just randomized all genetic defects but

The victim would just eat some ryetalin.
