### ISSUE TITLE
T-t-thanks HUD

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8585]
This happened during a round, will see if it happens next round. My bite was missing, admins told me to press F12 twice. Bite came back for 2 seconds, but my upper left helmet toggle HUD goes missing, as shown in the picture while wearing the CE helmet but with no light toggle.

![hud](https://cloud.githubusercontent.com/assets/5169310/13436850/3bd2d686-dfaf-11e5-8a86-7958c88765f1.png)

**Comment by Killette2** [comment]
Didn't happen again, I blame the CE helmet

**Comment by Zth--** [comment]
Did it happen when you were dead?

**Comment by ihadtoregisterforthis** [comment]
The helmet light going away is because of the F12, happens with all the buttons up there

**Comment by Killette2** [comment]
It was while I was alive

**Comment by DamianX** [comment]
Probably fixed by removing pooling.
