### ISSUE TITLE
Robotic transformation

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8587]
(WEB REPORT BY: pinkacolada REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> It cant be cured, if anything you can only slow it down with copper even if the cure is supposed to be a single 15u copper injection
> 
> What you expected to happen
>  The cure to work
> 
> What actually happened
>  The cure didnt work
> 
> Steps to reproduce if possible
>  Eat a roburger or that spaghetti stuff and then try and cure it with the injections of copper

**Comment by ihadtoregisterforthis** [comment]
#8568, this only adds the baguetti spaghetti to the list
