### ISSUE TITLE
Black screen after disposal climb

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8588]
(WEB REPORT BY: angryturnip REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Climbed into disposal unit, my screen went black, relogged, still black, admin teleported me out, problem fixed.
> 
> What you expected to happen
> screen wouldn't go black
> 
> What actually happened
> screen went black
> 
> Steps to reproduce if possible
> No idea

**Comment by Shadowmech88** [comment]
You were probably nullspaced somehow.

**Comment by Ephx1** [comment]
Nullspaced from disposal riding, amazing

**Comment by 9600bauds** [comment]
Probably caused by the nullspace disposals bug that has since been fixed, not enough info otherwise
