### ISSUE TITLE
Replace Goonecode toy in the Goonecode containment with 400 space credits

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8589]
Alternatively, change it to 1 BTC :^)

**Comment by ghost** [comment]
:+1:

**Comment by Exxion** [comment]
But then how will we get our wishes from the gods?

**Comment by 9600bauds** [comment]
The gods really want one bitcoin

**Comment by Exxion** [comment]
MINERS

Wait that pun wasn't even intentional

**Comment by SonixApache** [comment]
:+1:

actually can we use this as an excuse to put tcomms back on the sat?

**Comment by AutismSpider** [comment]
@SonixApache What would you turn the station Tcomms into then? Back into the old robot lab?

**Comment by SonixApache** [comment]
Tcomms to the sat
Mechanics to Tcomms
Janitor back to mechanics

**Comment by AutismSpider** [comment]
Lot of room though could move the pod bay in there to Tcomms not that far form space

**Comment by Shadowmech88** [comment]
In order to have it still be a recognizable and unique item, I suggest making a child of credit called dollar, and have 400 dollars in the containment instead.
That way people can still use the stack to pray for things, and it's easily recognizable as a unique item instead of just 400 basic credits.

**Comment by Exxion** [comment]
FOUR HUNDRED WISHES

**Comment by Shadowmech88** [comment]
Also, the Goonecode's display case should be moved into the bar, or into that little sitting area in Arrivals.

**Comment by SonixApache** [comment]
now is the time to add a new plaque

**Comment by clusterfack** [comment]
Sorry my dentists tells me to avoid gathering plaque

**Comment by Exxion** [comment]
*sigh

**Comment by mrpain666** [comment]
Replace it with a rare 2016 mint pomfcoin instead. We should still have a nice, rare, sometimes wish granting HARD MODE item to get out of there.

**Comment by mrpain666** [comment]
Oh and add a plaque saying that the goon code was pilfered on March 1, 25xx date or whatever.

**Comment by BestName** [comment]
> Tcomms to the sat
> Mechanics to Tcomms
> Janitor back to mechanics

This tbh. The mechanics office is too cramped and there is no reason to have custodials connect to the mailing room.

**Comment by ihadtoregisterforthis** [comment]
But it's a nice feature, I once sent a cleaner grenade to robotics because the roboticist there was living on the filth.

In any case, what would occupy the spot of mechanics?  And what about all the other maps?

**Comment by gbasood** [comment]
What's something we could make fun of goons for having
Solarium?

**Comment by AutismSpider** [comment]
keep the custodial close to the mailing room had fun mailing wet floor bombs as antag.

@ihadtoregisterforthis could turn it into back up room for stuff

**Comment by Imagebard** [comment]
Better idea.
Put a Coin in the satellite.
A bitcoin.

Name = "Bitcoin"
Description = "Comes with the text "Please don't rob our satellite" on the back. You should Tumble this bitcoin just to get on their nerves."
Bonus: You can now use the coin for a vending machine prize if no admins are online. Perfect.

**Comment by Blithering** [comment]
I like the Pomfcoin idea, as well as the plaque commemorating the goonecode's liberation

**Comment by gbasood** [comment]
Bitcoin or pomfcoin are both good :+1:

**Comment by CptWad** [comment]
pomfcoin is good. Theres a pomf toy already at the containment may as well make it better

**Comment by ihadtoregisterforthis** [comment]
This is my solution. Instead of the satellite being there so nobody gets it it would be so nothing gets out. Sacrificing it gives you bad effects.
Or maybe as a fancy emag to destroy kitchen appliances.
![goofcode 160px](https://cloud.githubusercontent.com/assets/13305885/13479472/def8bacc-e0b5-11e5-87a5-bcea9447f347.png)

**Comment by Iamgoofball** [comment]
:+1:

gooncode release made me obsolete

will code for scraps

**Comment by 9600bauds** [comment]
Yes we absolutely need this

**Comment by 9600bauds** [comment]
![goofball](https://cloud.githubusercontent.com/assets/6526157/13482740/8caf8170-e0cd-11e5-8dd7-545be1298a74.jpg)

**Comment by ghost** [comment]
:-1: to goofcode It'd be okay if someone used it on kitchen appliances, but imagine using the goofcode on chemistry machines.

**Comment by 9600bauds** [comment]
It just swaps the reagent names

**Comment by Iamgoofball** [comment]
post more goofpics, i'll add them to my desktop background rotation

**Comment by AutismSpider** [comment]
@DrCelt When use on chemistry machines it swap the reagent name list on food vends turn it into dans stuff

**Comment by AutismSpider** [comment]
When use on butt bots they spam ASS BLAST USA when some one touches it
