### ISSUE TITLE
The issue where we discuss goonecode leak/revision and what we may or may not steal/borrow

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#8592]
That way we don't have to fish thread or IRC to find out who wants what.
# General info
### With the official release out we can do whatever now, godspeed
Since I am the faggot that went first, I think the whole /obj/critter thing is actually great and we should totally steal its idea and a few of the mobs contained within, specifically all them goddamn parrots.
Maybe the boogie bot too

**Comment by Exxion** [comment]
Our spacepod code is awful and bad
I mean Goon's probably is too but at least it's COOL and awful and bad
Maybe we should port that
~~And by "we" I mean "I" because I'm the only one who actually bothers working on spacepod code anymore~~

Also, if their lighting isn't too laggy, we should port that

Goonchem (or at least some aspects of it) would be cool to port, but probably out of the question

I hear they have some good gamemodes, too

**Comment by mrpain666** [comment]
GAME MODES WHEN?
COMPUTER SYSTEM WHEN?

Uhh....I cant think of anything else, other than the maps I guess, but those probably wouldnt work without a 1:1 port.

**Comment by AutismSpider** [comment]
@Exxion can fit like 4 people in goon pods weapons and shit work to etc.

**Comment by Exxion** [comment]
Our weapons do work now, but the code is horrifically fragile and I bet the next person to touch it will break it again
Which is why porting Goon's pods would be a good idea

**Comment by gbasood** [comment]
Goonchem is cool and actually involves more than just fixing everyone's minor injuries 24 fucking 7 but I don't think it'll ever fit our playerbase.

**Comment by Shadowmech88** [comment]
They've got virtual-reality sleepers where you can race on a complete Mario Kart track with a rainbow road and everything.

**Comment by IratePirate** [comment]
Airbridges, pods, job features, traitor items, pods, Blob and other antags.

What about the sprites? Perspective change and all that?

**Comment by PJB3005** [comment]
Everything?

**Comment by gbasood** [comment]
>airbridges

Takes me back to original SS13 where you had to use an airbridge to get into the engine.

**Comment by ihadtoregisterforthis** [comment]
I for one say we leave the terrible perspective objects and walls out of this codebase.
Also their endemic memes.

**Comment by Shadowmech88** [comment]
They've got an admin button that causes every single atom to spin in place.

**Comment by gbasood** [comment]
Also I just want to throw this in:

# DO NOT RIP ART ASSETS FROM GOON
Everything else you will have to talk to the contributors about, but art assets are an absolutely no-no

**Comment by Ephx1** [comment]
The Saxophone, the one and only good Goon feature.

**Comment by IratePirate** [comment]
Half their sounds are straight from sources like Half Life 2, stock sounds and as you say, youtube videos.

**Comment by Ephx1** [comment]
Well then, those seem like free game then, saxophone here I come.

**Comment by Zth--** [comment]
I like the train mulebot, I think I'm gonna work on it

**Comment by Imagebard** [comment]
@d3athrow Would be nice if you dropped by.

**Comment by gbasood** [comment]
@Ephx1 If you have proof that they do not own the sounds, be ready to present that proof when you make a PR with those files. Alternatively, be ready to strip those files out.

**Comment by Ephx1** [comment]
https://youtu.be/gy1B3agGNxw?t=43s
proofs

**Comment by CptWad** [comment]
@gbasood there are people who don't know why we should not rip the art assets/maps/sounds, how bout a quick reasoning for those that dont know

**Comment by gbasood** [comment]
Here's what I'll put down:
# REASONS NOT TO STEAL SHIT
 - **We do not have license to any of the leaked code or content.** Period. That's on shaky legal ground, but it's best not to mess with that where possible. Besides, we don't want to copy+paste goon features, we want to take the concepts and make them our own.
 - Art assets, specifically, were contributed to Goon under their own specific license, most of them custom-made for Goon under the understanding that they wouldn't be used elsewhere. So for legal reasons, don't use those.
 - For non-legal reasons, we don't want to use art from goon because we don't want to look like goon and stealing art from their haphazardly will end up with things looking severely out of place. More so than they already do.
 - Sound files. The sources for these are from so many different places that it's best to source audio files yourself, so at least you know who you're going to piss off.

For the most part, the legal reasons aren't a huge part of why we won't take whatever we don't take. I'm against taking most of anything from the leak, code or otherwise, because it'll just end up being slapped on top of our shit and feeling incredibly out of place and we already have enough of that as is. That part's just my opinion, it's not the opinion of everyone else, most likely.

**Comment by PJB3005** [comment]
IMO no assets, for code it must be back end stuff.

**Comment by gbasood** [comment]
@PJB3005 Specifically you mean things like performance optimizations, or for example how they implemented lighting?

**Comment by d3athrow** [comment]
Tits

**Comment by PJB3005** [comment]
Anything the players don't interact with directly. 

Taking ideas is fine though

**Comment by CptWad** [comment]
ideas like obj/mob/ which would let us have less sloppy pet code

**Comment by gbasood** [comment]
@CptWad Not necessarily
We'd have to re-implement how possessing pets would work too which is a pain, and not necessarily going to give us any benefits for our efforts

**Comment by Blithering** [comment]
We're all forgetting the big question here. What do we put on the satellite to trade for wishes now?

**Comment by gbasood** [comment]
@Blithering #8589

**Comment by Imagebard** [comment]
@gbasood Better idea.
Put a Coin in the satellite.
A bitcoin.

Name = "Bitcoin"
Description = "Comes with the text "Please don't rob our satellite" on the back. You should Tumble this bitcoin just to get on their nerves."
Bonus: You can now use the coin for a vending machine prize if no admins are online. Perfect.

**Comment by gbasood** [comment]
@Imagebard discuss it in that issue not this one that's the entire reason I referenced it

**Comment by Imagebard** [comment]
Yes, I know what tumbling is.
No, capitalizing something doesn't mean the person doesn't know what he's talking about.

**Comment by gbasood** [comment]
Hey man, how am I supposed to know if you ACTUALLY know what it laundering a bitcoin is called or if you're referencing Tumblr in some way
Just because I'm an asshole doesn't mean I'm trying to attack your character at every turn geez

**Comment by clusterfack** [comment]
You guys worry too much. Anyway we've HAD the art assets eternally, but we never took them out of respect.

None of the code I've seen from their codebase is even up to our coding standards, and it's radically different enough that we would need to do some major adaptations to anything to port it. Thus, if anyone wants to port something from goonecode I have no real issue when you draw **inspiration** let's call it, from the released version.

**Comment by Zth--** [comment]
So what about lighting? Does this fasten the process?

**Comment by Glloyd** [comment]
In regards to licensing, on goonstation itself it says Goonstation is CC BY NC SA, so take that as you will. I think in that regards art assets are compatible with the licensing of your art assets, but the legality of how the whole thing was obtained leaves a question mark over all of that.

**Comment by CptWad** [comment]
From what cluster found lighting is what lags up most of goon.

**Comment by PJB3005** [comment]
Nah lighting isn't big of a performance issue on Goon.

**Comment by Iamgoofball** [comment]
Naba is the guy who did the VOX soundfiles.

I recall him stating that using the soundfiles was okay with him, but you should probably bug him about it first.

**Comment by Zth--** [comment]
Goon had tons of lag before the new lighting

**Comment by CptWad** [comment]
https://www.reddit.com/r/SS13/comments/48oiq7/statement_from_goonstation_team/

New revision _soon_ :tm:

**Comment by Ephx1** [comment]
DAMAGE CONT- oh, dammit

**Comment by Imagebard** [comment]
https://github.com/GoonstationOfficial/r35cd644

Are we allowed to do what we want with this code? They say that its better optimized(Sure thing lad)

**Comment by Imagebard** [comment]
Actually lemme quote @kyronkiranov because now that I think about it this really is fishy.

>kyronkiranov commented 3 minutes ago
The Goon Community once released an Haven&Hearth client that was actually a keylogger.
They managed to get many logins from legit players and used that information to "win" at the game.
How do we know this release does not have any malicious code like that? Why should anyone use this release instead of the leak? Especially since there seems to be very small differences...

**Comment by CptWad** [comment]
We should probably test to make sure it does not brick your computer, or that it does not have UI issues.
I mean if its really the same as the leak then sure, I will wait a bit till I update the OP with the new link

**Comment by Imagebard** [comment]
We should probably test it with something like a Sandbox Program so it doesn't do anything funny.

Also, here's a link to SomethingAwful SS13 thread.
SomethingAwful occasionally lifts it paywall, so consider checking it every now and then. Maybe they'll let slip up something they really don't want us to hear. 
http://forums.somethingawful.com/showthread.php?threadid=3551842

**Comment by CptWad** [comment]
Well there has to be one of us that has an account. hell I pay for byond subscription im sure someone bought access to an ancient worthless forum

**Comment by Iamgoofball** [comment]
jesus christ you guys are being turbo autists over this

**Comment by CptWad** [comment]
![soldieryes](https://cloud.githubusercontent.com/assets/3959840/13481692/a8905396-e09c-11e5-8440-d84a9879ec2c.jpg)

**Comment by d3athrow** [comment]
you should have been running the leaked project in a sandbox as well

**Comment by Iamgoofball** [comment]
yeah, if anything that was the one more likely to fuck you up

**Comment by Shadowmech88** [comment]
What's the legality on making a *completely new* sprite that *just happens* to be similar to one of Goon's sprites, but isn't an exact copy?

**Comment by clusterfack** [comment]
Anything in the current officially released version should be fine for our codebase so go wild?

**Comment by Shadowmech88** [comment]
@clusterfack 
*Anything*, or any code?

**Comment by clusterfack** [comment]
Anything

**Comment by ASmugCat** [comment]
You can take the sprites too. They can't do shit besides throw a shitfit and cause drama over it.

**Comment by CptWad** [comment]
Art assets too?
I get my parrots?

**Comment by clusterfack** [comment]
From what I can tell, yes

**Comment by IratePirate** [comment]
At least Goon aren't being dicks about this. This should be a good thing really, like the 2010 release that led to SS13 flowering and transforming into what is today.

**Comment by FudgePucker** [comment]
Welp they deleted it and also closed the original leak.

**Comment by Exxion** [comment]
Ruh roh

**Comment by Ephx1** [comment]
Bit late for that, unless it really was a ruse all along.

**Comment by Exxion** [comment]
https://github.com/GoonRelease/GoonRelease

**Comment by FudgePucker** [comment]
That one is shut down by DMCA takedown.

**Comment by Iamgoofball** [comment]
They're taking it down so they can get the consent of all goon coders and do a PROPER Open source release, don't worry

the leak got DMCA'd due to being a literal leak and also illegal

the official got taken down for now so they can put up an actual official release without broken assets for things like the chat box and changelog and shit

**Comment by FudgePucker** [comment]
So there is going to be an official goon open source release? Getting consent of ALL goon coders will take a while wouldn't it? Not all of them are active anymore. Are they just going to get consent of active coders and the ones they know are alive?
Nice.

Also I know lighting has been discussed already, but I really like goons multicolored light bulbs.
Also, their space drug rainbow screen is better than ours.

**Comment by Iamgoofball** [comment]
Yeah, Volundr said that if they cant get ahold of a coder/the coder denies, they'll just scrub their code and recode it if it's important.

I kept backups of the original official release and the original leak so things that get scrubbed can be re-added/recoded.

**Comment by CptWad** [comment]
A lot of us have it backed up
I know I do

**Comment by Jeroen52** [comment]
I have a copy of the leak, I was too late to the party for the "official"
release.

2016-03-03 19:07 GMT+01:00 CptWad <notifications@github.com>:

**Comment by PJB3005** [comment]
Yup I have it all backed up too.

**Comment by DrCelt** [comment]
To be honest anyone who didn't think "yeah I should back this up just in case" when they saw the goonecode was released is an eejit

**Comment by IratePirate** [comment]
So is there any way to open up their maps using /vg/'s version of Dream Maker without it failing to recognise? I'd like to begin the process of porting some maps.

**Comment by gbasood** [comment]
Goons are actually creating an official release soon.

**Comment by IratePirate** [comment]
Yeah but I don't think that makes a difference when it comes to compatibility.

**Comment by gbasood** [comment]
Nope
But if they used custom map tools they might release those.

**Comment by IratePirate** [comment]
![cogmap](https://cloud.githubusercontent.com/assets/6830971/13524348/9807a3b0-e1f2-11e5-9a6b-cca2bdd771fe.png)

As you can see it needs some fixing up, didn't expect anyone to ever see it in the map editor.

The map tools seem to be in the release.

>no porting maps

And why's that? They're releasing all of this anyway, and I highly doubt Dr Cogwerks is going to try and hoard the maps which are going to be changed up massively anyway (since they are built for Goon's playstyle). By the time this gets done this entire issue would have blown over.

**Comment by clusterfack** [comment]
>no porting maps

Fuck off with that, maps have the least license protection of literally anything in a repository

**Comment by CptWad** [comment]
Yeah but in all honesty fuck trying to add cogwerks maps, they are build for goonstation and would require shittons of effort just to make them compatible.
Really just about all of us would care to put the effort into adding donustation but thats about it

**Comment by clusterfack** [comment]
Donut station best map

**Comment by IratePirate** [comment]
Problem is Donut doesn't even open up in _their_ editor let alone ours.

**Comment by CptWad** [comment]
thats why I said we'd be willing to put the effort into it
hell I mapped a whole map from scratch before, all I needs a refrence, reason not to procrastinate and the occasional help here and there and I could do it

**Comment by DrCelt** [comment]
I'd far prefer their ship map than donut honestly

**Comment by clusterfack** [comment]
Stargate universe knockoff < donut

**Comment by CptWad** [comment]
^^^^^
:+1:

**Comment by Intigracy** [comment]
Can't believe I forgot about this.

![pomfcodeheist](https://cloud.githubusercontent.com/assets/4043940/14028554/6ebc2a8a-f1ba-11e5-875c-3219752d78f3.png)

**Comment by Intigracy** [comment]
Also close this now, they released an open source revision so we can take what we want.

**Comment by Shadowmech88** [comment]
We could still leave this open for discussing what we want to take from the open source revision

**Comment by clusterfack** [comment]
Nah that sounds like a different thing

**Comment by ihadtoregisterforthis** [comment]
No, that's exactly what this discussion is about

**Comment by Intigracy** [comment]
We can take EVERYTHING from the _open source revision_. This was about what CAN we take from the _leak_.

If you want something specific taken, make a feature request.
