### ISSUE TITLE
Chem Dispenser upgrades do not increase limit past 100

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#8594]
Revision: 255da17316da9aa055a16160c84e1aa831873695 

> General description of the issue

Although the chem dispenser in chemistry start with base tier 1 parts, they have an energy capacity of 100. When making a chem dispenser from scratch, however, you will only reach an energy capacity of 100 if you use tier 3 parts. Tier 2 parts will give the chem dispenser an energy capacity of 75. A brand new chem dispenser with tier 1 parts will only give you a max charge of 50 energy.

> What you expected to happen

I expected to reach a higher capacity than 100. I believe the old capacity with tier 2 parts was 125 and the capacity with tier 3 parts was 150.

> What actually happened

The chem dispensers either had an energy capacity worse than or equal to the roundstart dispensers. The picture below shows different dispensers. From left to right: A midround dispenser with tier 3 parts, a midround dispenser with tier 2 parts, a roundstart dispenser with tier 1 parts, a midround dispenser with tier 1 parts.
![chem dispenser upgrading bug full](https://cloud.githubusercontent.com/assets/5942183/13461054/79c68c0a-e07f-11e5-9056-fa7927f3dba9.png)
Upgrading a roundstart dispenser with all tier 3 parts except manipulators (the part responsible for max energy) did not change the capacity of the dispenser.
Spawning a chem dispenser through admin tools sets its max energy to 50.

> Steps to reproduce if possible

Create a dispenser through normal means (frame, wires, board, parts) and compare to the dispensers in chemistry by hitting both with a rapid parts exchanger. To circumvent the wait, search for the dispensers' max_energy variable in VV.

**Comment by gbasood** [comment]
I don't know if this was ever intended to occur or not so I'm gonna pre-emptively tag this Feature Request.

**Comment by CptWad** [comment]
its supposed to occur. not a feature request but feature loss

**Comment by Kammerjunk** [comment]
Roundstart chem dispensers being as good as tier 3 chem dispensers (disregarding charge speed, possibly) is intended?

**Comment by CptWad** [comment]
rounstart chem dispensers being better than they should is wizardry I always avoid
