### ISSUE TITLE
Liberty coat makes clothes under it invisible

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8595]
(WEB REPORT BY: cowboybuttsdrivemenuts REMOTE: 158.69.55.2:7777)
Revision: 255da17316da9aa055a16160c84e1aa831873695 

> As in the title, putting on the liberty coat into your exosuit slot overrides your jumpsuit and makes it appear that you're in your undies
> 
> I expected to be able to put on a liberty coat and wear other clothes under it
> 
> What actually happened
> The clothes are invisible
> 
> Steps to reproduce if possible
> Put on a liberty coat from the autodrobe.

**Comment by Exxion** [comment]
#8497 
I guess it's not _technically_ a duplicate but it almost is
