### ISSUE TITLE
MySQL Databases.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8596]
I'm filled dbconfig.txt with my server details, uncommented ENABLE_STAT_TRACKING and SQL_ENABLED, and commented BAN_LEGACY_SYSTEM. Server says, that conenction to both (tgstation and feedback) databases established, but temporary jobbans doesn't working, it saves only till reboot. And when i entering the server it says: "ADMIN LOG: fireflashie/(FireFlashie) is a relatively new player, may consider watching them. AGE =   First seen = "
Migration controller created tables.
Sorry for bad English.

**Comment by gbasood** [comment]
Some of the SQL things going on use BYOND's built-in SQLite functions, so it might be that

**Comment by ghost** [comment]
SQLite database seems working, but not MySQL.

**Comment by iwillkillmyself** [comment]
mysql is working fine, this is happening because the SQL schema is outdated, erro_player is missing an "accountjoined" field, maybe other stuff too

@d3athrow 
@clusterfack

**Comment by StarSmasher44** [comment]
SQL seems to be nonfunctional right now, it is impossible to load in the .sql file into the database as it is currently uploaded here.
`
An exception occurred while executing a Transact-SQL statement or batch.
Must declare the scalar variable "@@UNIQUE_CHECKS".
Must declare the scalar variable "@@FOREIGN_KEY_CHECKS".
Must declare the scalar variable "@@SQL_MODE".
'CREATE SCHEMA' must be the first statement in a query batch.
Incorrect syntax near '`'.
'CREATE SCHEMA' must be the first statement in a query batch.
Incorrect syntax near '`'.
Incorrect syntax near '`'.
Incorrect syntax near '`'.
Incorrect syntax near '`'.
Incorrect syntax near '`'.
Incorrect syntax near '`'.
`

**Comment by PJB3005** [comment]
I think that with migrations you don't even need to load the `.sql` file directly anymore, as the game should detect that the database is not up to date and then update it.

Note that that's purely theoretical and I need to test it, and I have no idea how migrations works.

**Comment by StarSmasher44** [comment]
Had no idea, I came as far as to try and load the sql, hat failed. Manually tried to fix the scripts but then I had some connection issues so I stopped right there. But if you can confirm if they automatically work then  that could have been my entire problem haha

**Comment by PJB3005** [comment]
My attempts to get SQL to connect at all have basically resulted in this:

![](http://i.imgur.com/uun7JEk.png)

Good job BYOND I'm proud of you.

**Comment by PJB3005** [comment]
Okay so, the MySQL database does automatically populate with migrations, the problem is that @clusterfack broke the public MySQL code entirely in #7891, but that never hit the main server due to a secret repo conflict.
