### ISSUE TITLE
Borer eggs will not reset if set in plasma with no ghosts

### ISSUE THREAD

**Issue by Ephx1** [d3athrow/vgstation13#8597]
Basically, if you set a borer egg in plasma, then turn on plasma, if there are no ghosts or willing ghosts the egg will become inert. As in you can't use it again.

So this means either praying for admins or crossing your fingers for a borer event if the egg is screwed.

**Comment by AI-Is-Rogue** [comment]
Wasn't there a feature added a while back that allows ghosts to click on borers to assume control?
Edit:I'm a blind idiot

**Comment by Ephx1** [comment]
Well yes, that's why I mentioned the borer event. However the eggs don't hatch if no one signed up, nor can you just click on the egg to do so.

**Comment by AI-Is-Rogue** [comment]
Yeah, I thought they hatched regardless if there were any willing ghosts or not, and I misread it.

**Comment by DarkDibblez** [comment]
Actually because I love borers, I'm gonna implement this shit @gbasood is it okay if I take this off your hands?

**Comment by AI-Is-Rogue** [comment]
I'm pretty sure this was already fixed by #11829.

**Comment by DarkDibblez** [comment]
Did some testing, and yep it works fine. This can be closed.

**Comment by gbasood** [comment]
>take this off my hands
@DarkDibblez I realize you already did this and we talk on discord and such but
litearlly my only code project right now is the stats viewer
go crazy
