### ISSUE TITLE
Typo on Grey space helmet

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8599]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 25e4b508298181d88282a40acf22e88f603125b5
> 
> General description of the issue
> Celt told me to make a bug report for a spelling mistake REE
> 
> What you expected to happen
> That's a grey pressure helmet. It is a normal-sized item.
> A strange globe-like structure. Despite looking like a decent glare would break it, it is surprisingly durable. Emough thinking room for a Grey.
> 
> What actually happened
> That's a grey pressure helmet. It is a normal-sized item.
> A strange globe-like structure. Despite looking like a decent glare would break it, it is surprisingly durable. ENOUGH thinking room for a Grey.
> 
> Steps to reproduce if possible
> shift click the helmet you dunce

**Comment by ghost** [comment]
aw shit
