### ISSUE TITLE
No progress bar on cablecuffs

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8600]
Maybe regular cuffs too?

**Comment by jernaumorat** [comment]
Are there any other instances you can think of where there should be a progress bar, and isn't?

**Comment by uazuaz** [comment]
@Vermilingua 
does CPR take time to be performed? if this is the case, the bar is missing for that too.

**Comment by 9600bauds** [comment]
Disposals tubing but I've made a separate issue on that

**Comment by jernaumorat** [comment]
I tried to fix this, but `do_after()` (which @clusterfack told me _should_ do the trick) has no effect. Is there some listing of actions with progress bars, because the definition for `do_after()` has nothing, and replacing `spawn(30)` (the current pause on cuffs) with the `do_after()` equivalent changes absolutely nada.

**Comment by ghost** [comment]
@Vermilingua Did you set the do_after correctly? I think you need a reference to the mob in the parametres to make the progress bar appear

**Comment by jernaumorat** [comment]
@DrCelt I did. I replaced the line `spawn(30)` with `if(do_after(user, C, 30))` where `user` was the param name of the holder and `C` is the target. There are two other parameters listed in `do_after()`, but they seemed mostly irrelevant, and unused in most cases of `do_after()`. This is in `code/game/objects/weapons/handcuffs.dm:30` BTW.

**Comment by ghost** [comment]
Huh. *shrug. How do normal cuffs do it?

**Comment by jernaumorat** [comment]
They don't. Normal and cablecuffs use the same action code. This affects both, and neither display a progress bar with the new _or_ old code.

**Comment by 9600bauds** [comment]
Stripping people is another thing that doesn't get a progress bar

**Comment by Intigracy** [comment]
It's because they're mobs silly.

Will fix, easy af.

**Comment by Intigracy** [comment]
@Vermilingua I dunno what you did wrong but do_after works perfectly fine for me.

Are you sure you recompiled after saving the code?

Are you sure you saved the code before recompiling?
