### ISSUE TITLE
Borer eggs from existing borers are broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8603]
(WEB REPORT BY: redun REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Borer lays egg, egg doesn't work.
> 
> What you expected to happen
> Egg hatches after a time spent in plasma.
> 
> What actually happened
> Borer eggs never hatch.
> 
> Steps to reproduce if possible
> I dunno what else to say, they simply don't work in the right conditions.

**Comment by Shadowmech88** [comment]
Hatching requires the presence of a ghost that wants to be a borer.
Maybe you were just unlucky.

**Comment by Brolaire** [comment]
it worked last round for me just fine

**Comment by Shadowmech88** [comment]
I'm fairly confident that this can be closed.
