### ISSUE TITLE
Pillbottle colo(u)red labels need to be more visible

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8604]
How they are right now:
![mspaint_2016-03-02_23-25-29](https://cloud.githubusercontent.com/assets/6526157/13482956/3394bfcc-e0cf-11e5-8263-e4903fd1c3f8.png)

How they should be (note I am bad spriteperson):
![mspaint_2016-03-02_23-28-18](https://cloud.githubusercontent.com/assets/6526157/13482982/4168d1d8-e0cf-11e5-8aab-e0cd1b251c5a.png)

Or alternatively, color the whole bottle:
![mspaint_2016-03-02_23-25-292](https://cloud.githubusercontent.com/assets/6526157/13482993/4d1cd04c-e0cf-11e5-8da4-d9176135755b.png)

**Comment by ihadtoregisterforthis** [comment]
I'd go for the option A, with different colo"u”rs, or a better hue for the inscription of the one in use.

**Comment by 9600bauds** [comment]
You can choose the colo'u'r, I picked purple as an example

**Comment by ghost** [comment]
Iunno I like the full bottle colour thing. I disagree they're not visible enough though.

**Comment by 9600bauds** [comment]
When you have three 10x6 icons of a pillbottle in your medical belt and you need to squint a little you're thinking you would probably appreciate a little bigger label

**Comment by ghost** [comment]
Ehhh maybe. I got on fine with it, but I see your point. How about also making them alt click or maybe attackself to set their colour too?

**Comment by 9600bauds** [comment]
Even better, rightclick is cancer
