### ISSUE TITLE
Kicks ridiculously robust at destroying windows if you kick an item towards them

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8605]
Kick a glass shard or metal rod towards a reinforced window and it takes literally 3 kicks to bring it down. Faster than even using a toolbox. Shit's broke yo

On a semi-related note, glass shards are now pretty quick at destroying shocked grilles. I don't remember them working so fast.

**Comment by Exxion** [comment]
Glass shards can destroy grilles? Since when?

**Comment by 9600bauds** [comment]
How do you think people break out of perma?

**Comment by Exxion** [comment]
Oh, sorry, I thought you meant thrown shards

**Comment by 9600bauds** [comment]
http://a.pomf.cat/rlvmlz.webm
how to get through a shocked grille

**Comment by Exxion** [comment]
Also, talonkicking means it is literally impossible to jail vox in any room with a window

**Comment by 9600bauds** [comment]
What do you mean? Humans can break out of any room with a window just fine

**Comment by Exxion** [comment]
Vox can do it with no items, though
They can kick down windows with no shoes on

**Comment by Zth--** [comment]
Attacking with a shard and without protection should cut your hand

**Comment by unid15** [comment]
talons were a mistake

btw throwing a shard at a window deals the same damage as a kick

**Comment by 9600bauds** [comment]
Definitely not from my testing
