### ISSUE TITLE
Goon perspective?

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8606]
It's entirely feasible we can port it. It's one of the few really worth porting hings and can be done with relative ease.

**Comment by Ephx1** [comment]
What is this "PERSPECTIVE" you speak of?

**Comment by ghost** [comment]
Their walls and doors are isometric. Our walls and doors are bastard children of isometric and topdown

**Comment by Ephx1** [comment]
Oh right, I'm fairly certain a good chunk of people don't like it from what I've seen.

**Comment by ghost** [comment]
Yeah they're nerds and also why I didn't bother to port it immediately and made this issue to gage public opinion.

**Comment by 9600bauds** [comment]
:-1: from me, I think it looks terrible to have half of the things in the game isometric and the other half not. Many of Goon's isometric sprites also look awful (see: boxes). Overall even the walls look bad to me and I don't see the appeal

**Comment by ghost** [comment]
@9600bauds But that's the case ANYWAY. And at least this way we are going to have SOME movement towards one or the other.

**Comment by ihadtoregisterforthis** [comment]
:-1:
Also it's called cabinet oblique projection, not just a deformed isometric.

**Comment by Kitfox88** [comment]
i like the current sprites and mechanics way more than goonstation's and i say that as someone who has paid 10 bucks to be part of the goony goon club

**Comment by ghost** [comment]
Mechanics are better here but their wall and door sprites are better than ours dang it we can't always be adverse to change

**Comment by 9600bauds** [comment]
Your error here is thinking that the only reason someone wouldn't want them is because they are adverse to change

**Comment by Exxion** [comment]
Goon walls look ultradumb

**Comment by ghost** [comment]
Pff you guys are nerds it's the only good thing about goon other than the lighting

**Comment by ihadtoregisterforthis** [comment]
Goon doors look extra terrible without some strange overlay.

**Comment by 9600bauds** [comment]
Someone made a render of them and in order to make sense from their perspective, the walls need to be just over waist high

**Comment by Exxion** [comment]
Horizontal Goon walls look fine
Vertical Goon walls are fucking trapezoidal

**Comment by ghost** [comment]
Vertical goon walls look no worse than our own walls, and their horizontal walls are far better

**Comment by Exxion** [comment]
I'll agree that their horizontal walls are better but I do not agree that their vertical walls are no worse

**Comment by ghost** [comment]
@Exxion any idea how we could fix that, then?

**Comment by Exxion** [comment]
Nope

**Comment by ghost** [comment]
We could have say the left side be more prominent, like how horizontals are, except sideways?

**Comment by ASmugCat** [comment]
I would love to experiment with this. Like others said here it would look pretty bad if only the walls look oblique and the rest looks like it is right now...but I guess we could change the walls/doors/lockers/computers and a few other things so they all fit. 

It would take quite a bit to resprite most things and find the worst offenders that need change, but I'm willing to help spriting this experiment if it becomes a thing. Since players love their comfy holes and other autism projects I don't see why a big majority would be opposed, but I guess it all depends on what the end result looks like.

Honestly a change of aesthetics wouldn't sit bad to our code and those grey stripes that we pass for walls look like horseshit. However I can see that the mass change to the overall aesthetic of the server may be too much for some spergs/players so yeah, once we have a prewview of sorts I'd suggest we put it on display for feedback/vote/insults, etc.

**Comment by Zth--** [comment]
I'd like to try, but in reality we have almost no spriters. It would take a loong time to finish everything at such a slow progress

**Comment by IratePirate** [comment]
It could work, some of the sprites are a bit crappy and need improving, e.g. the toolboxes which are far too short. Most of the others I like though, I think it works better than the odd perspective sprites we've had up until now. There was a reason they changed them after all.

Obviously there'll be conservative reactionaries as there always are on this server, but eventually people always come around, e.g. map changes.

**Comment by PJB3005** [comment]
Seriously I love goon's walls :+1:

**Comment by IratePirate** [comment]
Goons have resprited for the perspective effect the following items

> computers
> walls
> airlocks
> pod doors/blast doors
> boxes
> chairs
> toolboxes
> crates
> lockers
> wall lockers
> fuel/water tanks
> tables
> filing cabinets
> various machines like TVs, chem dispensers etc.
> vending machines
> surgery equipment
> sinks, baths, toilets etc.
> rechargers
> sleepers
> kitchen equipment
> pressure tanks
> morgue
> water coolers
> beds
> arcade machines
> probably more

**Comment by Iamgoofball** [comment]
pretty much everything on goon got a perspective shift

**Comment by Intigracy** [comment]
gross
