### ISSUE TITLE
[Deff] Literally fucking everywhere: Plastic flap B&E

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8611]
There's a shitton of places where you can just unwrench plastic flaps to get in. Pretty much in every single place where there are plastic flaps.

**Comment by Duny-** [comment]
Will take a look at that

**Comment by clusterfack** [comment]
Change it to a welder deconstruction step problem solved

**Comment by Probe1** [comment]
fix the retarded plastic economy comic and kurfurst left us with and fix the real problem.

**Comment by 9600bauds** [comment]
The problem is flaps being deconstructable at all though, not the plastic economy

**Comment by Probe1** [comment]
I'm not saying windoors shouldn't be added but these things wouldn't get scavenged every round if plastic was a more viable resource.  Plastic flaps easily beat relying on possibly non existent botanists who may not be willing to grow you any, plus the 10 minute lag before you get it.

So we have a way to get resources that's way better than the intended way, and they also just happen to be the linchpin in keeping a department secure from unauthorized access.

**Comment by 9600bauds** [comment]
Probe I don't disagree with the plastic economy being fucked but plastic flaps being deconstructible AT ALL or not is the thing behind this problem, whether they're commonly deconstructed or not is not relevant
E.G. As an Assistant I broke into Atmos by deconstructing plastic flaps, these plastic flaps were still there regardless of their worth in plastic sheets. Whether someone had scavenged them or not doesn't matter since I would have broken in anyways
