### ISSUE TITLE
Odd response when trying to unbuckle someone as diona nymph

### ISSUE THREAD

**Issue by xpcybic** [d3athrow/vgstation13#8612]
While playing as a diona nymph, I accidentally buckled someone to a bed. Upon trying to unbuckle them, I apparently tried to massage them instead.
![bodymassage](https://cloud.githubusercontent.com/assets/15971146/13485756/32d1634e-e0c8-11e5-9a09-a523b34f9e9e.png)
I don't remember exactly what I did for this message to come up, and I can't reproduce it on a test server - unbuckling works properly, and clicking the buckled person does nothing.

**Comment by Zth--** [comment]
I'm 90% sure it's a message you get when you're high
