### ISSUE TITLE
Liberty Coat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8613]
(WEB REPORT BY: generalveers25 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> The Liberty Coat item is bugged. Doesn't show the jumpsuit beneath, but acts if you're wearing the coat and nothing else.
> 
> What you expected to happen
> To be wearing my fly Liberty jacket for my lame Chaplain gimmick.
> 
> What actually happened
> Public nudity. How horrible! Think of the Children!
> 
> Steps to reproduce if possible
> 1. Acquire liberty jacket
> 2. Put on liberty jacket
> 3. Marvel at invisible pants.

**Comment by Exxion** [comment]
#8595

**Comment by 9600bauds** [comment]
dupe
