### ISSUE TITLE
Toxins Tank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8614]
(WEB REPORT BY: godzillakotm REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I couldn't turn on my internals, there was an issue with my tank I belive. It said "You don't have a toxins tank." Or something to that effect even though everything looked normal.
> 
> What you expected to happen
> My internals to turn on.
> 
> What actually happened
> I died.
> 
> Steps to reproduce if possible
> Remove tank? Reposition mask?

**Comment by mrpain666** [comment]
He was a plasmaman when this occurred, and this bug appears to make the race unplayable now as they are doomed to die due to faulty internals.

**Comment by ghost** [comment]
@gbasood SOOOOOOOODDDDDDDDDD
#8433

**Comment by PJB3005** [comment]
You should still be able to turn on internals by using the tank's UI, but it's a bit of a nuisance.

**Comment by gbasood** [comment]
I literally never changed this
and no part of the deus ex code touched this
so I have no idea how this is my fault

(and if it is I don't know what part of the code checks this so I can't fix it)
