### ISSUE TITLE
Allow vines to drop fruit.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8615]
The reason I liked old vines so much is they dropped the fruit on the floor when they grew. Now you have to click the vines, which have no indication that they need to be harvested (which I have requested in another issue, and sprited) besides being thick. I would either like vines to drop fruit when it's ready like they used to in botany2 or have a more noticable harvest sprite because as of now, it's more tedious than regular harvesting besides easier mass production.

Unrelated to this, because I'd rather have the first option where vines drop the fruit on their own, here is a sprite you can use as a more noticable harvest sprite.

![vines](https://cloud.githubusercontent.com/assets/5169310/13490312/d2f3f3f6-e0f9-11e5-9411-87fdc6748104.png)

**Comment by Zth--** [comment]
I completely support this

**Comment by Exxion** [comment]
Maybe they should drop the fruit a short while after they become harvestable, so that manual harvesting gets you fruit more quickly, but you still get fruit either way

**Comment by 9600bauds** [comment]
>which have no indication that they need to be harvested (which I have requested in another issue, and sprited)
They absolutely have an indication and it's rather visible, too
>and sprited
This is not a sprite

**Comment by Killette2** [comment]
Just use mspaint2sprite, it's easy

**Comment by 9600bauds** [comment]
But they literally already have a different sprite for harvesting, and they become opaque too

**Comment by Killette2** [comment]
How? A slightly thicker cluster of vines? That's a shitty sprite, that's why in my drawing I drew fruits on it, so you can see the actual fruits.

**Comment by 9600bauds** [comment]
A very thick cluster of vines that you can't see through
I didn't sprite it, it was unused before, but c'mon. It's very visible.
The reason why I didn't give it fruits because a) it would look shitty with all fruits being little round dots b) it would look shitty if all fruits were the same color c) making the shitty little round dots different colors depending on the fruit required me to code in a color for every fucking type of seed and muck with overlays just for that shitty little round dot

**Comment by Killette2** [comment]
What if it's creeper vines instead of kudzu vines? Does it still become thick? Creeper vines are the way they are to never block vision, and if they ever do it removes their point.

**Comment by 9600bauds** [comment]
I'm not sure actually, I think it makes them medium thickness instead of always light
It's been a long ass time since I touched anything botany related

**Comment by Killette2** [comment]
I could experiment in game with creeper vines if needed eventually, but them becoming thick would just piss people off and cause the usual kudzu lynch. I just want fruit sprites, nobody will give a fuck if they're just a generic color like red and don't actually represent the fruit. Hell, xenobotany seeds fruit don't represent the plant itself at all, such as an xeno cherry tree giving you 'pumpkins?'

**Comment by Killette2** [comment]
Now that the vines have a sprite as mentioned in another issue

#7258 

What about this one?
