### ISSUE TITLE
diona gas mask equipped

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8616]
(WEB REPORT BY: ashdemai REMOTE: 158.69.55.2:7777)
When a diona equips a gas mask it goes above its head, try it yourself look how funny it is!

**Comment by ihadtoregisterforthis** [comment]
Must be a nymph, just like with every mask or there, they share the monkey height.

**Comment by Exxion** [comment]
Backpacks also appear to hang from the tips of nymphs' tails

**Comment by Kitfox88** [comment]
Hats aren't lined up with Vox heads either. :-1:

**Comment by Intigracy** [comment]
There's no easy way to fix this short of making sprites JUST for diona just like there are just for monkeys and just for vox.

The vox one I'd be willing to do but not making an entire new set just for diona, they can share with monkeys and you can enjoy your magic floating mask.

**Comment by ihadtoregisterforthis** [comment]
Different MoMMI sprites have different hat heights. Can't something like that be implemented here?

**Comment by Intigracy** [comment]
You mean different versions of mommis have different hat heights?

**Comment by ihadtoregisterforthis** [comment]
[This thing with a long link](https://github.com/d3athrow/vgstation13/blob/cf6b26de8462feb13433095cd652b24cec1e4686/code/modules/mob/living/silicon/mommi/update_icons.dm#L44-L66)

**Comment by Intigracy** [comment]
Then yeah, we can do that with dionas, we just can't move the mask left/right for the side sprites.
