### ISSUE TITLE
Passive vents shut down above 4500kpa

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8617]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 25e4b508298181d88282a40acf22e88f603125b5
> 
> General description of the issue
> Self-explanatory. Passive vents to space stop venting gas above 4500kpa. In game this can result in such things as the waste loop clogging at high pressure and other unsavory effects.

**Comment by Zth--** [comment]
This explains why I had to rework the waste line every time back when I played as an atmos 24/7

**Comment by FudgePucker** [comment]
Well fuck.
This is an issue alright.
This might be caused due to it being a child of unariy vents

**Comment by PJB3005** [comment]
They're not childs of unaries at all, IIRC.

**Comment by Imagebard** [comment]
passive vents were fucked ever since I first tried to deal with them.

**Comment by PJB3005** [comment]
I'm unable to find any code that would cause this, testing right now.

**Comment by PJB3005** [comment]
Doesn't seem like a 4500 kPa specific issue but something is definetly up.

**Comment by clusterfack** [comment]
Well for one I have no idea what this code in vent.dm is 
CHECK_DISABLED(vents)
somehow I've never seen this before.

Also they no longer mingle with turfs, they remove their air contents and add it to the turf.

**Comment by PJB3005** [comment]
The `CHECK_DISABLED` part isn't it.

For some reason the `air_contents` of the vent aren't being filled by the pipeline?

Because the `air_contents` are empty it has no air to actually move.
