### ISSUE TITLE
Cannisters can't be emptied

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8618]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 25e4b508298181d88282a40acf22e88f603125b5 
> 
> General description of the issue
> When any quantity of a foreign gas is introduced into a cannister it will forever show that cannister as having a percentage of that gas inside. The result being that say a plasma cannister that once had one molecule of oxygen will forever claim to have only 99% plasma in it. Neither venting to space nor pumping gas out of it resolve the issue.

**Comment by Exxion** [comment]
I would expect some gas to remain in no matter what when simply venting the canister, but you should be able to pump all gas out
I bet you can purify it in most cases with a portable scrubber, but that wouldn't work if both gases involved are ones the scrubbers... scrub.

Why can't you select the gases to filter on portable scrubbers like you can on actual scrubbers?

**Comment by AutismSpider** [comment]
@Exxion we have that one unused gas canisters that hold and can select what gas to out put forgot what it was call right now but it works like a pipe and can hold any gas and you can select what comes out and gos in it etc

**Comment by AutismSpider** [comment]
Magnetically Suspended Gas Storage made by PJB3005 i think.

Just a huge SMES looking thing that can hold ton of gas and can be move only admin spawn no way to build or get it.

**Comment by PJB3005** [comment]
Yup I should add a way to build the MSGS at some point. Really I just had the code lying about and it still worked so I decided to PR it.
