### ISSUE TITLE
Colourblind the vox. Pinken the Plasma. Something the Other Races.

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8621]
Functionality is 100% there - I'll wait until #8447 to add them as there's lotsa messy UI stuff that needs updated and I'd rather work with the updated stuff

This is to function as a discussion.

**Comment by ihadtoregisterforthis** [comment]
Example concept renditions pls

**Comment by TheFriggenSawbones** [comment]
will this strain my eyes

**Comment by xevonix** [comment]
do it, i double dog dare you

**Comment by Exxion** [comment]
OK alright hear me out here
1. Why?

**Comment by icantthinkofanameritenow** [comment]
So...what exactly is this issue supposed to be about anyway?

**Comment by Ephx1** [comment]
> Pinken

Purple...n? Purplify?

No wait it's just purple.
PURPLE THE PLASMA*

**Comment by Probe1** [comment]
It's for moving the discussion to a new place so the PR doesn't languish.  

I'm with Exxion.  It's a cool gimmick but it's too invasive to be a default thing.  Use it, but use it for drinks or food or chems and whatnot.

**Comment by ghost** [comment]
It's not that invasive, honestly. 
The way it would work is:
-  Default eyes: You're a normal person, and you take your race's colour vision.
-  Assisted eyes: You take normal vision, but if you're hit with an EMP you will take your race's colour vision until it wears off
- Robot eyes: Probably needs a buff of some form *shrug

**Comment by Ephx1** [comment]
I like the assisted eyes idea.
Don't know what the fuck you'd give Robot eyes to buff but not completely make better.
Unless you just flat out replace them with assisted eyes and make robot eyes research only.

**Comment by icantthinkofanameritenow** [comment]
@DrCelt 
What, is this solely for MUH IMMULSIONS? Why would other races even have different kinds of color vision, lore-wise?

> implying anyone gives a fuck about lore

**Comment by Probe1** [comment]
The Vox colorblindness image instantly repulsed me and I ended up rewriting my comment to be a little less bitchy and a little more constructive.

I wouldn't play Vox if it was in.  However I don't have much of an interest in playing Vox to begin with.  So really what I feel we need is the opinions of those that would be effected by it.  And the only way to realistically do that is to merge it and have a trial period.

The mechanical eyes idea is good.  It gives players an actual fuckin reason to use mechanical eyes.  But is it something players want, and this is how we will be presenting the game to new players that don't know about the top strats.  They'd think the game looks like shit.

**Comment by ghost** [comment]
Could even have a little light static display or the colour flickering a little in and out until the assisted eyes are fixed.

@ihadtoregisterforthis It's COOL my friend, and makes races a little more unique as well as gives a reason to use mechanical/assisted eyes
@Probe1 That's if they exclusively play vox. We can add a warning at  the same time it says "You are now running on nitrogen internals from the the nitrogen tank in your suit storage. Your species finds oxygen toxic, so you must breathe nitrogen (AKA N2) only." as well.

**Comment by AutismSpider** [comment]
The Vox one looks like shit m8 whats makes you think the plasma man one would be any better?

or are you doing this for MUH IMMULSIONS if so get back to work on that snow map and not that shit.

**Comment by Exxion** [comment]
All vox players who I have seen comment on it have disliked it, but that was unfortunately on the thread and in private chat, not on GitHub.

Also, assisted eyes already have an overlay when EMPed. Same as the one meaning you're about to pass out from pain.

**Comment by Shadowmech88** [comment]
I have no desire to play vox in the first place, but personally I didn't mind the BG-colorblindness image.

**Comment by ghost** [comment]
@Exxion Which can be changed easily

**Comment by Exxion** [comment]
I already use assisted eyes, so I guess this doesn't really affect me
But it's still dumb

**Comment by Probe1** [comment]
I think the only way to get substantial feedback from the _affected players_ is to merge 'something' into the codebase and poll them.  Like an debug verb to enable it for a round.  

That's my thought.  I don't like it, but I don't play Vox so what's my opinion worth in this?  

That, and I think it's a really cool idea but not targeting the right parts of the game.  If you had made a PR that added this as a viral symptom I'd be all over it.

**Comment by Shadowmech88** [comment]
We definitely need red-green colorblindness as a genetic disability at some point.

**Comment by Exxion** [comment]
Make a colorblindness gene

**Comment by Shadowmech88** [comment]
Would it be possible for the gene to apply a random form of colorblindness each time it's activated?

**Comment by Probe1** [comment]
If it was a gene, and it also had a significant but not 100% chance to be present for a Vox at roundstart similar to bartender/detectives sobriety, I'd be down.  That sorta merges the two ideas.  You MIGHT start with colorblindness as a Vox, and it also exists as a defect that any player can get.

**Comment by AutismSpider** [comment]
@Exxion get that over lay when hit by  sleep toxin to

@Shadowmech88 Make it a race base gene

**Comment by ihadtoregisterforthis** [comment]
One way I see this being closer to being added is by controlled testing in a "Democratic" action: an admin button. Just like the mommi static, start some rounds with

> HEY KIDS WANT SUM COOL EFFECTS FOR YOUR RACE? 
> WANNA SEE A FEATURE?

and then

> SHOULD THIS BE THE DEFAULT OR SHOULD THIS BE THE DEFAULT? AMIRITE?

Guaranteed feedback

**Comment by Probe1** [comment]
@d3athrow At some point I'd like to talk about having more access to server polls given to admins.  We rarely take advantage of them to the extent that we could if use was better disseminated.  This is one of those times where if @DrCelt and @nuklearcellphoneg could make them we would see much more effective feedback on an issue.

**Comment by Exxion** [comment]
> Implying Celt can write good poll questions

**Comment by Probe1** [comment]
For +Permissions (the only immediate and reasonable flag choice without creating a new flag) the choices are those two, and two inactive or semi inactive admins.

Plus I'm an expert at yelling at Celt about being inappropriate and want to see my skills gainfully employed.

**Comment by liltiptop** [comment]
Maybe have robot eyes include a Medhud or something for a buff?
Also give the clown eye's the ability to see plasma as confetti so they can throw a party in the brig. :^)

**Comment by Probe1** [comment]
>Robotic eyes have different features that unlock based on your roundstart job or if you swipe an ID before having them surgically installed

fundit

**Comment by ghost** [comment]
@Probe1 

> Plus I'm an expert at yelling at Celt about being inappropriate and want to see my skills gainfully employed.

I can confirm.

**Comment by Killette2** [comment]
Reminder that color you see has to do with your brain more than your eyes. Your brain is what interprets what your eyes see, which is why hallucinations exist.

**Comment by ghost** [comment]
@Killette2 muh cones and rods though

**Comment by Arthurdentist** [comment]
I thought it was a quality idea and I didn't find the image that repulsive at all. The whole point would be lost if it was easily circumvented. I'd suggest tweaking the matrix until you found one that was 'better looking' perhaps.

**Comment by ghost** [comment]
http://ss13.moe/index.php/poll/37
:ok_hand:

**Comment by Zth--** [comment]
Gene idea is good

**Comment by Kitfox88** [comment]
I'm a vox player and I like it.

**Comment by Brolaire** [comment]
if its not too late to chime in:
Personally I really like the idea, however, I feel like this is gonna annoy a few Vox players (not all of course). I would like the idea (if this is possible) to only make them selectively colorblind, such as red/green colorblindness or blue/yellow colorblindness, maybe even make blue/red colorblindness to add those hilarious "is this o2 or n2?" situations to the game.

I also really support the gene idea, just make them all start with a gene anomaly

**Comment by nuklearcellphoneg** [comment]
@Probe1 @d3athrow @DrCelt 

On the poll thing, yes, we should be able to make polls, and perhaps spruce up the polling page as well.

Maybe make a +POLL flag Give it to Celt and I, and maybe say some Codermin, in order to ask the community how they feel about certain specific issues that come up, like the law 4 thing, or balancing changes, I-I can remove polls.

Preferably just yea or nay polls with pear as an option if you want to say idgaftbh.

Also this is a great  change, cheers.

Since clown traitors don't start out clumsy, can the Vox and so on start out without their disabilities via (LORE)?

**Comment by ihadtoregisterforthis** [comment]
Plasmamen are better seeing everything around flaming orange than purple.
Or, if purple, it could be an effect of the helmet, which would be more or less the same as racebound.

**Comment by Killette2** [comment]
I suggested that in OOC that plasmamen get a purple hue of everything while their helmet is on due tot he color of their mask. This however doesn't apply to heat res, where plasmamen can be naked if they want.
