### ISSUE TITLE
Invisible grilles on shuttle

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8622]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 25e4b508298181d88282a40acf22e88f603125b5 
> 
> General description of the issue
> reconstructing girders on the escape shuttle makes them invisible
> 
> What you expected to happen
> deconstruct and reconstruct would give me visible girders
> 
> What actually happened
> invisible girders that are not shown when rightclicking the tile, however they still act as a wall and you cant walk through them
> 
> Steps to reproduce if possible
> smash cockpit window on escape shuttle
> wirecutter girders
> step inside
> press z with rods in hand

**Comment by Exxion** [comment]
You mean grilles?

**Comment by Brolaire** [comment]
yes, grilles, sorry, im retarded

**Comment by PJB3005** [comment]
I've seen pooling on grilles shit itself a couple days ago, let's hope it's a one off case.

**Comment by clusterfack** [comment]
It's not pooling thats causing the problem, its bad coding

**Comment by PJB3005** [comment]
@clusterfack there were literally grilles that didn't correctly get their variables reset, these grilles were made by the CE right there.

**Comment by clusterfack** [comment]
I'm afraid you're totally wrong on this one because "Invisible girders" wouldn't be caused by pooling because pooling wouldn't set it to be invisible and neither does destroy.

**Comment by PJB3005** [comment]
[Ahem, I think you're the one who's wrong.](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/atoms.dm#L148)

Yes `gcDestroyed` was set one the grilles I'm talking about too.

**Comment by PJB3005** [comment]
I would also like to note that neither the name or the icon state of these grilles was messed up on any way.

**Comment by clusterfack** [comment]
Looking for gcDestroyed means nothing, both regular garbage collection and pooling set gcDestroyed. What you should have checked was disposed.

And perhaps you are seeing a different issue than myself then because I definitely have seen this issue with fucked up name/icon_state

**Comment by clusterfack** [comment]
More importantly, since Destroy() was called loc should have been set to null.

So either 
1. Resetvariables is called, which would set loc to null as well, and reset invisibility so it would be visible
2. Resetvariables wasn't called, it should have a null loc and invisibility

From this we can obviously see resetvariables wasn't called, therefore I have no reason to think it has anything to do with pooling, and not someone simply fucking up the code to not change the loc to null.

**Comment by clusterfack** [comment]
I've looked at the code and ALREADY found one theoretical issue
```
/obj/structure/grille/proc/healthcheck(var/hitsound = 0) //Note : Doubles as the destruction proc()
	if(hitsound)
		playsound(loc, 'sound/effects/grillehit.ogg', 80, 1)
	if(health <= (0.25*initial(health)) && !broken) //Modular, 1/4th of original health. Do make sure the grille isn't broken !
		broken = 1
		icon_state = "[initial(icon_state)]-b"
		density = 0 //Not blocking anything anymore
		getFromPool(/obj/item/stack/rods, get_turf(src)) //One rod set
```
Grilles that start broken have icon_state = "grille-b" and then call healthcheck which would set their icon_state to "grille-b-b"

**Comment by clusterfack** [comment]
Furthermore using a rod to repair a grille does this
```
				G.health = initial(G.health)
				G.density = 1
				G.broken = 0
				G.icon_state = "[initial(G.icon_state)]"
				use(1)
```

Which would set a broken grille's icon state to grille-b which is still broken
