### ISSUE TITLE
Players randomly can't see around them in darkness

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8623]
Sometimes, when you enter the dark, you can see a in a 3x3 square. One tile being yourself.
Sometimes you can only see 1x1, as in, only the tile you're standing at. This can cause in you being stuck and have all those unprecedented gameplay effects.
I died once because I could see only in a 1x1 square around myself and needed to break a window in order to escape, and someone was coming to kill me.

**Comment by 9600bauds** [comment]
Were you wearing sunglasses? Flash protection does that

**Comment by Imagebard** [comment]
>Were you wearing sunglasses?

FUCK SAKES
