### ISSUE TITLE
Facehuggers Can Rip Off Masks Through Helmets

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8633]
![image](https://cloud.githubusercontent.com/assets/3991927/13526593/752f3eb2-e1ce-11e5-8fc8-a4526f34d995.png)

@gbasood

**Comment by ghost** [comment]
SOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOODDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by Imagebard** [comment]
Note:
Should a xeno do this, the person with the mask will be infected.
But they won't be infected if they DON'T have a mask.

**Comment by gbasood** [comment]
wait what the fuck

**Comment by Exxion** [comment]
You just can't quite fix this, can you?

**Comment by gbasood** [comment]
I'll take a look at it, but I specifically did shit to fix a facehugger being able to take ANY action after ripping off a mask or bouncing off recently.

**Comment by ghost** [comment]
100% 
TESTED
