### ISSUE TITLE
Being able to butcher chopped-off limbs

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8634]
Thinking on the cannibalism feature suggested in #6789

With limbs flying left and right from gibbingtons and bombs, it could be interesting to be able to butcher said loose limbs for meat and bones, as right now all the loose limbs do is be trash or potential donors for those who are missing said limb. This would probably end up yielding more meat than the gibber as it would be more precise.

Additionally, if some xenoarchaeologist fancies getting into the occult with some soul stones, a potential use for said loose bones could be (besides macabre decoration)

> Re-assembling them in some way to resemble the human skeletal structure
> Implant a soul stone with a soul inside
> (Maybe have more steps to it than just that)
> You have successfully performed necromancy and raised a skeleton

**Comment by MusgardTiger** [comment]
Being able to butcher limbs to get meat would be neat. I mean people gib eachother and eat John Johnson burgers everyday, ain't nothing wrong with doing it more precisely.

Plus kitchen backroom would resemble a legitimate Austrian basement so am all for it.

**Comment by Imagebard** [comment]
Even if it only generated 1 meat per limb this would mean gibbing is better than The Gibber in the chef's backroom.

**Comment by ghost** [comment]
Was thinking about that, @Imagebard and you're right.

Thing is, I believe the torso isn't considered a limb object, but still the mob itself, so you could chop off all the limbs off somebody, butcher those for the meat, then throw the torso through the gibber (to get that 3 or 5 meat, depending on if the butchered was fat or not) and you get more meat for more work put in, but the gibber is still used.

At that point, yield is more dependent on how lazy the player is without alienating a certain piece of machinery.

**Comment by 9600bauds** [comment]
I think gibbing people should give more than 3 meat, anyways. A limb-based tally would be great.

**Comment by Killette2** [comment]
Does upgrading a gibber's parts increase the meat it produces? Should it?

**Comment by gbasood** [comment]
If limb-based butchering were included, then only major limbs should be butcherable. Arms, torso+groin, legs. No feet, hands, heads.

**Comment by ghost** [comment]
But sood, torso+groin aren't chopped off limbs, they're the source of the limbs

**Comment by Exxion** [comment]
I don't know, you can butcher mice, and feet, hands, and heads are bigger than mice.

**Comment by AutismSpider** [comment]
@Killette2  upgrading the gibber parts does nothing it should but it does not right now.
