### ISSUE TITLE
Bag of holding nerf and balance suggestion

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8635]
When EMPed, make it so the bag of holding malfunctions and disappears, such as when a bagulo happens. Look at all those gadgets on the BoH, how could it not malfunction when EMPed? I am not suggesting a singulo happen over a single bag, but I am suggesting that the bag itself just disappears out of your hands/back and all items inside are deleted when it is sucked into the malfunction.

Also don't be a retard and make sure there's no oversight for important items such as the nuke disk.

As it stands, the bag of holding is byfar the best bag in the game and when produced, everyone has one like it's a fashion statement. However, with this nerf we can suggest some balance to it too.

Maybe you can print a new stackable item to put inside your bag that allows EMP shielding, such as the EMP shielding pAIs get and security cameras get when plasma is involved, and this would imply the EMP shielding would be related to plasma. When EMPed, the EMP shield will consume stacks depending on the strength of the EMP and your bag would stay safe. Hell, this EMP protection doesn't even have to take a backpack slot, maybe you can attach it to part of the backpack a separate way so it doesn't take inventory space, and when examined the bag will tell you how much EMP protection it has.

**Comment by Shadowmech88** [comment]
> As it stands, the bag of holding is byfar the best bag in the game and when produced, everyone has one like it's a fashion statement. However, with this nerf we can suggest some balance to it too.

Well yes, it's intended to be the best bag in the game. So good in fact that it's expected for everyone to want to have one once R&D can make them.
This is mitigated both by their high material cost and the fact that they cause teleporters to malfunction.

Beyond that, I don't see why it's a _bad_ thing for them to be the best bag in the game with few downsides. This is a storage container we're talking about, not a weapon.

**Comment by Ephx1** [comment]
I don't particularly care for this idea, but the thought of a Validhunting scientist with ten bags of guns being stopped by a Vox raider with an Ion gun makes me giggle.

**Comment by ghost** [comment]
What if a bag getting EMPd switches its contents with another BoH?

**Comment by Killette2** [comment]
I made this suggestion keeping in mind, that people rarely use EMPs due to their somewhat limited availability to be found naturally on the station, with only 1 source of ion guns. The other sources being grenades from traitors, the chemical reaction, the singulo, and wizards. Also due to their limited availability, we often see as ghost situations where idiots SHOULD be using EMP, such as the riffle, but they don't because they're too new to do so.

Also they don't cost that much, diamonds can even be synthesized from other, mass producable, materials. I've seen rounds where science handed out advanced e-guns before the change like candy. If you think science couldn't easily pump out around 20 bags per round then there are either no/lazy miners or you are mistaken.

**Comment by Probe1** [comment]
I'm with @Shadowmech88 but @Skullyton is onto something neat as fuck.

**Comment by clusterfack** [comment]
Would let you intentionally steal from all other bags of holding really easily (for scientists/security)

**Comment by Imagebard** [comment]
As @shadowmech88 said, there's no reason to do what was said.
Unlike what killette2, hardly anybody has bags once they're made. "everyone has one like it's a fashion statement" is a giant overstatement.

**Comment by Killette2** [comment]
Time to play scientist and pass out bags of holding like candy

**Comment by Shadowmech88** [comment]
> there's no problem, so I'll create a problem and then campaign for it to be fixed

**Comment by clusterfack** [comment]
Time to play scientist and *do my job*

**Comment by Killette2** [comment]
I've seen it enough to warrant this suggestion, and it's not like it even kills bags of holding, and how harmful is it to give EMPs a new purpose?

**Comment by clusterfack** [comment]
I don't know if you're asking for a feature based on 'how bad could it be' without any real problem it's solving in the first place. I'm inclined to be against it.

**Comment by Killette2** [comment]
So a bag that can hold multiple large and/or dangerous items, that are impossible to hide otherwise, costing 2 or less diamonds (less if you upgrade the protolathe, which you can do with parts from the protolathe), that is seen on the science team almost every other round isn't a bit strong for the game?

**Comment by Shadowmech88** [comment]
I don't think so.

**Comment by clusterfack** [comment]
I can't think of any particular reason it would be.

**Comment by Killette2** [comment]
Fire axe, ion riffles, battering ram, and plasma cannon are good starters

**Comment by clusterfack** [comment]
Holding things of that size is basically the point of the bag of holding, you didn't think it was made to be a backpack holder did you?

**Comment by 9600bauds** [comment]
Anyone that claims BoHs are commonplace outside of Science or anyone with direct access to a Protolathe are just plain lying.

**Comment by Killette2** [comment]
They get passed out when singuloose :^)

not lying!

**Comment by Imagebard** [comment]
>Singuloose :^)

The round ends shortly afterwards unless someone is bothered to 1.Fight with heads of staff to prevent a shuttle call and 2.Rebuilds engineering
So can we close this issue yet

**Comment by Killette2** [comment]
> I disagree that bags of holding are passed out like candy
> This means the issue should be closed
> This also means the bag cannot ever be changed in any way, even if it was given a buff also, and a way to ignore this nerf

**Comment by Imagebard** [comment]
>I disagree that bags of holding are passed out like candy

I can't "disagree" with a fact. The truth is that bags of holding aren't passed out like candy and you lied to us to get something you don't like changed, but you just can't blurt that out loud.

**Comment by Killette2** [comment]
You can't just shoot down one point and say the rest aren't valid. I didn't say it happened EVERY round, no that's not a problem, but I still stand by the fact that I've seen it happen. I'm saying the rounds they do get mass produced, who doesn't wear them? I get science makes improved things, but minor downsides, such as one already existing which prevents you from accurately teleporting, won't kill your beloved bag.

**Comment by Imagebard** [comment]
>but minor downsides, such as one already existing which prevents you from accurately teleporting, won't kill your beloved bag.

Good, I guess the bag is well balanced as-is now.
Why are we here again?

**Comment by 9600bauds** [comment]
PhD in being mad

**Comment by Imagebard** [comment]
Could you please hush or something? The problem right now is that Killette2 opened another useless issue and once again proved that we would be better off if we threw him away and forced him to crossdress for the metaclub.

**Comment by Killette2** [comment]
Let's see this issue in more detail

Science creates lots of things that are electronic correct? Better power cells, energy related guns,posibrains, robotic limbs (if you are counting robotics), LOTS of things that can be EMPed

Then we have this gadgety looking bag with dials all over it, which has the ability to store huge items due to science. What? They can't be EMPed? Why is this? Surely since it was printed off of the protolathe using numerous different metals, you'd assume the creation was full of electronics to function the amazing way it does.

**Comment by Shadowmech88** [comment]
Are there any bluespace-utilizing items that can currently be EMPed?

**Comment by Killette2** [comment]
I haven't played with RnD recently enough to answer that 100% accurately, unless you want to post the code. But keep in mind the bag also takes other research branches such as engineering.

And to answer your question based on what I do know, I believe tracking beacons can be EMPed

---

Edit, bag of holding only takes 6 materials and 4 bluespace, was thinking of the drill with engineering. I'm sure the hand tele must be EMPable though

**Comment by FudgePucker** [comment]
Blue space beakers stasis beakers telebecons gpss handteles all don't have emp reactions I think.

Also deleting bags from emp is stupid, causing bags to cycle what its holding with another bag would be funny. You would be able to hand out bags of holding then put a bomb with a mousetrap assembly and play bag of fun roulette

**Comment by AutismSpider** [comment]
>high mat cost

>engi borg can shit out endless mats for them or they can use the mat sync to make all then need

oh you're being  serious let me laugh even harder 

@FudgePucker the blue space beakers/stasis don't the hand tele gets its power drain when emp

**Comment by 9600bauds** [comment]
The mat synth bug has been fixed for ages

**Comment by Killette2** [comment]
> Forgetting botany can mass produce plasma sheets using the plasma solidification formula
> Even implying that the Bag of Holding even cost more than 2 diamonds anyways
> Hell even XENOBIO can make metal easily, and plasma sheets 1 slime stage later

SCARCE MATERIALS AMIRITE?

**Comment by 9600bauds** [comment]
>botany can mass produce plasma sheets using the plasma solidification formula
Killete when you make issues like these you really need to speak in words that even vaguely resemble the state of anything that actually happens with any degree of consistency in the game, because otherwise you're being dishonest.

Even if what you just said had actually ever happened more than twice in a year, I don't see how it's relevant at all seeing as diamonds are the bottleneck for BoHs.

**Comment by AutismSpider** [comment]
@9600bauds yes the bug is fix all it cost is iron and glass to make the ammo to shit out the mats they need and iron and glass is cheap and easy to get and i point out engi borg thing all they need to do is jam the cheap to make hyper cells in it none stop for this.

**Comment by Killette2** [comment]
Once again, you're taking one of my points, then ignoring the other one calling it invalid too.

Are you saying xenobio is never used too? That metal, or dark purple slimes have never been seen?

**Comment by 9600bauds** [comment]
> I don't see how it's relevant at all seeing as diamonds are the bottleneck for BoHs.

What was that about taking one point and ignoring the other

**Comment by Imagebard** [comment]
As you can clearly see Killette isn't interested in playing fair.

**Comment by Killette2** [comment]
Diamonds aren't that hard to obtain, and usually a miner brings back diamond every trip just so he can get his diamond drill, weapons and bags not even related. Sure he might be a dickwad that brings back 5 diamonds at first, but diamonds will always exist, and the protolathe can easily be upgraded by using the protolathe itself to use less than 2 diamonds if unupgraded, less than 1 diamond if upgraded.

**Comment by 9600bauds** [comment]
It's Still The Bottleneck

**Comment by Killette2** [comment]
Mining borgs (just force a borg to do it, they are your bitches)
Miners
The Quartermaster (however unlikely)
Material synthesizer using plasma or metal from xenobio
Just going on the roid as a scientist and doing it yourself

**Comment by 9600bauds** [comment]
Look.

What you've said here is "material costs don't matter because you can make infinite plasma from xenobio and botany".

Then you went full retard when you realized that was stupid. I just don't care about this argument anymore.

By the way, you can't upgrade Protolathes to use less materials. So that's just a lie, too.

**Comment by Killette2** [comment]
I'm pretty sure you can, but I will allow you to prove me wrong.What materials does the protolathe take? I'm definitely sure you can do it with the autolathe, so why wouldn't it make sense to do it for the protolathe too?

Would you also be willing to take screenshots on the test server of protolathes with different tier parts to back up your argument, and their efficiency with said parts?

**Comment by FudgePucker** [comment]
Making bags go poof when emp'd wouldn't hurt science, it would hurt engineers who get a bag and make it less useful for destroying singuloth.

**Comment by AutismSpider** [comment]
@FudgePucker  only shit engineers set up the singuloth

**Comment by Ephx1** [comment]
And not-shit engineers stop it. It's not like everyone in engineering agrees on what to do together.

**Comment by 9600bauds** [comment]
![dreamseeker_2016-03-05_17-37-40](https://cloud.githubusercontent.com/assets/6526157/13550285/010f947e-e2f9-11e5-95db-9163106d0151.png)
![dreamseeker_2016-03-05_17-38-28](https://cloud.githubusercontent.com/assets/6526157/13550287/15ad4174-e2f9-11e5-9322-30cf6d3277d1.png)
![atom_2016-03-05_17-38-40](https://cloud.githubusercontent.com/assets/6526157/13550288/208fdee4-e2f9-11e5-95a5-2fdfbebfc460.png)
![firefox_2016-03-05_17-39-03](https://cloud.githubusercontent.com/assets/6526157/13550289/2a53664e-e2f9-11e5-8ffa-0947303f7057.png)
You can't upgrade autolathes either

**Comment by FudgePucker** [comment]
I know that. But there's always that one idiot who does it anyways

> speed run set up the SME before power outages, scatter the PA, and bring inside the gravitational generator. Filthy carbon still sets up singularity, even though 7K plasma rad collected O2 super charged SME.

*aflap *aflap *aflap

**Comment by AutismSpider** [comment]
>reagents
>protolathe does not use chems any more or has a use for it now nothing calls for acid and shit

need take the fucking beakers out of that thing

@Ephx1 Zero need for that awful black hole with room temp plasma it only make 400k to 600k Wats  you can half fucking ass the TEG and get 5 to 20 fucking MW of power only thing that thing is good for is antag taxi ride for the shuttle

**Comment by Ephx1** [comment]
I think your autism is getting out of hand. I just said people do it anyways, just like Fudge said. Settle down.

**Comment by AutismSpider** [comment]
![nromal day](https://cloud.githubusercontent.com/assets/10268342/13550324/c3765dfe-e2e0-11e5-8cd1-3778adaf3184.jpg)

**Comment by Killette2** [comment]
> 2250 diamonds for a bag of holding

Isn't one sheet of anything 3000 units?

Are you telling me that bag of holding from a normal protolath cost less than ONE diamond? Correct me if I'm wrong by inserting 1 sheet of metal and posting results

**Comment by FudgePucker** [comment]
Singuloth can produce enough power with super cold plasma, but if you are super cooling plasma why not just set up a different engine?

**Comment by Shadowmech88** [comment]
> Isn't one sheet of anything 3000 units?

I believe it actually varies based on the material.

**Comment by AutismSpider** [comment]
like 5000 for iron and glass diamond is 3000 per sheet

**Comment by 9600bauds** [comment]
3500 iron per sheet, 2000 diamond per sheet
Killete have you actually played Science? You seem to have very solid opinions on how it could work but are lacking knowledge on how it works

**Comment by Killette2** [comment]
Conflicting answers from the last 2 people to post here

Also even if it is 2000, 2250 is 1.125 diamonds. Barely anything.

**Comment by 9600bauds** [comment]
yes and 1.125 diamonds is infinity plasma because they're not exchangeable

**Comment by Killette2** [comment]
Except you can with a material synthesizer?

**Comment by 9600bauds** [comment]
Killete I'm not sure you realize that material synthetizers require IRON AND GLASS (IN THE FORM OF MATTER CARTRIDGES) to work and YOU CANNOT USE PLASMA TO CHARGE THEM
In the future please refrain from making issues like these until you have an at least superficial grasp on the thing you're complaining about

**Comment by Killette2** [comment]
What about metal slimes, which are even easier to get and mass produce than dark purple slimes?

**Comment by Imagebard** [comment]
![1409958379934](https://cloud.githubusercontent.com/assets/7571238/13550825/1cf614a4-e305-11e5-9fa3-882e62d97b9a.gif)
Does the word "giving up" not exist in your dictionary?

**Comment by Zth--** [comment]
close this shit

**Comment by 9600bauds** [comment]
and reopen it when metal slimes also give glass

**Comment by Killette2** [comment]
You don't need both metal AND glass to use the resource fabricator, just metal works fine.

**Comment by FudgePucker** [comment]
Yes you do. It requires material carts used in the RCD. The carts are made in the autolathe requiring metal AND glass.

**Comment by Killette2** [comment]
Maybe you are right come to think of it. That said glass can easily be farmed, but it would be tedious. Still, if a miner brings back 20 diamonds (read 4 nodes) then that can almost make 20 bags

**Comment by Intigracy** [comment]
tbh I'd like the idea of an EMP dumping the BoH's contents onto the ground, but not deleting the BoH and the items inside.

**Comment by Killette2** [comment]
Wow I look like a douche

**Comment by Intigracy** [comment]
You are a douche

**Comment by Killette2** [comment]
Pot meet kettle
