### ISSUE TITLE
[Meta] Genetics is completely separated from Medbay and I hate it

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8638]
YOU WANT MONKEYMAN FOR HEAD TRANSPLANT?
TOO BAD FUCK YOU, GO AROUND THE WHOLE GODDAMN PLACE AND DRAG IT THROUGH THE HALLWAY.
Geneticists not helping out in Medbay is a problem. Rather than trying to help with it, Meta just embraced the stigma and gave Geneticists their own safe zone echo chamber as an experiment of sorts.
Experiment over, here are the results. It's bad.

**Comment by AutismSpider** [comment]
rework genetics and make it not shit  they have one main job to clone fucking people and it got so bad that had to be fix.

**Comment by 9600bauds** [comment]
I think the absolute least that could be done is to make it so that the Genetics consoles are next to a window that points into the Cloner, not give them their responsibility-clad orange box.

**Comment by AutismSpider** [comment]
take it out as a job it does very little to help medbay or fucking sci for that matter

**Comment by 9600bauds** [comment]
That's not a map issue though

**Comment by Probe1** [comment]
I like it.  It's very interesting and having hallway accessible genetics is sweet.  The only thing I wish was different is it had a windoor and table.

NOT EVERY MAP HAS TO BE THE SAME BAUDS JEEZ

**Comment by Probe1** [comment]
Also geneticists are as part of medbay as virologists are.  They are but their jobs aren't the same as a doctor or a chemist where they are preoccupied with treatment.

**Comment by 9600bauds** [comment]
Not every map has to be the same but this one is different in a bad way

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/14234109/a44c25e2-f9a8-11e5-9b2a-fce1571a3dbc.png)

How about shifting the maint door up and putting a maint door directly across so it's a straight shot to medbay no twists no turns.

**Comment by Probe1** [comment]
I can even throw in a pair of windows so you can see the cloner from your chair and pretend you care about cloning.

**Comment by 9600bauds** [comment]
Sounds excellent, though it doesn't look like you could actually see into the cloner from the chair

**Comment by 9600bauds** [comment]
I consider this fixed by now
