### ISSUE TITLE
We should make bombermen not gib and also not track blood

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8640]
Because bomberman arena is a giant lag mine if left unattended

**Comment by clusterfack** [comment]
Alternatively we could fix blood

**Comment by 9600bauds** [comment]
That too

How do we fix blood?

**Comment by clusterfack** [comment]
Okay so the way we fix blood is by using a color matrix to create the desired look of the blood. This was previously not possibly which required the use of blend, and setting simply 'color' without a matrix ended up fucking up the look of it by alot. 

But with a color matrix you SHOULD be able to create a nearly identical effect (or one that looks a good enough approximation) to the way it looks when blended.

**Comment by Imagebard** [comment]
I'm also pretty sure that it causes lag because of virus-related checks.

**Comment by clusterfack** [comment]
While proxmove slows down our move() code, this is an entirely unrelated issue.

**Comment by clusterfack** [comment]
If no one knows how to mimic blend() using a color matrix properly someone could make a dev help post on byond's forum, they might know more.

**Comment by 9600bauds** [comment]
Ask Celt or PJB

**Comment by Shadowmech88** [comment]
Tested by hosting a bomberman round after filling the arena with gibs. Though the sample size was admittedly small, the bombermen reported no perceptible lag. It seems the optimizations made to blood since the report was filed have, at the very least, drastically lessened its impact.
