### ISSUE TITLE
Please fix the damn nanoUI consoles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8646]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
They are all fucked up to varying degrees.  http://i.imgur.com/s2nMcz5.png

This is not good work comrades.

**Comment by clusterfack** [comment]
GOD FUCKING DAMNIT ITS NOT FUCKING NANO

ALSO IT WORKS JUST CLEAR YOUR DAMN CACHE

**Comment by Probe1** [comment]
@clusterfack  I installed byond on a fresh SSD before I came back.  I cleared my cache just now.  

Shit is fucked; people are complaining.  Stop merging untested shit.  Every single day we have process crashes.  I'm asked every few days why the consoles don't werk by players.

**Comment by Probe1** [comment]
![dreamseeker_2016-03-07_12-17-01](https://cloud.githubusercontent.com/assets/8550416/13577092/d0e39888-e45e-11e5-8d05-38ac6c824e60.png)

**Comment by PJB3005** [comment]
One thing is that the Adv. Sec Cameras and the CMC uses HTMLI, the atmos one still uses Nano.

I think that vote's slightly misleading but yeah pomf fix your shit.

**Comment by Probe1** [comment]
People are referencing the same issue I had for the atmos console.  The alarms are all in the NE corner and can't be clicked.

I've cleared my cache and even if I hadn't, BYOND was installed on a new ssd after the z level size update was merged.

**Comment by PJB3005** [comment]
Oh shit I just realised this IS about the CAC.

**Comment by Probe1** [comment]
ALL of the advanced consoles are fucked up at this point.

**Comment by 9600bauds** [comment]
![dreamseeker_2016-04-04_18-35-20](https://cloud.githubusercontent.com/assets/6526157/14267312/bdc4b838-faa5-11e5-9cb6-1da74b5cc81a.png)
It's still somewhat fucked

**Comment by Probe1** [comment]
Count your blessings that it's even displaying the right station for you.
