### ISSUE TITLE
The great issue about Advanced Security Cameras

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8648]
~~So 1/2 of security camera consoles don't become useless because nobody cares to fix it. At least replace them with functioning consoles, the normal ones with slow menus.~~]

Haha nevermind
Welcome to Mr.Exxion's wild ride

**Comment by Exxion** [comment]
*sigh
OK, fine
Can someone tell me when advanced camera consoles last worked?

**Comment by PJB3005** [comment]
... 

Before pomf moved them to HTML interface and we're not going back to nano because lag.

**Comment by Exxion** [comment]
...Oh.
Oh fuck.

**Comment by Imagebard** [comment]
>We broke them and we're not going to the old version because its inferior even tough it works

![1455657847231](https://cloud.githubusercontent.com/assets/7571238/13544507/58739b38-e255-11e5-9fae-59a32359c9fd.jpg)

**Comment by Exxion** [comment]
>We

No, Pomf broke them
I'll take a look but no guarantees

**Comment by Exxion** [comment]
WHY
THE FUCK
IS THE CODE FOR THESE THINGS THERE?

**Comment by Imagebard** [comment]
7 hours in and the person that came checking for Advanced Camera Consoles started screaming.
I decree that Advanced Camera Consoles are eldritch abominations and must be kept away form the playerbase at all costs.

**Comment by Exxion** [comment]
Ssh I went to sleep give me a chance

**Comment by Exxion** [comment]
OK this is mysterious and esoteric
All the bugfix commits in the history of the file suggest that it DID work for a while after being ported to the HTML interface
But I'm 95% sure the issue is in the .js file rather than the .dm and the .js file hasn't been touched since a point in time in which it almost certainly worked
There are so many separate .js files linked in this thing it's like a fucking maze trying to figure out where each function is

**Comment by Exxion** [comment]
More than likely, it'll be easy to actually fix once what's broken is found
Finding what's broken, though, won't be so easy

**Comment by clusterfack** [comment]
What is wrong with them functionally? Seem to work fine for me

**Comment by Imagebard** [comment]
@clusterfack Okay, make sure you're using *Advanced* Security Camera consoles. Like the one in the warden office.
Right? You're using that?
Now notice that nothing appears in the map. You're supposed to, you know, actually be able to use them to select cameras in the station.
Text mode is broken too

**Comment by Zth--** [comment]
Atmos power alarm works but everything is out of place

**Comment by clusterfack** [comment]
Okay so I did and then it worked, so...

**Comment by Shadowmech88** [comment]
![image](https://cloud.githubusercontent.com/assets/3991927/13614768/b4b8e760-e537-11e5-889a-a953e639e9b3.png)
Case closed.

**Comment by clusterfack** [comment]
Indeed!

Now does the same thing happen for the CMC?
Do you have all the js and css files it requires in your byond cache?
Do other html5 things show up properly on your computer?

There's basically no way for us to debug this

**Comment by Exxion** [comment]
CMC works for me just fine
Advanced security camera consoles consistently do not work for me, even on local, and MANY people have the same issue
On local it at least gives me am error message, albeit not a very specific one
It suggests the .js file is not linked, even though it is
I'll try clearing my cache, etc. when I get up

**Comment by PJB3005** [comment]
@clusterfack seriously they're horribly broken, this isn't like that obscure some people couldn't use nano issue, this affects WAY too much people and simple things like it not being in the cache is basically impossible.

**Comment by Exxion** [comment]
If you're curious, the error it gives on local says that the add function is not defined
But it is

**Comment by Exxion** [comment]
Clearing my cache just broke it worse

**Comment by Exxion** [comment]
Alright, manually pasting the relevant files into my cache fixed it. For some reason, they fail to send.

**Comment by clusterfack** [comment]
@pjb3005 Sounds like its a cache issue to me

**Comment by clusterfack** [comment]
The reason why it would be a cache issue is that both advanced map UIs use identical methods for almost everything so the only difference between them is the assets. If he's getting undefined errors it's definitely an asset issue.

**Comment by Exxion** [comment]
Yes, as I said it's fixed by manually putting all the relevant files in the cache
So the issue is with sending the assets
And the CMC apparently has the same issue but I guess everyone already has its files cached from before asset sending broke

**Comment by Imagebard** [comment]
@clusterfack If you're going to hijack my issue like this, then I guess I'll play accordingly.

**Comment by Exxion** [comment]
OK what the fuck
Hey @Imagebard and anyone else who has this issue
Please try the following:

1. Try to use the broken advanced security camera console
2. Log off the server
3. Clear your BYOND cache
4. Log back on

Specifically in that order

**Comment by Imagebard** [comment]
It didn't do anything.

![coalgirls _tsukimonogatari_02_ 1920x1080_blu-ray_flac _ d5f97b17 mkv_snapshot_12 29_ 2016 03 08_21 08 34](https://cloud.githubusercontent.com/assets/7571238/13620888/fcfffdc6-e571-11e5-9140-3d135f893988.png)

I did it on the main server, as a observer/ghost.

**Comment by Exxion** [comment]
*shrug
It worked for me
On local, but that was not with the default config
(It will 100% not ever work ever if minimap generation is disabled, I think)

**Comment by Exxion** [comment]
Uh
Actually, do you mind looking in your BYOND cache for me?
Documents/BYOND/cache

Tell me if you see the following files:

1. Any .png with "minimap" anywhere in its name
2. `html_interface.js`
3. `map_shared.js`
4. `advcamera.js`

**Comment by Imagebard** [comment]
I don't have .js files, only those:
![00000](https://cloud.githubusercontent.com/assets/7571238/13621060/48043fc0-e573-11e5-9695-e932885801f9.png)

**Comment by Imagebard** [comment]
Wait up, let me look for the other files you mentioned.

**Comment by Exxion** [comment]
Yeah, the `.tmpl`s always seem to be there, but the `.js`s have issues

**Comment by Imagebard** [comment]
html_interface is here.
map_shared seems to be here, and in .js too.

**Comment by clusterfack** [comment]
Yeah those are necessary for the actual interface to display properly, but for the map to be replaced properly as it should you would need the advcamera .js

**Comment by Exxion** [comment]
The *really* mysterious thing is that *map_shared and advcamera.js are sent in the same proc*

**Comment by Imagebard** [comment]
And they're the ones that seem to be working.
Are all Adv. Security Camera console file procs working?

**Comment by Exxion** [comment]
Yes... sometimes
????????????????

**Comment by Imagebard** [comment]
*Wow.*

You mentioned it was working for you earlier, clusterfack. If you clear your cache go to the main server multiple times, does it stay that way?

**Comment by clusterfack** [comment]
Well I only had any perspective on this bug recently because I've been trying to convert central atmos to HTML and a certain thing someone added into prevent minimap inits was also preventing my js from being sent and the map wasn't loading properly. So I gave it a guess here.

**Comment by Imagebard** [comment]
Bump.
Any news or are Advanced/HTML consoles a abortion as always?

**Comment by Exxion** [comment]
No idea
Difficult for me to test fixes considering it now works for me

**Comment by Imagebard** [comment]
>It now works for me

I hate this bug with all my might.

**Comment by Imagebard** [comment]
As now can't fucking replicate the bug either, I will close this issue.
When someone that can replicate it appears, I'll ask him to open a issue on the github.

**Comment by gbasood** [comment]
C A C H I N G (probably)

**Comment by Imagebard** [comment]
I could probably delete my cache and see if it gets updated with the files again.

But I'd rather not do that right now.

**Comment by Exxion** [comment]
>(probably)

Yes, if you read the earlier comments, I confirmed it was caching
