### ISSUE TITLE
We need a gun that causes brain damage

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8657]
Not sure how we would get it, maybe similar research levels to the decloner, including the illegal ones, or just make it adminbus.

But the question being, why haven't we made a weapon that shoots energy projectiles that makes the victim retarded? Would this be a good weapon to introduced into the game? Impedizine filled syringe guns are not the same thing, but would be more like a ghetto version of it.

**Comment by 9600bauds** [comment]
Because brain damage is shit.

**Comment by Killette2** [comment]
Brain damage is very debilitating and would be interesting weaponized. Hell we've weaponized everything else from plasma riffles, genetics rad gun, decloner, syringe guns, chem sprayer, grenade launcher, pneumatic cannon, the spur which turns energy shots into brute, THE GHETTO BOMB GUN THAT RAPES EVERYTHING IN A SINGLE LINE, wheelchair cannons, and this doesn't even COVER adminbus guns

**Comment by AutismSpider** [comment]
@9600bauds >brain damage is bad

nigga at about 20% brain damage it becomes hard to use computers/can't use them at all and at random hard to see stuff not only that you start bashing your head on airlocks giving you MORE brain damage on top of brute. 

Even slime's can give you brain damage if they go for head shots.

**Comment by 9600bauds** [comment]
I said it was shit, not that it was bad.

**Comment by AutismSpider** [comment]
Brain damage is on par with clone damage even a little bit will fuck you over fast

**Comment by 9600bauds** [comment]
Just to be clear.
It's shit because it's awful, not because it's ineffective.

**Comment by Killette2** [comment]
Which is why I suggested research levels on par with the decloner, and since security or any nanotrasen personnel would have reason to use it, it would definitely need illegal tech.

Also food for thought, maybe we could make it similar to the thermal gun, where you can fire lots of minor shots, or one that drains all its energy in a big load. If you really want to fuck it more, make it not be able to be stored in backpacks or holsters and you have to wear it on your back.

Even if this is still too powerful, why not make it an adminbus item, just to make it? A syringe full of imped will fuck you more than 20% brain damage anyways

**Comment by Killette2** [comment]
*personnel would have no reason to use it, on mobile

**Comment by Killette2** [comment]
Also on the note of too strong, what happened to the pneumatic cannon instantly critting or even killing with one floor tile or glass share with enough pressure?

**Comment by icantthinkofanameritenow** [comment]
Actually, we already have a gun that causes brain damage. It's called the Mind Flayer, and it's adminbus-only. Deals 20 brain damage per shot, and also causes hallucinations. 

It's in here. 
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/projectiles/guns/energy/special.dm

**Comment by Killette2** [comment]
The name sounds familiar now that you mention it, so what should we do with it?

**Comment by Imagebard** [comment]
Keep it admin spawn only, never to turn back again.
Obviously.

**Comment by icantthinkofanameritenow** [comment]
@Killette2 
Try praying for it or something, I don't know. Just don't get your hopes up about ever getting to see it in-game.
