### ISSUE TITLE
Grey space suit Storage doesnt fit a normal sized 02 tank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8660]
(WEB REPORT BY: durgen REMOTE: 158.69.55.2:7777)
if this is a feature it's retarted.

**Comment by Imagebard** [comment]
Okay cool
Also
[Not A Bug]

**Comment by Shadowmech88** [comment]
I believe the grey spacesuit is a softsuit, and softsuits can't carry standard O2 tanks, only small ones.

**Comment by ghost** [comment]
It's intended

**Comment by clusterfack** [comment]
rekt
