### ISSUE TITLE
New HoS gear (MGR references ahoy)

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#8664]
Sprites for a helmet, high frequency blade and shield arm backpack item. 
![test](https://cloud.githubusercontent.com/assets/15067109/13551374/92ad2988-e32f-11e5-91d9-c901c3f058c2.png)

http://s000.tinyupload.com/?file_id=65500516683969541948
Edit: Updated closing animation with smoother rotation for north and south.

**Comment by ihadtoregisterforthis** [comment]
![sundowner](https://cloud.githubusercontent.com/assets/13305885/13551847/9aa8171e-e326-11e5-90f9-7d5605de99ee.jpg)

North and South animations could have some more rotation on the second step

**Comment by Exxion** [comment]
Yeah I agree, the plates seem to snap inwards really quickly on the north and south animations. The east and west ones look fine, though.

**Comment by Blithering** [comment]
Fair enough, those ones were done very early on. I'll redo them and update the link.
