### ISSUE TITLE
C4 Stored in jacket

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8670]
(WEB REPORT BY: squidmoko REMOTE: 158.69.55.2:7777)

> Revision 74a70d44b293f491c62680bde59b210bcf13f874
> 
> General description of the issue
> Put C4 in IAA jacket to store. When put in it auto counts down and explodes.
> 
> What you expected to happen
> Nothing at all
> 
> What actually happened
> My jacket exploded with me almost in it
> 
> Steps to reproduce if possible
> Should be easy enough. C4 in jacket

**Comment by Ephx1** [comment]
That's just beautiful.

**Comment by AutismSpider** [comment]
god bless shit code

**Comment by Kitfox88** [comment]
a+ gudcode :+1:

**Comment by 9600bauds** [comment]
TODO see if this is fixed by #12801

**Comment by Shadowmech88** [comment]
As it turns out, this was fixed.
