### ISSUE TITLE
Make the watermelons give more than 10 biomass in Hydro's Biogenerator.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8672]
(WEB REPORT BY: socachaca REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 74a70d44b293f491c62680bde59b210bcf13f874 
> 
> General description of the issue
> Watermelon gives a pathetic amount of biomass, compared to its size and to the rest of fruits that give more or less the same mass. I believe the change was made by a butthurt /tg/ coderbus dweller for some retarded reason.
> 
> What you expected to happen
> Get more than 10 biomass. Please.
> 
> What actually happened
> I got 10 pathetic biomass that is of no use to anybody.
> 
> Steps to reproduce if possible
> Grow watermelon
> put in biogenerator
> activate it
> cry as you realize it gives the same biomass as 2 despite the fact that you can slice it for 5 watermelon slices that give the same amount of nutrition.

**Comment by 9600bauds** [comment]
Biogenerator points are literally straight nutriment so unless the biogenerator gets snowflake watermelon efficiency it would mean that giving disproportionately high nutriment to watermelons

**Comment by BestName** [comment]
Watermelons used to contain more nutriment by default. I think there was also a bug which caused the biogenerator to give 2x the amount of biomass from watermelons which got fixed by /tg/ some time ago.
