### ISSUE TITLE
Add Goon-like sound reverbation

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8674]
Goon's sound reverbation thing sounds absolutely beautiful, it allows you to subtly hear everything on station without confusing you as to what is close and far

We should port it, however it seems harder than I thought

Or we could design something roughly similar to it, to avoid having to use the far_sound system for every single sound in the game

**Comment by Exxion** [comment]
Or we could not sound like we're in a fucking cathedral at all times

**Comment by ghost** [comment]
:ok_hand: :+1:
@exxion :-1: it's a space station not a cathedral, silly.

**Comment by Exxion** [comment]
Either way it sounds awful

**Comment by ghost** [comment]
It sounds like quality immersion. I'm sure that it'd be easy to make it toggleable if you're a nerd though

**Comment by Exxion** [comment]
I don't mean it sounds awful from the description
I mean in-game it does actually sound awful
It's like the worst part of playing on a Gooncode server, apart from the lag and bugs

**Comment by ghost** [comment]
To each their own, I think it's a petty neat feature and I like it sounding like I'm on a space station rather than on some perfectly soundproofed building

**Comment by Exxion** [comment]
Sure, emulsions and all that, but it still sounds like shit in my opinion

Make it an option and nobody with any sense can complain though

**Comment by CptWad** [comment]
yeah but changeling noises
and vampire noises

**Comment by SysadminJeroen** [comment]
@CptWad Maybe make a difference between loud noises (farting, yelling, toolboxing, airlocks) and quiet ones.

**Comment by IratePirate** [comment]
I've always sort of disliked it, or at least Goon's use of it. The constant distant screaming, farting and laser firing while you're calmly sitting in medbay was a real immersion shatterer.

**Comment by CptWad** [comment]
speaking of yelling *scream when?

**Comment by Gringonius** [comment]
I have to agree with Exxion, it's both a cool feature but not really that fitting. And with how things are right now you can expect any sounds of traitor activity attracting valid hunters like a catbeast announcement.

**Comment by PJB3005** [comment]
:+1: :x: :100:

**Comment by FudgePucker** [comment]
The sounds on goon make it unique, for better or worse.
All you can hear on our station is the radio or silence, everybody is off doing their jobs. On goon you can hear nothing but constant farting screaming and other noises off in the distance. Really spookie.

**Comment by ghost** [comment]
Farting and screaming won't be an issue here, fortunately.

**Comment by gbasood** [comment]
I agree, we should add this, just not to the degree goon has it.
Shouldn't be able to hear someone farting halfway across the station, or hear a ling absorbing in dorms without actually being in fucking dorms

**Comment by CptWad** [comment]
Id be ok with area based reverb, even if it might end up being shit

**Comment by PJB3005** [comment]
I'm looking into porting this and I've already began hitting a wall.

To prevent sound working cross space (for example sounds in the listening post being heard at the derelict) they properly organized their areas and made them a directory structure.

We don't have that and our ability to construct areas (blueprints) will make this even harder to pull off.

Any ideas on how to do this would be appreciated.

My only idea is making an extremely bloated and slow proc which runs on `world/New()` to make connected area groups.

**Comment by Exxion** [comment]
I don't care how you do it as long as it can be disabled
Please for the love of all that is holy make it a pref

**Comment by ghost** [comment]
Well, there's been that project of an area refactor, but it will require ridiculous amounts of work to convert everything

It will also need updating every single instance of an area typecheck or define in the code, and heavens know there are many since inheritance doesn't work and you have to type every single one by hand

Finally, while it could be universal, in the scope of a sound system it wouldn't work well on all maps. Absolutely nothing forbids a mapper from say, taking the Armory and putting it twenty tiles away on a minisat, and still having it under the security directory
