### ISSUE TITLE
Command reports are broken

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#8676]
ATTENTION, NEW COMMAND REPORT CREATED:

/$oo**boy*
Re;**r a<&< $**_@ st%_f <hat&3*/s ben**p**ra**_$d n de>eted&%h_/$as_0# /_e?ll_tha&<#_$**_a #_/_/<&%el<;pe% sentiece_ a>_has m_&ifee***\* ;\* be_e_e#*\* _@en I #/ay t__P_S*_D#_ B>& CAR_F_

Yeah. Nope. Fix this.

**Comment by PJB3005** [comment]
100% TESTED @DrCelt

**Comment by CptWad** [comment]
its all reports too, like for meteors or hostile infestation etc.

**Comment by ghost** [comment]
They're all broken? Whaaaaaat

**Comment by ghost** [comment]
Is it just the subtext or the title as well?

**Comment by CptWad** [comment]
both

**Comment by 9600bauds** [comment]
One Hundred Percent
