### ISSUE TITLE
Noir Mutation stuck on

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#8677]
I had some bumblefuck put himself on gumshoe and he did not want to see in black and white
so I forced his mutation off
Would not undo it
he later tried all other methods of gene reseting but all of them kept his noir mode on
@DrCelt

**Comment by Boxe** [comment]
that's detective bumblefuck to you

nothing removes the black and white vision

fix this shit

**Comment by DrCelt** [comment]
@Boxe was it still transitioning into black and white while you asked to be changed?

**Comment by Imagebard** [comment]
>i want to have the gumshoe title+coat but i don't wanna deal with this shit

Who let the casual in?
