### ISSUE TITLE
Minimum Pop Threshold for Extended

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8681]
Discussion/Feature Request

Personally I don't think extended rounds with five crewmembers are very fun.

**Comment by ghost** [comment]
The whole point of extended is it's supposed to be lowpop, nerd.

**Comment by Shadowmech88** [comment]
Right, but I think there should be a line between lowpop and extreme deadpop.
Lowpop to me is ~15 people.

**Comment by Ephx1** [comment]
So either you mean make it not start at all with 5 pop, or have a terrible round of instantly over tater.

**Comment by Iamgoofball** [comment]
extended is retarded on every codebase, remove

**Comment by ghost** [comment]
@Iamgoofball Feck off goofball as I said your opinion on balance changes is irrelevant as you're a TG gayboy and we're a fundamentally different playerbase.

**Comment by Exxion** [comment]
Extended is fun in midpop and not fun otherwise unless admins step in

**Comment by FudgePucker** [comment]
The problem is that with super low pop a murderboner could easily kill every crew member. Killing just two people with five crew members and you already depopulated half the server.
