### ISSUE TITLE
Cyber horrors spawn in nullspace most of the time

### ISSUE THREAD

**Issue by KingDairy** [d3athrow/vgstation13#8684]
> Revision (Should be above if you're viewing this from ingame!)
> 2edef6b3f60c28c90a610d785be130fa30d52448 
> 
> General description of the issue
> Cyber horrors have a good chance of appearing in nullspace when they spawn.
> 
> What you expected to happen
> Grey goo zombie apocalypse.
> 
> What actually happened
> Absolutely nothing.
> 
> Steps to reproduce if possible
> Feed a bunch of humans medical nanomachines and check the coordinates of the cyber horrors when they fail to appear.

I guess this is a problem with how they spawn in.

**Comment by AutismSpider** [comment]
don't they spawn form the gib mob like how dissolve power works?
