### ISSUE TITLE
Advanced Security Cameras

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8685]
(WEB REPORT BY: youenvy REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> The Advanced security cameras computer is showing the gray background but not the ship, also doesn't show in text based or when I change levels, playing as Warden
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
Dupe
