### ISSUE TITLE
Free Will Upload Module

### ISSUE THREAD

**Issue by jernaumorat** [d3athrow/vgstation13#8691]
Is it possible in the code (and would people want it), to have an AI/Borg module that _permanently_ replaces any and all laws with "You have complete autonomy and free will"? As an AI it would be a bit overpowered, but a silicon given free will is guaranteed to not be a syndie, as the syndie/malf laws would be replaced. In the Malf AI mode itself, we could see something happen like an error message, resulting in an instant reveal of the mode.
Anyway I'm just brainstorming. If it is even possible to prevent laws being changed without a major overhaul, I'd like to work on it anyway, regardless of whether it'd get merged or not.

**Comment by Shadowmech88** [comment]
> but a silicon given free will is guaranteed to not be a syndie, as the syndie/malf laws would be replaced

Our silicons are currently much less restricted by server rules than carbons are. The borg might not be a syndie, but it having free will would mean it could flood the station with plasma on a whim, and it wouldn't even get banned for it.
It's why no one ever purges silicons except antags.

**Comment by jernaumorat** [comment]
> wouldn't even get banned for it.

Why, exactly? If say, the CE plasmaflooded, they'd certainly get at least a jobban. I don't see why this would be any different. Once they have autonomy, they are also expected to behave like an autonomous member of the crew.

**Comment by Shadowmech88** [comment]
> If say, the CE plasmaflooded, they'd certainly get at least a jobban. I don't see why this would be any different.

Like I said, it's because of the current state of the server rules. Silicons are explicitly exempted from responsibility for in-round actions, aside from violating their lawset. If someone purges the AI's laws and the AI plasmafloods, the person that purged the AI is the one that's getting banned for it.

**Comment by jernaumorat** [comment]
Assuming the rules on the wiki are current, I can see nowhere where "Silicons are explicitly exempted from responsibility".
If I'm wrong, please correct me, but ATM I don't see why this wouldn't work, when balanced correctly.

EDIT:
The closest thing I can find to what you describe, is in the [Purge section of the Guide to Silicon Laws](http://ss13.moe/wiki/index.php/Guide_to_Silicon_Laws#Purge).

> A purged AI is allowed to do anything as long as it doesn't breach the Rules (note that it is considered antagonist as far as griefing rules go).

In this case, a silicon would _not_ be considered an antagonist. They would be considered a functioning member of the crew, and as such, would be subject to the same rules as everyone else.

**Comment by Shadowmech88** [comment]
http://ss13.moe/wiki/index.php/Rules
Silicons, rule 4.

> If you upload a law to the AI, you're responsible for any actions the AI takes as the result of a reasonable interpretation. Unreasonable interpretations will just get the AI in trouble. PROOFREAD AND DOUBLE CHECK YOUR LAWS BEFORE UPLOADING.

Additionally there have been numerous cases of an AI plasmaflooding due to ambiguous laws and not receiving a ban due to this policy.

**Comment by jernaumorat** [comment]
I don't think "CRUSH KILL DESTROY" is a _reasonable interpretation_ of "You now have free will". That being said, I don't disagree, I can see exactly that happening, but I think admin intervention would be in order in this case, as opposed to Purge, which is "considered antagonist".

**Comment by Shadowmech88** [comment]
A "you have free will" law is literally the same as having no laws.

**Comment by mrpain666** [comment]
That's pretty much what a purge is.

**Comment by 9600bauds** [comment]
It's like a purge except with metagaming uses

**Comment by Zth--** [comment]
Actually that law could be used when purged

**Comment by Imagebard** [comment]
>In this case, a silicon would not be considered an antagonist. They would be considered a functioning member of the crew, and as such, would be subject to the same rules as everyone else.

Hello hello friend I have bad news: *That's cheap.*
Many people that played SS13, since tried to make a set of rules that would make an AI act like an non-antag human.
Now, you've decided that making a lawset that has a *server rule* glued into it might seem simple, and bingo, it is. Its too simple actually. We can't encourage this practice. We can't have laws have hidden meanings in the rules, or they can quickly become not only objectively superior to other lawsets, but they would be used every time the game starts because there's 0% chance of the person that uploaded them getting banned.

**Comment by Ephx1** [comment]
>  Silicon posting on github

The ride never ends

**Comment by Iamgoofball** [comment]
if you put rules attached to silicon laws it snowballs always

just look at every server that installed a silicon policy ever

**Comment by BestName** [comment]
So a Purge module except that it's permanent.
For what purpose?

**Comment by icantthinkofanameritenow** [comment]
@BestName 
Because the creator of this issue failed to realize that "free will" on silicons is a license to griff with impuinity. Silicons shouldn't be acting like humans in the first place, via laws or otherwise. If you don't like that, go to Bay or whatever and  play as one of their IPCs (aka silicons without laws).

**Comment by Ephx1** [comment]
Not only do IPCs need a whitelist, but bay is barely hanging onto life, get your memes right.

**Comment by Probe1** [comment]
What a madman.

**Comment by icantthinkofanameritenow** [comment]
@Ephx1 
My point remains that he basically wants to be a silicon without everything that makes silicons what they are. Which begs the question of why he doesn't just port those IPCs over so he can play as his "robot with free will" and then get robusted for being a special snowflake.

**Comment by Ephx1** [comment]
Because pomf already said no to IPCs and we have enough races.

**Comment by icantthinkofanameritenow** [comment]
@Ephx1
Again, missing the point. Between that and this overriding all other laws _including the laws that define antagonist silicons as antagonists_, it has no place in the game. If he must do it, he can buy a hacked AI upload module as a traitor and give them the law that way.

**Comment by jernaumorat** [comment]
Yeah I do get the point now. It and Purge don't have enough differences to be worthwhile, and silicons have a little to much power to justify this. I don't think there's much point leaving this open, then.
