### ISSUE TITLE
Chef Excellence sauce not working propperly

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8692]
(WEB REPORT BY: manfreed REMOTE: 84.163.145.21:54074)

> Revision (Should be above if you're viewing this from ingame!)
> -none-
> 
> General description of the issue
> Eating 40u of the Chef Excellence sauce doesn't kill. 100u works fine however.
> (tested on private server. May need additional testing)
> 
> What you expected to happen
> To be dead after a couple of minutes
> 
> What actually happened
> Nothing for 15 minutes
> 
> Steps to reproduce if possible
> Put 2 bottles (40u) of Chef Excellence sauce on a donut and eat it.
> Wait for 15 minutes.

**Comment by PJB3005** [comment]
The chef traitor item, right?

IIRC the way it works is that it needs X amounts of ticks inside a person, and once you reach that the person instantly dies.

Issue is you don't get enough sauce to reach that amount of ticks.

**Comment by Iamgoofball** [comment]
replace with amatin 2k16

amatin does damage based on the amount of ticks it is in the target when it depletes fully

**Comment by Killette2** [comment]
FUCK YOU GOOFBALL. ALPHA AMATIN SHOULD FROM DESTROYING ANGELS, THE MUTATION OF FLY AMANTIA

https://github.com/d3athrow/vgstation13/issues/7915

DO NOT STEAL MY ISSUE, REEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Intigracy** [comment]
I could make it require only 5 units to kill someone, but that's a huge balance change.

Opinions.

**Comment by PJB3005** [comment]
@Intigracy make it take the amount you get from buying 1 dose in the uplink.
