### ISSUE TITLE
New medbay feature: Itching buff

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8693]
Itching. A thing that's not as common as your head hurting from welding without glasses, or not feeling well from uncured toxin damage. Sure all the above are flavor text, but what if we did something with itching?

Since itching is the least common of the 3 above mentioned, this would not evolve into the new cancer which plagued medbay until it was removed. Itching is obtained from virology or a space drug overdose (30+ units of space drugs), this in turn would also make drugs more hardcore.

The idea would be this, you get an itch. The longer the itch stays on you, it will grow. To treat an itch once it appears, just use grab intent on yourself, and select the part on your body where your itch is located to scratch it. Seems simple yes? Just scratching yourself is the cure. However, things can go wrong.

Stage 1: It's just an itch, scratch it. Once scratched, the itch will go away and it's simple as that. Don't do drugs kids!

Stage 2: For some reason, after repeated messages you don't feel like scratching your itch, it is now giving you a more serious warning message saying that your skin is starting to dry. Scratching is still the cure and no negative effects. Once you scratch the itch at THIS stage, an item falls to the ground called a flake of skin. It does nothing and your itch is cured, however it is also edible. This is totally gross, so it's edibility is optional, but hey who are we to judge?

![thatsakeeper](https://cloud.githubusercontent.com/assets/5169310/13579497/dc497dfc-e46b-11e5-9825-4e778779a957.jpg)

Stage 3: Your itch has now become a rash due to neglect. You will automatically scratch it causing you to bleed a little bit (NOTE VERY LITTLE, NO BLEEDING TO DEATH FROM A RASH) and this blood coming from your body along with scratching it uncontrollably might start to concern you. Head to medbay, the only treatment now is ointment on the affected area.

Stage 4: You really fucked up now. Your rash has evolved into puss filled hives. You will continue to scratch uncontrollably at your body, causing the sores to open, not only making you bleed minorly, but get toxin damage from bacteria entering your open sores. Medbay must manually drain the hives on your infected area via surgery and cauterize them shut, then apply ointment to cure the rash before you grow hives again. Next time you will scratch your itch, unless you want to be an abomination for FUN purposes.

**Comment by unid15** [comment]
which drugs are you on because I want some of that shit too

**Comment by NigglyWiggly** [comment]
![](http://puu.sh/mgzfn/4e94655113.png)

**Comment by ghost** [comment]
I preferred back when it was just babies

**Comment by Shadowmech88** [comment]
It really concerns me that I can't tell whether you actually want this or are just messing with us.

**Comment by Killette2** [comment]
> We can have vore tier monkey eating via monkey cubes
> You can even vore living monkeys whole if you're fat
> We can have diseases that make you puke eggs, cockroaches, and spiders
> We can fart in peoples faces, and have disturbing noises come out of our mutilated asshole when your butt is removed and wear asses on our heads
> But god forbid we have bad skin

**Comment by Praecordia** [comment]
> vore tier monkey eating
> eating a monkey cubes makes the deformed monkey chestburst you and fuck up your internals massively
> senpai...

**Comment by Killette2** [comment]
You forgot that you can eat them alive when fat, same way xenomorphs vore people

**Comment by Killette2** [comment]
> Slugs can crawl inside you and inject you with tons of juices

It's like you fuckers just want fetishes and not actual medical conditions

**Comment by ghost** [comment]
You're a strange person with even stranger ideas. You don't get hives from ignoring an itch.

**Comment by Killette2** [comment]
What term do you suggest to replace hives with? the point is them to become progressively worse, and it's not like diseases in space make sense anyways - see virology where random things just get mixed together

**Comment by Shadowmech88** [comment]
So is this a disease or just a regular old itch?
Because nothing happens when you ignore an itch if it's just an itch.
If it's a disease then call it a disease.

**Comment by Killette2** [comment]
It's a feature, but just an itch. For example, currently if you keep ignoring the head hurting message your messages get worse such as your head feels like it's about to split open and you take damage.

**Comment by Probe1** [comment]
Sounds neat but I'm not coding it.

**Comment by Shadowmech88** [comment]
Except headaches getting worse over time is a real thing that can actually happen. Regular itches turning into puss boils and hives is not.

**Comment by Killette2** [comment]
That's why the only source of itching ingame is space drugs and virology, so it CAN have a legit reason in this scenario. Have you ever itched in spess for no reason?

**Comment by Zth--** [comment]
This makes me feel uncomfortable.

**Comment by Arthurdentist** [comment]
its a "killette2 posts shit ideas" episode

**Comment by xpcybic** [comment]
Reading this made me itchy

**Comment by Killette2** [comment]
Be sure to scratch it
