### ISSUE TITLE
AME room is fucky on meta and deff

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#8698]
So the problem is you have to build and expand your AME upwards in meta and deff due to room design and that causes problems with AME (cores do not appear and AME becomes a hunk of useless metal). However if you build it like you do on box wich is from left to right, it works. 

Coders and/or mappers can fix this by adjusting AME rooms on meta and deff so you can build your AME from left to right or fixing AME code. 

Good day, m'codepeople.

**Comment by Probe1** [comment]
Happens on box too.  It's been an issue for almost a year now.  Ghlor said he'd take a look at it.

**Comment by ihadtoregisterforthis** [comment]
I don't get it. Is it a problem with superspecial code or is it that you can't figure out a way to make an AME on the space given?

**Comment by MusgardTiger** [comment]
On meta and deff assigned position for AME control thing requires you to build it upwards. Which causes AME to fuck up and become useless basically. You can build it like you do on box which is left to right but you'd have to make adjustments in the room and not everyone is aware of this bug.

**Comment by coldcola** [comment]
I'm just happy I can be of more use on deff now, with no singulo I was at a loss.

**Comment by Probe1** [comment]
The AME has a "Refresh Parts" button now that players can press.  It's the equivalent of banging on the top of a TV to make it work.  

It works.. but it's a sad solution.

**Comment by Probe1** [comment]
tbh I'm looking at it here and it doesn't look like a problem on metaclub.  Metaclubs AME room is 11 x 6.  Boxes is 8 x 7.  If the AME doesn't set up right, just hit REFRESH PARTS.  I don't think a mapping solution is the right approach because the AME room is already plenty big and expanding it would need the transit pipe thing moved and a whole lotta why.

**Comment by Probe1** [comment]
Desu this isn't a mapping issue its a code issue with the initialization and both AME rooms have been changed since this issue was made.

**Comment by Probe1** [comment]
It's still not a map issue. 
@ComicIronic 
@PJB3005 
@clusterfack 
@Exxion 
@9600bauds

**Comment by ComicIronic** [comment]
henk

**Comment by ghost** [comment]
Why is this still an issue?

**Comment by Probe1** [comment]
Because I'm gonna close all the old issues on March 1st like I did around Jan 1st.
