### ISSUE TITLE
Medihuds don't work for monkeys

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8699]
(WEB REPORT BY: archsunder REMOTE: 158.69.55.2:7777)

> Revision 16b9c9b6c966ca8c77c1e458164dcdf081a980e5 
> General description of the issue
> When a monkey wears a medihud, it doesnt show vitals on people or allow access to medical records when you examine people. 
> 
> What you expected to happen

Vital signs

> What actually happened
> 
> Steps to reproduce if possible

**Comment by Intigracy** [comment]
This bugfix requires so much work.

**Comment by clusterfack** [comment]
For performance reasons I don't even see why it should be fixed

**Comment by Intigracy** [comment]
The HUD drawing only affects human mobs and only works for human mobs, except for the pai code.

**Comment by Intigracy** [comment]
Yeah this would require a shitton of work.

I was able to manage to get huds to work ON monkeys, but not FOR monkeys. Humans could see the health of a monkey but monkeys couldn't see the health of humans or monkeys.
