### ISSUE TITLE
Add a template to poll observers for antagonists when a player enters an away mission

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#8700]
Most of our defunct away missions feature characters or units from antagonists lore.  Wizard Acadamy/Emitter Hell/Station Collision.

These would be better served with live players in addition to simple mobs.  

This issue isn't going anywhere any time soon since our current away misisons are fucked anyway.

**Comment by Brolaire** [comment]
I really like this idea, just give them a prompt similar to borer, pAI or xeno embryo. im curious as to what is actually wrong with Away Missions since I remember it being broken since I played on tg for the first time, which was in like 2013 I think.

**Comment by Probe1** [comment]
Coincidentally I just explained this to someone.

2:13 PM - Probe1: You would need to use Dreammaker which is included in your byond installation to edit the maps.  They have roughly 10 objects that have incorrect paths from when chairs and beds were refactored but the missions (being disabled at the time) weren't updated.
2:13 PM - Probe1: Once the mapping portion is resolved, you would need to figure out why
2:13 PM - Probe1: which is it
2:13 PM - Probe1: spacebattle.dmm can sometimes spawn infinite numbers of syndicate operative hostile mobs.
2:14 PM - Probe1: which you might guess causes serious issues with server performance.

The sad thing is I 99% fixed away missions obj paths six months ago but one thing led to another and the PR was never made.  Then ANOTHER person came and 99% fixed ... and one thing led to another..

It's some kind of gypsy curse.

**Comment by Probe1** [comment]
we have no away missions so lets worry about that then.
