### ISSUE TITLE
new Large Dual Port Air Vent dont have ID Tag

### ISSUE THREAD

**Issue by Dennok** [d3athrow/vgstation13#8701]
https://yadi.sk/i/dfgWhiHupyQDf
![](https://2.downloader.disk.yandex.ua/disk/a627cc54bf9ee9b044b496d6b8629dd0334a1dc1a5c6babd3cad680065aaa3f0/56de2891/0JtC8IFH0Kwjv_vSHYb_YIBobkayjeORipfHzKhV8P91w8uzK0czpg-mO6Ofepr8w0XtL_4O_LCtyuFE4v9nVg%3D%3D?uid=0&filename=2016-03-07%2023-16-08%20Large%20Dual%20Port%20Air%20Vent%20Configuration.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=33063&hid=b583b2b2a48b15858a1ab6b1c3022e0a&media_type=image&tknv=v2&eta g=c4fe411c7080978f4c87fdf12470083b)
new Large Dual Port Air Vent dont have ID Tag

**Comment by Dennok** [comment]
https://2.downloader.disk.yandex.ua/disk/a627cc54bf9ee9b044b496d6b8629dd0334a1dc1a5c6babd3cad680065aaa3f0/56de2891/0JtC8IFH0Kwjv_vSHYb_YIBobkayjeORipfHzKhV8P91w8uzK0czpg-mO6Ofepr8w0XtL_4O_LCtyuFE4v9nVg%3D%3D?uid=0&filename=2016-03-07%2023-16-08%20Large%20Dual%20Port%20Air%20Vent%20Configuration.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=33063&hid=b583b2b2a48b15858a1ab6b1c3022e0a&media_type=image&tknv=v2&etag=c4fe411c7080978f4c87fdf12470083b

**Comment by PJB3005** [comment]
Gah I actually remember this bug but I never fixed or reported it. 

You can work around it by opening the UI's HTML file in the BYOND cache (should be pretty high when sorting based on modification date) and editing the button so there's actual text in it, then reopening the UI.

**Comment by Zth--** [comment]
Wait can you edit the cache? And is that windows xp?

**Comment by PJB3005** [comment]
Yes, most browser resource files won't be resent when you edit them in your cache.

The exception is HTML (.htm) files which get reset if the contents of the ui changes.

**Comment by Dennok** [comment]
win 7
