### ISSUE TITLE
Add a master spawner object like the MoMMI spawner

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#8702]
We could really do well to have a spawnable spawner that accepts custom paths and is activated the same as a MoMMI spawner.  As well, it needs a variable that sets how many times it can be used.

Instead of the hassle of an admin saying ahelp for fun, we can just place a spawner and let anyone that wants it click in.  If we only want one wizard, or alien larva, or corgi, or whatever then we set it to 1 in VV.

Unlike a MoMMI spawner, it'd need to be visible only to ghosts.

**Comment by Exxion** [comment]
I have a feeling that stealing the Bomberman spawners would be better for this than the MoMMI spawner

**Comment by Probe1** [comment]
Excellent idea, that's way less code to cannibalize.

**Comment by coldcola** [comment]
hook up TVs to it so crew can watch a la thunderdome?

**Comment by Probe1** [comment]
I feel like someone added some bullshit that kinda works this way and whatever.
