### ISSUE TITLE
Nerf TEG does fuck all now

### ISSUE THREAD

**Issue by AutismSpider** [d3athrow/vgstation13#8704]
When you do a nerf make sure it fucking works TEG just jams up non stop even with low levels of  pressure in it

**Comment by Probe1** [comment]
I have no idea what's wrong with it, but it's jamming for reasons I can't explain.

**Comment by AutismSpider** [comment]
it was jam up be-for i pump in the hot plasma and cold plasma

**Comment by Probe1** [comment]
There's something extremely fucked up with the air processes in this round.

**Comment by AutismSpider** [comment]
No at this rate TEG does not work its jamming up on nothing.

it never jam up when the hot loop was 4000kpa but now it is none stop.

**Comment by Zth--** [comment]
Make a revert pull and then make them testt their shit

**Comment by PJB3005** [comment]
Hey smart-ass it's not broken you just need to git gud. 

I did not change the physics of the TEG, I only cut the power production rate by 4 times. 

it jams if it stops producing **thermal** power and then needs 10 seconds of producing thermal power to restart. 

Yes, I have tested it, it is not broken, your setups are.

**Comment by AutismSpider** [comment]
all it did was jam up using bare bones bones set up and custom one i used non stop can even ask Probe1

**Comment by PJB3005** [comment]
And was the pressure on one of the turbine's out sides higher than the in side?

**Comment by Skullyton** [comment]
Don't you need a difference in pressure to drive the turbines?

**Comment by PJB3005** [comment]
Yes but if your pressure is HIGHER on the output side of the turbines then you're not gonna move gas and as a result you won't have thermal power generation.

**Comment by Richardw93** [comment]
I've been trying for three rounds even with the help of an admin and I can't get it working. Could you perhaps briefly describe a setup that works?

**Comment by Imagebard** [comment]
TEG bug was discovered, basically something about it updating faster than the pipe network.
Closable.

**Comment by ComicIronic** [comment]
Issue number

**Comment by Imagebard** [comment]
#10034

**Comment by Probe1** [comment]
Its not what he's talking about but he's still right.  The TEG does fuck all power now.

We did it Reddit.

**Comment by Imagebard** [comment]
The TEG nerf was also undone but what do you know.

**Comment by PJB3005** [comment]
That's die to the ticking desync

**Comment by Probe1** [comment]
I meant its back to how it was.  Relegated to a curio.

**Comment by PJB3005** [comment]
How it was was perfect though.

Git gud.

**Comment by Imagebard** [comment]
If this issue does cover the TEG uselessness as a bug, it overlaps with #10034 
If it refers to PJB's nerfs, then that was undone already.

Ergo, fuck this issue.

**Comment by Probe1** [comment]
see comment above.

**Comment by Skullyton** [comment]
>Git Gud

It literally didn't work
