### ISSUE TITLE
Chef Special requires a too high dosage to kill

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#8706]
It's 5 AM and I gotta go sleep so please excuse any results I might reach that are just embarrassingly wrong.

The comment right above the Chef's Special in code/modules/reagents/Chemistry-Reagents.dm says:

> //Quiet and lethal, needs at least 4 units in the person before they'll die

Chef's Special has a metabolism of 0.39 and doesn't kill until it reaches a data tally of 165 (starts at a tally of 1). If I'm not mistaken, you will need 63.96 units of chefspecial in your system in order to reach a data tally of 165 and you'll need to wait about 11 minutes until they actually die.

**Comment by PJB3005** [comment]
Yup exactly.

**Comment by Imagebard** [comment]
We already have #8692
