### ISSUE TITLE
Add nutriment back into Bustanuts

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8707]
Syndie-cakes are still free and still have nutriment and it has caused zero issues
BUSTANUTS OR RIOT

**Comment by Ephx1** [comment]
Syndie-cakes do require that you hack the machine though, right?

**Comment by Zth--** [comment]
Yes. It's better this way, for once in my life I need a chef, and I'm not the only one.

**Comment by AutismSpider** [comment]
the cakes DD in it

**Comment by 9600bauds** [comment]
You absolutely couldn't feed a station on just the spawning bustanuts still, even back when they had nutriment I would always have to get the raisins
If anything then just make bustanuts contraband like syndie-cakes, because having them be COMPLETELY WORTHLESS is kind of bad

**Comment by Killette2** [comment]
There are enough vending machines for people to rely on nuts for 30ish people. If this change were to be done, I'd nerf the amount, because it used to have a whole 6 which is better than all the others, and free.

**Comment by 9600bauds** [comment]
> There are enough vending machines for people to rely on nuts for 30ish people.

What no
If mass feeding is a problem, I often hack for syndie-cakes and all 6 are still there, so it's not like anyone cares

**Comment by Ephx1** [comment]
> If anything then just make bustanuts contraband like syndie-cakes

Yeah I'm fine with that.

**Comment by liltiptop** [comment]
Agreed.
Trying to pay for 4noraisens all the time is a pain in the ass. Make bustanuts contraband and only have 5 boxes per machine for balance.
