### ISSUE TITLE
Air flow disabled on this tile.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8711]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/3HXTkho.png

The hall should be a vacuum thanks to the missing window but everythings fine.

**Comment by Zth--** [comment]
Actually the area was depressurized later. I was playing that round, maybe air was processing slowly

**Comment by clusterfack** [comment]
The primary cause of this is that small areas bounded by windows don't properly merge into larger as zones so there is two layers for the air to pass through. Some excessive CPU causing air to process slowly could be a secondary cause.

**Comment by Intigracy** [comment]
Does breaking a window not update the zones the same as creating one?

**Comment by Probe1** [comment]
Well I observed the area for quite  a bit of time and it stayed at 101 kPa, don't know what to say.  I don't see anything wrong mapping wise.

**Comment by Probe1** [comment]
Please close
