### ISSUE TITLE
Why the fuck does rye cure Grey powers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8712]
(WEB REPORT BY: lorkhatosh REMOTE: 158.69.55.2:7777)
Why is this still a thing.

**Comment by 9600bauds** [comment]
because you haven't reported it

**Comment by ghost** [comment]
This was fixed. It's a bug if it unfixed itself, not balance, @9600bauds

**Comment by 9600bauds** [comment]
Aite, didn't know, sometimes I forget greys exist
