### ISSUE TITLE
SME breaks forever if it makes a warning about exactly 19% or 119% instability.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#8713]
To do the audible warning messages the SME makes, it calls `vox_num2list`

This proc uses `num2words`

And this proc has an off-by-one that causes it to crash at (1)19%.

That crash then gets caught in the `do_work()` of the power machinery process.

**Comment by clusterfack** [comment]
I did some testing, I couldn't get num2words to crash at 19.

It did however crash at any multiple of 100 (less than one thousand).

**Comment by Intigracy** [comment]
So what do

**Comment by PJB3005** [comment]
@Intigracy fix `num2words` so it doesn't runtime.

**Comment by Intigracy** [comment]
yuck

**Comment by clusterfack** [comment]
@PJB3005 Are you sure its 19 or 119%? Because as I said it only broke for any multiple of 100 for me between 100 and 1000. I mean I could fix that but that wouldn't be a fix for *this* issue necessarily.

**Comment by PJB3005** [comment]
Whatever it is it's an off-by-one in `num2words`

**Comment by clusterfack** [comment]
Are you sure the issue might not have been with the vox itself? Do you have the runtime log somewhere?

**Comment by PJB3005** [comment]
Yes I have the runtime logs.

http://game.ss13.moe/logs/Dev/runtime/2016-03-08-runtime.log

Search for "list index out of bounds at text.dm:454", the timeframes match exactly with the SME breaking, and the actual runtime is in `num2words`, not the vox code.

Sadly it's truncated to shit due to some MORON putting a try catch in all the processes.
