### ISSUE TITLE
Innate Genetic traits have a chance of causing unrelated genetic damage problems.

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8714]
1.Select a job/race that gets an genetic power at roundstart(Maybe the chef, maybe a grey if they still have mind talk powers), join game
2.Reroll and reroll until you get a genetic defect instead of what you were going to get

I think I already know why this happens, giving someone a SE with genetic powers occasionally gives them a disability instead.
And look at the results.

>% chance of a Grey with no mind reading but a genetic defect
>Bartenders and Chefs randomly come with genetic defects when coming to the station

Why?

**Comment by PJB3005** [comment]
I don't think this is exclusive to Grays or other people that start with disabilities, I'm pretty sure this can happen to *everybody*

**Comment by Imagebard** [comment]
Yeah but what are the chances?

**Comment by Exxion** [comment]
Yes, it's a random chance, totally regardless of whether or not you start with a guaranteed power. If you get it INSTEAD of the power you should get, though, that's an issue.

**Comment by Imagebard** [comment]
>If you get it INSTEAD of the power you should get, though, that's an issue.

Its a issue, then.

**Comment by Intigracy** [comment]
I started with mindreading and seizures today.
If it's intended to randomly get disabilites at roundstart, then this isn't really a bug.

**Comment by Imagebard** [comment]
Okay fuck this
