### ISSUE TITLE
Syringe Gun Filled With Nanobots is a One Shot Kill

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8715]
Nanobots gib in amounts over 5u. A single syringe can hold 15. Ergo, a nanobot syringe gun becomes an instant gib gun, surpassing even the infamous chloral syringe gun in effectiveness.

This of course makes it very easy to fill a backpack full of nanobot syringes and go on an unstoppable murder spree. At least with the chloral syringe gun the murderer has to take some time to murder you while you're asleep.

It also apparently works on dead bodies, meaning you can gib literally anyone at any time, even if they're dead.

**Comment by Exxion** [comment]
Jesus Christ how horrifying

Out of curiosity, what does nanobot smoke do?

**Comment by ghost** [comment]
Ei Nath 2.0, now with more cybernetic zombies

**Comment by BestName** [comment]
Can the Odysseus' synthesizer synthesize nanobots?

**Comment by Shadowmech88** [comment]
Yes, it can.

**Comment by ghost** [comment]
Yes @BestName That's how one antag's new strat is - Make an odysseus at roundstart, take it over to the research station, make some medical nanites, get it to scan it, infinite nanites for either your handheld rapid syringe gun, or the one built into the odysseus itself, and considering the 'OD' amount on nanites is lower than the max capacity of a syringe, this leads to certain problems.

Same duping can be done by a service borg

**Comment by BestName** [comment]
![1420151591516](https://cloud.githubusercontent.com/assets/3892856/13621396/0ecaa82a-e5a0-11e5-8ed3-fd35161a0821.png)

**Comment by AutismSpider** [comment]
Service borg has all the tools to make smoke bomb of this stuff make this even better

**Comment by Shadowmech88** [comment]
@TheEliminator16

**Comment by TheEliminator16** [comment]
Alright, what if we make the mednanobots gib function chance based?
Using them in the recommended quantities will still be perfectly safe, but using them over 5u begins adding to a counter when they heal. Depending on how high that counter is, the chance for gibbing increases.
This would go nicely alongside with the cyber horror buff I've been meaning to put out.

**Comment by TheEliminator16** [comment]
Also it doesn't work on dead bodies.

**Comment by ghost** [comment]
What if it gibbed by-limb or your organs started overhealing and bursting if over 5u with a very slim chance of going cyber zombie, and it gibs you into a cyber zombie if you go over something like 20u

Like you're walking along, somebody hits you with a syringe, and rather than bursting into a robotic zombie, your organic arm rips itself of and your lungs jump out your chest and go walking to the bar

**Comment by Boxe** [comment]
just make them not-gib you below 16 units

please

the fact you can get gibbed with a single syringe(not even a syringe gun, just use a normal syringe with 15 units + harm intent) is the problem

**Comment by TheEliminator16** [comment]
Don't worry, I have changes in mind that should fix the problem.

**Comment by TheEliminator16** [comment]
Forgot to mention it in the PR, but this is fixed now, and can be closed
