### ISSUE TITLE
Borg flash dodge

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8718]
(WEB REPORT BY: yertbogan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 184047863433d58f78e90ce7709fbd5c418cb8ce 
> 
> General description of the issue
> when I had a menu up for placing a reinforced glass pane, I got flashed and stunned, but when I hit ok on the glass placement, I immediately placed the pane and regained full control.
> 
> What you expected to happen
> get stunned for the full duration
> 
> What actually happened
> the stun was canceled by me placing the glass pane.
> 
> Steps to reproduce if possible
> open the menu to place a glass pane as a borg, get flashed, place the pane while flashed.

**Comment by 9600bauds** [comment]
cannot reproduce!
