### ISSUE TITLE
Give xenobotany plants more chemicals.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8719]
The chemicals they contain are nice, but the following are useful chemicals I would like to see added.

Discount Dan's Sauce - despite there being an almost impossible recipe to make it (making it involves grinding all the ghetto stuff like radioactive beans that are in the dan's food in the first place), mass producing the sauce just really isn't a viable money unless you like spending money on vending machines and restocking them.

Silver - Golden apples contain gold when ground, glow berries produce uranium when ground, why not let xenobotany plants have a chance to produce liquid silver?

Black food coloring - The bartender gets very limited amounts of this, and I'm not sure if more can even be ordered. It would be interesting to have plants contain this

Space cleaner - Because why not? We already produce a ton of other weird chems from it

---

Here are the chems bellow ripped from the code that plants have a chance to produce, the higher the number, the more likely you are to get it.

``` DM
//Gives the plant a new, random icon from a list, with matching growth stages number.
/datum/seed/proc/add_random_chemical(var/severity = 15)
    var/list/possible_chems = list(
        // Important Medicines
        "rezadone" = 200,
        "peridaxon" = 200,
        // Items of Botany Importance
        "cryoxadone" = 100,
        "radium" = 100,
        "plasticide" = 100,
        // Items of Botanist Importance
        "hyperzine" = 100,
        "thermite" = 100,
        "synaptizine" = 100,
        "leporazine" = 100,
        "potassium" = 100,
        "plasma" = 100,
        // Misc Medicines
        "bicaridine" = 100,
        "inaprovaline" = 100,
        "ryetalyn" = 100,
        "alkysine" = 100,
        "dermaline" = 100,
        "dexalin" = 100,
        "dexalinp" = 75,
        "hyronalin" = 100,
        "blood" = 100,
        // Misc Poisons
        "cryptobiolin" = 100,
        "mercury" = 100,
        "impedrezene" = 100,
        "stoxin" = 100,
        "cyanide" = 100,
        "neurotoxin" = 100,
        "toxin" = 100,
        "slimejelly" = 75,
        // Fun Things
        "mutationtoxin" = 50,
        "amutationtoxin" = 10,
        "space_drugs" = 100,
        "methylin" = 100,
        "carppheromones" = 40,
        "nothing" = 50,
        "mindbreaker" = 100,
        "minttoxin" = 60,
        // Things of Dubious Use
        "sugar" = 100,
        "ethylredoxrazine" = 100,
        "paroxetine" = 100,
        "tramadol" = 100,
    )
```

**Comment by Exxion** [comment]
I just really really want stoxin2 to be available SOMEHOW

(It puts people to sleep, but also acts as a combination dexplus and a stronger version of inaprov that works on vox, as well as doing a few more things)
(Its description states that it's supposed to also heal damage but it actually doesn't do that)

**Comment by Killette2** [comment]
You mean sophoric that's found in sleepers only?

**Comment by Exxion** [comment]
No, sleepers use regular stoxin
stoxin2 is unobtainable from anything except SCP-294

**Comment by Imagebard** [comment]
>Here are the chems bellow ripped from the code that plants have a chance to produce, the higher the number, the more likely you are to get it.
// Important Medicines
"rezadone" = 200,
"peridaxon" = 200,

Aren't you sure that's backwards?
Am I reading this wrong?

**Comment by Exxion** [comment]
Yes, the higher the number, the more likely
That's why amutationtoxin has a 10 and why dexalin plus is lower than dexalin

**Comment by Killette2** [comment]
Sleepers do not give sleep toxin, it gives a rejuvination chemical, which slightly helps you, cannot be cured by antitoxin, and despite it being "helpful" It still sucks major ass to be under.

Sophoric a monkeyman and use an advanced mass spectormeter to see what I'm talking about

**Comment by Exxion** [comment]
Literally the only reference to stoxin2 anywhere in the entire codebase is its type definition
_Nothing_ gives it
Furthermore, I just looked at the code and sleepers give regular old stoxin

**Comment by 9600bauds** [comment]
> Sleepers do not give sleep toxin, it gives a rejuvination chemical, which slightly helps you, cannot be cured by antitoxin

Fucking botanists never letting go of the ambrosia

You've clearly never had to give a guy antitox to wake him up after another doctor inexplicably thinks "soporific" means "good thing give 20u"

**Comment by Brolaire** [comment]
I'm unfamiliar with amutationtoxin, what is this compared to normal mutationtoxin?

**Comment by Exxion** [comment]
mutationtoxin turns you into a slime person.
amutationtoxin turns you into a slime.

**Comment by Cisrox** [comment]
Yes
