### ISSUE TITLE
Why reagent code runtimes (mostly so I won't forget and try to track this down again

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#8721]
> <Sood> so the reason that reagents get null holder runtimes
> <Sood> all on_mob_life's call ..() before their own logic
> <Sood> the base on_mob_life calls metabolize which removes reagents
> <PJB3005> var/string/fart
> <Sood> when a reagent's total hits 0 in remove_reagent it gets qdel'd
> <Sood> so basically
> <Sood> a reagent can hit 0 and get qdel'd before its on_mob_life is called
> <Sood> not sure how we fix this :V
> <Sood> maybe we should change lifecode?
> <Sood> so that it calls on_mob_life and then metabolize and then we can remove metabolize from on_mob_life

**Comment by 9600bauds** [comment]
PJB has the right idea
