### ISSUE TITLE
ERT don't start implanted

### ISSUE THREAD

**Issue by Zth--** [d3athrow/vgstation13#8723]
which is stupid, they are coming right from centcomm

**Comment by icantthinkofanameritenow** [comment]
Now that I think of it, same goes for Death Squad, which makes even less sense since they're CentComm's special ops team. Why wouldn't they be implanted?

**Comment by AutismSpider** [comment]
both ERT and Death squad don't have implanted both are special teams form centcomm.

This is why ERT is dog shit on cult rounds stun and cult any ert you can get

**Comment by Imagebard** [comment]
@AutismSpider Are you supporting ERT and Deathsquad having implants? I can't seem to make it past through your thick grammar.

**Comment by AutismSpider** [comment]
Deathsquad should have implants and bomb implants ERT just normal implants

**Comment by icantthinkofanameritenow** [comment]
I believe Zth and AutismSpider mean loyalty implants, by the way.

And yes, ERT not having loyalty implants is an issue for cult rounds since it makes them vulnerable to conversion.

**Comment by ghost** [comment]
They should definitely have loyalty implants. This is an oversight, more than a feature request in my opinion

**Comment by Zth--** [comment]
Not only cult rounds, it's also useful for other rounds where you don't know if that guy wearing the ERT suit is legit or if the guy was killed and his suit stolen

**Comment by Intigracy** [comment]
easy fix
