### ISSUE TITLE
Space Fishing

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#8724]
We need it very badly.

Think, you craft a rod with some wood plastic and metal. You get some busta-nuts as bait and cast out your rod into space.

It could use the new bigger z-map. Like randomly generated space ponds where you can fish for some RARE and VALUABLE SHIT.

Fish could be used for decoration, exotic kitchen foods, medicine and oils for medbay. It'd be a ton of fun

**Comment by 9600bauds** [comment]
get goofball to port his fishing ;)

**Comment by TheFriggenSawbones** [comment]
is he a real angler

**Comment by AutismSpider** [comment]
he likes to fish for stuff his bait is A+ though

**Comment by Exxion** [comment]
How would the line work, though? Would the hook just have to be offscreen for everybody for a fish to bite?

**Comment by MusgardTiger** [comment]
We have a grappling gun. Which has a chain you can fire, you can base hooking code on that (maybe, i am code illiterate)

**Comment by Exxion** [comment]
I just meant that it would be weird to be looking at the hook and see a fish spontaneously appear

**Comment by TheFriggenSawbones** [comment]
base it off of Animal Crossing where you yank the fish right into your arms.

space is deep

**Comment by NigglyWiggly** [comment]
base it directly off of animal crossing, but with space instead of water.
The line goes into the space with a little bobber floating up above it

**Comment by Exxion** [comment]
but my emulsions

**Comment by TheFriggenSawbones** [comment]
it'll be so fun

**Comment by Blithering** [comment]
Could sprite an ambiguous, semi-transparent shoal of spessfish, have it as a simple, nonhostile mob, have it wander around until fished.

**Comment by TheFriggenSawbones** [comment]
cash told me to ping people @carshalash

**Comment by AutismSpider** [comment]
Going need a net to deal with space carp and stuff.

Made out of plastic or some thing.

**Comment by robintime** [comment]
although not implemented exactly like this, an in-depth fishing system _is_ currently in the works by GreatBigFailure aka Rubylips
