### ISSUE TITLE
Make conveyor belts copy your dir when built somehow

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8727]
Please

**Comment by Shadowmech88** [comment]
But they're built from machine frames, aren't they? It'd be a little odd.

**Comment by Exxion** [comment]
It would be pretty easy to do, but I agree with Shadowmech that it might not actually be any more intuitive

**Comment by 9600bauds** [comment]
There really needs to be a better way to build these things, doing anything with them is a pain

**Comment by PJB3005** [comment]
Idea:

If you have a multitool in hand, you can click and drag from the conveyor onto another tile.

The conveyor will then take the direction based on that.

No idea how to do corners though.

**Comment by Exxion** [comment]
Corners are not technically necessary, but they do look nice

**Comment by ghost** [comment]
We should just make conveyers not built by machine methods and instead be more intuitive that way.

**Comment by 9600bauds** [comment]
I'm working on something to make setting up conveyors less of a PITA, construction is still bad though

**Comment by Exxion** [comment]
I'm with Celt

**Comment by clusterfack** [comment]
Conveyors should just be an assembly object placed down similarly to a floor tile that sets it dir towards whatever direction you placed it from. Then you just have to wire it or something. 

Tada, easier to build and sets dir.

**Comment by 9600bauds** [comment]
It's very deeply tangled with machinerycode though, so it would need some work to do that

**Comment by clusterfack** [comment]
I'm not saying they shouldn't be machines. I'm saying they should have a special snowflake construction method.

**Comment by 9600bauds** [comment]
Absolutely
