### ISSUE TITLE
Ghosts can spin ghetto cannon

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#8735]
Stop this non sense pls.

**Comment by NigglyWiggly** [comment]
This sounds like a great feature.

**Comment by MusgardTiger** [comment]
it sounds like a bug which renders a feature useless by making it impossible for anyone to use it.

**Comment by Shadowmech88** [comment]
Is the same true for wheelchairs? The cannon is a child of wheelchairs.

**Comment by AutismSpider** [comment]
yup ghost can spin wheelchairs

**Comment by 9600bauds** [comment]
Why is the cannon a child of wheelchairs

**Comment by ihadtoregisterforthis** [comment]
Better a child of wheelchairs than a child of tin cans

**Comment by 9600bauds** [comment]
That's not how it works

That's not how any of this works

**Comment by Exxion** [comment]
Fixed by #8244 if that ever gets merged

**Comment by Intigracy** [comment]
Can close, it got merged.
