### ISSUE TITLE
Items removed from a container via clickdrag onto table have fucked up layers and are visible when blind etc.

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8738]
![dreamseeker_2016-03-09_21-14-27](https://cloud.githubusercontent.com/assets/6526157/13655124/f9ddf4a2-e63b-11e5-9402-f7a1e3fe093a.png)
To reproduce: Clickdrag a container with items in it (must be a container on the floor, not on your inventory) into a table, stab your eyes a lot

**Comment by clusterfack** [comment]
Oh wow, do storage items rely on the layer resetting and such from a mob dropping it to work properly?

Should be fixable by editing on_exit_storage() so that it also contains the same sanitys mob give when dropping to layers and such.

**Comment by Intigracy** [comment]
@9600bauds You see, it wasn't my fault.

**Comment by clusterfack** [comment]
How would it have been your fault in the first place? I made clickdrag emptying (and promptly proceeded to forget I even made it)

**Comment by 9600bauds** [comment]
He made Bag of Holding EMPing just set the content's loc onto the floor without calling remove_from_storage(), which caused a lot of fuck and one of those was this layering issue
His real fault was not enough testing anyways, anyone could fuck up around inventorycode
