### ISSUE TITLE
Halberds. Because spears are getting too big for their boots.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#8739]
Link for sprites: http://s000.tinyupload.com/?file_id=87795730043051064242
That'll show those sticks with the pointy bits but not the choppy bits.
Edit: No longer discriminates against amputees! Missing 1 handed sprites added.

**Comment by Imagebard** [comment]
Do you have sprites for when they aren't being wielded?

**Comment by Blithering** [comment]
@Imagebard 
I would have if I hadn't forgot to add them to the file. I'll update the link in a moment
