### ISSUE TITLE
Taxi modification

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8741]
(WEB REPORT BY: tifora REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 17a967d25e502d7b66d49a9f9e190e557509d3e2
> 
> General description of the issue
> Could taxi be modified to have external airlocks that could serve as start points for inter-station bridges.

I've included a diagram with an approximate location for the ideal place for these airlocks, they should also have an open cable for linking the power grids of all 3 stations:
http://i.imgur.com/IvZCKHI.jpg

**Comment by ihadtoregisterforthis** [comment]
The stations should be further apart in my opinion.

**Comment by Shadowmech88** [comment]
It's certainly possible now that the Z-levels have been expanded.

**Comment by Zth--** [comment]
Can we have retractable bridges? For muh immulsions of course

**Comment by DamianX** [comment]
Taxi is ded.
