### ISSUE TITLE
Fireaxe has no sound when striking mobs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8749]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
Silent but deadly.  Also a big issue since it has an extremely high damage output.

**Comment by Zth--** [comment]
Same with pickaxe. I couldn't find a proper sound for them

**Comment by liltiptop** [comment]
I'll take a look at it. Does the fire axe not make a sound when duel wielded. one hand wielded, or both?

**Comment by Probe1** [comment]
@liltiptop I tested it at time of issue by 2 handing a fireaxe as a test dummy against naked humans.  Chest, head, legs, arm attacks did not result in a sound.  No further testing.

There's stuff all over the place that lack sounds and they really should have them.  But in this particular case, the testing was to evaluate how much stronger a fireaxe is for decapitations (results were 25%-50% faster decaps compared to esword).  

The lethality of a fireaxe demands that it has a sound for it.

**Comment by liltiptop** [comment]
@Probe1 Okay. I'm working on it now.

**Comment by liltiptop** [comment]
Alright. I added a hitsound to the fireaxe. I'm gonna test it out later on my PC at home, and add a few more hitsounds to other weapons. I'll need to do a final test on everything when i'm finished with them all, then i'll make a pull request.

**Comment by AutismSpider** [comment]
D Drill should have some sounds that hits way harder then fire axe but can't decap limbs off

**Comment by Probe1** [comment]
Doin good man.

**Comment by Intigracy** [comment]
close. #8776
