### ISSUE TITLE
No firing sound on lasers if they hit a mob, replaced by hitsound

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8750]
What you expected to happen: _!!PEW!!_ -thud-

What actually happened: -thud-

Steps to reproduce: shoot gun at man, be almost silent, shoot gun at table, _!!PEW!!_

**Comment by ihadtoregisterforthis** [comment]
Noticed this with the spammed eye lasers.
If someone is in hearing range of the shooter but not the victim, does he hear anything?

**Comment by Shadowmech88** [comment]
Just tested locally. Lasers fired at a monkeyman produced appropriate laser sounds.
