### ISSUE TITLE
Mesons allowed me to see a laser shot through a wall.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8755]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/KWFkt3J.png

I was standing here.  I saw a laser shot to the left of me.  The Head of Personnel said that shot was fired at a bear near Hydroponics which is roughly 50 tiles away from engineering.  

Somehow my mesons let me see the laser shot as it hit.  I heard the impact noise when it hit the wall.

**Comment by Intigracy** [comment]
needs more testing

**Comment by clusterfack** [comment]
I don't even see anything here thats testable. He's just poorly describing some weird occurrence he thought he experienced?

**Comment by Intigracy** [comment]
Close when?
