### ISSUE TITLE
Facehuggers just don't give a damn about removing helmets anymore, have learned magic.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8756]
(WEB REPORT BY: blithering REMOTE: 158.69.55.2:7777)

> Revision 17a967d25e502d7b66d49a9f9e190e557509d3e2
> 
> Facehugger bounced off my helmet, didn't remove it, but still managed to hug me instantly. Checked but it was definitely a single hugger.
> 
> What you expected to happen
> Facehugger dies as it hits my helmet as the logs indicated,but removes helmet, second hugger needed to infest.
> 
> What actually happened
> The facehugger leaps at Lenny Webb's face!
> The facehugger bounces off of the the mining hardsuit helmet!
> The facehugger curls up into a ball!
> The facehugger tears the breath mask off of Lenny Webb's face!
> in a single action.
> 
> Steps to reproduce if possible

Put on a hardsuit or similar helmet, stand near an egg.

**Comment by liltiptop** [comment]
Yep, I can confirm that this happens. So how do we want to edit this? Do we want hardsuit helmets to be invincible to facehuggers, or change it to the old way it was? I personally think the old way it worked was fine. It  required xenos to attack people first then drag them back to their nest. But, i'll try to work with what other people want to have.

**Comment by ihadtoregisterforthis** [comment]
![this is fine](https://cloud.githubusercontent.com/assets/13305885/13683169/0a8ad66e-e6e4-11e5-985f-47314d7a7b0d.gif)

**Comment by Brolaire** [comment]
What's the old way? First one pulls off the helmet, second one the mask? I like the idea, genuinely think it's cool, but I feel like that doesn't really solve the problem, everyone's just gonna run around with cardborg helmets. If I remember the movies correctly, one of the facehuggers smashes the glass of a space suit before clinging on to his face. How about just make hardsuit helmets and maybe helmets immune to them, but like, bio suit helmets, space suit helmet, cardborg helmets and anything else that isnt made out of solid metal can be either ripped off or pierced and then facefucked in one go. Maybe that'd be a more interesting approach to this? Maybe it's also too unfair for the aliens, considering there's I think if I did my math correctly 22 hardsuits in total on Boxstation.
I would find it rather interesting if there was some sort of merge of the facehugger-immunity, the facehugger ripping off helmets and facehugger ignoring helmets options.
But that's just my uneducated opinion

**Comment by Imagebard** [comment]
@Brolaire Do you actually play SS13? Huggers were never stopped by cardborg helmets
What the hell are you ranting about, actually?

**Comment by Brolaire** [comment]
> @Brolaire Huggers were never stopped by cardborg helmets

Sorry, I thought they were, it's even why I added

> But that's just my uneducated opinion

Anything else I got wrong?

**Comment by Imagebard** [comment]
>Anything else I got wrong?

Okay here's a small list.

>What's the old way? First one pulls off the helmet, second one the mask? [Helmets are facehugger immune]
How about just make hardsuit helmets and maybe helmets immune to them[They're supposed to be already]
Maybe it's also too unfair for the aliens, considering there's I think if I did my math correctly 22 hardsuits in total on Boxstation.[22 hardsuits is often not enough]

**Comment by Brolaire** [comment]
> [Helmets were never, ever pulled off after hit]
> Sorry but isn't that what's supposed to be happening right now? It happens a bunch to me while mining , where i accidently crack the wall that encloses the facehuggers and one of them jumps at me and rips off my helmet. Did you misunderstand something when I said "pulled off"? Because I'm pretty sure others can also confirm that facehuggers that slam against your helmet rip the helmet off.

**Comment by Imagebard** [comment]
No, I'm pretty sure hardsuit helmets are 100% immune to facehuggers. You could slam 10 facehuggers into a on-station hardsuit and it would not come off.

The only way to explain this is that either mining facehuggers are special, or mining hardsuit helmets can be ripped off by facehuggers, neither of those making sense.
When was the first time a facehugger fucked your mining helmet?

**Comment by Brolaire** [comment]
> When was the first time a facehugger fucked your mining helmet?
> 1-2 weeks ago. I'll do some more testing today.

**Comment by Brolaire** [comment]
I'll be damned.

https://i.gyazo.com/27dcd5fc2b5328a448bc861735862dbe.png
https://i.gyazo.com/5f2e04d195e2cd1fe1341ad8a35e5686.png
Guess I was wrong after all, sorry.

**Comment by gbasood** [comment]
@Imagebard they have a 15% chance of going through rig helmets. That's pretty low in terms of BYOND RNG, at least

They're only 15% instead of full immune until xenos themselves get buffed

**Comment by Blithering** [comment]
At least my 'steps to reproduce field' seems to have worked. Hooray for testing!

**Comment by gbasood** [comment]
Github quotes like to include following lines, so you need an extra line break between a > and non-quoted things
