### ISSUE TITLE
Deff The entire aft hallway has ONE AIR ALARM and it's on the far side

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8757]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
serious pain in the butt to go through 4 sets of firelocks and 75 tiles.  box has like 4 in the central primary hallway for goood reason

**Comment by liltiptop** [comment]
It shouldn't be too hard to add an air alarm or two. I'll see what I can do.
