### ISSUE TITLE
Plasma men tanks

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8762]
(WEB REPORT BY: leon454 REMOTE: 158.69.55.2:7777)
Revision: 2d8d205b09836a52c1269e0a9a2e50cf21b1073d 

Plasma men cannot toggle their own internals, it gives an error along the lines of "you do not have plasma tank!".

Other people can turn a plasma mans internals back on through the stripping menu though.

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Intigracy** [comment]
#8433

#8614
