### ISSUE TITLE
Revenge of the butt bots

### ISSUE THREAD

**Issue by AlphaBuffalo** [d3athrow/vgstation13#8769]
Because we all love when that asshole roboticist makes 6 butt bots, hides them next to an intercom, and spams chat with butt butt butt butt butt butt butt. 

How about prevent butt bots from inserting butt when another butt bot does it, OR prevent butt bots from using intercoms?

**Comment by Probe1** [comment]
I've been thinking about this all day and it's really hard to find a balance point between a bunch of butt bots hidden in maint where no one will ever find them ruining comms, and neutering butt bots.  

There's a lot of ways you could tackle it.  

Make butt bots explode naturally if they reach a threshold of messages per minute.  
Give them a timed life.
Don't let butt bots repeat messages said by other butt bots (this is how spam works)

Who knows.  But it's a deceptively hard thing to balance between still having the griff fun time that we demand and being easily abused.

I WOULD SAY just mute them with a telecomm script but that isn't common knowledge sadly.

**Comment by clusterfack** [comment]
Butt bots already cant say messages from other buttbots, if they could you'd already have an infinite recursion loop.

**Comment by Iamgoofball** [comment]
just give buttbots a global cooldown between butting so that they butt once instead of group butting

that way it only nerfs "5 buttbots 1 room" instead of ruining the rest of the butting metagame

**Comment by FudgePucker** [comment]
You can't use tcom scripts on intercoms or hand radios, only headsets.

Yes this is fucking stupid and should be fixed.

**Comment by Intigracy** [comment]
@clusterfack milestone
