### ISSUE TITLE
Defib lockers interfere with locker closing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8770]
(WEB REPORT BY: acedick REMOTE: 158.69.55.2:7777)

> Revision 7e8c26348d714af0eeb5492306da2966308284f6 
> 
> General description of the issue
> The wall defib lockers will prevent you from closing any other locker or crate that occupies the tile in front of it (both above and below it) and no such error message if you try to close it.
> 
> What you expected to happen
> Tried to close a locker in front of a defib locker, struggled for a bit before testing on a different tile, and it worked just fine. Tested with both the one near cryo and one near chem on boxstation.
> 
> What actually happened
> Locker could not close, had to move locker to another tile.
> 
> Steps to reproduce if possible
> Just place any locker or crate in the tile in front of a defib locker and try to close it.

**Comment by Probe1** [comment]
Thems hows theys works 

Its a container that has been varedited to have an offset of 25 to 35 so it appears on the wall.  It is actually on the tile.  You're trying to open two containers on the same tile which don't werk.
