### ISSUE TITLE
People inside lockers can't use their hands for some reason

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#8772]
Step 1.Enter and close a locker
Step 2.Try putting a item in your pockets in your hands, or something into your pockets, or try something on your backpack.

Why are you unable to pocket things while inside a locker? Why is everything but switching hands disabled while inside a locker? It just makes no sense.

**Comment by 9600bauds** [comment]
Because you're not in a turf and BYOND doesn't like letting you do things while you're not in a turf
Can it be fixed? Probably but Idunno

**Comment by Exxion** [comment]
I'm pretty sure not being able to do stuff while not in a turf is the fault of our code more than BYOND
I could be wrong, though

**Comment by 9600bauds** [comment]
I think the whole issue of ling stasis mode breaking when in a sleeper was a BYOND issue, same principle here but eh I could be wrong too

**Comment by PJB3005** [comment]
@9600bauds the issue you're talking about is verb specific, this issue is our own code.

**Comment by SangriaMonkey** [comment]
This is a pain in the ass to deal with. You can swap items in and out of an inventory slot with a hotkey if you're holding one while inside though. Like a shotgun and a backpack.
