### ISSUE TITLE
Space pod exiting glitch

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8773]
(WEB REPORT BY: boosterrooster REMOTE: 158.69.55.2:7777)
Space pods are unexitable.

Once you enter a spacepod, you are unable to exit it by right clicking the pod and selecting exit or some manner. It only gives the option to enter the pod again, causing the message "this pod is occupied already" to display. If it means anything, I have enter the pod by both the dragging-sprite method and the right-click-enter method. This has happened 4 times from me testing it over multiple rounds.

I would hope a way to exit the pod would be added to the IC menu and/or a "dismount" option in the right click menu. Both would be good to solve this. Another would be just by left clicking the pod.

Created the pod following the wiki instructions and then (over multiple rounds) enter the pod both right click enter and dragging my sprite. After I had entered, I am unable to select any options for exiting it in the right click menu as well as just clicking the pod itels to get off like a normal mountable ride.

Create the pod, get in either by dragging sprite or right click menu, move to test pod to see if it works, right click and see the enter "pod option" and no "exit" option to select, or click the pod itself and try to get out, see that you are unable to exit it.

**Comment by 9600bauds** [comment]
essentially #2945 which was closed for no good reason

**Comment by Intigracy** [comment]
this'll be easy

**Comment by clusterfack** [comment]
Already tried intigracy. 

There's literally no GOOD way to do this thanks to some stupid byond shit: http://www.byond.com/forum/?post=2051263.

**Comment by Intigracy** [comment]
You just have no imagination.

**Comment by Intigracy** [comment]
Will you give me an imaginary dollar if I fix this?

**Comment by clusterfack** [comment]
Only if you fix it by somehow overcoming byond raping us all in the butt
