### ISSUE TITLE
modified atmos hardsuit has no fleshlight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8775]
(WEB REPORT BY: oberoth REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7e8c26348d714af0eeb5492306da2966308284f6 
> 
> General description of the issue
> As title
> 
> What you expected to happen
> Flashlight on modified suit
> 
> What actually happened
> no flashlight on modified suit
> 
> Steps to reproduce if possible
> modify atmos hardsuit with gold kit

**Comment by Imagebard** [comment]
HERE WE GO AGAIN
[Not A Bug]

**Comment by ihadtoregisterforthis** [comment]
Watch closer, the other one was about the lack of a flashlight. This one demands a fleshlight.

**Comment by ghost** [comment]
It's a feeeattuuuure

**Comment by Intigracy** [comment]
someone assign me

**Comment by 9600bauds** [comment]
i cannot

**Comment by Intigracy** [comment]
well since I got downvoted for wanting to fix this, nah.

**Comment by Imagebard** [comment]
A admin said it was intentional and there's code in the golden atmos hardsuit there specifically to make the flashlight go away
Can you close this cap'n Bauds

**Comment by ComicIronic** [comment]
ERP masturbation server when
