### ISSUE TITLE
Broken roburger on Meta

### ISSUE THREAD

**Issue by CyberTropic** [d3athrow/vgstation13#8780]
Eating the roburger that spawns in meta disposals hidden room turns you into a mommi instead of a borg.

**Comment by Killette2** [comment]
This is why you don't eat floorfood

**Comment by Intigracy** [comment]
I'm pretty sure this is intentional seeing as how you don't normally become a mommi through roburgers.

**Comment by Shadowmech88** [comment]
Regardless, we've got MoMMI spaghetti now, so this can be replaced with that.

**Comment by Probe1** [comment]
I take issue with this being called a bug or anything other than hilarious.

Live a little man

**Comment by AutismSpider** [comment]
rename the spawn one into autism burger +new text on it

**Comment by clusterfack** [comment]
A direct result of this line
https://github.com/d3athrow/vgstation13/pull/8581/files#diff-5da7182f398e1fd964dee9d74d475679R2250
Not being of the autist variety
