### ISSUE TITLE
obj/item/weapon/airlock_painter has no icon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8781]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/9yl81gR.png

Its in my right hand.  I only noticed it on the table because I right clicked it.

**Comment by Probe1** [comment]
The obj is located under two cable coils here in the art storage room above the bar on Metaclub.
![image](https://cloud.githubusercontent.com/assets/8550416/13725141/f7f69414-e866-11e5-94c3-b3377d2065ad.png)

**Comment by ghost** [comment]
I doubt this even works.

**Comment by Probe1** [comment]
That's a safe assumption.  Clicking an airlock just made it open.

**Comment by ghost** [comment]
The real issue is that this completely dead, unsupported item is mapped into metaclub, then.

**Comment by Probe1** [comment]
Yes exactly.  I snippytooled the location so whoever gets a bugfix PR open for meta first can remove it.

**Comment by PJB3005** [comment]
Yes I checked this item has no actual code for painting things.

**Comment by CptWad** [comment]
Just remove it then, having it work would just mean the clown rushing it and painting every door into external airlocks

**Comment by Intigracy** [comment]
It used to work though.

**Comment by ComicIronic** [comment]
Is this still an issue?

**Comment by Probe1** [comment]
yes and i'm a little disappointed by that fact.

**Comment by Probe1** [comment]
I took me less time than it took to make coffee, which I did side by side, to fix this.

:disappointed:

**Comment by ihadtoregisterforthis** [comment]
"fix" this

**Comment by Imagebard** [comment]
@ihadtoregisterforthis 
Yeah how dare he fix a item instead of, you know, _coding a whole new item to retroactively fix the unavailability of a item that is present in a alternative map?_ That's _completely_ irrational.
