### ISSUE TITLE
Russian revolver broken

### ISSUE THREAD

**Issue by CyberTropic** [d3athrow/vgstation13#8782]
The Russian revolver has one shot, but whenever you try to shoot at someone you just get endless _click_ no matter how many times you try to pull the trigger. Also mommis can keep trying to shoot themselves with the russian revolver and it will also cause endless _clicking_ without a shot ever being fired.

**Comment by ihadtoregisterforthis** [comment]
See also #8188 which got closed with a commit

**Comment by Intigracy** [comment]
someone assign me

**Comment by 9600bauds** [comment]
i cannot

**Comment by d3athrow** [comment]
doesn't fire at other people because the process_chambered doesn't work for it specifically due to it having nulls in the ammo list.

**Comment by Intigracy** [comment]
thanks, completely forgot to link this issue
