### ISSUE TITLE
Biopunk station 13

### ISSUE THREAD

**Issue by Guestaccess** [d3athrow/vgstation13#8790]
I'd like to suggest we biopunk the fuck out of spessmen.
maybe this is a bit complex for BYOND, and maybe this is a bit 'byond' what can be done with code (ack ack!)

but...
what if xeno organs could be grafted with strange effects, (maybe even a way to mutate specific organs to do specific things like genetics does to DNA?) everything from plasma generation, breathing other atmospheres, enhanced regeneration, increased darkvision, organs that create/release specific chemical cocktails for various purposes, spitting acid, creating a ling-like armblade, hell even organs that allow people to fire taser-like shots or lightning bolts if they can get certain chemicals/grafts to merge into bigger and better stuff! 

What if also, we took a botany-like approach to all the various creatures either scattered about the station or living in the void? Take a chicken breed it and play with its offspring via bluespace/mutagen/the-tears-of-the-clown to lay explosive eggs, or maybe turn it into the raptor we all know lurks in the creatures bones? Stat all (non-sentient) creatures, maybe add the ability to hybridize a bunch of freakish creatures and add the above mentioned "organs on steroids" to form a whole bunch of possibilities

Then add the clowns brain and cry as your creation does nothing more than tell fart jokes.

This would give a reason for Xenobio/Xenobotany to be a (separate) thing from normal botany/bio-research instead of whats currently spess slime farmer 2250 and his trusty NOT!botanist.

**Comment by Exxion** [comment]
The organ thing: 100% possible, at least since the Deus Ex update, though some of those more complex ones (spitting acid, arm blade, etc.) might be a bit difficult (though Goon already has item arms, so maybe we can look into "porting" those)
Genetically-engineering simple mobs: Also possible, but probably more involved to code because simple mobs are currently... well, very simple
