### ISSUE TITLE
Meteor Pens Dont fire meteors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8796]
(WEB REPORT BY: cptwad REMOTE: 158.69.55.2:7777)
thanks dylan

**Comment by CptWad** [comment]
ill watch my own issue
also I think it does fire a meteor it just does not have a proper sprite
it also uses a taser sound when firing which is either new or I just don't remember it

**Comment by AutismSpider** [comment]
pen and gun missing the meteor icons the meteor gun needs better god damn icon

**Comment by clusterfack** [comment]
Good idea, sprite a new one for us yeah?

**Comment by 9600bauds** [comment]
![dreamseeker_2016-12-17_16-35-07](https://cloud.githubusercontent.com/assets/6526157/21289256/cc1d6d6c-c476-11e6-80e8-c043fca7842f.png)
