### ISSUE TITLE
Invisible wall: Box Station

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#8799]
![image](https://cloud.githubusercontent.com/assets/6540760/13728483/f55a7696-e8f0-11e5-94af-203e24a1072b.png)

In the top left, where my ghost stands, center screen, seems to be an invisible wall.

**Comment by Shadowmech88** [comment]
I don't even recognize what part of the station that is.

**Comment by PJB3005** [comment]
@Shadowmech88 It's the bridge, leftmost window.

**Comment by nuklearcellphoneg** [comment]
@Shadowmech88 

Neither did I when I logged in

**Comment by Probe1** [comment]
Can anyone explain what's going on here?  I am pretty sure it's a coding issue and not a mapping one.  In fact, I think it's tied to invisible grilles.  https://github.com/d3athrow/vgstation13/issues/8976

**Comment by nuklearcellphoneg** [comment]
From my perspective I have no idea what was going on, but there was indeed a wall.

Normally it's covered by an rwall. /me shrug

**Comment by ghost** [comment]
Obviously not a map issue but a code issue

**Comment by Probe1** [comment]
Can't reproduce.

**Comment by Exxion** [comment]
Yeah it's been a long time and nobody else has mentioned it
It was probably some wacky-ass one-time thing
If someone encounters it again, open a new issue

**Comment by Intigracy** [comment]
probably the invisible grille issue.

**Comment by Exxion** [comment]
It is a mystery
Too bad nobody VVed the floor to see the contents

**Comment by Probe1** [comment]
nah it was the invisible grille

this was addressed ages ago collaborators are just lazy shits about closing issues.

**Comment by Intigracy** [comment]
if only people would put fixes #numba in their PR
