### ISSUE TITLE
Make emagged beepsky arrest everyone (again)

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8803]
Looking at the changelog, I saw this.

Emagging ED-209s make them laser people. 

which is how it used to be, but now emagging any bot makes it just unlock controls. The request is pretty much in the title, make emagged bots be the craziness they once were.

Beepsky arrested everyone (including the emagger if you didn't run off)
Cleanbot spilt gibs everywhere making a mess
I believe tilebot removed floortiles making hullbreaches, but that seems a bit strong, so removing floor tiles seems fine, again not too sure about what emagged tilebot used to do
Emagged medbot injected anyone, full health or not, great for putting poison in it
Emagged buttbots sprayed poo everywhere, but I don't really care about this one

I don't remember if I covered all of the bots, too lazy to check the roboticist wiki.

**Comment by Intigracy** [comment]
emag them twice
the first time unlocks the controls
the second time emags them

notabug

**Comment by clusterfack** [comment]
You may want to put in a message or something so the players know to do this intigracy

**Comment by Intigracy** [comment]
maybe
