### ISSUE TITLE
voice changers are literally useless and do not hide your face

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8805]
(WEB REPORT BY: termedclepe2 REMOTE: 158.69.55.2:7777)
voice changers do not hide your face when changed to look like bandanas or other full face cover items, in fact they used to always cover your face for identity checks regardless of their projection

they are a waste of tc currently and were nerfed for no reason

**Comment by 9600bauds** [comment]
Didn't you already make an issue on this

**Comment by 9600bauds** [comment]
Unless he means that it does not cover your identity at all even when set to gas mask etc (which it doesn't sound like since he's saying it's nerfed, not bugged) then this is a re-opening of #6890

**Comment by PJB3005** [comment]
He did

**Comment by Imagebard** [comment]
Since neither collaborators closed this Issue, I guess that you noticed this issue isn't entirely the same.
He's talking about just face-covering items now, instead of just things like cigarettes.

**Comment by Intigracy** [comment]
rarely do issues get closed outright

**Comment by FudgePucker** [comment]
Test it.
(Also it didn't conceal my identity as newcop wearing it while turned on as a gas mask, or my voice, leading to the image of me asking the captain for all access at hop desk with my obvious newcop name, ( HE ACTUALY GAVE IT TO ME THE ABSOLUTE MAD MAN (I later managed to pop open a canister filled with the hot loop of the TeG while wearing an atmos hardsuit in his office, only to have my last teammate (the admin who was on the team told me so) RPG me in the face, fun round, we lost and I was able to blame my team 110%)))

**Comment by Intigracy** [comment]
So even as a gas mask it's not hiding your face, you say?

**Comment by Intigracy** [comment]
I just don't understand if this is whining about cigars again or if none of the options are working, and if you won't even take the effort to explain the issue I'm not going to take the effort to test it.

**Comment by FudgePucker** [comment]
Test to see if voice changing masks work
Test to see if voice changing masks work with agent ids
Test to see if round start nukeops can use the mask.
See if it conceals identify when desgised as an mask that normally does.

**Comment by Intigracy** [comment]
nah

**Comment by Intigracy** [comment]
someone assign me

**Comment by 9600bauds** [comment]
i cannot

**Comment by clusterfack** [comment]
Probably something to do with celts flags changes. @drcelt.

**Comment by Intigracy** [comment]
oh celt can fix this then
