### ISSUE TITLE
Nuke ops getting free explosive implants is for no fun BULLIES

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#8816]
It was infinitely better before someone "fixed" their free implants only gibbing them.  Revert it back and let them buy their explosive implants.

**Comment by 9600bauds** [comment]
But it's extremely !!FUN!!

**Comment by Intigracy** [comment]
so much whining today

**Comment by 9600bauds** [comment]
Whining doesn't mean they're wrong.

**Comment by AutismSpider** [comment]
God help people that they need stun lock or sleepy juice them so they don't blow up.

**Comment by clusterfack** [comment]
???

Are people complaining that explosive implants work for nukeops again?

**Comment by Probe1** [comment]
@AutismSpider how are you gonna sleepy juice a guy in a hardsuit and stun locking a guy is pretty dank theorycrafting

Nuke ops was gay because nuke ops always had the upper hand when they lost and took out whatever guy robusted them.

Explosive implants were broken and just gibbed the guy, which was cool since it denied their gear and more importantly headset, but it didn't punish you for not dying first.

Then somebody fixed something that worked better when it was broken.

**Comment by AutismSpider** [comment]
probe when it was broken it made the ones normal antags could buy useless.

not only that what the fuck is a Syringe Gun? or are you just fucking with me or just retarded?

**Comment by ihadtoregisterforthis** [comment]
The broken implant would allow people to mug the near-corpse of the op. It would also drop the headset.

**Comment by Probe1** [comment]
It was infinitely better the other way around for both sides.  This is what you call "Gay shit that makes people hate game modes".

**Comment by FudgePucker** [comment]
Nuke ops aren't overpowered.
You can only win if there isn't a fucking dumb ass on your team, so never.
Do I need to post the green text of how my team fucked up everything and I had to solo it, only for my last teammate to show up and RPG me in the face?

**Comment by 9600bauds** [comment]
> not only that what the fuck is a Syringe Gun? or are you just fucking with me or just retarded?

It sounds like to me that you may just don't know that space suits completely block syringe gun shots.
Otherwise, you would actually see people using syringe guns against newcops in-game.

**Comment by Exxion** [comment]
Let 'em have working explosive implants, but do they really need ones like four times as powerful as the uplink ones? I mean fuck.

**Comment by clusterfack** [comment]
????

How powerful is the explosion? It should just be like a 3x3 tile bomb.

**Comment by AutismSpider** [comment]
same size as fuel tank going off even the uplink ones are the same

@9600bauds they don't block it 100% of the time unless wiz man gem hard suit does not count as one?

**Comment by 9600bauds** [comment]
They do block it 100% of the time. Otherwise, you would actually see people using syringe guns against newcops in-game.

**Comment by Exxion** [comment]
The uplink implants only gib on the same tile and I think don't do anything past three tiles
The op implants are slightly stronger than welderbombs, I think

**Comment by Boxe** [comment]
no

**Comment by d3athrow** [comment]
They have always had the implants, it was changed on baycode because zas and I changed it back.

**Comment by Probe1** [comment]
They have always had implants but until recently, they didn't blow anyone nearby the fuck out and nuke ops was a much better mode for it.

I should not be punished for doing well.  This is not good game crafting.  

Before @Dylanstrategie fucked up the score screens _fixing_ them, you used to get bonus points for arresting newcops.  Which is a sick joke if they're going to explode when you get near.  And you can't exactly put them to sleep without getting near because crybaby wizards demanded hardsuits block syringes so they could murder the crew without getting chloraled.

shit sucks, make them pay to suck shit.
