### ISSUE TITLE
Borers can drag people

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8817]
this is old but apparently it wasn't reported before

**Comment by liltiptop** [comment]
I suppose I could take a look at it, and try to mimic the mouse's ability to not be able to drag shit.
I'll see what I can do.

**Comment by clusterfack** [comment]
But borers don't have any HANDS.

Wait how the fuck are borers even dragging things, even mommis cant drag things.

**Comment by NigglyWiggly** [comment]
> even mommis cant drag things.

But that's wrong

**Comment by Exxion** [comment]
> wasn't reported before

But it was

**Comment by 9600bauds** [comment]
Where tho

**Comment by Exxion** [comment]
Yeah OK fine I'll find it when I get out of bed

**Comment by Shadowmech88** [comment]
I like it, it allows a borer to get out of their host and drag them to safety if need be.

**Comment by 9600bauds** [comment]
I don't like it for that reason
As if pumping you full of chems wasn't enough now they can literally pull you out of crit
This was seen with a borer dragging a ling out of doorcrushing

**Comment by clusterfack** [comment]
Yeah you're right I don't know why I remembered mommis as being unable to drag things seeing as I've used it a billion times. I confused it with some other inane restriction they have, but I just cant remember what.

**Comment by AutismSpider** [comment]
mommis can't click drag stuff like fuel tanks ore boxes etc

they can pull stuff fine

**Comment by clusterfack** [comment]
Thats what it was!
