### ISSUE TITLE
Feature Quest: Medical Borgs with a Medical Upgrade Borg recieve the R&D Surgery Implements

### ISSUE THREAD

**Issue by Kitfox88** [d3athrow/vgstation13#8820]
Or at least condense them all into a switchtool. Muh Inventory Management

**Comment by Ephx1** [comment]
No, fuck off.

**Comment by Kitfox88** [comment]
wow rude

**Comment by liltiptop** [comment]
taking away stuff from the robotocist?
nah fam.

**Comment by Kitfox88** [comment]
as a shitty silicon i must have all the toys

**Comment by liltiptop** [comment]
;Borg law 2 stop asking for shit.

**Comment by Ephx1** [comment]
First mediborgs had no surgery tools
Then they had board to get surgery tools
Then they got a prod to wake people up
Then they were allowed to click drag people into things
Then they got an upgrade that practically allows them to revive anyone from the dead
Now we have surgery tools built-in

Make it a new board entirely or go away. 
I don't usually believe in the "Powercreep" idea, but this is literally it.

**Comment by clusterfack** [comment]
Someone already suggested this I think, we didn't like the idea then either.

**Comment by Kitfox88** [comment]
o ok, rip

WORKSFORME
WONTFIX
