### ISSUE TITLE
Very Critical Issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8821]
(WEB REPORT BY: kitfox88 REMOTE: 158.69.55.2:7777)

> Revision
> c6368b079cce5ebc170956a21a70b02f6efa664e
> 
> General description of the issue
> Jester Suit is titled Jester Duit
> 
> What you expected to happen
> Not to have my immersions ruined
> 
> What actually happened
> I was sucked out of the magical world of spacemen back into my shitty life
> 
> Steps to reproduce if possible
> Read

**Comment by Exxion** [comment]
Dupe

**Comment by 9600bauds** [comment]
Of what issue

**Comment by SysadminJeroen** [comment]
Duit sensors
Op 14 mrt. 2016 15:38 schreef "9600bauds" notifications@github.com:

**Comment by Exxion** [comment]
What the hell
I _know_ this was reported but I can't find it
You win this round

**Comment by Kitfox88** [comment]
Maybe it was fixed at one point then fucked back up somehow?

**Comment by Exxion** [comment]
Searched closed issues too

**Comment by uazuaz** [comment]
this also happens

![pt](https://cloud.githubusercontent.com/assets/6170726/13748493/56f7c18a-e9fd-11e5-8494-94ebf30af0a4.jpg)

**Comment by Exxion** [comment]
That, I believe, is something weird and incomprehensible broken with \icon
