### ISSUE TITLE
Medically analyzed the floor

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8822]
(WEB REPORT BY: kitfox88 REMOTE: 158.69.55.2:7777)

> Revision
> c6368b079cce5ebc170956a21a70b02f6efa664e
> 
> General description of the issue
> You analyze the floor's vitals!
> Analyzing Results for the floor:
> Overall Status: Healthy
> Key: Suffocation/Toxin/Burns/Brute
> Damage Specifics: 0 - 0 - 0 - 0
> Body Temperature: ???°C (???°F)
> Localized Damage, Brute/Burn:
> No limb damage detected.
> Subject bloodstream oxygen level normal | Subject bloodstream toxin level normal | Subject burn injury status clear | Subject brute injury status clear
> Blood Level Unknown: ???% ???cl
> Subject's pulse: ??? BPM
> 
> What you expected to happen
> Analyze myself
> 
> What actually happened
> The floor's pretty healthy
> 
> Steps to reproduce if possible
> Click the floor under you somehow

**Comment by 9600bauds** [comment]
Caused by the clumsy gene

**Comment by ghost** [comment]
Clumsy gene or too much brain damage

**Comment by Kitfox88** [comment]
Oh, I was a clown so that must have been it, I thought it just made you fumble weapons. MY BAD
