### ISSUE TITLE
Feature Quest: Medbots healing you more for whatever medkit they are made out of

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8823]
Considering the mysterious medbot hits you with dex+ and I assume doctors delight, it's odd that the regular medbot goes without some interesting additions

Also why do they use overlays?

**Comment by liltiptop** [comment]
So basically have power ranger medibots?
YES!

**Comment by Exxion** [comment]
But medibots just inject you with whatever chem you put in their beakers

**Comment by liltiptop** [comment]
> But medibots just inject you with whatever chem you put in their beakers

I think what Skullyton meant was to have white medibots give you something like tri, blue medibots give you dex or dex+, yellow give you derma, green give you anti tox, and so on.
Currently, all medibots use internal synths (I think they give DD) unless you insert a beaker for them. I personally like this idea, it gives medibots more of a buff.

**Comment by Exxion** [comment]
Oh right, I forgot about the synths

**Comment by liltiptop** [comment]
I'll try working on it, but i'm not a very good coder. If I get it done, i'll make a PR.

**Comment by Exxion** [comment]
Depending on how bad and hardcoded medibots are, it could be either really easy or... not.

**Comment by ihadtoregisterforthis** [comment]
We need a red trauma medikit to spawn somewhere.

**Comment by clusterfack** [comment]
Sprite the different colored medibots or port them from somewhere else and we'll do this.

**Comment by ghost** [comment]
On it

**Comment by ihadtoregisterforthis** [comment]
We already have the sprites

**Comment by ghost** [comment]
They're split into overlays for some godforsaken reason

Lord knows why, can't be 'sprite bloat', as the named sprites are there (medbotblue, medbotred, medbotgreen) but they're all copies of the same base medbot sprite

**Comment by ihadtoregisterforthis** [comment]
Might be because of the steps to build, those would need every color too.

**Comment by ghost** [comment]
They're the animated sprites (finished product, including injecting)

**Comment by Probe1** [comment]
better make sure they all inject a patient or else there will be trouble when a guy just needs dex but the kelotane one is hogging him by injecting non stop chems he doesnt need.

**Comment by ghost** [comment]
Oh yeah, this can be closed as of the above merge, not sure why it didn't

**Comment by PJB3005** [comment]
@Skullyton you just used the issue number instead of "fixes #issue"
