### ISSUE TITLE
Chefs equipment working without power

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8825]
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> -none-
> 
> General description of the issue
> Some of the chefs machines like fryers and oven work without power
> 
> What you expected to happen
> Not to be able to make deepfried coton candy during a power outage
> 
> What actually happened
> I was able to
> 
> Steps to reproduce if possible
> Try to use chefs equipment while the apc is totally discharged.

**Comment by BestName** [comment]
Maybe they work on gas :^)

**Comment by ghost** [comment]
I sure wish I could be arsed to finish my Kitchen PR

**Comment by Intigracy** [comment]
goof is an idiot

**Comment by d3athrow** [comment]
who would have guessed goofcode is shit code
