### ISSUE TITLE
Spess suits and plasma

### ISSUE THREAD

**Issue by liltiptop** [d3athrow/vgstation13#8826]
So this is a little topic I want to bring up. When there's a plasma flood, all hardsuits (and I think soft suits) get effected by plasma, while the CE's suit and Atmos tech suits do not. Should we have ALL space suits, hard and soft, be resistant against plasma?

**Comment by NigglyWiggly** [comment]
To be honest, yeah, we probably should.
That'd be seen as a balance issue to a lot of people though, so I don't know.

**Comment by liltiptop** [comment]
Atmos and CE suit should still protect against heat, but I just think it's bullshit how one suit protects you from all plasma, and the other does absolutely nothing.

**Comment by Imagebard** [comment]
Get effected by plasma?
You mean contamination?

**Comment by liltiptop** [comment]
> Get effected by plasma?
> You mean contamination?

Basically, yeah. The atmos/CE suit protects your gloves, uniform, and magboots, while all other suits do nothing.

**Comment by Imagebard** [comment]
Contamination should just be removed considered how rare, niche, and hard to understand it is. This is the result of previous arguments about contamination, too.

But I guess that can't be done just now. In that case, as a patch around, I guess all airtight suits should prevent contamination of the clothes you have.

**Comment by PJB3005** [comment]
Really fucking annoying for Vox, because their suits don't block it.

**Comment by Shadowmech88** [comment]
This would somewhat nerf plasmafloods as well, since a space-worthy suit is much easier to acquire than an atmos hardsuit.
A plasmaflooder could still kill everyone by turning it into a plasmafire, though.

**Comment by Kitfox88** [comment]
It's effortless to turn a flood into a fire, yeah. Contamination is super annoying, and it makes no sense for a suit that's spaceworthy and airtight to not protect your shit.

**Comment by liltiptop** [comment]
Cool. I started this discussion just to see if everyone thought what I was thinking. I'll try to make a fix for this, but i'll leave it open for discussion anyway.

**Comment by Exxion** [comment]
R E M O V E
C O N T A M I N A T I O N

**Comment by Boxe** [comment]
you'd have to slap PLASMAGUARD on every suit to do this or something

but at the very least add it to the engineer rigs

makes no sense that engies who work with plasma have suits that don't even block the shit familia

**Comment by Shadowmech88** [comment]
> you'd have to slap PLASMAGUARD on every suit to do this or something

Couldn't you just put PLASMAGUARD on whatever the common parent of all space-worthy suits is? It'd make every existing spacesuit and new spacesuit inherit the flag.

**Comment by Boxe** [comment]
of course

i just really want engineering suits at the very least to have plasma guard

all suits having plasmaguard would be very nice tho

**Comment by Probe1** [comment]
Its specifically designed so atmos suits have guard and engi suits have rad protection.

If you want guard, pick an atmos suit.  If you want rad, pick an engi.

**Comment by NigglyWiggly** [comment]
But that's silly.
Why would they be designed like that

**Comment by Probe1** [comment]
Because we're playing a video game and having trade offs adds depth via decision making.

Engineering, if anything, is easy enough as is and could use some challenge.

**Comment by ghost** [comment]
I think instead of clothes underneath being irradiated, the hard suits themselves should be irradiated if they don't have plasma guard. That way the decontaminating thing makes sense AND they protect you

**Comment by Probe1** [comment]
I am ok with the hardsuits themselves getting contaminated 

I am not ok with removing the poisoning.

**Comment by Imagebard** [comment]
>I am not ok with removing the poisoning.

TRAITOR
BETRAYER
BACKSTABBER

**Comment by Probe1** [comment]
There is nothing wrong with a game being hard and you having to make choices.  If you want plasma protection then grab an atmos suit.  The status quo works just fine.

**Comment by Imagebard** [comment]
As If plasma needed any more buffs as-is.
Tell me Probe1, what is the point of this shoddy, poorly explained mechanic? I fail to see why is so hard and deep about having to remove your shoe and jumpsuit because there's a atmospheric gas contaminating your clothes through just about every airtight hardsuit.

And I say "deep" because you mentioned "having to make choices". You don't "make choices" with atmospheric hardsuits, you out of all people should know that if people have access to atmospheric hardsuits they go and grab one.
And the mechanic IS shoddy, its basically a snowflake code that buffs plasma flooding(So much for contamination making the game harder). Its poorly thought out. Unnecessary. It should have been removed long ago, and you're the only one that thinks otherwise

**Comment by Shadowmech88** [comment]
> shoddy, poorly explained mechanic

How is it any more poorly explained than anything else?

**Comment by Imagebard** [comment]
Its hard to understand. It only happens specifically with plasma floods, and most of the time:
1. People are going blind form standing in the plasma flood.
2. The plasma is on fire
3.They're only watching the plasma flood, and therefore not dying
4.They DID do get their clothes contaminated, and somehow escaped the plasma anyways, they normally don't notice it and die anyways.

So yeah, good luck figuring it out in-game.

**Comment by Shadowmech88** [comment]
My guess would be that the big glaring biohazard symbol on all of a person's clothes might be a clue to the fact that they're no longer safe to wear.
Given that the biohazard symbol is purple and it appeared after they were exposed to plasma in the air, it seems kind of intuitive that the symbol's appearance would be caused by plasma exposure.

**Comment by Boxe** [comment]
i liked it better when ZAS/Plasma weren't set to max all the time

**Comment by Imagebard** [comment]
>the big glaring biohazard symbol on all of a person's clothes might be a clue to the fact that they're no longer safe to wear.

Yeah, that reminds me. We reached the conclusion that contamination should have been removed, but nobody cared to do it, so some coder switched the biohazard symbol on everyone's clothes to a more notable purple. It was meant as a temporary patch-around.
Wherever the fuck did all the contamination lovers come form?

**Comment by Exxion** [comment]
Someone would have to test it, but I'm pretty sure plasma is actually harmless as long as you are wearing internals and eye protection and not wearing a jumpsuit/shoes/gloves. Which makes it ultra stupid that it is harmful when you ARE wearing clothes.

**Comment by ihadtoregisterforthis** [comment]
But then if plasma affected skin directly it would be extra hazardous.

**Comment by Exxion** [comment]
But it obviously _should_, as long as contamination works as it does now
Are you suggesting it's only harmful upon contacting clothing?

**Comment by Boxe** [comment]
ERPers have the upper hand in plasma survival

it's stylistically designed to be that way

**Comment by Shadowmech88** [comment]
You might be able to remove the [Unfulfilled Feature Requests] tag, all spacesuits *do* now block plasma.
Though, non-PLASMAGUARD suits still become contaminated themselves, so I'm not sure whether it counts as fulfilling this.

**Comment by Probe1** [comment]
This wasn't the only feature request closed today that had actually been resolved in some other PR at some other date but fuck we have so many issues and no one reads past the first two pages.
