### ISSUE TITLE
Missing girders when deconstructing Rwalls

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8832]
(WEB REPORT BY: blithering REMOTE: 158.69.55.2:7777)

> Revision 757919995cf0fe322e0b4f12842fc570cf21dab5
> 
> General description of the issue
> When you deconstruct a reinforced wall, at the step where the wall would be reduced to a reinforced girder, it doesn't appear, making deconstruction time lower, and messing with the creation of (buggy) reinforced false walls
> 
> What you expected to happen
> Wall reduced to girder.
> 
> What actually happened
> Wall reduced to nothing.
> 
> Steps to reproduce if possible
> Deconstruct a reinforced wall.

**Comment by ihadtoregisterforthis** [comment]
Deconstructed or destroyed, you'll need extra metal to fix a breach on one of these.

**Comment by 9600bauds** [comment]
This is a bug

**Comment by clusterfack** [comment]
Unable to reproduce
