### ISSUE TITLE
Why is there a Biohazard warning under a table in the Ghetto Library of Defficiency 

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#8835]
Why is it there

**Comment by Kitfox88** [comment]
F U C K
D U N Y

**Comment by PJB3005** [comment]
DUNY DID NOTHING WRONG.

**Comment by Probe1** [comment]
I know this one because I asked the other day.  It's to show that part of maint doesn't protect against rad storms.  Or maybe the opposite.

**Comment by Killette2** [comment]
Because the map is a biohazard

**Comment by Probe1** [comment]
We need better icons to convey that they are not shielded.  Spriting issue.

**Comment by Konater** [comment]
they were added to the map with pixel varedits and were getting reset
