### ISSUE TITLE
[Deff] Permabrig-esque area with Permabrig-esque botany and Permabrig-esque kitchen not actually Permabrig

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#8839]
I put an assistant in it, thinking it was Permabrig, and he just walked right out.
What the fuck @Duny-?
You mean you've made this system for Permabrig prisoners to actually do something with their time by serving other prisoners, and IT'S NOT FOR PRISONERS?

**Comment by ihadtoregisterforthis** [comment]
That is a public area for whoever wants to cook for the inmates.
Not a bug

**Comment by 9600bauds** [comment]
I know it's not a bug, but it's retarded. There is no actual Permabrig, and it lets prisoners escape from the courtyard by tabling each other (they even get a side exit away from Brig!)

**Comment by FudgePucker** [comment]
Permabrig should be able to be broken out of, putting away murderboners and grayshits makes the round boring.
~~fuck~~Thank you duny.

**Comment by 9600bauds** [comment]
I meant that it's extremely easy to break out of, using that strategy

**Comment by FudgePucker** [comment]
Psst, hey,
I was being sarcastic.
Permabrig should be PERMAbrig
You should need to have someone heavily armed kill everyone in security to break you out, or have someone with space gear break you out, not another inmate table you.

**Comment by 9600bauds** [comment]
You can actually escape permabrig rather safely even without space gear, or you used to be able to before hypothermia. I'm fairly sure you still can, though.

**Comment by Imagebard** [comment]
Can you please screenshot this "permabrig"?

**Comment by FudgePucker** [comment]
If you mean by smashing though four sets of windows though the main part of brig then yes, but that would require none being in brig or near it.

**Comment by 9600bauds** [comment]
![firefox_2016-03-15_14-24-28](https://cloud.githubusercontent.com/assets/6526157/13787182/a6356db2-eab9-11e5-87f7-5719e12e169a.png)
It's like a permabrig, except it's not

**Comment by Imagebard** [comment]
![ohwhatthehell](https://cloud.githubusercontent.com/assets/7571238/13787342/55f09646-eaba-11e5-9807-7eeccb1d7b64.png)

That's the nromal brig area you fucking idiot. Did the jail cells with timers on them not tip you off or something?

**Comment by PJB3005** [comment]
@Imagebard that IS the permabrig.

Deff's permabrig is also the normal brig.

**Comment by 9600bauds** [comment]
> Permabrig-esque area with Permabrig-esque botany and Permabrig-esque kitchen

yes clearly I must be talking about the place with the jail cells and timers on them which has neither a botany area nor a kitchen

**Comment by Imagebard** [comment]
Funny that, when Duny- made that map...
I don't remember any comments about THAT being the permabrig.

More like, people thought it was a playing area for people that were jailed. The Warden could set them here and they weren't confined to a 3x3 room.
If that's not the case, then I might have to open another issue.

**Comment by 9600bauds** [comment]
I'm talking about the thing on the back
It has a kitchen and a botany room much like a permabrig
but you can't use it as permabrig
which brings to attention the fact that there's no actual permabrig
The obvious solution is to make the not-permabrig into a permabrig

**Comment by Imagebard** [comment]
I'm trying to wrap my head around what you are implying.
9600bauds, do you mean THIS area?

![0000](https://cloud.githubusercontent.com/assets/7571238/13789951/060ff0f8-eac5-11e5-82d8-6d7f1992e36c.png)

**Comment by FudgePucker** [comment]
Maybe have a security shuttle that goes to the middle of space to a maximum security mining outpost. It is surrounded by two rwalls out in space, an asteroid area (no mobs) for them to mine out, a kitchen and botany area, fully stocked,  a security area for entering and exiting, comes with a system for CO2 and plasma flooding of the entire complex outside the security area, for if the prisoner is armed, wall flashes everywhere, a stocked medical area that could also be used by security to fix themselves up incase of revs or cult in medbay, and some other features. The only o2 tanks have to be provided by security (for if you want to be able to n2o flood).
The only way to call the shuttle is from the main station or the shuttle itself.

It would be harder to break out of than box brig, but would also have less survalence and more possible tools for excape. You can use xenobotany to try and make chems to excape, you can use xenoarch to get weapons, and you might be able to with enough effort and smarts make one tank bombs.

**Comment by Probe1** [comment]
Here's what we're gonna do.

We're gonna 

# Bring Back the Gulag

**Comment by Duny-** [comment]
>people don't instantly suicide when they are brigged on deff since there is no real permabrig (which is intended), how can we fix it?

>I know! Make it harder to escape and even more boring than box's perma

Doesn't the kitchen door require some kind of access? If not then that's an easy fix to your problem.

**Comment by 9600bauds** [comment]
Permabrig is infinitely more fun than a jail cell though, that's the point
It has stuff to do and is more interactive than two tables and some dice that you are probably completely alone with

**Comment by Imagebard** [comment]
>there is no real permabrig (which is intended)

**Comment by Probe1** [comment]
GULAG COMRADES

**Comment by PJB3005** [comment]
GULAG

**Comment by Duny-** [comment]
>Permabrig is infinitely more fun than a jail cell though, that's the point
>It has stuff to do and is more interactive than two tables and some dice that you are probably completely alone with

Easy then just add fun things to do in the big ass recreation room next to all cells made for this specific purpose

**Comment by 9600bauds** [comment]
Okay, you do it

**Comment by Imagebard** [comment]
Having to pass through a area with *permabrigged* prisoners(which could try to slip or disarm you) to arrest normal prisoners is a huge security flaw.

**Comment by Duny-** [comment]
IRL prisons do just that and are doing fine, looks like you need to git gud. You have several tools as a warden or security officer to make sure that doesn't happen.
Allowing prisoners to rely on human error to escape is much better design than having prisoners invariably kill themselves because they can't escape and nobody ever checks on them, or break the window and run/die.

@9600bauds Sure I'll just make the public botany jail botany instead and it'll be like box permabrig.

**Comment by Imagebard** [comment]
>IRL prisons do just that

Are you kidding me.
First, this isn't real life. You can't punish someone on permabrig that tries to slip you like you can in real life.
Second, you often CAN escape the permabrig. Only bad players such as FudgePucker and goofball try to get escape routes removed, and they never succeed.

**Comment by Duny-** [comment]
Then why are you trying to remove deff's escape route which in my opinion is FAR better than just waiting for the warden to leave and breaking the window?
And sure you can, throw them in a cell for half an hour if you lack imagination.

**Comment by Imagebard** [comment]
>Then why are you trying to remove deff's escape route which in my opinion is FAR better than just waiting for the warden to leave and breaking the window?

You mean the escape route that merely requires you to get tabled?
Yeah, nice escape route. On box you have to break off through space.
Are box"babies" really more hardcore than Duny-? Was I wrong all along?

>And sure you can

Whatever I do, It'll make the game more interesting for them. Helping them out of the bland boredom that is the permabrig is the worst thing I can do.

**Comment by Duny-** [comment]
The table thing is an oversight I will fix, I'm talking about relying on security fucking up when putting someone in a cell.
