### ISSUE TITLE
Derelict Atmos APC

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8845]
(WEB REPORT BY: menacingfork REMOTE: 158.69.55.2:7777)

> Revision fc8295744bc9e447bf00d9885aa8f062dfcb99f9 
> General description of the issue:
> The game thinks there's a apc in derelict atmos, even though there ain't.
> 
> What you expected to happen:
> Me building an APC.
> 
> What actually happened
> Me unable to build apc. Tears and screaming followed.
> 
> Steps to reproduce if possible
> Make a apc frame, try to slap it on the wall. Cry when it doesn't work.

**Comment by PJB3005** [comment]
What map.

**Comment by Probe1** [comment]
Box.  Ive seen ahelps before

**Comment by PJB3005** [comment]
Weird because I'm 100% sure I've done it in the past.

**Comment by clusterfack** [comment]
I have as well, perhaps there is a messed up tile that has the wrong area there. Or perhaps someone had already built an apc there. 

We may never know thanks to it being a shitty web report.
