### ISSUE TITLE
Brawndo should damage plants

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8866]
Brawndo is ripped straight from the movie Idiocracy, but nowhere in the botany code I saw did the chemical "sports drink" damage plants. Here is the video explaining everything

https://www.youtube.com/watch?v=VBML3VpbuYQ

It even uses the word botanist

**Comment by NigglyWiggly** [comment]
That makes no sense, Brawndo has what plants crave.
It's got electrolytes.

**Comment by ghost** [comment]
But it's what plants crave?

**Comment by IratePirate** [comment]
Like out the toilet?

**Comment by Shadowmech88** [comment]
Brawndo acting as plant fertilizer when?
It's what plants crave, after all.

**Comment by FudgePucker** [comment]
It should heal plants, cause beneficial mutations, and water them.
Its got what plants crave.

**Comment by FudgePucker** [comment]
#8886 THERE I FIXED IT GUYS.

**Comment by Killette2** [comment]
This is the opposite of what I wanted, but this works too
