### ISSUE TITLE
when replacing organs, the new organ has the same damage of the old one

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8867]
i don't know if this happens every time because usually i just mend organs instead of replacing it, but tonight i saw a guy replacing a liver to a vox and the new liver had just the same damage of the old one; i also heard about this bug in ghost chat some time ago.

**Comment by uazuaz** [comment]
i just made some test on the test server, i created some monkeymen, intoxicated them to damage their liver and replace it; i used 2 normal livers and 1 mechanical liver and i wasn't capable to reproduce this issue;
then, i tried to leave around 30 toxin damage before replacing the liver; during the surgery, toxins raised and at the end i had about 70 toxin damage and raising, so the new liver started to take damage as soon as the surgery ended.
so, it's very likely that the surgeon i saw just forgot to heal the toxin damage before replacing the liver, so the new liver taken toxic damage as happened to me.
maybe you know something else that you can test, otherwise you could just close this issue.
sorry if i bothered you with a false issue, next time i'll test before i open it.

**Comment by 9600bauds** [comment]
debunked
