### ISSUE TITLE
Mimics.

### ISSUE THREAD

**Issue by NigglyWiggly** [d3athrow/vgstation13#8870]
Killing a mimic leaves a copy of the original object in its place.
This applies to all mimics.
Including human mimics.

You can create a mimic of yourself and kill it to create a new human mob.

**Comment by gbasood** [comment]
Duplicate your:
- bombs
- eswords
- goonecode

**Comment by NigglyWiggly** [comment]
You cannot duplicate anything, it doesn't spawn a clone of you, it spawns a new human mob.

EDIT: You can however use this for free genomes

**Comment by gbasood** [comment]
But if an item mimic leaves a copy of the original object
And item mimics mimic an object we don't want to duplicate
couldn't you use it to duplicate non-mobs?

**Comment by Intigracy** [comment]
When you create the mimic, the old object is deleted isn't it?

But making one of a mob doesn't delete the mob when it spawns the mimic, and then it spawns a naked mob when it deletes the mimic.

**Comment by NigglyWiggly** [comment]
Correct.

**Comment by gbasood** [comment]
Oh I see now. Should be an easy fix.

**Comment by Intigracy** [comment]
Should just not let you make mimics of mobs. The entire point of mimics is that it's an object that's alive.

**Comment by ihadtoregisterforthis** [comment]
Are beings not a kind of object?

**Comment by Intigracy** [comment]
You're turning something alive into something alive fam.

**Comment by ihadtoregisterforthis** [comment]
You are taking the shape of something alive to reshape something alive
