### ISSUE TITLE
Meta, atmos entry room lacks a scrubbadub scrubber

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8879]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/Eql0sPS.png

3 atmos techs in a tub.  Plasma goes blub blub blub.  Without their glubs and stuck in the tubs, it needs a scrub scrub scrub.

**Comment by Intigracy** [comment]
leg so hot
hot hot leg
leg so hot you fry an egg

**Comment by Probe1** [comment]
BOO THIS MAN

**Comment by FudgePucker** [comment]
11/10 issue report

**Comment by liltiptop** [comment]
BOO!
