### ISSUE TITLE
The "trigger lights out" event button in the secrets panel isnt working

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#8884]
Be badmin
Open the secrets panel
Hit the "trigger lights out" event button
Watch nothing happen.

**Comment by Zth--** [comment]
Rip event. It's a shit button and I hate it

**Comment by Probe1** [comment]
we're talking 'break all the lights' right

that is a shitty button.  it can be useful during SPOOKYBUS but never outside it

**Comment by mrpain666** [comment]
No. The button in the secrets panel that matches the title of this issue.

**Comment by mrpain666** [comment]
Im also pretty sure this event fires just fine randomly on its own.

**Comment by PJB3005** [comment]
Isn't lights out the event where all the light fixtures around an area pop? 

I can't recall seeing that in a long time.

**Comment by mrpain666** [comment]
Oh I dont know then, I thought this was the power grid failure thing.
