### ISSUE TITLE
Mech Wormhole Gen, unable to pass through own wormholes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8887]
(WEB REPORT BY: tokanova REMOTE: 158.69.55.2:7777)

> Revision c56dcbec0c1bd28d8a1728d7317f1c1ccda6cca6 
> 
> General description of the issue
> Unable to pass through own generated wormholes while in mech
> 
> What you expected to happen
> Being able to pass through wormhole to random destination.
> 
> What actually happened
> Mech moves over wormhole
> 
> Steps to reproduce if possible
> Create Ripley
> Attach Wormhole generator to Ripley
> Create wormhole
> Try to enter Wormhole while in mech

**Comment by FudgePucker** [comment]
Obviously the mechs are too large to fit into the wormholes.

**Comment by Kitfox88** [comment]
requesting IT'S A FEAAAAATUUUUUUUUURE tag

**Comment by Killette2** [comment]
I saw this bug happen once with the space pod mech but didn't report it because I thought it was just only a bug with that shitty pod mech. But yea, mechs no longer go in wormholes, but they used to. Why do code keep breakening?
