### ISSUE TITLE
Beef up Admin Who with some player stats

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#8888]
Have a look at this.  You know there's no single place that counts and tallys useful information to admins like how many players are alive, how many are observing, how many are antagonists et cetera.  Could we add those numbers at the bottom of admin/advanced who?  Counting every time really sux.  It's not so bad right here in an issue where you have nothing to do.  In game though, the chat logs jumping and you're trying to count asap to find the data you need, and its generally a pain.

![dreamseeker_2016-03-16_10-39-07](https://cloud.githubusercontent.com/assets/8550416/13852998/235d7528-ec3b-11e5-8b27-9d9f06ceea9e.png)

**Comment by Iamgoofball** [comment]
#8888

**Comment by ihadtoregisterforthis** [comment]
Any undercover giganigga is killed.

**Comment by Probe1** [comment]
![guys stop acting like 4chan on 4chan](https://cloud.githubusercontent.com/assets/8550416/13861840/ea2c8f34-ec65-11e5-8b56-72c27f7cea54.jpg)

**Comment by gbasood** [comment]
Example of what I'd personally like to see:

> Living players: 16 Ghosts: 45

Maybe even

> Living antags: 3

If you want to get crazy

**Comment by Probe1** [comment]
that's the gist of what I'm asking for yeah.  Its pretty cool to imagine having lots of data like how many security members there are, and assistants, and people with antag roles enabled (filterable for antag types) and just all sorts of neat ideas we could come up with. . . 

But that's basically all I need here.  "How many people are alive, dead, and antags.

**Comment by MusgardTiger** [comment]
I need this and i don't know ho to give a thumbs up

**Comment by gbasood** [comment]
click the smiley face with a plus next to it on the OP
or click the thumb
