### ISSUE TITLE
Secure Briefcase in Salvaged Shuttle unopenable [Boxstation]

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8890]
I noticed that the Secure Briefcase on the Salvaged Shuttle is not openable at all because the keypad for the code input does not respond when using it. I tried to open it by hacking and with the help of a admin. Both did not work. This was on Boxstation.

**Comment by ghost** [comment]
It's called secure for a reason.

**Comment by Exxion** [comment]
Huh. Worked last time I tried it, but that was long ago since I discovered it didn't contain anything useful

**Comment by Intigracy** [comment]
Is it just that one or every one?

**Comment by gbasood** [comment]
Why do we even HAVE secure briefcases if they exist to be unopenable

**Comment by Exxion** [comment]
They don't
Everything with "secure" in its name can be easily hacked with a multitool
It's an old, long-standing joke

**Comment by ghost** [comment]
> Is it just that one or every one?

Did not test other ones yet, but I remember that I used a secure briefcase for a test once some time ago. That one worked, both hacking and using a code.
