### ISSUE TITLE
New xenobotany gene - falling fruit

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#8891]
What I want is pretty simple. Like how apples fall from a tree, plants with this gene will harvest themselves falling on the tile of the plant if not harvested after a certain amount of time. I would also allow this to be applicable to vines, allowing vines to be self harvesting like they used to before more recent changes from botany2 to botany3.

Whether this becomes a new gene, or gets mixed in with another group as some groups are mixed, is up in the air for discussion. Let's see what we should do with this idea.

**Comment by Senaat1** [comment]
looks gay

:+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Killette2** [comment]
Are you implying that's a bad thing?

![1450327033343](https://cloud.githubusercontent.com/assets/5169310/13857060/87da0ff8-ec4e-11e5-9af1-70261b87783a.jpg)

**Comment by ghost** [comment]
Killette has a good idea for once? I don't believe it.

**Comment by Killette2** [comment]
Looking at the xenobotany guide here, http://ss13.moe/wiki/index.php/Guide_to_Xenobotany I say the only two genes this idea would remotely fit under is morphology or development. Seeing as development involves production and maturation times, I would not want it there, so this becoming a new gene or being mixed into morphology is probably the best choice of action, as morphology is a gene where you often splice instead of purge genes, such as thorniness or slippeyness.

Also my ideas have always been solid, for example the itching idea, but the fact is this. No matter how good of an idea something may be or how much sense it could make in gameplay, like babies being orderable from cargo or itching skin, if it has any tint of weirdness to it then it is unlikely to be added.

Since this is botany related, I actually want this to be put in.

**Comment by Exxion** [comment]
Most of Killette's botany-related ideas are good

**Comment by ihadtoregisterforthis** [comment]
This is so good you revived senaat

**Comment by Senaat1** [comment]
> revived

this is just a shitpost from beyond the grave my good lad :100: :+1:

**Comment by Killette2** [comment]
When (you) code it

**Comment by robintime** [comment]
autoharvest was added in #19303 🙏
