### ISSUE TITLE
Let player possesed mobs cast spells

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#8904]
Currently only carbons can cast spells and there is a sea bus potential with that shit.

Make it happen, make vvvggg great again!

**Comment by PJB3005** [comment]
I remember an admin giving the same type of creature the wizard has some spells.

**Comment by clusterfack** [comment]
Does it give you some message in particular when you fail to cast a spell as a non carbon?

**Comment by MusgardTiger** [comment]
It says only humans or wizarda can cast spells silly or something along those lines. They can cast smoke and few others but they can't do most of the spells in the spellbook.

**Comment by clusterfack** [comment]
Well a specific message would have been more useful in cntrl f-ing the code that blocks it and tearing it out

**Comment by MusgardTiger** [comment]
I am not home at the moment but if you don't check it out until I return I'll post it here.

For those who want to try just give a player possessed corgi spells like jaunt or something like that. You'll get the message.

**Comment by MusgardTiger** [comment]
Okay this is the message you get when you try to cast a spell as a simple mob:

"Silly creature, you're not a human. Only humans can cast this spell."

**Comment by Exxion** [comment]
?????????
Whose bright idea was that? There's no reason for it. Just don't give things spells if you don't want them to cast the spells. Don't limit the adminbus.

**Comment by ihadtoregisterforthis** [comment]
Humans as in humanoids or as the specific race?

**Comment by NigglyWiggly** [comment]
Humanoids

**Comment by MusgardTiger** [comment]
@Exxion it is probably left over from bay. 

if not find who did it and hang him by his tippytoes.

**Comment by clusterfack** [comment]
It was almost certainly comic considering he redid all spellcode

**Comment by Intigracy** [comment]
Some of them are like that by necessity.

Such as mutate.

**Comment by ComicIronic** [comment]
This has been in the codebase a lot longer than I have been, and did not come from the spell rework.

It's caused by mobs not wearing wizzyclothes by default:

```
/*Checks if the wizard is wearing the proper attire.
Made a proc so this is not repeated 14 (or more) times.*/
/mob/proc/wearing_wiz_garb()
    to_chat(src, "Silly creature, you're not a human. Only humans can cast this spell.")
    return 0
```

Unless we want to enable all mobs to cast wizclothes spells, this isn't going to change.

**Comment by Shadowmech88** [comment]
So does that mean that a non-human mob with the no-robes spell would be able to cast spells as normal?

**Comment by ComicIronic** [comment]
Yes. It also means that, as Musgard correctly noticed, all mobs can cast no-robes spells like Smoke.

```
var/spell/noclothes/spell = locate() in user.spell_list
if((spell_flags & NEEDSCLOTHES) && !(spell && istype(spell)) && holder == user)//clothes check
    if(!user.wearing_wiz_garb())
        return 0
```

**Comment by Shadowmech88** [comment]
I feel like the best solution would be to bypass the robes check for non-carbon mobs. After all, the only way a simple_animal is going to get any spells is via adminbus, I don't see why they should need the no-robes spell as well just to be able to cast them.

**Comment by Intigracy** [comment]
Or you can just properly set the robes required var when you give them the
spell.

I don't remember the specific name.

**Comment by ComicIronic** [comment]
It's not a var, it's a flag.
