### ISSUE TITLE
Where I rag on the general fabricator over the course of a week to find all its flaws

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#8913]
Now, I'm not going to complain about the whole 'Oh it costs too much to make a compressed matter cartridge', but when it takes 5 whole minutes to make 1 cartridge on plastic-level parts, it's getting a bit ridiculous

EDIT - Turns out the time it takes to make anything, even knives, is severely bloated compared to the autolathe (took about 45 seconds per knife on plastic parts)

FURTHER EDIT - Parts that contain plastic, such as a pico manipulator, cost 360 plastic AND 360 additional plastic

![What the fuck](http://i.imgur.com/Sgmz0BQ.png)

EVEN FURTHER EDIT - You can apparently go into defficiency in a material if the cost of an item is more than what you have, but you still have some of that material, either that or the cost of a pico manipulator is apparently 20 plastic

General fabricator with pico manipulators, UHP micro lasers, and advanced matter bins - 5 minutes, 36000 iron, 18000 glass, 5600 plastic

Autolathe with micro manipulators and advanced matter bins - 4 seconds, 45000 iron, 22500 glass

It needs poking, or a functionality revamp (Being able to make multiple fabricators all linked to one blueprint server save having to go around each genfab and load it up individually if you want certain blueprints to be limited, and maybe even some way to have them all linked to one resource cache through bluespace crystal-tier upgrades)

**Comment by Imagebard** [comment]
Thanks Comic.

**Comment by PJB3005** [comment]
Fuck the gen fab tbh.

**Comment by Exxion** [comment]
The genfab is a neat idea, but basically every part of its execution is bad

**Comment by icantthinkofanameritenow** [comment]
So now with the biogenerator being able to make shoulder holsters, there's one less reason for anyone to even consider using the general fabricator. Why does it even exist at this point except to let traitor mechanics make a fuckton of guns? 

It either needs a massive overhaul or outright removal now.

**Comment by 9600bauds** [comment]
"Mechanics were a mistake" -Comic

**Comment by ComicIronic** [comment]
I did make an oversight in the genfab code which was that it assumed designs contained no plastic because they aren't really  meant to because it's a mechanic-only material. Whichever cleverclogs made the terribad idea of plastic tier 3 parts can eat the shoe on that one.

Also forging which would actually make the genfab worthwhile never.

**Comment by ghost** [comment]
Here's what I have to say - Stop adding shit to the protolathe.

Make it so you can draw out blueprints that could be something with less resource cost, or something highly fucking experimental

Heck, add some form of alien tech that can only be reproduced via general fab and blueprinting.

**Comment by icantthinkofanameritenow** [comment]
I'd support the last one, but all the alien tech we have is either 

*Guns (traitor mechanics only)
*Reskins of other items that you can already make
*Outright useless
*Impossible to scan

**Comment by ghost** [comment]
Soon™

I've got plans for after cybernetics

**Comment by clusterfack** [comment]
Well we could start adding things like better tools to do things more efficiently to make some more dynamic interactions (like vox raiders buying/selling them), but I can say without a doubt that if we added such tools currently they would end up being placed on the map and powercreeped into the game.
