### ISSUE TITLE
Deff cryo is not functional

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#8914]
Revision: f85d04563b9941f6f64e76cd43a2efc019055a70
This is not the current revision. I'm testing this on a local server, and it was brought to the then-latest revision earlier today.

Deff cryo currently looks like this:
![ss 2016-03-19 at 12 04 24](https://cloud.githubusercontent.com/assets/5942183/13894276/60bdfccc-ed66-11e5-90b9-af5946134f01.png)

I believe it previously looked like this:
![ss 2016-03-19 at 12 07 41](https://cloud.githubusercontent.com/assets/5942183/13894312/a558362c-ed66-11e5-8670-2f685a242dab.png)
I'm not sure, though.

Neither work, as there's no gas being cooled. Optimally, it should be a manifold facing the bottom O2 canister.

**Comment by ghost** [comment]
inb4 blame NotDuny

**Comment by ihadtoregisterforthis** [comment]
Blame notDuny but it was already fixed

**Comment by Kammerjunk** [comment]
It was? I tried to search through commits and PRs but I couldn't find anything about it.

**Comment by ihadtoregisterforthis** [comment]
#8406 closed by #8407

**Comment by Kammerjunk** [comment]
Oh, I see. This issue is much newer than a month because I guess Deff just keeps breaking, but I see Segi made a fix.

**Comment by Killette2** [comment]
Ummm what the fuck is this? That volume pump there will do nothing. There's no gas for the freezer to cool as the oxygen tanks come AFTER the pump. What is it pumping in there, the little amount of air that's in the freezer? Remove the pump and place it with a regular pipe, there's not even a need for a pump to be involved in cryo anyways.

Edit: I didn't actually read until after I posted, I thought this was a before or after. Yes a manifold would fix this.

**Comment by MrSegi** [comment]
> Ummm what the fuck is this?
> 
> Neither work, as there's no gas being cooled. Optimally, it should be a manifold facing the bottom O2 canister.

Kammerjunk was saying that both of those setups do not work, not that the bottom setup is correct.

**Comment by Killette2** [comment]
Read the edit. It was posted before you did and the github updates live so you didn't even need to refresh for the edit to appear.

**Comment by PJB3005** [comment]
What the fuck I just fixed this.
