### ISSUE TITLE
/obj/item/weapon/dnainjector/nofail/hulkmut can't be used

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#8919]
Click yourself, it does nothing.  No injection.  @ArthurDentist placed one in his vault and its bupkis.

It is directly tied to injectors placed on the map.  Injectors spawned in or created mid round will work fine.

/obj/item/weapon/dnainjector  is the bad mapping path and
 /obj/item/weapon/dnainjector/nofail/hulkmut  is the working spawned in mid round path

**Comment by Arthurdentist** [comment]
this isn't because of my PR by the by, I didn't edit any of the injectors.

**Comment by Probe1** [comment]
I'm aware, it was a heads up not an indictment.

**Comment by clusterfack** [comment]
Limited to just this one? Related to a runtime?

**Comment by Probe1** [comment]
I checked at the time and did not see a runtime.  I believe the injector itself lacks a proper attack.

**Comment by clusterfack** [comment]
It werks ingame

**Comment by Probe1** [comment]
the mapping nofail injectors are busted.  they have the wrong path.

**Comment by clusterfack** [comment]
>this isn't because of my PR by the by, I didn't edit any of the injectors.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/pull/8882/files#diff-fa0b9fcfd67e0628d34e167d2bef99e8R937

give me a sec

**Comment by Probe1** [comment]
I can reproduce it.  It spawns nofail injectors from a list and they have a working path but they don't seem to work at all. I can't inject myself with the one found at roundstart.  Let me try something.  

![bkuvnzr](https://cloud.githubusercontent.com/assets/8550416/14416743/898227ce-ff7b-11e5-8512-5bcdab5114fc.png)

**Comment by Probe1** [comment]
No, it didn't work.  I tried changing their path.  Regardless, I can reproduce this bug so pls re open.  It specifically occurs in the injectors in the cited list. https://github.com/d3athrow/vgstation13/pull/8882/files#diff-fa0b9fcfd67e0628d34e167d2bef99e8R937

**Comment by Intigracy** [comment]
DNA gets generated after the map spawns things as an fyi.

This'll take a convoluted fix or a very long spawn()

**Comment by clusterfack** [comment]
Or simply initialize as the case may be

**Comment by Probe1** [comment]
well reopen till fixed
