### ISSUE TITLE
Allow building on shuttle floors.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#8923]
Seriously why not?

**Comment by Intigracy** [comment]
:+1:

Turfs need to keep track of the floortype they have when building a wall on them though, so if you destroy it it spawns a new one of the same type.

**Comment by Killette2** [comment]
Well when it comes to building walls on shuttles, which I believe you can do with girders, it comes to issues such as walling off the shuttle from within, RCDing the wall to make a hull breach, and some other stupid junk that they made disabling it for a reason. Before we consider this, we need to think of EVERY way this could be abused, such as spamming shuttles full of computer consoles as an antagonist and such.

**Comment by AutismSpider** [comment]
shuttle full of consoles and other dumb shit if not some one being smart ass and RCD the shuttle floors or making walls out of plasma etc

**Comment by Intigracy** [comment]
This wouldn't allow for RCDing shuttle floors.

**Comment by AutismSpider** [comment]
not going stop people form being smart asses with walls/massive console etc
