### ISSUE TITLE
Plasmamen Changelings can't use Lesser Form

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8924]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7a65b3228440927d17195961c59a8a11e46a15a7 
> We cannot perform this ability in this form!

**Comment by PJB3005** [comment]
Issue is that plasmamen have no monkey form.

**Comment by Probe1** [comment]
best solution:  have changelings turn into norris instead of a monkey.  that's what norris is afterall.  a changeling.

**Comment by 9600bauds** [comment]
How is this feature loss

**Comment by Killette2** [comment]
Well it's kinda a feature loss in a way since we can't use a feature that we normally always could, but it's more of a racial thing.

**Comment by Intigracy** [comment]
Vox are probably the same way then, unless it turns them into chickens.

**Comment by Killette2** [comment]
I believe it would turn them into chickens, which would be rather comical. Instead of the crew fearing a deadly ventcrawling monkey DNA sucker, it would be a bunch of people chasing after a chicken (who'm can't even said ventcrawl)

**Comment by icantthinkofanameritenow** [comment]
@PJB3005 
Reminds me of the time I tried to monkey Sawbones. It ended up gibbing him instead for some reason.
