### ISSUE TITLE
Lasers interrupt OGGs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8928]
(WEB REPORT BY: theeliminator16 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 7a65b3228440927d17195961c59a8a11e46a15a7 
> 
> General description of the issue
> The sound of lasers firing causes currently playing oggs to end prematurely.
> 
> What you expected to happen
> The ogg should keep playing and properly cycle to the next one in the queue.
> 
> What actually happened
> Laser sound overrides OGGs and causes them to not finish.
> 
> Steps to reproduce if possible
> I think this is linked to lasers, specifically laser turrets but it might be for all lasers.

**Comment by 9600bauds** [comment]
Might be take related to the thing where their hitsound replaces their firing sound when hitting a mob

**Comment by Probe1** [comment]
IS THAT IT

I've been trying to figure out what's doing it for a month.

**Comment by clusterfack** [comment]
Can we play them on a different channel, is that a thing? I think its a thing.

**Comment by PJB3005** [comment]
Yes it's a thing but channels should be auto handled by BYOND if not specified.

**Comment by Intigracy** [comment]
#5880
#8502

**Comment by gbasood** [comment]
Possibly we're hitting a hard limit and maxing out the amount of sound channels. Would make sense for why large explosions, which cause lots of other explosions, screams, and flesh sounds, cause global sounds or music to stop playing.

That or it's really dumb about how it picks a channel and doesn't care whether a channel is in use or not, it just iterates a channel every time a sound is played.

**Comment by clusterfack** [comment]
Well there are only 8 sound channels (if I'm reading between the lines well enough on the reference)

**Comment by PJB3005** [comment]
@clusterfack the reference says it's 1-1024 though.

**Comment by clusterfack** [comment]
I was looking at the sound proc for that one
'channel: 0 for any available channel, 1-8 for specific channel (wavs only)'
But I guess setting the channel var you are talking about is probably the correct one. I didn't know you could set channel that way (and now I'm wondering why we don't use it)

**Comment by Intigracy** [comment]
(wavs only)

**Comment by clusterfack** [comment]
@Intigracy The way I read that is 'this arg wont work for shit for non-wavs' (also you're a fag)

**Comment by Intigracy** [comment]
I mean that's probably why we don't use it.

**Comment by clusterfack** [comment]
I'm not sure, the 'channel var' PJB describes is definitely in the reference and says it has values of 1-1024, and if it is a variable it should be accessible.

**Comment by Shadowmech88** [comment]
Tested, no longer seems to happen.
