### ISSUE TITLE
Putting seeds in the seed dispenser with the plant bag doesn't work correctly.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8932]
(WEB REPORT BY: grimaud516 REMOTE: 158.69.55.2:7777)

> Revision 7a65b3228440927d17195961c59a8a11e46a15a7
> 
> General description of the issue
> Putting seeds in the seed dispenser from the plant bag causes all of the seeds to stack under one plant, and when withdrawn they are empty seed packets.
> 
> What you expected to happen
> I expected to put the seeds in the dispenser with the bag and be able to withdraw them normally.
> 
> What actually happened
> I put the seeds in the dispenser through the plant bag.  When I went to withdraw the seeds I saw they were all stacked under one type of seed (they didn't go into their respected plant), and when I took them out they were empty packets when I tried to plant them.
> 
> Steps to reproduce if possible
> Make seeds using the seed creator
> Pick up seeds using plant bag
> Use plant bag on seed dispenser to put seeds inside of it.
> Withdraw seeds normally.

**Comment by Exxion** [comment]
The MegaSeed Servitor? Yeah, it's buggy and bad. Its ability to have seeds put into it should probably be removed; there are two other machines right there in hydroponics that do it better anyway.

**Comment by 9600bauds** [comment]
Related to #6551
