### ISSUE TITLE
Console Screen

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8933]
(WEB REPORT BY: seymourbutts REMOTE: 158.69.55.2:7777)
When a flatpacker blueprint for a console screen in placed in the flatpacker, it doesn't show in the queue but prevents adding another blueprint to it.

**Comment by Exxion** [comment]
A... console screen? In the flatpack fabricator? What?

**Comment by FudgePucker** [comment]
Okay.
Some admin needs to PM this player next time they get on.
Someone has worse English skills than notaspider.

Ether he was trying to put a blue print of a console screen into the flatpack machine, and then it fucked it up preventing it from taking other blueprints.
Or he was trying to put a computer (most of the computers just look like a screen) blueprint into it and it fucked it up.
Or he was trying to put a console screen blue print into the gen fab thinking it was the blue...
YOU CAN SEE WHERE I AM GOING WITH HOW DIFFERENT 1000 WAYS THIS COULD BE FUCKED UP.

**Comment by 9600bauds** [comment]
shitty issue
