### ISSUE TITLE
Should dionae be able to use creatine and nanobots?

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#8948]
In the reactions for creatine, mednanobots, and comnanobots, it's currently trying to prevent dionae from using those reagents by checking for `if(H.species.name != "Dionae")`
However, this doesn't work, meaning dionae are able to use both creatine and nanobots. As far as I can tell from less-than-thorough testing, what you actually want is `if(H.species.name != "Diona")` or perhaps `if(!istype(H, /mob/living/carbon/human/diona))`
Should this change be added, though? I don't care either way, but it doesn't seem to have caused any problems except dionae not having a cyber horror sprite. Thought people might want to share their opinions in a structured place and not just shitpost in the thread

EDIT: Someone please add a discussion tag or something? I dunno if I can or, if so, how

**Comment by TheFriggenSawbones** [comment]
Diona are trees they don't need nanobots

**Comment by TheEliminator16** [comment]
I intended to make nanobots non-usable by Dionae, but I made the same mistake as creatine because I reused the code.

I don't think they should be able to use them or creatine, they're way too strong as it is.

**Comment by Kammerjunk** [comment]
Ah, fantastic. Dionae being called like 3 or 4 different things (diona, dionae, dionaea at the very least) in different places is a bit of a bother, so that's understandable. I'm inclined to agree that a diona with mednanobots would probably be too resistant to burn damage, their only real weakness damage-wise. I haven't really used Hulk enough to know how it'd affect dionae, but you're probably right there too.

**Comment by TheEliminator16** [comment]
Especially because mednanobots heal burn and brute damage most efficiently when compared to oxy or even worse, toxin.

**Comment by PJB3005** [comment]
Pretty sure that dionaea is just flat out incorrect. 

If we're going by Diona being Latin the plural is dionae.

**Comment by Kammerjunk** [comment]
I think it's going by https://en.wikipedia.org/wiki/Dionaea but https://en.wikipedia.org/wiki/Dionae seems to be the same thing

**Comment by gbasood** [comment]
Brawndo for Dionae WHEN

**Comment by ghost** [comment]
Should be a way to make a species not able to process a certain chemical at all, maybe a chemical_exempt list that would just treat it as toxin or something.

Would let you make a bit more variety between species as well

**Comment by gbasood** [comment]
Actually I think livers should be able to support something along those lines

**Comment by TheEliminator16** [comment]
That's a good idea.
Maybe we should also make it so that if a human body doesn't have a liver, it sets the custom_metabolism of all reagents in that body to 0

**Comment by PJB3005** [comment]
@TheEliminator16 that's not how reagents work, though. Things like acid wouldn't hurt without liver then.

**Comment by TheEliminator16** [comment]
Oh, that's a good point, I didn't think of that.

**Comment by gbasood** [comment]
Custom metabolism = 0 would make it so a thing never metabolises, so it never gets used up, which for some reagents means it doesn't do a damn thing. For others it means it keeps reacting forever
