### ISSUE TITLE
SPSes Can't Be Heard While In a Backpack or Belt

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8955]
If the SPS is stored in a container that the mob is wearing, such as a security belt or backpack, the mob won't hear any announcements it makes. If the SPS is, for example, stored in the mob's pocket, the mob will hear its announcements, but no one else nearby will. An SPS on the ground can be heard by everyone.

Specifically the fact that the wearer can't hear the SPS if they've stored it in their backpack or security belt presents a significant problem.

**Comment by Exxion** [comment]
Probably an easy fix
It probably checks if its `loc` is a mob when it should check if `get_holder()` (or whatever the proc is) returns a mob and send it to that one

**Comment by gbasood** [comment]
#8956 related
