### ISSUE TITLE
Wizard's Horse Curse leaves Plasmen fucked

### ISSUE THREAD

**Issue by coldcola** [d3athrow/vgstation13#8958]
Happened twice in a round, when horse cursed the plasman is unable to turn on internals via the HUD or in hand menus.

Pretty easy to reproduce I'd think.

**Comment by Shadowmech88** [comment]
I don't believe horse masks are able to act as internals masks, meaning it'd fuck over vox as well.
The simple solution is to make horse masks act as internals masks, like clown masks do.

**Comment by SysadminJeroen** [comment]
It's a feeaaatuuuure?
I mean, can humans use internals with a horse mask on?

**Comment by Killette2** [comment]
Sometimes wizards horsemask people so they can't use internals, and that's their intent.

**Comment by Exxion** [comment]
Actually, genuinely is a feature

**Comment by Killette2** [comment]
So this should be made into a balance issue. Or we could just say go home non hummies

**Comment by Exxion** [comment]
Personally, I think it's fine as-is, assuming plasmamen being always unable to turn on their own internals from the hud was/is fixed

**Comment by 9600bauds** [comment]
Gotta pay the snowflake toll

**Comment by Exxion** [comment]
> Oversight

I'm pretty sure it's intentional
