### ISSUE TITLE
"He has no pulse" and the Like No Longer Show Up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8960]
(WEB REPORT BY: sangriamonkey REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

802a6427aed223f29ef83b65f0443b495b172e6b 

> General description of the issue

Examining a corpse doesn't tell you if it has a pulse or not. This makes it very hard to discern people in crit from dead people without having a med hud equipped.

> What you expected to happen

"He has no pulse and his soul has departed"

> What actually happened

"He does not appear to be breathing" and that's about it.

> Steps to reproduce if possible

Kill a guy and shift-click him.

**Comment by uazuaz** [comment]
if you right-click someone in an adjacent tile, you have a "check pulse" option;
if the person is alive, it takes about 6-7 seconds to check their pulse.

![pulse](https://cloud.githubusercontent.com/assets/6170726/13914566/69940266-ef4f-11e5-8e9e-ce9d2be86aa7.jpg)

**Comment by Shadowmech88** [comment]
Yes, but it used to outright say "he has no pulse" if you examined a dead person.
It used to also say whether the ghost had left the body, in the form of "his soul has departed."

**Comment by Exxion** [comment]
Yeah, that examine thing stopped happening a few months ago, I think

**Comment by ihadtoregisterforthis** [comment]
I blame it on mice losing the ability to count pulse

**Comment by SangriaMonkey** [comment]
This seems like a colossal pain in the ass for the sake of being one if that was an intentional change and really should have been documented somewhere.

**Comment by Exxion** [comment]
Honestly, the no pulse thing isn't a huge trouble, but there's now no way to tell if someone has ghosted.

**Comment by Exxion** [comment]
Good news! Looks like it is just broken and was not intentionally removed.
Bad news! The code doesn't _look_ broken and I have no idea why it isn't working, _and_ the relevant part of the file hasn't been edited since before it broke, if I'm not mistaken.

I would say it sounds like a secret repo thing except I can't imagine what use something in the secret repo could have that would break this

**Comment by clusterfack** [comment]
Pretty sure its !isUnconscious(user)

**Comment by clusterfack** [comment]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/carbon/human/examine.dm
```
	if (isUnconscious())
			msg += "<span class='warning'>[t_He] [t_is]n't responding to anything around [t_him] and seems to be asleep.</span>\n"
		if((isDead() || src.health < config.health_threshold_crit) && distance <= 3)
				msg += "<span class='warning'>[t_He] does not appear to be breathing.</span>\n"

		if(ishuman(user) && !isUnconscious(user) && distance <= 1)
```

**Comment by Exxion** [comment]
Wait, why would that break it? The user isn't unconscious, right?

**Comment by clusterfack** [comment]
Read the first and last line

**Comment by Exxion** [comment]
The first one is checking if the one being examined is unconscious and the last one is checking if the one doing the examining is unconscious, right?

**Comment by clusterfack** [comment]
Yeah no, that's not how it works.

**Comment by Intigracy** [comment]
Exxion you had what it SHOULD be doing down right.
