### ISSUE TITLE
BhangMeter map works fine, CrewMonitor map does not

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8961]
(WEB REPORT BY: termedclepe2 REMOTE: 158.69.55.2:7777)
The bhangmeter map works flawlessly, the crew monitor map doesn't display at all and shows only stars.

Having crew monitor map use the same drawing methods as bhangmeter would be great, or have both with a toggle option.

**Comment by Exxion** [comment]
Exactly the same caching issue as the advanced security cameras. No idea why the advanced security cameras map is broken for way more people than the CMC map, but they can both break in the same way.
I bet the bhangmeter already DOES use the same drawing method as those other two, but just happens to not be broken for you, as the caching issue only happens for some people and for some computers.

Try clearing your cache then opening the map. Try it again if it doesn't work. If it still doesn't work... *shrug

**Comment by clusterfack** [comment]
Again, should be fixed by the linked pr
