### ISSUE TITLE
Diona nymphs missing out on understanding others

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8962]
(WEB REPORT BY: milquetoast REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 802a6427aed223f29ef83b65f0443b495b172e6b 
> 
> General description of the issue
> It seems when blood sampling to fast in succession you can miss out on growth stages like being able to talk common
> 
> What you expected to happen
> That I would learn common
> 
> What actually happened
> I didn't
> 
> Steps to reproduce if possible
> Blood sampling fast in succession

**Comment by gbasood** [comment]
Someone else was complaining about not learning languages as a nymph before, as well. None at all, no matter how many samples were taken.

**Comment by jknpj** [comment]
Already got fixed.
