### ISSUE TITLE
Cultist max rune limit is too low for our current needs

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#8963]
```

 if (rune_list.len >= 26+runedec+ticker.mode.cult.len) //including the useless rune at the secret room, shouldn't count against the limit of 25 runes - Urist
            alert("The cloth of reality can't take that much of a strain. Remove some runes first!")
            return 

```

ritual.dm

This was probably good in 2010-2011 when it was coded but due to an increase in runes, players, and complexity of cult, this should be eliminated or increased from 26.

**Comment by Intigracy** [comment]
Why was there even a rune limit in the first place?

**Comment by Probe1** [comment]
Who knows.  Go get your coder valids @Intigracy

**Comment by Killette2** [comment]
> Not putting a convert rune on every single tile of medbay

**Comment by Probe1** [comment]
next time heads declare code red, wall off all of the bridge with runes to show them you're peaceful.

**Comment by ghost** [comment]
Think the reason the limit was reached in that particular round is because a paramedic cultist made a 15x15 area to research his runes in, and never wiped any, just kept making new failrunes

**Comment by Killette2** [comment]
Mime cultstation when? Remove all the walls and use cultist rune invisible walls.
