### ISSUE TITLE
Grinding Nettle and Death Nettle in a mortar don't give acid

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8965]
(WEB REPORT BY: manaony REMOTE: 158.69.55.2:7777)
Trying to do some ghetto experiments I went and tried to get polytrinic acid from the starting death nettle seed pack. After several grind I was forced to admit that I would get nothing. After trying my nettle in a normal grinder though I got the promised 10 units of poly acid and mortar gave me the corn oil from the corn. All in all I don't if there's even a problem but I'll make a bug report anyways.

**Comment by Intigracy** [comment]
So grinding wasn't working and then it magically was? What?

**Comment by gbasood** [comment]
It sounds like he ghetto'd something and it didn't work but a machine grinder did?

**Comment by Intigracy** [comment]
How's ghetto work?

**Comment by Manaony** [comment]
Here you go lad
http://imgur.com/a/c1aHA

**Comment by ihadtoregisterforthis** [comment]
I believe this is a duplicate

**Comment by gbasood** [comment]
#8532
#7511
Yep, but this has steps to reproduce.
