### ISSUE TITLE
Shit gets FUCKED if you grab someone laying down

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8967]
(WEB REPORT BY: zealotron REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 34a1e965142e8a8ce6c13e46c60296addabf7e83 
> 
> General description of the issue
> If you try to grab someone while laying down you can't ever move again or get rid of the grab. 
> 
> What you expected to happen
> To be normal
> 
> What actually happened
> I lost my legs
> 
> Steps to reproduce if possible
> 1. Lay down/Be put on a surgery table
> 2. Grab someone
> 3. Rest to get up
> 4. Lose something near and dear

**Comment by ihadtoregisterforthis** [comment]
Tested. You can regain movement by breaking the grab.
