### ISSUE TITLE
Esword banana

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#8970]
![honk](https://cloud.githubusercontent.com/assets/15067109/13940985/be90c516-efda-11e5-8b6e-19bc4fb8a5b1.png)

Esword for syndicate clowns, appears to be a banana when not active.
Would pair up nicely with https://github.com/d3athrow/vgstation13/pull/8321
Download link for icons: http://s000.tinyupload.com/index.php?file_id=96966426631840875974
Edit: Now comes in bunches, because evil clowns definitely would think that's a good idea
Edit 2: Now comes in pie flavour.
Edit 3: Inhand sprites for the bunch. With spinning!

**Comment by Killette2** [comment]
Is that a banana in your pocket or are you just happy to see me?

**Comment by Shadowmech88** [comment]
I feel like the sword's blade should be a much lighter shade of yellow, like a real banana's interior is.

**Comment by clusterfack** [comment]
I wish esword banana was an emoji

**Comment by ghost** [comment]
Bananablade

**Comment by ghost** [comment]
What about when it's combined with another esword? Would it be a half ebanana half esword, or would it be regular double-esword or double-ebanana?

**Comment by Blithering** [comment]
@Skullyton Clearly the next step is spriting the bunch-of-bananablade.

Edit: It happened. 
![clownsdidthis](https://cloud.githubusercontent.com/assets/15067109/13995081/8ecbede2-f11f-11e5-952f-a374e78e2615.png)

**Comment by ihadtoregisterforthis** [comment]
If not cream colored, the blade could be transparent, or glowing

**Comment by Blithering** [comment]
@ihadtoregisterforthis The blade has the same glowing effect as other eswords do.

**Comment by coldcola** [comment]
I have this pretty much done, just needs an in-hand sprite for the bunch and to be added to the syndicate uplink (if warranted)

**Comment by Blithering** [comment]
@coldcola I originally intended the bunch to be such a clusterfuck of blades it couldn't be held and had to be kicked around. I'll make an in-hand sprite if it's desired.
![piesword](https://cloud.githubusercontent.com/assets/15067109/14092665/7c9a7df8-f540-11e5-89c9-e59d7a8cd335.png) 
Also realised that if it looks like a banana people might try cooking with it, so I made that.

**Comment by coldcola** [comment]
how I've currently got it working is that if you aren't a clown and you use it, you'll fumble and it'll put you just about into crit, otherwise functions as a regular double-bladed sword.

I'm open to suggestion on the name for the bunch as well

**Comment by ghost** [comment]
Wait, would it be slippy when it's on the floor?

**Comment by coldcola** [comment]
it could be, which are you referring to, the bunch or the banana - or both?

**Comment by ghost** [comment]
How about all? And if it's 'active' and you slip on it, you have a chance to impale yourself?

**Comment by Blithering** [comment]
@coldcola Okay, I'll get working on an inhand sprite for the bunch. Thanks for coding all this nonsense.

**Comment by coldcola** [comment]
@Skullyton 
I like it for the concealed banana sword and the inactive bunch but wouldn't it be too detrimental to the syndi who bought it to have it slip them if they drop it - they could just buy a regular esword at that point.
Keep in mind when the an active bunch is dropped it become inactive so it would already have that property, so I'd just be adding it to the base banana sword

**Comment by Blithering** [comment]
@coldcola Okay I've updated with the inhand sprite for the bunch. Let me know if there's anything more you can think of that needs adding.

**Comment by coldcola** [comment]
Actually I didn't phrase that right because I'm dumb, can you do a mob overlay for the active bunch, I'm just using a regular banana for the inactive

**Comment by Blithering** [comment]
@coldcola It should all be in the new download link.
