### ISSUE TITLE
Print a Manual on Check-In/Out Computer is fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8972]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 34a1e965142e8a8ce6c13e46c60296addabf7e83 
> 
> General description of the issue
> https://i.gyazo.com/3bac0f5e2da83984a2d5d5482a75441a.png
> Books have the wrong titles and shit.
> 
> What you expected to happen
> Print one of each and put them in the reference bookshelf
> 
> What actually happened
> From "Out on the dig" onwards everything's fucked. If you click "Out on the dig" it tells you it's forbidden and can't be printed, "High-powered mass spectrometry" prints "Out on the dig", "Spectroscopy" prints the latter etc. etc. and there's no button to print "Cellular Suspension".

Can't believe I'm this bored I found this.

> Steps to reproduce if possible
> Try the "Print a Manual" option on the librarian's computer.

**Comment by xpcybic** [comment]
thanks oldcode

**Comment by Shadowmech88** [comment]
Tested on the test server, all the manuals printed out fine.
