### ISSUE TITLE
DEFF - Mulebots can't return home

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8973]
(WEB REPORT BY: vasby REMOTE: 158.69.55.2:7777)
QM#1 through 4 return an invalid location, so the mulebot doesn't know where to return home.

**Comment by gbasood** [comment]
Map issue?
Maybe we should add the map we're running to the bug reports.

**Comment by PJB3005** [comment]
It's literally in the title @gbasood

**Comment by gbasood** [comment]
wew

**Comment by Probe1** [comment]
After testing mulebot 1 works but mulebot 2 hangs at Status: Waiting for clear path after reaching its delivery.

**Comment by Probe1** [comment]
Even after deleting everything in the area its ??? hung.  AND deleting the other mulebot.  AND moving the home nav beacon to a new location.

![dreamseeker_2016-04-04_10-49-37](https://cloud.githubusercontent.com/assets/8550416/14251876/f109db0e-fa52-11e5-8654-db41d6290315.png)

**Comment by Duny-** [comment]
I have NO IDEA how to fix this

**Comment by Kurfursten** [comment]
Navbeacon stuff is a massive headache to work with. I'm guessing one of the beacons along the only route back doesn't have the connecting beacons tagged.

Also, this may have fucked with Probe's testing: after a MULE stalls due to blockage, you have to manually hit proceed again iirc.

**Comment by Probe1** [comment]
Believe me I manually restarted that fucker many times.  Including deleting everything in the surroounding 15x15 area, teleporting to be next to the beacon, and everything else I could think of.

**Comment by Kurfursten** [comment]
Did you check the destination tags on the next beacon? You can do it with an open hand or a multitool or something like that, also you can view variables - after screwing it open.

**Comment by CptWad** [comment]
these files are  cursed
