### ISSUE TITLE
no disabilities effect

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#8974]
when doing genetics i found some speech disabilities like Lisp, Loud and Wacky, but when i tried to talk they didn't have any effect on me.

**Comment by Exxion** [comment]
Can you give some more specifics? Any ideas _why_ they didn't work on you?
What other genes did you have? What race were you playing? Has this happened before? Did it happen to other people?

**Comment by uazuaz** [comment]
i was human;
i had few powers, like shock immunity, super fart, matter eater and telekinesis, can't remember if i had others;
i had no disabilities when i found these, because i inject myself a clean block to cure disabilities every time i get them (of course, i tested these disabilities before healing them)
a couple of days ago i was trying genetics on the test server and i had the same issue; that time, i noticed that also other speech disabilities, like Swedish and Smile, didn't have effect
Mute disability works as usual;
haven't talked with other people so i don't know if also happened to someone else.

**Comment by uazuaz** [comment]
now i remember that i had x-ray vision and the Strong "disability" too, plus a couple of modified blocks with inactivated powers.
i also had a power that said something about my leg muscles, it was not the super jump power and didn't appear in my powers list.

**Comment by 9600bauds** [comment]
Lisp is the only one that wouldn't work for me

Whisper's effect is literally commented out

**Comment by Intigracy** [comment]
Whisper seems like it'd fit more as a virus effect tbh.

**Comment by Shadowmech88** [comment]
Tested locally, all the speech disabilities had an effect. Some of the effects were quite minor and easy to miss, but they were there.
