### ISSUE TITLE
Wrong Mini map showing on the crew monitoring computer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8975]
(WEB REPORT BY: chickenzness REMOTE: 158.69.55.2:7777)

> Revision: 34a1e965142e8a8ce6c13e46c60296addabf7e83 
> 
> The map we're playing on is Box but the map shown is Metaclub
> 
> See the Box map
> 
> See the Metaclub map
> 
> Use the crew monitoring computer

**Comment by clusterfack** [comment]
Huh, guess it wasn't a problem with caching

**Comment by clusterfack** [comment]
I fixed this
