### ISSUE TITLE
Borer Jobban

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#8979]
Are they a thing? An admin told me they weren't a thing.
I think they should be a thing.

**Comment by ihadtoregisterforthis** [comment]
[grudgerequest]

**Comment by AutismSpider** [comment]
Not yet only way to job ban some one form borer is to do it form PAI

**Comment by mrpain666** [comment]
No they are not a thing. When someone fucks up with borer I am forced to just server ban them. I was unaware that a pai ban also covered it. I feel the two need to be separated.
