### ISSUE TITLE
If we're putting website requests on github then I'd love to have a confirmation box for unbanning someone

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#8985]
@d3athrow 

So you have this page.  ban page and rapsheet are the same.

![image](https://cloud.githubusercontent.com/assets/8550416/13969360/be63aeea-f058-11e5-954d-3efa61a7649c.png)

If you click unban, that's it.  wham bam done they're free to go.  If you accidentally click un-ban you may never be able to figure out who you accidentally unbanned.

Confirmation dialogue box pretty please.

**Comment by Shadowmech88** [comment]
As long as the ban page is being edited, I think listing the date the ban was applied would be handy for being able to look up the relevant logs.

**Comment by Intigracy** [comment]
I agree with Shadowmech 100%, banpage should have the date banned.

**Comment by gbasood** [comment]
Also unban time and date

**Comment by Probe1** [comment]
all these things would be nice but I'll settle for not getting sweaty palms when I click the damn scroll bar, worrying I may misclick and unban XxXW3LD3RB0MBPr0420XxX without realizing it.

**Comment by Shadowmech88** [comment]
Why would you ever use the scroll bar instead of your mouse's scroll wheel?

**Comment by Probe1** [comment]
There are a lot of fuckin bans.

**Comment by Intigracy** [comment]
click middle mouse button in, move mouse below cursor

**Comment by ihadtoregisterforthis** [comment]
Or hold the middle button for maximum scroll control

**Comment by Probe1** [comment]
![2016-03-22_20-46-03](https://cloud.githubusercontent.com/assets/8550416/13972429/1aead13c-f06f-11e5-82a0-6a52c7ae54e2.gif)

This is just the publicly visible bans and not all the expired temp bans

there's a lot and I'd like that confirmation box please

**Comment by Intigracy** [comment]
it goes faster the farther away you pull it from your initial click

![](https://dl.dropboxusercontent.com/s/bzdv6grclr6ggau/2016-03-22_17-52-12.gif?dl=0)

shitty gif tho, bad framerate

**Comment by ComicIronic** [comment]
Why closed?

**Comment by Intigracy** [comment]
I asked Pomf if he could and he said possibly.

You can see the date/time someone was banned by hovering over their name, which I just found out.

**Comment by Intigracy** [comment]
Also this is apparently already coded and Pomf just tested it to ensure it's still working, it is.

**Comment by d3athrow** [comment]
@ComicIronic because theres already a confirmation box

**Comment by Probe1** [comment]
I asked 6 months ago and it saw no traction.  I have 60+ open issues. I'd like the repo to be focused on present ones and not ones that existed you know, half a year or more ago.

I don't even have access to rapsheet right now to confirm if the issue is still present, as @d3athrow has pointed out.
