### ISSUE TITLE
Summon robes could use a tweak

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#8989]
Every time the "Summon Robes" spell is purchased, instead of upgrading the first instance like other spells, it makes a new button, independent from the others. This is inconsistent but still serves to reduce cooldown in a way.
The image shows this taken to the extreme, every time it's chosen it properly uses one good wizard point.

But most importantly the message after choosing it **_IS NOT CAPITALIZED**_

![summon robes](https://cloud.githubusercontent.com/assets/13305885/13973067/9ad967ec-f07d-11e5-82c1-46a1ff3b0fe4.png)

**Comment by Intigracy** [comment]
Are you sure clicking one doesn't put them all on cooldown?

**Comment by ihadtoregisterforthis** [comment]
Completely

**Comment by gbasood** [comment]
Most spells that allow you to get duplicates work this way (clown curse, mime curse)

**Comment by coldcola** [comment]
I took a look and it seems like none of the post-spell-learning messages are capitalized, is this a problem?

**Comment by nervere** [comment]
This got fixed 6 years ago.
