### ISSUE TITLE
Flatpack Fabricator and Sleeper/scanner consoles

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8990]
(WEB REPORT BY: kolith REMOTE: 158.69.55.2:7777)

> Revision 861a5c96dce31ffa41e9b3dd913fac4b6a7e352a 
> General description of the issue
> Used DA and flatpack fabricator to make a sleeper/body scanner, and it made unmovable and uninteractable consoles to the tile right of it, as well as the sleeper/scanner flatpacks.  
> 
> What you expected to happen
> Sleeper to be functional and the scanner to be made somehow as well.
> 
> What actually happened
> The sleeper functions, but you cannot interact or move the console. 
> 
> Steps to reproduce if possible
> Make a sleeper or body scanner with the flatpack fabricator.

**Comment by ihadtoregisterforthis** [comment]
#5311

**Comment by kol1th** [comment]
yep he told me to bring it up again so someone would fix it.

**Comment by PJB3005** [comment]
Dupe
