### ISSUE TITLE
METACLUB MASSIVE OUTRAGEOUS BUG

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8991]
(WEB REPORT BY: furbeh REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 861a5c96dce31ffa41e9b3dd913fac4b6a7e352a 
> 
> General description of the issue
> Donk-Pockets are unreachable in Permabrig
> http://i.imgur.com/4RAil5o.png
> 
> What you expected to happen
> Get donk-pockets
> 
> What actually happened
> can't get them
> 
> Steps to reproduce if possible
> Go to metaclub and permabrig.

**Comment by Exxion** [comment]
The Curse of `border_only = 0` in Diagonal `Adjacent()` strikes again!

**Comment by Intigracy** [comment]
That tile is also a plating instead of a floor.

TBH switching the box with the microwave would fix this, I'm pretty sure.

**Comment by Exxion** [comment]
It would
I really think `border_only` should be 1 in the `Adjacent()` diagonal case, though
It would also fix entombing yourself in a little box by misstepping while dragging something
But it may cause some other issues, I'm not sure
