### ISSUE TITLE
Shitficciency auxillary storage room on research station Bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8995]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 861a5c96dce31ffa41e9b3dd913fac4b6a7e352a 
> 
> General description of the issue
> When you try to scan an artifact on the pad in that room, it scans the firelocker instead.
> 
> What you expected to happen
> Scan my artifact
> 
> What actually happened
> Scanned the firelocker
> 
> Steps to reproduce if possible
> Get large artifact
> Put on pad in that room on Deff
> Scan it
> Get a paper that reports about the locker

**Comment by Probe1** [comment]
I remade the entire outpost because of this issue.

![image](https://cloud.githubusercontent.com/assets/8550416/14263472/c8b54b6c-fa88-11e5-9770-1a95fcbad959.png)
