### ISSUE TITLE
Not all of deadchat is logged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#8996]
(WEB REPORT BY: furbeh REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 861a5c96dce31ffa41e9b3dd913fac4b6a7e352a 
> General description of the issue
> Talking in deadchat without ghosting is not logged
> 
> What you expected to happen
> All of deadchat to be logged
> 
> What actually happened
> It isn't
> 
> Steps to reproduce if possible
> Talk while in your corpse after you die and check the logs afterwords

**Comment by Shadowmech88** [comment]
I was under the impression that it's just not possible to talk in deadchat while inside your corpse.
When I do it, I don't even see the text show up in the chatbox.

**Comment by chatsonf** [comment]
You can't hear ghostchat if you die after you go deaf from an explosion or something similar

**Comment by Shadowmech88** [comment]
That sounds like it should be its own bug report, Furbeh.

**Comment by chatsonf** [comment]
Alright let me get on it

**Comment by Exxion** [comment]
You can talk in ghostchat while in your corpse as long as it's a whole corpse, but not if you're just a head or brain. Also yeah, deadchat doesn't always log.

**Comment by chatsonf** [comment]
BUMP CAUSE FIXED
