### ISSUE TITLE
Deafness lasting after death and chat

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#8998]
> Revision
> 861a5c96dce31ffa41e9b3dd913fac4b6a7e352a
> General description of the issue
> You can't hear chat, including ghostchat, while in your body if you die after you go deaf from an explosion or something similar
> What you expected to happen
> The ability to hear chat after dying in an explosion while still in my body
> What actually happened
> The inability to hear chat while in my body
> Steps to reproduce if possible
> Die in an explosion, and try and talk in chat once you die. It will look like you didn't even say anything.

**Comment by Probe1** [comment]
This is a wider issue.  Mindbreaker and spiritbreaker persist through death as well.  You'll see players that died saying beep beep et cetera from the effects of sb.  I don't think there's any kind of check at all for this stuff.

**Comment by PJB3005** [comment]
@probe1 that issue has basically been written of as IT'S A Feature, though.

**Comment by Probe1** [comment]
I don't have much of a problem with it but I'm bringing it up since its related.

**Comment by ghost** [comment]
Dying when deaf does not appear to be an issue, though if you are a brain in a head it seems you do not get access to dead chat.
