### ISSUE TITLE
1

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9001]
SOMEONE LEFT DEBUG OUTPUT IN
And I have no idea what caused it
Encountered while testing gold slime core reaction on a local server, which spawned an alien drone, a rapidfire hivebot, a festivus pole, a giant spider hunter and a necromorph. But I didn't see any debug output in their respective files.

Tabbed out after the slime core reaction worked fine. Tabbed back in 5-10 mins later to "1" as the last line printed. So it's probably unrelated to the reaction itself.

Vaults spawned:

```
ADMIN LOG: Spawning 6 vaults (in 10 areas)...
ADMIN LOG: Loaded maps/randomVaults/rust.dmm: random vault area - 341,143,3.
ADMIN LOG: Loaded maps/randomVaults/spacegym.dmm: random vault area - 230,373,6.
ADMIN LOG: Loaded maps/randomVaults/clown_base.dmm: random vault area - 79,463,5.
ADMIN LOG: Loaded maps/randomVaults/hivebot_factory.dmm: random vault area - 262,151,4.
ADMIN LOG: Loaded maps/randomVaults/asteroid_temple.dmm: random vault area - 150,436,4.
ADMIN LOG: Loaded maps/randomVaults/icetruck_crash.dmm: random vault area - 379,364,4.
ADMIN LOG: Loaded 6 vaults successfully, 0 failures.
```

**Comment by Exxion** [comment]
I remember seeing a 1 show up while being mauled to death by xenos a month or two ago

**Comment by Intigracy** [comment]
Might be related to the alien drone then.

**Comment by xpcybic** [comment]
It's happenin', folks!

**Comment by PJB3005** [comment]
WAIT. 

First we had 3.

Then we had 2.

Now we have 1.

HAPPENING.

**Comment by gbasood** [comment]
#9001

> issue name: 1

**Comment by 9600bauds** [comment]
http://youtube.com/watch?v=TcJ-wNmazHQ

**Comment by FudgePucker** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHH

AAAAAAAAAAAAAAAAHHHHGHHHGRSJDFFVTFDHGDKVTHVF

ITS AT ONE NOW, RUN, FUCKING RUN

**Comment by clusterfack** [comment]
It was just a prank bro
