### ISSUE TITLE
Ghosts can activate the gibber

### ISSUE THREAD

**Issue by Kammerjunk** [d3athrow/vgstation13#9002]
Revision: 78d5f4674ca3c32913f277bf1f92442606abcaaa

> General description of the issue

Midround, someone put someone else in a gibber, but did not turn on the gibber. A ghost then clicked on the gibber and it turned on. Nuke then spawned himself and climbed in and the ghost clicked the gibber to the same effect.
![gibbed human with ghost](https://cloud.githubusercontent.com/assets/5942183/13986991/b99e72c0-f105-11e5-8e19-6a23e81dec25.PNG)

> What you expected to happen

I expected either nothing to happen or for the ghost to get a "you can't do that" message.

> What actually happened

In both attempts, the gibber turned on and gibbed the person inside as if it was a living person activating the gibber

> Steps to reproduce if possible

Put a human inside the gibber, ghost, turn on the gibber.

**Comment by Intigracy** [comment]
Can people even get out of the gibber once they're inside?

**Comment by Probe1** [comment]
I'm pretty sure there's a right click verb yah

**Comment by Kitfox88** [comment]
magical ghost hands
