### ISSUE TITLE
Clown goblins don't actually seem to deal brain damage

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9003]

**Comment by Probe1** [comment]
That was noted at the time when chocolatemoose first hacked them in as an admin.  

It seems the variable just defaults to brute and you gotta use something special to make it do drain bamage.

**Comment by Shadowmech88** [comment]
I overrode the melee_damage_type to "BRAIN", and had the simple_animal code check for that value and use adjustBrainLoss() to deal brain damage.
Is attack_animal() not the proc that governs a simple_animal attacking other mobs?

**Comment by unid15** [comment]
Maybe they just deal 0 damage in the code

**Comment by Shadowmech88** [comment]
They're children of cluwnes, and cluwnes deal between 0 and 0.5 damage, according to the code.

**Comment by unid15** [comment]
try raising it to 1 or 2

**Comment by 9600bauds** [comment]
Still broken
