### ISSUE TITLE
Plasmaman toxins tank broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9004]
(WEB REPORT BY: oberoth REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> f33e5b6d95c7165349ac1f9323716ce418c92c7b
> 
> General description of the issue
> Toxins tanks cant be reactivated as internals if they are removed. Only round start toxins internals run.

**Comment by gbasood** [comment]
Duplicate
