### ISSUE TITLE
You can hit yourself with your own eye lasers while aiming ahead of you while moving.

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9006]
Mutate spell eye lasers specifically

**Comment by Probe1** [comment]
Good, fuck that spell.  That spells a madhouse.

**Comment by Shadowmech88** [comment]
This can happen with a lot of projectiles.

**Comment by Shadowmech88** [comment]
Tested locally, I was unable to hit myself with my own eye lasers through any form of movement while firing.
