### ISSUE TITLE
Admin-accessible vault list window so I can jump to a vault at will

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9007]
Instead of relying on the roundstart links that I'll no longer have after roundstart

**Comment by Intigracy** [comment]
There's also jump to area.

**Comment by Probe1** [comment]
Yes but none of us have any idea what the area is called.

**Comment by Arthurdentist** [comment]
the area is always called mysterious vault but unfortunately this doesn't let you jump to any particular vault.

**Comment by Intigracy** [comment]
The area you use within your vault map is named.

That area is spawned with your vault because it's part of the vault.

**Comment by Probe1** [comment]
Yeah but we're never gonna know what an individual coder named it.

**Comment by gbasood** [comment]
Jump to area uses name var not typepath, though.

**Comment by Probe1** [comment]
Then we're back to it taking us to a random one.  We don't know what vaults are included unless we're at round start and have a hard time getting to a specific one.

**Comment by PJB3005** [comment]
SDQL query: `SELECT /area/vault where x != 0`

**Comment by Probe1** [comment]
fuk son not everyone has debug and not everyone that does understands how to make an sdql query, or will know what query to make unless they ask you/read this.

**Comment by mrpain666** [comment]
The jump to area thing really isnt effective at locating vaults. Someone sent a prayer to be taken somewhere "comfy" and the only vault I was able to find was the Vox Vault.

Make their own separate spot in the UI please.
