### ISSUE TITLE
Two borers One human

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9009]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 92e714f831a5ee0ee035e9f78029770c82ea6dab 
> General description of the issue
> GEE BILL?! TWO BORERS
> 
> What you expected to happen
> One human can only carry one borer
> 
> What actually happened
> Me and another cortical borer skullfucked the same human
> 
> Steps to reproduce if possible
> It's random I think, but sometimes you can infest the same human even if there's another one inside of you already. Has happened to Nick Weller as well.
> Literally no clue how it works

**Comment by Imagebard** [comment]
Note form 2-borer's bill:
They tried to crawl up my brain at about the same time. There were a lot of borers that round.

**Comment by Exxion** [comment]
Let's get an ULTIMATE BORER COLLECTIVE with eight borers in one person
More if they don't have to enter at the same time

**Comment by Intigracy** [comment]
Needs a check after the do_after that's the same as before the do_after.

**Comment by Brolaire** [comment]
Has this been fixeroo'd?

**Comment by ghost** [comment]
With the addition of MULTIBORERS this isn't an issue any more.

**Comment by ihadtoregisterforthis** [comment]
One down, 611 to go on the milestone
