### ISSUE TITLE
Borer is actualy Swedish

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9010]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 92e714f831a5ee0ee035e9f78029770c82ea6dab 
> 
> General description of the issue
> Telephoto vision also turned host who wasn't swedish before, swedish, bork bork!
> 
> What you expected to happen
> More vision
> 
> What actually happened
> Host said "I can see further, but, I'm also svedish, bork bork!"
> 
> Steps to reproduce if possible
> Climb into host, give telephoto vision.
> I don't think this always happens, but the same person had two borers inside of them as well. Fucking, I don't know

**Comment by Imagebard** [comment]
Note: The random chance for a genetic power block to fail/give a unrelated mutation might be related to this.

Note: This bug happened two times in a row to me.

**Comment by Killette2** [comment]
I've had a double mutation with a borer once, I forget which the other was though.

**Comment by Shadowmech88** [comment]
In general, triggering a genetics block seems to always carry a small chance of mutating one other random block. For example greys that get a disability along with their roundstart telepathy.

**Comment by Exxion** [comment]
@Shadowmech88 There's actually just a random chance to get a disability at roundstart, for everyone, not just greys.
Was the host Swedish before and just took rye to get rid of it? Because changing genetics blocks (even with the borer) undoes the effects of rye.

**Comment by Shadowmech88** [comment]
Are you sure? Because I've only heard reports of it from people that have some genetics difference at roundstart (detective, bartender, clown, etc.)

**Comment by Exxion** [comment]
It's _supposed_ to be that way, at least, judging by the code

**Comment by Probe1** [comment]
It's true.  There is a very rare chance of getting a disability at round start.  I've gotten YELLING before which was awkward.

And taking ryetalyn represses genetic changes without removing them.  So further genetic alterations will trigger the repressed genes as well.

No idea if that's happening here.

**Comment by Exxion** [comment]
Fun Fact: There's also a very low chance of getting a genetic power on top of the disability at roundstart
Best one I've gotten was telekinesis
I think I've gotten it at roundstart twice, but once was accompanied by seizures so I had to take rye that time

**Comment by Imagebard** [comment]
I didn't have the swedish disability before I got telephoto, to clean that up.

**Comment by gbasood** [comment]
@Imagebard has apparently enocuntered specifically getting swedish block after farsight via borer activated multiple times so someone needs to figure out what's going on with that

**Comment by Imagebard** [comment]
Not exactly the Swedish Block, just a random disability to go along with telephoto. I don't remember what the first one was.

**Comment by Intigracy** [comment]
> I don't think this always happens, but the same person had two borers inside of them as well. 

That's another issue in and of itself if you mean both inside at the same time.

**Comment by Brolaire** [comment]
Yes, both were in here at the same time @Intigracy 
Same round, host was again @Imagebard 
Check here: #9009

**Comment by chatsonf** [comment]
![BUMP'D](http://i.imgur.com/FWt9HD2.png)

**Comment by Probe1** [comment]
they already had the gene at round start but it was repressed.  the minute something messed with their genes it was activated.

not a bug

this happens to geneticists fairly frequently.  they inject themselves with whatever power and get a defect 4nr

**Comment by Shadowmech88** [comment]
Swedishness is a disability though, don't disabilities manifest 100% of the time?

**Comment by Probe1** [comment]
its the same repression as ryetalyn.  the defect is always there it just isn't active.

**Comment by Imagebard** [comment]
>they already had the gene at round start but it was repressed.

By repressed do you mean "they took ryetalin"
Because I assure you that's not it

**Comment by gbasood** [comment]
it's a feature because genetics activating genes that were present before but not activated IS a feature
not sure why this specific person had swedish showing up consistently
re-open if it's actually a bug and can be reproduced I guess
