### ISSUE TITLE
Being able to examine eye type.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9011]
With more and more surgical possibility, you can now have things such as wooden peg legs, robotic arms, and even missing limbs. All of this you can find out about a person when you examine them, except for the cases when a piece of their outfit hides said feature.

Now we have the ability to do eye transplants, and print gray eyes from the bioprinter in medbay. What does this have to do with anything? Well the answer is darksight. Grays can naturally see better in dark than humans, where it's almost pitch black but you can barely see. However if you wear mesons as a gray, the tiles are visible.

Why is this important you ask? Well different races have different darksight, which is now tied into your eyes. Humans have a darksight of 2, unathi have a darksight of 3, grays have a darksight of 5, mutons have a darksight of 1, unmentioned races such as diona, plasmamen, and vox have the same default darksight of humans making theirs 2. But tajaran/catbeast have 8? This creature can see extraordinary in the dark, and because of this, I have taken medbay positions and given people catbeast eyes, because it gives them the ONLY advantage of being a catbeast without getting lynched.

But what if you could examine someones eyes, it would be pretty hard to not notice if a human had a gray's eyes if they weren't wearing a full facial mask or helmet. If this was a feature, it may discourage some people from taking the all powerful catbeast eyes because then people will find out that they are part catbeast and might not take too kindly to that. We must also take into effect the new mechanical eyes, should mechanical eyes be noticable, or were they built to be very close looking to human eyes (the mechanical eyes being a fit-all to all other eye types is a bit of a stretch when you consider the eye sizes of other races, such as a gray's eyes. So that being said, I say mechanical eyes should be determinable upon examine unless their face is hidden)

Picture somewhat related

![googly eyes](https://cloud.githubusercontent.com/assets/5169310/14001847/96c181e8-f11e-11e5-9e0a-e9ba550215b9.jpg)

**Comment by Killette2** [comment]
Also, here is the carbon code, where I got all my information about darksight for other curious people who would like to learn more about the different advantages/disadvantages of playing races other than human.

https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/carbon/species.dm

**Comment by Exxion** [comment]
While you're at it, maybe make examination tell what race someone is
It's always easy to tell vox from everyone else, but ridiculously elaborate outfits make it difficult to tell the rest apart sometimes, especially greys from humans
But it seems like it would be much easier for the character to tell than the player, if that makes sense, so it should show up in examine

**Comment by liltiptop** [comment]
Don't we have a full body scanner for that? Or does it not work?

**Comment by Exxion** [comment]
Yes, but it really shouldn't be necessary to use a full-body scanner to determine something that is clearly visible about someone.

**Comment by icantthinkofanameritenow** [comment]
Better idea: how about we make it so if you transplant eyes from the "wrong race" in, they simply don't work? Tissue rejection is a thing, after all.

**Comment by ihadtoregisterforthis** [comment]
MY BRAND!

**Comment by Exxion** [comment]
@icantthinkofanameritenow How about we don't do that because the whole point of having different eye types was to be able to Frankenstein people

**Comment by Killette2** [comment]
Organ rejection is kind of lame, why wouldn't you want to give someone plasmaman lungs for example? We just need to let this all sink in and be around for a while, and eventually we will be able to attach new limbs and make true freaks.

**Comment by icantthinkofanameritenow** [comment]
@Exxion

I thought it was just for IMMULSIONS since until then everyone used the same lungs and eyes.

**Comment by Exxion** [comment]
That too, but come on, performing crimes against nature is cool
I remember a certain unnamed vox keeping a corpse with no limbs or head alive for as long as forty consecutive seconds

**Comment by icantthinkofanameritenow** [comment]
> no limbs or head

But I thought decapitation was an instant kill in SS13

**Comment by Exxion** [comment]
Turns out it isn't
You can briefly sustain a headless body
It takes suffocation damage at a ridiculous rate and is automatically catatonic, but you can keep a headless body in a vegetative state with a constant infusion of dex+ and maybe some other stuff

**Comment by Killette2** [comment]
Pretty sure you can live without a head but it's very difficult as you'd imagine.

**Comment by gbasood** [comment]
So I agree in that you should be able to tell what a person's eyes are somehow without taking htem out of their skull, in most cases.

How would you picture this mechanic working, though? Just on examine()? Because I really would prefer that examine code not get bloated

**Comment by Killette2** [comment]
I mean, we could have a more tab, which shows things like visible robotic or peg limbs, and add eyes there. You can already bloat examine as much as you want to by eating a ton of monkey cubes.

**Comment by gbasood** [comment]
Wait, what

**Comment by Killette2** [comment]
there is a malformed monkey (457) sticking out of their chest!
there is a malformed farwa (152) sticking out of their chest!
there is a malformed monkey (777) sticking out of their chest!
there is a malformed monkey (648) sticking out of their chest!

**Comment by gbasood** [comment]
eww
