### ISSUE TITLE
Weird screen issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9013]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 0b65257063f035e18ee5ec8bd32b72082da380fb 
> 
> General description of the issue
> Screen turned into big ball of fuck
> https://i.gyazo.com/7bc19ec1f118e42bd7d9ba5f192de197.png
> 
> What you expected to happen
> Ghost and spectate deadpop Taxi
> 
> What actually happened
> WHAT AM I LOOKING AT BOSS
> 
> Steps to reproduce if possible
> Fuck I don't know, put Grey head on human body, behead again, ghost.

**Comment by FudgePucker** [comment]
I think the pressure in the area is safe at least...

**Comment by 9600bauds** [comment]
this was caused by some weird sekrit repo stuff that's no longer in play
