### ISSUE TITLE
Cloning console sprite

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#9015]
The cloning console shows the "active" sprite even if the console is unpowered and unusable.

![cc](https://cloud.githubusercontent.com/assets/6170726/14016957/e8dc1e7a-f1c3-11e5-889b-7cb7907366b0.jpg)

**Comment by Brolaire** [comment]
I would like to add that the PA in Engineering also starts with a "turned on" sprite even though its not wired or on yet. Might wanna check that out too.

**Comment by clusterfack** [comment]
Recently? Because that was fixed (supposedly)

**Comment by Brolaire** [comment]
i saw it in the last week or so so yeah idk

**Comment by uazuaz** [comment]
@Brolaire 
that was fixed a couple of days ago. 
i taken this screenshot right now at round start:

![pa](https://cloud.githubusercontent.com/assets/6170726/14040705/3236a170-f26a-11e5-8909-482ca738f62d.jpg)

**Comment by Brolaire** [comment]
Oh if that's the case, I retract my statement, thanks for clarification.
