### ISSUE TITLE
Supermatter crystal is broken

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#9020]
Full crystal explosion doesn't trigger the cascade event, it spawns bluespace and keeps exploding at full force every few seconds. Since it keeps exploding, the server starts convulsing and **all** systems fail. Server crashes at high speed with no survivors.

![you are blinded by a brilliant flash of energy](https://cloud.githubusercontent.com/assets/13305885/14025855/dabb7e7a-f1ce-11e5-989c-d7f25d97457f.png)
![you are blinded by a brilliant flash of energy](https://cloud.githubusercontent.com/assets/13305885/14025860/dca7cb12-f1ce-11e5-88ea-c74d6e4b2f23.png)
![you are blinded by a brilliant flash of energy](https://cloud.githubusercontent.com/assets/13305885/14025853/d8ed52da-f1ce-11e5-8e72-14f35163cbbe.png)

PS: When I say _all_, I mean **_all**_. Test server results give hung process messages for _obj, pipenet, mob, power, lighting, machinery_ and then _pipenet, mob, power and obj_ again before crash.

**Comment by FudgePucker** [comment]
I guess it really is a round ending event :^)

**Comment by SysadminJeroen** [comment]
Noticed this about a month or two ago on the test server, thought that it was a test server only bug just like trying to spawn as an AI on the test server.

**Comment by gbasood** [comment]
Looks like it's triggering hte universal state's OnEnter multiple times

**Comment by gbasood** [comment]
``` DM

/obj/machinery/power/supermatter/ex_act(severity)
    switch(severity)
        if(3.0)
            return //Should be improved
        else
            return explode()

/obj/machinery/power/supermatter/proc/explode()
    explosion(get_turf(src), explosion_power, explosion_power * 2, explosion_power * 3, explosion_power * 4, 1)
    new /turf/unsimulated/wall/supermatter(get_turf(src))
    SetUniversalState(/datum/universal_state/supermatter_cascade)
    empulse(get_turf(src), 100, 200, 1)
    qdel(src)
```

Oh my god are you fucking kidding, THIS CODE

> on explode
> explode some more!
