### ISSUE TITLE
Nerf/remove diona

### ISSUE THREAD

**Issue by Manaony** [d3athrow/vgstation13#9021]
It's that time of the year again, diona are too tanky and have no drawback due to lol 1000 unit of hyperzine and it doesn't kill me.

Edit: Did I mention that space can't even kill them even without internal? Fair and balanced.

**Comment by ShiggyPiggy** [comment]
I like it tbh

**Comment by ShiggyPiggy** [comment]
I like it tbh

**Comment by Kitfox88** [comment]
make it so drugs don't affect them :^)

**Comment by Intigracy** [comment]
> Edit: Did I mention that space can't even kill them even without internal? Fair and balanced.

Prove

**Comment by Manaony** [comment]
> Prove

Is a 10 minutes period going to be enough or do I have to wait until the round end?

**Comment by AutismSpider** [comment]
If any thing bloodless races should not be affect by drugs more or less dionas and plasma men

**Comment by Shadowmech88** [comment]
Diona take something like 2.5x burn damage, and laser weapons are the most common weapons in the game.
You can even fuck a diona up with just a welding tool.

**Comment by AutismSpider** [comment]
@Shadowmech88 don't even need a welding tool tossing flares at them does shit ton of damage or non antag flare gun will down them fast keep in mind laser cannon does 100 burn to them.

**Comment by Manaony** [comment]
I admit I was exagerating, it only took 13 minutes to die.
![diona330](https://cloud.githubusercontent.com/assets/11906227/14029316/baf82e04-f1d7-11e5-9a95-0364807cc94d.png)
![iwaswrong](https://cloud.githubusercontent.com/assets/11906227/14029331/d2c4d0dc-f1d7-11e5-822b-a401349c3104.png)

**Comment by Exxion** [comment]
> no drawback

They take vastly increased burn damage and are completely vaporized when the other races get husked by burn damage. Also, they are the only race capable of being stuck in permanent crit-limbo.

**Comment by 9600bauds** [comment]
They get instahusked by lasers and weldingtools
If you want a race with ridiculous upsides but little to no drawbacks then look at plasmamen.

**Comment by coldcola** [comment]
I'm not completely sure but the Plasmamen seem to be able to go into the permanent crit-limbo under the right circumstances as well.

Make Dionae valid outside of botany without special badge given by HOP or something, even though I don't like them some players aren't complete shitters when they play them.

**Comment by Exxion** [comment]
Make diona _nymphs_ valid when outside botany, sure.
Don't do that to full-grown dionae because that's stupid.

**Comment by Shadowmech88** [comment]
Diona nymphs are already as valid as monkeys are.

**Comment by Exxion** [comment]
Really? Huh.

**Comment by Imagebard** [comment]
Diona Nymphs aren't valid if they have a "soul" inside of them. NPC nymphs that die off quickly are, tough.

**Comment by Exxion** [comment]
Well no shit those are valid
Not only are they NPCs, they're doomed NPCs

**Comment by Shadowmech88** [comment]
Diona nymphs are valid even if they have a soul, which is why you're allowed to murder them without penalty if they greentide. I have myself been told this by an admin after I myself was murdered for greentiding as a diona nymph.

**Comment by ihadtoregisterforthis** [comment]
@coldcola Plasmamen don't go into permacrit because they start suffocating.

**Comment by gbasood** [comment]
I'm against removing dionae but they've needed a rework to how they heal/take damage for a LONG time.

Maybe stop healing in crit for starters I don't know

**Comment by Exxion** [comment]
Dionae really aren't that overpowered against other players
They are absurdly overpowered against simple mobs, but there's not that great a problem with that
Because, remember, they take vastly increased burn damage and never heal it without drugs

Actually, there is one slight nerf that should probably be applied
Currently, a diona's bones can be broken, but the break stops having any effect after a few seconds
Fix that and I don't really see a problem with them

**Comment by Intigracy** [comment]
Well the bones are supposedly made of plant material, I'd assume they'd regrow.

**Comment by Exxion** [comment]
Yes, but currently they stay broken, just have no effect
Which means that once a diona's hand is broken then heals, it can never be broken again unless it is properly fixed
This applies to all bones but is only really a problem for hands

**Comment by Imagebard** [comment]
>I have myself been told this by an admin after I myself was murdered for greentiding as a diona nymph.

Okay then.
But just for reference, which admin?

**Comment by Intigracy** [comment]
nymphs are treated the same way as monkeys fam
shitters get their heads knocked in

**Comment by ihadtoregisterforthis** [comment]
Enable hardcore mode permanently on them.

**Comment by Manaony** [comment]
> Dionae really aren't that overpowered against other players
> They are absurdly overpowered against simple mobs, but there's not that great a problem with that
> Because, remember, they take vastly increased burn damage and never heal it without drugs

Considering you people keep adding vault with good shit in them and the only defense are simple mob yes it's a problem,

**Comment by Intigracy** [comment]
Not really, none of the vaults have superawesomeOPloot.

**Comment by AutismSpider** [comment]
@Intigracy >free hulk and an emag is not super awesome loot were all you got do is dig out some walls to dodge all the mobs for the power hulk then smash down some R walls for the emag

**Comment by Intigracy** [comment]
Not really, none of the vaults have superawesomeOPloot.

**Comment by 9600bauds** [comment]
If diona regen is to be nerfed, easy fix
Just make it require 5 seconds of no damage to kick in

**Comment by Exxion** [comment]
That wouldn't do much to nerf them against simple mobs considering simple mobs stop attacking when the target is in crit
It is literally impossible for most simple mobs to kill dionae right now

**Comment by Boxe** [comment]
familia i don't think dionae should gain any benefits from hyperzine, but they should move much faster than the current crawl they're forced into

as of now it's either go blood eagle or go sandraker

**Comment by ghost** [comment]
Aren't they trees/plants?

Make them bleed sap, have to go to the chef for a transfusion of maple syrup if they get dinged up too much

Give them a third-stage that happens some time after becoming an 'adult' where they just end up as a tree rooted to the ground, maybe make it dependent on their time exposed to light

![Harold](http://farm4.static.flickr.com/3257/3083875361_0726dfeaf0.jpg)

That'd give em a good reason to rush around on hyperzine, their life is finite unless they get brainswapped.

**Comment by Shadowmech88** [comment]
Literally no one would play the race if they were guaranteed to become immobile after a set amount of time.

**Comment by uazuaz** [comment]
what if they need to stand still to regen?

**Comment by gbasood** [comment]
Naaaah
I'd rather just make their regen less ridiculous
If we compare the racial bonuses dionae get against other racial bonuses (vox, plasmamen, greys), they have a clear advantage from the perspective of a powergamer
Greys are maybe a better example of how dionae should be balanced. They have a neat power but they also have downsides
Dionae downsides are so easy to deal with because of hyperzine that it's just plain silly

Side note, the fact that dionae's worst enemy is fire makes me think of The Thing

**Comment by Manaony** [comment]
How about having diona needing a tray to regenerate?

**Comment by Exxion** [comment]
Honestly, all we need is more burn-dealing simple mobs

**Comment by gbasood** [comment]
@Exxion It takes them 13 minutes to die IN SPACE
Not having enough fire is not the issue

**Comment by Exxion** [comment]
And in their lore they LIVE in space, albeit much closer to the sun

**Comment by Manaony** [comment]
> And in their lore they LIVE in space, albeit much closer to the sun

Actually they only go in space to became their fucking Gestalt shit that's not even a thing ingame according to our wiki

**Comment by Exxion** [comment]
Anyway, yeah, people don't seem to get JUST HOW BADLY burn damage wrecks them. A laser gun can crit them before they take two steps. I see that as a pretty OK tradeoff for being basically immune to brute damage and the only issues I see are
1. Bone thing I mentioned above
2. Almost no simple mobs deal burn damage

Also, they don't regenerate if they aren't in a turf, so stuff a critted diona in a locker and they'll die

**Comment by Shadowmech88** [comment]
What about making it so they don't regenerate without oxygen in the atmosphere, so they don't regenerate in space or when fighting asteroid mobs?

**Comment by Exxion** [comment]
Basilisks can already fuck them up because they can deal burn damage
Goliaths are little more than annoying to dionae, though

**Comment by Intigracy** [comment]
@Shadowmech88 finally a reasonable solution. No oxygen = no regenerating

**Comment by Exxion** [comment]
Except that would make them 100% useless anywhere except the station
They would have all their drawbacks but none of their advantages
They would be far weaker than the other races rather than in line with them

Dionae are minmaxed to fuck, but not really any more powerful than other races except against simple mobs

**Comment by Shadowmech88** [comment]
What drawbacks? Being slow?
The burn damage is irrelevant because they don't regenerate burn damage anyway.

A diona on hyperzine would be almost as capable as a human outside the station.

**Comment by Exxion** [comment]
They still take like 2.5x burn damage

**Comment by Shadowmech88** [comment]
Yeah, but they'd take that anyway whether or not they had their regeneration. And they wouldn't regenerate it whether or not they had their regeneration.
Removing their regeneration wouldn't make their burn penalty any better or worse.

**Comment by Exxion** [comment]
Right, but it WOULD make them objectively weaker than any other race while not on the station

**Comment by Shadowmech88** [comment]
As opposed to when they're on the station, and you can crit one with three welder strikes? That's not weak?

**Comment by Exxion** [comment]
It is
That's my point
They don't need to be nerfed

**Comment by Shadowmech88** [comment]
They need to be nerfed against non-human mobs. A single diona shouldn't be able to solo three goliaths armed with nothing but a pickaxe.
And then there's the fact of them taking over 10 minutes to die of space exposure.

**Comment by Exxion** [comment]
Have you tried that?
It's technically possible, but it takes about an hour and you get critted like twenty times if you trip once

**Comment by Shadowmech88** [comment]
Not myself, but I've seen others do it.

**Comment by Exxion** [comment]
I've only fought as many as two goliaths and a hivelord at once, and while I did win, it was awful and took forever
And why do simple mobs stop attacking once you're in crit, anyway?

**Comment by Shadowmech88** [comment]
My guess would be that they're set to not attack sleeping mobs so that defenseless players don't get murdered, but the same check is fulfilled by the mob being in crit as well.

**Comment by ihadtoregisterforthis** [comment]
They are honorable and don't attack unconscious prey. Sleep works just as well.
I would assume this is taken in a weird way from bears not attacking you if you fake being dead.

**Comment by AutismSpider** [comment]
being in crit counts as sleeping for god knows what

**Comment by Shadowmech88** [comment]
Maybe just make it so asteroid mobs don't care whether a diona is in unconscious or not.

**Comment by Exxion** [comment]
I'd go for that.

**Comment by AutismSpider** [comment]
make it count for all races really  mobs don't don't stop beating on you until you die  or play dead using sleep verb

**Comment by uazuaz** [comment]
you can also use the *faint emote, it's the same as the sleep command but it lasts for about 20 seconds only; goliaths will ignore you, never tried with other mobs but i can assume that it works as well.

**Comment by ghost** [comment]
Remove roundstart diona

**Comment by Cisrox** [comment]
Remove roundstart diona, please

**Comment by Intigracy** [comment]
That's a fair solution.

**Comment by Imagebard** [comment]
Wait up
Genius

If you remove roundstart diona, you get more people going spectator and waiting to become a Diona, right?
That would also give the admins more spectators to play with. Which means Diona players get involved in adminbus more often, and become Diona less.
Its a win/win

**Comment by ghost** [comment]
Or they just switch over to plasmaman if they're the sort that just wants a natural advantage over others in combat

**Comment by Exxion** [comment]
They'd already be plasmamen if they wanted advantages in combat against players

**Comment by AutismSpider** [comment]
no they shit up plasma men for power gaymen needs they take close to no burn damage form laser gun hits or being shock by air locks etc no blood is a huge + and free space suit does not slow them down but the vox space suit slow them by fuck ton

**Comment by Blithering** [comment]
Variety is the spice of spess. Removing races isn't the way to go. I'm not a fan of removing their unique features either.

**Comment by uazuaz** [comment]
make hyperzine slightly toxic for dionae, so they can still use it but not so much

**Comment by Shadowmech88** [comment]
Diona heal toxin damage just by being in light.
You'd have to make it _very_ toxic to diona for them to feel any effect.

**Comment by Exxion** [comment]
Dionae already typically take 3-6 times the overdose limit of hyperzine

Also, dionae do not heal when not directly in turfs, so dionae hopped up on hyperzine can't pilot mechs and get fucked if they're in lockers

**Comment by ihadtoregisterforthis** [comment]
Don't damage them if they are inmune to damage. Give them effects like hallucination, proper blurry vision, vomit, CeltCode™ "visean filters"© .
Don't go crazy with it because as much powergaming as 1000 units of hyperzine at roundstart might be, few people can stand moving so slow. Make it useable but not abuseable for free.

**Comment by ghost** [comment]
Vision based on movement, the faster they move, the weirder things get

**Comment by jknpj** [comment]
Already nerfed.
