### ISSUE TITLE
Roburgers turn you into MoMMI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9022]
(WEB REPORT BY: yred REMOTE: 158.69.55.2:7777)

> Revision b79173c4c3310fecd7118b54430b239334bda6c8 
> 
> What you expected to happen
> Roburger turn you into borg.
> 
> What actually happened
> MoMMIs you instead.
> 
> Steps to reproduce if possible
> Make a roburger and eat it.

**Comment by Shadowmech88** [comment]
It looks like that one roburger in #8780 wasn't an isolated case.

**Comment by clusterfack** [comment]
Dupe of that issue
