### ISSUE TITLE
Space law books wrong page

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9023]
(WEB REPORT BY: jakedb REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b79173c4c3310fecd7118b54430b239334bda6c8
> 
> General description of the issue
> Space law books now direct to the security officer guide, not the actual space law
> 
> What you expected to happen
> To see space law
> 
> What actually happened
> I saw the wiki page for security officer
> 
> Steps to reproduce if possible
> 1. open space law book
> 2. look at page

**Comment by clusterfack** [comment]
Yeah it very clearly has space law in the book I'm looking at. Not sure what he was expecting different than this, is it the fact it shows the entire space law page instead of just crimes and sentencing? I'm definitely not getting the wiki page for security officer.
