### ISSUE TITLE
Nuke Ops ship crashes on part of Atmos on Deff

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#9024]
![rogue fortress three 2016-03-24 203012](https://cloud.githubusercontent.com/assets/13305885/14034539/cec26faa-f202-11e5-8dcf-43805c830659.png)

Let's think together why this can be an issue

**Comment by FudgePucker** [comment]
Its convenient for the ops, now they know where the ship is instead of having to guess where in space it is :^)
For realsys, I have never found my way back to the ship before in ops, I always end up fucking off into space and ending up in another zlevel after we set them up the bomb.

**Comment by Probe1** [comment]
leave a trail of fudgecrumbs so you can get home.
