### ISSUE TITLE
Gas Mole Duping using Pipe Wrench

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9038]
(WEB REPORT BY: mxr41 REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
>  9c7dc21897493b5d1ba727421f08fab44d82fa95
> 
> General description of the issue
> Moles of gas can be duplicated using a pipe wrench.  Unwrench a pipe in a airtight room, the room will instantly take on the pressure of that pipe, reguardless of how many moles of gas were in the pipe.  This creates more moles of gas, which can be then sucked up using scrubbers to reach insane pressures quickly. 
> 
> What you expected to happen
> Very, very high pressures (obtained up to 10^20 kPa in one test, higher is easily possible.
> 
> What actually happened
> High pressures
> 
> Steps to reproduce if possible
> See above. Use a larger room to produce more gas (volume increases, generated moles of gas will increase)

**Comment by Intigracy** [comment]
@Clusterfack is a real hero, totes brave enough to touch atmos to fix this.

I believe in you!

**Comment by ihadtoregisterforthis** [comment]
He at least knows what's going on in there

**Comment by gbasood** [comment]
Sounds like pipes are dumping an entire network's worth of atmos in without emptying out the rest of the network
