### ISSUE TITLE
Xenoarch Woes

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#9044]
While xenoarch is mostly enjoyable for me, I have a few problems with it.

First of all, a couple of the large artifacts, which should be without burden to find, are complete shite. For example, the hoverpod. This garbage artifact is supposed to be something aliens used, however it is slow as shit, even slower than a Ripley. I would suggest making it faster, and having it be a utility that xenoarch can use, such as allowing it to transport one or two other large artifacts. I shouldn't be punished after spending 30 minutes looking for something. Another example is the cult pylon, which is a large artifact for whatever reason, that does literally nothing, same goes for the large crystals except those give glass if you break them, and they're moveable, unlike their pylon relative, which makes them a bit better.

Secondly, trace organics are also complete shite. The only things you can do with them are assemble a skeleton that does jack shit, or give botany aliens plants, which is the only thing this type of small artifact does. It's mostly a pain in the ass, and a burden, because literally nobody actually digs it up, I know if I scan a trace organic site. I'm booking it out of there.

Furthermore, the job has almost no use for the station, the only thing I can recall it being useful for is to give botany plants, and MAYBE if you find a SINGLE positive artifact that does something like charge borgs, or apcs. Currently, the state of this job is a useless job that only benefits the person doing it, unlike almost every other job, which at least helps out other departments, such as chemistry, robotics, etc.

**Comment by Intigracy** [comment]
pylons emit light iirc.

But yeah xenoarch sucks.
