### ISSUE TITLE
Horror Form Slamsed

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#9045]
Horror form has a terrible bug, and yet nobody has addressed this. Just hit someone as a horror form ling.

Horror Ling has slamsed Cisrox!
You feel something ripping in your chest!

**Comment by Kitfox88** [comment]
slamsed, son

**Comment by gbasood** [comment]
Problem is human_attackhand.dm line 314:

``` DM
            visible_message("<span class='danger'>[M] has [M.species.attack_verb]ed [src]!</span>")
```

And horror.dm line 6:

``` DM
    attack_verb = "slams"
```
