### ISSUE TITLE
Plant Deletion from Biogenerator

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9046]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 9c7dc21897493b5d1ba727421f08fab44d82fa95
> 
> General description of the issue
> Items cannot be removed from the biogenerator, also if you remove the circuit from the biogenerator with a plant inside, it is deleted from the universe.
> 
> What you expected to happen
> I'd be able to get my plant back
> 
> What actually happened
> My plant got deleted
> 
> Steps to reproduce if possible
> Put a plant in biogenerator
> Remove beaker
> Screwdriver
> Crowbar
> No plant

**Comment by Exxion** [comment]
It needs an eject plants button, basically
Also `EJECT_NOT_DEL` or whatever that machine flag is called

**Comment by Cisrox** [comment]
How is this a feature request, the plants shouldn't be getting deleted when you deconstruct the machine

**Comment by Exxion** [comment]
It's a feature request in that you want an eject button for the plants
Also nobody really cares about tags

**Comment by PJB3005** [comment]
Technically it's a feature request because they're _requesting_ code to make it _not_ delete things when deconstructed.

**Comment by Exxion** [comment]
It's more of an oversight
Someone just didn't think to give it `EJECTNOTDEL`
