### ISSUE TITLE
How we can get preload_rsc working

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9050]
## Why it hasn't been working previously

preload_rsc does not do a single thing if it's changed in client/New(). It has to be set BEFORE a client attempts to join, otherwise they just download the rsc via the game server.

Good news, it works fine when defined at build time. Tested with @clusterfack on a local server.
## Why preload_rsc is finnicky for us

When something in the rsc changes, we might end up with the sort of fucky shit that happens currently when a build fails and the rsc is corrupted. There's a few solutions to this:
## What we can do to fix this and make it work:

First of all, let me just say that the rsc zip that preload_rsc takes is literally just a zip with the .rsc file inside.
### Option 1: Generate new rsc.zip every time we get a commit

In client defines.dm, we'd need to set client.preload_rsc to an external URL pointing to the rsc zip.
For the watchdog script, we'd need it to update the rsc.zip URL before building a new commit EVERY TIME to prevent caching issues (i.e.
The watchdog would have to modify client defines.dm to point the preload_rsc var to the new ZIP before building for the serbian.

This would mean that clietns would be re-downloading the rsc every time there'd be a new commit.
### Option 2: set world.cache_lifespan to 0

This would mean that clients would have to re-download the rsc for every new session. (Whether 'session' means Dream Daemon session or client session I have no idea)

Might increase bandwidth usage
### Option 3: set world.cache_lifespawn to 1

So rsc caching would last a full day before clearing out, reducing load somewhat, but still having the possibility of introducing graphical issues.
### Option 4: Make a custom resource package as needed (watchdog possibly)

preload_rsc zips can actually just contain all the shit that would be included in the rsc file as loose files within the zip. This potentially means no errors. But I have no idea how this would work, so I don't know how this works at all.

All this is up to @d3athrow though

**Comment by gbasood** [comment]
Also, the reason we'd want to use preload_rsc is because it reduces game serb load when a player joins

**Comment by d3athrow** [comment]
What

**Comment by Exxion** [comment]
This issue predates the CDN
We have this now
