### ISSUE TITLE
Certain AME part has no sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9051]
(WEB REPORT BY: cisrox REMOTE: 158.69.55.2:7777)

> Revision 537a8e757b2360f6f78e8e8335f30bd58beef948
> 
> General description of the issue
> I think when an ame is only connected upward it has no sprite for that, it goes invisible
> 
> What you expected to happen
> I could see my part
> 
> What actually happened
> It was invisible
> 
> Steps to reproduce if possible

**Comment by SGuivenne** [comment]
Fairly certain this has since bee resolved
