### ISSUE TITLE
Job availability dependent on species selection

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9052]
If there were some way we could have it that job selection is dependent on your species, not only could we bring in some of the more forgotten species that are still in the coderbase (Unathi would be confined to service and the janitorial duties, etc.) , and make it so you can't have, say, a diona as captain which wouldn't make much sense on a station which is run with a bias towards humans, but could also have unique jobs for said species so as to make it easier for them to be spawned elsewhere.

This would mean that you could have, say, vox could have 'Vox trader' or 'Vox miner' or 'Vox botanist' etc. that would put them in the vox outpost, plasmaman could have 'derelict survivor' that would put them somewhere on the derelict, greys or skrells could have '[species] doctor' that would put them on the medical shuttle.

Just something to give a bit more customization, and finally give some use to the vox outpost besides a landing zone for the vox shuttle

**Comment by gbasood** [comment]
> bring in some of the more forgotten species that are still in the coderbase

I thought we hated those because /tg/ liked them too much?

**Comment by Intigracy** [comment]
what next, roundstart catbeasts?

**Comment by Kitfox88** [comment]
moth people when

**Comment by ihadtoregisterforthis** [comment]
Bone people when
