### ISSUE TITLE
exosuit fabricator not Emaggable

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9054]
(WEB REPORT BY: manfreed REMOTE: 84.163.130.254:54074)

> General description of the issue
> The exosuit fabricator cant be emagged to allow anyone to use it.
> 
> What you expected to happen
> To be able to emag and use a exosuit fabricator without the propper ID.
> 
> What actually happened
> Unauthorized Access: attempted by ...
> 
> Steps to reproduce if possible
> -Take emag
> -apply to exosuit fabricator
> -watch in awe as nothing changes

**Comment by gbasood** [comment]
On one hand, it clearly has the flag ACCESS_EMAG.
On the other, it has no emag-specific code.
