### ISSUE TITLE
Deff atmospherics still has an air pipe from its old iteration

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9056]
![image](https://cloud.githubusercontent.com/assets/8550416/14062421/715ce214-f374-11e5-84ef-24777112eaba.png)

You can see it here leading to nowhere.

**Comment by clusterfack** [comment]
Why is it lit up like that?

**Comment by Probe1** [comment]
I think the pipes you're currently in are lit up.

**Comment by Intigracy** [comment]
Yes.

**Comment by MrSegi** [comment]
Whoops, guess I will go ahead and fix this.
