### ISSUE TITLE
Spider Queens see through walls

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#9057]
_or_ **Great Coding Elim**

Super spiders can target mobs or light fixtures hidden by walls, and they likely get stuck if they can't destroy it
Note that this happens with skrites too, they shoot rentlessly agains mobs that they can't see, seen for example when trapped on a pen on Xenobio.

`Armin PM from-Probe1: Make a bug report describing it and recommend they add a debug output to the  spider queen to give the coordinates of what its attacking.`

**Comment by 9600bauds** [comment]
this is not a feachur

**Comment by gbasood** [comment]
Bug title describes a separate issue than webbing endlessly through walls

**Comment by gbasood** [comment]
To clarify:
**spiders should not select anything as a target that they do not have line of sight on**

and also:
**webs should not be placed twice on the same tile**

**Comment by clusterfack** [comment]
I don't really understand how they would be seeing 'through walls'

**Comment by gbasood** [comment]
@clusterfack probably because they use `range` or `orange`

**Comment by Shadowmech88** [comment]
Tested locally, no longer happens. I created a spider queen in a rectangle of walls, it did not react to the lights outside the walls until I removed one of the walls so that it could see one of the lights.
