### ISSUE TITLE
Call shuttle doesn't have a cancel button on the reason box

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#9058]
Tbh the yes/no prompt before the reason box should be removed, and just have it have the message box with a cancel button.

I was AI, might be on all of them (admin and console), might not.

**Comment by ihadtoregisterforthis** [comment]
Did you try leaving it on blank? For example the cargo console cancels the order if there isn't a reason at all.

**Comment by Intigracy** [comment]
Yes. It gave a random garbled reason.
