### ISSUE TITLE
Plasmamen UI tank valve

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9059]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 537a8e757b2360f6f78e8e8335f30bd58beef948 
> 
> General description of the issue
> Plasmamen can close the tank via the UI button but not re-open it
> 
> What you expected to happen
> Press the button to turn it back on 
> 
> What actually happened
> "You don't have a toxins tank."
> 
> Steps to reproduce if possible
> Drop tank on floor.
> Pick it back up
> Put it on suit slot
> Press the UI button.

**Comment by FudgePucker** [comment]
I bet this is due to changing the parent from plasma tank to o2 tank to let it be equitable in the back slot.

If so I am two for two

**Comment by gbasood** [comment]
If you want to fix it check what got fixed in #9037 and see what needs doing to fix this particular instance

**Comment by 9600bauds** [comment]
Dupe & fixed
