### ISSUE TITLE
multi stacks of materials consumed as MoMMi

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9060]
(WEB REPORT BY: runicbeast REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

537a8e757b2360f6f78e8e8335f30bd58beef948 

> General description of the issue

I was replacing solar panels as a MoMMi with Reinforced Plasma glass. I had one stack of 50 in my inventory and one stack of 50 in my hand. Upon replacing the last solar panel, when the stack from my hand was consumed, so was the stack in my inventory. I do not know if this occurs with other materials as i only noticed with the plasma glass.

> What you expected to happen

That only the stack in hand would be consumed.

> What actually happened

Both stacks consumed

> Steps to reproduce if possible

Fabricate two stacks of 50 plasma glass and use up all the sheets in one on replacing solars.

**Comment by Shadowmech88** [comment]
Possibly related to #8934.

**Comment by Shadowmech88** [comment]
No longer happens.
