### ISSUE TITLE
Fairy wings make your jumpsuit not display.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9063]
(WEB REPORT BY: konater REMOTE: 158.69.55.2:7777)
Sorry I don't know the flag or whatever. Putting fairy wings on reveal your underwear to all despite having a jumpsuit on.

**Comment by AutismSpider** [comment]
3rd or so issue about it

**Comment by Intigracy** [comment]
it's because you're a fairy

fuckin queer

**Comment by Konater** [comment]
I looked it up and didn't find any outstanding issues

**Comment by Intigracy** [comment]
#8497
#8595 
not dupes, but related.
