### ISSUE TITLE
PanD.E.M.I.C 2200 has no icon

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9065]
(WEB REPORT BY: probe1 REMOTE: 158.69.55.2:7777)
http://i.imgur.com/F5yshsa.png
picnic

**Comment by PJB3005** [comment]
Why would we care about an adminbus only machine?

**Comment by Cisrox** [comment]
Pretty sure there's a board for it in tech storage

**Comment by PJB3005** [comment]
Is there? I know for a fact it's not intended to exist anymore though.

**Comment by Cisrox** [comment]
![123456789](https://cloud.githubusercontent.com/assets/11482753/14066624/04f7bb0e-f41d-11e5-85c9-f3f933b1aca9.PNG)
