### ISSUE TITLE
cant wrench  rechargers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9067]
(WEB REPORT BY: pvak REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> once you unwrench the recharger you cant wrench it back anymore and it says 
> "The recharger isn't connected to a power source."
> even if you put it in the same position it was
> 
> What you expected to happen
> wrench the recharger
> 
> What actually happened
> cant wrench it
> 
> Steps to reproduce if possible

apply wrench to recharger

**Comment by Intigracy** [comment]
oops
