### ISSUE TITLE
After building a sound system, you need to do tech support step 1 or it won't work.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9069]

**Comment by uazuaz** [comment]
sorry, what does "tech support step 1" mean?
i think that you just need to put the new sound system off and then on again.

**Comment by Intigracy** [comment]
That's what tech support step 1 means.

"Have you tried turning it off and back on again?"
"Are you sure it's plugged in?"

**Comment by uazuaz** [comment]
ok, thanks for clarification.
