### ISSUE TITLE
Slowdown when wielding certain weapons no longer works

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9082]
With weapons like the gatling gun, the Nikita, and the Hecate, that require wielding to be able to use, when wielded they're supposed to apply a slowdown effect.

`/obj/item/weapon/gun/gatling/update_wield(mob/user)
    item_state = "minigun[wielded ? 1 : 0]"
    if(wielded)
        slowdown = 10
    else
        slowdown = 0`

Despite still being there in the code, the slowdown is no longer applied if you two-hand the weapon

> What did you expect to happen
> Wielding a gatling gun in both hands to slow me to a dramatic crawl so people have a chance to run away
> 
> What happened
> zipping around shooting people with a gatling gun

Currently doesn't work for the above listed weapons

**Comment by Killette2** [comment]
Someone didn't skip leg day. Speaking of, what if getting buff on the treadmill with your super muscular arms, removed this effect? If you're buff as fuck, you should be able to run around with heavy weapons faster than some wimp.

**Comment by unid15** [comment]
They're missing a flag, I think it's SLOWDOWN_WHEN_CARRIED. Currently only lances and offhands have it

**Comment by Imagebard** [comment]
I think this might be related to that PR that fixed shoes making you go faster if you held them in your hand.

**Comment by clusterfack** [comment]
Actually no, that worked fine. Like unid said his PR broke it.

**Comment by Shadowmech88** [comment]
Tested locally, gatling gun applied its slowdown properly.
According to the code, the Hecate is not intended to slow the user down when wielded, and the Nikita doesn't require wielding at all.
