### ISSUE TITLE
cant see the new chat

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9083]
(WEB REPORT BY: pvak REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

https://imgur.com/LwpNxBc

> What you expected to happen
> see the chat
> 
> What actually happened
> cant see the chat
> 
> Steps to reproduce if possible

join the server

**Comment by Exxion** [comment]
Works fine for me. Did you try restarting?

**Comment by pvak** [comment]
yes

**Comment by pvak** [comment]
changed vm and it werks
I guess windows xp was the problem

**Comment by PJB3005** [comment]
@pvak yes, that would be it. Update IE to IE 8 in Windows XP.

**Comment by PJB3005** [comment]
Closing because it's really not an issue since IE 8 is available on XP.
