### ISSUE TITLE
Goonchat works surprisingly well but that's not saying much and it's still broken

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9084]
1. Human icons are monumentally fucked
2. ~~Linebreaks are gone~~ This has been fixed
3. ~~All icons are very tiny~~
4. ~~Links don't work~~
5. I have not personally confirmed this, but according to the thread, PDA messages don't show up in chat, at least for the AI

**Comment by PJB3005** [comment]
Working on fixing linebreaks, I know why human icons are bust and I'll look into a fix.

**Comment by Exxion** [comment]
You fixed linebreaks but now all the icons are tiny
As in 1-2 pixels in size

**Comment by ihadtoregisterforthis** [comment]
![invisible items](https://cloud.githubusercontent.com/assets/13305885/14068939/03986e20-f468-11e5-9825-d3f176627797.png)

**Comment by NigglyWiggly** [comment]
You can't click links. Don't forget that.

**Comment by Exxion** [comment]
How did I forget to add that?

**Comment by ihadtoregisterforthis** [comment]
Roundstart text with the server adress and such gets deleted or just doesn't appear.

**Comment by gbasood** [comment]
I can click links fine myself

**Comment by Exxion** [comment]
Well I definitely can't

**Comment by PJB3005** [comment]
Links are fixed, blame the secret repo.

I have NO idea why icons are fucked, they work fine locally.

**Comment by PJB3005** [comment]
I can't fix the bug with human icons, (once icons work again), it's a BYOND issue.

**Comment by Exxion** [comment]
How so?

**Comment by NigglyWiggly** [comment]
So what you're saying is 

Revert goonchat 2016?

**Comment by clusterfack** [comment]
Whats it caused by?

**Comment by PJB3005** [comment]
@clusterfack for some BYOND reason the code to get 1 specific dir from the icons humans use gets all 4 dirs no matter what, the 4 dirs are encoded as 4 dirs and they get rendered as such.

**Comment by clusterfack** [comment]
Which proc so I can read it too

**Comment by PJB3005** [comment]
`/proc/bicon()`

**Comment by Iamgoofball** [comment]
@NigglyWiggly you're an idiot, we can just ask lummox to fix it

**Comment by NigglyWiggly** [comment]
Because that's worked out so well in the past

(I do not know if that has worked out in the past I just felt like I needed a snarky response.)

**Comment by Iamgoofball** [comment]
well maybe when you guys constantly talk about making sure he doesn't get money and goes broke so he's "forced" to open source, he's slightly less keen on helping you guys

**Comment by PJB3005** [comment]
^

**Comment by NigglyWiggly** [comment]
I have no idea what you're even talking about

**Comment by ihadtoregisterforthis** [comment]
Saving the chat log gives some html nonsense as text (on an IE window), which has to be saved as .html and then opened again to be readable.

**Comment by 9600bauds** [comment]
![dreamseeker_2016-04-04_19-26-46](https://cloud.githubusercontent.com/assets/6526157/14267368/2d5e92ea-faa6-11e5-9565-3e0cb74a421a.png)
Please, this is still fucked

**Comment by Exxion** [comment]
There's no obvious correlation between the person examined and the icon that shows up for them
It often shows vox when examining non-vox and vice versa

**Comment by PJB3005** [comment]
I made a bug report for the human icons thing.

http://www.byond.com/forum/?post=2065076

**Comment by Iamgoofball** [comment]
Wait, you're using 509?

why not 510?

**Comment by PJB3005** [comment]
Because it's not stable yet.

**Comment by Iamgoofball** [comment]
eh, it's pretty stable

**Comment by ihadtoregisterforthis** [comment]
Boy, chatting on Goon must be hell  :^)

**Comment by ihadtoregisterforthis** [comment]
Bring .ping back

**Comment by PJB3005** [comment]
I literally can't.

**Comment by PJB3005** [comment]
http://www.byond.com/forum/?post=2069511

I'm trying

**Comment by Exxion** [comment]
I'm still trying to figure out what went wrong with the jukebox announcing songs as they start
I can't even find the code that made it do that before
It 100% definitely isn't in jukebox.dm and I couldn't find it with a quick search of the entire codebase

Is there a way to disable Goonchat on local? I want to test something.

**Comment by PJB3005** [comment]
@Exxion you could modify `to_chat`, then edit the skin file so the specials tab is "default"

**Comment by Exxion** [comment]
Well human icons are still kind of fucked, but this is not really a major thing anymore

**Comment by NigglyWiggly** [comment]
But it is still fucked 
How is this not still a thing

**Comment by Exxion** [comment]
Because at this point, only like three things are still fucked, and they should be reported separately
And two already are
