### ISSUE TITLE
Clown goblins (and presumably all retaliate mobs) become hostile to everyone when they take damage from any source

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9085]
You'd best hope there isn't a hull breach when you're dragging around your nice pet clown goblin

**Comment by SysadminJeroen** [comment]
You gotta keep your pet clown goblin happy.

**Comment by ghost** [comment]
You'd think retaliate mobs would retaliate against those who wronged them

**Comment by Intigracy** [comment]
The world wronged them.

**Comment by Probe1** [comment]
that's what makes it so funny.  they're gobbin along minding their own business then someone punches one and they swarm everyone.

**Comment by Exxion** [comment]
That's fine, but environmental damage shouldn't set them off

**Comment by liltiptop** [comment]
> That's fine, but environmental damage shouldn't set them off

Who do they attack if that happens? Atmos techs? That'd actually be kinda funny.

**Comment by gbasood** [comment]
Not a bug they always worked this way
They add everyone in view to their targets when they get attacked
If someone wants to change it then they're welcome to though

In regards to 

> You'd best hope there isn't a hull breach when you're dragging around your nice pet clown goblin

They only retaliate on brute damage I think

By the way, I think retaliate mobs might be keeping refs on mobs which prevents proper garbage collection, someone should check that out if they change how retaliate mobs work
