### ISSUE TITLE
Add Adminbus Button to Disable IC Chat Sanitization

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9088]
Because everyone loves broadcasting images via radio.

**Comment by SysadminJeroen** [comment]
ROGAN

**Comment by SangriaMonkey** [comment]
why was this shit merged holy fuck

**Comment by SysadminJeroen** [comment]
@SangriaMonkey Old bug, easy to overlook such a small detail in a relatively large codebase.

**Comment by Shadowmech88** [comment]
Also, maybe disable sanititzation for admins by default so the admins can inject their dank memes directly into the chat.

**Comment by SysadminJeroen** [comment]
@Shadowmech88 rogan.mp3

**Comment by Intigracy** [comment]
Admins can already use HTML on global narrate and make sound.
