### ISSUE TITLE
New chat shit allows uploading audio and image/gif files into all chat

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#9089]
at least log that shit holy fuck someone uploaded a ten minute file of just "rogan" over and over while others spammed dogememes the hell is going on I go to a urban chickenkeeping class for three hours and this happens

**Comment by Jeroen52** [comment]
ROGAN

[It should be fixed already.](https://github.com/d3athrow/vgstation13/pull/9087)

**Comment by liltiptop** [comment]
ROGAN

**Comment by clusterfack** [comment]
As said, it was fixed immediately upon being noticed
