### ISSUE TITLE
Null rod reskin for paladin chaplains

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#9090]
Since the crusader armour was introduced to the vendors, knight gimmicks have become commonplace. Usually this includes welding a bunch of knives together to make a suitable blade, and risk security confiscating it. 
I thought it might help to have chaplains who choose a suitably knightly deity have their null rod icon change to a holy avenger style sword, as they're known for kicking unholy arse. Other chaplains could have either a spell/ritual to alter their null rod, or otherwise be at the mercy of their god's good graces. 
![avenger](https://cloud.githubusercontent.com/assets/15067109/14068746/2625a0da-f485-11e5-92d1-cbb02f9ddd79.png)
The icon itself is a retool of the cult blade, with a more 'holy' look and glow.
Download link for icons: http://s000.tinyupload.com/index.php?file_id=05535435526954482657

**Comment by ihadtoregisterforthis** [comment]
:+1: for the idea but I can't help to think that many will just chose said deity thinking they get a free sword.

**Comment by Exxion** [comment]
The null rod already has 15 force. It basically is a sword.

**Comment by SangriaMonkey** [comment]
:ok_hand:

**Comment by Intigracy** [comment]
I might just port TG's ability to reskin your null rod into a variety of objects.

**Comment by Shadowmech88** [comment]
@Exxion 
It doesn't have any sharpness, though.

**Comment by Imagebard** [comment]
@Shadowmech88 Neither do Claymores and Katanas but they're still swords aren't they?

**Comment by Senaat1** [comment]
As someone that never plays Chaplain is support this :100:% :eggplant: :eggplant: :eggplant: :eggplant: :laughing: :joy: :eggplant: :ok_hand: :ok_hand: :100:

**Comment by Shadowmech88** [comment]
@Imagebard 
Claymores and katanas both have 1.2 sharpness.
See `weaponry.dm`.

**Comment by Imagebard** [comment]
@Shadowmech88 
But
The last time I checked their item paths, they didn't have sharpness.
/obj/item/weapon/claymore

I was also so sure that claymores took so much time to decap something because they were bugged

**Comment by Shadowmech88** [comment]
@Imagebard 
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/objects/items/weapons/weaponry.dm#L53

It's all there, black and white, clear as crystal.

**Comment by Imagebard** [comment]
Well shit.

**Comment by gbasood** [comment]
w h e n

**Comment by Imagebard** [comment]
I was looking on /tg/ for a moment and

https://github.com/tgstation/-tg-station/blob/master/code/game/objects/items/weapons/holy_weapons.dm

**Comment by Blithering** [comment]
I'd be up for spriting more holy themed items for null rod reskins.

**Comment by ComicIronic** [comment]
What do you mean welding knives together

**Comment by Shadowmech88** [comment]
@ComicIronic
http://ss13.moe/wiki/index.php/Makeshift_weapons
You can craft swords now, among other things.
