### ISSUE TITLE
Remove goontext

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#9096]
Self explinatory, the old system was working fine. And I honestly haven't seen a single good reason for the change posted by anyone. You can't tell what items people have by shift clicking anymore, you can't see what people are communicating on. But don't worry, we can see doge images posted by graytiders in IC chat at the very least :^)

**Comment by Probe1** [comment]
From my perspective I can actually scroll up now.  Before, when quickly checking the logs you'd have to go right  to the hard text logs and couldn't look in game. Every new message would constantly bump your place and fuck you up.  This has been a big improvement in that area.

You do bring up problems that need fixed.  I believe PJB is going to fix the icons being tiny tomorrow.

**Comment by AutismSpider** [comment]
@Probe1 you left out how it fuck up some admin stuff it now lags the fuck out of you if people spam long list of text (aka woody got wood over coms) can't click links people post in OOC or in IC

More bad then good in this so far

**Comment by PJB3005** [comment]
@AutismSpider those are now fixed.

And somebody spamming text over the radio is something the admins should deal with.

**Comment by gbasood** [comment]
I don't know that any of the contributors actually want goonchat to be reverted ever unless it breaks a system that we need and we can't fix it

**Comment by Iamgoofball** [comment]
it's like you guys dont have any concept of "bugs can be fixed"

**Comment by ihadtoregisterforthis** [comment]
> closed

This is worse than a tyranny

**Comment by gbasood** [comment]
Doesn't describe a bug (anymore, since the bugs that this mentions are fixed), just describes "I don't like this system and it needs removal"

**Comment by ihadtoregisterforthis** [comment]
Sounds like a feature request

**Comment by Probe1** [comment]
let feature (or de-feature) requests be feature requests and sit open for discussion

**Comment by AutismSpider** [comment]
@gbasood not fix yet shift clicking keeps giving people nothing and  top of other shit

**Comment by gbasood** [comment]
then those are bugs that need to be reported in a new issue instead of in the issue that says 'REMOVE FEATURE'
