### ISSUE TITLE
(Add back?) attack delays on improving a grab

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9097]
How did these get removed in the first place

**Comment by Killette2** [comment]
We got more robust

**Comment by ihadtoregisterforthis** [comment]
If you mean since Cluster's PR, the delay didn't get removed, it never worked.

**Comment by Imagebard** [comment]
@ihadtoregisterforthis GOD fucking DAMN it.

If the delay thing doesn't work, I'm gonna make an alternative suggestion.

**Comment by clusterfack** [comment]
It's on my list, I'll bump it up a bit

**Comment by Probe1** [comment]
What happened was someone added z to improve grab and they didn't limit it like clicking I suppose.

**Comment by gbasood** [comment]
Why the fuck aren't they calling the same proc in the first place

**Comment by Probe1** [comment]
quality control and volunteer coders?
