### ISSUE TITLE
Emitters are so fucking bugged it's not funny

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9099]
I was going to test some things on the test server, but during my testing I found bugs! They should make a test test server to test things before they get put on a test server. I mean putting things untested on a server is silly right?

Anyways emitters. I was going to test things, then it came to my attention that they're super fucking broken. In this picture I was able to grab a locker, put it in front of the emitter beam, the emitter never broke the locker, even after several minutes, and when I pulled the locker away the emitter got cut short. I believe this problem also persist during blob rounds, but whatever's happening the laser isn't trying to laser what's in front of it unless it's a human body. Any basic object will shorten the emitter beam and become completely unaffected by said beam. Here's a picture of what it looked like.

![bugemitter](https://cloud.githubusercontent.com/assets/5169310/14077594/1bb2b17a-f4bb-11e5-8e4b-f35e9550c039.png)

**Comment by AutismSpider** [comment]
well shit how did this bug come back?

**Comment by Exxion** [comment]
Come back? It never went away.

**Comment by ihadtoregisterforthis** [comment]
Time to email N3X15

**Comment by gbasood** [comment]
probably infinite loop bugs or something, yet again, as far as the beam not updating properly
