### ISSUE TITLE
Clown ID/PDA

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9100]
(WEB REPORT BY: jeanvoerman REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> a6ab7a70302481144adb8820ae926752acf2749e
> 
> General description of the issue
> No name in ID or PDA
> 
> What you expected to happen
> Have a name, be able to use my PDA
> 
> What actually happened
> Neither my PDA nor ID have my name on it, so unless I have no mask on I'm an "unknown" as a Jester. This also means I am unable to use my PDAin any way, can't check crew manifest, can't send messages, nothing. Swiping my card doesn't work as the ID is not set to anyone
> 
> Steps to reproduce if possible
> Probably join Taxi as a jester.

**Comment by gbasood** [comment]
Possibly a bug with character setup and having a blank name? I don't know

**Comment by Shadowmech88** [comment]
I know that if you wait too long to set your name, when you _do_ set it, your ID and PDA won't update.

**Comment by gbasood** [comment]
Oh, probably that then

**Comment by DamianX** [comment]
duplicate #8488
