### ISSUE TITLE
mommis not able to use atmos analyzer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9115]
(WEB REPORT BY: fosstarreagan REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> mommi's are not able to use the atmospheric analyzer, possibly client side or lag?
> 
> What you expected to happen
> the analyzer giving me a report of atmospherics
> 
> What actually happened
> nothing came up
> 
> Steps to reproduce if possible
> become mommi, use analyzer

**Comment by Probe1** [comment]
BAN

**Comment by Probe1** [comment]
Same for carbons actually, atmos analyzers are fucked up.  using it does nothing.
