### ISSUE TITLE
Special characters get fucked when you're stunned

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#9117]
Try it, go into a round ask someone to stun you.

' becomes & #39;

**Comment by Intigracy** [comment]
@PJB3005

**Comment by Brolaire** [comment]
What do you mean, Special characters?

**Comment by Intigracy** [comment]
> ' becomes & #39;

gee I have no idea what he means

**Comment by Brolaire** [comment]
Oh fuck now I get it, I thought he meant as in player characters

**Comment by gbasood** [comment]
I think PJB fixed this actually

**Comment by PJB3005** [comment]
Fixed
