### ISSUE TITLE
Feature Request: Lighting various things on fire with various things

### ISSUE THREAD

**Issue by Brolaire** [d3athrow/vgstation13#9122]
So I noticed that some items that should be able to light each other on fire. Here's a quick list:
- You can light red candles with cigarettes but not the other way around.
- You cannot light the cake hat on fire.
- The birthday cake and birthday cake slice both have lit candles on it obviously, but cannot be used to light things.
- You can light a B-52 with a lit cigarette but you cannot light a cigarette with a lit B-52
- You cannot light a campfire with a B-52 or the other way around.
- You cannot light a B-52 with a burning person.
- You cannot light a red candle with a B-52
- You cannot light a plasma fire with a B-52

I assume all the interactions carry over to other files with obj/machianry/space_heater/campfire and obj/item/clothing/mask/cigarette

**Comment by Exxion** [comment]
You definitely can light a B-52 with a burning plasmaman, at least
And this sounds like snowflake coding to me, as opposed to snowflake coding for special flavor text and a default case for anything else that is hot

**Comment by Brolaire** [comment]
> snowflake coding

meaning? i assume you meant its super specific and pretty much useless. guess youre right, really useless and not too interesting but i just thought maybe someone would do this.

**Comment by Exxion** [comment]
It means that some of those things check for the specific thing you're trying to light them with rather than just checking its `is_hot()` or whatever it is
