### ISSUE TITLE
Instant Blink doesn't always work

### ISSUE THREAD

**Issue by Brolaire** [d3athrow/vgstation13#9124]
- Get spellbook
- Put five levels into Blink
- Mash the spell button

After seven or so blinks, which is just 3.5s, the game stops recognizing your clicking until you move the character or use a different spell (which is not possible if you have five levels of blink

Another bug that has to do with Blink:
- Activate Smoke spell
- Try to blink

Unless you move out of the smoke center, you cannot blink until the smoke subsides

**Comment by gbasood** [comment]
Weird, someone else didn't seem to have a problem blinking for days

**Comment by Brolaire** [comment]
That is very strange then. Did you try testing the smoke/blink issue?

**Comment by gbasood** [comment]
I haven't tried to reproduce yet, I just remember someone spamming instant blink while in clouds of smoke from their own blinks and not having any problems

**Comment by clusterfack** [comment]
Yeah I can't reproduce any of this
