### ISSUE TITLE
AFK admins no longer display as AFK after the chat stuff was changed

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9125]

**Comment by Intigracy** [comment]
@PJB3005

**Comment by clusterfack** [comment]
Did you really test to make sure this was true

**Comment by PJB3005** [comment]
Okay how the fuck could goon chat cause this, like seriously?

**Comment by Probe1** [comment]
Yes, I asked if anyone wasn't afk and received no reply.  I haunted them and they weren't moving.  There has been zero afk admins according to admin-adminwho since the change.

**Comment by PJB3005** [comment]
Okay I figured it out.

To run the ping meter, the chat sends a periodic ping `Topic()` message to the server, which resets the AFK status.

No idea how to fix that other than to remove the automatic ping meter entirely.

**Comment by Probe1** [comment]
Clever.  Well, this is a pretty big quality of life drop.  But it isn't essential.

**Comment by PsiOmegaDelta** [comment]
I suppose you could have a custom AFK timer that resets on clicks and non-ping Topic() calls but it feels a bit hacky.

**Comment by PJB3005** [comment]
Yeah @PsiOmegaDelta I guess.

**Comment by Intigracy** [comment]
Couldn't you just modify Topic() with a (var/resetafk = 1), with the ping meter specifically being the only thing that's setting it to 0?

**Comment by Boxe** [comment]
i can confirm that this is extremely easy to test in 100% of circumstances

**Comment by PJB3005** [comment]
@Intigracy inactivity is an internal BYOND thing.

**Comment by ghost** [comment]
@PJB3005 Then make it not one, nerd.
