### ISSUE TITLE
 Telecomms or chat or something going batty.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9126]
```
 requests console [Common] (Machine) beeps, "<img class="icon req_comp2" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAS1BMVEXAwMAgICAAUCgAWDDIMAAA
cDD4MABImHCQCAj4+ABQUGBAICBgYHBYWGgYGBhgYGhQUFgYGCAoKDAoKCggICiYCAg4ODgwMDhA
QEBQFu8MAAAAAXRSTlMAQObYZgAAAGR6VFh0RGVzY3JpcHRpb24AAHicU1ZwcnX39FNw8fXkKkst
Ks7Mz1OwVTDRM+DiLM9MKckAc
```

**Comment by Intigracy** [comment]
do me a favor and edit your post, put 3 `(tilde key) at the front and 3 at the end of it. It'll stop the HTML from going through.

**Comment by SangriaMonkey** [comment]
![wew lad](http://i.imgur.com/fmBFa25.png)
p. scary tbh

**Comment by Intigracy** [comment]
@PJB3005

**Comment by coldcola** [comment]
I was also getting people's name showing up when they spoke but nothing else (over comms)

**Comment by Probe1** [comment]
Ditto.  It may have been because a supermatter shard blew up next to me.

![dreamseeker_2016-03-29_01-04-01](https://cloud.githubusercontent.com/assets/8550416/14098913/9fb1833c-f54e-11e5-89da-0c94e9fde80a.png)

**Comment by Shadowmech88** [comment]
What's with the green names showing up in chat without any text next to them? It's in Probe's pic and I've gotten if before as well.

**Comment by Intigracy** [comment]
It happens when the speaker is deaf.

**Comment by PJB3005** [comment]
Okay so for some retarded reason and I'm gonna blame the fact that chat was never sanitized the base img tags are being outputted directly.

Technically isn't the fault of goon chat.

**Comment by ihadtoregisterforthis** [comment]
It already _worked_ before. A_n img tag_ ejected from _deaf player_ required 0 _sanity_ before the _Goonchat_.
Besides, even if the _html fancyness_ process was actually necessary, it would still make a ton more sense to make it built-into the _old system_, wouldn't it?

The inhuman _lack of sanity_ actually did nothing with the previous _chat_ system, though. To claim that _fixing_ is necessary with the new _chat_ system is just dishonest when that's not the way it used to work.

**Comment by PJB3005** [comment]
@ihadtoregisterforthis I'm not saying I'm not fixing it.

The fact that this worked before was purely a bug, which I fixed, which then broke the things that relied on the bug (there being zero sanity).

**Comment by PJB3005** [comment]
Also just saying but the fact that the requests console puts the image inside the speech message is already a crime.

**Comment by clusterfack** [comment]
Should be long fixed
