### ISSUE TITLE
Can No Longer See Space Station Name

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9127]
It used to be in the top-left of the window. Now it just says "Space Station 13."
Is there anywhere else the station name can be seen?

**Comment by uazuaz** [comment]
i noticed this weeks ago actually.
as far as i know, the only way to see the station's name now is in the BYOND window, under the "worlds" option that appears when you enter a server.

![ss](https://cloud.githubusercontent.com/assets/6170726/14106450/77fe546a-f5b1-11e5-8049-8fa982c17ab1.jpg)

**Comment by SysadminJeroen** [comment]
I had this problem for months, appeared after I updated my BYOND to
something recent.
Thanks @uazuaz for the workaround!

2016-03-29 13:24 GMT+02:00 uazuaz notifications@github.com:

**Comment by ghost** [comment]
T-thanks byond

**Comment by clusterfack** [comment]
Its actually a byond bug, lummox closed the issue on it saying it was fixed (apparently its not fixed)

We use 'world.name' to make the top left show the name of the station, but one of the updates around 508/509 made it stop showing.

**Comment by gbasood** [comment]
Someone should confirm whether or not this got fixed in 510 at least before bug reporting it

**Comment by clusterfack** [comment]
Sood fixed this
