### ISSUE TITLE
Cloning be fucked

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9128]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Now, when cloning, you're given a hefty dose of inaprovaline to prevent you from oxydepping out. Problem is you're given enough to go over the OD limit.

Now, I'm assuming that the cloning pod works off a health threshold, so this forces the clonee to stay in the pod a little longer than expected, as well as kill their liver. On the plus side, this also means they come out with less clone damage.

> What you expected to happen
> Not to have my liver rot while I'm being reconstituted
> 
> What actually happened
> About 20 liver damage, 70 toxin damage, but 15 clone damage
> 
> Steps to reproduce if possible
> Clone somebody using the base cloning setup, once they pop out check them with the health analyzer, and they should have a fair amount of toxin damage.

**Comment by ghost** [comment]
Pfffhahahhahahahahaha

**Comment by PJB3005** [comment]
SO THIS EXPLAINS THE TOXINS FROM CLONING.

**Comment by Intigracy** [comment]
Why does inaprovaline have an overdose limit, the only thing it does is keep you alive, doesn't heal or anything.

**Comment by liltiptop** [comment]
Oh lawdy. All in favor of having no OD for inaprovaline?

**Comment by clusterfack** [comment]
Last I checked while it had an overdose limit it had no overdose code

**Comment by Exxion** [comment]
There's another issue though
Inaprovaline doesn't work on vox and is toxic to them at any level

**Comment by clusterfack** [comment]
Good fuck the vox

**Comment by liltiptop** [comment]
> Inaprovaline doesn't work on vox and is toxic to them at any level

Nanotransen is trying to gas the vox even when they're revived.
LEEPEST DOOR.

**Comment by Intigracy** [comment]
tbh I think the vox getting poxed is funny
but it overdosing should be fixed

**Comment by gbasood** [comment]
I think the cloning pod needs some general love at this point
Doesn't it also not provide the correct atmos for vox/plasmen so they die while being cloned or something?

**Comment by Exxion** [comment]
Vox don't die while being cloned, but they never get above dark orange health and are usually in perpetual crit
Not sure about plasmamen

**Comment by Tokanova** [comment]
This really needs more attention. Low pop rounds where theirs only like one doctor who can't pay attention to the cloner, end up with the guy dying by the time he pops out of cloning before he can be treated.

This could be easy to fix if inaprovaline didn't have an OD limit.

**Comment by 9600bauds** [comment]
Inaprov no longer overdoses

Also, Vox clones don't get inaprovaline anyways
