### ISSUE TITLE
Add 'request maintenance' button to PDAs

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9132]
Would enable janitors, station techs to review maintenance requests via their own PDAs, displayed on a minimap in Crew Monitor style with map positions shown as icons.

Should also come with the ability to ignore requests on an individual so that the clown can't cover the entire chapel in requests to paint it black or something

**Comment by liltiptop** [comment]
I like it. So would every PDA start with it, or would you need to buy it at a terminal?

**Comment by Killette2** [comment]
I saw a chapel and I want it painted black
No colors anymore, I want them to turn black
I see the waifus walk by, dressed in their summer clothes
I have to turn my head until the darkness goes

**Comment by gbasood** [comment]
@liltiptop Probably every PDA start with it, buying it defeats the purpose, since non-assistants rarely buy anything for PDAs

**Comment by Kitfox88** [comment]
lol if you don't buy light enhancer and spam blocker you pleb

**Comment by PJB3005** [comment]
I spend my dosh on 4noraisins thank you.

**Comment by Killette2** [comment]
> Not hacking the vendor and playing PDA minesweeper while it fires free food at you

**Comment by gbasood** [comment]
w h e n
