### ISSUE TITLE
Blood Soup misnamed

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9135]
(WEB REPORT BY: furbeh REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> e0d40e6bec254528c45c2931b2d5d89c97d3d3c
> 
> General description of the issue
> Blood Soup is called Tomato Soup
> 
> What you expected to happen
> Blood soup called blood soup
> 
> What actually happened
> Blood Soup is called Tomato Soup
> 
> Steps to reproduce if possible

**Comment by Intigracy** [comment]
I'm pretty sure it's intended.

```
/obj/item/weapon/reagent_containers/food/snacks/bloodsoup
    name = "Tomato soup"
    desc = "Smells like copper"
```

**Comment by Killette2** [comment]
Just get a pen and rename it to Blood soup since it's intended. Be the mad chef you were meant to be and don't disguise it. Also if medbay is smart, they will steal some of your soup for it's exclusive chemicals.

now that I think about it, why doesn't medbay ever put blood in the cryo tube?

**Comment by Exxion** [comment]
Yeah, just like how a glass of blood is named a glass of tomato juice
It's intended

**Comment by Cisrox** [comment]
Why would blood smell like copper if it contains iron

**Comment by Intigracy** [comment]
Have you ever tasted blood?

It has a pretty distinct copper taste.

**Comment by gbasood** [comment]
It tastes like copper because of the iron
Not much iron lying around these days for people to lick though, it's mostly steel

**Comment by Killette2** [comment]
It's fucking bullshit how we can't lick iron these days anymore. It's all steel or some aluminum bullcrap these days. Back when I was a kid we'd all gather around the pole at our schoolgrounds on a hot early summer day before the graduation and give it a good licking. The taste of sweet iron was something you could always get in the old days of america, you could even call it a right. Now it's psuedo-iron this and diet-iron that. Where's the metal when you want the good old thing? There's hardly any organic iron mines these days, they just mix it will bullshit like coal and tin for smelting. I look forward to a future where we can go out on asteroids and mine iron ourselves, smelt it and earn pennies, but none of that even matters as long as we get to lick it. I don't care if I have to fight the mother of all goliaths just to taste that succulent ore, I'll grab my drill and do it.

**Comment by ghost** [comment]
why

**Comment by Killette2** [comment]
Because it was better than a period joke when people are talking about blood tasting like iron and licking iron. I have higher standards than that.

**Comment by SkowronX** [comment]
Tastes like pennies.

**Comment by Killette2** [comment]
What about salty coins and milk?
