### ISSUE TITLE
Supermatter does not respond to emitters

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9138]
(WEB REPORT BY: anonymousrex REMOTE: 158.69.55.2:7777)

> Revision e0d40e6bec254528c45c2931b2d5d89c97d3d3c3
> 
> General description of the issue

The supermatter does not energize when an emitter hits it, nor does it produce gas or electricity under those circumstances.  It only powers up when something hits it, in one case, a MoMMI walking into it.

> What you expected to happen

The supermatter to power up when exposed to an emitter.

> What actually happened

Supermatter did not power up, and even if struck with an external object or mob, would not stay powered up and would decline in power.

> Steps to reproduce if possible

Build an SME, fire an emitter at the shard, get nothing back.

**Comment by PJB3005** [comment]
Beams are breaking PRETTY FUCKING Badly.

**Comment by ghost** [comment]
In both instances I build my own SME but got nothing back from the shard.  The collector was placed correctly and set up properly enough that it should have generated electricity every cycle, and the shard itself should have started generating gases once exposed to the emitter, but it only did either if physically touched.

**Comment by PJB3005** [comment]
Almost certainly related to that other beam issue which I'm too lazy to link.

**Comment by ghost** [comment]
Thank you.  I'll go hunt around for it.

**Comment by Killette2** [comment]
It's my issue so you have to ask for permission to reference it.

**Comment by ghost** [comment]
Ahh, I was just going to read into it, not reference it.

**Comment by gbasood** [comment]
@AnonymouxRex jokes

**Comment by liltiptop** [comment]
Simple fix. We just make a disposal pipeline that fires people into the shard.

**Comment by Shadowmech88** [comment]
I made an SME build once that produced power via corgi puppies being mass-produced and shot directly into the shard.

**Comment by Kitfox88** [comment]
i think i saw that screenshot in the thread

**Comment by gbasood** [comment]
This still happening, even after movecode changes?

**Comment by clusterfack** [comment]
I've seen this work many times so I'm not sure what this is all about
