### ISSUE TITLE
A LOT of uniforms are missing fat sprites

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#9139]
All were tested on a fat human male, ~~didn't test on a fat human female.~~

Clothing that is missing a sprite and is instead showing a purple and black checkerboard suit:
![AAAAA SO MUCH CLOTHING](http://i.imgur.com/01G06Nq.png)
![More](http://i.imgur.com/XUjXG6e.png)
![Fat lawyers do exist](http://i.imgur.com/QMmhRDx.png)
**---------------------------------------------------------------------------------**
Clothing that is unable to be worn by fat people (only here cause some of them should be):
![WHY IS CHEMISTRY NOT FOR FAT PEOPLE](http://i.imgur.com/XBzDR9u.png)
![Not shown but important: CHAMELEON JUMPSUIT](http://i.imgur.com/V4Pokgt.png)
![Basically every clown vending machine item](http://i.imgur.com/QxFYU3e.png)
![Dresses but if men are allowed to wear them, fat men should too](http://i.imgur.com/f6OxADP.png)
![COME ON YOU KNOW YOU WANT FATMAN, CRIMEFIGHTER](http://i.imgur.com/eYXa442.png)
![Fat NukeOps When? (When fat spacesuits exist but that is a different issue)](http://i.imgur.com/IIlDtB1.png)

**Comment by Shadowmech88** [comment]
Closing in favor of #24718 and #24719.
