### ISSUE TITLE
Investigate log windows show html-encoded logs

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9140]
> %3csmall%3e21%3a56+%5b0x200c0f1%5d+%28198%2c249%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e21%3a56+%5b0x200c100%5d+%28238%2c249%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e21%3a56+%5b0x200c103%5d+%28198%2c251%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e21%3a56+%5b0x200c107%5d+%28238%2c251%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e21%3a56+%5b0x200c108%5d+%28211%2c253%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e21%3a56+%5b0x200c109%5d+%28225%2c253%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e21%3a56+%5b0x200c10a%5d+%28203%2c255%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e21%3a56+%5b0x200c10d%5d+%28233%2c255%2c3%29%3c%2fsmall%3e+%7c%7c+Energy+Cannon+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e22%3a07+%5b0x4000048%5d+%28292%2c253%2c1%29%3c%2fsmall%3e+%7c%7c+Engineering+has+a+power+alarm%21%3cbr+%2f%3e %3csmall%3e22%3a09+%5b0x200835d%5d+%28309%2c275%2c1%29%3c%2fsmall%3e+%7c%7c+Radiation+Collector+Array+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+Angelite+Entyshak.+Fuel%3a+100%25.%3cbr+%2f%3e %3csmall%3e22%3a09+%5b0x200835f%5d+%28310%2c275%2c1%29%3c%2fsmall%3e+%7c%7c+Radiation+Collector+Array+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+Angelite+Entyshak.+Fuel%3a+100%25.%3cbr+%2f%3e %3csmall%3e22%3a09+%5b0x2008361%5d+%28311%2c275%2c1%29%3c%2fsmall%3e+%7c%7c+Radiation+Collector+Array+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+Angelite+Entyshak.+Fuel%3a+100%25.%3cbr+%2f%3e %3csmall%3e22%3a09+%5b0x2007bbf%5d+%28309%2c269%2c1%29%3c%2fsmall%3e+%7c%7c+Radiation+Collector+Array+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+Angelite+Entyshak.+%3cfont+color%3d%27red%27%3eIt+is+empty%3c%2ffont%3e.%3cbr+%2f%3e %3csmall%3e22%3a09+%5b0x2007bc1%5d+%28310%2c269%2c1%29%3c%2fsmall%3e+%7c%7c+Radiation+Collector+Array+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+Angelite+Entyshak.+%3cfont+color%3d%27red%27%3eIt+is+empty%3c%2ffont%3e.%3cbr+%2f%3e %3csmall%3e22%3a09+%5b0x2007bc3%5d+%28311%2c269%2c1%29%3c%2fsmall%3e+%7c%7c+Radiation+Collector+Array+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+Angelite+Entyshak.+%3cfont+color%3d%27red%27%3eIt+is+empty%3c%2ffont%3e.%3cbr+%2f%3e %3csmall%3e22%3a12+%5b0x20077c8%5d+%28297%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27red%27%3e50000%2f200000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27red%27%3eoff%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a13+%5b0x20077c8%5d+%28297%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27red%27%3e50000%2f200000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+2edgy%3cbr+%2f%3e %3csmall%3e22%3a13+%5b0x20077d6%5d+%28298%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27red%27%3e50000%2f50000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27red%27%3eoff%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+2edgy%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x20077c8%5d+%28297%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e50000%2f45000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x20077d6%5d+%28298%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27red%27%3e50000%2f50000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x20077d6%5d+%28298%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e50000%2f45000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x2007f87%5d+%28305%2c272%2c1%29%3c%2fsmall%3e+%7c%7c+the+emitter+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+Angelite+Entyshak%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x2007f87%5d+%28305%2c272%2c1%29%3c%2fsmall%3e+%7c%7c+the+emitter+regained+power+and+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x20077e4%5d+%28299%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27red%27%3e50000%2f50000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27red%27%3eoff%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x20077e4%5d+%28299%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e50000%2f45000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27red%27%3eoff%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x20077e4%5d+%28299%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e50000%2f45000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a16+%5b0x20077e4%5d+%28299%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e100000%2f45000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077e4%5d+%28299%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e100000%2f80000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077d6%5d+%28298%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e100000%2f45000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077d6%5d+%28298%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e100000%2f80000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077c8%5d+%28297%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e100000%2f45000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077c8%5d+%28297%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e100000%2f80000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077e4%5d+%28299%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e200000%2f80000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077d6%5d+%28298%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e200000%2f80000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x2007f87%5d+%28305%2c272%2c1%29%3c%2fsmall%3e+%7c%7c+the+emitter+turned+%3cfont+color%3d%27red%27%3eoff%3c%2ffont%3e+by+David+Murdock%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077c8%5d+%28297%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e200000%2f80000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x2007f87%5d+%28305%2c272%2c1%29%3c%2fsmall%3e+%7c%7c+the+emitter+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+David+Murdock%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077c8%5d+%28297%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e200000%2f150000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077d6%5d+%28298%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e200000%2f150000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x2007f87%5d+%28305%2c272%2c1%29%3c%2fsmall%3e+%7c%7c+the+emitter+turned+%3cfont+color%3d%27red%27%3eoff%3c%2ffont%3e+by+David+Murdock%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x2007f87%5d+%28305%2c272%2c1%29%3c%2fsmall%3e+%7c%7c+the+emitter+turned+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+by+David+Murdock%3cbr+%2f%3e %3csmall%3e22%3a17+%5b0x20077e4%5d+%28299%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e200000%2f150000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a18+%5b0x20077f7%5d+%28306%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27red%27%3e50000%2f50000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a18+%5b0x20077f7%5d+%28306%2c266%2c1%29%3c%2fsmall%3e+%7c%7c+the+power+storage+unit+input%2foutput%3b+%3cfont+color%3d%27green%27%3e100000%2f50000%3c%2ffont%3e+%7c+Output-mode%3a+%3cfont+color%3d%27green%27%3eon%3c%2ffont%3e+%7c+Input-mode%3a+%3cfont+color%3d%27green%27%3eauto%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a24+%5b0x2007f87%5d+%28305%2c272%2c1%29%3c%2fsmall%3e+%7c%7c+the+emitter+turned+%3cfont+color%3d%27red%27%3eoff%3c%2ffont%3e+by+Sprok%3cbr+%2f%3e %3csmall%3e22%3a37+%5b0x2006527%5d+%28277%2c253%2c1%29%3c%2fsmall%3e+%7c%7c+Particle+Accelerator+Control+Computer+increased+to+%3cfont+color%3d%27red%27%3e1%3c%2ffont%3e+by+AnonymousRex%3cbr+%2f%3e %3csmall%3e22%3a37+%5b0x2006527%5d+%28277%2c253%2c1%29%3c%2fsmall%3e+%7c%7c+Particle+Accelerator+Control+Computer+increased+to+%3cfont+color%3d%27red%27%3e2%3c%2ffont%3e+by+AnonymousRex%3cbr+%2f%3e %3csmall%3e22%3a37+%5b0x2006527%5d+%28277%2c253%2c1%29%3c%2fsmall%3e+%7c%7c+Particle+Accelerator+Control+Computer+turned+%3cfont+color%3d%27red%27%3eON%3c%2ffont%3e+by+AnonymousRex%3cbr+%2f%3e %3csmall%3e22%3a37+%5b0x201dc38%5d+%28278%2c248%2c1%29%3c%2fsmall%3e+%7c%7c+the+gravitational+singularity+was+created.+%3cfont+color%3d%27red%27%3eNo+containment+fields+were+active.%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e22%3a38+%5b0x201dc38%5d+%28278%2c248%2c1%29%3c%2fsmall%3e+%7c%7c+the+gravitational+singularity+%3cfont+color%3d%27red%27%3egrew+to+size+3.%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e22%3a38+%5b0x2006527%5d+%28277%2c253%2c1%29%3c%2fsmall%3e+%7c%7c+Particle+Accelerator+Control+Computer+lost+a+connected+part%3b+It+%3cfont+color%3d%27red%27%3epowered+down%3c%2ffont%3e.%3cbr+%2f%3e %3csmall%3e22%3a38+%5b0x2006527%5d+%28277%2c253%2c1%29%3c%2fsmall%3e+%7c%7c+Particle+Accelerator+Control+Computer+turned+%3cfont+color%3d%27green%27%3eOFF%3c%2ffont%3e+by+outside+forces%3cbr+%2f%3e %3csmall%3e22%3a38+%5b0x30000ac%5d+%28285%2c244%2c1%29%3c%2fsmall%3e+%7c%7c+the+monkey+%28402%29+has+been+consumed+by+a+singularity%3cbr+%2f%3e %3csmall%3e22%3a38+%5b0x201dc38%5d+%28284%2c244%2c1%29%3c%2fsmall%3e+%7c%7c+the+gravitational+singularity+%3cfont+color%3d%27red%27%3egrew+to+size+5.%3c%2ffont%3e%3cbr+%2f%3e %3csmall%3e22%3a38+%5b0x30000a8%5d+%28283%2c241%2c1%29%3c%2fsmall%3e+%7c%7c+the+monkey+%28424%29+has+been+consumed+by+a+singularity%3cbr+%2f%3e %3csmall%3e22%3a39+%5b0x3000090%5d+%28288%2c231%2c1%29%3c%2fsmall%3e+%7c%7c+the+monkey+%28562%29+has+been+consumed+by+a+singularity%3cbr+%2f%3e %3csmall%3e22%3a39+%5b0x300008d%5d+%28291%2c234%2c1%29%3c%2fsmall%3e+%7c%7c+the+monkey+%28843%29+has+been+consumed+by+a+singularity%3cbr+%2f%3e %3csmall%3e22%3a40+%5b0x201dc38%5d+%28301%2c230%2c1%29%3c%2fsmall%3e+%7c%7c+the+gravitational+singularity+%3cfont+color%3d%27red%27%3egrew+to+size+7.%3c%2ffont%3e%3cbr+%2f%3e

**Comment by gbasood** [comment]
just html_decode shit before outputting to a window fam

**Comment by PJB3005** [comment]
The real question is why is the data encoded at all.

**Comment by gbasood** [comment]
Is it saving the output of to_chat for later use or something because that'd be it

**Comment by gbasood** [comment]
Yeah okay so it's probably being run through render text

**Comment by PJB3005** [comment]
Okay can we just lynch whatever morons used `html_decode` in COMPLETELY WRONG PLACES?

**Comment by gbasood** [comment]
Already fixed this whoops
