### ISSUE TITLE
Auto stacking or something has gone awry for a miner

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9141]
/obj/item/stack/tile somehow wound up in his crate.  I assume it's because of the recent stacking PR because of the object path.  Maybe.  Not really sure what could cause this.  It has no icon and its named the item.

![dreamseeker_2016-03-30_01-09-17](https://cloud.githubusercontent.com/assets/8550416/14132445/0d145d94-f614-11e5-8345-a9c2116d129b.png)

**Comment by Intigracy** [comment]
I think it might have come from mining, you know how they randomly pop out goodies for you? Yeah that.

**Comment by Probe1** [comment]
THAT'S FROM DESTROYING XENOARCH DIGSITES THOSE ARENT RANDOM GOODIES YOU MONSTER

**Comment by Intigracy** [comment]
Who cares about xenoarch?

Not me.
