### ISSUE TITLE
Horror form bugs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9142]
(WEB REPORT BY: str4t0sss REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 94b2b317898edbd76cbcf8497dbf00b8e981ca68 
> 
> General description of the issue
> Horror forms airlock forcing doesnt work, it dies to bleeding (not sure if intended), cannot devour humans like Aliens, but its written it can. 
> 
> What you expected to happen
> Forcing airlocks, devouring people
> 
> What actually happened
> Having to use ID's, beheading people
> 
> Steps to reproduce if possible
> Turn into horror form as a changeling, try to force a airlock or devour a mob. Get shot by a mateba and bleed out slowly.

**Comment by gbasood** [comment]
Couldn't find code for devouring for horror forms but airlock forcing code is still in there
