### ISSUE TITLE
Runtime on proc/to_chat could be causing severe lag spikes

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9144]
The server was lagging hard with 2-3 second hangs between actions/inputs.  I opened the profiler and under self cpu I only saw proc/to_chat out of the ordinary.  It was the 5th highest usage of the CPU.  The runtime may be causing bad hangups.

```

runtime error: DEBUG: Boutput called with invalid message
00:45:23 Runtime detected
DEBUG: Boutput called with invalid message at browserOutput.dm:212
 proc name: to chat (/proc/to_chat)
  source file: browserOutput.dm,212
  usr: (src)
  src: null
  call stack:
to chat(Michael Cariello (/mob/living/carbon/human), )
Dalton Webb (/obj/effect/fake_attacker): updateimage()
Dalton Webb (/obj/effect/fake_attacker): attack loop()
Dalton Webb (/obj/effect/fake_attacker): New(the floor (442,150,5) (/turf/simulated/floor))

```

**Comment by unid15** [comment]
Fixed by https://github.com/d3athrow/vgstation13/commit/7a0ad2dbedeb2981d7d715100f3eb1a48deefd52

**Comment by PJB3005** [comment]
Not really.

**Comment by Probe1** [comment]
I wish.  Todays runtimes
![image](https://cloud.githubusercontent.com/assets/8550416/14160069/0fe8820e-f6a8-11e5-9992-0529672a6a35.png)

**Comment by Probe1** [comment]
Aged out.
