### ISSUE TITLE
Venom sword doesnt work with normal beakers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9147]
(WEB REPORT BY: str4t0sss REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 4d6e777df0babdeed87e0cb98cd5cf6651c78cbd 
> 
> General description of the issue
> Venom sword should work with normal 50 u beakers, but it cannot be loaded.
> 
> What you expected to happen
> Beaker is loaded into venom sword.
> 
> What actually happened
> "That beaker is too large to fit into the venom sword's beaker port."
> Steps to reproduce if possible
> try to fit a 50 u beaker onto venom sword

**Comment by gbasood** [comment]
Wow I'm really good at second guessing myself

``` DM
if(!(W.type == /obj/item/weapon/reagent_containers/glass/beaker || W.type == /obj/item/weapon/reagent_containers/glass/beaker/noreact))
            to_chat(user, "<span class='warning'>That beaker is too large to fit into \the [src]'s beaker port.</span>")
            return
```

So it SHOULD be working when beakers are either normal noreact or normal beakers

Why that check isn't just

``` DM
if(W.type != /obj/item/weapon/reagent_containers/glass/beaker && W.type != /obj/item/weapon/reagent_containers/glass/beaker/noreact)
```

I have no idea

**Comment by clusterfack** [comment]
@Shadowmech88

**Comment by gbasood** [comment]
oh wait it's because it's not `istype` and it's checking the type manually instead duh

**Comment by Shadowmech88** [comment]
Doesn't checking the type manually work? It definitely DID work when I made the thing.

How are you supposed to check for "istype(/path/to/type) AND IS NOT a child of /path/to/type"?

**Comment by Exxion** [comment]
By doing what you did

**Comment by gbasood** [comment]
If you only want to load specific beakers then you need to check type == type.
Anyways this is your feature so either address it via code or we can call it a feature request instead of a bug

**Comment by Shadowmech88** [comment]
> If you only want to load specific beakers then you need to check type == type

Isn't that what the code is doing right now?

**Comment by Exxion** [comment]
Yes.
Presumably they tried to insert a beaker that was filled at roundstart.

**Comment by Shadowmech88** [comment]
Would it be better, as a universal standard, for subtypes like that which only exist to be varedited versions of the main type, to spawn an instance of the main type, edit it, then delete themselves, instead of forever existing as an `/obj/item/weapon/reagent_containers/glass/beaker/clonex` or what have you?

**Comment by Shadowmech88** [comment]
You know what, a better solution might be to check `istype(/obj/item/weapon/reagent_containers/glass/beaker)` and then check its volume.
I think that's what I'll do.

**Comment by ComicIronic** [comment]
There's a reason typechecking is considered terrible practice in every other language that exists. It's only so ubiquitous here because people can't be fucked to OO properly.
