### ISSUE TITLE
Fat people should have more options for outer clothing

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#9150]
As shown in my [other issue report](https://github.com/d3athrow/vgstation13/issues/9148), Fat people are heavily limited in their options for outer clothing, most options being armor.

While I don't think that fat people should be able to wear any outer clothing, some that they aren't currently able to wear would make more sense for them to be able to, such as suspenders and possibly the bloated looking space suits.
To make things simple, here's a list of all the human outer clothing to easily be searched
![1](http://i.imgur.com/EPpr6LK.png)
![2](http://i.imgur.com/psE7ZaN.png)
![3](http://i.imgur.com/WmrOAhp.png)
![4](http://i.imgur.com/ZyHA6V0.png)
![5](http://i.imgur.com/S1N8jVD.png)
![6](http://i.imgur.com/snsGkT4.png)
![7](http://i.imgur.com/yMnJvWp.png)
![8](http://i.imgur.com/cmHPb35.png)

**Comment by chatsonf** [comment]
Goodbye sweet prince

**Comment by Probe1** [comment]
You are 100% welcome to code it yourself.

**Comment by chatsonf** [comment]
How do I code a Sprite 🍆

**Comment by Probe1** [comment]
With the power of BUILD YOUR OWN NET DREAM
