### ISSUE TITLE
An idea on how to implement wages

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9163]
Pay 1/10th of starting wage every 2 minutes the round goes on, both to players and department accounts.
This would mean that each account would have the equivalent of its starting wages added to their account by the 20 minute mark.

Could go for longer times than that, even.
Payout every 3 minutes for 30 minutes
Payout every 5 minutes for 50 minutes
Payout every 6 minutes for an hour

And honestly we need some form of wage payout before we can worry about making the economy good

**Comment by ghost** [comment]
> And honestly we need some form of wage payout before we can worry about making the economy good

Actually we need to do the exact opposite.

**Comment by gbasood** [comment]
What, taking money from employees for existing?

Joking, I assume you mean adding things that players will actually want to buy before worrying about wages.

**Comment by ghost** [comment]
The way you could implement wages is inherently inflationary. - money coming from nowhere. By adding wages you will actually decrease player to player transactions. "Why should I trade money for X if I'm going to get money in four minutes anyway?" Or as a result of that, "why should I trade money for X if X has a value and money clearly doesn't." This is the biggest problem with the mining department getting fat dollar from minerals.

**Comment by clusterfack** [comment]
That's why miners should be paid by research, and research should make money selling shit to other people

**Comment by ghost** [comment]
Exactly.

**Comment by gbasood** [comment]
Then the problem is where the other people get their money

**Comment by clusterfack** [comment]
Security should charge people for getting arrested like in muh libertarian utopia

**Comment by clusterfack** [comment]
![](http://i.imgur.com/wDyQxr9.png)

**Comment by ghost** [comment]
Security and medbay should be paid by taxes on transactions. Duh.

**Comment by clusterfack** [comment]
Chemist sell chems, geneticists sell powers, virologists charge you not to spread beneficial viruses

**Comment by gbasood** [comment]
The problem is the economy has various money sinks like:
- Cargo
- Vending machines
- PDA terminal

And the only way to earn money from non-players is, as far as I know, from slots and mining. Which means you end up with crazy deflation and no one wants to pay eachother anything because you're better off asking for favors

**Comment by ghost** [comment]
The main problem is inflation, but deflation is an issue. Which is why the money sinks should be plugged and made player to player rather than player to environment. I will probably work on the economy after doing snowmap.

**Comment by Intigracy** [comment]
Sure you will.

**Comment by gbasood** [comment]
When you do, make sure you make sending dudes money easier.

**Comment by Intigracy** [comment]
Tbh we shouldn't have a difference between virtual wallet and bank account, it should just take from your bank account.

**Comment by ghost** [comment]
Ever seen what happens when somebody tries to charge for something?

I've seen people just walk in and welderbomb medbay front desk for trying to charge for chems, I've seen botany set aflame for trying to sell produce when there wasn't a chef, I have seen somebody put the entire cargo bay in vacuum simply because his crate cost money. All non-antag, all justified it with 'well it didn't cost money last round, why should it cost money this round? Fuck gimmicks'

People suck.

**Comment by gbasood** [comment]
Yeah, that's part of why the economy is shit
The other part is the ability to pay for shit is unnecessarily obtuse

**Comment by PJB3005** [comment]
The main problem is the player base, on goon money has little use but when somebody asks you money for something you're probably gonna give it to them if you want it.

**Comment by Probe1** [comment]
I have the perfect idea.

Stop having ideas and do it.

**Comment by gbasood** [comment]
Once @PJB3005 finishes #9223 I'd like to implement an easy way to send cash money via PDAs as a first step to economy things
The next steps would be more things for people to spend money on

Actually, department heads should be able to bill people.
Docs can write up a bill, send it to the CMO, and he can plug that bill into the system.
_(Because depending on who you believe, debt was the basis for an economic system coming into existence in the first place)_

**Comment by Shadowmech88** [comment]
> I'd like to implement an easy way to send cash money via PDAs as a first step to economy things

You can already wire people money straight from your PDA. PDAs can print physical credits straight from your bank account, too.

**Comment by gbasood** [comment]
Wow what the fuck why do ATMs exist

**Comment by chatsonf** [comment]
So you can print out a bunch of bills and rain it on people

**Comment by Intigracy** [comment]
So you can change the security settings on your account to have one account instead of needing to use the ATM constantly.

**Comment by Shadowmech88** [comment]
So you can access accounts you have the info for, but not an ID for. For example department accounts.

**Comment by Killette2** [comment]
So what if the HoP actually distributes the stations funds, gives bonuses to well working departments under his wing, and then the civilian/service departments can then buy things from medical, cargo (through crates still), science, and other things?

We wouldn't need ANY updates if the HoP touched the station funds of a whopping 75k, but players have yet to make it happen. ROWAN SHALL MAKE ECONOMY WORK, HOP MY NEW JOB!

**Comment by gbasood** [comment]
@Killette2 Pretty sure the reason players haven't made it happen yet is because the tools to transfer money between station accounts is shit and also because money doesn't actually help all that much

**Comment by Killette2** [comment]
Shows what you know, I will MAKE IT happen. I just prefer to do big things during high pop so we have a decently full crew.

**Comment by gbasood** [comment]
> the station funds of a whopping 75k

I checked in the code, and if you meant station account balance, it starts at 5k, so I'm not sure what you mean?

**Comment by Killette2** [comment]
Used to be 75k, must have been changed, I'll see eventually.

**Comment by Probe1** [comment]
yeah it was changed when deity took a crack at the economy because that was retarded`

**Comment by gbasood** [comment]
muh trickle-down economics :^)

**Comment by Killette2** [comment]
Or I could be Robin Honk. Steal from the miners and PDA gift money to the poor. Not sure if security would be ok with the energy bow part, but I might be able to get away with it if I wear tights.

**Comment by ihadtoregisterforthis** [comment]
Wages on the current state of the server sounds more getting paid for sitting on my thumbs for hours.
In that sense the mining machine is the okayest, it gives money relatable to the effort of the work, it's easy to use, and it doesn't destroy hard earned supplies for money. Here the money is a secondary output for a needed step, even if the money is more used than the materials. 
A crude example would be paying chemists for making pills. This system is by no means compatible with every job, but I'd rather the chaplain recycled some cans for coins when needed rather than him being rich an hour into the shift

**Comment by Killette2** [comment]
Why can't hydro send produce to centcomm for example, or virologist send antibodies? Roboticist could send mechs, and all this shit would give the sender money.

**Comment by gbasood** [comment]
> Wages on the current state of the server sounds more getting paid for sitting on my thumbs for hours.

Just like real life (non-physical labor anyway)

**Comment by Killette2** [comment]
Maybe like I said we should just push economy manually. I played HoP when a station was evacuating for a quick look, and every department starts off with 5k. Still, we have enough money for a HoP or Captain to distribute funds and encourage capitalism on the station.

**Comment by gbasood** [comment]
Perhaps the tools for managing department accounts should be easier as well.
