### ISSUE TITLE
Stay Culted as Borer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9168]
(WEB REPORT BY: morena REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)

I don't know what this means I'm sorry.

> General description of the issue

Died as a Cultist and got dragged into borer body because wasn't paying attention. Remained 'culted', could still hear Nar-sie, cult communications.

> What you expected to happen

As a Borer, I am a new entity in space and therefore should not be culted. I'm pretty sure the person I was in was NOT a cultist, they spoke about trying to avoid the cult a few times.

> What actually happened

I remained a cultist even as a borer, being able to hear the Cult communications and Nar-sie, which could lead to Metagaming.

> Steps to reproduce if possible

Get Culted, Die, and then become a Borer. This may work with other after-death 'respawns'

**Comment by gbasood** [comment]
Maybe something runtimed preventing proper deculting?
