### ISSUE TITLE
Chem grenade runtime

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9171]
08:57:43 Runtime detected
Cannot read null.total_volume at chem_grenade.dm:237
 proc name: prime (/obj/item/weapon/grenade/chem_grenade/prime)
  source file: chem_grenade.dm,237
  usr: Moises Gregory (/mob/living/carbon/human)
  src: the grenade (/obj/item/weapon/grenade/chem_grenade)
  usr.loc: the floor (12,235,2) (/turf/simulated/shuttle/floor)
  src.loc: null
  call stack:
the grenade (/obj/item/weapon/grenade/chem_grenade): prime()
the igniter (/obj/item/device/assembly/igniter): activate()
the igniter (/obj/item/device/assembly/igniter): pulsed(0)
the igniter-mousetrap assembly (/obj/item/device/assembly_holder): process activation(the mousetrap (/obj/item/device/assembly/mousetrap), 1, 0)
the mousetrap (/obj/item/device/assembly/mousetrap): pulse(0)
the mousetrap (/obj/item/device/assembly/mousetrap): triggered(Moises Gregory (/mob/living/carbon/human), "r_hand")
the mousetrap (/obj/item/device/assembly/mousetrap): on found(Moises Gregory (/mob/living/carbon/human))
the igniter-mousetrap assembly (/obj/item/device/assembly_holder): on found(Moises Gregory (/mob/living/carbon/human))
the grenade (/obj/item/weapon/grenade/chem_grenade): on found(Moises Gregory (/mob/living/carbon/human))
the bible (/obj/item/weapon/storage/bible): show to(Moises Gregory (/mob/living/carbon/human))
the bible (/obj/item/weapon/storage/bible): MouseDrop(Moises Gregory (/mob/living/carbon/human), null, the floor (12,235,2) (/turf/simulated/shuttle/floor), "mapwindow.map", "mapwindow.map", "icon-x=19;icon-y=19;left=1;scr...")
H0l3M4k3r (/client): MouseDrop(the bible (/obj/item/weapon/storage/bible), Moises Gregory (/mob/living/carbon/human), null, the floor (12,235,2) (/turf/simulated/shuttle/floor), "mapwindow.map", "mapwindow.map", "icon-x=19;icon-y=19;left=1;scr...")

runtime error: Cannot read null.total_volume
proc name: prime (/obj/item/weapon/grenade/chem_grenade/prime)
  source file: chem_grenade.dm,237
  usr: Moises Gregory (/mob/living/carbon/human)
  src: the grenade (/obj/item/weapon/grenade/chem_grenade)
  usr.loc: the floor (12,235,2) (/turf/simulated/shuttle/floor)
  src.loc: null
  call stack:
the grenade (/obj/item/weapon/grenade/chem_grenade): prime()
the igniter (/obj/item/device/assembly/igniter): activate()
the igniter (/obj/item/device/assembly/igniter): pulsed(0)
the igniter-mousetrap assembly (/obj/item/device/assembly_holder): process activation(the mousetrap (/obj/item/device/assembly/mousetrap), 1, 0)
the mousetrap (/obj/item/device/assembly/mousetrap): pulse(0)
the mousetrap (/obj/item/device/assembly/mousetrap): triggered(Moises Gregory (/mob/living/carbon/human), "r_hand")
the mousetrap (/obj/item/device/assembly/mousetrap): on found(Moises Gregory (/mob/living/carbon/human))
the igniter-mousetrap assembly (/obj/item/device/assembly_holder): on found(Moises Gregory (/mob/living/carbon/human))
the grenade (/obj/item/weapon/grenade/chem_grenade): on found(Moises Gregory (/mob/living/carbon/human))
the bible (/obj/item/weapon/storage/bible): show to(Moises Gregory (/mob/living/carbon/human))
the bible (/obj/item/weapon/storage/bible): MouseDrop(Moises Gregory (/mob/living/carbon/human), null, the floor (12,235,2) (/turf/simulated/shuttle/floor), "mapwindow.map", "mapwindow.map", "icon-x=19;icon-y=19;left=1;scr...")
H0l3M4k3r (/client): MouseDrop(the bible (/obj/item/weapon/storage/bible), Moises Gregory (/mob/living/carbon/human), null, the floor (12,235,2) (/turf/simulated/shuttle/floor), "mapwindow.map", "mapwindow.map", "icon-x=19;icon-y=19;left=1;scr...")

**Comment by Shadowmech88** [comment]
Tested locally, a chem grenade worked fine. I'm not sure exactly what circumstances would trigger this runtime, and nothing seems obviously wrong with the code. Given the report's age, I'm going to close this.
