### ISSUE TITLE
Flamethrowers are ridiculously good against xenos

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9173]
Shit's dumb
3-4 blasts from a flamethrower can put any given xeno at 100 fire damage
An unlucky xeno could probably die from a blast or two

Someone suggested making flamethrowers more bulky to offset their situational usefulness

**Comment by ihadtoregisterforthis** [comment]
Xenos don't have fire weakness, so how does this work with humans?

**Comment by AutismSpider** [comment]
Human hit by three blast they drop into crit (this is with shit mix in the tank i bet a good one would drop them in one or two blast)  diona drops in one blast not going wast time trying it on plasma men they only take 50% burn damage over all.

Over all flamer-throwers gone form going turn 90% of the station into death trap  using one tank of cold plasma into just going get shit mix and two/three shot people with some thing can be made with god damn rods and a welding tool

**Comment by MrSegi** [comment]
I tested the flamethrower with a 66/33 plasma/O2 mix at -266c, it drops humans in one blast if they are not wearing a hardsuit.

**Comment by FudgePucker** [comment]
Plasma tanks are contraband for a reason :^)

**Comment by Shadowmech88** [comment]
If it's too easy to get high damage with a bad mix, it would be simple enough to just nerf the flamethrower's total damage by some percentage.
Additionally, the flamethrower does double damage to non-human mobs, since in testing giant spiders seemed too resilient to a basic mix. I didn't think about xenos though, I might change it so that they only do double damage to simple_animals.

**Comment by AutismSpider** [comment]
@FudgePucker m8 flamers work with O2 tanks to and plasma not that hard to get on box or deff on taxi and meta it is.

**Comment by Shadowmech88** [comment]
@AutismSpider
I believe only plasma tanks can be loaded into flamethrowers.

**Comment by AutismSpider** [comment]
@Shadowmech88 old ones work with both plasma and O2 made sure for the new ones to only take plasma?

**Comment by Shadowmech88** [comment]
@AutismSpider 
Yes, the new ones can only take plasma tanks.

**Comment by Intigracy** [comment]
Xenos already had their fire damage bonus removed, what, do they have to be completely invincible to flame now?

**Comment by AutismSpider** [comment]
not the flame its the burn+them over heating with no real way to cool off

**Comment by FudgePucker** [comment]
I think flamethrowers should be OP, they are fucking flame throwers mother fucker.

**Comment by Tokanova** [comment]
It's a flamethrower, Xenomorphs even run from fire in the game where Xenomorphs are invincible, what the fuck is your problem?
If you want Xenomorphs to be stronger, don't nerf other things, buff them. Give them shit like colonial marines has, like the forcing unwelded doors open thing (Use the battering ram code perhaps) or the different evolution stuff with royal jelly. Make Weeds slow down non-xenos too, while growing faster. That'd make chasing xenos with a flame thrower a bit more dangerous.

**Comment by Kitfox88** [comment]
as an ert using the battering ram the other day i 100% support giving that shit to xenos by default, it's fun as fuck blasting open doors like a shithead

**Comment by Shadowmech88** [comment]
The code for it already exists, changeling horror forms have it as a verb.
I think it might be broken right now, though.

**Comment by AutismSpider** [comment]
It does nothing as a verb the spider mobs could force open airlocks to but they can't any more nor can they jam the locks up with web

**Comment by gbasood** [comment]
I never said that xenos should specifically ignore flamethrower damage. Just wanted to note that it was doing an insane amount of damage very quickly.
But it seems like based on what some other people have said that flamethrowers are ridiculously good in general?

@FudgePucker But they're way too easy to obtain, in my opinion, for them to be OP just because they're flamethrowers.

**Comment by Intigracy** [comment]
If the person using the flamethrower doesn't have proper gear, they end up fucked too, considering firelocks are going to activate the moment you use it + probably burn you to death.

It's a double edged sword.

**Comment by Shadowmech88** [comment]
@Intigracy 
Flamethrowers no longer affect the ambient atmospheric temperature as of #8318.

**Comment by Intigracy** [comment]
wow that's lame

**Comment by Shadowmech88** [comment]
The PR was open for half a month, no one seemed to have an issue with it.

**Comment by AutismSpider** [comment]
@Shadowmech88 sure about that m8 people had issue with it not heating up the room temp what it should keep doing any right now its better then god damn laser cannon if you can get get plasma tank or plasma man gas tank of cold plasma+O2 in it
