### ISSUE TITLE
Coming soon: Hyperthermia

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9176]
GET HYPE-RTHERMIA.
more information later - will have PR in two days
it'll have what the people loved about hypothermia, but better.

**Comment by Exxion** [comment]
OK that's cool and all but like
You could have just waited until you were ready to open the PR to announce it

**Comment by ghost** [comment]
@exxion All will become clear.

**Comment by gbasood** [comment]
hey where's that snow map

**Comment by Exxion** [comment]
I'm going to meme at you if it doesn't become clear

**Comment by 9600bauds** [comment]
He is already one big meme

**Comment by Intigracy** [comment]
How about fixing Hypothermia's issues before breaking more stuff?

**Comment by SysadminJeroen** [comment]
F E A T U R E F R E E Z E
Op 31 mrt. 2016 06:58 schreef "Intigracy" notifications@github.com:

**Comment by Intigracy** [comment]
Good idea Joeroen.

Let's call a feature freeze :^)

**Comment by PJB3005** [comment]
@Jeroen52 I approve, we've got too many bugs anyways.

**Comment by ghost** [comment]
What is the point of this 'issue'?

It seems more like an advertisement, and not even a good one.

> Coming soon to a station near you. Where previously cold has now become killer, with very little sensible ways to prevent it, we now bring to you - heat is now more lethal than before!

Considering the amount of heat you gain from a single pepper, you're going to go into heatstroke from being anywhere near botany.

**Comment by FudgePucker** [comment]
Oh boy, an update to the update that caused burning to death from eating a pepper, now eating a pepper will cause you to spontaneously combust and cause a fire in half the station.

I bet it will be 100% tested.

**Comment by unid15** [comment]
snow map when

lava map when

**Comment by PJB3005** [comment]
Space map when

<sup>wait</sub>

**Comment by 9600bauds** [comment]
I can't wait for plasmafloods to become even more deadly and commonplace!

**Comment by AutismSpider** [comment]
@9600bauds why plasma flood to much work when you can start a fuel fire and kill 90% of the station with less work

**Comment by SangriaMonkey** [comment]
> every spessman is a diabetic irishman with IBD who has never seen snow or gone camping before

d e e p e s t
l o r e

**Comment by ghost** [comment]
added to the game
