### ISSUE TITLE
Scanning a hydroponics pod with a device analyzer records the name of the plant, not the hydroponics pod

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9178]
#### Description of issue

Plant anything in a hydroponics pod then use a mechanics device analyzer to scan it, and take it to the reverse engine.  The reverse engine will give the name of the plant that was growing.  The flatpack fabricator prints out the correctly named flatpack, it doens't print potatoes its not that crazy.
#### Difference between expected and actual behavior

Tell you what, when you guys start having quality control and not merging a new broken thing in every week cough goonchat cough, i'll fill out the questionnaire here.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/14167519/cecb6510-f6e9-11e5-98d9-9809d08267fe.png)

**Comment by Killette2** [comment]
I'd l like to see potatoes with more efficient parts put into the biology of them using plastic, and then xenobotany will do the rest.

**Comment by FudgePucker** [comment]
Ha, the gen fab is so fucking stupid with its mat requirements that just some potatoes costs 27k iron, 4k glass, and 800 plastic.

Man someone really needs to fix that shitty piece of shit.

**Comment by Killette2** [comment]
But the question is, does it blend?

**Comment by Probe1** [comment]
personally i like how it lists plastic twice from the bygone days of when they would require random materials from the gold, silver, plasma, and uranium list.

one day I'm gonna snap, combine the general fabricator and flatpack fabricator, give them meaninful upgrades again, and de-fucking-clunk mechanics.

**Comment by 9600bauds** [comment]
I guess this should be using initial (name) when making the design datum
