### ISSUE TITLE
Cryo cells and pipes

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9180]
(WEB REPORT BY: dragonbro REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> When attempting to modify or build my own cryo center, I ran across two thing
1. You can't unwrench and move a cryo cell
2. Attempting to use a socket wrench on a pipe in front of the cryo cell means you'll be forever venting it, unable to remove it (This may be a bug with the cryo cell and its connected pipes, or the layer adapter)

> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible
> Attempt to unwrench the cryo cell in medical, or in the paramedics office, or attempt to move a cryo cell you had just gotten out of a flatpack.

**Comment by PJB3005** [comment]
Feature request for the moving cryo tubes bit.

The socket wrench thing is weird though. I tested it and it is indeed broken but only for the manifolds under the cryotubes, not for the single bent pipe at paramedics.

**Comment by ghost** [comment]
Think I found what was causing the layer adapter thing to go wonky.

turns out I'd linked it to distro without looking, but strange that it wouldn't vent at all

**Comment by Probe1** [comment]
cryo cells and freezers/heaters in general work very awkwardly and are not quality code when it comes to the atmos side of things.

I hate working with them.
