### ISSUE TITLE
Brain goes missing when you rejuvenate a decapaciated guy

### ISSUE THREAD

**Issue by MusgardTiger** [d3athrow/vgstation13#9181]
#### Description of issue

When you decapaciate a guy, then rejuvenate him he gets up then dies right away because he is missing the brain and the teeth. However decapaciated head still contains the actualy brain but I wanted to just rejuv the guy and get this over with.
#### Difference between expected and actual behavior

I expected the guy to have a brain.
#### Steps to reproduce

Decapaciate a guy, then rejuvenate him.
#### Length of time in which bug has been known to occur

Probably since forever tbh.
#### Server revision

371e0b458e8518dbf57a7425b2a4b4cf0941cf4d
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Intigracy** [comment]
I'm assuming it gives him a new head already, just without the brain?

**Comment by ihadtoregisterforthis** [comment]
"Decapaciate" meaning "Decapitate" in all instances?

**Comment by clusterfack** [comment]
Whose brain would have have? You cut off the brain. He is now the brain.

**Comment by Exxion** [comment]
Make a new brain and move him to that

**Comment by ghost** [comment]
Though I have seen this bug in the past, it seems to have been fixed now. Not sure how when or why though
