### ISSUE TITLE
AI Law Upload code might be leading to new bugs

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9183]
#### Description of issue

AI law uploading has shitcode in it, which seems to be leading to unexpected behavior lately
#### Difference between expected and actual behavior

Not being able to upload laws to the AI, seemingly at random
#### Steps to reproduce

Fairly complicated, but it seems to be related to the see_in_dark variable, maybe caused by an external factor. The actual check likely expects see_in_dark to be 0 when AI loses power
#### Specific information for locating

(law.dm)

```
    else if (current.see_in_dark == 0)
        to_chat(usr, "Upload failed. Only a faint signal is being detected from the AI, and it is not responding to our requests. It may be low on power.")
```
#### Length of time in which bug has been known to occur

No idea you fucks
#### Server revision

Latest as of this issue, fucking shiggydiggy
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

This form shit is a fucking tragedy, to bring it to the point : 

An oldcoder used an awful fucking check because he's incapable of seeing how the variable that allows mobs to see in the dark might be changed in the future to not correspond with the AI using it to determine if it lost power

This is most likely causing issues in some way as of CURRENT YEAR

**Comment by PJB3005** [comment]
@dylanstrategie if you're gonna make an "ahead of time" "bug" report, atleast TRY to investigate it.

`see_in_dark` is only set to 0 if the AI begins losing power, which is not a good thing.

Also if you're not gonna respect the issue bingo **don't fucking use it.**

Changing `see_in_dark` like this doesn't happen, and probably never will.

**Comment by ghost** [comment]
PJB, the AI was on full power at the time of the law change attempt, but it had had a power failure previous to that.

This had happened before, in similar circumstances, on tuesday, but seemed like a one-off thing.

**Comment by PJB3005** [comment]
If that's the case, then make a proper bug report instead of very shit speculation.

**Comment by PJB3005** [comment]
Wow I actually found a potential issue holy shit, but I highly doubt anybody would find it anyways.

Still a shit bug report, there's 5 locations in AI code where `see_in_dark` is set.
