### ISSUE TITLE
Cloning error.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9184]
(WEB REPORT BY: blithering REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 9b9aa46c2593bf6be288397cb1f34f61c7e64f68
> 
> General description of the issue
> When cloned, spawned with vampire HUD. Was not a vampire.
> 
> What you expected to happen
> Normal HUD
> 
> What actually happened
> Display showing total and usable blood. (at 185 and 140, despite not being a vamp)
> 
> Steps to reproduce if possible
> Not a clue on this one. Possibly clone someone during a vamp round?

**Comment by Probe1** [comment]
The best part is it was almost certainly a vampire round.

**Comment by 9600bauds** [comment]
higgs bugson

**Comment by ShiftyRail** [comment]
@Exxion this is most likely fixed.

**Comment by Exxion** [comment]
Yeah this kind of thing was pretty common for a while, but I haven't heard of it in a long time
