### ISSUE TITLE
Wall mounted hook has only one directional sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9189]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 6479e75b23d28ac1d05fbca0ea463a367759ea6c 
> 
> General description of the issue
> Attaching a lantern hook onto a wall always places it facing south, even if there's no wall to the south of it.
> 
> What you expected to happen
> Four directions of ambient lighting
> 
> What actually happened
> Just one direction for lantern hooks
> 
> Steps to reproduce if possible
> Make lantern hook with 1 metal
> try placing on wall

**Comment by PJB3005** [comment]
How can dylan suck this bad at coding.

@dylanstrategie.

**Comment by ghost** [comment]
And this was figured out just now ?

They look fine when placed at roundstart, so this is most likely a direction on new or sprite update issue

**Comment by PJB3005** [comment]
@dylanstrategie I figured it out.

You half assed it and there is 0 code to handle being placed in a certain direction.

**Comment by ghost** [comment]
I guess you're on the case then

**Comment by NigglyWiggly** [comment]
**STILL?**
DYLAN I MADE A BUG REPORT ALMOST IMMEDIATELY AFTER THIS WAS MERGED AND YOU SAID YOU FIXED IT

**Comment by PJB3005** [comment]
@NigglyWiggly that was for a very similar but not exactly the same issue.

Still dylan's a shitcoder.

**Comment by NigglyWiggly** [comment]
@PJB3005  You sure about that? #5137

**Comment by PJB3005** [comment]
@NigglyWiggly this issue is about hooks made during the round.

**Comment by Probe1** [comment]
what a buncha bullies.

**Comment by NigglyWiggly** [comment]
@PJB3005 
So was my issue
