### ISSUE TITLE
We have a serious scientific inaccuracy.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9191]
#### Description of issue

The "No oxygen" warning: ![](http://ss13.moe/wiki/images/1/10/HUD-Oxygen.gif)

Has the 2 above the O, instead of below it.
#### Difference between expected and actual behavior

2 would be below the O
#### Steps to reproduce

Jump into space.
#### Specific information for locating

`icons/mob/screen1_Midnight.dmi`
#### Length of time in which bug has been known to occur

For basically as long as we have this HUD, years.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by SysadminJeroen** [comment]
Currently editing the sprite.

**Comment by Killette2** [comment]
Ever consider we actually breathe squared oxygen?

**Comment by clusterfack** [comment]
Whoa

**Comment by IratePirate** [comment]
This was one of the first things I noticed when I started playing 3 years back.
