### ISSUE TITLE
Drink dispensers only take beakers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9192]
(WEB REPORT BY: brolaire REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Revision: 6479e75b23d28ac1d05fbca0ea463a367759ea6c 
> 
> General description of the issue
> Cannot use drinking glass for Soda, Booze or Tea dispensers

If not a bug, make this a feature request

**Comment by Exxion** [comment]
Not even the god damn shaker works

The problem is that they're children of chem dispensers
So changing this without also changing it for chem dispensers would require actual effort

**Comment by Shadowmech88** [comment]
No it wouldn't.
The fact that they're a child means that nothing you change for the drink dispenser will affect chem dispensers.
You'd just need to override the attackby() and make it not reject non-beaker reagent containers.

**Comment by Exxion** [comment]
Yes, but (depending on how it works, I haven't looked at the code), that may involve copying the whole thing and changing like one line, which we don't like doing

Wait a second I'm an idiot and `attackby()` only handles insertion of a container doesn't it

**Comment by Brolaire** [comment]
I would also like to point out that the soda dispenser is completely broken, as in it swallows the beaker but you cant interact with it. if you clcik on it with an empty hand, nothing happens. this mightve been unique to the round though

**Comment by Shadowmech88** [comment]
@Exxion 
Yes, `attackby()` is specifically called when you slap the machine with an item. A beaker, for example.

**Comment by Exxion** [comment]
Yes I know that
I was asking if it handled anything other than inserting the beaker for dispensers

**Comment by Shadowmech88** [comment]
I just skimmed the code, and it doesn't appear to.
The opening of the maintenance panel is handled in `/obj/machinery/attackby`, and it's the only other thing that would make use of `attackby()`.

**Comment by Intigracy** [comment]
Why is putting cups in the chem dispenser a bad thing again?

You can put buckets in it iirc.

**Comment by Probe1** [comment]
I don't see a problem with expanding the container list for chem dispensers as a whole.

**Comment by AutismSpider** [comment]
can put fucking rags in the chem dispenser! whats wrong with a cup or soda cans?

**Comment by Exxion** [comment]
> can put rags in the chem dispenser

Wow, rags just keep getting weirder

**Comment by Probe1** [comment]
Can you hold a rag over someones mouth?

**Comment by AutismSpider** [comment]
@Probe1 nope

**Comment by Kitfox88** [comment]
yeah i mean
if you can chem dispense into a bucket why not a bottle or glass or whatever

**Comment by Exxion** [comment]
#11557
