### ISSUE TITLE
It was inevitable really. Cat slimes.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#9202]
![kitties](https://cloud.githubusercontent.com/assets/15067109/14224143/fa88c390-f889-11e5-9eee-d92d9014e0d3.png)
Download link for icons:  http://s000.tinyupload.com/index.php?file_id=00925827381464261001

**Comment by sonime** [comment]
Tbh if if wasn't clear fetish fuel the idea of nekotoxin sounds fun if it inhibits speech.

**Comment by Senaat1** [comment]
:-1: :-1: :-1: :-1:

**Comment by Probe1** [comment]
normally I'd try to find something constructive or at least not comment but in this case: 

Fuck off.

**Comment by AutismSpider** [comment]
No if it was cute little side thing yeah but this is some one fetish fuel

**Comment by Senaat1** [comment]
I feel like four humbs down might not have been clear enough so i'll follow Probe's example.

Fuck off.

**Comment by Blithering** [comment]
![l9g4spe](https://cloud.githubusercontent.com/assets/15067109/14224303/37a78882-f890-11e5-8ff9-d4f58ffb492c.gif)

**Comment by AutismSpider** [comment]
Not good attention if any thing make a little vault with them in it so if people want be faggots they got hunt for the vault full of cat slimes and normal slimes

**Comment by 9600bauds** [comment]
I can't really comment on the idea but sadly I have to say that the sprite isn't terribly cat-like to me for some reason

**Comment by clusterfack** [comment]
Your april fools was one day late!

**Comment by Imagebard** [comment]
The sprite isn't that good, either.

**Comment by Kitfox88** [comment]
ragnarok online slimes when
