### ISSUE TITLE
Clown curse stops mime vox from gasping

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9204]
(WEB REPORT BY: solariousgabriella REMOTE: 158.69.55.2:7777)

> Revision 2f4132ad739907d393cbd6dea36201b10b426dcd
> 
> The wizard's spell of clown curse prevents a mime vox from gasping, this without their they could be cuffed and not have their internals on and have no way to show they're slowly dying.
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by FudgePucker** [comment]
Can't you still go me gasp or say *gasp?

Anyways why is security arresting the mime when there is a wizard?

**Comment by Exxion** [comment]
But why would they not have their internals on?
Both the clown mask and the mime mask work as internals

EDIT: Wait a second
Vox aren't _supposed_ to gasp when exposed to station air, as they die of toxins, not suffocation

**Comment by Kitfox88** [comment]
> Vox aren't supposed to gasp when exposed to station air, as they die of toxins, not suffocation

why can't we tune gasmasks to filter out certain particles in the air muh immulsions

**Comment by Exxion** [comment]
Sure, if you want to mount a whole scrubber to your face

**Comment by FudgePucker** [comment]
Gas masks don't work that way.

Firefighters have o2 tanks because masks can't really filter gases, they can only filter particles.

They can filter dust but not co2

**Comment by Shadowmech88** [comment]
>Vox aren't supposed to gasp when exposed to station air, as they die of toxins, not suffocation

Unless I'm missing something, it sounds like this isn't a bug.
