### ISSUE TITLE
Cable Coil from Gygax Wreckage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9205]
(WEB REPORT BY: pwirby REMOTE: 158.69.55.2:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Gygax wreckage producing 150 cable coil when using a wirecutter on it.
> 
> General description of the issue
> Gygax wreckage producing 150 cable coil when using a wirecutter on it.
> 
> What you expected to happen
> Get 10 of it; the same amount apllied to create it.
> 
> What actually happened
> Get 150 of it.
> 
> Steps to reproduce if possible
> Make a Gygax, destroy it, apply wirecutter on it.

**Comment by Imagebard** [comment]
Destroying Exosuits always has dumb results.
You can savage 150 cable coil, a battery, and a fully loaded O2 canister(The tile-wide ones) out of ANY destroyed exosuit.

**Comment by PJB3005** [comment]
I have no idea what to tag this.

**Comment by Imagebard** [comment]
Its likely no single correct answer exists.

Probably [Not A Bug] since it seems intentional, but?

**Comment by Probe1** [comment]
Add a tag for [SHIT CODE].  Then we can get in fights about it when it's applied.

**Comment by clusterfack** [comment]
If there was a shit code label, it wouldn't apply to this. (yes we'll start fighting about it before it is created)

**Comment by Probe1** [comment]
And thats exactly why it's a crummy idea.  Anyway the issue at hand seems clear enough.  Wreckage should not provide more materials than the amount it took to create it.  150 cable coil lengths is 5 entire coils.  It takes.. what, 10 he said?  to make the mech.

**Comment by PJB3005** [comment]
The costs of a mech are way higher than the costs of 5 cable coils, I don't think it's that big of an issue.

**Comment by Probe1** [comment]
who said it was?  but saying that a bug isn't a bug is buggy collaborative behavior and I don't want to hire someone to repair you.

**Comment by Imagebard** [comment]
Bug = Unintended Behavior
This = Intended Behavior

**Comment by clusterfack** [comment]
Its more of a consistency issue

**Comment by Probe1** [comment]
what part of it duplicates mats x15 is intentional?

**Comment by Imagebard** [comment]
Probe1, unless you see that in the code there's the event that makes it eject cable coil replicate itself 15 times when it should only do it once, then its intentional.

Why the hell are you even angry at this? Just because the code isn't a bug doesn't mean it won't be replaced.

**Comment by Probe1** [comment]
why do I appear angry or that I'm making a big deal?  it's a simple tagging issue as I've explained 4 or 5 times now.

it's not meant to produce 1 hundred and 50 (fifty) cable coils.  It does not take that many.  Collaborators have managed to pick tags that don't describe it and I've repeated myself what, 4 times now?

I'm not really sure where the anger or big issue is stemming from.  There's only so many ways I can keep saying it before I plum run out.

**Comment by Imagebard** [comment]
>it's not meant to produce 1 hundred and 50 (fifty) cable coils.

It also generates a battery, a oxygen canister, and cable coil out of nowhere.
Its the contents that would logically(A battery cell is used to power it, oxygen canister for the internal air, and the cable wire is here to connect the electronics) be here, but aren't put in here, either.

>why do I appear angry or that I'm making a big deal

Because, even tough this is going to be fixed, you're arguing that this should be tagged as "Bug/Fix" instead of "Not A Bug", even tough: 
*it realistically does not matter* (if you're posting just want this fixed)
and
*The truth of your statements can't be discerned right now* (if you actually think this a bug)

**Comment by Probe1** [comment]
I'm going to cite this later when we need an example of autism.

**Comment by Imagebard** [comment]
Omae no Mona

**Comment by Kurfursten** [comment]
I am definitely sure this is no longer the case
