### ISSUE TITLE
EMP making vending machines unfixable

### ISSUE THREAD

**Issue by Chronakai** [d3athrow/vgstation13#9206]
#### Description of issue

When a vending machine is broken, presumably by EMP blast, you can't fix it with any tool.
#### Difference between expected and actual behavior

Expected: Using some tool, like a screwdriver or crowbar on an EMP'd vending machine opens up the maintenance panel or pries out the electronics for soldering or replacement.

Actual: Using any tool on the vending machine in question gives a "X is broken! Fix it first!" message in chat. Cannot interact with the vending machine in any other way
#### Steps to reproduce
1. Spawn a vending machine
2. Push the button for Nuclear Detonation near Station random event
3. Repeat step 2 until the spawned vending machine breaks. EMP grenade may work too, not sure. The sprite will change to a broken vending machine.
4. Try to interact with it with any tool, such as a wrench or screwdriver.
#### Specific information for locating

Most, probably all vending machine objects
"[vending machine type name, i.e. YouTool] is broken, fix it first!"
#### Length of time in which bug has been known to occur

Not sure, first time I've encountered this.
#### Server revision

2f4132ad739907d393cbd6dea36201b10b426dcd (No notes about this issue in changelog since I encountered it 4/1/16)
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Did you use reinforced glass? Reinforced glass should be how to fix it.

Although I do agree it should be more clear.

**Comment by Chronakai** [comment]
I didn't use reinforced glass, no.
Is reinforced glass even used as a construction material in those?

**Comment by PJB3005** [comment]
I don't think you use it for construction, but IIRC it does get used for repairing.

**Comment by Chronakai** [comment]
That's not really intuitive, but good to know for the future.

**Comment by Chronakai** [comment]
Adventures on the test serb indeed say that rglass is the answer.
I'm not sure why it's rglass instead of regular glass like you unscrew out of computers, but there you go.

**Comment by Imagebard** [comment]
I'm also not sure why it uses r.glass
QUALITY indeed

**Comment by Tokanova** [comment]
I guess it's R glass because if it was normal glass the average spessman would eagerly smash it to get free snacks easier.

**Comment by Chronakai** [comment]
True. I'd suggest using a screwdriver on the broken machine would pop out the glass like computers do, and if you tried to be cheeky and weld the shard to put back in, it gives a message about not being strong enough?

**Comment by Probe1** [comment]
The reason it uses reinforced glass is a separate coding project.  Kicking vending machines was added long before kicking itself.  There was no way to repair vending machines that were kicked until they were broken.  Since it was being kicked, it was reasonable at the time to replace the kicked in glass and call it a day.

It of course didn't take into account there being many ways to break the machine.  So the only way to fix one is to replace the glass which seems pretty silly.

**Comment by Exxion** [comment]
You can't even unwrench a broken vending machine for some reason

**Comment by Probe1** [comment]
I believe I was the one that bitched about it and the repair action was added to compensate.

It's a pretty big mess.  What it needs to clean itself up is the standard disassembly applied when broken.
