### ISSUE TITLE
Shotgun darts can't be loaded with chemicals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9208]
(WEB REPORT BY: manfreed REMOTE: 158.69.55.2:7777)
After trying to load shotgun darts with chemicals I asked the thread how to do it and was told it doesn't work at all. However in the wiki it says this is possible.
I would have expected to be able to load them using a syringe similar to how it works with autoinjectors.
If this shouldn't be implemented due to ballance reasons the wiki needs to be updated.

**Comment by Killette2** [comment]
> Not a bug
> The most useless thing you can fire from a shotgun

We need shotgun darts

**Comment by Imagebard** [comment]
>Not A Bug

Pardon me, what?

**Comment by Shadowmech88** [comment]
If I remember correctly, the ability to load chemicals into shotgun darts was intentionally removed because it'd make a shotgun into a rapid syringe gun with more range.
The darts themselves were not removed for some reason, despite being useless now.

**Comment by Imagebard** [comment]
That's.
That's just.

But what about muh party booze shells?

**Comment by Killette2** [comment]
Well consider this, only 1 shotgun in the game can be sawn off to be stored in a backpack. The others are visible upon examination even if stored somewhere like the back or suit storage slot if possible. Rapid syringe gun is easier obtained, easier to hide, and syringes aren't illegal like shotgun darts are (I may be wrong on the autolathe hacking part). Having a shotgun be more powerful than a syringe gun seems perfectly fine to me considering how bulky of a weapon a shotgun is.

**Comment by Shadowmech88** [comment]
It's still a one-shot gg no re if it's filled with chloral. It'd be less useful for traitors because they can't conceal it, but it'd be just as useful for validhunting.

**Comment by Killette2** [comment]
Security: Hey why do you have a shotgun?
Crewmember: Oh I'm just validhunting, don't mind me they're filled with chloral shells so it's harmless
Security: My apologies, go ahead vigilante. There is nothing security would want to do about this scenario as you have the right to that weapon, despite not even owning a weapon permit access on your ID

The problem would be if security let them carry said guns, not the ability to carry said guns. There's a lot of bad things you can carry visually, and it only matters if security feels like stopping you.

**Comment by Shadowmech88** [comment]
I mean it would be a bad thing for _security_ to have them, because of how effective they are.
There's a reason Security doesn't have rapid syringe guns full of chloral in the armory.

**Comment by Killette2** [comment]
Well they have lethal shells, and lethal injection syringes, however that's a whole different level of chloral, but either way they can take you down if they want to with a shotgun. Security also has chemical implanters, so this wouldn't be the first time security has used chemical weaponry at all. This method only requires security get darts from cargo or RnD, then get the chemicals to put in them, which takes a lot of authorization.

**Comment by Shadowmech88** [comment]
Honestly your chances of survival are better if you get hit with one lethal shell than one chloral dart.

**Comment by Imagebard** [comment]
You realize that security doesn't start with shotgun darts, right?
And if you argue that they "can go get some form cargo", then I can also argue they can also go get syringe guns on medbay.

Seriously, I'm just here sitting and wondering who the fuck thinks shotgun darts are overpowered. Do you have an actual argument other than "But you can shoot chloral"(As if you weren't able to shoot chloral with a syringe gun?)

**Comment by Killette2** [comment]
I'd imply that shotgun darts could shoot through hardsuits, but that seems fair game. Keep in mind mech syringe guns, intentional or not, can also shoot through hardsuits so I just like to think they launch faster and the balance being it's a fucking mech. The only iffy side is that also means weaponizing an odyssues, but I'd rather be able to than not able to do something in spessmen.

Also I may be wrong but does security get lethal shells on any map? Maybe deffic or medbay that we may be overlooking? Hell on one map they get a grenade launcher I was told.

**Comment by Imagebard** [comment]
Security gets lethal shells on boxstation.

The map with a grenade launcher is a flashbang launcher, mind you. It CAN be loaded with lethal grenades but, how'd you gonna get that?

**Comment by Killette2** [comment]
Oh my mistake, I thought you said security starting with lethal shells, not darts.

**Comment by Shadowmech88** [comment]
> And if you argue that they "can go get some form cargo", then I can also argue they can also go get syringe guns on medbay.

The difference being that if you go to Medbay, you can get a single syringe gun that holds one chloral syringe, whereas if you go to Cargo, you can get a multiple combat shotguns that hold eight chloral darts each.
At least rapid syringe guns require doing some R&D.

**Comment by Imagebard** [comment]
Dude, I still don't see the problem.
In normal 1 vs 1 combat engagements, combat shotguns are clunky and you should be using taser + cuffs instead.

I can think this as being OP against Nuclear Operatives with 3 armed officers but if you roll to medbay/cargo enough to always have chloral syringes or always have shotgun darts you will already be banned for powergaming because *you're not allowed to go every round and get your chloral darts at roundstart*
So the only people who will be allowed to use shotgun darts every round will be, thum thum, the Bartender, who could actually use it to drug people with Gyro or whatever booze he has form afar.

**Comment by Killette2** [comment]
@Shadowmech88 

Cargo doesn't usually have a chem dispenser, but if they do good on them. Also you need at least armory access to obtain a non-bartender shotgun, the crate even implies it but we all know you can break a crate or break into the armory. It's still an authorization thing more than can you obtain it yourself thing.

**Comment by SysadminJeroen** [comment]
@Killette2: Emitter.

2016-04-04 19:32 GMT+02:00 Killette2 notifications@github.com:

**Comment by Killette2** [comment]
I just said it's about an authorization issue, not an obtaining issue. Anyone can break into the armory for a shotgun, and anyone can break into cargo crates. Did you read my post selectively?

**Comment by kernikov** [comment]
COUGH
No holy water darts for vampires

**Comment by Killette2** [comment]
Holy water grown trees carved into holy wooden stakes that can be shot from a holy crossbow as a bolt when?

**Comment by Imagebard** [comment]
Holy water grown tress carved into holy wooden stakes that can be shot from a holy crossbow as a *holy bolt* when

**Comment by nuklearcellphoneg** [comment]
Holy moly

**Comment by CptWad** [comment]
Good lord literally a one line fix on the wiki
we can close this or at least remove the [update wiki] tag
