### ISSUE TITLE
Wizard can blink whilst dead

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9209]
(WEB REPORT BY: solariousgabriella REMOTE: 158.69.55.2:7777)

> Revision bfd48c1a99c2db24a9596b9931c7002e3d9bf5dc 
> I clicked the blink spell (and all the others) whilst a corpse
> 
> Nothing should've happened when I clicked the spell
> 
> I blinked away
> 
> I believe this was possible as I entered and exited my corpse multiple times as a ghost

**Comment by coldcola** [comment]
as does ethereal jaunt.

**Comment by Intigracy** [comment]
![2016-04-06_22-00-22](https://cloud.githubusercontent.com/assets/4043940/14341090/0f639396-fc43-11e5-8dcc-1498dd3c1f4b.png)

Cannot reproduce.

**Comment by clusterfack** [comment]
Fixed by mindswap fixes I believe
