### ISSUE TITLE
Slamsed V2. BIBLE EDITION

### ISSUE THREAD

**Issue by Cisrox** [d3athrow/vgstation13#9210]
#### Description of issue

Bible hitting on head says slammeds wtf whoever fixed this needs to die
#### Difference between expected and actual behavior

It should say slammed, wtf
#### Steps to reproduce

Hit someone on head with bible until it says slammeds
#### Specific information for locating

Bible, hitting someone on the head says SLAMMEDS
WHO FIXED THIS I WANT THEIR HEAD ON A STAKE
#### Server revision

bfd48c1a99c2db24a9596b9931c7002e3d9bf5dc
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Cisrox** [comment]
HOLY SHIT IT SAYS SLAPPEDS TOO WHO THE FUCK DID THIS

**Comment by ghost** [comment]
quality linguistics module(tm)

**Comment by coldcola** [comment]
it was fixed for changeling horror you mong, grow up.
the person who put 'slams' as an attack verb that ends up outputting as 'slamsed' and 'attempted to slams' is at fault.
