### ISSUE TITLE
Should attack text be present or past tense?

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#9211]
Present, do the thumbs up to vote for this:
Chaplain McGriffon slams Faggot McGrayshirt in the head with the bible.

Past, do the thumbs down to vote for this:
Chaplain McGriffon slammed Faggot McGrayshirt in the head with the bible.

I'll give it 24 hours then change all the attacks to the winner.

Edit: By attack text I mean the shit that pops up in chat when you hit someone, admin sided stuff is going to stay past tense.

**Comment by ghost** [comment]
> April 2nd

**Comment by clusterfack** [comment]
Nobody cares

**Comment by Intigracy** [comment]
Well I'll fix issues like #9210 once and for all

**Comment by Exxion** [comment]
Definitely present tense. I thought this had already been decided on.

**Comment by Intigracy** [comment]
well screw 24h I'll just do it now.
