### ISSUE TITLE
There's no Thermal Homeostasis Regulator on Taxi

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#9214]
You took your antics too far @9600bauds

**Comment by clusterfack** [comment]
Alternate title: theres still a mancrowave on the other 3 maps.

**Comment by 9600bauds** [comment]
What's the issue here?

**Comment by Exxion** [comment]
The mancrowave is great though
It's still much more convenient than waking people with the sleepers because you don't have to open a UI or hit a button
Just throw them in and wait for a ding
Plus it works on people who are really hot or cold

**Comment by 9600bauds** [comment]
I added altclick to sleepers just so you don't have to open any menus
Also Cryo works both to cool people down and to heat them up

**Comment by Exxion** [comment]
I still really prefer the mancrowave, and I still see people use it all the time

**Comment by Shadowmech88** [comment]
> I like the mancrowave because you don't have to open a UI
> well the sleepers have alt+click now so they've got the same benefit
> I still prefer the mancrowave

?

**Comment by Exxion** [comment]
Have you heard of personal preference?

**Comment by clusterfack** [comment]
# STOP LIKING WHAT I DONT LIKE

**Comment by Shadowmech88** [comment]
I mean I just don't see any logical reason for the preference. The sleepers currently do everything the mancrowave does except temperature regulation, which is a rare issue anyway and can be solved with a single leporazine pill.

The mancrowave takes up space and it seems superfluous to me.

**Comment by 9600bauds** [comment]
The temperature regulation is also done by Cryo, I never see leporazine get made because temperature regulation is such a rare and niche case anyways, even after hypothermia.

**Comment by Exxion** [comment]
I like it because it's a one-step process. Throw them in and that's it. Don't even have to press another button. It's not exactly a huge deal, but it's nice. That's all I'm saying.
Considering it takes up a whopping two tiles, I don't really see the point of removing it, either.

**Comment by ghost** [comment]
Shall we remove the other entrances to medbay too? Particularly the one opposite the captains office. There's already a way to get into medbay, and it takes up TWO WHOLE TILES.

**Comment by Probe1** [comment]
I'm with the mancrowave is dumb department.  It's xbox hueg and only does two things.  Wake people up quickly and warm them up quickly.  Warming is already incorporated into cryo and waking is in the sleeper.

**Comment by Exxion** [comment]
> xbox hueg
> two tiles

**Comment by Probe1** [comment]
# HUEG

Size is an effect of location.  Every medbay had to have things removed so we could add mancrowaves.  They are twice the size of cryo - the machine they improve.

**Comment by 9600bauds** [comment]
Well to be fair, you should also count the freezer for Cryo

**Comment by xpcybic** [comment]
I was assured the mancrowave was getting taken off the other maps when I did this :hankey:

**Comment by 9600bauds** [comment]
Are there any changes that could be done to make sleepers replace the Mancrowave better, or is this just personal preference?

**Comment by Exxion** [comment]
Not really anything feasible, considering they have other functions

**Comment by 9600bauds** [comment]
Please elaborate

**Comment by Exxion** [comment]
It's nice to just throw someone in and be done with it, without even having to _click_ the thing again
But since sleepers have other functions, having them automatically wake and eject people thrown in would be rather silly

**Comment by ghost** [comment]
Removing player choice is silly. I'd take the argument about xbox huge if it was a valid one, or if it removed vital medbay equipment to be placed where it was on any map. It did not. On box, for example, it removed one locker (oh no!), and a literally useless oxygen tank. An argument about space being wasted only makes sense if you have something better to fill the space with.

**Comment by 9600bauds** [comment]
I have actually used that locker in the past but okay

**Comment by ihadtoregisterforthis** [comment]
You monsters
