### ISSUE TITLE
"sudden rush of air knocks you over" no longer appears in chat

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#9216]
#### Description of issue

The message you get when you fall over due to airflow hasn't been showing up since chat changed.
#### Difference between expected and actual behavior

I still fall down, I just don't know it's airflow unless I'm smart.
#### Steps to reproduce

Remove air from a room
Add a sudden rush of air to the room
#### Specific information for locating

(It's either A or The) sudden rush of air knocks you over
#### Length of time in which bug has been known to occur

Since chat changed
#### Server revision

ffba5cdcc40bf1c573f7fc737136556594f9543d 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
This was fixed, was it not?

**Comment by PJB3005** [comment]
Yup it was.

#9269
