### ISSUE TITLE
More subtypes for turf/simulated/floor/engine would be better

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9219]
This is something I'll probably tackle myself and i'm leaving this as a reminder for later.

![image](https://cloud.githubusercontent.com/assets/8550416/14232093/88006bfc-f96a-11e5-9fc8-d665c0e82e3d.png)

**Comment by PJB3005** [comment]
Correction: STOP USING INSTANCES AND MAKE SUBTYPES YOU SHIT MAPPERS.

**Comment by Probe1** [comment]
I need to learn how to create subtypes and what I'll need to do to migrate things to said subtype.
