### ISSUE TITLE
FRACTAL WATERMELON

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9224]
![](http://i.imgur.com/7I25IFD.gif)

![image](https://cloud.githubusercontent.com/assets/9827785/14234576/4458c6a2-f9b4-11e5-920d-f132fa50c361.png)

**Comment by Kitfox88** [comment]
yum

**Comment by FudgePucker** [comment]
Sheeeiiiitttt
Infinite watermelon? Is it right by the bottomless fried chicken bucket?

**Comment by Exxion** [comment]
It's not actually infinite
The bug is just that you can put watermelons within watermelons, layered arbitrarily many times

**Comment by FudgePucker** [comment]
I know that.

Also requesting the not a bug and its a fffeeeaaaaatttuuuurrreeee tags

**Comment by Exxion** [comment]
It already has the latter
