### ISSUE TITLE
The big old "These admin buttons don't have cancel buttons and should" issue

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#9228]
Basically every single one on the secrets panel.

**Comment by ghost** [comment]
The ban @Intigracy button isn't working can you fix it while you're at it

**Comment by Intigracy** [comment]
As soon as @DrCelt gets permanently deadminned with no chance of appeal.

**Comment by ghost** [comment]
deal

**Comment by ghost** [comment]
Drop bomb and Drop EMP lack cancel buttons
