### ISSUE TITLE
pAI recieves no indicator of recieving a PDA message beyond the beep

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#9230]
#### Description of issue

pAI's can't tell they got a message because it doesn't output into chat the message or that they got one
#### Difference between expected and actual behavior

I expect the pAI to beep in chat like a PDA would, or to just have the message pop up with a reply link
#### Steps to reproduce

Be pAI
Have master put you in their PDA (this might matter)
Send messages to the crew calling them losers
Hear beeps as they reply angrily, but see no messages without opening your interface
#### Specific information for locating

pAI PDA code
#### Length of time in which bug has been known to occur

No clue
#### Server revision

380bb99fad80f4e7b2827b34a12651a355a4b85d 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
The thread has alleged that this also applies to the AI since Goonchat was added, but I haven't personally tested it

**Comment by Probe1** [comment]
that's not true.  the screen of the PDA changes to a triangle ! alert.

**Comment by Intigracy** [comment]
Probe I saw that message you deleted.

Even if the pAI's icon changes to a triangle with a !, you won't ever see that because most of the time you're in someone's bag or pocket.

**Comment by Probe1** [comment]
Nah dude I mistook PDA for pAI.  I just woke up a few minutes before writing the message.  All on me, I was wrong.

**Comment by Intigracy** [comment]
#9367
