### ISSUE TITLE
Jukebox no longer announces songs as they start

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9232]
Appears to have been broken by Goonchat, but I have no idea why that would break it.

**Comment by Exxion** [comment]
Oh boy I can't even find where in the code it tries to announce the next song

**Comment by Exxion** [comment]
I have no idea when or how it happened, but this has been fixed.

**Comment by clusterfack** [comment]
It was fixed by my fix to visible message which was sanitizing messages with a bacon in them. There are potentially more issues fixed by that that I am too lazy to look for.

**Comment by clusterfack** [comment]
Bicon
