### ISSUE TITLE
Is it possible to allow decimal offsets for x_pixel offsets with dream maker?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9233]
I checked in dream maker and it had no effect.  It'd be pretty useful for mapping to really fine tune it in there.

**Comment by clusterfack** [comment]
Nigga how the fuck would that even make sense

**Comment by Intigracy** [comment]
It's a pixel based game.

You can't move half a pixel wtf.

Close issue when?

**Comment by ihadtoregisterforthis** [comment]
Partial pixels? I dunno, maybe you can ask satan when you meet him in hell.

**Comment by PJB3005** [comment]
Nope.

This also isn't the place for asking BYOND questions.

**Comment by Probe1** [comment]
I didn't know if it was a SS13 variable or hardcoded.
