### ISSUE TITLE
Increase the rarity of stormtrooper armor and blasters.  Cool it down with the overt references.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9234]
#### Description of issue

References are ok and most of the items in game are referencing something in sci fi.  But it's important that we don't look like some shit tier gmod server with bad skins of things.  

The star wars stuff added doesn't fit and its readily accessible so not only is it a really blatant reference, it's constantly around.
#### Difference between expected and actual behavior

Something like this to be admin spawn or an uncommon find.  Found it in the armory instead.  You might find it hypocritical when we have ED bots stomping around but they fit the game far closer than star wars and look like they belong.  After all, the title track of SS13 is almost indisputably the theme from the Robocop game.  Eswords aren't called lightsabers, you get what I"m saying?
#### Steps to reproduce

Merge anything people submit

**Comment by Manaony** [comment]
I support this. Down with coder tyranny.

**Comment by ihadtoregisterforthis** [comment]
How should we add more references without being obnoxious?
More variety? More OC along with references? Make them not so obvious?

**Comment by NigglyWiggly** [comment]
I'm probably not one to speak when it comes to this sort of thing, considering I added megaman stuff to the Autodrobe, but I agree.
Little references and nods to things are perfectly fine, but just outright saying "Stormtrooper" seems a bit silly, it's the exact reason why the Judge Dredd armor isn't readily available ingame.

@ihadtoregisterforthis
My personal method of doing this has been to never explicitly say what the item is in reference to.

**Comment by SangriaMonkey** [comment]
Original stuff can be just as out of place though.
Case and point: vox spacesuits.
Tighter quality control across the board would be nice.

**Comment by Tokanova** [comment]
@NigglyWiggly What ought have been done is the Stormtrooper armor should of been called something else, like 'Standardized Imperial Issue Military Armor'

**Comment by Probe1** [comment]
@ihadtoregisterforthis I'm fine with them existing.  They're already in and someone worked hard to give us this.  But let it be a great loot item for a vault.  Something a vox trader could sell.  An item that isn't normally obtainable.  It can still be in game but is less common than a stock item at roundstart.  

I feel like the autodrobe gets a pass on a lot of stuff because it's a costume vend.  It should have cowboys and indians dressup stuff.

**Comment by 9600bauds** [comment]
I don't really see the stormtrooper armor often enough to be concerned, really
Meanwhile I see the half-life combine stun stick constantly

**Comment by NigglyWiggly** [comment]
And that's an example of a reference done right.
Is it even directly based off of the Half Life one?

**Comment by Probe1** [comment]
I didn't realize they were a reference to half life until you brought it up and I feel really dumb for not realizing it.  Stun prods are pretty common in sci fi and even real life now adays though.

HL stun baton is clearly the sprites inspiration but ours has a much brighter hue and glows orange.  HL2's doesn't glow itself but has a blue arc of electricity.

![2016-04-03_20-53-52](https://cloud.githubusercontent.com/assets/8550416/14236129/37c491a8-f9de-11e5-87d6-7500585c83d2.gif)

**Comment by SangriaMonkey** [comment]
Pretty much.
![wew](http://media.moddb.com/cache/images/games/1/13/12465/thumb_620x2000/baton.png)

**Comment by Blithering** [comment]
I can think of more commonplace items that stick out more, such as the knight armour crate orderable from cargo. I understand I'm almost certainly biased here, but stormtrooper gear for sec was requested a lot at the time. 
If it's really that out of place, perhaps changing the gear into an alternate choice for nuke ops who want to re-enact the opening of episode IV, like the nazi gimmick vendor.

**Comment by clusterfack** [comment]
Who made the stormtrooper shit obtainable anyway?

**Comment by SkowronX** [comment]
This x1000

**Comment by Killette2** [comment]
Why is there no outfit that doesn't make security less violent? Nazi vendors and stormtrooper outfits is asking for escalation and tyranny

**Comment by Probe1** [comment]
@Killette2 Vulgaris has worn a vest and shorts for the last 3 years and that hasn't made him any less violent.

**Comment by Killette2** [comment]
He's a barechested man of the law, that sounds pretty tough to me. Call me when Vulgaris is being violent with a schoolgirl jumpsuit only, while playing security.

**Comment by ihadtoregisterforthis** [comment]
Call me too please

**Comment by Killette2** [comment]
Here's my issue number
Call me maybe

**Comment by Kitfox88** [comment]
i usually put on the 'bored security guy at a fortune 500 company' uniform and i try to be nice

**Comment by clusterfack** [comment]
#9315

**Comment by Killette2** [comment]
I kinda miss it now, let's put it back in
