### ISSUE TITLE
Revamp the Gateway / Exile Implants

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#9236]
As-is, the gateway is a useless room since away missions suck so never get turned on.

The gateway should be made to work at any time, so long as it finds another gateway to teleport to. This way we can add gateways to vaults to have even more fun with them.

Exile implants should get changed to cause damage to you so long as you're on z1.

**Comment by 9600bauds** [comment]
Might be shitty if you're trying to spessexplore with an exile implant and you randomly end up in z1

**Comment by Intigracy** [comment]
That's your fault for breaking the restraining order, obv.

**Comment by Blithering** [comment]
Perhaps instead of trying to revive away missions, which I have been told were buggy and difficult to map, have the gateway send you to a random vault when used? Since their implementation the major gripe with them has been the difficulty in reaching them in the first place.

**Comment by ihadtoregisterforthis** [comment]
Vaults are the closest we are to away missions anyways
