### ISSUE TITLE
Poly gets silenced once surgically implanted into someone

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#9239]
Well, today while doing my rounds in medbay we happened to have poly nearby for some reason. We had a patient who was being difficult and decided that it would be best to put the bird in him so it would stop taking everything.

Once implanted into his body the bird stopped talking all together, it was still alive but wouldn't talk. I consider this to be a pretty amusing bug and think that poly talking in chest cavities would be benficial to the server. It would appear that the reason for this is when poly is in ones hand it is weapon type and when implant is keeps that instead of reverting back to mob. If possible I believe this should be fixed for all pets that make sounds

**Comment by Exxion** [comment]
Poly normally speaks while in item form anyway. He definitely talks from within backpacks.
What an odd bug.

**Comment by Imagebard** [comment]
@9600bauds stop memeing the "OH GOD IT'S LOOSE" tag please

**Comment by PJB3005** [comment]
People are shit at tagging.

**Comment by ihadtoregisterforthis** [comment]
But that's Poly's line

**Comment by PJB3005** [comment]
Oh, right lack of a singuloose alarm is indeed a big problem.

**Comment by clusterfack** [comment]
Pretty sure this was a virtualhearer bug we fixed
