### ISSUE TITLE
I call bullshit

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9241]
![image](https://cloud.githubusercontent.com/assets/9827785/14240894/363c5f72-fa16-11e5-818c-8c028db5728a.png)

**Comment by Intigracy** [comment]
What, never tripped over your own feet?

**Comment by NigglyWiggly** [comment]
> Goliath is so excited to meet you that it stumbles over its own tentacles

C U T E

**Comment by Exxion** [comment]
I think this particular case was a goliath "knocking down" a different goliath, but it could probably happen that way too
It's in quotes because there was no actual effect on the goliath, as far as I could tell. Just the text.

**Comment by ihadtoregisterforthis** [comment]
Infighting when

**Comment by Intigracy** [comment]
Well beasties already attack each other.

I'm not sure if goliaths attack other goliaths, but they do attack the other mob types.

**Comment by Probe1** [comment]
Re-open if you plan on doing anything with this.

**Comment by Exxion** [comment]
:|

**Comment by Probe1** [comment]
I'm sorry we have nearly 2000 issues and I'm going to have to step on toes.  You are extremely welcome to re open it so you can close it with some kind of PR addressing goliaths tentacling goliaths in rare circumstances.

It's not like I don't think you're awesome.
