### ISSUE TITLE
Hailer QoL request

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9244]
When you use a hailer, it shouts halt security. In a crowded area or even when following someone, someone could just dismiss it as you goofing off with a noise maker, thus when you're using it for it's intended purpose it becomes useless. This idea would make hailers more useful.

I am now going to reference bike horns and rubber duckies. Items that used to only make noise when you used them in hand, but now we have a feature to honk at a specific person for whatever reason.

Clown honks his horn at Chef (example) is a message that appears in chat when you click on another player with said horn or duck. The clown would see this, the chef would see this, and everyone else around would all see this message.

What if this was used in a populated medbay instead of firing a taser at a crowd of people hoping to hit your guy? You pick up your hailer, click the perp (if you misclick and click someone else, just click the guy you intended to more than the accidental guy) and everyone in the area will immediately be aware who you intend to arrest or search, and may possibly aid you even instead of being meatshields for stun shots. This would also remove the excuse of criminals saying "I didn't know that was for me!" since they would obviously know it was. Yes, you can still be a dickbag and randomly hailer people 4noraisns, but this QoL feature that we could use from bike horns would massively improve hailers, save officers a few taser shots when a victim would be willing to cooperate, and make security overall less unneedly aggressive in certain situations.

Just tested to see if this is an existing feature on the test server, it is not.

**Comment by Shadowmech88** [comment]
I believe the purpose of hailers is to signal a moving person to stop while you're following them, since it's difficult to type while running and it's not easy to discern between "this security officer is chasing me" and "this security officer happens to be walking to the same part of the station that I am."

If the person is just standing in a crowded room, you could use your voice to point out that they are the one you want to talk to.

**Comment by Killette2** [comment]
pagedown to use an item in hand or clicking their person is a lot faster than typing out something to get their attention, especially when the person who's attention you are trying to get is moving.

So yes, that is a hailers purpose, but this makes them more useful to signal that you specifically want them and are not just using the hailer to make noise, and you can further use it as evidence that you wanted them to halt if they continue to evade you.

**Comment by ghost** [comment]
:+1:

**Comment by ghost** [comment]
May as well make Hailer a child of the bikehorn if you do this.

**Comment by ghost** [comment]
Actually you could even also make it set people to arrest if you have sec access. That'd be pretty good.

**Comment by Killette2** [comment]
Know what else would be good? To see if people have weapon permits on sec HUDs so they have more of an excuse to crack down on people bearing arms. Currently sec has no way of telling if you have weapon permits besides using beepsky I think.

**Comment by 9600bauds** [comment]
Oh hey this wasn't autoclosed
