### ISSUE TITLE
Bombermen suffocate now

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9245]
They need 02. The arena isn't unsimulated so we all slowly choke to death.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
@9600bauds This is fixed, Deity made the floors unsimulated

**Comment by PJB3005** [comment]
> pinging bauds.

Bauds left.

**Comment by gbasood** [comment]
> 02

also just make them not need to breathe

**Comment by Exxion** [comment]
> Bauds left

When? Why?

**Comment by clusterfack** [comment]
Because I called him a fag

**Comment by Exxion** [comment]
That seems unlikely to be the only reason

**Comment by Killette2** [comment]
He called him a queer too
