### ISSUE TITLE
You shouldn't be able to see while riding the disposal pipes [9247]

### ISSUE THREAD

**Issue by chatsonf** [d3athrow/vgstation13#9247]
Right now as of this current time, you can see all around you while you travel through the disposal piping. In a high RP sense, you shouldn't be able to see shit, you are in a fucking pipe in the dark, but that isn't the case. This leads to possible powergaming where you see people in maintenance possibly doing traitorous things, from changelings absorbing people, to cultists placing runes and converting people.
I suggest that while you are in a disposal pipe, you are temporarily blinded.
If you are fully blinded though, you won't be able to see that you are moving, so if you were stopped by either being a fat person or running into another fat person, there should be a message display saying that you have stopped, or have started moving again.

**Comment by Probe1** [comment]
There's something like, when you're pipe crawling the pipe you are in is highlighted.  

Also naturally you'd have to give people with x-ray vision
