### ISSUE TITLE
Could we remove all the arr pee xenoarch machines no one ever touches?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9249]
see these?

![image](https://cloud.githubusercontent.com/assets/8550416/14252103/d415cb92-fa53-11e5-8c50-d7bf45c811e8.png)

no one ever really uses these.  and they take up a lot of space.

**Comment by 9600bauds** [comment]
Could at the very least almost certainly be made into one single machine

**Comment by PJB3005** [comment]
And made less shit and tedious overall...

**Comment by 9600bauds** [comment]
Then again, maybe some people like having to use multiple machines, and they only take up a whole room of 4x6, so is it really worth doing away with personal preference????????

**Comment by ihadtoregisterforthis** [comment]
#6755

**Comment by Probe1** [comment]
Duplicate yeah.  Can we close the other one that went nowhere and is buried while this is somewhat near the top of the pile?  @Skullyton

**Comment by 9600bauds** [comment]
I guess the other one has some more info on what the machines do, copypaste that here

**Comment by Probe1** [comment]
> Not necessarily a bug, more of a feature request/discussion

![687474703a2f2f696d6775722e636f6d2f6d3851453457692e706e67](https://cloud.githubusercontent.com/assets/8550416/14253139/4b8d73ec-fa58-11e5-9e5f-bd4b774b2b77.png)

> Basic Machines
> 
> Gas Chromatography - This machine is a great baseline when you want to use all the anomalist machines. It allows one to test the compatibility of carrier fluids against the sample fluid. It also identifies types of tests that are applicable when using that carrier fluid. Try using the common carrier fluids such as the one applicable to the material type (field type), carbon, or iron.
> Ion Mobility- This machine is used to identify what quantity of the carrier fluid is present. Basically, the higher the number, the more likely that’s the material your anomaly is made out of, but this device can only test one carrier fluid and will give no results if there is none of that reactive agent present.
> Accelerator - Used to examine the age of the material, only works on the billions of years scale.
> Isotope Ratio - Used to examine the age of the material, only accurate up to a billion years.
> So, the functions of these machines can be effectively replaced by keeping notes on where you took the strange rock sample from, or is just lore fluff.
> 
> There's been a bit of discussion on removing these and instead replacing it with Xenobotany (Giving it more room to breathe and actually being useful) which would also free up the current area that xenobotany currently takes up for a break room (Basically somewhere to put a washing machine, something that xenoarch needs if it needs to use plasma to test large artifacts)
> 
> Putting this here for more of a easier way to log the discussion for ideas and such, save it disappearing into the void of SS13 logs

**Comment by Shadowmech88** [comment]
The accelerator and isotope ratio machines seem 100% useless. I can't think of any reason why you'd need to know the age of a thing.
The gas chromatographer seems theoretically useful, but plenty of people do Xenoarch just fine right now without using it.

**Comment by kol1th** [comment]
The whole

> here's been a bit of discussion on removing these and instead replacing it with Xenobotany (Giving it more room to breathe and actually being useful) which would also free up the current area that xenobotany currently takes up for a break room (Basically somewhere to put a washing machine, something that xenoarch needs if it needs to use plasma to test large artifacts) 

sounds pretty great.

I've _never_ seen anyone use those machines or the suits, anyways, let alone go in that room.

**Comment by Konater** [comment]
I don't think they were for arr pee but instead to get the type of rock from a sample to even start digging for artifacts. Then someone added that ability to the scanner.

**Comment by PJB3005** [comment]
Most are for RP, one is to make sure your carrier fluid is correct (not needed if you're not an idiot) and one is to track down LARGE artifacts.

**Comment by FudgePucker** [comment]
Maybe remove or add functions to some of the useless ones and make new sprites so it isn't a room filled with machines that look all alike.

**Comment by Probe1** [comment]
aged out
