### ISSUE TITLE
Should the Bhang-o-meter display the name of the area for each explosion together with the coordinates?

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9253]
One thing that's weird is that most things that work on coordinates can also know what area those coordinates belong to, such as GPS', SPS', the Crew Monitoring Console, etc.
However, the Bhang-o-Meter's readouts only include the coordinates of each explosion, with no clue on what area those coordinates are.
This results in people not knowing where where the explosion happened unless someone confirms it, and since those coordinates are affected by station drift/offsets you can't cheat and look at a render either.

One effect of this is that explosions are less high-profile than I think they should be: If the readout says it was an IED, nobody will care much because it could be anywhere, if the readout says "IED in Cargo Lobby" suddenly it's a completely different story.

**Comment by FudgePucker** [comment]
Wait, does this mean you can use ieds to figure out the telesciense cords on the zlevel?

**Comment by 9600bauds** [comment]
Well that requires the telepad, and seeing as there are multiple GPS' which do the same thing but better right next to the telepad...

**Comment by ihadtoregisterforthis** [comment]
I don't think the Bhang-o-meter reads IEDs

**Comment by 9600bauds** [comment]
Yes it does, it even used to read 0, 0, 0 explosions

**Comment by Intigracy** [comment]
Yes, it should read the area.

**Comment by 9600bauds** [comment]
For reference, this is the readout of an IED

![dreamseeker_2016-04-04_17-22-47](https://cloud.githubusercontent.com/assets/6526157/14262038/e179ccee-fa89-11e5-9362-d87cb3d37e99.png)

Anyone wanna guess where it was?

**Comment by Intigracy** [comment]
"Explosive disturbance detected at Cargo -" when?

**Comment by Kitfox88** [comment]
CARGONIA FALLS

**Comment by Probe1** [comment]
Add a variable for telecomms that lets you convert coordinates to locations.

Let players manually run it.

**Comment by Tokanova** [comment]
@Probe1 Couldn't they already do that by just sending a GPS to the coordinates and checking it?

**Comment by 9600bauds** [comment]
That is a rather massive stretch, people using telesci productively and in short notice is rarely heard of and definitely not for something as small as checking an IED explosion

**Comment by Probe1** [comment]
@Tokanova no, people that work telescience know EXACTLY where the IED went off because they were utilizing the nice reinforced floors to open a weapon lockbox.

I think that this really puts a little too much info too easily in players hands.  I have a rough idea from coords on Box where an explosion happened and sometimes call it out.

**Comment by 9600bauds** [comment]
Really? Because the coords from the explosion I posted point to the dead center of Medbay if you go by admin coords, but it was actually the floor of the research shuttle. The coordinate drift is MASSIVE, the most you could figure out is if the explosion was roughly on the left or right side of the station maybe.

**Comment by Probe1** [comment]
ADMIN LOG: Explosion with size (-1, 1, 3) in area Toxins Mixing Room **(212,277,1)** (JMP)

bhangmeter beeps, "Explosive disturbance detected - Epicenter at: grid **(206,245, 1)**. Epicenter radius: -1. Outer radius: 1. Shockwave radius: 3. Temporal displacement of tachyons: 0.1 seconds. Data logged."

40 isn't a massive drift.  It's enough to say where it happened but not exactly where.

**Comment by 9600bauds** [comment]
It's random each shift, so it could be 40 or it could be
![mspaint_2016-04-05_12-30-01](https://cloud.githubusercontent.com/assets/6526157/14287691/21041874-fb2a-11e5-903b-531ae5d30403.jpg)
Regardless that's a rather silly way of guesstimation and it's obviously not practiced by nearly anyone in the playerbase. I don't think it's a good mechanic.

**Comment by Probe1** [comment]
I think it gives players too much information.  Also I think the job name script being integrated into default telecoms was a step in the wrong direction as well.  So take what I'm saying with a grain of salt.

I like cool shit that the players can do themselves.   If it were an upgrade like an advanced version or a variable was integrated into telecoms that converted coordinate strings into locations then I would be 100% on board

**Comment by clusterfack** [comment]
It can be up to 50 in either direction. This is about the size of the entire station if you have a centralized point.

**Comment by Probe1** [comment]
Ok then what would even be the point of adding a location if it's going to be so erroneously wrong except to fuck with players

**Comment by clusterfack** [comment]
Pretty sure thats literally the point of the issue

**Comment by Probe1** [comment]
How bout we add drift inputs for the bhang?

**Comment by 9600bauds** [comment]
I don't think that memorizing coordinates in order to be able to understand the bhang at all is a good mechanic

**Comment by 9600bauds** [comment]
Maybe we could take the tcomms route and add a function to tcomms scripting to return an area, but 
1) it'd have to be limited to the station's z-level of course
2) I think it could let an AI work out the telesci drift by itself through sheer autism, not sure how much of a big deal that could be

**Comment by Probe1** [comment]
I have reconsidered my opinion and recant.

Do it.

**Comment by 9600bauds** [comment]
You know, I thought about this too and although the "guess from the coordinates" thing is plain bad, there's some merit in what Probe said about letting it up to the players via T-comms. How could a compromise be reached?

**Comment by clusterfack** [comment]
By doing what you said originally because its the superior idea

**Comment by Probe1** [comment]
Basically.  I'm pulling out.

I want a telecomm script but I won't get it and I'm being stubborn to say the whole idea is rotten.
