### ISSUE TITLE
Spawn a mob of mobs doesn't work

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9255]
#### Description of issue

A while ago, a new secrets button was added that would apparently let you spawn a certain amount of a certain mob, both of which are to the users discretion

Problem is, when using it, it lets you pick the amount, but doesn't let you pick the mob, leading to this

![Lists](http://i.imgur.com/BQ89LMV.png)
#### Difference between expected and actual behavior

What was expected - Being able to randomly spawn a specified amount of a specified mob

What happened - It let me choose the amount, but not the mob
#### Steps to reproduce

Admin tab, Secrets button, 'Trigger mobs of your choice appearing out of thin air', press it, go through the instructions, note that there's no prompt that lets you pick what mob you want, panic when everyones immersions are broken that there is now a wild pack of /lists on the station
#### Specific information for locating

See Steps to reproduce
#### Length of time in which bug has been known to occur

Considering I haven't seen any other admins try it, possibly from when the feature was first merged #9064 
#### Server revision

9886be1e30f40f250712b52c59f94204c7d525c4
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [?] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

@gbasood ?

**Comment by FudgePucker** [comment]
Now all we need is a glitched /list mob

**Comment by Tokanova** [comment]
If this gets fixed please fix 'Statio' to Station too

**Comment by gbasood** [comment]
pretty sure I fixed this
