### ISSUE TITLE
Can use PDA normally (including PDA messaging) while statued by Flesh to Stone

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9261]
#### Description of issue

Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
#### Difference between expected and actual behavior

Expected behavior: Cannot use PDA normally (including PDA messaging) while statued by Flesh to Stone
Actual behavior: Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
#### Steps to reproduce

Statued by Flesh to Stone, use PDA normally (including PDA messaging)
#### Specific information for locating

Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
#### Length of time in which bug has been known to occur

Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
#### Server revision

Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
- [ ] Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
- [ ] Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
- [x] Can use PDA normally (including PDA messaging) while statued by Flesh to Stone
- [x] [Can use PDA normally (including PDA messaging) while statued by Flesh to Stone](https://github.com/d3athrow/vgstation13/issues)

**Comment by Killette2** [comment]
I don't see a problem with using your PDA while stoned. You may however find yourself sending obnoxious messages, the crew probably doesn't want to hear how stoned you are and will find it annoying. However if you find out someone else is as stoned as you are, you two may want to PDA it out for a while until the magic wears off. But hey, who says you won't get stoned more than once in a round like that one guy who got a trophy for it?

**Comment by 9600bauds** [comment]
Well since you can't talk normally I assume you shouldn't be able to talk while stoned

**Comment by Killette2** [comment]
Speaking of flesh to stone, should it even affect golems? Their flesh is already stone.

**Comment by Intigracy** [comment]
Bauds, can you put it on your belt/id slot and pick it up, or only if you had it in your hand when you were stoned?

**Comment by 9600bauds** [comment]
I had it in my PDA slot and I dragged the sprite to myself like a normal person do

**Comment by FudgePucker** [comment]
I wish I could be stoned right now

**Comment by Killette2** [comment]
That could be aranged

![stonedwaifu](https://cloud.githubusercontent.com/assets/5169310/14271866/45143d8e-facb-11e5-9c35-c8d78650d4b2.jpg)
