### ISSUE TITLE
Fatness is Broken

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9262]
#### Description of issue

Fatness seems to be completely broken. None of the things that fatness is supposed to restrict are being restricted.
I had an admin spawn me in the thunderdome and make me fat in order to verify this, so there weren't any interfering factors.
#### Difference between expected and actual behavior

While fat, your sprite does not change to the fat sprite, and you are still able to move at normal speed and wear hardsuits. When inspected, it would still say "he is quite chubby," so it appears that I was fat, but being fat didn't do any of the things it's supposed to.
#### Steps to reproduce
1. Be fat
2. Try to do something fat people can't do, like put on a hardsuit
3. Still be able to put it on despite being fat
#### Length of time in which bug has been known to occur

Last round was when I confirmed it. Not sure when it started.
#### Server revision

9886be1e30f40f250712b52c59f94204c7d525c4
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Through additional testing, it seems that starting the round having chosen obesity as a disability spawns you in as a properly obese person.
However, I was unable to remove my jumpsuit, though other mobs could strip me of it and I could put it back on. Also whenever I attempted to put on a hardsuit, it would give me the "you're too fat" message twice, which might have something to do with the fact that both M_FAT and M_OBESITY were in my mutations list twice.

**Comment by Killette2** [comment]
Maybe it's one of those situations where you're too fat to do things like put your clothes on or bathe by yourself, and that reasoning is sadder than being too fat for your own clothes.

**Comment by Shadowmech88** [comment]
Additionally, if I use VV to give myself the M_FAT disability, it doesn't change my sprite and I get the "you feel fit again!" message within a second, though trying to equip a hardsuit within that second gives the standard too fat message.

**Comment by Killette2** [comment]
Honestly is there even a point to fatness in space? It serves little to no purpose, and has few functions and interesting features.

**Comment by 9600bauds** [comment]
It's also very unmantainable because of needing two sprites for every clothing item
AFAIK we're one of the very few servers that still have it

**Comment by CptWad** [comment]
Acutally its the Fat SE
it does not make you fat at all
Genetics or admin powers

**Comment by SysadminJeroen** [comment]
I actually got fat after eating a lot of pizzas.
![ss 2016-04-06 at 08 35 34](https://cloud.githubusercontent.com/assets/2915526/14331226/b0bf5eae-fc44-11e5-984b-45f1cd964cee.png)

**Comment by CptWad** [comment]
eating can make you fat but you have to eat A LOT
its not like times of yore where if you ate till you were full and kept eating you would get fat its something you have to upkeep in order to achieve

**Comment by 9600bauds** [comment]
I think the issue is that you can't overeat food but you can overeat nutriment if you pour it in a glass or eat a lot of ramen or something, thus it's the only way to get fat

**Comment by Shadowmech88** [comment]
This is still a thing, by the way.

On a local server I ingested and metabolized 50u of straight nutriment. My sprite did not become fat, nor was I prevented from wearing hardsuits, though my examination text did show "He is quite chubby."
After ingesting and metabolizing 50u of lipozine, the "He is quite chubby." text still did not go away.

I spawned a new human and toggled its fat gene. It, too, was not prevented from wearing hardsuits, however this human also did _not_ receive the "He is quite chubby." examination text.

**Comment by chatsonf** [comment]
The "proper" way to quickly become fat right now is to modify the overeatduration variable, which works [here](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm#L64)

**Comment by Shadowmech88** [comment]
@Furbeh 
So does the problem stem from the fact that `overeatduration` is not incrementing for some reason?

**Comment by chatsonf** [comment]
@Shadowmech88
No what it is is that you aren't changing the overeatduration variable when you force-change their mutations, which doesn't update their icons and immediately makes them stop being fat due to the overeatduration variable not being above 100.

**Comment by Shadowmech88** [comment]
> you aren't changing the overeatduration variable when you force-change their mutations

I believe using the admin panel to toggle a player's fat disability is functionally the same as receiving the disability via a genetics injector, so if that's the case, then it's a problem with the genetics disability itself.

But that still wouldn't explain why I couldn't become fat by consuming 50 straight units of nutriment. Have you successfully become fat from eating food in testing?

**Comment by chatsonf** [comment]
> I believe using the admin panel to toggle a player's fat disability is functionally the same as receiving the disability via a genetics injector, so if that's the case, then it's a problem with the genetics disability itself.

Yeah right now the disability doesn't do anything unless it is given by the overeatduration condition.

> But that still wouldn't explain why I couldn't become fat by consuming 50 straight units of nutriment.

Nutriment doesn't affect overeatduration directly, it should affect nutrients which in turn affects overeatduration.

> Have you successfully become fat from eating food in testing?

Yes I have, it just takes nearly 10 minutes due to the fat that it has to increment up to 500 to become fat.
While initially overeatduration wasn't increasing once I made a tochat tester for it it seemed to be incrementing.

**Comment by Shadowmech88** [comment]
Did you test lipozine, as well?

**Comment by chatsonf** [comment]
I didn't test it during the time but looking at [the code for it](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/reagents/Chemistry-Reagents.dm#L2695) it should work fine since it immediately sets your nutrients and overeatduration variables to 0, thus triggering the overeatduration unfat condition code

**Comment by Shadowmech88** [comment]
I'll make a new issue specific to the fat disability not properly making you fat, then. Sometime tomorrow.

**Comment by chatsonf** [comment]
Yeah in the end the fat mutation is a puppet of overeatduration, due to how it works.

**Comment by Shadowmech88** [comment]
Are you sure you were looking at the right mutation? The fatness disability is different from the "state of being fat" mutation, just like the hulk power is different from the "state of being in hulk" mutation that, for example, highlanders have.
