### ISSUE TITLE
On a pain scale I'm at a 1 with nine digits following it

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9263]
![dreamseeker_2016-04-04_20-11-46](https://cloud.githubusercontent.com/assets/8550416/14267813/d4185c60-faa1-11e5-869e-3952832176ef.png)

**Comment by Shadowmech88** [comment]
What even is an advanced pinpointer? I've never heard of it.

**Comment by clusterfack** [comment]
What do you think you are showing to us exactly?

**Comment by Probe1** [comment]
That dbquery/proc/execute is once again bulking hard and we're once again having the server hang for no apparent reason.

**Comment by clusterfack** [comment]
Well obviously it is the highest proc because you are profiling the start of the round when everyone logs in

**Comment by CptWad** [comment]
Advanced pinpointer (something that spawns at the ERT gear room) is a pinpointer that can point to anything, or more importantly anyone.

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/commit/d7d60e9f5ecb176cc98335588f3f39a78a3d41d4
