### ISSUE TITLE
structure/dispenser doesn't have a sound file when wrenched down

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9268]
#### Description of issue

The tank storage unit is the thing you get o2 and plasma tanks from. 

You lean down and unwrench the tank storage unit.
You wrench the tank storage unit into place.

No sound plays when you wrench it into place
#### Difference between expected and actual behavior

Seems fitting to have a sound here.
#### Server revision

9886be1e30f40f250712b52c59f94204c7d525c4 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
I can assure you goonchat did NOT cause this, it never had one at all.

**Comment by Probe1** [comment]
kek
