### ISSUE TITLE
Layered pipes placed in dream maker don't show up in game when multiple layered pipes are on the same tile

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9270]
![dreammaker_2016-04-05_10-53-00](https://cloud.githubusercontent.com/assets/8550416/14290195/11d815f6-fb2c-11e5-8668-f02d5b08bbfe.png)

#### Description of issue

Layered pipes placed in dream maker don't show up in game when multiple layered pipes are on the same tile
#### Difference between expected and actual behavior

painstakenly put down layered pipes to maintain a rooms furhurbunker level of reinforced walls without running pipes through rwalls

didn't work in game
#### Steps to reproduce

place layered pipes on the same tile **in dreammaker** and notice how they don't appear in game.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Do they show up in Dream Maker if you save, close, and re-open the map?
Basically, are they still there and just not in-game, or are they completely deleted?

**Comment by Probe1** [comment]
Correct.  They are there in dreammaker permanently.  I did those steps.

When the game compiles and server starts, the pipes that are layered on the same tile are missing.

**Comment by PJB3005** [comment]
Sounds like a piece of sanity against stacked pipes that's failing to take layers into account.

**Comment by Intigracy** [comment]
@DrCelt code strikes again

**Comment by PJB3005** [comment]
@intigracy doubt it in this case.

**Comment by PJB3005** [comment]
@intigracy doubt it in this case.

**Comment by Intigracy** [comment]
He made layered pipes.

**Comment by PJB3005** [comment]
No, comic did.

Celt made the pipes fancy.

**Comment by Intigracy** [comment]
Oh.

**Comment by Intigracy** [comment]
Actually, this DOES work, you must be doing something wrong.

Look at the pipes in the atmos control room on box.

**Comment by Probe1** [comment]
I did but when I used them they did not appear so somethings fucked here.

**Comment by Shadowmech88** [comment]
Can confirm it is at the very least not working properly.
In testing, straight pipes mapped in on a different layer showed up as though they were on the regular layer until they were unwrenched and wrenched back down. Putting two 4-way manifolds, each on a different layer, on the same tile resulted in both being invisible, though still present when inspected with Alt+Click. They were unable to be removed due to "needing to remove the plating" despite the fact that the floor there was plating and specifically it was the same turf type that the other, visible, pipes were on.

**Comment by Probe1** [comment]
aged out

**Comment by Shadowmech88** [comment]
![image](https://user-images.githubusercontent.com/3991927/67600137-07584c80-f737-11e9-9471-80385cd17b67.png)
![image](https://user-images.githubusercontent.com/3991927/67600143-0b846a00-f737-11e9-902b-e381c16f39f8.png)
Reported as no longer existing by burneddi on Discord.
