### ISSUE TITLE
HOW 2 BE A GRASSHOLE (grey asshole)

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9271]
1. Be a grey
2. Obtain pAI
3. Ingest a metric fuckton of sulfuric acid
4. Have pAI make smoke

Congratulations! You now have a zero-effort and zero-suspicion (as long as you are between steps 3 and 4) acid smoke bomb
Similar fuckery can be done with other races and different chemicals, but this is the most egregious (that I can think of, though since acid deals brute rather than burn damage for some reason, it's possible a diona could do this with polyacid, but the smoke would probably still kill them)
Examples include:
1. Gassing of the vox through inaprov smoke (kind of piss damage really, but very easy to do)
2. Gassing of the greys through water smoke (REALLY easy)
3. Gassing of the everything except dionae through any kind of smoke that would deal only brute/toxin/radiation damage

I admittedly haven't tested this, but it definitely _should_ work

**Comment by Intigracy** [comment]
At least if you're doing it with acid, you die too.

It's not any harder to just grab two beakers with the ingredients and mix them, or inject yourself with the smoke reagents when the time comes.

It's not zero suspicion because the smoke spawns ON you, so anyone with intelligence will know who it came from.

**Comment by PJB3005** [comment]
@intigracy you're a gray so you're immune to acid.

**Comment by Intigracy** [comment]
You're still immune to acid if you do it with two beakers.

Why is doing it via pAI a problem? It can only make the smoke, you still have to make/get the acid on your own and inject yourself.

**Comment by PJB3005** [comment]
@intigracy because you don't even have to pull out any beakers.

**Comment by Intigracy** [comment]
That's why it has a 15 byond second timer from the moment the pAI initiates it.

It also doesn't work when the pAI is in a PDA, and I think when in a bag but not sure about that one.

**Comment by Exxion** [comment]
Does the amount of acid in the container when you make the smoke affect anything?

**Comment by Intigracy** [comment]
Afaik that never got fixed to only apply based on the amount of acid in the smoke, which is why acid smoke is so lethal.

**Comment by Exxion** [comment]
Well, if that DOES get fixed, keep in mind that the human reagent container is over three times as big as the largest beaker

**Comment by Probe1** [comment]
I need to test it but I believe that pAI smoke does not properly log the contents of said smoke.  It'll just say a chemical reaction occurred here.

Tested.  Injected myself with polyacid, had the pAI use smoke and received this log.

> ADMIN LOG: A chemical smoke reaction has taken place in (Thunderdome | 132, 76). No associated key.

Not only do we not get a notification of who, we don't get what either.

@PJB3005 Logging and Administration tag please.

**Comment by Killette2** [comment]
Time to hydrate myself and gas the grays when needed via pill injestions

**Comment by AutismSpider** [comment]
This is stuff Rambling Maniac does a lot with a PAI+borer combo
