### ISSUE TITLE
Unreachable extinguisher cabinet

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#9272]
#### Description of issue

inside boxstation's medbay there is an unreachable extinguisher cabinet
#### Difference between expected and actual behavior

that i could take the extinguisher, but i couldn't, because you need to stand in an adjacent tile to take it
#### Specific information for locating

west of the body scanners, near the medical records computer

![extinguisher cabinet](https://cloud.githubusercontent.com/assets/6170726/14291922/fe6844ac-fb65-11e5-95dd-43f7db92ed10.jpg)
#### Length of time in which bug has been known to occur

i saw it today, tested again in the testing server
#### Server revision

d7d60e9f5ecb176cc98335588f3f39a78a3d41d4
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by FudgePucker** [comment]
I guess the table is in the way maybe, this violates firecodes.

Sue NT

**Comment by Probe1** [comment]
I just shut down git for the day too
