### ISSUE TITLE
Server hangs for a couple+ seconds every time someone logs in (or at least that's the popular theory behind the crippling lag as of lately)

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9273]
I think pretty much everyone is aware of this by now, but this needs an issue at least
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [xxxxxxxxx] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/issues/9263
https://github.com/d3athrow/vgstation13/issues/9246

My  previous two issues on the topic.

**Comment by 9600bauds** [comment]
good thing I didn't check that last one ;^)
But yeah apparently the cause is people logging in

**Comment by Probe1** [comment]
https://github.com/d3athrow/vgstation13/commit/d7d60e9f5ecb176cc98335588f3f39a78a3d41d4

**Comment by 9600bauds** [comment]
It's been happening way before that commit

**Comment by gbasood** [comment]
The commit was to fix the issue, not what caused it.

**Comment by 9600bauds** [comment]
Did that even fix it? I've still been noticing lag

**Comment by gbasood** [comment]
This still seems to be an issue even now that savefile code has calmed down a lot.

Could we get someone to profile Login() a bit to try to narrow this down or something? If it's related to the code and not the serbian setup then we should be able to reproduce it locally via guest logins, so we dont need to add profiling code to the serbian unless it turns out to be happening ONLY on the serb

**Comment by clusterfack** [comment]
It has never had anything to do with savefiles it has to do with mysql queries inserting connection information and can be solved by anyone willing and knowledgeable enough to make an async dll to insert.

**Comment by ComicIronic** [comment]
Can the Byond side even handle async code I thought it was single-threaded single instruction?

**Comment by clusterfack** [comment]
Thats why the dll is in a different language and just returns immediately

**Comment by gbasood** [comment]
It isn't JUST about making an async dll
It's also about making the serb recieve the info back via Topic() or some other means

**Comment by 9600bauds** [comment]
Hasn't happened in a while
