### ISSUE TITLE
Wooden chairs require 3 wood to build, only give 1 wood when disassembled

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9276]
#### Description of issue

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Difference between expected and actual behavior

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Steps to reproduce

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Specific information for locating

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Length of time in which bug has been known to occur

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Server revision

Wooden chairs require 3 wood to build, only give 1 wood when disassembled
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
It was either wooden chairs or another kind of chair that was changed to this because you got more materials back than it took to make.  Good grief.

**Comment by Killette2** [comment]
When you disassemble table parts of any kind you also get less materials, but I guess that's more intended since you can carry around a table.

**Comment by gbasood** [comment]
I feel like there's other issues that are also related to this

**Comment by ghost** [comment]
Make it cost one wood plank, chairs shouldn't cost that much

Three wood planks is a shitload for a single chair

**Comment by Killette2** [comment]
Three planks for a wooden chair, but two for a table. Sounds about right.
