### ISSUE TITLE
Tacticool helmet lights for sec helmets.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#9279]
![helmet light](https://cloud.githubusercontent.com/assets/15067109/14321856/cf08d5d4-fc12-11e5-9f74-8ce2d3a044ae.png)
Icons for a security helmet light attachment. Comes in tan for tacticool desert camo.
Download link for sprites: http://s000.tinyupload.com/?file_id=02685895708682422056
Edit: Now also comes in goofy blinking siren version as well.
![constable](https://cloud.githubusercontent.com/assets/15067109/14324584/4723982e-fc1d-11e5-843a-5f998a0af382.png)

Maybe have them bought from those vendors in cargo that noone uses and attached/detached with a screwdriver?

**Comment by Killette2** [comment]
There's a reason why police officers have the sirens on their car and not their head, but it's so retarded I can't not love it.

**Comment by 9600bauds** [comment]
Where should the helmet-mounted flashlights be available from? Sec lockers?

**Comment by Killette2** [comment]
or you could just attach a flashlight to it

**Comment by 9600bauds** [comment]
but there is already a tacticoollight icon I CAN'T JUST IGNORE IT SOMEONE ALREADY SPRITED IT
![dreammaker_2016-04-07_01-58-42](https://cloud.githubusercontent.com/assets/6526157/14341053/46d08228-fc64-11e5-8715-ca4af3193b01.png)

**Comment by liltiptop** [comment]
YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES YES I NEED THIS SO MUCH YES THANK YOU.

**Comment by ihadtoregisterforthis** [comment]
Can't the blinking siren be on the middle of the helmet?
![siren helmet](https://cloud.githubusercontent.com/assets/13305885/14361970/deed72c2-fcd3-11e5-85a6-c4eb9ec8e8fb.jpg)

**Comment by Blithering** [comment]
@9600bauds You could put them in the sectech vendors, maybe as premium stock, or the vendor outside cargo that sells stuff for people with excess cash. Or if there ends up being more of this tacticool gear, you could open up a chain of /k/-mart
![kmart](https://cloud.githubusercontent.com/assets/15067109/14362096/f8b65d78-fcf5-11e5-9f80-1eda55cc9b32.png)

**Comment by 9600bauds** [comment]
![firefox_2016-04-07_16-12-44](https://cloud.githubusercontent.com/assets/6526157/14363613/937e1834-fcdb-11e5-93a6-0e3df3a9fa74.png)
