### ISSUE TITLE
How do we fix the economy update?

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9281]
I'm the idea guy and even I can't think of a way to fix this shit. The only way to make money is to mug someone. Can we just steal goons 10 minutely paychecks or something?

**Comment by gbasood** [comment]
> The only way to make money is to mug someone

Nope. Miners materialize money out of thin air when they process their ores at cargo.

Also, we already have an issue, opened VERY RECENTLY, which discusses economy things, please stick to that:

#9163

**Comment by Killette2** [comment]
Thanks for the link, here's a thumbs up since I didn't notice it :) :+1:
