### ISSUE TITLE
Implementing money sinks so that money can actually do something

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9283]
First of all the main thing we'd want to do is **ACTUALLY DOCUMENT HOW TO USE THE EFTPOS SYSTEM** in such a way that people can find and use it and will actually want to use it

The core idea of all of this is to make the station more dependent on cargo to keep the station running. Cargo would then pay out money to Nanotrasen to fulfill orders. So eventually the station would run out of money, theorhetically, all on its own.

Here's some possible, simple money sinks.
- Booze-O-Mat takes money, requires resupply packages from cargo. Bartender could charge for drinks to keep the booze flowing.
- Paid vendor in medbay lobby which dispenses simple medical supplies (bandages, ointment, inaprov)
- Make the merch computer in cargo require resupply. Have the money spent on it go to cargo's department budget.
  - Posters for the merch computer.
  - Station souvenirs for the merch computer. (I Toured Nanotrasen's New Research Station And All I Got Was This Shirt)
- PDA terminal revenue should go to station budget.
- Add a vending machine which processes barcode'd items into itself. Passersby could then buy from the vending machine using a simplified list. Might be similar to EFTPOS I don't know
  - Barcodes have IDs (similar to UPCs) that determine what 'stack' in the vending machine the item falls under. The vending machine handles the prices. Prices can be changed by the vendor owner (chef for instance)
- Make Vox traders actually trade things if #9073 merges

Also, instead of going to the individual department's budgets, could have all vending-related things go into the station's budget, which could then be managed by the HoP. (suggested in #9163 over [here](https://github.com/d3athrow/vgstation13/issues/9163#issuecomment-206503049))

Better tools for department/station budgeting should be added as well, but not the focus of this issue. Possibly allow for HoP to see department withdrawals/deposits in total to see their profits/losses over the entire shift.

**Comment by ihadtoregisterforthis** [comment]
Should we get an [Economy] tag?
If not, why not just keep everything related together, instead of opening an issue every week?

**Comment by gbasood** [comment]
Maybe temporarily, since it's so popular now.

**Comment by Imagebard** [comment]
We need a simpler money exchange system if anything else.

**Comment by xpcybic** [comment]
Spitballing a couple of things floating around in my head and also ideas I've seen:
- What @Imagebard said definitely, make player-to-player transactions easier to perform
- Bring back tourist, make it a latejoin role that starts with a bunch of money to burn
- Bring back non-antag objectives; fulfilling them earns you a paycheck bonus
- Research-based roles like genetics and xenoarch earn bonuses based on their findings, sent to NT in some way
- Supply-based roles like botany, engineering (excess power supply), mining earn bonuses through exports via Cargo (how would payments be forwarded to the players that earned them?)
- Antags (maybe only sometimes) start with a bounty; sec (or anyone else?) can apprehend them and cash this bounty in
- Antag embezzlement objective, as seen on Goon
- Department heads manage their department's payroll and handing out of bonuses; would require more player cooperation and might be easily abused
- Station accountant role? Accounting department? Just make the Captain do it?
- Apply scarcity to things that are currently unlimited or very high in supply, like chem dispensers <sup>this would be incredibly cruel <sup>so maybe <sup>not</sup></sup></sup>

**Comment by Probe1** [comment]
@Imagebard PDA transfer money is too complicated?

**Comment by Probe1** [comment]
Every time we have this conversation it loops back to the same place.

We can't have things that cost money because we don't have ways to make money.  So we need a salary system.  But no one will code it.  So we go round and round with miners being the only people that make money.

**Comment by Exxion** [comment]
Do not make the Booze-O-Mat require money. It already takes obnoxiously long to dispense things.
The rest is all fine though.

**Comment by Imagebard** [comment]
>PDA transfer money is too complicated?

PDA transfer money is ingame?

**Comment by Shadowmech88** [comment]
@Imagebard 
There's a button on your PDA to wire money directly to another person. Has been for _months_.
You can even print physical credits from your PDA, directly out of your account.

**Comment by Intigracy** [comment]
Shows how often you actually play.

**Comment by gbasood** [comment]
@Exxion The time to vend could be removed if cost were added.

**Comment by gbasood** [comment]
@Probe1 We can't change how money is made without making players actually want to spend the money they make.

Money can be gained easier than it can be spent, as it stands.

**Comment by Intigracy** [comment]
How can money be made outside of mining?

**Comment by gbasood** [comment]
@Intigracy The station account starts with a ~~metric fuckton of money~~ a small sum of money actually that is never utilized.

Mining can make so much money so easily that it can actually produce more than what each department account combined starts with.

**Comment by Probe1** [comment]
@gbasood We have been over this for years.

Get salaries in, no ones interested in another failed EFTPOS based on head canon of how people play the game.  We need money to have a reason to spend money and no head (when they exist which varies to extremes based on population) takes the time to give their 'staff' money.

**Comment by Intigracy** [comment]
EFTPOS should get removed tbh, PDA sending is so much easier.

Money could be made more interesting if it were actually possible to steal from other people. As-is, you HAVE to know their bank ID and pin number, just stealing their ID doesn't work unless they lowered their security settings (which most miners do since you can't spend your money otherwise).

The economy sucks and gets talked about over and over again but nothing ever gets done or tried.

**Comment by 9600bauds** [comment]
You can steal money from IDs, you just can't steal ALL their money but it lets you steal some

**Comment by Exxion** [comment]
The POS machines are inflexible to the point of uselessness
I have no idea how the EFTPOS system works but I doubt it's any better

**Comment by ghost** [comment]
This is a poorly thought out suggestion and doesn't tackle the root of the problem even slightly

**Comment by liltiptop** [comment]
The thing is that most people, (chef, botanist, scientists, bartender) don't use the cash register, and stuff like guns, food, and plants are basically free. Seeing as how miners get LODSOFEMONE and only heads of staff have a fraction of what miners can get, I recommend a sort of "hourly payment" system. Meaning, depending on your job, you would earn a basic amount of cash, (let's just assume for now half of your stating bank account) and every hour or half an hour, you would get money transferred into your account. Other variables, like how much the botanist plants, bartender/chef makes drinks/meals, and the research levels of sci, how clean/charged/not exposed to space the station is for engineers and janitors, and viruses cured for medbay could add on extra cash. OR WE COULD JUST HAVE EVERYTHING FREE LOL.

**Comment by gbasood** [comment]
@Probe1 And yet most people are telling me to do the EXACT OPPOSITE
At this point I'm just going to put it to a highpop vote and see where to go from there because no one's going to do anything otherwise, it seems. Except Celt and I feel like he has enough shit to do with hypothermia and everything else he has plans for.

@DrCelt First wages are bad because we don't have money sinks, then money sinks are bad because you don't think the players will use any of them :+1: 

Edit: I'm not saying they aren't bad, I'm saying that I don't know what the hell else we're going to do to make players give eachother money for literally anything.
I'm not particularly attached to any one of those ideas. Just brainstorming, really.

**Comment by Probe1** [comment]
We've had votes and discussions and even some preliminary work by Deity.  

We need ways to get money that work.  We've agreed that salaries work.  We don't need to discuss it, we just need to do it.  And no one has done it so we're here trying to have the same discussions all over again when what we need is action.

**Comment by gbasood** [comment]
@Probe1 First I've heard of this.
Anyways I did some brainstorming on wages as well over at #9163 which it looks like you've read.
I'll work on that today so everyone can tell me I'm ruining the game again.
