### ISSUE TITLE
Cancer can't be operated on with surgery

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9285]
#### Description of issue

Some Clarnet commented out the surgery because it was 'too easy' #9212
#### Difference between expected and actual behavior

> Expected
> Being able to operate on cancer in its earlier stages
> actual
> You can't surgically remove cancer, making its easiest treatment 'beat the fuckers head in with a toolbox and clone him'
#### Steps to reproduce

> Get cancer from an admin
> Ask for it to be operated
> Search the wiki to see what the operation procedure is
> Realize that nobody updates the fucking wiki anymore when they add something
> Codetrawl
> Realize it's been commented out because it made the process 'too easy' and 'needed to be balanced'
#### Specific information for locating

It is located at #9212 
#### Length of time in which bug has been known to occur

When #9212 was merged
#### Server revision

b9705b97f4a7e4364e62dade06df73640669bd2e
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Intigracy** [comment]
It being admin only doesn't help when dylan gives people cancer every round he's on.

**Comment by Probe1** [comment]
Cancer has been used 7 times in the last two weeks, all in the same day, and dylan did it 3 of those times. Serwind did it 4.  

That said, jesus christ remove this from prayers and shit.  Put it in the secrets menu if you want but this is dumb griff shit and I've seen enough.

**Comment by Imagebard** [comment]
I FOREWARNED YOU

**Comment by ghost** [comment]
About an hour and a bit ago, it was used multiple times.

When it was found that surgery was no good, they just beat the afflicted heads in and cloned them, no chems applied or anything.

Why take the long route when you can take the short route? And taking out the shorter route isn't balancing, it's making what was 'murder if not helped by another' into 'You're guaranteed to die'

**Comment by Probe1** [comment]
Excuse me.  I mixed up the days.  4 times today.

**Comment by gbasood** [comment]
@dylanstrategie Fix it

**Comment by gbasood** [comment]
Apparently dylan INTENTIONALLY removed surgery, and you need to do chemo or limb removal to cure it now.
Because he's an asshole.

**Comment by Intigracy** [comment]
Well yeah, the OP linked the PR that he did it in multiple times.

**Comment by 9600bauds** [comment]
This is just so fucking stupid

**Comment by carshalash** [comment]
Is this a joke?

**Comment by ghost** [comment]
What gets me is how quickly it was merged, same day at the least, whereas others that are less questionable have been left up for months until they become incompatible.

**Comment by clusterfack** [comment]
>Left up for months until they become incompatible


Fuck off with straight up lying

**Comment by gbasood** [comment]
Cancer was up there for at LEAST a week, probably more
In fact, it was created 12 days ago and merged 4 days ago

**Comment by ghost** [comment]
@gbasood The PR to remove the surgery wasn't

**Comment by Imagebard** [comment]
Controversial PR merged in 8 days, anyone?

**Comment by Probe1** [comment]
i'm sorry that we didn't follow every PR and assumed the collaborators wouldn't merge dylan adding fucking inoperable cancer into the game so he can grief people.

The fuck.

No.

Bad.

**Comment by Tokanova** [comment]
Revert Dylan code when?

**Comment by ihadtoregisterforthis** [comment]
"Clarnet", that's a good name

**Comment by liltiptop** [comment]
HOW TO MAKE CURES FOR CANCER:
Small tumors: Operate on by surgery.
Large tumors: Use phalanximine until smaller tumor, then operate. (or amputate)
THERE FIXED EZPZ VALIDZ SECURED LET'S GO HOME

**Comment by ghost** [comment]
Actually, the idea is the exact opposite
- Chemotherapy for small tumors, especially brand new ones if some moron comes in with a metastased lump
- Amputation for xbox hueg cancer you wouldn't be able to get rid off otherwise
- You can also use chemotherapy on big tumors, but you either need to massively OD them on chemotherapy chems or have them come in every five minutes for scanning
