### ISSUE TITLE
Allow pAIs to be like navis from MMBN series.

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9286]
This is a feature that has often been discussed in OOC, so why not have a bit more fun interaction between pAIs and their owners? To simply things, the gameplay would be similar to mmbn2 with no program advances, but also no style changes. Also since this would have to be worked on for a long time, we would also want no elemental weaknesses.

Besides being a gimmick, what will this provide pAIs?
+new things to download
+ability to upgrade/buy ram, that's just how the series worked don't question it
+more fun interaction between other pAIs involving netbattles, strategy sharing, and chip collecting

How it would work

Owners of pAIs would want to jack their pAIs into APCs. The location of the APC depends on the type of viruses you may encounter there, or you may travel through the APC through wires to move to another APC. This will also allow the strategic cutting of wires to gimp your opponents pAI's traveling abilities through the wire network. Once in an APC, you may roam around and talk to NPCs just for the sake of being amusing, until a random encounter virus pops up. When you defeat the virus, depending on how fast you do it, you will be rewarded zenny (not space cash) and if you're good, their battle chips. Like in the MMBN games, the people must work with their navi during netbattles. The operator or pAI owner, will select which chips to give the pAI to fight with, and the pAI will control the movement and use the chips in battle. If you lose a battle, your pAI will be deleted, but to prevent this you can save a backup in your PDA for an amount of memory. NPCs will sell memory to you for zenny you obtain for winning battles, so as long as you have a back up you should be fine and not have your best friend die. To jack out of the wire net, You simply use the pAI on the APC you jacked into, or in the case of that APC being destroyed, you can message your pAI to a different APC and jack it out there. Due to this feature request being a rather huge and new one, we will want to simplify it as much as possible upon creation

Each APC zone will have only one type of virus for simplicity, until the gameplay is made balanced more, here are suggestions. ALL damage types will be burn, and navis would be given pain immunity to prevent burn stunlock. You will also get a default buster shot to use for when you don't have any chips until the 10 seconds pass where you can roll for more chips

Kitchen viruses are stoves that shoot fire at you in a straight line for a few seconds, this would not actually put you on fire but just deal burn damage. Defeating them gives a similar chip.

Botany viruses would use a homing vine attack to track you such as plantman from mmbn3. Wears off after about 10 seconds, chip does the same thing. Vines when hit will wrap your target, but not do damage or minor damage, allowing you to get in combos on your opponent. https://youtu.be/G2qK1ZH71uQ?t=22s

Bartender viruses try to spray booze at you with a slim cone type shape, if hit you will get the confusion status for a short while and be unable to control your movement, while you will still be able to dodge most things by just spamming direction buttons running wildly. Same results if you use said chip.

Medical viruses will be somewhat annoying, they heal themselves at low hp and try to dodge their attacks, the best way to fight them will be to kill them fast. The chip they provide is a heal chip, which can be used in battle to recover an amount of burn damage.

Virology viruses will shoot sneezes at you, if you get hit by the mucus, your HP will slowly tick down until you use a recovery chip to cure your virus. The chip you get from them will do the same effect (and thus not very effective against medical viruses)

Engineering viruses would allow you to shoot a line of stunning lightning, not as long as the plant stun, but since it's a straight lightning bolt shot, it would be harder to dodge. The virus does the same to you as the chip does.

Security viruses would give you one shot laser projectiles that only go in a straight line, this is just a basic damage chip and the virus would do the same when attacking you.

Cargo viruses attack you by shooting random junk through disposals at the back of their turf, however if the junk hits the cargo virus by them getting in the way, they get healed by the junk since they control disposals and are a trash-like virus. The chip you obtain by cargo viruses allow you to have an option of 2 more chips upon next chip selection during the rest of battle.

Miner viruses spawn boulders in front of them, then punch them towards you to do damage. The boulders act as meat shields, but are possible to break with enough damage. The chip they provide is boulder spawn, which spawns a boulder in front of you as a shield, but you do not get to punch it.

Atmos viruses wil use ZAS against you. They will fire visible gust of wind projectiles in the random 3 rows you are in and you must dodge them, or you will be slammed to the back and take your burn damage. The chip you get from this is airshot, which allows you to blow away any aura/shields your opponents have, and you can use it on rocks you or you're opponent created to launch the rocks at them chucking the boulder for massive damage

RnD viruses just shoot basic buster shots at you, like you do, however every now and then they upgrade so their shots are faster, or do more damage. The chip you recieve from them will allow you to upgrade randomly do more damage per buster shot, charge your shots faster for charged shots, or shoot them faster for rapid shots.

Toxins virus will lob bombs at you, the chip is pretty much the same, a bomb lob that does a good amount of damage.

Xenobio viruses will be slimes that randomly hop around their side of the field, and after every maybe 5 hops, they do 1 hop on where you were last standing that you need to dodge. Despite being slimes, they still only do burn damage. Using the chip for yourself allows you to summon said slime on your side, but it will hop a lot slower as your ally.

Robotics viruses will have you fighting bulky mechs that shoot projectiles at you. Once defeated you get a chip that turns you into a navi/mech fusion whos buster shot is enhanced to be maxed and you take half damage. However next turn after using this chip, you will not be able to select chips that turn as you are in fatigue/cooldown from using said chip.

Genetics viruses will be strange DNA humanoid blob like creatures that float around the field and randomly charge at you to drain your life. Once defeated, you get a bug style chip, giving you a random boost or bug, such as a shield, your life draining until you recover, confused movement, instarecover, max RnD style. Pretty much a random grab bag that can hurt or help you a lot.

Theater APC, however will have two viruses. clown and mime found separately. These viruses are intended to be annoying, clowns will throw banana pies slipping you, lob banana peels on your field that you cannot pick up, and will slip you once before disappearing after. They have no damaging abilities, just being a nuisance. Mime viruses will randomly spawn invisible walls on your field and turn invisible themselves. Due to the annoying factor of these two NPCs, their chips are a bit of a bother to get but will be worth it possibly. Mime chip allows you to summon invisible walls randomly on your opponents side of the field, and the clown chip will allow you to lob a one slip banana on your opponents side of the field.

Courtroom APC will have a judge virus there who will throw space law books at you and then eventually dash up to you, even on your side of the field, to try to hit you with a giant hammer, which you must side step to avoid. The hammer will do a lot of damage and so will the chip.

IIA office lets you fight lawyer viruses there, who spawn with regenerating barriers you have to break before you can even damage them. Once defeated, you get a barrier of your own, which sadly does not regen. Barriers can also be blown off by the atmos wind chips keep in mind.

Chapel viruses will contain two viruses in one battle always, two holy relics which heal each other per tick, just as the virus chip harms per tick. They will occasionally spawn a beam of light above you to dodge which will smite you otherwise. This will be a difficult battle, but with all the chip possibilities currently I'm sure you can find a way to out DPS their heals. The chip they provide spawns one holy relic on your side of the field that heals you, and if you are at full health, heals itself, and occasionally tries to smite your enemy. 

Library virus will be a wizard who uses spellbooks to shoot various spells at you, such as basic fireballs (not the real wizard version that fucks everything), homing magic missiles (a clone of the vine spell), the wizard will also be able to teleport around, The book may shoot a gust of wind at you, but unlike the atmos ZAS virus, this just removes barriers, and lastly the book can shoot a bolt of stunning lightning in a straight line at you (same as engineer). The chip will summon a book  on the front of the field that will cast a few a spell before changing to one of the next spells. Since the book stays on the front row copying your position, a few good fire chips or even the judgement hammer can easily destroy it.

If you feel like you can add an unmentioned area such as the morgue, gateway, teleporter room, ect, post how you think it could fit in.

---

Discuss how this feature would affect pAIs and make the role more enjoyable for them so more people are willing to play it, rather than the pAI just being a different version of a MMI in your pocket.

**Comment by Praecordia** [comment]
impossible to code desu

**Comment by Killette2** [comment]
Why? We can just copy most things from the code and resprite them. Fire would be a longer lasting laser beam, homing plant vines would be similar to goliath tentacles, and most of these abilites are straight line shots only. Which in particular do you think would be impossible?

**Comment by Intigracy** [comment]
When you code it.

**Comment by aceedex** [comment]
Id hate to play MMBN with byond latency

But more pAI stuff is good

**Comment by NigglyWiggly** [comment]
I'll sprite any megaman shit anyone needs.

That said this seems really unlikely to ever become a real thing

**Comment by Boxe** [comment]
dude what

**Comment by Intigracy** [comment]
Just another feature request that'll sit on the issues tracker for months/years from our local idea guy.

**Comment by Imagebard** [comment]
I want whatever killette's having.

**Comment by Tokanova** [comment]
Do It. If you want it, code it. You already had someone offer to sprite things, contact them. Do it. Everyone would enjoy it. The people that'll post negatively here are at the end of the day, likely a minority.

**Comment by Killette2** [comment]
Niggly you could sprite virus icons however you'd like. That said this would be a big project I'd imagine and would need to be done step by step, for instance the ability for pAIs to go into APCs in the first place then travel through wires. Random encounters added after that system is found to be working.

**Comment by NigglyWiggly** [comment]
This would give me an excuse to finally sprite mettaurs.
That or I could just use it as an excuse to use my megaman legends reaverbot sprites

**Comment by Killette2** [comment]
The idea was also where you would find the themed viruses in the APCs themselves, not the wires, but I guess generic viruses that have nothing to do with anything such as mettaurs be found in wires or jacking into special places, like vending machines. This is still a big idea so it would probably be best if we decide to even do it, to do it a step at a time

**Comment by Tokanova** [comment]
So we do this, and what happens?
What benefits would there be to jacking into APC's and shit and beating viruses?
Unless the Viruses are detrimental to the station? Are they? Will the viruses do shit like turn off power randomly, making pAI Virus Busters a necessity?

**Comment by Intigracy** [comment]
And if that's true, what are lowpop rounds supposed to do when there's no pAIs?

**Comment by Killette2** [comment]
Viruses drop zenny (money) and battle chips, which are used for battling viruses and other players. You can find NPCs in some areas that will sell you more health, more memory to download more and even NEW things on your pAI, and is generally a fun feature for players. The only tweak that will need to be done is to figure out what happens when it's milf mode, but the only closest thing we have is spesspets for your PDA, which nobody will want to play with you.

**Comment by Killette2** [comment]
@Intigracy 

Ask for one from RnD, if the pop is that low, steal the one from RnD office. That's the same situation with borers, golems, and nymphs. If it's lowpop unless someone murderboners, there's not even a lot of observers to become one.

**Comment by Tokanova** [comment]
Well. That'd be interesting.
Milf round, if the AI shunts to an APC, you can jack in and have your pAI fight the AI and if they win, APC DESTROY LETS GO HOME?

**Comment by Killette2** [comment]
That would be cool, but we'd need to do something so the pAIs can't detect hacked APCs somehow.

**Comment by Intigracy** [comment]
I meant if it's low enough pop you're not going to get a pAI.

In reply to
>Unless the Viruses are detrimental to the station? Are they? Will the viruses do shit like turn off power randomly, making pAI Virus Busters a necessity?

**Comment by Killette2** [comment]
Maybe you can jack into vending machines to fix the firing wire once the brand intelligence comes on rather than hacking it?

**Comment by optimumtact** [comment]
@Intigracy if you don't like the idea you can just not post instead of trying to tear other people down because you were bullied as a small child

**Comment by NigglyWiggly** [comment]
@optimumtact I feel like you really underestimate the number of random ideas that Killette suggests without any actual code or anything to back them up.

Besides, what did he even do to 'tear him down?' he just told him to code it himself and then asked a question

**Comment by Killette2** [comment]
> Number of le random ideas
> 2 pages of issues
> Some which are balance discussions or bug reports

OOC doesn't count

**Comment by Intigracy** [comment]
Just a bit more and you are 1/10 of the feature requests.

![2016-04-10_18-50-59](https://cloud.githubusercontent.com/assets/4043940/14414849/54e7a544-ff4d-11e5-88f0-7319acb81263.png)

![2016-04-10_18-51-09](https://cloud.githubusercontent.com/assets/4043940/14414850/5711d2a4-ff4d-11e5-8828-ba4d23830277.png)

**Comment by Killette2** [comment]
1/12.7 thank you very much

**Comment by Intigracy** [comment]
```
>just a bit more and you are
```

**Comment by Killette2** [comment]
> > trying to say 1/12 is even close to 1/10

I take it you've never shared a large or family sized pizza?

**Comment by Imagebard** [comment]
I take it that you like straws?
Because that's a very tiny one you're grasping at.
