### ISSUE TITLE
Station holomap, a way to make fixing explosions easier.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9299]
As it stands, fixing damage from explosions can be a bit of a pain. You'll have to look at the _outdated_ map renderer, and most of the time people don't give enough of a damn.

So I propose an item (maybe also PDA application) which, when activated, shows you "ghosts" of how the station's piping, cables and maybe other things were at roundstart, much like the T-ray scanner (or even implement it INTO the T-ray), except it would be longer lasting.

**Comment by ihadtoregisterforthis** [comment]
Would someone think about the silicons?

**Comment by PJB3005** [comment]
If I would code it I would certainly give it to engineering borgs and MoMMIs.

**Comment by FudgePucker** [comment]
@ihadtoregisterforthis Why are you playing MoMMI if you can't remember the entire map and its pipe network?

2autistic4u

**Comment by Killette2** [comment]
As this is a good idea, there is a glaring flaw in my opinion. Let's say you are an antagonist, and you want to redesign the map in your favor, such as changing disposal chute routes, or gas pipes to lead to a burn/freeze chamber? Normally someone might think something's odd but will think nothing of it, but if they have a way to double check they can alert that someone's been altering the layout of the station, investigate, and your sneaky efforts will be for nothing.

Also why would the syndicate want the blueprints (which doesn't even show the layout of the station, it's just for renaming rooms), when they could get a holomap instead? Blueprints are a bad greentext objective as it promotes the CE of hoarding them and is a hurdle for space forts being built.

**Comment by PJB3005** [comment]
@Killette2 your first point is definitely a concern.

Maybe a way to screw with the holomap?

**Comment by PJB3005** [comment]
Could do a 1 TC traitor item to modify the holomap of an area.

**Comment by Shadowmech88** [comment]
Whatever item you attach the ability to, you could have a traitor version of the item that, in addition to being a holomap, can also change the holomap of your screen area to update it to the current pipes/wires.

**Comment by PJB3005** [comment]
Yeah, sounds good.

I know it doesn't make a lot of sense but making it accessible by emagging a holomap sounds like a good way too.

Then again emag powercreep.

**Comment by Exxion** [comment]
You could also have the holomap require being wrenched down or something and only working in a certain range, so people couldn't just carry them around constantly and see all changes to the station that they pass by

**Comment by FudgePucker** [comment]
What about that fancy goonstation autoconstruction tool that can create rooms from blueprints?

What if you could drag a machine to an area, wrench it down, put in metal plasteel and ref glass into it and it would remake the area fixing the damage automatically?

**Comment by Probe1** [comment]
Not everyone is as good as me and even I pull up the map when doing big rebuilds on not-box. There should be something for people.

**Comment by FudgePucker** [comment]
I mean really, a machine that slowly rebuilds areas would increase the number of times that an area is fixed.

Okay lets say a bomb goes off, you go over to the hull breach, and start the slow task of repairing it.

You have to do very tedious work to replace the floors the walls and the windows, just for the shuttle to get called halfway though.

This machine just means that you feed it mats and let it do its work for large areas, for smaller damage like welderbombs and broken windows you would still do by hand, you don't want to drag a machine to do a small breach, but in the case of an entire area being blown up it would be worth it.

**Comment by Killette2** [comment]
Or we could fix the fucking floortile bot, which malfunctions more than farmbots and that's saying a lot. When did floorbots become so broken and useless?

**Comment by PJB3005** [comment]
@Killette2 in my experience the missing tiles is the least bad part of fixing an explosion.

**Comment by clusterfack** [comment]
When kurfurst touched them
