### ISSUE TITLE
Make plasmacutters worth a damn.

### ISSUE THREAD

**Issue by liltiptop** [d3athrow/vgstation13#9303]
So this is basically a discussion about the plasma cutter. It's current use is mining and breaking walls, that's about everything it does. It's immediately replaced by the diamond mining drill by miners, and only sees the light of day in a combat borg's modules. I've heard some discussion on what to do with it, and i'll share some ideas:
1. Make the plasma cutter fire ionized plasma by loading it with plasma sheets, 10 max. 
2. Make the plasma cutter act like a very high cap welder tool, fueling it with plasma.
3. Keep the plasma cutter the same way it is / remove it completely from the game.

I personally like a mix between 1 and 2, maybe give an advanced version to the CE to start with. Anyway, what do you think the plasma cutter's fate should be?

**Comment by Manaony** [comment]
I'm voting for 3

**Comment by Probe1** [comment]
Do you fucking mind github? http://i.imgur.com/bB1kLYm.gifv

NUMBER TWO IS A NATURAL WAY TO IMPROVE THEM.

**Comment by liltiptop** [comment]
The welder idea seems better suited, I agree. Should we have "plasma cartridges" or grinded plasma, or something loading it, or just jam in sheets of plasma?
I only ask because the sheets are ridiculously XBOX HUEG compaired to the cutter's sprite.

**Comment by Probe1** [comment]
fuck just have plasma sheets directly added why complicate things

**Comment by 9600bauds** [comment]
It needs to cut limbs

**Comment by AutismSpider** [comment]
just give it the power to cut down Rwalls real damn fast+normal welder tool uses (- the part about fixing robot limbs and shit)

**Comment by Intigracy** [comment]
Yeah having it as a plasma sheet loaded welder sounds great.

**Comment by CptWad** [comment]
Just increase its sharpness
make it more like the videogame its based on, allowing limb severing

**Comment by Kitfox88** [comment]
RWall murder + a pretty sharp melee weapon sounds fine to me. Make it require plasma sheets for fuel if that sounds unbalanced.

**Comment by CptWad** [comment]
yeah thats fair
plasma as fuel and can ruinate walls and people
