### ISSUE TITLE
Disassembling subverted APCs didn't increase the malf countdown timer

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9305]
#### Description of issue

When blue apcs are disassembled you are given time back on the clock.  This did not occur.
#### Difference between expected and actual behavior

Take apart apc -> get more time.  I took apart two while watching the timer and nothing happened.
#### Steps to reproduce

Game-Panel Mode Malfunction hack a few apcs, go delta, become a test dummy and disassemble the apcs
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Allspice** [comment]
#8526 
Probably been around 'a good while.'

**Comment by Probe1** [comment]
Thank you.
