### ISSUE TITLE
Wood Tables are now invisible

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#9306]
#### Description of issue

Wood tables are invisible

#### Difference between expected and actual behavior

They should not be

#### Steps to reproduce 

look at a wooden table

#### Specific information for locating

#9288 

#### Length of time in which bug has been known to occur

just recently

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by BestName** [comment]
I may know what's causing this and might open a pr soon after I'm done testing.
