### ISSUE TITLE
Wizard mindswap issue

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9307]
(WEB REPORT BY: lamberts REMOTE: 172.93.109.202:7777)

> Revision fffc83d361679b7c31ae4f3cd19e796fc4769a92 
> 
> General description of the issue
> When mindswapped, my first body was used as the location for spells such as mindswap and jaunt.
> 
> What you expected to happen
> To be able to mindswap into bodies adjacent to me current body, and for jaunt to teleport me to somewhere within 10 squares of where it was.
> 
> What actually happened
> I mindswapped into bodies adjacent or the first body itself. When I jaunted I always ended up withing 10 squares of the first body.
> 
> Steps to reproduce if possible
> I took mindswap, then clothless casting, then junt and magic missile, if the cobination/order matters. I then mindswapped with someone, ran halfway accross the station, and hit mindswap again whilst the first body wasn't next to anyone. This returned me to the first body.

**Comment by Blithering** [comment]
I was one of the people mindswapped into during this round, And also got a copy of the spell UI he had. I was able to cast them as if I were a wizard, and doing so would put both of our spells on cooldown. Very buggy.
