### ISSUE TITLE
Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9312]
Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead
#### Description of issue

Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead
#### Difference between expected and actual behavior

Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead
#### Steps to reproduce

Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead
#### Specific information for locating

Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead
#### Length of time in which bug has been known to occur

<Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead!--
    Be specific if you approximately know the time its been occurring
    for—this can speed up finding the source. If you're not sure
    about it, tell us too!
-->
#### Server revision

<!-- Found with the "Show server revision" verb in the OOC tab in game. --Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead>Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead
#### Issue Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor insteadatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

<!-- Check these by writing an x inside the [ ] (like this: [Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead
- [ Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead] Issue could be reproduced at least once
- [ ] Issue cStormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor insteadould be reproduced by different players
- [ ] Issue could Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor insteadbe reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](Stormtrooper armor doesn't have unique inhand sprites, looks like regular sec armor instead)

**Comment by gbasood** [comment]
> issue template comment blocks are bugging out

w e w

**Comment by 9600bauds** [comment]
they're not I just clicked randomly and pressed ctrl+v

**Comment by Intigracy** [comment]
smh bauds quit making meme issues you shitter

**Comment by 9600bauds** [comment]
this is a real issue with only mild social commentary on the issue reporting template

**Comment by clusterfack** [comment]
If you think its bad fix it you shitter it's OPEN SOURCE

**Comment by 9600bauds** [comment]
I never said it was bad ;)

**Comment by 9600bauds** [comment]
Also I can code mediocrely but I can't sprite to save my life

**Comment by Intigracy** [comment]
I can do anything, git gud.

**Comment by Blithering** [comment]
I must confess I absolutely hate making inhand sprites. There's one for the helmet at least.
http://s000.tinyupload.com/index.php?file_id=33611962951220487457

**Comment by ghost** [comment]
No one likes making inhand sprites.

**Comment by SkowronX** [comment]
I do!

**Comment by gbasood** [comment]
he said, and 3 months later it's still an issue

**Comment by Blithering** [comment]
Stormtrooper armour was removed from everything but bus station, which was then removed from rotation. Less of a priority issue at present.
