### ISSUE TITLE
Post your ideas for the Metaclub Research Outpost, Vox Trade Post, and Derelict

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9316]
Research Outpost and Derelict are both copy/paste from Box.

The Vox Trade Post is entirely destroyed.

You guys fucking love ideas so please, give me ideas and if they are good and liked then I will map them.

The mining outpost is copypaste too but I feel like it's such a non-destination that people just get in and out of that it shouldn't be a priority.  BUT IF YOU HAVE IDEAS POST THOSE ANYWAYS.

**Comment by ihadtoregisterforthis** [comment]
Make the vox outpost on a different z level than the asteroid

**Comment by Probe1** [comment]
@ihadtoregisterforthis which, and how would the crew reach it?

**Comment by Probe1** [comment]
via thread

> have it more embedded in the roid, with the large artifact testing areas deepest in

**Comment by ihadtoregisterforthis** [comment]
¯_:bird:_/¯ the idea is to reduce _meta_ and diversify. Why does the crew need to go to an almost forgotten outpost?
This would also push raiders to actually steal from the station instead of mining for a good chunk of their round.

**Comment by Probe1** [comment]
the old joke is vox raiders having to mine their own because there were no miners.

**Comment by Probe1** [comment]
> Ririchiyo_: why not have the vox trade post handled like another medical laboratory
> Ririchiyo_> but it's setup to handle every single race
> Ririchiyo_> pretty sure that'd also fit with their backstory.
> Tokanova> vox trade post with vox creator stuff. big meat vats that vox emerge from or something like that
> Tokanova> woah that holomap idea is excellent
> Tokanova> hilariously i think i commented last night 'if only there was a way to see what the station is supposed to look like' after a librarian dice bombed the station

**Comment by Killette2** [comment]
Remove vox?

**Comment by gbasood** [comment]
@Probe1 except for the part where that's actually happened of course

As to the OP: We have no actual reason to keep vox trading post on mining asteroid besides player interaction, both of Meta and elsewhere. We could replace this with a shuttle, however, and an off-station trade satellite sort of thing. Not sure that it matters a whole lot either way, they'd both suffer from the same problems.

**Comment by Probe1** [comment]
Okay that works for me.  We can take Ririchiyos idea and yours and combine them with the existing destroyed Vox Outpost.  

Add a shuttle from the xeno infested vox outpost on the roid to z6 which is just barren except the salvage shuttle

![image](https://cloud.githubusercontent.com/assets/8550416/14373564/5d1e4f28-fd19-11e5-93cd-b729160e97e8.png)

Put a medical lab there where Vox were genetically modified.  Have some sections with skellingtons and plasman remains from genetic modification.  Maybe if I'm feeling up to it some notes and stories.  Possibly some viro related items.

Seems good to me.

**Comment by Probe1** [comment]
Work so far on vox medical lab

![dreammaker_2016-04-08_14-58-33](https://cloud.githubusercontent.com/assets/8550416/14394631/3208e9b0-fd9b-11e5-9d40-48a5d7497373.png)

**Comment by Probe1** [comment]
Current WIP

![dreammaker_2016-04-08_16-51-25](https://cloud.githubusercontent.com/assets/8550416/14397315/acb40a50-fdaa-11e5-9ec6-2523aee010f9.png)

**Comment by Brolaire** [comment]
Maybe in that same area or maybe nearby have an small seperated room with 3x3 pens with diffferent Lifeforms as a sort-of test subject containment area. There could be one with human remains in it, another one with a a proboscis-less facehugger with an empty egg, and a spider-pen and some cocoons for example.
think of its layout like a warehouse and less like a lab

**Comment by Kammerjunk** [comment]
I assume the vox outpost changes are for the Trader update? Will it replace the current xeno-infested one or will it be a new structure?

**Comment by Brolaire** [comment]
Also maybe move the destroyed Vox Outpost (if the new one isnt gonna replace it obv) a few tiles to the east/north, this way I personally think it's way too close to the research outpost. I'm not sure if this is intended but you can SEE it from inside of the research outpost when you go to the far east end of it.

**Comment by Probe1** [comment]
@Kammerjunk both, vox raiders lack any kind of 'base' like on Box.  The existing xeno infested tradepost on the roid will remain but a shuttle will be there to transit to this.

@Brolaire I'll keep the location of the roid post in mind but the research outpost itself needs to become unique so its location may change as well.  The only suggestion so far is to embed it inside the asteroid itself.

A warehouse will work equally well as a lab but I'm 3 hours into the lab and I'd love to have someone say which is the better idea.

**Comment by Probe1** [comment]
And we can always use the warehouse idea on Deff in the future seeing as its tradepost is a copy paste.

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/14404662/33209848-fe4a-11e5-9ae4-a78200bfd20e.png)

**Comment by Brolaire** [comment]
i think cryosleep chambers would be a neat idea instead of beds. just put sleepers without the console or cryocells where the beds are and relabel them

**Comment by Probe1** [comment]
![image](https://cloud.githubusercontent.com/assets/8550416/14404788/b09df048-fe4c-11e5-877e-bc3cf1aa8395.png)

**Comment by Probe1** [comment]
@Brolaire I'd add that but someone needs to fix them spawning with sleeper consoles as well.  See https://github.com/d3athrow/vgstation13/issues/4796

**Comment by Probe1** [comment]
![dreammaker_2016-04-09_12-46-33](https://cloud.githubusercontent.com/assets/8550416/14404958/6142b0c4-fe51-11e5-89a4-e25a4bf83cb7.png)

**Comment by Probe1** [comment]
![dreammaker_2016-04-09_12-50-06](https://cloud.githubusercontent.com/assets/8550416/14404973/ba852130-fe51-11e5-9716-f5f11aabdb27.png)

**Comment by Brolaire** [comment]
Small Botany/Kitchen area where they grew food or something? door could be on the opposite side of the makeshift docking.

**Comment by Probe1** [comment]
I put it in the top right area but you're right, good call.

**Comment by Probe1** [comment]
Just a few more additions then I'll clean it up and add lights, unique areas, and the shuttle.

![dreammaker_2016-04-09_13-39-49](https://cloud.githubusercontent.com/assets/8550416/14405255/c980adba-fe58-11e5-89d4-4083636500f2.png)

**Comment by Brolaire** [comment]
i would put something into the empty room, like one or two sectech vendors or anything to make its still IMMERSIVE that this used to be a room that was in daily use before it exploded. besides that i dont want to add anything else to this, i like the layout and what we have so far

**Comment by Probe1** [comment]
You mean the destroyed room right?

**Comment by Brolaire** [comment]
yeah the destroyed one, sorry shoulda made it more clear

**Comment by Probe1** [comment]
Good plan.
note: make a subtype with less/0 quantities of some things.

**Comment by Probe1** [comment]
Adding a secvend subtype

```

/obj/machinery/vending/security/used
    req_access_txt = 0
    extended_inventory = 1
    products = list(
        /obj/item/weapon/handcuffs = 1,
        /obj/item/weapon/grenade/flashbang = 1,
        /obj/item/device/flash = 2,
        /obj/item/weapon/reagent_containers/food/snacks/donut/normal = 24,
        /obj/item/weapon/storage/box/evidence = 1,
        /obj/item/weapon/legcuffs/bolas = 2,
        )
    contraband = list(
        /obj/item/clothing/glasses/sunglasses = 2,
        /obj/item/weapon/storage/fancy/donut_box = 2,
        )

```

Its contraband is auto unlocked.  It was way less "security" type things and way more donuts.

**Comment by gbasood** [comment]
@Probe1 Do we still need this open
