### ISSUE TITLE
Doesn't display eyewear under flipped-up gasmask

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9319]
(WEB REPORT BY: senaat1 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
>  2493c00181a4a9d18667ce8bd8a83a01717b5db3 
> 
> General description of the issue
> If you flip up a gasmask, your glasses don't show
> 
> What you expected to happen

For my sprite to show glasses

> What actually happened

No glasses anywhere in sight

> Steps to reproduce if possible

Put on glasses
Put on gasmask
Click on the gasmask icon in the upper left hand corner
Look at eyes
Cry

**Comment by Killette2** [comment]
How do you look at your own eyes? You mentioned nothing about a mirror this impost, even then it's not even implied.

**Comment by gbasood** [comment]
Literally talking about the icon on his mob for eyewear not showing.
