### ISSUE TITLE
Blink no longer teleports you to areas you cannot see yet are in range

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#9324]
As of now blink only moves you to places that are visible. This spell used to be great for getting into places with patience or hoping you would blink to a room that you couldn't be chased into. I had Boxed test this further and he brought up that the area also needs light to be eligible to blink to. So if you use this in maint you're fucked.

**Comment by CptWad** [comment]
I noticed that too

**Comment by Intigracy** [comment]
Blink working through walls was one of the major selling points of the spell.

Darn.
