### ISSUE TITLE
PDA issue with AI's

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#9326]
We've been having some issues with AI's not being alerted when they get PDA messages, this has caused some pretty rough stuff for us and even caused a wrongful bannu.

**Comment by Intigracy** [comment]
#9230 related

@PJB3005

**Comment by Probe1** [comment]
I had an AI ignore me recently until I yelled at it over comms.  That would explain why it didn't respond to my PDA messages.  

The AI in question was an admin so I was at maximum eye roll about getting ignored.

**Comment by Intigracy** [comment]
This is a dupe of #9367 which has more specifics, please close.
