### ISSUE TITLE
Pretencious Mime Painting

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9328]
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 2493c00181a4a9d18667ce8bd8a83a01717b5db3
> 
> General description of the issue
> Typos.
> 
> What you expected to happen
> Pretentious Mime Painting
> There are no words to describe this painting.
> 
> What actually happened
> Pretencious Mime Painting
> There are no words to discribe this painting.

**Comment by Shadowmech88** [comment]
The offending lines are 250 and 251 of `paintings.dm`.

**Comment by ihadtoregisterforthis** [comment]
What, again?

**Comment by Shadowmech88** [comment]
@Intigracy corrected the title and description of the `/obj/item/mounted/frame/painting`, but not of the `/obj/structure/painting`.
