### ISSUE TITLE
Cloner allows you to scan yourself

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9330]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
To recreate this you have to just bring up the window, enter the scanner, go to records, return, then press scan and you're able to scan yourself.
It isn't neccisarily something round breaking, or really negative. I just figured to report it.

**Comment by Probe1** [comment]
thats funny, I just tested the DNA scanner yesterday to see if you could with the genetics console (you couldn't)

**Comment by Allspice** [comment]
Cloning backup in the cloner scanner, pop in a disk, go to Records->YourName, save your SE, pop out disk, put in the DNA modifier console, save From Disk to any buffer. Now you too can hand out your powers and definitely not your UIUE.

**Comment by Exxion** [comment]
@clusterfack I thought you fixed this

**Comment by clusterfack** [comment]
? I don't recall that

**Comment by Exxion** [comment]
Well, a less-involved version of it
Where `in_range()` used pure distance instead of `Adjacent()`

**Comment by Probe1** [comment]
Rest in peace best genetics trick 20??-2016

**Comment by Shadowmech88** [comment]
Could re-add the capability as a high-tier upgrade to the cloning pod, maybe.

**Comment by Probe1** [comment]
Energy better spent redoing genetics to be better all around.  And it was an anti social trick that let you scan yourself and back up your DNA without having to bother anyone else in medbay.  It really didn't help the game it just helped the player.

Naturally I used it every time I played.  It was shit for the game overall though.
