### ISSUE TITLE
Left clicking doesn't work when setting occupation preferences

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#9337]
#### Description of issue

Someone added a right clicking feature to cycle your preference backwards and must have broke the left clicking functionality to go forwards. Right now setting your jobs is hard.
#### Server revision

2493c00181a4a9d18667ce8bd8a83a01717b5db3
#### Issue bingo
- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players (Yred confirmed it ooc but any of you should be able to confirm this quickly)
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (I swear I checked)

**Comment by Exxion** [comment]
This happens for some people but not others
#8315

**Comment by Konater** [comment]
Oh god damn it there was another issue
