### ISSUE TITLE
Vials not being Labeled Vials

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9341]
(WEB REPORT BY: pinkacolada REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I can't label my vials for maximum work notes
> 
> What you expected to happen
> The vial to be labeled
> 
> What actually happened
> It didn't
> 
> Steps to reproduce if possible
> Take a vial, take a labeler, use the labeler to not it does not work and when it says use a pen instead, use a pen to label it, the pen does nothing either.

**Comment by Probe1** [comment]
It formerly worked but now NO beakers can be labeled (vials are a child of beakers).

**Comment by Probe1** [comment]
```

/obj/item/weapon/reagent_containers/glass/attackby(obj/item/weapon/W as obj, mob/user as mob)
    if(istype(W, /obj/item/weapon/pen) || istype(W, /obj/item/device/flashlight/pen))
        var/tmp_label = sanitize(input(user, "Enter a label for [src.name]","Label",src.label_text))
        if (!Adjacent(user) || user.stat) return
        if(length(tmp_label) > 10)
            to_chat(user, "<span class='warning'>The label can be at most 10 characters long.</span>")
        else
            to_chat(user, "<span class='notice'>You set the label to \"[tmp_label]\".</span>")
            src.label_text = tmp_label
            src.update_name_label()

```

kek @ writing with a penlight.

**Comment by Exxion** [comment]
> It formerly worked

If that's true, it must have been a long time ago, because the check preventing you from labeling beakers was there before my labeler changes

**Comment by Probe1** [comment]
Good question but I used to always label my cryo beakers.
