### ISSUE TITLE
Strange roach bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9342]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
http://puu.sh/obATp/1a91dcbe8c.png
Somehow the roaches are able to teleport through the walls and reach space. Not sure how you can reproduce this aside from overfilling a small room with roaches.

**Comment by CptWad** [comment]
didnt I already report this

**Comment by CptWad** [comment]
#7830

**Comment by ihadtoregisterforthis** [comment]
Roaches are one of the best pieces of content added

**Comment by 9600bauds** [comment]
fantastic

**Comment by 9600bauds** [comment]
Closing in favor of #7830
