### ISSUE TITLE
Eggs don't hatch

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9343]
**(WEB REPORT BY: intigracy REMOTE: `172.93.109.202:7777`)**
#### Revision (Should be above if you're viewing this from ingame!)

6391c2890a249b2e58d3f65cd982dc2d855c7d56 
#### General description of the issue

Eggs lain by chickens do not hatch into chickens
#### What you expected to happen

The eggs I got to hatch
#### What actually happened

They sat there. And sat there.
#### Steps to reproduce if possible
1. Feed chicken wheat
2. Look at eggs it lays
3. Keep looking at eggs
4. Look at eggs for even more time

**Comment by Intigracy** [comment]
I shoulda put the title as chicken eggs, my bad.

**Comment by gbasood** [comment]
Worked fine a few days ago
They take a long, long time.

**Comment by AutismSpider** [comment]
yell at Sci or the plastic monkeys to build you that thing to hatch them faster or buy one at cargo
