### ISSUE TITLE
Remove Kamina stuff from being littered around maintenance

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9349]
When people use this as an excuse to add other awful items to the game you know it has to go.

**Comment by BestName** [comment]
Is that really a thing that happens?

**Comment by Arthurdentist** [comment]
yeah have you got an example of this happening?

**Comment by ghost** [comment]
![carsh](https://cloud.githubusercontent.com/assets/7193289/14413464/ceb8642e-ff72-11e5-9a80-cfc429e4c306.png)

**Comment by AutismSpider** [comment]
Some shit rei added ages ago look at the huge drill you can find via xenoarc

**Comment by ghost** [comment]
As @Probe1 stated in #9315 

> I'm fine with references. The whole game is a reference to something or other. But when it's too obvious it lowers the quality of the game.

**Comment by 9600bauds** [comment]
Last I checked these are entombed inside and behind walls, no?
Unlike shit like the owl mask

**Comment by Probe1** [comment]
I think this might be a bit misguided.  The problem is with the jojo spirit-totally-not-cheap-DnD-ripoff strands stuff right?

Cause I don't want that either.

**Comment by ghost** [comment]
I'm FINE with the kamina clothes being in the game
I'm NOT FINE with them being named "kamina glasses" or being littered around maintenance - they should be in the clown's autodrobe instead.

**Comment by Probe1** [comment]
Sure, rename it and switch out the maint loot.  It's been stale for far too long anyway.

**Comment by Arthurdentist** [comment]
This is as pointless as it gets. I still don't see anything wrong with it.

**Comment by Gringonius** [comment]
I'm fine with removing it from maint BUT it should be moved to the theater costume vendor.

**Comment by ghost** [comment]
Think of it this way: if someone today made a PR adding them to maintenance, would you :+1: it? It's only because it's been added ages ago that it remains now; it sticks out like a sore thumb, as much as if not more so than the stormtrooper stuff or the monkey room in maintenance.

**Comment by icantthinkofanameritenow** [comment]
@DrCelt 
He does have a point. Most of the memes they're referencing have grown so stale I'm surprised half of our people even understand them.

**Comment by 9600bauds** [comment]
They're not even just "in maintenance", they're completely hidden

**Comment by ihadtoregisterforthis** [comment]
@DrCelt put the link to an archive with the comment on the thread instead, it won't last much longer.
