### ISSUE TITLE
Firelocks take in account air behind adjacent windows.

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#9359]
This a huge bother because when air leaks from the station any firelock standing next to a grille with glass windows will forbid people from opening it because the air inside the windows will still be at the pressure of 101 kPA, unless the windows get broken of course.
Medbay in particular suffers the most from it, you can pop out of a sleeper with exploding lungs and rising brute damage while you'll be unable to leave medbay despite the hallway behind the firelock having the same pressure as where you stand because of the air inside the glass.

I'm surprised this still wasn't a registered issue before, I think it's about time it should be adressed so they ignore the pressure in those tiles separated by directional windows.

**Comment by 9600bauds** [comment]
So THAT'S what it is

**Comment by 9600bauds** [comment]
Airflow counts as flow

**Comment by Imagebard** [comment]
Are you meming me bauds

**Comment by PJB3005** [comment]
Yes

**Comment by 9600bauds** [comment]
![mspaint_2016-05-05_00-05-47](https://cloud.githubusercontent.com/assets/6526157/15036127/309ac5b4-1261-11e6-97f7-757f9c3cc22e.png)
Picture of this in action
