### ISSUE TITLE
Cryokenisis does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9364]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
I click the power and nothing happens.

**Comment by Probe1** [comment]
The only way I could reproduce this is by being totally by myself with no one to be the target.  Suggested fix:  Add a line that says there are no targets.

![dreamseeker_2016-04-10_09-18-00](https://cloud.githubusercontent.com/assets/8550416/14410419/27cd1db4-fefd-11e5-9b76-60a8b45523ec.png)

**Comment by SGuivenne** [comment]
Is this bug still a thing?  Pretty sure this has since been worked on.
