### ISSUE TITLE
Hulk does not increase damage

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9365]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
I was playing as a rev and found a braindead HoP.
I started punching him as a Hulk and I hulked out three times punching him hard non-stop each time.
It did not increase damage and I had to finish him off with a knife.

**Comment by Shadowmech88** [comment]
Are you sure? Hulk punches are only five more damage than regular punches, it's not a whole lot to start with.

**Comment by 9600bauds** [comment]
Could be the same deal as https://github.com/d3athrow/vgstation13/issues/7092

**Comment by Shadowmech88** [comment]
Just tested. A regular punch did 2 damage to a monkeyman, a hulk punch did 10 damage.
