### ISSUE TITLE
Golems seem to be broken

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9366]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
Not sure if this is broken or not but we have been signed up for golem for over 10 minutes now and golems still did not appear out of the rune, rune just sort of is there glowing green.

**Comment by Shadowmech88** [comment]
I might be mistaken, but I believe you have to click the rune yourself, as a ghost. Or a living person does.
I believe someone's got to do some clicking to activate the actual summoning.

**Comment by ihadtoregisterforthis** [comment]
You need to be on top, click it or sign up, and someone alive has to click it too.

Sometimes you just are "not eligible" and I don't know why.

**Comment by Ephx1** [comment]
> Sometimes you just are "not eligible" and I don't know why.

If I recall, you can't ghost while alive to become a golem, you have to properly die then ghost.
