### ISSUE TITLE
AI/borg not receiving a notification on new PDA messages

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9367]
What it says on the tin. You hear the sound, but there's no longer a message notification with a link to open your message log and read it, the way that humans get them. I assume this has something to do with goonchat.

If this is tied to some new character setup preference, its presence has completely eluded me.

**Comment by PJB3005** [comment]
Multiple bug reports already, but I cannot for the life of me figure out WHY.

**Comment by Intigracy** [comment]
Looks like it got fixed at some point.

**Comment by Intigracy** [comment]
Scratch that, the icon is still fucked.

![ss 2016-06-14 at 11 53 14](https://cloud.githubusercontent.com/assets/4043940/16055560/b73ffb4a-3226-11e6-9051-e7115a3ee91f.png)

**Comment by Intigracy** [comment]
pAI is the same way.

![pai](https://cloud.githubusercontent.com/assets/4043940/16055844/b6b8fcfc-3227-11e6-87c4-7f3d043fba4d.png)

**Comment by clusterfack** [comment]
@intigracy Check if its sending bicon(/[icon]) or something

**Comment by Intigracy** [comment]
L.show_message("[bicon(P)] <b>Message from [src.owner] ([ownjob]), </b>\"[t]\" (<a href='byond://?src=\ref[P];choice=Message;skiprefresh=1;target=\ref[src]'>Reply</a>)", 2)

**Comment by Intigracy** [comment]
```
/obj/item/device/pda/proc/create_message(var/mob/living/U = usr, var/obj/item/device/pda/P)

    blablablabla

    //Search for holder of the PDA.
            var/mob/living/L = null
            if(P.loc && isliving(P.loc))
                L = P.loc
            //Maybe they are a pAI!
            else
                L = get_holder_of_type(P, /mob/living/silicon)

            if(L)
                L.show_message("[bicon(P)] <b>Message from [src.owner] ([ownjob]), </b>\"[t]\" (<a href='byond://?src=\ref[P];choice=Message;skiprefresh=1;target=\ref[src]'>Reply</a>)", 2)
```

**Comment by clusterfack** [comment]
That's pretty weird, bicon is only doing it to this right and nothing else?

**Comment by Intigracy** [comment]
PDA's for humans work fine if that's what you mean.

**Comment by ComicIronic** [comment]
Doesn't that look like the whole dmi to you?
Could it be this happens for when icon_state is null and it has to get it from icon default?

**Comment by PJB3005** [comment]
This was fixed.
