### ISSUE TITLE
Freezers cannot be upgraded with a Rapid Parts Exchanger

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9368]
To open the maintenance panel on a freezer, it must first be unwrenched. However, you cannot use the rapid parts exchanger on the freezer while it is unwrenched; it tells you to anchor it in place first. You also can't anchor it in place while the maintenance panel is open, and if you close it and anchor it, you're back to where you started.

They can be upgraded the old-fashioned way, but still, this is silly. The freezer's one of the few things worth upgrading around medbay.

**Comment by Chronakai** [comment]
Can confirm.

**Comment by ihadtoregisterforthis** [comment]
#6716
#6893
#7197
#7775

**Comment by d3athrow** [comment]
It actually works fine http://i.imgur.com/GaDfbPq.png something is having it call attackby still.
