### ISSUE TITLE
Easy solution to the "you feel buff gene" that does nothing

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9369]
What if we made it so the gene makes your body synthesize sports drink/brawndo?

**Comment by SysadminJeroen** [comment]
I believe that the gene prevents you from getting pushed to the ground due to air pressure. I'll check it anyways.

**Comment by PJB3005** [comment]
IIRC it makes Hulk stronger.

Pretty goddamn useless yeah.

**Comment by Shadowmech88** [comment]
Isn't it classified as the "strong" mutation in the code? I believe it causes thrown objects to deal more damage.

**Comment by BestName** [comment]
``` dm
var/throw_mult=1
        if(istype(src,/mob/living/carbon/human))
            var/mob/living/carbon/human/H=src
            throw_mult = H.species.throw_mult
            if(M_HULK in H.mutations || M_STRONG in H.mutations)
                throw_mult+=0.5
        item.throw_at(target, item.throw_range*throw_mult, item.throw_speed*throw_mult)
```

``` dm
else //We're being held by the mimic
        var/mob/living/carbon/human/H = user
        if(istype(H))
            if((M_HULK in H.mutations) || (M_STRONG in H.mutations)) //Finally a use for M_STRONG
                unlock_atom(H)
                visible_message("<span class='notice'>[H] easily breaks free of \the [src]'s hold!</span>")
                return
```

**Comment by Probe1** [comment]
>useless

doesn't it let you run with magboots engaged?

**Comment by Killette2** [comment]
Well fuck me, I heard that it does absolutely nothing all this time. But I never heard it doing anything with magboots, you're probably thinking of the strong leg gene.

**Comment by Probe1** [comment]
I may be. Duplicating the effect for strong would be a step towards improvement.

**Comment by Shadowmech88** [comment]
I believe that gene is referred to as the "run fast" gene in the code. But do to how our move delayer works, it's not possible for a mob to move faster than a running, well-fed, unencumbered human (without modifying the mob's movement_speed_modifier var that is, but the mutation currently does not).

So as a result the gene just brings you to top normal speed at all times, rather than making you actually faster.

**Comment by AutismSpider** [comment]
buff gene lets you toss rods and floor tiles for about 25 to 20 damage could do 30 on head shots if they have no  hat on or armor
