### ISSUE TITLE
Vaults don't always respect the bounds of vault areas when spawning

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9370]
#### Description of issue

I removed a 60x60 chunk of vault10 on metaclubs z6.  While testing my new area inside the 60x60 bounds, a syndicate vault spawned directly below it.  The center of the vault was inside vault10 area but the top of it was well outside it and deleted a fair bit of my structure.
#### Difference between expected and actual behavior

When spawning a vault check to see if the edges are within bounds and to retry if not.
Didn't check, spawned the top of a vault out of the vault10 area.
#### Steps to reproduce

Man this is such a bitch to reproduce that if I hadn't seen it happen while testing it wouldn't have been seen at all.  Try deleting all vault areas and mapping in an area that is too small to fit a vault.  That will probably provide a reproducible environ.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Yes, this is a problem when large vault spawn on the exact edge of the area.

The vault gets placed with the picked tile from the area being the bottom left, so you have to be careful.

**Comment by Probe1** [comment]
Closed in https://github.com/vgstation-coders/vgstation13/pull/23838
