### ISSUE TITLE
turf/simulated/floor is a hot mess and someones gotta subtype it.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9372]
![2016-04-10_16-44-11](https://cloud.githubusercontent.com/assets/8550416/14412988/88406e6a-ff3b-11e5-91da-457458422c9a.gif)

And that someone, unfortunately, is me.  If anyone has any advice please post it because it's gonna be a lotta dull work and I'm not so sure how I'll update every tile in the game, and whether it will break tile painters, and so on.

**Comment by ghost** [comment]
> subtyping stuff that should be varedited

thanks byond

**Comment by PJB3005** [comment]
Look at my smallsation PR that's not dead (RIP). I had the insanity to make subtypes for everything I used, including floors.

**Comment by Probe1** [comment]
https://github.com/PJB3005/vgstation13/blob/9a2b6fbace17564fedf52b8c02f171b4e166cad0/code/game/turfs/simulated/floor_types.dm#L413

**Comment by clusterfack** [comment]
Something like this isn't worth subtyping I think

**Comment by Probe1** [comment]
Look at the gif.  Right after cameras, it's as bad as mapping gets.  Its like having a huge box of legos all mixed together but you can only see two rows at once.

**Comment by PJB3005** [comment]
@probe1 that's an amazing analogy!

**Comment by xpcybic** [comment]
For added fun try generating all instances from dirs/states

**Comment by Probe1** [comment]
aged out
