### ISSUE TITLE
Defficiency R-UST feedback

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9376]
Post what you think of it here.  It's the only _on station_ R-UST we've had so I'm not too sure where the balance of it should be, how much should be set up how much should be left to players.  

Criticism complaints compliments whatever here.

**Comment by Probe1** [comment]
[16:28:23] Player PM from-Sailol/(Bronte Polson): So here, lemme tell you. First, two entrances are kinda unnecesarry
[16:29:00] Player PM from-Sailol/(Bronte Polson): Third, TEG needs a computer to regulate the pumps you could install
[16:29:33] Player PM from-Sailol/(Bronte Polson): and if you want to make it "station regular", Id recomend adding the parts instead of having to buy them from cargo 
[16:31:01] Player PM from-Sailol/(Bronte Polson): Ah, one last thing, there needs to be more space for the injector

**Comment by liltiptop** [comment]
1. The two entrances are not needed.
2. Having spare circuits there is not really needed as well, as you just order everything RUST related from cargo
3. I'd like it if the TEG was closer to the control room, but that's just my personal preference.
   Also FUCK YOU DUNY.

**Comment by AutismSpider** [comment]
lot of work for some thing that jam up 90% of the time

**Comment by Probe1** [comment]
@liltiptop 

The two entrances were chosen to give players something to fix.  They can make a choice of finishing the windoor or walling both off, or whatever.  I didn't want it to be "too set up" because it IS the R-UST and even if it's gonna be on the map it's still gotta have some setup right?

When I asked Sailol, he complained there WERENT the circuits needed to set it up so I think this is gonna come down to personal preferences.

Moving the TEG is a problem.  Can't go south cause the SME.  Can't go north cause atmos air mix chamber.  Fitting it anywhere else would require a significant rework of the surrounding areas.  I'd love to know where to put it that can also fit the fuel injector setup.  I CAN move the fuel injector but it'd be awfully dodgy to have it on the far side, away from view.  It's a decision and I wanna hear more about it.

@AutismSpider I know and it kills me that the TEG jams 90% of the time now, because those engineers worked really hard to set that thing up and achieved an excellent 1.6 million celcius and it was for naught.

**Comment by PJB3005** [comment]
#8771
