### ISSUE TITLE
Just what the hell are fax demotion and commodation keys supposed to do exactly?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9377]
#### Description of issue

http://i.imgur.com/zy59ZdR.png  See these?  Had a guy faxing centcomm constantly expecting a sticker to give to someone.  Stickers don't exist in the code as far as I know and he sure as hell wasn't getting one.
#### Difference between expected and actual behavior

Magic sticker contracts to work

They did nothing except repeatedly send centcomm messages
#### Steps to reproduce

Fax centcomm with the magic contract
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ihadtoregisterforthis** [comment]
> capitolize 

I've seen the thing. I was asked as CE to stamp it. The legend says whoever gets demoted losses access and rank.
ArrPee stuff but that's what the IAA does. Maybe ask senaat

**Comment by Konater** [comment]
To get those star posters you have to fax the commendation paper to PR and not central command
To demote someone you send the paper to PR, set the exact name on the chip, have a head stamp it, slap the chip on the guy that is getting demoted's ID

**Comment by Probe1** [comment]
I'll test it out and rewrite the description to make it more clear.

**Comment by clusterfack** [comment]
Yeah 90% sure I've seen them in the code somewhere, no idea how they are implemented if they are at all.

**Comment by PJB3005** [comment]
I've seen them in game.

**Comment by Brolaire** [comment]
ive done it 2 weeks ago, stickers are a goldstar poster btw. deffo needs better explanation

**Comment by Probe1** [comment]
Good gracious. Commendations  gives you a poster and the texts all screwed up and the poster doesn't even say the persons name.

Demotion chips don't change the job title.  They removed IAA access when applied to an IAA ID but didn't remove brig access or court access.

Demotion chips are a one time deal and if a person is ever given new access it will still return with `This card already has a microchip applied`

Holy fuck I applied `demote_chip` to a Captain ID and it only took away 20~ access values instead of all 63.

**Comment by Probe1** [comment]
```

/obj/item/weapon/card/id/syndicate/attackby(var/obj/item/I as obj, mob/user as mob)
    //placebo, does not affect access on syndie agent card
    if(istype(I, /obj/item/demote_chip/))
        var/obj/item/demote_chip/DE = I
        if(registered_name != DE.target_name)
            to_chat(user, "<span class='notice'>Failed to apply, names do not match.</span>")
        else if(bans != null)
            to_chat(user, "<span class='notice'>This card already has a microchip applied</span>")
        else
            icon_state = "centcom_old"
            bans = "9" //if get_region_accesses ever uses 9 we're fucked
            del(DE)
    else
        return ..()

/obj/item/weapon/card/id/attackby(var/obj/item/I as obj, mob/user as mob)
    //Check for if names match, card already has a chip, and its not a captains ID.
    if(istype(I, /obj/item/demote_chip))
        var/obj/item/demote_chip/D = I
        if(registered_name != D.target_name)
            to_chat(user, "<span class='notice'>Failed to apply, names do not match.</span>")
        else if(bans != null)
            to_chat(user, "<span class='notice'>This card already has a microchip applied</span>")
        else if(icon_state == "gold")
            to_chat(user, "<span class='notice'>This microchip cannot apply to this card type.</span>")
        else

            if(D.cap == 1)
                access -= get_region_accesses(5)
                bans = bans + "5"
            if(D.hop == 1)
                access -= get_region_accesses(6)
                access -= get_region_accesses(7)
                bans = bans + "67"
            if(D.hos == 1)
                access -= get_region_accesses(1)
                bans = bans + "1"
            if(D.ce == 1)
                access -= get_region_accesses(4)
                bans = bans + "4"
            if(D.rd == 1)
                access -= get_region_accesses(3)
                bans = bans + "3"
            if(D.cmo == 1)
                access -= get_region_accesses(2)
                bans = bans + "2"
            if(bans == null)
                to_chat(user, "<span class='notice'>You require at least one stamp.</span>")
                return
            icon_state = "centcom_old"
            del(D)
    else
        return ..()

```

https://github.com/d3athrow/vgstation13/pull/536

What a hot fucking mess.

**Comment by nuklearcellphoneg** [comment]
Please fix this and give the IAA power

**Comment by Probe1** [comment]
@nuklearcellphoneg I think that can be done easily by removing the stamp requirement on demotion chips but that's a canna worms.

Giving the IAA power of demotion - not just being able to acquire a chip then with the agreement of non existent heads and the person in question likelier to fight the IAA, but the power to demote a guy without stamps..

It'd change it up significantly.

**Comment by nuklearcellphoneg** [comment]
Just tie the requirement to departments. This would allow the hop and cap to focus on other stuff. If the cmo wants a chemist demoted, he can just go through the iaa, and all they would need would be a cmo stamp.

**Comment by Probe1** [comment]
[18:53:49]**VOTE: Custom vote started by Probe1.**<br>IAAs can order demotion chips RIGHT NOW with a fax.  In order to remove access, they must get a head of staffs stamp for the access pertaining to that head of staff.  Naturally this has never worked.  Should we remove the Stamp Act and let IAAs just order plain old  demotion chips and lynch them if they abuse it?
[18:54:52]VOTE: <b>Vote Result: Repeal the Stamp with 12 votes</b><br>   I have a brilliant solution that will fix everything and I will say it in OOC had 2 votes<br>   Keep the stamp had 2 votes

I made a poll today to check out what people thought, and also explained how it works in the title.  Since it never gets used, I expect people don't know how it works.

@nuklearcellphoneg How you described it is how it works in game.  But no one does that shit.  Instead of seeing the CMO to remove the medbay access and say the CE to remove the maint access, why not just go to the HoP in the first place and remove ALL the access.

Why use an alternative method to demotion that will take way more work and rely on getting shit stamped when the real obstacle isn't the demotion, its catching the fucker in line for demotion.

**Comment by nuklearcellphoneg** [comment]
@Probe1 

Personally, where I work has ID cards. There are doors I can go in and others I cannot go in.

If I get fired but keep my ID and come back, beep... HAAAAAANK.

Beep.... HAAAAANK.

They don't remove my access from my ID; they remove me from the system recognizing my access, if that makes sense. Why not make Remote Access Removal possible via IAA?

**Comment by Shadowmech88** [comment]
Because our ID system doesn't work like that. Airlocks are programmed to check for access, not who owns the ID.

**Comment by nuklearcellphoneg** [comment]
Right, I know. However, while this is how it happens from a Coding and utility perspective(it's easiest to just say it puts the access on the ID), perhaps, why does the IAA demotion have to work in this way? Use the key, get the stamp, cram it in the fax machine, remote demotion.

Could also ultimately be useful for an OP traitor IAA, and perhaps increase the IAA's usefulness and power overall, being someone that, if the Captain is aware an Assistant has given himself all access, you DO need to get to the Assistant and arrest and so on and so forth... however, the Captain can seek out the IAA in order to remotely remove the access.

It'd be a big game changer, but that's kind of the IAA's supposed niche anyway, being neither above nor below any station staff, but they have to rely on the big bad folks at Centcomm to help them out.

**Comment by Shadowmech88** [comment]
If they do get the power for remote demotion, they should have to request a _specific_ demotion stamp for a _specific_ crewmember, and it should require fielding by an admin at Centcomm.
I dislike the idea of an IAA being able to remote-demote any random crewmember at a whim.

**Comment by nuklearcellphoneg** [comment]
It greatly increases the value of a stamp and gives much more scrutiny towards an IAA, though I understand where you're coming from.

**Comment by Probe1** [comment]
IAAs literally never use this because its so convoluted and we're gonna have to give a little somewhere.
