### ISSUE TITLE
Artcifers are told they can use magic missile in their creation message

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#9380]
@DeityLink

**Comment by Probe1** [comment]
it'd be easier to just remove that one line desu

**Comment by DeityLink** [comment]
![t0xhtgj](https://cloud.githubusercontent.com/assets/7573912/14434096/67ab5eea-0011-11e6-8ce6-095c39037e63.gif)
>(reading soulstone.dm) how did that even happen, guess I better check the creation message for the other constructs as well, wait Juggernauts can reflect beam weapons?
>(reading constructs.dm) so they actually can, it's just a chance but...wait, then it's older than my projectile revamp right? so the projectile is gonna be weirdly shaped and shit...damn I have to make it match the ablative armor's code.
>(reading armor.dm) wait, the ablative armor is there but not the code for reflecting beams, where did I put it?
>(reading projectiles.dm? beams.dm? ah, human_defense.dm) ok there it is, only have to change this...and that...and...wait, construct names are capped, but the reflect message has "[src]" instead of "\the [src]" guess I have to add \improper before those names.
>(reading armor.dm, labcoat.dm, etc....) ...yeah nah, someone else will have to do it for those.

Incidentally did you know that juggernauts are even more effective than ablative armors are making beams and energy stuff bounce back?

**Comment by Probe1** [comment]
I didn't consciously know that but I'm not surprised considering I have a separate mentality when fighting juggs and that is to always move when shooting so avoid reflect backs.  Also I got chu on that hot meme fam

![images](https://cloud.githubusercontent.com/assets/8550416/14435509/3f26a37e-ffe6-11e5-8770-3b250dec2dda.jpg)

**Comment by DeityLink** [comment]
Well if you fire at them with laser weapons chances are the reflect will be instant either way. But depending on the angle you fire at them you can safely avoid it.
