### ISSUE TITLE
Characters displaying vox spritesheet on examine

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9384]
http://puu.sh/o7VvX/1321a5c8e1.png

Took this a few days ago when I first noticed it. Sometimes it displays other pieces of the spritesheet, such as a forward-facing vox. It does this regardless of the race or gender of the person you're examining, too.

**Comment by Intigracy** [comment]
@PJB3005

**Comment by PJB3005** [comment]
I can only think of 1 way this could happen.

I cache the base64 based on the ref of the icon (if it's a `/icon`), so BYOND obviously reuses those and when it does the code thinks the icon is already cached but it's pulling the wrong one.

**Comment by liltiptop** [comment]
I've also had issues with this.
When you shift click to examine, you'll get some distorted picture next to their name.
I think when you shift click a vox, it shows a human sprite

**Comment by PJB3005** [comment]
@liltiptop wait actually distorted or is it just 4 sprites in the space for 1 so they're tiny?

**Comment by Probe1** [comment]
Its 4 sprites for each perspective front back left right all in a tiny Square where they're icon should be
