### ISSUE TITLE
Turning mesons off and on again offer complete welding protection

### ISSUE THREAD

**Issue by Gringonius** [d3athrow/vgstation13#9387]
#### Description of issue

As described
#### Difference between expected and actual behavior

They should keep making you go blind instead.
#### Steps to reproduce

Wear mesons, toggle them off and on and weld anything.
Doesn't seem to offer flash protection though
#### Length of time in which bug has been known to occur

No idea. Probably since mesons were around
#### Server revision

b0cdcf0ad237904acf44e8c5d38426b096cd7493

**Comment by PJB3005** [comment]
Fixed in the holomap PR.

**Comment by Probe1** [comment]
nice ATOMIC pr you got there pjb

**Comment by PJB3005** [comment]
@probe1 I refactored how meson toggling worked so I decided to fix it while I was at it.

**Comment by Probe1** [comment]
I was kidding you goofball.
