### ISSUE TITLE
New Sprite for Large bluespace beaker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9392]
(WEB REPORT BY: tifora REMOTE: 172.93.109.202:7777)
The current sprite is shit, looks like they copied the smaller beaker sprite on top of a larger grey beaker.

**Comment by PJB3005** [comment]
10/10 bug report.

**Comment by clusterfack** [comment]
Fuck off making shit like this isn't what the bug reporter is for
