### ISSUE TITLE
Issues with operating on headless corpses

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9394]
If someone begins a debraining surgery on someone, and then that person is beheaded, surgery still seems to believe that they have a head and that the surgery is still in progress. So, say, if the person is beheaded with brain surgery left at the step where you have sawed open the head and need to use the retractor to force the skull open, using the retractor to attempt to rearrange the tissue for head transplant will simply open and close their skull. You can also advance the previous, unfinished surgery to the point where the retractor is no longer required so that you can perform the head transplant.

As I am not an absolute madman, I didn't attempt to remove the brain from the beheaded body, but it concerns me what might happen if you did.

Another issue I found was that when performing a head transplant, the first step never really "completes". Using the retractor completes the step and allows you to advance, but you're then able to use the retractor again, at any point in the surgery, which completely resets your progress and puts you back to step 1. This means that the surgical incision manager cannot be used for head transplant surgery, as attempting to use it as a hemostat will cause it to repeat the retractor step.

Found this out during a super long ling round with lots of husked bodies to transplant heads off of.

**Comment by Exxion** [comment]
But experimenting with bugs is fun

I'd really love to know what happens if you try to remove the brain

**Comment by Exxion** [comment]
I tested it on local
You _can_ remove the eyes from the headless corpse, but _not_ the brain

Furthermore, this is a separate issue, but the eyes are attached to the body, not the head, so replacing the head doesn't replace the eyes

**Comment by Hoshi-chan** [comment]
Whew. Wonder why it's like that.

**Comment by 9600bauds** [comment]
> the surgical incision manager cannot be used for head transplant surgery, as attempting to use it as a hemostat 

the surgical incision manager never works as a hemostat reeee

**Comment by Blithering** [comment]
Had a beheading related issue recently. I beheaded a guy, removed the brain, then reattached the head. The reattached head had a duplicated brain inside.

**Comment by ihadtoregisterforthis** [comment]
but if mmi is dead then WHO WAS BRAIN??
