### ISSUE TITLE
Hearing Lingchat as a Posibrain

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9396]
(WEB REPORT BY: lamberts REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b0cdcf0ad237904acf44e8c5d38426b096cd7493
> 
> General description of the issue
> Heard lingchat as a posibrain
> 
> What you expected to happen
> Not hearing lingchat
> 
> What actually happened
> Heard Lingchat
> 
> Steps to reproduce if possible
> Be a posibrain, hear lingchat. I was a posibrain that had another ghost in it before if that matters.

**Comment by Killette2** [comment]
This issue sounds familiar, didn't we have this bug be reported already?

**Comment by PJB3005** [comment]
Yes, and it was for all sillycons.
