### ISSUE TITLE
Order the PDA messaging menu like the crew manifest, or add "(Message)" buttons to the manifest

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9397]
Need to talk to the Botanist? Either slowly scroll down reading all the job titles until you find him, or ctrl+f "Botanist" and pick him apart from the 2 results
Need to talk to Dave? Either slowly scroll down reading all the names until you find him, or ctrl+f "Dave" 
It is very unquality

**Comment by Probe1** [comment]
the next logical step is "Why do we have two menus to do the same thing" instead of just a crew manifest menu with a MESSAGE and $ box

and he next logical step after THAT I can't believe I never thought of this before, is having mid 2000s flip phone customizable PDA backgrounds from a set list.

The answer to all this is wyci of course.  The customizable background idea is solid gold though and frankly you people should be paying me for these ideas.

**Comment by Intigracy** [comment]
Two menus because you can turn off your PDA ringer.

**Comment by liltiptop** [comment]
Why not just have something like
Messages>Department Select> Find person in department>then message/send dosh.

**Comment by BestName** [comment]
> Need to talk to Dave? Either slowly scroll down reading all the names until you find him, or ctrl+f "Dave"

How exactly would making it look like the crew manifest help with this?
Besides if you're having trouble finding a specific name in an alphabetically sorted list you might have brain problems.

**Comment by clusterfack** [comment]
Best of both worlds, add a message button to the crew manifest, and a search bar to the regular pda messaging menu along with the regular list of names

**Comment by 9600bauds** [comment]
The PDA messenger isn't always alphabetized for me, I think especially not for people who latejoined
Also you may know which department Dave is in

**Comment by 9600bauds** [comment]
Search bar seems a little pointless when you have Ctrl+F

**Comment by BestName** [comment]
But what if you don't know which department he works at? Then instead of looking through a neat alphabetically sorted list, you would have to go through every department and see if they have a Dave.

**Comment by 9600bauds** [comment]
Honestly I Ctrl+F every time, beats scrolling through a list.
But we could have both by keeping the messenger menu and adding the (Message) button on the manifest as well

**Comment by 9600bauds** [comment]
Also while we're at this: SILICONS SHOWING UP ON THE MANIFEST WHEN

**Comment by Probe1** [comment]
they aren't crew tho

**Comment by clusterfack** [comment]
Put them under 'slaves'

**Comment by 9600bauds** [comment]
that

**Comment by west3436** [comment]
No interest in implementing this since issue creation
