### ISSUE TITLE
Make glass sheet stacks slightly translucent?  Yes/no?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9403]
![6kejjtt](https://cloud.githubusercontent.com/assets/8550416/14467349/ee931244-00a8-11e6-9113-535bbab166ba.png)

This is such a better idea in my mind.

**Comment by Shadowmech88** [comment]
If a single sheet of glass is only _slightly_ translucent, then wouldn't a stack of 50 sheets not be translucent at all?

**Comment by Probe1** [comment]
Yeah I noticed that too.  If multiple single sheets of glass were stacked on top of each other then their opacity would stack, making it less translucent as it goes until it looks like it does currently.  But if you have a single object that is a stack of multiple sheets then there's no real recourse for that except to have multiple sprites.

And that's a can of worms.  How many sprites?  How many opacity settings?

**Comment by Shadowmech88** [comment]
You can manually alter an atom's `alpha` var to change its opacity.
What about making the stack's alpha set to `min([single sheet alpha] * src.amount, 255)`?
You can put the line into `/obj/item/stack/sheet/glass/update_materials()`.
