### ISSUE TITLE
Round end markov chain.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9407]
At the end of a round, it'd be neat if a piece of text made with markov chains generated during the round would be displayed.

Whether this should be limited to OOC, IC, or cover everything is up for debate.

**Comment by Probe1** [comment]
ok if you code it it sounds neat and it won't hurt much if people dislike it.

**Comment by Mijhead** [comment]
i am a random person and i :+1:

**Comment by Killette2** [comment]
So I had to google what this is... why the fuck are you requesting a vagina ingame?

![vagina](https://cloud.githubusercontent.com/assets/5169310/14482001/fa69af44-0105-11e6-9609-212a9e54d204.png)

**Comment by nuklearcellphoneg** [comment]
Sounds like something interesting for Round End info, but... what info is it going to portray?

**Comment by PJB3005** [comment]
@killette2 you ended on the wrong side of Google then.

A Markov chain is a chain of nodes, each having a weight to go to other nodes in the chain, some with higher chance some with lower.
http://setosa.io/ev/markov-chains/

@nuklearcellphoneg, no idea really, probably IC?

**Comment by 9600bauds** [comment]
Deadchat Markov chain: "is the AI is bolting, Termedclepe blowing up the fucking wheelchair need be nerfed every single fucking time. The mime has been all shift and who are the lings, but I haven't seen this guy do anything else when he's antag? I just wanted to be the autistic"

**Comment by nuklearcellphoneg** [comment]
Could be cool, could be a disturbing blob of gibberish.

I think chat messages could be neat but I'm guessing it would be something like:

Round occurs. 

Event----->> Chit chat occurring around same time.

So

Welder bomb--->>> Chit chat prior and after ---->>> ckey controlled mob accrues large damage, chit chat from before and after(in particular the mob receiving and the mob dealing damage) ---->>> tank bomb blows up, chit chat from the minute before and after

**Comment by ghost** [comment]
So, it'd include explosions at locations, people dying, people being revived, random events and where they affect, shuttle calls, traitors buying things?

**Comment by ihadtoregisterforthis** [comment]
This could go with the round statistics gathering that got merged last year.

**Comment by Probe1** [comment]
Which I've seen none of strangely

**Comment by gbasood** [comment]
They exist but they web interface is something I rarely touch on.
It's super ugly but it works for viewing per-round stats right now
Just doesn't get the statfiles delivered at the moment.

As for Markov chains, I really am not interested in adding another way for the stat parser to break at the moment.
