### ISSUE TITLE
The Sweet Machine needs power to work

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#9408]
The Sweet Machine that spawns outside the kitchen on box needs to be bolted in a powered room to work.

No message no nothin, it just won't accept coins if its not in an area with power.

**Comment by clusterfack** [comment]
Feel free to reopen when you feel like putting details

**Comment by PJB3005** [comment]
Pretty goddamn clear to me. 

He's talking about that sweet machine @Arthurdentist made, which you insert a coin in then (presumably) rotate the thing and get candy.

Those machines are mechanical, unless they aren't anymore in the future but I assume this is the intention of Arthur.

**Comment by clusterfack** [comment]
Yeah and if he felt like actual writing any of that in the issue so people like me who don't know what the fuck that is would understand the problem BECAUSE THATS THE FUCKING POINT OF AN ISSUE.

**Comment by Exxion** [comment]
It seems pretty safe to assume that people would know the name of a colorful machine found right in the main hallway

**Comment by ihadtoregisterforthis** [comment]
They would if they ever went to the server :~)

**Comment by TheFriggenSawbones** [comment]
@clusterfack 
ok sorry fixed

**Comment by clusterfack** [comment]
@ihadtoregisterforthis Despite what you remember of a machine like this I think of just a hundred lines of code at most, of which there are several hundreds of thousands in our codebase.
