### ISSUE TITLE
ripleys cant hit each other with the clamp

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9413]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> you can harm people but not other ripleys with the clamp
> 
> What you expected to happen

hit other mechs

> What actually happened
> cant hit other mechs
> 
> Steps to reproduce if possible

hit a mech wit harm intent

**Comment by Killette2** [comment]
Can ripleys shove each other on the non-harm intent with the clamp? I'd love to see sumo ripleys. Also can the ripley even fit something it's size in the clamp? What does it clamp?

**Comment by AutismSpider** [comment]
can pick up plasma cans and shit with the clamp even super matter shards if you dont pass out form the rads and shit

**Comment by Exxion** [comment]
Ripleys can pick up anything that:
1. Is not anchored
2. Is not a mob
3. Does not directly contain a mob

As long as it satisfies all of those requirements, a Ripley can pick it up
This (presumably) includes other Ripleys that have become unanchored by the singulo and do not currently have pilots

**Comment by Tokanova** [comment]
@Exxion They can actually pick up people in lockers.

**Comment by Exxion** [comment]
I'm very sure they can't
They used to be able to, though

**Comment by Tokanova** [comment]
Huh... I actually haven't tried it in a long time so what do I know.

**Comment by Killette2** [comment]
I'm pretty sure there's some fucked up way to pick up people somehow, like with the new addition of cages. It's just about being creative and thinking "How can I get around this limit"

**Comment by Exxion** [comment]
Probably. The search isn't recursive, so if there's a mob in something and then that is in something else, the Ripley would have no problem picking it up.

**Comment by AutismSpider** [comment]
cages bug out when  pick up with a ripley

The ripley grabs the cage and the mob is left trap on that spot until the riplet drops the cage mob gets teleport to were the cage is drop

**Comment by Exxion** [comment]
Ah yes
Because the cage doesn't actually _contain_ the mob, but simply has the mob locked to it

The same thing probably happens if you pick up an office chair or wheelchair with someone on it

**Comment by west3436** [comment]
No interest in implementing this since issue creation
