### ISSUE TITLE
Check Self for Injuries text for bleeding limbs needs to be red/bold/both

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9414]
I mean really, examining yourself DOES say if you're bleeding or not, there's no reason why this verb should be so shit

**Comment by Exxion** [comment]
Are you sure? It's always detected bleeding when I've done it
There's no different font for it or anything, though
It just says that a body part is bleeding

**Comment by 9600bauds** [comment]
Oh, you're right, it's just the same tiny black font so it's extremely easy to pass up
Well that's an easy fix at least
