### ISSUE TITLE
Deff medbay has no roller beds

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9416]
see title;
i'll fix it if no one beats me

**Comment by Killette2** [comment]
A medbay without roller beds sounds rather defficient.

**Comment by nuklearcellphoneg** [comment]
This goes against what defficiency stands for.

**Comment by Probe1** [comment]
I'll just put them in maint.

**Comment by nuklearcellphoneg** [comment]
That's the spirit

**Comment by Konater** [comment]
Two got added, this can be closed
