### ISSUE TITLE
Add "Get all light tiles in area" self attack function to light tile remotes

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9418]
#### Description of issue

Light tile remotes are super fun but light tiles are ubiquitous when used and no one really wants to click EVERY LIGHT TILE with a light tile remote _for every light tile remote (color) you want  to use_.  

Instead, they should have two settings.  The first as it is now, click a light tile add to memory.  The second, add all light tiles in a 3x3 area.  Or 5x5.  Or adjustable!

I was clicking upwards of 30 times for each light tile remote, and had 8 light tile remotes.  For the tiny amount of payoff (changing a light tiles color autonomously) it should be way way less clicks.

**Comment by Killette2** [comment]
I don't understand how light tile remotes work exactly, I haven't touched them since the rework. Can one remote be triggered to change several tiles like a switch with conveyor belts?

**Comment by Probe1** [comment]
Light tile remotes work by clicking on a light tile.  It saves them to memory.  From there, the light tile remote has a UI where you can change their color and send a signal to change color like a multitool menu.  The difference is it can be done remotely.  

The hangup here is each individual light tile has to be tagged.  For such a single-purpose item, it ends up generating a lot of work and isn't a worthwhile endeavor since you'll be clicking every single light tile with every single remote, and if you want light tiles to change colors you'll need multipl remotes.  So now you're clicking EVERY light tile with EVERY light tile remote to save the light tile in their memory.  

Even with a very simple program like 3 tiles and 3 remotes, its a minute of work.  Now lets say you want to do something sick like rim the bar with color changing light tiles.  Now you're clicking 20-40 times per remote.

**Comment by PJB3005** [comment]
How about click dragging?

**Comment by Probe1** [comment]
uhh click dragging like making a box or something over all the tiles you want to include?

I mean sure but I can't think of a single thing outside of buildmode that works like that.  Unless you meant holding lmb and hovering over every tile regardless of adjacency.  While that would work, it would end up being a lot of the same problem just without having to move.  You're manually adding every single light tile.  And for what this is, manually adding every tile in a large area is not worth the work.
