### ISSUE TITLE
Reagents disappear at 0.1 units, even if they have a custom metabolism below that amount

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9419]
Say you give someone 1 unit Spaceacillin, which has a custom metabolism of 0.01.
Supposedly, this should mean 100 ticks of Spaceacillin
However, after 90 ticks, the amount of Spaceacillin goes down to 0.1. At this point, somehow it just disappears instead of going down to 0.09
This means 10 less ticks worth of Spaceacillin IT'S A WHOLE 20 SECONDS WAKE UP SHEEPLE BIG PHARMA IS PLAYING US AAAAA

**Comment by ghost** [comment]
Probably a check to make sure that you don't get weird reagents becoming infinitesimally small

**Comment by Shadowmech88** [comment]
> At this point, somehow it just disappears instead of going down to 0.09

Are you checking with varedit, or with an advanced mass spec? It could be that the mass spec simply does not show reagents with amounts of less than 0.1.

**Comment by Killette2** [comment]
Old lipozine when? This instant lipozine is bullshit despite it supposed to be having a metabolism.

**Comment by 9600bauds** [comment]
I checked with VV as well yeah

**Comment by ghost** [comment]
Sounds like a hardcoded clean-up. We should likely keep it to prevent infinitesimal quantities of chemical

0.01 sounds better since we have so many snowflake chemicals which drain at that rate

**Comment by 9600bauds** [comment]
Why not just use the reagent's custom_metabolism
or does that make too much sense?
