### ISSUE TITLE
The drink "Joe" plays music oddly, as if it's playing the the same song twice on top of eachother

### ISSUE THREAD

**Issue by gobblecoque** [d3athrow/vgstation13#9420]
#### Description of issue

When drinking the drink "Joe", the screen turns black and white, as expected, but the music that comes plays as if it's playing twice ALMOST at the same time. It's pretty noticeable.  
#### Difference between expected and actual behavior

The song that accompanies the effects of "Joe" is supposed to play once, and on repeat instead of twice and layered on top of each other.
#### Steps to reproduce

Simply drink "Joe".
#### Specific information for locating

The drink, "Joe" is made by using 5 units of coffee and 5 units of Whiskey.
#### Length of time in which bug has been known to occur

Probably since "Joe" was added, 2016.03.06, By Dr. Celt, along with the NOIR mutation. 
#### Server revision

900fcf51f749acea63a190fab60608f088405746 Current Infomational Settings: 
Protect Authority Roles From Tratior: 1
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by 9600bauds** [comment]
Extremely good report

**Comment by Exxion** [comment]
Did this just happen again? Because it was allegedly fixed three days ago.

**Comment by ihadtoregisterforthis** [comment]
The last time it was called "Jazz Hell", so I assume it's a different thing.

**Comment by gobblecoque** [comment]
@9600bauds  I hope that wasn't sarcastic ;_;
@Exxion I didn't see it in the change log. I'll check now.

**Comment by ihadtoregisterforthis** [comment]
@DrCelt

**Comment by gobblecoque** [comment]
This has been fixed. Please add to changelog.
