### ISSUE TITLE
Add two wires (ID Scan, open/close) to windoors

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9421]
I'm thinking "How cool would it be to make an assembly where the bell opens a windoor?  Or a button?  Lots of possibilities.  Windoors are a lot simpler, all they'd need are ID scan and a open/close wire.

We could retain the existing balance by making its panel only accessible when the windoor is open.  No need to worry about people hacking windoors and maps having new vulnerabilities et cetera.

**Comment by 9600bauds** [comment]
Windoors SHOULD be hackable desu

**Comment by FudgePucker** [comment]
I mean, you can hack it now with a blunt object already, if you know what I mean.

:+1:
