### ISSUE TITLE
Defficiency Permabrig Intercom Not Broadcasting

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9422]
#### Description of issue

The intercom in the Defficiency permabrig will not broadcast even when the microphone is turned on.
#### Difference between expected and actual behavior

The intercom should broadcast what is said inside the room while the microphone is on.
#### Steps to reproduce

Enter the Defficiency permabrig, turn the intercom's microphone on, and talk into it.
#### Length of time in which bug has been known to occur

Just last round.
#### Server revision

900fcf51f749acea63a190fab60608f088405746
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Intigracy** [comment]
The broadcast wire starts cut I'm pretty sure.

This way people you permabrig can't yell over the radio constantly until someone comes to break them out.

**Comment by Konater** [comment]
This can probably be closed now

**Comment by Shadowmech88** [comment]
Does the intercom in your reworked Deff permabrig not have its broadcast wire cut?
