### ISSUE TITLE
Screenshotting no longer displays a message in chat

### ISSUE THREAD

**Issue by xpcybic** [d3athrow/vgstation13#9424]
#### Description of issue

Taking an ingame screenshot through the File menu or F2 shortcut no longer gives you a confirmation line in chat with the name of the screenshot.
#### Difference between expected and actual behavior

Previously you would get a line with something like "Screenshot saved as whateverthefuck.png" with a link to the file.
#### Steps to reproduce
1. File -> Quick screenshot or F2
2. Check screenshots folder and confirm that the screenshot was saved
3. Check chat pane and find no such confirmation
#### Length of time in which bug has been known to occur

Only recently; I would assume since goonchat
#### Server revision

edf4f5d6aa7ab6ed0c4317e4f7e1ff291d0a7f7b 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ihadtoregisterforthis** [comment]
I thought screenshots were busted as a whole

**Comment by xpcybic** [comment]
I double-checked and they're definitely still saving

**Comment by PJB3005** [comment]
I was gonna say I can't fix this but I can, but it'll be hacky.

**Comment by clusterfack** [comment]
Why exactly would this present more of a problem than anything else?

**Comment by PJB3005** [comment]
@clusterfack the screenshot message is handled entirely internally in BYOND.

**Comment by west3436** [comment]
BYOND issue.
