### ISSUE TITLE
Attacking with a baton/loaded immediately after lasering with a energy/gun results in baton applying burn damage instead of brute

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9428]
#### Description of issue

A stun baton when used on harm intent applies 10 brute damage.  When a mob is lasered with an energy gun and immediately afterwards struck with a stun baton, it applies burn damage instead of brute.  The second hit (and successive hits) will apply brute damage properly.
#### Difference between expected and actual behavior

Brute damage should be applied consistently instead
#### Steps to reproduce

spawn human, baton/loaded, and energy/gun.  Stand close by and laser the mob then harmbaton him.  Check the variables and you'll see he has 40 burn damage instead of 30 burn and 10 brute.  Harmbaton him again and see he has 10 brute 40 burn.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
Tested locally, no longer seems to happen. Monkeyman had 10 brute and 30 burn as expected.
