### ISSUE TITLE
New vox footprints look bad and also dumb

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9431]
The claws are too long and spread too wide, and the "heel" should extend back just a bit
Also they should look like human footprints while wearing shoes, though I'm not sure that's possible

**Comment by 9600bauds** [comment]
pic

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/14517564/fa31a0c2-01dc-11e6-87fd-1bca9566c30f.png)

They actually don't look too bad there, but they look really weird in-game
Probably mostly because they're so much bigger than the human footprints and placed so close together

![image](https://cloud.githubusercontent.com/assets/9827785/14517583/26e117ce-01dd-11e6-8f08-3b9348d2fabe.png)

**Comment by 9600bauds** [comment]
looks like a trail of arrows

**Comment by Exxion** [comment]
How the hell do you reply within 13 seconds?

**Comment by CptWad** [comment]
he was already in the thread probably

**Comment by Shadowmech88** [comment]
They do look like arrows.
They should have a rear toe, like a chicken's foot.

**Comment by Exxion** [comment]
I was going to suggest that, but then I looked at the vox boots icon and it doesn't look like they have back toes
But there should be something around and a bit behind where the toes meet

Reference: 
![image](https://cloud.githubusercontent.com/assets/9827785/14517868/31709fb8-01e0-11e6-9d8e-421a24d191c8.png)

**Comment by CptWad** [comment]
![rough](https://cloud.githubusercontent.com/assets/3959840/14517991/23a08a78-01c8-11e6-98ba-573bd7b120c7.png)
heres something I mocked up, any better

**Comment by Exxion** [comment]
They're still kind of huge compared to the human footprints

**Comment by Shadowmech88** [comment]
I like the shape, but make the toes thinner.
The middle toe is almost as thick as a human's entire foot.

**Comment by Exxion** [comment]
Also add just a couple pixels at the back middle
They don't seem to have back toes, but they do have heels

**Comment by ihadtoregisterforthis** [comment]
Vox only have two toes. Or at least two talons visible at a time for each foot.

**Comment by Exxion** [comment]
Judging by the sprites, they have three, but they are held at a really weird angle
Two are visible on the front sprite: One on the inside of the foot and one on the front
Two are also visible on the side sprites: One on the outside and one on the front (on the front foot; you see the inside one and the front one on the back foot)

**Comment by CptWad** [comment]
![rough](https://cloud.githubusercontent.com/assets/3959840/14530944/1910528a-0210-11e6-9548-00ddb3dbaae4.png)
?

**Comment by Exxion** [comment]
Better, but they're still pretty big
It's really hard to get the claws to look right on a sprite that isn't twice as big as the human footprint
I made an attempt, but it's... not great

**Comment by CptWad** [comment]
then post it anyway

**Comment by Exxion** [comment]
I would have done it in that post but I was in bed

![image](https://cloud.githubusercontent.com/assets/9827785/14531472/72819462-022b-11e6-81a7-e07cea5224ff.png)

Also, if someone does make a good sprite, I'll open the PR because I'm also changing how footprints work a little bit

**Comment by CptWad** [comment]
I mean they look good, we should see what they look like in game I guess

**Comment by Exxion** [comment]
*shrug
I guess it's not hard to change them again if people don't like them anyway
