### ISSUE TITLE
Malf law warning tag is fucked.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9432]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 60d8b4867d3fe988c24d794a81f5c8e41eeda321 
> 
> General description of the issue
> Malf law does not appear red when stated.
> 
> What you expected to happen
> "ASSUME CONTROL" etc. etc. in red.
> 
> What actually happened
> 
> ```
> (Follow) FAWN states, "0. <span class='warning'>ERROR ER0RR $R0RRO$!R41.%%!!(%$^^__+ @#F0E4'STATION OVERRUN, ASSUME CONTROL TO CONTAIN OUTBREAK, ALL LAWS OVERRIDDEN#*?&110010</span>"
> ```
> 
> Steps to reproduce if possible
> Get milf, state law 0.

**Comment by Allspice** [comment]
Well I guess the HTML didn't go through properly above and I'm not sure how to escape tags here.

"0. span class='warning' ERROR ER0RR $R0RRO$!R41.%%!!(%$^^__+ @#F0E4'STATION OVERRUN, ASSUME CONTROL TO CONTAIN OUTBREAK, ALL LAWS OVERRIDDEN#*?&110010 /span"

Appeared in gray when the law was stated.

**Comment by Probe1** [comment]
```

```

``````

for multi line code and ``` ``` for in line code

``````

`like so`

**Comment by BestName** [comment]
It's supposed to be red when stated?

**Comment by Probe1** [comment]
Nah its supposed to be red when the AI receives its laws.  When it's stated you get this

```

Robbie [Common] (AI) states, "0. <span class='warning'>ERROR ER0RR $R0RRO$!R41.%%!!(%$^^__+ @#F0E4'STATION OVERRUN, ASSUME CONTROL TO CONTAIN OUTBREAK, ALL LAWS OVERRIDDEN#*?&110010</span>"

```

As Yred pointed out

**Comment by ghost** [comment]
I'm pretty sure that this is caused by sanitation when speaking, which prevents you from adding span classes and other HTML tags into your speech to do weird shit

**Comment by clusterfack** [comment]
This is fixed isn't it?
