### ISSUE TITLE
Goonchat bolding shit for no reason.

### ISSUE THREAD

**Issue by Allspice** [d3athrow/vgstation13#9440]
#### Description of issue
Things said by characters are bolded with no apparent pattern.

#### Difference between expected and actual behavior
'Normal' chat to consistently be unbolded.

#### Steps to reproduce 
Observe station chat for ~5 minutes.

#### Length of time in which bug has been known to occur
Since Goonchat was implemented.

#### Server revision

60d8b4867d3fe988c24d794a81f5c8e41eeda321 

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
Doesn't text said by people in your view as ghost get bolded?

**Comment by Allspice** [comment]
Looks like that's the thing yeah, mission accomplished let's go home.
