### ISSUE TITLE
Should we use a mapfile format similar to /tg/'s?

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9447]
Pros: Almost totally eliminates map merge conflicts

Cons: Increases the size of the mapfiles by probably somewhere around 20% (by my estimate, based on assumptions that may or may not be correct) and the number of lines in the mapfiles by some absolutely absurd degree

**Comment by Probe1** [comment]
vote yes

**Comment by Shadowmech88** [comment]
What effects would larger mapfiles have?

**Comment by PJB3005** [comment]
Nothing, really.

**Comment by Exxion** [comment]
The extra size is almost entirely whitespace, so it shouldn't have much effect on loading time
Can't say for sure because... well, BYOND always has surprises

**Comment by PJB3005** [comment]
Nah it's not exclusively whitespace, it seperates the map chunks a ton more.

**Comment by Exxion** [comment]
Well yeah
I did say _almost_ entirely

Also, if we do do this, our map files will be astronomically long
/tg/'s are pretty fucking long and they only have one Z-level per file
It wouldn't really be a problem under any circumstances I can think of, though

**Comment by SysadminJeroen** [comment]
@PJB3005, so less merge conflicts and less pain in the ass?

2016-04-14 22:18 GMT+02:00 PJB3005 notifications@github.com:

**Comment by Exxion** [comment]
If we go as far as /tg/ did, zero merge conflicts unless two people edit the same individual tile (or the map cleaner rearranges some tiles like it sometimes just decides to do), and even then possibly not

**Comment by unid15** [comment]
Abso

hecking

lutely

**Comment by Intigracy** [comment]
We don't have merge conflicts unless people edit the same individual tile.

Well at least we wouldn't if people would read the directions in install.txt.

**Comment by optimumtact** [comment]
be aware that at least for us it made asteroid unuseable in the byond map editor since it just broke on large map files, so you had to convert to dmm, edit, then back to tgm

**Comment by Probe1** [comment]
crap

**Comment by Exxion** [comment]
Wait, is the issue with large files or long files?

**Comment by optimumtact** [comment]
I'm not actually sure, I think it was the length of the file

http://www.byond.com/forum/?post=2044362 bug report

**Comment by Exxion** [comment]
If it's length, we probably shouldn't even bother with this idea until that gets fixed, considering we store all our Z-levels on one file, so all of our mapfiles would be quite a lot longer than any of yours

**Comment by Probe1** [comment]
Yeah I was pretty crushed to read that because man, this sounds great.

And Lummox will never respond.

**Comment by optimumtact** [comment]
you can still use it, it just requires an extra conversion step from tgm -> dmm for the actual server compilation/running.

again, it may not be size exactly, my memory is hazy as to the actual reason and asteroid is not iirc our largest map, so I reckon at least give it a whirl locally

edit:plus I was wrong in my original description - it dies in the compilation step, not the editor step.

**Comment by Intigracy** [comment]
Even worse.

**Comment by mrpain666** [comment]
Last I checked, we handle lag pretty well. We can take the extra 20%.

**Comment by Exxion** [comment]
Yes, if compiling works then the extra 20% or so size isn't a big deal
I guess I'll test it out when I get the chance and see if we have the same issue they do

**Comment by Exxion** [comment]
No, we shouldn't
