### ISSUE TITLE
Mech bay chargers are too slow by default

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9449]
^

**Comment by PJB3005** [comment]
^

**Comment by Imagebard** [comment]
^^

**Comment by ghost** [comment]
I'll likely tinker up the Mech Bay chargers a bit, need to change their sprite. I'll likely change that along the way

**Comment by Probe1** [comment]
Its just a single variable don't get crazy.

**Comment by SysadminJeroen** [comment]
Keep the changes atomic.

**Comment by aceedex** [comment]
Maybe keep the same charge speed for regular ol' parts but make tier 3s a giant significant change. 
Have mechanics have a reason to upgrade the damn things

**Comment by Probe1** [comment]
Already does.  The problem is the giant charge in place (and the base charge) is really weak and only intended to be a boon to high cap cells.  Now, no roboticist is gonna use full research then just neglect to pop in a hyper or at least a super cap cell.

Then you end up with 5-10 minute charge times.  What would you rather do?  Go find a person with lathe access and get some spare cells then swap the dead cell with a fully charged one, or use the slow as mech charger?

Gotta make charging less zzzz tab out and wait.

**Comment by ghost** [comment]
I have value tweaks in place, but there's other things I changed that I need to get working

This might take a bit, especially since I'm going to be moving stuff today

**Comment by Probe1** [comment]
aged out
