### ISSUE TITLE
Examine icons for mobs are still messed up.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9451]
Before it showed a 4 way perspective of a vox.  Now it shows a human male in their boxers
![image](https://cloud.githubusercontent.com/assets/8550416/14547901/38756834-0280-11e6-9478-69a009eff79d.png)

For everybody.

**Comment by 9600bauds** [comment]
it's an improvement at least

**Comment by Probe1** [comment]
kinda.  observers still get the 4 direction vox one

**Comment by PJB3005** [comment]
Dupe
