### ISSUE TITLE
Hand of cards can be dropped to the ground and it will still retain its extremely long icon

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9452]
![dreamseeker_2016-04-14_20-59-03](https://cloud.githubusercontent.com/assets/6526157/14548501/b5e70158-028d-11e6-9949-ed76c3b38e5f.png)
i'm sure you can see the issue here

**Comment by Killette2** [comment]
I'm pretty sure that's a feature, I've seen it several times.

**Comment by 9600bauds** [comment]
Maybe to hold in your hand, but it definitely should revert to a clump of cards or something when you drop it
Otherwise, I'm fairly sure you can see the issue in the picture

**Comment by Shadowmech88** [comment]
What's the black and red bit on the end?

**Comment by 9600bauds** [comment]
I assume that's supposed to be the hand? It's all part of the icon

**Comment by ihadtoregisterforthis** [comment]
Clump of cards sound like the best option

**Comment by Killette2** [comment]
What if you drop it very softly not to scatter cards and keep your hand intact?

**Comment by 9600bauds** [comment]
Then it should look like a hand of cards where each card is not half the size of a man and which doesn't go through walls

**Comment by ComicIronic** [comment]
willfix

**Comment by 9600bauds** [comment]
didn'tfix

**Comment by nervere** [comment]
No longer an issue. Testing done by @Inorien - thanks!
