### ISSUE TITLE
Idea to improve deffs security layout

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9453]
![image](https://cloud.githubusercontent.com/assets/8550416/14548526/924bb7a0-0285-11e6-8ca0-dc3a2ded1c12.png)

**Comment by Killette2** [comment]
I bet this design will work wonderfully with those prison stools in every cell

**Comment by ghost** [comment]
Looks fair to me

Also the Kitchen needs to be properly closed with multiple windoors if it isn't already, or else you can allow someone to escape by tabling them and tailgating out of the Kitchen

**Comment by Probe1** [comment]
wow stop being so against the prisoners having weapons @killette2 #equalrights

**Comment by Killette2** [comment]
My apologies, I support this. Now would you be so kindly to put me in a western cell facing the hallway to freedom please?

And wait, is that DOORS over WINDOORS?

**Comment by optimumtact** [comment]
Why do you not have a public gallery for the rioters?

**Comment by 9600bauds** [comment]
What's the problem with the stools?

**Comment by Shadowmech88** [comment]
I feel like there should be enough wall-mounted flashers in the main area for the warden to flash everyone inside at once.

**Comment by Probe1** [comment]
Quick and dirty mapped idea

# OLD

![image](https://cloud.githubusercontent.com/assets/8550416/14548684/4504c17e-0287-11e6-85c2-f595661906c7.png)

# NEW

![image](https://cloud.githubusercontent.com/assets/8550416/14548668/07d236e2-0287-11e6-9774-440d28d2978e.png)

**Comment by chatsonf** [comment]
Like how it looks, seems like there should be doors into the area on both sides of the warden's room though, instead of just the west side

**Comment by Probe1** [comment]
@9600bauds When they were placed originally they were obj/structure/bed/stool.  to get rid of some snowflakey code, they are now obj/weapon/stool.. so the prisoners all have weapons in every cell.

@Shadowmech88 Yeah there's lots of room for fine touches, but I think overall this is it, this is how we marry deffs idea of perma with having it be accessible and safe.

**Comment by 9600bauds** [comment]
You could always pick up stools by clickdragging them to you

**Comment by Intigracy** [comment]
This means when any door is open all prisoners can escape though.

**Comment by Probe1** [comment]
They'll start bolted and I'm ok with thinking security can be competent enough to re-lock them afterwards, and access to unused cells will be limited by bolted doors.  Plus the cells already have flashers so if someone tailgates they can just get permaflashed.

**Comment by Intigracy** [comment]
You can't permaclose a timed cell's windoor though.

So your choices are to leave an escape route or throw them inside the permabrig with no bed (muh arrpee) and bolt the door behind them.

**Comment by Intigracy** [comment]
How about adding a fourth cell on the left and making all of those publically visible/no door into permabrig, and making the right side just have two perma cells with three beds each?

**Comment by Probe1** [comment]
@Intigracy its a trap to say this but I want to retain Dunys vision while still trying to make this map _work._

Here, I made you a video in action.  I didn't showcase it, but in addition to this we already have blast doors for every single cell that shut on the windoors location, accessible by the Warden

https://youtu.be/lSmw8ht1nSI

What you're thinking is what I'm thinking about right now.  Do we cut out the cells on the right side and only have the 4 on the left.  Or vice versa, do we preserve the hallway AS IS, and add 4 cells on the right side only?

**Comment by Killette2** [comment]
> Removing access to the public for prison botany/kitchen

Who do you think will feed the prisoners and grow food, the security officers? I'd have better luck praying the clown will bake me a loaf of banana bread. It's an open hallway for that reason.

**Comment by Konater** [comment]
This can be closed since I butchered the brig myself
