### ISSUE TITLE
APCs seem to just not be coded with the possibility of them having zero power in mind

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9455]
Either by having their battery run out completely or by NOT having a battery in the first place, APCs just don't realize they shouldn't even work.
They will:
- still have their red display, as opposed to something like a black screen
- still be hackable! you can make their power 'short', and unlock their controls.
- still SHOCK YOU when mending their power wire, doing zero damage but still stunning you

They probably should disengage their cover lock when they run out of power, too, so people can jam a new cell in the damn thing without necessitating hacking it anyways

**Comment by ghost** [comment]
Could be an interesting concept of an APC having an internal battery just for supporting itself. Once the main cell runs out of charge, the APC itself would start drawing from its internal cell, and should that fail, any settings such as Lights off, Atmos off, Equipment off, etc would end up being lost.

**Comment by FudgePucker** [comment]
Eh, that means it would have two cells, a back up and a back up back up.

It has an internal cell for remembering power settings and to ensure it turns back on once power is restored
