### ISSUE TITLE
Adamantine Golems can't handle the cold.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#9463]
@Shadowmech88
@DrCelt
![gl1](https://cloud.githubusercontent.com/assets/7810719/14572557/7529f0e0-031d-11e6-9129-acab48305f97.png)
![gl2](https://cloud.githubusercontent.com/assets/7810719/14572510/3429b030-031d-11e6-870d-ba0fc5c07a18.png)
![gl3](https://cloud.githubusercontent.com/assets/7810719/14572514/38baea38-031d-11e6-90e8-0c5386ada423.png)

**Comment by ghost** [comment]
ahahahaha someone didn't test this, and it's the guy who bitches at me for not testing :^) [spoiler] I think there's a species var for being hypothermic or not, use that to fix it. [/spoiler]

**Comment by ihadtoregisterforthis** [comment]
Thermal shock when

**Comment by Shadowmech88** [comment]
Actually I did test this, I simply didn't edit the PR message to reflect it.

In species.dm I set the golem body temperature to 0, and their cold damage thresholds 1, 2, and 3 to -1.
That didn't make them immune to cold, so I gave up.
I'm not a fan of the prospect of diving into hypothermia code to find out why it doesn't play nice with the species vars.

**Comment by Exxion** [comment]
@DrCelt 

> Not making hypothermia ACTUALLY USE THE SPECIES VARS

**Comment by Shadowmech88** [comment]
I see now that there's a `can_be_hypothermic` var at the bottom of `/datum/species`.
But really a species should not take damage from hypothermia if their cold damage thresholds are unreachable.

**Comment by clusterfack** [comment]
Pretty sure thats because celt just removed the cold damage thresholds or some stupid shit like that I remember asking him about months ago

**Comment by Shadowmech88** [comment]
They're certainly not removed, the vars still exist.
If he made it so that they don't do anything, he _should_ have removed them.

**Comment by 9600bauds** [comment]
But can they take the heat?

**Comment by Imagebard** [comment]
>This whole issue went the other way around and revealed it was DrCelt's fault
Again

Good job.

**Comment by ghost** [comment]
> blaming me for shadowmech

aaaaaa

**Comment by Exxion** [comment]
Except it actually is your fault, mostly

**Comment by ghost** [comment]
> he codes something
> he tests it and it doesn't work
> he adds it to the game anyway
> he doesn't use the species var for hypothermia
> I tell him that's the one he should edit
> and it's somehow my fault

:confused:

**Comment by Exxion** [comment]
> The way you used to make species immune to cold no longer works and this is not explained anywhere to anyone
