### ISSUE TITLE
ADMIN LOG: Process 'vote' may be hung.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9469]
Happened several rounds in the last 6 hours.  No one was able to vote for a new map.

**Comment by PJB3005** [comment]
I should write a guide to forcing map votes with advanced proccall.

I've done a map vote and restart due to a broken map vote 2 times now.

**Comment by Probe1** [comment]
It keeps happening.  A hack solution isn't what we need but it is a temporary workaroound
