### ISSUE TITLE
Oven and subtypes (stills et cetera) cannot be unwrenched when power is off

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9470]
https://github.com/d3athrow/vgstation13/pull/9290

All that comes up is the return 

```
   to_chat(user, "<span class='warning'> The powers off, it's no good. </span>")
        return

```

I should have tested it better and caught it.  Stills are children of what I fixed.

**Comment by Probe1** [comment]
There's something really fucked up but it isn't stills and I think biogenerators might not need power and it's time to get to the bottom of this mystery.

**Comment by Probe1** [comment]
Still can't figure out why this one still won't work in maint when it should.

**Comment by PJB3005** [comment]
It's simple, the `..()` to handle unwrenching is after the power check.

**Comment by Killette2** [comment]
> botany running out of power

I can't hear you, I'm too busy funding my glowshroom lit potato battery ran factory.
