### ISSUE TITLE
Protolathe UI

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9471]
(WEB REPORT BY: tifora REMOTE: 172.93.109.202:7777)
The order that items are listed in the design selection screen varies depending on what research level is increased first, which can result in a very disorganized menu.

The UI should sort it so it always looks the same.

**Comment by 9600bauds** [comment]
I tried doing this but the research designs and servers code in general is SUCH A FUCKING MESS you have no idea

**Comment by west3436** [comment]
Designs can be sorted alphabetically now per [32835].
