### ISSUE TITLE
[Feature Request] Emptying container while not in hand

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#9475]
Being able to empty container on a tile adjacent to you. This would be useful for the pillcollector, placing the pills right onto a table. Or being able to dump a backpack onto a table, just to name a few examples.

**Comment by Shadowmech88** [comment]
I'm not certain that the pill collector is a "container" per se.
The other stuff should be doable, probably with alt+click or some other shortcut.

**Comment by MercuryDoll** [comment]
I don't really know what's called what in the code. But with "container" i had pretty much all handheld objects in mind that you can put other things into for storage: backpacks, carton boxes, plastic bags, pillboxes, suiitcases, lockboxes...

**Comment by 9600bauds** [comment]
Click drag container into table IIRC

**Comment by 9600bauds** [comment]
Literally already exists, just clickdrag a container onto a table
Updating the Wiki to make this more clear

**Comment by ComicIronic** [comment]
The pill collector is actually just a storage item with click behaviour.

**Comment by clusterfack** [comment]
My feature saves the day again

**Comment by ComicIronic** [comment]
but where is this click behaviour documented :^)

**Comment by 9600bauds** [comment]
;^)
http://ss13.moe/wiki/index.php/Shortcuts

**Comment by clusterfack** [comment]
Wow I never put that there, thanks anonymous person
