### ISSUE TITLE
Metaclub feedback from OOC

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9478]
OOC: SolariousGabriella: It doesn't look like there's a water cooler anywhere on this map

OOC: ArchSunder: No candy machine, cant tide glubs

OOC: Boxed_I: has no round start slot machines iirc

OOC: Morena: it exists

OOC: PJB3005: it isn't 24/7

**Comment by PJB3005** [comment]
The last point is still definitely the biggest issue.

**Comment by Exxion** [comment]
But Meta is the worst map

**Comment by Probe1** [comment]
Why?

**Comment by PJB3005** [comment]
Because it isn't box, duh.

**Comment by 9600bauds** [comment]
> cant tide glubs

I don't get this part

**Comment by Exxion** [comment]
No, Box is the second worst

**Comment by Probe1** [comment]
What a madman

**Comment by clusterfack** [comment]
Is this what passes as valid issues these days

**Comment by 9600bauds** [comment]
It's practically the only way to get map feedback

**Comment by Probe1** [comment]
What he said.  I have to hound people for it and I"ll be damned if I don't record it.

**Comment by xpcybic** [comment]
Most of what I did to Taxi came from perusing the logs
