### ISSUE TITLE
Succumbing While in Crit as a Diona Does Not Kill

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9480]
I've seen other people talk about this before, but I couldn't find an issue on it.
Be diona, enter crit, succumb, get the "You have given up life and succumbed to death" message, still don't die.

**Comment by Exxion** [comment]
#7959 mentions it, but not in the title, so we should leave this open too

Also, the same seems to apply to vox with nitrogen in their system and presumably also applies to anything with dexalin in their system

They cannot get past 199 oxygen damage, _even by dealing damage with the admin panel_

**Comment by AutismSpider** [comment]
its failing to go past 199 oxygen damage any one can do eat shit ton of dex as plasma man grey or human or be hook up to iv bag of dex plus or eat lot of nitrogen pills as a vox.

**Comment by Exxion** [comment]
You know, dexalin _does_ work on vox
It's just inaprovaline that doesn't

**Comment by AutismSpider** [comment]
that's silly dexalin is made out of O2 should be poison to them

**Comment by Exxion** [comment]
Yeah, it should really probably work the other way around
Especially considering that (save for stoxin2, which is completely unobtainable) there is no equivalent for inaprovaline that works on vox, while there is an equivalent for dexalin that does

**Comment by AutismSpider** [comment]
This happen to skeletons to when they were playable

**Comment by FudgePucker** [comment]
I said in the vox medical PR that dex+ should instantly kill them.

It sets o2 damage to 0 by flooding every cell in the body with oxygen. It should cause instantaneous organ failure and cell death in vox.

**Comment by Exxion** [comment]
That would be fine if and only if there is an equivalent for it that works on vox
Dex+ is too necessary for current medbay practices to make it unusable on an entire race

**Comment by PJB3005** [comment]
@FudgePucker an instant kill is OP though. 

Also I did make a PR to make Vox inaprov and dex on GitLab, I should fix that.

**Comment by Exxion** [comment]
Nitrogen is already a straight upgrade from dex for vox

**Comment by Intigracy** [comment]
Nitrogen should just serve both purposes.

**Comment by Exxion** [comment]
Honestly, nitrogen for vox is already pretty overpowered
Dexalin that also heals toxin damage and metabolizes 20 times slower

**Comment by Intigracy** [comment]
Why does it heal toxin damage?

Breathing it doesn't.

**Comment by Intigracy** [comment]
Nymphs or People?

**Comment by Exxion** [comment]
No idea, but it does
It lets you walk around without internals... usually
There's something weird with tickrates and sometimes it heals slightly faster than you take damage, sometimes slightly slower
