### ISSUE TITLE
YOU CANNOT CONTAIN THIS

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9481]
1. Pick up a walking mushroom (activated) with both of your hands
2. They will constantly walk out of your grip, even if there's no other mushrooms around
3. There is no easy way to contain your champion fighter walking mushrooms
4. Also nobody knows mushrooms can level up by eating other mushrooms, which is why nobody does trained mushroom fights

I want a way to carry around my mushroom that isn't a locker, and I can't even do that with my hands because they run away.

**Comment by Probe1** [comment]
nevermind you can't put them in your backpack

also if you try and cheat by injuring one of the other mushrooms to make sure one wins the game shits on it.  I forget how.

**Comment by Exxion** [comment]
As I recall, you just don't get levels for pre-damaged mushrooms

**Comment by AutismSpider** [comment]
no levels if the mushroom has damage

**Comment by 9600bauds** [comment]
Can you not just like
locker them

**Comment by Probe1** [comment]
`Unwield the walking mushroom first.`

ok so you can't bag them.  that should be an easy solution.

**Comment by Exxion** [comment]
Why not just not let them walk out of your grip?

**Comment by Blithering** [comment]
Cages?

**Comment by Probe1** [comment]
Cages.

**Comment by Killette2** [comment]
> Your mushroom is caged
> Cages cost fucking plasteel in the first place
> Other mushrooms will be able to chomp your caged/locker mushrooms due to mob code unlike the invulnerable caged carbon

Not fixing it. When do we get lazarus tier capsules for them?

**Comment by AutismSpider** [comment]
oh should be easy to recode the lazarus capsule to hold one mob type just needs new icon and stuff

**Comment by Killette2** [comment]
That sounds like a good idea, wonder if it's been thought of before...

https://github.com/d3athrow/vgstation13/issues/3156

MAYBE THIS IS THE REASON I KEEP PUSHING THAT OLD ISSUES OR REQUEST SHOULD NOT BE ABANDONED AND FORGOTTEN

**Comment by 9600bauds** [comment]
> Hmmm this idea is kind of shitty looking back. 
> 
> Killette2 closed this on 18 Mar

**Comment by Intigracy** [comment]
No, the reason you keep pushing that old feature requests not be abandoned and forgotten is because most of your feature requests fall under that category.

Because you make so fucking many.

**Comment by Killette2** [comment]
name 1(ONE) thing wrong with the following feature request. Specify which request is bad, and why. Also do it on the request itself, not here jackass.

https://github.com/d3athrow/vgstation13/issues/7213
https://github.com/d3athrow/vgstation13/issues/7167
https://github.com/d3athrow/vgstation13/issues/6202
https://github.com/d3athrow/vgstation13/issues/3153

And even botany3 didn't fix that last one, unless you can point out in the code a single change botany3 did to hydro gloves, that issue is still not only a request, but a gameplay issue.

**Comment by nuklearcellphoneg** [comment]
@Killette2 Code it.

I have a bunch of dead requests as well. :(

**Comment by Killette2** [comment]
Code being able to own pet walking mushrooms? I wouldn't even know where to begin with a simple mob that you can't carry in your hands because they constantly walk out of your grip.

Not to mention, walking mushrooms should be called a complex mob because there's so much to them such as attacking other walking mushrooms exclusively, eating their corpses, and leveling up from eating their corpses. How am I supposed to make a way to contain them without it messing up something like their level or current health?

**Comment by nuklearcellphoneg** [comment]
I-I dunno those other guys had good ideas.

**Comment by Killette2** [comment]
The capsule is the only reasonable idea, because due to mob code they will be able to be attacked in lockers or cages by other mushrooms (see trying to hide form a viceraptor or space carp in a locker), and I pointed out I made the same capsule request about a year ago.

But if you want the capsule thing rather than being able to carry them go for it. I just want a way for them to be containable, whatever the workaround need be.

**Comment by Blithering** [comment]
I now want viceraptors to be a thing.

**Comment by west3436** [comment]
Covered cages are a solution here - no other options have been proposed since issue creation

**Comment by Blithering** [comment]
8 years on, still no viceraptors.
