### ISSUE TITLE
whop whop someone forgot to remove some DEBUG OUTPUT

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9482]
![image](https://cloud.githubusercontent.com/assets/9827785/14585099/6ec00f6e-0435-11e6-871f-0f2724e19be0.png)

@CptWad was an Adamantine Golem and committed suicide with the Wand of Destruction and this happened.

EDIT: The issue is golems, not the rod
@Shadowmech88

**Comment by clusterfack** [comment]
watafak

**Comment by Exxion** [comment]
![image](https://cloud.githubusercontent.com/assets/9827785/14585133/1e6f9e24-0437-11e6-9080-eef809b8b050.png)

**Comment by Shadowmech88** [comment]
Well shit, I didn't see this ANY of the times I've killed golems since merge.
I'll add it into my current golem fix PR.

**Comment by Probe1** [comment]
GIRTHY

**Comment by ghost** [comment]
I can confirm it happens, please fix post-haste
