### ISSUE TITLE
Airlocks with no power still play the access denied sound when someone with no access bumps into them

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9484]
Expected: Nothing

Got: EH-EH

Also, there's only one airlock opening animation and it has the green airlock lights visible, so if you crowbar open a power-less airlock it will still have green lights despite having no power (muh immulsions)

**Comment by Exxion** [comment]
Do they still flash red, too? I forget. I seem to recall that was fixed a while back, but maybe I just stopped noticing it or something

**Comment by ihadtoregisterforthis** [comment]
There are two opening animations, with panel open and panel closed. Some doors don't have lights when opened without panel and some do. And then there are some that have a closing animation with red lights.
Could they use those fancy overlays instead of a set of sprites for every option?
