### ISSUE TITLE
Early Vox Trader feedback.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9489]
[12:21:11] Armin PM to - Got any immediate feedback on traders so far?
[12:21:23] Player PM from-Shamzie: Not really.
[12:21:55] Player PM from-Konater: Other than map issues I'm having fun
[12:22:26] Player PM from-JJKoshane: Pretty neat, I like how they're setted up to be potential allies to the station along with enemies if the right kind of antagonist comes along.  I suppose the only thing to complain about is the hill you have to climb to obtain materials and resources given your somewhat restricted situation but then again that's a part of the fun.
12:21:11] Armin PM to -  Thanks guys.
[12:23:04] Player PM from-JJKoshane: No problem.
[12:23:24] Armin PM to-Konater/: Oh what were the specific map issues?
[12:24:17] Player PM from-Konater/(Chachakiyati): No grinder for flour, lack of components, no access to vending machines 
[12:24:48] Player PM from-Konater/(Chachakiyati): Also apparently a lack of metal assuming these guys didn't throw it away

Personal notes:

++ ADD FERRY SO THEY CAN DOCK AT FERRY DOCK TO TRADE @ STATION
++ ADD CONSOLE TO CALL FERRY; ORDER ITEMS?? 
++ PASSWORD LOCKED GIVE TRADERS PASSWORD IN NOTES AT ROUNDSTART LIKE TRAITOR MODE
++ DEVISE CURRENCY SYSTEM FOR TRADERS
++ CO-OPT REQUESTS CONSOLE FOR TRADE REQUESTS.

@unid15 
I don't expect you to do any of this but I thought you'd like to hear it.

I'll keep scrounging for feedback.

**Comment by icantthinkofanameritenow** [comment]
Here's one.

Give them something actually worth trading for. Everything they can come up with is stuff that can be found on the station easily or isn't worth trading for.

Also, if vox get their own job, every race ought to get a unique job only they can be. Otherwise it's just race favoritism.

**Comment by Probe1** [comment]
More feedback from OOC.

**Skowron**: it's up to the player, and the others playing

**Icantthinkofanameritenow**: hell, there's nothing even worth trading for that can't be found on the station.  sure, you could go and look for vaults...but good luck even finding one before your internals run out now.  i also don't se what's gained by making traders vox only.  When I see a job with less access than assistant and an expectation to roleplay on a server whose first response to RPing is "gb2Bay", there's obviously something fucked up.  just look at IAAs. were it not for the occasional fax, they'd be greyshits with suits.  i also don't se what's gained by making traders vox only

**KingcrimsonIJW**: dunno, shops have worked in the past.  thing is iaa's affect the round.  not traders for now.  if it doesnt break anything no need to take it out

**Sarah Johnson**: Traders only need some improvement and they can contribute

**KungFury**: Just provide a seperate ID/access system for their outpost

**SomGuy**: I've seen some on-station shops go startlingly well  but they were all run by clowns

**Jubisloviu**: vox traders is yet another memejob to entertain closet furries

[18:48:43]VOTE: Custom vote started by Probe1.<br>How has your experience been with vox traders so far?
[18:49:45]VOTE: <b>Vote Result: I haven't encountered or played as one so I can't say with 15 votes</b><br>  Positive had 5 votes<br>    Negative had 3 votes<br>    Indifferent had 3 votes

**Comment by Probe1** [comment]
@icantthinkofanameritenow its hardly favoritism to ship the vox out of the station, strip them of their rights as crew, and force the players to play non humans.

**Comment by clusterfack** [comment]
Maybe it would be more fair if we gassed them while we were at it

**Comment by ihadtoregisterforthis** [comment]
It's more of a race flavoring and LORE continuation than favoritism. They have a functional vox outpost and nothing spawns there, and the idea of having vox there sounded nice.
If there was some sort of grayy exploration ship it would make sense if a few of them hydrophobics started in there.

> implying IAAs aren't assistants with shades

**Comment by icantthinkofanameritenow** [comment]
@Probe1
That would be true...if this was in fact the only job Vox could take other than raiders. Anyone can tell that definitely isn't the case unless you're willing to upset a lot of people.

**Comment by PuglifeINSPESS** [comment]
Loving vox traders so far. What I think traders need is a reliable way to get about, a bargaining chip (or an easier way to get that chip than the station's crew would have) and maybe a smelter so they can compete with the miners on the roid.

**Comment by SerWind** [comment]
When I originally heard there was going to be Vox traders I figured there would be some sort of ship they would get. Maybe something that would start as ghetto, or not even functional, that they could build on or build up. Fits the theme of scavengers, in my opinion. I didn't even think they would start on the Vox station. I like the idea of a rickety ship floating through space, and them begging, bartering, or stealing whatever they need to get things built up.

Now if you want to get into really crazy idea guy territory it would be cool if they had their own unique place they could visit with unique Vox shit. Like has been said, they don't have anything people really need/want. They find the most use on low pop it seems, when jobs like miner aren't being filled, but then on low pop the need for that isn't really that high.

**Comment by carshalash** [comment]
I'd say give them boards that will let them set up an autolathe and R&D, that way they can get more trading going on.

**Comment by jknpj** [comment]
Do they have pickaxes? Selling ore and trash to the station(if there's no miners) or even to miners(Diamond/Phazon/Bananium/Spur/Happiest Mask/Alien Guns) seems like a great way to get by. They also need a reason to not raid the the research outpost. It's really annoying to have the chem-dispenser plus xenobotany stuff stolen every single shift.

**Comment by carshalash** [comment]
Also, maybe changing the access for the mining outpost to make it so the vox can smelt things might be a good idea, with that and the ferry they'll be able to reasonably get some materials ready, go trade at the station and start their monopoly on whatever the fuck they want since they'll then have materials to actually make shit and just trade the materials themselves. 

The only big issue I can think of is miner vs bird fights since their jetpacks give them an advantage of getting diamond from the sweetspot on box.

**Comment by 9600bauds** [comment]
I've seen these people get REALLY rowdy with miners.

**Comment by carshalash** [comment]
Yeah. The last day has made my comments about access to mining access stronger. If they have actual access to it they cant greytide and break everything like dipshits. That and it would be really nice for parameds only being needed to be let into the shuttle station side

**Comment by Probe1** [comment]
This is, _unfortunately_, probably part of the trial and learning phase where people find and push the limits.  While we can certainly rework (every maps) mining outpost or more sanely, give the trade outpost things to dissuade them, we should evaluate and not make a quick reaction to a problem that we haven't fully seen yet.

**Comment by Blithering** [comment]
Having now played my first round of trader, two things spring to mind. 
1) The alternate titles for traders are kind of pointless, as there's no ID or crew manifest to reflect them.
2) Changing the empty wallets that they spawn with to wallets with the usual chance of coins and credits would give them some much needed early cash to splash and get the trading thing rolling.

**Comment by 9600bauds** [comment]
I'm gonna have to repeat https://github.com/d3athrow/vgstation13/issues/4616 here
Those brown diver suits are deceptively, extremely good
A Vox in one of those can eat two, maybe three shotgun shells and not even bleed out from it

**Comment by SerWind** [comment]
Rational and deliberate action? NEVER. REMOVE IT NOW REE
