### ISSUE TITLE
We have no addictive substances, here is an example

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9491]
Here is the code for nicotine

---

/datum/reagent/nicotine
    name = "Nicotine"
    id = "nicotine"
    description = "A highly addictive stimulant extracted from the tobacco plant."
    reagent_state = LIQUID
    color = "#181818" //rgb: 24, 24, 24

---

 that's all, no addiction, no overdose, it's a useless flavor chemicals. We've been asking for addictive and hardcore drugs for a while, how can we fuck this one up?

**Comment by Probe1** [comment]
chemistry in general is a shitheap.  people kept removing overdoses and replacing them with nothing and now we have this casual shit.  
![dumpster-fire-214x300](https://cloud.githubusercontent.com/assets/8550416/14590062/8f3c19ce-04bf-11e6-8f73-985d4e98b5c3.jpg)

**Comment by Shadowmech88** [comment]
Creatine is "addictive" in a way; the symptom of withdrawal is death.

**Comment by Brolaire** [comment]
nicotine should give you the itch and pus-filled boils if you dont smoke it. also skin flakes

**Comment by Exxion** [comment]
I have a number of ideas for making chemistry more interesting, but honestly none of them are possible without completely rewriting reagents, which is not something I (or really probably anyone else) have the patience to do

**Comment by Iamgoofball** [comment]
okay here's a kicker:

port /tg/'s chemistry **backend**

it has qdelling reagents, a PROPER overdose system, a PROPER addiction system, and general code improvements/optimizations that the bay/vg coders didnt ever bother porting

it also strips out all the really useless realism backend shit that has never been useful ever and serves to add Complexity(tm) for ??? reasons

**Comment by Probe1** [comment]
he may be right about a bit of that.

**Comment by Exxion** [comment]
> qdelling reagents

But reagents are datums
How the fuck can you qdel them?

**Comment by Iamgoofball** [comment]
we added datum qdelling at tg

**Comment by Intigracy** [comment]
goofcode and goofchem are bad go away

**Comment by Iamgoofball** [comment]
have you actually looked at it or are you just operating off of "its goofball"

**Comment by PJB3005** [comment]
@Exxion we've had datum qdelling for ages now. The only reason you initially couldn't was because whoever wrote the GC didn't understand references correctly.

**Comment by Exxion** [comment]
Oh
I'm pretty sure the code still says only movable atoms

**Comment by PJB3005** [comment]
Where, then? #5829

**Comment by Exxion** [comment]
I'll check later when I can

**Comment by Exxion** [comment]
Oh, OK, I remembered incorrectly
It doesn't say only movable atoms, it just says no atoms other than movable atoms and then doesn't mention datums
