### ISSUE TITLE
Silicon module cancel button locks players out.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9492]
#### Description of issue

-JJKoshane I selected the miner module on accident as I intended to select medical, icon prompt came up, I pressed cancel as I thought MAYBE it'd allow me to rechoose my module, then I was stuck.  
#### Difference between expected and actual behavior

Several silicons recently have hit cancel while rechoosing a module.  This has left them in a state where they cannot move or reselect a module.  It should let them pick again but instead locks them in a state where they cannot move or change modules.
#### Steps to reproduce

Become a mob/silicon/robot
Choose a module
Hit cancel
#### Specific information for locating

/mob/living/silicon/robot
#### Length of time in which bug has been known to occur

At the very least 2 months.
#### Server revision

327d30b4467d0c433dd845d87b8c600f01811388 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Imagebard** [comment]
#7001

**Comment by Probe1** [comment]
fix 
it

reeeeee
