### ISSUE TITLE
New engine concept: photon engine.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9494]
So I had a neat idea for an engine once, I'm probably never coding it and I'm really vague on the specifics for what it would be. 
#### Pseudoscience I came up with:

NT scientists have figured out a way to make bluespace tunnels. Basically pipes in which the laws of physics differ. It is possible to decompose certain molecules by accelerating them to near light speed inside such a tunnel. The molecules get ripped apart and turned back into energy with bluespace magic. This process shall be called "photonization" (I needed a name shut up)

This effect only works on molecules which are not stable enough (CO<sub>2</sub> and N<sub>2</sub>O), and it essentially allows for the ability to turn matter back into energy.

The issue is that the energy cost of accelerating these molecules to light speed in a bluespace tunnel takes more energy than can be harvested, so it is not viable for energy production.

That's where plasma comes in.

Plasma is stable enough to stay accelerated inside a tunnel for extended periods of time. Plasma creates a literal shitload of CO<sub>2</sub> when burned. When plasma is accelerated into a tunnel along with O<sub>2</sub>, and the burn reaction happens inside the tunnel, the potential energy output is orders of magnitude higher than burning plasma in a regular burn chamber. This is because all the CO<sub>2</sub> produced in the reaction does not go to waste but instead turns into energy.

However tunnels come with risks. If the energy in the tube drops too low the tube will break, spewing PLASMA AT THE SPEED OF LIGHT everywhere. If there is too much energy the tunnel will be unable to contain the energy, and you'll be basically breaking our laws of physics as we currently know them and you'll get problems, including PLASMA AT THE SPEED OF LIGHT.
One of the reasons it is possible to accelerate molecules so close to the speed of light they photonize is due to the "perfectness" of a bluespace tunnel. Too many unstable molecules (CO<sub>2</sub> and N<sub>2</sub>O) will cause entropy and result in bad things.

The result is an engine that requires maintenance, has a SHITLOAD of energy output, and hopefully has a _very_ high skill ceiling.
#### Practice

The heart of the engine will be a single controller unit. It creates and holds the bluespace tunnel holding the photonization process.

The tunnel will behave like a beam, bouncing of (specialized) mirrors and going through (specialized) splitters and (specialized) prisms.

On the beam there will be machinery to use the bluespace tunnel.

The tunnel will have a couple of properties:
- **Plasma**: Accelerated plasma moles in the tunnel.
- **Energy**: Energy in the tunnel, needs to be proportional to the amount of plasma.
- **Unstable molecules**: Amount of (CO<sub>2</sub> and N<sub>2</sub>O) moles in the tunnel which are not yet photonized.
- **Entropy**: instability in the tunnel, caused by an excess of unstable molecules.
- **Resistance**: resistance due to entropy or machinery. Causes loss of energy.

The amount of energy should be proportional to the amount of plasma and unstable molecules. Failure to do so will result in tears, bluespace anomalies, fires, GIANT PLASMA LASER BEAMS, and more!

Unstable molecules get converted into energy. The more energy currently in the tunnel the faster.
Entropy is made by presence of unstable molecules. The more entropy in the tunnel, the more resistance from all sources and lower power output.

There will be 2 types of machines to use on the tunnel, the tunnel will pass through them and get effects.

Both machines take a gas tank which controls their effect. They will slowly consume the gasses by % causing the mole usage to drop over time, which is why the engine needs monitoring & maintenance.
##### Flux buffer:

Generates power and creates resistance in the tunnel.

It uses plasma, magnets, bluespace, whatever to achieve power creation and energy loss in the tunnel.

The output is dependent on the amount of moles taken in (which as stated previously, will slowly decline). The output curve takes the shape of an upside down parabola: ![](https://d32v6r6fgi4k49.cloudfront.net/images/algebra/alg_fn_nonlin_narr_graphik_11.png)

The resistance graph however will be linear, with more plasma equaling more resistance.
##### Gas accelerator

Injects or uses gasses (in)onto the tunnel. The effect is determined by the type of gas. All effects take tons of power.
- Plasma: Adds plasma to the tunnel.
- N<sub>2</sub>: Artificial resistance for managing the energy level of the tunnel.
- O<sub>2</sub>: Reacts with plasma in the tunnel to create unstable molecules.
- CO<sub>2</sub> / N<sub>2</sub>O: Adds unstable molecules directly, but not in redeeming amounts. Should be used to kickstart the engine or to prevent low energy problems.

The general idea is to keep your engine at stable energy levels, prevent entropy and monitor for problems before they spiral out of control.

**Comment by Killette2** [comment]
As I would shit on you for making such a request involving plasma infused emitter beams, it's a new engine idea and we all desperately crave a new engine. This gets a free pass.

But after reading this whole post I'm still confused.
What does this engine take as fuel, energy, plasma, or both? Plasma in what form?
Can this engine run indefinitely like a TEG hooked up to gas miners or a SMES set up properly?
What does plasma have to do with bluespace?
Which drug were you on when this idea came about?
This raises so many questions

**Comment by Exxion** [comment]
First, let's unfuck beams.

**Comment by Killette2** [comment]
What do you mean?

![bugemitter](https://cloud.githubusercontent.com/assets/5169310/14597516/2d91909e-051b-11e6-8cf1-25a564f1ed4e.png)

**Comment by PJB3005** [comment]
Rewrote the OP after thinking about it for a day.

**Comment by ghost** [comment]
Still wanna see some antimatter collectors, so we can keep the AME fuelled just with station-side equipment

**Comment by Exxion** [comment]
Also, before we get a new ultra-high-power engine, we need something to consume all that power

**Comment by ghost** [comment]
And somebody to fix the broken TEG

**Comment by Killette2** [comment]
Who says it has to be an engine to consume wats? Tesla coil when? Coil chains, set to zap people?

**Comment by PJB3005** [comment]
@skullyton I did though.

People are seeing it as controversial though...

**Comment by ghost** [comment]
@PJB3005 Nobody has been able to set it up yet, we've had Sarah Johnson and Angelite working on it, and they got nothing but angry words and numbers regarding the subject.

![Holy shit](http://i.imgur.com/1ndpU1r.png)

All those pipes, and it still fucked up

**Comment by PJB3005** [comment]
#8771 
Also what the hell are these retards trying with volume pumps, those are useless.

**Comment by Kurfursten** [comment]
You frequently call other people retards for not being able to work the engine only you can make work because you coded the current form. Why don't you write the wiki article? Didn't I ask you to write the RUST article 6 months ago?

**Comment by PJB3005** [comment]
Oh, you did but I never got around to it.

Whoops

**Comment by Killette2** [comment]
Should I touch the TEG? I'd be rising from the atmos grave but I've been around long enough.
