### ISSUE TITLE
Remove GoonChat autokicker

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9496]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
I leave for 5 minutes to use the bathroom and I am kicked from the game.
I alt tab waiting for something to happen in game for a minute or two, I am kicked from the game because it thinks I am AFK.
At best, our server gets 60 people during the summer.
We have no need for this useless, annoying feature.
Please remove it.

**Comment by Shadowmech88** [comment]
I've noticed the message that says you're either AFK or disconnected, but I've never had it actually kick me for being AFK before.

**Comment by clusterfack** [comment]
I know of no such feature, especially not one in goonchat

**Comment by clusterfack** [comment]
Talked to xenovix he's just retarded
