### ISSUE TITLE
Goonchat ping for afk is spamming href logs, produces false "You are afk" messages, and is just all around wasteful.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9499]
#### Description of issue

href logs look like this

```

00:49 Killmaster851 (usr:Killmaster851) || _src_=chat&proc=ping
00:49 Artyom177 (usr:Artyom177) || _src_=chat&proc=ping
00:49 Deity Link (usr:Deity Link) || _src_=chat&proc=ping
00:49 Konater (usr:Konater) || _src_=chat&proc=ping
00:49 Xpcicyn (usr:Xpcicyn) || _src_=chat&proc=ping
00:49 Yred (usr:Yred) || _src_=chat&proc=ping
00:49 Knife-28 (usr:Knife-28) || _src_=chat&proc=ping
00:49 Vladorf (usr:Vladorf) || _src_=chat&proc=ping

```

```

                                                         Profile results (total time)
Proc Name                                                                                      Self CPU    Total CPU    Real Time        Calls
------------------------------------------------------------------------------------------    ---------    ---------    ---------    ---------
/mob/Stat                                                                                         1.796        1.803     7153.926       111996
/mob/living/carbon/human/Stat                                                                     0.193        1.099     3436.730        54727
/datum/chatOutput/proc/pingLoop                                                                   0.001        0.001     2137.519           27
/mob/dead/observer/Stat                                                                           0.046        0.674     1556.061        24445
/mob/new_player/Stat                                                                              0.016        0.173     1291.229        18946

```

Its causing people to get AFK notifications without actually being AFK and shitting up the logs.
#### Difference between expected and actual behavior

src = chat&proc=ping to not run every second

proc=ping runs every second
#### Steps to reproduce

Open href logging http://game.ss13.moe/logs/2016/04-April/17-Sunday%20hrefs.htm and have a look
#### Length of time in which bug has been known to occur

Since whenever goonchat was added
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
Just remove it and hope that output catching is added so we can use BYOND's built-in disconnect detection
Alternatively, we can attempt to make disconnect detection that actually works

**Comment by liltiptop** [comment]
I vote for just removing it. It just detects whether your sprite isn't moving for a bit, so if you sit in a chair or something, it'll say you're afk.
