### ISSUE TITLE
Check Antag was listed twice in this prayer 4noraisen

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9500]
#### Description of issue

   PRAY (DEITY:Space Jesus): icychocobo/(Plant Person Epsilon) (?) (PP) (VV) (SM) (JMP) (CA) (SC) **(CA):** Great Word of the Wood, your actions great and noble. Please deliver  subject from his confinement aboard this strange and lonely area, and bring him to a greater place.
#### Difference between expected and actual behavior

(CA) (check antagonists) only to be listed once.  

It was listed twice.
#### Steps to reproduce

become a diona nymph(?), pray, check.
#### Specific information for locating

/mob/living/carbon/monkey/diona

**Comment by NigglyWiggly** [comment]
Are you sure that's not just the   ｃａｎｃｅｒ  button?

**Comment by Probe1** [comment]
Yea I checked by pressing it

**Comment by clusterfack** [comment]
Never seen it happen since
