### ISSUE TITLE
Metaclub Deathsquad spawning is probably broken

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9503]
Play on meta club

Try to spawn in a death squid

Watch as the players get the prompt, click yes and fill deadchat with joy, and then have a death squad not appear.

The spawn points are probably broken.

**Comment by mrpain666** [comment]
Hell, check the other maps while you're at it too.

**Comment by Probe1** [comment]
Werks on my machine.  I was in that round however and did witness it fail to work.

![dreamseeker_2016-04-24_21-25-07](https://cloud.githubusercontent.com/assets/8550416/14771794/0a475e00-0a63-11e6-9771-548706b75a50.png)

**Comment by Probe1** [comment]
Tested again, same results.  Seems like there was a broken controller or some bullshit IN THAT SPECIFIC ROUND.

**Comment by mrpain666** [comment]
Im going to close this. Re open this if it happens again, someone.
