### ISSUE TITLE
It would be nice if admins were alerted if/when a spawned death squad actually spawns

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9504]
Title says it all. It would be nice if we were given an alert and a log line when they actually spawn in.

Maybe even one when they leave Centcom.

**Comment by Exxion** [comment]
They can't even leave CentComm without admin intervention, can they?

**Comment by PJB3005** [comment]
Don't you mean ERT?

**Comment by mrpain666** [comment]
@exxion which is why I'd like the alert
@PJB3005 Squids and ERTs, sure

**Comment by PJB3005** [comment]
But deafsquids can't spawn without admins can they?
