### ISSUE TITLE
Positronic Brains

### ISSUE THREAD

**Issue by SerWind** [d3athrow/vgstation13#9505]
Maps should either start with 1 or 2 more positronic brains or the requirements should be scaled back on making them. 

Starting with 1 or 2 more is probably the better idea as this is only really an issue during smaller pop when you may not have the means to get that sweet sweet guld, and there's only really going to be a couple of people looking to borg it up. 

Also I'd like to suggest borgs be a late join possibility. Potentially in a bayby tier way where the flavor text is they were "pulled from storage". I'm sure we have a reason why we can't do this so i'm curious about it but nonetheless I still think it's a good idea.

**Comment by Ephx1** [comment]
> Also I'd like to suggest borgs be a late join possibility.

One less thing for roboticists to do. At that point all they would be doing is upgrades, mechs, and maybe one AI. They would be unnecessary, just join up as a borg.

**Comment by Probe1** [comment]
I'm ok with adding another positronic brain, and even bringing their material costs closer to MMIs (but still more expensive as they function differently), having late join borgs is silly.

**Comment by ihadtoregisterforthis** [comment]
Two posibrains on the same place sounds cheap.
A second pre-borgcube could be on science storage if the map has one, or the RD office where it can be easily reached by forcing every window with ease.

**Comment by SerWind** [comment]
I was actually going to suggest that if two more were added they could be placed around. Say one like you suggested in the RD office, and maybe one on the research station or even on the bridge. 

The one is clearly a freeby, the others should maybe require some level of knowledge, or even communication amongst players.

I didn't think late join borgs would fly but figured I'd see what people had to say anyway.

**Comment by Ephx1** [comment]
The only late-join synthetic role I'm fine with is AI, and even then only if an empty core is not filled.
Make an empty core -> Someone can join up as AI
Empty roundstart AI core -> Someone can join up as AI
These are fine, but otherwise no thank you.

**Comment by jknpj** [comment]
Maps already start with one

**Comment by Ephx1** [comment]
Reading is fun.

**Comment by jknpj** [comment]
Reading is for fags

**Comment by DamianX** [comment]
Latejoined borgs were tried and failed.
I don't see the point in adding another positronic brains to all maps and no one brought anything up for two years, so.
