### ISSUE TITLE
Plasmamen are blinded by plasma

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#9506]
Rarely does a plasmaman leave their soft portable atmosphere but when it does it can go blind without proper gear. And I doubt they are a naturally blind ~~race~~ _ethnicity_ like moles.

Also reproduced #9314 and it is better than complete blindness but it spams a lot.
- [X] Issue happened in a recent (less than 24 hours ago) round

**Comment by NigglyWiggly** [comment]
> And I doubt they are a naturally blind race like moles.

Well to be fair, Plasmamen aren't really even a race

**Comment by Kitfox88** [comment]
niggly das racist

**Comment by ihadtoregisterforthis** [comment]
_mein headcannon_
