### ISSUE TITLE
Shower doesn't properly update hand icons, meaning you don't lose the bloody hands

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9507]
This is only a sprite issue, but since bloody hands are cosmetic-only as it stands, this means you run around with bloody hands until you use a sink

It's a very easy fix, that I'm not focusing on because of other things, someone else can take a look at it and quickly figure it out from looking at, say, sink code, which works in that regard

**Comment by Exxion** [comment]
Bloody hands aren't cosmetic-only
It shows up on examine if you aren't wearing gloves/a hardsuit
