### ISSUE TITLE
Make hallucinations change client.color 

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9510]
Seriously imagine RGB->BRG.

**Comment by Exxion** [comment]
Would a cycling filter be possible? Like a smoothly sliding hue adjustment

**Comment by ihadtoregisterforthis** [comment]
For those who can't seriously imagine it
![rgb to brg](https://cloud.githubusercontent.com/assets/13305885/14621591/61b2cff8-059a-11e6-9ff6-2c37d09b5e4a.png)

**Comment by PJB3005** [comment]
Probably? I don't know much about  HSL/HSV though.

**Comment by Intigracy** [comment]
Sure, why not.

It already makes your client.dir change directions, as well as messes up your HUD with different colors.

**Comment by SkowronX** [comment]
i feel it

**Comment by unid15** [comment]
Maybe a separate drug that fucks with the colors. And when it wears off, you slowly start going colourblind until you get another hit

**Comment by ghost** [comment]
I can make this.

**Comment by nuklearcellphoneg** [comment]
Yes please, this is fairly realistic.
