### ISSUE TITLE
Bibles can fit crabs inside them

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9512]
#### Description of issue

Apparently simple mobs that are picked up can fit inside Bibles secret storage.
#### Difference between expected and actual behavior

There's a crab inside the bible.
#### Steps to reproduce

Get a crab and j-j-jam it in. 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Shadowmech88** [comment]
simple_animals have defined sizes.
How large was the crab? Did it require two hands to hold?
If not I don't think it's _too_ unreasonable that a crab could fit inside a bible.

**Comment by Probe1** [comment]
w_class 1

**Comment by Shadowmech88** [comment]
Do larger animals like corgis fit?

**Comment by Exxion** [comment]
Can't test that because corgis are musttwohand
But yeah, I don't see the problem here

**Comment by Shadowmech88** [comment]
You can't put things in a bible's inventory without holding the bible?

**Comment by Exxion** [comment]
You can't put things in any inventory while they're wielded
Items with musttwohand cannot ever be put in any inventory

**Comment by 9600bauds** [comment]
What a wonderfully specific bug

**Comment by Imagebard** [comment]
What a wonderfully normal mechanic.
I say it should be kept in.

**Comment by Intigracy** [comment]
It's because w_class = 1.

It also fits in your pocket.

I see no issue here.

**Comment by ihadtoregisterforthis** [comment]
Feature.

I bet you can cram a large rat king in there whole.

**Comment by ghost** [comment]
Fit in a baby carp

**Comment by FudgePucker** [comment]
Crabs can fit in the bible
CAN'T EXPLAIN THAT NOW CAN YOU ATHEISTS?

**Comment by unid15** [comment]
sounds like a fine feature

**Comment by NigglyWiggly** [comment]
Please do not fix this sounds like a great thing.

That said maybe the crab sprite should be made smaller because right now it's a fucking huge crab

**Comment by Shadowmech88** [comment]
The standard crab is huge, but there exist other, smaller crabs.

**Comment by clusterfack** [comment]
Snibbidy snip

**Comment by FudgePucker** [comment]
MoMMi nest needs a pet crab called CE

**Comment by Exxion** [comment]
But MoMMIs wouldn't be allowed to interact with it

**Comment by ihadtoregisterforthis** [comment]
What about a plush?
