### ISSUE TITLE
advanced prosthesis eyeballs

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#9520]
#### Description of issue

it seems that there is no difference at all between regular eyes and advanced prosthesis eyeballs.
after i got them i ahelped and the mod said me that is supposed that you can see in the dark with them, but it's just the same; the light you see in the picture is the PDA.

![advanced prosthesis eyeballs](https://cloud.githubusercontent.com/assets/6170726/14637363/0e634926-0631-11e6-80be-5de4dc3f8891.jpg)
#### Difference between expected and actual behavior

that there was a difference between eyes and advanced eyes
#### Length of time in which bug has been known to occur

i saw this today.
#### Server revision

700abd1e8f462176e4518d512289865e1f58b913
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
It improves night vision (How opaque blocks of shadow are)

Or at least it should

**Comment by PJB3005** [comment]
Are you sure your monitor isn't just really dark?

**Comment by uazuaz** [comment]
well, the darkness i saw using advanced eyes is just the same darkness i see with normal human eyes.
by the way, it should be easy to test, let someone transplant advanced eyes on you and see if the darkness is the same for you.

**Comment by PJB3005** [comment]
Can you retest this but put on mesons?

If you can see further with the mesons + prosthetic eyes then yes it works and your monitor is just too dark for you to notice it.

I checked with ShareX and there's colour in the tiles you wouldn't be able to see without prosthetic eyes.

**Comment by ihadtoregisterforthis** [comment]
I doubt how much can the monitor brightness affect a straight screenshot.

**Comment by PJB3005** [comment]
@ihadtoregisterforthis it doesn't, which is my point.

If the prosthesis eyes were actually broken, the pitch black area would be #000000, but they aren't.

![](http://i.imgur.com/Ymk9uxE.png)

**Comment by uazuaz** [comment]
i'm not sure i understood what you mean; as far as i know, darkness was changed some time ago and there is not a "pitch black zone" anymore, even tunnels without light have actually a little bit of light.
the testing server is down and i can't do proper tests now, tomorrow i will do another screenshot with normal eyes on the regular server for comparison.

**Comment by PJB3005** [comment]
The way soft lighting works is like this:

Every tile is at least somewhat lit up. However if the tile is not in your `see_in_dark` range (for humans 1, gets increased by prosthetic eyes which is why they work) it'll actually be invisible to you.

If you are in range it's visible, but it might be hard to impossible to see depending in your monitor / brightness.

**Comment by Shadowmech88** [comment]
Oh, so does that mean other people can't see your halo of visible tiles?
I've always been concerned about hiding in the dark due to the fact that it looks like I light up nearby tiles a little, even with no lights on me.

**Comment by PJB3005** [comment]
Nope, they can't.

**Comment by uazuaz** [comment]
here another screenshot in the same spot with normal eyes and the same PDA light, it seems that i was wrong and advanced eyes actually give you a better visual in the dark, but i never noticed it. sorry to have bothered you for nothing.

![pb](https://cloud.githubusercontent.com/assets/6170726/14766117/c5f98656-09fe-11e6-9c94-8d25f76e47e9.jpg)

on a side note, my monitor is at his max brightness. meh.
