### ISSUE TITLE
Holomap not showing cables

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9521]
(WEB REPORT BY: kolith REMOTE: 172.93.109.202:7777)

> Revision 700abd1e8f462176e4518d512289865e1f58b913 
> 
> General description of the issue
> Used the holomap as an engi borg, only showed pipes+terminals, but not cables themselves
> 
> What you expected to happen
> Holomap showing all cables
> 
> What actually happened
> Holomap showed everything other than the cables themselves.
> 
> Steps to reproduce if possible
> Use a holomap in an area with cables.

**Comment by kol1th** [comment]
fug ignore this, i'll use the new template that isn't in-game

**Comment by PJB3005** [comment]
Alright then
