### ISSUE TITLE
drag fixed stuff inside disposals

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9522]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue

fixed stuff can be dragged into disposals bins and then they disapears

> What you expected to happen
> not happen
> 
> What actually happened
> happened
> 
> Steps to reproduce if possible

drag stuff into disposals bin

**Comment by PJB3005** [comment]
DYLAN

GODDAMMIT

#9436

**Comment by Shadowmech88** [comment]
What do you mean by "fixed?"
Like anchored? Or buckled?

**Comment by ghost** [comment]
That makes little sense, what do you mean by "fixed stuff" ? Anchored items ?

Looking at the old and new code on disposals, those exceptions should explicitly be handled by attackby, unless we had a bug trailing us for months

**Comment by PJB3005** [comment]
@dylanstrategie you fucked up and there is no check for mons anymore, everything not seen as an item gets seen as mob.

**Comment by PJB3005** [comment]
https://github.com/d3athrow/vgstation13/pull/9436/files#diff-c113cc8b190f978c4e67605c46061b1bL446
