### ISSUE TITLE
Borg / all holomaps(?) not showing cables

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#9523]
#### Description of issue

Engiborg Holomap does not show cables, only pipes and terminals.

With T-Ray scanner: 
![image](https://cloud.githubusercontent.com/assets/16979948/14639239/5a761bea-05f0-11e6-8c34-ba66a80c85a1.png)

With holomap: 
![image](https://cloud.githubusercontent.com/assets/16979948/14639244/637e83a8-05f0-11e6-9761-c08c5a226972.png)
#### Difference between expected and actual behavior

I expected it to show everything, including cables, but it does not.
#### Steps to reproduce

Use a holomap near any cables.
#### Specific information for locating

Engiborg holomap.
#### Length of time in which bug has been known to occur

Just found about it recently.
#### Server revision

700abd1e8f462176e4518d512289865e1f58b913
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by kol1th** [comment]
@PJB3005

**Comment by ihadtoregisterforthis** [comment]
Congratulations on the 1300 open issues milestone

**Comment by PJB3005** [comment]
Hrm, that's weird...
