### ISSUE TITLE
seeing people put stuff in containers when blind

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9527]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I can see people put stuff in containers, even though I'm blind
> 
> What you expected to happen
> not see people put stuff in containers when blind
> 
> What actually happened
> "so and so" puts "this and that" into the bag
> 
> Steps to reproduce if possible
> be blind, have someone else put something in a container

**Comment by Killette2** [comment]
I think the intent behind this is so you can hear your valids. Hear a traitor stuff an emag in his bag? The all too familiar rustles it makes, makes your hair stand up.

**Comment by ghost** [comment]
Think it's the way the message is sent to chat, same with medbots and beepsky 'talking'
