### ISSUE TITLE
Magitek Discussion

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9529]
If I remember correctly, there's currently an unused magic research tree in R&D.
What would people think of adding some researchable magitek into the game? Nothing crazy like full-on wizard spells, but maybe the ability to craft items that have some element of magic in them, without needing to get them off the corpse of a wizard.

**Comment by icantthinkofanameritenow** [comment]
Like what? Mass-produced Firebird knockoffs?

**Comment by NigglyWiggly** [comment]
Oh shit I actually still have sprites for an 'Arcane Research' division.
Shit like artificial staffs that are just rifles and stuff

**Comment by Exxion** [comment]
Make all the magitech stuff really gimmicky
Like guns that shoot randomized projectiles, or switch the positions of the firer and the one who's hit but deal no damage, or guns that just slip the target, etc.
Just silly and interesting things
Leave the stuff that's just powerful to regular tech

**Comment by AutismSpider** [comment]
Yes lets add more shit to bloated maggot filled body that is  call R&D (zero R&D work is done any way its just a list of shit to jam into it) same R&D that has a gun that can make Singuos /gravs wells and other deadly shit

**Comment by Exxion** [comment]
> Implying adding new things that can be created with R&D is in any way related to the quality of the system itself

I don't think anyone is arguing that our current research system is good, but the solution to that is not to never change what it can be used to get

**Comment by AutismSpider** [comment]
that mean R&D does useful stuff with the tech to help the crew half  the time they fucking don't

**Comment by icantthinkofanameritenow** [comment]
@Exxion 

> guns that shoot randomized projectiles

There's already a  gun that does that, it shows up as a xenoarch find every now and then. 

And AutismSpider, if you want to help make RnD not suck, I'd be willing to help. I had some ideas about porting TG's EXPERIMENT-R, but apparently it doesn't work out quite that well in practice.

**Comment by Exxion** [comment]
Oh, I thought that gun was bus only

**Comment by mrpain666** [comment]
We need a gun that fucking spawns passive corgis.

**Comment by Killette2** [comment]
What about passive aggressive corgis?

**Comment by AutismSpider** [comment]
no we need a gun that make clowns

**Comment by ghost** [comment]
Why not a staff that makes guns, that makes staffs that fires guns
