### ISSUE TITLE
Trophy rack needs trophies.

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#9531]
Icons for mounting skulls on the chaplain's trophy rack. 
![trophy](https://cloud.githubusercontent.com/assets/15067109/14659302/875668ca-0692-11e6-92e3-73fb194cf68e.png)
Download link for icons: http://s000.tinyupload.com/index.php?file_id=01041577017758675129
Impress your friends! Intimidate your enemies! Behead your enemies! Stick their heads on your increasingly morbid backpack!

**Comment by ihadtoregisterforthis** [comment]
About time.
I always thought they were supposed to do this.

**Comment by DeityLink** [comment]
Looks fine.

That'll have to wait for #9530 to get merged since it adds skulls.

**Comment by DeityLink** [comment]
Oh, I just realized you were the guy I soulstoned! I guess you got to see your new sprites up close this way. I like the tactical helmets by the way.

**Comment by Blithering** [comment]
Yeah, was half the reason I was hinting at getting the skulls, pity we didn't get to see the new particle effects that round.

**Comment by DeityLink** [comment]
Actually we did, when I soulstoned your corpse from the morgue. It was hardly noticeable since they only had one tile to travel, but I saw them.
