### ISSUE TITLE
Blind spell affects MoMMIs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9532]
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 700abd1e8f462176e4518d512289865e1f58b913 
> 
> General description of the issue
> Self-explanatory. To quote Skowron: IT'S MAGIC I AIN'T GOTTA EXPLAIN SHIT.
> 
> What you expected to happen
> Me not being affected by blind spell
> 
> What actually happened
> Being affected by blind as if I was a carbon
> 
> Steps to reproduce if possible
> Be a MoMMI, be near a wizard when he uses Blind

**Comment by AutismSpider** [comment]
Happens with cyborg to robot eyes and shit aint gotta explain it

**Comment by Probe1** [comment]
That sucks.  Too bad MoMMIs don't use radar and are slaved to their optical sensors.
