### ISSUE TITLE
Either remove borers from the random infestation event or give them some sort of passive AI

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9534]
Home Confederation Update

Vermin infestation

Bioscans indicate that cortical borers have been breeding in the Chapel. Clear them out, before this starts to affect productivity.

And then it just gets dumb watching them lay there, do nothing, and have players scream at empty borers to get in their heads.

**Comment by Intigracy** [comment]
Ghosts can take over borers that spawn via that event by clicking on them.

**Comment by ihadtoregisterforthis** [comment]
Even if they can be piloted they are called vermin and many times treated as such.

**Comment by Killette2** [comment]
mrpain stop lying, the players kill the borers not ask to be infested.

**Comment by west3436** [comment]
They're edible now so I guess the crew can just eat them??
