### ISSUE TITLE
Asteroid setpieces still spawn on top of base areas, such as the Trade Outpost

### ISSUE THREAD

**Issue by DeityLink** [d3athrow/vgstation13#9536]
![setpieces](https://cloud.githubusercontent.com/assets/7573912/14673865/c0dafcdc-0700-11e6-8dfb-fc46752b26ae.jpg)

top kek

**Comment by PJB3005** [comment]
Pretty sure we've got an issue on this already.

**Comment by DeityLink** [comment]
Indeed, and it's a whole year old already #4776 If anything we should close it and keep discussing in this issue so people get reminded that it still exists and is even more annoying now since Vox Traders are a thing.

**Comment by 9600bauds** [comment]
I don't know, the other issue has more info on why this happens and how to fix it

**Comment by DeityLink** [comment]
Well it's linked in my previous post. I'm just trying to remind everyone that it's still there.

**Comment by clusterfack** [comment]
Then bump it don't open a new issue, do you not understand how an issue tracker works?
