### ISSUE TITLE
Spider Queens shoot around 50 to 100 stacks of webs if they can't reach a light bulb

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#9537]
![000000000000](https://cloud.githubusercontent.com/assets/7571238/14678962/3d003614-06ee-11e6-9a1e-b9de0354004d.png)

Holy shit calm down your assburgers.

**Comment by 9600bauds** [comment]
>@DeityLink: Spacechem is a fucking boring game

Fite me

**Comment by Probe1** [comment]
they do that shit though WALLS

THROUGH WALLS.

**Comment by ihadtoregisterforthis** [comment]
But I did
#9057

**Comment by Probe1** [comment]
great tagging work sood

**Comment by gbasood** [comment]
Seeing through walls and webbing AT walls are entirely different issues
Make better titles

**Comment by Imagebard** [comment]
What are you even talking about

**Comment by Shadowmech88** [comment]
Also if they can't reach a light, they ignore mobs around them since the light is still their current target.
Not sure if they'd change targets when you attack them, but it did allow me to capture a spider queen in a cage since I could get right next to it without being attacked.

**Comment by gbasood** [comment]
@Imagebard APPARENTLY that's not okay
That issue itself describes an actual problem so it's not ITS A FEATURE despite describing a thing that isnt actually an issue initially

**Comment by CptWad** [comment]
Harvesting silk from webs when
dwarf fortress textile industry when

**Comment by Probe1** [comment]
GCS farms when
goblin as an alt title for assistant
