### ISSUE TITLE
That Robotic Talk font is god-awful, FIX IT

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9538]
I don't know who put their hands on it, but please change it back

It just looks awful. Just use TT and call it a day, or don't use any special font at all

**Comment by PJB3005** [comment]
Ah, the good 'ol complain-after-it-gets-merged

#9459

**Comment by Intigracy** [comment]
It's the same one as they use to talk on the radio normally.

Please see #9513 

What don't you like vote:
![2016-04-18_18-10-38](https://cloud.githubusercontent.com/assets/4043940/14624889/67264566-0593-11e6-992a-f9489975a8e4.png)
