### ISSUE TITLE
Can't syringe gun over tables

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9541]
(WEB REPORT BY: manfreed REMOTE: 172.93.109.202:7777)

> General description of the issue
> Firing a syringe gun at someone on the other side of a table doesn't work. If I see corectly you hit the table
> 
> What you expected to happen
> I expected the syringe to fly over the table
> 
> What actually happened
> I hit the table
> 
> Steps to reproduce if possible
> -Place dummy on the other side of a table. Table material of the table doesn't seem to matter
> -try to shoot dummy with a syringe gun

**Comment by Shadowmech88** [comment]
Syringe guns should really fire proper projectiles instead of whatever they do now.

**Comment by Killette2** [comment]
and pierce civie softsuits

**Comment by 9600bauds** [comment]
![firefox_2016-12-16_20-43-06](https://cloud.githubusercontent.com/assets/6526157/21290961/1ea4f98e-c4ad-11e6-851e-1d53f3e60b26.png)
