### ISSUE TITLE
dna injectors and  vaults

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9542]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> the dna injectors that spawn in one of the vaults dont work
> 
> What you expected to happen
> to work
> 
> What actually happened

they dont

> Steps to reproduce if possible

hit yourself with the dna injector

**Comment by PJB3005** [comment]
I believe this is about the gym vault.

**Comment by Intigracy** [comment]
DNA generates after the map spawns things in.

So these don't have the block references like they should.

**Comment by Shadowmech88** [comment]
Is there a way to check whether DNA generation has been done?
Could put an if statement in the DNA injectors' `New()` that would enter a while loop if DNA generation hadn't been done yet, then once it has exit the loop and respawn the injector.

**Comment by Intigracy** [comment]
Yes, and it would be a while statement instead.

**Comment by PJB3005** [comment]
Better yet, put it in `initialize` instead
