### ISSUE TITLE
Double emagging bots doesn't work

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9543]
I tried to emagged a medbot twice

First emag told me controls were unlocked, emag again to cause it to malfunction

Further attempts to emag did nothing, features borked

**Comment by Shadowmech88** [comment]
Also does not seem to work on Beepsky.

**Comment by 9600bauds** [comment]
did you crowbar inbetween the swipes

**Comment by Shadowmech88** [comment]
I didn't think bots even _had_ panels you could crowbar.

**Comment by clusterfack** [comment]
Emagging it more than twice isn't supposed to do anything, did I miss something here?

**Comment by Killette2** [comment]
A few request ago I complained that we can't emag bots to make them malfunction anymore, such as making beepsky arrest anyone on site. However it was pointed out YOU CAN, you just are supposed to emag them twice now, the first emag being control unlock.

Now for quality we get a message when you emag it, you get told to emag it again to make it malfunction, however this is not working at all.

**Comment by clusterfack** [comment]
IF IT IS NOT CLEAR I AM ASKING WHAT IS NOT WORKING ABOUT IT

**Comment by Shadowmech88** [comment]
Emagging a bot successfully unlocks its control panel.
Emagging it a second time is supposed to make it malfunction.
Emagging it a second time, currently, does not appear to make it malfunction.
