### ISSUE TITLE
Requesting blackout message

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9544]
Sometimes due to pain or cold, you black out. This often happens in medbay, and the doctor does not notice you're unconscious and keeps talking. It's annoying because you can't hear him, and they may think you're just on the ground due to pain.

Since there is a message that appears in chat for when you collapse (see radiation overdose) that lets people know you're collapsing, why not add a message for everyone to see that you've blacked out so they know you're asleep and not able to hear them.

**Comment by west3436** [comment]
Not a desired feature anymore
