### ISSUE TITLE
Cold and Heat resist genes do not work together.

### ISSUE THREAD

**Issue by SkowronX** [d3athrow/vgstation13#9545]
It simply sticks with the gene that was acquired first. Getting the second one while the first is active doesn't do anything

**Comment by PJB3005** [comment]
Pretty sure this is intentional...

**Comment by PJB3005** [comment]
[Yup](https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/dna/genes/powers.dm#L178)

**Comment by Probe1** [comment]
My dreams of Hot Coldman ended before they began!

**Comment by SkowronX** [comment]
Then change it. aaaaaah

**Comment by PJB3005** [comment]
Interestingly enough if I'm understanding the code right it looks like there is a 5% chance for it to work with both if you are NOT using forced genes.

**Comment by Shadowmech88** [comment]
Tag this as a feature request then.
I too think they should both work together.

**Comment by nuklearcellphoneg** [comment]
Can't they just cancel each other out?

Having both is kind of OP

**Comment by Shadowmech88** [comment]
Having multiple genetic powers usually leads to being OP.
