### ISSUE TITLE
Test server is experiencing weird bug again

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9547]
In the lobby it says the station time is 12:01, despite 12:05 being when the game should start due to the 5 minute lobby time. When you join, the stations basic functions such as lighting, vision, and power do not work, the only solution is to alt-click tiles to see what's on them and nuke the station.

This is the second time this bug has occurred that I have witnessed, both on different maps and weeks apart (first was meta, now it's box).

**Comment by clusterfack** [comment]
I'm surprised we still have a test server right now to be honest

**Comment by ihadtoregisterforthis** [comment]
It serves more as a panic room when the main server dies, but it's used for testing regularly.

**Comment by FudgePucker** [comment]
All you gotta do is set up a magic smes and spawn a flash light.

**Comment by PJB3005** [comment]
Nope, I think the entire scheduler breaks.

**Comment by FudgePucker** [comment]
Oh well shit then its fucked

**Comment by gbasood** [comment]
@PJB3005 Shouldn't 510 PR have fixed this? Unless the btime dll is still being loaded?
