### ISSUE TITLE
Allow telnet connections, exclusively for OOC.

### ISSUE THREAD

**Issue by PJB3005** [d3athrow/vgstation13#9548]
Pretty fucking useful to not have to connect properly if you just want to ask OOC's opinion on something.

**Comment by MercuryDoll** [comment]
Why don't we have a Discord for OOC? :^)

**Comment by SysadminJeroen** [comment]
CC: @TheFriggenSawbones :^)

**Comment by Iamgoofball** [comment]
i keep forgetting byond does telnet and irc

**Comment by PJB3005** [comment]
Are you sure BYOND can do IRC @Iamgoofball? http://www.byond.com/docs/ref/info.html#/client/var/connection

**Comment by TheFriggenSawbones** [comment]
@Jeroen52 hello yes

**Comment by Iamgoofball** [comment]
Yes, I've logged into synirc and rizon before
