### ISSUE TITLE
Write a real fuckin wiki entry for HOGAN or pull it from the repo

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9551]
https://github.com/d3athrow/vgstation13/pull/8445

Jokes are funny.  Jokes that leave the silicons confused and crew dead are not.  Fix it damnit.  Wiki on how its supposed to work or OUT.

**Comment by 9600bauds** [comment]
[Memes]

**Comment by Ephx1** [comment]
> Ambiguous laws

When will you faggots stop with this? Silicons only use it as an excuse to murder others.

**Comment by AutismSpider** [comment]
@Ephx1 when celt dies in a fire for his meme law set and the faggot who put the hogan in jumps into pit of glass

**Comment by ghost** [comment]
I didn't add that lawset but it is objectively the best one.

**Comment by Probe1** [comment]
Celtic, which I have no idea why it was added to the fookin core, has an entry on the wiki and is not my immediate concern.

Hogan on the other hand does not.

**Comment by NigglyWiggly** [comment]
Celtic is literally the worst AI lawset I have ever seen, serious or otherwise.
Shit, the wiki entry on it even tries to pretend it has actual defined laws to follow instead of just one incredibly vague statement that means literally nothing to an AI.

But yeah the Hogan lawset needs an entry too, and I can't think of anything to write for it beyond just linking to the song

**Comment by carshalash** [comment]
http://ss13.moe/wiki/index.php/Guide_to_Silicon_Laws#Law_Modification sent ;)

**Comment by Ephx1** [comment]
English isn't your first language, is it?

**Comment by carshalash** [comment]
It is, I'm just retarded.

**Comment by Probe1** [comment]
matches the lawset

**Comment by 9600bauds** [comment]
![firefox_2016-04-27_01-31-07](https://cloud.githubusercontent.com/assets/6526157/14841774/bed790aa-0c17-11e6-9de2-04a016509d50.png)

**Comment by Shadowmech88** [comment]
How do we get the dank lightning emoji like you, Bauds?

**Comment by 9600bauds** [comment]
Inspect element

**Comment by Zth--** [comment]
this has been addressed, close pls

**Comment by Probe1** [comment]
no, it really hasn't.

**Comment by SysadminJeroen** [comment]
How do I contribute to the Wiki?

**Comment by Shadowmech88** [comment]
Go to the wiki, make an account, go to the page you want to edit, hit the edit button at the top of the page.

**Comment by Imagebard** [comment]
I feel like someone specific should comment on this issue.
@Hoshi-chan

**Comment by Ephx1** [comment]
There's nothing to comment on, ambiguous laws are beyond idiotic and silicons love to shit up everything with them

**Comment by Imagebard** [comment]
Yeah but I wanted to see him having a stroke

**Comment by Ephx1** [comment]
Fair enough

**Comment by ihadtoregisterforthis** [comment]
Dead
