### ISSUE TITLE
Security belt can't hold cig packs

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9553]
(WEB REPORT BY: gobab REMOTE: 172.93.109.202:7777)
Medbelts can, normally you stuff lighters in the cig packs which is sick, but for some gay reason sec belts can't hold cig packs

pls fix

**Comment by 9600bauds** [comment]
But how do you find the space with so much shit to carry

**Comment by Exxion** [comment]
The round during which he reported this he did nothing but sit at the bar anyway

**Comment by Kitfox88** [comment]
sounds like a good sec officer to me

**Comment by Exxion** [comment]
Fixed by #13298 but there were quotes around "fixes" so it didn't autoclose
