### ISSUE TITLE
Fireball rework suggestion

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9559]
Here is fireball, how it works, and it's flaws. The points bellow are not the flaws, just describing the spell

-moves slow
-shoots, explodes when it touches someting (explosion is where fireball last was, not on object touched)
-upgrades lower the cooldown drastically, to around 2 or less seconds when maxed
-is a robeless spell
-they do fuckall to windows, computers/machines, APCs, airlocks, ect. Only good for breaking the metal off of walls and breaking floortiles due to the way their explosion works (fireball explodes, not object it hits so it's alway 1 tile off)
-you often get double fireballs exploded in your face due to their slow movespeed and high cooldown when spamming them, this is complete bullshit

Now here are ideas of how we can make fireball better

-upgrading could increase damage, cooldown remains unchanged
-upgrading could increase damage slightly, and reduce cooldown, but not as much as it currently does
-upgrading can make them go faster and reduce cooldown, maybe damage too

and for the hell of it, a new spell suggestion

---

greater fireball

-robed spell
-1 point still, it's just a different fireball
-higher cooldown, intended to be a powerful spell like lightning
-upgrading drastically increases damage, but also raises the cooldown to scale with such power
-MASS DESTRUCTION

**Comment by Sarcalogo** [comment]
YOU'VE GOT A CHEMISTRY CLASS I WANT A PIECE OF YOUR MIND
YOU DON'T KNOW WHAT YOU STARTED WHEN YOU MIXED IT UP WITH MIIIIIIIIIIIIIIIIIIIINE
ARE YOU READY FOR THE FINAL SOLUUUUUUUUUUUUUTION??
OH OH
OH OH

**Comment by NigglyWiggly** [comment]
Vocaroo when

**Comment by Boxe** [comment]
wizards not requiring sandals to cast when/wizard hardsuit coming with wizzy magboots when

**Comment by Konater** [comment]
Needs a rework rather than number changes

**Comment by Intigracy** [comment]
> -moves slow

Moves as fast as an electrode, if not faster.

**Comment by Konater** [comment]
Someone was using it last round, it was moving slow as balls

**Comment by Imagebard** [comment]
2nd fireball suggestion:
It starts a fire instead of exploding.

**Comment by AutismSpider** [comment]
Make it work like a real fire ball when it crash's into a mob wall etc sets them on fire and any thing near it.

@Intigracy Fire ball moves so slow you can out run it and bump into after casting it on top of doing dick for damage

**Comment by Killette2** [comment]
Except, running into a fireball is the ONLY time it does damage. If a fireball 'hits' you, it explodes to the tile next to you. If you run into it, you are on the same time when it explodes so it explodes ontop of you doing tons of damage.

The way it works is DICKS.

**Comment by Konater** [comment]
Make it so the fireball explodes on the tile that blocked it then it will actually do damage to people other than yourself and be able to break walls. In hand toggle like lightning optional

**Comment by Killette2** [comment]
In hand fireball... CHARGING fireballs...
