### ISSUE TITLE
I figured out why some hardsuits don't seem to actually have any slowdown and the cause is as dumb as it gets

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9560]
Take a mining hardsuit. The bodypiece has a slowdown of 1. The helmet has a slowdown of 1.
You might think this means the hardsuit has a slowdown of 2, right?
You'd be wrong, because **the only things that actually slow you down are your shoes and your exosuit, so your helmet's slowdown doesn't even matter**
![atom_2016-04-21_17-39-13](https://cloud.githubusercontent.com/assets/6526157/14723547/018dbe94-07e8-11e6-887f-048b1c35a4c3.png)

Okay, so the hardsuit effectively has a slowdown of 1. That should slow you down, right?
Well, the way this was supposed to work is that you are slowed down if you aren't wearing a pair of shoes. The way this was accomplished was by making shoes have a slowdown of -1.
So as long as you are wearing shoes, your hardsuit has **zero slowdown**

**Comment by PJB3005** [comment]
:clap:

**Comment by Exxion** [comment]
But negative slowdowns work, so you should have -1 slowdown without the suit on and go faster, even with a slowdown of 1

Although I'm not sure negative slowdowns are as significant as equal positive slowdowns
They are noticeable, though
Source: That one fucking shoe bug

Maybe a slowdown of specifically -1 is equal to a slowdown of 0 for some reason

**Comment by Intigracy** [comment]
Someone wearing shoes has -1 slowdown.

Someone not wearing shoes has 0 slowdown.

Someone wearing shoes and wearing a hardsuit has 0 slowdown.

Someone not wearing shoes and wearing a hardsuit has 1 slowdown.

So yes, hardsuits do slow you down compared to the average joe. Unless negatives are bugged, in which case hardsuits still slow you down.

Though we do need to adjust slowdown to account for all slots.

**Comment by 9600bauds** [comment]
Negative slowdown doesn't work, I don't think

**Comment by Exxion** [comment]
Negative slowdown _does_ work, I'm almost positive
Hence the shoe bug

**Comment by 9600bauds** [comment]
If it does work I have never, ever noticed any difference

**Comment by SkowronX** [comment]
Does the slow down value use the new movement speed modifier var?

**Comment by 9600bauds** [comment]
Without a hardsuit: 
I varedited some shoes to have -100 slowdown, no difference
-10 slowdown, no difference
-5 slowdown, no difference
Taking my shoes off mid-sprint, I couldn't notice any difference at all

With a slowdown 1 hardsuit:
No shoes: obvious slowdown
Shoes: no slowdown
Taking off my hardsuit mid-sprint with shoes on, no difference

**Comment by clusterfack** [comment]
I have stated the values don't make any sense anymore right? I believe I have.

No, the values no longer make any sense and are basically completely imbalanced.

**Comment by 9600bauds** [comment]
At the time I wrote this, hardsuit helmets had a slowdown of 1
They now have a slowdown of 0
I can't find any commit that would have changed that
I'm going nuts

**Comment by N3X15** [comment]
git blame

**Comment by 9600bauds** [comment]
I ran git blame through rig.dm and nothing, I have no idea where else the slowdown could have been
I swear it was there at one point

**Comment by NigglyWiggly** [comment]
Reminder to **NERF GHETTO SPACE SUITS**

I don't remember if they still have no fucking slowdown but they shouldn't even be rigs to begin with

**Comment by Probe1** [comment]
Ghetto space suits are supremely dumb and I have no idea how they got in the code.

**Comment by NigglyWiggly** [comment]
I sprited them for Celt with the idea that they'd be shitty makeshift space suits but then he made them just work like a normal rig suit

**Comment by Probe1** [comment]
Golly Celt.  Maybe we shouldn't make it so every assistant can go space exploring in a fucking jacket and gas mask.

**Comment by Shadowmech88** [comment]
I think it'd be better if the ghetto space suit provided you something like half the pressure protection, but still completely insulated you so you could spacewalk without passing out.

**Comment by 9600bauds** [comment]
I mean, to be fair, in ye olde times you could spacewalk with just the firefighter gear and coffee

**Comment by NigglyWiggly** [comment]
No no probe it's not just a jacket and mask, that's just for the whole 'spacewalking in a fire suit' thing
The real protection is the blanket that you steal from medbay

**Comment by Probe1** [comment]
You're right.  

God there's so many things I want to nerf the shit out of but I don't have the energy to reasonably state my case to the players and listen to arguments for why we should have things that don't work.

**Comment by DamianX** [comment]
Fixed by the movement speed rework
