### ISSUE TITLE
Maybe intended: WOOP WOOP only shows to the wearer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9561]
(WEB REPORT BY: brolaire REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 07b8f8d981f38ebd66476cc58136b57b2a572b7b 
> 
> General description of the issue
> Using the siren helmet only tells the user who used it, which is sorta redundant
> 
> What you expected to happen
> Being able to distinguish who used the WOOP WOOP all the time
> 
> What actually happened
> Only you, the WOOP WOOP user, can read the following:
> Areel Huumin's siren helmet rasps, "WOOP WOOP!"
> 
> Steps to reproduce if possible
> put woop woop on someone else
> tell them to woop woop

**Comment by 9600bauds** [comment]
I actually copypasted the code from the hailer so the hailer does this thing too lol

**Comment by Kitfox88** [comment]
HALT
SHITCODE

**Comment by clusterfack** [comment]
>I actually copypasted the code from the hailer so the hailer does this thing too lol

*TRUSTING THE CODE*

**Comment by Probe1** [comment]
wait till clusterfack sees what I did
