### ISSUE TITLE
Strange stones sometimes get disconnected from their base station

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9562]
Or rather the base station gets disconnected from them
They stay connected to the station
They can transmit, but not receive

I'm about 80% sure I've already found the cause, but I'll have to test it, which I can do in a little while
If I'm right, though, it's a very easy fix

**Comment by clusterfack** [comment]
Don't leave us hangin

**Comment by Exxion** [comment]
I'll fix it within the hour if I'm right about what's wrong, and I'll explain what happened in the PR
But the short version is esoteric BYOND list fuckery

**Comment by clusterfack** [comment]
If you mean what I think you mean then line 60 needs to be changed to
```
	var/list/obj/item/commstone/thestones = allstones.Copy()
```

**Comment by Exxion** [comment]
Yeah, that's what I think too
I want to test it first, though, just to make sure
