### ISSUE TITLE
Borgs can stunbaton AI cores

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#9565]
[YOUR BORG IS STUN BATONING YOU, PLEASE STANDBY]

**Comment by NigglyWiggly** [comment]
how is this an issue though

**Comment by Allspice** [comment]
Can shockarm an AI and it'll stutter for the rest of the round, it's hilarious.

**Comment by AutismSpider** [comment]
Shockarm works on borgs forces them stutter and shit

**Comment by Probe1** [comment]
Spiderbots, who normally can do absolutely fuck all, can actually poke an AI to death over the course of 10 minutes.

**Comment by Killette2** [comment]
That's stupid Probe. What if a human law 2's a borg to secretly kill their AI under asimov?

**Comment by clusterfack** [comment]
As if a borg wouldn't be a faggot and rules lawyer his way out of it 99.9% of the time

**Comment by Shadowmech88** [comment]
The borg would still have to get into the AI core, which only opens from the inside. The human would have to order an engieborg to weld the walls down, then order a secborg to club the AI to death.
Even if you removed the ability to baton the core, the human could simply order the engieborg to welderbomb the AI to death, to the same effect. Or it could shut off the APC breaker in the core.

**Comment by nuklearcellphoneg** [comment]
f e a t u r e

**Comment by Intigracy** [comment]
I think the issue is that you can STUN the AI core.

**Comment by Shadowmech88** [comment]
Hitting a sensitive computer with a stick that's got electricity sparking off the end of it is bound to cause some problems.

**Comment by Imagebard** [comment]
next off you're going to tell me that the AI core isn't waterproofed

**Comment by Probe1** [comment]
Trust me if I could sell the idea to someone to add running water to the game, shocking silicons would be way up there n the list.

**Comment by Probe1** [comment]
Honestly even though the spiderbot thing is kinda an issue, that's not what this one is about.  This one is about a borg being able to hit a mob that is also a structure with a weapon.  

That is ok.
