### ISSUE TITLE
AI can't initiate Borg destruct

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9573]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
Seriously it's stupid, there should be no reason why AI can't destroy borgs.

**Comment by Imagebard** [comment]
>OOC: Lorkhatosh: I write uninformed retarded reports
OOC: Lorkhatosh: that's my thing

**Comment by ghost** [comment]
Guess I'll write it for him

Lork was an AI during a round where a traitor went HAM with creating then emagging borgs. Lork then attempted to use the cyborg console to initiate the global destruct switch. Problem is, global destruct needs an Id swiped, so as an AI, you can't blow all the borgs.

**Comment by Shadowmech88** [comment]
I feel like a good solution would be making it so that an AI using any "swipe ID" button would cause the machine to act as if a captain-level ID had been swiped into the machine.

**Comment by clusterfack** [comment]
Because AIs aren't omnipotent enough

**Comment by Intigracy** [comment]
I completely disagree with giving the AI access to blowing borgs that aren't slaved to them, which is in essence what this feature request is asking for.

They're removed from the blow menu when not slaved for a reason.

**Comment by kol1th** [comment]
> Lork was an AI during a round where a traitor went HAM with creating then emagging borgs.

you can't blow emagged borgs anyways, not even as AI. Why would you think this is okay.

**Comment by Intigracy** [comment]
Pretty sure as a human you can blow emagged borgs.

**Comment by kol1th** [comment]
> Pretty sure as a human you can blow emagged borgs.

you can blow subverted borgs, not emagged borgs

**Comment by Imagebard** [comment]
This was intended as a bug report
Why does this have the Balance and Feature Request tags

**Comment by Intigracy** [comment]
Because it's asking for the ability to blow emagged cyborgs as an AI.

**Comment by Imagebard** [comment]
Looking at the PR without context, its just stating a incorrect fact.
By asking the creator of this Issue, he'll say its a Bug Report.

All of this points to it being a feature request.
_No wait_

**Comment by Intigracy** [comment]
Global cyborg killswitch = blow all borgs in existence. Giving the AI access to this means it can therefore now blow emagged cyborgs and cyborgs that are intentionally unsynced from the AI.

:-1:

**Comment by kol1th** [comment]
> Global cyborg killswitch = blow all borgs in existence. Giving the AI access to this means it can therefore now blow emagged cyborgs and cyborgs that are intentionally unsynced from the AI.

yeah basically this. you can blow any borg as an AI, but not emagged ones. not really a bug, more intended afaik

**Comment by Intigracy** [comment]
As AI the only borgs that show up on the list are ones synced to you, I'm pretty sure.

So if you and another AI exist together, he can't blow your borgs and you can't blow his. Nor can either of you blow any borgs that are emagged or just not synced to an AI.

**Comment by kol1th** [comment]
Yeah that's exactly how it works.

**Comment by Killette2** [comment]
AI's should NOT be able to use things involving ID swipes, here is reasons that would make it unfair

-Blowing emagged borgs
-Assisting in or doing on it's own, the turning on red alert on it's own for combat borgs
-Use head of staff announcers to impersonate heads of staff, the ability to use comms computers for announcements is strong enough

**Comment by PJB3005** [comment]
Don't forget "AI give me all access and do not tell anybody"

**Comment by AutismSpider** [comment]
@Killette2 need two people for that good luck with that its just massive fight just to do it on blob rounds other then that yeah i agree with you

**Comment by FudgePucker** [comment]
AI could just you know, swipe two different swipe machines to call red, because a human can't make it to two machines in time, the ai could

**Comment by Imagebard** [comment]
@AutismSpider And this justifies allowing the AI to activate red alert?
