### ISSUE TITLE
Feature Request: Renaming Vox Trader/Vox Raider

### ISSUE THREAD

**Issue by Brolaire** [d3athrow/vgstation13#9577]
Okay so this sound really stupid, but I noticed a lot of people saying Trader or Raider when they meant the other. Maybe if the default name was one of the alternatives instead of Trader, people would stop getting Vox Raiders/Traders/Traitors mixed up.
Alternative: Wait it out and hope people stop making this small mistake or just tell them to stop being so stupid.

Curious what others think about this considering there is nothing really bad with this besides MUH IMMULSION being broken by others.

**Comment by Gringonius** [comment]
Traders don't even get IDs to show their jobs. I doubt that a rebranding will change anything.
Just leave things like their are for le ebin chickengriff meme.

**Comment by kol1th** [comment]
There's no in-game indication of them being Vox Traders, except for people knowing that the job exists, so this doesn't make much sense

**Comment by Blithering** [comment]
There's a point, why do you get several different alternate titles to choose from as trader when there's no ID to reflect it?

**Comment by Brolaire** [comment]
Wouldn't it be possible to implement some sort of Vox ID with no access anywhere but voxstation? Or give them see-through helmets so they're not Unknown?
