### ISSUE TITLE
Atmos computer map thing

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9581]
(WEB REPORT BY: slamjamwithdoctordan REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> c1d94cf88087938c9d38b61d36edae2582d80d08 
> 
> General description of the issue
> Atmos reports are out of place on the atmos computer
> 
> What you expected to happen
> them to be in the right fucking place
> 
> What actually happened
> ????
> 
> Steps to reproduce if possible
> literally open the atmos monitoring computer and look at the map thingy
> I was playing atmos tec with the darkblue UI

thx bb

**Comment by 9600bauds** [comment]
this apparently happened in meta

**Comment by clusterfack** [comment]
It would happen on any map because of nanoui

**Comment by 9600bauds** [comment]
Worth noting in case the error is with the minimap pngs or someshit

**Comment by Probe1** [comment]
been broken since I came back in feb

**Comment by PJB3005** [comment]
Yup

**Comment by 9600bauds** [comment]
Pretty sure this was fixed
