### ISSUE TITLE
Can't cut pizza with scalpel or circular saw

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9582]
(WEB REPORT BY: kitfox88 REMOTE: 172.93.109.202:7777)

> Revision c1d94cf88087938c9d38b61d36edae2582d80d08
> 
> General description of the issue
> Can't cut pizza with scalpel or circular saw
> 
> What you expected to happen
> cut dat fuckin pizza
> 
> What actually happened
> nuthin at all
> 
> Steps to reproduce if possible
> click on pizza with one of those two tools

maybe it's cause i was a borg in which case i demand equality for silicons god damn it

**Comment by clusterfack** [comment]
><Cloroxygen> Can't reproduce  "Can't cut pizza with scalpel or circular saw #9582"

**Comment by ghost** [comment]
I can't reproduce this locally, used borg also

**Comment by Killette2** [comment]
was the pizza on a table?

**Comment by Kitfox88** [comment]
Sorry, yeah. Chef had it sitting on the serving table in front of the Kitchen.
