### ISSUE TITLE
Borer OD Message Error

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9586]
(WEB REPORT BY: rhimrifer REMOTE: 172.93.109.202:7777)

> Revision
> Revision: c1d94cf88087938c9d38b61d36edae2582d80d08 
> 
> General description of the issue
> Using non-OD levels of chemicals(besides hyperzine) causes a popup about OD when releasing chems as borer.
> 
> What you expected to happen
> A popup to not occur
> 
> What actually happened
> A popup occured at incorrect times
> 
> Steps to reproduce if possible
> Play as borer and release any chemical that isn't hyperzine when in a host

**Comment by Probe1** [comment]
100% tested is really getting out of hand here.

**Comment by 9600bauds** [comment]
I tested it with bicaridine, alkysine and hyperzine, that's like 100% man
Will fix tomorrow, on phone

**Comment by 9600bauds** [comment]
I suspect the problem here to be chemicals with an overdose of 0 because it's definitely not "any chemical that isn't hyperzine"
