### ISSUE TITLE
Access Denied in Vox Station as Vox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9587]
(WEB REPORT BY: icychocobo REMOTE: 172.93.109.202:7777)

> Revision c1d94cf88087938c9d38b61d36edae2582d80d08 
> 
> General description of the issue
> Engi-Vend gives an Access Denied error as a round-start Vox Trader. Title is Traveler, should it matter.
> 
> What you expected to happen
> It gives me my bleedin Meson Goggles
> 
> What actually happened
> Access Denied error
> 
> Steps to reproduce if possible
> Round-start spawn as a Vox Traveler (might work fine for other titles?) and attempt to dispense something from the Engi-Vend in the Vox Station.

**Comment by Exxion** [comment]
Everything in that trading post should start with the access check wire cut

**Comment by PJB3005** [comment]
Alternatively we rework the access system so there's faction level access groups.

**Comment by Exxion** [comment]
But access is ID-based and traders have no IDs
Unless you propose we change the necessity for an ID for any kind of access

**Comment by PJB3005** [comment]
Okay, here's what I propose:

We give Vox traders IDs, but they're Vox IDs and can only be used for Vox things.

Then regular IDs can't access the Vox things.

**Comment by ihadtoregisterforthis** [comment]
Different sprites required

**Comment by 9600bauds** [comment]
Different sprites provided

**Comment by beesil** [comment]
Fixed in #10502
