### ISSUE TITLE
Vampire text

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9589]
(WEB REPORT BY: edwarus REMOTE: 172.93.109.202:7777)
#### Revision

c1d94cf88087938c9d38b61d36edae2582d80d08 
#### General description of the issue

vampire text is wrong it says that to drain blood you use harm intent and target the head but since the new bite feature was implemented you have to actually bite now but as mentioned alls the entry text for vamp tells you is harm intent and target head.

**Comment by Killette2** [comment]
It really pisses me off when people don't erase the default bug report text when they don't even fill out all the columns. Now we get this ugly gray bug report that looks top heavy.

**Comment by PJB3005** [comment]
At least I can edit these fucking bug reports.

**Comment by Killette2** [comment]
How come when I click on the thing that says revision now, it leads to Scootaloo being removed from the default clown names? Also why is it being removed?

**Comment by ihadtoregisterforthis** [comment]
It's the last commit, to have a reference of what came before.

**Comment by Killette2** [comment]
But why is Scootaloo removed? I see nothing wrong with it, it's just as goofy as the other clown names, if not lame and uncreative also.

**Comment by Shadowmech88** [comment]
Say so here: #9566.

**Comment by Killette2** [comment]
Wow, I didn't know bronies played our server. I don't even know what the fuck a Scootaloo is. That says a lot.
