### ISSUE TITLE
Dragged as mouse

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9591]
**(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)**
#### General description of the issue

When you are mous and are being dragged you get a message every second "You are too small to pull anything" resulting in a robust spam.
#### What you expected to happen

Get no message
#### What actually happened

Got the message
#### Steps to reproduce if possible

Become a mouse and let yourself be dragged.

**Comment by 9600bauds** [comment]
Been happening for a long time now, I'm fairly certain this is a dupe but whatever

**Comment by ihadtoregisterforthis** [comment]
#4742
