### ISSUE TITLE
virologist satchels

### ISSUE THREAD

**Issue by uazuaz** [d3athrow/vgstation13#9592]
#### Description of issue

the virologist starts with 2 satchels, a gray one on his back and a green virologist satchel inside a plastic bag
#### Difference between expected and actual behavior

i expected to have just a virologist satchel on the back
#### Steps to reproduce

choose virologist as a job
#### Length of time in which bug has been known to occur

saw this today
#### Server revision

c1d94cf88087938c9d38b61d36edae2582d80d08
#### Issue bingo

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by PJB3005** [comment]
This might've actually been my fault...

**Comment by ghost** [comment]
Cannot reproduce exactly as described by reporter, However bugs do exist here.

Seemingly Related(local): Virologist Satchel spawns in hand with first aid kit, dropping left hand reveals both items.
1. Join late round as human virologist with alt. satchel.
2. Drop first-aid kit.
3. Examine the items evoked to the tile.

**Comment by Exxion** [comment]
> Dropping left hand reveals both items

I honestly can't figure out how this is even possible

**Comment by uazuaz** [comment]
here what i see at round start (i don't know about latejoining); this is the content of the plastic bag:

![satchel](https://cloud.githubusercontent.com/assets/6170726/14763103/31b6e8b6-098c-11e6-8a16-30c0178eaf2e.jpg)
