### ISSUE TITLE
Deff Missing Atmospipe

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9594]
(WEB REPORT BY: **herrytheafroheadcrab** REMOTE: `172.93.109.202:7777`)
#### General description of the issue

On defficency next to the mechanics workshop in maintance there is a connection from the waste loop missing.
There should be a three way pipe but there is only a bent one cutting of arrivals distro from the loop.

**Comment by ihadtoregisterforthis** [comment]
Also take a gander at this 
![control installation four 2016-04-07 172028](https://cloud.githubusercontent.com/assets/13305885/14763611/eace2268-0970-11e6-9ffe-2403ec0b8427.png)

**Comment by Probe1** [comment]
i swear to fucking god duny all these pipes under rwalls
