### ISSUE TITLE
Joining the round as it starts occasionally FUCKS YOUR PROFILE AND LOADS A BLANK ONE

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9597]
#### Description of issue

http://i.imgur.com/Vg5518v.png  This has occurred to a handful of players, including myself just now.  When you join a round before the server has finished loading it has a chance of this happening
#### Difference between expected and actual behavior

My character slot to be loaded or at least not get a blanked out name and shit

I get a blanked out name and no preferences saved both in game and in my settings
#### Steps to reproduce

???
#### Specific information for locating

Reload slot fixes it but you don't have any indication it has happened until you open Setup Preferences or join with a blank name.
#### Length of time in which bug has been known to occur

Since yall started meddling a month ago with profiles
#### Server revision

c1d94cf88087938c9d38b61d36edae2582d80d08 Current Infomational Settings: 
Protect Authority Roles From Tratior: 1
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
also why

```

Current Infomational Settings: 
Protect Authority Roles From Tratior: 1

```

its debug output left in the game on accident right..?

**Comment by Intigracy** [comment]
I have no idea why this is happening.

Also you can observe before the round starts even though my code specifically prevents that, but you can't open setup character. Which has the exact same code line preventing it. I can't reproduce this locally either.

**Comment by Intigracy** [comment]
Also at the protect authority roles thing, that has been on show revision since forever.

**Comment by Exxion** [comment]
> Only happened in the last month

This always used to happen for me on local before I fixed it by...
Er...
Fuck, I forgot how I fixed it
It was a config thing though, I think

**Comment by Intigracy** [comment]
It has to do with sql database I'm pretty sure, I THINK it's happening because before you would load your preferences as you joined (which was the cause of bald everyone since species datums weren't initialized), but now it's having everyone query at the same time to load.

This would also explain the lack of being able to reproduce locally, and why it only happens to a few people.

**Comment by clusterfack** [comment]
Probe when this happened to you did you log in early in the round, then log out while it initialized, and then log in slightly later?

I believe this is caused by a runtime in datum/preferences/new

**Comment by Probe1** [comment]
No i'm pretty sure I logged in once but I wasn't really paying attention.

The game restarted, I was there, I did nothing, I realized I had a blank name when looking at Player-Panel-New and checked my setup profile to confirm.

**Comment by clusterfack** [comment]
Too late probe

**Comment by Probe1** [comment]
I have no issue and I must report
