### ISSUE TITLE
Cult Tome Typo

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9603]
https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/game/gamemodes/cult/ritual.dm
Line 377.

> "<span class='warning'>You drag the ghost to our plan of reality!</span>"

**Comment by clusterfack** [comment]
This just got fixed

**Comment by Shadowmech88** [comment]
When?
The repo's current copy of the file still has the typo.

**Comment by clusterfack** [comment]
#9588

**Comment by clusterfack** [comment]
Oh I see he forgot the next line hahaha

**Comment by clusterfack** [comment]
What a nerd

**Comment by Exxion** [comment]
That would be why there were all those line comments on that line in the PR

**Comment by clusterfack** [comment]
Reading is for nerds

**Comment by DeityLink** [comment]
ikr
