### ISSUE TITLE
Floorbot doesn't do anything

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9605]
![dreamseeker_2016-04-23_21-35-20](https://cloud.githubusercontent.com/assets/6526157/14764784/8230f476-099b-11e6-861a-84b1b2909a56.png)
As you can see, even when forcibly dragged on top of a breach and held at gunpoint, it lacks an understanding that it's supposed to be doing something

**Comment by clusterfack** [comment]
Pretty sure it searches for tiles if it has < 50 for some reason

**Comment by 9600bauds** [comment]
well that's just dumb

**Comment by Intigracy** [comment]
Improves floors: No

Gee I wonder why it's not doing anything.

**Comment by 9600bauds** [comment]
"improve" is not the same as repairing
"finds tiles" just makes it pick up tiles from the floor

**Comment by Angelite191** [comment]
It only repairs tiles if find tiles and make tiles when empty are ticked. If else it won't do shit. It also looks for tiles if it's missing a single tile, which is BYOND stupid. Improve tiles will place a tile over the plating which is very silly. 

I fucking love floor bots, but it seems every time I come back to them they're less functional than the previous.

**Comment by Intigracy** [comment]
@clusterfack milestone

**Comment by Zth--** [comment]
I tried looking into this. We should burn all bots code and start again from scratch. Really.

**Comment by 9600bauds** [comment]
Hmmmm, where have I heard that before

**Comment by Intigracy** [comment]
Me

**Comment by PJB3005** [comment]
Port TG bots.

**Comment by d3athrow** [comment]
i was gonna fix this but fuck that bot code.
From what I could see,

> process() called
> check for power and if we're repairing
> do something based on mode
> if idling look for work
> if we have a target do nothing
> if amount of tiles is below 50 hunt for tiles
> if no tiles found try to find tiles to fix
> otherwise try to find a space tile to fix
> if we've got work, try to fix

**Comment by d3athrow** [comment]
never mind i fix
