### ISSUE TITLE
Mask object disapeering inside toolbox

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9607]
(WEB REPORT BY: spetslana REMOTE: 172.93.109.202:7777)
I put this mask object with glowing eyes into a yellow electrical toolbox, and the item disapeered, however the toolbox gained another row of spaces for items to go in it. I couldn't see the mask to take it out but the toolbox still worked more or less.

**Comment by Brolaire** [comment]
> mask object with glowing eyes

????????????????

**Comment by Probe1** [comment]
He's talking about the Happy Mask.

**Comment by clusterfack** [comment]
He just mistook the fact toolboxes can actually hold 14 items, I cant reproduce anything like this
