### ISSUE TITLE
Sec. Role Character Setup Has Advanced Bomb Suit Helmet On

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9609]
(WEB REPORT BY: kinggrimlock REMOTE: 172.93.109.202:7777)

> Revision 5478d4dc33ca2847caf1e298fa3a3e48a2a8e2a8
> 
> General description of the issue
> Security officer roles (Head of Security, Warden, and Security Officers) have an Advanced Bomb Suit helmet on their heads instead of what they would normally wear in the character setup screen.
> 
> What you expected to happen
> I expected my character to be wearing a HoS/Warden Cap or Sec. Helmet in the character setup screen when my preferred role was set to HoS, Warden, or Sec. Officer.
> 
> What actually happened
> My character was wearing an Advanced Bomb Suit helmet instead.
> 
> Steps to reproduce if possible
> 1. Enter Character Setup Screen.
> 2. Click on Occupation Preferences.
> 3. Set your preference for Head of Security, Warden, or Security Officer to High.
> 4. Save your changes, and exit back to the Character Setup screen. Your character will now be wearing an Advanced Bomb Suit helmet.

**Comment by nuklearcellphoneg** [comment]
This is from memory but don't we have a bomb disposals alt role?
