### ISSUE TITLE
Parcel opening with only one arm

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#9617]
#### Description of issue

Opening a parcel with one arm puts it in the missing hand
#### Difference between expected and actual behavior

I don't know what I really expected to happen. I opened a parcel with my one arm, and it put it into my nonexistent hand.
#### Steps to reproduce

Open a parcel with one arm
#### Specific information for locating

Parcel with package wrap, and only having one arm
#### Length of time in which bug has been known to occur

Probably forever.
#### Server revision

c0d0e740b31a46796205b1e5344d9f5b31289dec
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Exxion** [comment]
It should really put it in the same hand it was in before regardless of whether or not you are missing the other

**Comment by kol1th** [comment]
does it do the same thing with two hands?

**Comment by Exxion** [comment]
It currently puts the thing you took out of the parcel in the hand you used to open the parcel rather than the hand the parcel was in, regardless of whether you have one hand or two

**Comment by kol1th** [comment]
i used Z to open it

**Comment by Exxion** [comment]
Oh yeah, you do open it by using it in hand, don't you? I remembered incorrectly.
Either way, it puts it in your other hand
Unless you other hand is full, in which case it probably puts it on the ground
It probably tries to equip the item before having you drop the parcel
