### ISSUE TITLE
Borer chemical warning

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9622]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> Borer Secrete Chemical warning that was added today doesn't work. For example if the host has a sleep toxin, using anti-tox issues a warning that it could overdose.
> 
> What you expected to happen
> No message
> 
> What actually happened
> Message
> 
> Steps to reproduce if possible
> Get a sleep toxin into the host and secrete antitox

**Comment by PJB3005** [comment]
# 100%

**Comment by Intigracy** [comment]
# **TESTED**

**Comment by Probe1** [comment]
![eggplant_png_clipart-469](https://cloud.githubusercontent.com/assets/8550416/14768830/a4e97424-0a19-11e6-8475-65d48c5776d4.png)

**Comment by 9600bauds** [comment]
At least I don't have the full blame now :^)

**Comment by ghost** [comment]
I can't reproduce this locally
![cantreproduce](https://cloud.githubusercontent.com/assets/7598675/14770014/4c165f9a-0a34-11e6-8c13-f29c645de36d.png)
