### ISSUE TITLE
Late joined can't be a borer

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9623]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> If you join after the borer egg has been set, you can't enter it anymore.
> What you expected to happen
> To enter it.
> What actually happened
> Nothing.
> Steps to reproduce if possible
> Let someone lay the egg and join as a ghost afterwards.

**Comment by Killette2** [comment]
I guess until that'd fixed, you can always ghost-join braindead borers.

**Comment by Shadowmech88** [comment]
Except eggs don't hatch without a ghost in them.
So if the egg tries to hatch and no one volunteers, the egg becomes useless. Ghosts can't enter it, and it never produces a braindead borer that ghosts _can_ enter.

**Comment by ihadtoregisterforthis** [comment]
Is this about not seeing the join pop-up if it appears before joining?

**Comment by Intigracy** [comment]
Click the egg to join the list of candidates.

**Comment by Shadowmech88** [comment]
I'm pretty sure this is fixed, as eggs now continually poll for ghosts.
