### ISSUE TITLE
Chemmasters don't update from alt click

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9624]
(WEB REPORT BY: **invoid9** REMOTE: `172.93.109.202:7777`)
#### General description of the issue

When you have chemmaster window open and altclick the machine to eject beaker, the infomation in the box does not update. It only updates again once you refresh the machine somehow.
#### What you expected to happen

Information updates when beaker is ejected.
#### What actually happened

It's not.
#### Steps to reproduce if possible

Place beaker in thingy, open chemmaster window, leave it open, alt-click to eject.

**Comment by 9600bauds** [comment]
This is the case for so much shit in the game and it saddens me
