### ISSUE TITLE
Wire shocking nonsense

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9625]
If you touch a wire on the floor with almost any item, you will instantly be shocked as if touching a wired grille.
Why is this a problem? Firstly, because of the exceptions:
This only has a 50% chance of happening when using a wirecutter. To cut the wire. So already not only does this make no sense, but the most malicious use is excempt (i've actually snipped the entire grid during malf without any gloves because I knew of this). Also, this won't happen when using a glass shard.

And second, because it's prone to happen accidentally. I've had this happen to me:
- When tearing up floortiles to replace them with carpet, and accidentally clicking the wire underneath (twice)
- When trying to flash an escaping prisoner in cuffs after he ran into maint (since the wires are always exposed there)
- When trying to repair some wiring after an IED (you won't get shocked if you click the floor, which completes the wiring harmlessly, but if you click the wire it does shock you for some incomprehensible reason)
- When trying to use a health analyzer on someone and they stood up just before I clicked (oh come the fuck on)

I mean, you're just lightly tapping the insulated wire with an item, you're not even damaging it, BUT if you actually do cut it apart then it's only a 50% chance to happen!!

I think this is pretty backwards-ass and a strictly negative hazard to have in the game

:zap:

**Comment by FudgePucker** [comment]
Why is glass shard better than wire cutters anyways?
So the rubber insulated wire cutters is a worse choice than a jagged shard of glass.

There should be a chance for your hand to slip and touch the exposed wire when using a jagged shard of glass.

**Comment by Shadowmech88** [comment]
Wirecutters in-game conduct current, so it'd stand to reason that for some reason they just aren't insulated.

**Comment by 9600bauds** [comment]
You can't actually cut the wire with the glass shard

**Comment by MercuryDoll** [comment]
My assumption was that the 50% shock chance was an emulation of arcing. In reallife when you use a regular wirecutter (which usually has rubber-insulated grips) and cut a hot wire, depending on the power that runs through it there's a chance it creates an arc that potentially could go around the insulation and shock your bare hands.
I agree though that touching wires with anything that isn't supposed to cut (knifes etc) should not shock you.

**Comment by gbasood** [comment]
Things that shock you when you accidentally click on a wire:
- Bandages/bruise packs/ointment!
- Health scanners!
- GUNS!
- **LITERALLY ANYTHING THAT IS NOT SPECIFICALLY MARKED AS NON-CONDUCTIVE**

Why?
Because of this:

``` DM
wire attackby handling cable coils, rc1s, wirecutters, multitools
THEN
    else
        if(W.is_conductor())
            shock(user, 50, 0.7)

/obj/proc/is_conductor(var/siemens_min = 0.5)
    if(src.siemens_coefficient >= siemens_min)
        return 1
    return
```

Sure, doesn't matter that the cable itself is insulated enough that walking on it doesn't hurt you, just go ahead and make anything conduct through it, it's fine

This is shitty and we should be handling things that we DO want people getting shocked on instead of shocking everyone for everything.

**Comment by ComicIronic** [comment]
> This is shitty and we should be handling things that we DO want people getting shocked on instead of shocking everyone for everything.

Then set the default value of siemens_coefficient to something higher than 0.5. Most stuff isn't that conductive in the first place.

**Comment by 9600bauds** [comment]
The conductivity of the item isn't the main point, it's which things shock you
