### ISSUE TITLE
"Space pod - transit tube" near  wall bug

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9628]
(WEB REPORT BY: tugamix666 REMOTE: 172.93.109.202:7777)

> Revision 
> 271435f8425089df85bac323f3594c0e62bd9fde
> 
> General description of the issue
> When in a space pod if traveling over transit tubes you can get inside a wall, and then just move beyond the wall.
> 
> What you expected to happen
> Not go through the wall.
> 
> What actually happened
> I went through the wall.
> 
> Steps to reproduce if possible
> get in a working space pod, find some transit tubes that are near a wall, travel over them in direction of the wall. You should be either inside the wall or completly through it.

**Comment by Exxion** [comment]
I've definitely seen this reported before, but I can't find the report

**Comment by Shadowmech88** [comment]
Maybe it was reported while we were on Gitlab.

**Comment by Exxion** [comment]
I only even looked at the Gitlab for like a week after we moved over before I gave up on it

**Comment by Ephx1** [comment]
Not only was it on Gitlab, but I reported it on that weird issue reporter that N3X15 set up, Red something.
Point is, this shit's been around forever.

**Comment by Exxion** [comment]
Well
I found it
#7111
