### ISSUE TITLE
Make syndicate simple mobs explode on death

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9632]
They are easy enough to kill and give the highest end loot when they die.

Giving them "explosive implants" so they don't drop phat lewt would dramatically increase the value of using them as mobs.

Y/N?

**Comment by ihadtoregisterforthis** [comment]
What could go wrong? :^)

**Comment by Probe1** [comment]
It would be sane to give melee syndicate mobs a smaller explosion radius and gib so they aren't suicide bombers, yeah.

**Comment by ihadtoregisterforthis** [comment]
I was going to suggest make them push foward on low health.
In any case they shoudn't be able to destroy plating.

**Comment by MercuryDoll** [comment]
Like C4 explosions that aren't enough to damage the ship but strong enough to hurt anyone standing nearby? Make them scream "allahu ackbar!" too.
