### ISSUE TITLE
Device Analyzer Doesn't Work On Chef Machines

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9633]
(WEB REPORT BY: seymourbutts REMOTE: 172.93.109.202:7777)
Device Analyzers don't function on chef machines, and there's no other boards or methods of construction to build them.

**Comment by Probe1** [comment]
Which ones..

**Comment by Killette2** [comment]
I'd guess deepfrier, grill, cereal maker, ice cream machine, ect. I'm a bit drunk so may be wrong.

However, microwave and gibber should work just fine.

**Comment by ComicIronic** [comment]
Yeah, it wouldn't work on anything without a circuitboard is normally the behaviour.
If someone would fix them to take a board and components, that would be good.
