### ISSUE TITLE
Should the outposts on the asteroid be electrified?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9634]
I held a vote.  I'd like to hear about it on github before I personally do anything.

Custom vote started by Probe1.
Should MEME OPTION the research and mining outposts on all maps have electrified grilles to deter the you know who from breaking in?
Type vote to place your votes.
You have 60 seconds to vote.
Vote Result: Yes with 11 votes
No had 1 vote

I think this is reactionary but people have been asking for it. I have not added it yet but may if no one objects.

**Comment by Shadowmech88** [comment]
The outpost isn't connected to the main power grid.
How badly would the shocks really hurt?

Not only that, but it is _piss easy_ to simply use a shard of glass to break down the electrified grilles.

**Comment by 9600bauds** [comment]
Shards were supposed to take a long fucking time to get through a grille.
This got changed here: https://github.com/d3athrow/vgstation13/commit/62ec91d8d695eb5f8c6cbbeb64f16d6cab301101
Until that's reverted, electrified grilles are going to continue being a joke. And probably are still going to be a little bit of a joke afterwards.

**Comment by 9600bauds** [comment]
m o b i l e

**Comment by Probe1** [comment]
What you both said was my concern.

**Comment by Shadowmech88** [comment]
Glass _anything_ really shouldn't be able to damage metal _anything_. Unless the metal grilles are a mesh like steel wool, it really isn't logical to be able to break it down with just a shard of glass.

**Comment by 9600bauds** [comment]
> Glass anything really shouldn't be able to damage metal anything.

glass spears can't melt MoMMI beams

**Comment by 9600bauds** [comment]
Alternative solution: Make grilles be damaged by thrown items. Remove the glass shard's stupid shock resistance. Make it so that the classic perma escape consists of THROWING the glass shard over and over and over and over at the grille.

**Comment by Shadowmech88** [comment]
That still wouldn't make them any less of a joke.

**Comment by 9600bauds** [comment]
At least it wouldn't be as lighting fast as it is right now

**Comment by kol1th** [comment]
probably should be but glass also shouldn't be shock-proof

**Comment by uazuaz** [comment]
add a furnace circuit board inside vox outpost, so the vox can build their own furnace and smelt their ore without the need to break in the mining outpost

**Comment by Shadowmech88** [comment]
Is glass not an electrical insulator IRL?

**Comment by uazuaz** [comment]
if you use a glass shard to break a metal grille IRL:

-it's very likely that it breaks without dealing any damage to the grille
-it's very likely going to cut your hands and let them bleed

**Comment by Shadowmech88** [comment]
Well yeah, but @kol1th said that glass shouldn't be shock-proof.
I agree that it shouldn't be capable of destroying metal grilles.

**Comment by NigglyWiggly** [comment]
Secret Repo PR to make glass shards unable to cut metal grilles and make them slice up your hand and cause bleeding when you try to use them WHEN

**Comment by PJB3005** [comment]
Just a friendly reminder.

Dylan for once made a good chance and snuck a change making shards conduct into a PR of his. 

People became furious.

**Comment by FudgePucker** [comment]
Oh you use wire cutters with an insulated handle it arcs around and shocks you, but the 100 times folded glass shard just scares away the electricity and instantly destroys the grille.
