### ISSUE TITLE
I want server polls for admins.  We need it.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9638]
https://github.com/tgstation/-tg-station/pull/11919

This.   I want this.   The plastic versus gold/silver/uranium is the latest reason why.  Asking people to register on forums and expecting no one to register twice to get two votes, and expecting admins to carefully check registrations for that, it's crazy.  

We need this.

**Comment by Intigracy** [comment]
@D3athrow

**Comment by Probe1** [comment]
He knows.  This is an anchor post so  I can link him.  Also he has several thousand @'s on github.

**Comment by d3athrow** [comment]
go ahead and port it. just know we still use the erro_ database prefixes

**Comment by Probe1** [comment]
![1455520907594](https://cloud.githubusercontent.com/assets/8550416/14872886/9d67cfe6-0cbe-11e6-9ef1-c8171a558366.gif)
