### ISSUE TITLE
Moneybags are limited to 7 items

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#9641]
#### Description of issue

The moneybags that are created when crafting coins at the coinpress are limited to 7 items. The only exception seems to be the coinpress itself, if you have a bag with 10 coins, take one out and try it to put it back in, it says it's full.
#### Difference between expected and actual behavior

To fill all these coins back into the bag.
#### Steps to reproduce

Acquire materials, make coins, take coin out, try to put it back in.
#### Server revision

f65a28b3b5641cd91b8ca5e5d8fa3584c7df973e Current 
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
What limit do you think the money bag should be limited to?

**Comment by ihadtoregisterforthis** [comment]
### ∞

**Comment by Probe1** [comment]
https://www.youtube.com/watch?v=ON-7v4qnHP8

**Comment by ghost** [comment]
Can't do infinite, will 99999 do?

**Comment by Iamgoofball** [comment]
yes you can

just put in INFINITY its a define

**Comment by ghost** [comment]
Oh, thanks goofball!

**Comment by ghost** [comment]
Alright, testing has shown that the game ends up pausing for a few minutes if you try to unbag/pick up about 1000 gold coins at once on a private server.

How's 300 max slots sound?

**Comment by ghost** [comment]
Additionally, they can be used in place of ore bags, and the mint produces infinite of them (just needs to be making coins at the time)

This is some fucky balance stuff

**Comment by Iamgoofball** [comment]
@Skullyton You just need to cap the amount it can pick up at once. Only allow picking up/unloading 100 at a time. or make it do it over time.

**Comment by MercuryDoll** [comment]
300 Coins limit sounds fine, though personally 500 sounds better. Are you making moneybags stack coins, similar to stacks of cash?

**Comment by Zth--** [comment]
Actually the best solution here is to make coins stackable

**Comment by clusterfack** [comment]
I think there is partially created code somewhere to stack identical items

**Comment by PJB3005** [comment]
Yes, there is, and it's a single boolean.

**Comment by nuklearcellphoneg** [comment]
Does the money bag fit on a suit slot?

INFINITE SOUNDS A BIT MUCH

**Comment by ghost** [comment]
@Iamgoofball That'd just make unloading them a pain in general, plus the way you get money bags could do with a rework anyway, as it just spawns a new one each coin if there wasn't one there to put the coin in, so you can make a whole lot of the bags if you just keep moving them.

How about adding it to the biogenerator instead, and making the coins just drop to the floor? It acts like an improved mining bag anyway as it can pick up ores.

@clusterfack Using that so the UI doesn't crash you if you take a look inside, seems fairly stable contrary to the comment next to where it's set to 0.

**Comment by MercuryDoll** [comment]
Remove the code that spawns moneybags and place two of them in the room of the coinpress. The biogenerator already is able make moneybags i think, but even if it doesn't, miners would just use lockers or boxes instead.

**Comment by Zth--** [comment]
Yeah, biogenerators are able to make moneybags. I didn't touch coinpress code because it's really scary, but it actually needs some rework
