### ISSUE TITLE
Add Ministation to map pool for lowpop

### ISSUE THREAD

**Issue by xpcybic** [d3athrow/vgstation13#9646]
It still works and compiles (and if it doesn't it won't take too much work to fix) and I've seen a lot of support for it in the thread. At the very least it'll split the vote and lead to fewer rounds on taxi (which seems best played in moderation).
Based on remarks in #9640

**Comment by Brolaire** [comment]
Would enjoy this

**Comment by MercuryDoll** [comment]
Hell, if it compiles throw it in. Even if it's only half working, as long as vital stuff isn't completely busted and the map is playable without admin intervention it might be a great autismfort for lowpop.

**Comment by iwillkillmyself** [comment]
A few issues I remember of:

*map not in the 500x500 format, no vaults
*telecomms broken
*termogenerator setup no longer functional
*pods to the AI satellite not working
*medbay lacking body scanner, bone gel, bone setter and fix'o vein
*outdated shuttles, none working
*no ion rifles at the armory
*all jobs are in, should make a code modification so we only can play with the jobs which the station was made for
*no cameras anywhere
*no captains laser in bridge and other tons of traitor wanted items missing
*jukeboxless bar

**Comment by MercuryDoll** [comment]
Vaults are not needed yet.
Needs to be fixed.
If you mean the TEG, that thing never worked
Pods and shuttles need to be fixed.
Medbay and armory can be easily stocked.
Not sure if that's easily possible, but people tend to pick the vital jobs first anyway.
Considering the size and the intended population, i don't think we need cameras that badly.
Traitor items shouldn't be hard to stock up on either.
OH THE HUMANITY

**Comment by PJB3005** [comment]
> TEG never worked

You mean the TEG setup on mini or the TEG in general?

**Comment by MercuryDoll** [comment]
TEG in general. Until i see videoproof of a TEG running 5 minutes without jamming once i refuse to believe it is functional.

**Comment by SerWind** [comment]
Yes please. 

Also Dorf station when? Only as a bus option though I guess, that gimmick would probably get old on lowpop quick like.

**Comment by MercuryDoll** [comment]
Dorf station will need to be bussed sooner or later. When it goes from deadpop to morningpop people will cry for something to happen and then there's nothing better than the dorfmines being overrun by all sorts of monsters.

**Comment by Killette2** [comment]
Why don't we make new stations instead of import ancient ones with the tons of outdated problems that come with them?

**Comment by Shadowmech88** [comment]
Hey, if you've got a great idea for a new station, I'd welcome it.
Let us know when you finish making it.

**Comment by ihadtoregisterforthis** [comment]
It's easier to take something really old and rebrand it than actually sit down an invent something.

**Comment by Brolaire** [comment]
id murder four people for a station shaped like the engi ship from FTL

**Comment by Shadowmech88** [comment]
I wonder how difficult it would be to code a "moving" ship-station, in that the station itself does not move, but anything on a space tile on the station's Z-level moved at a constant speed in the direction opposite the ship's bow, to give the illusion of the ship itself moving.
Could even have it encounter drones and other space stuff as it "moved."

**Comment by MercuryDoll** [comment]
You mean like the outside of the escape shuttle when it's moving to Centcomm? The challenge would be to make it go from static to dynamic, so it can be toggled on and off for events.

**Comment by Hoshi-chan** [comment]
More maps!

**Comment by xpcybic** [comment]
I'm working on it. There are a few more things to be fixed, including what @iwillkillmyself listed, and then we shall pray to the chicken man to do the server things and add it to map voting.
PR SOON
