### ISSUE TITLE
vgstation/obj/xenoarch.dmi DELET THIS

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9650]
https://github.com/d3athrow/vgstation13/tree/Bleeding-Edge/obj

**Comment by PJB3005** [comment]
Sure

**Comment by Intigracy** [comment]
Why?

**Comment by Probe1** [comment]
because that is not where icons go

**Comment by Intigracy** [comment]
Why not move it rather than delete it?

Especially if it's being used.

**Comment by Probe1** [comment]
Why would it be in use?   vgstation/obj/xenoarcheology.dmi is a duplicate of vgstation13\icons\obj .  Deity fugged up a long time ago and no one noticed.

**Comment by Intigracy** [comment]
nvm then
