### ISSUE TITLE
Make admin announce text larger

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9652]
#### Description of issue

Admin announce text with the admin verb Announce is the same size as regular text.  It would be indistinguishable if not for the color and font.  This makes it largely worthless unless you use a ton of line breaks to push it out to its own and it should be larger.
#### Specific information for locating

verb = Announce

**Comment by Exxion** [comment]
If I'm not mistaken, you should be able to get around this by using `<span style="size:[some appropriate font size]pt">` until this gets changed
Unless announce gets HTML encoded, but that would be stupid

**Comment by Probe1** [comment]
That's a good point but I think it should be a default.
