### ISSUE TITLE
GHOST HANDS ON THE WASHING MACHINE PANIC

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9656]
ghosts can open and close the washer.

**Comment by nuklearcellphoneg** [comment]
Feature

M-maybe

**Comment by Probe1** [comment]
A bug is in the eye of the beholder.

**Comment by 9600bauds** [comment]
I was told this was a 'feature'

**Comment by Exxion** [comment]
As long as they can't interrupt a cycle in progress, not a big deal
I'd say leave it
It's less significant than rotating chairs, after all

**Comment by clusterfack** [comment]
We've talked about this once or twice already and I'm fairly sure there was a concensus that ghosts can and should be able to fuck with washing machines

**Comment by 9600bauds** [comment]
feechurr

**Comment by Probe1** [comment]
i'll SEARCH first next time
