### ISSUE TITLE
Deadchat not logged if ghost is still in their body.

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9658]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
I went to look through the logs to see about a conversation I was pulled out of due to being cloned and I noticed that anything I said while I was within my body was not logged in our logs for some reason.

**Comment by Exxion** [comment]
Oh yeah, I guess I did forget to report this

Also, on a related note, ghost emotes are never logged, I believe

**Comment by gbasood** [comment]
Think this might be a duplicate
