### ISSUE TITLE
Allow people to put nametags on unnamed simple animals to give them a name.

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9659]
Now you can name your corgi shipment!
Possibly make nametags let you stylize your pet as well, to some extent
(p.s. don't let people rename Ian, Poly, Runtime, or already-named animals)

**Comment by Shadowmech88** [comment]
You can already do this with a labeler.
However, "corgi (152) (Ian Junior)" doesn't look very nice.

Probably the easiest way would be to give the functionality to pens, in the same way that a pen can rename a food item.

**Comment by liltiptop** [comment]
New item: 
We already have coins on strings, right? Why not add that to an animal and make it a collar? Then you can name your pet.

**Comment by gbasood** [comment]
could just be a dogtag even
orderable from merch computer or something because where else are we gonna put them
also should prevent people from naming named pets

**Comment by gbasood** [comment]
![image](https://cloud.githubusercontent.com/assets/2076607/21756113/931e1798-d5d1-11e6-915c-02b697654e50.png)
from @SkowronX

**Comment by SkowronX** [comment]
like I said, that one needs a little cleanup
