### ISSUE TITLE
Character setup is more broken than ever

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9661]
Not only is it failing to load characters at round start now, but when it fails to, it sometimes randomly generates a character and _saves over the slot that was loaded._

This is even worse than having to re-select hair every round.

**Comment by MercuryDoll** [comment]
There's more peculiarities with it. It doesn't display robotic prosthetics on the right arm properly, which carries over to your observer ghost.
Many people can also confirm that the colors you pick aren't saved in the Unique Identifier (UI), resulting in cloning having odd results, even if a UI syringe was used.

**Comment by PJB3005** [comment]
We should just revert it.

**Comment by Hoshi-chan** [comment]
When I loaded my sec character a few hours ago, the display showed her with a bomb disposal hood on. It displayed my botanist character as wearing some really strange backpack, too.

**Comment by xpcybic** [comment]
@MercuryDoll the hair color thing might be older than this - I saw a changeling transform into me and get the wrong hair color months ago.

**Comment by Intigracy** [comment]
> Not only is it failing to load characters at round start now, but when it fails to, it sometimes randomly generates a character and saves over the slot that was loaded.

Nah that happens every time it doesn't load your save. It would have happened before (it's intended for new players who don't have saves) except it was broken.

Those color things have issues up already and are not related.
