### ISSUE TITLE
Adding HoP's bell to flatpack fabricator doesnt work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9662]
(WEB REPORT BY: governor123 REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> scan the bell, put print blueprints, stick it in the fabricator
> What you expected to happen
> Print a bell
> What actually happened
> Says it is already in there every time I nsert it but it is not in there.
> 
> Steps to reproduce if possible
> mentioned above

**Comment by Exxion** [comment]
You probably already had a different desk bell in there

**Comment by gbasood** [comment]
i mean
it SOUNDS like it's just copying the bell and you expect it to be the HoP's bell for some reason
but they're not unique bells
they just have diff frequencies

actually if they're coded as children of whatever the bell type is that might end up with something weird

**Comment by Shadowmech88** [comment]
Tested locally, unable to reproduce. I was able to add multiple different desk bells to the reverse engine.
It's possible that they *used* to all have the same path and be varedited, but they don't now.
