### ISSUE TITLE
Map renders way out of date

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9663]
(WEB REPORT BY: tnepr REMOTE: 172.93.109.202:7777)
All the map renders that appear when you click on the in game button are way out of date. rip nexis

**Comment by Probe1** [comment]
We know.  The way its done is broken.

**Comment by MercuryDoll** [comment]
Why don't we replace the map button links with the same map images for the medical monitor or the bhangmeter? I usually use that button on a map i don't know that well yet to find any of the departments.

**Comment by ghost** [comment]
It's a simple fix, we need to create our own N3X15 to fix this. Maybe if we get someone to shave their head, watch furry porn and get hypertension

**Comment by Probe1** [comment]
I'll get right on that.

**Comment by SysadminJeroen** [comment]
@dylanstrategie I can do that.

**Comment by 9600bauds** [comment]
did those steps but now I got a job at Microsoft instead??? please help

**Comment by clusterfack** [comment]
I fixed this msyelf
