### ISSUE TITLE
Safes can only be incremented by 5 but have codes that aren't divisible by 5, making them impossible to open.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9668]
#### Description of issue

The input on a safes code can be input in increments of 5.  The code itself can be any number (38, 49, 102, whatever).  Thus the safe becomes impossible to open.
#### Specific information for locating

obj/structure/safe
#### Length of time in which bug has been known to occur

Forever?  Related issue https://github.com/d3athrow/vgstation13/issues/7925

**Comment by 9600bauds** [comment]
Did you look at the "code" via VV? The safe numbers are actually multiplied by 5 in the topic() so a code like 100 is actually tumbler position 20
I'm 100% sure safes work consistently

**Comment by Probe1** [comment]
I haven't seen anyone unlock one in forever.

**Comment by 9600bauds** [comment]
I have seen me unlock one as a bored greyshit 3 times out of 3

**Comment by 9600bauds** [comment]
Also wasn't there that round in Deff where someone got the energy axe from the safe?

**Comment by Iamgoofball** [comment]
safe code is so fucking old

**Comment by Exxion** [comment]
I've only once tried to unlock a safe and I succeeded
Last time I personally saw someone with the e-axe on Deff (meaning they opened the safe) was just a few weeks ago
Safes work

**Comment by 9600bauds** [comment]
![dreamseeker_2016-05-12_02-33-16](https://cloud.githubusercontent.com/assets/6526157/15205106/e28cc784-17ea-11e6-9a33-76072ab589e9.png)
Still works 100% of the time 12/05/2016

**Comment by clusterfack** [comment]
Good to know it'll keep working for about the next seven months then
