### ISSUE TITLE
Most vending machines cannot be emagged

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9677]
Which means you can't emag an Engi-Vend to get a multitool or holomaps.
They don't have the EMAGGABLE flag. That is the only reason they can't be emagged.

**Comment by ComicIronic** [comment]
They have emag inventory?

**Comment by gbasood** [comment]
I was under the impression that emagging it would give you access if you didn't have an ID
And I think that's its behavior if it is emagged via VV or emag_act or whatever

**Comment by Eneocho** [comment]
Emagging does remove access checks from vending machines now.
