### ISSUE TITLE
Tables/Reinforced Tables

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#9683]
#### Description of issue

Tables take no time to construct if you have the parts
#### Difference between expected and actual behavior

I can run down one tile maint, construct a table, and be gone
#### Steps to reproduce

Play the game, use your imagination

**Comment by Probe1** [comment]
I've been thinking about this too but didn't want to get a controversial tag on a PR.  

It does need to be done.

**Comment by Shadowmech88** [comment]
It can be done, but how often do you see people doing it?

**Comment by Exxion** [comment]
Almost never, but I bet people will start now that they've been given the idea

**Comment by nuklearcellphoneg** [comment]
1) I could be wrong but it's an easy fix(adding construction time might not be the best balance)

2) Other than deconstructing and a few powers and so on, there's no way to cope other than go around

Alternate ways of alleviating with would be not being able to store them in backpacks and maybe only add construction time to reinforced, as regular tables can simply be wrenched.

BECAUSE to be honest, I can understand being able to hold one table

**Comment by 9600bauds** [comment]
I've heard of this one a few times but I've never heard of it actually being used

**Comment by nuklearcellphoneg** [comment]
The table itself shouldn't really need a change- but because it takes a moment to deconstruct a reinforced(via welding tool) I think it should take a moment to construct the reinforced.

**Comment by Exxion** [comment]
It takes several seconds to deconstruct a table, reinforced or not
Reinforced just takes longer

**Comment by nuklearcellphoneg** [comment]
You're right, I remembered that wrong. I forgot about wrench, wrench, wrenching, and then waiting before moving onto the next set of tables.

So yeah, so I'll stand by it and say they need a few ticks of construction time.

**Comment by 9600bauds** [comment]
Desu that could get annoying if you're trying to build a bar or something, the real issue here is being able to carry table parts in your backpack

Why would you even need to? You only have space for a tiny amount of tables anyways

**Comment by Exxion** [comment]
I'd say make it faster to deconstruct non-reinforced tables and give reinforced ones construction time

**Comment by 9600bauds** [comment]
That:
- has balance concerns that don't involve this issue (makes it extremely fast for anyone to dismantle the entire bar void of tables)
- doesn't really fix the issue (unless you were 100% expecting the other guy to plop a table and had a wrench in hand, and he STILL benefits from it)

**Comment by Exxion** [comment]
People dismantle the entire bar every third round anyway. They just take about a minute to do it.

And yeah, it would still benefit him to do it, just not nearly as much
As it stands, dropping the table is a guaranteed escape, as even if the person has a wrench in their hand, it takes so long to dismantle it that the escaping person can go far enough that there are too many branches in maint to guess which they went down

But your solution works, too

**Comment by Shadowmech88** [comment]
I feel like if the person thinks ahead far enough to have table parts prepared, they deserve the escape.
I don't think build time should be added to tables, for this reason anyway, unless this strategy becomes very widespread.

**Comment by 9600bauds** [comment]
Eh if you prepare ahead you could probably just splash the floor with water to cover up your escape pretty well and it wouldn't be as griefy as now having a reinforced table blocking the middle of maint that needs eye protection to get rid of

**Comment by Exxion** [comment]
At the _very_ least, give reinforced tables construction time

**Comment by Shadowmech88** [comment]
I agree with the reinforced table construction time, just because they're such a nuisance to deconstruct since you need a welding tool and eye protection.

**Comment by Exxion** [comment]
It would also prevent accidentally placing them in the wrong place

**Comment by MercuryDoll** [comment]
Construction time on **reinforced** tables sound completely reasonable.

**Comment by ComicIronic** [comment]
Another reason to add table climbing

**Comment by Probe1** [comment]
gb2 tg

I wouldn't really mind table climbing we're too set in our traditional reasons for not wanting something.
