### ISSUE TITLE
Have to manually click on tiles for mining

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9684]
(WEB REPORT BY: aceedex REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b568fab0d12fed2021d087c8aef247cdd2d3b8fe 
> 
> General description of the issue
> Instead of just bumping into walls and starting to mine, now I need to go around clicking on em to start the mining proccess
> 
> What you expected to happen
> To just shoulder tackle walls to make minerals appear
> 
> What actually happened
> The mining proccess is now a giant pain in the bootyhole that would only be enjoyed by a legitimate mental patient
> 
> Steps to reproduce if possible
> Grab a pickaxe and try to mine

**Comment by jknpj** [comment]
I wonder why this is happening. You can still dig rocky debris normally, but walls require your full attention, a steady hand to be manually clean

**Comment by Exxion** [comment]
#9673 
@gbasood

**Comment by gbasood** [comment]
@Exxion Clusterfack thinks it's a runtime, not the bumpcode change
And also if that even IS the thing that broke it then it really shouldn't work that way.

**Comment by Exxion** [comment]
I don't see any relevant runtimes in the log before this was reported, but I'll test things

**Comment by Exxion** [comment]
Local testing has confirmed that the cause is, in fact, #9673

**Comment by PJB3005** [comment]
:100:

**Comment by gbasood** [comment]
I don't see why we should revert that change because it broke mining
Someone should fix this for just mining, there is no good reason to have duplicate Bump() calls

**Comment by Exxion** [comment]
I didn't say revert it, I just said it was the cause
But a better fix is just to make the other Bump() call not break
