### ISSUE TITLE
Sometimes people are unable to click on anything (with temporary fix in description)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9692]
If this happens, use this SDQL query to temporarily fix it for everyone currently in round:
`UPDATE /obj/screen/clicker SET plane = -10`
Or use VV to modify anyone's clicker plane to -10. Should be in their mob.client.screen list
~~I think I fixed it in a PR but who knows anymore~~

**Comment by gbasood** [comment]
I really can't reproduce this locally at all so I have no idea what's going on
I'll have to try again later

**Comment by clusterfack** [comment]
Fixed it
