### ISSUE TITLE
Add 'toggle ghosts' button for ghosts

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9693]
We can do this now more easily because of planes! Woo!

**Comment by nuklearcellphoneg** [comment]
Will this fix toggle darkness removing ghost sprites?

**Comment by gbasood** [comment]
They could be separated yeah but until someone does that no

**Comment by nuklearcellphoneg** [comment]
That would be nice.

**Comment by Intigracy** [comment]
Are we on 510 now?

**Comment by PJB3005** [comment]
Yes

**Comment by ghost** [comment]
oh I can do this with planes
