### ISSUE TITLE
Weapon Recharger Availability

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9696]
Weapon rechargers are currently not constructable through any means whatsoever.
Should they be?
Perhaps via a circuit board obtained with high-level R&D research?

**Comment by Exxion** [comment]
Maybe we should also make it possible to remove the cells from weapons so cell chargers can be used as ghetto rechargers
Currently, you can remove the cell from a stunbaton, but no other weapons (as far as I know) despite the fact that all of them technically have internal power cells

**Comment by Shadowmech88** [comment]
A problem with that is that now you've effectively given magazines to all energy weapons.
Instead of having to carry multiple eguns or visit the recharger periodically, you can just carry one egun and a backpack full of spare batteries.

**Comment by Exxion** [comment]
That can be _somewhat_ circumvented by making replacing the cell take time so that it can't be changed out in the middle of combat, but yes, it would still do that for, say, raiding vaults.

**Comment by PJB3005** [comment]
Or the fact that hyper cap cells in eguns would be op.

**Comment by clusterfack** [comment]
They definitely should not be

**Comment by MercuryDoll** [comment]
In a PvE environment (vaults) that would be fine but e-guns are mostly used in PvP cases. And yeah, people will want hypercap cells to allow for more shots. I don't really want to see someone running around with a lethal laser that can shoot like 25 times before it runs empty, just to have them run into maint and switch the battery for another 25 shots within a few seconds.

**Comment by aceedex** [comment]
Make it reproduceable through the flatpack fabricator only. Gives mechanics something to do

**Comment by ghost** [comment]
Yeah, just do it like shoulder holsters are. Gotta go scan it, gen fab/flatpack and it needs the rare materials so it's not a roundstart make 500.
