### ISSUE TITLE
Add a tradeship for traders?

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9699]
[Image in full](http://i.imgur.com/N3LmHHW.png)

![image](https://cloud.githubusercontent.com/assets/8550416/14863690/bd103430-0c84-11e6-9b67-3acc965de4ed.png)

I've consistently seen requests for the vox to have a legitimate way to get to the station for trade purposes.  Do we want this?

I made a mock up real quick to give an idea of how it would work.  An added bonus would be using a report whenever it docks so they can't sneaki breeki aboard.  The items are just filler to paint the picture and not final version.

@unid15 this is your baby so your feedback matters the most to me but everyone has a stake and opinion to share.

**Comment by Shadowmech88** [comment]
Is there a system in place to prevent a ship from moving somewhere if there's another ship at the location? If the trader ship uses the station's south auxiliary docking, we may run into issues where the trade ship docks on top of the salvage shuttle, or vice versa.

**Comment by MercuryDoll** [comment]
Considering those places/airlocks are otherwise unused/only used in rare cases, i'm all for it if only to stop them from breaking into the science outpost/mining station every round only to realize they can't use the shuttle console anyway.

**Comment by Probe1** [comment]
@Shadowmech88 Yes.  Shuttles have a variable for "Destroy_everything" that is by default 0 and can be varedited to 1 by admins.

**Comment by Exxion** [comment]
I'm not clear on whether or not shuttles still need exclusive areas with the whole shuttle datums system (go ahead and yell at me but that happened while I wasn't looking), but if they do, then we couldn't have overlapping shuttles anyway

**Comment by Shadowmech88** [comment]
So it won't destroy the stuff under it, but will it prevent the shuttle from moving there altogether?

**Comment by ghost** [comment]
What about adding a small trading area on that dock or near cargo for that purpose? It encourages RP and serves as a small access control for vox on the station if they don't have IDs.

About the issue with stuff standing in the docking area: we could define a few ship size standards for every dock so you can only dock in a dock (yo dawg) that is equal or greater than your ship class. Also, we could add light beacons just outside of the docking area that start flashing when a ship is moving towards that dock.

**Comment by Intigracy** [comment]
Remove raiders, give traders the raider shuttle.

**Comment by Shadowmech88** [comment]
Warning lights for docking areas sounds like a great idea _in general_.

**Comment by Probe1** [comment]
@Shadowmech88 Correct.  It can but not by default and requires coding or admin intervention.  There is no system in place for say, moving a shuttle to a parking lot if another shuttle wants to dock there.  Admins can do it by hand in game by making a new docking port tied to the shuttle in question. 

@Exxion Shuttles work by having pairs of dock ports.  They are visible to ghosts in game as red and blue arrows.  The shuttle itself holds a blue docking marker and when it is moved to a dock port that blue marker will align one tile below the red destination docking port.  The red destination docking ports can be unlimited in number and are shown as the options you can select when jumping a salvage, nuke, vox, mining, or research shuttle.  In the case of the last two, there is only a single option.  

Shuttle consoles can be by default restricted from silicon access, require ID access, or be restricted from players.  With additional variables a passcode system could be added.  I have in the discussion suggested VT be given a round-unique password in their roundstart notes that unlocks a shuttle console (or ghetto cargo system console that was discussed and is an entirely separate issue)

@wwjnc What does that have over the trade area being directly in the shuttle?  How would this resolve the current issue of VT vandalism to gain entry to the station and legitimate alternatives to bring wares to the crew?

**Comment by ghost** [comment]
@Probe1 if the trading area is the shuttle itself then disregard my first paragraph

**Comment by Probe1** [comment]
Yeah that's the shutters bit.  The rtables are a place to put goods, the shutters with accompanying buttons allow VT to seal the 'staff' half of the ship.

**Comment by unid15** [comment]
@Shadowmech88 yeah by default shuttles don't destroy other shuttles. Having two shuttles share one destination should 100% work unless one of them is using transit areas, in which case the shuttle _may_ get stuck in transit

**Comment by Exxion** [comment]
@Probe1 I know that much, but what I'm not sure about is whether or not shuttles still need _areas_ defined for where they go
Although I'm guessing not, which is pretty cool

**Comment by Probe1** [comment]
The areas were replaced by docking ports some months back.  Some ships that use "hyperspace" still require their own areas on z2 (escape pods & escape shuttle; nuke op, skip jack, salvage shuttle).

This is to show players that traveling is taking some time to reach their destination.  It can be added and expanded for new shuttles very quickly if needed
Edit:  An area may be required but there is plenty of room for expansion at vox trade posts and said area doesn't need to be at Z1 station levels, so we don't have to worry about space or changing main station maps to fit this idea.

**Comment by 9600bauds** [comment]
Done
