### ISSUE TITLE
Migrate away mission loader to use vault style datums

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9700]
This is above my skill level and away mission loader code is old, unfriendly, and SHIT.  Please.

**Comment by Intigracy** [comment]
Away missions were a bad concept and should be scrapped T B H

**Comment by PJB3005** [comment]
Yep, remove.

The only way to do them remotely right is procedural map generation.

**Comment by Probe1** [comment]
why not both

**Comment by Exxion** [comment]
Which we have tools for, if anyone wants to try it

I might make an attempt at some point, but it won't be good

**Comment by unid15** [comment]
done
