### ISSUE TITLE
Feature Request: Grey Primitive Form

### ISSUE THREAD

**Issue by Brolaire** [d3athrow/vgstation13#9701]
Not sure if someone else ever thought about this or if duplicate issues exist, but all races have both a humanoid form and a primitive, monkeylike form. The only exception? The Greys. Come to think of it, I don't know what happens when you fiddle with the evolution gene of a Grey.
Is there a reason why they don't have one? If not, maybe give them something that looks like the sectoids from XCOM enemy unknown or the martians from Mars Attacks!
There's plenty of popculture to reference, but if people are still strictly against memes and references I guess both of those are no-nos.

**Comment by Killette2** [comment]
It's already sprited, someone posted in the thread a gray mini-me looking thing and it looked amusing. I'd also love the fact that it would be valid, so it looks funny, usually player controlled, and I'm allowed to kill it. I'm in.

**Comment by ihadtoregisterforthis** [comment]
Greys aren't the only ones without monkey form by the way.

**Comment by clusterfack** [comment]
Please search issues before making duplicates #8403
