### ISSUE TITLE
Vox engineering hardsuits do not protect against welding

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9703]
#### Description of issue

The standard vox engineering hardsuit does not have weld protection. Untest about flash protection. Unsure about vox atmos hardsuit or CE vox hardsuit. Unsure about plasmaman hardsuits
#### Difference between expected and actual behavior

standard human engineering suits are flash and weld proof. vox are not
#### Steps to reproduce

be vox enginner. have vox helmet. weld several times. blind
#### Server revision

6a312154d1e595003c7a2603b0ccd136eb2c4804 Current Infomational Settings: 
Protect Authority Roles From Tratior: 1
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ghost** [comment]
Found out the vox engineering suits ARE flashproof

**Comment by Shadowmech88** [comment]
Just tested, all vox Engineering helmets are welder-proof.
