### ISSUE TITLE
Someone make a new universal state (that isn't R-UST)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9705]
Because we need more slow round-ending events they're neat

**Comment by ghost** [comment]
Syndicate invasion, fairly large ship spawns a fair distance away from the station (But still same Z level) and starts firing 'insertion pods' at the station (Act like immovable rods, but stop after a certain time, once they do, spawn a random assortment of space-bound syndicate troops)

Unless you're the absolute maddest and can take out the entire ship by detonating their engine core (Triggers an off-station nuke event for round over), or getting an assortment of items (Emag, 2 auth keys, syndicaptain ID, etc.) to make the ship fly into the nearby mining asteroid (Wouldn't end the round, but will seriously fuck up the roid and anyone who just so happened to be on the ship at the time, while leaving a whole lotta loot around) , it's best to evacuate the station

**Comment by gbasood** [comment]
I like it, there's not enough syndicate-related stuff in game for a group that's supposed to be the big bad rivals of NT anyways, just enemy agents
