### ISSUE TITLE
HUD objects (that aren't /obj/screen/fullscreen) need to have a plane >= 30 / LIGHTING_LAYER

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9706]
So they show up above other things.

**Comment by ComicIronic** [comment]
Above what other things?

**Comment by clusterfack** [comment]
30? Surely we have a define for that :^)

I assume he means the lighting plane or something

**Comment by gbasood** [comment]
yes

**Comment by ComicIronic** [comment]
LIGHTING_LAYER

**Comment by gbasood** [comment]
that exists NOW sure
when I made this it didn't

**Comment by ghost** [comment]
What do you mean by this

**Comment by gbasood** [comment]
It isn't really relevant anymore I think
