### ISSUE TITLE
Scoreboard did not list spells purchased by wizard

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9708]
![dreamseeker_2016-04-27_18-35-36](https://cloud.githubusercontent.com/assets/8550416/14870225/eafee4a0-0ca6-11e6-913a-06a96663717d.png)

**Comment by gbasood** [comment]
What spells did he buy?
Can it be reproduced?
Actually, DID he buy spells or only items?

**Comment by Probe1** [comment]
Its right there in OOC.

**Comment by Konater** [comment]
I think spells only get listed if they're alive and kicking

**Comment by Intigracy** [comment]
Probably had to do with the deleted mob, yeah.
