### ISSUE TITLE
Client Closes when attempting to connect to server

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9709]
#### Description of issue

Multiple people are reporting that their Dreamweaver client cannot connect to the server, and that the window closes after the connection closes. If we attempt to connect again, dreamweaver will not even open unless we restart byond first.

See the thread for more details/complaints.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by clusterfack** [comment]
Update to 510
