### ISSUE TITLE
Bluespace tiles are eaten by the singulo

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9714]
wew

**Comment by ghost** [comment]
It's a feature

When the universe is ending, the only thing that can save you from the entire universe being condensed into supermatter, is an all-consuming hole in the universe

**Comment by clusterfack** [comment]
Sequel: Space Station 14

A station not only powered by a bunch of singularity engines, a spaceship with a bunch of singularities in the front of it plowing its way through the destroyed universe in the aftermath of a supermatter cascade.

**Comment by FudgePucker** [comment]
New game mode, space travel.
The station has to get to centcom, you have to use engines.

All the engines are powered by bullshit.

A gravity sail, there are linked together particles that get sucked into the singularity, but are attached to the station by some bolts, pulling the station. A wrench could cause the station to come to a stand still.

Best round sense meatywhores

**Comment by gbasood** [comment]
Okay I get that it's a feature but
One of the ways the cascade happens is if the crystal is eaten by a singulo
So the bluespace tile that gets spawned AT THE CRYSTAL is immediately eaten and no bluespace tiles exist in the world.

**SO HOW CAN THERE BE A CASCADE WITHOUT SUPERMATTER**

**Comment by ihadtoregisterforthis** [comment]
Then make it so if there aren't any bluespace tiles left it stops the universe ending, easy featurization.

**Comment by clusterfack** [comment]
Thats a trouble

(Super singularities should spit out supermatter tiles for funsies)
