### ISSUE TITLE
Items placed on wall on one side can be seen on the other

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9721]
(WEB REPORT BY: realestestate REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> I can see items that are on the other side of the wall, where that wasn't the case before the update. for instance, I can see the captain's safe and fireplace from outside his quarters. I can't interact with them, so it just looks stupid.
> 
> What you expected to happen
> items on the other side of the wall that are not in view to not appear
> 
> What actually happened
> as mentioned above
> 
> Steps to reproduce if possible
> look at the walls where the captain's office is from the hallway, you can see the fireplace and safe from outside

**Comment by PJB3005** [comment]
SOOOOOOD

**Comment by Intigracy** [comment]
Wasn't this said it would happen way before we actually switched to 510?

**Comment by clusterfack** [comment]
This is a feature of 510 it needs a new flag TILE_BOUND or something

**Comment by gbasood** [comment]
@PJB3005 but remember we can have EUROPA LIGHTING with 510 if we wanted to try it

Also I didn't change anything, by all accounts this shouldn't be happening and I haven't actually seen it happen yet myself
