### ISSUE TITLE
Blowing the nuke should trigger a FUCKING MAP VOTE JESUS CHRIST

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9723]
FUCK YOUR FUCKING GODDAMN WEIGHTED MAP VOTES AND YOUR TAXI STATION JESUS CHRIST

Implement please. Thanks.

**Comment by gbasood** [comment]
I thought it did?

**Comment by mrpain666** [comment]
Nope

**Comment by PJB3005** [comment]
Nuke code is terrible and handles restarting the server all on its own.

**Comment by gbasood** [comment]
Nuke code should:
- Properly bring up the scoreboard using current gamemode's code
- Trigger map vote
- Handle any other round end things that gamemode code/shuttle docking usually handle

**Comment by MercuryDoll** [comment]
Why not make the round-end code standalone and let gamemode codes call roundend() or whatever.

**Comment by PJB3005** [comment]
@MercuryDoll if it worked and didn't crash the server it's good.
- oldcoders, SVN era

**Comment by clusterfack** [comment]
Lol it literally has custom code to restart the server this is worse than I thought

![](http://puu.sh/pbWWv/9eda808af0.png)

**Comment by ComicIronic** [comment]
This twisted game needs to be reset

**Comment by SonixApache** [comment]
Isn't this fixed now?

**Comment by mrpain666** [comment]
Watch the next nuke ops round you see where it goes off and report back with your findings.

**Comment by MadmanMartian** [comment]
closed by #19869
