### ISSUE TITLE
Speech Bubble is bugged

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9724]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
It appears only when your character moves or turns, if you are static it doesn't appear

**Comment by Shadowmech88** [comment]
I assume this is supposed to be "speech bubble."

**Comment by clusterfack** [comment]
Maybe he's the flash

**Comment by gbasood** [comment]
Possible something happened with 510 that made speech bubbles not work the same but they seem fine to me?

**Comment by Probe1** [comment]
happened to me too.  said something, bubble stayed up for a long ass time.

**Comment by clusterfack** [comment]
See #9737
