### ISSUE TITLE
Retards lack the dexterity to smack people with the bible

### ISSUE THREAD

**Issue by BestName** [d3athrow/vgstation13#9733]
#### Description of issue

Retards can't smack people with the bible
#### Difference between expected and actual behavior

I expected to be able to smack people with the bible regardless of my less than ideal mental health but I was told that "You don't have the dexterity to do this!"
#### Steps to reproduce
1. Acquire brain damage
2. Acquire the bible
3. Try to hit yourself or someone else with it
4. You don't have the dexterity to do this!
#### Server revision

7d9088b630c0e7708f6b0e7726f954b58a38df7e
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Iamgoofball** [comment]
*tips fedora

**Comment by Killette2** [comment]
I dunno, sure mauling someone with an object in general is easy, but aiming for the top of their head may be a bit tricky when you're a retard. You don't see an all retard baseball league do you? They wouldn't have the dexterity to pull it off!

**Comment by gobblecoque** [comment]
its not so much as "easy" as it allows for fun gimmicks, like retard priest trying to make people retards with him. if they don't get brain damage, they're cursed. or ect.

**Comment by xpcybic** [comment]
This is my favorite issue name
