### ISSUE TITLE
Vampire Hud

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9734]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
Not sure if this is bug or not but Vampire Hud does not display how much blood I've consumed

**Comment by Intigracy** [comment]
I tried:

Taking his vampire then giving it back
Having him relog
Removing him from his mob then putting it back

Nothing worked. The other vampire's HUD was fine.
