### ISSUE TITLE
Progress bars are extremely inconsistent after 510 switch

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9737]
#### Description of issue

Progress bars, the thing that shows up on top of yo head.  Sometimes they don't show up at all.  Sometimes they only show 10% progress then freeze and disappear when it completes.  
#### Difference between expected and actual behavior

There's multiple progress states they switch through that aren't being used.  If it works at all.
#### Steps to reproduce

Grab an RPD and make some pipes and wrench them in.  Plenty of testing data.
#### Length of time in which bug has been known to occur

Since 510.

**Comment by Shadowmech88** [comment]
> Progress bars are extremely consistent

This sounds like a good thing.

**Comment by Exxion** [comment]
Yeah, noticed this while testing mining stuff
But you may want to fix that title

**Comment by gbasood** [comment]
Not sure what this has to do with 510 but hey

**Comment by clusterfack** [comment]
Entirely the fault of byond, a most recent bug introduced into their beta build in their last bugfixing attempt to sync images to frames properly or something.

Should be fixed in the next byond update 1341 when it comes out on monday.

**Comment by clusterfack** [comment]
Fixed by 510.1341
http://www.byond.com/docs/notes/510.html
