### ISSUE TITLE
Evolving as a xeno causes you to constantly be blacked out.

### ISSUE THREAD

**Issue by carshalash** [d3athrow/vgstation13#9738]
http://i.imgur.com/I3GEZ0K.png

This kind of just kept happening, this  is kind of unplayable.

**Comment by CptWad** [comment]
Yes its real can confirm

**Comment by Probe1** [comment]
![2016-04-29_00-47-35](https://cloud.githubusercontent.com/assets/8550416/14908337/f9e1e2ee-0da3-11e6-9991-c49192a03b41.gif)

**Comment by carshalash** [comment]
I need to learn how to capture gifs some day.

**Comment by Probe1** [comment]
https://getsharex.com/  go to record gif

**Comment by CptWad** [comment]
@DeityLink
@gbasood

**Comment by Intigracy** [comment]
Happened to me too when I exploded myself with a bomb and became a head.

**Comment by Shadowmech88** [comment]
Possibly an issue with moving a player's ghost from one body to another, then?

**Comment by Probe1** [comment]
its def a 510 overlay issue

**Comment by DeityLink** [comment]
Some player was having this issue a few days ago when he mutated from larva to sentinel. First time I see overlays smoothly go away like that. I am not sure what causes it.

**Comment by gbasood** [comment]
It's a 510 fullscreen overlay thing yeah
Not sure why but hey
When you say evolved, do you mean from larvae to anything? Because that's a thing I can probably easily fix

@intigracy That's because dead things are blind duh
@DeityLink the fullscreen overlays code I added causes smoothing for things like that

**Comment by CptWad** [comment]
its just becoming a xeno at all, strangely larva were uneffected
