### ISSUE TITLE
Flashbangs don't stun mobs without a client (not UI issue)

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9739]
???
To reproduce: flashbang catatonic man, watch in awe as it has no effect

**Comment by Shadowmech88** [comment]
Not a bug. I've looked at flashbang code before and it's intended to function like this.

Why would you want to flashbang clientless mobs anyway?

**Comment by 9600bauds** [comment]
Why wouldn't you be able to?

**Comment by 9600bauds** [comment]
Bit jarring when you flashbang a ling with a monkeyman and only one goes down

**Comment by clusterfack** [comment]
Tactical logout

**Comment by Exxion** [comment]
It's quite dumb regardless of whether or not it's intentional

**Comment by clusterfack** [comment]
I doubt we could fix you not getting flashed since you don't have a hud when you log out, but not being stunned? That's pretty silly.

**Comment by Exxion** [comment]
Not like the flash is really relevant anyway
The stun is the important part
