### ISSUE TITLE
Thunderdome hilarity on taxi

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9743]
>spawn myself on the thunderdome before round start while everyone else is in the lobby
>start throwing cursed dice to get a feel for probabilities
>get catbeasted by the dice
>round starts
>somehow FUCKING TELEPORTED to the station
>lynched by Nevil instantly
>he takes my dice and also catbeasts himself
This bug was so fucking funny I almost didnt want to report it. HONK.

**Comment by mrpain666** [comment]
Oh god muh meme arrows didnt post!

**Comment by kol1th** [comment]
MEME ARROWS 

I was wondering what those catbeast heads named "ADMIN" were. honk

**Comment by mrpain666** [comment]
@kol1th yeah I gibbed myself because I didnt want him getting my admin ID at round start. Lel.

**Comment by gbasood** [comment]
> doing anything before round start

Did you fucking ready up before round start and then make a mob for yourself or something stupid
Because in that case, stop being a badmin, not a bug

**Comment by 9600bauds** [comment]
i fixd ur meme arrows :)

**Comment by Intigracy** [comment]
Quit doing things before the round starts dummy.

When the round starts it teleports human mobs with minds to the station, that's how moving people from the lobby works.

**Comment by mrpain666** [comment]
Well if that's intentional then I'll have to be more careful
