### ISSUE TITLE
Vine fruit sprites don't always work

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9744]
Intended effect - harvestable vines have the red fruit icon

Actual effect - only the vines in the original 3x3 area of the vine growth bear these sprites, the rest do not yet are still harvestable

I had a screenshot, but byond didn't register the screenshot when I hit F2 at the time so you just gotta trust me on this.

**Comment by Killette2** [comment]
![vinebug](https://cloud.githubusercontent.com/assets/5169310/15202649/4aee68da-17ca-11e6-9625-5228d8c42db6.png)

Reconfirming with an image attached

**Comment by Shadowmech88** [comment]
Closing in favor of #11449 since it has more information.
