### ISSUE TITLE
Ghosts that have their sprites hidden shouldn't have right-click menus or be mouse-overable but they are anyway

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9745]
Not DIRECTLY a BYOND bug: test environment shows that things with alpha = 0 normally have no mouse interaction, but for some reason ghosts do in SS13

Maybe has something to do with how ghost visibility is handled but Im not sure how that is so ¯_(ツ)_/¯

**Comment by gbasood** [comment]
By the way this was my test environment:

``` DM
/*
    These are simple defaults for your project.
 */

world
    fps = 25        // 25 frames per second
    icon_size = 32  // 32x32 icon size by default

    view = 6        // show up to 6 tiles outward from center (13x13 view)


// Make objects move 8 pixels per tick when walking

mob
    step_size = 8
    icon = 'test.dmi'
    verb
        toggle_alpha()
            src.alpha = src.alpha == 255 ? 0 : 255
        still_visible()
            usr << "Yep!"

obj
    step_size = 8
    icon = 'test.dmi'
    icon_state = "obj"
    verb
        bwoink()
            set src in world
            usr << "bwoink!"
```

If you use toggle_alpha you'll no longer have still_visible in right-click menus, like how ghosts should be working I think maybe

**Comment by gbasood** [comment]
So basically someone needs to check **all the vars that ghosts have** to see if they can reproduce it elsewhere with any of  them

**Comment by Intigracy** [comment]
We change ghost invisibility layer, not alpha.

**Comment by gbasood** [comment]
@Intigracy No, their alpha gets changed too

**Comment by clusterfack** [comment]
Yeah I don't think this is a problem in retrospect, it's a result of SEE_SELF sight flag which makes it so you're always able to "see" yourself.
