### ISSUE TITLE
Jukes can't have their panel closed, and can't be wrenched up/down

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9747]
Possibly specific to MoMMIs

**Comment by ComicIronic** [comment]
Check the jukebox attack code.
If it doesn't have some kind of 
`. = ..()
if(.)
    return .`
block, it's implemented wrong.

**Comment by Shadowmech88** [comment]
Tested locally. As both a MoMMI and a carbon, I was able to both wrench/unwrench the jukebox as well as open and close its panel.
