### ISSUE TITLE
Global narrate font styles can mess with secrets panel's admin log

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9750]
`<span style='font-family: Wingdings'>honk</span>`
Changed the logs to wingdings until I did a new log with Verdana.
May have been double quotes may have been single quotes I dont know anymore

**Comment by Shadowmech88** [comment]
Tested locally, after making that same wingdings announcement, the following entries in the admin log were normal text. Tested with both single quotes and double quotes.
