### ISSUE TITLE
Paper formatting is totally busted

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9752]
At the very least, you can't post images, but I think all of the formatting might be broken.

Tested on both paper and nanopaper with multiple image formats.

**Comment by Shadowmech88** [comment]
Does this include tags like [bold] [italic] et cetera?

**Comment by 9600bauds** [comment]
I totally cannot figure out why this is happening.
Was this caused by 510?

**Comment by Shadowmech88** [comment]
It's been broken since the move to 510 I believe, yes.

**Comment by 9600bauds** [comment]
How it looked when writing `"[img]http://i.4cdn.org/vg/1466316185049.jpg[/img]"` on a paper before 510:
![dllhost_2016-06-19_03-35-03](https://cloud.githubusercontent.com/assets/6526157/16175741/e03ad9c4-35ce-11e6-8047-7bf388c7e6cc.png)

How it is now:
![dllhost_2016-06-19_03-34-56](https://cloud.githubusercontent.com/assets/6526157/16175742/e339d5c6-35ce-11e6-8d66-f3deaf05d107.png)

There's regex everywhere so fuck that
Ideas?
