### ISSUE TITLE
Expand for blob does not work

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9754]
(WEB REPORT BY: lorkhatosh REMOTE: 172.93.109.202:7777)
as a blob I can not go to non-blob tiles and I can't attack/expand blob

**Comment by gbasood** [comment]
Note this is a round BEFORE deity's blob so don't blame him

**Comment by Shadowmech88** [comment]
I _assume_ Deity tested his PR, so if it worked for him the issue might be fixed, whatever it was.

**Comment by gbasood** [comment]
It works. Ctrl+click guys
