### ISSUE TITLE
Blobchat is html_encoding chars for no raisin

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9758]
> Blob Telepathy, Blob Overmind (912) (Follow) says, "I&#39;m having some action down here so watch out"

**Comment by PJB3005** [comment]
> De-encode

Not goonchat related either, it's oldcoders being retarded with sanity procs.

**Comment by gbasood** [comment]
only showed up because of goonchat move
I know it's not goonchat's fault but still, indirectly caused by

**Comment by Shadowmech88** [comment]
I've noticed this happening with whispering, as well.

**Comment by ComicIronic** [comment]
Fixed y/n?

**Comment by gbasood** [comment]
y
