### ISSUE TITLE
Eguns are $50 each, which is too cheap

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9759]
Departments start with 5k.
Players start with ~500 I believe.
That means a player at roundstart has enough money in his PERSONAL ACCOUNT to open up an armory of his own.
Guns should not be that cheap.

Also, pizzas are more expensive than guns.

With the planned changes coming in the Wages PR, department accounts get 500 per paycheck, so you could do it all over again every 20 minutes

**Comment by 9600bauds** [comment]
> Players start with ~500

How do you fuck that up

**Comment by gbasood** [comment]
@9600bauds By not looking at the values
Doesn't matter, a crate of guns is less than a crate of pizzas, that's just terrible

**Comment by ihadtoregisterforthis** [comment]
# <sub><sup>This is an</sup></sub> AMERICAN <sub><sup>station

**Comment by Probe1** [comment]
Wages first, cargo price overhaul second?

All of cargo pricing is fucked and honestly the points system needs to come back anyway.  And shaft miners will have lodesofmone so cargo won't care.  Its basically a lose-lose to change things up right now when there's many things that effect it and will neuter any balance changes.

**Comment by gbasood** [comment]
@Probe1 Yep, that's the plan
I just want to document how **ABSOLUTELY STUPID** cargo prices are before I get to them

**Comment by 9600bauds** [comment]
Honestly, with how cheap fucking everything is, eguns being 50$ is one of the most reasonable prices

**Comment by gbasood** [comment]
@9600bauds in terms of prices relative to eachother? Sure. In terms of actual supply/demand? Nooooooope

**Comment by NigglyWiggly** [comment]
@9600bauds 

> Honestly, with how cheap fucking everything is, eguns being 50$ is one of the most reasonable prices

We have things in vending machines that cost more than that.

**Comment by 9600bauds** [comment]
I was talking about Cargo prices, but that too

**Comment by ghost** [comment]
Shelve it until econ is unfucked then balance it against the needs of nuke/blob/wiz/cult/rev. I'd rather we have too many guns too easily.

**Comment by gbasood** [comment]
@SarahJohnson489 I think that if supply guns were actually a problem for most of those modes (besides blob and wiz) then we'd see those antags hitting supply over other targets but yeah, this is still waiting till after at least one or two econ changes
