### ISSUE TITLE
This is what PJB got done for antag datums before he decided he was done

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9762]
https://github.com/PJB3005/vgstation13/tree/antag-datums-are-happening

It isn't nearly ready to be a PR, but he's done with SS13 code he says
Who wants to take it up?

**Comment by ihadtoregisterforthis** [comment]
F

**Comment by 9600bauds** [comment]
F

**Comment by PJB3005** [comment]
I was around here: https://github.com/Baystation12/Baystation12/pull/8360/files#diff-0e52030681029993755f95a9e858f335R3 in the diff for the original PR.

**Comment by gbasood** [comment]
Here's dudes I want to know specifically if they want to pick this up:
@intigracy
@unid15
@DeityLink

**Comment by DeityLink** [comment]
ZELKJFGEZ%PKINJGZEJPOFGE Z µKOLFG ZEPKµ GZREJP O GZE

**Comment by DeityLink** [comment]
> if they want to pick this up

I'll let intigracy and unid15 take a go at it first. Modifying systems is a special kind of fun that I only take in moderation and possibly accompanied by fun features. And as much as antag datums would bring some flexibility in a round's developpmen, I'm not in a hurry to code them over say something like...a talking sword?

**Comment by unid15** [comment]
Maybe in a month or two, when I get more free time and nobody else picks it up

**Comment by Intigracy** [comment]
What was the hoped for end result?

I know you want refactored antag datums, but how do you want them to behave once refactored?

**Comment by PJB3005** [comment]
@Intigracy not refactored I wanted antagonist datums at all.

**Comment by gbasood** [comment]
@Intigracy This is our end goal I think, and riri agrees with me:
- Instead of gamemodes needing to be set up at game start, we'd have gamemode 'datums' that just held groups of antags in them, did simple logic checks, and held group data (like blood count for cultist)
- Antags themselves would have datums that had information about their antag status (like blood for vamps, absorbs for lings, and objectives for traitors)
- A refactored ticker would be able to handle a list of 'antag group' datums that it would periodically do things like completion checks on, and we'd be able to add them to the ticker mid-round, so that a group of cultists could summon Narsie properly if they were added mid-round.
- @ririchiyo is saying something about 'antag events' nto sure what he means yet

**Comment by PJB3005** [comment]
@gbasood your blood count for cult thing is already the wrong approach.

Ideally we have no gamemodes at all.

**Comment by gbasood** [comment]
@PJB3005 We need to store blood spilled somewhere, and group antags have shared objectives, so they're going to need a place to store things like that.

Or if it's a better example, imagine a group of traitors that shared an objective to steal X sheets of metal (or things like heist)

**Comment by PJB3005** [comment]
@gbasood you put the blood counter on the antagonist datum itself.

The antag datum is a prototype to define how antags should behave, it doesn't make a new one for each antag that gets added.

**Comment by gbasood** [comment]
@PJB3005 Here's where I don't understand you though, let's forget about cultist as an example
We have a group of antags that needs to keep track of their progress towards an objective and perform an action based on the completion of that objective.
Rather than do a logic check every time, we could store completion progress in a var and modify it as necessary.
How do we store that information except in somewhere that knows about all the antags of its type?

**Comment by Intigracy** [comment]
[10:35:25] <Intigracy> antagType antagMode and antagEvents
[10:35:38] <Intigracy> antagType is just attached to your mind and tells what kinds of antag(s) you are
[10:35:51] <Intigracy> antagMode is in the ticker and holds the relevant vars for the related antag modes
[10:36:06] <Intigracy> blood, list of antags, etc
[10:36:42] <Intigracy> and antagevents is I assume just how it would handle making new antags
[10:36:53] <Intigracy> like if there's not an antagmode datum for cultists and you make a cultist
[10:36:56] <Intigracy> it'd make a new one
[antagevents would also hold all of the game ending events in like malf or nuke]

[10:40:07] <Intigracy> gamemodes wouldn't "exist" like they do now, it'd just be conditions for roundstart
[10:40:14] <Intigracy> so SPAWN THESE ANTAGS AND THESE DATUMS

**Comment by DamianX** [comment]
we have role datums now
