### ISSUE TITLE
xeno raider chef recipe

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9763]
(WEB REPORT BY: **pvak** REMOTE: `172.93.109.202:7777`)
#### General description of the issue

the recipe in the wiki gives burned mess
#### What you expected to happen

xeno raiders
#### What actually happened

burned mess
#### Steps to reproduce if possible

add 2 salt 1 potato 1 xeno meat

**Comment by Probe1** [comment]
Can reproduce.
