### ISSUE TITLE
Bebop Cola!

### ISSUE THREAD

**Issue by Blithering** [d3athrow/vgstation13#9769]
Sprites for a vending machine, also an unfortunate captain squashed by the machine. Possibly for use as a curio in a vault.
![reference](https://cloud.githubusercontent.com/assets/15067109/14926716/5c35d3be-0e45-11e6-838b-ad06d96c695f.png)
Because Sealab 2021 was an eerie prophecy of ss13. 
Download link for icons: http://s000.tinyupload.com/index.php?file_id=15217679443346891974

**Comment by Imagebard** [comment]
That vending machine is kinda shitty

**Comment by ihadtoregisterforthis** [comment]
![scorpions when](https://cloud.githubusercontent.com/assets/13305885/14929068/0481415c-0e32-11e6-81fa-17473eedc5e5.png)

**Comment by FudgePucker** [comment]
You know what, how would bodies decay in space?

Its a space station so its pretty clean so there are no fly's to lay maggots on dead flesh

I don't think bacteria can survive in a vacuum, so a dead corpse would look just as it did when they died, it wouldn't be bones

**Comment by Shadowmech88** [comment]
Why close this?

**Comment by Blithering** [comment]
It was mostly just a meme idea, and I'm pretty sure the sprite download link  has expired.
