### ISSUE TITLE
Add a menu to allow admins to modify a human's appearance easily

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9770]
So that admins can bus their spawned mobs harder

**Comment by NigglyWiggly** [comment]
We have an edit appearance button y'know

**Comment by gbasood** [comment]
Does it work? I've never seen it used

**Comment by PJB3005** [comment]
Yes, it does.

**Comment by gbasood** [comment]
buttons and shit Sood never sees.txt
