### ISSUE TITLE
Rirch has basically been doing nothing

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#9771]
I've told you multiple times that this Ririch person is merely fucking around and adding controversial/DNM tags to PRs he doesn't like, and now that he's becoming active again(since the last time he was told off by Pomf123) he quickly reverted to the same.

**Comment by 9600bauds** [comment]
who the fuck is rirch

**Comment by gbasood** [comment]
@Imagebard We've had a huge argument about this already on the IRC
If he keeps tagging things DNM without saying why __on github__ there's going to be problems but otherwise I think we worked it out maybe

**Comment by FudgePucker** [comment]
Clearly he should have contributor status removed until he is more active in programing bug fixing or anything besides shitposting and abusing tags.

**Comment by Exxion** [comment]
He's stopped doing it with [Controversial] at least
He used to be really bad about that

**Comment by gbasood** [comment]
@FudgePucker He's doing code review which is just as important as actually coding.
Right now the primary people doing review are Clusterfack and PJB, and if riri stays active doing it that's a huge help

**Comment by Intigracy** [comment]
can we at least keep the issue tracker related to code

**Comment by Exxion** [comment]
As much as I don't like Riri, yes, this topic would be more suited to the forum

**Comment by Intigracy** [comment]
or IRC
I've seen nobody that has been banned from IRC (since the time I've been here) for expressing an opinion

**Comment by gbasood** [comment]
Agreed
