### ISSUE TITLE
Blindfolds prevent you from hearing visible_messages, even if they specifically have messages for blind people

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9772]
If you have the BLIND disability and someone welds a vent near you, you hear the sound and get the message "You hear welding."
If you have a blindfold on and someone welds a vent near you, you get just the sound and no message.

I think people with blindfolds just don't count for "in viewers" at all.

**Comment by Shadowmech88** [comment]
> even if they specifically have messages for deaf people

Shouldn't this be "blind people"?

**Comment by 9600bauds** [comment]
Yes

**Comment by Shadowmech88** [comment]
This bug still seems to occur.
