### ISSUE TITLE
Advance system cams is not showing up

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9779]
(WEB REPORT BY: recounted REMOTE: 172.93.109.202:7777)

> Revision (Should above if you're viewing this from i bengame!)
> 
> General description of the issue
> I can't see the map at all but I can click on the space map of it and it was show me the cams
> 
> What you expected to happen
> to see the map with the camera around it
> 
> What actually happened nothing is popping up
> 
> Steps to reproduce if possible

**Comment by 9600bauds** [comment]
there's like three issues open on this one but we deserve a reminder

**Comment by Exxion** [comment]
We also have no idea at all whatsoever how to fix it
I tried once, and got far enough to determine that it was a clientside caching issue before it fixed itself for me so I could no longer test fixes

**Comment by gbasood** [comment]
We already know the bug that causes this
But no one has tried to fix it yet

**Comment by gbasood** [comment]
@Exxion It's not a clientside caching issue, it's related DIRECTLY to when cameras are destroyed or hacked

**Comment by Exxion** [comment]
It 100% is a caching issue if this report is about the bug I think it is
There are multiple known bugs with the advanced camera console though

**Comment by gbasood** [comment]
@Exxion When a camera is hacked or destroyed it causes cameras to stop showing up properly as icons on the map.

The map itself can be fine but  the icons will never show if cameras are destroyed/hacked at any point during hte round

**Comment by Exxion** [comment]
Yes, and the OP says he can't see the map
Which is the caching bug

**Comment by gbasood** [comment]
Oh, whoops

**Comment by Shadowmech88** [comment]
Given the age of this report and the fact that it seems to primarily be a BYOND bug with little hope of being fixed, I think this can be closed.
