### ISSUE TITLE
You lack enough /obj/item/stack/sheet/glass/plasmarglass to finish the solar.

### ISSUE THREAD

**Issue by xpcybic** [d3athrow/vgstation13#9786]
Occurred while trying to place a reinforced plasmaglass solar panel with only one sheet in my hand, as a MoMMI. Not sure if it happens with other types of glass.

**Comment by gbasood** [comment]
Not sure what intended behavior, etc is without looking at code

**Comment by clusterfack** [comment]
It's outputting glass.type in the failure message instead of glass.name

**Comment by xpcybic** [comment]
Oh nice an easy fix then

**Comment by clusterfack** [comment]
Indeed it is

**Comment by Probe1** [comment]
you are such lazy motherfuckers

**Comment by PJB3005** [comment]
Didn't Dylan last touch this?
