### ISSUE TITLE
Add a constructable clown shuttle console and hide it somewhere and..

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9790]
(add the clown planet back)

**Comment by Probe1** [comment]
addendum:
https://www.youtube.com/watch?v=SUamHEvVQy0

**Comment by Shadowmech88** [comment]
Don't we currently have a "clown planet" in the form of the bananium and clown vault? The clown inside even says "Welcome to Clown Planet!"

**Comment by Probe1** [comment]
nah the clown planets a thing.

**Comment by Blithering** [comment]
Could the clown spacesuit be added to the clown vault maybe?

**Comment by Probe1** [comment]
I guess but that's not related.  That'd be a good place to put the console though.

**Comment by Shadowmech88** [comment]
@Blithering 
Just make a separate feature request for that.
