### ISSUE TITLE
Mobs buckled to roller beds cannot be hit by projectiles

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9793]
This is an issue specific to  `obj/structure/bed/roller` .  It does not effect `obj/structure/bed` or `obj/structure/bed/chair` .  

When a mob is buckled to a roller bed and shot with a projectile, it hits the roller bed instead of the mob.  I tested this against laser/admin and shotgun/pump/combat .  

I suspect, because roller beds make a dense tile that you cannot walk over when a mob is buckled, it blocks the projectile entirely.  This behavior is unique to roller beds.  You can walk over a bed with someone in it.

**Comment by nervere** [comment]
There are exceptions in the code for this now. Testing done by @Inorien - thanks!
