### ISSUE TITLE
Restrict air alarm alerts to z levels

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9794]
#### Description of issue

If an air alarm in "SECRET ROOM" in the ass end of z6 triggers, the station is notified.  This interferes with my ability to power/stabilize secret areas on the map.
#### Difference between expected and actual behavior

Not to have god powered air alarm detection

**Comment by PJB3005** [comment]
I already made subtypes for no alarm APCs.

Just add ones for air alarms.

**Comment by Probe1** [comment]
While that does work, its kinda a bad solution to what needs to be a variable in air alarm monitoring code.
