### ISSUE TITLE
System request: Spawner subtype that checks all spawners of type and ends if one has succeeded in spawning an object

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9795]
I want to place an overpowered item on an away mission.  If I put it in one place then people will just game it and rush right to that place.  Instead, I want something like https://github.com/d3athrow/vgstation13/blob/Bleeding-Edge/code/modules/maps/spawners/set_spawners.dm that also checks to see if a spawner has succeeded in spawning an object in the list and returns if the object has been spawned.

That way I can have it potentially be in multiple places which would alleviate (but not eliminate) the memorization factor.

It would also help pave the way towards more procedural away missions.

**Comment by ghost** [comment]
Isn't there something like that in the 'cult asteroid temple' vault, with the mace?

1 of them is the mace, the rest are mimics, that sorta thing.

**Comment by Probe1** [comment]
```

/obj/effect/landmark/catechizer_spawn //Multiple of these are put in a single area. One of these landmark will contain a true catachizer, others only mimics
    name = "catechizer spawn"

/obj/effect/landmark/catechizer_spawn/New()
    spawn()
        if(!isturf(loc)) return

        var/list/all_spawns = list()
        for(var/obj/effect/landmark/catechizer_spawn/S in get_area(src))
            all_spawns.Add(S)

        var/obj/effect/true_spawn = pick(all_spawns)
        all_spawns.Remove(true_spawn)

        var/obj/item/weapon/melee/morningstar/catechizer/original = new(get_turf(true_spawn))

        for(var/obj/effect/S in all_spawns)
            new /mob/living/simple_animal/hostile/mimic/crate/item(get_turf(S), original) //Make copies
            qdel(S)

        qdel(src)

```

**Comment by Exxion** [comment]
> Searching for all existing spawns in an area

I don't like that method one bit
I think there's a better way to do it with a global var

**Comment by gbasood** [comment]
just add all of `spawn once` spawners them to a global `spawnonce` sort of list
then pick one of the ones you're actually using, say a `spawnonce\clownmask` spawner
and remove the rest from the list on success
