### ISSUE TITLE
Spam When Trying to Load a Character Save that Isn't There

### ISSUE THREAD

**Issue by ihadtoregisterforthis** [d3athrow/vgstation13#9796]
![1](https://cloud.githubusercontent.com/assets/13305885/14938588/006108a0-0eff-11e6-87b2-c18ed5164399.png)
![3](https://cloud.githubusercontent.com/assets/13305885/14938590/0241945a-0eff-11e6-9b90-c0305f0ff4ac.png)
![4](https://cloud.githubusercontent.com/assets/13305885/14938591/03e43fce-0eff-11e6-9743-563cf3fee896.png)

**Comment by Probe1** [comment]
@intigracy

**Comment by PJB3005** [comment]
100

%

**Comment by kol1th** [comment]
:100:

**Comment by Intigracy** [comment]
Why don't you have a character slot?

**Comment by PJB3005** [comment]
Uh, that's pretty bloody obvious. 

Clear a local sqlite database, open char setup, load slot, select a slot.

**Comment by Intigracy** [comment]
~~Oh right, when you're trying to load a blank slot to save a new character.~~

**Comment by Intigracy** [comment]
Opening character setup and pressing load slot doesn't call try_load_sqlite it calls load_save_sqlite, meaning 1 try.

The only place the spam would happen is client/new, meaning he loaded preferences successfully but his save slot didn't exist.

Clearing your database would mean clearing your preferences as well, so it should be failing to load prefs and just randomizing him a new character slot (which is saved).

**Comment by ihadtoregisterforthis** [comment]
It was a clean local server, lobby time, without a saved slot and being unable to save a slot as the character setup wasn't ready.

**Comment by Intigracy** [comment]
Clearly it wasn't a clean local server.

I just downloaded a zip of the repo and compiled/started it up, it correctly generated/saved me a new character without waiting on the errors.

The only other way I could see this happening is if you're connecting to a server for the very first time and quit after it creates you preferences, then rejoin and suddenly it loads the prefs and has no save slot to load.

**Comment by Intigracy** [comment]
...did you copy over the example config to config?

**Comment by ihadtoregisterforthis** [comment]
...yes
