### ISSUE TITLE
You can SEE SHIT through line of sight

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9798]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> b4e75d134db3dfbb18c5a020a4ab84e452a91281 
> General description of the issue
> You can see shit you shouldn't be able to,
> http://puu.sh/oBCKq/71fcf625b6.png
> http://puu.sh/oBCLp/ac363fd435.png
> http://puu.sh/oBCMH/f272c4973a.png
> http://puu.sh/oBCTy/370f4c3a7a.png
> http://puu.sh/oBCV8/2547c16583.png
> 
> What you expected to happen
> to not see ghost fire places
> 
> What actually happened
> I CAN SEE THEM through walls its crazy
> 
> Steps to reproduce if possible
> just talk a walk around the station

**Comment by FudgePucker** [comment]
I mean the fireplace is pretty fucked up, but some of those other examples are somewhat iffy, I can see something mounted on the wall with out seeing the wall, it is away from the wall. Problem with the top down viewing system.

**Comment by TheFriggenSawbones** [comment]
yeah its just weird the wall tile is blacked out and i'm able to see whats on top, i assume this is all a 510 thing right

**Comment by Exxion** [comment]
It is a 510 thing
#9721

**Comment by Imagebard** [comment]
This is because items are placed on a tile next to a wall and then put at a X/Y offset so it seems like they're on another tile.
It also doesn't really matter.

**Comment by Exxion** [comment]
Visually acting like things are on the tile they appear to be rather than the tile they are is new to 510
And like hell it doesn't matter
It's ugly and confusing and there are a handful of fringe cases in which it would (mildly) affect gameplay

**Comment by clusterfack** [comment]
Add the TILE_BOUND appearance flag to all of these objects to preserve previous behavior

**Comment by Probe1** [comment]
that dont seem too easy
that seem like a fucking lot of testing.

**Comment by Exxion** [comment]
Easy for each thing
Just not easy in total

**Comment by clusterfack** [comment]
Testing? Testing what

**Comment by Probe1** [comment]
well I presume this is localized to objects that are offset to walls.

so I'd have to look around and write up a big list of every object thats on a way.  then test them all.  

Fixing these 3 that are reported is as many minutes of work but fixing the issue entirely is a slog.

**Comment by clusterfack** [comment]
It's not like we couldn't apply the flag to EVERYTHING you silly person

**Comment by clusterfack** [comment]
(Though it would be more annoying for multitile objects like cryo which benefit from this)

**Comment by Probe1** [comment]
So what's the usage?  Just cram TILE_BOUND in after the last var?

**Comment by Exxion** [comment]
```
/atom
  appearance_flags = [whatever it is now] | TILE_BOUND
```

That should be sufficient
If `appearance_flags` isn't already there, omit the `|`

**Comment by Probe1** [comment]
Where would I find /atom?

**Comment by Exxion** [comment]
atoms.dm, I think
