### ISSUE TITLE
HIGHLANDERS ABLE TO EAT HIGHLANDER HEADS FOR A FULL HEAL LIKE A HIVE LORD CORPSE WHEN?

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9801]
HIGHLANDERS ABLE TO EAT HIGHLANDER HEADS FOR A FULL HEAL LIKE A HIVE LORD CORPSE WHEN?
![firefox_2016-05-01_01-37-39](https://cloud.githubusercontent.com/assets/6526157/14940119/4e81c874-0f3d-11e6-843a-9252d495fc35.png)

Highlander is great except for the part where everyone bleeds out constantly

Maybe another way to do this would be upon decapitation so you can't store heads for healing

**Comment by Shadowmech88** [comment]
Mobs have a var that's a reference to the last mob that attacked them, right?
Just have any highlander that dies give a full heal to that mob.

**Comment by 9600bauds** [comment]
Caveat: Do it on beheading

**Comment by clusterfack** [comment]
Also have an energy animation going to the powered highlander

**Comment by Shadowmech88** [comment]
We can use the same kind of animations @DeityLink made for soulstoning, I think.

**Comment by 9600bauds** [comment]
@Deitylink I think you'd like this idea in general

**Comment by Imagebard** [comment]
Eating heads makes no sense, and a geneticist can just make tons of monkeymen heads to eat during highlander, therefore becoming invincible.

+1 for decapping people giving a heal, -1 to eating heads.

**Comment by MercuryDoll** [comment]
If anything, eating their hearts should make them stronger. But not heads, wtf.

**Comment by Imagebard** [comment]
>But not heads, wtf.

Do you know what a highlander is.

**Comment by clusterfack** [comment]
You can only kill a highlander through decapitation with a sword

**Comment by 9600bauds** [comment]
Or from internal bleeding from being slashed once

**Comment by DeityLink** [comment]
The particles I made are really easy to use, or to create variants of. just read runes.dm or soulstone.dm and search for "tracker".

Their source dm is trackers.dm
