### ISSUE TITLE
Vox Trader wallet icon state calls a non existent icon

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9803]
Uniiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiid

![image](https://cloud.githubusercontent.com/assets/8550416/14940299/06f75030-0f3f-11e6-8811-dc86349a9c1f.png)

**Comment by 9600bauds** [comment]
![atom_2016-05-01_02-56-09](https://cloud.githubusercontent.com/assets/6526157/14940317/454f3a24-0f48-11e6-83aa-2044fd1ed659.png)
s h i t c o d e
