### ISSUE TITLE
Sammis have binary 4noraisen

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9814]
#### Description of issue

They aren't slaved to the AI and have different laws.  Guess what happens when malf or subverted silicons use binary.  Let alone just normal use.

**Comment by Probe1** [comment]
Also just for keks they state their laws over binary only for some reason.

**Comment by gbasood** [comment]
Because they're mommi-derrived and they can only speak over binary unless emagged

**Comment by AutismSpider** [comment]
if SAMMIs are to retain the ability to talk on both common and binary, their laws needs to be extended similar to KEEPER"

**Comment by gbasood** [comment]
They won't keep binary. Period.

**Comment by MercuryDoll** [comment]
Agreed, since they are not AI bound malf-AIs won't be able to make them do their bidding anyway. So there's no reason they need binary, since any silicon other than MoMMIs have common anyway.

**Comment by Hoshi-chan** [comment]
Even if it's being removed, it's worth noting that when speaking on binary, they whisper what they're saying, as if they were on a headset.

**Comment by MercuryDoll** [comment]
That would be fine, borgs just need to not stand near SAMMIs when malfing then. Optionally give them a law to not concern themselves with the matter of other beings unless it is directly related to their designated task.

**Comment by gbasood** [comment]
@MercuryDoll "New task: tell me what they're saying on binary"

**Comment by MercuryDoll** [comment]
"Optionally" as in "Additionally to removing binary radio". Because if someone really manages to drag around an active SAMMI to spy on borgs that would be an achievement. pAIs are much more covert.
