### ISSUE TITLE
SAMMIs can re-enter their bodies when they're already occupied

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9821]
Using re-enter corpse

**Comment by gbasood** [comment]
You can accidentally gain ownership of someone else's body this way too, had it happen to me personally

**Comment by Hoshi-chan** [comment]
If they disconnect, they can also reconnect and re-inhabit their already-inhabited body, causing them to say everything twice.

**Comment by gbasood** [comment]
Doesn't even need to be disconnected really, if they're disembodied in any way they can do this
