### ISSUE TITLE
SAMMIs continue to exist when blown

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9827]
I was blown as a SAMMI (Is this a thing that you can do? I assume it was done with the robotics control console and not adminfuckery) only to become a floating hat, which could still pick things up, interact with other creatures (such as feeding them donuts), partially interact with my then-invisible HUD, control doors, and speak.

As for context, I'm not quite sure. I simply exploded, sending gibs everywhere, as well as my hat, but I remained there as a floating hat.

Oh yes, and while I could no longer be pulled, I could still be pushed around, despite being invisible.

**Comment by ghost** [comment]
This potentially could also be happening with MoMMIs, lost track of the number of them that complain they were hit by meteors, and are now stuck in semi-purgatory. Able to see, speak, but not interact with their menus

**Comment by gbasood** [comment]
@Skullyton sounds like de-brained MoMMIs less than blown mommis
I called gib() on a bunch of MoMMIs that may have caused this not sure
