### ISSUE TITLE
Admin EMP has no cancel button(s)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9830]
@skullyton aka dragonbro told me this

**Comment by ghost** [comment]
List of shit that needs a cancel button
- Drop EMP (throughout would be nice, but one at the start and end would be nice too)
- Drop Bomb (Throughout would be nice, but one at the start and end would be nice too)
- Local Narrate
- Global Narrate
- Announce
- Respawn Character
- Create a Bomberman Arena
- Execute Smissmas
