### ISSUE TITLE
Combat Nanobots

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9832]
(WEB REPORT BY: edwarus REMOTE: 172.93.109.202:7777)

> Revision 4102dab658654ce415602d85fcd06e05944e243f
> 
> General description of the issue
> nanobots dissappearing from body.
> 
> What you expected to happen
> After eating nanobot pills thought to stay supercharged for a while
> 
> What actually happened
> I ate the 9 unit pill of combat nanobots then ate some pizza after that i punched a window and then went to punch a wall but all the nanobots were out of my system
> 
> Steps to reproduce if possible
> make combat nanobots 9 units eat it eat pizza punch a window

**Comment by gbasood** [comment]
I thought >5 units was overdose = cyber horror?

**Comment by Exxion** [comment]
No, that was medical ones
And that's not even true for them anymore

**Comment by Shadowmech88** [comment]
From what I can tell from the code, this is intentional. Combat nanobots metabolize very slowly, but once the hulk effect is triggered at 5u-10u, after 45 seconds you de-hulk and the combat nanobots clear themselves out of your system.

**Comment by strawberrytan** [comment]
Yeah as said combat nanobots activate hulk as long as you take enough without ODing and after 45 seconds clears the nanobots
