### ISSUE TITLE
Escaping Metastation Xenobiology as borer is unintutive as fuck.

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#9834]
At least shift around the way the vents are connected so a borer can escape if the door to the hallway the main station to the xenobiology wing are linked. Both connect back to xenobio(???)

**Comment by Probe1** [comment]
That's the entire point.

You don't escape xenobiology.  It's contained because its purpose is to house and study dangerous creatures.

**Comment by Shadowmech88** [comment]
Why isn't Boxstation's Xenobiology's atmos system disconnected from the main station like Virology's is, then?

**Comment by Intigracy** [comment]
Boxstation's xenobiology atmos system **is** disconnected from the main station like virology's is.

You have to get out via the vent between the airlocks.

Unless waste is connected, idr.

**Comment by Probe1** [comment]
It isn't.

**Comment by Probe1** [comment]
I guess we should add little doggy doors for borers lol.

**Comment by Imagebard** [comment]
>You have to get out via the vent between the cycling airlocks.

Yeah basically what I'm asking for.

**Comment by Probe1** [comment]
Anyones free to but I'm sure as hell not doing it.  The entire point of that area is its containment.

**Comment by Intigracy** [comment]
Yeah but containment is breached if you're stupid enough to leave the door open.

**Comment by AutismSpider** [comment]
Not like slimes can vent out they freeze to death on venting form meme code

**Comment by Probe1** [comment]
Slimes are bad but what I'm worried about are things other than slimes like ayy and so on.
