### ISSUE TITLE
MoMMIs can't woop the siren helmet while wearing it

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9835]
They simply lack the HUD icon that humanoids have, so they have to take the helmet into their hands any time they want to WOOP WOOP. This is discriminatory and unfair and should be fixed.

Also, available to secborgs when? The entire security force, silicons included, should be able to strike fear into the hearts of lawbreakers with the sound of da police.

**Comment by Probe1** [comment]
Add a verb for it so I can bind it to a macro and spam the fuck outta it

But also for the MoMMIs.

**Comment by Kitfox88** [comment]
marinaborg's eyeplate flashes blue and red while WOOP WOOP when

**Comment by gbasood** [comment]
rip sammis
