### ISSUE TITLE
Freezing in place as robot

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9839]
(WEB REPORT BY: stealthmelon REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

I am very new to playing robots so I don't know if this is a common issue or not, but both times I've played, I have gotten stuck in place very shortly after starting the round. I have no idea as to what causes it, but the only way to fix it is to be pulled by someone else.

**Comment by gbasood** [comment]
Sounds like the skin selection thing
Do not hit cancel when selecting your module and your skin, it'll fuck you up\
Closing due to duplicate issue
