### ISSUE TITLE
Inspecting People Always Shows Them as a Grey

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9843]
![image](https://cloud.githubusercontent.com/assets/3991927/14953920/ad9b1f12-1033-11e6-846f-bd76ad8b704c.png)
This guy was a human.

This same image is shown for both humans and greys. Haven't tested it with any other races. Doesn't seem to happen with non-human mobs.

**Comment by PJB3005** [comment]
I think what's happening is that the \ref of the cached icons are being reused.

**Comment by PJB3005** [comment]
This is actually a dupe
