### ISSUE TITLE
Crawling on vents always produces a funny message

### ISSUE THREAD

**Issue by Imagebard** [d3athrow/vgstation13#9844]
Step 1, crawl into a vent as borer/xeno
Step 2, Read the funny messages(**THE VENT IS SEARING HOT!**) and imagine its nothing because it wasn't the last 100 times you jumped in a vent
Step 3, either nothing happens, or they dumped searing hot plasma on the scrubbers and you don't know because the vent messages are **ALWAYS** here, even on normal temperatures and pressures

**Comment by ihadtoregisterforthis** [comment]
Reduced from the code, messages about temperature
```
	if(0 to BODYTEMP_COLD_DAMAGE_LIMIT)
		You feel a painful freeze coming from the vent!
	if(BODYTEMP_COLD_DAMAGE_LIMIT to T0C)
		You feel an icy chill coming from the vent.
	if(T0C + 40 to BODYTEMP_HEAT_DAMAGE_LIMIT)
		You feel a hot wash coming from the vent.
	if(BODYTEMP_HEAT_DAMAGE_LIMIT to INFINITY)
		You feel a searing heat coming from the vent!
```
And about pressure

```
	if(0 to HAZARD_LOW_PRESSURE)
		You feel a rushing draw pulling you into the vent!
	if(HAZARD_LOW_PRESSURE to WARNING_LOW_PRESSURE)
		You feel a strong drag pulling you into the vent.
	if(WARNING_HIGH_PRESSURE to HAZARD_HIGH_PRESSURE)
		You feel a strong current pushing you away from the vent.
	if(HAZARD_HIGH_PRESSURE to INFINITY)
		You feel a roaring wind pushing you away from the vent!
```

**Comment by gbasood** [comment]
One thing that bugs me about these is warnings about pressure when you're something that doesn't get pressure damage in vents (borers)

**Comment by AutismSpider** [comment]
Borers don't take pressure damage same with xenos but they get pressure damage warning any way

**Comment by xpcybic** [comment]
To my recent recollection, nearly every time I've tried ventcrawling as diona nymph I took heat/pressure damage and, if I didn't get out fast enough, got stunlocked to death, *even if the messages didn't appear*.
... @DrCelt

**Comment by AutismSpider** [comment]
@xpcybic happens with slime's normal temp and pressure levels in the air loop you then die to some magic heat or cold in the pipe some how. happens to monkeys some times to.

**Comment by gbasood** [comment]
o l d

**Comment by Imagebard** [comment]
Holy shot who c-
I mean, fuck done.
