### ISSUE TITLE
Change station time to sync with server time instead of always being noon

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9846]
It would be nice if we could actually have station times that aren't always 12 to 14-15. Would add some diversity and allow for real graveyard shifts

Would only need to edit the roundstart announcement to not mention noon, set station time to server time at world/New() (or Init, whichever is better) and add a way to know at what absolute time the shift started, most likely in PDA + Admin Status entry

**Comment by Probe1** [comment]
muh tradition

**Comment by Shadowmech88** [comment]
If we do add this, we'd need to store what time the shift started somewhere where players can see it, so they can check how long the shift's been going on.

**Comment by 9600bauds** [comment]
Hello
The automatic diagnostic and announcement system welcomes you to the station
The time is
Real 
Nigga hours
Honk if u up
Have a secure day
