### ISSUE TITLE
No extended N2 tank

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9847]
(WEB REPORT BY: pwirby REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Vox engineers don't spawn with extended capacity N2 tanks in their survival equipment box, like human and grey does with O2 ones.
> 
> General description of the issue
> Vox engineers don't spawn with extended capacity N2 tanks in their survival equipment box, like human and grey does with O2 ones.
> 
> What you expected to happen
> Vox engineers/ whatever jobs that spawn with enxteded capacity tanks, also spawn with N2 extended capacity tanks.
> 
> What actually happened
> Vox engineers spawn with Extended capacity O2 tank instead of N2 one.
> 
> Steps to reproduce if possible
> Select Vox race, join the game as atmos technician, look inside your bag, then you survival equipment box.

**Comment by 9600bauds** [comment]
I guess you could empty a O2 tank and fill it with nitrogen, not like it really matters since the large nitrogen tank will never ever run out

**Comment by SysadminJeroen** [comment]
@9600bauds I assume that some want to walk around without a hardsuit on for a prolonged period.

What you can do is set your emergency N2 tank to output only 16 kPa, go to the main above the chapel and you'll find a N2 canister. Use that to fill it up completely and you'll have at least 10 minutes of N2.

**Comment by 9600bauds** [comment]
Use an air conditioner to empty an extended O2 tank, load it with nitrogen
I do this with oxygen (without emptying of course) as human and it lasts me for well over 30 minutes, never needed a refill

**Comment by Probe1** [comment]
you are a bird
if you want nice things you have made a mistake.

**Comment by Probe1** [comment]
You heard me PJ"Bird lover"

**Comment by Killette2** [comment]
You said vox engineer right? Just scrub out all that disgusting oxygen in the air.
