### ISSUE TITLE
R&D system rework suggestion

### ISSUE THREAD

**Issue by MercuryDoll** [d3athrow/vgstation13#9848]
Since noone likes the menial task that is stuffing a list of items into the destructive analyzer, here is an idea that i thought up that, with the right execution, should reward active research as well as help out if noone bothers to do research with an automation feature.
Borrowing from TBS and RTS games, research is now done with a "progress bar".

Items, or "Technologies", have a categorical (Research Level) requirement that is just like the current one and a Research Point (RP) requirement. Research Points are produced by CPUs.
A new machine, called the Processor Rack (similar to server racks) will hold up to 8 CPUs. There are different qualities of CPUs, each producing a different amount of RP per second. R&D starts out with two basic CPUs. Additional CPUs can be either bought via cargo or produced by R&D themselves, with higher quality CPUs available at specific Research Levels.

Research is done by activating a technology's research, CPUs are either automatically or manually assigned, so multiple things can be researched at once or scientists can focus on getting one specific technology faster. Additionally, there's an Auto-Mode which automatically starts research on the next new tech whose requirements are met.

Once research of a technology is completed, it can be produced instantly. Specific Technology Level points are also rewarded depending on the nature of the item. These TechPoints increase the Research Level (eg. Power). The Destructive Analyzer will function similar, but instead of directly upgrading the Research Level, it instead rewards a small amount of techpoints that could potentially upgrade Research Levels, as well as reduce the necessary RP to research the analyzed item by 90%, has it not been researched yet.

![image](https://a.pomf.cat/hdfvro.jpg)

**Comment by gbasood** [comment]
I mean we actually wrote up a design doc on how to rework R&D
But no one's tried to take it up yet
Good idea, though, if that never gets done this is at least a step in the right direction
We're a little short on coders wanting to do huge reworks like this right now for the amount of tasks we have

**Comment by MercuryDoll** [comment]
It is simply a thought from an ideaguy's mind and completely open to discussion. It of course needs a lot of indepth work, coding, number juggling for balance etc. I don't see it implemented any time soon and i'd be completely fine if another system is chosen over it, but i just wanted to let this idea heared out of curiousity if people would be interested in it.

**Comment by PJB3005** [comment]
There's both a design doc and the great 'how do we rework R&D' issue

**Comment by icantthinkofanameritenow** [comment]
@gbasood 
Where?

**Comment by Kurfursten** [comment]
How does this help if no one is doing the research? It looks like you have to input research choices anyway.

**Comment by MercuryDoll** [comment]
You can manually choose a research or activate Auto-Queue™, where it automatically activates the next available research once the last one finished. This way, even if noone wants to handle research, without upgrading from the two standart CPUs, eventually there should have been enough research done to make the first upgrades available.

**Comment by icantthinkofanameritenow** [comment]
So it automates research completely, invalidating he point of having people do it at all. That's not an improvement!

**Comment by ComicIronic** [comment]
Based on what we have now as a mindless job that nobody wants to do, I think it's a major improvement.

**Comment by icantthinkofanameritenow** [comment]
I guess so, but I would prefer something that actually requires human involvement, and does so in a way that isn't "follow the checklist" or "look at these progress bars every now and then". 

By any chance do you still have that RnD rework design doc?

**Comment by clusterfack** [comment]
Minigames that arent fun that you have to play (or ignore) a million times are awful

**Comment by icantthinkofanameritenow** [comment]
@clusterfack 
I'm not exactly a fan of just turning on one button and letting the game take care of all the rest either.

**Comment by clusterfack** [comment]
That's what a lot of systems boil down to already

**Comment by Kurfursten** [comment]
The idea has grown on me, but only if

> Active improvement of the research servers results in research completed at least as far as diamond mining drills by the time miners show up at R&D
> Passive improvement of the research servers is slow enough that people don't just let it run itself every shift

This kind of system would obviously require a lot of tweaking if implemented.
