### ISSUE TITLE
Feature Request - Add AltClick() to Microwave

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#9852]
```
/obj/machinery/microwave/AltClick()
    if(!usr.incapacitated() && Adjacent(usr) && usr.dexterity_check()))
        cook() //Cook checks for power, brokenness, and contents internally
        return
    return ..()
```

**Comment by gbasood** [comment]
literally just
make a PR if you have working code

**Comment by Kurfursten** [comment]
I don't have my stuff on my new laptop

Easier to let someone else take the credit

**Comment by FudgePucker** [comment]
Funfact: if it is just changing one file in the repo, you can do it from your web browser, hell I have done like 3-4 PRs and no one has caught on that I have no fucking idea what I am doing.

**Comment by Kurfursten** [comment]
You should never be changing one file unless it's a hotfix

Changelogs!
