### ISSUE TITLE
Warden should have access to the Security account

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9856]
(WEB REPORT BY: durgen REMOTE: 172.93.109.202:7777)
The Warden is in charge of the brig and securitie's gear etc.
It makes more sense for the Warden to have access to that money than the HOS.
Could they perhaps both get the account details?

**Comment by Probe1** [comment]
I disagree.  The head of the department has the department account.  The Warden is not the head of the department and it doesn't make much sense to add an exception.

What could be done is adding ways for non heads to access department accounts through the accounts database code.  That way if a HoS doesn't exist, the account details can be accessed by say, a Captain.

**Comment by Durgen** [comment]
> and it doesn't make much sense to add an exception.

The QuarterMaster is already an exception

> What could be done is adding ways for non heads to access department accounts through the accounts database code. That way if a HoS doesn't exist, the account details can be accessed by say, a Captain.

that sounds like a good alternative

**Comment by Durgen** [comment]
gah, I am a github noob and don't know how to do comment markup

**Comment by ComicIronic** [comment]
Leave a gap after your blocks to separate them out.
The QM isn't strictly non-head anyways, the HoP is considered to manage service and cargo in a transient capacity. The big danger with the Warden having access to the account is ordering stupid shit without authority (which the QM already does, as a good example).

**Comment by gbasood** [comment]
@ComicIronic I thought cargo had their own budget account actually?

**Comment by Probe1** [comment]
Cargo is a half-department and the quartermaster is the head of it.  He isn't a real head just like cargo isn't a real department, but they still have some of the benefits.  They are nominally supervised by the head of personnel.

**Comment by ComicIronic** [comment]
As an aside, don't you have to lynch the QM for Rev?

**Comment by Probe1** [comment]
No, he is not considered a full head because cargo is not considered a full department.  De jure, control of the department is ultimately in the HoPs territory but de facto the Quartermaster is the alpha and omega of cargo.

However the Head of Personnel lacks access to the cargo account I believe.  Maintaining my position that giving a non head of a department (the Warden) is an anomaly.

**Comment by gbasood** [comment]
Warden is a subordinate of HoS and should have to go through his department head to get to department funds.
The only way warden will get their own budget is if we literally lose our sanity and re-add prison station
(or if we somehow manage to support more than 90 players without problems we might actually WANT a prison station, but probably not)
