### ISSUE TITLE
electric chair toggling as ghost

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9860]
(WEB REPORT BY: ziekr REMOTE: 172.93.109.202:7777)

> Revision 70040064c01e81e7e1e51dd93d2b28a53b3d259e
> 
> General description of the issue

electric chair doesnt prevent ghosts from toggling it on and off

> Steps to reproduce if possible

right click electric chair as ghost
click toggle electric chair

**Comment by clusterfack** [comment]
Check for ghosts in the verb that allows you to toggle it

**Comment by 9600bauds** [comment]
Just do !usr.incapacitated(), it's all the sanity needed and it checks for ghosts too

**Comment by ComicIronic** [comment]
Verbs are where good code goes to die, we should really be replacing them.
