### ISSUE TITLE
Windoor Collision Seems Messed Up

### ISSUE THREAD

**Issue by Shadowmech88** [d3athrow/vgstation13#9861]
Some windoors aren't responding to being bumped, specifically the southeast armory windoor and the left windoor of the pair of windoors near the brig's east maintenance.

Also, firing a hookshot at a windoor doesn't seem to cause the hookshot to hit the windoor if it hits the "inner" side, the one that faces the tile it's on. It does stop, but it just hangs in place until it reaches its max "length" and then retracts. It doesn't actually grab the windoor.

**Comment by clusterfack** [comment]
It seems like the windoors, but it is actually the fact you are being blocked by those sideways window in the secure armory. I haven't yet found time to investigate why those windows in particular are causing you to bump them.

**Comment by clusterfack** [comment]
We have investigated this and made a bug report
http://www.byond.com/forum/?post=2079322

**Comment by Shadowmech88** [comment]
Probably due to some workaround we did rather than Lummox fixing it, but I tested locally and none of these issues still exist.
