### ISSUE TITLE
Windoor in cargo doesn't stop crates from passing through into the disposal chute

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9862]
#### Description of issue

/obj/machinery/door/window for some reason is being a prick and letting crates pass right through it into /obj/machinery/disposal/deliveryChute when the conveyor is on.
#### Difference between expected and actual behavior

Supposed to be dense. I checked the variable and it is dense.  But things still pass through.
#### Steps to reproduce

Turn on the conveyors in cargo and let a crate run through.
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by ComicIronic** [comment]
Possible duplicate of #9861

**Comment by clusterfack** [comment]
This is due to the layering of the disposal being lower than the windoor so it is above it on the bump order, it needs to be lowered.

**Comment by ComicIronic** [comment]
Shouldn't windoors be ON_BORDER anyways?

**Comment by clusterfack** [comment]
Nah that's not REALLY how it works anymore

**Comment by Shadowmech88** [comment]
Tested locally, this is no longer the case.
