### ISSUE TITLE
INFINITE MEDICAL MODULE BOARDS

### ISSUE THREAD

**Issue by kol1th** [d3athrow/vgstation13#9863]
#### Description of issue

Mediborgs can take infinite medical module upgrades

![](http://puu.sh/oEyHz/46a1214640.png)
#### Difference between expected and actual behavior

Expected it to only take one, but instead INFINITE UPGRADED HYPOSPRAYS
#### Steps to reproduce

Use more than one medical module upgrade on a mediborg
#### Specific information for locating

Medical module board
#### Length of time in which bug has been known to occur

I'd assume since 510, but I haven't tried before now
#### Server revision

416f345e9029f0fccacf211221a265d43a19994f
#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [X] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by Probe1** [comment]
I reproduced it and tried to fix it but var/installed didn't seem to want to work.
