### ISSUE TITLE
Greys now lack a sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9864]
(WEB REPORT BY: xevonix REMOTE: 172.93.109.202:7777)
If you spawn a grey, it is invisible.
Code is probably messed up somewhere.

**Comment by PJB3005** [comment]
> Code is probably messed up somewhere.

Thanks captain obvious.

**Comment by Shadowmech88** [comment]
What, like your whole body's invisible?

**Comment by ihadtoregisterforthis** [comment]
Minmaxing race strikes again.
I swear it wasn't the sprite fix

**Comment by Shadowmech88** [comment]
> invisible naked greys running around wreaking havoc

**Comment by clusterfack** [comment]
A similar thing has happened with fat naked skeletons, that could be it. Or someone could have simply erased the proper sprite from one of the dmis as people so often do.

**Comment by Shadowmech88** [comment]
It doesn't seem to be 100% of the time. I saw Yahir last round and he wasn't invisible.

**Comment by gbasood** [comment]
Possibly related to runtimes?
Next time you see this check for the player's name in runtime logs.

**Comment by Intigracy** [comment]
Yeah, the runtime logs update almost immediately.
