### ISSUE TITLE
Add pitch variance to woop woop for helmet sirens

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9868]
Related: https://youtu.be/IYln15uN8KA

**Comment by Intigracy** [comment]
Pitch variance is the best

**Comment by 9600bauds** [comment]
We discussed this in the original PR and the general idea was that it'd sound really damn weird

**Comment by gbasood** [comment]
@9600bauds It sounds really damn weird right now though
Do we have control over the range of the pitch variance?

**Comment by Intigracy** [comment]
https://dl.dropboxusercontent.com/s/fdee68u8mhvyzja/2016-05-05_12-40-44.mp4?dl=0

sure does

**Comment by gbasood** [comment]
@Intigracy Yeah okay but
**WHAT LEVEL OF CONTROL DO WE HAVE OVER PITCH VARIANCE**
Because if we can define it to vary only by a very small amount it will still sound better than absolutely no pitch variance
which was my goal
