### ISSUE TITLE
Pulling things from tiles diagonally to you gets really fucky

### ISSUE THREAD

**Issue by Konater** [d3athrow/vgstation13#9874]
It's hard to explain but you'll either stop pulling it after it moves one, not pull it at all or you'll move with it perpendicularly with it still being on a diagonal tile
This started happening yesterday the same time we could move things through walls

**Comment by Hoshi-chan** [comment]
I can second this. I was just coming here to report it.

Pulling things in general seems kind of busted. Even when they're directly next to you, you sometimes need to stand there for a few seconds before moving or you won't start to pull; you'll just walk away with nothing happening.
