### ISSUE TITLE
Lighting broke again

### ISSUE THREAD

**Issue by Dizor** [d3athrow/vgstation13#9875]
No idea what did it, possibly too many light tiles on the station, but shit broke last round 

https://gfycat.com/FinePiercingFish

No idea how to get Webms uploaded so this is the best I got

**Comment by PJB3005** [comment]
Sounds like the process isn't ticking, the thing with the mesons is very weird though.

**Comment by clusterfack** [comment]
This is just a problem with the process scheduler in one round, there's no real information we can take from this
