### ISSUE TITLE
Don't show non-admins who's readied up at the lobby

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9876]
People often use it to kind-of-meta which gamemode could be played based on the minimum pop for each gamemode, it's not uncommon to see people say "3 more for blob/rev/malf" when the round is about to start.
Some people take the meta pretty far, either intentionally or not, by comparing the amount of people who readied up with the amount of people in the manifest, so they can have a fair idea of whether it's newcops etc.

There's not really that much non-meta use for this kind of information, anyways, I don't think anybody would miss it terribly

**Comment by gbasood** [comment]
It sucks but if it's being used for this sort of metagaming then it should be changed.

**Comment by 9600bauds** [comment]
Having a hard time imagining what else could you use the ready up count for

**Comment by ihadtoregisterforthis** [comment]
As I see it, "3 more for blob/rev/malf" isn't so much of meta as it is encouraging people to join so there are more options for better modes instead of double traitors all day.
What is true is the inverse, players knowing which modes it can't be because there are too little players at start.

**Comment by 9600bauds** [comment]
It might not be meta in the intentional or malicious sense of it, but yes when you let everyone know that it can't be rev before the game starts then they won't react the same to an assistant with a flash. Even if it wasn't in their initial intentions to meta.

**Comment by Killette2** [comment]
It's not really meta since when the game starts it list the potential round-types anyways.

**Comment by 9600bauds** [comment]
I thought it lists all the gamemodes available in secret, without excluding the ones with too little pop for?
In either case, the whole "30 people readied up vs 20 people in manifest" check isn't exactly a secret

**Comment by Killette2** [comment]
Are you implying a nuke ops and vox raiders in the same roundstart as mixed? That's horrifying.

You also can't manifest meta due to silicons (including MoMMIs who you cannot PDA), vox traders, and round start xeno larvae (metaclub member only).

**Comment by 9600bauds** [comment]
I'm not disagreeing in that it's not 100% accurate, but it gives you a pretty good idea, otherwise people wouldn't do it

**Comment by CptWad** [comment]
Well you also have to account that robots and now vox traders dont show up on the manifest, enough to hide nukeops now

**Comment by 9600bauds** [comment]
Non-MoMMIs show up at the PDA messenger which is a better way to do this than the manifest
If you assume a semi-constant number of MoMMIs and traders, not fluctuating incredibly every shift, then yeah you can get a good idea

**Comment by Boxe** [comment]
but i used this to tell when someone i want to play with is playing

**Comment by Kurfursten** [comment]
I like knowing who is ready. My two favorite modes require 25 people to be ready. How else can I bully people into readying up?

**Comment by ihadtoregisterforthis** [comment]
You would need to account for people going back to lobby from filled roles.

**Comment by 9600bauds** [comment]
All I can say here is that if metaing for newcops didn't work, then people wouldn't do it.

**Comment by Killette2** [comment]
@ihadtoregisterforthis also has a point, some people would rather try to roll again if they don't get a specific job rather than go to the HoP (who may or may not even exist) and jobs also have a extra slot which can only be filled by late joining. IE 2 starting botanist but 3 can play, same with doctors and scientist, meaning even if on high it won't fill you unless you late join.

Also I don't think meta for nuke ops isn't that big of a deal if you're not a shithead and don't prepare for it. If I find it's a nuke ops round and I'm something like a botanist or xenobiologist, I'd probably just slack off for I know the grind won't get far but wouldn't actively gear up for a fight.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Irrelevant in the post-d*namic era

**Comment by Intigracy** [comment]
Now that cult fires with 11 people.
