### ISSUE TITLE
It is 100% possible (albeit very difficult) to pick up bullets in flight and throwing them acts like you fired them from a gun

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9882]
Remember that discussion a while ago about the method projectiles use to prevent you from picking them up?
Turns out they don't
You can't pick them up by clicking on them, but Alt+clicking on the tile works
This is made much worse by #9871

**Comment by 9600bauds** [comment]
amazing

**Comment by Exxion** [comment]
The clown in the last round was showing us this and ended up giving me the bullet (from an assault rifle)
An ERT member decided to try to post-round griff me so I decided to throw the bullet at him
I got the knockdown and the bullet stuck in the wound
Must have a hell of a throwing arm

**Comment by Probe1** [comment]
I saw a clown throw an electrode last round :laughing: :100: :100:

**Comment by clusterfack** [comment]
You can also pick up immovable rods, and throwing them is what triggers their march of death

**Comment by Exxion** [comment]
So uh
Wouldn't this be fixed by just making `/obj/item/projectile/attack_hand()` not call the parent?

**Comment by Shadowmech88** [comment]
[IT'S A FEAAAATUUUUREEEEEEEEE]

**Comment by Exxion** [comment]
Honestly I think it would be hilarious to allow catching projectiles by clicking them, and if you're that fast you deserve some kind of bonus
But throwing the projectiles at full power is too much

**Comment by 9600bauds** [comment]
Watch how it gets abused by people with macros

**Comment by Shadowmech88** [comment]
If this does get fixed, an exception should be added for the timestop var so that projectiles frozen in time can still be picked up and thrown back at the shooter.

**Comment by PJB3005** [comment]
Macro abuse can be fixed by randomizing the name of the projectile.

**Comment by SysadminJeroen** [comment]
@PJB3005 Surely a permanent fix would be to just disable picking up projectiles, right?

**Comment by Killette2** [comment]
Come to think of it, macro abuse would be able to pick up most projectiles if they aren't given a very specific name besides bullet or electrode.

I'd love to see someone catch a staff of change bullet, and sell it however.

**Comment by Exxion** [comment]
I could have sworn "addresses" worked for autoclosing

Anyway, projectiles can now only be picked up while timestopped

**Comment by ComicIronic** [comment]
Did you fix this, because the code I saw didn't change the pickup verb, only attackhand

**Comment by Exxion** [comment]
`attack_hand()` is how the pickup verb is called

**Comment by Exxion** [comment]
Oh wait, you're right, it's also a verb
So no, I guess this isn't fully fixed yet
Easy fix, though
I'll do it later

**Comment by 9600bauds** [comment]
I'm fairly sure the pickup verb doesn't work for picking up bullets, I tried it once

**Comment by Exxion** [comment]
[Shrugging emote I'm too lazy to find right now]
Either way, I'll check later

Also, I realized I should _probably_ do more about the timestop thing
Because right now, you can pick up timestopped bullets, but then you can just throw them again outside of the timestop area

**Comment by Shadowmech88** [comment]
> but then you can just throw them again outside of the timestop area

I don't think that's a huge problem. The only person that could do that is a _wizard_, after all.

**Comment by Exxion** [comment]
But my emulsions

Also you could disarm a wizard holding the bullet and throw it at them

**Comment by 9600bauds** [comment]
I mean honestly at that point you've earned it

**Comment by Exxion** [comment]
Turns out the pickup verb calls `attack_hand()` so this actually _is_ fixed

**Comment by Killette2** [comment]
What if we add an intentional version of this? A way where you can say "No." like in the Matrix where you can stop or grab bullets if you obtain this somehow.

**Comment by Shadowmech88** [comment]
You mean like the timestop spell?

**Comment by Killette2** [comment]
Does timestop currently stop all projectiles and thrown items letting them be picked up? Also that crossed my mind, but what if we added it to vampires? People go nuts over that dio shit right? I don't know how it works, just slap it in there the kids will love it.

**Comment by 9600bauds** [comment]
> what if we added [timestop] to vampires

I don't know WHAT crazy weed you've been growing but you need to lay off of it

**Comment by Killette2** [comment]
No that's too much. What if something lesser just for bullets.

also >dude lmao weed
