### ISSUE TITLE
Projectiles do not properly collide with windows

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#9883]
Essentially heres what happens
since forever you could pick up projectiles, the downside was that there was no way to do that fast enough with byonds lag and projectiles, when picked up would still keep going while also being in your hand meaning if you did snatch an electrode from mid air you would still get stunned
However on pure chance I noticed a projectile just stop and wait next to a window
If a window has four sides [ west, ] east, - north and _ south heres what I saw ( e = electrode)

e]

if the projectile, such as an electrode, flies onto a tile that also has a window facing the direction of the tile its going to next, the projectile STOPS
this at first means you cant do anything to it
but 
if you alt click the tile
you can pick up your projectile
and throw it at people
This works with most projectiles, bullets dont work well with it but all energy blasts seem to work fine
Intrestingly enough they are normal sized items so you can fit them in your backpack, they however cannot be clicked and must be alt clicked if you want to pick them up, or in the backpacks case dumped out

**Comment by CptWad** [comment]
![hell](https://cloud.githubusercontent.com/assets/3959840/15001982/39f14da6-1151-11e6-9a73-38064375b32b.png)
Alright heres some further testing
Laserguns, and things like laserguns (xraygun lasercannon etc) are not effected
Spurs and its children are but they automatically dissapear so they dont fuck up
Ricochet Rifle is sorta, you have to try it yourself to see the wild consequenses, use a long line of windows for full effect
Rocketlaunchers are affected and are hilarious

**Comment by gbasood** [comment]
Fixed by #9893
