### ISSUE TITLE
Bloodred hardsuit (/obj/item/clothing /suit/space/rig/syndi) displays your bare hands even if you have gloves

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9887]
![dreamseeker_2016-05-03_21-27-20](https://cloud.githubusercontent.com/assets/6526157/15002268/daa8a2ca-1175-11e6-8de7-4f6ce671751c.png)
Some flags problem

**Comment by Shadowmech88** [comment]
I always figured the suit's built-in exterior gloves were just flesh-colored.

**Comment by ihadtoregisterforthis** [comment]
wow, racist

**Comment by Killette2** [comment]
I thought they came in with built in stealth cloakers for just your gloves.

**Comment by ComicIronic** [comment]
This is caused by the inherited coverage flags, which hide your gloves icons.
I'm surprised the suit doesn't have its own gloves.

**Comment by clusterfack** [comment]
Paging @drcelt

**Comment by Killette2** [comment]
Paging Dr. Dick

**Comment by ghost** [comment]
hello

**Comment by ghost** [comment]
this is a sprite issue

**Comment by ghost** [comment]
@Skullyton - mind spriting a fix to this for me?

**Comment by ghost** [comment]
On it, boss.

Operator black, or similar red?

**Comment by Shadowmech88** [comment]
I personally think black would be the better choice.
