### ISSUE TITLE
Ranged weapons (including lasers) do precisely fuckall to blobs

### ISSUE THREAD

**Issue by Exxion** [d3athrow/vgstation13#9888]
@DeityLink

100% Tested<sup>®™</sup>

**Comment by Exxion** [comment]
Actually hold on
Just in case this has to do with movecode rather than the blob itself
@clusterfack

**Comment by icantthinkofanameritenow** [comment]
Confirmed to be immune to ALL forms of ranged damage now, not just guns. Someone fucked up really, really badly.

**Comment by Exxion** [comment]
My money's on the movecode changes, then

**Comment by DeityLink** [comment]
Lasers worked just fine when we spammed blobs for an entire day after my update was merged.

**Comment by Exxion** [comment]
Movecode it is
@clusterfack @clusterfack @clusterfack

**Comment by Shadowmech88** [comment]
How do flamethrowers fare against them?

**Comment by icantthinkofanameritenow** [comment]
@Shadowmech88 
Flamethrowers never worked against blobs very well.

**Comment by Shadowmech88** [comment]
@icantthinkofanameritenow 
I changed that when I reworked them.

**Comment by Exxion** [comment]
It's not even balance
It's 100% a bug
The blob is entirely impossible to defeat without lasers

**Comment by Killette2** [comment]
> He hasn't heard of the flashbang fireaxe combo

**Comment by Exxion** [comment]
There are two fire axes on the whole station
No matter how good you are, two people can't subdue an entire blob once it reaches a reasonable size

**Comment by Killette2** [comment]
Welders are pretty good and bountiful, barely being weaker than a fireaxe against blobs.

**Comment by Exxion** [comment]
They also run out all the time and also the new SANICBLOB is exceptionally robust against melee attackers
And that still doesn't mean this shouldn't be fixed

If someone (@clusterfack) hasn't fixed it by whenever I get a chance (probably Thursday), I guess I'll take a look

**Comment by AutismSpider** [comment]
Blob grows to fast for welders to be good out right need plasma-cutters if going do melee shit vs the new blob (fire axe is god awful now use lasers or burn base weapons or fuck off)

not only that cant be smart ass and teleport diona in cap/riot suit on top of the core any more the walls near the core tick the fastest and will go fist of the north on you.

**Comment by Exxion** [comment]
> fire axe is god awful now

Three hits to pop a blob chunk
It's not as good as it used to be, but it's still pretty solid

**Comment by ghost** [comment]
Confirmed that lasers do nothing against them, bullets stop when fired at them (And can be picked up and thrown by alt-clicking the tile and then clicking the bullet)

And emitters, when turned on and fired at the blob, the beams start to stack up on the tile where they collide with the blob, this'll cause some serious shit as it takes a few seconds of sustained fire for it to stack to server-crashing levels

**Comment by Exxion** [comment]
Emitters do what now

OK fine I'll change branches and look at it now

**Comment by AutismSpider** [comment]
old emitter bug is back what fun.

means you can run time the game in other ways with emitter beams

**Comment by Exxion** [comment]
No, there's still a limit to how many stack up, and the cause is something else entirely

**Comment by Killette2** [comment]
This is why you ask cargo for industrial welders. The double capacity REALLY helps.

**Comment by DeityLink** [comment]
@Killette2 

> flashbang fireaxe combo

Now that blobs get notified when the area around their core gets attacked, good luck with that.
