### ISSUE TITLE
Blobs Immune to lasers

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9889]
(WEB REPORT BY: mechamusume91 REMOTE: 172.93.109.202:7777)

> Revision 51f2dadfddb31dde056913193129a98c496cff47 
> 
> General description of the issue
> For whatever reason blobs are immune to everything except melee attacks
> 
> What you expected to happen
> 
> What actually happened
> 
> Steps to reproduce if possible

**Comment by Exxion** [comment]
#9888
