### ISSUE TITLE
Baguloth can be escaped if you combine the backpacks in your hands/inventory rather than on the ground

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9896]
The act of combining two bags of holding has explicit code to immediately consume the user into the resulting singularity, the problem is that if the singulo spawns in the same tile as you, this won't work and you can run away from the singularity before it has a chance to consume you.

**Comment by ihadtoregisterforthis** [comment]
Emergent gameplay™

**Comment by Killette2** [comment]
I've done this before during a round. This is NEVER 100% safe, even with magboots or tables blocking you from a square diagonal of the singulo. When you create it, it has a chance of insta-sucking you in because fuck you that's why.

The other thing is, during that round I attempted it a second time, also doing it diagonally. I did not succeed, but lmao 2bagulos.

**Comment by ComicIronic** [comment]
> because fuck you that's why.

Literally this though.
Bagulo yourself fam.

**Comment by Killette2** [comment]
So when has placing items into adjacent items not existed? That feature's been around longer than I can remember. Is this really a bug?

**Comment by 9600bauds** [comment]
It is a bug. When you mix the two bags it literally throws you towards the singulo (i.e. so that you are instantly sucked in).
The problem is that if you're in the same tile as the singulo when it spawns, the throw doesn't do anything.

**Comment by Killette2** [comment]
If you're on the same tile as the singulo, I think you have bigger problems. Such as death.

**Comment by Probe1** [comment]
I reported this in the PR to add baguloth :zzz: 

Surely coders will fix it soon.

**Comment by 9600bauds** [comment]
> If you're on the same tile as the singulo, I think you have bigger problems. Such as death.

Yes, which is why it should KILL YOU

**Comment by Killette2** [comment]
_It was just a hologram_

**Comment by gbasood** [comment]
I think this might be as simple as just making it fire process() in the same tick as it's spawned?

**Comment by 9600bauds** [comment]
Probably just use Bump() or something instead of throwing the user at the singulo (which will at best effectively just Bump())
