### ISSUE TITLE
The "alarmed firelocks requiring access or a crowbar" discussion

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9904]
Is the ID lock effective, considering most people simply carry a crowbar to get around it?
Does the ID lock do enough to justify it's existence?
Should they have special checks to not ID lock inbetween two zones where their opening wouldn't matter anyways? e.g. inbetween two space tiles, or inbetween a space tile and a room with 0KPA
Related issue: #9359

Happy FireFighter's Day Everybody!

**Comment by Shadowmech88** [comment]
> Should they have special checks to not ID lock inbetween two zones where their opening wouldn't matter anyways? e.g. inbetween two space tiles, or inbetween a space tile and a room with 0KPA

I think this is fine. Instead of having firelocks trigger at a specific pressure on either side, have them trigger at a specific pressure _differential_.
After all, opening a firelock with a million kPa behind it wouldn't matter if the room you're in now also has a million kPa.

**Comment by Exxion** [comment]
If I'm not mistaken, that's how they already work
They _close_ at an absolute pressure, but only _lock_ at a certain differential, I believe

**Comment by 9600bauds** [comment]
They specifically fuck up with space tiles because they think the whole room is 6K and temperature difference keeps them locked
