### ISSUE TITLE
Deep fried clown goblins return mask and shoes; for infinite, deep fried goblins

### ISSUE THREAD

**Issue by ghost** [d3athrow/vgstation13#9906]
Clown goblins return the mask and shoes after being deep fried, as oppossed to just disappearing and leaving the deep fried corpse behind. This does allow for infinite food in the form of deep fried goblin products, as the item is accepted by the candy machine and cereal maker, (couldn't try the oven and ice cream machine yet).

...I wouldn't mind this bug be left alone for a while, though

**Comment by 9600bauds** [comment]
Sometimes you need to take a step back and wonder what the fuck is this game

**Comment by Shadowmech88** [comment]
I'm surprised you can fry them at all without deepfryeverything turned on, seeing as they're mobs.

**Comment by Killette2** [comment]
You can grab the botany starting chicken (and any mob really) and put them in the cereal machine, deepfriers, hell anything. It's still amusing to get rid of that chicken by making it someone's cereal.

**Comment by ComicIronic** [comment]
Can you deep fry a buffalo in 45 seconds?

**Comment by Killette2** [comment]
https://www.youtube.com/watch?v=Tc8iu0XFUQc

**Comment by clusterfack** [comment]
This will be fixed in my most recent bugfixes pr
