### ISSUE TITLE
Coleslaw

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9907]
(WEB REPORT BY: neatweeaboo REMOTE: 172.93.109.202:7777)

> Revision fbb31265a68408f543a21d4095edf9326903338c 
> 
> General description of the issue
> Recipe for coleslaw yields burned mess
> 
> What you expected to happen
>  10 units of Vinegar, 1 Carrot, 1 Cabbage to yield 1 coleslaw
> 
> What actually happened
> got a burned mess
> 
> Steps to reproduce if possible
>  10 units of Vinegar, 1 Carrot, 1 Cabbage

**Comment by Killette2** [comment]
How many times did you try making this? Sometimes the microwave just says fuck you, but maybe the recipe is documented wrong, like plant pots were. The best way is to look at the code to find out your answer.

**Comment by Probe1** [comment]
Can be closed.  Recipe on wiki incorrectly stated the amount of vinegar was 10 when it was 2.  This has been fixed.
