### ISSUE TITLE
Can't walk into windoors to open them

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9908]
(WEB REPORT BY: yred REMOTE: 172.93.109.202:7777)

> Revision fbb31265a68408f543a21d4095edf9326903338c
> 
> General description of the issue
> Walking into a windoor that is not on your tile does not open it.
> 
> What you expected to happen
> Windoor opening when I walk into it
> 
> What actually happened
> Does not open.
> 
> Steps to reproduce if possible
> Walk into a windoor that is not on your tile (e.g. first windoor out of the crab nest on Meta).

**Comment by ComicIronic** [comment]
@clusterfack still happening or an old issue?

**Comment by clusterfack** [comment]
Still happening but a dupe
