### ISSUE TITLE
Gunfab

### ISSUE THREAD

**Issue by ComicIronic** [d3athrow/vgstation13#9909]
Back in the ass end of last year, I was thinking of adding d20's ammolathe to the server for sec.

Since new designs (and a new fabricator) are largely trivial additions in terms of code, can we instead think of any issues with Sec being able to print its own researched guns ( or at the least, ammo )?

**Comment by Kurfursten** [comment]
If you're just going to make it ammo, you should do a vending machine and rip off the Ammo Bandito from Bioshock.

**Comment by Shadowmech88** [comment]
I've been kicking around ideas for custom ammo with properties based on what kind of metals are used in its construction. For example uranimum bullets would irradiate their target, phazon bullets would have infinite penetration, etc.

**Comment by ComicIronic** [comment]
Yeah but I hate vending machines because you have to refill them if one item is sold out - fabs are more versatile. We already have the auto lathe making bullets anyways

**Comment by Probe1** [comment]
So I saw this issue about 5 minutes after it was made and I still haven't thought of a tactful way of saying it.  

The general fabricator is still a pile of shit that only Traitors use.

Before you left you said you wanted to change it.  Seeing it in the game right now doesn't give me a tremendous amount of faith in a new machine when we have the general fabricator which it is borderline useless.

I'd be excited if you said you were going to rework it as part of this.  Two birds with one stone.

**Comment by icantthinkofanameritenow** [comment]
@Probe1 
Agreed. The only remarkable things a non-traitor Mechanic can make with a general fab are more hand teles- and good fucking luck getting the Phazon needed to make them. Come to think of it, flatpack fabricators could use some love too, I've hardly if ever seen them being used for any reason whatsoever.

**Comment by ComicIronic** [comment]
General fab rework 
N E V E R

No but really the forge/moulds/genfab update is going to happen eventually, it just takes a lot of work.

**Comment by Probe1** [comment]
forge that was the word fuck

I thought about it for a solid five minutes trying to remember the name.
