### ISSUE TITLE
cant clean soot with a rag

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9910]
(WEB REPORT BY: manfreed REMOTE: 172.93.109.202:7777)
If you click on the thing you want to clean of the floor you clean the thing, not the floor

> You begin to wipe down the motor oil.
> the floor remains dirty because you didn't click on the floor. In the case of soot it is impossible to click the floor since it covers the whole tile making it impossible to clean with a rag. This might apply to other cleaning methods as well but I didn't test that.

**Comment by Killette2** [comment]
You are cleaning the soot though, it's nice and shiny now.

**Comment by ComicIronic** [comment]
Can you not alt click the floor tile?

**Comment by Exxion** [comment]
You can Alt+click the floor to do it, but it's unintuitive
Cleaning messes should
You know
Clean them

**Comment by ComicIronic** [comment]
An issue with the ambiguity of "cleaning messes".
You can polish a turd.
