### ISSUE TITLE
You still "step on" glass shards when lying down, a.k.a. "sliplocks are gone but shardlocks remain"

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9913]
Slips were balanced to not slip you while you're already down, to prevent people from dragging someone on top of a banana peel over and over and stunlock them forever.
However glass shards still do this, so if you manage to slip someone and take off their shoes then you can just drag them on top of a shard over and over and stunlock while murderizing the shit out of them.

**Comment by Killette2** [comment]
I dunno, having your body dragged across glass seems like it would have a pretty painful effect.

**Comment by 9600bauds** [comment]
You have clothes, and this works even with a hardsuit on
And the premise of glass shards is that cutting up your feet makes you fall down, it makes no sense that it'd keep you down

**Comment by Killette2** [comment]
The average person is wearing a jumpsuit, and maybe a labcoat. Hardsuit I could understand protecting you, but I think it would be a bit difficult getting up if someone is actively dragging you across glass.

**Comment by 9600bauds** [comment]
You can get up just fine while someone is dragging you around and toolboxing your face in. In any case, wouldn't it be harder to get up if the person is actually assaulting you with the glass?

The bottom line is that this was specifically removed from slips because of how abusable and cheap it was.

**Comment by Exxion** [comment]
Realism is secondary to gameplay anyway

**Comment by Killette2** [comment]
But gameplay is second to muh immursions
*breathes in
*breathes out
