### ISSUE TITLE
Plasma contaminates through vox pressure suits

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9914]
(WEB REPORT BY: pseudonym REMOTE: 172.93.109.202:7777)
Contaminated gloves, jumpsuit and boots, but NOT THE PRESSURE SUIT

**Comment by ComicIronic** [comment]
Suits don't contaminate, it should be noted. This is really a feature request to add plasma sealing to the vox suits, which I'm not fond of.

**Comment by gbasood** [comment]
@ComicIronic Except that it's currently intended for suits to protect items that they cover, and I'm told that none of them do

So this isn't even about pressure suits anymore, it's a bug report on suits not preventing contam of shit they cover.

**Comment by PJB3005** [comment]
Dupe, sadly.

**Comment by ComicIronic** [comment]
@gbasood Well I don't know who told you that, because they are full of shit.

From my testing, all Vox suits prevent plasma contamination.

**Comment by Imagebard** [comment]
>This is really a feature request to add plasma sealing to the vox suits, which I'm not fond of.

Okay so Vox suits don't prevent contamination

>From my testing, all Vox suits prevent plasma contamination.

Wait a minute am I misunderstanding this?

**Comment by Probe1** [comment]
1.  Hardsuits need to get contaminated but still poison the wearer unless it has `[plasmaguard]`
2.  People a few months ago wanted all hardsuits (and vox engineering suits) to have plasma guard.  I still strongly disagree and if you want to rebalance something you have to make up for it, which people had no ideas for.

**Comment by Intigracy** [comment]
Hardsuits don't get contaminated because you can't washing machine hardsuits to remove it.

**Comment by Probe1** [comment]
you're supposed to use the SSUs..

**Comment by Imagebard** [comment]
@Probe1
Are you some sort of plasma flooder?

**Comment by Probe1** [comment]
butt seriously, the game has to be balanced and thats part of it.  you can't take away a downside/remove a buff from engi and atmos hardsuits then do nothing else.  its silly.

**Comment by Imagebard** [comment]
_Ah yes, plasma is so perfectly balanced that any nerf would require a buff to compensate_

**Comment by Probe1** [comment]
Plasma _floods_ are badly balanced but they were never really intended to be.  They are an example of asymmetrical balance.  The entire station being flooded with plasma is a worst case doomsday scenario that seldom happens.  It's powerful, but so are the tools to prevent it and one of the prime goals for an atmospheric technician is to keep an eye on the plasma miner.  Stopping them is difficult but possible.  Preventing them is much easier.

[Plasma _guard_ ] is a different discussion and one about whether the regular use and operation in plasma should be a luxury afforded to only the special hardsuits specifically designed to be used in plasma, or all hardsuits.

And this is not a case of asymmetrical balance.  They were deliberately not given it, just as the Vox were deliberately given inferior suits after complaining they had no suits at all, and now we are here.

I won't be thrilled if vox atmos tech hardsuits get plasma guard.  I think it's silly.  But that's life.  But Vox engineering suits in general are right out and you can go fish unless you plan to rebalance the whole thing and give plasma working conditions new hazards (Which frankly they don't need and it's fine as is).

**Comment by Imagebard** [comment]
I wanted to throw up a rant but first I must ask, Plasma Guard is the modifier that makes clothing immune to plasma contamination, right?

**Comment by Probe1** [comment]
Correct.

**Comment by west3436** [comment]
Plasma seals are now suit upgrades which can be applied to hardsuits
