### ISSUE TITLE
Bomberman suits should come with oxygen tanks / allow oxygen tanks in suit storage / bombermen shouldn't need air

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9922]
For obvious raisins

**Comment by AutismSpider** [comment]
Right now suit is just for looks and the power to drop bombs/get power ups comes form the bomb dispenser they spawn with.

Need turn them into mobs like golems with the power to drop bombs etc

**Comment by Imagebard** [comment]
> turn them into a mob/race type like golems with the power to drop bombs etc 

While leaving the suit in the code for clown shenanigans*

**Comment by Probe1** [comment]
Tag is as a bug fam.  It didn't used to happen wasn't intended to happen and shouldn't be happening

**Comment by 9600bauds** [comment]
Didn't know

**Comment by Imagebard** [comment]
Oh yeah actually, isn't this a dupe of another issue?

**Comment by 9600bauds** [comment]
It could be, I deleted the bugreporting template because I'm too cool 8)

**Comment by Hoshi-chan** [comment]
Just do what was done with golems: make them their own race that has the suit built-in, and then remove their need to breathe.

Also, their primal form should be a bomb.
