### ISSUE TITLE
Logs of canisters being opened are borked, displays "/list" instead of a list of the gases in the canister

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9925]
[19:10:54]ADMIN: THE UN(lamberts) opened a canister that contains /list at 210, 274, 1
[19:13:18]ADMIN: THE UN(lamberts) opened a canister that contains /list at 187, 262, 1

**Comment by Intigracy** [comment]
I think it only happens when the list only has one gas, not sure though.

I saw one that was oxygen + plasma that correctly outputted.

**Comment by Intigracy** [comment]
This seems to be working fine now.

**Comment by clusterfack** [comment]
Check it with n2o

**Comment by Intigracy** [comment]
![2016-06-03_18-04-45](https://cloud.githubusercontent.com/assets/4043940/15796628/bde19996-29b5-11e6-923c-75d346eb50fe.png)
![2016-06-03_18-05-12](https://cloud.githubusercontent.com/assets/4043940/15796629/bf52ad7e-29b5-11e6-9552-00feab6e970d.png)

**Comment by Intigracy** [comment]
What needs doing though is that the investigate log doesn't reflect this at the moment, it just says you opened a canister.

**Comment by clusterfack** [comment]
Okay final question before I close it, what happens with no gases

**Comment by Intigracy** [comment]
Nothing.

**Comment by 9600bauds** [comment]
I think this is just for the logs, but works fine in-game

**Comment by d3athrow** [comment]
This was fixed with dfa3c9568ae965291d6824fd64143ef6adadbaff
