### ISSUE TITLE
Does it take too long for facehugger embryos to incubate (burst?)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9927]
Feels like it takes as good 5-10 mins for a person to burst into a xeno

**Comment by Probe1** [comment]
It does take a long time but xenos pretty powerful and just one larva can restart the entire infestation.

If any adjustment is made it should be around the neighborhood of 10 to 20% faster.  Nothing major.  

Xeno is in a really good spot right now not perfect but really good.  We're getting into the territory where fluctuations in player count and round context play just as big of a part as xeno balance itself.

**Comment by gbasood** [comment]
I assume that most people (myself included) still feel that facehuggers are too good, and we should foucs on making the aliens themselves better, though?
Maybe the opinion on that has changed, it's been awhile since I buffed them

**Comment by Probe1** [comment]
Afaik facehuggers are blocked by helmets (at least hardsuit helmets) again so my issue is gone.  If they still make you sleep then that's pretty shitty.

**Comment by mrpain666** [comment]
I'll keep a closer eye on them. I feel like most of the time, if the host survives his encounter and makes it to surgery, he usually seems to get it out in time.

**Comment by gbasood** [comment]
@Probe1 They have a very high RNG chance to be blocked by hardsuit helmets but all other helmets are removed in one facehugger hit.
It takes another facehugger hit to remove the mask and facehug now, but that should be done in one go AFAIK

**Comment by clusterfack** [comment]
Takes way too long, a shuttle can arrive in the time it takes an egg to burst and a larva to be ready to upgrade. Reduce it to 3-4 minutes Max and I'll approve it.

**Comment by Blithering** [comment]
I was a miner that got facehugged recently, the larvae seemed to burst in around a minute, definitely not enough time to get back to the station proper for surgery.

**Comment by clusterfack** [comment]
Oh I thought we were talking about the time it takes for an egg to mature

**Comment by gbasood** [comment]
Maybe a percent chance to stage up is a shit mechanic and it should be time based with some time variation instead?

**Comment by Hoshi-chan** [comment]
Removing an embryo should be something that requires haste, maybe even ghetto surgery if that means removing it sooner, even at risk to the patient's life.

That being said, "seems like 5-10 minutes" is vague. You should extensively test and measure the amount of time that it takes before changing this, because making it too fast could completely ruin the balance of xenos; they're already incredibly powerful since someone removed their weakness to lasers.

**Comment by gbasood** [comment]
>since someone removed their weakness to lasers
What? A full charge of a laser can kill any hunter, and two outright kills a queen.
