### ISSUE TITLE
Ghosts can still use Telesci

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9928]
(WEB REPORT BY: zealotron REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 31337dfeef903060bb9d3b659239458d2db46649 
> 
> General description of the issue
> Ghosts can use the Telesci computer,
> observers possibly can't? I'm unsure.
> 
> What you expected to happen
> To not be able to teleport all the stations valuable as a ghost
> 
> What actually happened
> Riches for me and my dead bitches
> 
> Steps to reproduce if possible
> Suicide as a normal player and try to use telescience.

**Comment by 9600bauds** [comment]
dëup of #8393
