### ISSUE TITLE
Appearance bans do not randomize races. They should

### ISSUE THREAD

**Issue by mrpain666** [d3athrow/vgstation13#9932]
Without mentioning any specific cases, I am requesting that appearance bans randomize races instead of just names and whatever. Someone else has tested it and informed the admin team that it does not randomize the race. Or just force default it to human. Whatever

Also, while you're in there, add a temporary variable if you could. Right now it's just perma or nothing, last I checked.

I believe this feature is outdated and needs to be brought in line now that we have many playable races.

**Comment by PJB3005** [comment]
I don't think this is a good idea.

The thing is that appearance doesn't have gameplay impact, species do.

You might be a shitter with apprarances but you don't deserve getting your round ruined by being Diona without anybody in chemistry, due to RNG.

**Comment by 9600bauds** [comment]
Just make them human master race :^)

**Comment by icantthinkofanameritenow** [comment]
Wait, appearance bans are a thing?

**Comment by mrpain666** [comment]
@PJB3005 make them forced human then

**Comment by gbasood** [comment]
Yeah appearance bans are a thing.
I've mostly seen them used on people who decide EVERY ROUND to name themselves 'Meme King Supreme' or something else similarly stupid

Also, if this gets implemented I can forsee:
>appearance banned vox raider spawns as a human
>everyone freaks the fuck out
>he still somehow has vox language
>PLEASE DONT SHOOT
>lock him a locker immediately and weld him in

Probably wont actually happen but I can dream

**Comment by MercuryDoll** [comment]
Don't be racist against trans-vox you shitlord!

**Comment by Exxion** [comment]
Appearance bans and race bans should be separate things

**Comment by mrpain666** [comment]
Then if that's the case give us the ability to jobban people from vox raiders if you feel that's going to be an issue.

The systems regarding bans just feels really outdated now.

**Comment by FudgePucker** [comment]
I mean human is enough.
Although I don't know how apperince bans work, it might be silly if there's a chance to have a albino woman with a pink afro as a random body setting showing up.
