### ISSUE TITLE
Alien nests need to be remade

### ISSUE THREAD

**Issue by CptWad** [d3athrow/vgstation13#9934]
#### Description of issue
I have several issues with nests
the resist time does not matter if you push someone over or if they are let out of the nest
in however long the timer is, the will resist out of that specific nest
meaning if they spam click A LOT like EVERYONE DOES they will 100% of the time get out reliably
even if a xeno stands over them and spam pushes down
even if they get out you can put them back on the nest, however if they spam click they INSTANTLY GET OFF THE NEST

#### Difference between expected and actual behavior
To operate like bucklecuffing 

#### Steps to reproduce 
Using two people, or yourself playing two people, spawn in the xeno and human for roleplay
put human in nest
have human spamclick the nest twenty times
push the human over
take the human off the nest drag him around for 10 tiles
put him back on the nest
wait
watch as the human magically resists off the nest
click drag human back to nest
previously qued resists now register and he instantly resists AGAIN

#### Length of time in which bug has been known to occur

This is acutally before sood beefed up xenos this has happened I think. Since I recall shit like this happening a lot years ago

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

**Comment by CptWad** [comment]
oh yeah you can also kick xenos from nests and can kill xeno larva in a few hits with kicks so thats hilarous but broken

**Comment by gbasood** [comment]
Players who have been facehugged and buckled into a nest SPECIFICALLY should have a harder time getting out than a player who has been buckled into a nest just after walking over it (nests under doorways are a real strategy)

**Comment by clusterfack** [comment]
Pinging @deity_link?

**Comment by CptWad** [comment]
Nah I dont think its his fault either, this has been around a while but he was the last to touch it so id trust him with fixing it since he knows most about it

**Comment by gbasood** [comment]
Deity seems to have a good head when it comes to making things like this fun anyway

**Comment by DeityLink** [comment]
>even if a xeno stands over them and spam pushes down
>if they spam click they INSTANTLY GET OFF THE NEST

This is an issue. I don't think Xenos should be able to reset the timer by hitting them, However any "timer" should stop as soon as you get out of the nest. I can see a few ways to have it work out. Consider this bug fixed soon.

Oh by the way, you don't have to use the template for issues. The description was descriptive enough.

**Comment by CptWad** [comment]
I usually don't use the template unless I don't have anything to do
I did not have anything to do
