### ISSUE TITLE
Spider queen pathing is incredibly broken

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9937]
They don't seem to be reaching their targeted light, especially if that light is around a corner or if there is a wall between them and the light.

Why are they targeting lights they can't see anyway?

**Comment by Shadowmech88** [comment]
> Why are they targeting lights they can't see anyway?

Because of #9057.

**Comment by Probe1** [comment]
There are many issues on this, some of which have "its a feature" tagged on.  

Like how they will repeatedly web the same tile 10+ times.

**Comment by gbasood** [comment]
@Probe1 That specific part is not a feature. There should never be more than one web per tile.
Selecting targets through walls was an _okayish_ feature but it's seeming to do more harm than good now and should be fixed.

**Comment by jknpj** [comment]
Fixed by N3X
