### ISSUE TITLE
Doubletraitoring still happening on autotraitor (apparently)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9939]
@Skullyton says so anyway

**Comment by Probe1** [comment]
It does.  I asked someone to report it last night but I guess they did not.

Happened during a traitor-ling round.

**Comment by gbasood** [comment]
@Probe1 In the future if this happens to someone and they don't report it, check the debug logs for their key and you might find out why they're being selected twice.

**Comment by Probe1** [comment]
which debug logs?

**Comment by gbasood** [comment]
~~They're in the runtime logs but they're prefaced by DEBUG:~~
I don't knoooow
ask dylan

**Comment by Killette2** [comment]
You probably asked me to report it, but I was too busy making spiritbreaker bananas and yelling in ahelp.

**Comment by clusterfack** [comment]
I believe this has been fixed I haven't seen it in a long time, and if so it's due another issue.

**Comment by gbasood** [comment]
I think I fixed that actually so yeah
