### ISSUE TITLE
Autotraitor is traitoring people who shouldn't be traitors and more!

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9940]
Silicons who are traitored do not seem to get a law 0! MoMMIs included!
Traitor borers!
TRAITOR MICE!
And sometimes people who ARE ALREADY TRAITORS are being re-sent objectives after they've been borged, making them think they should be traitor AIs!

**Comment by Shadowmech88** [comment]
Only true MLG players can complete their objectives as a mouse.

**Comment by Allspice** [comment]
On a similar note, sometimes one or more of the borgs slaved to a traitor AI do not have the law 0, while the rest get it.

**Comment by AutismSpider** [comment]
mommis have a flag to stop round start and auto traitor stuff

**Comment by Shadowmech88** [comment]
Wasn't traitoring borers fixed recently by a change to mind code?

**Comment by clusterfack** [comment]
Yep
