### ISSUE TITLE
Only starting cultists can see eachother's HUD markers

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9952]
What it says on the tin.

Be a cultist, convert someone else into a cultist, and neither of you can see that the other is in the cult.

**Comment by clusterfack** [comment]
This still happening?

**Comment by ComicIronic** [comment]
I don't know, did they update Byond?

**Comment by clusterfack** [comment]
Yeah I'm not sure if its really a code problem

**Comment by ghost** [comment]
Not reproducible
