### ISSUE TITLE
Gun sprites no longer reliably indicate charge level when EMP'd

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9954]
After being EMP'd, they seem to indicate that they have a charge still (an orange or partial red/blue indicator), and yet they do not.

**Comment by Shadowmech88** [comment]
Can confirm.

**Comment by clusterfack** [comment]
Just needs an update_icon in emp_act most likely.

**Comment by ComicIronic** [comment]
Tempted to not fix this just for the EMP actually breaking something.

**Comment by Hoshi-chan** [comment]
Yeah, that's what I thought it might be too. Like, "Oh, well the EMP fucked up the indicator."

In any case, it should be observable somehow, like examining the gun to see, "The charge level indicator seems broken."
