### ISSUE TITLE
When hit with a staff of change as a wizard, you lose all of your spells

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9955]
It's understandable if you're being turned into a borg or a xenomorph, but going from humanoid to humanoid, this just seems silly.

**Comment by Shadowmech88** [comment]
Even if they're turned into a borg or xenomorph, I think they should still keep their spells, just be unable to use them.
After all, they could get turned back into a human at some point.

**Comment by 9600bauds** [comment]
w i z a r d
x e n o s

**Comment by Konater** [comment]
Wizards should keep their spells after cloning too, it's all tied to their mind why would they lose it
Let me them their robeless spells if they get changed, then we can get wizards that purge an AI, turn themselves into a cyborg then fireball shit

**Comment by MercuryDoll** [comment]
SoC'ing a wizard also "kills" them, thus ending the round if it was a solo-wiz.
I'm for wizards keeping their spells if they are transformed into a humanoid/xeno, when they are borged their spells should be disabled though.

**Comment by gbasood** [comment]
Okay fine, but should being transformed to another type of human really de-wiz you?

**Comment by clusterfack** [comment]
We should attach some spells to the body and some to the mind, and when we transfer minds transfer those spells

**Comment by gbasood** [comment]
Yeah that's the issue suggested in the referenced issue that got immediately closed the first time
Humans are hte only people who should have spells, so once that's implemented both of these issues should be closed

**Comment by ComicIronic** [comment]
Humans are not the only mobs with spells and that's a bad assumption.

**Comment by gbasood** [comment]
_wizard_ spells

**Comment by Intigracy** [comment]
Well, cloning transfers your spells.
