### ISSUE TITLE
can_stand bug (the one where you punch yourself to fix it)

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9959]
[09:06:24] Kammerjunk/(Ginger Beach) (JMP): I have no idea why it happens, but it can make Asimov medborgs a bit of a bother post-cloning
[09:06:25] Pseudonym/(Nestachack) (JMP): can_stand = (canstand_l && canstand_r)
[09:06:27] Pseudonym/(Nestachack) (JMP): seems like 
[09:06:38] Pseudonym/(Nestachack) (JMP): legcode might be poop
[09:06:50] Diethyl/(Adam Savato) (JMP): I has been happening for a long while now.
[09:06:55] Diethyl/(Adam Savato) (JMP): it*
[09:07:10] Pseudonym/(Nestachack) (JMP): canstand_r and canstand_l are set based on if r/l_leg/foot is_usable returns true
[09:07:25] Pseudonym/(Nestachack) (JMP): it's updated on handle_organs

under the `handle_organs` proc in modules\organs\organ.dm:

``` DM
    var/canstand_l = 1
    var/canstand_r = 1
    var/legispeg_l = 0
    var/legispeg_r = 0
    var/hasleg_l =   1 //Have left leg
    var/hasleg_r =   1 //Have right leg
    var/hasarm_l =   1 //Have left arm
    var/hasarm_r =   1 //Have right arm
    //var/datum/organ/external/E = organs_by_name["l_foot"]
    var/datum/organ/external/E
    E = organs_by_name["l_leg"]
    if(!E.is_usable()) //The leg is missing, that's going to throw a wrench into our plans
        canstand_l = 0
        hasleg_l = 0
    legispeg_l = E.is_peg() //Need to check this here for the feet

    E = organs_by_name["r_leg"]
    if(!E.is_usable())
        canstand_r = 0
        hasleg_r = 0
    legispeg_r = E.is_peg()

    //We can stand if we're on a peg leg, otherwise same logic.
    E = organs_by_name["l_foot"]
    if(!E.is_usable() && !legispeg_l)
        canstand_l = 0
    E = organs_by_name["r_foot"]
    if(!E.is_usable() && !legispeg_r)
        canstand_r = 0
    E = organs_by_name["l_arm"]
    if(!E.is_usable())
        hasarm_l = 0
    E = organs_by_name["r_arm"]
    if(!E.is_usable())
        hasarm_r = 0

    //Can stand if we have both of our legs (with leg and foot parts present, or an entire pegleg)
    //Has limbs to move around if at least one arm or leg is at least partially there
    can_stand = (canstand_l && canstand_r)
```

So IN THEORY either handle_organs calls aren't happening when they should
OR
is_usable is fucky

**Comment by 9600bauds** [comment]
Some people still swear the cause of this is leg/foot deformities from clone damage which is a plausible theory

**Comment by clusterfack** [comment]
What are you literally talking about in this

**Comment by 9600bauds** [comment]
In human_damage.dm, /mob/living/carbon/human/adjustCloneLoss(var/amount)

``` DM
                var/datum/organ/external/O = pick(candidates)
                O.mutate()
                to_chat(src, "<span class = 'notice'>Something is not right with your [O.display_name]...</span>")
```

The O.mutate is 

``` DM
/datum/organ/external/proc/mutate()
    src.status |= ORGAN_MUTATED
    owner.update_body()
```

The leading theory is that ORGAN_MUTATED has shitcode somewhere which is the cause of this when it happens to a leg/foot

**Comment by clusterfack** [comment]
Guys, please

**Comment by 9600bauds** [comment]
???
what

**Comment by clusterfack** [comment]
Are we claiming this bug still exists? Has someone succeeded in reproducing it again?

**Comment by kol1th** [comment]
Well it happened during a round earlier today, some people had their legs blown off, I attached the leg, and tried to shake them up, but it did nothing. Punching them made them stand. It also occasionally still happens after cloning.

**Comment by Hoshi-chan** [comment]
It happens all the fucking time. Like, every round where people are cloned.

Pull a clone out of cryo, put them in the mancrowave, shake or prod them repeatedly, and the only way that they can get up is if someone punches them, or they punch themselves. It's so frequent that most mediborgs, myself included, simply look the other way while medbay staff punch them, or ask them to punch themselves, because justifying a bug workaround as "harm" seems shitty.

**Comment by Probe1** [comment]
@clusterfack you twit it has existed continuously for six months.

**Comment by gbasood** [comment]
@clusterfack It happened LITERALLY YESTERDAY
I WAS THERE

Anyways the only place where can_stand is modified at runtime is where I codequoted.
So it's all linked back to this block somehow

**Comment by FudgePucker** [comment]
It might have to do with the foot and leg damage not getting refreshed after cyro or surgery, so ()can_stand thinks you are a cripple at full health, but after you get punched it goes 'player took damage, let's check to see if they can still walk', it sees now that you are at 99% health and can stand up.

**Comment by clusterfack** [comment]
@Probe1 

Fuck off probe if at any point in those 6 months you fags have viewed variables to see what kind of shit is going on we would have had this fixed ages ago.

**Comment by Probe1** [comment]
@clusterfack you have to tell us what to check.  You assume we 1.  know checking VV will help and 2.  know what variable will control it.  Make a memo in game with details on what to do and someone will check it out.

**Comment by clusterfack** [comment]
@Probe1 If I knew what to look for, I would have fixed it already. As it stands I can't even reproduce it, ever, basically.

He'll even tell me which variables are changing before/after you are punched once

**Comment by 9600bauds** [comment]
I think I was able to reproduce this by giving myself 99 clone damage and having my legs or feet deform from that damage (takes a few tries, which bodypart deforms is random) then jumping into cryo
We talked about this in IRC I think 
Might try again tomorrow

**Comment by gbasood** [comment]
@9600bauds 

> So IN THEORY either handle_organs calls aren't happening when they should
> OR
> is_usable is fucky

**Comment by 9600bauds** [comment]
Oh yeah I never tested this again, let me try

**Comment by 9600bauds** [comment]
Yep, it works exactly like this:
1- Give yourself like 60 clone damage until one of your feet or legs becomes deformed
2- Punch yourself (I HAVE NO FUCKING IDEA WHAT THE SIGNIFICANCE OF PUNCHING YOURSELF IS)
3- Now you can't stand up anymore
4- Heal the clone damage via cryo, rezadone untested
5- You still cannot stand anymore until you punch yourself

I'm testing what gives you the ability to stand back up. Rejuvenate doesn't, the Mancrowave doesn't, sleeper wakeup doesn't, coffee doesn't.

So far the only thing that worked was brute damage, be it from punching or from the traditional Grey wrench treatment

**Comment by clusterfack** [comment]
Remove this
```
			if((knockout >= M.species.max_hurt_damage) && prob(50))
				visible_message("<span class='danger'>[M] has weakened [src]!</span>")
				apply_effect(2, WEAKEN, armor_block)
```
and see if it still occurs

**Comment by 9600bauds** [comment]
I now know that it's any brute damage that fucks or fixes you, not specifically punching
I don't think that change would change anything but whatever not like my time is worth money

**Comment by clusterfack** [comment]
Then its probably a result of handle organs not reaching some area due to not thinking it needs to process a limb, and the brute damage forces it to process

**Comment by 9600bauds** [comment]
For some fucked up reason, rezadone does work for curing your clone damage and making your limb update properly

**Comment by clusterfack** [comment]
```
	var/damage_this_tick = getBruteLoss() + getFireLoss() + getToxLoss()
	if(damage_this_tick > last_dam)
		force_process = 1
```

From handle organ code

**Comment by 9600bauds** [comment]
That's weird because I did try shooting myself up with thermite and toxin and even cyanide, and nothing except brute damage would work

**Comment by 9600bauds** [comment]
also funfact, thermite causes burn damage ;^)

**Comment by Shadowmech88** [comment]
> injecting a mixture of powdered metals causes burn damage

I demand to know who's responsible.

**Comment by 9600bauds** [comment]
Oh wait, I see what happened now, that's LIMB damage. Toxin and shit is direct damage for the whole mob
