### ISSUE TITLE
Chisel size

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9961]
(WEB REPORT BY: pwirby REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Take a chisel, examine it/ try to put it in your pocket/box.
> 
> General description of the issue
> The chisel is a normal sized item but it's IRL more a pocket one. Also, it has no use other than engrave so making it pocket sized make it much useful.
> 
> What you expected to happen

To be pocket sized.

> What actually happened

Is normal sized.

> Steps to reproduce if possible

Take a chisel, examine it/ try to put it in your pocket/box.

**Comment by Killette2** [comment]
Same wish ashtrays. THEY'RE TOO FUCKING HUGE NORMAL SIZED ASHTRAYS WHEN IS MY ISSUE BEING ADDRESSED.

**Comment by ComicIronic** [comment]
Stop stealing ashtrays you klepto.

**Comment by Shadowmech88** [comment]
@Killette2 
You could do it yourself, you know.
Changing the size of an item is _literally_ just changing a single number.

**Comment by Killette2** [comment]
@Shadowmech88 
Tell that to pwirby then.

**Comment by Shadowmech88** [comment]
@Killette2 
The same goes for him of course, but I was talking specifically about your ashtray size problem.

**Comment by Brolaire** [comment]
Can be closed?

**Comment by PJB3005** [comment]
Uh, that's not merged yet...

**Comment by Brolaire** [comment]
Oh sorry!
