### ISSUE TITLE
Bring back 5x Summon Guns during Wizard

### ISSUE THREAD

**Issue by Hoshi-chan** [d3athrow/vgstation13#9962]
Either allow it to be cast multiple times, or add a new variant called "Greater Summon Guns" which uses up all of your spell slots for a much greater effect, such as pulling from a pool of consistently more powerful guns, spawning more guns per-person than regular Summon Guns, having a higher chance of creating survivors, or perhaps creating a more antagonistic type of survivor whose goal is to actively seek out and kill others, rather than "survive".

Wizard was never balanced, and outside of disintegrate being removed (which was a great move), it feels like all sorts of changes have been made over time to "balance" it at the cost of it being any fun to play.

**Comment by ComicIronic** [comment]
Wizard needs more spells which are both fun and effective

**Comment by Hoshi-chan** [comment]
Just look in a D&D player's handbook, there are so many good ideas, it's unbelievable that we don't have some of them. Cone of cold and ray of frost come to mind.

Personally, I think it'd be neat if all wizards had access to cantrips by default, regardless of their spell choices or robed/unrobed status. Simple things, like create food and drink, light, mending (repair damaged floor tiles, walls, glass), message (magic telepathy), ghost sound (like a sound synth that you can direct where you click), etc.

**Comment by Killette2** [comment]
More elemental magic other than useless fireball when?

**Comment by AutismSpider** [comment]
Fire ball needs massive rework

we have bits of the goon code right?

copy some of the wiz spells they have like ice beam and summon golem/meteor

**Comment by Killette2** [comment]
@AutismSpider 

https://github.com/d3athrow/vgstation13/issues/9559

I swear you faggots reference my suggestions on purpose, then abandon them after slight discussion.

**Comment by Kitfox88** [comment]
@Killette2 
BABY'S DAY OUT MODE WHEN

**Comment by Imagebard** [comment]
@Killette2 We're _trying_ to ignore you.

**Comment by Killette2** [comment]
B-B-But I never even posted the babies day out post

**Comment by TheFriggenSawbones** [comment]
add STICKS to SNAKES

**Comment by Killette2** [comment]
Take DCSS
add any spell in there to here

**Comment by AutismSpider** [comment]
if this was DCSS all the good spells would be taken out 

rip turning dead body's into deadly pots to toss at shit

**Comment by Hoshi-chan** [comment]
@TheFriggenSawbones They're wizards, not clerics, you doof.

**Comment by Killette2** [comment]
I don't remember any bodys to pots spell in recent DCSS

**Comment by AutismSpider** [comment]
@Killette2 it was call Evaporate+ Fulsome Distillation both were removed in 0.12

Fulsome Distillation extracts essences from a corpse into a potion. The potions produced are mostly used as ammunition for Evaporate. The potions produced will be identified if necessary. 

Evaporate spell allows the caster to throw a magically heated potion that explodes into a cloud of up to 3x3 squares. The exact effect produced depends entirely on the kind of potion used

**Comment by Killette2** [comment]
Oh you did mean potions, I thought pots meant clay pots because surely you wouldn't want to waste potions.

**Comment by ComicIronic** [comment]
If you think about it, we're like a reverse DCSS. We never remove features, and the game gets less and less stable as we update.

**Comment by Imagebard** [comment]
>We never remove features

You know I think I missed the party where we removed feature removal.
Is it because we want to be complex or something

**Comment by AutismSpider** [comment]
@ComicIronic ninja code like to have word with you

**Comment by Shadowmech88** [comment]
We normally scrutinize all additions to the code such that anything that gets in is well-liked enough to not be removed later.

**Comment by Killette2** [comment]
I say we rotate out stun batons, there's too many weapons to memorize and rotating out items will keep the game healthy and balanced.

**Comment by Kurfursten** [comment]
this happened
