### ISSUE TITLE
Windoor not giving back Airlock Electronics

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9965]
(WEB REPORT BY: pwirby REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> Windoor not giving back Airlock Electronics.
> 
> General description of the issue
> The windoors, when breaked, only give back two piece of cable and a broken glass.
> 
> What you expected to happen

Give back an airlock with the cable and glass (also maybe a metal rod since it's made with renforced glass)

> What actually happened

Give back only two piece of cable and one glass shard.

> Steps to reproduce if possible

Make a window/found one > destroy it > look at the nonexistent airlock electronics

**Comment by Exxion** [comment]
#7657
@clusterfack

**Comment by gbasood** [comment]
may or may not be fixed

**Comment by PJB3005** [comment]
I can't recall this being fixed.

**Comment by DamianX** [comment]
This is not the case anymore
CLOSE IT
