### ISSUE TITLE
[Deff] No O2 canister in EVA, but there still is a N2 canister somehow

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9967]
I would think that no O2 canister is calculated shittiness if not for the N2 canister right there
Gas the Vox, or don't gas anyone

**Comment by Probe1** [comment]
EVA in general is one of the many things on deff thats shit.

**Comment by Intigracy** [comment]
Deff is the map with only 2 SSU's in engineering.

Atmos has 3.

Fuck Deff.
