### ISSUE TITLE
Stripping menu is hot garbage

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9969]
Problems it has:
- #7760
- #8222
- If you try to put an item on someone, it doesn't check for what slot it should go to. You can try to accidentally put a labcoat on someone's jumpsuit slot, it will still display the text, give the progress bar, etc. but then it will just do nothing.
- It doesn't update after stripping someone of something, you need to refresh the window manually or wait a while until it refreshes itself
- It likes to re-open itself after you close it, for some reason
- Could use better formatting, what about a paperdoll like your equip menu?

**Comment by Probe1** [comment]
> it likes to re-open itself

When it completes an action, like stripping, it'll send a signal to refresh.  which re opens.
