### ISSUE TITLE
Admins cannot handle plastique (c4) after it has been attached in any way.

### ISSUE THREAD

**Issue by gbasood** [d3athrow/vgstation13#9971]
Once C4 spawned via uplink items is attached to something, it adds an overlay to that thing and then nullspaces itself.
You can SDQL SELECT for plastique but there is no way to tell which plastique is which
Not sure what the best solution to this is

**Comment by Shadowmech88** [comment]
Wouldn't it be best to add the C4 to the contents of whatever it's attached to?

**Comment by gbasood** [comment]
Problem being if we wanted to keep it an unremovable explosive you'd need to handle it differently for things like lockers.

We _could_ make it use atom locking and set mouse opacity to 0 on attachment for roughly the same effect it has now though

**Comment by PJB3005** [comment]
The best solution is atom locking.

**Comment by west3436** [comment]
No interest in implementing this since issue creation
