### ISSUE TITLE
Tool belts should be able to dump their contents into other toolbelts.

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9974]
cause fuck the advanced toolbelt and having to slowly click over every single item.

**Comment by Shadowmech88** [comment]
I'd like it if toolbelts and toolboxes had the same kind of pickup method as plastic bags do, so you could fill a toolbelt or toolbox from a YouTool much faster.

**Comment by CptWad** [comment]
holy jesus yes
I would not mind if it was a progress bar thingy too, one click and 
"You begin to organise everything into the [toolbox/belt]"
...
"You successfully put all you can into the [src]"
"The [src] Cannot hold the Backpack"

**Comment by Killette2** [comment]
I can see this as a quality thing, but as someone who's actually used toolbelts this triggers me to no end.

**Comment by Exxion** [comment]
@Shadowmech88 
If memory serves, all you have to change to get it to do that is one variable
