### ISSUE TITLE
Among the many other things fucked about the round end screen, it doesn't check your PDA wallet for $ when calculating the richest escapee

### ISSUE THREAD

**Issue by Probe1** [d3athrow/vgstation13#9978]
flibbleflapple

**Comment by ComicIronic** [comment]
Where the hell did you find a wallet?

**Comment by Probe1** [comment]
The PDA wallet.  It's a thing Deity added when he was going to rework the economy but disappeared instead.

Put cash into your PDA.  Wirelessly transfer cash to other players.  Eject cash from your PDA.  Pretty useful.

**Comment by MercuryDoll** [comment]
That feature is great, but sadly without much use since not enough things drop cash, or use cash.
![image](http://vignette3.wikia.nocookie.net/uncyclopedia/images/0/0d/Prints_money.gif/revision/latest?cb=20060721101458)

**Comment by JMWTurner** [comment]
Fixed by #11436
