### ISSUE TITLE
AR price nerf and submachine gun buff

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9983]
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
make submachine guns cost metal and glass
make AR cost metal glass and silver

**Comment by 9600bauds** [comment]
someone make a better sprite for the assault rifle while we're at it

**Comment by ComicIronic** [comment]
> make guns cheaper
> make a gun cost only metal and glass

How about no

**Comment by 9600bauds** [comment]
Comic I'm not sure in what year you were cryogenically frozen but ARs already are metal and glass

**Comment by Imagebard** [comment]
AR is supposed to be a reference to XCOM and also the weakest gun.
If you put silver on it it'll be pricier than the better XCOM guns. Nerf it instead.

**Comment by clusterfack** [comment]
Give it only a 45% chance to go where you shoot it.

**Comment by AutismSpider** [comment]
@clusterfack you mean 30%

**Comment by Probe1** [comment]
95% it'll still miss every time

**Comment by ComicIronic** [comment]
GOOOOOOOOOOOOOOOOOOOOOOOOOOOF

**Comment by Blithering** [comment]
@clusterfack  Please no, that's what ruined the star wars blasters. Still, assault rifles are really in need of some kind of rebalance.
