### ISSUE TITLE
[Box] Security disposals conveyor too erect

### ISSUE THREAD

**Issue by 9600bauds** [d3athrow/vgstation13#9984]
![dllhost_2016-05-08_20-30-44](https://cloud.githubusercontent.com/assets/6526157/15101045/d1ea5888-155b-11e6-995a-ee335461bd03.png)
Should be a corner in the corner

**Comment by Probe1** [comment]
i have never understood the point of that room

**Comment by ComicIronic** [comment]
So you can catch illegal trash.
It's mainly if someone flushes something that Sec can yell ":s STOP THE BELTS" and they can fish it out before it gets flushy flushed.

**Comment by Probe1** [comment]
I understand what wishful thinking went into that but it has never in all my time playing ever been of importance.

Its true purpose is to serve as an interesting little room and maybe once in a while someone will question it and someone will give a perfunctory answer about its function.  

But its true function is to just be a room that some mapper thought he was real clever making and never effects the outcome of anything.  Its like a  fleur-de-lis or a doodle on the edge of a paper.  It looks nice but has no real effect.

**Comment by 9600bauds** [comment]
I guess it's like
if you're searching or interrogating someone and the cuffs come off for whatever reason
and they disposals themselves
you could go there and bag 'em before they break the window

I don't know, I guess it COULD happen

**Comment by PJB3005** [comment]
They can just hide in the exit disposals bin, can't get them out.

**Comment by Konater** [comment]
Now that I think about it those windows are all on the wrong tiles, we have this problem on a lot of maps where trash will just hit the windows because they're on the same tile

**Comment by Probe1** [comment]
I've mostly fixed those instances by adding an additional conveyor under the disposal pieces which keeps everything moving if it happens to break down.
