### ISSUE TITLE
Remove virus dish shattering

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9986]
If you accidentally click a virus dish with ANYTHING in your hand, including a pen or piece of paper (unsure about hand labeler) it shatters. This is stupid, and makes many virologist consider suicide. Remove this feature, I don't want to have to be this careful around viruses.

**Comment by 9600bauds** [comment]
Holy hell I didn't know this existed and it sounds awful

**Comment by Exxion** [comment]
There should be _something_ that requires you to be careful, but that doesn't sound like what it should be

**Comment by Imagebard** [comment]
**DOUBLE STUPID MODE:** Breaking a virus dish releases the virus.

**Comment by Exxion** [comment]
As it should
That's probably why this feature is there
But it shouldn't be so easy to accidentally break it
Possible, so that there's a nonzero risk associated with virology
But not this easy

**Comment by SysadminJeroen** [comment]
1. Be traitor
2.  Obtain as many virus disks as possible.
3. Obtain hidden identity.
4. Chuck virus disks at random crewmembers.
5. Virologist's nightmare.

**Comment by Killette2** [comment]
Breaking the virus dish does release the virus, this is true. And it might not be a bad mechanic (just kidding).

BUT the fact anything breaks it is retarded. If you still want dishes to be breakable, make it so things that deal over 0 brute damage only can shatter it. That way paper, health analyzers, and other virus dishes don't smash each other.

**Comment by Exxion** [comment]
I quite like that solution, @Killette2

**Comment by Imagebard** [comment]
>But it shouldn't be so easy to accidentally break it

Which is _why_ it crosses over to "double stupid" mode.

**Comment by Probe1** [comment]
SS13 at its best and worst.  

Shattering viruses is COOL.  It can also be a pain in the ass if you fuck up.  But its coolness outweighs it.

**Comment by Killette2** [comment]
> Spend 30 minutes just trying to get the crates and access
> Spend 30 minutes finding the right syndromes
> Spend an hour radiating the virus to be stronger
> Break it, it doesn't even spread to you

It's not really cool, it's just a lame feature that pisses off that one dude in virology and makes them suicide succumb.

**Comment by clusterfack** [comment]
You have to handle virus dishes extremely carefully? What a concept.

**Comment by Probe1** [comment]
Don't get me wrong, I'm cool with something sane like pens not breaking them.  But one of the core concepts of SS13 is how dangerous working on a space station is.  You remove the danger, you get longer rounds, people exhaust the content then they get bored and quit.  

The game is oriented towards disasters happening.

**Comment by Killette2** [comment]
Except it's not, when you can throw around beakers, mail people unboxed pizzas, perform surgery on people who'm are awake, live in a swarm of bees and be fine, jump through space naked for a few seconds with some air then apply a few bandages later when you're back in a stabilized area, ride in the stations duct work like it's an amusement park, put metal in the microwave to make recipes, do I need to give more examples of things that are not careful at all which would be if the game were more realistic?

Realism does not make excuse for tedium and annoyances.

**Comment by Killette2** [comment]
The point is, more often than not it creates an annoyance more than a hazard. Maybe 1/10 times a broken dish will result in an outbreak, and even if the virologist gets sick they are likely to suicide because their hard working project just got destroyed in front of them before they could finish in quality or specifications.

**Comment by Probe1** [comment]
Some of those things are unintended behavior like surgery while awake.  It used to and should cause steps to fail most of the time.  However as you saw this morning, you were debrained while awake and repeatedly standing up mid-step without any complications.  That's a bug.

And bees?  Outside botany bees are a sure way to send half the crew to medbay for anti toxin.

I'm ok with making pens or having the attackby check for harm intent or something moderate but having shit break when you're not careful is a good idea.

**Comment by Exxion** [comment]
My vote is still for Killette's suggestion of making only items with nonzero force break the dishes

**Comment by Probe1** [comment]
ok

**Comment by clusterfack** [comment]
At the price of making throw_impact always shatter them if it doesn't already

**Comment by Killette2** [comment]
You are also over estimating bees by a lot, even when used by an antag you have to remember bees despawn overtime, it's the hive that generates bees.
