### ISSUE TITLE
Duplicate bump() call removal ruined the singularity

### ISSUE THREAD

**Issue by Intigracy** [d3athrow/vgstation13#9987]
#### Description of issue

Before, the singularity's time and upkeep for energy was working based off of the duplicate bump() being there
Now it's 2x as slow, and leaving the PA at 0 will now cause the singularity to die over time instead of keeping it at roughly the same energy with slight increase over time.
#### Difference between expected and actual behavior

Expected singularity to remain the same
It changed
#### Steps to reproduce

Use the singularity

**Comment by Exxion** [comment]
Alright hold on
The particles weren't getting deleted the first time they bumped the singularity?

You know what it doesn't matter
Just double how much energy they impart to the singularity
It's probably like a one-character fix

**Comment by Exxion** [comment]
OK it's actually a bunch of one-character fixes because the accelerated particles have many subtypes, but it's still easy
I guess I'll do it

**Comment by Intigracy** [comment]
PA particles don't delete except when they hit their max range.

Which is why you can have multiple fields in a row.
