### ISSUE TITLE
Can we add a Russian Revolver and ammo to the bar, roundstart?

### ISSUE THREAD

**Issue by TheFriggenSawbones** [d3athrow/vgstation13#9988]
I think it's a cool idea, it was fun as hell on Goon.

maybe fix it so you can't fire it at people, only yourself, unless it's like that already.

**Comment by Exxion** [comment]
There is one on Meta and maybe Taxi

**Comment by Kurfursten** [comment]
Taxi is deeaaaaad!

**Comment by Exxion** [comment]
It's only on Meta
Also, it comes loaded, but with no extra ammo

**Comment by TheFriggenSawbones** [comment]
we need to bring it, and ammo, to box

**Comment by Killette2** [comment]
You can fire at others with the revolver, but that's part of the fun for playing russian roulette with modified rules.
