### ISSUE TITLE
Botanist traitor item, Beez(insert good name here)

### ISSUE THREAD

**Issue by Killette2** [d3athrow/vgstation13#9993]
It will function similar to BeezEez, but have a different effect on the hive. When it's used on a hive, the queen/hive when spawning bees will always spawn hostile bees. The purpose of this suggestion is that antag bees suck, you can't make them attack people(other than yourself), they despawn, and the hive is what spawns new bees. Let's say you release some pissed off bees in medbay and they create a swarm, you'll be good in about 90 seconds and they'll despawn, bees move slow as fuck anyways.

Also buff bee speed, pissed bees move slower than beepsky on patrol mode.

**Comment by 9600bauds** [comment]
Also wearing a spacesuit makes you immune to bees

**Comment by Killette2** [comment]
Oh yeah that part sucks too, especially since you can increase bee stinger size they should be able to be huge enough to pierce shit. Also unsure if the weed bug with plants still exist over a year later.

**Comment by AutismSpider** [comment]
We have that pain suit and mask right?

We can use that for antag stuff for like 8 TC you get box that has the suit and mask etc and some Chems and a Bee Whistle 

Chem is use to turn you into walking bee hive the whistle call back the bees to you

Clicking on some on harm will fire bees at them (Bee bullet that does brute and toxin damage+ any chems the bees happen suck up form hydro like poly acid etc)

**Comment by Killette2** [comment]
Being a walking bee hive sounds strange. You have to consider, to make bees deadly you have to purposely toxify plants around the hive so the bees remove and collect the toxin, or shoot the hive with a floral somatoray on yield mode to increase the size of their stingers.

**Comment by AutismSpider** [comment]
you would power up  bees before using this stuff.

Hive part lets you suck up near by bees to use+ the whistle to call them

**Comment by Killette2** [comment]
So you're saying I somehow fuse with the hive to become bee man? That's more insane than my idea

But what if the bees could shield you from things like projectiles... protected in a swarm of your own creation.

**Comment by AutismSpider** [comment]
Could add to the whistle or as a power for eating the chems+having the suit on.

X number of bees in you to make a shield a sword etc

**Comment by 9600bauds** [comment]
Idea for wizard spell
bees
it spawns bees
the incantation is just BEEEEEEEEEEEEEEEES

**Comment by Brolaire** [comment]
its not insane killette, Kojima did it first

**Comment by Killette2** [comment]
SPOILERS

**Comment by ghost** [comment]
BeeSeez, makes bees follow you and attack others that you *point to

**Comment by ghost** [comment]
BeeKeez, Bees that follow you can be used to open doors

**Comment by Shadowmech88** [comment]
BeezKneez, their sting can blow people's legs off.

**Comment by Shadowmech88** [comment]
BeezSneez, bees that spread viruses.

**Comment by Killette2** [comment]
BeezBreeze, bees that can control ZAS to blow you over so they can get to you to sting you easier.

**Comment by Kitfox88** [comment]
HeeBeez, beez that are just too creepy

**Comment by ihadtoregisterforthis** [comment]
BeeEeeEeeZ!

**Comment by clusterfack** [comment]
We need to add BeezEeZZZ to put our bees to sleep

**Comment by FudgePucker** [comment]
New traitor item, African queen bee.
These bees are SUPER PISSED OFF ALL THE TIME, fly faster, live longer, and fucking hates everything

**Comment by 9600bauds** [comment]
I figured for big African female bees, you'd want BeeSazz

**Comment by Brolaire** [comment]
Did someone say.... BEE QUEENIE?!

**Comment by ghost** [comment]
BeezFreez, bees that inject you with frost oil till you die from hypothermia

**Comment by DeityLink** [comment]
Close this outdated issue. bees no longer despawn, and bees can come out of the hive angry without dying by keeping the toxicity between 33% and 50%. Furthermore you can now hit someone with the briefcase full of bees to have the bees swarm after them. Guarranted kill on a downed non-armored crewmember.
