### ISSUE TITLE
maps is not showing up on crew monitoring monitors

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9996]
(WEB REPORT BY: recounted REMOTE: 172.93.109.202:7777)

> Revision (Should be above if you're viewing this from ingame!)
> 
> General description of the issue
> The monitor does not show up the map of the station hasn't been working for a while...
> 
> What you expected to happen
> to see the station map with crew icons
> 
> What actually happened
> seeing the background space
> 
> Steps to reproduce if possible
> click on crew monitoring station
> switch to mini map 
> nothing shows up

**Comment by 9600bauds** [comment]
Sounds like caching issue

**Comment by Exxion** [comment]
Caching issue and a duplicate of like eight other issues

**Comment by 9600bauds** [comment]
leave it as a reminder ;)

**Comment by clusterfack** [comment]
>leave it as a reminder ;)

Stop this shit, this is why we have fucking infinite issues and a bunch of them that are already fixed are not closed

**Comment by 9600bauds** [comment]
It was a joke while I was looking up all the other issues mom

**Comment by clusterfack** [comment]
It's already happened too many times, TOO MANY
