### ISSUE TITLE
Gas mask transformed sprite

### ISSUE THREAD

**Issue by D3athrow-Issues** [d3athrow/vgstation13#9997]
(WEB REPORT BY: 1pirateguy REMOTE: 172.93.109.202:7777)

> Revision 8c289364197931ca26fbd54b8244ee1eb52a31b4 
> 
> General description of the issue
> I had the new flashlight sec helmet on and a gas mask, I put on a roman helmet by clicking it in-hand, and my gasmask changed to some broken sprite after
> 
> What you expected to happen
> My gasmask to not break and my helmet to switch just fine
> 
> What actually happened
> My gasmask item sprite is fucked
> 
> Steps to reproduce if possible
> Put on sec helmet w/ flashlight
> toggled it a bunch like an idiot
> put on regular gas mask
> put on roman helmet from hand
> switch back to sec helmet
> gas mask item sprite is different now

**Comment by 9600bauds** [comment]
Works fine for me

**Comment by Shadowmech88** [comment]
This has happened to me.

I was wearing a flashlight HoS hat and a gas mask. I used the "toggle mask" button to flip my mask up and back down, and my mask's sprite changed to what looked like a plastic bag with a gas mask drawn onto it. If I flipped it up again, its sprite became the "Honk???" broken sprite. Flipping it down made it back into the plastic bag-looking sprite.

I tried it with multiple individual gas masks and it happened with all of them, changing them permanently.

**Comment by Exxion** [comment]
Can you give more specific instructions? I just can't get it to happen at all.

**Comment by Shadowmech88** [comment]
Put on gas mask.
Use the "toggle mask" UI button.
Use the "toggle mask" UI button again.

I've only done it in a single round so far, which is why I held off on reporting it myself. I'll try it again the next time I'm on.

**Comment by Exxion** [comment]
I mean did you do anything other than that beforehand that might have affected it
Because I couldn't get anything weird to happen with any combination of light sec hat and mask switching method

**Comment by Shadowmech88** [comment]
Not that I can think of.

**Comment by Shadowmech88** [comment]
Reproduced it last round. I got a brand-new gas mask from Engineering, took off everything I was wearing, and put the gas mask on.
I used the "toggle mask" UI button twice, and my mask turned into this:
![gasmask](https://cloud.githubusercontent.com/assets/3991927/15142208/a9ba019c-1669-11e6-9a54-8f61e6f3a10f.PNG)
Nothing I did would change it back.

**Comment by Exxion** [comment]
So it's only been done on the live server, not local?

**Comment by 9600bauds** [comment]
Can't get it to work on a listen serb, weird

**Comment by Exxion** [comment]
S E C R E T
R E P O

**Comment by Intigracy** [comment]
oops, my bad

**Comment by Exxion** [comment]
But what was changing their `icon_state` to something else so that broke?
