### ISSUE TITLE
Meteor Storm no longer indicates beginning or end

### ISSUE THREAD

**Issue by Kurfursten** [d3athrow/vgstation13#9998]
So Meteor Storms are generally just to give bored engineers something to do. But now they only appear on the Bhangometer (a machine engineers don't have access to) and they don't tell you when the storm will stop (meaning they are basically encouraging you to never fix the breaches, or risk getting insta-gibbed by 2dev bombs. I witnessed this myself. The only two engineers interested in fixing things got killed and the two not interested in doing engineering tasks survived. You're encouraging terrible engineers.

Bring back the start and finish messages.

**Comment by Probe1** [comment]
Can you give a specific time for this because I suspect an admin pressed the silent meteor button.

**Comment by Kurfursten** [comment]
Nevermind, Jjenjr was literally just murdering the engineers trying to repair escape with meteors. Killed both of us with direct hits, I guess I should've known that wasn't a coincidence.

Manually threw 43 individual meteors of varying type to wreck the station around 10:22 PM last night, starting right after the shuttle was called.

**Comment by Probe1** [comment]
I can smell the adminabuse from a mile away.
