### ISSUE TITLE
Request: Code Levels

### ISSUE THREAD

**Issue by nuklearcellphoneg** [d3athrow/vgstation13#9999]
Hi. Can we make it so that anyone in Security can change the code level to Blue, or at least just the Warden and HoS, perhaps via the Security records console? And also add in a prompt which states:

'Advancing to Code Blue must be precipitated with evidence of the following: Murder, hostile alien activity(changelings, xenomorphs), occult activity(vampires, cultists), members of the Syndicate, blah blah blah', along with a text box in order to put a message which then gets sent to Centcomm(Admins)- this way we could determine pretty easily whether or not they went Code Blue just to valid hunt.

This is in order to give more weight to Green, Red, Blue code levels, level out escalation a bit, and hopefully do away with, 'omg he tased and searched me 4 no raisin and found my cult tome.', as well as empowering the stealth approach in some ways, as well as giving Security extra leeway once the round type has been exposed without-a-doubt.

**Comment by Shadowmech88** [comment]
I would also like it if there was literally any other way to trigger code red besides requiring two people with head-level access to be alive, because that's not always possible.
Maybe a button on the communications console that sends a request to Centcomm to have red-alert remote-triggered.

**Comment by Probe1** [comment]
we've talked about that before and the consensus, and my answer, was no.  hell no.  it would lead to abject levels of powergaming and the circumvention of server rules by instantly declaring code blue.

IMEANIGUESSITCOULDWORK if it had admin oversight but 
I doubt it.

**Comment by nuklearcellphoneg** [comment]
@Probe1 As opposed to what happens right now? 

 '...along with a text box in order to put a message which then gets sent to Centcomm(Admins)- this way we could determine pretty easily whether or not they went Code Blue just to valid hunt.'

'Advancing to Code Blue must be precipitated with evidence of the following: Murder, hostile alien activity(changelings, xenomorphs), occult activity(vampires, cultists), members of the Syndicate, blah blah blah' <---- They'd need to have direct evidence of one of these in order to initiate it, and if they bullshitted it, they'd get banned.

This is in conjunction with the rule rewrite: I'm trying to find ways of empowering security without holding their hand the whole time.
1. Security is expected to use non-lethal measures unless faced with lethal force or it's readily apparent the other party is capable of stunning. Stuns, due to the combat system, are considered lethal.

1a. Changelings, hulks, nuke ops, vampires, and cyborgs are ALWAYS considered to be capable of lethal force. Therefore, it's perfectly acceptable for lethal force to be used to stop them.

1b. Someone who has killed can be dealt with via lethal measures.
1. Permabrigging generally takes people out of the round. Reserve it for people whose Space Law punishment is Perma.
2. Space law is an IC set of rules. Not server rules. This means that when it comes to laws being broken, at the end of the day, there shouldn't really be ahelps about it. 

3a. If you broke the law and security has you detained for any valid reason, do not ahelp it unless you suspect they are cheating(metagaming, random searching on Code Green, etc) or griefing. If you ahelp and you are found at fault, you will progressively be banned for a day, week, month, and then permabanned.

3b. Conversely, if a member of Security IS griefing the crew as a nonantagonist, this will result in a Permaban from all Security roles.
1. On Alert levels: Under Green, Security must have a reason to act prior to acting. Someone being accused of a crime which has occurred or trespassing where they don't have access are reasons to begin to take action. 

Under Code Blue, however, random searches may be committed on anyone outside of their department, however, immediate tasing and so on are not allowed.

Under Code Red, Security is essentially given the free reign of an Antagonist, although they must act in good faith towards the crew, Nanotrasen, Space Law,and so on, they may K.O.S. those that are outside of the boundaries of their department and anyone who does not follow an order; if you hear their little speaker say 'HALT Security', stop, and lay down. If they tell you to stop and lay down, so. Depending on the circumstances, they may give you a warning beforehand, but they are allowed to kill any and all people who don't bend to the law.

4a. Under certain circumstances where the Code can not be changed, Security may take the appropriate action. It's best for the Security in question to ahelp before doing so. However, sometimes there is no time and action must be taken. Examples range from not having a Head to change the Code, due to murder, inactivity, or none signed up, or it being a Cult round, with Security being the last bastion of Non Cult. Again, it's very important to Ahelp prior to taking extreme measures, however, in such a situation it might be acceptable to announce and then act as though it were code red.
1. On Suspicious Behavior: They basically need to be either committing what appears to be a crime, OR they need to be in an area where they clearly have no access, i.e., an assistant does have access to maintenance, therefore they are allowed to be there, but they're not allowed in the adjoining solars control room. . If they can immediately prove they've been given access via the HoP, you must stand down.

Note: The above is a work in progress and not the final product.

**Comment by Killette2** [comment]
The problem with that is ICly there's no checks and balanced to security. IAA agents and lawyers mean fuckall, and nobody plays them seriously or often enough.

**Comment by Probe1** [comment]
an easy half way solution is to just add the HoS to the list of id requirements that can elevate the code and use the existing mechanisms.

**Comment by Shadowmech88** [comment]
I thought ANY head-level ID could change it to code blue.

**Comment by Probe1** [comment]
only cap.

**Comment by AutismSpider** [comment]
only cap for code blue (when it should be hop hos and cap for this)

Red is any two head ids

**Comment by Intigracy** [comment]
Blue should just be any head tbh.

If any head can put it up to code red with any other, surely they should be able to put it to code blue.

**Comment by nuklearcellphoneg** [comment]
Yes, any head should be able to knock it up to Code Blue. However:

Just like we added the required reason for calling the shuttle,  it would be nice to have the same for this.

**Comment by Hoshi-chan** [comment]
I like both of nuke's ideas. Particularly, changing the server rules to discourage ahelping legitimate imprisonment, as that also discourages admin involvement in IC issues and situations. The less admin involvement, the better.

It's definitely a move in the right direction, but space law as it exists is fucking awful. It's frequently abused by powertripping sec players to give people unreasonably long brig times and/or to put them in perma over minor offenses. Also, you can't necessarily expect every single player to be intimately familiar with space law to know that what they're being brigged for isn't legitimate (and, as such, not to ahelp it), as most sec players don't even bother to read it. I still have to chastise officers when they brig someone for longer than they would for assault because it's "assaulting an officer," or "assaulting a head."

As for code blue, what if instead of just adding a message requirement to code blue and lifting the requirements on who can initiate it, you moved it from the communications console to the same little card swiping consoles that you use to initiate code red. It makes more sense like that anyways.

**Comment by nuklearcellphoneg** [comment]
> As for code blue, what if instead of just adding a message requirement to code blue and lifting the requirements on who can initiate it, you moved it from the communications console to the same little card swiping consoles that you use to initiate code red. It makes more sense like that anyways.

---

I like that too, although I still wish any Security could upgrade the level if need be(this might would necessitate breaking into a head's office in the worst case scenario.

From the rewrite I'm doing on rules:

---
1. On Alert levels: Under Green, Security must have a reason to act prior to acting. Someone being accused of a crime which has occurred or trespassing where they don't have access are reasons to begin to take action, i.e., Suspicious Behavior.

Under Code Blue, however, random searches may be committed on anyone outside of their department or access level. You may not immediately stun and cuff while in a public area(hallways, so on), unless they disregard a command to halt.  In regards to people whose identity may be masked, shoot first, ask questions later may be observed.

Under Code Red, Security is essentially given the free reign of an Antagonist, although they must act in good faith towards the crew, basically enforcing Space Law and ensuring the safety of their crew mates.

---

will not work unless something like this is implemented, in which case I made:

---

4a. Under certain circumstances where the Code can not be changed, Security may take the appropriate action. It's best for the Security in question to ahelp before doing so. However, sometimes there is no time and action must be taken. Examples range from not having a Head to change the Code, due to murder, inactivity, or none signed up, or it being a Cult round, with Security being the last bastion of Non Cult. Again, it's very important to Ahelp prior to taking extreme measures, however, in such a situation it might be acceptable to announce and then act as though it were code red.

---

But, this, again, would necessitate admin intervention and is exactly what I'd like to move away from.

**Comment by ghost** [comment]
Oh god yes please. The it's code green! argument at least held a little water when any head could up it. Like say, a HoS passing through. Once we lost that it tumbled down a bit.

**Comment by Intigracy** [comment]
A+ idea to putting it on the keycard authentication devices.

**Comment by Imagebard** [comment]
Clone of #4178
But y'know just close that one.

**Comment by mrpain666** [comment]
I dont see the problem with it. Kinda retarded that the HEAD of SECURITY cant change the SECURITY LEVEL.

**Comment by Probe1** [comment]
As it turns out the code is already there but not working.

**Comment by Imagebard** [comment]
'Ere we go

**Comment by nuklearcellphoneg** [comment]
@PJB3005 Can we change the label to a bug related one? :^)

**Comment by mrpain666** [comment]
was this really issue #9999? If it was that should be a free ticket to every label and doing/fixing whatever it was for, let's be reasonable here.

**Comment by ghost** [comment]
The bug part of this has been closed, it's now a feature request as far as I can tell

**Comment by nuklearcellphoneg** [comment]
Hello..... :(

**Comment by DeityLink** [comment]
Is that still not a thing?

**Comment by Kammerjunk** [comment]
this is really old and should just be closed

**Comment by Shadowmech88** [comment]
It looks like all Command staff can do it, which should be good enough.
As Security, you can request that the HoS changes the code. If there is no HoS, become acting HoS and do it yourself.
If there's no HoS and there is no way whatsoever to get HoS access and you're in a situation where you think the code should be raised, you've probably got bigger problems than following Code Green etiquette.
